### ISSUE TITLE
[resovled] When a network fault occurs on one node, upload file very slow.

### ISSUE THREAD

**Issue by king-john** [minio/minio#10005]
I run the distributed minio of four nodes. When a network fault occurs on one node, upload file very slow.

## Expected Behavior

Files are uploaded quickly. 

## Current Behavior

Files are uploaded  is slow. 
## Steps to Reproduce (for bugs)

1. vi /etc/hosts ,add :
server-ip1    minio-server1
server-ip2    minio-server2
server-ip3    minio-server3
server-ip4    minio-server4
2. start minio
./minio server http://minio-server{1...4}/minio/data{1...4}
3.Inject a network fault to make a node server unreachable. 
4.upload file very slow.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-06-22T03-12-50Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version:  
* Operating System and version (`uname -a`): Ubuntu 18.04.2
* Link to your project:

**Comment by klauspost** [comment]
Upgrade to latest version which contains https://github.com/minio/minio/pull/9808 and re-test.

**Comment by klauspost** [comment]
It is inevitable that there will be an impact, but the PR above should ensure that the system will keep a server offline until it can positively be reached.

**Comment by klauspost** [comment]
@king-john

**Comment by harshavardhana** [comment]
This is already fixed in the latest release, upgrade is recommended .

**Comment by king-john** [comment]
@harshavardhana @klauspost 
Uploading files is still slow after the upgrade. 
I use cmd：blade create network drop --local-port 9000 --timeout 300
minio version RELEASE.2020-07-12T19-14-17Z

**Comment by king-john** [comment]
F5 minio Browser like this :
![image](https://user-images.githubusercontent.com/19261919/87282505-eb941100-c526-11ea-9843-f03b1b73930c.png)

**Comment by king-john** [comment]
It now looks like when I inject a network failure, the first upload is slow and may fail, and the next one is a quick success.

**Comment by klauspost** [comment]
Yes. That is the expected behaviour.

**Comment by king-john** [comment]
@klauspost 
I see # 9808.  
When a request returns an error. The client is marked offline. But it's gonna take a minute, right?

**Comment by klauspost** [comment]
@king-john Yes. There is no way of knowing if a non-responding server is just slow or if it is offline.

To avoid throwing servers offline all the time we need a reasonably long timeout to happen before we take it offline. Calls in that period will hang, waiting for a reply, but the server will remember that disk/server as being offline until it has been contacted again.

**Comment by king-john** [comment]
Thanks very much!
