### ISSUE TITLE
 Expected 'storage' API version 'v17', instead found 'a1', please upgrade the servers

### ISSUE THREAD

**Issue by deepPsixoz** [minio/minio#10006]
## Current Behavior
1. 、Console startup log:
minio_1  | Waiting for a minimum of 4 disks to come online (elapsed 17s)
minio_1  |
minio_1  | Unable to read 'format.json' from http://192.168.1.2:9000/mnt/data1: Expected 'storage' API version 'v17', instead found 'a1', please upgrade the servers
minio_1  |
minio_1  | Unable to read 'format.json' from http://192.168.1.3:9000/mnt/data1: Expected 'storage' API version 'v17', instead found 'a1', please upgrade the servers
minio_1  |
minio_1  | Unable to read 'format.json' from http://192.168.1.4:9000/mnt/data1: Expected 'storage' API version 'v17', instead found 'a1', please upgrade the servers
minio_1  |
minio_1  | Unable to read 'format.json' from http://192.168.1.5:9000/mnt/data1: Expected 'storage' API version 'v17', instead found 'a1', please upgrade the servers

2. The browser selects to create a bucket, and then prompts: Server not initialized, please try again

## Steps to Reproduce (for bugs)

My docker-compose.yml  file for deployment on 4 servers:

minio:
  image: minio/minio
  volumes:
    - /mnt/data1:/mnt/data1
    - /mnt/data2:/mnt/data2
  ports:
    - "{{ minio_port }}:9000"
  environment:
    MINIO_ACCESS_KEY: {{ minio_user }}
    MINIO_SECRET_KEY: {{ minio_password }}
  command: server --address :9000 http://192.168.1.{1...4}/mnt/data1{1...2} 

## Your Environment
minio version RELEASE.2020-07-02T00-15-09Z
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build unknown
Linux rhel-cert-02 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This clearly looks like some other service is running on port 9000 or there is a proxy in between.

Can you use a different port or fix your local environment?

**Comment by harshavardhana** [comment]
Use the latest release https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z
