### ISSUE TITLE
ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: permission denied

### ISSUE THREAD

**Issue by mergewreck** [minio/minio#10008]
docs suggest that the .minio.xxx dirs should be user based and not sure why is / which is not writable

## Steps to Reproduce (for bugs)
$ curl -O https://dl.min.io/server/minio/release/darwin-amd64/minio
$ chmod +x minio

## Current Behavior
$ MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin ./minio gateway hdfs
ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: permission denied

## Your Environment
$ ./minio --version
minio version RELEASE.2020-07-02T00-15-09Z

$ uname -a
Darwin CHI-EN-21YJGH5 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
You should provide a custom path to hdfs if you don't want us to use /tmp , we cannot really autoguess this neither hdfs is able to provide us the actual rootpath for a user.

just use `minio gateway hdfs hdfs://namenode/path`

**Comment by mergewreck** [comment]
hdfs://namenode/path does not change the directory minio uses

$ minio gateway hdfs hdfs://namenode/path 

still writes to /.minio.sys/tmp

minio should root the gateway at the /path which includes .minio.sys/tmp files, as well buckets should be relative to /path
