### ISSUE TITLE
[not our bug] MINIO + STS https://github.com/minio/minio/blob/master/docs/sts/web-identity.md Issue.

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio#10001]
## Current Behavior
In continuation with #9976 The server configuration with OpenID works sometimes in Windows and sometimes it gives un trusted certificate. 

But when the server connects on windows or linux, UI login with OpenID is working but post request mentioned in https://github.com/minio/minio/blob/master/docs/sts/web-identity.md, which is http://minio.cluster:9000?Action=AssumeRoleWithWebIdentity&DurationSeconds=3600&WebIdentityToken=eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJQb0VnWFA2dVZPNDVJc0VOUm5nRFhqNUF1NVlhIiwiYXpwIjoiUG9FZ1hQNnVWTzQ1SXNFTlJuZ0RYajVBdTVZYSIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6MTU0MTgwOTU4MiwiaWF0IjoxNTQxODA1OTgyLCJqdGkiOiI2Y2YyMGIwZS1lNGZmLTQzZmQtYTdiYS1kYTc3YTE3YzM2MzYifQ.Jm29jPliRvrK6Os34nSK3rhzIYLFjE__zdVGNng3uGKXGKzP3We_i6NPnhA0szJXMOKglXzUF1UgSz8MctbaxFS8XDusQPVe4LkB_45hwBm6TmBxzui911nt-1RbBLN_jZIlvl2lPrbTUH5hSn9kEkph6seWanTNQpz9tNEoVa6R_OX3kpJqxe8tLQUWw453A1JTwFNhdHa6-f1K8_Q_eEZ_4gOYINQ9t_fhTibdbkXZkJQFLop-Jwoybi9s4nwQU_dATocgcufq5eCeNItQeleT-23lGxIz0X7CiJrJynYLdd-ER0F77SumqEb5iCxhxuf4H7dovwd1kAmyKzLxpw&Version=2011-06-15,
Gives below error,

```
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <Error>
        <Type></Type>
        <Code>InvalidParameterValue</Code>
        <Message>crypto/rsa: verification error</Message>
    </Error>
    <RequestId>161FB922BCC96904</RequestId>
</ErrorResponse><!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
```
1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):2020-07-02T00:15:09Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):Windows 10 Enterprise/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
> <?xml version="1.0" encoding="UTF-8"?>
> <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
>     <Error>
>         <Type></Type>
>         <Code>InvalidParameterValue</Code>
>         <Message>crypto/rsa: verification error</Message>

This entirely looks like your RSA key is corrupt something is maliciously modifying the signature

```
// ErrVerification represents a failure to verify a signature.
// It is deliberately vague to avoid adaptive attacks.
var ErrVerification = errors.New("crypto/rsa: verification error")
```

**Comment by PSHREYASHOLLA** [comment]
> > `InvalidParameterValue`
> >         crypto/rsa: verification error
> 
> This entirely looks like your RSA key is corrupt something is maliciously modifying the signature
> 
> ```
> // ErrVerification represents a failure to verify a signature.
> // It is deliberately vague to avoid adaptive attacks.
> var ErrVerification = errors.New("crypto/rsa: verification error")
> ```

Can you elaborate why MINIO is unable to resolve the same? As I am able to use the same web identity token(JWT) to get the access token with other applications.

**Comment by harshavardhana** [comment]
> Can you elaborate why MINIO is unable to resolve the same? As I am able to use the same web identity token(JWT) to get the access token with other applications.

I don't know @PSHREYASHOLLA

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana @kannappanr  Can you please confirm if MinIO + Azure(OpenID) will work? As the same is our requirement and based on this I have to contact my Product Management team with my analysis.

**Comment by harshavardhana** [comment]
> @harshavardhana @kannappanr  Can you please confirm if MinIO + Azure(OpenID) will work? As the same is our requirement and based on this I have to contact my Product Management team with my analysis.

Yes it will work, you need to first understand the requirement of requesting custom claims from the Azure AD.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana  With same userID/Password I am able to login to MinIO from  browser using same Azure AD, then why is it failing for PostRequest?

**Comment by harshavardhana** [comment]
> @harshavardhana  With same userID/Password I am able to login to MinIO from  browser using same Azure AD, then why is it failing for PostRequest?

Because browser uses implicit flow, POST request requires auth flow. You need to check how to do that in Azure AD.

Do not have access to an environment test this for you.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana 

> > @harshavardhana  With same userID/Password I am able to login to MinIO from  browser using same Azure AD, then why is it failing for PostRequest?
> 
> Because browser uses implicit flow, POST request requires auth flow. You need to check how to do that in Azure AD.
> 
> Do not have access to an environment test this for you.

But as mentioned here, https://github.com/minio/minio/blob/master/docs/sts/web-identity.md, the custom policy in JWT token is required for UI Browser login. Can you clarify that

**Comment by harshavardhana** [comment]
> @harshavardhana
> 
> > > @harshavardhana  With same userID/Password I am able to login to MinIO from  browser using same Azure AD, then why is it failing for PostRequest?
> > 
> > 
> > Because browser uses implicit flow, POST request requires auth flow. You need to check how to do that in Azure AD.
> > Do not have access to an environment test this for you.
> 
> But as mentioned here, https://github.com/minio/minio/blob/master/docs/sts/web-identity.md, the custom policy in JWT token is required for UI Browser login. Can you clarify that

Yes of course that is meant for authorization not authentication, authentication becomes implicit when server can verify the received JWT is authentic.

You will not have access to data from browser without policy.

**Comment by harshavardhana** [comment]
Login flow has two stages

- Authentication - AuthN (configuring server with proper openid discovery document which provides us JWKS URL which verifies the authenticity of JWT payload)
- Authorization - AuthZ (policy claim needed)

So you may successfully login, but not successfully access the data. Without policy all authentication is implicitly denied.

**Comment by harshavardhana** [comment]
Reproduced the `crypto/rsa` can you tell me if you are using Access Token or ID Token here as JWT to send to MinIO?

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana We are using Access Token.

**Comment by harshavardhana** [comment]
> @harshavardhana We are using Access Token.

Can you try with id_token ? @PSHREYASHOLLA

**Comment by PSHREYASHOLLA** [comment]
> > @harshavardhana We are using Access Token.
> 
> Can you try with id_token ? @PSHREYASHOLLA

Tried with id_token getting below error,
`<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <Error>
        <Type></Type>
        <Code>InvalidParameterValue</Code>
        <Message>Invalid kid value &lt;nil&gt;</Message>
    </Error>
    <RequestId>16227AA579D0F839</RequestId>
</ErrorResponse>`

**Comment by harshavardhana** [comment]
> `<?xml version="1.0" encoding="UTF-8"?> <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"> <Error> <Type></Type> <Code>InvalidParameterValue</Code> <Message>Invalid kid value &lt;nil&gt;</Message> </Error> <RequestId>16227AA579D0F839</RequestId> </ErrorResponse>`

This looks like the kid is missing from the JWT claims for us to validate the token, the previous one with access_token the kid is present but the signature is wrong.

I suspect there is some issue in terms of OpenID discovery URL i.e your discovery URL pointing to MinIO is different than the one your application is using for authorization endpoint. 

Can you confirm that the discovery document authorization endpoint? presented to MinIO is the same as the one your application is using to generate access_token?

**Comment by PSHREYASHOLLA** [comment]
> > `<?xml version="1.0" encoding="UTF-8"?> <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"> <Error> <Type></Type> <Code>InvalidParameterValue</Code> <Message>Invalid kid value &lt;nil&gt;</Message> </Error> <RequestId>16227AA579D0F839</RequestId> </ErrorResponse>`
> 
> This looks like the kid is missing from the JWT claims for us to validate the token, the previous one with access_token the kid is present but the signature is wrong.
> 
> I suspect there is some issue in terms of OpenID discovery URL i.e your discovery URL pointing to MinIO is different than the one your application is using for authorization endpoint.
> 
> Can you confirm that the discovery document authorization endpoint? presented to MinIO is the same as the one your application is using to generate access_token?

Yes have cross checked the same and the configurations are proper. With access_token getting rsa error and with id_token getting kid missing

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana  Can you confirm what is MinIO expecting access_token or id_token or any one of two is accepted?

**Comment by harshavardhana** [comment]
The issue looks like MSFT being non IETF compliant, lets see if we can fix this on our end but this is super non-compliant behavior from MSFT which leads to this issue. 

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609#issuecomment-430741177

```
At the end of the day, Msft (Azure AD) is currently generating JWT Tokens that fail signature validation.

Therefore Msft is non-IETF compliant by failing to generate valid JWT Tokens, eg tokens which can be validated by their provided signature.

So, when will Msft fix this?
```

**Comment by harshavardhana** [comment]
Here is the solution https://medium.com/@abhinavsonkar/making-azure-ad-oidc-compliant-5734b70c43ff

```
We need to tell Azure AD that the token we need is not for Graph API but an API of our own. To achieve this, a custom scope should be created in the App Registration → Expose an API page. You can name this scope whatever you like. Then make sure to add this scope in the authorization request initiated by the client along with the default openid scope.
This forces Azure to return a JWT token without the post-processed nonce claim which results in an access token that can be validated as per the spec.
```

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana Will try the above solution but can you confirm what is MinIO expecting access_token or id_token or any one of two is accepted?

**Comment by harshavardhana** [comment]
> @harshavardhana Will try the above solution but can you confirm what is MinIO expecting access_token or id_token or any one of two is accepted?

It's not MinIO you need to provide us JWT token which can be validated I do not know what MSFT is doing here, as far their clunky implementation.  I have a solution referenced which indicates that access_token is the correct approach after you have enabled the scopes.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana 

As mentioned here https://medium.com/@abhinavsonkar/making-azure-ad-oidc-compliant-5734b70c43ff, created Scopes and tried passing the access_token and id_token, but the issue remains same,

For access_token,
// ErrVerification represents a failure to verify a signature.
// It is deliberately vague to avoid adaptive attacks.
var ErrVerification = errors.New("crypto/rsa: verification error")

And for id_token,
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <Error>
        <Type></Type>
        <Code>InvalidParameterValue</Code>
        <Message>Invalid kid value &lt;nil&gt;</Message>
    </Error>
    <RequestId>16259E6F3CD54577</RequestId>
</ErrorResponse>

**Comment by harshavardhana** [comment]
> @harshavardhana
> 
> As mentioned here https://medium.com/@abhinavsonkar/making-azure-ad-oidc-compliant-5734b70c43ff, created Scopes and tried passing the access_token and id_token, but the issue remains same,
> 
> For access_token,
> // ErrVerification represents a failure to verify a signature.
> // It is deliberately vague to avoid adaptive attacks.
> var ErrVerification = errors.New("crypto/rsa: verification error")
> 
> And for id_token,
> 
> `InvalidParameterValue` Invalid kid value <nil> 16259E6F3CD54577

Now the issue here is that your JWKS URL is wrong. Azure AD looks severely broken we cannot support non compliant OIDC server.

You need to talk to Azure AD support here.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana  So are you telling MinIO is not supported with Azure AD? And can you tell me what API is being used to validate the JWT token sent to MinIO, so that the I can take up the same with Azure AD support team?

**Comment by harshavardhana** [comment]
> @harshavardhana So are you telling MinIO is not supported with Azure AD? And can you tell me what API is being used to validate the JWT token sent to MinIO?

@PSHREYASHOLLA I am saying there is enough evidence that Azure AD is broken and not OIDC compliant by default - we cannot support entities that are not OIDC compliant.

I already shared how you can make it OIDC compliant it seems like something is broken beyond that, this is out of scope for MinIO. You need to talk to Azure AD folks to provide proper JWT tokens which can be verified. 

Please share them all the links shared here to get their guidance.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana  Thanks for all data, I will definitely take this up with Azure Support, but can you tell me how the passed JWT is getting validated from MinIO so that we have clear picture?

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for all data, I will definitely take this up with Azure Support, but can you tell me how the passed JWT is getting validated from MinIO so that we have clear picture?

https://github.com/minio/minio/blob/master/cmd/config/identity/openid/jwt.go#L170

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana Thanks for the information, will check that.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana, Was trying with Keycloak as webidentity provider. Here was able to get the AssumeRoleWithWebIdentityResponse,

<?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithWebIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <AssumeRoleWithWebIdentityResult>
        <AssumedRoleUser>
            <Arn></Arn>
            <AssumeRoleId></AssumeRoleId>
        </AssumedRoleUser>
        <Credentials>
            <AccessKeyId>FT8P56JOXAJDUCWEYWCP</AccessKeyId>
            <SecretAccessKey>0aIZ6OhJxkvbxYy+9J20llgrV8JRCG+LtzwKkH8h</SecretAccessKey>
            <Expiration>2020-08-05T14:17:30Z</Expiration>
            <SessionToken>eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJGVDhQNTZKT1hBSkRVQ1dFWVdDUCIsImFjciI6IjEiLCJhZGRyZXNzIjp7fSwiYXVkIjoiYWNjb3VudCIsImF6cCI6Im1pbmlvIiwiZW1haWwiOiJicmFkQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZXhwIjoxNTk2NjM3MDUwLCJmYW1pbHlfbmFtZSI6ImJyYWQiLCJnaXZlbl9uYW1lIjoiYnJhZCIsImdyb3VwcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl0sImlhdCI6MTU5NjYzNjc1MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL21hc3RlciIsImp0aSI6ImI5ODE5ZWE1LTI1NDUtNDVlNi05Y2ZiLWIwM2JkMTY0MDFlNyIsIm5hbWUiOiJicmFkIGJyYWQiLCJwb2xpY3kiOiJyZWFkd3JpdGUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJicmFkIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIHBob25lIGFkZHJlc3MgcG9saWN5IG1pY3JvcHJvZmlsZS1qd3Qgb2ZmbGluZV9hY2Nlc3MiLCJzZXNzaW9uX3N0YXRlIjoiOWU4ODI5YmYtMjJmNy00ZGNiLWIxNmItOTg4NGQ3NDdjMDZiIiwic3ViIjoiMTAzMTJjMjktZWYxYi00OWNmLTg0ZjQtODQ1MGZiNDZkNDM5IiwidHlwIjoiQmVhcmVyIiwidXBuIjoiYnJhZCJ9.E0Fp-jUXjKMrGSPAN07CLu69Z9pgG0DOuUVbF0Mm--G7a3Q2O9qr37UwnY5HraIfU91qtnR91vDFHQyQ6LpBBQ</SessionToken>
        </Credentials>
        <SubjectFromWebIdentityToken>10312c29-ef1b-49cf-84f4-8450fb46d439</SubjectFromWebIdentityToken>
    </AssumeRoleWithWebIdentityResult>
    <ResponseMetadata>
        <RequestId>162864D6A17B57F8</RequestId>
    </ResponseMetadata>
</AssumeRoleWithWebIdentityResponse>


But when I use the  <AccessKeyId>FT8P56JOXAJDUCWEYWCP</AccessKeyId> and
            <SecretAccessKey>0aIZ6OhJxkvbxYy+9J20llgrV8JRCG+LtzwKkH8h</SecretAccessKey> in JAVA SDK API like,

	MinioClient minioClient = new MinioClient("http://localhost:9000","FT8P56JOXAJDUCWEYWCP","0aIZ6OhJxkvbxYy+9J20llgrV8JRCG+LtzwKkH8h");
minioClient.listBuckets();

Getting below error,

Exception in thread "main" java.lang.IllegalArgumentException: unknown error code string 'InvalidTokenId'
	at io.minio.Xml.unmarshal(Xml.java:68)
	at io.minio.MinioClient.execute(MinioClient.java:1134)
	at io.minio.MinioClient.executeGet(MinioClient.java:1311)
	at io.minio.MinioClient.listBuckets(MinioClient.java:3123)
	at com.misys.dms.Main.main(Main.java:48)

**Comment by harshavardhana** [comment]
> @harshavardhana, Was trying with Keycloak as webidentity provider. Here was able to get the AssumeRoleWithWebIdentityResponse,
> 
> FT8P56JOXAJDUCWEYWCP 0aIZ6OhJxkvbxYy+9J20llgrV8JRCG+LtzwKkH8h 2020-08-05T14:17:30Z eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJGVDhQNTZKT1hBSkRVQ1dFWVdDUCIsImFjciI6IjEiLCJhZGRyZXNzIjp7fSwiYXVkIjoiYWNjb3VudCIsImF6cCI6Im1pbmlvIiwiZW1haWwiOiJicmFkQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZXhwIjoxNTk2NjM3MDUwLCJmYW1pbHlfbmFtZSI6ImJyYWQiLCJnaXZlbl9uYW1lIjoiYnJhZCIsImdyb3VwcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl0sImlhdCI6MTU5NjYzNjc1MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL21hc3RlciIsImp0aSI6ImI5ODE5ZWE1LTI1NDUtNDVlNi05Y2ZiLWIwM2JkMTY0MDFlNyIsIm5hbWUiOiJicmFkIGJyYWQiLCJwb2xpY3kiOiJyZWFkd3JpdGUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJicmFkIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIHBob25lIGFkZHJlc3MgcG9saWN5IG1pY3JvcHJvZmlsZS1qd3Qgb2ZmbGluZV9hY2Nlc3MiLCJzZXNzaW9uX3N0YXRlIjoiOWU4ODI5YmYtMjJmNy00ZGNiLWIxNmItOTg4NGQ3NDdjMDZiIiwic3ViIjoiMTAzMTJjMjktZWYxYi00OWNmLTg0ZjQtODQ1MGZiNDZkNDM5IiwidHlwIjoiQmVhcmVyIiwidXBuIjoiYnJhZCJ9.E0Fp-jUXjKMrGSPAN07CLu69Z9pgG0DOuUVbF0Mm--G7a3Q2O9qr37UwnY5HraIfU91qtnR91vDFHQyQ6LpBBQ 10312c29-ef1b-49cf-84f4-8450fb46d439 162864D6A17B57F8
> But when I use the FT8P56JOXAJDUCWEYWCP and
> 0aIZ6OhJxkvbxYy+9J20llgrV8JRCG+LtzwKkH8h in JAVA SDK API like,
> 
> ```
> MinioClient minioClient = new MinioClient("http://localhost:9000","FT8P56JOXAJDUCWEYWCP","0aIZ6OhJxkvbxYy+9J20llgrV8JRCG+LtzwKkH8h");
> ```
> 
> minioClient.listBuckets();
> 
> Getting below error,
> 
> Exception in thread "main" java.lang.IllegalArgumentException: unknown error code string 'InvalidTokenId'
> at io.minio.Xml.unmarshal(Xml.java:68)
> at io.minio.MinioClient.execute(MinioClient.java:1134)
> at io.minio.MinioClient.executeGet(MinioClient.java:1311)
> at io.minio.MinioClient.listBuckets(MinioClient.java:3123)
> at com.misys.dms.Main.main(Main.java:48)

You didn't specify the session token @PSHREYASHOLLA

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana, I am using  "new io.minio.MinioClient(endPoint,accessKey,secretKey);" from JAVA SDK minio-7.0.2-all.jar.
I did not see any API acceptiong sessionToken, where to pass the same in API?

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana You want me to raise a separate issue for the same?

**Comment by harshavardhana** [comment]
> @harshavardhana, I am using "new io.minio.MinioClient(endPoint,accessKey,secretKey);" from JAVA SDK minio-7.0.2-all.jar.
> I did not see any API acceptiong sessionToken, where to pass the same in API?

We have moved on to 7.1 which supports session tokens you should look at the latest API @PSHREYASHOLLA

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana, Thanks for the information, will check the 7.1 SDK jar. So this API is now not backward compatible?

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana, Tried with minio-7.0.1.jar, and API I can find is  MinioClient.builder().endpoint(hostURL).credentials(accessKey,secretKey). Not finding where to pass session token, can you guide me to documentation?

**Comment by harshavardhana** [comment]
> @harshavardhana, Tried with minio-7.0.1.jar, and API I can find is MinioClient.builder().endpoint(hostURL).credentials(accessKey,secretKey). Not finding where to pass session token, can you guide me to documentation?

Ah yes my bad its not released yet https://github.com/minio/minio-java/tree/master/api/src/main/java/io/minio/credentials we plan to release it soon.

**Comment by PSHREYASHOLLA** [comment]
> > @harshavardhana, Tried with minio-7.0.1.jar, and API I can find is MinioClient.builder().endpoint(hostURL).credentials(accessKey,secretKey). Not finding where to pass session token, can you guide me to documentation?
> 
> Ah yes my bad its not released yet https://github.com/minio/minio-java/tree/master/api/src/main/java/io/minio/credentials we plan to release it soon.

So for now MinIO + OpenID will not work?

**Comment by harshavardhana** [comment]
> So for now MinIO + OpenID will not work?

@PSHREYASHOLLA I would suggest you use our https://slack.min.io for further questions and answers. GitHub issues are not a forum.  I am going to lock this issue as resolved.
