### ISSUE TITLE
[working as intented] Numeric name directories are not mounted on Minio

### ISSUE THREAD

**Issue by igtm** [minio/minio#10017]
## Expected Behavior

Any file name directories should be properly mounted.

## Current Behavior

Numeric name directories are not mounted on Minio.

## Possible Solution

I'm not sure. but something like `ListDir` function might cause this bug?

## Steps to Reproduce (for bugs)

- create 2 files. `1` and `1aaa`

<img width="179" alt="スクリーンショット 2020-07-11 13 00 36" src="https://user-images.githubusercontent.com/6331737/87216046-d1b3cc00-c376-11ea-9894-5d799c71e2fb.png">

- but you can see only `1aaa` on minio

![スクリーンショット 2020-07-11 13 01 03](https://user-images.githubusercontent.com/6331737/87216045-d0829f00-c376-11ea-9d38-a6b822aea4f4.png)

## Context

We have numeric directories.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
docker image `sha256:5e44d63679823a3dd15f27d6b6ba00dbc429a387faf3abaad4f5d2105d2e1efb`

**Comment by harshavardhana** [comment]
yes minimum requirement for bucket name is minimum '3' characters as per AWS S3 bucket naming guidelines, these directories are ignored automatically - just rename these directories  > 3 characters.

**Comment by igtm** [comment]
Oh! Thank you for your quick response! I got it
