### ISSUE TITLE
[resolved] minio gateway hdfs hdfs://namenode/path does not use /path

### ISSUE THREAD

**Issue by mergewreck** [minio/minio#10011]
See [/issues/10008] ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: permission denied

The justification to close the ticket does not work

i.e, "just use minio gateway hdfs hdfs://namenode/path"

hdfs://namenode/path does not change the directory minio uses

$ minio gateway hdfs hdfs://namenode/path

still writes to /.minio.sys/tmp

minio should root the gateway at the /path which includes .minio.sys/tmp files, as well, buckets should be relative to /path

From the comment on [/issues/10008] it sounds like that is the way it is supposed to work?

**Comment by harshavardhana** [comment]
Not supported yet we may add it in future - thanks for the bug report.
