### ISSUE TITLE
[resolved] Update minio gateway hdfs documentation to clarify limitations and roadmap- Especially regarding multipart upload

### ISSUE THREAD

**Issue by mergewreck** [minio/minio#10013]
See [/issues/10012]

Update minio gateway hdfs documentation to clarify limitations and roadmap- Especially regarding multipart upload

https://docs.min.io/docs/minio-gateway-for-hdfs.html

**Known limitations**
Gateway inherits the following limitations of HDFS storage layer:

No bucket policy support (HDFS has no such concept)
No bucket notification APIs are not supported (HDFS has no support for fsnotify)
No server side encryption support (Intentionally not implemented)
No server side compression support (Intentionally not implemented)

**Roadmap**
Additional metadata support for PutObject operations
Additional metadata support for Multipart operations
Background append to provide concurrency support for multipart operations

That is different than

_"Multipart is not supported on purpose HDFS gateway is designed for repatriation of data from HDFS to MinIO its scope is not to perpetually continue to use HDFS"_

Please clarify, as above suggests multipart is supported, and it is to a degree. But parallel multipart upload is not.

As noted in [/issues/10012] A standard s3 api which can support s3 and hdfs (via gateway) is of great value in supporting cases where both are used- especially a case in which one is moving to s3 (and s3 apis) while moving away from hdfs. mc mirror only satisfies migration at the data laye, not the api layer.

**Comment by mergewreck** [comment]
Also note that minio client impl will automatically multipart behind scenes- so if not intended to be used with gateway that is a case for confusion. I do wonder if the gateway has the same 5gb upload limitation as s3. I would like to use same api impl to upload data whether historical hdfs or s3. Was looking into the hdfs gateway as an option for that.

**Comment by harshavardhana** [comment]
> Also note that minio client impl will automatically multipart behind scenes- so if not intended to be used with gateway that is a case for confusion. I do wonder if the gateway has the same 5gb upload limitation as s3. I would like to use same api impl to upload data whether historical hdfs or s3. Was looking into the hdfs gateway as an option for that.

you can use `mc cp --disable-multipart` FWIW

**Comment by harshavardhana** [comment]
Doc being addressed in #10014

**Comment by harshavardhana** [comment]
Doc updated closing.
