### ISSUE TITLE
lifecycle configuration - cannot create multiple rules for the same filter prefix

### ISSUE THREAD

**Issue by findmyname666** [minio/minio#10027]
I planned to create general lifecycle configuration for all object in a bucket. My idea is to use several lifecycle rules on the bucket level e.g. no prefix specified in the filter section. The rules are unique as they contain different expiration periods and they match objects based on filter's tags. Specifically i tried to create lifecycle configuration for weekly expiration of objects e.g. if an object is tagged with value 1week it will expire after 7 days, 2 weeks == 14 days and so on ....

## Expected Behavior

MinIO shouldn't fail to create lifecycle configuration when there are multiple lifecycle rules for the same prefix. I created the same configuration on AWS without issues. There is also similar example in [S3 AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html), section "Example 1: Overlapping prefixes (no conflict)".
```
<LifecycleConfiguration>
  <Rule>
    <ID>Rule 1</ID>
    <Filter>
    </Filter>
    <Status>Enabled</Status>
    <Expiration>
      <Days>365</Days>
    </Expiration>
  </Rule>
  <Rule>
    <ID>Rule 2</ID>
    <Filter>
      <Prefix>logs/</Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Transition>
      <StorageClass>STANDARD_IA<StorageClass>
      <Days>30</Days>
    </Transition>
   </Rule>
</LifecycleConfiguration>
```

## Current Behavior

The request failed. Error received by client -> `failed to set lifecycle policy, Lifecycle configuration has rules with overlapping prefix`.
Error from MinIO server logs:
```
API: PutBucketLifecycle(bucket=esdump)
Time: 22:24:05 CEST 07/12/2020
DeploymentID: 5ec00ac9-5352-4961-a856-275a220e14dd
RequestID: 16211B03B626B413
RemoteHost: 127.0.0.1
Host: localhost:9001
UserAgent: MinIO (linux; amd64) minio-go/v6.0.57
Error: Lifecycle configuration has rules with overlapping prefix
       4: github.com/minio/minio@/cmd/api-errors.go:1875:cmd.toAPIErrorCode()
       3: github.com/minio/minio@/cmd/api-errors.go:1900:cmd.toAPIError()
       2: github.com/minio/minio@/cmd/bucket-lifecycle-handlers.go:77:cmd.objectAPIHandlers.PutBucketLifecycleHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Possible Solution

As far i see AWS S3 allows rules with overlapping prefixes therefore i don't see reason for this sanity checking.

## Steps to Reproduce (for bugs)

1. Run MinIO server.
```
./minio server --address 127.0.0.1:9001  ./data
```
2. Create some test bucket. 
3. Try to set lifecycle configuration for the test bucket. Lifecycle configuration should contain multiple rules (>1) for the same filter prefix. Example configuration:
```
<LifecycleConfiguration><Rule><ID>1week</ID><Filter><Prefix></Prefix><Tag><Key>weekly_expiration</Key><Value>1</Value></Tag></Filter><Status>Enabled</Status><Expiration><Days>7</Days></Expiration></Rule><Rule><ID>2week</ID><Filter><Prefix></Prefix><Tag><Key>weekly_expiration</Key><Value>2</Value></Tag></Filter><Status>Enabled</Status><Expiration><Days>14</Days></Expiration></Rule></LifecycleConfiguration>
``` 

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2020-07-02T00-15-09Z
```
* Server setup and configuration:
Running standlone MinIO server:
```
./minio server --address 127.0.0.1:9001  ./data
```
* Operating System and version (`uname -a`):
```
Linux noname 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
Fixed by #10053
