### ISSUE TITLE
[resolved] DNS style bucket is broken after minio/minio:RELEASE.2020-07-02T00-15-09Z

### ISSUE THREAD

**Issue by BoleynSu** [minio/minio#10023]
## Expected Behavior

When MINIO_DOMAIN is set, dns style bucket should work.

## Current Behavior

It is not working.

## Steps to Reproduce (for bugs)

With the latest image, it is broken and pinning to minio/minio:RELEASE.2020-07-02T00-15-09Z will make it work.

## Regression

Yes. minio/minio:RELEASE.2020-07-02T00-15-09Z works fine,

## Your Environment

k3s on Fedora CoreOS

**Comment by harshavardhana** [comment]
Needs one more fix from gorilla/mux upstream issue

**Comment by BoleynSu** [comment]
Thanks for fixing it.
