### ISSUE TITLE
Expose last crawl time, duration and next crawl time

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio#10028]
**Is your feature request related to a problem? Please describe.**
Currently it's very hard to figure out when a lifecycle check or a crawl in general happens. I noticed that it even depends on how long the previous run took. We have many small files and with a debug run I noticed that it's going very slow. I'm missing a way to find out when the last run was, how long the last run took (probably also add an average) and when I can expect the next run to be. This would make it more transparent and if some performance issues need to be debugged it can be checked if crawling might be the reason for that.

**Describe the solution you'd like**
Maybe this can be included into the information provided by mc admin info?
Something like:
```
●  play.minio.io
   Uptime: 11 hours
   Version: 2020-01-17T22:08:02Z
   Network: 1/1 OK
   Drives: 4/4 OK
   Last Dara Crawl start: 2020-06-17T22:08:02Z (Duration: 1 hour)
   Next Dara Crawl start: 2020-06-18T09:08:02Z
```

If a crawl is in progress and next crawl info isn't available maybe show infos about how long it is already running instead

```
●  play.minio.io
   Uptime: 11 hours
   Version: 2020-01-17T22:08:02Z
   Network: 1/1 OK
   Drives: 4/4 OK
   Last Crawl start: 2020-06-18T09:08:02Z (Running: 30 min)
   Next Crawl start: (crawling in progress)
```

**Describe alternatives you've considered**
Maybe this can also be included into prometheus metrics.

**Comment by harshavardhana** [comment]
We have moved away from this model some time ago @WolfspiritM our crawler and lifecycle are continuous now and always running at very low priority threads.

You are advised to upgrade as this feature is not that useful anymore.

**Comment by WolfspiritM** [comment]
@harshavardhana Thanks. The version in my example is just from the docs page about mc admin info. I'm using the version from about 11 days ago. I think I got the docs wrong for MINIO_DISK_USAGE_CRAWL_DELAY then. I thought if the whole crawl operation takes 1 hour then it will wait 10 hours for the next crawl. But after reading it again I think it's If the previous file deletion took e.g. 1 second then with a MINIO_DISK_USAGE_CRAWL_DELAY of 10 it will wait for 10 seconds before doing the next file deletion. That explains why I'm seeing very "slow" lifecycle cleanup and I should be able to make that progress faster with decreasing that delay.

Is there any way to figure out how long a full crawl takes until it's starting back at the beginning? That value might still be helpful for larger systems I think to make sure if the MINIO_DISK_USAGE_CRAWL_DELAY is set correctly. Something like "Full/Average crawl duration".

But it's not that vital if it keeps crawling all the time so I'm closing this issue. Thanks again!

**Comment by harshavardhana** [comment]
> Is there any way to figure out how long a full crawl takes until it's starting back at the beginning? That value might still be helpful for larger systems I think to make sure if the MINIO_DISK_USAGE_CRAWL_DELAY is set correctly. Something like "Full/Average crawl duration".

Nope, there is no way to know precisely, since crawl will suspend itself there are active I/O in progress @WolfspiritM - it also cannot predict how many files might exist in a directory or bucket so it can clearly be never accurate.

**Comment by klauspost** [comment]
> That explains why I'm seeing very "slow" lifecycle cleanup and I should be able to make that progress faster with decreasing that delay.

Correct. That is why the variable is exposed. Of course increasing this may have a negative effect on your cluster since more resources will be used for scanning.

Also, there is a max wait of one second between operations, so it will progress, albeit *very* slowly on a heavily loaded cluster.
