### ISSUE TITLE
[resolved] After restarting the service, the user list is not loaded correctly

### ISSUE THREAD

**Issue by manors** [minio/minio#10022]
Add two or more users, then restart the service. Only the first user will be loaded.

## Expected Behavior
All users should be loaded, even if the service is restarted.

## Current Behavior
Only the first user will be loaded.

## Steps to Reproduce (for bugs)

$ mc admin user add local test1 11111111
Added user `test1` successfully.
$ mc admin user add local test2 11111111
Added user `test2` successfully.
$ mc admin user list local
enabled    test1
enabled    test2
$ mc admin service restart local
Restart command successfully sent to `local`.
Restarted `local` successfully.
$ mc admin user list local
enabled    test1
$

## Your Environment

* Version used (`minio --version`): RELEASE.2020-07-11T06-07-16Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux 1-v2 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Users are loaded asynchronously, and it should show up after all the servers quorum is established. 

Do you not see that ?

**Comment by manors** [comment]
Just use in single server mode, still not loaded in about 10 minutes.
I don't think it's a problem of asynchronous loading, I can repeat this problem on different machines. Only the latest version will have this problem.

minio start param: server /data{1...4}

**Comment by BoleynSu** [comment]
I have seen the same issue. I guess both of us are using minio/minio:latest.

After pinning to minio/minio:RELEASE.2020-07-02T00-15-09Z, the users are back.

The latest image also breaks DNS style bucket. I guess you should have more tests to make sure releases will not break existing deployments.

**Comment by harshavardhana** [comment]
> The latest image also breaks DNS style bucket. I guess you should have more tests to make sure releases will not break existing deployments.

DNS style buckets were fixed #10010 due to an upstream regression @BoleynSu 

> Just use in single server mode, still not loaded in about 10 minutes.
> I don't think it's a problem of asynchronous loading, I can repeat this problem on different machines. Only the latest version will have this problem.
> 
> minio start param: server /data{1...4}

That doesn't make sense @manors let me check on my end.

**Comment by manors** [comment]
> I have seen the same issue. I guess both of us are using minio/minio:latest.
> 
> After pinning to minio/minio:RELEASE.2020-07-02T00-15-09Z, the users are back.
> 
> The latest image also breaks DNS style bucket. I guess you should have more tests to make sure releases will not break existing deployments.

Yes, I have avoided using minio/minio:latest, which will cause stability problems.
Can we return to the old version? After all, it is Breaking Change and may not be forward compatible.

**Comment by BoleynSu** [comment]
1) Good to know. So the next release should include the fix, right?

2) I think it should be a regression. I can reproduce the exact same behavior.

**Comment by harshavardhana** [comment]
> Can we return to the old version? After all, it is Breaking Change and may not be forward compatible.

Backward compatible no @manors the backend format has changed so wait for the new release.

**Comment by harshavardhana** [comment]
yes we will make a release before the weekend is over.

**Comment by manors** [comment]
thanks for your reminder @harshavardhana  :)

**Comment by BoleynSu** [comment]
@manors I agree it is a bad practice to use the latest tag. I am using it just because I do not have time to manually update the version regularly (since minio is just deployed for personal use in my home lab). Automatically update the version number is not too much better than using latest, so I am just being lazy here.

Still I think latest should be more stable. Maybe we just need more tests.

**Comment by manors** [comment]
>existing backend metadata will be moved to the new format when the corresponding object is accessed.

In the case of a large number of objects, only one list_objects request is needed, and the server can be fully loaded for several hours. This is a bad experience for who using minio/minio:latest

I am going through this situation.  sad...

**Comment by harshavardhana** [comment]
> In the case of a large number of objects, only one list_objects request is needed, and the server can be fully loaded for several hours. This is a bad experience for who using minio/minio:latest

Yes that is because of backend migration to newer format @manors unfortunately there is no way out of this. It is a one-time activity

**Comment by harshavardhana** [comment]
Also I found an issue fixed in #10018 which can cause some performance problems or take time.

**Comment by manors** [comment]
Just a suggestion, maybe it is a good idea to set a speed limit for backend migration.
