### ISSUE TITLE
Could you tell me about PATH parameter meaning ``minio server PATH`` command?

### ISSUE THREAD

**Issue by hiroyuki-sato** [minio/minio#1003]
Hello
## Question.

1, Could you tell me more detail about PATH parameter which I execute `./minio server PATH` command?
Is `PATH` root directory for minio?

2, And when I execute `./mc mb localhost/photobucket` command, I got following error.
What is wrong?
## Environment
- OSX: 10.11.1
- minio: 2015-12-02T18:55:51Z
- mc: Version: 2015-12-01T02:45:44Z

```
./minio version
Version: 2015-12-02T18:55:51Z
Release-Tag: OFFICIAL.2015-12-02T18-55-51Z
Commit-ID: df94b4d3caef491dbdda0740d9a21fa2176550dc
```

```
./mc version
Version: 2015-12-01T02:45:44Z
Release-tag: OFFICIAL.2015-12-01T02-45-44Z
Commit-id: 0fd1e3c387c0ae00772ff92572cad8a9c6fe16c2
```
## setup

```
./minio server ./minio_test

AccessKey: XXXXXXXXXXXXXXXXXXXX  SecretKey: ****************************************

To configure Minio Client.

    $ wget https://dl.minio.io:9000/updates/2015/Nov/darwin-amd64/mc
    $ chmod 755 mc
    $ ./mc config host add http://localhost:9000 XXXXXXXXXXXXXXXXXXXX ****************************************
    $ ./mc mb localhost/photobucket
    $ ./mc cp ~/Photos... localhost/photobucket

Starting minio server:
Listening on http://127.0.0.1:9000
Listening on http://xxx.xxx.xxx.xxx:9000
```
## mc mb error

```
./mc mb localhost/photobucket
mc: <ERROR> Unable to make bucket ‘http://localhost:9000/host/photobucket’. Buckets can only be created at the top level.
```

But following command worked fine.

```
./mc mb photobucket
Bucket created successfully ‘photobucket’.
```
## mb ls

This is contents of /tmp directory which I execute `minio server ./minio_test` command.

```
./mc ls
[2015-12-08 21:08:38 JST]    53B .s.PGSQL.5432.lock
[2015-12-08 20:11:07 JST]   204B Atom Crashes/
[2015-12-08 20:10:53 JST]   102B com.apple.launchd.IghxY4nixF/
[2015-12-08 20:10:53 JST]   102B com.apple.launchd.jgfPq0oJaB/
[2015-12-08 20:10:53 JST]   102B com.apple.launchd.mrxgvEgGZO/
[2015-12-08 20:10:41 JST]    68B cvcd/
[2015-12-01 06:58:38 JST]  10MiB mc
[2015-12-08 21:19:55 JST]  11MiB minio
[2015-12-08 21:27:07 JST]   102B minio_test/
[2015-12-08 21:27:41 JST]    68B minio_test2/
[2015-12-08 21:37:35 JST]    68B photobucket/
[2015-12-08 21:26:53 JST]     5B test.txt
```

**Comment by krishnasrinivas** [comment]
@hiroyuki-sato 
`minio server PATH` here PATH is the directory that you want to export using minio server.

About the problem here:

```
./mc mb localhost/photobucket
mc: <ERROR> Unable to make bucket ‘http://localhost:9000/host/photobucket’. Buckets can only be created at the top level.
```

This is a bug in our code.

Can you try this command for now:
`mc mb http://localhost:9000/photobucket`

**Comment by hiroyuki-sato** [comment]
@krishnasrinivas 

Thank you for replying.

## mc mb result.

I got the following error.

`./mc mb http://localhost:9000/photobucket2` result

```
./mc mb http://localhost:9000/photobucket2
mc: <ERROR> Unable to make bucket ‘http://localhost:9000/photobucket2’. We encountered an internal error, please try again.
```

```
ERRO[0026] MakeBucket failed.                            Error={Cause:Root path ./minio_test reached its minimum free disk threshold. Type:fs.RootPathFull CallTrace:[{Line:107 Filename:pkg/fs/fs-bucket.go Function:fs.Filesystem.MakeBucket Env:map[]} {Line:220 Filename:bucket-handlers.go Function:main.CloudStorageAPI.PutBucketHandler Env:map[]}] SysInfo:map[host.name:hsato-mbp.local mem.used:700kB mem.total:4.7MB host.arch:amd64 host.lang:go1.5.1 host.cpus:4 mem.heap.used:700kB mem.heap.total:1.7MB host.os:darwin]}
```

`mc mb photobucket2` worked fine.

```
./mc mb photobucket2
Bucket created successfully ‘photobucket2’.
```

## PATH

I want to export '/tmp/minio_test' directory.
so I execute `minio server /tmp/minio_test` command.

But when I execute `mc ls` command 
I got following output

This is output of '/tmp' directory contents, not '/tmp/minio_test'.
Note: (minio command location is `/tmp/minio`)

Is this proper behavior?

```
./mc ls
[2015-12-08 22:06:38 JST]    53B .s.PGSQL.5432.lock
[2015-12-08 20:11:07 JST]   204B Atom Crashes/
[2015-12-08 20:10:53 JST]   102B com.apple.launchd.IghxY4nixF/
[2015-12-08 20:10:53 JST]   102B com.apple.launchd.jgfPq0oJaB/
[2015-12-08 20:10:53 JST]   102B com.apple.launchd.mrxgvEgGZO/
[2015-12-08 20:10:41 JST]    68B cvcd/
[2015-12-01 06:58:38 JST]  10MiB mc
[2015-12-08 21:19:55 JST]  11MiB minio
[2015-12-08 21:27:07 JST]   102B minio_test/
[2015-12-08 21:27:41 JST]    68B minio_test2/
[2015-12-08 21:37:35 JST]    68B photobucket/
[2015-12-08 22:18:46 JST]    68B photobucket2/
[2015-12-08 21:26:53 JST]     5B test.txt
```

Thanks.

**Comment by krishnasrinivas** [comment]
in the error message:
`ERRO[0026] MakeBucket failed.                            Error={Cause:Root path ./minio_test reached its minimum free disk threshold. Type:fs.RootPathFull CallTrace:[{Line:107 Filename:pkg/fs/fs-bucket.go Function:fs.Filesystem.MakeBucket Env:map[]} {Line:220 Filename:bucket-handlers.go Function:main.CloudStorageAPI.PutBucketHandler Env:map[]}] SysInfo:map[host.name:hsato-mbp.local mem.used:700kB mem.total:4.7MB host.arch:amd64 host.lang:go1.5.1 host.cpus:4 mem.heap.used:700kB mem.heap.total:1.7MB host.os:darwin]}
`

it says that disk is full under /tmp/minio_test can you check disk space?

`./mc mb photobucket2` this will create photobucket2 directory under current working directory and not in the minio export directory. So you will need to do `mc mb http://localhost:9000/photobucket2`. just make sure that there is diskspace in /tmp

Let us know how it goes.

**Comment by hiroyuki-sato** [comment]
Oh I see 
- Could you tell me minimum require space?
- Can I change disk space threshold?

~~I have 23GB fee space (95% used).~~
I have 9.7GB(5%) Free space

```
Filesystem                                     Size   Used  Avail Capacity   iused     ifree %iused  Mounted on
/dev/disk1                                     188G   178G   9.7G    95%  43466046   2370048   95%   /
```

**Comment by krishnasrinivas** [comment]
we return error in case less than 5% disk space is available as backend file systems behave unpredictably when usage nears 100%. So we keep the threshold to 95%.

**Comment by hiroyuki-sato** [comment]
Thanks. I tried on another disk It worked as I expect.

**Comment by harshavardhana** [comment]
> Thanks. I tried on another disk It worked as I expect.

To change the min-free-disk use the following option 

```
      $ minio server min-free-disk 2% /home/shared/Pictures
```

**Comment by hiroyuki-sato** [comment]
Thanks!.

**Comment by harshavardhana** [comment]
> Thanks!.

Sure. Your welcome!

**Comment by drook** [comment]
In my case 5% is 648 Gbytes. Could you please add the configuration parameter ? Because if it was ZFS I could understand, but with xfs there's no such "unpredictability".
