### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#10033]
We are trying to start MinIO  using shell cmd.
## Current Behavior

API: SYSTEM()
Time: 18:07:26 CST 07/13/2020
Error: http://10.10.90.88:9333/export1 as has incorrect configuration: remote server offline
       1: github.com/minio/minio@/cmd/server-main.go:489:cmd.serverMain()

## Steps to Reproduce (for bugs)

1.   ./minio server --config-dir /etc/minio --address 127.0.0.1:9333 http://10.10.10.86/export1 http://10.10.10.87/export1 http://10.10.10.88/export1 http://10.10.10.89/export1
2.  then this error happens
Time: 18:07:26 CST 07/13/2020
Error: http://10.10.90.88:9333/export1 as has incorrect configuration: remote server offline
       1: github.com/minio/minio@/cmd/server-main.go:489:cmd.serverMain()

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
centos 3.10.0-957.el7.x86_64
minio https://dl.min.io/server/minio/release/linux-amd64/minio

**Comment by klauspost** [comment]
Please add version. If not latest, retest with latest.

**Comment by kendn1993** [comment]
> 
> 
> Please add version. If not latest, retest with latest.

I use this link https://dl.min.io/server/minio/release/linux-amd64/minio,It seems that there is no version in it.

**Comment by klauspost** [comment]
Execute `minio --version`.

**Comment by harshavardhana** [comment]
Use the latest release and let us know https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z
