### ISSUE TITLE
docs.min.io is broken

### ISSUE THREAD

**Issue by Siedlerchr** [minio/minio#10034]
Today I noticed that the docs are broken in Firefox and also in Chrome:
![grafik](https://user-images.githubusercontent.com/320228/87302684-2770ab80-c512-11ea-88ac-efdcc2e6a63b.png)

When I click somewhere nothing happens.
Maybe it is related to the github outage earlier this day?

**Comment by nitisht** [comment]
@Siedlerchr we're aware. Please bear with us while we fix it, meanwhile please browse https://github.com/minio/minio/tree/master/docs
