### ISSUE TITLE
Docs page is broken

### ISSUE THREAD

**Issue by nesty92** [minio/minio#10037]
![image](https://user-images.githubusercontent.com/26422482/87322032-ee790c80-c4fa-11ea-8c4c-8eab388c5c4e.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Resolved PTAL
