### ISSUE TITLE
[not a bug] server has incorrect configuration: remote server offline

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#10040]
## Current Behavior

API: SYSTEM()
Time: 09:30:46 CST 07/14/2020
Error: http://10.10.90.88:9333/export1 as has incorrect configuration: remote server offline
       1: github.com/minio/minio@/cmd/server-main.go:489:cmd.serverMain()

## Steps to Reproduce (for bugs)

1.   ./minio server --config-dir /etc/minio \
	       --address 127.0.0.1:$port \
	       http://10.10.10.86/export1 \
               http://10.10.10.88/export1 \
               http://10.10.10.54/export1 \
               http://10.10.10.87/export1 
2.  then this error happen

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version RELEASE.2020-07-13T18-09-56Z
Linux  3.10.0-957.el7.x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> API: SYSTEM()
> Time: 09:30:46 CST 07/14/2020
> Error: http://10.10.90.88:9333/export1 as has incorrect configuration: remote server offline
> 1: github.com/minio/minio@/cmd/server-main.go:489:cmd.serverMain()

This means your remote server is offline @kendnone - have you started all servers?

**Comment by kendn1993** [comment]
> 
> 
> > API: SYSTEM()
> > Time: 09:30:46 CST 07/14/2020
> > Error: http://10.10.90.88:9333/export1 as has incorrect configuration: remote server offline
> > 1: github.com/minio/minio@/cmd/server-main.go:489:cmd.serverMain()
> 
> This means your remote server is offline @kendnone - have you started all servers?

Yes,I hava started all servers,only this server http://10.10.10.86/export1 show this error,others show Waiting for a minimum of 2 disks to come online (elapsed 1m8s)

**Comment by harshavardhana** [comment]
> 1. ./minio server --config-dir /etc/minio 
>    --address 127.0.0.1:$port

if you bind your port to 127.0.0.1 - how do you expect MinIO to connect on different IPs?  Just bind to `0.0.0.0:$port`

```
> 1. ./minio server --config-dir /etc/minio 
>    --address ":$port"
```

**Comment by kendn1993** [comment]
> 
> 
> > 1. ./minio server --config-dir /etc/minio
> >    --address 127.0.0.1:$port
> 
> if you bind your port to 127.0.0.1 - how do you expect MinIO to connect on different IPs? Just bind to `0.0.0.0:$port`
> 
> ```
> > 1. ./minio server --config-dir /etc/minio 
> >    --address ":$port"
> ```

Thank you very much.Finally it works.
