### ISSUE TITLE
minio fails to auto heal after wiping out data directories in distributed setup.

### ISSUE THREAD

**Issue by uucico** [minio/minio#10057]
I am evaluating minio in a 4-node setup with 12 disks each, so I have a 3x 16-disk ec sets, and storage class is ec:5.

After importing a number of objects, I wiped clean all data disks in one of the nodes and restarted. 

Disk healing does not seem to work even when forced though "mc admin heal-r", all data directories are kept empty.

## Expected Behavior
Format and auto heal disks

## Current Behavior
"mc admin heal -r" will show most objects in red (as expected) but healing never occurs.

mc admin info shows:
```
328 GiB Used, 4 Buckets, 1,069 Objects
36 drives online, 12 drives offline
```

In the server logs:
```
Jul 15 21:11:27 prd7088p minio: API: SYSTEM()
Jul 15 21:11:27 prd7088p minio: Time: 21:11:27 -04 07/15/2020
Jul 15 21:11:27 prd7088p minio: DeploymentID: 33e47b33-67f0-4a68-97a8-83a5647ec191
Jul 15 21:11:27 prd7088p minio: Error: unformatted disk found
Jul 15 21:11:27 prd7088p minio: 1: github.com/minio/minio@/cmd/background-newdisks-heal-ops.go:100:cmd.monitorLocalDisksAndHeal()
```

## Possible Solution
Unknown by me.

## Steps to Reproduce (for bugs)
1. Running minio RELEASE.2020-07-14T19-14-30Z with "minio server http://minioc1n{1...4}:9000/data{1...12}/data"
2. Create buckets load some data
3. Wipe clean all data directories (this would simulate a pristine machine)
4. Restart minio in the affected server
5. Try to heal with "mc admin heal -r"

Not sure if this also happens when wiping a single disk.

## Context
Trying to simulate a complete machine replacement. 

## Regression
No.

## Your Environment
As described in the summary.

**Comment by harshavardhana** [comment]
Found the fix FWIW
