### ISSUE TITLE
[wontfix] Interface for Authentication

### ISSUE THREAD

**Issue by hangcun** [minio/minio#10059]
In our working situation, credentials' persistence and scope will be a significant consideration for security. As the demands of security department, credentials should be kept in an high-secure internal storage. And more strictly, credentials (secret key) should not be exposed to business layer, so the authentication will not be able to be done in Minio.

In order to be easier to expand Minio for some situations like ours, an interface for authentication and credentials storage may be a good way.

This issue is just a discussion for the feasibility. If you are good to accept this proposal, we are willing to do the implementation.

**Comment by harshavardhana** [comment]
> This issue is just a discussion for the feasibility. If you are good to accept this proposal, we are willing to do the implementation.

No this doesn't make sense for us @hangcun

**Comment by harshavardhana** [comment]
MinIO is the trusted authority here, we are perfectly capable of doing the best possible implementation of any authN or authZ layer. So I don't think we would like to extend this to something unexpected.

If you have a business requirement then you are free to become our customer https://minio.io/pricing - if not you are free to fork the project and make these in your fork we will not be officially supporting it.
