### ISSUE TITLE
Query minio to find on which node the object is located

### ISSUE THREAD

**Issue by ddorian** [minio/minio#10051]
Hi,

To make things efficient, you need to read from the node that has the data directly. The same with write!.

3 cases:

1. Colocating compute+data. You want to execute on the node which has the data locally. Hopefully the "data" part. If not, one that has the parity parts.

2. Downloading from minio. You want to download directly from the server that has the data or partity part. This will 1/2 the network overhead when downloading from a random node which may not have the data.

3. Uploading to minio. You first query minio for a "free" zone. And then upload directly to one of the servers of that zone. 

The api should return a list of minio nodes, sorted by the best/efficient case.

**Comment by nitisht** [comment]
Data on MinIO doesn't reside on a single node, please refer to the docs here https://docs.minio.io/docs/minio-erasure-code-quickstart-guide.html

Also, our intention is to be S3 API compatible. We purposefully avoid adding any other custom APIs. Closing this as answered. Feel free to join us on Slack for further questions.
