### ISSUE TITLE
How to upload a file more than 10M

### ISSUE THREAD

**Issue by orange-pig** [minio/minio#1005]
I can upload a file with 100KB use mc.exe, but 10M is not. The error is " Failed to copy 'test.zip'. open \tmp\multiparts$591727036: The system cannot find the path specified. mc.exe: Session safely terminated. Toresume session 'mc session resume zyHRQVeY'

**Comment by bughandler** [comment]
yah, I have the same question.

**Comment by harshavardhana** [comment]
> I can upload a file with 100KB use mc.exe, but 10M is not. The error is " Failed to copy 'test.zip'. open \tmp\multiparts$591727036: The system cannot find the path specified. mc.exe: Session safely terminated. Toresume session 'mc session resume zyHRQVeY'

This bug was fixed recently, can you paste your 'mc.exe version' ?

**Comment by harshavardhana** [comment]
Additionally try 'mc.exe update' to get the new link or download the new binary - https://dl.minio.io/client/mc/release/windows-amd64/mc.exe

**Comment by bughandler** [comment]
I build it with the source code that checked out from official repo

**Comment by bughandler** [comment]
here I should describe my issues in detail

1: the minio-py sdk (version 0.2.9) & mc.exe (newest version build from minio repo)
    a: generated url for download , expire seconds is 1024. but when I access this url, result is follow error "The request signature we calculated does not match the signature you provided"
    b: when I upload a file more than 10MB , maybe , exactly I don't known the limited size. I got a error just look like this issues's content

2: the mc.exe (download from https://dl.minio.io/client/mc/release/windows-amd64/mc.exe)
   EVERYTHING IS OK.

**Comment by harshavardhana** [comment]
Closing this as the issue was fixed in the latest 'mc' release.
