### ISSUE TITLE
[not a bug] ERROR Unable to initialize server switching into safe-mode: Unable to initialize sub-systems: Credentials missing

### ISSUE THREAD

**Issue by GONETHEN** [minio/minio#10050]
## Steps to Reproduce (for bugs)

1.download
2.chmod +x ./minio
3../minio server /xxx/xxxx/minio/data
4.error

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2020-07-13T18-09-56Z
* Operating System and version (`uname -a`):
Linux ecs-45c2 3.10.0-1062.12.1.el7.x86_64

**Comment by harshavardhana** [comment]
This is because you didn't specify the older credentials present in your env.

If you specify the right envs, it shall work fine.
