### ISSUE TITLE
i need to upload file from browser(i am using liferay portal ) without using presigned URl from minio ,is that possible ?

### ISSUE THREAD

**Issue by balaKarur** [minio/minio#10063]
I need to upload big file from browser (I am using liferay portal in my application ). with minio server. is possible can i upload file without presigned URL...

**Comment by harshavardhana** [comment]
Use the issue template to describe what is it that you are trying to do with more clarity.

This issue is blank with nothing actionable from our end.

**Comment by balaKarur** [comment]
> Use the issue template to describe what is it that you are trying to do with more clarity.
> 
> This issue is blank with nothing actionable from our end.

Thanks for your reply :)

**Comment by balaKarur** [comment]
My requirement :
i need to upload big file from browser, so i setup minio server , now i need to upload big file from bowser.
I referred this example : "https://docs.min.io/docs/upload-files-from-browser-using-pre-signed-urls.html ".  as per this exampel 
i needed created " var client = new Minio.Client() " minio client object and "const server = require('express')()" http express server...
i dont what to do like this , i need one REST  APi to upload file 
HTML Part :
<input id="fileObject"  onchange="onSelectFile(this)"  type="file"  /> 
My js file content 
function onSelectFile (fileObject)
{
    var file = fileObject.files[0];
        
    var uploadURL = "http://<server Host>:9000/minio/upload/bucketName/"+file.name;
    var method = "PUT";
    sendHttpRequest(uploadURL,method,file);
}
function sendHttpRequest(url, method, body,contentType)
		{
			var req = "";
	    	var token = "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJtaW5pb2FkbWluIiwiZXhwIjoxNTk0OTEyMzg3LCJzdWIiOiJtaW5pb2FkbWluIn0.UJesizYg8xvNKEDszNEjB5vU8amLrtmEk-2dFRHYOtz0--Q5UT3sN5IRO8IUJqCjQBpS51oR9pJlv5rWHFNKUg"; 
			try
			{
                req = new XMLHttpRequest();
                req.open("PUT",url , !0)
                req.withCredentials = !1
                req.open(method, url);
                req.setRequestHeader("Authorization", "bearer " + token);
                req.setRequestHeader("x-amz-date","20200715T151323Z")
                req.send(body);
                 req.onload = function()
                {
                    if (req.status === 200 || req.status === 201)
                    {
                        console.log("file uploaded successful");
                    }
                    else
                    {
                       console.log("Failed to upload");
                    }
                };

			   
			  }
			  catch(e)
			  {
				  console.log(e);
			  }
		}
