### ISSUE TITLE
[faq] Upload file from bowser thru http

### ISSUE THREAD

**Issue by balaKarur** [minio/minio#10064]
My requirement :
i need to upload big file from browser, so i setup minio server , now i need to upload big file from bowser.
I referred this example : "https://docs.min.io/docs/upload-files-from-browser-using-pre-signed-urls.html ". as per this example
i needed created " var client = new Minio.Client() " minio client object and "const server = require('express')()" http express server...
i dont what to do like this , i need one REST APi to upload file , the same like 
![Uploading image.png…]()
![minioUI](https://user-images.githubusercontent.com/13732401/87637270-97c03c80-c75f-11ea-8eed-7ea007cb18d3.png)

**HTML Part :**

**My js file content**
function onSelectFile (fileObject)
{
var file = fileObject.files[0];

var uploadURL = "http://serverHostName :9000/minio/upload/bucketName/"+file.name;
var method = "PUT";
sendHttpRequest(uploadURL,method,file);
}
function sendHttpRequest(url, method, body,contentType)
{
var req = "";
var token = "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJtaW5pb2FkbWluIiwiZXhwIjoxNTk0OTEyMzg3LCJzdWIiOiJtaW5pb2FkbWluIn0.UJesizYg8xvNKEDszNEjB5vU8amLrtmEk-2dFRHYOtz0--Q5UT3sN5IRO8IUJqCjQBpS51oR9pJlv5rWHFNKUg";
try
{
req = new XMLHttpRequest();
req.open("PUT",url , !0)
req.withCredentials = !1
req.open(method, url);
req.setRequestHeader("Authorization", "bearer " + token);
req.setRequestHeader("x-amz-date","20200715T151323Z")
req.send(body);
req.onload = function()
{
if (req.status === 200 || req.status === 201)
{
console.log("file uploaded successful");
}
else
{
console.log("Failed to upload");
}
};

		  }
		  catch(e)
		  {
			  console.log(e);
		  }
	}

## Expected Behavior
when i upload a file ,its shodul call ,minio server and start upload the file

## Current Behavior
Currently i am getting Error
Request URL: http://serverHostName :9000/minio/upload/bucketName/package.json
Request Method: PUT
Status Code: 400 Bad Request
Remote Address: 10.20.4.59:9000
Referrer Policy: no-referrer-when-downgrade 

## Your Environment
minio latest version
Windows 
Chrome browser latest version

**Comment by harshavardhana** [comment]
https://github.com/harshavardhana/minio-js-browser-upload following project provides you with the right examples on how to upload through browser to MinIO using presigned PUT and presigned POST

**Comment by balaKarur** [comment]
Hi .Thanks for your sample code :) .
Sorry for the late reply I was moved to another project, now started working on this .
i am facing an issue with the sample code which you shared.
when I upload a file from Ui getting the below error in the Code editor. Please help me to resolve this. Thanks :)
I gave the proper server port as **9443** and my bucket name 

**Errors:**
PS D:\VDSS16.0\minio\preSignedURL\minio-js-browser-upload> node .\presign-post-server.js
D:\VDSS16.0\minio\preSignedURL\minio-js-browser-upload\node_modules\minio\dist\main\xml-parsers.js:64
    throw new Error('XML parse error');
    ^

Error: XML parse error
    at parseXml (D:\VDSS16.0\minio\preSignedURL\minio-js-browser-upload\node_modules\minio\dist\main\xml-parsers.js:64:11)   
    at parseBucketRegion (D:\VDSS16.0\minio\preSignedURL\minio-js-browser-upload\node_modules\minio\dist\main\xml-parsers.js:250:10)
    at DestroyableTransform._flush (D:\VDSS16.0\minio\preSignedURL\minio-js-browser-upload\node_modules\minio\dist\main\transformers.js:88:19)

**Comment by klauspost** [comment]
@balaKarur Are you sure you are using the API port and not the console port?

**Comment by balaKarur** [comment]
@klauspost Thanks for your quick reply 🥇  . Now I used **9000** port 
it's working 👍 
I will execute my use case, if I face any issues let you know, Thanks for your support  @harshavardhana 
Is possible can you please add below line in the read me file , this will be helpful for  new user 
**Steps to execute the Project:**
1)Download the project from GIT.
2)Open the project directory in the command line
 execute the comment to download the npm module dependency
 **npm install**
 3)In the same command line 
 Run the expresser server with the following comment 
**node .\presign-post-server.js**
4)Open the browser with the following URL.
**http://localhost:8080/**

**Comment by balaKarur** [comment]
Hi, can you please tell me max how many GB file can upload thru pre-signed URL?

**Comment by harshavardhana** [comment]
> Hi, can you please tell me max how many GB file can upload thru pre-signed URL?

https://docs.min.io/docs/minio-server-limits-per-tenant.html
