### ISSUE TITLE
[working as intended] MinIO + HTTP Logger Issue

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio#10070]
## Expected Behavior
Trying https://github.com/minio/minio/tree/master/docs/logging audit logging,
Configuration is,
export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
export MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
./minio server /data/MinIO/data

Have exposed a Rest Service URL, http://IP:PORT/bfweb/retail/EOD/minioLogs. But unable to get the call to the service. Have checked minio admin trace --all myminio, could not find any trace of the HTTP target being called. 

## Steps to Reproduce (for bugs)

1.export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
export MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
./minio server /data/MinIO/data
2.
3.
4.

## Your Environment

* Version used (`minio --version`): 2020-07-02T00:15:09Z

* Server setup and configuration:
* Operating System and version (`uname -a`):Windows/Linux

**Comment by vadmeste** [comment]
@PSHREYASHOLLA it works fine for me with the same MinIO server version and the same environment variables that you set.

**Comment by PSHREYASHOLLA** [comment]
@vadmeste  Where does minio log this traffic of calling the HTTP URL, as mentioned I am unable to find anything in mc admin trace --all myminio?

**Comment by vadmeste** [comment]
> @vadmeste Where does minio log this traffic of calling the HTTP URL, as mentioned I am unable to find anything in mc admin trace --all myminio?

I don't think we want to log the same thing twice. You must have a typo somewhere @PSHREYASHOLLA. You can test this locally:
1. `nc -l -p 8080`
2. Run Minio server in another terminal
3. `mc ls myminio/`

**Comment by PSHREYASHOLLA** [comment]
@vadmeste, Checked the configuration again and tested in,
Linux,
export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
export MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
./minio server /data/MinIO/data

Windows,
set MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
set MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
set MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
minio.exe server E:\data\MinIO\data

But in both cases my rest service, http://IP:8080/bfweb/retail/EOD/minioLogs is not getting called.

**Comment by harshavardhana** [comment]
> @vadmeste, Checked the configuration again and tested in,
> Linux,
> export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
> export MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
> export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
> ./minio server /data/MinIO/data
> 
> Windows,
> set MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
> set MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
> set MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
> minio.exe server E:\data\MinIO\data
> 
> But in both cases my rest service, http://IP:8080/bfweb/retail/EOD/minioLogs is not getting called.

@PSHREYASHOLLA we perform POST call is that endpoint supporting POST operation?

**Comment by PSHREYASHOLLA** [comment]
> > @vadmeste, Checked the configuration again and tested in,
> > Linux,
> > export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
> > export MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
> > export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
> > ./minio server /data/MinIO/data
> > Windows,
> > set MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
> > set MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_target1="minioadmin"
> > set MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
> > minio.exe server E:\data\MinIO\data
> > But in both cases my rest service, http://IP:8080/bfweb/retail/EOD/minioLogs is not getting called.
> 
> @PSHREYASHOLLA we perform POST call is that endpoint supporting POST operation?

Yes service is POST method service.

**Comment by harshavardhana** [comment]
I just configured https://webhook.site/#!/32e2620f-a205-4524-8bf6-e4df8925affa/c4b89bc6-0827-4736-8a11-82b1c4fd2e24/1 you can see the messages getting posted. 

It looks like the environment values are not passed into the server configuration @PSHREYASHOLLA

**Comment by harshavardhana** [comment]
Also, does your server support AUTH_TOKEN correctly? @PSHREYASHOLLA

**Comment by PSHREYASHOLLA** [comment]
> I just configured https://webhook.site/#!/32e2620f-a205-4524-8bf6-e4df8925affa/c4b89bc6-0827-4736-8a11-82b1c4fd2e24/1 you can see the messages getting posted.
> 
> It looks like the environment values are not passed into the server configuration @PSHREYASHOLLA

So can you guide me how to confirm the same if the configurations are passed to server?

**Comment by harshavardhana** [comment]
It is as simple as this 

```
export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on" 
export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=https://webhook.site/32e2620f-a205-4524-8bf6-e4df8925affa 
minio server /tmp/{1..4}
```

**Comment by PSHREYASHOLLA** [comment]
> It is as simple as this
> 
> ```
> export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on" 
> export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=https://webhook.site/32e2620f-a205-4524-8bf6-e4df8925affa 
> minio server /tmp/{1..4}
> ```

Yes as mentioned above have used,
Linux,
export MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
export MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
./minio server /data/MinIO/data

Windows,
set MINIO_AUDIT_WEBHOOK_ENABLE_target1="on"
set MINIO_AUDIT_WEBHOOK_ENDPOINT_target1=http://IP:PORT/bfweb/retail/EOD/minioLogs
minio.exe server E:\data\MinIO\data

Since the suspect is server not getting configuration, can we check somwhere after server startup if the same is configured?

**Comment by harshavardhana** [comment]
AFAIK the webhook serve is not able to read the POST request,  you can point to a public URL like webhook.site and see some other endpoint is working.

**Comment by PSHREYASHOLLA** [comment]
> AFAIK the webhook serve is not able to read the POST request, you can point to a public URL like webhook.site and see some other endpoint is working.

With linux the audit is logging for https://webhook.site/32e2620f-a205-4524-8bf6-e4df8925affa. But is not able to ping my rest service. The only difference I see here is the HTTP and HTTPS. 
1) Does this expects only HTTPS?
2) If it fails to connect to the webhook URL does it log anywhere?

P.S : On windows even https://webhook.site/32e2620f-a205-4524-8bf6-e4df8925affa is not working

**Comment by harshavardhana** [comment]
More logs added here #10274 would indicate what might be wrong, most probably the issue is the wrong misconfiguration.

**Comment by harshavardhana** [comment]
Added more logs which would shed light on the mis configuration here https://dl.minio.io/server/minio/release/linux-amd64/
