### ISSUE TITLE
AWS SDK - Auth error

### ISSUE THREAD

**Issue by rafael-leo-almeida** [minio/minio#1007]
Hi, I'm tring to use oficial java sdk but minio return an auth error:

ERRO[1132] Initializing signature v4 failed.             Error={Cause:Missing fields in auth header Type:*errors.errorString CallTrace:[{Line:46 Filename:api-signature.go Function:main.getCredentialsFromAuth Env:map[]} {Line:77 Filename:api-signature.go Function:main.isValidRegion Env:map[]} {Line:89 Filename:api-signature.go Function:main.stripAccessKeyID Env:map[]} {Line:108 Filename:api-signature.go Function:main.initSignatureV4 Env:map[]} {Line:92 Filename:signature-handler.go Function:main.signatureHandler.ServeHTTP Env:map[]}] SysInfo:map[host.name:chupacabra host.lang:go1.5.1 mem.heap.used:1.2MB host.arch:amd64 host.cpus:4 mem.used:1.2MB mem.total:5.5MB mem.heap.total:2.7MB host.os:linux]}

Aws sample code

```
AWSCredentials credentials = new BasicAWSCredentials("KL5HT9MO4UFV91V2UH3L", "6/WVA8WrkYyKHSi4hmQfaU/zR3nQcj5LDGG7CqUM");
AmazonS3 s3Client = new AmazonS3Client(credentials);
//s3Client.setRegion(Region.getRegion(Regions.US_EAST_1));
s3Client.setEndpoint("http://minioHOST:PORT");
s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
s3Client.listBuckets().forEach((bucket) -> {
    System.out.println(bucket.getName());
});

```

**Comment by harshavardhana** [comment]
Thanks @rafaelsisweb - will take a look.

**Comment by harshavardhana** [comment]
@rafaelsisweb - tried with latest aws-sdk-java-1.10.41 

What was needed was to set Signature version to '4' as the signer since aws-sdk-java defaults to signature version '2' by default . 

Since minio only supports signature version '4' it would fail. 

```
import java.io.IOException;

import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.S3ClientOptions;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.ClientConfiguration;

public class HelloListBuckets {
  public static void main(String[] args) throws IOException {
    AWSCredentials credentials = new BasicAWSCredentials("WLGDGYAQYIGI833EV05A",
                                                         "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF");
    ClientConfiguration clientConfiguration = new ClientConfiguration();
    clientConfiguration.setSignerOverride("AWSS3V4SignerType");
    AmazonS3 s3Client = new AmazonS3Client(credentials, clientConfiguration);
    Region usEast1 = Region.getRegion(Regions.US_EAST_1);
    s3Client.setRegion(usEast1);
    s3Client.setEndpoint("http://localhost:9000");
    s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
    s3Client.listBuckets().forEach((bucket) -> {
        System.out.println(bucket.getName());
     });
  }
}
```

Please try this example and let me know how this goes.

**Comment by rafael-leo-almeida** [comment]
Auth work as well, listing buckets works to. But when to upload a file, minio stack this error:

{"Error":{"cause":"The request signature we calculated does not match the signature you provided","type":"fs.SignatureDoesNotMatch","trace":[{"line":301,"file":"pkg/fs/fs-multipart.go","func":"fs.Filesystem.CreateObjectPart"},{"line":326,"file":"object-handlers.go","func":"main.CloudStorageAPI.PutObjectPartHandler"}],"sysinfo":{"host.arch":"amd64","host.cpus":"4","host.lang":"go1.5.1","host.name":"chupacabra","host.os":"linux","mem.heap.total":"3.6MB","mem.heap.used":"1.9MB","mem.total":"7.1MB","mem.used":"1.9MB"}},"level":"error","msg":"CreateObjectPart failed.","time":"2015-12-17T09:05:51-02:00"}

```
Upload upload = tm.upload(bucketName, fileName, new File(filePath));
            if (upload.isDone() == false) {
                System.out.println("Transfer: " + upload.getDescription());
                System.out.println("  - State: " + upload.getState());
                System.out.println("  - Progress: " + upload.getProgress().getBytesTransferred());
            }
upload.waitForCompletion();
```

**Comment by harshavardhana** [comment]
> Auth work as well, listing buckets works to. But when to upload a file, minio stack this error:

I verified two cases - one with Amazon S3 Java SDK and Aamazon S3 Golang SDK but have different results. 

Sample programs which work and don't work. 

A simple put object uploads a single 12MB file

Golang works fine with signature version '4' but java doesn't. 

```
$ go run put-aws.go
{
  ETag: "\"e2e5243148e7bdbfb298570349e7b150\""
}
```

``` go
package main

import (
    "fmt"
    "os"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/credentials"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
)

func main() {
    newSession := session.New()
    s3Config := &aws.Config{
        Credentials:      credentials.NewStaticCredentials("WLGDGYAQYIGI833EV05A", "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF", ""),
        Endpoint:         aws.String("http://localhost:9000"),
        Region:           aws.String("us-east-1"),
        DisableSSL:       aws.Bool(true),
        S3ForcePathStyle: aws.Bool(true),
    }
    // Create an S3 service object in the default region.
    s3Client := s3.New(newSession, s3Config)

    file, err := os.Open("/Users/harsha/caddy")
    if err != nil {
        fmt.Println(err)
        return
    }
    pparams := new(s3.PutObjectInput)
    pparams.Bucket = aws.String("testbbucket")
    pparams.Key = aws.String("caddy")
    pparams.Body = file

    respp, err := s3Client.PutObject(pparams)
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println(respp)
}
```

**Comment by harshavardhana** [comment]
```
$ md5 ~/caddy
MD5 (/Users/harsha/caddy) = e2e5243148e7bdbfb298570349e7b150
```

**Comment by harshavardhana** [comment]
This fails with Content-MD5 mis-match and pretty sure that is happening for multipart as well. (I think you are doing a multipart operation)

``` java
      credentials = new BasicAWSCredentials("WLGDGYAQYIGI833EV05A",
                                              "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF");
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");
        AmazonS3 s3Client = new AmazonS3Client(credentials, clientConfiguration);
        Region usEast1 = Region.getRegion(Regions.US_EAST_1);
        s3Client.setRegion(usEast1);
        s3Client.setEndpoint("http://localhost:9000");
        s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
        tx = new TransferManager(s3Client);

        bucketName = "testbbucket" + credentials.getAWSAccessKeyId().toLowerCase();

        new S3TransferProgressSample();
    }
```

``` java
         };

            File fileToUpload = fileChooser.getSelectedFile();
            PutObjectRequest request = new PutObjectRequest(
                    bucketName, fileToUpload.getName(), fileToUpload)
                .withGeneralProgressListener(progressListener);
            upload = tx.upload(request);
        }
    }
```

**Comment by harshavardhana** [comment]
Not sure why the Content-MD5 mismatches. for Java alone and not Golang.

**Comment by harshavardhana** [comment]
Oh looks like aws-sdk-java sends back following headers .

`{PUT /testbbucket/caddy HTTP/1.1 1 1 map[Content-Type:[application/octet-stream] Content-Md5:[4uUkMUjnvb+ymFcDSeexUA==] Connection:[Keep-Alive] X-Amz-Date:[20151218T001827Z] X-Amz-Decoded-Content-Length:[12232928] Content-Length:[12241473] X-Amz-Content-Sha256:[STREAMING-AWS4-HMAC-SHA256-PAYLOAD] Authorization:[AWS4-HMAC-SHA256 Credential=WLGDGYAQYIGI833EV05A/20151218/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=6049168c4cc08fb1c9961a2bf20f045127e67bc89f886105feb8474bdd9047ba] User-Agent:[aws-sdk-java/1.10.41 Mac_OS_X/10.11.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.25-b02/1.8.0_25 com.amazonaws.services.s3.transfer.TransferManager/1.10.41]] 0xc82012ae80 12241473 [] false localhost:9000 map[] map[] <nil> map[] 127.0.0.1:55360 /testbbucket/caddy <nil> <nil>}`

**Comment by harshavardhana** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html - Found it 
`When using signature version 4 to authenticate request, this header provides a hash of the request payload. For more information see Authenticating Requests by Using the Authorization Header (Compute Checksum of the Entire Payload Prior to Transmission) - Signature Version 4. When uploading object in chunks, you set the value to STREAMING-AWS4-HMAC-SHA256-PAYLOAD to indicate that the signature covers only headers and that there is no payload. For more information, see Authenticating Requests Using HTTP Authorization Header (Chunked Upload).`

**Comment by harshavardhana** [comment]
Okay so the Content-Md5 is not reliable here, so we cannot really verify, going to try non streaming approach.  

@rafaelsisweb on your end - if possible can you print the request headers for the multipart upload you are doing?

**Comment by harshavardhana** [comment]
Golang SDK on the other hand is not setting Content-MD5 at all.

**Comment by harshavardhana** [comment]
Tested with S3TransferManager written in Golang - seems to be working fine.  Going to test with Java now. 

```
package main

import (
    "log"
    "os"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/credentials"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3/s3manager"
)

func main() {
    file, err := os.Open("/Users/harsha/caddy")
    if err != nil {
        log.Fatal("Failed to open file", err)
    }
    s3Config := &aws.Config{
        Credentials:      credentials.NewStaticCredentials("WLGDGYAQYIGI833EV05A", "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF", ""),
        Endpoint:         aws.String("http://localhost:9000"),
        Region:           aws.String("us-east-1"),
        DisableSSL:       aws.Bool(true),
        S3ForcePathStyle: aws.Bool(true),
    }
    uploader := s3manager.NewUploader(session.New(s3Config))
    result, err := uploader.Upload(&s3manager.UploadInput{
        Body:   file,
        Bucket: aws.String("testbbucket"),
        Key:    aws.String("caddy"),
    })
    if err != nil {
        log.Fatalln("Failed to upload", err)
    }

    log.Println("Successfully uploaded to", result.Location)
}
```

**Comment by harshavardhana** [comment]
```
/**
     * Determine whether to use aws-chunked for signing
     */
    private static boolean useChunkEncoding(SignableRequest<?> request) {
        // Whether to use chunked encoding for signing the request
        boolean chunkedEncodingEnabled = false;
        if (request.getOriginalRequestObject() instanceof PutObjectRequest
                || request.getOriginalRequestObject() instanceof UploadPartRequest) {
            chunkedEncodingEnabled = true;
        }
        return chunkedEncodingEnabled;
    }
```

Okay looks like Java SDK will do chunked uploading as default for PutObjectRequest and UploadPartRequest.

**Comment by rafael-leo-almeida** [comment]
@harshavardhana that is the entire request....
`PUT http://192.168.41.14:9000 /teste/MongoChef.dmg Parameters: ({"uploadId":["YmznEp472GLEvzsyLrxQqtgtQBjaQg5gwNTWdOipfVGC5lc"],"partNumber":["10"]}Headers: (x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD, Authorization: AWS4-HMAC-SHA256 Credential=KL5HT9MO4UFV91V2UH3L/20151218/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=29a02ca4ec5569462ce2d500286dd8a470f5f187af75b606aab5a53e170bb8bb, X-Amz-Date: 20151218T134008Z, User-Agent: aws-sdk-java/1.10.41 Linux/3.16.7-29-desktop Java_HotSpot(TM)_64-Bit_Server_VM/25.60-b23/1.8.0_60 com.amazonaws.services.s3.transfer.TransferManager_multipart/1.10.41, Host: 192.168.41.14:9000, x-amz-decoded-content-length: 5242880, Content-Length: 5246566, Content-Type: application/octet-stream, )`

**Comment by harshavardhana** [comment]
ref - https://github.com/aws/aws-sdk-java/issues/580

**Comment by harshavardhana** [comment]
https://github.com/aws/aws-sdk-java/pull/581 - change submitted here to provide an option to disable chunked uploading.

**Comment by rafael-leo-almeida** [comment]
Hi @harshavardhana, I was trying to test chunked-encoding but got this Exception when try:

```
...
clientConfiguration.setSignerOverride("AWSS3V4SignerType");
...
AmazonS3 s3Client = new AmazonS3Client(credentials, clientConfiguration);
```

Result is:

```
Exception in thread "main" java.lang.Exception: Cannot create an instance of com.amazonaws.services.s3.internal.AWSS3V4Signer
```

**Comment by harshavardhana** [comment]
@rafaelsisweb - i couldn't take a look today. I will tomorrow. Thanks for testing.

**Comment by harshavardhana** [comment]
> @rafaelsisweb - i couldn't take a look today. I will tomorrow. Thanks for testing.

I haven't been able to take a look at this, been traveling and on vacation. Will do this on priority on coming monday.

**Comment by harshavardhana** [comment]
> I haven't been able to take a look at this, been traveling and on vacation. Will do this on priority on coming monday.

There has been some progress today - We are finally running some integration tests which aws-sdk-java needs to do before the patch is accepted. Patch is going to accepted in a different form than what was currently submitted.  Since there are some limitations on how the Signature factory is implemented in aws-sdk-java.

The option is going to be simple enough to be enabled just like how it was done initially.

**Comment by rafael-leo-almeida** [comment]
@harshavardhana good news, waiting that to deploy minio on alpha production environment.

**Comment by harshavardhana** [comment]
@rafaelsisweb the patch is merged. Will be available as an option in next release in 2016.

**Comment by rafael-leo-almeida** [comment]
@harshavardhana thanks. Wainting to do new tests.

**Comment by harshavardhana** [comment]
> @harshavardhana thanks. Wainting to do new tests.

@rafaelsisweb aws-sdk-java is released.

**Comment by harshavardhana** [comment]
@rafaelsisweb - following code now works with minio server with the new aws-sdk-java release. Closing this bug. 

```
       ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");

        AmazonS3 s3 = new AmazonS3Client(credentials, clientConfiguration);
        Region usEast1 = Region.getRegion(Regions.US_EAST_1);
        s3.setRegion(usEast1);
        s3.setEndpoint("http://localhost:9000");
        S3ClientOptions clientOptions = new S3ClientOptions();
        clientOptions.withPathStyleAccess(true);
        clientOptions.disableChunkedEncoding();
        s3.setS3ClientOptions(clientOptions);
        System.setProperty("com.amazonaws.services.s3.disableGetObjectMD5Validation","true");
```

**Comment by rafael-leo-almeida** [comment]
Hi, this bug returns after upgrading from RELEASE.2016-08-21T02-44-47Z to RELEASE.2016-09-11T17-42-18Z

When doing upload to minio on RELEASE.2016-08-21T02-44-47Z version everything works but on latest version got this exception.

`
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3L137), S3 Extended Request ID: 3L137
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1422)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`
