### ISSUE TITLE
[not our bug] Error: Storage resources are insufficient for the read operation.

### ISSUE THREAD

**Issue by ethanxzw** [minio/minio#10071]
Hi team, now we face a issue for minio deployment on k8s with statefulset mode as below. could you please help to check it? 

API: SYSTEM()
Time: 09:22:45 UTC 07/17/2020
DeploymentID: 52640fa1-f3a6-4f9c-9cb2-129907c7ff9d
Error: Storage resources are insufficient for the read operation.
       8: github.com/minio/minio@/cmd/config-common.go:40:cmd.readConfig()
       7: github.com/minio/minio@/cmd/config-migrate.go:2505:cmd.checkConfigVersion()
       6: github.com/minio/minio@/cmd/config-migrate.go:2478:cmd.migrateMinioSysConfig()
       5: github.com/minio/minio@/cmd/config.go:243:cmd.initConfig()
       4: github.com/minio/minio@/cmd/config.go:213:cmd.(*ConfigSys).Init()
       3: github.com/minio/minio@/cmd/server-main.go:246:cmd.initAllSubsystems()
       2: github.com/minio/minio@/cmd/server-main.go:220:cmd.initSafeMode()
       1: github.com/minio/minio@/cmd/server-main.go:447:cmd.serverMain()
Waiting for all sub-systems to be initialized.. Unable to initialize config system: Storage resources are insufficient for the read operation.

PVC info:
data-minio-0                                               Bound    pvc-cdba9479-c80c-11ea-b038-fa163e339fae   3Gi        RWO 
data-minio-1                                               Bound    pvc-cdbc6e19-c80c-11ea-b038-fa163e339fae   3Gi        RWO 
data-minio-2                                               Bound    pvc-cdbe99c1-c80c-11ea-b038-fa163e339fae   3Gi        RWO 
data-minio-3                                               Bound    pvc-cdc07072-c80c-11ea-b038-fa163e339fae   3Gi        RWO 

Name:          data-minio-0
Namespace:     corecrm
StorageClass:  crm-nfs-storage-class
Status:        Bound
Volume:        pvc-cdba9479-c80c-11ea-b038-fa163e339fae
Labels:        app=minio
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      3Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Events:
  Type       Reason                 Age   From                         Message
  ----       ------                 ----  ----                         -------
  Normal     ProvisioningSucceeded  39m   persistentvolume-controller  Successfully provisioned volume pvc-cdba9479-c80c-11ea-b038-fa163e339fae using kubernetes.io/glusterfs
Mounted By:  minio-0

## Your Environment
minio version:  RELEASE.2020-04-02T21-34-49Z
k8s version: 1.14.0
OS version: 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
GlusterFS doesn't support O_DIRECT by default you need to enable O_DIRECT support.

We recommend that you use disks directly not use network filesystem to run distributed setup.

https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/administration_guide/chap-managing_red_hat_storage_volumes

**Comment by ethanxzw** [comment]
Hi guys, we have enabled strict-o-direct options for minio volumes, but the issue still exist. could you please share the steps to enable O_DIRECT support, thanks.

Options Reconfigured:
performance.write-behind: off
user.heketi.id: b074b127532f0610d03031671a218060
transport.address-family: inet
storage.fips-mode-rchecksum: on
nfs.disable: on
performance.client-io-threads: off
performance.strict-o-direct: on
performance.nfs.strict-o-direct: on

**Comment by harshavardhana** [comment]
> Hi guys, we have enabled strict-o-direct options for minio volumes, but the issue still exist. could you please share the steps to enable O_DIRECT support, thanks.
> 
> Options Reconfigured:
> performance.write-behind: off
> user.heketi.id: b074b127532f0610d03031671a218060
> transport.address-family: inet
> storage.fips-mode-rchecksum: on
> nfs.disable: on
> performance.client-io-threads: off
> performance.strict-o-direct: on
> performance.nfs.strict-o-direct: on

@ethanxzw although I gave you a workaround, we don't recommend that you use GlusterFS with MinIO in distributed mode. You can use NAS gateway mode which is recommended.

You provide direct disks to MinIO or any CSI which provides direct block devices.
