### ISSUE TITLE
[FAQ] how minio handle disk replacment? remove old disk, add new disk rebuild the data

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10081]
is there any instruction and best practice for this?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Nothing special keep servers always running

- umount  /mnt/data1
- (remove disk from the enclosure)
- (attach a new drive, format)
- mount /mnt/data1

Server will start the heal of the newly added drive in 3 minutes automatically.

Wait for the new release to test this, we had some bugs which we fixed recently.

**Comment by harshavardhana** [comment]
Closing as answered and also new release has been made
