### ISSUE TITLE
signature: Implement support for STREAMING-AWS4-HMAC-SHA256-PAYLOAD

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1008]
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html - 

```
x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
```

**Comment by harshavardhana** [comment]
Streaming signature version '4' - http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

**Comment by harshavardhana** [comment]
ref #1007

**Comment by lukiano** [comment]
Hi, I was trying your product. Pretty cool by the way, better than fakes3. But I'm streaming data and got stuck by this issue. Is there a way to disable signatures? Thanks!

**Comment by harshavardhana** [comment]
> Hi, I was trying your product. Pretty cool by the way, better than fakes3. But I'm streaming data and got stuck by this issue. Is there a way to disable signatures? Thanks!

There is no way to disable signatures at the moment you can use payload based signature technique, can you paste your program or SDK that you are using ? Thanks

**Comment by lukiano** [comment]
I'm using the Amazon SDK in Java, where you set an InputStream with your contents. In this case I receive them from the network. The SDK internally has a small buffer so it can retry in case of errors. So, if my data is smaller than such buffer, it works fine. If bigger, I get "com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch"

**Comment by harshavardhana** [comment]
> I'm using the Amazon SDK in Java, where you set an InputStream with your contents. In this case I receive them from the network. The SDK internally has a small buffer so it can retry in case of errors. So, if my data is smaller than such buffer, it works fine. If bigger, I get "com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch"

Ah we provided a patch upstream to use SignatureV4 with payload directly rather than doing STREAMING you can use that for the time being.

In the meantime, we will add a check for this and respond back with an appropriate message.

```
import java.io.IOException;

import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.S3ClientOptions;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.ClientConfiguration;
import com.amazonaws.services.s3.model.PutObjectRequest;

import java.io.File;

public class HelloListBuckets {
  public static void main(String[] args) throws IOException {
    AWSCredentials credentials = new BasicAWSCredentials("WLGDGYAQYIGI833EV05A",
                                                         "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF");
    ClientConfiguration clientConfiguration = new ClientConfiguration();
    clientConfiguration.setSignerOverride("AWSS3V4SignerType");
    AmazonS3 s3Client = new AmazonS3Client(credentials, clientConfiguration);
    Region usEast1 = Region.getRegion(Regions.US_EAST_1);
    s3Client.setRegion(usEast1);
    s3Client.setEndpoint("http://localhost:9000");
    s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
    File file = new File("/Users/harsha/caddy");
    s3Client.putObject(new PutObjectRequest("testbbucket", file.getName(), file));
  }
}
```

**Comment by harshavardhana** [comment]
Important parameter here is 'disableChunkedEncoding()' which basically would do payload verification. 

```
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");

        AmazonS3 s3 = new AmazonS3Client(credentials, clientConfiguration);
        Region usEast1 = Region.getRegion(Regions.US_EAST_1);
        s3.setRegion(usEast1);
        s3.setEndpoint("http://localhost:9000");
        S3ClientOptions clientOptions = new S3ClientOptions();
        clientOptions.withPathStyleAccess(true);
        clientOptions.disableChunkedEncoding();
        s3.setS3ClientOptions(clientOptions);
        System.setProperty("com.amazonaws.services.s3.disableGetObjectMD5Validation","true");
```

**Comment by GarimaKapoor** [comment]
We will document it under AWS Java SDK for Minio Server.

**Comment by harshavardhana** [comment]
Will be fixed by July 24th

**Comment by harshavardhana** [comment]
Closing this as duplicate of #2326
