### ISSUE TITLE
[working as intended] Can arm64 and amd64 hosts be used in the same cluster?

### ISSUE THREAD

**Issue by skandragon** [minio/minio#10089]
It seems right now they cannot (rejected with ```incorrect configuration: Expected platform 'OS: linux | Arch: arm64', found to be running 'OS: linux | Arch: amd64'```

However, is this due to a binary incompatibility or an over-cautious check?

**Comment by harshavardhana** [comment]
@skandragon no it is not allowed - it is due to mainly performance differences in a distributed setup. amd64 >> arm64 unless you are using like graviton2 like ARM CPUs.

Homogenous environments are more predictable to debug and fix issues.
