### ISSUE TITLE
directory containing more than 10000 files causes docker container OOM

### ISSUE THREAD

**Issue by dongbixibiX** [minio/minio#10088]
when a sub directory (depth =2) contains more than 10000(maxObjectList) files, minio consumes a lot of memory and causes docker container OOM (Over 8g)

## Expected Behavior
minio consumes reasonable memory

## Current Behavior
minio consumes a lot of memory and causes docker container OOM (Over 8g)

### solution 1
 reduce the number of files in the directory
### solution 2
i saw many **doTreeWalk goroutines** in dlv debug program
i changed code **cmd/tree-walk.go:165** showed below, rebuilt and restart,  minio is back to normal
```
//resultCh := make(chan TreeWalkResult, maxObjectList)
resultCh := make(chan TreeWalkResult, 100000)  // greater than number of files in the directory
```

## Steps to Reproduce (for bugs)
1. create a directory, and put more than 10000(maxObjectList) files into it
2. start minio server 
3. wait for about a hour, mino will causes docker container OOM (Over 8g)

## Context
a sample memory profile file
[profile.zip](https://github.com/minio/minio/files/4943467/profile.zip)

## Your Environment
* Version used (`minio --version`):   RELEASE.2020-07-18T18-48-16Z
* Server setup and configuration:     Default
* Operating System and version (`uname -a`): Linux 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dongbixibiX** [comment]
We use minio to store spark-history logs, which can be related to this. Let's investigate the specific reason

**Comment by harshavardhana** [comment]
Duplicate of #9966
