### ISSUE TITLE
[working as intended] Env variables MINIO_STORAGE_CLASS_STANDARD and MINIO_STORAGE_CLASS_RRS not working fine

### ISSUE THREAD

**Issue by neonanda** [minio/minio#10099]
<After setting parity value for MINIO_STORAGE_CLASS_RRS to 1, my 4 node cluster with 2 disks on each node not working fine when i stop 2 nodes with 4 disks >

## Expected Behavior
<As per my understanding if i put RRS value to 1 my cluster should work even in case 4 disks  or 2 nodes are offline, i mean i am able to download files but not able to upload any new files>
<Environment should work in case i put value 1 for MINIO_STORAGE_CLASS_RRS , i was expecting error but everything is working fine>

## Current Behavior
<Currently as soon as i put 2 nodes containing 4 disks offline the rest of the cluster with 2 nodes containing 4 disks becoming RO>
<There should have option to put MINIO_STORAGE_CLASS_RRS and MINIO_STORAGE_CLASS_STANDARD in such a way so that in case we have issue with nodes it should still works fine, compromising parity sometimes ok>

## Possible Solution
No Idea

## Steps to Reproduce (for bugs)

1. Created minio cluster with 4 nodes with 2 disks on each node so there are 8 disks in total
2. I stopped 2 nodes after setting MINIO_STORAGE_CLASS_RRS to 2 and MINIO_STORAGE_CLASS_STANDARD to 3, i also tried only using one parameter MINIO_STORAGE_CLASS_RRS with value 1.
3. As soon as 2 nodes with 4 disks in total are not available rest of the minio cluster's node are not available for RW.

## Context
I have  only 2 sites available for creation of any distributed cluster, i was planning to distribute equal nodes on each site.
i was looking for arbitor kind of thing which can help in case one of my site goes down, 
So, i was looking for either some proxy/arbitor i can use or way to change setting for MINIO_STORAGE_CLASS_RRS so that the cluster remain available for RW even after the loss of one site.

Can you please help me with the correct configuration value in case i m doing something wrong with MINIO_STORAGE_CLASS_RRS and MINIO_STORAGE_CLASS_STANDARD, basically i want half of the disks available for RW in case one site dows down. I don't care about the parity, if it is least it is fine.

## Your Environment

* Version used (`minio --version`): Latest
* Server setup and configuration: Two sites are available, each site has 2 nodes and each node has 2 disks. So, in total there are 8 disks present.
* Operating System and version (`uname -a`): RHEL 7.4

**Comment by harshavardhana** [comment]
> * Created minio cluster with 4 nodes with 2 disks on each node so there are 8 disks in total
> * I stopped 2 nodes after setting MINIO_STORAGE_CLASS_RRS to 2 and MINIO_STORAGE_CLASS_STANDARD to 3, i also tried only using one parameter MINIO_STORAGE_CLASS_RRS with value 1.

Loosing 2 nodes you loose 4 drives you cannot have lower parity than this. You are expecting more HA than your number of nodes it cannot be provided. 

MinIO is a symmetric design i.e each server participates equal number of drives.

**Comment by neonanda** [comment]
So, is there any alternative you can suggest to use in case one of my site goes down for e.g we are using MONGO DB on same env and we have created arbitor for handling voting kind of situations, if there any kind of such thing which can help me when one site goes down.

**Comment by harshavardhana** [comment]
> So, is there any alternative you can suggest to use in case one of my site goes down for e.g we are using MONGO DB on same env and we have created arbitor for handling voting kind of situations, if there any kind of such thing which can help me when one site goes down.

Add more nodes you can get more availability with 4 nodes minimum possible loss is 1 node with EC:2 and 2 node tolerance for with any value with EC:3 or EC:4 

Expecting more HA than your existing nodes wouldn't work. If you bring in 8 nodes with 1 drive each then you can have easily 2 node, 3 node and 4 node tolerance.

**Comment by klauspost** [comment]
I suppose you have already seen the documentation, but for future reference:

https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html
https://docs.min.io/docs/distributed-minio-quickstart-guide.html
https://github.com/minio/minio/tree/master/docs/erasure/storage-class
