### ISSUE TITLE
[working as intended] [faq] Unable to initialize backend: format.json file: expected format-type: fs, found: xl

### ISSUE THREAD

**Issue by alirezarahmani** [minio/minio#10094]
I get the following error when I run start:
``ERROR Unable to initialize backend: format.json file: expected format-type: fs, found: xl``
and when I delete .minio.sys file, my file would display any more

**Comment by harshavardhana** [comment]
@alirezarahmani as the error mentioned you cannot use same backend used for FS to be used with erasure coding

**Comment by alirezarahmani** [comment]
> @alirezarahmani as the error mentioned you cannot use same backend used for FS to be used with erasure coding

can you give me more directions, how I can fix it?

**Comment by harshavardhana** [comment]
> can you give me more directions, how I can fix it?

you need to provide fresh drives for going from single drive to multiple drives - you need migrate `mc mirror`

**Comment by alirezarahmani** [comment]
> > can you give me more directions, how I can fix it?
> 
> you need to provide fresh drives for going from single drive to multiple drives - you need migrate `mc mirror`

I do not want multiple drives, I just stopped to renew SSL and start again it does not work. that is all

**Comment by harshavardhana** [comment]
> > > can you give me more directions, how I can fix it?
> > 
> > 
> > you need to provide fresh drives for going from single drive to multiple drives - you need migrate `mc mirror`
> 
> I do not want multiple drives, I just stopped to renew SSL and start again it does not work. that is all

Share your command line @alirezarahmani ?

**Comment by alirezarahmani** [comment]
> > > > can you give me more directions, how I can fix it?
> > > 
> > > 
> > > you need to provide fresh drives for going from single drive to multiple drives - you need migrate `mc mirror`
> > 
> > 
> > I do not want multiple drives, I just stopped to renew SSL and start again it does not work. that is all
> 
> Share your command line @alirezarahmani ?

minio.1 server --address ":443" --certs-dir /home/ubuntu/.minio/certs  /minio

**Comment by harshavardhana** [comment]
> minio.1 server --address ":443" --certs-dir /home/ubuntu/.minio/certs /minio

share your `cat /minio/.minio.sys/format.json`?

**Comment by alirezarahmani** [comment]
> > minio.1 server --address ":443" --certs-dir /home/ubuntu/.minio/certs /minio
> 
> share your `cat /minio/.minio.sys/format.json`?

{"version":"1","format":"xl","id":"fff229d9-9224-42d9-92ed-a9ed875c57a8","xl":{"version":"3","this":"5e55ebbf-d0cf-4e68-a598-ed8a74602efd","sets":[["5e55ebbf-d0cf-4e68-a598-ed8a74602efd","ef6a3e1e-6f33-4e0e-b742-a8de7f96bf00","aaa6eeaa-6a3c-4c8f-86ab-59d2a306db76","b3576d4d-0f45-4f8d-89ad-f97b0db7b19b"]],"distributionAlgo":"CRCMOD"}}

**Comment by harshavardhana** [comment]
> {"version":"1","format":"xl","id":"fff229d9-9224-42d9-92ed-a9ed875c57a8","xl":{"version":"3","this":"5e55ebbf-d0cf-4e68-a598-ed8a74602efd","sets":[["5e55ebbf-d0cf-4e68-a598-ed8a74602efd","ef6a3e1e-6f33-4e0e-b742-a8de7f96bf00","aaa6eeaa-6a3c-4c8f-86ab-59d2a306db76","b3576d4d-0f45-4f8d-89ad-f97b0db7b19b"]],"distributionAlgo":"CRCMOD"}}

This drive was already used in a 4 drive setup @alirezarahmani - you cannot re-use it with single drive mode.

**Comment by alirezarahmani** [comment]
how I should use it? 
which command should I run?

**Comment by alirezarahmani** [comment]
> > {"version":"1","format":"xl","id":"fff229d9-9224-42d9-92ed-a9ed875c57a8","xl":{"version":"3","this":"5e55ebbf-d0cf-4e68-a598-ed8a74602efd","sets":[["5e55ebbf-d0cf-4e68-a598-ed8a74602efd","ef6a3e1e-6f33-4e0e-b742-a8de7f96bf00","aaa6eeaa-6a3c-4c8f-86ab-59d2a306db76","b3576d4d-0f45-4f8d-89ad-f97b0db7b19b"]],"distributionAlgo":"CRCMOD"}}
> 
> This drive was already used in a 4 drive setup @alirezarahmani - you cannot re-use it with single drive mode.

how I should use it?
which command should I run?
