### ISSUE TITLE
Wrong update url

### ISSUE THREAD

**Issue by rafael-leo-almeida** [minio/minio#1009]
When run ./minio update we got **mc** update info.

In update-main.go the url minioUpdateStableURL seems to be wrong.
https://dl.minio.io:9000/updates/updates.json shoud be https://dl.minio.io:9000/updates/minio/updates.json

**Comment by harshavardhana** [comment]
> When run ./minio update we got mc update info.
> 
> In update-main.go the url minioUpdateStableURL seems to be wrong.
> https://dl.minio.io:9000/updates/updates.json shoud be https://dl.minio.io:9000/updates/minio/updates.json

Thanks this will be fixed. With the new release.
