### ISSUE TITLE
[resolved] [not our bug] 403 error when trying to read or write file in Minio server

### ISSUE THREAD

**Issue by AronT-TLV** [minio/minio#10096]
Following the instruction in [this cookbook article](https://github.com/minio/cookbook/blob/master/docs/apache-spark-with-minio.md#3-start-spark-shell) when I try the sample read test I get a 403 error
## Expected Behavior

The file should be able to read and be printed as per the test

## Current Behavior

I get the following error:
```
java.nio.file.AccessDeniedException: s3a://sparkdata/bureau_balance.csv: getFileStatus on s3a://sparkdata/bureau_balance.csv: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 570435DC55FC9B3B; S3 Extended Request ID: 4uS9WCBdlCMfYAIAWOhYJ79lHthyCS3ucJb/Dh3o51kEWYRw+1KXogUBvvM7Bv2hJkFQVXX2jds=; Proxy: null), S3 Extended Request ID: 4uS9WCBdlCMfYAIAWOhYJ79lHthyCS3ucJb/Dh3o51kEWYRw+1KXogUBvvM7Bv2hJkFQVXX2jds=:403 Forbidden
```

## Steps to Reproduce (for bugs)

1. set up Hadoop 3.2.1 and Spark version 3.0.0. Copied over latest version of relevant jars noted in cookbook, add appropriate env variables to my shell startup and checked they worked
2. Ran the Minio server on my Mac with directory `/usr/local/sparkdata` set with appropriate ownership and permissions
3. used mc config to set up 
4. created bucket sparkdata
5. tested with aws cli than I can list bucket and copy files to it
6. tested same with Minio Client
7. Ran spark shell as per the article 
8 Just as an additional check set the policy to public

## Context

Trying to get our spark tooling to use MinIO as the hdfs 
 
## Regression

It seems that way

I've seen closed tickets where this worked but perhaps they were using older versions of Spark and Hadoop

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version RELEASE.2020-07-18T18-48-16Z
minio server /usr/local/data
mc config host add minio http://127.0.0.1:9000 --api S3v4
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
[minio-obd_20200720211224.json.gz](https://github.com/minio/minio/files/4949397/minio-obd_20200720211224.json.gz)

**Comment by harshavardhana** [comment]
@AronT-TLV will get back

**Comment by harshavardhana** [comment]
I just ran this without issues with spark 2.4.x @AronT-TLV can you try with spark 2.4.x?

**Comment by AronT-TLV** [comment]
Sure @harshavardhana Let me know first which version of Hadoop you used. Thanks.

**Comment by AronT-TLV** [comment]
@harshavardhana **Update**: there was an error in my spark shell command which caused the configuration parameters not to be passed properly, so it never went to Minio, but to AWS and that's why I got the 403 error. 

I can now confirm read and write to Minio as S3 works great in Spark 3.0.0 and Hadoop 3.2.1
