### ISSUE TITLE
[wontfix] Versioning support for gateway (azure, s3)

### ISSUE THREAD

**Issue by IsNull** [minio/minio#10108]
**Versioning support for gateways unclear**

We can only use features which are not a lock-in on any specific platform, and minio is one of the best solutions to guarantee this for object-storage. The versioning feature was long awaited, but unless it is also supported in gateways (when the underlying platform supports versioning natively) its too much of a lock-in.

Currently it is unclear (from the documentation) if the gateways support versioning, and if not, if this feature is planned. Specifically: 
* Does the minio s3 gateway support versioning or is it planned?
* Does the minio azure gateway support versioning or is it planned?

The documentation says `Versioning feature is only available in erasure coded and distributed erasure coded setups.` which certainly means that it is not supported when running minio with a mounted folder...

**Desired Solution**

- Be more specific in the Gateway documentation what each gateway supports in regard to Object-Locking and Versioning
- Support versioning on gateways when the underlying service provides versioning aswell (s3, azure).

**Alternative Solution**
Without versioning support for the gateways, we can not embrace the versioning feature in minio. Because one key feature of minio is that we can transparently choose if minio runs standalone or as gateway. We need to guarantee that our systems run with minio standalone or when in gateway mode - so we can only use features that are supported everywhere.

**Comment by harshavardhana** [comment]
@IsNull we will not be supporting versioning for azure, s3 gateway implementations.  Gateway implementations are feature-complete and frozen not taking anymore feature requests.

**Comment by IsNull** [comment]
Thanks for the fast & clear response.
