### ISSUE TITLE
Install minio on windows server 2016

### ISSUE THREAD

**Issue by chalkwu** [minio/minio#10109]
When I install minio on windows server 2016 with command
.\minio.exe server (mypath)  and I encount the exception as below:

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unexpected return pc for runtime.asmstdcall called from 0x11
stack: frame={sp: 0x379fd20, fp:0x379fd30} stack=[0x0, 0x379ff30...
...
]
rax 0x0
rbx 0x356e0c8
rcx 0x358ff80
rdi 0x215000
rsi 0x379fe60
rbp 0x379fe28
rsp0x379fd18
r8 0x4
r9 0x379fea0
r10 0x8
r11 0x1d010e
r12 0x21015a0
r13 0x0
r14 0x0
r15 0x2030000
rip 0x0
rflags 0x10293
cs 0x33
fs 0x53
gs 0x2b
====================================

How to fix this? Pls help.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
It seems that you are not the first to see this: https://github.com/golang/go/issues/21060

It doesn't appear there is much we can do from here. You are welcome to open an issue on the Go project and assist them with debugging the issue if it reproduces on several systems.

Remember to fill out the information in when reporting. While I am unsure it will help this time it always makes it easier to help.

**Comment by chalkwu** [comment]
Thank you so much for your quick reply. I am a newee of github and a starter of minio. You are so kind, thank you.

**Comment by klauspost** [comment]
Sorry for not being able to help directly. Hope you figure it out.

**Comment by mt-mithril** [comment]
I have tested on an 128g ram server and I successfully reproduced the problem. I tried to compile a 32bit version and it succeed. I think the reason  for this problem may related to wrong CPU settings in bios like Virtualization settings, etc. I hope this can help you!
