### ISSUE TITLE
[faq] can mc client connect to amazon S3 and Aliyun OSS?

### ISSUE THREAD

**Issue by hillbun** [minio/minio#10116]
can mc client connect to amazon S3 and Aliyun OSS?

or mc is just a client of minio?

**Comment by kannappanr** [comment]
It can be used against any S3 server. Please look at the documentation here https://docs.minio.io/docs/minio-client-quickstart-guide.html . Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further such questions
