### ISSUE TITLE
Deleted objects don't free space

### ISSUE THREAD

**Issue by fwiethof** [minio/minio#10113]
## Expected Behavior

When I remove objects with mc rm, the free space reported by mc admin info server should go up.
When I remove objects with mc rm, the free space on the /export volume of my Minio pods should go up.

## Current Behavior

When I remove objects,  mc du reports that the used space goes down.
However, mc admin info server and df -h /export values don't change.

## Possible Solution

Unknown.

## Steps to Reproduce (for bugs)

mc rm <some objects>
mc admin info server
df -h /export on the pod

## Context

I am using Minio as object storage backend for GitLab on K8s.
GitLab registry images filled all of the Minio disk space.
After running GitLab garbage collection, I noticed that this does not help.

## Regression

Unknown.

## Your Environment

Minio RELEASE.2019-08-07T01-59-21Z

**Comment by harshavardhana** [comment]
> Minio RELEASE.2019-08-07T01-59-21Z

@fwiethof 1yr+ old release please upgrade

**Comment by fwiethof** [comment]
Good point.
I will do.
By the way, recreating all the pods solved the issue.

**Comment by harshavardhana** [comment]
> Good point.
> I will do.
> By the way, recreating all the pods solved the issue.

Yes that is because @fwiethof `.minio.sys/tmp` is cleared upon restart

**Comment by fwiethof** [comment]
Thanks for the insight.
By the way, is there any way to trigger free space recalculation other than recreating the pods?
I did not find this in the docs.

**Comment by harshavardhana** [comment]
> Thanks for the insight.
> By the way, is there any way to trigger free space recalculation other than recreating the pods?
> I did not find this in the docs.

mc admin info --json - provides you available free space per drive @fwiethof - you can also monitor that in prometheus.
