### ISSUE TITLE
bucket creation fails

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1011]
PUT operations fail during bucket creation if content-length is not available in headers.
It works on aws s3

**Comment by harshavardhana** [comment]
> PUT operations fail during bucket creation if content-length is not available in headers.
> It works on aws s3

Yes this has to be changed to verifying if body is available and then verifying Content-Length. But i wonder this was reproducible only on minio-js ? the reason other languages work is all other are setting Content-Length=0 if there is no body.

**Comment by harshavardhana** [comment]
> PUT operations fail during bucket creation if content-length is not available in headers.
> It works on aws s3

Looks like the code is correct in validating if there is a Body. Can you verify if 'js' sending a body? 

```
    // if body of request is non-nil then check for validity of Content-Length
    if req.Body != nil {
        /// if Content-Length missing, deny the request
        if req.Header.Get("Content-Length") == "" {
            writeErrorResponse(w, req, MissingContentLength, req.URL.Path)
            return
        }
```

**Comment by krishnasrinivas** [comment]
I just saw that there is a bug in minio-js where it does not set content-length for non-standard regions (i.e the request will have body but no content-length header).
But this request was for standard region where would be no body and no content-length.

Maybe in minio-server req.Body contains a valid reader but without any data in it.

**Comment by harshavardhana** [comment]
I don't think that is the problem. I haven't been able to reproduce this on minio python and java.. and also golang.  Can you check again ?.

I don't think Golang HTTP server is designed in such a way. You can really crash a server by sending a large request if one has to read and validate the length of incoming request.

**Comment by harshavardhana** [comment]
Another possible thing on why Amazon S3 server works is since it does chunked encoding on the incoming request, so a prior Content-Length might not be a requirement. 

I will verify and see what else is different.

**Comment by harshavardhana** [comment]
Was able to reproduce, the problem is in verifying 'req.Body' as non-nil since req.Body is an interface the backing pointer struct will always provide a non-nil value. This is the same problem of custom errors being thrown back by error interface, one cannot really validate them properly.

**Comment by harshavardhana** [comment]
All other HTTP clients are setting Content-Length=0 for an empty body internally with in their implementation. So it would work.
