### ISSUE TITLE
[resolved] Cluster unresponsive after one node down

### ISSUE THREAD

**Issue by Eldorico** [minio/minio#10110]
We have a 4 virtual servers cluster on openstack, with a Debian 10 image containing a 80Gb disk. (no volume attached). 

In order to upgrade the hypervisor, we shotdown a minio vm server.  Cluster began to be very slow and our users experienced a lot of 504. (Our 4 virtual servers are behind an haproxy server with a 50 seconds timeout).  Even `mc admin info storage2` couldnt respond and printed `mc: <ERROR>  <...> Failed to parse server response.`  

Everything went fine only when the shotdown node went up. 

## Expected Behavior
We expect the cluster still be reliable when one node is powered off. 

## Current Behavior
The cluster went too slow or unresponsive. 

## Possible Solution
We dont know minio very much and dont know what happened. We searched a manner in telling minio that a server is down and should be considered as it. Maybe is there some timeout in minio to reduce? Maybe label a minio instance as "in maintenance" or something like that? 

We know that our version is not fully updated. (it is from january). Maybe upgrading corrects the problem? (We have 3 production clusters an 1 test cluster). And are affraid to update a cluster from an mc client that has access to all cluster. 

## Steps to Reproduce (for bugs)
1. Create 4 vms within the same network
2. Configure an haproxy with a roundrobin to the minios servers on port 9000
3. Create a bucket and some files
4. Shutdown a node.  `openstack server stop myNode`
5. Cluster becomes slow. 
6. Boot the powered off node. The cluster becomes fast
7. If we systemctl stop minio on a node. The cluster stays fast. 

In fact, we think the problem is when a myNode doesnt ping anymore that the problem occurs. :monocle_face: 

## Context
We would like to be able to shutdown our vms in order to upgrade the hypervisors for example. Or simply shutdown some vms for maintenance, without disturbing the server. 

## Regression
?

## Your Environment
```bash 
root@dockerdev-302:~# minio --version
minio version RELEASE.2020-01-25T02-50-51Z
```

4 virtual machines having one minio instance each. Same network. 
```bash
root@dockerdev-302:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@dockerdev-302:~# uname -a
Linux dockerdev-302 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
root@dockerdev-302:~# 
```

Some logs when a machine doesnt ping
```bash 
Jul 22 12:42:21 dockerdev-302 minio[1295]: API: SYSTEM()
Jul 22 12:42:21 dockerdev-302 minio[1295]: Time: 12:42:21 CEST 07/22/2020
Jul 22 12:42:21 dockerdev-302 minio[1295]: DeploymentID: c9e19c0b-6e3c-46f1-96c7-4525f23d95b5
Jul 22 12:42:21 dockerdev-302 minio[1295]: Error: Post https://minio2.greenstorage.mycompany.com:9000/minio/peer/v6/backgroundhealstatus?: dial tcp 10.4.46.64:9000: connect: no route to host
Jul 22 12:42:21 dockerdev-302 minio[1295]:        3: cmd/notification.go:258:cmd.(*NotificationSys).BackgroundHealStatus()
Jul 22 12:42:21 dockerdev-302 minio[1295]:        2: cmd/admin-handlers.go:918:cmd.adminAPIHandlers.BackgroundHealStatusHandler()
Jul 22 12:42:21 dockerdev-302 minio[1295]:        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
[...]
Jul 22 12:42:28 dockerdev-302 minio[1295]: API: SYSTEM()
Jul 22 12:42:28 dockerdev-302 minio[1295]: Time: 12:42:28 CEST 07/22/2020
Jul 22 12:42:28 dockerdev-302 minio[1295]: DeploymentID: c9e19c0b-6e3c-46f1-96c7-4525f23d95b5
Jul 22 12:42:28 dockerdev-302 minio[1295]: Error: Post https://minio2.greenstorage.mycompany.com:9000/minio/peer/v6/backgroundopsstatus?: dial tcp 10.4.46.64:9000: connect: no route to host
Jul 22 12:42:28 dockerdev-302 minio[1295]:        2: cmd/notification.go:276:cmd.(*NotificationSys).BackgroundOpsStatus()
Jul 22 12:42:28 dockerdev-302 minio[1295]:        1: cmd/daily-lifecycle-ops.go:84:cmd.startDailyLifecycle()
[...]
```

**Comment by harshavardhana** [comment]
Lots of fixes gone in related to networking issues fixed in recent releases, please upgrade.

#10058 
#9858 
#9808
