### ISSUE TITLE
S3 Gateway can not delete folders

### ISSUE THREAD

**Issue by diemus** [minio/minio#10122]
I have a s3 compatible service, when i use minio as a gateway and try to delete a folder, it report an error `Functionality not implemented`, i thought it was a problem of my s3 compatible service. but when i change the service to minio, the gateway still report `Functionality not implemented` .  the mc client can delete folder successfully

#### version
RELEASE.2020-05-16T01-33-21Z

#### how to reproduce
run minio as s3 compatible service and run a minio s3 gateway

**Comment by harshavardhana** [comment]
> RELEASE.2020-05-16T01-33-21Z

Use the latest version and try again we have a plethora of CI tests to test S3 gateway + MinIO as backend.

**Comment by diemus** [comment]
@harshavardhana  different problem with latest version. the webrpc request will stuck in pending status when you try to delete a folder

#### version
RELEASE.2020-07-24T22-43-05Z

**Comment by harshavardhana** [comment]
> @harshavardhana different problem with latest version. the webrpc request will stuck in pending status when you try to delete a folder
> 
> #### version
> RELEASE.2020-07-24T22-43-05Z

It won't be stuck do you have reduced permissions while communicating with the credentials to the backend?

**Comment by diemus** [comment]
it's a S3 gateway + MinIO as backend. so i think there is no permission problems. I can delete single object with web UI , but it will stuck when I delete a folder.

**Comment by harshavardhana** [comment]
> it's a S3 gateway + MinIO as backend. so i think there is no permission problems. I can delete single object with web UI , but it will stuck when I delete a folder.

can you describe your setup further? with some more description? is your backend MinIO also on the same version as gateway?

**Comment by diemus** [comment]
no ,the backend is still RELEASE.2020-05-16T01-33-21Z.  they are used in production, so I did not update them.
I could try to build another one to test this. by the way , I can delete folder by mc rm.

**Comment by harshavardhana** [comment]
> no ,the backend is still RELEASE.2020-05-16T01-33-21Z. they are used in production, so I did not update them.
> I could try to build another one to test this. by the way , I can delete folder by mc rm.

most probably because Gateway now relies on versioning API to work and it may not work with 05-16 release, you should use the same gateway version with the backend you are using.

**Comment by diemus** [comment]
the problem is I'm using S3 gateway against another s3 compatible service, not minio itself. I just us minio to test to exclude this factor. it stuck with that S3  compatible service too

**Comment by diemus** [comment]
not working with latest version, still stuck in pending

**Comment by harshavardhana** [comment]
> the problem is I'm using S3 gateway against another s3 compatible service, not minio itself. I just us minio to test to exclude this factor. it stuck with that S3 compatible service too

As I said it needs versioning API @diemus

**Comment by diemus** [comment]
i don't think it's problem with versioning api , the tcpdump does not shows any request to the real backend. when I delete a single object it does.
