### ISSUE TITLE
BackgroundHeal not work 

### ISSUE THREAD

**Issue by xiaosong135** [minio/minio#10125]
## Expected Behavior
Damaged files can be heal every 30 days

## Current Behavior
BackgroundHeal not work 

## Possible Solution
The healSequence with clientToken = "0000-0000-0000-0000" is being loaded into ‘globalBackgroundHealState’ by ‘initBackgroundHealing()’,

But it was cleaned up by ‘periodicHealSeqsClean()’ after five minutes,

The background task that caused the 30-day full repair will generate an endless loop when ‘healErasureSet()’ calls ‘getHealSequenceByToken()’ and cannot be performed.

We found that 'hasEnded()' was modified in a certain version, and the second judgment condition (h.endTime.Add(keepHealSeqStateDuration).Before(now)) of the cleanup function 'periodicHealSeqsClean()' is forever true due to the unassigned value of'endTime', cause clientToken = "0000-0000-0000-0000" background tasks to be cleaned up.
since 2020.5.4 commit，
![image](https://user-images.githubusercontent.com/12624490/88363567-10a04380-cdb3-11ea-8c9a-3a3c316c6da3.png)

## Steps to Reproduce (for bugs)

1. delete some part.1 or xl.json
2.Waiting for the BackgroundHeal

## Your Environment

* Version used (`minio --version`):
The latest release
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
To be fixed in #10103
