### ISSUE TITLE
[resolved] bucket quota have no effect when using web UI

### ISSUE THREAD

**Issue by ghost** [minio/minio#10134]
bucket quota have no effect when using web UI

## Expected Behavior
- quota should be respected when uploading files using web UI
- web UI seems to allow unlimited space usage

## Current Behavior
- quota works fine with every other client I tested: WinSCP, minio-client, S3 Browser
- quota is ignored when uploading using the web GUI

## Possible Solution

Disable Web UI

## Steps to Reproduce (for bugs)

1.  create bucket
2.  set hard quota
3.  upload files far beyond quota

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-07-20T02-25-16Z
* Server setup and configuration:  4 Nodes Cluster
* Operating System and version (`uname -a`):  FreeBSD <hostname> 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

**Comment by harshavardhana** [comment]
Fixed by #10129
