### ISSUE TITLE
[resolved] unable to clear bucket quota

### ISSUE THREAD

**Issue by ghost** [minio/minio#10133]
## Expected Behavior
`mc admin bucket quota --clear tenant02/quotatest`

should remove the quota from bucket "quotatest"

## Current Behavior
above command hangs for about 1 minute and returns this error:

`minio-client: <ERROR> Unable to clear bucket quota config. Failed to parse server response: invalid character '<' looking for beginning of value.`

## Possible Solution

As a workaround, it is possible to increase the quota.

## Steps to Reproduce (for bugs)

1. Create a new bucket
2. set quota: `mc admin bucket quota --hard 1G   tenant02/quotatest`
3. write / delete some files (this step is not necessary)
4. try to remove quota (see above)

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2020-05-16T01-33-21Z
* Server setup and configuration:  4 Node-Setup, ZFS Storage backend
* Operating System and version (`uname -a`): FreeBSD <hostname> 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

**Comment by ghost** [comment]
I noticed that minio and minio-client versions differ:
pkg search ^minio
minio-2020.05.16.01.33.21      Amazon S3 compatible object storage server
minio-client-2020.06.20.00.18.43 Replacement for ls, cp, mkdir, diff and rsync commands for filesystems

Possbile cause?

**Comment by harshavardhana** [comment]
> I noticed that minio and minio-client versions differ:
> pkg search ^minio
> minio-2020.05.16.01.33.21 Amazon S3 compatible object storage server
> minio-client-2020.06.20.00.18.43 Replacement for ls, cp, mkdir, diff and rsync commands for filesystems
> 
> Possbile cause?

Yes @minidisk1147 and quotas were not supported properly in those releases. 

You should upgrade to latest.

**Comment by ghost** [comment]
Thanks, will retry when I've upgraded

**Comment by ghost** [comment]
confirming: clearing bucket quota works with server version RELEASE.2020-07-20T02-25-16Z
