### ISSUE TITLE
Error: http://MyMinioHost2:9000/MyDirPath/MINIODISK1 as has incorrect configuration     : remote server offline

### ISSUE THREAD

**Issue by mogomo** [minio/minio#10139]
When starting MinIO (from Linux shell) as distributed minio server on a 4 node setup with 4 drives each, we get errors like mentioned in issue 10033, here:  https://github.com/minio/minio/issues/10033

When running the following script:
export MINIO_ACCESS_KEY="1_MY_ACCESS_KEY_9PpgEaMdXz"
export MINIO_SECRET_KEY="1_MY_SECRET_KEY_4KqP3XayOwGhj59D3m"
**./minio server http://miniohost{1...4}/vertica_data/mogo/MINIODISK{1...4}**

This is the output:
**API: SYSTEM()
Time: 12:36:52 UTC 07/27/2020
Error: http://miniohost2:9000/vertica_data/mogo/MINIODISK1 as has incorrect configuration                 : remote server offline
       1: github.com/minio/minio@/cmd/server-main.go:493:cmd.serverMain()**

**Version used (minio --version):**   		minio version RELEASE.2020-07-24T22-43-05Z
**Operating System and version (uname -a):**	Linux myhostnamexyz 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Server setup and configuration:**		Installed MinIO on 4 nodes (miniohost1 - miniohost4), 
Each with 4 directories: /vertica_data/mogo/MINIODISK1 - /vertica_data/mogo/MINIODISK4

**Comment by vadmeste** [comment]
@mogomo it could be a normal thing. What matters is that when you start all servers and run `mc admin info`, all nodes should be up.

**Comment by mogomo** [comment]
Don't think this is normal.
The node miniohost1 is repeatedly throwing the same error about miniohost2 as shown above all the time.
While each of the other 3 nodes say that it "wait for a minimum of 8 disks to come online".

**Comment by vadmeste** [comment]
@mogomo most likely, one or more nodes are unreachable. You need to check your network configuration.

**Comment by harshavardhana** [comment]
Check your firewall configuration enable port 9000, looks like a simple network issue.

Also make sure that your host is not resolving to 127.0.0.1
