### ISSUE TITLE
minio Object lifecycle management like AWS S3 implementation

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10136]
do minio plan to implement the full feature of https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> do minio plan to implement the full feature of https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html
> 

Yes the only thing right now which we don't implement is transition of objects which 
will be implemented in the future as a tiering feature.

We will not be implementing cleanup of old multipart objects which we automatically
already do once in 24hrs.
