### ISSUE TITLE
[resolved] Allow initial deployment with few disks offline

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#10132]
**Is your feature request related to a problem? Please describe.**
Currently, when a minio cluster is first deployed it requires that all the disks be online. In a very large setup, it might be hard to do that.

**Describe the solution you'd like**
Minio should be deployed if there is enough write quorum on all the erasure sets and not necessarily all disks are online.

**Comment by harshavardhana** [comment]
This feature is added and fixed in 74116204ced74b2516a3f681896b5a28f1dec6b2 #10273
