### ISSUE TITLE
please reduce your request

### ISSUE THREAD

**Issue by ufLearn** [minio/minio#10143]
I want to support concurrent upload, can support concurrent upload

Now it's multithreaded uploads, sleeping 10-1000

Problems occurred: ErrorResponse(code = SlowDown, message = Please reduce your request
response={code=503
        at io.minio.MinioClient.execute(MinioClient.java:1211)
        at io.minio.MinioClient.execute(MinioClient.java:1236)

I'd like to know about the performance of Minio. Is there any reference material that can help me, thanks

**Comment by harshavardhana** [comment]
@ufLearn you should analyze your network here.

Also please use the issue template to provide us your MinIO version,  a sample reproducer and also describe the setup type.

Will close this issue as incomplete please provide more infor.
