### ISSUE TITLE
Allow to contact STS internally from WebRPC

### ISSUE THREAD

**Issue by sushiMix** [minio/minio#10148]
**Is your feature request related to a problem? Please describe.**
I'd like to use the STS feature to allow OIDC connexion from MinIO Browser without needing a specific domain.
I'm currently only routing /minio to expose the MinIO Browser. I have other applications in other paths.
Now I need to expose / for MinIO STS.

**Describe the solution you'd like**
web-handlers.go#LoginSTS should be able to call the local STS endpoint. (default behavior or with a configuration flag) instead of calling with the incoming domain (which means calling the frontal load balancer in HA mode).

**Describe alternatives you've considered**
Expose the STS endpoint on a subpath to allow a path routing capability

**Additional context**
I'm exposing the minio cluster on Kubernetes

**Comment by harshavardhana** [comment]
No MinIO is not an nginx server, it requires exclusive access to path / .

We have zero reason to do this, we have closed many issues like this in the past please look them up on why we are not interested in changing the routing rules here.
