### ISSUE TITLE
[FAQ] minio support of add user defined metadata for object like AWS S3

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10140]
is there any code sample for this and does minio support this? and also object taging?

    /**
     * <p>A map of metadata to store with the object in S3.</p>
     */
    inline const Aws::Map<Aws::String, Aws::String>& GetMetadata() const{ return m_metadata; }

    /**
     * <p>A map of metadata to store with the object in S3.</p>
     */
    inline bool MetadataHasBeenSet() const { return m_metadataHasBeenSet; }

    /**
     * <p>A map of metadata to store with the object in S3.</p>
     */
    inline void SetMetadata(const Aws::Map<Aws::String, Aws::String>& value) { m_metadataHasBeenSet = true; m_metadata = value; }

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Yes you need to set x-amz-meta-key: value when uploading content.

This is as simple as https://docs.minio.io/docs/golang-client-api-reference.html#PutObject check the options.UserMetadata

**Comment by gwnet** [comment]
@harshavardhana buddy, is there workable C++ client SDK for minio?

**Comment by harshavardhana** [comment]
> @harshavardhana buddy, is there workable C++ client SDK for minio?

No @gwnet it has not been priority for us. Most cloud native apps are written in Go, and machine learning apps in Java and Python. Covers most of the modern applications.

We recommend using AWS SDK C++ library.

**Comment by gwnet** [comment]
@harshavardhana buddy
I try to run AWS S3 client example to my localhost simple minio on windows. but it failed with network issue. it has no network overhead, just local machine.


-		Aws::Client::AWSError<enum Aws::S3::S3Errors>	{m_errorType=NETWORK_CONNECTION (99) m_exceptionName="" m_message="Encountered network error when sending http request" ...}	Aws::Client::AWSError<enum Aws::S3::S3Errors>
		m_errorType	NETWORK_CONNECTION (99)	Aws::S3::S3Errors
+		m_exceptionName	""	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+		m_message	"Encountered network error when sending http request"	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+		m_remoteHostIpAddress	""	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+		m_requestId	""	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
+		m_responseHeaders	{ size=0 }	std::map<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>,std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>,std::less<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>>,Aws::Allocator<std::pair<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>> const ,std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>>>>
		m_responseCode	REQUEST_NOT_MADE (-1)	Aws::Http::HttpResponseCode
		m_isRetryable	true	bool
		m_errorPayloadType	NOT_SET (0)	Aws::Client::ErrorPayloadType
+		m_xmlPayload	{m_doc=0x0000000000000000 <NULL> }	Aws::Utils::Xml::XmlDocument
+		m_jsonPayload	{m_value=0x0000000000000000 <NULL> m_wasParseSuccessful=true m_errorMessage="" }	Aws::Utils::Json::JsonValue



![image](https://user-images.githubusercontent.com/7543276/89001315-7c8f2880-d32c-11ea-9d5a-62d35535ef53.png)

**Comment by harshavardhana** [comment]
> @harshavardhana buddy
> I try to run AWS S3 client example to my localhost simple minio on windows. but it failed with network issue. it has no network overhead, just local machine.
> 
> 
> -		Aws::Client::AWSError<enum Aws::S3::S3Errors>	{m_errorType=NETWORK_CONNECTION (99) m_exceptionName="" m_message="Encountered network error when sending http request" ...}	Aws::Client::AWSError<enum Aws::S3::S3Errors>
> 		m_errorType	NETWORK_CONNECTION (99)	Aws::S3::S3Errors
> +		m_exceptionName	""	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
> +		m_message	"Encountered network error when sending http request"	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
> +		m_remoteHostIpAddress	""	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
> +		m_requestId	""	std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>
> +		m_responseHeaders	{ size=0 }	std::map<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>,std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>,std::less<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>>,Aws::Allocator<std::pair<std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>> const ,std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>>>>
> 		m_responseCode	REQUEST_NOT_MADE (-1)	Aws::Http::HttpResponseCode
> 		m_isRetryable	true	bool
> 		m_errorPayloadType	NOT_SET (0)	Aws::Client::ErrorPayloadType
> +		m_xmlPayload	{m_doc=0x0000000000000000 <NULL> }	Aws::Utils::Xml::XmlDocument
> +		m_jsonPayload	{m_value=0x0000000000000000 <NULL> m_wasParseSuccessful=true m_errorMessage="" }	Aws::Utils::Json::JsonValue
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/7543276/89001315-7c8f2880-d32c-11ea-9d5a-62d35535ef53.png)
> 

Please join our slack for Q/A - GitHub is not the place for Q/A - thanks

**Comment by gwnet** [comment]
@harshavardhana I download .NET SDK test sample. it failed too. I know this is my network issue. because if i connect the AWS website it works. and I can control my minio with webUI.

but how to work around it then i can debug it easily with my laptop from company?

ConnectionException: MinIO API responded with message=Connection error: An attempt was made to access a socket in a way forbidden by its access permissions An attempt was made to access a socket in a way forbidden by its access permissions. Status code=0, response=An attempt was made to access a socket in a way forbidden by its access permissions An attempt was made to access a socket in a way forbidden by its access permissions, content=

**Comment by gwnet** [comment]
@harshavardhana  .NET SDK is my issue, I forget specify the 9000 port. but i can reproduce the AWS C++ SDK cannot work well with minio. please help me review the code.
```
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX - License - Identifier: Apache - 2.0

//snippet-start:[s3.cpp.put_object.inc]
#include <iostream>
#include <fstream>
#include <sys/stat.h>
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/PutObjectRequest.h>
#include <awsdoc/s3/s3_examples.h>

#include <aws/core/auth/AWSCredentialsProvider.h>
//snippet-end:[s3.cpp.put_object.inc]

using namespace Aws::S3;
using namespace Aws::S3::Model;

/* ////////////////////////////////////////////////////////////////////////////
 * Purpose: Adds an object to an Amazon S3 bucket.
 *
 * Prerequisites: An Amazon S3 bucket and the object to be added.
 *
 * Inputs:
 * - bucketName: The name of the bucket.
 * - objectName: The name of the object.
 * - region: The AWS Region for the bucket.
 *
 * Outputs: true if the object was added to the bucket; otherwise, false.
 * ///////////////////////////////////////////////////////////////////////// */

// snippet-start:[s3.cpp.put_object.code]
bool AwsDoc::S3::PutObject(const Aws::String& bucketName, 
    const Aws::String& objectName,
    const Aws::String& region)
{
    // Verify that the file exists.
    struct stat buffer;

    if (stat(objectName.c_str(), &buffer) == -1)
    {
        std::cout << "Error: PutObject: File '" <<
            objectName << "' does not exist." << std::endl;

        return false;
    }

    Aws::Client::ClientConfiguration config;

    if (!region.empty())
    {
        config.region = region;
    }

    config.endpointOverride = "127.0.0.1:9000";  // S3服务器地址和端口
    config.scheme = Aws::Http::Scheme::HTTP;
    config.verifySSL = false;
    //Aws::Auth::AWSCredentials cred("RPW421T9GSIO4A45Y9ZR", "2owKYy9emSS90Q0pXuyqpX1OxBCyEDYodsiBemcq");  // 认证的Key
    //m_client = new S3Client(Aws::Auth::AWSCredentials("test", "12345678"), cfg, false, false);


    Aws::S3::S3Client s3_client(Aws::Auth::AWSCredentials("minioadmin", "minioadmin"), config);
    //Aws::S3::S3Client s3_client(config);
    
    Aws::S3::Model::PutObjectRequest request;
    request.SetBucket(bucketName);
    //request.SetKey(objectName);
    request.SetKey("object1");

    std::shared_ptr<Aws::IOStream> input_data = 
        Aws::MakeShared<Aws::FStream>("SampleAllocationTag", 
            objectName.c_str(), 
            std::ios_base::in | std::ios_base::binary);

    request.SetBody(input_data);

    Aws::S3::Model::PutObjectOutcome outcome = 
        s3_client.PutObject(request);

    if (outcome.IsSuccess()) {

        std::cout << "Added object '" << objectName << "' to bucket '"
            << bucketName << "'.";
        return true;
    }
    else 
    {
        std::cout << "Error: PutObject: " << 
            outcome.GetError().GetMessage() << std::endl;
       
        return false;
    }
}

int main()
{
    Aws::SDKOptions options;


    Aws::InitAPI(options);
    {
        const Aws::String bucket_name = "test";
        const Aws::String object_name = "C:\\tmp\\1.txt";
        const Aws::String region = "";

        if (!AwsDoc::S3::PutObject(bucket_name, object_name, region)) {
            
            return 1;
        }
    }
    Aws::ShutdownAPI(options);

    return 0;
}
// snippet-end:[s3.cpp.put_object.code]
```

**Comment by Hudayberdyyev** [comment]
I just started to study in this way. so forgive me if the question is completely stupid. but I want to understand the point. @harshavardhana why we need to set user meta data ? please explain to me why we need it ?
