### ISSUE TITLE
[resolved] Performance Test cause panic

### ISSUE THREAD

**Issue by huangpanpan** [minio/minio#10144]
1、distributed erasure coding with cache
2、There was a runtime error when testing perfomance.
![panic](https://user-images.githubusercontent.com/17831777/88617314-e6a79380-d0c8-11ea-800d-aac62a043e5b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2020-07-02T00-15-09Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Please upgrade to latest and run the same tests.. also the crash location is an empty line in the code. So not sure what might be causing this.

**Comment by huangpanpan** [comment]
> Please upgrade to latest and run the same tests.. also the crash location is an empty line in the code. So not sure what might be causing this.
The minio version is RELEASE.2020-07-02T00-15-09Z

**Comment by harshavardhana** [comment]
> > Please upgrade to latest and run the same tests.. also the crash location is an empty line in the code. So not sure what might be causing this.
> > The minio version is RELEASE.2020-07-02T00-15-09Z

Upgrade to latest release @huangpanpan
