### ISSUE TITLE
[wontfix] Can Minio implement Hadoop's FileSystem to replace HDFS?

### ISSUE THREAD

**Issue by fengzhongfeixu** [minio/minio#10153]
**Can Minio implement Hadoop's FileSystem to replace HDFS? Just like seaweedfs's SeaweedFileSystem.**[https://github.com/chrislusf/seaweedfs/wiki/Hadoop-Compatible-File-System](url)

**Comment by harshavardhana** [comment]
No we will not @fengzhongfeixu - use `fs.s3a`
