### ISSUE TITLE
[stale] Minio Server Pod has an error log

### ISSUE THREAD

**Issue by enayzhu** [minio/minio#10156]
Use mc client to upload a small file without success within 30s (can be successful under normal circumstances). An error log was found on the minio pod.
The file was not uploaded successfully within 30 seconds. I stopped this operation.
After 3 attempts, the file was successfully uploaded in 30s.

Four minio are deployed in a distributed manner, namely minio-0 minio-1 minio-2 minio-3

Log collected on minio-1
{"deploymentid":"231cc4f4-b845-41fc-88d7-162efbb0e723","level":"ERROR","errKind":"MINIO","time":"2020-07-21T10:47:59.680747963Z","api":{"name":"GetObject","args":{"bucket":"eric-pc-mm-ebm","object":"A20200720.1600+0200-20200720.1615+0200_4_ebs.92.enc"}},"remotehost":"192.168.187.246","host":"eric-data-object-storage-mn-1.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000","requestID":"1623BECB5E00D7A3","userAgent":"MinIO (linux; amd64) minio-go/v6.0.26 mc/DEVELOPMENT.GOGET","error":{"message":"Post \"https://eric-data-object-storage-mn-2.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/minio/storage/export/v14/readall?disk-id=2740c16c-060e-41ff-ba2b-08fd54476077\u0026file-path=A20200720.1600%2B0200-20200720.1615%2B0200_4_ebs.92.enc%2Fxl.json\u0026volume=eric-pc-mm-ebm\": EOF","source":["/opt/go/src/github.com/minio/minio/cmd/xl-v1-utils.go:170:cmd.readXLMeta()","/opt//go/src/github.com/minio/minio/cmd/xl-v1-utils.go:193:cmd.readAllXLMetadata.func1()","/opt/go/src/github.com/minio/minio/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()"],"variables":{"disk":"https://eric-data-object-storage-mn-2.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/export"}}}
{"deploymentid":"231cc4f4-b845-41fc-88d7-162efbb0e723","level":"ERROR","errKind":"MINIO","time":"2020-07-21T10:48:17.681193882Z","api":{"name":"GetObject","args":{"bucket":"eric-pc-mm-ebm","object":"A20200720.1545+0200-20200720.1600+0200_4_ebs.87.enc"}},"remotehost":"192.168.187.246","host":"eric-data-object-storage-mn-1.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000","requestID":"1623BECE054D7131","userAgent":"MinIO (linux; amd64) minio-go/v6.0.26 mc/DEVELOPMENT.GOGET","error":{"message":"Post \"https://eric-data-object-storage-mn-0.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/minio/storage/export/v14/readall?disk-id=38587bc6-3872-465b-b6f1-76bc2a8d1f9b\u0026file-path=A20200720.1545%2B0200-20200720.1600%2B0200_4_ebs.87.enc%2Fxl.json\u0026volume=eric-pc-mm-ebm\": http: server closed idle connection","source":["/opt/go/src/github.com/minio/minio/cmd/xl-v1-utils.go:170:cmd.readXLMeta()","/opt//go/src/github.com/minio/minio/cmd/xl-v1-utils.go:193:cmd.readAllXLMetadata.func1()","/opt/go/src/github.com/minio/minio/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()"],"variables":{"disk":"https://eric-data-object-storage-mn-0.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/export"}}}

Log collected on minio-3
{"deploymentid":"231cc4f4-b845-41fc-88d7-162efbb0e723","level":"ERROR","errKind":"MINIO","time":"2020-07-21T10:48:19.581951276Z","api":{"name":"GetBucketLocation","args":{"bucket":"eric-pc-mm-ebm"}},"remotehost":"192.168.187.246","host":"eric-data-object-storage-mn-3.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000","requestID":"1623BECF5F221199","userAgent":"MinIO (linux; amd64) minio-go/v6.0.26 mc/DEVELOPMENT.GOGET","error":{"message":"Post \"https://eric-data-object-storage-mn-1.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/minio/storage/export/v14/statvol?disk-id=3d515d8b-40da-4fbf-96b7-de3fb20a36f6\u0026volume=eric-pc-mm-ebm\": EOF","source":["/opt/go/src/github.com/minio/minio/cmd/api-errors.go:1786:cmd.toAPIErrorCode()","/opt/go/src/github.com/minio/minio/cmd/api-errors.go:1811:cmd.toAPIError()","/opt/go/src/github.com/minio/minio/cmd/bucket-handlers.go:174:cmd.objectAPIHandlers.GetBucketLocationHandler()","net/http/server.go:2012:http.HandlerFunc.ServeHTTP()"]}}
{"deploymentid":"231cc4f4-b845-41fc-88d7-162efbb0e723","level":"ERROR","errKind":"MINIO","time":"2020-07-21T10:48:23.182154948Z","api":{"name":"HeadObject","args":{"bucket":"eric-pc-mm-ebm","object":"A20200720.1700+0200-20200720.1715+0200_5_ebs.114.enc"}},"remotehost":"192.168.187.246","host":"eric-data-object-storage-mn-3.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000","requestID":"1623BECCF927DFF6","userAgent":"MinIO (linux; amd64) minio-go/v6.0.26 mc/DEVELOPMENT.GOGET","error":{"message":"Post \"https://eric-data-object-storage-mn-1.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/minio/storage/export/v14/readall?disk-id=3d515d8b-40da-4fbf-96b7-de3fb20a36f6\u0026file-path=A20200720.1700%2B0200-20200720.1715%2B0200_5_ebs.114.enc%2Fxl.json\u0026volume=eric-pc-mm-ebm\": EOF","source":["/opt/go/src/github.com/minio/minio/cmd/xl-v1-utils.go:170:cmd.readXLMeta()","/opt/go/src/github.com/minio/minio/cmd/xl-v1-utils.go:193:cmd.readAllXLMetadata.func1()","/opt/go/src/github.com/minio/minio/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()"],"variables":{"disk":"https://eric-data-object-storage-mn-1.eric-data-object-storage-mn-svc.pcc.svc.cluster.local:9000/export"}}}

Other minio did not see related log.
## Expected Behavior

File upload completed within 30 seconds
minio has no error log

## Current Behavior

After startup, it works well, and then starts uploading.

## Steps to Reproduce (for bugs)

1.Start the environment and all PODS are in good condition
2.Upload a file
3.Small probability of issues

## Regression
 No

## Your Environment

* Version used (`minio --version`):  RELEASE.2020-02-27T00-23-05Z-3-g46b6274
* Server setup and configuration:
* Operating System and version (`uname -a`): linux

**Comment by harshavardhana** [comment]
Please upgrade to latest and test again..

**Comment by enayzhu** [comment]
Can these two error log "EOF" and "http: server closed idle connection" indicate that there was a problem with the http connection at the time?

**Comment by enayzhu** [comment]
Can these two error log "EOF" and "http: server closed idle connection" indicate that there was a problem with the http connection at the time?

**Comment by harshavardhana** [comment]
> Can these two error log "EOF" and "http: server closed idle connection" indicate that there was a problem with the http connection at the time?

Yes but this is quite an old release you should upgrade to latest and let us know how it goes.
