### ISSUE TITLE
[wontfix] Setting short urls for objects as aliases.

### ISSUE THREAD

**Issue by megafetis** [minio/minio#10159]
**Is your feature request related to a problem? Please describe.**

Its comfortably to store objects in nested folders for manage them.
But full url become soo big. Pleace add ability to set additional urls as aliases.

**Describe the solution you'd like**

#### original public path:

`https://myminio.org/{user_id}/album/{album_id}/{img_name}.jpg`

#### short public url as alias for example:
```cs
await minio.PutObjectAsync(bucketName, objectName, filePath,contentType);
var alias_id = Guid.NewId().ToString()+".jpg";
await minio.SetObjectAliasAsync(bucketName, objectName, alias_id);
```
#### result:

`https://myminio.org/{some_guid}.jpg`

**Comment by harshavardhana** [comment]
Building a CAS system on top of MinIO is application responsibility, we will not add specialized namespaces.

We implement S3 APIs and that's where it ends.
