### ISSUE TITLE
Bucket usage metrics missing in Docker

### ISSUE THREAD

**Issue by acourtneybrown** [minio/minio#10151]
When running MinIO under Docker with a single storage disk, the bucket usage metrics never appear in the Prometheus endpoint.  After spending some time tracking this issue down, it appears to be caused by an early return in `bucketUsageMetricsPrometheus`, namely:

https://github.com/minio/minio/blob/1b6ba0d0620ae24d28ff11394f11ca304ac4c61f/cmd/metrics.go#L391-L394

## Expected Behavior

When I curl the `/minio/prometheus/metrics`, I should see the `bucket_` metrics (ie: `bucket_objects_count`, `bucket_objects_histogram` & `bucket_usage_size`).  For example,

```bash
$ curl http://localhost:9000/minio/prometheus/metrics | grep bucket_

# HELP bucket_objects_count Total number of objects in a bucket
# TYPE bucket_objects_count gauge
bucket_objects_count{bucket="foo"} 1
# HELP bucket_objects_histogram Total number of objects of different sizes in a bucket
# TYPE bucket_objects_histogram gauge
bucket_objects_histogram{bucket="foo",object_size="BETWEEN_1024_B_AND_1_MB"} 1
bucket_objects_histogram{bucket="foo",object_size="BETWEEN_10_MB_AND_64_MB"} 0
bucket_objects_histogram{bucket="foo",object_size="BETWEEN_128_MB_AND_512_MB"} 0
bucket_objects_histogram{bucket="foo",object_size="BETWEEN_1_MB_AND_10_MB"} 0
bucket_objects_histogram{bucket="foo",object_size="BETWEEN_64_MB_AND_128_MB"} 0
bucket_objects_histogram{bucket="foo",object_size="GREATER_THAN_512_MB"} 0
bucket_objects_histogram{bucket="foo",object_size="LESS_THAN_1024_B"} 0
# HELP bucket_usage_size Total bucket size
# TYPE bucket_usage_size gauge
bucket_usage_size{bucket="foo"} 2389
$
```

## Current Behavior

When running MinIO under docker with a single disk:

```bash
docker run -p 9000:9000 minio/minio:latest server /tmp/data-docker
```

even after waiting for the data usage crawler to run, using the same curl as ☝️ shows no relevant metrics:

```bash
$ curl http://localhost:9000/minio/prometheus/metrics | grep bucket_
$
```

## Possible Solution

It appears that the problem lies in `fs-v1.go` where the `totalCache.Info.LastUpdated` time is never set beyond the initial (zero) value from object creation before it is saved:

https://github.com/minio/minio/blob/1b6ba0d0620ae24d28ff11394f11ca304ac4c61f/cmd/fs-v1.go#L301-L303

In contrast to the analogous code in `erasure.go` where the `cache` object does have the associated timestamp updated before saving & writing to the `updates` channel:

https://github.com/minio/minio/blob/1b6ba0d0620ae24d28ff11394f11ca304ac4c61f/cmd/erasure.go#L323-L326

The following diff appears to resolve the problem during local development/testing, but I'm not sure if this breaks any other code or tests:

```diff
diff --git a/cmd/fs-v1.go b/cmd/fs-v1.go
index 16255bc8..2384c612 100644
--- a/cmd/fs-v1.go
+++ b/cmd/fs-v1.go
@@ -298,6 +298,7 @@ func (fs *FSObjects) CrawlAndGetDataUsage(ctx context.Context, bf *bloomFilter,
                if intDataUpdateTracker.debug {
                        logger.Info(color.Green("CrawlAndGetDataUsage:")+" Saving totals cache with %d entries", len(totalCache.Cache))
                }
+               totalCache.Info.LastUpdate = time.Now()
                logger.LogIf(ctx, totalCache.save(ctx, fs, dataUsageCacheName))
                cloned := totalCache.clone()
                updates <- cloned.dui(dataUsageRoot, buckets)
```

## Regression

Unknown

## Your Environment

* Version used (`minio --version`):  minio/minio:latest` docker image as of 7/28/2020
* Server setup and configuration:  `minio/minio:latest` docker image as of 7/28/2020
* Operating System and version (`uname -a`): Docker 2.3.0.4

**Comment by harshavardhana** [comment]
@acourtneybrown this is a correct fix please send a PR
