### ISSUE TITLE
[working as intended] minio AccessDenied when time is out of sync

### ISSUE THREAD

**Issue by zhuangchongyi** [minio/minio#10155]
error occurred
ErrorResponse(code = AccessDenied, message = Access denied
, bucketName = test3, objectName = null, resource = /test3, requestId = null, hostId = null)
request={method=HEAD, url=http://192.168.131.139:9000/test3, headers=Host: 192.168.131.139:9000
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/1.0.1
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200729T044719Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200729/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=403, headers=Accept-Ranges: bytes
Content-Length: 288
Content-Type: application/xml
Server: MinIO/RELEASE.2020-07-12T19-14-17Z
Vary: Origin
Date: Wed, 29 Jul 2020 12:47:24 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:1135)
	at io.minio.MinioClient.execute(MinioClient.java:935)
	at io.minio.MinioClient.executeHead(MinioClient.java:1204)
	at io.minio.MinioClient.bucketExists(MinioClient.java:3592)

**Comment by lydon-GH** [comment]
我也发现这个问题了，连接window没问题，但是连接到linux就有问题，同求，如何解决

**Comment by kannappanr** [comment]
@zhuangchongyi Can you please try with the latest version of minio-java ? Also, can you provide more information on your setup. What mode is minio running? When you say works in Windows and not in Linux, are you referring to the client or the server? What credentials are you using?

Please fill in as much information as possible.

**Comment by kannappanr** [comment]
Also, `play` runs on Linux and we have clients connecting from both Windows and Linux machines to play. You have to check if the user you are using has the correct privileges or not

**Comment by zhuangchongyi** [comment]
Thank you for your reply. I have solved the problem.My Minio is in the Linux environment, and the Maven dependent version of my project is 7.1.0, which indicates that I am not authorized. Then I change to the dependency of version 3.0.10, which indicates that the service time is inconsistent. Therefore, I set the Linux time and the problem is solved

**Comment by zhuangchongyi** [comment]
你看一下linux的时间对不对，不对的话你同步一下，我应该是时间的问题
你可以参考这个同步下时间 https://www.cnblogs.com/twodoge/p/11663019.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 下午5:18
收件人:&nbsp;"minio/minio"<minio@noreply.github.com&gt;;
抄送:&nbsp;"年少^_^轻狂"<1909017815@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [minio/minio] minio AccessDenied怎么解决？ (#10155)





 
我也发现这个问题了，连接window没问题，但是连接到linux就有问题，同求，如何解决

**Comment by harshavardhana** [comment]
> Thank you for your reply. I have solved the problem.My Minio is in the Linux environment, and the Maven dependent version of my project is 7.1.0, which indicates that I am not authorized. Then I change to the dependency of version 3.0.10, which indicates that the service time is inconsistent. Therefore, I set the Linux time and the problem is solved

Closing as a setup issue.
