### ISSUE TITLE
[working as intended] CloudFunctionNotifcation

### ISSUE THREAD

**Issue by 2020testuser** [minio/minio#10168]
Hi,
I want to invoke (trigger) a Knative serverless function (using the function url) when I put a file in s3 bucket.
Could anyone please let me know whether CloudFunction Notification is available in Java Minio or Go Minio ? (as it is unsupported in Python Minio).

If QueueConfigurationNotification can be used, do I need to any queue component like RabbitMQ ?
If not, could you let me know how I can trigger a function when the file is dumped (using PUT) in S3?

Thanks in advance!

**Comment by kannappanr** [comment]
@2020testuser PTAL at http://minio.github.io/minio-java/io/minio/messages/NotificationConfiguration.html . Do you want to use this against MinIO or AWS S3?

**Comment by harshavardhana** [comment]
@2020testuser we do not support CloudFunction notification we support QueueConfiguration explained in the other issues that I closed.
