### ISSUE TITLE
Python Minio  set_bucket_notification()  in Minio S3 Sandbox

### ISSUE THREAD

**Issue by 2020testuser** [minio/minio#10166]
This is related to the issue - Set notification namespace for NotificationConfiguration #6789 . The set_bucket_notification() is not working in Python as expected when using minio sandbox (play.minio.io). 
 I'm using docker minio client and server. Could anyone let me know whether this function works in Python?

## Expected Behavior
When I use set_bucket_notification() in Minio Python SDK, it should work. However, getting an error.
`from minio import Minio
from minio.error import (ResponseError, SignatureDoesNotMatch, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)

# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('play.minio.io',
               access_key='Q3AM3UQ867SPQQA43P2F',
               secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
 )
print("Connection successful")
notification = {
    'CloudFunctionConfigurations': [
        {
            'Arn': 'arn1',
            'Events': ['s3:ObjectCreated:*'],
            'Filter': {
                'Key': {
                    'FilterRules': [
                        {
                            'Name': 'suffix',
                            'Value': '.xml'
                        }
                    ]
                }
            }
           # 'CloudFunction': 'http://localhost:8000/testapi'
        }
    ]
}
try:
    minioClient.set_bucket_notification('testbucket', notification)
except ResponseError as err:
    # handle error response from service.
    print(err)`

## Current Behavior
Currently, using set_bucket_notification() in Minio Python SDK, gives an error. Below is the error msg.
`ResponseError: code: UnsupportedNotification, message: MinIO server does not support Topic or Cloud Function based notifications., bucket_name: otdatahub, object_name: None, request_id: xxx, host_id: yyy, region:`

## Steps to Reproduce (for bugs)

1. Run the below code which uses set_bucket_notification() in Minio Python SDK.

2. You will get an error.

## Your Environment

* Version used (`minio --version`): Using the latest docker minio client
* Server setup and configuration: Using the latest docker minio client
* Operating System : MAC OS

**Comment by harshavardhana** [comment]
> `ResponseError: code: UnsupportedNotification, message: MinIO server does not support Topic or Cloud Function based notifications., bucket_name: otdatahub, object_name: None, request_id: xxx, host_id: yyy, region:`

We do not support CloudFunctions you need to use is QueueConfigurations

```py
notification = {
    'QueueConfigurations': [
        {
            'Id': '1',
            'Arn': 'arn1',
            'Events': ['s3:ObjectCreated:*'],
            'Filter': {
                'Key': {
                    'FilterRules': [
                        {
                            'Name': 'prefix',
                            'Value': 'abc'
                        }
                    ]
                }
            }
        }
    ]
}

try:
    minioClient.set_bucket_notification('mybucket', notification)
except ResponseError as err:
    # handle error response from service.
    print(err)
except (ArgumentError, TypeError) as err:
    # should happen only during development. Fix the notification argument
    print(err)
```
