### ISSUE TITLE
[faq] NotificationConfiguration for MinIO

### ISSUE THREAD

**Issue by 2020testuser** [minio/minio#10171]
Since, my issue got closed , creating this to get more clarification on (https://github.com/minio/minio/issues/10168#issuecomment-666702725)[my issue answer] . Appreciate if could provide more information.

1. Since, CloudNotification is not supported in Minio, could you please let me know how the CloudFunction Configuration mentioned in the minio NotificationConfiguration can be used?

2. Is CloudFunction Configuration supported only in [Minio Java SDK](http://minio.github.io/minio-java/io/minio/messages/CloudFunctionConfiguration.html) not in Python SDK or Go SDK?

I want to use the  [NotificationConfiguration](http://minio.github.io/minio-java/io/minio/messages/NotificationConfiguration.html) IBM S3 and/or Minio S3 (whatever is supported). 

Thanks in advance!

**Comment by harshavardhana** [comment]
> Since, my issue got closed , creating this to get more clarification on ([https://github.com/minio/minio/issues/10168#issuecomment-666702725)[my](https://github.com/minio/minio/issues/10168#issuecomment-666702725)%5Bmy) issue answer] . Appreciate if could provide more information.
> 
> 1. Since, CloudNotification is not supported in Minio, could you please let me know how the CloudFunction Configuration mentioned in the minio NotificationConfiguration can be used?

Its called QueueConfiguration @2020testuser You need to use http://minio.github.io/minio-java/io/minio/messages/QueueConfiguration.html

**Comment by 2020testuser** [comment]
@harshavardhana - Thanks! This really helps.
 Regarding my other question on whether any queue component (like RabbitMQ) is needed to use QueueConfiguration. 
Also, wondering is it possible to invoke  the serverless function using the QueueConfiguration when a file is PUT in S3? This is what I'm looking for. If there is any link , could you please share?
Thanks!

**Comment by harshavardhana** [comment]
> @harshavardhana - Thanks! This really helps.
>  Regarding my other question on whether any queue component (like RabbitMQ) is needed to use QueueConfiguration. 
> Also, wondering is it possible to invoke  the serverless function using the QueueConfiguration when a file is PUT in S3? This is what I'm looking for. If there is any link , could you please share?
> Thanks!

https://docs.minio.io/docs/minio-bucket-notification-guide.html#AMQP here is how you can setup server to get the ARN

**Comment by 2020testuser** [comment]
@harshavardhana - so, looks like I need RabbitMQ or some Queue Component to use Queue Configuration.  Could you please confirm? Also, is there any link to trigger a function from the Queue when the queue is updated?  Thanks again! Appreciate your help!

**Comment by harshavardhana** [comment]
> @harshavardhana - so, looks like I need RabbitMQ or some Queue Component to use Queue Configuration. Could you please confirm? Also, is there any link to trigger a function from the Queue when the queue is updated? Thanks again! Appreciate your help!

There is no trigger you upload or delete objects the AQMP target gets notified once configured as per the AWS S3 notification style https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html this is the event message structure

**Comment by 2020testuser** [comment]
@harshavardhana - Thanks! Then, I need some AQMP component like RabbitMQ. I will check the link.

**Comment by harshavardhana** [comment]
> @harshavardhana - Thanks! Then, I need some AQMP component like RabbitMQ. I will check the link. 
> 

RabbitMQ is AMQP so that should work without any issues.
