### ISSUE TITLE
[resolved] Recursive heal does not complete

### ISSUE THREAD

**Issue by SoftBoil** [minio/minio#10179]
The "mc admin heal -r myminio" stops without error after running for a few minutes (2-15 min).
I re-run the same command multiple times.  Each time a few more files are healed but stops again after minutes.

Client output after 3 runs:
1) arq/460ac29a-6921-483b-bebd-7235b6b…F3-CBB7-4E58-9F2E-0871221229C6.pack
    28/28 objects; 28 MiB in 2562047h47m16.854775807s
Green  │ 30 │ 100.0%

2) arq/460ac29a-6921-483b-bebd-7235b6b…92-C0D9-476F-BCE9-15D6B42AD994.pack
    0/21 objects; 21 MiB in 2562047h47m16.854775807s
    │ Green  │ 23 │ 100.0%

3) arq/460ac29a-6921-483b-bebd-7235b6b…AB-D5C3-4491-8385-222131FC2632.pack
    0/158 objects; 156 MiB in 2562047h47m16.854775807s
    │ Green  │ 160 │ 100.0%

## Expected Behavior
heal runs until completion.

## Scenario
1) Server running with 6 drives, ec:2
2) Populate with files from ARQ backup program
3) Remove minio directory from 1 drive
4) After .minio.sys directory is recreated try above heal command

## Your Environment
Server: 
   Version: 2020-07-31T03:39:05Z
   Network: 1/1 OK 
   Drives: 6/6 OK 

   192 GiB Used, 3 Buckets, 63,034 Objects
   6 drives online, 0 drives offline

Client:
  Version: RELEASE.2020-07-31T23-34-13Z

**Comment by harshavardhana** [comment]
> The "mc admin heal -r myminio" stops without error after running for a few minutes (2-15 min).
> I re-run the same command multiple times. Each time a few more files are healed but stops again after minutes.
> 
> Client output after 3 runs:
> 
> 1. arq/460ac29a-6921-483b-bebd-7235b6b…F3-CBB7-4E58-9F2E-0871221229C6.pack
>    28/28 objects; 28 MiB in 2562047h47m16.854775807s
>    Green  │ 30 │ 100.0%
> 2. arq/460ac29a-6921-483b-bebd-7235b6b…92-C0D9-476F-BCE9-15D6B42AD994.pack
>    0/21 objects; 21 MiB in 2562047h47m16.854775807s
>    │ Green  │ 23 │ 100.0%
> 3. arq/460ac29a-6921-483b-bebd-7235b6b…AB-D5C3-4491-8385-222131FC2632.pack
>    0/158 objects; 156 MiB in 2562047h47m16.854775807s
>    │ Green  │ 160 │ 100.0%
> 
> ## Expected Behavior
> heal runs until completion.
> 
> ## Scenario
> 1. Server running with 6 drives, ec:2
> 2. Populate with files from ARQ backup program
> 3. Remove minio directory from 1 drive
> 4. After .minio.sys directory is recreated try above heal command
> 
> ## Your Environment
> Server:
> Version: 2020-07-31T03:39:05Z
> Network: 1/1 OK
> Drives: 6/6 OK
> 
> 192 GiB Used, 3 Buckets, 63,034 Objects
> 6 drives online, 0 drives offline
> 
> Client:
> Version: RELEASE.2020-07-31T23-34-13Z

Was this a pre-existing data? Or was it fresh content? @SoftBoil

**Comment by SoftBoil** [comment]
There are new files that were created by a backup program on the server. The files existed before the directory on one drive was removed. No new files was added since the healing attempt started.

**Comment by harshavardhana** [comment]
> There are new files that were created by a backup program on the server. The files existed before the directory on one drive was removed. No new files was added since the healing attempt started.

what I meant is did you upgrade MinIO from an earlier version like from 2months ago?

**Comment by harshavardhana** [comment]
I have tried reproducing this on my end but to no avail, @SoftBoil - are there any specific console log messages that you can share from MinIO instance? 

From what I can tell your existing data on the drives is somewhat in an inconsistent state

```
~  mc admin heal -r myminio/
 ◓  testbucket/genccode
    1/1 objects; 14 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

```
~ rm -rf  ~/fs1/testbucket/*
```

```
~ mc admin heal -r myminio/
 ◐  testbucket/zic
    401/401 objects; 74 MiB in 4s
    ┌────────┬─────┬─────────────────────┐
    │ Green  │ 403 │ 100.0% ████████████ │
    │ Yellow │   0 │   0.0%              │
    │ Red    │   0 │   0.0%              │
    │ Grey   │   0 │   0.0%              │
    └────────┴─────┴─────────────────────┘
```

**Comment by SoftBoil** [comment]
> what I meant is did you upgrade MinIO from an earlier version like from 2months ago?

It's possible that my original install was from 2 months ago.  I've been regularly updating the server with the "mc admin update" command

**Comment by harshavardhana** [comment]
> > what I meant is did you upgrade MinIO from an earlier version like from 2months ago?
> 
> It's possible that my original install was from 2 months ago. I've been regularly updating the server with the "mc admin update" command

Okay @SoftBoil is there any error on the console when you run `mc admin heal -r` ?

**Comment by SoftBoil** [comment]
> Okay @SoftBoil is there any error on the console when you run `mc admin heal -r` ?

There is no error on the console and no error in the server log (minio.log).  Is there a way to enable more extensive logging on the server side?

Right now I'm trying it again with "mc admin trace -a -v myminio".  I'll past the last two trace entries before it stopped. The start time logged in the last entry seems suspicious.

**REDACTED** [REQUEST admin.Heal] 20:09:55.650
**REDACTED** POST /minio/admin/v3/heal/?clientToken=42807101-6233-46aa-87ff-53e2d0b49609
**REDACTED** Host: **REDACTED**:9000
**REDACTED** X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
**REDACTED** X-Amz-Date: 20200803T200955Z
**REDACTED** Authorization: AWS4-HMAC-SHA256 Credential=minion/20200803//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1c462e9e737d4f75c9c120e8ed8b106caef6bf179b116020691f963d9df5d4d0
**REDACTED** Transfer-Encoding: chunked
**REDACTED** User-Agent: MinIO (darwin; amd64) madmin-go/0.0.1 mc/2020-07-31T23:34:13Z
**REDACTED** 
**REDACTED** [RESPONSE] [20:09:55.650] [ Duration 236µs  ↑ 80 B  ↓ 400 B ]
**REDACTED** 200 OK
**REDACTED** Accept-Ranges: bytes
**REDACTED** Content-Length: 149
**REDACTED** Content-Security-Policy: block-all-mixed-content
**REDACTED** Content-Type: application/json
**REDACTED** Server: MinIO/RELEASE.2020-07-31T03-39-05Z
**REDACTED** Vary: Origin
**REDACTED** X-Amz-Request-Id: 1627DB0240CE3EB0
**REDACTED** X-Xss-Protection: 1; mode=block
**REDACTED** {"Summary":"running","StartTime":"2020-08-03T20:05:19.079292Z","Settings":{"recursive":true,"dryRun":false,"remove":false,"scanMode":0},"Items":null}
**REDACTED** 
**REDACTED** [REQUEST admin.Heal] 20:09:56.654
**REDACTED** POST /minio/admin/v3/heal/?clientToken=42807101-6233-46aa-87ff-53e2d0b49609
**REDACTED** Host: **REDACTED**:9000
**REDACTED** Authorization: AWS4-HMAC-SHA256 Credential=minion/20200803//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b28d7c1490ec2bd069f59312fbcc0dc32db8df6333023ed00b3fb92d153f9973
**REDACTED** Transfer-Encoding: chunked
**REDACTED** User-Agent: MinIO (darwin; amd64) madmin-go/0.0.1 mc/2020-07-31T23:34:13Z
**REDACTED** X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
**REDACTED** X-Amz-Date: 20200803T200956Z
**REDACTED** 
**REDACTED** [RESPONSE] [20:09:56.654] [ Duration 258µs  ↑ 80 B  ↓ 395 B ]
**REDACTED** 200 OK
**REDACTED** X-Amz-Request-Id: 1627DB027CA67B28
**REDACTED** X-Xss-Protection: 1; mode=block
**REDACTED** Accept-Ranges: bytes
**REDACTED** Content-Length: 144
**REDACTED** Content-Security-Policy: block-all-mixed-content
**REDACTED** Content-Type: application/json
**REDACTED** Server: MinIO/RELEASE.2020-07-31T03-39-05Z
**REDACTED** Vary: Origin
**REDACTED** {"Summary":"finished","StartTime":"0001-01-01T00:00:00Z","Settings":{"recursive":false,"dryRun":false,"remove":false,"scanMode":0},"Items":null}

**Comment by harshavardhana** [comment]
@SoftBoil please upgrade to latest release and test - there has been some issues fixed in erasure coding calculation.

**Comment by SoftBoil** [comment]
Success!  The heal ran for about 2-3 hours and completed.
Thank you for looking into the issue.

mc admin heal -r myminio
 ◒  arq/460ac29a-6921-483b-bebd-7235b6b…896c56776f3af892586e84716e8066d2685
    10,009/10,009 objects; 18 GiB in 2562047h47m16.854775807s
    ┌────────┬────────┬─────────────────────┐
    │ Green  │ 10,011 │ 100.0% ████████████ │
    │ Yellow │      0 │   0.0%              │
    │ Red    │      0 │   0.0%              │
    │ Grey   │      0 │   0.0%              │
    └────────┴────────┴─────────────────────┘

**Comment by SoftBoil** [comment]
Actually after checking the contents of the drives it looks like healing did not complete as I thought.
The contents of myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs on the deleted volume only had 30 directories out of 230.

I manually run "mc admin heal -r myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs".  I can see files being re-created on the server, but the client does not report progress and quits after 2 minutes.

**Comment by harshavardhana** [comment]
> Actually after checking the contents of the drives it looks like healing did not complete as I thought.
> The contents of myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs on the deleted volume only had 30 directories out of 230.
> 
> I manually run "mc admin heal -r myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs". I can see files being re-created on the server, but the client does not report progress and quits after 2 minutes.

Please upgrade to latest and let us know @SoftBoil we did fix few issues in this area.. 

NOTE: if there is no content to heal, healing won't report any objects being healed.

**Comment by SoftBoil** [comment]
I tried again with the latest version and it heals only one or two directories before stopping. The output when it stops looks similar to what it was before: "0/0 objects; 0 B in 2562047h47m16.854775807s"

I confirm that there is missing content by comparing the directory count between the drives:
  minio2/min6/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs has 178 sub-directories
  minio3/min6/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs has 256 sub-directories
Each sub-directory is non-empty and contains files.

It seems that server silently gives up during healing. Are there any debug flags that I can enable? I'd like to help provide more useful information.

**Comment by harshavardhana** [comment]
> I tried again with the latest version and it heals only one or two directories before stopping. The output when it stops looks similar to what it was before: "0/0 objects; 0 B in 2562047h47m16.854775807s"
> 
> I confirm that there is missing content by comparing the directory count between the drives:
> minio2/min6/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs has 178 sub-directories
> minio3/min6/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs has 256 sub-directories
> Each sub-directory is non-empty and contains files.
> 
> It seems that server silently gives up during healing. Are there any debug flags that I can enable? I'd like to help provide more useful information.

How many files do you have here @SoftBoil ? Also do you have a proxy between hosts? Can you run the heal directly pointing to a single server ?

**Comment by harshavardhana** [comment]
@SoftBoil we have re-implemented the healing functionality from latest release onwards we have auto-healing is running all the time now so there is no reason to ever run `mc admin heal` anymore and it will be removed in time.

Closing this issue since `mc admin heal -r` is deprecated now.
