### ISSUE TITLE
Add storage layer deadlines similar to hung_task_timeout_secs

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#10178]
**Is your feature request related to a problem? Please describe.**
Storage devices can invariably die at times and not respond properly, while we have network layer timeouts
and handling now we do not have a clear way to handle similar situations that can potentially happen
on the storage layer. This can lead to situations where MinIO server might perpetually hang
or at the mercy for Linux filesystems to return an appropriate error. I

**Describe the solution you'd like**

Instead, understand the kernel hung_task_timeout code and implement something similar in MinIO. 

```
sysctl -a --pattern hung
kernel.hung_task_warnings = 10
kernel.hung_task_timeout_secs = 120
kernel.hung_task_check_count = 32768
kernel.hung_task_panic = 0
```

**Describe alternatives you've considered**
Alternatives such as io_uring interface are not yet implemented and may not be for quite some time in future

https://github.com/golang/go/issues/31908 

https://github.com/hodgesds/iouring-go 

https://www.scylladb.com/2020/05/05/how-io_uring-and-ebpf-will-revolutionize-programming-in-linux/

https://github.com/spacejam/rio

**Additional context**

Rather than waiting on io_uring interface, we are better off using channels and deadlines?

**Comment by harshavardhana** [comment]
// cc @vadmeste transferred this to you after discussing with @abperiasamy - ping me for more questions.

**Comment by klauspost** [comment]
@harshavardhana @abperiasamy Looking at the performance of `iouring-go` doesn't look too encouraging.

As per the linked golang/go issue it seems this would need to be implemented in the runtime, so a ring per P (processor core) can be implemented. In Go 'userspace' there isn't any access/control of this. Of course we can [hack something](https://godoc.org/github.com/klauspost/cpuid#CPUInfo.Ia32TscAux) but I suspect it will be pretty fragile.

Not a big fan of spinning up goroutines for file operations to have timeouts, but it may be a simpler way with a similar performance penalty. This would of course also have the benefit of being platform agnostic. When/if there is runtime support we an switch to that.

Not saying we shouldn't pursue this, just that we should at least check performance along the way and not just at the end. This definitely isn't a free lunch.

**Comment by harshavardhana** [comment]
> @harshavardhana @abperiasamy Looking at the performance of `iouring-go` doesn't look too encouraging.
> 
> As per the linked golang/go issue it seems this would need to be implemented in the runtime, so a ring per P (processor core) can be implemented. In Go 'userspace' there isn't any access/control of this. Of course we can [hack something](https://godoc.org/github.com/klauspost/cpuid#CPUInfo.Ia32TscAux) but I suspect it will be pretty fragile.
> 
> Not a big fan of spinning up goroutines for file operations to have timeouts, but it may be a simpler way with a similar performance penalty. This would of course also have the benefit of being platform agnostic. When/if there is runtime support we an switch to that.
> 

> Not saying we shouldn't pursue this, just that we should at least check performance along the way and not just at the end. This definitely isn't a free lunch.

Correct @klauspost one approach is to look at implementation and see how it would work properly without impacting much performance, feel free to chime in to this issue if you have any sample implementations too.

**Comment by vadmeste** [comment]
@abperiasamy just recommended that we solve the issue at high level (to fix both local/remote disks)

So first, I wrote some fuse code to simulate a failed disk (sleep 5 seconds and return EIO), and yes, I confirm that the whole cluster can be stuck in that case.

Then, I implemented a quick solution that makes `mc ls` at least work quickly. The idea is that in erasure level, we fine-tune 
 errgroup.Go() to control when we are satisfied since in general we only need quorum for listing.

(it is implemented here, but do not focus too much on its correctness https://github.com/minio/minio/compare/master...vadmeste:dist-timeout?expand=1)

We can do the same for reading metadata and reading objects.

For writing metadata and objects (not implemented yet), we should not abort so quickly as we do as reading/listing, so my idea is that errgroup will gather time execution of at least N/2+1 goroutines that are writing and calculate the median time, and then start to ignore disks that takes e.g. 5 times longer than other normal disks 

By the way, this solution does not to create more goroutines time and I do not expect its having a performance penaly.

**Comment by harshavardhana** [comment]
> @abperiasamy just recommended that we solve the issue at high level (to fix both local/remote disks)
> 
> So first, I wrote some fuse code to simulate a failed disk (sleep 5 seconds and return EIO), and yes, I confirm that the whole cluster can be stuck in that case.
> 
> Then, I implemented a quick solution that makes `mc ls` at least work quickly. The idea is that in erasure level, we fine-tune
> errgroup.Go() to control when we are satisfied since in general we only need quorum for listing.
> 
> (it is implemented here, but do not focus too much on its correctness https://github.com/minio/minio/compare/master...vadmeste:dist-timeout?expand=1)
> 
> We can do the same for reading metadata and reading objects.
> 
> For writing metadata and objects (not implemented yet), we should not abort so quickly as we do as reading/listing, so my idea is that errgroup will gather time execution of at least N/2+1 goroutines that are writing and calculate the median time, and then start to ignore disks that takes e.g. 5 times longer than other normal disks
> 
> By the way, this solution does not to create more goroutines time and I do not expect its having a performance penaly.

Yeah I like the idea of purpose-built code at top level - but we need cancellers are posix level also such that we do not build/pile up things.  @vadmeste how are you planning to cancel the blocked routines at posix level?

**Comment by vadmeste** [comment]
> @vadmeste how are you planning to cancel the blocked routines at posix level?

It looks like we need to write our own read/write functions to call in place of io.ReadFile() and io.WriteFile(), with non blocking mode activated. Although this is generally not useful with disk files, the only benefit is that we can close file and quit to free up resources, however I am not sure if this will have a performance regression.

**Comment by klauspost** [comment]
@vadmeste We should be able to wrap the readers/writers. We will need to spawn a goroutine anyway. Let me see if I can create an easy to use wrapper.

**Comment by harshavardhana** [comment]
This issue is still a work in progress.

**Comment by harshavardhana** [comment]
This issue has been long stale and there is no easier way to add deadlines. 

We have for now done enough optimization at the storage layer and we do not need to do this - as there are cleaner ways to do this.
