### ISSUE TITLE
[faq] Expanding existing distributed

### ISSUE THREAD

**Issue by bluefan** [minio/minio#10172]
## Expected Behavior
old cluster is almost full. when i finish expanding, new object upload requests can using the new cluster

## Current Behavior
 new object upload requests using the old cluster

## Steps to Reproduce (for bugs)
1. the old config

```
export MINIO_ACCESS_KEY=accesskey
export MINIO_SECRET_KEY=secretkey
minio server http://oss-node{1...10}/data{1...10}/minio
```

2. finish expanding
the node1-10 is almost full , so i do the expanding

new config is
```
export MINIO_ACCESS_KEY=accesskey
export MINIO_SECRET_KEY=secretkey
minio server http://oss-node{1...10}/data{1...10}/minio http://oss-node{11...20}/data{1...10}/minio
```

3.upload and trace

`
mc admin trace -a  minio | grep CreateFile 
`

 03:33:47.647 [403 Forbidden] internal.CreateFile **oss-node5**:9000/minio/storage/data4/minio/v20/createfile?disk-id=ef344d22-829d-4c7f-91f4-937681de77ce&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp      152µs       ↑ 58 B ↓ 157 B

03:33:47.689 [200 OK] internal.CreateFile **oss-node7**:9000/minio/storage/data4/minio/v20/createfile?disk-id=a0c0bdf5-1ca2-4bd0-93e5-6ce07d3e29c5&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp      50.085ms     ↑ 713 KiB ↓ 0 B

03:33:47.691 [200 OK] internal.CreateFile **oss-node6**:9000/minio/storage/data4/minio/v20/createfile?disk-id=b3910bdf-c904-43f3-aba5-5c29326b6ebb&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp     52.025ms     ↑ 713 KiB ↓ 0 B

03:33:47.025 [200 OK] internal.CreateFile **oss-node8**:9000/minio/storage/data4/minio/v20/createfile?disk-id=eecbd990-ce03-4654-bb1d-97075c87e8a7&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp     54.553ms     ↑ 713 KiB ↓ 0 B

03:33:47.768 [200 OK] internal.CreateFile **oss-node10**:9000/minio/storage/data4/minio/v20/createfile?disk-id=2fea7204-295f-47c6-b64b-0fa327f3478f&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp     129.334ms    ↑ 713 KiB ↓ 0 B

03:33:47.823 [200 OK] internal.CreateFile **oss-node9**:9000/minio/storage/data4/minio/v20/createfile?disk-id=5ca76871-2d33-4865-9acd-dcb518934c84&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp     185.069ms    ↑ 713 KiB ↓ 0 B

03:33:47.856 [200 OK] internal.CreateFile **oss-node2**:9000/minio/storage/data4/minio/v20/createfile?disk-id=7061bd0a-0aa7-435a-92e0-1bdc0ff25281&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp      210.129ms    ↑ 713 KiB ↓ 0 B

03:33:47.884 [200 OK] internal.CreateFile **oss-node1**:9000/minio/storage/data4/minio/v20/createfile?disk-id=75d5b700-ead8-4f37-8255-83e4fa644d45&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp      235.251ms    ↑ 713 KiB ↓ 0 B

03:33:47.914 [200 OK] internal.CreateFile **oss-node4**:9000/minio/storage/data4/minio/v20/createfile?disk-id=afe5b9d8-a6af-44a8-ad6c-322568613d56&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp     267.127ms    ↑ 713 KiB ↓ 0 B

03:33:48.178 [200 OK] internal.CreateFile **oss-node3**:9000/minio/storage/data4/minio/v20/createfile?disk-id=09df5fcd-22d9-43ba-947b-24f2c18921f7&file-path=bf2be904-54c3-4b20-82cd-f555778cbf32%2Fbaeeae29-90c4-4293-aae2-e09b8aa3d98f%2Fpart.1&length=729623&volume=.minio.sys%2Ftmp     531.008ms    ↑ 713 KiB ↓ 0 B

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2020-07-20T02-25-16Z
mc version RELEASE.2020-07-17T02-52-20Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
Linux 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> new object upload requests using the old cluster

They will use if the cluster has enough space @bluefan affinity is re-use the same cluster if necessary. This is randomized and expected.

**Comment by bluefan** [comment]
> > new object upload requests using the old cluster
> 
> They will use if the cluster has enough space @bluefan affinity is re-use the same cluster if necessary. This is randomized and expected.

Not the least used cluster？

**Comment by harshavardhana** [comment]
> > > new object upload requests using the old cluster
> > 
> > 
> > They will use if the cluster has enough space @bluefan affinity is re-use the same cluster if necessary. This is randomized and expected.
> 
> Not the least used cluster？

Not always, it tries to get the best out of the situation. So that your previous instance is not severely discarded.

The implementation is such that it will eventually make both cluster equal in its usage.

**Comment by harshavardhana** [comment]
If your previous cluster can take writes it is allowed, it is not a blind implementation where it always uses the newer zone.

**Comment by harshavardhana** [comment]
So what you are seeing is correct, it is only a bug if schedules writes to first zone where there is no space and it fails. If it doesn't fail and the writes go through fine there is no issue.

**Comment by bluefan** [comment]
> So what you are seeing is correct, it is only a bug if schedules writes to first zone where there is no space and it fails. If it doesn't fail and the writes go through fine there is no issue.

I see，thanks
