### ISSUE TITLE
[faq] How to use MinIO with AWS C++ SDK?

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10176]
hello minio expert,
after my debug, i found that AWS SDK build http request URI with bucket name in, but minio does not have this. so i failed everytime try to upload to minio with AWS C++ SDK.

as the code show, AWS always prefix the bucket name into the URL.
    if(m_useVirtualAddressing && Aws::Utils::IsValidDnsLabel(bucket) &&
        bucket == Aws::Utils::StringUtils::ToLower(bucket.c_str()))
    {
        ss << m_scheme << "://" << bucket << "." << m_baseUri;
    }
    else
    {
        ss << m_scheme << "://" << m_baseUri << "/" << bucket;
    }

    return ComputeEndpointOutcome(EndpointRegionPair(ss.str(), signerRegion));
}

my bucket name is test, so it try to access http://test.127.0.0.1:9000

  | Name | Value | Type
-- | -- | -- | --
▶ | std::basic_stringstream<char,std::char_traits<char>,Aws::Allocator<char> >::str returned | "http://test.127.0.0.1:9000" | std::basic_string<char,std::char_traits<char>,Aws::Allocator<char>>

![image](https://user-images.githubusercontent.com/7543276/89092781-698d5e80-d3e7-11ea-9dbf-0a970a7d34e5.png)
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> my bucket name is test, so it try to access http://test.127.0.0.1:9000

This is because AWS SDK C++ is trying to do DNS based bucket access https://github.com/aws/aws-sdk-cpp/issues/587#issuecomment-311263896 use the configuration mentioned here 

@gwnet

**Comment by gwnet** [comment]
thank you so much @harshavardhana  I review the code, I need fill m_uservirtualaddress to false. now it works fine. 

below is my new code
```
 Aws::SDKOptions m_options;
    S3Client* m_client = { NULL };


    Aws::InitAPI(m_options);
    Aws::Client::ClientConfiguration cfg;
    cfg.endpointOverride = "127.0.0.1:9000";  // S3服务器地址和端口
    cfg.scheme = Aws::Http::Scheme::HTTP;
    cfg.verifySSL = false;
    //Aws::Auth::AWSCredentials cred("RPW421T9GSIO4A45Y9ZR", "2owKYy9emSS90Q0pXuyqpX1OxBCyEDYodsiBemcq");  // 认证的Key
    m_client = new S3Client(Aws::Auth::AWSCredentials("minioadmin", "minioadmin"), cfg, 
        Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false);

    PutObjectRequest putObjectRequest;
    putObjectRequest.WithBucket(BucketName.c_str()).WithKey(objectKey.c_str());
    auto input_data = Aws::MakeShared<Aws::FStream>("PutObjectInputStream", pathkey.c_str(), std::ios_base::in | std::ios_base::binary);
    putObjectRequest.SetBody(input_data);
    auto putObjectResult = m_client->PutObject(putObjectRequest);
    if (putObjectResult.IsSuccess())
    {
        std::cout << "Done!" << std::endl;
        return true;
    }
    else
    {
        std::cout << "PutObject error: " <<
            putObjectResult.GetError().GetExceptionName() << " " <<
            putObjectResult.GetError().GetMessage() << std::endl;
        return false;
    }
```
