### ISSUE TITLE
[not our bug] Can't access Minio put_bucket_versioning Rest API (We are using Elixir backend)

### ISSUE THREAD

**Issue by pavo-tusker** [minio/minio#10181]
Hi,
 We are using elixir in our backend. So Minio is not providing the SDK for elixir. So we are using ExAWS SDK for accessing elixir. Recently Minio enabled bucket versioning feature. We want to use a bucket versioning feature( ExAws library also not providing the support for versioning). So, we planned to use the S3 REST API. We can successfully access get APIs using Rest API.

We tried to use the put_bucket_versioning API but we cannot make it work.
We are using SigAWS library in elixir for a signature generation (https://github.com/handnot2/sigaws)

Here I provide my code and response:
`   url = "http://localhost:9000/test-2/?versioning"

    body = Poison.encode!(%{
      VersioningConfiguration: %{
        Status: "Enabled"
      }
    })

    {:ok, %{} = sig_data, _} =
      Sigaws.sign_req(url, service: "s3",
        method: "PUT",
        access_key: "minioadmin",
        secret: "minioadmin" )
    response = HTTPoison.put(url, body, sig_data, [])`

Our Signature:

`%{
  "Authorization" => "AWS4-HMAC-SHA256 Credential=minioadmin/20200803/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=8ebe222447092a680ec23b5a39a9a23c7534f553532c1d3795f02cae8edd94cc",
  "X-Amz-Algorithm" => "AWS4-HMAC-SHA256",
  "X-Amz-Content-Sha256" => "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "X-Amz-Date" => "20200803T123312Z",
  "X-Amz-SignedHeaders" => "host;x-amz-date"
}`

The response we are getting from Minio:
`{:ok,
 %HTTPoison.Response{
   body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message><BucketName>test-2</BucketName><Resource>/test-2/</Resource><RequestId>1627C21608F0480A</RequestId><HostId>628b08f3-7ffe-442d-bf96-20083da98366</HostId></Error>",
   headers: [
     {"Accept-Ranges", "bytes"},
     {"Content-Length", "347"},
     {"Content-Security-Policy", "block-all-mixed-content"},
     {"Content-Type", "application/xml"},
     {"Server", "MinIO/RELEASE.2020-07-27T18-37-02Z"},
     {"Vary", "Origin"},
     {"X-Amz-Request-Id", "1627C21608F0480A"},
     {"X-Xss-Protection", "1; mode=block"},
     {"Date", "Mon, 03 Aug 2020 12:33:12 GMT"}
   ],
   request: %HTTPoison.Request{
     body: "{\"VersioningConfiguration\":{\"Status\":\"Enabled\"}}",
     headers: [
       {"Authorization",
        "AWS4-HMAC-SHA256 Credential=minioadmin/20200803/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=8ebe222447092a680ec23b5a39a9a23c7534f553532c1d3795f02cae8edd94cc"},
       {"X-Amz-Algorithm", "AWS4-HMAC-SHA256"},
       {"X-Amz-Content-Sha256",
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
       {"X-Amz-Date", "20200803T123312Z"},
       {"X-Amz-SignedHeaders", "host;x-amz-date"}
     ],
     method: :put,
     options: [],
     params: %{},
     url: "http://localhost:9000/test-2/?versioning"
   },
   request_url: "http://localhost:9000/test-2/?versioning",
   status_code: 400
 }}`

**Comment by harshavardhana** [comment]
> Hi,
> We are using elixir in our backend. So Minio is not providing the SDK for elixir. So we are using ExAWS SDK for accessing elixir. Recently Minio enabled bucket versioning feature. We want to use a bucket versioning feature( ExAws library also not providing the support for versioning). So, we planned to use the S3 REST API. We can successfully access get APIs using Rest API.
> 
> We tried to use the put_bucket_versioning API but we cannot make it work.
> We are using SigAWS library in elixir for a signature generation (https://github.com/handnot2/sigaws)
> 
> Here I provide my code and response:
> ` url = "http://localhost:9000/test-2/?versioning"
> 
> ```
> body = Poison.encode!(%{
>   VersioningConfiguration: %{
>     Status: "Enabled"
>   }
> })
> 
> {:ok, %{} = sig_data, _} =
>   Sigaws.sign_req(url, service: "s3",
>     method: "PUT",
>     access_key: "minioadmin",
>     secret: "minioadmin" )
> response = HTTPoison.put(url, body, sig_data, [])`
> ```
> 
> Our Signature:
> 
> `%{ "Authorization" => "AWS4-HMAC-SHA256 Credential=minioadmin/20200803/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=8ebe222447092a680ec23b5a39a9a23c7534f553532c1d3795f02cae8edd94cc", "X-Amz-Algorithm" => "AWS4-HMAC-SHA256", "X-Amz-Content-Sha256" => "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "X-Amz-Date" => "20200803T123312Z", "X-Amz-SignedHeaders" => "host;x-amz-date" }`
> 
> The response we are getting from Minio:
> `{:ok, %HTTPoison.Response{ body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message><BucketName>test-2</BucketName><Resource>/test-2/</Resource><RequestId>1627C21608F0480A</RequestId><HostId>628b08f3-7ffe-442d-bf96-20083da98366</HostId></Error>", headers: [ {"Accept-Ranges", "bytes"}, {"Content-Length", "347"}, {"Content-Security-Policy", "block-all-mixed-content"}, {"Content-Type", "application/xml"}, {"Server", "MinIO/RELEASE.2020-07-27T18-37-02Z"}, {"Vary", "Origin"}, {"X-Amz-Request-Id", "1627C21608F0480A"}, {"X-Xss-Protection", "1; mode=block"}, {"Date", "Mon, 03 Aug 2020 12:33:12 GMT"} ], request: %HTTPoison.Request{ body: "{\"VersioningConfiguration\":{\"Status\":\"Enabled\"}}", headers: [ {"Authorization", "AWS4-HMAC-SHA256 Credential=minioadmin/20200803/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=8ebe222447092a680ec23b5a39a9a23c7534f553532c1d3795f02cae8edd94cc"}, {"X-Amz-Algorithm", "AWS4-HMAC-SHA256"}, {"X-Amz-Content-Sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}, {"X-Amz-Date", "20200803T123312Z"}, {"X-Amz-SignedHeaders", "host;x-amz-date"} ], method: :put, options: [], params: %{}, url: "http://localhost:9000/test-2/?versioning" }, request_url: "http://localhost:9000/test-2/?versioning", status_code: 400 }}`

Looks like the library is buggy here @pavo-tusker calculating checksum incorrectly for the body.

**Comment by harshavardhana** [comment]
Just to keep things simple just use `mc versioning enable myminio/testbucket`  - the most painless way to enable versioning. https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#command-versioning

**Comment by harshavardhana** [comment]
Closing this issue as stale, please provide a reproducer. For now, I don't see anything wrong on our end.
