### ISSUE TITLE
[FAQ] minio internal network traffic threading model and CPU bind tuning

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10182]
minio network threading model detail. can minio network IO thread bind to specific CPU cores? can we do this and how?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
If you want to do this you need to use taskset outside if MinIO,

MinIO won't do any pinning we just rely on Go runtime which efficiently schedules the CPU usage.

**Comment by gwnet** [comment]
@harshavardhana how can I know which thread inside minio are for IO thread? does golang runtime provide API to pin thread on specific CPU core?

**Comment by harshavardhana** [comment]
> @harshavardhana how can I know which thread inside minio are for IO thread? does golang runtime provide API to pin thread on specific CPU core?

There is no way to know, threads are automatically managed by Go. We do not create any POSIX threads.
