### ISSUE TITLE
Request - intellisense for showing possible paths in fs

### ISSUE THREAD

**Issue by gnot** [minio/minio#1018]
I doubt this is possible unless mc.exe is invoked as its own shell. 
Context - when copying/listing directory in use, at times it is useful to have contextual intellisense to display paths.

Say local share is c:\minionshare
Create say another directory underneath called golang
To copy a file one would have to do 
mc.exe cp c:\go\robots.txt localhost/golang 

Let us say there are multiple folders underneath minionshare. While trying to copy a file - once you reach localhost/ - you should be able to tab out and retrieve possible destinations. But I guess that may not be possible as we are still in local command context and it does not about the overlay structure.

**Comment by harshavardhana** [comment]
> Let us say there are multiple folders underneath minionshare. While trying to copy a file - once you reach localhost/ - you should be able to tab out and retrieve possible destinations.

For billions of objects this is not scalable, we thought about it and avoided these things to make experience predictable.

**Comment by gnot** [comment]
makes sense - most of the time it will be api call rather than cmdline browsing.

**Comment by harshavardhana** [comment]
> makes sense - most of the time it will be api call rather than cmdline browsing.

Yes, our idea is to keep it minimal. Will close this.
