### ISSUE TITLE
[resolved] Different response between standalone mode and distributed mode

### ISSUE THREAD

**Issue by YaoC** [minio/minio#10183]
## Current Behavior
When I get a prefix using `get_object` method I found the responses are different:

- standalone mode returns status code **200**
- distributed mode returns status code **404**

## Steps to Reproduce (for bugs)

1. `echo 'this is a test file' > test.txt`
2. Create a bucket `foo` and a prefix `bar` in the brower
3. Upload `test.txt` into `/foo/bar/`
4. `get_object(bucket_name=foo, object_name=bar/)`

I found in distributed mode a `errFileNotFound ` returned here:
https://github.com/minio/minio/blob/43dd68a58acdbf12f4809665432d0540af0cb123/cmd/xl-v1-object.go#L334

And I was puzzled about why it is not a directory if it is not empty.

## Your Environment

- RELEASE.2020-06-22T03-12-50Z

**Comment by harshavardhana** [comment]
> ## Current Behavior
> When I get a prefix using `get_object` method I found the responses are different:
> 
> * standalone mode returns status code **200**
> * distributed mode returns status code **404**
> 
> ## Steps to Reproduce (for bugs)
> 1. `echo 'this is a test file' > test.txt`
> 2. Create a bucket `foo` and a prefix `bar` in the brower
> 3. Upload `test.txt` into `/foo/bar/`
> 4. `get_object(bucket_name=foo, object_name=bar/)`
> 
> I found in distributed mode a `errFileNotFound ` returned here:
> https://github.com/minio/minio/blob/43dd68a58acdbf12f4809665432d0540af0cb123/cmd/xl-v1-object.go#L334
> 
> And I was puzzled about why it is not a directory if it is not empty.
> 
> ## Your Environment
> * RELEASE.2020-06-22T03-12-50Z

Well this behavior is necessary for quite a lot of Hadoop applications which require this sort of hack. We cannot change this behavior anyways.

A directory is directory only if it's not empty.

**Comment by harshavardhana** [comment]
> * standalone mode returns status code **200**

In-fact this is a bug and we should fix it - standalone mode should return 404 if directory is not empty.

**Comment by YaoC** [comment]
> A directory is directory only if it's not empty.

A directory is directory only if it's ~~not~~ empty ?

**Comment by harshavardhana** [comment]
> > A directory is directory only if it's not empty.
> 
> A directory is directory only if it's ~not~ empty ?

yes @YaoC
