### ISSUE TITLE
[perf] high latency issue when use all optane devices and loopback NIC in EC mode

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10196]
hello minio expert. I deploy minio with all optane SSD that is super low latency. I run the minio benchmark test with mongoose, just 1 thread, this should be the minio latency baseline. for one 4K IO optane SSD is closed to 2-3us. loopback NIC will be super low latency too. but the minio benchmark is very high 4500 us second latency. what is the reason of this? how to improve this?

intel@wcp116:~/wayne/tmp$ java -jar mongoose-bundle-4.2.15.jar --storage-driver-type=s3 --storage-net-node-port=9000 --storage-auth-uid=minioadmin --storage-auth-secret=minioadmin --storage-net-node-addrs=127.0.0.1  --item-data-size=256k --item-output-file=testdistributed256k.csv --load-step-id=wayne-256k   --storage-driver-limit-concurrency=1  --load-op-limit-count=50000 
################################################## mongoose v 4.2.18 ##################################################
2020-08-04 10:13:04,625 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2020-08-04 10:13:04,628 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2020-08-04 10:13:04,629 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2020-08-04T10:13:04,814 I                                main                           Available/installed extensions:
	Load --------------------------> com.emc.mongoose.base.load.step.linear.LinearLoadStepExtension
	dummy-mock --------------------> com.emc.mongoose.base.storage.driver.mock.DummyStorageDriverMockExtension
	coop-mock ---------------------> com.emc.mongoose.storage.driver.coop.mock.CoopStorageDriverMockExtension
	PipelineLoad ------------------> com.emc.mongoose.load.step.pipeline.PipelineLoadStepExtension
	WeightedLoad ------------------> com.emc.mongoose.load.step.weighted.WeightedLoadStepExtension
	fs ----------------------------> com.emc.mongoose.storage.driver.coop.nio.fs.FileStorageDriverExtension
	swift -------------------------> com.emc.mongoose.storage.driver.coop.netty.http.swift.SwiftStorageDriverExtension
	nio-mock ----------------------> com.emc.mongoose.storage.driver.coop.nio.mock.NioStorageDriverMockExtension
	net ---------------------------> com.emc.mongoose.storage.driver.coop.netty.NettyStorageDriverExtension
	netty-mock --------------------> com.emc.mongoose.storage.driver.coop.netty.mock.NettyStorageDriverMockExtension
	http --------------------------> com.emc.mongoose.storage.driver.coop.netty.http.HttpStorageDriverExtension
	s3 ----------------------------> com.emc.mongoose.storage.driver.coop.netty.http.s3.S3StorageDriverExtension
	atmos -------------------------> com.emc.mongoose.storage.driver.coop.netty.http.atmos.AtmosStorageDriverExtension

Warning: Nashorn engine is planned to be removed from a future JDK release
2020-08-04T10:13:05,093 I                                main                           Using the "Oracle Nashorn" scenario engine
2020-08-04T10:13:05,517 I StorageDriver                  main                           wayne-256k: creating the storage driver instance for the type "s3"
2020-08-04T10:13:05,671 I StorageDriver                  main                           storage/driver/1/s3/2057077925: use 88 I/O workers
2020-08-04T10:13:05,811 I StorageDriver                  main                           wayne-256k: creating the storage driver instance for the type "s3"
2020-08-04T10:13:05,825 I StorageDriver                  main                           storage/driver/1/s3/1164394344: use 88 I/O workers
2020-08-04T10:13:05,876 I NettyStorageDriverBase         main                           Adjust output buffer size: 256KB
Aug 04, 2020 10:13:06 AM com.github.akurilov.netty.connection.pool.MultiNodeConnPoolImpl preConnect
INFO: Pre-created 1 connections
2020-08-04T10:13:06,034 I LinearLoadStepClient           main                           wayne-256k: load step client started, additional nodes: []
------------------------------------------------------------------------------------------------------------------------
 Step Id  | Timestamp  |  Op  |     Concurrency     |       Count       | Step  |   Last Rate    |  Mean    |   Mean    
 (last 10 |            | type |---------------------|-------------------| Time  |----------------| Latency  | Duration  
 symbols) |yyMMddHHmmss|      | Current  |   Mean   |   Success  |Failed|  [s]  | [op/s] |[MB/s] |  [us]    |   [us]    
----------|------------|------|----------|----------|------------|------|-------|--------|-------|----------|-----------
wayne-256k|200804101306|CREATE|         0|0.0       |           0|     0|0.002  |0.0     |0.0    |         0|          0
2020-08-04T10:13:06,226 I HttpStorageDriverBase          fibers-executor-#84            The bucket checking response is: 404 Not Found
wayne-256k|200804101316|CREATE|         1|0.97      |        2116|     0|10.002 |224.6801|56.1700|      4005|       4599
wayne-256k|200804101326|CREATE|         1|0.98492462|        4346|     0|20.002 |221.7314|55.4328|      4034|       4533
wayne-256k|200804101336|CREATE|         1|0.98993288|        6532|     0|30.002 |218.7480|54.6870|      4082|       4543
wayne-256k|200804101346|CREATE|         1|0.99244332|        8743|     0|40.002 |222.9405|55.7351|      4102|       4536
wayne-256k|200804101356|CREATE|         1|0.99395161|       10888|     0|50.002 |210.0877|52.5219|      4138|       4559
wayne-256k|200804101406|CREATE|         1|0.99495798|       13061|     0|60.002 |216.1164|54.0291|      4155|       4565
wayne-256k|200804101416|CREATE|         1|0.99567723|       15231|     0|70.002 |219.1097|54.7774|      4167|       4570
wayne-256k|200804101426|CREATE|         1|0.99621689|       17388|     0|80.002 |215.2677|53.8169|      4180|       4577

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by gwnet** [comment]
I run the read test, I make sure all reads are hits in the page cache. just for 1 thread 4K object, the minio latency is 1500 us. that is way large than loopback NIC and kernel page cache, they are all ram hit. where is the bottleneck?

------------------------------------------------------------------------------------------------------------------------
 Step Id  | Timestamp  |  Op  |     Concurrency     |       Count       | Step  |   Last Rate    |  Mean    |   Mean    
 (last 10 |            | type |---------------------|-------------------| Time  |----------------| Latency  | Duration  
 symbols) |yyMMddHHmmss|      | Current  |   Mean   |   Success  |Failed|  [s]  | [op/s] |[MB/s] |  [us]    |   [us]    
----------|------------|------|----------|----------|------------|------|-------|--------|-------|----------|-----------
  wayne-4k|200804130905|READ  |         0|0.0       |           0|     0|0.004  |0.0     |0.0    |         0|          0
  wayne-4k|200804130915|READ  |         1|0.97979797|        5867|     0|10.004 |618.3432|2.41540|      1412|       1674
  wayne-4k|200804130925|READ  |         1|0.98484848|       12187|     0|20.004 |632.7684|2.47175|      1414|       1622
  wayne-4k|200804130935|READ  |         1|0.98989898|       18503|     0|30.004 |642.8677|2.51120|      1421|       1606
  wayne-4k|200804130945|READ  |         1|0.99242424|       24875|     0|40.004 |636.0411|2.48453|      1422|       1595
  wayne-4k|200804130955|READ  |         1|0.99191919|       31261|     0|50.004 |640.5830|2.50170|      1421|       1588
  wayne-4k|200804131005|READ  |         1|0.99327731|       37658|     0|60.004 |640.7104|2.50219|      1421|       1582
^C2020-08-04T13:10:07,400 I                                main                           wayne-4k: await for 1 step slices done
  wayne-4k|200804131007|READ  |         0|0.99185667|       38850|     0|61.924 |641.5255|2.50574|      1421|       1581
---
# Results ##############################################################################################################

**Comment by gwnet** [comment]
I review the performance counter of minio. there is no latency break down counter https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html

how can we know why we have so much big latency?

**Comment by gwnet** [comment]
@harshavardhana  I am debugging this, I reproduce the long 1500 us long latency with loopback NIC and ramdisk with minio. 
I profile the minio and attached graph here.
[profile001.pdf](https://github.com/minio/minio/files/5027907/profile001.pdf)

I feel the profile indicate 3 hotspot things
1. golang scheduler long latency
2. malloc hotspot, minio did not create memory pool to reduce latency
3. syscall overhead,

**Comment by gwnet** [comment]
```
Showing top 10 nodes out of 299
      flat  flat%   sum%        cum   cum%
     5.49s  7.09%  7.09%      6.04s  7.80%  syscall.Syscall
     4.84s  6.25% 13.34%      4.84s  6.25%  runtime.futex
     3.68s  4.75% 18.09%      3.68s  4.75%  runtime.usleep
     3.65s  4.71% 22.81%      3.94s  5.09%  runtime.runqgrab
     3.44s  4.44% 27.25%      4.17s  5.39%  runtime.step
     2.84s  3.67% 30.92%      7.34s  9.48%  runtime.pcvalue
     2.62s  3.38% 34.30%      2.85s  3.68%  syscall.Syscall6
     2.30s  2.97% 37.27%     11.54s 14.90%  runtime.gentraceback
     1.46s  1.89% 39.16%     16.43s 21.22%  runtime.mallocgc
     1.45s  1.87% 41.03%     10.79s 13.94%  runtime.findrunnable
```

@harshavardhana  buddy, to be more specific. as for low latency network like loopback, and low latency storage as ramdisk. I actually plan use the optane SSD and 100GBE in the future.

the minio latency is super long than the HW, we can see the syscall that is triggered by GetObjectNInfo is already one bottleneck now. and also golang scheduler, and also the malloc that is triggered by http.headers.clone are also overhead now.

```
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                             1.71s 28.69% |   internal/poll.(*FD).Read
                                             0.70s 11.74% |   github.com/minio/minio/cmd.(*FSObjects).GetObjectNInfo
     5.42s  7.00%  7.00%      5.96s  7.70%                | syscall.Syscall
                                             0.41s  6.88% |   runtime.reentersyscall
                                             0.11s  1.85% |   runtime.exitsyscall
----------------------------------------------------------+-------------
                                             2.44s 50.41% |   runtime.futexsleep
                                             1.65s 34.09% |   runtime.systemstack
                                             0.60s 12.40% |   runtime.schedule
     4.84s  6.25% 13.25%      4.84s  6.25%                | runtime.futex
----------------------------------------------------------+-------------
                                             3.39s 92.12% |   runtime.sysmon
                                             0.29s  7.88% |   runtime.runqgrab
     3.68s  4.75% 18.00%      3.68s  4.75%                | runtime.usleep
----------------------------------------------------------+-------------
                                             3.94s   100% |   runtime.runqsteal
     3.65s  4.71% 22.72%      3.94s  5.09%                | runtime.runqgrab
                                             0.29s  7.36% |   runtime.usleep
----------------------------------------------------------+-------------
                                             4.13s   100% |   runtime.pcvalue
     3.40s  4.39% 27.11%      4.13s  5.33%                | runtime.step
                                             0.73s 17.68% |   runtime.readvarint
----------------------------------------------------------+-------------
                                             3.72s 51.45% |   runtime.funcspdelta
                                             3.28s 45.37% |   runtime.pcdatavalue
                                             0.23s  3.18% |   github.com/minio/minio/cmd.(*FSObjects).GetObjectNInfo
     2.78s  3.59% 30.70%      7.23s  9.34%                | runtime.pcvalue
                                             4.13s 57.12% |   runtime.step
----------------------------------------------------------+-------------
                                            11.24s 99.21% |   runtime.systemstack
                                             0.08s  0.71% |   runtime.gcDrain
     2.23s  2.88% 33.58%     11.33s 14.63%                | runtime.gentraceback
                                             3.87s 34.16% |   runtime.funcspdelta
                                             3.43s 30.27% |   runtime.pcdatavalue
                                             1.39s 12.27% |   runtime.findfunc
----------------------------------------------------------+-------------
                                             1.24s 69.66% |   github.com/minio/minio/cmd.(*FSObjects).GetObjectNInfo
     1.63s  2.11% 35.68%      1.78s  2.30%                | syscall.Syscall6
                                             0.10s  5.62% |   runtime.exitsyscall
----------------------------------------------------------+-------------
                                            10.77s 99.81% |   runtime.schedule
     1.45s  1.87% 37.56%     10.79s 13.94%                | runtime.findrunnable
                                             4.76s 44.11% |   runtime.runqsteal
                                             2.20s 20.39% |   runtime.stopm
                                             0.78s  7.23% |   runtime.(*randomEnum).next
                                             0.67s  6.21% |   runtime.epollwait
                                             0.11s  1.02% |   runtime.lock
----------------------------------------------------------+-------------
                                             6.55s 40.71% |   runtime.newobject
                                             4.98s 30.95% |   runtime.makeslice
                                             2.19s 13.61% |   runtime.mapassign_faststr
                                             0.50s  3.11% |   runtime.slicebytetostring
                                             0.38s  2.36% |   github.com/minio/minio/cmd.(*FSObjects).GetObjectNInfo
                                             0.30s  1.86% |   github.com/minio/minio/cmd.checkRequestAuthTypeToAccessKey
                                             0.27s  1.68% |   net/http.Header.Clone
                                             0.09s  0.56% |   github.com/gorilla/mux.(*Route).Match
     1.44s  1.86% 39.42%     16.09s 20.78%                | runtime.mallocgc
                                            10.14s 63.02% |   runtime.systemstack
                                             1.36s  8.45% |   runtime.(*mcache).nextFree
                                             1.34s  8.33% |   runtime.heapBitsSetType
                                             0.76s  4.72% |   runtime.nextFreeFast
                                             0.26s  1.62% |   runtime.memclrNoHeapPointers
----------------------------------------------------------+-------------
                                             1.39s 95.86% |   runtime.gentraceback
     1.32s  1.70% 41.12%      1.45s  1.87%                | runtime.findfunc
----------------------------------------------------------+-------------
```

**Comment by gwnet** [comment]
buddy, I create one very simple http golang server on loopback NIC, then run one ab test. it show me the the latency is 250 us.

intel@wcp116:~$ ab -n 10000 -c 1 "http://localhost/ccc"
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            80

Document Path:          /ccc
Document Length:        30 bytes

Concurrency Level:      1
Time taken for tests:   2.357 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1470000 bytes
HTML transferred:       300000 bytes
Requests per second:    4241.91 [#/sec] (mean)
Time per request:       0.236 [ms] (mean)
Time per request:       0.236 [ms] (mean, across all concurrent requests)
Transfer rate:          608.95 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    0   0.0      0       1
Waiting:        0    0   0.0      0       1
Total:          0    0   0.0      0       1

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      0
  75%      0
  80%      0
  90%      0
  95%      0
  98%      0
  99%      0
 100%      1 (longest request)
intel@wcp116:~$

**Comment by gwnet** [comment]
any progress?

**Comment by klauspost** [comment]
I don't see anything unexpected in your numbers. 

MinIO favors throughput over absolute latency so there may be some extra setup here and there.

You are welcome to submit patches, but for now it is what it is and we have an ongoing effort to improve both latency and throughput, but this provides no real information.

**Comment by gwnet** [comment]
got it. agreed. I have another issue need your help review. that is BW issue. I will paste my new finding in github and also find you in slack. 👍
