### ISSUE TITLE
fs: Expiry attribute should honor the time requested

### ISSUE THREAD

**Issue by gnot** [minio/minio#1019]
Docs should clarify what is the default expiry (NONE) vs when you pass in an item what is honored. Will the location be cleaned of directories or files, does it depend on last access time of the directory/location or just the expiry option. 
Context 
After executing  minio.exe server expiry 0.5h c:\minionshare 
and creating bunch of empty directories, I waited for an hour to see what happens. Then came in next day (4+ hours) and saw the metadata .json files were gone from root of the location but directories were still there. I could still go ahead and copy files 
mc.exe cp c:\Go\robots.txt localhost/testdir 
I was expecting an error message saying location does not exist. I would also expect a log message in server console or somewhere else wrt what happened.  I guess new changes are coming to logger - so this issue is just a placeholder.

**Comment by harshavardhana** [comment]
> mc.exe cp c:\Go\robots.txt localhost/testdir

This won't be an error 'mc' recreates all non existing prefixes as well. So you won't any issue. 

> After executing minio.exe server expiry 0.5h c:\minionshare

The expiry is for files alone, not for the time they were created. But i see the confusion, but here is what it means currently. 

.5h of expiry means that every 3hrs files 30mins older than that time will be cleared. 

> Docs should clarify what is the default expiry (NONE) vs when you pass in an item what is honored. Will the location be cleaned of directories or files, does it depend on last access time of the directory/location or just the expiry option.

Yes noted.

**Comment by gnot** [comment]
Yep looks like files are removed, "directories" are not. Although the "real target" does not have concept of directories - expiry doc should make a note of that so that folks starting out will be reminded of that.  Because expiry  - sort of suggests it.  Expiry - time definitely needs little doc help. Thanks.

**Comment by harshavardhana** [comment]
> Yep looks like files are removed, "directories" are not. Although the "real target" does not have concept of directories - expiry doc should make a note of that so that folks starting out will be reminded of that. Because expiry - sort of suggests it. Expiry - time definitely needs little doc help. Thanks.

Yes sure i will do that. This bug will closed when we have it sufficiently documented.

**Comment by tuaphongpro123** [comment]
Can I set expiry is none?

**Comment by harshavardhana** [comment]
> Can I set expiry is none?

You cannot - S3 spec mandates minimum of 1sec, if you wish to have fully publicly accessible URLs then please set bucket policies to 'read-only' - http://docs.minio.io/docs/minio-client-complete-guide#policy

```
mc policy download myminio/bucket/prefix
```
