### ISSUE TITLE
[resolved] Minio fails to start normally if certain files are found in the root of a bucket

### ISSUE THREAD

**Issue by aakso** [minio/minio#10193]
If an user uploads a file to a bucket root with a name that collides with certain legacy config file names, Minio will not operate after a process restart. The server process will stay in safe mode.

This bug is observed only in single disk mode (fs).

## Expected Behavior
Server should start regardless what file names are in use.

## Current Behavior
Server starts in safe mode restricting access to S3 API.

The traces indicate that the situation is originating from `(*BucketMetadata).convertLegacyConfigs`

## Possible Solution
To make server start normally, the offending metadata directory needs to be deleted. (in `.minio.sys/buckets`).

I don't have enough background information to know whether the old style state files can ever be in the `buckets` metadata dir.
However, the issue can be mitigated by handling the `ObjectExistsAsDirectory` error.

## Steps to Reproduce (for bugs)

1. start minio in single drive mode (fs)
2. create a bucket
3. upload a file with any content and filename `policy.json`
4. restart the minio process

## Regression
Not sure.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-07-31T03-39-05Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
  * `Linux devbox 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
  * `Darwin renard 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

**Comment by aakso** [comment]
Logs: [server_console.txt](https://github.com/minio/minio/files/5020772/server_console.txt)

**Comment by harshavardhana** [comment]
Fixed by #10185
