### ISSUE TITLE
atime check fails for volumes mounted with relatime

### ISSUE THREAD

**Issue by recursionbane** [minio/minio#10190]
## Expected Behavior

Mounts with `relatime` set should satisfy `atime` check for cache disk

## Current Behavior

`ERROR Unable to initialize disk caching: Atime support required for disk caching`

The mount-point looks like:
`redacted:/vol/scratch62/redacted on /home/redacted type nfs (rw,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,noacl,proto=tcp,port=2049,timeo=600,retrans=10,sec=sys,mountaddr=redacted,mountvers=3,mountport=635,mountproto=udp,local_lock=none,addr=redacted)
`

## Steps to Reproduce (for bugs)

1. `env MINIO_CACHE_DRIVES=/home/redacted MINIO_CACHE_EXPIRY=1 MINIO_CACHE_QUOTA=10 MINIO_CACHE_AFTER=0 minio server .`
2. MinIO server fails to start with `ERROR Unable to initialize disk caching: Atime support required for disk caching`
3. Additional [debugging](https://github.com/minio/minio/tree/release/docs/debugging) context unavailable since the MinIO server does not start

## Context

To lower latency, the cache drive is SSD.

## Regression

Unknown if this is a regression.

## Your Environment

* Version used (`minio --version`): `RELEASE.2020-07-31T03-39-05Z`
* Server setup and configuration: No configuration file, env vars only: `env MINIO_CACHE_DRIVES=/home/redacted MINIO_CACHE_EXPIRY=1 MINIO_CACHE_QUOTA=10 MINIO_CACHE_AFTER=0 minio server .`
* Operating System and version (`uname -a`): `CentOS Linux release 7.5.1804 (Core)` `Linux redacted 4.1.15.pnotify #18 SMP Thu May 18 15:50:05 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> `redacted:/vol/scratch62/redacted on /home/redacted type nfs (rw,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,noacl,proto=tcp,port=2049,timeo=600,retrans=10,sec=sys,mountaddr=redacted,mountvers=3,mountport=635,mountproto=udp,local_lock=none,addr=redacted) `

NFS doesn't support atime properly @recursionbane - you should use caching for regular drives high-performance ones. NFS mounts are not meant for caching purposes. 

Caching shouldn't be on a shared NAS its not designed for it and you may see unexpected results.

**Comment by recursionbane** [comment]
Thank you for your response, @harshavardhana.

This is a managed environment without `sudo`, so an NFS SSD is currently the best available cache disk.

Is there a way to bypass the `atime` check when NFS `relatime` is detected?

**Comment by harshavardhana** [comment]
> This is a managed environment without `sudo`, so an NFS SSD is currently the best available cache disk.
> 
> Is there a way to bypass the `atime` check when NFS `relatime` is detected?

No @recursionbane we cannot do that, caching won't work without atime - if you don't have cache disk available it is best to avoid it, using it with NFS will be detrimental to your performance than beneficial.

**Comment by recursionbane** [comment]
Thank you.
