### ISSUE TITLE
Service display format disk error

### ISSUE THREAD

**Issue by lixiaopengy** [minio/minio#10195]
**I use four nodes, and each node uses a disk to deploy the cluster. However, when my container service is running normally, I log in to Minio with a browser. An error occurs when creating a bucket, and the server is not initialized. Viewing the container service log shows the following error:**
<img width="957" alt="minio" src="https://user-images.githubusercontent.com/65278402/89269589-a8801600-d66c-11ea-82f6-619622ef1e23.png">

Waiting for the first server to format the disks.
Unable to read 'format.json' from http://acaas1:9000/data/minio: client time 2020-08-04 08:03:59 +0000 UTC is too apart with server time 2020-08-03 17:09:57.69553419 +0000 UTC

Waiting for the first server to format the disks.
Unable to read 'format.json' from http://acaas1:9000/data/minio: client time 2020-08-04 08:03:59 +0000 UTC is too apart with server time 2020-08-03 17:09:58.005074377 +0000 UTC

Waiting for the first server to format the disks.
Unable to read 'format.json' from http://acaas1:9000/data/minio: client time 2020-08-04 08:04:00 +0000 UTC is too apart with server time 2020-08-03 17:09:58.527478954 +0000 UTC

Waiting for the first server to format the disks.
Unable to read 'format.json' from http://acaas1:9000/data/minio: client time 2020-08-04 08:04:01 +0000 UTC is too apart with server time 2020-08-03 17:09:59.028082396 +0000 UTC

Waiting for the first server to format the disks.
Unable to read 'format.json' from http://acaas1:9000/data/minio: client time 2020-08-04 08:04:01 +0000 UTC is too apart with server time 2020-08-03 17:09:59.493756843 +0000 UTC

Waiting for the first server to format the disks.
Unable to read 'format.json' from http://acaas1:9000/data/minio: client time 2020-08-04 08:04:02 +0000 UTC is too apart with server time 2020-08-03 17:10:00.033057509 +0000 UTC

Waiting for the first server to format the disks.

**Comment by vadmeste** [comment]
> client time 2020-08-04 08:04:02 +0000 UTC is too apart with server time 2020-08-03 17:10:00.033057509 +0000 UTC

This means you need to fix the date/time of your server or in your machine.

**Comment by lixiaopengy** [comment]
> > 客户端时间2020-08-04 08:04:02 +0000 UTC与服务器时间相隔太远2020-08-03 17：10：00.033057509 +0000 UTC
> 
> 这意味着您需要确定服务器或计算机中的日期/时间。

Thank you very much. It is really due to the time inconsistency of nodes. The problem has been solved
