### ISSUE TITLE
[not our bug] [FAQ] minio distributed mode fail to start

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10191]
root@sm151:/home/intel/wayne/miniobin# ./minio server  http://10.2.61.58/mnt/data1 http://10.2.61.58/mnt/data2 http://10.2.61.58/mnt/data3 http://10.2.61.58/mnt/data4 http://10.2.61.164/mnt/data1 http://10.2.61.164/mnt/data2 http://10.2.61.164/mnt/data3 http://10.2.61.164/mnt/data4 http://10.2.61.166/mnt/data1 http://10.2.61.166/mnt/data2  http://10.2.61.166/mnt/data3 http://10.2.61.166/mnt/data4 http://10.2.61.174/mnt/data1 http://10.2.61.174/mnt/data2 http://10.2.61.174/mnt/data3 http://10.2.61.174/mnt/data4

API: SYSTEM()
Time: 22:49:08 MST 08/03/2020
Error: http://10.2.61.164:9000/mnt/data1 as has incorrect configuration: <HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: "Operation timed out"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
You have a network proxy between nodes which is disabling communication on port 9000 @gwnet
