### ISSUE TITLE
403 on anonymous access when bucket is domain prefix

### ISSUE THREAD

**Issue by yaitskov** [minio/minio#10198]
I have an app using S3 and trying to run it locally without AWS.
I noticed issue - head/get gets 403 with minio.
After some sniffing. Figured out that there are 2 ways to address resource:

1 http://localhost:9000/bucketName/a/b/file.txt
2 http://bucketName.localhost:9000/a/b/file.txt

My haskell library uses second one. AWS service handles it without problem, but
minio image returns 403. Bucket access is set to public.

```
curl http://bucket.localhost:9001/folder/file.txt
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>file.txt</Key><BucketName>folder</BucketName><Resource>/folder/file.txt</Resource><RequestId>162823B35906A9E0</RequestId><HostId>dd15f498-b027-468d-af56-29f10547ac2d</HostId></Error>

```

But this is working:
```
curl http://localhost:9001/bucket/folder/file.txt
```

**Comment by kannappanr** [comment]
You can try
`MINIO_DOMAIN=localhost minio server /data`
and modify `/etc/hosts` and add the following line
```
127.0.0.1 bucket.localhost
```
For each bucket that you will create, you need to do this, if you want to do this locally. 

Please go through our documentation to set this up properly.
