### ISSUE TITLE
Allow non-numeric lists for creating zones

### ISSUE THREAD

**Issue by fukawi2** [minio/minio#10202]
**Is your feature request related to a problem? Please describe.**
Creating a distributed setup, with a single zone requires use of the ellipses function:

```
minio server http://minio{1..6}:9000/minio/data{1...2}
```

This pattern isn't always suitable for a given infrastructure. For example, across multiple data centers (_for example, Los Angeles (LAX), New York (NYC), and Tokyo (TOK)_), hostnames might be more like:

- `minio1.lax`
- `minio2.lax`
- `minio1.nyc`
- `minio2.nyc`
- `minio1.tok`
- `minio2.tok`

**Describe the solution you'd like**
Allow use of lists (eg, comma-delimited) to create a distributed zone. The above 6 hosts in 3 data centers could be written like this:

```
minio server http://minio{1..2}.{lax,nyc,tok}:9000/minio/data{1...2}
```

**Describe alternatives you've considered**
- Renaming hostname patterns: not feasible.
- Using aliases (eg, `minio-node1` = `minio1.lax`, `minio-node4` = `minio2.nyc`): very confusing to know which node is which without looking up.

**Additional context**
We're looking to move ~500tb from AWS S3 to in-house. MinIO would be the least-disruptive way to do this. We would be distributing this data across 3 data centers as documented in this issue.

**Comment by harshavardhana** [comment]
@fukawi2 these are complicated stuff which cannot be implemented in a clean manner for us - ellipses have a proper purpose for us. 

> This pattern isn't always suitable for a given infrastructure. For example, across multiple data centers (_for example, Los Angeles (LAX), New York (NYC), and Tokyo (TOK)_), hostnames might be more like:

You can simply have a hostname alias for your external reference but for internal communication, it can use sequential hostnames. 

I don't see why we need to complicate our codebase to cater for this.

**Comment by harshavardhana** [comment]
> We're looking to move ~500tb from AWS S3 to in-house. MinIO would be the least-disruptive way to do this. We would be distributing this data across 3 data centers as documented in this issue.

This is an okay use case - but make sure that your network infrastructure has low latency between data centers, MinIO erasure coding is not designed to work across data centers with high latency. It is expected that you can guarantee a minimum of 1Gig network link performance.

**Comment by harshavardhana** [comment]
> ```
> minio server http://minio{1..2}.{lax,nyc,tok}:9000/minio/data{1...2}
> ```

you can also name it `minio server http://minio{1...2}.region{1...3}:9000/minio/data{1...2}` where you designate 

region1 = lax
region2 = nyc
region3 = tok

**Comment by fukawi2** [comment]
> You can simply have a hostname alias for your external reference but for internal communication, it can use sequential hostnames.

That's very confusing when the rest of our infrastructure is identified by it's DC suffix (eg, `.lax`). For example, the internal names would be used in `mc admin info`, unless I'm missing something? We would not redesign our naming structure to implement a single tool - that would be more disruptive than using a tool other than MinIO.

> It is expected that you can guarantee a minimum of 1Gig network link performance.

Our internal network in each DC is all 100Gbe currently, and we would be looking to implement dedicated private links between the DC's for this. What kind of **latency** is acceptable between nodes in a single zone?

**Comment by harshavardhana** [comment]
> That's very confusing when the rest of our infrastructure is identified by it's DC suffix (eg, `.lax`). For example, the internal names would be used in `mc admin info`, unless I'm missing something? We would not redesign our naming structure to implement a single tool - that would be more disruptive than using a tool other than MinIO.

There is no re-design all you need to do is make small entries in /etc/hosts which reference the sequential addressing, there is no good for us to do these type of custom addressing. It simply complicates our codebase and overall documentation. We are not asking you to make DNS entries these can be just local to the storage servers.  All external addressing to these servers from your DNS server stays the same.

Alternative ways, you can also name it minio server `http://minio{1...2}.region{1...3}:9000/minio/data{1...2}` where you designate

region1 = lax
region2 = nyc
region3 = tok

> Our internal network in each DC is all 100Gbe currently, and we would be looking to implement dedicated private links between the DC's for this. What kind of **latency** is acceptable between nodes in a single zone?

Acceptable latency is what a 1Gig network would provide @fukawi2

**Comment by fukawi2** [comment]
> There is no re-design all you need to do is make small entries in /etc/hosts which reference the sequential addressing,

But those addresses are what would be used in the output of tools like `mc admin info` isn't it? That doesn't solve the problem, since our team would still have to manually/mentally map "region1" to "lax" when administrating the cluster.

> Acceptable latency is what a 1Gig network would provide @fukawi2

Latency != Bandwidth. Latency is measured in time, not bytes. Latency between our DC's is currently between 8ms and 23ms (generally).

**Comment by harshavardhana** [comment]
> But those addresses are what would be used in the output of tools like `mc admin info` isn't it? That doesn't solve the problem, since our team would still have to manually/mentally map "region1" to "lax" when administrating the cluster.
> 

Administratively region1 --> lax is not really painful to remember - on the other hand we implementing an esoteric approach is very painful the point is once added we need to perpetually support this forever. 

If its a big deal for you please do send us a patch @fukawi2 we are happy to accept those changes. 

> Latency != Bandwidth. Latency is measured in time, not bytes. Latency between our DC's is currently between 8ms and 23ms (generally).

Object storage is throughput sensitive, not latency.  So however you want to look at it minimum required is 1Gig interface network.

**Comment by fukawi2** [comment]
> If its a big deal for you please do send us a patch @fukawi2 we are happy to accept those changes.

I will consider this since you've indicated that you'd be willing to accept any such patch. Thanks for your time - I'll keep working on my testing. You can assign this to me if you (want|can), and if we want to go forward with a patch then I can do so.

**Comment by harshavardhana** [comment]
This is a long shot and looks to be overkill for now - closing this issue if there are any real plans we shall revisit this in the future.
