### ISSUE TITLE
[working as intended] Unable to find config.json file in ~/.minio

### ISSUE THREAD

**Issue by Pad0y** [minio/minio#10219]
## Expected Behavior

The documentation says that the default configuration directory is `${HOME}/.minio`，and MINIO Server will generates a new config.json when it is first started, but now my current directory(`~/.minio`) only exist  CAS folder, does not exist `config.json`.
![image](https://user-images.githubusercontent.com/33904150/89612915-9a700680-d8b3-11ea-9ac2-2adfba95a294.png)
So where should I find minio's configuration file and know what its parameters are.
But I found a hidden folder called`.minio.sys` in the mount directory of Minio, but I don't know what it's for
![image](https://user-images.githubusercontent.com/33904150/89613217-4fa2be80-d8b4-11ea-8748-e25e187f89d5.png)
I look forward to your answers to my questions and excuse my poor English. Thank you!

## Your Environment

* Version used (`minio --version`):
`minio version RELEASE.2020-08-05T21-34-13Z`
* Server setup and configuration:
`minio server /data`
* Operating System and version (`uname -a`):
`Linux pamper 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
config.json is long deprecated @Pad0y we have moved to a different model look at how different fields can be accessed using 

https://github.com/minio/minio/tree/master/docs/config#configuration-directory

https://github.com/minio/minio/tree/master/docs/config#list-all-config-keys-available

**Comment by harshavardhana** [comment]
> The documentation says that the default configuration directory is `${HOME}/.minio`，and MINIO Server will generates a new config.json when it is first started, but now my current directory(`~/.minio`) only exist CAS folder, does not exist `config.json`.

Documentation doesn't say that at all if you are referring to chinese docs, then they are not yet updated.
