### ISSUE TITLE
[faq] Minio Docker with TLS

### ISSUE THREAD

**Issue by Twilek-de** [minio/minio#10212]
Hi all,
I try to setup Minio via Docker and secure it with TLS. There is no official documented way to do this. I have tried to map the /root/.minio directory and put some certs there but it doesn´t seem to have any effect. Is there an official way to this?

**Comment by Twilek-de** [comment]
I have helped myself by using Apache as an reverse Proxy, but it still seems worthwhile to make the inbuild TLS funcitonality usable in Docker.

**Comment by nitisht** [comment]
Setting up with Docker is explained here https://github.com/minio/minio/issues/6820 

As long as you follow https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html and put certs in correct locations you should be fine.

**Comment by Twilek-de** [comment]
What I did is mapping the /root/.minio/ directory outside of the container. It then generated the certs directory there. Then I put my certs in there as explained in the guide and spun up a new container. But that does not work, you only get http access, not https.
