### ISSUE TITLE
[not our bug] stale NFS file handle from Netapp PVCs

### ISSUE THREAD

**Issue by philipp1992** [minio/minio#10211]
We are running minio on kubernetes using multitple PODs with a single NFS backed PVC, that is mounted to each POD.

occasionally we get the following errors:

API: PutObjectPart(bucket=sabe-pipeline, object=DEV/staging_income/detect/test2/RF_1201.0002K20_101011_939023392.xml)
Time: 06:36:33 UTC 08/06/2020
DeploymentID: 851139db-54d7-45ea-a255-1f3530fa0618
RequestID: 16289A5D1BE4689D
RemoteHost: 100.122.8.110
Host: minio-service.noobaa.svc:9000
UserAgent: aws-sdk-nodejs/2.660.0 linux/v12.18.2 promise
Error: read /data/.minio.sys/multipart/0d6227a5d3114a3a3426ed383d0aee28dc22a4709a98a0dc9a5bfbd0a58f9501/8abeafb2-c707-4ce7-886a-9715aafabf04/00007.f4401457d0101ff6f64a13652976848b.8388608: **stale NFS file handle**
       uploadID=8abeafb2-c707-4ce7-886a-9715aafabf04, partPath=/data/.minio.sys/multipart/0d6227a5d3114a3a3426ed383d0aee28dc22a4709a98a0dc9a5bfbd0a58f9501/8abeafb2-c707-4ce7-886a-9715aafabf04/00007.f4401457d0101ff6f64a13652976848b.8388608, filepath=/data/.minio.sys/tmp/dddb63d2-b926-4dae-b033-f57c3993c67e/8abeafb2-c707-4ce7-886a-9715aafabf04.98418be6-d7a4-474b-b178-44abd8d87716
       1: github.com/minio/minio@/cmd/fs-v1-multipart.go:119:cmd.(*FSObjects).backgroundAppend()

Any idea, what is causing this and how to fix?

## Context
FIle cant be read at that time, may be able to read is later.

## Your Environment
Kubernetes 1.18
minio version RELEASE.2020-07-14T19-14-30Z
NFS Backend: Netapp

**Comment by harshavardhana** [comment]
Use NFSv4 @philipp1992 better cache coherency guarantees and has fixes for all the nasty bugs from NFSv3

Otherwise you may have to remount NFS with a timeout=0

**Comment by philipp1992** [comment]
we are already using NFSv4. These are our mount options:

rw,relatime,vers=4.0,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=xxx,local_lock=none,addr=xxx

anything you would modify?

**Comment by harshavardhana** [comment]
> rw,relatime,vers=4.0,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=xxx,local_lock=none,addr=xxx

I would try to get a tcpdump for the NFS traffic and trace the stale filehandle. @philipp1992 IMO this looks like a bug in the NFS. This is quite common in NFSv3 days with v4 this is quite significantly reduced. 

tcpdump of the NFS traffic will explain a more deeper story.

**Comment by harshavardhana** [comment]
> > rw,relatime,vers=4.0,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=xxx,local_lock=none,addr=xxx
> 
> I would try to get a tcpdump for the NFS traffic and trace the stale filehandle. @philipp1992 IMO this looks like a bug in the NFS. This is quite common in NFSv3 days with v4 this is quite significantly reduced.
> 
> tcpdump of the NFS traffic will explain a more deeper story.

Closing this issue since we cannot do much here on our end.
