### ISSUE TITLE
Allow defining hostname when requesting presigned URLs

### ISSUE THREAD

**Issue by yukiisbored** [minio/minio#10222]
**Is your feature request related to a problem? Please describe.**

When requesting presigned URLs, Minio generates a URL takes the hostname from the `Host` header as reference.

In local development setup with Docker, this can be an issue as the application communicate to Minio via an alias that's only available in the container network which ends resulting in an unusable presigned URL.

Changing the URL manually by replacing the hostname results in SignatureDoesNotMatch error.

**Describe the solution you'd like**

I think when requesting presigned URLs, it should be possible to override the requested hostname in the URL with a HTTP header like `X-Host-Override` which will generate a proper presigned URL with the proper hostname.

**Describe alternatives you've considered**

Setting up a local reverse proxy and add entries to `/etc/hosts` or setup a local DNS server which adds the records.

The `/etc/hosts` solution is possible on desktops/laptops but difficult to do on more restrictive devices such as smartphones where privilege escalation is necessary to edit the `hosts` file.

Setting up a local DNS server can help but it may be difficult for developers who may not have the experience.

**Comment by KevinSmile** [comment]
If you use web-ui to generate presigned-url, it's a minio-server issue.
If you use client-sdks to generate presigned-url, it's a client issue.
see https://github.com/minio/minio/issues/10284

**Comment by KevinSmile** [comment]
Based on my research, either you are using web-ui or client-sdks, the `host` part (for calculating presigned-url) is not from http-headers:
- For web-ui, the `host` part is from request_body.params.host.
- For client-sdks, the `host` part is from client builder's endpoint.
So build another new client and change the endpoint part may help, like this:
![image](https://user-images.githubusercontent.com/17903517/90528468-3ac40600-e1a5-11ea-8b12-928692d91ac2.png)

**Comment by yukiisbored** [comment]
This is from the client SDK but the issue is that I would like to be able to declare an alternative hostname to be used when creating presigned-URLs. This is useful in testing environments with, for example, Docker where network between containers is isolated and Minio is bind to another port on the host side.

For example in a typical development setup with Docker, Minio would be accessible from the main application via `minio:9000` but from the host's network side, it's accessible in `localhost:9000`. In this case, when the application which uses the client SDK generates a presigned URL, it will result in one that uses `minio:9000` and would be useless since from the host side it's accessible only via `localhost:9000`.

Replacing `minio:9000` to `localhost:9000` in the resulting presigned URL would simply result in a signature error due to how AWS does signatures on HTTP headers.

**Comment by yukiisbored** [comment]
Actually, I just realized the Python SDK has the same issue as #10284 where the signature is actually generated in the client SDK (https://github.com/minio/minio-py/blob/master/minio/api.py#L1551). I guess what we should do is add the ability to define an alternative hostname inside presigned URL or maybe when constructing the client have a variable which defines publicly accessible URL?

**Comment by KevinSmile** [comment]
Yes, you are right! 
So I guess the best hacking-way is changing the `doesPresignedSignatureMatch` logic (on minio-server side) when you try to use a presigned-url outside your container-network:

https://github.com/minio/minio/blob/98ca770f81442142e959104804bcee30facce38d/cmd/signature-v4.go#L204

Currently we verify signature like this,
https://github.com/minio/minio/blob/98ca770f81442142e959104804bcee30facce38d/cmd/signature-v4.go#L321-L327

change it to (use your alternative hostname to generate a newSignature2): 
```go
 // Verify signature. 
if !compareSignatureV4(correctSignature, newSignature1) && !compareSignatureV4(correctSignature, newSignature2) {
   return ErrSignatureDoesNotMatch
}
```

**Comment by traed** [comment]
DId this ever get resolved? I'm facing this issue as well.
