### ISSUE TITLE
[not our bug] remote server offline errors upon upgrade

### ISSUE THREAD

**Issue by thomic** [minio/minio#10235]
When I upgrade a docker-container running MinIO from release minio/minio:RELEASE.2020-04-23T00-58-49Z to release minio/minio:RELEASE.2020-08-08T04-50-06Z than the following errors occur in the log:

1)
```
Aug 10 13:58:58 minio-01 docker-compose[3838]: Pulling minio (minio/minio:RELEASE.2020-08-08T04-50-06Z)...
Aug 10 13:58:59 minio-01 docker-compose[3838]: RELEASE.2020-08-08T04-50-06Z: Pulling from minio/minio
Aug 10 13:59:01 minio-01 docker-compose[3838]: Digest: xxx
Aug 10 13:59:01 minio-01 docker-compose[3838]: Status: Downloaded newer image for minio/minio:RELEASE.2020-08-08T04-50-06Z
Aug 10 13:59:01 minio-01 docker-compose[3838]: Creating minio_minio_1 ...
Aug 10 13:59:01 minio-01 docker-compose[3838]: Creating minio_minio_1
Aug 10 13:59:03 minio-01 docker-compose[3838]: [71B blob data]
Aug 10 13:59:03 minio-01 docker-compose[3838]: minio_1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | All MinIO sub-systems initialized successfully
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Status:         4 Online, 0 Offline.
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Endpoint:  xxx
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Browser Access:
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    xxx
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Object API (Amazon S3 compatible):
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
```

and after some time of the minio-container running

2)
```
Aug 10 14:04:45 minio-01 docker-compose[5035]: minio_1  | Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  |
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | API: SYSTEM()
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | Time: 14:09:44 UTC 08/10/2020
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | DeploymentID: a4e0ed07-72ea-40ac-81ce-0c3e0eb5bbde
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | Error: Post https://example.net/minio/peer/v10/cyclebloom?: dial tcp 10.11.5.18:443: connect: connection refused
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  |        2: github.com/minio/minio@/cmd/notification.go:478:cmd.(*NotificationSys).updateBloomFilter.func1()
Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  |        1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  |
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | API: SYSTEM()
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | Time: 14:14:44 UTC 08/10/2020
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | DeploymentID: a4e0ed07-72ea-40ac-81ce-0c3e0eb5bbde
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | Error: /cyclebloom https://example.net/minio/peer/v10: remote server offline
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  |        2: github.com/minio/minio@/cmd/notification.go:478:cmd.(*NotificationSys).updateBloomFilter.func1()
Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  |        1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  |
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | API: SYSTEM()
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | Time: 14:19:44 UTC 08/10/2020
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | DeploymentID: a4e0ed07-72ea-40ac-81ce-0c3e0eb5bbde
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | Error: /cyclebloom https://example.net/minio/peer/v10: remote server offline
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  |        2: github.com/minio/minio@/cmd/notification.go:478:cmd.(*NotificationSys).updateBloomFilter.func1()
Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  |        1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
```

I saw this error should be fixed with https://github.com/minio/minio/issues/9910 and https://github.com/minio/minio/pull/9928 but it seems like it's not?

Any ideas?

**Comment by harshavardhana** [comment]
> When I upgrade a docker-container running MinIO from release minio/minio:RELEASE.2020-04-23T00-58-49Z to release minio/minio:RELEASE.2020-08-08T04-50-06Z than the following errors occur in the log:
> 
> 1)
> ```
> Aug 10 13:58:58 minio-01 docker-compose[3838]: Pulling minio (minio/minio:RELEASE.2020-08-08T04-50-06Z)...
> Aug 10 13:58:59 minio-01 docker-compose[3838]: RELEASE.2020-08-08T04-50-06Z: Pulling from minio/minio
> Aug 10 13:59:01 minio-01 docker-compose[3838]: Digest: xxx
> Aug 10 13:59:01 minio-01 docker-compose[3838]: Status: Downloaded newer image for minio/minio:RELEASE.2020-08-08T04-50-06Z
> Aug 10 13:59:01 minio-01 docker-compose[3838]: Creating minio_minio_1 ...
> Aug 10 13:59:01 minio-01 docker-compose[3838]: Creating minio_minio_1
> Aug 10 13:59:03 minio-01 docker-compose[3838]: [71B blob data]
> Aug 10 13:59:03 minio-01 docker-compose[3838]: minio_1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | All MinIO sub-systems initialized successfully
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Status:         4 Online, 0 Offline.
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Endpoint:  xxx
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Browser Access:
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    xxx
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Object API (Amazon S3 compatible):
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
> Aug 10 13:59:04 minio-01 docker-compose[3838]: minio_1  | Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
> ```
> 
> and after some time of the minio-container running
> 
> 2)
> ```
> Aug 10 14:04:45 minio-01 docker-compose[5035]: minio_1  | Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  |
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | API: SYSTEM()
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | Time: 14:09:44 UTC 08/10/2020
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | DeploymentID: a4e0ed07-72ea-40ac-81ce-0c3e0eb5bbde
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  | Error: Post https://example.net/minio/peer/v10/cyclebloom?: dial tcp 10.11.5.18:443: connect: connection refused
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  |        2: github.com/minio/minio@/cmd/notification.go:478:cmd.(*NotificationSys).updateBloomFilter.func1()
> Aug 10 14:09:44 minio-01 docker-compose[5035]: minio_1  |        1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  |
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | API: SYSTEM()
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | Time: 14:14:44 UTC 08/10/2020
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | DeploymentID: a4e0ed07-72ea-40ac-81ce-0c3e0eb5bbde
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  | Error: /cyclebloom https://example.net/minio/peer/v10: remote server offline
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  |        2: github.com/minio/minio@/cmd/notification.go:478:cmd.(*NotificationSys).updateBloomFilter.func1()
> Aug 10 14:14:44 minio-01 docker-compose[5035]: minio_1  |        1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  |
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | API: SYSTEM()
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | Time: 14:19:44 UTC 08/10/2020
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | DeploymentID: a4e0ed07-72ea-40ac-81ce-0c3e0eb5bbde
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  | Error: /cyclebloom https://example.net/minio/peer/v10: remote server offline
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  |        2: github.com/minio/minio@/cmd/notification.go:478:cmd.(*NotificationSys).updateBloomFilter.func1()
> Aug 10 14:19:44 minio-01 docker-compose[5035]: minio_1  |        1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
> ```
> 
> I saw this error should be fixed with https://github.com/minio/minio/issues/9910 and https://github.com/minio/minio/pull/9928 but it seems like it's not?
> 
> Any ideas?

If they are not printed again, then you can ignore them.

The reconnect would have succeeded.

**Comment by thomic** [comment]
I will try to reproduce the scenario tommorow. But what I can say is, that the ``` API: SYSTEM() ``` were printed (reprinted) more than once.

**Comment by harshavardhana** [comment]
> I will try to reproduce the scenario tommorow. But what I can say is, that the ``` API: SYSTEM() ``` were printed (reprinted) more than once.

It doesn't matter if it's printed more than once, because the reconnect attempt is quick. 

If it's not printed after then everything fine and things move on.

**Comment by harshavardhana** [comment]
Will close this issue, since this is not an issue.
