### ISSUE TITLE
[resolved] PutObject locks object during full upload duration

### ISSUE THREAD

**Issue by lallinger-tech** [minio/minio#10240]
While uploading multiple files in parallel a subsequent parallel listObjects call only finishes after all uploads.

## Expected Behavior
A listObjects call should return with a list of all currently available objects/already completed uploads. This should also return within a short time, even if there are uploads running. When overwriting (uploading objects with an already existing key) this also should return as fast as possible without waiting for any upload to complete.

## Current Behavior
Currently this works as inteded if you first upload some objects. When you upload the same objects again (or overwrite objects with a new one using an already existing key) in parallel the listObject call only returns after all uploads are finished.

The listObjects call should also be fast when overwriting objects.

## Steps to Reproduce (for bugs)

1. Start Minio. At best somewhere where you have relative slow upload speed. This bug can also be seen locally, but then you have to increase the number of objects you upload, to simulate a longer total upload time.
2. create index.js containing:
```
const AWS = require('aws-sdk');
const fs =require('fs')

s3_params= {
    params: { Bucket: "localtest" },
    endpoint: "http://localhost:9000",
        accessKeyId: "admin",
        secretAccessKey:"admintest",
        signatureVersion: "v2",
        s3ForcePathStyle: true
}

s3 = new AWS.S3(s3_params);
let key_marker;

async function list_objects(start){
    let p = new Promise(()=>
    {
        s3.listObjects({
            MaxKeys: 1000,
        }, function (err,data) {
            if(err)throw err;
            console.log(data);
            let end = new Date() - start;
            console.log("end list, timediff: %dms",end);
        });
    })
}

async function upload(){
    let file = fs.readFileSync('./file-1');
    let ustart=new Date();
    // increase if you have fast upload speeds
    for (let i = 1; i < 10; i++) {
        let n="file-"+i
        const request = {
            Key: n,
            Body: file,
        };
        resa =  s3.putObject(request, function (err, data) {
            if (err) throw err;
            console.log("upload took: %dms", new Date() - ustart)
        });
        console.log("started uploading file:",n);
    }
    console.log("start list")
    let start= new Date();
    await list_objects(start);
}

upload();
```
3. Create a file containing about 5MiB, name it ```file-1``` and place it next to ```index.js```
4. Install ```aws-sdk```: ```nnpm install aws-sdk``` (I tested aws-sdk 2.790.0 and 2.660.0)
5. Start the program: ```node .\index.js```
This works as inteded, resulting in this log output:
```
started uploading file: file-1
started uploading file: file-2
started uploading file: file-3
started uploading file: file-4
started uploading file: file-5
started uploading file: file-6
started uploading file: file-7
started uploading file: file-8
started uploading file: file-9
start list
Object {IsTruncated: false, Marker: "", Contents: Array(0), Name: "localtest", Prefix: "", …}
end list, timediff: 1112ms
upload took: 34088ms
upload took: 35757ms
upload took: 35957ms
upload took: 36001ms
upload took: 36020ms
upload took: 36024ms
upload took: 36046ms
upload took: 36091ms
upload took: 36110m
```

Output of mc admin trace:
```
06:06:24.881 [200 OK] s3.ListObjectsV1 localhost:9000/localtest?max-keys=1000  127.0.0.1         291µs       ↑ 67 B ↓ 508 B
06:06:58.221 [200 OK] s3.PutObject localhost:9000/localtest/file-3 127.0.0.1         33.392829s   ↑ 5.3 MiB ↓ 259 B
06:07:00.339 [200 OK] s3.PutObject localhost:9000/localtest/file-1 127.0.0.1         35.507239s   ↑ 5.3 MiB ↓ 259 B
06:07:00.344 [200 OK] s3.PutObject localhost:9000/localtest/file-2 127.0.0.1         35.509066s   ↑ 5.3 MiB ↓ 259 B
06:07:00.364 [200 OK] s3.PutObject localhost:9000/localtest/file-4 127.0.0.1         35.531922s   ↑ 5.3 MiB ↓ 259 B
06:07:00.408 [200 OK] s3.PutObject localhost:9000/localtest/file-5 127.0.0.1         35.563628s   ↑ 5.3 MiB ↓ 259 B
06:07:00.430 [200 OK] s3.PutObject localhost:9000/localtest/file-7 127.0.0.1         35.575946s   ↑ 5.3 MiB ↓ 259 B
06:07:00.492 [200 OK] s3.PutObject localhost:9000/localtest/file-6 127.0.0.1         35.629266s   ↑ 5.3 MiB ↓ 259 B
06:07:00.500 [200 OK] s3.PutObject localhost:9000/localtest/file-8 127.0.0.1         35.628409s   ↑ 5.3 MiB ↓ 259 B
06:07:00.523 [200 OK] s3.PutObject localhost:9000/localtest/file-9 127.0.0.1         35.63437s    ↑ 5.3 MiB ↓ 259 B
```
6. Without deleting the objects rerun the program: ```node .\index.js```
Log output:
```
started uploading file: file-1
started uploading file: file-2
started uploading file: file-3
started uploading file: file-4
started uploading file: file-5
started uploading file: file-6
started uploading file: file-7
started uploading file: file-8
started uploading file: file-9
start list
upload took: 33365ms
upload took: 35431ms
upload took: 35659ms
upload took: 35750ms
upload took: 35907ms
upload took: 36046ms
upload took: 36182ms
upload took: 36264ms
upload took: 36268ms
Object {IsTruncated: false, Marker: "", Contents: Array(9), Name: "localtest", Prefix: "", …}
end list, timediff: 36075ms
```
Output of mc admin trace:
```
06:07:45.977 [200 OK] s3.PutObject localhost:9000/localtest/file-1 127.0.0.1         33.191667s   ↑ 5.3 MiB ↓ 259 B
06:07:47.426 [200 OK] s3.PutObject localhost:9000/localtest/file-3 127.0.0.1         34.635781s   ↑ 5.3 MiB ↓ 259 B
06:07:47.738 [200 OK] s3.PutObject localhost:9000/localtest/file-5 127.0.0.1         34.952353s   ↑ 5.3 MiB ↓ 259 B
06:07:48.116 [200 OK] s3.PutObject localhost:9000/localtest/file-2 127.0.0.1         35.315933s   ↑ 5.3 MiB ↓ 259 B
06:07:48.136 [200 OK] s3.PutObject localhost:9000/localtest/file-8 127.0.0.1         35.313966s   ↑ 5.3 MiB ↓ 259 B
06:07:48.141 [200 OK] s3.PutObject localhost:9000/localtest/file-7 127.0.0.1         35.318758s   ↑ 5.3 MiB ↓ 259 B
06:07:48.157 [200 OK] s3.PutObject localhost:9000/localtest/file-4 127.0.0.1         35.33468s    ↑ 5.3 MiB ↓ 259 B
06:07:48.213 [200 OK] s3.PutObject localhost:9000/localtest/file-9 127.0.0.1         35.386307s   ↑ 5.3 MiB ↓ 259 B
06:07:48.248 [200 OK] s3.PutObject localhost:9000/localtest/file-6 127.0.0.1         35.401347s   ↑ 5.3 MiB ↓ 259 B
06:07:48.249 [200 OK] s3.ListObjectsV1 localhost:9000/localtest?max-keys=1000  127.0.0.1         35.41357s    ↑ 67 B ↓ 3.3 KiB
```
As can be seen the listObjects call now takes as long as the slowest upload. When you try to list the objects in the same bucket using a different client while the upload is still running it also takes until all uploads are finished.

I tried this script uploading sequentially and not in parallel which results in the listObjects call always finishing after the current upload is finished, for example: file-1 is already finished, file-2 started uploading => try to list objects => file-2 finishes uploading => listObjects call returns

## Context

We are using [NooBaa](https://github.com/noobaa/noobaa-operator) in front of Minio for user management, lambda functions and abstraction. We experienced major performance issues with Minio when trying to update the metadata of objects using copyObject.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-08-08T04-50-06Z and minio version RELEASE.2020-08-07T01-23-07Z
* Server setup and configuration: The above output was produced using one Minio pod on an OKD 4.5 cluster with block storage PVC and port forwarding. But this also works on a local setup.
* Operating System and version (`uname -a`): Linux minio-c4fd85589-cpb8l 5.6.19-300.fc32.x86_64 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 Linux

**Comment by klauspost** [comment]
Looks like locking is in effect here.

> A listObjects call should return with a list of all currently available objects/already completed uploads. 

I am not sure that simply not returning "in progress uploads" is a good solution.

For slow uploads you should use multipart uploads which will make the existing objects available until it has completed and therefore doesn't have any locking issues.

I will investigate if there is anything that can be done without sacrificing integrity. Maybe a shorter lock timeout for listobjects is possible.

**Comment by lallinger-tech** [comment]
I think this should return quite fast even if there are uploads pending, because it would also be possible, that these uploads never finish (getting canceled, server timeouts etc..). In this case you would have waited in vain and unnecessarily for the uploads to finish, just to get the list. Also objects only should appear in the listObjects call if their upload is completed and therefore can be downloaded. If there is an operation in progress overwriting a already existing object, the listObjects call should return the "old" object until the "new" one is completely uploaded.

Is minio overwriting an object in place when you upload with the same key? If so the listObjects call should return only the ones which are completely available..

As far as i know you can't use multipart for files less than 5MiB (correct me if i'm wrong) and my example uses an arbitrary filesize just to simulate longer upload times on your connection. In my case a filesize of 6MB was used, resulting in the 34s to complete listObjects call.

Shouldn't the files which are being currently uploaded saved to a temp folder before moving them over into the correct folder?

**Comment by klauspost** [comment]
> Shouldn't the files which are being currently uploaded saved to a temp folder before moving them over into the correct folder?

It is. the lock is however held for the entire operation. I will see if I can change that so it is only held during the rename operation at the end.

> As far as i know you can't use multipart for files less than 5MiB.

The [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html) state that...

> Each part must be at least 5 MB in size, except the last part.

If there is only 1 part having it be < 5MiB doesn't violate that. But most code is probably assuming that uploading 5MiB will be a rather quick operation.

**Comment by lallinger-tech** [comment]
> It is. the lock is however held for the entire operation. I will see if I can change that so it is only held during the rename operation at the end.

That sounds right, thanks!

> The [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html) state that...
> 
> > Each part must be at least 5 MB in size, except the last part.
> 
> If there is only 1 part having it be < 5MiB doesn't violate that. But most code is probably assuming that uploading 5MiB will be a rather quick operation.

Ok, i could easily change the above test, but as stated in "Context" this is not directly my code but rather a put together snippet from me, to simulate the calls Noobaa is doing. Because of this it would be best if it would also work with this type of upload, nonetheless i think by design this should work as one would think, because i'm sure AWS S3 does not take several seconds to minutes for a list object call.

**Comment by harshavardhana** [comment]
This issue looks like is the issue in FS mode instead of our erasure-coded mode. In erasure-coded mode we do not hold any filesystem locks since it fully uses a distributed in-memory lock we don't see this issue at all. 

Is your setup a single drive setup? @lallinger-arbeit 

Here are the outputs

```
mc admin trace myminio-local2/
17:53:33.498 [200 OK] s3.ListObjectsV1 localhost:9002/localtest?max-keys=1000  127.0.0.1         35.148ms     ↑ 134 B ↓ 3.3 KiB
17:53:33.511 [200 OK] s3.ListObjectsV1 localhost:9002/localtest?max-keys=1000  127.0.0.1         55.796ms     ↑ 67 B ↓ 3.4 KiB
17:53:33.754 [200 OK] s3.PutObject localhost:9002/localtest/file-1 127.0.0.1         300.439ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.756 [200 OK] s3.PutObject localhost:9002/localtest/file-4 127.0.0.1         300.741ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.758 [200 OK] s3.PutObject localhost:9002/localtest/file-6 127.0.0.1         302.196ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.759 [200 OK] s3.PutObject localhost:9002/localtest/file-2 127.0.0.1         302.022ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.760 [200 OK] s3.PutObject localhost:9002/localtest/file-7 127.0.0.1         303.906ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.760 [200 OK] s3.PutObject localhost:9002/localtest/file-8 127.0.0.1         304.392ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.761 [200 OK] s3.PutObject localhost:9002/localtest/file-9 127.0.0.1         304.787ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.761 [200 OK] s3.PutObject localhost:9002/localtest/file-5 127.0.0.1         305.373ms    ↑ 5.0 MiB ↓ 294 B
17:53:33.763 [200 OK] s3.PutObject localhost:9002/localtest/file-3 127.0.0.1         306.511ms    ↑ 5.0 MiB ↓ 294 B
```

```
17:53:56.981 [200 OK] s3.ListObjectsV1 localhost:9002/localtest?max-keys=1000  127.0.0.1         56.101ms     ↑ 67 B ↓ 3.4 KiB
17:53:57.292 [200 OK] s3.PutObject localhost:9002/localtest/file-7 127.0.0.1         366.294ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.310 [200 OK] s3.PutObject localhost:9002/localtest/file-6 127.0.0.1         384.872ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.320 [200 OK] s3.PutObject localhost:9002/localtest/file-5 127.0.0.1         394.848ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.320 [200 OK] s3.PutObject localhost:9002/localtest/file-3 127.0.0.1         392.982ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.321 [200 OK] s3.PutObject localhost:9002/localtest/file-4 127.0.0.1         394.797ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.323 [200 OK] s3.PutObject localhost:9002/localtest/file-1 127.0.0.1         400.129ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.323 [200 OK] s3.PutObject localhost:9002/localtest/file-2 127.0.0.1         395.9ms      ↑ 5.0 MiB ↓ 294 B
17:53:57.324 [200 OK] s3.PutObject localhost:9002/localtest/file-8 127.0.0.1         399.218ms    ↑ 5.0 MiB ↓ 294 B
17:53:57.329 [200 OK] s3.PutObject localhost:9002/localtest/file-9 127.0.0.1         403.364ms    ↑ 5.0 MiB ↓ 294 B
```

Listing completes before uploads completed in any situation. 

However, the issue is visible in single drive FS mode
```
~ mc admin trace myminio-local2/
17:54:42.027 [200 OK] s3.PutObject localhost:9002/localtest/file-3 127.0.0.1         255.889ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.027 [200 OK] s3.PutObject localhost:9002/localtest/file-1 127.0.0.1         256.871ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.027 [200 OK] s3.PutObject localhost:9002/localtest/file-9 127.0.0.1         255.171ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.028 [200 OK] s3.PutObject localhost:9002/localtest/file-6 127.0.0.1         254.684ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.031 [200 OK] s3.PutObject localhost:9002/localtest/file-5 127.0.0.1         259.083ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.031 [200 OK] s3.PutObject localhost:9002/localtest/file-2 127.0.0.1         260.028ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.032 [200 OK] s3.PutObject localhost:9002/localtest/file-7 127.0.0.1         258.83ms     ↑ 5.0 MiB ↓ 331 B
17:54:42.037 [200 OK] s3.PutObject localhost:9002/localtest/file-4 127.0.0.1         265.39ms     ↑ 5.0 MiB ↓ 331 B
17:54:42.050 [200 OK] s3.PutObject localhost:9002/localtest/file-8 127.0.0.1         274.823ms    ↑ 5.0 MiB ↓ 331 B
17:54:42.187 [200 OK] s3.ListObjectsV1 localhost:9002/localtest?max-keys=1000  127.0.0.1         415.186ms    ↑ 67 B ↓ 3.3 KiB
```

**Comment by harshavardhana** [comment]
do you have KMS enabled your configuration @lallinger-arbeit ? can you provide more setup details here?

**Comment by lallinger-tech** [comment]
@harshavardhana I'm neither using erasure code mode nor KMS. I would be happy if it would work without, but i can switch, if this resolves the error.

The above output is produced using only a single Minio pod started with `minio server /data` on a RWO block PVC. But we first experienced problems with multiple pods started with the same command, where all pods use the same RWX NFS PVC mounted to /data.

**Comment by harshavardhana** [comment]
> The above output is produced using only a single Minio pod started with `minio server /data` on a RWO block PVC. But we first experienced problems with multiple pods started with the same command, where all pods use the same RWX NFS PVC mounted to /data.

yes, that is the fix in the PR https://github.com/minio/minio/pull/10248 - FS is using filesystem locks which can interfere with on-going uploads, removing them simply makes it work properly. 

Erasure coding is meant for other HA use-cases I am not sure that is what you have.

**Comment by lallinger-tech** [comment]
Ok, i will test your PR. Thanks so far!

**Comment by lallinger-tech** [comment]
@harshavardhana First test works like a charm! I will make further tests with Noobaa and if everything succeeds i will close this issue! Thank you very much!
