### ISSUE TITLE
[not our bug] Creating an index of files to copy is extremely slow. 

### ISSUE THREAD

**Issue by timhughes** [minio/minio#10245]
Creating an index of files to copy is extremely slow. In the below **Current Behavior** section it shows that when `mc` is creating a list of the files it needs to copy it takes approximately 23 minutes on a cold run. When run a second time over the same file-set it takes about 30 seconds (probably cached in minio server). The actual file copy takes ~6 minutes. 

The 23 minutes to create the file listing seems inordinately long. Do you have any thoughts on why this may be occurring and is there any thing that can improve this indexing.

## Expected Behavior
I would expect that the indexing of the files would take much less time than the actual file copy.

## Current Behavior

```
[tim@lddata-live-jupyter01 tim_minio_speed_test]$ time mc cp --recursive blue/top-of-book/parquet/datasource_label\=ldprof/year\=2020/month\=04/ test_blue
...-top-of-book-2020-04-30-23-59.parquet:  31.79 GiB / 31.79 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 91.04 MiB/s 5m57s
real	28m51.871s
user	9m36.892s
sys	9m44.080s
[tim@lddata-live-jupyter01 tim_minio_speed_test]$ du -sh test_blue/
32G	test_blue/
[tim@lddata-live-jupyter01 tim_minio_speed_test]$ time mc cp --recursive blue/top-of-book/parquet/datasource_label\=ldprof/year\=2020/month\=04/ test_blue
...-top-of-book-2020-04-30-23-59.parquet:  31.79 GiB / 31.79 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 92.26 MiB/s 5m52s
real	6m6.236s
user	7m58.164s
sys	6m34.238s
```
## Steps to Reproduce (for bugs)

1. run similar commands to above using `time` before the `mc` commands on a cold dataset and then again over the same set 

## Your Environment

* Version used (`minio --version`):
  * Server side:
    `minio version RELEASE.2020-06-14T18-32-17Z`
  * Client side
     `mc version RELEASE.2019-07-03T18-14-53Z`
* Server setup and configuration:
Underlying filesystem is ZFS mounted with noatime

    `zpool1/data/archive on /data/archive type zfs (rw,noatime)`

* Operating System and version (`uname -a`):
  * Server side:
     `Linux lddata-blue-stormd01 4.4.143-100.el6.x86_64 #1 SMP Wed Jul 25 12:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
  * Client side
     `Linux lddata-live-jupyter01 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by timhughes** [comment]
Just realised that my minio client was quite old so I have upgraded it to be at the closed release to the server side.
Updated client to: `mc version RELEASE.2020-05-28T23-43-36Z`  

They way it reports speed appears to take into account the total time rather than just the data-copy time but the total time is comparable (data set is different month so it was not cached). It also appears to do the 'find all files' in chunks throughout the time period rather than all at the beginning.  
```
[tim@lddata-live-jupyter01 tim_minio_speed_test]$ time mc cp --recursive blue/top-of-book/parquet/datasource_label\=ldprof/year\=2020/month\=05/ test_blue
...-top-of-book-2020-05-31-23-59.parquet:  26.34 GiB / 26.34 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 18.45 MiB/s 24m21s
real	24m21.635s
user	3m41.813s
sys	6m10.141s
[tim@lddata-live-jupyter01 tim_minio_speed_test]$ time mc cp --recursive blue/top-of-book/parquet/datasource_label\=ldprof/year\=2020/month\=05/ test_blue
...-top-of-book-2020-05-31-23-59.parquet:  26.34 GiB / 26.34 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 69.75 MiB/s 6m26s
real	6m26.785s
user	2m59.398s
sys	4m37.810s
```

**Comment by harshavardhana** [comment]
You are better off using mc mirror if that is what you want, mc cp is resumable so it creates an index locally by listing all the content first time. This is not the default behavior. See `mc cp --continue` 

Also mc cp doesn't do session building anymore, and starts copying as soon as the listing batch starts responding.

**Comment by harshavardhana** [comment]
Also it cannot be sped up, it is taking as long as listing is taking for an entire run, depending on how fast your disks are responding to listing operations.

**Comment by timhughes** [comment]
Hi @harshavardhana, 

Thanks for looking at this. I have just had one of those moments where I read you message and though "that is utter rubbish" and went off to prove you wrong, only to find out you were totally correct :facepalm: 

I had a look at the process with strace and it looks to be doing a recursive file listing and then a `stat` to get the file details. This was pretty easy to emulate using `find` and `stat`.

I just ran the following on warm data
```
[root@lddata-blue-stormd01 ~]# time find /data/exports/top-of-book/parquet/datasource_label\=ldprof/year\=2020/month\=05/ -exec stat {} \;
real	1m48.962s
user	0m46.432s
sys	1m3.579s
```
and this on cold
```
[root@lddata-blue-stormd01 ~]# time find /data/exports/top-of-book/parquet/datasource_label\=ldprof/year\=2020/month\=06/ -exec stat {} \;
real	22m37.585s
user	0m46.565s
sys	1m42.940s
```

As always thanks for your time and awesome response speed :1st_place_medal: 

Cheers

Tim
