### ISSUE TITLE
bad throughput deployed 4 nodes each node has 4 optane device and one 40GBE NIC only 450MB/s S3 Bindwidth on each node

### ISSUE THREAD

**Issue by gwnet** [minio/minio#10242]
Hello minio expert, 
not sure if i did anything wrong, but with my distributed deployment mode, the 40GBE and my optane SSD is so not full. only 400MB/s is used on each device. is this expected?

## Steps to Reproduce (for bugs)

1. run minio distributed way on 4 nodes
```
./minio server  http://192.168.150.150/mnt/data1 http://192.168.150.150/mnt/data2 http://192.168.150.150/mnt/data3 http://192.168.150.150/mnt/data4 http://192.168.150.151/mnt/data1 http://192.168.150.151/mnt/data2 http://192.168.150.151/mnt/data3 http://192.168.150.151/mnt/data4 http://192.168.150.152/mnt/data1 http://192.168.150.152/mnt/data2  http://192.168.150.152/mnt/data3 http://192.168.150.152/mnt/data4 http://192.168.150.153/mnt/data1 http://192.168.150.153/mnt/data2 http://192.168.150.153/mnt/data3 http://192.168.150.153/mnt/data4
```
2. then run EMC mongoose or minio S3-Benchmark for read with 64 threads
3. only get 500MB/s on each node and all optane driver is very idle and NIC and CPU is very idle.
4.

====see below counter===
oop8            0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
loop9            0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
nvme0n1       3100.00    121.65     0.00   0.00    0.04    40.18    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00  86.20
nvme1n1       3107.00    122.04     0.00   0.00    0.04    40.22    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00  88.60
nvme2n1          0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
nvme3n1          0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
sda              0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00    

Average:        IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
Average:           lo  25922.17  25922.17 555645.30 555645.30      0.00      0.00      0.00      0.00
Average:    enp24s0f0      5.67      3.50      0.77      1.19      0.00      0.00      2.67      0.00
Average:    enp24s0f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:       ens3f0 330601.83 382926.50 386470.54 479268.01      0.00      0.00      0.00      9.82
Average:    enp24s0f2      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:    enp24s0f3      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:       ens3f1      2.00      0.00      0.12      0.00      0.00      0.00      0.00      0.00

---------------4 nodes, each node will have 400MB/s each optane disk is not full BW.
Aug 11, 2020 12:43:08 AM com.github.akurilov.netty.connection.pool.MultiNodeConnPoolImpl preConnect
INFO: Pre-created 64 connections
2020-08-11T07:43:08,655 I LinearLoadStepClient           main                           wayne-1024k: load step client started, additional nodes: []
------------------------------------------------------------------------------------------------------------------------
 Step Id  | Timestamp  |  Op  |     Concurrency     |       Count       | Step  |   Last Rate    |  Mean    |   Mean    
 (last 10 |            | type |---------------------|-------------------| Time  |----------------| Latency  | Duration  
 symbols) |yyMMddHHmmss|      | Current  |   Mean   |   Success  |Failed|  [s]  | [op/s] |[MB/s] |  [us]    |   [us]    
----------|------------|------|----------|----------|------------|------|-------|--------|-------|----------|-----------
ayne-1024k|200811074308|READ  |         0|0.0       |           0|     0|0.001  |0.0     |0.0    |         0|          0
ayne-1024k|200811074318|READ  |        64|62.6326530|        4052|     0|10.001 |429.3398|428.707|    149509|     153375
ayne-1024k|200811074328|READ  |        64|63.3147208|        8487|     0|20.001 |444.2064|444.206|    145954|     148979
ayne-1024k|200811074338|READ  |        64|63.5439189|       12938|     0|30.001 |441.4058|441.405|    144136|     146886
ayne-1024k|200811074348|READ  |        64|63.6531645|       17292|     0|40.001 |433.6405|433.640|    144396|     147016
ayne-1024k|200811074358|READ  |        64|63.7226720|       21657|     0|50.001 |428.9294|428.929|    144308|     146863
ayne-1024k|200811074408|READ  |        64|63.7622259|       25866|     0|60.001 |411.2371|411.237|    145177|     147680
ayne-1024k|200811074418|READ  |        64|63.7962427|       30064|     0|70.001 |422.8784|422.878|    145873|     148365
ayne-1024k|200811074428|READ  |        64|63.8217446|       34241|     0|80.001 |421.7884|421.788|    146471|     148944
ayne-1024k|200811074438|READ  |        64|63.8415730|       38502|     0|90.001 |423.4816|423.481|    146664|     149123
ayne-1024k|200811074448|READ  |        64|63.8564206|       42734|     0|100.001|406.0969|406.096|    146853|     149293
ayne-1024k|200811074458|READ  |        64|63.8694852|       47018|     0|110.001|425.8126|425.812|    146896|     149326
ayne-1024k|200811074508|READ  |        64|63.8795282|       51247|     0|120.001|418.5374|418.537|    147059|     149487
ayne-1024k|200811074518|READ  |        64|63.8872472|       55571|     0|130.001|436.7203|436.720|    146992|     149416
ayne-1024k|200811074528|READ  |        64|63.8938628|       59922|     0|140.001|452.2626|452.262|    146760|     149178
ayne-1024k|200811074538|READ  |        64|63.8995956|       64316|     0|150.001|440.5466|440.546|    146543|     148956
ayne-1024k|200811074548|READ  |        64|63.9058749|       68711|     0|160.001|424.1493|424.149|    146337|     148744
ayne-1024k|200811074558|READ  |        64|63.9114149|       73400|     0|170.001|528.3521|528.352|    145586|     147989
ayne-1024k|200811074608|READ  |        64|63.9163391|       78781|     0|180.001|517.6694|517.669|    143601|     145997
ayne-1024k|200811074618|READ  |        64|63.9207446|       85033|     0|190.001|704.7598|704.759|    140441|     142824
------------------------------------------------------------------------------------------------------------------------
 Step Id  | Timestamp  |  Op  |     Concurrency     |       Count       | Step  |   Last Rate    |  Mean    |   Mean    
 (last 10 |            | type |---------------------|-------------------| Time  |----------------| Latency  | Duration  
 symbols) |yyMMddHHmmss|      | Current  |   Mean   |   Success  |Failed|  [s]  | [op/s] |[MB/s] |  [us]    |   [us]    
----------|------------|------|----------|----------|------------|------|-------|--------|-------|----------|-----------
ayne-1024k|200811074628|READ  |        64|63.9247094|       91860|     0|200.001|634.1178|634.117|    136792|     139164
ayne-1024k|200811074638|READ  |        64|63.9282964|       98171|     0|210.001|592.5308|592.530|    134361|     136723
2020-08-11T07:46:41,124 I                                main                           wayne-1024k: await for 1 step slices done
ayne-1024k|200811074641|READ  |         0|63.8958630|      100000|     0|212.533|745.5330|745.533|    133442|     135802
---
# Results ##############################################################################################################
- Load Step Id:                wayne-1024k
  Operation Type:              READ
  Node Count:                  1
  Concurrency:                 
    Limit Per Storage Driver:  64
    Actual:                    
      Last:                    0
      Mean:                    63.89586305278174
  Operations Count:            
    Successful:                100000
    Failed:                    0
  Transfer Size:               97.66GB
  Duration [s]:                
    Elapsed:                   212.533
    Sum:                       13580.238419
  Throughput [op/s]:           
    Last:                      745.5330990444439
    Mean:                      471.6981132075472
  Bandwidth [MB/s]:            
    Last:                      745.5330990444439
    Mean:                      471.6981132075472
  Operations Duration [us]:    
    Avg:                       135802.38419
    Min:                       17457
    LoQ:                       51463
    Med:                       65977
    HiQ:                       82355
    Max:                       570798
  Operations Latency [us]:     
    Avg:                       133442.2412
    Min:                       16298
    LoQ:                       49326
    Med:                       63682
    HiQ:                       80146
    Max:                       569243

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
A lot of variables affect performance. That said 1MB objects are pretty small and requires a lot of work but the benchmark progrm

To try another benchmark, you can try [warp](https://github.com/minio/warp). It also provides an option for running the test against all servers directly and has the option of running several warp clients concurrently on several computers.

We do not provide tuning help on github so I will close this issue. You can drop by [Slack](https://slack.min.io/) and see if other community members can help you or look into our [support options](https://min.io/pricing) where we can help directly with performance tuning.

**Comment by gwnet** [comment]
@klauspost  buddy I tried S3-benchmark too. I feel it is not benchmark tool issue. with standard alone minio, I can saturate optane disks. I have new finding. 
even I set the max cores golang use, I found my minio process always use 5 cores no matter how much load I give. I use the minio profile. it show me the find runnable is hotspot.
could you please help me?
root@sm151:/home/intel/wayne/miniobin# env GOMAXPROCS=111
SHELL=/bin/bash
SUDO_GID=1000
MINIO_SECRET_KEY=minio123
SUDO_COMMAND=/bin/bash
SUDO_USER=intel
PWD=/home/intel/wayne/miniobin
LOGNAME=root
HOME=/root
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm
LESSOPEN=| /usr/bin/lesspipe %s
USER=root
DISPLAY=localhost:11.0
SHLVL=1
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
MINIO_ACCESS_KEY=minio
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
SUDO_UID=1000
MAIL=/var/mail/root
OLDPWD=/home/intel/wayne
_=/usr/bin/env
GOMAXPROCS=111

![image](https://user-images.githubusercontent.com/7543276/89894051-059b3f00-dc0c-11ea-80e2-fa579b943ee1.png)
