### ISSUE TITLE
MinIO STS with Okta: The authentication request has an invalid 'state' parameter

### ISSUE THREAD

**Issue by amansaini46** [minio/minio#10252]
I'm trying to use Okta as a web identity provider.  Here is a snippet of configuration. 
export MINIO_IDENTITY_OPENID_CONFIG_URL=https://okta.domainname/oauth2/default/.well-known/openid-configuration
export MINIO_IDENTITY_OPENID_CLIENT_ID="843351d4-1080-11ea-aa20-271ecba3924a"

However, When i try to access MinIO using browser and click on "Login in with OpenId"  I'm getting an error "The authentication request has an invalid 'state' parameter" I have followed the instructions on this page. https://docs.min.io/docs/minio-sts-quickstart-guide.html

## Expected Behavior

I should be able to login to Minio browser client using Okta 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Unable to use STS provider with MinIO

## Regression

No

## Your Environment

* Version used (`minio --version`): REALEASE.2020.08-08T02-33-58Z
* Server setup and configuration: Minio running on docker 
* Operating System and version (`uname -a`): Centos

**Comment by harshavardhana** [comment]
> However, When i try to access MinIO using browser and click on "Login in with OpenId" I'm getting an error "The authentication request has an invalid 'state' parameter" I have followed the instructions on this page. https://docs.min.io/docs/minio-sts-quickstart-guide.html

You need to make sure that you have enabled implicit flow if you want to use browser support. Also if Okta has special scopes please use the `MINIO_IDENTITY_OPENID_SCOPES` to specify the correct scopes.

```
 mc admin config set play/ identity_openid --env
KEY:
identity_openid  enable OpenID SSO support

ARGS:
MINIO_IDENTITY_OPENID_CONFIG_URL*   (url)       openid discovery document e.g. "https://accounts.google.com/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID     (string)    unique public identifier for apps e.g. "292085223830.apps.googleusercontent.com"
MINIO_IDENTITY_OPENID_CLAIM_NAME    (string)    JWT canned policy claim name, defaults to "policy"
MINIO_IDENTITY_OPENID_CLAIM_PREFIX  (string)    JWT claim namespace prefix e.g. "customer1/"
MINIO_IDENTITY_OPENID_SCOPES        (csv)       Comma separated list of OpenID scopes for server, defaults to advertised scopes from discovery document e.g. "email,admin"
MINIO_IDENTITY_OPENID_COMMENT       (sentence)  optionally add a comment to this setting
```

**Comment by amansaini46** [comment]
I have has enabled implicit login. Please see the screenshot below. I have
also set MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email,offline_access"
but still getting the same error.
MINIO_IDENTITY_OPENID_CONFIG_URL=
https://domainname/oauth2/default/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_CLIENT_ID=someID
MINIO_IDENTITY_OPENID_SCOPES=openid,profile,email,offline_access
[image: image.png]
[image: image.png]

**Comment by harshavardhana** [comment]
@amansaini46 it may be that okta is using something special which is missing, we will check and let you know.

**Comment by amansaini46** [comment]
Thank you so much.

**Comment by amansaini46** [comment]
I was wondering if you were able to reproduce the issue.

**Comment by harshavardhana** [comment]
> I was wondering if you were able to reproduce the issue.

@amansaini46 right now didn't have time to look this yet.. will do so when I get free cycles.

**Comment by amansaini46** [comment]
@harshavardhana I think this issue caused by Okta passing the state parameter but MinIo does not know what to do with the state parameter. Hence it throw invalid state paramter error.

**Comment by harshavardhana** [comment]
> @harshavardhana I think this issue caused by Okta passing the state parameter but MinIo does not know what to do with the state parameter. Hence it throw invalid state paramter error.

No it means that `state` parameter sent is unexpected @amansaini46 - i.e we did set a state parameter but that was never returned back.
