### ISSUE TITLE
minio with boto?

### ISSUE THREAD

**Issue by bacongobbler** [minio/minio#1025]
Hi there!

I'm working on moving us off of S3 and onto Minio. However, we rely on software like [WAL-E](https://github.com/wal-e/wal-e) which utilizes boto as the S3 client for connecting to the storage backend. Has anyone managed to get boto working with minio, and if so are there any guides out there for this?

So far, I'm able to connect via boto but it fails because the auth mechanism is not supported:

```
S3ResponseError: S3ResponseError: 400 Bad Request
        <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><Key></Key><BucketName></BucketName><Resource>/dbwal/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

`os.environ['S3_USE_SIGV4'] = 'True'` seems to be the fix according to https://github.com/boto/boto/issues/2741 so I will try that, but I just wanted to document my use case and see if anyone else has managed to get as far as me. :)

Thanks!

**Comment by harshavardhana** [comment]
> So far, I'm able to connect via boto but it fails because the auth mechanism is not supported:

@bacongobbler - Minio server only supports signature v4. So the S3_USE_SIGV4 is correct, we haven't documented using boto with Minio server yet. 

If you use signature version '4' with region as 'us-east-1' it will work. But i will try it out locally and document it.

**Comment by harshavardhana** [comment]
> If you use signature version '4' with region as 'us-east-1' it will work. But i will try it out locally and document it.

Looks like boto3 defaults to signature version '2' 

`{"StartTime":"2016-01-09T03:03:40.166787289Z","Duration":2290,"StatusMessage":"","ContentLength":"","HTTP":{"ResponseHeaders":{},"Request":{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept-Encoding":["identity"],"Authorization":["AWS WLGDGYAQYIGI833EV05A:Oxc2cuKWYcA8YqSTmhQdio6Hrso="],"Date":["Sat, 09 Jan 2016 03:03:40 GMT"],"User-Agent":["Boto3/1.2.3 Python/2.7.10 Darwin/15.0.0 Botocore/1.3.17 Resource"]},"Host":"localhost:9000","Form":null,"PostForm":null,"Trailer":{"Accept-Encoding":["identity"],"Authorization":["AWS WLGDGYAQYIGI833EV05A:Oxc2cuKWYcA8YqSTmhQdio6Hrso="],"Date":["Sat, 09 Jan 2016 03:03:40 GMT"],"User-Agent":["Boto3/1.2.3 Python/2.7.10 Darwin/15.0.0 Botocore/1.3.17 Resource"]},"RemoteAddr":"[::1]:59765","RequestURI":"/"}}}`

**Comment by harshavardhana** [comment]
https://github.com/minio/minio#how-to-use-aws-cli-with-minio - just added documentation, looks like boto is working.

**Comment by harshavardhana** [comment]
going to test boto3 now.

**Comment by harshavardhana** [comment]
> going to test boto3 now.

Here you go make sure that you do these things before using boto3 and just follow https://github.com/minio/minio#how-to-use-aws-cli-with-minio, since boto3 and aws cli shares the same configuration files. 

```
>>> import boto3
>>> s3 = boto3.resource('s3', endpoint_url='http://localhost:9000')
>>> for bucket in s3.buckets.all():
...     print(bucket.name)
...
testbbucket
testbbucketwlgdgyaqyigi833ev05a
testbucket
testbucketwlgdgyaqyigi833ev05a
>>> s3_client = boto3.client('s3', endpoint_url='http://localhost:9000')
>>> s3Client.list_buckets()
{u'Owner': {u'DisplayName': 'minio', u'ID': 'minio'}, u'Buckets': [{u'CreationDate': datetime.datetime(2016, 1, 8, 0, 38, 23, tzinfo=tzutc()), u'Name': 'testbbucket'}, {u'CreationDate': datetime.datetime(2015, 12, 17, 16, 11, 42, tzinfo=tzutc()), u'Name': 'testbbucketwlgdgyaqyigi833ev05a'}, {u'CreationDate': datetime.datetime(2015, 12, 27, 22, 54, 3, tzinfo=tzutc()), u'Name': 'testbucket'}, {u'CreationDate': datetime.datetime(2015, 12, 17, 15, 59, 16, tzinfo=tzutc()), u'Name': 'testbucketwlgdgyaqyigi833ev05a'}], 'ResponseMetadata': {'HTTPStatusCode': 200, 'HostId': '', 'RequestId': 'TVJCFIT00IRZAS81'}}
>>> s3Client.list_objects(Bucket='testbbucket')
{u'Name': 'testbbucket', 'ResponseMetadata': {'HTTPStatusCode': 200, 'HostId': '', 'RequestId': 'KU3IR0WUVAXIVV27'}, u'NextMarker': '', u'Prefix': '', u'MaxKeys': 1000, u'Delimiter': '', u'Marker': '', u'EncodingType': '', u'IsTruncated': False, u'Contents': [{u'LastModified': datetime.datetime(2015, 12, 17, 16, 46, 41, tzinfo=tzutc()), u'ETag': '""', u'StorageClass': 'STANDARD', u'Key': 'caddy', u'Owner': {u'DisplayName': 'minio', u'ID': 'minio'}, u'Size': 12232928}, {u'LastModified': datetime.datetime(2016, 1, 8, 0, 38, 23, tzinfo=tzutc()), u'ETag': '""', u'StorageClass': 'STANDARD', u'Key': 'dddd', u'Owner': {u'DisplayName': 'minio', u'ID': 'minio'}, u'Size': 12232928}, {u'LastModified': datetime.datetime(2015, 12, 23, 9, 42, 29, tzinfo=tzutc()), u'ETag': '""', u'StorageClass': 'STANDARD', u'Key': 'emacs', u'Owner': {u'DisplayName': 'minio', u'ID': 'minio'}, u'Size': 37236368}, {u'LastModified': datetime.datetime(2015, 12, 9, 16, 5, 24, tzinfo=tzutc()), u'ETag': '""', u'StorageClass': 'STANDARD', u'Key': 's3cmd', u'Owner': {u'DisplayName': 'minio', u'ID': 'minio'}, u'Size': 138504}, {u'LastModified': datetime.datetime(2015, 12, 9, 16, 12, 52, tzinfo=tzutc()), u'ETag': '""', u'StorageClass': 'STANDARD', u'Key': 'test/123132/123', u'Owner': {u'DisplayName': 'minio', u'ID': 'minio'}, u'Size': 138504}]}
```

**Comment by cmdelatorre** [comment]
I'm struggling with the same issue and now I found this. Is it possible that the link
* https://github.com/minio/minio#how-to-use-aws-cli-with-minio

chaged to: 

* https://docs.minio.io/docs/aws-cli-with-minio ?

**Comment by deadlylaid** [comment]
hi @harshavardhana 
thanks for your solution
but I have just one question, can I use RabbitMQ with boto3?

like

```
boto3.resource('sqs', endpoint_url='rabbitmq_ip_address')
```
because I want using staging service minio + RabbitMQ (real service is S3+SQS)

**Comment by asm582** [comment]
Hello @harshavardhana ,

In my current setup, I am using codalab stack which is Django with boto on python 2.7.

I get the following exception:
S3ResponseError: S3ResponseError: 400 Bad Request

Below are the properties set in my .env:

DEFAULT_FILE_STORAGE=storages.backends.s3boto.S3BotoStorage
AWS_ACCESS_KEY_ID=Q3AM3UQ867SPQQA43P2F
AWS_SECRET_ACCESS_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
AWS_STORAGE_BUCKET_NAME=public
AWS_STORAGE_PRIVATE_BUCKET_NAME=private
AWS_S3_CALLING_FORMAT=boto.s3.connection.OrdinaryCallingFormat
AWS_S3_HOST=play.min.io
AWS_QUERYSTRING_AUTH=False
S3DIRECT_REGION=us-east-1
S3_USE_SIGV4=True

can you please help on how can I resolve the above exception?

**Comment by harshavardhana** [comment]
Please open a new issue @asm582 - this GitHub issue is too old to reopen.
