### ISSUE TITLE
Cluster replication

### ISSUE THREAD

**Issue by ahmedz890** [minio/minio#10269]
Hi There , 

I need to setup 2 minio clusters in two different location . so my questions are

1. is there any way to create cluster to cluster replication . 
2. when i create one cluster and 2 nodes in each location the connection is  so slow during write or copy  is there is any way to let minio write/read data from specific nodes to avoid using the remote nodes. 

Thanks in advanced

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/minio-bucket-replication-guide.html PTAL here

**Comment by harshavardhana** [comment]
> 2\. when i create one cluster and 2 nodes in each location the connection is  so slow during write or copy  is there is any way to let minio write/read data from specific nodes to avoid using the remote nodes.

We do not support geo erasure coding, you need to have servers with low latency. It is not something we are planning to support.
