### ISSUE TITLE
Not able to attach policy runtime to a temporary credentials generated through STS API

### ISSUE THREAD

**Issue by shrikantgarg17** [minio/minio#10282]
## Expected Behavior
When i attach a policy at runtime to a minio subuser , that policy should be applied to that subuser and it should have access to that bucket/folder which is mentioned in policy

## Current Behavior
When a attaching a policy at runtime to a subuser through java sdk , it still gives 403 access denied error.

Below are the steps i am doing to attach a policy runtime through aws java sdk using STS api.

steps to create policy
	    	Policy policy = new Policy();
	    	Statement statement = new Statement(Statement.Effect.Allow);
              String  resource = String.format("arn:aws:s3:::%s/%s/*",s3BucketName,s3ObjectKey);
              statement.withActions(S3Actions.GetObject).withResources(new Resource(resource));
	    	policy.withStatements(statement);

Now, policy is created.

Next step is to create assumeRole request and attach policy to it.

AssumeRoleRequest roleRequest = new AssumeRoleRequest()
	                .withRoleArn("arn:123:456:789:1234")
	                .withRoleSessionName("anyhting")
	                .withDurationSeconds(7200)
	                .withPolicy(policy.toJson());

 AWSCredentials credentials = new BasicAWSCredentials("newuser",
	    			 "newuser123"); 
This is a minio subuser created from mc add user command.

 ClientConfiguration clientConfiguration = new ClientConfiguration();

Next step is to create sts client using STS API.

 AWSSecurityTokenService stsClient =
	                 AWSSecurityTokenServiceClientBuilder.standard()
	                 .withEndpointConfiguration(new
	                 AwsClientBuilder.EndpointConfiguration("https://minio.com", region))
	                 .withClientConfiguration(clientConfiguration) .withCredentials(new
	                 AWSStaticCredentialsProvider(credentials)) .build();

Now you generate temporay credentials.

AssumeRoleResult response = stsClient.assumeRole(roleRequest);
             Credentials session_creds = response.getCredentials();

This is the whole step i am doing. 
Lets say arn isn resource = "arn:aws:s3:::shri-test/ABCF5TRS/*";

So those temporary credential should have access to any object inside folder ABCF5TRS but when i try to connect to this folder , it gives me access denied 403 error.

Is it not policy to bind any policy runtime to those temporary credentials.
or is there any other way to do this.

Thanks for your help in advance.

I am using aws 1.11.637 java sdk

minio version is 2020-04-15T00:39:01Z

**Comment by harshavardhana** [comment]
You cannot override policy by attaching policies, the policy has to be first present in your original user.

You can use extra policies to further restrict the request but not get privileges beyond your original scope.

**Comment by harshavardhana** [comment]
> You cannot override policy by attaching policies, the policy has to be first present in your original user.
> 
> You can use extra policies to further restrict the request but not get privileges beyond your original scope.

Follow the docs where you need to add `mc admin policy set` which is necessary not just adding the credentials

**Comment by shrikantgarg17** [comment]
so , which means a policy has to be presnt when we create  a user .
and only way to attach policy is through mc commands.

so is there is no way to generate policy at runtime and attach it to user suppose i dont create any policy initally when user was created. All i want to do is through java code and not through mc commnd.

lets say i have a user , that want to request for A object in bucket mybucket , so i generate policy through java code and attach it and then those temporary credentials have access only  to A object.
then that user comes  and request for B object in same object, so again i generate policy through java code and attach it and then those temporary credentials have access only  to B object.
consider there was no policy created from mc command. is it possible?

**Comment by harshavardhana** [comment]
> consider there was no policy created from mc command. is it possible?

No

**Comment by shrikantgarg17** [comment]
ok. When we say we can further restrict it can it be possible like i create policy for that user through mc command for mybucket.
somehting like 

{
    "Version": "2012-10-17",
    "Statement": [
       {
        "Effect": "Allow",
        "Action": "s3:ListBucket",
        "Resource": "arn:aws:s3:::mybucket"
       },
       {
        "Effect": "Allow",
        "Action": [ "s3:GetObject", "s3:PutObject" ],
        "Resource": "arn:aws:s3:::mybucket/*"
      }
   ]
}

and then through java code further restrict it at object level for that user (temporary creds generated throiugh STS API)

**Comment by harshavardhana** [comment]
> ok. When we say we can further restrict it can it be possible like i create policy for that user through mc command for mybucket.
> somehting like
> 
> {
> "Version": "2012-10-17",
> "Statement": [
> {
> "Effect": "Allow",
> "Action": "s3:ListBucket",
> "Resource": "arn:aws:s3:::mybucket"
> },
> {
> "Effect": "Allow",
> "Action": [ "s3:GetObject", "s3:PutObject" ],
> "Resource": "arn:aws:s3:::mybucket/*"
> }
> ]
> }
> 
> and then through java code further restrict it at object level for that user (temporary creds generated throiugh STS API)

Yes that is correct..
