### ISSUE TITLE
refactor presigned-url logic

### ISSUE THREAD

**Issue by KevinSmile** [minio/minio#10284]
**Is your feature request related to a problem? Please describe.**
Currently,  the logics of getting a presigned-url of an object are different based on how you call it:
1. Through web-ui ===> calculate the presigned-url by `minio-server`

https://github.com/minio/minio/blob/ede86845e5968559249625b03db6e0f0319b6df0/cmd/web-handlers.go#L1972

https://github.com/minio/minio/blob/ede86845e5968559249625b03db6e0f0319b6df0/cmd/web-handlers.go#L2049-L2057

2. Through client-sdks (e.g. minio-go client) ===> calculate the presigned-url by `minio-client-sdk` itself
minio-go client sdk provides [PresignedGetObject](https://docs.min.io/docs/golang-client-api-reference.html#PresignedGetObject) :
https://github.com/minio/minio-go/blob/1407169b38f1da4f8caebba411182b4a9edfc0ea/api.go#L734-L747
https://github.com/minio/minio-go/blob/1407169b38f1da4f8caebba411182b4a9edfc0ea/pkg/signer/request-signature-v4.go#L221-L236

You can see that  code in https://github.com/minio/minio-go/tree/master/pkg/signer and https://github.com/minio/minio/blob/master/cmd/signature-v4.go are almost the same.

The problem is, why don't we still call minio-server api when use client-sdks? 
Is it for performance (so let clients do the calculation)?

**Describe the solutions you'd like**
Solution1: Instead of doing the calculation itself, call minio-server api when use a client-sdk to generate presigned-url.

Solution2: move the `signer` implementations from `minio` and `minio-go` the a new standalone project. 
(If we do care about the performance and choose to let clients do the calculation)

**Additional context**
1. It seems that minio-java client also calculates the presigned-url itself.
https://github.com/minio/minio-java/blob/release/api/src/main/java/io/minio/Signer.java#L357-L369

2. https://github.com/minio/minio/issues/10222 seems to be a client issue if we choose Solution2?

**Comment by KevinSmile** [comment]
If this issue makes sense, I'd like to have a try.

**Comment by harshavardhana** [comment]
Generation of presigned URL in server for webUI is manual because of multiple reasons

- avoids a client constructor, there is no reason for the client instance for the server itself to generate a presigned URL 
- provides more control over what is being presigned and any other internal details that needs to be combined such as credential handling etc.

It is possible to re-use some portions from pkg/signer, it's not really a priority right now.

**Comment by KevinSmile** [comment]
OK. Thanks for your quick response! @harshavardhana
