### ISSUE TITLE
[working as intended] mc: <ERROR> Cannot list user. This 'admin' API is not supported by server in 'mode-gateway-azure'

### ISSUE THREAD

**Issue by prasadrajesh** [minio/minio#10299]
Getting error while adding user to minio. I am using mode azure-gateway and k8s on AKS.
Even getting error while listing user. 
Is there any way to add user without etcd?

## Expected Behavior
`mc admin user list minio` it should add user. 

## Current Behavior
"mc: <ERROR> Cannot list user. This 'admin' API is not supported by server in 'mode-gateway-azure'"

` mc admin user list minio --debug`

`mc: <DEBUG> GET /minio/admin/v3/list-users HTTP/1.1
 Host: minio.data-system.svc.cluster.local:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=cerenceminiotest/20200820//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200820T085724Z
Accept-Encoding: gzip`

`mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 221
Accept-Ranges: bytes
Content-Type: application/json
Date: Thu, 20 Aug 2020 08:57:25 GMT
Server: MinIO/RELEASE.2020-06-14T18-32-17Z`

{"Code":"XMinioAdminVersionMismatch","Message":"This` 'admin' API is not supported by server in 'mode-gateway-azure'","Resource":"/minio/admin/v3/list-users","RequestId":"","HostId":"abc694fd-c574-4f22-be32-7c949ac091d5"}
mc: <DEBUG> Response Time:  103.251487ms

`mc: <ERROR> Cannot list user. This 'admin' API is not supported by server in 'mode-gateway-azure'
 (1) admin-user-list.go:73 cmd.mainAdminUserList(..) Tags: [minio]
 (0) admin-user-list.go:73 cmd.mainAdminUserList(..)
 Release-Tag:RELEASE.2020-08-20T00-23-01Z | Commit:ebb05ce469d5 | Host:minio-client-7975db97d-27zf2 | OS:linux | Arch:amd64 | Lang:go1.14.7 | Mem:2.7 MB/73 MB | Heap:2.7 MB/67 MB.`

## Steps to Reproduce (for bugs)

1. create an AKS cluster on Azure.
2. deploy minio server and mode set to azure gateway
3. try to list user `mc admin user list minio --debug`

**Comment by harshavardhana** [comment]
You need to use etcd to enable users in Gateway one of the prerequisites mentioned in the documentation.

https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html
