### ISSUE TITLE
[not our bug] File Lost Illusion when backend is down

### ISSUE THREAD

**Issue by lanpeopless** [minio/minio#10290]
I found a BUG when uploading files ,The program throws the following exception information

![image](https://user-images.githubusercontent.com/38205406/90590722-dbe9a580-e213-11ea-94db-cc54682f55e8.png)

and the console file is also missing

![image](https://user-images.githubusercontent.com/38205406/90590857-29661280-e214-11ea-8957-488bf40b5dbd.png)

When I tried again I encountered the following problem

![image](https://user-images.githubusercontent.com/38205406/90591236-2c153780-e215-11ea-8cbb-c3897e309f80.png)

## MINIO Version And Log

![image](https://user-images.githubusercontent.com/38205406/90591520-e60ca380-e215-11ea-96da-d8601aa09ee7.png)

![image](https://user-images.githubusercontent.com/38205406/90591574-0177ae80-e216-11ea-875f-c133113b1564.png)

## Config and code
![image](https://user-images.githubusercontent.com/38205406/90591679-4d2a5800-e216-11ea-9e88-97030c99c8e4.png)

![image](https://user-images.githubusercontent.com/38205406/90591731-66330900-e216-11ea-872e-1600dc8c14d1.png)

![image](https://user-images.githubusercontent.com/38205406/90591763-7ba83300-e216-11ea-989f-c6c13e8d1b24.png)

**Comment by harshavardhana** [comment]
There is no bug here @lanpeopless your backend is returning incorrect POSIX errors such "host is down" - we cannot access any files on the backend.
