### ISSUE TITLE
[faq] Minio Gateway Notifications

### ISSUE THREAD

**Issue by 2020testuser** [minio/minio#10306]
Hi,
Currently, bucket notification APIs are not supported in minio gateway for s3 as per the below link.
[bucket notification in minio gateway for s3](https://docs.min.io/docs/minio-gateway-for-s3.html)

Could you please let me know whether this feature is in the minio gateway roadmap and if so, when (month/year) this feature would be available for use by minio customers? This feature would be really useful.

Also, if this is not in the roadmap, could you please include it?

Thanks in advance!

**Comment by klauspost** [comment]
We do not have any current plans to extend gateway functionality and are unlikely to do so.
