### ISSUE TITLE
[resolved] missing cleanup of tmp data on IncompleteBody error

### ISSUE THREAD

**Issue by feuerrot** [minio/minio#10304]
## Expected Behavior
If there is an error during PutObject the temporary files/directories below `.minio.sys/tmp which were created for the request should be cleaned up.

Error:
```
API: PutObject(bucket=[bucket name], object=[object])
Time: 16:15:55 UTC 08/17/2020
DeploymentID: ebaef8a7-6ccc-4ab2-9314-9aaeea8bec7a
RequestID: 162C1A562572B633
RemoteHost: [remote host]
Host: hostname
UserAgent: Go-http-client/1.1
Error: /has incomplete body
       6: github.com/minio/minio@/cmd/erasure-object.go:697:cmd.erasureObjects.putObject()
       5: github.com/minio/minio@/cmd/erasure-object.go:566:cmd.erasureObjects.PutObject()
       4: github.com/minio/minio@/cmd/erasure-sets.go:674:cmd.(*erasureSets).PutObject()
       3: github.com/minio/minio@/cmd/erasure-zones.go:552:cmd.(*erasureZones).PutObject()
       2: github.com/minio/minio@/cmd/object-handlers.go:1552:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2036:http.HandlerFunc.ServeHTTP()
```

## Current Behavior
Due to a currently unknown reason this error happens sometimes on our system and it leaves temporary directories:
```
[root@hostname ~]# ls -la /mnt/disks/1/.minio.sys/tmp/
[…]
drwxr-xr-x  3 root root 4096 17. Aug 18:15 a1e14c4b-b3fb-4af4-b3c0-df28edab0aa3
drwxr-xr-x  3 root root 4096 17. Aug 18:11 ad22102f-076c-4551-9517-27fad4ece4bf
```
(timestamps in CEST, so the `a1e14c4b`-directory probably belongs to the error above based on the timestamp. I don't have the content anymore as someone already did a cleanup)

## Possible Solution
I'd suspect that this is a bug somewhere in [easureObjects.putObject()](https://github.com/minio/minio/blob/master/cmd/erasure-object.go#L570) - there [is a defer](https://github.com/minio/minio/blob/master/cmd/erasure-object.go#L601) which should clean up the temporary files, but maybe it doesn't catch the [tempEasureObj](https://github.com/minio/minio/blob/master/cmd/erasure-object.go#L678)?

## Steps to Reproduce (for bugs)
I'm currently not able to reproduce the bug

Edit: I tried to reproduce it using [this code](https://github.com/feuerrot/p14753) but wasn't able to. It ends up at the same code path and logs the same error, but the tmp directory is empty afterwards.

## Regression
Unknown

## Your Environment
* Version used (`minio --version`): RELEASE.2020-08-16T18-39-38Z
* Server setup and configuration: we use the minio/minio docker container running on kubernetes using nginx as our ingress controller

**Comment by vadmeste** [comment]
@feuerrot could you take a look at the content of these directories ? are they empty ? what the size of different files inside those directories ?

**Comment by vadmeste** [comment]
What's the sizes of those stale tmp files ?

**Comment by feuerrot** [comment]
@vadmeste the directories were deleted, because they used all of the remaining free disk space.
```
/mnt/disks/1
   13,9 GiB [##########] /.minio.sys
    5,0 GiB [###       ] /[bucket name]
  458,0 MiB [          ] /[another bucket]
!  16,0 KiB [          ] /lost+found
```

I don't have additional information and I'm also not quite sure, if this is a problem in minio or our setup. Currently I'm still not able to reproduce the bug using concurrent uploads and sending only parts of the body for some of them - as soon as the client closes it's connection (using ^C with the python client, which results in the `/has incomplete body`-error) the temporary files of this connection get removed.

**Comment by vadmeste** [comment]
@feuerrot how do you mount your disks ? are they NFS or something else ?

**Comment by feuerrot** [comment]
@vadmeste The disks are logical volumes on the host, using ext4 as their fs:
```
/dev/mapper/vg1-k8s1 on /mnt/disks/1 type ext4 (rw,relatime,data=ordered)
```
The vg itself is a virtio blockdevice.

**Comment by feuerrot** [comment]
The problem happened twice and during both times we had `proxy-send-timeout` and `proxy-read-timeout` in our nginx ingress controller configuration.
After the last occurence the timeout configuration was removed and since then there was no further one.

I was also not able to reproduce the bug using a local nginx with configured timeouts.

**Comment by vadmeste** [comment]
> I was also not able to reproduce the bug using a local nginx with configured timeouts.

Great, so shall I set low values of 'proxy-send-timeout' and 'proxy-read-timeout' to be able to reproduce this in my machine ?

**Comment by feuerrot** [comment]
@vadmeste You can try. I did on my machine and was also not able to trigger the bug again - as soon as the client process is terminated or runs into the timeout, the corresponding connection from nginx to minio is closed which triggers a cleanup.

Would it be useful to capture data using `mc admin obd` the next time we run into this error or is there any other way, to dump the current internal state of a minio process?

**Comment by vadmeste** [comment]
@feuerrot no need. I was able to reproduce now. We can take it from here.
