### ISSUE TITLE
[not our bug] multiple tcp/udp connections and chunking

### ISSUE THREAD

**Issue by patrickpreuss** [minio/minio#10312]
**Is your feature request related to a problem? Please describe.**
Scaling of outbout bound tcp connections. bandwidth Utilisation

**Describe the solution you'd like**
Have the ability to utilize multiple tcp streams and file chunking over the sessions.
This would help to scaleout wide area links better.

**Comment by harshavardhana** [comment]
MinIO uses HTTP protocol for all communications internode and outbound.

Any other bandwidth shaping should be done outside of MinIO. This issue is not appropriate for MinIO.
