### ISSUE TITLE
ansyc replication feature

### ISSUE THREAD

**Issue by patrickpreuss** [minio/minio#10311]
while using "mc cp file my3/replica" it takes the time until the file is on a remote replica.

** Describe the solution you'd like**
it would be greate to have the ability to configure the replica with asyncronous behavior

**Comment by harshavardhana** [comment]
> while using "mc cp file my3/replica" it takes the time until the file is on a remote replica.
> 
> ** Describe the solution you'd like**
> it would be greate to have the ability to configure the replica with asyncronous behavior

This is on purpose, to make sure that we replicate things atomically as and when the I/O is received.

Bring enough bandwidth between replication targets. We are not planning to add asynchronous requirement.
