### ISSUE TITLE
files created wile replication is turned of do not have the Replication Status: flag

### ISSUE THREAD

**Issue by patrickpreuss** [minio/minio#10313]
Files created while the replica is disbaled do not have the flag replica status
Replication Status: COMPLETE

## Expected Behavior
the Replication Status should be created regardless of the replication state and configuration. 
the replication status should provide information about status in general and specific to an replication Agreement 

## Current Behavior
Name      : tf3
Date      : 2020-08-20 21:10:28 UTC
Size      : 50 MiB
ETag      : 99e44d51e6cec9c639c96cb97f7d8c94
Type      : file
Metadata  :
  Content-Type: application/x-executable
Replication Status: COMPLETE

**Comment by poornas** [comment]
x-amz-replication-status is reported only on objects that are eligible for replication - this is per [s3 spec](https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-status.html)

**Comment by harshavardhana** [comment]
> x-amz-replication-status is reported only on objects that are eligible for replication - this is per [s3 spec](https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-status.html)

Closed as per implementation requirements.
