### ISSUE TITLE
[resolved] automatically cleaning the incomplete uploads does not work

### ISSUE THREAD

**Issue by jianwang-beijing** [minio/minio#10319]
In the other issue https://github.com/minio/minio/issues/10276, I create some incomplete file and I got an information that the all incomplete uploads will be removed after 3 days. But it does not work.

## Expected Behavior
all incomplete uploads will be removed after 3 days

## Current Behavior
all incomplete uploads remain 

## Possible Solution
NO

## Steps to Reproduce (for bugs)

1. setup minio with docker-compose
2. use aws-sdk to create some multipart upload files
3. check the multipart upload files after three days, the result looks like:
```
  ~ mc ls --incomplete --recursive local/ng-temp/part/parttest.zip
[2020-08-17 21:46:51 CST]      0B parttest.zip
[2020-08-17 21:46:01 CST]      0B parttest.zip
[2020-08-17 17:47:03 CST]      0B parttest.zip
[2020-08-17 17:18:17 CST]      0B parttest.zip
[2020-08-17 14:40:52 CST]      0B parttest.zip
[2020-08-17 14:33:25 CST]      0B parttest.zip
```

## Context

In fact, I want the lifecycle function, I test the function on the same minio version in local. The lifecycle does not work(https://github.com/minio/minio/issues/10255 )
So I find the another way to clean the old files in my temp bucket, I use the `rm` and crontab to finish the job:
```
mc rm -r --force --older-than 7d0h0m local/ng-temp
```
The above way is ok for the normal files, but the multipart upload files also need to be removed. So I do the test and find the bug. 

## Regression
NO

## Your Environment
* Version used (`minio --version`):RELEASE.2020-08-13T02-39-50Z
* Server setup and configuration:
* Operating System and version (`uname -a`):Linux ip-10-0-170-187.cn-northwest-1.compute.internal 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jianwang-beijing** [comment]
@harshavardhana Hi, I find your PR has merged and close the issue. So I can test the incomplete file at now with latest release version, right? I find the latest tag is [five days ago](https://hub.docker.com/r/minio/minio/tags), I am not sure whether it is ok to do the test. Another question, the default clean incomplete days is 3, it is too long for testing. Does the incomplete clean days can be configurated?

**Comment by harshavardhana** [comment]
> @harshavardhana Hi, I find your PR has merged and close the issue. So I can test the incomplete file at now with latest release version, right? I find the latest tag is [five days ago](https://hub.docker.com/r/minio/minio/tags), I am not sure whether it is ok to do the test. Another question, the default clean incomplete days is 3, it is too long for testing. Does the incomplete clean days can be configurated?

either user master branch @jianwang-beijing or wait for the next release.

**Comment by jianwang-beijing** [comment]
> > @harshavardhana Hi, I find your PR has merged and close the issue. So I can test the incomplete file at now with latest release version, right? I find the latest tag is [five days ago](https://hub.docker.com/r/minio/minio/tags), I am not sure whether it is ok to do the test. Another question, the default clean incomplete days is 3, it is too long for testing. Does the incomplete clean days can be configurated?
> 
> either user master branch @jianwang-beijing or wait for the next release.

What is our release plan?

**Comment by harshavardhana** [comment]
> > > @harshavardhana Hi, I find your PR has merged and close the issue. So I can test the incomplete file at now with latest release version, right? I find the latest tag is [five days ago](https://hub.docker.com/r/minio/minio/tags), I am not sure whether it is ok to do the test. Another question, the default clean incomplete days is 3, it is too long for testing. Does the incomplete clean days can be configurated?
> > 
> > either user master branch @jianwang-beijing or wait for the next release.
> 
> What is our release plan?

We release every week.

**Comment by jianwang-beijing** [comment]
> > > > @harshavardhana Hi, I find your PR has merged and close the issue. So I can test the incomplete file at now with latest release version, right? I find the latest tag is [five days ago](https://hub.docker.com/r/minio/minio/tags), I am not sure whether it is ok to do the test. Another question, the default clean incomplete days is 3, it is too long for testing. Does the incomplete clean days can be configurated?
> > > 
> > > 
> > > either user master branch @jianwang-beijing or wait for the next release.
> > 
> > 
> > What is our release plan?
> 
> We release every week.

Ok, I wait the next release version. Another question about the default 3 days cleaning, does it can be configurated in order to make the test time short?

**Comment by harshavardhana** [comment]
> 
> Ok, I wait the next release version. Another question about the default 3 days cleaning, does it can be configurated in order to make the test time short?

No there are no plans @jianwang-beijing if you want then you should compile the source and reduce the time.

**Comment by jianwang-beijing** [comment]
> > Ok, I wait the next release version. Another question about the default 3 days cleaning, does it can be configurated in order to make the test time short?
> 
> No there are no plans @jianwang-beijing if you want then you should compile the source and reduce the time.

Ok, Thank you.
