### ISSUE TITLE
Previously removed Header "Server:" reports release-version to the world

### ISSUE THREAD

**Issue by kad-poelw** [minio/minio#10318]
## Expected Behavior
curl -I <url> doesn't show the header "Server:" with included release version.

## Current Behavior
> $ curl -I https://.../.../.../downloads/testfile.zip
> HTTP/1.1 200 OK
> Accept-Ranges: bytes
> Access-Control-Allow-Headers: Content-Type
> Access-Control-Allow-Method: GET,OPTIONS,HEAD
> Access-Control-Allow-Origin: *HH_NL_NUTS2
> Content-Length: 517361
> Content-Md5: q4132f1SOOjG8699sNEk2hLOatguMw==
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/zip
> Date: Tue, 18 Aug 2020 08:* Server setup and configuration:21:46 GMT
> Etag: "ab87f548e3a31bcf6c34493684b3ae33"
> Last-Modified: Wed, 12 Aug 2020 10:19:55 GMT
> Server: MinIO/RELEASE.2020-08-08T04-50-06Z
> Vary: Origin
> X-Amz-Request-Id: 162C4F1218BB8CCD
> X-Xss-Protection: 1; mode=block
> Strict-Transport-Security: max-age=3600; includeSubDomains; preload

## Possible Solution
It has been done before with https://github.com/minio/minio/pull/7074/ where the linux arch and version were removed. Maybe this can be used to also remove the releasetag? Or make it an optional thing to publish via a config setting?

## Steps to Reproduce (for bugs)
1. Host any file (i.e. a zip)
2. Curl towards the file with -I flag
3. Read headers and note "Server:". 

## Context
Amongst the headers of the file hosted the header "Server:" comes back with the current release we are running. We dont want this footprint to be known outside of our organization in case of (zeroday) bugs which might impact our environment.

## Regression
N/A

## Your Environment
* Version used (`minio --version`): RELEASE.2020-08-08T04-50-06Z
* Operating System and version (`uname -a`): Azure k8s environment. Ubuntu 16.04 LTS + k8s 1.16.x

**Comment by harshavardhana** [comment]
> It has been done before with #7074 where the linux arch and version were removed. Maybe this can be used to also remove the releasetag? Or make it an optional thing to publish via a config setting?

We will not remove that @kad-poelw you can go ahead and hide it if you want by adding a proxy.
