### ISSUE TITLE
Expected 'storage' API version 'v20', instead found 'v20'

### ISSUE THREAD

**Issue by adamlamar** [minio/minio#10324]
## Expected Behavior
When upgrading minio from tag `RELEASE.2019-09-26T19-42-35Z` to tag `RELEASE.2020-08-18T19-41-00Z`, a simple rolling restart should allow the upgrade to proceed successfully.

## Current Behavior
Upgrading a minio statefulset running in kubernetes causes minio to not function. These errors are seen in the logs:

```
Unable to read 'format.json' from http://minio-1.minio:9000/storage: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
```
```
API: SYSTEM()
Time: 23:41:38 UTC 08/21/2020
DeploymentID: 29c2bc16-386f-4e9c-b900-c136904e8673
Error: dataUpdateTracker.start: No drives specified
       1: cmd/data-update-tracker.go:179:cmd.(*dataUpdateTracker).start()
```

```
API: SYSTEM()
Time: 23:41:58 UTC 08/21/2020
DeploymentID: 29c2bc16-386f-4e9c-b900-c136904e8673
Error: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
       endpoint=http://minio-2.minio:9000/storage
       2: cmd/prepare-storage.go:52:cmd.glob..func5.1()
       1: cmd/erasure-sets.go:207:cmd.(*erasureSets).connectDisks.func1()
```

Eventually all pods get stuck waiting for the lock:
```
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
```
Although the pods continue to run, minio doesn't seem to recover on its own. 

Prior to the upgrade, these objects existed:

```
$ kubectl run mc -ti --rm --image=minio/mc:latest --restart=Never --command -- /bin/sh -c 'mc config host add minio http://minio:9000 admin changeme; mc mb --ignore-existing minio/test; echo "foo" | mc pipe minio/test/foo; echo "foo2" | mc pipe minio/test/foo2; mc ls minio/test'
If you don't see a command prompt, try pressing enter.
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
Added `minio` successfully.
Bucket created successfully `minio/test`.
[2020-08-21 23:39:48 UTC]      4B foo
[2020-08-21 23:39:48 UTC]      5B foo2
```
After upgrading, the object listing is incorrect (missing `foo2`) and objects uploaded during this time appear to be lost:

```
$ kubectl run mc -ti --rm --image=minio/mc:latest --restart=Never --command -- /bin/sh -c 'mc config host add minio http://minio:9000 admin changeme; mc mb --ignore-existing minio/test; echo "foo" | mc pipe minio/test/foo; echo "foo4" | mc pipe minio/test/foo4; mc ls minio/test'
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
Bucket created successfully `minio/test`.
[2020-08-21 23:44:16 UTC]      4B foo
[2020-08-21 23:44:16 UTC]      5B foo4
pod "mc" deleted

$ kubectl run mc -ti --rm --image=minio/mc:latest --restart=Never --command -- /bin/sh -c 'mc config host add minio http://minio:9000 admin changeme; mc mb --ignore-existing minio/test; echo "foo" | mc pipe minio/test/foo; echo "foo5" | mc pipe minio/test/foo5; mc ls minio/test'
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
Bucket created successfully `minio/test`.
[2020-08-21 23:44:23 UTC]      4B foo
[2020-08-21 23:44:23 UTC]      5B foo5
pod "mc" deleted

$ kubectl run mc -ti --rm --image=minio/mc:latest --restart=Never --command -- /bin/sh -c 'mc config host add minio http://minio:9000 admin changeme; mc mb --ignore-existing minio/test; echo "foo" | mc pipe minio/test/foo; echo "foo6" | mc pipe minio/test/foo6; mc ls minio/test'
If you don't see a command prompt, try pressing enter.
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
Bucket created successfully `minio/test`.
[2020-08-21 23:44:34 UTC]      4B foo
[2020-08-21 23:44:34 UTC]      5B foo6
pod "mc" deleted
```

Note: although minio returns `Server not initialized, please try again` on `mc config`, the `mc mb`, `mc pipe`, and `mc ls` commands don't produce any error.

After scaling down to zero replicas and scaling back up, normal operation is restored, along with the `foo2` object, but not previous uploads:

```
$ kubectl run mc -ti --rm --image=minio/mc:latest --restart=Never --command -- /bin/sh -c 'mc config host add minio http://minio:9000 admin changeme; mc mb --ignore-existing minio/test; echo "foo" | mc pipe minio/test/foo; echo "foo8" | mc pipe minio/test/foo8; mc ls minio/test'
If you don't see a command prompt, try pressing enter.
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
Added `minio` successfully.
Bucket created successfully `minio/test`.
[2020-08-21 23:51:21 UTC]      4B foo
[2020-08-21 23:39:48 UTC]      5B foo2
[2020-08-21 23:51:21 UTC]      5B foo8
pod "mc" deleted
```

## Possible Solution
This issue can be worked around by scaling the minio statefulset to zero replicas and then scaling back up.

## Steps to Reproduce (for bugs)
1. Deploy minio statefulset using tag `RELEASE.2019-09-26T19-42-35Z`
2. Upload a few objects
3. Deploy minio statefulset using tag `RELEASE.2020-08-18T19-41-00Z`
4. Wait until all pods are running
5. Upload objects (these objects will be lost)
6. Restart the statefulset with `kubectl rollout restart sts minio`, note that the behavior persists
7. Scale the statefulset to zero replicas using `kubectl scale sts minio --replicas 0`, wait for all pods to update, then scale back up using `kubectl scale sts minio --replicas 4`
8. Wait until all pods are running
9. Note the cluster is operational again

## Context
Testing the upgrade prior to applying to several existing clusters

## Regression
Yes?

## Your Environment

* Version used (`minio --version`): RELEASE.2019-09-26T19-42-35Z
* Server setup and configuration: kubernetes 1.15
* Operating System and version (`uname -a`): Ubuntu 16.04

**Comment by harshavardhana** [comment]
> * Restart the statefulset with `kubectl rollout restart sts minio`, note that the behavior persists

Rolling upgrades is not supported from 2019 to 2020 @adamlamar you should upgrade all servers simultaneously.

**Comment by harshavardhana** [comment]
The upgrade should be very simple

1. Deploy minio statefulset using tag RELEASE.2019-09-26T19-42-35Z
2. Upload a few objects
3. Scale the statefulset to zero replicas using kubectl scale sts minio --replicas 0,  change the Statefulset image, then scale back up using kubectl scale sts minio --replicas 4
4. mc ls - all objects should be still available

This is the guarantee that we provide, mixing matching versions from 2019 to 2020 rolling upgrades are not allowed.

**Comment by adamlamar** [comment]
Got it, thanks for the quick response! Is there a version constraint that does support rolling upgrades, or should we always scale down entirely and then scale back up?

**Comment by adamlamar** [comment]
Ok I see in the docs that the release notes call out when rolling upgrades are not supported. That works for me, but I did notice that some others in slack also saw the error message `Expected 'storage' API version 'v20', instead found 'v20'` on new clusters. Will leave up to you whether we keep this issue open or closed.

**Comment by kannappanr** [comment]
@adamlamar I think it is fine to close the issue here and open new ones if users are seeing this error between versions which do support non-disruptive upgrade.

**Comment by harshavardhana** [comment]
> Got it, thanks for the quick response! Is there a version constraint that does support rolling upgrades, or should we always scale down entirely and then scale back up?

Yes only if we call it out during the release notes, otherwise you are safe to do rolling upgrades. You should use our operator which manages to upgrade in a much better manner. 

> Ok I see in the docs that the release notes call out when rolling upgrades are not supported. That works for me, but I did notice that some others in slack also saw the error message `Expected 'storage' API version 'v20', instead found 'v20'` on new clusters. Will leave up to you whether we keep this issue open or closed.

The problem is not this, there is a mismatch between clusters since the cluster didn't respond back properly this error message has garbled itself. So it is safe to close this.

**Comment by rerime** [comment]
@harshavardhana 
How to run correctly distributed cluster?

WORKS!
docker run --net host --name minio \
  -e "MINIO_ACCESS_KEY=minio" \
  -e "MINIO_SECRET_KEY=secret" \
  -v /data/minio/data1:/data1 \
  -v /data/minio/data2:/data2 \
  -v /data/minio/data3:/data3 \
  -v /data/minio/data4:/data4 \
  minio/minio:RELEASE.2020-08-16T18-39-38Z server http://server.example.org:9000/data{1...4}

NOT WORK!
docker run -p 9000:9000  --name minio \
  -e "MINIO_ACCESS_KEY=minio" \
  -e "MINIO_SECRET_KEY=secret" \
  -v /data/minio/data1:/data1 \
  -v /data/minio/data2:/data2 \
  -v /data/minio/data3:/data3 \
  -v /data/minio/data4:/data4 \
  minio/minio:RELEASE.2020-08-16T18-39-38Z server http://server.example.org:9000/data{1...4}

WORKS!
docker run -p 9000:9000  --name minio \
  -e "MINIO_ACCESS_KEY=minio" \
  -e "MINIO_SECRET_KEY=secret" \
  -v /data/minio/data1:/data1 \
  -v /data/minio/data2:/data2 \
  -v /data/minio/data3:/data3 \
  -v /data/minio/data4:/data4 \
  minio/minio:RELEASE.2020-08-16T18-39-38Z server /data{1...4}
