### ISSUE TITLE
[working as intended] AccessDenied to the login page of the browser GUI with last version of minio

### ISSUE THREAD

**Issue by JosephLucas** [minio/minio#10322]
## Expected Behavior
Accessing the login page of the browser GUI with http://localhost:9000

## Current Behavior
Getting a XML response with AccessDenied

## Steps to Reproduce (for bugs)
```
su minio # change user to avoid starting minio as root
cd ~ # goes to the home of minio user
mkdir -p dir1/dir2
echo "hello world" >  dir1/dir2/test.txt
minio server --address localhost:9000 dir1
```
Then I execute
```
mc config host add myminio http://localhost:9000 minioadmin minioadmin
```
It works well and 
```
mc ls myminio/dir2
```
returns 
```
[2020-08-21 13:37:42 UTC]     12B test.txt
```
as expected.

But 
```
curl http://localhost:9000
```
returns unexpected
```
*   Trying ::1:9000...
* connect to ::1 port 9000 failed: Connection refused
*   Trying 127.0.0.1:9000...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Accept-Ranges: bytes
< Content-Length: 226
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/RELEASE.2020-07-13T18-09-56Z
< Vary: Origin
< X-Amz-Request-Id: 162D4D3EB36C346A
< X-Xss-Protection: 1; mode=block
< Date: Fri, 21 Aug 2020 13:59:34 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>162D4D3EB36C346A</RequestId><HostId>c5ea4808-c903-4d4d-816a-705274de9b2a</HostId></Error>
```

Thus the mc client seems ok, but the login page of the browser GUI seems broken.

## Your Environment

Using last versions:
```
mc version RELEASE.2020-08-20T00-23-01Z
minio version RELEASE.2020-07-13T18-09-56Z
```
from https://dl.min.io/...

the starting log of minio indicates that 
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 1 month ago ┃
┃ Update: Run `mc admin update`                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```
I cannot execute the update due to my setup. But links from https://dl.min.io/... should be pointing to last versions. It would make no sense to do otherwise IMO.

**Comment by kannappanr** [comment]
the browser login page is `http://localhost:9000/minio/login`

When you do `curl HTTP://localhost:9000` it ends up trying to do a `ListBuckets` API as an anonymous user. Please take a look at the AWS s3 spec https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html

closing this issue. Please feel free to reach out to us at https://slack.min.io for such questions in the future

**Comment by JosephLucas** [comment]
Thank you for the quick answer. I looked at the AWS s3 spec but I don't see what is the relevant in my case.

Previously -- I mean in a previous version of minio, 2 months ago -- the url http://localhost:9000 was redirecting toward the login page. The current [documentation](https://docs.min.io/docs/minio-quickstart-guide.html) still gives the wrong url for the login page of the browser GUI.

Now, with your url
```
curl http://localhost:9000/minio/login
```
returns
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AllAccessDisabled</Code><Message>All access to this bucket has been disabled.</Message><Resource>/minio/login</Resource><RequestId></RequestId><HostId>e1fc1f66-9528-4617-9057-58c6d2e87f77</HostId></Error>
```
It is better, but still not the login page. What can I do  ?

I tried
```
mc policy set public selfminio/pambda
```
without any success.
`mc` works well.

The issue is still open for me.
I'm coming on slack.

**Comment by harshavardhana** [comment]
> Thank you for the quick answer. I looked at the AWS s3 spec but I don't see what is the relevant in my case.
> 
> Previously -- I mean in a previous version of minio, 2 months ago -- the url http://localhost:9000 was redirecting toward the login page. The current [documentation](https://docs.min.io/docs/minio-quickstart-guide.html) still gives the wrong url for the login page of the browser GUI.
> 
> Now, with your url
> 
> ```
> curl http://localhost:9000/minio/login
> ```
> 
> returns
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AllAccessDisabled</Code><Message>All access to this bucket has been disabled.</Message><Resource>/minio/login</Resource><RequestId></RequestId><HostId>e1fc1f66-9528-4617-9057-58c6d2e87f77</HostId></Error>
> ```
> 
> It is better, but still not the login page. What can I do ?
> 
> I tried
> 
> ```
> mc policy set public selfminio/pambda
> ```
> 
> without any success.
> `mc` works well.
> 
> The issue is still open for me.
> I'm coming on slack.

We only redirect to login page if the incoming request is browser @JosephLucas and the error is specifically access denied.

The bucket is public then it automatically goes to the UI

**Comment by JosephLucas** [comment]
I confirm that adding "User-Agent: <whatever browser value>" in the HTTP request works.
For instance
```
curl -vkL http://192.168.56.101:9000 -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
```
Thanks for your help.

**Comment by harshavardhana** [comment]
> I confirm that adding "User-Agent: " in the HTTP request works.
> For instance
> 
> ```
> curl -vkL http://192.168.56.101:9000 -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
> ```
> 
> Thanks for your help.

So this is expected @JosephLucas closing this issue.
