### ISSUE TITLE
[resolved] KES requests fail with HTTP Version Not Supported (S3 gateway)

### ISSUE THREAD

**Issue by tsufeki** [minio/minio#10326]
## Expected Behavior
S3 gateway configured for single encryption and KES should encrypt data when calling PutObject with SSE-S3

## Current Behavior
minio fails with a 500 and following logs:
```
API: PutObject(bucket=tsufeki-k8s-backup-2, object=foo9)
Time: 23:24:58 UTC 08/21/2020
DeploymentID: 70502bde-97ae-4469-b913-dcca8320e6dd
RequestID: 162D6C19314A2974
RemoteHost: 127.0.0.1
Host: 127.0.0.1:9000
UserAgent: aws-cli/1.18.111 Python/3.8.5 Linux/5.7.0-2-amd64 botocore/1.17.22
Error: HTTP Version Not Supported
       6: cmd/api-errors.go:1980:cmd.toAPIErrorCode()
       5: cmd/api-errors.go:2005:cmd.toAPIError()
       4: cmd/object-handlers.go:1535:cmd.objectAPIHandlers.PutObjectHandler()
       3: cmd/http-tracer.go:128:cmd.Trace()
       2: cmd/handler-utils.go:365:cmd.httpTraceHdrs.func1()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```

## Possible Solution

Downgrading KES to 0.8.1 (last version not enforcing HTTP/2) is a working workaround - suggesting that for some reason minio may be using HTTP/1 not 2 to make requests to KES.

## Steps to Reproduce (for bugs)

1. Configure KES as in https://github.com/minio/kes/wiki/MinIO-Object-Storage (self-signed certs)
2. Start `minio gateway s3` with appropriate KMS env vars
3. Run `aws --endpoint-url http://127.0.0.1:9000 s3 cp ./foo s3://some-bucket/foo --sse`

## Context
I'm trying to encrypt Velero backups in Kubernetes.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-08-18T19-41-00Z (docker image)
* KES version: 0.11.0
* Server setup and configuration: small kubernetes cluster ([k3s](https://k3s.io/), both minio and kes are simple deployments and ClusterIP services, they are not behind any proxies or ingresses.
* Operating System and version (`uname -a`): `Linux zeruel1 5.7.0-2-amd64 #1 SMP Debian 5.7.10-1 (2020-07-26) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> Downgrading KES to 0.8.1 (last version not enforcing HTTP/2) is a working workaround - suggesting that for some reason minio may be using HTTP/1 not 2 to make requests to KES.

that doesn't look correct @tsufeki we have to ensure works are you sure are you have correct KES and MinIO versions? 

>         cfg.Transport.ForceAttemptHTTP2 = true

**Comment by harshavardhana** [comment]
```
~ minio gateway s3 https://play.minio.io
Endpoint:  http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000      
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000      

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set mys3 http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

running KES on play 
```
 env |grep KMS
MINIO_KMS_KES_CERT_FILE=/home/harsha/root.cert
MINIO_KMS_KES_KEY_FILE=/home/harsha/root.key
MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373
MINIO_KMS_KES_KEY_NAME=my-minio-key
MINIO_KMS_AUTO_ENCRYPTION=on
```

Looks like you are running an old version of KES @tsufeki you should use latest so that it works fine with latest MinIO.

**Comment by tsufeki** [comment]
@harshavardhana I'm pretty sure both are latest docker images, here are the trace of the request:

```127.0.0.1 [REQUEST s3.PutObject] 23:34:12.129
127.0.0.1 PUT /tsufeki-k8s-backup-2/foo9
127.0.0.1 Proto: HTTP/1.1
127.0.0.1 Host: 127.0.0.1:9000
127.0.0.1 User-Agent: aws-cli/1.18.111 Python/3.8.5 Linux/5.7.0-2-amd64 botocore/1.17.22
127.0.0.1 X-Amz-Date: 20200821T233412Z
127.0.0.1 Expect: 100-continue
127.0.0.1 X-Amz-Content-Sha256: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
127.0.0.1 X-Amz-Server-Side-Encryption: AES256
127.0.0.1 Accept-Encoding: identity
127.0.0.1 Authorization: AWS4-HMAC-SHA256 Credential=000875f47b185670000000004/20200821/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-server-side-encryption, Signature=dcfb458beb71dee9b99c30321607c3ebeaf5116dc6a5ee431189e8e547665f40
127.0.0.1 Content-Length: 4
127.0.0.1 Content-Md5: 07BzhNET7exJ6qYjitX/AA==
127.0.0.1 <BODY>
127.0.0.1 [RESPONSE] [23:34:12.129] [ Duration 7.553ms  ↑ 141 B  ↓ 618 B ]
127.0.0.1 500 Internal Server Error
127.0.0.1 Server: MinIO/RELEASE.2020-08-18T19-41-00Z
127.0.0.1 Vary: Origin
127.0.0.1 X-Amz-Request-Id: 162D6C9A27079E63
127.0.0.1 X-Xss-Protection: 1; mode=block
127.0.0.1 Accept-Ranges: bytes
127.0.0.1 Content-Length: 349
127.0.0.1 Content-Security-Policy: block-all-mixed-content
127.0.0.1 Content-Type: application/xml
127.0.0.1 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>foo9</Key><BucketName>tsufeki-k8s-backup-2</BucketName><Resource>/tsufeki-k8s-backup-2/foo9</Resource><RequestId>162D6C9A27079E63</RequestId><HostId>b71749f1-fe4a-46a8-863f-7713b655beac</HostId></Error>
127.0.0.1
```

Versions were the first thing I checked, please take another look.

**Comment by aead** [comment]
@tsufeki The error (exposed in the MinIO) logs occurs b/c the request to KES was not made over HTTP/2. However, since 145f501 MinIO tries to use HTTP/2 if the peer supports it when talking to KES.
Is there another system (like an HTTP proxy) between MinIO and KES? Also, can you confirm that KES received the request and returned the `UnsupportedVersion` error by running:

```
kes log trace
```
See https://github.com/minio/kes/wiki/Logs-and-Monitoring#monitoring

**Comment by tsufeki** [comment]
@aead I confirmed that KES got the requests:
```
$ ./kes log trace -k
638f397 [200 OK] /v1/log/audit/trace             22µs
638f397 [505 HTTP Version Not Supported] /v1/key/generate/minio-gateway        7µs
638f397 [505 HTTP Version Not Supported] /v1/key/generate/minio-gateway        9µs
638f397 [505 HTTP Version Not Supported] /v1/key/generate/minio-gateway       43µs
638f397 [505 HTTP Version Not Supported] /v1/key/generate/minio-gateway        5µs
638f397 [505 HTTP Version Not Supported] /v1/key/generate/minio-gateway        4µs
```
And minio version is definitely ok:
```
$ kubectl exec -ti -n minio-test minio-gateway-6f5cf56d6-djdq9 -- minio --version
minio version RELEASE.2020-08-18T19-41-00Z
```
There is no proxy between minio and kes, they communicate directly through kube pod-to-pod network. I've made a [repo with my complete setup](https://github.com/tsufeki/minio-repro-10326) if you wanted to check the details.

Thanks
