### ISSUE TITLE
[resolved] Inaccurate response for not-valid authorization region

### ISSUE THREAD

**Issue by serverwentdown** [minio/minio#10333]
This hard-coded region might confuse users when they encounter mismatching regions. 

https://github.com/minio/minio/blob/81c90ae43013a0616a0cda15f0ef1f4d2fb72bc4/cmd/api-errors.go#L603

**Comment by serverwentdown** [comment]
repeat issue for #10250

**Comment by harshavardhana** [comment]
fixed in #10323
