### ISSUE TITLE
Cannot build with CGO_ENABLED=0

### ISSUE THREAD

**Issue by arschles** [minio/minio#1033]
Hey guys,

I'm trying to build a Minio server from HEAD to run in an `alpine:3.3` container as part of the Deis platform. I'm currently building from HEAD using [this script](https://github.com/deis/minio/blob/master/server/install.sh), which essentially downloads the latest source code from `master` and runs `make install` on it.

When running that in a docker container that includes the `CGO_ENABLED` environment variable set to `0`, the below error occurs:

``` console
Installing minio:
# github.com/minio/minio/vendor/github.com/minio/minio-xl/pkg/crypto/sha256
vendor/github.com/minio/minio-xl/pkg/crypto/sha256/sha256_linux_amd64.go:63: undefined: blockAVX2
vendor/github.com/minio/minio-xl/pkg/crypto/sha256/sha256_linux_amd64.go:65: undefined: blockAVX
vendor/github.com/minio/minio-xl/pkg/crypto/sha256/sha256_linux_amd64.go:67: undefined: blockSSE
vendor/github.com/minio/minio-xl/pkg/crypto/sha256/sha256_linux_amd64.go:69: undefined: blockGeneric
# github.com/minio/minio/vendor/github.com/minio/minio-xl/pkg/crypto/sha512
vendor/github.com/minio/minio-xl/pkg/crypto/sha512/sha512_linux_amd64.go:50: undefined: blockAVX2
vendor/github.com/minio/minio-xl/pkg/crypto/sha512/sha512_linux_amd64.go:52: undefined: blockAVX
vendor/github.com/minio/minio-xl/pkg/crypto/sha512/sha512_linux_amd64.go:54: undefined: blockSSE
vendor/github.com/minio/minio-xl/pkg/crypto/sha512/sha512_linux_amd64.go:56: undefined: blockGeneric
Makefile:59: recipe for target 'gomake-all' failed
make: *** [gomake-all] Error 2
cp: cannot stat '/go/bin/minio': No such file or directory
make: *** [build-server] Error 1
```

I'm guessing the error happens because there's no default configuration when no build tag gets compiled, but I'm not sure if there's a solution in this case. Anyway, this command should reproduce the file:

``` console
docker run -e CGO_ENABLED=0 -e GO15VENDOREXPERIMENT=1 -e GOROOT=/usr/local/go --rm -v /path/to/install.sh:/pwd -w /pwd golang:1.5.2 ./install.sh
```

**Comment by harshavardhana** [comment]
The issue is largely coming in from the assembly files which require CGO

**Comment by harshavardhana** [comment]
@arschles - is there a reason to build minio inside docker image? - There is a more convenient way - 'make dockerimage' 

In this case it would create a docker image with minio binary copied in. There is a way to fix it btw, working on it.

**Comment by harshavardhana** [comment]
With CGO enabled 'minio' server will use processor optimized version of sha256 which are significantly faster than Golang sha256 package. 

SO wondering it makes sense to not disable them this way even for docker images.

**Comment by arschles** [comment]
Hey @harshavardhana - I unfortunately need to build a binary that I can `COPY` into my own Docker image, which is based on `alpine:3.3`. This doesn't work if I `make dockerimage` and then `docker cp` the binary into my alpine based image due to an exec file format error.

I do believe that `go build --ldflags '-extldflags -static'` does produce an alpine compatible binary when executed with `GOOS=linux` (or on a linux based system). I'm still testing, but so far so good!

Sidenote: when you make official releases, will you be providing alpine-compatible binaries?

**Comment by harshavardhana** [comment]
> Sidenote: when you make official releases, will you be providing alpine-compatible binaries?

What architecture are you looking for alpine? is this arm based? - 

Additionally current HEAD should build without cgo available . I made changes so that they all fall back to golang native packages rather than using our assembly files.

**Comment by arschles** [comment]
It can still be amd64, but they'll have to be built without cgo available. I haven't been keeping up with HEAD for the past week or so - is there a makefile target that will build with cgo turned off?

**Comment by harshavardhana** [comment]
> It can still be amd64, but they'll have to be built without cgo available. I haven't been keeping up with HEAD for the past week or so - is there a makefile target that will build with cgo turned off?

There is no need if CGO is disabled it will automatically build with regular 'make'

**Comment by harshavardhana** [comment]
> There is no need if CGO is disabled it will automatically build with regular 'make'

We have written extensions of sha1,sha256 and sha512 which sadly requires CGO since the extensions are in assembly for processor optimizations. 

But we added build pragmas so that if cgo is disabled we don't throw errors during builds,  rather fallback to golang native packages.

**Comment by arschles** [comment]
Ok, thanks for that explanation. From what I understand, and given the restrictions given by the makefile, the below command should work:

``` console
docker run -e CGO_ENABLED=0 -e GOOS=linux -e GO15VENDOREXPERIMENT=1 -e GOPATH=/go -e GOROOT=/usr/local/go -e PWD=/go/src/github.com/minio/minio -v $GOPATH:/go -w /go/src/github.com/minio/minio golang:1.5.2 make
```

It indeed works:

``` console
ENG000656:minio aaronschlesinger$ docker run -e CGO_ENABLED=0 -e GOOS=linux -e GO15VENDOREXPERIMENT=1 -e GOPATH=/go -e GOROOT=/usr/local/go -e PWD=/go/src/github.com/minio/minio -v $GOPATH:/go -w /go/src/github.com/minio/minio golang:1.5.2 make
Checking deps:
Check for supported arch.. Check for supported os.. Checking if proper environment variables are set.. Done
Using GOPATH=/go and GOROOT=/usr/local/go
Checking dependencies for Minio.. Done
Checking if project is at /go
Setting BUILD_LDFLAGS: '-X main.minioVersion=2016-01-15T18:56:35Z -X main.minioReleaseTag=UNOFFICIAL.2016-01-15T18-56-35Z -X main.minioCommitID=8ff43086fb154bbaa7f584dcb5c9cc013fa137ea -X main.minioShortCommitID=8ff43086fb15'
Installed golint:
Installed vet:
Installed gocyclo:
Installed deadcode:
Running vet:
Running fmt:
Running lint:
Running cyclo:
Installing minio:
```

However, it still doesn't run inside `alpine:3.3`:

``` console
ENG000656:minio aaronschlesinger$ docker run --rm -e DOCKERIMAGE=1 -v $GOPATH/bin -w /minbin alpine:3.3 ./minio
exec: "./minio": stat ./minio: no such file or directory
Error response from daemon: Cannot start container c6904340affb023688c6adec62fdbd1891a9b0e2ab4c8801b88bb9758d322d30: [8] System error: exec: "./minio": stat ./minio: no such file or directory
```

I believe this is because the `go build` command is still missing the `--ldflags '-extldflags -static'` flags in the `gomake-all` target. Thoughts?

**Comment by arschles** [comment]
By the way, I have to run the build commands inside of a container because I'm running them on a mac and don't have any linux headers installed.

**Comment by harshavardhana** [comment]
> ENG000656:minio aaronschlesinger$ docker run --rm -e DOCKERIMAGE=1 -v $GOPATH/bin -w /minbin alpine:3.3 ./minio
> exec: "./minio": stat ./minio: no such file or directory
> Error response from daemon: Cannot start container c6904340affb023688c6adec62fdbd1891a9b0e2ab4c8801b88bb9758d322d30: [8] System error: exec: "./minio": stat ./minio: no such file or directory

The binary is built and should be available inside your GOPATH in the docker image, not at './minio'

**Comment by harshavardhana** [comment]
> The binary is built and should be available inside your GOPATH in the docker image, not at './minio'

Oh i see the '-v' is set, wondering where its copied to.

**Comment by arschles** [comment]
Ah, typo in the second command. I forgot to mount the volume to `/minbin` inside the container. Note the addition of `:/minbin` after the `-v $GOPATH/bin`.

After fixing the command, it looks like things work. Logs below. Thanks for your help here.

``` console
ENG000656:minio aaronschlesinger$ docker run --rm -e DOCKERIMAGE=1 -v $GOPATH/bin:/minbin -w /minbin alpine:3.3 ./minio
NAME:
  Minio - Cloud Storage Server for Micro Services.

DESCRIPTION:
  Micro services environment provisions one Minio server per application instance. Scalability is achieved through large number of smaller personalized instances. This version of the Minio binary is built using Filesystem storage backend for magnetic and solid state disks.

USAGE:
  minio [flags] command [arguments...]

COMMANDS:
  server    Start Minio cloud storage server.
  config    Collection of config management commands.
  version   Print version.
  update    Check for a new software update.

FLAGS:
  --config-folder, -C "/minbin/.minio"  Path to configuration folder.
  --address ":9000"         ADDRESS:PORT for cloud storage access.
  --cert                Provide your domain certificate.
  --key                 Provide your domain private key.
  --json                Enable json formatted output.

VERSION:
  2016-01-15T18:56:35Z

MEM:
  Used: 287kB | Allocated: 287kB | Used-Heap: 287kB | Allocated-Heap: 852kB

PLATFORM:
  Host: be18e46274f7 | OS: linux | Arch: amd64

RUNTIME:
  Version: go1.5.2 | CPUs: 1
```

**Comment by harshavardhana** [comment]
> After fixing the command, it looks like things work. Logs below. Thanks for your help here.

Perfect as expected.

**Comment by harshavardhana** [comment]
Ping us if you have more issues..

**Comment by arschles** [comment]
Will do, thanks @harshavardhana
