### ISSUE TITLE
Uploads From Client Are Killed

### ISSUE THREAD

**Issue by capriciousduck** [minio/minio#10340]
When uploading a file to my minio server, the client outputs "Killed" and the upload stops. I'm running the client from Clever-Cloud Paas.

**Comment by klauspost** [comment]
There is no such error returned by the server.

Please refile with the requested information in the issue template and additional information needed to reproduce the issue.

**Comment by capriciousduck** [comment]
I'm sorry. I mean when I try to upload from the mc client, it outputs that error.

**Comment by capriciousduck** [comment]
Here is the debug:

`mc: <DEBUG> GET /movies/?location= HTTP/1.1
Host: minio.cleverapps.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=capriciousduck/20200824/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200824T144155Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 24 Aug 2020 14:41:55 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Sozu-Id: 5da8ed2c-69a3-46bf-a0ac-005e9ba3b712
Vary: Origin
X-Amz-Request-Id: 162E3B4BF3C03E31
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  107.545205ms

mc: <DEBUG> HEAD /movies/ HTTP/1.1
Host: minio.cleverapps.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=capriciousduck/20200824/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200824T144155Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Mon, 24 Aug 2020 14:41:55 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Sozu-Id: 5da8ed2c-69a3-46bf-a0ac-005e9ba3b712
Vary: Origin
X-Amz-Request-Id: 162E3B4BF41A2F7C
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  3.099033ms

mc: <DEBUG> HEAD /movies/ HTTP/1.1
Host: minio.cleverapps.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=capriciousduck/20200824/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200824T144155Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Mon, 24 Aug 2020 14:41:55 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Sozu-Id: 75fce11f-0a34-4808-8b86-e70a6ee4eb77
Vary: Origin
X-Amz-Request-Id: 162E3B4BF45A16E3
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  3.100162ms

 0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃mc: <DEBUG> HEAD /movies/ HTTP/1.1
Host: minio.cleverapps.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=capriciousduck/20200824/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200824T144155Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Mon, 24 Aug 2020 14:41:55 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Sozu-Id: 4531de5a-d100-4bf7-b324-692f81ae519f
Vary: Origin
X-Amz-Request-Id: 162E3B4BF49B1B53
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  3.123861ms

mc: <DEBUG> GET /movies/?object-lock= HTTP/1.1
Host: minio.cleverapps.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=capriciousduck/20200824/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200824T144155Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Content-Length: 330
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 24 Aug 2020 14:41:55 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Sozu-Id: b3b59fb8-457b-4eb9-a075-a8f85b6aa94c
Vary: Origin
X-Amz-Request-Id: 162E3B4BF4DC72B0
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ObjectLockConfigurationNotFoundError</Code><Message>Object Lock configuration does not exist for this bucket</Message><BucketName>movies</BucketName><Resource>/movies/</Resource><RequestId>162E3B4BF4DC72B0</RequestId><HostId>1f5c4a5e-43c3-416f-92c5-0fddc0b2c28a</HostId></Error>mc: <DEBUG> Response Time:  3.187446ms

mc: <DEBUG> POST /movies/The.One.and.Only.Ivan.2020.1080p.DSNP.WEBRip.DDP5.1.x264-CM.mkv?uploads= HTTP/1.1
Host: minio.cleverapps.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.5 mc/2020-08-20T00:23:01Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=capriciousduck/20200824/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: video/x-matroska
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20200824T144155Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 304
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 24 Aug 2020 14:41:55 GMT
Server: MinIO/RELEASE.2020-08-18T19-41-00Z
Sozu-Id: 18317acb-b711-495a-a20e-0ffb1504079b
Vary: Origin
X-Amz-Request-Id: 162E3B4BF518002B
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  4.380598ms

...p.DSNP.WEBRip.DDP5.1.x264-CM.mkv:  0 B / 5.71 GiB ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃Killed`

**Comment by klauspost** [comment]
Seems like your operating system is killing the process.

(1) The process which (common cause) takes too much memory and causes the OOM condition (2) The kernel which sends the SIGKILL (signal 9) to terminate it and logs the fact in some system log like /var/log/messages

This is for the minio server. Issues with `mc` are here: https://github.com/minio/mc
