### ISSUE TITLE
make the docker binary check more generic

### ISSUE THREAD

**Issue by arschles** [minio/minio#1035]
for users who have the `docker` CLI installed in a non-standard location for linux, the `make dockerimage` target won't work. [This line](https://github.com/minio/minio/blob/master/Makefile#L74) should probably be changed to `which docker`

**Comment by harshavardhana** [comment]
> for users who have the docker CLI installed in a non-standard location for linux, the make dockerimage target won't work. This line should probably be changed to which docker

Perfect. Will change that.

**Comment by arschles** [comment]
thanks @harshavardhana !
