### ISSUE TITLE
[working as intended] Incorrect value for MINIO_COMPRESS in docs for some versions

### ISSUE THREAD

**Issue by mac-chaffee** [minio/minio#10350]
The documentation for enabling compression on disk say to set MINIO_COMPRESS="on": https://docs.minio.io/docs/minio-compression-guide.html

But some versions of minio expect MINIO_COMPRESS="true": https://github.com/minio/minio/blob/RELEASE.2019-05-23T00-29-34Z/cmd/common-main.go#L394

## Expected Behavior
Docs for enabling compression should match expected values in the code

## Current Behavior
Following the compression docs on some versions (specifically around RELEASE.2019-05-23T00-29-34Z) will not result in compression being enabled

## Possible Solution
I'm not sure what the current environment variable is, seems like it has recently been changed to `MINIO_COMPRESS_ENABLE="enable"`: https://github.com/minio/minio/blob/master/cmd/config/compress/compress.go#L39

But that value seems to have changed a few times if you look at the history, like `MINIO_COMPRESS_STATE`

So it seems we have some options:
1. Update the docs to have a table which maps minio versions to expected environment variables
2. Maybe update the config to accept some of these legacy environment variables
3. Something else?

## Steps to Reproduce (for bugs)
```
docker run -d --rm --name myminio -e MINIO_COMPRESS=on minio/minio:RELEASE.2019-05-23T00-29-34Z server /export

docker exec -it myminio ash
wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc && mv ./mc /bin

mc ls
vi ~/.mc/config.json  # set secret key/access key

# download a 1.2MB text file
wget http://www.gutenberg.org/files/2701/2701-0.txt -O moby_dick.txt
mc mb local/compression-test
mc cp moby_dick.txt local/compression-test

# Inspect the size on disk of that file, it is still the full 1.2MB
ls -alh /export/compression-test
```

## Context
We have about 5TB of data in our live minio instance, and we're creating a backup of that data. So we want the backup minio instance to have compression enabled since 99% of the files are large text files.

## Regression
No, seems the docs have always been out of sync with the code since the original PR that enabled compression

## Your Environment
* Version used: 
```
Version: 2019-05-23T00:29:34Z
Release-Tag: RELEASE.2019-05-23T00-29-34Z
Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8
```
* Server setup and configuration: single node, docker
* Operating System and version (`uname -a`): alpine

**Comment by harshavardhana** [comment]
> Version: 2019-05-23T00:29:34Z
> Release-Tag: RELEASE.2019-05-23T00-29-34Z
> Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8

You are using a really old release here, we have re-implemented pretty much every area since. 
The latest docs talk about the latest releases. 

> Docs for enabling compression should match expected values in the code

To meet the expected state use the latest releases.

**Comment by kannappanr** [comment]
PTAL https://github.com/minio/minio/tree/RELEASE.2019-05-23T00-29-34Z/docs/compression for documentation corresponding to that version

**Comment by mac-chaffee** [comment]
Ah thanks @kannappanr I missed that page. And thanks @harshavardhana , I think my confusion came from compress.go expecting MINIO_COMPRESS_ENABLE, but I missed that compress/legacy.go does support MINIO_COMPRESS=on as the docs indicate: https://github.com/minio/minio/blob/9acdeab73d7edd154c91481504036fb5209d583f/cmd/config/compress/legacy.go#L27

Thank you both for your time!
