### ISSUE TITLE
[not our bug] 400 Bad Request for uploading video using POST request

### ISSUE THREAD

**Issue by Rohan29** [minio/minio#10356]
## Expected Behavior
Hello Guys , videos should be uploaded successfully

## Current Behavior
 I am getting 400 Bad Request Error from Minio server while uploading video of size larger than 1 mb
Also getting error - Body of your post request is not well formed

Error Log on IOS side
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: bad request (400)" UserInfo={NSLocalizedDescription=Request failed: bad request (400), NSErrorFailingURLKey=**https://URL/bucket name/**, com.alamofire.serialization.response.error.data={length = 341, bytes = 0x3c3f786d 6c207665 7273696f 6e3d2231 ... 3c2f4572 726f723e }, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x280c00540> { URL: **https://URL/bucket name/**, } { Status Code: 400, Headers {
    "Accept-Ranges" =     (
        bytes
    );
    Connection =     (
        close
    );
    "Content-Security-Policy" =     (
        "block-all-mixed-content"
    );
    "Content-Type" =     (
        "application/xml"
    );
    Date =     (
        "Wed, 26 Aug 2020 08:26:16 GMT"
    );
    Server =     (
        "Minio/RELEASE.2019-03-27T22-35-21Z"
    );
    "Transfer-Encoding" =     (
        Identity
    );
    Vary =     (
        Origin
    );
    "X-Amz-Request-Id" =     (
        162EC3F1BA60CC93
    );
    "X-Minio-Deployment-Id" =     (
        "90b44fa3-ada0-41e3-923d-1ff68e459265"
    );
    "X-Xss-Protection" =     (
        "1; mode=block"
    );
} }}

## Your Environment
I am using IOS device

**Comment by harshavardhana** [comment]
> I am getting 400 Bad Request Error from Minio server while uploading video of size larger than 1 mb
> Also getting error - Body of your post request is not well formed

Please share your code, NOTE MinIO is S3 compatible so you be using POST-multipart-form method

**Comment by Rohan29** [comment]
Hello , we are sending multipart data in encrypted format

This is form object 
+ (nullable OWSUploadForm *)parse:(nullable NSDictionary *)formResponseObject
{
    if (![formResponseObject isKindOfClass:[NSDictionary class]]) {
        OWSFailDebug(@"Invalid upload form.");
        return nil;
    }
    NSDictionary *responseMap = formResponseObject;

    NSString *_Nullable formAcl = responseMap[@"acl"];
    if (![formAcl isKindOfClass:[NSString class]] || formAcl.length < 1) {
        OWSFailDebug(@"Invalid upload form: acl.");
        return nil;
    }
    NSString *_Nullable formKey = responseMap[@"key"];
    if (![formKey isKindOfClass:[NSString class]] || formKey.length < 1) {
        OWSFailDebug(@"Invalid upload form: key.");
        return nil;
    }
    NSString *_Nullable formPolicy = responseMap[@"policy"];
    if (![formPolicy isKindOfClass:[NSString class]] || formPolicy.length < 1) {
        OWSFailDebug(@"Invalid upload form: policy.");
        return nil;
    }
    NSString *_Nullable formAlgorithm = responseMap[@"algorithm"];
    if (![formAlgorithm isKindOfClass:[NSString class]] || formAlgorithm.length < 1) {
        OWSFailDebug(@"Invalid upload form: algorithm.");
        return nil;
    }
    NSString *_Nullable formCredential = responseMap[@"credential"];
    if (![formCredential isKindOfClass:[NSString class]] || formCredential.length < 1) {
        OWSFailDebug(@"Invalid upload form: credential.");
        return nil;
    }
    NSString *_Nullable formDate = responseMap[@"date"];
    if (![formDate isKindOfClass:[NSString class]] || formDate.length < 1) {
        OWSFailDebug(@"Invalid upload form: date.");
        return nil;
    }
    NSString *_Nullable formSignature = responseMap[@"signature"];
    if (![formSignature isKindOfClass:[NSString class]] || formSignature.length < 1) {
        OWSFailDebug(@"Invalid upload form: signature.");
        return nil;
    }

    NSNumber *_Nullable attachmentId = responseMap[@"attachmentId"];
    if (attachmentId == nil) {
        // This value is optional.
    } else if (![attachmentId isKindOfClass:[NSNumber class]]) {
        OWSFailDebug(@"Invalid upload form: attachmentId.");
        return nil;
    }
    NSString *_Nullable attachmentIdString = responseMap[@"attachmentIdString"];
    if (attachmentIdString == nil) {
        // This value is optional.
    } else if (![attachmentIdString isKindOfClass:[NSString class]] || attachmentIdString.length < 1) {
        OWSFailDebug(@"Invalid upload form: attachmentIdString.");
        return nil;
    }
    
    OWSUploadForm *form = [OWSUploadForm new];
    
    // Required properties.
    form.formAcl = formAcl;
    form.formKey = formKey;
    form.formPolicy = formPolicy;
    form.formAlgorithm = formAlgorithm;
    form.formCredential = formCredential;
    form.formDate = formDate;
    form.formSignature = formSignature;

    // Optional properties.
    form.attachmentId = attachmentId;
    form.attachmentIdString = attachmentIdString;

    return form;
}

- (void)appendToForm:(id<AFMultipartFormData>)formData
{
    // We have to build up the form manually vs. simply passing in a paramaters dict
    // because AWS is sensitive to the order of the form params (at least the "key"
    // field must occur early on).
    //
    // For consistency, all fields are ordered here in a known working order.
    OWSLogInfo(@"form policy is key: %@ , acl: %@, x-amz-algorithm: %@, x-amz-credential: %@,  x-amz-date: %@, : policy: %@ , x-amz-signature: %@, attachment ",self.formKey,self.formAcl,self.formAlgorithm,self.formCredential,self.formDate,self.formPolicy,self.formSignature);
    AppendMultipartFormPath(formData, @"key", self.formKey);
    AppendMultipartFormPath(formData, @"acl", self.formAcl);
    AppendMultipartFormPath(formData, @"x-amz-algorithm", self.formAlgorithm);
    AppendMultipartFormPath(formData, @"x-amz-credential", self.formCredential);
    AppendMultipartFormPath(formData, @"x-amz-date", self.formDate);
    AppendMultipartFormPath(formData, @"policy", self.formPolicy);
    AppendMultipartFormPath(formData, @"x-amz-signature", self.formSignature);
}


================================================
- (AnyPromise *)parseFormAndUpload:(nullable id)formResponseObject
                           urlPath:(NSString *)urlPath
                     progressBlock:(UploadProgressBlock)progressBlock
{
    OWSUploadForm *_Nullable form = [OWSUploadForm parse:formResponseObject];
    if (!form) {
        return [AnyPromise
            promiseWithValue:OWSErrorWithCodeDescription(OWSErrorCodeUploadFailed, @"Invalid upload form.")];
    }
    UInt64 serverId = form.attachmentId.unsignedLongLongValue;
    if (serverId < 1) {
        return [AnyPromise
            promiseWithValue:OWSErrorWithCodeDescription(OWSErrorCodeUploadFailed, @"Invalid upload form.")];
    }

    self.serverId = serverId;

    __weak OWSAttachmentUploadV2 *weakSelf = self;
    AnyPromise *promise = [AnyPromise promiseWithResolverBlock:^(PMKResolver resolve) {
        
        [self.uploadHTTPManager POST:urlPath
            parameters:nil
            constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
                OWSAttachmentUploadV2 *_Nullable strongSelf = weakSelf;
                if (!strongSelf) {
                    return resolve(OWSErrorWithCodeDescription(OWSErrorCodeUploadFailed, @"Upload deallocated"));
                }

                // We have to build up the form manually vs. simply passing in a paramaters dict
                // because AWS is sensitive to the order of the form params (at least the "key"
                // field must occur early on).
                //
                // For consistency, all fields are ordered here in a known working order.
            OWSLogInfo(@"formData is: %@",formData);
                [form appendToForm:formData];
                AppendMultipartFormPath(formData, @"Content-Type", OWSMimeTypeApplicationOctetStream);

                NSData *_Nullable uploadData = [strongSelf attachmentData];
                if (uploadData.length < 1) {
                    OWSCFailDebug(@"Could not load upload data.");
                    return resolve(
                        OWSErrorWithCodeDescription(OWSErrorCodeUploadFailed, @"Could not load upload data."));
                }
                OWSAssertDebug(uploadData.length > 0);
                [formData appendPartWithFormData:uploadData name:@"file"];
            OWSLogInfo(@"uploadData %@",uploadData.description);
                OWSLogVerbose(@"constructed %@ body", [NSByteCountFormatter stringFromByteCount:uploadData.length countStyle:NSByteCountFormatterCountStyleFile]);
            }
            progress:^(NSProgress *progress) {
                OWSLogVerbose(@"Upload progress: %.2f%%", progress.fractionCompleted * 100);

                progressBlock(progress);
            }
            success:^(NSURLSessionDataTask *uploadTask, id _Nullable responseObject) {
                OWSAttachmentUploadV2 *_Nullable strongSelf = weakSelf;
                if (!strongSelf) {
                    return resolve(OWSErrorWithCodeDescription(OWSErrorCodeUploadFailed, @"Upload deallocated"));
                }

                OWSLogInfo(@"Upload succeeded with key: %@ : %@", form.formKey, responseObject);
                return resolve(@(1));
            }
            failure:^(NSURLSessionDataTask *_Nullable uploadTask, NSError *error) {
                OWSLogError(@"Upload failed with error: %@", error);
                resolve(error);
            }];
    }];
    return promise;
}
=============================
Creating Multipartform Data

- (nullable NSData *)attachmentData
{
    OWSAssertDebug(self.attachmentStream);

    NSData *encryptionKey;
    NSData *digest;
    NSError *error;
    NSData *attachmentData = [self.attachmentStream readDataFromFileWithError:&error];
    if (error) {
        OWSLogError(@"Failed to read attachment data with error: %@", error);
        return nil;
    }

    NSData *_Nullable encryptedAttachmentData = [Cryptography encryptAttachmentData:attachmentData
                                                                          shouldPad:YES
                                                                             outKey:&encryptionKey
                                                                          outDigest:&digest];
    if (!encryptedAttachmentData) {
        OWSFailDebug(@"could not encrypt attachment data.");
        return nil;
    }

    self.encryptionKey = encryptionKey;
    self.digest = digest;

    return encryptedAttachmentData;
}

=============================
Header data is

{
    "Accept-Language" = "en-GB;q=1, mr-IN;q=0.9, en-IN;q=0.8, hi-IN;q=0.7, mai-IN;q=0.6";
    "Content-Type" = "application/x-www-form-urlencoded";
    "User-Agent" = "Dosto Howzit/3.6 (iPhone; iOS 13.6; Scale/2.00)";
}

**Comment by Rohan29** [comment]
Please close this issue, Solved

**Comment by harshavardhana** [comment]
> Please close this issue, Solved

Closing as per this comment

**Comment by zatricky** [comment]
@Rohan29 it's helpful to give pointers as to what solved the issue ; others might be facing the same situation with the same root cause.

https://xkcd.com/979/

**Comment by rrdolaner** [comment]
how did you solve the problem. I encountered the same problem

**Comment by baughmann** [comment]
I came here to ask how do you turn lead into gold?

**EDIT:** Nevermind, figured it out.

**Comment by baughmann** [comment]
> Please close this issue, Solved

I came here to ask how do you turn lead into gold?

**EDIT:** Nevermind, figured it out.

**Comment by Rohan29** [comment]
Hello guys, for my case data was not sent in file format, it was sent as parameter in dictionary.

**Comment by Mohamadreza-shad** [comment]
Hello guys, in my case, MinIO API responded with message=400 without body resulted in path with less than two components. Status code=BadRequest, this error message 400, while I was uploding an image(with size 300 kb)
Is there Anybody who can help me?
Thank you in advance

**Comment by rrdolaner** [comment]
Hello, I have experienced the same thing. There was a problem between server and client. This event was happening because the parameters we set were corrupted to the other side. There was a problem especially when setting "boundary". I saw that this is not set when going as "multipart/form data" on Alamofire side. it was giving a "400 Bad Request" message on the MINIO side because the other side was waiting for it. I tried to solve this part without using AF. 

I created a method called "uploadAttachment" in OWSUpload class. Here you can compare the changes I made. I hope it solves your problem.

[OWSUpload.swift](https://gist.github.com/rrdolaner/0300521631797a16f42b6a2de0d8d958)

**Comment by Mohamadreza-shad** [comment]
dear Resul,
thank you in advance for this helpful information.
