### ISSUE TITLE
[resolved] AssumeRoleWithWebIdentity - JWKS endpoint not refreshed

### ISSUE THREAD

**Issue by footplus** [minio/minio#10359]
With recent MinIO versions, it seems that AssumeRoleWithWebIdentity does not recognize JWTs signed with a key not present at the JWKS endpoint when MinIO started (JWKS rotation).

## Expected Behavior
MinIO should perform the AssumeRoleWithWebIdentity correctly when provided with a JWT signed with a key created by the IDP after MinIO startup (as part of key rotation by the IdP).

## Current Behavior

MinIO errors out with:

```
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>key is of invalid type</Message></Error><RequestId>162EC31498921B31</RequestId></ErrorResponse>
```
while the token is correct and is signed with an existing key (at the IdP) with alg RS256.
Just after restarting MinIO, the exact same token is presented and the call correctly succeeds.

## Possible Solution
MinIO should update at least the JWKS key set (and probably the OpenID configuration URL if JWKS endpoint is not specified) from the JWKS endpoint, to discard expired keys and gather new ones.
This could be checked at regular intervals (configurable) and perhaps forcefully checked (w/short negative cache) like in the past when an unknown kid is presented.

## Steps to Reproduce (for bugs)

1. Start MinIO associated with an IdP that does quick key rotation
2. Wait for the key to actually rotate
3. Request an id token from the IdP
4. Submit the id token to MinIO via AssumeRoleWithWebIdentity (this fails)
5. Restart MinIO
6. Submit the same token; the AssumeRoleWithWebIdentity call will succeed.

## Context
MinIO associated with an OpenID IdP (Dex).
I was trying to get AK/SK/ST in a long-running MinIO cluster.
By the way, actual mc support for generating AK/SK/ST from OpenID in the same way that the kubelogin program does could be very interesting.

## Regression
Yes.
Although the implementation did not update the endpoint periodically, JWKS endpoint was actually re-scraped in case token validation failed in the past: https://github.com/minio/minio/commit/abbf6ce6ccf8e99d6e295b9d26483301f0c8139b 

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-08-08T04-50-06Z
* Server setup and configuration: identity_openid config_url=https://my-dex-endpoint.cluster.local/.well-known/openid-configuration client_id=minio.cluster.local claim_name=email claim_prefix= jwks_url= scopes=
* Operating System and version (`uname -a`): CentOS 7.8.2003

**Comment by harshavardhana** [comment]
We changed it to avoid a racy call to rescrape, as JWKS hardly change underneath. 

Let me see we can bring it back with proper protection.

**Comment by footplus** [comment]
Thanks !

What do you mean by "JWKS hardly change underneath" ?

I think the actual endpoint location in the discovery document indeed hardly changes (but still, it's possible), but there are OIDC implementations that automatically rotate JWKs (like Dex that issues a new JWK every 6h in the default configuration: https://github.com/dexidp/dex/blob/master/server/rotation.go).

I agree that is a little excessive, and I can choose a longer duration (3 months, 6 months, etc), but still, the rotation will happen, and this is often out of minio's user's control: you bind MinIO to a SSO to not have to manage the user authentication method at cluster level, and the SSO admin can decide to rotate keys at any point in time.
