### ISSUE TITLE
[not our bug] Hope to support thumbnails

### ISSUE THREAD

**Issue by lurkerw** [minio/minio#10353]
Hope to support dynamic compression of pictures through a suffix,just like Nginx plugin
for example:
https://fond-oss1.oss-us-east-1.aliyuncs.com/test/timg.jpg
https://fond-oss1.oss-us-east-1.aliyuncs.com/test/timg.jpg?x-oss-process=image/resize,h_100
There is only one picture on OSS

**Comment by harshavardhana** [comment]
@lurkerw this is MinIO, not Alibaba Cloud closing the issue.
