### ISSUE TITLE
composeObject合并文件这个api不允许文件小于5m。我如果是18m的文件，分别是，5M,5M,5M,3M,四份，还是会报错

### ISSUE THREAD

**Issue by openwave11** [minio/minio#10379]
## Expected Behavior

如果我上传一个18M文件，分别上传了5M,5M,5M,3M,四份，调用composeObject，api时，期望文件合并成功

## Current Behavior

在第四个部分（3M），时抛出异常，： size 4382720 must be greater than 5242880。

> java sdk，MinioClient.composeObject 2074行

>   if (size < PutObjectOptions.MIN_MULTIPART_SIZE
>           && sources.size() != 1
>           && i != (sources.size() - 1)) {
>         throw new IllegalArgumentException(
>             "source "
>                 + src.bucketName()
>                 + "/"
>                 + src.objectName()
>                 + ": size "
>                 + size
>                 + " must be greater than "
>                 + PutObjectOptions.MIN_MULTIPART_SIZE);
>       }

## Possible Solution

期望取消次限制，由用户自己控制分块文件大小。

## Steps to Reproduce (for bugs)

1.找到一个文件，将文件切割为若干份，最后一份小于5M
2.将所有分块上传到minio
3.通过composeObject合并文件
4.在遍历到最后一个文件时，抛出异常。要求每个part大于5M

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

minio version RELEASE.2020-07-18T18-48-16Z
Linux MA2 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Unfortunately, we do not understand Chinese please open your issue in English preferably 

- Please provide entire java code as a reproducer
- Please provide entire how is MinIO setup? i.e are you using single drive, erasure coded (multi drive) mode?

**Comment by iamyjx** [comment]
VERSION 2020-10-12T21:53:21Z
- The position of exception
- The last part does not check 
- Ensure the parts sorted correct **by part name**
- 兄弟们，我只能帮你们到这里了

![minio](https://user-images.githubusercontent.com/1700739/97947368-089b6b00-1dc8-11eb-8e13-523b9559fe2e.png)

**Comment by minskiter** [comment]
same problem for #13387 already fixed
