### ISSUE TITLE
Provide command via env

### ISSUE THREAD

**Issue by rquadling** [minio/minio#10375]
**Is your feature request related to a problem? Please describe.**
Without a convoluted approach, BitBucket Pipelines does not seem to allow me to set the command when using the pre-made minio/minio container, so I get no output and no service.

**Describe the solution you'd like**
It would be useful to support a new envvar, `MINIO_COMMAND` and the value would be whatever the command would be if I had use the more conventional approach.

**Describe alternatives you've considered**
One option is for me to extend the pre-made container with an override for the command, but then I'm now having to maintain compatibility and upgrades.

**Comment by harshavardhana** [comment]
MINIO_ARGS and MINIO_ENDPOINTS both work already supported.. also not documented on purpose.

**Comment by rquadling** [comment]
Not being able to get this working (feeling really dumb now).

```
$ docker run -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 minio/minio server /data
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

works as expected when supplying the command.

Wanting it to work using MINIO_ARGS and no command line arguments.


```
$ docker run -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 -e MINIO_ARGS='server /data' minio/minio
NAME:
  minio - High Performance Object Storage

DESCRIPTION:
  Build high performance data infrastructure for machine learning, analytics and application data workloads with MinIO

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   start object storage server
  gateway  start object storage gateway
  
FLAGS:
  --certs-dir value, -S value  path to certs directory (default: "/root/.minio/certs")
  --quiet                      disable startup information
  --anonymous                  hide sensitive information from logging
  --json                       output server logs and startup information in json format
  --help, -h                   show help
  --version, -v                print the version
  
VERSION:
  RELEASE.2020-09-02T18-19-50Z
```

```
$ docker run -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 -e MINIO_ARGS=server -e MINIO_ARGS=/data minio/minio
$ docker run -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 -e MINIO_ARGS="server /data" minio/minio
```
All give the same output.

**Comment by harshavardhana** [comment]
*gosh* it's just 


> $ docker run -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 -e MINIO_ARGS=/data minio/minio server

**Comment by rquadling** [comment]
And you've demonstrated the problem in that I still have to pass the `server` parameter.

The environment I'm having to use only allows variables to be passed, not the command, just like I said in the original question.
