### ISSUE TITLE
[not our bug] Missing Environment Variables When Running Minio in Docker in Synology UI?

### ISSUE THREAD

**Issue by BlackSwiftSoftware** [minio/minio#10377]
I suspect that this is a problem of documentation, and I fully admit I'm a bit out of my depth here. That said, I had a lot difficulty getting Minio setup and it was because of this issue. When setting up Minio from Docker Hub in Synology NAS, Minio shows two environment variables -- MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE. Minio does not show MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables. The documentation on the Docker Hub page does not explain the difference between the two.

## Expected Behavior
I expected to see MINIO_ACCESS_KEY and MINIO_SECRET_KEY as default environment variables. Not realizing there was a difference, I was trying to enter my keys as strings into these environmental variables and couldn't understand why they weren't getting set.

## Current Behavior
The GUI for Docker on Synology NAS shows environmental variables for MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE.

## Possible Solution
Removing '_FILE' from the end of MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE allows you to enter an access key and secret key as a text string. Could Minio configure Docker to default to having environment variables MINIO_ACCESS_KEY and MINIO_SECRET_KEY in addition to MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE? Would this not allow users to chose whether they wish to provide their keys as strings or store the keys in files? I further suggest language on the Docker Hub page for Minio that explains the difference in these environmental variables.

## Context
Not being the brightest of fellows, I probably spent an hour trying to understand why Minio wasn't getting configured with my keys. I noted the difference in MINIO_ACCESS_KEY_FILE vs. MINIO_ACCESS_KEY but assumed that since the default environmental variables given to me had '_FILE' at the end, that these were the environmental variables I should be using. In other words, I thought that I needed to set the access key and secret key by giving string values to MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE.

## Regression
No.

## Your Environment
Synology NAS running Docker and Minio version 2020-08-13T02:39:50Z.
Host: minio | OS: linux | Arch: amd64
Runtime: Version: go1.14.7 | CPUs: 2

**Comment by harshavardhana** [comment]
> I suspect that this is a problem of documentation, and I fully admit I'm a bit out of my depth here. That said, I had a lot difficulty getting Minio setup and it was because of this issue. When setting up Minio from Docker Hub in Synology NAS, Minio shows two environment variables -- MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE. Minio does not show MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables. The documentation on the Docker Hub page does not explain the difference between the two.

This is a Synology NAS configuration issue we do not maintain this on our end. You can configure all documented environment variables if not this is a bug in Synology and we can't do much.

> I expected to see MINIO_ACCESS_KEY and MINIO_SECRET_KEY as default environment variables. Not realizing there was a difference, I was trying to enter my keys as strings into these environmental variables and couldn't understand why they weren't getting set.

There is not default ENV you just set them as you want. Synology packaging perhaps lacks all of this. 

> The GUI for Docker on Synology NAS shows environmental variables for MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE.

Cannot help you here unfortunately, we do not maintain the Synology NAS package.

**Comment by harshavardhana** [comment]
> Removing '_FILE' from the end of MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE allows you to enter an access key and secret key as a text string. Could Minio configure Docker to default to having environment variables MINIO_ACCESS_KEY and MINIO_SECRET_KEY in addition to MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE? Would this not allow users to chose whether they wish to provide their keys as strings or store the keys in files? I further suggest language on the Docker Hub page for Minio that explains the difference in these environmental variables.

All of it is documented here https://docs.minio.io/docs/minio-docker-quickstart-guide.html

**Comment by BlackSwiftSoftware** [comment]
@harshavardhana, I write with trepidation, realizing I may be hopelessly clueless... But are the default environmental variables not set by the Dockerfile, which is created by Minio?

Here's a relevant section of the Dockerfile, from:
https://github.com/minio/minio/blob/master/Dockerfile

`ENV MINIO_UPDATE off`
`ENV MINIO_ACCESS_KEY_FILE=access_key \`
`    MINIO_SECRET_KEY_FILE=secret_key \`
`    MINIO_KMS_MASTER_KEY_FILE=kms_master_key \`
`    MINIO_SSE_MASTER_KEY_FILE=sse_master_key`

Am I wrong in understanding that _IF_ MINIO_ACCESS_KEY_ and MINIO_SECRET_KEY were also set as environment variables, they would appear as options? In words, I was under the strong impression that Synology is not setting up it's own default variables. It's pulling them from the Dockerfile.

If I am mistaken, my apologies for the report and a thousand thank you's for the great product.

**Comment by harshavardhana** [comment]
> Am I wrong in understanding that _IF_ MINIO_ACCESS_KEY_ and MINIO_SECRET_KEY were also set as environment variables, they would appear as options? In words, I was under the strong impression that Synology is not setting up it's own default variables. It's pulling them from the Dockerfile.

No, it is not pulling from Dockerfile we do not set anything as default in Dockerfile - you need to set something required through ENV as necessary based on the ENVs, if none is set we just default within MinIO to `minioadmin:minioadmin` (accessKey:secretKey) respectively. 

_FILE envs are meant to read from docker secrets or kubernetes secrets.

**Comment by BlackSwiftSoftware** [comment]
I fear that I'm not doing a good job explaining myself. I am NOT asking for MinIO to _set_ anything. Yes, I understand that when no ENV variables are given, MinIO defaults to `minioadmin:minioadmin` for the keys. 

What I'm trying to ask is why MinIO includes the _FILE ENV variables in the Dockerfile but not MINIO_ACCESS_KEY and MINIO_SECRET_KEY. Unless I'm missing something (entirely possible!), if you had the following in the Dockerfile:

`MINIO_ACCESS_KEY=your_access_key`
`MINIO_SECRET_KEY=your_secret_key`

or perhaps 

`MINIO_ACCESS_KEY=minioadmin`
`MINIO_SECRET_KEY=minioadmin`

Would that not make it much clearer and easier for users that wish to set strings for the keys rather than use files? Would that not also show people what the key values would be if they leave the default values? (I had already read the documentation that you linked before posting here, but there isn't any mention that the default values are `minioadmin`, so I had to discover this by looking at the logs.)

As it is now, users have to learn that they should _not_ use the _FILE ENV variables if they wish to provide keys as strings. I thought it would be much clearer if the existence of the other ENV variables was shown. It would help guide users to more quickly and easily set up MinIO.

Thank you for talking to me. I am not trying to be argumentative and will not reply again unless you'd like me to clarify something. Thanks again for the great software. Cheers.

**Comment by harshavardhana** [comment]
> I fear that I'm not doing a good job explaining myself. I am NOT asking for MinIO to _set_ anything. Yes, I understand that when no ENV variables are given, MinIO defaults to `minioadmin:minioadmin` for the keys.
> 
> What I'm trying to ask is why MinIO includes the _FILE ENV variables in the Dockerfile but not MINIO_ACCESS_KEY and MINIO_SECRET_KEY. Unless I'm missing something (entirely possible!), if you had the following in the Dockerfile:
> 
> `MINIO_ACCESS_KEY=your_access_key`
> `MINIO_SECRET_KEY=your_secret_key`
> 
> or perhaps
> 
> `MINIO_ACCESS_KEY=minioadmin`
> `MINIO_SECRET_KEY=minioadmin`
> 
> Would that not make it much clearer and easier for users that wish to set strings for the keys rather than use files? Would that not also show people what the key values would be if they leave the default values? (I had already read the documentation that you linked before posting here, but there isn't any mention that the default values are `minioadmin`, so I had to discover this by looking at the logs.)
> 
> As it is now, users have to learn that they should _not_ use the _FILE ENV variables if they wish to provide keys as strings. I thought it would be much clearer if the existence of the other ENV variables was shown. It would help guide users to more quickly and easily set up MinIO.
> 
> Thank you for talking to me. I am not trying to be argumentative and will not reply again unless you'd like me to clarify something. Thanks again for the great software. Cheers.

We don't because that doesn't make sense since those are real values and we cannot set them automatically. Env credentials are used for encrypting the backend which can have consequences if you don't know which credentials we used to encrypt the content.


We include _FILE because it is anticipation you have docker secrets present and you want to attach them. If the files are present it is assumed that you intention was for us to read credentials from here.
