### ISSUE TITLE
Helm Chart with extraContainers support for logging

### ISSUE THREAD

**Issue by christophemorio** [minio/minio#10387]
**Is your feature request related to a problem? Please describe.**
In Kubernetes setup, MinIO server logging goes through another container (mc admin trace) within pod. Which is currently not possible using the Helm Chart.

**Describe the solution you'd like**
A common helm chart pattern is `extraContainers` parameter to allow one or more arbitrary containers.

**Describe alternatives you've considered**
Another independent deployment does not perfect fit,
if MinIO server replica > 1, it's hard to track all pods.

**Additional context**
I will propose a PR.

**Comment by harshavardhana** [comment]
> **Is your feature request related to a problem? Please describe.**
> In Kubernetes setup, MinIO server logging goes through another container (mc admin trace) within pod. Which is currently not possible using the Helm Chart.
> 
> **Describe the solution you'd like**
> A common helm chart pattern is `extraContainers` parameter to allow one or more arbitrary containers.
> 
> **Describe alternatives you've considered**
> Another independent deployment does not perfect fit,
> if MinIO server replica > 1, it's hard to track all pods.
> 
> **Additional context**
> I will propose a PR.

mc admin trace is not replacement for logging, it is meant for debugging purposes - you can configure logging as regular logging and audit targets

https://github.com/minio/minio/tree/master/docs/logging
