### ISSUE TITLE
Configure the timestamp of mc admin trace logging

### ISSUE THREAD

**Issue by tharunShiv** [minio/minio#10380]
We have set up the logging using the command
`mc admin trace local > /var/log/minio/minio-access.log`

The issue we're facing is, the time stamp that shows up in the logs in real-time is not the same as our time zone. 
Say, if the current time is 11:40 IST
The logs show 06:09:05.003 as the recent logs

## Expected Behavior
So if the current time is 11:41, the recent logs should show at the current timezone timestamp, that is , 11:41:00.000

## Current Behavior
Currently it shows a different time.

## Possible Solution
Is there any way to configure the timestamp of logging? A possibility where we can choose the fields we want, along with date and time, where we also get to mention the timestamp?
Or, the minio can also use the local date and time from the machine.

## Steps to Reproduce (for bugs)
`mc admin trace local > /var/log/minio/minio-access.log` and please check the logs in real time. 

## Context
Trying to set up access logs

## versions
minio server: 2020-02-27T00:23:05Z
minio client: RELEASE.2020-02-25T18-10-03Z

Thank you

**Comment by harshavardhana** [comment]
What we show as `mc admin trace` is UTC @tharunShiv to avoid issues while debugging as we all are in different time zones.

**Comment by harshavardhana** [comment]
> `mc admin trace local > /var/log/minio/minio-access.log` and please check the logs in real time.

You shouldn't use `mc admin trace` as a way to get logs from server, you should configure Audit targets if that is what you want for access logging. 

`mc admin trace` is meant for debugging purposes only.

**Comment by tharunShiv** [comment]
Hi, 
   Okay, I went through the documentation multiple times, but I'm not able to find out the right way to set up access logs, can you please point me to it? What is that audit target?

**Comment by klauspost** [comment]
See https://docs.min.io/docs/minio-bucket-notification-guide.html 

You can also join the community slack where others may be able to help you: https://slack.min.io/

**Comment by tharunShiv** [comment]
Thank you, I'm already a part of the MinIO slack community for months now
