### ISSUE TITLE
[resolved] no event from Minio using HTTP DELETE 

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#10381]
I'm using s3fs to mount a bucket on linux, removing a file from the bucket Minio doesn't send the event to web hook.

## Expected Behavior

Minio send s3:ObjectRemoved:Delete to webhook.

## Current Behavior

No event

## Steps to Reproduce (for bugs)
$ mc admin config get local notify_webhook
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
notify_webhook:local endpoint=http://localhost:2080/ auth_token= queue_limit=0 queue_dir=/var/tmp/local client_cert= client_key= comment="Minio Webhook"

$ mc event list local/francesco
arn:minio:sqs::local:webhook   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter:

the index.php file that logs everything:

```
<?php

$debug=1;
openlog("minio-webhook", LOG_PID | LOG_PERROR, LOG_LOCAL0);

if ($_SERVER['REQUEST_METHOD'] == 'POST' ) {
  $json = file_get_contents('php://input');
  $obj = json_decode($json,true);
  if ($debug) {
    syslog ( LOG_DEBUG , $json );
  }

} else {
  syslog(LOG_WARNING, "client sent a get request: {$_SERVER['REMOTE_ADDR']} ({$_SERVER['HTTP_USER_AGENT']})");
}
?>
```

$ tail -1 /etc/fstab
s3fs#francesco /home/francesco/s3 fuse _netdev,allow_other,mp_umask=0022,use_path_request_style,enable_content_md5,nomultipart,curldbg,url=https://FQDN/ 0 0

$ ls -l /home/francesco/s3/test_versions.txt
-rw-r--r-- 1 root root 4377 ago 31 10:04 test_versions.txt

$ tail -1 /var/log/minio-webhook.log
Aug 31 10:04:46 ap42 minio-webhook[1635]: {"EventName":"s3:ObjectAccessed:Head","Key":"francesco/test_versions.txt"....

$ rm -f /home/francesco/s3/francesco/test_versions.txt

Debug from s3fs:
<pre>
Aug 31 10:05:51 ap42 s3fs[32406]: > DELETE /francesco/test_versions.txt HTTP/1.1
Aug 31 10:05:51 ap42 s3fs[32406]: > host: FQDN
Aug 31 10:05:51 ap42 s3fs[32406]: > User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
Aug 31 10:05:51 ap42 s3fs[32406]: > Accept: */*
Aug 31 10:05:51 ap42 s3fs[32406]: > Authorization: AWS4-HMAC-SHA256 Credential=admin/20200831/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7a3851307b960219bba194d8faf0863148d619ba481f0c7e461bcc454dfb9245
Aug 31 10:05:51 ap42 s3fs[32406]: > x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Aug 31 10:05:51 ap42 s3fs[32406]: > x-amz-date: 20200831T080551Z
Aug 31 10:05:51 ap42 s3fs[32406]: >
Aug 31 10:05:51 ap42 s3fs[32406]: < HTTP/1.1 204 No Content
Aug 31 10:05:51 ap42 s3fs[32406]: < Accept-Ranges: bytes
Aug 31 10:05:51 ap42 s3fs[32406]: < Content-Security-Policy: block-all-mixed-content
Aug 31 10:05:51 ap42 s3fs[32406]: < Server: MinIO/RELEASE.2020-08-27T05-16-20Z
Aug 31 10:05:51 ap42 s3fs[32406]: < Vary: Origin
Aug 31 10:05:51 ap42 s3fs[32406]: < X-Amz-Request-Id: 16304BBF0FD39E9F
Aug 31 10:05:51 ap42 s3fs[32406]: < X-Xss-Protection: 1; mode=block
Aug 31 10:05:51 ap42 s3fs[32406]: < x-amz-delete-marker: true
Aug 31 10:05:51 ap42 s3fs[32406]: < x-amz-version-id: ee900370-f577-4eca-9a01-89f312a98d31
Aug 31 10:05:51 ap42 s3fs[32406]: < Date: Mon, 31 Aug 2020 08:05:51 GMT
Aug 31 10:05:51 ap42 s3fs[32406]: <
Aug 31 10:05:51 ap42 s3fs[32406]: * Connection #0 to host FQDN left intact
</pre>

No event from minio:

tail -1 /var/log/minio-webhook.log Aug 31 10:04:31 ap42 minio-webhook[1635]: {"EventName":"s3:ObjectAccessed:Head","Key":"francesco/test_versions.txt","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2....

## Your Environment
$ minio -v
minio version RELEASE.2020-08-27T05-16-20Z
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

s3fs           1.82-1       amd64        FUSE-based file system backed by Amazon S3

**Comment by harshavardhana** [comment]
Looks like a regression
