### ISSUE TITLE
[working as intended] MinIO Server on Windows 10 with AWS S3 SDK .NET ListObjectVersions not implemented

### ISSUE THREAD

**Issue by iboware** [minio/minio#10388]
## Expected Behavior
If we use Minio Server on Linux following code block works without any problem. 
```csharp
 var request = new ListObjectsV2Request
            {
                Prefix = folder,
                BucketName = bucket
            };

ListObjectsV2Response response = await _client.ListObjectsV2Async(request);
```

It used to work with SDK:
```csharp
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.100.1" />
        <PackageReference Include="AWSSDK.S3" Version="3.3.104.36" />
```

It does not work with SDK:
```csharp
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" />
        <PackageReference Include="AWSSDK.S3" Version="3.5.0.5" />
```

## Current Behavior
Some developers uses Windows development env. that is why they use the Windows version of Minio Server, and when they call this block of code above, we get following output from minio client trace:
```bash
localhost [REQUEST s3.ListObjectVersions] 15:50:40.211
localhost GET /tenant31?versions
localhost Proto: HTTP/1.1
localhost Host: localhost:9005
localhost
 Authorization: AWS4-HMAC-SHA256 
Credential=storage-access-key/20200826/us-east-1/s3/aws4_request, 
SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, 
Signature=7456f0f795f974f62ed9fcfb5486510f9e02de79b61eb80df726572c529f5572
localhost Content-Length: 0
localhost Request-Id: |8dc912b4-46688b3e24c6147e.10.
localhost
 User-Agent: aws-sdk-dotnet-coreclr/3.3.112.0 
aws-sdk-dotnet-core/3.3.107.37 .NET_Core/3.1.6 
OS/Microsoft_Windows_10.0.19041 ClientAsync
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200826T155040Z
localhost
localhost [RESPONSE] [15:50:40.211] [ Duration 1.012ms  ↑ 88 B  ↓ 585 B ]
localhost 501 Not Implemented
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 322
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-08-26T00-00-49Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 162EDC35867256A0
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A
 header you provided implies functionality that is not 
implemented</Message><BucketName>tenant31</BucketName><Resource>/tenant31</Resource><RequestId>162EDC35867256A0</RequestId><HostId>cc0e106d-fc48-428f-bfea-ab38fbcc5d17</HostId></Error>
```
## Context
Everything works on production and testing but local development environments running on Windows broken because of this

## Your Environment

* Version used (`minio --version`): RELEASE.2020-08-27T05-1620Z
* Server setup and configuration: minio.exe server path-to-data-folder
* Operating System and version (`uname -a`): Windows 10 (Operating System MinIO Server running on)

**Comment by harshavardhana** [comment]
Single drive setups do not support Versioning as mentioned in the documentation, use erasure coding or distributed erasure coding   for versioning support. 

https://docs.minio.io/docs/minio-bucket-versioning-guide.html

> Versioning feature is only available in erasure coded and distributed erasure coded setups.

**Comment by iboware** [comment]
Thank you for your quick reply @harshavardhana . Is there a way to enable it without Minio SDK? Because we are using AWS S3 SDK for .NET Core. Is it possible to activate it with an environmental variable or configuration on Minio Server?

**Comment by harshavardhana** [comment]
> Thank you for your quick reply @harshavardhana . Is there a way to enable it without Minio SDK? Because we are using AWS S3 SDK for .NET Core. Is it possible to activate it with an environmental variable or configuration on Minio Server?

It's not about SDK its server feature @iboware `minio.exe server tmp{1...4}`  will get you versioning running locally.

**Comment by iboware** [comment]
@harshavardhana  That solved the problem! Thank you!  I have one last question: Would starting minio server with `minio.exe server tmp{1...4}` destroy any existing data in the folder tmp? Because we used to start it with `minio.exe server tmp` are there any special procedure that I have to follow to protect those data?

**Comment by harshavardhana** [comment]
> @harshavardhana That solved the problem! Thank you! I have one last question: Would starting minio server with `minio.exe server tmp{1...4}` destroy any existing data in the folder tmp? Because we used to start it with `minio.exe server tmp` are there any special procedure that I have to follow to protect those data?

@iboware that is just a local directory - `tmp` is just an example you can choose whatever you want.

**Comment by iboware** [comment]
@harshavardhana yes, I understand that but if I have an existing directory before using {1...4} Erasure Code, because it creates 4 copy of it, would that destroy any data in that existing folder and what should I do to prevent it, after running the server with {1...4} erasure code. That is my question.

**Comment by harshavardhana** [comment]
> @harshavardhana yes, I understand that but if I have an existing directory before using {1...4} Erasure Code, because it creates 4 copy of it, would that destroy any data in that existing folder and what should I do to prevent it, after running the server with {1...4} erasure code. That is my question.

Don't delete it that's all, use the same protections that you use to protect other folders on your OS. MinIO cannot save you from deleting backend folders.
