### ISSUE TITLE
[resolved] bucket inconsistent among distributed minio disks 

### ISSUE THREAD

**Issue by yangwwii** [minio/minio#10393]
On distributed MinIO deployed as a statefulset on kubernetes cluster, it's observed that the bucket list are different among the disks. there are 4 disks in total. the bucket list on disk in pod 0 is different from others.

Pods are all in running state and no pod restarts.

## Expected Behavior
It's expected that the bucket/object on all disks are all the same.

## Current Behavior
the bucket list are inconsistent between the disk on pod 0 and the other disks.

## Steps to Reproduce (for bugs)
We get this issue reproduced on RELEASE.2020-02-27T00-23-05Z, but it's not 100% reproduced.
We have another controller pod as minio client for creating buckets, installed together with minio via 'helm install'. these buckets are created during runtime but quite early on when the controller pod gets started and they are populated as needed.

**Comment by yangwwii** [comment]
Could I know why Minio don't make a sync with the other disks once it gets started to make the data consistent with the other disks.

**Comment by harshavardhana** [comment]
> Could I know why Minio don't make a sync with the other disks once it gets started to make the data consistent with the other disks.

You need to upgrade such that you can enjoy the new features like auto-healing etc, 

> We get this issue reproduced on RELEASE.2020-02-27T00-23-05Z, but it's not 100% reproduced.

This is an old release please upgrade.

**Comment by yangwwii** [comment]
Hi, @harshavardhana  thanks for your info. which version did the fix of 'auto healing' in?
what's the behaviors with auto-healing supported? does it support bucket/object sync once pods starts, or healing in period?

**Comment by harshavardhana** [comment]
> Hi, @harshavardhana  thanks for your info. which version did the fix of 'auto healing' in?
> what's the behaviors with auto-healing supported? does it support bucket/object sync once pods starts, or healing in period?

All latest releases, it supports auto heal all the time. There is no time interval it happens automatically upon when free cycles are available.

- auto heal of all buckets and objects
- disk replacement heal 
- healing if objects if they have corruption is all part of this

**Comment by yangwwii** [comment]
That sounds great! so we won't do healing manually. I will try the latest MinIO, thanks for your support @harshavardhana
