### ISSUE TITLE
[not our bug] Minio Azure Proxy throws error when deleting

### ISSUE THREAD

**Issue by martenlindblad** [minio/minio#10405]
## Expected Behavior
The DELETE call to Azure Blob Storage should work without throwing errors

## Current Behavior
The delete call `API: DeleteMultipleObjects(bucket=xxx)` throws an error:
```
API: DeleteMultipleObjects(bucket=dro)
Time: 13:07:23 UTC 09/02/2020
DeploymentID: d23bfe1b-f3d6-4421-892b-a7902e3c4643
RequestID: 1630F950E5394E84
RemoteHost: 172.17.0.1
Host: 127.0.0.1:9000
UserAgent: Hadoop 3.1.0, aws-sdk-java/1.11.754 Mac_OS_X/10.13.6 OpenJDK_64-Bit_Server_VM/25.242-b08 java/1.8.0_242 scala/2.11.12 groovy/2.4.11 vendor/AdoptOpenJDK
Error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=InternalError) =====
Description=Server encountered an internal error. Please try again after some time.
RequestId:52d8dd8d-001e-0099-0229-819ac5000000
Time:2020-09-02T13:07:23.8550678Z, Details: 
   Code: InternalError
   DELETE https://xxx.blob.core.windows.net/xxx/2020-09-02--15/?timeout=61
   Authorization: REDACTED
   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-08-27T05:16:20Z]
   X-Ms-Client-Request-Id: [fa2a6276-c33e-48b2-6ec7-06a271781885]
   X-Ms-Date: [Wed, 02 Sep 2020 13:07:23 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 500 Server encountered an internal error. Please try again after some time.
   Content-Length: [253]
   Content-Type: [application/xml]
   Date: [Wed, 02 Sep 2020 13:07:23 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InternalError]
   X-Ms-Request-Id: [52d8dd8d-001e-0099-0229-819ac5000000]
   X-Ms-Version: [2018-11-09]



       4: cmd/api-errors.go:1961:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:1986:cmd.toAPIError()
       2: cmd/bucket-handlers.go:458:cmd.objectAPIHandlers.DeleteMultipleObjectsHandler()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)
1. Start the proxy:
```
docker run -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=xxx" \
 -e "MINIO_SECRET_KEY=xxx" \
 -e "MINIO_AZURE_CHUNK_SIZE_MB=0.25" \
 minio/minio gateway azure
```
2. Run an Apache Flink job (version 1.11.1) with a StreamingFileSink that points to the MinIO endpoint.
When Flink tries to checkpoint the data, MinIO throws an error and after a few retries the Flink job aborts.
```
        StreamingFileSink<T> fileSink = StreamingFileSink
                .forBulkFormat(new Path("s3://bucket/"), ParquetAvroWriters.forReflectRecord(clazz))
                .build();
```

## Context
We are trying to move our data warehousing to Azure Synapse that reads parquet data in an Azure Blob Storage.
Apache Flink does not support Azure Blob Storage as a file system for StreamingFileSink. Flink supports S3 however. We wanted to try to use MinIO as a proxy for the data.

## Regression
No

## Your Environment
* Version used (`minio --version`): 2020-08-27T05:16:20Z
* Server setup and configuration: Docker on Mac
* Operating System and version (`uname -a`): Darwin XXX 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
> ===== RESPONSE ERROR (ServiceCode=InternalError) =====
> Description=Server encountered an internal error. Please try again after some time.
> RequestId:52d8dd8d-001e-0099-0229-819ac5000000
> Time:2020-09-02T13:07:23.8550678Z, Details: 
>    Code: InternalError
>    DELETE https://xxx.blob.core.windows.net/xxx/2020-09-02--15/?timeout=61
>    Authorization: REDACTED
>    User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-08-27T05:16:20Z]
>    X-Ms-Client-Request-Id: [fa2a6276-c33e-48b2-6ec7-06a271781885]
>    X-Ms-Date: [Wed, 02 Sep 2020 13:07:23 GMT]
>    X-Ms-Version: [2018-11-09]
>    --------------------------------------------------------------------------------
>    RESPONSE Status: 500 Server encountered an internal error. Please try again after some time.
>    Content-Length: [253]
>    Content-Type: [application/xml]
>    Date: [Wed, 02 Sep 2020 13:07:23 GMT]
>    Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
>    X-Ms-Error-Code: [InternalError]
>    X-Ms-Request-Id: [52d8dd8d-001e-0099-0229-819ac5000000]
>    X-Ms-Version: [2018-11-09]

The error returned by the backend here, can't do much on our end. Just retry the operation, we rely on the SDK to retry.

**Comment by martenlindblad** [comment]
I've tried it under repeated conditions. We are using [hierarchical namespace](https://docs.microsoft.com/sv-se/azure/storage/blobs/data-lake-storage-namespace). Maybe that uses separate API calls for handling objects?

**Comment by martenlindblad** [comment]
I can confirm that the proxy works using regular Azure Blob Storage _without_ enabeling **hierarchical namespace**. I will create a feature request to support hierarchical namespace.
