### ISSUE TITLE
[not our bug] /root/.minio/certs: read-only file system

### ISSUE THREAD

**Issue by liwh1111** [minio/minio#10415]
![image](https://user-images.githubusercontent.com/63097736/92196845-c5457e80-eea2-11ea-8f9f-004f480d3e26.png)

Have you encountered this problem and how to solve it

**Comment by harshavardhana** [comment]
because you have mounted a directory that cannot be written to @liwh1111 please follow the best practices of creating k8s secrets.

Please use issue template to describe your issue properly, otherwise cannot help you.
