### ISSUE TITLE
MinIO nodes (in distributed mode) fail to initialize and restart forever, with cluster marked as healthy

### ISSUE THREAD

**Issue by adferrand** [minio/minio#10418]
## Context

I an running a MinIO cluster on Kubernetes, running in distributed mode with 4 nodes. Sometimes one of the node randomly starts to fail to initialize, and will stay like this until the whole cluster (all MinIO nodes in it) is restarted.

Typical stdout is:
```
 You are running an older version of MinIO released 2 weeks ago 
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes 


Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
(same message repeating forever ...)
```

During this situation, read/write operations are extremely slow (10 or 100 times than usual), and S3 clients will receive randomly `Server not initialized, please try again`, depending on if the actual node handling the request is the faulty node, since in the context of a Kubernetes service, requests are load balanced on "healthy" nodes. 

Finally, the endpoint `/minio/health/live` and `/minio/health/ready` are both continuing to return HTTP 200, preventing the Kubernetes cluster to isolate the faulty node.

## Expected Behavior

* The MinIO cluster is able to self-heal, so eventually the faulty node synchronize again and rejoin the cluster.
* Read/Write operations are not affected significantly, since with 3 nodes online, the cluster can still sustain all operations on a typical N/2 redundancy
* Health probes are returning an error until the synchronization is done, in order to avoid making requests on nodes that are not initialized.

## Current Behavior

* The cluster never self heal, and a manual entire restart of the cluster is needed to fix temporarily the issue
* Operations are really slow
* Health probes always return HTTP 200 status code during the incident

## Possible Solution

I understand that my bug report is quite dramatic while providing very few valuable information of the inner behavior.

I am more than ready to provide any effort to publish more helpful information if some MinIO experts explains me how to troubleshoot the cluster.

## Steps to Reproduce (for bugs)

Really sadly, the error will occur completely randomly. I will apply any advice to troubleshoot the issue on my cluster the next time I observe this behavior.

## Regression

I don't think it is a regression. I failed to find a equivalent issue in my search. The closest issues I could find were also about a node displaying `Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock`, but the message was followed each time by a reason in parenthesis explaining clearly what was the problem.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-08-18T19-41-00Z
* Server setup and configuration:
** Configured in distributed mode, deployed on a Kubernetes cluster using a HelmChart
** The 4 MinIO nodes run in pods orchestrated using a StatefulSet, with each pod attached to a persistent volume mounted on the `/data` path.
** Each node is started with the command: `http://minio-{0...3}.minio.minio-namespace.svc.cluster.local/data`, where `minio-X` is the name of each pod of the statefulset, `minio` is the name of the Kubernetes service, and `minio-namespace` is the namespace where the MinIO cluster is deployed
* Operating System and version (`uname -a`): Not directly accessible since it is a managed Kubernetes cluster. It runs on Kubernetes 1.18.6 however.

I will be really grateful if you can help me on that problem ! Thanks in advance.

**Comment by harshavardhana** [comment]
This can only happen if you didn't create the headless service properly and we cannot resolve the DNS @adferrand NOTE: we also need to make sure quorum number of servers are available. 

Taking down 2 nodes and restarting a 3 node won't make it come back into the cluster since we need write quorum number of servers i.e 3 in case of 4 pods. 

> I an running a MinIO cluster on Kubernetes, running in distributed mode with 4 nodes. Sometimes one of the node randomly starts to fail to initialize, and will stay like this until the whole cluster (all MinIO nodes in it) is restarted.

You need to figure out why do they randomly fail. MinIO server should never restart on its own unnecessarily, check if your liveness probes are properly configured and not set to values like `1 second`  set it to `10 seconds` atleast.

**Comment by adferrand** [comment]
Hello @harshavardhana, thanks a lot for your response.

In term of probe configuration, I use the default values on timeout as provided in the official chart (1 second for liveness, 6 seconds for readiness). Anyway I do not think there is a problem with the liveness probes configuration, because I do not see any event related to a liveness probe failure in the cluster: they always return HTTP 200 all the time, while I noticed that on the faulty node, the HTTP responses also contain a header `X-Minio-Server-Status` set to `safemode`.

So I believe this is the MinIO process itself that is exiting. I saw once some errors about MinIO reaching timeout moving out of `safemode`, but I do not know what it means and need to find a way to retrieve this log since it happens very rarely when the desynchronization occurs (like each two hours).

The headless service is created properly, because at first start (and complete rollout), the cluster is able to boot correctly. On faulty nodes, I also checked with nslookup that the FQDN are resolvable (`{statefulset_name}-{replica_number}.{headless_service_name}.{namespace}.svc.cluster.local`), and they are. Note that I usually does the check several time after the synchronization error starts to occur.

My hypothesis is the following. Randomly I see in the Kubernetes cluster a LeaderElection on the Kubernetes manager controller. I think that at this time (few seconds), all endpoints on the cluster are not accessible anymore, including FQDN from headless services. How the MinIO cluster would react if simultaneously all nodes can not see their siblings anymore ?

**Comment by adferrand** [comment]
As a side note, I will be able to retrieve a lot more logs when the next failure will happen, because I developped a controller in my cluster that will detect this failure in a matter of seconds, take several debugging data at this time, then rollout restart the MinIO cluster.

**Comment by harshavardhana** [comment]
> In term of probe configuration, I use the default values on timeout as provided in the official chart (1 second for liveness, 6 seconds for readiness). Anyway I do not think there is a problem with the liveness probes configuration, because I do not see any event related to a liveness probe failure in the cluster: they always return HTTP 200 all the time, while I noticed that on the faulty node, the HTTP responses also contain a header `X-Minio-Server-Status` set to `safemode`.

I think choosing liveness to 1sec is too low, ideally it should be like 5secs atleast @adferrand 

> So I believe this is the MinIO process itself that is exiting. I saw once some errors about MinIO reaching timeout moving out of `safemode`, but I do not know what it means and need to find a way to retrieve this log since it happens very rarely when the desynchronization occurs (like each two hours).

There is no way it will exit on its own unless you have some form of memory limit on the container and cgroup simply kills the process. There has to restart events triggered so observing `kubectl get events` is better to know what is going on.

**Comment by adferrand** [comment]
Thanks for the tip about increasing the liveness probe timeout to more than 1 seconds, it will increase in the absolute the resiliency of the cluster, in particular under heavy loads.

For the problem I describe in this issue however, I do not get any events about liveness probe failing. By the way the pods holding the MinIO nodes are basically idle during the incident.

Looking at the code of MinIO, I do think that MinIO can exit on its own. At high level I think it is happening this:

The MinIO node tries to initialize the safe mode. Inside the `initSafeMode`, I can see the loop waiting for a lock to be acquired:
https://github.com/minio/minio/blob/a694ba93d9f8151fb7bc22ad189431c3e71e4984/cmd/server-main.go#L247-L253

It corresponds to the lines I see in the MinIO pod:
```
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
```

Eventually in my situation we exceed the deadline retry mechanism, and hit this which makes `initSafeMode` return an error:
https://github.com/minio/minio/blob/a694ba93d9f8151fb7bc22ad189431c3e71e4984/cmd/server-main.go#L293-L296

Which make this line in the caller `serverMain` fail the entire process, display the output I saw about "safe-mode", and return exitcode 1.
https://github.com/minio/minio/blob/a694ba93d9f8151fb7bc22ad189431c3e71e4984/cmd/server-main.go#L523

Now this could explain that an infinite restart loop of the faulty MinIO pod is possible and so can happen in my situation. However I do not understand which bad thing could happen during the lock acquire and why this node never succeed in acquiring it. Also I do not understand why from the healthy cluster, one of the node could fall into these infinite restart loop in the first place.

**Comment by harshavardhana** [comment]
Yes but this is a startup situation, why would MinIO would be in startup situation automatically after a successful up status.

There is no good reason why would server again go into a startup mode, unless it is restarted on a regular basis either externally or something related to k8s.

We have many deployments with k8s so I don't see issue being reported at all, so I wonder if there is something that is different in your environment which keeps restarting MinIO perhaps 

- a really low limit for RAM for the container
- some form of network issues

Note you can get more information if you set MINIO_DSYNC_TRACE=1 as env and see what it is printing.

Also please upgrade to latest release and test this again

**Comment by simonrey1** [comment]
I am having the same problem @adferrand.
I am using Azure Kubernetes Infrastructure.

**Comment by harshavardhana** [comment]
@adferrand were you able to look at this further? - If not I will go ahead and close this issue for now. Since we have most of our deployments in k8s and do not face this problem at all.

**Comment by adferrand** [comment]
It is difficult to gather data because of the irregularity of the error. However what I could see so far is that initially the faulty node receives a SIGTERM from the cluster.

It does so because the LivenessProbe marks the Pod as unhealthy. And it has been initiated by the `/health` endpoint that suddenly timeout.

I really think that it is not related to MinIO, but specific to the cluster, that fails its network for whatever reason.

However after that the node enters in this infinite restart loop were it fails to acquire its lock during the safemode phase, then reach the deadline to acquire lock making it restart, as we saw in the code previously.

I still need to enable the MINIO_DSYNC_TRACE=1 to see exactly what is going on during the lock acquire, and why my cluster never reaches again a stable status.

**Comment by harshavardhana** [comment]
> However after that the node enters in this infinite restart loop were it fails to acquire its lock during the safemode phase, then reach the deadline to acquire lock making it restart, as we saw in the code previously.
> 
> I still need to enable the MINIO_DSYNC_TRACE=1 to see exactly what is going on during the lock acquire, and why my cluster never reaches again a stable status.

Try with latest release @adferrand

**Comment by TheBeatles1994** [comment]
I am also having the same problem, and the error will occur completely randomly. @harshavardhana 
The network is healthy, and DNS can be resolved.

My minio version is 2020-06-01T17:28:03Z, and k8s version is 1.14.8.

**Comment by harshavardhana** [comment]
> I am also having the same problem, and the error will occur completely randomly. @harshavardhana
> The network is healthy, and DNS can be resolved.
> 
> My minio version is 2020-06-01T17:28:03Z, and k8s version is 1.14.8.

Move to latest release @TheBeatles1994

**Comment by adferrand** [comment]
Hello @harshavardhana, I updated my MinIO cluster to `RELEASE.2020-09-17T04-49-20Z`.

Sadly the issue continues to occur.

I saw in the Kubernetes events the following entries when one of the node fails to synchronize:
```
Liveness probe failed: Get http://10.2.9.107:9000/minio/health/live: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Container minio failed liveness probe, will be restarted
Readiness probe failed: Get http://10.2.9.107:9000/minio/health/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

So definitely the initial shutdown of the MinIO node is not initiated by the MinIO process itself, but by the liveness marking the pod as unhealthy, because of a timeout occuring while trying to access the `/minio/health/live` endpoint. After that the pod restarts, but fails to go out of the safemode, and needs a full restart the all pods to make the cluster work again.

I will try your suggestion to increase the timeout on the liveness probe.

**Comment by adamlamar** [comment]
I have this problem too. Can we re-open the issue?

As I can see it, the issue is that some replicas are not able to obtain the lock on startup, and they're stuck forever with the message `Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock`.

We can clearly see minio-0 is ready, but minio-1 is not:

```
/ $ curl minio-0.minio:9000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>163818C91694A79D</RequestId><HostId>017b62a1-74cd-4448-b2ce-0adc57074629</HostId></Error>/ $
/ $ curl minio-1.minio:9000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Resource>/</Resource><RequestId>163818CAD4AB7769</RequestId><HostId>017b62a1-74cd-4448-b2ce-0adc57074629</HostId>
```

The readiness check also returns safemode status, but is still 200:
```
/ $ curl -v minio-1.minio:9000/minio/health/ready
*   Trying 10.244.94.25...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x560847af7a40)
* Connected to minio-1.minio (10.244.94.25) port 9000 (#0)
> GET /minio/health/ready HTTP/1.1
> Host: minio-1.minio:9000
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO/RELEASE.2020-09-17T04-49-20Z
< Vary: Origin
< X-Amz-Request-Id: 163818F24F0B322F
< X-Minio-Server-Status: safemode
< X-Xss-Protection: 1; mode=block
< Date: Fri, 25 Sep 2020 18:04:56 GMT
<
* Connection #0 to host minio-1.minio left intact
```

This is on a brand new cluster under very little load.

**Comment by adamlamar** [comment]
I turned on `MINIO_DSYNC_TRACE=1` and all replicas are constantly emitting this message:

```
dsync: Unable to call Lock failed with Expected 'lock' API version 'v3', instead found 'v3', please upgrade the servers for dsync.LockArgs{UID:"bfdf8d1f-23a8-4b46-b6bd-d5a0593f19ef", Resources:[]string{".minio.sys/config/transaction.lock"}, Source:"[server-main.go:251:initSafeMode()]"} at http://minio-2.minio:9000/storage
```

**Comment by harshavardhana** [comment]
> I turned on `MINIO_DSYNC_TRACE=1` and all replicas are constantly emitting this message:
> 
> ```
> dsync: Unable to call Lock failed with Expected 'lock' API version 'v3', instead found 'v3', please upgrade the servers for dsync.LockArgs{UID:"bfdf8d1f-23a8-4b46-b6bd-d5a0593f19ef", Resources:[]string{".minio.sys/config/transaction.lock"}, Source:"[server-main.go:251:initSafeMode()]"} at http://minio-2.minio:9000/storage
> ```

This means that you `minio-2.minio` is not resolvable to the host where MinIO is running i.e there is no taker for the local locker server. Looks like your setup is wrong here.

**Comment by adamlamar** [comment]
I don't believe there is a DNS resolution problem. We actually ran a 2019 release for a long time in these clusters and never had this problem.

Also, I recreated the minio statefulset and this time the log message from minio-3 states that the issue lies with minio-0:

```
dsync: Unable to call RLock failed with /rlock "http://minio-0.minio:9000/minio/lock/storage/v3": remote server offline for dsync.LockArgs{UID:"50977d21-9cf8-4dd5-b946-634aa49d4bf8", Resources:[]string{".minio.sys/backen
d-encrypted"}, Source:"[erasure-object.go:241:erasureObjects.GetObject()]"} at http://minio-0.minio:9000/storage
```

So I exec into the minio-3 pod and requests to minio-0 complete as expected:

```
/ $ curl http://minio-0.minio:9000/storage
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>storage</BucketName><Resource>/storage</Resource><RequestId>16381A374472BE00</RequestId><HostId>9b498750-1b30-471d-8b57-ac93cdf76919</HostId></Error>/ $
```

**Comment by harshavardhana** [comment]
> I don't believe there is a DNS resolution problem. We actually ran a 2019 release for a long time in these clusters and never had this problem.

The statefulset headless service is wrong here @adamlamar you should be using the `minio-0.minio.svc.cluster.local`

**Comment by adamlamar** [comment]
With a statefulset, both DNS names will resolve. But just to show, here's the same issue with the fully qualified name:

```
dsync: Unable to call Lock failed with /lock "http://minio-1.minio.<namespace>.svc.cluster.local:9000/minio/lock/storage/v3": remote server offline for dsync.LockArgs{UID:"06f3c793-3af6-478f-ac90-05f2a490a2e8", Resources:[]string{".minio.sys/config/transaction.lock"}, Source:"[server-main.go:251:initSafeMode()]"} at http://minio-1.minio.<namespace>.svc.cluster.local:9000/storage
```

This issue can be hard to reproduce, and I think it only occurs often when the node (not minio itself) is under high load. Would it be possible to adjust the readiness endpoint to fail when minio is in safe mode? I think that would fix the majority of the issue.

**Comment by adferrand** [comment]
> 
> 
> With a statefulset, both DNS names will resolve. But just to show, here's the same issue with the fully qualified name:
> 
> ```
> dsync: Unable to call Lock failed with /lock "http://minio-1.minio.<namespace>.svc.cluster.local:9000/minio/lock/storage/v3": remote server offline for dsync.LockArgs{UID:"06f3c793-3af6-478f-ac90-05f2a490a2e8", Resources:[]string{".minio.sys/config/transaction.lock"}, Source:"[server-main.go:251:initSafeMode()]"} at http://minio-1.minio.<namespace>.svc.cluster.local:9000/storage
> ```
> 
> This issue can be hard to reproduce, and I think it only occurs often when the node (not minio itself) is under high load. Would it be possible to adjust the readiness endpoint to fail when minio is in safe mode? I think that would fix the majority of the issue.

I completely agree. If the readiness probe could fail during safemode, it would have following great benefits:
* it would make visible in the Kubernetes metadata that the node is not ready, and maybe unhealthy (typically it would trigger some alerts on a properly configured Prometheus stack)
* the node will not be joinable from the service endpoint, avoiding from clients the `Server not initialized, please try again.` errors, because requests would be redirected to healthy nodes
* the unhealthy node would eventually be restarted, increasing chances for auto-heal (even if in my case, a restart of all nodes are required)

**Comment by adferrand** [comment]
If a maintainer is up to give some time on that issue, I am totally up for writing a PR on that matter. I have the following design propositions:
1. modify the logic of the existing endpoint `/minio/health/ready` to return `200` HTTP status code only when the node has exited the `safemode`
2. modify this logic only when an ad-hoc environment variable is set
3. create a new endpoint like `/minio/health/initialized` that would have the new logic and keep `/minio/health/ready` untouched

**Comment by harshavardhana** [comment]
@adferrand readiness is a bit of a broken behavior from k8s - meant to be only used by nginx like applications - for our networking guarantees do not work in their parlance. That is why we suggest removing readiness altogether, we have removed it from all our docs and it should never be used. 

The reason is readiness allows for cascading network failure when nothing fails in that manner in MinIO.

**Comment by adamlamar** [comment]
@harshavardhana I don't think @adferrand or I are asking for full k8s readiness semantics, but rather just a switch we can flip when minio transitions from safe mode to normal operation. This could then be checked with a kubernetes [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes).

**Comment by harshavardhana** [comment]
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock

In-fact I was able to reproduce this - this is actually not related to readiness or liveness or whatever - it is related to how pods come up. 

> @harshavardhana I don't think @adferrand or I are asking for full k8s readiness semantics, but rather just a switch we can flip when minio transitions from safe mode to normal operation. This could then be checked with a kubernetes [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes).

For example, these probes are not that valuable for MinIO - MinIO already knows how to handle the node failure appropriately. All you need is an ingress rule to MinIO nodes to have proper HA for client traffic. 

We don't need to rely on k8s to turn off the network and take it back online etc. This type of design is very disruptive to MinIO and its operations. 

That is why I will fix the original problem that I found because adding startup probes readiness probes is not going to fix this problem.

**Comment by adamlamar** [comment]
Fixing the original problem works too! 👍

**Comment by adferrand** [comment]
> For example, these probes are not that valuable for MinIO - MinIO already knows how to handle the node failure appropriately. All you need is an ingress rule to MinIO nodes to have proper HA for client traffic.
> 
> We don't need to rely on k8s to turn off the network and take it back online etc. This type of design is very disruptive to MinIO and its operations.

Indeed as @adamlamar said I was not thinking about modifying the behavior of `/minio/health/ready` for the internal logic of the MinIO cluster, but for providing the kind of ingress rule that you are describing, because the only way I know for a Kubernetes Service to not load balance to a particular pod is if the readiness/liveness probe is failing. In the context of Kubernetes that kind of readiness logic makes sense at the edge of the MinIO cluster in my opinion.

However if `/minio/health/ready` is also used internally by MinIO to synchronization operation between the MinIO pods, I understand that modifying its behavior is indeed a problem.

If you found the root cause of this issue, that is really great! I am looking forward to seeing the fix!

However I would like to advocate for an alternate readiness endpoint, specifically for cloud usage as described above. Indeed even with a prefectly healty MinIO cluster, there is a short time during which MinIO pods are marked as healthy but are not out of the `safemode` yet, because the readiness probe is already marking them as ready. Typically on my cluster a given pod takes 70 seconds to synchronize. During this time a client that would make a request to the Kubernetes Service, and would be load balanced to the initializing pod, will receive the error `Server not initialized, please try again.`.

In that context do you still think it worths to add another endpoint for that matter that could be used by the MinIO Helm Chart for instance?

**Comment by adferrand** [comment]
Since the problem has been confirmed, reproduced, and currently under work, could we reopen this issue to keep track of the changes? I can also engage the discussion about the modified readiness probe in a separate issue if you want.

**Comment by adamlamar** [comment]
Any chance we could get this fix into a tagged release soon?

**Comment by adferrand** [comment]
New release with the fix! https://github.com/minio/minio/releases/tag/RELEASE.2020-10-03T02-19-42Z

Thanks a lot @harshavardhana.

**Comment by simonrey1** [comment]
I have a problem pulling this image:
```
docker pull minio/minio:RELEASE.2020-10-03T02-19-42Z
```
Output:
```
RELEASE.2020-10-03T02-19-42Z: Pulling from minio/minio
df20fa9351a1: Pulling fs layer
72bf75d60211: Pulling fs layer
error pulling image configuration: unknown blob
```

**Comment by harshavardhana** [comment]
> I have a problem pulling this image:
> 
> ```
> docker pull minio/minio:RELEASE.2020-10-03T02-19-42Z
> ```
> 
> Output:
> 
> ```
> RELEASE.2020-10-03T02-19-42Z: Pulling from minio/minio
> df20fa9351a1: Pulling fs layer
> 72bf75d60211: Pulling fs layer
> error pulling image configuration: unknown blob
> ```

Docker lost, data again @eqqe we have fixed it for now.
