### ISSUE TITLE
[wont fix] Support for Azure Data Lake Storage (Gen 2) in Azure Proxy

### ISSUE THREAD

**Issue by martenlindblad** [minio/minio#10410]
**Is your feature request related to a problem? Please describe.**
When using Apache Flink we are left with two options regarding storing data on disk. Either pure HDFS or S3. Azure have an object store (Azure Blob Storage) that is not supported. MinIO helps us using Azure Blob Storage via the Azure Proxy interface. However, Azure also have a concept called Azure Data Lake Storage (Gen 2). This storage option is better suited for big data operations using [hierarchical namespace](https://docs.microsoft.com/sv-se/azure/storage/blobs/data-lake-storage-namespace). This is because rename is an atomic operation. It also has support for ACL per directory which regular Blob Storage does not have.
Unfortunately MinIO doesn't support Azure Data Lake Storage (Gen 2).

**Describe the solution you'd like**
I would like MinIO to figure out if the Azure Storage is in fact Azure Data Lake Storage (Gen 2) and if that's the case, use the API for the **hierarchical namespace**.

**Describe alternatives you've considered**
The alternatives are use the regular Azure Blob Storage. This works but is not optimal since renames occur quite an overhead when dealing with lots of data, and ACL can't be done on folder level.

**Additional context**
There are two big players when it comes to streaming big data platforms, Apache Flink and Apache Spark. Flink unfortunately have worse support for different file systems, but it's much easier to program streaming applications on it.

**Comment by harshavardhana** [comment]
For now, our gateway implementations are in code freeze. Moving this for future exploration.

**Comment by harshavardhana** [comment]
We decided that this is out of scope for our Azure Gateway implementation and we do not have the resources currently to work on this. Closing this as won't fix for now.
