### ISSUE TITLE
release: Official release?

### ISSUE THREAD

**Issue by arschles** [minio/minio#1041]
Will Minio have an official release or something similar? Right now, [deis/minio](https://github.com/deis/minio) is using builds from HEAD of this repository, but we'd prefer to use something that the team considers stable and will support for a defined amount of time.

**Comment by harshavardhana** [comment]
> Will Minio have an official release or something similar? Right now, deis/minio is using builds from HEAD of this repository, but we'd prefer to use something that the team considers stable and will support for a defined amount of time.

Yes we will, we are currently working on that. We are planning on making an official release end of this month to feb 1st week.  Officially released binaries will be signed,  anyone using locally can verify the signed binaries using public key. 

Additionally we consider 'HEAD' to be always ready to be used or at least pre-production, there is no unstable branch :-)

**Comment by arschles** [comment]
Sounds good @harshavardhana. We've found that HEAD has indeed been very stable, but we're really looking forward to trying out the official release!

**Comment by harshavardhana** [comment]
> Sounds good @harshavardhana. We've found that HEAD has indeed been very stable, but we're really looking forward to trying out the official release!

@arschles -  we will keep you guys informed. Thanks for the heads up.

**Comment by harshavardhana** [comment]
> Sounds good @harshavardhana. We've found that HEAD has indeed been very stable, but we're really looking forward to trying out the official release!

An official release has been uploaded, please test and give us feedback. This version also brings 'minio browser' out of the box. 

We are going to keep pushing more releases, closing this issue.

**Comment by arschles** [comment]
Thanks @harshavardhana - do you happen to have binary releases anywhere? We'd love to use one for Alpine linux...

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana - do you happen to have binary releases anywhere? We'd love to use one for Alpine linux...

@arschles we have it available always at https://dl.minio.io/server/minio/release/ - haven't build anything specifically for Alpine Linux? what architecture are you looking for?

**Comment by harshavardhana** [comment]
Reopening so that @arschles , you can close this yourself once you have the new binaries for deis.

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana - do you happen to have binary releases anywhere? We'd love to use one for Alpine linux...

@arschles - were you able to try the new released binary for Alpine Linux yet? - Let us know Thanks.

**Comment by arschles** [comment]
Hey @harshavardhana - we haven't been able to review yet, but deis/minio#70 tracks that work. I'm gonna be getting back to working on that component of the Deis platform soon (probably this afternoon or Monday), so I'll try it then. Thanks for reminding!

**Comment by harshavardhana** [comment]
> Hey @harshavardhana - we haven't been able to review yet, but deis/minio#70 tracks that work. I'm gonna be getting back to working on that component of the Deis platform soon (probably this afternoon or Monday), so I'll try it then. Thanks for reminding!

Thanks - let us know of any issues.

**Comment by harshavardhana** [comment]
> Hey @harshavardhana - we haven't been able to review yet, but deis/minio#70 tracks that work. I'm gonna be getting back to working on that component of the Deis platform soon (probably this afternoon or Monday), so I'll try it then. Thanks for reminding!

Checking back to see if you were able to validate the new released binaries?

**Comment by arschles** [comment]
Yep, we have a PR with experimental support for it in https://github.com/deis/minio/pull/75. We're in the process of validation, functional and manual testing now!

**Comment by harshavardhana** [comment]
> Yep, we have a PR with experimental support for it in deis/minio#75. We're in the process of validation, functional and manual testing now!

Thanks @arschles .

**Comment by arschles** [comment]
@harshavardhana we tried out the official release in https://github.com/deis/minio/pull/75, but found that it doesn't _quite_ work for everything we need. We have a multipart fix in https://github.com/minio/minio/pull/1126 that would need to go into a new official release before we can adopt it.

**Comment by harshavardhana** [comment]
> @harshavardhana we tried out the official release in deis/minio#75, but found that it doesn't quite work for everything we need. We have a multipart fix in #1126 that would need to go into a new official release before we can adopt it.

Yes we are planning to make a new release, which might happen this week.

**Comment by arschles** [comment]
Cool. Can you ping here when that happens?

**Comment by harshavardhana** [comment]
> Cool. Can you ping here when that happens?

Yes absolutely.

**Comment by arschles** [comment]
Thanks!

**Comment by harshavardhana** [comment]
@arschles - uploaded a new binary yesterday, can you validate it on your end?

**Comment by arschles** [comment]
@harshavardhana we're working on releasing our beta now, but I'll be starting to submit patches for upgrading both the new client & server for our first release candidate, and I'll mention this issue in each. Thanks for letting me know!

**Comment by harshavardhana** [comment]
This has been fixed.
