### ISSUE TITLE
FATAL error "corrupted backend format" when lost+found is found on backend dir

### ISSUE THREAD

**Issue by enayzhu** [minio/minio#10411]
When 4 minio pods are deployed on three nodes in a distributed manner, one pod may not start normally. 

Error log: {"level":"FATAL","errKind":"","time":"2020-08-27T08:55:14.880603038Z","error":{"message":"Disk https://minio-data-mn-3.minio-data-mn-svc.pcc.svc.cluster.local:9000/export: corrupted backend format, please join https://slack.min.io for assistance","source":["/go/pkg/mod/pkg/mod/github.com/minio/cli@v1.22.0/app.go:500:cli.HandleAction()"]}}

## Expected Behavior

All pods start normally.
The problem I encountered should be the same problem as 9277.
But I found that there is lost+found on some disks, but pods can still be used.

So I would like to ask how lost+found affects the start of pod ?
Under what scenarios will minio report FATAL level errors ?  Can you give me a few examples ? Thanks a lot.
 
## Current Behavior

Occasionally an "corrupted backend format" error occurs, and the pod cannot start normally

## Steps to Reproduce (for bugs)

1.In my environment, it can be reproduced directly after installation
2.
3.
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-02-27T00-23-05Z-4-gcb4a9140
* Server setup and configuration:Kubernetes 1.17.3,  network-block for the minio volume
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2020-02-27T00-23-05Z-4-gcb4a9140

use latest release this issue has been long fixed, we properly ignore "lost+found" now.

**Comment by enayzhu** [comment]
Under what scenarios will minio report FATAL level errors ? Can you give me a few examples ? Thanks a lot.

**Comment by klauspost** [comment]
@enayzhu You are welcome to browse the code.  

Alternatively we can provide personal assistance through our subscription service: https://min.io/pricing
