### ISSUE TITLE
[working as intended] MINIO_SSE_AUTO_ENCRYPTION key does not work

### ISSUE THREAD

**Issue by mchudinov** [minio/minio#10428]
When MINIO_SSE_AUTO_ENCRYPTION is set to **on** it does not activate encryption for new buckets.

## Expected Behavior
With MINIO_SSE_AUTO_ENCRYPTION set to **on** encryption should be activated automatically for every new bucket. 

## Current Behavior
No encryption currently until it is explicitly activated with command line
`mc encrypt set sse-s3 minio/bucket1/`

## Steps to Reproduce (for bugs)
Tested with current Docker image of minio.

Example of my docker-compose
```services:
  minio1:
    image: minio/minio
    container_name: minio1
    networks:
      - minio
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_KMS_KES_ENDPOINT=https://kes:7373
      - MINIO_KMS_KES_CERT_FILE=/build/kes-identity-minio.cert
      - MINIO_KMS_KES_KEY_FILE=/build/kes-identity-minio.key
      - MINIO_KMS_KES_CA_PATH=/build/kes-server.cert
      - MINIO_KMS_KES_KEY_NAME=minio-key
      - MINIO_SSE_AUTO_ENCRYPTION=on    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - kes
    command: server http://minio{1...3}/data{1...2}
```

## Your Environment
* Version used (`minio --version`): the last Docker image RELEASE.2020-09-05T07-14-49Z
* Operating System and version (`uname -a`): Docker image

**Comment by harshavardhana** [comment]
> No encryption currently until it is explicitly activated with command line
> `mc encrypt set sse-s3 minio/bucket1/`

This is the expected behavior if necessary you should use the latest ENV 

>       - MINIO_SSE_AUTO_ENCRYPTION=on

MINIO_KMS_AUTO_ENCRYPTION=on
