### ISSUE TITLE
[not our bug] The objects with lock configuration should not allow any overwriting actions

### ISSUE THREAD

**Issue by forestbupt** [minio/minio#10425]
Previously(RELEASE.2020-05-08) we can protect the objects from overwriting by these steps:
1. mc mb -l minio/test
2. mc lock minio/test governance 1d

with above configuration, any overwriting actions would get a "Object is WORM protected and cannot be overwritten" error.

but in the latest release (RELEASE.2020-09-05) the overwriting actions are performed successfully.

## Expected Behavior
The objects with lock configuration should not allow any overwriting actions

## Current Behavior
The overwriting actions are performed successfully, and there are multiple version objects in the bucket. 

## Possible Solution
Not allow overwriting until the current version object's RetainUntilDate expire

## Steps to Reproduce (for bugs)
Previously:
[root@server minio]# ./minio -v
minio version RELEASE.2020-05-08T02-40-49Z
[root@server minio]#
[root@server minio]# ./mc mb -l minio/test
Bucket created successfully `minio/test`.
[root@server minio]# ./mc lock minio/test governance 1d
GOVERNANCE mode is enabled for 1DAYS
[root@server minio]# ./mc cp /etc/hosts minio/test/hosts
/etc/hosts:    344 B / 344 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 7.23 KiB/s 0s[root@server minio]#
[root@server minio]#
[root@server minio]# ./mc cp /etc/hosts minio/test/hosts
mc: <ERROR> Failed to copy `/etc/hosts`. Object is WORM protected and cannot be overwritten

now:
[root@server minio]# ./minio -v
minio version RELEASE.2020-09-05T07-14-49Z
[root@server minio]# ./mc mb -l minio/test
Bucket created successfully `minio/test`.
[root@server minio]#
[root@server minio]# ./mc lock minio/test governance 1d
GOVERNANCE mode is enabled for 1DAYS
[root@server minio]#
[root@server minio]# ./mc cp /etc/hosts minio/test/hosts
/etc/hosts:    344 B / 344 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 46.93 KiB/s 0s [root@server minio]#
[root@server minio]#
[root@server minio]# ./mc cp /etc/hosts minio/test/hosts
/etc/hosts:    344 B / 344 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 50.31 KiB/s 0s [root@server minio]#
[root@server minio]#
[root@server minio]# ./mc ls minio/test/hosts --versions
[2020-09-06 02:42:59 EDT]    344B hosts (2nd, vid=bbb2711b-4771-4e69-a764-3ef4b8c8ad64)
[2020-09-06 02:42:56 EDT]    344B hosts (1st, vid=2d4db8a4-267c-427a-882d-d845f7238722)

## Context
Although we can use the new 'version-id' to protect the specified objects, the problem is that our existing apps don't understand version-id at all, in our cases, we just want to make sure the the objects are immutable. Introducing the new 'version-id' concept into our system require extra effort, for example most apis need to add a new parameter versionId. It looks not reasonable since we don't need multiple versions.

## Your Environment
* Version used (`minio --version`): RELEASE.2020-09-05T07-14-49Z
* Server setup and configuration:  ./minio server /root/minio/data1 /root/minio/data2 /root/minio/data3 /root/minio/data4
* Operating System and version (`uname -a`): Linux server 4.18.0-80.11.2.el8_0.x86_64

**Comment by harshavardhana** [comment]
The reason for this because we implemented bucket versioning just like AWS S3

So object locking implicitly enables versioning on the bucket, it's not that your original content is overwritten that is saved as an older version and protected.

So if you delete a particular version you are not really able to delete a version on the object. 

Read the cohasset assessment of the implementation https://min.io/cohasset

And for understanding spec https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock.html

**Comment by harshavardhana** [comment]
> Although we can use the new 'version-id' to protect the specified objects, the problem is that our existing apps don't understand version-id at all, in our cases, we just want to make sure the the objects are immutable. Introducing the new 'version-id' concept into our system require extra effort, for example most apis need to add a new parameter versionId. It looks not reasonable since we don't need multiple versions.

This is unfortunate, your apps need to understand the versioning concepts, our intention is to be S3 API compatible as we previously had an incompatible implementation.
