### ISSUE TITLE
[working as intended] Minio not supporting bucket versioning 

### ISSUE THREAD

**Issue by anisha-deverashetty** [minio/minio#10429]
I am using MinIO client to create buckets and enable versioning. I am running the latest image of minio server from dockerhub. I get error when trying to enable versioning.

However when I tried some old release version (RELEASE.2020-08-18T19-41-00Z), I was able to enable versioning successfully.
 
## Expected Behavior
Should be able to enable versioning on bucket

## Current Behavior
Not able to enable versioning

## Steps to Reproduce (for bugs)
`mc version enable minio/mybucket`
mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.

## Your Environment
* Version used (minio --version): RELEASE.2020-09-05T07-14-49Z
* Server setup and configuration: I use minio/minio docker container running on Ubuntu
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

**Comment by harshavardhana** [comment]
MinIO supports bucket versioning only in erasure coded and distributed erasure coded mode, refer docs https://docs.minio.io/docs/minio-bucket-versioning-guide.html

> Versioning feature is only available in erasure coded and distributed erasure coded setups.

**Comment by anisha-deverashetty** [comment]
Ah I didn't notice that in docs. Thanks @harshavardhana for quick reply.
