### ISSUE TITLE
[resolved] Get incomplete result when download with rate limit

### ISSUE THREAD

**Issue by ethinx** [minio/minio#10430]
We have a test, download file from MinIO with `curl --limit-rate`, always get incomplete content and curl complain:

```
curl -o /dev/null --limit-rate 300k http://minio.example.com:9000/data.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 71 28.1M   71 20.0M    0     0   299k      0  0:01:36  0:01:08  0:00:28  300k
curl: (18) transfer closed with 8532684 bytes remaining to read
```
It has no problem when download without rate limit.

Moreover, when download with rate limit, we did tcpdump and check the socket on server, seems the server close the socket when there were still data in the socket Send-Q.

```
ESTAB      0      1256864    Server:9000                  Client:54766
ESTAB      0      1107720    Server:9000                  Client:54766
FIN-WAIT-1 0      1279382    Server:9000                  Client:54766
FIN-WAIT-1 0      1097318    Server:9000                  Client:54766
FIN-WAIT-1 0      726550    Server:9000                  Client:54766
FIN-WAIT-1 0      489310    Server:9000                  Client:54766
FIN-WAIT-1 0      238910    Server:9000                  Client:54766
FIN-WAIT-2 0      0         Server:9000                  Client:54766
// socket disappear
```

## Expected Behavior
Get complete file content

## Current Behavior
Get incomplete file content

## Possible Solution
Close connection when client receive all datas.

## Steps to Reproduce (for bugs)
1. Upload a big file to MinIO
2. Download the file by `curl` and set a small rate limit, e.g. `--limit-rate 200k`

## Context
We did rate limit on client side and notice this issue.

## Regression
May be not a regression

## Your Environment

* Version used (`minio --version`): RELEASE.2020-07-12T19-14-17Z
* Server setup and configuration: no particular config
* Operating System and version (`uname -a`): CentOS 7

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2020-07-12T19-14-17Z
> * Server setup and configuration: no particular config
> * Operating System and version (`uname -a`): CentOS 7

Are you running MinIO server in distributed ? is there any TLS involved? any proxy in between?

**Comment by ethinx** [comment]
> > * Version used (`minio --version`): RELEASE.2020-07-12T19-14-17Z
> > * Server setup and configuration: no particular config
> > * Operating System and version (`uname -a`): CentOS 7
> 
> Are you running MinIO server in distributed ? is there any TLS involved? any proxy in between?

Yes, it's in distributed.

We did test in these two way, result are the same:

1. client -> LB -> (one of the distributed node) [ Nginx with TLS -> MinIO ]
2. client -> one of the distributed MinIO instance directly

**Comment by harshavardhana** [comment]
> > > * Version used (`minio --version`): RELEASE.2020-07-12T19-14-17Z
> > > * Server setup and configuration: no particular config
> > > * Operating System and version (`uname -a`): CentOS 7
> > 
> > 
> > Are you running MinIO server in distributed ? is there any TLS involved? any proxy in between?
> 
> Yes, it's in distributed.
> 
> We did test in these two way, result are the same:
> 
> 1. client -> LB -> (one of the distributed node) [ Nginx with TLS -> MinIO ]
> 2. client -> one of the distributed MinIO instance directly

Can you try with latest release?

**Comment by ethinx** [comment]
Try this version and problem disappear, thx and closed the issue.

minio version RELEASE.2020-09-05T07-14-49Z
