### ISSUE TITLE
ssl: Support automatic SSL with letsencrypt

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1043]
Implement automatic SSL with https://letsencrypt.org/ support.

**Comment by alexanderjulo** [comment]
I don't think minio should do this on itself, if you use docker it is super easy to spin up any kind of proxy (like caddy or nginx-proxy) and link them to achieve the same thing.

**Comment by harshavardhana** [comment]
You are right @alexex we are not implementing it just yet. Proxy solves this problem for us for the time being.
