### ISSUE TITLE
[resolved] Empty Query for Long.MAX_VALUE Comparison

### ISSUE THREAD

**Issue by philipp-kaiser** [minio/minio#10436]
When doing a simple query with Java-Client, i get an empty result when comparing some value with Long.MAX_VALUE (9223372036854775807).

`SELECT * FROM S3Object s WHERE s.somevalue <= 9223372036854775807`

## Expected Behavior
The query should return the expected results. When using one digit less (922337203685477580), it's working as expected.
Is there a maximum value limit?

## Current Behavior
Queries with Long.MAX_VALUE return empty result.

## Steps to Reproduce (for bugs)
1.  Query for:
`SELECT * FROM S3Object s WHERE s.somevalue <= 9223372036854775807`
2. Query for:
`SELECT * FROM S3Object s WHERE s.somevalue <= 922337203685477580`

## Context
We store timestamps and query for x <= Long.MAX_VALUE to get all objects.

## Your Environment
Minio Java Client
Version: io.minio:minio:7.1.0
Java: 8

**Comment by klauspost** [comment]
Fix linked below.
