### ISSUE TITLE
getLocalBackgroundHealStatus panic while globalIsErasure is false

### ISSUE THREAD

**Issue by pengzhenpin** [minio/minio#10454]
while i use minio client without erasure : mc admin info minio/,minio server panic
## Expected Behavior

display minio server information
## Current Behavior

minio server panic and mc hang
## Possible Solution

cmd/global-heal.go:71 `bgSeq, ok := globalBackgroundHealState.getHealSequenceByToken(bgHealingUUID)`
minio server panic because `globalIsErasure` is `false` , in cmd/server-main.go:440 global heal state keep nil

Can we add a statement to determine whether `globalBackgroundHealState` is `nil` or `globalIsErasure` is `false`：

```golang
func getLocalBackgroundHealStatus() (madmin.BgHealState, bool) {
	if globalBackgroundHealState == nil {
		return madmin.BgHealState{}, false
	}
	……
```

or 

```golang
func getLocalBackgroundHealStatus() (madmin.BgHealState, bool) {
	if globalIsErasure == false {
		return madmin.BgHealState{}, false
	}
	……
```

## Steps to Reproduce (for bugs)

1. start minio server：minio server /data/tmp
2. mc alias set minio http://172.16.31.238:9000 minioadmin minioadmin
3. mc admin info minio/
4. server painc

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2020-09-05T07-14-49Z
* Server setup and configuration:minio server /data/tmp
* Operating System and version (`uname -a`):Linux notebook 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@pengzhenpin thanks for the report - sent a fix
