### ISSUE TITLE
[working as intended] MinIO Azure Gateway Docs don't lead to functional solution

### ISSUE THREAD

**Issue by darkn3rd** [minio/minio#10452]
## Expected Behavior

As per documention, this should magically work:

```
docker run -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=azurestorageaccountname" \
 -e "MINIO_SECRET_KEY=azurestorageaccountkey" \
 minio/minio gateway azure
```

## Current Behavior

The feedback to the user is:

```
ERROR Unable to initialize gateway backend: illegal base64 data at input byte 18
```

## Possible Solution

Document how to configure credentials for the container.  Similar to GCS.

## Steps to Reproduce (for bugs)

As per [documentation](https://docs.min.io/docs/minio-gateway-for-azure.html):

```bash
docker run -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=azurestorageaccountname" \
 -e "MINIO_SECRET_KEY=azurestorageaccountkey" \
 minio/minio gateway azure
```

## Context

I cannot get off the ground with MinIO + Azure.  I will have to walk through the code, either find an example, like unit tests or look through the source code as documentation.

## Regression

Other people have reported this before, but no solution.

## Your Environment

* minio version RELEASE.2020-04-28T23-56-56Z
* docker
* ubuntu 19.10

**Comment by harshavardhana** [comment]
> ```
> ERROR Unable to initialize gateway backend: illegal base64 data at input byte 18
> ```

Are you just copy pasting our documents?

**Comment by kannappanr** [comment]
@darkn3rd I just tried the command you pasted

```
docker run -p 9000:9000 --name azure-s3 -e "MINIO_ACCESS_KEY=azureaccesskey" -e "MINIO_SECRET_KEY=azuresecretkey" minio/minio gateway azure
```
and we are also testing minio azure gateway on every PR.

**Comment by harshavardhana** [comment]
@darkn3rd is also using some old release here @kannappanr

**Comment by harshavardhana** [comment]
@darkn3rd for your situation you are better off using our https://az.minio.io/ navigate to 6th point is where you copy your storage account key and storage secret key.

**Comment by darkn3rd** [comment]
It's obvious in hindsight.  From the docs, I was using: https://docs.min.io/docs/minio-gateway-for-azure.html
I realized later I had to values from `az storage account show-connection-string`.
