### ISSUE TITLE
[not our bug] When a distributed minio node goes down, the page will appear empty without content, but access to a single file is normal

### ISSUE THREAD

**Issue by Linsanxian** [minio/minio#10462]
When a distributed minio node goes down, the page will appear empty without content, but access to a single file is normal

When I try to refresh multiple times, sometimes the page is normal and sometimes the page is empty

system version Linux aws-tc-qa-195 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
minio version RELEASE.2020-09-08T23-05-18Z

**Comment by Linsanxian** [comment]
I started distributed minio like this 

export MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
export MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

./minio server http://172.100.3.192/data/minio http://172.100.3.192/data/minio1 \
               http://172.100.2.219/data/minio http://172.100.2.219/data/minio1 \
               http://172.100.2.40/data/minio http://172.100.2.40/data/minio1 \
               http://172.100.3.195/data/minio http://172.100.3.195/data/minio1


use nginx as load balancer

upstream minio-cluster {
      server 172.100.3.195:9004 max_fails=3 fail_timeout=30s;
      server 172.100.3.192:9001 max_fails=3 fail_timeout=30s;
      server 172.100.2.219:9002 max_fails=3 fail_timeout=30s;
      server 172.100.2.40:9003 max_fails=3 fail_timeout=30s;
}

server {
 listen 80;

 ignore_invalid_headers off;
 client_max_body_size 0;
 proxy_buffering off;

 location / {
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For 	$proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header Host $http_host;

   proxy_connect_timeout 300;
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   chunked_transfer_encoding off;

   proxy_pass http://minio-cluster;
 }
}

**Comment by harshavardhana** [comment]
> ./minio server http://172.100.3.192/data/minio http://172.100.3.192/data/minio1
> http://172.100.2.219/data/minio http://172.100.2.219/data/minio1
> http://172.100.2.40/data/minio http://172.100.2.40/data/minio1
> http://172.100.3.195/data/minio http://172.100.3.195/data/minio1

Your entire setup is wrong here @Linsanxian you have incorrectly setup distributed setup. You should use ellipses syntax to provide maximum availability using setup the way you have done will lead to loss of availability quickly. 

Re-do your setup like this..

```
./minio server http://server{1...4}/minio{1...2}
```

> minio version RELEASE.2020-09-08T23-05-18Z

Use the latest release

**Comment by Linsanxian** [comment]
must it be started this way?

I will try to update to the latest version

**Comment by harshavardhana** [comment]
> must it be started this way?
> 
> I will try to update to the latest version

Yes if you want correct HA it is expected, otherwise you are incorrectly spreading the drives.

**Comment by Linsanxian** [comment]
I have updated to the latest version and started as you said before
But still encounter the same problem

export MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
export MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

./minio server http://server{1...4}/data/minio{1...2}


/etc/hosts
172.100.3.192 server1
172.100.2.219 server2
172.100.2.40 server3
172.100.3.195 server4

**Comment by harshavardhana** [comment]
what problem do you encounter? @Linsanxian

**Comment by harshavardhana** [comment]
your issue looks like you are trying to access through the load balancer and its not able to list content - just point to any IP directly at port 9000 all content should be correctly visible. To fix this you have to make sure your LB rejects the downed server correctly and not fail with 504 gateway errors.

**Comment by harshavardhana** [comment]
I tried reproducing locally, 

```
#!/usr/bin/env bash

unset MINIO_KMS_KES_CERT_FILE
unset MINIO_KMS_KES_KEY_FILE
unset MINIO_KMS_KES_ENDPOINT
unset MINIO_KMS_KES_KEY_NAME

export MINIO_PROMETHEUS_AUTH_TYPE=public
export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
export MINIO_UPDATE_MINISIGN_PASSWD="RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav"
export MINIO_KMS_MASTER_KEY=my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574
export MINIO_KMS_AUTO_ENCRYPTION=off
export MINIO_DISK_USAGE_CRAWL_DEBUG=on
export MINIO_DSYNC_TRACE=1
export MINIO_ENDPOINTS="http://localhost:9002/tmp/fs-new1 http://localhost:9003/tmp/fs-new2 http://localhost:9004/tmp/fs-new3 http://localhost:9005/tmp/fs-new4"

#rm -rf /tmp/fs-new{1..4}
for i in {02..05}; do
    "${GOPATH}/bin/minio" server --address ":90${i}" &
done
```

I can always list content upto read quorum downed servers, doesn't look like an issue on MinIO

**Comment by Linsanxian** [comment]
I will describe my problem and the problems encountered in detail
After I start the four nodes in the above manner, my steps are as follows:
1. Open the Minio page and upload 2 files
2. Shut down one of the nodes
3. Keep refreshing the page
At this time, the following two situations will appear on the page:
1. You can see the uploaded files
2. Can't see any files

Check the address of the uploaded file separately, no problem

**Comment by harshavardhana** [comment]
> I will describe my problem and the problems encountered in detail
> After I start the four nodes in the above manner, my steps are as follows:
> 
> 1. Open the Minio page and upload 2 files
> 2. Shut down one of the nodes
> 3. Keep refreshing the page
>    At this time, the following two situations will appear on the page:
> 4. You can see the uploaded files
> 5. Can't see any files
> 
> Check the address of the uploaded file separately, no problem

Yes this is because your access to LB is going to downed node which returns 504, check the browser console logs and you will see the error returned. 

The issue is misconfigured load balancer.
