### ISSUE TITLE
MinIO distributed does not initialize but waits for other containers to to so

### ISSUE THREAD

**Issue by dedelmann** [minio/minio#10465]
Hi,
first of all i don't know if that is a supported setup but i am trying to run minio distributed on 4 nodes with 1 drive each. I also want to run it with docker so i setup following command that i run on every node to start up minio (i also tried the same command/nodes but setting up a standalone minio and it works):
```
docker run --restart=unless-stopped \
  -d -p 9000:9000 \
  --name minio \
  -e "MINIO_REGION_NAME=my-region" \
  -e "MINIO_ACCESS_KEY=<access-key>" \
  -e "MINIO_SECRET_KEY=<secret-key>" \
  -v /mnt/drive01/:/data/drive01/ \
  minio/minio:RELEASE.2020-09-10T22-02-45Z \
  server http://minio{01...04}.my-domain.com:9000/data/drive{01...01}
```
But minio never initializes...
Log output (just keeps on going):
```
[root@minio01 ~]# docker logs minio
Waiting for a minimum of 2 disks to come online (elapsed 0s)

Waiting for a minimum of 2 disks to come online (elapsed 1s)

Waiting for a minimum of 2 disks to come online (elapsed 1s)

Waiting for a minimum of 2 disks to come online (elapsed 2s)

Waiting for a minimum of 2 disks to come online (elapsed 2s)

Unable to read 'format.json' from http://minio01.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers

Unable to read 'format.json' from http://minio02.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers

Unable to read 'format.json' from http://minio03.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers

Unable to read 'format.json' from http://minio04.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers
```
Browser:
```
<Error>
<Code>XMinioServerNotInitialized</Code>
<Message>Server not initialized, please try again.</Message>
<Key>drive01</Key>
<BucketName>data</BucketName>
<Resource>/data/drive01</Resource>
<RequestId>1633B039F86B80DB</RequestId>
<HostId/>
</Error>
```

## Expected Behavior
I guess it should just work as it does with the regular binary. It initializes and sets up everything on the storage drive.

## Current Behavior
MinIO never initializes.

## Steps to Reproduce (for bugs)
described above

## Your Environment
OS: CentOS Linux release 7.8.2003 (Core)
Docker Version: 19.03.12 (Docker Engine - Community)
Latency between nodes: <1ms
MinIO Version: RELEASE.2020-09-10T22-02-45Z

**Comment by harshavardhana** [comment]
> Hi,
> first of all i don't know if that is a supported setup but i am trying to run minio distributed on 4 nodes with 1 drive each. I also want to run it with docker so i setup following command that i run on every node to start up minio (i also tried the same command/nodes but setting up a standalone minio and it works):
> 
> ```
> docker run --restart=unless-stopped \
>   -d -p 9000:9000 \
>   --name minio \
>   -e "MINIO_REGION_NAME=my-region" \
>   -e "MINIO_ACCESS_KEY=<access-key>" \
>   -e "MINIO_SECRET_KEY=<secret-key>" \
>   -v /mnt/drive01/:/data/drive01/ \
>   minio/minio:RELEASE.2020-09-10T22-02-45Z \
>   server http://minio{01...04}.my-domain.com:9000/data/drive{01...01}
> ```
> 
> But minio never initializes...
> Log output (just keeps on going):
> 
> ```
> [root@minio01 ~]# docker logs minio
> Waiting for a minimum of 2 disks to come online (elapsed 0s)
> 
> Waiting for a minimum of 2 disks to come online (elapsed 1s)
> 
> Waiting for a minimum of 2 disks to come online (elapsed 1s)
> 
> Waiting for a minimum of 2 disks to come online (elapsed 2s)
> 
> Waiting for a minimum of 2 disks to come online (elapsed 2s)
> 
> Unable to read 'format.json' from http://minio01.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers
> 
> Unable to read 'format.json' from http://minio02.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers
> 
> Unable to read 'format.json' from http://minio03.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers
> 
> Unable to read 'format.json' from http://minio04.my-domain.com:9000/data/drive01: Expected 'storage' API version 'v20', instead found 'e01', please upgrade the servers
> ```
> 
> Browser:
> 
> ```
> <Error>
> <Code>XMinioServerNotInitialized</Code>
> <Message>Server not initialized, please try again.</Message>
> <Key>drive01</Key>
> <BucketName>data</BucketName>
> <Resource>/data/drive01</Resource>
> <RequestId>1633B039F86B80DB</RequestId>
> <HostId/>
> </Error>
> ```
> 
> ## Expected Behavior
> I guess it should just work as it does with the regular binary. It initializes and sets up everything on the storage drive.
> 
> ## Current Behavior
> MinIO never initializes.
> 
> ## Steps to Reproduce (for bugs)
> described above
> 
> ## Your Environment
> OS: CentOS Linux release 7.8.2003 (Core)
> Docker Version: 19.03.12 (Docker Engine - Community)
> Latency between nodes: <1ms
> MinIO Version: RELEASE.2020-09-10T22-02-45Z

This is because your DNS cannot be resolved in any manner. Notice the way you are running we need access to host IP if you are not planning to use overlay network.

So please specify --net=host

**Comment by harshavardhana** [comment]
> ```
>   server http://minio{01...04}.my-domain.com:9000/data/drive{01...01}
> ```

Also specify only one drive if you have only one drive i.e `/drive01` instead of `{01...01}` looks confusing to remember

**Comment by dedelmann** [comment]
Hi, thanks for the fast reply!
Yes that was it... Was a little too obvious i guess... Sorry for that but thanks for the help!
I also changed the drive to `/drive01` :)

Thanks again 👍
