### ISSUE TITLE
[working as intended] Error: http: Server closed

### ISSUE THREAD

**Issue by lost22git** [minio/minio#10464]
## Current Behavior

![image](https://user-images.githubusercontent.com/65008815/92877839-212d7b80-f43e-11ea-91a6-b4c701d7d6bf.png)

## Steps to Reproduce (for bugs)

1. First I run it in docker `docker run -d --name minio --network app_net -v D:\appdata\minio\config:/root/.minio -v D:\appdata\minio\data1:/minio/data1 -v D:\appdata\minio\data2:/minio/data2 -v D:\appdata\minio\data3:/minio/data3 -v D:\appdata\minio\data4:/minio/data4  -p 9000:9000 --restart=always minio/minio server /minio/data1 /minio/data2 /minio/data3 /minio/data4`
2. Secondly, I upload one file, and it success!
3. Thirdly, I  stop and remove the minio container, but data saved
4. Fourly, I run it in docker `docker run -d --name minio --network app_net -v D:\appdata\minio\config:/root/.minio -v D:\appdata\minio\data1:/minio/data1 -v D:\appdata\minio\data2:/minio/data2 -v D:\appdata\minio\data3:/minio/data3 -v D:\appdata\minio\data4:/minio/data4 -v D:\appdata\minio\data5:/minio/data5 -v D:\appdata\minio\data6:/minio/data6 -p 9000:9000 --restart=always minio/minio server /minio/data1 /minio/data2 /minio/data3 /minio/data4 /minio/data5 /minio/data6`，then throw error like this: 
![image](https://user-images.githubusercontent.com/65008815/92878609-dd874180-f43e-11ea-91d3-a8e479645157.png)

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-09-10T22-02-45Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Windows 10 2004, Docker in WSL2

**Comment by harshavardhana** [comment]
This is a normal error when we call Golang net/http Shutdown() it is printed @zxf-thingsmatrix nothing to worry about.

**Comment by lost22git** [comment]
it can not run in port 9000 over http after fourth step！ @harshavardhana

**Comment by harshavardhana** [comment]
> it can not run in port 9000 over http after fourth step！ @harshavardhana

You are trying to run 4 drives and then suddenly 6 drives - is not allowed.

Just run the same number of drives it will work fine.
