### ISSUE TITLE
using the API minio-go double event by deleting an object

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#10479]
Using the simple test program below:

<pre>
package main

import (
"context"
"fmt"
"log"
"github.com/minio/minio-go"
"github.com/minio/minio-go/pkg/credentials"
)

func main() {
endpoint := "127.0.0.1:9000"
accessKeyID := "test"
secretAccessKey := "n8pSsr5dlfi5sTQIoX30wLwcVo2lH0Xo"
useSSL := true

// Initialize minio client object.
minioClient, err := minio.New(endpoint, &minio.Options{
Creds: credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
Secure: useSSL,
})
if err != nil {
log.Fatalln(err)
}

opts := minio.RemoveObjectOptions{
VersionID: "",
}
err = minioClient.RemoveObject(context.Background(), "test", "in/test.txt", opts)
if err != nil {
fmt.Println(err)
return
}
}
</pre>

go run test.go
mc admin trace -a local:

15:27:36.497 [204 No Content] s3.DeleteObject 127.0.0.1:9000/test/in/test.txt 192.168.3.10      2.593ms      ↑ 77 B ↓ 226 B

webhook notify:

$ ls -l /var/lib/s3/minio-webhook 
-rwxrwx--- 1 minio minio 738 Sep 14 17:21 cf10f034-3aec-4565-8c13-fd0a306ee29f.event
-rwxrwx--- 1 minio minio 775 Sep 14 17:21 687f18cd-8a83-49b4-9306-00a1e71d2ae3.event

$ cat /var/lib/s3/minio-webhook/687f18cd-8a83-49b4-9306-00a1e71d2ae3.event
{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2020-09-14T15:21:07.459Z","eventName":"s3:ObjectRemoved:Delete","userIdentity":{"principalId":"test"},"requestParameters":{"accessKey":"test","region":"","sourceIPAddress":"192.168.3.10"},"responseElements":{"content-length":"0","x-amz-request-id":"1634AF9F8F0CFF29","x-minio-deployment-id":"b08b0774-0135-404d-a41a-0d7ca74e2caa","x-minio-origin-endpoint":"https://127.0.0.1:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"test","ownerIdentity":{"principalId":"test"},"arn":"arn:aws:s3:::test"},"object":{"key":"in%2Ftest.txt","sequencer":"1634AF9F8F25B315"}},"source":{"host":"192.168.3.10","port":"","userAgent":"MinIO (linux; amd64) minio-go/v7.0.6"}}

$ cat /var/lib/s3/minio-webhook/cf10f034-3aec-4565-8c13-fd0a306ee29f.event
{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2020-09-14T15:21:07.459Z","eventName":"s3:ObjectRemoved:Delete","userIdentity":{"principalId":"test"},"requestParameters":{"accessKey":"test","region":"","sourceIPAddress":"192.168.3.10"},"responseElements":{"x-amz-request-id":"","x-minio-deployment-id":"b08b0774-0135-404d-a41a-0d7ca74e2caa","x-minio-origin-endpoint":"https://127.0.0.1:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"test","ownerIdentity":{"principalId":"test"},"arn":"arn:aws:s3:::test"},"object":{"key":"in%2Ftest.txt","sequencer":"1634AF9F8F2325BB"}},"source":{"host":"192.168.3.10","port":"","userAgent":"MinIO (linux; amd64) minio-go/v7.0.6"}}

ps: the first have content-lenght:0

## Expected Behavior

only one event

## Regression

with minio from late August no problem at all

## Your Environment

$ minio -v 
minio version RELEASE.2020-09-10T22-02-45Z
$ cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)

**Comment by klauspost** [comment]
Potential regression from #10449 - it seems like [deleteObject is already sending the even unless it is a delete marker](https://github.com/minio/minio/blob/14b1c9f8e4459302e645717d0ad94719522eb185/cmd/object-handlers-common.go#L307) as well as the [new code](https://github.com/minio/minio/blob/f355374962387f4c0ec1a388eb986c85a2ef0a79/cmd/object-handlers.go#L2740)

**Comment by harshavardhana** [comment]
Fixed in master branch 0104af6bccce0f8fce537a713c424f4aed2041f0 - another fix to fix the original issue with delete marker is sent #10481
