### ISSUE TITLE
[working as intended] Improve documentation for MINIO_KMS_AUTO_ENCRYPTION migration

### ISSUE THREAD

**Issue by fnkr** [minio/minio#10473]
**Is your feature request related to a problem? Please describe.**

MinIO Gateway prints this error when `MINIO_KMS_AUTO_ENCRYPTION` is `on`:
```
Error: MINIO_KMS_AUTO_ENCRYPTION env is deprecated please migrate to using `mc encrypt` at bucket level
```

The deprecation was added with PR https://github.com/minio/minio/pull/10400. Now that global auto encryption is deprecated, as a Minio Gateway user, I'd like to know how to use SSE in the future. The PR also contains a documentation update:

> MinIO automatically encrypts all objects on buckets if KMS is successfully configured and bucket encryption configuration is enabled for each bucket as shown below:
> ```
> mc encrypt sse-s3 myminio/bucket/
> ```

But the command does not seem to exist:

```
# mc encrypt sse-s3 myminio/bucket/
mc: <ERROR> `sse-s3` is not a mc command. See `mc --help`.
```

I tried a similar command - which does exist - but it does not work either:

```
# mc encrypt set sse-s3 myminio/bucket/
mc: <ERROR> Unable to enable auto encryption. A header you provided implies functionality that is not implemented.
```

**Describe the solution you'd like**

Please add more details about how bucket level encryption is supposed to work to the documentation, especially regarding MinIO Gateway and S3 backends that do not support SSE.

**Additional context**

I agree with @aead's [comment in #10400](https://github.com/minio/minio/pull/10400#pullrequestreview-480581700):

> Why are we deprecating server-wide auto-encryption?
> AFAICS bucket-level encryption configuration is not a full replacement. In particular, an operator may:
> 
> - want to ensure that an entire deployment is encrypted without configuring each and every bucket separately
> - want to ensure that all objects are encrypted even when applications can create buckets and may not use / set SSE headers

Best regards

**Comment by harshavardhana** [comment]
As mentioned it's just deprecated but not removed, so please continue to use it and ignore the warnings for now. 

> ```
> # mc encrypt set sse-s3 myminio/bucket/
> mc: <ERROR> Unable to enable auto encryption. A header you provided implies functionality that is not implemented.
> ```

This is not yet supported for Gateway we will do so in time. Gateway is a lower priority for us - if you want to use the latest functionalities move to MinIO server implementation. 

> The deprecation was added with PR #10400. Now that global auto encryption is deprecated, as a Minio Gateway user, I'd like to know how to use SSE in the future. The PR also contains a documentation update:
> 

As I said the ENV is still supported and honored so ignore the warning and continue to use the way it is. When the ENV is removed completely a migration plan will be presented.
