### ISSUE TITLE
Problems with bucket lifecycle deletion policy after minio update.

### ISSUE THREAD

**Issue by sibilkov** [minio/minio#10478]
I have a small 200GB single-node minio. This minio is deployed in a kubernetes cluster. Until recently, the `imagePullPolicy: Always` kubernetes setting was not set. But the minio also did not restart for a long time. I assume that the version of the used docker image was from the April-May releases. 
Recently I have updated the nodes in the k8s-cluster, which caused the minio docker image tag/version has been updated to `RELEASE.2020-08-27T05-16-20Z`. From that moment automatic deletion of objects by lifecycle-bucket-rule stopped working for me. And also i have tried to update version to `RELEASE.2020-08-27T05-16-20Z` (this is my current version) but have no result.
There is no one lifecycle (or something like) message in logs, and I can't increase verbosity of them.
Here is bucket lifecycle policy:
```
# ./mc ilm export minio/project-bucket
{
 "Rules": [
  {
   "AbortIncompleteMultipartUpload": {},
   "Expiration": {
    "Date": "0001-01-01T00:00:00Z",
    "Days": 7,
    "DeleteMarker": false
   },
   "ID": "Delete temporary backend uploads",
   "Filter": {
    "And": {},
    "Prefix": "tmp/"
   },
   "NoncurrentVersionExpiration": {
    "NoncurrentDays": 0
   },
   "NoncurrentVersionTransition": {},
   "Status": "Enabled",
   "Transition": {
    "Date": "0001-01-01T00:00:00Z"
   }
  }
 ]
}
```

One of the old non-deleted files for example:
```
# ./mc stat minio/project-bucket/tmp/job-backend-ffd0bb.gz
Name      : job-backend-ffd0bb.gz
Date      : 2020-08-24 01:03:11 UTC 
Size      : 208 B  
ETag      : 85f33af0596a3016db107301751845ad 
Type      : file 
Expiration: 2020-09-01 00:00:00 UTC (lifecycle-rule-id: Delete temporary backend uploads) 
Metadata  :
  Content-Type: application/octet-stream 

```

Also I tried to use the older versions from May. But this way caused the minio recalculate the expiration dates for old files from the moment of restart and not from the creation date. 
And also I tried to change and recreate the lifecycle policy - no any result.
Nothing has changed except the minio version. What could have gone wrong? 
Is there a way to manually apply lifecycle policies? 

## Expected Behavior
Minio lifecycle policy deletes old files every night

## Current Behavior
Minio lifecycle policy ignores old files, nothing happening.

Thanks for your product and your time, I hope we can find a solution.

**Comment by vadmeste** [comment]
> I have a small 200GB single-node minio.

Single-node and single disk or multiple disks ?

**Comment by sibilkov** [comment]
single-disk, one persistent volume
And I can do whatever I want with the data manually (including delete) i.e. only automatic deletion by lifecycle-policy broke.

**Comment by harshavardhana** [comment]
@sibilkov please upgrade and let us know if this is fixed?

**Comment by harshavardhana** [comment]
We have made one more release - please upgrade and let us know.

**Comment by sibilkov** [comment]
@harshavardhana oh, sorry so much for latency! yes, Ive upgraded my minio to `RELEASE.2020-09-21T22-31-59Z` version and it helped. I think we can close the ticket. Thank you so much)
