### ISSUE TITLE
Minio client "mc" clashes with midnight commander "mc"

### ISSUE THREAD

**Issue by stuaxo** [minio/minio#10477]
Midnight commander is a file manager that has been around since 1994.

It's inconvenient that minio client is called "mc" as that clashes with its binary.

https://en.wikipedia.org/wiki/Midnight_Commander

**Comment by klauspost** [comment]
OK. Not sure what you expect us to do about it.

**Comment by stuaxo** [comment]
Choose a different name (or offer a default alternative symlink) since this project is the newer one ?

**Comment by alexevon** [comment]
Just a thought-

I had the same issue as I had mc (midnight commander) for years prior to
minio.  I used to create an alias such as "minio-client"  prior to moving
the "mc" binary to the /bin folder.  This worked for a long time.

**Comment by stuaxo** [comment]
This will become an issue if minio is ever going to be added to linux package managers as they already have midnight commander.

**Comment by harshavardhana** [comment]
> This will become an issue if minio is ever going to be added to linux package managers as they already have midnight commander.

We have no intention of doing that @stuaxo

**Comment by harshavardhana** [comment]
It is actually explained here https://github.com/minio/mc/blob/master/CONFLICT.md
