### ISSUE TITLE
aws s3 cp fails whereas aws s3 ls succeeds

### ISSUE THREAD

**Issue by fwessels** [minio/minio#1048]
I have uploaded a test file using 'mc cp' to a test bucket on the public server, and configured the AWS CLI according to the instructions which works correctly for the 'ls' command:

```
aws s3 ls frank/TESTFILE.txt --profile minio-play --endpoint-url https://play.minio.io:9000
```

which produces the correct result:

```
2016-01-26 13:38:40         20 TESTFILE.txt
```

However when I try to do 'cp' or 'rm' command I get an 'Invalid argument type', e.g.:

```
aws s3 cp frank/TESTFILE.txt . --profile minio-play --endpoint-url https://play.minio.io:9000
```

```
usage: aws s3 cp <LocalPath> <S3Path> or <S3Path> <LocalPath> or <S3Path> <S3Path>
Error: Invalid argument type
```

This is the profile that I am using for 'minio-play' from ~/.aws/config:

```
[profile minio-play]
region = us-east-1
s3 =
    signature_version = s3v4
```

along with these credentials from ~/.aws/credentials:

```
[minio-play]
aws_access_key_id     = PLAY
aws_secret_access_key = PASSWORD
```

Also note that an incorrect bucket or key is nicely reported back for an 'ls' command:

```
aws s3 ls frank/TESTFILE_MISSING.txt --profile minio-play --endpoint-url https://play.minio.io:9000
```

```
A client error (NoSuchKey) occurred when calling the ListObjects operation: The specified key does not exist.
```

**Comment by harshavardhana** [comment]
> aws s3 cp frank/TESTFILE.txt . --profile minio-play --endpoint-url https://play.minio.io:9000

This cp style is incorrect while the 'aws s3 ls' works without `s3://` it is expected for cp 

```
aws s3  cp s3://frank/TESTFILE.txt /tmp --endpoint-url https://play.minio.io:9000
```

Also you don't need to use credentials for https://play.minio.io:9000 it is a public server.

**Comment by fwessels** [comment]
Thanks, this fixed the issue.
