### ISSUE TITLE
Write Cache

### ISSUE THREAD

**Issue by pixie79** [minio/minio#10483]
Hi

I am not sure from the docs if this is currently possible.

I am looking to use Minio as a proxy in front of a replicated bucket for AWS and Azure. The proxy would run in distributed mode on a kubernetes cluster with versioning enabled.

Ideally I would like to be able to write a file to the minio cluster. That should then be written by minio to both the AWS and Azure buckets. If there is a cloud failure then minio should queue the write to the failing cloud for later.
Whilst the file is still being written to the backend I would like minio to be able to serve that file to other clients immediately. Thus acting as a write through cache. 

Once data has been written then normal cache rules about file access could apply, ideally fetching the file from either backend bucket. Even better if I could specify which backend by default to save on cloud egress fees.

This solution would allow for storage read and writes to be HA between cloud providers with no delay to reads after writes due to the write through caching.

Thanks

Mark

**Comment by harshavardhana** [comment]
Look at https://github.com/minio/sidekick

**Comment by pixie79** [comment]
Hi

I do not believe sidekick answers the question with is around a write through cache not a read cache. From my understanding for sidekick to work you would need to issue a GET call first. When in reality the first call will be a PUT/POST to write the file to Minio. After which Minio would write to the relevant backends whilst simultaneously serving the file from its local cache.

Regards

**Comment by alexanderankin** [comment]
I would be curious to know the answer to this question as well, @harshavardhana the general purpose load-balancer doesn't address this question, whereas a write-cache is a MinIO specific configuration question. If the answer is simply that MinIO doesnt and cant support this, this is the issue which comes up for the relevant google search, and there should be an explicit `No` answer here.
