### ISSUE TITLE
Healing is too slow / Allow admin to bump the priority for healing

### ISSUE THREAD

**Issue by dpgeekzero** [minio/minio#10497]
I have 3 beefy servers with a 10GB network between and 6 800GB SSD's in each.
After pushing 600GB of data into the cluster, I stopped a node and wiped all of the disks.
After re-adding the node, healing started, but it's extremely slow; the server is up to 54GB used after more than a day.
The servers are almost completely idle, fully dedicated to running minio.

If this was a production deployment and I lost another server while the first was rebuilding, I would be looking at downtime.

## Expected Behavior
Either healing should go faster by default or the admin should have the ability to increase healing priority.

## Current Behavior
Healing is too slow

## Your Environment
* Version: minio version RELEASE.2020-09-05T07-14-49Z
* Server: Dell PE640 w/ Hardware RAID and minio drives in passthrough mode.
* OS: Linux blockstore-02 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You can make it faster by making disk crawling speed faster https://github.com/minio/minio/tree/master/docs/config#usage-crawler

**Comment by harshavardhana** [comment]
> * Server: Dell PE640 w/ Hardware RAID and minio drives in passthrough mode.

Avoid Hardware RAID, bad deployment model for MinIO - provide us the drives directly.

**Comment by dpgeekzero** [comment]
That's what passthrough mode does.  :)
To the OS they're just normal SAS drives.

**Comment by harshavardhana** [comment]
> That's what passthrough mode does. :)
> To the OS they're just normal SAS drives.

As long as drives are separately presented as JBODs we are good.

**Comment by klauspost** [comment]
@harshavardhana FYI, This is the formatter/full drive healer managing this, so bumping crawler speed will not change it. As long as this is running the crawler will not touch these disks.

We could look into bumping the full disk rebuilder.

**Comment by harshavardhana** [comment]
> @harshavardhana FYI, This is the formatter/full drive healer managing this, so bumping crawler speed will not change it. As long as this is running the crawler will not touch these disks.
> 
> We could look into bumping the full disk rebuilder.

Okay 👌 right now there is no way looks like.

**Comment by torblerone** [comment]
So, are you planning a feature that will allow you to manually prioritize healing?
Since manual healing is marked as deprecated, I see problems for the future. In my test cluster with ~ 700,000 small objects, manual healing only took a good hour. The auto-healing should therefore be able to be prioritized higher if an admin considers it right.

**Comment by peterfroehlich** [comment]
We have exactly the same problem, but in a prod environment. 3x nodes with 3x data disks each. One of the data disks failed and the rebuild of the data takes ages. After 4 days we are on 46GB of 317GB but in that time the cluster added 16GB to each data disk of new data. So we only rebuild 30GB in 4days.
 
We have lots of small files, I guess thats the problem...? 
1.2 TiB Used, 22 Buckets, 5,869,029 Objects
9 drives online, 0 drives offline
minio version: RELEASE.2020-10-28T08-16-50

Ah, and I found no proper way to monitor the healing. Is there one? 

`mc admin heal local` report is wrong I think/hope:
Background healing status:
 ●  206401 item(s) scanned in total
 ●  Completed 14 hours 22 minutes ago
