### ISSUE TITLE
Mino doesn't work with NFS storage after update

### ISSUE THREAD

**Issue by Saddamus** [minio/minio#10493]
Hello,
After upgrading minio on kubernetes from 3 months old release, service doesn't work.
I use NFS volume provided by data center - no idea about it's settings (config flags), but until now it was working.
Pod and user that minio is running on has full rights to mounted volume. 
If i change the volume to my own NFS server, minio works properly, but i can not note any difference between working and not working volume.  Strace from the process: https://termbin.com/eja5
Any idea what is the reason ?

## Expected Behavior
Minio after helm upgrade should work with the same volume as the previous version

## Current Behavior
Minio pod starts, but web interface says that server has not been initialized

**Comment by klauspost** [comment]
Please fill out the requested information. There is no usable information here.

**Comment by harshavardhana** [comment]
> Please fill out the requested information. There is no usable information here.

Closing this issue insufficient information nothing for us to do on this.
