### ISSUE TITLE
[faq] Can't use root disk as a disk in minio distributed

### ISSUE THREAD

**Issue by alizaya** [minio/minio#10519]
Hi, I have a little problem with my cluster. I have 3 nodes and each node has 3 disks and one of the disks has os on it.
my docker-compose.yml

version: '2.4'                                                                                                                                                                        
services:                                                                                                                                                                                     
  minio_distributed:                                                                                                                                                                          
    image: registry.basalam.dev/minio/minio:RELEASE.2020-09-10T22-02-45Z                                                                                                                      
    restart: always                                                                                                                                                                           
    container_name: minio_distributed                                                                                                                                                         
    network_mode: host                                                                                                                                                                        
    volumes:                                                                                                                                                                                  
      - /mnt/minio1:/minio1                                                                                                                                                                   
      - /mnt/minio2:/minio2                                                                                                                                                                   
      - /mnt/minio3:/minio3                                                                                                                                                                   
      - ./config:/root/.minio
    command: server http://minio{1...3}/minio{1...3}

and my fstab 

/dev/sdb /mnt/minio2   xfs        noatime,defaults              0       0
/dev/sdc /mnt/minio3   xfs        noatime,defaults              0       0

logs of containers

API: SYSTEM()                                                                                                                                                 
minio_distributed    | Time: 06:32:00 UTC 09/19/2020
minio_distributed    | DeploymentID: 48c84077-db82-4156-a0a5-0d9ca1ed83c2
minio_distributed    | Error: /reloadformat "http://minio2:9000/minio/peer/v10": remote server offline
minio_distributed    |        1: cmd/background-heal-ops.go:145:cmd.healDiskFormat.func1()
minio_distributed    | All MinIO sub-systems initialized successfully
minio_distributed    | Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
minio_distributed    | Use `mc admin info` to look for latest server/disk info
minio_distributed    |  Status:         6 Online, 3 Offline. 
minio_distributed    | Endpoint:  http://192.168.200.2:9000  http://192.168.210.2:9000  http://192.168.110.0:9000  http://127.0.0.1:9000      
minio_distributed    | 
minio_distributed    | Browser Access:
minio_distributed    |    http://192.168.200.2:9000  http://192.168.210.2:9000  http://192.168.110.0:9000  http://127.0.0.1:9000      
minio_distributed    | 
minio_distributed    | Object API (Amazon S3 compatible):
minio_distributed    |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio_distributed    |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio_distributed    |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio_distributed    |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio_distributed    |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
minio_distributed    | Found drives to heal 1, proceeding to heal content...
minio_distributed    | Disk `/minio1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
minio_distributed    | Disk `http://minio2:9000/minio1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
minio_distributed    | Disk `http://minio3:9000/minio1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
minio_distributed    | 
minio_distributed    | API: SYSTEM()
minio_distributed    | Time: 06:32:08 UTC 09/19/2020
minio_distributed    | DeploymentID: 48c84077-db82-4156-a0a5-0d9ca1ed83c2
minio_distributed    | Error: Disk: /minio1 returned unformatted disk found
minio_distributed    |        endpoint=http://minio1:9000/minio1
minio_distributed    |        2: cmd/prepare-storage.go:52:cmd.glob..func5.1()
minio_distributed    |        1: cmd/background-newdisks-heal-ops.go:129:cmd.monitorLocalDisksAndHeal()
minio_distributed    | Found drives to heal 1, proceeding to heal content...
minio_distributed    | Disk `/minio1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
minio_distributed    | Disk `http://minio2:9000/minio1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
minio_distributed    | Disk `http://minio3:9000/minio1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.

**Comment by harshavardhana** [comment]
We do not allow a mix of root disk and mounted drives. Either all if them should be root disks or all of them proper drives

**Comment by alizaya** [comment]
ok if I make root disk 2 partition and then mount it it will be ok?

**Comment by harshavardhana** [comment]
> ok if I make root disk 2 partition and then mount it it will be ok?

Yes it will be okay, it cannot be the same as `/`

**Comment by alizaya** [comment]
thank you
