### ISSUE TITLE
Minio has different docker repo shas with same version

### ISSUE THREAD

**Issue by darkn3rd** [minio/minio#10523]
## Expected Behavior

The image and shas would be identical for `latest` and docker tag using that same version.

## Current Behavior

The shas are different for `minio/minio:latest` (which is `RELEASE.2020-09-17T04-49-20Z`) and `minio:minio:RELEASE.2020-09-17T04-49-20Z`

* **`minio/minio:RELEASE.2020-09-17T04-49-20Z`**
 `minio/minio@sha256:e2b7b633c2507c0a5d20f9f256f5f04c00ca6247e35b8ffb30fc1c06cfaeffaf`
* **`miniominio:latest`**: `minio/minio@sha256:3d9a4597d1d7b80d29bfe957f78e51be8bce731bf3869165a6ecf4c42ad7f166`

This is also reflected on Docker Hub: https://hub.docker.com/r/dgraph/dgraph/tags

## Possible Solution

* use the same image for both versions when they are the same, just apply a a new tag of latest and push that.

## Steps to Reproduce (for bugs)

```bash
# get release used for latest (remove carriage return form output)
RELEASE=$(docker run -ti minio/minio:latest --version | cut -d' ' -f3 | tr -d '\r')
# fetch repo sha of released used in latest
docker inspect minio/minio:$RELEASE | jq '.[].RepoDigests[0]' -r
# fetch repo sha of latest
docker inspect minio/minio:latest | jq '.[].RepoDigests[0]' -r
```

The shas are also https://hub.docker.com/r/dgraph/dgraph/tags

1. Get release used in latest: `RELEASE=$(docker run -ti minio/minio:latest --version | cut -d' ' -f3 | tr -d '\r')`
2. Using that release fetch repo digest sha from the release version: `docker inspect minio/minio:$RELEASE | jq '.[].RepoDigests[0]' -r`
3. Fetch repo digest sha from latest version `docker inspect minio/minio:latest | jq '.[].RepoDigests[0]' -r`
4. Compare to verify that these versions are the same artifact

## Context

The sha are looked at both for security and integrity of the artifact.  Many organizations with tighter change control processes (or security) have to vet artifacts before approved, which is where an artifact digest becomes important.  Outside of this, generally speaking, you can know that the software that shows that version is actually that version, as a different sha shows that it may not be.  Thus you cannot know for certain that `latest` with the version `RELEASE.2020-09-17T04-49-20Z` is really the same as the image version `RELEASE.2020-09-17T04-49-20Z`.

## Regression

* this is build process issue for minio artifacts, so no regression? 

## Your Environment
* Version used (`minio --version`): RELEASE.2020-09-17T04-49-20Z
* Server setup and configuration: docker on ubuntu
* Operating System and version (`uname -a`): PopOS (Ubuntu 19.10)
  * Linux pop-os 5.3.0-7648-generic #41~1586789791~19.10~9593806-Ubuntu SMP Mon Apr 13 17:50:40 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
All the builds here are triggered by docker hub, the container by itself are same but of course they are built separately and may be slightly off due to automated process - so this is not really a problem.

Why do you think it's a problem?

**Comment by harshavardhana** [comment]
We are not planning to push these manually that is a broken process for us, as we pretty much want this to be fully automated - 

Now the point is latest tag is just for convenience, it is not meant to be for real deployments. Real deployments should always reflect the tagged releases.

I don't think there is anything actionable here for us.
