### ISSUE TITLE
limitations of multipart upload backgroundAppend

### ISSUE THREAD

**Issue by zt-initech** [minio/minio#10521]
1. `backgroundAppend` doesn't skip parts using sparse file, so if a part is missing it is stuck until that part is uploaded.
In the worst case, imagine a 50GB upload of 10,000 5MB parts, in which the first part is uploaded last. No almost complete file will be ready in tmp directory, after the last part (part number 1) is uploaded the "complete multipart upload" command will take a long time.
Why not let `backgroundAppend` seek 5MB and fill in the parts that are available?

2. When a part is replaced (upload-part with same part number but different content and hence different etag), `backgroundAppend` doesn't know and the file in tmp is not updated. Yes, it can turn out that `CompleteMultipartUpload` will be asked to use the older part content (by etag), but most likely case is that the newer part content will be needed. `backgroundAppend` always uses the first (by etag) file for each part number. If the part that was uploaded later is the one with the greater etag, the tmp file will be wrong and `CompleteMultipartUpload` will be in the `appendFallback` case, which for large files will be very slow. Why not let `PutObjectPart` inform `backgroundAppend` to update the part in the tmp file? A part can be updated in-place if it's the same size or if it's the last appended part, that would be very efficient. If some parts need to be "moved", it's not as efficient, but still more efficient than starting from the beginning during `CompleteMultipartUpload` when it turns out the file in tmp is wrong.

3. The value in `appendFileMap` is not persisted across minio restart, so when minio is restarted it deletes the file in tmp prepared by `backgroundAppend` and needs to start from scratch. For large uploads, this is terrible for performance. Why not persist the value in `appendFileMap` on disk, together with the MPU metadata?

**Comment by harshavardhana** [comment]
If you have a solution feel free to send us, this is best possible solution for now while keeping things sane for FS backend

- a single contiguous file at the backend (no special tooling needed to read from the backend)
- supports variadic part sizes (as per AWS S3 spec)

If these are not necessary for you then you should look at using erasure coded backend which is more suitable for more high performant applications.

There is nothing more actionable at this point, feel free to send a fix if you know a better way while making sure to support the aforementioned requirements of single drive/FS backend.
