### ISSUE TITLE
Nested array query does not work as expected in S3 Select

### ISSUE THREAD

**Issue by karthikseshadri** [minio/minio#10526]
Given a file with each line as a json array, query on them does not work as expected. The same works fine in AWS S3.

Example: gzip compressed file with content as below

[{"text":"sample message 1"}]
[{"text":"sample message 2"}]

Executed the below query.

`select * from S3Object[*][*] s3 where s3.text like 'sample%'`

## Expected Behavior
Both the records should be returned in the response.

## Current Behavior
Getting an error "Encountered an error parsing the JSON file: unexpected json type below root :array. Check the file and try again."

## Your Environment
* Using "minio/minio" as a TestContainer in junit tests.

**Comment by klauspost** [comment]
We current only support objects as values.
