### ISSUE TITLE
[not our bug] Minio not starting in distributed mode

### ISSUE THREAD

**Issue by AbdullahAlhulwah** [minio/minio#10527]
Hi everyone,

I'm currently trying to setup minio cluster on AWS. I am using 4 nodes each node has one disk. These are the steps that have been done:

- Created a file system then mounted the disk on /data directory on all nodes.
- Installed minio and mc on all nodes.
- Created environment file with access key and secret key on all nodes.
- Changed the permission on /data directory on all nodes.

And then I tried to run minio on all nodes. So I ran the following command on all nodes at the same time:

/usr/local/bin/minio server http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data

But minio doesn't start at any of the node.
The first node displays : Following servers are currently offline or unreachable [http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data]
And the other nodes display: Waiting for a minimum of 2 disks to come online (elapsed 1m1s)

Note that I tried:
- Running NTP
- Disabling the firewall
- Made sure that port 9000 is open

I need to know what is the cause of this and how to fix it. Thanks.

**Comment by harshavardhana** [comment]
> /usr/local/bin/minio server http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data
> 
> But minio doesn't start at any of the node.
> The first node displays : Following servers are currently offline or unreachable [http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data]

Your DNS doesn't resolve? why are you specifying the command line like this why not?

```
minio server http://minio-{1...4}:9000/data
```

**Comment by AbdullahAlhulwah** [comment]
> > /usr/local/bin/minio server http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data
> > But minio doesn't start at any of the node.
> > The first node displays : Following servers are currently offline or unreachable [http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data]
> 
> Your DNS doesn't resolve? why are you specifying the command line like this why not?
> 
> ```
> minio server http://minio-{1...4}:9000/data
> ```

Thank you for the fast response. I am actually now using the ip address instead of "minio-*" to avoid any problems that can occur from hostnames. The IP addresses are not consecutive so  I cannot do it the way you mentioned. But shouldn't it behave the same  way regardless of the command format ?

**Comment by harshavardhana** [comment]
> Thank you for the fast response. I am actually now using the ip address instead of "minio-*" to avoid any problems that can occur from hostnames. The IP addresses are not consecutive so I cannot do it the way you mentioned. But shouldn't it behave the same way regardless of the command format ?

We recommend using ellipses, single args on command have been deprecated while you can still use them. They simply cannot communicate AFAICS.

**Comment by harshavardhana** [comment]
AFAICS this is purely a setup issue on your end, please join us on https://slack.min.io to help you out more. There is no issue here AFAICS.
