### ISSUE TITLE
Cannot create a bucket policy with a "s3:*" action

### ISSUE THREAD

**Issue by blackandred** [minio/minio#10538]
I would like to create any policy with `s3:*` action instead of specifying all actions in order.

## Expected Behavior
The policy should pass.

## Current Behavior
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedPolicy</Code><Message>unsupported action &#39;s3:*&#39;</Message><BucketName>2d23b0a9-0714-433c-a92b-6310e4037aa9</BucketName><Resource>/2d23b0a9-0714-433c-a92b-6310e4037aa9</Resource><RequestId>1636B5A1175C3553</RequestId><HostId>be77e072-6942-4077-a543-8d9340d8e5ad</HostId></Error>
```

## Possible Solution
Allow to create such policy :)

## Steps to Reproduce (for bugs)
1. Create a bucket "2d23b0a9-0714-433c-a92b-6310e4037aa9"
2. Send an example, simplest policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Example",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::2d23b0a9-0714-433c-a92b-6310e4037aa9/*",
                "arn:aws:s3:::2d23b0a9-0714-433c-a92b-6310e4037aa9"
            ]
        }
    ]
}
```

## Context
-

## Regression
-

## Your Environment

* Client: aws-sdk-php/3.154.4
* Version used (`minio --version`): RELEASE.2020-09-17T04-49-20Z
* Server setup and configuration: Official docker container
* Operating System and version (`uname -a`): `Linux riotkit-ops 5.4.60-2-MANJARO #1 SMP PREEMPT Sat Aug 22 14:35:41 UTC 2020 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "Example",
>             "Effect": "Allow",
>             "Action": "s3:*",
>             "Resource": [
>                 "arn:aws:s3:::2d23b0a9-0714-433c-a92b-6310e4037aa9/*",
>                 "arn:aws:s3:::2d23b0a9-0714-433c-a92b-6310e4037aa9"
>             ]
>         }
>     ]
> }

For bucket policies we do not support `s3:*` @blackandred  it is only allowed with IAM policies. For bucket policies you need to provide all actions.

**Comment by blackandred** [comment]
@harshavardhana Thanks for ultra-quick answer. Good to know :slightly_smiling_face:

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for ultra-quick answer. Good to know 🙂

We may add it in future, but since bucket policies in MinIO are meant for anonymous access only, we restricted this behavior to avoid any unexpected calls exposed.

**Comment by kannappanr** [comment]
@blackandred Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further questions
