### ISSUE TITLE
[working as intended] Failed to get the correct bucket list via 'mc ls <hostname>'

### ISSUE THREAD

**Issue by yangwwii** [minio/minio#10537]
I deployed a distributed minio with replica=4. there are 4 disks when starting minio server.
By mc CLI commands, I created three buckets,
mc mb abc/viola1
mc mb abc/viola2
mc mb abc/viola3

Then deleted one buckets in pod0/export/ directly to make the buckets inconsistent among disks
kubectl exec -it minio-0 -- rm -rf export/viola1

The problem is, it's observed that it has almost 25% chances to get the wrong bucket list when I executed 'mc ls abc'

From the minio code, the minio pod receives request only get the bucket list from one random disk. Is it reasonable to get the buckets list from all the disks and merge them in case there is inconsistent buckets list on disks?

There're the possibility that bucket is failed to create on one disk due to network issue or etc. in this case, the bucket only exists on the other disks and can't be healed automatically to the disk recovered from network issue.

cmd\xl-sets.go
// List all buckets from one of the set, we are not doing merge
// sort here just for simplification. As per design it is assumed
// that all buckets are present on all sets.
func (s *xlSets) ListBuckets(ctx context.Context) (buckets []BucketInfo, err error) {
    // Always lists from the same set signified by the empty string.
    return s.getHashedSet("").ListBuckets(ctx)
}
cmd\xl-v1-bucket.go
// listBuckets - returns list of all buckets from a disk picked at random.
func (xl xlObjects) listBuckets(ctx context.Context) (bucketsInfo []BucketInfo, err error) {
    for _, disk := range xl.getLoadBalancedDisks() {
        volsInfo, err = disk.ListVols()
        if err == nil {
            // NOTE: The assumption here is that volumes across all disks in
            // readQuorum have consistent view i.e they all have same number
            // of buckets. This is essentially not verified since healing
            // should take care of this.
            **return bucketsInfo, nil**

## Expected Behavior
it's expected to get the complete bucket lists no matter that which disk minio get the buckets list from 

## Current Behavior
mc ls abc/
[2020-09-21 08:31:47 UTC]      0B viola2/
[2020-09-21 08:31:48 UTC]      0B viola3/

**Comment by harshavardhana** [comment]
Purging directly on the backend is not supported, such type of corruptions cannot be handled.

Healing kicks in around 5-10mins which heals the bucket automatically. If you upload an object to the bucket that bucket is always available.

ListBuckets is not quorum based so you will see it not available for the moment.

**Comment by yangwwii** [comment]
@harshavardhana, regarding to 'Healing kicks in around 5-10mins which heals the bucket automatically.'

> Purging directly on the backend is not supported, such type of corruptions cannot be handled.
> 
> Healing kicks in around 5-10mins which heals the bucket automatically. If you upload an object to the bucket that bucket is always available.
> 
> ListBuckets is not quorum based so you will see it not available for the moment.

@harshavardhana  thanks for your information. Yes, I agree "directly purge" doesn't happen often. We really saw the buckets inconsistent in our run-time (not doing any bucket purge) and it didn't get healing automatically unfortunately. We don't sure what trigger this. We are interested with the auto heading you have mentioned, but how to build the inconsistent buckets in local test bed?  
Regarding to "Healing kicks in around 5-10mins which heals the bucket automatically", if it's a flexible time for recovery, what's the maximum time does it take for bucket auto-healing.

And, in spite of the bucket is missing on disk0, I can upload, download and list objects in this bucket, the object list can be handled due to it merge the object info among disks. Kindly please correct me if i made miss-understanding.

I'm not quite clear about "If you upload an object to the bucket that bucket is always available." do you mean the uploading object action will trigger the bucket healing on disk?
