### ISSUE TITLE
[faq] Prometheus metrics export contains wrong values for disk metrics

### ISSUE THREAD

**Issue by juv** [minio/minio#10539]
Prometheus metrics export contains wrong values for disk metrics.

Minio prometheus exporter shows a value of e.g. `530857984000` but while running the  `df` command a totally different value is shown (e.g. minio shows 531 GB, df -h shows 494.4 GB)

## Expected Behavior
MinIO disk metrics and `df` matches

## Current Behavior
MinIO reports higher values for all disk_ metrics than the operating system.
I've wondered if MinIO reports the values in e.g. kibibyte rather than kilobyte but that does not seem to be the case? 

## Steps to Reproduce (for bugs)
1. Access MinIO metrics endpoint under /minio/prometheus/metrics
2. Note values of disk_storage_total, disk_storage_used, disk_storage_available
3. Run `df` (`df -h`) command for the volume that MinIO is using for storing the data
4. Compare the values, they don't match

## Context
MinIO storage alerts in Prometheus are not correct

## Your Environment
* Version used (`minio --version`): RELEASE.2020-07-22T00-26-33Z
* Server setup and configuration: MinIO NAS gateway (GlusterFS backend), Kubernetes
* Operating System and version (`uname -a`): Linux prod-minio-86677c897d-qcprp 3.10.0-957.46.1.el7.x86_64 #1 SMP Wed Jan 15 08:14:48 EST 2020 x86_64 Linux

**Comment by harshavardhana** [comment]
> 1. Access MinIO metrics endpoint under /minio/prometheus/metrics
> 2. Note values of disk_storage_total, disk_storage_used, disk_storage_available
> 3. Run `df` (`df -h`) command for the volume that MinIO is using for storing the data
> 4. Compare the values, they don't match

The value here is obtained based on the blockSize on the disk @juv `df -h` on GlusterFS may not be the same as what is returned from the systemcall `statvfs` 

This is not our issue @juv

**Comment by harshavardhana** [comment]
Ah you are mistaken @juv `530857984000` is indeed 494GiB returned by `df -h` we return in bytes you are supposed to convert that into IEC representation which is returned by `df -h`
