### ISSUE TITLE
[fixed] If we set bucket quota, we cannot upload files in to the bucket

### ISSUE THREAD

**Issue by mohandass-pat** [minio/minio#10548]
Hi, 
We have enabled bucket quota with 64Mib. But if I upload a 5 Mib it will not allow me to upload files into that. It returns 503 error. We cannot upload a single file into the quota enabled bucket

**Comment by klauspost** [comment]
You don't really provide much information.

Hard quota limits are using the totals from the crawler, which updates at most every 5 minutes, but depending on your cluster size usually slower.

The system is not designed to operate that close to the limit, so I propose you set a limit you are less likely to hit.

**Comment by mohandass-pat** [comment]
Actually, Our requirement is to create a bucket with a specific storage size. For Ex, If there is a bucket with a storage size of 500 MB, If we upload a file more than 500MB it should throw the error as the storage limit exceeds. Our assumption is with Bucket Quota we can achieve that.

**Comment by klauspost** [comment]
@mohandass-pat Fixed via #10551

**Comment by mohandass-pat** [comment]
I updated to the latest Minio Version. Now I can upload files to quota enabled bucket. But now there is another issue. It is allowing to upload files into buckets even after the limit is reached.
I used this command, 
`mc admin bucket quota minio/demo-quota --hard 50 MB` to set bucket quota.

Then I uploaded files more than 50 MB. It was not throwing any errors. It allows for uploading more files.

**Comment by harshavardhana** [comment]
> I updated to the latest Minio Version. Now I can upload files to quota enabled bucket. But now there is another issue. It is allowing to upload files into buckets even after the limit is reached.
> I used this command,
> `mc admin bucket quota minio/demo-quota --hard 50 MB` to set bucket quota.
> 
> Then I uploaded files more than 50 MB. It was not throwing any errors. It allows for uploading more files.

Yes it will until crawling catches up, its not instantaneous quota @mohandass-pat
