### ISSUE TITLE
[resolved] Summary: Blank bucket when node is down on 3-node, 12-disk cluster on FreeBSD

### ISSUE THREAD

**Issue by rbadass** [minio/minio#10545]
After successfully uploading files to a bucket, then taking a single node down out of a 3-node cluster (each having 4 disks each), the bucket is blank. No files are listed via the web browser or the minio-client. Buckets are listed, but they are blank.
Cannot reproduce this behaviour on Linux.

## Expected Behavior

Files should be listable and readable even when a single node is down.

## Current Behavior

The bucket is blank, when it should be returning files.
minio-client ls myminio/bucket --debug results in HTTP/1.1 200 OK, however the listing is BLANK
Brining the node up again shows all the files again. Bringing down any other node results in the bucket being blank again, as long as 1 node is down the bucket is blank.

## Steps to Reproduce (for bugs)

1. Create a distributed cluster of 3 nodes with 4 disks each
2. Upload a file to a bucket in the cluster
3. Take down a single node
4. Try to list files in the bucket

One important difference I noted between Linux and FreeBSD was the following output when the node was down. Here it is on FreeBSD - it says there are 0 drives offline, where on Linux it will say 4 drives offline.

_  node2:9000
   Uptime: offline
 
_  node3:9000
   Uptime: 2 minutes 
   Version: 2020-09-10T22:02:45Z
   Network: 2/3 OK 
   Drives: 4/4 OK 
 
_  node1:9000
   Uptime: 3 minutes 
   Version: 2020-09-10T22:02:45Z
   Network: 2/3 OK 
   Drives: 4/4 OK 
 
8 drives online, 0 drives offline

## Your Environment

* Version used (`minio --version`): minio from FreeBSD latest packages (minio-2020.09.10.22.02.45)
* Server setup and configuration: I am running each node as a jail, however the same behaviour was observed with separate machines. Have tried on both UFS and ZFS with no differences.
* Operating System and version (`uname -a`): FreeBSD amd64 12.1

**Comment by harshavardhana** [comment]
> ## Current Behavior
> The bucket is blank, when it should be returning files.
> minio-client ls myminio/bucket --debug results in HTTP/1.1 200 OK, however the listing is BLANK
> Brining the node up again shows all the files again. Bringing down any other node results in the bucket being blank again, as long as 1 node is down the bucket is blank.

You need to use latest release @rbadass to avoid non-quorum based listing.

**Comment by jam-34** [comment]
Wouldn't 2/3 of the nodes being online make it a quorum?  If it were a larger cluster with say 5 out of 6 online would this have been functioning properly in the pre-Sept 23rd release?

**Comment by harshavardhana** [comment]
Fixed by #10555
