### ISSUE TITLE
Env variables ignored

### ISSUE THREAD

**Issue by englm** [minio/minio#10541]
I'm trying to pass region name and storage classes via environment variables in minio docker container and it seems that the variables are ignored.
Also tried a similar setup without docker and getting the same results.

## Expected Behavior
The configuration values should be set as defined in the environment variables.

## Current Behavior
The minio config parameters remains at the default values/empty
`root@minio01:~# mc admin config export local/`
`region name=`
`storage_class standard= rrs=EC:2`

Env values are set as desired:
`root@minio01:~# docker exec -it minio /bin/sh`
`/ # set`
`[..]`
`MINIO_ACCESS_KEY='admin'`
`MINIO_ACCESS_KEY_FILE='access_key'`
`MINIO_KMS_MASTER_KEY_FILE='kms_master_key'`
`MINIO_REGION_NAME='my-region'`
`MINIO_SECRET_KEY='myPassword'`
`MINIO_SECRET_KEY_FILE='secret_key'`
`MINIO_SSE_MASTER_KEY_FILE='sse_master_key'`
`MINIO_STORAGE_CLASS_RRS='EC:2'`
`MINIO_STORAGE_CLASS_STANDARD='EC:3'`
`MINIO_UPDATE='off'`
`[..]`

## Steps to Reproduce (for bugs)

1. `docker run -d -p 9000:9000 --name minio \`
`-v /srv/minio-data1:/data1 \`
`-v /srv/minio-data2:/data2 \`
`-v /srv/minio-data3:/data3 \`
`-v /srv/minio-data4:/data4 \`
`-v /srv/minio-data5:/data5 \`
`-v /srv/minio-data6:/data6 \`
`-v /srv/minio-data7:/data7 \`
`-v /srv/minio-data8:/data8 \`
`-v /srv/minio-data9:/data9 \`
`-v /srv/minio-data10:/data10 \`
`-e "MINIO_REGION_NAME=my-region" \`
`-e "MINIO_ACCESS_KEY=admin" \`
`-e "MINIO_SECRET_KEY=myPassword" \`
`-e "MINIO_STORAGE_CLASS_STANDARD=EC:3" \`
`-e "MINIO_STORAGE_CLASS_RRS=EC:2" \`
`minio/minio server /data{1...10}`

## Your Environment

* Version used (`minio --version`): `RELEASE.2020-09-21T22-31-59Z`
* Server setup and configuration: see Steps to Reproduce
* Operating System and version (`uname -a`): `Linux 3752df957496 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 Linux`

**Comment by harshavardhana** [comment]
ENV is automatically honored, `mc admin config` only displays what is present and set on the config on the disk only.

This is working as expected, we plan to add support for displaying `mc admin config` for env in future
