### ISSUE TITLE
Bulk removal of records does not remove rows in namespace postgres table

### ISSUE THREAD

**Issue by caryfitzhugh** [minio/minio#10553]
We have a system which has notify_postgres set up, queue_length is 50k, type is 'namespace'.
The events for put / delete are on a bucket, pointing at that postgres database.

It has all seemed to work well, but recently when we ran ```mc rm --recursive --force minio/bucket/2000/05/```
it removed over 5000 records. 

The database did not have all of the files removed though.  

```
SELECT COUNT(*) FROM minio_files WHERE key LIKE 'bucket/2020/05/%'
```

still returns thousands of rows in the database. :(   

Smaller tests seem to succeed (deleting a sub-folder of < 10 records worked).

Watching ```mc admin trace --errors``` shows nothing unusual.

## Expected Behavior

When I delete a record in minio, and have namespace postgres notifications set up, the row in the db should be deleted.
Or - if there is an issue storing the record, it should be logged at the least, and retried ideally.

Would be fantastic if there was a way to 'sync' the notification table with what's in the system.  (even if there is no event, just add the record to postgres, and the data field is blank, or something).

## Current Behavior

When deleting records with mc --recursive, the postgres database rows are not removed from the pg table.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We need the minio pg namespace table to be an accurate reflection of the contents of the minio system.  This is concerning.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

version is minio/minio:RELEASE.2020-08-13T02-39-50Z
postgres version is PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit

**Comment by caryfitzhugh** [comment]
Just ran it on another path.  Results are as follows:

| Records in DB      | Description |
| ----------- | ----------- |
| 3080      | Prior to deletion on prefix 2020/05/%      |
| 2117   | After deletion on prefix 2020/05/%        |

counting the logs from the ```mc rm --recursive``` showed 3087 lines. so maybe writing the records also has bugs?

**Comment by caryfitzhugh** [comment]
Last one for now...  

Just ran it on another path.  Results are as follows:

| Records in DB      | Description |
| ----------- | ----------- |
| 2869      | Prior to deletion on prefix 2020/05/03/%      |
| 1607   | After deletion on prefix 2020/05/03/%        |

counting the logs from the ```mc rm --recursive``` showed 2872 lines. so maybe writing the records also has bugs?

I saved off all the admin trace logs (--all) this time as well.  Did not see any errors, nor did I see any log messages referencing those files that were deleted (which seemed odd, I figured I would see DeleteObject logs).  However the files are definitely gone from MinIO.

**Comment by caryfitzhugh** [comment]
Concerned a little bit that fixing it with multiple connections may mask an underlying issue where notifications are dropped.
I had believed that the system should never lose a notification.  I had assumed from the parameters, that queue_limit was a list that provided consistency - you would not lose a notification as long as the queue_limit was not reached.

What is the behavior of queue_limit and the postgres_notifier if the DB is slow, down, rebooting, etc?

**Comment by Praveenrajmani** [comment]
The problem we had was that the bulk delete would produce bulk events at once. The pg client had to open connections in bulk at once. Which may exceed the maximum connection limit. So, By setting the max open connections limit the client would just use limited open connections and the rest of the deletes would just wait for the connection and get served instead of opening multiple parallel connections and exhausting the limit.

The queue_dir would just store the events and replays it to the target. And keep on retrying the event if the event transit fails due to connection errors. The event in the store gets deleted only after a successful transit to the target. The errors would be logged once in the server console.
