### ISSUE TITLE
The problem of dilatation

### ISSUE THREAD

**Issue by thewholeworld** [minio/minio#10566]
Hi, I have some capacity expansion problems. At present, I have completed the first expansion. The expansion command is shown in the figure. Now I want to expand the capacity for the second time. According to the instructions in the document, the startup command is like this, but there is no output after executing the startup program. What is the problem?
![image](https://user-images.githubusercontent.com/41433762/94245480-e30b7e00-ff4c-11ea-99ab-13adf2b35ed1.png)
![image](https://user-images.githubusercontent.com/41433762/94245528-f0c10380-ff4c-11ea-838f-cb23e5947107.png)
What is the problem?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
@thewholeworld Please fill out the requested information.

**Comment by kannappanr** [comment]
please try `./minio server http://192.168.43.{5...6}/data{1...2} http://192.168.43.{7...8}/data{1...2} http://192.168.43.{20...25}/data{1...2}`

You cannot combine two zones into a single zone. Please reach out to us at https://slack.min.io for further questions like this

**Comment by thewholeworld** [comment]
> 请试试 `./minio server http://192.168.43.{5...6}/data{1...2} http://192.168.43.{7...8}/data{1...2} http://192.168.43.{20...25}/data{1...2}`
> 
> 您不能将两个区域合并为一个区域。请通过https://slack.min.io与我们联系，以获取更多类似的问题

Hi, I started it according to your command, but if machine A starts, then machine B starts, machine A will exit. Starting B first and then starting A will encounter the same situation.

**Comment by harshavardhana** [comment]
> Hi, I started it according to your command, but if machine A starts, then machine B starts, machine A will exit. Starting B first and then starting A will encounter the same situation.

All nodes need to have the same command line and they should be separate hosts. Things to check

- Fresh drives not used previously in any deployment
- Check permissions on all drives if MinIO can write to
- Check if ports are open.

**Comment by thewholeworld** [comment]
> > 嗨，我根据您的命令启动了它，但是如果机器A启动了，那么机器B启动了，机器A将退出。首先启动B，然后启动A会遇到相同的情况。
> 
> 所有节点都必须具有相同的命令行，并且它们应该是单独的主机。检查事项
> 
> * 以前未在任何部署中使用的新驱动器
> * 如果MinIO可以写入所有驱动器，请检查其权限
> * 检查端口是否打开。

Hi, I have confirmed your question. The startup commands of the eight nodes are the same, and they are all separate hosts. They are all newly attached hard disks. The ports are also opened. The details are shown in the figure
![image](https://user-images.githubusercontent.com/41433762/94358826-3d841600-00d6-11eb-96db-94d6ced90e03.png)
![image](https://user-images.githubusercontent.com/41433762/94358843-64dae300-00d6-11eb-8a23-c88049f0ab8c.png)

**Comment by thewholeworld** [comment]
Start the script command as follows：
#!/bin/bash
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin123

./minio server http://192.168.43.{5...6}/data{1...2} http://192.168.43.{7...8}/data{1...2} http://192.168.43.{20...23}/data{1...2}

**Comment by thewholeworld** [comment]
Configuration of another machine：
![image](https://user-images.githubusercontent.com/41433762/94359042-62c55400-00d7-11eb-820c-c4327063adc5.png)
![image](https://user-images.githubusercontent.com/41433762/94359066-812b4f80-00d7-11eb-8d37-b2c9c20d132f.png)

**Comment by thewholeworld** [comment]
The starting command of the other machine is as follows:
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin123

./minio server http://192.168.43.{5...6}/data{1...2} http://192.168.43.{7...8}/data{1...2} http://192.168.43.{20...23}/data{1...2
