### ISSUE TITLE
[working as intended] Supporting custom jwt claims

### ISSUE THREAD

**Issue by UchihaYuki** [minio/minio#10564]
I'm using keycloak and minio now. I think supporting custom jwt claims is necessary.

The only way I can control user access is through policy claim, which means I have to assign different policies to different users. For customer-facing applications, the state of users might change, for example, if a user buys a vip membership for a month, the user will get more access to minio then get less after a month. I can achieve this easily by use a custom jwt claims, jwt:vip=time-when-vip-expires, without it I have to traverse through user database to update policy for them daily, even hourly if I'd like to get more accurate control.

**Comment by harshavardhana** [comment]
@UchihaYuki 

Already long supported 

```
~ mc admin config set play/ identity_openid 
KEY:
identity_openid  enable OpenID SSO support

ARGS:
config_url*   (url)       openid discovery document e.g. "https://accounts.google.com/.well-known/openid-configuration"
client_id     (string)    unique public identifier for apps e.g. "292085223830.apps.googleusercontent.com"
claim_name    (string)    JWT canned policy claim name, defaults to "policy"
claim_prefix  (string)    JWT claim namespace prefix e.g. "customer1/"
scopes        (csv)       Comma separated list of OpenID scopes for server, defaults to advertised scopes from discovery document e.g. "email,admin"
comment       (sentence)  optionally add a comment to this setting
```

```
~ mc admin config set play/ identity_openid  --env
KEY:
identity_openid  enable OpenID SSO support

ARGS:
MINIO_IDENTITY_OPENID_CONFIG_URL*   (url)       openid discovery document e.g. "https://accounts.google.com/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID     (string)    unique public identifier for apps e.g. "292085223830.apps.googleusercontent.com"
MINIO_IDENTITY_OPENID_CLAIM_NAME    (string)    JWT canned policy claim name, defaults to "policy"
MINIO_IDENTITY_OPENID_CLAIM_PREFIX  (string)    JWT claim namespace prefix e.g. "customer1/"
MINIO_IDENTITY_OPENID_SCOPES        (csv)       Comma separated list of OpenID scopes for server, defaults to advertised scopes from discovery document e.g. "email,admin"
MINIO_IDENTITY_OPENID_COMMENT       (sentence)  optionally add a comment to this setting
```

Read the docs.

**Comment by UchihaYuki** [comment]
But I still can't use custom claims.
when I run
`mc admin policy add local vip vip.json `
I get
`mc.exe: <ERROR> Unable to parse the input policy: invalid condition key 'jwt:vip'.`
The content of vip.json
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::vip/*"
            ],
            "Condition": {
                "DateGreaterThan": {
                    "jwt:vip": "${aws:CurrentTime}"
                }
            }
        }
    ]
}
```

**Comment by harshavardhana** [comment]
> But I still can't use custom claims.
> when I run
> `mc admin policy add local vip vip.json `
> I get
> `mc.exe: <ERROR> Unable to parse the input policy: invalid condition key 'jwt:vip'.`
> The content of vip.json
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "s3:GetObject",
>                 "s3:PutObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::vip/*"
>             ],
>             "Condition": {
>                 "DateGreaterThan": {
>                     "jwt:vip": "${aws:CurrentTime}"
>                 }
>             }
>         }
>     ]
> }
> ```

That's not how you use it again read the docs please or join our https://slack.min.io for more questions https://github.com/minio/minio/blob/master/docs/multi-user/README.md#policy-variables

**Comment by UchihaYuki** [comment]
I have read the doc, and it says
`If the user is authenticating using an STS credential which was authorized from OpenID connect we allow all jwt:* variables specified in the JWT specification, **custom jwt:* or extensions are not supported.**`
But in my case, I need custom jwt. If I can't use custom jwt, I have to do lots of work to achieve the same effects.

**Comment by harshavardhana** [comment]
> have read the doc, and it says
> `If the user is authenticating using an STS credential which was authorized from OpenID connect we allow all jwt:* variables specified in the JWT specification, **custom jwt:* or extensions are not supported.**`
> But in my case, I need custom jwt. If I can't use custom jwt, I have to do lots of work to achieve the same effects.

Yeah for now its not possible - dynamic values like this are not possible to add easily. We may add it in the future but for now its very low priority.

**Comment by harshavardhana** [comment]
If you are interested feel free to send a patch yourself we will be happy to review and accept the code @UchihaYuki
