### ISSUE TITLE
always waiting for the first server to format the disks

### ISSUE THREAD

**Issue by kkangkang789** [minio/minio#10577]
i want to use erasure-coding, when i use following command-line
./minio server http://xx.xxx.xxx.34/home/test/data1 \
> http://xx.xxx.xxx.42/home/test/data1 \
> http://xx.xxx.xxx.68/home/test/data1 \
> http://xx.xxx.xxx.131/home/test/data1

the first disk always Waiting for all other servers to be online to format the disks, other disk waiting for the first server to format the disks.

finally 

i don't quite understand the instructions
export MINIO_ACCESS_KEY=<ACCESS_KEY>
export MINIO_SECRET_KEY=<SECRET_KEY>
minio server http://host{1...n}/export{1...m} http://host{o...z}/export{1...m}
can you give me an example?

thanks a lot

**Comment by harshavardhana** [comment]
> the first disk always Waiting for all other servers to be online to format the disks, other disk waiting for the first server to format the disks.
> 
> finally
> 
> i don't quite understand the instructions
> export MINIO_ACCESS_KEY=<ACCESS_KEY>
> export MINIO_SECRET_KEY=<SECRET_KEY>
> minio server [http://host{1...n}/export{1...m}](http://host%7B1...n%7D/export%7B1...m%7D) [http://host{o...z}/export{1...m}](http://host%7Bo...z%7D/export%7B1...m%7D)
> can you give me an example?

they need to be able to

- speak to each other on the IP
- ports need to be open by default runs on port 9000
- 3 nodes are sufficient for MinIO - the minimum required is 4 nodes or 4 drives.

**Comment by kkangkang789** [comment]
thanks ,  i found that the disk was not cleaned .

the last question, what is the reason for using the TCP6 protocol
