### ISSUE TITLE
[working as intended] Bucket policy does not work

### ISSUE THREAD

**Issue by nagikami** [minio/minio#10578]
when I set the policy on the bucket, it does not work.
## Expected Behavior

when I set the policy on the bucket, it works.

## Current Behavior

when I set the policy on the bucket, it does not work.

## Possible Solution

I find the following code in auth-handler.go:
if cred.AccessKey == "" {
		if globalPolicySys.IsAllowed(policy.Args{
			AccountName:     cred.AccessKey,
			Action:          policy.Action(action),
			BucketName:      bucketName,
			ConditionValues: getConditionValues(r, "", "", nil),
			IsOwner:         false,
			ObjectName:      objectName,
		}) {
			return ErrNone
		}
		return ErrAccessDenied
	}
I guess the accesskey should not be empty, and the policy verification will not be executed. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2020-09-23T19-18-30Z
* Server setup and configuration:
* Operating System and version (`uname -a`): 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Bucket policies in MinIO are meant for Anonymous users i.e AccessKey is empty. If you want user-level policies look at `mc admin policy` command.
