### ISSUE TITLE
[HDFS gateway] getting error with any hdfs bucket

### ISSUE THREAD

**Issue by jojodaser** [minio/minio#10585]
## Expected Behavior

Should list bucket

## Current Behavior

![image](https://user-images.githubusercontent.com/18657819/94526003-743d6600-0267-11eb-98f8-cd4947ee2e61.png)
getting error with any bucket

## Steps to Reproduce (for bugs)

1.  run minIO gateway for HDFS storage with override the namenode 
```
    export MINIO_ACCESS_KEY=minio
    export MINIO_SECRET_KEY=minio123
    minio gateway hdfs hdfs://namenode:8020
```

## Your Environment

* Version used (`minio --version`): RELEASE.2020-09-26T03-44-56Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux sparknode 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Just tested with a local HDFS setup, seems to be working fine. Looks like the user you are running `minio gateway hdfs` with does not have proper access for these directories. 

Closing this as setup issue.
