### ISSUE TITLE
[faq] minio replication

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10589]
**Is your feature request related to a problem? Please describe.**
I have deployed minio 4 nodes in production and DR site.  I have enabled the replication between source and destination bucket level while executing below command on production node 1
./mc admin bucket remote add minio-prod1/test-prod http://testdr:5c31ad832d8c911f0176e86a4be1cbc9@drserver1:9001/test-dr --service replication

./mc replicate add minio-prod1/test-prod --priority 1 --arn "arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-prod" --storage-class "STANDARD" --remote-bucket "test-dr"

**Describe the solution you'd like**
i would like to know do i need to execute command  for all the nodes in my production site to enable replication to DR. If not one node to node replication is sufficient and what are the best approach 

**Describe alternatives you've considered**

If one of the production node is down where i enabled the replication ( run above command), meanwhile someone updated the bucket and its not replicating to DR site and how can i resolve this issue.

**Additional context**

**Comment by poornas** [comment]
@LiginGeorge , 
>i would like to know do i need to execute command for all the nodes in my production site to enable replication to DR. If not one node to node replication is sufficient and what are the best approach

No, running it just once is sufficient.

>If one of the production node is down where i enabled the replication ( run above command), meanwhile someone updated the bucket and its not replicating to DR site and how can i resolve this issue.

Even when a node is down, uploads to other nodes for this bucket would replicate. When DR site goes down, replication failures will be retried and healed automatically. 

You might want to join https://slack.min.io for answers to general questions.

**Comment by LiginGeorge** [comment]
I enabled the replication from production one node to DR one node.  After that i powered off that production node and updated bucket with few data. Data is showing in the minio browser however its not reflected in the  node which was down during that time.(after it boot and minio service started). Also that  updated data not replicated to DR as well.( replication command executed in the powered off node)
