### ISSUE TITLE
Data consistency after offline recovery of nodes

### ISSUE THREAD

**Issue by prodanlabs** [minio/minio#10583]
**Is your feature request related to a problem? Please describe.**
When a node of the minio cluster is offline, if there is data upload or modification during the period when the node is offline, the data will not be synchronized after the node is restored. Load balance distribution request, 404 will appear

**Describe the solution you'd like**
Don't know if there is a solution now.

**Comment by harshavardhana** [comment]
> When a node of the minio cluster is offline, if there is data upload or modification during the period when the node is offline, the data will not be synchronized after the node is restored. Load balance distribution request, 404 will appear

This has been fixed with auto heal in place @prodanlabs - you don't say much about your setup so can't help you much here.
