### ISSUE TITLE
AmazonJavaSDK - IAM policy creation error - This endpoint belongs to "sts".

### ISSUE THREAD

**Issue by LowcaPromocji** [minio/minio#10580]
I want to use any Java SDK to create IAM policy in minio. Due to the fact, that official Minio Java SDK is not supporting such abomination, I'd like to ask if there is way to do that with AmazonSDK and AmazonIdentityManagement class. During it creation, I encoutered error. 
Credential used: the same as in cookbook for AmazonS3 class (extra PathStyleAccessEnabled set to true in AmazonS3) with works.

## Expected Behavior

Policy was created successfully/can use AmazonIdentityManagement api

## Current Behavior

Caused by: com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: Error parsing the Credential parameter; incorrect service. This endpoint belongs to "sts". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: AuthorizationParametersError; Request ID: 1638EEEE58897E28; Proxy: null)

## Possible Solution

Is required endpoint differ from standard http://localhost:9000?

## Steps to Reproduce (for bugs)

1. Create AmazonIdentityManagement  basing on AmazonS3 instructions in cookbook
2. Try to use it creating any policy

## Context

I try to make a program with REST api that will create proper buckets with policies for sts access (openid Keycloak) that will give access to users if Keycloak role is present in their jwt (Bucket id= Test, Role = Test-admin). 

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> I want to use any Java SDK to create IAM policy in minio. Due to the fact, that official Minio Java SDK is not supporting such abomination, I'd like to ask if there is way to do that with AmazonSDK and AmazonIdentityManagement class. During it creation, I encoutered error.
> Credential used: the same as in cookbook for AmazonS3 class (extra PathStyleAccessEnabled set to true in AmazonS3) with works.
> 
> ## Expected Behavior
> Policy was created successfully/can use AmazonIdentityManagement api
> 
> ## Current Behavior
> Caused by: com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: Error parsing the Credential parameter; incorrect service. This endpoint belongs to "sts". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: AuthorizationParametersError; Request ID: 1638EEEE58897E28; Proxy: null)
> 
> ## Possible Solution
> Is required endpoint differ from standard http://localhost:9000?
> 
> ## Steps to Reproduce (for bugs)
> 1. Create AmazonIdentityManagement  basing on AmazonS3 instructions in cookbook
> 2. Try to use it creating any policy
> 
> ## Context
> I try to make a program with REST api that will create proper buckets with policies for sts access (openid Keycloak) that will give access to users if Keycloak role is present in their jwt (Bucket id= Test, Role = Test-admin).
> 
> ## Regression
> ## Your Environment
> * Version used (`minio --version`):
> * Server setup and configuration:
> * Operating System and version (`uname -a`):

We do not support AWS IAM APIs use `mc admin policy` to create policies.
