### ISSUE TITLE
[faq] how to setup MinIO replication?

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10595]
**Is your feature request related to a problem? Please describe.**
with reference to the case  #10589 , I enabled the replication from production one node to DR one node( cluster is in distribuited). After that i powered off that production node and updated bucket with few data. Data is showing in the minio browser however its not reflected in the server side file system which was down during that time.Though server made up after sometime. Also that updated data not replicated to DR as well.( replication command executed in the powered off node)

note: uploaded file replicated to other servers in the file system issue faced only in the shutdown server.

**Describe the solution you'd like**
How to overcome this situation.

**Describe alternatives you've considered**

let us know your suggestion to overcome this issue

**Additional context**

**Comment by poornas** [comment]
@LiginGeorge, can you give more details on how you copied data to the bucket when the first node was down? 

I was not able to repro any issue with a similar setup. I tested with a distributed replication setup with 4 nodes, and killed one of the running servers. 
When I do a `mc cp /etc/issue upnode/test-prod/` to the remaining node that is up, it does get replicated. If there is any failure to replicate, `mc stat` on the object would show X-Amz-Replication-Status FAILED, and the data crawler that runs every five minutes would catch up. 

Please share the `mc stat` output. Which version of MinIO are you using?

**Comment by harshavardhana** [comment]
> @LiginGeorge, can you give more details on how you copied data to the bucket when the first node was down?
> 
> I was not able to repro any issue with a similar setup. I tested with a distributed replication setup with 4 nodes, and killed one of the running servers.
> When I do a `mc cp /etc/issue upnode/test-prod/` to the remaining node that is up, it does get replicated. If there is any failure to replicate, `mc stat` on the object would show X-Amz-Replication-Status FAILED, and the data crawler that runs every five minutes would catch up.
> 
> Please share the `mc stat` output. Which version of MinIO are you using?

I think @LiginGeorge doesn't have a proper LB or is trying to upload to the server which is down. I would simply say a setup issue or just lack of understanding.

**Comment by LiginGeorge** [comment]
Hi ,
 Today i freshly setup the nodes and tried the replication between the  production/DR nodes its working fine. Yes you are right i am not using LB for the replication its happening between two nodes in production and DR. Whenever the replication enabled DR Node down, replication will fail though once node back it will get enabled automatically and data also replicating successfully from PR site.
Do you know any interval is there where DR is down and replication will be time out or will not happen at all ?

**Comment by poornas** [comment]
>Do you know any interval is there where DR is down and replication will be time out or will not happen at all ?

If replication is in pending or failing state, it will be retried when the periodic data crawl happens and will catch up once the DR node comes back online.

**Comment by LiginGeorge** [comment]
OK. Production to DR replication is fine and do we need to follow same steps for the DR to production. it should be active active replication or active passive replication. Also i have noticed  after disabling the replication to DR whatever file uploaded in the bucket not getting replicated  though replication enable back.

./mc replicate set  minio-prod1/noqodi-prod --id btq8ie00889apiko57i0 --state disable 
./mc replicate set  minio-prod1/noqodi-prod --id btq8ie00889apiko57i0 --state enable

**Comment by harshavardhana** [comment]
> OK. Production to DR replication is fine and do we need to follow same steps for the DR to production. it should be active active replication or active passive replication. Also i have noticed after disabling the replication to DR whatever file uploaded in the bucket not getting replicated though replication enable back.

You can't have active/active replication @LiginGeorge - if you need that you need to use other solutions.  What we have is the AWS S3 style replication of buckets.

**Comment by LiginGeorge** [comment]
Thank you.. When DR is active and want to replicate data to PR what should
should be done?

**Comment by LiginGeorge** [comment]
Hi,
Could you please clarify below points:

1. Also i have noticed after disabling the replication to DR whatever file uploaded in the bucket not getting replicated to DR even after enabling replication.
2. When DR is active and want to replicate data to PR what should be the steps

**Comment by poornas** [comment]
> Also i have noticed after disabling the replication to DR whatever file uploaded in the bucket not getting replicated to DR even after enabling replication.

You can verify that replication got re-enabled by checking `mc replicate ls` to see the state of the rule. Replication would start for any uploads **after** the rule got re-enabled. If there was a time frame when the rules were disabled and uploads happened then - they would not be replicated. 

>When DR is active and want to replicate data to PR what should be the steps

 If you want to replicate from the DR node to PR node, you would need to go through the same [steps](https://docs.minio.io/docs/minio-bucket-replication-guide.html) on the DR node, using PR as the target.

**Comment by LiginGeorge** [comment]
If you want to replicate from the DR node to PR node, you would need to go
through the same steps
<https://docs.minio.io/docs/minio-bucket-replication-guide.html> on the DR
node, using PR as the target.

 As your team advised active-active replication not possible so either one
side replication only supported you mean,
 if we want to enable the replication from DR to PR then we should disable
the replication from PR to DR.

**Comment by poornas** [comment]
>  your team advised active-active replication not possible so either one
side replication only supported you mean,

Just to clarify, you can set up replication on both sides - you will not need to disable replication at either end. Only those objects uploaded to the node directly will be replicated, not the replicas

**Comment by harshavardhana** [comment]
Will close this GitHub issue, looks like this has turned into Q/A session rather than an actual issue. Feel free to join https://slack.min.io for further questions.
