### ISSUE TITLE
[faq] Unable to use versioning or lock on local minio

### ISSUE THREAD

**Issue by GigiusB** [minio/minio#10593]
## Expected Behavior

Capability of enabling bucket versioning

## Current Behavior
I am trying to use the command
```
mc version enable test/testbucket
```
but I am getting `A header you provided implies functionality that is not implemented`

I would expect the local server work as the play.
```
/ # mc mb play/testv
Bucket created successfully `play/testv`.
/ # mc version enable play/testv
play/testv versioning is enabled
/ # mc mb --with-lock play/testv
mc: <ERROR> Unable to make bucket `play/testv`. Your previous request to create the named bucket succeeded and you already own it.
/ # mc mb --with-lock play/testv2
Bucket created successfully `play/testv2`.
/ # mc admin info play
●  play.min.io
   Uptime: 7 hours 
   Version: 2020-09-26T17:54:02Z
   Network: 1/1 OK 
   Drives: 4/4 OK 
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
```
/ # mc alias set test http://172.17.0.1:19000 minioadmin minioadmin
Added `test` successfully.
/ # mc admin test
mc: <ERROR> `test` is not a mc command. See `mc --help`. 
/ # mc mb test/testbucket
Bucket created successfully `test/testbucket`.
/ # mc version enable test/testbucket
mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.
/ # mc mb --with-lock test/testbucket2
mc: <ERROR> Unable to make bucket `test/testbucket2`. A header you provided implies functionality that is not implemented
```

## Your Environment
Minio running in docker container from image minio:minio exposing port 9000 on host port 19000
Mc running in docker container
Host:
```
$ uname -a
Linux beast 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
/ # mc -v
mc version RELEASE.2020-09-23T20-02-13Z
/ # mc admin info test
●  172.17.0.1:19000
   Uptime: 4 minutes 
   Version: 2020-09-26T03:44:56Z
   Network: 1/1 OK 
```

**Comment by harshavardhana** [comment]
Filesystem mode doesn't support object locking or versioning ..

- *Versioning feature is only available in erasure coded and distributed erasure coded setups.* - https://docs.minio.io/docs/minio-bucket-versioning-guide.html
- *Object locking feature is only available in erasure coded and distributed erasrue coded setups.* - https://docs.minio.io/docs/minio-bucket-object-lock-guide.html

FS mode is meant for simple usecases for more larger functionality use erasure coding.
