### ISSUE TITLE
I want to build a minio service via TLS in the local area network.

### ISSUE THREAD

**Issue by crossnote** [minio/minio#10591]
Two linux servers 28.204.48.62 and 28.204.48.63 are used, according to the introduction of the https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html document, I used openssl to generate a self-signed certificate, put private.key and public.crt in the ${HOME}/.minio/certs folder of the 62 and 63 machines, and successfully started the service. And visit https://28.204.48.62 through a browser to upload and download files successfully.
But when I use java SDK 7.1.0 version to connect to the minio server, the following error occurred: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException : unable to find valid certification path to requested target
Then I imported the self-signed certificate into the cacerts file of JDK_Home/jre/lib/security using the keytool tool that comes with jdk, and the following error occurred:
 ErrorResponse {code=AccessDenied,message= Access denied }........
I don't know how to solve this problem now, can someone help me, thanks (edited)  how it should work -->

**Comment by harshavardhana** [comment]
Would love to help but lacks information. Doesn't say anything about the setup etc.
