### ISSUE TITLE
[faq] minio DR bucket replication removal

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10604]
**Is your feature request related to a problem? Please describe.**
./mc admin bucket remote rm minio-prod1/test-prod --arn "arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-prod"
mc: <ERROR> Unable to remove remote target. Replication configuration exists with this ARN.

/mc admin bucket remote ls minio-prod1/test-prod
Remote URL                          Source     ->Target      ARN
http://minio1.local:9001  test-prod->test-prod arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-prod

**Describe the solution you'd like**
Need to remove the replication which i set between the  production and DR node.

**Describe alternatives you've considered**
Need your suggestion on this

**Additional context**

**Comment by poornas** [comment]
```
mc replicate rm sourceAlias/bucket --all --force
```
you will need to remove the replication configuration on the bucket before you can run `mc admin bucket remote rm` command.

**Comment by harshavardhana** [comment]
> ```
> mc replicate rm sourceAlias/bucket --all --force
> ```
> 
> you will need to remove the replication configuration on the bucket before you can run `mc admin bucket remote rm` command.

Closed as per the last comment @poornas

**Comment by LiginGeorge** [comment]
for instance, replication is in progress from production to DR and after DR switch over we need to enable the replication from DR to production. Let me know the steps are you suggesting here to proceed.

**Comment by harshavardhana** [comment]
> for instance, replication is in progress from production to DR and after DR switch over we need to enable the replication from DR to production. Let me know the steps are you suggesting here to proceed.

you can set it up always we support active/active https://blog.min.io/active-active-replication/

**Comment by LiginGeorge** [comment]
Thanks. I have gone through the article where its saying the replication from production to DR, however same steps to follow from DR to PR. Let me know below steps are right.

Production:

./mc admin bucket remote add minio-prod1/test-bucket http://testuserdr:5c31ad832d8c9114444176e86a4be1cbc9@minio-dr1:9001/test-bucket --service replication
./mc replicate add minio-prod1/test-bucket --priority 1 --arn "arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-bucket" --storage-class "STANDARD" --remote-bucket "test-bucket"

DR: 

./mc admin bucket remote add minio-dr1/test-bucket http://testuserpr:5c31ad832d8c911f0176e333a4be1cbc9@minio-prod1:9001/test-bucket --service-replication
./mc replicate add minio-dr1/test-bucket --priority 1 --arn "arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-bucket" --storage-class "STANDARD" --remote-bucket "test-bucket"

**Comment by poornas** [comment]
> Thanks. I have gone through the article where its saying the replication from production to DR, however same steps to follow from DR to PR. Let me know below steps are right.
> 
> Production:
> 
> ./mc admin bucket remote add minio-prod1/test-bucket http://testuserdr:5c31ad832d8c9114444176e86a4be1cbc9@minio-dr1:9001/test-bucket --service replication
> ./mc replicate add minio-prod1/test-bucket --priority 1 --arn "arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-bucket" --storage-class "STANDARD" --remote-bucket "test-bucket"
> 
> DR:
> 
> ./mc admin bucket remote add minio-dr1/test-bucket http://testuserpr:5c31ad832d8c911f0176e333a4be1cbc9@minio-prod1:9001/test-bucket --service-replication
> ./mc replicate add minio-dr1/test-bucket --priority 1 --arn "arn:minio:replication::cb673f0a-8507-4fcd-a11d-8ae1eff4f92d:test-bucket" --storage-class "STANDARD" --remote-bucket "test-bucket"

Correct

**Comment by LiginGeorge** [comment]
it should work with 3 weeks old mc version as well. Doesn't need to use the latest mc version ?

**Comment by harshavardhana** [comment]
> it should work with 3 weeks old mc version as well. Doesn't need to use the latest mc version ?

Better to always use latest mc and latest minio

**Comment by tjanson** [comment]
I had exactly the same question. It might be a good idea to add this to the docs, or perhaps even better: change the error message to suggest that using `--force` is standard procedure in this case (which is the unexpected and "scary" part that might confuse users).
