### ISSUE TITLE
[working as intended] files are not getting deleted from the server

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10608]
**Is your feature request related to a problem? Please describe.**
After we delete the file in the bucket through S3 browser its deleting from the minio browser console also from S3 browser console. But its not deleting from the server file system end.

**Describe the solution you'd like**
Need to clean the deleted files from the server as well.

**Describe alternatives you've considered**
Need your suggestion on this

**Additional context**

**Comment by harshavardhana** [comment]
@LiginGeorge you should explain yourself further

- what is the MinIO version?
- does your bucket have versioning enabled?

**Comment by LiginGeorge** [comment]
./mc -version
mc version RELEASE.2020-09-23T20-02-13Z
 ./minio -version
minio version RELEASE.2020-09-26T03-44-56Z

yes, i have enabled the bucket version as that is a prerequisites for the bucket replication to DR

**Comment by poornas** [comment]
when you delete an object via the S3 browser a [delete marker](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html) is created for versioned objects. To permanently delete the object version from disk, you will need to specify the --version-id flag in `mc rm`. You can identify the version ids by doing a `mc ls` with --versions flag

For general questions, please join the MinIO slack channel on https://slack.min.io .

**Comment by harshavardhana** [comment]
> when you delete an object via the S3 browser a [delete marker](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html) is created for versioned objects. To permanently delete the object version from disk, you will need to specify the --version-id flag in `mc rm`. You can identify the version ids by doing a `mc ls` with --versions flag

As explained by @poornas use `mc` - MinIO Browser doesn't support deleting versions yet.

**Comment by LiginGeorge** [comment]
Hi, 
 Please find the output of the command
./mc ls --versions minio-prod1/noqodi-prod
[2020-09-30 20:11:45 +04]     0B 9f464186-e3e9-4773-afc7-7ad382484b96 v2 DEL chrony.txt
[2020-09-30 17:30:04 +04] 5.5KiB e0c0d5a2-2dd5-4c87-8c12-23f0ac7ce1ae v1 PUT chrony.txt
its allowing me to delete one version id only 

./mc rm minio-prod1/noqodi-prod/chrony.txt --version-id "e0c0d5a2-2dd5-4c87-8c12-23f0ac7ce1ae"
Removing `minio-prod1/noqodi-prod/chrony.txt` (versionId=e0c0d5a2-2dd5-4c87-8c12-23f0ac7ce1ae).

For the same file other version id i am getting below error

./mc rm minio-prod1/noqodi-prod/chrony.txt --version-id "9f464186-e3e9-4773-afc7-7ad382484b96"
mc: <ERROR> Failed to remove `minio-prod1/noqodi-prod/chrony.txt`. 405 Method Not Allowed

Also files in the server end still available.

**Comment by LiginGeorge** [comment]
./mc ls --versions minio-prod1/noqodi-prod
[2020-09-30 20:11:45 +04]     0B 9f464186-e3e9-4773-afc7-7ad382484b96 v1 DEL chrony.txt

this DEL file still exist and in the server as well

**Comment by harshavardhana** [comment]
> ./mc ls --versions minio-prod1/noqodi-prod
> [2020-09-30 20:11:45 +04] 0B 9f464186-e3e9-4773-afc7-7ad382484b96 v1 DEL chrony.txt
> 
> this DEL file still exist and in the server as well

mc rm --versions -r

**Comment by harshavardhana** [comment]
> ./mc rm minio-prod1/noqodi-prod/chrony.txt --version-id "9f464186-e3e9-4773-afc7-7ad382484b96"
> mc: Failed to remove `minio-prod1/noqodi-prod/chrony.txt`. 405 Method Not Allowed

This we fixed https://github.com/minio/mc/commit/2568f9e7bf2dda46f334b40f8ff65d25d6e7f981

**Comment by LiginGeorge** [comment]
So should i download the new mc version to fix this issue ?  is it available the new one in the minio website. Also minio version also needs to replace ?

**Comment by harshavardhana** [comment]
> So should i download the new mc version to fix this issue ? is it available the new one in the minio website. Also minio version also needs to replace ?

not yet you have to build from source, no server replacement needed @LiginGeorge

**Comment by LiginGeorge** [comment]
I am not a developer, is there any possibility  to get it fix via any command syntax or downloading via new mc version to run the same.

**Comment by poornas** [comment]
you can download [this](https://play.min.io/bin/mc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20201001%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201001T060832Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=671730be39d83cc7a7f3ed5a2ce77c5afd7bcecf7bb118e434d5ea218d601e08) binary and try

**Comment by LiginGeorge** [comment]
Hi,
  
  If i want to delete .well-known folder how do i can do that ?
./mc ls --versions minio1/test-pay-static-content/.well-known/HashOfHashFileList.txt
[2020-10-20 16:54:06 +04]   290B af4506e9-7cad-48fa-b3ed-8debf889e9ff v1 PUT HashOfHashFileList.txt

**Comment by vadmeste** [comment]
> ./mc ls --versions minio1/test-pay-static-content/.well-known/HashOfHashFileList.txt

./mc rm --versions -r --force minio1/test-pay-static-content/.well-known/
