### ISSUE TITLE
[faq] [working as intended] mc admin config get endpoint notify_webhook return nothing using environment configuration

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#10602]
inizializing minio with:

export MINIO_NOTIFY_WEBHOOK_ENABLE_test=on
export MINIO_NOTIFY_WEBHOOK_ENDPOINT_test=https://test.fqdn/api/webhook/
export MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_test=/var/lib/minio/queue
export MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_test=10000

then run

$ mc admin config get aliasname notify_webhook
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=

## Expected Behavior

return the above webhook configuration

## Current Behavior

return empty configuration

## Steps to Reproduce (for bugs)
start minio with the above config then run mc admin config get aliasname notify_webhook

## Your Environment

$ minio -v
minio version RELEASE.2020-09-26T03-44-56Z

**Comment by harshavardhana** [comment]
This is working as intended, ENV values are not sent back with `mc admin config` - `mc admin config` only displays values which are persisted. 

We may add ENV values displayed as part of `mc admin config` in the future, but there are no plans right now.
