### ISSUE TITLE
Back button in the web interface does not take me back to the parent folder

### ISSUE THREAD

**Issue by knzivid** [minio/minio#10619]
## Steps to Reproduce (for bugs)

- The user opens a new tab
- The user is on page `bucket/folder` with a subfolder `child`
- The user clicks on `bucket/folder/child` link on the page
- The user presses back to navigate back to the parent

## Expected Behavior

The user is taken back to `bucket/folder`

## Current Behavior

The user is taken back to the new tab page (before navigating to minio web interface)

## Context

SPA (single page applications) respect browser back button and it's intuitive to press the forward/backward button on the mouse to navigate. MinIO browser breaks this assumption.

## Regression

Not sure

## Your Environment

- Version 2020-07-24T22-43-05Z
- Linux my-storage 4.4.59+ #25426 SMP Tue Jul 14 19:47:36 CST 2020 aarch64 GNU/Linux synology_rtd1296_ds420j

**Comment by harshavardhana** [comment]
Yes this is not supported yet, browser is a lower priority for us right now.

If you wish to add this feature please send us a fix yourself, or wait for us to get back to it.
