### ISSUE TITLE
mc.exe: <ERROR> Cannot get service status. The specified bucket is not valid. (Bucket name invalid: .minio.sys). with azure gateway

### ISSUE THREAD

**Issue by Win32Sector** [minio/minio#10620]
I tried execute mc admin info for minio in azure gateway mode.

But I receive error:

`mc.exe: <ERROR> Cannot get service status. The specified bucket is not valid. (Bucket name invalid: .minio.sys). `

Is it works in gateway mode?

## Your Environment

* Version used (`minio --version`): latest image
* Server setup and configuration: AKS

**Comment by harshavardhana** [comment]
Looks like a server side issue, will take a look.
