### ISSUE TITLE
Unable to pull latest stable release from docker hub

### ISSUE THREAD

**Issue by xoxys** [minio/minio#10629]
## Current Behavior
```
docker pull minio/minio:RELEASE.2020-10-03T02-19-42Z
RELEASE.2020-10-03T02-19-42Z: Pulling from minio/minio
df20fa9351a1: Already exists 
72bf75d60211: Pulling fs layer 
error pulling image configuration: unknown blob
```
## Your Environment
* Operating System and version (`uname -a`): Linux 5.8.10-200.fc32.x86_64 #1 SMP Thu Sep 17 16:48:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@xoxys thanks for reporting this.

Happening for me as well. Maybe you can use minio/minio:latest until this gets fixed, most likely today.

**Comment by xoxys** [comment]
No worries I'm using an older release for now.

**Comment by harshavardhana** [comment]
Looks like automated docker build has failed we have seen this happen at docker hub at some points in time, looks like some data loss.

**Comment by harshavardhana** [comment]
Fixed it upstream by pushing the latest tag
