### ISSUE TITLE
Request: allow exposing metrics on non-service port

### ISSUE THREAD

**Issue by ghost** [minio/minio#10625]
**Is your feature request related to a problem? Please describe.**

We want to expose metrics without authentication to simplify prometheus configuration, but only for cluster-internal clients. The service port is exposed to a wider audience of clients, and we will have to jump through hoops to blacklist the metrics URI.

**Describe the solution you'd like**

It would be nice if minio could listen on a separate port and expose metrics on that port only (or with different authentication parameters). Then that port could be exposed to cluster internal clients only.

>Exposing metrics on a separate port would probably simplify configuration and enhance security.

https://github.com/minio/minio/issues/8323#issuecomment-537688739

**Describe alternatives you've considered**

Using the "none" metrics auth method and blacklisting the metrics API. This is more error prone.

**Additional context**

As an added benefit, minio could offer the standard /metrics route if configured to use a separate port for metrics (rather than the custom / minio-specific route).

**Comment by harshavardhana** [comment]
Separate ports are a nuisance for us and hard to manage. It's a rabbit we wish to avoid. To secure the endpoint there is already authentication required by default. 

We would rather not add many ways to do the same thing.

**Comment by ghost** [comment]
fair enough!
