### ISSUE TITLE
mc rm  doesn't delete buckets.

### ISSUE THREAD

**Issue by Win32Sector** [minio/minio#10630]
## Expected Behavior
mc rm --recursive --force --dangerous minio 
this command deletes recursively files and buckets

mc rb --force --dangerous minio
This command delertes empty buckets
## Current Behavior
first command deletes only files, second command doesn't delete buckets

## Your Environment

* Version used (`minio --version`): mc version RELEASE.2020-08-20T00-23-01Z
* Server setup and configuration: AKS

**Comment by vadmeste** [comment]
> first command deletes only files,

This is actually expected. rm should not delete buckets, that's why we have rb (remove bucket) for that purpose.


> second command doesn't delete buckets

What's the output of 'mc rb' ? does your bucket contain some files ?

**Comment by Win32Sector** [comment]
mc rb  --force --dangerous minio

executed with code 0 without any output.

**Comment by vadmeste** [comment]
Not able to reproduce it on my side, could you do that with a new bucket ? does your bucket already have some data ?

**Comment by vadmeste** [comment]
@Win32Sector also what's your S3 server ?

**Comment by vadmeste** [comment]
oh, it seems I was able to reproduce it. I can remove bucket by bucket but not all buckets in one command. Will investigate and fix it.

**Comment by micworg** [comment]
maybe the same problem as here:  
https://minio.slack.com/archives/C3NDUB8UA/p1601311650149900
