### ISSUE TITLE
[not our bug] Possible problem with anonymous bucket policies

### ISSUE THREAD

**Issue by MT-S** [minio/minio#10639]
Authenticated user with ReadWrite policy cannot upload or delete from bucket with anonymous policy 'download'.

## Expected Behavior
I assume that anonymous policy only applies to unauthenticated users and authenticated user is limited to his IAM policy.

## Current Behavior
When anonymous policy is 'download' bucket folder chmod changes to read. If authenticated user tries to upload file it crashes internally  "We encountered an internal error, please try again.", because "Error: rename .../.minio.sys/tmp/...  .../bucket/... permission denied" 

## Possible Solution
If this was the intended behavior change "We encountered an internal error, please try again." to something related to permisions

## Steps to Reproduce (for bugs)
1.  mc policy set download /path/to/bucket
2.  Upload file (while user with readwrite)

## Context
.

## Regression
Not sure

## Your Environment
* Version used (`minio --version`): RELEASE.2020-10-03T02-19-42Z
* Server setup and configuration: vmware machine 
* Operating System and version (`uname -a`): Ubuntu 20.04.01 LTS

**Comment by harshavardhana** [comment]
> When anonymous policy is 'download' bucket folder chmod changes to read. If authenticated user tries to upload file it crashes internally "We encountered an internal error, please try again.", because "Error: rename .../.minio.sys/tmp/... .../bucket/... permission denied"

You seem to have not explained your setup at all, not sure what you are trying to do here.

**Comment by MT-S** [comment]
> > When anonymous policy is 'download' bucket folder chmod changes to read. If authenticated user tries to upload file it crashes internally "We encountered an internal error, please try again.", because "Error: rename .../.minio.sys/tmp/... .../bucket/... permission denied"
> 
> You seem to have not explained your setup at all, not sure what you are trying to do here.

I am trying to have bucket with following:
Anonymous user - can only read/get files
Authenticated user - can do anything (upload/delete)

Setup:
Simple test server using latest binary build

Problem (or might be intended behavior):
When anonymous policy "mc policy set download /path/to/bucket" is set, authenticated user (ReadWrite) cannot upload file to bucket and sees internal server error in Web GUI.

**Comment by kannappanr** [comment]
`mc policy set download alias/bucket` is the right way to set this

You should not use `mc policy set download /path/to/bucket` you are basically changing the permission of the folder in the backend. I am assuming that you are using file system mode here

**Comment by harshavardhana** [comment]
> Simple test server using latest binary build
> 
> Problem (or might be intended behavior):
> When anonymous policy "mc policy set download /path/to/bucket" is set, authenticated user (ReadWrite) cannot upload file to bucket and sees internal server error in Web GUI

This is a minor bug, not a fundamental problem, please share the console log might be something silly which can be fixed.

**Comment by MT-S** [comment]
> `mc policy set download alias/bucket` is the right way to set this
> 
> You should not use `mc policy set download /path/to/bucket` you are basically changing the permission of the folder in the backend. I am assuming that you are using file system mode here

Yep stupid me. Thank you.
