### ISSUE TITLE
gateway support for immutability and retention

### ISSUE THREAD

**Issue by muhamadazmy** [minio/minio#10641]
I am building a custom gateway for minio that leverage on some feature provided by https://threefold.io/ grid. I faced a problem with implementing the "immutability" feature (object locking and retention) that minio actually assume that locking is not enabled if you are using a gateway [here](https://github.com/minio/minio/blob/effe1310900b1672a5713f89803a1490380f2ac1/cmd/bucket-object-lock.go#L41) and we get an immediate `Bucket is missing ObjectLockConfiguration` error. without consulting the gateway object layer for configuration.

- I need to understand the reason this is not supported for gateways (like technical limitations or difficulties that lead to this decision)
- We can **try** to implement this feature in minio but I am not sure about the amount of work that is needed to get it working the right way with no regression. And if we actually should do it (depends on your answer on the previous point)

**Comment by harshavardhana** [comment]
Object Locking is a native API in AWS S3 we cannot directly translate them into anything meaningful for gateway layer.

If you are writing the gateway layer, it should just return not implemented that's all.

**Comment by kannappanr** [comment]
@muhamadazmy Closing this as answered. Please feel free to reach out to us if you have further questions

**Comment by muhamadazmy** [comment]
@harshavardhana thank you for your answer, although there is something i don't quite get. 
- Object locking is supported by minio as stated here: https://docs.minio.io/docs/minio-bucket-object-lock-guide.html
- Hence the question, why the headers associated with "locking" are not passed a long to a gateway implementation. Shouldn't it be up to the gateway to decide if it's implemented or not?
- Currently minio immediately return NotImplemented!

Our gateway can handle object locking the problem is the call/options to manage object locking requests are not forwarded to the gateway, so it give us no chance to handle it

**Comment by harshavardhana** [comment]
> @harshavardhana thank you for your answer, although there is something i don't quite get. 
> - Object locking is supported by minio as stated here: https://docs.minio.io/docs/minio-bucket-object-lock-guide.html
> - Hence the question, why the headers associated with "locking" are not passed a long to a gateway implementation. Shouldn't it be up to the gateway to decide if it's implemented or not?
> - Currently minio immediately return NotImplemented!
> 
> Our gateway can handle object locking the problem is the call/options to manage object locking requests are not forwarded to the gateway, so it give us no chance to handle it 
> 

They are not passed along at all, we have gateway implementations already where they are not passed along.

Unless you are basing this off some old commit.

**Comment by zaibon** [comment]
I think the question @muhamadazmy is trying to ask, is why are they not passed along to the gateway interface? 
From what I can read, minio core does support this feature just fine. Is there any technical reason why they are not made available into the gateway interface ?

**Comment by harshavardhana** [comment]
> I think the question @muhamadazmy is trying to ask, is why are they not passed along to the gateway interface?
> From what I can read, minio core does support this feature just fine. Is there any technical reason why they are not made available into the gateway interface ?

@zaibon we are limiting the scope of gateway - it is in code freeze at the moment.
