### ISSUE TITLE
S3 DeleteObjects: when object is a directory - the returned object key is wrong

### ISSUE THREAD

**Issue by romayalon** [minio/minio#10643]
When trying to delete an object of type directory (for example 'my_dir/') using S3 DeleteObjects the returned object key is wrong - the actual returned object key is the name of the directory + ```"__XLDIR__"```.  (and for the example - 'my_dir__XLDIR__'). 
## Expected Behavior

When trying to delete an object of type directory (for example 'my_dir/') using DeleteObjects the returned the same object key (and for the example - should be 'my_dir/'). 
## Current Behavior

When trying to delete an object of type directory (for example 'my_dir/') using DeleteObjects the returned object key is wrong - the actual returned object key is the name of the directory + ```"__XLDIR__"```. (and for the example - 'my_dir__XLDIR__'). 
## Steps to Reproduce (for bugs)

1. Create a bucket and a folder in it.
2. Delete that folder and check the returned value (used aws sdk for node js).

## Context

I'm trying to verify the deleted objects by their keys.
## Your Environment

* Version used (`minio --version`): used play minio
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> When trying to delete an object of type directory (for example 'my_dir/') using S3 DeleteObjects the returned object key is wrong - the actual returned object key is the name of the directory + `"__XLDIR__"`. (and for the example - 'my_dir__XLDIR__').

This is a bug which should be fixed @romayalon

**Comment by harshavardhana** [comment]
This is fixed in the latest release.
