### ISSUE TITLE
Follow up issue with #10490

### ISSUE THREAD

**Issue by MikeLReminderM** [minio/minio#10657]
Error creating cert file based on answer to #10490

## Expected Behavior

I expect a certificate that will work for *.local will be created by the command:

openssl req -new -x509 -days 3650 -key server.key -out server.cert   -subj "/C=/ST=/L=/O=/CN=" -addext "subjectAltName = DNS:*.local"

## Current Behavior

openssl does not recognize the -addext option:

openssl req -new -x509 -days 3650 -key server.key -out server.cert   -subj "/C=/ST=/L=/O=/CN=" -addext "subjectAltName = DNS:*.local"
_**unknown option -addext**_
req [options] <infile >outfile
where options  are....

## Possible Solution

Was that supposed to be a different option?

## Steps to Reproduce (for bugs)

I want to create a wildcard cert to use with minio in Kubernetes.   I want to be able to use the same cert for all pods
and not have to create new certs for every pod and need to add that cert to all the trust directories for all the others.

## Regression

No.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

Latest minio docker image.

Right now trying to make this work in docker compose and then will try kubernetes.

CentOS 7 is the OS.

**Comment by MikeLReminderM** [comment]
As an update, I gave up on getting this to work and just run minio with http and put nginx in front of it to handle https.

**Comment by harshavardhana** [comment]
> As an update, I gave up on getting this to work and just run minio with http and put nginx in front of it to handle https.

Thanks for updating us @MikeLReminderM
