### ISSUE TITLE
Error: bucket name cannot be empty when upgrading

### ISSUE THREAD

**Issue by AlexGustafsson** [minio/minio#10658]
I tried to upgrade from `RELEASE.2020-07-27T18-37-02Z` to `RELEASE.2020-10-09T22-55-05Z` using Docker. Unfortunately the server won't start properly. It logs nothing when started, but on each request to the server's HTTP interface, I get the following:

```
API: SYSTEM()
Time: 18:04:00 UTC 10/12/2020
DeploymentID: [UUID]
Error: bucket name cannot be empty
       4: cmd/bucket-policy.go:52:cmd.(*PolicySys).IsAllowed()
       3: cmd/auth-handler.go:338:cmd.checkRequestAuthTypeToAccessKey()
       2: cmd/bucket-handlers.go:273:cmd.objectAPIHandlers.ListBucketsHandler()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```

When I reverted back to the old version, it worked again.

## Expected Behavior

Upgrading from quite recent versions should be allowed without any hiccups.

## Current Behavior

Upgrading from a quite recent version yields minio unusable.

## Possible Solution

It might be some configuration fault on my end, but given the log, I think it's unlikely. I used `mc` to check the working instance and there are no empty buckets, unnamed buckets or files etc.

## Steps to Reproduce (for bugs)

1. Run `minio/minio:RELEASE.2020-07-27T18-37-02Z`
2. Use it, put some files on it etc.
3. Run `minio/minio:RELEASE.2020-10-09T22-55-05Z`
4. Try to connect to the server's HTTP interface
5. Watch as nothing is returned and the log complains

## Regression

Yes, most likely. From version `minio/minio:RELEASE.2020-07-27T18-37-02Z`.

## Your Environment

* Version used (`minio --version`): `minio/minio:RELEASE.2020-07-27T18-37-02Z`
* Server setup and configuration: `MINIO_ACCESS_KEY_FILE=...`, `MINIO_SECRET_KEY_FILE=...`, `MINIO_PROMETHEUS_AUTH_TYPE=jwt`
* Operating System and version (`uname -a`): `Docker version 19.03.11, build 42e35e6`

**Comment by harshavardhana** [comment]
> API: SYSTEM()
> Time: 18:04:00 UTC 10/12/2020
> DeploymentID: [UUID]
> Error: bucket name cannot be empty
>        4: cmd/bucket-policy.go:52:cmd.(*PolicySys).IsAllowed()
>        3: cmd/auth-handler.go:338:cmd.checkRequestAuthTypeToAccessKey()
>        2: cmd/bucket-handlers.go:273:cmd.objectAPIHandlers.ListBucketsHandler()
>        1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()

This is not a bug looks like you have some anonymous requests coming in at `/` @AlexGustafsson

**Comment by harshavardhana** [comment]
> I tried to upgrade from `RELEASE.2020-07-27T18-37-02Z` to `RELEASE.2020-10-09T22-55-05Z` using Docker. Unfortunately the server won't start properly. It logs nothing when started, but on each request to the server's HTTP interface, I get the following:

Can you share how are you starting? - server starts up fine on docker containers for me as well as kubernetes.

**Comment by AlexGustafsson** [comment]
Thanks for the quick response.

I'm running Minio on a Docker swarm with a static host. So basically `docker stack deploy --compose-file docker-compose.yml minio`.

The compose file should be equivalent to:

```
docker run \
-e MINIO_ACCESS_KEY_FILE=... \
-e MINIO_SECRET_KEY_FILE=... \
-e MINIO_PROMETHEUS_AUTH_TYPE=jwt \
-v /path/to/access-key:/var/run/secrets/access-key \
-v /path/to/secret-key:/var/run/secrets/secret-key \
minio/minio:RELEASE.2020-10-09T22-55-05Z
```

Is there any known issues that may usually occur when upgrading minio, does one have to upgrade incrementally or something? I've read somewhere either on this project or on the website that you're only supposed to update if it's necessary.

**Comment by harshavardhana** [comment]
> Thanks for the quick response.
> 
> I'm running Minio on a Docker swarm with a static host. So basically `docker stack deploy --compose-file docker-compose.yml minio`.
> 
> The compose file should be equivalent to:
> 
> ```
> docker run \
> -e MINIO_ACCESS_KEY_FILE=... \
> -e MINIO_SECRET_KEY_FILE=... \
> -e MINIO_PROMETHEUS_AUTH_TYPE=jwt \
> -v /path/to/access-key:/var/run/secrets/access-key \
> -v /path/to/secret-key:/var/run/secrets/secret-key \
> minio/minio:RELEASE.2020-10-09T22-55-05Z
> ```
> 
> Is there any known issues that may usually occur when upgrading minio, does one have to upgrade incrementally or something? I've read somewhere either on this project or on the website that you're only supposed to update if it's necessary.

@AlexGustafsson NOTE - if you did rolling upgrade then its not recommended when you said its not up and ready what do you see?

**Comment by AlexGustafsson** [comment]
@harshavardhana No, I only have one instance of minio running.

I wasn't able to get a response from the site at all and the log showed:

```
API: SYSTEM()
Time: 18:04:00 UTC 10/12/2020
DeploymentID: [UUID]
Error: bucket name cannot be empty
       4: cmd/bucket-policy.go:52:cmd.(*PolicySys).IsAllowed()
       3: cmd/auth-handler.go:338:cmd.checkRequestAuthTypeToAccessKey()
       2: cmd/bucket-handlers.go:273:cmd.objectAPIHandlers.ListBucketsHandler()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```

I tried upgrading to  `RELEASE.2020-09-26T03-44-56Z` now, and it worked. I then tried again to upgrade to `RELEASE.2020-10-09T22-55-05Z`. Now I do get a response, but the log is still showing errors:

```
API: SYSTEM()
Time: 18:46:16 UTC 10/12/2020
DeploymentID: ...
Error: bucket name cannot be empty
       9: cmd/bucket-metadata.go:111:cmd.(*BucketMetadata).Load()
       8: cmd/bucket-metadata.go:142:cmd.loadBucketMetadata()
       7: cmd/bucket-metadata-sys.go:398:cmd.(*BucketMetadataSys).GetConfig()
       6: cmd/bucket-metadata-sys.go:323:cmd.(*BucketMetadataSys).GetPolicyConfig()
       5: cmd/bucket-policy.go:40:cmd.(*PolicySys).Get()
       4: cmd/bucket-policy.go:45:cmd.(*PolicySys).IsAllowed()
       3: cmd/auth-handler.go:338:cmd.checkRequestAuthTypeToAccessKey()
       2: cmd/bucket-handlers.go:273:cmd.objectAPIHandlers.ListBucketsHandler()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
API: SYSTEM()
Time: 18:46:16 UTC 10/12/2020
DeploymentID: ...
Error: bucket name cannot be empty
       4: cmd/bucket-policy.go:52:cmd.(*PolicySys).IsAllowed()
       3: cmd/auth-handler.go:338:cmd.checkRequestAuthTypeToAccessKey()
       2: cmd/bucket-handlers.go:273:cmd.objectAPIHandlers.ListBucketsHandler()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```

~The log seems to occur on most actions on the interface, such as viewing a bucket.~

EDIT: The logs seem to occur no matter the actions performed.

**Comment by harshavardhana** [comment]
> EDIT: The logs seem to occur no matter the actions performed.

Log can be ignored @AlexGustafsson it is not a bug - it is in-fact rejecting some port scanner like entities at `/`

**Comment by harshavardhana** [comment]
> I wasn't able to get a response from the site at all and the log showed:

When you said no response at all what does it mean? can you show me an example?

**Comment by AlexGustafsson** [comment]
@harshavardhana Sounds reasonable. Thank you for the incredibly fast response, and replying despite this obviously being a community issue rather than a bug. Closing.

"No response was" was basically no response from the server (it not responding at all), but from I gather it must have simply been an anomaly with a slow deployment or the like, with minio not being fully up yet.
