### ISSUE TITLE
[not our bug] Cross-Origin Read Blocking (CORB) blocked cross-origin response - 307 temporary redirect

### ISSUE THREAD

**Issue by petebytes** [minio/minio#10668]
## Expected Behavior
When trying to access uploaded files, they should not be blocked by the browser

## Current Behavior
![image](https://user-images.githubusercontent.com/676739/95917640-6efc1300-0d5f-11eb-9ddf-ec3fab501521.png)

on the Console
```Cross-Origin Read Blocking (CORB) blocked cross-origin response http://minio.test:9000/minio/launchmuse-dev/development/launchmuse.app/store/content/10/digital_content/6d8ac2323de6ac810352c721603e6020.jpg with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.```

on Network Tools
```307 Temporary Redirect Content-Security-Policy: block-all-mixed-content Location: ...6d8ac2323de6ac810352c721603e6020.jpg Vary: Origin X-Amz-Request-Id: 163D96F14EA12078 X-Xss-Protection: 1; mode=block Content-Length: 0```

## Possible Solution
Seems like file mime type is not being retained, it shows text/html instead of actual mime type.

## Steps to Reproduce (for bugs)
I do not have a publicly available instance.  Can setup a time to share environment via meet/zoom

## Context
Trying to configure dev environment to mirror production.  Too many times have been caught with problems that only occur in staging/prod due to filesystem vs S3 storage use.

## Regression
No

## Your Environment

Minio minio:RELEASE.2020-10-12T21-53-21Z
Running in Ubuntu 20.04 under Windows WSL2 using docker-compose
Linux 8355ac78dd93 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 Linux

**Comment by harshavardhana** [comment]
This is because your uploader is setting the incorrect content-type @petebytes

**Comment by petebytes** [comment]
Thanks for the extra quick response @harshavardhana :)
Using Minio browser
- The preview link works fine
- The share link works fine

In db I stored the mime type, showing image/jpeg
`{"id":"content/10/digital_content/6d8ac2323de6ac810352c721603e6020.jpg","storage":"store","metadata":{"size":40959,"filename":"split-testing.jpg","mime_type":"image/jpeg","width":1200,"height":600}}`

I am checking the file type using ffmpeg - will update findings shortly

**Comment by petebytes** [comment]
File and metadata on minio showing correct mime_type.

cat fs.json 
{"version":"1.0.2","checksum":{"algorithm":"","blocksize":0,"hashes":null},"meta":{"content-disposition":"inline; filename=\"split-testing.jpg\"; filename*=UTF-8''split-testing.jpg","content-type":"image/jpeg","etag":"9d939fafec932c8b356241a04fcd1515"}}/storage/.minio.sys/buckets/launchmuse-dev/development/launchmuse.app/store/content/10/digital_content/6d8ac2323de6ac810352c721603e6020.jpg # 

file --mime-type 6d8ac2323de6ac810352c721603e6020.jpg 
6d8ac2323de6ac810352c721603e6020.jpg: image/jpeg

**Comment by petebytes** [comment]
Have not fixed it but isolated the issue to using acl of public-read.
researching fix...
