### ISSUE TITLE
Can't download the entire folder located on a bucket in minio SDKs

### ISSUE THREAD

**Issue by Prafulljohri** [minio/minio#10662]
Directory download is a common practice and AWS S3 supports this feature. 

## Expected Behavior
The DownloadObjectArgs should contain the prefix method (where we can pass the folder directory) as it's available in ListObjectsArgs. 

## Current Behavior
The current API does not have this feature and it is getting failed while passing the directory only in the object method of DownloadObjectArgs.
Also, the minio browser supports the zip download of the directory while it's is missing for the SDKs

## Possible Solution
Add support to download the complete directory. For reference please refer to the below AWS S3 document.
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#downloadDirectory-java.lang.String-java.lang.String-java.io.File-

## Your Environment

* Version used (`minio --version`): any
* Server setup and configuration: any
* Operating System and version (`uname -a`): any

**Comment by vadmeste** [comment]
@Prafulljohri could you paste the error that the AWS SDK throws ?

**Comment by Prafulljohri** [comment]
@vadmeste I've not used the AWS SDK, but after googling for a solution I found that the API is available in AWS S3

**Comment by harshavardhana** [comment]
Downloading a directory is a client side functionality, there is no API to download a directory. 

Open this as a feature request in our Java SDK we may implement it in future. 

There is nothing for server to do here.

**Comment by Prafulljohri** [comment]
As requested, opened the request in minio-Java SDK
https://github.com/minio/minio-java/issues/1073
