### ISSUE TITLE
lifecycle rule for path does not work

### ISSUE THREAD

**Issue by ghost** [minio/minio#10664]
**lifecycle rule to clean path content does not work**
## Expected Behavior
Clean temporary files

## Current Behavior
Files remain

## Possible Solution
I dont know

## Steps to Reproduce (for bugs)

1. mc ls s3minio/testbucket
[2020-10-13 09:52:40 CDT]     0B deleteNext14/
[2020-10-13 09:52:40 CDT]     0B temp/
[2020-10-13 09:52:40 CDT]     0B test1/

2 .mc ilm export s3minio/testbucket
{
 "Rules": [
  {
   "AbortIncompleteMultipartUpload": {},
   "Expiration": {
    "Date": "2020-10-14T00:00:00Z",
    "DeleteMarker": false
   },
   "ID": "del-2020-10-14/",
   "Filter": {
    "And": {},
    "Prefix": "deleteNext14/",
    "Tag": {}
   },
   "NoncurrentVersionExpiration": {
    "NoncurrentDays": 0
   },
   "NoncurrentVersionTransition": {},
   "Status": "Enabled",
   "Transition": {
    "Date": "0001-01-01T00:00:00Z"
   }
  },
  {
   "AbortIncompleteMultipartUpload": {},
   "Expiration": {
    "Date": "0001-01-01T00:00:00Z",
    "Days": 1,
    "DeleteMarker": false
   },
   "ID": "TemporaryFiles",
   "Filter": {
    "And": {},
    "Prefix": "temp/",
    "Tag": {}
   },
   "NoncurrentVersionExpiration": {
    "NoncurrentDays": 0
   },
   "NoncurrentVersionTransition": {},
   "Status": "Enabled",
   "Transition": {
    "Date": "0001-01-01T00:00:00Z"
   }
  }
 ]
}
3. mc ls s3minio/testbucket/temp| wc -l
10000

4. Path "temp" not empty

## Regression

No

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2020-10-03T02-19-42Z
mc version RELEASE.2020-10-03T02-54-56Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
Linux s3node01 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@hjacas `mc stat s3minio/testbucket/path/to/an/object` shows when that object is supposed to be removed (see Expiration in the output)

**Comment by ghost** [comment]
# mc stat s3minio/testbucket/temp/file.aoup
Name      : file.aoup
Date      : 2020-10-12 10:18:06 CDT 
Size      : 1.0 MiB 
ETag      : fd7c8f4a1a6e8a6ca3669d731643ee13 
Type      : file 
**Expiration: 2020-10-13 20:00:00 CDT (lifecycle-rule-id: TemporaryFiles)** 
Metadata  :
  Content-Type: application/octet-stream 

It is scheduled to expire at 20:00:00 today
Right?

**Comment by ghost** [comment]
I wait then and check tomorrow
Thanks a lot

**Comment by ghost** [comment]
on the same topic: additionally, it had another rule named "del-2020-10-14", which should delete the content of the path "deleteNext14" next Oct 14 and "mc stat ..." returns:

**# mc stat s3minio/testbucket/deleteNext14/file.aoun
Name      : file.aoun
Date      : 2020-10-12 10:29:07 CDT 
Size      : 1.0 MiB 
ETag      : c83ec430f70074eddf1cac76fd9840d5 
Type      : file 
Expiration: 2020-10-13 20:00:00 CDT (lifecycle-rule-id: del-2020-10-14/) 
Metadata  :
  Content-Type: application/octet-stream** 



What would be the explanation for this?
Will it be today and not tomorrow when it is eliminated?

**Comment by harshavardhana** [comment]
> on the same topic: additionally, it had another rule named "del-2020-10-14", which should delete the content of the path "deleteNext14" next Oct 14 and "mc stat ..." returns:
> 
> **# mc stat s3minio/testbucket/deleteNext14/file.aoun Name : file.aoun Date : 2020-10-12 10:29:07 CDT Size : 1.0 MiB ETag : c83ec430f70074eddf1cac76fd9840d5 Type : file Expiration: 2020-10-13 20:00:00 CDT (lifecycle-rule-id: del-2020-10-14/) Metadata : Content-Type: application/octet-stream**
> 
> What would be the explanation for this?
> Will it be today and not tomorrow when it is eliminated?

That rule doesn't have any days set, so it will be today.

**Comment by ghost** [comment]
since yesterday morning

**Comment by ghost** [comment]
sorry, the same day the object was created on Oct 12

**Comment by vadmeste** [comment]
> sorry, the same day the object was created on Oct 12

According to the S3 specification, the object will be deleted in the next day at midnight GMT.

2020-10-14 00:00:00 GMT = 2020-10-13 20:00:00 CDT

**Comment by ghost** [comment]
Hello,
During the night the rules worked as expected
Thanks for your clarifications and support.
