### ISSUE TITLE
[faq] Expected fault tolerance behaviour

### ISSUE THREAD

**Issue by adilinden** [minio/minio#10665]
## Expected Behavior

Documentation at https://docs.min.io/docs/minio-erasure-code-quickstart-guide states that one can loose N/2 drives in a cluster without data loss.

- How are data and parity distributed across disks?
- If I have 4 disks, can any two disks go offline at any time without loss of data and continued usage of the storage solution?

## Your Environment

* Version used (`minio --version`): latest
* Server setup and configuration: ESXi 6.5
* Operating System and version (`uname -a`): Ubuntu 20.04 & Docker

I would like to setup 2 DCH (Docker Container Hosts), one each on a physical server, and attach drives to Minio on each DCH. The goal would be for this to be shared storage that remains online and maintains its integrity even if one of the DCH or physical ESXi hosts goes offline.

**Comment by adilinden** [comment]
Summary:

Documentation at https://docs.min.io/docs/minio-erasure-code-quickstart-guide states that one can loose N/2 drives in a cluster without data loss.

- How are data and parity distributed across disks?
- If I have 4 disks, can any two disks go offline at any time without loss of data and continued usage of the storage solution?

I would like to setup 2 DCH (Docker Container Hosts), one each on a physical server, and attach drives to Minio on each DCH. The goal would be for this to be shared storage that remains online and maintains its integrity even if one of the DCH or physical ESXi hosts goes offline.

Will Minio behave as I would expect?

**Comment by klauspost** [comment]
> If I have 4 disks, can any two disks go offline at any time without loss of data and continued usage of the storage solution?

No, you will lose write capability when you lose the second disk, but it will be restored as soon as you replace the disk.

You can join the community slack https://slack.min.io/ or look into our direct support options: https://min.io/pricing
