### ISSUE TITLE
Make transit endpoint configurable

### ISSUE THREAD

**Issue by StevenReitsma** [minio/minio#10663]
**Is your feature request related to a problem? Please describe.**
Minio support encryption using Hashicorp Vault. This works great, but depends on Vault's transit engine being mounted at `/transit`. Minio does not support configuring the transit engine path. `/transit` is the default for Vault, but can be changed when using multiple transit engines. At my organization, we use multiple transit engines for several different purposes, each with different policies.

**Describe the solution you'd like**
Add an additional environment variable `MINIO_KMS_VAULT_TRANSIT_PATH` that can be configured. There should be a default value of `transit` for this value to ensure backwards compatibility.

**Describe alternatives you've considered**
KES already supports this, but I prefer the transit engine over the KV engine to keep the keys in Vault. Additionally, adding KES would add another component to an already complex system of applications.

Related KES issue: https://github.com/minio/kes/issues/55
Related KES commit: https://github.com/minio/kes/commit/9a6264cf76c1ae99204e8e6e892ec6b5e9a0d61c

**Comment by harshavardhana** [comment]
Our recommended approach is to use Kes, Hashicorp Vault directly is deprecated and it is advised that you move to Kes.
