### ISSUE TITLE
mc: Reports 'Chunk Encoding isn't supported' when asked to copy small files to s3 bucket path

### ISSUE THREAD

**Issue by enlitVR** [minio/minio#10672]
mc: <ERROR> Failed to copy **/outbound/snowball/tar/irad-daily_ct_2020-10-01-files.445.tar**. _Chunk encoding is not supported yet_ reported when copying small files
## Expected Behavior
copy should complete succesfully and report transfer time/rate as files 1GB+ do.

## Current Behavior
Error above reported while file size is "small" (<1G).

## Possible Solution
Is there a setting to adjust the threshold size for breaking files into multiple parts for upload?

## Steps to Reproduce (for bugs)
The specified file  can't be uploaded to the snowball using `mc cp irad-daily_ct_2020-10-01-files.445.tar snow/cmv-inbound/irad/irad-daily__ct_2020-10-01-files.445.tar`... Throws the above error if file is <1GB. 
Not sure what smallest size is that transfers successfully.

## Context
Error means when copying large batches of auto generated tars, to snowball s3 bucket , need to detect copy failures and repeat those copies using AWS cli, which is much slower, and extra logic complicates copy process.

## Your Environment
• Version used (minio --version): `mc version RELEASE.2020-08-20T00-23-01Z`
• Server setup and configuration:  _mc is connecting to AWS Snowball Edge via a dedicated 10Gbps direct connection_
• Operating System and version (uname -a): **Ubuntu 18.04.3 LTS , Kernel 5.4.0-48-generic minio/minio#52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**
.mc/config.json:
{
"version": "10",
"aliases": {
...
"snow": {
"url": "http://w.x.y.z:port",
"accessKey": "<accessKey>",
"secretKey": "<secretKey>",
"api": "s3v4",
"path": "auto"
}
}

**Comment by harshavardhana** [comment]
`mc` automatically uses AWS STREAMING signature AWS Snowball Edge doesn't support this fully. So you can't use `mc` to upload content into Snowball edge.
