### ISSUE TITLE
[working as intended] minio single drive starts after long time

### ISSUE THREAD

**Issue by aleksandpetrov** [minio/minio#10674]
## Current Behavior

The minio runs in 20-30 min after start
## Steps to Reproduce (for bugs)

1. Run ./minio server /data

## Context

I try start the minio in terminal and via systemd as well as with system directory and dedicated disk, result  the same
## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2020-09-26T03-44-56Z
* Server setup and configuration:
PowerEdge R540
2 x Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
RAM 196Gb
* Operating System and version (`uname -a`):
Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@aleksandpetrov how many buckets do you have ?

**Comment by aleksandpetrov** [comment]
> @aleksandpetrov how many buckets do you have ?

I have an empty directory.

**Comment by vadmeste** [comment]
@aleksandpetrov could you try with another directory ? like run this `minio server /tmp/testdisk/`

**Comment by aleksandpetrov** [comment]
> @aleksandpetrov could you try with another directory ? like run this `minio server /tmp/testdisk/`

I tried it with many directories, the same result

**Comment by aleksandpetrov** [comment]
the process pauses on next(strace output):
newfstatat(AT_FDCWD, "/usr/local/bin/minio", {st_mode=S_IFREG|0755, st_size=51683328, ...}, 0) = 0
futex(0xc000580bc8, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigprocmask(SIG_SETMASK, ~[], [], 8) = 0
clone(child_stack=0xc000810000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM) = 3787702
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT ILL TRAP ABRT BUS FPE SEGV TERM STKFLT CHLD PROF SYS RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT ILL TRAP ABRT BUS FPE SEGV TERM STKFLT CHLD PROF SYS RTMIN RT_1], NULL, 8) = 0
futex(0xc0004ee148, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT ILL TRAP ABRT BUS FPE SEGV TERM STKFLT CHLD PROF SYS RTMIN RT_1], NULL, 8) = 0
futex(0xc000580bc8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3554408, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x3554408, FUTEX_WAIT_PRIVATE, 0, NULL

**Comment by aleksandpetrov** [comment]
Upd:
For another release.

  **mount -t tmpfs -o size=4096m tmpfs /mnt/ramdisk
  ./minio.RELEASE.2020-09-23T19-18-30Z server --address :9000 /mnt/ramdisk**

Port was bound and web interface became available in 20 min.
By the way on another host(vm or hw) the same time for run.

**Comment by harshavardhana** [comment]
Did the same steps, takes like few secs

```
~ sudo mount -t tmpfs -o size=4096m tmpfs /mnt/ramdisk
~ sudo time ./minio server --address :9000 /mnt/ramdisk
Endpoint:  http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000          
AccessKey: minioadmin 
SecretKey: minioadmin 

Browser Access:
   http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000          

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minioadmin minioadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
^CExiting on signal: INTERRUPT
0.08user 0.02system 0:01.42elapsed 7%CPU (0avgtext+0avgdata 51052maxresident)k
0inputs+0outputs (0major+6819minor)pagefaults 0swaps
```
