### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by a386572631** [minio/minio#10673]
## Steps to Reproduce (for bugs)

1.通过nginx负载 访问到minio服务，使用浏览器没问题，实例化MinioClient对象的时候提示not match，确定AK和SK没错
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Incomplete issue closing
