### ISSUE TITLE
[not our bug] Problem of coverage when i upload same-name or same-content file to minio server

### ISSUE THREAD

**Issue by DDusky** [minio/minio#10675]
**Is your feature request related to a problem? Please describe.**

1.  When I upload a file with the same name but different content, the latter overrides the former
2. When I upload a file with a different name but the same content, the latter does not override the former

    This can cause problems with wasted storage space.

**Describe the solution you'd like**

  First, I might encrypt the file name, and second, I need to parse MD5 and determine repeatability before uploading the file.

**Comment by DDusky** [comment]
Oh, I forgot, I'm calling the Python SDK
use `minio_server. put_object(bucket_name, object_name, data, lenth)`

**Comment by harshavardhana** [comment]
De-dup is not part of MinIO - it needs to be done client side. @DDusky
