### ISSUE TITLE
mc: du fails to find disk usage from s3 bucket path when number of directory entries is 'high' 

### ISSUE THREAD

**Issue by enlitVR** [minio/minio#10671]
mc: <ERROR> Failed to find disk usage of `snow/cmv-inbound/irad_snaps/` recursively. Truncated response should have continuation token set

## Expected Behavior

`mc du snow/cmv-inbound` should return a number in each case, or stop due to some defined limit,
and instead report limit reached without total being found.

## Current Behavior

3 things:
1. mc du <path> returns value when path contains as many as 981 files, but
2. generates the above error somewhere between there and 1101 files in path.
3. If root of bucket contains fewer files, it can report a (inaccurate) value for the total space in use in the bucket.

## Steps to Reproduce (for bugs)

I have two directories on an s3 bucket path; 1 (snow/cmv-inbound/irad) contains 966 tar files(ranging from 1G <file> 8G ea) that total 2.0T, and `mc du snow/cmv-inbound/irad` returns such.

The second one (snow/cmv-inbound/irad_snaps) contains 1101 tar files that total somewhat more than 5.0T.
Somewhere between 981 files and 1101 files, `mc du snow/cmv-inbound/irad_snaps` stopped working.

The same is true when exceeding a similar number of files in the root of the bucket: `mc du snow/cmv-inbound` would fail with the same error if there were 980+ files present.

Strangely enough, with the path `snow/cmv-inbound` only containing other subdirs (iow , less than 980+ files), `mc du snow/cmv-inbound` returns a value, even though `mc du snow/cmv-inbound/irad_snaps` fails with the above error.

The returned value also appears to be low by the amount of data in the directory that failed to return a value when addressed directly; `mc du snow/cmv-inbound/` returns 23T, when we already know `mc du snow/cmv-inbound/irad_snaps` should return a bit more than 5T, and a query of the bucket's allocated space - minus the free space says the bucket is actually using 28.7T total.

## Context

Needing to know breakdown of space in use in bucket in archiving exercise.
Without du, need to build other scripting to do 'ls -l <path>' and sum values.

## Regression

 This is first use of minio client, can't say if it is a regression or not.

## Your Environment

* Version used (`minio --version`): mc version RELEASE.2020-08-20T00-23-01Z
* Server setup and configuration:  mc is connecting to AWS Snowball Edge via a dedicated 10Gbps direct connection
* Operating System and version (`uname -a`): Ubuntu 18.04.3 LTS , Kernel 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

.mc/config.json:
{
	"version": "10",
	"aliases": {
...
		"snow": {
			"url": "http://w.x.y.z:port",
                        "accessKey": "<accessKey>",
                        "secretKey": "<secretKey>",
			"api": "s3v4",
			"path": "auto"
		}
}

**Comment by harshavardhana** [comment]
> * Server setup and configuration:  mc is connecting to AWS Snowball Edge via a dedicated 10Gbps direct connection

AWS Snowball is not a fully compatible S3 server we only support Snowball for `mc mirror` like functionality. If you want `mc du` to work use a real S3 server.

**Comment by harshavardhana** [comment]
Also moving this issue to relevant project.
