### ISSUE TITLE
Continuous fuzzing

### ISSUE THREAD

**Issue by AdamKorcz** [minio/minio#10689]
This issue revisits continuous fuzzing as discussed in https://github.com/minio/minio/issues/8089

**I am suggesting the following solution:** 
With minio already being fuzzed, I suggest setting up continuous fuzzing through googles oss-fuzz project. Open source projects can integrate into oss-fuzz, and following approval of the project, Google will run the fuzzers continuously. In case bugs are found, maintainers receive an email with a detailed bug report. The service is offered free of charge with an implied expectation that bugs are fixed, so that the resources spent on fuzzing minio go towards fixing bugs.

**What are the steps necessary to finish this integration:**
I will be happy to integrate minio into oss-fuzz. All I need are the email addresses of the maintainers that should receive the bug reports. No files need to be added to minio's repository at this point. 

**What would be good steps to take after setting up continuous fuzzing:**
The next step would be to write more fuzzers. I see a few targets myself that are not already being fuzzed, and I would be happy to write more fuzzers.

**Comment by harshavardhana** [comment]
You are free to send the PR and we are happy to accept always.

**Comment by AdamKorcz** [comment]
Sounds good! For the record, no PR is needed for me to setup continuous fuzzing. What is needed is one or more email addresses for maintainers to receive potential bug reports. These will be added to a public list that can be amended at any time.

Once I have those, I will be able to proceed.

**Comment by harshavardhana** [comment]
> Sounds good! For the record, no PR is needed for me to setup continuous fuzzing. What is needed is one or more email addresses for maintainers to receive potential bug reports. These will be added to a public list that can be amended at any time.

- harsha at min.io
- klaus at min.io
