### ISSUE TITLE
Minio distributed deployment waiting for disks to come online indefinitely

### ISSUE THREAD

**Issue by tometchy** [minio/minio#10682]
I've read the issue https://github.com/minio/minio/issues/6187 but it's not my case, despite result looks the same.

## Expected Behavior
Correct Minio working on two nodes with simple redundancy, when one machine gets down, cluster need to keep working with one machine.

## Current Behavior
Can't connect (two) nodes.

## Steps to Reproduce (for bugs)

I have two machines with _Docker_ and _docker-compose_ on both and try to create cluster with them. I need simple redundancy, when one machine gets down, cluster need to keep working with one machine.
First machine address is 10.131.15.14 and second is 10.131.15.15
Communication need to be over TLS but I think it's not the issue, I have set correct certificates (which solved TLS errors I had at the beginnig).
After reading docs I have created following configuration (access and secret keys are the same on both machines, here I _obfuscated_ them).

10.131.15.14:
``` docker-compose
version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2020-01-16T03-05-44Z
    #restart: unless-stopped
    volumes:
      - /datastore01/volumes/minio/data1-1:/data1:z
      - /datastore01/volumes/minio/data1-2:/data2:z
      - /datastore01/volumes/minio/data1-3:/data3:z
      - /datastore01/volumes/minio/data1-4:/data4:z
      - /etc/localtime:/etc/localtime:ro
      - /datastore01/certs:/root/.minio/certs
    ports:
      - "44314:44314"
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
    command: server https://10.131.15.14/data{1...4} https://10.131.15.15/data{1...4}  --address ":44314"
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://10.131.15.14:44314/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

10.131.15.15:
``` docker-compose
version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2020-01-16T03-05-44Z
    #restart: unless-stopped
    volumes:
      - /datastore01/volumes/minio/data1-1:/data1:z
      - /datastore01/volumes/minio/data1-2:/data2:z
      - /datastore01/volumes/minio/data1-3:/data3:z
      - /datastore01/volumes/minio/data1-4:/data4:z
      - /etc/localtime:/etc/localtime:ro
      - /datastore01/certs:/root/.minio/certs
    ports:
      - "44314:44314"
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
    command: server https://10.131.15.14/data{1...4} https://10.131.15.15/data{1...4}  --address ":44314"
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://10.131.15.15:44314/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

```

Minio starts without errors (on both nodes), but keep saying _Waiting for a minimum of 2 disks to come online_ (indefinitely), for example:
> minio_1  | 2020-10-15T03:41:09.981287773Z Formatting 1 zone, 1 set(s), 4 drives per set.
minio_1  | 2020-10-15T03:41:10.493692748Z Waiting for a minimum of 2 disks to come online (elapsed 0s)

I know that communication between nodes work on this port, because from every node I can _curl_ both minio containers (from both nodes), and have answer from minio (saying that minio server is not initialized), for example:
```
curl https://10.131.15.15:44314
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Resource>/</Resource><RequestId>163E0D5B1892963C</RequestId><HostId></HostId></Error>
```

## Context
It's new minio setup, I do it for the first time and need to have it working on two machines (as Docker containers).
I need simple redundancy, when one machine gets down, cluster need to keep working with one machine.

## Regression
---

## Your Environment
* Version used (`minio --version`):RELEASE.2020-01-16T03-05-44Z
* Server setup and configuration: CentOS Linux 8 (Core) with Docker version 19.03.13, build 4484c46d9d and docker-compose version 1.26.2, build eefe0d31
* Operating System and version (`uname -a`):  4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
>     command: server https://10.131.15.14/data{1...4} https://10.131.15.15/data{1...4}  --address ":44314"

Specifying manually won't work @tometchy MinIO needs to know the drives which host they belong to, also this is an incorrect way to run MinIO you should spreading the data across the hosts for proper HA. 

Closing this as unsupported way to run MinIO
