### ISSUE TITLE
Monitor minio in k8s, Unauthorized

### ISSUE THREAD

**Issue by jurycu** [minio/minio#10681]
deploy a minio in k8s, using prometheus to monitor it.  this is prometheus config:
` 
- job_name: 'minio'
      bearer_token:  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3NTYzMzI4MzcsImlzcyI6InByb21ldGhldXMifQ.ABNKUdKQAcuks2tvFlmrEnqnawpm8wIJUrqAIB_R3p_4vX3PPc0izKq4i6XeeeWzvR0as1T1V3Da0tGYC_rt5Q
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: minio
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
`

the   bearer_token is use mc to create, but prometheus scrape err, msg:server returned HTTP status 401 Unauthorized
## Expected Behavior
prometheus can get the metrics
## Current Behavior
Unauthorized

how to create a  correct token in minio cluster that every node can use.

**Comment by harshavardhana** [comment]
The issue doesn't have any proper description on what is needed or what is expected. Please re-open with relevant information about 

- Your environment, MinIO version, k8s version etc.
- Concise description of what is missing.
- A sample yaml to reproduce the problem
