### ISSUE TITLE
[not our bug] I want to upload images in the server when compression and add watermark, how to achieve?

### ISSUE THREAD

**Issue by thewholeworld** [minio/minio#10680]
In order to save storage space and improve efficiency, I want to compress the uploaded images when uploading on the server. Due to some business requirements, I also need to add watermark to the images. At present, we are in the server. How can it be achieved?

**Comment by harshavardhana** [comment]
This is part of your application stack, nothing to do with MinIO server. We receive blobs and store blobs.
