### ISSUE TITLE
STS behind proxy - 405 error

### ISSUE THREAD

**Issue by LowcaPromocji** [minio/minio#10684]
I am trying to create Minio Server with something like SSO using STS (Keycloak according to [this page](https://github.com/minio/minio/blob/master/docs/sts/keycloak.md)) and proper policy management. I want grant Realm User access to buckets defined by Realm Roles (which is possible by adding policy per role) using Minio Server GUI. Minio Server is behind Nginx server. 
Dockerized Minio used with Docker Swarm
## Expected Behavior

Proxy works, user is able to log in and get access to specified buckets
## Current Behavior

During login by OpenId, I get:
API: WebLoginSTS()
Error: 405 Not Allowed

Approach tested and works without proxy.
## Possible Solution

Is it posible to give such access to Keycloak users using Minio Server GUI? 
## Steps to Reproduce (for bugs)

1. Create Minio server instance with configured Keycloak by OpenId 
2. Move Minio behind  proxy (Nginx)
3. Try to login

## Context
Nginx configuration:
`    location /minio {
	proxy_pass http://minio:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k; 
    }`

## Your Environment

* Version used (`minio --version`):
RELEASE.2020-09-21T22-31-59Z

**Comment by harshavardhana** [comment]
> `location /minio { proxy_pass http://minio:9000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_buffer_size 128k; proxy_buffers 4 256k; proxy_busy_buffers_size 256k; }`

Changing location like this not supported please follow our Nginx documentation https://docs.minio.io/docs/setup-nginx-proxy-with-minio.html 

Using MinIO under custom URL is not supported and will never be supported.

**Comment by LowcaPromocji** [comment]
Changing location helped. :)
