### ISSUE TITLE
JAVADoc is 404.

### ISSUE THREAD

**Issue by Ymriri** [minio/minio#10691]
http://minio.github.io/minio-java/ is 404.
Is it updated or no?

**Comment by balamurugana** [comment]
It is accessible https://wave.webaim.org/report#/http://minio.github.io/minio-java/. Please check your browser.

**Comment by Ymriri** [comment]
I checked it out already ,my Google browser is doing fine.
is that because I use a VPN as I am in china？

**Comment by balamurugana** [comment]
No idea. Have you checked https://wave.webaim.org/report#/http://minio.github.io/minio-java/ ?

**Comment by Ymriri** [comment]
![image](https://user-images.githubusercontent.com/56512874/96273067-7f331d00-1001-11eb-953c-a07d47a0e658.png)
yep，Iv checked it out.

**Comment by balamurugana** [comment]
Not sure what's going on at your side.
