### ISSUE TITLE
remote error: tls: bad certificate

### ISSUE THREAD

**Issue by IIPoliII** [minio/minio#10690]
## Expected Behavior

I want my machines to securly connect between them using HTTPS

## Current Behavior

On every machines, they don't trust each others and I get the error `remote error: tls: bad certificate`

## Steps to Reproduce (for bugs)

1. Install a minio cluster using the following https://github.com/Poli-Systems/Minio-Cluster-Setup (it's far from being finished but it's an example)
2. Copy the SSL certificate between the machines using copy-cert.sh for example
3. Try to start the cluster 
4. Make `service minio status`

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
I am using Ubuntu 20.04, and the latest minio version and the config you can quiet understand it in the script.

The certificates are in the CAs cert not with a pretty random name but they are there. Any idea?

```
Oct 15 17:45:17 ubuntu-4gb-nbg1-3 minio[18747]: 2020/10/15 17:45:17 http: TLS handshake error from 10.0.0.2:45558: remote error: tls: bad certificate
Oct 15 17:45:18 ubuntu-4gb-nbg1-3 minio[18747]: 2020/10/15 17:45:18 http: TLS handshake error from 10.0.0.2:45564: remote error: tls: bad certificate
Oct 15 17:45:18 ubuntu-4gb-nbg1-3 minio[18747]: 2020/10/15 17:45:18 http: TLS handshake error from 10.0.0.5:50592: remote error: tls: bad certificate
Oct 15 17:45:18 ubuntu-4gb-nbg1-3 minio[18747]: Unable to read 'format.json' from https://minio-1:9000/var/minio: Post "https://minio-1:9000/minio/storage/var/minio/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate is not valid for any names, but wanted to match minio-1
Oct 15 17:45:18 ubuntu-4gb-nbg1-3 minio[18747]: Unable to read 'format.json' from https://minio-2:9000/var/minio: Post "https://minio-2:9000/minio/storage/var/minio/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate is not valid for any names, but wanted to match minio-2
Oct 15 17:45:18 ubuntu-4gb-nbg1-3 minio[18747]: Unable to read 'format.json' from https://minio-4:9000/var/minio: Post "https://minio-4:9000/minio/storage/var/minio/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate is not valid for any names, but wanted to match minio-4

```

**Comment by harshavardhana** [comment]
> 1. Install a minio cluster using the following https://github.com/Poli-Systems/Minio-Cluster-Setup (it's far from being finished but it's an example)

This is not our recommendation - follow our TLS docs https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls.html

**Comment by IIPoliII** [comment]
I don't exactly understand. I am using the .go certificate generator should I specify a IP or an hostname somewhere?

**Comment by harshavardhana** [comment]
> I don't exactly understand. I am using the .go certificate generator should I specify a IP or an hostname somewhere?

hostname

**Comment by IIPoliII** [comment]
I updated the script and it uses now the hostname but I still get the error
```
API: SYSTEM()
Time: 11:59:56 CEST 10/16/2020
Error: https://minio-2:9000/var/minio as has incorrect configuration: Post "https://minio-2:9000/minio/bootstrap/v1/verify?": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Acme Co")
       1: cmd/server-main.go:458:cmd.serverMain()
2020/10/16 11:59:57 http: TLS handshake error from 10.0.0.5:46790: remote error: tls: bad certificate
2020/10/16 11:59:57 http: TLS handshake error from 10.0.0.4:58662: remote error: tls: bad certificate
2020/10/16 11:59:57 http: TLS handshake error from 10.0.0.3:59774: remote error: tls: bad certificate

```


Any ideas?

EDIT : The latest version of the repo is using openssl and the same thing here is the old version using generate_cert.go https://github.com/Poli-Systems/Minio-Cluster-Setup/tree/f0b345a9ecf9be09419f2ad9c231c23e0a43af9b
