### ISSUE TITLE
Questions about performance

### ISSUE THREAD

**Issue by shencangsheng** [minio/minio#10707]
I am using minio in a docker swarm cluster, but when one minio node goes down, access to other minio nodes becomes extremely slow. Is it due to low server configuration or is there something to configure?

**Comment by harshavardhana** [comment]
This should never happen, what is the server version here? @shencangsheng

**Comment by shencangsheng** [comment]
Server version is ubuntu16.04,docker version is 19.03. @harshavardhana

**Comment by shencangsheng** [comment]
I'm using the official compose file with the ` healthcheck: test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"] interval: 30s timeout: 20s retries: 3` configuration and the server fails to start and the server is configured for 8g2cpu. when I crash the next node the access becomes slow. @harshavardhana

**Comment by harshavardhana** [comment]
> I'm using the official compose file with the ` healthcheck: test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"] interval: 30s timeout: 20s retries: 3` configuration and the server fails to start and the server is configured for 8g2cpu. when I crash the next node the access becomes slow. @harshavardhana

What is the MinIO version?

**Comment by shencangsheng** [comment]
Image used for mirroring: minio/minio:latest,Also, Also, the s3f3 I'm using is mounted in a local directory and accessing the mounted directory is slow.@harshavardhana

**Comment by harshavardhana** [comment]
> Image used for mirroring: minio/minio:latest,Also, Also, the s3f3 I'm using is mounted in a local directory and accessing the mounted directory is slow.@harshavardhana

docker run --rm minio/minio:latest --version ?

**Comment by shencangsheng** [comment]
`version: '3.8'
services:
  minio1:
    image: minio/minio
    hostname: minio1
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"`
@harshavardhana

**Comment by shencangsheng** [comment]
Use the official swarm compose provided by.
@harshavardhana

**Comment by klauspost** [comment]
Feel free to drop by the community slack: https://slack.min.io/ or look into our direct support options: https://min.io/pricing
