### ISSUE TITLE
docs: update lifecycle docs to provide examples for versioning and delete marker 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#10704]
**Is your feature request related to a problem? Please describe.**
No documentation regarding on how to setup lifecycle policies on versioning enabled bucket

**Describe the solution you'd like**
No documentation regarding on how to setup lifecycle policies on versioning enabled bucket

**Describe alternatives you've considered**
Figuring out using AWS S3 docs, quite challenging. 

**Additional context**
Our documentations should also describe our limitations, what we implement, and how we work. i.e when does the expiration really happen and how to use `mc stat` to figure out the expiration window.

**Comment by vadmeste** [comment]
Going to add versioning support in mc ilm command first.

**Comment by harshavardhana** [comment]
> Going to add versioning support in mc ilm command first.

We can document the entire JSON first, since server is not waiting for `mc` to support this functionality.
