### ISSUE TITLE
A timeout occurred while trying to lock a resource, please reduce your request rate

### ISSUE THREAD

**Issue by furkalor** [minio/minio#10717]
I use spark for data science purposes and minio as a storage backend. Loads are quite intensive. After several days of working some operations begin to fail and I see the next error: 

mc: <ERROR> Failed to remove in `https://minio-dev-1.minio.local:4433/dataplatform/data/entities/balance_transactions/d=20201016_0.1685190200805664/part-00000-f00cb57d-ac8d-4975-96c1-8611f14e51d5-c002.snappy.parquet`. A timeout occurred while trying to lock a resource, please reduce your request rate

Only a full cluster restart helps in this situation.
## Expected Behavior

Normal minio work if there are enough resources from the hardware side.
## Current Behavior

/opt/mc/current/mc --debug mv --recursive minio/dataplatform/data/entities/balance_transactions/d=20201016_0.1685190200805664/ minio/dataplatform/data/entities/balance_transactions/d=20201016/

...75-96c1-8611f14e51d5-c002.snappy.parquet:  0 B / 74.64 MiB ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃
mc: <DEBUG> PUT /dataplatform/data/entities/balance_transactions/d%3D20201016/part-00000-f00cb57d-ac8d-4975-96c1-8611f14e51d5-c002.snappy.parquet?partNumber=1&uploadId=7058bb61-439d-4835-8770-f817f522f0fa HTTP/1.1
Host: minio-dev-1.minio.local:4433
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Content-Length: 0
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Copy-Source: dataplatform/data/entities/balance_transactions/d%3D20201016_0.1685190200805664/part-00000-f00cb57d-ac8d-4975-96c1-8611f14e51d5-c002.snappy.parquet
X-Amz-Copy-Source-Range: bytes=0-78261577
X-Amz-Date: 20201020T191937Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 228
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 20 Oct 2020 19:19:38 GMT
Server: MinIO/RELEASE.2020-10-03T02-19-42Z
Vary: Origin
X-Amz-Request-Id: 163FC987C7F605E8
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1.178924048s

...75-96c1-8611f14e51d5-c002.snappy.parquet:  74.64 MiB / 74.64 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 59.60 MiB/s
mc: <DEBUG> POST /dataplatform/data/entities/balance_transactions/d%3D20201016/part-00000-f00cb57d-ac8d-4975-96c1-8611f14e51d5-c002.snappy.parquet?uploadId=7058bb61-439d-4835-8770-f817f522f0fa HTTP/1.1
Host: minio-dev-1.minio.local:4433
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Content-Length: 241
X-Amz-Content-Sha256: b89b0f20a313a733ed0e4e9318295e1150c657439e85da2686c7735fbe82d17a
X-Amz-Date: 20201020T191938Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 546
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 20 Oct 2020 19:19:38 GMT
Etag: "3caca8fcb90244fc243bec8037a1e48d-1"
Server: MinIO/RELEASE.2020-10-03T02-19-42Z
Vary: Origin
X-Accel-Buffering: no
X-Amz-Request-Id: 163FC9880E42FAB5
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  22.411958ms

...75-96c1-8611f14e51d5-c002.snappy.parquet:  74.64 MiB / 74.64 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 59.26 MiB/s 1s
mc: <DEBUG> POST /dataplatform/?delete= HTTP/1.1
Host: minio-dev-1.minio.local:4433
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Content-Length: 196
X-Amz-Content-Sha256: de7462f16eed5c03e3e9dd2a16456fd1d118b16dfce14fb9995e3f655694105f
X-Amz-Date: 20201020T191938Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 426
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 20 Oct 2020 19:24:38 GMT
Server: MinIO/RELEASE.2020-10-03T02-19-42Z
Vary: Origin
X-Amz-Request-Id: 163FC9880F99ACA7
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  5m0.046788961s

mc: <ERROR> Failed to remove in `https://minio-dev-1.minio.local:4433/dataplatform/data/entities/balance_transactions/d=20201016_0.1685190200805664/part-00000-f00cb57d-ac8d-4975-96c1-8611f14e51d5-c002.snappy.parquet`. A timeout occurred while trying to lock a resource, please reduce your request rate
 (1) mv-main.go:178 cmd.(*removeManager).readErrors.func1(..) Tags: [https://minio-dev-1.minio.local:4433/dataplatform/data/entities/balance_transactions/d=20201016_0.1685190200805664/part-00000-f00cb57d-ac8d-4975-96c1-8611f14e51d5-c002.snappy.parquet]
 (0) client-s3.go:1178 cmd.(*S3Client).Remove.func1(..)
 Commit:f11ae85566fe | Release-Tag:RELEASE.2020-10-03T02-54-56Z | Host:minio-dev-1 | OS:linux | Arch:amd64 | Lang:go1.14.9 | Mem:3.0 MB/75 MB | Heap:3.0 MB/66 MB
## Steps to Reproduce (for bugs)

The problem appears unexpectedly: the cluster can work several hours or several days.

## Context

[minio-health_20201020195353.json.gz](https://github.com/minio/minio/files/5411337/minio-health_20201020195353.json.gz)
## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-10-03T02-19-42Z
* Server setup and configuration:

* * ●  minio-dev-2.minio.local:4433
   Uptime: 5 days 
   Version: 2020-10-03T02:19:42Z
   Network: 3/3 OK 
   Drives: 4/4 OK 

* * ●  minio-dev-3.minio.local:4433
   Uptime: 5 days 
   Version: 2020-10-03T02:19:42Z
   Network: 3/3 OK 
   Drives: 4/4 OK 

* * ●  minio-dev-1.minio.local:4433
   Uptime: 5 days 
   Version: 2020-10-03T02:19:42Z
   Network: 3/3 OK 
   Drives: 4/4 OK 

510 GiB Used, 6 Buckets, 69,277 Objects
12 drives online, 0 drives offline
* Operating System and version (`uname -a`): Linux minio-dev-1 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I use 3 node cluster 4 SSD drives each. The cluster is working in distributed mode.

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): minio version RELEASE.2020-10-03T02-19-42Z
> * Server setup and configuration:
> * * ●  minio-dev-2.minio.local:4433
>     Uptime: 5 days
>     Version: 2020-10-03T02:19:42Z
>     Network: 3/3 OK
>     Drives: 4/4 OK
> * * ●  minio-dev-3.minio.local:4433
>     Uptime: 5 days
>     Version: 2020-10-03T02:19:42Z
>     Network: 3/3 OK
>     Drives: 4/4 OK
> * * ●  minio-dev-1.minio.local:4433
>     Uptime: 5 days
>     Version: 2020-10-03T02:19:42Z
>     Network: 3/3 OK
>     Drives: 4/4 OK

you need to upgrade to latest to avoid some locking related fixes @furkalor 

```
git rel RELEASE.2020-10-03T02-19-42Z..RELEASE.2020-10-18T21-54-12Z |grep lock
- fix: allow locker to be niladic (10/12/20) (Harshavardhana)
- do not hold write locks - if objects don't exist (#10644) (10/08/20) (Harshavardhana)
- fix: handle concurrent lockers with multiple optimizations (#10640) (10/08/20) (Harshavardhana)
- fix: allow read unlocks to be defensive about split brains (#10637) (10/07/20) (Harshavardhana)
```

**Comment by furkalor** [comment]
It's better now but some locks still appear:

Request:

20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "POST /dataplatform/?delete HTTP/1.1[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Host: minio-dev.minio.local:44344[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "amz-sdk-invocation-id: 20c7946b-5336-3222-66b1-96e6e579a8a4[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "amz-sdk-retry: 1/15/495[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Authorization: AWS4-HMAC-SHA256 Credential=dataplatform/20201023/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=b576feecda96c07c2a91ed7ea8db9a44d104a44859067913ec5302768e355a96[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Content-MD5: 7/IOpBaZnuCQ4N0tbaYJPg==[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Content-Type: application/xml[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "User-Agent: Hadoop 3.3.0, aws-sdk-java/1.11.750 Linux/4.15.0-88-generic OpenJDK_64-Bit_Server_VM/25.265-b01 java/1.8.0_265 scala/2.11.12 vendor/Oracle_Corporation[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "X-Amz-Date: 20201023T125239Z[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Content-Length: 466[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "<Delete><Quiet>true</Quiet><Object><Key>data/events-compact/accounts/y=2020/m=10/d=22/_temporary/</Key></Object><Object><Key>data/events-compact/accounts/y=2020/m=10/d=22/</Key></Object><Object><Key>data/events-compact/accounts/y=2020/m=10/</Key></Object><Object><Key>data/events-compact/accounts/y=2020/</Key></Object><Object><Key>data/events-compact/accounts/</Key></Object><Object><Key>data/events-compact/</Key></Object><Object><Key>data/</Key></Object></Delete>"

Response:

"<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Error><Code>RequestTimeout</Code><Message>A timeout occurred while trying to lock a resource, please reduce your request rate</Message><Key>data/events-compact/accounts__XLDIR__</Key><VersionId></VersionId></Error></DeleteResult>"

Minio trace told me:

01:28:42.776 [200 OK] s3.DeleteMultipleObjects minio-dev.softswiss.net:44344/dataplatform/?delete  116.202.236.210    5m0.542663s  ↑ 563 B ↓ 598 B

{
                            "deploymentid": "dd9e7396-a828-4e6c-bb79-83c64ecc8b7c",
                            "level": "ERROR",
                            "errKind": "MINIO",
                            "time": "2020-10-23T17:47:20.82458902Z",
                            "api": {
                                "name": "NetOBDInfo",
                                "args": {}
                            },
                            "remotehost": "10.0.1.3",
                            "host": "minio-dev-3.minio.local:4433",
                            "requestID": "1640B03A14195E26",
                            "userAgent": "Go-http-client/2.0",
                            "error": {
                                "message": "stream error: stream ID 1; CANCEL",
                                "source": [
                                    "cmd/peer-rest-server.go:425:cmd.(*peerRESTServer).NetOBDInfoHandler()",
                                    "net/http/server.go:2042:http.HandlerFunc.ServeHTTP()"
                                ]
                            }
                        }
