### ISSUE TITLE
STS authentication not working with Minio gateway WebUI

### ISSUE THREAD

**Issue by dciangot** [minio/minio#10711]
Minio gateway WebUI not working for users using STS webIdentity, while the Minio server (not gateway) behaves correctly. Below I share a repository with a simple docker-compose that reproduces locally our setup under investigation.

## Expected Behavior
The login to the gateway webUI should be allowed for users using OpenID.

## Current Behavior
The access is denied with 404 on gateway server

## Steps to Reproduce (for bugs)
Reproducible locally following instructions on this repo:  https://github.com/dciangot/debug-minio-gw

## Context
We are currenty evaluating for an R&D activity at the Italian institute of particle physics (INFN) if we might be able to use the Minio gateway to add STS authN and OPA authZ  functionalities on top of an existing S3 endpoint of ours.

**Comment by dciangot** [comment]
Checking even better, looks like the whole `AssumeRoleWithWebIdentity` API is not enabled on Minio gateway (*)? Is this correct?
In that case, is there any plan to support that, or we better think about another solution for this problem?

(*)
```<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /</Message><Resource>/</Resource><RequestId></RequestId><HostId>3c9cc2d6-8b44-4a42-92d5-b54033dd7553</HostId></Error>```

**Comment by harshavardhana** [comment]
You need to setup etcd with `minio gateway` to avail STS feature.
