### ISSUE TITLE
Copying files within minio (S3 -> S3) fails

### ISSUE THREAD

**Issue by AntiPaste** [minio/minio#1071]
Using AWS SDK for Go copying a file within minio creates an empty file (0 bytes).

``` golang
_, err = svc.CopyObject(&s3.CopyObjectInput{
    Bucket:     aws.String("test"),
    CopySource: aws.String("source"),
    Key:        aws.String("destination"),
})
```

Above example creates an empty file called `destination` regardless of the size of the `source` file.
s3cmd seems to fail in a different way, refusing to copy the file at all:

``` plaintext
$ s3cmd ls s3://test
2016-02-02 11:47    112907   s3://test/source
$ s3cmd -v cp s3://test/source s3://rakennustieto/destination
INFO: Summary: 1 remote files to copy
$ echo $? # return code
1
$ s3cmd ls s3://test
2016-02-02 11:47    112907   s3://test/source
```

**Comment by krishnasrinivas** [comment]
@AntiPaste minio does not support [CopyObject](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html)

**Comment by harshavardhana** [comment]
Apart from what @krishnasrinivas already said @AntiPaste - what you are attempting would mean x-amz-copy-source is minio server,  CopyObject is a feature which works well with in Amazon and its regions alone. Amazon will have no idea of what minio's credentials are and where it could even read the data from. 

To copy from 'minio server' to s3 we have a easy to use tool called [mc](https://github.com/minio/mc), 'mc' implements 'mc mirror' which basically helps you keep multiple sites in sync.

**Comment by harshavardhana** [comment]
This out of scope for 'minio' closing.
