### ISSUE TITLE
[openID, WSO2] - self-signed certificate doesn't work

### ISSUE THREAD

**Issue by jaxWR** [minio/minio#10716]
I'm trying to run a minio server with `identity_openid > config_url` set to a WSO2 running on localhost.

Problem is, no matter how I create the credentials (self-signed), minIO complains  --on startup-- that `Error: Unable to initialize OpenID: Get "https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration": x509: certificate signed by unknown authority`

More info @ steps-to-reproduce

## Expected Behavior

MinIO accepts the self-signed credentials. Or at least gives a meaningful error.
I'm getting that same error even if the /certs folder is empty, so I don't even know if minio is really reading the credentials.

An `--insecure` flag for localhost or something like that could also work.

## Current Behavior

Getting `Error: Unable to initialize OpenID: Get "https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration": x509: certificate signed by unknown authority`

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Create a certificate. I have tried with
    * https://golang.org/src/crypto/tls/generate_cert.go
    * `openssl req -newkey rsa:2048 -x509 -nodes -keyout key.pem -new -out cert.pem -config req.cfg -sha256 -days 3650` having a req.cfg file
    * other openssl approaches
    * using WSO2s wso2carbon.jks file to generate the cert (`keytool -export -alias wso2carbon -file carbon_public2.crt -keystore wso2carbon.jks -storepass wso2carbon`)
2. Move the cert to __home__/.minio/certs
3. Rename key to `private.key` and cert to `public.cert`
4. [re]start minio

## Context

trying to implement [this](https://github.com/aarushiarya/minio-idp)

## Regression

No

## Your Environment

* minio.exe version RELEASE.2020-10-18T21-54-12Z
* No special setup except OpedIDs config_url. Starting server with `.\minio.exe server C:\__some__folder__`
* Win10 Pro 
* WSO2 running on docker @ localhost:9443

**Comment by harshavardhana** [comment]
> * using WSO2s wso2carbon.jks file to generate the cert (`keytool -export -alias wso2carbon -file carbon_public2.crt -keystore wso2carbon.jks -storepass wso2carbon`)

the certs need to be kept at ~/.minio/certs/CAs to trust the identity provider.

**Comment by jaxWR** [comment]
> the certs need to be kept at ~/.minio/certs/CAs to trust the identity provider.

already tried that

same error

**Comment by harshavardhana** [comment]
You need to put the WSO2 certs in `.minio/certs/CAs`  - i.e `carbon_public2.crt`

**Comment by jaxWR** [comment]
yes, I already did that. Forgot to mention it on steps to reproduce.

Got `Error: Unable to initialize OpenID: Get "https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration": x509: certificate signed by unknown authority`

Also tried with 127.0.0.1 instead of localhost (just in case). No joy

**Comment by harshavardhana** [comment]
@jaxWR then your cert is not really meant for this URL - try `curl` with the public cert for WSO2

**Comment by harshavardhana** [comment]
also on windows, the certs-dir is present in the users HOMEDIR check what is the default by look at the `minio --help`

**Comment by jaxWR** [comment]
> what is the default by look at the minio --help

`-certs-dir value path to certs directory (default: "C:\\Users\\___me_____\\.minio\\certs")`

already tried pointing --certs-dir to a different path containing certs, didn't really make any difference so I switched back to defaults.


----
> @jaxWR then your cert is not really meant for this URL - try curl with the public cert for WSO2

if I first import the  `carbon_public2.crt` into Windows' mmc, and then `curl https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration`  I get 


```

StatusCode        : 200
StatusDescription :
Content           : {"request_parameter_supported":true,"claims_parameter_supported":true,"introspection_endpoint":"htt
                    ps://localhost:9443/oauth2/introspect","Response_modes_supported":["query","fragment","form_post"],
                    "s...
RawContent        : HTTP/1.1 200
                    X-Frame-Options: DENY
                    X-Content-Type-Options: nosniff
                    X-XSS-Protection: 1; mode=block
                    Keep-Alive: timeout=60
                    Connection: keep-alive
                    Content-Length: 2195
                    Content-Type: application/...
Forms             : {}
Headers           : {[X-Frame-Options, DENY], [X-Content-Type-Options, nosniff], [X-XSS-Protection, 1; mode=block],
                    [Keep-Alive, timeout=60]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 2195
```

that means the cert is working ok, right?

**Comment by jaxWR** [comment]
But I'm still getting `Error: Unable to initialize OpenID: Get "https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration": x509: certificate signed by unknown authority` on the minio side

If it's any help, when the minio server starts it logs:

```
[The error logs here]

...

Certificate:
    Signature Algorithm: SHA256-RSA
    Issuer: C=US, ST=VA, UnknownOID=2.5.4.7, O=MyCompany, OU=MyDivision, CN=localhost
    Validity
        Not Before: Tue, 20 Oct 2020 16:44:30 GMT
        Not After : Fri, 18 Oct 2030 16:44:30 GMT

```

**Comment by jaxWR** [comment]
so the certificates work, but not for minio

is there any specific version these certs should be to work for minio? those are v3
