### ISSUE TITLE
Long timeout connecting to https://dl.min.io before run process

### ISSUE THREAD

**Issue by aleksandpetrov** [minio/minio#10723]
Thank you for closed my issue #10674  without debug and research. Way to go guys!

When I trying run simple server like "./minio server /data", the process trying resolve name dl.min.io before start and trying connect to it(WHY???). My server can resolve all DNS records, but doesn't have access to Internet. As a result, I have to wait about 20 min until happens a timeout. 

tcpdump output:
    10.70.31.15.53 > 10.70.31.196.55174: [udp sum ok] 40353 q: A? dl.min.io. 1/4/8 dl.min.io. [3m43s] A 178.128.69.202 ns: min.io. [19h16m54s] NS ns-cloud-e3.googledomains.com., min.io. [19h16m54s] NS ns-cloud-e1.googledomains.com., min.io. [19h16m54s] NS ns-cloud-e4.googledomains.com., min.io. [19h16m54s] NS ns-cloud-e2.googledomains.com. ar: ns-cloud-e1.googledomains.com. [7h12m42s] A 216.239.32.110, ns-cloud-e1.googledomains.com. [19h41m27s] AAAA 2001:4860:4802:32::6e, ns-cloud-e4.googledomains.com. [1d9h30m46s] A 216.239.38.110, ns-cloud-e4.googledomains.com. [19h41m27s] AAAA 2001:4860:4802:38::6e, ns-cloud-e3.googledomains.com. [22h9m35s] A 216.239.36.110, ns-cloud-e3.googledomains.com. [19h41m27s] AAAA 2001:4860:4802:36::6e, ns-cloud-e2.googledomains.com. [22h39m34s] A 216.239.34.110, ns-cloud-e2.googledomains.com. [19h41m27s] AAAA 2001:4860:4802:34::6e (340)
    10.70.31.196.58936 > 178.128.69.202.443: Flags [P.], cksum 0x2338 (incorrect -> 0x59ee), seq 0:189, ack 1, win 229, options [nop,nop,TS val 2590971309 ecr 3918460386], length 189
 00:00:00.188412 IP (tos 0x0, ttl 64, id 44881, offset 0, flags [DF], proto TCP (6), length 52)
    10.70.31.196.58936 > 178.128.69.202.443: Flags [.], cksum 0x227b (incorrect -> 0x0dfa), seq 189, ack 4204, win 294, options [nop,nop,TS val 2590971497 ecr 3918460673], length 0
 00:00:00.005087 IP (tos 0x0, ttl 64, id 44882, offset 0, flags [DF], proto TCP (6), length 145)
----- many are the same strings ------

If DNS has disabled or has set fake env "http_proxy", like "http_proxy="fake" ./minio server /data", this problem is fixed.

**Comment by vadmeste** [comment]
Maybe we can use MINIO_UPDATE to disable checking for update as well, what do you think @harshavardhana ?

**Comment by aleksandpetrov** [comment]
> Maybe we can use MINIO_UPDATE to disable checking for update as well, what do you think @harshavardhana ?

 If run "MINIO_UPDATE=off ./minio server /data" does not affect any.

**Comment by harshavardhana** [comment]
The timeout is actually a DNS timeout looks like this timeout is not related to our code.

**Comment by aleksandpetrov** [comment]
> The timeout is actually a DNS timeout looks like this timeout is not related to our code.

It undoubtedly related to your code , because your code need DNS for simple run. I think this behavior is wrong.  I will be grateful the ability to manage external connections in minio.

**Comment by harshavardhana** [comment]
> It undoubtedly related to your code , because your code need DNS for simple run. I think this behavior is wrong. I will be grateful the ability to manage external connections in minio.

We cannot do that we have reasons to have this in place, @aleksandpetrov you are free to modify the code and use it the way you want it.

**Comment by harshavardhana** [comment]
@aleksandpetrov you can also enable `minio --quiet` to turn off sending requests to dl.min.io
