### ISSUE TITLE
error running latest Minio binary on CentOS 7

### ISSUE THREAD

**Issue by ghost** [minio/minio#10725]
Error running latest minio binary on CentOS 7

## Expected Behavior
After browser download/curl/wget of https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2020-10-18T21-54-12Z, chmod +x, the binary should run Minio in the appropriate mode.

## Current Behavior
Using browser download/curl/wget of https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2020-10-18T21-54-12Z followed by a `chmod +x`, I issue the following command to start Minio in gateway mode to Amazon S3:
`MINIO_ACCESS_KEY=myaccesskey MINIO_SECRET_KEY=mysecretkey ./minio gateway --quiet --address ":9000" s3`. This results in the following error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x947195]

goroutine 44 [running]:
github.com/minio/minio/cmd/http.DialContextWithDNSCache.func1(0x20e4c20, 0xc0000ba010, 0x1da9d22, 0x3, 0xc000f5af60, 0x12, 0x0, 0x0, 0x0, 0x0)
	github.com/minio/minio/cmd/http/dial_dnscache.go:60 +0xd5
net/http.(*Transport).dial(0xc0000fa000, 0x20e4c20, 0xc0000ba010, 0x1da9d22, 0x3, 0xc000f5af60, 0x12, 0x0, 0x0, 0x0, ...)
	net/http/transport.go:1141 +0x1fd
net/http.(*Transport).dialConn(0xc0000fa000, 0x20e4c20, 0xc0000ba010, 0x0, 0xc000f66e60, 0x4, 0xc000f5af60, 0x12, 0x0, 0xc0004a50e0, ...)
	net/http/transport.go:1575 +0x1abb
net/http.(*Transport).dialConnFor(0xc0000fa000, 0xc000807b80)
	net/http/transport.go:1421 +0xc6
created by net/http.(*Transport).queueForDial
	net/http/transport.go:1390 +0x40f

Environment:
uname -a: `Linux myhostname 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
cat /etc/redhat-release: `CentOS Linux release 7.8.2003 (Core)`

**Comment by vadmeste** [comment]
@kb-braintrust this is already fixed and the fix will be released soon.
