### ISSUE TITLE
bucket creation with secret key

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10721]
**Is your feature request related to a problem? Please describe.**
How  to create bucket with different secret key.

**Describe the solution you'd like**
Need to create bucket with different secret key and don't want to use the same secret and access key which we generated while setting up minio

**Describe alternatives you've considered**
Please advice how to resolve my above issues.

**Additional context**

**Comment by harshavardhana** [comment]
Creating credentials and bucket are different process - you don't create a bucket with credentials 

https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html doc explains how to associate a user to a bucket.

**Comment by LiginGeorge** [comment]
created a user called ligin2 and created and assigned policy to the user. But after login to minio browser still i  am not able to create  bucket by using ligin2 user getting "Do not have enough permissions to access this resource"

[wlpadmin@minio1 ~]$ ./mc admin user info minio1 ligin2
AccessKey: ligin2
Status: enabled
PolicyName: ligin2policy
MemberOf:
[wlpadmin@minio1 ~]$ ./mc admin policy info minio1 ligin2policy
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Sid": "Stmt1603268843714",
   "Effect": "Allow",
   "Action": [
    "s3:*"
   ],
   "Resource": [
    "arn:aws:s3:::ligin2"
   ]
  }
 ]
}

**Comment by LiginGeorge** [comment]
Hi,

Any idea how to resolve this issue , by assigning policy to the user to create bucket ?

**Comment by klauspost** [comment]
@LiginGeorge We do not provide support here.

Feel free to join the [community slack](https://slack.min.io/) or look into our [commercial support options](https://min.io/pricing).
