### ISSUE TITLE
Policy does not work as expected

### ISSUE THREAD

**Issue by armsby** [minio/minio#10722]
I have an application that I would like to be able to read notification from a bucket, if I use the default readwrite policy on my user I can listen to them but I would like to limit the allowed action from s3:*

this should be possible as I can get them if I allow s3:* in my policy 

I have created the following policy that I expect to work:

{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Deny",
   "Action": [
    "s3:CreateBucket",
    "s3:DeleteBucket"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:PutObject",
    "s3:DeleteObject",
    "s3:GetObject",
    "s3:GetObjectVersion",
    "s3:ListBucket",
    "s3:GetBucketLocation",
    "s3:ListenNotification",
    "s3:GetBucketNotification"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}

but I keep getting a 403 Forbidden on the s3.ListenNotification

## Expected Behavior
my application would receive the configured notification for that bucket

## Current Behavior
403 access forbidden to ListenNotification

## Your Environment
RELEASE.2020-10-03T02-54-56Z

**Comment by vadmeste** [comment]
It looks like a bug, thanks for reporting it, I will will investigate.

**Comment by vadmeste** [comment]
@armsby I tested with ListenNotification() of minio-go and it works fine, you can test as well with `mc watch` . Most likely your application is doing other things not allowed in your policy document. You can check what S3 requests arriving to your server from your application using `mc admin trace` command.

Closing this, please reopen if you see issues with `mc watch` on your side.

**Comment by armsby** [comment]
mc config: block1
  URL       : http://block1.local:9000
  AccessKey : test
  SecretKey : REDACTED
  API       : s3v4
  Path      : auto

user config:
 mc admin user info block1 test
AccessKey: test
Status: enabled
PolicyName: test
MemberOf:

current policy: mc admin policy info block1 test
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Deny",
   "Action": [
    "s3:CreateBucket",
    "s3:DeleteBucket"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:DeleteObject",
    "s3:GetBucketLocation",
    "s3:GetBucketNotification",
    "s3:GetObject",
    "s3:GetObjectVersion",
    "s3:ListBucket",
    "s3:ListenNotification",
    "s3:PutObject"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}

mc command: mc watch --events put,delete block1/New
mc: <ERROR> Unable to watch for events. Access Denied.

mc trace 
storage.crafting.dk [REQUEST s3.GetBucketLocation] 12:26:13.628
storage.crafting.dk GET /New/?location=
storage.crafting.dk Proto: HTTP/1.1
storage.crafting.dk Host:REDACTED:19000
storage.crafting.dk Authorization: AWS4-HMAC-SHA256 Credential=test/20201021/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=206e3356adeac1704e6df844211cbdd73bd9428d84dc28d3e8e9a73d3bdd0328
storage.crafting.dk Content-Length: 0
storage.crafting.dk User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-23T20:02:13Z
storage.crafting.dk X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
storage.crafting.dk X-Amz-Date: 20201021T122613Z
storage.crafting.dk
storage.crafting.dk [RESPONSE] [12:26:13.628] [ Duration 257µs  ↑ 77 B  ↓ 378 B ]
storage.crafting.dk 200 OK
storage.crafting.dk Vary: Origin
storage.crafting.dk X-Amz-Request-Id: 1640018D467A3500
storage.crafting.dk X-Xss-Protection: 1; mode=block
storage.crafting.dk Accept-Ranges: bytes
storage.crafting.dk Content-Length: 128
storage.crafting.dk Content-Security-Policy: block-all-mixed-content
storage.crafting.dk Content-Type: application/xml
storage.crafting.dk Server: MinIO/RELEASE.2020-10-03T02-54-56Z
storage.crafting.dk <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
storage.crafting.dk
storage.crafting.dk [REQUEST s3.ListenNotification] 12:26:13.629
storage.crafting.dk GET /New/?events=s3%3AObjectAccessed%3A%2A&events=s3%3AObjectRemoved%3A%2A&prefix=&suffix=
storage.crafting.dk Proto: HTTP/1.1
storage.crafting.dk Host: REDACTED:19000
storage.crafting.dk Content-Length: 0
storage.crafting.dk User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-23T20:02:13Z
storage.crafting.dk X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
storage.crafting.dk X-Amz-Date: 20201021T122613Z
storage.crafting.dk Authorization: AWS4-HMAC-SHA256 Credential=test/20201021/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0b127b703ef5501365f8601ebfc6bd7aa2d9fda300fa792737edf2c72d18e6ae
storage.crafting.dk
storage.crafting.dk [RESPONSE] [12:26:13.629] [ Duration 347µs  ↑ 77 B  ↓ 515 B ]
storage.crafting.dk 403 Forbidden
storage.crafting.dk Content-Security-Policy: block-all-mixed-content
storage.crafting.dk Content-Type: application/xml
storage.crafting.dk Server: MinIO/RELEASE.2020-10-03T02-54-56Z
storage.crafting.dk Vary: Origin
storage.crafting.dk X-Amz-Request-Id: 1640018D46872A71
storage.crafting.dk X-Xss-Protection: 1; mode=block
storage.crafting.dk Accept-Ranges: bytes
storage.crafting.dk Content-Length: 258
storage.crafting.dk <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>New</BucketName><Resource>/New/</Resource><RequestId>1640018D46872A71</RequestId><HostId>6448996f-0fac-4a53-8e77-f6fd4f0c9d3d</HostId></Error>

**Comment by armsby** [comment]
I cant get it to work with mc watch

**Comment by armsby** [comment]
I might not be using go, but this is my test script 

from minio import Minio
from minio.error import ResponseError

minio = Minio(
    'storage.crafting.dk',
    access_key='test',
    secret_key='REDACTED',
    secure=True,
)
iter = minio.listen_bucket_notification(
    "test",
    events=['s3:ObjectCreated:*', 's3:ObjectAccessed:*']
)

for events in iter:
    print(events)


it can not be more simple and it works when action is s3:*

**Comment by vadmeste** [comment]
oh, you are missing this permission actually ```s3:ListenBucketNotification``` in your policy document. Could you try it and see if it works?

**Comment by armsby** [comment]
thank you, that did it

**Comment by armsby** [comment]
that seams to have fixed it, thank you, I would love some better documentation around policy's as they are not 100% a match to aws

**Comment by kannappanr** [comment]
@armsby Can you give an example on where you feel it is not a match?

**Comment by armsby** [comment]
s3:ListenBucketNotification
s3:ListenNotification

are not listed in the AWS s3 documentation, I only get as far as I did with the trace tool and would never have found the last one

as AWS pushes this over SQS, it might be there, but I did not find it also it would be nice to be able to limit events like this 
  {
   "Effect": "Allow",
   "Action": [
     "s3:ListenNotification",
     "s3:ListenBucketNotification"
   ],
   "Event": [
     "s3:ObjectCreated:*",
     "s3:ObjectRemoved:*"
   ],
   "Resource": [
     "arn:aws:s3:::*"
   ]
  }
or with a conditions, if im wrong and it is documented in the AWS s3 policy documentation im sorry and would you please give me a link as I have not found it

**Comment by harshavardhana** [comment]
> as AWS pushes this over SQS, it might be there, but I did not find it also it would be nice to be able to limit events like this
> {
> "Effect": "Allow",
> "Action": [
> "s3:ListenNotification",
> "s3:ListenBucketNotification"
> ],

ListenBucketNotification is our implementation @armsby not AWS S3. You cannot have event-based selection in this manner. 

Just add s3:ListenBucketNotification to your `bucket` or all the resources and it will work.

**Comment by kannappanr** [comment]
@armsby We are sort of revamping our documentation, we will see how we can incorporate information like these.

**Comment by armsby** [comment]
thank you, I really like the software
