### ISSUE TITLE
docs/sts/web-identity.go uses v6 api and fails with v7

### ISSUE THREAD

**Issue by stefan-enway** [minio/minio#10737]
if i try to run go run docs/sts/web-identity.go as described in https://github.com/minio/minio/blob/master/docs/sts/keycloak.md
it will fail with docs/sts/web-identity.go:224:16: undefined: minio.NewWithOptions

## Expected Behavior
should not complain

## Current Behavior
undefined message

## Possible Solution
a) use v6 in line 38 and 39
b) learn how to fix it and open an PR for it (i will have a look ;)

## Steps to Reproduce (for bugs)
go run docs/sts/web-identity.go

## Context
tried to check my keycloak setup

## Your Environment

minio version DEVELOPMENT.2020-10-22T13-45-01Z
server not really needed
Ubuntu 18.04 with go version go1.15.2 linux/amd64

**Comment by harshavardhana** [comment]
Feel free to send a fix @stefan-enway

**Comment by harshavardhana** [comment]
closed by 4442382c168a453e4159312833a4d7712d3b5d44
