### ISSUE TITLE
Does Minio have an interface to display the upload or download progress bar and the size of the current file when uploading or downloading

### ISSUE THREAD

**Issue by gallop1** [minio/minio#10731]
Does Minio have an interface to display the upload or download progress bar and the size of the current file when uploading or downloading？I want to have these two interfaces, but I can't find them in the official website. Please explain it to the developer.

**Comment by vadmeste** [comment]
> Does Minio have an interface to display the upload or download progress bar and the size of the current file when uploading or downloading？

Which MinIO SDK are you referring to ?

**Comment by klauspost** [comment]
No. The MinIO server itself does not provide that. Your developer will likely have to implement that.

Feel free to join community slack where other users can help with this sort of issues: https://slack.min.io/

**Comment by gallop1** [comment]
@vadmeste Minio 3.1.13.0 this version
