### ISSUE TITLE
Remove type "event" for elasticsearch notification target

### ISSUE THREAD

**Issue by jbertozzi** [minio/minio#10732]
In Elasticsearch version > 6 support for types [has been removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html).

The notification target elasticsearch is making use of this feature, which cause events to not be properly indexed out of the box.

## Expected Behavior

The type should be set to "_doc".

The elasticsearch URL called should be "http://elastic:9200/index" and not http://elastic:9200/index/_event"

## Current Behavior

Document are created with type "event" instead of "_doc".

## Possible Solution

Add a settings to elasticsearch notification target to let minio know how to send the events.

## Steps to Reproduce (for bugs)

1. Configure MinIO server
2. Configure elasticsearch server
3. Enable notification bucket (`mc admin config set <minio>notify_elasticsearch enable=on url="http://selasticsearch:9200" format="access" index="minio-event" queue_dir=""`)
4. Configure a bucket with notification event enabled (`mc mb <minio>/mybucket ; mc event add <minio>/mybucket arn:minio:sqs::1:elasticsearch`)
5.  Generate an event by writing an object (`mc cp <file> <minio>/mybucket/`)
6. Check for the document created, it has the type is set to "event"

## Your Environment
* Version used: RELEASE.2020-10-18T21-54-12Z
* Operating System and version (`uname -a`): Linux 4.18.0-193.13.2.el8_2.x86_64 #1 SMP Mon Jul 13 23:17:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by donatello** [comment]
Still working on upgrading the elasticsearch notifications to a new library as there exists an official golang library now - https://github.com/elastic/go-elasticsearch - this should solve this current problem. We will also be moving to requiring the latest elasticsearch 7.x release.

**Comment by harshavardhana** [comment]
> Still working on upgrading the elasticsearch notifications to a new library as there exists an official golang library now - https://github.com/elastic/go-elasticsearch - this should solve this current problem. We will also be moving to requiring the latest elasticsearch 7.x release.

@donatello are you still working on this?

**Comment by donatello** [comment]
I have a branch with some work for this but it's not complete yet. I am going to come back to this next week.

**Comment by donatello** [comment]
This is merged to master and available in the latest release.
