### ISSUE TITLE
[not our bug] minio-notifications-in-splunk

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10736]
**Is your feature request related to a problem? Please describe.**
i was trying to configure minio notification  for splunk and  below command i executed part of that.

[root@test1 minioqmg]# ./mc admin config set nqdqmg audit_webhook enable=on endpoint=http://10.0.3.1:8088/services/collector/raw auth_token="Splunk29b217c3-ac0c-4712-bc82-8fbd0e7c4930"
Setting new key has been successful.
Please restart your server with `mc admin service restart nqdqmg`.

[root@test1 minioqmg]# ./mc admin service restart nqdqmg
Restart command successfully sent to `nqdqmg`.
Failed to restart `nqdqmg`. error: invalid character '<' looking for beginning of value

**Describe the solution you'd like**
Now i am not able to list service status by using following command 
./mc admin --debug info nqdqmg  and getting below error.

[root@test1 minioqmg]# ./mc admin --debug info nqdqmg
mc: <DEBUG> GET /minio/admin/v3/info HTTP/1.1
Host: 10.12.205.207:9006
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-10-01T06:06:18Z
Authorization: AWS4-HMAC-SHA256 Credential=test1/20201022//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201022T102828Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2267
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: text/html; charset=utf-8
Date: Thu, 22 Oct 2020 10:28:28 GMT
Last-Modified: Fri, 12 Apr 2019 09:34:09 GMT
Vary: Origin
X-Amz-Request-Id: 164049B4F1B33DA4
X-Minio-Deployment-Id: 8de9e1e6-e265-4197-8af5-3cb3b8cd0872
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1.150518ms

mc: <ERROR> Unable to get service status: invalid character '<' looking for beginning of value
 (0) admin-info.go:81 cmd.clusterStruct.String(..)
 Release-Tag:DEVELOPMENT.2020-10-01T06-06-18Z | Commit:177f15db2ea2 | Host:test1 | OS:linux | Arch:amd64 | Lang:go1.15.1 | Mem:2.7 MB/74 MB | Heap:2.7 MB/67 MB.

i have used new mc to configure the webhook  and it was running with one year old mc.

**Describe alternatives you've considered**

**Additional context**

**Comment by vadmeste** [comment]
@LiginGeorge what's your MinIO server version ?

**Comment by LiginGeorge** [comment]
./mc --version
mc version DEVELOPMENT.2020-10-01T06-06-18Z
 ./minio version
Version: 2019-04-23T23:50:36Z
Release-Tag: RELEASE.2019-04-23T23-50-36Z
Commit-ID: 35d19a4ae287179a0c7d6938b2b1c8e63b4747c1

**Comment by harshavardhana** [comment]
> /mc --version
> mc version DEVELOPMENT.2020-10-01T06-06-18Z
> ./minio version
> Version: 2019-04-23T23:50:36Z
> Release-Tag: RELEASE.2019-04-23T23-50-36Z
> Commit-ID: [35d19a4](https://github.com/minio/minio/commit/35d19a4ae287179a0c7d6938b2b1c8e63b4747c1)

mc too new for very old MinIO version please refer to the release notes to see compatibility.

**Comment by LiginGeorge** [comment]
Hi,
 
 updated with the new version still not able to find see logs in Splunk. Is it supported by minio to push the events to splunk.
[wlpadmin@minio1 ~]$ ./mc --version
mc version RELEASE.2020-11-25T23-04-07Z
[wlpadmin@minio1 ~]$ ./minio --version
minio version RELEASE.2020-11-25T22-36-25Z
[wlpadmin@minio1 ~]$

**Comment by klauspost** [comment]
@LiginGeorge Upgrade the MinIO server version, not only mc.

**Comment by LiginGeorge** [comment]
Hi,

 I have mentioned minio version also apart from mc

[wlpadmin@minio1 ~]$ ./minio --version
minio version RELEASE.2020-11-25T22-36-25Z
[wlpadmin@minio1 ~]$
