### ISSUE TITLE
[faq] Are there the Maximum number of objects per bucket limit by inode of linux system?

### ISSUE THREAD

**Issue by wuweiminhuo** [minio/minio#10733]
I want to make sure whether the maximum number of objects per bucket is no-limit?
because i want to put ten million images into one bucket without other directory, but when i saw the file location is also create the directory of bucket and the object in the disk, if there are so many images in same directory , should limit by the inode of linux system?  so that is have limit.
could anybody reply my question?

**Comment by klauspost** [comment]
Yes. And 10M files at the same prefix level will likely be slow because of FS limitations.

Please use community slack for similar questions and followup: https://slack.min.io/
