### ISSUE TITLE
madmin.InfoMessage.Backend seems to not conform to associated structs

### ISSUE THREAD

**Issue by venezia** [minio/minio#10740]
While the type for madmin.Infomessage.Backend is `interface{}`, it doesn't seem to be able to be cast to known backends, namely `madmin.FSBackend` or `madmin.ErasureBackend`

## Expected Behavior
I would expect something like to work
```go
	switch backend := info.Backend.(type) {
	case madmin.FSBackend:
		// do something fun
	case madmin.ErasureBackend:
		// do something else fun
	default:
		// oh noes, we don't have one of the known backends
	}
```

## Current Behavior
```go
	fmt.Printf("%T", info.Backend)
```
returns `map[string]interface{}`, thus the default case is always coming up

## Possible Solution
I think the `madmin.ServerInfo(...)` method's line
```go
	err = json.Unmarshal(respBytes, &message)
```
may need a bit of tuning with respect to how to handle Endpoint being an empty interface - to see if that portion can be cast as one of the known types, etc.

Right now I can do something like 
```go
	backendMap, ok := input.(map[string]interface{})
	if ok {
		if backend, ok := backendMap["backendType"].(string); ok {
			if backend == string(madmin.FsType) {
```

but it is rather clunky, not to mention that the integer values in `ErasureBackend` are cast to float64...
```go
	if offlineDisks, ok := backendMap["offlineDisks"].(float64); ok {
		realOfflineDisks = int(offlineDisks)
	}
```

## Steps to Reproduce (for bugs)

* I ran a small go program that imported github.com/minio/minio/pkg/madmin
* it called madmin.ServerInfo on a 2-node minio environment with erasure (two disks each node)
* version of the minio server was 2020-09-23T19:18:30Z

## Context
It just makes it harder to utilize that node of data from ServerInfo.  I suspect `mc admin` CLI calls just json output the `madmin.InfoMessage` struct so it never really surfaced, but that's purely speculation 

## Regression
Not a regression

## Your Environment
* Version used (`minio --version`): 2020-09-23T19:18:30Z commit id: f7f9517b6ae297210aca2a68416e298396c07076
* Server setup and configuration: two node minio environment, each with two disks, erasure enabled
* Operating System and version (`uname -a`): Linux, 4.15.0-112-generic, Ubuntu 18.04.4

**Comment by harshavardhana** [comment]
Here is the solution 

```
        // MinIO server type default
        backendType := "Unknown"
        // Set the type of MinIO server ("FS", "Erasure", "Unknown")
        v := reflect.ValueOf(u.Info.Backend)
        if v.Kind() == reflect.Map {
                for _, key := range v.MapKeys() {
                        val := v.MapIndex(key)
                        switch t := val.Interface().(type) {
                        case string:
                                backendType = t
                        }
                }
        }
```
