### ISSUE TITLE
[faq] how do I synchronize files from external systems to Minio?

### ISSUE THREAD

**Issue by shenzgang** [minio/minio#10743]
How do I synchronize files from external systems to Minio?Can inotify and rsync synchronize?How do I do that? Thank you!

**Comment by harshavardhana** [comment]
you can use `mc mirror --watch` @shenzgang

**Comment by shenzgang** [comment]
thank you!

**Comment by shenzgang** [comment]
hello @harshavardhana,As you have suggested, the synchronization is now complete. Can you get the file information, such as the file name, and route to different buckets according to the file type? Or can you define some business processes yourself? thanks!
