### ISSUE TITLE
Unmounting disk not recognised by minio

### ISSUE THREAD

**Issue by csbarry** [minio/minio#10747]
When trying to simulate a disk failure by unmounting a disk (/data/disk19) I see the following errors in /var/log/syslog

Oct 23 13:18:20 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Disk `/data/disk19` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Oct 23 13:18:20 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found drives to heal 1, proceeding to heal content...
Oct 23 13:18:31 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Disk `/data/disk19` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Oct 23 13:18:31 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found unformatted drive http://node01:9000/data/disk19, attempting to heal...
Oct 23 13:18:32 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found drives to heal 1, proceeding to heal content...
Oct 23 13:18:42 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Disk `/data/disk19` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Oct 23 13:18:43 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found drives to heal 1, proceeding to heal content...
Oct 23 13:18:46 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found unformatted drive http://node01:9000/data/disk19, attempting to heal...
Oct 23 13:18:54 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Disk `/data/disk19` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Oct 23 13:18:54 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found drives to heal 1, proceeding to heal content...
Oct 23 13:19:01 dc-csdc-974a1a6bb30b725a1e-beta.sac1.csdc.beta minio[19851]:  Found unform

Mc admin info  does not show the disk offline, and prometheus stats still show the disk as online.

## Expected Behavior
I would expect that minio recognises that the disk is offline and marks it as such, then when the disk is re-mounted it should begin to heal.

## Current Behavior
Disk is not marked offline and errors posted above fill /var/log/syslog until the disk is remounted

## Steps to Reproduce (for bugs)
simply unmount any disk in use by minio

## Regression

no

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2020-10-18T21-54-12Z
* Server setup and configuration:   6 node distributed cluster with 60 jbod disks per node.
* Operating System and version (`uname -a`): Ubuntu 18.04.  Linux obj1-node01.sac1.dc 4.15.0-115-generic #116-Ubuntu SMP Wed Aug 26 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
When you remove the disk, a directory gets created on the root partition.

MinIO doesn't exclusively own the disk so there is nothing in MinIO to recognize a drive as such.

As the message indicates the disk is found to be offline and rejected since now the directory is at root disk.

Will check if we don't display healing terror instead report that it's a root disk and keep rejecting it.

**Comment by csbarry** [comment]
@harshavardhana Sorry im not quite following you.
What directory gets created on the root partition?.
What I have noticed is this, our disks are mounted under /data/disk{1 - 60)...If i unmount say disk 1 I get the errors posted above, if I delete while the disk is not mounted /data/disk1 the directory /data/disk1 is re-created by a minio process and the above errors continue.

My question is, if I unmount a disk should that disk not be marked as unavailable?,  if not what happens if I physically pull a disk from the server?, will I get the same error messages in the syslog and the disk still marked as active?
