### ISSUE TITLE
logging: Add logging across codebase

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1074]

**Comment by dreh23** [comment]
I believe [Prometheus](https://prometheus.io/) is a candidate for scalable metrics monitoring without reinventing the wheel. 
Other 3rd party Programms do integrate prometheus as well:
https://prometheus.io/docs/instrumenting/exporters/#directly-instrumentated-software

**Comment by harshavardhana** [comment]
> I believe Prometheus is a candidate for scalable metrics monitoring without reinventing the wheel. 
> Other 3rd party Programms do integrate prometheus as well:
> https://prometheus.io/docs/instrumenting/exporters/#directly-instrumentated-software

Prometheus is nice but this bug is regarding general logging inside the code

**Comment by sreeram-dev** [comment]
@harshavardhana I have experimented with Prometheus trying to scale it up. I prefer Influxdb and the TICK stack around it. Easy to work with and integrates really well with grafana.
The choice boils down to pull based vs push based monitoring.

Regarding scalable logging framework. Need more details. Can we use https://github.com/Sirupsen/logrus It has great hooks.

**Comment by harshavardhana** [comment]
> Regarding scalable logging framework. Need more details. Can we use https://github.com/Sirupsen/logrus It has great hooks.

We already do! 

> @harshavardhana I have experimented with Prometheus trying to scale it up. I prefer Influxdb and the TICK stack around it. Easy to work with and integrates really well with grafana.
> The choice boils down to pull based vs push based monitoring.

As of now we are not planning to do this.
