### ISSUE TITLE
feat: Use distinct secret key for minio and gateway backend

### ISSUE THREAD

**Issue by matiascognite** [minio/minio#10746]
I'm using minio as a gateway to azure blobstore.
The service I'm using, doesn't allow long keys > 64 characters. And even if it did, maybe I don't want to give it my azure credentials. 

Thus I'd like to have two secret keys - one for connecting to minio (MINIO_SECRET_KEY)
And another one for minio to connect to azure. This could default to MINIO_SECRET_KEY, but it would be very nice to be able to override it.

In the minio GCS gateway, we can set the GOOGLE_APPLICATION_CREDENTIALS environment variable, and have MINIO_SECRET_KEY be whatever we like.

**Comment by vadmeste** [comment]
There is an open PR for that https://github.com/minio/minio/pull/10943
