### ISSUE TITLE
[wont fix] public bucket replication

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10757]
**Is your feature request related to a problem? Please describe.**
I have created a bucket in PR site and set public policy and similar for DR as well. 
While enabling bucket replication we need access and a secret key which is generally not set for the public bucket and access will be open. I have created a user and assigned the public policy to the user and mentioned the bucket name also but getting below error
[wlpadmin@minio1 ~]$ ./mc admin bucket remote add minio1/test1 http://testuser:4c31ad822d8c911f0136e86a4be1cbc9@minio5:9001/test1 --service replication
mc: <ERROR> Unable to configure remote target. Remote service endpoint or target bucket not available.

**Describe the solution you'd like**

for public bucket how we can set the bucket replication between two clusters.

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
Bucket replication is as per AWS S3 spec, doesn't support anonymous public buckets. So MinIO doesn't support either.
