### ISSUE TITLE
GitLab CI integration not working 

### ISSUE THREAD

**Issue by matheusroleal** [minio/minio#10754]
## Expected Behavior
The expected behavior should be the correct caching at my minio instance. But for some reason, the gitlab is not communicating correctly with minio. It keeps showing the same message(`file does not exist`) even when there is data stored.

## Current Behavior
I get the following error when trying to use Minio for caching:
[0Ksection_start:1603226174:restore_cache
[0K[32;1mChecking cache for master...[0;m
[31;1mFATAL: file does not exist                        [0;m 
[0;33mFailed to extract cache[0;m

## Steps to Reproduce
I've configured my GitLab Runner to access container with Minio:
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "10.224.79.227:9000"
      AccessKey = "minio"
      SecretKey = "minio123"
      BucketName = "gitlab-runner"
      BucketLocation = "eu-west-1"
      Insecure = true

I've used the linux Minio package inside the container. I've configured the following environmental variables:
MINIO_ACCESS_KEY=minio
MINIO_PROMETHEUS_AUTH_TYPE=public
MINIO_REIGON=eu-west-1
MINIO_SECRET_KEY=minio123
MINIO_VOLUMES=/mnt/data

## Context
I'm setting a GitLab Runner using MinIO for caching

## Your Environment
* Version used (`minio --version`): RELEASE.2020-10-12T21-53-21Z
* Server setup and configuration: Docker container
* Operating System and version (`uname -a`): x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please send `mc admin trace` information from the server, also provide more setup details such as

- backend filesystem? 
- a sample workload that can help us reproduce it? 

Closing this issue as incomplete until then.
