### ISSUE TITLE
Dockerfile.arm64.release contains env variable without '\' at the end

### ISSUE THREAD

**Issue by d4ex** [minio/minio#10758]
Dockerfile.arm64.release contains env variable without '\\' at the end

## Current Behavior
Error message from docker build:
Error response from daemon: Dockerfile parse error line 12: unknown instruction: MINIO_UPDATE_MINISIGN_PUBKEY="RWTX5ZR1TIHQLWG9KECKT0C45M3AGEHD6IVIMQHPYRYWVWGBP1AVSGAV"

## Possible Solution
Add '\\' at line 11 :+1:

**Comment by harshavardhana** [comment]
@d4ex feel free to send a fix

**Comment by d4ex** [comment]
Hmpf to late :) I tried it shortly after opened the issue, but i got a 403 when i pushed the branch :( Dont know why

remote: Permission to minio/minio.git denied to d4ex.

**Comment by harshavardhana** [comment]
> remote: Permission to minio/minio.git denied to d4ex.

Of course, you don't have write access to MinIO repo - you need to fork.

**Comment by d4ex** [comment]
> > remote: Permission to minio/minio.git denied to d4ex.
> 
> Of course, you don't have write access to MinIO repo - you need to fork.

Yep that was the problem :) Next time i know what to do. Thanks
