### ISSUE TITLE
404 Not Found error

### ISSUE THREAD

**Issue by kkangkang789** [minio/minio#10767]
when i upload files , the conlose log  is as follows 

API: SYSTEM()
Time: 10:44:19 CST 10/27/2020
DeploymentID: cdec89e6-eabe-462a-a1dd-394cefa33b79
Error: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

       2: github.com/minio/minio@/cmd/notification.go:473:cmd.(*NotificationSys).updateBloomFilter.func1()
       1: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()

this is my start cmd  ./minio server http://xx.xxx.xxx.235/home/yangkang/data{1...4}

**Comment by harshavardhana** [comment]
Not sure what you are trying to report, there isn't much information closing as lack of info.
