### ISSUE TITLE
Minio S3 bucket versioning not working with Amazon S3 client/ SDK

### ISSUE THREAD

**Issue by dimuthu44** [minio/minio#10760]
Hi team, 

We are using Amazon S3 Java SDK (1.11.813) and StorageGrid environment for the moment.
And we are testing our application with Minio with bucket versioning enabled in the Amazon s3 client, this integration works fine with StorageGrid but in Minio we are getting an error. We took the code excerpts from Amazon S3 guide and like I said, we were able to run it fine with StorageGrid.
Please query back for further information should you need. TIA.

The error is:
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: A header you provided implies functionality that is not implemented (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented;

Client configuration: 

```
class DefaultSThreeClient(s3Client: AmazonS3)  {
     if (!s3Client.doesBucketExistV2(bucketName)) {
      s3Client.createBucket(bucketName)
      val bucketVersioningConfiguration = new BucketVersioningConfiguration(BucketVersioningConfiguration.ENABLED)
      val request = new SetBucketVersioningConfigurationRequest(bucketName, bucketVersioningConfiguration)
      s3Client.setBucketVersioningConfiguration(request)
    }


  case class EndPointConfig(region: Regions, endpoint: String)

  private var client: Option[DefaultSThreeClient] = None

  def createClient(): SThreeClient = {
    val sslConnectionFactory = new SSLConnectionSocketFactory(buildSSLContext.build(), Array("TLSv1.2"),
      null, NoopHostnameVerifier.INSTANCE)
    val conf = new ClientConfiguration()
    conf.getApacheHttpClientConfig.setSslSocketFactory(sslConnectionFactory)
    if (client.isEmpty) {
      val s3Credential = new BasicAWSCredentials(clientAccessKey, clientSecretKey)
      val amazonClient = AmazonS3ClientBuilder
        .standard()
        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(serviceEndpoint, Regions.US_EAST_1.name()))
        .withPathStyleAccessEnabled(false)
        .withCredentials(new AWSStaticCredentialsProvider(s3Credential))

       client = Option(new DefaultSThreeClient(amazonClient.build()))
     }
```
## Examples we referred
[https://docs.aws.amazon.com/AmazonS3/latest/dev/manage-versioning-examples.html](url)

## Expected Behavior
Should store the object in Minio S3

## Current Behavior
Throws an Exception

## Possible Solution
Probably versioning does not support Amazon SDKs way yet. But I could be wrong here.

## Steps to Reproduce (for bugs)
Using an Amazon SDK, create a versioning enabled bucket and store an object.

## Your Environment
Minio Version : 2020-10-12T21:53:21Z (Docker image)
Environment : Linux 5.4.0-52-generic #57~18.04.1-Ubuntu

**Comment by harshavardhana** [comment]
@dimuthu44 we do not support versioning in single drive mode, you need to use erasure-coded setup.
