### ISSUE TITLE
policy command fails with aws-cn regions in s3 gateway mode

### ISSUE THREAD

**Issue by danielfree** [minio/minio#10768]
## Expected Behavior
minio s3 gateway should properly list/get/set policies on S3 buckets located in aws-cn regions(cn-north-1, cn-northwest-1).

## Current Behavior

policy commands failed with error `invalid resource 'arn:aws-cn:s3:::*'`.

## Possible Solution

guess the minio policy api interface does not accept `arn:aws-cn:s3`,  only accept `arn:aws:s3`.
should be able to change that.

## Steps to Reproduce (for bugs)
1. set up minio as s3 gateway with endpoint in aws-cn, e.g. `minio gateway s3 https://s3.cn-northwest-1.amazonaws.com.cn/`
2. `mc alias set aws-cn http://localhost:9000 mykey mysecret`
3. `mc list policy aws-cn/my-bucket`
4. will get error `invalid resource 'arn:aws-cn:s3:::my-bucket/*'`

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2020-10-03T02-19-42Z
* Server setup and configuration:  standalone
* Operating System and version (`uname -a`): MacOS Darwin Kernel Version 19.6.0

**Comment by harshavardhana** [comment]
Unfortunately, this is expected and we have no way to test / validate this for china region.  Feel free to send a fix if you wish us to get this support in.
