### ISSUE TITLE
bucket not deleting after updated mc

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10774]
Bucket not deleting after updated mc and its not responding after that.

## Expected Behavior

when we delete the bucket it's not responding after that. 

## Current Behavior
[wlpadmin@minio1 ~]$ ./mc rb --force minio1/public  -- not responding after this

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Not much information to go about.
