### ISSUE TITLE
[wontfix] Enhanced listing API: Sort files and directories in listing, limit the results, allow pagination

### ISSUE THREAD

**Issue by KrishnaPG** [minio/minio#10771]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to get the `list of last 10 modified files/objects/buckets` through API

While earlier issues, such as https://github.com/minio/minio/issues/7252 have been closed citing "S3 does not have this feature" as reason - S3 is not a golden yardstick. Just because S3 does a lousy job of providing bad API, does not necessarily mean `minio` should follow suit and not have its own extended API.

**Describe the solution you'd like**
An extended API that allows 

1. querying the contents (buckets / objects) based on metadata, filenames 
2. limits the number of results 
3. pagination of results (in a result set of 100, start from 50 and give the next 10)

**Describe alternatives you've considered**
Using native file system APIs.

**Additional context**
The proposed API is "in addition" to the base S3 API, so it should not create problem for those who want to just stick to S3.

**Comment by klauspost** [comment]
>  minio [should] have its own extended API

That is contrary to the goal of MinIO. You are welcome to fork MinIO to extend the API.
