### ISSUE TITLE
It always reminds me "waiting for the first server to format the disks."

### ISSUE THREAD

**Issue by thewholeworld** [minio/minio#10781]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I divided a disk into two regions of the same size and mounted it on two folders. Both hosts did the same. After I start the script, the command line says "waiting for the first server to format the disks.".
## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-09-17T04-49-20Z
* Server setup and configuration: 
The config below：
#!/bin/bash
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin123

./minio server http://172.16.5.{7...8}/data{1...2}

* Operating System and version (`uname -a`): centos7.4

**Comment by harshavardhana** [comment]
> I divided a disk into two regions of the same size and mounted it on two folders. Both hosts did the same. After I start the script, the command line says "waiting for the first server to format the disks.".

your networking is not available here @thewholeworld - there are like zillions of deployments in this manner. So this is a setup issue.

**Comment by thewholeworld** [comment]
There is no problem with network configuration. I want to ask whether it is possible to partition a hard disk into two identical zones, and then mount the file directory through the zone. Is this allowed? When I do, it always reminds me 'waiting for the first server to format the disks.' @harshavardhana

**Comment by harshavardhana** [comment]
> There is no problem with network configuration. I want to ask whether it is possible to partition a hard disk into two identical zones, and then mount the file directory through the zone. Is this allowed? When I do, it always reminds me 'waiting for the first server to format the disks.' @harshavardhana 

No it is not possible
