### ISSUE TITLE
Allow disabling of Direct IO

### ISSUE THREAD

**Issue by stevefan1999-personal** [minio/minio#10797]
Hi, I was using rclone mount + minio + google drive to get unlimited object storage, but since rclone mount is a FUSE application, and O_DIRECT is of course never going to be supported, and minio seemingly started enforcing O_DIRECT since `RELEASE.2020-05-08T02-40-49Z`? (My binary search leads me to this final version before I started to get error message), this means I'd have to be several versions behind.
For anyone curious, this is the mysterious error I've been seeing.
```
 You are running an older version of MinIO released 5 months ago 
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes 
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Use 'sudo chown <your-username> /export && sudo chmod u+rxw /export' to provide sufficient permissions.
stream closed
```

**Comment by harshavardhana** [comment]
Single drive mode doesn't use O_DIRECT its only meant for erasure coding.

**Comment by stevefan1999-personal** [comment]
@harshavardhana I traced the error and they only appear on these places
https://github.com/minio/minio/search?q=ErrUnableToWriteInBackend

that's why I started to be suspicious about O_DIRECT

**Comment by harshavardhana** [comment]
> that's why I started to be suspicious about O_DIRECT

It is not it simply a permissions issue we are not able to write to the mount a temporary file as the user.

**Comment by stevefan1999-personal** [comment]
@harshavardhana hmm any possible chance to skip doing that as well? Although I could force rclone to 777 everything (and immutable too since FUSE doesn't really enforce ACL implementation which rclone rightfully skipped so)

**Comment by harshavardhana** [comment]
> @harshavardhana hmm any possible chance to skip doing that as well? Although I could force rclone to 777 everything (and immutable too since FUSE doesn't really enforce ACL implementation which rclone rightfully skipped so)

No sir we cannot skip writing to backend FS to test out permissions.

**Comment by harshavardhana** [comment]
> No sir we cannot skip writing to backend FS to test out permissions.

Closing this as a non-issue
