### ISSUE TITLE
Memory consumtion problem 

### ISSUE THREAD

**Issue by titansmc** [minio/minio#10796]
I ran out of memory in one of the 2 nodes cluster (96 disks each). 

## Expected Behavior
Minio control the memory usage

## Current Behavior
systemd kills the process:
```
[Service]
WorkingDirectory=/usr/local
MemoryHigh=24G
MemoryMax=28G
```

## Context
when users query the servers a lot. Attached is the profile data

## Regression
probably yes

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-10-28T08-16-50Z
* Server setup and configuration: CentOS 7
* Operating System and version (`uname -a`):Linux ops-object01.embl.de 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[profile.zip](https://github.com/minio/minio/files/5466261/profile.zip)

**Comment by harshavardhana** [comment]
you shouldn't limit MinIO in this manner @titansmc we need as much as memory as the requests come in by default we set the total requests allowed to the memory limit presented by the system. 

We need at least 300MiB per request at times if the object is large this would mean that we can only support up to 100 requests per second on any given server with 24GiB of RAM. So if you arbitrarily limit the server in this manner you should also limit the number of requests per server. 

https://github.com/minio/minio/tree/master/docs/throttle

We do not honor the systemd memory limits so setting this may have adverse consequences, so please make sure to reduce the allowed number of requests as well to ensure that server doesn't use more memory.
