### ISSUE TITLE
supports internationalization (i18n)

### ISSUE THREAD

**Issue by blinkfox** [minio/minio#10808]
**Is your feature request related to a problem? Please describe.**
MinIO has many users in China, so add international support will be more friendly to Chinese developers or users, and it will also be of great help to the promotion of MinIO.

**Describe the solution you'd like**
Hope that MinIO web browser supports internationalization (i18n). Such as: `Simplified Chinese`.

**Describe alternatives you've considered**
Not yet

**Additional context**
Not yet

**Comment by harshavardhana** [comment]
i18n is a significant effort, unfortunately we don't have the luxury of time.

We may do this in future but there are no set timelines.

**Comment by blairdrummond** [comment]
Hi @blinkfox ; my colleague @wg102 has this functionality available in an open PR. Feel free to give it a try if it suits your needs

[PR](https://github.com/minio/minio/pull/12063)
