### ISSUE TITLE
Why is it that when I delete all the files in a directory, the directory is automatically deleted? 

### ISSUE THREAD

**Issue by 4714407** [minio/minio#10801]
Why is it that when I delete all the files in a directory, the directory is automatically deleted? But it allows you to create an empty directory

**Comment by harshavardhana** [comment]
Only in FS mode, this behavior is valid. Erasure coding preserves mkdir operations.

Use erasure coding if you want directories to be preserved.

**Comment by 4714407** [comment]
I used the erase code mode, but the directory was deleted automatically

**Comment by 4714407** [comment]
In the first step, I created a directory, for example, "Tom /"

In the second step, I put a file in the directory, for example: "Tom / 1. XML"

In the third step, I delete "1. XML" from the directory "Tom", but the directory "Tom" is also deleted

Is there any way to keep the directory "Tom" empty like the first step, instead of being deleted together

**Comment by harshavardhana** [comment]
> In the first step, I created a directory, for example, "Tom /"
> 
> In the second step, I put a file in the directory, for example: "Tom / 1. XML"
> 
> In the third step, I delete "1. XML" from the directory "Tom", but the directory "Tom" is also deleted
> 
> Is there any way to keep the directory "Tom" empty like the first step, instead of being deleted together

Use the latest versions

**Comment by 4714407** [comment]
After using the version 2020-10-28t08:16:50z, the problem is solved
