### ISSUE TITLE
rpc: Merge minio browser port 9001 with 9000

### ISSUE THREAD

**Issue by pirogoeth** [minio/minio#1081]
I have a slightly strange set up -- picture it as two machines, both with separate external addresses as well as an internal/private network. Server A runs production services, including main web, where the minio file browser is being hosted. Server B runs a series of Docker images where I am running minio API+RPC. 

On Server A, I've configured nginx to serve the browser on `cdn.prod.example.org` and RPC on `cdn.prod.example.org/rpc`. Note that server B is configured to _only_ publish the minio API and RPC ports internally (`10.100.0.7:8750 -> 9000 (API)`, `10.100.0.7:8751:9001 (RPC)`).

Everything works until you get to uploading files - then things fail:

![Error from web UI](http://i.imgur.com/tspw2Yx.png)

Is there a way to override the determined upload URI that gets served up over RPC? Maybe set it statically or something?

**Comment by harshavardhana** [comment]
Thanks we will take a look.
