### ISSUE TITLE
How to get list of files and folder within folder level using Minio API

### ISSUE THREAD

**Issue by shomshekarLA** [minio/minio#10817]
We need to list the files and the folder which comes under the root directory, currently Minio API "list_objects" is listing out all the files from different levels not the folder within a bucket

## Expected Behavior

The files as well as the folders should come only for root level, not all

## Current Behavior

The files as well as the folders should come only for root level, not all

## Possible Solution

The files as well as the folders should come only for folder level, not all.
Also is there any API currently available to achieve the requirement.

## Steps to Reproduce (for bugs)

1. Root
      File1
      File2
      Folder1
         File3
         File4
         Folder2
           File5
2.  Under Root level the output should display File1, File2, Folder1
3. Under Folder1 it should display File3, File4 and Folder2
4. What we need is how to get the folder listed as an object along with other files under the parent directory. (As example given above) 

## Context

For large and complex folder structures, it will take longer time even to display the content on Frontend, even for a single file.

## Your Environment

* Version used (`minio --version`): Version: go1.14.9 | CPUs: 4
* Server setup and configuration: 
* Operating System and version (`uname -a`): 
------------------
URL : https://play.min.io/minio
access_key='Q3AM3UQ867SPQQA43P2F',
secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',

**Comment by kannappanr** [comment]
This is already supported in s3

```
$ AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws --endpoint-url http://play.min.io s3api list-objects-v2 --bucket root --delimiter '/'
{
    "Contents": [
        {
            "Key": "file1",
            "LastModified": "2020-11-03T23:27:17.608Z",
            "ETag": "\"b954418e6a50d4d4cb8f02776d867550\"",
            "Size": 26,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "",
                "ID": ""
            }
        },
        {
            "Key": "file2",
            "LastModified": "2020-11-03T23:27:21.558Z",
            "ETag": "\"b954418e6a50d4d4cb8f02776d867550\"",
            "Size": 26,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "",
                "ID": ""
            }
        }
    ],
    "CommonPrefixes": [
        {
            "Prefix": "folder1/"
        }
    ]
}
```
```
$ AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws --endpoint-url http://play.min.io s3api list-objects-v2 --bucket root --delimiter '/' --prefix folder1/
{
    "Contents": [
        {
            "Key": "folder1/file3",
            "LastModified": "2020-11-03T23:27:42.897Z",
            "ETag": "\"b954418e6a50d4d4cb8f02776d867550\"",
            "Size": 26,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "",
                "ID": ""
            }
        },
        {
            "Key": "folder1/file4",
            "LastModified": "2020-11-03T23:27:46.295Z",
            "ETag": "\"b954418e6a50d4d4cb8f02776d867550\"",
            "Size": 26,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "",
                "ID": ""
            }
        }
    ],
    "CommonPrefixes": [
        {
            "Prefix": "folder1/folder2/"
        }
    ]
}
```
```
 $ mc ls -r play/root
[2020-11-03 15:27:17 PST]    26B file1
[2020-11-03 15:27:21 PST]    26B file2
[2020-11-03 16:14:27 PST]     0B folder1/
[2020-11-03 15:27:42 PST]    26B folder1/file3
[2020-11-03 15:27:46 PST]    26B folder1/file4
[2020-11-03 16:14:27 PST]     0B folder1/folder2/
[2020-11-03 15:28:30 PST]    26B folder1/folder2/file5
```

Please look at the examples given above.  Closing this as answered. Feel free to reach out to us at slack https://slack.min.io for further such questions
