### ISSUE TITLE
Deleted objects don't free space 

### ISSUE THREAD

**Issue by JhonJohnatan** [minio/minio#10816]
Hey guys,
I have distributed minio, with 4 nodes.
Every node has a NFS storage around 9TB (Total 36TB)

In minio I see 9.4TB Used, but the disks are 87% full (31TB Used)

I've been waiting the 12 hours disk space update routine and it doesn't helped.

I tried to heal with mc admin, doesn't work.

## Expected Behavior
Minio will use 9.4TB*2 = 18.8TB. 52% will be used 

## Current Behavior
Minio uses 31TB. 88% used 

## Possible Solution
I have no idea

## Steps to Reproduce (for bugs)
df -h on server nodes

## Context
I run out of space, soon my production will fail

## Your Environment

Minio version: 2020-10-28T08:16.50Z
CentOS Linux 8 (Core)
Linux 4.18.0-80.e18.x86_64 GNU/Linux

**Comment by klauspost** [comment]
Disk space should be freed immediately unless you are using versioned buckets, then disk space will remain in use even after deletion, since deletion is non-destructive.

Does your buckets have versioning enabled?

When you delete an object is the data in the corresponding folders deleted, ie `mc rm myminio/bucket/prefix/object.txt` should remove the `diskN/bucket/prefix/object.txt` folder. Is it still left? Could you post the `xl.meta` left behind if so?

**Comment by JhonJohnatan** [comment]
> Disk space should be freed immediately unless you are using versioned buckets, then disk space will remain in use even after deletion, since deletion is non-destructive.
> 
> Does your buckets have versioning enabled?
> 
> When you delete an object is the data in the corresponding folders deleted, ie `mc rm myminio/bucket/prefix/object.txt` should remove the `diskN/bucket/prefix/object.txt` folder. Is it still left? Could you post the `xl.meta` left behind if so?

I checked and the buckets are un-versioned.
I did find an empty directory (UI+MC), but on the disk they do exist. there is a `xl.meta` file.
is there any xl.meta content you need? because I have technical issues that blocks me from sending the whole file

Another information, I did upgrade the minio to latest this week, that previous version was from june 2020.

@klauspost

**Comment by klauspost** [comment]
Could you upload a harmless file, delete it and post exactly which files are in the folders along with any `xl.json` that may be there. (just one should be fine)

**Comment by JhonJohnatan** [comment]
> Could you upload a harmless file, delete it and post exactly which files are in the folders along with any `xl.json` that may be there. (just one should be fine)

I have just uploaded a file to a new bucket. After uploading and deleting there are no files on disk.
@klauspost

**Comment by klauspost** [comment]
@JhonJohnatan Are you able to reproduce a specific case where the files are left over after deletion?

**Comment by JhonJohnatan** [comment]
I've tried many ways. I couldn't reproduce it. The problem I face with now is a full storage minio with no reason.

The `Used` indication points on 9.5TB used, but, I have 36TB.
How can it be? 

@klauspost 

--EDIT! PROBLEM SOLVED--
Turns the issue was that our IT folks saved backups of the NFS that we used for our MinIO servers on the NFS itself

Thank you for your help @klauspost :)

**Comment by klauspost** [comment]
@JhonJohnatan Very glad you found the solution! 🎉
