### ISSUE TITLE
[fixed] When deleting directories and files, there are problems with the returned results

### ISSUE THREAD

**Issue by 4714407** [minio/minio#10832]
request
```
---------START-HTTP---------
POST /test?delete= HTTP/1.1
Host: 127.0.0.1:9000
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/1.4.11.1
Content-MD5: fmijloSGyo0x5JKAvphAWg==
x-amz-content-sha256: 4aeb982d70acc1ba2aa745be448eb9ec45e9950c17827d186c5fc8215d94a2eb
x-amz-date: 20201105T090941Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201105/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

<Delete xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Quiet>false</Quiet><Object><Key>dir1/</Key></Object><Object><Key>dir2/</Key></Object><Object><Key>dir2/7.jpg</Key></Object></Delete>
HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 210
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-10-28T08-16-50Z
Vary: Origin
X-Amz-Request-Id: 1644918831D824F8
X-Xss-Protection: 1; mode=block
Date: Thu, 05 Nov 2020 09:09:41 GMT

----------END-HTTP----------
```
response:
```
<?xml version="1.0" encoding="UTF-8"?>
<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Deleted><Key>dir2/</Key></Deleted><Deleted></Deleted><Deleted><Key>dir2/7.jpg</Key></Deleted></DeleteResult>
```
The delete operation was successful. Both directories and one file were deleted successfully, but
In the returned XML, here is a Deleted node with no content!

**Comment by harshavardhana** [comment]
> In the returned XML, here is a Deleted node with no content!

Where you can see there is the correct XML content? where do you not see it?

**Comment by 4714407** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Deleted><Key>dir2/</Key></Deleted>
<Deleted></Deleted>
<Deleted><Key>dir2/7.jpg</Key></Deleted>
</DeleteResult>
```
Can you see it?

**Comment by harshavardhana** [comment]
> <?xml version="1.0" encoding="UTF-8"?>
> <DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> <Deleted><Key>dir2/</Key></Deleted>
> <Deleted></Deleted>
> <Deleted><Key>dir2/7.jpg</Key></Deleted>
> </DeleteResult>

Yes that is because you sent three elements and we return back 3 elements. since dir2/ is the same
prefix for the next object is filtered out. 

Do you have a problem with it? @4714407

**Comment by 4714407** [comment]
The correct return result should be:
```
<?xml version="1.0" encoding="UTF-8"?>
<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Deleted><Key>dir2/</Key></Deleted>
<Deleted><Key>dir1/</Key></Deleted>
<Deleted><Key>dir2/7.jpg</Key></Deleted>
</DeleteResult>
```
Why should dir1/ be omitted?

**Comment by 4714407** [comment]
At this time, the client is abnormal when parsing the returned result


org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=Key, type=void, data=false, required=true) on field'name' private java.lang.String io .minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2

**Comment by harshavardhana** [comment]
> At this time, the client is abnormal when parsing the returned result
> 
> org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=Key, type=void, data=false, required=true) on field'name' private java.lang.String io .minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2

This doesn't make sense, which version of minio-java is this ?

**Comment by 4714407** [comment]
Don’t you think the returned XML is incorrect? A empty Deleted value was returned.
I am using io.minio:minio:7.1.4
Server version:2020-10-28T08:16:50Z

**Comment by harshavardhana** [comment]
> Don’t you think the returned XML is incorrect? A empty Deleted value was returned.

@4714407 checking

**Comment by harshavardhana** [comment]
Looks like a bug @4714407 fixing it.
