### ISSUE TITLE
aboult language

### ISSUE THREAD

**Issue by Tompythonorange** [minio/minio#10830]
how can I choose ui language different?  maybe it can not be changed? thank you

**Comment by harshavardhana** [comment]
There is only one language we support i.e English

**Comment by Tompythonorange** [comment]
support  the other language Chinese please. I love you my whole life, thank you.













At 2020-11-05 11:55:20, "Harshavardhana" <notifications@github.com> wrote:

There is only one language we support i.e English

**Comment by Tompythonorange** [comment]
support Chinese please, I love you, waiting for you to support Chinese all my life, thank you.
















At 2020-11-05 11:55:20, "Harshavardhana" <notifications@github.com> wrote:

There is only one language we support i.e English
