### ISSUE TITLE
Minio S3 Gateway with SSE enabled doesn't support ListObjectsV1 with marker

### ISSUE THREAD

**Issue by StevenReitsma** [minio/minio#10838]
## Expected Behavior
When listing objects, I expect pagination to work properly in the Minio S3 Gateway with SSE enabled.

## Current Behavior
When I use the ListObjectsV1 API, I properly get a NextMarker back. If I use this as the Marker in a new request, it doesn't get used and I get back the same 1000 keys and the same NextMarker as in the previous request. Looking through the code, the `marker` parameter doesn't seem to be used in this function: 

https://github.com/minio/minio/blob/71753e21e0d78a986b21a773bdf3fbaf7333879c/cmd/gateway/s3/gateway-s3-sse.go#L67-L69

Shouldn't the `marker` parameter be used when calling ListObjectsV2 instead of an empty `continuationToken`?

## Possible Solution
Maybe the `marker` function param should be used in the call to ListObjectsV2?

## Steps to Reproduce (for bugs)
Run Minio S3 Gateway with SSE.
Use following piece of Python code:

```python
import boto3
from botocore.client import Config

client = boto3.client("s3", endpoint_url="https://minio.url, config=Config(signature_version="s3v4"), region_name="abc")
objects = client.list_objects(
    Bucket='my-bucket',
    Delimiter='',
    EncodingType='url',
    MaxKeys=1000,
    Prefix='folder_with_thousands_of_files/'
) # this properly contains the first 1000 objects and a NextMarker

objects2 = client.list_objects(
    Bucket='my-bucket',
    Delimiter='',
    EncodingType='url',
    MaxKeys=1000,
    Prefix='folder_with_thousands_of_files/',
    Marker='the NextMarker from the previous call'
) # this incorrectly returns the same 1000 objects as the previous call and the same NextMarker as given in the Marker argument
```

## Context
Minio S3 Gateway with SSE (single encryption). The S3 backend is a Ceph Object Gateway (RadosGW).

## Your Environment

* Version used (`minio --version`): `minio/minio:RELEASE.2020-10-28T08-16-50Z` Docker image
* Server setup and configuration: Using KMS Vault (transit API), AUTO_ENCRYPTION on
* Operating System and version (`uname -a`): `Linux hostname 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@StevenReitsma feel free to send a PR happy to accept

**Comment by StevenReitsma** [comment]
Will do, I already found a fix locally. I'll run the tests and submit a PR soon
