### ISSUE TITLE
object policy doesnt work

### ISSUE THREAD

**Issue by FrankJulius** [minio/minio#10831]
## Expected Behavior
It should only let me see the "TestUser" folder in the bucket

## Current Behavior
I cant see any file

## Steps to Reproduce (for bugs)

1. I have followed these steps: https://docs.min.io/docs/minio-multi-user-quickstart-guide.html
2.This is my json policy file:
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::aoidata"],
      "Condition": {"StringLike": {"s3:prefix": ["TestUser/*"]}}
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::aoidata/TestUser/*"]
    }
  ]
}`
3.When i deploy:
mc admin policy add minIO policyTestUser policyTestUser.json
Added policy `policyTestUser` successfully.mc admin policy set minIO policyTestUser user=TestUser
Policy policyTestUser is set on user `TestUser`
4.Its says this, when im logged in as "TestUser":Can you help me fix that?
![image](https://user-images.githubusercontent.com/73987753/98218155-baaf7000-1f4b-11eb-9873-3c520054b927.png)

## Context
 i want that a user has his own foler in a bucket and only can see and write in it

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-10-28T08-16-50Z
* Operating System and version (`uname -a`): Windows 10 64 bit Version 10.0.18363.1082]

**Comment by harshavardhana** [comment]
> 1. {   "Version": "2012-10-17",   "Statement": [ { "Action": ["s3:ListBucket"], "Effect": "Allow", "Resource": ["arn:aws:s3:::aoidata"], "Condition": {"StringLike": {"s3:prefix": ["TestUser/*"]}} }, { "Action": [ "s3:GetObject", "s3:PutObject" ], "Effect": "Allow", "Resource": ["arn:aws:s3:::aoidata/TestUser/*"] }   ] }

The policy is incorrect

**Comment by FrankJulius** [comment]
thank you, it works.
do you know how i can see only my folder?

**Comment by harshavardhana** [comment]
> do you know how i can see only my folder?

That's not allowed unfortunately @FrankJulius - you need to build custom UI for that.
