### ISSUE TITLE
Minio: Custom azure endpoint is not working

### ISSUE THREAD

**Issue by vennilashanthi** [minio/minio#10843]
When starting minio with a custom azure Endpoint as per documentation,
minio gateway azure https://azureaccountname.blob.custom.azure.endpoint is not seems to be working.

## Expected Behavior
Accept the custom endpoints of Azurestack ( blob storage ) and work as like public cloud endpoint ( https://core.windows.net ) 

## Current Behavior
Existing buckets is not listing.
Getting an following error upon creating the new bucket.
![image](https://user-images.githubusercontent.com/74044261/98355313-f9c2eb80-2047-11eb-8aa9-947c6bcd14e7.png)

## Steps to Reproduce (for bugs)
Setup azure with a custom domain, not the public one ( core.windows.net )
check this with Azurestack

## Context
Not able to run minio gateway against azurestack !

## Your Environment
Minio version :

```./minio --version
minio version RELEASE.2020-10-28T08-16-50Z```

Operating System:

```## uname -a
Linux minio-xaas 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
## cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)```

**Comment by harshavardhana** [comment]
azurestack is not a fully complete azure replacement, it never worked for us. You should ask azurestack devs to fix their bugs ottherwise unfortunately we can't do much here.
