### ISSUE TITLE
How to restrict public access to minIO objects

### ISSUE THREAD

**Issue by nerdial** [minio/minio#10854]
**Sorry for opening an issue here, i tried slack group but there was no answer.**

I have got a question about minio. I am using a stand-alone minio server for my project. Here is the situation :

- There is only one admin account that receives files and uploads them to minio server.

- My Users need to access just their own uploaded objects. I mean another user is not supposed to see other people's object publicly (e.g. by visiting direct link in URL).

- Admin users are allowed to see all objects in any circumstances.

**1. How can i implement such policies for my project considering i have got my database for user authentication and how can i combine them to authenticate the user.**

**2. If not what other options do i have here to ease the process ?**

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html here is how you can do it.
