### ISSUE TITLE
Does ExpirationDate not allow setting local dates?

### ISSUE THREAD

**Issue by 4714407** [minio/minio#10852]
Do you only support midnight dates, but not local dates?

**Comment by harshavardhana** [comment]
ExpirationDate is GMT @4714407 as per AWS S3 spec.

**Comment by harshavardhana** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html

> The date value must conform to the ISO 8601 format. The time is always midnight UTC.
