### ISSUE TITLE
./mc ls *** result is invalid character entity

### ISSUE THREAD

**Issue by Cpanmac** [minio/minio#10856]
Error ：`mc: <ERROR> Unable to list folder. XML syntax error on line 37: invalid character entity &nbsp; ` When I execute  ./mc ls minio！
* Version used (`minio --version`): minio version RELEASE.2020-07-18T18-48-16Z
* Operating System and version (`uname -a`):Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Could you supply a complete commandline used? `mc ls ***` makes no sense.

**Comment by kannappanr** [comment]
Can you please open the issue in `mc`? I don't think this has anything to do with minio. Closing this issue here.
