### ISSUE TITLE
Retention policy not working

### ISSUE THREAD

**Issue by nekrondev** [minio/minio#10860]
## Expected Behavior
- Buckets with governance retention policy should disallow modifications before expiration date

## Current Behavior
```shell
root@dev:~/minio$ mc mb minio/data --with-lock
Bucket created successfully `minio/data`.
root@dev:~/minio$ mc retention set --default compliance 30d minio/data/
COMPLIANCE mode is enabled for 30DAYS
root@dev:~/minio$ mc cp mc minio/data/
mc:                                        20.21 MiB / 20.21 MiB ┃ 10.78 MiB/s 1s
root@dev:~/minio$ mc retention info minio/data/mc
Name    : minio/data/mc
Mode    : COMPLIANCE, expiring in 29 days

root@dev:~/minio$ mc rm minio/data/mc
Removing `minio/data/mc`.
root@dev:~/minio$ mc ls minio/data/
```

## Possible Solution
- none

## Steps to Reproduce (for bugs)
- using docker-compose file (https://docs.min.io/docs/deploy-minio-on-docker-compose.html)
- execute the same steps as seen above

## Your Environment
* Version used: Docker image minio/minio:RELEASE.2020-11-06T23-17-07Z
* Server setup and configuration: single dev node
* Operating System and version (`uname -a`): Ubunut 20.04.01 LTS

**Comment by harshavardhana** [comment]
`mc rm` creates a new version - `mc ls --versions` to see a delete-marker created.
