### ISSUE TITLE
[working as intended] Minio AMQP Noifications cannot tell if a file is created or overwritten

### ISSUE THREAD

**Issue by AbdullahAlhulwah** [minio/minio#10865]
Currently I am using AMQP Notifications to send a notification to another component when a new object is added to a bucket. The problem is that there might be some duplicate files being added to the same bucket, but the notification will be exactly the same as if it's a new file. That will cause the component that receives the notification to consume twice.  

How can we handle these duplicate notifications?

**Comment by kannappanr** [comment]
@AbdullahAlhulwah S3 notifications are just that. It will tell you what API was used. With the overwrite of the object, everything can change except the object name. Notifications from MinIO are supposed to be generated for the subscribed API.
