### ISSUE TITLE
[faq] Retention has no effect

### ISSUE THREAD

**Issue by AbdullahAlhulwah** [minio/minio#10870]
I tried enabling retention for 7 days on an object to prevent overwriting/deleting on that object. 

mc retention set governance 7d myminio/testbucket/testobject
Object` retention successfully set for 'myminio/testbucket/testobject'.

And when I try to remove it: 
mc rm myminio/testbucket/testobject
Removing 'myminio/testbucket/testobject.

The object is successfully removed which should not happen if retention is enabled.

Environment: 
I am using minio on AWS with ubuntu 16.04. Minio is setup on distributed mode of 3 nodes.
minio version: RELEASE.2020-09-10T22-02-45Z

**Comment by harshavardhana** [comment]
Retention enables versioning `mc rm` creates a delete marker - observe your original object with `mc ls --versions`
