### ISSUE TITLE
[duplicate] internal error after disk failure

### ISSUE THREAD

**Issue by armsby** [minio/minio#10877]
we had a disk failing in one of your 4 nodes, disk has been replaced and we are back to have all 64 disks up, but when we are trying to list the content of some folders we are getting a 500 internal error, and the same if we are trying to delete it

## Expected Behavior
folder to list after disk replacement

## Current Behavior
cluster returns an internal error 
mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.
 (1) ls.go:216 cmd.doList(..) Tags: [http://server.local:9000/folder/subfolder]
 (0) client-s3.go:2158 cmd.(*S3Client).listInRoutine(..)

## Steps to Reproduce (for bugs)
I would love to reproduce it but I have no idea why it is giving this error

## Context
im not able to delete the folder or over write it with new content

## Your Environment
minio version: 2020-11-10T21:02:24Z
setup 4 nodes with 16 disks in each
OS ubuntu 20.04.1

**Comment by harshavardhana** [comment]
@armsby please provide us the necessary logs

**Comment by armsby** [comment]
what logs do you need?

**Comment by harshavardhana** [comment]
> what logs do you need?

server logs what else? 

> mc: Unable to list folder. We encountered an internal error, please try again.

when you see this there will be logs on the server console.

**Comment by armsby** [comment]
this is what I see on the server
[minio_error.zip](https://github.com/minio/minio/files/5526208/minio_error.zip)

I hope this is what you are after

**Comment by harshavardhana** [comment]
> this is what I see on the server
> [minio_error.zip](https://github.com/minio/minio/files/5526208/minio_error.zip)
> 
> I hope this is what you are after

This error is same issue as reported here #10868  - closing this as duplicate
