### ISSUE TITLE
Update loop

### ISSUE THREAD

**Issue by i0x71** [minio/minio#10889]
Not sure if this is a bug, but mc admin update xxx is not able to tell that its running the latest version, as opposed to mc update

root@sandbox:~ mc admin update dot9
Server `dot9` updated successfully from 2020-11-10T21:02:24Z to 2020-11-10T21-02-24Z
root@sandbox:~ mc admin update dot9
Server `dot9` updated successfully from 2020-11-10T21:02:24Z to 2020-11-10T21-02-24Z
root@sandbox:~ mc admin update dot9
Server `dot9` updated successfully from 2020-11-10T21:02:24Z to 2020-11-10T21-02-24Z
root@sandbox:~ mc update
You are already running the most recent version of ‘mc’.

No matter how many times you run mc admin update xxx, every time it will run for about a minute and then reply that it has updated (to the same version)

**Comment by harshavardhana** [comment]
> root@sandbox:~ mc admin update dot9
> Server `dot9` updated successfully from 2020-11-10T21:02:24Z to 2020-11-10T21-02-24Z
> root@sandbox:~ mc admin update dot9
> Server `dot9` updated successfully from 2020-11-10T21:02:24Z to 2020-11-10T21-02-24Z
> root@sandbox:~ mc admin update dot9
> Server `dot9` updated successfully from 2020-11-10T21:02:24Z to 2020-11-10T21-02-24Z

We haven't changed anything specific which would allow this, let me check what is happening on the server.

**Comment by harshavardhana** [comment]
Looks like this issue has been there since ages, not sure how we are seeing this now.

**Comment by i0x71** [comment]
Thanks for looking into this!
