### ISSUE TITLE
Slow multipart upload performance when using small chunk sizes in distributed mode

### ISSUE THREAD

**Issue by acejam** [minio/minio#10891]
## Expected Behavior
Fast (above 100+ MiB/s) and sustained multipart upload performance when using the default AWS CLI chunk size (8 MB)

## Current Behavior
Multipart upload performance spikes at the beginning of the upload and then quickly drops by 70-90% down to ~45 MiB/s.

## Possible Solution
The described scenario seems closely related to #7206, but I don't think the fix would be the same.

## Steps to Reproduce (for bugs)
Note: Many of the steps below use the AWS CLI
1. Setup a new distributed MinIO cluster with 3 nodes using HDD's. `minio server http://host{1...3}/export{1...2}`
2. Create a storage bucket: `aws --endpoint-url http://host1:9000 s3 mb s3://test-bucket`
3. Using the AWS CLI with default configuration options, upload a 1GB file to the new bucket: `aws --endpoint-url http://host1:9000 s3 cp 1GB.raw s3://test-bucket/`
4. Observe upload performance with initial transfer rate/spike to ~60 MiB/s. Upload speed quickly drops to ~45 MiB/s. Let the upload finish.
5. Increase the AWS CLI chunk size to 64 MB: `aws configure set default.s3.multipart_chunksize 64MB`
6. Repeat step 3 again using the same command. Upload performance now spikes to 220 MiB/s. After a few seconds speed drops, but remains at 150-200 MiB/s sustained. (A good thing)

## Context
I'm trying to setup a distributed MinIO cluster for various clients. I cannot control the clients, or their configurations. Clients use several different S3 compatible tools, including the AWS CLI, CyberDuck, Veeam, CommVault, etc. The default configuration values for these tools are performant with other S3 compatible services, including AWS, Wasabi, DO Spaces, and BackBlaze B2. With MinIO, the sustained throughput is too low, unless the client chunk/part size is increased. 

## Regression
I don't believe so.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-11-10T21-02-24Z
* Server setup and configuration: (3) Nodes with (2) 6TB 7200rpm HDD's each. 36 TB total raw capacity
* Operating System and version (`uname -a`): Ubuntu 20.04 Server x64
Linux 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
All testing done via 2 Gbps private internal network

**Comment by harshavardhana** [comment]
> The described scenario seems closely related to #7206, but I don't think the fix would be the same.

It is not related @acejam

**Comment by harshavardhana** [comment]
> * Setup a new distributed MinIO cluster with 3 nodes using HDD's. `minio server http://host{1...3}/export{1...2}`

What is your default concurrency here? @acejam

**Comment by acejam** [comment]
> > * Setup a new distributed MinIO cluster with 3 nodes using HDD's. `minio server http://host{1...3}/export{1...2}`
> 
> What is your default concurrency here? @acejam

For the AWS CLI? The default, which appears to be 10.

**Comment by harshavardhana** [comment]
> For the AWS CLI? The default, which appears to be 10.

have you tried increasing it to 32?

**Comment by acejam** [comment]
> > For the AWS CLI? The default, which appears to be 10.
> 
> have you tried increasing it to 32?

I have, and it didn’t make much difference. Changing the chunk size does though. However the point of this issue is that I cannot change these settings on my client machines. Many of these consuming applications also use the AWS SDK’s internally.

**Comment by acejam** [comment]
@harshavardhana Any ideas on this?

**Comment by harshavardhana** [comment]
> @harshavardhana Any ideas on this?

Will get back in a week..

**Comment by harshavardhana** [comment]
This is to be expected @acejam smaller chunks have to serialize when they are uploaded concurrently they update metadata. The test is actually a bit useless since multipart uploads don't mean that each part actually is an independent entity they are contiguous parts of a single object. The actual performance/throughput should be measured with multiple uploads of multiple objects to choke the network i.e upload many such multipart operations for different objects rather than a single object. 

Once you do that you can see the server starts peaking in performance.  So AFAICS there is no issue here it is implemented as per the design.

There is nothing to fix on our end AFAICS at this moment.
