### ISSUE TITLE
Keycloak Access Token Lifespan problem

### ISSUE THREAD

**Issue by tomsozolins** [minio/minio#10905]
Hello!

I am configuring MinIO to use OpenID authentification with Keycloak and LDAP integration according to this guide:
https://github.com/minio/minio/blob/master/docs/sts/keycloak.md

I can successfully login in MinIO browser, but the problem is that i am logged out from Minio after some minutes and redirected to login page. I tried to change Keycloak Access Token Lifespan to 24 hours and it doesn't affect the MinIO logout problem.
How can i configure MinIO for longer client sessions, because this is a serious deal breaker if the session time cannot be increased...

**Comment by harshavardhana** [comment]
> I can successfully login in MinIO browser, but the problem is that i am logged out from Minio after some minutes and redirected to login page. I tried to change Keycloak Access Token Lifespan to 24 hours and it doesn't affect the MinIO logout problem.
> How can i configure MinIO for longer client sessions, because this is a serious deal breaker if the session time cannot be increased...

You cannot increase it beyond 24hourse @tomsozolins you are allowed to set it up to 12hrs maximum.

**Comment by tomsozolins** [comment]
> > I can successfully login in MinIO browser, but the problem is that i am logged out from Minio after some minutes and redirected to login page. I tried to change Keycloak Access Token Lifespan to 24 hours and it doesn't affect the MinIO logout problem.
> > How can i configure MinIO for longer client sessions, because this is a serious deal breaker if the session time cannot be increased...
> 
> You cannot increase it beyond 24hourse @tomsozolins you are allowed to set it up to 12hrs maximum.

I tried to set it to 4 hours too and it doesn't work. I still get logged out of MinIO after few minutes. The logout happens even if upload is ongoing...

**Comment by tomsozolins** [comment]
> > I can successfully login in MinIO browser, but the problem is that i am logged out from Minio after some minutes and redirected to login page. I tried to change Keycloak Access Token Lifespan to 24 hours and it doesn't affect the MinIO logout problem.
> > How can i configure MinIO for longer client sessions, because this is a serious deal breaker if the session time cannot be increased...
> 
> You cannot increase it beyond 24hourse @tomsozolins you are allowed to set it up to 12hrs maximum.

I found log file in keycloak, which seems to be the time when logout is happening:
`keycloak: #033[0m#033[33m09:08:09,764 WARN  [org.keycloak.events] (default task-34) type=REFRESH_TOKEN_ERROR, realmId=master, clientId=security-admin-console, userId=null, ipAddress=X.X.X.X, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret`

It is weird that it shows realm=master, because i have configured minio realm and specified it in minio config.

Is this a keycloak problem or MinIO problem or something else?

**Comment by tomsozolins** [comment]
Fixed the problem. I had to do a little more than what was documented in https://github.com/minio/minio/blob/master/docs/sts/keycloak.md. 

When i changed Access Token Lifespan in Minio Realm settings section, the logout problem vanished. 
Seems like Realm has higher priority than specific "account" setting, so no matter how much time period i put in "account", it was overriden by Realm setting.

Maybe the documentation needs to be updated to address this problem?

**Comment by harshavardhana** [comment]
> Maybe the documentation needs to be updated to address this problem?

This is part of keycloak deployment document, we do not mention it as we don't have any special recommendations here. Its upto your organization to configure your Identity provider.  We only talk about what sticks it with MinIO.
