### ISSUE TITLE
Lifecycle seems not work?

### ISSUE THREAD

**Issue by sesky4** [minio/minio#10903]
## Problem
I wrote serval TB data, each about 1MB into MinIO in last serval months.
1 week ago I added a lifecycle with expiration set to 30 days.
```json
>>> mc ilm export local/loki
{
 "Rules": [
  {
   "AbortIncompleteMultipartUpload": {},
   "Expiration": {
    "Date": "0001-01-01T00:00:00Z",
    "Days": 30,
    "DeleteMarker": false
   },
   "ID": "OldLog",
   "Filter": {
    "And": {},
    "Prefix": "fake/",
    "Tag": {}
   },
   "NoncurrentVersionExpiration": {
    "NoncurrentDays": 0
   },
   "NoncurrentVersionTransition": {},
   "Status": "Enabled",
   "Transition": {
    "Date": "0001-01-01T00:00:00Z"
   }
  }
 ]
}
```

## Expected Behavior
I expect MinIO will delete those old objects when it do garbage collection.But disk usage didn't go down(objects not deleted).

## Question
1.Will lifecycle delete objects that are added before the time lifecycle being created?
2.When will MinIO trigger lifecycle?

## Environment(docker-compose)
version_before_add_lifecycle: RELEASE.2020-07-02T00-15-09Z
version_now: RELEASE.2020-10-28T08-16-50Z
volumes:
      - /home/data0/minio_data:/data0
      - /home/data1/minio_data:/data1
      - /home/data2/minio_data:/data2
      - /home/data3/minio_data:/data3
environment:
      - MINIO_ACCESS_KEY=xxx
      - MINIO_SECRET_KEY=xxx
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_DISK_USAGE_CRAWL_ENABLE=off
command: server /data{0...3}

Disk are normal spin disks, not SSD.
I set MINIO_DISK_USAGE_CRAWL_ENABLE to 'off' because I found it using a lot of CPU all the time(about %400), and after I set it to 'off', the CPU goes down.

**Comment by harshavardhana** [comment]
> I set MINIO_DISK_USAGE_CRAWL_ENABLE to 'off' because I found it using a lot of CPU all the time(about %400), and after I set it to 'off', the CPU goes down.

If you disable crawling lifecycle will not run @sesky4

**Comment by sesky4** [comment]
Thanks :)

**Comment by sesky4** [comment]
Hi @harshavardhana , I enabled MINIO_DISK_USAGE_CRAWL_ENABLE.
And 24 hours goes away, the disk usage is still not changed.
Is there any way I can debug this? Through log, or somewhat? :)
