### ISSUE TITLE
Why does s3_ttfb_seconds_bucket of prometheus metrics not include api=putobject

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio#10904]
**Describe the solution you'd like**
The histogram metric `s3_ttfb_seconds_bucket` can see the time-consuming distribution of requests, but why are there only indicators such as `getobject` and `listbuckets`?

```
s3_ttfb_seconds_bucket{api="getobject",le="0.05"} 74469
s3_ttfb_seconds_bucket{api="getobject",le="0.1"} 75229
s3_ttfb_seconds_bucket{api="getobject",le="0.25"} 76721
s3_ttfb_seconds_bucket{api="getobject",le="0.5"} 78378
s3_ttfb_seconds_bucket{api="getobject",le="1"} 80142
s3_ttfb_seconds_bucket{api="getobject",le="2.5"} 81912
s3_ttfb_seconds_bucket{api="getobject",le="5"} 83241
s3_ttfb_seconds_bucket{api="getobject",le="10"} 84713
s3_ttfb_seconds_bucket{api="getobject",le="+Inf"} 86358
s3_ttfb_seconds_sum{api="getobject"} 85138.51100840722
```

Is there any way to see the time-consuming histogram of `putobject`

**Comment by harshavardhana** [comment]
PutObject is a client sent body, there is no body in the response and we also send Expect 100 continue right away, the value is always in line nanoseconds - rather meaningless with PutObject.
