### ISSUE TITLE
S3 Virtual Hosted-Style Requests not working

### ISSUE THREAD

**Issue by guerrap** [minio/minio#10910]
## Expected Behavior
I'm using the official aws-sdk-js client, and I'm trying to create a bucket and upload some files, pointing to a local minio container.
I expected to be able to create an S3 bucket and upload the files without configuring the aws client with the `s3ForcePathStyle` option set to `true`, that forces the path style URLs for S3 objects (support for the path-style model ended on September 30, 2020). AWS deprecation [plan](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/).

## Current Behavior
The creation of a bucket causes an error:
`Non-whitespace before first tag`

And also the file upload:
`The XML you provided was not well-formed or did not validate against our published schema`

If I configure the aws client this way, it all works properly:

```
endpoint: "http://127.0.0.1:9000",
s3ForcePathStyle: true
```

## Steps to Reproduce (for bugs)

1. install the aws-sdk-js client `npm install aws-sdk`
2. start minio container:
```
docker run -p 9000:9000 \
  -e "MINIO_ACCESS_KEY=access_key" \
  -e "MINIO_SECRET_KEY=secret_key" \
  minio/minio server /data
```
3. configure the aws client and try to create a bucket:
```
aws.config.update({
    accessKeyId: "access_key",
    secretAccessKey: "secret_key"
});

const s3 = new aws.S3({
    endpoint: "http://localhost:9000"
});

await awsS3
    .createBucket({
        Bucket: "bucket"
    })
.promise();
```
4. try to upload a file:
```
const response = await s3
    .upload({
        Bucket: "bucket",
        Key: "folder/my-file",
        Body: "file-content",
    })
.promise();
```

## Context
I'm using minio as an S3 mock for integration tests.
I don't know, maybe this is an aws-sdk client-related problem, but pointing to a real S3 storage on AWS, all work fine.

## Regression
No

## Your Environment

* aws-sdk version: `2.779.0`
* node version: `v14.8.0`,
* Version used: I'm using the latest minio docker image
* Server setup and configuration: default configuration
* Operating System and version (`uname -a`): `Linux guerrap-TM1701 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Virtual hosted style is supported when you enable MINIO_DOMAIN env

Please read the docs at docs.minio.io
