### ISSUE TITLE
[faq] How to rotate root/admin credentials? 

### ISSUE THREAD

**Issue by MikeLReminderM** [minio/minio#10911]
We wanted to turn off the minio web UI login page.  So we added the variable:

MINIO_BROWSER=off

to the /etc/default/minio file we use.   

We have four running servers.   The first one restarted with no issues.

The second one is giving the error in the subject of this report.

## Expected Behavior

A restart with the variable "MINIO_BROWSER=off" set is producing an unexpected error on the second server I have applied it to.

I would expect a restart not to produce this error.

## Current Behavior

We see the following on the affected server:

sudo systemctl status minio
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-11-17 11:46:57 EST; 3s ago
     Docs: https://docs.min.io
 Main PID: 4247 (minio)
    Tasks: 8 (limit: 4678)
   CGroup: /system.slice/minio.service
           └─4247 /usr/local/bin/minio server http://minio{01...04}/data{1...4}

Nov 17 11:46:59 minio04 minio[4247]: API: SYSTEM()
Nov 17 11:46:59 minio04 minio[4247]: Time: 11:46:59 EST 11/17/2020
Nov 17 11:46:59 minio04 minio[4247]: DeploymentID: d0156181-3dd6-401c-a086-cf8d9c6bbc81
Nov 17 11:46:59 minio04 minio[4247]: Error: Unable to migrate IAM users and policies to new format: sio: data is not authentic
Nov 17 11:46:59 minio04 minio[4247]:        1: cmd/iam.go:486:cmd.(*IAMSys).Init()
Nov 17 11:46:59 minio04 minio[4247]: API: SYSTEM()
Nov 17 11:46:59 minio04 minio[4247]: Time: 11:46:59 EST 11/17/2020
Nov 17 11:46:59 minio04 minio[4247]: DeploymentID: d0156181-3dd6-401c-a086-cf8d9c6bbc81
Nov 17 11:46:59 minio04 minio[4247]: Error: IAM sub-system is partially initialized, some users may not be available
Nov 17 11:46:59 minio04 minio[4247]:        1: cmd/iam.go:487:cmd.(*IAMSys).Init()

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

1.  Apply the variable MINIO_BROWSER=off
2. restart minio service
3.
4.

## Context

Not sure what the effect is.   I would like the web UI login page to be off, which it seems to be after a restart.

But I would also like to see clean restarts without these errors.

## Regression

No.

## Your Environment

* Version used (`minio --version`):

minio --version
minio version RELEASE.2020-10-18T21-54-12Z

* Server setup and configuration:
* Operating System and version (`uname -a`):

uname -a
Linux minio02 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is because you have changed your credentials without rotating them

**Comment by MikeLReminderM** [comment]
Does that mean after all 4 servers have been restarted, the errors should not occur?

**Comment by harshavardhana** [comment]
> Does that mean after all 4 servers have been restarted, the errors should not occur?

I don't know what you did - but when you change credentials you have to make sure to rotate them https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

**Comment by MikeLReminderM** [comment]
How is it that you do "not know what I did"?   I stated exactly what the change was in the issue.

I didn't add or change any users or the access or secret key values.   I applied an environmental variable to disable the web UI only.   As I clearly stated above.   How is that "changing credentials"?

You've linked me to something that doesn't address the "MINIO_BROWSER" variable - I set it to "off", that was my one and only change.

Can you kindly read my issue more carefully, or perhaps for the first time?
