### ISSUE TITLE
[working as intended] MinIO Gateway for NAS provide putObject asynchronous cache

### ISSUE THREAD

**Issue by dingjs** [minio/minio#10918]
**Is your feature request related to a problem? Please describe.**
NAS is much slower than local disk,especially small files. 

**Describe the solution you'd like**
Now MinIO provide getObject cache for Nas.Is it possible to provide cache for putObject.When clients putObject ot MinIO,MinIO cache it in the local disk,and sync to the NAS asynchronously.It would be more suitable for cold,warn,hot data.

**Comment by kannappanr** [comment]
@dingjs Will check internally and let you know if we plan to add this support in the future.

**Comment by harshavardhana** [comment]
> @dingjs Will check internally and let you know if we plan to add this support in the future.

PutObjects are already cached @dingjs what we have also added is an async completion response you should enable 

Default is `writethrough` 
```
export MINIO_CACHE_COMMIT=writeback
```
