### ISSUE TITLE
[faq] How to generate a s3 URL?

### ISSUE THREAD

**Issue by stevekm** [minio/minio#10913]
The instructions here describe how to create a http url to an object;

https://github.com/minio/minio/issues/5180

> You need to remove minio, so the URL should be
>
> `http://10.39.0.45:9000/test/types-of-mounts.png`

However, when I attempt to use a url like `s3://10.39.0.45:9000/test/types-of-mounts.png`, my S3 client gives errors such as  `The specified bucket is not valid`

How should you format a `s3://` URL for a MinIO object?

**Comment by harshavardhana** [comment]
Please ask questions on https://slack.min.io for FAQ's - `s3://` is not a URL standard you need a client which interprets `s3://` to `http://` 

This is not a MinIO issue.
