### ISSUE TITLE
After minio node reboot, object listing returns Error 504.

### ISSUE THREAD

**Issue by tomsozolins** [minio/minio#10919]
Hello!

I have a problem when testing failure scenario on 3 nodes MinIO cluster.
If i reboot any of the 3 nodes then in MinIO Browser some of the buckets, but not all are loading indefinetily and then returns Error 504.

`minio version RELEASE.2020-11-13T20-10-18Z`

Here is MinIO log events when i click on bucket:
`Nov 18 15:20:47 node3 minio[1448]: Error: Post "http://node1:9000/minio/peer/v10/updatemetacache?": net/http: timeout awaiting response headers (*rest.NetworkError)
Nov 18 15:20:47 node3 minio[1448]: 3: cmd/peer-rest-client.go:673:cmd.(*peerRESTClient).UpdateMetacacheListing()
Nov 18 15:20:47 node3 minio[1448]: 2: cmd/metacache-set.go:257:cmd.(*listPathOptions).updateMetacacheListing()
Nov 18 15:20:47 node3 minio[1448]: 1: cmd/metacache-set.go:650:cmd.(*erasureObjects).listPath.func4.1()
Nov 18 15:20:47 node3 minio[1448]: API: SYSTEM()
Nov 18 15:20:47 node3 minio[1448]: Time: 15:20:47 EET 11/18/2020
Nov 18 15:20:47 node3 minio[1448]: DeploymentID: 4d257282-5ef3-4273-9bdc-bb0a5966d519
Nov 18 15:20:47 node3 minio[1448]: Error: Post "http://node1:9000/minio/peer/v10/updatemetacache?": net/http: timeout awaiting response headers (*rest.NetworkError)
Nov 18 15:20:47 node3 minio[1448]: 1: cmd/metacache-set.go:656:cmd.(*erasureObjects).listPath.func4.1()
Nov 18 15:20:47 node3 minio[1448]: Client http://node1:9000/minio/peer/v10 online
` 
If i restart all minio node services then the problem goes away, but the sessions are closed and client is logged out.

Objects are listing normally when the MinIO service is down. But when i start the MinIO service then object listing problem starts happening. 
Initially i thaught the problem may be because of haproxy, but then i tried to login directly to Minio node Browser and the same problem is happening.

**Comment by klauspost** [comment]
Added #10922 

Note there will be instability and failed calls when a server is killed. This should take the worst delays out, though.

**Comment by tomsozolins** [comment]
> Added #10922
> 
> Note there will be instability and failed calls when a server is killed. This should take the worst delays out, though.

Thank you very much. Will wait for this fix before creating production cluster.
