### ISSUE TITLE
Calling metrics on gateway triggers unauthenticated calls to remote s3 

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#10921]
I have a minio gateway and minio nas server. Since adding metrics via prometheus the number of 403's triggered on the nas instance has started to climb in synch with prometheus probes to the gateway.

## Expected Behavior

The metrics endpoint should be lightweight and not trigger side effects probably.
Calls from the gateway to the remote S3 should be authenticated.

## Current Behavior

mc admin trace on the storage mc instance shows this:

```
14:02:49.716 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.159      15.446ms     ↑ 31 B ↓ 483 B
14:02:49.892 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.159      992µs       ↑ 31 B ↓ 483 B
14:02:54.032 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.158      2ms          ↑ 31 B ↓ 483 B
14:02:54.209 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.158      994µs       ↑ 31 B ↓ 483 B
14:03:00.076 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.168      9.474ms      ↑ 31 B ↓ 483 B
14:03:00.255 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.168      3.003ms      ↑ 31 B ↓ 483 B
14:03:04.716 [403 Forbidden] s3.ListBuckets der2219.mgsops.net:9000/ 10.75.11.159      13.512ms     ↑ 31 B ↓ 483 B
```

## Steps to Reproduce (for bugs)

1. Save this `docker-compose.yml` file in a folder. It will create a subfolder ".mc" to store minio client credentials.

```yaml
version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
  gateway:
    command: gateway s3 http://minio:9000
    image: minio/minio:latest
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
  mc:
    image: minio/mc
    volumes:
    - ./.mc:/root/.mc
  curl:
    image: curlimages/curl
```

2. execute the following commands from a bash or compatible terminal in the folder 

```bash
docker-compose up -d minio gateway
```

3. Run mc admin trace in one terminal to view the minio log:

```bash
docker-compose run mc alias set minio http://minio:9000 access_key secret_key
docker-compose run mc admin trace minio/
```

4. In another terminal, call the metrics endpoint on the gateway

```bash
docker-compose run curl http://gateway:9000/minio/prometheus/metrics
```

## Context

Its making the metrics noisy and difficult to track actual errors

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2020-11-13T20-10-18Z`

**Comment by harshavardhana** [comment]
This is on purpose to look if backend is offline. It makes a simple HTTP call like curl to see if network is reachable.

**Comment by chrisbecke** [comment]
That is a proper reason to make the call I guess.
But the current implementation has the knock on effect of making metrics on the upstream server act like this:

![Screenshot 2020-11-18 at 19 55 40](https://user-images.githubusercontent.com/6085581/99568475-20820a00-29d8-11eb-86f1-839258f1f8ad.png)

**Comment by harshavardhana** [comment]
Let's see how this situation can be improved! - perhaps not make an HTTP call? :-)

**Comment by chrisbecke** [comment]
I'm not. But prometheus does. Qhich is monitoring both my actual minio instances is.
And every time prometheus touches the .../metrics endpoint of the gateway, a 403 error is logged on, and counted in the metrics of, the backend minio.
