### ISSUE TITLE
[faq] ERROR Unable to initialize backend: format.json file: expected format-type: fs, found: xl

### ISSUE THREAD

**Issue by rocketkittens** [minio/minio#10925]
#10657  Expected Behavior
docker run should work

## Current Behavior
ERROR Unable to initialize backend: format.json file: expected format-type: fs, found: xl

**Comment by harshavardhana** [comment]
You cannot use single drive after you have used the drive with erasure coded setup, wipe the drive to reuse it with single drive setup
