### ISSUE TITLE
[fixed] Distributed deployment of minio, the download operation time becomes longer after losing a pod

### ISSUE THREAD

**Issue by enayzhu** [minio/minio#10930]
Distributed deployment of Minio, four pods distributed on four nodes, reboot one of the Nodes, and then download the file with MC client. There will be a delay of 1min (1s or 2s in normal state), and finally the file will be downloaded successfully.
Compared with the normal state, downloading the same file takes 1 min more.
## Expected Behavior

I hope that the download operation can proceed unaffected after losing a pod.

## Current Behavior

Performing a download operation after losing a pod will take 1 min more than operating the same file in a normal environment.

## Steps to Reproduce (for bugs)

1.Distributed deployment of 4 minio on 4 nodes
2.Restart one of the nodes
3.After restarting the node, use the mc client to perform the download operation
4.Observation results, it should take 1 min longer than normal operation

## Context

Failed to obtain configuration information, affecting the normal startup of the program
## Your Environment

* Version used (`minio --version`): RELEASE.2020-02-27T00-23-05Z-4-gcb4a9140
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2020-02-27T00-23-05Z-4-gcb4a9140

You need to upgrade to RELEASE.2020-10-28T08-16-50Z @enayzhu
