### ISSUE TITLE
mc tag set returns 502 if not all nodes are online in distributed setup

### ISSUE THREAD

**Issue by annkam** [minio/minio#10939]
## Expected Behavior

I expected tagging to be available when I lose one node in distributed setup.

## Current Behavior

mc tag set returns 502 when one node goes offline in my 12 nodes cluster. There is a LB in front of minio cluster. 

![image](https://user-images.githubusercontent.com/18022078/99758439-4288a300-2b24-11eb-9fd9-58c7b09592bd.png)

If I access one of the nodes directly, the error is different

```
# mc tag set staas-test-direct/test/test.txt "key1=test"                                                              │·············································
mc: <ERROR> Failed to set tags for http://node.example.com:9000/test/test.txt. Put "http://node.example.com:9000│·············································
/test/test.txt?tagging=": Connection closed by foreign host http://node.example.com:9000/test/test.txt?tagging=. Ret│·············································
ry again.
```

## Steps to Reproduce (for bugs)

1. Deploy minio in distributed mode
2. Shutdown one node
3. Try to set a tag on any object

## Context

We can't shutdown even one node for maintenance in our production distributed setup without affecting users who use bucket tagging.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-10-28T08-16-50Z and RELEASE.2020-05-01T22-19-14Z
* Operating System and version (`uname -a`): CentOS 7

**Comment by harshavardhana** [comment]
The error is returned by your LB @annkam not MinIO - configure it properly to fallback

**Comment by annkam** [comment]
I mentioned that if I access one of the nodes directly, I still see the error

**Comment by annkam** [comment]
this is what happens when I connect mc DIRECTLY to one of the 12 nodes (not the one I shutdown)

```
# mc tag set staas-test-direct/test/test.txt "key1=test" --debug                                                      │·············································
mc: <DEBUG> GET /test/?location= HTTP/1.1                                                                               │·············································
Host: s3test25d02.group.s7:9000                                                                                         │·············································
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-11-17T00:39:14Z                                                │·············································
Authorization: AWS4-HMAC-SHA256 Credential=***/20201120/us-east-1/s3/aws4_request,│·············································
 SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**                                             │·············································
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                                  │·············································
X-Amz-Date: 20201120T045019Z                                                                                            │·············································
Accept-Encoding: gzip                                                                                                   │·············································
                                                                                                                        │·············································
mc: <DEBUG> HTTP/1.1 200 OK                                                                                             │·············································
Content-Length: 128                                                                                                     │·············································
Accept-Ranges: bytes                                                                                                    │·············································
Content-Security-Policy: block-all-mixed-content                                                                        │·············································
Content-Type: application/xml                                                                                           │·············································
Date: Fri, 20 Nov 2020 04:50:21 GMT                                                                                     │·············································
Server: MinIO/RELEASE.2020-10-28T08-16-50Z                                                                              │·············································
Vary: Origin                                                                                                            │·············································
X-Amz-Request-Id: 16491E15C97F8460                                                                                      │·············································
X-Xss-Protection: 1; mode=block                                                                                         │·············································
                                                                                                                        │·············································
mc: <DEBUG> Response Time:  6.342998ms                                                                                  │·············································
                                                                                                                        │·············································
mc: <ERROR> Failed to set tags for http://s3test25d02.group.s7:9000/test/test.txt. Put "http://s3test25d02.group.s7:9000│·············································
/test/test.txt?tagging=": Connection closed by foreign host http://s3test25d02.group.s7:9000/test/test.txt?tagging=. Ret│·············································
ry again.                                                                                                               │·············································
 (1) tag-set.go:129 cmd.setTags(..) Tags: [key1=test]                                                                   │·············································
 (0) client-s3.go:2294 cmd.(*S3Client).SetTags(..)                                                                      │·············································
 Release-Tag:RELEASE.2020-11-17T00-39-14Z | Commit:adafa0024ff6 | Host:8d38f6ba57c9 | OS:linux | Arch:amd64 | Lang:go1.1│·············································
5.5 | Mem:2.7 MB/74 MB | Heap:2.7 MB/67 MB. 
```

**Comment by annkam** [comment]
The only request captured with mc admin trace is

`05:11:07.265 [200 OK] s3.GetBucketLocation s3test25d02.group.s7:9000/test/?location=  172.20.117.68     6.841ms      ↑ 7│·············································
7 B ↓ 378 B`

When I call mc tag set it hangs for about a minute before throwing the error and the only request captured with trace is GetBucketLocation

**Comment by harshavardhana** [comment]
> The only request captured with mc admin trace is
> 
> `05:11:07.265 [200 OK] s3.GetBucketLocation s3test25d02.group.s7:9000/test/?location= 172.20.117.68 6.841ms ↑ 7│············································· 7 B ↓ 378 B`
> 
> When I call mc tag set it hangs for about a minute before throwing the error and the only request captured with trace is GetBucketLocation

then this is actually not server related problem - the server is not even seeing the request i.e `mc` is terminating.

**Comment by harshavardhana** [comment]
is s3test25d02.group.s7 pointing to single IP or rr-dns?

**Comment by annkam** [comment]
single IP and that node is online. One of the other nodes is offline. When it comes back online, tagging works again.

It's not mc terminating, it's the node closing the connections as it's written in the error message.

**Comment by harshavardhana** [comment]
> It's not mc terminating, it's the node closing the connections as it's written in the error message.

care to share that as well? @annkam ?

**Comment by harshavardhana** [comment]
is s3test25d02.group.s7 pointing to the same server which you talking to with MinIO and taking it down?

**Comment by annkam** [comment]
@harshavardhana I've already posted full `mc tag set` wih `--debug` output with the error message 7 comments above. 

> is s3test25d02.group.s7 pointing to the same server which you talking to with MinIO and taking it down?

No it's not. Please read my commentaries carefully. 
I use mc to connect to **s3test25d02.group.s7** which points to a single IP
I shutdown another node, **s3test25d12.group.s7** which points to a different single IP

**Comment by harshavardhana** [comment]
@annkam I am talking about server logs

**Comment by annkam** [comment]
This is the log from s3test25d02.group.s7 when I try to set a tag on a object while another node is offline:

Sorry, bad formatting in the first file, reuploaded it 

[minio-server-error.log](https://github.com/minio/minio/files/5571572/minio-server-error.log)

**Comment by harshavardhana** [comment]
Found the fix @annkam was a silly bug.

**Comment by annkam** [comment]
Thanks a lot! Will describe my problems in a more detailed way next time))
