### ISSUE TITLE
Cannot identify who made operations on object with OpenID auth.

### ISSUE THREAD

**Issue by tomsozolins** [minio/minio#10936]
Hello! I am using MinIO with (Keycloak identity provider + LDAP federation). How is it possible from audit perspective to identify which person made changes to the object if MinIO event notification shows only random temporary token id in Principialid field?

I can see log event in Keycloak when user has logged in using MinIO openid, but it is not enough information for audit purposes. 
I would like to know which person made changes to the object and when. Is this possible to achieve?

**Comment by harshavardhana** [comment]
This is logged as part of `requestClaims` that identifies the origin OpenID - look at audit logging https://github.com/minio/minio/tree/master/docs/logging#audit-targets
