### ISSUE TITLE
Unable to upload png batch exported from ps

### ISSUE THREAD

**Issue by zhizzzzzz** [minio/minio#10931]
Unable to upload png batch exported from ps 

![test](https://user-images.githubusercontent.com/20277316/99615769-f4599e00-2a56-11eb-89f2-24f734f9b75b.png)

VERSION
2020-11-13T20:10:18Z
PLATFORM
Host: ac1d212e4e6b | OS: linux | Arch: amd64
RUNTIME
Version: go1.15.5 | CPUs: 16

**Comment by harshavardhana** [comment]
Please describe the issue more clearly @zhizzzzzz - use our templates
