### ISSUE TITLE
server: Feature request: custom content types

### ISSUE THREAD

**Issue by leifcr** [minio/minio#1094]
Ideally all content types would be added to https://github.com/jshttp/mime-db, but I still think it is would be a good feature.

**Comment by harshavardhana** [comment]
> Ideally all content types would be added to https://github.com/jshttp/mime-db, but I still think it is would be a good feature.

Setting custom types through Put operation will be supported when the XL version is merged, for the time being Filesystem backend doesn't remember any custom content-type. So we just rely on mime-db for the best guess.

**Comment by leifcr** [comment]
How about adding an attribute to config.json e.g.:

```
{
  "contentTypes": {
  "application/vnd.dart": {
    "compressible": true,
    "extensions": ["dart"]
  },
  "application/vnd.google-apps.document": {
    "compressible": false,
    "extensions": ["gdoc"]
  }
}
```

The map needs to be rebuilt upon loading the config, but the benefit would be great for applications, which won't come into mimedb. It also helps when mimedb might be get outdated in a production setup.

**Comment by harshavardhana** [comment]
> {
>   "contentTypes": {
>   "application/vnd.dart": {
>     "compressible": true,
>     "extensions": ["dart"]
>   },
>   "application/vnd.google-apps.document": {
>     "compressible": false,
>     "extensions": ["gdoc"]
>   }
> }

We will see how it can be achieved.

**Comment by harshavardhana** [comment]
Server now supports custom content-type with XL backend.  Closing the bug.

**Comment by leifcr** [comment]
@harshavardhana  Would it be possible to revisit this issue? Testing minio on a kubernetes cluster, and this feature would be great to have.

**Comment by harshavardhana** [comment]
> @harshavardhana Would it be possible to revisit this issue? Testing minio on a kubernetes cluster, and this feature would be great to have.

What is the issue? @leifcr MinIO already supports custom content-types across all its modes of operation when you upload an object. Also, please open a new issue describing the problem in detail.

**Comment by leifcr** [comment]
@harshavardhana I guess I must have missed something in the docs. I just tested in the browser to do a quick test using the helm chart to deploy minio, and downloaded the file, and got worng content-type back. Going to test with proper client, and read up on the docs. Any hints on where to read about setting content type? Or would that be client specific?

**Comment by harshavardhana** [comment]
> @harshavardhana I guess I must have missed something in the docs. I just tested in the browser to do a quick test using the helm chart to deploy minio, and downloaded the file, and got worng content-type back. Going to test with proper client, and read up on the docs. Any hints on where to read about setting content type? Or would that be client specific?

Browser is not using S3 API so it tries to do the best case scenario, but you can't really be relying on browser uploads to set proper content-type.  Use the S3 API and set the content-type for your PUT request and that will be stored.

**Comment by leifcr** [comment]
@harshavardhana Thanks. That put me on the right track, and it was really easy to solve

For future reference, here's a command line to do it using s3cmd for testing:
```
s3cmd modify --mime-type=vnd/mysupertype 's3://test-bucket/testfile.strangeformat'
```
reply in the header is then vnd/mysupertype as content-type. For other libraries/integrations, this has to be done either in the put command or by modifying the element afterwards. Both work with minio. Awesome! Thanks again.
