### ISSUE TITLE
"A timeout occured while trying to lock a resource, please reduce your request rate" when uploading over a previous version of the file

### ISSUE THREAD

**Issue by Rush** [minio/minio#10948]
## Expected Behavior
File should upload without a problem. This occured when I tried to overwrite the previously uploaded file with the same name. Deleting the file does not help ...

## Current Behavior
```
$ mc cp docker/build-sh-docker-v*.tgz "target/$S3_BUCKET"
`docker/build-sh-docker-v1.0.2.tgz` -> `target/downloads/build-sh-docker-v1.0.2.tgz`
mc: <ERROR> Failed to copy `build-sh-docker-v1.0.2.tgz`. A timeout occurred while trying to lock a resource, please reduce your request rate
Total: 0 B, Transferred: 246.24 MiB, Speed: 825.37 KiB/s
```

## Context
I am uploading releases of my software to a minio cluster. `mc` is of latest version. Used to happen on older version as well.

## Regression
It regressed by itself. Was running a minio cluster installed in June. After upgrading the issue persisted.

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2020-11-19T23-48-16Z
```
It was also happening on a release from June

* Server setup and configuration:
2 servers, each running a minio cluster on two disks:
```
/dev/sdb1      11716797420 294444032 11422353388   3% /hdd2
/dev/sda1      11716797420 294444032 11422353388   3% /hdd1
```

```
●  dragon2:9000
   Uptime: 2 hours
   Version: 2020-11-19T23:48:16Z
   Network: 2/2 OK
   Drives: 0/0 OK

●  dragon1:9000
   Uptime: 2 hours
   Version: 2020-11-19T23:48:16Z
   Network: 2/2 OK
   Drives: 0/0 OK

398 GiB Used, 10 Buckets, 349,719 Objects
0 drives online, 0 drives offline
```

* Operating System and version (`uname -a`): 
```
Linux dragon 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
as well as 
```
Linux dragon2 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
> $ mc cp docker/build-sh-docker-v*.tgz "target/$S3_BUCKET"
> `docker/build-sh-docker-v1.0.2.tgz` -> `target/downloads/build-sh-docker-v1.0.2.tgz`
> mc: <ERROR> Failed to copy `build-sh-docker-v1.0.2.tgz`. A timeout occurred while trying to lock a resource, please reduce your request rate
> Total: 0 B, Transferred: 246.24 MiB, Speed: 825.37 KiB/s

This is because the locking acquisition timed out due to one of the nodes disconnected - you only have 2 nodes if you lose 1 node you lose quorum for writes - this is an odd setup - at least minimum you should have 3 nodes to satisfy any serious availability guarantees. We call your setup a Toy Setup and not supported for any production workload.

There is nothing to fix here from our end. 

### Toy Setup

Capacity constrained environments works but not recommended for production.

| servers | drives (per node) | stripe_size | parity chosen (default) | tolerance for reads (servers) | tolerance for writes (servers) |
|--------:|------------------:|------------:|------------------------:|------------------------------:|-------------------------------:|
|       1 |                 1 |           1 |                       0 |                             0 |                              0 |
|       1 |                 4 |           4 |                       2 |                             0 |                              0 |
|       4 |                 1 |           4 |                       2 |                             2 |                              3 |
|       5 |                 1 |           5 |                       2 |                             2 |                              2 |
|       6 |                 1 |           6 |                       3 |                             3 |                              4 |
|       7 |                 1 |           7 |                       3 |                             3 |                              3 |

**Comment by Rush** [comment]
Appreciate your honesty. I'll gladly upgrade to a larger cluster once the project can cover the costs.

The cluster is in fact online and I can upload most files without issues. If failing to upload is expected behavior maybe it should be documented?

**Comment by harshavardhana** [comment]
> Appreciate your honesty. I'll gladly upgrade to a larger cluster once the project can cover the costs.
> 
> The cluster is in fact online and I can upload most files without issues. If failing to upload is expected behavior maybe it should be documented?

It is definitely not expected you should verify if you have network problems @Rush in your cluster just loosing one server momentarily can cause disruptions such as these. 

It would be better to investigate this from a networking point of view.

**Comment by Rush** [comment]
Thank you. Will investigate and will report back if I learn of anything that would indicate a bug in minio rather than network instability.

**Comment by harshavardhana** [comment]
> Thank you. Will investigate and will report back if I learn of anything that would indicate a bug in minio rather than network instability.

We would be happy to debug if you have found anything unusual.

**Comment by Rush** [comment]
I did more debugging and I cannot find any network issues. What I found however was some locks don't ever seem to expire hmm:
```
> mc admin top locks locals
71 hours              READ    downloads/build-docker-v1.0.2.tgz
71 hours              READ    downloads/build-sh-docker-v1.0.2.tgz
69 hours              READ    downloads/build-docker-v1.0.3.tgz
69 hours              READ    downloads/build-sh-docker-v1.0.3.tgz
35 hours              READ    downloads/build-sh-docker-v1.0.3.tgz
```
Is there a way to debug what is holding those READ locks?

**Comment by harshavardhana** [comment]
> I did more debugging and I cannot find any network issues. What I found however was some locks don't ever seem to expire hmm:
> 
> ```
> > mc admin top locks locals
> 71 hours              READ    downloads/build-docker-v1.0.2.tgz
> 71 hours              READ    downloads/build-sh-docker-v1.0.2.tgz
> 69 hours              READ    downloads/build-docker-v1.0.3.tgz
> 69 hours              READ    downloads/build-sh-docker-v1.0.3.tgz
> 35 hours              READ    downloads/build-sh-docker-v1.0.3.tgz
> ```
> 
> Is there a way to debug what is holding those READ locks?

yes sure please provide the `mc admin top locks --json` - also how were these uploaded?

**Comment by harshavardhana** [comment]
And how frequently can you reproduce this? @Rush

**Comment by klimermana** [comment]
Hi @harshavardhana .  We are running into a similar problem of locks not expiring and at higher loads getting the "please reduce your request rate" error.

We are running a 3 node cluster with ten drive nodes on each and version RELEASE.2020-11-19T23-48-16Z.

We are seeing different things in the logs for each node:
<ip 1> we are seeing constant printouts for:
> Quorum not met
Releasing abandoned lock
Releasing abandoned lock
Releasing abandoned lock
Releasing abandoned lock


<ip 2> we see new locks being created for requests coming in but nothing about quorums / abandoned locks

<ip 3> we see "quorum not met" and new requests coming in, but nothing about abandoned locks.

The locks printout can be found here:
https://gist.github.com/klimermana/bc9cf54bfa5c233a881fe22b3b8a4c8b

**Comment by R-omk** [comment]
We have a similar problem


version: RELEASE.2020-11-19T23-48-16Z'

```
./mc admin top locks img
Time                  Type    Resource
8 hours               WRITE   imagefield-data/59/50/50059.json
8 hours               WRITE   .minio.sys/runDataCrawler.lock


 ./mc admin top locks img --json
{
 "status": "success",
 "locks": {
  "time": "2020-11-28T02:58:50.252406434Z",
  "resource": "imagefield-data/59/50/50059.json",
  "type": "WRITE",
  "source": "[erasure-object.go:656:erasureObjects.putObject()]",
  "serverlist": [
   "imagedata-minio-2.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-3.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-4.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-5.imagedata-minio-svc.apps.svc.cluster.local:9000"
  ],
  "owner": "imagedata-minio-0.imagedata-minio-svc.apps.svc.cluster.local:9000",
  "id": "0c6e10cd-7f1b-4bda-af3b-e67c11ecc75d",
  "quorum": 4
 }
}
{
 "status": "success",
 "locks": {
  "time": "2020-11-28T03:00:45.404727387Z",
  "resource": ".minio.sys/runDataCrawler.lock",
  "type": "WRITE",
  "source": "[data-crawler.go:75:runDataCrawler()]",
  "serverlist": [
   "imagedata-minio-0.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-2.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-3.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-4.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-5.imagedata-minio-svc.apps.svc.cluster.local:9000",
   "imagedata-minio-1.imagedata-minio-svc.apps.svc.cluster.local:9000"
  ],
  "owner": "imagedata-minio-2.imagedata-minio-svc.apps.svc.cluster.local:9000",
  "id": "f9fade21-620d-4a82-9366-e3a90a2f5edf",
  "quorum": 4
 }
}
```
--
That is all customizations

```
      env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: imagedata-minio
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: imagedata-minio
              key: secretkey
        - name: MINIO_BROWSER
          value: 'off'
        - name: MINIO_COMPRESS
          value: 'on'
        - name: MINIO_DISK_USAGE_CRAWL_DELAY
          value: '40'
        - name: MINIO_DISK_USAGE_CRAWL_ENABLE
          value: 'on'
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: 'EC:2'
```

**Comment by harshavardhana** [comment]
I am not able to reproduce in any meaningful way, more help would be appreciated such as set MINIO_DSYNC_TRACE=1 environment and `mc cp` to show us the errors.

**Comment by Rush** [comment]
I'll try to reproduce in the next few days. It was pretty consistent for me

**Comment by fcomte** [comment]
I am having this issue too. I will try to reproduce aswell

**Comment by harshavardhana** [comment]
Please test this out and give feedback https://github.com/minio/minio/pull/11030

**Comment by Rush** [comment]
Nice! Sorry but I'm not familiar with the release process. When will it be part of the official binary?

**Comment by harshavardhana** [comment]
> Nice! Sorry but I'm not familiar with the release process. When will it be part of the official binary?

Please build the binary yourself to validate this on baremetal  @Rush - if you are in a container env get `minio/minio:edge` to test this.
