### ISSUE TITLE
[fixed] MinIO does not send object delete log to Audit Webhook when using MinIO Browser.

### ISSUE THREAD

**Issue by tomsozolins** [minio/minio#10941]
Hello!

I have a problem with MinIO audit webhook not logging delete operations on objects when using MinIO Browser. 

When i upload object in MinIO Browser it gets logged:
![image](https://user-images.githubusercontent.com/48243828/99781899-1f102900-2b21-11eb-913f-ae588d56bdd6.png)
However when i delete object through MinIO Browser is does not send log to webhook, but it is logged with ObjectRemoved in MC watch:
![image](https://user-images.githubusercontent.com/48243828/99782854-60ed9f00-2b22-11eb-9caf-05d00e51867c.png)

I tried to delete object through MC client, then the message gets logged to Audit Webhook:
![image](https://user-images.githubusercontent.com/48243828/99782265-92199f80-2b21-11eb-8464-76b640595314.png)

The problem is that clients will be using MinIO Browser not MC client,  so if they delete some object it won't be logged in MinIO audit logs.

**Comment by harshavardhana** [comment]
MinIO browser has limited functionalities @tomsozolins it's not meant to mimic everything that we have - for example it doesn't support downloading versions etc. This UI is frozen and not taking more feature requests. 

You are better off using our new implementation which has all the necessary features https://github.com/minio/console

**Comment by tomsozolins** [comment]
> MinIO browser has limited functionalities @tomsozolins it's not meant to mimic everything that we have - for example it doesn't support downloading versions etc. This UI is frozen and not taking more feature requests.
> 
> You are better off using our new implementation which has all the necessary features https://github.com/minio/console

I have been trying the console for a while, i like it more than MinIO browser because there are a lot more stuff available, but wasn't able to migrate to it because there are some MinIO Browser features which i can't find in the Console. 
For example:
1) Does Minio Console support OpenID authentification? I have already configured MinIO browser with Keycloak identity provider and it works very well, but couldn't find any documentation if it possible to configure this authentification method for Console.
2) MinIO Browser supports uploading folders by drag and drop, while in Console i can upload only single object.  Will there be support in Console for this kind of uploading behavior?
3) In MinIO browser there is a share button for each object which generates temporary url to the object. Will this be supported in MinIO Console?

**Comment by harshavardhana** [comment]
> * Does Minio Console support OpenID authentification? I have already configured MinIO browser with Keycloak identity provider and it works very well, but couldn't find any documentation if it possible to configure this authentification method for Console.
> * MinIO Browser supports uploading folders by drag and drop, while in Console i can upload only single object.  Will there be support in Console for this kind of uploading behavior?
> * In MinIO browser there is a share button for each object which generates temporary url to the object. Will this be supported in MinIO Console?

All of this will be supported in time @tomsozolins follow console activity for now

**Comment by tomsozolins** [comment]
> > * Does Minio Console support OpenID authentification? I have already configured MinIO browser with Keycloak identity provider and it works very well, but couldn't find any documentation if it possible to configure this authentification method for Console.
> > * MinIO Browser supports uploading folders by drag and drop, while in Console i can upload only single object.  Will there be support in Console for this kind of uploading behavior?
> > * In MinIO browser there is a share button for each object which generates temporary url to the object. Will this be supported in MinIO Console?
> 
> All of this will be supported in time @tomsozolins follow console activity for now

Thank you !

**Comment by harshavardhana** [comment]
FWIW this is fixed in #10947
