### ISSUE TITLE
[faq] mirror two minio servers

### ISSUE THREAD

**Issue by Danbuth** [minio/minio#10956]
Here I have two minio servers Instance.
I want to let the two minio server auto sync.
such as write data to the A minio server. And the B minio server will rsync data from A. Or A send data to B.
Do minio have this feature

**Comment by harshavardhana** [comment]
`mc mirror --watch`  is your friend @Danbuth or server side replication - https://docs.minio.io/docs/minio-bucket-replication-guide.html

Next time please use the issue template to describe your issue. We specifically added issue templates so that community can describe their issue properly.
