### ISSUE TITLE
Strategy for decommissioning nodes

### ISSUE THREAD

**Issue by fennm** [minio/minio#10954]
Note that this is not really a bug report, but also not a feature request, so feel free to re-categorize as appropriate.

I've read through the MinIO documentation and GitHub issues, and while expanding a cluster by adding new nodes is documented (https://docs.minio.io/docs/distributed-minio-quickstart-guide.html), and the design decision not to include rebalancing code has been discussed (#7986), I haven't found a good discussion on how to decommission nodes in a cluster while keeping the data intact.

I can see a couple different ways to go about this:

1.  Mirror data at the application level:
    1. Create a new minio cluster on new hardware
    1. Use `mc mirror` to mirror all the buckets to the new cluster in a loop
    1. Quiesce writes
    1. Redirect applications to the new cluster
    1. Decommission the old cluster when done
1.  Swap out nodes one at a time.  For each node to be decommissioned:
    1. Shut down the old node
    2. Start a new node with the same name
    1.  Wait for the cluster to heal

Is one of these strategies preferred over the other?  Is there a different strategy that I'm missing?

**Comment by harshavardhana** [comment]
We are working on an inbuilt strategy for migrating to new set of clusters using `mc admin decom` command which shall be available in future, it is currently under design and development.

**Comment by fennm** [comment]
Cool!  In the meantime, obviously strategy (1) above would work and be safe, but is (2) something to be avoided?

**Comment by harshavardhana** [comment]
> Cool! In the meantime, obviously strategy (1) above would work and be safe, but is (2) something to be avoided?

(1) is safe and preferred - (2) is not well documented or tested in the field so advise is proceed with caution.

**Comment by fennm** [comment]
Understood, thanks!
