### ISSUE TITLE
Directory deletion failed

### ISSUE THREAD

**Issue by zxs-git** [minio/minio#10969]
Failed to delete the directory.After the deletion, the UI does not display the directory, but when the page is refreshed, the directory reappears

If there are files in the directory, the files will be deleted, but the folder will still exist

**Comment by harshavardhana** [comment]
> Failed to delete the directory.After the deletion, the UI does not display the directory, but when the page is refreshed, the directory reappears
> 
> If there are files in the directory, the files will be deleted, but the folder will still exist

You haven't opened the issue with details on what is required, the entire issue template is ignored. Unfortunately, we have to close this issue.
