### ISSUE TITLE
MinIO can't delete previous deployment

### ISSUE THREAD

**Issue by prabhant** [minio/minio#10963]
MinIO distributed setup is 
Hi, I have one small issue with minio erasure code. I was trying to deploy on two notes and at first, i tried

Any idea  how to deal with this situation?
## Expected Behavior

Hi, I was trying to deploy on two notes and at first, I tried this command on both nodes

1. minio server http://mynode{1...2}.mywebsite.com/export{1...6}

Later I found out that internal IP might be the solution so I tried

2.  minio server http://ipaddress1/export{1...6} http://ipaddress2/export{1...6}

this gave me same errors but the main problem I'm getting right now is  this error when I try to execute the first command again:
**ERROR Unable to initialize backend: 2nd disk is already being used in another erasure deployment. (Number of disks specified: 12 but the number of disks found in the 2nd disk's format.json: 6)**

## Context
I'm trying to deploy Minio between two nodes and now because of this issue I'm not sure how to proceed anymore
My question right now is how to remove this error and delete the other minio deployment. Not able to find anything like this in the documentation

## Your Environment

* Version used (`minio --version`): RELEASE.2020-10-09T22-55-05Z

**Comment by nitisht** [comment]
Can you make sure the disks `/export{1...6}` are empty on both nodes (make sure to delete `.minio.sys` on all drives) and try freshly with

> minio server http://mynode{1...2}.mywebsite.com/export{1...6}

If it doesn't work, please post the outcome here.

**Comment by prabhant** [comment]
Working now, Thanks for quick response.
