### ISSUE TITLE
Directory deletion failed

### ISSUE THREAD

**Issue by zxs-git** [minio/minio#10967]
目录名称：knowledge-base/[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]/

当我删除目录 ：[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]/  在minIO UI 上删除成功。但是当我刷新页面后，这个目录又展示出来

**Comment by harshavardhana** [comment]
Please open issues in English! @zxs-git
