### ISSUE TITLE
[faq] Unable to enable versioning. A header you provided implies functionality that is not implemented.

### ISSUE THREAD

**Issue by mannyd28** [minio/minio#10966]
Trying to enable bucket versioning on a new bucket using MinIO client and receive an error: Unable to enable versioning. A header you provided implies functionality that is not implemented. This is on macOS Catalina 10.15.6.

## Expected Behavior

```
% mc mb myalias/mybucket
Bucket created successfully `myalias/mybucket`.
% mc version enable myalias/mybucket
myalias/mybucket versioning is enabled
```

## Current Behavior

```
% mc mb myalias/mybucket
Bucket created successfully `myalias/mybucket`.
% mc version enable myalias/mybucket
mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.
```

## Steps to Reproduce (for bugs)

1. `brew install minio/stable/minio`
2. `brew install minio/stable/mc`
3. `export MINIO_ACCESS_KEY=minio`
4. `export MINIO_SECRET_KEY=miniostorage`
5. `minio server ~/.minio/data &`
6. `mc alias set myalias http://127.0.0.1:9000 minio miniostorage`
7. `mc mb myalias/mybucket`
8. `mc version enable myalias/mybucket`

## Context

I am trying to implement versioning on the bucket to provide version history and ability to revert to previous versions to my users.

## Regression

Maybe. It is working on `RELEASE.2020-07-27T18-37-02Z` on **RHEL 7**. I tried the to download the same version of the binary for macOS from https://dl.min.io/server/minio/release/darwin-amd64/archive/minio.RELEASE.2020-07-27T18-37-02Z, but I received a different error when trying to copy a file to a versioned bucket on that version on macOS (following the same steps above, the error occurred after step 8):

```
% mc cp ~/path/to/file myalias/mybucket
mc: <ERROR> Failed to copy `/Users/username/path/to/file`. A header you provided implies functionality that is not implemented
```

## Your Environment

* Version used (`minio --version`): 
`minio version RELEASE.2020-11-19T23-48-16Z`
`mc version RELEASE.2020-11-17T00-39-14Z`
* Server setup and configuration: See steps to reproduce above
* Operating System and version (`uname -a`): `Darwin MacBook-Pro 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

**Comment by harshavardhana** [comment]
Single drive mode doesn't allow versioning to be enabled @mannyd28 it is not a regression 

> Maybe. It is working on `RELEASE.2020-07-27T18-37-02Z` on **RHEL 7**. I tried the to download the same version of the binary for macOS from https://dl.min.io/server/minio/release/darwin-amd64/archive/minio.RELEASE.2020-07-27T18-37-02Z, but I received a different error when trying to copy a file to a versioned bucket on that version on macOS (following the same steps above, the error occurred on step 7):

This was an error on our end we should have never allowed it.
