### ISSUE TITLE
If CompressionType is not set, SelectObjectContent API return junk instead of InvalidTextEncoding error

### ISSUE THREAD

**Issue by ritik-raj23** [minio/minio#10970]
## Expected Behavior
Should return `InvalidTextEncoding` error.

## Current Behavior
Returns junk.

## Steps to Reproduce (for bugs)

	public static String getCSVZipObjectHeader(String bucketName, String objectName,
		      MinioClient minioClient) throws Exception{
		try {
			String sqlExpression = "select * from S3Object limit 1";
			InputSerialization is = new InputSerialization(null, false, null, null, FileHeaderInfo.NONE, null, null, null);
			OutputSerialization os = new OutputSerialization(null, null, null, QuoteFields.ASNEEDED, null);
			SelectResponseStream stream =
			    minioClient.selectObjectContent(
			        SelectObjectContentArgs.builder()
			            .bucket(bucketName)
			            .object(objectName)
			            .sqlExpression(sqlExpression)
			            .inputSerialization(is)
			            .outputSerialization(os)
			            .requestProgress(true)
			            .build());

			byte[] buf = new byte[2048];
			int bytesRead = stream.read(buf, 0, buf.length);
			String header =  (new String(buf, 0, bytesRead, StandardCharsets.UTF_8)).trim();
			stream.close();
			log.info(header);
			return header;
		}catch(Exception e) {
			log.error("Error retrieving header from S3 Object. {}", e.getMessage());
			throw e;
		}
	}

## Context
Extracting the header from a compressed CSV file

## Your Environment

* Version used (`minio --version`):  
minio version RELEASE.2020-08-18T19-41-00Z
* Server setup and configuration: 
Distributed MinIO 4 Servers 

* Operating System and version (`uname -a`):
Linux itom-di-minio-0 3.10.0-862.14.4.el7.x86_64 minio/minio#1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ritik-raj23** [comment]
@balamurugana What is the release-date for minio-java ? Such that I can consume it and validate

**Comment by harshavardhana** [comment]
> @balamurugana What is the release-date for minio-java ? Such that I can consume it and validate

There are no set dates @ritik-raj23 - just follow the PR and build the patch locally yourself if needed.
