### ISSUE TITLE
High load after upgrading to RELEASE.2020-11-10T21-02-24Z on CIFS mount

### ISSUE THREAD

**Issue by fdziarmagowski** [minio/minio#10975]
Since upgrading to RELEASE.2020-11-10T21-02-24Zthere is a very high CPU load (up to 80) to be observed on nodes running minio container during backups (using velero here). Running with this version we see many backups failing. Downgrading to RELEASE.2020-07-02T00-15-09Z solves the problem for us.
Our setup: k8s (1.17.4), docker (19.03.4) and velero (1.5.3), minio runs as a s3backend for velero storing all data on a cifs mount (low perfomance Hetzner storage box). The cifs mount is attached to the (minio)s3backup k8s Deployment as a flexVolume using microsoft.com/smb driver. minio is available to other components over https (ingress provided).
The minio container is not showing anything spectacular in logs, beside the standard short notice about browser access and object API.

**Comment by harshavardhana** [comment]
@fdziarmagowski please explain in more detail what is the entire setup 

- what is the actual setup like? provide us with yamls examples for us to reproduce it?
- what operations are being performed on the server which leads to this? 
- capture `mc admin profile start` ?

**Comment by harshavardhana** [comment]
> @fdziarmagowski please explain in more detail what is the entire setup
> 
> * what is the actual setup like? provide us with yamls examples for us to reproduce it?
> * what operations are being performed on the server which leads to this?
> * capture `mc admin profile start` ?

Worthy of close, nothing actionable without more information
