### ISSUE TITLE
Different hostname for presigned URLs

### ISSUE THREAD

**Issue by traed** [minio/minio#10972]
This is a duplicate of #10222 that got marked as stale but was never resolved. We really need this feature to be able to use minio in a dockerized environment.

**Comment by harshavardhana** [comment]
That is not possible as per the original issue #10222 - we cannot leak information in this manner. You should just use the hostname that is being pointed to by incoming client as presigned URL.

i.e your SDK constructor should use the incoming hostname instead. Nothing special needs to be done on server side.
