### ISSUE TITLE
Support federation in kubernetes without coredns+etcd plugin

### ISSUE THREAD

**Issue by rustysys-dev** [minio/minio#10976]
**Is your feature request related to a problem? Please describe.**
Currently minio seems to only support federation using etcd paths and coredns with the etcd plugin.

Kubernetes systems with coredns use the `kubernetes` plugin.  This doesn't seem compatible with the current state of minio with regards to federation in minio.  

Are there any plans for implementing federation in kubernetes without the coredns+etcd combo?  It would be nice to see closer integration with kubernetes in this area.

**Describe the solution you'd like**
I don't claim to be an expert in this area, and don't know if it would work but it may be as easy as creating a kubernetes service for created buckets?

**Comment by harshavardhana** [comment]
Federation is deprecated @rustysys-dev and not recommended - we wouldn't be adding it in operator.

**Comment by mynameisandresb** [comment]
@harshavardhana Deprecated in general? I don't see anything in the minio forms that say we should not be using federation. Should we not be using federation for minio/minio?

**Comment by harshavardhana** [comment]
> @harshavardhana Deprecated in general? I don't see anything in the minio forms that say we should not be using federation. Should we not be using federation for minio/minio?

federation is meant for global DNS - most deployments don't need it as the scale is too small to setup all these components.  If you have the scale then sure use it - but minio/operator is not planning to support it for now.
