### ISSUE TITLE
Including only specific functions if minio into aws-autoloader

### ISSUE THREAD

**Issue by dinohrascanec** [minio/minio#10985]
Currently we're using AWS-PHP-SDK for communication with min.io server. We have installed it in traditional way by downloading and unzipping file & including it with `require_once '../aws-autoloader.php';` In aws-autoloader.php there's about 1000 requires. What we need is only 2 functions of Aws\S3\S3Client: getObject() and putObject(). Is there a way to include only those 2 functions instead of whole package which is 20+Mb large?

## Expected Behavior
We would like to include only getObject() and putObject() of Aws\S3\S3Client into our project.

## Current Behavior
We're including whole package by `require_once '../aws-autoloader.php'`

## Context
We would like to escape including whole package (20+Mb) with including only functions we want (getObject() and putObject()) due to better & quicker performance.

## Your Environment
* Version used (`minio --version`): Latest
* Server setup and configuration: VPS
* Operating System and version (`uname -a`): Ubuntu 16.04

**Comment by nitisht** [comment]
@dinohrascanec this is the MinIO Server repo, written in go. I think you want to create an issue in aws-sdk-php repo.
