### ISSUE TITLE
Error: unformatted disk found

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#10981]
When I migrated one of the 4-node minio services to a new machine, the corresponding directories and parameters were configured, and the service failed to run normally.

## Expected Behavior

normal running

## Current Behavior
![image](https://user-images.githubusercontent.com/27141040/100306488-807f3e80-2fde-11eb-9649-2e0c87160a9f.png)

## Steps to Reproduce (for bugs)
1. Deploy a minio cluster with 4 services
2. Run for a while
3. Move one of the services to new Server
4. Start up

* Version used (`minio --version`):
minio version RELEASE.2020-07-13T18-09-56Z

* Server setup and configuration:
* Operating System and version (`uname -a`):
Linux minio 4.4.246-1.el7.elrepo.x86_64 #1 SMP Tue Nov 24 09:26:59 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is correct it shows that you have a new drive at /home/minio/data - someone has either removed or purged `.minio.sys/`

**Comment by kendn1993** [comment]
> This is correct it shows that you have a new drive at /home/minio/data - someone has either removed or purged `.minio.sys/`

I deleted this file. How can I make the application serve normally?

**Comment by harshavardhana** [comment]
> I deleted this file. How can I make the application serve normally?

If you deleted it MinIO would think that you removed a drive @kendnone - you should run `mc admin heal -r` to heal the drive

**Comment by kendn1993** [comment]
> > I deleted this file. How can I make the application serve normally?
> 
> If you deleted it MinIO would think that you removed a drive @kendnone - you should run `mc admin heal -r` to heal the drive

![Uploading image.png…]()

**Comment by kendn1993** [comment]
thank you ,how can this command work
