### ISSUE TITLE
s3cmd - can't connect, SSL certificate verification failure: SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by stuaxo** [minio/minio#10989]
This is probably a duplicate for some bugs the stalebot shut.

I pulled and rebuilt my docker containers
Installed `s3cmd` from pip, but can't seem to connect:

```sh
$ s3cmd --host=s3:9003 ls
ERROR: SSL certificate verification failure: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)

$ s3cmd --no-check-certificate --host=s3:9003 ls
ERROR: SSL certificate verification failure: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124

$ echo signature_v2 = False > ~/.s3cfg

s3cmd --no-check-certificate --host=s3:9003 ls
ERROR: SSL certificate verification failure: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124

$ echo signature_v2 = True > ~/.s3cfg

$ s3cmd --no-check-certificate --host=s3:9003 ls
ERROR: SSL certificate verification failure: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124
```

**Comment by harshavardhana** [comment]
We do not support TLSv1.1 clients @stuaxo and there are stricter restrictions on TLS usage.

**Comment by stuaxo** [comment]
Does s3cmd work with minio ?

This is for local development so I don't need security of any kind.

**Comment by harshavardhana** [comment]
> Does s3cmd work with minio ?
> 
> This is for local development so I don't need security of any kind.

Of course it does @stuaxo s3cmd uses us in their CI/CD pipeline, make sure to turn off TLS in s3cmd config if your intention is locally running MinIO and MinIO is not configured with certificates.

**Comment by stuaxo** [comment]
Fantastic.   I'll check out the certificate situation and have a look at their CI setup.
