### ISSUE TITLE
compiling Minio after generating the new UI-Assets.go file

### ISSUE THREAD

**Issue by imopro** [minio/minio#10987]
First, I removed ui-assets.go from the Minio/Browser directory. Then I followed the instructions in the README in the Minio/Browser folder and did the following:
### Generate ui-assets.go
```sh
npm run release
` ` `
When I execute the command above, I create a new UI-assets.go. Then I go to the parent directory to execute "make", but the following error occurs:
#make
browser/ui-assets.go:412:34: undefined: os
browser/ui-assets.go:413:10: undefined: os
make: *** [Makefile:72: build] Error 2

Next, i execute the "make verifiers"

#make verifiers
Running fmt check
Running lint check
WARN [runner] Can't run linter goanalysis_metalinter: S1039: failed prerequisites: [(inspect@github.com/minio/minio/browser, isgenerated@github.com/minio/minio/browser): analysis skipped: errors in package: [/opt/test-isos/minio/browser/ui-assets.go:412:34: undeclared name: os /opt/test-isos/minio/browser/ui-assets.go:413:10: undeclared name: os]]
ERRO Running error: S1039: failed prerequisites: [(inspect@github.com/minio/minio/browser, isgenerated@github.com/minio/minio/browser): analysis skipped: errors in package: [/opt/test-isos/minio/browser/ui-assets.go:412:34: undeclared name: os /opt/test-isos/minio/browser/ui-assets.go:413:10: undeclared name: os]]
make: *** [Makefile:41: lint] Error 3

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
Ubuntu
go 1.14.7
npm 7.0.14
go-bindata 3.1.0
node 15.3.0

**Comment by harshavardhana** [comment]
> ```shell
> When I execute the command above, I create a new UI-assets.go. Then I go to the parent directory to execute "make", but the following error occurs:
> #make
> browser/ui-assets.go:412:34: undefined: os
> browser/ui-assets.go:413:10: undefined: os
> make: *** [Makefile:72: build] Error 2
> ```

Looks like some Go runtime errors, most probably a bad Go installation `os` package cannot be missing other than some screwed up GOROOT env.

**Comment by imopro** [comment]
> > ```shell
> > When I execute the command above, I create a new UI-assets.go. Then I go to the parent directory to execute "make", but the following error occurs:
> > #make
> > browser/ui-assets.go:412:34: undefined: os
> > browser/ui-assets.go:413:10: undefined: os
> > make: *** [Makefile:72: build] Error 2
> > ```
> 
> Looks like some Go runtime errors, most probably a bad Go installation `os` package cannot be missing other than some screwed up GOROOT env.

But the same go environment, using “Git clone” ui-assets.go to "make" compilation is no problem. why? Is it uI-assets.go?
