### ISSUE TITLE
MinIO Browser upload failure - net::ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by tomsozolins** [minio/minio#10986]
Hello!
`minio version RELEASE.2020-11-25T22-36-25Z` (same problem happens also on `minio version RELEASE.2020-11-19T23-48-16Z)`
I have a problem with multiple files failing to upload - MinIO Browser shows error 503 and Server not initialized.

MinIO service status:
```node3 minio[1086]: API: ClusterCheckHandler()
Nov 26 15:27:43 node3 minio[1086]: Time: 15:27:43 EET 11/26/2020
Nov 26 15:27:43 node3 minio[1086]: DeploymentID: XXX
Nov 26 15:27:43 node3 minio[1086]: RequestID: 164B11CCC1D14AC3
Nov 26 15:27:43 node3 minio[1086]: RemoteHost: X.X.X.X
Nov 26 15:27:43 node3 minio[1086]: Host: node3:9000
Nov 26 15:27:43 node3 minio[1086]: UserAgent: Go-http-client/1.1
Nov 26 15:27:43 node3 minio[1086]: Error: Server not initialized, please try again (*errors.errorString)
Nov 26 15:27:43 node3 minio[1086]:        2: cmd/peer-rest-client.go:637:cmd.(*peerRESTClient).GetLocalDiskIDs()
Nov 26 15:27:43 node3 minio[1086]:        1: cmd/notification.go:1260:cmd.(*NotificationSys).GetLocalDiskIDs.func1()```
```

![image](https://user-images.githubusercontent.com/48243828/100357133-ed093600-2ffc-11eb-882b-75b1b0b77612.png)

The upload failures happens more if i drag and drop two or more directories in MinIO Browser upload. 
If i upload only single folder then the upload has less failures.

MC trace is showing only the successfull uploads and it does not show the failed ones.

Haproxy:
![image](https://user-images.githubusercontent.com/48243828/100360699-f5b03b00-3001-11eb-92a8-bd93f559b7e9.png)

Original directory:
![image](https://user-images.githubusercontent.com/48243828/100365291-f77cfd00-3007-11eb-927e-73bb82f860b7.png)

MinIO upload:
![image](https://user-images.githubusercontent.com/48243828/100365343-082d7300-3008-11eb-9821-2fa251a8db46.png)

When uploading the Chrome Console shows exactly 18 errors matching the missing file count.
![image](https://user-images.githubusercontent.com/48243828/100367876-89d2d000-300b-11eb-9ac0-cb982345d2c9.png)

`index_bundle-2020-11-21T03-45-04Z.js:49 POST https://XXX/minio/webrpc net::ERR_INSUFFICIENT_RESOURCES`

What resources are insufficient? The cluster has 320TB capacity and is basically empty.

**Comment by harshavardhana** [comment]
> `index_bundle-2020-11-21T03-45-04Z.js:49 POST https://XXX/minio/webrpc net::ERR_INSUFFICIENT_RESOURCES`

This looks like a browser error and it's overloaded on the client-side. Nothing to do with the server AFAICS. 

> Nov 26 15:27:43 node3 minio[1086]: UserAgent: Go-http-client/1.1
> Nov 26 15:27:43 node3 minio[1086]: Error: Server not initialized, please try again (*errors.errorString)
> Nov 26 15:27:43 node3 minio[1086]:        2: cmd/peer-rest-client.go:637:cmd.(*peerRESTClient).GetLocalDiskIDs()
> Nov 26 15:27:43 node3 minio[1086]:        1: cmd/notification.go:1260:cmd.(*NotificationSys).GetLocalDiskIDs.func1()```

This error is not related to browser upload failure - this is some other cluster health check you are running that failed.
