### ISSUE TITLE
Minio clustercheckhandler using external IP's

### ISSUE THREAD

**Issue by Iguana9999phil** [minio/minio#10998]
running an 8 node cluster and having random issues with files not being served, checked the logs and minio seems to have issues connecting to the others servers. While checking I noticed the external IP's are used instead of the set internal IP's.
## Expected Behavior
Minio should check using internal IP's.

## Current Behavior
Minio checks using external IP's, probably because those are first listed as endpoints.

## Possible Solution
Make it possible to set the IP range used / interface used for all internal traffic.

## Steps to Reproduce (for bugs)

1. Setup 8 node cluster with 2 interfaces, 1 external facing (ext IP's for clients) 2nd internal facing for internal traffic.
2. change /etc/hosts to make sure FQDN used are pointing to the internal IP's.
3. Start cluster.

Minio on the node will show using all interfaces as endpoints. 

Nov 29 20:52:41 storage1 minio[30336]: Status:         120 Online, 0 Offline.
Nov 29 20:52:41 storage1 minio[30336]: Endpoint:  https://xx.xx.xx.ext  https://xx.xx.xx.int  https://127.0.0.1
Nov 29 20:52:41 storage1 minio[30336]: Browser Access:

## Context
Nov 29 20:49:15 storage1 minio[24851]: API: ClusterCheckHandler()
Nov 29 20:49:15 storage1 minio[24851]: Time: 20:49:15 PST 11/29/2020
Nov 29 20:49:15 storage1 minio[24851]: DeploymentID: 718f791a-e0e6-449d-ac7f-d225cb997c12
Nov 29 20:49:15 storage1 minio[24851]: RequestID: 164BFB6EC27180FF
Nov 29 20:49:15 storage1 minio[24851]: RemoteHost: xx.xx.xx.ext
Nov 29 20:49:15 storage1 minio[24851]: Host: storage1.domain.com:443
Nov 29 20:49:15 storage1 minio[24851]: UserAgent: Go-http-client/1.1
Nov 29 20:49:15 storage1 minio[24851]: Error: context deadline exceeded (context.deadlineExceededError)
Nov 29 20:49:15 storage1 minio[24851]:        2: cmd/peer-rest-client.go:642:cmd.(*peerRESTClient).GetLocalDiskIDs()
Nov 29 20:49:15 storage1 minio[24851]:        1: cmd/notification.go:1260:cmd.(*NotificationSys).GetLocalDiskIDs.func1()
Nov 29 20:49:25 storage1 minio[24851]: API: ClusterCheckHandler()
Nov 29 20:49:25 storage1 minio[24851]: Time: 20:49:25 PST 11/29/2020
Nov 29 20:49:25 storage1 minio[24851]: DeploymentID: 718f791a-e0e6-449d-ac7f-d225cb997c12
Nov 29 20:49:25 storage1 minio[24851]: RequestID: 164BFB713E637D6F
Nov 29 20:49:25 storage1 minio[24851]: RemoteHost: xx.xx.xx.ext
Nov 29 20:49:25 storage1 minio[24851]: Host: storage1.domain.com:443
Nov 29 20:49:25 storage1 minio[24851]: UserAgent: Go-http-client/1.1
Nov 29 20:49:25 storage1 minio[24851]: Error: context deadline exceeded (context.deadlineExceededError)
Nov 29 20:49:25 storage1 minio[24851]:        2: cmd/peer-rest-client.go:642:cmd.(*peerRESTClient).GetLocalDiskIDs()
Nov 29 20:49:25 storage1 minio[24851]:        1: cmd/notification.go:1260:cmd.(*NotificationSys).GetLocalDiskIDs.func1()
Nov 29 20:49:26 storage1 minio[24851]: API: ClusterCheckHandler()
Nov 29 20:49:26 storage1 minio[24851]: Time: 20:49:26 PST 11/29/2020
Nov 29 20:49:26 storage1 minio[24851]: DeploymentID: 718f791a-e0e6-449d-ac7f-d225cb997c12
Nov 29 20:49:26 storage1 minio[24851]: RequestID: 164BFB7173C736F8
Nov 29 20:49:26 storage1 minio[24851]: RemoteHost: xx.xx.xx.ext
Nov 29 20:49:26 storage1 minio[24851]: Host: storage1.domain.com:443
Nov 29 20:49:26 storage1 minio[24851]: UserAgent: Go-http-client/1.1
Nov 29 20:49:26 storage1 minio[24851]: Error: context deadline exceeded (context.deadlineExceededError)
Nov 29 20:49:26 storage1 minio[24851]:        2: cmd/peer-rest-client.go:642:cmd.(*peerRESTClient).GetLocalDiskIDs()
Nov 29 20:49:26 storage1 minio[24851]:        1: cmd/notification.go:1260:cmd.(*NotificationSys).GetLocalDiskIDs.func1()
Nov 29 20:49:32 storage1 minio[24851]: API: ClusterCheckHandler()
Nov 29 20:49:32 storage1 minio[24851]: Time: 20:49:32 PST 11/29/2020
Nov 29 20:49:32 storage1 minio[24851]: DeploymentID: 718f791a-e0e6-449d-ac7f-d225cb997c12
Nov 29 20:49:32 storage1 minio[24851]: RequestID: 164BFB72BB49254B
Nov 29 20:49:32 storage1 minio[24851]: RemoteHost: xx.xx.xx.ext
Nov 29 20:49:32 storage1 minio[24851]: Host: storage1.domain.com:443
Nov 29 20:49:32 storage1 minio[24851]: UserAgent: Go-http-client/1.1
Nov 29 20:49:32 storage1 minio[24851]: Error: context deadline exceeded (context.deadlineExceededError)
Nov 29 20:49:32 storage1 minio[24851]:        2: cmd/peer-rest-client.go:642:cmd.(*peerRESTClient).GetLocalDiskIDs()
Nov 29 20:49:32 storage1 minio[24851]:        1: cmd/notification.go:1260:cmd.(*NotificationSys).GetLocalDiskIDs.func1()
## Regression

No idea

## Your Environment

* Version used (`minio --version`):  RELEASE.2020-11-25T22-36-25Z
* Server setup and configuration: 8x SX292 hetzner
* Operating System and version (`uname -a`):Linux storage1 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux Debian 10.5

**Comment by harshavardhana** [comment]
You should just use the IP of the internal IPs basically like this 

```
minio server http://internal-hostnames{n....m}/disk{1...N}
```

This is just your deployment style to configure
