### ISSUE TITLE
minio server connection timed out

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#10990]
When I migrated one of the 4-node minio services to a new machine, the corresponding directories and parameters were configured, and the service failed to run normally.

## Current Behavior

![image](https://user-images.githubusercontent.com/27141040/100416915-9b26e580-30ba-11eb-8e5e-750c4642feec.png)
![image](https://user-images.githubusercontent.com/27141040/100416931-a1b55d00-30ba-11eb-93c4-e81a49b1040f.png)
![image](https://user-images.githubusercontent.com/27141040/100416941-a5e17a80-30ba-11eb-8866-6e2e361a3a71.png)
![image](https://user-images.githubusercontent.com/27141040/100416949-ae39b580-30ba-11eb-87dc-2fe002681130.png)

it shows that 88server connect time out.

## Steps to Reproduce (for bugs)

1.Deploy a minio cluster with 4 services
2.Run for a while
3.Move one of the services to new Server
4.Start up

Version used (minio --version):
minio version RELEASE.2020-07-13T18-09-56Z

Server setup and configuration:

#!/bin/bash
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin123456
export MINIO_VOLUMES="/home/minio/data/"
port=9333
nohup ./minio server --config-dir /etc/minio \
               --address ":$port" \
               http://10.10.90.86$MINIO_VOLUMES \
               http://10.10.90.88$MINIO_VOLUMES \
               http://10.10.90.53$MINIO_VOLUMES \

Operating System and version (uname -a):
Linux minio 4.4.246-1.el7.elrepo.x86_64 #1 SMP Tue Nov 24 09:26:59 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> minio version RELEASE.2020-07-13T18-09-56Z

Please test with the latest release

**Comment by klauspost** [comment]
This piece of code no longer exists, so if there is still a problem this will no longer yield the same error.

**Comment by harshavardhana** [comment]
> This piece of code no longer exists, so if there is still a problem this will no longer yield the same error.

Closing as a non issue
