### ISSUE TITLE
MinIO server with NAS became slow occasionally 

### ISSUE THREAD

**Issue by dingjs** [minio/minio#10999]
## Expected Behavior
Maintain good performance

## Current Behavior
I am using minio server with nas,but after a day or two,MinIO server became very slow.I use `fio` to test the nfs,IOPS drops a lot to only 10 to 20. When I reboot minio server,the iops would improve to a few hundreds.
This may not be a Minio bug. But the NAS compony insists that the NAS works fine. 
### Before reboot MinIO server
![image](https://user-images.githubusercontent.com/3361218/100566031-eaaa2300-32ff-11eb-857f-2e7fe1787070.png)

### After reboot MinIO server
![image](https://user-images.githubusercontent.com/3361218/100566072-057c9780-3300-11eb-9b6c-7c636bd7f3f4.png)

## Your Environment
OS: Linux release 7.5.1804
![image](https://user-images.githubusercontent.com/3361218/100566298-a3706200-3300-11eb-81c8-b8eb82dc40e1.png)

MinIO server: 2020-08-27

**Comment by harshavardhana** [comment]
> I am using minio server with nas,but after a day or two,MinIO server became very slow.I use `fio` to test the nfs,IOPS drops a lot to only 10 to 20. When I reboot minio server,the iops would improve to a few hundreds.
> This may not be a Minio bug. But the NAS compony insists that the NAS works fine.

NAS slowing down is their problem @dingjs as can be seen by the fio ops - there may be caching going on on the NAS which might slow it down. Here are the things to try

- Stop MinIO and run fio - does the `fio` ops remain the same? 
- Does mounting and remounting of NFS change the fio ops?

**Comment by dingjs** [comment]
> > I am using minio server with nas,but after a day or two,MinIO server became very slow.I use `fio` to test the nfs,IOPS drops a lot to only 10 to 20. When I reboot minio server,the iops would improve to a few hundreds.
> > This may not be a Minio bug. But the NAS compony insists that the NAS works fine.
> 
> NAS slowing down is their problem @dingjs as can be seen by the fio ops - there may be caching going on on the NAS which might slow it down. Here are the things to try
> 
> * Stop MinIO and run fio - does the `fio` ops remain the same?
> * Does mounting and remounting of NFS change the fio ops?

The odd thing is when I stop MinIO and run fio,the iops would improve a lot. It may be a coincidence.

**Comment by harshavardhana** [comment]
> The odd thing is when I stop MinIO and run fio,the iops would improve a lot. It may be a coincidence.

You shouldn't be running fio when applications are still using the mount. MinIO is going to use the NAS and NAS will be accessed accordingly there is nothing we can do if NAS slows down. 

It may slow down for many reasons to investigate this properly you have to do the tests that I asked you.

**Comment by dingjs** [comment]
> > The odd thing is when I stop MinIO and run fio,the iops would improve a lot. It may be a coincidence.
> 
> You shouldn't be running fio when applications are still using the mount. MinIO is going to use the NAS and NAS will be accessed accordingly there is nothing we can do if NAS slows down.
> 
> It may slow down for many reasons to investigate this properly you have to do the tests that I asked you.

OK,thanks!

**Comment by harshavardhana** [comment]
Closing this issue for now.
