### ISSUE TITLE
mc ERROR Unable to update the server. Server not initialized, please try again.

### ISSUE THREAD

**Issue by LiginGeorge** [minio/minio#10997]
Unable to startup the minio and it's showing offline status though the process is online.

**Describe the solution you'd like**
wlpadmin@minio2 ~]$ ./mc admin update minio2
mc: <ERROR> Unable to update the server. Server not initialized, please try again.
[wlpadmin@minio2 ~]$ ps -eaf | grep -i minio
avahi      1055      1  0 Nov23 ?        00:00:03 avahi-daemon: running [minio2.local]
wlpadmin 135230 131731  2 15:51 pts/0    00:01:04 ./minio server --address :9001 http://minio1/minio http://minio2/minio http://minio3/minio http://minio4/minio
wlpadmin 148286 131731  0 16:36 pts/0    00:00:00 grep --color=auto -i minio

**Describe alternatives you've considered**
[wlpadmin@minio2 ~]$ cat minio.out
nohup: ignoring input

API: SYSTEM()
Time: 15:51:35 +04 11/29/2020
DeploymentID: 811b3db3-99fe-4d8b-a663-ca1972beaaf9
Error: msgp: wanted array of size 17; got 13 at Versions/0 (msgp.ArrayError)
       1: cmd/storage-rest-client.go:470:cmd.(*storageRESTClient).WalkVersions.func1()

API: SYSTEM()
Time: 15:51:35 +04 11/29/2020
DeploymentID: 811b3db3-99fe-4d8b-a663-ca1972beaaf9
Error: Disk: http://minio1:9001/minio returned Expected 'storage' API version 'v20', instead found 'v22', please upgrade the servers (*fmt.wrapError)
       endpoint=http://minio1:9001/minio
       2: cmd/prepare-storage.go:52:cmd.glob..func6.1()
       1: cmd/erasure-sets.go:211:cmd.(*erasureSets).connectDisks.func1()

API: SYSTEM()
Time: 15:51:35 +04 11/29/2020
DeploymentID: 811b3db3-99fe-4d8b-a663-ca1972beaaf9
Error: Disk: http://minio3:9001/minio returned Expected 'storage' API version 'v20', instead found 'v22', please upgrade the servers (*fmt.wrapError)
       endpoint=http://minio3:9001/minio
       2: cmd/prepare-storage.go:52:cmd.glob..func6.1()
       1: cmd/erasure-sets.go:211:cmd.(*erasureSets).connectDisks.func1()
[wlpadmin@minio2 ~]$
**Additional context**
[wlpadmin@minio1 ~]$ ./mc admin --debug info minio1
mc: <DEBUG> GET /minio/admin/v3/info HTTP/1.1
Host: 10.12.207.74:9001
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-11-25T23:04:07Z
Authorization: AWS4-HMAC-SHA256 Credential=nqdtestminio/20201129//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201129T123814Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1676
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Sun, 29 Nov 2020 12:38:16 GMT
Server: MinIO/RELEASE.2020-09-26T03-44-56Z
Vary: Origin
X-Amz-Request-Id: 164BFAD7279BF64E
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  2.183872787s

●  minio2:9001
   Uptime: offline
   Drives: 0/1 OK

●  minio3:9001
   Uptime: 4 weeks
   Version: 2020-10-18T21:54:12Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio4:9001
   Uptime: 3 days
   Version: 2020-11-10T21:02:24Z
   Network: 3/4 OK
   Drives: 0/1 OK

●  minio1:9001
   Uptime: 4 weeks
   Version: 2020-09-26T03:44:56Z
   Network: 4/4 OK
   Drives: 1/1 OK

**Comment by harshavardhana** [comment]
> ● minio3:9001
> Uptime: 4 weeks
> Version: 2020-10-18T21:54:12Z
> Network: 4/4 OK
> Drives: 1/1 OK
> 
> ● minio4:9001
> Uptime: 3 days
> Version: 2020-11-10T21:02:24Z
> Network: 3/4 OK
> Drives: 0/1 OK
> 
> ● minio1:9001
> Uptime: 4 weeks
> Version: 2020-09-26T03:44:56Z
> Network: 4/4 OK
> Drives: 1/1 OK

you have been running many different versions this cannot be updated using `mc admin update` - manually copy the binaries on all servers and restart them.
