### ISSUE TITLE
S3 Select - maxCharsPerRecord of 1mb to be configurable

### ISSUE THREAD

**Issue by joshuataylor** [minio/minio#10996]
**Is your feature request related to a problem? Please describe.**
The max size for selecting records is 1mb, which is what Amazon has for S3. This should be configurable so it can be more, which obviously won't be the same as S3 but a great win for Minio.

**Describe the solution you'd like**
Have this default to 1mb, but allow the user to set a configurable limit for this.
https://github.com/minio/minio/blob/master/pkg/s3select/select.go#L427

**Describe alternatives you've considered**
None

**Additional context**
Not sure if this would be considered a breaking change if the default remains the same as S3, with this configurable to a higher limit.

**Comment by harshavardhana** [comment]
> The max size for selecting records is 1mb, which is what Amazon has for S3. This should be configurable so it can be more, which obviously won't be the same as S3 but a great win for Minio.

Well, it would be nice but unfortunately, it would break applications we are simply behaving for compliance reasons with the spec to not break existing applications with AWS S3.

> Not sure if this would be considered a breaking change if the default remains the same as S3, with this configurable to a higher limit.

Changing this can break applications in unknown ways

**Comment by klauspost** [comment]
Feel free to fork. We don't have any plans to add/support this.
