### ISSUE TITLE
NAS gateway - MinIO object metadata  folder configurable

### ISSUE THREAD

**Issue by dingjs** [minio/minio#11001]
**Is your feature request related to a problem? Please describe.**
When using NFS,its read write performance can't compare with local disk.Object meatadatas are very small files. It would be better if object meatadata's folder is configurable

**Describe the solution you'd like**
Object meatadata's folder  configurable

**Comment by harshavardhana** [comment]
> Object meatadata's folder configurable

No it is not possible @dingjs the fact is that we need them on the same namespace for filesystem locking and concurrency semantics.
