### ISSUE TITLE
Azure gateway mode is broken on v2020-11-19T23:48:16Z

### ISSUE THREAD

**Issue by ig-sinicyn** [minio/minio#11007]
Steps to reproduce
1. Get connection string for existing azure storage (for example, mystorage/my_key).
2. Download current mino release from https://dl.min.io/server/minio/release/windows-amd64/minio.exe
3. In command line, powershell:
```ps
$env:MINIO_ACCESS_KEY="mystorage" 
$env:MINIO_SECRET_KEY="my_key"
 .\minio.exe gateway azure --address :9008
```
4. open in browser http://localhost:9008
5. Use credentials from above to login, attempt to make a bucket
-or- (C# minio client)
4, 5:
```
	client = new MinioClient(
		options.Endpoint, options.AccessKey,
		options.SecretKey, options.SessionToken);
	if (!await client.BucketExistsAsync(BucketName))
		await client.MakeBucketAsync(BucketName);
```
6. Bucket creation fails, minio server output:
```
API: WebListBuckets()
Time: 15:51:41 MSK 12/01/2020
DeploymentID: c149d95a-7aea-4d13-a6bf-33508eb715c0
RemoteHost: 127.0.0.1
Host: localhost:9008
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
Error: Get "https://mystorage.blob.core.windows.net?comp=list&timeout=1501": x509: certificate signed by unknown authority (*url.Error)
       5: cmd\api-errors.go:1995:cmd.toAPIErrorCode()
       4: cmd\api-errors.go:2020:cmd.toAPIError()
       3: cmd\web-handlers.go:2279:cmd.toWebAPIError()
       2: cmd\web-handlers.go:2147:cmd.toJSONError()
       1: cmd\web-handlers.go:359:cmd.(*webAPIHandlers).ListBuckets()

```
-or-
```
API: GetBucketLocation(bucket=my-bucket
Time: 15:39:36 MSK 12/01/2020
DeploymentID: 4a3ec9a7-473e-4a14-bc2e-7685e7ab693c
RequestID: 164C980701F7152C
RemoteHost: 127.0.0.1
Host: localhost:9008
UserAgent: MinIO (Microsoft Windows 10.0.19041;X64) minio-dotnet/1.0.9
Error: Get "https://mystorage.blob.core.windows.net?comp=list&prefix=my-bucket&timeout=1501": x509: certificate signed by unknown authority (*url.Error)
       4: cmd\api-errors.go:1995:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:2020:cmd.toAPIError()
       2: cmd\bucket-handlers.go:179:cmd.objectAPIHandlers.GetBucketLocationHandler()
       1: net\http\server.go:2042:http.HandlerFunc.ServeHTTP()
```

minio version:
```
VERSION
2020-11-19T23:48:16Z
PLATFORM
Host: IgorPC | OS: windows | Arch: amd64
RUNTIME
Version: go1.15.5 | CPUs: 12
```

**Comment by ig-sinicyn** [comment]
UPD. Just in case. I've checked latest minio version on another machine (entirely different network/ISP), same issue.

**Comment by vadmeste** [comment]
```
Error: Get "https://mystorage.blob.core.windows.net?comp=list&timeout=1501": x509: certificate signed by unknown authority (*url.Error)
```

I think users see this with old Windows machines, what's your version ?

**Comment by ig-sinicyn** [comment]
Microsoft Windows NT 10.0.19041.0 (May 2020), all updates installed

**Comment by harshavardhana** [comment]
> ```
> Error: Get "https://mystorage.blob.core.windows.net?comp=list&timeout=1501": x509: certificate signed by unknown authority (*url.Error)
> ```
> 
> I think users see this with old Windows machines, what's your version ?

Just get the certs from your blob account and trust it in your registry.

Try accessing curl https locally on the box and see if that works ?

**Comment by ig-sinicyn** [comment]
> Get "https://mystorage.blob.core.windows.net?comp=list&timeout=1501"
> Try accessing curl https locally on the box and see if that works 

Just checked, works fine. It responds 404,
```
<Error>
  <Code>ResourceNotFound</Code>
  <Message>The specified resource does not exist. RequestId:06ab8425-301e-0065-3d79-c8769e000000 Time:2020-12-02T07:04:03.6430995Z</Message>
</Error>
```
Also, we use az storage client a lot so I think the issue is not on azure side.

**Comment by harshavardhana** [comment]
> Also, we use az storage client a lot so I think the issue is not on azure side.

yes this looks like the system cert pool is broken

**Comment by harshavardhana** [comment]
Looks like a regression introduced in Go @ig-sinicyn 

https://github.com/golang/go/commit/05471e9ee64a300bd2dcc4582ee1043c055893bb

**Comment by harshavardhana** [comment]
Please test this binary @ig-sinicyn 

```
~ mc cp -a play/testbucket/minio.exe .
```

**Comment by ig-sinicyn** [comment]
> Please test this binary @ig-sinicyn

Works without issues:)
