### ISSUE TITLE
about minio Active-Active Bucket Replication

### ISSUE THREAD

**Issue by Danbuth** [minio/minio#11000]
**Is your feature request related to a problem? Please describe.**
I want a minio server replicate to another minio server. And refer to [https://blog.min.io/active-active-replication](https://blog.min.io/active-active-replication)
But now I have three questions.

1. `mc version enable` error
`mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.`
![image](https://user-images.githubusercontent.com/22046432/100586600-5c976200-332a-11eb-9763-76d88029372e.png)

2. about Active-Active Bucket Replication,  it  could replicated already existed bucket. can't replicate all bucket, and future create bucket. It can be?

3. I need deploy minio on two servers, and use distributed MinIO to deploy. but if any one server down, the minio just can read, don't write.because two servers, the cluster It must be a multiple of two，like 2,4,6... Is there any way to deploy minio on two servers, if any one down, the minio can also wirte.

**Comment by harshavardhana** [comment]
> 1. `mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.`

You need MinIO erasure coded setup 

> * about Active-Active Bucket Replication,  it  could replicated already existed bucket. can't replicate all bucket, and future create bucket. It can be?
> *

No it cannot be @Danbuth 

> 3\. I need deploy minio on two servers, and use distributed MinIO to deploy. but if any one server down, the minio just can read, don't write.because two servers, the cluster It must be a multiple of two，like 2,4,6... Is there any way to deploy minio on two servers, if any one down, the minio can also wirte.

https://github.com/minio/minio/blob/master/docs/distributed/SIZING.md look at the different sizing
