### ISSUE TITLE
Object shared expires 7days

### ISSUE THREAD

**Issue by dingding7199** [minio/minio#11011]
**Is your feature request related to a problem? Please describe.**
When i shared my document . Object shared expires 7days notice. 

**Describe the solution you'd like**
I want shared object longtime such as 365days.

**Describe alternatives you've considered**
Such as use config is batter than hard code.

**Additional context**
![image](https://user-images.githubusercontent.com/13215312/100816477-14d71e80-3481-11eb-8945-75481d7f904b.png)
![image](https://user-images.githubusercontent.com/13215312/100816312-c88bde80-3480-11eb-9988-070ee60406e8.png)
![image](https://user-images.githubusercontent.com/13215312/100816354-db061800-3480-11eb-84a7-c2cfbc776d16.png)
![image](https://user-images.githubusercontent.com/13215312/100816381-eb1df780-3480-11eb-90a6-c762e83d84c7.png)

**Comment by harshavardhana** [comment]
AWS S3 mandates presigned URLs expire in 7 days max we simply follow the SPEC.

**Comment by harshavardhana** [comment]
if you want full anonymous access use `mc policy set public myminio/mybucket` to make your entire bucket publicly readable and writable.

**Comment by dingding7199** [comment]
Tks @hackintoshrao .

**Comment by dingding7199** [comment]
update expires time 365 days @harshavardhana 
![image](https://user-images.githubusercontent.com/13215312/101333064-1ce3f380-38b1-11eb-8893-cd67487fab50.png)
