### ISSUE TITLE
How do I upload file in the browser env?

### ISSUE THREAD

**Issue by Sayid1** [minio/minio#11021]
I couldn't get the ReadableStream|Buffer object I needed for uploading in a browser environment

putObject type definition is as follows：
```typescript
putObject(bucketName: string, objectName: string, stream: ReadableStream|Buffer|string, callback: ResultCallback<string>): void;
```

Thanks very much! :)

**Comment by Sayid1** [comment]
Or can I only upload files in the Node environment?

**Comment by nitisht** [comment]
Closing this due to incomplete info. Please create issue using the issue template, otherwise it is not possible for us to help you
