### ISSUE TITLE
admin users can't create new users

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#11037]
I have an admin user defined as follow:

mc admin user info clusters3 admin-user
```
AccessKey: admin-user
Status: enabled
PolicyName: admin-policy
MemberOf:
```

mc admin policy info clusters3 admin-policy
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "admin:*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:*"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
```

mc admin user add clusters3 testuser 1234567890987654321
`mc: <ERROR> Unable to add new user. Access Denied.`

I think this is a regression problem related to the PR:

https://github.com/minio/minio/pull/11005

$ minio -version
`minio version RELEASE.2020-12-03T05-49-24Z`

$ cat /etc/centos-release
`CentOS Linux release 8.2.2004 (Core)`

**Comment by harshavardhana** [comment]
@fdefilippo will check

**Comment by harshavardhana** [comment]
Found the problem sending a fix.!
