### ISSUE TITLE
notify_mysql: invalid index length on MySQL 5.7: Specified key was too long

### ISSUE THREAD

**Issue by vaddenz** [minio/minio#11031]
Use MySQL as event sink with format `namespace`, failed to create target cause MySQL reports this error: 

```
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes [1762d20ec16e][1071]
```

Minio version: RELEASE 2020-12 (latest)
MySQL version: 5.7.18

## Expected Behavior
Successfully add mysql as event sink.

## Current Behavior
Action failed.

## Possible Solution

Update the create table statement [here](https://github.com/minio/minio/blob/b880796aef3394ecf00e43fdfcaff5145eb348b5/pkg/event/target/mysql.go#L76), modify the `key_name` field length to a suitable value.

## Steps to Reproduce (for bugs)

1. Start a MySQL server with version 5.7 and the latest version minio server
2. Run `mc admin config set <minio> notify_mysql:<name> table=<tabe> dsn_string=<dsn>`

**Comment by donatello** [comment]
Will check this week.
