### ISSUE TITLE
Unable to delete bucket

### ISSUE THREAD

**Issue by mymasse** [minio/minio#11054]
## Expected Behavior

Run `mc rb --force --dangerous <BUCKET>` and bucket gets deleted

## Current Behavior

Command fails after around 30 minutes with the following:
```
mc <ERROR> Failed to remove <BUCKET> . The bucket you tried to delete is not empty.
```

## Possible Solution

No idea!

## Steps to Reproduce (for bugs)

1. Create a bucket
2. Load about 5TB of data
3. Delete the bucket

## Context

We have this bucket which is not required anymore in one of our cluster and we want to delete since we only have 9% free space on the 3TB drives.

We also tried to run `mc rm --force --recursive <BUCKET>` which returned with no error, but bucket data is still there.

## Your Environment

* Version used (`minio --version`): `2020-01-25T02:50:51Z`
* CLI Version used: `2020-01-13T22-49-03Z`
* Server setup and configuration: BOSH deployed on 4 nodes each with 3TB drive
* Operating System and version (`uname -a`): Ubuntu Xenial Bosh stemcell

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): `2020-01-25T02:50:51Z`
> * CLI Version used: `2020-01-13T22-49-03Z`

Please upgrade to latest releases and let us know @mymasse

**Comment by mymasse** [comment]
So we can't easily upgrade that cluster now with our work from home posture. Is this something that as been reported before? Anything we can try without upgrading?

**Comment by harshavardhana** [comment]
> So we can't easily upgrade that cluster now with our work from home posture. Is this something that as been reported before? Anything we can try without upgrading?

The MinIO version is almost a year old, we have fixed and changed quite a lot of things since then. You may try doing `mc admin heal -r` on the bucket and try deleting it again.

**Comment by klauspost** [comment]
If the issue persists on the latest release, feel free to open an issue.
