### ISSUE TITLE
minio分布式运行在win系统下没有示例

### ISSUE THREAD

**Issue by gulanglei** [minio/minio#11059]
minio在win系统上分布式部署失败，就在昨天2020-12-08官网还给出win示例操作，在示例2中。目前(2020-12-09)在官网找不到示例2了，也就是找不到win系统下分布式启动部署的示例了。
目前官网只有GNU/Linux 和 macOS系统的分布式示例。还请麻烦提供下win系统下的分布式示例。

**Comment by harshavardhana** [comment]
We do not understand chinese language, please open issues in english.
