### ISSUE TITLE
Linux system starts minio distributed error report

### ISSUE THREAD

**Issue by gulanglei** [minio/minio#11064]
API: SYSTEM()
Time: 21:32:20 CST 12/09/2020
DeploymentID: b3e2d697-0bc5-4724-b39c-3f5431ec9ef3
Error: Unable to migrate IAM users and policies to new format: sio: data is not authentic (*fmt.wrapError)
       1: cmd/iam.go:508:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 21:32:20 CST 12/09/2020
DeploymentID: b3e2d697-0bc5-4724-b39c-3f5431ec9ef3
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:509:cmd.(*IAMSys).Init()

**Comment by klauspost** [comment]
@gulanglei Please fill out the provided form with information. https://raw.githubusercontent.com/minio/minio/master/.github/ISSUE_TEMPLATE/bug_report.md

Without that information we cannot help you.

**Comment by harshavardhana** [comment]
> @gulanglei Please fill out the provided form with information. https://raw.githubusercontent.com/minio/minio/master/.github/ISSUE_TEMPLATE/bug_report.md
> 
> Without that information we cannot help you.

Perhaps it's best to close such issues as well.
