### ISSUE TITLE
There is no example of minio distributed running under win system

### ISSUE THREAD

**Issue by gulanglei** [minio/minio#11061]
The distributed deployment of minio on the win system failed. Just yesterday, the official website of 2020-12-08 also gave a win example operation, in example 2. Currently (2020-12-09) I can't find example 2 on the official website, that is, I can't find an example of distributed startup deployment under the win system.
Currently the official website only has distributed examples of GNU/Linux and macOS systems. Please also provide a distributed example under the win system.

**Comment by harshavardhana** [comment]
As explained in the previous issue https://github.com/minio/minio/issues/11060#issuecomment-741576595
