### ISSUE TITLE
[working as intended] There is no example of minio distributed running under win system

### ISSUE THREAD

**Issue by gulanglei** [minio/minio#11060]
The distributed deployment of minio on the win system failed. Just yesterday, the official website of 2020-12-08 also gave a win example operation, in example 2. Currently (2020-12-09) I can't find example 2 on the official website, that is, I can't find an example of distributed startup deployment under the win system.
Currently the official website only has distributed examples of GNU/Linux and macOS systems. Please also provide a distributed example under the win system.

**Comment by harshavardhana** [comment]
> The distributed deployment of minio on the win system failed. Just yesterday, the official website of 2020-12-08 also gave a win example operation, in example 2. Currently (2020-12-09) I can't find example 2 on the official website, that is, I can't find an example of distributed startup deployment under the win system.
> Currently the official website only has distributed examples of GNU/Linux and macOS systems. Please also provide a distributed example under the win system.

Windows support for distributed setup is experimental, building scalable systems on Windows systems is not recommended.  GNU/Linux is the recommended choice here. 

macOS is meant for local development work.

**Comment by gulanglei** [comment]
When can I support Windows? What is the current version of minio?

**Comment by harshavardhana** [comment]
> When can I support Windows? What is the current version of minio?

Already supported but it's experimental not recommended for production use under distributed setup @gulanglei - for production systems in distributed setup please use GNU/Linux.

**Comment by gulanglei** [comment]
The official website did not see the distributed support for the win system. Okay, let me check and accept distributed under Linux system.

**Comment by gulanglei** [comment]
> > 我什么时候可以支持Windows？minio的当前版本是什么？
> 
> 已经支持，但不建议在分布式安装程序@gulanglei下将其用于生产实验-对于分布式安装的生产系统，请使用GNU / Linux。

The official website did not see the distributed support for the win system. Okay, let me check and accept distributed under Linux system.

**Comment by harshavardhana** [comment]
> > > 我什么时候可以支持Windows？minio的当前版本是什么？
> > 
> > 
> > 已经支持，但不建议在分布式安装程序@gulanglei下将其用于生产实验-对于分布式安装的生产系统，请使用GNU / Linux。
> 
> The official website did not see the distributed support for the win system. Okay, let me check and accept distributed under Linux system.

It is not because its experimental, we want to encourage what is common in practice and scalable.

**Comment by gulanglei** [comment]
> > > > 我什么时候可以支持Windows？minio的当前版本是什么？
> > > 
> > > 
> > > 已经支持，但不建议在分布式安装程序@gulanglei下将其用于生产实验-对于分布式安装的生产系统，请使用GNU / Linux。
> > 
> > 
> > 官方网站没有看到对win系统的分布式支持。好的，让我检查并接受Linux系统下的分布式。
> 
> 不是因为它是实验性的，我们要鼓励实践中常见的和可扩展的。

Understand, then I should build a minio distributed cluster under linux system
