### ISSUE TITLE
[faq] Minio server in standalone mode on docker for windows doesn't start with Docker volume mount

### ISSUE THREAD

**Issue by mail2hjain** [minio/minio#11077]
## Expected Behavior

Minio server in standalone mode on docker for windows should work with docker volume mount in order to support persistence across container restarts.

## Current Behavior

Hangs on start. no errors (any log line for that matter) on console. Bowser UI indicates server is not initialized.

## Steps to Reproduce (for bugs)

1. Have docker EE setup on Windows server 2019.
2. Use the DockerFile for Minio as below:
```
FROM mcr.microsoft.com/windows/nanoserver:1809 as build

WORKDIR /MinIO
ADD https://dl.min.io/server/minio/release/windows-amd64/minio.exe .

ENV MINIO_ACCESS_KEY="xyz"
ENV MINIO_SECRET_KEY="blahblah"

ENTRYPOINT ["minio", "server",  "--address", ":9001", "/Data"]
```
3. Spawn the container using below command:
`docker run --mount source=minio-data,target=c:\Data minio`

4. container starts, but not the minio server. No log lines on console. Browser UI indicates server not initialized.

## Context

We are evaluating minio as Object Store for 'on-premise' deployment of our application. We are stuck with windows due to various other reasons. Persistence is obviously required however a redundancy is not.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-12-03T05-49-24Z
* Server setup and configuration: server in standalone mode with all default configurations
* Operating System and version (`uname -a`): Windows server 2019 Version - 1809

**Comment by harshavardhana** [comment]
@mail2hjain MinIO standalone mode requires posix locks / fcntl locking / Win32 locking - support on the mount

Most probably the volume mounts with docker on windows do not support this and are poor in their Win32 API compatibility.

Just run our windows binary natively it will work fine.

**Comment by mail2hjain** [comment]
@harshavardhana  Thanks for the update. 
Does this limitation (of requiring locking support on mount) not exist in 'Erasure Code' mode? 
Same setup worked fine when running the server with redundancy as ```minio server /Data{1...4}``` This however meant 2X disk space consumption (as I understood from [here](https://github.com/minio/minio/tree/master/docs/erasure/storage-class#storage-usage)).

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for the update.
> Does this limitation (of requiring locking support on mount) not exist in 'Erasure Code' mode?
> Same setup worked fine when running the server with redundancy as `minio server /Data{1...4}` This however meant 2X disk space consumption (as I understood from [here](https://github.com/minio/minio/tree/master/docs/erasure/storage-class#storage-usage)).

Yes it doesn't exist.
