### ISSUE TITLE
4 nodes, 4 disks per node, how to start minio in erasure code mode?

### ISSUE THREAD

**Issue by gulanglei** [minio/minio#11074]
4 nodes, 4 disks per node, how to start minio in erasure code mode?

**Comment by kannappanr** [comment]
you have to run 

minio server http://pc{1...4}/mnt/disk{1...4}

where pc1, pc2, pc3 and pc4 are names of the 4 nodes and `/mnt/disk1` through `/mnt/disk4` are the disks on all of the nodes.

PTAL https://docs.minio.io/docs/distributed-minio-quickstart-guide.html

Closing this issue. Please reach out to us at https://slack.min.io for such questions. Also, https://docs.min.io would be a great place for these sorts of questions.

**Comment by gitlawr** [comment]
@kannappanr Any instruction about how to join the minio slack community?
Seems like a minio.io email is required.
![image](https://user-images.githubusercontent.com/5697937/103845884-f398cc00-50d7-11eb-8a4b-fe20ea2457aa.png)

**Comment by harshavardhana** [comment]
Just join here https://slack.min.io
