### ISSUE TITLE
Problem with metrics: count(count by (bucket) (bucket_objects_count))

### ISSUE THREAD

**Issue by olegsidokhmetov** [minio/minio#11079]
**Is your feature request related to a problem? Please describe.**
I have some problem with metrics.
Now I have only 5 buckets
![2020-12-10_17-47-30](https://user-images.githubusercontent.com/51410180/101803873-48fdaf80-3b11-11eb-811f-65751f80a512.png)

But in Grafana I see in dashboard 7 buckets.
![2020-12-10_17-46-52](https://user-images.githubusercontent.com/51410180/101803831-3d11ed80-3b11-11eb-8049-94402f8c9768.png)

Command from server
```
root@MinIO:/usr/local/share/minio# mc ls minio
[2020-12-10 16:21:28 UTC]     0B 007/
[2020-12-10 12:27:17 UTC]     0B client000/
[2020-12-04 12:32:09 UTC]     0B photos/
[2020-12-04 11:50:47 UTC]     0B quersystem/
[2020-12-10 12:14:44 UTC]     0B rar/
```
**Describe the solution you'd like**
To see correct amount of buckets. How it can do?

**Describe alternatives you've considered**
I did not have idea.

**Additional context**

**Comment by harshavardhana** [comment]
> I have some problem with metrics.
> Now I have only 5 buckets

This value is updated slowly, it's not atomic @olegsidokhmetov - correct buckets would get updated after crawler updated.

**Comment by klauspost** [comment]
No feedback, so assuming there is nothing unexpected going on here. Closing.
