### ISSUE TITLE
minio.error.EntityTooSmall: EntityTooSmall: message: Your proposed upload is smaller than the minimum allowed object size.

### ISSUE THREAD

**Issue by ManivannanMurugavel** [minio/minio#11076]
Hi,

I trying to change the MIN_PART_SIZE is 2MiB, But i am getting the error is **"minio.error.EntityTooSmall: EntityTooSmall: message: Your proposed upload is smaller than the minimum allowed object size"**. 

The default value is 5MiB..

May be it is minio server oriented problem, 
Let me know, how can i solve the problem?

**Comment by vadmeste** [comment]
@ManivannanMurugavel MinIO server follows S3 spec, we cannot really change this behavior.

**Comment by Albadrany99** [comment]
- - [ ]
