### ISSUE TITLE
Linux system starts minio distributed cluster error?

### ISSUE THREAD

**Issue by gulanglei** [minio/minio#11072]
API: SYSTEM()
Time: 21:32:20 CST 12/09/2020
DeploymentID: b3e2d697-0bc5-4724-b39c-3f5431ec9ef3
Error: Unable to migrate IAM users and policies to new format: sio: data is not authentic (*fmt.wrapError)
       1: cmd/iam.go:508:cmd.(*IAMSys).Init()

**Comment by harshavardhana** [comment]
> Error: Unable to migrate IAM users and policies to new format: sio: data is not authentic (*fmt.wrapError)

If you change credentials you need to make sure to rotate them or provide older credentials https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials 

Also please provide proper issue reporting using template.
