### ISSUE TITLE
[faq] Minio replication don't replicate all objects in bucket

### ISSUE THREAD

**Issue by cubbasa** [minio/minio#11071]
I've setup Minio with replication between clusters to replicate all objects in bucket. 
Objects if they are copied to source bucket using Minio client are properly replicate to destination cluster and metadata  X-Amz-Replication-Status is set correctly on these objects.
I use Minio as object storage for Loki (https://grafana.com/oss/loki/) which using api directly  to put objects in source bucket. Objects put by Loki are not seen by replication at all and they are omitted by replication also they are missing metadata X-Amz-Replication-Status too. Objects are properly stored in Minio source cluster and have other metadata set properly. I've got lifecycle rule set on this bucket which is working correctly and set proper metadata with expiration on all objects and expire them later on.

## Expected Behavior

Replication should replicate all objects according to configuration which is set to do so.

## Current Behavior

Replication partially replicate some of objects which are copied by mc client and not if they are put by api directly.

## Steps to Reproduce (for bugs)

1. Setup Loki configuration (chart version 2.0.2, Loki version 2.0.0) with Minio as object storage (https://grafana.com/docs/loki/latest/configuration/examples/#s3-compatible-apis)
2. Setup Minio replication (https://docs.min.io/docs/minio-bucket-replication-guide.html)
- replication replicate everything (I don't use any tags or prefixes in configuration)
- name of bucket is the same on source and destination cluster

## Your Environment

* Version used (`minio --version`):
RELEASE.2020-12-03T05-49-24Z
* Server setup and configuration:
Default configuration with 4 replicas
* Operating System and version (`uname -a`):
Kubernets: (v1.15.7)
Chart version: 8.0.7

**Comment by poornas** [comment]
does the accesskey for MinIO configured in Loki have permissions to get replication configuration - it should have `s3:GetReplicationConfiguration`  permission for the bucket in question.

**Comment by cubbasa** [comment]
@poornas for simplicity I've used admin credentials for replication configuration (bucket remote user for destination and for replication configuration on source) to be sure that is not related to some permission issues.

**Comment by poornas** [comment]
On source cluster, can you do a trace `mc admin trace -v sourcealias` and paste incoming request/response from loki api call? Also would like to see the output of `mc admin info sourcealias` and replication config - if there are no objectprefix/tag specific filters in the replication config and/or permission issues - it should replicate

**Comment by cubbasa** [comment]
@poornas Your comments helped me to get answer where there was a problem. 
After I've read them again I've found that I've got proper permissions only of 2 of 3 places that should be (I thought that I've used everywhere admin privileges but after check it wasn't the case).
Now after I've added one missing permission everything works as expected thank You very much.
