### ISSUE TITLE
After last upgrade memory fault

### ISSUE THREAD

**Issue by titansmc** [minio/minio#11088]
```



dic 11 22:14:56 ops-object02.domain.de minio[39576]: panic: runtime error: invalid memory address or nil pointer dereference
dic 11 22:14:56 ops-object02.domain.de minio[39576]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1613fc3]
dic 11 22:14:56 ops-object02.domain.de minio[39576]: goroutine 287823 [running]:
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage(0x10, 0xc00898fb20, 0xc00898fb40, 0xc00898fb60, 0xc00898f8e0, 0xc00898f900, 0xc008996a20, 0x214cde0, 0xc01e843a80, 0xc005dfaa80, ...)
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure.go:256 +0x143
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd.(*erasureServerPools).CrawlAndGetDataUsage.func1(0xc01e8376a0, 0xc01e837698, 0xc01ec0b1e0, 0xc01e839e50, 0xc005dfaa80, 0x24, 0x43, 0xc0012206d0, 0xc01e839e70, 0xc01e839e60, ...)
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure-server-sets.go:352 +0x1a5
dic 11 22:14:56 ops-object02.domain.de minio[39576]: created by github.com/minio/minio/cmd.(*erasureServerPools).CrawlAndGetDataUsage
dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure-server-sets.go:339 +0x2a7
dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Unit minio.service entered failed state.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service failed.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service holdoff time over, scheduling restart.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Stopped MinIO.
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Starting MinIO...
dic 11 22:14:56 ops-object02.domain.de systemd[1]: Started MinIO.

```

## Expected Behavior
working as usual 

## Current Behavior
after upgrading it, there is one node restarting constantly

## Steps to Reproduce (for bugs)

1. Upgrade to RELEASE.2020-12-10T01-54-29Z

## Regression
Yes

## Your Environment

* Version used (`minio --version`): RELEASE.2020-12-10T01-54-29Z
* Server setup and configuration: CentOS 7, systemd, 2 nodes cluster with 96 disks each
* Operating System and version (`uname -a`): 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: panic: runtime error: invalid memory address or nil pointer dereference
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1613fc3]
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: goroutine 287823 [running]:
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage(0x10, 0xc00898fb20, 0xc00898fb40, 0xc00898fb60, 0xc00898f8e0, 0xc00898f900, 0xc008996a20, 0x214cde0, 0xc01e843a80, 0xc005dfaa80, ...)
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure.go:256 +0x143
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd.(*erasureServerPools).CrawlAndGetDataUsage.func1(0xc01e8376a0, 0xc01e837698, 0xc01ec0b1e0, 0xc01e839e50, 0xc005dfaa80, 0x24, 0x43, 0xc0012206d0, 0xc01e839e70, 0xc01e839e60, ...)
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure-server-sets.go:352 +0x1a5
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: created by github.com/minio/minio/cmd.(*erasureServerPools).CrawlAndGetDataUsage
> dic 11 22:14:56 ops-object02.domain.de minio[39576]: github.com/minio/minio/cmd/erasure-server-sets.go:339 +0x2a7
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: Unit minio.service entered failed state.
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service failed.
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: minio.service holdoff time over, scheduling restart.
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: Stopped MinIO.
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: Starting MinIO...
> dic 11 22:14:56 ops-object02.domain.de systemd[1]: Started MinIO.

@titansmc please share entire trace

**Comment by harshavardhana** [comment]
are you sure all minio servers are running the same version?

**Comment by titansmc** [comment]
```
[root@ops-object02 ~]# minio --version
minio version RELEASE.2020-12-10T01-54-29Z
```
other server:
```
[root@ops-object01 ~]# minio --version
minio version RELEASE.2020-12-10T01-54-29Z
```
This is the trace ran from un node, but the same for the other, it hangs:
```
[root@ops-object01 ~]# mc admin trace --debug embl1
mc: <DEBUG> GET /minio/admin/v3/trace?all=false&err=false HTTP/1.1
Host: ops-object01.embl.de
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=2fVsfSGJV54FNDNN7EXAMsaffPLE/20201211//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201211T212758Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Security-Policy: block-all-mixed-content
Content-Type: text/event-stream
Date: Fri, 11 Dec 2020 21:27:59 GMT
Vary: Origin
X-Accel-Buffering: no
X-Amz-Request-Id: 164FC6B67470051E
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  530.764947ms

^Cmc: <ERROR> Unable to listen to http trace: context canceled
 (0) admin-trace.go:129 cmd.mainAdminTrace(..)
 Release-Tag:RELEASE.2020-10-03T02-54-56Z | Commit:f11ae85566fe | Host:ops-object01.embl.de | OS:linux | Arch:amd64 | Lang:go1.14.9 | Mem:4.1 MB/73 MB | Heap:4.1 MB/66 MB.
[root@ops-object01 ~]# 
```

**Comment by titansmc** [comment]
```
[root@ops-object02 ~]# mc admin trace embl2
21:28:53.243 [200 OK] s3.ListBuckets s3.domain.de/ 10.11.62.118      212.438ms    ↑ 93 B ↓ 3.8 KiB
21:28:59.622 [200 OK] s3.ListBuckets s3.domain.de/ 10.11.62.118      41.057ms     ↑ 155 B ↓ 3.8 KiB
21:28:59.766 [206 Partial Content] s3.GetObject s3.domain.de/git-art/fe/a0/fea0c15bfd199fdd642c9df47989df37c089cad27e83aecacedfefe369a93881/2019_08_09/28053/26016/job.log?X-Amz-Expires=600&X-Amz-Date=20201211T212900Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=git-lfs%2F20201211%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=3960025f323b2bc4f41ab8f05d1d0a3368cd44e2fa3b2bf9962ce0c7f04b079f  10.11.4.159       126.944ms    ↑ 60 B ↓ 4.7 KiB
21:29:16.954 [200 OK] s3.GetBucketLocation s3.domain.de/moscardo/?location=  10.11.62.118      2.581ms      ↑ 155 B ↓ 349 B
21:29:17.087 [200 OK] s3.HeadBucket s3.domain.de/moscardo/ 10.11.62.118      2.267ms      ↑ 93 B ↓ 189 B
21:29:17.239 [200 OK] s3.ListObjectsV2 s3.domain.de/moscardo/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=  10.11.62.118      179.378ms    ↑ 155 B ↓ 4.3 KiB

```

If I list a bucket, for example, I get this.

**Comment by harshavardhana** [comment]
Thanks looks fine @titansmc

**Comment by titansmc** [comment]
is it something in the code that you need to look at?

**Comment by harshavardhana** [comment]
@titansmc do you have one of the disks on the node that is crashing offline?

**Comment by titansmc** [comment]
Yes, this was never recovered, since we replaced it while we hit that bug ,
about 2 months ago

**Comment by titansmc** [comment]
Can  I test the fix?

**Comment by harshavardhana** [comment]
> Can I test the fix?

yes compile from source

**Comment by titansmc** [comment]
I have updated to the latest and it looks like it is not restarting the server any more, I will keep an eye.
Cheers.
