### ISSUE TITLE
Minio does not bring temporary credentials HTML page JS SDK upload?

### ISSUE THREAD

**Issue by 120011676** [minio/minio#11083]
**Is your feature request related to a problem? Please describe.**
Page JS SDK upload files, do not expose the impression information, use temporary credentials

**Describe the solution you'd like**
Get a temporary credential for JS SDK page upload

**Describe alternatives you've considered**
Using other software

**Additional context**
https://github.com/minio/minio/issues/11051#issuecomment-740409994

**Comment by harshavardhana** [comment]
MinIO supports HTLM JS upload using STS tokens - use AssumeRole API to do this https://github.com/minio/minio/blob/master/docs/sts/assume-role.md
