### ISSUE TITLE
Getting error when trying to change crawler delay

### ISSUE THREAD

**Issue by sajjadG** [minio/minio#11093]
We are getting this error when trying to increase crawler delay:

```
# mc admin config set minio-prod-distributed/ crawler delay=60.0
mc: <ERROR> Unable to set 'crawler delay=60.0' to server: sub-system 'crawler' cannot have empty keys.
```

## Environment

* Version used: RELEASE.2020-10-03T02-19-42Z
* Server setup and configuration: 3 node setup with 3x4T disk each 
* Server Hardware: cpu: 2680v2 - memory: 64GB - network: 1Gb
* Operating System and version: Debian10 (deployed with docker)

**Comment by harshavardhana** [comment]
> * Version used: RELEASE.2020-10-03T02-19-42Z

We never supported these values, please upgrade to the latest both server and `mc`
