### ISSUE TITLE
Metrics end point throws a 403 HTTP Error 

### ISSUE THREAD

**Issue by deshetti** [minio/minio#11105]
I have installed Minio using Docker, Brew & Helm. The metrics endpoint (http://localhost:9000/minio/prometheus/metrics) is throwing a 403 error in all the cases after I access the endpoint after logging in. Is there anything I need to set to enable metrics? 

## Expected Behavior
Metrics end point `/minio/prometheus/metrics` should display the metrics

## Current Behavior
Throwing a 403 error

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2020-12-12T08-39-07Z`
* Server setup and configuration: Basic installation as mentioned here for macOS: https://docs.min.io/docs/minio-quickstart-guide.html 
* Operating System and version (`uname -a`): `Darwin deshetti-macbook.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

**Comment by harshavardhana** [comment]
By default Prometheus metrics export is an authenticated endpoint and has been for quite some point now. 

https://github.com/minio/minio/tree/master/docs/metrics/prometheus#2-configure-authentication-type-for-prometheus-metrics

**Comment by deshetti** [comment]
@harshavardhana As I mentioned, the 403 error is after I logged in to Minio.

**Comment by deshetti** [comment]
@harshavardhana Here are the screenshots for both the endpoints after I login with the default Accesskey and Secretkey

<img width="1292" alt="Screen Shot 2020-12-14 at 4 13 13 PM" src="https://user-images.githubusercontent.com/10763210/102142107-7c00b580-3e27-11eb-96b1-3ce7b7cbde14.png">

<img width="1266" alt="Screen Shot 2020-12-14 at 4 13 20 PM" src="https://user-images.githubusercontent.com/10763210/102142140-858a1d80-3e27-11eb-9553-d3ee5e037834.png">

It is not very hard to validate. I would appreciate it if you can validate the issue before closing.

**Comment by harshavardhana** [comment]
> @harshavardhana As I mentioned, the 403 error is after I logged in to Minio.

There is no logged in for Prometheus check the docs on what you need to do.
