### ISSUE TITLE
Deploy distributed minio, not working.

### ISSUE THREAD

**Issue by py463360578** [minio/minio#11117]
I start the minio on two linux servers, using script : 
```
export MINIO_ACCESS_KEY=train_platform
export MINIO_SECRET_KEY=train_platform
./minio server http://train_minio{1...2}/opt/minio/data{1...4}
```
Then I put an object to http://train_minio1:9000, and there exists. 
But when I browse http://train_minio2:9000, there is no bucket or object.
Data is not sysnchronized bewteen these two servers, why ?

**Comment by harshavardhana** [comment]
@py463360578 please provide information - use the issue template and fill out all the details properly.
