### ISSUE TITLE
minio browser uploads file with name contains #, the uploaded file name is different.

### ISSUE THREAD

**Issue by rickyteng** [minio/minio#11112]
minio browser uploads file with name contains #, for example abc#123.txt
the uploaded file name is abc

## Expected Behavior

the uploaded file name should be abc#123.txt

## Current Behavior

the uploaded file name is abc

## Steps to Reproduce (for bugs)

1. prepare a txt file, name it abc#123.txt
2. upload it by minio browser

## Context

I can not upload file by browser. I can use mc to upload file.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

Version used :  RELEASE.2020-11-13T20-10-18Z
Operating System and version: Linux n14 4.9.140-tegra #1 SMP PREEMPT Thu Sep 24 16:07:04 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by vadmeste** [comment]
@rickyteng thanks for reporting this.  This looks like MinIO browser missed encoding '#' character.
