### ISSUE TITLE
running mc ls myminio fails to give byte size

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11110]
When running mc ls myminio this fails to give the byte size of the listed buckets, this is once upgraded to minio version RELEASE.2020-12-12T08-39-07Z

**## Expected Behavior**
mc ls myminio should show the byte count and bucket name. 

**## Current Behavior**
Currently this only shows a zero byte count, however it does list the buckets. 

**## Steps to Reproduce (for bugs)**
1. Upgrade to RELEASE.2020-12-12T08-39-07Z
2. run a mc ls myminio and wait for output 

**## Context**
This is an annoying bug as you cannot see the size of a bucket easily, you need to dig into other metrics. 

## Your Environment

* Version used RELEASE.2020-12-12T08-39-07Z
* Physical hardware with 128GB Ram X 6 in a single cluster. 
* Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

We cannot supply logs.

**Comment by zapto2600** [comment]
Missing the mc ls myminio -r

**Comment by vadmeste** [comment]
@zapto2600 `mc ls alias/` can never show the size of the bucket. You need `mc du` for that.

Closing this unless you show us how to get the bucket size with any mc version.

**Comment by zapto2600** [comment]
You can use mc ls alias -r
