### ISSUE TITLE
Deploy distributed minio cluster, but not working.

### ISSUE THREAD

**Issue by py463360578** [minio/minio#11118]
I start the minio on two linux servers, using script :
```
export MINIO_ACCESS_KEY=train_platform
export MINIO_SECRET_KEY=train_platform
./minio server http://train_minio{1...2}/opt/minio/data{1...4}
```
Then I put an object to http://train_minio1:9000, and there exists.
But when I browse http://train_minio2:9000, there is no bucket or object.
Data is not sysnchronized bewteen these two nodes, why ?
## Expected Behavior
If the cluster work, the data should be sychronized between these nodes.

## Current Behavior
The object put to minio, only exists in one node, and there is nothing in the another node.

## Possible Solution
No idea.
## Steps to Reproduce (for bugs)

1. Prepare two nodes, 4 disks per node.
2. Excute the below scripts to start minio cluster.
```
export MINIO_ACCESS_KEY=train_platform
export MINIO_SECRET_KEY=train_platform
./minio server \ 
http://train_minio{1...2}/opt/minio/data{1...4}
```
3. Use java cli to make bucket "test", and put an object to http://train_minio1:9000/test
4. Browse 'http://train_minio1:9000', I can see the bucket 'test' and the object
5. Browse 'http://train_minio2:9000', there is nothing.

## Context
The minio cluster dose not work, so the disk may be not enough in the future.

## Regression
no idea.

## Your Environment

* Version used (`minio --version`):2020-12-12T08:39:07Z
* Server setup and configuration:2 nodes, 4 disks per node
* Operating System and version (`uname -a`):Linux train_minio1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This doesn't make sense @py463360578 - distributed mode runs perfectly fine - I think you have some setup issues like firewall, or DNS settings node is not resolving etc. 

```bash
#!/usr/bin/env bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
export MINIO_ENDPOINTS="http://127.0.0.1:9001/tmp/disk01 http://127.0.0.1:9002/tmp/disk02 http://127.0.0.1:9003/tmp/disk03 http://127.0.0.1:9004/tmp/disk04 http://127.0.0.1:9005/tmp/disk05 http://127.0.0.1:9006/tmp/disk06 http://127.0.0.1:9007/tmp/disk07 http://127.0.0.1:9008/tmp/disk08"
for i in {01..08}; do
    minio server --address ":90${i}" &
done
```
