### ISSUE TITLE
Data loss after disk failure and restarting MinIO in distributed mode

### ISSUE THREAD

**Issue by alisalmaji** [minio/minio#11119]
Data loss occurred even with STANDARD parity after disk failure.

We have 4, 8TB physical disks and partition them into 28 * 1TB and create minio in distributed mode. ( 2 * 14 minio cluster)
Each physical disk partitioned into 7*1TB.
The parity was 7 data & 7 parity disks. ( STANDARD MODE )
Cluster was deployed on docker swarm.

## Problem
We expect after one of physical drives failure ( 7 minios ) no data lost.
That was ok ( no data loss and parity worked ) until we restart server to add physical drive.
After restart 2.8 TB of our data LOST.

We started minio heal process and but still we dont have 2.8TB of our data.

Please help and guide us to solve problem or change architect to prevent this type of data losses.

**Comment by harshavardhana** [comment]
@alisalmaji your issue report doesn't make sense - can you provide more details?

**Comment by klauspost** [comment]
MinIO should never be set up with separate partitions on the same disks. Provide raw disks to MinIO, otherwise you are bypassing all safety measures to prevent data loss.

**Comment by alisalmaji** [comment]
@klauspost 
That is true but in our design even if one of physical disks failed, MinIO should prevent data loss in standard mode.
Even with disk failure everything was ok but after restart MinIO, data lost.

**Comment by alisalmaji** [comment]
@harshavardhana 
![image](https://user-images.githubusercontent.com/52038282/102353392-36c2bc00-3fbe-11eb-8f40-e497ad2ffa06.png)

**Comment by alisalmaji** [comment]
@harshavardhana 
Based on picture above, we create 2 * 14 MinIO cluster with this command:
server http://new-minio-{1...14}/export-1 http://new-minio-{15...28}/export-1

Below of each minio is just one 1TB partition.

This is backend configuration:

![image](https://user-images.githubusercontent.com/52038282/102353789-ce280f00-3fbe-11eb-87eb-0adb85f41bd8.png)

**Comment by alisalmaji** [comment]
We stored 8.8 TB data in MinIO, but now we just have 6.0 TB data.
many of our objects return 404 status code

**Comment by harshavardhana** [comment]
> server [http://new-minio-{1...14}/export-1](http://new-minio-%7B1...14%7D/export-1) [http://new-minio-{15...28}/export-1](http://new-minio-%7B15...28%7D/export-1)

First this is an incorrect way to setup - you seem to running same server locally across many partitions - this doesn't provide any protection. Losing an entire node will lead to an entire pool to be lost. 

> That is true but in our design even if one of physical disks failed, MinIO should prevent data loss in standard mode.

Another is incorrect setup with using same drives with multiple partitions. 

I don't think we can fix your setup - this is not a data loss scenario - this is simply a bad setup not knowing what you are doing.

**Comment by alisalmaji** [comment]
@harshavardhana 
MinIOs spread over 5 servers and not locally.

we didnt loss a node, just one physical drive ( 7 partitions ). With "standardSCData: 7" and "standardSCParity 7" according to erasure document, MinIO should not loss any data.

I accept our design is not good, but this is all we have from physical resources.
We are a new startup and dont have huge financial resources to done best practices.

**Comment by klauspost** [comment]
There are no guarantees.  If you lose your parity shard amount of disks, you will lose all objects that aren't in perfect condition.

I cannot tell you what has happened here, but there can be many reasons objects aren't in perfect condition. MinIO will not fail uploads if a drive cannot be written to, only if there are enough 'bad' drives for the object to be unable to reconstruct.

Scanning and reconstructing takes time and in most cases there is a significant delay between objects being automatically heal checked.

I don't think there is much more we can do here. Going through your setup and see if there is any way to recover your data is not something we can offer for free, since it would likely be very time consuming.

**Comment by godsey** [comment]
@alisalmaji given you have 4 8TB drives, you should purchase an additional 2 servers and run 1 minio physical host with 1 physical 8TB drive as a single 8TB partition.
