### ISSUE TITLE
expose Prometheus "Bucket Count"  

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11113]
As a administrator, I would like to be able to expose some more metrics about my MinIO cluster, i would like to have a metric that covers total buckets over a cluster ie` bucket_count `

**Describe alternatives you've considered**
Running rules around bucket_objects_count works, however due to the total size of buckets the calculation takes too long.

**Comment by harshavardhana** [comment]
This should be addressed in a faster manner as per #11115

**Comment by harshavardhana** [comment]
> This should be addressed in a faster manner as per #11115

Please upgrade and let us know if reflecting newer buckets is still slower.

It should be updated every 5 minutes.

**Comment by kannappanr** [comment]
@zapto2600 closing this issue as answered. Please feel free to reach out to us if you have further questions
