### ISSUE TITLE
Container crash on startup

### ISSUE THREAD

**Issue by xoxys** [minio/minio#11120]
## Current Behavior
With the latest version from today (RELEASE.2020-12-16T05-05-17Z) we see:

```
Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: SYSTEM()
Time: 13:24:42 UTC 12/16/2020
DeploymentID: bf763a18-0875-4ca3-a90d-389f8660105e
Error: Not Implemented (cmd.NotImplemented)
       3: cmd/fs-v1.go:1551:cmd.(*FSObjects).HealBucket()
       2: cmd/bucket-metadata-sys.go:442:cmd.(*BucketMetadataSys).concurrentLoad.func1()
       1: pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
```

## Your Environment

* Version used (`minio --version`): RELEASE.2020-12-16T05-05-17Z
* Operating System and version (`uname -a`): Linux 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> API: SYSTEM()
> Time: 13:24:42 UTC 12/16/2020
> DeploymentID: bf763a18-0875-4ca3-a90d-389f8660105e
> Error: Not Implemented (cmd.NotImplemented)
>        3: cmd/fs-v1.go:1551:cmd.(*FSObjects).HealBucket()
>        2: cmd/bucket-metadata-sys.go:442:cmd.(*BucketMetadataSys).concurrentLoad.func1()
>        1: pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()

There is no crash here, it can be ignored and moved on - all the functionality remains the same.

**Comment by xoxys** [comment]
Thanks for closing this issue. The web frontend is not reachable with this version and thats the only eeror in the log

**Comment by xoxys** [comment]
@harshavardhana If it is not related to this then I can't see a reason why the web frontend is dead after the upgrade

**Comment by harshavardhana** [comment]
> Thanks for closing this issue. The web frontend is not reachable with this version and thats the only eeror in the log

this error log has nothing to do with the web frontend.

**Comment by xoxys** [comment]
Fine, what should I do to report it correctly? Fill up another issue?

**Comment by harshavardhana** [comment]
Please open an issue with relevant screenshots for WebUI and along with browser dev tools output - some network trace etc. There is literally nothing in this issue that is actionable. 

I just tested locally it runs perfectly fine.

**Comment by xoxys** [comment]
Ok found it.... all this is related to the switch of the underlying docker base image (and/or its packages)... While wget based health checks were working fine all the time this has changed now due to the lack of wget in the new images.

**Comment by harshavardhana** [comment]
> Ok found it.... all this is related to the switch of the underlying docker base image (and/or its packages)... While wget based health checks were working fine all the time this has changed now due to the lack of wget in the new images.

You should use curl which is always present in our docker images
