### ISSUE TITLE
When an object name is the same as the prefix of another object

### ISSUE THREAD

**Issue by zivhong-via** [minio/minio#11129]
I did the following experiments using the version RELEASE.2020-12-18T03-27-42Z.

Experimental steps:

Case 1:
    0. Start a minio server with the command "minio server ~/minioFolders/disk{1...4}"
    1. make a bucket named "bucket1"
    2. put an object with key "name1/obj1"
    3. put an object with key "name1"
    4. list objects in "bucket1"
        - The responding object list only contains object "name1"
    5. check the files in the folder "disk1" on the server
        ![image](https://user-images.githubusercontent.com/76200585/102590915-2b9d9680-414c-11eb-8e25-632a15cf5ee4.png)
    6. remove the folder "disk1" to trigger heeling (monitorLocalDisksAndHeal)
    7. list objects in "bucket1"
        - The responding object list only contains object "name1"
    8. check the files in the folder "disk1" on the server
        ![image](https://user-images.githubusercontent.com/76200585/102591607-41f82200-414d-11eb-87af-d877811be16a.png)

Case 2:
When writing objects in the following order, the server will respond with the error message "XMinioParentIsObject: Object-prefix is already an object, please choose a different object-prefix name."
    1. put an object with key "name1"
    2. put an object with key "name1/obj1"

## Expected Behavior

It should be able to catch all objects in **case 1**.
Refer to the results of AWS S3, the operation of **case 2** should be successful.

**Comment by harshavardhana** [comment]
> 1. make a bucket named "bucket1"
> 2. put an object with key "name1/obj1"
> 3. put an object with key "name1"
> 4. list objects in "bucket1"
> - The responding object list only contains object "name1"
> 5. check the files in the folder "disk1" on the server

This case should never be allowed on MinIO and case2 - we do not allow creating objects 
with conflicting names. This looks like some regression.

**Comment by zivhong-via** [comment]
> This case should never be allowed on MinIO and case2 - we do not allow creating objects
with conflicting names. This looks like some regression.

This means that MinIO will never support creating objects with conflicting names?
This behavior is allowed in AWS S3 service. Does this mean that developers need to consider this issue if the backend is to be transferred from AWS S3 to MinIO?

**Comment by harshavardhana** [comment]
> This means that MinIO will never support creating objects with conflicting names?

yes we will not. There is nothing we can do about it, unfortunately.

> This behavior is allowed in AWS S3 service. Does this mean that developers need to consider this issue if the backend is to be transferred from AWS S3 to MinIO?

This is wrong behavior in AWS S3 and we don't want to encourage it. Yes they need to.

**Comment by zivhong-via** [comment]
I got it, thank you for your answer.

**Comment by harshavardhana** [comment]
> This means that MinIO will never support creating objects with conflicting names?

Just to be clear what we are saying is you can't have

- bucket/object1  and - bucket/object1/object2 on the same namespace.
