### ISSUE TITLE
access_key with '/' does not work as expected

### ISSUE THREAD

**Issue by BoleynSu** [minio/minio#11126]
Access keys with '/' will be gone after restarting the service. The same bug also exists for policies.

## Expected Behavior
Access keys with '/' work correctly.

## Current Behavior
Access keys with '/' will be gone after restarting the service.

## Possible Solution
Forbid access_key with '/' or handle it correctly.

## Steps to Reproduce (for bugs)

1. mc admin user add play test/user
2. mc admin user list play
3. mc admin service restart
4. mc admin user list play

## Your Environment
play.min.io

**Comment by harshavardhana** [comment]
although we can support it, we ask you to avoid it - relevant PR with the fix https://github.com/minio/minio/pull/11127
