### ISSUE TITLE
[faq] Crawler is running on multiple nodes

### ISSUE THREAD

**Issue by josiasmontag** [minio/minio#11131]
I am currently investigating why the crawler is not able to keep up in our cluster. I noticed that it crawls the same bucket on multiple nodes. 

Both `minio3` and `minio8` do simultaneously scan the bucket `tasks`:

minio3
```
data-usage: Start crawling. Bloom filter: false - /export3 + tasks
data-usage: Cycle: 0, Entries: 0 - /export3 + tasks
data-usage: Level 0, scanning 1 directories. - /export3 + tasks
data-usage: Level 1, scanning 587497 directories. - /export3 + tasks
...
```

minio8
```
data-usage: Start crawling. Bloom filter: false - /export4 + tasks
data-usage: Cycle: 0, Entries: 0 - /export4 + tasks
data-usage: Level 0, scanning 1 directories. - /export4 + tasks
data-usage: Level 1, scanning 1248471 directories. - /export4 + tasks
...
```

```
~ mc admin top locks minio --json
{
 "status": "success",
 "locks": {
  "time": "2020-12-18T11:19:59.031566698Z",
  "resource": ".minio.sys/runDataCrawler.lock",
  "type": "WRITE",
  "source": "[data-crawler.go:79:runDataCrawler()]",
  "serverlist": [
   "minio2:9000",
   "minio3:9000",
   "minio4:9000",
   "minio1:9000"
  ],
  "owner": "minio6:9000",
  "id": "31c36e3a-2062-4cf2-b126-9fea5a81f24c",
  "quorum": 3
 }
}
```

## Expected Behavior
According to my understanding it should only run once per cluster?

## Current Behavior
Crawler runs on at least 2 nodes at the same time.

## Possible Solution
Move the `runDataCrawler.lock` after the initial 5 minute delay instead of locking directly on startup when some nodes might not be up yet.

## Steps to Reproduce (for bugs)

1. Setup 8 nodes cluster with `MINIO_DISK_USAGE_CRAWL_DEBUG=on`
2. `mc admin service restart minio`
3. Wait 5 minutes
4. Check on how many nodes the crawler is running 

## Context
Although using `mc admin config set minio crawler delay=0` the crawler is not able to keep up. Usage data is outdated and ILM rules are applied very delayed / not at all. Multiple crawlers running at the same time might be the reason for it.

## Your Environment
```
●  minio2:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio3:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio4:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio5:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio6:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio7:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio8:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

●  minio1:9000
   Uptime: 11 minutes 
   Version: 2020-12-16T05:05:17Z
   Network: 8/8 OK 
   Drives: 4/4 OK 

870 MiB Used, 3 Buckets, 192 Objects
32 drives online, 0 drives offline
```

**Comment by klauspost** [comment]
To visit all objects all sets must be crawled in the entire cluster.

Objects are distributed across sets and server pools, so no set has all objects.

**Comment by klauspost** [comment]
Only one server (with the lock) will initiate the scans and collect/summarize the data.

**Comment by josiasmontag** [comment]
Okay, thanks for the explanation.
