### ISSUE TITLE
[working as intended] Cluster health endpoint maintenance query not accurate

### ISSUE THREAD

**Issue by briend** [minio/minio#11139]
According to the [healthcheck docs](https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md), we should be able to hit this endpoint and if a `200` response is received then it is safe to take a node down for maintenance:

```
curl -I -H "User-Agent: Mozilla/5.0"  http://localhost:9000/minio/health/cluster?maintenance=true
HTTP/1.1 200 OK
```
Maybe this is an assumption, but we thought that this would return something other than `200` if the cluster was in a degraded state such as if there is failed disk, down nodes, and/or unhealthy objects.  We tried to "break" a minio cluster by taking down 3 out of 4 nodes, removing disks, etc, but this endpoint always returned `200` despite the cluster being functionally broken.

Our use-case for this information is when migrating minio kubernetes pods to new hardware.  Before deleting and moving a pod it would ideal to know that it is safe to do so.  

Tested on version: `RELEASE.2020-12-03T05-49-24Z`

**Comment by harshavardhana** [comment]
It will only return non 200 OK - if you don't have enough quorum @briend or drives are healing

```
curl -v -H "User-Agent: Mozilla/5.0"  http://localhost:9000/minio/health/cluster?maintenance=true
```

**Comment by harshavardhana** [comment]
> Maybe this is an assumption, but we thought that this would return something other than `200` if the cluster was in a degraded state such as if there is failed disk, down nodes, and/or unhealthy objects. We tried to "break" a minio cluster by taking down 3 out of 4 nodes, removing disks, etc, but this endpoint always returned `200` despite the cluster being functionally broken.

also please describe your issue properly with examples, which MinIO version etc. You haven't filled out any of the issue template either.

**Comment by harshavardhana** [comment]
As you can see in the following tests it works perfectly fine - quorum loss scenario 

```
#!/usr/bin/env bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
export MINIO_ENDPOINTS="http://127.0.0.1:9001/tmp/disk01 http://127.0.0.1:9002/tmp/disk02 http://127.0.0.1:9003/tmp/disk03 http://127.0.0.1:9004/tmp/disk04 http://127.0.0.1:9005/tmp/disk05 http://127.0.0.1:9006/tmp/disk06 http://127.0.0.1:9007/tmp/disk07 http://127.0.0.1:9008/tmp/disk08"
for i in {01..08}; do
    minio server --address ":90${i}" &
done
```

Running an 8 server setup locally means that I have with default storage class 4 data, 4 parity i.e 5 is write quorum

Now if I take down 3 nodes 
```
~ ps -ef |grep 900
harsha    654150       1  8 21:59 pts/0    00:00:15 minio server --address :9004
harsha    654151       1  6 21:59 pts/0    00:00:12 minio server --address :9005
harsha    654152       1  6 21:59 pts/0    00:00:12 minio server --address :9006
harsha    654153       1  6 21:59 pts/0    00:00:12 minio server --address :9007
harsha    654154       1  6 21:59 pts/0    00:00:13 minio server --address :9008
```

And now reaching to 9004 port it indicates that you will lose quorum of you take down any of the nodes. 


```
~  curl -v http://localhost:9004/minio/health/cluster?maintenance=true
*   Trying 127.0.0.1:9004...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9004 (#0)
> GET /minio/health/cluster?maintenance=true HTTP/1.1
> Host: localhost:9004
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 412 Precondition Failed
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 165208ED51AFABE2
< X-Minio-Write-Quorum: 5
< X-Xss-Protection: 1; mode=block
< Date: Sat, 19 Dec 2020 06:03:54 GMT
< 
* Connection #0 to host localhost left intact
```

Returns that Pre-Condition failed i.e you shouldn't take more servers down as you make loos write access to your applications. This is the sole reason this was built for and works as expected. 

You can't use it with FS, Gateway modes those only indicate if their single backend drives have access etc.

Similarly, let's say even one of the drives is being healed we don't allow you to take down the server, removing the drive of a running system, and running the same check returns how many drives are being healed. 

```
~ curl -v http://localhost:9004/minio/health/cluster?maintenance=true
*   Trying 127.0.0.1:9004...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9004 (#0)
> GET /minio/health/cluster?maintenance=true HTTP/1.1
> Host: localhost:9004
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 412 Precondition Failed
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1652090FBA44E5DC
< X-Minio-Healing-Drives: 1
< X-Minio-Write-Quorum: 5
< X-Xss-Protection: 1; mode=block
< Date: Sat, 19 Dec 2020 06:06:20 GMT
< 
* Connection #0 to host localhost left intact
```

And why maintenance is not allowed at this point in time - you should let the drives heal. Once the drives heal 

```
~ curl -v http://localhost:9004/minio/health/cluster?maintenance=true
*   Trying 127.0.0.1:9004...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9004 (#0)
> GET /minio/health/cluster?maintenance=true HTTP/1.1
> Host: localhost:9004
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 165209227B7B38D5
< X-Minio-Write-Quorum: 5
< X-Xss-Protection: 1; mode=block
< Date: Sat, 19 Dec 2020 06:07:40 GMT
< 
* Connection #0 to host localhost left intact
```

You can see that you can proceed with the maintenance of this server.  

*maintenance* is a way to ask a server if I can take it down or not for some OS upgrades or some other routine activities while keeping the availability online for the cluster. 

This feature is tightly integrated and works with the VMware Vsphere product already.

Also, I do request you to open issues with some more information, opening issues without any meaningful outputs, what is your setup like - what version of MinIO - none of that is mentioned in the issue. 

Unfortunately, these type of issues is simply not actionable for us, nonetheless, I took the opportunity to explain this for others to read and understand.
.

**Comment by briend** [comment]
Thank you and sorry for the poorly documented issue.  My main issue seemed to be improperly using `curl -I` for headers only, when I should have used `curl -v`.  Also I’m not sure how you manage to make it work without providing a Mozilla user agent header.  But I am very happy to see so much detail in the X-headers, that wasn’t immediately obvious; I thought only the status code was relevant.   Again thanks for your thorough example.  I recreated most of that with the docker-compose template.

**Comment by briend** [comment]
I just realized that you _don't_ need to provide the `Mozilla` user-agent with `curl -v`.  Just a comedy of errors here :-)

You only get an error with the HEAD request, which you shouldn't do (make a GET).  Hope that helps someone:
```
# incorrect, get 403:
curl -I -XHEAD http://localhost:9000/minio/health/cluster?maintenance=true
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1652CCCA46F270B5
X-Xss-Protection: 1; mode=block
Date: Mon, 21 Dec 2020 17:53:06 GMT

# incorrect, get invalid result code:
curl -I -XHEAD -H "User-Agent: Mozilla/5.0" http://localhost:9000/minio/health/cluster?maintenance=true
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2281
Content-Security-Policy: block-all-mixed-content
Content-Type: text/html; charset=utf-8
Last-Modified: Sat, 21 Nov 2020 03:45:25 GMT
Vary: Origin
X-Amz-Request-Id: 1652CCCCFAB6C1F1
X-Xss-Protection: 1; mode=block
Date: Mon, 21 Dec 2020 17:53:17 GMT


# correct, gets valid result and additional minio X-Headers:
curl -I -XGET http://localhost:9000/minio/health/cluster?maintenance=true
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1652CCD6A57754AC
X-Minio-Write-Quorum: 3
X-Xss-Protection: 1; mode=block
Date: Mon, 21 Dec 2020 17:53:59 GMT

```
