### ISSUE TITLE
Slowdown:Slowdown

### ISSUE THREAD

**Issue by doodlemania2** [minio/minio#11147]
Getting lots of these with a default installation:
Error: SlowDown: A timeout exceeded while waiting to proceed with the request, please reduce your request rate 503 

After a while, the timeouts go to Retrying (10) ... and will do a backoff 503 for some time.

I've not set any command line args to throttle/limit, so was wondering if Minio was calculating internal limits based on amount of RAM available or something?

## Expected Behavior
Given no configuration on limits otherwise, should not get any 503's unless I literally crash the app :)

## Your Environment
*Latest from master
*Ubuntu Bionic
*Running in docker with 256MB of Ram allocated.

**Comment by harshavardhana** [comment]
Yes 256MiB means we have little room to do anything meaningful.

**Comment by doodlemania2** [comment]
Makes perfect sense - I guess I should reframe my question if there is an internal setup that defines these timeout thresholds based on resources that I could override or configure?

**Comment by harshavardhana** [comment]
> Makes perfect sense - I guess I should reframe my question if there is an internal setup that defines these timeout thresholds based on resources that I could override or configure?

https://github.com/minio/minio/tree/master/docs/config#api @doodlemania2 its `MINIO_API_REQUESTS_DEADLINE` that you are looking for.
