### ISSUE TITLE
I am trying to set different key/secret the azure gateway in order not to share azure secretwith MinIO clients

### ISSUE THREAD

**Issue by RaniRaven** [minio/minio#11154]
According to the basic documentation :
Use custom access/secret keys
If you do not want to share the credentials of the Azure blob storage with your users/applications, you can set the original credentials in the shell environment using AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY variables and assign different access/secret keys to MINIO_ACCESS_KEY and MINIO_SECRET_KEY.

This should be working, but the minio server fails with invalid cerdentials for azure if the MINIO_ACCESS_KEY  is not set to the azure credentials. How is this supposed to be done ?

**Comment by kannappanr** [comment]
@RaniRaven I just now tested this and this seems to be working fine. I have AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY set to the Azure credentials. MINIO_ACCESS_KEY and MINIO_SECRET_KEY are set to minio and minio123 respectively.

**Comment by harshavardhana** [comment]
> According to the basic documentation :
> Use custom access/secret keys
> If you do not want to share the credentials of the Azure blob storage with your users/applications, you can set the original credentials in the shell environment using AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY variables and assign different access/secret keys to MINIO_ACCESS_KEY and MINIO_SECRET_KEY.
> 
> This should be working, but the minio server fails with invalid cerdentials for azure if the MINIO_ACCESS_KEY is not set to the azure credentials. How is this supposed to be done ?

Use latest MinIO releases for this to be supported..
