### ISSUE TITLE
Unable to handle encrypted backend for config, iam and policies

### ISSUE THREAD

**Issue by Tsingh315** [minio/minio#11155]
While starting minio docker container on mac getting the error with trace 

## Expected Behavior
Expecting minio docker container to start without any problems. 

## Current Behavior
 Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
storage_1   |        8: github.com/minio/minio@/cmd/fs-v1-helpers.go:333:cmd.fsCreateFile()
storage_1   |        7: github.com/minio/minio@/cmd/fs-v1.go:973:cmd.(*FSObjects).putObject()
storage_1   |        6: github.com/minio/minio@/cmd/fs-v1.go:887:cmd.(*FSObjects).PutObject()
storage_1   |        5: github.com/minio/minio@/cmd/config-common.go:62:cmd.saveConfig()
storage_1   |        4: github.com/minio/minio@/cmd/config-encrypted.go:291:cmd.migrateConfigPrefixToEncrypted()
storage_1   |        3: github.com/minio/minio@/cmd/config-encrypted.go:107:cmd.handleEncryptedConfigBackend()
storage_1   |        2: github.com/minio/minio@/cmd/server-main.go:194:cmd.initSafeMode()
storage_1   |        1: github.com/minio/minio@/cmd/server-main.go:447:cmd.serverMain()
storage_1   | Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: Unexpected error, please report this issue at https://github.com/minio/minio/issues'

## Steps to Reproduce (for bugs)

1. Using docker-compose.yml file
2. configuration: 
`  storage:
    image: minio/minio
    volumes:
      - ./volumes/s3:/data
    environment:
      - MINIO_ACCESS_KEY=<1234>
      - MINIO_SECRET_KEY=<45433>
    ports:
      - "9000:9000"
    command: ["server","/data"]
    networks:
      -network1`
3. docker-compose up

## Context
I am unable to run my local docker container.

## Your Environment
Macos Catalina 10.15.5

**Comment by harshavardhana** [comment]
Changing environment values requires credential rotation or use older credentail https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

**Comment by Tsingh315** [comment]
What environment values? We are not doing credential rotation. Kindly advise.
