### ISSUE TITLE
Errors reported when MINIO_DOMAIN is set on a collection of NAS gateway instances

### ISSUE THREAD

**Issue by gbiff** [minio/minio#11161]
I'm looking to support virtual-host-style requests with a set of MinIO instances running in 'NAS gateway' mode behind a pair of load balancers. However, the instances run with different internal IPs and are logging errors to the console:
`API: SYSTEM()
Time: 00:19:06 UTC 12/24/2020
DeploymentID: 36371598-c7da-4ff2-a229-c4b6d5b5b324
Error: Unable to add bucket DNS entry for bucket <bucket name>, an entry exists for the same bucket. Use one of these IP addresses [<container's internal IP>:9000] to access the bucket (*errors.errorString)
       2: cmd/bucket-handlers.go:131:cmd.initFederatorBackend()
       1: cmd/gateway-main.go:351:cmd.StartGateway()`
## Expected Behavior

The MinIO instances all have access to the same buckets as they mount the same NFS share. I don't see a need to specify MINIO_PUBLIC_IPS with this configuration as each instance can operate independently and provide access to all buckets.
## Current Behavior

An error is reported on the console per bucket and it's unclear if the error can be safely ignored.
## Possible Solution

Setting MINIO_PUBLIC_IPS=127.0.0.1 appears to resolve the errors without any problems, but I'm not certain if this is valid or if it will lead to unforeseen issues?
## Steps to Reproduce (for bugs)

Start two MinIO instances in 'NAS gateway' mode, using the same NFS share for storage and environment variables:
MINIO_ACCESS_KEY=accesskey
MINIO_SECRET_KEY=secretkey
MINIO_DOMAIN=minio.mydomain.com
MINIO_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
MINIO_ETCD_PATH_PREFIX=minio

## Regression

No, I don't believe this is a regression. 
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
A wildcard DNS entry directs S3 clients to a pair of haproxy load balancers, which distribute traffic to multiple MinIO instances (RELEASE.2020-11-19T23-48-16Z) running within docker containers on multiple physical hosts. The instances access the same NFSv3 share for storage, and ETCD cluster. We're not using CoreDNS and we're not trying to run MinIO in a federated mode - we simply want to enable virtual-host-style bucket addressing.

**Comment by harshavardhana** [comment]
> An error is reported on the console per bucket and it's unclear if the error can be safely ignored.

Error cannot be safely ignored, the issue here is that you have bucket entries already present with conflicting IP ranges. You need to specify the IPs in MINIO_PUBLIC_IPS that specify how client is going to resolve to this bucket. 

You can see our documentation on this and how it explains this process. 

> * A wildcard DNS entry directs S3 clients to a pair of haproxy load balancers, which distribute traffic to multiple MinIO instances (RELEASE.2020-11-19T23-48-16Z) running within docker containers on multiple physical hosts. The instances access the same NFSv3 share for storage, and ETCD cluster. We're not using CoreDNS and we're not trying to run MinIO in a federated mode - we simply want to enable virtual-host-style bucket addressing.

If all you want is just virtual-host-style and you don't use coreDNS then you can simply ignore this message.
