### ISSUE TITLE
安全连接指的是什么意思？https吗？

### ISSUE THREAD

**Issue by goutou123** [minio/minio#11162]
上传文件时报错提示，MinIO API responded with message=Requests specifying Server Side Encryption with Customer provided keys must be made over a secure connection

**Comment by harshavardhana** [comment]
Please open issues in English with relevant information

**Comment by kannappanr** [comment]
Yes, it means https. Please take a look at https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls.html for instructions on setting up TLS. SSE-C requires the connection to be `https`
