### ISSUE TITLE
Object shared want to segment upload

### ISSUE THREAD

**Issue by Andy6Loda** [minio/minio#11167]
Is your feature request related to a problem? Please describe.
1.When i shared one document  allow some people upload . Just one method HTTP::PUT?
2.I try to segment upload,use the HTTP-Header parameter ‘Range’ is invalid，but it can be used in download

Describe the solution you'd like
I want shared upload object allow segment upload

Describe alternatives you've considered
Such as use POST method by Transfer-Encoding: chunked，Range ...

**Comment by harshavardhana** [comment]
> Is your feature request related to a problem? Please describe.
> 1.When i shared one document allow some people upload . Just one method HTTP::PUT?
> 2.I try to segment upload,use the HTTP-Header parameter ‘Range’ is invalid，but it can be used in download
> 
> Describe the solution you'd like
> I want shared upload object allow segment upload
> 
> Describe alternatives you've considered
> Such as use POST method by Transfer-Encoding: chunked，Range ...

Segment upload requires S3 multipart upload, for that you need to generate presigned URLs for each S3 multipart operation.

https://www.altostra.com/blog/multipart-uploads-with-s3-presigned-url

**Comment by Andy6Loda** [comment]
Okay, thanks for the explanation.
