### ISSUE TITLE
docs: Improve Docker documentation.

### ISSUE THREAD

**Issue by rafael-leo-almeida** [minio/minio#1116]
Include in Docker.md an way to separete config files into a specific volume. In the same way that is done with data.
That will enable to recreate a container using original image whithou generate new credencials.

https://github.com/minio/minio/blob/master/Docker.md#persist-minio-configs

> docker create -v /export --name minio-export **-v /.minio --name minio-config** minio/my-minio /bin/true

In my case I start two only data container (data || config) and attach to main container (app).

**Comment by harshavardhana** [comment]
Thanks @rafaelsisweb - we will look into it.
