### ISSUE TITLE
helm chart for minio's azure gateway

### ISSUE THREAD

**Issue by RaniRaven** [minio/minio#11168]
I found a couple of guides in the internet about how to deploy minio to k8s.
The problem is that all are missing information about the setting of the config-map of the yaml.
I need to get an example for the yaml's file configuration for the deployment over k8s with the correct parameters settings.

For example, in the default generated yaml, there is not access/secret values in the azure gateway section, and it is unclear how to set the values to that the access key of azure will not be exposed to the clients.

**Comment by harshavardhana** [comment]
We publish a managed app in Azure Cloud and expect you to use this 

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/minio.minioblob?tab=Overview

We are not doing any further work on helm charts unfortunately https://github.com/minio/charts
