### ISSUE TITLE
Huge slowness due to "object layer not ready"

### ISSUE THREAD

**Issue by cambierr** [minio/minio#11174]
## Expected Behavior
I just expect Minio to work as it did for the last N months

## Current Behavior
Minio is damn slow (most object related calls takes more than 2 seconds to complete and transfers are uber slow) **on a specific bucket**

## Possible Solution
* I started a manual heal to see if it helps but it's very slow so no feedback yet

## Steps to Reproduce (for bugs)
I don't know what happened... 

## Context
My minion is deployed in Kubernetes using official 8.0.8 chart, nothing special other than that

## Regression
No idea

## Your Environment

* Version used (`minio --version`): RELEASE.2020-12-03T05-49-24Z
* Server setup and configuration: distributed setup with 4 shards
* Operating System and version (`uname -a`): Kubernetes 18 on Ubuntu 20.04

## Misc
I the logs in one of the four pods, I see thousands of those lines:
```
API: GetMetacacheListing()

Time: 09:53:44 UTC 12/28/2020

DeploymentID: 955cc6d3-5d25-4e57-bbe5-d3d2d27e64b1

RequestID: 1654D8B099ED2581

RemoteHost: 10.42.0.11

Host: minio-b-2.minio-b-svc.minio-b.svc.cluster.local:9000

UserAgent: Go-http-client/1.1

Error: loadBucketMetaCache: object layer not ready. bucket: "gitlab-registry" (*errors.errorString)

       4: cmd/metacache-bucket.go:83:cmd.loadBucketMetaCache()

       3: cmd/metacache-manager.go:165:cmd.(*metacacheManager).getBucket()

       2: cmd/peer-rest-server.go:620:cmd.(*peerRESTServer).GetMetacacheListingHandler()

       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2020-12-03T05-49-24Z

You should upgrade @cambierr we fixed a whole bunch of bugs upgrade to RELEASE.2020-12-26T01-35-54Z and let us know how it goes.

**Comment by cambierr** [comment]
Will try right now.

That's the version included by the helm chart. Shouldn't it be updated too to include a more recent version if that one is that buggy ?

**Comment by cambierr** [comment]
@harshavardhana I confirm that upgrading minio did the trick ! Thank you very much

Still, I think a new patch should be provided to the helm chart repo so that there is a version with a working minio setup

**Comment by harshavardhana** [comment]
> Will try right now.
> 
> That's the version included by the helm chart. Shouldn't it be updated too to include a more recent version if that one is that buggy ?

Helm charts are not our priority right now @cambierr
