### ISSUE TITLE
labels are not being correctly updated in docker images on docker hub

### ISSUE THREAD

**Issue by justsomeguyontheinternet** [minio/minio#11189]
docker hub tag "RELEASE.2020-12-29T23-29-29Z" doesn't match
"LABEL name=MinIO vendor=MinIO Inc <dev@min.io> maintainer=MinIO Inc <dev@min.io> version=RELEASE.2020-11-25T22-36-25Z release=RELEASE.2020-11-25T22-36-25Z...."

![image](https://user-images.githubusercontent.com/34630628/103367177-6aa7e200-4a92-11eb-868f-0508d62045e6.png)

**Comment by harshavardhana** [comment]
Correct this is because it's not automated properly @justsomeguyontheinternet fixed it 428f288379292541b49fe64d52881fe0fe91ebcd

**Comment by justsomeguyontheinternet** [comment]
not sure if it matters, but a few older versions have the same issue, i think most of them between 11-25 and most recent.

**Comment by harshavardhana** [comment]
> not sure if it matters, but a few older versions have the same issue, i think most of them between 11-25 and most recent.

Yeah older ones don't matter we can fix it from now on, this is just a label thing anyways cosmetic.

**Comment by justsomeguyontheinternet** [comment]
Thanks!
