### ISSUE TITLE
Replication feature : MinIO Extension doesn't work as I expect

### ISSUE THREAD

**Issue by TreeKat71** [minio/minio#11180]
I enable “Delete Replication” and disable “Delete Marker Replication”. 
Then I delete an object from the source with version id, but it doesn’t delete the replicated one.  Is it correct?

## Expected Behavior
If I delete an object from the source, the replicated one should be deleted as well. 

## Current Behavior
I delete an object from the source, but it doesn’t delete the replicated one.

## Steps to Reproduce (for bugs)
1. mc version enable minio/source
2. mc version enable minio/backup
3. mc admin bucket remote add minio/source http://ACCESS:SECRET@IP:PORT/backup --service replication
-> "arn:minio:replication::HASH:backup"

4. mc replicate add minio/source --arn "arn:minio:replication::HASH:backup" --replicate "delete" --remote-bucket backup
-> Replication configuration rule applied to minio/source successfully.

5.  Upload an object from web UI to source bucket
6.  mc rm minio/source/1.jpg --version-id "ID" (Delete object with version id)

## Your Environment

* Version used (`minio --version`):  2020-12-23T02:24:12Z
* Server setup and configuration: 
* Operating System and version (`uname -a`):  Linux kminion-gpu-001 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TreeKat71** [comment]
I am not sure it is fixed or not. I use the edge docker image.  And I disable both, but it seems like both enabled.

The default behavior is disable both. 
1. I use `mc watch` to monitor what happen to the target bucket.
2. I delete the object from the web UI and here is the log
"""
[2021-01-06T09:42:33.754Z]        s3:ObjectRemoved:DeleteMarkerCreated http://ip:32000/muller-s/8b8126b1cae1d797a381e44965f76255.jpg
[2021-01-06T09:42:33.761Z]        s3:ObjectRemoved:Delete http://ip:32000/muller-b/8b8126b1cae1d797a381e44965f76255.jpg
[2021-01-06T09:42:33.762Z]        s3:Replication:OperationCompletedReplication http://ip:32000/muller-s/8b8126b1cae1d797a381e44965f76255.jpg
"""

**Comment by poornas** [comment]
> I am not sure it is fixed or not. I use the edge docker image. And I disable both, but it seems like both enabled.
> 
> The default behavior is disable both.

you can see if your replication rule has delete replication enabled or not by looking at `mc replicate export alias/bucket`. If you are disabling a previously enabled rule you can either rm and add the rule again or edit with `mc replicate edit alias/bucket --id rule-id --replicate ""` to disable delete and delete marker replication. Tested this again - works as intended.

**Comment by TreeKat71** [comment]
What I mean is I disable both, which is default, and I check it with `mc replicate ls <alias>/<bucket> --json`.
And yes they are both disabled. 
BUT when I delete an object from the web UI, the target object is also deleted.
BTW, if I use `mc rm --version-id`, it only deletes the source object not both.
