### ISSUE TITLE
MinIO S3 gateway cache not being hit

### ISSUE THREAD

**Issue by solracsf** [minio/minio#11187]
- Ubuntu 20.04
- minio version RELEASE.2020-12-29T23-29-29Z
- Disk cache on local (`ext4`) drive

I've set up a S3 gateway using these variables:

```
MINIO_CACHE="on"
MINIO_CACHE_DRIVES="/var/cache/minio"
MINIO_CACHE_EXPIRY=30
MINIO_CACHE_QUOTA=60
MINIO_CACHE_AFTER=0
MINIO_CACHE_WATERMARK_LOW=80
MINIO_CACHE_WATERMARK_HIGH=95
```

Cache drive is being filed:

```
du -sh /var/cache/minio
23M  /var/cache/minio
```

But, if i download a file, it's being download from the edge and not from the cache.

Here, a 9Mb file downloaded 10 times using

`for i in {1..10}; do curl -o /dev/null http://10.1.0.10:9000/s/aeiufb/download; done`

![image](https://user-images.githubusercontent.com/12234510/103328536-8d69d480-4a59-11eb-9168-9977a06e8e93.png)

It produces 97Mb of egress, i was expecting a value between zero and a few Kb, as the file has been uploaded trough the gateway and  `MINIO_CACHE_AFTER=0`

**Comment by harshavardhana** [comment]
This doesn't look like our gateway implementation @acsfer are you sure you are using MinIO and not Storj's gateway implementation here ?

**Comment by solracsf** [comment]
@harshavardhana forget about the logs, these were indeed about Storj Gateway... _(sorry, i'm testing both implementations...)_
But the use case described is about MinIO implementation. Reproduced right now, same behavior.

What else can i provide to debug this?

**Comment by harshavardhana** [comment]
> What else can i provide to debug this?

what is your backend S3 implementation here?

**Comment by solracsf** [comment]
Scaleway, Wasabi and Filebase. All 3 present this issue by simply changing endpoint+credentials.

**Comment by harshavardhana** [comment]
> Scaleway, Wasabi and Filebase. All 3 present this issue by simply changing endpoint+credentials

Just checked with AWS S3 seems to work fine and even MinIO as the S3 gateway. 

> `for i in {1..10}; do curl -o /dev/null http://10.1.0.10:9000/s/aeiufb/download; done`

```
~  for i in {1..10}; do curl -o /dev/null http://localhost:9000/harshavardhana/mc; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0  7816k      0  0:00:02  0:00:02 --:--:-- 7812k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   141M      0 --:--:-- --:--:-- --:--:--  142M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   139M      0 --:--:-- --:--:-- --:--:--  139M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   127M      0 --:--:-- --:--:-- --:--:--  128M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   124M      0 --:--:-- --:--:-- --:--:--  124M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   132M      0 --:--:-- --:--:-- --:--:--  132M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   124M      0 --:--:-- --:--:-- --:--:--  124M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   132M      0 --:--:-- --:--:-- --:--:--  132M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   133M      0 --:--:-- --:--:-- --:--:--  133M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0   129M      0 --:--:-- --:--:-- --:--:--  129M
```

```
~  MINIO_CACHE="on" MINIO_CACHE_DRIVES="/home/harsha/minio" MINIO_CACHE_EXPIRY=30 MINIO_CACHE_QUOTA=60 MINIO_CACHE_AFTER=0 MINIO_CACHE_WATERMARK_LOW=80 MINIO_CACHE_WATERMARK_HIGH=95 minio gateway s3
```

```
~ du -sh /home/harsha/minio
19M     /home/harsha/minio
```

How much storage do you have at `/var/cache/minio` ?

**Comment by solracsf** [comment]
> Cache Capacity: 51 GiB Free, 72 GiB Total

**Comment by harshavardhana** [comment]
@acsfer I can't seem to reproduce it - seems to work fine 

> Cache Capacity: 240 GiB Free, 429 GiB Total

also, why did you remove your comments about the server logs? - can you share the logs that are related to MinIO?

**Comment by solracsf** [comment]
Comments were related to another instance (I've just messed terminal windows...).

No logs are produced by minio when executing `for i in {1..10}...`
But i know cache isn't being hit because all traffic goes trough the public iface, not the private.

**Comment by harshavardhana** [comment]
> Comments were related to another instance (I've just messed terminal windows...).
> 
> No logs are produced by minio when executing `for i in {1..10}...`
> But i know cache isn't being hit because all traffic goes trough the public iface, not the private.

If there are no logs then it means that there is no error here,  I am not sure how it can happen here most probably because you don't have enough cache 

> MINIO_CACHE="on"
> MINIO_CACHE_DRIVES="/var/cache/minio"
> MINIO_CACHE_EXPIRY=30
> MINIO_CACHE_QUOTA=60
> MINIO_CACHE_AFTER=0
> MINIO_CACHE_WATERMARK_LOW=80
> MINIO_CACHE_WATERMARK_HIGH=95

have you tried changing these parameters? `MINIO_CACHE_QUOTA=90` ?

**Comment by solracsf** [comment]
Well, I've just tested the same settings with AWS and...it just works.

I believe that poor S3 implementation are causing this, just like #11188 ? Are there any API methods needed to be supported by S3 compatible services for this to work? Or will it just work with AWS?

**Comment by harshavardhana** [comment]
> I believe that poor S3 implementation are causing this, just like #11188 ? Are there any API methods needed to be supported by S3 compatible services for this to work? Or will it just work with AWS?

We only test with AWS S3, GCS and MinIO - I can't comment on what is missing with other vendors.

**Comment by harshavardhana** [comment]
> Well, I've just tested the same settings with AWS and...it just works.
> 

Closing this issue anyways.
