### ISSUE TITLE
http2: Transport received Server's graceful shutdown GOAWAY

### ISSUE THREAD

**Issue by solracsf** [minio/minio#11188]
- Ubuntu 20.04
- minio version RELEASE.2020-12-29T23-29-29Z

I've set up a S3 gateway to https://docs.filebase.com/platform-overview/s3-compatible-api but i'm getting errors while uploading files:

```
API: PutObjectPart(bucket=bucket, object=urn:oid:570)
Time: 13:21:51 CET 12/30/2020
DeploymentID: 1c037082-f801-4b24-be60-4c72c3d616bc
RequestID: 16557DEFD631C280
RemoteHost: 10.1.0.5
Host: 10.1.0.10:9000
UserAgent: aws-sdk-php/3.133.27 GuzzleHttp/6.5.1 curl/7.68.0 PHP/7.4.13
Error: Put "https://s3.filebase.com/bucket/urn%3Aoid%3A570?partNumber=1&uploadId=2~uvSggBZwNQzTybmoP4LSoB07-P85jdg":
http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written;
define Request.GetBody to avoid this error (*url.Error)
       4: cmd/api-errors.go:2015:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2040:cmd.toAPIError()
       2: cmd/object-handlers.go:2284:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```
or
```
API: PutObjectPart(bucket=bucket, object=urn:oid:5580)
Time: 14:43:26 CET 12/30/2020
DeploymentID: 4d9ff7ce-41e7-404d-8bec-7883975869ed
RequestID: 1655825591A56C6D
RemoteHost: 10.1.0.16
Host: 10.1.0.10:9000
UserAgent: aws-sdk-php/3.133.27 GuzzleHttp/6.5.1 curl/7.68.0 PHP/7.4.13
Error: Put "https://s3.filebase.com/bucket/urn%3Aoid%3A5580?partNumber=16&uploadId=2~rGY4uYvgTWgFfhK58pQoYBPszntw-HB":
stream error: stream ID 1765; PROTOCOL_ERROR (*url.Error)
       4: cmd/api-errors.go:2015:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2040:cmd.toAPIError()
       2: cmd/object-handlers.go:2284:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
This is because the backend incorrectly implements HTTP2 protocol @acsfer our S3 gateway works fine with GCS S3 APi and AWS S3

**Comment by solracsf** [comment]
OK, I've followed your answer to them. Is there any way to force HTTP/1.1?

**Comment by harshavardhana** [comment]
> OK, I've followed your answer to them. Is there any way to force HTTP/1.1?

Its for server to negotiate, we attempt HTTP2 if server doesn't support they can fall back to HTTP 1.1

**Comment by acejam** [comment]
@harshavardhana I trust that MinIO works fine with GCS and AWS S3 API's, but can you comment further on what you mean by:

> This is because the backend incorrectly implements HTTP2 protocol

**Comment by harshavardhana** [comment]
> > This is because the backend incorrectly implements HTTP2 protocol

The reason you get GOAWAY like messages is when the backend server is not handling the HTTP2.0 requests properly, prematurely closing connections. 

Filebase S3 API is not well known and may have bugs of their own.

**Comment by solracsf** [comment]
As per #11187 I believe poor S3 API implementations (API, server configurations...) are causing these issues.

The same application backed by an AWS S3 bucket just works out of the box for the same usage...a lot more expensive, but a lot more reliable too 😿
