### ISSUE TITLE
MinIO disks_offline and disks_total in Prometheus monitoring

### ISSUE THREAD

**Issue by DAGorchakov** [minio/minio#11196]
Hello, I have minio cluster with 5 nodes and 2 disks for each. I try to monitor it with the help of /minio/prometheus/metrics.  

## Expected Behavior
if one or more disk is unreachable in `mc info` I want to see it in prometheus\grafana\alertmanager

## Current Behavior
![prom_minio_monitoring](https://user-images.githubusercontent.com/17656075/103402665-91334f00-4b5e-11eb-843e-8a85bae0b913.jpg)

## Possible Solution
Just want to know if it is a bug. is it possible to see this info in /minio/prometheus/metrics?

## Steps to Reproduce (for bugs)
```
Minio start command: /usr/local/bin/minio server https://minio-0{1...5}.domain.com/var/minio/data{1...2}
Environment variables: 
MINIO_ACCESS_KEY=abc
MINIO_SECRET_KEY=12345678
MINIO_PROMETHEUS_AUTH_TYPE="public"
```

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-12-29T23-29-29Z
* Operating System and version (`uname -a`): NAME="Red Hat Enterprise Linux Server" VERSION="7.9 (Maipo)" Linux minio-01 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
Thanks for reporting this. I will send a fix for this.

**Comment by vadmeste** [comment]
@harshavardhana the reason for this issue is that we don't ping disks anymore as we used before. StorageInfo() is not used in health check anymore, I guess we can make it more costly and read from disks.

Also xl-storage has IsOnline which is always returning true maybe we can modify it as well

**Comment by vadmeste** [comment]
Actually, StorageInfo is regularly called by Prometheus

**Comment by harshavardhana** [comment]
@DAGorchakov how is your disk offline can you provide --json output of `mc admin info` ?
