### ISSUE TITLE
Metadata errors that are unable to be repaired via mc or automatically.

### ISSUE THREAD

**Issue by zenjabba** [minio/minio#11191]
<7>DEBUG : zd-ebooks/ebooks/Books_English/: ReadDirAll: 
<7>DEBUG : pacer: low level retry 1/10 (error RequestError: send request failed
caused by: Get "https://zendrives3.digitalmonks.org/zd-ebooks?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=ebooks%2FBooks_English%2F": net/http: timeout awaiting response headers)
<7>DEBUG : pacer: low level retry 2/10 (error RequestError: send request failed

2020/12/31 02:36:12 NOTICE: Halifax - Retribution (2020)/Season 01/Halifax - Retribution (2020) - S01E05 - Episode 5 [ HDTV-1080p h264 AC3 5.1 ]-CBFM.mkv: Failed to read metadata: ServiceUnavailable: Service Unavailable
        status code: 503, request id: 1655AC8F13445CC6, host id:

## Expected Behavior

Not getting a timeout nor failed to read metadata. This locks up access to the S3 bucket for $timeout locking remote system

## Possible Solution

We are trying to use the `mc admin heal` but get errors such as

 ◒  [disk-format]
    0/0 objects; 0 B in 3s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 1 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
mc: <ERROR> Unable to display heal status. Heal had an error - Storage resources are insufficient for the read operation.
 (1) admin-heal.go:256 cmd.mainAdminHeal(..) Tags: [block2, {
 "summary": "stopped",
 "detail": "Storage resources are insufficient for the read operation.",
 "startTime": "2020-12-31T03:06:39.304359059Z",
 "settings": {
  "recursive": true,
  "dryRun": false,
  "remove": false,
  "scanMode": 0
 }
}]
 (0) admin-heal.go:256 cmd.mainAdminHeal(..)
 Release-Tag:RELEASE.2020-12-18T10-53-53Z | Commit:d0e1456be34f | Host:jumpbox | OS:linux | Arch:amd64 | Lang:go1.15.6 | Mem:3.5 MB/74 MB | Heap:3.5 MB/67 MB.
root@jumpbox:~# mc admin heal block2 -r --debug

● Admin Info ... ✔
unable to obtain health information: This 'admin' API is not supported by server in 'mode-server-distributed-xl'

Trace Logs

03:14:41.095 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E11 - Episode 11 - HDTV-1080p-thumb.jpg 2a0e              114.463ms    ↑ 190 B ↓ 942 B
03:14:41.094 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E05 - Episode 5 - HDTV-1080p.nfo 2a0e              131.052ms    ↑ 190 B ↓ 928 B
03:14:41.094 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E02 - Episode 2 - HDTV-1080p-thumb.jpg 2a0e              162.317ms    ↑ 190 B ↓ 939 B
03:14:41.094 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E05 - Episode 5 - HDTV-1080p-thumb.jpg 2a0e              510.277ms    ↑ 190 B ↓ 940 B
03:14:41.094 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E03 - Episode 3 - HDTV-1080p-thumb.jpg 2a0e              511.43ms     ↑ 190 B ↓ 940 B
03:14:41.092 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E06 - Episode 6 - HDTV-1080p-thumb.jpg 2a0e              520.359ms    ↑ 190 B ↓ 940 B
03:14:41.114 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E12 - Episode 12 - HDTV-1080p-thumb.jpg 2a0e              501.241ms    ↑ 190 B ↓ 942 B
03:14:41.094 [503 Service Unavailable] s3.GetObject zendrives3.digitalmonks.org/zd-anime/tv/anime/Dimension High School (2019) [356310]/Season 01/Dimension High School - S01E08 - Episode 8 - HDTV-1080p-thumb.jpg 2a0e              522.596ms    ↑ 190 B ↓ 940 B

## Context

We are trying to repair the metadata on the drives that have been corrupted so we can look to upgrade. We are currently stuck on  Version: 2020-10-27T04:03:55Z because when we tried to upgrade to RELEASE.2020-12-26T01-35-54Z we had a unavailable system due to what looks like IAM errors
and minio spent over 36 hours trying to repair something that it couldn't

## Your Environment

Version: 2020-10-27T04:03:55Z

12 Nodes with 16 Disks in each node, 128GB RAM and 32 cores in each system

Linux zdstore-block2-node1 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Version: 2020-10-27T04:03:55Z

Upgrade to latest @zenjabba and let us know - also purge the content at `rm -rf /drives/.minio.sys/config/iam`

**Comment by zenjabba** [comment]
We tried updating to RELEASE.2020-12-26T01-35-54Z and couldn't get it to work

**Comment by harshavardhana** [comment]
> We tried updating to RELEASE.2020-12-26T01-35-54Z and couldn't get it to work

Purge everything in `drives/.minio.sys/config` and restart the servers.

**Comment by zenjabba** [comment]
15:43:03.999 [403 Forbidden] internal.Lock zdstore-block2-node4.digitalmonks.local:9000/minio/lock/v4/lock?owner=zdstore-block2-node1.digitalmonks.local%3A9000&quorum=3&source=%5Bdata-crawler.go%3A80%3ArunDataCrawler%28%29%5D&uid=a9565293-9a77-4e69-be67-0d31b9a202ac  192.168.0.80      59µs        ↑ 89 B ↓ 156 B
15:43:04.000 [403 Forbidden] internal.Lock zdstore-block2-node2.digitalmonks.local:9000/minio/lock/v4/lock?owner=zdstore-block2-node1.digitalmonks.local%3A9000&quorum=3&source=%5Bdata-crawler.go%3A80%3ArunDataCrawler%28%29%5D&uid=a9565293-9a77-4e69-be67-0d31b9a202ac  192.168.0.80      49µs        ↑ 89 B ↓ 156 B
15:43:03.930 [200 OK] internal.DeleteFile zdstore-block2-node8.digitalmonks.local:9000/minio/storage/mnt/disk3/v22/deletefile?disk-id=15960034-0193-4141-90e7-b5e830eea546&file-path=buckets%2Fzd-ebooks%2F.metacache%2Fd77063e8-5815-4b8b-9d1f-539754a32547&recursive=true&volume=.minio.sys  192.168.0.88      68.399ms     ↑ 58 B ↓ 0 B
15:43:04.001 [403 Forbidden] internal.Lock zdstore-block2-node3.digitalmonks.local:9000/minio/lock/v4/lock?owner=zdstore-block2-node1.digitalmonks.local%3A9000&quorum=3&source=%5Bdata-crawler.go%3A80%3ArunDataCrawler%28%29%5D&uid=a9565293-9a77-4e69-be67-0d31b9a202ac  192.168.0.80      190µs       ↑ 89 B ↓ 156 B

**Comment by zenjabba** [comment]
Deleted those folders, upgraded to latest version, still getting internal. 403 Forbidden. I also confirmed that ownership of the file system is correct.

another new example

`15:45:59.680 [403 Forbidden] internal.CreateFile zdstore-block2-node12.digitalmonks.local:9000/minio/storage/mnt/disk10/v22/createfile?disk-id=5c0499d9-8975-41f1-8fa6-e923a8cef7ec&file-path=bfae5b94-4b13-4ea1-ae5e-e9814df124c4%2Fd958c24b-60e9-4ed7-99fb-41651e7db3d3%2Fpart.1&length=-1&volume=.minio.sys%2Ftmp  192.168.0.125     115.352ms    ↑ 103 B ↓ 186 B`

**Comment by zenjabba** [comment]
https://transfer.digitalmonks.org/DUfHk/miniologs.logs

full admin error logs for ~50 seconds
