### ISSUE TITLE
Restore regular object Symlink Support in NAS Gateway

### ISSUE THREAD

**Issue by mikelococo** [minio/minio#11203]
**Is your feature request related to a problem? Please describe.**
https://github.com/minio/minio/pull/9457 removed support for all symlinks in the filesystem backend(s) used by the nas gateway functionality in order to resolve https://github.com/minio/minio/issues/9419. However, this is an extremely course-grained solution that reduces the value of the nas gw tremendously. There are other behaviors that would retain much of the value of the previous behavior while reducing a great deal of the risk.

**Describe the solution you'd like**
Minimally, allow file symlinks and disallow only directory symlinks. The edge-cases to consider with file symlinks are much simpler, and there is a broadly accepted approach for translating the behavior of POSIX symlinks into APIs that don't support that behavior... which is to make them behave as hardlinks by:

- Resolve the file symlink for reads
- For deletes, delete the file symlink but not the real file to which the symlink points

This approach is used by the [lighttpd webdav module](https://redmine.lighttpd.net/projects/1/wiki/Docs_ModWebDAV#symlinks) and by [samba (see the "Links" heading)](https://www.samba.org/samba/docs/using_samba/ch08.html)

**Describe alternatives you've considered**
For files, hardlinks can be used but don't support any filesystem that has pre-existing symlinks.

For directory symlinks (which are admittedly more complex and which Lighttpd's webdav module also punted on) and more generally for the use-case of constructing a virtual view of a filesystem, alternatives are particularly dire:

- Docker volumes and other types of bind mounts can't be used to construct a virtual view of the filesystem due to https://github.com/minio/minio/issues/5080#issuecomment-375104140
- Symlinks can't be used to construct a virtual view of the filesystem due to this issue.

Having SOME facility by which a virtual filesystem view can be created is quite useful in a variety of circumstances.

**Additional context**
In the event this bug is closed wontfix or until it is resolved, a workaround is to use [bindfs](https://bindfs.org/) with [--resolve-symlinks and --resolved-symlink-deletion=symlink-only](https://bindfs.org/docs/bindfs-help.txt) to construct virtual views of the filesystem. One constructs a symlinked view of the filesystem that they want to serve via minio, and then uses bindfs to mount it in a way that lies to minio about the symlinks, making them appear to be "real" files.

I have not deeply tested the safety of this config, and it definitely has the potential to reintroduce https://github.com/minio/minio/issues/9419 and other bugs like it but my prediction is that:
- It's safe for all reads and lists, on objects that correspond to symlinks pointing to files and on objects that correspond to files inside of symlinked directories
- All operations are safe on objects that correspond to file-symlinks, and the behavior as observed by minio clients will be identical to what they would see if hard links were used.
- Deletes of objects within a symlinked directory might be dangerous, depending on the detailed behaviors of bindfs around atomicity and empty checks.

However, provided one is able to guarantee either technically or by policy (with a recovery plan should the policy be violated) that either symlinked directories won't be used or that files inside symlinked directories won't be deleted, bindfs can restore some symlink functionality by eliding their existence from minio.

**Comment by harshavardhana** [comment]
@mikelococo the time has passed for this, and we have no customers who need this and have asked for it.

Feel free to fork MinIO and add this support yourself

Unfortunately we are not taking any new feature requests on gateway implementations anymore. 

If you wish to force our roadmap items feel free to become our customer https://min.io/pricing

**Comment by vpal** [comment]
This is a very valid request. We are struggling with the same issue and are because of this are not able to update MinIO any more.
Symlink support is really a very essential feature of Linux filesystems and provides great amount of flexibility.
Also given the fact that MinIO uses rename to ensure atomicity leaves nas gateway users with actually no flexibility when constructing directory layouts.

A switch to turn on followsymlinks for the people who know what they are doing would be really useful.

**Comment by harshavardhana** [comment]
> This is a very valid request. We are struggling with the same issue and are because of this are not able to update MinIO any more.
> Symlink support is really a very essential feature of Linux filesystems and provides great amount of flexibility.
> Also given the fact that MinIO uses rename to ensure atomicity leaves nas gateway users with actually no flexibility when constructing directory layouts.
> 
> A switch to turn on followsymlinks for the people who know what they are doing would be really useful.

You are free to fork MinIO and restore the support @vpal

**Comment by vpal** [comment]
@harshavardhana would you maybe also accept a PR that readds this functionality as optional by default being turned off?

**Comment by harshavardhana** [comment]
> @harshavardhana would you maybe also accept a PR that readds this functionality as optional by default being turned off?

@vpal as stated this is not something we wish to keep in the code base and it's out of scope for us at the moment.

**Comment by harshavardhana** [comment]
> **Describe the solution you'd like**
> Minimally, allow file symlinks and disallow only directory symlinks. The edge-cases to consider with file symlinks are much simpler, and there is a broadly accepted approach for translating the behavior of POSIX symlinks into APIs that don't support that behavior... which is to make them behave as hardlinks by:
> 
> * Resolve the file symlink for reads
> * For deletes, delete the file symlink but not the real file to which the symlink points

We have decided to implement this behavior.
