### ISSUE TITLE
Dummy PutObjectAcl call supported but can't be specified in policy

### ISSUE THREAD

**Issue by mattcg** [minio/minio#11235]
Minio will not allow you to add a policy with s3:PutObjectAcl in the actions, but a dummy handler for the method does exist (introduced in https://github.com/minio/minio/commit/712e82344c2fa32647ddbb6be68603e6942f1e6a). This results in confusing behaviour. The Discourse application will fail to create uploads when it attempts to PutObjectAcl, if the policy currently applied in Minio only explicitly specifies the actions allowed by Minio in policies. However, if you set the allowed policies to "s3:*", calls to the dummy PutObjectAcl method will succeed and Discourse will not throw a fit.

## Expected Behavior
Minio will allow policies with PutObjectAcl and GetObjectAcl.

## Current Behavior
Minio does not allow policies with PutObjectAcl and GetObjectAcl.

## Possible Solution
Allow PutObectAcl and GetObjectAcl in policies.

## Steps to Reproduce (for bugs)
Attempt to add a policy, using for example `mc admin policy add minio-cloud user /path-to-the-file/user.json`, that includes PutObjectAcl and/or GetObjectAcl in the allow list.

## Context
This issue can be worked around by changing the allowed actions to "s3:*". However, the behaviour is confusing for users Minio (the action is not allowed in policies but is in fact supported in a dummy way).

## Regression
no

**Comment by harshavardhana** [comment]
It is supported to satisfy some applications, which do not handle the ACL calls retuning NotImplemented 

We have no intention to implement ACLs, ACL APIs are legacy you should be IAM policies to manage authorization.

**Comment by harshavardhana** [comment]
> Attempt to add a policy, using for example `mc admin policy add minio-cloud user /path-to-the-file/user.json`, that includes PutObjectAcl and/or GetObjectAcl in the allow list.

As a workaround use `s3:PutBucketPolicy` and `s3:GetBucketPolicy` which would help you to not allow all actions for the user.
