### ISSUE TITLE
Can't get storage info by mc command: Using my my own released version.

### ISSUE THREAD

**Issue by LawyZheng** [minio/minio#11241]
I am a rookie developer and barely know about React and Golang.
I just want to study Golang through the MinIO source code. 
But I got an error, how can I fix it? Thanks a lot.

## Expected Behavior

I want to use `mc admin info myminio` to get info about my cloud storage, but got an error like this: 
>mc: <ERROR> Unable to get service status. Failed to parse server response: invalid character '<' looking for beginning of value

## Current Behavior

I tried to release my own test version. So I just ran the command `make` to build my own version, and got my binary file.
Luckily, the file could be executed normally. I could access it with the browser and the command-line.
But when I use `mc admin info myminio`, I got an error like this: 
> mc: <ERROR> Unable to get service status. Failed to parse server response: invalid character '<' looking for beginning of value.

## Steps to Reproduce (for bugs)

1. modify the HTML code
2. run `npm run release` to get `ui-assets.go`
3. run `make` to build and get a new executable file.
4. replace the old executable with the new one.
5. run `minio server`

## Context

--

## Regression

--

## Your Environment

* Version used (`minio --version`): 
> mc: mc version RELEASE.2021-01-05T05-03-58Z
> minio : modified by the commit `eb9172eecb985da13a814533490f274c5a5e83fa`
* Server setup and configuration: -
* Operating System and version (`uname -a`): Windows Server 2019 x86_64

**Comment by harshavardhana** [comment]
> > mc:  Unable to get service status. Failed to parse server response: invalid character '<' looking for beginning of value.

This means you need to upgrade your `mc`

**Comment by LawyZheng** [comment]
> > > mc:  Unable to get service status. Failed to parse server response: invalid character '<' looking for beginning of value.
> 
> This means you need to upgrade your `mc`

I have updated my mc already. Now my mc version is `mc version RELEASE.2021-01-05T05-03-58Z` 
I tried to run `mc update`, and got `You are already running the most recent version of ‘mc’.You are already running the most recent version of ‘mc’.`
