### ISSUE TITLE
2020.06.22-031250 to 2021.01.05-052238 upgrade data usage recalculates on every run

### ISSUE THREAD

**Issue by pruiz** [minio/minio#11246]
Hi,

We have a 10 node cluster, using erasure sets, and it has been giving weird outputs on 'mc admin info' wrt online drives, used space, etc. 

After inspecting it a little bit, we found a WRITE lock for .minio.sys/runDataCrawler.lock, which appeared to be stale/stuck:

```
BayMax:mc pruiz$ ./mc admin top locks --json --count 1   arkive
{
 "status": "success",
 "locks": {
  "time": "2021-01-07T00:28:01.391838626Z",
  "resource": ".minio.sys/runDataCrawler.lock",
  "type": "WRITE",
  "source": "[data-crawler.go:76:runDataCrawler()]",
  "serverlist": [
   "arkive-01:9000",
   "arkive-02:9000",
   "arkive-03:9000",
   "arkive-04:9000",
   "arkive-05:9000",
   "arkive-07:9000",
   "arkive-09:9000",
   "arkive-10:9000",
   "arkive-08:9000"
  ],
  "owner": "arkive-06:9000",
  "id": "1e934275-bf88-483a-be2c-73c78793b0ad",
  "quorum": 6
 }
}
```

We've even tried to stop the node owning the lock (arkive-06), but the lock wont go away anyway.

Is this an expected behaviour? shouln't another node take over the leader role and reinitiate data crawling when the actual crawler node is stopped?

## Expected Behavior

We expected the lock to go away, and the crawling process to be re-started at another node.

## Current Behavior

.minio.sys/runDataCrawler.lock is still there even an hour after stopping the node holding it.

## Steps to Reproduce (for bugs)

We don't know how this happened on the first place.

## Context

10 node distributed cluster with 120 disks as erasure sets, with usage details (as seen at 'mc admin info') flapping: for example some times all used space is reported correctly (ie. 71TB used), a few minutes later usage space changes to 4.5TB, then a few minutes later it is back to 71TB.. or any intermediate amount. The same issue happens wrt objects count, it keeps changing pseudo-randomly.

Otherwise, the cluster is working properly, data can be read/written, etc.

## Regression

This happened after upgrading from 2020.06.22-031250 to 2021.01.05-052238, so it is probably a regression of some sort.

## Your Environment

* minio version RELEASE.2021-01-05T05-22-38Z
* 10 node distributed cluster, 12 disk per node, using erasure sets.
* Linux arkive-xx 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@pruiz crawler always needs to run and it always runs all the time so it is correct that it is running. 

> We expected the lock to go away, and the crawling process to be re-started at another node.

It won't go away it is always chosen to be one node in its lifetime until that node is restarted. 

> 10 node distributed cluster with 120 disks as erasure sets, with usage details (as seen at 'mc admin info') flapping: for example some times all used space is reported correctly (ie. 71TB used), a few minutes later usage space changes to 4.5TB, then a few minutes later it is back to 71TB.. or any intermediate amount. The same issue happens wrt objects count, it keeps changing pseudo-randomly.

This is happening because you didn't upgrade all your servers properly, are you sure all your servers are running same version ? 

> Is this an expected behaviour? shouln't another node take over the leader role and reinitiate data crawling when the actual crawler node is stopped?

It gets cleared if the owner is gone, after a while when the expiry routine kicks in.

**Comment by pruiz** [comment]
Hi @harshavardhana 

The upgrade was performed by stopping all nodes, replacing the binary, then starting them again.

Also, all nodes are running the same version:

```
BayMax:SignServerDocker pruiz$ mc admin info  arkive |grep Version:
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
   Version: 2021-01-05T05:22:38Z
```

**Comment by pruiz** [comment]
Also i've found some of this errors while inspecting logs:

```
Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: API: SYSTEM()
Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: Time: 21:22:31 UTC 01/06/2021
Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: DeploymentID: 419bc9e4-c53b-45ef-947d-e3395d3cb957
Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: Error: Operation timed out (cmd.OperationTimedOut)
Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: 1: cmd/erasure.go:309:cmd.erasureObjects.crawlAndGetDataUsage.func1()
```

**Comment by harshavardhana** [comment]
> Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: API: SYSTEM()
> Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: Time: 21:22:31 UTC 01/06/2021
> Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: DeploymentID: 419bc9e4-c53b-45ef-947d-e3395d3cb957
> Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: Error: Operation timed out (cmd.OperationTimedOut)
> Jan 06 21:22:31 arkive-06.ono.ter0.com minio[6139]: 1: cmd/erasure.go:309:cmd.erasureObjects.crawlAndGetDataUsage.func1()

This is completely different @pruiz

**Comment by pruiz** [comment]
Even after restarting the whole cluster again, summary from 'mc admin info' keeps changing (rotating?) with values like:

```
54 TiB Used, 27 Buckets, 25,718 Objects
120 drives online, 0 drives offline
```

Then, a few minutes later:

```
4.3 TiB Used, 20 Buckets, 5,410 Objects
120 drives online, 0 drives offline
```

And some time later it will be back at 54TB.. (or any other value) before returning to 4.3TB, etc.

**Comment by harshavardhana** [comment]
Do you have objects with proper prefixes? how are your objects spread out?

**Comment by harshavardhana** [comment]
Most probably an issue of an upgrade here due to `2020.06.22-031250` since we changed the backend format.

**Comment by pruiz** [comment]
@harshavardhana  not sure what do you mean with 'proper prefixes', but our distributed setup is as three zones, of 4 disks across 10 nodes: http://arkive-{01...10}/srv/disk{1...4} http://arkive-{01...10}/srv/disk{5...8} http://arkive-{01...10}/srv/disk{9...12}

**Comment by pruiz** [comment]
@harshavardhana just let me know if I can provide additional diag/debug info.. (also I will stay at slack for a while, just in case)

**Comment by harshavardhana** [comment]
> We've even tried to stop the node owning the lock (arkive-06), but the lock wont go away anyway.

This I found a way to address, upgrade will test separately.

**Comment by pruiz** [comment]
Found a new kind of error at logs:

```
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: API: SYSTEM()
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: Time: 22:52:58 UTC 01/07/2021
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: DeploymentID: 419bc9e4-c53b-45ef-947d-e3395d3cb957
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: Error: cache version deprecated (will autoupdate) (*errors.errorString)
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 3: cmd/logger/logonce.go:93:logger.LogOnceIf()
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 2: cmd/data-usage-cache.go:483:cmd.(*dataUsageCache).load()
Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 1: cmd/erasure.go:345:cmd.erasureObjects.crawlAndGetDataUsage.func2()
```

**Comment by harshavardhana** [comment]
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: API: SYSTEM()
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: Time: 22:52:58 UTC 01/07/2021
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: DeploymentID: 419bc9e4-c53b-45ef-947d-e3395d3cb957
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: Error: cache version deprecated (will autoupdate) (*errors.errorString)
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 3: cmd/logger/logonce.go:93:logger.LogOnceIf()
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 2: cmd/data-usage-cache.go:483:cmd.(*dataUsageCache).load()
> Jan 07 22:52:58 arkive-06.ono.ter0.com minio[6139]: 1: cmd/erasure.go:345:cmd.erasureObjects.crawlAndGetDataUsage.func2()

Correct this is why it's rescanning from the beginning, but I think this will go on until perhaps for 

```
54 TiB Used, 27 Buckets, 25,718 Objects
```

27 buckets as the new cycles get updated.

**Comment by pruiz** [comment]
humm.. well in that case it may take quite a while as the original details where '71TB, 27 buckets & 830k+ objects'..

**Comment by pruiz** [comment]
What I am unable to find in code is where the stated timeout occurs.. I was trying to find if there any tunable I can set as to allow for an increased timeout, just in case.. :?

**Comment by harshavardhana** [comment]
> humm.. well in that case it may take quite a while as the original details where '71TB, 27 buckets & 830k+ objects'..

Yes, but it won't be that long @pruiz 

> What I am unable to find in code is where the stated timeout occurs.. I was trying to find if there any tunable I can set as to allow for an increased timeout, just in case.. :?

There is no tunable for such things, it is an owner-less lock which the server has to clear - it automatically does in 30secs - needs the PR #11247

**Comment by pruiz** [comment]
I've tuned (temporarily) heal parameters as (max_sleep=100ms max_io=100) and crawler (delay=0),.. and I'll wait a few hours, while keeping an eye, to see how it goes.

**Comment by pruiz** [comment]
@harshavardhana there is another thing which seems weird, periodically I see the following log entry:

```
minio: <DEBUG> dataUpdateTracker: Saving: 157121 bytes, Current idx: 53330
```

However, even if the log is from hours apart, the number of bytes and the 'current idx' values state the same, it's like something is stuck and never updating..

**Comment by harshavardhana** [comment]
> @harshavardhana there is another thing which seems weird, periodically I see the following log entry:
> 
> ```
> minio: <DEBUG> dataUpdateTracker: Saving: 157121 bytes, Current idx: 53330
> ```
> 
> However, even if the log is from hours apart, the number of bytes and the 'current idx' values state the same, it's like something is stuck and never updating..

That is a bloom filter it has nothing to do with your actual usage. Also you should never enable these debug messages - I don't know why are you enabling this  - it may just confuse you.

**Comment by pruiz** [comment]
I guess there is some kind of bloom filter in use to speed up searches for space usage details.. I am just trying to understand what is going on..

**Comment by harshavardhana** [comment]
> I guess there is some kind of bloom filter in use to speed up searches for space usage details.. I am just trying to understand what is going on..

bloom filter is used to pick the prefixes to be used for newer usage cycles so that we don't have to keep scanning previous prefixes that have been already scanned.

**Comment by pruiz** [comment]
After a while the info reached the right counters:

```
71 TiB Used, 28 Buckets, 871,906 Objects
120 drives online, 0 drives offline
```

But five minutes later, it went back to where it started:

```
4.3 TiB Used, 20 Buckets, 5,552 Objects
120 drives online, 0 drives offline
```

This seems looped somehow.

**Comment by harshavardhana** [comment]
Re-opening to verify the upgrade scenarios here

**Comment by pruiz** [comment]
@harshavardhana I've noted something curious.

If the cluster has not traffic (ie. it is cordoned from service), the summary data from 'admin info', does not change, and always shows wrong data (4.5TB, etc.)..

However, if we generate/allow some traffic against the cluster, the counters start updating incrementally, until it reaches the real values.. however always it cicles back to 4.5TB.

I am yet to narrow what kind of requests allow for counters to start updating. But, as said, if we forbid any 'client traffic/requests', the counters are wrong and seems to never update/change at all.

**Comment by pruiz** [comment]
What keeps poping up in our logs periodically are this Timeout errors, from two different sources..

* cmd/erasure.go:309:

```
Jan 08 13:38:23 arkive-06.ono.ter0.com minio[6139]: API: SYSTEM()
Jan 08 13:38:23 arkive-06.ono.ter0.com minio[6139]: Time: 13:38:23 UTC 01/08/2021
Jan 08 13:38:23 arkive-06.ono.ter0.com minio[6139]: DeploymentID: 419bc9e4-c53b-45ef-947d-e3395d3cb957
Jan 08 13:38:23 arkive-06.ono.ter0.com minio[6139]: Error: Operation timed out (cmd.OperationTimedOut)
Jan 08 13:38:23 arkive-06.ono.ter0.com minio[6139]: 1: cmd/erasure.go:309:cmd.erasureObjects.crawlAndGetDataUsage.func1()
```

* cmd/erasure.go:383:

```
Jan 08 13:36:55 arkive-06.ono.ter0.com minio[6139]: API: SYSTEM()
Jan 08 13:36:55 arkive-06.ono.ter0.com minio[6139]: Time: 13:36:55 UTC 01/08/2021
Jan 08 13:36:55 arkive-06.ono.ter0.com minio[6139]: DeploymentID: 419bc9e4-c53b-45ef-947d-e3395d3cb957
Jan 08 13:36:55 arkive-06.ono.ter0.com minio[6139]: Error: Operation timed out (cmd.OperationTimedOut)
Jan 08 13:36:55 arkive-06.ono.ter0.com minio[6139]: 1: cmd/erasure.go:383:cmd.erasureObjects.crawlAndGetDataUsage.func2()
```

**Comment by klauspost** [comment]
@pruiz This will be fixed by https://github.com/minio/minio/pull/11243

Locks are being kept for outdated data.

**Comment by harshavardhana** [comment]
Fixed sufficiently in #11243 #11247

**Comment by pruiz** [comment]
@harshavardhana I'll update today and let u know, many thnks :)

**Comment by pruiz** [comment]
We've been running 2021.01.08.211821Z for ~11h now, and the stale data/space usage issues look gone now.

@harshavardhana thnks again for your timely help.
