### ISSUE TITLE
MinIO failed to deploy with error log "UUID on positions 0:0 do not match"

### ISSUE THREAD

**Issue by yangwwii** [minio/minio#11259]
We are trying to deploy distributed MinIO(replica:4) via helm3 install on a clean namespace. But it's failed to start the service
sometimes, the issue didn't occur 100% but we happened to see it for several times. We didn't do any healing or pod/node restart.

## Current Behavior

1. Get pods info:
#kubectl --request-timeout 5 get pods --all-namespaces -o wide
beets minio-0 0/1 Running 0 11m 10.1.158.14 worker-1 &lt;none&gt; &lt;none&gt;
beets minio-1 1/1 Running 0 11m 10.1.35.91 worker-6 &lt;none&gt; &lt;none&gt;
beets minio-2 1/1 Running 0 11m 10.1.88.147 worker-5 &lt;none&gt; &lt;none&gt;
beets minio-3 1/1 Running 0 11m 10.1.120.82 worker-3 &lt;none&gt; &lt;none&gt;

2.Describe all minio pods info, the similar log seen on all pods are:
#kubectl describe pods
Name:         minio-0
Volumes:
  export:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  export-minio-0
ReadOnly:   false
Events:
  Type     Reason            Age                    From                          Message
  ----     ------            ----                   ----                          -------
  Warning  FailedScheduling  13m (x2 over 13m)      default-scheduler             running "VolumeBinding" filter plugin for pod "minio-0": pod has unbound immediate PersistentVolumeClaims
3. storage class info:
StorageClass:
Name: network-block
IsDefaultClass: Yes
Annotations: meta.helm.sh/release-name=rook,meta.helm.sh/release-namespace=default,storageclass.kubernetes.io/is-default-class=true
Provisioner: ceph.rook.io/block
Parameters: blockPool=rbd,clusterNamespace=rook-ceph,fstype=xfs
AllowVolumeExpansion: <unset>
MountOptions: <none>
ReclaimPolicy: Delete
VolumeBindingMode: Immediate
Events: <none>

4. all pods container log:

minio-0_minio.log

2020-12-29T18:03:23.448263513Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:23.447770239Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"UUID on positions 0:0 do not match with, expected c64fa3c6-f72e-4517-a887-6e399fb84603 got 3a1c0ac0-2e06-48d4-ab4d-227a542efda5",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:190:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-0.minio-svc.beets.svc.cluster.local:9000/export"}}}
2020-12-29T18:03:23.452062046Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:23.451592638Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"UUID on positions 0:0 do not match with, expected c64fa3c6-f72e-4517-a887-6e399fb84603 got 3a1c0ac0-2e06-48d4-ab4d-227a542efda5",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:190:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-1.minio-svc.beets.svc.cluster.local:9000/export"}}}
2020-12-29T18:03:23.457885829Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:23.457693649Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"UUID on positions 0:0 do not match with, expected c64fa3c6-f72e-4517-a887-6e399fb84603 got 3a1c0ac0-2e06-48d4-ab4d-227a542efda5",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:190:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-3.minio-svc.beets.svc.cluster.local:9000/export"}}}

minio-1_minio.log

2020-12-29T18:03:22.643959881Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:22.643704127Z","message":"Waiting for the first server to format the disks.\n"}
2020-12-29T18:03:23.148768206Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:23.148144018Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"unformatted disk found",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-0.minio-svc.beets.svc.cluster.local:9000/export"}}}
2020-12-29T18:03:23.152693392Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:23.152087481Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"unformatted disk found","source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-2.minio-svc.beets.svc.cluster.local:9000/export"}}}

minio-2_minio.log

2020-12-29T18:03:21.81854535Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:21.81831082Z","message":"Waiting for the first server to format the disks.\n"}
2020-12-29T18:03:22.318105542Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:22.317901053Z","message":"Waiting for the first server to format the disks.\n"}
2020-12-29T18:03:22.822634177Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:22.821931171Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"unformatted disk found",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()"
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-0.minio-svc.beets.svc.cluster.local:9000/export"}}}
2020-12-29T18:03:22.82641947Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:22.825831516Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"unformatted disk found",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-2.minio-svc.beets.svc.cluster.local:9000/export"}}}
2020-12-29T18:03:23.341610988Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:23.341093198Z","message":"Attempting encryption of all config, IAM users and policies on MinIO backend\n"}
2020-12-29T18:03:23.343771637Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:23.343506628Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"Write failed. Insufficient number of disks online",
"source":["/go/src/github.com/minio/minio/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()",
"/go/src/github.com/minio/minio/cmd/xl-v1-object.go:581:cmd.xlObjects.putObject()",
"/go/src/github.com/minio/minio/cmd/xl-v1-object.go:466:cmd.xlObjects.PutObject()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:712:cmd.(*xlSets).PutObject()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:404:cmd.(*xlZones).PutObject()",
"/go/src/github.com/minio/minio/cmd/config-common.go:62:cmd.saveConfig()",
"/go/src/github.com/minio/minio/cmd/config-encrypted.go:312:cmd.migrateConfigPrefixToEncrypted()",
"/go/src/github.com/minio/minio/cmd/config-encrypted.go:109:cmd.handleEncryptedConfigBackend()",
"/go/src/github.com/minio/minio/cmd/server-main.go:191:cmd.initSafeMode()",
"/go/src/github.com/minio/minio/cmd/server-main.go:410:cmd.serverMain()"]}}
2020-12-29T18:03:23.41106833Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:23.410910862Z","message":"Waiting for config backend to be encrypted..\n"}
2020-12-29T18:03:23.595678563Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:23.595325034Z","message":"Attempting encryption of all config, IAM users and policies on MinIO backend\n"}
2020-12-29T18:03:23.598293605Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:23.598096055Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"Write failed. Insufficient number of disks online",
"source":["/go/src/github.com/minio/minio/cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()",
"/go/src/github.com/minio/minio/cmd/xl-v1-object.go:581:cmd.xlObjects.putObject()",
"/go/src/github.com/minio/minio/cmd/xl-v1-object.go:466:cmd.xlObjects.PutObject()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:712:cmd.(*xlSets).PutObject()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:404:cmd.(*xlZones).PutObject()",
"/go/src/github.com/minio/minio/cmd/config-common.go:62:cmd.saveConfig()",
"/go/src/github.com/minio/minio/cmd/config-encrypted.go:312:cmd.migrateConfigPrefixToEncrypted()",
"/go/src/github.com/minio/minio/cmd/config-encrypted.go:109:cmd.handleEncryptedConfigBackend()",
"/go/src/github.com/minio/minio/cmd/server-main.go:191:cmd.initSafeMode()",
"/go/src/github.com/minio/minio/cmd/server-main.go:410:cmd.serverMain()"]}}
2020-12-29T18:03:23.606625468Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:23.606464262Z","message":"Waiting for config backend to be encrypted..\n"}

2020-12-29T18:03:23.653413881Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:23.652630086Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"UUID on positions 0:0 do not match with, expected 3a1c0ac0-2e06-48d4-ab4d-227a542efda5 got c64fa3c6-f72e-4517-a887-6e399fb84603",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:57:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:219:cmd.(*xlSets).connectDisks()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:1510:cmd.(*xlSets).HealFormat()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:1242:cmd.(*xlZones).HealFormat()",
"/go/src/github.com/minio/minio/cmd/background-heal-ops.go:149:cmd.bgHealDiskFormat()",
"/go/src/github.com/minio/minio/cmd/background-heal-ops.go:86:cmd.(*healRoutine).run()"],
"variables":{"endpoint":"https://minio-2.minio-svc.beets.svc.cluster.local:9000/export"}}}

2020-12-29T18:03:23.839668085Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:23.838937525Z","message":"Attempting encryption of all config, IAM users and policies on MinIO backend\n"}

2020-12-29T18:03:25.768784237Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:25.768232346Z",
"api":{"name":"SYSTEM","args":{}},"error":{"message":"Server not initialized, please try again",
"source":["/go/src/github.com/minio/minio/cmd/notification.go:123:cmd.(*NotificationGroup).Go.func1()"],
"variables":{"peerAddress":"minio-0.minio-svc.beets.svc.cluster.local:9000"}}}

2020-12-29T18:03:25.768822642Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:25.768305728Z",
"api":{"name":"SYSTEM","args":{}},"error":{"message":"Server not initialized, please try again",
"source":["/go/src/github.com/minio/minio/cmd/background-heal-ops.go:163:cmd.bgHealDiskFormat()",
"/go/src/github.com/minio/minio/cmd/background-heal-ops.go:86:cmd.(*healRoutine).run()"]}}

2020-12-29T18:03:25.768829018Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:25.76834324Z",
"api":{"name":"SYSTEM","args":{}},"error":{"message":"Server not initialized, please try again",
"source":["/go/src/github.com/minio/minio/cmd/background-heal-ops.go:163:cmd.bgHealDiskFormat()",
"/go/src/github.com/minio/minio/cmd/background-heal-ops.go:86:cmd.(*healRoutine).run()"]}}

2020-12-29T18:03:44.750663176Z 2020/12/29 18:03:44 http: TLS handshake error from 10.1.35.76:43198: remote error: tls: bad certificate

2020-12-29T18:03:47.591763103Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe","level":"ERROR",
"errKind":"MINIO","time":"2020-12-29T18:03:47.59148888Z",
"api":{"name":"SYSTEM","args":{}},
"error":{"message":"Post \"https://minio-0.minio-svc.beets.svc.cluster.local:9000/minio/peer/v6/setbucketlifecycle?bucket=itc\": EOF",
"source":["/go/src/github.com/minio/minio/cmd/notification.go:123:cmd.(*NotificationGroup).Go.func1()"],
"variables":{"peerAddress":"minio-0.minio-svc.beets.svc.cluster.local:9000"}}}

minio-3_minio.log

532194706Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:22.531347796Z","message":"Waiting for the first server to format the disks.\n"}
2020-12-29T18:03:23.028193502Z {"level":"INFO","errKind":"","time":"2020-12-29T18:03:23.027979081Z","message":"Waiting for a minimum of 2 disks to come online (elapsed 1m15s)\n\n"}
2020-12-29T18:03:23.54042324Z {"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:23.540084489Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"UUID on positions 0:0 do not match with, expected 3a1c0ac0-2e06-48d4-ab4d-227a542efda5 got c64fa3c6-f72e-4517-a887-6e399fb84603",
"source":["/go/src/github.com/minio/minio/cmd/prepare-storage.go:50:cmd.glob..func5.1()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:190:cmd.(*xlSets).connectDisksWithQuorum()",
"/go/src/github.com/minio/minio/cmd/xl-sets.go:326:cmd.newXLSets()",
"/go/src/github.com/minio/minio/cmd/xl-zones.go:75:cmd.newXLZones()",
"/go/src/github.com/minio/minio/cmd/server-main.go:459:cmd.newObjectLayer()",
"/go/src/github.com/minio/minio/cmd/server-main.go:379:cmd.serverMain()"],
"variables":{"endpoint":"https://minio-2.minio-svc.beets.svc.cluster.local:9000/export"}}}

2020-12-29T18:03:44.753317624Z 2020/12/29 18:03:44 http: TLS handshake error from 10.1.35.76:43200: remote error: tls: bad certificate

2020-12-29T18:03:47.462508626Z {"deploymentid":"0280ba39-c2a0-4bca-90df-c4bdcba4cefe",
"level":"ERROR","errKind":"MINIO","time":"2020-12-29T18:03:47.462169916Z","api":{"name":"SYSTEM","args":{}},
"error":{"message":"Post \"https://minio-0.minio-svc.beets.svc.cluster.local:9000/minio/peer/v6/setbucketlifecycle?bucket=coredump\": EOF",
"source":["/go/src/github.com/minio/minio/cmd/notification.go:123:cmd.(*NotificationGroup).Go.func1()"],
"variables":{"peerAddress":"minio-0.minio-svc.beets.svc.cluster.local:9000"}}}

## Steps to Reproduce (for bugs)

1, create namespace
2, helm install the helm chart.
3. it failed to upload object to MinIO, and minio readiness failed.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-03-05T01-04-19Z
* Server setup and configuration:  distributed minio with replica number 4
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
This is very old release @yangwwii please upgrade to latest release.

**Comment by yangwwii** [comment]
Hi @harshavardhana , it's hardly to get reproduced. Is there possible Minio pod-0 (with the first disk) allocates the disk UUID for two times in the phase of disk initialization.?

**Comment by harshavardhana** [comment]
> Hi @harshavardhana , it's hardly to get reproduced. Is there possible Minio pod-0 (with the first disk) allocates the disk UUID for two times in the phase of disk initialization.?

@yangwwii we have re-implemented this area of code multiple times and the code diverged a lot - we do not have the context anymore to help you. 

Please upgrade to latest releases and let us know how it goes.

**Comment by yangwwii** [comment]
@harshavardhana Sure, i understood it. will contact you once the issue get reproduced on latest version.
