### ISSUE TITLE
fs/multipart: Error uploading file larger than 8mb

### ISSUE THREAD

**Issue by harel-e** [minio/minio#1125]
Hello,

First of all, thanks for this wonderful utility.
I tried to upload a file of size 9mb using aws cli and got the following error 

aws --endpoint-url http://localhost:9000 s3 cp ./largeFile s3://test2/
upload failed: ./largeFile to s3://test2/largeFile
Connection was closed before we received a valid response from endpoint URL: "http://localhost:9000/test2/largeFile?uploadId=gbE6BU1ugVLBKxx6DjiGbmL3XGZcd_i5SrDLaxJKEvabH2o".

The output from Minio process is shown below
Uploading 8mb and below worked fine.

Environment:

MacOS 10.11.3
Minio: version 2016-02-08T00:13:11Z
aws: aws-cli/1.10.4 Python/2.7.11 Darwin/15.3.0 botocore/1.3.26

Thanks,
Harel

Minio Log

2016/02/14 08:59:24 http: panic serving [::1]:55938: runtime error: index out of range
goroutine 70 [running]:
net/http.(_conn).serve.func1(0xc82004a000, 0xf40050, 0xc820222070)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1287 +0xb5
github.com/minio/minio/pkg/fs.doPartsMatch(0xc8203dfce0, 0x3, 0x4, 0xc820238f50, 0x2, 0x2, 0xc82039cfa0)
    /Users/harsha/mygo/src/github.com/minio/minio/pkg/fs/fs-multipart.go:126 +0x1b9
github.com/minio/minio/pkg/fs.Filesystem.CompleteMultipartUpload(0x7fff5fbffc8f, 0xa, 0x5, 0xc8201829c0, 0xc820182720, 0xc8201827c0, 0xc8200704e0, 0xc820070540, 0xc8203e1d6b, 0x5, ...)
    /Users/harsha/mygo/src/github.com/minio/minio/pkg/fs/fs-multipart.go:471 +0x111d
main.CloudStorageAPI.CompleteMultipartUploadHandler(0x0, 0x7fff5fbffc8f, 0xa, 0x5, 0xc8201829c0, 0xc820182720, 0xc8201827c0, 0xc8200704e0, 0xc820070540, 0xf401d0, ...)
    /Users/harsha/mygo/src/github.com/minio/minio/object-handlers.go:501 +0x603
main.(CloudStorageAPI).CompleteMultipartUploadHandler-fm(0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/routers.go:94 +0x4b
net/http.HandlerFunc.ServeHTTP(0xc8200959a0, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1422 +0x3a
github.com/minio/minio/vendor/github.com/gorilla/mux.(_Router).ServeHTTP(0xc820094d70, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
main.timeHandler.ServeHTTP(0xf84ca8, 0xc820094d70, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/generic-handlers.go:139 +0x3db
main.(_timeHandler).ServeHTTP(0xc8201b1500, 0xf401d0, 0xc82004a790, 0xc82047e460)
    <autogenerated>:31 +0xb6
main.resourceHandler.ServeHTTP(0xf84cd0, 0xc8201b1500, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/generic-handlers.go:211 +0x392
main.(_resourceHandler).ServeHTTP(0xc8201b1510, 0xf401d0, 0xc82004a790, 0xc82047e460)
    <autogenerated>:33 +0xb6
main.ignoreSignatureV2RequestHandler.ServeHTTP(0xf84cf8, 0xc8201b1510, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/generic-handlers.go:166 +0x1ae
main.(_ignoreSignatureV2RequestHandler).ServeHTTP(0xc8201b1520, 0xf401d0, 0xc82004a790, 0xc82047e460)
    <autogenerated>:32 +0xb6
main.signatureHandler.ServeHTTP(0xf84d20, 0xc8201b1520, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/signature-handler.go:110 +0x6a6
main.(_signatureHandler).ServeHTTP(0xc8201b1530, 0xf401d0, 0xc82004a790, 0xc82047e460)
    <autogenerated>:93 +0xb6
github.com/minio/minio/vendor/github.com/rs/cors.(_Cors).Handler.func1(0xf401d0, 0xc82004a790, 0xc82047e460)
    /Users/harsha/mygo/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:185 +0x1c5
net/http.HandlerFunc.ServeHTTP(0xc82000dc00, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc820071e60, 0xf401d0, 0xc82004a790, 0xc82047e460)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc82004a000)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(_Server).Serve
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1910 +0x3f6
2016/02/14 08:59:24 http: panic serving [::1]:55937: runtime error: index out of range
goroutine 62 [running]:
net/http.(_conn).serve.func1(0xc8202784d0, 0xf40050, 0xc82002c088)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1287 +0xb5
github.com/minio/minio/pkg/fs.doPartsMatch(0xc8202f6900, 0x3, 0x4, 0xc820238f50, 0x2, 0x2, 0xc820379120)
    /Users/harsha/mygo/src/github.com/minio/minio/pkg/fs/fs-multipart.go:126 +0x1b9
github.com/minio/minio/pkg/fs.Filesystem.CompleteMultipartUpload(0x7fff5fbffc8f, 0xa, 0x5, 0xc8201829c0, 0xc820182720, 0xc8201827c0, 0xc8200704e0, 0xc820070540, 0xc82028062b, 0x5, ...)
    /Users/harsha/mygo/src/github.com/minio/minio/pkg/fs/fs-multipart.go:471 +0x111d
main.CloudStorageAPI.CompleteMultipartUploadHandler(0x0, 0x7fff5fbffc8f, 0xa, 0x5, 0xc8201829c0, 0xc820182720, 0xc8201827c0, 0xc8200704e0, 0xc820070540, 0xf401d0, ...)
    /Users/harsha/mygo/src/github.com/minio/minio/object-handlers.go:501 +0x603
main.(CloudStorageAPI).CompleteMultipartUploadHandler-fm(0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/routers.go:94 +0x4b
net/http.HandlerFunc.ServeHTTP(0xc8200959a0, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1422 +0x3a
github.com/minio/minio/vendor/github.com/gorilla/mux.(_Router).ServeHTTP(0xc820094d70, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
main.timeHandler.ServeHTTP(0xf84ca8, 0xc820094d70, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/generic-handlers.go:139 +0x3db
main.(_timeHandler).ServeHTTP(0xc8201b1500, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    <autogenerated>:31 +0xb6
main.resourceHandler.ServeHTTP(0xf84cd0, 0xc8201b1500, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/generic-handlers.go:211 +0x392
main.(_resourceHandler).ServeHTTP(0xc8201b1510, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    <autogenerated>:33 +0xb6
main.ignoreSignatureV2RequestHandler.ServeHTTP(0xf84cf8, 0xc8201b1510, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/generic-handlers.go:166 +0x1ae
main.(_ignoreSignatureV2RequestHandler).ServeHTTP(0xc8201b1520, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    <autogenerated>:32 +0xb6
main.signatureHandler.ServeHTTP(0xf84d20, 0xc8201b1520, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/signature-handler.go:110 +0x6a6
main.(_signatureHandler).ServeHTTP(0xc8201b1530, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    <autogenerated>:93 +0xb6
github.com/minio/minio/vendor/github.com/rs/cors.(_Cors).Handler.func1(0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /Users/harsha/mygo/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:185 +0x1c5
net/http.HandlerFunc.ServeHTTP(0xc82000dc00, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc820071e60, 0xf401d0, 0xc8202c6000, 0xc82037a9a0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc8202784d0)
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(_Server).Serve
    /usr/local/Cellar/go/1.5.3/libexec/src/net/http/server.go:1910 +0x3f6
2016/02/14 08:59:26 http: panic serving [::1]:55940: runtime error: index out of range

**Comment by harshavardhana** [comment]
> Environment:
> 
> MacOS 10.11.3
> Minio: version 2016-02-08T00:13:11Z
> aws: aws-cli/1.10.4 Python/2.7.11 Darwin/15.3.0 botocore/1.3.26
> 
> Thanks,

Thanks for your report, taking a look.

**Comment by harshavardhana** [comment]
`mc` Seems to be copying fine checking what is the issue with `aws cli`

```
$ mc cp ~/Downloads/bigfile.12MB s3://1222
...oads/bigfile.12MB: 12.00 MB / 12.00 MB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00 % 305.66 MB/s 0
```

**Comment by harshavardhana** [comment]
> Environment:
> 
> MacOS 10.11.3
> Minio: version 2016-02-08T00:13:11Z
> aws: aws-cli/1.10.4 Python/2.7.11 Darwin/15.3.0 botocore/1.3.26

We will be making a new release with more fixes in a few days, thanks for your report.  Keeping this open until then for you to download new binary and validate.

**Comment by harel-e** [comment]
Thanks, much appreciated.

**Comment by harel-e** [comment]
Tested on the latest code. No errors. 

Thanks for the quick fix.

**Comment by harshavardhana** [comment]
New binary with fixes uploaded.
