### ISSUE TITLE
Rename files with S3 Browser or other S3 tools "The request signature we calculated does not match the signature you provided. Check your key and signing method."

### ISSUE THREAD

**Issue by csc-solution** [minio/minio#11253]
## Expected Behavior

I always get this error if i try to rename / move files with S3 browser or other S3 compatible tools like TntDrive.

## Steps to Reproduce (for bugs)

1. Fresh and clean docker install of minio
2. Startup minio: docker run -p 9000:9000 -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" -e "MINIO_DOMAIN=s3.mydomain.com" minio/minio server /data
3. Create new buckt with s3 Browser and upload file
4. Try to rename the uploaded file

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-01-05T05-22-38Z
* Server setup and configuration: minio runing on docker (version 20.10.2, build 2291f61)
* Operating System and version (`uname -a`): Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-60-generic x86_64)

## Attachments:
[minio.log](https://github.com/minio/minio/files/5789262/minio.log)

![s3client_1](https://user-images.githubusercontent.com/51422947/104061584-28e90b00-51f9-11eb-82b8-008281ccde91.png)

![s3client_2](https://user-images.githubusercontent.com/51422947/104061587-2ab2ce80-51f9-11eb-9af0-4041f50b6a84.png)

**Comment by harshavardhana** [comment]
> 1. Fresh and clean docker install of minio
> 2. Startup minio: docker run -p 9000:9000 -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" -e "MINIO_DOMAIN=s3.mydomain.com" minio/minio server /data
> 3. Create new buckt with s3 Browser and upload file
> 4. Try to rename the uploaded file

If you enable MINIO_DOMAIN are you making sure your incoming connection is resolving `s3.mydomain.com` ?

**Comment by csc-solution** [comment]
Yes, minio server can resolve the domain, but it's the same if MINIO_DOMAIN is disabled and the communication is only via IP address

**Comment by harshavardhana** [comment]
> Yes, minio server can resolve the domain, but it's the same if MINIO_DOMAIN is disabled and the communication is only via IP address

Yes then it is mainly because the secret key used is wrong and that's why signature mismatches or the tool that you are using doesn't support non- AWS S3 endpoints.

**Comment by csc-solution** [comment]
I don't think thats a problem with the used tool, because with Ceph RADOS and an old Skylable SX installation, this functionality works correct. Which secret key do you mean, because if the credentials from the logged in user are wrong then i could'nt upload files or create buckets. 

Or do i understand something wrong in this case?

Minio is my favorite, because i need a s3 storage with a simple file backend. All others are oversized for our development.

**Comment by harshavardhana** [comment]
> I don't think thats a problem with the used tool, because with Ceph RADOS and an old Skylable SX installation, this functionality works correct. Which secret key do you mean, because if the credentials from the logged in user are wrong then i could'nt upload files or create buckets.

Try running `mc admin trace -v`

**Comment by csc-solution** [comment]
> Try running `mc admin trace -v`

Then i get the output from the attached minio.log. The only error what i found is with the s3.CopyObject request.

**Comment by harshavardhana** [comment]
> > Try running `mc admin trace -v`
> 
> Then i get the output from the attached minio.log. The only error what i found is with the s3.CopyObject request.

don't interpret it yourself, please share it here.

**Comment by csc-solution** [comment]
Already attached on my first post: https://github.com/minio/minio/files/5789262/minio.log

**Comment by harshavardhana** [comment]
```
s3.mydomain.com [REQUEST s3.CopyObject] 20:08:49.303
s3.mydomain.com PUT /new-bucket-e89db1ca/TestFile2.txt
s3.mydomain.com Proto: HTTP/1.1
s3.mydomain.com Host: s3.mydomain.com:9000
s3.mydomain.com Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20210108/us-east-1/s3/aws4_request,SignedHeaders=content-security-policy;content-type;host;user-agent;x-amz-request-id;x-xss-protection;x-amz-acl;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-s3b-last-modified;x-amz-meta-sha256;x-amz-metadata-directive;x-amz-storage-class, Signature=54046bec732ad1d94036a7897cd7bb9669c8987b763b88f2f568490bbe985730
s3.mydomain.com X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
s3.mydomain.com X-Amz-Meta-Sha256: 2d79e31462113b9e580c0a504c09e61ec5f04b8e6adf3ae3fbca5de5a217cade
s3.mydomain.com Content-Security-Policy: block-all-mixed-content
s3.mydomain.com X-Amz-Meta-S3b-Last-Modified: 20210108T200729Z
s3.mydomain.com X-Amz-Storage-Class: STANDARD
s3.mydomain.com Content-Type: text/plain
s3.mydomain.com X-Amz-Metadata-Directive: COPY
s3.mydomain.com X-Amz-Request-Id: 16585AA47CA4DCF5
s3.mydomain.com X-Xss-Protection: 1; mode=block
s3.mydomain.com Content-Length: 0
s3.mydomain.com User-Agent: S3 Browser 9.1.3 https://s3browser.com
s3.mydomain.com X-Amz-Acl: private
s3.mydomain.com X-Amz-Copy-Source: /new-bucket-e89db1ca/TestFile.txt
s3.mydomain.com X-Amz-Date: 20210108T200849Z
s3.mydomain.com 
s3.mydomain.com [RESPONSE] [20:08:49.304] [ Duration 1.222ms  ↑ 268 B  ↓ 663 B ]
s3.mydomain.com 403 Forbidden
s3.mydomain.com Accept-Ranges: bytes
s3.mydomain.com Content-Length: 435
s3.mydomain.com Content-Security-Policy: block-all-mixed-content
s3.mydomain.com Content-Type: application/xml
s3.mydomain.com Server: MinIO
s3.mydomain.com Vary: Origin
s3.mydomain.com X-Amz-Request-Id: 16585AA47CFE83E9
s3.mydomain.com X-Xss-Protection: 1; mode=block
s3.mydomain.com <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>TestFile2.txt</Key><BucketName>new-bucket-e89db1ca</BucketName><Resource>/new-bucket-e89db1ca/TestFile2.txt</Resource><RequestId>16585AA47CFE83E9</RequestId><HostId>840f871f-7d00-421d-9297-dac655fda823</HostId></Error>
s3.mydomain.com 
```

Here the issue is incorrect signature calculation by the client - 

```
s3.mydomain.com X-Amz-Copy-Source: /new-bucket-e89db1ca/TestFile.txt
```

The value is URL encoded and should be calculated as part of the signature with the URL encoded form

https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html

```
Specifies the source object for the copy operation. You specify the value in one of two formats, depending on whether you want to access the source object through an access point:

For objects not accessed through an access point, specify the name of the source bucket and the key of the source object, separated by a slash (/). For example, to copy the object reports/january.pdf from the bucket awsexamplebucket, use awsexamplebucket/reports/january.pdf. The value must be URL encoded.

For objects accessed through access points, specify the Amazon Resource Name (ARN) of the object as accessed through the access point, in the format arn:aws:s3:<Region>:<account-id>:accesspoint/<access-point-name>/object/<key>. For example, to copy the object reports/january.pdf through access point my-access-point owned by account 123456789012 in Region us-west-2, use the URL encoding of arn:aws:s3:us-west-2:123456789012:accesspoint/my-access-point/object/reports/january.pdf. The value must be URL encoded.
```

**Comment by harshavardhana** [comment]
If it worked with Ceph RADOS and Skylable then their implementation is buggy and allowing unexpected spec behavior.

**Comment by csc-solution** [comment]
> 
> 
> If it worked with Ceph RADOS and Skylable then their implementation is buggy and allowing unexpected spec behavior.

Thanks for your quick analyze of our problem. Yesterday i talked with the manufacture from our S3 Tool and got a fix from him. You were right, its not a problem from minio and now it works perfect.
