### ISSUE TITLE
Unable to perform the direct video streaming using get_presigned_url() when the object placed inside the folder #1057

### ISSUE THREAD

**Issue by Udayaprasad** [minio/minio#11263]
We are unable to stream the video object which is stored inside the folder, but I am able to download the video object and play it from my local computer.

E.G: 
if the object_name is just video1.mp4 then I am able to play the video URL from the following link otherwise, if we place the object like ('videos/video1.mp4'), then it is not playing
`https://cuttopoint.com/player.html`

## Expected Behavior
I should able to play the video even though it is placed under the folder. It is working in `play.min.io` but not in custom minio docker setup.

## Current Behavior
Here the problem is presigned URL generated by get_presigned_url() is not able to stream the video file if we stored it in a folder (object_name = "videos/video1.mp4").

## Steps to Reproduce (for bugs)

```
import urllib3

client = Minio(
    "SERVER:PORT",
    access_key="ACCESS_KEY",
    secret_key="SECRET_KEY",
    secure=True,
    http_client=urllib3.ProxyManager(
        "http://PROXYSERVER:PROXYPORT/",
        timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
        retries=urllib3.Retry(
            total=5,
            backoff_factor=0.2,
            status_forcelist=[500, 502, 503, 504],
        ),
    ),
)


bucket_name = "sample-bucket"
file_path = "/Users/uname/Downloads/video.mp4"
object_name = "videos/video1.mp4"


file_obj.fput_object(bucket_name, object_name,
                                       file_path)

objects = client.list_objects(
    bucket_name, recursive=True, start_after="videos/",
)

for obj in objects:
    logger.info(obj.object_name)

url = client.get_presigned_url(
    "GET",
    bucket_name,
    object_name,
    expires=timedelta(days=7)
)
```

## Your Environment
`Docker image: image: minio/minio:RELEASE.2020-12-23T02-24-12Z`

**Comment by harshavardhana** [comment]
@Udayaprasad you need to set content-type for your object properly.

**Comment by Udayaprasad** [comment]
@harshavardhana  While putting the object, by default the `content-type` is "application/octet-stream" . I hope, we don't need to specify explicitly. 

```
def fput_object(self, bucket_name, object_name, file_path,
                    content_type="application/octet-stream",
                    metadata=None, sse=None, progress=None,
                    part_size=0, num_parallel_uploads=3,
                    tags=None, retention=None, legal_hold=False):
```

**Comment by harshavardhana** [comment]
Of course you need to @Udayaprasad because the browser needs to know if the content is playable or not.

**Comment by Udayaprasad** [comment]
@harshavardhana  In that case, Do you know any reason, why it is working if we put the video file within the bucket (Not in any folder)? We are facing the problem only when storing inside the folder.

**Comment by harshavardhana** [comment]
> @harshavardhana In that case, Do you know any reason, why it is working if we put the video file within the bucket (Not in any folder)? We are facing the problem only when storing inside the folder.

Just set the correct content-type it will work fine.

**Comment by Udayaprasad** [comment]
@harshavardhana  Can you suggest what needs to set the Content-Type here. Below the Reactplayer code.

```
<ReactPlayer
      playing={showVideo}
      className='react-player'
      url={"http://localhost:4700/mybucket/video1.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cogai-dev%2F20210111%2F%2Fs3%2Faws4_request&X-Amz-Date=20210111T140252Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=ed96d802f93c6ca1d49c33701d6ef78b1244399be4835418a030d45d8d7e391c"}
      width='100%'
      controls={true} />
```

`https://www.npmjs.com/package/react-player`

**Comment by harshavardhana** [comment]
```js
<ReactPlayer
      playing={showVideo}
      className='react-player'
      url={[
           {src: "http://localhost:4700/mybucket/video1.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cogai-dev%2F20210111%2F%2Fs3%2Faws4_request&X-Amz-Date=20210111T140252Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=ed96d802f93c6ca1d49c33701d6ef78b1244399be4835418a030d45d8d7e391c", type: "video/mp4"},
        ]}
      width='100%'
      controls={true} />
```

AFAICS this is what you need to do https://www.npmjs.com/package/react-player its also mentioned in their docs.

**Comment by Udayaprasad** [comment]
@harshavardhana  No luck for me.

![image](https://user-images.githubusercontent.com/8266316/104427946-db2e2300-55a9-11eb-8c70-a3a8a7c0016e.png)

![image](https://user-images.githubusercontent.com/8266316/104428028-f5680100-55a9-11eb-8290-c3e838363a48.png)
