### ISSUE TITLE
[faq] NetBSD not supported. mkdir: .... Too many links...

### ISSUE THREAD

**Issue by MatthiasPetermann** [minio/minio#11264]
## Expected Behavior

It would be nice if MinIO could know the limitation of NetBSD mentioned 
in the subject and work around it or at least mitigate it, so that more 
than 32766 objects can be stored in one bucket.

## Current Behavior

When MinIO runs on NetBSD, currently a maximum of 32766 objects can be 
stored in a bucket. After that the operating system reports an error 
(Too many links). The cause seems to be that in the directory 
"/.minio.sys/buckets/<bucketname>/" a subdirectory is created for each 
object, which contains exactly one file (fs.json). In summary, the root 
cause is that internally in the file system, the ".." link in each 
subdirectory is a hard link to the inode of the parent directory. The 
link counter is implemented as a 16 bit integer, which leads to the 
limitation. Detached from MinIO, this has been discussed here in a 
technically well-founded manner:

https://mail-index.netbsd.org/tech-userlevel/2010/01/17/msg003148.html

## Possible Solution

- The minimum solution, in my view, is to include this problem in the 
documentation and point it out (if it's not already in there). I think 
this can be helpful for planning, since the problem - if known - can of 
course be circumvented on the client side by taking precautions 
yourself as an application developer so that no more than 32766 objects 
are ever stored in a bucket, and working with child buckets instead. 
However, this would require client-side logic that you don't really 
want to have at this point, since it moves internals of the storage 
logic to the client - bad architecture.

- Otherwise, I could imagine doing away with creating subdirectories 
for each individual object, and saving the contents of each fs.json to 
a file in a common directory. The name of the file could then be like 
the name of the object plus the .json extension. As far as i know, 
there are no such low limits for the maximum number of files in 
directories. Whether and how this makes sense or is possible, I cannot 
assess.

- Alternatively, an (optional) partitioning / sharding would be useful, 
i.e. inserting another directory level based on a hash value, e.g. the 
MD5 sum of the object name (similar to what Git does). This would not 
solve the problem completely, but would make its occurrence much less 
likely. 

## Steps to Reproduce (for bugs)

1. Create a bucket
2. Try to upload more than 32766 files
3. Watch MinIO log for error message

## Context

I want to use MinIO to store many small objects. The objects can be 
roughly divided into 5 categories, so it was obvious to create a bucket 
for each category. Within each bucket, 200k objects are to be stored.

## Regression

This is not a regression as far I can judge.

## Your Environment

* Version: RELEASE.2020-10-28T08-16-50Z
* Server setup and configuration: 1 CPU Core, 2 GB RAM, 300 GB Storage
* Operating System and version (`uname -a`): NetBSD/amd64 9.1

**Comment by klauspost** [comment]
MinIO doesn't provide NetBSD support as you can see on https://docs.min.io/docs/minio-quickstart-guide.html - we cannot list all operating systems we do not support, but it would be reasonable to assume that anything not listed there isn't supported or the very least tested.

We do not plan to provide support and workarounds for such a big issue like you mention doesn't seem feasible as it would be a fundamental non-compatible change to how MinIO operates.

**Comment by MatthiasPetermann** [comment]
Hi Klaus,

thanks for the quick response and for the clarification. I am aware that NetBSD (just like FreeBSD) are not *officially* supported. Whereas it is of course still good to know that it is at least technically feasible due to the platform independence of Golang, if there is someone on the side of the respective operating system project who takes care of the concrete porting. I also think that this works well and MinIO is not the only project that officially does not support *BSDs and yet is successfully used on them. So I don't see a problem for MinIO here. I also realize that it is not possible from the software project side to support every operating system first hand. 

My suggestion would be to make the support statement the same for all *BSDs then. "Not *officially* supported" I think sums it up quite well - this relieves MinIO of the expectation to support the BSDs directly and keeps the door open for the packagers of the respective operating systems.

The specific observation (Too Many Links) is, to my current knowledge, also affecting FreeBSD with UFS filesystem, as well as Linux with ext3/ext2 filesystem. The solution in each case is to switch to a different file system. On Linux ext4 is the standard anyway, on FreeBSD ZFS has been available as a stable alternative for years, and NetBSD also offers usable ZFS support since 9.0, but it is still in beta. All of the latter file systems do not have the observed limitation and can thus be used for MinIO without restrictions.

Many greetings
Matthias

**Comment by win2all** [comment]
Столкнулся с аналогичной проблемой в Linux с файловой системой ext3
`UserAgent: MinIO (amd64; amd64) minio-java/42.2.5
Error: mkdir /opt/extend/minio/data/.minio.sys/buckets/logws/2021-02/05/8283816900.xml: too many links
       4: github.com/minio/minio@/cmd/api-errors.go:1972:cmd.toAPIErrorCode()
       3: github.com/minio/minio@/cmd/api-errors.go:1997:cmd.toAPIError()
       2: github.com/minio/minio@/cmd/object-handlers.go:1554:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2036:http.HandlerFunc.ServeHTTP()
`
Создание отдельного каталога на каждый файл порадовало (сарказм).
Узнать реальную ошибку из java невозможно, в стеке пишет "просто какая-то ошибка", вместо того чтобы передать реальное исключение.
