### ISSUE TITLE
My disk has a size of 500GB. Can I check via api how much free space is still available?

### ISSUE THREAD

**Issue by AmarHelaSoft** [minio/minio#11270]
My disk has a size of 500GB. Can I check via api how much free space is still available?
is there any REST API available to get free space and used space and total space ?
if, yes kindly help me to know about it .

**Comment by harshavardhana** [comment]
you can do `mc admin info --json` to see disk free space.

**Comment by AmarHelaSoft** [comment]
@harshavardhana - I am using minio in Node.js server. Then how can i make request to get these info in json format ?
Can you provide detail info. I am new with minio

**Comment by AmarHelaSoft** [comment]
> you can do `mc admin info --json` to see disk free space.

I am using minio in Node.js server. Then how can i make request to get these info in json format ?
Can you provide detail info. I am new with minio

**Comment by harshavardhana** [comment]
> @harshavardhana - I am using minio in Node.js server. Then how can i make request to get these info in json format ?
> Can you provide detail info. I am new with minio

You can invoke `mc` from node.js

**Comment by AmarHelaSoft** [comment]
> > @harshavardhana - I am using minio in Node.js server. Then how can i make request to get these info in json format ?
> > Can you provide detail info. I am new with minio
> 
> You can invoke `mc` from node.js

Can you provide me some code sample for this ? As, i am totally new with minio client.

**Comment by klauspost** [comment]
@AmarHelaSoft `mc` is a regular application. You start it like any other.
