### ISSUE TITLE
Distributed deployment of 4 pods on 4 nodes. When one node is down, the client pull operation hangs for 15 minutes and succeeds.

### ISSUE THREAD

**Issue by enayzhu** [minio/minio#11286]
Distributed deployment of 4 pods on 4 nodes, when one node is down, the client pull operation hangs for 15 minutes and succeeds. It takes about 2 seconds to operate the same file when 4 pods are normal. At the same time, I found that only the first operation will hang for 15 minutes after the node is down, and the subsequent operations will take about 10s each time, which is an acceptable time. But the first operation hang after the node went down, it took too long
## Expected Behavior

Complete the pull operation in a few seconds
## Current Behavior

Pull operation is successful after 15min
## Steps to Reproduce (for bugs)

1.The node where the shoutdown minio pod is located
2.mc performs a pull operation
3.
4.

## Your Environment

* Version used (`minio --version`):RELEASE.2021-01-16T02-19-44Z-1-g40d59c196
* Server setup and configuration:Kubernetes 1.17.3, network-block for the minio volume
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> Distributed deployment of 4 pods on 4 nodes, when one node is down, the client pull operation hangs for 15 minutes and succeeds. It takes about 2 seconds to operate the same file when 4 pods are normal. At the same time, I found that only the first operation will hang for 15 minutes after the node is down, and the subsequent operations will take about 10s each time, which is an acceptable time. But the first operation hang after the node went down, it took too long

This timeout is your client timeout @enayzhu basically whichever ingress rule you are using.  You need to use a ClusterIP which can manage the routing properly for the downed services. 

The server detects a downed node right away and takes it offline.  If the client is not routable then it can take time.

**Comment by enayzhu** [comment]
I am using ClusterIP now, and this problem does not occur on the client side.
It is caused by not discovering offline pods in time when communicating between server clusters.

**Comment by harshavardhana** [comment]
> I am using ClusterIP now, and this problem does not occur on the client side.
> It is caused by not discovering offline pods in time when communicating between server clusters.

I have never seen 15min timeouts, there are no such at a within MinIO unless you are using really old servers.
