### ISSUE TITLE
Disk Ordering Issue unable to heal

### ISSUE THREAD

**Issue by zenjabba** [minio/minio#11283]
Small files that have metadata corruption are unable to be healed due to disk ordering issue.

**Error Logs**

Jan 15 17:10:43 zdstore-block2-node1 minio[1138956]: Time: 17:10:43 UTC 01/15/2021
Jan 15 17:10:43 zdstore-block2-node1 minio[1138956]: DeploymentID: 995ce92a-2e6d-4b5d-93e3-9c402935a486
Jan 15 17:10:43 zdstore-block2-node1 minio[1138956]: Error: Heal attempt failed for zd-audiobooks/audiobooks/Audiobooks_English/Shawn Inmon/Alex Hawk Time Travel Adventure 1 - A Door into Time (2020)/reader.txt: Unable to heal object zd-audiobooks/audiobooks/Audiobooks_English/Shawn Inmon/Alex Hawk Time Travel Adventure 1 - A Door into Time (2020)/reader.txt, disk ordering issue detected
Jan 15 17:10:43 zdstore-block2-node1 minio[1138956]:        2: cmd/admin-heal-ops.go:755:cmd.(*healSequence).healItemsFromSourceCh()
Jan 15 17:10:43 zdstore-block2-node1 minio[1138956]:        1: cmd/admin-heal-ops.go:766:cmd.(*healSequence).healFromSourceCh()
Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]: API: BackgroundHeal()
Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]: Time: 17:12:39 UTC 01/15/2021
Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]: DeploymentID: 995ce92a-2e6d-4b5d-93e3-9c402935a486
Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]: Error: Heal attempt failed for zd-audiobooks/audiobooks/Audiobooks_English/Stephen L. Hadley/Master of Monsters  - Publisher's Pack 2, Books 3-4 (2020)/reader.txt: Unable to heal object zd-audiobooks/audiobooks/Audiobooks_English/Stephen L. Hadley/Master of Monsters  - Publisher's Pack 2, Books 3-4 (2020)/reader.txt, disk ordering issue detected
Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]:        2: cmd/admin-heal-ops.go:755:cmd.(*healSequence).healItemsFromSourceCh()
Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]:        1: cmd/admin-heal-ops.go:766:cmd.(*healSequence).healFromSourceCh(

**Your Environment**
Version: 2020-10-27T04:03:55Z

12 Nodes with 16 Disks in each node, 128GB RAM and 32 cores in each system

Linux zdstore-block2-node1 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> audiobooks/audiobooks/Audiobooks_English/Stephen L. Hadley/Master of Monsters - Publisher's Pack 2, Books 3-4 (2020)/reader.txt: Unable to heal object zd-audiobooks/audiobooks/Audiobooks_English/Stephen L. Hadley/Master of Monsters - Publisher's Pack 2, Books 3-4 (2020)/reader.txt, disk ordering issue detected
> Jan 15 17:12:39 zdstore-block2-node1 minio[1138956]: 2: cmd/admin-heal-op

we have already automatically handled this @zenjabba in later releases - you should upgrade.

**Comment by zenjabba** [comment]
@harshavardhana so can you please help us to upgrade to a later version.

**Comment by harshavardhana** [comment]
> @harshavardhana so can you please help us to upgrade to a later version.

@zenjabba sure https://min.io/pricing - feel free to buy the subscription we are happy to help.
