### ISSUE TITLE
crypto/sha256: SIGILL: illegal instruction upon ls in KVM instance

### ISSUE THREAD

**Issue by ghost** [minio/minio#1128]
I tested this on 2 maschines (Debian Jessie up2date @KVM). If I run "./mc ls myserver" , the minio server dies instantly with.

**Output mc**:
mc: <ERROR> Unable to stat ‘myserver. Connection closed by foreign host http://94.23.xxx.xxxx:5555/. Retry again.
 (2) ls-main.go:100 main.checkListSyntax(..) Tags: [myserver](1) url.go:49 main.url2Stat(..) Tags: [myserver](0) pkg/client/s3/s3.go:291 s3.(*s3Client).Stat(..)
 Release-Tag:OFFICIAL.2016-02-08T02-14-28Z | Commit:fbe476865835 | Host:tp | OS:linux | Arch:amd64 | Lang:go1.5.1 | Mem:601kB/4.7MB | Heap:601kB/1.6MB

**Output minio**:
SIGILL: illegal instruction
PC=0x40374b m=4
signal arrived during cgo execution

goroutine 19 [syscall, locked to thread]:
runtime.cgocall(0x401990, 0xc8201ed868, 0x0)
    /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8201ed820 sp=0xc8201ed7f0
github.com/minio/minio/pkg/crypto/sha256._Cfunc_sha256_transform_rorx(0xc8201a45d0, 0xc8201a45b0, 0x1)
    github.com/minio/minio/pkg/crypto/sha256/_obj/_cgo_gotypes.go:58 +0x35 fp=0xc8201ed868 sp=0xc8201ed820
github.com/minio/minio/pkg/crypto/sha256.blockAVX2(0xc8201a45b0, 0xc8201a45d0, 0x40, 0x40)
    /root/go/src/github.com/minio/minio/pkg/crypto/sha256/sha256block.go:44 +0x53 fp=0xc8201ed888 sp=0xc8201ed868
github.com/minio/minio/pkg/crypto/sha256.block(0xc8201a45b0, 0xc8201a45d0, 0x40, 0x40)
    /root/go/src/github.com/minio/minio/pkg/crypto/sha256/sha256_linux.go:80 +0x58 fp=0xc8201ed8b0 sp=0xc8201ed888
github.com/minio/minio/pkg/crypto/sha256.(_digest).Write(0xc8201a45b0, 0xc820185a00, 0x8, 0x40, 0x8, 0x0, 0x0)
    /root/go/src/github.com/minio/minio/pkg/crypto/sha256/sha256_linux.go:119 +0x165 fp=0xc8201ed938 sp=0xc8201ed8b0
github.com/minio/minio/pkg/crypto/sha256.(_digest).checkSum(0xc8201a45b0, 0x0, 0x0, 0x0, 0x0)
    /root/go/src/github.com/minio/minio/pkg/crypto/sha256/sha256_linux.go:160 +0x180 fp=0xc8201ed9d0 sp=0xc8201ed938
github.com/minio/minio/pkg/crypto/sha256.Sum256(0xc8201da440, 0x0, 0x8, 0x0, 0x0, 0x0, 0x0)
    /root/go/src/github.com/minio/minio/pkg/crypto/sha256/sha256_linux.go:102 +0xbf fp=0xc8201eda38 sp=0xc8201ed9d0
main.signatureHandler.ServeHTTP(0x7fb334c0ee28, 0xc8201994e0, 0x7fb334c10208, 0xc820100580, 0xc8201d6000)
    /root/go/src/github.com/minio/minio/signature-handler.go:99 +0x4cb fp=0xc8201edb18 sp=0xc8201eda38
main.(_signatureHandler).ServeHTTP(0xc8201994f0, 0x7fb334c10208, 0xc820100580, 0xc8201d6000)
    <autogenerated>:94 +0xb6 fp=0xc8201edb50 sp=0xc8201edb18
github.com/minio/minio/vendor/github.com/rs/cors.(_Cors).Handler.func1(0x7fb334c10208, 0xc820100580, 0xc8201d6000)
    /root/go/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:185 +0x1c5 fp=0xc8201edbb0 sp=0xc8201edb50
net/http.HandlerFunc.ServeHTTP(0xc82017fb00, 0x7fb334c10208, 0xc820100580, 0xc8201d6000)
    /usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc8201edbd0 sp=0xc8201edbb0
net/http.serverHandler.ServeHTTP(0xc820019ec0, 0x7fb334c10208, 0xc820100580, 0xc8201d6000)
    /usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc8201edc30 sp=0xc8201edbd0
net/http.(_conn).serve(0xc8201ce000)
    /usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc8201edf88 sp=0xc8201edc30
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8201edf90 sp=0xc8201edf88
created by net/http.(_Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 1 [select]:
github.com/minio/minio/pkg/minhttp.ListenAndServe(0xc820199ef0, 0x2, 0x2, 0x89bb60)
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:158 +0x4aa
main.serverMain(0xc82016e0f0)
    /root/go/src/github.com/minio/minio/server-main.go:340 +0xe23
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xa22118, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaa2000, 0x21, 0x0, ...)
    /root/go/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:117 +0x19ac
github.com/minio/minio/vendor/github.com/minio/cli.(_App).Run(0xc82014c480, 0xc82000a0a0, 0x5, 0x5, 0x0, 0x0)
    /root/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:186 +0x476
github.com/minio/minio/vendor/github.com/minio/cli.(_App).RunAndExitOnError(0xc82014c480)
    /root/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:197 +0x45
main.main()
    /root/go/src/github.com/minio/minio/main.go:193 +0x29f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select]:
github.com/minio/minio/pkg/fs.(_Filesystem).listObjectsService.func1(0xc8200185a0, 0xc82016cc90, 0xc820018540, 0xc820014e00)
    /root/go/src/github.com/minio/minio/pkg/fs/fs-bucket-listobjects.go:232 +0x910
created by github.com/minio/minio/pkg/fs.(_Filesystem).listObjectsService
    /root/go/src/github.com/minio/minio/pkg/fs/fs-bucket-listobjects.go:280 +0x104

goroutine 7 [select]:
github.com/minio/minio/vendor/github.com/facebookgo/httpdown.(*server).manage(0xc820100420)
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:205 +0xac4
created by github.com/minio/minio/vendor/github.com/facebookgo/httpdown.HTTP.Serve
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:97 +0x4fa

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7fb334c10008, 0x72, 0xc8200101a0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(_pollDesc).Wait(0xc8201a4220, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc8201a4220, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).accept(0xc8201a41c0, 0x0, 0x7fb334c10188, 0xc8201be100)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(_TCPListener).AcceptTCP(0xc8200262e0, 0xc820039e90, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(_TCPListener).Accept(0xc8200262e0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(_Server).Serve(0xc820019ec0, 0x7fb334c100c8, 0xc8200262e0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/minio/minio/vendor/github.com/facebookgo/httpdown.(*server).serve(0xc820100420)
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:278 +0x8b
created by github.com/minio/minio/vendor/github.com/facebookgo/httpdown.HTTP.Serve
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:98 +0x51c

goroutine 9 [select]:
github.com/minio/minio/vendor/github.com/facebookgo/httpdown.(*server).manage(0xc8201004d0)
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:205 +0xac4
created by github.com/minio/minio/vendor/github.com/facebookgo/httpdown.HTTP.Serve
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:97 +0x4fa

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7fb334c0ff48, 0x72, 0xc8200101a0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(_pollDesc).Wait(0xc8201a4290, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc8201a4290, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).accept(0xc8201a4230, 0x0, 0x7fb334c10188, 0xc8201a8080)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(_TCPListener).AcceptTCP(0xc8200262e8, 0x4a1fc0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(_TCPListener).Accept(0xc8200262e8, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(_Server).Serve(0xc8201a2300, 0x7fb334c100c8, 0xc8200262e8, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/minio/minio/vendor/github.com/facebookgo/httpdown.(*server).serve(0xc8201004d0)
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:278 +0x8b
created by github.com/minio/minio/vendor/github.com/facebookgo/httpdown.HTTP.Serve
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:98 +0x51c

goroutine 11 [semacquire]:
sync.runtime_Semacquire(0xc820199f9c)
    /usr/local/go/src/runtime/sema.go:43 +0x26
sync.(_WaitGroup).Wait(0xc820199f90)
    /usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/minio/minio/pkg/minhttp.(_app).wait(0xc8201a23c0)
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:88 +0x162
github.com/minio/minio/pkg/minhttp.ListenAndServe.func1(0xc8201a2a20, 0xc8201a23c0)
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:153 +0x48
created by github.com/minio/minio/pkg/minhttp.ListenAndServe
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:156 +0x349

goroutine 12 [chan receive]:
github.com/minio/minio/pkg/minhttp.(_app).trapSignal(0xc8201a23c0, 0xc820199f90)
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:96 +0x1ff
created by github.com/minio/minio/pkg/minhttp.(_app).wait
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:79 +0x85

goroutine 13 [chan receive]:
github.com/minio/minio/vendor/github.com/facebookgo/httpdown.(_server).Wait(0xc820100420, 0x0, 0x0)
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:284 +0x57
github.com/minio/minio/pkg/minhttp.(_app).wait.func1(0xc820199f90, 0xc8201a23c0, 0x7fb334c10158, 0xc820100420)
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:83 +0x52
created by github.com/minio/minio/pkg/minhttp.(*app).wait
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:86 +0x135

goroutine 14 [chan receive]:
github.com/minio/minio/vendor/github.com/facebookgo/httpdown.(_server).Wait(0xc8201004d0, 0x0, 0x0)
    /root/go/src/github.com/minio/minio/vendor/github.com/facebookgo/httpdown/httpdown.go:284 +0x57
github.com/minio/minio/pkg/minhttp.(_app).wait.func1(0xc820199f90, 0xc8201a23c0, 0x7fb334c10158, 0xc8201004d0)
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:83 +0x52
created by github.com/minio/minio/pkg/minhttp.(*app).wait
    /root/go/src/github.com/minio/minio/pkg/minhttp/http_nix.go:86 +0x135

goroutine 15 [select, locked to thread]:
runtime.gopark(0xb1cce0, 0xc820024728, 0xa220a0, 0x6, 0x47ed18, 0x2)
    /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024728)
    /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

rax    0x6a09e667
rbx    0xbb67ae85
rcx    0x3c6ef372
rdx    0x510e527f
rdi    0xc8201a45d0
rsi    0xc8201a45b0
rbp    0x0
rsp    0x7fb33361ebe0
r8     0xa54ff53a
r9     0x9b05688c
r10    0x1f83d9ab
r11    0x5be0cd19
r12    0xf
r13    0xb1961c
r14    0x5
r15    0x8
rip    0x40374b
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0

**Comment by harshavardhana** [comment]
> Output minio:
> SIGILL: illegal instruction
> PC=0x40374b m=4
> signal arrived during cgo execution

This because of sh256 trying to initiate processor instructions for computation, KVM does not have those features. 

Here is the following code - sha256_transform_rorx is an assembly function.

> /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8201ed820 sp=0xc8201ed7f0
> github.com/minio/minio/pkg/crypto/sha256._Cfunc_sha256_transform_rorx(0xc8201a45d0, 0xc8201a45b0, 0x1)
> github.com/minio/minio/pkg/crypto/sha256/_obj/_cgo_gotypes.go:58 +0x35 fp=0xc8201ed868 sp=0xc8201ed820

Keeping this bug open for discussion to be able to transparently disable this code internally at runtime, currently running inside KVM will lead to this issue.

**Comment by ghost** [comment]
If I understand correctly the situation should be solved if you add a generic fallback like https://golang.org/src/crypto/sha256/sha256.go that doesn't need special instructions set. Most VMs have them though, just saw that my 2 KVM are the "rare" case of not having SSE3+ or AVX :)

**Comment by harshavardhana** [comment]
> If I understand correctly the situation should be solved if you add a generic fallback like https://golang.org/src/crypto/sha256/sha256.go that doesn't need special instructions set. Most VMs have them though, just saw that my 2 KVM are the "rare" case of not having SSE3+ or AVX :)

We do have generic fall back but i am not sure why it didn't handle it

```
func block(dig *digest, p []byte) {
        switch true {
        case cpu.HasAVX2() == true:
                blockAVX2(dig, p)
        case cpu.HasAVX() == true:
                blockAVX(dig, p)
        case cpu.HasSSE41() == true:
                blockSSE(dig, p)
        default:
                blockGeneric(dig, p)
        }
}
```

In this case rorx means that AVX2 was enabled, it could be that KVM exposes these through cpuid but not make all instructions available at the hypervisor layer.

**Comment by ghost** [comment]
flags: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni cx16 x2apic popcnt hypervisor lahf_lm

if that helps anything ;)

**Comment by harshavardhana** [comment]
> flags: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni cx16 x2apic popcnt hypervisor lahf_lm
> 
> if that helps anything ;)

Can you run the following code if you have golang installed? 

```
package main

import (
    "fmt"
    "github.com/klauspost/cpuid"
)

func main() {
    // Print basic CPU information:
    fmt.Println("Name:", cpuid.CPU.BrandName)
    fmt.Println("PhysicalCores:", cpuid.CPU.PhysicalCores)
    fmt.Println("ThreadsPerCore:", cpuid.CPU.ThreadsPerCore)
    fmt.Println("LogicalCores:", cpuid.CPU.LogicalCores)
    fmt.Println("Family", cpuid.CPU.Family, "Model:", cpuid.CPU.Model)
    fmt.Println("Features:", cpuid.CPU.Features)
    fmt.Println("Cacheline bytes:", cpuid.CPU.CacheLine)
    fmt.Println("L1 Data Cache:", cpuid.CPU.Cache.L1D, "bytes")
    fmt.Println("L1 Instruction Cache:", cpuid.CPU.Cache.L1D, "bytes")
    fmt.Println("L2 Cache:", cpuid.CPU.Cache.L2, "bytes")
    fmt.Println("L3 Cache:", cpuid.CPU.Cache.L3, "bytes")

    // Test if we have a specific feature:
    if cpuid.CPU.SSE() {
        fmt.Println("We have Streaming SIMD Extensions")
    }
}
```

```
go run main.go
```

**Comment by ghost** [comment]
Name: QEMU Virtual CPU version 2.3.0
PhysicalCores: 0
ThreadsPerCore: 1
LogicalCores: 0
Family 6 Model: 6
Features: CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,POPCNT,CX16
Cacheline bytes: 64
L1 Data Cache: 32768 bytes
L1 Instruction Cache: 32768 bytes
L2 Cache: 4194304 bytes
L3 Cache: -1 bytes
We have Streaming SIMD Extensions

**Comment by harshavardhana** [comment]
```
package main

import (
    "fmt"
    "github.com/klauspost/cpuid"
)

func main() {
    if cpuid.CPU.AVX2() {
        fmt.Println("We have streaming AVX2 extensions")
    }
}
```

One more - thanks!

**Comment by ghost** [comment]
no output

**Comment by harshavardhana** [comment]
> no output

Okay this is most probably our bug, the cpu.HasAVX2() is returning true for KVM which shouldn't be. Fixing it.

**Comment by harshavardhana** [comment]
Re-open until release..
