### ISSUE TITLE
Cannot create webhook when running Minio with Docker

### ISSUE THREAD

**Issue by emagnca** [minio/minio#11289]
Cannot create webhook when running Minio with Docker. It works when running Minio as a stand-alone. Can you please explain what the difference is.

## Expected Behavior
Possible to create webhooks when running with Docker

## Current Behavior
Not possible to create webhook when running with Docker

## Steps to Reproduce (for bugs)
The following commands works when running Minio as a stand-alone:
$ MINIO_ACCESS_KEY=admin MINIO_SECRET_KEY=mySecret minio server ~/data/minio &
$ mc admin config set local notify_webhook endpoint=http://192.168.1.223:3002 
$ mc admin service restart local                                               
$ mc event add local/mmdok arn:minio:sqs::1:webhook --event put            
Successfully added arn:minio:sqs::1:webhook

But when running the same sequence of commands with Docker it fails:
$ docker run --name minio -d -p9000:9000 -e MINIO_ACCESS_KEY=admin -e MINIO_SECRET_KEY=mySecret minio/minio server ~/data/minio
$ mc admin config set local notify_webhook endpoint=http://192.168.1.223:3002                                                  
$ mc admin service restart local                                                                                               
$ mc event add local/mmdok arn:minio:sqs::1:webhook --event put                                                                
mc: <ERROR> Unable to enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.

## Context
Need to be notified when new files are uploaded to Minio

## Regression
No

## Your Environment
minio version RELEASE.2021-01-16T02-19-44Z
Darwin iMacsomorMagnus.lan 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
> But when running the same sequence of commands with Docker it fails:
> $ docker run --name minio -d -p9000:9000 -e MINIO_ACCESS_KEY=admin -e MINIO_SECRET_KEY=mySecret minio/minio server ~/data/minio
> $ mc admin config set local notify_webhook endpoint=http://192.168.1.223:3002
> $ mc admin service restart local
> $ mc event add local/mmdok arn:minio:sqs::1:webhook --event put
> mc: Unable to enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.

Because your docker instance is not persisted by default - you need to provide persistence - use containers properly.

**Comment by emagnca** [comment]
The problem was not that the bucket did not exist. Then the error message is different. Actually the error message is fully correct. When looking more carefully the SQS ARN is printed out in the shell and it was different in the Docker shell than the stand-alone. See below. I somehow missed this yesterday. My excuses for being too quick in writing a trouble report.

So this works in my case for Docker: 
$ mc event add local/mmdok arn:minio:sqs::_:webhook --event put

From the Docker shell
================
$ docker logs minio
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint: http://172.17.0.2:9000  http://127.0.0.1:9000 

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Restarting on service signal
Endpoint: http://172.17.0.2:9000  http://127.0.0.1:9000 
SQS ARNs: arn:minio:sqs::_:webhook

**Comment by harshavardhana** [comment]
> SQS ARNs: arn:minio:sqs::_:webhook

Yes you didn't add an alias for your webhook that's why it chose `_`

**Comment by emagnca** [comment]
Thank you for the info and prompt answer. Is this documented somewhere?

**Comment by harshavardhana** [comment]
> Thank you for the info and prompt answer. Is this documented somewhere?

At docs.minio.io one search away https://docs.minio.io/docs/minio-bucket-notification-guide.html

**Comment by emagnca** [comment]
Yes. I have been there. Thank you.
