### ISSUE TITLE
Unable to push logging to splunk

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11281]
When setting audit_webhook and logger_webhook events are not pushed to splunk. 

## Expected Behavior
All events should be logged to the log forwarder 

## Current Behavior
Events are not received in splunk. 

## Steps to Reproduce (for bugs)
**set audit_webhook** 
mc admin config set myminio audit_webhook enable=on endpoint=https://mysplunk:8088/services/collector auth_token="my token"

Set  logger_webhook 

mc admin config set myminio logger_webhook enable=on endpoint=https://mysplunk:8088/services/collector auth_token="my token"

run some test copy's using MC and list buckets, and admin operations. 

Search Splunk. 

## Context
Without full logging we cannot implement Minio

## Your Environment
* 2021-01-08T21:18:21Z
Ubuntu 18 
24 Node Cluster

**Comment by nitisht** [comment]
Have you seen https://docs.minio.io/docs/minio-bucket-notification-guide.html#webhooks

Looks like you did not follow step 2, i.e. `mc event add myminio/images ....`

**Comment by zapto2600** [comment]
I followed the blog post here: https://blog.min.io/minio-notifications-in-splunk/ I do not want to monitor single events like .jpg but ALL events to create a compliant solution. 

Looking in mc admin console myminio there is an error 

Error: Unable to initialize audit HTTP target: Post "https://mysplunk:8088/services/collector": context deadline exceeded (*fmt.wrapError)

I cannot find any reference to this error?

**Comment by harshavardhana** [comment]
> Error: Unable to initialize audit HTTP target: Post "https://mysplunk:8088/services/collector": context deadline exceeded (*fmt.wrapError)

This means that we couldn't write to your HTTP target and it's not reachable.

I just tested with https://webhook.site/d0ef18cd-e542-4583-bc53-cc06d062a1dc public site, it's all working fine.
