### ISSUE TITLE
Upgrade issue from Oct 27th 2020 to anything later

### ISSUE THREAD

**Issue by zenjabba** [minio/minio#11282]
Please find attached for case https://github.com/minio/minio/issues/11191

[miniologs.txt](https://github.com/minio/minio/files/5821991/miniologs.txt)

We cannot upgrade from Oct 27th without the system being unusable.

**Comment by harshavardhana** [comment]
This looks like you have corrupted your system @zenjabba somehow. Feel free to engage with us on the https://subnet.min.io/subscribe - we are happy to hand hold and bring up the deloyment.
