### ISSUE TITLE
Why is the uploadPart method modified by protected？

### ISSUE THREAD

**Issue by neko-zhu** [minio/minio#11298]
The uploadPart method modified by protected，if i want to use the multipart upload function, what should I do?

I hope the uploadPart method and its related methods to be modified by public

Looking forward to your reply！

**Comment by harshavardhana** [comment]
I have no idea what you are asking, Is this related to MinIO - please provide more details.

**Comment by neko-zhu** [comment]
SDK for Java, the uploadPart method under the MinioClient class is modified by protected. What are the considerations?
![image](https://user-images.githubusercontent.com/32889558/104981381-78bea200-5a43-11eb-9720-569ea5c500e6.png)
