### ISSUE TITLE
GCS Gateway only supports buckets with "fine-grained" permissions

### ISSUE THREAD

**Issue by talzion12** [minio/minio#11292]
I created a bucket with uniform permissions and configured minio to be a gateway for GCS. Whenever I tried to `mc policy get HOST/BUCKET` I got invalid bucket name error (the bucket name is all lowercase with hyphens).

## Expected Behavior
It should get the policy or return a more descriptive error message.

## Current Behavior
`mc` prints ```mc: <ERROR> Unable to get policy `` for `HOST/BUCKET`. The specified bucket is not valid.```.

## Steps to Reproduce (for bugs)

1. Create a GCS bucket.
2. Set it to "uniform" permissions in Google Cloud Console.
3. Try to `mc policy get HOST/BUCKET`

## Context
My entire bucket is public and so I didn't see a reason for the fine grained permissions. It took me hours to find out the problem was the uniform permissions.

By the way, I can see [here](https://github.com/minio/minio/blob/master/cmd/gateway/gcs/gateway-gcs.go#L300) that any GCS invalid error is converted into a `BucketNameInvalidError` which seems misleading.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-01-16T02-19-44Z
* Server setup and configuration: GCS Gateway
* Operating System and version (`uname -a`): 4.19.150+ #1 SMP Sat Oct 24 07:57:26 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Gateway GCS implementation is frozen not taking any more requests, feel free to send a PR if you must.
