### ISSUE TITLE
Aws::S3::Model::HeadBucketRequest fails: No response body

### ISSUE THREAD

**Issue by malikkirchner** [minio/minio#11297]
At the moment it is not possible to check if an object or bucket exists with a HEAD request.

## Expected Behavior
If an object/bucket exists, the HeadBucketRequest/HeadObjectRequest should result in a success response. If it doesn't exist, the request should fail.

## Current Behavior
The HeadBucketRequest/HeadObjectRequest always fails with: 'No response body.'

## Steps to Reproduce (for bugs)

```
Aws::S3::Model::HeadBucketRequest request;
request.WithBucket( bucket );
auto result = s3_client.HeadBucket( request );
result.IsSuccess()
```

## Regression
Yes.

## Your Environment
* minio version DEVELOPMENT.2021-01-18T06-29-05Z
* Linux starfleet-janeway 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@malikkirchner Head of course will never have a response body - not sure why the SDK is incorrect behaving here - looks like a client bug.

**Comment by harshavardhana** [comment]
FWIW it has been reported in AWS SDK C++ before https://github.com/aws/aws-sdk-cpp/issues/1391

**Comment by malikkirchner** [comment]
I see, thank you for the clarification!
