### ISSUE TITLE
[not a bug] Inconsistent Unauthenticated HTTP Response for Bucket Identification

### ISSUE THREAD

**Issue by joswr1ght** [minio/minio#11293]
The Minio server responds with the error code `AccessDenied` when an unauthenticated request is made for a bucket that does not exist. This is a departure from the behavior of AWS S3, which returns the error code `NoSuchBucket`:

```
$ curl -s http://s3.amazonaws.com/nosuchbucketname | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist</Message>
  <BucketName>nosuchbucketname</BucketName>
  <RequestId>6E7DF1445C10461D</RequestId>
  <HostId>H/uuza9hxsidE79A7VirhjbmEN9F9RSbz7iTwqLRgZa7/EbYvT0DLKBiCbypgg5B33HG4GlP16c=</HostId>
</Error>
```

```
$ curl -s http://play.min.io/nosuckbucketname | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied.</Message>
  <BucketName>nosuckbucketname</BucketName>
  <Resource>/nosuckbucketname</Resource>
  <RequestId>165B544FCA3A2006</RequestId>
  <HostId>cee624e3-ecd8-4c48-901a-74e259357f40</HostId>
</Error>
```

## Expected Behavior

To preserve feature compatibility with the AWS S3 service, Minio should return the error code `NoSuchBucket` when a request is made for a bucket that does not exist. Here is a mock-up on what I believe should happen:

```
$ curl -s http://play.min.io/nosuckbucketname | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist</Message>
  <BucketName>nosuchbucketname</BucketName>
  <Resource>/nosuckbucketname</Resource>
  <RequestId>165B544FCA3A2006</RequestId>
  <HostId>cee624e3-ecd8-4c48-901a-74e259357f40</HostId>
</Error>
```

## Current Behavior

When requesting a bucket that does not exist, Minio returns `AccessDenied` as an error code; it should return `NoSuchBucket` to match AWS S3 functionality.

## Steps to Reproduce (for bugs)

```
curl -s http://play.min.io/nosuckbucketname | xmllint --format -
```

## Context

The departure from AWS S3 functionality prevents some tools from interacting with the Minio server as if it were an AWS S3 server.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

```
$ ./minio --version
minio version RELEASE.2021-01-16T02-19-44Z
$ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l

$ uname -a
Linux slingshot 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
This is not inconsistent it is as per AWS S3 behavior @joswr1ght 


```
~ curl https://s3.amazonaws.com/hello-this-is-unique-bucket
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>hello-this-is-unique-bucket</BucketName><RequestId>19B24D126E978303</RequestId><HostId>evH5mmTTvrYYIDehfke7tEnbFVa+ANQpm7Sne2rzWJI/tJaqZnvMh+dco8nyx5oIFEor/1cgohM=</HostId></Error>
```

**Comment by harshavardhana** [comment]
> $ curl -s http://play.min.io/nosuckbucketname | xmllint --format -
> <?xml version="1.0" encoding="UTF-8"?>
> <Error>
>   <Code>AccessDenied</Code>
>   <Message>Access Denied.</Message>
>   <BucketName>nosuckbucketname</BucketName>
>   <Resource>/nosuckbucketname</Resource>
>   <RequestId>165B544FCA3A2006</RequestId>
>   <HostId>cee624e3-ecd8-4c48-901a-74e259357f40</HostId>
> </Error>

The main reason here is that AWS S3 hits DNS but we have to the drives - 
an unauthenticated call hitting the drive is not a good idea. 

So we are not changing it @joswr1ght
