### ISSUE TITLE
MinIO select API for compressed object causing OOM for MinIO Server

### ISSUE THREAD

**Issue by RitikRajSrivastava** [minio/minio#11300]
## Expected Behavior
MinIO select API for compressed object must not cause OOM for MinIO server.

## Current Behavior
MinIO server resource is increasing and reaching the max resource allocated(i.e 10GB) and server restarts .

## Steps to Reproduce (for bugs)
Code snippet :

   public static String getCSVObjectHeader(String bucketName, String objectName, String contentType,
                                            MinioClient minioClient) throws Exception{
        try {
            String sqlExpression = "select * from S3Object limit 1";
            CompressionType compressionType = null;
            if("application/gzip".equalsIgnoreCase(contentType)
                    || "application/x-gzip".equalsIgnoreCase(contentType)){
                compressionType = CompressionType.GZIP;
            }
            InputSerialization is = new InputSerialization(compressionType, false, null, null, FileHeaderInfo.NONE, null, null, null);
            OutputSerialization os = new OutputSerialization(null, null, null, QuoteFields.ASNEEDED, null);
            SelectResponseStream stream =
                    minioClient.selectObjectContent(
                            SelectObjectContentArgs.builder()
                                    .bucket(bucketName)
                                    .object(objectName)
                                    .sqlExpression(sqlExpression)
                                    .inputSerialization(is)
                                    .outputSerialization(os)
                                    .requestProgress(true)
                                    .build());
            byte[] buf = new byte[2048];
            int bytesRead = stream.read(buf, 0, buf.length);
            String header =  (new String(buf, 0, bytesRead, StandardCharsets.UTF_8)).trim();
            stream.reset();
            stream.close();
            return header;
        } catch(Exception e) {
            System.out.println("Error retrieving header from S3 Object. ");
            throw e;
        }
   }

When fetched header for object, resource for MinIO sever increases gradually and terminates .
![image](https://user-images.githubusercontent.com/21273131/105008508-58044580-5a5f-11eb-8baf-b46b83e4ad3e.png)

When not using select API with same load, resource for MinIo server remains in some 100-300MB
![image](https://user-images.githubusercontent.com/21273131/105009067-0f00c100-5a60-11eb-96ee-16a9ac58fce8.png)

## Your Environment

* Version used (`minio --version`): 2021-01-05T05:22:38Z
* Server setup and configuration: 4 server with each having (4 CPU and 10GB RAM)
* Operating System and version (`uname -a`): Linux itom-di-minio-1 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
@RitikRajSrivastava What is your input? It looks like gzipped CSV data. What size, etc?

Is it possible for you to share a data sample that reproduces the issue?

**Comment by RitikRajSrivastava** [comment]
Hi @klauspost 
Records per Gzip file     | 140800
No of Gzip files/min         | 114
Total # of records / min | 16 Million Records
Gzip  file size in mb        |  5.6MB i.e. (100MB   Normal CSV)

Sample file :
[1610969034-Thread0-file27.csv.gz](https://github.com/minio/minio/files/5834839/1610969034-Thread0-file27.csv.gz)

**Comment by klauspost** [comment]
@RitikRajSrivastava I tried a simple reproducer uploading the file to my setup and executing `mc sql -query="select * from S3Object limit 1" local2/buck2/1610969034-Thread0-file27.csv.gz` continuously. The server goes up about 200MB in total, but keeps fairly steady.

Are you executing many queries in parallel or on many files?

**Comment by RitikRajSrivastava** [comment]
@klauspost , yeah we are executing some 20 queries in parallel on 20 different files.

**Comment by klauspost** [comment]
@RitikRajSrivastava Thanks for the info. On 1000 files it does exhibit a growing memory profile. I will see if I can locate where it happens.

**Comment by klauspost** [comment]
@RitikRajSrivastava #11302 has a fix for the leak. After this memory usage remains stable.

**Comment by RitikRajSrivastava** [comment]
Thanks a lot @klauspost @harshavardhana 
Apart from this one more issue observed : 
After some 6hr of testing on similar load, when  I try to remove an object, request fails with Okhttp Timeout exception .
When I checked the locks acquired. I got below output :
I have no name!@itom-di-minio-0:/minio> ./mc -C /minio admin top locks clientuser
Time Type Resource
20 hours READ nomperfbucket/1609776270-Thread4-file2254.csv.gz
18 hours WRITE nomperfbucket/1609786729-Thread5-file4741.csv.gz/934c2c97-15c7-416d-98f6-0faf7c56ad0e
18 hours READ nomperfbucket/1609786495-Thread1-file4610.csv.gz
18 hours READ nomperfbucket/1609786067-Thread4-file4512.csv.gz
18 hours READ nomperfbucket/1609786186-Thread1-file4538.csv.gz
18 hours READ nomperfbucket/1609786428-Thread2-file4596.csv.gz
18 hours READ nomperfbucket/1609786231-Thread1-file24801.csv.gz
18 hours READ nomperfbucket/1609786239-Thread1-file24803.csv.gz
18 hours READ nomperfbucket/1609786105-Thread3-file4523.csv.gz
18 hours READ nomperfbucket/1609786124-Thread5-file4598.csv.gz


Anything I am missing  ?

**Comment by harshavardhana** [comment]
> 18 hours READ nomperfbucket/1609786495-Thread1-file4610.csv.gz
> 18 hours READ nomperfbucket/1609786067-Thread4-file4512.csv.gz
> 18 hours READ nomperfbucket/1609786186-Thread1-file4538.csv.gz
> 18 hours READ nomperfbucket/1609786428-Thread2-file4596.csv.gz
> 18 hours READ nomperfbucket/1609786231-Thread1-file24801.csv.gz
> 18 hours READ nomperfbucket/1609786239-Thread1-file24803.csv.gz
> 18 hours READ nomperfbucket/1609786105-Thread3-file4523.csv.gz
> 18 hours READ nomperfbucket/1609786124-Thread5-file4598.csv.gz

Not sure if this leak in gzip has a side effect here @klauspost - probably since the stream is never closed.

**Comment by klauspost** [comment]
@harshavardhana No, it will never close upstream, that is not its responsibility.

It can miss that for errors, fixed here: https://github.com/minio/minio/pull/11302/commits/55cad66a19780bd95bdfa5d653193b93ffd95e59
