### ISSUE TITLE
[not a bug] Minio S3 Gateway caching expiry date is wrong . 

### ISSUE THREAD

**Issue by fsadoon** [minio/minio#11304]
dears : 

i used below configuration for minio gateway mode : 

MINIO_CACHE="on"
MINIO_CACHE_DRIVES="/home/miniogateway/"
MINIO_CACHE_QUOTA=80
MINIO_CACHE_EXPIRY=5
MINIO_CACHE_AFTER=0
MINIO_CACHE_WATERMARK_LOW=70
MINIO_CACHE_WATERMARK_HIGH=90
MINIO_ACCESS_KEY=
MINIO_SECRET_KEY=

cach.json output : 

"expires":"Mon, 01 Jan 0001 00:00:00 GMT"} 

any ideas ?

**Comment by klauspost** [comment]
Please fill out the appropriate template with your information: https://raw.githubusercontent.com/minio/minio/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by klauspost** [comment]
I suspect you are using an old version of MinIO. If so, upgrade and recheck as caching has changed a lot.

**Comment by fsadoon** [comment]
sorry, i'll use the templet in future issues .. 

not really, i used old version initially : 

./minio_old --version 
minio_old version RELEASE.2020-03-25T07-03-04Z


then i downloaded the newer version : 

 ./minio --version 
minio version RELEASE.2021-01-16T02-19-44Z


i just downloaded latest version and start the script from there .. is there a specific way to upgrade it or my way is ok ?

**Comment by fsadoon** [comment]
dears .. 

i tried to initiate a new server with another S3 environment and still i can see same wrong date, 
just to eliminate the S3 endpoint

**Comment by klauspost** [comment]
AFAIK the field doesn't exist anymore and is just handled by MinIO.

Try wiping the cache and observe new entries.

**Comment by fsadoon** [comment]
if you are pointing to " wiping the cached files from MinIO cache disk " i've already done that .. 
let me do one thing .. i will provision a new VM and build latest version of Minio and i'll get back with the results 

Regards

**Comment by fsadoon** [comment]
i did the following : 

fresh VM with latest MinIO Linux version, with default gateway configuration and here is the cache.json out put : 


`{"version":"1.0.0","stat":{"size":51362,"modTime":"2021-01-23T00:27:49.48909467Z"},"checksum":{"algorithm":"highwayhash256S","blocksize":1048576},"meta":{"Content-Type":"image/jpeg","content-type":"image/jpeg","etag":"9b88d12a123f7f7bdf14ab4793996fdb","expires":"Mon, 01 Jan 0001 00:00:00 GMT"},"hits":1,"bucket":"testbucket","object":"IMG_2458 (1).jpg"}`


you can see the expires date still showing a wrong date

**Comment by poornas** [comment]
I'm not sure why you're looking at the cache.json here - the expires metadata that you see in the cache.json refers to the "Expires" cache control HTTP header if any that is returned by S3 on a GET. If such a header is present and cached, the cache honors that and clears any stale entry and reverts to backend on a GET.  The "expires" that you see in the metadata here is redundant, and would be used only if it had a valid date.

The  MINIO_CACHE_EXPIRY env variable is no longer used as the MINIO_CACHE_WATERMARK_* are used to automatically decide when to purge stale content as the cache size approaches the high watermark. Please refer to latest docs [here](https://github.com/minio/minio/tree/master/docs/disk-caching)

**Comment by harshavardhana** [comment]
Closing the issue as per the last comment
