### ISSUE TITLE
web: Running minio in a docker container behind a proxy

### ISSUE THREAD

**Issue by alexanderjulo** [minio/minio#1130]
Currently I am trying to run minio in a docker container behind a proxy (I am using caddy for this).

While I was able to get some basic functionality to work, anything API related does not seem to work because it seems to be basing on the localhost still:

![screen shot 2016-02-16 at 00 00 51](https://cloud.githubusercontent.com/assets/144562/13062709/d36b36f2-d440-11e5-81e7-40d930d36b42.png)

I also tried setting minio to use my host using `--address`, but as the docker container does not have this IP assigned this also does not work:

```
ERRO[0000] Failed to start the minio server.             Error={Cause:listen tcp 46.101.127.4:5000: bind: cannot assign requested address Type:*net.OpError CallTrace:[{Line:161 Filename:vendor/github.com/minio/minio-xl/pkg/minhttp/net.go Function:minhttp.(*minNet).ListenTCP Env:map[]} {Line:54 Filename:vendor/github.com/minio/minio-xl/pkg/minhttp/http_nix.go Function:minhttp.(*app).listen Env:map[]} {Line:137 Filename:vendor/github.com/minio/minio-xl/pkg/minhttp/http_nix.go Function:minhttp.ListenAndServe Env:map[]} {Line:341 Filename:server-main.go Function:main.serverMain Env:map[]}] SysInfo:map[host.os:linux host.cpus:2 mem.total:4.5MB mem.heap.used:926kB mem.heap.total:1.7MB host.arch:amd64 host.name:e70461482f87 host.lang:go1.5.1 mem.used:926kB]}
```

I'd really like this to work and I'd be open to both doing some weird rewrite magic and to a configuration option for minio to use my custom domain hostname, although I'd prefer the latter.

I am not really an expert on the matter, so please let me know whether you need anything more than what was provided in this post so far.

Thank you already for working on minio, I think it is a really cool project and I am looking forward to using it. I am also happy to provide some examples or anything else that might be helpful!

**Comment by klausenbusk** [comment]
Have you tried starting minio with `--address 0.0.0.0:9000`?

**Comment by alexanderjulo** [comment]
Good question!. I have now. Creating a bucket seems to work, but when I try to upload a file, the following error appears:

`missing port in address drop.julo.ch (0) web-handlers.go:163 main.getTargetHost(..) Release-Tag:UNOFFICIAL.2016-02-08T00-59-00Z | Commit-ID:e79a73a3f5fa9b0111ecf2620be84ff5f3e9698a | Docker-Image:true | Host:68c97088e262 | OS:linux | Arch:amd64 | Lang:go1.5.1 | Mem:1.2MB/8.8MB | Heap:1.2MB/5.7MB`

Which might be due to the fact that I have it on default ports (80/443) where the ports are not usually specifically explicitly named.

**Comment by klausenbusk** [comment]
> Which might be due to the fact that I have it on default ports (80/443) where the ports are not usually specifically explicitly named.

I think you correct. Currently the API can't handle request where the targetHost parameter is missing the port. 
Relevant code: https://github.com/minio/minio/blob/76ac78c0eb4b2c87a791fc1aeb07caea9629b8f0/web-handlers.go#L169
and the minion browser use `window.location.host` which strip port if port == 80/44
https://github.com/minio/miniobrowser/blob/5b914dd55dbfa0c4a99446422908eb54f4d40dc4/app/js/actions.js#L226

**Comment by krishnasrinivas** [comment]
@alexex @klausenbusk thanks, we'll fix this!

**Comment by alexanderjulo** [comment]
@krishnasrinivas that'd be amazing, thanks!

**Comment by harshavardhana** [comment]
@alexex - can you share your nginx/proxy configuration? - oh i see that's caddy no worries that should be simple enough.

**Comment by alexanderjulo** [comment]
```
drop.julo.ch {
    tls alexander@julo.ch

    proxy / drop:9000 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }

    redir /browser /browser/ 301

    proxy /browser/ drop:9001 {
        without /browser
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }

    proxy /rpc drop:9001 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
}
```

Something like this @harshavardhana :-)

But it is obviously made for the 2 port design, I don't think it'd apply anymore. Let me know whenever you have something ready for testing, I'm glad to help

**Comment by harshavardhana** [comment]
> drop.julo.ch {
>     tls alexander@julo.ch
> 
> ```
> proxy / drop:9000 {
>     proxy_header Host {host}
>     proxy_header X-Real-IP {remote}
>     proxy_header X-Forwarded-Proto {scheme}
> }
> 
> redir /browser /browser/ 301
> 
> proxy /browser/ drop:9001 {
>     without /browser
>     proxy_header Host {host}
>     proxy_header X-Real-IP {remote}
>     proxy_header X-Forwarded-Proto {scheme}
> }
> 
> proxy /rpc drop:9001 {
>     proxy_header Host {host}
>     proxy_header X-Real-IP {remote}
>     proxy_header X-Forwarded-Proto {scheme}
> }
> ```
> 
> }
> Something like this @harshavardhana :-)
> 
> But it is obviously made for the 2 port design, I don't think it'd apply anymore. Let me know whenever you have something ready for testing, I'm glad to help

If you can build the latest source you can test it locally, you might have to get a new asset file from `miniobrowser` project as well. 

Here is the simple caddy config i used. 

```
cat Caddyfile
10.0.0.3:2015 {
    proxy / localhost:9000 {
        proxy_header Host {host}
    }
    tls off
}
```

**Comment by harshavardhana** [comment]
Thanks @alexex

**Comment by alexanderjulo** [comment]
@harshavardhana I already tried to build the source once locally and kind of failed spectacularly, don't know why, but I am not exactly a go expert, I will try to verify as soon as there is some kind of build available, i.e. a pre-release or whatever. :-)

**Comment by harshavardhana** [comment]
> @harshavardhana I already tried to build the source once locally and kind of failed spectacularly, don't know why, but I am not exactly a go expert, I will try to verify as soon as there is some kind of build available, i.e. a pre-release or whatever. :-)

Can you paste the issues that you faced?  To build Go packages always has initial trouble of setting up proper GOPATH's, but we tried our best to sufficiently document them.  Let us know, we will be able to improve our docs.

**Comment by alexanderjulo** [comment]
This should be fixed now. :-)
