### ISSUE TITLE
Disable ability to login with MINIO_ROOT_PASSWORD when LDAP Integration is Enabled

### ISSUE THREAD

**Issue by davemsolomon** [minio/minio#11319]
I would like for login attempts with the MINIO_ROOT credentials to be rejected when the LDAP Integration is enabled. 

It seems to me that having a set of static super-user credentials (MINIO_ROOT) that are usable from the minio GUI poses an unnecessary security risk and does not seem like enterprise-grade security. The value of the LDAP Integration lies in the ability to move user credential management outside of the platform. 

You may ask, if the MINIO_ROOT credentials are not usable then how will it be possible to administer the platform? If the instance needs to be administered then simply start the instance without the LDAP Integration, perform the administration with the MINIO_ROOT credentials then shut down the instance and start it again with the LDAP Integration.

**Comment by harshavardhana** [comment]
@davemsolomon that is not possible because root credentials are used for 

- encrypting credentials
- communicating between nodes (authentication)

Root credentials are never meant to be shared with the client so using them should be restricted at the deployment level. Other than that we cannot really have it disabled.

**Comment by davemsolomon** [comment]
@harshavardhana would you be so kind as to share your thoughts on below?

I assume (but could be wrong) that what I am requesting could be achieved without impacting your two items listed above. 

With respect to encrypting credentials, I would think that credentials could continue to be encrypted using MINIO_ROOT but still disallow consumer calls with those credentials. 

With respect to inter-node communication, if system level inter-node communication uses the MINIO_ROOT credentials then that is fine assuming system level inter-node communication can be distinguished from consumer level traffic.

**Comment by harshavardhana** [comment]
> @harshavardhana would you be so kind as to share your thoughts on below?

@davemsolomon right now its not feasible for us to do, we can revisit this some time in future if needed. But right now we have other priorities.

**Comment by davemsolomon** [comment]
@harshavardhana I understand, of course. Thank you for your attention to my concern!
