### ISSUE TITLE
web: Improve "Minio Browser"

### ISSUE THREAD

**Issue by klausenbusk** [minio/minio#1131]
Add option to:
- Delete object.
- Create folder.
- Delete bucket.

**Comment by harshavardhana** [comment]
> Add option to:
> 
> Delete object.
> Create folder.
> Delete bucket.

These are intentionally left out for the time being until we bring in a way to recover a deleted object, otherwise deletes UI become simpler and can lead to at times unintentional data loss.

**Comment by klausenbusk** [comment]
> otherwise deletes UI become simpler and can lead to at times unintentional data loss.

Can't you just add a big red confirm box? Where people need to type in the bucket name, before they can delete?

**Comment by harshavardhana** [comment]
> Can't you just add a big red confirm box? Where people need to type in the bucket name, before they can delete?

It doesn't matter even in that scenario you might end up deleting accidentally, in our experience deleting accidently and not being able to recover is more costly. But definitely this will be implemented subsequently as we stabilize on more important aspects of the UI.

**Comment by harshavardhana** [comment]
Superseeded by - https://github.com/minio/miniobrowser/issues/154

**Comment by nii236** [comment]
What about creating folders? #154 only covers deletion
