### ISSUE TITLE
Pre-signed PutObject operation fails with signature error (same client code works on AWS S3)

### ISSUE THREAD

**Issue by ecarrara** [minio/minio#11317]
We have noticed an incompatibility between MinIO and AWS S3. The code below works fine on AWS S3 but fails on MinIO with a `SignatureDoesNotMatch` error:

```python
import boto3, os

AWS_ENDPOINT_URL = "http://127.0.0.1:9000"
BUCKET = "bucket1"

s3_client = boto3.client("s3", endpoint_url=AWS_ENDPOINT_URL)
url = s3_client.generate_presigned_url(
    "put_object",
    Params=dict(Bucket=BUCKET, Key="test.txt", Metadata={"test": "42"}),
    ExpiresIn=3600, HttpMethod="PUT",)

with open('./a.txt', 'w') as f:
    f.write('test')
os.system(f"curl -T ./a.txt '{url}'")
```

Pre-signed URL: http://127.0.0.1:9000/bucket1/teste.txt?AWSAccessKeyId=minioadmin&Signature=X2wmK7WRucZ925NRnquG5LlMATI%3D&x-amz-meta-teste=42&Expires=1611170499

MinIO response:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <Key>test.txt</Key>
  <BucketName>bucket1</BucketName>
  <Resource>/bucket1/test.txt</Resource>
  <RequestId>165C03393A891A51</RequestId>
  <HostId>2e68410e-dedd-4e43-904f-109aeaf143db</HostId>
</Error>
```

I think this kind of problem has been reported many times (issues #1059, #5726, #5857).

If I add the x-amz-meta-test: 54 header to the request everything works (as pointed by @harshavardhana https://github.com/minio/minio/issues/5726#issuecomment-376965451):

```python
# ...
os.system(f"curl -T ./a.txt -H 'x-amz-meta-test: 42' '{url}'")
```

But I think this is a bug because the official S3 API does not require this header again in the second request (the x-amz-meta-test is already in query-string).

## Expected Behavior

Upload succeeds.

## Current Behavior

Requests using pre-signed URLs for PutObject operations requires x-amz-meta-* headers. Official AWS S3 API works without this limitation.

## Possible Solution

A workaround to that problem might be to simply "copy" metadata query string to r.Header before signature verification.

```diff
diff --git a/cmd/object-handlers.go b/cmd/object-handlers.go
index 087dbfe8d..640fec434 100644
--- a/cmd/object-handlers.go
+++ b/cmd/object-handlers.go
@@ -1419,6 +1419,13 @@ func (api objectAPIHandlers) PutObjectHandler(w http.ResponseWriter, r *http.Req
return
}

+ // [hot-fix] Force query-string metadata to be present in request headers too
+ var queryStringMetadata = make(map[string]string)
+ extractMetadataFromMap(ctx, r.URL.Query(), queryStringMetadata)
+ for metadataKey, metadataValue := range queryStringMetadata {
+ r.Header.Add(metadataKey, metadataValue)
+ }
+
switch rAuthType {
case authTypeStreamingSigned:
// Initialize stream signature verifier.
```

## Context

Our HTTP backend generates pre-signed URLs that is used by clients to upload objects direct to S3. The metadata is added by backend (our client don't know the metadata values beforehand).

## Regression

I don't know.

## Your Environment

* Version used (`minio --version`): minio version DEVELOPMENT.2021-01-20T18-11-36Z
* Server setup and configuration: default settings
* Operating System and version (`uname -a`): Linux 5.9.14-arch1-1

**Comment by harshavardhana** [comment]
> ```diff
> diff --git a/cmd/object-handlers.go b/cmd/object-handlers.go
> index 087dbfe8d..640fec434 100644
> --- a/cmd/object-handlers.go
> +++ b/cmd/object-handlers.go
> @@ -1419,6 +1419,13 @@ func (api objectAPIHandlers) PutObjectHandler(w http.ResponseWriter, r *http.Req
> return
> }
> 
> + // [hot-fix] Force query-string metadata to be present in request headers too
> + var queryStringMetadata = make(map[string]string)
> + extractMetadataFromMap(ctx, r.URL.Query(), queryStringMetadata)
> + for metadataKey, metadataValue := range queryStringMetadata {
> + r.Header.Add(metadataKey, metadataValue)
> + }
> ```

This is already handled internally @ecarrara you shouldn't need to do this. Let me check the code locally.

**Comment by harshavardhana** [comment]
> Pre-signed URL: http://127.0.0.1:9000/bucket1/teste.txt?AWSAccessKeyId=minioadmin&Signature=X2wmK7WRucZ925NRnquG5LlMATI%3D&x-amz-meta-teste=42&Expires=1611170499
> 
> MinIO response:

Ah you are using signature v2 - just use signature v4 @ecarrara it will work fine.  Not sure why anyone uses signature v2 still.

**Comment by ecarrara** [comment]
Hi @harshavardhana

Thank you for your quick reply!

> > Pre-signed URL: http://127.0.0.1:9000/bucket1/teste.txt?AWSAccessKeyId=minioadmin&Signature=X2wmK7WRucZ925NRnquG5LlMATI%3D&x-amz-meta-teste=42&Expires=1611170499
> > MinIO response:
> 
> Ah you are using signature v2 - just use signature v4 @ecarrara it will work fine. Not sure why anyone uses signature v2 still.

I think many projects are still using v2 because it is the default version used in boto3 python library. In our project we use v4 and a library called aiobotocore but I have created a minimal script to reproduce de bug using the official library provided by AWS to report it here.

And we've tried using v4 too, same error:

```python
import boto3, os
from botocore.client import Config

AWS_ENDPOINT_URL = "http://127.0.0.1:9000"
BUCKET = "bucket1"

s3_client = boto3.client( "s3", endpoint_url=AWS_ENDPOINT_URL, config=Config(signature_version="s3v4"))
url = s3_client.generate_presigned_url(
    "put_object",
    Params=dict(Bucket=BUCKET, Key="teste.txt", Metadata={"teste": "42"}),
    ExpiresIn=3600,  HttpMethod="PUT")

print(url)
with open("/tmp/a.txt", "w") as f:
    f.write("test contents")
os.system(f"curl -T /tmp/a.txt '{url}'")
```

```shellscript
python metadata_bug.py
http://127.0.0.1:9000/bucket1/teste.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210121%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210121T005937Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host%3Bx-amz-meta-teste&X-Amz-Signature=2320d94801557ca19874532ccba7e6611246b8865256def3e7b76ffc0fe9af0c
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>There were headers present in the request which were not signed</Message>
  <Key>teste.txt</Key>
  <BucketName>bucket1</BucketName>
  <Resource>/bucket1/test.txt</Resource><RequestId>165C1979D78AEE54</RequestId><HostId>899f6df0-7370-469b-ba6b-c4753698a787</HostId></Error>
```

In this specific case, does MinIO have a S3 compatible API? The code above works fine with AWS S3.

**Comment by harshavardhana** [comment]
> http://127.0.0.1:9000/bucket1/teste.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210121%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210121T005937Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host%3Bx-amz-meta-teste&X-Amz-Signature=2320d94801557ca19874532ccba7e6611246b8865256def3e7b76ffc0fe9af0c
> <?xml version="1.0" encoding="UTF-8"?>
> <Error>
>   <Code>AccessDenied</Code>
>   <Message>There were headers present in the request which were not signed</Message>
>   <Key>teste.txt</Key>
>   <BucketName>bucket1</BucketName>
>   <Resource>/bucket1/test.txt</Resource><RequestId>165C1979D78AEE54</RequestId><HostId>899f6df0-7370-469b-ba6b-c4753698a787</HostId></Error>

The issue here that `x-amz-meta` is not handled in the query param for some reason @ecarrara because it was added as part of x-amz-signed-headers. 

As a workaround 

```
import boto3
import os

from botocore.client import Config

s3_client = boto3.client('s3',
                         endpoint_url='http://localhost:9000',
                         aws_access_key_id='minio',
                         aws_secret_access_key='minio123',
                         config=Config(signature_version="s3v4"),
                         region_name='us-east-1')
BUCKET = "bucket1"

url = s3_client.generate_presigned_url(
    "put_object",
    Params=dict(Bucket=BUCKET, Key="test.txt", Metadata={"test": "42"}),
    ExpiresIn=3600,  HttpMethod="PUT")

print(url)
with open("/tmp/a.txt", "w") as f:
    f.write("test contents")
os.system(f"curl -H 'x-amz-meta-test: 42' -T /tmp/a.txt '{url}'")
```

> I think many projects are still using v2 because it is the default version used in boto3 python library. In our project we use v4 and a library called aiobotocore but I have created a minimal script to reproduce de bug using the official library provided by AWS to report it here.

That is really sad! - unfortunately, we wish to not do anything with signature v2 sorry!.

**Comment by harshavardhana** [comment]
Okay here is the problem your request says 

> http://localhost:9000/bucket1/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20210121%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210121T015256Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host%3Bx-amz-meta-test&X-Amz-Signature=5e8742725136cd575c743c62215591c45f9b681bbd270c98c1d2e074aac5b4e4


Now here you have added `x-amz-meta-test` as a signed header but it is not part of either query() param or it is part of HTTP header in the request. 

There is no way we can validate this request - so the correct way to do it is 

```py
import boto3
import os

from botocore.client import Config

s3_client = boto3.client('s3',
                         endpoint_url='http://localhost:9000',
                         aws_access_key_id='minio',
                         aws_secret_access_key='minio123',
                         config=Config(signature_version="s3v4"),
                         region_name='us-east-1')
BUCKET = "bucket1"

url = s3_client.generate_presigned_url(
    "put_object",
    Params=dict(Bucket=BUCKET, Key="test.txt", Metadata={"test": "42"}),
    ExpiresIn=3600,  HttpMethod="PUT")

print(url)
with open("/tmp/a.txt", "w") as f:
    f.write("test contents")
os.system(f"curl -H 'x-amz-meta-test: 42' -T /tmp/a.txt '{url}'")
```

By adding the actual header you wish to upload.

It works with AWS S3 is actually a bug they seem to ignore their own SPEC published regarding AWS S3v4.  boto3 is also foolishly not indicating that what you should do if you add metadata and silently signs it but never adds as part of the query param.

So in both situations this is not a bug, MinIO is handling it perfectly as per the spec.

**Comment by ecarrara** [comment]
@harshavardhana  thanks again for the proposed workaround!

Like I wrote previously, in our system the client code (program that receive the pre-signed URL) do not know the header values beforehand. For example, the backend adds the metadata "track-id: <generated-uuid-v4>" to PutObject operation and keeps a track of this in our database. When the client code upload the object to S3 we receive a notification (SQS in AWS, Webhook in MinIO) and do an update in our database based on track-id metadata previous generated.

And yeah! I agree with you that this can be a bug in AWS side! But it would be really nice if MinIO could replicate this bug to be fully S3-compatible.

**Comment by harshavardhana** [comment]
> Like I wrote previously, in our system the client code (program that receive the pre-signed URL) do not know the header values beforehand.

if you don't know the values it cannot be validated such a request is malicious @ecarrara - unfortunately, if you add metadata as part of the `presign` it needs to be presented when you are uploading including the values. 

That is the AWS S3 Signature v4 spec and we respect that.

**Comment by ecarrara** [comment]
> if you don't know the values it cannot be validated such a request is malicious

I disagree with this part.. our client code and backend trust each-other using a HTTPS connection, if our backend returned a pre-signed URL that contains metadata our client will trust in this URL.

> unfortunately, if you add metadata as part of the presign it needs to be presented when you are uploading including the values.

I totally agree with this! Of course this have to be included to be used in sign verification. boto3 add this metadata into url query string. But the MinIO behavior is different that AWS S3 API behavior. MinIO does not use metadata present in query string to calculate the signature but use it later to persist the metadata information.

In AWS S3 they use the `x-amz-meta-*` values in the query-string to calculate the signature as if they were sent in the header.

It would be nice if the MinIO had a flag/settings to replicate this AWS bug. What do you think about that?

**Comment by harshavardhana** [comment]
> In AWS S3 they use the `x-amz-meta-*` values in the query-string to calculate the signature as if they were sent in the header.

Yes but we already do that too @ecarrara the boto3 is not adding it as shown and even your example doesn't add it. 

> http://127.0.0.1:9000/bucket1/teste.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210121%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210121T005937Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host%3Bx-amz-meta-teste&X-Amz-Signature=2320d94801557ca19874532ccba7e6611246b8865256def3e7b76ffc0fe9af0c

There is no `x-amz-meta-test` added here. 

> I disagree with this part.. our client code and backend trust each-other using a HTTPS connection, if our backend returned a pre-signed URL that contains metadata our client will trust in this URL.
> 
> >

It is malicious if AWS S3 accepts a client request when it says that header is signed and client doesn't present the header.

**Comment by harshavardhana** [comment]
The main reason here is AWS S3 spec is not clear on how should a canonical request be generated in this situation -

for example, adding a manual metadata entry in the query param means that it is expecting somehow the query string to be the actual signature or is it expected to be in the HEADER. Both have different outcomes. 

So we have no way of predicting this and we do not wish to do it outside of what is written in the SPEC v/s how it actually behaves. 

It is a very kludgy way to do things, so it is better for you to set the HTTP header this way we are aware of the intention from the client

> ```diff
> diff --git a/cmd/object-handlers.go b/cmd/object-handlers.go
> index 087dbfe8d..640fec434 100644
> --- a/cmd/object-handlers.go
> +++ b/cmd/object-handlers.go
> @@ -1419,6 +1419,13 @@ func (api objectAPIHandlers) PutObjectHandler(w http.ResponseWriter, r *http.Req
> return
> }
> 
> + // [hot-fix] Force query-string metadata to be present in request headers too
> + var queryStringMetadata = make(map[string]string)
> + extractMetadataFromMap(ctx, r.URL.Query(), queryStringMetadata)
> + for metadataKey, metadataValue := range queryStringMetadata {
> + r.Header.Add(metadataKey, metadataValue)
> + }
> ```

The fix presented here is blind to the fact,  can actually end up adding all kinds of metadata - also overwriting legitimate data that may be present in the HTTP header, basically, you are maliciously triggering behavior change on the server. 

These kinds of things are going to be problematic for MinIO.
