### ISSUE TITLE
AD/LDAP & Vault Integration in MinIO

### ISSUE THREAD

**Issue by dasaratharajkumar** [minio/minio#11316]
AD/LDAP & Vault Integration in MinIO

I am referring to the below link and proceeding the same. now got stuck in the last step "go run ldap.go -u foouser -p foopassword"

https://github.com/minio/minio/blob/master/docs/sts/ldap.md

Issue what I am facing is that the ldap.go file is trying to access some plugin and says that there is no such version. but I could see that particular version in the given link. 
Output: go: git.apache.org/thrift.git@v0.13.0: reading git.apache.org/thrift.git/go.mod at revision v0.13.0: unknown revision v0.13.0

Not sure on how to proceed further.

* Version used (`minio --version`): minio version RELEASE.2020-12-18T03-27-42Z
* Server setup and configuration: RHEL7 -8CPU-16GB RAM
* Operating System and version (`uname -a`): 3.10.0-1160.6.1.el7.x86_64

**Comment by harshavardhana** [comment]
You need to first have Go installed properly and set GO111MODULE=on as environment variable

Once that is done it should work fine

**Comment by dasaratharajkumar** [comment]
I could see that the Go env GO111MODULE is set to "on"

GO111MODULE="on"

Also Go was installed properly with all its dependencies. Still the same  error pops.

**Comment by harshavardhana** [comment]
Runs perfectly fine for me 

```
~ go run ldap.go 
  -p string
        AD/LDAP Password
  -sts-ep string
        STS endpoint (default "http://localhost:9000")
  -u string
        AD/LDAP Username
```
