### ISSUE TITLE
Suggestion: Expiry policy based on number of access

### ISSUE THREAD

**Issue by SrMouraSilva** [minio/minio#11315]
**Is your feature request related to a problem? Please describe.**
I'm searching a way to block the access to a specific file by a number of access, but I don't found it. Only discover restriction by time.

**Describe the solution you'd like**
A way to enable file access by number of access (number of requests to the url generated) **and** by time.

**Describe alternatives you've considered**
I've considered to define a very small time, but I'm not sure that this solution is feasible...
Another alternative is to apply a manual logic and request that minio removes the old file address, if it is possible.

**Comment by klauspost** [comment]
There is no built in functionality for this and likely will not be. Updating data on every access will be resource intensive and goes against the goal of MinIO.

Instead it can be implemented as a third party tool using a logging target. See more here: https://github.com/minio/minio/tree/master/docs/logging

**Comment by SrMouraSilva** [comment]
Thanks, @klauspost!
