### ISSUE TITLE
MINIO_PROMETHEUS_AUTH_TYPE=public still requires auth 

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11324]
if you set` export MINIO_PROMETHEUS_AUTH_TYPE="public"` this has no effect and returns authentication needed  (via curl or HTTPS)

Documentation followed (as per all of our other deployments) https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md 

## Expected Behavior
This should be fully unauthenticated 

## Current Behavior
If you set this to public authentication is still required. 

## Steps to Reproduce (for bugs)

1. Set export MINIO_PROMETHEUS_AUTH_TYPE="public" as per the documentation
https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md 

## Context
Trying to expose metrics for scraping 

## Regression
Yes working prior to 2021-01-08T21:18:21Z

## Your Environment

* Version used (`minio --version`): 2021-01-08T21:18:21Z
* Server setup and configuration: 24 Node cluster with 
* Operating System and version (`uname -a`): Ubuntu 18 

Notes: 

This was also reported and closed here: https://github.com/minio/minio/issues/11321 
Documentation followed: https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md

If you visit https://play.min.io:9000/minio/prometheus/metrics/cluster this used to work but no longer works and requires auth

**Comment by harshavardhana** [comment]
> If you visit https://play.min.io:9000/minio/prometheus/metrics/cluster this used to work but no longer works and requires auth

Not released yet @zapto2600

**Comment by zapto2600** [comment]
Im not sure why you closed this? This has been in releases for a while now and is a regression.

**Comment by harshavardhana** [comment]
> Im not sure why you closed this? This has been in releases for a while now and is a regression.

Because you are referring to master documentation read it here https://github.com/minio/minio/tree/RELEASE.2021-01-16T02-19-44Z/docs/metrics/prometheus

**Comment by zapto2600** [comment]
However this has been a feature since 2018.... So is a regression just because I have referenced the master documentation is not a good shout to close a ticket for a bug. 

https://blog.min.io/monitor-minio-server-with-prometheus/

**Comment by harshavardhana** [comment]
> If you visit https://play.min.io:9000/minio/prometheus/metrics/cluster this used to work but no longer works and requires auth

Just updated play to latest master 

> However this has been a feature since 2018.... So is a regression just because I have referenced the master documentation is not a good shout to close a ticket for a bug.
> 
> https://blog.min.io/monitor-minio-server-with-prometheus/

It is not a bug we have changed things in the master but we still support older endpoint and also updated the endpoint link c080f04e661d38b87c3487362067114e6461517b

**Comment by harshavardhana** [comment]
Old endpoint 

```
~ curl -s https://play.min.io:9000/minio/prometheus/metrics | grep minio_versi
# HELP minio_version_info Version of current MinIO server instance
# TYPE minio_version_info gauge
minio_version_info{commit="00cf9686cdda789b72a1e2b77cddedba3c2604ca",version="2021-01-22T09:43:54Z"} 1
```

New endpoint

```
~ curl -s https://play.min.io:9000/minio/v2/metrics/cluster | grep minio_software
# HELP minio_software_commit_info Git commit hash for the MinIO release.
# TYPE minio_software_commit_info gauge
minio_software_commit_info{commit="00cf9686cdda789b72a1e2b77cddedba3c2604ca",server="127.0.0.1:9000"} 0
# HELP minio_software_version_info MinIO Release tag for the server
# TYPE minio_software_version_info gauge
minio_software_version_info{server="127.0.0.1:9000",version="2021-01-22T09:43:54Z"} 0
```

Going to stop conversating on this, read the documentation for the release directly. If not build MinIO from master to refer to master documentation. @zapto2600

**Comment by zapto2600** [comment]
le sigh. If you try and use the master documentation against play it is still wrong and requires auth. Either its a bug or your documentation is incorrect. 

Either way one of them needs to be fixed. Good way to peeve off a potential customer.

**Comment by harshavardhana** [comment]
> Either way one of them needs to be fixed. Good way to peeve off a potential customer.

I just updated it, feel free to look again.
