### ISSUE TITLE
Why can't I find this article about Federation in the official document directory?

### ISSUE THREAD

**Issue by oiar** [minio/minio#11325]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi all! Why can't I find this article about Federation in the official document directory? 
(https://docs.min.io/docs/minio-federation-quickstart-guide.html)

But I can find it on GitHub.
(https://github.com/minio/minio/blob/master/docs/federation/lookup/README.md)

**Comment by harshavardhana** [comment]
Federation is not recommended anymore - you are supposed to use `pool` based expansion, 
the federation is needed only for really high scale deployments. 

> Hi all! Why can't I find this article about Federation in the official document directory?
> (https://docs.min.io/docs/minio-federation-quickstart-guide.html)

This document is from GitHub @oiar

**Comment by oiar** [comment]
Hello，I've a question about minio tenant expand. I learned that we can extends the total capacity of a MinIO Tenant by adding a new Pool, but this is just an expansion on the basis of a cluster. What should I do if I need to increase node more than 32 ? Should we add a new cluster or ignore the number of nodes in a cluster? I will be very grateful if I can receive your reply.
