### ISSUE TITLE
"Bad Request" For Accessing a 'Read-Only' Bucket with Wrong Authorization

### ISSUE THREAD

**Issue by LawyZheng** [minio/minio#11323]
"Bad Request" For Accessing 'Read-Only' Bucket with Authorization.
I created a bucket with a "Read-Only" policy and uploaded some objects.
When I tried to send a request with random  "Authorization" in headers, I got `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.` error. 
BTW, it works as intended if I send a request without "Authorization".

## Expected Behavior

It might be a bug to me. Even if the "Authorization" might be wrong,  I don't need to authorize the "getting object" request with its headers anymore, because the bucket has already been set to "Read-only" Policy.

## Current Behavior

Response with `400 status` saying `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

## Steps to Reproduce (for bugs)

1. create a bucket, and upload an object
2. set the bucket policy to "Read-only"
3. send a request with WRONG Authorization in headers to get the object
4. get a `Bad Request` error. 

## Possible Solution

I tried to fix this bug with a very simple solution in `cmd/auth-handler.go`.
I hope it could help.

**Firstly, I find that the requests with WRONG Authorization will be recognized as `authTypeUnknown`, while the requests without Authorization will be recognized as `authTypeAnonymous`** 
```go
// cmd/auth-handler.go Line 100
func getRequestAuthType(r *http.Request) authType {
	if isRequestSignatureV2(r) {
		return authTypeSignedV2
	} else if isRequestPresignedSignatureV2(r) {
		return authTypePresignedV2
	} else if isRequestSignStreamingV4(r) {
		return authTypeStreamingSigned
	} else if isRequestSignatureV4(r) {
		return authTypeSigned
	} else if isRequestPresignedSignatureV4(r) {
		return authTypePresigned
	} else if isRequestJWT(r) {
		return authTypeJWT
	} else if isRequestPostPolicySignatureV4(r) {
		return authTypePostPolicy
	} else if _, ok := r.URL.Query()[xhttp.Action]; ok {
		return authTypeSTS
	} else if _, ok := r.Header[xhttp.Authorization]; !ok {
		return authTypeAnonymous
	}
	return authTypeUnknown
}
```

 **Secondly, I find that the `authTypeUnknown` request will be returned with `ErrSignatureVersionNotSupported`, while `authTypeAnonymous` request will be handled with `Supported S3 AuthType`** 

```go
// cmd/auth-handler.go Line 524
func setAuthHandler(h http.Handler) http.Handler {
	// handler for validating incoming authorization headers.
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		aType := getRequestAuthType(r)
		if isSupportedS3AuthType(aType) {
			// Let top level caller validate for anonymous and known signed requests.
			h.ServeHTTP(w, r)
			return
		} else if aType == authTypeJWT {
			// Validate Authorization header if its valid for JWT request.
			if _, _, authErr := webRequestAuthenticate(r); authErr != nil {
				w.WriteHeader(http.StatusUnauthorized)
				return
			}
			h.ServeHTTP(w, r)
			return
		} else if aType == authTypeSTS {
			h.ServeHTTP(w, r)
			return
		}
		writeErrorResponse(r.Context(), w, errorCodes.ToAPIErr(ErrSignatureVersionNotSupported), r.URL, guessIsBrowserReq(r))
	})
}
```

**Next,  I add the `authTypeUnknown` to `supportedS3AuthTypes` struct, in order to handle `authTypeUnknown` in the same way as `authTypeAnonymous` does.** 
```go
// cmd/auth-handler.go Line 506
var supportedS3AuthTypes = map[authType]struct{}{
	authTypeAnonymous:       {},
	authTypePresigned:       {},
	authTypePresignedV2:     {},
	authTypeSigned:          {},
	authTypeSignedV2:        {},
	authTypePostPolicy:      {},
	authTypeStreamingSigned: {},
	authTypeUnknown:         {}, // I added "authTypeUnknown". 
}
```

**Then, I still find the request will be responded with `400 status` because the `checkRequestAuthTypeToAccessKey` function still handles the `authTypeUnknown` with `400 status`**
I tried to handle `authTypeUnknown` according to its policy.

```go
// cmd/auth-handler.go Line 284
func checkRequestAuthTypeToAccessKey(ctx context.Context, r *http.Request, action policy.Action, bucketName, objectName string) (accessKey string, owner bool, s3Err APIErrorCode) {
	var cred auth.Credentials
	switch getRequestAuthType(r) {
	case authTypeUnknown:
		if action != policy.ListAllMyBucketsAction && cred.AccessKey == "" {
			// Anonymous checks are not meant for ListBuckets action
			if globalPolicySys.IsAllowed(policy.Args{
				AccountName:     cred.AccessKey,
				Action:          action,
				BucketName:      bucketName,
				ConditionValues: getConditionValues(r, "", "", nil),
				IsOwner:         false,
				ObjectName:      objectName,
			}) {
				// Request is allowed return the appropriate access key.
				return cred.AccessKey, owner, ErrNone
			}

			if action == policy.ListBucketVersionsAction {
				// In AWS S3 s3:ListBucket permission is same as s3:ListBucketVersions permission
				// verify as a fallback.
				if globalPolicySys.IsAllowed(policy.Args{
					AccountName:     cred.AccessKey,
					Action:          policy.ListBucketAction,
					BucketName:      bucketName,
					ConditionValues: getConditionValues(r, "", "", nil),
					IsOwner:         false,
					ObjectName:      objectName,
				}) {
					// Request is allowed return the appropriate access key.
					return cred.AccessKey, owner, ErrNone
				}
			}
			return cred.AccessKey, owner, ErrAccessDenied
		}
		return accessKey, owner, ErrSignatureVersionNotSupported
    ......
    }
.....
}
```

I also ran the `go test` for the new version. It passed all cases except for `Test 9 - unknown auth header is not supported s3 type`.
I just study Golang for one week. I know this solution might not be very good. It could only fix the `getting object` request. I hope you guys could fix this bug in a better way.

## Context

I'm using an application that I can't modify. It will send a request with Authorization in headers that I can't cancel. So when I  want to use it to get an object in the "Read-only Policy" bucket, I got this error.

**Comment by harshavardhana** [comment]
> It might be a bug to me. Even if the "Authorization" might be wrong, I don't need to authorize the "getting object" request with its headers anymore, because the bucket has already been set to "Read-only" Policy.

This is working as AWS S3 - if you present Authorization header then we validate the request.
