### ISSUE TITLE
MINIO_PROMETHEUS_AUTH_TYPE=public no effect

### ISSUE THREAD

**Issue by gcxfd** [minio/minio#11321]
![image](https://user-images.githubusercontent.com/69608605/105256520-db897800-5bc0-11eb-8042-8f2007aa780a.png)

minio  RELEASE.2021-01-16T02-19-44Z

start minio with MINIO_PROMETHEUS_AUTH_TYPE=public

curl http://127.0.0.1:9000/minio/prometheus/node
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AllAccessDisabled</Code><Message>All access to this bucket has been disabled.</Message><Resource>/minio/prometheus/node</Resource><RequestId></RequestId><HostId>6b2732ee-b6cc-4ad6-bb76-0cf73a1d307f</HostId></Error>
```

**Comment by harshavardhana** [comment]
This is not yet released @gcxfd - don't use master features https://github.com/minio/minio/tree/RELEASE.2021-01-16T02-19-44Z/docs/metrics
