### ISSUE TITLE
File replication stopped work for bucket where enabled DeleteReplication and DeleteMarkerReplication

### ISSUE THREAD

**Issue by pavel-z1** [minio/minio#11340]
I have buckets in the two datacenter with enabled replication between each other.
Replication of files stopped working after enabling DeleteReplication and DeleteMarkerReplication feature.
```
mc replicate edit local/test --id "bt8u4bnckkkgn5mck280" --replicate "delete,delete-marker"
```

I've tried to remove replication and create it again. This action did not help.

## Current Behavior
Currently I see this file replication statues:
```
# mc stat local/test/file-2.yaml
Name      : zbx_export_templates-2.yaml
Date      : 2021-01-23 09:20:01 CET
Size      : 15 KiB
ETag      : 6c8ced0e9f644b94542defeff66372c3
VersionID : 9044152a-7c52-4142-be07-fe9600f4b274
Type      : file
Metadata  :
  Content-Type: application/x-yaml
Replication Status: FAILED


# mc stat local/test/file-36.xml
Name      : zbx_export_templates-36.xml
Date      : 2021-01-24 16:50:01 CET
Size      : 34 KiB
ETag      : 333ca4bb0e6a53bb2d3337765a0e03cb
VersionID : 4183c14d-5448-4aaa-b0c0-cb1878b25ca1
Type      : file
Metadata  :
  Content-Type: text/xml
Replication Status: PENDING
```

Replication parameters:
```
# mc replicate export local/test
{
 "Rules": [
  {
   "ID": "c06pctnckkkjebv3ihog",
   "Status": "Enabled",
   "Priority": 1,
   "DeleteMarkerReplication": {
    "Status": "Enabled"
   },
   "DeleteReplication": {
    "Status": "Enabled"
   },
   "Destination": {
    "Bucket": "arn:aws:s3:::test",
    "StorageClass": "STANDARD"
   },
   "Filter": {
    "And": {},
    "Tag": {}
   },
   "SourceSelectionCriteria": {
    "ReplicaModifications": {
     "Status": ""
    }
   }
  }
 ],
 "Role": "arn:minio:replication:ams01:ec22934bb052ca100db62c883efba31df89547bd2705e521dded84fbccac40bb:test"
}
```

## Regression
Yes

## My Environment
minio: RELEASE.2021-01-16T02-19-44Z inside docker container

OS: CentOS Linux release 8.2.2004
Kernel: 4.18.0-193.14.2.el8_2.x86_64

**Comment by poornas** [comment]
@pavel-z1, can you check if target bucket "test" is deleted or versioning suspended? Also if the remote target credentials has changed, replication could fail - do you see this replcation arn in `mc admin bucket remote ls`? You might want to `mc admin bucket remote edit` to update the credentials if there has been a change in creds.

You mentioned having set up 2 way replication - is it failing in both directions?

**Comment by hnesland** [comment]
I found the same problem. I can reproduce this by setting up two instances, enabling replication and `delete,delete-marker`. Create a file in the replicated bucket, observe it replicates okay the first time, remove the file and it is also removed on both instances. However, when I add the file again, it will not be replicated. It seems to be because of existing versions. If I remove the file with --versions --force, then the replication still works.

**Comment by poornas** [comment]
> I found the same problem. I can reproduce this by setting up two instances, enabling replication and `delete,delete-marker`. Create a file in the replicated bucket, observe it replicates okay the first time, remove the file and it is also removed on both instances. However, when I add the file again, it will not be replicated. It seems to be because of existing versions. If I remove the file with --versions --force, then the replication still works.

was able to repro this. @pavel-z1 , did you also remove the file and then add again? Trying to determine if your issue is different.

**Comment by pavel-z1** [comment]
Hi @poornas ,

I see replication arn from both buckets:
```
mc admin bucket remote ls local/test
Remote URL                                          Label Source->Target ARN
http://minio-01.*****       test  ->test   arn:minio:replication:rot0101:fa6f87bc922d128d415d766eb579079d647e0a4ef39c5cea0b0df93786061ee6:test
```

```
# mc admin bucket remote ls local/test
Remote URL                                          Label Source->Target ARN
http://minio-02.******        test  ->test   arn:minio:replication:ams01:ec22934bb052ca100db62c883efba31df89547bd2705e521dded84fbccac40bb:test
```

Bucket version is enabled on both buckets:
```
# mc version info local/test
local/test versioning is enabled
```


> You might want to mc admin bucket remote edit to update the credentials if there has been a change in creds

I am use superuser for replication. Before enabling delete-markers feature replication works fine. I don't think that issue related to the user.

> You mentioned having set up 2 way replication - is it failing in both directions?

Replication failing in both directions.

>was able to repro this. @pavel-z1 , did you also remove the file and then add again? Trying to determine if your issue is different.

No, I have different behaviour.
Any new file from start doen't replcate. From both directions new files didn't replicate.
I've tried to clean up buckets, delete replication, created replication again, the problem is permanent.
