### ISSUE TITLE
minio NAS gateway fails to start

### ISSUE THREAD

**Issue by sibsssidor** [minio/minio#11345]
## Expected Behavior
Follow the instruction in 
https://docs.min.io/docs/minio-gateway-for-nas.html
Nas gateway docker container starts succesfully.

## Current Behavior
The nas gateway container fails to start, reporting:

ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters

increasing MINIO_ROOT_USER/MINIO_ROOT_PASSWORD length has no effect

## Possible Solution
Update the documentation to provide the correct CLI to start the nas gw.

## Steps to Reproduce (for bugs)

1.create a directory /home/user/nasgw
2.docker run -p 9000:9000 --name nas-s3  -e "MINIO_ROOT_USER=nasgateway"  -e "MINIO_ROOT_PASSWORD=nasgateway_2021" -v /home/user/nasgw:/container/vol  minio/minio gateway nas /container/vol

## Context
run the nas gateway

## Your Environment

* Version used (`minio --version`): running from docker, according to documentation
* Server setup and configuration: running from docker, according to documentation
* Operating System and version (`uname -a`): Ubuntu 18.04

**Comment by klauspost** [comment]
Works fine when I try your commandline. Maybe check if your docker is working correctly/is updated?

**Comment by sibsssidor** [comment]
Hi @klauspost  - tx for checking. I'm on docker 19.03.8 (see below) and starting a simple nginx works no prob. 
A docker images reports 
minio/minio         latest              4e86c54e76ec        2 months ago        59.5MB

I tried on a windows machine first but the environment was messy so moved to a clean Ubuntu box. Same story.
Is there anything I'm supposed to set that is assumed by the documentation? (e.g. some env variable)
I feel like I'm having a rather stupid day... :-) 

Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:

**Comment by vadmeste** [comment]
@sibsssidor I would say, update your image and try again, `docker pull minio/minio:latest`

**Comment by sibsssidor** [comment]
Ah! that did the trick! Very stupid day indeed...

**Comment by sibsssidor** [comment]
Made the assumption that since I never used that image it would have pulled the latest. Tx @klauspost !
