### ISSUE TITLE
Wrong "mc admin prometheus generate" output in document

### ISSUE THREAD

**Issue by alisalmaji** [minio/minio#11349]
Wrong "mc admin prometheus generate" output in document

## Expected Behavior
I expecte the output of "mc admin prometheus generate" in minio client latest version to be  "metrics_path: /minio/v2/metrics/cluster"

## Current Behavior
"mc admin prometheus generate" command output in latest minio client version and latest server version shows
 "metricsPath": "/minio/prometheus/metrics",

## Your Environment
minio client and service version:  RELEASE.2021-01-16T02-45-34Z

**Comment by harshavardhana** [comment]
@alisalmaji we haven't made a release yet - so it's pointing to the master 

Read the release docs here https://github.com/minio/minio/tree/RELEASE.2021-01-16T02-19-44Z/docs/metrics/prometheus#31-authenticated-prometheus-config
