### ISSUE TITLE
Support Confidential OpenID Client in MinIO Browser

### ISSUE THREAD

**Issue by belfhi** [minio/minio#11347]
**Is your feature request related to a problem? Please describe.**
At our institute it is encouraged to use confidential clients in Keycloak 
instead of public clients.
Currently, there is only support (at least the documentation and a code search suggests that)
for public OpenID Connect clients.

**Describe the solution you'd like**
Support and document the use of an environment variable
that would be similar to the other OIDC settings, for example `OPENID_CLIENT_SECRET`
to use the secret.

**Comment by harshavardhana** [comment]
can you explain further with some documentation what is the confidential openid client?

**Comment by belfhi** [comment]
Sure.
There are two client types specified in the oauth spec [1], a public one and a confidential one, that has
a client secret, similar to a username and a password.

[1]
https://oauth.net/2/client-types/

**Comment by awuetz** [comment]
Hi,

i support this request... I just searched for the same option `OPENID_CLIENT_SECRET` to create a confidential OpenID Client.

**Comment by belfhi** [comment]
I was looking at the examples for web identity and they use ClientID and ClientSecret, just the minio implementation itself seems to be lacking this feature.  https://github.com/minio/minio/blob/master/docs/sts/web-identity.go

**Comment by harshavardhana** [comment]
> I was looking at the examples for web identity and they use ClientID and ClientSecret, just the minio implementation itself seems to be lacking this feature. https://github.com/minio/minio/blob/master/docs/sts/web-identity.go

That is not what this issue is about @belfhi

**Comment by harshavardhana** [comment]
If this is about web browser supporting client_secret then there is no plan to support that - if that is what you want - you are advised to use https://github.com/minio/console 

You can already use STS API with client id and client secrets @belfhi

**Comment by harshavardhana** [comment]
> If this is about web browser supporting client_secret then there is no plan to support that - if that is what you want - you are advised to use https://github.com/minio/console
> 
> You can already use STS API with client id and client secrets @belfhi

As per this closing issue - there are no plans to support client secret with MinIO browser
