### ISSUE TITLE
Cluster nodes are hanging / not responding to requests

### ISSUE THREAD

**Issue by amhuber** [minio/minio#11355]
Running a minio cluster and periodically one or more nodes will stop responding to HTTPS requests, including from the mc command and to the metrics endpoint, triggering Prometheus scrape errors.

## Expected Behavior

Nodes should be always available and responsive.
## Current Behavior

Nodes appear to be hung or not responsive.  The problem seems to be occurring more frequently in larger clusters.
## Steps to Reproduce (for bugs)

1.  Run a multiple node cluster using the following options:

    MINIO_VOLUMES='https://minio0{1...5}.mydomain.com/export{1...2}'
    MINIO_OPTS='--address :443'
    MINIO_ACCESS_KEY='accesskey'
    MINIO_SECRET_KEY='secretkey'
    MINIO_PROMETHEUS_AUTH_TYPE='public'
    
2.  Wait for one or more days.
3.  Observe one or more nodes stop responding to HTTPS requests.

## Context

We recently updated from a version from 08/2020 to the latest version and this issue started occuring.  We did not have any stability issues before then.  The problem may be related to locks that are hanging - when one node is unresponsive we observe multiple old locks:

    Time                  Type    Resource
    22 hours              WRITE   .minio.sys/runDataCrawler.lock
    35 minutes            READ    <contentpath>
    33 minutes            READ    .minio.sys/buckets/.usage.json
    32 minutes            READ    <contentpath>
    31 minutes            READ    .minio.sys/buckets/.usage.json
    30 minutes            READ    <contentpath>
    29 minutes            READ    .minio.sys/buckets/.usage.json
    27 minutes            READ    .minio.sys/buckets/.usage.json
    25 minutes            READ    .minio.sys/buckets/.usage.json
    23 minutes            READ    .minio.sys/buckets/.usage.json

When restarting the node we see the following in the logs, but there are no other log messages while the node is unresponsive:

    Jan 26 09:21:27 minio02 systemd[1]: Stopping MinIO...
    Jan 26 09:21:27 minio02 minio[32071]: Exiting on signal: TERMINATED
    Jan 26 09:21:32 minio02 minio[32071]: API: SYSTEM()
    Jan 26 09:21:32 minio02 minio[32071]: Time: 09:21:32 PST 01/26/2021
    Jan 26 09:21:32 minio02 minio[32071]: DeploymentID: 438a2b38-b7a6-4232-9b86-256d539607b3
    Jan 26 09:21:32 minio02 minio[32071]: Error: timed out. some connections are still active. goroutines written to /tmp/minio-goroutines-954800529.txt (*errors.errorString)
    Jan 26 09:21:32 minio02 minio[32071]:        2: cmd/signals.go:59:cmd.handleSignals.func2()
    Jan 26 09:21:32 minio02 minio[32071]:        1: cmd/signals.go:77:cmd.handleSignals()
    Jan 26 09:21:32 minio02 systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
    Jan 26 09:21:32 minio02 systemd[1]: minio.service: Failed with result 'exit-code'.
    Jan 26 09:21:32 minio02 systemd[1]: Stopped MinIO.

The referenced goroutines file:

[goroutines-954800529.txt](https://github.com/minio/minio/files/5875330/goroutines-954800529.txt)

## Regression

Unknown.
## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2021-01-16T02-19-44Z
* Server setup and configuration:  5 node cluster with 10 total disks
* Operating System and version (`uname -a`):  Ubuntu 18.04 / 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
On the surface it seems like you have hanging TCP connections, maybe due to packet loss.

When the system is running and you are seeing these locks, could you do a `mc admin profile start --type=goroutines ALIAS && sleep 5 && mc admin profile stop ALIAS` and post it here? It should not contain any sensitive data.

**Comment by amhuber** [comment]
We have a total of 11 distributed deployments in different locations around the world that we updated to the latest version and we've seen this issue in three of them so far, so something environment specific like packet loss seems unlikely to be happening in all of them.

I'll run the commands the next time we see errors and upload the files.

**Comment by amhuber** [comment]
We had another occurrence tonight.  The "02" node was the one that was unresponsive to requests to /minio/prometheus/metrics and it was also not responding to clients requests.  Running "mc admin info" pointing to that node was also unresponsive.  I did note that I was getting a 200 response to /minio/health/live so the process isn't completely hung, and that unfortunately also means it was still in service in our load balancer even though it was not serving requests, resulting in client errors.  I also noted some stale locks as before using "mc admin top locks".

Here is the profile captured using the commands you provided:

[profile.zip](https://github.com/minio/minio/files/5886056/profile.zip)

Let me know if there is anything else you'd like me to gather.

**Comment by klauspost** [comment]
Server 1 has about 35 connections blocked on writing, Server 2 has about the same number of connections blocked on reading.

Since it doesn't change from the beginning to the end of the trace these connections are likely stuck TCP connections between the servers. 

The other servers do not seem to have this problem, or it wasn't triggered.

I would investigate your network setup and maybe perform traces on why these connections are getting stuck.

**Comment by klauspost** [comment]
I am not sure there is much more we can do from here, but you can ask on community slack for people with similar experiences: https://slack.min.io/

Or you could look into our support options that will allow us to go more in depth with your setup: https://min.io/pricing

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`):  minio version RELEASE.2021-01-16T02-19-44Z

We just made a new release - feel free to upgrade and let us know.

**Comment by amhuber** [comment]
FYI, we've been updating periodically and were still seeing these issues every day or two until we updated to https://github.com/minio/minio/releases/tag/RELEASE.2021-02-14T04-01-33Z.  It's now been more than a week with no further hangs so the issue appears to be resolved by that change.

**Comment by harshavardhana** [comment]
> FYI, we've been updating periodically and were still seeing these issues every day or two until we updated to https://github.com/minio/minio/releases/tag/RELEASE.2021-02-14T04-01-33Z. It's now been more than a week with no further hangs so the issue appears to be resolved by that change.

This is mainly because we turned-off HTTP2 support

**Comment by ifokeev** [comment]
update helped me too, big thank

**Comment by ifokeev** [comment]
nope, still hangs up
