### ISSUE TITLE
Restrict root account to specific IP subnet(s)

### ISSUE THREAD

**Issue by dwagelaar** [minio/minio#11353]
We're developing SaaS applications for healthcare, and we've gone through quite the traject of standards compliance w.r.t. privacy and security. Our services currently all require multi-factor authentication (MFA), for example, and all internal services are only accessible from internal, secured networks.

We'd like to use the S3 feature of signed URLs in MinIO to offload object downloads from our server-side applications to the MinIO service. Ideally, we'd open up the main firewall for outside clients, such that they can access the signed URLs directly. Signed URLs are meant to expire, just like the OAuth tokens of our MFA-protected SaaS applications. Regular user accounts can be restricted to specific IP subnets through policies(*), but the MinIO root account cannot be modified through policies. This leaves single-factor authenticated root access open to the Internet.

The only way to achieve improved security is to rotate the root account credentials every 12 hours(**), in order to achieve comparable security to the expiring OAuth tokens, except that the OAuth tokens do not provide root access to the backend.

Is it possible to add a restriction to the source IP addresses that may connect to the MinIO root account? Without this feature, we're forced to proxy everything through our own SaaS APIs, such that all access is MFA protected (and therefore compliant).

Related issues/docs:
- https://github.com/minio/minio/issues/11319
- https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

(*) Experiments with MinIO have shown that URLs signed by an IP-restricted user account are also restricted to the same IP addresses, and there not usable from the Internet. It looks like we will still need to implement credentials rotation to make this secure, but at least this does not expose a root access account.

(**) The root credentials documentation states to "Make sure to remove MINIO_ROOT_USER_OLD and MINIO_ROOT_PASSWORD_OLD in scripts or service files before next service restarts of the server to avoid double encryption of your existing contents." - Apparently MinIO does not detect whether the current root credentials are already correct; what about multiple MinIO instances running in gateway mode?

**Comment by harshavardhana** [comment]
Root accounts are meant to be locked away and restricted / never used by clients.

Once you have setup MinIO you shout proceed to create sub-admins and once they are created you can restrict all you want using IAM policies IP restrictions.

Root account is not meant for such restrictions unfortunately, if you really want to restrict it run a proxy in front look for the authorization header and restrict the IPs henceforth.

**Comment by dwagelaar** [comment]
@harshavardhana Thank you for your reply! Your suggestion of restricting the Authorization header in our reverse proxy works well, and also fixes the limitation in signed URLs: it is now possible to publish signed URLs to external clients, while keeping the main S3 REST API restricted to internal IP addresses. We're indeed not using the root account, except for creating new application user and physical user accounts, such that we can put ACLs on our various buckets.
