### ISSUE TITLE
Gateway mode with "writeback" cache commit mode leads to 404s and cache miss

### ISSUE THREAD

**Issue by pchristos** [minio/minio#11367]
Running minio in gateway mode with `MINIO_CACHE_COMMIT: "writeback"` returns 404 for cached objects, which haven't yet been uploaded to the remote object storage, and leads to unexpected cache misses.

## Expected Behavior

Using GCS gateway with `MINIO_CACHE_COMMIT: "writeback"`, I'd expect minio to serve cached objects, while they're still being uploaded to GCS.

## Current Behavior

Currently, if the object has been cached by minio, but hasn't been uploaded to GCS  yet, the following error is thrown:
```bash
mc: <ERROR> Failed to copy `http://minio:9000/my-test-bucket/test_file_100m`. The specified key does not exist.
```

## Steps to Reproduce (for bugs)

1. Upload 100 MB object: `./mc cp test_file_100m minio/my-test-bucket/`

2. Check cache drive with `ls -al /data/media/6b1fdedf0d61c4e57c53a0085d417861794906f652d5aa4f08519bfcabf25d0b`:
```
total 102416                                                                    
drwxr-xr-x 2 root root      4096 Jan 27 17:08 .                                 
drwxr-xr-x 5 1000 1000      4096 Jan 27 17:08 ..                                
-rw-r--r-- 1 root root       398 Jan 27 17:08 cache.json                        
-rw-r--r-- 1 root root 104860800 Jan 27 17:08 part.1   
```
Note that the size of `part.1` matches the size of the uploaded file.

3. Check output of `cat /data/media/6b1fdedf0d61c4e57c53a0085d417861794906f652d5aa4f08519bfcabf25d0b/cache.json`:
```
{"version":"1.0.0","stat":{"size":104857600,"modTime":"2021-01-27T17:08:14.790950859Z"},"checksum":{"algorithm":"highwayhash256S","blocksize":1048576},"meta":{"content-md5":"58quVyuZ2KzWXYKfJFnhmw==","content-type":"application/octet-stream","etag":"e7caae572b99d8acd65d829f2459e19b","x-minio-internal-write-back-status":"pending"},"hits":1,"bucket":"my-test-bucket","object":"test_file_100m"}
```
The writeback procedure is pending.

4. Attempting to download the object right away: `./mc cp minio/my-test-bucket/test_file_100m /tmp/foo` returns:
```
mc: <ERROR> Failed to copy `http://minio:9000/my-test-bucket/test_file_100m`. The specified key does not exist.
```

Corresponding logs:
```
minio_1           | API: GetObject(bucket=my-test-bucket, object=test_file_100m)
minio_1           | Time: 17:08:42 UTC 01/27/2021                               
minio_1           | DeploymentID: 8dfc5ad4-2de7-4de9-9509-40f73c42aa8a          
minio_1           | RequestID: 165E25D57F20965C                                 
minio_1           | RemoteHost: 172.19.0.2                                      
minio_1           | Host: minio:9000                                            
minio_1           | UserAgent: MinIO (linux; amd64) minio-go/v7.0.8 mc/2021-01-16T02:45:34Z
minio_1           | Error: storage: object doesn't exist (*errors.errorString)  
minio_1           |        5: cmd/gateway/gcs/gateway-gcs.go:890:gcs.(*gcsGateway).GetObjectInfo()
minio_1           |        4: cmd/disk-cache.go:763:cmd.newServerCacheObjects.func1()
minio_1           |        3: cmd/disk-cache.go:260:cmd.(*cacheObjects).GetObjectNInfo()
minio_1           |        2: cmd/object-handlers.go:418:cmd.objectAPIHandlers.GetObjectHandler()
minio_1           |        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

5. Check cache drive with `ls -al /data/media/`:
```
total 12                                                                        
drwxr-xr-x 3 tomotech tomotech 4096 Jan 26 18:56 .                              
drwxr-xr-x 4 root     root     4096 Jan 26 14:36 ..                             
drwxr-xr-x 2 root     root     4096 Jan 26 18:56 .minio.sys                     
```                                                                                
The `6b1fdedf0d61c4e57c53a0085d417861794906f652d5aa4f08519bfcabf25d0b` directory is gone and the object does no seem to have been uploaded to the bucket yet. However, after a brief period of time, the directory re-appears.

6. Then, `./mc cp minio/my-test-bucket/test_file_100m /tmp/foo` succeeds in ~20s, which means that the uploaded object wasn't served from minio's cache.

7. Re-running the above command returns in ~1s. The object was served from minio's cache.                                                                                                                                       

8. Check output of `cat /data/media/6b1fdedf0d61c4e57c53a0085d417861794906f652d5aa4f08519bfcabf25d0b/cache.json`:
```
{"version":"1.0.0","stat":{"size":104857600,"modTime":"2021-01-27T18:13:20.514055522Z"},"checksum":{"algorithm":"highwayhash256S","blocksize":1048576},"meta":{"Content-Type":"application/octet-stream","content-md5":"58quVyuZ2KzWXYKfJFnhmw==","content-type":"application/octet-stream","etag":"e7caae572b99d8acd65d829f2459e19b","expires":"Mon, 01 Jan 0001 00:00:00 GMT","x-minio-internal-write-back-status":"pending"},"hits":2,"bucket":"my-test-bucket","object":"test_file_100m"}
```                                                                                
The new `meta` has both a `content-type` and `Content-Type` attribute, while the output in step (3) just has `content-type`. Could the extra `Content-Type` have invalidated the cache?

In a secondary test case, I repeated steps 1-3. Instead of attempting to quickly download the object, as described in step 4, I waited for it to be pushed to GCS first. So, checking the cache after a while:
```
{"version":"1.0.0","stat":{"size":104857600,"modTime":"2021-01-28T10:55:31.320998738Z"},"checksum":{"algorithm":"highwayhash256S","blocksize":1048576},"meta":{"content-md5":"58quVyuZ2KzWXYKfJFnhmw==","content-type":"application/octet-stream","etag":"e7caae572b99d8acd65d829f2459e19b","x-minio-internal-write-back-status":"complete"},"hits":2,"bucket":"my-test-bucket","object":"test_file_100m"}
```
The writeback procedure is complete and `hits` has also been increased to 2. Attempting to download the object now returns in ~1s. In this case, the object was returned from minio's cache.
                                                                                
## Context

I am testing out minio as a cache to GCS. I am working with large files, so caching greatly affects efficiency.

## Regression

Can't say it is. Seems a bit similar to https://github.com/minio/minio/issues/8979.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-01-16T02-19-44Z
* Running with docker-compose with the following settings:
```                                                                             
GOOGLE_APPLICATION_CREDENTIALS: "/key.json"                                     
MINIO_ROOT_USER: "adminuser"                                                    
MINIO_ROOT_PASSWORD: "adminuser"                                                
MINIO_CACHE: "on"                                                               
MINIO_CACHE_QUOTA: 80                                                           
MINIO_CACHE_WATERMARK_LOW: 70                                                   
MINIO_CACHE_WATERMARK_HIGH: 90                                                  
MINIO_CACHE_DRIVES: "/data/media"                                               
MINIO_CACHE_COMMIT: "writeback"                                                 
```
The bug scenario was tested with `gateway s3 https://storage.googleapis.com`, as well.

TBF I can see how this behavior could be a design decision, instead of a bug: minio returns only what's in the remote bucket. Yet, the cache invalidation in step 6 still doesn't feel like it's the expected behavior.

**Comment by klauspost** [comment]
Even though writeback is inherently tricky, it seems that we are missing to check if we have a staged object before trying upstream.

**Comment by poornas** [comment]
I can see why you would expect the cache entry to be served even prior to the writeback committing to the remote bucket.  Cache design validates whether the cache entry is stale by comparing ETags with the remote object - making an exception for writeback mode would open up room for failure to clean up stale entries from cache or serving stale content even after remote object changed. 

This would not be a good trade-off for being able to serve cached content in the small window of time it takes to commit to backend. Instead, if in your use-case you expect to access cached content right away after upload, it would make sense to set Cache-Control max-age or Expiry headers. When a valid Cache-Control/Expiry  header is present, ETag is not validated with the remote until the validity duration is past.

**Comment by poornas** [comment]
btw, you can use the --attr flag in `mc cp`  to set metadata like Cache-Control and other custom metadata
```
mc cp --attr "Cache-Control=max-age=90000,min-fresh=9000;key1=value1;key2=value2" test_file_100m minio/my-test-bucket/

```

**Comment by harshavardhana** [comment]
> btw, you can use the --attr flag in `mc cp` to set metadata like Cache-Control and other custom metadata
> 
> ```
> mc cp --attr "Cache-Control=max-age=90000,min-fresh=9000;key1=value1;key2=value2" test_file_100m minio/my-test-bucket/
> ```

Closing as per this comment

**Comment by pchristos** [comment]
Thanks for the hint. That's actually helpful.

However, I'd still expect a different behavior with regards to the cache invalidation described in step 6:

> TBF I can see how this behavior could be a design decision, instead of a bug: minio returns only what's in the remote bucket. Yet, the cache invalidation in step 6 still doesn't feel like it's the expected behavior.



Shouldn't minio serve the requested object directly from cache?
