### ISSUE TITLE
minio gateway stuck with tls closed connection

### ISSUE THREAD

**Issue by onip** [minio/minio#11363]
we're using MinIO as an S3 gateway, through docker, at version `RELEASE.2020-06-22T03-12-50Z`.
today, with an uptime of `~6weeks` it stopped responding to our data upload service with this error

```
API: PutObject(bucket=<omitted_bucket_name>, object=<omitted_object_name>.png)
Time: 07:52:46 UTC 01/24/2021
DeploymentID: e4746081-ba8e-463e-be4a-992db341094d
RequestID: 165D1BC2F21C1131
RemoteHost: 192.168.112.35
Host: minio:9000
UserAgent: MinIO (linux; x64) minio-js/7.0.16
Error: Put https://<omitted_bucket_name>.s3.dualstack.ap-east-1.amazonaws.com/<omitted_object_name>.png: tls: use of closed connection
       4: github.com/minio/minio@/cmd/api-errors.go:1875:cmd.toAPIErrorCode()
       3: github.com/minio/minio@/cmd/api-errors.go:1900:cmd.toAPIError()
       2: github.com/minio/minio@/cmd/object-handlers.go:1486:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

`uname -a`

```
Linux mtr 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I've searched the issues and found nothing similar, hope it is not a duplicate.

**Comment by onip** [comment]
forgot to mention that restarting the container

```bash
$ docker restart minio
```

fixed the problem.

**Comment by harshavardhana** [comment]
Please upgrade to latest @onip and let us know how it goes.

**Comment by onip** [comment]
will do, but

- it happened after six weeks, so current version will always be outdated next time
- went through all release notes since and nothing was mentioned in that regard. 

so i think it is worth at least a quick glance
