### ISSUE TITLE
Openstack Swift compatibility with consistency

### ISSUE THREAD

**Issue by morind** [minio/minio#11374]
**Is your feature request related to a problem? Please describe.**
A lot of Object Storage offers are based on Openstack Swift especially in cloud environment.
Problem: the Swift S3 API is not consistent. That's not the only drawback but probably the most important because it is impossible to create data pipelines based on these offers.

**Describe the solution you'd like**
I would like to use Minio as Consistency and Cache layer in front of Openstack Swift.

**Describe alternatives you've considered**
The default Minio s3 gateway does not provide consistency with Openstack Swift S3 API

**Additional context**
related to https://github.com/minio/minio/issues/8213

**Comment by harshavardhana** [comment]
We have no plans to support Swift API - S3 API is the Gold Standard. Our prime directive is to always do only one thing and one thing better.  The choice was simply S3 API.

If there is a real commercial requirement we may consider it - feel free to reach out to us at https://min.io/pricing

**Comment by morind** [comment]
My purpose was to use Swift as backend of dremio in order to provide a consistent S3 API. This is not the case concerning the Swift S3 API.
