### ISSUE TITLE
Minio cluster slows down and 503 every 12 hours

### ISSUE THREAD

**Issue by Iguana9999phil** [minio/minio#11378]
Every 12 hours or so the Minio Cluster will slow to a crawl, give 499 and 503 errors and needs a restart using mc and even need restart of minio service on each node.

Just before it starts to act up multiple nodes will show errors in the logs.
minio[10979]: updateCacheEntry: bucket media list id 5622ffc8-1fbd-42e3-b51b-34e8228dbfd8 not found
minio[25516]: updateCacheEntry: bucket media list id 8828a2fe-e290-435a-b762-fba6e7f7975c not found
minio[6970]: updateCacheEntry: bucket media list id 4d14192b-9fcc-4ccd-8719-b5d8e8e9b63d not found

One node gives Error: too few shards given as well

## Expected Behavior
Be stable.

## Current Behavior
Unstable the longer it's up, then crashes.

## Possible Solution
No idea
## Steps to Reproduce (for bugs)

No idea how to reproduce

## Context

Storage is unstable, need to restart and babysit it the whole day.
## Regression
No idea

## Your Environment

* Version used (`minio --version`): RELEASE.2021-01-16T02-19-44Z
* Server setup and configuration: 12x SX132 Hetzner
* Operating System and version (`uname -a`):4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Unless you can provide us a reproducer @Iguana9999phil not sure what we can do here.  Feel free to upgrade and let us know how it goes.

I don't see how this is possible on stable hardware and network.

**Comment by harshavardhana** [comment]
> minio[10979]: updateCacheEntry: bucket media list id 5622ffc8-1fbd-42e3-b51b-34e8228dbfd8 not found
> minio[25516]: updateCacheEntry: bucket media list id 8828a2fe-e290-435a-b762-fba6e7f7975c not found
> minio[6970]: updateCacheEntry: bucket media list id 4d14192b-9fcc-4ccd-8719-b5d8e8e9b63d not found

Try purging the `.metacache` folder on `/backend_drive/.minio.sys/buckets/<bucketname>/.minio.sys`

**Comment by harshavardhana** [comment]
If you have a production cluster - you better get a subscription from us https://min.io/pricing - so we can login to your clusters and help you architecture/debug these issues. 

Other than that there is nothing that I see should be problematic here. From what It looks like you have unstable hardware.

**Comment by Iguana9999phil** [comment]
Not a production cluster as I only have trouble since starting. Will there be an overview of the bug fixes in the coming release? I see the zip but no info yet.

**Comment by harshavardhana** [comment]
> Not a production cluster as I only have trouble since starting. Will there be an overview of the bug fixes in the coming release? I see the zip but no info yet.

We always upload to dl.min.io and you can update doing `mc admin update`

**Comment by Iguana9999phil** [comment]
Installed the latest and cleared all .metacache dirs on disks. Minio seems to be more stable now (as in not having full cluster going down) still minio restarts itself every couple of hours on most nodes. 

Logs show:

```
 minio[25242]: runtime: failed to create new OS thread (have 4916 already; errno=11)
minio[25242]: runtime: may need to increase max user processes (ulimit -u)
```
ulimit -u gives me
`515140`

Service file (from the minio docs)

```
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
WorkingDirectory=/usr/local/

User=root
Group=root

[Service]
Type=simple
ExecStartPre=/bin/sleep 5
EnvironmentFile=/etc/minioenvironment
ExecStart=/usr/local/bin/minio server "Zones"
# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=196608

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
Service file status
```
```
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-02-01 06:55:20 PST; 3h 53min ago
     Docs: https://docs.min.io
  Process: 8260 ExecStartPre=/bin/sleep 5 (code=exited, status=0/SUCCESS)
 Main PID: 8261 (minio)
    Tasks: 4560 (limit: 4915)
   Memory: 113.7G
   CGroup: /system.slice/minio.service
           └─8261 /usr/local/bin/minio server "zones"
```
ulimit numbers are the same for both root as for the local user. minio currently runs as root.

EDIT: seems debian / systemd calculates that itself, I can set it higher by adding TasksMax={limit} which works after restarting minio, I assume this will not give negative effects except for using more resources due to the increase of tasks?

**Comment by harshavardhana** [comment]
>  minio[25242]: runtime: failed to create new OS thread (have 4916 already; errno=11)
> minio[25242]: runtime: may need to increase max user processes (ulimit -u)

You have restrictions here on OS threads @Iguana9999phil - you should set this to a higher value - as you are putting the nodes through a higher workload. 4916 is small if you put the server through a lot of workload.  My laptop has 

```
ulimit -u
30496
```

I don't see anything wrong here it clearly looks like a deployment and configuration issue. Perhaps this has been your problem all along. 

> EDIT: seems debian / systemd calculates that itself, I can set it higher by adding TasksMax={limit} which works after restarting minio, I assume this will not give negative effects except for using more resources due to the increase of tasks?

Correct

You should check like this assuming `minio` is your service name

> systemctl show -p TasksMax minio

Best value is set it to `TasksMax=infinity` - this is the correct setting for MinIO
