### ISSUE TITLE
Upload travis build <somewhere>

### ISSUE THREAD

**Issue by klausenbusk** [minio/minio#1137]
So it easier for users to test fix, without they need to build it them self.

**Comment by harshavardhana** [comment]
> So it easier for users to test fix, without they need to build it them self.

Actually this is a good idea, it is easier to upload to 'https://play.minio.io:9000'

**Comment by GarimaKapoor** [comment]
Docker hub builds Minio for every commit under edge tag.

 `$ docker pull minio/minio:edge`
