### ISSUE TITLE
Crawler writes to disk every minute when nothing has changed

### ISSUE THREAD

**Issue by maforshaw** [minio/minio#11381]
I updated to the latest minio version due to the security report but the crawler can no longer be disabled and keeps disks awake.

## Expected Behavior
The crawler should only write to files inside folder .minio.sys if something has changed.

## Current Behavior
Lots of files inside folder .minio.sys are updated every 1 minute, I can see that from the modified dates.

## Possible Solution
Either please reintroduce environment variable "MINIO_DISK_USAGE_CRAWL_ENABLE" or stop writing every 1 minute when nothing has changed. Another possible solution is to add a setting that allows you to tell the crawler to run only every x hours.

## Steps to Reproduce (for bugs)
Run minio as "server /data", create a bucket, add a file and keep looking the modified dates of files inside folder ".minio.sys". Even the "tmp" folder is modified every minute.

## Context
I have multiple volumes on a NAS. The system volume runs all the time, other volumes (where Minio data lives) only wake when needed. A few years ago when you allowed ".minio.sys" to live in a different location, this all worked perfectly because it was on the system volume and the data volume only woke when data requests were made. Since that is now not allowed and symlinks/mounts are also not allowed, I can't find any workarounds to the disk write cycle every minute.

## Regression
Yes, the "MINIO_DISK_USAGE_CRAWL_ENABLE" setting was removed which now means my disks stay awake all the time.

## Your Environment
Synology NAS
Minio runs inside Docker.
Latest Minio version.

**Comment by harshavardhana** [comment]
> I have multiple volumes on a NAS. The system volume runs all the time, other volumes (where Minio data lives) only wake when needed. A few years ago when you allowed ".minio.sys" to live in a different location, this all worked perfectly because it was on the system volume and the data volume only woke when data requests were made. Since that is now not allowed and symlinks/mounts are also not allowed, I can't find any workarounds to the disk write cycle every minute.

We have never allowed that, and I have written the entire code for it's lifetime. 

> Run minio as "server /data", create a bucket, add a file and keep looking the modified dates of files inside folder ".minio.sys". Even the "tmp" folder is modified every minute.

If it's a single disk use NAS gateway mode  crawler will not be enabled @maforshaw

**Comment by maforshaw** [comment]
@harshavardhana Early versions worked fine (for me) with "--config-dir" on another docker bind mount, which was on another volume. Eventually the option was removed and validation added to prevent mount point workarounds.

I'll take a look at the NAS gateway mode.

**Comment by harshavardhana** [comment]
> @harshavardhana Early versions worked fine (for me) with "--config-dir" on another docker bind mount, which was on another volume. Eventually the option was removed and validation added to prevent mount point workarounds.
> 

config has moved to backend for years now, and we always had .minio.sys where it is today from day 1 of the single drive mode.

> I'll take a look at the NAS gateway mode.

Please do NAS gateway is FS mode underneath without crawler.
