### ISSUE TITLE
arm release missing

### ISSUE THREAD

**Issue by HeavyHorst** [minio/minio#11380]
## Expected Behavior

An arm release should be available under: https://dl.min.io/server/minio/release/ i think?
I was able to update the last times without problems with mc.

## Current Behavior

The release is missing.
mc update fails with: 
`mc: <ERROR> Unable to update the server. Error downloading URL https://dl.min.io/server/minio/release/linux-arm/minio.sha256sum. Response: 404 Not Found.`

There is an linux-arm.tar.gz but this file is 1.4GiB what seems to be wrong. All other tar.gz files are < 200MiB

**Comment by harshavardhana** [comment]
We do not make arm32 releases anymore - you need to build them yourself @HeavyHorst  and haven't done that for almost 6months now.

**Comment by HeavyHorst** [comment]
Ok, no Problem!
The update to version 2021-01-16T02:19:44Z worked, so I thought it was a bug.

**Comment by HeavyHorst** [comment]
Hm, the arm release is back again: https://dl.min.io/server/minio/release/linux-arm/
