### ISSUE TITLE
Add state parameter to buildOpenIDAuthURL

### ISSUE THREAD

**Issue by ninjaslothx** [minio/minio#11398]
**Is your feature request related to a problem? Please describe.**
Currently the [buildOpenIDAuthURL](https://github.com/minio/minio/blob/master/browser/app/js/browser/utils.js#L19) doesn't implement the state parameter. 

Some IDP have this as a required field in their requests 
For example see https://developer.okta.com/docs/reference/api/oidc/#request-parameters

**Describe the solution you'd like**
Implement the state parameter in the oidc request https://tools.ietf.org/html/rfc6819#section-3.6

**Comment by harshavardhana** [comment]
> Currently the [buildOpenIDAuthURL](https://github.com/minio/minio/blob/master/browser/app/js/browser/utils.js#L19) doesn't implement the state parameter.

We do not want state parameter because we expected browser implementation to be implicit flow, if you want a proper OpenID compatible solution use https://github.com/minio/console

**Comment by ninjaslothx** [comment]
It does not matter if it is implicit, the likes of okta still require a state parameter - see here https://developer.okta.com/docs/guides/implement-implicit/use-flow/

**Comment by james-d-elliott** [comment]
The OpenID Connect Core spec recommends this and does not stipulate any such flow based adjustments. While it's not *REQUIRED* it's recommended during both authorization requests and authorization responses. Unless I'm missing something it seems like the recommendation for all flows is to use the state (correct me if I'm wrong). 

Edit: ~~Actually maybe I am? This spec does mention that it's for the code flow.~~ looks like it's just in an alternate section.

Citations:

https://datatracker.ietf.org/doc/html/rfc6749#section-11.2.2
~~https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest~~
https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

**Comment by georglauterbach** [comment]
@harshavardhana Is there going to be something done about this? Redirecting users to the console is not helpful at all, especially for small / tiny MinIO instances.
