### ISSUE TITLE
minio-LDAP integration 

### ISSUE THREAD

**Issue by ardeshiri** [minio/minio#11399]
We are trying to use MINIO as an S3 compatible component in a project. However the project has many parts all of which need to be integrated with LDAP in order to perform authentication. Even though the functionality seems straightforward, we are having difficulty setting it up.

## Expected Behavior

We expected to be able to access buckets with usernames and passwords defined in AD/LDAP, and define policies for them using AWS SDK, MC and/or web interface.
## Current Behavior

 All in all, It does not seem to work. Neither the web-API, nor MC recognizes users. All we get is:
"The Access Key Id you provided does not exist in our records."
We even used wireshark to monitor commiunications between MINIO and LDAP. No communications were taking place. We also could not find any helpful log to diagnose the problems. 
## Your Environment

We used MINIO both in docker and binary mode(setting environment variables) and LDAP integration in Lookup-Bind mode with these test configurations:
$export MINIO_ACCESS_KEY="minio"
$export MINIO_SECRET_KEY="minio123"
$export MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="cn=administrator,cn=Users,dc=first,dc=com"
$export MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="P@ssw0rd"
$export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="dc=first,dc=com"
$export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=""
$export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
and finally:
$./minio server ./date
(or  $./mc admin service restart mx )

Version: go1.15.5 | CPUs: 4
Host: *** | OS: linux | Arch: amd64
2020-11-13T20:10:18Z
OPENLDAP server and MINIO are both running insecure. 
The ldapsearch command on the same system as MINIO, using the same configuration responses properly.

Are we missing anything? Is there any further thing we can try to make it work? 

Thanks.

**Comment by harshavardhana** [comment]
@ardeshiri you cannot just use access key and secret with mc . Access needs to be presented with session token as well..

So with mc you need to use https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#rotating-credentials

Browser UI doesn't support LDAP you need to use our MinIO console for WebUI for full LDAP support https://github.com/minio/console
