### ISSUE TITLE
listParts response Initiator->DisplayName is empty

### ISSUE THREAD

**Issue by tuine** [minio/minio#11408]
## Expected Behavior

ListPartsResult->Initiator->DisplayName must have a value
```
<ListPartsResult
    xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Bucket>test</Bucket>
    <Key>test</Key>
    <UploadId>424f9267-386b-4392-8673-8439a7a8e87e</UploadId>
    <Initiator>
        <ID>02d6176db274dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID>
        <DisplayName></DisplayName>
    </Initiator>
</ListPartsResult>
```
## Current Behavior

ListPartsResult->Initiator->DisplayName is empty

## Steps to Reproduce (for bugs)

1. createMultipartUpload()
2. uploadPart()
3. listParts()
The response xml ListPartsResult->Initiator->DisplayName is empty

## Context

JAVA SDK 
class ListPartsResult->class Initiator  -> field displayName is required，so listParts method throw a exception:throw io.minio.errors.XmlParserException: null

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-01-30T00-20-58Z
* Server setup and configuration: running in a docker container using the official image
* Operating System and version (`uname -a`):  the same problem on your "https://play.minio.io:9000/"

**Comment by harshavardhana** [comment]
@balamurugana this ListPartsResult never expects the response to have DisplayName and ID - We should fix minio-java

https://docs.aws.amazon.com/AmazonS3/latest/API/API_Initiator.html

```
DisplayName
Name of the Principal.

Type: String

Required: No

ID
If the principal is an AWS account, it provides the Canonical User ID. If the principal is an IAM User, it provides a user ARN value.

Type: String

Required: No
```

> Required: No

**Comment by harshavardhana** [comment]
This shall be piggybacked into the PR #11410
