### ISSUE TITLE
S3 Select: missing data on multiple column when using MinIO S3 Gateway

### ISSUE THREAD

**Issue by mailsmail** [minio/minio#11413]
When selecting object content with Parquet format using MinIO S3 Gateway, I've got the result with empty data on some columns. This issue didn't occur when selecting CSV or JSON file, and it also did not happen when using MinIO server. 

## Current Behaviour

Missing data on some columns when selecting parquet file using MinIO S3 gateway.

```
$ aws --endpoint-url http://localhost:9000 \
    s3api select-object-content \
        --bucket parquet-test \
        --key TotalPopulation.parquet \
        --expression "select * from s3object limit 5" \
        --expression-type SQL \
        --input-serialization '{"Parquet": {}}' \
        --output-serialization '{"CSV": {}}' \
        /dev/stdout
4,,2,,,1950.5,,,,
4,,2,,,1951.5,,,,
4,,2,,,1952.5,,,,
4,,2,,,1953.5,,,,
4,,2,,,1954.5,,,,
```

## Expected Behaviour

The result is expected to be like this:

```
4,Afghanistan,2,Medium,1950,1950.5,4099.2431640625,3652.8740234375,7752.1171875,11.87399959564209
4,Afghanistan,2,Medium,1951,1951.5,4134.755859375,3705.39501953125,7840.15087890625,12.008999824523926
4,Afghanistan,2,Medium,1952,1952.5,4174.4501953125,3761.5458984375,7935.99609375,12.156000137329102
4,Afghanistan,2,Medium,1953,1953.5,4218.3359375,3821.347900390625,8039.68408203125,12.3149995803833
4,Afghanistan,2,Medium,1954,1954.5,4266.48388671875,3884.83203125,8151.31591796875,12.486000061035156
```

## Possible Solution

Currently, my solution is to add `io.Copy` to read all of the data downloaded from S3 into `bytes.Buffer`. 

```go
// pkg/s3Select/select.go

func (s3Select *S3Select) Open(getReader func(offset, length int64) (io.ReadCloser, error)) error {
	...

	case parquetFormat:
		if !strings.EqualFold(os.Getenv("MINIO_API_SELECT_PARQUET"), "on") {
			return errors.New("parquet format parsing not enabled on server")
		}

		getReaderFn := func(offset, length int64) (io.ReadCloser, error) {
			rc, err := getReader(offset, length)
			if err != nil {
				return nil, err
			}
			var buf bytes.Buffer
			if _, err = io.Copy(&buf, rc); err != nil {
				return nil, err
			}
			return ioutil.NopCloser(&buf), nil
		}

		var err error
		s3Select.recordReader, err = parquet.NewReader(getReaderFn, &s3Select.Input.ParquetArgs)
```

I'm not sure if this solution is good or efficient, because I'm worried `io.Copy` could possibly increase the heap allocation, especially if the file is large. 

The issue could be related to pipe reader/writer created in `(l *s3Objects) GetObjectNInfo()` 
https://github.com/minio/minio/blob/fe3aca70c3d2478a956250254da172bb55c5cc34/cmd/gateway/s3/gateway-s3.go#L403-L412 

I thought it is  closed early somewhere in parquet reader (I don't know exactly where). I also tried and tested it with MinIO server by adding pipe reader/writer in `(fs *FSObjects) GetObjectNInfo`, and there's also missing data on some columns.

## Steps to Reproduce

To reproduce this issue, run MinIO as S3 gateway.

and:
1. Download this [TotalPopulation.zip](https://github.com/minio/minio/files/5911736/TotalPopulation.zip) file (the data is downloaded from here: https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/CSV_FILES/WPP2019_TotalPopulationBySex.csv and then converted to parquet).
2. Upload the parquet File to S3.
3. Select the parquet object using AWS-CLI

## Environment

- `minio --version`: minio version DEVELOPMENT.2021-02-02T12-15-54Z
- Run minio as S3 Gateway and set env `MINIO_API_SELECT_PARQUET=on`

**Comment by klauspost** [comment]
In normal (distributed) mode it works fine:
```
λ mc cp TotalPopulation.parquet local2/testbucket
λ mc sql -query="select * from s3object limit 5" local2/testbucket/TotalPopulation.parquet
4,Afghanistan,2,Medium,1950,1950.5,4099.2431640625,3652.8740234375,7752.1171875,11.87399959564209
4,Afghanistan,2,Medium,1951,1951.5,4134.755859375,3705.39501953125,7840.15087890625,12.008999824523926
4,Afghanistan,2,Medium,1952,1952.5,4174.4501953125,3761.5458984375,7935.99609375,12.156000137329102
4,Afghanistan,2,Medium,1953,1953.5,4218.3359375,3821.347900390625,8039.68408203125,12.3149995803833
4,Afghanistan,2,Medium,1954,1954.5,4266.48388671875,3884.83203125,8151.31591796875,12.486000061035156
```

So it must be something with how the object is retrieved.

We cannot copy the data to an internal buffer since that would make it easy to crash the servers with OOM.

**Comment by harshavardhana** [comment]
> Currently, my solution is to add `io.Copy` to read all of the data downloaded from S3 into `bytes.Buffer`.

That will not scale for all Parquet

**Comment by mailsmail** [comment]
@klauspost 
Normal mode means running it as server, right?

Yes, it's working as expected in minio server.

> So it must be something with how the object is retrieved.

if there's somehting wrong with how the object is retrieved, shouldn't selecting CSV object or JSON object also result in missing data?

**Comment by harshavardhana** [comment]
> if there's somehting wrong with how the object is retrieved, shouldn't selecting CSV object or JSON object also result in missing data?

No its the Parquet Reader implementation that is buggy here @mailsmail

**Comment by mailsmail** [comment]
I think I've found the cause of this issue. After checking method `readPage()` in `pkg/s3select/internal/parquet-go/page.go`, I noticed that `thriftReader.Read(dataBuf)` didn't read the entire byte. 

https://github.com/minio/minio/blob/876b79b8d8e10e4e4f213b495c6af0713e0f061c/pkg/s3select/internal/parquet-go/page.go#L126

I also found that `Read` method inside `(g *GetObjectReader) Read`, for some reason, cannot read more than 32KB.

https://github.com/minio/minio/blob/876b79b8d8e10e4e4f213b495c6af0713e0f061c/cmd/object-api-utils.go#L812-L813

I think it might be related to this issues: https://github.com/golang/go/issues/33264 and https://github.com/golang/go/issues/16474.

So to fix it, I use `io.ReadFull` instead of `Read` in `(g *GetObjectReader) Read`.

```go
func (g *GetObjectReader) Read(p []byte) (n int, err error) {
	n, err = io.ReadFull(g.pReader, p)
	if err != nil {
		// Calling code may not Close() in case of error, so
		// we ensure it.
		g.Close()
	}
	return
}
```

I've tested using this fix, and it worked fine when running as S3 Gateway.

**Comment by klauspost** [comment]
Reads are [allowed to be short](https://golang.org/pkg/io/#Reader). The part around `thriftReader.Read` should be modified since it contains the bug.

**Comment by klauspost** [comment]
You are welcome to send a PR if you would like credit for the fix.

Not sure if it has other similar problems.

**Comment by harshavardhana** [comment]
>  if _, err = thriftReader.Read(dataBuf); err != nil {

The implementation issue here is that it's expecting the underlying reader to all the buffer, you have to look at the returned `n` and then re-read them to fill the entire buffer.

**Comment by harshavardhana** [comment]
@mailsmail the correct fix would be to read the required buffer from the caller not underneath 

```diff
diff --git a/pkg/s3select/internal/parquet-go/page.go b/pkg/s3select/internal/parquet-go/page.go
index 22c25793e..22f89fe80 100644
--- a/pkg/s3select/internal/parquet-go/page.go
+++ b/pkg/s3select/internal/parquet-go/page.go
@@ -21,6 +21,7 @@ import (
        "context"
        "errors"
        "fmt"
+       "io"
        "math"
        "strings"
 
@@ -108,24 +109,39 @@ func readPage(
                        }
                        repLevelsLen = pageHeader.DataPageHeaderV2.GetRepetitionLevelsByteLength()
                        repLevelsBuf = make([]byte, repLevelsLen)
-                       if _, err = thriftReader.Read(repLevelsBuf); err != nil {
+
+                       n, err := io.ReadFull(thriftReader, repLevelsBuf)
+                       if err != nil {
                                return nil, err
                        }
+                       if n != int(repLevelsLen) {
+                               return nil, fmt.Errorf("expected parquet header repetition levels %d, got %d", repLevelsLen, n)
+                       }
 
                        defLevelsLen = pageHeader.DataPageHeaderV2.GetDefinitionLevelsByteLength()
                        defLevelsBuf = make([]byte, defLevelsLen)
-                       if _, err = thriftReader.Read(defLevelsBuf); err != nil {
+
+                       n, err = io.ReadFull(thriftReader, defLevelsBuf)
+                       if err != nil {
                                return nil, err
                        }
+                       if n != int(defLevelsLen) {
+                               return nil, fmt.Errorf("expected parquet header definition levels %d, got %d", defLevelsLen, n)
+                       }
                }
                dbLen := pageHeader.GetCompressedPageSize() - repLevelsLen - defLevelsLen
                if dbLen < 0 {
                        return nil, errors.New("parquet: negative data length")
                }
+
                dataBuf := make([]byte, dbLen)
-               if _, err = thriftReader.Read(dataBuf); err != nil {
+               n, err := io.ReadFull(thriftReader, dataBuf)
+               if err != nil {
                        return nil, err
                }
+               if n != int(dbLen) {
+                       return nil, fmt.Errorf("expected parquet data buffer %d, got %d", dbLen, n)
+               }
 
                if dataBuf, err = compressionCodec(metadata.GetCodec()).uncompress(dataBuf); err != nil {
                        return nil, err
```

This should fix the problem here.

**Comment by mailsmail** [comment]
@harshavardhana Oops, sorry about that. 

Yes, placing `io. ReadFull` at `(g *GetObjectReader) Read` just create another problem, it fails when running `make test`.

**Comment by mailsmail** [comment]
It is working fine now, thanks @harshavardhana

**Comment by harshavardhana** [comment]
Thanks for testing sending a PR
