### ISSUE TITLE
Prometheus minio_cluster_capacity_* metrics do not work

### ISSUE THREAD

**Issue by mirsafari** [minio/minio#11422]
When configuring Prometheus monitoring using provided docs https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html, the value of metrics minio_cluster_capacity_raw_free_bytes, minio_cluster_capacity_raw_total_bytes, minio_cluster_capacity_usable_free_bytes and minio_cluster_capacity_usable_total_bytes is 0. Other metrics work fine for me.

## Expected Behavior
Metrics minio_cluster_capacity_raw_free_bytes, minio_cluster_capacity_raw_total_bytes, minio_cluster_capacity_usable_free_bytes and minio_cluster_capacity_usable_total_bytes should show real values of cluster capacity and free space

## Current Behavior
Metrics minio_cluster_capacity_raw_free_bytes, minio_cluster_capacity_raw_total_bytes, minio_cluster_capacity_usable_free_bytes and minio_cluster_capacity_usable_total_bytes show 0 value.
Tested on versions RELEASE.2021-02-01T22-56-52Z and RELEASE.2021-01-30T00-20-58Z

## Steps to Reproduce (for bugs)
Run Minio distributed setup on versions RELEASE.2021-02-01T22-56-52Z or RELEASE.2021-01-30T00-20-58Z and try to collect Prometheus metrics on /minio/v2/metrics/cluster endpoint

## Context

I'm trying to test Minio deployment before production and wanted to explore metrics and create dashboards. I would also like to explore how minio_cluster_capacity_raw_free_bytes metric changes as we expand distributed setup with a new pool of servers.

## Your Environment
* Minio version used: RELEASE.2021-02-01T22-56-52Z and RELEASE.2021-01-30T00-20-58Z
* Operating System and version: Ubuntu 18.04 LTS - 15.0-122-generic #124-Ubuntu
* Docker version: 20.10.3
* Prometheus version: 2.19.2
* Setup description:

4 VMs with Ubuntu 18.04 LTS and 2 disks each, using XFS:
```
mkfs.xfs /dev/sdc
mkfs.xfs /dev/sdd
mount -t xfs /dev/sdc /data/pool1-disk1
mount -t xfs /dev/sdd /data/pool1-disk2
```
Create env file /etc/minio.env for minio configuration:
```
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=minio123
MINIO_PROMETHEUS_AUTH_TYPE="public"
```
Start Minio instances on each VM:
```
docker run -dit --rm --name minio1 \
--network=host \
--env-file /etc/minio.env \
-v /data/pool1-disk1:/data1 \
-v /data/pool1-disk2:/data2 \
minio/minio:RELEASE.2021-01-30T00-20-58Z server --address :9001 http://minio{1...4}:9001/data{1...2}
```
Configure Prometheus:
```
- job_name: minio-job-test
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets:
    - 10.10.10.10:9001
```
curl example using token:
```
$ curl -s -H 'Accept: application/json' -H "Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3NjU5NDg5NDksImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJtaW5pbyJ9.d3u2HYCEbTF-ZP4i6b8X8ty6yY1PalXO8RwzaDpAfMSuFDoeSWY4GB6qyS6gtndexz4IUUa0ogJrK-TwmNPcww" http://10.10.10.10:9001/minio/v2/metrics/cluster | grep cluster 
# HELP minio_cluster_capacity_raw_free_bytes Total free capacity online in the cluster.
# TYPE minio_cluster_capacity_raw_free_bytes gauge
minio_cluster_capacity_raw_free_bytes{server="minio3:9001"} 0
# HELP minio_cluster_capacity_raw_total_bytes Total capacity online in the cluster.
# TYPE minio_cluster_capacity_raw_total_bytes gauge
minio_cluster_capacity_raw_total_bytes{server="minio3:9001"} 0
# HELP minio_cluster_capacity_usable_free_bytes Total free usable capacity online in the cluster.
# TYPE minio_cluster_capacity_usable_free_bytes gauge
minio_cluster_capacity_usable_free_bytes{server="minio3:9001"} 0
# HELP minio_cluster_capacity_usable_total_bytes Total usable capacity online in the cluster.
# TYPE minio_cluster_capacity_usable_total_bytes gauge
minio_cluster_capacity_usable_total_bytes{server="minio3:9001"} 0
# HELP minio_cluster_disk_offline_total Total disks offline.
# TYPE minio_cluster_disk_offline_total gauge
minio_cluster_disk_offline_total{server="minio3:9001"} 0
# HELP minio_cluster_disk_online_total Total disks online.
# TYPE minio_cluster_disk_online_total gauge
minio_cluster_disk_online_total{server="minio3:9001"} 16
# HELP minio_cluster_nodes_offline_total Total number of MinIO nodes offline.
# TYPE minio_cluster_nodes_offline_total gauge
minio_cluster_nodes_offline_total{server="minio3:9001"} 0
# HELP minio_cluster_nodes_online_total Total number of MinIO nodes online.
# TYPE minio_cluster_nodes_online_total gauge
minio_cluster_nodes_online_total{server="minio3:9001"} 8
```

![image](https://user-images.githubusercontent.com/16070956/106733637-6bdca980-6612-11eb-89a3-96e1284f5197.png)

**Comment by mirsafari** [comment]
Value of metric is 0 also on the example from docs:
```
curl https://play.min.io/minio/v2/metrics/cluster | grep cluster
# TYPE minio_cluster_capacity_raw_free_bytes gauge
minio_cluster_capacity_raw_free_bytes{server="127.0.0.1:9000"} 0
# HELP minio_cluster_capacity_raw_total_bytes Total capacity online in the cluster.
# TYPE minio_cluster_capacity_raw_total_bytes gauge
minio_cluster_capacity_raw_total_bytes{server="127.0.0.1:9000"} 0
# HELP minio_cluster_capacity_usable_free_bytes Total free usable capacity online in the cluster.
# TYPE minio_cluster_capacity_usable_free_bytes gauge
minio_cluster_capacity_usable_free_bytes{server="127.0.0.1:9000"} 0
# HELP minio_cluster_capacity_usable_total_bytes Total usable capacity online in the cluster.
# TYPE minio_cluster_capacity_usable_total_bytes gauge
minio_cluster_capacity_usable_total_bytes{server="127.0.0.1:9000"} 0
# HELP minio_cluster_disk_offline_total Total disks offline.
# TYPE minio_cluster_disk_offline_total gauge
minio_cluster_disk_offline_total{server="127.0.0.1:9000"} 0
# HELP minio_cluster_disk_online_total Total disks online.
# TYPE minio_cluster_disk_online_total gauge
minio_cluster_disk_online_total{server="127.0.0.1:9000"} 4
# HELP minio_cluster_nodes_offline_total Total number of MinIO nodes offline.
# TYPE minio_cluster_nodes_offline_total gauge
minio_cluster_nodes_offline_total{server="127.0.0.1:9000"} 0
# HELP minio_cluster_nodes_online_total Total number of MinIO nodes online.
# TYPE minio_cluster_nodes_online_total gauge
minio_cluster_nodes_online_total{server="127.0.0.1:9000"} 1
```

**Comment by kerneltime** [comment]
Thank you for reporting this. Will send a PR to fix this.

**Comment by etcshad0vv** [comment]
Hello,
Looks like cluster capacity metrics `minio_cluster_capacity_*` are no longer available in release: RELEASE.2021-06-07T21-40-51Z

```
curl -v 172.31.221.115:9000/minio/v2/metrics/cluster | grep bytes
# HELP minio_bucket_usage_total_bytes Total bucket size in bytes
# TYPE minio_bucket_usage_total_bytes gauge
minio_bucket_usage_total_bytes{bucket="velero",server="127.0.0.1:9000"} 0
# HELP minio_inter_node_traffic_received_bytes Total number of bytes received from other peer nodes.
# TYPE minio_inter_node_traffic_received_bytes counter
minio_inter_node_traffic_received_bytes{server="127.0.0.1:9000"} 2057
# HELP minio_inter_node_traffic_sent_bytes Total number of bytes sent to the other peer nodes.
# TYPE minio_inter_node_traffic_sent_bytes counter
minio_inter_node_traffic_sent_bytes{server="127.0.0.1:9000"} 3.8113891e+07
# HELP minio_node_disk_free_bytes Total storage available on a disk.
# TYPE minio_node_disk_free_bytes gauge
minio_node_disk_free_bytes{disk="/export",server="127.0.0.1:9000"} 4.37201076224e+11
# HELP minio_node_disk_total_bytes Total storage on a disk.
# TYPE minio_node_disk_total_bytes gauge
minio_node_disk_total_bytes{disk="/export",server="127.0.0.1:9000"} 4.39804690432e+11
# HELP minio_node_disk_used_bytes Total storage used on a disk.
# TYPE minio_node_disk_used_bytes gauge
minio_node_disk_used_bytes{disk="/export",server="127.0.0.1:9000"} 2.603614208e+09
# HELP minio_node_io_rchar_bytes Total bytes read by the process from the underlying storage system including cache, /proc/[pid]/io rchar
# TYPE minio_node_io_rchar_bytes counter
minio_node_io_rchar_bytes{server="127.0.0.1:9000"} 4.7479911e+07
# HELP minio_node_io_read_bytes Total bytes read by the process from the underlying storage system, /proc/[pid]/io read_bytes
# TYPE minio_node_io_read_bytes counter
minio_node_io_read_bytes{server="127.0.0.1:9000"} 1.78348032e+08
# HELP minio_node_io_wchar_bytes Total bytes written by the process to the underlying storage system including page cache, /proc/[pid]/io wchar
# TYPE minio_node_io_wchar_bytes counter
minio_node_io_wchar_bytes{server="127.0.0.1:9000"} 1.8069130661e+10
# HELP minio_node_io_write_bytes Total bytes written by the process to the underlying storage system, /proc/[pid]/io write_bytes
# TYPE minio_node_io_write_bytes counter
minio_node_io_write_bytes{server="127.0.0.1:9000"} 1.8266083328e+10
# HELP minio_node_process_resident_memory_bytes Resident memory size in bytes.
# TYPE minio_node_process_resident_memory_bytes gauge
minio_node_process_resident_memory_bytes{server="127.0.0.1:9000"} 1.10166016e+08
# HELP minio_s3_traffic_received_bytes Total number of s3 bytes received.
# TYPE minio_s3_traffic_received_bytes counter
minio_s3_traffic_received_bytes{server="127.0.0.1:9000"} 0
# HELP minio_s3_traffic_sent_bytes Total number of s3 bytes sent
# TYPE minio_s3_traffic_sent_bytes counter
minio_s3_traffic_sent_bytes{server="127.0.0.1:9000"} 1130
```
Is this change intentional? 
Thanks!

**Comment by harshavardhana** [comment]
> Hello,
> Looks like cluster capacity metrics `minio_cluster_capacity_*` are no longer available in release: RELEASE.2021-06-07T21-40-51Z
> 
> ```
> curl -v 172.31.221.115:9000/minio/v2/metrics/cluster | grep bytes
> # HELP minio_bucket_usage_total_bytes Total bucket size in bytes
> # TYPE minio_bucket_usage_total_bytes gauge
> minio_bucket_usage_total_bytes{bucket="velero",server="127.0.0.1:9000"} 0
> # HELP minio_inter_node_traffic_received_bytes Total number of bytes received from other peer nodes.
> # TYPE minio_inter_node_traffic_received_bytes counter
> minio_inter_node_traffic_received_bytes{server="127.0.0.1:9000"} 2057
> # HELP minio_inter_node_traffic_sent_bytes Total number of bytes sent to the other peer nodes.
> # TYPE minio_inter_node_traffic_sent_bytes counter
> minio_inter_node_traffic_sent_bytes{server="127.0.0.1:9000"} 3.8113891e+07
> # HELP minio_node_disk_free_bytes Total storage available on a disk.
> # TYPE minio_node_disk_free_bytes gauge
> minio_node_disk_free_bytes{disk="/export",server="127.0.0.1:9000"} 4.37201076224e+11
> # HELP minio_node_disk_total_bytes Total storage on a disk.
> # TYPE minio_node_disk_total_bytes gauge
> minio_node_disk_total_bytes{disk="/export",server="127.0.0.1:9000"} 4.39804690432e+11
> # HELP minio_node_disk_used_bytes Total storage used on a disk.
> # TYPE minio_node_disk_used_bytes gauge
> minio_node_disk_used_bytes{disk="/export",server="127.0.0.1:9000"} 2.603614208e+09
> # HELP minio_node_io_rchar_bytes Total bytes read by the process from the underlying storage system including cache, /proc/[pid]/io rchar
> # TYPE minio_node_io_rchar_bytes counter
> minio_node_io_rchar_bytes{server="127.0.0.1:9000"} 4.7479911e+07
> # HELP minio_node_io_read_bytes Total bytes read by the process from the underlying storage system, /proc/[pid]/io read_bytes
> # TYPE minio_node_io_read_bytes counter
> minio_node_io_read_bytes{server="127.0.0.1:9000"} 1.78348032e+08
> # HELP minio_node_io_wchar_bytes Total bytes written by the process to the underlying storage system including page cache, /proc/[pid]/io wchar
> # TYPE minio_node_io_wchar_bytes counter
> minio_node_io_wchar_bytes{server="127.0.0.1:9000"} 1.8069130661e+10
> # HELP minio_node_io_write_bytes Total bytes written by the process to the underlying storage system, /proc/[pid]/io write_bytes
> # TYPE minio_node_io_write_bytes counter
> minio_node_io_write_bytes{server="127.0.0.1:9000"} 1.8266083328e+10
> # HELP minio_node_process_resident_memory_bytes Resident memory size in bytes.
> # TYPE minio_node_process_resident_memory_bytes gauge
> minio_node_process_resident_memory_bytes{server="127.0.0.1:9000"} 1.10166016e+08
> # HELP minio_s3_traffic_received_bytes Total number of s3 bytes received.
> # TYPE minio_s3_traffic_received_bytes counter
> minio_s3_traffic_received_bytes{server="127.0.0.1:9000"} 0
> # HELP minio_s3_traffic_sent_bytes Total number of s3 bytes sent
> # TYPE minio_s3_traffic_sent_bytes counter
> minio_s3_traffic_sent_bytes{server="127.0.0.1:9000"} 1130
> ```
> 
> Is this change intentional?
> Thanks!

Are you running in single drive mode @etcshad0vv ?

**Comment by etcshad0vv** [comment]
Yes

**Comment by harshavardhana** [comment]
> Yes

So if you are in single drive there is nothing to show for cluster metrics so nothing is shown.
