### ISSUE TITLE
Allow specifying AccessKey and SecretKey via cmd line or env

### ISSUE THREAD

**Issue by osallou** [minio/minio#1142]
Would be fine to be able to specify the accesskey and secretkey when starting server via command line or config.
An application could manage some credentials and start an minio server for one user, specifying its specific credentials. This would ease automation instead of parsing console ouput.

**Comment by osallou** [comment]
Seems config is recorded in ~/.minio/config.json. As we can specify config-folder, we can create a config at runtime and specify it so command-line direct access is maybe not needed.

**Comment by fd0** [comment]
I'd really like to be able to specify the access credentials in an environment variable or via command line. At the moment, I'm creating a config file and set the config directory, but that feels wrong.
