### ISSUE TITLE
Please comment in docs that EFS is not supported due to nanosecond not supported on EFS

### ISSUE THREAD

**Issue by realthered** [minio/minio#11443]
**Is your feature request related to a problem? Please describe.**
I found that AWS EFS is not supported for gateway cache.
The root cause is EFS doesn't support nanosecond though it is using relatime, but the log I saw was "atime support required for disk caching".
Is it hard to change the log?

**Describe the solution you'd like**
I don't know the reason why you want to use atime, so I can't suggest something.
But the root cause of "atime support required for disk caching" was EFS doesn't support nanosecond, but the library of atime make a temp file and compares time of both.
Because EFS doesn't nanosecont, it was checked as same so "atime support required for disk caching" is shown.

**Describe alternatives you've considered**
It would be good to mark that EFS is not supported as gateway cache.

**Additional context**
I tried to use EFS as cache in Kubernetes. Finally, I attached each EBS for each pods in kubernetes.

**Comment by harshavardhana** [comment]
We have nothing specific against EFS, atime support with precision is necessary. 

We just print that its not supported `atime` proper support requires precision so the log is appropriate.

Beyond that it won't make sense for us to single out EFS

**Comment by realthered** [comment]
Then how about editing log like "atime support or not supporting nanosecond"? I took 2 days to find it becuase I'm not close to linux-detailed things. Maybe there were some people like me 😞

**Comment by harshavardhana** [comment]
> Then how about editing log like "atime support or not supporting nanosecond"? I took 2 days to find it becuase I'm not close to linux-detailed things. Maybe there were some people like me

you could have asked on our https://slack.min.io - or asked here https://github.com/minio/minio/discussions
