### ISSUE TITLE
Extremly slow max-keys request via aws-sdk

### ISSUE THREAD

**Issue by thoro** [minio/minio#11441]
Hi

## Expected Behavior

The request should return nearly instantly

## Current Behavior

The request takes > 10 seconds to be finished.

## Context

I'm using harbor 2.1.3 with minio as a storage backend and sometimes it happens that the pulling of an image takes multiple minutes, on other times it's very quick.

I have indentified the following request:

[04/Feb/2021:10:43:09 +0000] "10.019" "GET /harbor?max-keys=1&prefix=docker%2Fregistry%2Fv2%2Fblobs%2Fsha256%2F20%2F20eef16e2602f17cc25f5a4b38bfca0338512764124a33d98231977b05e4c65e%2Fdata HTTP/2.0" 200 769 "-" "aws-sdk-go/1.15.11 (go1.14.13; linux; amd64)" "-" "-" "-"

## Your Environment

* Version used (`minio --version`): RELEASE.2020-11-13T20-10-18Z
* Server setup and configuration: Minio runs on 8 nodes, each with an 8 TB SSD (NVMe, PCIex3 x4, > 4 GB/s) connected over infiniband 100G
* Operating System and version (`uname -a`): Docker Container, on top of Containerd 1.4.3 on top of Centos 7

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2020-11-13T20-10-18Z

@Thoro please upgrade to the latest release and let us know how it goes.

**Comment by thoro** [comment]
@harshavardhana I tried to update via rolling update, but the first node never came up and errored out with:

```
Unable to read 'format.json' from http://s3-storage-6.s3-storage.platon-live.svc.cluster.local:9000/data/s3-storage/storage0: Not allowed (POST /minio/storage/data/s3-storage/storage0/v26/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)
```

I didn't want to continue with more nodes due to this ... does the update require a full restart?

**Comment by klauspost** [comment]
Yes, rolling upgrade is not supported for this jump.

**Comment by harshavardhana** [comment]
> @harshavardhana I tried to update via rolling update, but the first node never came up and errored out with:
> 
> ```
> Unable to read 'format.json' from http://s3-storage-6.s3-storage.platon-live.svc.cluster.local:9000/data/s3-storage/storage0: Not allowed (POST /minio/storage/data/s3-storage/storage0/v26/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)
> ```
> 
> I didn't want to continue with more nodes due to this ... does the update require a full restart?

Always upgrade all nodes, rolling upgrade is not recommended usually for MinIO.

**Comment by thoro** [comment]
What's the guidance on updating a heavily (as in constantly having request happen) used cluster? I can't just stop the traffic there.

**Comment by harshavardhana** [comment]
> What's the guidance on updating a heavily (as in constantly having request happen) used cluster? I can't just stop the traffic there.

Just upgrade all of them @Thoro it takes few seconds to upgrade.

**Comment by harshavardhana** [comment]
If you have a production cluster and need hand holding please subscribe to our subscription https://min.io/pricing @Thoro

**Comment by thoro** [comment]
Well, it's not about handholding, it's thinking about what might happen, and an upgrade requires all nodes to be done for a few seconds (especially with kubernetes pods stopping and starting), and it case that fails you got a longer downtime .. anyways you previously had the releases marked if they worked via rolling update or only via full upgrade, haven't seen those notices on any releases lately.


Back to topic: upgraded, first test seemed fine, I will close it for now and reopen in case the same issue shows up again.

**Comment by harshavardhana** [comment]
> Well, it's not about handholding, it's thinking about what might happen, and an upgrade requires all nodes to be done for a few seconds (especially with kubernetes pods stopping and starting), and it case that fails you got a longer downtime .. anyways you previously had the releases marked if they worked via rolling update or only via full upgrade, haven't seen those notices on any releases lately.

Yes if you used our operator it can handle upgrades more seamlessly @Thoro https://github.com/minio/operator - if you do things on your own in vanilla k8s then you have to bear with our implementation requirements.

**Comment by thoro** [comment]
@harshavardhana I will try the operator out
