### ISSUE TITLE
madmClnt.StorageInfo(context.Background()): json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int exit status 1

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#11453]
Hi, the API madmClnt.StorageInfo(context.Background()) from madmin return json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int exit status 1 

just run the example below:

https://github.com/minio/minio/blob/master/pkg/madmin/examples/storage-info.go

thnx.

**Comment by harshavardhana** [comment]
> Hi, the API madmClnt.StorageInfo(context.Background()) from madmin return json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int exit status 1
> 
> just run the example below:
> 
> https://github.com/minio/minio/blob/master/pkg/madmin/examples/storage-info.go
> 
> thnx.

There is no StandardSCData anymore @fdefilippo it is deprecated.

**Comment by fdefilippo** [comment]
ok so what to use?

**Comment by harshavardhana** [comment]
> ok so what to use?

you shouldn't be using this at all - what are you trying to use this for?

**Comment by harshavardhana** [comment]
> you shouldn't be using this at all - what are you trying to use this for?

you should upgrade your dependency with `go get github.com/minio/minio/pkg/madmin`

**Comment by fdefilippo** [comment]
I use the API to show the status of the disks and their usage:

![image](https://user-images.githubusercontent.com/16714986/107019467-fd2e5600-67a1-11eb-98e8-7685c463be20.png)

**Comment by fdefilippo** [comment]
$ go get github.com/minio/minio/pkg/madmin
$ curl -O https://raw.githubusercontent.com/minio/minio/master/pkg/madmin/examples/storage-info.go
$ # and after the appropriate modifications to the accessKey/secretKey
$ go run storage-info.go
2021/02/05 11:10:10 json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int
exit status 1

**Comment by harshavardhana** [comment]
> $ go get github.com/minio/minio/pkg/madmin
> $ curl -O https://raw.githubusercontent.com/minio/minio/master/pkg/madmin/examples/storage-info.go
> $ # and after the appropriate modifications to the accessKey/secretKey
> $ go run storage-info.go
> 2021/02/05 11:10:10 json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int
> exit status 1

You should always use GO111MODULE=on to get the correct dependency.

**Comment by fdefilippo** [comment]
$ export GO111MODULE=on
$ go get github.com/minio/minio/pkg/madmin
go: downloading github.com/minio/minio v0.0.0-20210205093423-af9cb5f5f2f6
go: found github.com/minio/minio/pkg/madmin in github.com/minio/minio v0.0.0-20210205093423-af9cb5f5f2f6
go: downloading github.com/minio/minio-go/v7 v7.0.8
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/StackExchange/wmi v0.0.0-20190523213315-cbe66965904d
go: downloading golang.org/x/sys v0.0.0-20210119212857-b64e53b001e4
go: downloading github.com/go-ole/go-ole v1.2.4
$ cd ~/go/src/github.com/minio/minio/pkg/madmin/examples
go run storage-info.go
2021/02/05 19:12:03 json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int
exit status 1

**Comment by harshavardhana** [comment]
> $ cd ~/go/src/github.com/minio/minio/pkg/madmin/examples
> go run storage-info.go
> 2021/02/05 19:12:03 json: cannot unmarshal array into Go struct field .Backend.StandardSCData of type int
> exit status 1

This is pointing to older code @fdefilippo 

```
~ go run storage-info.go 
2021/02/05 10:48:32 {[{/home/play/data1 false /home/play/data1 false ok 38c531bf-c547-4937-a143-a4f68d807c07  8378122240 4765220864 3612901376 0 0 0 0 0} {/home/play/data2 false /home/play/data2 false ok d779cd7a-a5f2-4bff-8cb0-475f261ee4bd  8378122240 4764463104 3613659136 0 0 0 0 0} {/home/play/data3 false /home/play/data3 false ok 785f7ab3-c064-4cd2-8a29-aeb8c0897160  8378122240 4763283456 3614838784 0 0 0 0 0} {/home/play/data4 false /home/play/data4 false ok 736739a5-d009-4824-9596-6e989ac5c8c3  8378122240 4764028928 3614093312 0 0 0 0 0}] {2 map[] map[] 2 2}}
```

```go
package main

import (
        "context"
        "log"

        "github.com/minio/minio/pkg/madmin"
)

func main() {
        // Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY and my-bucketname are
        // dummy values, please replace them with original values.

        // API requests are secure (HTTPS) if secure=true and insecure (HTTPS) otherwise.
        // New returns an MinIO Admin client object.
        madmClnt, err := madmin.New("play.minio.io", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
        if err != nil {
                log.Fatalln(err)
        }

        st, err := madmClnt.StorageInfo(context.Background())
        if err != nil {
                log.Fatalln(err)
        }
        log.Println(st)
}
```
