### ISSUE TITLE
[documentation] User management in gateway mode

### ISSUE THREAD

**Issue by james64** [minio/minio#11458]
**Is your feature request related to a problem? Please describe.**
Documentation should explain more about user accounts management in gateway mode. Ability to manage users in general are mentioned [here](https://docs.min.io/docs/minio-multi-user-quickstart-guide.html). A removal of admin API is mentioned [here](https://docs.min.io/docs/minio-gateway-for-nas.html). I found no other relavant info.

**Describe the solution you'd like**
Is multiuser fine grained access control operations possible in gateway mode? If so how should one go about configuring it without admin API. Or is it somehow tied to permissions setup in underlying storage backend? Questions like these should be addressed in documentation at least briefly.

**Describe alternatives you've considered**
N/A

**Additional context**
This report is about documentation. Just to explain our situation so it (maybe) helps with better doc. We have NFS storage volume provided. It has it's own mechanisms to protect the data so we do not need any replicaiton. We need S3 api over it preferably with user accounts and access control. We wanted high availability of S3 api so we used gateway mode so that we can have more minio instances ready to serve the data from one volume...

Thanks for minio!

**Comment by harshavardhana** [comment]
> Documentation should explain more about user accounts management in gateway mode. Ability to manage users in general are mentioned [here](https://docs.min.io/docs/minio-multi-user-quickstart-guide.html). A removal of admin API is mentioned [here](https://docs.min.io/docs/minio-gateway-for-nas.html). I found no other relavant info.

That is not our mainline product @james64 - Gateway is implemented for repatriation of data to MinIO distributed setup. Gateway is not taking any more features. 

The multi-user quickstart guide works as is https://github.com/minio/minio/tree/master/docs/multi-user#1-prerequisites here its mentioned explicitly 

> Configure etcd (optional needed only in gateway or federation mode) - Etcd V3 Quickstart Guide

If configured rest of the document follows with nothing special needed.
