### ISSUE TITLE
cache json files while enable O_direct

### ISSUE THREAD

**Issue by sirizhou** [minio/minio#11455]
**Is your feature request related to a problem? Please describe.**
I enable O_direct
```shell
mc admin config set myminio/ storage_class dma="read+write"
```
then I put and get 1000000 small files
```shell
warp get --host=127.0.0.1:9000 --access-key=minioadmin --secret-key=minioadmin --obj.size=1M --duration=5m --objects=1000000
```
Cache usage quickly rises
```shell
Every 2.0s: free -mh                                                      sm150: Fri Feb  5 02:53:21 2021
              total        used        free      shared  buff/cache   available
Mem:          251Gi        12Gi       222Gi       9.0Mi        16Gi       240Gi
Swap:         2.0Gi          0B       2.0Gi
```
If put or get 25 large files(1G), cache usage will not rise.
**Describe the solution you'd like**
When O_direct is enabled, will json files still be cached?

**Describe alternatives you've considered**
if i use warp to test list operation. that problem matters a lot. May I list json files from storage directly but not list them from page cache?

**Comment by harshavardhana** [comment]
O_DIRECT is not meant for caching - it is meant for erasure-coded backends @sirizhou
