### ISSUE TITLE
madmin.AccountInfo returns `The Access Key Id you provided does not exist in our records` in federation mode.

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#11456]
Environment:

- server: `2021-02-01T22:56:52Z`
- madmin: latest

I have 2 clusters in federation mode locally:

```shell
{
    "c3bef3f9-0dd6-4624-92fe-5c5b7cb48b6a": {
        "nodes": [
            "192.168.50.11:9000",
            "192.168.50.12:9000"
        ],
        "usage": {
            "bucketsCount": 1,
            "bucketsSizes": {
                "toto-bucket": 0
            },
            "lastUpdate": "2021-02-05T10:14:20.461551216Z",
            "objectsCount": 0,
            "objectsSizesHistogram": null,
            "objectsTotalSize": 0
        }
    },
    "d4fceb7a-6bbe-46ee-be72-e2c225c4efb5": {
        "nodes": [
            "192.168.50.21:9000",
            "192.168.50.22:9000"
        ],
        "usage": {
            "bucketsCount": 1,
            "bucketsSizes": {
                "test-bucket": 0
            },
            "lastUpdate": "2021-02-05T10:05:04.118255801Z",
            "objectsCount": 0,
            "objectsSizesHistogram": null,
            "objectsTotalSize": 0
        }
    }
}
```

Before upgrading with ` go get github.com/minio/minio/pkg/madmin`, I always got informations about an account with:

```go
adminClient, err := madmin.New(randomMinioURL, "YOUR-ACCESSKEYID", "YOUR-SECRETACCESSKEY", true)
accountInfo, err := adminClient.AccountUsageInfo(a.TimeoutContext())
```

After the upgrade, I changed `AccountUsageInfo` by `AccountInfo` but it returns on some nodes:

```shell
The Access Key Id you provided does not exist in our records.
```
```go
adminClient, err := madmin.New(randomMinioURL, "YOUR-ACCESSKEYID", "YOUR-SECRETACCESSKEY", true)
accountInfo, err := adminClient.AccountInfo(a.TimeoutContext())
```

For `adminClient.ListUsers()`, it returns an empty array in some nodes.

**Comment by ToLToL** [comment]
It should return value regardless of in which Minio server we create the admin client right?

**Comment by harshavardhana** [comment]
> It should return value regardless of in which Minio server we create the admin client right?

@ToLToL are you using etcd? then its etcd load that is taking time.

**Comment by ToLToL** [comment]
@harshavardhana Yes I use etcd

**Comment by harshavardhana** [comment]
> @harshavardhana Yes I use etcd

Do you see the user at `config/iam/users/` ?  @ToLToL

**Comment by ToLToL** [comment]
Yes, I see all users:

```
config/iam/users/test-user1/identity.json
����fUȘ�W1�I3�zo��bܤ /M��e6Ha"KDV����0H�iH��i�TUԉ�^�bPi]P���f�w�A��������$��MЀq�}P�b�|I�+�S�T-���\�,n����z�,@KD�
�ֱ�H���,���$;�jh�f4?�ñ.���YwC�5��������ʏ
config/iam/users/mario/identity.json
�jm	�
          !��f�~��T˞�M�v�F3�j]B
'�_.=
�qN ߩj}g�����c�w��2~3z�f�n�G;���6ˤ�e$,�W�L5�[MU�:*�\`ȒvȦ%E��
                                                            7��j�r/�;q���ӝ��RS�^{���BO�/4�t	KS�;=3�*u�`������ȣH�����
config/iam/users/toto123123/identity.json
�]��Id��k_�m
�^s[�u?(@w�$~��AE��d���pn�S�9�|
                               YH����o�ga�&����>���G]��
V                                                      �F#�EY���3Z� �iq�ms��Ħ���{���x�QȺ�n�J��&Rd�a�#��XeY�5`L���lw��#~����⮘S��Ts��n�^� ��0>?��,U
config/iam/users/test-user2/identity.json
��k�/&YHd�kY��D���,gS�7ǯ^_�S��?���2@W]f6�:
               �h�By�E`�:KZH�V����X;���NޟX�������F��!A�x
�'c�K��D
        ���!esI�?ϤC��ɞ�)���?�q9�+(�6���4o�?
                                           k
```

**Comment by harshavardhana** [comment]
> Yes, I see all users:

Then do you see etcd timeout errors in MinIO console?

**Comment by ToLToL** [comment]
No etcd timeout errors.

**Comment by harshavardhana** [comment]
> No etcd timeout errors.

@ToLToL then there is some communication issue with etcd that's why MinIO is not able to get the exact users.

**Comment by ToLToL** [comment]
@harshavardhana 

It's strange because I can get users from the VM where MinIO runs with: `etcdctl --endpoints="{etcd_endpoint}" --cacert ca.pem --cert etcd.pem --key etcd-key.pem get --prefix 'config/iam/users/'`

**Comment by harshavardhana** [comment]
> It's strange because I can get users from the VM where MinIO runs with: `etcdctl --endpoints="{etcd_endpoint}" --cacert ca.pem --cert etcd.pem --key etcd-key.pem get --prefix 'config/iam/users/'`

Did you configure MinIO to use the ETCD client certs?

**Comment by ToLToL** [comment]
I have the same environment as before, I just updated MinIO server to the latest release: ` RELEASE.2021-02-01T22-56-52Z ` and madmin with `go get github.com/minio/minio/pkg/madmin`.

Some nodes return the correct accountInfo whereas some return `The Access Key Id you provided does not exist in our records.`

**Comment by ToLToL** [comment]
> > It's strange because I can get users from the VM where MinIO runs with: `etcdctl --endpoints="{etcd_endpoint}" --cacert ca.pem --cert etcd.pem --key etcd-key.pem get --prefix 'config/iam/users/'`
> 
> Did you configure MinIO to use the ETCD client certs?

yes

**Comment by harshavardhana** [comment]
> Some nodes return the correct accountInfo whereas some return `The Access Key Id you provided does not exist in our records.`

I just tried locally on an etcd setup, I don't see this problem.

**Comment by ToLToL** [comment]
@harshavardhana

When I try with `mc admin user info local-cluster-02 mario --insecure --debug`, I  ALWAYS get:

```
mc: <DEBUG> GET /minio/admin/v3/user-info?accessKey=mario HTTP/1.1
Host: 192.168.50.21:9000
User-Agent: MinIO (darwin; amd64) madmin-go/0.0.1 mc/RELEASE.2021-01-30T00-50-42Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20210205//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210205T200813Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Content-Length: 230
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 05 Feb 2021 20:08:13 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1660F2DC06E7BB71
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminNoSuchUser","Message":"The specified user does not exist. (Specified user does not exist)","Resource":"/minio/admin/v3/user-info","RequestId":"1660F2DC06E7BB71","HostId":"d4fceb7a-6bbe-46ee-be72-e2c225c4efb5"}
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: DigiCert Inc
mc: <DEBUG>  >> Expires: 2021-10-13 12:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: DigiCert Inc
mc: <DEBUG>  >> Expires: 2027-11-27 12:46:10 +0000 UTC
mc: <DEBUG> Response Time:  6.272357ms

mc: <ERROR> Unable to get user info. The specified user does not exist. (Specified user does not exist)
 (1) admin-user-info.go:70 cmd.mainAdminUserInfo(..) Tags: [local-c-02, mario]
 (0) admin-user-info.go:70 cmd.mainAdminUserInfo(..)
 Release-Tag:RELEASE.2021-01-30T00-50-42Z | Commit:ade302d9693f | Host:macbook-pro | OS:darwin | Arch:amd64 | Lang:go1.15.7 | Mem:2.3 MB/76 MB | Heap:2.3 MB/66 MB.
```

**Comment by harshavardhana** [comment]
Please test with latest release @ToLToL - closing this issue.

**Comment by ToLToL** [comment]
@harshavardhana 

In another federation setup with 3 clusters, 5k users and buckets, I create an admin client in a random node:

```go
adminClient, err := madmin.New(randomMinioURL, "YOUR-ACCESSKEYID", "YOUR-SECRETACCESSKEY", true)
accountInfo, err := adminClient.AccountInfo(a.TimeoutContext())
```

Sometimes it returns all buckets, sometimes `null`.

**Comment by ToLToL** [comment]
It seems like you should create an admin client in a node within the cluster where the buckets are.

for instance: 

I have cluster A and B and my bucket is inside the cluster A.

If I create an admin client in a node within cluster A: I get my bucket with `AccountInfo`
Otherwise, it returns null

Is it the desired behavior ? I thought that it should return all buckets regardless of the node where the admin client is created.

**Comment by ToLToL** [comment]
I always get user's buckets with: ` RELEASE.2020-10-18T21-54-12Z` for server and `AccountUsageInfo`.

I think this is a regression.

**Comment by ToLToL** [comment]
@harshavardhana 

It's working. Thanks
