### ISSUE TITLE
Horrible performance on Windows Server 2019 with iscsi and ssl 

### ISSUE THREAD

**Issue by kakachen001** [minio/minio#11477]
I am getting horrible speed in this rare scenario. I have been testing for almost a month to locate the problem. 
My Setup:
Minio Server is running on Windows Server 2019 VM hosted on a Server 2019 Hyper V
ISCSI target is TrueNAS 12 Core.
SSL is a secp256r1 

## Expected Behavior

I should be about to get around 400-500 Mbps since that what i am getting when there's no problem.

## Current Behavior

Currently I am getting a burst speed of around 30 Mbps and the transfer will stop for couple sec after couple MB of data has been transferred.  

## Possible Solution

No Idea

## Steps to Reproduce (for bugs)

I was able to reproduce the problems on more than 10 server 2012, 2016, and 2019 VMs. It only happens when the block storage is connected via iscsi and ssl enabled. There's no problem if SSL is not enabled. 

I used the following command:

minio --certs-dir C:\Minio_Server\certs server --address :50010 E:\Minio_Data\Tenant_10

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:

Minio Server is running on Windows Server 2019 VM hosted on a Server 2019 Hyper V
ISCSI target is TrueNAS 12 Core.
SSL is a secp256r1 

* Operating System and version (`uname -a`): Windows Server 2019

**Comment by harshavardhana** [comment]
Single drive setups can give it only the best that is possible with your set-up. I don't think we can make it any faster artificially.

**Comment by harshavardhana** [comment]
Ideal use case bring real disks and real JBODs..

**Comment by kakachen001** [comment]
If I am able to get 400-500 Mbps via iscsi without SSL and unusable speed after enabling ssl I would consider that as a bug. That's not making it artificially faster. 

> Single drive setups can give it only the best that is possible with your set-up. I don't think we can make it any faster artificially.

**Comment by harshavardhana** [comment]
> If I am able to get 400-500 Mbps via iscsi without SSL and unusable speed after enabling ssl I would consider that as a bug. That's not making it artificially faster.
> 
> >

You need some real hardware to keep SSL faster, which shows that your CPU is the bottleneck here. I don't think there is anything we can do here sorry.

Our TLS/SSL stack is Go runtime which is by far the fastest in the industry. So if that is not fast then there are some serious problems with your CPU.

**Comment by kakachen001** [comment]
You got to be kidding me right ? 
I am able to get full with ssl enable when it is using a local disk and not iscsi ur blaming my CPU which is sitting at 2% !!!!

> > If I am able to get 400-500 Mbps via iscsi without SSL and unusable speed after enabling ssl I would consider that as a bug. That's not making it artificially faster.
> 
> > 
> 
> > >
> 
> 
> 
> You need some real hardware to keep SSL faster, which shows that your CPU is the bottleneck here. I don't think there is anything we can do here sorry.
> 
> 
> 
> Our TLS/SSL stack is Go runtime which is by far the fastest in the industry. So if that is not fast then there are some serious problems with your CPU. 
> 
>

**Comment by harshavardhana** [comment]
If you have a real reproducer with some code we can help, share some profiles, metrics etc, otherwise, there is nothing we can do here unfortunately @kakachen001

**Comment by klauspost** [comment]
@kakachen001 You are welcome to write `sales@minio.io` to get access to [SUBNET](https://min.io/pricing) where we can go into more detailed diagnostics of your problem.
