### ISSUE TITLE
Again broken replication in the new release RELEASE.2021-02-07T01-31-02Z

### ISSUE THREAD

**Issue by pavel-z1** [minio/minio#11472]
After update from release RELEASE.2021-01-30T00-20-58Z to release ELEASE.2021-02-07T01-31-02Z was broken replication.
Replication of the files between replicated bucket randomly failed.

## Expected Behaviour
Successfully replicated new files

## Current Behavior
```
# mc stat local/test/test_file.jpeg
Name      : test_file.jpeg
Date      : 2021-02-07 13:35:59 CET
Size      : 301 KiB
ETag      : ff2116dad429974ffe0fd92156e3c899
VersionID : 8b3424f2-234a-4439-88a4-b7b27b4b3369
Type      : file
Metadata  :
  Content-Type: image/jpeg
Replication Status: FAILED
```

## Possible Solution
Downgrade to minio RELEASE.2021-01-30T00-20-58Z

## Steps to Reproduce (for bugs)
1. Configure Replication between buckets with enabled Delete-Marker replication
2. Upload several files
3. Check file on replicated bucket

## Regression
This issue a regression

## Your Environment
Minio RELEASE.2021-02-07T01-31-02Z

**Comment by harshavardhana** [comment]
@pavel-z1 can you provide more details like server logs? - you haven't seemed to be able to share anything about your setup and nothing that can help us fix these bugs.

**Comment by poornas** [comment]
Can you give more details about your server setup -  please share command line how you are starting the server, replication config and `mc admin trace` on the destination side - if replication is failing sporadically, is your network stable between these 2 clusters? The failures should get retried once the scanner picks them up for retry which runs every minute.

**Comment by pavel-z1** [comment]
OS: CentOS Linux release 8.2.2004 (Core)
MinIO in docker: 
```
# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                  PORTS               NAMES
7c7664d5f146        minio/minio:RELEASE.2021-01-30T00-20-58Z   "/usr/bin/docker-ent…"   17 hours ago        Up 17 hours (healthy)                       minio_server
```

Buckets replication configs:
```
Rotterdam
mc admin bucket remote ls local | grep prd-faxes
http://minio-05.ams01.internal:80        prd-faxes              ->prd-faxes               arn:minio:replication:ams01:eb1032f7-2ec5-4ed5-a120-2a288e449b5a:prd-faxes

Amsterdam
mc admin bucket remote ls local | grep prd-faxes
http://minio-01.rot01.internal:80        prd-faxes              ->prd-faxes               arn:minio:replication:rot01:6c71afb5-76a5-44f2-87a4-9313c7e0b1fa:prd-faxes
```

Nginx Proxy server used between Minio clusters. Nginx configuration:
```
upstream minio_upstream {
    least_conn;
    zone minio_upstream_mem_zone 64k;
    server 192.168.24.40:9000 weight=1 max_fails=1 fail_timeout=10s;
    server 192.168.24.61:9000 weight=1 max_fails=1 fail_timeout=10s;
    server 192.168.24.22:9000 weight=1 max_fails=1 fail_timeout=10s;
    server 192.168.24.13:9000 weight=1 max_fails=1 fail_timeout=10s;
}

proxy_cache_path /mnt/tmpfs-nginx/ keys_zone=backend_proxy_cache:10m
                levels=1:2 max_size=2g
                inactive=1d use_temp_path=off;
proxy_cache_min_uses 1;
proxy_cache_revalidate on;
proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
proxy_cache_valid 200 1d;
proxy_cache_valid 301 1m;

ignore_invalid_headers off;
client_max_body_size 0;
client_body_buffer_size 20M;

# I TOLD YOU NOT TO CACHE HEAD REQUESTS !@#$%
map $request_method $head_nocache {
    default 0;
    "HEAD" 1;
}

# Don not cache URLs with continuation-token argument
map $args $args_nocache {
    default $head_nocache;
    "~continuation-token=" 1;
    "~delimiter=" 1;
}

# Check if file size is less than 10000000
map $upstream_http_content_length $result_nocache {
    default 1;
    "~^[0-9]{0,7}$" $args_nocache;
}

server {
    listen 80 default_server;
    server_name minio-ha-access-02.ams01.internal;
    client_max_body_size 1000m;

    location / {
        add_header X-Cache-Status "$upstream_cache_status" always;
        proxy_pass http://minio_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_set_header Authorization $http_authorization;
        proxy_http_version 1.1;

        proxy_cache backend_proxy_cache;
        proxy_buffering on;
        proxy_no_cache $result_nocache;
        proxy_cache_convert_head off;
        proxy_cache_key  "$scheme$proxy_host$request_method$request_uri$is_args$args";
        proxy_cache_methods GET;
        proxy_cache_revalidate on;
        chunked_transfer_encoding off;

    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }


}
```

Hi @harshavardhana , you can at least try to reproduce problem with **Steps to Reproduce**. This information enough for your QA team to replicate bug. It is very strange to see from you a statement that I did not provide information, when you did not even try reproduce the problem. 

Hi @poornas , we are don't had problems with network between datacenters during tests.
We have 12 buckets. The problem occurred on several buckets, other buckets It is not affected by the problem. This is what was meant by `replicated bucket randomly failed`.

Trace with error from destination side. Hostnames were masked. If you will need clean hostnames please provide private channel to which I can send you raw logs.
```
minio-08.ams01.internal [REQUEST s3.HeadObject] 06:36:40.638
minio-08.ams01.internal HEAD /prd-faxes/test2.jpeg?versionId=a715af23-0c1d-4303-bf98-5bdc7bd9b1d4
minio-08.ams01.internal Proto: HTTP/1.1
minio-08.ams01.internal Host: minio-02.ams01.internal
minio-08.ams01.internal User-Agent: MinIO (linux; amd64) minio-go/v7.0.8
minio-08.ams01.internal X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio-08.ams01.internal X-Forwarded-For: 192.168.64.11
minio-08.ams01.internal X-Real-Ip: 192.168.64.11
minio-08.ams01.internal Content-Length: 0
minio-08.ams01.internal X-Forwarded-Proto: http
minio-08.ams01.internal X-Minio-Source-Proxy-Request: false
minio-08.ams01.internal Authorization: AWS4-HMAC-SHA256 Credential=repluser/20210208/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-source-proxy-request, Signature=1a5130e2af0defd6ab66602e6af6d9c1a0312c41f0df3e92de114961ddef1ead
minio-08.ams01.internal X-Amz-Date: 20210208T063640Z
minio-08.ams01.internal
minio-08.ams01.internal [RESPONSE] [06:36:40.638] [ Duration 127µs  ↑ 150 B  ↓ 225 B ]
minio-08.ams01.internal 400 Bad Request
minio-08.ams01.internal X-Amz-Request-Id: 1661B2508ECD3957
minio-08.ams01.internal X-Xss-Protection: 1; mode=block
minio-08.ams01.internal Accept-Ranges: bytes
minio-08.ams01.internal Content-Length: 0
minio-08.ams01.internal Content-Security-Policy: block-all-mixed-content
minio-08.ams01.internal Server: MinIO
minio-08.ams01.internal Vary: Origin
minio-08.ams01.internal X-Amz-Bucket-Region: ams01
minio-08.ams01.internal
minio-08.ams01.internal
minio-07.ams01.internal [REQUEST s3.PutObject] 06:36:40.667
minio-07.ams01.internal PUT /prd-faxes/test2.jpeg?versionId=a715af23-0c1d-4303-bf98-5bdc7bd9b1d4
minio-07.ams01.internal Proto: HTTP/1.1
minio-07.ams01.internal Host: minio-02.ams01.internal
minio-07.ams01.internal Content-Type: image/jpeg
minio-07.ams01.internal X-Minio-Source-Etag: ff2116dad429974ffe0fd92156e3c899
minio-07.ams01.internal X-Real-Ip: 192.168.64.11
minio-07.ams01.internal X-Forwarded-For: 192.168.64.11
minio-07.ams01.internal X-Minio-Source-Mtime: 2021-02-08T06:36:40.604521429Z
minio-07.ams01.internal Content-Length: 307939
minio-07.ams01.internal User-Agent: MinIO (linux; amd64) minio-go/v7.0.8
minio-07.ams01.internal X-Amz-Date: 20210208T063640Z
minio-07.ams01.internal X-Amz-Replication-Status: REPLICA
minio-07.ams01.internal X-Forwarded-Proto: http
minio-07.ams01.internal Authorization: AWS4-HMAC-SHA256 Credential=repluser/20210208/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-replication-status;x-amz-storage-class;x-minio-source-etag;x-minio-source-mtime, Signature=9a4df0eab5957c2ad3c0d5a7b0021be466a94fac551a239567272e7fa61f476e
minio-07.ams01.internal X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
minio-07.ams01.internal X-Amz-Storage-Class: STANDARD
minio-07.ams01.internal <BODY>
minio-07.ams01.internal [RESPONSE] [06:36:40.668] [ Duration 336µs  ↑ 220 B  ↓ 668 B ]
minio-07.ams01.internal 400 Bad Request
minio-07.ams01.internal X-Xss-Protection: 1; mode=block
minio-07.ams01.internal Accept-Ranges: bytes
minio-07.ams01.internal Content-Length: 411
minio-07.ams01.internal Content-Security-Policy: block-all-mixed-content
minio-07.ams01.internal Content-Type: application/xml
minio-07.ams01.internal X-Amz-Request-Id: 1661B250908D4820
minio-07.ams01.internal Server: MinIO
minio-07.ams01.internal Vary: Origin
minio-07.ams01.internal X-Amz-Bucket-Region: ams01
minio-07.ams01.internal <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region is wrong; expecting &#39;ams01&#39;.</Message><Key>test2.jpeg</Key><BucketName>prd-faxes</BucketName><Resource>/prd-faxes/test2.jpeg</Resource><Region>ams01</Region><RequestId>1661B250908D4820</RequestId><HostId>0db2bee9-f5ae-4f42-a88f-5370876397b3</HostId></Error>
minio-07.ams01.internal
```

**Comment by harshavardhana** [comment]
> Hi @harshavardhana , you can at least try to reproduce problem with **Steps to Reproduce**. This information enough for your QA team to replicate bug. It is very strange to see from you a statement that I did not provide information, when you did not even try reproduce the problem.

Your current description should have been present in your earlier report - you can't expect us to imagine all your setup - you should as a community user provide us with relevant information to get to the bottom of this.  The reason we are asking your help is that we can't reproduce this on our end otherwise we have no reason not to fix it. 

I am sorry I don't have the luxury to dig all the details here, we have production customers to support - so it is in your interest to provide relevant information so that we can help each other quickly.

> <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region is wrong; expecting &#39;ams01&#39;.</Message><Key>test2.jpeg</Key><BucketName>prd-faxes</BucketName><Resource>/prd-faxes/test2.jpeg</Resource><Region>ams01</Region><RequestId>1661B250908D4820</RequestId><HostId>0db2bee9-f5ae-4f42-a88f-5370876397b3</HostId></Error>
> minio-07.ams01.internal

Did you happen to add `mc admin bucket remote add --region` while creating your remote targets? @pavel-z1

**Comment by pavel-z1** [comment]
Ok, we will draw the appropriate conclusions about the lack of QA testing before the releases of the public versions of MinIO.


> > `AuthorizationHeaderMalformed`The authorization header is malformed; the region is wrong; expecting 'ams01'.test2.jpegprd-faxes/prd-faxes/test2.jpegams011661B250908D48200db2bee9-f5ae-4f42-a88f-5370876397b3
> > minio-07.ams01.internal
> 
> Did you happen to add `mc admin bucket remote add --region` while creating your remote targets? @pavel-z1

From my previous message:
```
Rotterdam
mc admin bucket remote ls local | grep prd-faxes
http://minio-05.ams01.internal:80        prd-faxes              ->prd-faxes               arn:minio:replication:ams01:eb1032f7-2ec5-4ed5-a120-2a288e449b5a:prd-faxes

Amsterdam
mc admin bucket remote ls local | grep prd-faxes
http://minio-01.rot01.internal:80        prd-faxes              ->prd-faxes               arn:minio:replication:rot01:6c71afb5-76a5-44f2-87a4-9313c7e0b1fa:prd-faxes
```

As you see, region is present in the ARN for both locations:
arn:minio:replication:ams01:eb1032f7-2ec5-4ed5-a120-2a288e449b5a:prd-faxes
arn:minio:replication:rot01:6c71afb5-76a5-44f2-87a4-9313c7e0b1fa:prd-faxes

On the previous Minio version (RELEASE.2021-01-30T00-20-58Z) replication works without issue for the same buckets. This is regression in the latest RELEASE.2021-02-07T01-31-02Z

**Comment by harshavardhana** [comment]
> As you see, region is present in the ARN for both locations:

Looks like that is the issue here, its the region in ARN that is not honored properly.

**Comment by pavel-z1** [comment]
Hi @harshavardhana , @poornas ,

Seems bug is not fully fixed.
I still have issue in the same environment.

I have replicated buckets in two locations: rot01 and ams01.
When I upload file to the location rot01, file successfully replicated to the ams01.
But when I upload file to the ams01 I receive error in the rot01: `<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region is wrong; expecting &#39;rot01&#39;.</Message><Key>test3.jpeg</Key><BucketName>test</BucketName><Resource>/test/test3.jpeg</Resource><Region>rot01</Region><RequestId>1663DABC2D90ABD2</RequestId><HostId>551a8f1e-787f-4a45-8d23-ddcc04529bf4</HostId></Error>`

This is trace from the rot01 minio when I upload file to the ams01:
```
minio1.rot01.local [REQUEST s3.HeadObject] 07:19:53.256
minio1.rot01.local HEAD /test/test3.jpeg?versionId=96847983-434b-4075-ab37-18b14bde94cf
minio1.rot01.local Proto: HTTP/1.1
minio1.rot01.local Host: minio-accesspoint-1.rot01.local
minio1.rot01.local X-Forwarded-For: 192.168.20.92
minio1.rot01.local X-Minio-Source-Proxy-Request: false
minio1.rot01.local Authorization: AWS4-HMAC-SHA256 Credential=repluser/20210215/rot0101/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-source-proxy-request, Signature=cc7938ead76e51e1c2f31114d3ebe2976684c37e7a1715a5a3726ab58ac32c94
minio1.rot01.local User-Agent: MinIO (linux; amd64) minio-go/v7.0.9
minio1.rot01.local X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio1.rot01.local Content-Length: 0
minio1.rot01.local X-Amz-Date: 20210215T071953Z
minio1.rot01.local X-Forwarded-Proto: http
minio1.rot01.local X-Real-Ip: 192.168.20.92
minio1.rot01.local
minio1.rot01.local [RESPONSE] [07:19:53.256] [ Duration 356µs  ↑ 150 B  ↓ 225 B ]
minio1.rot01.local 400 Bad Request
minio1.rot01.local X-Amz-Request-Id: 1663DABC2C040319
minio1.rot01.local X-Xss-Protection: 1; mode=block
minio1.rot01.local Accept-Ranges: bytes
minio1.rot01.local Content-Length: 0
minio1.rot01.local Content-Security-Policy: block-all-mixed-content
minio1.rot01.local Server: MinIO
minio1.rot01.local Vary: Origin
minio1.rot01.local X-Amz-Bucket-Region: rot01
minio1.rot01.local
minio1.rot01.local
minio2.rot01.local [REQUEST s3.PutObject] 07:19:53.281
minio2.rot01.local PUT /test/test3.jpeg?versionId=96847983-434b-4075-ab37-18b14bde94cf
minio2.rot01.local Proto: HTTP/1.1
minio2.rot01.local Host: minio-accesspoint-1.rot01.local
minio2.rot01.local Content-Length: 307939
minio2.rot01.local X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
minio2.rot01.local X-Amz-Storage-Class: STANDARD
minio2.rot01.local X-Real-Ip: 192.168.20.92
minio2.rot01.local Authorization: AWS4-HMAC-SHA256 Credential=repluser/20210215/rot0101/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-replication-status;x-amz-storage-class;x-minio-source-etag;x-minio-source-mtime, Signature=ecd3fffbd487f2b36f04f13c1de6255562a484bead8451fd57b10b57b2799537
minio2.rot01.local User-Agent: MinIO (linux; amd64) minio-go/v7.0.9
minio2.rot01.local X-Forwarded-For: 192.168.20.92
minio2.rot01.local X-Minio-Source-Etag: ff2116dad429974ffe0fd92156e3c899
minio2.rot01.local X-Amz-Date: 20210215T071953Z
minio2.rot01.local X-Amz-Replication-Status: REPLICA
minio2.rot01.local X-Forwarded-Proto: http
minio2.rot01.local Content-Type: image/jpeg
minio2.rot01.local X-Minio-Source-Mtime: 2021-02-15T07:19:53.189863753Z
minio2.rot01.local <BODY>
minio2.rot01.local [RESPONSE] [07:19:53.282] [ Duration 244µs  ↑ 220 B  ↓ 658 B ]
minio2.rot01.local 400 Bad Request
minio2.rot01.local Content-Security-Policy: block-all-mixed-content
minio2.rot01.local Content-Type: application/xml
minio2.rot01.local X-Amz-Bucket-Region: rot01
minio2.rot01.local X-Amz-Request-Id: 1663DABC2D90ABD2
minio2.rot01.local Accept-Ranges: bytes
minio2.rot01.local Server: MinIO
minio2.rot01.local Vary: Origin
minio2.rot01.local X-Xss-Protection: 1; mode=block
minio2.rot01.local Content-Length: 401
minio2.rot01.local <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region is wrong; expecting &#39;rot01&#39;.</Message><Key>test3.jpeg</Key><BucketName>test</BucketName><Resource>/test/test3.jpeg</Resource><Region>rot01</Region><RequestId>1663DABC2D90ABD2</RequestId><HostId>551a8f1e-787f-4a45-8d23-ddcc04529bf4</HostId></Error>
```

To be sure that Nginx cache no effect I have disabled caching. Result is the same, the same issue only in one direction: frpm ams01 to rot01.

I remind, that location is correctly configured in both locations:
```
Rotterdam
mc admin bucket remote ls local | grep prd-faxes
http://minio-05.ams01.internal:80        prd-faxes              ->prd-faxes               arn:minio:replication:ams01:eb1032f7-2ec5-4ed5-a120-2a288e449b5a:prd-faxes

Amsterdam
mc admin bucket remote ls local | grep prd-faxes
http://minio-01.rot01.internal:80        prd-faxes              ->prd-faxes               arn:minio:replication:rot01:6c71afb5-76a5-44f2-87a4-9313c7e0b1fa:prd-faxes
```

Replication works previously without issue in the Minio version RELEASE.2021-01-30T00-20-58Z
All minio servers, have the same minio version:
```
# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                    PORTS               NAMES
4eb0a6107fd7        minio/minio:RELEASE.2021-02-14T04-01-33Z   "/usr/bin/docker-ent…"   30 minutes ago      Up 30 minutes (healthy)                       minio_server
```

**Comment by harshavardhana** [comment]
Re-opening lets take a look

**Comment by harshavardhana** [comment]
> have replicated buckets in two locations: rot01 and ams01.
> When I upload file to the location rot01, file successfully replicated to the ams01.
> But when I upload file to the ams01 I receive error in the rot01: `<?xml version="1.0" encoding="UTF-8"?> <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region is wrong; expecting &#39;rot01&#39;.</Message><Key>test3.jpeg</Key><BucketName>test</BucketName><Resource>/test/test3.jpeg</Resource><Region>rot01</Region><RequestId>1663DABC2D90ABD2</RequestId><HostId>551a8f1e-787f-4a45-8d23-ddcc04529bf4</HostId></Error>`

@pavel-z1 are you sure you did create the config with region settings correctly?

**Comment by pavel-z1** [comment]
> 
> @pavel-z1 are you sure you did create the config with region settings correctly?

What command I can use to check that current region configuration is correct?
I will provide command results

**Comment by harshavardhana** [comment]
> What command I can use to check that current region configuration is correct?
> I will provide command results

Mainly when you created the 

> minio2.rot01.local [REQUEST s3.PutObject] 07:19:53.281
> minio2.rot01.local PUT /test/test3.jpeg?versionId=96847983-434b-4075-ab37-18b14bde94cf
> minio2.rot01.local Proto: HTTP/1.1
> minio2.rot01.local Host: minio-accesspoint-1.rot01.local
> minio2.rot01.local Content-Length: 307939
> minio2.rot01.local X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> minio2.rot01.local X-Amz-Storage-Class: STANDARD
> minio2.rot01.local X-Real-Ip: 192.168.20.92
> minio2.rot01.local Authorization: AWS4-HMAC-SHA256 Credential=repluser/20210215/rot0101/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-replication-status;x-amz-storage-class;x-minio-source-etag;x-minio-source-mtime, Signature=ecd3fffbd487f2b36f04f13c1de6255562a484bead8451fd57b10b57b2799537
> minio2.rot01.local User-Agent: MinIO (linux; amd64) minio-go/v7.0.9
> minio2.rot01.local X-Forwarded-For: 192.168.20.92
> minio2.rot01.local X-Minio-Source-Etag: ff2116dad429974ffe0fd92156e3c899
> minio2.rot01.local X-Amz-Date: 20210215T071953Z
> minio2.rot01.local X-Amz-Replication-Status: REPLICA
> minio2.rot01.local X-Forwarded-Proto: http
> minio2.rot01.local Content-Type: image/jpeg
> minio2.rot01.local X-Minio-Source-Mtime: 2021-02-15T07:19:53.189863753Z
> minio2.rot01.local <BODY>
> minio2.rot01.local [RESPONSE] [07:19:53.282] [ Duration 244µs  ↑ 220 B  ↓ 658 B ]
> minio2.rot01.local 400 Bad Request
> minio2.rot01.local Content-Security-Policy: block-all-mixed-content
> minio2.rot01.local Content-Type: application/xml
> minio2.rot01.local X-Amz-Bucket-Region: rot01
> minio2.rot01.local X-Amz-Request-Id: 1663DABC2D90ABD2
> minio2.rot01.local Accept-Ranges: bytes
> minio2.rot01.local Server: MinIO
> minio2.rot01.local Vary: Origin
> minio2.rot01.local X-Xss-Protection: 1; mode=block
> minio2.rot01.local Content-Length: 401
> minio2.rot01.local <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region is wrong; expecting &#39;rot01&#39;.</Message><Key>test3.jpeg</Key><BucketName>test</BucketName><Resource>/test/test3.jpeg</Resource><Region>rot01</Region><RequestId>1663DABC2D90ABD2</RequestId><HostId>551a8f1e-787f-4a45-8d23-ddcc04529bf4</HostId></Error>

As you can clearly see here 

The region that is actually set 

> minio2.rot01.local X-Amz-Bucket-Region: rot01

The region that you are using in your config however

> > minio2.rot01.local Authorization: AWS4-HMAC-SHA256 Credential=repluser/20210215/rot0101/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-replication-status;x-amz-storage-class;x-minio-source-etag;x-minio-source-mtime, Signature=ecd3fffbd487f2b36f04f13c1de6255562a484bead8451fd57b10b57b2799537

It says `rot0101` there is an extra `01` not sure where it's getting added from you should check that.

**Comment by pavel-z1** [comment]
@harshavardhana , yes, in this particular case issue was in my side. It was incorrect region in the configuration.
Fixed by recreating replication.
Thank you.
