### ISSUE TITLE
changes to errgroup.go break 32 bit arm

### ISSUE THREAD

**Issue by HeavyHorst** [minio/minio#11474]
Sorry for this, i'm planning to migrate to 64bit machines.

## Expected Behavior

minio starts succecfully `after mc admin update`

## Current Behavior

Minio fails with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11a20]
goroutine 137 [running]:
runtime/internal/atomic.goCas64(0x3b5091c, 0xffffffff, 0xffffffff, 0x3, 0x0, 0x0)
runtime/internal/atomic/atomic_arm.go:87 +0x1c
github.com/minio/minio/pkg/sync/errgroup.(*Group).Go.func1(0x3b50900, 0x3, 0x3b509c0)
github.com/minio/minio/pkg/sync/errgroup/errgroup.go:124 +0x11c
created by github.com/minio/minio/pkg/sync/errgroup.(*Group).Go
         github.com/minio/minio/pkg/sync/errgroup/errgroup.go:104 +0x5
```

## Possible Solution

64 bit align the Group  struct.
firstErr is the only fields that is accessed atomically so ist should be enough to move this field to the beginning of the struct.

> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

## Regression

Yes

## Your Environment

* Version used (`minio --version`): RELEASE.2021-02-07T01-31-02Z
* Server setup and configuration: Distributed, 4 Servers with one drive each
* Operating System and version (`uname -a`): Linux odroidxu4 4.14.212-odroidxu4 #12 SMP PREEMPT Wed Feb 3 21:31:20 CET 2021 armv7l armv7l armv7l GNU/Linux

**Comment by HeavyHorst** [comment]
I can confirm that changing Group to:

```
 type Group struct {                                                                                                                                                                                             
      firstErr  int64
      wg        sync.WaitGroup
      bucket    chan struct{}
      errs      []error
      cancel    context.CancelFunc
      ctxCancel <-chan struct{} // nil if no context.
      ctxErr    func() error
  }

```

fixes the problem.

**Comment by harshavardhana** [comment]
We never really test arm32 so these are bound to happen
