### ISSUE TITLE
Minio constantly getting killed by OOM Manager

### ISSUE THREAD

**Issue by thoro** [minio/minio#11482]
Since updating to the newest version, minio gets regularly killed by the OOM Manager.

## Expected Behavior

Not getting killed

## Current Behavior

Getting killed

## Steps to Reproduce (for bugs)

Not sure, used with application as before.

## Context

![Screenshot 2021-02-08 at 15 47 39](https://user-images.githubusercontent.com/554474/107235686-3b877780-6a25-11eb-82e7-81518c6d4dce.png)

## Regression

YES, worked fine before with RELEASE.2020-11-13T20-10-18Z

## Your Environment

* Version used (`minio --version`): RELEASE.2021-02-01T22-56-52Z
* Server setup and configuration: Kubernetes 1.19.7, 20 GB Memory limit per minio instance, 8 instances with each 8 TB SSD
* Operating System and version (`uname -a`): Linux at-host-45 5.4.60 #1 SMP Sun Aug 23 07:18:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thoro** [comment]
Updated to RELEASE.2021-02-07T01-31-02Z just in case it solves something ...

**Comment by harshavardhana** [comment]
This should be fixed with latest release @Thoro

**Comment by thoro** [comment]
Sadly it's not fixed in the newest release I installed!

Is there anything I can provide to debug it?

**Comment by harshavardhana** [comment]
@Thoro which version you were running before?

**Comment by thoro** [comment]
RELEASE.2021-02-01T22-56-52Z then upgraded to RELEASE.2021-02-07T01-31-02Z

I have to say the rate of the restarts is not high currently, it's around 1 / hour - it was much higher with previous version

But I think OOM should not happen with 20 GB of available ram.

**Comment by harshavardhana** [comment]
> But I think OOM should not happen with 20 GB of available ram.

That depends on how much data you have @Thoro can you set GOC=25 environment value? - also capture `mc admin profile start alias/` and then run for 5mins `mc admin profile stop alias/` 

share it here.

**Comment by thoro** [comment]
How much ram per TB of data is recommended?

[profile.zip](https://github.com/minio/minio/files/5946809/profile.zip)

**Comment by harshavardhana** [comment]
> How much ram per TB of data is recommended?

Set GOGC=25 and see if that helps @Thoro and also `GODEBUG=madvdontneed=1` set this ENV.

**Comment by harshavardhana** [comment]
I see that used space is quite low - most probably this is just incorrect reporting due to the following Go bug - its only going to be fixed in go1.16

```
(pprof) top
Showing nodes accounting for 243.66MB, 96.99% of 251.21MB total
Dropped 599 nodes (cum <= 1.26MB)
Showing top 10 nodes out of 99
      flat  flat%   sum%        cum   cum%
     192MB 76.43% 76.43%      192MB 76.43%  github.com/minio/minio/pkg/argon2.NewIDKey.func1
   16.12MB  6.42% 82.85%    16.12MB  6.42%  github.com/ncw/directio.AlignedBlock
      13MB  5.17% 88.02%       13MB  5.17%  github.com/minio/minio/cmd.glob..func6
    5.88MB  2.34% 90.36%     5.88MB  2.34%  github.com/minio/minio/cmd.newReplicationState
    4.58MB  1.82% 92.18%     4.58MB  1.82%  github.com/minio/minio/cmd.newExpiryState
    4.51MB  1.79% 93.98%     4.51MB  1.79%  github.com/minio/minio/cmd.newTransitionState
    2.53MB  1.01% 94.99%     3.08MB  1.23%  compress/flate.NewWriter
    1.82MB  0.72% 95.71%     1.82MB  0.72%  sync.(*Pool).pinSlow
    1.81MB  0.72% 96.43%     1.81MB  0.72%  bytes.makeSlice
    1.41MB  0.56% 96.99%     1.41MB  0.56%  github.com/willf/bitset.New
```

**Comment by harshavardhana** [comment]
BTW you look like a perfect candidate for our production support https://min.io/pricing @Thoro have you considered that? - we can run health diagnostics etc on your setup and provide architecture guidance.

**Comment by harshavardhana** [comment]
> How much ram per TB of data is recommended?

20GiB is not going to be enough in reality if you have a heavily loaded system, minimum you should have 32GiB or above.

**Comment by thoro** [comment]
Reg. subscription I'm not a fan of - one time is more my ballpark.

Reg. issue: It seems to have helped so far, no crashes in the past 9 hours, I will monitor it further.

I see that there's two instances using massively more memory than the others:

![Screenshot 2021-02-09 at 08 58 10](https://user-images.githubusercontent.com/554474/107332875-0296e380-6ab5-11eb-892e-85e22f4ef781.png)

Investigating the pprof of the instances with more memory usage compared to others shows that they both report:

1) pprof shows less memory usage, around ~40 % of reported
2) most memory is allocated in dataUsageCache  serialize/DecodeMsg/replaceHashed
3) both instances use significantly more cpu time

Cpu:

![Screenshot 2021-02-09 at 10 21 14](https://user-images.githubusercontent.com/554474/107342533-991cd200-6ac0-11eb-9b68-281e01318d95.png)


s3_requests_total is similar (within 5%) on all nodes

-) Is this expected?
-) What is causing it? (master behaviour?, internal task?, random caching?)

**Comment by klauspost** [comment]
1) Yes
2) Data crawler, calculating usage. This is strictly related to the number of objects in `bucket/prefix1/prefix2` directory levels.

**Comment by thoro** [comment]
2) Thanks, that explains

Is there a way to monitor the internal processes?
Can I disable the crawler? I don't need the space reporting.

**Comment by klauspost** [comment]
If you want, you can use `MINIO_DISK_USAGE_CRAWL_DEBUG=on`, but it is rather verbose.

It cannot be disabled, since it is responsible for all maintenance tasks.

**Comment by thoro** [comment]
Ok, one thing still doesn't sit right with me .. I did the profiling for the whole cluster for 10 minutes, and the nodes with the high cpu usage look like that:

```
go tool pprof profile-s3-storage-0.s3-storage.platon-live.svc.cluster.local:9000-cpu.pprof                                                                                                                                   11:00:57
File: minio
Type: cpu
Time: Feb 9, 2021 at 10:24am (CET)
Duration: 9.16mins, Total samples = 41.70s ( 7.59%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 24690ms, 59.21% of 41700ms total
Dropped 1096 nodes (cum <= 208.50ms)
Showing top 10 nodes out of 253
      flat  flat%   sum%        cum   cum%
    5690ms 13.65% 13.65%     5880ms 14.10%  syscall.Syscall
    4810ms 11.53% 25.18%     4920ms 11.80%  runtime.findObject
    3800ms  9.11% 34.29%     3800ms  9.11%  runtime.markBits.isMarked (inline)
    2660ms  6.38% 40.67%    13000ms 31.18%  runtime.scanobject
    2360ms  5.66% 46.33%     2380ms  5.71%  runtime.runqgrab
    1390ms  3.33% 49.66%     1390ms  3.33%  runtime.futex
    1240ms  2.97% 52.64%     1240ms  2.97%  runtime.pageIndexOf (inline)
    1200ms  2.88% 55.52%     6970ms 16.71%  runtime.findrunnable
     910ms  2.18% 57.70%      970ms  2.33%  syscall.Syscall6
     630ms  1.51% 59.21%     2450ms  5.88%  runtime.gentraceback
```

And here the pprof file: 
[profile-s3-storage-0.s3-storage.platon-live.svc.cluster.local:9000-cpu.pprof.zip](https://github.com/minio/minio/files/5950708/profile-s3-storage-0.s3-storage.platon-live.svc.cluster.local.9000-cpu.pprof.zip)

I would expect a hint of crawler code.

**Comment by klauspost** [comment]
Not sure what you are looking for, but here it is:

![image](https://user-images.githubusercontent.com/5663952/107357636-a2af3580-6ad2-11eb-9628-686989029b5e.png)

Use `-focus=crawlDataFolder` to get details. It is not a CPU intensive task.

**Comment by thoro** [comment]
Okay, then that doesn't explain why it uses 30% CPU on one node (and 20% on another) - see the cpu graph from before

I assumed based on your answer that the crawler is causing this cpu usage, and also the memory usage.

Is that maybe the heal task?

**Comment by klauspost** [comment]
Probably, but 30% is inconsequential.

**Comment by harshavardhana** [comment]
> Okay, then that doesn't explain why it uses 30% CPU on one node (and 20% on another) - see the cpu graph from before

That is because of GOGC=25 - that would make it busy on CPU and GC is more active where the crawler is running. Crawler only runs from one server.
