### ISSUE TITLE
TFX pipelines fails on Minio but works on AWS

### ISSUE THREAD

**Issue by ConverJens** [minio/minio#11481]
TFX pipelines are fully S3 compatible and runs perfectly on AWS but when using Minio as backend the pipeline fails due to different behaviour from Minio. When using Minio, the Transform component fails.

## Expected Behavior
Any operation that is successful using AWS S3 should work using Minio as well.

## Current Behavior
Some operations fails.

## Steps to Reproduce (for bugs)
1. Deploy Minio
2. Run a TFX pipeline containing a Transform step, as a pipeline using an orchestrator or interactively from a Jupyter server, with Minio as the pipeline root. Example pipeline but need to set S3 args: https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_local.py
3. The transform step will fail.

See TFX issue: https://github.com/tensorflow/tfx/issues/3189

## Context
We are running TFX pipelines on-prem in KubeFlow and would like to use Minio as our end-to-end storage solution. 

## Regression
No, latest version.

## Your Environment
Kubernetes v1.19.6
Minio: latest stabel version

**Comment by ferryvg** [comment]
Fails because HeadObject to Minio returns 404 error for empty object, such as "empty directory"

**Comment by vadmeste** [comment]
@ConverJens are you using MinIO erasure mode here ? (what arguments do you pass when you start your MinIO server)

**Comment by ConverJens** [comment]
@vadmeste Just server:
```
containers:
      - args:
        - server
        - /data
```
and only with one underlying PVC.

**Comment by vadmeste** [comment]
@ConverJens FS mode has some issues with empty directory and I don't think it is going to be fixed anytime soon. 

For the sake of testing, could you try with erasure mode ? Just spawn a new testing environment and instead of passing '/data', pass '/data/{1..4}' (this is not a good idea in the first place but we are just testing right now)

**Comment by ConverJens** [comment]
I have now created a notebook which reproduces this issue locally as well. See tar ball attached. Only pre-requisite is minio running locally on port 9000 (configurable) and that you create a bucket manually with RW permissions. The first cell in the notebook installs the dependencies needed for the pipeline to run.

[tfx-s3-notebook.tar.gz](https://github.com/minio/minio/files/5943780/tfx-s3-notebook.tar.gz)

**Comment by ConverJens** [comment]
@vadmeste Sure, I'll try it and get back to you shortly.

**Comment by ConverJens** [comment]
@vadmeste That worked! Thank you very much for your help!

So I assume that running Minio in erasure mode is the prefferred way then?

**Comment by ConverJens** [comment]
@ferryvg FYI

**Comment by vadmeste** [comment]
> So I assume that running Minio in erasure mode is the prefferred way then?

Yes, many features are not supported in FS mode, it is more intended for a more simplistic use case.

**Comment by ConverJens** [comment]
@vadmeste Right. Thank your for the quick support!

**Comment by ferryvg** [comment]
@ConverJens 
Hm.. I gots same error. But i have outdated MiniO version `You are running an older version of MinIO released 2 weeks ago`

**Comment by ferryvg** [comment]
That fixed after upgrading to latest dev version

**Comment by ConverJens** [comment]
@ferryvg I had the same issue as well now. While testing in KubeFlow, only the latest dev version worked, i.e. RELEASE.2021-02-07T01-31-02Z.

**Comment by wyljpn** [comment]
> @ferryvg I had the same issue as well now. While testing in KubeFlow, only the latest dev version worked, i.e. RELEASE.2021-02-07T01-31-02Z.

Hi, @ConverJens 
I had started Minio in erasure mode with RELEASE.2021-02-07T01-31-02Z image, then run a pipeline containing TFX components.
It got an error, **No response body**, at CsvExampleGen. 
```
INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'
INFO:absl:Running driver for CsvExampleGen
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:select span and version = (0, None)
INFO:absl:Glob pattern for split : /rflow-tfx-pvc/rflow/aman/data/export-*/*
INFO:absl:Regex pattern for split : /rflow-tfx-pvc/rflow/aman/data/export-(?P<span>.*)/[^/]*
INFO:absl:latest span and version = (0, None)
INFO:absl:Adding KFP pod name aman-77txv-1597316287 to execution
/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 198, in launch
    self._exec_properties)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 167, in _run_driver
    component_info=self._component_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/components/base/base_driver.py", line 311, in pre_execution
    component_info=component_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/components/example_gen/driver.py", line 144, in _prepare_output_artifacts
    base_driver._prepare_output_paths(example_artifact)  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/components/base/base_driver.py", line 65, in _prepare_output_paths
    fileio.makedirs(artifact_dir)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/io/fileio.py", line 83, in makedirs
    _get_filesystem(path).makedirs(path)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/io/plugins/tensorflow_gfile.py", line 76, in makedirs
    tf.io.gfile.makedirs(path)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 483, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unknown: : No response body.
```
Do you have an idea to fix it?

**Comment by wy-hua** [comment]
[@w](https://github.com/minio/minio/issues/11481#issuecomment-1010900379) 
Hi @wyljpn. I came into the same error and had the same traceback like you. Have you solved it yet?
