### ISSUE TITLE
Allow backend to chown based on user who uploaded

### ISSUE THREAD

**Issue by zv0n** [minio/minio#11495]
**Is your feature request related to a problem? Please describe.**
In our organization we want to deploy minio on a directory that also acts as an NFS share and having different owner of files based on file uploader would benefit us a lot (users who connect via NFS would only have access to files they own).

**Describe the solution you'd like**
When minio server is run under root, allow mapping from minio users to system users and chown of uploaded files to appropriate user.

**Describe alternatives you've considered**
Inotify script running on the data directory with buckets which changes ownership of new files - problem with buckets that are accessible to multiple users

**Comment by harshavardhana** [comment]
> In our organization we want to deploy minio on a directory that also acts as an NFS share and having different owner of files based on file uploader would benefit us a lot (users who connect via NFS would only have access to files they own).

Gateway codebases are under code freeze and not taking any feature requests, if you wish to influence the roadmap items then you are free to subscribe to us https://min.io/pricing or contact sales@min.io

**Comment by zv0n** [comment]
I didn't mean that we're using gateway. Sorry if my message wasn't clear. We want to use minio server and then share the root data directory of the server via NFS.

**Comment by klauspost** [comment]
@zv0n That doesn't really change that this is a feature we are very unlikely to implement unless there is a push from customers. Sorry.
