### ISSUE TITLE
Show tags in MinIO Filebrowser

### ISSUE THREAD

**Issue by InsOpDe** [minio/minio#11494]
**Is your feature request related to a problem? Please describe.**
We store our Jenkins artifacts with MinIO. It would be important for our internal processes to annotate certain artifacts with a build or release-tag. MinIO already has a tagging ability, but the filebrowser does not reflect it.

It would be great if we could see tags of objects/buckets in the minio-filebrowser. 

**Describe the solution you'd like**
If I am inside a bucket or a directory it would be best to see the annotated tags right below the search-field

In order to see which tags subdirectories and objects have,  it would be nice to see them in the table where the `Size` and `Last Modified` data is displayed.

**Describe alternatives you've considered**
Currently we embed the build information into the directory structure. (In some circumstances this causes redundant data since every run job generates artifact and only some should be tagged, but we want all artifacts stored in MinIO so we just copy the generated artifacts to an extra directory if the job happens to be a release-job)

**Comment by harshavardhana** [comment]
> We store our Jenkins artifacts with MinIO. It would be important for our internal processes to annotate certain artifacts with a build or release-tag. MinIO already has a tagging ability, but the filebrowser does not reflect it.

MinIO Browser is not taking any more feature requests all our work for UI has moved to https://github.com/minio/console - please open feature requests there and start using our https://github.com/minio/console project.
