### ISSUE TITLE
minio over rclone, folder access failed

### ISSUE THREAD

**Issue by ghost** [minio/minio#11496]
OS version: windows 10, x64
rclone version: v1.54.0 - 2021-02-02
minio version: RELEASE.2021-02-07T01-31-02Z
Hi, i mounted dropbox and i try to make minio server D:\drop\dropbox
"D:\drop\dropbox" is mounted dropbox path, but minio cannot access this directory!
Manually with explorer i can copy files to my mounted dropbox path, and delete them
![image](https://user-images.githubusercontent.com/20506433/107370944-4d801d80-6aec-11eb-8626-ad650f6a707e.png)
how to fix it? best regards

**Comment by harshavardhana** [comment]
Looks like a permission issue on the local system, nothing actionable from our end.  Fix your permissions on Windows @connected201

**Comment by ghost** [comment]
> 
> 
> Looks like a permission issue on the local system, nothing actionable from our end. Fix your permissions on Windows @connected201

Hi, i run minio as Administrator!

**Comment by harshavardhana** [comment]
> > Looks like a permission issue on the local system, nothing actionable from our end. Fix your permissions on Windows @connected201
> 
> Hi, i run minio as Administrator!

Doesn't matter there is some permission missing,  do not have access to windows - so don't know beyond this.
