### ISSUE TITLE
Not able to initiate minio via docker secrets

### ISSUE THREAD

**Issue by kc-95-scg** [minio/minio#11506]
Hi, I am trying to initiate a minio server using docker-compose and docker secrets by passing the credentials as MINIO_ROOT_USER_FILE and MINIO_ROOT_PASSWORD_FILE as according to this tutorial.
https://docs.min.io/docs/minio-docker-quickstart-guide.html#:~:text=MinIO%20Custom%20Access%20and%20Secret%20Keys%20using%20Docker%20secrets,as%20access%20and%20secret%20keys.
However, i am am getting ERROR Unable to initialize the server: Unable to initialize sub-systems: Credentials missing.

May i know how to pass the access key and secret key as absolute path?

I am sure that the container is able to access the secret as, when i am initiating the server with MINIO_ACCESS_KEY and MINIO_SECRET_KEY, i am able to do $ cat /run/secrets/minioaccess, and it shows the docker secret.

Here is my docker-compose configuration.
local_minio:
    image: minio/minio:latest
    container_name: local_minio
    entrypoint: sh
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /m_root_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    secrets:
      - minioaccess
      - miniosecret
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minioaccess # This doesnt work
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/miniosecret
      #MINIO_ACCESS_KEY_FILE: /run/secrets/minioaccess # this doesnt work too
      #MINIO_SECRET_KEY_FILE: /run/secrets/miniosecret
      #MINIO_ACCESS_KEY: minio # this works
      #MINIO_SECRET_KEY: testsecret123
    command: -c '/usr/bin/minio server /data'
secrets:
  minioaccess:
    file: minioaccess.txt
  miniosecret:
    file: miniosecret.txt 

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-01-30T00-20-58Z
* Server setup and configuration:- 
* Operating System and version (`uname -a`): Linux kc 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> MINIO_ROOT_USER_FILE: /run/secrets/minioaccess # This doesnt work
> MINIO_ROOT_PASSWORD_FILE: /run/secrets/miniosecret
> #MINIO_ACCESS_KEY_FILE: /run/secrets/minioaccess # this doesnt work too
> #MINIO_SECRET_KEY_FILE: /run/secrets/miniosecret
> #MINIO_ACCESS_KEY: minio # this works
> #MINIO_SECRET_KEY: testsecret123
> command: -c '/usr/bin/minio server /data'
> secrets:
> minioaccess:
> file: minioaccess.txt
> miniosecret:
> file: miniosecret.txt

Your files are called `.txt` and you provide ENV without `.txt` ?

**Comment by kc-95-scg** [comment]
@harshavardhana, thanks for the quick reply.
Yes, this is the syntax for docker-compose secrets. https://docs.docker.com/engine/swarm/secrets/         (scroll to the very end)

I have started the container/minio server when i pass these following variables
      MINIO_ACCESS_KEY_FILE: /run/secrets/minioaccess
      MINIO_SECRET_KEY_FILE: /run/secrets/miniosecret
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
And I am able to view the access keys that i stored in minioaccess.txt.
![Screenshot from 2021-02-10 16-18-17](https://user-images.githubusercontent.com/78844564/107483156-a1a60300-6bbb-11eb-954f-a2d9a516aef4.png)

These errors which i saw during initialization might be helpful
![Screenshot from 2021-02-10 16-19-39](https://user-images.githubusercontent.com/78844564/107483437-06f9f400-6bbc-11eb-9e2a-c8e5f1bf15a3.png)

**Comment by harshavardhana** [comment]
> I have started the container/minio server when i pass these following variables
> MINIO_ACCESS_KEY_FILE: /run/secrets/minioaccess
> MINIO_SECRET_KEY_FILE: /run/secrets/miniosecret
> MINIO_ACCESS_KEY: minio
> MINIO_SECRET_KEY: minio123

It seems to be reading the file correctly if you set different values for both only `env` value gets honored and the server won't start properly, use the right credentials that you used before. .

**Comment by kc-95-scg** [comment]
Yeap, but i would like to start the server only using MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE as env.
(or MINIO_ROOT_USER_FILE and MINIO_ROOT_PASSWORD_FILE)
As shown in the tutorial page here.

![Screenshot from 2021-02-10 16-47-27](https://user-images.githubusercontent.com/78844564/107486192-b2587800-6bbf-11eb-8b69-a2386a25df8e.png)

Raising this up as i figured there could be a bug with initiating the server using absolute file path

**Comment by kc-95-scg** [comment]
@harshavardhana Are there any updates on this?
I am still unable to start the server using MINIO_ROOT_USER_FILE and MINIO_ROOT_PASSWORD_FILE
(or MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE )

**Comment by harshavardhana** [comment]
> @harshavardhana Are there any updates on this?
> I am still unable to start the server using MINIO_ROOT_USER_FILE and MINIO_ROOT_PASSWORD_FILE
> (or MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE )

No updates @kc-95-scg

**Comment by harshavardhana** [comment]
```
~ docker service create --name="minio-service"   --secret="minio_access_key"   --secret="minio_secret_key"   --env="MINIO_ROOT_USER_FILE=minio_access_key"   --env="MINIO_ROOT_PASSWORD_FILE=minio_secret_key" minio/minio server /data
3qn2tjy38skyic7f6qkocknp0
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged 
```

```
~ docker ps -a |grep minio
9585d6c1a429   minio/minio:latest              "/usr/bin/docker-ent…"   41 seconds ago   Up 39 seconds   9000/tcp   minio-service.1.y7n8wtelbqudbqn9go9fsxo8i
```

```
~ docker exec -it 9585d6c1a429 /bin/bash
[root@9585d6c1a429 /]# 
```

```
~ [root@9585d6c1a429 /]# cat /run/secrets/minio_access_key 
admin
[root@9585d6c1a429 /]# cat /run/secrets/minio_secret_key 
password123
[root@9585d6c1a429 /]#
```

```
~ docker logs 9585d6c1a429
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint: http://172.17.0.3:9000  http://127.0.0.1:9000       

Browser Access:
   http://172.17.0.3:9000  http://127.0.0.1:9000      

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
IAM initialization complete
```

and it seems to be up and running with the right set of credentials 

```
~ docker run -it  --entrypoint=/bin/bash --rm minio/mc
[root@4abf759f36f2 /]# 
mc alias set myminio/ http://172.17.0.3:9000 admin password123
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
Added `myminio` successfully

~ [root@078aef747ecb /]# mc admin info myminio
●  172.17.0.3:9000
   Uptime: 4 minutes 
   Version: 2021-03-12T00:00:47Z
   Network: 1/1 OK 

```

This seems to be working fine.  Looks like you have some issue in your environment.
