### ISSUE TITLE
Current release deb file not retrievable via archive/ directory from downloads page

### ISSUE THREAD

**Issue by jonathanschlue-as** [minio/minio#11518]
## Expected Behavior

The current release of the mcli deb Package is retrievable from both of the following locations:

* https://dl.min.io/server/minio/release/linux-amd64/ and
* https://dl.min.io/server/minio/release/linux-amd64/archive/

## Current Behavior

The current release of the mcli-Deb-Package is only retrievable from

* https://dl.min.io/server/minio/release/linux-amd64/ 

but not from

* https://dl.min.io/server/minio/release/linux-amd64/archive/

## Possible Solution

Whenever releasing a new version of minio and accompanying artifacts (.deb, .rpm, checksum files, ...), make sure to release all of the artifacts both

* to https://dl.min.io/server/minio/release/$ARCHITECTURE/ (replacing the last "current" release)
* *and* to https://dl.min.io/server/minio/release/$ARCHITECTURE/archive

This would match the behaviour already implemented e.g. for binary artifacts (e.g. `minio.RELEASE.2021-02-11T08-23-43Z`).

## Steps to Reproduce (for bugs)

1. Determine current minio release deb file under https://dl.min.io/server/minio/release/linux-amd64/

![image](https://user-images.githubusercontent.com/49396111/107630865-70cdd880-6c64-11eb-8692-9c2469bb10a2.png)

2. Try to download it from the `archive/` subdirectory

```
$ wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20210211082343.0.0_amd64.deb
--2021-02-11 11:27:42--  https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20210211082343.0.0_amd64.deb
Resolving dl.min.io (dl.min.io)... 178.128.69.202
Connecting to dl.min.io (dl.min.io)|178.128.69.202|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-11 11:27:43 ERROR 404: Not Found.
```

## Context

We recently switched from consuming binary releases to deb package releases.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-02-11T08-23-43Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
Linux *FQDN REDACTED* 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jonathanschlue-as** [comment]
Also see https://github.com/minio/mc/issues/3605

**Comment by harshavardhana** [comment]
Sure will keep a copy in archive as well.
