### ISSUE TITLE
Hide bucket from client/UI

### ISSUE THREAD

**Issue by jaxWR** [minio/minio#11519]
Hello,

I know this has already been requested but last time I saw it it had no ETA. Has this already been implemented?
is there any way I can do this? (doesn't matter if it's kind of a workaround)

**Describe the solution you'd like**
I set a bucket's policy to download (readable for all). 
I want all the files inside it to be reachable for anyone
But I want to hide the bucket **in the UI**.

**Describe alternatives you've considered**
tweaking UI's code

**Additional context**
Minio running locally on docker. Nothing special.

**Comment by harshavardhana** [comment]
This is not possible and not part of what we want to do. This is too niche a requirement - if you wish you can modify the code yourself and fork the project. 

Closing this as wont fix.
