### ISSUE TITLE
mc show all disk ok, but server reports 1 offline

### ISSUE THREAD

**Issue by titansmc** [minio/minio#11525]
There is a miss match between what `mc` reports and the output from the server logs

## Expected Behavior
Consistent disks status 

## Current Behavior
Server reports:
```
feb 12 09:01:59 ops-object01.domain.de minio[22250]: Status:         191 Online, 1 Offline.
feb 12 09:01:59 ops-object01.domain.de minio[22250]: Endpoint: https://192.168.210.233  https://127.0.0.1

```
since we hit https://github.com/minio/minio/issues/10769

`mc` shows:
```
09:12 $ mc admin info  embl/   
●  ops-object02.domain.de:443
   Uptime: 17 minutes 
   Version: 2021-02-11T08:23:43Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

●  ops-object01.domain.de:443
   Uptime: 17 minutes 
   Version: 2021-02-11T08:23:43Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

7.6 TiB Used, 41 Buckets, 8,864,840 Objects
192 drives online, 0 drives offline

```
## Context
On the other hand `mc admin info --json alias` shows all disks are ok

## Regression
don't know

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-02-11T08-23-43Z`
* Server setup and configuration: CentOS 7
* Operating System and version (`uname -a`): Linux ops-object02.embl.de 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@titansmc, MinIO cluster is faulty tolerant. A cluster can start even if some nodes are down, that's why you have 'offline' status in the startup banner. To get the current status, you just need to run `mc admin info` and it looks all is up and fine in your use case.

Closing this as answered, please feel free to reopen or join https://slack.min.io

**Comment by titansmc** [comment]
but I have just umounted one drive:
```
Found unformatted drive https://ops-object01.domain.de:443/minio/22, attempting to heal...
```
The minio server found there is an unformatted drive and tries to heal it, but it continues to show all disks ok.

```
11:48 $ mc admin info embl/ 
●  ops-object01.domain.de:443
   Uptime: 2 hours 
   Version: 2021-02-11T08:23:43Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

●  ops-object02.domain.de:443
   Uptime: 2 hours 
   Version: 2021-02-11T08:23:43Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

7.6 TiB Used, 41 Buckets, 8,864,840 Objects
192 drives online, 0 drives offline

```

**Comment by klauspost** [comment]
A drive that is healing is considered OK.

**Comment by titansmc** [comment]
but this error is not going away never and all disks have the same sized more or less. But I still don't get why this banner during startup  show 1 failed disk and mc reports them all good at the same time. There was a time where those numbers were consistent.

**Comment by harshavardhana** [comment]
> but this error is not going away never and all disks have the same sized more or less. But I still don't get why this banner during startup show 1 failed disk and mc reports them all good at the same time. There was a time where those numbers were consistent.

We have changed things @titansmc the banner is only transient - real reports you need to see are from `mc admin info` to get more detailed info look at `mc admin info --json`

**Comment by titansmc** [comment]
great. Thanks.
