### ISSUE TITLE
Trying to get minio cluster metrics return "All access to this bucket has been disabled."

### ISSUE THREAD

**Issue by celalsahin** [minio/minio#11521]
Setup: minio cluster, initialized by minio operator(3.0.29) - working over http - using default setting except "http".
## Expected Behavior

I expect http://minios3-cluster:80/minio/v2/metrics/cluster to return cluster metrics similar to what returns from https://play.min.io/minio/v2/metrics/cluster

## Current Behavior

Both with authentication bearer or not I get the following error:

```
[csahin@qc08c ~]$ curl --location --request GET 'http://minios3-cluster:80/minio/v2/metrics/cluster' --header 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AllAccessDisabled</Code><Message>All access to this bucket has been disabled.</Message><Resource>/minio/v2/metrics/cluster</Resource><RequestId></RequestId><HostId>2fea1e51-c01b-47b4-81af-5008edb823d2</HostId></Error>
[csahin@qc08c ~]$
[csahin@qc08c ~]$
[csahin@qc08c ~]$ curl --location --request GET 'http://minios3-cluster:80/minio/v2/metrics/cluster'
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AllAccessDisabled</Code><Message>All access to this bucket has been disabled.</Message><Resource>/minio/v2/metrics/cluster</Resource><RequestId></RequestId><HostId>2fea1e51-c01b-47b4-81af-5008edb823d2</HostId></Error>
[csahin@qc08c ~]$
```

## Steps to Reproduce (for bugs)

1.  Setup minio tenant using minio operator as described in: https://github.com/minio/operator/blob/v3.0.29/README.md
Use "tenant.yaml" method described in https://github.com/minio/operator/blob/v3.0.29/README.md#tenant-setup so you can change to "requestAutoCert: false" - hence have minio running over http instead of default https. After editing tenant.yaml create the tenant via kubectl apply -f tenant.yaml
2. Try to fetch metrics via curl / similar as described above

## Context

I am trying to fetch metrics from my minio cluster.

## Your Environment

* Version used (`minio --version`): image: minio/minio:RELEASE.2020-11-19T23-48-16Z
* Server setup and configuration: OCP cluster 4.6.13
* Operating System and version (`uname -a`): OCP cluster 4.6.13

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): image: minio/minio:RELEASE.2020-11-19T23-48-16Z

This release supports Prometheus metrics at a different endpoint 

https://github.com/minio/minio/tree/master/docs/metrics

```
Deprecated metrics monitoring

Prometheus' data available at /minio/prometheus/metrics is deprecated
```

Please upgrade to latest image to use `/v2/metrics` endpoint
