### ISSUE TITLE
Marker-Delete replication again broken on the latest release RELEASE.2021-02-11T08-23-43Z

### ISSUE THREAD

**Issue by pavel-z1** [minio/minio#11527]
After update minio from release RELEASE.2021-01-30T00-20-58Z to RELEASE.2021-02-11T08-23-43Z again stopped working Delete-Marker replication feature.

## Expected Behaviour on the replicated bucket after file deletion
```
# mc stat local/test/test3.jpeg
mc: <ERROR> Unable to stat `local/test/test3.jpeg`. Object does not exist.
```

## Current Behaviour on the source bucket after file deletion of file on the replica bucket
```
mc stat local/test/test3.jpeg
Name      : test3.jpeg
Date      : 2021-02-12 12:55:18 CET
Size      : 301 KiB
ETag      : ff2116dad429974ffe0fd92156e3c899
VersionID : 22cc44a0-d7ac-4233-b2f1-4a254da38783
Type      : file
Metadata  :
  Content-Type: image/jpeg
Replication Status: COMPLETED
```

## Possible Solution
As current workaround I've downgraded minio back to the RELEASE.2021-01-30T00-20-58Z

## Steps to Reproduce (for bugs)
1. Configure Replication between buckets with enabled Delete-Marker replication
2. Upload file, then delete file.
3. Check file on replicated bucket

I can't provide trace because `mc admin trace  -v -e local` don't show any error on both sides when I delete file.

## Context
All three recent releases of MinIO contain bugs in file replication and replication delete-markers.
As result, it is no any option to use normally replication on the latest releases:
 - RELEASE.2021-02-01T22-56-52Z (broken replication of delete markers) https://github.com/minio/minio/issues/11454
 - RELEASE.2021-02-07T01-31-02Z (broken files replication) https://github.com/minio/minio/issues/11472
 - RELEASE.2021-02-11T08-23-43Z (broken replication of delete markers) current issue.

Maybe, MinIO team should finally stabilise file replication and replication of deleted-markers feature before publish the new release?
Or, maybe you need to send pre release version to QA, that will check replication features next time?

## Regression
This is issue a regression

## Your Environment
OS: CentOS Linux release 8.2.2004 (Core)
MinIO in docker: 
```
# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                  PORTS               NAMES
7c7664d5f146        minio/minio:RELEASE.2021-02-11T08-23-43Z    "/usr/bin/docker-ent…"   41 minutes ago        Up 41 minutes (healthy)                       minio_server
```

**Comment by poornas** [comment]
If you are deleting an object marked as REPLICA, it will not be replicated back to source even with delete-marker setting enabled. This setting is to allow replication of delete-markers on objects that were created on the replica bucket (essentially objects showing x-amz-eplication-status of COMPLETED)

**Comment by harshavardhana** [comment]
> After update minio from release RELEASE.2021-01-30T00-20-58Z to RELEASE.2021-02-11T08-23-43Z again stopped working Delete-Marker replication feature.

So whatever was working perhaps was the original bug that is addressed properly to behave in accordance with AWS S3

**Comment by pavel-z1** [comment]
> If you are deleting an object marked as REPLICA, it will not be replicated back to source even with delete-marker setting enabled. This setting is to allow replication of delete-markers on objects that were created on the replica bucket (essentially objects showing x-amz-eplication-status of COMPLETED)

Hi @poornas , I am don't want and don't expect to replicate replica.
This issue was created because during deletion of replica file minio does not replicate delete-marker to the source bucket.
This is related to the Active-Active replication bucket. They should replicate in both sides according to the documentation.

**Comment by poornas** [comment]
I understand that we are talking about active-active replication. However, replicating delete-marker set on replica back to source would lead to inonsistency - if source were also to set a delete marker concurrently, you will end up with 2 delete markers for the object when synced

**Comment by harshavardhana** [comment]
> I understand that we are talking about active-active replication. However, replicating delete-marker set on replica back to source would lead to inonsistency - if source were also to set a delete marker concurrently, you will end up with 2 delete markers for the object when synced

Based on let's close this issue as it is per design and we are keeping it this way as per our current design. 

> Maybe, MinIO team should finally stabilise file replication and replication of deleted-markers feature before publish the new release?
> Or, maybe you need to send pre release version to QA, that will check replication features next time?

Also please be mindful of our efforts here @pavel-z1 - we intend the best to give our community and these words don't sound very encouraging to our overall efforts.

if you are dependent on MinIO as a business you should definitely buy [subscription](https://min.io/pricing) that provides SLA - to build a more effective relationship between us.

**Comment by pavel-z1** [comment]
Hi @poornas 
>I understand that we are talking about active-active replication. However, replicating delete-marker set on replica back to source would lead to inonsistency - if source were also to set a delete marker concurrently, you will end up with 2 delete markers for the object when synced
If delete marker

I've tested delete-marker replication during last two months and now I totally confused. Feature and logic of delete-marker replication that I saw during last two months was changes without any notification from Minio developers.
Now you say, that previous operation logic was incorrect, and should be changed.
As a minio user, I'm disappointed. 

Can you please provide Minio documentation how application should work with file delete operation and Active-Active replications that had enabled replication of delete-marker features?

Application can use any of bucket in active-active mode, that lead to the situations, when different files can be initially created in the different buckets. As result, the source files placed on the different buckets.
In that case application don't know which bucket for the specific file is the source bucket.
How application should perform delete file operations in that case?

Also, it would be helpful for all Minio customers to get some documentation from Minio about delete-markers replication design and recommendation how users should use buckets with Active-Active replications and delete markers replications.

Thank you in advance for information.


@harshavardhana 
Over the past two months, I have seen persistent problems with replication features in new Minio releases. Almost every new release contains a critical issue with replication.
Despite the fact that you react promptly, the dynamics with bugs does not change, critical bugs continue to appear in each new release.

This wouldn't be a problem if you were tagging stable releases. However, as a user, I have no knowledge of which release has been tested and which has not.
As a result, I spend a huge amount of time testing each new release, hoping to get a minio with the declared functionality, without hidden critical bugs.

That is why I suggested that you take a closer look at the testing process before publishing the release.
Or, if you don’t have the ability to test, it would be a friendly step for the community to tag stable minio releases so that users can safely upgrade to the stable release, instead of thoroughly testing each new release, spending significant work time. 

>if you are dependent on MinIO as a business you should definitely buy subscription that provides SLA - to build a more effective relationship between us.

Based on current Minio release policy, and not encouraging answers in bug reports, I see no prospects and guarantees from Minio that for me the quality of the product will change after purchasing a subscription.

**Comment by pavel-z1** [comment]
Hi @poornas

>I understand that we are talking about active-active replication. However, replicating delete-marker set on replica back to source would lead to inonsistency - if source were also to set a delete marker concurrently, you will end up with 2 delete markers for the object when synced
If delete marker

I've tested delete-marker replication during last two months and now I totally confused. Feature and logic of delete-marker replication that I saw during last two months was changes without any notification from Minio developers.
Now you say, that previous operation logic was incorrect, and should be changed.
As a minio user, I'm disappointed.

Can you please provide Minio documentation how application should work with file delete operation and Active-Active replications that has enabled replication of delete-marker features?

Application can use any of bucket in active-active mode, that lead to the situations, when different files can be initially created in the different buckets. As result, the source files placed on the different buckets.
In that case application don't know which bucket for the specific file is the source bucket.
How application should perform delete file operations in that case?

Also, it would be helpful for all Minio customers to get some documentation from Minio about delete-markers replication design and recommendation how users should use buckets with Active-Active replications and delete markers replications.

Thank you in advance for information.

**Comment by poornas** [comment]
>Can you please provide Minio documentation how application should work with file delete operation and Active-Active replications that has enabled replication of delete-marker features?

@pavel-z1 , we will add to the documentation. Will also discuss with the engineering team further on the point you raised above.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/blob/master/docs/bucket/replication/DESIGN.md design document added and released as well..

**Comment by pavel-z1** [comment]
Thank you for help.
This solved a lot of problems for us.
