### ISSUE TITLE
Fix the gateway documents to document the additional ENV vars supported.

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#11526]
**Is your feature request related to a problem? Please describe.**
The documentation for minio Azure and AWS gateway modes implies that the minio credentials must be the same as the provider credentials.

**Describe the solution you'd like**
The documentation for the various gateways should document the additional environment variables supported, such as AWS_ACCESS_KEY, and how they act when combined with MINIO_ACCESS_KEY.

**Additional context**
I am not a technical writer and would make a hash of updating these pages myself.

**Comment by harshavardhana** [comment]
> The documentation for the various gateways should document the additional environment variables supported, such as AWS_ACCESS_KEY, and how they act when combined with MINIO_ACCESS_KEY.

- AWS S3 gateway already documents this https://github.com/minio/minio/blob/master/docs/gateway/s3.md#using-binary-in-ec2
- So does GCS https://github.com/minio/minio/blob/master/docs/gateway/gcs.md#12-run-minio-gcs-gateway-using-docker
- So does Azure https://github.com/minio/minio/blob/master/docs/gateway/azure.md#use-custom-accesssecret-keys
