### ISSUE TITLE
Add support for dynamic AWS credentials credentials (for the gateway feature)

### ISSUE THREAD

**Issue by iptizer** [minio/minio#11528]
**Is your feature request related to a problem? Please describe.**
    
- We are on premise, on a laptop or somewhere. Doesn't matter.
- We have a tool only accepting static AWS/S3 credentials.
- We have data in an AWS account, but **we can only issue temporary [AWS STS credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html)**.

So we would like our tool to access MinIO with static credentials and MinIO then "translating" to dynamic credentials.

**Describe the solution you'd like**

"Normal" AWS Credentials consist of `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY`.

STS generated keys have 3 variables. `AWS_SECRET_ACCESS_KEY`, `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_TOKEN`.

I currently don't see a way to start MinIO with these dynamic credentials.

Adding this feature would allow for the proposed gateway solution by handling the upgrade strategy with k8s power:

* On every new generated STS token a new MinIO instance is created.
* An ingress resource in front keeps old still active connections on the old MinIO, new conections are routed to the new MinIO instances.

This is a minimal solution. Going further, MinIO could be enabled to handle changing credentials. Maybe this is already possible using the etcd backend.

Also a/the MinIO Operator could take care of the generating the credentials, starting new MinIO instances, handling ingress resources, steering traffic.

**Describe alternatives you've considered**
Not really possible.

**Comment by harshavardhana** [comment]
This is already supported if the domain is s3.amazonaws.com 

https://github.com/minio/minio/blob/master/cmd/gateway/s3/gateway-s3.go#L152 

Multiple mechanisms are supported @iptizer 

Documentation here https://github.com/minio/minio/blob/master/docs/gateway/s3.md#using-binary-in-ec2

Beyond this gateway's are not taking anymore feature requests, it's in code freeze.
