### ISSUE TITLE
[not a bug] Minio. The s3 api doesn't work

### ISSUE THREAD

**Issue by Gashir** [minio/minio#11533]
## Expected behavior
Operation of the s3.putObject, s3.ListObjectsV2 methods in the minio cluster in fault tolerance mode. 

## Current Behavior
The s3 api doesn't work. When testing a minio cluster consisting of 6 nodes, problems arise when using the s3 api methods s3.putObject, s3.ListObjectsV2 - at the moment when we turn off 1 or 2 nodes from the cluster, when we return a full cluster of 6 nodes, the problems of the s3 api disappear. 

## Steps to reproduce (for errors)

 logs

1.[503 Service Unavailable] s3.PutObject s3.work.ru/tariff-test/load.tariff/09.02.2021/ivanov.dd/2.xlsx src ip        12.068296s
2.[500 Internal Server Error] s3.ListObjectsV2 s3.work.ru/1cdocmng-test?list-type=2&prefix=DOC6&continuation-token=RE2ODFjMTI4YjE1XQ%3D%3D...  src ip

## environment

* Version used ('minio --version`): minio version RELEASE.2021-02-11T08-23-43Z
* Server configuration and configuration:
 $ cat /etc/default/minio
MINIO_VOLUMES="/minio/data{1...2}/"
MINIO_OPTS="--address '192.168.4.44:9000' http://192.168.4.{44...45}/minio/data{1...2} http://192.168.4.{46...47}/minio/data{1...2} http://192.168.4.{48...49}/minio/data{1...2}"
MINIO_ACCESS_KEY="*******"
MINIO_SECRET_KEY="********"
MINIO_PROMETHEUS_AUTH_TYPE="public"
* Operating system and version ('uname -a`):
 Oracle Linux Server 8.3  5.4.17-2036.101.2.el8uek.x86_64

**Comment by harshavardhana** [comment]
> * MINIO_OPTS="--address '192.168.4.44:9000' [http://192.168.4.{44...45}/minio/data{1...2}](http://192.168.4.%7B44...45%7D/minio/data%7B1...2%7D) [http://192.168.4.{46...47}/minio/data{1...2}](http://192.168.4.%7B46...47%7D/minio/data%7B1...2%7D) [http://192.168.4.{48...49}/minio/data{1...2}](http://192.168.4.%7B48...49%7D/minio/data%7B1...2%7D)"

This is an incorrect way to setup MinIO you should deploy it as a single pool otherwise each pool can only tolerate only itself i.e each args tolerate only its own entity. 

Taking down nodes will break things at that point. Write the server as a single command line setup such as 

```
MINIO_OPTS="--address '192.168.4.44:9000' [http://192.168.4.{44...49}/minio/data{1...2}
```

It shall tolerate how you expect.

**Comment by Gashir** [comment]
Thank you for your help, we rebuilt the cluster and everything worked! Another question, we tested fault tolerance, and when we turn off the nodes from the cluster and turn them back on, the data is not synchronized, the mc admin heal minio command helps, but it issued a warning "MinIO server now supports auto-heal, this command will be removed in future."  Please explain how it will work "auto-heal" ?

**Comment by harshavardhana** [comment]
> Thank you for your help, we rebuilt the cluster and everything worked! Another question, we tested fault tolerance, and when we turn off the nodes from the cluster and turn them back on, the data is not synchronized, the mc admin heal minio command helps, but it issued a warning "MinIO server now supports auto-heal, this command will be removed in future." Please explain how it will work "auto-heal" ?

auto-heal automatically runs all the time - it is dependent on the crawler cycle @Gashir

**Comment by klauspost** [comment]
@Gashir Is you want more details, we can assist you directly here: https://min.io/pricing
