### ISSUE TITLE
make error while building from source 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1153]
make fails on systems where gpg is not installed. (currently failed on El captain OSX) 
<img width="926" alt="screen shot 2016-02-22 at 3 56 02 pm" src="https://cloud.githubusercontent.com/assets/2609511/13215631/d5e58522-d97c-11e5-9677-fbd870f0d1be.png">

**Comment by harshavardhana** [comment]
This is expected 'gpg' is a requirement, this will be removed after ui-asset vendorization @hackintoshrao

**Comment by harshavardhana** [comment]
Closing, gpg dependency will be removed after asset vendorization, for the time being it is required to verify signature of assets downloaded from dl.minio.io
