### ISSUE TITLE
Grafana new metrics support

### ISSUE THREAD

**Issue by DaniilNikolaevich** [minio/minio#11543]
On 2nd of February, you committed new cluster metrics (commit c4848f9 https://github.com/minio/minio/tree/master/docs/metrics/prometheus). 

You provided new metrics in `list.md`, but did not push new `minio-overview.json` in `grafana` directory. The current version of that json does not work properly with new metrics. As a result, i have no ability to use grafana dashboard.

Would you please update that json, so the community can use your metrics?

**Comment by coltmister** [comment]
+1 This would be awesome.

**Comment by DaniilNikolaevich** [comment]
Hello guys, how it's going on?)

**Comment by tkg61** [comment]
I was able to modify the existing json file to work (mostly) with the new metrics. More or less just a find and replace for the prometheus metric names and 2 variables in the dashboard. Hope that helps someone who needs this quickly

**Comment by aldelsa** [comment]
I tried to fix it, but there are missing metrics like bucket_objects_histogram. I waiting a official dashboard too.

**Comment by nitisht** [comment]
New dashboard also available on https://grafana.com/grafana/dashboards/13502
