### ISSUE TITLE
Minio not starting in distributed mode from a service descriptor file

### ISSUE THREAD

**Issue by AlexNisulescu** [minio/minio#11540]
**Here is my minio conf file:**

MINIO_OPTS="http://minio-{1...4}:9000/data"
MINIO_ACCESS_KEY="myminio"
MINIO_SECRET_KEY="myminioserver"

**And here is the service file:**

[Unit]
Description=minio
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/
User=root
Group=root
EnvironmentFile=/etc/default/minio
ExecStart=/usr/local/bin/minio server \$MINIO_OPTS
Restart=always
LimitNOFILE=65536
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

Whenever I start the server using systemctl start minio.service there is only one server started in standalone mode and they are not comunicating. If anyone can help me I would be grateful. Thanks.

**Comment by harshavardhana** [comment]
> MINIO_OPTS="[http://minio-{1...4}:9000/data](http://minio-%7B1...4%7D:9000/data)"

I don't know where you got this from it is clearly mentioned https://github.com/minio/minio-service/tree/master/linux-systemd/distributed 

```
MINIO_VOLUMES=...
```

Just follow our docs properly

**Comment by AlexNisulescu** [comment]
Now I see. I couldn't find the documentation for the systemd script, but I got it now. Thanks a lot.
