### ISSUE TITLE
Python API list_objects call AccessDenied unless s3:GetBucketLocation is set 

### ISSUE THREAD

**Issue by vonera** [minio/minio#11541]
the following policy is not sufficient to list objects using the python API
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:GetObjectVersion"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}
```
However using **mc** works as expected.
```
mc ls nio_alice/mybucket
[2021-02-16 13:12:43 CET] 135KiB file.png
```

## Expected Behavior
lists the contents

## Current Behavior
throws AccessDenied

## Steps to Reproduce (for bugs)
run the latest minio docker image 

```bash
brew install minio/stable/mc
mc alias set nio http://127.0.0.1:9000 nio_admin nio_admin

mc mb nio/mybucket
mc cp file.png nio/mybucket/


mc admin user add nio alice alice123
mc alias set nio_alice http://127.0.0.1:9000 alice alice123
```

```json
cat > rw_mybucket.json << EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:GetObjectVersion"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}
EOF
```

```
mc admin policy add nio rwMybucket rw_mybucket.json
mc admin policy set nio rwMybucket user=alice

mc ls nio_alice/mybucket
[2021-02-16 13:12:43 CET] 135KiB file.png 
```
----------------- in python 

``` python
from minio import Minio
from minio.error import S3Error
client = Minio(
    "127.0.0.1:9000",
    access_key="alice",
    secret_key="alice123",
    secure = False,
)
objects = client.list_objects("mybucket")
for obj in objects:
    print(obj.object_name)
```
>>> S3Error: S3 operation failed; code: AccessDenied, message: Access Denied., resource: /mybucket, request_id: 16643BAC4D44D1E4, host_id: 9df8db5c-fe20-473e-95fb-08b7146ebc63, bucket_name: mybucket

If I add **s3:GetBucketLocation** to the Policy it works

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-02-14T04-01-33Z
*  mc --version: mc version RELEASE.2021-01-30T00-50-42Z
* Operating System and version (`uname -a`): latest docker image on Darwin MacBook-Pro-2.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

**Comment by vadmeste** [comment]
@vonera any API won't work if it doesn't know the location of the bucket, it would result to signature mismatch error. You really need to allow GetBucketLocation permission here.

**Comment by vonera** [comment]
Probably u are right, 
the problem is: it is kind of not obvious, specially as mc seams to work without it.

**Comment by vadmeste** [comment]
> Probably u are right,
> the problem is: it is kind of not obvious, specially as mc seams to work without it.

I see. mc is able to find a way if it is not able to get the bucket location but this is really penalizing because it means mc will always communicate with AWS servers in US East 1 and not with the servers where your data are actually stored.

**Comment by balamurugana** [comment]
@vonera You would need to pass `region` argument to `Minio` constructor in `minio-py` to avoid calling `GetBucketLocation` S3 API; otherwise you would need to enable `s3:GetBucketLocation` in your policy at server side.

**Comment by vonera** [comment]
thanks 2 all for clarification, maybe it is worth mentioning in the documentation.

**Comment by harshavardhana** [comment]
> @vonera You would need to pass `region` argument to `Minio` constructor in `minio-py` to avoid calling `GetBucketLocation` S3 API; otherwise you would need to enable `s3:GetBucketLocation` in your policy at server side.

Closing this issue.
