### ISSUE TITLE
multiple make error OSX El captain 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1154]
1. yasm error
2. GPG error 
   
   gpg: requesting key F9AAC728 from hkp server pgp.mit.edu
   gpg: no valid OpenPGP data found.
   gpg: Total number processed: 0
   gpg: keyserver communications error: keyserver helper general error
   gpg: keyserver communications error: unknown pubkey algorithm
   gpg: keyserver receive failed: unknown pubkey algorithm
   make: **\* [ui-assets.go] Error 2

**Comment by harshavardhana** [comment]
> yasm error

Yasm is required for Erasure code library compilation, 

> gpg: requesting key F9AAC728 from hkp server pgp.mit.edu
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> gpg: keyserver communications error: keyserver helper general error
> gpg: keyserver communications error: unknown pubkey algorithm
> gpg: keyserver receive failed: unknown pubkey algorithm
> make: **\* [ui-assets.go] Error 2

This seems like a network error to fetch the public key from pgp.mit.edu.

**Comment by harshavardhana** [comment]
> yasm error

@hackintoshrao additionally can you please describe this error? - i do not know what to make of 'yasm error' ?

**Comment by hackintoshrao** [comment]
<img width="866" alt="screen shot 2016-02-22 at 4 35 41 pm" src="https://cloud.githubusercontent.com/assets/2609511/13216541/5c0496ac-d982-11e5-932a-25f7bc2a6382.png"> 
Yes, It was obvious issue of yasm not installed, but can the experience be made simpler for building from make by automating the yasm installation.

**Comment by harshavardhana** [comment]
> Yes, It was obvious issue of yasm not installed, but can the experience be made simpler for building from make by automating the yasm installation.

Yasm should have been detected by the checkdeps.sh and complianed. It doesn't make sense to install yasm by ourselves. 

I think the recent merge from minio-xl missed a change to verify this in checkdeps.sh - https://github.com/minio/attic/blob/master/minio-xl/buildscripts/checkdeps.sh#L25.

**Comment by hackintoshrao** [comment]
Yes, that's right. May be a graceful install command could have made experience easier.
