### ISSUE TITLE
Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by ashishdocforce** [minio/minio#11554]
I was using this doc to install minio on my ubuntu 20 server: https://linuxhint.com/installing_minio_ubuntu/

When i reached to the step 3 to check minio server, I get this error in terminal:

```
./minio: 1: Syntax error: Unterminated quoted string
```

**Comment by harshavardhana** [comment]
Not sure what you are saying, please follow our docs @ashishdocforce

**Comment by ashishdocforce** [comment]
> Not sure what you are saying, please follow our docs @ashishdocforce

I get this type of error from minio for the first time. I have set it up before this server and it worked well. I followed below steps,

1). Download an installation file:
```
wget https://dl.minio.io/server/minio/release/linux-amd64/minio
```
2). Give file permission:
```
chmod +x minio
```
3). Trying to run minio server:
```
sudo ./minio server /minio
```
I get this error on this third step:

`Syntax error: Unterminated quoted string`

Hope you understand my point now.

**Comment by ashishdocforce** [comment]
> > Not sure what you are saying, please follow our docs @ashishdocforce
> 
> I get this type of error from minio for the first time. I have installed it before this server and it worked well. I followed below steps,
> 
> 1). Download an installation file:
> 
> ```
> wget https://dl.minio.io/server/minio/release/linux-amd64/minio
> ```
> 
> 2). Give file permission:
> 
> ```
> chmod +x minio
> ```
> 
> 3). Trying to run minio server:
> 
> ```
> sudo ./minio server /minio
> ```
> 
> I get this error on this third step:
> 
> `Syntax error: Unterminated quoted string`
> 
> Hope you understand my point now.

**Comment by ashishdocforce** [comment]
>  Not sure what you are saying, please follow our docs @ashishdocforce

@harshavardhana I get this type of error from minio for the first time. I have installed it before this server and it worked well. I followed below steps,
 1). Download an installation file:
 ```
 wget https://dl.minio.io/server/minio/release/linux-amd64/minio
```


 2). Give file permission:
 ```
 chmod +x minio
```


3). Trying to run minio server:
 ```
 sudo ./minio server /minio
```


I get this error on this third step:
 `Syntax error: Unterminated quoted string`
Hope you understand my point now.

**Comment by harshavardhana** [comment]
```
~ wget https://dl.minio.io/server/minio/release/linux-amd64/minio
--2021-02-17 00:12:24--  https://dl.minio.io/server/minio/release/linux-amd64/minio
Resolving dl.minio.io (dl.minio.io)... 178.128.69.202
Connecting to dl.minio.io (dl.minio.io)|178.128.69.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51683328 (49M) [application/octet-stream]
Saving to: ‘minio’

minio                                           100%[=====================================================================================================>]  49.29M  22.1MB/s    in 2.2s    

2021-02-17 00:12:26 (22.1 MB/s) - ‘minio’ saved [51683328/51683328]
```
```
~ chmod +x minio
```
```
~ ./minio server /tmp/fs
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint: https://10.0.0.67:9000  https://172.17.0.1:9000  https://172.18.0.1:9000  https://127.0.0.1:9000               
RootUser: minio 
RootPass: minio123 

Browser Access:
   https://10.0.0.67:9000  https://172.17.0.1:9000  https://172.18.0.1:9000  https://127.0.0.1:9000              

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio https://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

Certificate:
    Signature Algorithm: SHA256-RSA
    Issuer: O=mkcert development CA, OU=harsha@prtsc, CN=mkcert harsha@prtsc
    Validity
        Not Before: Fri, 11 Dec 2020 00:46:00 GMT
        Not After : Wed, 11 Dec 2030 00:46:00 GMT
```

**Comment by ashishdocforce** [comment]
@harshavardhana Can it be my ubuntu version? I do have ubuntu 20. and that is where it is causing an issue. Lot's of installation needs changes to ubuntu 20. did you tested it on ubuntu 20?
