### ISSUE TITLE
Release roadmap for Minio?

### ISSUE THREAD

**Issue by MichaelKim0407** [minio/minio#11553]
Is there a release roadmap for minio? The current timestamp-based versioning is not very helpful for understanding the scope of releases, when things may break, when an update is needed, etc. A roadmap (or a change in the versioning scheme) can help us understand when to update/ what to update to.

We are currently using docker images for minio server.

**Comment by klauspost** [comment]
Releases are documented on the releases page: https://github.com/minio/minio/releases

If you need more guided updates look into our support options: https://min.io/pricing

**Comment by MichaelKim0407** [comment]
That was not helpful at all...

I have read both pages before posting the question. My issue is, as a developer that uses minio, there is no way to understand your release intentions, on top of the timestamp-based versioning.

For example, I can use Python 3.7 or Postgres 11 with the understanding that I can always update to the latest version to get bug/security fixes and my code won't break. I can't do that with minio, and I'm forced to choose among not getting security fixes, risking that my code may break, or keep reading the release page which is 99% irrelevant to me. This is very developer-unfriendly.

Obviously you are using the timestamp-based versioning for some reason and you can't change it overnight, providing a roadmap for future releases, at least the near future, can help a lot.

**Comment by klauspost** [comment]
@MichaelKim0407 We offer guided updates as part of the subscription.

We don't release any breaking changes. We strive to make a clean upgrade path.
