### ISSUE TITLE
Server does not respect MINIO_STORAGE_CLASS_STANDARD and MINIO_STORAGE_CLASS_RRS env variables

### ISSUE THREAD

**Issue by aleksanderlech** [minio/minio#11557]
Server does not respect **MINIO_STORAGE_CLASS_STANDARD** and **MINIO_STORAGE_CLASS_RRS** env variables or at least there is some inconsistency between the server and the client when reading the current storage classes.

## Expected Behavior
If I run the server with **MINIO_STORAGE_CLASS_STANDARD** and **MINIO_STORAGE_CLASS_RRS** environment variables set I would expect that the mc admin config value for the `storage_class` key would be updated properly.

## Current Behavior
Assume the following env present:

`MINIO_STORAGE_CLASS_STANDARD="EC:4"
MINIO_STORAGE_CLASS_RRS="EC:3"`

After the server is started the client asked for the storage classes is still returning the builtin defaults:

`
$ mc admin config get <<alias>> storage_class
   storage_class standard= rrs=EC:2 dma=read+write
`

## Steps to Reproduce (for bugs)

Run the Minio server as follows:

`$ docker run -p 9000:9000 -e MINIO_STORAGE_CLASS_STANDARD=EC:4 -e MINIO_STORAGE_CLASS_RRS=EC:3 minio/minio:edge server /data/disk{1..16}`

Setup the Minio client alias:

`$ minio-client alias set local http://localhost:9000 minioadmin minioadmin --api s3v4`

Read the storage_class value:

`$ mc admin config get local storage_class`

Notice that the value returned is still the built in default:

`storage_class standard= rrs=EC:2 dma=read+write`

## Context
I am trying to override the default standard and reduced storage classes for my Minio cluster.

## Your Environment
* Version: RELEASE.2021-02-14T04-01-33Z
* Server setup and configuration: (for instance http://192.168.62.19{0...3}/mnt/disk{1...4})
* Operating System and version: Linux host 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> If I run the server with **MINIO_STORAGE_CLASS_STANDARD** and **MINIO_STORAGE_CLASS_RRS** environment variables set I would expect that the mc admin config value for the `storage_class` key would be updated properly.

env values are not displayed as part of `mc admin config get alias/ storage_class` - `mc admin config` is only when you set the values from `mc admin config set` command are persisted.

Environment values override config values and are not retrieved from `mc admin config get`

**Comment by aleksanderlech** [comment]
Thank you for the fast clarification. I would say it's at least confusing and I did not see any documented way allowing us to check the current storage classes setup in the cluster.

**Comment by harshavardhana** [comment]
> Thank you for the fast clarification. I would say it's at least confusing and I did not see any documented way allowing us to check the current storage classes setup in the cluster.

You can see it with `mc admin info --json` @aleksanderlech
