### ISSUE TITLE
File in status Replication Status: PENDING a long of time

### ISSUE THREAD

**Issue by pavel-z1** [minio/minio#11555]
I have minio in different location with ACTIVE-ACTIVE buckets replication. Two regions: rot01 and ams01.
File uploaded to the rot01 bucket 16 hours ago still has status `Replication Status: PENDING`:
```
# mc stat local/prd-data-old/tmp_cr_files/ff2ed8e4-6ee0-11eb-a2d8-3fca3d2ea2ee/bdbef36875daabd477e2cd37bc85d022/c0afbaf866ea06ce6a1a90f015904aa340168a6c_0.wav
Name      : c0afbaf866ea06ce6a1a90f015904aa340168a6c_0.wav
Date      : 2021-02-14 17:25:29 CET
Size      : 1.2 MiB
ETag      : 6124f640986056befc4163e677196186
VersionID : 9ca3cf99-3fa7-4453-a860-350895497bb6
Type      : file
Metadata  :
  Content-Type       : audio/x-wav
  X-Amz-Meta-Mc-Attrs: atime:1613319929#0/gid:0/gname:root/mode:33188/mtime:1613319929#0/uid:0/uname:root
Replication Status: PENDING
```

But, when i create the new file in the same directory it replicate correctly without delay:
```
# mc stat local/prd-data-old/tmp_cr_files/ff2ed8e4-6ee0-11eb-a2d8-3fca3d2ea2ee/bdbef36875daabd477e2cd37bc85d022/test3.jpeg
Name      : test3.jpeg
Date      : 2021-02-17 08:55:40 CET
Size      : 301 KiB
ETag      : ff2116dad429974ffe0fd92156e3c899
VersionID : 879b8be2-dcc5-4b27-80ed-89fc243d537b
Type      : file
Metadata  :
  Content-Type: image/jpeg
Replication Status: COMPLETED
```

## Expected Behavior
Expect replication without delay

## Current Behavior
```
# mc stat local/prd-data-old/tmp_cr_files/ff2ed8e4-6ee0-11eb-a2d8-3fca3d2ea2ee/bdbef36875daabd477e2cd37bc85d022/c0afbaf866ea06ce6a1a90f015904aa340168a6c_0.wav
Name      : c0afbaf866ea06ce6a1a90f015904aa340168a6c_0.wav
Date      : 2021-02-14 17:25:29 CET
Size      : 1.2 MiB
ETag      : 6124f640986056befc4163e677196186
VersionID : 9ca3cf99-3fa7-4453-a860-350895497bb6
Type      : file
Metadata  :
  Content-Type       : audio/x-wav
  X-Amz-Meta-Mc-Attrs: atime:1613319929#0/gid:0/gname:root/mode:33188/mtime:1613319929#0/uid:0/uname:root
Replication Status: PENDING
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Not clear at this time how to reproduce.
Need information how to debug this issue.

Such trace during 1 hour don't return any information:
```
mc admin trace -v --path '/prd-data-old/tmp_cr_files/ff2ed8e4-6ee0-11eb-a2d8-3fca3d2ea2ee/bdbef36875daabd477e2cd37bc85d022/c0afbaf866ea06ce6a1a90f015904aa340168a6c_0.wav' local
```

## Regression
Not sure

## Your Environment
minio RELEASE.2021-02-14T04-01-33Z
Inside docker container:
```
# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                       PORTS               NAMES
4eb0a6107fd7        minio/minio:RELEASE.2021-02-14T04-01-33Z   "/usr/bin/docker-ent…"   2 days ago          Up About an hour (healthy)                       minio_server
```
CentOS Linux release 8.2.2004 (Core)
```
# uname -a
Linux prd-objstor-minio-06.live.ams01.kwebbl.cloud 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Minio info:
```
962 GiB Used, 15 Buckets, 1,709,385 Objects
4 drives online, 0 drives offline
```

**Comment by klauspost** [comment]
Pending files are uploaded as they are seen during crawl. 

Crawling speed depends on the cluster load and the number of objects as well as storage speed.

You can speed up the crawler with `mc admin config set myminio crawler delay=1` which will allow it to use 10x resources.

**Comment by pavel-z1** [comment]
Enabled:
```
# mc admin config set local crawler delay=1
Successfully applied new settings.
```
Waiting

**Comment by poornas** [comment]
Can you also share output of `mc admin top locks local` if replication is still not caught up.

**Comment by pavel-z1** [comment]
During 4 hours after enabling `crawler delay=1` files were replicated.

But reason why files initially have not been replicated is not clear.
There was no problem with remote minio cluster and no network issues. `mc mirror` copied file to the source region without replication.

Current state:
New files replicated without delay.
Mass upload to the source region with replication to the remote region work correctly too.

Can't replicate issue at this moment.

@poornas can you advice, how to perform force replication specific files or directories without reupload? If in production environment issue will occur agin we will need to replicate asap, in production there is no way to wait for crawler.

**Comment by klauspost** [comment]
@pavel-z1 If the replication fails when the object is uploaded it will be marked pending and will eventually be picked up by the crawler. This is how it is designed.

It can fail for any number of reason, most likely network error at the remote. Your logs may contain hints to the failure.
