### ISSUE TITLE
`2021-02-07T01:31:02Z` takes more time to respond to madmin

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#11564]
`2021-02-07T01:31:02Z` takes more time to response to madmin's `AccountInfo` than `2020-10-18T21:54:12Z`.

## Your Environment
Federation with 1 cluster (2 nodes) and etcd. I switch cluster for testing purposes; they have different MinIO version.
I created 150 users / buckets: each user has one bucket.

First cluster:

```
●  minio1.storage.tresorio.com:9000
   Uptime: 15 minutes
   Version: 2021-02-07T01:31:02Z
   Network: 2/2 OK
   Drives: 4/4 OK

●  minio0.storage.tresorio.com:9000
   Uptime: 15 minutes
   Version: 2021-02-07T01:31:02Z
   Network: 2/2 OK
   Drives: 4/4 OK

0 B Used, 150 Buckets, 0 Objects
8 drives online, 0 drives offline
```

response time:

```
32.781488ms
43.418544ms
29.62823ms
28.299496ms
27.111348ms
32.385505ms
28.158128ms
```

Second cluster:

```
●  minio1.storage.tresorio.com:9000
   Uptime: 7 minutes
   Version: 2020-10-18T21:54:12Z
   Network: 2/2 OK
   Drives: 4/4 OK

●  minio0.storage.tresorio.com:9000
   Uptime: 7 minutes
   Version: 2020-10-18T21:54:12Z
   Network: 2/2 OK
   Drives: 4/4 OK

0 B Used, 2 Buckets, 0 Objects
8 drives online, 0 drives offline
```

```
19.043887ms
19.678051ms
21.128289ms
19.984566ms
21.164285ms
19.061604ms
```

It's a regression compared to `2020-10-18T21:54:12Z`. What's the the cause of this regression ?

Thanks.

**Comment by ToLToL** [comment]
Maybe because it has `Policy` now:

`2021-02-07T01:31:02Z`:
```
type AccountInfo struct {
	AccountName string
	Policy      iampolicy.Policy
	Buckets     []BucketUsageInfo
}
```

`2020-10-18T21:54:12Z`:
```
type AccountUsageInfo struct {
	AccountName string
	Buckets     []BucketUsageInfo
}
```

**Comment by harshavardhana** [comment]
We add extra information so it is expected 

> 32.781488ms
> 43.418544ms
> 29.62823ms
> 28.299496ms
> 27.111348ms
> 32.385505ms
> 28.158128ms

Also this change is marginal for all things considered. I don't think this is a bug.

**Comment by ToLToL** [comment]
Ok thanks

**Comment by ToLToL** [comment]
`client.MakeBucket()` and `client.RemoveBucket()` from `2021-02-07T01:31:02Z` take 5x more time than `2020-10-18T21:54:12Z`.

**Comment by ToLToL** [comment]
One more thing, I have a method that creates a bucket, change canned policy and set the policy to the user. 
It takes 10x more time on `2021-02-07T01:31:02Z` compared to `2020-10-18T21:54:12Z` (200 ms vs ~ 2, 2 seconds).

I found that it mainly comes from `adminClient.AddCannedPolicy()`.

**Comment by ToLToL** [comment]
@harshavardhana

The only difference in `adminClient.AddCannedPolicy()` (admin-hanlders-users.go) is: 

```go
defer logger.AuditLog(ctx, w, r, mustGetClaimsFromToken(r))
```

I did a [diff checker for the 2 versions](https://www.diffchecker.com/PuCwmtkT).

**Comment by ToLToL** [comment]
I didn't configure any weebhook:

```
➜  mc admin config get local-c-02 logger_webhook
logger_webhook enable=off endpoint= auth_token=
➜  mc admin config get local-c-02 audit_webhook
audit_webhook enable=off endpoint= auth_token=
```

So it should exit immediately right ?:

```go
func AuditLog(ctx context.Context, w http.ResponseWriter, r *http.Request, reqClaims map[string]interface{}, filterKeys ...string) {
  // Fast exit if there is not audit target configured
    if len(AuditTargets) == 0 {
       return
    }
  ...
}
```

**Comment by klauspost** [comment]
@ToLToL The version jump is too large to make much difference and the code you listed doesn't appear to have any significant changes.

Also, it seems to be within reasonable limits. You are of course welcome to continue your investigation, but it isn't something that warrants an extensive investigation.

**Comment by ToLToL** [comment]
I'd like to upgrade MinIO but it's very annoying to have 10x response time.

It would be nice if you could  check the cause in `AddCannedPolicy()` since `2020-10-18T21:54:12Z`.
Thanks.
