### ISSUE TITLE
logging: Easier error message 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1156]
The error message displayed when minio server is started in a non-existent directory seems to be complicated and needs a lot of cognitive load for a common end user to decipher and understand. May be the debug message could be kept out and just a simple message stating the directory doesn't exist would make more sense for a 12 year old using minio. What do you think? @abperiasamy  @harshavardhana 
<img width="1274" alt="screen shot 2016-02-22 at 9 22 49 pm" src="https://cloud.githubusercontent.com/assets/2609511/13223501/74bdc0c4-d9aa-11e5-91f4-561f364d59c7.png">

**Comment by harshavardhana** [comment]
Currently all the logs are JSON formatted. It is meant to be on purpose so that the output is parsable.

**Comment by harshavardhana** [comment]
But I think for console printing we don't need JSON which will be fixed with the new config changes. Where as file, syslog and mongo logger are all formatted

**Comment by harshavardhana** [comment]
This is handled at #1123

**Comment by hackintoshrao** [comment]
:+1:
