### ISSUE TITLE
Max Limit in MInio Lifecycle Policy.

### ISSUE THREAD

**Issue by mohandass-pat** [minio/minio#11573]
In our product, we are planning to give 1 bucket for 1 user. In every bucket under /trash prefix, we want to delete the objects older than 30 days. We are achieving this with the Minio Lifecycle policy rule. So, if there are 1000 users we need to set 1000 lifecycle policy rules. But currently, Minio is not allowing to set more than 1000 lifecycle rules. So if the user count grows the policy rule count also will increase. How to handle this?

**Comment by nitisht** [comment]
Please use Slack for questions and Issue templates for GitHub (for issues / feature requests)

Thanks in advance. Closing this issue.
