### ISSUE TITLE
Error from PutBucketHandler while using POSTMan for S3 compatibility 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1157]
While using POSTMAN's built in functionality to generate headers for S3 authentication it seems like a non-supportive header is generated. The screenshots reveal more. 

<img width="721" alt="screen shot 2016-02-22 at 10 13 37 pm" src="https://cloud.githubusercontent.com/assets/2609511/13225226/efa6b4ce-d9b1-11e5-8fec-6040dfc33cc2.png">
<img width="895" alt="screen shot 2016-02-22 at 10 14 05 pm" src="https://cloud.githubusercontent.com/assets/2609511/13225225/efa5a26e-d9b1-11e5-98dc-a8e747cfe4d5.png">

Checking from the code about what went wrong and which are the allowed ACL/headers for the subset of functionality provided by Minio and will be setting right headers from POSTMAN and then I'll match the compatibility with S3 . Please assign this to me. @abperiasamy  @harshavardhana . Opening the issue just as a tracker.

**Comment by hackintoshrao** [comment]
looks like x-amz-acl is missing. But not sure form the S3 docs that this mandatory, if not there is a compatibility mismatch, will confirm, again please assign this to me.

**Comment by harshavardhana** [comment]
X-amz-acl is not mandatory.

**Comment by hackintoshrao** [comment]
Since the virtual format needs DNS implementation BucketName.s3.amazonaws.com format of creating bucket is not implemented by Minio. Hence closing the issue.

**Comment by cvvs** [comment]
So you don't support bucketname.domain.tld in minio for buckets?

**Comment by harshavardhana** [comment]
> So you don't support bucketname.domain.tld in minio for buckets?

No we don't

**Comment by cvvs** [comment]
Unfortunate.

**Comment by harshavardhana** [comment]
> Unfortunate

It is possible to make it work but requires another DNS service as well along with Minio, we decided that it is not worth complicating Minio server deployment for this purpose alone.

**Comment by cvvs** [comment]
I'm not familiar with any org who doesn't use DNS, but it's your call.
Thanks for the response.
