### ISSUE TITLE
Existing files cannot be deleted or replaced

### ISSUE THREAD

**Issue by onestudy** [minio/minio#11571]
Several files cannot be deleted or replaced. Most of the files operate normally.

Existing files cannot be deleted through Minio's Web site
Existing files cannot be deleted by using the `./mc rm --force minio1/a/a.json` command
Prompt operation timeout.

Is there any way to safely delete this file?

**Comment by harshavardhana** [comment]
You should explain your setup in more detail, by removing the entire issue reporting template we cannot help you.
