### ISSUE TITLE
test: Write postman/newman collection tests

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1158]
bucket-handlers.go doesn't seem to have tests and benchmarks. Just want to confirm it before starting to write them. And if they don't exist please assign it to me I'm on it. @abperiasamy  @harshavardhana

**Comment by harshavardhana** [comment]
All the handlers are tested in server_fs_test.go by instantiating a http test server. See what else is missing there.

**Comment by harshavardhana** [comment]
Testing using postman is blocked until - https://github.com/mhart/aws4/pull/21

**Comment by hackintoshrao** [comment]
Unable to proceed because of https://github.com/postmanlabs/newman/issues/335

**Comment by hackintoshrao** [comment]
Both the above issues are solved, moving ahead.

**Comment by hackintoshrao** [comment]
Encountered a bug during bucket creation using POSTMAN, here is the bug description https://medium.com/@hackintoshrao/33fba33470ed .

**Comment by harshavardhana** [comment]
Closing this as we have moved on to our own tests.
