### ISSUE TITLE
Configure sending notifications from a third-party module.

### ISSUE THREAD

**Issue by tifling85** [minio/minio#11588]
**Is your feature request related to a problem? Please describe.**
I am trying to write a Python module that will set up sending notifications to webhook. I found a method to add bucket event (client.set_bucket_notification), but i can't find a method to set notify_webhook (alternative for 'mc admin config set myminio notify_webhook:1'). Is there a way to do it?

**Describe the solution you'd like**
Configure sending notifications from a third-party module.

**Describe alternatives you've considered**

**Additional context**
Thanks!

**Comment by harshavardhana** [comment]
> **Is your feature request related to a problem? Please describe.**
> I am trying to write a Python module that will set up sending notifications to webhook. I found a method to add bucket event (client.set_bucket_notification), but i can't find a method to set notify_webhook (alternative for 'mc admin config set myminio notify_webhook:1'). Is there a way to do it?
> 
> **Describe the solution you'd like**
> Configure sending notifications from a third-party module.
> 
> **Describe alternatives you've considered**
> 
> **Additional context**
> Thanks!

You enable notification on the bucket and server sends notification to your endpoint that is configured on server.

You should look at our docs properly to understand what is bucket notification used for.

There is no code that you need to write to send notifications. You are only writing code for the receiving end.

**Comment by tifling85** [comment]
> You enable notification on the bucket and server sends notification to your endpoint that is configured on server.

endpoint is only configurable from minio client or environment variables on server?

> There is no code that you need to write to send notifications. You are only writing code for the receiving end.

I'm trying to write code to enable sending notifications on the minio for the receiving end.

Thanks!

**Comment by harshavardhana** [comment]
> > You enable notification on the bucket and server sends notification to your endpoint that is configured on server.
> 
> endpoint is only configurable from minio client or environment variables on server?
> 
> > There is no code that you need to write to send notifications. You are only writing code for the receiving end.
> 
> I'm trying to write code to enable sending notifications on the minio for the receiving end.
> 
> Thanks!

https://github.com/minio/minio/tree/master/pkg/madmin

Look at this..
