### ISSUE TITLE
Uploading files is very slow.  LAN, 600k files, upload takes about 1 minute

### ISSUE THREAD

**Issue by onestudy** [minio/minio#11589]
Use the latest version of Minio(2021-02-14). 
Operating system centos8. 
Service startup script:
``` shell
/data/minio/run/minio server --config-dir /data/minio/etc \
http://10.3.77.99/data/minio/data \
http://10.3.77.100/data/minio/data \
http://10.3.77.101/data/minio/data \
http://10.3.77.102/data/minio/data
```
Uploading files is very slow. In LAN, a 600k files, upload takes about 1 minute

**Comment by harshavardhana** [comment]
There is nothing in the issue description to help you - the entire issue template is empty without and valid reproducer.  Closing this as incomplete info.
