### ISSUE TITLE
failed to ennable dma="read+write" by mc

### ISSUE THREAD

**Issue by sirizhou** [minio/minio#11599]
## Expected Behavior
```shell
intel@sm150:~$ mc admin config set myminio/ storage_class dma="read+write"
Successfully applied new settings.Please restart your server with `
mc admin service restart myminio/`.
```

## Current Behavior
```shell
intel@sm150:~$ mc admin config set myminio/ storage_class dma="read+write"
mc: <ERROR> Unable to set 'storage_class dma=read+write' to server: sub-system 'storage_class' cannot have empty keys.
```

## Steps to Reproduce (for bugs)

```shell
minio server ~/siri/optane0 ~/siri/optane1 ~/siri/optane2 ~/siri/optane3
```

```shell
mc admin config set myminio/ storage_class dma="read+write"
```

## Context
I want to enable O_DIRECT

## Your Environment
the file sysytem of back-end storage is xfs.

I use following commit:
commit 920b863955e530737344427ac415dcac9e4a234c (HEAD -> master, origin/master, origin/HEAD)
Author: Ritesh H Shukla <kerneltime@gmail.com>
Date:   Mon Jun 8 18:03:15 2020 -0700
will reproduce current behavior

if i use 
commit 920b863955e530737344427ac415dcac9e4a234c (HEAD -> master, origin/master, origin/HEAD)
Author: Ritesh H Shukla <kerneltime@gmail.com>
Date:   Mon Jun 8 18:03:15 2020 -0700

it's ok.

**Comment by harshavardhana** [comment]
You are running a very old version of MinIO please use latest release.

**Comment by sirizhou** [comment]
Oh my god, I didn’t realize that this year is 21 years. 
I don’t know how I got such an old version.
Thank you very much！
