### ISSUE TITLE
docker compose部署的时候 server 启动报错 Unable to read 'format.json' from http://192.168.1.100:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)

### ISSUE THREAD

**Issue by hskycloud** [minio/minio#11596]
## Current Behavior
minio    | Waiting for a minimum of 2 disks to come online (elapsed 2m19s)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.100:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.101:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.102:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.103:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Waiting for a minimum of 2 disks to come online (elapsed 2m20s)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.100:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.101:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.102:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)
minio    |
minio    | Unable to read 'format.json' from http://192.168.1.103:9000/data: Server expects 'storage' API version 'v27', instead found 'v27' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-02-19T04-38-02Z)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

version: '3.7'

# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio:
    image: minio/minio:RELEASE.2021-02-19T04-38-02Z
    container_name: minio
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/data
      - ./config:/root/.minio
    expose:
      - "9000"
    ports:
      - 9000:9000      
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: xxx
    command: server http://192.168.1.100/data http://192.168.1.101/data http://192.168.1.102/data http://192.168.1.103/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.103:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

**Comment by harshavardhana** [comment]
Rolling upgrade is not supported, upgrade all servers @hskycloud

**Comment by harshavardhana** [comment]
> command: server http://192.168.1.100/data http://192.168.1.101/data http://192.168.1.102/data http://192.168.1.103/data

Use service names in docker without using IP addresses, if you want to use IP address use `net: host` option
