### ISSUE TITLE
docs: how to set up a minio cluster?

### ISSUE THREAD

**Issue by wangkirin** [minio/minio#1159]
I am trying to use `minio` as object storage service in our project, but after reading `README.md`  I still don't know how to use `minio` to set up a large scale(multi-node)  storage cluster, could someone give me a guide? thank you !

**Comment by klausenbusk** [comment]
I don't think you can run the XL version yet. Maybe ask at [gitter](https://gitter.im/minio/minio).

**Comment by harshavardhana** [comment]
@klausenbusk  - yes right @wangkirin sorry for responding late. Scale out version is a work in progress for now you can setup single backend filesystem.

**Comment by wangkirin** [comment]
@harshavardhana , thank you for your response : )
Are there any plan to support high availability  feature like multi copy of storage instance ?

**Comment by harshavardhana** [comment]
> Are there any plan to support high availability feature like multi copy of storage instance ?

There are no plans to implement 'mutli copy/replication' .  

XL backend will be erasure coded across multiple disks and nodes.  High availability is provided through XL backend which can withstand multiple disk failures.  XL backend has a max limit of 16 (8 data and 8 parity). You may scale up with 1 server and 16 disks or 16 servers with 1 disk each or any combination in-between. Any of the 16 nodes can serve the same data,  8 of the 16 servers can go down you will still be able to access your data. 

But FS backend might also work for majority of the use cases.  For HA in FS, you simply do 'mc mirror' via cron job to another instance within the same cluster. 

NOTE 'mc' is Minio Client is a command line tool to get/put data between various S3 compatible storage vendors - https://github.com/minio/mc

**Comment by lavvy** [comment]
Please has this feature been added. Or when is it likely to be completed

**Comment by harshavardhana** [comment]
> Please has this feature been added. Or when is it likely to be completed

Single node version for aggregating multiple disks - is already available on the master branch and we will be making a release soon, we are working in parallel on the multi node part as well which will be ready in around 2months time.

**Comment by ameent** [comment]
@harshavardhana any help I can offer for getting the distributed version out? Are there any design docs I can look at?

**Comment by harshavardhana** [comment]
> @harshavardhana any help I can offer for getting the distributed version out? Are there any design docs I can look at?

@ameent we are working on it right now, there are no design docs available. Feel free to chime into our conversations at https://gitter.im/minio/minio.

**Comment by koolhead17** [comment]
Hello @ameent, we have just added https://docs.minio.io/docs/minio-erasure-code-quickstart-guide but as @harshavardhana mentioned we are still working on detailed design doc.

**Comment by kevinsimper** [comment]
I was wondering the same, but I am a little confused how disk failure is the same clustering? If that single minio disappears then you can't get your files until it comes online again, but the idea behind  S3 is that the data is replicated behind the scenes.

**Comment by koolhead17** [comment]
@kevinsimper minio distributed version implements erasure code to protect data even when N/2 disks fail, your cluster is up and working. More on [https://docs.minio.io/docs/minio-erasure-code-quickstart-guide](https://docs.minio.io/docs/minio-erasure-code-quickstart-guide)

For standalone Minio server one can simply use `mc mirror command`  with `--watch` to another minio server, so in real time your data is mirrored to remote location which can be local data centre or remote cloud. This link will help [https://docs.minio.io/docs/minio-client-complete-guide#mirror](https://docs.minio.io/docs/minio-client-complete-guide#mirror)

Feel free to join us on on [Gitter developer chat channel](https://gitter.im/minio/minio)

**Comment by kramer65** [comment]
We are looking for a self hosted data storage solution similar to S3. Minio seems perfect, but we need to avoid any single points of failure. Therefore, every service we've got, needs to be running on at least two nodes. 
I'm not sure what erasure exactly is, but as far as I understand it's a way for a server with multiple drives to still be online if one or more drives fail (please correct me if I'm wrong). 
We need more than that though. We also need to replicate the data onto another server in another physical location so that even if one of the data centers explodes we are still online. 

Does minio.io currently offer such functionality? If needed we are happy to pay for it.

**Comment by harshavardhana** [comment]
> We are looking for a self hosted data storage solution similar to S3. Minio seems perfect, but we need to avoid any single points of failure. Therefore, every service we've got, needs to be running on at least two nodes. 
> I'm not sure what erasure exactly is, but as far as I understand it's a way for a server with multiple drives to still be online if one or more drives fail (please correct me if I'm wrong). 

We have a document which explains this - https://docs.minio.io/docs/minio-erasure-code-quickstart-guide

> We need more than that though. We also need to replicate the data onto another server in another physical location so that even if one of the data centers explodes we are still online.

To replicate the data to another data center you should use - https://docs.minio.io/docs/minio-client-complete-guide#mirror

> Does minio.io currently offer such functionality? If needed we are happy to pay for it.

Feel free to join us at https://gitter.im/minio/minio we are happy to help in anyway we can.

**Comment by pascalandy** [comment]
You can check out my step-by-step guide:
[The complete guide to attach a Docker volume with Minio on your Docker Swarm Cluster](http://firepress.org/blog/the-complete-guide-to-attach-a-docker-volume-with-minio-on-your-docker-swarm-cluster/)

**Comment by k0nsl** [comment]
@pascalandy: your blog is dead.

**Comment by pascalandy** [comment]
Thx for letting me know. Fixed !

**Comment by linc978** [comment]
I have a 4 nodes configuration, which each node is exporting /mnt/sdc1/www18[1234] respectively.
The 4 nodes are using  NTP service  to sync up their clock.
They also use environment variables to define the same access key and secret key.
The distributed MINIO was hanging in the following state for several hours.
Any clue is it a user error, or how to debug this problem?

Below is the console output from node-181 from a re-run:

[root@minio181 ~]# minio server --address=:9000  http://10.245.37.181/mnt/sdc1/www181 http://10.245.37.182/mnt/sdc1/www182 http://10.245.37.183/mnt/sdc1/www183 http://10.245.37.184/mnt/sdc1/www184
Created minio configuration file successfully at /root/.minio

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 1 month ago     ┃
┃ Update: https://dl.minio.io/server/minio/release/linux-amd64/minio ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 22s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 34s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 53s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1m10s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1m30s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1m53s)
ERRO[0136] Disk http://10.245.37.182:9000/mnt/sdc1/www182 is still unreachable  cause=disk not found source=[prepare-storage.go:202:printRetryMsg()]
ERRO[0136] Disk http://10.245.37.183:9000/mnt/sdc1/www183 is still unreachable  cause=disk not found source=[prepare-storage.go:202:printRetryMsg()]
ERRO[0136] Disk http://10.245.37.184:9000/mnt/sdc1/www184 is still unreachable  cause=disk not found source=[prepare-storage.go:202:printRetryMsg()]
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 2m15s)

**Comment by nitisht** [comment]
@linc978 we fixed some Docker/Swarm related issues in the latest release, Can you try the latest release image `RELEASE.2017-09-29T19-16-56Z` and let us know how it went?

**Comment by linc978** [comment]
Using the latest version yielded the same result, with "disk not found" error.

[root@minio181 ~]# minio version
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21

To remove complexity, I ran the 4 MINIO servers on 4 (centos) VMs.
They are on the same subnet, and can ping each other, and their time is in sync.
Each VM has the following mount on /mnt/sdc1
/dev/sdc1 on /mnt/sdc1 type ext4 (rw,relatime,seclabel,data=ordered)

"minio server /mnt/sdc1" was successfully run on the 4 VM.

For distributed MINIO, each VM ran the same command as follows:

rm -rf  /root/.minio   /mnt/sdc1/.minio.sys

export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=password
 minio server   http://10.245.37.181/mnt/sdc1 http://10.245.37.182/mnt/sdc1 http://10.245.37.183/mnt/sdc1 http://10.245.37.184/mnt/sdc1

Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 13m4s)
ERRO[0801] Disk http://10.245.37.182:9000/mnt/sdc1 is still unreachable  cause=disk not found source=[prepare-storage.go:197:printRetryMsg()]
ERRO[0801] Disk http://10.245.37.183:9000/mnt/sdc1 is still unreachable  cause=disk not found source=[prepare-storage.go:197:printRetryMsg()]
ERRO[0801] Disk http://10.245.37.184:9000/mnt/sdc1 is still unreachable  cause=disk not found source=[prepare-storage.go:197:printRetryMsg()]
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 13m21s)

**Comment by harshavardhana** [comment]
Do you have selinux enabled ?

**Comment by linc978** [comment]
yes, should I disable it ?

[root@minio181 golang-book]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**Comment by harshavardhana** [comment]
> yes, should I disable it ?

can you try that?

**Comment by linc978** [comment]
Did the following on all 4 VMs with SELINUX disabled, same result.

[root@minio181 ~]# sestatus
SELinux status:                 disabled

[root@minio183 ~]# rm -rf  /root/.minio /mnt/sdc1/.minio.sys /mnt/sdc1/*
[root@minio183 ~]# export MINIO_SECRET_KEY=password; export MINIO_ACCESS_KEY=admin
[root@minio183 ~]# minio server   http://10.245.37.181/mnt/sdc1 http://10.245.37.182/mnt/sdc1 http://10.245.37.183/mnt/sdc1 http://10.245.37.184/mnt/sdc1
Created minio configuration file successfully at /root/.minio
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 19s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 37s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1m0s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1m19s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1m36s)
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 2m3s)
ERRO[0142] Disk http://10.245.37.181:9000/mnt/sdc1 is still unreachable  cause=disk not found source=[prepare-storage.go:197:printRetryMsg()]
ERRO[0142] Disk http://10.245.37.182:9000/mnt/sdc1 is still unreachable  cause=disk not found source=[prepare-storage.go:197:printRetryMsg()]
ERRO[0142] Disk http://10.245.37.184:9000/mnt/sdc1 is still unreachable  cause=disk not found source=[prepare-storage.go:197:printRetryMsg()]

**Comment by linc978** [comment]
I can do ssh/scp among the 4 VMs without a password.
Each MINIO server can see the local directory, but not the remote directories.
The previous console was from host-183, which couldn't see the directories from 181,182 and 184.
Same behavior on the other 3 VMs.

below is their routing information:
[root@minio181 ~]# ip route
default via 10.245.37.1 dev ens192 
10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.181 
169.254.0.0/16 dev ens192 scope link metric 1002 
[root@minio181 ~]# ssh root@10.245.37.182 ip route
default via 10.245.37.1 dev ens192 
10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.182 
169.254.0.0/16 dev ens192 scope link metric 1002 
[root@minio181 ~]# ssh root@10.245.37.183 ip route
default via 10.245.37.1 dev ens192 
10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.183 
169.254.0.0/16 dev ens192 scope link metric 1002 
[root@minio181 ~]# ssh root@10.245.37.184 ip route
default via 10.245.37.1 dev ens192 
10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.184 
169.254.0.0/16 dev ens192 scope link metric 1002

**Comment by harshavardhana** [comment]
> I can do ssh/scp among the 4 VMs without a password.
> Each MINIO server can see the local directory, but not the remote directories.
> The previous console was from host-183, which couldn't see the directories from 181,182 and 184.
> Same behavior on the other 3 VMs.
> 
> below is their routing information:
> [root@minio181 ~]# ip route
> default via 10.245.37.1 dev ens192
> 10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.181
> 169.254.0.0/16 dev ens192 scope link metric 1002
> [root@minio181 ~]# ssh root@10.245.37.182 ip route
> default via 10.245.37.1 dev ens192
> 10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.182
> 169.254.0.0/16 dev ens192 scope link metric 1002
> [root@minio181 ~]# ssh root@10.245.37.183 ip route
> default via 10.245.37.1 dev ens192
> 10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.183
> 169.254.0.0/16 dev ens192 scope link metric 1002
> [root@minio181 ~]# ssh root@10.245.37.184 ip route
> default via 10.245.37.1 dev ens192
> 10.245.37.0/24 dev ens192 proto kernel scope link src 10.245.37.184
> 169.254.0.0/16 dev ens192 scope link metric 1002

Can you head over to https://slack.minio.io and ping us, i can login remotely and take a look if that is possible.

**Comment by linc978** [comment]
My VMs are behind corporate firewalls, thus no access from outside. Can you point me to any tips on how to triage the network storage problem with MINIO ? I have also subscribed to https://slack.minio.io
Thanks!

**Comment by linc978** [comment]
harshavardhana, Thank you for your help. It's exciting to see our MINIO cluster up and running.

**Comment by harshavardhana** [comment]
> harshavardhana, Thank you for your help. It's exciting to see our MINIO cluster up and running.

:+1:  we will try to document iptables instructions in our docs.

**Comment by pascalandy** [comment]
I pure laziness, may I ask what is the final answer?
Thanks in advance :)

**Comment by harshavardhana** [comment]
> I pure laziness, may I ask what is the final answer?
> Thanks in advance :)

Not sure what are you talking about? @pascalandy @linc978 issue context is not related to Docker.

**Comment by pascalandy** [comment]
Ohh sorry then :-p
I guess I got confused when I saw this comment.

> @linc978 we fixed some Docker/Swarm related issues in the latest release, Can you try the latest release image RELEASE.2017-09-29T19-16-56Z and let us know how it went?

**Comment by linc978** [comment]
I have two 10G networks. Any example on how to configure one for MINIO's inter-cluster nodes communication, and the other for client host access ?

**Comment by harshavardhana** [comment]
@linc978 feel free to join us on slack or create a new github issue. Let's avoid discussing on old issues here.
