### ISSUE TITLE
web: add authentication to brower

### ISSUE THREAD

**Issue by osallou** [minio/minio#1160]
browser should have authentication (using access / secret key), at least optionally.

A very basic use case it executing N servers for N users. Then users are proxied to their server/browser. For security, access should be authenticated.

**Comment by krishnasrinivas** [comment]
Access is authenticated using secret/access Key, do you see the access not authenticated anywhere?

**Comment by osallou** [comment]
nope, this works fine, my fault. Certainly a previous old login and session kept open.... :-(
Closing issue.
