### ISSUE TITLE
download objects with presigned share link, there is no Content-Disposition field in response headers.

### ISSUE THREAD

**Issue by anytimehh** [minio/minio#11605]
## Expected Behavior
If you download objects with presigned share link, there is no Content-Disposition field in response headers.
But if you use download cmd to download the object, there is a Content-Disposition field in the response headers.
It should return normally:
Content-Disposition: attachment; filename="howtoinstall.pptx"

## Possible Solution
In the cmd/object-handlers.go file, add in line 495:
w.Header().Set(xhttp.ContentDisposition, fmt.Sprintf("attachment; filename=\"%s\"", path.Base(objInfo.Name)))

Add "path" on line 29

**Comment by harshavardhana** [comment]
@anytimehh can you provide the reproducible steps ?

**Comment by anytimehh** [comment]
create a share link, download object use the link from chrome eg. then you can see the response headers no Content-Disposition field.

**Comment by anytimehh** [comment]
> @anytimehh can you provide the reproducible steps ?
@harshavardhana
create a share link, download object use the link from chrome eg. then you can see the response headers no Content-Disposition field.

**Comment by harshavardhana** [comment]
> > @anytimehh can you provide the reproducible steps ?
> > @harshavardhana
> > create a share link, download object use the link from chrome eg. then you can see the response headers no Content-Disposition field.

Browser share link doesn't add content-disposition @anytimehh why do you need content-disposition?

**Comment by anytimehh** [comment]
> > > @anytimehh can you provide the reproducible steps ?
> > > @harshavardhana
> > > create a share link, download object use the link from chrome eg. then you can see the response headers no Content-Disposition field.
> 
> Browser share link doesn't add content-disposition @anytimehh why do you need content-disposition?

Sometimes it is necessary to obtain the real filename from the content-disposition field.
Maybe this is not very important. Thank you.

**Comment by vadmeste** [comment]
@anytimehh the exact filename already exists in the presigned URL, however I sent a PR so shared links created by Browser will be in downloadable format automatically.
