### ISSUE TITLE
get file Download Url  Failed

### ISSUE THREAD

**Issue by yanghui-git** [minio/minio#11601]
My environment : Java version  1.8  Ip 192.168.102.199
                              Minio version 8.0.1   Ip 192.168.102.19.99 
                              Java application and Minio  are same deployed machine

Goal：I want to get the file download url that i can download  from minio directly

My method：
I use the method like 
minoclient.getPresignedObjectUrl(
                        GetPresignedObjectUrlArgs.builder()
                                .method(Method.GET)
                                .bucket("new-one")
                                .object("note.txt")
                                .expiry(60 * 60 * 24 * 6)
                                .build());

And If  I set  minioclient  like 
 MinioClient.builder()
                    .endpoint("http://192.168.102.199:9000")    And i get the url   and the url success  I can download the file from minio directly

But  if I set minioclient like  MinioClient.builder()
                    .endpoint("http://localhost:9000")   And I aslo get url  like http://localhost:/............  then  I change localhost to 192.168.102.199

But this url is failed ;  your can see in my picture ;

Question If I want to get the download file url directly, I  must use real Ip like 192.168.102.199  ？ or I can use localhost ?  when I set minoclient

Thanks for very much
<img width="943" alt="截屏2021-02-22 下午6 21 47" src="https://user-images.githubusercontent.com/69784471/108695203-fa21bc80-753a-11eb-884b-862cadbb4615.png">

**Comment by balamurugana** [comment]
As host name in the URL is used in signature calculation, you cannot mangle with that. You have to set appropriate at server and client sides.

**Comment by yanghui-git** [comment]
So  I must use the really IP （ 192.168.102.199） rather then localhost？？
