### ISSUE TITLE
auto remove object with delete markers

### ISSUE THREAD

**Issue by Sug2077** [minio/minio#11616]
## Expected Behavior

I need auto remove all versions of object when delete-marker added

## Steps to Reproduce

1.set ilm
```
mc mb minio1/test1
mc version enable minio1/test1
mc ilm add --expired-object-delete-marker
mc ilm ls minio1/test1 --json
{
 "status": "success",
 "target": "minio1/test1",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "DeleteMarker": true
    },
    "ID": "c0qq592f2j6vqjfllodg",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
```
2.upload object and delete
```
mc ls --versions minio1/test1
[2021-02-24 03:04:15 UTC]     0B 744368d2-2836-4569-9ef5-e845b4e9deb8 v2 DEL s.png
[2021-02-24 03:03:37 UTC] 184KiB de08a495-a302-4c33-bb4c-c8a65b9381ca v1 PUT s.png
```

## Context

Object with delete-marker still exist.
There is no example for this feature, how to configure it.
Or is this a bug？

## Your Environment

minio server:
docker image: minio/minio:RELEASE.2021-02-23T20-05-01Z
mc client:
docker image: minio/mc:RELEASE.2021-02-19T05-34-40Z

**Comment by harshavardhana** [comment]
We cannot do that @Sug2077 because of S3 compatibility - they get deleted upon their expiration once in 24hrs and when their expiration hits.

**Comment by Sug2077** [comment]
> We cannot do that @Sug2077 because of S3 compatibility - they get deleted upon their expiration once in 24hrs and when their expiration hits.

Then my configuration is correct？
I will continue to watch for feedback

**Comment by harshavardhana** [comment]
> Then my configuration is correct？
> I will continue to watch for feedback

The configuration is correct it takes 24hrs to take affect if you have lots of files then it may take more time.

**Comment by Sug2077** [comment]
> > Then my configuration is correct？
> > I will continue to watch for feedback
> 
> The configuration is correct it takes 24hrs to take affect if you have lots of files then it may take more time.

I have create a delete-marker, then set server time to next day, reboot server ,but no change with that object。
How to simulate validation

**Comment by Sug2077** [comment]
> > Then my configuration is correct？
> > I will continue to watch for feedback
> 
> The configuration is correct it takes 24hrs to take affect if you have lots of files then it may take more time.

```
[root@c74d51273406 /]# mc ilm ls miniotest/deletetest --json
{
 "status": "success",
 "target": "miniotest/deletetest",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "DeleteMarker": true
    },
    "ID": "c0r2r2if2j6vne3bnp10",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
[root@c74d51273406 /]# date
Thu Feb 25 11:29:46 UTC 2021
[root@c74d51273406 /]#  mc ls --versions miniotest/deletetest
[2021-02-24 10:47:54 UTC]     0B f4e7e33a-2342-4217-bbea-6664fddf3f5d v2 DEL foxmail.png
[2021-02-24 10:47:47 UTC]  89KiB 4070f911-05cc-445c-bc78-eaba8459d5b5 v1 PUT foxmail.png
```

```
[root@c74d51273406 /]# mc ilm ls miniotest/deletetest2 --json
{
 "status": "success",
 "target": "miniotest/deletetest2",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "DeleteMarker": true
    },
    "ID": "c0r2v22f2j6vmvmtbpd0",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
[root@c74d51273406 /]# date
Thu Feb 25 11:32:34 UTC 2021
[root@c74d51273406 /]#  mc ls --versions miniotest/deletetest2
[2021-02-24 10:51:20 UTC]     0B 41f07b44-50bf-41c9-af48-1eaac867fe82 v1 DEL foxmail.png
```

My test failed

**Comment by harshavardhana** [comment]
You forgot to enable 

```
~ mc ilm add -h |grep expired
  --expired-object-delete-marker                      remove delete markers with no parallel versions
```

**Comment by Sug2077** [comment]
> You forgot to enable
> 
> ```
> ~ mc ilm add -h |grep expired
>   --expired-object-delete-marker                      remove delete markers with no parallel versions
> ```

I'm sure I have enable ilm,
use this `mc ilm add --expired-object-delete-marker miniotest/deletetest `

```
[root@c74d51273406 /]# mc ilm export miniotest/deletetest
{
 "Rules": [
  {
   "AbortIncompleteMultipartUpload": {},
   "Expiration": {
    "Date": "0001-01-01T00:00:00Z",
    "DeleteMarker": true
   },
   "ID": "c0r2r2if2j6vne3bnp10",
   "Filter": {
    "And": {},
    "Tag": {}
   },
   "NoncurrentVersionExpiration": {
    "NoncurrentDays": 0
   },
   "NoncurrentVersionTransition": {},
   "Status": "Enabled",
   "Transition": {
    "Date": "0001-01-01T00:00:00Z"
   }
  }
 ]
}
```

**Comment by vadmeste** [comment]
>  I need auto remove all versions of object when delete-marker added

You need to enable 

```
   "NoncurrentVersionExpiration": {
    "NoncurrentDays": 0
   },
```

**Comment by Sug2077** [comment]
> > I need auto remove all versions of object when delete-marker added
> 
> You need to enable
> 
> ```
>    "NoncurrentVersionExpiration": {
>     "NoncurrentDays": 0
>    },
> ```

I found another problem, `--noncurrentversion-expiration-days` must set at the ilm creation time
`mc ilm edit` doesn't work

```
[root@minio4 ~]# mc ilm ls localhost/deletetest --json
{
 "status": "success",
 "target": "localhost/deletetest",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "DeleteMarker": true
    },
    "ID": "c0r2r2if2j6vne3bnp10",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
[root@minio4 ~]# mc ilm edit --id c0r2r2if2j6vne3bnp10 --noncurrentversion-expiration-days 1  localhost/deletetest
Lifecycle configuration rule with ID `c0r2r2if2j6vne3bnp10` modified  to localhost/deletetest.
[root@minio4 ~]# mc ilm ls localhost/deletetest --json
{
 "status": "success",
 "target": "localhost/deletetest",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "DeleteMarker": true
    },
    "ID": "c0r2r2if2j6vne3bnp10",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
```

**Comment by Sug2077** [comment]
> > I need auto remove all versions of object when delete-marker added
> 
> You need to enable
> 
> ```
>    "NoncurrentVersionExpiration": {
>     "NoncurrentDays": 0
>    },
> ```

After set the `--noncurrentversion-expiration-days 1`, auto delete start work, but it just delete alone delete-markers.
How to configure auto delete all versions of object when the object's last version is a delete-marker?

**Comment by vadmeste** [comment]
@Sug2077 yes, it looks like ilm edit doesn't work. I will send a fix.

For the moment, as a workaround, just do `mc ilm export` then `mc ilm import` after editing the JSON to set you NoncurrentVersionExpiration days

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/pull/3626 fixed here
