### ISSUE TITLE
Minio gateway not working with scaleway s3/play.min.io

### ISSUE THREAD

**Issue by mayli** [minio/minio#11614]
The gateway also doesn't work with scaleway s3.
MINIO_REGION=nl-ams MINIO_ROOT_USER=acc MINIO_ROOT_PASSWORD=sec ./minio gateway s3 https://s3.nl-ams.scw.cloud/
 ./mc ls local/
mc: <ERROR> Unable to list folder. The specified bucket does not exist
 ./mc ls local/some_bucket
mc: <ERROR> Unable to list folder. Access Denied.

The gateway also doesn't work with play.min.io

`MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG ./minio gateway s3 https://play.min.io`
$ ./mc ls local/user/
mc: <ERROR> Unable to list folder. Access Denied.
$ ./mc ls play/user
[2021-02-23 14:13:48 PST]     0B 2021/

## Expected Behavior
mc should be able to access the scaleway s3 (or play.min.io) via gateway

## Current Behavior
server is logging those errors.

minio:
API: SYSTEM()
Time: 13:55:52 PST 02/23/2021
DeploymentID: d5202c2d-88da-4565-b4f1-129451a9aa8d
Error: Prefix access is denied: some_bucket/ (cmd.PrefixAccessDenied)
       5: cmd/bucket-policy.go:52:cmd.(*PolicySys).IsAllowed()
       4: cmd/auth-handler.go:343:cmd.checkRequestAuthTypeToAccessKey()
       3: cmd/auth-handler.go:274:cmd.checkRequestAuthType()
       2: cmd/bucket-listobjects-handlers.go:217:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()

## Possible Solution
The `mc list scaleway/some_bucket` is working, so the issue is likely specific to gateway

## Context
using minio as gateway of scaleway s3

## Regression
no

## Your Environment
minio version RELEASE.2021-02-19T04-38-02Z
Ubuntu 18.04

**Comment by harshavardhana** [comment]
There was bug in release

> minio version RELEASE.2021-02-19T04-38-02Z

Please update to the latest release

**Comment by mayli** [comment]
@harshavardhana 
Tested with minio version RELEASE.2021-02-23T20-05-01Z, still unable to use gateway with play.min.io

$ MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG ./minio gateway s3 https://play.min.io

Works for direct access
```
$ ./mc ls play/repro
[2021-02-23 14:23:04 PST]     0B pre/
```

Access denied in gateway
```
$ ./mc ls local/repro
mc: <ERROR> Unable to list folder. Access Denied.
```

**Comment by harshavardhana** [comment]
Looks like you have some local configuration that is messing with `gateway` check if you have `~/.aws/credentials` etc. 

```
~ MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG ./minio gateway s3 https://play.min.io
Endpoint: https://10.0.0.67:9000  https://172.17.0.1:9000  https://172.18.0.1:9000  https://127.0.0.1:9000                   
RootUser: Q3AM3UQ867SPQQA43P2F 
RootPass: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG 

Browser Access:
   https://10.0.0.67:9000  https://172.17.0.1:9000  https://172.18.0.1:9000  https://127.0.0.1:9000           
...

```

```
~ mc alias set mys3-play https://localhost:9000 Q3AM3UQ867SPQQA43P2F zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```

```
~ mc ls mys3-play/testbucket/
[2021-02-23 10:49:41 PST]  16MiB minio.gz
```

**Comment by mayli** [comment]
@hackintoshrao I think that some misunderstanding of minio gateway, I thought I am able to use a new set of RootUser and RootPass when accessing the gateway while keeping the original one as secret. But it seems I have to use the exact creds for gateway clients. Thanks for the examples.

**Comment by harshavardhana** [comment]
> @hackintoshrao I think that some misunderstanding of minio gateway, I thought I am able to use a new set of RootUser and RootPass when accessing the gateway while keeping the original one as secret. But it seems I have to use the exact creds for gateway clients. Thanks for the examples.

you can but for that you need to AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY .. for separate creds for backend communication.

**Comment by mayli** [comment]
It seems the gateway doesn't support that ENV VAR, so the MINIO_ROOT_USER MINIO_ROOT_PASSWORD are reused for both remote S3 and local server
```
$ AWS_ACCESS_KEY_ID=Q3AM3UQ867SPQQA43P2F AWS_SECRET_ACCESS_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG ./minio gateway s3 https://play.min.io
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters
```

**Comment by harshavardhana** [comment]
> $ AWS_ACCESS_KEY_ID=Q3AM3UQ867SPQQA43P2F AWS_SECRET_ACCESS_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG ./minio gateway s3 https://play.min.io

you need to set both @mayli
