### ISSUE TITLE
Inconsistent AMQP bucket notification documentation

### ISSUE THREAD

**Issue by torblerone** [minio/minio#11613]
I wanted to test MinIO bucket notifications in combination with a RabbitMQ instance. I wanted to setup configuration with environment variables as they are easy to deploy with kustomization's `configMapGenerator`.

I used this documentation: [Publish MinIO events via AMQP](https://docs.min.io/docs/minio-bucket-notification-guide.html)

It says that the environment variable `MINIO_NOTIFY_AMQP_DELIVERY_MODE` can be set to `1` for non-persistent and to `2` for persistent queues. The examples command uses number `0` instead, so I don't really know which configuration/combination is right: `0/1` or `1/2`?

## Expected Behavior

Clear documentation of valid configuriation values

## Current Behavior

Confusing mismatch of valid configurations 

## Possible Solution

Update the docs? :-)

## Steps to Reproduce (for bugs)

[Publish MinIO events via AMQP](https://docs.min.io/docs/minio-bucket-notification-guide.html)

## Context

I'm not able to setup MinIO bucket notifications in combination with AMQP right now.

## Regression

no

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
not neccessary

**Comment by ravindk89** [comment]
@poornas looking at the docs for `streadway/amqp`, it *looks* like setting `delivery_mode` 0 might alias to 1? It looks like we are using the `Publishing` struct as part of the call, and the docs for [`Publishing`](https://pkg.go.dev/github.com/streadway/amqp#Publishing) imply that `0/1` = `Transient` (Non-Persistent?) and `2` is (Persistent). 

Does that sound about right? If that's the case, the doc example is correct, but the reference is incomplete (should not `0/1` are interchangeable for the purpose of setting Transient, and maybe that `0` is the default if unset?)

**Comment by poornas** [comment]
>Does that sound about right? If that's the case, the doc example is correct, but the reference is incomplete (should not 0/1 are interchangeable for the purpose of setting Transient, and maybe that 0 is the default if unset?)

sounds correct - 0 is the default if unset

**Comment by torblerone** [comment]
@ravindk89 @poornas Thank you for your answer! So if I understand correctly, `0/1` maps to **non-persistent** and `2` maps to **persistent**, which leads to the following reference:

```
0 - non-persistent  default
1 - non-persistent  explicit
2 - persistent      explicit
```
