### ISSUE TITLE
[Federation] accountInfo returns incorrect bucket size

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#11624]
I have 3 clusters in federation setup and a user has a bucket in each cluster.
`accountInfo()` returns all buckets within the federation since https://github.com/minio/minio/commit/84d400487f0a467f4cec20c06d5da392bfbfa8b4 but it returns `0` for some buckets' size. 

Is it because we cannot get the `Size` and `Access` from `dnsBuckets`?

`cmd/admin-handlers-users.go` in https://github.com/minio/minio/commit/84d400487f0a467f4cec20c06d5da392bfbfa8b4:
```go
for _, dnsRecords := range dnsBuckets {
    buckets = append(buckets, BucketInfo{
    Name:    dnsRecords[0].Key,
    Created: dnsRecords[0].CreationDate,
  })
}
```

`BucketUsageInfo`:

```go
type BucketUsageInfo struct {
   Name    string        `json:"name"`
   Size    uint64        `json:"size"`
   Created time.Time     `json:"created"`
   Access  AccountAccess `json:"access"`
}
```

**Comment by harshavardhana** [comment]
Unfortunately, this can only work if the federation has the knowledge, AccountInfo is never meant and designed to work for federation. 

Federation is also deprecated and will be removed in the future. So if you are still using it please be aware. Nothing actionable from our end at this point in time.

**Comment by ToLToL** [comment]
I should expand existing distributed setup instead of federation as stated here : https://docs.minio.io/docs/distributed-minio-quickstart-guide.html ?
