### ISSUE TITLE
Slow objects listing on rotational (high latency) media

### ISSUE THREAD

**Issue by skand888** [minio/minio#11625]
**Is your feature request related to a problem? Please describe.**
At Flexify we recommend Minio Server as a file/disk->object storage gateway for disk-to-object migrations. But when the original data is on a rotational media, such as HDD RAID or GCP's standard persistent disk, the listing of objects via the S3 API is extremely slow. It might take up to two minutes on an otherwise not utilized disk to get the default page size of 4,500 objects. 

This happens because for each object MinIO makes a system `stat` call, sequentially, and on a rotational media, each such call might take 15-20 ms. 0.020 * 4,500 = 90 seconds. 

For example, this happens in the `listObjects` function (calling `getObjInfo` and `getObjectInfoDir` sequentially in a cycle):

```go
	for i := 0; i < maxKeys; {
                // ...
		if HasSuffix(walkResult.entry, SlashSeparator) {
			for _, getObjectInfoDir := range getObjectInfoDirs {
				objInfo, err = getObjectInfoDir(ctx, bucket, walkResult.entry)
				// ...
			}
		} else {
			objInfo, err = getObjInfo(ctx, bucket, walkResult.entry)
		}
		// ...
		i++
	}
```

**Describe the solution you'd like**
Call  `getObjInfo` and `getObjectInfoDir` for multiple entries in parallel. Most disk systems, including Google Cloud's standard persistent disk, while having high latency, can perform many requests in parallel. Calling 100 parallel `stat` would also return in 15-20 ms, but the entire list page would complete 100 faster, in under 1 second compared to 90+ seconds. 

**Describe alternatives you've considered**
Not calling `stat` at all and returning the list w/o object's metadata such as size.

**Additional context**
`sdb` is GCP's standard persistent disk (on HDDs), and `sdc` is GCP's balanced persistent disk (SSDs), both are working on listing a large number of objects via Minio. Note the difference in `r_await` and `r/s`.
![standard_vs_balanced](https://user-images.githubusercontent.com/15358281/109040459-e3c95b80-7708-11eb-8e64-5d4926930fa2.JPG)

**Comment by harshavardhana** [comment]
This is single drive setup ? @skand888

**Comment by skand888** [comment]
> This is single drive setup ? @skand888

No, it's a multi-terabyte GCP's standard persistent disk, it promises at least 3,500 read tps. But I guess a local HDD-based RAID array would be very similar.

**Comment by harshavardhana** [comment]
> No, it's a multi-terabyte GCP's standard persistent disk, it promises at least 3,500 read tps. But I guess a local HDD-based RAID array would be very similar.

I mean `minio` setup can you share how you passed your command line?

**Comment by skand888** [comment]
> I mean `minio` setup can you share how you passed your command line?

Just as simple as `./minio server ./minio-root`

**Comment by skand888** [comment]
> I mean `minio` setup can you share how you passed your command line?

Just a single directory. We use `minio` to expose pre-existing data via S3 API so we can take it and migrate elsewhere.

**Comment by harshavardhana** [comment]
Then you are seeing what is your disk capable of, listing on single drive setups has no special optimizations. I don't know what we can do here.

**Comment by skand888** [comment]
> Then you are seeing what is your disk capable of, listing on single drive setups has no special optimizations. I don't know what we can do here.

Nope. The disk is capable of 3,500 read tps, if done in parallel. But only 50-100 tps if done sequentially. If you make those `stat` calls concurrently instead of sequentially, you can get the stat for the entire page much faster.

**Comment by harshavardhana** [comment]
> > Then you are seeing what is your disk capable of, listing on single drive setups has no special optimizations. I don't know what we can do here.
> 
> Nope. The disk is capable of 3,500 read tps, if done in parallel. But only 50-100 tps if done sequentially. If you make those `stat` calls concurrently instead of sequentially, you can get the stat for the entire page much faster.

But then that would lower the IOPS for other I/O operations we can't just do that at a whim. You only wish to list content and migrate, but that is not the only use case MinIO is designed for.  You can make this modification locally and use it.  But it can't be added as part of an upstream release.

**Comment by skand888** [comment]
> But then that would lower the IOPS for other I/O operations we can't just do that at a whim. You only wish to list content and migrate, but that is not the only use case MinIO is designed for. You can make this modification locally and use it. But it can't be added as part of an upstream release.

Even if `minio` is sharing IOPS with some other services on the same disk, it should be able to utilize more than 3% of available IOPS. Even native `ls` does it. And 90+ seconds for getting a page of 4,500 is unusable anyway. Limiting concurrency to a single routine is not how you distribute resources between services. 

We did local modifications (just removed the `stat` call) that allow us to get all available IOPS now. But I think it could be a good improvement for a generic user that would want to run `minio` on RAID and do not suffer from the unpractically long listing.

**Comment by harshavardhana** [comment]
Will think about it @skand888

**Comment by jgspratt** [comment]
What is the downside of removing the stat call?

Would there be any downside from defining an environment variable that would disable the stat call? Or enable parallel stat?

**Comment by skand888** [comment]
> What is the downside of removing the stat call?
> 
> Would there be any downside from defining an environment variable that would disable the stat call? Or enable parallel stat?

Without the stat call, the size of the objects cannot be known. It works for our case, but I don't think it's much useful for the mainstream. Parallel stat calls seem to be the best solution, and can also be the default behavior as it's OS scheduler's responsibility to distribute IOPS between processes. We actually tested it (all 4,500 calls in goroutines) on a fork and have not noticed any extreme load on RAM/CPU/Disk, but noticed over 100x response time improvement. 

I don't see a reason why it could be in the mainstream. Or at least an environment variable could be used to limit the parallelism.

**Comment by klauspost** [comment]
@skand888 I have added a pull request with 10 concurrently running operations. That should yield a reasonable improvement and not kill weaker systems.

I will not add this as a config value, but you are of course welcome to do your own builds.

**Comment by skand888** [comment]
> @skand888 I have added a pull request with 10 concurrently running operations. That should yield a reasonable improvement and not kill weaker systems.
> 
> I will not add this as a config value, but you are of course welcome to do your own builds.

Thanks!
