### ISSUE TITLE
Let service run as application user instead of root user

### ISSUE THREAD

**Issue by vanthome** [minio/minio#11626]
In the docker world it's best practice to let a containerized service run as non-root.
[For example Postgres create a `postgres` user and then in the Dockerfile use `USER postgres` to let the workload run under that user.](https://docs.docker.com/engine/examples/postgresql_service/). 
I recommend you also introduce such a user for the official ArangoDB container images.

**Comment by harshavardhana** [comment]
Multiple ways to do it you can run using securityContext  @vanthome or specify MINIO_USERNAME or MINIO_GROUPNAME or you can run as `docker run --user`

**Comment by vanthome** [comment]
I can't find any docs about `MINIO_USERNAME`. Can you give me a pointer?

**Comment by harshavardhana** [comment]
> I can't find any docs about `MINIO_USERNAME`. Can you give me a pointer?

just use `docker run --user` easier

**Comment by vanthome** [comment]
I have tried to set the user in docker compose like this `user: "1000"`. This is the result:

```
b-minio1           | 
b-minio1           | API: SYSTEM()
b-minio1           | Time: 11:17:54 UTC 02/26/2021
b-minio1           | Error: disk returned an unexpected error at http://b-minio1:9000/export, please investigate - disk will be offline (*errors.errorString)
b-minio1           |        5: cmd/storage-rest-server.go:1005:cmd.logFatalErrs()
b-minio1           |        4: cmd/storage-rest-server.go:1023:cmd.registerStorageRESTHandlers()
b-minio1           |        3: cmd/routers.go:28:cmd.registerDistErasureRouters()
b-minio1           |        2: cmd/routers.go:93:cmd.configureServerHandler()
b-minio1           |        1: cmd/server-main.go:464:cmd.serverMain()
b-minio1           | ERROR Unable to initialize backend: Unable to write to the backend
b-minio1           |       > Please ensure MinIO binary has write permissions for the backend
b-minio1           |       HINT:
b-minio1           |         Run the following command to add write permissions: `sudo chown -R <your-username>. <path> && sudo chmod u+rxw <path>`

````

And I'm not using any mapped host paths. so just setting the user will not be sufficient.

**Comment by harshavardhana** [comment]
> I have tried to set the user in docker compose like this `user: "1000"`. This is the result:
> 
> ```
> b-minio1           | 
> b-minio1           | API: SYSTEM()
> b-minio1           | Time: 11:17:54 UTC 02/26/2021
> b-minio1           | Error: disk returned an unexpected error at http://b-minio1:9000/export, please investigate - disk will be offline (*errors.errorString)
> b-minio1           |        5: cmd/storage-rest-server.go:1005:cmd.logFatalErrs()
> b-minio1           |        4: cmd/storage-rest-server.go:1023:cmd.registerStorageRESTHandlers()
> b-minio1           |        3: cmd/routers.go:28:cmd.registerDistErasureRouters()
> b-minio1           |        2: cmd/routers.go:93:cmd.configureServerHandler()
> b-minio1           |        1: cmd/server-main.go:464:cmd.serverMain()
> b-minio1           | ERROR Unable to initialize backend: Unable to write to the backend
> b-minio1           |       > Please ensure MinIO binary has write permissions for the backend
> b-minio1           |       HINT:
> b-minio1           |         Run the following command to add write permissions: `sudo chown -R <your-username>. <path> && sudo chmod u+rxw <path>`
> ```
> 
> And I'm not using any mapped host paths. so just setting the user will not be sufficient.

You need to also make sure that your drive at /export has write permissions for the user - this is normal even having user inside Dockerfile won't help this situation. 

Use `/tmp/export` which your user has write access to.

**Comment by vanthome** [comment]
ok, but this way I need to derive from the mino image and create my own derivative with some `RUN chown...` right? I cannot do this just with paramterization of `docker run`...?

**Comment by harshavardhana** [comment]
> ok, but this way I need to derive from the mino image and create my own derivative with some `RUN chown...` right? I cannot do this just with paramterization of `docker run`...?

Not at all you need to have a local directory that has the same permissions as the user you are running as..

docker run --user ... -v /home/user/drive:/export ..

**Comment by drTr0jan** [comment]
> I have tried to set the user in docker compose like this `user: "1000"`. This is the result:
> 
> ```
> b-minio1           | 
> b-minio1           | API: SYSTEM()
> b-minio1           | Time: 11:17:54 UTC 02/26/2021
> b-minio1           | Error: disk returned an unexpected error at http://b-minio1:9000/export, please investigate - disk will be offline (*errors.errorString)
> b-minio1           |        5: cmd/storage-rest-server.go:1005:cmd.logFatalErrs()
> b-minio1           |        4: cmd/storage-rest-server.go:1023:cmd.registerStorageRESTHandlers()
> b-minio1           |        3: cmd/routers.go:28:cmd.registerDistErasureRouters()
> b-minio1           |        2: cmd/routers.go:93:cmd.configureServerHandler()
> b-minio1           |        1: cmd/server-main.go:464:cmd.serverMain()
> b-minio1           | ERROR Unable to initialize backend: Unable to write to the backend
> b-minio1           |       > Please ensure MinIO binary has write permissions for the backend
> b-minio1           |       HINT:
> b-minio1           |         Run the following command to add write permissions: `sudo chown -R <your-username>. <path> && sudo chmod u+rxw <path>`
> ```
> 
> And I'm not using any mapped host paths. so just setting the user will not be sufficient.

I've same error after upgrade from 2021.02.11.08.23.43 to 2021.02.24.18.44.45.

**Comment by vanthome** [comment]
@hackintoshrao this solution involves using an externally mapped volume but I want to use the default docker volume as defined by the container image.

**Comment by harshavardhana** [comment]
> @hackintoshrao this solution involves using an externally mapped volume but I want to use the default docker volume as defined by the container image.

I don't know if docker allows that but in k8s this is very normal and works 

```
      ## Configure security context 
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
```

**Comment by harshavardhana** [comment]
Or you can run

```
docker run -e MINIO_USERNAME=name -e MINIO_GROUPNAME=group
```
