### ISSUE TITLE
Distributed MinIO active-active replicate

### ISSUE THREAD

**Issue by sjn939394630** [minio/minio#11631]
I have four server make up two mino-clusters. server1-2 make up cluster1 and server3-4 make up cluster2. and I want cluster1's object operation can replicate to cluster2, so I create an active-active replication on server1 and server3.
## Expected Behavior

put object to cluster1 or cluster2 can replicate to eachother
## Current Behavior

Now I put object to cluster1-server1 or cluster2-server3 can replicate to eachother, but put object to cluster1-server2 or cluster2-server4 can not replicate.  then I guess replication maybe need config on server2 to server 4, but it doesn't work when configured.
## Steps to Reproduce (for bugs)

1.minio version RELEASE.2021-02-19T04-38-02Z
   mc version RELEASE.2021-02-19T05-34-40Z

2.mc replicate ls cluster1/dwbcbucket --json

> {
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0ef1e60r43vsi8180eg",
  "Status": "Enabled",
  "Priority": 1,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}
{
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0rh2881aohe66aacpog",
  "Status": "Enabled",
  "Priority": 3,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}

mc replicate ls cluster2/dwbcbucket --json

> {
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0ef1vvintdfsguf44ng",
  "Status": "Enabled",
  "Priority": 2,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}
{
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0rh33tgd44ful27tiu0",
  "Status": "Enabled",
  "Priority": 4,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}

## Context

[Pass] put object1 to cluster1/dwbcbucket on server1, object1 replicate to cluster2/dwbcbucket
[Pass] put object2 to cluster2/dwbcbucket on server3, object2 replicate to cluster1/dwbcbucket
[Fail] put object1 to cluster1/dwbcbucket on server2, object1 replicate to cluster2/dwbcbucket
[Fail] put object1 to cluster2/dwbcbucket on server4, object1 replicate to cluster1/dwbcbucket

## Your Environment

I have tested on four CentOS 7.6 server use minio binary version RELEASE.2021-02-19T04-38-02Z.

**Comment by poornas** [comment]
can you share your startup command for these clusters/docker compose if any? Also would like to see what `mc replicate ls server2-alias/dwbcbucket` and `mc admin bucket remote ls server2-alias/dwbcbucket` shows - note that the alias is for the servers where the replication is not happening. 

I tried to repro this with 2 4 node clusters - and do see that replication occurs irrespective of whether it was triggered from the server where the remote target/replication config was added or otherwise. Was there any failure on the clusters/ restart?

**Comment by harshavardhana** [comment]
> "Bucket": "arn:aws:s3:::dwbcbucket",

Doesn't this look wrong @poornas ?

**Comment by poornas** [comment]
if he did not set the --region flag, it would show up like this. That should not be a issue, tested without region locally. Seems like the remote target setting/ replication config is not being propagated to all the servers in cluster somehow

**Comment by poornas** [comment]
btw @sjn939394630, did you add a zone after setting up replication config between server1->server3

**Comment by sjn939394630** [comment]
@poornas it's my cluster configuration, I didn't add any zone after setting up.
1.start sh
cluster1
> export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_PROMETHEUS_AUTH_TYPE="public"
nohup minio server http://10.30.0.{171...172}/data{1...3} >> minio.log 2>&1 &

cluster2

> export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_PROMETHEUS_AUTH_TYPE="public"
nohup minio server http://10.30.0.{173...174}/data{1...3} >> minio.log 2>&1 &

2.server hostname configuration,I did it on each of the four server.

> mc config host add cluster1 http://10.30.0.171:9000 "minio" "minio123"
mc config host add cluster1 http://10.30.0.172:9000 "minio" "minio123"
mc config host add cluster2 http://10.30.0.173:9000 "minio" "minio123"
mc config host add cluster2 http://10.30.0.174:9000 "minio" "minio123"

cat /root/.mc/config.json
server1
> {
	"version": "10",
	"aliases": {
		"cluster1": {
			"url": "http://10.30.0.171:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		},
		"cluster2": {
			"url": "http://10.30.0.173:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		}
	}

server2
> {
	"version": "10",
	"aliases": {
		"cluster1": {
			"url": "http://10.30.0.172:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		},
		"cluster2": {
			"url": "http://10.30.0.174:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		}
	}

server3
>  {
	"version": "10",
	"aliases": {
		"cluster1": {
			"url": "http://10.30.0.171:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		},
		"cluster2": {
			"url": "http://10.30.0.173:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		}
	}

server4
> {
	"version": "10",
	"aliases": {
		"cluster1": {
			"url": "http://10.30.0.172:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		},
		"cluster2": {
			"url": "http://10.30.0.174:9000",
			"accessKey": "minio",
			"secretKey": "minio123",
			"api": "s3v4",
			"path": "auto"
		}
	}

3.remote and replicate command
I did this command on server1
> mc admin bucket remote add cluster1/dwbcbucket http://minio:minio123@10.30.0.173:9000/dwbcbucket --service replication
mc replicate add cluster1/dwbcbucket \
--priority 1 \
--storage-class STANDARD \
--remote-bucket dwbcbucket \
--replicate delete,delete-marker \
--arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

I did this command on server2
> mc admin bucket remote add cluster1/dwbcbucket http://minio:minio123@10.30.0.174:9000/dwbcbucket --service replication
mc replicate add cluster1/dwbcbucket \
--priority 3 \
--storage-class STANDARD \
--remote-bucket dwbcbucket \
--replicate delete,delete-marker \
--arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

I did this command on server3
> mc admin bucket remote add cluster2/dwbcbucket http://minio:minio123@10.30.0.171:9000/dwbcbucket --service replication
mc replicate add cluster2/dwbcbucket \
--priority 2 \
--storage-class STANDARD \
--remote-bucket dwbcbucket \
--replicate delete,delete-marker \
--arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

I did this command on server4
> mc admin bucket remote add cluster2/dwbcbucket http://minio:minio123@10.30.0.172:9000/dwbcbucket --service replication
mc replicate add cluster2/dwbcbucket \
--priority 4 \
--storage-class STANDARD \
--remote-bucket dwbcbucket \
--replicate delete,delete-marker \
--arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket



4.replicate configuration
mc replicate ls cluster1/dwbcbucket --json
Server1 and Server2 have the same result

> {
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0ef1e60r43vsi8180eg",
  "Status": "Enabled",
  "Priority": 1,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}
{
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0rh2881aohe66aacpog",
  "Status": "Enabled",
  "Priority": 3,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}

mc replicate ls cluster2/dwbcbucket --json
Server3 and Server4 have the same result

> {
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0ef1vvintdfsguf44ng",
  "Status": "Enabled",
  "Priority": 2,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}
{
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0rh33tgd44ful27tiu0",
  "Status": "Enabled",
  "Priority": 4,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}

5.remote configuration
mc admin bucket remote ls cluster1/dwbcbucket.
Server1 and Server2 have the same result

> Remote URL               Label Source    ->Target     ARN
http://10.30.0.174:9000        dwbcbucket->dwbcbucket arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

mc admin bucket remote ls cluster2/dwbcbucket.
Server3 and Server4 have the same result

> Remote URL               Label Source    ->Target     ARN
http://10.30.0.172:9000        dwbcbucket->dwbcbucket arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

**Comment by poornas** [comment]
can we back up a bit, and try to get 1-way replication from cluster1-> cluster2 work irrespective of whether server 1 or server2 received the request. 
Could you do `mc replicate rm --all --force alias/dwbcbucket` on all these servers, followed by `mc admin bucket remote alias/dwbcbucket --arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket` to clear all existing config,  then redo the setup from cluster1-server1 -> cluster2-server3. 
Following `mc admin bucket remote add` on server1 - you should be able to view the target set up on server2 of cluster1 when you perform `mc admin bucket remote ls alias/dwbcbucket`
Similarly `mc replicate add` on server1 followed by `mc replicate ls` on server2 should show the replication configuration. 
If above two commands work as expected, the requests received by server1/server2 of cluster1 should be replicated correctly.

**Comment by sjn939394630** [comment]
I tried to reconfigure it agin, But it didn't work, Here's how I do it.

1.I did replicate rm on four server

> mc replicate rm --all --force cluster1/dwbcbucket
mc replicate rm --all --force cluster2/dwbcbucket

mc replicate ls cluster1/dwbcbucket --json

> {
 "status": "error",
 "error": {
  "message": "Unable to list replication configuration",
  "cause": {
   "message": "replication configuration not set",
   "error": {}
  },
  "type": "fatal",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "4",
   "host.lang": "go1.15.7",
   "host.name": "dwrj30171",
   "host.os": "linux",
   "mem.heap.total": "67 MB",
   "mem.heap.used": "4.1 MB",
   "mem.total": "75 MB",
   "mem.used": "4.1 MB"
  }
 }
}

2.I did remote rm on two cluster

> mc admin bucket remote rm cluster1/dwbcbucket --arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket
mc admin bucket remote rm cluster2/dwbcbucket --arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

mc admin bucket remote ls cluster1/dwbcbucket

> No remote targets found for `cluster1/dwbcbucket`

3.add remote on server1

> mc admin bucket remote add cluster1/dwbcbucket http://minio:minio123@10.30.0.173:9000/dwbcbucket --service replication
Remote ARN = `arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket`.

mc admin bucket remote ls cluster1/dwbcbucket
server1 and server2 have same result

> Remote URL               Label Source    ->Target     ARN
http://10.30.0.173:9000        dwbcbucket->dwbcbucket arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket

4.add replicate on server1

>  mc replicate add cluster1/dwbcbucket \
> --priority 1 \
> --storage-class STANDARD \
> --remote-bucket dwbcbucket \
> --replicate delete,delete-marker \
> --arn arn:minio:replication::518ceee96bcf0a3f6e6a847a056f2391327d0d63af034206fc7b4ae03f290f90:dwbcbucket
Replication configuration rule applied to cluster1/dwbcbucket successfully.

 mc replicate ls cluster1/dwbcbucket --json
server1 and server2 have same result

> {
 "op": "",
 "status": "success",
 "url": "",
 "rule": {
  "ID": "c0s6c560r43rd04t3qt0",
  "Status": "Enabled",
  "Priority": 1,
  "DeleteMarkerReplication": {
   "Status": "Enabled"
  },
  "DeleteReplication": {
   "Status": "Enabled"
  },
  "Destination": {
   "Bucket": "arn:aws:s3:::dwbcbucket",
   "StorageClass": "STANDARD"
  },
  "Filter": {
   "And": {},
   "Tag": {}
  },
  "SourceSelectionCriteria": {
   "ReplicaModifications": {
    "Status": ""
   }
  }
 }
}

5.I use golang sdk get minioClient to put object on server1, then find object in server1.

> mc find cluster1/dwbcbucket --newer-than 30m
cluster1/dwbcbucket/storeKey1614309183505398001

And then I find this object in server3, replicate successful.
> mc find cluster2/dwbcbucket --newer-than 30m
cluster1/dwbcbucket/storeKey1614309183505398001

But when I get server2 minioClient to put object, still not replicate success.
find in server1
> mc find cluster1/dwbcbucket --newer-than 30m
cluster1/dwbcbucket/storeKey1614309183505398001
cluster1/dwbcbucket/storeKey1614309497152600701

find in server3
> mc find cluster2/dwbcbucket --newer-than 30m
cluster2/dwbcbucket/storeKey1614309183505398001

find object by name on server3 had no result
> mc find cluster2/dwbcbucket --name "storeKey1614309497152600701"

**Comment by sjn939394630** [comment]
I found that the objects uploaded through server2 are finally replicate to cluster2, but it is not real-time.
I waited two hours and then checked the objects in server3 and found that the replicate came, but the specific delay time is not clear.
But objects uploaded through server1 replicate to cluster2 in real-time.

**Comment by harshavardhana** [comment]
> I found that the objects uploaded through server2 are finally replicate to cluster2, but it is not real-time.
> I waited two hours and then checked the objects in server3 and found that the replicate came, but the specific delay time is not clear.

Most probably there is something in the cluster2 logs that you can share @sjn939394630 ? - looks like your cluster2 is not setup properly.

**Comment by sjn939394630** [comment]
@harshavardhana I uploaded a file to server2 at 1:58, then server3 output three logs at 12:01. So do I need to configure replicate on server3?

API: SYSTEM()
Time: 14:01:54 CST 02/26/2021
DeploymentID: 0db4f243-7173-4c10-b0e8-88b95a89315b
Error: The replication configuration was not found: dwbcbucket (cmd.BucketReplicationConfigNotFound)
       2: cmd/bucket-replication.go:573:cmd.replicateObject()
       1: cmd/bucket-replication.go:822:cmd.(*replicationState).addWorker.func1()

API: SYSTEM()
Time: 14:01:59 CST 02/26/2021
DeploymentID: 0db4f243-7173-4c10-b0e8-88b95a89315b
Error: The replication configuration was not found: dwbcbucket (cmd.BucketReplicationConfigNotFound)
       2: cmd/bucket-replication.go:573:cmd.replicateObject()
       1: cmd/bucket-replication.go:822:cmd.(*replicationState).addWorker.func1()

API: SYSTEM()
Time: 14:02:09 CST 02/26/2021
DeploymentID: 0db4f243-7173-4c10-b0e8-88b95a89315b
Error: The replication configuration was not found: dwbcbucket (cmd.BucketReplicationConfigNotFound)
       2: cmd/bucket-replication.go:573:cmd.replicateObject()
       1: cmd/bucket-replication.go:822:cmd.(*replicationState).addWorker.func1()

**Comment by poornas** [comment]
@sjn939394630 , the logs that you see on server 3 can be ignored - it is because your earlier replication configuration was set to 2-way and some objects that were uploaded to cluster2 had failed replication to cluster1 and are being re-tried. If you setup the replication from cluster 2 to cluster 1, those objects should get replicated.

In general replication is asynchronous and it may not be instantaneous - it depends on network bandwidth, number of requests hitting your server, and the size of your namespace can also affect how quickly the scanner can catch up on those replication requests that need to be re-tried You could also set --sync flag while setting up `mc admin bucket remote add` if synchronous replication should be attempted.
`mc stat   cluster1/dwbcbucket/storeKey1614309497152600701` on the object would show status of replication. It will change from `PENDING` to `COMPLETED` or `FAILED` after replication attempt.

**Comment by sjn939394630** [comment]
@poornas I upload this object at 13:58, Until 15:15 is still PENDING, Minio cluster did not do other work during this period, Is this abnormal?

> Name      : dwbcbucket/storeKey1614319104089545601
Date      : 2021-02-26 13:58:24 CST 
Size      : 476 B  
ETag      : 979f182d36cb885eb0453ba73f988d95 
VersionID : d88a0e71-a56d-4801-81f0-97f687d88a33 
Type      : file 
Metadata  :
  Content-Type: application/txt 
Replication Status: PENDING

**Comment by klauspost** [comment]
@sjn939394630 Yes, that is normal. Pending files will be picked up by the crawler/scanner. Depending on your number of objects that can take a while.

**Comment by harshavardhana** [comment]
@sjn939394630 how many objects do you have?  - your cluster2 on different hardware than cluster1 ?

**Comment by poornas** [comment]
can you paste output of `mc admin top locks server2alias` ?

**Comment by sjn939394630** [comment]
@poornas I changed the replicate strategy to --sync, Now the files uploaded to server2 can be replicate real-time. But this will definitely affect the efficiency of file upload，Is there a way to optimize the asynchronous replication strategy?
There are about 2500 objects in my bucket.

> mc admin top locks cluster1
Time                  Type    Resource
113 hours             WRITE   .minio.sys/runDataScanner.lock

> mc admin top locks cluster2
Time                  Type    Resource
112 hours             WRITE   .minio.sys/runDataScanner.lock

**Comment by poornas** [comment]
> @sjn939394630 how many objects do you have? - your cluster2 on different hardware than cluster1 ?

How about this?  Did the replication eventually finish at all when initiated from  server2 or not?

**Comment by sjn939394630** [comment]
@poornas There are about 2500 objects in my bucket, The object number of cluster1 and cluster2 is almost the same and two cluster on different hardware. Objects under the asynchronous replication strategy will eventually replicate successfully, but the replication time is uncontrollable.

**Comment by poornas** [comment]
What is the difference in hardware here? Replication initializes 100 workers by default to handle the replication load - this can be tweaked via `mc admin config set alias api replication_workers=` to increase/decrease the number of workers needed, however I am wondering here whether your second server is having sufficient memory available to handle replication requirements. Were you trying to replicate all 2500 objects uploaded to your bucket at the same time? How many buckets are there in this cluster?

**Comment by sjn939394630** [comment]
The two clusters are different virtual machines on the same hardware, and there is no difference in configuration. Most of the 2500 objects have been replicated, and only 5 or less are waiting for replicate. I have two buckets in cluster, most of objects in dwbcbucket, another bucket have less than ten objects

**Comment by harshavardhana** [comment]
It clearly looks like your cluster2 is not able to handle the load for some reason even at a really lower scale. I suspect you should look at your setup. 

If cluster1 can replicate it should be possible for cluster2 to do the same without the long wait - either there is some random network issue that happens due to replication / i.e load  - your cluster1 and cluster2 are clearly different in some fundamental setup config.  

We have tried multiple variations locally can see that two different clusters with the same configuration behave without much issues. 

If you really want us to dig further we can help architecture your solution https://min.io/pricing - we regularly architecture these types of deployments before they go to production. So we are happy to help you there. 

For now, I think replication is working fine, and let's close this issue.
