### ISSUE TITLE
SSL with docker no longer works on any port but 443

### ISSUE THREAD

**Issue by TimCook1** [minio/minio#11639]
When attempting to run minio via docker on port 9000 with SSL, minio completely ignores the certificates and will only allow access via http.  The only way to get it to actually utilize the certs is by launching it as root with --address ":443"

## Expected Behavior
I would expect if I put the private.key and public.crt in the certs directory I map to /root/.minio, that I can access the instance via https://ipaddres:9000

## Current Behavior
Minio completely ignores the certificates and is only available via http://ipaddress:9000

It works exactly as expected if you launch it mapping port 443 and adding 'server --address ":443"'

However this requires launching as root due to utilizing a port under 1024 - I don't want to run this as root.

## Steps to Reproduce (for bugs)

1. generate certificates with a command like:
      openssl req -new -x509 -nodes -days 365 -key private.key -out public.crt -config openssl.conf

2. place files into /mnt/config/certs/ (or similar directory that your non-root user has access to)

3. launch minio as non-root user

docker run -p 9000:9000 \
  --user $(id -u):$(id -g) \
  --name minio \
  -e "MINIO_ROOT_USER=YOURUSER" \
  -e "MINIO_ROOT_PASSWORD=YOURPASS" \
  -v /mnt/config:/root/.minio \
  -v /minio_disk01:/data1 \
  -v /minio_disk02:/data2 \
  -v /minio_disk03:/data3 \
  -v /minio_disk04:/data4 \
  -v /minio_disk05:/data5 \
  -v /minio_disk06:/data6 \
  -v /minio_disk07:/data7 \
  -v /minio_disk08:/data8 \
  -v /minio_disk09:/data9 \
  -v /minio_disk10:/data10 \
  -v /minio_disk11:/data11 \
  -v /minio_disk12:/data12 \
  minio/minio server /data{1...12}

## Context
At this point it's basically impossible to access minio via SSL if you want more than one instance or a non-root user without setting up an nginx proxy (or similar)

## Regression
Yes, this appears to be a regression given there are countless posts on github and around the net with pople utilizing ssl and port 9000.  I don't know specifically what broke it.

## Your Environment

latest docker pull from today - minio/minio latest
Ubuntu 20.04.2 LTS updated today
Docker version 19.03.8, build afacb8b7f0

**Comment by harshavardhana** [comment]
> docker run -p 9000:9000
> --user $(id -u):$(id -g)
> --name minio
> -e "MINIO_ROOT_USER=YOURUSER"
> -e "MINIO_ROOT_PASSWORD=YOURPASS"
> -v /mnt/config:/root/.minio

If you run as a user you need to put the certs at `/home/user/.minio` @TimCook1

**Comment by harshavardhana** [comment]
> * place files into /mnt/config/certs/ (or similar directory that your non-root user has access to)
> *

You didn't specify `--certs-dir` folder if you are using non-standard path

**Comment by TimCook1** [comment]
So I can tell you what I just tried:

My certs are in /mnt/config/certs and owned by user tim

Logging in as user "tim":

docker run -p 9000:9000
--user $(id -u):$(id -g)
--name minio
-e "MINIO_ROOT_USER=YOURUSER"
-e "MINIO_ROOT_PASSWORD=YOURPASS"
-v /mnt/config:/home/tim/.minio

(plus all the disk mapping)

This still doesn't pick up the certs.  If I'm mapping /mnt/config to /home/tim/.minio, why would I also be adding a --certs-dir.  Isn't "certs" the default directory?

**Comment by harshavardhana** [comment]
> So I can tell you what I just tried:
> 
> My certs are in /mnt/config/certs and owned by user tim
> 
> Logging in as user "tim":
> 
> docker run -p 9000:9000
> --user $(id -u):$(id -g)
> --name minio
> -e "MINIO_ROOT_USER=YOURUSER"
> -e "MINIO_ROOT_PASSWORD=YOURPASS"
> -v /mnt/config:/home/tim/.minio
> 
> (plus all the disk mapping)
> 
> This still doesn't pick up the certs. If I'm mapping /mnt/config to /home/tim/.minio, why would I also be adding a --certs-dir. Isn't "certs" the default directory?

Okay it won't work like this 

```
~ docker run -p 9000:9000 --rm --user $(id -u):$(id -g) --name minio -e "MINIO_ROOT_USER=YOURUSER" -e "MINIO_ROOT_PASSWORD=YOURPASS" -v ~/.minio:/.minio minio/minio server --help
NAME:
  minio server - start object storage server

USAGE:
  minio server [FLAGS] DIR1 [DIR2..]
  minio server [FLAGS] DIR{1...64}
  minio server [FLAGS] DIR{1...64} DIR{65...128}

DIR:
  DIR points to a directory on a filesystem. When you want to combine
  multiple drives into a single large system, pass one directory per
  filesystem separated by space. You may also use a '...' convention
  to abbreviate the directory arguments. Remote directories in a
  distributed setup are encoded as HTTP(s) URIs.

FLAGS:
  --address value              bind to a specific ADDRESS:PORT, ADDRESS can be an IP or hostname (default: ":9000")
  --certs-dir value, -S value  path to certs directory (default: "/.minio/certs")
  --quiet                      disable startup information
  --anonymous                  hide sensitive information from logging
  --json                       output server logs and startup information in json format
  --help, -h                   show help
  
```

See what your default directory? - then pass like this 

``` docker run -p 9000:9000 --rm --user $(id -u):$(id -g) --name minio -e "MINIO_ROOT_USER=YOURUSER" -e "MINIO_ROOT_PASSWORD=YOURPASS" -v ~/.minio:/.minio minio/minio server /tmp/data
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint: https://172.17.0.3:9000  https://127.0.0.1:9000       

Browser Access:
   https://172.17.0.3:9000  https://127.0.0.1:9000      
```

If you want a custom folder 

```
~ docker run -p 9000:9000 --rm --user $(id -u):$(id -g) --name minio -e "MINIO_ROOT_USER=YOURUSER" -e "MINIO_ROOT_PASSWORD=YOURPASS" -v ~/.minio/certs:/tmp/certs minio/minio server --certs-dir /tmp/certs /tmp/data
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint: https://172.17.0.3:9000  https://127.0.0.1:9000  
```

There is no `/home` for your user so we just have to stick to `/` inside the container. 
~
