### ISSUE TITLE
The O_DIRECT check runs ~10 times/second

### ISSUE THREAD

**Issue by solsson** [minio/minio#11643]
On an 8 disk statefulset running in Kubernetes, logs show about 10 entries per second of [Drive <drive> does not support O_DIRECT for reads, proceeding to use the drive without O_DIRECT](https://github.com/minio/minio/blob/RELEASE.2021-02-24T18-44-45Z/cmd/xl-storage.go#L298). Not a big issue but I notice that this check runs in a function `newXLStorage` which I suppose shouldn't run that often, and the CPU usage seems to have increased by 50-100% after the upgrade from RELEASE.2020-09-10T22-02-45Z.

## Expected Behavior
The info entry should show up once per minio instance, drive or bucket? The degradation to not using O_DIRECT is correct.

## Current Behavior
Verbose logs and increased CPU usage.

## Context
I'm fine with this being the expected behavior for environments that don't support O_DIRECT, but I thought I'd better report this issue because if the increased CPU usage (which could very well be due to other changes between RELEASE.2020-09-10T22-02-45Z and now).

AFAIK we haven't configured any non-standard storage class anywhere.

## Regression
Yes

## Your Environment
* Version used (`minio --version`): RELEASE.2021-02-24T18-44-45Z
* Server setup and configuration: GKE, cos_containerd nodes, Kubernetes v1.18.12-gke.1210, PD_SSD drives ext4
* Operating System and version (`uname -a`): glcoud [cos](https://cloud.google.com/container-optimized-os/), `Linux gke-g2-standard01-c23d1e34-wu1p 5.4.49+ #1 SMP Sun Oct 18 19:43:35 PDT 2020 x86_64 AMD EPYC 7B12 AuthenticAMD GNU/Linux`

**Comment by klauspost** [comment]
This is likely from the  [metrics](https://github.com/minio/minio/blob/98d3f94996d229831a7a9d0dae38858674442735/cmd/metrics-v2.go#L1081) recreating the storage.

Instead of recreating it should use the existing storage running on the server.

**Comment by harshavardhana** [comment]
> This is likely from the [metrics](https://github.com/minio/minio/blob/98d3f94996d229831a7a9d0dae38858674442735/cmd/metrics-v2.go#L1081) recreating the storage.
> 
> Instead of recreating it should use the existing storage running on the server.

Yes @klauspost

**Comment by harshavardhana** [comment]
fixed in #11647
