### ISSUE TITLE
Anonymous LDAP user lookup

### ISSUE THREAD

**Issue by bo5o** [minio/minio#11646]
When using AssumeRoleWithLDAPIdentity and Lookup-Bind Mode, it is required to set MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD. The password is then checked to be not empty (see https://github.com/minio/minio/blob/02e7de6367874b320c7ddee3f96a706fe322bfa7/cmd/config/identity/ldap/config.go#L425). This makes it impossible to use an 'anonymous' user as lookup DN, which some workflows require.

I'd suggest just removing the check and allowing empty passwords.

**Comment by harshavardhana** [comment]
@cbows can you provide more details on your setup?  please provide your ldif configuration file as well - this would help us look at the issue.

**Comment by bo5o** [comment]
[RFC 4513 Section 5.1.1](https://tools.ietf.org/html/rfc4513#section-5.1.1) describes 'anonymous bind' to authenticate against a directory server. Anonymous bind is a simple bind with a zero-length DN and/or zero-length password. There are various use-cases for anonymous binds, in my case, it is used to provide some kind of 'public' access to the directory server to lookup DNs.

A configuration could look like this:
```
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="<empty or not>"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=""
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="o=MyOrg"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(|(uid=%s)(...)(...))"
```

Currently however, this configuration wouldn't pass this line https://github.com/minio/minio/blob/02e7de6367874b320c7ddee3f96a706fe322bfa7/cmd/config/identity/ldap/config.go#L425 and thus not allowing anonymous binds.

EDIT: In case empty bind DN and password are given, another config option is probably needed. Something like `MINIO_IDENTITY_LDAP_LOOKUP_ANONYMOUS_BIND=on/off`.

**Comment by bo5o** [comment]
I gave it a try #11655

**Comment by harshavardhana** [comment]
> EDIT: In case empty bind DN and password are given, another config option is probably needed. Something like `MINIO_IDENTITY_LDAP_LOOKUP_ANONYMOUS_BIND=on/off`.

Let's change the option to be 

> MINIO_IDENTITY_LDAP_LOOKUP_BIND_ANONYMOUS=on

Instead of 

> MINIO_IDENTITY_LDAP_LOOKUP_ANONYMOUS_BIND
