### ISSUE TITLE
Can't download files bigger than 100 MiB via s3fs-fuse 1.18 from minio RELEASE.2021-02-24T18-44-45Z

### ISSUE THREAD

**Issue by weisdd** [minio/minio#11651]
In versions up to `RELEASE.2021-02-23T20-05-01Z` (included), it was possible to use s3fs-fuse (1.88) for minio backups. - We would mount all buckets and then run restic to archive everything.
When we upgraded from `RELEASE.2021-02-19T04-38-02Z` to `RELEASE.2021-02-24T18-44-45Z`, we found out that it was no longer possible to copy files over 100 MiB. E.g. simple `cp` would fail with `read error: I/O error`. At the same time, `mc cp` works fine.
After downgrade to `RELEASE.2021-02-19T04-38-02Z` / `RELEASE.2021-02-23T20-05-01Z`, everything's fine again.

So, from s3fs' point of view, there's definitely a regression in compatibility with earlier versions of minio. I'm not aware whether you care about third-party software, though I'm pretty sure I'm not going to be the only one complaining about the issue described above.

The issue affects minio running in erasure mode (4 x nodes). With one node, everything's fine.

## Expected Behavior

Copy/Read operations for files bigger than 100 MiB should work fine.

## Current Behavior

s3fs `1.18` can't handle copy operations for files bigger than 100 MiB from minio running in erasure mode (4 nodes), version `RELEASE.2021-02-19T04-38-02Z`

## Steps to Reproduce (for bugs)

1. Prepare a 4 x node minio cluster, create a bucket named `gitlab-backups` (or whatever you want).

2. Run the following steps on Ubuntu 20.04 LTS (other distros might require different flags for docker security options):

```shell
docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined alpine:3.13

apk add --no-cache fuse
apk add s3fs-fuse=1.88-r0 --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
echo ACCESSKEY:SECRETKEY > ${HOME}/.passwd-s3fs
chmod 600 ${HOME}/.passwd-s3fs
mkdir -p /backups/gitlab-backups
s3fs gitlab-backups /backups/gitlab-backups -o url=http://minio.localhost -o passwd_file=${HOME}/.passwd-s3fs -o use_path_request_style -o ro -o enable_noobj_cache -o max_stat_cache_size=200000 -o complement_stat -o no_check_certificate -f -o dbglevel=info -f -o curldbg
```

3. In a separate console, exec into the container with s3fs:
```shell
docker exec -it <ID> sh
```

4. Try to copy the file:
```shell
cp /backups/gitlab-backups/1.tar /tmp
```
  The operation should fail.

## Regression
**Is this issue a regression?**
Yes

## Your Environment
* Version used (`minio --version`): `RELEASE.2021-02-24T18-44-45Z` 
* Server setup and configuration: distributed / 4 nodes, nothing fancy.
* Operating System and version (`uname -a`): Ubuntu 20.04 LTS `Linux a4133737586c 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 Linux`. Have the same issue on other distros.

Attached the following files:

RELEASE.2021-02-19T04-38-02Z:
* [fine-minio.log](https://github.com/minio/minio/files/6054319/fine-minio.log)
* [fine-s3fs.log](https://github.com/minio/minio/files/6054320/fine-s3fs.log)

RELEASE.2021-02-23T20-05-01Z
* [fine2-minio.log](https://github.com/minio/minio/files/6054317/fine2-minio.log)
* [fine2-s3fs.log](https://github.com/minio/minio/files/6054318/fine2-s3fs.log)

RELEASE.2021-02-24T18-44-45Z 
* [issue-minio.log](https://github.com/minio/minio/files/6054321/issue-minio.log)
* [issue-s3fs.log](https://github.com/minio/minio/files/6054322/issue-s3fs.log)

**Comment by weisdd** [comment]
@gaul @ggtakec @rrizun just in case you'd like to take a look at s3fs-fuse traces.

**Comment by ggtakec** [comment]
@weisdd
It seems that s3fs is receiving the result of a curl call called CURLE_PARTIAL_FILE.
This is the last line of the log shown below.
```
[CURL DBG] > GET /gitlab-backups/1614387609_2021_02_27_13.7.4_gitlab_backup.tar HTTP/1.1
[CURL DBG] > Host: minio.localhost
[CURL DBG] > User-Agent: s3fs/1.88 (commit hash unknown; OpenSSL)
[CURL DBG] > Accept: */*
[CURL DBG] > Authorization: ...
   ...
   ...
[CURL DBG] * Mark bundle as not supporting multiuse
[CURL DBG] < HTTP/1.1 206 Partial Content
[CURL DBG] < Server: openresty/1.15.8.1
[CURL DBG] < Date: Sat, 27 Feb 2021 11:19:10 GMT
[CURL DBG] < Content-Type: application/x-tar
[CURL DBG] < Content-Length: 10485760
[CURL DBG] < Connection: keep-alive
[CURL DBG] < Accept-Ranges: bytes
[CURL DBG] < Content-Range: bytes 125829120-136314879/767477760
[CURL DBG] < Content-Security-Policy: block-all-mixed-content
[CURL DBG] < ETag: "b4067a7c8a139f5f3b56290ba924eb97-6"
[CURL DBG] < Last-Modified: Sat, 27 Feb 2021 11:05:58 GMT
[CURL DBG] < Vary: Origin
[CURL DBG] < X-Amz-Request-Id: 166796C1CC8C24BB
[CURL DBG] < X-Xss-Protection: 1; mode=block
[CURL DBG] <
[CURL DBG] * transfer closed with 2097152 bytes remaining to read
```
That means that it was closed before receiving the remaining bytes.
And I found a problem similar to stackoverflow.
There seems to be some suspicious parts such as the network between servers.
https://stackoverflow.com/questions/30026326/curle-partial-file-error-for-large-files-with-libcurl

It seems unlikely that you have a problem with s3fs, so check these servers and networks just in case.
Thanks in advance for your assistance.

**Comment by harshavardhana** [comment]
@weisdd can you try starting server with MINIO_STORAGE_CLASS_DMA=write and retry your tests ?

**Comment by harshavardhana** [comment]
Okay so It tried with the latest MinIO master and 02-24 and unable to reproduce this 

```
[CURL DBG] * Mark bundle as not supporting multiuse
[CURL DBG] < HTTP/1.1 206 Partial Content
[CURL DBG] < Accept-Ranges: bytes
[CURL DBG] < Content-Length: 10485760
[CURL DBG] < Content-Range: bytes 52428800-62914559/104857600
[CURL DBG] < Content-Security-Policy: block-all-mixed-content
[CURL DBG] < Content-Type: application/x-tar
[CURL DBG] < ETag: "0c4af570340e15f2be9924e70bc34257-13"
[CURL DBG] < Last-Modified: Sat, 27 Feb 2021 17:45:02 GMT
[CURL DBG] < Server: MinIO
[CURL DBG] < Vary: Origin
[CURL DBG] < X-Amz-Request-Id: 1667ABD4A444142B
[CURL DBG] < X-Xss-Protection: 1; mode=block
[CURL DBG] < Date: Sat, 27 Feb 2021 17:45:21 GMT
[CURL DBG] < 
[CURL DBG] * Mark bundle as not supporting multiuse
[CURL DBG] < HTTP/1.1 206 Partial Content
[CURL DBG] < Accept-Ranges: bytes
[CURL DBG] < Content-Length: 10485760
[CURL DBG] < Content-Range: bytes 73400320-83886079/104857600
[CURL DBG] < Content-Security-Policy: block-all-mixed-content
[CURL DBG] < Content-Type: application/x-tar
[CURL DBG] < ETag: "0c4af570340e15f2be9924e70bc34257-13"
[CURL DBG] < Last-Modified: Sat, 27 Feb 2021 17:45:02 GMT
[CURL DBG] < Server: MinIO
[CURL DBG] < Vary: Origin
[CURL DBG] < X-Amz-Request-Id: 1667ABD4A4281250
[CURL DBG] < X-Xss-Protection: 1; mode=block
[CURL DBG] < Date: Sat, 27 Feb 2021 17:45:21 GMT
[CURL DBG] < 
[CURL DBG] * Connection #1 to host localhost left intact
[INF]       curl.cpp:RequestPerform(2267): HTTP response code 206
[CURL DBG] * Connection #1 to host localhost left intact
[INF]       curl.cpp:RequestPerform(2267): HTTP response code 206
[CURL DBG] * Connection #1 to host localhost left intact
[INF]       curl.cpp:RequestPerform(2267): HTTP response code 206
[CURL DBG] * Connection #1 to host localhost left intact
[INF]       curl.cpp:RequestPerform(2267): HTTP response code 206
[CURL DBG] * Connection #1 to host localhost left intact
[INF]       curl.cpp:RequestPerform(2267): HTTP response code 206
[INF] s3fs.cpp:s3fs_getattr(778): [path=/bigfile.tar]
[INF] s3fs.cpp:s3fs_flush(2320): [path=/bigfile.tar][fd=11]
[INF]       fdcache_entity.cpp:RowFlush(1194): [tpath=][path=/bigfile.tar][fd=11]
[INF] s3fs.cpp:s3fs_release(2377): [path=/bigfile.tar][fd=11]
[INF]       fdcache.cpp:GetFdEntity(409): [path=/bigfile.tar][fd=11]
```

```
~ aws --endpoint-url http://localhost:9001 --profile minio s3 cp ./bigfile.tar s3://gitlab-backups/ 
upload: ./bigfile.tar to s3://gitlab-backups/bigfile.tar
```

```
~ /backups/gitlab-backups # cp bigfile.tar /tmp/
```

**Comment by harshavardhana** [comment]
I see that you are also proxing the requests, to limit variation can you directly talk to MinIO on a port and see the results are same with different versions?

**Comment by harshavardhana** [comment]
So I ended up trying more number of configurations, I can't seem to reproduce it.

It would be worth for us if you show me how MinIO is deployed, any docker or k8s configuration that is used etc.  For now not sure what you are seeing right now.

**Comment by weisdd** [comment]
@ggtakec thanks!

@harshavardhana thanks for the replies.

So, first of all, a few words about environment:
I've got two different clusters for tests:
* SLES 12 SP5, Kubernetes `1.18.8`, Local Volumes (LVM, `xfs`, CSI: `topolvm`), 4 x minio nodes, nginx ingress controller;
* Ubuntu 20.04 LTS, Kubernetes `1.18.16` (microk8s, `snap install microk8s --classic --channel=1.18/edge`), Local Volumes (Hostpath, `ext4`), 4 x minio nodes, nginx ingress controller;
The only extra configuration I pass is: `MINIO_API_READY_DEADLINE: "5s"` and `MINIO_PROMETHEUS_AUTH_TYPE: "public"`. There's nothing special about docker runtime either.

1. Check [`edge` image](https://hub.docker.com/layers/minio/minio/edge-cicd/images/sha256-ff23b323f7767e2333a9134fa68c29ddbafa680b3850921f2cdcaeccae557e22?context=explore):
=> No changes.

2. Check with direct connection:
=> Tried with both `NodePort` and `Service`, no changes.

3. Check `MINIO_STORAGE_CLASS_DMA: write`:
=> It helped.

I'll check if I hit the same issue in pure docker environment (docker-compose) without `MINIO_STORAGE_CLASS_DMA: write` being set.

**Comment by harshavardhana** [comment]
> 3\. Check `MINIO_STORAGE_CLASS_DMA: write`:
>     => It helped.

Are you saying it worked? @weisdd on both the releases?

**Comment by harshavardhana** [comment]
> * SLES 12 SP5, Kubernetes `1.18.8`, Local Volumes (LVM, `xfs`, CSI: `topolvm`), 4 x minio nodes, nginx ingress controller;
> * Ubuntu 20.04 LTS, Kubernetes `1.18.16` (microk8s, `snap install microk8s --classic --channel=1.18/edge`), Local Volumes (Hostpath, `ext4`), 4 x minio nodes, nginx ingress controller;
>   The only extra configuration I pass is: `MINIO_API_READY_DEADLINE: "5s"` and `MINIO_PROMETHEUS_AUTH_TYPE: "public"`. There's nothing special about docker runtime either.

Also, did you reproduce this on both XFS and ext4?

**Comment by weisdd** [comment]
@harshavardhana yes, the issue disappears for both `RELEASE.2021-02-24T18-44-45Z` and `edge` running on the two above-mentioned clusters (meaning, `ext4`, `xfs` as backend storage) once I pass them `MINIO_STORAGE_CLASS_DMA: write`.

Could you, please, explain a bit what can we make out of this observation? What effect does the `MINIO_STORAGE_CLASS_DMA: write` have under the hood?

**Comment by harshavardhana** [comment]
> @harshavardhana yes, the issue disappears for both `RELEASE.2021-02-24T18-44-45Z` and `edge` running on the two above-mentioned clusters (meaning, `ext4`, `xfs` as backend storage) once I pass them `MINIO_STORAGE_CLASS_DMA: write`.
> 
> Could you, please, explain a bit what can we make out of this observation? What effect does the `MINIO_STORAGE_CLASS_DMA: write` have under the hood?

@weisdd mainly the failure is in O_DIRECT reads (default is read+write) here perhaps something to do with backend FS but I can't reproduce this locally on XFS. So there is something to do with k8s environment as well.

If you can try a debug build it will help me - would you be interested?

**Comment by weisdd** [comment]
@harshavardhana sure, I'd love to help :) Though, I'll run it only in microk8s cluster as the other one is used by other folks, so better to limit experiments with it.

I've tried docker-compose with bind-mounts, worked fine. :/

I'll try to create an environment using multipass + ubuntu 20.04 LTS + microk8s. So, hopefully, you'll get a repro in your lab as well.

**Comment by harshavardhana** [comment]
> I've tried docker-compose with bind-mounts, worked fine. :/

This worked fine without any special options? @weisdd

**Comment by harshavardhana** [comment]
> I'll try to create an environment using multipass + ubuntu 20.04 LTS + microk8s. So, hopefully, you'll get a repro in your lab as well.

Yes, this looks very environment-specific and looks rare so now I am more curious what we are missing.

**Comment by weisdd** [comment]
@harshavardhana yep, without touching `MINIO_STORAGE_CLASS_DMA`, just took your official docker-compose manifest, and it worked.

**Comment by icecrypt7** [comment]
I had a similar issue with the latest version and had no choice to downgrade.
It's related to byte-range requests which Minio doesn't serve right ( which had changes in recent versions ).
for example with 1gb file, I did a byte range 100MB-200MB request via curl directly to Minio and it responded around 90M and every time it was exactly same byte (e.g. returned 94342000 bytes) or with 10MB-20MB range responded around 500kb and then Minio closes connection.

Environment: Distributed & Erasure coding, 4 Nodes with 4 Disks each, CentOS7, XFS, Binary Minio RELEASE.2021-02-24T18-44-45Z

**Comment by weisdd** [comment]
@ahledl of, wow, thanks for sharing that :) I'm about to post a lab, so @harshavardhana will have a chance to take a look at the issue.

**Comment by harshavardhana** [comment]
> I had a similar issue with the latest version and had no choice to downgrade.
> It's related to byte-range requests which Minio doesn't serve right ( which had changes in recent versions ).
> for example with 1gb file, I did a byte range 100MB-200MB request via curl directly to Minio and it responded around 90M and every time it was exactly same byte (e.g. returned 94342000 bytes) or with 10MB-20MB range responded around 500kb and then Minio closes connection.
> 
> Environment: Distributed & Erasure coding, 4 Nodes with 4 Disks each, CentOS7, XFS, Binary Minio RELEASE.2021-02-24T18-44-45Z

@ahledl that doesn't make sense really as we already tried in various other situations and we are not able to do it precisely in all situations -  can you try `MINIO_STORAGE_CLASS_DMA=write` and see if that helps?

**Comment by weisdd** [comment]
@harshavardhana
First, you need to install [multipass](https://multipass.run/), then go through the following steps:

```shell
# Create a virtual machine with Ubuntu 20.04 on board
multipass launch focal -n minio-s3fs -m 4G -c 2 -d 15G

# Enter the VM
multipass shell minio-s3fs

cat << EOF > prepare-lab.sh
#!/usr/bin/env bash
set -euo pipefail
# Install microk8s and configure environment
sudo snap install microk8s --classic --channel=1.18/edge
sudo microk8s status --wait-ready
sudo usermod -a -G microk8s ubuntu
mkdir -p .kube
sudo microk8s config > .kube/config
sudo chown -f -R ubuntu ~/.kube
chmod 600 .kube/config
curl -LO https://dl.k8s.io/release/v1.18.16/bin/linux/amd64/kubectl
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
echo 'source <(kubectl completion bash)' >>~/.bashrc
echo 'alias k=kubectl' >>~/.bashrc
echo 'complete -F __start_kubectl k' >>~/.bashrc

# Enable plugins
sudo microk8s.enable dns rbac storage metrics-server

# Install helm
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
helm repo add minio https://helm.min.io/
helm repo update

# Install minio, wait till it's ready
kubectl create ns minio
kubectl config set-context --current --namespace=minio
helm install --wait --timeout 10m --set accessKey=minio,secretKey=minio123,mode=distributed,replicas=4,resources=null,service.type=NodePort,image.tag=RELEASE.2021-02-24T18-44-45Z --namespace minio minio minio/minio

# Install docker
sudo apt update && sudo apt install -y docker.io
sudo usermod -a -G docker ubuntu

# Install mc, create a bucket, and put a big file into it
curl -LO https://dl.min.io/client/mc/release/linux-amd64/mc
sudo install -o root -g root -m 0755 mc /usr/local/bin/mc
sleep 30
mc alias set myminio/ http://127.0.0.1:32000 minio minio123
mc mb --ignore-existing myminio/gitlab-backups
dd if=/dev/zero of=file.txt count=200 bs=1048576
mc cp file.txt myminio/gitlab-backups
EOF

chmod +x prepare-lab.sh
./prepare-lab.sh

# Exit the shell, so the changes in user group and environment are applied, enter the VM again
exit
multipass shell minio-s3fs

# Run a docker container with s3fs (you could do that from microk8s as well, though there's no real need for that)
export IP=$(k get svc minio -n minio -o=jsonpath='{.spec.clusterIP}')
docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined -e IP --name s3fs alpine:3.13

# Run these commands inside the container
apk add --no-cache fuse
apk add s3fs-fuse=1.88-r0 --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
echo minio:minio123 > ${HOME}/.passwd-s3fs
chmod 600 ${HOME}/.passwd-s3fs
mkdir -p /backups/gitlab-backups

# If you don't need to see debug output of s3fs, just omit the -f flag - it'll run in the background
s3fs gitlab-backups /backups/gitlab-backups -o url=http://$IP:9000 -o passwd_file=${HOME}/.passwd-s3fs -o use_path_request_style -o ro -o enable_noobj_cache -o max_stat_cache_size=200000 -o complement_stat -o no_check_certificate -o dbglevel=info -f -o curldbg

# Exec into the same container if s3fs is running in the foreground
multipass shell minio-s3fs
docker exec -it s3fs sh

# Copy the file
cp /backups/gitlab-backups/file.txt /tmp
```

**Comment by harshavardhana** [comment]
@weisdd thank you so much - I will get back - are you able to successfully reproduce the error?

**Comment by weisdd** [comment]
@weisdd :) yep, in this lab, I hit the issue every single time :)

**Comment by harshavardhana** [comment]
Okay, it's a server crash (that's why partial data is seen by the client) rare but happens @weisdd

**Comment by weisdd** [comment]
@harshavardhana I'm glad the lab worked for you. Just ping me if there's anything else I can assist you with.

**Comment by harshavardhana** [comment]
Thanks for the brilliant reproducer, found the fix @weisdd - something very simple that was missing.
