### ISSUE TITLE
PUT from s3fs bypass policy rules

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#11658]
Hi, using s3fs as a client the policies set on the accessKey are bypassed, allowing writing despite being forbidden.

$ mc admin policy info local test-policy

```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Sid": "Deny User From Deleting Standard Folders",
   "Effect": "Deny",
   "Action": [
    "s3:DeleteObject"
   ],
   "Resource": [
    "arn:aws:s3:::${aws:username}/in/",
    "arn:aws:s3:::${aws:username}/out/",
   ]
  },
  {
   "Sid": "List bucket",
   "Effect": "Allow",
   "Action": [
    "s3:ListBucket",
    "s3:ListBucketMultipartUploads",
    "s3:ListenBucketNotification",
    "s3:ListenNotification",
    "s3:GetBucketLocation",
    "s3:ListAllMyBuckets"
   ],
   "Resource": [
    "arn:aws:s3:::${aws:username}"
   ]
  },
  {
   "Sid": "in Read/Delete/List",
   "Effect": "Allow",
   "Action": [
    "s3:GetObjectTagging",
    "s3:ListAllMyBuckets",
    "s3:ListBucket",
    "s3:ListMultipartUploadParts",
    "s3:ListenBucketNotification",
    "s3:ListenNotification",
    "s3:DeleteObject",
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::${aws:username}/in/*"
   ]
  },
  {
   "Sid": "out Write,Read/Delete/List",
   "Effect": "Allow",
   "Action": [
    "s3:DeleteObject",
    "s3:ListAllMyBuckets",
    "s3:ListMultipartUploadParts",
    "s3:GetObject",
    "s3:GetObjectTagging",
    "s3:ListBucket",
    "s3:PutObject"
   ],
   "Resource": [
    "arn:aws:s3:::${aws:username}/out/*"
   ]
  }
]
}
```
$ mc admin user info local francesco
AccessKey: francesco
Status: enabled
PolicyName: test-policy
MemberOf: francesco

$ mc admin group info  clusters3 francesco
Group: francesco
Status: enabled
Policy: test-policy
Members: francesco

$ cat /etc/fstab |grep s3fs
s3fs#francesco /mnt/s3 fuse _netdev,allow_other,mp_umask=0022,use_path_request_style,enable_content_md5,nomultipart,curldbg,url=https://3.FQDN:9001/ 0 0

$ cp testfile.txt /mnt/s3/in/

Trace log:

03:42:05.718 [200 OK] s3.PutObject s3.FQDN:9001/francesco/in/test-from-s3fs.txt 192.168.3.10      505.225ms    ↑ 194 B ↓ 230 B
03:42:06.224 [200 OK] s3.HeadObject s3.FQDN:9001/francesco/in/test-from-s3fs.txt 192.168.3.10      14.006ms     ↑ 84 B ↓ 446 B
03:42:06.274 [200 OK] s3.PutObject s3.FQDN:9001/francesco/in/test-from-s3fs.txt 192.168.3.10      367.607ms    ↑ 676 KiB ↓ 230 B

S3FS Curl Debug Log:
```
PUT /francesco/in/testfile.txt HTTP/1.1
Host: s3.FQDN:9001
User-Agent: s3fs/1.88 (commit hash unknown; OpenSSL)
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=GIS6DNWEO9QYNPSU/20210228/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-atime;x-amz-meta-ctime;x-amz-meta-gid;x-amz-meta-mode;x-amz-meta-mtime;x-amz-meta-uid, Signature=471fa244eab7d0cbc06e0f53119531d95af335fd2c338ab3515e43dbad47287c
Content-MD5: 1TjEJVLW/yj59ssgpBNwVw==
Content-Type: application/octet-stream
x-amz-content-sha256: 744946be0b7333b372cf2867df5dfe68140b59ab2a130136fcc2d02c5edbc0a9
x-amz-date: 20210228T035720Z
x-amz-meta-atime: 1614484639
x-amz-meta-ctime: 1614484640
x-amz-meta-gid: 0
x-amz-meta-mode: 33152
x-amz-meta-mtime: 1614484640
x-amz-meta-uid: 0
Content-Length: 67090
Expect: 100-continue

TLSv1.3 (IN), TLS app data, [no content] (0):
HTTP/1.1 100 Continue
TLSv1.3 (OUT), TLS app data, [no content] (0):
TLSv1.3 (OUT), TLS app data, [no content] (0):
TLSv1.3 (OUT), TLS app data, [no content] (0):
TLSv1.3 (OUT), TLS app data, [no content] (0):
TLSv1.3 (OUT), TLS app data, [no content] (0):
We are completely uploaded and fine
TLSv1.3 (IN), TLS app data, [no content] (0):
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
ETag: "d538c42552d6ff28f9f6cb20a4137057"
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1667CD39F7CB24EF
X-Xss-Protection: 1; mode=block
Date: Sun, 28 Feb 2021 03:57:20 GMT
```

$ mc cp test-from-mc.txt cs3/in/
mc: <ERROR> Failed to copy `testfile.txt`. Insufficient permissions to access this file `https://s3.FQDN/francesco/in/testfile.txt`

Tracce Log:
03:45:23.982 [403 Forbidden] s3.PutObject s3.FQDN/francesco/in/test-from-mc.txt 79.xx.xx.xx     556µs       ↑ 117 B ↓ 547 B

## Expected Behavior

Writing Forbidden by all clients

minio -v
minio version RELEASE.2021-02-24T18-44-45Z

**Comment by harshavardhana** [comment]
> PUT /francesco/in/testfile.txt HTTP/1.1
> Host: s3.FQDN:9001
> User-Agent: s3fs/1.88 (commit hash unknown; OpenSSL)
> Accept: */*
> Authorization: AWS4-HMAC-SHA256 Credential=GIS6DNWEO9QYNPSU/20210228/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-atime;x-amz-meta-ctime;x-amz-meta-gid;x-amz-meta-mode;x-amz-meta-mtime;x-amz-meta-uid, Signature=471fa244eab7d0cbc06e0f53119531d95af335fd2c338ab3515e43dbad47287c
> Content-MD5: 1TjEJVLW/yj59ssgpBNwVw==
> Content-Type: application/octet-stream
> x-amz-content-sha256: 744946be0b7333b372cf2867df5dfe68140b59ab2a130136fcc2d02c5edbc0a9
> x-amz-date: 20210228T035720Z
> x-amz-meta-atime: 1614484639
> x-amz-meta-ctime: 1614484640
> x-amz-meta-gid: 0
> x-amz-meta-mode: 33152
> x-amz-meta-mtime: 1614484640
> x-amz-meta-uid: 0
> Content-Length: 67090
> Expect: 100-continue

You are using a completely different credential here @fdefilippo 

> $ mc admin user info local francesco
> AccessKey: francesco
> Status: enabled
> PolicyName: test-policy
> MemberOf: francesco

Your policy is enabled for a different user @fdefilippo
