### ISSUE TITLE
Bucket Notification not sent when copying the file to folder using cp command

### ISSUE THREAD

**Issue by pavansistla** [minio/minio#11650]
Bucket notifications are not working

## Expected Behavior
Able to send the event to kafka

## Current Behavior
If i use mc or browser create for object events are working
Able to display files when I use linux copy command to data directory

## Steps to Reproduce (for bugs)
1. Set an event for bucket to notify kafka
2. cp <SOURCE> <MINIO DATA BUCKET>
3. Able to see the file in browser
4. No event notifications is sent

**Comment by harshavardhana** [comment]
@pavansistla please describe more about your issue with MinIO release and also a reproducer,  - can't help you here until you open the issue with more details.

Thanks

**Comment by pavansistla** [comment]
@harshavardhana 

1. Installed Minio on my local machine by mapping the data folder
2. Create a bucket using minio browser
3. Set an event for the bucket to notify kafka
4. Copy the file to bucket using linux cp command to drive
5. Able to see the file in browser
6. No event notifications is sent to kafka

Can you please let me know if these steps are not clear.

**Comment by harshavardhana** [comment]
> 1. Installed Minio on my local machine by mapping the data folder
> 2. Create a bucket using minio browser
> 3. Set an event for the bucket to notify kafka
> 4. Copy the file to bucket using linux cp command to drive
> 5. Able to see the file in browser
> 6. No event notifications is sent to kafka

Please paste all the commands that you ran @pavansistla

**Comment by pavansistla** [comment]
@harshavardhana 

EXPORT MINIO_ROOT_USER
EXPORT MINIO_ROOT_PASSWORD

minio server ~/minio/data

mkdir ~/minio/data/bucket1

mc admin config set minio notify_kafka:1 tls_skip_verify="off"  queue_dir="" queue_limit="0" sasl="off" sasl_password="" sasl_username="" tls_client_auth="0" tls="off" client_tls_cert="" client_tls_key="" brokers="localhost:9092" topic="minio-events" version=""

mc event add minio/bucket1 arn:minio:sqs::1:kafka

cp test.txt ~/minio/data/bucket1/ -> no notification

mc cp test.txt ~/minio/data/bucket1/ -> notification sent

**Comment by harshavardhana** [comment]
> cp test.txt ~/minio/data/bucket1/ -> no notification

you are copying to backend directly not using S3 API @pavansistla how do you expect server to send notifications for such operations?

**Comment by pavansistla** [comment]
yeah .. here minio browser is able to detect and showing files

**Comment by harshavardhana** [comment]
> yeah .. here minio browser is able to detect and showing files

of course you can because that's a MinIO feature to support existing files on the backend.
