### ISSUE TITLE
encoding of object keys in webhook object notifications is inconsistent with AWS S3

### ISSUE THREAD

**Issue by macklin-10x** [minio/minio#11665]
## Expected Behavior

Object keys in bucket notifications are encoded in a manner consistent with notifications generated by AWS S3.  ObjectCreated notifications generated by AWS S3 and forwarded to SQS are URL-encoded according to their spec but in reality the slash character is not encoded, while otherwise using query-style encoding (eg space -> +).

## Current Behavior

`/` characters in paths are URL-encoded.

## Possible Solution

Do not encode slashes, or we close this issue and I attempt to file the mirror image of this bug with AWS S3.

## Context

My application merges notification streams from both minio (fronting a network file system) and AWS S3.  I cannot merge the two event streams without applying different escaping rules to each.

**Comment by harshavardhana** [comment]
@macklin-10x can you provide an example from AWS S3 ? 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html 

S3 documentation indicates that 

> The s3 key provides information about the bucket and object involved in the event. The object key name value is URL encoded. For example, "red flower.jpg" becomes "red+flower.jpg" (Amazon S3 returns "application/x-www-form-urlencoded" as the content type in the response).

URL encoded is different than - path encoded so `/` slashes are encoded.  We cannot change this right now as these keys would have been already used for persistence etc., they really need to fix their docs or fix their implementation to reflect their docs.

**Comment by macklin-10x** [comment]
Yeah I'm gonna pin this squarely on AWS not adhering to their own spec; this is arguably not really a minio bug.  Closing, and thanks for your input!
