### ISSUE TITLE
"Volume not found" error message in log

### ISSUE THREAD

**Issue by andreas-repp** [minio/minio#11685]
I have a minio cluster with 4 nodes, each having 2 disks of 2 TB (local storage) running in Kubernetes with the minio helm chart. All 4 minio pods spam logs like this:

```
2: cmd/metacache-set.go:254:cmd.(*listPathOptions).updateMetacacheListing()
1: cmd/metacache-set.go:651:cmd.(*erasureObjects).listPath.func3.1()

API: SYSTEM()
Time: 09:56:48 UTC 03/03/2021
DeploymentID: 488174a7-79db-47ed-9c5e-8884824de6c6
Error: volume not found (*errors.errorString)
3: cmd/peer-rest-client.go:676:cmd.(*peerRESTClient).UpdateMetacacheListing()
2: cmd/metacache-set.go:254:cmd.(*listPathOptions).updateMetacacheListing()
1: cmd/metacache-set.go:651:cmd.(*erasureObjects).listPath.func3.1()
```

This log message is printed between every 1  to 10 seconds. Running `mc admin info fa-minio` shows that all disks are there. 

```
●  fa-minio-0.fa-minio-svc.fa-minio.svc.cluster.local:9000
   Uptime: 19 hours
   Version: 2021-03-01T04:20:55Z
   Network: 4/4 OK
   Drives: 2/2 OK

●  fa-minio-1.fa-minio-svc.fa-minio.svc.cluster.local:9000
   Uptime: 6 hours
   Version: 2021-03-01T04:20:55Z
   Network: 4/4 OK
   Drives: 2/2 OK

●  fa-minio-3.fa-minio-svc.fa-minio.svc.cluster.local:9000
   Uptime: 12 minutes
   Version: 2021-03-01T04:20:55Z
   Network: 4/4 OK
   Drives: 2/2 OK

●  fa-minio-2.fa-minio-svc.fa-minio.svc.cluster.local:9000
   Uptime: 17 hours
   Version: 2021-03-01T04:20:55Z
   Network: 4/4 OK
   Drives: 2/2 OK

12 GiB Used, 8 Buckets, 215,501 Objects
8 drives online, 0 drives offline
```

Can you tell me what is wrong or how I can debug this?

**Comment by klauspost** [comment]
Volume is internal speak for buckets. Some of your disks may be missing some buckets completely.

**Comment by andreas-repp** [comment]
Ah, good to know the terminology. What can I do about it? Doesn't it heal itself? It's showing this error for weeks now.

**Comment by klauspost** [comment]
For weeks? Or since last upgrade?

This condition shouldn't really come up under normal circumstances.

**Comment by andreas-repp** [comment]
Yes, it is there at least since two weeks and multiple version upgrades. Unfortunately, I don't know the exact date any more. At first I thought it would heal itself, but it does not seem to happen. What can I do to fix it?

**Comment by harshavardhana** [comment]
This error is simply an in-memory cache error 

```
// updateCacheEntry will update non-transient state.
func (m *metacacheManager) updateCacheEntry(update metacache) (metacache, error) {
        m.mu.RLock()
        if meta, ok := m.trash[update.id]; ok {
                m.mu.RUnlock()
                return meta, nil
        }

        b, ok := m.buckets[update.bucket]
        m.mu.RUnlock()
        if ok {
                return b.updateCacheEntry(update)
        }

        // We should have either a trashed bucket or this
        return metacache{}, errVolumeNotFound
}
```

It doesn't represent anything on the disk - so it is basically a List request on a bucket that doesn't exist or has been removed transiently.

Nothing to be worried about IMO - `mc admin service restart` should remove this log from occurring.

**Comment by andreas-repp** [comment]
I just `mc admin service restart` but it didn't help. The cluster has also been restarted a couple of times since this started to appear.
