### ISSUE TITLE
docs: How minio compare to other object storage (Ceph, etc.)

### ISSUE THREAD

**Issue by klausenbusk** [minio/minio#1168]

**Comment by klausenbusk** [comment]
I think something similar to how seaweedfs do it in their README. https://github.com/chrislusf/seaweedfs#compared-to-other-file-systems

**Comment by AshwinJay** [comment]
There is another one based on Cassandra - https://github.com/exoscale/pithos. It would be nice if the docs mentioned whether Minio with its current FS store allows forming a cluster of storage nodes. 

Thanks.

**Comment by harshavardhana** [comment]
> There is another one based on Cassandra - https://github.com/exoscale/pithos. It would be nice if the docs mentioned whether Minio with its current FS store allows forming a cluster of storage nodes.
> 
> Thanks.

Currently it doesn't - it's a work in progress.

**Comment by GarimaKapoor** [comment]
We will leave it to the community to compare :)

**Comment by jdbranham** [comment]
Is the cluster storage node still a work in progress?

**Comment by harshavardhana** [comment]
> Is the cluster storage node still a work in progress?

No it is not https://docs.minio.io/docs/distributed-minio-quickstart-guide
