### ISSUE TITLE
"make test" is failing on Mac

### ISSUE THREAD

**Issue by sgandon** [minio/minio#11698]
When building minio from the source code in order to contribute to the base code, the tests (in fact the linting) fails on my mac.

## Expected Behavior

Launching unit tests should work

## Current Behavior

```
make test
Running fmt check
Running lint check
pkg/smart/types.go:23:6: `nvmePassthruCommand` is unused (deadcode)
type nvmePassthruCommand struct {
     ^
pkg/smart/types.go:62:6: `nvmeIdentController` is unused (deadcode)
type nvmeIdentController struct {
     ^
pkg/smart/types.go:153:6: `nvmeSMARTLog` is unused (deadcode)
type nvmeSMARTLog struct {
     ^
cmd/http/dial_others.go:29:6: `setInternalTCPParameters` is unused (deadcode)
func setInternalTCPParameters(c syscall.RawConn) error {
     ^
pkg/smart/types.go:179:2: `fd` is unused (structcheck)
	fd   int
	^
make: *** [lint] Error 1
```

## Your Environment

here is the commit sha : 7be710947
* Operating System and version (`uname -a`):
```
uname -a
Darwin LT-C02X44SLJGH6.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

**Comment by harshavardhana** [comment]
> make test
> Running fmt check
> Running lint check
> pkg/smart/types.go:23:6: `nvmePassthruCommand` is unused (deadcode)
> type nvmePassthruCommand struct {
>      ^
> pkg/smart/types.go:62:6: `nvmeIdentController` is unused (deadcode)
> type nvmeIdentController struct {
>      ^
> pkg/smart/types.go:153:6: `nvmeSMARTLog` is unused (deadcode)
> type nvmeSMARTLog struct {
>      ^
> cmd/http/dial_others.go:29:6: `setInternalTCPParameters` is unused (deadcode)
> func setInternalTCPParameters(c syscall.RawConn) error {
>      ^
> pkg/smart/types.go:179:2: `fd` is unused (structcheck)
> 	fd   int
> 	^
> make: *** [lint] Error 1

Do not run `make test` just run `cd cmd/; go test -v`   - lint is just incorrectly complaining about functions that are not implemented for `macOS`

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/11699 - don't have a mac so please let us know if this solves `make test`.
