### ISSUE TITLE
Healing a disk is taking a very long time.

### ISSUE THREAD

**Issue by Surfict** [minio/minio#11696]
## Expected Behavior
Healing a disk that should contain around 70GB of data shouldn't take an entire day.

## Current Behavior
I am testing my minio installation. I voluntarily delete all files from one of my node and check if I can still use minio and if the disk is healing correctly. It's healing, but it takes around 18h to heal around 70GB of data. 

## Steps to Reproduce (for bugs)
1. Stop minio
2. Remove everything from one of the disks that is using minio
3. Start minio and check the logs of the minio instance who is healing
4. Check how fast the disk takes to heal using df -h

## Context
I am testing my minio installation. I voluntarily delete all files from one of my 8 disks and check if I can still use minio and if the disk is healing correctly. We currently have only 70 GB od data per disk that is used by minio, but plan to have TB of it in the future. If it takes one day to heal 70GB, healing 1tb could be a problem..

I tried the same manipulation with a minio using docker volumes and not mounting disks. The healing time was very efficient and very different from what I observe in this case.

## Your Environment
We use minio in a docker swarm, with four instances. Each of these instances has two disks attached. Each of these disks can contain up to 4.3 Tb of data. 
I am using theses ENV variable in the configuration :
```
      MINIO_HEAL_MAX_SLEEP: 100ms
      MINIO_HEAL_MAX_IO: '1000'
```

(I also tried with MAX_DELAY to replace MAX_SLEEP, i think there is something to update in the [doc](https://docs.min.io/docs/minio-server-configuration-guide.html) )
* Version used (`minio --version`): RELEASE.2021-03-01T04-20-55Z-16-gf12517b4d
* Operating System and version (`uname -a`): 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
That's not how MinIO heals @Surfict if you manually delete content from the backend is different than replacing drives - so if you replace a drive that gets healed quickly but if manually delete content such as a drive was offline - then crawler visits the drive in its various cycles. 

If you wish to force the heal then you can manually trigger it using `mc admin heal -r --remove alias/`

**Comment by klauspost** [comment]
The number of objects is the primary factor for heal speed, and as Harsha mentioned full disk healing is a lot faster than single file healing.

Full disk healing is a lot more realistic scenario than single files going missing. We will work on improving that scenario, but single file healing will take a long time since scanning the entire HD is an expensive operation and we will not let it interfere with regular operation.

**Comment by Surfict** [comment]
How could I simulate a drive replacement? What I do is removing every files from it, it is exactly at the same state as it was in a fresh install, when minio start (an empty folder.)

**Comment by klauspost** [comment]
@Surfict Unmount+reformat+mount should be fine.
