### ISSUE TITLE
Hitting process limit

### ISSUE THREAD

**Issue by gedOHub** [minio/minio#11706]
Minio server crash from time to time. Error looks like:
```bash
runtime: failed to create new OS thread (have 4914 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

## Expected Behavior
Do not crash

## Current Behavior
Limits are increased in systemd service description:
```bash
...
[Service]
...
LimitNPROC=16000
LimitNOFILE=65536
...
```

## Possible Solution
Increase limits

## Context
From time to time minio servers just crashed and stops working.

## Your Environment
* minio version RELEASE.2021-02-19T04-38-02Z
* 4 x ( 2 x CPU AMD EPYC 7B12, 8GB RAM,  )
* #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

What I'm missing?

**Comment by harshavardhana** [comment]
You should also increase TasksMax=infinity and NPROC to infinity as well. Having limits and pushing the server will definitely crash it.

**Comment by gedOHub** [comment]
@harshavardhana can you give an example or how it should be done?

**Comment by klauspost** [comment]
@gedOHub Consult your OS documentation.
