### ISSUE TITLE
Mino enableVersioning not exists and setBucketVersioning is not implmented

### ISSUE THREAD

**Issue by Shanmugasundaram-V** [minio/minio#11707]
## Expected Behavior

Enabling versioning for bucket should work as Expected

Enabling versioning for bucket is not working
minioClient.enableVersioning(EnableVersioningArgs.builder().bucket(bucketName).build());
enableVersioning - is not available in minio 8.1.0

minioClient.setBucketVersioning(
			          SetBucketVersioningArgs.builder()
			              .bucket(bucketName)
			              .config(new VersioningConfiguration(VersioningConfiguration.Status.ENABLED, null))
			              .build());
throws error:
error occurred
ErrorResponse(code = NotImplemented, message = A header you provided implies functionality that is not implemented, bucketName = version-bucket, objectName = null, resource = /version-bucket, requestId = 16696477F22656F8, hostId = ae094568-2368-470c-a3e2-216a8215fc25)
request={method=PUT, url=http://localhost:9000/version-bucket?versioning=, headers=Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.0.3
Content-MD5: QQFYoy/mRYV9PGZUfFi0Bw==
x-amz-content-sha256: 482d4e510b5cdcf0bbf3a044e82832dc711f4f28757a6c06eb21758282a73ef7
x-amz-date: 20210305T082007Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210305/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=501, headers=Accept-Ranges: bytes
Content-Length: 334
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 16696477F22656F8
X-Xss-Protection: 1; mode=block
Date: Fri, 05 Mar 2021 08:20:07 GMT
}

I am using Windows Server and Java SDK

**Comment by nitisht** [comment]
How did you start the server?

**Comment by Shanmugasundaram-V** [comment]
minio.exe server <location>

**Comment by nitisht** [comment]
Versioning is not supported on FS mode. Please use erasure code mode with atleast 4 drives
