### ISSUE TITLE
the port I specified does not work

### ISSUE THREAD

**Issue by rinat9177** [minio/minio#11716]
I downloaded the latest version of minio
I am having problems running the minio on port 9002. 
I have specified the port manually.
`MINIO_VOLUMES="/opt/drive{1...2}"
MINIO_OPTS="-C /etc/minio https://minio{1...3}:9002/opt/drive{1...2}"`

 But the instances of the minio do not see each other. 
`Error: Marking https://minio3:9002/minio/storage/opt/drive2/v28 temporary offline;`
Then I ran netstat -apn and saw  0 :::9000. Minio listen to 9000 port

**Comment by harshavardhana** [comment]
> I am having problems running the minio on port 9002.
> I have specified the port manually.
> `MINIO_VOLUMES="/opt/drive{1...2}" MINIO_OPTS="-C /etc/minio https://minio{1...3}:9002/opt/drive{1...2}"`
> 
> But the instances of the minio do not see each other.
> `Error: Marking https://minio3:9002/minio/storage/opt/drive2/v28 temporary offline;`
> Then I ran netstat -apn and saw 0 :::9000. Minio listen to 9000 port

This is completely incorrect way to run MinIO  - read the docs properly https://github.com/minio/minio-service/tree/master/linux-systemd/distributed
