### ISSUE TITLE
Prometheus monitoring issue

### ISSUE THREAD

**Issue by gedOHub** [minio/minio#11713]
## Current Behavior
After the update, Prometheus endpoint marks disks as offline, but `mc admin info` shows all disks online.

No log entries related to this issue.

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
1. Set up minio cluster with `2021-02-14T04:01:33Z` version
2. Update minio cluster to `2021-03-04T00:53:13Z` version
3. `mc admin info` shows all nodes and disks are `online`
```bash
root@node1:~# mc admin info local
●  node2:9000
   Uptime: 3 hours 
   Version: 2021-03-04T00:53:13Z
   Network: 4/4 OK 
   Drives: 16/16 OK 

●  node3:9000
   Uptime: 3 hours 
   Version: 2021-03-04T00:53:13Z
   Network: 4/4 OK 
   Drives: 16/16 OK 

●  node4:9000
   Uptime: 3 hours 
   Version: 2021-03-04T00:53:13Z
   Network: 4/4 OK 
   Drives: 16/16 OK 

●  node1:9000
   Uptime: 3 hours 
   Version: 2021-03-04T00:53:13Z
   Network: 4/4 OK 
   Drives: 16/16 OK 

411 MiB Used, 6 Buckets, 32,596 Objects
64 drives online, 0 drives offline

```
4. Promethesu metrics:
```bash
root@node1:~# curl http://localhost:9000/minio/v2/metrics/cluster | grep offline
...
minio_cluster_disk_offline_total{server="node1:9000"} 64
...
root@node1:~# curl http://localhost:9000/minio/v2/metrics/cluster | grep online
...
minio_cluster_disk_online_total{server="node1:9000"} 64
...
```

## Your Environment

* 2021-03-04T00:53:13Z
* 4 x ( 2 x AMD EPYC 7B12, 8GB RAM )
* SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> ```shell
> root@node1:~# curl http://localhost:9000/minio/v2/metrics/cluster | grep offline
> ...
> minio_cluster_disk_offline_total{server="node1:9000"} 64
> ...
> root@node1:~# curl http://localhost:9000/minio/v2/metrics/cluster | grep online
> ...
> minio_cluster_disk_online_total{server="node1:9000"} 64
> ```

Ah looks like a stupid regression - let me send a fix.
