### ISSUE TITLE
Minio signature error upon restarting docker container

### ISSUE THREAD

**Issue by nuevilly** [minio/minio#11719]
Summary:  I use Minio with Arq Backup for Mac, and everything works well.  However, after restarting the docker container, I receive the error" 

"GET https://xxx.xxx/xxx/xxxx/backupfolders/@eaDir/backupfolder.json: The request signature we calculated does not match the signature you provided. Check your key and signing method."

I have the latest version of Minio running in Docker on my Synology NAS.  I use Minio to backup with Arq for MacOS.  Everything was set up following the instructions here:  https://www.arqbackup.com/blog/synology-backup-guide/

Everything works perfectly, until I restart the docker container.  Following this, I am no longer able to backup to Minio or access my backups through Arq.  I receive the signature error above.  

I am still able to access the Minio bucket via the Browser, and I have confirmed that my access key and secret key are unchanged.  

This behaviour can be reliably reproduced by:
1. starting a new Minio docker container (following the instructions linked above), 
2. setting up the backup, with Arq 
3. everything works perfectly
4. Restart Minio in docker
5. I receive the signature error. 

I have spoken to Arq support, and everything appears to be working on Arq's end. 
 
## Expected Behavior
When I restart the Minio docker container, I should be able to continue accessing my backups without a signature error. 

## Current Behavior
After restarting the docker container, I receive the following error on my Arq client for MacOS:

"GET https://xxx.xxx/xxx/xxxx/backupfolders/@eaDir/backupfolder.json: The request signature we calculated does not match the signature you provided. Check your key and signing method."

I can no longer run my backups using Arq.  However, I am still able to access Minio via the browser interface

## Possible Solution

Unknown

## Steps to Reproduce (for bugs)

1. start a new Minio docker container (following the instructions here: https://www.arqbackup.com/blog/synology-backup-guide/), 
2. set up the backup with Arq using the Minio access key and secret key
3. everything works perfectly
4. Restart Minio in docker
5. I receive the Signature error and can no longer access Minio through Arq

I can still access the bucket through the Minio browser interface. 

## Context

I am using Minio in docker on my Synology NAS to backup my Mac using Arq Backup, following the instructions here:
https://www.arqbackup.com/blog/synology-backup-guide/

## Regression

No

## Your Environment

* Version used (`minio --version`):  RELEASE.2021-03-04T00-53-13Z
* Server setup and configuration:  Docker on Synology NAS (all updated to latest versions)

**Comment by harshavardhana** [comment]
@nuevilly are you not setting the right environment credentials?

**Comment by nuevilly** [comment]
Do you mean the RootUser and RootPass variables?  If so, yes.  I have checked that these are correct and I can use them to successfully login through the Minio browser

**Comment by harshavardhana** [comment]
> Do you mean the RootUser and RootPass variables? If so, yes. I have checked that these are correct and I can use them to successfully login through the Minio browser

There is no reason "signature error" can happen other than 

- you have incorrect proxy settings
- you passed an incorrect secret key

I can't see such basic error will go unnoticed through our CI/CD systems.  

I can use `mc` and restart docker as much as I want and no issues. Can you confirm no issues with `mc`?

**Comment by nuevilly** [comment]
This issue has been resolved.  It was not directly a Minio issue after all, but rather a problem with Arq and "@eaDir" folders generated by Synology (these are extended-attributes folders, that likely get created when the NAS is indexed). I found that deleting the "@eaDir" folders in the Bucket solved the issue.

I'm not sure why, but Arq was trying to access these folders, and Minio was giving a signature error.

Thanks for your help!

**Comment by harshavardhana** [comment]
> I'm not sure why, but Arq was trying to access these folders, and Minio was giving a signature error.

this is because Arq is incorrectly encoding these - they are not properly encoding the URL path when '@' character files are involved. 

```
~ mc cp /etc/hosts play/testbucket/@htest
/etc/hosts:                        525 B / 525 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 5.63 KiB/s 0 

~ mc ls play/testbucket/
[2021-03-05 22:04:00 PST]   525B @htest

~ mc: <DEBUG> GET /testbucket/%40htest HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v7.0.8 mc/2021-03-05T05:43:16Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210306/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210306T060617Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 525
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Sat, 06 Mar 2021 06:06:17 GMT
Etag: "92a46c640c0a622d9500d610a7cb1d50"
Last-Modified: Sat, 06 Mar 2021 06:04:00 GMT
Server: nginx/1.14.0 (Ubuntu)
Vary: Origin
X-Amz-Request-Id: 1669ABBEF1886B16
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  20.79937ms

127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Most probably Arq backup doesn't handle the Path encoding properly for such objects @nuevilly

**Comment by nuevilly** [comment]
@harshavardhana 

thanks. I'll let the Arq team know so they can hopefully fix it.  I doubt I'm the first/last person to have this issue.


One more quick question - in all my troubleshooting, I deleted the `.minio.sys` folder. Everything seems to be working fine, and a new `.minio.sys` folder was automatically created, but I'm wondering if I've somehow compromised my backups by deleting this folder?

**Comment by harshavardhana** [comment]
> One more quick question - in all my troubleshooting, I deleted the `.minio.sys` folder. Everything seems to be working fine, and a new `.minio.sys` folder was automatically created, but I'm wondering if I've somehow compromised my backups by deleting this folder?

Its recreated in single drive setups, only thing that is lost is 'metadata' associated with objects
