### ISSUE TITLE
Incomplete object Lists

### ISSUE THREAD

**Issue by vixns** [minio/minio#11724]
When recursively listing a big objects tree, sometimes the list is incomplete.

## Expected Behavior

A complete list of objects or a timeout error.

## Current Behavior

The last part contains no errors, but seems to be the end of the list, the key count is less than then mac, and the IsTruncated flag is False, here's is a sample.
```
[...]<KeyCount>979</KeyCount><MaxKeys>4500</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated>[...]
```
I known it's incomplete because if a re-run the same `mc ls --recursive ...` command, with no change in the repository, the resulting list is bigger.

If i rerun it many times, thanks to kernel fs caching, I finally obtain the full list.

It only occurs on big trees, and is far more frequent when using sidecick, but also occurs without sidekick on our biggest trees.
The cluster is 4x4 mechanical HDD.

## Possible Solution

https://github.com/minio/minio/pull/11700 will workaround it I guess, but It seems to be related to some timeout, each 4500 objects list query takes 60~150s when fs caches are empty. 

## Steps to Reproduce (for bugs)

1. setup a 4x4 disks cluster with (slow but cheap) mechanical HDDs
2. install sidekick, it makes it easier to reproduce, I don't know why.
3. create a tree with > 100k objects
4. run `mc ls --recursive ... | wc -l` several times, if this issue occurs, you will see increasing numbers on each call.

## Context

I discover this issue when using restic with minio as backend on servers with many files.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-03-04T00-53-13Z
* Server setup and configuration: minio server https://minio{1...4}.XXXX.net:9000/mnt/disk{1...4}/data
* Operating System and version (`uname -a`): Linux minio1 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You should enable MINIO_API_LIST_QUORUM=strict for quorum lists by default MinIO lists from at most 3 disks. It's called optimal scenario.
