### ISSUE TITLE
111

### ISSUE THREAD

**Issue by jaceding** [minio/minio#11729]
提供的 docker-compose.yaml 不能很好的开箱即用

**Comment by nitisht** [comment]
请在问题模板中填写完整的详细信息，以便我们为您提供帮助

**Comment by jaceding** [comment]
docker-compose.yaml 中的 
server http://minio{1...4}/data{1...2} 
是什么意思？
如果我需要启动三台示例该如何启动呢

**Comment by jaceding** [comment]
> 请在问题模板中填写完整的详细信息，以便我们为您提供帮助

docker-compose.yaml 中的：
server http://minio{1...4}/data{1...2}
是什么意思呢?
如果启动三个minio示例分配在三台不同机器上怎么写
