### ISSUE TITLE
auto delete all versions of objects when their latest version is a delete-marker

### ISSUE THREAD

**Issue by Sug2077** [minio/minio#11738]
**Is your feature request related to a problem? Please describe.**
Minio server-side bucket replication is a very useful feature, I have configure that on my server, the replication help me a lot.

But the application service doesn't use versions , objects with delete-marker will always exist on server unless I delete it manually.

Is there a better way to auto delete them?

**Describe the solution you'd like**

Can you add a new feature with ilm:

After added a delete-marker on an object, and expired 24 hours, Minio server will delete all versions of the object.

**Comment by harshavardhana** [comment]
> auto delete all versions of objects when their latest version is a delete-marker

This is a non-S3 behavior we are not willing to change that @Sug2077 feel free to fork MinIO and implement this yourself.

**Comment by harshavardhana** [comment]
> But the application service doesn't use versions , objects with delete-marker will always exist on server unless I delete it manually.

You should use ILM "ExpireDeleteMarker" to enable deleting delete markers.

**Comment by Sug2077** [comment]
> > But the application service doesn't use versions , objects with delete-marker will always exist on server unless I delete it manually.
> 
> You should use ILM "ExpireDeleteMarker" to enable deleting delete markers.

But that just can delete lonely delete-markers, it doesn't help me much

**Comment by kannappanr** [comment]
@Sug2077 You can use BucketNotification and delete associated versions if the latest version is a delete marker. It has to be done outside of MinIO in an external application

**Comment by Sug2077** [comment]
> @Sug2077 You can use BucketNotification and delete associated versions if the latest version is a delete marker. It has to be done outside of MinIO in an external application

I will try that , Thank you for your sugestion
