### ISSUE TITLE
CopyObject returns wrong error 

### ISSUE THREAD

**Issue by mvrhov** [minio/minio#11748]
When you use CopyInBucket functionality and source object doesn't exist, the returned error reports NoSuckKeyError, where the Key property contains the destination object. Which doesn't make any sense.
I'd say that the key property should contain source object.

**Comment by vadmeste** [comment]
> When you use CopyInBucket functionality

What's the exact API that you are talking about ?

**Comment by mvrhov** [comment]
I've changed the title, as I have used the wrong function name. The proper minio api function is CopyObject

**Comment by vadmeste** [comment]
I didn't not find time to do it since this is a big change, but I should fix it soon.

**Comment by harshavardhana** [comment]
> I didn't not find time to do it since this is a big change, but I should fix it soon.

why is this a big change @vadmeste ?

**Comment by harshavardhana** [comment]
Fixed by #12427
