### ISSUE TITLE
LDAP User credentials can be gathered in plain-text via mc admin trace

### ISSUE THREAD

**Issue by groucho64738** [minio/minio#11742]
If I have minio configured to use LDAP as a backend for STS, observing the trace logs with **mc admin trace -v myminio** will show the received curl command including the users plain-text (unicoded) password. 
## Expected Behavior

It would be better if credentials could be blocked in trace output. If we set up https support to minio, this handles the encryption over the network to obfuscate passwords, but any admin on the minio box should not be able view passwords. If mc admin trace is meant for debugging, is it possible to have any passwords blanked? you could have something print the url used, and instead of showing LDAPPassword=thepassword, you can have LDAPPassword=AAAAAAAA or something such that a minio admin does not gain privileged information?
## Current Behavior

Running **mc admin trace -v myminio** displays the curl line used by the client, including the LDAPPassword=thepassword in plain-text
## Steps to Reproduce (for bugs)

1. Enable LDAP support
2. Run mc admin trace on the server
3. Use a client of some sort to get an STS token
4. View the trace output to see the curl request and LDAPPassword appear

## Context

This issue has security ramifications. No one but the user really should be able to view a password in plain text if it can be avoided. 
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
Minio version RELEASE.2021-02-11T08-23-43Z
OS: RHEL7

**Comment by groucho64738** [comment]
This issue is still present in RELEASE.2021-03-04T00-53-13Z

Here's some output of an example. 
test-min1 [REQUEST sts.AssumeRoleWithLDAPIdentity] 12:14:32.431
test-min1 POST /?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=myusername&LDAPPassword=can+youreadthis%3F&Version=2011-06-15
test-min1 Proto: HTTP/1.1
test-min1 Host: test-min1:9000
test-min1 Accept: */*
test-min1 Accept-Encoding: gzip, deflate
test-min1 Connection: keep-alive

**Comment by harshavardhana** [comment]
Although we can fix this, this is not security issue. mc admin trace is like tcpdump and it is mainly meant for debugging purposes.
