### ISSUE TITLE
[Proposal] Add Cluster Configuration File Option 

### ISSUE THREAD

**Issue by lmentary** [minio/minio#11756]
**Is your feature request related to a problem? Please describe.**
It is difficult to deploy Minio in environments where you are not root and have no control over hostnames due to the elipsis string. 

**Describe the solution you'd like**
It would be great if you could simply define each disk explicitely rather than by using the elipsis formula which force's you to use a specific hostname pattern.

ex:
```
clusters:
- cluster-1:
   - http://some_host:9000:/data/disk1
   - http://some_different_hostname:9000:/myfiles/disk2
```
 It seems like the ellipsis strings are converted to a similar format internally anyhow, so this would essentially be skipping the parsing process.

**Describe alternatives you've considered**
In our specific case, all the usual suspects such as messing with hosts files, virtual networks and docker/k8 are out due to various restrictions imposed by different entities.
We've considered finagling proxies, both forward and reverse in combination with self-signed certs. To accommodate the host nomenclature requirements of minio. However the self signed certs are likely to be vetoed at the first sign of a security audit.

**Comment by harshavardhana** [comment]
You can construct your own distribution order using `MINIO_ENDPOINTS`  environment value.

If you use that environment you are on your own and you need to make sure to order disks properly on command line to provide better HA.

**Comment by lmentary** [comment]
To elaborate for those of you who came here on an archeological dig:

You must set MINIO_ERASURE_SET_DRIVE_COUNT and MINIO_ENDPOINTS to achieve this. 

You must then declare a number of endpoints divisible by the drive count as this will represent each "cluster". As minio will take the first n=MINIO_ERASURE_SET_DRIVE_COUNT entries and make them an EC set. So if you have 4 boxes (a, b, c, d) with 2 drives (/data-1, /data-2) and want to split EC evenly across the 4 boxes (one being all data1 drives and 2 being all data 2 drives) you would run the following command:

`MINIO_ROOT_USER=qwerty MINIO_ROOT_PASSWORD=qwerty12345 MINIO_ERASURE_SET_DRIVE_COUNT=4 MINIO_ENDPOINTS="https://a:9000/data-1 https://b:9000/data-1 https://c:9000/data-1 https://d:9000/data-1 https://a:9000/data-2 https://b:9000/data-2 https://c:9000/data-2 https://d:9000/data-2" minio server
`

So the first EC set will be across all the /data-1 drives and the second will be across the /data-2 drives.

**Comment by ianzhang1988** [comment]
@ harshavardhana
> You can construct your own distribution order using `MINIO_ENDPOINTS` environment value.
> 
> If you use that environment you are on your own and you need to make sure to order disks properly on command line to provide better HA.

Cloud you elaborate this.
* What do you mean by "on your own"? 
* What is proper disk order?
* Can I add new pool to cluster using MINIO_ENDPOINTS?

I have some servers which are in use, so I can't change ip or mount point or basicly anything on those servers.
So, can I make server pools for a cluster with non consecutive ip and path(like this: /data1 /data3 /data6) using MINIO_ENDPOINTS?

**Comment by harshavardhana** [comment]
> @ harshavardhana
> 
> > You can construct your own distribution order using `MINIO_ENDPOINTS` environment value.
> > If you use that environment you are on your own and you need to make sure to order disks properly on command line to provide better HA.
> 
> Cloud you elaborate this.
> 
> * What do you mean by "on your own"?
> * What is proper disk order?
> * Can I add new pool to cluster using MINIO_ENDPOINTS?
> 
> I have some servers which are in use, so I can't change ip or mount point or basicly anything on those servers.
> So, can I make server pools for a cluster with non consecutive ip and path(like this: /data1 /data3 /data6) using MINIO_ENDPOINTS?

No you cannot do that with individual args @ianzhang1988 you need to use ellipses syntax.

**Comment by ianzhang1988** [comment]
@harshavardhana
> No you cannot do that with individual args @ianzhang1988 you need to use ellipses syntax.

Is there some complex logic behind ellipses syntax, or is it just expand to an array?

I need a walkaroud for non continuous IP and path to work. Is it possible for me add few code to achieve this without breaking something important?

**Comment by harshavardhana** [comment]
> I need a walkaroud for non continuous IP and path to work. Is it possible for me add few code to achieve this without breaking something important?

Unfortunately that's not possible - non continuous IP is not necessary - just setup a helper DNS entries in /etc/hosts to provide the ellipses syntax.

**Comment by ianzhang1988** [comment]
Thanks for the reply.

Have no doubt ellipses syntax would working fine on dedicated servers,  though it's difficult to reuse some exsiting servers with ellipses syntax.

**Comment by ianzhang1988** [comment]
@harshavardhana 

After reading some code, I think I know the reason why using ellipses syntax.

Correct me if I'm wrong, ellipses syntax is for ensuring the object spread evenly across nodes, http://host{1...4}/xxx is for code to identify nodes ranther than disk.

So, if I extend the syntax to something like this http://host{1,2,3,4}/data{1,2,3,4} in `ellipses.FindEllipsesPatterns(arg)`, I can get the same result as http://host{1...4}/data{1...4},  and http://host{1,2,7,4}/data{3,5,9,2} would work fine, right?

Maybe config file like this:
``` json
{
	"cluster": [
		[
			{
				"url": "http://host-1:9000",
				"driver": [
					"/data1",
					"/data3"
				]
			},
			{
				"url": "http://host-3:9000",
				"driver": [
					"/data4",
					"/data8"
				]
			},
			{
				"url": "http://host-4:9000",
				"driver": [
					"/data2",
					"/data3"
				]
			},
			{
				"url": "http://host-6:9000",
				"driver": [
					"/data3",
					"/data8"
				]
			}
		],
		[
			{
				"url": "http://host-12:9000",
				"driver": [
					"/data1",
					"/data7"
				]
			},
			{
				"url": "http://host-15:9000",
				"driver": [
					"/data2",
					"/data7"
				]
			},
			{
				"url": "http://host-34:9000",
				"driver": [
					"/data7",
					"/data9"
				]
			},
			{
				"url": "http://host-24:9000",
				"driver": [
					"/data4",
					"/data8"
				]
			}
		]
	]
}
```

**Comment by harshavardhana** [comment]
> @harshavardhana 
> 
> After reading some code, I think I know the reason why using ellipses syntax.
> 
> Correct me if I'm wrong, ellipses syntax is for ensuring the object spread evenly across nodes, http://host{1...4}/xxx is for code to identify nodes ranther than disk.
> 
> So, if I extend the syntax to something like this http://host{1,2,3,4}/data{1,2,3,4} in `ellipses.FindEllipsesPatterns(arg)`, I can get the same result as http://host{1...4}/data{1...4},  and http://host{1,2,7,4}/data{3,5,9,2} would work fine, right?
> 
> Maybe config file like this:
> ``` json
> {
> 	"cluster": [
> 		[
> 			{
> 				"url": "http://host-1:9000",
> 				"driver": [
> 					"/data1",
> 					"/data3"
> 				]
> 			},
> 			{
> 				"url": "http://host-3:9000",
> 				"driver": [
> 					"/data4",
> 					"/data8"
> 				]
> 			},
> 			{
> 				"url": "http://host-4:9000",
> 				"driver": [
> 					"/data2",
> 					"/data3"
> 				]
> 			},
> 			{
> 				"url": "http://host-6:9000",
> 				"driver": [
> 					"/data3",
> 					"/data8"
> 				]
> 			}
> 		],
> 		[
> 			{
> 				"url": "http://host-12:9000",
> 				"driver": [
> 					"/data1",
> 					"/data7"
> 				]
> 			},
> 			{
> 				"url": "http://host-15:9000",
> 				"driver": [
> 					"/data2",
> 					"/data7"
> 				]
> 			},
> 			{
> 				"url": "http://host-34:9000",
> 				"driver": [
> 					"/data7",
> 					"/data9"
> 				]
> 			},
> 			{
> 				"url": "http://host-24:9000",
> 				"driver": [
> 					"/data4",
> 					"/data8"
> 				]
> 			}
> 		]
> 	]
> }
> ```

Yes but we won't be doing that, we are rewriting this portion where the setup entirely changes and the process itself will be different.

**Comment by ianzhang1988** [comment]
> Yes but we won't be doing that, we are rewriting this portion where the setup entirely changes and the process itself will be different.

Thanks for your help.

Hope that at code level it would still be relatively easy to extend this part at the futrue changes, So that I could work with my own code and update the code base without too much trouble.
