### ISSUE TITLE
Objects expire 7days

### ISSUE THREAD

**Issue by pauloinho** [minio/minio#11757]
Hi,

I have a freenas server and I enabled the S3 service and I got Minio.

My question is: How do I change the sharing of my videos, because it is limited to 7 days.

It's the first time that I'm using this service and I don't know how to do it

Thanks in advance

**Comment by kannappanr** [comment]
@pauloinho Pre-signed url is limited to 7 days. If you want to allow access for longer, the better way is to allow anonymous download access to that object/prefix. Please reach out to us https://slack.min.io for further such questions

**Comment by pauloinho** [comment]
Hi kannappanr

Thans for quick responding

The goal is to upload some videos to the bucket and then watch them streaming during the year (No limite days)

How do i allow anonymous download access to that object/prefix?
