### ISSUE TITLE
Allow rebranding of MinIO on the server side (logo, etc. for web interface for accessing/uploading to buckets)

### ISSUE THREAD

**Issue by teward** [minio/minio#11751]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, would just be a Like To Have

**Describe the solution you'd like**
Environment variable that can be configured to display an alternative logo or branding instead of the MinIO branding.

**Describe alternatives you've considered**
None available, as we were looking to rebrand the UI component to be a company specific logo that users could see.

**Comment by harshavardhana** [comment]
@teward this is not in our interest - if you really want to have a formal relationship write to us at sales@min.io or visit us a https://min.io/pricing

**Comment by jsmith-dev** [comment]
That's a profoundly poor response.
