### ISSUE TITLE
Unable to set new lifecycle rules: `SetLifecycle` is not supported for `filesystem`.

### ISSUE THREAD

**Issue by TheEdgeOfRage** [minio/minio#11764]
## Expected Behavior
I want to set a lifecycle configuration to delete old versions of objects in a bucket.

## Current Behavior
I'm try to apply the following configuration:

```json
{
    "Rules": [
        {
            "ID": "Removing all old versions",
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 2
            },
            "Status": "Enabled"
        }
    ]
}
```
But I get this error:

```
mcli: <ERROR> Unable to set new lifecycle rules: `SetLifecycle` is not supported for `filesystem`.
```

I'm running Minio in a Docker container using ZFS as the storage driver and root fs on the host. I assume that the error means that the host filesystem is not compatible with the lifecycle configuration, though I might be wrong on that.

I have Minio running on another machine which replicates objects to the one where I get the error and on that machine I could set the lifecycle config just file. The two machines are pretty much identical in setup, except for the ZFS part.

## Steps to Reproduce (for bugs)
Since I'm not sure whether the error does mean that the underlying filesystem isn't supported, but if yes, reproducing would just mean running Minio on a ZFS system and setting a lifecycle policy.

## Context
I'm backing up my PC using duplicity to a local machine (the non-ZFS one) using Minio, which then replicates the objects to a remote server as a secondary backup. Since replication requires Bucket versioning to be enabled and duplicity cleans up old backups using just S3 delete, it wouldn't clean up old backups completely and it would start wasting a lot of disk space. I wanted to mitigate this using a lifecycle config.

## Regression
I don't think so

## Your Environment

* Version used (`minio --version`): Minio version RELEASE.2021-03-04T00-53-13Z
* Server setup and configuration: I run it through Docker over 4 volumes: `server /data{1...4}`
* Operating System and version (`uname -a`): `Linux hostname 5.11.2-arch1-1 #1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> ```
> mcli: <ERROR> Unable to set new lifecycle rules: `SetLifecycle` is not supported for `filesystem`.
> ```

You need first create an alias using `mc alias set ...` and then apply the lifecycle ..

**Comment by TheEdgeOfRage** [comment]
Oh god, I have the alias named on thing on one PC and another on a second computer, so I mixed them up. It never occurred to me that the error means that it's trying to do it on the local filesystem instead of a Minio bucket. Thought it would be nice if the error were a bit clearer on that.

Thank you
