### ISSUE TITLE
Build fails for 32bit linux/mips and linux/mipsle

### ISSUE THREAD

**Issue by trenta3** [minio/minio#11768]
**Is your feature request related to a problem? Please describe.**
Minio fails to compile for 32bit linux/mips and linux/mipsle architectures.
```bash
[minio]$ env GO111MODULE=on GOOS=linux GOARCH=mips go build -o minio-mips
# github.com/minio/minio/pkg/disk
pkg/disk/stat_linux.go:39:22: cannot use s.Type (type int32) as type int64 in argument to getFSType
# github.com/minio/minio/pkg/sys
pkg/sys/stats_linux.go:72:22: invalid operation: uint64(unit) * totalRAM (mismatched types uint64 and uint32)
```

**Describe the solution you'd like**
I know these architectures are not supported out of the box but it would be great if the code compiles effortless also for these 32bit architectures, especially since other 32bit arch already work.
A couple of substitutions in headers solve the problem for me: after these commands the above build step succeeds.
```bash
[minio]$ grep -rl ',!386' | xargs sed -i 's/,!386/,!386,!mips,!mipsle/g'
[minio]$ grep -rl 'linux,386' | xargs sed -i 's/linux,386/linux,386 linux,mips linux,mipsle/g'
```

It would be great to add this to the official repository, and maybe also take care of the other 32bit architectures that go offers a crosscompilation to.
Thank you for the great work by the way!

**Comment by klauspost** [comment]
@trenta3 Please send in a PR and we can quickly add it if it checks out.

**Comment by harshavardhana** [comment]
> ```shell
> [minio]$ grep -rl ',!386' | xargs sed -i 's/,!386/,!386,!mips,!mipsle/g'
> [minio]$ grep -rl 'linux,386' | xargs sed -i 's/linux,386/linux,386 linux,mips linux,mipsle/g'
> ```

NOTE: using 32bit architectures is going way too backpedalling - you can't run anything serious for today's workloads. We would be happy to fix the build here.  But clearly, you are better off spending time and resources on a 64bit architecture.

**Comment by trenta3** [comment]
@harshavardhana I know, I'm just using it to provide a better view of the internal storage of some embedded hardware.
Not doing anything serious with that.

**Comment by trenta3** [comment]
@klauspost Should I add the two new architectures to the crosscompile script?
I see that linux/s390x is included but linux/arm and linux/386 are not.

**Comment by klauspost** [comment]
@trenta3 `s390x` is 64 bits, right?

We don't expect to support 32 bit systems and you are likely to run out of memory if you do. You are welcome to send the fixes to make it compile, but we are not going to go out of our way to keep it like that.

Send the fixes to make it build, and we will take a look at it.

**Comment by harshavardhana** [comment]
the cross-compile test script already tests linux/arm and linux/386

```bash
#!/bin/bash

set -e
# Enable tracing if set.
[ -n "$BASH_XTRACEFD" ] && set -x

function _init() {
    ## All binaries are static make sure to disable CGO.
    export CGO_ENABLED=0

    ## List of architectures and OS to test coss compilation.
    SUPPORTED_OSARCH="linux/ppc64le linux/mips64 linux/arm64 linux/s390x darwin/arm64 darwin/amd64 freebsd/amd64 windows/amd64 linux/arm linux/386 netbsd/amd64"
}

function _build() {
    local osarch=$1
    IFS=/ read -r -a arr <<<"$osarch"
    os="${arr[0]}"
    arch="${arr[1]}"
    package=$(go list -f '{{.ImportPath}}')
    printf -- "--> %15s:%s\n" "${osarch}" "${package}"

    # go build -trimpath to build the binary.
    export GOOS=$os
    export GOARCH=$arch
    export GO111MODULE=on
    go build -trimpath -tags kqueue -o /dev/null
}

function main() {
    echo "Testing builds for OS/Arch: ${SUPPORTED_OSARCH}"
    for each_osarch in ${SUPPORTED_OSARCH}; do
        _build "${each_osarch}"
    done
}

_init && main "$@"
```
