### ISSUE TITLE
Using Minio with Auth0 behind an auth proxy. Policy claim missing from the JWT

### ISSUE THREAD

**Issue by lyndon160** [minio/minio#11761]
I am attempting to login to Minio behind a reverse proxy which already authenticates the user. This proxy forwards the token in the Authorisation header. This appears to be picked up by minio as it ends up as a request parameter after attempting to login. Currently, I'm only interested in using the basic policies that are default in minio's deployment. The example I'll be working with is `readonly`. However, when attempting to login, I get an error with the token claims, more detail below.

I have configured auth0 to add a claim to a namespace. It looks like this at the top level of the payload of the token:

`"https://min.io/policy":"readonly"`

As for Minios configuration, it looks like this:

```
MINIO_IDENTITY_OPENID_CLIENT_ID: <removed>
MINIO_IDENTITY_OPENID_CONFIG_URL: <removed>.auth0.com/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_POLICY_CLAIM_PREFIX:  https://min.io/
```
## Expected Behavior
User is logged in to minio after clicking "Login via OIDC"

## Current Behavior
User is directed to page asking for client id and in the browser console there is the following error:

```
Uncaught (in promise) Error: We encountered an internal error, please try again.: cause(policy claim missing from the JWT token, credentials will not be generated)
    at index_bundle-2021-01-12T13-07-37Z.js:10
```

**Comment by harshavardhana** [comment]
Can you paste your JWT? Obtained from auth0 ?

**Comment by lyndon160** [comment]
JWT payload


```
{
  "https://min.io/policy": "readonly",
  "nickname": "<removed>",
  "name": "<removed>",
  "updated_at": "2021-03-10T16:54:19.101Z",
  "email": "<removed>",
  "email_verified": true,
  "iss": "<removed>",
  "sub": "<removed>",
  "aud": "<removed>",
  "iat": 1615395259,
  "exp": 1615431259
}
```

**Comment by harshavardhana** [comment]
Try with CLAIM_NAME=https://min.io/policy ?

**Comment by lyndon160** [comment]
I've just tried all of the following (not all at once)

```
         - name: MINIO_IDENTITY_OPENID_POLICY_CLAIM_PREFIX
           value: https://min.io/
         - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
           value: https://min.io/policy
         - name: MINIO_IDENTITY_CLAIM_NAME
           value: https://min.io/policy
         - name: MINIO_CLAIM_NAME
           value: https://min.io/policy
         - name: CLAIM_NAME
           value: https://min.io/policy
```
Unfortunately, this still shows the same error.

**Comment by harshavardhana** [comment]
I Will check and get back @lyndon160 - Can you perform `curl -X POST endpoint -d "Action=AssumeRoleWithWebIdentity&DurationSeconds=3600&WebIdentityToken={auth0JWTToken}&Version=2011-06-15" ` does it return anyhting?

**Comment by harshavardhana** [comment]
> ```
> MINIO_IDENTITY_OPENID_POLICY_CLAIM_PREFIX:  https://min.io/
> ```

Looks like your ENV is wrong @lyndon160 

It should be 

> MINIO_IDENTITY_OPENID_CLAIM_PREFIX=https://min.io

Also, you shouldn't set `MINIO_IDENTITY_OPENID_CLAIM_PREFIX` if you have `MINIO_IDENTITY_OPENID_CLAIM_NAME` set. 

I just tried with auth0 works perfectly fine

```
~ export MINIO_IDENTITY_OPENID_CLIENT_ID=Z83N6hjKwZAypoWXn5ijD1VZZXk7dp2R 
~ export MINIO_IDENTITY_OPENID_CONFIG_URL=https://minio.us.auth0.com/.well-known/openid-configuration 
~ export MINIO_IDENTITY_OPENID_CLAIM_PREFIX="https://min.io/" 
~ minio server ~/test
```

With a custom rule 

```js
function(user, context, callback) {
  const namespace = 'https://min.io/';
  context.idToken[namespace + 'policy'] = user.user_metadata.policy;
  callback(null, user, context);
}
```

User metadata
```js
{
  "policy": "readonly"
}
```

Try it with 

```
username: test@m.io
password: minio123456$
```

**Comment by lyndon160** [comment]
Hi @harshavardhana thanks for spotting that. I appreciate you testing this with Auth0.

Looks like it's now correctly picked up by minio. However, I still get a similar error (but with the correct claim):

```
Error: https://min.io/policy claim missing from the JWT token, credentials will not be generated
```
My implementation in auth0 is identical to yours. And the payload of my token as shown above looks correct, effectively requiring a top level claim that looks like:
```
  "https://min.io/policy": "readonly",
```


I've tried your curl request (with my token), but I'm not sure what path I need to be hitting. I've tried the following:

`/minio/`
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /minio/</Message><Resource>/minio/</Resource><RequestId></RequestId><HostId>719fe98a-2803-4af9-9b4d-556af214e45b</HostId></Error>
```


`/minio/admin/config` 

```
{"Code":"XMinioAdminVersionMismatch","Message":"Unexpected client 'admin' API version found 'unknown', expected 'v3', please downgrade the client to older releases","Resource":"/minio/admin/config","RequestId":"","HostId":"719fe98a-2803-4af9-9b4d-556af214e45b"}
```

I can't test your client as my callback url is `http://minio:9000/minio/login/openid` or `http://localhost:9000/minio/login/openid` which is not added to your allowlist.


Thanks

**Comment by lyndon160** [comment]
Update:

Ok, I've tested this setup in a different environment (not protected by a reverse proxy that adds an authorization header) and it works as expected.

I'll post back if and when I come up with a full solution for my use case. Thanks for your help @harshavardhana!

**Comment by lyndon160** [comment]
After further testing, I've found that the issue is not related to the reverse proxy setup I am using, but a configuration difference between the two test configurations I have been using. One was using a local store, which worked, and the other was connecting to an Azure blob.

I seem to be able to get this working this:

```
docker run -p 9000:9000 <minio access and secret envs> MINIO_IDENTITY_OPENID_CONFIG_URL=https://<removed>.eu.auth0.com/.well-known/openid-configuration --env MINIO_IDENTITY_OPENID_CLAIM_PREFIX="https://min.io/" minio/minio:edge server /data
```

I can login with OpenID and the policy I have applied to the user is respected. So all seems good.

However, when trying to run this against an existing Azure blob, it shows the "claim missing" error after attempting to login via OpenID.
```
docker run -p 9000:9000 <minio access and secret envs> <azure envs> --env MINIO_IDENTITY_OPENID_CONFIG_URL=https://<removed>.eu.auth0.com/.well-known/openid-configuration --env MINIO_IDENTITY_OPENID_CLAIM_PREFIX="https://min.io/" minio/minio:edge gateway azure
```
Accessing this with the access key and secret works as expected and shows the data in the azure blob. However, login with OIDC shows this error:

``` 
Error: https://min.io/policy claim missing from the JWT token, credentials will not be generated
```

Full error log (recently pulled from Edge, so the code lines line up with source)

```
API: WebLoginSTS()
Time: 11:40:07 UTC 03/11/2021
DeploymentID: fc21500f-f808-47b8-adb6-9d204d1023e8
RemoteHost: 172.17.0.1
Host: localhost:9000
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
Error: https://min.io/policy claim missing from the JWT token, credentials will not be generated (*errors.errorString)
      10: /go/minio/cmd/api-errors.go:2009:cmd.toAPIErrorCode()
       9: /go/minio/cmd/api-errors.go:2034:cmd.toAPIError()
       8: /go/minio/cmd/web-handlers.go:2419:cmd.toWebAPIError()
       7: /go/minio/cmd/web-handlers.go:2285:cmd.toJSONError()
       6: /go/minio/cmd/web-handlers.go:2254:cmd.(*webAPIHandlers).LoginSTS()
       5: reflect/value.go:476:reflect.Value.call()
       4: reflect/value.go:337:reflect.Value.Call()
       3: /go/minio/pkg/rpc/server.go:275:rpc.(*Server).ServeHTTP()
       2: /go/minio/cmd/generic-handlers.go:135:cmd.setRedirectHandler.func1()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```


Any idea why this works with one setup and not the other? I am logging in the with same user, with the same JWT payload.

**Comment by lyndon160** [comment]
I now see that running it in Gateway mode you need to use ETD. Works now as expected now. RTFM!

**Comment by harshavardhana** [comment]
> ```
> docker run -p 9000:9000 <minio access and secret envs> <azure envs> --env MINIO_IDENTITY_OPENID_CONFIG_URL=https://<removed>.eu.auth0.com/.well-known/openid-configuration --env MINIO_IDENTITY_OPENID_CLAIM_PREFIX="https://min.io/" minio/minio:edge gateway azure
> ```

If you use gateway @lyndon160 you need to enable etcd
