### ISSUE TITLE
Add more labels for S3 metrics

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#11774]
Hi,

Today `s3_requests_current` metrics have these labels:

```
api
instance
job
```

We should add other labels to have something like `mc admin trace`

```
➜  ~ mc admin trace minio

14:06:13.714 [200 OK] s3.ListObjectsV2 minio-server.dev:9000/?list-type=2&delimiter=%2F&prefix=  {Client_IP}    48.425ms     ↑ 159 B ↓ 886 B
```

```
queryURL
statusCode
responseTime
Throughput
ClientIP
...
```

Thanks.

**Comment by harshavardhana** [comment]
This is already re-implemented https://github.com/minio/minio/blob/master/docs/metrics/prometheus/list.md

**Comment by ToLToL** [comment]
Ok thanks.

I used the old endpoint to get metrics: `/minio/prometheus/metrics/cluster`

**Comment by ToLToL** [comment]
Even with the new version I don't have all the information that I have with `mc admin trace`:

```
minio_s3_requests_inflight_total{api="deletebucket",server="127.0.0.1:9000"} 0
minio_s3_requests_inflight_total{api="deletemultipleobjects",server="127.0.0.1:9000"} 0
minio_s3_requests_inflight_total{api="deleteobject",server="127.0.0.1:9000"} 0
...
```

Especially the request parameter to know which object / bucket was created or deleted by `PutObject`, `DeleteObject`, `DeleteBucket` etc... 

ex:
 
```
16:04:13.136 [204 No Content] s3.DeleteBucket minio.dev:9000/mario/ {Client_IP}    274.951ms    ↑ 77 B ↓ 197 B
```

I know that the `mario` bucket was deleted.

**Comment by harshavardhana** [comment]
> Even with the new version I don't have all the information that I have with `mc admin trace`:
> 
> ```
> minio_s3_requests_inflight_total{api="deletebucket",server="127.0.0.1:9000"} 0
> minio_s3_requests_inflight_total{api="deletemultipleobjects",server="127.0.0.1:9000"} 0
> minio_s3_requests_inflight_total{api="deleteobject",server="127.0.0.1:9000"} 0
> ...
> ```
> 
> Especially the request parameter to know which object / bucket was created or deleted by `PutObject`, `DeleteObject`, `DeleteBucket` etc...
> 
> ex:

We cannot provide such low level details with prometheus metrics, that will be bit too much, You need to enable audit logging to splunk or kibana for such monitoring.
