### ISSUE TITLE
please make sure all servers are running the same MinIO version

### ISSUE THREAD

**Issue by sjn939394630** [minio/minio#11771]
## Current Behavior

I have three server make up one minio-cluster, each server have two mount disk. Startup reported the following error

> Unable to read 'format.json' from http://121.36.49.43:9000/mnt/data1: Server expects 'storage' API version 'v29', instead found 'v29' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-03-12T00-00-47Z)
> 
> Unable to read 'format.json' from http://121.36.49.43:9000/mnt/data2: Server expects 'storage' API version 'v29', instead found 'v29' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-03-12T00-00-47Z)
> 
> Unable to read 'format.json' from http://114.116.252.24:9000/mnt/data1: Server expects 'storage' API version 'v29', instead found 'v29' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-03-12T00-00-47Z)
> 
> Unable to read 'format.json' from http://114.116.252.24:9000/mnt/data2: Server expects 'storage' API version 'v29', instead found 'v29' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-03-12T00-00-47Z)
> 
> Unable to read 'format.json' from http://121.36.85.1:9000/mnt/data1: Server expects 'storage' API version 'v29', instead found 'v29' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-03-12T00-00-47Z)
> 
> Unable to read 'format.json' from http://121.36.85.1:9000/mnt/data2: Server expects 'storage' API version 'v29', instead found 'v29' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-03-12T00-00-47Z)
> 
> Waiting for a minimum of 3 disks to come online (elapsed 3s)

minio start.sh

> export MINIO_ACCESS_KEY=minio
> export MINIO_SECRET_KEY=minio123
> export MINIO_PROMETHEUS_AUTH_TYPE="public"
> nohup minio server http://121.36.49.43/mnt/data1 http://121.36.49.43/mnt/data2 http://114.116.252.24/mnt/data1  http://114.116.252.24/mnt/data2 http://121.36.85.1/mnt/data1 http://121.36.85.1/mnt/data2  >> minio.log 2>&1 &

## Your Environment

* Version used (`minio --version`): RELEASE.2021-03-12T00-00-47Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux ecs-31bc-0002 4.4.0-197-generic #229-Ubuntu SMP Wed Nov 25 11:05:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@sjn939394630 are you sure that you are running the same exact version in all your nodes ?

**Comment by sjn939394630** [comment]
@vadmeste yep.I am sure that the three server are running the same exact version RELEASE.2021-03-12T00-00-47Z

**Comment by vadmeste** [comment]
> @vadmeste yep.I am sure that the three server are running the same exact version RELEASE.2021-03-12T00-00-47Z

Is this your first time running MinIO server ?

**Comment by sjn939394630** [comment]
It's the first time on the three server.

**Comment by harshavardhana** [comment]
> > nohup minio server http://121.36.49.43/mnt/data1 http://121.36.49.43/mnt/data2 http://114.116.252.24/mnt/data1  http://114.116.252.24/mnt/data2 http://121.36.85.1/mnt/data1 http://121.36.85.1/mnt/data2  >> minio.log 2>&1 &

This happens because your IP is not local to the node and most probably that's why its not able to register itself. Are you running inside AWS instances here?  - If you are running in cloud instances you need to use private IPs to talk to MinIO instances, not public IPs.
