### ISSUE TITLE
Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.

### ISSUE THREAD

**Issue by sjn939394630** [minio/minio#11784]
## Current Behavior

I'm batching data to Minio-cluster, An error was reported when transferring to more than 80,000 files. Show Storage backend has reached its minimum free disk threshold, But my disk space is enough. /mnt/data1 and /mnt/data2 is the storage disk.

df -h
> root@ecs-31bc-0002:~/minio# df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            7.9G     0  7.9G   0% /dev
> tmpfs           1.6G   21M  1.6G   2% /run
> /dev/vda1        99G  3.0G   91G   4% /
> tmpfs           7.9G     0  7.9G   0% /dev/shm
> tmpfs           5.0M  4.0K  5.0M   1% /run/lock
> tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
> tmpfs           1.6G     0  1.6G   0% /run/user/0
> /dev/vdb1        50G   13G   34G  28% /mnt/data1
> /dev/vdc1        50G   13G   34G  28% /mnt/data2

mc admin info cluster --json.  
> root@ecs-31bc-0002:~/minio# mc admin info cluster1 --json
> {
>     "status": "success",
>     "info": {
>         "mode": "online",
>         "deploymentID": "9757c10c-99d7-4575-ab3a-bc702635e831",
>         "buckets": {
>             "count": 1
>         },
>         "objects": {
>             "count": 86714
>         },
>         "usage": {
>             "size": 36322766
>         },
>         "services": {
>             "kms": {
>                 "status": "disabled"
>             },
>             "ldap": {}
>         },
>         "backend": {
>             "backendType": "Erasure",
>             "onlineDisks": 6,
>             "rrSCParity": 2,
>             "standardSCParity": 3
>         },
>         "servers": [
>             {
>                 "state": "online",
>                 "endpoint": "192.168.0.11:9000",
>                 "uptime": 5799,
>                 "version": "2021-03-12T00:00:47Z",
>                 "commitID": "feafccf0072a9b5fbddc33553890ff56cb2f83b6",
>                 "network": {
>                     "192.168.0.11:9000": "online",
>                     "192.168.0.177:9000": "online",
>                     "192.168.0.179:9000": "online"
>                 },
>                 "drives": [
>                     {
>                         "endpoint": "http://192.168.0.11:9000/mnt/data1",
>                         "path": "/mnt/data1",
>                         "state": "ok",
>                         "uuid": "877c612a-890b-45f1-8c80-706e7b3d12d3",
>                         "totalspace": 50008342528,
>                         "usedspace": 13539811328,
>                         "availspace": 36468531200,
>                         "pool_index": 0,
>                         "set_index": 0,
>                         "disk_index": 2
>                     },
>                     {
>                         "endpoint": "http://192.168.0.11:9000/mnt/data2",
>                         "path": "/mnt/data2",
>                         "state": "ok",
>                         "uuid": "6dcf70c0-dc54-454b-b740-4c20c17599a0",
>                         "totalspace": 50008342528,
>                         "usedspace": 13545119744,
>                         "availspace": 36463222784,
>                         "pool_index": 0,
>                         "set_index": 0,
>                         "disk_index": 3
>                     }
>                 ],
>                 "poolNumber": 1
>             },
>             {
>                 "state": "online",
>                 "endpoint": "192.168.0.179:9000",
>                 "uptime": 5796,
>                 "version": "2021-03-12T00:00:47Z",
>                 "commitID": "feafccf0072a9b5fbddc33553890ff56cb2f83b6",
>                 "network": {
>                     "192.168.0.11:9000": "online",
>                     "192.168.0.177:9000": "online",
>                     "192.168.0.179:9000": "online"
>                 },
>                 "drives": [
>                     {
>                         "endpoint": "http://192.168.0.179:9000/mnt/data1",
>                         "path": "/mnt/data1",
>                         "state": "ok",
>                         "uuid": "76129272-0400-40fa-8845-8854b4e6ba8b",
>                         "totalspace": 50008342528,
>                         "usedspace": 13544722432,
>                         "availspace": 36463620096,
>                         "pool_index": 0,
>                         "set_index": 0,
>                         "disk_index": 4
>                     },
>                     {
>                         "endpoint": "http://192.168.0.179:9000/mnt/data2",
>                         "path": "/mnt/data2",
>                         "state": "ok",
>                         "uuid": "07b2d762-946d-4171-8781-8bcfcf790303",
>                         "totalspace": 50008342528,
>                         "usedspace": 13538193408,
>                         "availspace": 36470149120,
>                         "pool_index": 0,
>                         "set_index": 0,
>                         "disk_index": 5
>                     }
>                 ],
>                 "poolNumber": 1
>             },
>             {
>                 "state": "online",
>                 "endpoint": "192.168.0.177:9000",
>                 "uptime": 5801,
>                 "version": "2021-03-12T00:00:47Z",
>                 "commitID": "feafccf0072a9b5fbddc33553890ff56cb2f83b6",
>                 "network": {
>                     "192.168.0.11:9000": "online",
>                     "192.168.0.177:9000": "online",
>                     "192.168.0.179:9000": "online"
>                 },
>                 "drives": [
>                     {
>                         "endpoint": "http://192.168.0.177:9000/mnt/data1",
>                         "path": "/mnt/data1",
>                         "state": "ok",
>                         "uuid": "b5dfa4e0-22a1-49d5-bd16-ed2ea82cfe28",
>                         "totalspace": 50008342528,
>                         "usedspace": 13544603648,
>                         "availspace": 36463738880,
>                         "pool_index": 0,
>                         "set_index": 0,
>                         "disk_index": 0
>                     },
>                     {
>                         "endpoint": "http://192.168.0.177:9000/mnt/data2",
>                         "path": "/mnt/data2",
>                         "state": "ok",
>                         "uuid": "dd658023-bb75-4fe5-abf2-e3594ecddb47",
>                         "totalspace": 50008342528,
>                         "usedspace": 13541138432,
>                         "availspace": 36467204096,
>                         "pool_index": 0,
>                         "set_index": 0,
>                         "disk_index": 1
>                     }
>                 ],
>                 "poolNumber": 1
>             }
>         ]
>     }
> }

ls -l |grep "^d"|wc -l  on /mnt/data1/dwbcbucket/data is my object storage path

> root@ecs-31bc-0003:/mnt/data1/dwbcbucket/data# ls -l |grep "^d"|wc -l
> 818854

Why does mc show that Minio occupies 36mb of storage, but the disk does use 13gb? And why does mc show that Minio object number is 86714, but ls show object number is 818854?

## Your Environment

* Version used (`minio --version`):  RELEASE.2021-03-12T00-00-47Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux ecs-31bc-0002 4.4.0-197-generic #229-Ubuntu SMP Wed Nov 25 11:05:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You have ran our inodes @sjn939394630 `df -i`
