### ISSUE TITLE
Permission denied when assign custom policy to user

### ISSUE THREAD

**Issue by VoidAndAny** [minio/minio#11789]
I used to create bucket with specific user and policy applied to this user and it doesn't work anymore, I can't apply policy to my user.
I recently upgrade from 2019-07-17 to 2021-03-12

I saw that syntax to apply policy has change, from one step in 2019-07-17 : 
```
mc admin user add myminio myuser mypassword mypolicy
```
To 2 steps with 2021-03-12:
```
mc admin user add myminio myuser mypassword
mc admin policy set myminio mypolicy user=myuser
```

To be sure, I try with the exact example given in documentation 

## Expected Behavior

Policy added to user with command 
```
mc admin policy set myminio getonly user=newuser
```

## Current Behavior
Command hang for at least ~30s then I have permission denied error:

```
$ mc admin policy set myminio getonly user=newuser
mc: <ERROR> Unable to set the policy. We encountered an internal error, please try again. (rename /var/lib/minio/.minio.sys/tmp/d65198f1-c455-4b65-acff-b1020e98cebb/e856104a-e032-44bc-8601-5c5983dbc2d2 /var/lib/minio/.minio.sys/config/iam/policydb/users/newuser.json: permission denied).
```
Note  /var/lib/minio/.minio.sys/tmp/d65198f1-c455-4b65-acff-b1020e98cebb directory is always empty

Permission on this directory:
```
ls -la /var/lib/minio/.minio.sys/tmp/d65198f1-c455-4b65-acff-b1020e98cebb/
total 8,0K
drwxr-xr-x 2 minio minio 4,0K 15/03/2021 17:21 ./
drwxr-xr-x 4 minio minio 4,0K 12/03/2021 16:23 ../
```

I Tried with minio user and root

## Steps to Reproduce (for bugs)
Command given in section "Create a new user with canned policy" on quick start page page https://docs.min.io/docs/minio-multi-user-quickstart-guide.html

## Your Environment

* Version used (`minio --version`): 2021-03-12
* Server setup and configuration: 
* Operating System and version (`uname -a`): Ubuntu 18.04.5 LTS

**Comment by harshavardhana** [comment]
> $ mc admin policy set myminio getonly user=newuser
> mc: <ERROR> Unable to set the policy. We encountered an internal error, please try again. (rename /var/lib/minio/.minio.sys/tmp/d65198f1-c455-4b65-acff-b1020e98cebb/e856104a-e032-44bc-8601-5c5983dbc2d2 /var/lib/minio/.minio.sys/config/iam/policydb/users/newuser.json: permission denied).

This looks like you have some backend permissions that have changed.

**Comment by VoidAndAny** [comment]
Please can you guide me, where to search ?

**Comment by VoidAndAny** [comment]
Ok found it, `/var/lib/minio/.minio.sys/config/iam/policydb`belong to root instead of minio
Sorry for your time
