### ISSUE TITLE
Add a variable to limit the healing CPU usage. 

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11797]
When a heal operation due to a disk failure or node failure runs the CPU ramps to 100% across the nodes that are involved in the healing. This causes monitoring alarms to trigger and also stops commands like mc admin info, trace and console from running. Also Prometheus exports are not fully exported due to lower CPU time.  A small cluster of 5 million objects takes around 30 hours to heal and not having monitoring and being able to perform admin functions is concerning. 

**Describe the solution you'd like**
I would like to see a configurable max limit or a hard coded max limit of 90% CPU usage for heal operations. This will free CPU cycles for other operations. 

**Describe alternatives you've considered**
Bigger CPU's and more hardware but this isn't a viable option. 

**Additional context**
I have raised this in the past. https://github.com/minio/minio/issues/11542 

![image](https://user-images.githubusercontent.com/23471378/111286557-3b892180-863a-11eb-8960-bb25d701c13e.png)

**Comment by klauspost** [comment]
Controlling full disk healing speed is on the current roadmap.

You are welcome to send a 1 minute cpu profile while the healing is running and I can take a look.

**Comment by zapto2600** [comment]
As per my original comment. The problem is that MC wont respond to get a profile.

**Comment by klauspost** [comment]
@zapto2600 As per my previous comment on your earlier issue you may have something on your system that eats CPU cycles, like a bad device driver, bad FS code or something similar. Having so much IO available that it can saturate an 8 core EPYC CPU is extremely improbable.

**Comment by zapto2600** [comment]
We only see this behaviour when healing. Other times the CPU is very much seldom used. On a smaller cluster with less objects we do not see this behaviour.

**Comment by klauspost** [comment]
@zapto2600 Could you post the CPU features `cat /proc/cpuinfo` should be fine for now in the environment that runs the server.

I am wondering if CPU features could be disabled. As mentioned there is no way healing should be taking this much CPU.

It could seem like IO has fallen back to CPU based transfers and are unable to utilize DMA to offload the CPU when reading/writing data. How does your IO queue and IO CPU usage look?

**Comment by zapto2600** [comment]
So it looks like when the cluster is stopped and started for the first time (ie after a upgrade or a problem) its doing its checks this is when we mainly see the behaviour and causes the cluster to be unstable and unresponsive for hours. This isnt a problem on clusters with a lower object count. (with the same configuration).

R_await is < 0.12 w_await is 0.51.   

`flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca`

**Comment by klauspost** [comment]
Yeah, with `avx2` it should be fine. My guess is that your NIC or something in your network setup is eating system resources. 

There is no way healing alone can cause this CPU load, and it ties in with your other problems. Maybe try without TLS and see if that makes a difference.
