### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by AdeloreSimiloluwa** [minio/minio#11794]
Having issues connecting to my minio from jupyter notebook

# How to access MinIO
minio_address = "0.0.0.0:80"
minio_access_key = "--------"
minio_secret_key = "------"

minio_client = Minio(minio_address,
                    access_key=minio_access_key,
                    secret_key=minio_secret_key,
                    secure=True)

with open("text.txt" ,"w")as f:
  f.write("text run")

minio_client.make_bucket("demo-minio-bucket")

<img width="1336" alt="Screen Shot 2021-03-15 at 7 37 11 PM" src="https://user-images.githubusercontent.com/62348760/111234859-d8f63e00-85c5-11eb-8340-874209f62139.png">

**Comment by harshavardhana** [comment]
> minio_address = "0.0.0.0:80"
> minio_access_key = "--------"
> minio_secret_key = "------"

Make sure MinIO is running on port 80 or alternatively specify the port MinIO is running on "default is 9000"

**Comment by AdeloreSimiloluwa** [comment]
I also used the default and got the same error @harshavardhana

**Comment by AdeloreSimiloluwa** [comment]
> > minio_address = "0.0.0.0:80"
> > minio_access_key = "--------"
> > minio_secret_key = "------"
> 
> Make sure MinIO is running on port 80 or alternatively specify the port MinIO is running on "default is 9000"

 i also used the default and got the same error @harshavardhana

**Comment by harshavardhana** [comment]
> > > minio_address = "0.0.0.0:80"
> > > minio_access_key = "--------"
> > > minio_secret_key = "------"
> > 
> > 
> > Make sure MinIO is running on port 80 or alternatively specify the port MinIO is running on "default is 9000"
> 
> i also used the default and got the same error @harshavardhana

You need to specify the IP of the server where your MinIO is running.
