### ISSUE TITLE
minio  gateway hdfs, doc update?

### ISSUE THREAD

**Issue by sidsanders** [minio/minio#11791]
while trying to get minio gateway for hdfs running, i used hdfs cli to get the proper namenode partial url to pass to minio as an override.
## Possible Solution

doc perhaps could include running:
'hdfs getconf -nnRpcAddresses'
which should return namenode:port, which you can then use for an override (prepend hdfs:// to result)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-03-12T00-00-47Z
* Server setup and configuration: single gateway node for minio test, ambari 2.7.5 + hdp 3.1.4
* Operating System and version (`uname -a`): CentOS Linux release 7.8.2003

**Comment by harshavardhana** [comment]
I don't know what this issue is,  closing we automatically use Addresses available from Hadoop conf - if you don't have that you need to specify in the command args. 

Closing this issue.

**Comment by sidsanders** [comment]
there wasnt an issue.  it was an item for doc on setting the params for the gateway.
