### ISSUE TITLE
Why does Minio take up disk space much larger than the actual object size

### ISSUE THREAD

**Issue by sjn939394630** [minio/minio#11796]
## Current Behavior

I use 6 50gb disks for Minio storage, Use the ext4 disk formatting method, specify a block size of 4kb corresponding to an iNode.During use, it is found that the disk space takes up a lot, which is much larger than the actual size of the objects in the cluster.What caused this problem?

/dev/vdb1 and /dev/vdb2 is the object storge disk.
> root@ecs-31bc-0003:~/minio# df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            7.9G     0  7.9G   0% /dev
> tmpfs           1.6G   13M  1.6G   1% /run
> /dev/vda1        99G  2.8G   92G   3% /
> tmpfs           7.9G     0  7.9G   0% /dev/shm
> tmpfs           5.0M  4.0K  5.0M   1% /run/lock
> tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
> tmpfs           1.6G     0  1.6G   0% /run/user/0
> /dev/vdb1        47G   30G   15G  67% /mnt/data1
> /dev/vdc1        47G   30G   15G  67% /mnt/data2

> root@ecs-31bc-0002:/usr/local/prometheus# mc admin info cluster1
> ●  192.168.0.11:9000
>    Uptime: 1 hour 
>    Version: 2021-03-12T00:00:47Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> ●  192.168.0.179:9000
>    Uptime: 1 hour 
>    Version: 2021-03-12T00:00:47Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> ●  192.168.0.177:9000
>    Uptime: 1 hour 
>    Version: 2021-03-12T00:00:47Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> 25 MiB Used, 1 Bucket, 57,843 Objects
> 6 drives online, 0 drives offline
> 

## Your Environment

* Version used (`minio --version`): RELEASE.2021-03-12T00-00-47Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux ecs-31bc-0002 4.4.0-197-generic #229-Ubuntu SMP Wed Nov 25 11:05:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sjn939394630** [comment]
object size is 25mb, but the disk used 33gb

![image](https://user-images.githubusercontent.com/35216211/111251888-0e913a80-864b-11eb-9eaa-1b7194690830.png)

**Comment by harshavardhana** [comment]
> I use 6 50gb disks for Minio storage, Use the ext4 disk formatting method, specify a block size of 4kb corresponding to an iNode.During use, it is found that the disk space takes up a lot, which is much larger than the actual size of the objects in the cluster.What caused this problem?

MinIO uses inodes for xl.meta and part.1 files for its backend format - it's a design choice here @sjn939394630 - you should provide bigger disks 

> /dev/vdb1 47G 30G 15G 67% /mnt/data1

This is a really tiny disk and you also have a lot of junk data perhaps deleted objects at `/mnt/data1/.tmp/.trash`

**Comment by sjn939394630** [comment]
@harshavardhana Why is the number of files in the storage directory far greater than the number of cluster objects?

![image](https://user-images.githubusercontent.com/35216211/111253789-b825fb00-864e-11eb-903f-0fb5ef83c5bf.png)

![image](https://user-images.githubusercontent.com/35216211/111253853-d4c23300-864e-11eb-8382-c2c278359405.png)

**Comment by harshavardhana** [comment]
> @harshavardhana Why is the number of files in the storage directory far greater than the number of cluster objects?

I don't know just do a `find` on your backend `/mnt/data1` and see the structure.  whatever it's doing - it's doing correctly. NOTE `mc admin info` output is not current output - it takes time for the disk scanner to update itself. 

The correct value you should look at `df -i` and see your actual inode usage.
