### ISSUE TITLE
Document: Suggested / best file system to be used with local storage volumes on k8s

### ISSUE THREAD

**Issue by andreas-repp** [minio/minio#11798]
We have set up a minio cluster on a k8s with 4 nodes with local storage volumes pointing to disks on the nodes. In our use case, we have to store a large number of small files (multiple millions of ~ 1kB in size). 

Unfortunately, we weren't able to find documentation on what file system we should use for the disks the local storage volumes run on. It would be great to provide some information on what works well / is tested well and/or what is proposed by the Min.IO team/community. 

Furthermore, we weren't able to determine if it is possible to use raw block devices and if that would be beneficial. 

At the moment we are using Ext4 and experience trouble with directories containing a lot of files (>10k). Since it is a big effort to reformat the disks and transfer the data to a new setup, such information should be provided in the intro guide to avoid having to set everything up multiple times and learn it the hard way.

**Comment by harshavardhana** [comment]
> Unfortunately, we weren't able to find documentation on what file system we should use for the disks the local storage volumes run on. It would be great to provide some information on what works well / is tested well and/or what is proposed by the Min.IO team/community.

Our recommendation is always to use XFS on Linux @andreas-eberle - we don't specifically document it because that is a choice left to the user - MinIO is deployed in various environments with various degrees of requirements.

> Furthermore, we weren't able to determine if it is possible to use raw block devices and if that would be beneficial.

No we need a filesystem, we can't use raw block devices.

**Comment by harshavardhana** [comment]
@ravindk89 can this be covered in our new docs?

**Comment by andreas-repp** [comment]
Thanks @harshavardhana. I think this would be a good thing to be added to the docs. You might add it with a "we allow everything but XFS is often used"-disclaimer.

**Comment by ravindk89** [comment]
@harshavardhana yeah, I've been trying to curate something like this [Production Recommendations](https://docs.min.io/minio/k8s/reference/production-recommendations.html) page, and that seems like a good spot as any for noting XFS. 

@andreas-eberle I'll also add a note to [this section of our primary K8s deployment tutorial](https://docs.min.io/minio/k8s/tutorials/deploy-minio-tenant.html#b-create-the-required-persistent-volumes) and the github readme just for better coverage. Thanks for making this request.
