### ISSUE TITLE
ldap configuration shows multiple fields for lookup_bind_password= 

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#11802]
Checking config for identity_ldap shows repeated valued
## Expected Behavior

Config returned should not have duplicate values
## Current Behavior

```
mc admin config get min identity_ldap
identity_ldap server_addr= sts_expiry=1h username_format= group_search_filter= group_search_base_dn= tls_skip_verify=off server_insecure=off server_starttls=off user_dn_search_base_dn= user_dn_search_filter= lookup_bind_dn= lookup_bind_password= lookup_bind_password= lookup_bind_password= lookup_bind_password= 
```
## Possible Solution

Unknown but `mc admin config reset identity_ldap` gets rid of duplicate values
## Steps to Reproduce (for bugs)

Unsure how it gets to this state initially, but when it gets to that state it can be seen with `mc admin config get <alias> identity_ldap`

## Context

Not sure if this prevents user from setting ldap config without env vars
## Regression

Unsure
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
Observed against RELEASE.2021-03-04T00-53-13Z and RELEASE.2021-02-19T05-34-40Z distributed

**Comment by donatello** [comment]
Unable to repro this.
