### ISSUE TITLE
STS Service LDAP.go example cannot run - undefinded minio module

### ISSUE THREAD

**Issue by sytolk** [minio/minio#11806]
The problem is in this line:
https://github.com/minio/minio/blob/master/docs/sts/ldap.go#L27

My GO version: 1.16.2

It works like this:
```
import (
	...
	minio "github.com/minio/minio-go/v7"
	cr "github.com/minio/minio-go/v7/pkg/credentials"
)
```

This is the ldap.go output:
```
User: Philip J. Fry
Pass: fry
URL: http://localhost:9000
{N6MANMTP88L5YVCOR5S4 x6gnJCagJgMhz+EjPqpnjGirMJsqqIp1R86DKPUe eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJONk1BTk1UUDg4TDVZVkNPUjVTNCIsImV4cCI6MTYxNjE4ODkzNSwibGRhcFVzZXIiOiJjbj1QaGlsaXAgSi4gRnJ5LG91PXBlb3BsZSxkYz1wbGFuZXRleHByZXNzLGRjPWNvbSJ9.W-eN9B233oOKcQ77brNi-jOqKP8aCQGVI1bgKyKI2DDbqHZC-rvajfU5lTE5qf9QNLuYkTA0pQnSdhOKHJRhDg S3v4} <nil>
Calling list objects with temp creds: 
{  0001-01-01 00:00:00 +0000 UTC 0  0001-01-01 00:00:00 +0000 UTC map[] map[] map[] 0 { } []  false false   0001-01-01 00:00:00 +0000 UTC  Bucket name contains invalid characters}

Process finished with exit code 0
```
I see that there is a temp secure key && secret keys but Calling list objects with temp creds is not ok. Maybe the problem is in ListObjects() impl ?

**Comment by sytolk** [comment]
I have try to login with received access and secret keys in web minio but without success.. what is the problem?
![image](https://user-images.githubusercontent.com/1415463/111450785-6b5b2680-8719-11eb-8d70-c3c857d387a8.png)

**Comment by harshavardhana** [comment]
> I have try to login with received access and secret keys in web minio but without success.. what is the problem?

you can't use LDAP creds with browser it won't work

> User: Philip J. Fry
> Pass: fry
> URL: http://localhost:9000
> {N6MANMTP88L5YVCOR5S4 x6gnJCagJgMhz+EjPqpnjGirMJsqqIp1R86DKPUe eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJONk1BTk1UUDg4TDVZVkNPUjVTNCIsImV4cCI6MTYxNjE4ODkzNSwibGRhcFVzZXIiOiJjbj1QaGlsaXAgSi4gRnJ5LG91PXBlb3BsZSxkYz1wbGFuZXRleHByZXNzLGRjPWNvbSJ9.W-eN9B233oOKcQ77brNi-jOqKP8aCQGVI1bgKyKI2DDbqHZC-rvajfU5lTE5qf9QNLuYkTA0pQnSdhOKHJRhDg S3v4} <nil>
> Calling list objects with temp creds: 
> {  0001-01-01 00:00:00 +0000 UTC 0  0001-01-01 00:00:00 +0000 UTC map[] map[] map[] 0 { } []  false false   0001-01-01 00:00:00 +0000 UTC  Bucket name contains invalid characters}
> 
> Process finished with exit code 0

You need to change this code to point to something meaningful such as an actual bucket. Running the code as is copy pasting is meaningless.

**Comment by sytolk** [comment]
@harshavardhana you proposed very interesting fix for this issue :) to close it.. but its not clear now who will make a PR with changes here:
https://github.com/minio/minio/blob/master/docs/sts/ldap.go#L27

and here:
https://github.com/minio/minio/blob/master/docs/sts/ldap.go#L78
yes I see now from docs that the parameter two of the ListObjects() is the bucketName.. but have not see the reason that ldapUsername == bucketName Why?? is setting ldapUsername instead
maybe the right fix for this is to have an additinal bucketName command line parameter

**Comment by harshavardhana** [comment]
> yes I see now from docs that the parameter two of the ListObjects() is the bucketName.. but have not see the reason that ldapUsername == bucketName Why?? is setting ldapUsername instead

That's just an example not meant for you to copy-paste - write relevant code to understand how it works - https://github.com/minio/minio/blob/master/docs/sts/ldap.md
