### ISSUE TITLE
STS API always return XML

### ISSUE THREAD

**Issue by sytolk** [minio/minio#11811]
I have make POST request to STS API with header `Accept: application/json` but XML is returned from the API
https://github.com/minio/minio/blob/master/docs/sts/ldap.md#sample-post-request

```
Stanimirs-Mac-mini:~ sytolk$ curl -X POST -v -H "Accept: application/json" -d "Action=AssumeRoleWithLDAPIdentity&LDAPUsername=Philip J. Fry&LDAPPassword=fry&Version=2011-06-15" http://localhost:9000
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> POST / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: application/json
> Content-Length: 96
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 96 out of 96 bytes
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 810
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 166D21323504BB20
< X-Xss-Protection: 1; mode=block
< Date: Wed, 17 Mar 2021 12:32:20 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<AssumeRoleWithLDAPIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><AssumeRoleWithLDAPIdentityResult><Credentials><AccessKeyId>P8DNFYBHP9I9NR316HT6</AccessKeyId><SecretAccessKey>pUDqm5NPV18fMUhO3wtiTz3v2zRxny4kG2QM7KMo</SecretAccessKey><Expiration>2021-03-20T00:32:20Z</Expiration><SessionToken>eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJQOERORllCSFA5STlOUjMxNkhUNiIsImV4cCI6MTYxNjIwMDM0MCwibGRhcFVzZXIiOiJjbj1QaGlsaXAgSi4gRnJ5LG91PXBlb3BsZSxkYz1wbGFuZXRleHByZXNzLGRjPWNvbSJ9.pa64lyWc_VCHxp8_MtqKKwq5N2rjYgvCKcPyQ4mrbXZXg8tIRbNV2SEXaE2BXgJFXmFAMhgORhSBGUGTntfqcg</SessionToken></Credentials></AssumeRoleWithLDAPIdentityResult><ResponseMetadata><RequestId>166D21323504BB20</RequestId></ResponseMetadata></AssumeRoleWithLDAPIdentityResponse>* Closing connection 0
```

**Comment by harshavardhana** [comment]
@sytolk STS API is an AWS STS API so it is always XML  -> "application/json" is not meaningful  here.

**Comment by sytolk** [comment]
@harshavardhana is this means that STS API is closed source and cannot be changed?

**Comment by harshavardhana** [comment]
STS API is based on this https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html and it will always be XML - I don't know what is closed source here. 

All the code is available at https://github.com/minio/minio

**Comment by sytolk** [comment]
@harshavardhana  maybe AWS use 15 years old SOAP web service that always return XML.. but if minio use REST API for STS you can easy convert XML output to JSON based on client `Accept:` header: 

https://docs.oracle.com/cd/E50245_01/E50253/html/vmapi-rest-mediatype.html

And this will not break AWS specification

**Comment by harshavardhana** [comment]
> @harshavardhana maybe AWS use 15 years old SOAP web service that always return XML.. but if minio use REST API for STS you can easy convert XML output to JSON based on client `Accept:` header:
> 
> https://docs.oracle.com/cd/E50245_01/E50253/html/vmapi-rest-mediatype.html
> 
> And this will not break AWS specification

Sorry @sytolk this is beyond our scope.

**Comment by sytolk** [comment]
Ok but can you accept PR for this? I see that minio use this lib for STS API https://github.com/gorilla/mux and I think its easy to create writeSuccessResponseJSON function and place it in end of the Endpoints like this: https://github.com/minio/minio/blob/master/cmd/sts-handlers.go#L258
and switch based on client Accept: header

**Comment by harshavardhana** [comment]
> Ok but can you accept PR for this? I see that minio use this lib for STS API https://github.com/gorilla/mux and I think its easy to create writeSuccessResponseJSON function and place it in end of the Endpoints like this: https://github.com/minio/minio/blob/master/cmd/sts-handlers.go#L258

@sytolk no as I said it is out of scope - we don't wish to deviate away from AWS APIs especially at the protocol level.

**Comment by sytolk** [comment]
Ok i will write this issue to AWS :)
