### ISSUE TITLE
assetFS redeclared: make error, build failure 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1182]
Running on OSX El Captain. 
go version go1.6 darwin/amd64

Here is the log of the `make`

```
Checking deps:
Check for supported arch.. Check for supported os.. Checking if proper environment variables are set.. Done
Using GOPATH=/Users/hackintoshrao/mycode/go and GOROOT=/usr/local/go
Checking dependencies for Minio.. Done
Checking if project is at /Users/hackintoshrao/mycode/go
Installed golint:
Installed vet:
Installed gocyclo:
Installed deadcode:
Installed misspell:
Running vet:
Running fmt:
Running lint:
Running cyclo:
Installing minio:
# github.com/minio/minio
./ui-assets.go:573: assetFS redeclared in this block
    previous declaration at ./routers.go:74
make: *** [gomake-all] Error 2
```

Here simple grep searching for assetFS in the root directory of the project
`$ grep "assetFS"  *.go` 

```
routers.go:func assetFS() *assetfs.AssetFS {
routers.go: minio.Path("/{assets:[^/]+.js|favicon.ico}").Handler(http.StripPrefix(privateBucket, http.FileServer(assetFS())))
routers.go: minio.Path("/{index:.*}").Handler(indexHandler{http.StripPrefix(privateBucket, http.FileServer(assetFS()))})
ui-assets.go:func assetFS() *assetfs.AssetFS {
```

**Comment by harshavardhana** [comment]
> Checking deps:
> Check for supported arch.. Check for supported os.. Checking if proper environment variables are set.. Done
> Using GOPATH=/Users/hackintoshrao/mycode/go and GOROOT=/usr/local/go
> Checking dependencies for Minio.. Done
> Checking if project is at /Users/hackintoshrao/mycode/go
> Installed golint:
> Installed vet:
> Installed gocyclo:
> Installed deadcode:
> Installed misspell:
> Running vet:
> Running fmt:
> Running lint:
> Running cyclo:
> Installing minio:
> 
> # github.com/minio/minio
> 
> ./ui-assets.go:573: assetFS redeclared in this block
>     previous declaration at ./routers.go:74
> make: **\* [gomake-all] Error 2

'make clean' and 'make' again.

**Comment by harshavardhana** [comment]
This is expected since we moved from download assets to top level and vendorized it  'make clean' and 'make' again.

**Comment by hackintoshrao** [comment]
@harshavardhana , `make clean` and `make` is not working for me

**Comment by harshavardhana** [comment]
> @harshavardhana , make clean and make is not working for me

Ah remove the ui-assets.go file 'rm ui-assets.go'

**Comment by hackintoshrao** [comment]
Hmm, that solves the build issues. May be a solution to make it easier would be great.

**Comment by harshavardhana** [comment]
> Hmm, that solves the build issues. May be a solution to make it easier would be great.

There is no way to do that, things are changing rapidly. So brace for it.

**Comment by hackintoshrao** [comment]
Sure :+1:
