### ISSUE TITLE
 Minio starts in terminal fine but not in systemd service

### ISSUE THREAD

**Issue by floodico** [minio/minio#11829]
Actually server started too, but seems that `ExecStart` has't received no exit status. So, in my monitoring system this service shown as failed
<img width="835" alt="Screenshot 2021-03-18 at 19 36 05" src="https://user-images.githubusercontent.com/12949777/111672472-abf29700-8822-11eb-9cec-dfb7d582d3de.png">

**Comment by harshavardhana** [comment]
There is nothing in the issue that you reported for us to help 

- You removed the entire issue template
- You are pasting a screenshot and there is nothing specific that you are asking here
- There is no version information shared.

Closing this issue as incomplete

**Comment by floodico** [comment]
it worked after I removed `Type=forking` from the systemd script. @harshavardhana Thanks for your quick response ;)
