### ISSUE TITLE
Unable to start a dockerized Minio Gateway in SSE-C mode

### ISSUE THREAD

**Issue by dysonfrost** [minio/minio#11827]
## Expected Behavior

I'd like to use Minio Gateway with single encryption (SSE-C) at the gateway. The gateway should encrypt the data then pass it to a S3 compatible bucket (Backblaze), using the following environment variables:

```
MINIO_ACCESS_KEY=<backlaze_access_key>
MINIO_SECRET_KEY=<backblaze_secret_access_key>
MINIO_GATEWAY_SSE="c"
```
Minio should start and I expect to see this output:
```
Endpoint: http://172.17.0.3:9000  http://127.0.0.1:9000 

Browser Access:
   http://172.17.0.3:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

I don’t have KES or KMS configured, just the gateway and my s3 backend. I understand that SSE-C doesn’t require a server side configuration, that’s why I plan to provide the encrypt key to let the gateway handle data encryption. 

## Current Behavior

When I start minio, it displays the following message error:

```
ERROR Unable to start gateway with SSE: MINIO_GATEWAY_SSE set but KMS is not configured
      HINT:
        Refer to https://docs.min.io/docs/minio-kms-quickstart-guide.html for setting up SSE
```

## Possible Solution

I managed to run minio with SSE-C by setting the `MINIO_SSE_MASTER_KEY` environment variable to a random value.

Example: 

```
MINIO_SSE_MASTER_KEY=my-master-key:32-byte-hex-value
```

## Steps to Reproduce (for bugs)

Minio is running in docker, I'm using the following command line:
```sh
docker run -p 9000:9000 --name minio-s3 \
 -e "MINIO_ROOT_USER=<backblaze_access_key>" \
 -e "MINIO_ROOT_PASSWORD=<backblaze_secret_access_key>" \
 -e "MINIO_GATEWAY_SSE=c" \
 minio/minio gateway s3 https://<backblaze-endpoint>
```
using `MINIO_SSE_MASTER_KEY`:

```sh
docker run -p 9000:9000 --name minio-s3 \
 -e "MINIO_ROOT_USER=<backblaze_access_key>" \
 -e "MINIO_ROOT_PASSWORD=<backblaze_secret_access_key>" \
 -e "MINIO_GATEWAY_SSE=c" \
 -e "MINIO_SSE_MASTER_KEY=my-minio-key:ddd43f72bc039b18595a91643c1ae2ee3438f2b63160048b1db8f7117339c18f" \
 minio/minio gateway s3 https://<backblaze-endpoint>
```

## Context

I plan to provide the encrypt key to let the gateway handle data encryption. Minio has to be containerized either with Docker or a container orchestrator like Kubernetes or Nomad.
## Regression

No
## Your Environment

* Version used (`minio --version`):
 minio version `RELEASE.2021-03-17T02-33-02Z` and previous major releases since `RELEASE.2020-07-11T06-07-16Z`
* Operating System and version (`uname -a`): 
Local environment - Darwin 20.3.0; macOS 11.2.1
Live environment - Hashicorp Nomad cluster 1.0.1; Ubuntu server 20.04.1 LTS with kernel 5.4.0-51-generic
Docker version - 20.10.2, build 2291f61 & 20.10.3, build 48d30b5

**Comment by butsjoh** [comment]
There seems to be no clear documentation about it so it is actually also not clear if it should be still used this way or not ...

**Comment by harshavardhana** [comment]
> ERROR Unable to start gateway with SSE: MINIO_GATEWAY_SSE set but KMS is not configured

You can't enable these features without enabling KMS - this feature is meant for encrypting content at gateway layer 

For docs 
https://github.com/minio/minio/blob/master/docs/gateway/s3.md#run-minio-gateway-for-aws-s3-compatible-services

**Comment by butsjoh** [comment]
@harshavardhana The point we are trying to make is that we dont't get the "ERROR Unable to start gateway with SSE: MINIO_GATEWAY_SSE set but KMS is not configured" if we specify a MINIO_SSE_MASTER_KEY. So that means something is working without enabling KMS. And that is nowhere to be found in the documentation. The only reference we found was in the code here https://github.com/minio/minio/blob/209fe61dcc35d53a7bb0f1587dd7e6b32a1c3588/cmd/crypto/config.go#L387. Something about EnvKMSMasterKeyLegacy. There is no documentation about that at all and that is why we are asking the question if this we should still use it or that the default should be a KMS through KES.

**Comment by harshavardhana** [comment]
> @harshavardhana The point we are trying to make is that we dont't get the "ERROR Unable to start gateway with SSE: MINIO_GATEWAY_SSE set but KMS is not configured" if we specify a MINIO_SSE_MASTER_KEY. So that means something is working without enabling KMS. And that is nowhere to be found in the documentation. The only reference we found was in the code here

MINIO_SSE_MASTER_KEY is your KMS its a test KMS with the single master key @butsjoh

**Comment by butsjoh** [comment]
So it should only be used for test purpose then i guess and in production you should have a KMS setup through KES?
