### ISSUE TITLE
mc admin trace missing client info in ipv6

### ISSUE THREAD

**Issue by armsby** [minio/minio#11833]
## Expected behavior
that I would see the full IPv6 address of the client not only the first segment

## Actual behavior
I only see the first segment, witch makes it useless

## Steps to reproduce the behavior
simple trace mc admin trace --json 
## mc --version
mc version RELEASE.2020-11-17T00-39-14Z

{
 "status": "success",
 "host": "minio",
 "time": "2020-11-24T17:10:06.901280106Z",
 "client": "216.18.217.130",
 "callStats": {
  "rx": 190,
  "tx": 1041,
  "duration": 6879148,
  "timeToFirstByte": 0
 },
 "api": "s3.ListObjectsV1",
 "path": "/folder",
 "query": "delimiter=%2F&encoding-type=url&max-keys=1000&prefix="",
 "statusCode": 200,
 "statusMsg": "OK"
}

{
 "status": "success",
 "host": "minio",
 "time": "2020-11-24T17:10:06.903212944Z",
 "client": "2a0e",
 "callStats": {
  "rx": 190,
  "tx": 1041,
  "duration": 6879148,
  "timeToFirstByte": 0
 },
 "api": "s3.ListObjectsV1",
 "path": "/folder",
 "query": "delimiter=%2F&encoding-type=url&max-keys=1000&prefix=",
 "statusCode": 200,
 "statusMsg": "OK"
}

**Comment by klauspost** [comment]
Transfer (to `minio/mc` I suppose) stuck?

**Comment by harshavardhana** [comment]
> Transfer (to `minio/mc` I suppose) stuck?

No I moved it back this needs a server fix I think.
