### ISSUE TITLE
All parts reported as corrupt after an update, but no issues reported by heal

### ISSUE THREAD

**Issue by tongpu** [minio/minio#11839]
## Expected Behavior
MinIO should not report existing files as corrupt after an upgrade.

## Current Behavior
After an update to RELEASE.2021-03-17T02-33-02Z the logs show a lot of entries like the following. According to the log all parts of the file are corrupted, but the data is being returned by e.g. `mc cp` without error and `mc admin heal --scan deep --recursive --dry-run example01` doesn't show any issues with the files.

```
Mar 20 01:02:47 example01 minio[19211]: API: SYSTEM()
Mar 20 01:02:47 example01 minio[19211]: Time: 01:02:47 CET 03/20/2021
Mar 20 01:02:47 example01 minio[19211]: DeploymentID: e63dfdae-1763-40b9-93e2-adb728b50da2
Mar 20 01:02:47 example01 minio[19211]: Error: Disk: /var/lib/minio/data1 -> student-photoid-upload/student_photo_id_1604742663954_5360868.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 01:02:47 example01 minio[19211]:        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
Mar 20 01:02:47 example01 minio[19211]:        1: cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
Mar 20 01:02:47 example01 minio[19211]: API: SYSTEM()
Mar 20 01:02:47 example01 minio[19211]: Time: 01:02:47 CET 03/20/2021
Mar 20 01:02:47 example01 minio[19211]: DeploymentID: e63dfdae-1763-40b9-93e2-adb728b50da2
Mar 20 01:02:47 example01 minio[19211]: Error: Disk: /var/lib/minio/data2 -> student-photoid-upload/student_photo_id_1604742663954_5360868.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 01:02:47 example01 minio[19211]:        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
Mar 20 01:02:47 example01 minio[19211]:        1: cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
Mar 20 01:02:47 example01 minio[19211]: API: SYSTEM()
Mar 20 01:02:47 example01 minio[19211]: Time: 01:02:47 CET 03/20/2021
Mar 20 01:02:47 example01 minio[19211]: DeploymentID: e63dfdae-1763-40b9-93e2-adb728b50da2
Mar 20 01:02:47 example01 minio[19211]: Error: Disk: http://203.0.113.5:9199/var/lib/minio/data2 -> student-photoid-upload/student_photo_id_1604742663954_5360868.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 01:02:47 example01 minio[19211]:        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
Mar 20 01:02:47 example01 minio[19211]:        1: cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
Mar 20 01:02:47 example01 minio[19211]: API: SYSTEM()
Mar 20 01:02:47 example01 minio[19211]: Time: 01:02:47 CET 03/20/2021
Mar 20 01:02:47 example01 minio[19211]: DeploymentID: e63dfdae-1763-40b9-93e2-adb728b50da2
Mar 20 01:02:47 example01 minio[19211]: Error: Disk: http://203.0.113.5:9199/var/lib/minio/data1 -> student-photoid-upload/student_photo_id_1604742663954_5360868.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 01:02:47 example01 minio[19211]:        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
Mar 20 01:02:47 example01 minio[19211]:        1: cmd/erasure-decode.go:164:cmd.(*parallelReader).Read.func1()
Mar 20 01:02:47 example01 minio[19211]: API: SYSTEM(bucket=student-photoid-upload, object=student_photo_id_1604742663954_5360868.jpg)
Mar 20 01:02:47 example01 minio[19211]: Time: 01:02:47 CET 03/20/2021
Mar 20 01:02:47 example01 minio[19211]: DeploymentID: e63dfdae-1763-40b9-93e2-adb728b50da2
Mar 20 01:02:47 example01 minio[19211]: Error: file is corrupted (cmd.StorageErr)
Mar 20 01:02:47 example01 minio[19211]:       15: cmd/erasure-encode.go:84:cmd.(*Erasure).Encode()
Mar 20 01:02:47 example01 minio[19211]:       14: cmd/erasure-lowlevel-heal.go:39:cmd.Erasure.Heal()
Mar 20 01:02:47 example01 minio[19211]:       13: cmd/erasure-healing.go:427:cmd.erasureObjects.healObject()
Mar 20 01:02:47 example01 minio[19211]:       12: cmd/erasure-healing.go:849:cmd.erasureObjects.HealObject()
Mar 20 01:02:47 example01 minio[19211]:       11: cmd/erasure-sets.go:1302:cmd.(*erasureSets).HealObject()
Mar 20 01:02:47 example01 minio[19211]:       10: cmd/erasure-server-pool.go:1598:cmd.(*erasureServerPools).HealObject()
Mar 20 01:02:47 example01 minio[19211]:        9: cmd/data-scanner.go:821:cmd.(*scannerItem).applyActions()
Mar 20 01:02:47 example01 minio[19211]:        8: cmd/xl-storage.go:439:cmd.(*xlStorage).NSScanner.func1()
Mar 20 01:02:47 example01 minio[19211]:        7: cmd/data-scanner.go:470:cmd.(*folderScanner).scanQueuedLevels.func1()
Mar 20 01:02:47 example01 minio[19211]:        6: cmd/os-readdir_unix.go:154:cmd.readDirFn()
Mar 20 01:02:47 example01 minio[19211]:        5: cmd/data-scanner.go:403:cmd.(*folderScanner).scanQueuedLevels()
Mar 20 01:02:47 example01 minio[19211]:        4: cmd/data-scanner.go:254:cmd.scanDataFolder()
Mar 20 01:02:47 example01 minio[19211]:        3: cmd/xl-storage.go:406:cmd.(*xlStorage).NSScanner()
Mar 20 01:02:47 example01 minio[19211]:        2: cmd/storage-rest-server.go:176:cmd.(*storageRESTServer).NSScannerHandler()
Mar 20 01:02:47 example01 minio[19211]:        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
Mar 20 01:02:47 example01 minio[19211]: API: SYSTEM()
Mar 20 01:02:47 example01 minio[19211]: Time: 01:02:47 CET 03/20/2021
Mar 20 01:02:47 example01 minio[19211]: DeploymentID: e63dfdae-1763-40b9-93e2-adb728b50da2
Mar 20 01:02:47 example01 minio[19211]: Error: file is corrupted (cmd.StorageErr)
Mar 20 01:02:47 example01 minio[19211]:        9: cmd/data-scanner.go:826:cmd.(*scannerItem).applyActions()
Mar 20 01:02:47 example01 minio[19211]:        8: cmd/xl-storage.go:439:cmd.(*xlStorage).NSScanner.func1()
Mar 20 01:02:47 example01 minio[19211]:        7: cmd/data-scanner.go:470:cmd.(*folderScanner).scanQueuedLevels.func1()
Mar 20 01:02:47 example01 minio[19211]:        6: cmd/os-readdir_unix.go:154:cmd.readDirFn()
Mar 20 01:02:47 example01 minio[19211]:        5: cmd/data-scanner.go:403:cmd.(*folderScanner).scanQueuedLevels()
Mar 20 01:02:47 example01 minio[19211]:        4: cmd/data-scanner.go:254:cmd.scanDataFolder()
Mar 20 01:02:47 example01 minio[19211]:        3: cmd/xl-storage.go:406:cmd.(*xlStorage).NSScanner()
Mar 20 01:02:47 example01 minio[19211]:        2: cmd/storage-rest-server.go:176:cmd.(*storageRESTServer).NSScannerHandler()
Mar 20 01:02:47 example01 minio[19211]:        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)

1. Deploy distributed MinIO cluster with an old version (e.g. RELEASE.2019-01-10T00-21-20Z)
2. Upgrade cluster to current release (RELEASE.2021-03-17T02-33-02Z)
3. Check logs for error messages

## Context
Because I'm very sure that the data on-disk is fine, I would primarily be interested in figuring out what causes these log messages and how to get rid of them.

## Regression
Possibly a regression with regards to the format on-disk, but I can't provide any more explicit pointers.

## Your Environment
* Version used (`minio --version`): RELEASE.2021-03-17T02-33-02Z
* Server setup and configuration: Debian GNU/Linux 9 (stretch), MinIO distributed mode with 2 nodes and 4 disks
* Operating System and version (`uname -a`): Linux example01 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@tongpu is it listing these all the time?

**Comment by tongpu** [comment]
> @tongpu is it listing these all the time?

It's been showing files as corrupted since the upgrade this morning. According to a quick grep over the log files it seems like it's at least not reporting it multiple times per file, so auto-heal might kick in after the file is being reported as corrupted once.

**Comment by harshavardhana** [comment]
> It's been showing files as corrupted since the upgrade this morning. According to a quick grep over the log files it seems like it's at least not reporting it multiple times per file, so auto-heal might kick in after the file is being reported as corrupted once.

So it is basically healing them @tongpu automatically - the error message is just printed and should be avoided since it was able to successfully heal them.

They were indeed corrupted - i.e some blocks not all the object.

**Comment by tongpu** [comment]
I just found an example in the logs of a file that was reported multiple times:
```
Mar 19 15:14:07 example02 minio[16341]: Error: Disk: /var/lib/minio/data2 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 19 15:14:07 example02 minio[16341]: Error: Disk: /var/lib/minio/data1 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 19 15:14:07 example02 minio[16341]: Error: Disk: http://203.0.113.4:9199/var/lib/minio/data2 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 19 15:14:07 example02 minio[16341]: Error: Disk: http://203.0.113.4:9199/var/lib/minio/data1 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 19 15:14:07 example02 minio[16341]: API: SYSTEM(bucket=krec-thumbnails, object=wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg)
Mar 20 00:00:53 example02 minio[3312]: Error: Disk: /var/lib/minio/data2 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 00:00:53 example02 minio[3312]: Error: Disk: /var/lib/minio/data1 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 00:00:53 example02 minio[3312]: Error: Disk: http://203.0.113.4:9199/var/lib/minio/data1 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 00:00:53 example02 minio[3312]: Error: Disk: http://203.0.113.4:9199/var/lib/minio/data2 -> krec-thumbnails/wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg/part.1 returned file is corrupted (*fmt.wrapError)
Mar 20 00:00:53 example02 minio[3312]: API: SYSTEM(bucket=krec-thumbnails, object=wealth-wisdom-how-ordinary-australians-can-create-extraordinary-wealth-9781742468105.jpg)
```
The different PIDs are because we had to restart the daemons, because we're also facing issues with an unkown process (probably the healing) filling our disk, because `.minio.sys/tmp` is growing very quickly.

**Comment by harshavardhana** [comment]
> The different PIDs are because we had to restart the daemons, because we're also facing issues with an unkown process (probably the healing) filling our disk, because `.minio.sys/tmp` is growing very quickly.

It will get cleaned up every 10minutes @tongpu - we have delayed deletes so that are being put into `.minio.sys/tmp/.trash`

**Comment by tongpu** [comment]
> > The different PIDs are because we had to restart the daemons, because we're also facing issues with an unkown process (probably the healing) filling our disk, because `.minio.sys/tmp` is growing very quickly.
> 
> It will get cleaned up every 10minutes @tongpu - we have delayed deletes so that are being put into `.minio.sys/tmp/.trash`

It's not `.minio.sys/tmp/.trash` that's filling the disk, it's files like `.minio.sys/tmp/$UUID1/$UUID2/part.1` that are using most of the disk space.

Additionally I just realized that the way that data is persisted on disk is different for new uploads and older data. New data uses the file name `bucket/object/$UUID/part.1` for the part, but old data doesn't have the additional UUID directory and uses the filename `bucket/object/part.1`. Is there some way to trigger a migration from the old format to the new format?

**Comment by harshavardhana** [comment]
> Additionally I just realized that the way that data is persisted on disk is different for new uploads and older data. New data uses the file name `bucket/object/$UUID/part.1` for the part, but old data doesn't have the additional UUID directory and uses the filename `bucket/object/part.1`. Is there some way to trigger a migration from the old format to the new format?

Of course that is MinIO writes are you saying that your uploads are not finishing? 

> It's not `.minio.sys/tmp/.trash` that's filling the disk, it's files like `.minio.sys/tmp/$UUID1/$UUID2/part.1` that are using most of the disk space.

This is the actual objects that are getting uploaded.

**Comment by harshavardhana** [comment]
> Additionally I just realized that the way that data is persisted on disk is different for new uploads and older data. New data uses the file name `bucket/object/$UUID/part.1` for the part, but old data doesn't have the additional UUID directory and uses the filename `bucket/object/part.1`. Is there some way to trigger a migration from the old format to the new format?

We cannot do that you need to overwrite it.

**Comment by tongpu** [comment]
> > Additionally I just realized that the way that data is persisted on disk is different for new uploads and older data. New data uses the file name `bucket/object/$UUID/part.1` for the part, but old data doesn't have the additional UUID directory and uses the filename `bucket/object/part.1`. Is there some way to trigger a migration from the old format to the new format?
> 
> Of course that is MinIO writes are you saying that your uploads are not finishing?

No, the uploads are working fine. We haven't encountered any problems with uploads yet. I don't think that we have enough uploads on this system to use 20GB in 2 hours, so I guess there are other processes that also write to this directory (possible the healing process).

> > Additionally I just realized that the way that data is persisted on disk is different for new uploads and older data. New data uses the file name bucket/object/$UUID/part.1 for the part, but old data doesn't have the additional UUID directory and uses the filename bucket/object/part.1. Is there some way to trigger a migration from the old format to the new format?
>
> We cannot do that you need to overwrite it.

Ok, I already tried that with one of the buckets using the following command and it fixed the on-disk format.
```
mc mirror example01/bucket .
mc mirror --overwrite . example01/bucket
```

**Comment by tongpu** [comment]
Overwriting all the data seems to have fixed the issue with corrupted parts being reported. I'm going to monitor the logs for the next days and going to close the issue if this fixed the issue in the end.

**Comment by harshavardhana** [comment]
> Overwriting all the data seems to have fixed the issue with corrupted parts being reported. I'm going to monitor the logs for the next days and going to close the issue if this fixed the issue in the end.

Thanks for the report, going to close anyways - let's reopen if you see it again.
