### ISSUE TITLE
Windows server startup: Error: could not read /proc: CreateFile /proc: The system cannot find the file specified. (*errors.errorString)

### ISSUE THREAD

**Issue by apiszcz** [minio/minio#11837]
Is there a method to debug my problem?

--
```
API: SYSTEM()
Time: 13:35:18 EDT 03/19/2021
DeploymentID: 822162f5-8015-4835-9e0a-621c5d05b056
Error: could not read /proc: CreateFile /proc: The system cannot find the file specified. (*errors.errorString)
       5: cmd\logger\logonce.go:53:logger.(*logOnceType).logOnceIf()
       4: cmd\logger\logonce.go:93:logger.LogOnceIf()
       3: cmd\metrics-v2.go:681:cmd.getMinioProcMetrics.func1()
       2: cmd\metrics-v2.go:1316:cmd.populateAndPublish()
       1: cmd\metrics-v2.go:1282:cmd.ReportMetrics.func1()
```

**Comment by harshavardhana** [comment]
@apiszcz which version of MinIO is this ?

**Comment by apiszcz** [comment]
minio.exe version RELEASE.2021-03-17T02-33-02Z

**Comment by apiszcz** [comment]
When I restart minio as administrator there is no error message.
UPDATE: starting with Administrator privilege's, still seeing the error message above.
This configuration line may cause the error
set MINIO_PROMETHEUS_AUTH_TYPE="public"

**Comment by apiszcz** [comment]
Update the error is caused by using promotheus and the end point /minio/v2/metrics/cluster
The /minio/v2/metrics/node end point does not produce the error message.

**Comment by harshavardhana** [comment]
> Update the error is caused by using promotheus and the end point /minio/v2/metrics/cluster
> The /minio/v2/metrics/node end point does not produce the error message.

this looks like there is some /proc access that is failing can you paste the error once more with 03-17 release? @apiszcz
