### ISSUE TITLE
[CONTRIB/META] Debian/Ubuntu APT Packaging of MinIO

### ISSUE THREAD

**Issue by teward** [minio/minio#11853]
This is not a standard feature request as there is no 'meta' category for things, more that I would like to assist MinIO in getting the programs into distribution repositories for Ubuntu or Debian, or at least help smooth the process over and provide the framework and necessary support to help keep it updated in a repository.

Firstly, some relevant background here on *me* so you know this isn't just an out of the blue request without someone backing it up:
 * I'm an Ubuntu Core Developer and member of the Ubuntu Developer Membership Board and the Ubuntu Community Council.  I am also a supporting member of the Ubuntu Server team (volunteer, unpaid)/  This can be seen on my work on my Launchpad page - https://launchpad.net/~teward
 * I personally maintain a few packages in Debian - `xca` which is an tool for managing X.509 certificates and certificate trees, and `vmfs6-tools` which is an updated `vmfs-tools` for `vmfs6` filesystems.  I have a lot of experience with packaging applications both for Ubuntu and for Debian (as I had to develop the vmfs6 packaging myself) and can provide a lot of guidance on that front if it's desired.
 * I am active on a very regular basis on Ubuntu and Debian environments, because I maintain packages in Debian and have leadership positions in Ubuntu, so I'm very active with lots of enthusiasm and no likelihood of burning out any time soon on those fronts.

I actively use MinIO server and client on my infrastructure and for my clients (via my Consulting LLC) and for my Full Time job as well as for my own personal infrastructure.

As a result, I have to deploy MinIO regularly as services in Ubuntu and Debian environments.  To that extent, it would be amazing to have this in the repositories directly, or for MinIO to provide an apt/deb repository for Ubuntu/Debian systems.

The first question to bring up here is, would MinIO's community variant here that's open source benefit from having guidance and work on getting the packaging ready for use?  Secondly, would MinIO have any issues with me working to get minio server and client into the Debian/Ubuntu repositories, and help keep it maintained (even as a community contribution if not via a MinIO provided repository server)?

(This also extends to the minio client as well - i know that's a separate repository, but there's a quick way to make both generated by the same source package and produce separate installs for the server and client components.)

**Comment by ravindk89** [comment]
Hi @teward 

Thank you for this feature request, and for the offer to help in its implementation. We do provide deb/rpm packages for `minio` and `mc` for download, with download and installation instructions on our [Downloads](https://min.io/download#/linux) page. We also have planned updates to our documentation for highlighting the deb/rpm installation route. We believe this meets the needs of users who prefer installation via a package manager. If you have some suggestions around further improvements to those packages, we'd be happy to hear it.

With regards to the specific request of preparing MinIO components for release to an apt repository, whether self-hosted or upstream, at this time we do not have the engineering resources or cycles to commit to ensuring the long-term success of that feature. We consider package release/maintenance to be a full-time job, and we are fully committed between our existing packages and Docker/K8s releases. 

The answer to your second question is related to the resource constraints mentioned above. Your offer to assist with guidance/ownership/maintenance is very kind and much appreciated. However, we cannot match that enthusiasm with the required engineering resources/cycles to ensure long-term success. Furthermore, it would not be a reasonable burden on a community member, especially given the frequency of our release schedule and the demands of our users/customers for consistent access to the latest stable releases. If at any time you needed to take a break or to step away, we would not necessarily be able to step in and provide the same level of maintenance and support on the upstream side. That carries a significant risk to both parties over time. 

Thank you again for your request.

**Comment by harshavardhana** [comment]
> Hi @teward
> 
> Thank you for this feature request, and for the offer to help in its implementation. We do provide deb/rpm packages for `minio` and `mc` for download, with download and installation instructions on our [Downloads](https://min.io/download#/linux) page. We also have planned updates to our documentation for highlighting the deb/rpm installation route. We believe this meets the needs of users who prefer installation via a package manager. If you have some suggestions around further improvements to those packages, we'd be happy to hear it.
> 
> With regards to the specific request of preparing MinIO components for release to an apt repository, whether self-hosted or upstream, at this time we do not have the engineering resources or cycles to commit to ensuring the long-term success of that feature. We consider package release/maintenance to be a full-time job, and we are fully committed between our existing packages and Docker/K8s releases.
> 
> The answer to your second question is related to the resource constraints mentioned above. Your offer to assist with guidance/ownership/maintenance is very kind and much appreciated. However, we cannot match that enthusiasm with the required engineering resources/cycles to ensure long-term success. Furthermore, it would not be a reasonable burden on a community member, especially given the frequency of our release schedule and the demands of our users/customers for consistent access to the latest stable releases. If at any time you needed to take a break or to step away, we would not necessarily be able to step in and provide the same level of maintenance and support on the upstream side. That carries a significant risk to both parties over time.
> 
> Thank you again for your request.

Closing as per this comment.
