### ISSUE TITLE
s3 client out of memory when uploading small files with high concurrency when deploying minio with a network-file backed mounts

### ISSUE THREAD

**Issue by marchdaisy** [minio/minio#11857]
## Expected Behavior

I use aws-sdk-go s3 client to upload 50000 small files (about 300 bytes) with concurrency 80, deploying the minio server with distributed mode. When the storageclass for pvc is network-file (with Provisioner:fuseim.pri/ifs), the client pod (configured with memory limit 2Gi, and cpu limit 3000m) will be killed due to out of memory. But when the storageclass for pvc is network-block (Provisioner:ceph.com/rbd), all the uploads will be successful with no problem.

## Current Behavior

The client pod will be OOMKilled when minio with network-file backed mounts.

## Possible Solution

Is there some benchmark test for minio with network-file and network-block? 

## Steps to Reproduce (for bugs)

I use a load testing tool Locust to send large amount of files.

## Context

I collected some information by go tool pprof for s3 client when minio is network-file mounts .
During uploading files, the aws-sdk-go process occupied large number of memory in heap.
Showing top 10 nodes out of 20
flat flat% sum% cum cum%
1.82GB 99.81% 99.81% 1.82GB 99.81% github.com/aws/aws-sdk-go/service/s3/s3manager.(*maxSlicePool).newSlice
0 0% 99.81% 1.82GB 99.81% github.com/aws/aws-sdk-go/service/s3/s3manager.(*maxSlicePool).Get 

## Regression

No

## Your Environment

* Version used (`minio --version`): RELEASE.2020-02-27T00-23-05Z
* Server setup and configuration: helm install minio minio-8.0.7.tgz --namespace $NAMESPACE --set existingSecret=minio-secret -- set mode=distributed --set persistentVolumeClaim.size=10Gi --set autoEncryption.enabled=false
* Operating System and version (`uname -a`): Linux minio-0 4.12.14-197.72-default #1 SMP Mon Nov 16 11:40:35 UTC 2020 (ced2a71) x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
The server does not affect client memory usage. You need to file a bug on the `aws-sdk-go` package.

**Comment by marchdaisy** [comment]
@klauspost Just wondering, is there some benchmark test for minio with backed network-file and network-block? Is there a possibility that the request messages are pending in client due to the slow response of minio server with network-file.

**Comment by klauspost** [comment]
@marchdaisy See https://github.com/minio/warp for benchmarks.
