### ISSUE TITLE
S3 Gateway Passthrough SSE-KMS stopped working 

### ISSUE THREAD

**Issue by gacopl** [minio/minio#11865]
## Expected Behavior
aws s3 cli upload to SSE-KMS encrypted bucket should work in recent versions

## Current Behavior
aws s3 cli upload to SSE-KMS encrypted bucket in latest and any higher version than > RELEASE.2020-08-27T05-16-20Z throws this error

 An error occurred (NotImplemented) when calling the PutObject operation: A header you provided implies functionality that is not implemented

## Steps to Reproduce (for bugs)

Use any newer image than RELEASE.2020-08-27T05-16-20Z

`
apiVersion: v1
kind: Pod
metadata:
  name: dvc-minio
  annotations:
    iam.amazonaws.com/role:  s3access
  labels:
    app: dvc-minio
spec:
  containers:
  - name: dvc-minio
    command:
      - minio
      - gateway
      - s3
    ports:
    - name: minio
      containerPort: 9000
    env:
    - name: MINIO_ACCESS_KEY
      value: custom_access_key
    - name: MINIO_SECRET_KEY
      value: custom_secret_key
    image: minio/minio:latest
    imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: dvc-minio
spec:
  selector:
    app: dvc-minio
  type: ClusterIP
  ports:
  - name: dvc-minio
    port: 9000
    targetPort: 9000
 `

**Comment by poornas** [comment]
This was turned off in https://github.com/minio/minio/pull/10484 for predictable behavior across gateways

**Comment by harshavardhana** [comment]
> This was turned off in #10484 for predictable behavior across gateways

Closing
