### ISSUE TITLE
Disable Hostname / IP in signature for presigned url

### ISSUE THREAD

**Issue by marcown** [minio/minio#11870]
Hi,

is there any way to disable hostname / ip check in get/put presigned url (exclude these from calculating the signature)? As noted in another issue #11826 I am using nginx in a docker container and the backend (also part of the same docker network) generates the url (because the data does not always come from minio). 

In my use case this would be super helpful. Again: It's not possible to call get/put presigned url from the frontend.

**Comment by harshavardhana** [comment]
@marcown sorry thats not possible.

**Comment by marcown** [comment]
You are not being helpful. Maybe you could elaborate a bit more about that and why it is not possible? And why is this feature not implemented?

**Comment by harshavardhana** [comment]
> You are not being helpful. Maybe you could elaborate a bit more about that and why it is not possible? And why is this feature not implemented?

It is a security issue @marcown - Host header is a signed header in signature v4.

**Comment by pilare** [comment]
@harshavardhana so how to provide alternative in the call external public path, so presigned urls can be used in docker-compose or kubernetes environments? All the minio documentation is mentioning how to do nginx proxy, and that is working just fine, except it won't work for the presigned signatures. I can see some code for dotnet client (withProxy - not sure if it would do what we are asking here), but nothing for minio-js, which I'm using. [dotnet API](https://docs.min.io/docs/dotnet-client-api-reference.html). Those issues are also mentioned @ngrigoriev in #7857

**Comment by ghost** [comment]
@harshavardhana  If it is a security issue, maybe allow the choose different hostname and port when creating the presigned URL so it can be use in a docker/k8s environment

**Comment by harshavardhana** [comment]
> @harshavardhana If it is a security issue, maybe allow the choose different hostname and port when creating the presigned URL so it can be use in a docker/k8s environment

You can of course choose that on the client-side - Presigned is a fully client-side operation. Has nothing to do with the server code. 

As long as Host: header is preserved when talking to MinIO from the Presigned URL then it will work fine whichever hostname you can use.

**Comment by ghost** [comment]
> > @harshavardhana If it is a security issue, maybe allow the choose different hostname and port when creating the presigned URL so it can be use in a docker/k8s environment
> 
> You can of course choose that on the client-side - Presigned is a fully client-side operation. Has nothing to do with the server code.
> 
> As long as Host: header is preserved when talking to MinIO from the Presigned URL then it will work fine whichever hostname you can use.

I understand, but for example, when working in a docker-compose. I can have a Backend server that talks with minio in `minio:9000`, sign the URL and return it to my frontend application, then I'm unable to download from the frontend via `http://minio:9000/"`  because my local computer can't resolve `minio:9000"` domain, but he can access minio on `http://localhost:9001"` for example.
So I & others would like to generate this pre-signed URL from the backend and to be allowed to choose on what domain/host it would be available for download .

**Comment by harshavardhana** [comment]
> I understand, but for example, when working in a docker-compose. I can have a Backend server that talks with minio in `minio:9000`, sign the URL and return it to my frontend application, then I'm unable to download from the frontend via `http://minio:9000/"` because my local computer can't resolve `minio:9000"` domain, but he can access minio on `http://localhost:9001"` for example.
> So I & others would like to generate this pre-signed URL from the backend and to be allowed to choose on what domain/host it would be available for download .

So you should generate a URL based on `http://localhost:9001` again repeating myself - presigned URL generation is a fully client side operation - you can use any client constructors with various endpoints that you wish to share whichever is resolvable will work fine. 

As long as `Host:` header is preserved.

**Comment by kdopen** [comment]
> presigned URL generation is a fully client side operation 

Maybe I'm misreading the documentation at https://docs.min.io/docs/upload-files-from-browser-using-pre-signed-urls.html, but it sure seems that `presignedPutObject` is being called in the back-end, not from the client. And, when I do this, I get URLs which reference the minio pod inside my kubernetes cluster - NOT the domain name used by nginx for the frontend.
