### ISSUE TITLE
Unable to write all the data to client in S3 gateway mode

### ISSUE THREAD

**Issue by solracsf** [minio/minio#11871]
With latest release `minio version RELEASE.2021-03-17T02-33-02Z` Gateway to AWS S3 has started to output this error very frequently (and it causes objects not displaying):

```
API: GetObject(bucket=my-bucket, object=urn:oid:84)
DeploymentID: a39d1842-0afc-45d8-a2e1-ef933225df71
RequestID: 166F08F0EED5155F
RemoteHost: 127.0.0.1
Host: 127.0.0.1:7100
UserAgent: aws-sdk-php/3.133.27
Error: Unable to write all the data to client io: read/write on closed pipe (*fmt.wrapError)
       2: cmd/object-handlers.go:513:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

Can't reproduce it when downgrading (.deb package) to `minio version RELEASE.2021-02-07T01-31-02Z`

**Comment by harshavardhana** [comment]
> API: GetObject(bucket=my-bucket, object=urn:oid:84)
> DeploymentID: a39d1842-0afc-45d8-a2e1-ef933225df71
> RequestID: 166F08F0EED5155F
> RemoteHost: 127.0.0.1
> Host: 127.0.0.1:7100
> UserAgent: aws-sdk-php/3.133.27
> Error: Unable to write all the data to client io: read/write on closed pipe (*fmt.wrapError)
>        2: cmd/object-handlers.go:513:cmd.objectAPIHandlers.GetObjectHandler()
>        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

This error message can be ignored this is a log that is printed when the client closes the connection @acsfer

**Comment by solracsf** [comment]
Ok for the log, but objects aren't displaying on the frontend when using this latest release. And the page stuks on loading (using Nextcloud) while these logs appear; it doesn't occur with `RELEASE.2021-02-07T01-31-02Z`

This (bad) behaviour only occurs with `minio version RELEASE.2021-03-17T02-33-02Z`

**Comment by harshavardhana** [comment]
All our tests seem to be running fine with the AWS S3 gateway... will have to check. can you explain your setup in detail?

**Comment by solracsf** [comment]
@harshavardhana using a bare metal box under Ubuntu 20.04. Kernel `5.4.0-70-generic`

## Network
```
--- s3.dualstack.eu-west-3.amazonaws.com ping statistics ---
30 packets transmitted, 30 received, 0% packet loss, time 29043ms
rtt min/avg/max/mdev = 0.917/1.039/1.103/0.033 ms
```

## Service file
```
[Unit]
Description = MinIO Gateway

Wants  = network-online.target
After  = network-online.target
Before = nginx.service php7.4-fpm.service

AssertFileIsExecutable = /usr/local/bin/minio
RequiresMountsFor      = /var/cache/minio
AssertPathIsReadWrite  = /var/cache/minio

[Service]
User  = minio
Group = minio

EnvironmentFile = /etc/minio/aws
ExecStart       = /usr/local/bin/minio gateway s3 https://s3.dualstack.eu-west-3.amazonaws.com --address "127.0.0.1:7000"

# Let systemd restart this service always
Restart = always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE = 65536

# Disable timeout logic and wait until process is stopped
TimeoutStopSec = infinity
SendSIGKILL    = no

[Install]
WantedBy = multi-user.target
```
## Environment File
```
MINIO_ACCESS_KEY="AKIAVBJUC44xxxxxxxxxx"
MINIO_SECRET_KEY="ZcQQ/cjuU5wQOh8luGGk8ngxxxxxxxxxxxxx"
MINIO_REGION="eu-west-3"
MINIO_CACHE="on"
MINIO_CACHE_DRIVES="/var/cache/minio"
MINIO_CACHE_EXPIRY=21
MINIO_CACHE_QUOTA=60
MINIO_CACHE_AFTER=1
MINIO_CACHE_WATERMARK_LOW=80
MINIO_CACHE_WATERMARK_HIGH=95
MINIO_BROWSER="off"
```
Then, try to deploy a Nextcloud with it. https://docs.nextcloud.com/server/20/admin_manual/configuration_files/primary_storage.html

## config.php
```
'objectstore' => 
  array (
    'class' => '\\OC\\Files\\ObjectStore\\S3',
    'arguments' => 
    array (
      'bucket' => 'my-bucket',
      'key' => 'AKIAVBJUC44xxxxxxxxxx',
      'secret' => 'ZcQQ/cjuU5wQOh8luGGk8ngxxxxxxxxxxxxx',
      'autocreate' => false,
      'hostname' => '127.0.0.1',
      'port' => 7000,
      'use_ssl' => false,
      'region' => 'eu-west-3',
    ),
  ),
```
At the first launch, Nextcloud will miss many interface icons (stored at S3), and `syslog` logs dozens of:
```
API: GetObject(bucket=my-bucket, object=urn:oid:24)
DeploymentID: ce338346-2a12-41ac-93c8-193d874f5c7d
RequestID: 166F18AAFF4E9DC4
RemoteHost: 127.0.0.1
Host: 127.0.0.1:7000
UserAgent: aws-sdk-php/3.133.27
Error: Unable to write all the data to client io: read/write on closed pipe (*fmt.wrapError)
       2: cmd/object-handlers.go:513:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
Can you reproduce this without cache? @acsfer

**Comment by solracsf** [comment]
Yes, i've tried that too `MINIO_CACHE="off"`. Same behaviour @harshavardhana

**Comment by harshavardhana** [comment]
> Yes, i've tried that too `MINIO_CACHE="off"`. Same behaviour @harshavardhana

Is there a predefined object size where you see this ? does it happen randomly across all objects?

**Comment by solracsf** [comment]
Well, as this happens essentially at install times, all files are <2Mb, some just a few bytes (mainly these are interface  - assets - files).

**Comment by harshavardhana** [comment]
> Well, as this happens essentially at install times, all files are <2Mb, some just a few bytes (mainly these are interface - assets - files).

what is an install time?

**Comment by solracsf** [comment]
As i've reported at https://github.com/minio/minio/issues/11871#issuecomment-805310599 this mainly happens when trying to install/deploy the software.

**Comment by ToLToL** [comment]
Hi,

I don't know if it's related but with `2021-03-10T05:11:33Z`, distributed setup I sometimes have:

```
API: GetObject(bucket=mybucket, object=pikachu.png)
Time: 18:31:36 UTC 03/23/2021
DeploymentID: 1543b90c-3079-4a27-a8f3-14135f9a5c10
RequestID: 166F0C48621F3D2B
RemoteHost: {IP}
Host: {IP}
UserAgent: aws-sdk-php/3.133.27
Error: Unable to write all the data to client write tcp {IP}->{IP}: write: connection reset by peer (*fmt.wrapError)
       objectErasureMap=map[pikachu.png:{1 1 [/mnt/data1 https://minio1.dev:9000/mnt/data0 https://minio2.dev:9000/mnt/data0 /mnt/data2 https://minio1.dev:9000/mnt/data1 https://minio2.dev:9000/mnt/data1 /mnt/data3 https://minio1.dev:9000/mnt/data2 https://minio2.dev:9000/mnt/data2 /mnt/data0 https://minio1.dev:9000/mnt/data3 https://minio2.dev:9000/mnt/data3]}]
       2: cmd/object-handlers.go:513:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

Didn't have this problem with `minio/minio:RELEASE.2021-03-04T00-53-13Z`.

**Comment by harshavardhana** [comment]
This is not related @ToLToL - this is when client disconnected before reading all content "connection reset by peer" - happens with browsers.

**Comment by poornas** [comment]
Tested with RELEASE.2021-03-17T02-33-02Z for both stand alone gateway and in conjunction with nextcloud - could not repro any issue. Is it possible that you are being rate limited by AWS or have poor network - MinIO gateway just does a pass through and was expecting to read more when the pipe was closed

**Comment by solracsf** [comment]
Ok i'm closing then; i dont think its one or another, as i have a full 1Gbps connection on the bare metal and the AWS endpoint pings in less than 1sec, and AWS would not rate limit the creation of 50 small files... Thanks anyway.
