### ISSUE TITLE
chroot minio start in server or gateway mode fails without config dir

### ISSUE THREAD

**Issue by rajeshamdev** [minio/minio#11872]
Trying to start minio in server and gateway mode with chroot using golang os/exec pkg cmd.Run().
I am on minio version RELEASE.2021-02-07T01-31-02Z. Also tried with the latest RELEASE.2021-03-17T02-33-02Z.
Server or gateway start fails.

Cmd: /usr/sbin/chroot /mnt/minio/299 /bin/minio gateway nas --json --certs-dir /ssl/certs --address localhost:9001 /mnt299

The same will succeed with -C:
Cmd: /usr/sbin/chroot /mnt/minio/299 /bin/minio gateway nas --json -C /conf --certs-dir /ssl/certs --address localhost:9001 /mnt299

Although "-C" option is workaround, this option is hidden.

[root@lsdev]# minio
NAME:
  minio - High Performance Object Storage

DESCRIPTION:
  Build high performance data infrastructure for machine learning, analytics and application data workloads with MinIO

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   start object storage server
  gateway  start object storage gateway
  
FLAGS:
  --certs-dir value, -S value  path to certs directory (default: "/root/.minio/certs")
  --quiet                      disable startup information
  --anonymous                  hide sensitive information from logging
  --json                       output server logs and startup information in json format
  --help, -h                   show help
  --version, -v                print the version
  
VERSION:
  RELEASE.2021-03-17T02-33-02Z 
## Expected Behavior
server or gateway without config dir option should succeed.

## Current Behavior

Fails ith below error:
error: {"level":"FATAL","errKind":"","time":"2021-03-23T19:32:33.580227507Z","error":{"message":"Invalid arguments specified","source":["cmd/common-main.go:218:cmd.handleCommonCmdArgs()"]}}

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Seems to run perfectly fine locally 

```
~ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway nas --certs-dir /tmp/test --json --address ":9091" ~/Downloads/

^C{"level":"INFO","errKind":"","time":"2021-03-23T20:39:52.338027741Z","message":"Exiting on signal: INTERRUPT\n"}

~ minio -version
minio version DEVELOPMENT.2021-03-23T20-23-54Z
```

**Comment by rajeshamdev** [comment]
@harshavardhana: As I described, running with chroot with cmd.Run() fails. The error comes from:

https://github.com/minio/minio/blob/RELEASE.2021-03-17T02-33-02Z/cmd/common-main.go#L218
globalConfigDir, configSet = newConfigDirFromCtx(ctx, "config-dir", defaultConfigDir.Get)

**Comment by harshavardhana** [comment]
> @harshavardhana: As I described, running with chroot with cmd.Run() fails. The error comes from:

@rajeshamdev we do not test chroot - you can try setting HOME=/chroot

**Comment by harshavardhana** [comment]
Just tested locally works properly

```
~ sudo chroot --userspec harsha:harsha /tmp/${USER} /bin/minio server --json -C /conf --certs-dir /certs --address "localhost:9001" /data
```

**Comment by rajeshamdev** [comment]
@harshavardhana: Even though `certs-dir` option selected, minio server code still looks for `homedir` and creates empty `.minio ` dir which I think is unnecessary.

**Comment by harshavardhana** [comment]
> @harshavardhana: Even though `certs-dir` option selected, minio server code still looks for `homedir` and creates empty `.minio ` dir which I think is unnecessary.

We need that unfortunately for now @rajeshamdev
