### ISSUE TITLE
Same port is used for infra and users API

### ISSUE THREAD

**Issue by sgandon** [minio/minio#11879]
**Is your feature request related to a problem? Please describe.**
The health check, the metrics and the user/admin API are served on the same port.
This makes it cumbersome to setup restrcition access to infra APIs because we need to configure our ingress controller for specific routings and non routing to prevent the use of those infra APIs publically.
More over if we want to prevent access to them we need to know the routes we want to prevent.
I am also inclined to think that using one single port augments the attack surface of the service.

**Describe the solution you'd like**
A lot of tools provide [different ports](https://artifacthub.io/packages/helm/bitnami/postgresql#metrics) for metrics or health check that ease the setup of the service not requiring to fiddle with the gateway route to prevent any missuse of those APIs.
One possible solution to support backward compatilibity would be to use optionnal environment variables for overriding the default unique port behaviour.

**Describe alternatives you've considered**
As mentionned the work around that is to configure the gateway routing but this requires knowledge of the route.

**Comment by zapto2600** [comment]
This is something I have been considering raising also. Its bad practice to have all of your management and user API endpoints on the same port. 

Splitting these out would make alot of security sense.

**Comment by harshavardhana** [comment]
MinIO is designed to require minimal ports on the system, i.e one listening port. You can isolate the traffic based on policies - security is policy-driven not port-driven. 

You apply relevant policies to restrict access for incoming IPs to User-Agents or whatever.  

I don't think we have an interest in making this change in design for now.
