### ISSUE TITLE
MC Admin Info to return Cluster available space 

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11883]
As an administrator I would like to see the cluster free space as well as the usage space when you run mc admin info myminio. This would allow easier reconciliation or troubleshooting without having to look at other systems or metrics. 

**Describe alternatives you've considered**
Using other metric endpoints is ok. But having it in mc admin info would help alot. Currently used space, bucket and object count is exposed. 

0 B Used, 1 Bucket, 0 Objects
12 drives online, 0 drives offline

I wasn't sure if this was a Server FR or a MC FR please feel free to move.

**Comment by harshavardhana** [comment]
mc admin info --json provides the necessary information.. 

The main reason is we don't have available real-estate to provide on the command UI. To get more in-depth details it's better to use `mc admin info --json`

For more UI friendly you are advised to use https://github.com/minio/console
