### ISSUE TITLE
Memory exhausted for releases newer than RELEASE.2021-03-04T00-53-13Z

### ISSUE THREAD

**Issue by lukasertl** [minio/minio#11888]
I'm running a cluster with 6 nodes, holding approx. 1TB of data in 200.000 objects.  Up until RELEASE.2021-03-04T00-53-13Z the memory usage was quite constant (~1GB), but newer releases cause the minio process to grow larger and larger until it uses up all RAM, at a rate of ~8GB/hour.

This is a memory profile I gathered from one of the hosts:

```
File: minio
Type: inuse_space
Time: Mar 24, 2021 at 9:51pm (CET)
Showing nodes accounting for 1413379.54kB, 93.54% of 1510931.70kB total
Dropped 862 nodes (cum <= 7554.66kB)
      flat  flat%   sum%        cum   cum%
272009.90kB 18.00% 18.00% 272009.90kB 18.00%  github.com/klauspost/compress/s2.NewWriter.func1
  262144kB 17.35% 35.35%   262144kB 17.35%  github.com/minio/minio/pkg/argon2.NewIDKey.func1
251464.53kB 16.64% 52.00% 251464.53kB 16.64%  bufio.NewReaderSize (inline)
251404.22kB 16.64% 68.63% 251404.22kB 16.64%  bufio.NewWriterSize (inline)
139543.37kB  9.24% 77.87% 139543.37kB  9.24%  bytes.makeSlice
48738.46kB  3.23% 81.10% 48738.46kB  3.23%  github.com/minio/minio/pkg/ioutil.ReadFile
37505.33kB  2.48% 83.58% 37747.80kB  2.50%  io.copyBuffer
36524.82kB  2.42% 86.00% 36734.80kB  2.43%  github.com/klauspost/compress/s2.NewWriter
19366.36kB  1.28% 87.28% 33424.74kB  2.21%  crypto/x509.parseCertificate
```

## Regression
Is this issue a regression? Yes, started with RELEASE.2021-03-10T05-11-33Z

## Your Environment

minio version RELEASE.2021-03-10T05-11-33Z
CentOS Linux release 8.3.2011

**Comment by harshavardhana** [comment]
> 272009.90kB 18.00% 18.00% 272009.90kB 18.00%  github.com/klauspost/compress/s2.NewWriter.func1

Provide more details about your deployment - are you using compression for your objects?

**Comment by klauspost** [comment]
@lukasertl Could you capture a memory+goroutine profile after the server has used more memory and attach them here.

It is possible to see which system is actually holding on to the memory and can just as easily be `argon2.NewIDKey`.

**Comment by lukasertl** [comment]
> Provide more details about your deployment - are you using compression for your objects?

Compression settings are default:

```
compression enable=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml allow_encryption=off
```

> @lukasertl Could you capture a memory+goroutine profile after the server has used more memory and attach them here.

I've attached the profile.  This is with version 2021-03-10T05:11:33Z - 30 minutes after startup the process has ~5GB RAM.

[profile.tar.gz](https://github.com/minio/minio/files/6205290/profile.tar.gz)

**Comment by klauspost** [comment]
@lukasertl Thanks! I will take a look ASAP.

**Comment by klauspost** [comment]
@lukasertl It seems there are a lot of canceled listings going on. IOPS must be through the roof, the memory usage is just a side effect. Making sure they are properly canceled in the linked PR.

**Comment by lukasertl** [comment]
Interestingly, IOPS are very moderate, with any version I'm seeing an average of 200 IOPS on the system.  I wouldn't consider that as extreme. :-)

**Comment by klauspost** [comment]
@lukasertl ok, the listings are probably blocked then.
