### ISSUE TITLE
Show XML instead of redirecting to login when encountering error

### ISSUE THREAD

**Issue by Weilbyte** [minio/minio#11896]
**Is your feature request related to a problem? Please describe.**
When the UI is enabled, Minio redirects to login screen when encountering an error such as missing permissions or unavailable file.

**Describe the solution you'd like**
There should be an option to have Minio show the XML output in these situations and redirect to login only when provided with `/`/no path.

**Comment by harshavardhana** [comment]
This is a UI feature for browser requests, turn off MINIO_BROWSER=off you will get what you want.

**Comment by Weilbyte** [comment]
@harshavardhana Setting `MINIO_BROWSER` to `off` from what I can see disables the login feature as well though. Is there a way to have both the panel and XML responses on at the same time depending on the path?

**Comment by harshavardhana** [comment]
> @harshavardhana Setting `MINIO_BROWSER` to `off` from what I can see disables the login feature as well though. Is there a way to have both the panel and XML responses on at the same time depending on the path?

@Weilbyte unfortunately no, you are better off turning the in-built browser instead point your users to https://github.com/minio/console - a better revamped UI.

**Comment by Weilbyte** [comment]
> > @harshavardhana Setting `MINIO_BROWSER` to `off` from what I can see disables the login feature as well though. Is there a way to have both the panel and XML responses on at the same time depending on the path?
> 
> @Weilbyte unfortunately no, you are better off turning the in-built browser instead point your users to https://github.com/minio/console - a better revamped UI. 

That's just what I needed. Thank you!
