### ISSUE TITLE
minio help doesn't work as expected

### ISSUE THREAD

**Issue by fwessels** [minio/minio#1190]
```
$ minio help
minio: <FATAL> ‘help’ is not a minio sub-command. See ‘minio help’.
```

I would suggest to implement it for consistency reasons...

**Comment by harshavardhana** [comment]
> I would suggest to implement it for consistency reasons...

yeah it is implemented as '--help' it is intentional that we removed 'help' - but that message needs to be fixed.

**Comment by krishnasrinivas** [comment]
error message should be:
`minio: <FATAL> ‘help’ is not a minio sub-command. See ‘minio --help’.`

**Comment by krishnasrinivas** [comment]
> but that message needs to be fixed.

Ah, you already noted that.

**Comment by harshavardhana** [comment]
This issue is closed, in current master.
