### ISSUE TITLE
runtime: failed to create new OS thread on high loads.

### ISSUE THREAD

**Issue by dkhachyan** [minio/minio#11915]
## Current Behavior

When reading a large number of small objects minio crashes with error:
```
runtime: failed to create new OS thread (have 1025 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

## Environment
* Minio Version: RELEASE.2021-03-17T02-33-02Z
* MinIO Operator Version: 4.0.3
* Server setup and configuration: OpenShift 4.7
* Operating System and version: FCOS 33
* Kernel version: 5.10.12-200.fc33.x86_64

**Comment by klauspost** [comment]
@dkhachyan Have you tried following the suggestion, ie. increase ulimit?

**Comment by dkhachyan** [comment]
> @dkhachyan Have you tried following the suggestion, ie. increase ulimit?

Current  limits:
```
bash-4.4$ ulimit -aH 
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 513997
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4194304
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
I think max user processes is enough.

```
sh-4.4$ cat /proc/sys/kernel/threads-max
1027994
```

**Comment by klauspost** [comment]
Something on  your system is restricting the number of [clone](https://man7.org/linux/man-pages/man2/clone.2.html) calls.

Maybe check `cat /proc/PID of minio/limits | egrep "(processes|files)"`

Either way your system is overloaded and this is the first limit you hit. You can limit the number of concurrent requests to avoid crashes. See "api" section here: https://docs.min.io/docs/minio-server-configuration-guide.html
