### ISSUE TITLE
Minio quota limit popup in web ui

### ISSUE THREAD

**Issue by DAGorchakov** [minio/minio#11925]
**Is your feature request related to a problem? Please describe.**
If quota is setup in minio `mc admin bucket quota TARGET/BUCKET --hard LIMIT` user does not know about it and when user reaches this limit he has no information about it and doesn`t know why file is stuck

**Describe the solution you'd like**
Is it possible to do popup for user about quota\limit? Something like `limit 50MB for this bucket`

**Describe alternatives you've considered**
Maybe it is possible to show progress bar with bucket_size \ bucket_limit in top of Minio page? 

**Additional context**
It is a big deal to reply for every customer the reason for 'stuck upload file'
![image](https://user-images.githubusercontent.com/17656075/112955008-a6148400-9147-11eb-94d9-1b36db88be84.png)

**Comment by harshavardhana** [comment]
MinIO embedded UI is deprecated and not taking any more features - start asking for such feature requests at https://github.com/minio/console
