### ISSUE TITLE
Field with date type is in integer when selecting a parquet file

### ISSUE THREAD

**Issue by mailsmail** [minio/minio#11926]
When selecting object with parquet format, I've found that if the field is a `date` type it will gives you an integer instead of a date. 

I found that the integer is a number of day since epoch (Jan 1st, 1970). So, from the example below  (in expected behavior and current behavior) 9568 is the number of days since 1970-01-01 to 1996-03-13.

After reading the documentation of github.com/xitongsys/parquet-go (because the parquet-go used in here is a modified version of that library), date type (`DATE`) is a logical type, and the primitive type is `INT32`. So, I think the issue is caused by the use of primitive type instead of logical type. 

## Expected Behavior

This is the expected result (output from AWS S3 Select):

```
1996-03-13
1996-04-12
1996-01-29
1996-04-21
1996-03-30
1996-01-30
```

## Current Behavior

Currently, the output is an integer like this:

```
9568 
9598 
9524 
9607 
9585 
9525
```

## Possible Solution

Maybe change the check in [here](https://github.com/minio/minio/blob/edf053c5c90c7e526912b8a68353914d3ef17f0b/pkg/s3select/parquet/reader.go#L61-L77) by using logical type instead of primitive type.

## Steps to Reproduce (for bugs)

Use this file: [lineitem_shipdate.zip](https://github.com/minio/minio/files/6227968/lineitem_shipdate.zip)

1. Using AWS CLI, execute this command:

```shell
aws s3api select-object-content \
  --bucket test \
  --key lineitem_shipdate.parquet \
  --expression "SELECT * FROM S3Object LIMIT 5" \
  --expression-type SQL \
  --input-serialization '{"Parquet":{}}' \
  --output-serialization '{"CSV":{}}' \
  /dev/stdout
```

## Your Environment

* Version used (`minio --version`): minio version DEVELOPMENT.2021-03-30T09-37-21Z

**Comment by klauspost** [comment]
@mailsmail Added some basic date support in #11928
