### ISSUE TITLE
PutObjectLegalHold using the s3 API fails

### ISSUE THREAD

**Issue by champds** [minio/minio#11920]
## Current Behavior
Request like this:
```javascript
let toSubmit = {Bucket: bucketName, Key: key, LegalHold: {Status: "ON"}};
let legalHoldCommand = new PutObjectLegalHoldCommand(toSubmit);
let legalHoldResult = await this.s3.send(legalHoldCommand);
```

indicates that the MD5 was not calculated, so we go this route:
```javascript
let toSubmit = {Bucket: bucketName, Key: key, LegalHold: {Status: "ON"}};
    toSubmit.ContentMD5 = crypto.createHash('md5').update('').digest('base64');
let legalHoldCommand = new PutObjectLegalHoldCommand(toSubmit);
let legalHoldResult = await this.s3.send(legalHoldCommand;
```

But then we see this error:
```
minio4_1  | API: PutObjectLegalHold(bucket=bucket3, object=foo99)
minio4_1  | Time: 18:42:04 UTC 03/29/2021
minio4_1  | DeploymentID: b60b8001-7b84-41ba-940e-c06713c09bf2
minio4_1  | RequestID: 1670E455FC9412DE
minio4_1  | RemoteHost: 192.168.XX.YY
minio4_1  | Host: minio4:9000
minio4_1  | UserAgent: aws-sdk-js/3.10.0
minio4_1  | Error: expected element type <LegalHold> but have <ObjectLockLegalHold> (xml.UnmarshalError)
minio4_1  |        4: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
minio4_1  |        3: cmd/api-errors.go:2034:cmd.toAPIError()
minio4_1  |        2: cmd/object-handlers.go:2978:cmd.objectAPIHandlers.PutObjectLegalHoldHandler()
minio4_1  |        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()`
```

## Your Environment
* Version: minio/minio:RELEASE.2021-03-26T00-00-41Z (although we've tried other previous releases; same issue)
* Server setup and configuration:  Docker on CentOS 7 (4 nodes)

**Comment by harshavardhana** [comment]
This looks like XML element that is sent is incorrect which SDK are you using here? @champds

**Comment by harshavardhana** [comment]
S3 API documents this as `<LegalHold>` https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLegalHold.html

**Comment by champds** [comment]
@harshavardhana - thanks - we've tried using several versions, but latest was 3.10.0

**Comment by champds** [comment]
Looks like this is a compat issue w/ S3, as they must allow it.  From all tested versions of the s3-client, we see it requesting (via packet capture):
### Not Working (PUT)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ObjectLockLegalHold xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Status>ON</Status>
</ObjectLockLegalHold>
```

### Working (GET) (response from Minio)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<LegalHold xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Status>ON</Status></LegalHold>
```

**Comment by harshavardhana** [comment]
> Looks like this is a compat issue w/ S3, as they must allow it. From all tested versions of the s3-client, we see it requesting (via packet capture):
> 
> ### Not Working (PUT)
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <ObjectLockLegalHold xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
>   <Status>ON</Status>
> </ObjectLockLegalHold>
> ```
> 
> ### Working (GET) (response from Minio)
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <LegalHold xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Status>ON</Status></LegalHold>
> ```

We only support what they documented @champds - the naming convention changing is beyond our control.

**Comment by champds** [comment]
@harshavardhana - thanks so much.   Absolutely understand.  Clearly an AMZ issue; we'll track it from that end and post any updates here.  Hopefully this thread helps someone else.

Thanks Again!

**Comment by harshavardhana** [comment]
FWIW sending a fix anyways to have fallbacks in our code

**Comment by champds** [comment]
Confirmed operation on this end.  Amazing, Minio!  Thanks so much for the addition to handle the Amazon problems.
