### ISSUE TITLE
Bucket Lifecycle to slow with many many small files

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio#11924]
## Expected Behavior
Old files should be deleted regularly.

## Current Behavior
I noticed that there are still files from January which didn't get deleted yet. I restarted minio and updated from an earlier version (RELEASE.2021-02-01T22-56-52Z) to a new version and it did deleted a few files (I think the newest ones in the folder it starts with) but then it seems to be stuck in one folder scanning all of the other files literally for days (at least that is what I think). I kept minio running and it took days until it deleted a few more files.

My guess is that the scanner is way too slow. I even changed the scanner delay to 5 instead of 10 and it seems to make it a bit faster (I can't really tell) but it's still way to slow and I'm not sure if I just want to reduce the delay even further.

I even enabled debug mode which showed that it keeps scanning slowly each folder (so the log increased way too fast so I didn't keep it running) and it keeps running in the same folder What is interesting however is that if I disable all lifecycle rules while the debug mode was on it still said that the file that is currently scanned has active lifecycle rules. Does an active scanner run for a folder use a cached set of lifecycle rules?

## Possible Solution

I'm not sure if there is a good solution. Maybe there is a way to store the current state of the buckets in a cache and only keep using this cache. I noticed there is some kind of cache involved but also found some mentioning of a full run every 16 cycles. A full run in my case would take weeks which is way too long.

Maybe the scanner can be forked into multiple wroker threads to scan the directory structure faster? Configurable similar to delay?

I think the lifecycle rules should update mid run if they're not doing that already.

It would still be nice to have a bit more insight into what the scanner is doing (as I already asked for here https://github.com/minio/minio/issues/10028). Currently in my case it's not doing anything for days and then removing some files. It's hard to tell where it currently is, how fast it is and how long it will take. At least knowing which folders it already scanned would be nice.

## Steps to Reproduce (for bugs)

1. Have many many files in minio
2. Set up a lifecycle rule
3. Wait for it to finish
4. ...still waiting

## Context

I currently have many many very small json files (1 million per day) in a structure like that within one bucket:
DIRECTION/TASKID/YEAR/MONTH/DAY/*
e.g.
inbound/1ad86290-4a7b-4609-82ad-9e4282218a1a/2021/01/07/*

There are 5 directions with about 200000 files per day each

I've set up lifecycle rules for each direction to delete old files like that e.g.:
``` json
{
      "Expiration": {
        "Days": 50
      },
      "ID": "Delete old inbound files",
      "Filter": { "Prefix": "inbound/" },
      "Status": "Enabled"
}
```

Making a manual delete task works but it's also very slow and I think it should be done by the server instead.

## Regression

No

## Your Environment

* Version used (`minio --version`): 2021-03-26T00:00:41Z
* Server setup and configuration: docker
* Operating System and version (`uname -a`): OS: linux | Arch: amd64 (docker)

**Comment by klauspost** [comment]
The scanner operates at the fastest possible speed without disturbing operations. If you want to make it run faster tweak the delay down further. It is a float value, so you can even set it to `0.5` to make it 10x faster than now.

The scanner runs concurrently on multiple buckets, so maybe some separation will help you.

Rules are read when a cycle starts on a bucket. If not it would end up being inconsistent.
