### ISSUE TITLE
Logs are flooded when audit webhook is not reachable

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#11930]
When an endpoint is not accessible, minio logs are flooded with messages similar to:
```
API: SYSTEM()
Time: 10:28:54 PDT 03/30/2021
DeploymentID: 3f3d26f0-2e9f-4f4b-b1a2-a2a5bffaf938
Error: http://localhost:8088/services/collector/raw returned 'Post "http://localhost:8088/services/collector/raw": dial tcp 127.0.0.1:8088: connect: connection refused', please check your endpoint configuration
 (*fmt.wrapError)
       1: cmd/logger/target/http/http.go:133:http.(*Target).startHTTPLogger.func1()
```
## Expected Behavior
Logs should be printed but not as aggressively

## Current Behavior
Logs are repeated several times per second as seen via stdout or `mc admin console`

## Possible Solution
Not sure if we want to check if the endpoint is back up less often (maybe) or do step off of printing logs

## Steps to Reproduce (for bugs)
1. Start minio
2. Configure audit logger endpoint, e.g. this config pointing to splunk:
```
mc admin config get min audit_webhook
audit_webhook endpoint=http://localhost:8088/services/collector/raw auth_token="Splunk <token>" client_cert= client_key= 
```
3. Stop webhook endpoint
4. Observe stdout or mc admin console

## Context
Not a priority issue but might mask other important logs being sent

## Regression
Unsure

## Your Environment

* Version used (`minio --version`):
Tested against 2021-03-17T02:33:02Z and master with most recent commit: commit edf053c5c90c7e526912b8a68353914d3ef17f0b
* Server setup and configuration:
`export MINIO_PROMETHEUS_AUTH_TYPE="public"; export MINIO_ACCESS_KEY=minio; export MINIO_SECRET_KEY=minio123;  minio server ~/min_data/{1...4}`
* Operating System and version (`uname -a`):
Ubuntu 20.04

**Comment by harshavardhana** [comment]
Fixed in master @eco-minio PTAL - closing this issue.
