### ISSUE TITLE
Healthcheck endpoints redirect to frontend homepage

### ISSUE THREAD

**Issue by to-ny** [minio/minio#11937]
Whenever I try to reach `http://localhost:9000/minio/health/live`, I get redirected to  `http://localhost:9000/minio/login` 

## Expected Behavior
Get a blank page with HTTP status 200

## Current Behavior
Redirect to `http://localhost:9000/minio/login`

## Possible Solution
Didn't look at the code, sorry

## Steps to Reproduce (for bugs)
1. Execute the sample CLI command to launch MinIO

```bash
docker run -p 9000:9000 \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  minio/minio server /data
```
2. Go to http://localhost:9000/minio/health/live

## Context
I get the same error when I try to access the Prometheus metrics on our MinIO instances.

## Regression
Yes. We used to deploy the version  `RELEASE.2020-10-18T21-54-12Z` and the endpoints worked.

## Your Environment

* Version used (`minio --version`): "latest" tag on Docker
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux

Thanks for your help!

**Comment by harshavardhana** [comment]
You can't use browser visit these endpoints.  You should use them appropriately using curl or some other healthcheck tool.
