### ISSUE TITLE
"Unable to write all the data to client" errors on client disconnect

### ISSUE THREAD

**Issue by vcabbage** [minio/minio#11948]
After upgrading to the latest release version (`2021-03-26T00:00:41Z`) we started encountering errors like:

```
Unable to write all the data to client write tcp 172.30.0.118:80->172.30.0.200:3144: write: broken pipe (*fmt.wrapError)
```

This logic was introduced in https://github.com/minio/minio/pull/11659.

## Expected Behavior

I don't believe an error should be logged in this situation. The "do not need to log disconnected clients " comment leads me to believe it's not the desired behavior.

https://github.com/minio/minio/blob/f966fbc4a32fe37e5b964126cc23fe04a2773522/cmd/object-handlers.go#L514-L516

## Current Behavior

Error is logged.

## Possible Solution

I believe (have not verified) `IsNetworkOrHostDown` returns false in this case because the `*net.OpError` isn't wrapped in a `*url.Error`.

https://github.com/minio/minio/blob/f966fbc4a32fe37e5b964126cc23fe04a2773522/pkg/net/url.go#L159-L167

## Regression

I believe this is a regression since these were not previously logged as errors.

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-03-26T00-00-41Z`
* Server setup and configuration: Single server, not replicated.
* Operating System and version (`uname -a`): `4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> ```
> Unable to write all the data to client write tcp 172.30.0.118:80->172.30.0.200:3144: write: broken pipe (*fmt.wrapError)
> ```

this means that your client closed before it read the whole content - we are logging specifically for this reason alone when customers complain that their client is not receiving data. 

you need to configure your load balancer appropriately to ensure that it doesn't close active connections.

**Comment by vcabbage** [comment]
Thanks for the quick reply!

> this means that your client closed before it read the whole content

I understand that. This is expected behavior in our environment since we race requests to multiple servers.

> we are logging specifically for this reason alone when customers complain that their client is not receiving data.

Is the "do not need to log disconnected clients" comment out of date then?

> you need to configure your load balancer appropriately to ensure that it doesn't close active connections.

This doesn't apply to us.

**Comment by harshavardhana** [comment]
> I understand that. This is expected behavior in our environment since we race requests to multiple servers.
> 

Hmm that doesn't make sense that if you issue a GET request and do not read the content - why bother sending a request? 


> Is the "do not need to log disconnected clients" comment out of date then?
>

Disconnected clients do not report as "broken pipe" @vcabbage - broken pipe means a client actively closed the connection in the middle of a read() - that is an error condition that is logged appropriately to indicate what is the issue with the client logic.

**Comment by vcabbage** [comment]
I take it you're not interested in changing this behavior. Fair enough :slightly_smiling_face: Thanks for taking the time to consider the issue.

---

To add more detail about what specifically we're doing (which I should have done from the beginning):

* We run multiple independent servers.
* Clients make requests to both servers simultaneously and use the first response, closing the other.
* We make requests simultaneously rather than sequentially because if a server is down we don't want to wait for a timeout.
* Requests are made with the Minio Go client library. Since the library doesn't send the object request when calling `GetObject`, rather deferring until a read is done, we do `obj.Read(nil)` to verify the object exists, is accessible, etc to the client.

We can always work around this by either using a different call to check the object is accessible or simply ignore the error from the server.
