### ISSUE TITLE
Ability to disable share objects for Minio

### ISSUE THREAD

**Issue by DAGorchakov** [minio/minio#11944]
## Expected Behavior

I just want to know if it is possible to disable the ability for some or all users to use share button (create presigned URLs)? According to this [article](https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html) AWS has this ability, but minio has not keys 's3:authType' and 's3:signatureAge':
> mc: <ERROR> Unable to parse the input policy: invalid condition key 's3:authType'.

> mc: <ERROR> Unable to parse the input policy: invalid condition key 's3:signatureAge'.

## Context

According to policy of our company we have to disable it

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-03-26T00-00-41Z
* Server setup and configuration: CentOS Linux 7 (Core)
* Operating System and version (`uname -a`): Linux gda 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
We should be able to support it @DAGorchakov
