### ISSUE TITLE
Minio won't start due to "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by hkirov** [minio/minio#11965]
We have test setup with two clusters. Cluster 1 is configured with bucket replication to Cluster 2. Cluster 2 was broght down for 48 hours. After that nodes in cluster 2 won't start due to "invalid memory address or nil pointer dereference". Whithoult replication cluster 2 works fine.

## Expected Behavior
Normal start of nodes in cluster and resume of replication.

## Current Behavior
Nodes in cluster die and wont start with replication.

## Steps to Reproduce (for bugs)
1. Configure bucket replication 
2. mc mb --ignore-existing --with-lock myminio1/162
2. mc mb --ignore-existing --with-lock myminio2/162
3. mc version enable myminio1/162
4. mc version enable myminio2/162
5. mc admin bucket remote add myminio1/162 https://XXXXXXXXXXXX:YYYYYYYYYYY@myminio2:9000/162 --service "replication" --region “us-west-1”
6. mc replicate add myminio1/162 --remote-bucket 162 --priority 1 --arn arn:..................:162  --replicate "delete-marker,delete"
7. start uploading data into source bucket (1 file per minute during test)
8. mc admin service stop myminio2
9. keep cluster 2 down for 48 hours
10. start cluster 2

## Context
I want to use server side bucket replication.

## Regression
Not sure.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-03-26T00-00-41Z
* Server setup and configuration: 4 nodes per cluster KVM guests CentOS Linux release 7.9.2009
* Operating System and version (`uname -a`):Linux minre-1.sysm.eu 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* ssh access to nodes can be provided upon request.
* 
[minio2.4.txt](https://github.com/minio/minio/files/6258241/minio2.4.txt)
[minio2.3.txt](https://github.com/minio/minio/files/6258242/minio2.3.txt)
[minio2.2.txt](https://github.com/minio/minio/files/6258243/minio2.2.txt)
[minio2.1.txt](https://github.com/minio/minio/files/6258244/minio2.1.txt)

**Comment by harshavardhana** [comment]
Fixed by #11939
