### ISSUE TITLE
Error: "Storage resources are insufficient for the write operation" when refreshing MinIO Browser.

### ISSUE THREAD

**Issue by xaviermerino** [minio/minio#11961]
I setup a 4 node (4 disks each) cluster of Minio servers. The servers are named:
-  `minio-server-1`
-  `minio-server-2`
-  `minio-server-3`
-  `minio-server-4`

I uploaded some data and then turned off the servers in 2 nodes. As far as I know, only 2 nodes (or half the disks) are required to read the data. And 3 nodes would be required to write more data. 

I can't download the files (through MinIO Browser) and instead I get the following error: `We encountered an internal error, please try again.`

Note: If I bring back one more node, I can download (and upload) just fine. 

## Expected Behavior
I expect to be able to download the files from MinIO Browser since at least 8 disks (or half the nodes) are up. 

## Current Behavior
Currently, when visiting / refreshing the MinIO Browser, the console spits out some errors:
```
API: WebListObjects(bucket=test)
Time: 02:05:58 UTC 04/04/2021
DeploymentID: d6e95954-3e90-4a30-81de-d161c1e586e2
RemoteHost: 10.0.15.1
Host: minio-server-1:9000
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
Error: /cyclebloom "http://minio-server-4:9000/minio/peer/v12": remote server offline (*rest.NetworkError)
       2: cmd/notification.go:604:cmd.(*NotificationSys).findEarliestCleanBloomFilter.func1()
       1: pkg/sync/errgroup/errgroup.go:122:errgroup.(*Group).Go.func1()

API: WebListObjects(bucket=test)
Time: 02:05:58 UTC 04/04/2021
DeploymentID: d6e95954-3e90-4a30-81de-d161c1e586e2
RemoteHost: 10.0.15.1
Host: minio-server-1:9000
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
Error: /cyclebloom "http://minio-server-2:9000/minio/peer/v12": remote server offline (*rest.NetworkError)
       2: cmd/notification.go:604:cmd.(*NotificationSys).findEarliestCleanBloomFilter.func1()
       1: pkg/sync/errgroup/errgroup.go:122:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 02:05:58 UTC 04/04/2021
DeploymentID: d6e95954-3e90-4a30-81de-d161c1e586e2
Error: Write failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       4: cmd/erasure-object.go:709:cmd.erasureObjects.putObject()
       3: cmd/metacache-set.go:678:cmd.(*erasureObjects).listPath.func3.2()
       2: cmd/metacache-stream.go:777:cmd.newMetacacheBlockWriter.func1.2()
       1: cmd/metacache-stream.go:806:cmd.newMetacacheBlockWriter.func1()
```

Then, every now and then I get this error (that keeps on repeating):
```
API: SYSTEM()
Time: 02:00:53 UTC 04/04/2021
DeploymentID: d6e95954-3e90-4a30-81de-d161c1e586e2
Error: Storage resources are insufficient for the write operation .minio.sys/tmp/b37041ad-9332-4b2f-9c7d-9f2194bf319d/eadcaace-4539-4d3f-8b98-06bbef1d8455/part.1 (cmd.InsufficientWriteQuorum)
       1: cmd/data-usage.go:57:cmd.storeDataUsageInBackend()
```

## Steps to Reproduce (for bugs)
1. Start `minio` server.

```
MINIO_ROOT_USER=minioadmin1 MINIO_ROOT_PASSWORD=minioadmin1 minio server --address :9000 http://minio-server-{1...4}/mnt/minio{1...4}/tenant1
```

2. Upload files through MinIO Browser.
3. Disconnect two servers, so that you only leave two up and running.
4. Try to download a file. It fails.

## Context
I was just testing out MinIO. I have a Vagrant environment with 4 VMs and 4 disks attached to each VM. 

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2021-02-24T18-44-45Z`
* Operating System and version (`uname -a`): Ubuntu 20.04 `Linux 5.4.0-58-generic #64-Ubuntu`

**Comment by harshavardhana** [comment]
We cannot list the content since we need to write to the disks @xaviermerino - we require quorum writes to succeed since listing actually creates caches for the content - at the minimum, it has the same requirement as your write quorum for objects. 

You can read the data still if you know the entire path of the object - navigation I am afraid will not work. Bring more disks and more servers - using a 4 disk setup is too small to have any real HA.
