### ISSUE TITLE
api: Incompatibility with S3 behaviour on create bucket 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1196]
Attempt to create multiple buckets with the same name fails on Minio server, but it succeeds on S3. This breaks the compatibility with S3.

This attempt fails

``` go
    minioClient, err := minio.New("localhost:9000", "xxxx", "+xxx", true)
    if err != nil {
        log.Fatalln(err)
    }
    for i := 0; i < 10; i++ {
        err = minioClient.MakeBucket("karthicminio", minio.BucketACL("private"), "us-east-1")
        if err != nil {
            log.Fatalln(err)
        }
        log.Println("Success")
    }

```

Whereas this succeeds, 

``` go
    s3Client, err := minio.New("s3.amazonaws.com", "xxxx", "xxx", false)
    if err != nil {
        log.Fatalln(err)
    }
    for i := 0; i < 10; i++ {
        err = s3Client.MakeBucket("karthicminio", minio.BucketACL("private"), "us-east-1")
        if err != nil {
            log.Fatalln(err)
        }
        log.Println("Success")

    }

```

**Comment by harshavardhana** [comment]
> s3Client, err := minio.New("s3.amazonaws.com", "xxxx", "xxx", false)
>     if err != nil {
>         log.Fatalln(err)
>     }
>     for i := 0; i < 10; i++ {
>         err = s3Client.MakeBucket("karthicminio", minio.BucketACL("private"), "us-east-1")
>         if err != nil {
>             log.Fatalln(err)
>         }
>         log.Println("Success")

This only succeeds for "us-east-1" region, not for other regions. It is S3's limitation :-)

**Comment by hackintoshrao** [comment]
Oh wow! cool...
