### ISSUE TITLE
MINIO_DOMAIN  invalid

### ISSUE THREAD

**Issue by liuaiyuan** [minio/minio#11974]
## Expected Behavior
Show image in browser

## Current Behavior
Opening http://app1.xxx.cc/1.jpg will still be redirected to http://app1.xxx.cc/minio/login

But I can open the image through http://app1.xxx.cc/app1/1.jpg

## Steps to Reproduce (for bugs)
``` shell 
export MINIO_DOMAIN=app1.xxx.cc,app2.xxx.cc
export MINIO_ROOT_USER=minioadmin
export MINIO_ROOT_PASSWORD=minioadmin

./minio ./data/
```

## Your Environment
minio version RELEASE.2021-03-26T00-00-41Z

**Comment by harshavardhana** [comment]
> ```shell
> export MINIO_DOMAIN=app1.xxx.cc,app2.xxx.cc
> ```

This needs to be a DOMAIN i.e `xxx.cc` is enough you don't need add your bucket names as part of domain. 

> But I can open the image through http://app1.xxx.cc/app1/1.jpg

You need to make sure your bucket is publicly readable for objects
