### ISSUE TITLE
Minio process falls on SIGSEGV error

### ISSUE THREAD

**Issue by dzp-kulichova** [minio/minio#11971]
Hi,
We run Minio cluster with 3 nodes and 12 drives each. 
Sometimes Minio process fail on error and we need to start it again. 
It happens randomly on any node. We are not able to say what initiated that error.

Minio is started with setsid command on shell scipt which contains this:

```
#!/bin/sh

export MINIO_ROOT_USER=bd_root
export MINIO_ROOT_PASSWORD=<REDACTED>
export MINIO_DOMAIN=bdw01.<REDACTED>.local,bdw02.<REDACTED>.local,bdw03.<REDACTED>.local

/home/minio/minio server --address 0.0.0.0:9900 https://bdw{01...03}.<REDACTED>.local/data/{01...12}/minio
```

Version used: minio version RELEASE.2021-03-26T00-00-41Z
Operating System and version: Linux bdw02 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

We use applications like NiFi and Trino to process data in Minio S3 API. Not any special use of this cluster. 
But, in Trino we have worker nodes together with Minio nodes (yes, no ideal case, but we working on rebuild architecture). On every Trino worker node is configured Minio URL to this same node. For example on worker node bdw01 is Trino configured to comunicate with Minio on bdw01, and on bdw02 is Trino configured to comunicate with Minio on bdw02. Could be this source of problem?

After some time in console we got error in Minio and process on that node end:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ac832]

goroutine 1786957 [running]:
io.(*nopCloser).Read(0xc0175a0730, 0xc007de8000, 0x2000, 0x2000, 0x40db9b, 0xc0175a0720, 0x40a6bf)
        <autogenerated>:1 +0x32
io.discard.ReadFrom(0x7fa16ba8f2c0, 0xc0175a0730, 0x1d141e0, 0x1, 0x7fa16bb906c8)
        io/io.go:598 +0x95
io.copyBuffer(0x279d760, 0x3494ec0, 0x7fa16ba8f2c0, 0xc0175a0730, 0x0, 0x0, 0x0, 0x0, 0xc0175a0701, 0xc002cf3d40)
        io/io.go:409 +0x357
io.Copy(...)
        io/io.go:382
github.com/minio/minio/cmd/http.DrainBody(0x27b5778, 0xc0175a0730)
        github.com/minio/minio/cmd/http/close.go:40 +0xdd
github.com/minio/minio/cmd.(*storageRESTClient).CreateFile(0xc0008e1400, 0x27cc988, 0xc0000420d8, 0x1f42bbe, 0xe, 0xc00089cc90, 0x2b, 0x1001000, 0x279ac60, 0xc007132130, ...)
        github.com/minio/minio/cmd/storage-rest-client.go:346 +0x53c
github.com/minio/minio/cmd.newStreamingBitrotWriter.func1(0x1000000, 0x20000, 0x27d15c0, 0xc0022265b0, 0xc007132130, 0x27f3658, 0xc0008e1400, 0x1f42bbe, 0xe, 0xc00089cc90, ...)
        github.com/minio/minio/cmd/bitrot-streaming.go:85 +0x104
created by github.com/minio/minio/cmd.newStreamingBitrotWriter
        github.com/minio/minio/cmd/bitrot-streaming.go:79 +0x2bd
```

**Comment by harshavardhana** [comment]
This is fixed in #11939
