### ISSUE TITLE
Configuring MinIO Gateway for Azure blob storage

### ISSUE THREAD

**Issue by subhankarc** [minio/minio#11994]
We would like to configure MinIO gateway to connect to Azure blobstore. The example in https://docs.min.io/docs/minio-gateway-for-azure.html for configuring Azure blob storage in minio gateway expects `azureaccountname` and `azureaccountkey`. In our case, we get access to a container only via blob `sas_token`. so we have a `container_uri` and a blob `sas_token`. Can we configure minio gateway with that to do blob operations within that container ?

**Comment by nitisht** [comment]
Please use Slack (https://slack.min.io) for such questions @subhankarc . Closing this issue.

**Comment by niteshagrawalgmail** [comment]
@nitisht the question is asked here : https://minio.slack.com/archives/C3NDUB8UA/p1617789770277100
can someone reply on that thread.
