### ISSUE TITLE
document: HTTP rate/connections limit for minio server.

### ISSUE THREAD

**Issue by klausenbusk** [minio/minio#1200]
Rate: Max X request/s global and per ip
Connection: Max X simultaneous connections global and per ip

**Comment by klausenbusk** [comment]
Use-case: If you have fixed bandwidth (ex. 100/100), and you need to distribute a large files to many clients, then it is more optimal to let 10 clients download with 10 megabit each than 500 clients downloading at 0,2 megabit.

**Comment by abperiasamy** [comment]
You can use iptables (mangle) + tc to limit your outgoing http bandwidth. We will test it and make a simple howto.

**Comment by klausenbusk** [comment]
> You can use iptables (mangle) + tc to limit your outgoing http bandwidth. We will test it and make a simple howto.

I don't want to limit outgoing bandwidth but max simulations connections, so every request run as short time as possible.
I prefer 10 connections finishing every minute instant of 100 connections finishing every 10 minute, if that make sense?

**Comment by GarimaKapoor** [comment]
This has been in master with MINIO_MAXCONN environment variable. 

```
$ MINIO_MAXCONN=128 minio server <dir>
```
