### ISSUE TITLE
Support for Authorization Code flow in Minio browser

### ISSUE THREAD

**Issue by m-pavel** [minio/minio#12003]
Currently minio browser uses implicit flow to integrate with openid authorization server. Which is not recommended and going to be  excluded from Oauth 2.1 spec (https://tools.ietf.org/html/draft-ietf-oauth-v2-1-02).
I would like to have support of Authorization Code flow in minio browser.

**Comment by harshavardhana** [comment]
MinIO browser is deprecated and not taking any more features - start using https://github.com/minio/console
