### ISSUE TITLE
Implement ForAllValues and ForAnyValue set operators in Condition

### ISSUE THREAD

**Issue by artm** [minio/minio#12026]
**Is your feature request related to a problem? Please describe.**

We would like to base policy conditions on presence of groups in `jwt:groups` array (same or similar to #11303).

**Describe the solution you'd like**

 The way to do that in AWS is using set operators `ForAnyValue` and `ForAllValues` (see [reference](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html#reference_policies_multi-key-or-value-conditions)), e.g.:

```json
"Resource": ["arn:aws:s3:::xyz-*"],
"Condition": {
    "ForAnyValue:StringLike": {
        "jwt:groups": ["xyz"]
    }
}
```

**Describe alternatives you've considered**

We already have a KeyCloak instance between Minio and the directories the user tokens are coming from, I have considered implementing the access logic there but haven't found a consise and maintainable way to do that.

**Comment by artm** [comment]
I have removed my incorrect assumption that the set operators only combine with `StringLike`, later in the same document they use `"ForAllValues:StringEquals"`

**Comment by artm** [comment]
Having said that, implementing just `ForAnyValue:StringLike` as a single function would already solve a lot of cases while the generic implementation of the operators would take longer to design.

**Comment by artm** [comment]
In the meantime would you have any workaround suggestions? How would I test for a particular value in groups array?

**Comment by harshavardhana** [comment]
> In the meantime would you have any workaround suggestions? How would I test for a particular value in groups array?

There are no workarounds right now unfortunately. @artm

**Comment by fcomte** [comment]
I am very interested in this fonctionnality. I am still lock with the open policy agent to enable this kind of rules.
