### ISSUE TITLE
enhancement: Using Reviewable Github integration for code reviews 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1202]
It would be great if we could use better tools for code review before accepting a PR. I love the experience provided by Reviewable for code reviews, otherwise we may have to end up discussing it over comments with links or copy-paste of the line of code under scrutiny. Here is an example https://github.com/cockroachdb/cockroach/pull/3528

**Comment by harshavardhana** [comment]
> It would be great if we could use better tools for code review before accepting a PR. I love the experience provided by Reviewable for code reviews, otherwise we may have to end up discussing it over comments with links or copy-paste of the line of code under scrutiny. Here is an example cockroachdb/cockroach#3528

We can use,  but it is not really advisable on depending on external tools like reviewable.io unless we really need to - what seems to be the problem with github pull requests and comments?

**Comment by hackintoshrao** [comment]
This is the problem I'm facing. Let's say after reviewing a PR, you feel a need for changes in 25 different lines, but you may also want to ask some questions before suggesting changes for all of them, and lets say each one of these turn into a long conversation, it gets really really chaotic with comments. It would be great if something could group together these discussion around each one of these 25 lines. This is where I've found reviewable to be really useful.  And for others reading these discussions over a line of code becomes really easy. Also after the changes are made in further commits it also becomes easy to evaluate what you suggested before.

**Comment by harshavardhana** [comment]
> This is the problem I'm facing. Let's say after reviewing a PR, you feel a need for changes in 25 different lines, but you may also want to ask some questions before suggesting changes for all of them, and lets say each one of these turn into a long conversation, it gets really really chaotic with comments. It would be great if something could group together these discussion around each one of these 25 lines. This is where I've found reviewable to be really useful. And for others reading these discussions over a line of code becomes really easy. Also after the changes are made in further commits it also becomes easy to evaluate what you suggested before.

A collapsible comment approach is even valid with github.  Each one shouldn't turn into a long conversation in that case a patch should be dropped and re-implemented. The way to solve this problem is not by introducing new ways to do reviews, better to do smaller commits and concise ones where feedback can be provided in a well constrained manner. 

Also if the reviews take lots of comments it's better to call the person and discuss in detail which is must faster. We are not a big enough team to justify these requirements.

**Comment by hackintoshrao** [comment]
Wow.....makes sense. Wonder then what's the actual use case around reviewable!
