### ISSUE TITLE
 Active-Active Bucket Replication, when the replication target goes down, the time delay to reach full sync is very long and  uncertain 

### ISSUE THREAD

**Issue by qufa** [minio/minio#12025]
I am using active-active bucket replication fowllowing the guide [https://docs.min.io/docs/minio-bucket-replication-guide.html](minio-bucket-replication-guide) and [https://blog.min.io/active-active-replication](active-active-replication blog).
I made two cluster of minio, and both have the same configurations. Each cluster has 3 nodes and 2 drivers per node(thus 6 drivers total). Assume the source alias clusterA and the target alias clusterB.
When I upload files to clusterA, and it replicate to clusterB quickly, even when one of three nodes down whatever in the two clusters , because of the Erasure Code makes it HA.
But when I shut down the clusterB totally, and then make some file upload to clusterA, after a while , recover the clusterB, observing the files to be coming fully sync, it will take a very very long time and I'm not sure how long it will be(more than 12 hours). At the mean time, after the clusterB comes back , the newlly upload file to clusterA can be replicate to clusterB very quicklly as we expect.

Since the hint in the [https://blog.min.io/active-active-replication/](blog):

> What happens when the replication target goes down?
If the target goes down, the source will cache the changes and will start syncing once the replication target comes back up. There may be some delay to reach full sync depending on the length of time, number of changes, bandwidth and latency.

Is there any exactlly mechanism to makes the two cluster becoming to reach full sync and can exactlly  evaluate the delay ?
Assuming the bandwidth and latency takes lesser impact.

## Expected Behavior

Two cluster becoming fully sync as quick as possible.

## Current Behavior

Takes a very long time to becoming fully sync, even more than 12 hours, it does not sync.

## Steps to Reproduce (for bugs)

1. Construct two same cluster with minio, the source named clusterA and target names clusterB
2. Upload some files(less than 100 in total) to clusterA, and observing the replication result
3. Shut down the clusterB, and then upload 20 files to clusterA, about 1 minute per file.
4. 20 minutes later, recover clusterB, and observing the replication result.
5. Some file become sync quickly, and some takes very long time. Use mc stat check the file meta in clusterA, it still shows FAILED with replication status.

## Context

I want to make a Master-Slave cluster, and can continue service when one totally goes down.

## Your Environment

* Version used (`minio --version`):  **minio.RELEASE.2021-03-17T02-33-02Z**
* Server setup and configuration:
* The topology of the env:  clusterA <-->nginxA   <--->  nginxB<--->clusterB
* Operating System and version (`uname -a`): **Linux 3.10.0-1160.el7.x86_64**

**Comment by harshavardhana** [comment]
You need to configure `mc admin config set alias/ scanner max_delay=100ms`

**Comment by qufa** [comment]
> You need to configure `mc admin config set alias/ scanner max_delay=100ms`

Hi, thanks for reply! I followed your suggestion and test again , it seems to have a little improvement,
but still some files can not be sync . The test result can been seen below, the red rectangle  show where
there should be a file sync here.

![image](https://user-images.githubusercontent.com/68358882/114136418-3c615a80-993d-11eb-966e-395a38f8340d.png)

BTW, the command `mc admin config set alias/ scanner max_delay=100ms` I tried for some error,  it might be the `ms` mark that
could not be parsed. so I've used `100` instead directly.
Any more suggestions ?

**Comment by harshavardhana** [comment]
> BTW, the command `mc admin config set alias/ scanner max_delay=100ms` I tried for some error, it might be the `ms` mark that
> could not be parsed. so I've used `100` instead directly.
> Any more suggestions ?

Its actually 

```
~ mc admin config set play/ scanner max_wait=100ms delay=1
Successfully applied new settings.
```

**Comment by qufa** [comment]
I adjust the configuration， and the problem remain.
This time I have only 1/20 file sync failed, and I use `mc admin trace -v -a alias` command to observing the source cluster status,  found amounts of logs below in the picture, and it continuous refreshing

![image](https://user-images.githubusercontent.com/68358882/114161753-029f4c80-995b-11eb-9629-92dd4c3a9e01.png)

Is that mignt be a bug ? or it mignt be the reason that two cluster deos not fully sync ?

**Comment by klauspost** [comment]
@qufa No, that is perfectly normal. Only one scanner is permitted per cluster and locks are used to ensure that.

**Comment by qufa** [comment]
After adjust the configuration, I test it some more times, it still takes a long time (more than 1 hour),  is that normal ?
just 20 minutes and 20 small files?

**Comment by klauspost** [comment]
It depends mostly on the total number of objects in your cluster.

**Comment by harshavardhana** [comment]
> It depends mostly on the total number of objects in your cluster.

And the bandwidth you have between nodes. And the throughput you have on the destination.

**Comment by qufa** [comment]
My two clusters are in a same LAN, the same CIDR, no firewalls,  so the transmission can be considered very fast enough, also the files I test is just small files, about 1~100kb.
The total number of objects in my cluster is just less than 300, so I dont believe in this  minimize  active-active replication system it  works so bad, there mignt be something wrong with logic or mechanism.

BTW, 20 files I test last weekend are not become fully sync by now! There still 2/20 can not be replicated seems they will never be done.

**Comment by harshavardhana** [comment]
With new scanner changes the catch should be much faster, please upgrade to latest releases and let us know.
