### ISSUE TITLE
Federation - Forward S3 request to the right cluster

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#12038]
### Setup
Federation (etcd + coredns), 2 clusters
mc S3 endpoint: `s3.example.com`, load balancer for all MinIO nodes.
Let's say I have a `mario` bucket in the 1st cluster.

What's the expected behaviour if I upload a file to `mario` bucket and `s3.example.com` redirects to a node of the 2nd cluster. Is the request then forwarded to the right cluster ?

ex:
`mc cp my-photo.png s3-example-com/mario`
If `s3.example.com` redirects to a node of the 2nd cluster, I get: `mc: <ERROR> Failed to copy my-photo.png. 502 Bad Gateway`
 
MinIO logs:

Every nodes of the 1st cluster: `2021-04-09 16:10:52.706016 I | http: TLS handshake error from {IP}: EOF
2021-04-09 16:10:52.710520 I | http: TLS handshake error from {IP} remote error: tls: bad certificate`

Node of the 2nd cluster: `Error: x509: cannot validate certificate for {IP} because it doesn't contain any IP SANs (x509.HostnameError)`

Maybe it's just a certificate problem.

**Comment by harshavardhana** [comment]
Redirections cannot be supported for signature v4 - just make sure that each federated instances trust each other TLS certs and they all have DNS and IP..

**Comment by ToLToL** [comment]
@harshavardhana 

I run the first cluster:

```
export MINIO_ETCD_ENDPOINTS="http://etcd:2379"
export MINIO_DOMAIN=storage.domain.com
export MINIO_PUBLIC_IPS=44.35.2.1,44.35.2.2,44.35.2.3,44.35.2.4
minio server --certs-dir=/certs https://minio{0...2}.storage.domain.com/mnt/export{0...3}
```

second cluster:

```
export MINIO_ETCD_ENDPOINTS="http://etcd:2379"
export MINIO_DOMAIN=storage.domain.com
export MINIO_PUBLIC_IPS=44.35.1.1,44.35.1.2,44.35.2.3,44.35.1.4
minio server --certs-dir=/certs https://minio{3...5}.storage.domain.com/mnt/export{0...3}
```

And in each server I have /etc/hosts:


```
...
{IP} minio0.storage.domain.com
{IP} minio1.storage.domain.com
{IP} minio2.storage.domain.com
{IP} minio3.storage.domain.com
{IP} minio4.storage.domain.com
{IP} minio5.storage.domain.com
```

tls cert: `storage.domain.com` as CN and `*.storage.domain.com` as SAN

I still have the same errors logs:

```
Error: x509: cannot validate certificate for {IP} because it doesn't contain any IP SANs (x509.HostnameError)
```

**Comment by ToLToL** [comment]
@harshavardhana 

I use Let's Encrypt for tls certificate so I cannot add public IPs as SANs.
Do you see a solution to this ? It's a very annoying problem 😒.
