### ISSUE TITLE
tests: Inconsistent success behaviour of ./pkg/fs tests 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1203]
The image below depicts the issue. The tests succeed inconsistently while -race flag is used. Running latest pull of Minio on OSX El Caption
<img width="825" alt="screen shot 2016-03-08 at 5 46 43 am" src="https://cloud.githubusercontent.com/assets/2609511/13587904/586a1fa6-e4f1-11e5-9d7b-afdf404229db.png">

Here is the terminal log of entire trial https://docs.google.com/document/d/13hariQm-R1FXMIJWSmVnut73m4ljmeb7AjUOdIzbSPo/edit?usp=sharing

**Comment by harshavardhana** [comment]
> The image below depicts the issue. The tests succeed inconsistently while -race flag is used. Running latest pull of Minio on OSX El Caption

:+1:  - seen it, the bug is fixed by @balamurugana patch for ListObjects.

**Comment by hackintoshrao** [comment]
cool... !
