### ISSUE TITLE
can not create minio docker container

### ISSUE THREAD

**Issue by jissi** [minio/minio#12047]
## Current Behavior

run  "docker run -p 9000:9000 minio/minio server /data " 

ERROR Invalid command line arguments: wrong number of fields (expected 6, got 7): rootfs overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/LF4BS6BYTR7FUG6GTFZLT6MR5T:/var/lib/docker/overlay2/l/QJEPI6XM5MEJYPRSKWDZPTRY3B:/var/lib/docker/overlay2/l/3MGGCFZUPRNH774Q3GZD75P2ML:/var/lib/docker/overlay2/l/APHBJBM3NS4ZL4OG43I35SWZWE:/var/lib/docker/overlay2/l/Y7NFEKWSQLICLZUWB3UKFEA7MP:/var/lib/docker/overlay2/l/CYKEK43NR6EM24T5ZNZ3PXQOT3:/var/lib/docker/overlay2/l/5VAHSAIJQFBA75OKRJOJWILR26:/var/lib/docker/overlay2/l/PF33NJTSDPJ3CXZDDPABEXBZW2,upperdir=/var/lib/docker/overlay2/3ea7b411491d3cb71dcddcc80642b5b6234305a91698368d6ae325f0092f6d53/diff,workdir=/var/lib/docker/overlay2/3ea7b411491d3cb71dcddcc80642b5b6234305a91698368d6ae325f0092f6d53/work,index=off,xino=off 0 0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio latest
* Server setup and configuration: docker 20.10.5
* Operating System and version (`uname -a`): Linux xxx-pc 4.19.183-1-MANJARO #1 SMP Wed Mar 24 18:08:29 UTC 2021 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
No idea what this is looks like a setup issue.

**Comment by greg0ire** [comment]
I'm experiencing the same issue with Manjaro too, and a version of minio that is not the latest, so this is probably not a minio issue indeed.

Update: What's weird is that the error message does look like it's coming from minio:
https://github.com/minio/minio/blob/3d685b7fffd37620660f88b115f852ecb4c89194/cmd/server-main.go#L144
https://github.com/minio/minio/blob/3d685b7fffd37620660f88b115f852ecb4c89194/pkg/mountinfo/mountinfo_linux.go#L136

@harshavardhana please consider reopening this :pray: 

I think the issue might be with the `rootfs overlay / overlay` part: the first `overlay` does not seem to match https://github.com/minio/minio/blob/3d685b7fffd37620660f88b115f852ecb4c89194/pkg/mountinfo/mountinfo_linux.go#L150-L155

It seems to be an fstype, not a type.

I observe the same type of output when I run `cat /proc/mounts` from a random, unrelated php container I have running on my machine, but only for the `rootfs` line. All other lines have the normal format.

**Comment by greg0ire** [comment]
Thanks! I have yet to find out if that `root overlay / overlay` is something that can really happen in a normal situation or if it is a bug. `man 5 proc` says the following about `/proc/mounts:

```
       /proc/mounts
              Before kernel 2.4.19, this file was a list of all the filesystems  currently  mounted  on
              the  system.   With the introduction of per-process mount namespaces in Linux 2.4.19 (see
              mount_namespaces(7)), this file became a link to /proc/self/mounts, which lists the mount
              points  of  the  process's own mount namespace.  The format of this file is documented in
              fstab(5).
```

`man 5 fstab` is of no help in finding what this second field is about.

`cat /etc/mtab` shows the same output

`mount` seems happy with this and displays `overlay on 1653 type overlay (rw,blah blah blah…)`. So it does not crash, but the `1653` part is weird, for other lines it shows normal paths such as `/proc`, `/dev`, etc.

**Comment by harshavardhana** [comment]
Not sure this looks unusual, and can have issue with parsing can you paste your entire `/etc/mtab` or `/proc/self/mounts` ?

**Comment by greg0ire** [comment]
Sure, meanwhile, I asked the question here and got an interesting comment: https://unix.stackexchange.com/questions/645994/why-does-proc-mounts-show-a-line-with-7-columns-type-overlay

```
cat /etc/mtab
rootfs overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/YX72VZLETNSVXXXZQBENGGMI7W:/var/lib/docker/overlay2/l/74ZMIOZ4PCTUODVBBM5HPKA2VD:/var/lib/docker/overlay2/l/OI4LL4AG2CMZFQ2NOBA4WAGO2D:/var/lib/docker/overlay2/l/XNVOJIJBXWDYAMHKQVV36C75V7:/var/lib/docker/overlay2/l/OV7JOV3TW5MJUIXZ3D5INLWP2S:/var/lib/docker/overlay2/l/HESJLWTHRG6WS3ATRQZ53LHTHR:/var/lib/docker/overlay2/l/APVFQLQRINYD73WECQN5743O64:/var/lib/docker/overlay2/l/4XZCFLNC4XES6EMPFMVIDVCDZG:/var/lib/docker/overlay2/l/QXPY3J5KFA225KY2UQ2ZMSFQL6:/var/lib/docker/overlay2/l/J2FZIZQJRJILGLDETPYG3LUO36:/var/lib/docker/overlay2/l/6SQYUEBL4UYK7LOSPVWHY2VSTO:/var/lib/docker/overlay2/l/HEM6EMXICNYBE7NFCL66QLRN7F:/var/lib/docker/overlay2/l/FKCJWEQK6MTE7ZGGAQKRIIAQ2S:/var/lib/docker/overlay2/l/2CQEUDLJPSF5QYSHUP3FZZP2NG:/var/lib/docker/overlay2/l/RPHBJZTVMCPKW5YO4DLXDDEMG6:/var/lib/docker/overlay2/l/7CK3YF2F3UPMWJEDMJSPF4BUVM:/var/lib/docker/overlay2/l/6VNPYNFDWXULE3DHTTOKVK4TEV:/var/lib/docker/overlay2/l/FHGM5ZCKKZXU3ILXNLACVEEVJV:/var/lib/docker/overlay2/l/QTUW3G342VYWBSHCJKOUFBW67D:/var/lib/docker/overlay2/l/NUWVWRCIWNNIPY6HFOFLS7PUMK:/var/lib/docker/overlay2/l/7GGMDSIT66JJAT7WXHJKYZ5YZT:/var/lib/docker/overlay2/l/XWKJI2UXVR27CWTCN5EH7BB6UH:/var/lib/docker/overlay2/l/BMY5J7APK7EU25PJFBSRH2Q34L,upperdir=/var/lib/docker/overlay2/8c7724788f18ef56cdb72aa21b7720cc9e6e3255421b71fcff791f84c26f6d51/diff,workdir=/var/lib/docker/overlay2/8c7724788f18ef56cdb72aa21b7720cc9e6e3255421b71fcff791f84c26f6d51/work,index=off,xino=off 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,nosuid,size=65536k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
sysfs /sys sysfs ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs rw,nosuid,nodev,noexec,relatime,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/rdma cgroup ro,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
/dev/mapper/luks-c1d0e160-5e8f-4429-965f-1b362eb25599 /app ext4 rw,noatime 0 0
/dev/mapper/luks-c1d0e160-5e8f-4429-965f-1b362eb25599 /etc/resolv.conf ext4 rw,noatime 0 0
/dev/mapper/luks-c1d0e160-5e8f-4429-965f-1b362eb25599 /etc/hostname ext4 rw,noatime 0 0
/dev/mapper/luks-c1d0e160-5e8f-4429-965f-1b362eb25599 /etc/hosts ext4 rw,noatime 0 0
tmpfs /tmp/ssh-XXXXXXvAtHTp/agent.2316 tmpfs rw,nosuid,nodev,nr_inodes=409600 0 0
/dev/mapper/luks-c1d0e160-5e8f-4429-965f-1b362eb25599 /home/app/.composer/auth.json ext4 rw,noatime 0 0
proc /proc/bus proc ro,relatime 0 0
proc /proc/fs proc ro,relatime 0 0
proc /proc/irq proc ro,relatime 0 0
proc /proc/sys proc ro,relatime 0 0
proc /proc/sysrq-trigger proc ro,relatime 0 0
tmpfs /proc/asound tmpfs ro,relatime 0 0
tmpfs /proc/acpi tmpfs ro,relatime 0 0
tmpfs /proc/kcore tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/keys tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/latency_stats tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/timer_list tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/sched_debug tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/scsi tmpfs ro,relatime 0 0
tmpfs /sys/firmware tmpfs ro,relatime 0 0
```

**Comment by greg0ire** [comment]
FYI I asked my colleagues for which this works, they don't have the `rootfs ` part.
