### ISSUE TITLE
Wrong Error：Object name Does not contain unsupported characters

### ISSUE THREAD

**Issue by JJwangbilin** [minio/minio#12046]
## Expected Behavior

i want upload file , object name :༡༢།བསྟན་བཅོས་བཻཌཱུར་དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx

command:mc cp ༡༢།བསྟན་བཅོས་བཻཌཱུར་དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx /  

Object name Does not contain unsupported characters， But mac mc client 、python sdk return message:Object name contains unsupported characters.

 
## Current Behavior

code: XMinioInvalidObjectName
message: Object name contains unsupported characters.
bucket_name: xxx
object_name: 
༡༢ །བསྟན་བཅོས་བཻཌཱུར་དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད། .docx, 
## Steps to Reproduce (for bugs)

1. object name Divided into two parts，༡༢།བསྟན་བཅོས་བཻཌཱུར་            དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx
2. test one part,   ༡༢།བསྟན་བཅོས་བཻཌཱུར་.docx, success
3. test one part ,   དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx, success
4. so, this object name Does not contain unsupported characters
5. ༡༢།བསྟན་བཅོས་བཻཌཱུར་དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx,failed to copy
mc: <ERROR> Failed to copy `༡༢།བསྟན་བཅོས་བཻཌཱུར་དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx`. Object name contains unsupported characters.

## Context

only object_name, Can create files for testing。

## Regression

 No

## Your Environment

* Version used (`minio --version`): mc version RELEASE.2021-03-23T05-46-11Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Darwin MacBook-Air.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64

**Comment by harshavardhana** [comment]
The main issue here is the `open ༡༢།བསྟན་བཅོས་བཻཌཱུར་དཀར་པོ་ལས་བརྩམས་པའི་དྲིས་ལན་འཁྲུལ་སྣང་གཡའ་སེལ་དོན་གྱི་རང་བཞིན་སྟོན་བྱེད།.docx.part.minio: file name too long` is too long @JJwangbilin for filesystems to store. 

This exceed 1024 bytes in UTF-8
