### ISSUE TITLE
Invalid command line arguments: path '/mnt/disk1/data' cannot be served by different address on same server

### ISSUE THREAD

**Issue by martyanov** [minio/minio#12048]
Hi everyone! What I am doing wrong? I've just copied the command from the official documentation [here](https://docs.min.io/minio/baremetal/tutorials/minio-installation.html) and added host entries with distinct IP addresses to `/etc/hosts`.

## Expected Behavior

Properly initialized distributed MinIO.

## Current Behavior

```
./minio server https://minio{1...4}.example.com/mnt/disk{1...4}/data
ERROR Invalid command line arguments: path '/mnt/disk1/data' cannot be served by different address on same server
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-04-06T23-11-00Z`
* Operating System and version (`uname -a`): `5.10.17-100.fc32.x86_64 #1 SMP Wed Feb 17 21:32:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Make sure your host can resolve the IP to a local interfaces and also make sure they they all resolve to their own unique IPs.

This is the most basic setup issue.
