### ISSUE TITLE
Metadata on pre-existing directory (aka fs-mode) ?

### ISSUE THREAD

**Issue by philpep** [minio/minio#12042]
When running minio on pre-existing directory (as documented in https://docs.min.io/docs/minio-quickstart-guide.html "Pre existing data"), the server doesn't expose `etag` metadata (`00000000000000000000000000000000-1`) of files.

Exposing correct etag (which is IIUC the md5 of the file content) here would be an awesome feature !

Thanks!

Related to #5050

**Comment by klauspost** [comment]
That would require indexing potentially terabytes of data. Not really a feasible feature.

**Comment by philpep** [comment]
Maybe this can be an option ? Or adding a command that add metadata on files that's doesn't have yet ? Maybe this is already possible via API (add only metadata) ?

I'm looking for some project that provide s3 like API on existing posix directory which is handled by external process, and minio seems a perfect choice here, except I need etag on client side (since I need to check for modified files and only get changed files). Is etag the sole way to known the file content has changed ?

But maybe you have other suggestion than minio for this ? I've a single server using a single disk in a single datacenter, I don't care about replication/encryption and I've less than few GB of data :)

**Comment by klauspost** [comment]
I don't know about others, but for MinIO you can download+upload the data, or copy it to another bucket. We typically don't add these types of fringe features as options, since it carries maintenance and documentation along.

**Comment by harshavardhana** [comment]
This is not an expected use case, existing data is access is provided as a convenience - extending that to do other kind of background operations is unexpected and beyond the scope of FS mode.

**Comment by philpep** [comment]
Seems I can workaround this by writing medata by myself in `.minio.sys/buckets/<bucket>/<path>/fs.json`. And then minio make metadata available. So I can write a daemon looking a inotify events and write metadata if needed.

May I expect bad side effects by doing this ?

Thanks!
