### ISSUE TITLE
MinIO-gateway multi-user support with Consul

### ISSUE THREAD

**Issue by theboringstuff** [minio/minio#12061]
**Is your feature request related to a problem? Please describe.**
We would like to use MinIO-gateway with Multi-User support, but it requires etcd for storing encrypted IAM data.
We understand the need for storage backend, but in public clouds we usually do not have access to etcd.
On the other hand, we usually deliver in-cluster Consul service.

**Describe the solution you'd like**
We would like to be able to use Consul instead of etcd for MinIO-gateway for storing encrypted IAM data.

**Describe alternatives you've considered**
We could use etcd, but we will have to implement in-cluster etcd deployment with support for different ops.

**Comment by theboringstuff** [comment]
As I can see, MinIO-gateway is being moved to Ming: https://github.com/minio/ming

Will Ming even provide multi-user support?

**Comment by harshavardhana** [comment]
MinIO gateway is not taking any feature requests and neither will ming project for the time being.

Feel free to send PR to support consul if you must.
