### ISSUE TITLE
authentication for minio gateways failed with openid provider [keycloak][eks]

### ISSUE THREAD

**Issue by RomainPhil** [minio/minio#12079]
The authentication with a openId like Keycloak works only with Minio server and failed with gateway.

## Expected Behavior

The authentication with a third party should work with Minio Gateway and Minio Server. 

## Current Behavior

The attribute defined during the deployment of minio by the env variable  `MINIO_IDENTITY_OPENID_CLAIM_NAME` is not found when Minio is deployed as gateways but works fine when it's server mode 

## Possible Solution

add a step during the authentication of minio gateways to allow the usage of local credential but authentication by the openid Server

## Steps to Reproduce (for bugs)

every component are deployed on a eks 18.4 with a loadblancer in front of Keycloak

1. setup a Keycloak with a realm `master` and and create a role with an attribute `minioPolicy` =  ``ReadWrite``
2. Create user with the role create previously 
3. deploy minio with following env variable   
```
MINIO_IDENTITY_OPENID_CONFIG_URL: https://<keycloak_rul>/auth/realms/master/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_CLIENT_ID: <open_id>
MINIO_IDENTITY_OPENID_CLAIM_NAME: minioPolicy
```
4. Create a port forward to your local port `kubectl port-forward svc/minio 5000:9000`
4. try to auth with minio deployed as server with open_id (work on my side)
5. redeploy minio as gateway and add the annotation for iam role in eks `eks.amazonaws.com/role-arn:` 
6. the authentication by openid failed with following issue:

```
API: WebLoginSTS()
Time: 14:40:20 UTC 04/16/2021
DeploymentID: fd332306-d9ab-4051-a8e8-a2ce64f51507
RemoteHost: 127.0.0.1
Host: localhost:5000
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Error: minioPolicy claim missing from the JWT token, credentials will not be generated (*errors.errorString)
      10: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
       9: cmd/api-errors.go:2034:cmd.toAPIError()
       8: cmd/web-handlers.go:2443:cmd.toWebAPIError()
       7: cmd/web-handlers.go:2309:cmd.toJSONError()
       6: cmd/web-handlers.go:2278:cmd.(*webAPIHandlers).LoginSTS()
       5: reflect/value.go:476:reflect.Value.call()
       4: reflect/value.go:337:reflect.Value.Call()
       3: pkg/rpc/server.go:275:rpc.(*Server).ServeHTTP()
       2: cmd/generic-handlers.go:135:cmd.setRedirectHandler.func1()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```
where `minioPolicy` is the name of my MINIO_IDENTITY_OPENID_CLAIM_NAME, which works fine in server mode

## Context

We prepare the independancy ou our platformp to cloud_provider so minio is on the implementation.
where it's works fine on server mode for local dev environnement, some limitation start to appear on aws.

the obligation to pass the aws_key and secret key as user password doesn't help us and we would like to use keycloak as the main piece for the authentication.

techinical context:
On a eks cluster with a keycloak server deployed as a pods behind a load balancer, the keycloak is configured  with a userid, a group and a user and the following claim policy `minioPolicy` = ReadWrite.

the annotation for minio service account is present and the policy used is the one furnish in  https://docs.min.io/docs/minio-gateway-for-s3.html.

## Your Environment

eks : 18.4
minio: RELEASE.2021-03-26T00-00-41Z-35-g5cce9361b
keycloak: bitnami/keycloak:12.0.4-debian-10-r9

I am available for more details on the deployment of the different components.

**Comment by harshavardhana** [comment]
> ```
> MINIO_IDENTITY_OPENID_CLAIM_NAME: minioPolicy
> ```

This claim should come from keycloack as part of the user who is trying to login

> On a eks cluster with a keycloak server deployed as a pods behind a load balancer, the keycloak is configured with a userid, a group and a user and the following claim policy `minioPolicy` = ReadWrite.

You need to create the policy on MinIO `mc admin policy add`

**Comment by harshavardhana** [comment]
> The authentication with a third party should work with Minio Gateway and Minio Server.

Also for Gateway you need to enable `etcd`

**Comment by RomainPhil** [comment]
thanks but any link ?
the documentation is splited in so many part that i can't some accurate documentation to the gateway

**Comment by RomainPhil** [comment]
> > ```
> > MINIO_IDENTITY_OPENID_CLAIM_NAME: minioPolicy
> > ```
> 
> This claim should come from keycloack as part of the user who is trying to login
> 
> > On a eks cluster with a keycloak server deployed as a pods behind a load balancer, the keycloak is configured with a userid, a group and a user and the following claim policy `minioPolicy` = ReadWrite.
> 
> You need to create the policy on MinIO `mc admin policy add`

that works completely with minio server, is the policy required only for mino gateway ?

**Comment by harshavardhana** [comment]
> that works completely with minio server, is the policy required only for mino gateway ?

gateway requires etcd @RomainPhil

**Comment by RomainPhil** [comment]
i get that minio gateway require etcd, but it's installed as standard on eks. so the issue is not here
