### ISSUE TITLE
lifecycle works unexpected in server or gateway nas mode

### ISSUE THREAD

**Issue by TestMsr** [minio/minio#12073]
## Expected Behavior

server mode:success get object info without err.
gateway nas mode:can get/set lifecycle like server mode.

## Current Behavior

server mode:minio server panic with nil pointer
gateway nas mode: 1.set bucket lifecle successful 2.get bucket lifecycle it returns not implement

## Possible Solution

server mode:it seems that initBackgroundExpiry function only called on erasure mode.
gateway mode:should indicate whether it is supported now

## Steps to Reproduce (for bugs)

1.setbucketlifecycle
2.getobject 
3.error occurs (object was deleted by lifecycle)

## Context

config.Rules = []lifecycle.Rule{
		{
			ID:     "expire_bucket",
			Status: "Enabled",
			Expiration: lifecycle.Expiration{
				Days: 1,
			},
			RuleFilter: lifecycle.Filter{
				Prefix: objectName,
			},
		},
	}

2021-04-16 18:10:26.905691 I | http: panic serving 10.226.22.65:64201: runtime error: invalid memory address or nil pointer dereference
goroutine 4847 [running]:
net/http.(*conn).serve.func1(0xc000645ea0)
	net/http/server.go:1824 +0x153
panic(0x1c652c0, 0x343b370)
	runtime/panic.go:971 +0x499
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc0001d1400, 0x27c3370, 0xc000e3c7e0)
	github.com/minio/minio/cmd/generic-handlers.go:689 +0x1cc
panic(0x1c652c0, 0x343b370)
	runtime/panic.go:965 +0x1b9
github.com/minio/minio/cmd.(*expiryState).queueExpiryTask(0x0, 0xc000bff33d, 0x4, 0xc000bff342, 0x1, 0x0, 0xed6de6072, 0x3464580, 0x241, 0x0, ...)
	github.com/minio/minio/cmd/bucket-lifecycle.go:79 +0x3a
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler(0x2502850, 0x2502820, 0x27c08e0, 0xc0011b3180, 0xc000ff3500)
	github.com/minio/minio/cmd/object-handlers.go:462 +0x1dc5
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x27c08e0, 0xc0011b3180, 0xc000ff3500)
	github.com/minio/minio/cmd/handler-utils.go:375 +0x70
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.maxClients.func1(0x27c08e0, 0xc0011b3180, 0xc000ff3500)
	github.com/minio/minio/cmd/handler-api.go:153 +0x3b7
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.collectAPIStats.func1(0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	github.com/minio/minio/cmd/handler-utils.go:390 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc0011621c0, 0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRedirectHandler.func1(0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:135 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc0006856f8, 0x27c08e0, 0xc0011b30e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addCustomHeaders.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:664 +0x174
net/http.HandlerFunc.ServeHTTP(0xc000685710, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addSecurityHeaders.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:673 +0x1ea
net/http.HandlerFunc.ServeHTTP(0xc000685728, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBucketForwardingHandler.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:547 +0xad
net/http.HandlerFunc.ServeHTTP(0xc000685740, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestValidityHandler.func1(0x27c08b0, 0xc000685920, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:535 +0x468
net/http.HandlerFunc.ServeHTTP(0xc000685758, 0x27c08b0, 0xc000685920, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setHTTPStatsHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:469 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc000685770, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:49 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc000685788, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:68 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc0006857a0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x279d820, 0xc0006857a0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x82
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:161 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0006857b8, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setReservedBucketHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:293 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000685818, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:262 +0x1ce
net/http.HandlerFunc.ServeHTTP(0xc000685830, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setTimeValidityHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:357 +0x407
net/http.HandlerFunc.ServeHTTP(0xc000685848, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setIgnoreResourcesHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:456 +0xb8
net/http.HandlerFunc.ServeHTTP(0xc0006858a8, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setAuthHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/auth-handler.go:492 +0x391
net/http.HandlerFunc.ServeHTTP(0xc0006858c0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setSSETLSHandler.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:707 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0006858d8, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.filterReservedMetadata.func1(0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	github.com/minio/minio/cmd/generic-handlers.go:108 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc0006858f0, 0x27c3370, 0xc000e3c7e0, 0xc000ff3500)
	net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001d3440, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc00119ce20, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x279d820, 0xc00119ce20, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/minio/minio/cmd/generic-handlers.go:692 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	github.com/minio/minio/cmd/http/server.go:101 +0x258
net/http.HandlerFunc.ServeHTTP(0xc001026000, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000649560, 0x27c3370, 0xc000e3c7e0, 0xc0001d1400)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000645ea0, 0x27cc9f8, 0xc0001327c0)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version RELEASE.2021-03-26T00-00-41Z

cmd:./minio server ./data --address ":9001"

**Comment by harshavardhana** [comment]
This is not a NAS gateway mode 

> cmd:./minio server ./data --address ":9001"

You need to use 

> cmd:./minio gateway nas ./data --address ":9001"

**Comment by TestMsr** [comment]
> This is not a NAS gateway mode
> 
> > cmd:./minio server ./data --address ":9001"
> 
> You need to use
> 
> > cmd:./minio gateway nas ./data --address ":9001"

This is my description fault.I use this two command separately.
There are two different problems here .one in server mode and another is gateway nas.
In server mode minio give panic err while getobject with file expried but yet deleted.
In gateway nas mode there appears no error while set bucket lifecycle,but when i get it ,it confused me returning not implement.

**Comment by harshavardhana** [comment]
> In gateway nas mode there appears no error while set bucket lifecycle,but when i get it ,it confused me returning not implement.

NAS gateway doesn't support lifecycle @TestMsr - just that for some reason it saves the lifecycle rules but never applies them.
