### ISSUE TITLE
startup: do not start minio server if port is not free

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1207]
Reference: https://github.com/minio/minio-js/issues/431

Make sure that none of the other processes are listening on the
specified port on any of the interfaces.

On linux if a process is listening on 127.0.0.1:9000 then Listen()
on ":9000" fails with the error "port already in use".
However on Mac OSX Listen() on ":9000" falls back to the IPv6 address.
This causes confusion on Mac OSX that minio server is not reachable
on 127.0.0.1 even though minio server is running. So before we start
the minio server we make sure that the port is free on all the IPs.

**Comment by harshavardhana** [comment]
Looks like the patch didn't fix the issue on OSX 

```
$ go run /tmp/main.go
Listening on 0.0.0.0:9000
```

```
$ minio server ~/testdir/

AccessKey: xxxxx  SecretKey: xxxxx Region: us-east-1

Minio Object Storage:
    http://127.0.0.1:9000
    http://10.1.10.32:9000

Minio Browser:
    http://127.0.0.1:9000
    http://10.1.10.32:9000

To configure Minio Client:
    $ wget https://dl.minio.io/client/mc/release/darwin-amd64/mc
    $ chmod 755 mc
    $ ./mc config host add myminio http://localhost:9000 WLGDGYAQYIGI833EV05A BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF

```

**Comment by harshavardhana** [comment]
The reason is perhaps net.Listen("tcp") itself,  ipv4 and ipv6 should be verified separately in the loop. Can you fix it @krishnasrinivas ?

**Comment by harshavardhana** [comment]
This is fixed.

**Comment by olanseerla** [comment]
How do you stop the server?
