### ISSUE TITLE
Sometimes bucket created with S3 client has an empty region

### ISSUE THREAD

**Issue by alexis-m** [minio/minio#12072]
If a bucket is created with an S3 client right after starting a new minio instance with a configured region, sometimes it is created with an empty region.
Present in` RELEASE.2021-04-06T23-11-00Z`.
Bisected to `RELEASE.2020-10-03T02-19-42Z` (last good) to `RELEASE.2020-10-09T22-55-05Z` (first bad).

## Expected Behavior
CreateBucket and then GetBucketLocation should return the configured region.

## Current Behavior
Sometimes (when CPUs are busy), the region on a new bucket is empty.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
On Ubuntu.
`$ mkdir ~/tmp/minio_bug`

Create `~/tmp/minio_bug/use_minio.py`
```Python
#!/usr/bin/env python3

import boto3

region = 'test-region'
endpoint_url = 'http://127.0.0.1:9000'
client = boto3.client(
    's3',
    endpoint_url=endpoint_url,
    region_name=region,
    aws_access_key_id='test_key',
    aws_secret_access_key='test_secret',
)

bucket_name = 'test-bucket'
res1 = client.create_bucket(
    Bucket=bucket_name, CreateBucketConfiguration={'LocationConstraint': region}
)
print(res1['Location'])
assert res1['Location'] == '/test-bucket'

# This sometimes fails with KeyError: 'x-amz-bucket-region'
print(res1['ResponseMetadata']['HTTPHeaders']['x-amz-bucket-region'])
#
# OR a different test
#
# Sometimes location is None
location_dict = client.get_bucket_location(Bucket=bucket_name)
location = location_dict['LocationConstraint']
print(location)
assert location == region
```

Create `~/tmp/minio_bug/repro.sh`
```Bash
#!/bin/bash

rm -rf ~/tmp/minio_bug/data

echo === Load CPU cores with 7za benchmark
# Set number of threads to match the number CPU cores.
7za b -mmt12 1>/dev/null &
# Let it ramp up.
sleep 10

# Start minio
export MINIO_ACCESS_KEY=test_key
export MINIO_SECRET_KEY=test_secret
export MINIO_REGION_NAME=test-region
minio server ~/tmp/minio_bug/data &

echo === use minio
python3 ~/tmp/minio_bug/use_minio.py

sleep 1

echo === kill 7za
pkill 7za
echo === kill minio
pkill minio
```

Run `$ bash ~/tmp/minio_bug/repro.sh`
```
=== Load CPU cores with 7za benchmark
=== use minio
Attempting encryption of all config, IAM users and policies on MinIO backend
/test-bucket
Traceback (most recent call last):
  File "/home/user/tmp/minio_bug/use_minio.py", line 23, in <module>
    print(res1['ResponseMetadata']['HTTPHeaders']['x-amz-bucket-region'])
KeyError: 'x-amz-bucket-region'
Endpoint: http://127.0.0.1:9000
RootUser: test_key
RootPass: test_secret
Region:   test-region

Browser Access:
   http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
IAM initialization complete
=== kill 7za
=== kill minio
Exiting on signal: TERMINATED
```

Note `KeyError: 'x-amz-bucket-region'`. With enough CPU load the issue is very frequent, although not 100%.
If I omit 7za load, then the region comes as expected.

## Context
We use minio for internal local testing when we frequently bring up fresh instances. The issue prevents is from updating to the latest minio. No impact otherwise.

## Regression
I bisected this to `RELEASE.2020-10-03T02-19-42Z` (last good) to `RELEASE.2020-10-09T22-55-05Z` (first bad).
This change #10645 (remove safeMode behavior in startup) looks relevant, although I don't know what it did exactly.

## Your Environment
`minio version RELEASE.2021-04-06T23-11-00Z`
`Linux desk 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Region is always empty by default and also region is set only when config is fully loaded otherwise you can't expect it to set the region right away until it loads the config.

So slow down your client.. and let the server be up fully.
