### ISSUE TITLE
Gracefully shutdown Min.IO instance to prevent upload truncation during cluster restart

### ISSUE THREAD

**Issue by cverges-medallia** [minio/minio#12078]
**Is your feature request related to a problem? Please describe.**

When performing maintenance to the Min.IO cluster in Kubernetes, K8S will restart one node at a time; however, each node dies suddenly and truncates any existing connections.

When this does occur, the Min.IO connection returns a 403 (Forbidden), which is semantically unexpected, too.  Something like a 429 would be better to indicate that a retry would work.

**Describe the solution you'd like**

Add graceful shutdown support, whereby a Min.IO node will not accept new connections but will allow old ones to gracefully finish.  A max timeout can be established, if desired.

**Describe alternatives you've considered**

Client-side retries are what's currently in use, but for files that are large (10 GB+) when a connection is dropped, this retry simply takes a lot of waste/duplicated time to recover.

**Comment by harshavardhana** [comment]
> Add graceful shutdown support, whereby a Min.IO node will not accept new connections but will allow old ones to gracefully finish. A max timeout can be established, if desired.

That is currently set to 5secs and no new connections are established.

**Comment by harshavardhana** [comment]
> When this does occur, the Min.IO connection returns a 403 (Forbidden), which is semantically unexpected, too. Something like a 429 would be better to indicate that a retry would work.

This happens when the server is coming up and redirects the requests to neighboring nodes or IAM system is not yet initialized so unexpected users are returned with 403.

**Comment by cverges-medallia** [comment]
Thank you for the fast replies!

Can the max timeout be tweaked as part of the cluster definition?  (Apologies if I missed that setting in the docs.)

And is there a way to prevent the 403 from occurring?  The rest of the cluster is up (IAM, etc.)

**Comment by harshavardhana** [comment]
> Thank you for the fast replies!
> 
> Can the max timeout be tweaked as part of the cluster definition? (Apologies if I missed that setting in the docs.)
> 
> And is there a way to prevent the 403 from occurring? The rest of the cluster is up (IAM, etc.)

Will check what is going on here.. @cverges-medallia

**Comment by harshavardhana** [comment]
> And is there a way to prevent the 403 from occurring? The rest of the cluster is up (IAM, etc.)

I think changing 403 --> 503 is better from a retry point of view.

**Comment by cverges-medallia** [comment]
503 seems like it would work fine.  It looks like it's one of the codes that the AWS CLI auto-retries on: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html.
