### ISSUE TITLE
Is't expand the number of disks must same as original cluster?

### ISSUE THREAD

**Issue by invent-lwj** [minio/minio#12070]
I setup old cluster of 8nodes, 1disk per node, then, i expand it with 4nodes, 1disk per node. I got error `ERROR Unable to initialize backend: All current serverPools should have same parity ratio`. When i expand 8nodes, 1disk per node, it's work fine.
So i want to know it's restrict to expand same number of disks with old cluster?
Thanks!
Another question:
When expand old cluster, does the command format is restrict to `minio server http://host{1...n}/export{1...m} http://host{o...z}/export{1...m}` ?
This rule is mean only can expand nodes with continuous IP or hostname?
But i can start original cluster with sperate IP ` command: server http://a-minio/data1 http://b-minio/data1 http://c-minio/data1 http://d-minio/data1 http://e-minio/data1 http://f-minio/data1 http://g-minio/data1 http://h-minio/data1`, when i expand this cluster with command `command: server http://a-minio/data1 http://b-minio/data1 http://c-minio/data1 http://d-minio/data1 http://e-minio/data1 http://f-minio/data1 http://g-minio/data1 http://h-minio/data1 http://a1-minio/data1 http://b1-minio/data1 http://c1-minio/data1 http://d1-minio/data1 http://e1-minio/data1 http://f1-minio/data1 http://g1-minio/data1 http://h1-minio/data1`, failed.
Thanks!

**Comment by harshavardhana** [comment]
@invent-lwj you cannot expand with positional args - only ellipses expansion allows expansion.
