### ISSUE TITLE
3 dots or 2 dots in shell

### ISSUE THREAD

**Issue by invent-lwj** [minio/minio#12071]
I start cluster on shell with `./minio server http://IP1/data{1...2}(three dots) http://IP2/data{1...2}(three dots)`, encounter error `ERROR Invalid command line arguments: Incorrect number of endpoints provided [http://IP1/data{1...2}]`
But, i run commond with three dots on docker-compose is fine, only can run command with two dots in shell? 
```
NOTE: {1...n} shown have 3 dots! Using only 2 dots {1..n} will be interpreted by your shell and won't be passed to MinIO server, affecting the erasure coding order, which would impact performance and high availability. Always use ellipses syntax {1...n} (3 dots!) for optimal erasure-code distribution
```
I have read document, 2 dots{1..n} is low performance and ha, but how to perform with 3 dots{1...n} on shell?
Thanks!

**Comment by klauspost** [comment]
Do not use 2 dots, as stated in the docs. A server pool cannot have only 2 disks.
