### ISSUE TITLE
minio returns GMT time when server time is configured to a different timezone

### ISSUE THREAD

**Issue by weiklr** [minio/minio#12089]
When I use minio client via java sdk, I encountered the error "RequestTimeTooSkewed", even though I already set the server time to be the same time zone as the client (GMT +8). the client's time is 15 mins slower than the server.

When I did a curl http://minio1:9000 to troubleshoot, i noticed that the response time zone is in GMT -8. How can I set the time to follow the server's timezone instead?

## Expected Behavior
Minio should not be returning GMT time, and follows server time when serving http requests.

## Steps to Reproduce (for bugs)
1. Start minio in docker
2. do a curl http://minio:9000, and observe the timezone from the response.
3.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-04-06T23-11-00Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): Red Hat 8.3

**Comment by klauspost** [comment]
`RequestTimeTooSkewed` sounds more like a server error when `x-amz-date` in requests are more than 15 minutes off from the server time. This is a requirement of signed requests.

Sounds like you are already aware of this:

> the client's time is 15 mins slower than the server.

Timezone is sent, so whichever timezone you send/receive doesn't matter. Synchronize your clocks.
