### ISSUE TITLE
Allow AssumeRole-API to assume specific user/role

### ISSUE THREAD

**Issue by dprbook** [minio/minio#12083]
In my setup, I have an external Identity Provider (IdP), which returns JWTs after authentication to a frontend. This JWT is then forwarded to MinIO and verified using an OIDC-endpoint. This federated user wants to be part of groups. (As far as I understand, MinIO has no roles per se, so users can be used instead.) The goal behind this is to have MinIO be the access manager but use an external IdP/federated users.

## Expected Behavior
When a call to AssumeRole is made, one can specify, which user is to be assumed. This user can then be used as part of groups to define their individual allowances. In other words, the AssumeRole-endpoint should include a way to request a specific role and return that role (which it should theoretically with the RoleArn-parameter and the AssumedRoleUser-section of the response).

## Current Behavior
The temporary credentials are only for a temporary user, which cannot be added to groups.

### In MinIO
- A policy is used to define which user is assumed. This policy's name is passed as the claim in the JWT. AWS variables are used to return the corresponding MinIO user. 
- Groups can include temp users. Groups would need to be able to include federated user ids/names and temporary users to have the original requestee included (either coded into the access tokens or stored somewhere and resolved). 
- Another solution would be to allow the temporary user to assume the real user. The calls would then be: 
1. AssumeUser (JWT) -> TempUser
2. AssumeUser (TempUser) -> User
3. ListBuckets(User) -> Bucket[]
Here the temp user token would need to include, which federated user it was created for to return the correct long-lasting user (like 2.) and this would require a policy limiting the assumable user to the one corresponding to the original requestee, so this is a strictly worse version than the above (IMO).
- There is a way to generate temporary credentials for long-lasting users. Then, an endpoint (in an external service, not MinIO) can be created, which resolves the JWT to temporary credentials (using long-lasting credentials stored for the user). This endpoint then functionally replaces the AssumeRole-API.
### Outside MinIO
Some other options of solving this came to mind, but I found most of them suboptimal.
- Create a temp URI for objects -> ListBuckets is a problem; also, for each call to S3, a temp URI would need to be created.
- Creating an endpoint, which resolves the JWT to user credentials, exchanges the authentication data, and then forwards the call to MinIO.

## Context
As described above, I want users with groups. Each user can be added separately to groups. There should be an entity in MinIO, so the access rights can be managed and decided in MinIO (and not something like encoded into the JWT). But the credentials of the user should not be passed to the frontend. And the frontend can call MinIO directly and without jumping through hoops.

All examples I found in MinIO's documentation do not return an AssumedRoleId even though it is marked as mandatory in AWS STS documentation. Therefore, I'm assuming (no pun intended), that the functionality described above is simply not present in MinIO. If I overlooked something, please let me know.

## Regression
No

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-04-06T23-11-00Z
* Server setup and configuration: local Docker

**Comment by harshavardhana** [comment]
The roles are policies on MinIO there is no reason to have additional roles that also attach to policies. 

The AWS implementation is pointlessly complicated and not needed. It was designed for their infrastructure and we don't really want to repeat their mistakes.

We may bring roles if you cannot solve it by using canned policies but we haven't seen any such requirement in the field.

Closing this issue as out of scope at the moment.
