### ISSUE TITLE
How to skip OIDC authentication if already authenticated with Keycloak

### ISSUE THREAD

**Issue by thomas-jakemeyn** [minio/minio#12094]
**Is your feature request related to a problem? Please describe.**
I am working on a project that embeds MinIO. Authentication is done with Keycloak + gatekeeper. If an incoming HTTP request is not authenticated, then the gatekeeper triggers a redirection to the login page. The problem is that, despite the fact that the active user is authenticated and has a JWT token, (s)he needs to click on the button *Login with OpenID* prior to accessing the MinIO browser. Note that the active user has access directly to the MinIO browser when clicking on that button and does not have to provide credentials again.

**Describe the solution you'd like**
I would like the user experience to be seamless. If the active user is already authenticated with Keycloak, then (s)he should not have to click on *Login with OpenID*.

**Describe alternatives you've considered**
I could log in and log out in MinIO programmatically, as the user logs in and out from my project, but I am not sure how to do this with MinIO.

**Additional context**
It would also be nice to be able to hide the top-right menu in the MinIO browser since it provides access to the *Logout* feature.

**Comment by harshavardhana** [comment]
You cannot externalize authentication in MinIO, because your gatekeeper needs to implement S3 signature validation.

Otherwise MinIO is the authority for signature v4, if you are only looking at our browser then don't be that is the common way to access MinIO.
