### ISSUE TITLE
create user in old minio server

### ISSUE THREAD

**Issue by fvahid** [minio/minio#12092]
I want create new user on old minio server I got this error

---------START-HTTP---------
PUT /minio/admin/v3/add-user?accessKey=vahid HTTP/1.1
Host: minio.apps.private.teh-1.snappcloud.io
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1
Content-Length: 102

X-Amz-Date: 20210419T202120Z
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Content-Length: 328
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Vary: Origin
X-Amz-Request-Id: 16775BF6C2D658DD
X-Xss-Protection: 1; mode=block

END-HTTP---------
2021/04/20 00:51:20 Failed to parse server response: invalid character '<' looking for beginning of value.

Here is my sample code 

	mdmClnt, err := madmin.New(endpoint, accessKeyID, secretAccessKey, useSSL)
	mdmClnt.TraceOn(os.Stderr)

	if err != nil {
		fmt.Println(err)
		return
	}

	if err = mdmClnt.AddUser(ctx, userName, userPass); err != nil {
		log.Fatalln(err)
	} else {
		log.Printf("Successfully created %s\n", userName)
	}

I found problem cause minio client request on PUT /minio/admin/v3/add-user?accessKey=vahid HTTP/1.1 but my old minio server work on PUT /minio/admin/v1/add-user?accessKey=vahid HTTP/1.1

but I don't know how to fix this issue

**Comment by harshavardhana** [comment]
Upgrade your MinIO or stick your client to the version you want...

**Comment by fvahid** [comment]
how to stick client version on code ?

**Comment by harshavardhana** [comment]
> how to stick client version on code ?

Read go mod documentation on how to do it..

**Comment by fvahid** [comment]
I know with changing go mode I can stick version to desire but this need to recompile application , I want do it by coding 
something like change config in minio client api

**Comment by fvahid** [comment]
@harshavardhana I need to connect to tow minio server in single application in same time with different version any solution do you have to do that?

**Comment by harshavardhana** [comment]
> @harshavardhana I need to connect to tow minio server in single application in same time with different version any solution do you have to do that?

There is no solution @fvahid you need to manage it locally ..
