### ISSUE TITLE
No errors and no actions when deleting an object using double escaped key

### ISSUE THREAD

**Issue by uhfath** [minio/minio#12108]
I've spent a whole day trying to figure out why nothing is happening after a request is sent to minio using incorrect escaping.

## Expected Behavior
When an incorrectly formed URL is used for a request, minio should return an error. Any error with a description.

## Current Behavior
Currently 204 is returned without any signs of incorrect request being made in the first place (tested with DELETE request).

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Because of a bug in my app the URL used to delete an object was double escaped.
This is how it should look:
https://files.kapmed07.ru/smsconverter/%D1%81%D0%B2%D0%BE%D0%B4%D0%BA%D0%B0%20%D0%A4%D0%9B%D0%9A.xlsx?versionId=8a8fdfc2-6e99-46f4-8266-9a3bc5682715
And this is how it was sent:
https://files.kapmed07.ru/smsconverter/%25D1%2581%25D0%25B2%25D0%25BE%25D0%25B4%25D0%25BA%25D0%25B0%2520%25D0%25A4%25D0%259B%25D0%259A.xlsx?versionId=8a8fdfc2-6e99-46f4-8266-9a3bc5682715

Note the difference in %25 symbol added to every other escaped symbol.
This was hard to spot when debugging.

The problem is that minio reports that everything is OK (204 returned) but no action was actually taken.
In this case, file was not deleted.

## Context
Any error, which indicates that URL or a key is incorrect would be useful.
Even a simple 404.
If this is not an error, than an action should be taken according to the request.

## Regression
No idea. Haven't tested in previous versions.

## Your Environment
* Version used: **minio version RELEASE.2021-04-18T19-26-29Z**
* Server setup and configuration: **Hyper-V 10.0.17763**
* Operating System and version: **Windows Server 2016 Standard x64 (10.0.14393)**

**Comment by harshavardhana** [comment]
Delete calls always return even if the fail or success as 204 as per AWS S3 behavior we are just complying.

Also client encoding bugs we can't fix and auto correct clients - we do not know if this was legitimate request or not without context. So that is out of our scope.

Closing this as not our issue. This is just an expected S3 API behavior.

**Comment by uhfath** [comment]
I understand. Thanks.
Perhaps it even makes sense to always return 204 since the resource is not there in any case.
