### ISSUE TITLE
Why is Content-Md5 required when using Content-SHA256?

### ISSUE THREAD

**Issue by uhfath** [minio/minio#12118]
When issuing a "PutObjectLegalHold" API request without setting "Content-Md5" header minio reports
"Missing required header for this request: Content-Md5."

But what is the purpose of it since we have SHA256?
I see that [AWS S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLegalHold.html) mentions this header, but not as a required or anything like that.
Other requests, like getting, putting and deleting objects do not require this header.

## Expected Behavior
No need for "Content-Md5" header and MD5 calculations.

## Current Behavior
Error is returned at least for "PutObjectLegalHold" API request.

## Possible Solution
Perhaps not to restrict the usage of this header since we have "Content-SHA256"

## Steps to Reproduce (for bugs)
1. Send a "PutObjectLegalHold" request without a "Content-Md5" header value set.

## Context
Using Md5 is not secure. More than that on my platform (Blazor) it's not and never will be supported.

## Regression
No idea. Haven't tested in previous versions.

## Your Environment
* Version used: **minio version RELEASE.2021-04-18T19-26-29Z**
* Server setup and configuration: **Hyper-V 10.0.17763**
* Operating System and version: **Windows Server 2016 Standard x64 (10.0.14393)**

**Comment by harshavardhana** [comment]
It's AWS S3 API requirement, not us :-) - we are simply complying.

They require content-md5 to be mandatory for these APIs, don't read their docs they don't tell the full story. 

You have to really make those API calls on AWS S3 and figure these details out which we did for compliance purposes.

So we can't really change it..

**Comment by uhfath** [comment]
Got it. Thanks.
I guess some legacy stuff in AWS S3.
But it's a pity they don't mention things like this.

**Comment by uhfath** [comment]
On a side note, is there any place that defines a list of APIs that require this header in minio?

**Comment by harshavardhana** [comment]
> On a side note, is there any place that defines a list of APIs that require this header in minio?

Unfortunately No. All legal hold and compliance related requires this..

**Comment by uhfath** [comment]
Thanks!
