### ISSUE TITLE
Cannot set-up webhook in config

### ISSUE THREAD

**Issue by bryanyip94** [minio/minio#12112]
Tried to set-up a webhook to an Openfaas function to get notification for every PUT event, but keep receiving the error: mc.exe: <ERROR> Unable to set 'notify_webhook:1 queue_limit=0 endpoint=http://127.0.0.1:57860/function/hello-python queue_dir=' to server: not connected to target server/service. Problem only occurs when Minio is deployed on Kubernetes.

Expected Behavior
Config file should be updated

Current Behavior
Continuously receiving an error

Possible Solution

Steps to Reproduce (for bugs)
- Create minio using kubectl and yaml files
- mc admin config set myminio notify_webhook:1 queue_limit="0" endpoint="http://127.0.0.1:57860/function/hello-python" queue_dir=""

Context
Regression
Your Environment
Version used (minio version): minio version RELEASE.2021-04-06T23-11-00Z
Environment name and version (e.g. nginx 1.9.1):
Server type and version:
Operating System and version (uname -a): windows 10
Link to your project:

**Comment by harshavardhana** [comment]
> Tried to set-up a webhook to an Openfaas function to get notification for every PUT event, but keep receiving the error: mc.exe: Unable to set 'notify_webhook:1 queue_limit=0 endpoint=http://127.0.0.1:57860/function/hello-python queue_dir=' to server: not connected to target server/service. Problem only occurs when Minio is deployed on Kubernetes.

In k8s you need to make sure your webhook is running locally as a side car or make sure to use the service name for your openfaas endpoint.

You can't just reuse the same settings from local setup on k8s.

**Comment by bryanyip94** [comment]
But I think the error is that I cannot make any changes to the config file? As it continuously provide the error: 'not connected to target server/service'. What does this error mean? I cannot find much about it online. 

In the documentation I also cannot find how I can deploy Minio with an already configured config file, is this possible?

Sorry I am using Minio for the first time. I hope you can help me.

**Comment by RysisLiang** [comment]
> But I think the error is that I cannot make any changes to the config file? As it continuously provide the error: 'not connected to target server/service'. What does this error mean? I cannot find much about it online.
> 
> In the documentation I also cannot find how I can deploy Minio with an already configured config file, is this possible?
> 
> Sorry I am using Minio for the first time. I hope you can help me.

Hello, I have the same problem. Is there a solution now?

Steps：
- docker run -d \
  -p 9500:9000 \
  -p 9501:9001 \
  -e "MINIO_ROOT_USER=xxx" \
  -e "MINIO_ROOT_PASSWORD=xxx" \
  --name minio1 \
  minio/minio server /data --console-address ":9001"
- mc admin config import localS3 < mycfg.txt    -- result -> mc: <ERROR> Unable to set server config: not connected to target server/service.
