### ISSUE TITLE
minio not preserving ownership

### ISSUE THREAD

**Issue by Leif160519** [minio/minio#12123]
## Expected Behavior

Minio should save the file attributes when uploading files through the web

## Current Behavior
The actual test found that it cannot

## Steps to Reproduce (for bugs)

1.
```
ll /home/gens/weichao.pem 
-rwxrwxr-x 1 gens gens 1.7K 1月  18 16:06 /home/gens/weichao.pem*
```
2.web upload to minio
3.
``` ll /data/minio/data/weichao.pem 
-rw-r--r-- 1 root root 1.7K 4月  23 10:07 /data/minio/data/windows-soft/weichao.pem
```

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-12-23T02-24-12Z
* Server setup and configuration:
* Operating System and version (`uname -a`):Linux 5.8.0-26-generic

**Comment by harshavardhana** [comment]
> ```llvm
> ```llvm
> -rw-r--r-- 1 root root 1.7K 4月  23 10:07 /data/minio/data/windows-soft/weichao.pem
> ```
> ```

You are running MinIO as a root user @Leif160519

**Comment by Leif160519** [comment]
Thank you for your reply,
I just re-run minio with a normal account, and found that the file attributes are still not preserved, and the docker runs minio as root. Can this be similar to mc, and the file attributes are preserved through startup parameters?

**Comment by Leif160519** [comment]
> > ```llvm
> > llvm
> > -rw-R - R-- 1根根1 .7K 4月  23  10：07 /data/minio/data/windows-soft/weichao.pem
> > ```
> 
> 您正在以root用户@ Leif160519的身份运行MinIO


thank you for your reply,
I just re-run minio with a normal account, and found that the file attributes are still not preserved, and the docker runs minio as root. Can this be similar to mc, and the file attributes are preserved through startup parameters?

**Comment by harshavardhana** [comment]
> > > ```llvm
> > > llvm
> > > -rw-R - R-- 1根根1 .7K 4月  23  10：07 /data/minio/data/windows-soft/weichao.pem
> > > ```
> > 
> > 
> > 您正在以root用户@ Leif160519的身份运行MinIO
> 
> thank you for your reply,
> I just re-run minio with a normal account, and found that the file attributes are still not preserved, and the docker runs minio as root. Can this be similar to mc, and the file attributes are preserved through startup parameters?

You should run docker as your `docker run  --user`
