### ISSUE TITLE
web can open but can not connect with py sdk

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/minio#12126]
I have set up minio and nginx to proxy to it with postfix "minio" , such as http://hostname/minio to http://minio_ip:9000. After set it to nginx, I can open http://hostname/minio, but can not connect it with minio python sdk, it seems "path in endpoint is not allowed"

**Comment by TestMsr** [comment]
'/minio' will be treated as bucket name in path-style.
you will have to modify the sdk

**Comment by vadmeste** [comment]
@HaoLiuHust nginx is not allowed to modify the request path, this will break the S3 protocol, so you cannot add a 'minio' prefix here.

What you can do is add a subdomain to your hostname, so the endpoint will be http://minio.hostname/
