### ISSUE TITLE
download file not support more than 256KiB

### ISSUE THREAD

**Issue by Andy6Loda** [minio/minio#12148]
**Is your feature request related to a problem? Please describe.**
MinIO Helm Chart install on k8s, the pv/pvc use glusterfs. The file size is 128KiB is ok ,but not work on large than 256KiB

**Additional context**
LOG ERROR:

Error: Unable to write all the data to client /has incomplete body (*fmt.wrapError)
: cmd/object-handlers.go:516:cmd.objectAPIHandlers.GetObjectHandler()
1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

Error: unexpected EOF (*errors.errorString)
5: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
4: cmd/logger/logonce.go:93:logger.LogOnceIf()
3: cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()
2: cmd/erasure.go:364:cmd.erasureObjects.nsScanner()
1: cmd/erasure-server-pool.go:478:cmd.(*erasureServerPools).NSScanner.func2()

minio version 2021-04-22 and 2021-04-18 both error

[root@host100 abc]# ./mc cp version0422/ttt/112233 0422test
mc: <ERROR> Failed to copy `http://10.10.20.170:32123/ttt/112233`. Input reader closed pre-maturely. Expected `111635267` bytes, but only received `111149056` bytes.
[root@host100 abc]# ./mc cp version0422/ttt/min 0422test
http://10.10.20.170:32123/ttt/min:         9 B / 9 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 2 B/s 3s

**Comment by harshavardhana** [comment]
Can you more details, I can't see how this is possible?

**Comment by harshavardhana** [comment]
Just tried, it looks like its able to download properly - looks like some GlusterFS configuration issue.  Do not use backend PVCs from GlusterFS if you are not using NAS gateway.

If you are trying to run distributed setup on top of GlusterFS its not supported.
