### ISSUE TITLE
AGPL compliance issue

### ISSUE THREAD

**Issue by marcan** [minio/minio#12155]
Hi MinIO folks,

I learned that MinIO switched to the AGPL, and I was curious to see how the project achieves AGPL compliance, which is notoriously difficult and underdocumented for projects which do not have a sole copyright owner (only common for commercial software with open source dumps and with some oddball free projects that require copyright assignment, like the FSF's own). Unfortunately, given the AGPL as written, it would seen MinIO is currently in violation of its own license. More specifically, all MinIO contributors after the license change are in violation of all prior contributors' copyright.

Commit 06943256 switched the license of the project to AGPLv3. While it is unclear exactly how this relicensing affects the existing Apache licensed codebase, it is quite unambiguous that any further contributions after this point would be licensed under the AGPLv3.

The next commit, c829e3a1, was co-authored by @krisis, @poornas, and @krishnasrinivas. The code introduced by this commit would be licensed under the AGPLv3, and unambiguously make the derivative work it creates AGPLv3-only. As MinIO does not require copyright assignment for contributions, the overall codebase at this point is a derivative work authored by many people, and these three people have a copyright interest in the work as licensed under the AGPLv3.

In the next commit, 4d53054f, @harshavardhana modified an AGPLv3 program. As they do not own the copyright to the entire program, they are bound to follow its license when making modifications to the copyrighted work it covers.

Clause 13 of the AGPLv3 reads as follows:

> 13. Remote Network Interaction; Use with the GNU General Public License.
> 
> Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. This Corresponding Source shall include the Corresponding Source for any work covered by version 3 of the GNU General Public License that is incorporated pursuant to the following paragraph.

Therefore, the modified version authored by @harshavardhana must "prominently offer all users interacting with it remotely [...] an opportunity to receive the Corresponding Source".

This offer is not in place. Building and running MinIO yields no source code offer when accessed via `curl`:

```
$ curl -i http://192.168.3.10:9000
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Length: 226
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 167944E3B8BA24E3
X-Xss-Protection: 1; mode=block
Date: Mon, 26 Apr 2021 01:41:25 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>167944E3B8BA24E3</RequestId><HostId>642b02d4-039e-427c-9719-06764cf33e91</HostId></Error>
```

Nor via the web browser:

![image](https://user-images.githubusercontent.com/98387/116018282-ae93a800-a67c-11eb-8f7f-81830d41a2d7.png)

In both cases references to MinIO being the server exist, but there is no link or reference to a network server from which the user may receive the source code, nor is there any reference to the exact source code version used to build MinIO. I do not see how this can meet the requirements of the license.

**Comment by harshavardhana** [comment]
Please email us at legal@minio.io or hello@minio.io for specific discussions such as these @marcan.  Closing this issue as the interpretation here is not legally vetted requires a more offline analysis.

> Therefore, the modified version authored by @harshavardhana must "prominently offer all users interacting with it remotely [...] an opportunity to receive the Corresponding Source".

The source code is directly available here at https://github.com/minio/minio
