### ISSUE TITLE
grafana dashboard no data

### ISSUE THREAD

**Issue by MoonJustry** [minio/minio#12165]
grafrana import from docs/metrics/prometheus/grafana/minio-overview.json, but the default metrics not matched, like Uptime panel, default metric is `process_start_time_seconds`, but not exist, query process_start* results is : `minio_node_process_starttime_seconds`
There is the same problem with minio-console dashbord
## Expected Behavior

maybe ![image](https://user-images.githubusercontent.com/12591294/116183371-4e6e3600-a750-11eb-8bab-d61ad6a920bd.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/12591294/116183245-2252b500-a750-11eb-9377-ad34308dcfcf.png)

## Possible Solution

![image](https://user-images.githubusercontent.com/12591294/116183363-4a421880-a750-11eb-8d80-8068191902c5.png)

## Steps to Reproduce (for bugs)

1. configure prometheus according to https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html and `metrics_path: /minio/v2/metrics/cluster`
3. configure garafana, and import dashbord by id 13502 or by json input docs/metrics/prometheus/grafana/minio-overview.json
4. dashbord panels N/A

## Your Environment

* Version used (`minio --version`): Version: 2021-04-21T03:40:16Z based on RELEASE.2021-04-18T19-26-29Z
* Server setup and configuration: prometheus auth is public, others default config
* Operating System and version (`uname -a`):

scrape_configs:
- job_name: minio-job
  bearer_token: *****
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['****"]

**Comment by harshavardhana** [comment]
Yeah if you use 

> job_name: minio-job
> bearer_token: *****
> metrics_path: /minio/v2/metrics/cluster
> scheme: http
> static_configs:
> * targets: ['****"]

the current dashboard won't show the metrics @MoonJustry you need to use `/minio/prometheus/metrics`

**Comment by MoonJustry** [comment]
> Yeah if you use
> 
> > job_name: minio-job
> > bearer_token: *****
> > metrics_path: /minio/v2/metrics/cluster
> > scheme: http
> > static_configs:
> > 
> > * targets: ['****"]
> 
> the current dashboard won't show the metrics @MoonJustry you need to use `/minio/prometheus/metrics`

`/minio/prometheus/metrics`, it works, thanks!
Maybe can add some hints to the current document.

**Comment by harshavardhana** [comment]
> > Yeah if you use
> > > job_name: minio-job
> > > bearer_token: *****
> > > metrics_path: /minio/v2/metrics/cluster
> > > scheme: http
> > > static_configs:
> > > 
> > > * targets: ['****"]
> > 
> > 
> > the current dashboard won't show the metrics @MoonJustry you need to use `/minio/prometheus/metrics`
> 
> `/minio/prometheus/metrics`, it works, thanks!
> Maybe can add some hints to the current document.

Sure we will @MoonJustry
