### ISSUE TITLE
export and import all config from minio

### ISSUE THREAD

**Issue by fvahid** [minio/minio#12169]
I know in minio all config including user password , bucket ILM and other staff palced in .minio.sys directory
would we have any solution to backup all config and import onto another minio server ?

**Comment by harshavardhana** [comment]
> I know in minio all config including user password , bucket ILM and other staff palced in .minio.sys directory
> would we have any solution to backup all config and import onto another minio server ?

Right now no such solution exists, we can provide a command in future for full migration.

Closing this issue for now as we don't have any immediate plans to work on this.
