### ISSUE TITLE
lockBlocking: lockLossCallback not always called

### ISSUE THREAD

**Issue by klauspost** [minio/minio#12160]
[(*distLockInstance).GetLock()`](https://github.com/minio/minio/blob/069432566fcfac1f1053677cc925ddafd750730a/cmd/namespace-lock.go#L146) creates a new context, but the provided cancelation function is not always called.

This leaks memory:

![leak](https://user-images.githubusercontent.com/5663952/116111932-6180f780-a6b7-11eb-854b-0f90c03c5538.png)

## Expected Behavior

The [returned cancel function](https://github.com/minio/minio/blob/069432566fcfac1f1053677cc925ddafd750730a/cmd/namespace-lock.go#L150)  is *always* called.

## Current Behavior

Various conditions cause it not to be called.

## Possible Solution

Ensure that all return paths/scenarios call this function.

## Steps to Reproduce (for bugs)

Should be clear from the source. Solution isn't obvious trivial to me.

## Context

Memory builds up over time.

## Regression

Appears to be after #11535

**Comment by vadmeste** [comment]
oups, good catch @klauspost. 

I will review the code, it should not be hard to fix.

**Comment by harshavardhana** [comment]
Wouldn't it be just this? 

```diff
git diff
diff --git a/pkg/dsync/drwmutex.go b/pkg/dsync/drwmutex.go
index 8909630d8..7b8dfa52d 100644
--- a/pkg/dsync/drwmutex.go
+++ b/pkg/dsync/drwmutex.go
@@ -182,6 +182,9 @@ func (dm *DRWMutex) lockBlocking(ctx context.Context, lockLossCallback func(), i
        for {
                select {
                case <-ctx.Done():
+                       if lockLossCallback != nil {
+                               lockLossCallback()
+                       }
                        return false
                default:
                        // Try to acquire the lock.
@@ -228,6 +231,9 @@ func (dm *DRWMutex) startContinousLockRefresh(lockLossCallback func(), id, sourc
                for {
                        select {
                        case <-ctx.Done():
+                               if lockLossCallback != nil {
+                                       lockLossCallback()
+                               }
                                return
                        case <-refreshTimer.C:
                                refreshTimer.Reset(drwMutexRefreshInterval)
```
