### ISSUE TITLE
minio kerberos

### ISSUE THREAD

**Issue by jiajinhui** [minio/minio#12168]
https://github.com/minio/minio/pull/7581

I added Kerberos authentication according to your method, but it didn't work. This is my startup script  run.sh

#!/bin/bash
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=adminadmin
export MINIO_KERBEROS_KEYTAB=/data/opt/keytab/minio.service.keytab
/data/opt/minio/run/minio server --address "192.XXX.XXX.119:9000"
http://192.XXX.XXX.119/data/opt/minio/data1 http://192.XXX.XXX.119/data/opt/minio/data2
http://192.XXX.XXX.121/data/opt/minio/data1 http://192.XXX.XXX.121/data/opt/minio/data2
http://192.XXX.XXX.122/data/opt/minio/data1 http://192.XXX.XXX.122/data/opt/minio/data2 \

Can boot successfully, but Kerberos authentication is not enabled,
On the other server 192.XXX.XXX.117, the Kerberos Client and MC are installed on this server.

Without kinit, use MC access (MC ls myMinio), still can access successfully. Shouldn't we use MC to access only after kinit? I don't know if my understanding is correct or if there is something wrong with the configuration. Please advise me

![image](https://user-images.githubusercontent.com/33280933/116194758-dc075100-a763-11eb-9169-e7ca93bb7651.png)

This is the configuration of my MC:
![image](https://user-images.githubusercontent.com/33280933/116194861-00fbc400-a764-11eb-89cf-e4a5dcbfeced.png)

**Comment by harshavardhana** [comment]
We do not support Kerberos in MinIO @jiajinhui

**Comment by jiajinhui** [comment]
![image](https://user-images.githubusercontent.com/33280933/116205641-884f3480-a770-11eb-849c-f09163addc23.png)
However, Minio does support  Kerberos with HDFS

I have tried this, and if HDFS enabled Kerberos, Minio is deployed based on HDFS and can be configured successfully

Here is my startup script:
#!/bin/bash
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=adminadmin
export HADOOP_CONF_DIR=/data/opt/hadoop3/etc/hadoop
export HADOOP_HOME=/data/opt/hadoop3
export KRB5_CONFIG=/etc/krb5.conf
export KRB5KEYTAB=/data/opt/keytab/minio.service.keytab
export KRB5USERNAME=minio
export KRB5REALM=HADOOP.COM
/data/opt/minio/run/minio gateway hdfs

This deployment of Minio Server does not support Kerberos？
