### ISSUE TITLE
Unable to initialize gateway backend: mkdir /.minio.sys/tmp: no available namenodes: write tcp x.x.x.165:x->x.x.x.115:8020: write: broken pipe

### ISSUE THREAD

**Issue by lynch2git** [minio/minio#12176]
Hello everyone, I encountered a issue.
## Expected Behavior

I am trying to start a minio using gateway hdfs with kerberos.
## Current Behavior

When i starting minio, it report an error.
## Steps to Reproduce (for bugs)

1. init a shell with all the needed:
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export KRB5_CONFIG=/opt/apps/minio/krb5.conf
export KRB5KEYTAB=/opt/apps/minio/user1.keytab
export KRB5USERNAME=user1
export KRB5REALM=DATA02.COM
./minio gateway hdfs hdfs://192.168.0.115:8020

2. exec the shell
[root@dfs-3 run]# ./run.sh

3. retrieve error :
ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: no available namenodes: write tcp 192.168.0.165:12015->192.168.0.115:8020: write: broken pipe

## Context

1. There is no problem executing the command 'ping 192.168.0.115' and 'telnet 192.168.0.115 8020' on node 192.168.0.165.
2. Executing the command 'klist' on node 192.168.0.165:
```
[root@dfs-3 minio]# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: user1@DATA02.COM

Valid starting       Expires              Service principal
04/25/2021 18:35:27  03/30/2026 18:35:26  krbtgt/DATA02.COM@DATA02.COM
```
3. Executing the command 'hdfs dfs -ls' on node 192.168.0.165 is ok:
```
[root@dfs-3 minio]# hdfs dfs -ls hdfs://192.168.0.115:8020/
Found 10 items
drwxr-xr-x   - hdfs   hdfs            0 2021-04-20 16:49 hdfs://192.168.0.115:8020/apps
drwx------   - hdfs   hdfs            0 2021-04-21 17:03 hdfs://192.168.0.115:8020/flink
drwxr-xr-x   - hdfs   hdfs            0 2021-04-20 16:43 hdfs://192.168.0.115:8020/hdp
drwxr-xr-x   - mapred hdfs            0 2021-04-20 16:43 hdfs://192.168.0.115:8020/mapred
drwxrwxrwx   - mapred hadoop          0 2021-04-20 16:44 hdfs://192.168.0.115:8020/mr-history
drwxr-xr-x   - hdfs   hdfs            0 2021-04-20 16:44 hdfs://192.168.0.115:8020/services
drwxrwxrwx   - spark  hadoop          0 2021-04-23 17:23 hdfs://192.168.0.115:8020/spark2-history
drwx------   - hdfs   hdfs            0 2021-04-21 18:33 hdfs://192.168.0.115:8020/tenant
drwxrwxrwx   - hdfs   hdfs            0 2021-04-22 11:30 hdfs://192.168.0.115:8020/tmp
drwxrwxrwx   - hdfs   hdfs            0 2021-04-21 17:02 hdfs://192.168.0.115:8020/user
```

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2021-04-22T15-44-28Z

* HDFS Version:
3.0.0

* Server setup and configuration:
SELinux and IPTables from the environment are disabled.

* Operating System and version (`uname -a`):
Linux dfs-3 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Anyone encountered this issue ?

Regards,
Lynch

**Comment by harshavardhana** [comment]
> ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: no available namenodes: write tcp 192.168.0.165:12015->192.168.0.115:8020: write: broken pipe

This error is the key here @lynch2git looks like namenode is returning an error for our requests.

**Comment by lynch2git** [comment]
The namenode report some errors when i starting minio:
```
2021-04-29 10:51:54,389 INFO  ipc.Server (Server.java:doRead(1249)) - Socket Reader #1 for port 8020: readAndProcess from client 192.168.0.165:30291 threw exception [org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]]
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
	at org.apache.hadoop.ipc.Server$Connection.initializeAuthContext(Server.java:2129) ~[hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Connection.readAndProcess(Server.java:2078) ~[hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Listener.doRead(Server.java:1242) [hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Listener$Reader.doRunLoop(Server.java:1098) [hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Listener$Reader.run(Server.java:1069) [hadoop-common-3.0.0-cdh6.2.0.jar:?]
2021-04-29 10:52:01,449 INFO  ipc.Server (Server.java:doRead(1249)) - Socket Reader #1 for port 8020: readAndProcess from client 192.168.0.165:30297 threw exception [org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]]
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
	at org.apache.hadoop.ipc.Server$Connection.initializeAuthContext(Server.java:2129) ~[hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Connection.readAndProcess(Server.java:2078) ~[hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Listener.doRead(Server.java:1242) [hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Listener$Reader.doRunLoop(Server.java:1098) [hadoop-common-3.0.0-cdh6.2.0.jar:?]
	at org.apache.hadoop.ipc.Server$Listener$Reader.run(Server.java:1069) [hadoop-common-3.0.0-cdh6.2.0.jar:?]

```

**Comment by harshavardhana** [comment]
Your configuration should have the following entries

### Setup Kerberos

MinIO supports two Kerberos authentication methods, keytab, and ccache.

To enable Kerberos authentication, you need to set `hadoop.security.authentication=kerberos` in the HDFS config file.

```xml
<property>
  <name>hadoop.security.authentication</name>
  <value>kerberos</value>
</property>
```

MinIO will load `krb5.conf` from environment variable `KRB5_CONFIG` or default location `/etc/krb5.conf`.
```sh
export KRB5_CONFIG=/path/to/krb5.conf
```

**Comment by lynch2git** [comment]
@harshavardhana Hi, Harshavardhana, i checked my configuration again, i have set these two configurations, i set it up by referring to http://docs.min.io

**Comment by harshavardhana** [comment]
@lynch2git then I do not know unfortunately, I don't have HDFS setup so can't really validate what might be an issue.

**Comment by lynch2git** [comment]
Okay, please wait for me for a few hours. I will go to the company to get the HDFS setup after daybreak (because I am not in the US, my current time is 01:00 a.m.), then please help me to see if the configuration is has a problem.

**Comment by lynch2git** [comment]
@harshavardhana Hi, harshavardhana, this is part of the my HDFS setup and minio setup. If you need other configurations, please let me know.
[mysetup.zip](https://github.com/minio/minio/files/6409021/mysetup.zip)

**Comment by lynch2git** [comment]
I have solved this problem. Reason: my `HADOOP_CONF_DIR` environment variable is not configured correctly, so the `core-site.xml` file is not loaded.
