### ISSUE TITLE
Minio does support  Kerberos with HDFS？

### ISSUE THREAD

**Issue by jiajinhui** [minio/minio#12170]
![image](https://user-images.githubusercontent.com/33280933/116205641-884f3480-a770-11eb-849c-f09163addc23.png)
However, Minio does support  Kerberos with HDFS

I have tried this, and if HDFS enabled Kerberos, Minio is deployed based on HDFS and can be configured successfully

Here is my startup script:
#!/bin/bash
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=adminadmin
export HADOOP_CONF_DIR=/data/opt/hadoop3/etc/hadoop
export HADOOP_HOME=/data/opt/hadoop3
export KRB5_CONFIG=/etc/krb5.conf
export KRB5KEYTAB=/data/opt/keytab/minio.service.keytab
export KRB5USERNAME=minio
export KRB5REALM=HADOOP.COM
/data/opt/minio/run/minio gateway hdfs

This deployment of Minio Server does not support Kerberos？

_Originally posted by @jiajinhui in https://github.com/minio/minio/issues/12168#issuecomment-827407819_

**Comment by harshavardhana** [comment]
> ![image](https://user-images.githubusercontent.com/33280933/116205641-884f3480-a770-11eb-849c-f09163addc23.png)
> However, Minio does support Kerberos with HDFS
> 
> I have tried this, and if HDFS enabled Kerberos, Minio is deployed based on HDFS and can be configured successfully
> 
> Here is my startup script:
> #!/bin/bash
> export MINIO_ACCESS_KEY=minio
> export MINIO_SECRET_KEY=adminadmin
> export HADOOP_CONF_DIR=/data/opt/hadoop3/etc/hadoop
> export HADOOP_HOME=/data/opt/hadoop3
> export KRB5_CONFIG=/etc/krb5.conf
> export KRB5KEYTAB=/data/opt/keytab/minio.service.keytab
> export KRB5USERNAME=minio
> export KRB5REALM=HADOOP.COM
> /data/opt/minio/run/minio gateway hdfs
> 
> This deployment of Minio Server does not support Kerberos？
> 
> _Originally posted by @jiajinhui in [#12168 (comment)](https://github.com/minio/minio/issues/12168#issuecomment-827407819)_

Yes hdfs gateway supports kerberos but only for backend communication.

Kerberos support is not present for S3 calls.
