### ISSUE TITLE
#12172 introduces regression when accessing html files in public buckets

### ISSUE THREAD

**Issue by CosmicToast** [minio/minio#12179]
## Expected Behavior
Assume I have a bucket `foo`.
It is set up for anonymous access.
If I have `myminio/foo/bar.html`, I would expect to be able to access it via `minio.link/foo/bar.htm`l

## Current Behavior

As of #12172 this is redirecting me to the console project instead of showing the html output of `foo/bar.html`.

## Possible Solution

Only redirect to the minio/console exclusively on `/` (and maybe `/minio` and `/minio/`), not any other endpoints.

## Steps to Reproduce (for bugs)

1. Build minio from git.
2. Create bucket, set its policy to allow anonymous readonly access.
3. Create `foo.html` in it.
4. Try to access it (e.g http://my.minio.com/mybucket/foo.html) in a browser.

## Context

I host .html pages in publicly accessible buckets for various reasons.
However, this goes beyond this - a common case for minio is to host things like image files in a CDN-like fashion - this breaks that as well when they're viewed through a browser (i.e most of the time).

## Regression

Yes, this is a regression.
It appears to be caused by #12172

## Your Environment

* Version used (`minio --version`): latest HEAD (built a few minutes ago)
* Server setup and configuration: Single (filesystem) minio instance.
* Operating System and version (`uname -a`): Linux fafnir 5.11.16-0-edge #1-Alpine SMP PREEMPT Wed, 21 Apr 2021 12:36:06 +0000 x86_64 Linux

**Comment by harshavardhana** [comment]
The browser code is removed from master so this is a change that we wanted to have, let me check if there is a way to avoid this for anonymous requests.

**Comment by CosmicToast** [comment]
Yes, I understand that the browser code is removed, and I have the console running under /console now.
However, the issue is that this interferes with minio's ability to do its actual job (i.e serve files) - something that did not depend on the browser code.
In other words, the regression is not that the old console ui is gone, but that the files that would normally be accessible (and are in no way related to the browser code!) are no longer such.
