### ISSUE TITLE
Files uploaded using presignedPostPolicy does not emit bucket notifications

### ISSUE THREAD

**Issue by chpaulin** [minio/minio#12180]
We have experienced that MinIO is not fireing the ObjectCreated notifications when a file is uploaded using presignedPostPolicy. It works fine using the presignedPutObject. 

## Expected Behavior
When POSTING a file using presignedPostPolicy we expect the ObjectCreatedPost or ObjectCreatedCompleteMultipartUpload to fire.

## Current Behavior
When POSTING a file using presignedPostPolicy no notification is emitted

## Possible Solution
Don't know at this time

## Steps to Reproduce (for bugs)
1. Launch an instance of MinIO and configure a webhook that listens for all ObjectCreated notifications `s3:ObjectCreated:*`
2. Generate the form data needed for upload. Example in JS using nodeJS and expressJS
``` javascript
server.get('/presignedPost', (req: any, res: any) => {

    const policy = new Minio.PostPolicy()
    policy.setBucket('some-bucket')    
    policy.setContentType('video/x-matroska;codecs=avc1,opus')
    policy.setKey('files/uploads/name-of-file.mkv')    

    client.presignedPostPolicy(policy, (err, result) => {
        if (err) throw err
        res.json(result)
        res.end()
    })
})
```
3. Using the URL and FormData returned from the above request call POST with the file added to the form as key `file`
4. The webhook will not be invoked as no notification is created

## Context
We cant change to use presignedPutObject as we are using a third party component called Uppy/Companion and all the logic creating the presigned solution is in there.

We have webhooks listening for these notifications and would be happy if this is a configuration misshap from our side.

## Your Environment
Docker Image: minio/minio:RELEASE.2021-04-06T23-11-00Z.hotfix.65162d087
Docker Host: Ubuntu 20.04 x64

**Comment by harshavardhana** [comment]
have you enabled `mc event add` to enable notifications? for the bucket?

**Comment by harshavardhana** [comment]
Here is how I tested

```
~ mc watch myminio/
[2021-04-28T20:14:39.806Z]  525 B s3:ObjectCreated:Put http://127.0.0.1:9000/bucket/1.txt
```

```
~ minio server ~/test
Endpoint: http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000               
RootUser: minio 
RootPass: minio123 

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
IAM initialization complete
```

```
~ curl http://127.0.0.1:9000/bucket/ -F x-amz-signature=82c5b1a923068c654b082f20de63d599f404e3f54da71f501cf74ae814e359be -F bucket=bucket -F policy=eyJleHBpcmF0aW9uIjoiMjAyMS0wNS0wNVQyMDoxNDoyOS41OTNaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwiYnVja2V0Il0sWyJlcSIsIiRrZXkiLCIxLnR4dCJdLFsiZXEiLCIkeC1hbXotZGF0ZSIsIjIwMjEwNDI4VDIwMTQyOVoiXSxbImVxIiwiJHgtYW16LWFsZ29yaXRobSIsIkFXUzQtSE1BQy1TSEEyNTYiXSxbImVxIiwiJHgtYW16LWNyZWRlbnRpYWwiLCJtaW5pby8yMDIxMDQyOC91cy1lYXN0LTEvczMvYXdzNF9yZXF1ZXN0Il1dfQ== -F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=minio/20210428/us-east-1/s3/aws4_request -F x-amz-date=20210428T201429Z -F key=1.txt -F file=@/etc/hosts
```

Looks like notifications are working fine.

**Comment by chpaulin** [comment]
> have you enabled `mc event add` to enable notifications? for the bucket?

Specificly for adding files using POST? It works great using any other means of uploading files; dropping a file directly into the Web UI, using presignedPutObject and using the s3Client PutObjectCommand in JS

**Comment by harshavardhana** [comment]
> Specificly for adding files using POST? It works great using any other means of uploading files; dropping a file directly into the Web UI, using presignedPutObject and using the s3Client PutObjectCommand in JS

Can you elaborate more on how the webhook is setup? I can't see how its possible.

**Comment by chpaulin** [comment]
> > Specificly for adding files using POST? It works great using any other means of uploading files; dropping a file directly into the Web UI, using presignedPutObject and using the s3Client PutObjectCommand in JS
> 
> Can you elaborate more on how the webhook is setup? I can't see how its possible.

@harshavardhana thanks for looking into this with such short notice.

So what I am saying is that using POST to upload a file seems to be the only time we don't get a notification

``` javascript
var formdata = new FormData();
formdata.append("bucket", "some-bucket,");
formdata.append("Content-Type", "video/x-matroska;codecs=avc1,opus");
formdata.append("key", "files/uploads/test2.mkv");
formdata.append("x-amz-date", "20210428T062235Z");
formdata.append("x-amz-algorithm", "AWS4-HMAC-SHA256");
formdata.append("x-amz-credential", "AKIAIOSFODNN7EXAMPLE/20210428/us-east-1/s3/aws4_request");
formdata.append("policy", "eyJjb25kaXRpb25zIjpb...");
formdata.append("x-amz-signature", "6f3da4be...");
formdata.append("file", fileInput.files[0], "/C:/Users/user/Downloads/webcam-1619550361261.mkv");

var requestOptions = {
  method: 'POST',
  body: formdata,
  redirect: 'follow'
};

fetch("http://localhost:9000/hh-stage", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

The FormData parameters where generated using the Minio client as seen in the issue definition

Using PUT works great but as stated it's not under our control to choose that approach as Uppy has choosen the POST approach

**Comment by harshavardhana** [comment]
Still, it rather looks strange since notification should happen regardless @chpaulin unless you set your notification to be specifically s3:Put - as I can see with `mc watch`

**Comment by chpaulin** [comment]
> Still, it rather looks strange since notification should happen regardless @chpaulin unless you set your notification to be specifically s3:Put - as I can see with `mc watch`

Ah I see, yes that could ofc have been the issue.

This is my Webhook setup
``` javascript

const minioClient = new Client(config);

(async function initialize() {
  // Create a new notification object
  const bucketNotification = new Minio.NotificationConfig();

  // Setup a new Queue configuration
  const arn = Minio.buildARN('minio', 'sqs', '', config.accountID, 'webhook')

  const queue = new Minio.QueueConfig(arn)
  queue.addEvent(Minio.ObjectCreatedAll) //Corresponds to s3:ObjectCreated:*
  queue.addFilterPrefix('files/uploads')

  // Add the queue to the overall notification object
  bucketNotification.add(queue)

  await waitForConnectivity()

  try {
    await minioClient.setBucketNotification(config.bucket, bucketNotification)
    console.log('Success')
  } catch (err) {
    console.log(err)
  }
})()
```

**Comment by chpaulin** [comment]
@harshavardhana: I tested with `mc watch` and I got the put event when I posted it seems
```
[2021-04-28T20:37:38.073Z] 3.0 MiB s3:ObjectCreated:Put http://10.0.0.1:9000/hh-stage/files/uploads/test2.mkv
```
But this is not being sent to my webhook for some reason

Dropping the same file in the WebUI i get a similar notification and this is also received by ny webhook
```
[2021-04-28T20:41:10.170Z] 3.0 MiB s3:ObjectCreated:Put http://10.0.0.1:9000/hh-stage/files/uploads/webcam-1619550361261.mkv
```

**Comment by harshavardhana** [comment]
@chpaulin can you share your `GetBucketNotification` XML ? - this would show us your configuration..

**Comment by chpaulin** [comment]
> `GetBucketNotification` XML

Where can I find that?

**Comment by harshavardhana** [comment]
> Where can I find that?

when you said you have setup notifications - how is that done? can you describe?

**Comment by chpaulin** [comment]
> > Where can I find that?
> 
> when you said you have setup notifications - how is that done? can you describe?

Maybe not the best phrasing on my part. I have done nothing on the server side what so ever except for adding two Enviroment variables:
```
MINIO_NOTIFY_WEBHOOK_ENABLE_2=on
MINIO_NOTIFY_WEBHOOK_ENDPOINT_2=http://10.0.0.1:9006
```
If i run the following after setting up my notifications in the webhook service
``` javascript
minioClient.getBucketNotification('hh-stage', function(err, bucketNotificationConfig) {
  if (err) return console.log(err)
  console.log(JSON.stringify(bucketNotificationConfig))
})
```
i get this
``` json5
{
  "TopicConfiguration": [],
  "QueueConfiguration": [
    {
      "Id": "",
      "Queue": "arn:minio:sqs::2:webhook",
      "Event": [
        "s3:ObjectCreated:*"
      ],
      "Filter": [
        {
          "Name": "prefix",
          "Value": "files/uploads"
        }
      ]
    }
  ],
  "CloudFunctionConfiguration": []
}
```

**Comment by chpaulin** [comment]
Pasted the wrong ENV variables. The identifier ofc matches :)

**Comment by harshavardhana** [comment]
Looks good @chpaulin - will test and let you know.

**Comment by chpaulin** [comment]
> Looks good @chpaulin - will test and let you know. 

@harshavardhana: Greatly appreciated 🙏

**Comment by harshavardhana** [comment]
@chpaulin I tested with master branch - I can't reproduce it all notifications are being notified properly.

**Comment by chpaulin** [comment]
> @chpaulin I tested with master branch - I can't reproduce it all notifications are being notified properly.

Hi @harshavardhana and thanks for looking into it and sorry for not getting back sooner. I had another look at it and I found that it fails only with a specific `Content-Type` => `video/x-matroska;codecs=avc1,opus`

If the content type omits the codec part (`;codecs=avc1,opus`) then we get a call as we expect but not with this addition. `mc watch` gets the notification though. Could it be that the `;` in there is messing with some logic for webhooks? Maybe something in libcUrl?

**Comment by harshavardhana** [comment]
> Hi @harshavardhana and thanks for looking into it and sorry for not getting back sooner. I had another look at it and I found that it fails only with a specific `Content-Type` => `video/x-matroska;codecs=avc1,opus`

Thanks let me look @chpaulin - there should be no dependency as such on this value.

**Comment by harshavardhana** [comment]
> If the content type omits the codec part (`;codecs=avc1,opus`) then we get a call as we expect but not with this addition. `mc watch` gets the notification though. Could it be that the `;` in there is messing with some logic for webhooks? Maybe something in libcUrl?

So `mc watch` gets even with the content-type - AFAICS this seems like some webhook receiving end issue.  Perhaps you are parsing content-type incorrectly?

**Comment by harshavardhana** [comment]
Closing this as not reproducible
