### ISSUE TITLE
"mc ls local" fails with "mc: <ERROR> Unable to list folder. Access Denied."

### ISSUE THREAD

**Issue by somnathchoudhuri** [minio/minio#12189]
## Steps to Reproduce (for bugs)

1. [miniousr@pythnlnx ~]$ ./mc ls local
mc: <ERROR> Unable to list folder. Access Denied.
2. [miniousr@pythnlnx ~]$ ./mc mb local/mybucket
mc: <ERROR> Unable to make bucket `local/mybucket`. Access Denied.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration: CentOS 7 running on i5 CPU with RAM16 GB
* Operating System and version (`uname -a`): Linux pythnlnx.choudhuri.org 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by somnathchoudhuri** [comment]
OS: CentOS 7.3

[miniousr@pythnlnx ~]$ ./minio -version
minio version RELEASE.2021-04-22T15-44-28Z

[miniousr@pythnlnx ~]$ ./mc -version
mc version RELEASE.2021-04-22T17-40-00Z

**Comment by somnathchoudhuri** [comment]
[miniousr@pythnlnx ~]$ cat ~/.mc/config.json
{
        "version": "10",
        "aliases": {
                "gcs": {
                        "url": "https://storage.googleapis.com",
                        "accessKey": "YOUR-ACCESS-KEY-HERE",
                        "secretKey": "YOUR-SECRET-KEY-HERE",
                        "api": "S3v2",
                        "path": "dns"
                },
                "local": {
                        "url": "http://localhost:9000",
                        "accessKey": "",
                        "secretKey": "",
                        "api": "S3v4",
                        "path": "auto"
                },
                "play": {
                        "url": "https://play.min.io",
                        "accessKey": "Q3AM3UQ867SPQQA43P2F",
                        "secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
                        "api": "S3v4",
                        "path": "auto"
                },
                "s3": {
                        "url": "https://s3.amazonaws.com",
                        "accessKey": "YOUR-ACCESS-KEY-HERE",
                        "secretKey": "YOUR-SECRET-KEY-HERE",
                        "api": "S3v4",
                        "path": "dns"
                }
        }
}

**Comment by harshavardhana** [comment]
> [miniousr@pythnlnx ~]$ cat ~/.mc/config.json
> {
> "version": "10",
> "aliases": {
> "gcs": {
> "url": "https://storage.googleapis.com",
> "accessKey": "YOUR-ACCESS-KEY-HERE",
> "secretKey": "YOUR-SECRET-KEY-HERE",
> "api": "S3v2",
> "path": "dns"
> },
> "local": {
> "url": "http://localhost:9000",
> "accessKey": "",
> "secretKey": "",
> "api": "S3v4",
> "path": "auto"
> },
> "play": {
> "url": "https://play.min.io",
> "accessKey": "Q3AM3UQ867SPQQA43P2F",
> "secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
> "api": "S3v4",
> "path": "auto"
> },
> "s3": {
> "url": "https://s3.amazonaws.com",
> "accessKey": "YOUR-ACCESS-KEY-HERE",
> "secretKey": "YOUR-SECRET-KEY-HERE",
> "api": "S3v4",
> "path": "dns"
> }
> }
> }

Your local config has credentials missing @somnathchoudhuri
