### ISSUE TITLE
docker: Docker image doesn't run with ipv6 addresses - checkPortAvailability() needs to be fixed

### ISSUE THREAD

**Issue by gleclaire** [minio/minio#1219]
The Docker Hub seems to only have a latest tag.  Since the current release is not working there does not appear to be a way to use a previous docker image

**Comment by harshavardhana** [comment]
> The Docker Hub seems to only have a latest tag. Since the current release is not working there does not appear to be a way to use a previous docker image

Can you try again? there are two releases `minio/minio:latest` and `minio/minio:edge`

**Comment by krishnasrinivas** [comment]
@gleclaire can you do `service docker stop` `service docker start` and then try starting minio container?

I installed docker on a fresh ubuntu and saw the problem, but it went away once I restarted the docker daemon. (saw someone posting this on stackoverflow)

**Comment by harshavardhana** [comment]
This doesn't seem to be problem and not reproducible, closing for now. Please re-open if seen again.
