### ISSUE TITLE
Manual force healing never finished

### ISSUE THREAD

**Issue by ghost** [minio/minio#12205]
We trigger manual healing by API using `github.com/minio/minio/pkg/madmin#Heal()` method with `force=true` argument inside golang app. After calling this method multiple times for same minio node (k8s pod) it always returns `healTaskStatus: {"summary": "running", ...}` even after healing actually done. healTaskStatus request from another minio node (by healing token) returns `healTaskStatus: {"summary": "finished", ...}`. Looks like race conditions issue.

## Expected Behavior

When healing started by API call with `force=true` flag multiple times one after another then `healTaskStatus: {"summary": "finished", ...}` is expected after healing actually done.

## Current Behavior

When healing started by API call with `force=true` flag multiple times one after another then `healTaskStatus: {"summary": "running", ...}` is always.

## Possible Solution

Unknown.

## Steps to Reproduce (for bugs)

Here is simple program to reproduce:
```golang
package main

import (
	"context"
	"encoding/json"
	"log"
	"strconv"

	"github.com/minio/minio/pkg/madmin"
	"net/http"
)

const s3AccessKey = "XXXXXXXXXXXXXXXX"
const s3SecretKey = "XXXXXXXXXXXXXXXX"
const bucket = "test"

var s3Endpoint = []string{
	"minio-pool0-0.minio-hl.minio.svc.cluster.local:9000",
	"minio-pool0-1.minio-hl.minio.svc.cluster.local:9000",
	"minio-pool0-2.minio-hl.minio.svc.cluster.local:9000",
}
var healOpts = madmin.HealOpts{
	Recursive: true,
	DryRun:    false,
}

var globalContext [3]context.Context
var globalCancel [3]context.CancelFunc
var madmClnt [3]*madmin.AdminClient
var token string

func processHealInvokeResult(healStart madmin.HealStartSuccess, healTaskStatus madmin.HealTaskStatus, err error) error {
	if err != nil {
		log.Println(err)
		return err
	}

	j, e := json.MarshalIndent(healStart, "", "  ")
	if e != nil {
		log.Println(e)
		return e
	}
	log.Println("healStart: " + string(j))
	// flush verbose output
	healTaskStatus.Items = make([]madmin.HealResultItem, 0)
	j, e = json.MarshalIndent(healTaskStatus, "", "  ")
	if e != nil {
		log.Println(e)
		return e
	}
	log.Println("healTaskStatus: " + string(j))

	return nil
}

func startHealing(node int) (clientToken string, err error) {
	healStart, healTaskStatus, err := madmClnt[node].Heal(globalContext[node], bucket, "", healOpts, "", true, false)
	if err = processHealInvokeResult(healStart, healTaskStatus, err); err != nil {
		return clientToken, err
	}
	return healStart.ClientToken, nil
}

func getStatus(node int) error {
	return processHealInvokeResult(madmClnt[node].Heal(globalContext[node], bucket, "", healOpts, token, false, false))
}

func getHealStartHandler(node int) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		clientToken, err := startHealing(node)
		if err == nil {
			token = clientToken
			w.Write([]byte("SUCCESS\n"))
		} else {
			w.Write([]byte("FAIL\n"))
		}
	}
}

func getStatusHandler(node int) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		if getStatus(node) == nil {
			w.Write([]byte("SUCCESS\n"))
		} else {
			w.Write([]byte("FAIL\n"))
		}
	}
}

func main() {
	var err error
	for i := 0; i < 3; i++ {
		globalContext[i], globalCancel[i] = context.WithCancel(context.Background())
		madmClnt[i], err = madmin.New(s3Endpoint[i], s3AccessKey, s3SecretKey, true)
		if err != nil {
			log.Fatalln(err)
		}

		http.HandleFunc("/"+strconv.Itoa(i)+"/start", getHealStartHandler(i))
		http.HandleFunc("/"+strconv.Itoa(i)+"/status", getStatusHandler(i))
	}

	server := &http.Server{
		Addr: ":8080",
	}
	server.ListenAndServe()
}
```

`test` bucket total size <10Gb and consists of <10 objects. 

I started this program on 1st terminal:
```shell
# 1st terminal
$ ./test
```

On 2nd terminal I initiated healing on 0-node and checked status on all nodes:
```shell
# 2nd terminal
$ curl http://localhost:8080/0/start                                                                               [0]
SUCCESS

$ curl http://localhost:8080/0/status                                                                              [0]
SUCCESS

$ curl http://localhost:8080/1/status                                                                              [0]
SUCCESS

$ curl http://localhost:8080/2/status                                                                              [0]
SUCCESS

# 1st terminal
2021/05/03 23:05:58 healStart: {
  "clientToken": "27be195c-4288-47c1-9c21-c74385b008d6@0",
  "clientAddress": "10.0.235.179",
  "startTime": "2021-05-03T16:05:58.412746115Z"
}
2021/05/03 23:05:58 healTaskStatus: {
  "summary": "",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:06:04 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:06:04 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "2021-05-03T16:05:58.412883443Z",
  "settings": {
    "recursive": true,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:06:07 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:06:07 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:06:10 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:06:10 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
```

Now started healing on 0-node three times one after another and checked status on all nodes again in reverse order:
```shell
# 2nd terminal
$ for i in 1 2 3; do curl http://localhost:8080/0/start; done                                                      [0]
SUCCESS
SUCCESS
SUCCESS

$ curl http://localhost:8080/2/status                                                                              [0]
SUCCESS

$ curl http://localhost:8080/1/status                                                                              [0]
SUCCESS

$ curl http://localhost:8080/0/status                                                                              [0]
SUCCESS

# 1st terminal
2021/05/03 23:11:27 healStart: {
  "clientToken": "f3e01a01-fc21-4703-ba53-2aafaa43b309@0",
  "clientAddress": "10.0.235.179",
  "startTime": "2021-05-03T16:11:27.400440014Z"
}
2021/05/03 23:11:27 healTaskStatus: {
  "summary": "",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:11:28 healStart: {
  "clientToken": "6b0a02ba-dfd5-42cb-b010-9a731094a632@0",
  "clientAddress": "10.0.235.179",
  "startTime": "2021-05-03T16:11:27.420592191Z"
}
2021/05/03 23:11:28 healTaskStatus: {
  "summary": "",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:11:29 healStart: {
  "clientToken": "367cffeb-3289-4768-a811-39fa302707f7@0",
  "clientAddress": "10.0.235.179",
  "startTime": "2021-05-03T16:11:28.470658341Z"
}
2021/05/03 23:11:29 healTaskStatus: {
  "summary": "",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:11:32 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:11:32 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:11:36 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:11:36 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:11:40 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:11:40 healTaskStatus: {
  "summary": "running",
  "detail": "",
  "startTime": "2021-05-03T16:11:29.47149258Z",
  "settings": {
    "recursive": true,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
```
As you can see `"summary": "finished"` on 2,1-node and `"summary": "running"` on 0-node.

Then I restarted minio StatefulSet and checked status again:
```shell
# 2nd terminal
$ curl http://localhost:8080/0/status                                                                              [0]
SUCCESS

$ curl http://localhost:8080/1/status                                                                              [0]
SUCCESS

$ curl http://localhost:8080/2/status                                                                              [0]
SUCCESS

# 1st terminal
2021/05/03 23:48:31 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:48:31 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:48:37 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:48:37 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
2021/05/03 23:48:39 healStart: {
  "clientToken": "",
  "clientAddress": "",
  "startTime": "0001-01-01T00:00:00Z"
}
2021/05/03 23:48:39 healTaskStatus: {
  "summary": "finished",
  "detail": "",
  "startTime": "0001-01-01T00:00:00Z",
  "settings": {
    "recursive": false,
    "dryRun": false,
    "remove": false,
    "recreate": false,
    "scanMode": 0
  }
}
```

Now `"summary": "finished"` on all nodes.

## Context

We want to place small persistent storage of some services (Vault eg.) working in k8s to minio cause it is HA. But we discovered one minio "feature": if object was placed to minio cluster when 1 of 3 nodes down then after down node is up again object disappears until autoHeal scheduled. So we planned to write simple AdmissionController for k8s which will execute manual healing for selected buckets automatically on minio pod start. Issue doesn't allow handle when healing finished.

## Regression

Unknown

## Your Environment

`minio/minio:RELEASE.2021-04-22T15-44-28Z` 3 nodes deployed by minio-operator.
Environment: baremetal k8s cluster (`v1.20.4`) with 3 working nodes on `SMP Debian 4.19.181-1 (2021-03-19) x86_64`.
Minio storage: 3x10x16Tb SATA HDD disks, EC: 6.
Network: 10Gbit

**Comment by harshavardhana** [comment]
> We trigger manual healing by API using `github.com/minio/minio/pkg/madmin#Heal()` method with `force=true` argument inside golang app. After calling this method multiple times for same minio node (k8s pod) it always returns `healTaskStatus: {"summary": "running", ...}` even after healing actually done. healTaskStatus request from another minio node (by healing token) returns `healTaskStatus: {"summary": "finished", ...}`. Looks like race conditions issue.

First of all, this is not expected and we don't really want you to use these APIs anymore they are there for legacy purposes.  Also if you do it you do it single-threaded.

> ```go
> func main() {
> 	var err error
> 	for i := 0; i < 3; i++ {
> 		globalContext[i], globalCancel[i] = context.WithCancel(context.Background())
> 		madmClnt[i], err = madmin.New(s3Endpoint[i], s3AccessKey, s3SecretKey, true)
> 		if err != nil {
> 			log.Fatalln(err)
> 		}
> 
> 		http.HandleFunc("/"+strconv.Itoa(i)+"/start", getHealStartHandler(i))
> 		http.HandleFunc("/"+strconv.Itoa(i)+"/status", getStatusHandler(i))
> 	}
> 
> 	server := &http.Server{
> 		Addr: ":8080",
> 	}
> 	server.ListenAndServe()
> }
> ```

and not supposed to run it like this in parallel.

**Comment by ghost** [comment]
@harshavardhana thanks for replay. Actually I do single-threaded and got the same result: always `"summary": "running"` after multiple one after another healing initiation. It is just example above. With it is easier to demonstrate different healing state on different nodes.

> First of all, this is not expected and we don't really want you to use these APIs anymore they are there for legacy purposes.

Can you recommend another way to initiate healing after minio pod start?

**Comment by harshavardhana** [comment]
> Can you recommend another way to initiate healing after minio pod start?

MinIO internally automatically does it @Kirill-Bugaev you shouldn't do it as part of some client API

**Comment by ghost** [comment]
@harshavardhana I know. But as I already described above:
> We want to place small persistent storage of some services (Vault eg.) working in k8s to minio cause it is HA. But we discovered one minio "feature": if object was placed to minio cluster when 1 of 3 nodes down then, after down node is up again, object disappears until autoHeal scheduled. So we planned to write simple AdmissionController for k8s which will execute manual healing for selected buckets automatically on minio pod start.

If I understand correctly autoSelfHeal is not starting immediately after broken node is up again. So those objects which was placed to 2/3-nodes cluster are disappeared until healing propagates them to node which backed to life. At least such behavior I discovered when experimenting with 3-nodes minio cluster. It would be nice If I can trigger healing (automatically) for limited set of buckets  immediately after node backed to life.

**Comment by harshavardhana** [comment]
Will take a look.

**Comment by Zarmi2005** [comment]
I have the same problem, @hackintoshrao do you have any ETA?

**Comment by harshavardhana** [comment]
Will look at this this week - there is no ETA @Zarmi2005

**Comment by harshavardhana** [comment]
> We want to place small persistent storage of some services (Vault eg.) working in k8s to minio cause it is HA. But we discovered one minio "feature": if object was placed to minio cluster when 1 of 3 nodes down then after down node is up again object disappears until autoHeal scheduled. So we planned to write simple AdmissionController for k8s which will execute manual healing for selected buckets automatically on minio pod start. Issue doesn't allow handle when healing finished.

Correct but this is scheduled to be fixed differently by making sure healing is triggered on such areas upon restart. You do not need to do these things. 

> If I understand correctly autoSelfHeal is not starting immediately after broken node is up again. So those objects which was placed to 2/3-nodes cluster are disappeared until healing propagates them to node which backed to life. At least such behavior I discovered when experimenting with 3-nodes minio cluster. It would be nice If I can trigger healing (automatically) for limited set of buckets immediately after node backed to life.

Yes, this is being fixed in the newer healing overhaul, so writing an admission controller is not worth the effort.  A manual way to trigger healing is the legacy approach and we do not recommend that you build an application using this API. It is still kept around since it helps in certain very specific situations in handling dangling objects.

**Comment by harshavardhana** [comment]
```
 mc admin heal -r --remove --scan=deep play/
 ◓  00zero
    0/710,539 objects; 1 GiB in 1h1m54s
    ┌────────┬─────────┬─────────────────────┐
    │ Green  │ 710,775 │ 100.0% ████████████ │
    │ Yellow │       0 │   0.0%              │
    │ Red    │       0 │   0.0%              │
    │ Grey   │       0 │   0.0%              │
    └────────┴─────────┴─────────────────────┘
```

It seems like the manual healing works perfectly fine, and seems to even list and heal properly. Not sure why you were not able to use AFAICS it seems to work fine.
