### ISSUE TITLE
Upload freeze when session token expired during the uploading

### ISSUE THREAD

**Issue by colorzzr** [minio/minio#12215]
Hi all! I am trying to upload a large file through `fput_object` api. I use the temporary session token to serve as credentials. But it caped by my keycloak token(I integrate MinIO with keycloak service) around 5min. The file will require way more than 5min sometimes. I notice if the token expired during the uploading, the process will stop there(the speed drop to 0mb/s) and without any error. I am not sure what is going on underneath. 

Thanks in advance!

## Expected Behavior

The expected behavior might be following two:

- The code can refresh the session token during the upload. But I don't find any native API to refresh the session token.
- Raise the error for the token expire. 

## Current Behavior

Current behavior is that the program just freeze and no error pops up.

## Possible Solution

Possible solution:
Currently, I am trying to refresh the session token by myself during the uploading. I found we can pass in a `Progress()` object to show some uploading progress. And the credentials are stored statically inside the `MinIO` object. I take out the credentials by reference and pass into `Progress()`. During the uploading, `Progress()` will check if token expire and refresh it by calling all the login procedure. I know it is a hacky way.

The token expire time can extend upto 7 days. But my keycloak token expires in 5min(and I cannot change it). There is a walk around. I use the `presigned_put_object` api which is not limited by previous token.

## Steps to Reproduce (for bugs)

1. login with keycloak and get the access token
2. get the session token by `http://minio_endpoint?Action=AssumeRoleWithClientGrants&DurationSeconds=900&Token=%s&Version=2011-06-15` (even if I set duration for 900s, my session token will still expire with my keycloak token -5min)
3. use the temperary `access_token`, `secrete_key` and `sesstion_token` to initialize `Minio` object
4. use `fput` to upload file > 5min.

## Context

I am wondering if there is a native way to refresh the session token. I know the AWS support to refresh the temporary token during the upload. please correct me if I got some misunderstood here. Thanks.

## Regression

Unknown

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-03-12T00-00-47Z`
* Server setup and configuration: `docker run -p 9000:9000 minio/minio server /data`
* Operating System and version (`uname -a`): 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by harshavardhana** [comment]
> Hi all! I am trying to upload a large file through `fput_object` api. I use the temporary session token to serve as credentials. But it caped by my keycloak token(I integrate MinIO with keycloak service) around 5min. The file will require way more than 5min sometimes. I notice if the token expired during the uploading, the process will stop there(the speed drop to 0mb/s) and without any error. I am not sure what is going on underneath.
> 
> Thanks in advance!
> 
> ## Expected Behavior
> The expected behavior might be following two:
> 
> * The code can refresh the session token during the upload. But I don't find any native API to refresh the session token.
> * Raise the error for the token expire.
> 
> ## Current Behavior
> Current behavior is that the program just freeze and no error pops up.
> 
> ## Possible Solution
> Possible solution:
> Currently, I am trying to refresh the session token by myself during the uploading. I found we can pass in a `Progress()` object to show some uploading progress. And the credentials are stored statically inside the `MinIO` object. I take out the credentials by reference and pass into `Progress()`. During the uploading, `Progress()` will check if token expire and refresh it by calling all the login procedure. I know it is a hacky way.
> 
> The token expire time can extend upto 7 days. But my keycloak token expires in 5min(and I cannot change it). There is a walk around. I use the `presigned_put_object` api which is not limited by previous token.
> 
> ## Steps to Reproduce (for bugs)
> 1. login with keycloak and get the access token
> 2. get the session token by `http://minio_endpoint?Action=AssumeRoleWithClientGrants&DurationSeconds=900&Token=%s&Version=2011-06-15` (even if I set duration for 900s, my session token will still expire with my keycloak token -5min)
> 3. use the temperary `access_token`, `secrete_key` and `sesstion_token` to initialize `Minio` object
> 4. use `fput` to upload file > 5min.
> 
> ## Context
> I am wondering if there is a native way to refresh the session token. I know the AWS support to refresh the temporary token during the upload. please correct me if I got some misunderstood here. Thanks.
> 
> ## Regression
> Unknown
> 
> ## Your Environment
> * Version used (`minio --version`): `minio version RELEASE.2021-03-12T00-00-47Z`
> * Server setup and configuration: `docker run -p 9000:9000 minio/minio server /data`
> * Operating System and version (`uname -a`):
> 
> ```
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.2 LTS
> Release:        20.04
> Codename:       focal
> ```

You should use the credentials framework to refresh the tokens internally.

https://github.com/minio/minio-py/blob/master/minio/credentials/providers.py

**Comment by colorzzr** [comment]
Hi @harshavardhana! I try to use the providers but it shows same behaviour. The uploading will freeze if the token expired during that time. For token refresh, can you elaborate more that how to refresh it during the upload? Thanks!

**Comment by harshavardhana** [comment]
> Hi @harshavardhana! I try to use the providers but it shows same behaviour. The uploading will freeze if the token expired during that time. For token refresh, can you elaborate more that how to refresh it during the upload? Thanks!

you need to provide token refreshable functions - @colorzzr i.e if you wish to automate this using Keycloack you need to use the refresh_token to get new fresh id_token - generate new STS creds from the MinIO server.

**Comment by colorzzr** [comment]
> 
> 
> > Hi @harshavardhana! I try to use the providers but it shows same behaviour. The uploading will freeze if the token expired during that time. For token refresh, can you elaborate more that how to refresh it during the upload? Thanks!
> 
> you need to provide token refreshable functions - @colorzzr i.e if you wish to automate this using Keycloack you need to use the refresh_token to get new fresh id_token - generate new STS creds from the MinIO server.

Thanks @harshavardhana ! I am searching for the api which can trigger the token refreshable function. I find `WebIdentityClientGrantsProvider` class support one called `jwt_provider_func` [code](https://github.com/minio/minio-py/blob/master/minio/credentials/providers.py#L505). Do you mean I can place the function here and later it will be called during upload? If my understanding is not correct, can you please point out the correct api for me? Thanks!

**Comment by colorzzr** [comment]
@harshavardhana ^^^. Could you please point me to the API that I can trigger my token refreshable functions? Thanks!
