### ISSUE TITLE
Minio not connecting to aws s3 due to unexpected signature v2/v4 issues

### ISSUE THREAD

**Issue by redturtlepower** [minio/minio#12246]
I am quoting a reply of my last issue, the issue was closed quite fast with no chance to react on my side.
First I tried with backblaze. Does not work, problem seemed to be on minio side. Got closed immediately without further ado. Soo.... I created an aws s3 bucket. Only change to my docker stack setup is the new endpoint command: gateway s3 https://s3.eu-central-1.amazonaws.com. Same error. How are you running minio?

> I am not aware of any settings to change v2/v4 signature behaviour. The error seems to indicate minio is not using v4 signature. Backblaze uses v4 ([source](https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API))

MinIO uses v4 by default in S3 gateway mode - this looks like Backblaze is not compatible with S3 API.  It works fine with AWS S3 in my testing @redturtlepower 

```
~ AWS_PROFILE=s3 minio gateway s3 --address :9001 https://s3.amazonaws.com
Endpoint: http://10.0.0.67:9001  http://172.17.0.1:9001  http://172.18.0.1:9001  http://172.28.0.1:9001  http://127.0.0.1:9001
RootUser: minio
RootPass: minio123

Browser Access:
   http://10.0.0.67:9001  http://172.17.0.1:9001  http://172.18.0.1:9001  http://172.28.0.1:9001  http://127.0.0.1:9001

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set mys3 http://10.0.0.67:9001 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

```
~  mc ls mys3/ | head
[2019-04-03 19:28:07 PDT]     0B aws-glue-scripts-804065449417-us-east-1/
[2019-04-03 19:28:08 PDT]     0B aws-glue-temporary-804065449417-us-east-1/
[2019-03-19 01:21:58 PDT]     0B aws-logs-804065449417-us-east-1/
[2021-04-14 01:04:54 PDT]     0B default-ret/
[2021-03-05 16:18:58 PST]     0B donatello-us-east-2/
[2020-07-07 11:21:05 PDT]     0B ecoilm/
[2019-03-11 14:53:41 PDT]     0B ersan/
[2021-04-23 03:11:31 PDT]     0B erslock/
[2020-01-21 15:11:10 PST]     0B harshavardhana/
[2019-11-09 12:43:48 PST]     0B kannappan300/
```

_Originally posted by @harshavardhana in https://github.com/minio/minio/issues/12245#issuecomment-833888508_

**Comment by harshavardhana** [comment]
Please post your queries if present back in #12245

**Comment by redturtlepower** [comment]
Well I have but no one looks at closed issues, right? I made a comment that is worth to look at. Can you reopen that issue?
