### ISSUE TITLE
Delay in uploading files in k8s environment

### ISSUE THREAD

**Issue by jump2005** [minio/minio#12247]
## Expected Behavior

One node crash does not block the upload of files.

## Current Behavior

Distributed mode deployment of Minio in k8s environment.
One node crash will delay about 1-3 minutes when uploading files.

## Steps to Reproduce (for bugs)

1.In k8s useing 4 pods for minio server, anti affinity deployment.
2.One of the nodes crash, use mc upload file to bucket.
3.Upload action blocked, need to wait 1-3 minutes before you can continue to upload.
4.The upload will succeed, but it will block for a while.

## Context

This problem will cause my application to delay because the upload will block and affect performance
1.Why?
2.How to fix.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-03-04T00-53-13Z
* Server setup and configuration: Distributed deployment of 4 pods in k8s
* Operating System and version (`uname -a`): Linux 4.4.223-1.el7.elrepo.x86_64 #.... GUN/Linux

**Comment by harshavardhana** [comment]
> ## Expected Behavior
> One node crash does not block the upload of files.
> 
> ## Current Behavior
> Distributed mode deployment of Minio in k8s environment.
> One node crash will delay about 1-3 minutes when uploading files.
> 
> ## Possible Solution
> ## Steps to Reproduce (for bugs)
> 1.In k8s useing 4 pods for minio server, anti affinity deployment.
> 2.One of the nodes crash, use mc upload file to bucket.
> 3.Upload action blocked, need to wait 1-3 minutes before you can continue to upload.
> 4.The upload will succeed, but it will block for a while.
> 
> ## Context
> This problem will cause my application to delay because the upload will block and affect performance
> 1.Why?
> 2.How to fix.
> 
> ## Regression
> ## Your Environment
> * Version used (`minio --version`): RELEASE.2021-03-04T00-53-13Z
> * Server setup and configuration: Distributed deployment of 4 pods in k8s
> * Operating System and version (`uname -a`): Linux 4.4.223-1.el7.elrepo.x86_64 #.... GUN/Linux

Pod crash shouldn't lead to such delays, but first request that detects the issue needs to timeout.

We also need to have another timeout. So it is expected that some in-flight requests take time but not all.

Also please latest release and let us know...

**Comment by jump2005** [comment]
> 
> 
> > ## Expected Behavior
> > One node crash does not block the upload of files.
> > ## Current Behavior
> > Distributed mode deployment of Minio in k8s environment.
> > One node crash will delay about 1-3 minutes when uploading files.
> > ## Possible Solution
> > ## Steps to Reproduce (for bugs)
> > 1.In k8s useing 4 pods for minio server, anti affinity deployment.
> > 2.One of the nodes crash, use mc upload file to bucket.
> > 3.Upload action blocked, need to wait 1-3 minutes before you can continue to upload.
> > 4.The upload will succeed, but it will block for a while.
> > ## Context
> > This problem will cause my application to delay because the upload will block and affect performance
> > 1.Why?
> > 2.How to fix.
> > ## Regression
> > ## Your Environment
> > 
> > * Version used (`minio --version`): RELEASE.2021-03-04T00-53-13Z
> > * Server setup and configuration: Distributed deployment of 4 pods in k8s
> > * Operating System and version (`uname -a`): Linux 4.4.223-1.el7.elrepo.x86_64 #.... GUN/Linux
> 
> Pod crash shouldn't lead to such delays, but first request that detects the issue needs to timeout.
> 
> We also need to have another timeout. So it is expected that some in-flight requests take time but not all.
> 
> Also please latest release and let us know...

yes, harshavardhana
I read the code that is a flag to mark down. The first time should be tcp retry time? or minio server handler?

**Comment by harshavardhana** [comment]
> yes, harshavardhana
I read the code that is a flag to mark down. The first time should be tcp retry time? or minio server handler?

Correct its tcp timeout there is nothing that can be done about in-flight requests. Only after a timeout requests become fast. 

This expected tolerance is always necessary. If you configured ClusterIP crashed pods are moved to terminating stage by k8s in 30s after which the routing makes sure correct node sees the request.

These are sane values you have to build application around it.. there is no instantaneous failover available in http API. You retry the calls that fail..

Of course once the timeout had reached all calls should mark the node as down and never talk to it further. Until it comes online.

Going to close this issue since this is working as expected.
