### ISSUE TITLE
MinIO Caching : Error: io: read/write on closed pipe for API getObject

### ISSUE THREAD

**Issue by guptajiten** [minio/minio#12249]
I have recently started using minio caching with azure gateway. I have been hitting error as specified below with getObject API call with fairly high load.

```
API: GetObject(bucket=**, object=**)
Time: 17:38:06 UTC 05/04/2021
DeploymentID: 19813cf3-9717-44d8-82dc-1b7168a5b532
RequestID: 167BEDBCD2F59B0B
RemoteHost: **
Host: minio:9000
UserAgent: MinIO (linux; x64) minio-js/7.0.18
Error: io: read/write on closed pipe (*errors.errorString)
       4: cmd/api-errors.go:2003:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2028:cmd.toAPIError()
       2: cmd/object-handlers.go:481:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

## Expected Behavior
getObject API should not return error

## Current Behavior
Almost 20% of request results in error to client

## Possible Solution
Not known. Worst case I would avoid using minio caching and have just application caching.

## Steps to Reproduce (for bugs)
1. Enable minio caching with below environment variables
            - name: MINIO_CACHE
              value: "on"
            - name: MINIO_CACHE_DRIVES
              value: "/mnt/cache"
            - name: MINIO_CACHE_EXCLUDE
              value: ""
            - name: MINIO_CACHE_QUOTA
              value: 99
            - name: MINIO_CACHE_AFTER
              value: 3
            - name: MINIO_CACHE_WATERMARK_LOW
              value: 90
            - name: MINIO_CACHE_WATERMARK_HIGH
              value: 95
2. Send getObject requests (~20k requests(get+put) per minute distributed over 8 minio process) and observe failures

## Context
I am trying to enable MinIO caching with Azure Gateway with k8s env.

## Regression
No

## Your Environment
MinIO Image: RELEASE.2021-04-22T15-44-28Z

**Comment by poornas** [comment]
@jlohiya, are these 8 minio processes sharing the same cache drives on disk? What % of your cache is utilized here

**Comment by guptajiten** [comment]
@poornas Thanks for looking into it. Those 8 pods are distributed on different nodes. I see these errors on pod which is completely isolated. I see max ~20% disk cache usage.

**Comment by guptajiten** [comment]
@poornas Also when I disable caching I don't get a single error so something going wrong only when caching is enabled.

**Comment by poornas** [comment]
I was not able to repro this on a standalone setup - what is your client here? Noticed that your MINIO_CACHE_AFTER setting is 3, for the object reporting this error of read/write on closed pipe - is it in fact cached. 
The cached directory name can be found with the command below - replace with actual bucket and object name.
 `➜ echo -n  "bucket/object"  | openssl dgst  -sha256 `

**Comment by guptajiten** [comment]
@poornas We are using minio-js client in k8s environment: 

UserAgent: MinIO (linux; x64) minio-js/7.0.18

We did functional testing with caching enabled and it worked fine but when we moved to load test we see these errors increasing gradually over time.

I can confirm from caching metrics (cache_hits_total) and in directory that data is cached as per config.

**Comment by harshavardhana** [comment]
This may be a potential fix https://github.com/minio/minio/pull/12264

**Comment by guptajiten** [comment]
@harshavardhana Thanks!
will the changes gonna make to official docker image release soon? 

I will pull the latest image and will verify the fix.

**Comment by harshavardhana** [comment]
> This may be a potential fix #12264

Closing this as fixed in #12264

**Comment by guptajiten** [comment]
@harshavardhana  I still see the issue, sorry to say that it is not fixed by "RELEASE.2021-05-11T23-27-41Z" which includes (#12264 ).

**Comment by harshavardhana** [comment]
> @harshavardhana I still see the issue, sorry to say that it is not fixed by "RELEASE.2021-05-11T23-27-41Z" which includes (#12264 ).

I don't think we are able to reproduce it, it was a theoretical fix that was needed anyways. Since we cannot reproduce it I don't think we can move anywhere. 

Unless you can tell us precisely how to reproduce and provide us the client-side code as well to go along with it. It would be helpful. 

If this is just an error message on the screen and there is nothing unusual about the usage or fetching data then you can ignore this error.

**Comment by guptajiten** [comment]
> > @harshavardhana I still see the issue, sorry to say that it is not fixed by "RELEASE.2021-05-11T23-27-41Z" which includes (#12264 ).
> 
> I don't think we are able to reproduce it, it was a theoretical fix that was needed anyways. Since we cannot reproduce it I don't think we can move anywhere.
> 
> Unless you can tell us precisely how to reproduce and provide us the client-side code as well to go along with it. It would be helpful.
> 
> If this is just an error message on the screen and there is nothing unusual about the usage or fetching data then you can ignore this error.

minio-js client gets the internal error and its while calling getObject API so we dont think if it can be ignored.

We are using minio in kubernetes environment with Azure Gateway. We are sending around ~20k request per minute (~10k getObject + ~10k putObject)

would that be helpful?

**Comment by harshavardhana** [comment]
> We are using minio in kubernetes environment with Azure Gateway. We are sending around ~20k request per minute (~10k getObject + ~10k putObject)

Please share the code and the deployment style as well? - how many instances of the azure gateway are running?

**Comment by guptajiten** [comment]
> Please share the code and the deployment style as well? - how many instances of the azure gateway are running?

We are deploying using helm and with kubernetes: v1.19.9

```
azuregateway:
  enabled: true
  replicas: 8
```
