### ISSUE TITLE
MinIO UI OIDC with ADFS

### ISSUE THREAD

**Issue by bruno-villa** [minio/minio#12266]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is that the MinIO UI has a slight incompatibility with ADFS if one wants to use user groups to match user tokens to policies. The UI uses the implicit flow and requests an id_token but the token returned by ADFS is limited to the standard claims. The contents of the token can be extended to include e.g. groups the user belongs to ([ADFS docs](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts#customize-id-token-additional-claims-in-id-token)). However, there is a limitation in that ADFS only returns the extended token via POST and not via URL parameters. As mentioned in the linked docs, the token request must specify `response_mode=form_post`. 

**Describe the solution you'd like**
It'd be ideal to be able to specify the response mode as an optional setting (e.g. `MINIO_IDENTITY_OPENID_RESPONSE_MODE`), MinIO would have to retrieve the token from the form body rather than the parameters if this setting was set to `form_post`. 

**Describe alternatives you've considered**
The principal alternative would be using a different S3 client. 

**Additional context**
Tested using `minio/minio:RELEASE.2020-12-03T05-49-24Z`. The latest release seems to include a major refactor but I do not see relevant changes to the STS. 
The limitation is specific to ADFS. Other identity providers work with the default response mode.

**Comment by harshavardhana** [comment]
> The problem is that the MinIO UI has a slight incompatibility with ADFS if one wants to use user groups to match user tokens to policies.

MinIO UI is going to be deprecated and removed in future releases we are moving to https://github.com/minio/console - please test with this and let us know - if it doesn't feel free to open a feature request based on this issue. 

Closing this issue here since its not relevant and we are not planning to extend the current UI anymore.
