### ISSUE TITLE
Slow PutObject performance on API access

### ISSUE THREAD

**Issue by alatas** [minio/minio#12268]
We have a database filled with regular files. We installed a four-instance MinIO cluster to transfer these files. At the beginning of the migration process, I developed an individual migration tool running on a client computer that stands between DB and MinIO. This tool gathers the file as a byte stream from the DB with its metadata. It buffers the file stream to the client computer's memory. Then transfers it to the MinIO with the AWS S3 SDK. The schema of the pipeline is like `DB <--> Client --> MinIO`

In the first 3GB of the transfer, we can only get an average of 1.0 MB/sec transfer rate, which is not acceptable. Then we investigate the possible bottlenecks. First, we tested the DB-Client connection. The client tool can gather the files from the DB at an average of 15 - 20MB/sec rate when writing these files into the client computer's hard disk. 

Then we transfer these sample files from the client computer to one of the MinIO servers in the cluster via SFTP with an average rate of 15MB/sec. I also tested the hard disks and the network with different tools. The disks and the network prove that they can handle more than 100MB/sec. These experiments mean the network and the disks are not the sources of our problem.

Then we changed the client SDK from AWS S3 SDK to official MinIO DotnetSDK. The rate is dropped from 1.0 MB/sec to 850KB/sec. After that, we used the `mc` client tool to send the gathered sample files from the client computer to MinIO. And the rate is raised to 12 - 13 MB/sec, which is acceptable according to the transfer rate from the DB.

So, I think a bug in the MinIO API endpoint causes much worse transfer rates compared to our tool developed with AWS SDK and official SDK to the `mc` client tool.

I didn't write this issue to the minio dotnet-sdk repo because we used also AWS SDK and the behavior didn't change very much. I think this is not related to the SDK.

## Expected Behavior
The SDK and the mc tool offer similar transfer rates to the same MinIO cluster.

## Current Behavior
mc client tool can put objects nearly 10x faster than the SDKs.

## Possible Solution
To use mc client tool to transfer files.

## Steps to Reproduce (for bugs)
1. Create a simple tool with the SDK that put objects to the MinIO, 
2. Measure the transfer rate.
3. Put these files with the `mc cp` command. And measure the transfer rate again

## Context
The MSSQL DB has files in very different sizes, from 1 KB to 10MB.

## Your Environment
* minio version RELEASE.2021-04-22T15-44-28Z
* 4 servers with 8 cores and 12GB of memory each.
* There are 32 disks total with 900GB each. EC:4 parity.
* Servers are connected with the same switch on a 1Gb network.
* Ubuntu 20.04

**Comment by klauspost** [comment]
In general this is orders of magnitude slower than what you would expect from a setup like this.

There is no "magic salt" in what mc does, but it will do things like concurrent multipart uploads for instance. You are welcome to take a look and mimic that behavior for your own system. You can benchmark your system with our [warp tool](https://github.com/minio/warp)

You are welcome to ask on [community slack](https://slack.min.io/) to see if others have experience with this. We offer assistance in setting up your cluster as part of our [Subscription Services](https://min.io/pricing). Write to `hello@minio.io` to get in touch with us if you need more information.

**Comment by alatas** [comment]
@klauspost Thanks for the reply. 
I looked at the source of mc. I saw parallelism and applied it to my tool with AWS S3 SDK. Now I can get 6 - 7MB/sec.

Then I made a bunch of PUT tests with the warp tool. According to the results, It is clear that the transfer rate is very bonded with the object size. When I test with objects with sizes of 10MB, I get 50MB/sec. On the other hand, I get 0.2MB/sec when I test with 10KB objects.

The transfer rate is dropping very significantly when the object sizes are smaller. I think this is closely related to the overhead and my setup.

**Comment by meotimdihia** [comment]
@alatas: How did you do that with AWS S3 SDK? Could you say more details about this 😀?

**Comment by alatas** [comment]
> @alatas: How did you do that with AWS S3 SDK? Could you say more details about this 😀?

I changed the single thread copy method to a parallel one. I am using 20 - 25 threads, copying different files at the same time. The number of threads is changing due to file size.
