### ISSUE TITLE
Policy createTimestamp and modifyTimestamp

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#12261]
**Is your feature request related to a problem? Please describe.**
please consider adding timestamps for creation and modify on policy

**Comment by harshavardhana** [comment]
Can you provide AWS specification for this ?

**Comment by fdefilippo** [comment]
https://docs.aws.amazon.com/cli/latest/reference/iam/create-policy.html

**Comment by harshavardhana** [comment]
Yes but we do not support IAM APIs @fdefilippo this is out of our scope.

**Comment by fdefilippo** [comment]
ok but it would be enough to add to the json the values:

[{"name":"test","body":"","cidr":null,"createdBy":"principalId","createTimestamp:"YYYY-MM-DD HH:MM:SS","modifiedBy":"principalId","modifytimestamp":"YYYY-MM-DD HH:MM:SS"}]

**Comment by harshavardhana** [comment]
@vadmeste looking at the value of `policy.json` metadata will work here that captures the `ModTime` so was thinking that this can be easily supported.

We can also add `createTimeStamp` as part of the `x-amz-meta-<createTimeStamp` for IAM objects.

**Comment by vadmeste** [comment]
@harshavardhana I am not sure which API this is intended for, adding canned policies in admin API ? This is clearly out of scope here

**Comment by harshavardhana** [comment]
The output has now changed in `mc` it provides `CreateDate` and `UpdateDate` latest MinIO and `mc` releases.
