### ISSUE TITLE
[Feature request] AccountInfo - Caching system

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#12278]
**Is your feature request related to a problem? Please describe.**

I have a federation: etcd on aws and baremetal storage.

I fetch all my users' infos every x minutes to get their latest storage usage. The problem is that since https://github.com/minio/minio/pull/11484/files from `RELEASE.2021-02-11T08-23-43Z` MinIO lists all buckets from etcd for `madmin.AccountInfo` and my EC2 ELB bills have 10x.

**Describe the solution you'd like**
1. Caching system for buckets
2. `madmin.AccountInfo` requests ALL buckets, can we just fetch the user's buckets instead?

Thanks.

**Comment by harshavardhana** [comment]
First of all you should really stop using federation on AWS and top of that avoid etcd running on AWS.

- caching of buckets is not possible, there is no well defined way to do such things
- there is no way to avoid listing of buckets there is no explicit owner for a bucket

Also remember we are removing support for federation in future releases. If you are willing to stick to this as architecture then you won't be able to upgrade.

Note: AccountInfo API is never called every so minutes so it must be your application that is doing AccountInfo all the time.

**Comment by harshavardhana** [comment]
Closing this as this doesn't makes sense for us. There is no way to cache AccountInfo here..

**Comment by ToLToL** [comment]
@harshavardhana 

We really need federation for our use case and it's a pity that MinIO will remove support for it.
What are the reasons for this decision ?

**Comment by harshavardhana** [comment]
> @harshavardhana
> 
> We really need federation for our use case and it's a pity that MinIO will remove support it.
> What are the reasons for this decision ?

The main reason is the complexities involved in deployment, all the newer features cannot be made aware of the federation.  We like to keep our code simple as much as possible - and periodically remove unnecessary features.
