### ISSUE TITLE
Minio UI "Server returned error [504]" - Timeout

### ISSUE THREAD

**Issue by teplydat** [minio/minio#12270]
## Current Behavior
We use minio on a k8s with ambassador as an ingress that has a default timeout of 30s.
If an action needs more than 30s (e.g. deleting a lot of folders and files) there comes an error message "Server returned error [504]" in the UI. (Btw: the action(/deletion) is fully done after a while but the error in the UI is not nice).
This behavior does not happen with cli tools!

Of course we could increase the timeout of the ingress but it does not make sense to increase endless.

## Expected Behavior
Longer actions in minio UI should not be interfered by an ingress/proxy timeout.

**Comment by harshavardhana** [comment]
If you need more performance you should have better hardware, keeping 30secs value and expecting all operations to complete with in that time limit is useless.

You should either use a more responsive hardware or increase the timeout value for UI. 30s is not useful to do anything useful for large streams and large steam of I/O from the UI.

Also MinIO browser UI is getting deprecated and removed we are moving fully to https://github.com/minio/console please start using that instead.
