### ISSUE TITLE
mc admin config reset myMinIO notify_webhook fails to remove key 

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#12272]
When running mc admin config reset myMinIO notify_webhook to remove a stale config fails to remove the key after running mc admin service restart myminio

## Expected Behavior
When running mc admin config reset myMinIO notify_webhook I would expect the key to be removed after running mc admin service restart myminio

## Current Behavior
The key fails to get removed. 

## Steps to Reproduce (for bugs)
1. Add a key to notify_webhook (mc admin config set myMinIO notify_webhook
2. run mc admin config reset myMinIO notify_webhook
3. run mc admin service restart myminio
4. run mc admin config get myMinIO notify_webhook the same keys will be there. 

## Context
Key is no long valid and need to add a new valid config. 

## Regression
Unsure

## Your Environment

* Version used (`minio --version`): 2021-04-22T15:44:28Z
* Server setup and configuration: Dev system. 3 Nodes 
* Operating System and version (`uname -a`): Ubuntu 18

**Comment by harshavardhana** [comment]
> * Add a key to notify_webhook (mc admin config set myMinIO notify_webhook
> * run mc admin config reset myMinIO notify_webhook
> * run mc admin service restart myminio
> * run mc admin config get myMinIO notify_webhook the same keys will be there.

Here is what I tried 

```
~ mc admin config set myminio/ notify_webhook endpoint=https://webhook.site/32100cbc-187f-40a3-a490-09dc17e7cb24
Successfully applied new settings.
Please restart your server 'mc admin service restart myminio/'.
~ mc admin service restart myminio/
~ mc admin config get myminio/ notify_webhook
notify_webhook endpoint=https://webhook.site/32100cbc-187f-40a3-a490-09dc17e7cb24 auth_token= queue_limit=0 queue_dir= client_cert= client_key=
~ mc admin config reset myminio/ notify_webhook
Key is successfully reset.
Please restart your server with `mc admin service restart myminio/`.
~ mc admin service restart myminio/
~ mc admin config get myminio/ notify_webhook
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
```

So it seems like it's working fine, AFAICS make sure that you have restarted the service after `reset` if not `mc admin config get` will return an in-memory copy - so it is expected that you restart the service. 

Closing this issue as not reproducible. 

> * Version used (`minio --version`): 2021-04-22T15:44:28Z

Even with this version.

**Comment by harshavardhana** [comment]
Please share if there is any other log information,  etc. from what it looks like you might have missed a restart or the restart didn't succeed on all the nodes.

**Comment by zapto2600** [comment]
What logs would be helpful? I cannot find anything that references the webhook from the logs I have checked. This is my process 


Redacted@Redacted ~ % mc admin config get my-minio/ notify_webhook
notify_webhook endpoint=REDACTED_URL auth_token=REDACTED queue_limit=0 queue_dir= client_cert= client_key=
notify_webhook:splunk endpoint=REDACTED_URL auth_token=REDACTED queue_limit=0 queue_dir= client_cert= client_key=

Redacted@Redacted ~ %  mc admin config reset nvme-testing notify_webhook
Key is successfully reset.
Please restart your server with `mc admin service restart my-minio/.

Redacted@Redacted ~ % mc admin service restart my-minio/
Restart command successfully sent to `my-minio/`.

Restarted `my-minio/` successfully.
Redacted@Redacted ~ %  mc admin config get nvme-testing notify_webhook
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
notify_webhook:splunk endpoint=REDACTED_URL auth_token=REDACTED queue_limit=0 queue_dir= client_cert= client_key=

Redacted@Redacted ~ %

**Comment by harshavardhana** [comment]
> Redacted@Redacted ~ % mc admin config reset nvme-testing notify_webhook

The reset here is only invoked for the default target if you wish to reset your `:splunk`  then you need to provide

```
mc admin config reset nvme-testing notify_webhook:splunk
```

Check the examples `mc admin config reset -h` 

```
  1. Reset MQTT notifcation target 'name1' settings to default values.
     $ mc admin config reset myminio/ notify_mqtt:name1
```
