### ISSUE TITLE
Invalid key length issue when enable sse-s3

### ISSUE THREAD

**Issue by wufengzlw** [minio/minio#12289]
Follow instruction:
https://github.com/minio/minio/blob/master/docs/kms/README.md

Requirement:
Enable SSE for minio with KES and Vault

## Expected Behavior

After enable sse-s3 for a bucket, I can upload files to the bucket, and SSE is working

## Current Behavior

Can not upload file to a bucket enabled SSE-S3, get this error:
API: SYSTEM()
Time: 15:07:45 UTC 05/13/2021
DeploymentID: 6d2b3c01-03b1-4186-a591-79902b1f88a5
Error: crypto: invalid key length (*errors.errorString)
       6: cmd/logger/logger.go:394:logger.CriticalIf()
       5: cmd/crypto/key.go:48:crypto.GenerateKey()
       4: cmd/encryption-v1.go:249:cmd.newEncryptMetadata()
       3: cmd/encryption-v1.go:264:cmd.newEncryptReader()
       2: cmd/encryption-v1.go:331:cmd.EncryptRequest()
       1: cmd/web-handlers.go:1279:cmd.(*webAPIHandlers).Upload()

## Steps to Reproduce (for bugs)

1. minio <--> kes config:
https://github.com/minio/kes/wiki/MinIO-Object-Storage
2. kes <--> vault config:
https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore#kes-server-setup
3. Create key in KES and store it in Vault: (wokring)
export KES_SERVER=https://x.x.x.x:7373
export KES_CLIENT_CERT=minio.cert
export KES_CLIENT_KEY=minio.key
kes key create -k my-minio-key
4. Check key in vault:
lzhao@ubuntu:~$ vault list kv
Keys
my-minio-key
5. Enable sse-s3 for the bucket:
lzhao@ubuntu:$ mc encrypt set sse-s3 minio/ccc
Auto encryption configuration has been set successfully for minio/ccc
lzhao@ubuntu:$ mc encrypt info minio/ccc
Auto encryption 'sse-s3' is enabled

6. When I upload file to bucket "ccc", there is an error from minio docker:
API: SYSTEM()
Time: 15:07:45 UTC 05/13/2021
DeploymentID: 6d2b3c01-03b1-4186-a591-79902b1f88a5
Error: crypto: invalid key length (*errors.errorString)
       6: cmd/logger/logger.go:394:logger.CriticalIf()
       5: cmd/crypto/key.go:48:crypto.GenerateKey()
       4: cmd/encryption-v1.go:249:cmd.newEncryptMetadata()
       3: cmd/encryption-v1.go:264:cmd.newEncryptReader()
       2: cmd/encryption-v1.go:331:cmd.EncryptRequest()
       1: cmd/web-handlers.go:1279:cmd.(*webAPIHandlers).Upload()

## Your Environment

* Version used (`minio --version`):
latest version of "minio/minio" docker
* Server setup and configuration:
1. minio <--> kes config:
https://github.com/minio/kes/wiki/MinIO-Object-Storage
2. kes <--> vault config:
https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore#kes-server-setup
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
You didn't share how you enabled the MinIO variables for MinIO to talk to Kes @wufengzlw

**Comment by harshavardhana** [comment]
> You didn't share how you enabled the MinIO variables for MinIO to talk to Kes @wufengzlw

Are you also using vault v2 backend by any chance?

**Comment by jakeblatchford** [comment]
Experiencing the same issue when using KES backend (https://docs.min.io/docs/minio-kms-quickstart-guide.html) on version `RELEASE.2021-05-11T23-27-41Z`. Issue was not present in `RELEASE.2021-04-22T15-44-28Z`

Start command:
```minio server --address ":9100" /opt/minio```

Env:
```
MINIO_KMS_KES_CA_PATH='/opt/kes/server.cert'
MINIO_KMS_KES_CERT_FILE='/opt/kes/minio.cert'
MINIO_KMS_KES_ENDPOINT='https://127.0.0.1:7373'
MINIO_KMS_KES_KEY_FILE='/opt/kes/minio.key'
MINIO_KMS_KES_KEY_NAME='my-minio-key
```

```API: SYSTEM()
Time: 15:21:35 UTC 05/13/2021
DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
Error: Unable to initialize config, some features may be missing crypto/aes: invalid key size 0 (*fmt.wrapError)
       3: cmd/server-main.go:390:cmd.initAllSubsystems()
       2: cmd/server-main.go:321:cmd.initServer()
       1: cmd/server-main.go:535:cmd.serverMain()
Endpoint: http://10.0.2.15:9100  http://10.210.12.13:9100  http://127.0.0.1:9100       

Browser Access:
   http://10.0.2.15:9100  http://10.210.12.13:9100  http://127.0.0.1:9100      

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: SYSTEM()
Time: 15:21:35 UTC 05/13/2021
DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
Error: crypto/aes: invalid key size 0 (aes.KeySizeError)
       4: cmd/iam-object-store.go:198:cmd.(*IAMObjectStore).migrateToV1()
       3: cmd/iam-object-store.go:206:cmd.(*IAMObjectStore).migrateBackendFormat()
       2: cmd/iam.go:430:cmd.(*IAMSys).doIAMConfigMigration()
       1: cmd/iam.go:625:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 15:21:35 UTC 05/13/2021
DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
Error: Unable to migrate IAM users and policies to new format: crypto/aes: invalid key size 0 (*fmt.wrapError)
       1: cmd/iam.go:631:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 15:21:35 UTC 05/13/2021
DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:632:cmd.(*IAMSys).Init()
Exiting on signal: TERMINATED
```

**Comment by harshavardhana** [comment]
@aead ^^

**Comment by wufengzlw** [comment]
@harshavardhana 
this is the config in minio for kes connection:
"kes.vre" is a DNS name redirect traffic to kes pod in kubernetes
the others are follow the instruction from here:
https://github.com/minio/kes/wiki/MinIO-Object-Storage

        - name: MINIO_KMS_KES_ENDPOINT
          value: "https://kes.vre:7373" 
        - name: MINIO_KMS_KES_KEY_FILE
          value: "/var/lib/docker/minio.key"
        - name: MINIO_KMS_KES_CERT_FILE
          value: "/var/lib/docker/minio.cert"
        - name: MINIO_KMS_KES_CA_PATH
          value: "/var/lib/docker/server.cert"
        - name: MINIO_KMS_KES_KEY_NAME
          value: "my-minio-key"

And I'm using vault V1 by this setting:
vault secrets enable -version=1 kv

instruction from here:
https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore#kes-server-setup

**Comment by harshavardhana** [comment]
> 6\. When I upload file to bucket "ccc", there is an error from minio docker:
>     API: SYSTEM()
>     Time: 15:07:45 UTC 05/13/2021
>     DeploymentID: 6d2b3c01-03b1-4186-a591-79902b1f88a5
>     Error: crypto: invalid key length (*errors.errorString)
>     6: cmd/logger/logger.go:394:logger.CriticalIf()
>     5: cmd/crypto/key.go:48:crypto.GenerateKey()
>     4: cmd/encryption-v1.go:249:cmd.newEncryptMetadata()
>     3: cmd/encryption-v1.go:264:cmd.newEncryptReader()
>     2: cmd/encryption-v1.go:331:cmd.EncryptRequest()
>     1: cmd/web-handlers.go:1279:cmd.(*webAPIHandlers).Upload()

Looks like key generate has failed here a fix for that is here to see the actual error #12290

**Comment by aead** [comment]
@wufengzlw You can try to run a `kes log trace` while you start the MinIO server and while uploading an object.
This will show why the `GenerateKey` calls fail - from the perspective of KES.

**Comment by harshavardhana** [comment]
> Experiencing the same issue when using KES backend (https://docs.min.io/docs/minio-kms-quickstart-guide.html) on version `RELEASE.2021-05-11T23-27-41Z`. Issue was not present in `RELEASE.2021-04-22T15-44-28Z`
> 
> Start command:
> `minio server --address ":9100" /opt/minio`
> 
> Env:
> 
> ```
> MINIO_KMS_KES_CA_PATH='/opt/kes/server.cert'
> MINIO_KMS_KES_CERT_FILE='/opt/kes/minio.cert'
> MINIO_KMS_KES_ENDPOINT='https://127.0.0.1:7373'
> MINIO_KMS_KES_KEY_FILE='/opt/kes/minio.key'
> MINIO_KMS_KES_KEY_NAME='my-minio-key
> ```
> 
> ```
> Time: 15:21:35 UTC 05/13/2021
> DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
> Error: Unable to initialize config, some features may be missing crypto/aes: invalid key size 0 (*fmt.wrapError)
>        3: cmd/server-main.go:390:cmd.initAllSubsystems()
>        2: cmd/server-main.go:321:cmd.initServer()
>        1: cmd/server-main.go:535:cmd.serverMain()
> Endpoint: http://10.0.2.15:9100  http://10.210.12.13:9100  http://127.0.0.1:9100       
> 
> Browser Access:
>    http://10.0.2.15:9100  http://10.210.12.13:9100  http://127.0.0.1:9100      
> 
> Object API (Amazon S3 compatible):
>    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.min.io/docs/java-client-quickstart-guide
>    Python:     https://docs.min.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
> 
> API: SYSTEM()
> Time: 15:21:35 UTC 05/13/2021
> DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
> Error: crypto/aes: invalid key size 0 (aes.KeySizeError)
>        4: cmd/iam-object-store.go:198:cmd.(*IAMObjectStore).migrateToV1()
>        3: cmd/iam-object-store.go:206:cmd.(*IAMObjectStore).migrateBackendFormat()
>        2: cmd/iam.go:430:cmd.(*IAMSys).doIAMConfigMigration()
>        1: cmd/iam.go:625:cmd.(*IAMSys).Init()
> 
> API: SYSTEM()
> Time: 15:21:35 UTC 05/13/2021
> DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
> Error: Unable to migrate IAM users and policies to new format: crypto/aes: invalid key size 0 (*fmt.wrapError)
>        1: cmd/iam.go:631:cmd.(*IAMSys).Init()
> 
> API: SYSTEM()
> Time: 15:21:35 UTC 05/13/2021
> DeploymentID: f43dc778-0953-4b3c-89c9-3410f6e5cbf3
> Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
>        1: cmd/iam.go:632:cmd.(*IAMSys).Init()
> Exiting on signal: TERMINATED
> ```

Dud you configure kes while upgrading? or did you enable KES in previous release? @jakeblatchford

**Comment by wufengzlw** [comment]
@harshavardhana 

with minio:RELEASE.2021-04-22T15-44-28Z

it's working

**Comment by harshavardhana** [comment]
> @harshavardhana
> 
> with minio:RELEASE.2021-04-22T15-44-28Z
> 
> it's working

@wufengzlw can you do kes log trace for us with the upgrade to 05-11 ?

**Comment by wufengzlw** [comment]
@harshavardhana 

Our developers are testing with this version, I can not change version of Minio for now

**Comment by harshavardhana** [comment]
I actually tried upgrading from 04-22 and do not see any issues at all followed the exact steps to setup vault etc. Upgrades were tested starting from 01 release to latest. 

```
MINIO_KMS_KES_CAPATH=/home/harsha/vault/server.cert 
MINIO_KMS_KES_CERT_FILE=/home/harsha/vault/app.cert 
MINIO_KMS_KES_KEY_FILE=/home/harsha/vault/app.key 
MINIO_KMS_KES_ENDPOINT=https://127.0.0.1:7373 
MINIO_KMS_KES_KEY_NAME=my-app-key 
./minio server /tmp/dist-xl{1...4}
Verifying if 1 bucket is consistent across drives...
Status:         4 Online, 0 Offline.
Endpoint: http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
RootUser: minio
RootPass: minio123

Browser Access:
   http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
IAM initialization complete
```

**Comment by harshavardhana** [comment]
> I actually tried upgrading from 04-22 and do not see any issues at all followed the exact steps to setup vault etc. Upgrades were tested starting from 01 release to latest. 
> 
> ```
> MINIO_KMS_KES_CAPATH=/home/harsha/vault/server.cert 
> MINIO_KMS_KES_CERT_FILE=/home/harsha/vault/app.cert 
> MINIO_KMS_KES_KEY_FILE=/home/harsha/vault/app.key 
> MINIO_KMS_KES_ENDPOINT=https://127.0.0.1:7373 
> MINIO_KMS_KES_KEY_NAME=my-app-key 
> ./minio server /tmp/dist-xl{1...4}
> Verifying if 1 bucket is consistent across drives...
> Status:         4 Online, 0 Offline.
> Endpoint: http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
> RootUser: minio
> RootPass: minio123
> 
> Browser Access:
>    http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
> 
> Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
>    $ mc alias set myminio http://10.0.0.67:9000 minio minio123
> 
> Object API (Amazon S3 compatible):
>    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.min.io/docs/java-client-quickstart-guide
>    Python:     https://docs.min.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
> IAM initialization complete
> ```

I guess there is some issue and misconfiguration in your current KES that is missing after upgrade.

We shall make a new release today which should help show you the exact error that was unfortunately hidden.
