### ISSUE TITLE
Minio 5-11 broke AD group auth for Console

### ISSUE THREAD

**Issue by tkg61** [minio/minio#12282]
## Expected Behavior
Applying policies to LDAP groups should allow users to log into console

## Current Behavior
Applying policies to LDAP groups does not work but applying policies to users in those groups works. 

Flipping back to Minio 418 immediately fixes the issue regardless of console version.

## Steps to Reproduce (for bugs)

1. Have a Working environment
2. upgrade to latest version
3. Stops working

Fresh:
1. Take consoleAdmin policy apply to group in AD
2. Try to log into Console with AD account, fails
3. Error in Console is:
```
2021-05-12 20:37:22.938785 I | 2021/05/12 20:37:22 error.go:52: user_login.go:50: original error: invalid Login
2021-05-12 20:37:22.938824 I | 2021/05/12 20:37:22 error.go:154: debugging error: The Access Key Id you provided does not exist in our records.
```
4. No errors in Minio console

## Regression
Yes, latest version introduced this bug

## Your Environment
Minio - 511 version
Console 0.7.1
multi-node cluster and standalone environments effected

**Comment by harshavardhana** [comment]
> Applying policies to LDAP groups does not work but applying policies to users in those groups works.

Understood @tkg61 we shall take a look

**Comment by harshavardhana** [comment]
For the time being the workaround is necessary..

**Comment by harshavardhana** [comment]
Can you provide some more details on how the group part was setup on your end ?

**Comment by tkg61** [comment]
Sure,

mc command:
` mc admin policy set myminio consoleAdmin CN=GROUP-DN,OU=OU_NAME3,OU=OU_NAME2,OU=OU_NAME1,DC=MY,DC=DOMAIN,DC=local`

ENV:
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="OU=OU_NAME2,OU=OU_NAME1,DC=MY,DC=DOMAIN,DC=local"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="OU=OU_NAME2,OU=OU_NAME1,DC=MY,DC=DOMAIN,DC=local"

Further debug:

We have user groups in OU_NAME3 and another OU_NAME4 underneath OU_NAME2. Maybe sub-OUs broke?
```
             OU_NAME1
                   |
                OU_NAME2
              /          \
        OU_NAME3       OU_NAME4
        |                     |
  Usergroups             Usergroups
```  
  
When i don't apply a policy to a user, minio console gives an error it couldn't find a policy for my user or one of its groups (printing out said items). When i copy and paste the group from the error message into the mc command to apply the policy i don't get any more errors from minio but console outputs the above error in the OP. If i copy and past the user DN into the mc command it works fine.

**Comment by harshavardhana** [comment]
> `mc admin policy set myminio consoleAdmin CN=GROUP-DN,OU=OU_NAME3,OU=OU_NAME2,OU=OU_NAME1,DC=MY,DC=DOMAIN,DC=local`

This is incorrect @tkg61 you are not doing `mc admin policy set myminio/ consoleAdmin group=""`

**Comment by tkg61** [comment]
> > `mc admin policy set myminio consoleAdmin CN=GROUP-DN,OU=OU_NAME3,OU=OU_NAME2,OU=OU_NAME1,DC=MY,DC=DOMAIN,DC=local`
> 
> This is incorrect @tkg61 you are not doing `mc admin policy set myminio/ consoleAdmin group=""`

Sorry, yes, I have been doing that, copy and pasted incorrectly from the command line. 

Also I have a non test instance that I upgraded in place with no tweaks (working before) and the issue still persists.

**Comment by harshavardhana** [comment]
> Also I have a non test instance that I upgraded in place with no tweaks (working before) and the issue still persists.

mc admin trace -a -v --funcname admin.*  --funcname sts.* alias/ - can you provide the output for this? while you are attempting to login with your AD account after upgrade?

**Comment by tkg61** [comment]
Here is the output 

```
mytest.domain.local:9000 [REQUEST sts.AssumeRoleWithLDAPIdentity] [23:46:37.438] [Client IP: ::1]
mytest.domain.local:9000 POST /?Action=AssumeRoleWithLDAPIdentity&LDAPPassword=*REDACTED*&LDAPUsername=Test_user&Version=2011-06-15
mytest.domain.local:9000 Proto: HTTP/1.1
mytest.domain.local:9000 Host: mytest.domain.local:9000
mytest.domain.local:9000 Content-Length: 0
mytest.domain.local:9000 User-Agent: Go-http-client/1.1
mytest.domain.local:9000
mytest.domain.local:9000 [RESPONSE] [23:46:37.469] [ Duration 31.321ms  ↑ 31 B  ↓ 1.0 KiB ]
mytest.domain.local:9000 200 OK
mytest.domain.local:9000 Content-Type: application/xml
mytest.domain.local:9000 Server: MinIO
mytest.domain.local:9000 Vary: Origin
mytest.domain.local:9000 X-Amz-Request-Id: 167E767D88D2BCB5
mytest.domain.local:9000 X-Xss-Protection: 1; mode=block
mytest.domain.local:9000 Accept-Ranges: bytes
mytest.domain.local:9000 Content-Length: 837
mytest.domain.local:9000 Content-Security-Policy: block-all-mixed-content
mytest.domain.local:9000 <?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithLDAPIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><AssumeRoleWithLDAPIdentityResult><Credentials><AccessKeyId>ACCESSKEYID</AccessKeyId><SecretAccessKey>ASECRETACCESSKEY</SecretAccessKey><Expiration>2021-05-13T00:46:37Z</Expiration><SessionToken>ASESSIONTOKEN</SessionToken></Credentials></AssumeRoleWithLDAPIdentityResult><ResponseMetadata><RequestId>167E767D88D2BCB5</RequestId></ResponseMetadata></AssumeRoleWithLDAPIdentityResponse>
mytest.domain.local:9000
mytest.domain.local:9000 [REQUEST admin.AccountInfo] [23:46:37.471] [Client IP: ::1]
mytest.domain.local:9000 GET /minio/admin/v3/accountinfo
mytest.domain.local:9000 Proto: HTTP/1.1
mytest.domain.local:9000 Host: mytest.domain.local:9000
mytest.domain.local:9000 Authorization: AWS4-HMAC-SHA256 Credential=ACCESSKEYID/20210512//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=5e9122fafef8abd6130455765060f01793d14a8b72f9d34f9d303e1906f984a1
mytest.domain.local:9000 Content-Length: 0
mytest.domain.local:9000 User-Agent: MinIO (linux; amd64) madmin-go/0.0.1
mytest.domain.local:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
mytest.domain.local:9000 X-Amz-Date: 20210512T234637Z
mytest.domain.local:9000 X-Amz-Security-Token: ASECURITYTOKEN
mytest.domain.local:9000
mytest.domain.local:9000 [RESPONSE] [23:46:37.471] [ Duration 795µs  ↑ 98 B  ↓ 453 B ]
mytest.domain.local:9000 403 Forbidden
mytest.domain.local:9000 X-Amz-Request-Id: 167E767D8AC3476E
mytest.domain.local:9000 X-Xss-Protection: 1; mode=block
mytest.domain.local:9000 Accept-Ranges: bytes
mytest.domain.local:9000 Content-Length: 224
mytest.domain.local:9000 Content-Security-Policy: block-all-mixed-content
mytest.domain.local:9000 Content-Type: application/json
mytest.domain.local:9000 Server: MinIO
mytest.domain.local:9000 Vary: Origin
mytest.domain.local:9000 {"Code":"InvalidAccessKeyId","Message":"The Access Key Id you provided does not exist in our records.","Resource":"/minio/admin/v3/accountinfo","RequestId":"167E767D8AC3476E","HostId":"9c561e3a-b3fc-4535-aa9f-93572a3436d3"}

mytest.domain.local:9000
```

If i just switch out which version is running with no other changes i get a 200 response and the information is printed out at the bottom with what i can access and my permissions

**Comment by harshavardhana** [comment]
> If i just switch out which version is running with no other changes i get a 200 response and the information is printed out at the bottom with what i can access and my permissions

Okay so the issue is not in STS its in actually validating the AccountInfo - should be easy to fix.
