### ISSUE TITLE
Feature request: Disable access if MinIO is started with missing pools

### ISSUE THREAD

**Issue by haslersn** [minio/minio#12286]
As stated in https://github.com/minio/operator/issues/637#issuecomment-839994484, it is allowed (and there is a use case, when using MinIO operator) to start MinIO with a single pool, if the data of that pool used to be just one pool of a multi-pool MinIO.

In order to prevent mistakes—e.g. a user could forget to turn off ingress—MinIO should not allow any access to the API during this time.

**Describe the solution you'd like**

When starting MinIO with missing pool(s), MinIO should not allow any access to the API. Instead it should log an error stating that MinIO has been started with missing pool(s).

**Describe alternatives you've considered**

Discussion: Maybe this should even be a fatal error, i.e., lead to an immediate non-zero exit. However, I'm not sure whether abovementioned use case (creating a MinIO operator tenant with 1 pool and then expanding it) would then still work, or whether the operator would refuse to expand a MinIO that doesn't even successfully start.

**Comment by harshavardhana** [comment]
Pools is going to be redesigned, currently pools are ephemeral i.e they do not exist beyond it's runtime behavior.

Changes in command line are unsupported once the pool has expanded. It is upto the user or operator to preserve this information properly. 

So we are rewriting this portion and this issue will be automatically addressed there..

**Comment by harshavardhana** [comment]
This shall be implemented as part of https://github.com/minio/minio/issues/11990
