### ISSUE TITLE
Minio ILM policies not working

### ISSUE THREAD

**Issue by zeropoint46** [minio/minio#12281]
## Expected Behavior
I have configured an ILM policy on a bucket:
`{
 "status": "success",
 "target": "test-minio/test-bucket",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "Days": 10,
     "DeleteMarker": false
    },
    "ID": "c25hq217rvpfmj7nampg",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
`
files older than 10 days should be deleted. however they are not.

## Current Behavior
after 10days or possibly 11 because of when the job runs, files older than 10 days should be deleted. however they are not. If I don't manually clean up, files will remain forever.

## Possible Solution
not sure what the exact issue is to propose a solution

## Steps to Reproduce (for bugs)
1. set ilm policy with expiration
2. wait until files should expire
3. check for files older than policy

## Context
It has caused our cluster to fill up and run out of space and cause us to have to manually clean up the buckets.

## Regression
I don't think it ever worked

## Your Environment
* Version used (`minio --version`): 2021-04-22T15:44:28Z
* Server setup and configuration: using the minio public release docker image in kubernetes cluster
* Operating System and version (`uname -a`): Linux 4.15.0-70-generic (baremetal k8 node that minio container is running on)

**Comment by harshavardhana** [comment]
To be fixed by #12229
