### ISSUE TITLE
unable to install the Minio mc

### ISSUE THREAD

**Issue by bbpandey1** [minio/minio#12299]
## Current Behavior
==> Tapping minio/stable
Cloning into '/usr/local/Homebrew/Library/Taps/minio/homebrew-stable'...
remote: Enumerating objects: 1196, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 1196 (delta 37), reused 43 (delta 20), pack-reused 1136
Receiving objects: 100% (1196/1196), 158.78 KiB | 2.94 MiB/s, done.
Resolving deltas: 100% (782/782), done.
Tapped 2 formulae (31 files, 235.8KB).
==> Installing mc from minio/stable
==> Downloading https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.20
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "mc"
Download failed: https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2021-05-12T01-29-06Z

## Possible Solution
Please correct the URL for the stable version.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> ==> Tapping minio/stable
> Cloning into '/usr/local/Homebrew/Library/Taps/minio/homebrew-stable'...
> remote: Enumerating objects: 1196, done.
> remote: Counting objects: 100% (60/60), done.
> remote: Compressing objects: 100% (40/40), done.
> remote: Total 1196 (delta 37), reused 43 (delta 20), pack-reused 1136
> Receiving objects: 100% (1196/1196), 158.78 KiB | 2.94 MiB/s, done.
> Resolving deltas: 100% (782/782), done.
> Tapped 2 formulae (31 files, 235.8KB).
> ==> Installing mc from minio/stable
> ==> Downloading https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.20
> ##O#- #
> curl: (22) The requested URL returned error: 404
> Error: Failed to download resource "mc"
> Download failed: https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2021-05-12T01-29-06Z
> 
> ## Possible Solution


This is fixed in https://github.com/minio/homebrew-stable/commit/308ddccb8b146275d50b2193f3b3fead03869a6c
