### ISSUE TITLE
Users getting disable after upgrade to RELEASE.2021-05-11T23-27-41Z

### ISSUE THREAD

**Issue by ManishNferX** [minio/minio#12292]
We upgraded the cluster from RELEASE.2021-01-08T21-18-21Z to RELEASE.2021-05-11T23-27-41Z
Post upgrade, all the old users in the cluster went to the disabled state

## Expected Behavior
All users are in an enabled state with no changes after the upgrade.

## Current Behavior
Users went into a disabled state, after checking with the mc client.

## Possible Solution
Deleting all the old users and recreating them, fixed the issue.

## Steps to Reproduce (for bugs)

1.We upgraded the cluster from RELEASE.2021-01-08T21-18-21Z to RELEASE.2021-05-11T23-27-41Z
2. Upgrade was done, by replacing the binary and restarting the cluster in one shot
3. Post upgrade, all the users went into disabled state.
4. Even after trying to enable with mc client (and it showing the success), the users were not enabled.

## Context
None of the users were able to access their buckets

## Regression
No

## Your Environment
Older version: RELEASE.2021-01-08T21-18-21Z
Upgraded version: RELEASE.2021-05-11T23-27-41Z
OS: ubuntu 18.04.5
Kernel: 4.15.0-112-generic

**Comment by harshavardhana** [comment]
@ManishNferX Thanks we shall take a look - @aead ^^

**Comment by harshavardhana** [comment]
@ManishNferX I tried to upgrade from RELEASE.2021-01-08T21-18-21Z to  RELEASE.2021-05-11T23-27-41Z all users seem to be in-tact. 

are you running in a distributed setup?

**Comment by ManishNferX** [comment]
@harshavardhana : Yes, we are running 20 machines cluster, with 10 disks per machine. Weird that the issue didn't pop up at your end. My guess would be, we are hitting some corner case then.

**Comment by harshavardhana** [comment]
> @harshavardhana : Yes, we are running 20 machines cluster, with 10 disks per machine. Weird that the issue didn't pop up at your end. My guess would be, we are hitting some corner case then.

do you know the number of users you had? did you have any users disabled as well previously?

**Comment by ManishNferX** [comment]
No, none of the users were disabled previously and it was all working fine till we upgraded.
We got roughly 40 users.

**Comment by harshavardhana** [comment]
> No, none of the users were disabled previously and it was all working fine till we upgraded.
> We got roughly 40 users.

Okay let me try with 40 users.

**Comment by harshavardhana** [comment]
> > No, none of the users were disabled previously and it was all working fine till we upgraded.
> > We got roughly 40 users.
> 
> Okay let me try with 40 users.

Okay so I tried 50 users on a distributed multi-node setup - doesn't look like there is an issue. Will keep looking..

**Comment by ManishNferX** [comment]
Thansk @harshavardhana . I will also dig further and see if I can find something more to help you.

**Comment by harshavardhana** [comment]
@ManishNferX when you said users were disabled you actually mean that users were present as `mc admin user list` but they were showing as "disabled" ?  or `mc admin user list` was empty?

**Comment by ManishNferX** [comment]
Yes, users were there, and they were showing in "mc admin user list" but the status was disabled.

```
$ mc admin user info minio XXX@XXX.net
AccessKey: XXXXXXXXXXXXX
Status: disabled
PolicyName:
MemberOf:
```

```
$ mc admin user list myminio
disabled    XXXXX@nf...  XXXX-data-...
disabled    XXX@XXXX.net    XXX-re...
disabled    XXXXXXXXX   XXXXXXX...
.......
```

It was showing like this.

**Comment by harshavardhana** [comment]
AFAICS that is impossible for the server to do it on its own - there are no code pathways to arrive at this @ManishNferX - unless simply it was an on-disk state was correct - somehow in-memory representation was wrong.

Whatever it is - it's quite strange.

**Comment by ManishNferX** [comment]
This was not an on-disk state before the upgrade. One more thing we noticed, is that when we first saw this issue, we also just tried creating the users (without deleting them), and that worked and also, users got enabled.

But, after few hours, the whole minio cluster got restarted (on its own), and the state went to disabled again. I would assume that whatever we changed, didn't get pushed to disk, and post minio restart (we are still checking why this happened, but we couldn't find my relevant logging for this), it's all got reverted.

In the end, we deleted and recreated all users, which worked fine (and still working)

Though from the morning we are facing a really weird issue, where our policies are going missing on its own. We are in the process of again recreating them.

Are there any commands I can run and help you with any output?

**Comment by harshavardhana** [comment]
> But, after few hours, the whole minio cluster got restarted (on its own), and the state went to disabled again. I would assume that whatever we changed, didn't get pushed to disk, and post minio restart (we are still checking why this happened, but we couldn't find my relevant logging for this), it's all got reverted.

why would the server restart on its own? - there would be something to indicate on the system that there was a process restart - like if you are running in systemd there would be an indication of a restart. 


> Though from the morning we are facing a really weird issue, where our policies are going missing on its own. We are in the process of again recreating them.

This is also strange - you can verify if really your policies are missing at `<backend_drive>/.minio.sys/config/iam/policies`  across servers.  If they are not missing on the backend then they are simply missing through the server trying to read them would be something else. 

Also checking if you have any KMS enabled with MinIO on this cluster?

**Comment by ManishNferX** [comment]
@harshavardhana: So, we dug into this further. The restarts seem to be happening because minio is using all the system RAM (128G) and running out of memory. Below are the logs.

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x240e761, 0x16)
	runtime/panic.go:1117 +0x72
runtime.sysMap(0xdda4000000, 0x1c000000, 0x3c44df0)
	runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x3c2a400, 0x1bc00000, 0x42c3f7, 0x3c2a408)
	runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x3c2a400, 0xdd00, 0x0)
	runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x3c2a400, 0xdd00, 0x440000, 0xc004ac4900)
	runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:910 +0x59
runtime.systemstack(0xc009a64c60)
	runtime/asm_amd64.s:379 +0x66
runtime.mstart()
	runtime/proc.go:1246
```

We don't have any KMS enabled with the minio cluster.

Also, I just got to know one more thing. While we were updating the cluster, we didn't shut down the process before replacing the binary. The process went like this, replace the binary -> restart the minio process.
Is that something that could have caused the issues we are seeing?

We also noticed the users also went missing over the weekend. As of now, we have recreated everything, but I am waiting for policies/users to go missing again so that I can check at the filesystem level and update you.

**Comment by ManishNferX** [comment]
Here are more logs about the OOM

```
[Mon May 17 08:16:25 2021] Out of memory: Kill process 2136200 (minio) score 944 or sacrifice child
[Mon May 17 08:16:25 2021] Killed process 2136200 (minio) total-vm:137694528kB, anon-rss:124276916kB, file-rss:23028kB, shmem-rss:0kB
[Mon May 17 08:16:30 2021] oom_reaper: reaped process 2136200 (minio), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[Mon May 17 11:29:47 2021] minio invoked oom-killer: gfp_mask=0x14280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), nodemask=(null), order=0, oom_score_adj=0
[Mon May 17 11:29:47 2021] minio cpuset=/ mems_allowed=0
```

**Comment by ManishNferX** [comment]
Also, regarding the disappearing policies, we created a policy in the morning, and by evening, it went missing. When I checked these folders 
```
$ ls -l /mnt/drive*/.minio.sys/config/iam/policies | grep <policy_name>
```
I couldn't find the policy on the filesystem only. I checked all the minio machines and all the mounts.

**Comment by harshavardhana** [comment]
> @harshavardhana: So, we dug into this further. The restarts seem to be happening because minio is using all the system RAM (128G) and running out of memory. Below are the logs.
> 
> ```
> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0x240e761, 0x16)
> 	runtime/panic.go:1117 +0x72
> runtime.sysMap(0xdda4000000, 0x1c000000, 0x3c44df0)
> 	runtime/mem_linux.go:169 +0xc6
> runtime.(*mheap).sysAlloc(0x3c2a400, 0x1bc00000, 0x42c3f7, 0x3c2a408)
> 	runtime/malloc.go:729 +0x1e5
> runtime.(*mheap).grow(0x3c2a400, 0xdd00, 0x0)
> 	runtime/mheap.go:1346 +0x85
> runtime.(*mheap).allocSpan(0x3c2a400, 0xdd00, 0x440000, 0xc004ac4900)
> 	runtime/mheap.go:1173 +0x609
> runtime.(*mheap).alloc.func1()
> 	runtime/mheap.go:910 +0x59
> runtime.systemstack(0xc009a64c60)
> 	runtime/asm_amd64.s:379 +0x66
> runtime.mstart()
> 	runtime/proc.go:1246
> ```
> 
> We don't have any KMS enabled with the minio cluster.
> 
> Also, I just got to know one more thing. While we were updating the cluster, we didn't shut down the process before replacing the binary. The process went like this, replace the binary -> restart the minio process.
> Is that something that could have caused the issues we are seeing?
> 
> We also noticed the users also went missing over the weekend. As of now, we have recreated everything, but I am waiting for policies/users to go missing again so that I can check at the filesystem level and update you.

Yes, this looks strange @ManishNferX please try upgrading to the latest release yesterday and see if that helps in the memory build-up.

**Comment by ManishNferX** [comment]
Already did that in the morning, hoping for this, as I did see some memory optimization changelogs, but it didn't help.
We are still seeing continuous restarts for all minio (every hour or so) and issues with policies/users disappearing.

**Comment by harshavardhana** [comment]
> Already did that in the morning, hoping for this, as I did see some memory optimization changelogs, but it didn't help.
> We are still seeing continuous restarts for all minio (every hour or so) and issues with policies/users disappearing.

can you enable `mc admin profile start alias/` to see the memory buildup and share with us the results of the profile output?  `mc admin profile stop alias/` after like 5minutes..

**Comment by ManishNferX** [comment]
> > Already did that in the morning, hoping for this, as I did see some memory optimization changelogs, but it didn't help.
> > We are still seeing continuous restarts for all minio (every hour or so) and issues with policies/users disappearing.
> 
> can you enable `mc admin profile start alias/` to see the memory buildup and share with us the results of the profile output? `mc admin profile stop alias/` after like 5minutes..

[profile.zip](https://github.com/minio/minio/files/6495582/profile.zip)

**Comment by harshavardhana** [comment]
@ManishNferX do not see real used memory

```
go tool pprof profile-10.10.0.104\:8991-mem.pprof 
File: minio
Type: inuse_space
Time: May 17, 2021 at 10:00am (PDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 548.27MB, 95.67% of 573.07MB total
Dropped 875 nodes (cum <= 2.87MB)
Showing top 10 nodes out of 75
      flat  flat%   sum%        cum   cum%
  260.07MB 45.38% 45.38%   392.19MB 68.44%  github.com/minio/minio/cmd.(*dataUsageCache).DecodeMsg
  111.40MB 19.44% 64.82%   111.40MB 19.44%  github.com/minio/minio/cmd.NewReplicationPool
  103.03MB 17.98% 82.80%   103.03MB 17.98%  github.com/tinylib/msgp/msgp.(*Reader).ReadString
   29.12MB  5.08% 87.88%    80.53MB 14.05%  github.com/minio/minio/cmd.(*dataUsageHashMap).DecodeMsg
      14MB  2.44% 90.32%       14MB  2.44%  github.com/minio/minio/cmd.glob..func6
   10.81MB  1.89% 92.21%    10.83MB  1.89%  github.com/minio/minio/cmd.newErasureSets
    5.49MB  0.96% 93.17%     5.49MB  0.96%  bufio.NewWriterSize
    5.46MB  0.95% 94.12%     5.46MB  0.95%  bufio.NewReaderSize
    4.88MB  0.85% 94.97%     4.88MB  0.85%  github.com/minio/minio/cmd.newExpiryState
    4.02MB   0.7% 95.67%     4.02MB   0.7%  github.com/ncw/directio.AlignedBlock
```

@ManishNferX try setting `GOGC=25` and restart the cluster - there is nothing in the profile that I can see shows extensive memory usage or leakage. 

How many objects do you have in the cluster?

**Comment by harshavardhana** [comment]
can you provide `mc admin config export` looks like you have enabled bitrot scanning by default? @ManishNferX

**Comment by harshavardhana** [comment]
do you also have any other application that co-exists with MinIO on the same servers?

**Comment by harshavardhana** [comment]
```
go tool pprof -alloc_space profile-10.10.0.101\:8991-mem.pprofmmunity$ 
File: minio
Type: alloc_space
Time: May 17, 2021 at 10:00am (PDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 71.56GB, 42.83% of 167.10GB total
Dropped 1938 nodes (cum <= 0.84GB)
Showing top 10 nodes out of 267
      flat  flat%   sum%        cum   cum%
   14.35GB  8.59%  8.59%    16.29GB  9.75%  net/url.parseQuery
    8.41GB  5.03% 13.62%     8.41GB  5.03%  github.com/ncw/directio.AlignedBlock
    8.12GB  4.86% 18.48%     8.13GB  4.86%  github.com/minio/minio/cmd.bitrotVerify
    7.51GB  4.49% 22.97%    10.27GB  6.15%  github.com/minio/minio/cmd.(*dataUsageCache).DecodeMsg
    7.38GB  4.42% 27.39%     7.38GB  4.42%  io.ReadAll
    6.73GB  4.03% 31.42%     6.73GB  4.03%  bufio.(*Scanner).Scan
    6.06GB  3.62% 35.04%     6.06GB  3.62%  strings.(*Builder).grow (inline)
    5.08GB  3.04% 38.09%     5.39GB  3.23%  net/textproto.(*Reader).ReadMIMEHeader
    4.07GB  2.43% 40.52%     4.07GB  2.43%  bytes.makeSlice
    3.86GB  2.31% 42.83%     3.86GB  2.31%  crypto/sha512.New
```

The actual allocation

**Comment by ManishNferX** [comment]
```
$ mc admin config export minio
region name=
storage_class standard= rrs=EC:2 dma=read+write
# cache drives= exclude= expiry=90 quota=80 after=0 watermark_low=70 watermark_high=80 range=on commit=writethrough
# compression enable=off allow_encryption=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml,binary/octet-stream
# etcd endpoints= path_prefix= coredns_path=/skydns client_cert= client_cert_key=
# identity_openid config_url= client_id= claim_name=policy claim_prefix= scopes= jwks_url=
# identity_ldap server_addr= username_format= user_dn_search_base_dn= user_dn_search_filter= group_search_filter= group_search_base_dn= sts_expiry=1h tls_skip_verify=off server_insecure=off server_starttls=off lookup_bind_dn= lookup_bind_password=
# policy_opa url= auth_token=
kms_vault
kms_kes
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict extend_list_cache_life=0s replication_workers=500 replication_failed_workers=4
heal bitrotscan=off max_sleep=1s max_io=10
scanner delay=10 max_wait=15s cycle=1m
# logger_webhook enable=off endpoint= auth_token=
# audit_webhook enable=off endpoint= auth_token= client_cert= client_key=
# notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
# notify_amqp enable=off url= exchange= exchange_type= routing_key= mandatory=off durable=off no_wait=off internal=off auto_deleted=off delivery_mode=0 queue_limit=0 queue_dir=
# notify_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir= version=
# notify_mqtt enable=off broker= topic= password= username= qos=0 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0
# notify_nats enable=off address= subject= username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 streaming=off streaming_async=off streaming_max_pub_acks_in_flight=0 streaming_cluster_id= queue_dir= queue_limit=0
# notify_nsq enable=off nsqd_address= topic= tls=off tls_skip_verify=off queue_dir= queue_limit=0
# notify_mysql enable=off format=namespace dsn_string= table= queue_dir= queue_limit=0 max_open_connections=2
# notify_postgres enable=off format=namespace connection_string= table= queue_dir= queue_limit=0 max_open_connections=2
# notify_elasticsearch enable=off url= format=namespace index= queue_dir= queue_limit=0 username= password=
# notify_redis enable=off format=namespace address= key= password= queue_dir= queue_limit=0
```

Also, I noticed from the above configs that watermark high is set to 80% disk usage? Looking at my cluster, most of the disks are in the range of 75-80%. Could that possibly result in what's happening?

**Comment by ManishNferX** [comment]
No @harshavardhana, these are completely dedicated machines for Minio. Nothing else runs on these machines, leaving monitoring modules (which we also looked into, and they are not taking any significant resources)

**Comment by ManishNferX** [comment]
Also, is there anything I can check to look into missing policies/users? Today morning few policies/users went missing again.

**Comment by harshavardhana** [comment]
> Also, is there anything I can check to look into missing policies/users? Today morning few policies/users went missing again.
> 

That looks weird. There is nothing present on the system that can do that.

There are explicit deletes on these objects. So clearly there is something else running that clears it up.

We made a new release to address the memory spike, please do give it a try.

**Comment by ManishNferX** [comment]
Updated to the new release. Sadly, the memory build-up issue is still there. Minio process quickly starts eating all memory. Even if I try to start the profile, it's not enough time. The build-up happens in a matter of few minutes, and the minion process restarts after that.

Below are some system logs from when it happens. Hoping that could help a little. 

```
[Mon May 17 23:50:30 2021] Node 0 active_anon:127957180kB inactive_anon:624kB active_file:0kB inactive_file:288kB unevictable:9076kB isolated(anon):0kB isolated(file):0kB mapped:4740kB dirty:184kB writeback:168kB shmem:1552kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 61134848kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[Mon May 17 23:50:30 2021] Node 0 DMA free:15904kB min:120kB low:148kB high:176kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15988kB managed:15904kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[Mon May 17 23:50:30 2021] lowmem_reserve[]: 0 1770 128744 128744 128744
[Mon May 17 23:50:30 2021] Node 0 DMA32 free:521868kB min:14208kB low:17760kB high:21312kB active_anon:1349656kB inactive_anon:0kB active_file:60kB inactive_file:220kB unevictable:0kB writepending:4kB present:1961756kB managed:1874248kB mlocked:0kB kernel_stack:0kB pagetables:4kB bounce:0kB free_pcp:560kB local_pcp:0kB free_cma:0kB
[Mon May 17 23:50:30 2021] lowmem_reserve[]: 0 0 126973 126973 126973
[Mon May 17 23:50:30 2021] Node 0 Normal free:985296kB min:985668kB low:1232084kB high:1478500kB active_anon:126606732kB inactive_anon:624kB active_file:0kB inactive_file:0kB unevictable:9076kB writepending:348kB present:132120576kB managed:130020588kB mlocked:9076kB kernel_stack:7568kB pagetables:261428kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[Mon May 17 23:50:30 2021] lowmem_reserve[]: 0 0 0 0 0
[Mon May 17 23:50:30 2021] Node 0 DMA: 0*4kB 0*8kB 0*16kB 1*32kB (U) 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15904kB
[Mon May 17 23:50:30 2021] Node 0 DMA32: 10*4kB (UME) 40*8kB (UME) 34*16kB (UME) 26*32kB (UME) 19*64kB (UME) 19*128kB (UME) 22*256kB (UME) 26*512kB (UME) 27*1024kB (UME) 2*2048kB (UE) 114*4096kB (UH) = 523016kB
[Mon May 17 23:50:30 2021] Node 0 Normal: 27964*4kB (UME) 20033*8kB (UME) 13928*16kB (UME) 8149*32kB (UME) 3541*64kB (UME) 36*128kB (UM) 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 986968kB
[Mon May 17 23:50:30 2021] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[Mon May 17 23:50:30 2021] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[Mon May 17 23:50:30 2021] 1916 total pagecache pages
[Mon May 17 23:50:30 2021] 0 pages in swap cache
[Mon May 17 23:50:30 2021] Swap cache stats: add 0, delete 0, find 0/0
[Mon May 17 23:50:30 2021] Free swap  = 0kB
[Mon May 17 23:50:30 2021] Total swap = 0kB
[Mon May 17 23:50:30 2021] 33524580 pages RAM
[Mon May 17 23:50:30 2021] 0 pages HighMem/MovableOnly
[Mon May 17 23:50:30 2021] 546895 pages reserved
[Mon May 17 23:50:30 2021] 0 pages cma reserved
[Mon May 17 23:50:30 2021] 0 pages hwpoisoned
[Mon May 17 23:50:30 2021] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[Mon May 17 23:50:30 2021] [  508]     0   508   132937     3182  1040384        0             0 systemd-journal
[Mon May 17 23:50:30 2021] [  528]     0   528    26476      120    98304        0             0 lvmetad
[Mon May 17 23:50:30 2021] [  531]     0   531     8489      281   118784        0         -1000 systemd-udevd
[Mon May 17 23:50:30 2021] [  741]     0   741     1876       68    57344        0             0 mdadm
[Mon May 17 23:50:30 2021] [  762]   101   762    17758      238   172032        0             0 systemd-resolve
[Mon May 17 23:50:30 2021] [  808]     0   808     3092      867    65536        0             0 haveged
[Mon May 17 23:50:30 2021] [  814]   103   814    11998      221   139264        0          -900 dbus-daemon
[Mon May 17 23:50:30 2021] [  817]     0   817     7083       96   102400        0             0 atd
[Mon May 17 23:50:30 2021] [  819]     0   819     7895      329   102400        0             0 cron
[Mon May 17 23:50:30 2021] [  869]     0   869     4110       35    73728        0             0 agetty
[Mon May 17 23:50:30 2021] [16240]     0 16240    16732     3346   176128        0             0 supervisord
[Mon May 17 23:50:30 2021] [25633]   100 25633    18001      224   167936        0             0 systemd-network
[Mon May 17 23:50:30 2021] [683706]   998 683706   179512     2214   221184        0             0 consul_exporter
[Mon May 17 23:50:30 2021] [2048358]     0 2048358     1130      339    57344        0             0 atopacctd
[Mon May 17 23:50:30 2021] [3884583]     0 3884583    46873     2492   266240        0             0 unattended-upgr
[Mon May 17 23:50:30 2021] [4063569]   106 4063569     7100       94    98304        0             0 uuidd
[Mon May 17 23:50:30 2021] [1603728]     0 1603728     6696      922    94208        0             0 smartd
[Mon May 17 23:50:30 2021] [1604479]   102 1604479    68246      368   163840        0             0 rsyslogd
[Mon May 17 23:50:30 2021] [4151188]     0 4151188   180264     1861   155648        0             0 sidekick
[Mon May 17 23:50:30 2021] [4172216]     0 4172216    20252      332   184320        0             0 systemd-logind
[Mon May 17 23:50:30 2021] [1449763]     0 1449763    51193      670   425984        0             0 sssd
[Mon May 17 23:50:30 2021] [1449764]     0 1449764    63119     1678   507904        0             0 sssd_be
[Mon May 17 23:50:30 2021] [1449765]     0 1449765    50456      582   425984        0             0 sssd_nss
[Mon May 17 23:50:30 2021] [1449766]     0 1449766    45860      412   380928        0             0 sssd_pam
[Mon May 17 23:50:30 2021] [1449767]     0 1449767    43732      541   376832        0             0 sssd_ssh
[Mon May 17 23:50:30 2021] [1449784]     0 1449784    18076      590   192512        0         -1000 sshd
[Mon May 17 23:50:30 2021] [1747479]   112 1747479    28911      291   139264        0             0 ntpd
[Mon May 17 23:50:30 2021] [1944853]  8901 1944853   179984     1993   204800        0             0 node_exporter
[Mon May 17 23:50:30 2021] [1953123]     0 1953123    33644      799   274432        0             0 sshd
[Mon May 17 23:50:30 2021] [1953201]  5001 1953201    19202      315   184320        0             0 systemd
[Mon May 17 23:50:30 2021] [1953202]  5001 1953202    71546      729   282624        0             0 (sd-pam)
[Mon May 17 23:50:30 2021] [1953295]  5001 1953295    33644      267   274432        0             0 sshd
[Mon May 17 23:50:30 2021] [1953296]  5001 1953296     8300      898   102400        0             0 bash
[Mon May 17 23:50:30 2021] [1953312]     0 1953312    22081      633   204800        0             0 sudo
[Mon May 17 23:50:30 2021] [1953316]     0 1953316    21931      595   200704        0             0 su
[Mon May 17 23:50:30 2021] [1953317]     0 1953317     5725      883    98304        0             0 bash
[Mon May 17 23:50:30 2021] [1956897]     0 1956897     9366      506   106496        0             0 htop
[Mon May 17 23:50:30 2021] [1980431]   999 1980431   214092     9170   393216        0             0 consul
[Mon May 17 23:50:30 2021] [1997071]  8900 1997071 32918007 31952969 260808704        0             0 minio
[Mon May 17 23:50:30 2021] [1999451]     0 1999451     6506     2271   102400        0             0 atop
[Mon May 17 23:50:30 2021] Out of memory: Kill process 1997071 (minio) score 970 or sacrifice child
[Mon May 17 23:50:30 2021] Killed process 1997071 (minio) total-vm:131672028kB, anon-rss:127811876kB, file-rss:0kB, shmem-rss:0kB
[Mon May 17 23:50:32 2021] oom_reaper: reaped process 1997071 (minio), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```


Please let me know @harshavardhana if you want me to create a separate ticket for the memory issue.

**Comment by ManishNferX** [comment]
We have recreated some policies again, which got deleted today morning and monitoring it. Will update here if some again goes missing.
Just to confirm, there is nothing else running on the machines which could possibly interact with the server.

**Comment by harshavardhana** [comment]
> We have recreated some policies again, which got deleted today morning and monitoring it. Will update here if some again goes missing.
> Just to confirm, there is nothing else running on the machines which could possibly interact with the server.

@ManishNferX can you provide remote access to the systems ?

**Comment by harshavardhana** [comment]
We were able to figure out the root cause for the high memory usage as well as users becoming disabled

**Comment by ManishNferX** [comment]
That's superb @harshavardhana . Looking forward to it.
