### ISSUE TITLE
RemoveObject followed by GetObject succeed in retrieving the object - distributed mode

### ISSUE THREAD

**Issue by ofekby** [minio/minio#12294]
RemoveObject followed by GetObject succeed in retrieving the object - distributed mode.
Some objects are deleted after a while

## Expected Behavior

1. call RemoveObject API
2. call GetObject API
3. Receive 404 error code response
4. No data is left on disk regarding the object.

## Current Behavior

1. call RemoveObject API
2. call GetObject API
3. Responded with object data
4. The object directory is still on disk.
5. The object is some times deleted 

## Possible Solution

Just an assumption, the RemoveObject API call respond with 200 code before the object is 
deleted from the write quorum of the Minio nodes.

## Steps to Reproduce (for bugs)

1. Create a bucket with no replication or versioning
2. PutObject in this bucket
3. remove the object with RemoveObject API
4. fetch the object with GetObject API

The bucket contains about 1 million objects, there are about 20 PutObject per second and 20 DeleteObject per second. 

## Context

The disk used by Minio is filled up and only by running `rm -rf <object_path>` the space and inodes are reclaimed.
We make about 20 PutObject per second and 20 DeleteObject per second on the same bucket.
There are no errors in the Minio service logs.

Things I have tried with no help:
* Calling the RemoveObject API directly to each of the nodes - but object is still present.
* Restarting Minio.

Thought about upgrading Minio but didn't see anything addressing this issue in the changelogs.

## Your Environment

* Version used (`minio --version`): Minio 2021-03-01
* Server setup and configuration: 4 nodes in distributed mode. On each node 1 disk mapped to a mounted NFS V3 volume. (Total of 4 disks). Each node runs on seperate VM with 32 cores and 32GB ram.
* Operating System and version (`uname -a`): centos 7

**Comment by harshavardhana** [comment]
> Just an assumption, the RemoveObject API call respond with 200 code before the object is
> deleted from the write quorum of the Minio nodes.

That is not possible @ofekby - we delete if we cannot delete because if inodes ran out then the object will be preserved, unfortunately, S3 API doesn't have any other return other than 200 OK. So we have to reply 200 OK even in case of failures.

> The disk used by Minio is filled up and only by running `rm -rf <object_path>` the space and inodes are reclaimed.

Please upgrade and test lots of things that have changed.

**Comment by ofekby** [comment]
> > Just an assumption, the RemoveObject API call respond with 200 code before the object is
> > deleted from the write quorum of the Minio nodes.
> 
> That is not possible @ofekby - we delete if we cannot delete because if inodes ran out then the object will be preserved, unfortunately, S3 API doesn't have any other return other than 200 OK. So we have to reply 200 OK even in case of failures.
> 
> > The disk used by Minio is filled up and only by running `rm -rf <object_path>` the space and inodes are reclaimed.
> 
> Please upgrade and test lots of things that have changed.

**Comment by ofekby** [comment]
> That is not possible @ofekby - we delete if we cannot delete because if inodes ran out then the object will be preserved, 
> unfortunately, S3 API doesn't have any other return other than 200 OK. So we have to reply 200 OK even in case of failures.

@harshavardhana The inodes usage is at 15%, and storage is currently at 80%.

**Comment by harshavardhana** [comment]
@ofekby that is impossible unless you have quorum missing etc.

**Comment by ofekby** [comment]
@harshavardhana I can see that once in a while there is a drop in the usage of both inodes and disk space - but it is very minor compared to the amount of files that are deleted. Is Minio handles some kind of deletion in intervals?
Just to emphasize, we don't use versioning nor replication.

**Comment by harshavardhana** [comment]
> @harshavardhana I can see that once in a while there is a drop in the usage of both inodes and disk space - but it is very minor compared to the amount of files that are deleted. Is Minio handles some kind of deletion in intervals?
> Just to emphasize, we don't use versioning nor replication.

@ofekby yes Deletes are not purged right away they are moved to `<disk>/.minio.sys/tmp/.trash` folder and they are purged in the background but the version you are running shouldn't have this change at all. 

> Version used (minio --version): Minio 2021-03-01

**Comment by harshavardhana** [comment]
> * Server setup and configuration: 4 nodes in distributed mode. On each node 1 disk mapped to a mounted NFS V3 volume. (Total of 4 disks). Each node runs on a separate VM with 32 cores and 32GB ram.

Okay so you are using NFS - NFS is not strictly consistent and it's impossible to make it strictly consistent.  Either try to use NFS v4 or do not use NFS and use regular disk filesystems. 

Closing this issue as this is not supported. NFS volumes are not supported.
