### ISSUE TITLE
[Error] A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by luorixiangyang** [minio/minio#12306]
I take a error when to  create a  bucket  with object-lock; Here is error log:
Error occurred: error occurred
ErrorResponse(code = NotImplemented, message = A header you provided implies functionality that is not implemented, bucketName = my-bucketname-in-eu-with-object-lock, objectName = null, resource = /my-bucketname-in-eu-with-object-lock, requestId = 167FD91B2350B930, hostId = 883ec7a6-979d-4d3d-85a2-3bcd127806cc)
request={method=PUT, url=http://10.160.36.247:9000/my-bucketname-in-eu-with-object-lock, headers=x-amz-bucket-object-lock-enabled: true
Host: 10.160.36.247:9000
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.2.1
Content-MD5: RRbNtostJSb8PTpMdgsvng==
x-amz-content-sha256: a2531158b25edb57200e54140cc1b12d0af943f596ea467c2fbbedcc16223cc5
x-amz-date: 20210517T120846Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210517/eu-west-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-bucket-object-lock-enabled;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
.....

-----------------------------
Here is the testcase in java：（step1，step2  finished, but step 3 take error for objcetlock）
@Test
    public void test_Api_makeBucket() throws InvalidKeyException, ErrorResponseException, InsufficientDataException,
            InternalException, InvalidResponseException, NoSuchAlgorithmException, ServerException, XmlParserException,
            IllegalArgumentException, IOException {
        // step1
        String bucketName = "my-bucketname";
        if (!this.minioClient.bucketExists(BucketExistsArgs.builder().bucket(bucketName).build())) {
            this.minioClient.makeBucket(MakeBucketArgs.builder().bucket(bucketName).build());
            System.out.println("build my-bucketname success 。。。");
        }
        // step2
        String bucketNameEU = "my-bucketname-in-eu";
        if (!minioClient.bucketExists(BucketExistsArgs.builder().bucket(bucketNameEU).build())) {
            minioClient.makeBucket(MakeBucketArgs.builder().bucket(bucketNameEU).region("eu-west-1").build());
            System.out.println(bucketNameEU + " is created successfully");
        }

        // Create bucket 'my-bucketname-in-eu-with-object-lock' in 'eu-west-1' with
        // object lock
        // functionality enabled.
        // [error]:no support for next action to build a object-lock bucket
        // step3
        String bucketInRegionEUwithObjectLock = "my-bucketname-in-eu-with-object-lock";
        if (!minioClient.bucketExists(BucketExistsArgs.builder().bucket(bucketInRegionEUwithObjectLock).build())) {
            minioClient.makeBucket(MakeBucketArgs.builder().bucket(bucketInRegionEUwithObjectLock).region("eu-west-1")
                    .objectLock(true).build());
            System.out.println(bucketInRegionEUwithObjectLock + " is created successfully");
        }

    }

let me know how to fix it. thank.

**Comment by klauspost** [comment]
> Object locking feature is only available in erasure coded and distributed erasure coded setups.

https://docs.min.io/docs/minio-bucket-object-lock-guide.html

I am only guessing this is your problem. Next time, please fill out the provided form.
