### ISSUE TITLE
Can't create service account from LDAP group based creds with Console

### ISSUE THREAD

**Issue by tkg61** [minio/minio#12315]
## Expected Behavior
A service account can be generated from console using LDAP creds

## Current Behavior
When clicking on the create button on the service account popup, the screen goes white and logs out the user

Minio outputs no errors to the console 

Console webapp outputs: 
`2021-05-18 13:17:33.633661 I | 2021/05/18 13:17:33 error.go:52: user_service_accounts.go:35: original error: The specified user does not exist. (Specified user does not exist)`

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
go to create service account after logging in with LDAP account, click create button (no additional policies), be logged out

## Context
In further testing this started happening in the 511 update and continues in the 518 one, rolling back to the 418 update everything works fine 

Maybe related to #12282?

Did another trace: 

```
myhost:9000 [RESPONSE] [13:21:03.289] [ Duration 62.96ms  ↑ 157 B  ↓ 469 B ]
myhost:9000 404 Not Found
myhost:9000 Content-Type: application/json
myhost:9000 Server: MinIO
myhost:9000 Vary: Origin
myhost:9000 X-Amz-Request-Id: 16802BD5D3470389
myhost:9000 X-Xss-Protection: 1; mode=block
myhost:9000 Accept-Ranges: bytes
myhost:9000 Content-Length: 240
myhost:9000 Content-Security-Policy: block-all-mixed-content
myhost:9000 {"Code":"XMinioAdminNoSuchUser","Message":"The specified user does not exist. (Specified user does not exist)","Resource":"/minio/admin/v3/add-service-account","RequestId":"16802BD5D3470389","HostId":"HOSTID"}

```

## Regression
Yes, works fine in 418 

## Your Environment
N/A

**Comment by vadmeste** [comment]
@tkg61 what's your console version ?

**Comment by tkg61** [comment]
I have tested with 0.6.8, 0.7.0, 0.7.1 and master pulled on 5/16
