### ISSUE TITLE
ERROR Invalid command line arguments: path '/export' can not be served by different port on same address

### ISSUE THREAD

**Issue by hemantrevankar** [minio/minio#12310]
Hi everyone,
I am setting up minio on a bare metal kubernetes cluster using the minio operator via kubectl minio plugin following the guide here: https://github.com/minio/operator/blob/master/README.md

The minio operator is successfully installed in the namespace minio-operator using the kubectl minio init --cluster-domain=k8s.dev.eds

Next, the minio tenant is installed in the namespace minio using the below command:
kubectl minio tenant create mt1 --servers 4 --volumes 4 --capacity 4Gi --namespace minio --storage-class minio-operator

Here, I use the minio-operator as the StorageClass which is a mapr provisioner to provision PV dynamically.
**# kubectl get sc minio-operator**
NAME             PROVISIONER        RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
minio-operator   com.mapr.csi-kdf   Retain          WaitForFirstConsumer   false                  21h

**# kubectl -n minio-operator get all**
NAME                                 READY   STATUS    RESTARTS   AGE
pod/console-6bdcbb8b89-lcvqz         1/1     Running   0          8h
pod/minio-operator-c57b5d89b-brg64   1/1     Running   0          8h

NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/console    ClusterIP   10.233.3.99     <none>        9090/TCP,9443/TCP   8h
service/operator   ClusterIP   10.233.56.117   <none>        4222/TCP,4233/TCP   8h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/console          1/1     1            1           8h
deployment.apps/minio-operator   1/1     1            1           8h

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/console-6bdcbb8b89         1         1         1       8h
replicaset.apps/minio-operator-c57b5d89b   1         1         1       8h

**# kubectl -n minio get pvc**
NAME                 STATUS   VOLUME                                         CAPACITY   ACCESS MODES   STORAGECLASS     AGE
data0-mt1-pool-0-0   Bound    mapr-pv-b9e6e094-d5ce-4e96-bae8-10446a400bc0   1Gi        RWO            minio-operator   133m
data0-mt1-pool-0-1   Bound    mapr-pv-6d0938f1-ee96-4e5b-902e-6fd4cb0acd49   1Gi        RWO            minio-operator   133m
data0-mt1-pool-0-2   Bound    mapr-pv-6e2f828d-3ff4-4a63-ba77-0dd3e65a7aa4   1Gi        RWO            minio-operator   133m
data0-mt1-pool-0-3   Bound    mapr-pv-b2e9922d-4f14-4efe-939b-808a57438f49   1Gi        RWO            minio-operator   133m

## Expected Behavior
The expectation here is, the tenant containers/pods should work.

## Current Behavior
Current behavior is the tenant pods go into a CrashLoopBackOff state.
Below are the details:
**# kubectl -n minio get tenant**
NAME   STATE                          AGE
mt1    Waiting for Pods to be ready   137m

**# kubectl -n minio get all**
NAME               READY   STATUS             RESTARTS   AGE
pod/dnsutils       1/1     Running            20         20h
pod/mt1-pool-0-0   0/1     CrashLoopBackOff   30         131m
pod/mt1-pool-0-1   0/1     CrashLoopBackOff   30         131m
pod/mt1-pool-0-2   0/1     CrashLoopBackOff   30         131m
pod/mt1-pool-0-3   0/1     CrashLoopBackOff   30         131m

NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/minio    ClusterIP   10.233.47.51   <none>        443/TCP    133m
service/mt1-hl   ClusterIP   None           <none>        9000/TCP   133m

NAME                          READY   AGE
statefulset.apps/mt1-pool-0   0/4     131m

**Below are the logs from the operator pod/container:**
`E0517 15:54:18.171660       1 main-controller.go:742] error syncing 'minio/mt1': MinIO is not ready
I0517 15:54:32.796955       1 http_handlers.go:180] MINIO_ARGS value is https://mt1-pool-0-{0...3}.mt1-hl.minio.svc.k8s.dev.eds/export
I0517 15:54:33.874620       1 http_handlers.go:180] MINIO_ARGS value is https://mt1-pool-0-{0...3}.mt1-hl.minio.svc.k8s.dev.eds/export
I0517 15:54:57.070888       1 http_handlers.go:180] MINIO_ARGS value is https://mt1-pool-0-{0...3}.mt1-hl.minio.svc.k8s.dev.eds/export
Get "https://10.233.81.25:9000/minio/admin/v3/info": dial tcp 10.233.81.25:9000: connect: connection refused
E0517 15:55:39.979536       1 main-controller.go:742] error syncing 'minio/mt1': MinIO is not ready`

Below are the logs from the minio tenant pods:
**# kubectl -n minio logs -f pod/mt1-pool-0-0**
ERROR Invalid command line arguments: path '/export' can not be served by different port on same address
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide

## Your Environment
* Version used (`minio --version`): minio/minio:RELEASE.2021-04-06T23-11-00Z
* Operating System and version (`uname -a`): Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* kubernetes cluster version: v1.18.8
* docker version: Docker version 19.03.12, build 48a66213fe

**Comment by harshavardhana** [comment]
@hemantrevankar this is because your command line is not correct 

> https://mt1-pool-0-{0...3}.mt1-hl.minio.svc.k8s.dev.eds

All your DNS is resolving locally you need to make sure to provide the right values here

```
https://mt1-pool-0-{0...3}.mt1-hl.minio.svc.k8s.dev.eds
```

This might not be the correct CLUSTER_DOMAIN name here - we have seen this with an incorrectly configured system.

**Comment by hemantrevankar** [comment]
@harshavardhana can you help suggest the way to provide the right value through the command line using kubectl minio plugin? I think I am unaware of the option of doing that.

**Comment by harshavardhana** [comment]
> @harshavardhana can you help suggest the way to provide the right value through the command line using kubectl minio plugin? I think I am unaware of the option of doing that.

@hemantrevankar unfortunately no - AFAICS in a proper k8s setup things seem to be working fine. 

> The minio operator is successfully installed in the namespace minio-operator using the kubectl minio init --cluster-domain=k8s.dev.eds

This one are you sure your CLUSTER_DOMAIN is set to `k8s.dev.eds` - if you are unsure you should avoid using `--cluster-domain` command line option.

Also you should upgrade your minio operator seems like your `kubectl minio` plugin needs update.

**Comment by hemantrevankar** [comment]
> This one are you sure your CLUSTER_DOMAIN is set to `k8s.dev.eds` - if you are unsure you should avoid using `--cluster-domain` command line option.
Yes, the cluster domain is k8s.dev.eds. Without passing this option, it defaults to cluster.local and service dns names do not resolve to an IP (results in DNSError) as below:
Error: lookup mt1-pool-0-3.mt1-hl.minio.svc.cluster.local no such host (*net.DNSError)

> Also you should upgrade your minio operator seems like your `kubectl minio` plugin needs update.
the krew plugin says the present one is the latest available.
# kubectl krew upgrade
Updated the local copy of plugin index.
Upgrading plugin: minio
Skipping plugin minio, it is already on the newest version

**Comment by hemantrevankar** [comment]
> This one are you sure your CLUSTER_DOMAIN is set to `k8s.dev.eds` - if you are unsure you should avoid using `--cluster-domain` command line option.

Yes, the cluster domain is k8s.dev.eds. Without passing this option, it defaults to cluster.local and service dns names do not resolve to an IP (results in DNSError) as below:
Error: lookup mt1-pool-0-3.mt1-hl.minio.svc.cluster.local no such host (*net.DNSError)

> Also you should upgrade your minio operator seems like your `kubectl minio` plugin needs update.
the krew plugin says the present one is the latest available.
kubectl krew upgrade
Updated the local copy of plugin index.
Upgrading plugin: minio
Skipping plugin minio, it is already on the newest version

**Comment by harshavardhana** [comment]
> Yes, the cluster domain is k8s.dev.eds. Without passing this option, it defaults to cluster.local and service dns names do not resolve to an IP (results in DNSError) as below:
> Error: lookup mt1-pool-0-3.mt1-hl.minio.svc.cluster.local no such host (*net.DNSError)
> 
> >

Yeah, there is some deeper setup issue @hemantrevankar  I think the DNS domain cannot resolve with '3rd' level for `k8s.dev.sds` can you re-set the cluster to use `cluster.local`?

**Comment by hemantrevankar** [comment]
> I think the DNS domain cannot resolve with '3rd' level for `k8s.dev.sds`

Below is the /etc/resolve.conf entries from within a container in the cluster.
/ # cat /etc/resolv.conf
nameserver 169.254.25.10
search minio.svc.k8s.dev.eds svc.k8s.dev.eds k8s.dev.eds
options ndots:5

Do you see any potential problem with this?

**Comment by harshavardhana** [comment]
> Below is the /etc/resolve.conf entries from within a container in the cluster.
> / # cat /etc/resolv.conf
> nameserver 169.254.25.10
> search minio.svc.k8s.dev.eds svc.k8s.dev.eds k8s.dev.eds
> options ndots:5
> 
> Do you see any potential problem with this?

The problem here is that the DNS resolves but it's not resolving to the correct servers 
all pods are pointing to same host, without any remote access unfortunately I don't see 
what else we can do here.  Sorry

**Comment by chadleeshaw** [comment]
Try completely  removing the search suffixes from /etc/resolv.conf on your bare metal boxes.  Then restart the pods.  Make sure its not in your start up scripts either if this works.
