### ISSUE TITLE
unexpected "mc access " behavior

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#1231]
I am trying to set my bucket public, this feature was available before but now i see this message.

```
$ ./mc  access set public myminio/french-press
mc: <ERROR> Unable to set access permission ‘public’ for ‘myminio/french-press’. A header you provided implies functionality that is not implemented.
```

**Comment by ekozan** [comment]
It's linked to https://github.com/minio/minio-go/issues/340

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/mc/pull/1640

**Comment by harshavardhana** [comment]
This expected and fixed in mc. Closing this.
