### ISSUE TITLE
minio  too slowly remove more smaller files.

### ISSUE THREAD

**Issue by luorixiangyang** [minio/minio#12327]
I put more then 10TB data in minio cluster,  there are 16 drivers,   2.5 TB storage size for each drivers. me set MINIO_STORAGE_CLASS_RRS=EC:2, MINIO_STORAGE_CLASS_STANDARD=EC:2 to get the high avariable storage space to 87%.  After that, my collages  upload  near 20TB data  to it. but we find there have no  remain  space quickly.  We found cost more extranel space size for .minio.sys.  Currently we are hard use commands to summary space cost details. (likely du -sh --max-depth=1 || mc du -r -d 1 ... , will cost long time and no feedback.).  So final we decide to remove some datas ,  but target datas has more small files (near 2KB-8MB), we found cost 5mins-10mins only delete 20000 small files. So how can slove this issue better?

version : RELEASE.2021-04-22T17-40-00Z

**Comment by klauspost** [comment]
@luorixiangyang Optimizing your system is beyond what we do here. 

If you are interested you are welcome to look into our subscription options where we can help you debugging issues with your specific setup: See https://min.io/pricing
