### ISSUE TITLE
Docker  Documentation

### ISSUE THREAD

**Issue by rafael-leo-almeida** [minio/minio#1232]
In Docker.md, the config volume is been mounted on _/.minio_  but after Dockerfile was updated to use _alpine_ image the config folder now is **/root/.minio** in this case docker volume has to be changed.

from:

> docker create -v /export --name minio-export -v **/.minio** --name minio-config minio/my-minio /bin/true

to:

> docker create -v /export --name minio-export -v **/root/.minio** --name minio-config minio/my-minio /bin/true

**Comment by harshavardhana** [comment]
Fixed thanks @rafaelsisweb - btw can you take a look at #1227 and provide your feedback.
