### ISSUE TITLE
Implement support for k8s as alternative to etcd for iam store in gateway

### ISSUE THREAD

**Issue by erlendvollset** [minio/minio#12338]
**Is your feature request related to a problem? Please describe.**
I have a set of microservices which I am deploying on multiple kubernetes clusters (gcp managed, azure managed, openshift). One of our services is a file storage API which uses GCS, Azure blob storage, and Ceph as backing stores in the different clusters. I am currently looking into using the minio gateway in all these clusters and would like to use the STS functionality to provide users with temporary credentials to upload/download specific objects. What I don't want to do is to operate an etcd cluster in addition to the gateway, therefore I would like to request that some alternative to etcd would be implemented as config store for the gateway.

**Describe the solution you'd like**
A k8s-native approach would be ideal. Something along the lines of what patroni has done would be great - some relevant resources:
- https://patroni.readthedocs.io/en/latest/kubernetes.html#kubernetes
- https://github.com/zalando/patroni/blob/master/patroni/dcs/kubernetes.py

Otherwise Postgres would be a nice alternative - we already have postgres clusters readily available in all our k8s environments.

**Describe alternatives you've considered**
- Just operate the etcd cluster and move on
- Implement support for k8s-native or postgres config store ourselves
- Put [tusd](https://github.com/tus/tusd) in front of the minio gateway to enable authorizing uploads using webhooks. This won't work for azure though because the minio gateway is not fully s3-compatible for azure (tusd relies on list multipart uploads)

Looking forward to hearing your thoughts on this topic!

**Comment by harshavardhana** [comment]
etcd usage itself is deprecated, not going to use another alternative here. Keeping things simple no more additional configuration.
