### ISSUE TITLE
open-id error, missing function browser/app/js/browser/utils.js

### ISSUE THREAD

**Issue by bc1000** [minio/minio#12348]
Using actual stable docker container minio/minio and integration with keycloak via Open-ID.
Minio-Button for Open-ID login is defect. Without reaction, javascript error.

## Expected Behavior

use Open-ID button, be redirected to keycloak

## Current Behavior

press open-id button shows following error in browser:

`index_bundle.js:67 Uncaught TypeError: (0 , j.buildOpenIDAuthURL) is not a function
    at M.value (index_bundle.js:67)
    at Object.j (index_bundle.js:33)
    at O (index_bundle.js:33)
    at index_bundle.js:33
    at E (index_bundle.js:33)
    at DM (index_bundle.js:33)
    at TM (index_bundle.js:33)
    at jM (index_bundle.js:33)
    at OM (index_bundle.js:33)
    at G (index_bundle.js:33)`

## Possible Solution

Button without any function "browser/app/js/browser/utils.js" Function was removed!
Using this container, button is fine: minio/minio:RELEASE.2020-10-28T08-16-50Z-38-g7482aa978

## Steps to Reproduce (for bugs)

1. use actual stable docker-container minio/minio
2. integrate with keycloak, OpenID
3.  Try to use Open-ID with minio

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-05-20T22-31-44Z
* Server setup and configuration: docker
* Operating System and version (`uname -a`): docker

**Comment by harshavardhana** [comment]
Embedded browser is not taking anymore feature requests, please start using https://github.com/minio/console
