### ISSUE TITLE
PutObject or MultipartUpload returns NoSuchKey error in minio cluster.

### ISSUE THREAD

**Issue by 3pointer** [minio/minio#12349]
We use the distributed deployment of minio as the objects storage by command:
```
nohup ./minio  server  http://10.0.1.{1...5}/disk{1...24}  > /root/minio.log 2>&1 &      
```
then we have the client execute these apis `put_object` or `create_multipart_upload` `upload_part` `complete_multipart_upload` to minio endpoint `10.0.1.1`.

## Expected Behavior

client receives no error from minio.

## Current Behavior

```
"<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>test/a.sst</Key><BucketName>backup</BucketName><Resource>/backup/test/a.sst</Resource><RequestId>1680CBBFC8B49C</RequestId><HostId>6b07e68e-de8a-401f-bfc3-xxx</HostId></Error>"
```
## Possible Solution

`NoSuchKey` is strange. because we are expected to create this key in the `put_object` or `complete_multipart_upload` function.
After I check the code in `erasure-objects.go` and `erasure-multipart.go`, I found the possible place that throw `NoSuchKey` error is in `readAllFileInfo`. but I have no clue why this could happen.

## Steps to Reproduce (for bugs)

I tried to reproduce in my test environment but failed.
I have tried 5 nodes with 5 disks, but it didn't reproduce.

## Context

We are trying to put our backup to minio cluster.

## Regression

 No

## Your Environment

minio version RELEASE.2021-04-22T15-44-28Z

**Comment by harshavardhana** [comment]
> minio version RELEASE.2021-04-22T15-44-28Z

This has been fixed in later releases @3pointer 

```
~  git tag --contains bb1198c2c6068f5d82fa133976566c8c5845652c
RELEASE.2021-05-11T23-27-41Z
RELEASE.2021-05-16T05-32-34Z
RELEASE.2021-05-17T23-48-24Z
RELEASE.2021-05-18T00-53-28Z
RELEASE.2021-05-20T22-31-44Z
```

**Comment by 3pointer** [comment]
Thanks~ we'll try the latest release.

**Comment by klauspost** [comment]
This will also cause it on rare occasions: https://github.com/minio/minio/pull/12514/files#diff-230273e1e172281fe159ff769077a29d873f50c73fcdf00051ce48cbff4ca479R134
