### ISSUE TITLE
Cannot upload file to sub directory via minio webGUI

### ISSUE THREAD

**Issue by pandan0315** [minio/minio#12352]
When "drag" file to minio webGUI sub directory, it doesn't work

## Expected Behavior

1. add subdirectory "hello" behind "test" bucket in URL.  http://localhost:9000/minio/test/ ->http://localhost:9000/minio/test/hello/
2. drag local file "testput.txt" to test/hello/
3. pop up "file upload successful"

## Current Behavior

1. add subdirectory "hello" behind "test" bucket in URL.  http://localhost:9000/minio/test/ ->http://localhost:9000/minio/test/hello/
2. drag local file "testput.txt" to test/hello/
3. nothing added to /test/hello/

check with log, "PUT /test/hello%2Ftestput.txt HTTP/1.1" 404 ,  it seems "%2F" not decoded to "/"

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2021-03-26T00-00-41Z
* Operating System and version (`uname -a`): Linux 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Mar 25 14:36:04 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You should try https://github.com/minio/console @pandan0315 - embedded browser is not taking anymore feature requests.
