### ISSUE TITLE
Oidc Button does not work

### ISSUE THREAD

**Issue by rodolfototaro** [minio/minio#12354]
Cannot use openid connect button in the Object Browser
## Expected Behavior

starting login flow with identity provider

## Current Behavior

Authentication flow does not start and there happens the following error in the browser console:

index_bundle.js:67 Uncaught TypeError: (0 , j.buildOpenIDAuthURL) is not a function
    at M.value (index_bundle.js:67)
    at Object.j (index_bundle.js:33)
    at O (index_bundle.js:33)
    at index_bundle.js:33
    at E (index_bundle.js:33)
    at DM (index_bundle.js:33)
    at TM (index_bundle.js:33)
    at jM (index_bundle.js:33)
    at OM (index_bundle.js:33)

## Possible Solution

Restore the function in the file browser/app/js/browser/utils.js

export const OPEN_ID_NONCE_KEY = 'openIDKey'

export const buildOpenIDAuthURL = (authEp, authScopes, redirectURI, clientID, nonce) => {
  const params = new URLSearchParams()
  params.set("response_type", "id_token")
  params.set("scope", authScopes.join(" "))
  params.set("client_id", clientID)
  params.set("redirect_uri", redirectURI)
  params.set("nonce", nonce)

  return `${authEp}?${params.toString()}`

Probably something wrong happened during this _commit/revert commit_ and in the file now there is only the licence header 

commit f7a87b30bfe048e52b4bbe5fdece563a20e5c9ba
Author: Harshavardhana <harsha@minio.io>
Date:   Thu Apr 29 19:01:43 2021 -0700

    Revert "deprecate embedded browser (#12163)"
    
    This reverts commit 736d8cbac483d8bf56c3422ca9a9c4c3e043c6cf.
    
    Bring contrib files for older contributions

commit 736d8cbac483d8bf56c3422ca9a9c4c3e043c6cf
Author: Harshavardhana <harsha@minio.io>
Date:   Tue Apr 27 10:52:12 2021 -0700

    deprecate embedded browser (#12163)
    
    https://github.com/minio/console takes over the functionality for the
    future object browser development
    
    Signed-off-by: Harshavardhana <harsha@minio.io>

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Thanks for the report @rtotarocuebiq we shall fix it in next release.

**Comment by harshavardhana** [comment]
Fixed by #12355
