### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by jax79sg** [minio/minio#12366]
TLS doesn't seem to work with docker version of minio. Followed instructions on https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html .

## Expected Behavior

Show that https is enabled.

## Current Behavior

*No https.*
```
Endpoint: http://172.17.0.3:9000  http://127.0.0.1:9000 

Browser Access:
   http://172.17.0.3:9000  *http*://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
IAM initialization complete
```
## Steps to Reproduce (for bugs)

`docker run -d --name minioserver -p 9000:9000 -e MINIO_ROOT_USER=miniouser -e MINIO_ROOT_PASSWORD=miniopassword  -v /mnt/DATA/projects/clearml/minio/certs:/.minio/certs -v /mnt/DATA/projects/clearml/minio/data:/data --restart=always minio/minio  server /data`

mc not found if i run `docker exec minioserver /bin/bash -c "mc admin trace myminio"`

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
docker 19.03
latest minio image

**Comment by harshavardhana** [comment]
> `docker run -d --name minioserver -p 9000:9000 -e MINIO_ROOT_USER=miniouser -e MINIO_ROOT_PASSWORD=miniopassword -v /mnt/DATA/projects/clearml/minio/certs:/.minio/certs -v /mnt/DATA/projects/clearml/minio/data:/data --restart=always minio/minio server /data`

It needs to be 

docker run -d --name minioserver -p 9000:9000 -e MINIO_ROOT_USER=miniouser -e MINIO_ROOT_PASSWORD=miniopassword -v /mnt/DATA/projects/clearml/minio/certs:/root/.minio/certs -v /mnt/DATA/projects/clearml/minio/data:/data --restart=always minio/minio server /data
