### ISSUE TITLE
Support fetching OpenID connect claims from UserInfo endpoint

### ISSUE THREAD

**Issue by bachp** [minio/minio#12367]
**Is your feature request related to a problem? Please describe.**
Some identity prodviders like [GitLab](https://docs.gitlab.com/ce/integration/oauth_provider.html) don't provide information about group membership as part of the identity token. They only expose it via `/oauth/userinfo` endpoint, as described in the [OpenID Connect 1.0](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) sepcification.

**Describe the solution you'd like**
Enable minio to get the claims from the [UserInfo endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) instead of the identity token.

This could be optional and should be configurable.

**Describe alternatives you've considered**

Adding a configuration option to gitlab to support including the groups claim inside the identity token. 

**Additional context**

--

**Comment by antony14110** [comment]
Hello,

I have a minio server and an SSO solution. I can chack the user with the value of the SSO Token, it's work with a value of : "accessKey",  "aud",  "auth_time", "exp", "iat",  "iss",  "jti",  "kid",  "sub" but it's seem to that Minio don't ask the information at userinfo URL of my SSO Solution (but the URL is  set in the .well-known/openid-configuration) . This code is for that feature ?
If yes, when this evolution will be ok in the Minio executable code ?

Thank's for your return.
