### ISSUE TITLE
ETag is not quoted in event notifications

### ISSUE THREAD

**Issue by ghost** [minio/minio#12384]
## Expected Behavior
When receiving an [event notification](https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html), the ETag in the event message should match the ETag returned by e.g. the `PUT` request that triggered the event.

## Current Behavior
When e.g. `PUT`ing an object, the ETag is quoted:
```
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}
```
However, in the event notification sent by MinIO the ETag is not quoted:
```
< some lines omitted >
"object": {
  "key": "foo",
  "eTag": "d41d8cd98f00b204e9800998ecf8427e",
  "contentType": "binary/octet-stream",
  "userMetadata": {
      "content-type": "binary/octet-stream"
  },
  "sequencer": "1682EF292E43090F"
}
< some lines omitted >
```

## Possible Solution
Add quotes to ETag in the event notification body. This should be consistent with AWS behaviour.

## Steps to Reproduce (for bugs)
The bug can be observed using the following small docker compose file:
```
version: "3.8"

services:
  echo:
    image: mendhak/http-https-echo:19

  minio:
    image: minio/minio:RELEASE.2021-05-26T00-22-46Z
    volumes:
      - /data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "storageid"
      MINIO_SECRET_KEY: "storagekey"
      MINIO_NOTIFY_WEBHOOK_ENABLE_TEST: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_TEST: "http://echo:8080"
    command: server /data

  minio-init:
    image: minio/mc:latest
    environment:
      MINIO_ACCESS_KEY: "storageid"
      MINIO_SECRET_KEY: "storagekey"
    entrypoint: |
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 storage http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mb storage/objects/;
      /usr/bin/mc policy set public storage/objects;
      /usr/bin/mc event add storage/objects arn:minio:sqs::TEST:webhook --event put;
      "
    depends_on:
      - minio
```

Run `docker-compose up` and then put an object:
```
export AWS_SECRET_ACCESS_KEY=storagekey
export AWS_ACCESS_KEY_ID=storageid
aws s3api put-object --endpoint-url http://localhost:9000 --bucket objects --key foo
```
The ETag returned by the `aws` command will be quoted, while the ETag printed by the `echo` container will have no quotes (aside from the ones required by the JSON format).

## Context
Since the ETag sent with the event notification does not match the one returned/used by various S3 API calls, trying to use that ETag for comparison or with `If-None-Match` will result in unexpected behaviour. 

This also seems to have been an issue in other areas previously: https://github.com/minio/minio/issues/9517

## Regression
No

## Your Environment
* Version used (`minio --version`): minio/minio:RELEASE.2021-05-26T00-22-46Z container.
* Server setup and configuration: The setup shown in the docker compose file above. 
* Operating System and version (`uname -a`): Linux <hostname> 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@philip-cc https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html#notification-content-structure-examples shows that ETag doesn't have quotes as returned in header in PUT object request. Do you have any AWS notification setup by any chance ?

**Comment by klauspost** [comment]
I don't think etags should be quoted, and I would be rather surprised if MinIO returned quoted etags.

I suspect this is a property of the `aws` command.

**Comment by vadmeste** [comment]
> I don't think etags should be quoted, and I would be rather surprised if MinIO returned quoted etags.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag, this is part of the HTTP spec. But I think Etag is a hash and its real value is without a quote. I just wanted to see how S3 behaves to follow it

**Comment by ghost** [comment]
Just spent some time setting up an S3 bucket with event notifications pointed at my email. Turns out that MinIO does actually mirror S3's behaviour, even if it is a bit weird. 

This is the response headers as given by the `aws` CLI's debug mode for a PUT:
```
DEBUG - Response headers: {'x-amz-id-2': 'Sxrw3ncez/6g3pevAZ1Zu5r9H0nomMAlYrKa6PfK0x2OqUnsp82bKujeEOeWRtzVEFw1FJG1sSs=', 'x-amz-request-id': '0ZE2A7DHJNT7J0G6', 'Date': 'Thu, 03 Jun 2021 12:57:29 GMT', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'Content-Length': '0', 'Server': 'AmazonS3'}
```
As you can see the ETag is quoted.

This is the notification for that event (some stuff omitted):
```
{
  ...
  "Message" : "{\"Records\":[{\"eventVersion\":\"2.1\",\"eventSource\":\"aws:s3\",\"awsRegion\":\"eu-west-3\",\"eventTime\":\"2021-06-03T12:57:27.066Z\",\"eventName\":\"ObjectCreated:Put\",\"userIdentity\":{...},\"requestParameters\":{\"sourceIPAddress\":\"...\"},\"responseElements\":{\"x-amz-request-id\":\"0ZE2A7DHJNT7J0G6\",\"x-amz-id-2\":\"1Zy1ShWViZPaBisyxiu+Rd/ot9A1vZUGvrxsCvN/wNol3tSQGRtI7Ouuok+KJWYBQRo4fnpTmYxj/WYcYb1dLNDMf/7aQurO\"},\"s3\":{\"s3SchemaVersion\":\"1.0\",\"configurationId\":\"test-event\",\"bucket\":{\"name\":\"...\",\"ownerIdentity\":{\"principalId\":\"...\"},\"arn\":\"...\"},\"object\":{\"key\":\"bar\",\"size\":0,\"eTag\":\"d41d8cd98f00b204e9800998ecf8427e\",\"sequencer\":\"0060B8D1B8A467545B\"}}}]}",
  ...
}
```
Here, the ETag is not quoted. Sorry for any inconvenience and feel free to close this issue!

**Comment by vadmeste** [comment]
Thanks @philip-cc, closing this.
