### ISSUE TITLE
Is it support about repliccation bewteen two cluster with gateway mode

### ISSUE THREAD

**Issue by wwyhy** [minio/minio#12389]
Hello,

We'd like to deploy 2 minio cluster with gateway mode on different cloud provider. 

One is Azure with blob storage, another one is Alibaba cloud with OSS stroage.  
And we need configure the replication with "One-Way Server-Side Bucket Replication." 

Is this solution workable？

Thanks!
Br, wwyhy

**Comment by harshavardhana** [comment]
> We'd like to deploy 2 minio cluster with gateway mode on different cloud provider.

No @wwyhy - gateway mode does not support replication.

**Comment by wwyhy** [comment]
@harshavardhana 

Is there any plan to support this or do you have any suggest solution for this senario? thanks!

**Comment by miranlau** [comment]
@harshavardhana 
Seems MinIO server mode only supports the replication between 2 buckets(local or remote) per my understanding.
How can I do if I need the replication between 3 or more buckets?
Please suggest, thanks.

**Comment by harshavardhana** [comment]
> @harshavardhana 
> 
> Is there any plan to support this or do you have any suggest solution for this senario? thanks!

No plans yet @wwyhy

**Comment by harshavardhana** [comment]
> @harshavardhana 
> Seems MinIO server mode only supports the replication between 2 buckets(local or remote) per my understanding.
> How can I do if I need the replication between 3 or more buckets?
> Please suggest, thanks.

Correct we followed AWS S3 spec, once AWS implements we shall follow.

**Comment by olafbuitelaar** [comment]
Being able to replicate over different cloud providers would be a great feature
