### ISSUE TITLE
Minio cluster be shutdown...

### ISSUE THREAD

**Issue by luorixiangyang** [minio/minio#12382]
I build a minio cluster on 16 drviers（each 10TB）:
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0000/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0001/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0002/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0003/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0004/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0005/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0006/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0007/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0008/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0009/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0010/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0011/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0012/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0013/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0014/
drwxrwxrwx  7 root      root         7 5月  21 17:25 163_85_Node_0015/

Here is run bat file:
#!/bin/bash

export MINIO_STORAGE_CLASS_RRS=EC:2
export MINIO_STORAGE_CLASS_STANDARD=EC:2

MINIO_HOST=192.168.10.2

MINIO_HOST_NO1=192.168.10.2

cd `dirname $0`
path=`pwd`

nohup /usr/local/envs/n-minio/minio server --address :9000 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0000 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0001 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0002 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0003 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0004 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0005 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0006 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0007 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0008 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0009 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0010 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0011 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0012 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0013 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0014 \
http://${MINIO_HOST_NO1}/mnt/163_85_Node_0015 > ${path}/../logs/minio-cluster-2-${MINIO_HOST}.log 2>&1 &

current task exception and can't access website http://192.168.10.2:9000,  looking to log file, find some records:
**github.com/minio/minio/cmd.(*timedValue).Get(0xc0014180d8, 0x1337de3eb97, 0x0, 0xc023f05c4b5df611, 0x13368fc13c4)
        github.com/minio/minio/cmd/utils.go:911 +0x53
github.com/minio/minio/cmd.(*xlStorage).DiskInfo(0xc001418000, 0x281bd78, 0xc0000480c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/minio/minio/cmd/xl-storage.go:490 +0x97
github.com/minio/minio/cmd.(*xlStorageDiskIDCheck).DiskInfo(0xc001580000, 0x281bd78, 0xc0000480c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/minio/minio/cmd/xl-storage-disk-id-check.go:214 +0xed
github.com/minio/minio/cmd.erasureObjects.getOnlineDisks.func1(0xc263df8bd0, 0xc2f81f8900, 0x10, 0x10, 0x3, 0xc263df8bb8, 0xc215e07d70)
        github.com/minio/minio/cmd/erasure-common.go:61 +0x117
created by github.com/minio/minio/cmd.erasureObjects.getOnlineDisks
        github.com/minio/minio/cmd/erasure-common.go:56 +0x18c**

 hope you feedback, thanks.

**Comment by luorixiangyang** [comment]
Add some ref infos:

1. It already running normally until 5 days ago, but take the exception today. 
2. The 16 drivers use mount mode from other servers, the file typs is nfs.

please check. thanks.

**Comment by vadmeste** [comment]
@luorixiangyang the log that you pasted seems to be truncated, could you try to paste more larger section if the log ?

**Comment by luorixiangyang** [comment]
> @luorixiangyang the log that you pasted seems to be truncated, could you try to paste more larger section if the log ?

Sorry,  i think i miss some important infos not to supply:
bject API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD'
**IAM initialization complete
runtime: failed to create new OS thread (have 10688 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc**

runtime stack:
runtime.throw(0x1f80073, 0x9)
        runtime/panic.go:1117 +0x72
runtime.newosproc(0xc304a72800)
        runtime/os_linux.go:160 +0x1be
runtime.newm1(0xc304a72800)
        runtime/proc.go:2124 +0xdd
runtime.newm(0x254a7f0, 0xc000057800, 0x29bf)
        runtime/proc.go:2103 +0xa6
runtime.startm(0xc000057800, 0x445f01)
        runtime/proc.go:2334 +0xe5
runtime.handoffp(0xc000057800)
        runtime/proc.go:2379 +0x2ec
runtime.retake(0x4fac2be5fe1b6, 0xc200000001)
        runtime/proc.go:5322 +0x17d
runtime.sysmon()
        runtime/proc.go:5230 +0x185
runtime.mstart1()
        runtime/proc.go:1306 +0xc8
runtime.mstart()
        runtime/proc.go:1272 +0x6e

goroutine 1 [chan receive, 21 minutes]:
github.com/minio/minio/cmd.serverMain(0xc0004fc9c0)
        github.com/minio/minio/cmd/server-main.go:561 +0xadd
github.com/minio/cli.HandleAction(0x1bea520, 0x2547de0, 0xc0004fc9c0, 0xc00071d200, 0x0)
        github.com/minio/cli@v1.22.0/app.go:500 +0xc2
github.com/minio/cli.Command.Run(0x1f7b3c7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1fa674a, 0x1b, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:225 +0x9bb
github.com/minio/cli.(*App).Run(0xc0000e7ba0, 0xc00003a140
....


I guess maybe take MOO issue.

**Comment by harshavardhana** [comment]
> runtime: failed to create new OS thread (have 10688 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

You need to increase your system max process.

> The 16 drivers use mount mode from other servers, the file typs is nfs.

Using NFS with MinIO as backend drive erasure coded setup is not supported.

**Comment by luorixiangyang** [comment]
> erasure coded

[https://docs.min.io/docs/distributed-minio-quickstart-guide.html](https://docs.min.io/docs/distributed-minio-quickstart-guide.html)

Consistency Guarantees
MinIO follows strict read-after-write and list-after-write consistency model for all i/o operations both in distributed and standalone modes. This consistency model is only guaranteed if you use disk filesystems such as **xfs, ext4 or zfs** etc.. for distributed setup.

If MinIO distributed setup is using NFS volumes underneath it is not guaranteed MinIO will provide these consistency guarantees since NFS is not consistent filesystem by design (If you must use NFS we recommend that you atleast use **NFSv4** instead of NFSv3).


So you suggest use ext4 replecement  of  NFS ?

**Comment by luorixiangyang** [comment]
> > runtime: failed to create new OS thread (have 10688 already; errno=11)
> > runtime: may need to increase max user processes (ulimit -u)
> > fatal error: newosproc
> 
> You need to increase your system max process.
> 
> > The 16 drivers use mount mode from other servers, the file typs is nfs.
> 
> Using NFS with MinIO as backend drive erasure coded setup is not supported.

How about cifs file type?

**Comment by harshavardhana** [comment]
> So you suggest use ext4 replecement of NFS ?

XFS @luorixiangyang - no network filesystems, please.
