### ISSUE TITLE
server "hello" message does not show correct key and secret if overridden

### ISSUE THREAD

**Issue by finlay** [minio/minio#1240]
If you override the access key and secret key, for example with ENV variables in the following Dockerfile:

```
FROM minio/minio:latest

ENV MINIO_ACCESS_KEY=2G45L38FAPM2O95NCXFR
ENV MINIO_SECRET_KEY=zuftfteSlswRu7BJ86wekitnifILbZam1KYY3TGx
```

The message displayed shows the randomly generated ones. However, the server is respecting them.

**Comment by harshavardhana** [comment]
Fixed by #1241
