### ISSUE TITLE
Unable to list s3 bucket using minio client

### ISSUE THREAD

**Issue by albertsebastian1** [minio/minio#12405]
## Expected Behavior

mc ls mybucket/ should list the contents.

## Current Behavior

Able to make bucket using mc mb.
Not able to list bucket using mc ls

## Steps to Reproduce (for bugs)

1. Install minio client on an ubuntu VM
2. Configure alias with s3 endpoint, access key and secret access key
3. Ensure the user has required s3 permissions attached to IAM
4. create bucket using mc mb ( working )
5. **List the content of bucket after copying files  - Not Working** ( HTTP response is 200OK )
## Your Environment

* Version used (`minio --version`):  Minio Client Version:  RELEASE.2021-04-22T17-40-00Z, RELEASE.2021-05-26T19-19-26Z
* Minio Version : RELEASE.2020-04-28T23-56-56Z
* Server setup and configuration: 
* Tried both in standalone VM and AWS EKS cluster
* IAM permissions set : S3FullAccess and also tried with custom policy with below permissions 
*  "s3:ListBucketMultipartUploads",
                "s3:ListBucketVersions",
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:GetBucketAcl",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:PutObjectVersionAcl",
                "s3:GetObjectVersionAcl",
                "s3:PutBucketAcl",
                "s3:GetBucketLocation",
                "s3:PutObjectAcl",
                "s3:GetObjectVersion"

* Operating System and version (`uname -a`): Ubuntu 18.04 , x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
@albertsebastian1 Please upgrade to the latest version. When you have done so, if the issue still reproduces, post the output from  `mc ls --debug myminio`.

**Comment by albertsebastian1** [comment]
> @albertsebastian1 Please upgrade to the latest version. When you have done so, if the issue still reproduces, post the output from `mc ls --debug myminio`.

Thanks for the get back @klauspost . Please find below debug output from standalone ec2 VM to s3 bucket ls call

./mc ls testuserstore/testuser2/ --debug
mc: <DEBUG> GET /testuser2/?location= HTTP/1.1
Host: xxxxxxxxxxmybucket.s3.us-east-2.amazonaws.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-05-26T19-19-26Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210601/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210601T024704Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 01 Jun 2021 02:47:04 GMT
Server: AmazonS3
X-Amz-Id-2: /hWA/xxxxxxxxxxmybucket
X-Amz-Request-Id: xxxxxxxxxxmybucket

16d
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'</Message><Region>us-east-2</Region><RequestId>xxxxxxxxxxmybucket</RequestId><HostId>xxxxxxxxxxmybucket</HostId></Error>
0
**Please note we have corrected the above default region issue by setting env variable inside the pod**


mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: DigiCert Inc
mc: <DEBUG>  >> Expires: 2022-01-18 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: IE
mc: <DEBUG>  >> Organization: Baltimore
mc: <DEBUG>  >> Expires: 2025-05-10 12:00:00 +0000 UTC
mc: <DEBUG> Response Time:  23.370466ms

mc: <DEBUG> GET /testuser2/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
Host: xxxxxxxxxxmybucket.s3.us-east-2.amazonaws.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-05-26T19-19-26Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210601/us-east-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: xxxxxxxxxxmybucketsha
X-Amz-Date: 20210601T024704Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 153
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Date: Tue, 01 Jun 2021 02:47:05 GMT
Etag: "b95c6c46ea8203dd0db622cdc5900277"
Last-Modified: Tue, 01 Jun 2021 02:46:43 GMT
Server: AmazonS3
X-Amz-Id-2: xxxxxxxxxxmybucketid
X-Amz-Request-Id: xxxxxxxxxxmybucketid

mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: DigiCert Inc
mc: <DEBUG>  >> Expires: 2022-01-18 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found:
mc: <DEBUG>  >> Country: IE
mc: <DEBUG>  >> Organization: Baltimore
mc: <DEBUG>  >> Expires: 2025-05-10 12:00:00 +0000 UTC
mc: <DEBUG> Response Time:  45.1471ms

**Please note we are getting same response from EKS mc pod as well**

**Comment by albertsebastian1** [comment]
@klauspost Please find below details 

**Minio Version: RELEASE.2021-05-27T22-06-31Z**
**Minio Client Version: RELEASE.2021-04-22T17-40-00Z**

./mc ls mybucket/ --debug
mc: <DEBUG> GET / HTTP/1.1
Host: my-minio-host:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-04-22T17-40-00Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210601/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: xxxxxxx-X-AMz
X-Amz-Date: 20210601T095124Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 275
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 01 Jun 2021 09:51:24 GMT
Server: MinIO
Vary: Origin
X-Amz-Bucket-Region: us-east-2
X-Amz-Request-Id: 16846C8515AB30C2
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  228.876062ms

**Comment by harshavardhana** [comment]
As you can see from your policy GetBucketLocation is not authorized if you don't authorize it then you need to manually specify the region name using MC_REGION=us-east-2

**Comment by albertsebastian1** [comment]
> As you can see from your policy GetBucketLocation is not authorized if you don't authorize it then you need to manually specify the region name using MC_REGION=us-east-2

@harshavardhana  I have tried listing bucket **after exporting MC_REGION**. Still the issue is not resolved. Please check below 

![image](https://user-images.githubusercontent.com/18263817/120345955-91579680-c318-11eb-9eea-df996aae984e.png)

**Comment by harshavardhana** [comment]
> > As you can see from your policy GetBucketLocation is not authorized if you don't authorize it then you need to manually specify the region name using MC_REGION=us-east-2
> 
> @harshavardhana I have tried listing bucket **after exporting MC_REGION**. Still the issue is not resolved. Please check below
> 
> ![image](https://user-images.githubusercontent.com/18263817/120345955-91579680-c318-11eb-9eea-df996aae984e.png)

There is no issue here - you have ended up specifying bucket name as part of your endpoint URL in `mc` - if you do that then you will not be able to ListBuckets() since your alias directly points to your bucket name.

**Comment by albertsebastian1** [comment]
> > > As you can see from your policy GetBucketLocation is not authorized if you don't authorize it then you need to manually specify the region name using MC_REGION=us-east-2
> > 
> > 
> > @harshavardhana I have tried listing bucket **after exporting MC_REGION**. Still the issue is not resolved. Please check below
> > ![image](https://user-images.githubusercontent.com/18263817/120345955-91579680-c318-11eb-9eea-df996aae984e.png)
> 
> There is no issue here - you have ended up specifying bucket name as part of your endpoint URL in `mc` - if you do that then you will not be able to ListBuckets() since your alias directly points to your bucket name.

@harshavardhana  Thanks for pointing this out. Please check below mc alias config. If this is wrong, what is your suggestion please ? 

![image](https://user-images.githubusercontent.com/18263817/120347941-57878f80-c31a-11eb-81a5-6084031d5bc2.png)

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for pointing this out. Please check below mc alias config. If this is wrong, what is your suggestion please ?

It should look like this

```
mc alias list s3
s3
  URL       : https://s3.amazonaws.com
```

**Comment by albertsebastian1** [comment]
> > @harshavardhana Thanks for pointing this out. Please check below mc alias config. If this is wrong, what is your suggestion please ?
> 
> It should look like this
> 
> ```
> mc alias list s3
> s3
>   URL       : https://s3.amazonaws.com
> ```

Thanks @harshavardhana . I am able to  list **all** buckets after making the suggested correction in the alias s3 Endpoint URL. 

Trying to figure out a way to point an alias  to a specific bucket.
