### ISSUE TITLE
Allow to use aws:username for admin: policy actions

### ISSUE THREAD

**Issue by markovendelin** [minio/minio#12401]
**Related problem**

I would like to allow MinIO users to create other users with separate secret keys. The user-controlled sub-users could be used
in different environments and have more limited access with the separate policies. For example, each backup PC could have a dedicated user with the dedicated bucket(s). Thus, if something would end up leaking login info on that PC, the damage would be limited to the data controlled from it.

**Describe the solution you'd like**

Already now, it looks like having policy in the form

```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}-*"
            ]
        }
    ]
}
```

allows me to create namespace of buckets prefixed with the username. As a result, users can do whatever they need to with these buckets, including creating and destroying them.

I would like to have ability to create, list, and destroy users using similar policy

```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:CreateUser",
                "admin:DeleteUser",
                "admin:ListUsers"
            ],
            "Resource": [
                "arn:aws:iam:::${aws:username}-*"
            ]
        }
    ]
}
```

**Describe alternatives you've considered**

Haven't found any.

**Comment by harshavardhana** [comment]
Thre are no resources for `admin:*` APIs @markovendelin there is no restriction as such for them.

**Comment by markovendelin** [comment]
Thank you for fast reply! Let me ask then differently - is there a way to make a policy like that? Whether using resources or maybe there are some conditions that can be specified?

**Comment by markovendelin** [comment]
@harshavardhana:  Thinking of it, `admin:*` is MinIO own API and it has no compatibility implied with S3. So, as a feature request, it makes sense to ask for extension of it. Whether to go on and extend is a different story and depends on developers priorities. However, the absence of resources in the current API should not be something leading to the closure of the feature request.

**Comment by harshavardhana** [comment]
> @harshavardhana:  Thinking of it, `admin:*` is MinIO own API and it has no compatibility implied with S3. So, as a feature request, it makes sense to ask for extension of it. Whether to go on and extend is a different story and depends on developers priorities. However, the absence of resources in the current API should not be something leading to the closure of the feature request.

There are no resources present in admin API - so it doesn't make sense to add it.

We may do it in future if needed. So this issue is closed since there are no immediate requirements.
