### ISSUE TITLE
[single drive mode] prometheus metrics for disks online/offline and cluster capacity are broken 

### ISSUE THREAD

**Issue by zagr0** [minio/minio#12414]
For normally ran and working standalone minio server `minio server --certs-dir /certs --address :9000 /data`, disk's status info and prometheus metrics are reported wrong:
`minio_cluster_disk_offline_total` - 1
`minio_cluster_disk_online_total` - 0
`minio_cluster_capacity_usable_free_bytes` - NaN
`minio_cluster_capacity_usable_total_bytes` - NaN

the others metrics seams fine

MinIO Client also does not show disk info properly (its missing in the output)
```
$ mc admin info local
●  localhost:9000
   Uptime: 3 hours 
   Version: 2021-05-28T00:23:41Z
   Network: 1/1 OK 

209 KiB Used, 2 Buckets, 2 Objects
```

## Expected Behavior
prometheus metrics to provide usable capacity and disks online/offline metrics properly

## Steps to Reproduce (for bugs)
Actually I'm running minio with [bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/minio)
1. run `/opt/bitnami/minio/bin/minio server --certs-dir /certs --address :9000 /data`
2. get info with `mc admin info local`
3. scrape metrics `curl http://localhost:9000/minio/v2/metrics/cluster`

## Your Environment

* Version used (`minio --version`):
minio version DEVELOPMENT.2021-05-28T00-23-41Z
* Client version used (`mc -v`):
mc version DEVELOPMENT.2021-05-27T14-06-49Z
* Server setup and configuration:
minio ran in k8s - GKE
/data mounted as PV
```
$ mount |grep /data
/dev/sdb on /data type ext4 (rw,relatime)
```
* Operating System and version (`uname -a`):
$ uname -a       
Linux minio-7f8566b759-84mt2 5.4.89+ #1 SMP Sat Feb 13 19:45:14 PST 2021 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
These metrics are not meant for single node setups @zagr0 but we should ignore them anyways.

**Comment by zagr0** [comment]
the most confusing thing is that offline disk is reported - indicates for an issue
capacity metrics are not available (but raw are shown) and this is not obvious

have not found anything reg that in documentation, but of course would be really great to not have offline disk reported

**Comment by harshavardhana** [comment]
> the most confusing thing is that offline disk is reported - indicates for an issue
> capacity metrics are not available (but raw are shown) and this is not obvious
> 
> have not found anything reg that in documentation, but of course would be really great to not have offline disk reported

All the information here is meant for erasure coded deployments and should be simply ignored for single drive setups.
