### ISSUE TITLE
arm64 bitrot miscaculation issue due to some asm changes

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#12413]
After that I started from scratch using version RELEASE.2021-03-01T04-20-55Z
Now I'm having the same issue again while upgrading to newest version.

I did many tests on a lab installation and could locate RELEASE.2021-03-26T00-00-41Z as relevant.
Updates to versions before that are ok.
Updates to versions after fail.
When I start from scratch with RELEASE.2021-03-26T00-00-41Z updates to newest are ok.

Seems that this could be related to #11901
"on arm64 (on Go 1.16) wrong hash values got computed due to incorrectly naming asm constants like regular Go functions"
@harshavardhana this could also be the reason why you could not reproduce the issue, it is arm64 specific.

As far as I can see the corruption happens only in the metadata, especially .metacache folder.

Is there a chance to recreate or rebuild the metadata after update without without damaging the uploaded files?

Attached are all files from the lab installation before and after update (RELEASE.2021-03-17T02-33-02Z --> RELEASE.2021-03-26T00-00-41Z)
[before-after.zip](https://github.com/minio/minio/files/6576010/before-after.zip)

_Originally posted by @Woidla27 in https://github.com/minio/minio/issues/11627#issuecomment-852065659_

**Comment by justinclift** [comment]
Sounds like this is an _extremely_ bad problem, and there should be some way to detect the bad calculation (eg keep the code around in a callable function), then re-write it with the correct hash value.

**Comment by harshavardhana** [comment]
> Sounds like this is an _extremely_ bad problem, and there should be some way to detect the bad calculation (eg keep the code around in a callable function), then re-write it with the correct hash value.

These sanity checks are already present in all newer releases this was an internal issue to track upgrades and figure out if there is something more we can do to help @justinclift

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by loyalPlayer** [comment]
I met this problem today and I found that these data works ok if downgrade to minio version used before. I don't know it's whether useful for this problem. Is it possible to read corrupted data by downgrade minio version in this scenario?  Export data after downgrade then import data after upgrade

https://github.com/minio/minio/issues/12943

**Comment by harshavardhana** [comment]
> I met this problem today and I found that these data works ok if downgrade to minio version used before. I don't know it's whether useful for this problem. Is it possible to read corrupted data by downgrade minio version in this scenario? Export data after downgrade then import data after upgrade

That's the only way out of ARM64 issue.

**Comment by klauspost** [comment]
@loyalPlayer No. The solution is to upgrade beyond the problematic version.

**Comment by justinclift** [comment]
k, so who's correct?

**Comment by harshavardhana** [comment]
> @loyalPlayer No. The solution is to upgrade beyond the problematic version.

@klauspost ^^

**Comment by loyalPlayer** [comment]
> @loyalPlayer No. The solution is to upgrade beyond the problematic version.

@klauspost You're right in my case which from 2020-10-28 to 2021-03-17, I upgrade beyond the problematic version and solve the problem. Thank you so much with deeply grateful ^v^

I think case of this issue 12413 differs from my case , its base version is RELEASE.2021-03-01T04-20-55Z with arm64 bitrot miscaculation, It works ok with a arm64 bitrot miscaculation when bucket was created in version RELEASE.2021-03-01T04-20-55Z. But when upgrade to correct version, minio of new version with correct arm64 bitrot caculation cannot reach data generated by arm64 bitrot miscaculation in version RELEASE.2021-03-01T04-20-55Z. However, if you downgrade it back to RELEASE.2021-03-01T04-20-55Z,  data generated by arm64 bitrot miscaculation of old version would become reachable again.At the same time, data created by correct arm64 bitrot caculation would become unreachable.

I just downloaded these version (RELEASE.2021-03-01T04-20-55Z, RELEASE.2021-03-26T00-00-41Z) and verified that they are indeed the case.
