### ISSUE TITLE
One server memory is more high than other server

### ISSUE THREAD

**Issue by invent-lwj** [minio/minio#12428]
minio version: minio-RELEASE.2021-04-22T15-44-28Z
cluster info: 28 servers, Centos7 os, each server have 12 disks, 11 pools of EC set size is 16, 10 pools of EC size is 12
My problem is one server memory is more than others, i check memory by `top` 
This is pprof files. Thanks!
[13profiles.tar.gz](https://github.com/minio/minio/files/6591153/13profiles.tar.gz)

**Comment by klauspost** [comment]
MinIO will hold a number of buffers ready for writes. Up to 1 GB.

This server has responsible for scanning and saved some data. These buffers are kept around. You can upgrade to the latest version and it should reduce the memory usage of the scanner.
