### ISSUE TITLE
MINIO_STORAGE_CLASS_STANDARD  and  MINIO_STORAGE_CLASS_RRS   Doesn't  work

### ISSUE THREAD

**Issue by jicki** [minio/minio#12438]
## Expected Behavior

```
http://minio-{1...4}/export{1...9}

```

```
set  
MINIO_STORAGE_CLASS_STANDARD="EC:18"
MINIO_STORAGE_CLASS_RRS="EC:9"

```

```
mc admin config get s3 storage_class

storage_class standard= rrs=EC:2 dma=read+write
```

**Comment by vadmeste** [comment]
@jicki please follow the issue template next time.

If I understood correctly, you expect that `mc admin config get` to show numbers set by environment variables, but this is not expected. `mc admin config get` will only show values set by `mc admin config set`. Maybe we need to add another command which shows environment variables set in MinIO environment.

**Comment by jicki** [comment]
> @jicki please follow the issue template next time.
> 
> If I understood correctly, you expect that `mc admin config get` to show numbers set by environment variables, but this is not expected. `mc admin config get` will only show values set by `mc admin config set`. Maybe we need to add another command which shows environment variables set in MinIO environment.

yes 

In addition, how do I view obj data information, data and parity

ps:  sorry my english is very bad

**Comment by harshavardhana** [comment]
> http://minio-{1...4}/export{1...9}

With 4 nodes and 9 drives check what is the maximum parity allowed for your setup, https://min.io/product/erasure-code-calculator 

Also, read our documentation here https://github.com/minio/minio/tree/master/docs/distributed
