### ISSUE TITLE
"s3cmd get"  response header from minio doesnt contain etag for md5

### ISSUE THREAD

**Issue by jsat97** [minio/minio#1243]
Invoked as: /usr/bin/s3cmd -d get s3://testbucket/file1 junk
Problem: KeyError: 'etag'
S3cmd:   1.6.1
python:   2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 548, in cmd_object_get
    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 647, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 1476, in recv_file
    md5_from_s3 = response["headers"]["etag"].strip('"')    <<<<<<<<
KeyError: 'etag'

relevant debug output from s3cmd --

download: 's3://testbucket/file1' -> 'junk'  [1 of 1]
DEBUG: get_hostname(testbucket): localhost:9000
DEBUG: ConnMan.get(): creating new connection: http://localhost:9000
DEBUG: non-proxied HTTPConnection(localhost:9000)
DEBUG: format_uri(): /testbucket/file1
DEBUG: Response: {'status': 200, 'headers': {'content-length': '102400', 'accept-ranges': 'bytes', 'vary': 'Origin', 'server': 'Minio/RELEASE.2016-03-11T03-45-50Z (linux; amd64)', 'last-modified': 'Thu, 17 Mar 2016 15:13:12 GMT', 'x-amz-request-id': 'JY1L1W4UXUI3VEYM', 'date': 'Thu, 17 Mar 2016 17:02:18 GMT', 'content-type': 'application/octet-stream'}, 'reason': 'OK'}
   4096 of 102400     4% in    0s   788.49 kB/sDEBUG: ConnMan.put(): connection put back to pool (http://localhost:9000#1)
 102400 of 102400   100% in    0s    14.55 MB/s  done

**Comment by harshavardhana** [comment]
Thanks @jsat97

**Comment by harshavardhana** [comment]
https://github.com/s3tools/s3cmd/pull/720 - a possible fix to avoid crash is pushed.
