### ISSUE TITLE
Minio with S3 storage : Error bucket name does not follow Amazon S3 standards

### ISSUE THREAD

**Issue by albertsebastian1** [minio/minio#12433]
I have one application running on both Azure AKS and AWS EKS which internally writes files to Mino whose storage is Azure Storage Account and AWS S3 respectively. Currently everything is working as expected with Azure storage account whereas in the s3 backed Minio , the application is not able to locate a folder inside an s3 bucket and write files into that.  When we try to set the bucket name as mybucket/myfolder its not allowing and returns error

mybucket\\myfolder : bucket name does not follow Amazon S3 standards. For more information refer http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

## Expected Behavior

The Java application should start writing files to **mybucket/myfolder** in AWS S3

## Current Behavior

mybucket\\myfolder : bucket name does not follow Amazon S3 standards. For more information refer http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> I have one application running on both Azure AKS and AWS EKS which internally writes files to Mino whose storage is Azure Storage Account and AWS S3 respectively. Currently everything is working as expected with Azure storage account whereas in the s3 backed Minio , the application is not able to locate a folder inside an s3 bucket and write files into that. When we try to set the bucket name as mybucket/myfolder its not allowing and returns error

Using bucket name as `mybucket/myobject` is unexpected - you need provide bucketName separately and then provide object dir as `myobjectdir/` for object Name. 

This is not an issue just your coding bug.
