### ISSUE TITLE
[question] How to get arn address

### ISSUE THREAD

**Issue by invent-lwj** [minio/minio#12434]
I establish minio cluster on local machine, i want to get event of a bucket, this command must input ARN, how to get it? Thanks!
```
EXAMPLES:
  1. Enable bucket notification with a specific ARN
    $ mc event add myminio/mybucket arn:aws:sqs:us-west-2:444455556666:your-queue
```

**Comment by harshavardhana** [comment]
@invent-lwj  follow the docs here https://docs.min.io/docs/minio-bucket-notification-guide.html
