### ISSUE TITLE
Users inconsistency across the cluster.

### ISSUE THREAD

**Issue by kollisaisriharsha** [minio/minio#12441]
Expect all the servers in the cluster to return the same number of users when called ('mc admin user list myminio')

## Expected Behavior

Users on the server get removed after the service is restarted.

## Current Behavior

When I do an `mc admin user list` on multiple servers of the same cluster the servers give a different responses on some servers.
I.e lets say we have 45 users on the cluster, some servers of the cluster only show 22

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Users started reporting that they are not able to access MinIO buckets that they have access to earlier. When we checked in some cases the users are missing on some machines and in some cases, the policies attached are missing.
Screenshots for users missing on some machines: 
![image](https://user-images.githubusercontent.com/28617024/120801961-7dea3c80-c55f-11eb-84a0-3b8b0e53f6c5.png)

Screenshots for policies missing on some machines:
![image](https://user-images.githubusercontent.com/28617024/120802118-b0943500-c55f-11eb-9c6c-afab58ab8a4c.png)

## Your Environment

* Version used (`minio --version`): RELEASE.2021-05-27T22-06-31Z
* Server setup and configuration: distributed MinIO running on bear-metal servers. (20 machines 10 disk each)
* Operating System and version (`uname -a`): Linux minio20 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@kollisaisriharsha most likely you have some logs indicating issues loading IAM users, could you upload all your servers logs ?

**Comment by kollisaisriharsha** [comment]
@vadmeste, we have one other issue on the cluster for which I created another ticket and just uploaded a full log file there.
This is the link https://github.com/minio/minio/issues/12443#issuecomment-854778547.
Please let me know if you need any other data here.

Thank you!

**Comment by harshavardhana** [comment]
> @vadmeste, we have one other issue on the cluster for which I created another ticket and just uploaded a full log file there.
> This is the link [#12443 (comment)](https://github.com/minio/minio/issues/12443#issuecomment-854778547).
> Please let me know if you need any other data here.
> 
> Thank you!

That is the main reason why you are seeing this error.  Both issues are same here..
