### ISSUE TITLE
 TCP: out of memory -- consider tuning tcp_mem

### ISSUE THREAD

**Issue by mazataza** [minio/minio#12440]
we have four minio servers
after updating all server to the version 2021-05-27T22:06:31Z we got high load and from time to time we got following messages in kern.log 

 TCP: out of memory -- consider tuning tcp_mem

i tried using the script here but the issue still happend.
https://github.com/minio/minio/blob/master/docs/deployment/kernel-tuning/sysctl.sh

let me know what info you need and how to help.

**Comment by harshavardhana** [comment]
This is unrelated to MinIO, I don't know why this is opened here.

If you are pushing server to limits you need to increase your tcp buffers or add memory to the system.
