### ISSUE TITLE
Invalid UI version in the JSON-RPC response

### ISSUE THREAD

**Issue by ThyrixYang** [minio/minio#12450]
Hi,

I just tied the following command
```
docker run \
	-p 9000:9000 \
	--env MINIO_ROOT_USER=user \
	--env MINIO_ROOT_PASSWORD=9iYcPasdfafsafccDlyPcz \
	minio/minio:edge \
	server /data
```
and open the browser with url: http://127.0.0.1:9000
When I try to log in using the user name and password, the browser shows the following error message
`Invalid UI version in the JSON-RPC response`
and I can't log in.

I'm not sure whether the MINIO_ROOT_USER and MINIO_ROOT_PASSWORD is the access key and secret key. If they are, is this a bug?

---

Edit: I found that use the stable version solves this error.
```
docker run \
	-p 9000:9000 \
	--env MINIO_ROOT_USER=user \
	--env MINIO_ROOT_PASSWORD=9iYcPasdfafsafccDlyPcz \
	minio/minio \
	server /data
```
so I think this is a bug in the edge version.

**Comment by harshavardhana** [comment]
This is because edge has UI version set to DEVELOPMENT.GOGET
