### ISSUE TITLE
respHeaders in Params, Why not in headers

### ISSUE THREAD

**Issue by rupamking1** [minio/minio#12457]
presignedGetObject respHeaders in Params, Why not in headers,
because Params is not encrypted in https but headers is encrypted in https.

how to pass respHeaders Object via headers? Please answer me...

don't close issue without answer

**Comment by klauspost** [comment]
1) The issue was moved to discussion
2) This does not appear to have anything to do with the minio server. If you are using an SDK, open the issue there.
3) If you want to have dedicated support, look into our [support options](https://min.io/pricing)
