### ISSUE TITLE
Lifecycle Policy - objects not deleted from disk after expiration

### ISSUE THREAD

**Issue by gsalaz98** [minio/minio#12462]
## Expected Behavior

Lifecycle policy expiration deletes object(s) from MinIO host's disk after the lifecycle policy's expiry days have elapsed

## Current Behavior

Object remains on host's disk after the lifecycle expiry days have elapsed. Some commands result in the deletion of the expired objects, but not all commands do (list-objects-v2 for example does not delete the object).
## Possible Solution

N/A
## Steps to Reproduce (for bugs)

Note: time of writing is 2021-06-08 01:21:00 UTC, objects have since crossed their lifecycle expiry time/date.
Note: endpoint URL pointing to MinIO instance is removed from AWS CLI examples to keep example commands short

Existing lifecycle policy:
```
[root@c7af30a3136b /]# mc ilm ls data2/bucket
          ID          |     Prefix     |  Enabled   | Expiry |  Date/Days   |  Transition  |    Date/Days     |  Storage-Class   |          Tags          
----------------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------------
 c2v5850mqraj34bnnbi0 |                |    ✓       |  ✓     |   2 day(s)   |     ✗        |                  |                  |                        
----------------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------------
```

```
[root@c7af30a3136b /]# aws s3api get-bucket-lifecycle-configuration --bucket bucket
{
    "Rules": [
        {
            "Expiration": {
                "Days": 2
            },
            "ID": "c2v5850mqraj34bnnbi0",
            "Filter": {
                "Prefix": ""
            },
            "Status": "Enabled"
        }
    ]
}
```
Running the following commands from remote hosts indicate that the object exists:

```
[root@c7af30a3136b /]# mc ls data2/bucket/20210605/
...
[2021-06-05 20:02:00 UTC] 1.7MiB 20210605_a44f1c9d.tar
[2021-06-05 21:02:01 UTC] 1.7MiB 20210605_dfdded1e.tar
```

```
[root@c7af30a3136b /]# aws s3 ls s3://bucket/20210605/20210605_dfdded1e.tar
2021-06-05 14:02:01    1730560 20210605_dfdded1e.tar
```

```
[root@c7af30a3136b /]# aws s3api list-objects-v2 --bucket transfer --prefix 20210605/20210605_dfdded1e.tar
{
    "Contents": [
        {
            "Key": "20210605/20210605_dfdded1e.tar",
            "LastModified": "2021-06-05T21:02:01.433Z",
            "ETag": "\"7e445193617eadf778213cf9afd98f73\"",
            "Size": 1730560,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "minio",
                "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
            }
        }
    ]
}
```

However, when we go to get more information on the object itself, the expired object does get deleted from the MinIO host's disk.

1. Run `ls -la` in the path the object resides in, demonstrating that it exists on disk in host (`transfer` is the directory that contains all buckets for this host)
```
[root@miniohost /transfer/bucket/20210605]# ls -la
...
-rw-r--r-- 1 root root    1730560 Jun  5 21:02 20210605_dfdded1e.tar
```

2. Try to stat the object to view lifecycle expiry date/other information
```
[root@c7af30a3136b /]# mc stat data2/bucket/20210605/20210605_dfdded1e.tar
mc: <ERROR> Unable to stat `data2/bucket/20210605/20210605_dfdded1e.tar`. Object does not exist.

# OR, you can run this command and it will result in the same behavior:

[root@c7af30a3136b /]# mc ls data2/bucket/20210605/20210605_a44f1c9d.tar
[root@c7af30a3136b /]# $?
bash: 0: command not found
```

3. List objects in host again, object has been deleted after running the previous command
```
[root@miniohost /transfer/bucket/20210605]# stat 20210605_dfdded1e.tar
stat: cannot stat '20210605_dfdded1e.tar': No such file or directory

[root@miniohost /transfer/bucket/20210605]# stat 20210605_a44f1c9d.tar
stat: cannot stat '20210605_a44f1c9d.tar': No such file or directory
```

Earlier today, I ran `mc stat` on one of the objects that has since been expired (and deleted using a command listed in step 2). This is the output I received earlier today:

```
[root@c7af30a3136b /]# mc stat data2/bucket/20210605/20210605_227fbba2.tar
Name      : 20210605_227fbba2.tar
Date      : 2021-06-05 23:02:37 UTC 
Size      : 1.7 MiB 
ETag      : 0b2f5c647c8dc381c4121682bc9a0d3b 
Type      : file 
Expiration: 2021-06-08 00:00:00 UTC (lifecycle-rule-id: c2v5850mqraj34bnnbi0) 
Metadata  :
  Content-Type: application/x-tar
```

## Context

Objects aren't cleaned up from host disk automatically, resulting in build-up of disk space usage

## Regression

Unknown
## Your Environment

```
[root@c7af30a3136b /]# mc admin info data2
●  data2.<domain>.com
   Uptime: 4 days 
   Version: 2021-05-27T22:06:31Z
   Network: 1/1 OK 
```

```
[root@qc-data-2 /]# minio --version
minio version RELEASE.2021-05-27T22-06-31Z
```

```
[root@qc-data-2 /]# uname -a
Linux qc-data-processing-node-2 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vadmeste** [comment]
@gsalaz98 if you have a lot number of objects in your cluster, then it could take more time than expected for the lifecycle to detect and remove objects. Lifecycle depends on the speed of the scanner as well. So you may want to increase the scanner speed as well.

**Comment by gsalaz98** [comment]
@vadmeste we have very few objects stored in the bucket. There were about 240 objects in the bucket when I created the issue.

This is the scanner configuration that's currently being used (default):

```
[root@c7af30a3136b /]# mc admin config get data2/ scanner
scanner delay=10 max_wait=15s cycle=1m 
```

The MinIO instance is idle for majority of the time, especially around 00:00:00 UTC

Also, the objects mentioned yesterday are still on disk and haven't been cleaned up overnight

**Comment by harshavardhana** [comment]
This looks like a bug @gsalaz98 - are you running in a single drive mode? - what is your server version?

**Comment by gsalaz98** [comment]
Yes, we're running on a single drive, and via docker as well.

The server version is `minio version RELEASE.2021-05-27T22-06-31Z`

**Comment by harshavardhana** [comment]
Yeah that is because you are affected by this #12432 and you should upgrade to latest release @gsalaz98

**Comment by gsalaz98** [comment]
I've upgraded to `2021-06-07T21-40-51Z` now, and the scanner deleted all of the expired data :tada: 

Thank you so much for the responsiveness & help, I truly appreciate it. Closing now since the issue has been resolved with a MinIO version upgrade :slightly_smiling_face:
