### ISSUE TITLE
Distributed lock that blocks a certain session

### ISSUE THREAD

**Issue by evt-byte** [minio/minio#12472]
When using Python SDK to upload files, params `part_size` 5m, num_parallel_uploads = 3, upload file size is 200m, performance is very slow.

## Steps to Reproduce (for bugs)

1.tcp dump
2.mc admi trace
3.mc cp
4.analysis

## Context

Minio is deployed in distributed mode and there is a distributed lock for a certain object. Once minio receive a request, it will try to obtain the lock to process a data block. There are 3 sessions in client which connect to 3 pods in our case, so 3 requests reach 3 minio pods almost at the same time, however, only the pod that obtains the lock would handle the request, others would be blocked and re-try after a moment. 
In the extreme case, minio pod1 is very unlucky, failed to obtain the lock for 5s, during which the other pods are busy in handling their own requests. As pod1 cannot handle the request for almost 5s, TCP window of the session that connects to pod1 would reach full soon. Though the case is extreme, there is nothing unusual happening.

From my view, the original intention to support multiple sessions in client is to form some kind of pipeline to improve performance. In the best case, different  pods would handle the requests in round-robin. While a pod is handling a request, others are receiving the requests to the buffer, which can save the time of transferring those buffered request. However, the lock is raced freely, so the best case is very rare. Multiple sessions in client may cause extra lock cost which would consume the benefit of multiple sessions or even worse. 

Why does the lock appear and affect performance?
and
When num_parallel_uploads is set to 3, it does not perform well when uploads is set to 1. Is that the reason for locking?
If only one pod can get the lock, what is the meaning of the num_parallel_uploads parameter? Set to 3, but only 1 is working...

Only this parameter(num_parallel_uploads) is used in the document, without its specific description:
https://docs.min.io/docs/python-client-api-reference.html

## Your Environment

* Version used (`minio --version`): RELEASE.2020-02-27T00-23-05Z 
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
@evt-byte First upgrade to the newest version. A *lot* has changed since then.

If the problem still persist provide more details on how you reproduce the issue and your exact setup (startup string, OS, etc)

**Comment by harshavardhana** [comment]
> @evt-byte First upgrade to the newest version. A _lot_ has changed since then.

Since this is largely an older release with older semantics - please upgrade @evt-byte - what you are mentioning is perhaps addressed sometime later

```
commit 0104af6bccce0f8fce537a713c424f4aed2041f0
Author: Harshavardhana <harsha@minio.io>
Date:   Mon Sep 14 15:57:13 2020 -0700

    delayed locks until we have started reading the body (#10474)
```

**Comment by evt-byte** [comment]
Hi, @harshavardhana, @klauspost  we have upgraded to version RELEASE.2021-03-04, and the problem still exists.
