### ISSUE TITLE
Minio Client retention command documentation examples are inaccurate

### ISSUE THREAD

**Issue by tkazmierczak-tt** [minio/minio#12474]
Minio Client retention command documentation is inaccurate in regards to examples showing WORM protection on objects.

## Expected Behavior
Follow the documented example.

Example: Set governance for 30 days for object prefix on bucket mybucket
```
mc retention set governance 30d myminio/mybucket/prefix -r
Object retention successfully set for objects with prefix `myminio/mybucket/prefix`.
```
Objects created with prefix prefix in the above bucket mybucket cannot be deleted until the compliance period is over
```
mc cp ~/comp.csv myminio/mybucket/prefix/
mc rm myminio/mybucket/prefix/comp.csv
Removing `myminio/mybucket/prefix/comp.csv`.
```
This passes successfully and creates a proper DeleteMarker.

## Current Behavior
But the documentation states that the removal should fail with message:
```
mc: <ERROR> Failed to remove `myminio/mybucket/prefix/comp.csv`. Object is WORM protected and cannot be overwritten
```
indicating a completely different behavior. It took me quite a while to find https://github.com/minio/minio/issues/10425 with a short summary that it worked previously this way, but was changed later to be compliant with AWS Object Locking.

## Possible Solution

Correct the doc.

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/commit/27d0ea67cb506bc9a3fe8dca9b5c44995beb8924 fixed
