### ISSUE TITLE
[NAS gateway] Server not initialized, please try again with NFS mounts

### ISSUE THREAD

**Issue by misterEggroll** [minio/minio#12475]
Reopening since  #12473  was erroneously closed.
I am trying to deploy a minio server on Kubernetes.

The deployment has a persistent volume attached to it. Which is resulting in the pod starting but the server isn't starting.
The liveness check which uses `/minio/health/live` passes but the server is unreachable via the UI.
The cluster probe `/minio/health/cluster` returns `503 Server Unreachable` when mounted with the PVC.

This is the manifest I'm using:

`manifest.yaml`
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: argo
  labels:
    name: argo-minio-pv
    app: minio
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <server IP>
    path: <path on NFS>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-minio-pvc
  namespace: argo
  labels:
    name: argo-minio-pvc
    app: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: argo-minio-pv
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - command:
            - minio
            - server
            - /storage
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_SECRET_KEY
              value: password
          image: minio/minio:RELEASE.2021-06-07T21-40-51Z
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          name: main
          ports:
            - containerPort: 9000
          securityContext:
            runAsUser: 0
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          # Mount data on PVC here
          volumeMounts:
            - mountPath: /storage
              name: minio-data
      # Declare PVC as a volume accessible to the deployment
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: argo-minio-pvc
```

## Current Behavior
I see the message "Server not initialized, please try again" when port forwarding the minio service and opening the UI on the browser.

Minio pod is starting. But the server is not accessible and not showing logs.
```
NAME                                   READY   STATUS    RESTARTS   AGE
minio-5f66cbf6db-qr2tm                 1/1     Running   0          14m
```

### Logs

```
 % kubectl logs -n argo minio-5f66cbf6db-qr2tm
 % 
```

### Health Checks

`minio/health/cluster`:
```
 % curl http://localhost:9000/minio/health/cluster -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> GET /minio/health/cluster HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1686E012222D2772
< X-Minio-Server-Status: offline
< X-Xss-Protection: 1; mode=block
< Date: Wed, 09 Jun 2021 09:31:24 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

`minio/health/live`:
```
% curl http://localhost:9000/minio/health/live -v   
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> GET /minio/health/live HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1686E14237754AC2
< X-Minio-Server-Status: offline
< X-Xss-Protection: 1; mode=block
< Date: Wed, 09 Jun 2021 09:53:10 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

## Expected Behavior
The minio pod should start by showing the startup log and the health check should return this result:

### Log:
```
kubectl logs -n argo minio-6b99bcf59f-r5zmh
Endpoint: http://10.0.2.212:9000  http://127.0.0.1:9000 

Browser Access:
   http://10.0.2.212:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

```

### Health Check:

`minio/health/cluster`:
```
 % curl http://localhost:9000/minio/health/cluster -v              
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> GET /minio/health/cluster HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1686E18FB85F452F
< X-Xss-Protection: 1; mode=block
< Date: Wed, 09 Jun 2021 09:58:43 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

`minio/health/live`:
```
% curl http://localhost:9000/minio/health/live -v                 
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9000 (#0)
> GET /minio/health/live HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Security-Policy: block-all-mixed-content
< Server: MinIO
< Vary: Origin
< X-Amz-Request-Id: 1686E1A048F2CD31
< X-Xss-Protection: 1; mode=block
< Date: Wed, 09 Jun 2021 09:59:54 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection 0
```

## Possible Solution

Unsure.

## Steps to Reproduce (for bugs)
1. Create PV
2. Create PVC
3. Mount folder on PVC
4. Start deployment: `kubectl apply -f manifest.yaml`

## Context
I'm trying to mount a PersistentVolumeClaim to my minio deployment.
The drive is getting mounted successfully and there are files getting created as well.

Volumes using `kubectl describe pod`:
```
Volumes:
  minio-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  argo-minio-pvc
    ReadOnly:   false
  default-token-w8hcj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-w8hcj
    Optional:    false
```

`ls` on the mounted drive:
```
 % kubectl exec -n argo -it minio-5f66cbf6db-qr2tm -- ls -la /storage       
total 8
drwxrwxr-x 3 root root 4096 Jun  9 07:07 .
drwxr-xr-x 1 root root   56 Jun  9 08:16 ..
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .minio.sys
```

Mounted drive further details:
```
 % kubectl exec -n argo -it minio-5f66cbf6db-qr2tm -- df -h | grep -e File -e /storage
Filesystem                     Size  Used Avail Use% Mounted on
<IP>:/exports/minio/  197G   66G  131G  34% /storage
```

However, the minio server is not starting.

## Regression
Unsure.

## Environment
* Docker Release used: `minio/minio:RELEASE.2021-06-07T21-40-51Z`
* Kubernetes Version: `v1.16.15-eks-ad4801`

**Comment by harshavardhana** [comment]
Cluster probe is not meant for non distributed setups. So if you use it it may return errors for single drive setups.

**Comment by harshavardhana** [comment]
> % curl http://localhost:9000/minio/health/cluster -v
> *   Trying ::1...
> * TCP_NODELAY set
> * Connected to localhost (::1) port 9000 (#0)
> > GET /minio/health/cluster HTTP/1.1
> > Host: localhost:9000
> > User-Agent: curl/7.64.1
> > Accept: */*
> > 
> < HTTP/1.1 503 Service Unavailable
> < Accept-Ranges: bytes
> < Content-Length: 0
> < Content-Security-Policy: block-all-mixed-content
> < Server: MinIO
> < Vary: Origin
> < X-Amz-Request-Id: 1686E012222D2772
> < X-Minio-Server-Status: offline
> < X-Xss-Protection: 1; mode=block
> < Date: Wed, 09 Jun 2021 09:31:24 GMT
> < 
> * Connection #0 to host localhost left intact
> * Closing connection 0

the main reason for this failure is because either 

```
// Health returns health of the object layer
func (fs *FSObjects) Health(ctx context.Context, opts HealthOptions) HealthResult {
        if _, err := os.Stat(fs.fsPath); err != nil {
                return HealthResult{}
        }
        return HealthResult{
                Healthy: newObjectLayerFn() != nil,
        }
}
```

The Stat is failing on the backend drive or the Object layer is not initialized due to some other issues such as not being able to write to the `/storage` backend.

**Comment by misterEggroll** [comment]
The point isn't whether health checks work or not. The point is that the UI is giving me a [Server not initialized, please try again](https://i.imgur.com/GqUAYgt.png).

I'm attempting to use an NFS server which falls under NAS storage. I tried it out with the `minio gateway nas /mount/path` command. Same results.

I'm not sure if it's an issue with permissions since the `.minio.sys` folder is getting created on the mounted drive.

Can you please help me out with why this could be happening despite health checks passing ?

**Comment by harshavardhana** [comment]
> I'm not sure if it's an issue with permissions since the `.minio.sys` folder is getting created on the mounted drive.
> 
> Can you please help me out with why this could be happening despite health checks passing ?

what kind of health checks is passing? are you talking about `/live` and `/ready` ? 

> The point isn't whether health checks work or not. The point is that the UI is giving me a [Server not initialized, please try again](https://i.imgur.com/GqUAYgt.png).

This part I get, not denying that - I just said why it might not be working. Can you share logs from the server if any? - there should be some..

**Comment by misterEggroll** [comment]
> This part I get, not denying that - I just said why it might not be working. Can you share logs from the server if any? - there should be some..

That's the first thing I looked for as well. There are no logs to speak of. I enabled `HTTP_TRACE` to `stdout` and still radio silence on that front.

> what kind of health checks is passing? are you talking about /live and /ready ?

Both. If either fail, my pod restarts. But currently they both seem to be responding in the green which leads me to think this is more of an IO issue which is going undetected in the logs.

**Comment by harshavardhana** [comment]
Here is the thing to do can you capture `mc admin info --json` output ? And also perhaps login to the pod and see if the backend is writable.

The `.minio.sys/` should carry a file called format.json

**Comment by misterEggroll** [comment]
> The .minio.sys/ should carry a file called format.json

```
% kubectl exec -it minio-7c876b5559-h4pfh -n argo -- sh -c "ls -la /storage"
total 8
drwxrwxr-x 3 root root 4096 Jun  9 07:07 .
drwxr-xr-x 1 root root   56 Jun  9 11:09 ..
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .minio.sys
% kubectl exec -it minio-7c876b5559-h4pfh -n argo -- sh -c "ls -la /storage/.minio.sys"
total 20
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .
drwxrwxr-x 3 root root 4096 Jun  9 07:07 ..
drwxr-xr-x 2 root root 4096 Jun  9 07:07 buckets
-rw------- 1 root root    0 Jun  9 07:07 format.json
drwxr-xr-x 2 root root 4096 Jun  9 07:07 multipart
drwxr-xr-x 6 root root 4096 Jun  9 11:09 tmp

```

> Here is the thing to do can you capture mc admin info --json output ? And also perhaps login to the pod and see if the backend is writable.

`mc` client can't be found in the path of the docker image(`minio/minio:RELEASE.2021-06-07T21-40-51Z`):
```
% kubectl exec -it minio-7c876b5559-h4pfh -n argo -- mc admin info --json
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"mc\": executable file not found in $PATH": unknown
command terminated with exit code 126
```

I `port-forwarded` the minio service to my local env and tried to connect to it using the `mc` cli:

```
% kubectl port-forward -n argo service/minio 9000:9000
Forwarding from 127.0.0.1:9000 -> 9000
Forwarding from [::1]:9000 -> 9000

 % mc config host add minio http://localhost:9000 admin password
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
```

**Comment by harshavardhana** [comment]
Is there a way to remotely access this setup? @misterEggroll - there is something unusual going on here. 

> % kubectl exec -it minio-7c876b5559-h4pfh -n argo -- mc admin info --json

mc comes in a separate container `minio/mc:tag` @misterEggroll

**Comment by misterEggroll** [comment]
> Is there a way to remotely access this setup? @misterEggroll - there is something unusual going on here.

I don't think that's possible since this is once of the clusters my company is using.

> mc comes in a separate container minio/mc:tag @misterEggroll

I'm trying to setup Argo Workflows with Minio as an artifact repository using [this quickstart manifest](https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-postgres.yaml).

There is no separate `mc` setup as a separate deployment. Since the minio server is running as a standalone service. I believe the APIs are being accessed by making use of the [Golang Client](https://docs.min.io/docs/golang-client-quickstart-guide.html) by the other services in the manifest I shared. This is assumed since they're written in Golang([argo server dependency](https://github.com/argoproj/argo-workflows/blob/master/go.mod#L41)). 

If there is any other information I can furnish you with ? Be it turning on additional logging or any configuration tweak. I can help out and share the results.

*Please note*, I'm merely trying to ensure the minio server is working as is. The other components remain untouched since an NFS mount renders minio unreachable.

**Comment by harshavardhana** [comment]
> If there is any other information I can furnish you with ? Be it turning on additional logging or any configuration tweak. I can help out and share the results.
> 
> _Please note_, I'm merely trying to ensure the minio server is working as is. The other components remain untouched since an NFS mount renders minio unreachable.

Have you tried RELEASE.2021-06-09T18-51-39Z release? - I will have to try and reproduce this on my end with NFS mounts.

**Comment by misterEggroll** [comment]
> Have you tried RELEASE.2021-06-09T18-51-39Z release? - I will have to try and reproduce this on my end with NFS mounts.

```
% kubectl describe -n argo pods  minio-59b88f7585-922ll | grep Image
    Image:         minio/minio:RELEASE.2021-06-09T18-51-39Z
    Image ID:      docker-pullable://minio/minio@sha256:88931f679647720b738849402abc841b2288513dc4d2821b1891c0f27e1d644d
```

Just deployed using this image, same results. 
`Server not initialized, please try again`

```
 % kubectl exec -n argo -it  minio-59b88f7585-922ll -- ls -la /storage
total 8
drwxrwxr-x 3 root root 4096 Jun  9 07:07 .
drwxr-xr-x 1 root root   56 Jun 10 08:55 ..
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .minio.sys
 % kubectl exec -n argo -it  minio-59b88f7585-922ll -- ls -la /storage/.minio.sys
total 20
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .
drwxrwxr-x 3 root root 4096 Jun  9 07:07 ..
drwxr-xr-x 2 root root 4096 Jun  9 07:07 buckets
-rw------- 1 root root    0 Jun  9 07:07 format.json
drwxr-xr-x 2 root root 4096 Jun  9 07:07 multipart
drwxr-xr-x 7 root root 4096 Jun 10 08:55 tmp

 % kubectl port-forward -n argo service/minio 9000:9000                          
Forwarding from 127.0.0.1:9000 -> 9000

 % mc config host add minio http://localhost:9000 admin password
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again
```

**Comment by harshavardhana** [comment]
Wait the format.json has `0bytes` 

```
 % kubectl exec -n argo -it  minio-59b88f7585-922ll -- ls -la /storage/.minio.sys
total 20
drwxr-xr-x 5 root root 4096 Jun  9 07:07 .
drwxrwxr-x 3 root root 4096 Jun  9 07:07 ..
drwxr-xr-x 2 root root 4096 Jun  9 07:07 buckets
-rw------- 1 root root    0 Jun  9 07:07 format.json
drwxr-xr-x 2 root root 4096 Jun  9 07:07 multipart
drwxr-xr-x 7 root root 4096 Jun 10 08:55 tmp
```

that's not correct looks like some kind of issue during write NFS is silently ignoring it, are you using NFSv3? or NFSv4?

**Comment by harshavardhana** [comment]
```
minio gateway nas /tmp/fs
Endpoint: http://10.0.0.67:9000  http://172.16.3.4:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
RootUser: minio
RootPass: minio123

Browser Access:
   http://10.0.0.67:9000  http://172.16.3.4:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set mynas http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
^CExiting on signal: INTERRUPT
```

This is how it should look like
```
~ ls /tmp/fs
[2021-06-04 20:08:54 PDT] 4.0KiB .minio.sys/
[2021-06-08 19:57:09 PDT] 4.0KiB testbucket/
```

```
~ ls /tmp/fs/.minio.sys/
[2021-06-08 20:07:34 PDT] 4.0KiB buckets/
[2021-06-04 20:08:54 PDT] 4.0KiB config/
[2021-06-03 23:23:23 PDT]    94B format.json
[2021-06-03 23:23:23 PDT] 4.0KiB multipart/
[2021-06-10 02:04:20 PDT] 4.0KiB tmp/
```

**Comment by harshavardhana** [comment]
NOTE: NAS gateway requires that you have enabled `fcntl` support for your NFS mount if you haven't it won't work properly.

**Comment by misterEggroll** [comment]
Understood ! Let me try this out and get back to you with my findings. I'll get back to you in a few hours.

**Comment by misterEggroll** [comment]
I'm making use of [this dockerfile](https://hub.docker.com/r/jsafrane/nfsexporter/dockerfile) and running it as a container on a Kubernetes cluster.
The container uses [this script](https://github.com/jsafrane/kubernetes-nfs-example/blob/master/exporter/run_nfs) to run the NFS server.

## NFS Server Details:

Install details:
```
[root@nfs-server-0 locktest]# yum --version nfs
3.4.3

[root@nfs-server-0 locktest]# rpcinfo -u localhost nfs
program 100003 version 3 ready and waiting
rpcinfo: RPC: Program/version mismatch; low version = 3, high version = 4
program 100003 version 4 is not available

[root@nfs-server-0 locktest]# cat /proc/fs/nfsd/versions
-2 +3 +4 +4.1 +4.2
```

This indicates the container is using NFSV3. But supports NFS V4 as well. Going by the `/proc/fs/nfsd/versions` file.

Further details:
```
[root@nfs-server-0 locktest]# cat /etc/exports 
/exports *(rw,fsid=0,insecure,no_root_squash)
/ *(rw,fsid=0,insecure,no_root_squash)


[root@nfs-server-0 locktest]# ps -ef | grep rpc 
rpc         13     1  0 Apr01 ?        00:01:24 /usr/sbin/rpcbind -w
root        16     1  0 Apr01 ?        00:00:52 /usr/sbin/rpc.mountd -N 2 -V 3
rpcuser     20     1  0 Apr01 ?        00:00:00 /usr/sbin/rpc.statd --no-notify
root     11098 10601  0 10:04 pts/3    00:00:00 grep --color=auto rpc

[root@nfs-server-0 locktest]# rpcinfo -p localhost | grep nfs
    100003    3   tcp   2049  nfs
    100003    4   tcp   2049  nfs
    100227    3   tcp   2049  nfs_acl
    100003    3   udp   2049  nfs
    100227    3   udp   2049  nfs_acl
```

I pulled the [locktest](https://github.com/jnovack/locktest) repository to test `fcntl` locking functions in NFSv4.
These are the results of running the tests:
```
[root@nfs-server-0 locktest]# touch /exports/f.txt
[root@nfs-server-0 locktest]# ./locktest -n 2 -f /exports/f.txt 
Init
process initalization
..
--------------------------------------

TEST : TRY TO WRITE ON A READ  LOCK:..==
TEST : TRY TO WRITE ON A WRITE LOCK:==
TEST : TRY TO READ  ON A READ  LOCK:==
TEST : TRY TO READ  ON A WRITE LOCK:==
TEST : TRY TO SET A READ  LOCK ON A READ  LOCK:==
TEST : TRY TO SET A WRITE LOCK ON A WRITE LOCK:xx
TEST : TRY TO SET A WRITE LOCK ON A READ  LOCK:xx
TEST : TRY TO SET A READ  LOCK ON A WRITE LOCK:xx
TEST : TRY TO READ LOCK THE WHOLE FILE BYTE BY BYTE:==
TEST : TRY TO WRITE LOCK THE WHOLE FILE BYTE BY BYTE:==

process number : 2 - Remote clients: 0 local client 1 - Total client 1 - Total concurent tests: 2
process number running test successfully :
2 process of 2 successfully ran test : WRITE ON A READ  LOCK
2 process of 2 successfully ran test : WRITE ON A WRITE LOCK
2 process of 2 successfully ran test : READ  ON A READ  LOCK
2 process of 2 successfully ran test : READ  ON A WRITE LOCK
2 process of 2 successfully ran test : SET A READ  LOCK ON A READ  LOCK
2 process of 2 successfully ran test : SET A WRITE LOCK ON A WRITE LOCK
2 process of 2 successfully ran test : SET A WRITE LOCK ON A READ  LOCK
2 process of 2 successfully ran test : SET A READ  LOCK ON A WRITE LOCK
2 process of 2 successfully ran test : READ LOCK THE WHOLE FILE BYTE BY BYTE
2 process of 2 successfully ran test : WRITE LOCK THE WHOLE FILE BYTE BY BYTE
```

There doesn't seem to be an issue with `fcntl` as per what I see here. Unless there's some other tests that I can perform to check for this specific requirement.

### References:

* [Which version of NFS is my NFS server using?](https://unix.stackexchange.com/questions/185829/which-version-of-nfs-is-my-nfs-server-using)
* [How can I test whether fcntl() locks work with my NFS setup?](https://serverfault.com/questions/708371/how-can-i-test-whether-fcntl-locks-work-with-my-nfs-setup)
* [How to check nfs version](https://www.linuxquestions.org/questions/linux-newbie-8/how-to-check-nfs-version-627485/)

**Comment by harshavardhana** [comment]
Local locks are always honored by fcntl you need to run fcntl across mounts this requires multiple gateway instances to hold locks and synchronize. This is only possible in NFSv3 with NLM configured and won't work otherwise.

Kernel NFS doesn't support this out of the box like NetApp etc.

**Comment by misterEggroll** [comment]
> Local locks are always honored by fcntl you need to run fcntl across mounts this requires multiple gateway instances to hold locks and synchronize. This is only possible in NFSv3 with NLM configured and won't work otherwise.

I ran the same locktests code from inside the minio container on the mounted drive.

```
[root@minio-76b4d989bd-zng8v /]# grep -e nfs -e exports  /proc/mounts 
172.20.153.250:/exports/minio/ /storage nfs rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.20.153.250,mountvers=3,mountport=20048,mountproto=tcp,local_lock=none,addr=172.20.153.250 0 0

[root@minio-76b4d989bd-zng8v locktest]# ./locktest -n 5 -f /storage/.minio.sys/f.txt 
Init
process initalization
..........
--------------------------------------

TEST : TRY TO WRITE ON A READ  LOCK:

```

They get stuck indefinitely. I'm assuming this is a sign that there is something amiss. I'm not exactly sure what I have to do to rectify the issue.

**Comment by harshavardhana** [comment]
> > Local locks are always honored by fcntl you need to run fcntl across mounts this requires multiple gateway instances to hold locks and synchronize. This is only possible in NFSv3 with NLM configured and won't work otherwise.
> 
> I ran the same locktests code from inside the minio container on the mounted drive.
> 
> ```
> [root@minio-76b4d989bd-zng8v /]# grep -e nfs -e exports  /proc/mounts 
> 172.20.153.250:/exports/minio/ /storage nfs rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.20.153.250,mountvers=3,mountport=20048,mountproto=tcp,local_lock=none,addr=172.20.153.250 0 0
> 
> [root@minio-76b4d989bd-zng8v locktest]# ./locktest -n 5 -f /storage/.minio.sys/f.txt 
> Init
> process initalization
> ..........
> --------------------------------------
> 
> TEST : TRY TO WRITE ON A READ  LOCK:
> ```
> 
> They get stuck indefinitely. I'm assuming this is a sign that there is something amiss. I'm not exactly sure what I have to do to rectify the issue.

This is exactly the issue, to rectify this you need to either use 

- nfsv4 
- or have NLM configured for NFSv3

**Comment by harshavardhana** [comment]
Another way to workaround this is also to mount NFSv3 client with `local_lock=all` 

Anyways this is beyond MinIO now closing this issue.

**Comment by misterEggroll** [comment]
@harshavardhana 

Thank you for the `local_lock=all` tip. 

I was running NFS Server V3.
```
% kubectl exec -it nfs-server-0 -- rpcinfo -u localhost nfs                           
program 100003 version 3 ready and waiting
```

After some digging, I figured out that Kubernetes supports mount options for certain types of persistent volumes(described [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options), example [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes))

Since minio is the client to my NFS server, the option needs to be set on the minio PV that I created.

This is what my PV looks like:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-2
  namespace: argo
  labels:
    name: minio-pv-2
    app: minio2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  # Workaround to make minio work with NFS server V3.
  # https://github.com/minio/minio/issues/12475#issuecomment-862467976
  mountOptions:
    - local_lock=all
  nfs:
    server:  <IP>
    path: "/exports/minio/"
```

This allowed my minio server to start up successfully with a drive mounted to my NFSV3 server.
