### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by kdkd** [minio/minio#1247]
Right now the server can't be built on FreeBSD. The issues I've found so far:
1. checkdeps.sh doesn't recognize the architecture/OS (expected)
2. The top level Makefile needs to use "gmake" rather than "make" when building isa-l
3. isa-l is selecting incorrect ARFLAGS to build the library
4. pkg/crypto/sha\* is looking for "linux" for the architecture
5. pkg/disk/stat_nix.go is looking for getFSType which isn't being found

That's as far as I got before I decided this wasn't just a build issue. I'm happy test/validate anything if someone else wants to take it from here.

**Comment by vadmeste** [comment]
I can take this for this weekend @harshavardhana, what do you think?

**Comment by harshavardhana** [comment]
Sure @vadmeste.

**Comment by harshavardhana** [comment]
@kdkd we can now compile our project with FreeBSD - thanks to @vadmeste . would you mind giving it a try and letting us know if you face issues?

**Comment by harshavardhana** [comment]
> @kdkd we can now compile our project with FreeBSD - thanks to @vadmeste . would you mind giving it a try and letting us know if you face issues?

Closing this as this is a fixed issue. Thanks @vadmeste

**Comment by kdkd** [comment]
Sorry for the delay, I can confirm this is working now on FreeBSD!
