### ISSUE TITLE
Minio Server Side Replication Documentation

### ISSUE THREAD

**Issue by jsirex** [minio/minio#12483]
After reading documentation it is still not clear for me about how server side replication deals with conflict resolution.

Here is use case:
I have `s3.dc1` and fallback `s3.dc2` minio clusters. If `s3.dc1` goes down I put object V1 to `s3.dc2` as fallback. Assume replication from `s3.dc2` to `s3.dc1` and vice verse. So `s3.dc2` minio will put my object the replication queue.
Now imagine `s3.dc1` goes back online and someone immediately put object V2 to `s3.dc1`. 

From my understanding here is what will happen:

1. `s3.dc1` will put object V2 into the replication queue.
1. Replication worker at `s3.dc1` will put object V2 on `s3.dc2` and it will be "latest".
1. Replication worker at `s3.dc2` will put object V1 on `s3.dc1` and it will be "latest".

```
 S3.DC1   |  S3.DC2
----------+-----------
   V2     |    V1
   V1     |    V2
```

So, there is no creation timestamp or similar involved, isn't it?

PS. I'm not discussing whether minio behaviour is right or wrong, just want to know exactly what will happen. Probably it is worth to update docs.

**Comment by harshavardhana** [comment]
@jsirex MinIO replication requires buckets to have versioning enabled - versioning allows for conflict resolution naturally through its implementation.

**Comment by harshavardhana** [comment]
The implementation is similar to the implementation by AWS https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html

**Comment by jsirex** [comment]
@harshavardhana thank you for quick response.
I know about versioning, but it still not clear to me. There are no explicit stating of order.
From aws documentation:
> Replicate objects while retaining metadata — You can use replication to make copies of your objects that retain all metadata, such as the original object creation time and version IDs. This capability is important if you need to ensure that your replica is identical to the source object.

Is "the latest" object is an object with "the latest" creation time? So in my original post step 3 should be correct as:

3. Replication worker at `s3.dc2` will put object V1 on `s3.dc1`, preserve creation time. There is already newer object V2 according to creation time, so object V1 will NOT be "latest object".

Corrected picture:
```
 S3.DC1   |  S3.DC2
----------+-----------
   V1     |    V1
   V2     |    V2
```

Am I right?

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/blob/master/docs/bucket/replication/DESIGN.md you may want to read this.

**Comment by jsirex** [comment]
Document above does not explicitly state that object with latest timestamp will be the latest.

For example, I have object with versions V1 V3 V2 in the bucket. Which one is the latest? Which one will I get by "GET /object"?

**Comment by harshavardhana** [comment]
> Document above does not explicitly state that object with latest timestamp will be the latest.
> 
> For example, I have object with versions V1 V3 V2 in the bucket. Which one is the latest? Which one will I get by "GET /object"?

For that read what is versioning https://github.com/minio/minio/blob/master/docs/bucket/versioning/README.md @jsirex

**Comment by jsirex** [comment]
I already did. In that document "latest" object mentioned as "current" object.
And document does not explicitly state that object with latest timestamp will be the current object, won't it?

For me looks like last PUT makes object "current".

I have `s3.dc1` <-> `s3.dc2` active active replication and I put object V1 in `s3.dc2` and V2 in `s3.dc1` before any replication occurs. After replication:
1. Which version of object will be "current" at `s3.dc1`? V1?
2 .Which version of object will be "current" at `s3.dc2`? V2?

**Comment by harshavardhana** [comment]
```
I have s3.dc1 <-> s3.dc2 active active replication and I put object V1 in s3.dc2 and V2 in s3.dc1 before any replication occurs. After replication:

Which version of object will be "current" at s3.dc1? V1?
2 .Which version of object will be "current" at s3.dc2? V2?
```

Which ever completes at the end is the latest.
