### ISSUE TITLE
Arbitrary Read Timeout

### ISSUE THREAD

**Issue by zerjioang** [minio/minio#12481]
## Expected Behavior

Im executing a command using minio client to upload a set of documentation files, and I expect to upload them successfully. The command
```bash
mc cp -r . minio/internal/docs
```

should work with no timeout errors

## Current Behavior

Im executing a command using minio client to upload a set of files to my server and I notice read tcp timeout errors eventually. The command is:

```bash
mc cp -r . minio/internal/docs
```

and the errors Im getting are

```bash
API: PutObject(bucket=internal, object=docs/p/tutorials/getting-started.html)
Time: 15:26:33 UTC 06/08/2021
DeploymentID: 0fe8e224-f56c-4429-b349-273ca13beb4b
RequestID: 1686A4BBEC220D7E
RemoteHost: 172.26.2.99
Host: 172.17.0.2:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-05-18T03-39-44Z
Error: read tcp 172.17.0.2:9000->172.26.2.99:41044: read: connection timed out (*net.OpError)
       5: cmd/fs-v1-helpers.go:316:cmd.fsCreateFile()
       4: cmd/fs-v1.go:1126:cmd.(*FSObjects).putObject()
       3: cmd/fs-v1.go:1042:cmd.(*FSObjects).PutObject()
       2: cmd/object-handlers.go:1693:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

and the client get stuck at

```bash
index.html:              8.79 MiB / 8.79 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 17.00 KiB/s
```

## Steps to Reproduce (for bugs)

1. Submit a file folder to minio using `mc`. For example: `mc cp -r . minio/internal/docs`
2. Wait for command success

## Context

The problem happens when I try to submit files to the minio server.

## Regression

No

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-06-09T18-51-39Z`
* Server setup and configuration:
* The way in where the server instance is deployed with Docker is:
 ```bash
docker run \
	--restart always \
	-v $(pwd)/volumes/data:/data \
	-v $(pwd)/volumes/config:/root/.minio \
	-e "MINIO_ACCESS_KEY=$KEY" \
	-e "MINIO_SECRET_KEY=$SECRET" \
	-p 9000:9000 \
	--name minio \
	-d minio/minio:latest server /data
```
* Operating System and version (`uname -a`): `Linux cdn 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@zerjioang are you talking to MinIO over the local network? proxy? 

> ```shell
> Error: read tcp 172.17.0.2:9000->172.26.2.99:41044: read: connection timed out (*net.OpError)
> ```

This suspiciously looks like some kind of a client timeout.

**Comment by zerjioang** [comment]
@harshavardhana  Yes, Im working on local network, in where I deployed a single instance of a minio server. During last months its been working fine, but few weeks ago started to report timeout errors with no settings changed. 

Those are the IPs automatically assigned by Docker networking as part of the vnet created. This is indeed, the net configuration

```json
[
    {
        "Name": "bridge",
        "Id": "f5d1ed402e3061bfa5761cbbe26548137d477f139e6ad2208ac66e135430406a",
        "Created": "2021-06-10T09:57:02.449935094+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "9420c9f2bcc06812bbe4e88f879df3df5dc9bd5e5a7a18558745dd9fa82aab90": {
                "Name": "minio",
                "EndpointID": "2056657d0b9ec52dac1841a9b3e47d1737a0d03bd7584474ab01a5bcc320d8da",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

**Comment by harshavardhana** [comment]
> @harshavardhana Those are the IPs automatically assigned by Docker networking as part of the vnet created. This is indeed, the net configuration

I suspect there is an issue at the docker layer where it proxies the requests into the internal pods 

>    -p 9000:9000 \

Try running MinIO locally without docker just `minio server $(pwd)/volumes/data` and copy the files..

**Comment by zerjioang** [comment]
Okey, I will redeploy it bypassing docker networking layer, and let you know the outcome.

**Comment by zerjioang** [comment]
@hackintoshrao I attempt to install minio with no docker at all following next steps

```bash
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio

# to copy original minio created data
sudo cp -ra volumes raw-volumes

# set ownership
sudo chmod +rw -R ./raw-volumes
sudo chgrp $USER -R ./raw-volumes
sudo chown $USER -R ./raw-volumes

# run minio
MINIO_ACCESS_KEY=$KEY MINIO_SECRET_KEY=$SECRET ./minio server ./raw-volumes/data
```

Now it seems to be working better but it reports some errors like.

```bash
UserAgent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-05-18T03-39-44Z
Error: unexpected EOF (*errors.errorString)
       5: cmd/fs-v1-helpers.go:316:cmd.fsCreateFile()
       4: cmd/fs-v1.go:1126:cmd.(*FSObjects).putObject()
       3: cmd/fs-v1.go:1042:cmd.(*FSObjects).PutObject()
       2: cmd/object-handlers.go:1693:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

and it took 2m16s to upload 8.79 MiB

```bash
mc cp -r . minio/internal/docs/p      
about.html:             8.79 MiB / 8.79 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 65.93 KiB/s 2m16s
```

I dont know if this is normal on minio or it might be a local network issue (mine). To add some light I run a speedtest on my minio server connection from my actual client with `iperf` and report
`19.4 Mbits/sec` link speed, which means that average upload of 8.79 MiB should be way more faster than 2m16s.

```bash
Client connecting to 172.26.40.52, TCP port 5001
TCP window size: 45.0 KByte (default)
------------------------------------------------------------
[  3] local 172.26.2.99 port 36308 connected with 172.26.40.52 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  23.1 MBytes  19.4 Mbits/sec
```

**Comment by vadmeste** [comment]
> I dont know if this is normal on minio or it might be a local network issue (mine)

19.4 Mbits/sec is kind of low in a local network already, could you try to run `mc` in the same machine as MinIO server and see what is the upload speed ?

**Comment by harshavardhana** [comment]
>  [  3]  0.0-10.0 sec  23.1 MBytes  19.4 Mbits/sec

This network is most probably WiFi here and you cannot assume that all of this bandwidth is available. Real data transfer will take a major hit on performance here.

You should fix your network if you expect a better performance. I don't there is any issue here simply a suboptimal networking setup.

Closing this issue since there is nothing MinIO can do here.
