### ISSUE TITLE
Custom 403 response

### ISSUE THREAD

**Issue by rozahp** [minio/minio#12488]
**Is your feature request related to a problem? Please describe.**

Is it possible to custom 403 responses to bad user-agents and/or to custom 403 responses overall?

Today bad user-agents gets 403 and access denied notice with a lot of info. 

Example:

curl https://play.min.io/ -H "Host: Mozill"

Return: 403 and with a lot of text... 

curl https://play.min.io/ -H "Host: Mozilla"

Return: 307 Temporary Redurict to /minio/.

Why not just "Access Denied" or something more simple? 

Thanks for a great software!! 😀

**Comment by harshavardhana** [comment]
@rozahp this is behaving as expected, Mozilla is a string used to detect if requests are landing to the embedded browser. There is no other way to know. 

If you want "AccessDenied" you can turn-off browser `MINIO_BROWSER=off`

**Comment by rozahp** [comment]
For future reference:

Block bad UA at proxy level.
