### ISSUE TITLE
statObject method response user meta error

### ISSUE THREAD

**Issue by zhghg** [minio/minio#12494]
## Expected Behavior

set userMeta when copyObject. then when call statObject , we should get userMeta info. 

## Current Behavior

when statObject, userMetaInfo map is empty

## Possible Solution

when call statObject method, server response hump format key,  it is wrong

https://docs.aws.amazon.com/AmazonS3/latest/userguide/add-object-metadata.html

![image](https://user-images.githubusercontent.com/5567916/121764114-e646a880-cb73-11eb-8dd6-ec13c4d4cf4f.png)

## Your Environment

minio server is run with docker
minio server web info:

VERSION
2021-06-09T18:51:39Z
PLATFORM
Host: minio-minio1 | OS: linux | Arch: amd64
RUNTIME
Version: go1.16.5 | CPUs: 4

Java jar meven
<dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>8.2.1</version>
 </dependency>

**Comment by kannappanr** [comment]
@jiangmitiao Please add more information. Information like what mode is being used. Also a reproducer to reproduce the issue will be useful

**Comment by kannappanr** [comment]
```
mc mb play/jiang
Bucket created successfully `play/jiang`.
```
```
mc cp issue play/jiang
issue:                26 B / 26 B [===================] 57 B/s 0s
```
```
mc stat play/jiang/issue
Name      : issue
Date      : 2021-06-11 21:01:20 PDT
Size      : 26 B
ETag      : b954418e6a50d4d4cb8f02776d867550
Type      : file
Metadata  :
  Content-Type: application/octet-stream
```
```
mc cp play/jiang/issue play/jiang/issue_copy --attr "test=somevalue"
...n.io/jiang/issue:  26 B / 26 B [========================] 84 B/s 0s
```
```
mc stat play/jiang/issue_copy
Name      : issue_copy
Date      : 2021-06-11 21:02:03 PDT
Size      : 26 B
ETag      : b954418e6a50d4d4cb8f02776d867550
Type      : file
Metadata  :
  X-Amz-Meta-Test: somevalue
  Content-Type   : application/octet-stream
```

**Comment by harshavardhana** [comment]
> when call statObject method, server response hump format key, it is wrong

HTTP headers are case insensitive @jiangmitiao canonical format is the expected key and value.  HTTP clients should interpret the header keys in a case insensitive way. 

You should read the hTTP RFC

From RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers": (http://www.w3.org/Protocols/rfc2616/rfc2616.html)

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

Updated RFC 7230 does not list any changes from RFC 2616 at this part.

**Comment by zhghg** [comment]
> HTTP headers are case insensitive

thx, I take a issue to minio-java sdk
