### ISSUE TITLE
Enabling bucket replication

### ISSUE THREAD

**Issue by kartheeksuram** [minio/minio#12492]
**Is your feature request related to a problem? Please describe.**

I get **Unable to enable versioning. A header you provided implies functionality that is not implemented.** error when I tried to enable versioning for bucket replication.

```
sh-4.4# mc version enable miniomaster/miniobucket/
mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.
sh-4.4# 
```

I want to enable bucket replication for buckets located in different data centers, one datacenter being in California and another being in Colorado. Does MinIO bucket replication support this? If yes, how to configure the replication.
The reason date being replicated to different DCs is for redundancy.

I was also reading https://docs.min.io/docs/distributed-minio-quickstart-guide.html but this explains how replication is enabled from disk 1 to disk 2 on the same datacenter but not when we disks are located in a different datacenter.

**Comment by harshavardhana** [comment]
Bucket replication can only be enabled with distributed setups or locally erasure-coded setups - you cannot enable replication - distributed setup within the cluster does erasure coding. 

Replication is between multiple sites - you can't run single drive setups to enable replication.
