### ISSUE TITLE
too many 503 error on a distributed minio server

### ISSUE THREAD

**Issue by buildwithdemis** [minio/minio#12508]
we have currently setup distributed minio with 8 nodes and 2 drives per node. and successfully migrated objects from the previous standalone server. 

## Current Behavior
while looking at the output we are getting too many errors: `503 Service Unavailable`

##optimization
I have seen other forums and applied recommended settings like increase the `file descriptor` size of the server(set to 1 million). I have seen that this is not an issue because `cat /proc/sys/fs/file-nr` value is too low. Which is less than 10k opened files.

##environment:
version: minio version RELEASE.2021-04-06T23-11-00Z
OS: ubuntu 18.04
RAM: 20GB for each node
Data size: ~140 GB files type: image, xml, json
Disk type: spining disk 7.2kRPM
RAID: RAID 10

**Comment by klauspost** [comment]
@demis-svenska Upgrade and post server logs.

**Comment by buildwithdemis** [comment]
Upgraded to **minio version RELEASE.2021-06-14T01-29-23Z**

Here is the log from `trace` output `mc admin trace alias`

2021-06-15T13:38:48:000 [503 Service Unavailable] s3.GetObject minio3:9000/echis/7a78b026608545aba33067841ae4a23b 172.19.4.35       58.305ms     ↑ 123 B ↓ 639 B
2021-06-15T13:38:48:000 [503 Service Unavailable] s3.GetObject minio7:9000/echis/7a78b026608545aba33067841ae4a23b 172.19.4.35       11.262ms     ↑ 123 B ↓ 639 B
2021-06-15T13:38:48:000 [200 OK] s3.PutObject minio4:9000/echis/f01bd686c43744de920b9b0f3a74da0c 172.19.4.35       1.828749s    ↑ 2.1 KiB ↓ 230 B
2021-06-15T13:38:48:000 [200 OK] s3.GetObject minio8:9000/echis/524c7847560d4b78b7ab198619a2c6db 172.19.4.35       1.463844s    ↑ 123 B ↓ 2.5 KiB
2021-06-15T13:38:52:000 [503 Service Unavailable] s3.GetObject minio8:9000/echis/7a78b026608545aba33067841ae4a23b 172.19.4.35       11.416ms     ↑ 123 B ↓ 639 B
2021-06-15T13:38:49:000 [200 OK] s3.PutObject minio6:9000/echis/b1782fbc403344f4aebbd9dc9e633d4b 172.19.4.42       3.784398s    ↑ 2.3 KiB ↓ 230 B
2021-06-15T13:38:54:000 [503 Service Unavailable] s3.GetObject minio3:9000/echis/7a78b026608545aba33067841ae4a23b 172.19.4.35       7.901ms      ↑ 123 B ↓ 639 B

**Comment by klauspost** [comment]
@demis-svenska Logs from the server.

**Comment by buildwithdemis** [comment]
sorry for the late reply.

Mostly, i use syslog and `mc admin console alias` to trace `minio` related logs. is there any other location that i should find the logs?

I setup minio using a guide from digitalocean: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-18-04

**Comment by harshavardhana** [comment]
> Mostly, i use syslog and `mc admin console alias` to trace `minio` related logs. is there any other location that i should find the logs?

Just capture `journalctl -fu minio > file.txt`  from all nodes and attach it here.

**Comment by harshavardhana** [comment]
you may also be interested to upgrade to RELEASE.2021-06-17T00-10-46Z

**Comment by buildwithdemis** [comment]
Hi, the log is empty. It only displays `Logs begin at Mon 2021-03-29 13:19:09 UTC` on all nodes

172.19.4.47 |
-- Logs begin at Mon 2021-03-29 13:19:09 UTC. --
172.19.4.41 
-- Logs begin at Sun 2021-02-21 19:08:14 UTC. --
172.19.4.53 
-- Logs begin at Thu 2021-04-08 18:26:19 UTC. --
172.19.4.56 
-- Logs begin at Thu 2021-04-08 18:28:25 UTC. --
172.19.4.57
-- Logs begin at Thu 2021-04-08 18:28:37 UTC. --
172.19.4.40 
-- Logs begin at Sun 2021-05-09 05:21:40 UTC. --
172.19.4.55 
-- Logs begin at Thu 2021-04-08 18:28:18 UTC. --
172.19.4.54
-- Logs begin at Thu 2021-04-08 18:28:09 UTC. --

**Comment by klauspost** [comment]
@demis-svenska Without more information we are just guessing. You need to set up your cluster so you capture logs.

**Comment by buildwithdemis** [comment]
cluster is already set up. Is there any other way to check it? Here is config for cluster health info

CMD: `mc admin info minionew`                                                                                                        
●  minio1:9000                                                                                                                                                        
   Uptime: 2 days                                                                                                                                                     
   Version: 2021-06-14T01:29:23Z                                                                                                                                      
   Network: 8/8 OK                                                                                                                                                    
   Drives: 2/2 OK                                                                                                                                                     
                                                                                                                                                                      
●  minio2:9000                                                                                                                                                        
   Uptime: 14 hours                                                                                                                                                   
   Version: 2021-06-14T01:29:23Z                                                                                                                                      
   Network: 8/8 OK                                                                                                                                                    
   Drives: 2/2 OK                                                                                                                                                     
                                                                                                                                                                      
●  minio4:9000
   Uptime: 2 days 
   Version: 2021-06-14T01:29:23Z
   Network: 8/8 OK 
   Drives: 2/2 OK 

●  minio5:9000
   Uptime: 2 days 
   Version: 2021-06-14T01:29:23Z
   Network: 8/8 OK 
   Drives: 2/2 OK 

●  minio6:9000
   Uptime: 2 days 
   Version: 2021-06-14T01:29:23Z
   Network: 8/8 OK 
   Drives: 2/2 OK 

●  minio7:9000
   Uptime: 2 days 
   Version: 2021-06-14T01:29:23Z
   Network: 8/8 OK 
   Drives: 2/2 OK 
●  minio8:9000
   Uptime: 2 days 
   Version: 2021-06-14T01:29:23Z
   Network: 8/8 OK 
   Drives: 2/2 OK 
   
●  minio3:9000 
   Uptime: 2 days 
   Version: 2021-06-14T01:29:23Z
   Network: 8/8 OK 
   Drives: 2/2 OK

**Comment by klauspost** [comment]
@demis-svenska It is the output from stderr written by the server.

**Comment by buildwithdemis** [comment]
It's the output of the command `mc admin info minionew` where `minionew `is an alias

**Comment by klauspost** [comment]
@demis-svenska I know. Post the output from your *servers*, not the client.

**Comment by buildwithdemis** [comment]
running the command on the server machine, I got the same output. If there is a different cmd, please write it.

**Comment by harshavardhana** [comment]
If the logs are empty then 503 is just client terminating connections here - looks like your client is perhaps far away from closing connections. 

> 2021-06-15T13:38:48:000 [503 Service Unavailable] s3.GetObject minio3:9000/echis/7a78b026608545aba33067841ae4a23b 172.19.4.35 58.305ms ↑ 123 B ↓ 639 B
> 2021-06-15T13:38:48:000 [503 Service Unavailable] s3.GetObject minio7:9000/echis/7a78b026608545aba33067841ae4a23b 172.19.4.35 11.262ms ↑ 123 B ↓ 639 B

**Comment by buildwithdemis** [comment]
Thanks, I'll look into the application side. 
Related Question:
     where can I find detailed logs for minio? Like what we found on other systems. eg , On Nginx we have something like: `/var/log/nginx/access.log` and `/var/log/nginx/error.log`

**Comment by harshavardhana** [comment]
> Thanks, I'll look into the application side.
> Related Question:
> where can I find detailed logs for minio? Like what we found on other systems. eg , On Nginx we have something like: `/var/log/nginx/access.log` and `/var/log/nginx/error.log`

They are printed on the terminal where you are running, it should be always present at `journalctl -u minio`

Closing this issue since there nothing here in the logs to debug on MinIO.
