### ISSUE TITLE
Failed auth attempts cause no errors in logs (web-interface)

### ISSUE THREAD

**Issue by Ziars** [minio/minio#12503]
## Expected Behavior

Unsuccessful authentication attempt via web-interface causes 4xx error, visible in debug logs.

## Current Behavior

Unsuccessful authentication attempt via web-interface causes no errors in debug logs. I get only 200 codes there, nothing like an error.

## Steps to Reproduce (for bugs)

1. Run minio-server with web-interface enabled:
``` ini
MINIO_BROWSER=on
```
2. Launch [debug](https://github.com/minio/minio/tree/release/docs/debugging) tracing or enable audit-logging to HTTP endpoint, i.e.:
```
mc admin trace --all --verbose local
mc admin config set local audit_webhook:test auth_token="" endpoint="https://domain.tld"
```
3. Make a login attempt with invalid credentials (in web-interface)
4. Check resulting logs

## Context

I'm trying to setup brute-force protection with fail2ban. It works fine with failed requests via CLI (that result in `403 Forbidden`), but I can't achieve the same for web-interface auth attempts.

## Environment

Versions:

``` shell
~# minio --version
minio version RELEASE.2021-06-14T01-29-23Z

~# minio-client --version
minio-client version RELEASE.2021-06-13T17-48-22Z
```

Configuration:

``` ini
MINIO_VOLUMES="/var/lib/minio/data"
MINIO_ACCESS_KEY=my_access_key
MINIO_SECRET_KEY=my_secret_key
MINIO_REGION=local
MINIO_BROWSER=on
MINIO_DOMAIN=mydomain.tld
MINIO_OPTS="--anonymous"
```

OS:

```
~# uname -a
Linux testing 4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Is this a bug or am I missing something? Thank you in advance.

**Comment by harshavardhana** [comment]
Failed auth attempts never log anything @Ziars since the error response is sent back to client - if you want to see like nginx like logs configure a proxy in front of MinIO. 


> Unsuccessful authentication attempt via web-interface causes no errors in debug logs. I get only 200 codes there, nothing like an error.

Authentication of WebInterface is JSON-RPC based so you won't be able to use S3 protocol tools to look at those errors.

**Comment by harshavardhana** [comment]
JSON-RPC error is sent as a body not as an HTTP status code @Ziars so your tool needs to interpret the body of the response.

**Comment by Ziars** [comment]
@harshavardhana thank you for the clarification! So, for getting infromation about failed auth attempts we need:

1. Separate service, running `mc admin trace` and logging the output (for attempts via CLI)
1. Nginx as a proxy in front of MinIO, with response logging (for attempts via web-interface)

This greatly increases the entry threshold for MinIO as an open source product. Is there a chance of getting authentication error logging implemented in the future, so we can setup bot protection easier?

**Comment by harshavardhana** [comment]
> @harshavardhana thank you for the clarification! So, for getting infromation about failed auth attempts we need:
> 
> 1. Separate service, running `mc admin trace` and logging the output (for attempts via CLI)
> 1. Nginx as a proxy in front of MinIO, with response logging (for attempts via web-interface)
> 
> This greatly increases the entry threshold for MinIO as an open source product. Is there a chance of getting authentication error logging implemented in the future, so we can setup bot protection easier?

No it does not you need to enable audit logging.

mc admin trace is always present, also the browser code you are talking about is already gone and we have moved to full S3 API based protocol for all operations.
