### ISSUE TITLE
Listing empty bucket is far slower than listing non-empty bucket

### ISSUE THREAD

**Issue by adamhooper** [minio/minio#12518]
## Expected Behavior

I would expect listing an empty bucket to be near-instantaneous.

## Current Behavior

Minio seems to take a minimum of 6ms to list an empty bucket on my system. This is an AMD Ryzen 5 with tmpfs.

The workaround is to ... well ... add a file! Listing a non-empty bucket can take 1ms.

## Steps to Reproduce (for bugs)

I measured the above timings in my Python+botocore codebase. There, minio CPU usage is 350%, which surprises me because I thought I was requesting in serial. There may be problems in my codebase; but I won't reduce it because I can use `mc` to illustrate the minio-side problem.

Here's an illustration with `mc` timings. The slowdown is smaller when I use `mc` (and minio CPU stays at 100%). The slowdown is significant and easy to reproduce.

```
$ docker run --rm -p 9000:9000 --tmpfs /data minio/minio:RELEASE.2021-06-14T01-29-23Z server /data
$ mc config host add test http://localhost:9000 minioadmin minioadmin --api S3v4
$ mc mb test/abc/ # empty bucket
$ time for i in `seq 1 1000`; do mc ls test/abc/ >/dev/null; done

real    0m7.577s
user    0m3.548s
sys     0m2.106s
$ touch x
$ mc cp x test/abc/x # non-empty bucket
time for i in `seq 1 1000`; do mc ls test/abc/ >/dev/null; done

real    0m6.339s
user    0m3.449s
sys     0m2.196s
```

I would expect the non-empty timings to be imperceptibly slower than the empty-directory timings. Instead, listing an empty directory is ~20% slower than listing a non-empty directory.

## Context

I use minio for unit testing. I have 5 buckets, and I empty them between tests. Most tests take maybe 5ms and don't write anything to minio; so minio slows down my test suite 700%.

## Regression

This is a regression, but I can't pinpoint the exact date. My unit-test suite started taking twice as long as it used to. I think the minio release came after September 2020.

## Your Environment

* Version: `RELEASE.2021-06-14T01-29-23Z`
* Server setup and configuration: Docker+tmpfs
* Operating system

**Comment by harshavardhana** [comment]
> I would expect listing an empty bucket to be near-instantaneous.

It cannot be @adamhooper there are many resources that still need to be used to ascertain that your bucket is indeed empty.

**Comment by klauspost** [comment]
mc does different calls. Based on the response, so you cannot compare it.

If 404, it retries `GetBucketLocation`. Serverside it takes about 0.5ms to return the response, so if any, this is an mc issue.

I don't think this is a huge issue worth pursuing. It definitely isn't a serverside issue.

**Comment by adamhooper** [comment]
@klauspost So shall I work on a reduction then? If I can prove that minio is 5x slower to list an empty bucket than a non-empty one, without MC being involved at all, would that be considered a bug (and a regression)?

**Comment by klauspost** [comment]
@adamhooper I don't see what you mean. You are showing a 20% slowdown on a combination of things.

You can do an `mc admin trace myminio` and observe the serverside request times.

Existing bucket:
`2021-06-17T12:45:50:000 [200 OK] s3.GetBucketLocation localhost:9000/test/?location=  ::1               516µs       ↑ 77 B ↓ 349 B`

Non-existing:
`2021-06-17T12:47:33:000 [404 Not Found] s3.GetBucketLocation localhost:9000/blah/?location=  ::1               527µs       ↑ 77 B ↓ 509 B`

The server is not doing anything other than a Stat operation on the folder it expects to be there. If your underlying FS is slow for that, it will just be reflected.

**Comment by adamhooper** [comment]
@klauspost Did you close this bug report because A) you agree that minio is far slower to list empty buckets and that's not a problem; or because B) I didn't convince you that minio is far slower to list empty buckets?

I'll clarify:

* My `mc` timings are both on existing buckets. I'm only talking about `s3.ListObjectsV2`, not any other operation.
* My timings are on tmpfs on a fast computer, so I doubt my underlying FS is slow.
* Even if we dismiss my `mc` test as beside the point, I think there's a server-side issue here.

Thank you for suggesting `mc admin trace`. Here are its timings, using today's latest `mc` and `mc ls --recursive` and the same test procedure above:

*Empty bucket*: `2021-06-17T13:09:27:000 [200 OK] s3.ListObjectsV2 localhost:9000/abc/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=  172.17.0.1        5.017ms      ↑ 77 B ↓ 510 B`

*Bucket that contains a single file*: `2021-06-17T13:10:53:000 [200 OK] s3.ListObjectsV2 localhost:9000/abc/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=  172.17.0.1        463µs       ↑ 77 B ↓ 822 B`

Apparently, `s3.ListObjectsV2` is 10x slower on an empty bucket.
