### ISSUE TITLE
[faq] throttle api calls auto by setup mode

### ISSUE THREAD

**Issue by TestMsr** [minio/minio#12529]
**Is your feature request related to a problem? Please describe.**
ram_per_request is now 22Mib+ with erasure block size,it's unreliable in gateway and single drive mode

**Describe the solution you'd like**
setting by setup mode

**Describe alternatives you've considered**

**Additional context**

**Comment by klauspost** [comment]
Use `MINIO_API_REQUESTS_MAX` env var or `mc admin config set myminio api requests_max=n`
