### ISSUE TITLE
Gateway to MongoDB Gridfs

### ISSUE THREAD

**Issue by jmthackett** [minio/minio#12528]
I'm more or less constantly on the lookout for systems that will lead me to be able to manage less stuff (without becoming SPOF) and have recently been investigating whether or not MongoDB has any S3 interfaces to its GridFS file storage system.

GridFS seems to blur the lines between storing documents and objects, and so an S3 interface makes perfect sense.

There is some prior art:

In ruby: https://github.com/Wijnand/mainboard

In javascript: https://github.com/antoinegomez/gridfs-s3-http

What I'd like to see is minio supporting a similar mode, which would be comparable to its HDFS gateway. 

Some perks of this approach are that deduplication of blocks (well, 255kb documents in GridFS) is free, and replication and sharding are very flexible.

I've considered running other systems (Ceph etc) but they're hugely heavyweight. I'd not want to have that operational burden. But I (and I think probably quite a few people) am reasonably au fait with running a MongoDB cluster, and already have lots of tooling for it.

**Comment by ravindk89** [comment]
Hi @jmthackett 

As a former tech writer for MongoDB with significant time spent on the server docs, I was somewhat tickled to see GridFS come up here.

A key part of MinIO Gateway's offerings is S3 compatibility. Building an interface that respects MongoDB's fundamental access methods and API - readConcern, writeConcern, replication/sharding topologies, translating database -> collections -> documents into bucket path-style access, whether or not to utilize transactions, etc. etc.  - would be a significant undertaking. We also have to commit to maintaining that interface over time as MongoDB releases updates, which is an additional resource burden for the team.

We appreciate the enthusiasm, but we're not going to take this feature request. The resources required to implement it correctly don't justify the potential benefits. If someone from the community wants to fork [minio/ming](https://github.com/minio/ming/) (once its ready) and try it out themselves, they are welcome to do so as long as they respect the project license.
