### ISSUE TITLE
Minio unable to start on TLS. ( Trying to renew the certs was working fine for past couple of years)

### ISSUE THREAD

**Issue by maniker** [minio/minio#12520]
We are trying to start the Minio on TLS by enabling a existing key and certificate ( followed step 2 from the https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html). We successfully integrated couple of years ago now we are trying to renew the old cert and followed the same process by uploading private.key and public.crt in certs directly but we get an error while starting the app.

## Expected Behavior
Expect Minio to run on TLS https when we obtain a cert from the certificate authority.

## Current Behavior
After uploading the .key and .crt in the /certs directory, we get this below error.
http: TLS handshake error from SERVERNAME: remote error: tls: unknown certificate authority
 http: TLS handshake error from SERVERNAME EOF

## Possible Solution
1. This is something we have successfully done before and it worked for us, we get a pem file from our organization and i seperate the private key from it and create a private.key file and the remaining file as public.crt. We tried openssl format, pks8, pks 1 but get the same above error when we run minio server ~/test. 

## Steps to Reproduce (for bugs)
1.[account@servername certs]$ ls  openssl  private1.key  private.key  public.crt
2. minio server ~/test
ERROR Unable to load the TLS configuration: Missing TLS password.
      > Please set the password to environment variable `MINIO_CERT_PASSWD` so that the private key can be decrypted.
we have never set a password before to MINIO_CERT_PASSWD,  but after setting the password

3. [account@servername  certs]$ export MINIO_CERT_PASSWD='TestPassword!'
[account@servername  certs]$ printenv MINIO_CERT_PASSWD
TestPassword
[tnicextr@testencextr1lsat certs]$  minio server ~/test
Endpoint:  https://servername:9000 
AccessKey: test
SecretKey: test1

Browser Access:
   https://servername:9000  https://test:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio https://servname:9000 test test111

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

2021/06/16 12:57:31 http: TLS handshake error from :33363: EOF
2021/06/16 12:57:32 http: TLS handshake error from :33446: EOF
2021/06/16 12:57:36 http: TLS handshake error from :6989: EOF
2021/06/16 12:57:37 http: TLS handshake error from :34758: EOF
2021/06/16 12:57:38 http: TLS handshake error from :51110: EOF
2021/06/16 12:57:39 http: TLS handshake error from :51114: remote error: tls: unknown certificate authority
2021/06/16 12:57:41 http: TLS handshake error from :30078: EOF
.

## Context
This is effecting us to stop our extract job and services. we need renew the cert in production in few weeks from now.

## Your Environment
Version: 2019-06-13T01:41:13Z
Release-Tag: RELEASE.2019-06-13T01-41-13Z
*Operating system :- Linux

**Comment by harshavardhana** [comment]
@maniker once you have updated the certs - server is starting fine - you need to make sure to trust the new public.crt on the client 

> 2021/06/16 12:57:39 http: TLS handshake error from :51114: remote error: tls: unknown certificate authority

That is the issue reported here. Rest of the errors can be ignored such as `EOF`. 

I don't think anything has changed in server here looks like server has recognized certs and is running in TLS mode already.

**Comment by harshavardhana** [comment]
> This is effecting us to stop our extract job and services. we need renew the cert in production in few weeks from now.

For production systems buy a subscription to get support and guidance on how to run a supported infrastructure - https://min.io/pricing

Relying on something in production without support doesn't make any logistic sense.

**Comment by maniker** [comment]
> @maniker once you have updated the certs - server is starting fine - you need to make sure to trust the new public.crt on the client
> 
> > 2021/06/16 12:57:39 http: TLS handshake error from :51114: remote error: tls: unknown certificate authority
> 
> That is the issue reported here. Rest of the errors can be ignored such as `EOF`.
> 
> I don't think anything has changed in server here looks like server has recognized certs and is running in TLS mode already.

how to trust the new cert from the client?  @harshavardhana

**Comment by harshavardhana** [comment]
> how to trust the new cert from the client? @harshavardhana

`public.crt` needs to be added to your ca-certificates ideally in /etc/ssl/certs directory
