### ISSUE TITLE
Public metrics are not public?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [minio/minio#12530]
## Expected Behavior
When `MINIO_PROMETHEUS_AUTH_TYPE: public`, metrics return without login

## Current Behavior
Docs: https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html#2-configure-authentication-type-for-prometheus-metrics

1. curl `https://play.min.io/minio/v2/metrics/cluster` or `my-cluster/minio/v2/metrics/cluster`
2. Both return login screen

## Steps to Reproduce (for bugs)

1. Install bitnami minio helm chart, it is setting `MINIO_PROMETHEUS_AUTH_TYPE: public` by default
![image](https://user-images.githubusercontent.com/46970457/122566407-30d29400-d050-11eb-86f0-647ed3e4f938.png)
2. Try to query `/minio/v2/metrics/cluster`
3. Try to query `https://play.min.io/minio/v2/metrics/cluster`

## Context
More details: https://github.com/bitnami/charts/issues/6704

## Regression
Seems yes

## Your Environment
* Version used (`minio --version`): `minio version DEVELOPMENT.2021-06-17T03-17-14Z`
* Server setup and configuration:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
```
curl https://play.min.io/minio/v2/metrics/cluster | tail
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80036    0 80036    0     0   325k      0 --:--:-- --:--:-- --:--:--  325k
# TYPE minio_usage_last_activity_nano_seconds gauge
minio_usage_last_activity_nano_seconds{server="127.0.0.1:9000"} 2.5378904479e+10
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 14794
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

This is working perfectly fine, visiting the URL on the UI won't work it will redirect to always to a browser UI this is nothing special. 

Please check what you are doing locally.

**Comment by sergeyshaykhullin** [comment]
@harshavardhana Thanks, yes. I found a problem

This might help someone in a future https://github.com/bitnami/charts/issues/6704
