### ISSUE TITLE
mkdir: too many links

### ISSUE THREAD

**Issue by mostafa8026** [minio/minio#12536]
I get this error after putting object:

```
API: PutObject(bucket=decodl-storage, object=...)
Time: 14:00:33 UTC 06/19/2021
DeploymentID: 3d8c7363-1a2e-4bc7-8bc8-a96f72d15d97
RequestID: 168A008FB842A19A
RemoteHost: 136.243.8.29
Host: storage.decodl.ir
UserAgent: MinIO (linux; amd64) minio-go/v7.0.11
Error: mkdir /export3/decodl-storage/...: too many links (*fs.PathError)
       4: cmd/xl-storage.go:2100:cmd.(*xlStorage).RenameData()
       3: cmd/xl-storage-disk-id-check.go:419:cmd.(*xlStorageDiskIDCheck).RenameData()
       2: cmd/erasure-object.go:522:cmd.renameData.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```
## Steps to Reproduce (for bugs)
putting an object

## Context
I update from ext2 to ext4, but problem yet exists.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-06-17T00-10-46Z
* Server setup and configuration:  k8s - minio provider
* Operating System and version (`uname -a`): Linux storage1-zone-0-0 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mostafa8026** [comment]
How can I troubleshoot the problem?

**Comment by harshavardhana** [comment]
Do not use ext4 use XFS our recommend filesystem. ext has limits on number of directories per prefix.

**Comment by mostafa8026** [comment]
Do you know the limit?
I have 64999 files in one prefix, and it is the largest one.

**Comment by mostafa8026** [comment]
and how I convert ext4 to the xfs properly, do you have any advice?

**Comment by harshavardhana** [comment]
> and how I convert ext4 to the xfs properly, do you have any advice?

There is no way to do that reformat and re-do your setup.

**Comment by mostafa8026** [comment]
I used fstransform and everything is good now (after 2 days 😢)
