### ISSUE TITLE
OPA is not working anymore

### ISSUE THREAD

**Issue by fcomte** [minio/minio#12547]
## Expected Behavior
I know that opa is deprecated.
I am still using it access to create rules that iterate over a claim in jwt : groups which is a list.

## Current Behavior

Version : RELEASE.2021-04-22T15-44-28Z is working for OPA access control
Version : RELEASE.2021-06-07T21-40-51Z or RELEASE.2021-06-17T00-10-46Z is not working

The sts endpoint still give me the token but when using credentials, minio answer "the access key you provide does not exist in our records"

Is OPA still suppose to work despite it is deprecated ?

**Comment by harshavardhana** [comment]
> ## Expected Behavior
> I know that opa is deprecated.
> I am still using it access to create rules that iterate over a claim in jwt : groups which is a list.
> 
> ## Current Behavior
> Version : RELEASE.2021-04-22T15-44-28Z is working for OPA access control
> Version : RELEASE.2021-06-07T21-40-51Z or RELEASE.2021-06-17T00-10-46Z is not working
> 
> The sts endpoint still give me the token but when using credentials, minio answer "the access key you provide does not exist in our records"
> 
> Is OPA still suppose to work despite it is deprecated ?

@fcomte the error you are describing is a problem perhaps introduced recently due to newer requirements.  It was due to the fact that we require more functionality on MinIO and we do not deploy with OPA in any of our deployments anymore.

I don't think it is feasible to support OPA anymore and unfortunate side affect.

**Comment by fcomte** [comment]
solving this issue https://github.com/minio/minio/issues/11303 would be very great for those that is trapped in OPA.

**Comment by harshavardhana** [comment]
> solving this issue #11303 would be very great for those that is trapped in OPA.

That is going to be resolved but its currently blocked on https://github.com/minio/pkg/pull/2
