### ISSUE TITLE
GetObject returns different response to Amazon S3

### ISSUE THREAD

**Issue by chrisharward** [minio/minio#12543]
When we do a GetObject call against MinIO with both an invalid etag in the If-Match field, and a range that's past the end of the object data in the Range field, we get a different error from MinIO than from Amazon S3.

## Expected Behavior
Amazon S3 returns the following error:
An error occurred (PreconditionFailed) when calling the GetObject operation: At least one of the pre-conditions you specified did not hold

## Current Behavior
MinIO returns:
An error occurred (InvalidRange) when calling the GetObject operation: The requested range is not satisfiable

## Steps to Reproduce (for bugs)
Create an object with data using put_object, then run a get_object request setting both an invalid etag and range past the end of the object in the request_headers field.

Code sample to repro:

```py
import io

from minio import Minio
from minio.error import S3Error

def main():
    # Create a client with the MinIO server playground, its access key
    # and secret key.
    client = Minio(
        "play.min.io",
        access_key="Q3AM3UQ867SPQQA43P2F",
        secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    )

    # Upload empty folder
    result = client.put_object(
        "test", "object", io.BytesIO(b"data"), 4,
    )
    print("created {0} object; etag: {1}, version-id: {2}".format(
            result.object_name, result.etag, result.version_id,
        ),
    )

    client.get_object("test", "object", request_headers={ 'If-Match': 'invalid_etag', 'Range': 'bytes=4-10' })

if __name__ == "__main__":
    try:
        main()
    except S3Error as exc:
        print("error occurred.", exc)
```

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2020-06-22T03-12-50Z

**Comment by harshavardhana** [comment]
> * minio version RELEASE.2020-06-22T03-12-50Z

@chrisharward we have changed the error responses since some time now please upgrade and test.

**Comment by harshavardhana** [comment]
> When we do a GetObject call against MinIO with both an invalid etag in the If-Match field, and a range that's past the end of the object data in the Range field, we get a different error from MinIO than from Amazon S3.

Also what is the big difference here anyways, are you as client expecting a particular error to invalidate some caches?

**Comment by harshavardhana** [comment]
The main difference for us is that we validate ranges first than metadata @chrisharward - Although this can be fixed - I am not sure why do we care anyways here since it clearly looks like InvalidRange is the correct error. Because client made a mistake where as `If-Match-Etag` might not be same which could be a valid situation. 

Instead of not knowing that Range was wrong during `If-Match-Etag` is a good sign such that you can fix your client implementation issue. 

It is buggy behavior In our opinion that ETag is validated first instead of validating invalid inputs.

**Comment by chrisharward** [comment]
The issue for us is that we use MinIO as a local system test environment, for a product that in production runs against Amazon S3, so we like it to match the S3 behavior as closely as possible.

It is possible to get both of these errors in the same request if the object changes in S3 between a list_objects call and the get_object call (if it is replaced by a smaller object for instance). There's not much you can do as a client to prevent this,  which is why for testing purposes we'd like MinIO to behave the same way as Amazon S3 does.

You could argue that it is correct to check range first and then etag, but for us this is largely academic. Our interest is in having a system that as closely resembles Amazon S3 as possible.

**Comment by harshavardhana** [comment]
> The issue for us is that we use MinIO as a local system test environment, for a product that in production runs against Amazon S3, so we like it to match the S3 behavior as closely as possible.
> 
> It is possible to get both of these errors in the same request if the object changes in S3 between a list_objects call and the get_object call (if it is replaced by a smaller object for instance). There's not much you can do as a client to prevent this, which is why for testing purposes we'd like MinIO to behave the same way as Amazon S3 does.
> 
> You could argue that it is correct to check range first and then etag, but for us this is largely academic. Our interest is in having a system that as closely resembles Amazon S3 as possible.

Sure just for compatibility alone, make sense.
