### ISSUE TITLE
Feature Request: RBAC for objects in bucket

### ISSUE THREAD

**Issue by WeiTangLau** [minio/minio#12546]
**Is your feature request related to a problem? Please describe.**
I would like to give access of some files to other users (e.g. PDF file instead of WORD).
Thus, I should be able to define the roles, and then select the roles needed via a dropdown to be able to view & download the object.

**Describe alternatives you've considered**
The alternative I can think of is to split the files into 2 buckets, public and private. Private means only owner can view & download, public means both owner and other parties can view and download.

**Comment by harshavardhana** [comment]
We already have IAM compatible policies, per object based is already supported.

Not sure what is the ask here.
