### ISSUE TITLE
The first expansion was successful, but the second expansion failed

### ISSUE THREAD

**Issue by NoSadness** [minio/minio#12549]
### **MinIO Version:**
2021-06-17T00:10:46Z 

### **Steps to Reproduce:**
1、Original MinIO cluster
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=miniotest
minio server http://10.3.73.{137...137}/mnt/disk{1...6}/miniodata
2、The first expansion was successful
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=miniotest
minio server http://10.3.73.{137...137}/mnt/disk{1...6}/miniodata http://10.3.73.{140...140}/mnt/disk{1...6}/miniodata
3、After the second expansion, minio failed to start
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=miniotest
minio server http://10.3.73.{137...137}/mnt/disk{1...6}/miniodata http://10.3.73.{140...140}/mnt/disk{1...6}/miniodata http://10.3.73.{148...148}/mnt/disk{1...6}/miniodata

The error log info in 10.3.73.137 :
Error: http://10.3.73.140:9000/mnt/disk1/miniodata as has incorrect configuration: Expected endpoint http://10.3.73.137/mnt/disk1/miniodata, seen http://10.3.73.137:9000/mnt/disk1/miniodata (*fmt.wrapError)
       1: cmd/server-main.go:512:cmd.serverMain() 

The error log info in 10.3.73.140 and 10.3.73.148 :
Waiting for the first server to format the disks. 

Reference https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup: It says that "This expansion strategy works endlessly, so you can perpetually expand your clusters as needed."  Is there any problem with the configuration in the second expansion?

**Comment by klauspost** [comment]
Seems like one is missing the `:9000` port. Also please confirm that all your servers are the same version.

Try `minio server http://10.3.73.137:9000/mnt/disk{1...6}/miniodata http://10.3.73.140:9000/mnt/disk{1...6}/miniodata http://10.3.73.148:9000/mnt/disk{1...6}/miniodata`

**Comment by NoSadness** [comment]
> Seems like one is missing the `:9000` port. Also please confirm that all your servers are the same version.
> 
> Try `minio server http://10.3.73.137:9000/mnt/disk{1...6}/miniodata http://10.3.73.140:9000/mnt/disk{1...6}/miniodata http://10.3.73.148:9000/mnt/disk{1...6}/miniodata`

I confirm that the version on each node is the same。And i set the config " --address", the complete execution command is "nohup /opt/minioexpand/bin/minio server --config-dir /etc/minioexpand --address 10.3.73.137:9000   http://10.3.73.{137...137}/mnt/disk{1...6}/miniodatatest http://10.3.73.{140...140}/mnt/disk{1...6}/miniodatatest http://10.3.73.{148...148}/mnt/disk{1...6}/miniodatatest > /opt/minioexpand/logs/running.log 2>&1 &"

**Comment by NoSadness** [comment]
> Seems like one is missing the `:9000` port. Also please confirm that all your servers are the same version.
> 
> Try `minio server http://10.3.73.137:9000/mnt/disk{1...6}/miniodata http://10.3.73.140:9000/mnt/disk{1...6}/miniodata http://10.3.73.148:9000/mnt/disk{1...6}/miniodata`

Thanks，The sechond expansion was successful When the  ‘:9000‘ port  is added to the path。I hava a question，why first expansion was successful without add the  ‘:9000‘ port to path.

**Comment by klauspost** [comment]
No idea. That is why I asked you to confirm that you are running the same version on all servers.

**Comment by NoSadness** [comment]
> No idea. That is why I asked you to confirm that you are running the same version on all servers.

I have confirmed that they are all the same version。

**Comment by klauspost** [comment]
@harshavardhana I couldn't find the place where the port is added. Could you check if there is somewhere it isn't?

**Comment by johny-mnemonic** [comment]
I seem to have similar issue when trying to extend my cluster.
I am using systemd-service with following config:
```
# Volume to be used for MinIO server.
MINIO_VOLUMES="http://worker{21...36}/mnt/disks/minio-{0...3}"
# Use if you want to run MinIO on a custom port.
MINIO_OPTS="--address :20080"
# Root user for the server.
MINIO_ROOT_USER=minio
# Root secret for the server.
MINIO_ROOT_PASSWORD=minio123
```
Everything works fine with that config and cluster has 16 nodes with 4 drives per server = 64 drives in four 16-disk erasure sets.
But when I try to extend the cluster with another 8 servers (same setup with 4 drives per server) by modifying the VOLUMEs line like this:
```
MINIO_VOLUMES="http://worker{21...36}/mnt/disks/minio-{0...3} http://worker{37...44}/mnt/disks/minio-{0...3}"
```
I am getting following errors on the old servers:
```
Jun 22 15:52:54 worker21 minio[24418]: Error: http://worker37:20080/mnt/disks/minio-0 as has incorrect configuration: 404 Not Found (*fmt.wrapError)
Jun 22 15:52:54 worker21 minio[24418]: 1: cmd/server-main.go:512:cmd.serverMain()
```
And different error on new servers:
```
Jun 22 15:59:27 worker37 minio[17374]: Error: Read failed. Insufficient number of disks online (*errors.errorString)
Jun 22 15:59:27 worker37 minio[17374]: 5: cmd/prepare-storage.go:261:cmd.connectLoadInitFormats()
Jun 22 15:59:27 worker37 minio[17374]: 4: cmd/prepare-storage.go:310:cmd.waitForFormatErasure()
Jun 22 15:59:27 worker37 minio[17374]: 3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
Jun 22 15:59:27 worker37 minio[17374]: 2: cmd/server-main.go:592:cmd.newObjectLayer()
Jun 22 15:59:27 worker37 minio[17374]: 1: cmd/server-main.go:521:cmd.serverMain()
Jun 22 15:59:27 worker37 minio[17374]: Waiting for a minimum of 16 disks to come online (elapsed 45s)
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker38:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker39:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker40:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker41:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker42:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker43:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker44:20080/mnt/disks/minio-0: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker38:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker39:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker40:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker41:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker42:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker43:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker44:20080/mnt/disks/minio-1: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker38:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker39:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker40:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker41:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker42:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker43:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker44:20080/mnt/disks/minio-2: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker38:20080/mnt/disks/minio-3: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker39:20080/mnt/disks/minio-3: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker40:20080/mnt/disks/minio-3: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker41:20080/mnt/disks/minio-3: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker42:20080/mnt/disks/minio-3: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker43:20080/mnt/disks/minio-3: 404 Not Found
Jun 22 15:59:27 worker37 minio[17374]: Unable to read 'format.json' from http://worker44:20080/mnt/disks/minio-3: 404 Not Found
```
I double checked, that I have same MinIO version on all servers:
```
/usr/local/bin/minio --version
minio version RELEASE.2021-06-09T18-51-39Z
```
I also tried to add the storage class to the config, to make sure new servers are started with the same EC:
```
# Set storage redundancy
MINIO_STORAGE_CLASS_STANDARD=EC:4
```
But it didn't help.

I can telnet between servers on port 20080 just fine, so it doesn't seem to be a network issue.

**Comment by harshavardhana** [comment]
> > No idea. That is why I asked you to confirm that you are running the same version on all servers.
> 
> I have confirmed that they are all the same version。

Is the command line for expansion same across servers ? How is the input provided across servers ?

**Comment by johny-mnemonic** [comment]
> Is the command line for expansion same across servers ? How is the input provided across servers ?

For my case it is. 
At least `systemctl status minio` shows this command line on all servers:
```
/usr/local/bin/minio server --address :20080 http://worker{21...36}/mnt/disks/minio-{0...3} http://worker{37...44}/mnt/disks/minio-{0...3}
```
What kind of input? Is there some command one needs to execute to extend the cluster?

**Comment by harshavardhana** [comment]
@johny-mnemonic your issue looks like worker37 is not local to the node it's running, if this is some custom DNS it won't work.  The DNS needs to resolve to the host its running on..

The reason for the 404 error is because that it's not able to register the drives that are local to itself. Your issue is not the same as the issue reported here. 

Your issue simply is a DNS setup issue IMO.

**Comment by harshavardhana** [comment]
> minio server [http://10.3.73.{137...137}/mnt/disk{1...6}/miniodata](http://10.3.73.%7B137...137%7D/mnt/disk%7B1...6%7D/miniodata) [http://10.3.73.{140...140}/mnt/disk{1...6}/miniodata](http://10.3.73.%7B140...140%7D/mnt/disk%7B1...6%7D/miniodata) [http://10.3.73.{148...148}/mnt/disk{1...6}/miniodata](http://10.3.73.%7B148...148%7D/mnt/disk%7B1...6%7D/miniodata)

what is the point of expanding in this manner - by expanding like this you are not gaining any HA here @NoSadness - this setup is wrong.  You are providing ellipses within the same sequences i.e 137...137 you can simply specify 137 instead directly. 

Perhaps this may be the reason why your 2nd expansion doesn't work, but then expanding like this doesn't increase any HA simply creates more faulty setups. For real HA you need to spread out your setup across nodes. 

My suggestion is to throw away the existing setup instead add DNS names to all nodes such as node1, node2, node3 `http://node{1...3}/minio/data{1...6}/minio` in /etc/hosts and set them up as a single entity, and migrate your existing content using `mc mirror`.

**Comment by johny-mnemonic** [comment]
I am not sure what you mean by "worker37 is not local to the node it's running". I am not using any custom DNS and `nslookup worker37` resolves to the IP assigned to the host network interface (shown by `ip addr show eth1`).

I think I have found the issue though. I am able to `telnet workerXX 20080` even when MinIO is not running, so it seems I did some mistake while deploying these servers :-( It's interesting that MinIO doesn't complain that the port is already in use though.

Thanks for your time and sorry for hi-jacking this issue.

**Comment by NoSadness** [comment]
> > minio server [http://10.3.73.{137...137}/mnt/disk{1...6}/miniodata](http://10.3.73.%7B137...137%7D/mnt/disk%7B1...6%7D/miniodata) [http://10.3.73.{140...140}/mnt/disk{1...6}/miniodata](http://10.3.73.%7B140...140%7D/mnt/disk%7B1...6%7D/miniodata) [http://10.3.73.{148...148}/mnt/disk{1...6}/miniodata](http://10.3.73.%7B148...148%7D/mnt/disk%7B1...6%7D/miniodata)
> 
> what is the point of expanding in this manner - by expanding like this you are not gaining any HA here @NoSadness - this setup is wrong. You are providing ellipses within the same sequences i.e 137...137 you can simply specify 137 instead directly.
> 
> Perhaps this may be the reason why your 2nd expansion doesn't work, but then expanding like this doesn't increase any HA simply creates more faulty setups. For real HA you need to spread out your setup across nodes.
> 
> My suggestion is to throw away the existing setup instead add DNS names to all nodes such as node1, node2, node3 `http://node{1...3}/minio/data{1...6}/minio` in /etc/hosts and set them up as a single entity, and migrate your existing content using `mc mirror`.

Thank you for your reply, I will try your suggestion 。The reason why I do this is that there are some scenarios where only one machine is needed, so I'm doing a stand-alone expansion test。

**Comment by harshavardhana** [comment]
> I think I have found the issue though. I am able to `telnet workerXX 20080` even when MinIO is not running, so it seems I did some mistake while deploying these servers :-( It's interesting that MinIO doesn't complain that the port is already in use though.

We do but it depends on the port that is already opened up as SO_REUSEPORT @johny-mnemonic - if that is done then we have no way to fail since the kernel doesn't return an error.
