### ISSUE TITLE
How to use minio_s3_time_ttfb_seconds_distribution to show request latency

### ISSUE THREAD

**Issue by cobolbaby** [minio/minio#12540]
**Is your feature request related to a problem? Please describe.**

If I want to use the `minio_s3_time_ttfb_seconds_distribution` metric to make a chart in Grafana to show the request delay, how to write promql?

Because the metric is of the histogram type, there should be two statistical indicators `minio_s3_time_ttfb_seconds_distribution_count` and `minio_s3_time_ttfb_seconds_distribution_sum`, but they seem to be missing at present.

**Comment by cobolbaby** [comment]
@nitisht Could you give some suggestions?

**Comment by cobolbaby** [comment]
@nitisht Refer to [the official document](https://prometheus.io/docs/practices/histograms/#apdex-score), I have defined two indicators. But the second expression returns `NaN`, which means that [histograms are not compatible with prometheus histogram_quantile()](https://github.com/prometheus/prometheus/issues/4264).

-  the percentage of requests served within 100ms

```
sum(rate(minio_s3_time_ttfb_seconds_distribution{instance=~"$instance", le="0.100"}[5m])) by (api) /
  sum(rate(minio_s3_time_ttfb_seconds_distribution{instance=~"$instance", le="10.000"}[5m])) by (api) < 1
```

- the request duration within which you have served 95% of requests.

```
histogram_quantile(0.95, sum(rate(minio_s3_time_ttfb_seconds_distribution{instance=~"$instance"}[10m]))by (api, le))
```

![2021-09-07 15-09-12屏幕截图](https://user-images.githubusercontent.com/11460848/132301996-8a0fefd3-0672-4a86-ba7a-2126423fd537.png)

**Comment by cobolbaby** [comment]
Please reopen the issue if you can. @harshavardhana

**Comment by nitisht** [comment]
@cobolbaby the metric `minio_s3_time_ttfb_seconds_distribution` is a Gauge metric, not a histogram. So applying quantile is failing as expected. Ref: https://github.com/minio/minio/blob/master/cmd/metrics-v2.go#L719-L723

**Comment by cobolbaby** [comment]
> the metric minio_s3_time_ttfb_seconds_distribution is a Gauge metric

Isn't this value a cumulative value?

**Comment by harshavardhana** [comment]
> > the metric minio_s3_time_ttfb_seconds_distribution is a Gauge metric
> 
> Isn't this value a cumulative value?

Better to read here https://prometheus.io/docs/concepts/metric_types/#gauge

**Comment by cobolbaby** [comment]
@harshavardhana @nitisht  I mean, the value of `minio_s3_time_ttfb_seconds_distribution` I see is a cumulative value, which does not match the description of the guage type.

In addition, how do I calculate the quantiles of request latency?

**Comment by lddlww** [comment]
```
The histogram_quantile() function interpolates quantile values by assuming a linear distribution within a bucket. The highest bucket must have an upper bound of +Inf. (Otherwise, NaN is returned.)
```
can't find ```+inf``` in ```minio_s3_time_ttfb_seconds_distribution```

minio version：
```
minio version RELEASE.2022-02-07T08-17-33Z
```
