### ISSUE TITLE
Service minio server fails to start in Debian.

### ISSUE THREAD

**Issue by fojac** [minio/minio#12551]
## Expected Behavior
I installed minio using the .deb at [(https://min.io/download#/linux)] in a Debian bullseye LxC container
minio server is launching fine using `/usr/local/bin/minio server --address: 9000 /tmp/minio`
I did a `wget https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service` in `/etc/systemd/system/`
I would expect to see the service minio status showing a launched minio server.

## Current Behavior
I would expect the service to start.
I read there was a bug in the minio service file, which was fixed.

## Steps to Reproduce (for bugs)

When trying to do a service minio start I have the following:
```
service minio status
● minio.service - MinIO
     Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
    Drop-In: /run/systemd/system/service.d
             └─zzz-lxc-service.conf
     Active: failed (Result: exit-code) since Tue 2021-06-22 13:03:58 UTC; 34s ago
       Docs: https://docs.min.io
    Process: 28264 ExecStartPre=/bin/bash -c if [ -z "${MINIO_VOLUMES}" ]; then echo "Variable MINIO_VOLUMES not set in /etc/default/minio"; exit 1; fi (code=exited, status=217/USER)
        CPU: 3ms

Jun 22 13:03:58 me systemd[1]: minio.service: Failed with result 'exit-code'.
Jun 22 13:03:58 me systemd[1]: Failed to start MinIO.
Jun 22 13:03:58 me systemd[1]: minio.service: Scheduled restart job, restart counter is at 5.
Jun 22 13:03:58 me systemd[1]: Stopped MinIO.
Jun 22 13:03:58 me systemd[1]: minio.service: Start request repeated too quickly.
Jun 22 13:03:58 me systemd[1]: minio.service: Failed with result 'exit-code'.
Jun 22 13:03:58 me systemd[1]: Failed to start MinIO.
```
## Context
I would like to start minio as a service under Debian.

## Regression
 I don't know.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-06-17T00-10-46Z
* Server setup and configuration: Debian LxC bullseye
* Operating System and version (`uname -a`): me 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

My /etc/default/minio file is the following (note that I changed the user and password :-) ).

```
root@opencti:/etc/systemd/system# cat /etc/default/minio
MINIO_VOLUMES="/tmp/minio/"
MINIO_ROOT_USER="root"
MINIO_ROOT_PASSWORD="root"
MINIO_OPTS="--address :9000"
```

My /etc/systemd/system/minio file is the following :
```
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/

User=minio-user
Group=minio-user

EnvironmentFile=/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"

ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})
```

**Comment by harshavardhana** [comment]
@fojac you should first verify if `minio-user` is present on the system, if not create it or provide a user that exists on the system.  You also need to have minio-user provided write access to the backend. 

You can't expect MinIO to just start the service upon install - it's not Nginx I am afraid. This looks like a setup issue closing the issue.
