### ISSUE TITLE
Changing policy of bucket with B2 backend (s3 compatible) throws API error

### ISSUE THREAD

**Issue by redturtlepower** [minio/minio#12552]
## Expected Behavior

Changing bucket policy via web ui is possible

## Current Behavior

Changing bucket policy via web ui is not possible
Error Text: "Backblaze B2 does not support this API call".

## Possible Solution

I don't know minio source code. As I could not find the error message in the source code repo, I assume the message comes from B2 after a request from minio. Which request could this be? When B2 driver was removed because of s3 api compliance, did someone check whether B2 also supported the aws s3 json policies?

## Steps to Reproduce (for bugs)

1. Create minio with backblaze b2 backend
2. click on dots next to bucket and then "Edit policy" -> Forms shows up, and a error banner

## Context

I made my app release infrastructure almost ready only to find out that public access is not possible? Or is this only a web ui thing?

## Regression

no

## Your Environment

* Version used (`minio --version`): RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration: Minio running in docker
* Operating System and version (`uname -a`): Linux 5.4.0-72-generic Ubuntu x86_64

**Comment by harshavardhana** [comment]
B2 does not implement all S3 APIs @redturtlepower not sure what we can do here.

**Comment by redturtlepower** [comment]
Does minio allow public access via gateway to B2 buckets? My B2 bucket is public. This should just work. If not, I might missunderstand the purpose of minio. I want a selfhosted caching layer to a s3 compatible backend, with a web ui to browse files, and I don't care about bitrot and other advanced stuff. Is minio the right tool for this?

**Comment by harshavardhana** [comment]
> Does minio allow public access via gateway to B2 buckets? My B2 bucket is public. This should just work. If not, I might missunderstand the purpose of minio. I want a selfhosted caching layer to a s3 compatible backend, with a web ui to browse files, and I don't care about bitrot and other advanced stuff. Is minio the right tool for this?

The purpose of MinIO is build an on-prem object storage server on commodity hardware.

You are trying use gateway here - we do not support all S3 compatible vendors as we do not know the level of their compatibility and we never really have bandwidth to test all of them.

I just tested MinIO gateway works with AWS S3 and MinIO server this is sufficient for us. 

Beyond this feel free to debug the code and  we are happy to accept reasonable fixes. I don't think we have the bandwidth to look B2 S3 API as well.

**Comment by klauspost** [comment]
I suggest you contact Backblaze and ask them to support this API call.
