### ISSUE TITLE
Docker Minion can't build with SSL

### ISSUE THREAD

**Issue by narutomanchester** [minio/minio#12558]
Hello,

I'm running Minio with Docker, and want to has https. I follow up on the tutorial:
- Gen private.key and public.key by cmd: `openssl req        -newkey rsa:2048 -nodes -keyout 127.0.0.1:9000.key        -x509 -days 365 -out 127.0.0.1:9000.crt` . And put it inside `config/certs` folder
- Docker run with: `docker run -p 9000:9000   --name minio   -v /config:/.minio   -v /DATA:/data   -e "MINIO_ROOT_USER=abc"   -e "MINIO_ROOT_PASSWORD=abc"   minio/minio server /data`

I done with this, but it still runs with HTTP. Anyone can help me. 
Thank you in advance.

**Comment by harshavardhana** [comment]
@narutomanchester you need to put certs at `/root/.minio/` i.e `-v /config:/root/.minio`

**Comment by narutomanchester** [comment]
It works. Thank you a lot @harshavardhana
