### ISSUE TITLE
Object read by the client is still encrypted in server SSE-S3 mode

### ISSUE THREAD

**Issue by dl-g** [minio/minio#12553]
Object read by the client is still encrypted in server SSE-S3 mode

## Expected Behavior
In server SSE-S3 mode, the client requests each written object to be encrypted by the server. A get/read request should receive the object in decrypted form.

## Current Behavior
We wrote 4115 objects to the minio server. All but one passed our integrity checks. The bad object received by the client seems to be in encrypted form. Hexdump comparison between the client 'clear' copy and the server encrypted copy are identical. The server copy has 4096 additional bytes at the end.

Additional inspection on the server .minio.sys directory showed that this object does not have a fs.json file. All of the other good objects do. the minio server process did not crash or restart.

The client log showed that this PUT request for the bad object took 6282 msecs. The average PUT latency is 305 msecs.

## Steps to Reproduce (for bugs)

We only ran into one such corrupted object. Don't know how to reproduce.

## Context

We are building a file system using S3 objects. This corrupt object has introduced inconsistency in our system.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

minio version:  2019-10-12T01:39:57Z
server setup:
[root@localhost s3]# cat ~/run-minio 
export MINIO_REGION=us-west-1
export MINIO_ACCESS_KEY=XXXXXXXX
export MINIO_SECRET_KEY=YYYYYYYY
export MINIO_SSE_MASTER_KEY=my-minio-key:ZZZZZZZZ
/usr/bin/minio server --address :9000 /data/s3 &

[root@localhost s3]# find ~/.minio   
/root/.minio
/root/.minio/certs
/root/.minio/certs/CAs

OS: 
[root@localhost s3]# uname -a
Linux localhost.localdomain 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> export MINIO_SSE_MASTER_KEY=my-minio-key:ZZZZZZZZ

Using this kind of key is not supported anymore @dl-g please upgrade the setup and use real KMS systems like KES. Encrypting objects like this on a production system is not supported please use https://github.com/minio/kes and https://github.com/minio/minio/tree/master/docs/kms

https://github.com/minio/minio/blob/master/docs/kms/IAM.md#kms-iamconfig-encryption

Also if `fs.json` is missing for the object then we have no idea how to decrypt it, what is the backend filesystem being used here? - if you are using NFSv3 then this kind of issue will be expected.  Use NFSv4 instead .

Closing this issue since the release is too old and many things have changed since then.

**Comment by dl-g** [comment]
Thanks for the response.

XXX/YYY/ZZZ are not the actual values used.  We obscured them for security.

The backend filesystem is XFS over a locally attached disk.

The question is why is the fs.json file missing for this object?

**Comment by harshavardhana** [comment]
> The question is why is the fs.json file missing for this object?

We do not know @dl-g - since you are not using any protection mechanism on the backend - it can be gone because of many reasons. We can't really tell - you are also on a very old release so upgrade and redo your tests.

**Comment by dl-g** [comment]
the minio server runs on a dedicated environment. there are no external factors that could have removed the fs.json file. Not sure what the protection mechanism is in this context.

**Comment by harshavardhana** [comment]
> the minio server runs on a dedicated environment. there are no external factors that could have removed the fs.json file. Not sure what the protection mechanism is in this context.

There are always external factors, I don't see what else can we do here. 

Please upgrade and test - also invest in setting up real KMS instances for your objects using MASTER_KEY is only meant for testing purposes, if you wish to rely on a production environment - setup KMS.

**Comment by dl-g** [comment]
It is a test&dev environment. we are ok if encryption is disabled.

Hower, corrupting objects is not ok.  Is it possible that minio missed creating the fs.json file?  It took 6+ seconds to write the object and it was acknowledged successfully.  But the subsequent read failed our integrity check seconds later.

We will try the latest version. Just wondering if there are any known issues similar to this one.
