### ISSUE TITLE
Error information in log

### ISSUE THREAD

**Issue by evt-byte** [minio/minio#12561]
K8s deployment, distributed mode, 4 pods.
After successful deployment, the host can be configured, and files can be uploaded and downloaded.

But there will be an error message:
"error":{"message":"open /export/.minio.sys/buckets/.tracker.bin: invalid argument (*fs.PathError)"

And 

bash-4.4$ mc admin info myhost
...
 Drives: 0/0 OK 
...
0 B Used, 1 Bucket, 0 Objects
0 drives online, 0 drives offline

**No Drives online.**

## Expected Behavior

mc admin info host, in the before version, response:
pod1:
Drives: 1/1 OK 
pod2:
Drives: 1/1 OK 
pod3:
Drives: 1/1 OK 
pod4:
Drives: 1/1 OK 

## Current Behavior

All pods:
 Drives: 0/0 OK 

## Possible Solution

Error stack information at `minio/cmd/data-update-tracker.go:306`

code snippet:
              for _, drive := range drives {
			cacheFormatPath := pathJoin(drive, dataUpdateTrackerFilename)
			err := ioutil.WriteFile(cacheFormatPath, buf.Bytes(), os.ModePerm)
			if err != nil {
				if osIsNotExist(err) {
					continue
				}
				logger.LogIf(ctx, err)
				continue
			}
		}

ioutil.WriteFile(cacheFormatPath, buf.Bytes(), os.ModePerm)

## Steps to Reproduce (for bugs)

1.Install minio
2.Observation logs
3.Error found

## Context

The error information in the log will be synchronized to other services, and an alarm will appear

## Your Environment

* Version used (`minio --version`): RELEASE.2021-04-22
* Server setup and configuration: k8s
* Operating System and version (`uname -a`): linux

**Comment by klauspost** [comment]
@evt-byte Your system is having serious issues if this is reported. Fill out the requested information instead of what you just feel like.

This is a regular file write that is failing.

**Comment by evt-byte** [comment]
@klauspost We upgraded the version of Minio to get this error log, what is the `.tracker.bin`. Does the previous version have this file?

**Comment by klauspost** [comment]
Yes.

**Comment by evt-byte** [comment]
@klauspost Hi, klauspost, I have completed the relevant information. Why is there such a error? Is the number(0/0) of drives caused by this error?

Thanks
BR//Evt

**Comment by klauspost** [comment]
> Server setup and configuration: k8s

This is where your problem lies. The servers are either unable to communicate or unable to access disks, looks like the latter. Since you provide no information about it, there is nothing we can do to help.

Ensure that disks are writable.
