### ISSUE TITLE
Docker Swarm Support droped?

### ISSUE THREAD

**Issue by jwillmer** [minio/minio#12560]
I saw that all documentation regarding docker swarm was removed. Does that mean it is not supported anymore? I was looking into minio for exactly that purpose. Is there some news regarding this change?

**Comment by harshavardhana** [comment]
> I saw that all documentation regarding docker swarm was removed. Does that mean it is not supported anymore? I was looking into minio for exactly that purpose. Is there some news regarding this change?

Docker swarm is a dead product, use kubernetes instead. 

We only support k8s for distributed clusters in production deployments. 

You can still use swarm if you have the knowhow but it is not something we are planning to support in production. 

The documentation is simply removed to keep things simple.

**Comment by jwillmer** [comment]
Docker Swarm is dead but not [Docker Swarm Mode](https://docs.docker.com/engine/swarm/):

> Docker Swarm mode is built into the Docker Engine. **Do not confuse Docker Swarm mode with Docker Classic Swarm which is no longer actively developed.**
