### ISSUE TITLE
Policy Condition failed when policy condition contains ["starts-with","$success_action_status",""]

### ISSUE THREAD

**Issue by Shanbw** [minio/minio#12567]
The policy that we set when uploading files contains `["starts-with","$success_action_status",""]`, an error will be reported：
error message：Access Denied. (Invalid according to Policy: Policy Condition failed)

I try to change it to `["eq","$success_action_status","200"]`, or remove this Policy Condition, no error will be reported, and the upload can be successful.

But we try to use `aws` or `ceph` these common s3 object stores, which support `["starts-with","$success_action_status",""]`, and also support `["eq","$success_action_status ","200"]`, and if the Policy Condition is deleted when the form field contains `success_action_status`, an error will be reported.

## Expected Behavior
upload success

## Current Behavior
The upload fails and the result is as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied. (Invalid according to Policy: Policy Condition failed)</Message>
    <BucketName>test-pub</BucketName>
    <Resource>/test-pub</Resource>
    <RequestId>168B2C939B28736C</RequestId>
    <HostId>abb7fb01-7ead-47e5-9741-af50555b39b8</HostId>
</Error>
```

## Possible Solution
1. Modify `["starts-with","$success_action_status",""]` to `["eq","$success_action_status","200"]`
2. Delete the  Policy Condition : `["starts-with","$success_action_status",""]`

## Conclusion
This will make minio not very compatible with aws s3

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2021-06-17T00-10-46Z
* Operating System and version (`uname -a`):  Darwin MacBook-Pro-3.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by ebozduman** [comment]
@Shanbw 

I can reproduce the issue.
Working on a fix.

I think this issue was supposed to be reported against minio-go. 
You were using minio-go, right?
Please also copy and paste your script.

**Comment by ebozduman** [comment]
@Shanbw

Please also copy and paste your script.

**Comment by Shanbw** [comment]
> @Shanbw
> 
> I can reproduce the issue.
> Working on a fix.
> 
> I think this issue was supposed to be reported against minio-go.
> You were using minio-go, right?
> Please also copy and paste your script.

I did not use minio-go, I used java call

**Comment by ebozduman** [comment]
@Shanbw 
Can you copy/paste your script?
I'd also like to verify the fix with your script.
