### ISSUE TITLE
Can't Connect to Minio with Python API

### ISSUE THREAD

**Issue by narutomanchester** [minio/minio#12569]
I set up Minio with TLS via Docker. It runs successfully. Like this
<img width="627" alt="Screen Shot 2021-06-24 at 3 43 55 PM" src="https://user-images.githubusercontent.com/18007841/123232070-fdd24980-d502-11eb-9631-1fa15d59ec70.png">
However, When I try to connect to Minio via Python, it doesn't work. It comes with an exception: `HTTPSConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /data?location= (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`

My code: `client = Minio(
        "127.0.0.1:9000",
        access_key="MY_ACCESS_KEY",
        secret_key="MY_SECRET_KEY"
    )`
    
Anyone can help me. Thanks in advance.

**Comment by harshavardhana** [comment]
Make sure to `secure=False` in your client constructor when you are running in non-TLS mode.

**Comment by narutomanchester** [comment]
@harshavardhana Thank you for your response. As I said above, I'm running with TLS. So I think `secure=False` is required.

**Comment by harshavardhana** [comment]
> @harshavardhana Thank you for your response. As I said above, I'm running with TLS. So I think `secure=False` is required.

If you are running with TLS make sure to trust the certificate first by specifying SSL_TLS_CERT env or creating a custom transport.

**Comment by narutomanchester** [comment]
hello @harshavardhana. I still don't know how to fix it. Can you give me a tutorial?

**Comment by balamurugana** [comment]
@narutomanchester If you are using self-signed/untrusted TLS certificate, export env var `SSL_CERT_FILE` with path to your certificate file as value or create/pass your own `http_client` to `Minio` constructor. Refer https://github.com/minio/minio-py/blob/master/minio/api.py#L143

**Comment by verydemo** [comment]
Java API set  SSL_TLS_CERT env invalid, i should how to do
