### ISSUE TITLE
bucket bandwidth limit

### ISSUE THREAD

**Issue by liutao5689** [minio/minio#12570]
I set some bucket policy download, and then I can download file in this bucket. But I want limit one bucket download speed limit to 1Mbps and the other bucket limit to 10Mbps.  So I want to use mc command like "mc admin bucket  bandwidth set 1Mbps" to limit a bucket download bandwidth.

**Comment by klauspost** [comment]
We will consider your request, however there are no current plans for such a feature.

**Comment by harshavardhana** [comment]
> I set some bucket policy download, and then I can download file in this bucket. But I want limit one bucket download speed limit to 1Mbps and the other bucket limit to 10Mbps. So I want to use mc command like "mc admin bucket bandwidth set 1Mbps" to limit a bucket download bandwidth.

Bucket bandwidth is meant for `replication` targets it is not meant to set throttling for incoming S3 API connections. You can easily do this using nginx based throttling for different bucket `locations /bucket` 

This doesn't need to be present on MinIO to be complicated.
