### ISSUE TITLE
Server fails to initialize after upgrading from 2021-02-11T08:23:43Z to 2021-06-17T00-10-46Z

### ISSUE THREAD

**Issue by macklin-10x** [minio/minio#12576]
## Expected Behavior
The server initializes correctly after upgrading to the newest version from a prior 2021 version.

## Current Behavior
After using mc admin to upgrade the server to the latest version, the server does not correctly initialize, and repeatedly logs this error:
`Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: config file not found)`

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-06-17T00-10-46Z`
* Operating System and version (`uname -a`): `Linux [REDACTED] 4.4.218-1.el7.elrepo.x86_64 #1 SMP Thu Apr 2 14:46:23 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
`mc admin update`  has an issue when downloading binaries from dl.min.io - it is better you download it once and copy the binaries to all hosts to restart them together.

From whatever it looks like an unusual that you are seeing 'config not found'

Can you share your command line?  And how you are running this ? 

Also you can simply do `rm -rf /backend/.minio.sys/config/config.json` .. also are you running the setup in multiple pools ?

**Comment by macklin-10x** [comment]
This is running on a single server.  Nothing special on the command line, just running `minio server /shared`.

**Comment by macklin-10x** [comment]
Even if I delete or rename `/shared/.minio.sys/config/config.json` or even rename the entire `config` directory I still get the same error.

**Comment by macklin-10x** [comment]
@harshavardhana helped diagnose this down to an issue with credential migration on top of NFS v3; he suggested running minio in nas gateway mode `minio gateway nas /shared` and it initialized correctly.

**Comment by harshavardhana** [comment]
Thanks, @macklin-10x will try NFSv3 for migration.
