### ISSUE TITLE
Not able to stream audio after uploading it into minio

### ISSUE THREAD

**Issue by meeoh** [minio/minio#12585]
Not sure if im just missing something here about how minio works, but I uploaded in m4a into minio, and when trying to visit the url in chrome I get an empty screen that looks like this and is unplayable.

The url im visiting is something like http://192.168.86.106:9000/bucket_name/filename.m4a. The audio is definitely a playable file

![image](https://user-images.githubusercontent.com/5509365/123555525-52b8ce80-d754-11eb-935b-6e1ecbfe8264.png)

## Expected Behavior
Would expect that I could play the audio in chrome

## Current Behavior
Audio is unplayable

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> The url im visiting is something like http://192.168.86.106:9000/bucket_name/filename.m4a. The audio is definitely a playable file

First you need to make sure your object is publicly readable - have you made sure to enable your bucket to be publicly readable using `mc policy set download alias/bucket_name`?

**Comment by shameelabd** [comment]
I think it should be public, I used the browser to set a policy: 

![image](https://user-images.githubusercontent.com/61977684/123556136-85b09180-d757-11eb-991e-4ece88994b7e.png)

And was able to visit the resource incognito

**Comment by meeoh** [comment]
I think it should be public, I used the browser to set a policy: 

![image](https://user-images.githubusercontent.com/61977684/123556136-85b09180-d757-11eb-991e-4ece88994b7e.png)

And was able to visit the resource incognito

**Comment by harshavardhana** [comment]
> I think it should be public, I used the browser to set a policy:

Can you do `curl -v --head http://192.168.86.106:9000/bucket_name/filename.m4a` - what is the output?

**Comment by meeoh** [comment]
> > I think it should be public, I used the browser to set a policy:
> 
> Can you do `curl -v --head http://192.168.86.106:9000/bucket_name/filename.m4a` - what is the output?

```
>curl -v --head http://192.168.86.106:9000/voices/b133e3a370cc739a_1624817974888.m4a                                                 Sun Jun 27 15:01:30 2021
*   Trying 192.168.86.106...
* TCP_NODELAY set
* Connected to 192.168.86.106 (192.168.86.106) port 9000 (#0)
> HEAD /voices/b133e3a370cc739a_1624817974888.m4a HTTP/1.1
> Host: 192.168.86.106:9000
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Length: 734101
Content-Length: 734101
< Content-Security-Policy: block-all-mixed-content
Content-Security-Policy: block-all-mixed-content
< Content-Type: audio/mp4
Content-Type: audio/mp4
< ETag: "494ff72f099efec41559e6b6a70fc353"
ETag: "494ff72f099efec41559e6b6a70fc353"
< Last-Modified: Sun, 27 Jun 2021 18:19:34 GMT
Last-Modified: Sun, 27 Jun 2021 18:19:34 GMT
< Server: MinIO
Server: MinIO
< Vary: Origin
Vary: Origin
< X-Amz-Request-Id: 168C85A0F58FBD30
X-Amz-Request-Id: 168C85A0F58FBD30
< X-Xss-Protection: 1; mode=block
X-Xss-Protection: 1; mode=block
< Date: Sun, 27 Jun 2021 19:01:31 GMT
Date: Sun, 27 Jun 2021 19:01:31 GMT

<
* Connection #0 to host 192.168.86.106 left intact
* Closing connection 0
```

**Comment by harshavardhana** [comment]
@meeoh can you try `mplayer http://192.168.86.106:9000/voices/b133e3a370cc739a_1624817974888.m4a ` ? 

Here is how I tried locally. 

```
~ mc stat play/testbucket/
Name      : Z Motion - from YouTube.mp3
Date      : 2021-06-27 12:06:21 PDT
Size      : 4.5 MiB
ETag      : 3cc22dbafc175d3beb64a0d00073be60
Type      : file
Metadata  :
  Content-Type: audio/mpeg

~ mplayer "https://play.min.io/testbucket/Z Motion - from YouTube.mp3"
MPlayer 1.3.0 (Debian), built with gcc-10 (C) 2000-2016 MPlayer Team
do_connect: could not connect to socket
connect: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing https://play.min.io/testbucket/Z Motion - from YouTube.mp3.
libavformat version 58.45.100 (external)
Audio only file format detected.
==========================================================================
Opening audio decoder: [mpg123] MPEG 1.0/2.0/2.5 layers I, II, III
AUDIO: 44100 Hz, 2 ch, s16le, 128.0 kbit/9.07% (ratio: 16000->176400)
Selected audio codec: [mpg123] afm: mpg123 (MPEG 1.0/2.0/2.5 layers I, II, III)
==========================================================================
AO: [pulse] 44100Hz 2ch s16le (2 bytes per sample)
Video: no video
Starting playback...
A:   5.0 (05.0) of 295.0 (04:55.0)  0.5%

```

Seems to be playing fine for me.

**Comment by meeoh** [comment]
> @meeoh can you try `mplayer http://192.168.86.106:9000/voices/b133e3a370cc739a_1624817974888.m4a ` ?
> 
> Here is how I tried locally.
> 
> ```
> ~ mc stat play/testbucket/
> Name      : Z Motion - from YouTube.mp3
> Date      : 2021-06-27 12:06:21 PDT
> Size      : 4.5 MiB
> ETag      : 3cc22dbafc175d3beb64a0d00073be60
> Type      : file
> Metadata  :
>   Content-Type: audio/mpeg
> 
> ~ mplayer "https://play.min.io/testbucket/Z Motion - from YouTube.mp3"
> MPlayer 1.3.0 (Debian), built with gcc-10 (C) 2000-2016 MPlayer Team
> do_connect: could not connect to socket
> connect: No such file or directory
> Failed to open LIRC support. You will not be able to use your remote control.
> 
> Playing https://play.min.io/testbucket/Z Motion - from YouTube.mp3.
> libavformat version 58.45.100 (external)
> Audio only file format detected.
> ==========================================================================
> Opening audio decoder: [mpg123] MPEG 1.0/2.0/2.5 layers I, II, III
> AUDIO: 44100 Hz, 2 ch, s16le, 128.0 kbit/9.07% (ratio: 16000->176400)
> Selected audio codec: [mpg123] afm: mpg123 (MPEG 1.0/2.0/2.5 layers I, II, III)
> ==========================================================================
> AO: [pulse] 44100Hz 2ch s16le (2 bytes per sample)
> Video: no video
> Starting playback...
> A:   5.0 (05.0) of 295.0 (04:55.0)  0.5%
> ```
> 
> Seems to be playing fine for me.

Hm it seems to be an issue with my m4a files themselves. I downloaded a sample mp3 file and uploaded that into minio and it works fine. I also renamed it to an m4a and it still worked fine. Thanks for the debugging help @harshavardhana, will play around and figure out whats wrong with my files and update this issue with any other findings
