### ISSUE TITLE
Server expects 'storage' API version 'v37', instead found 'v37' - *rolling upgrade is not allowed*

### ISSUE THREAD

**Issue by mostafa8026** [minio/minio#12583]
After expanding minio with operator, I got this error in the newly create server:
```
Unable to read 'format.json' from https://storage1-zone-0-0.storage1-hl.min3.svc.cluster.local:9000/export0:  'storage' API version 'v37', instead found 'v37' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-06-17T00-10-46Z)
```

## Expected Behavior
expanded without problem

## Current Behavior
buggy

## Possible Solution
I changed both servers image to the RELEASE.2021-06-17T00-10-46Z, but the error insists.

## Steps to Reproduce (for bugs)

1. expand tenant with new one, older one must be RELEASE.2021-06-17T00-10-46Z
2. the newly generated one get latest image
3. and after changing both to the RELEASE.2021-06-17T00-10-46Z
4. error insists

## Context
k8s/minio/operator

## Your Environment

* Version used (`minio --version`): RELEASE.2021-06-17T00-10-46Z
* Server setup and configuration: k8s/minio/operator 4.1.2
* Operating System and version (`uname -a`):
Linux storage1-ss-1-0 5.4.0-47-generic 51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mostafa8026** [comment]
I get below error when run: mc admin update
```
$ mc admin update sg
Server `sg` already running the most recent version 2021-06-17T00:10:46Z of MinIO
```

**Comment by harshavardhana** [comment]
Is this the same problem that was closed in https://github.com/minio/operator/issues/692 ?

**Comment by harshavardhana** [comment]
Looks like yes closing this issue.

**Comment by mostafa8026** [comment]
Yes it is. Sorry. I forget to close issue in this repo.
