### ISSUE TITLE
webhook event does not send authorization headers

### ISSUE THREAD

**Issue by Athius** [minio/minio#12597]
## Expected Behavior
An Authorization Bearer must be present on the HTTP headers if the auth_token is set

## Current Behavior
No Authorization Bearer is present

## Possible Solution
?
I don't remember which version I had, but previously this feature worked great.

## Steps to Reproduce (for bugs)
1. .\mc.exe admin config set myminio notify_webhook:1 endpoint="https://myserver.com/webhook" auth_token="my_string_token" queue_limit="0"
2. .\mc.exe admin service restart myminio/
3. .\mc.exe admin config get myminio/ notify_webhook
4. .\mc.exe event add myminio/mybucket arn:minio:sqs::1:webhook --event "put" --suffix "*.json"
notify_webhook:1 endpoint=https://myserver.com/webhook auth_token=my_string_token queue_limit=0 queue_dir= client_cert= client_key=
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
5. .\mc.exe cp .\test.json myminio/mybucket

## Your Environment
* Version used (`minio --version`):
.\mc.exe admin info myminio
   myminio.url
   Uptime: 11 minutes
   Version: 2021-06-17T00:10:46Z
   Network: 1/1 OK

* Server setup and configuration:
* Operating System and version (`uname -a`):
docker image: minio/minio:latest

**Comment by harshavardhana** [comment]
Nothing has changed here I see that the "Authorization" header is still correctly set.

**Comment by Athius** [comment]
Thank you for your answer. 
I use fastapi as my webhook receiver. I didn't change anything on this part. 

The only change I did was replacing the url of an existing event on minio part. 

I will try to find a way to see more info inside minio logs.

**Comment by harshavardhana** [comment]
I configured a simple webhook I see "Authorization" header @Athius 

```
POST / HTTP/1.1
Host: localhost:4222
Authorization: Bearer mytoken
Content-Length: 993
Content-Type: application/json
User-Agent: Go-http-client/1.1

{"EventName":"s3:ObjectCreated:Put","Key":"test/hosts","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2021-06-29T17:55:57.390Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"minio"},"requestParameters":{"principalId":"minio","region":"","sourceIPAddress":"127.0.0.1"},"responseElements":{"content-length":"0","x-amz-request-id":"168D1F35FD5A28AD","x-minio-deployment-id":"40299ffe-525f-4ac7-a341-b127ecb78e41","x-minio-origin-endpoint":"http://10.0.0.67:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"test","ownerIdentity":{"principalId":"minio"},"arn":"arn:aws:s3:::test"},"object":{"key":"hosts","size":525,"eTag":"5b377a06b0c7f323235594444b907661","contentType":"application/octet-stream","userMetadata":{"content-type":"application/octet-stream"},"sequencer":"168D1F3603131493"}},"source":{"host":"127.0.0.1","port":"","userAgent":"MinIO (linux; amd64) minio-go/v7.0.12 mc/DEVELOPMENT.GOGET"}}]}
```

**Comment by harshavardhana** [comment]
This seems to be working fine, closing this issue. Please let us know - I can't see how this is not working.  The only reason would be the server not being able to notify the webhook target due to some network issues.
