### ISSUE TITLE
Unable to upload multiple files simultaneously

### ISSUE THREAD

**Issue by ragorilla** [minio/minio#12594]
When I try to upload multiple files, exactly more than 4 files, to minio at the same time, I always get the following error response:
```
ErrorResponse(code=SlowDown, message=Resource requested is unreadable, please reduce your request rate, bucketName=hitbox, objectName=49ea7e0f-27a2-459e-ba4e-64b8380fe71f, resource=/hitbox/49ea7e0f-27a2-459e-ba4e-64b8380fe71f, requestId=168CFC9534B3D342, hostId=d0b13ce9-c956-4b3d-a826-f8f376b25a68)
request={method=PUT, url=http://minio:9000/hitbox/49ea7e0f-27a2-459e-ba4e-64b8380fe71f?uploadId=53814697-ede6-4dec-b5ae-5bb5774fedda&partNumber=312, headers=Content-Encoding: aws-chunked
x-amz-decoded-content-length: 5242880
Host: minio:9000
User-Agent: MinIO (amd64; amd64) minio-java/dev
x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
x-amz-date: 20210629T072123Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210629/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*
}
response={code=503, headers=Accept-Ranges: bytes
Content-Length: 394
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Retry-After: 120
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 168CFC9534B3D342
X-Xss-Protection: 1; mode=block
Date: Tue, 29 Jun 2021 07:21:23 GMT
}
```

Minio is running in distributed mode as 4 pods on my setup:
```
minio-0                                         1/1     Running     0          92m
minio-1                                         1/1     Running     0          92m
minio-2                                         1/1     Running     0          92m
minio-3                                         1/1     Running     0          92m
```

I use Java Client API (6.0.13) as minio client and I cannot find any console log related to this error.
FYI, current api throttling configuration is like below: 
```
# mc admin config get minio api
api requests_max=50 requests_deadline=2h cors_allow_origin=* cluster_deadline=10s remote_transport_deadline=2h list_quorum=optimal extend_list_cache_life=0s replication_workers=250 replication_failed_workers=8 replication_failed_workers=8
```

When requests_max is set to 0 (unlimited), this error also occurred.

## Expected Behavior

I should be able to upload multiple files to minio at the same time.

## Current Behavior

When I try to upload more than 4 files, it failed with above error message.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-06-17T00-10-46Z
* Server setup and configuration: OpenShift 4.6
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
Could you post any output from the server logs that is produced when the error is returned?

Could you check your setup with [warp](https://github.com/minio/warp#download), for example `warp put --host=s3-server{1...8}:9000 --access-key=minio --secret-key=minio123 --autoterm`. Upload the zst output file.

**Comment by harshavardhana** [comment]
@ragorilla that doesn't really make sense - looks like either you are running out of disk space or you really have a terrible disk/network infrastructure that is giving up on concurrent I/O.

**Comment by ragorilla** [comment]
> Could you post any output from the server logs that is produced when the error is returned?
there is no minio pod logs that is produced when the error is returned.

> Could you check your setup with [warp](https://github.com/minio/warp#download), for example `warp put --host=s3-server{1...8}:9000 --access-key=minio --secret-key=minio123 --autoterm`. Upload the zst output file.
minio has

**Comment by ragorilla** [comment]
> @ragorilla that doesn't really make sense - looks like either you are running out of disk space or you really have a terrible disk/network infrastructure that is giving up on concurrent I/O.

@harshavardhana As your comment, I tried to change to persistent volumes provided by another storage class, then it worked without the error.

Could you provide recommended persistence volume/disk requirement to cover the concurrent I/O or how to check whether my disk infrastructure is terrible for minio?

**Comment by harshavardhana** [comment]
> > @ragorilla that doesn't really make sense - looks like either you are running out of disk space or you really have a terrible disk/network infrastructure that is giving up on concurrent I/O.
> 
> @harshavardhana As your comment, I tried to change to persistent volumes provided by another storage class, then it worked without the error.
> 

That's exactly what I meant is that make sure to use local PVs or use direct-csi project to help provision PVs.

> Could you provide recommended persistence volume/disk requirement to cover the concurrent I/O or how to check whether my disk infrastructure is terrible for minio?

You already did by changing storage class it worked fine, there is no issue on MinIO end.

Closing this issue as non MinIO problem.
