### ISSUE TITLE
Dose minio support zfs storage pool?

### ISSUE THREAD

**Issue by SigmaGavin** [minio/minio#12602]
I have 32 disks in one computer.So i use the zfs to create a strorage pool as a big   driver. but, when i use the minio to mount the path,there is an error.

here are my start cmd:
`docker run -d --name minio   --restart=always --net=host   -e MINIO_ROOT_USER=minio   -e MINIO_ROOT_PASSWORD=minio123   -v /pool-hdd:/mnt/data   minio/minio server   --address xx.xx.xx.xx:9000   http://minio-zfs-data{1...4}/mnt/data`

here are my error:
API: SYSTEM()
Time: 03:03:03 UTC 06/30/2021
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:317:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
       2: cmd/server-main.go:592:cmd.newObjectLayer()
       1: cmd/server-main.go:521:cmd.serverMain()
Waiting for a minimum of 2 disks to come online (elapsed 1h8m7s)

here are my zfs pool:

root@minio-zfs-shijuezu3:/pool-hdd# df -h | grep hdd
pool-hdd                           217T  384K  217T   1% /pool-hdd

**Comment by harshavardhana** [comment]
We do you need O_DIRECT support for ZFS to use MinIO on ZFS.
