### ISSUE TITLE
startAfter (start-after) is ignored on s3 gateway

### ISSUE THREAD

**Issue by roelarents** [minio/minio#12611]
When using minio as s3 gateway, the `startAfter` parameter "falls off".

## Expected Behavior
I expected (but perhaps wrongfully) to get a list of objects whose key starts after (greater than) the one given in the `startAfter` (or `start-after`) parameter.

## Current Behavior
The startAfter parameter is ignored and all objects are returned.

## Possible Solution
* I read [something](https://github.com/minio/minio-go/issues/1396) about a _marker_ that should be similar to the startAfter parameter. Perhaps the startAfter can be converted to that.
* The startAfter parameter is [ignored](https://github.com/minio/minio/commit/778e9c864f67faa564fd17c1037902772b1e61fb#diff-afd109a2c6495acb9c175071eb0bf8a1f7114563e675173c0e952df6b3e7812cL384) since the [update from minio sdk v6 to v7](https://github.com/minio/minio/pull/10042). The issue suggests that v6 could still be used for s3 gateway.

## Steps to Reproduce (for bugs)

1. Run an s3 storage (e.g. minio itself) and put some files in a bucket
2. Get a listing of the bucket, set the startAfter param to a key halfway. E.g. [using the aws go sdk](https://github.com/aws/aws-sdk-go/blob/main/service/s3/api.go#L24979)
3. Observe that you get half the objects, as desired
4. Run `minio gateway s3 <that storage>`
5. Get a listing of the bucket from the gateway storage
6. Observe that you get everything

## Context
We have a minio s3 gateway running in an Azure kubernetes cluster, fronting for an azure blob storage in the back. But in our integration tests, with k3s, we use another minio storage in the back, like in the steps to reproduce.

## Regression
Yes, I suppose it worked before the [update from minio sdk v6 to v7](https://github.com/minio/minio/pull/10042)

## Your Environment
* Version used (`minio --version`): master today

**Comment by harshavardhana** [comment]
Thanks for opening the issue, we shall fix it starting with minio-go
