### ISSUE TITLE
MinIO OpenId does not work after server restart

### ISSUE THREAD

**Issue by Shratha4** [minio/minio#12614]
When an environment is rebooted, Minio SSO is deactivated and the Minio UI asks for credentials.

After the environment is restarted OpenId option is not available, it asks for secret key and access key.

 Suggest a fix for the issue
![image](https://user-images.githubusercontent.com/86821151/124232206-fd533780-db2e-11eb-84ec-fa2bc223aaec.png)

**Comment by harshavardhana** [comment]
@Shratha4 not sure what you did - neither you have told us any details of your setup. You have willfully removed all the issue template that asks for such details. 

You need to help us to help you.  Closing this issue as non-actionable with nothing relevant present in the issue to debug.

**Comment by Shratha4** [comment]
MinIO OpenId is not present after rebooting the system. After the Environment is restarted it asks for access key and secret key.

Expected Behavior
After restart of the Environment MinIO UI should be like this 
![image](https://user-images.githubusercontent.com/86821151/124238579-62f6f200-db36-11eb-8131-bc2532bae510.png)

Current Behavior
After restart of the Environment MiniIo UI is likethis
![image](https://user-images.githubusercontent.com/86821151/124238666-7dc96680-db36-11eb-9630-dc9a9343fa07.png)
 Login with OpenId is not present. 

Possible Solution
If I try to delete the minio pod and then load the page its present but suddenly after restart its not present. 

Steps to Reproduce (for bugs)
First I thought it had etcd issue and added etcd to be deployed at init container stage and tried, but its having no effect.

Context
I want login with OpenId to be available because its easy for to login. 

Your Environment
minio version RELEASE.2020-11-13T20-10-18Z
