### ISSUE TITLE
GetObject does not support zip option

### ISSUE THREAD

**Issue by xuzikun2003** [minio/minio#12619]
On the minio website, a folder can be downloaded as a zip
![image](https://user-images.githubusercontent.com/25806935/124369394-5ea70380-dc20-11eb-93dd-1841db85080b.png)

However, the class GetObjectArgs provided by the SDK does not provide a zip option
https://minio-java.min.io/io/minio/GetObjectArgs.html

I am wondering why the SDK cannot support zip download but the web UI can support.

**Comment by harshavardhana** [comment]
There is no download as zip API in S3, you need to write this yourself in your application.
