### ISSUE TITLE
Getting connection closed after approx 15 minutes from minio

### ISSUE THREAD

**Issue by shrikantgarg17** [minio/minio#12616]
When trying to get large file while creating inputstream from presigned download url , it gives connection closed error after around 15-20 minsutes.

Inputstream should not break and complete file should be read. In this case for example file contains 100 k records and after reading around 60k records it break.

following is the reference code 
// getting pre signed url
String signedURL = getDownloadURL(id, requestHeaders);

// returning inputstream
return new URL(signedURL).openStream();

Now, while reading from this input stream it breaks after reading dome record.

Even i tried directly reading it from minio storage

fileInputStream= s3Client.getObject("bucket-name","object-name").getObjectContent();

but this also breaks after some time.

This is how i am making s3 connection

`
AWSCredentials credentials = new BasicAWSCredentials(accessKey, secretKey);
		
		ClientConfiguration clientConfig = new ClientConfiguration().withRequestTimeout(5000);
	    clientConfig.setUseTcpKeepAlive(true);
	    

	    s3Client = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(credentials))
	       .withEndpointConfiguration(new EndpointConfiguration(endpointURL, region)).withPathStyleAccessEnabled(true)
	       .withClientConfiguration(clientConfig).build();
`

Minio Details

![image](https://user-images.githubusercontent.com/56015673/124262703-f8eb4680-db4f-11eb-9872-85a1f81a2ee2.png)

**Comment by klauspost** [comment]
There are no timeouts in MinIO. How are you running MinIO?

You could always try upgrading to the newest version.

**Comment by shrikantgarg17** [comment]
'Caused by: java.lang.IllegalStateException: ConnectionClosedException reading next record: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 37,181,768; received: 18,350,080)\n'

This is the exception i see in logs

**Comment by shrikantgarg17** [comment]
we are running minio in kubernetes pod in openshift

**Comment by klauspost** [comment]
@shrikantgarg17 Is anything logged on the server side? Please upgrade and report back.

**Comment by shrikantgarg17** [comment]
Nopes ..nothing is getting in server logs

**Comment by shrikantgarg17** [comment]
There are some random error logs but i dont think they are related to this issue
![image](https://user-images.githubusercontent.com/56015673/124276205-21c80780-db61-11eb-9e2e-8e348b757928.png)

API: SYSTEM()
Time: 23:08:02 UTC 07/01/2021
DeploymentID: b16c6dda-b08f-4fe4-ac45-3f78420d0278
Error: file not found
       4: github.com/minio/minio@/cmd/data-usage.go:421:cmd.updateUsage()
       3: github.com/minio/minio@/cmd/posix.go:342:cmd.(*posix).CrawlAndGetDataUsage()
       2: github.com/minio/minio@/cmd/posix-diskid-check.go:43:cmd.(*posixDiskIDCheck).CrawlAndGetDataUsage()
       1: github.com/minio/minio@/cmd/xl-v1.go:341:cmd.xlObjects.crawlAndGetDataUsage.func2()

**Comment by shrikantgarg17** [comment]
There are some random error logs at server but i dont think they are related to this issue

API: SYSTEM()
Time: 23:08:02 UTC 07/01/2021
DeploymentID: b16c6dda-b08f-4fe4-ac45-3f78420d0278
Error: file not found
       4: github.com/minio/minio@/cmd/data-usage.go:421:cmd.updateUsage()
       3: github.com/minio/minio@/cmd/posix.go:342:cmd.(*posix).CrawlAndGetDataUsage()
       2: github.com/minio/minio@/cmd/posix-diskid-check.go:43:cmd.(*posixDiskIDCheck).CrawlAndGetDataUsage()
       1: github.com/minio/minio@/cmd/xl-v1.go:341:cmd.xlObjects.crawlAndGetDataUsage.func2()

**Comment by harshavardhana** [comment]
@shrikantgarg17 please upgrade and test ..

**Comment by harshavardhana** [comment]
@shrikantgarg17 this looks like a client-side issue, there is no real timeout on the server that times out at 15minutes from what it looks like there is a timeout at 

- At load balancer let's say you are using ingress and you have perhaps a misconfigured timeout for reads such as `proxy_read_timeout` 
- Or your AmazonS3Client is getting garbage collected by Java - https://stackoverflow.com/questions/9952815/s3-java-client-fails-a-lot-with-premature-end-of-content-length-delimited-messa
- https://issues.apache.org/jira/browse/FLINK-7589

**Comment by harshavardhana** [comment]
Going to close this as this is not an issue on MinIO - I tested with downloading a 100GiB file and it completes fine even if it reads beyond 15minutes.
