### ISSUE TITLE
Unable to replicate large file (5 gig)

### ISSUE THREAD

**Issue by mostafa8026** [minio/minio#12613]
We have problem with replicating large files (5 gig). It says:

```
API: SYSTEM()
Time: 19:40:01 UTC 07/01/2021
DeploymentID: 11aedd1b-03c9-444b-94d0-e524cde34b54
Error: Unable to replicate for object /S4Q/S4QDV2W/S4QDV2W.zip(4304a1e6-d890-411c-960a-1141327a0ea1): The difference between the request time and the server's time is too large. (*fmt.wrapError)
       2: cmd/bucket-replication.go:710:cmd.replicateObject()
       1: cmd/bucket-replication.go:820:cmd.(*ReplicationPool).AddWorker()
```

## Expected Behavior
Other files are ok and replicated successfully, even a file of 1 gig. but this file is not replicated.

## Possible Solution
I'm using ntp to sync time between servers

## Steps to Reproduce (for bugs)
1. Upload a large file of 5 gig
2. replication is not work

## Context
Docker - Docker version 19.03.8, build afacb8b7f0

## Regression
No

## Your Environment
* Version used (`minio --version`): RELEASE.2021-03-17T02-33-02Z
* Server setup and configuration: ubuntu 20.04
* Operating System and version (`uname -a`): 
```
Linux 39703622670e 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kannappanr** [comment]
@mostafa8026 Current releases use single part for replication. https://github.com/minio/minio/pull/12535
This support will be part of the next release.
Marking this as fixed. Please feel free to reach out to us if you have further questions

**Comment by harshavardhana** [comment]
> 
> ```
> API: SYSTEM()
> Time: 19:40:01 UTC 07/01/2021
> DeploymentID: 11aedd1b-03c9-444b-94d0-e524cde34b54
> Error: Unable to replicate for object /S4Q/S4QDV2W/S4QDV2W.zip(4304a1e6-d890-411c-960a-1141327a0ea1): The difference between the request time and the server's time is too large. (*fmt.wrapError)
>        2: cmd/bucket-replication.go:710:cmd.replicateObject()
>        1: cmd/bucket-replication.go:820:cmd.(*ReplicationPool).AddWorker()
> ```
> 

This issue is your setup problem - fix your NTP settings, there is time difference between clusters and that is not acceptable.

This has nothing to do with replication support for multipart which was a separate feature we added.

**Comment by mostafa8026** [comment]
@harshavardhana 
How can I find that the ntp config is correct. I already install ntp on the main server and in the other server I add this server as ntp server. What else should I have to check?
Also, I run minio on docker.

**Comment by mostafa8026** [comment]
Is there anyway to change globalMaxSkewTime with env vars?
because I think the upload process takes more than 15 minutes.

**Comment by harshavardhana** [comment]
> Is there anyway to change globalMaxSkewTime with env vars?
> because I think the upload process takes more than 15 minutes.

That has nothing to do with this error @mostafa8026 this happens right during signature validation not during upload.
