### ISSUE TITLE
MinIO OpenId does not work after server restart

### ISSUE THREAD

**Issue by Shratha4** [minio/minio#12623]
MinIO OpenId is not present after rebooting the system. After the Environment is restarted it asks for access key and secret key.

Expected Behavior
After restart of the Environment MinIO UI should be like this
![image](https://user-images.githubusercontent.com/86821151/124418927-2ca9b480-dd7a-11eb-8d4b-cbf9dc28f937.png)

Current Behavior
After restart of the Environment MiniIo UI is likethis
![image](https://user-images.githubusercontent.com/86821151/124418940-359a8600-dd7a-11eb-973f-4eb44bede8a0.png)
Login with OpenId is not present.

Possible Solution
If I try to delete the minio pod and then load the page its present but suddenly after restart its not present.

Steps to Reproduce (for bugs)
First I thought it had etcd issue and added etcd to be deployed at init container stage and tried, but its having no effect.

Context
I want login with OpenId to be available because its easy for to login.

Your Environment
minio version RELEASE.2020-11-13T20-10-18Z

**Comment by harshavardhana** [comment]
> minio version RELEASE.2020-11-13T20-10-18Z

Please upgrade to the latest release and let us know - in container environments you need to make sure your containers are persistent. 

Without persistence restarting containers you will lose the data including your OpenID configuration. 

Can you share your entire environment settings?

**Comment by Shratha4** [comment]
We have attached persistent volumes to etcd and MinIO is linked to Azure Gateway(Storage Account).
Do we need to attach a persistent even to MinIO?

**Comment by harshavardhana** [comment]
> We have attached persistent volumes to etcd and MinIO is linked to Azure Gateway(Storage Account).
> Do we need to attach a persistent even to MinIO?

How is OpenID configured? @Shratha4

**Comment by Shratha4** [comment]
We have configured OpenId using keycloak and etcd on MinIO gateway.

**Comment by harshavardhana** [comment]
> We have configured OpenId using keycloak and etcd on MinIO gateway.

How meaning show me the environment variables..

**Comment by Shratha4** [comment]
env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.secretName" . }}
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.secretName" . }}
                  key: secretkey
            {{- if and .Values.gcsgateway.enabled .Values.gcsgateway.gcsKeyJson }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/gcs_key.json"
            {{- end }}
            {{- if .Values.etcd.endpoints }}
            - name: MINIO_ETCD_ENDPOINTS
              value: {{ join "," .Values.etcd.endpoints | quote }}
            {{- if .Values.etcd.clientCert }}
            - name: MINIO_ETCD_CLIENT_CERT
              value: "/etc/credentials/etcd_client_cert.pem"
            {{- end }}
            {{- if .Values.etcd.clientCertKey }}
            - name: MINIO_ETCD_CLIENT_CERT_KEY
              value: "/etc/credentials/etcd_client_cert_key.pem"
            {{- end }}
            {{- if .Values.etcd.pathPrefix }}
            - name: MINIO_ETCD_PATH_PREFIX
              value: {{ .Values.etcd.pathPrefix }}
            {{- end }}
            {{- if .Values.etcd.corednsPathPrefix }}
            - name: MINIO_ETCD_COREDNS_PATH
              value: {{ .Values.etcd.corednsPathPrefix }}
            {{- end }}
            {{- end }}
            {{- if .Values.s3gateway.enabled -}}
            {{- if or .Values.s3gateway.accessKey .Values.existingSecret }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.secretName" . }}
                  key: awsAccessKeyId
            {{- end }}
            {{- if or .Values.s3gateway.secretKey .Values.existingSecret }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "minio.secretName" . }}
                  key: awsSecretAccessKey
            {{- end }}
            {{- end }}
            {{- range $key, $val := .Values.environment }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}

**Comment by klauspost** [comment]
@Shratha4 If you don't want to provide the information there is nothing we can do to help you.

You you require confidentiality look into our [subscription options](https://min.io/pricing).

**Comment by harshavardhana** [comment]
> env:
> - name: MINIO_ACCESS_KEY
> valueFrom:
> secretKeyRef:
> name: {{ template "minio.secretName" . }}
> key: accesskey
> - name: MINIO_SECRET_KEY
> valueFrom:
> secretKeyRef:
> name: {{ template "minio.secretName" . }}
> key: secretkey
> {{- if and .Values.gcsgateway.enabled .Values.gcsgateway.gcsKeyJson }}
> - name: GOOGLE_APPLICATION_CREDENTIALS
> value: "/etc/credentials/gcs_key.json"
> {{- end }}
> {{- if .Values.etcd.endpoints }}
> - name: MINIO_ETCD_ENDPOINTS
> value: {{ join "," .Values.etcd.endpoints | quote }}
> {{- if .Values.etcd.clientCert }}
> - name: MINIO_ETCD_CLIENT_CERT
> value: "/etc/credentials/etcd_client_cert.pem"
> {{- end }}
> {{- if .Values.etcd.clientCertKey }}
> - name: MINIO_ETCD_CLIENT_CERT_KEY
> value: "/etc/credentials/etcd_client_cert_key.pem"
> {{- end }}
> {{- if .Values.etcd.pathPrefix }}
> - name: MINIO_ETCD_PATH_PREFIX
> value: {{ .Values.etcd.pathPrefix }}
> {{- end }}
> {{- if .Values.etcd.corednsPathPrefix }}
> - name: MINIO_ETCD_COREDNS_PATH
> value: {{ .Values.etcd.corednsPathPrefix }}
> {{- end }}
> {{- end }}
> {{- if .Values.s3gateway.enabled -}}
> {{- if or .Values.s3gateway.accessKey .Values.existingSecret }}
> - name: AWS_ACCESS_KEY_ID
> valueFrom:
> secretKeyRef:
> name: {{ template "minio.secretName" . }}
> key: awsAccessKeyId
> {{- end }}
> {{- if or .Values.s3gateway.secretKey .Values.existingSecret }}
> - name: AWS_SECRET_ACCESS_KEY
> valueFrom:
> secretKeyRef:
> name: {{ template "minio.secretName" . }}
> key: awsSecretAccessKey
> {{- end }}
> {{- end }}
> {{- range $key, $val := .Values.environment }}
> - name: {{ $key }}
> value: {{ $val | quote }}
> {{- end}}

There is no IDENTITY related information set here, are you trying to set using `mc admin config` ?

**Comment by Shratha4** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/86821151/124503750-d07b7a80-dde3-11eb-8278-0fd38cc34a85.png)

This is the Environment variables.

**Comment by harshavardhana** [comment]
> This is the Environment variables.

@Shratha4 are you sure that the OPENID reachable after restart?  have you seen the logs on the pods?

**Comment by Shratha4** [comment]
![image](https://user-images.githubusercontent.com/86821151/124556768-50dac380-de56-11eb-8744-855bc352ec97.png)
These are the logs

**Comment by harshavardhana** [comment]
> ![image](https://user-images.githubusercontent.com/86821151/124556768-50dac380-de56-11eb-8744-855bc352ec97.png)
> These are the logs

Without upgrade I don't think we can help further here, can you try latest version?

**Comment by Shratha4** [comment]
I updated it to latest version and checked, even now I am facing same issue
![image](https://user-images.githubusercontent.com/86821151/124723239-746e3e80-df28-11eb-8dcc-9c59c5a1ae4a.png)
 
version- RELEASE.2021-06-17T00-10-46Z

These are the logs
![image](https://user-images.githubusercontent.com/86821151/124723954-29a0f680-df29-11eb-81e2-bf1953c7ac81.png)

**Comment by harshavardhana** [comment]
I tried locally it seems to work fine, not sure what you are doing here @Shratha4
