### ISSUE TITLE
Update dependencies to use gopsutil:v3.21.6 to be able to cross compile openbsd/amd64

### ISSUE THREAD

**Issue by danieljakots** [minio/minio#12620]
Hi,

It would be great to enable cross compile builds on OpenBSD/amd64 to detect failure. The current blocker is old gopsutil. It used to require CGO for OpenBSD. Since v3.21.6 it's not the case anymore.
Once everything switched to v3.21.6, we'll be able to enable cross compiling of openbsd/amd64, see #12417.

What's in the way is: minio/minio pulls gopsutil through:
github.com/minio/mc@v0.0.0-20210626002108-cebf3318546f github.com/shirou/gopsutil/v3@v3.21.4
github.com/minio/madmin-go@v1.0.6 github.com/shirou/gopsutil/v3@v3.21.4
github.com/minio/madmin-go@v1.0.12 github.com/shirou/gopsutil/v3@v3.21.4

The madmin-go@v1.0.6 is because minio/minio pulls github.com/minio/console v0.7.5-0.20210628223511-b51d5505f375
which pulls github.com/minio/operator@v0.0.0-20210616045941-65f31f5f78ae
which pulls github.com/minio/madmin-go@v1.0.6

So as I understand it:
- [ ] minio/mc needs to be updated to use v3.21.6
  - [ ] minio/minio needs to be updated to use this new minio/mc
- [x] minio/madmin-go needs to be updated to use v3.21.6
  - [x] minio/minio needs to be updated to use this new madmin-go
  - [ ] minio/operator needs to be updated to this new madmin-go
    - [ ] minio/console needs to be updated to this new minio/operator
    - [ ] minio/minio needs to be updated to use this new minio/console

Thanks!
Daniel

**Comment by harshavardhana** [comment]
There is no direct requirement for other projects to be upgraded since we do not really have plans to make builds available for other projects under OpenBSD - MinIO compiles fine is enough for us and the commit bb92989 fixes this sufficiently.

**Comment by danieljakots** [comment]
Oh I thought that everything pulling the old gopsutil needed an update.
Thanks!
