### ISSUE TITLE
Backup Error after 3 Weeks

### ISSUE THREAD

**Issue by ahocchb** [minio/minio#12630]
We use Veeam Backup and Recovery in Version 11 for our Infrastructure Backups. We created a Scale-Out Repository and configured our Minio Instance as S3 compatible Target. Everything works fine for the first 3 Weeks. 
After 3 Weeks the first VMs run into the Error Message: 
Processing BackupJob Error: REST API error: 'S3 error: The specified method is not allowed against this resource.
Code: MethodNotAllowed', error code: 405
Other: Key: 'Veeam/Archive/veeam/10b991ba-f5d0-4b2f-a50c-b6dc836edbf6/b2e4256f-8c4f-9893-a381-3ac89584afcb/blocks/4e9e2db7c4fc167a57aff1571b9330c2/33774.7dce2cdc128eb78e9f3e29369f0ab844.00000000000000000000000000000000.blk', BucketName: 'backup', Resource: '/backup/Veeam/Archive/veeam/10b991ba-f5d0-4b2f-a50c-b6dc836edbf6/b2e4256f-8 
Some days later every VM runs into the above Error Message. 
We create a new Bucket with the same configuration as the first one and run the Initial Backup Job over 2 Days. The Backup is running normally again for a time of 3 weeks, then the same Error Message appears again.

## Expected Behavior
The backup should run normally.

## Current Behavior
Backup Job runs into error message and no Virtual Machines are backuped.

## Your Environment

* Version used (`minio --version`): mc version RELEASE.2021-06-08T01-29-37Z
* Server setup and configuration:  MINIO_DATA=/srv/storage/disk{1...4} with 4 RDM-Disk on a TrueNAS over FC
* Operating System and version (`uname -a`): Linux stoves3toenj01 5.3.18-lp152.78-default #1 SMP Tue Jun 1 14:53:21 UTC 2021 (556d823) x86_64 x86_64 x86_64 GNU/Linux

NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by klauspost** [comment]
Most likely it is trying to use `PutObjectRetention` `PutObjectLegalHold` on a deleted object.

Could you do a:

```
mc ls --versions ALIAS/backup/Veeam/Archive/veeam/10b991ba-f5d0-4b2f-a50c-b6dc836edbf6/b2e4256f-8c4f-9893-a381-3ac89584afcb/blocks/4e9e2db7c4fc167a57aff1571b9330c2/33774.7dce2cdc128eb78e9f3e29369f0ab844.00000000000000000000000000000000.blk
```

**Comment by ahocchb** [comment]
@klauspost
`
[2021-06-26 14:44:56 CEST]  20KiB ae4fc2e1-e58d-4196-a429-e5ed9790e2bd v2 PUT 33774.7dce2cdc128eb78e9f3e29369f0ab844.00000000000000000000000000000000.blk
`
`[2021-06-26 12:10:34 CEST]     0B 2df68c64-f15d-4bc4-8bd4-c8bdb87b1194 v1 DEL 33774.7dce2cdc128eb78e9f3e29369f0ab844.00000000000000000000000000000000.blk`

**Comment by klauspost** [comment]
Rather strange that `v1` is a delete marker, but maybe they explicitly deleted previous versions.

Harsha, just a wild guess, but maybe S3 removes delete markers if it is the the first version?

@ahocchb Is the error before or after `v2` was uploaded?

**Comment by ahocchb** [comment]
@klauspost @harshavardhana the error is from yesterday evening.

**Comment by klauspost** [comment]
ok, so after v2 was uploaded. It doesn't say which version it tried to modify, but it most likely tried to do it on `v1` considering the error.

**Comment by ahocchb** [comment]
@klauspost So you mean veeam should delete V2, but tries to delete V1?

**Comment by harshavardhana** [comment]
> @klauspost So you mean veeam should delete V2, but tries to delete V1?

Please provide the output for `mc stat --versions` on the object and let's see the metadata on it.

**Comment by klauspost** [comment]
@harshavardhana Either that, or (more likely) it attempts to set retention policy on the delete marker.

**Comment by harshavardhana** [comment]
> @harshavardhana Either that, or (more likely) it attempts to set retention policy on the delete marker.

Yeah perhaps `mc admin trace -v` output is needed here for the backup run and we can see which version of the object it tries to update.

**Comment by harshavardhana** [comment]
> Harsha, just a wild guess, but maybe S3 removes delete markers if it is the the first version?

@klauspost no - delete markers are set even if the object doesn't exist and `DeleteObject` was called on a non-existent object. 

```
AWS_PROFILE=s3 aws s3api delete-object --bucket harshavardh
ana --key i/do/not/exist 
{
    "DeleteMarker": true,
    "VersionId": "HheLCWTiqoSJwpKRcVoKomdr7AZJCEh1"
}
```

```
~ mc ls -r --versions s3/harshavardhana/i/
[2021-07-07 17:11:58 PDT]     0B HheLCWTiqoSJwpKRcVoKomdr7AZJCEh1 v1 DEL do/not/exist
```

All the more confusing implementations from AWS S3 :-)

**Comment by harshavardhana** [comment]
Although we do not follow this and we do not create a delete marker on a non-existent object just because it's not necessary and it's frivolous.

**Comment by ahocchb** [comment]
@harshavardhana: Metadata for the Object:
mc stat --versions local/backup/Veeam/Archive/veeam/10b991ba-f5d0-4b2f-a50c-b6dc836edbf6/b2e4256f-8c4f-9893-a381-3ac89584afcb/blocks/4e9e2db7c4fc167a57aff1571b9330c2/33774.7dce2cdc128eb78e9f3e29369f0ab844.00000000000000000000000000000000.blk
Name      : 33774.7dce2cdc128eb78e9f3e29369f0ab844.00000000000000000000000000000000.blk
Date      : 2021-06-26 14:44:56 CEST
Size      : 20 KiB
ETag      : cfcc05a1e6b577b99b82a7c0b21e4d77
VersionID : ae4fc2e1-e58d-4196-a429-e5ed9790e2bd
Type      : file
Metadata  :
  X-Amz-Object-Lock-Mode             : COMPLIANCE
  X-Amz-Meta-Arch-Block-Size         : 20336
  X-Amz-Object-Lock-Retain-Until-Date: 2021-07-15T09:22:34.000Z
  Content-Type                       : application/octet-stream
  X-Amz-Object-Lock-Legal-Hold       : OFF

**Comment by harshavardhana** [comment]
> X-Amz-Object-Lock-Retain-Until-Date: 2021-07-15T09:22:34.000Z

Your object has retain until date this is why it is not allowed to be deleted @ahocchb - not sure why Veeam would try to delete this object. 

Also, make sure that you have NTP configured correctly and the timing is the same on all the nodes.

**Comment by harshavardhana** [comment]
Closing this as we don't see anything wrong here on our end.
