### ISSUE TITLE
s3 gateway for minio instance does not allow public access

### ISSUE THREAD

**Issue by cweiske** [minio/minio#12638]
When running a minio gateway for a minio server, publicly accessible files give a "403 Forbidden". The gateway log says "Prefix access is denied".

The main minio server has "download" policy for anonymous users, set with `mc policy set download test-minio-main/mybucket/`.

## Expected Behavior
Fetching files anonymously via curl should work, both on the minio server and the minio gateway:
```
$ curl localhost:9001/mybucket/hello.txt
hello
```

## Current Behavior
Fetching file data anonymously only works on the main minio server, but not on the minio gateway:
```
#main minio server
$ curl localhost:9001/mybucket/hello.txt
hello

#minio gateway 
$ curl -i localhost:9002/mybucket/hello.txt
HTTP/1.1 403 Forbidden
...
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message>...
```

The gateway logs say:
```
API: SYSTEM()
Time: 06:50:33 UTC 07/08/2021
DeploymentID: 511d2a6f-09c2-4a46-abe0-4d4ff793c687
Error: Prefix access is denied: mybucket/ (cmd.PrefixAccessDenied)
       4: cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
       3: cmd/object-handlers.go:347:cmd.objectAPIHandlers.getObjectHandler()
       2: cmd/object-handlers.go:565:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)
1. Setup main minio server
```
docker run --rm --detach --name test-minio-main -p 9001:9000 minio/minio server data/
mc alias set test-minio-main http://localhost:9001 minioadmin minioadmin
mc mb test-minio-main/mybucket
mc policy set download test-minio-main/mybucket/

echo hello > hello.txt
mc cp hello.txt test-minio-main/mybucket/

cat <<EOT > s3-myreadonly-policy-v4.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "readonly",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        },
        {
            "Sid": "readonly",
            "Effect": "Allow",
            "Action": [
                "s3:HeadBucket",
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::mybucket"
        }
    ]
}
EOT

mc admin user add test-minio-main readuser readpass
mc admin policy add test-minio-main myreadonly s3-myreadonly-policy-v4.json
mc admin policy set test-minio-main myreadonly user=readuser
```
2. Test anonymous access on main minio server:
```
$ curl localhost:9001/mybucket/hello.txt
hello
```
3. Setup gateway
```
docker run --rm --detach --name test-minio-gateway -p9002:9000 --link test-minio-main --env MINIO_ROOT_USER=readuser --env MINIO_ROOT_PASSWORD=readpass minio/minio gateway s3 http://test-minio-main:9000

mc alias set test-minio-gateway-readonly http://localhost:9002 readuser readpass
```
4. Test accessing the file on the gateway with authentication:
```
$ mc cat test-minio-gateway-readonly/mybucket/hello.txt
hello
```
5. Test anonymous access on the s3 gateway:
```
$ curl -i localhost:9002/mybucket/hello.txt
HTTP/1.1 403 Forbidden
```

## Context
I want to have a local development mirror of a remote minio instance for speed reasons. I can't sync all the data from remote because it would require too much disk space.

## Regression
No.

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2021-06-17T00-10-46Z`
* Server setup and configuration: `Docker version 20.10.7, build f0df350`
* Operating System and version (`uname -a`): `Linux sybo 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@cweiske we do not allow this on purpose you need to set policies through MinIO for this to work. You can't expect us to send the results to the backend directly. 

We are not just a proxy like nginx - we are S3 API terminator as well so the public policies need to be applied at the MinIO layer as well. 


```
~ AWS_PROFILE=s3 minio gateway s3
~ mc policy set myminio/sjm-airlines-1/
~  curl --head http://localhost:9000/sjm-airlines-1/hosts999
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 461
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
ETag: "da7bd5000c85fbccd2093554205a637d"
Last-Modified: Sat, 22 Aug 2020 05:56:43 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 168FC039A71DF2EB
X-Xss-Protection: 1; mode=block
Date: Thu, 08 Jul 2021 07:29:05 GMT
```

Now restart the gateway and still works fine.

```
~ curl --head http://localhost:9000/sjm-airlines-1/hosts999
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 461
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
ETag: "da7bd5000c85fbccd2093554205a637d"
Last-Modified: Sat, 22 Aug 2020 05:56:43 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 168FC03DD474A799
X-Xss-Protection: 1; mode=block
Date: Thu, 08 Jul 2021 07:29:23 GMT
```

**Comment by cweiske** [comment]
@harshavardhana I cannot set the policy on the gateway, because I get an "access denied" for it:

```
$ mc policy set download test-minio-gateway-readonly/mybucket
mc: <ERROR> Unable to set policy `download` for `test-minio-gateway-readonly/mybucket`. Access Denied.
```

I had to set the root user+password to be the readonly user of the main minio server. There is no other user on the gateway that would allow setting the policy IMO.

----

Also, the process described in the bug description works without problems with Amazon's S3 as main server for the gateway. I don't have to set the policy on the gateway in that case.

**Comment by cweiske** [comment]
It turns out that the policy misses an action: `s3:GetBucketPolicy`. When this is added, public access to files on the gateway works fine.

Full "myreadonly" policy for the main minio server:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "readonly",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        },
        {
            "Sid": "readonly",
            "Effect": "Allow",
            "Action": [
                "s3:HeadBucket",
                "s3:ListBucket",
                "s3:GetBucketPolicy"
            ],
            "Resource": "arn:aws:s3:::mybucket"
        }
    ]
}
```
