### ISSUE TITLE
在windows中 go build 完成后 登录就报 Invalid UI version in the JSON-RPC response

### ISSUE THREAD

**Issue by simanlx** [minio/minio#12636]
在windows环境下 go build 编译后 运行 登录就报 Invalid UI version in the JSON-RPC response

看了一片文章说需要  build 参数放在 go build 之后去执行

具体需要什么参数，如何操作。

有没有相关的说明，找了好久也没有相关资料！

**Comment by harshavardhana** [comment]
You can't use `go build` with UI - you should do `make install` @simanlx

**Comment by simanlx** [comment]
在windows系统中

**Comment by klauspost** [comment]
@simanlx Use WSL/WSL2
