### ISSUE TITLE
Unable to get mcConfigDir.

### ISSUE THREAD

**Issue by fhemberger** [minio/minio#12641]
Using `RELEASE.2021-07-08T01-15-01Z` (linux-arm), I get the following startup error:

```
minio: <ERROR> Unable to get mcConfigDir. exec: "getent": executable file not found in $PATH.
```

So far I was only running `minio` on the host, but this message [comes from the `mc` client](https://github.com/minio/mc/blob/RELEASE.2021-06-13T17-48-22Z/cmd/config.go#L72), so I tried installing it as well (without any effect). But I'm not sure why the server component would pull that in at all.

`RELEASE.2021-06-17T00-10-46Z` works for me.

## minio Version
RELEASE.2021-07-08T01-15-01Z

## Host
Synology Diskstation 414 (NAS)

```
Linux DiskStation 3.2.40 #25556 SMP Thu Mar 4 17:57:56 CST 2021 armv7l GNU/Linux synology_armadaxp_ds414
````

## Upstart Config
```
env PATH=/usr/local/bin:$PATH
env MINIO_ROOT_USER="********"
env MINIO_ROOT_PASSWORD="********"
env MINIO_PROMETHEUS_AUTH_TYPE="public"

exec /usr/local/bin/minio \
  --console-address ":9000" \
  --config-dir /minio/.minio \
  --certs-dir /minio/.minio/certs \
  server \
  /volume1/minio
```

**Comment by harshavardhana** [comment]
> ```
  > minio: <ERROR> Unable to get mcConfigDir. exec: "getent": executable file not found in $PATH.
> ```

as you can see clearly `getent` is missing from your PATH looks like a system with standard tools removed. 

This is being called because you have `$HOME` missing in your environment variable, it is failing with `mcConfigDir` error because `minio/console` package uses `minio/mc` as library for few things. 

Just set HOME and this error shall go away.

```
env HOME=/minio
env PATH=/usr/local/bin:$PATH
env MINIO_ROOT_USER="********"
env MINIO_ROOT_PASSWORD="********"
env MINIO_PROMETHEUS_AUTH_TYPE="public"

exec /usr/local/bin/minio \
  --console-address ":9000" \
  --config-dir /minio/.minio \
  --certs-dir /minio/.minio/certs \
  server \
  /volume1/minio
```

**Comment by fhemberger** [comment]
@harshavardhana Thanks for the help!
