### ISSUE TITLE
[not our bug] Minio hangs on http request metrics or info when backend in GlusterFS

### ISSUE THREAD

**Issue by chris93111** [minio/minio#12645]
Hello 
When i try to recover info with mc admin --json info, they are no response of minio, the request stuck
it's same with prometheus/metrics api
the S3 is ok , i can liste user or policy and also /minio/health/live work ...

first i have found this error for metrics api:
 API: SYSTEM()
 Time: 11:25:24 UTC 07/08/2021
 DeploymentID: 516e7520-b2f5-432f-9d6f-c03dff05a671
 Error: file already locked (*errors.errorString)
        6: cmd/fs-v1.go:968:cmd.(*FSObjects).getObjectInfo()
        5: cmd/fs-v1.go:722:cmd.(*FSObjects).GetObjectNInfo()
        4: cmd/data-usage.go:63:cmd.loadDataUsageFromBackend()
        3: cmd/metrics.go:434:cmd.bucketUsageMetricsPrometheus()
        2: cmd/metrics.go:99:cmd.(*minioCollector).Collect()
        1: github.com/prometheus/client_golang@v1.8.0/prometheus/registry.go:444:prometheus.(*Registry).Gather.func1()

but i see nothing new in trace or console logs with debug

## Steps to Reproduce (for bugs)
mc admin --json info 
## Your Environment
minio/minio:RELEASE.2021-03-17T02-33-02Z , with filesystem mount
docker in redhat 3.10.0-1062.1.2.el7.x86_64

**Comment by harshavardhana** [comment]
@chris93111 just restart the server and this will go away - it looks like there is a previous lock on the `fcntl` that is not cleared. 

are you using NFSv3 by any chance here?

**Comment by chris93111** [comment]
Hi @harshavardhana yes i use glusterfs it's shared fs

**Comment by harshavardhana** [comment]
> Hi @harshavardhana yes i use glusterfs it's shared fs

Ah GlusterFS @chris93111 this looks like you haven't enabled POSIX locking on it? you need to make sure to enable POSIX locking otherwise it won't work.

**Comment by chris93111** [comment]
yes the restart don't resolve the problem

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/issues/5467#issuecomment-368581860 read this historic issue on what values to set for GlusterFS to honor fcntl locks.

Closing this issue as this is beyond MinIO's scope now.

**Comment by chris93111** [comment]
thanks clear locked file resolve the problem
