### ISSUE TITLE
Auto-healing doesn't work after some time or manual heal

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [minio/minio#12644]
I have minio cluster which consist of 2 pools with 4 servers on each. 
``` server http://minio{1...4}/data http://minio{5...8}/data ```
I run servers with docker-compose and using ``` minio/minio:RELEASE.2021-06-17T00-10-46Z ```  image  
Each minio server/container /data dir attached to host as volume for persistent storage
```  - ./data/data6:/data ```
I am testing minio for durability and  resilience  cause I need it for petabyte scale highly available, durable and resilient workload.
Now for test purposes I was deleting   some folder/bucket in data6 directory to mimic data lose or so.

## Expected Behavior

I expect that minio will automatically heal/restore data.
## Current Behavior

It does nothing. It auto-healed several times in past but now minio did nothing , I tried to upload and download data to put some activity to trigger auto-heal but no result.  I tried ``` mc admin info ``` and it shows that everything is ok. Prometheus metrics also doesn't said anything. Even restart of container doesn't help. I just been able to recover data manually running ``` mc admin heal ``` .

## Possible Solution

The reason that I can recall for now  is that manual heal somehow turns off auto-healing, because it works before I tried manual heal very first time. I tried to find some documentation about healing of minio but it is  not enough info. When minio does/triggers auto-healing ? how/when it is checking data existence? How I can be sure the if mc admin info shows OK it is really OK ?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> Now for test purposes I was deleting some folder/bucket in data6 directory to mimic data lose or so.

Auto healing runs but it is run as per the scanner schedule you need to wait for it to figure out this information and it is not instantaneous - if you want faster scanner times look at how you reduce the scanner intervals 

```
 mc admin config set play/ scanner --env
KEY:
scanner  manage namespace scanning for usage calculation, lifecycle, healing and more

ARGS:
MINIO_SCANNER_DELAY     (float)     scanner delay multiplier, defaults to '10.0'
MINIO_SCANNER_MAX_WAIT  (duration)  maximum wait time between operations, defaults to '15s'
MINIO_SCANNER_CYCLE     (duration)  time duration between scanner cycles, defaults to '1m'
```

**Comment by klauspost** [comment]
@HaykManukyanAvetiky If you want to test a realistic scenario, replace an entire drive. Random files is very unlikely to go missing on disks, but full disk failure are common.

When the scanner run a cycle on the disk where you deleted the files it will notice the missing folders. However under normal circumstances there can be weeks or months between a bucket being visited on a specific disk. You can tune that, mostly with the scanner delay, but it will be more disruptive to your other operation.

**Comment by HaykManukyanAvetiky** [comment]
The problem is not only healing , there is no alert or indication that something happened. Also I wait more than 30m,  even after restart it is still not there, it is wired guys 

> > Now for test purposes I was deleting some folder/bucket in data6 directory to mimic data lose or so.
> 
> Auto healing runs but it is run as per the scanner schedule you need to wait for it to figure out this information and it is not instantaneous - if you want faster scanner times look at how you reduce the scanner intervals
> 
> ```
>  mc admin config set play/ scanner --env
> KEY:
> scanner  manage namespace scanning for usage calculation, lifecycle, healing and more
> 
> ARGS:
> MINIO_SCANNER_DELAY     (float)     scanner delay multiplier, defaults to '10.0'
> MINIO_SCANNER_MAX_WAIT  (duration)  maximum wait time between operations, defaults to '15s'
> MINIO_SCANNER_CYCLE     (duration)  time duration between scanner cycles, defaults to '1m'
> ```

**Comment by HaykManukyanAvetiky** [comment]
My concern is that at least i should have some indication that I have data lose , in order to run heal manually

**Comment by HaykManukyanAvetiky** [comment]
The problem with that is , when you have data lose like I said, it need to be recovered immediately otherwise some of you servers can go offline during that time and you will be unable to get object. I just thinking to manually run heal every day or so , via cron for example to ensure that, but it is not elegant solution     

> @HaykManukyanAvetiky If you want to test a realistic scenario, replace an entire drive. Random files is very unlikely to go missing on disks, but full disk failure are common.
> 
> When the scanner run a cycle on the disk where you deleted the files it will notice the missing folders. However under normal circumstances there can be weeks or months between a bucket being visited on a specific disk. You can tune that, mostly with the scanner delay, but it will be more disruptive to your other operation.

**Comment by klauspost** [comment]
@HaykManukyanAvetiky When a full disk is lost it will start recovery at once and run through all your files. Deleting some random files/folders does not trigger that.

If a disk is offline when data is being written it is written with additional erasure shards to compensate for the missing disk. So if you have `EC:4` and a disk is offline, the data will be written with `EC:5` effectively. If a file is read and it is found to have missing data it is queued for immediate healing. 

If the scanner observes a missing folder it will similarly check if it was deleted or needs to be restored.

Full data scans are expensive and can be disruptive to the performance of your cluster which is why "drive-by-healing" is only performed very slowly.
