### ISSUE TITLE
Dynamic policy variables do not work properly with embedded console

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#12651]
> There is no way to do that anymore @flixr we have moved on from that.

Hm... thats a bummer... wondering how I can now give access to the console for our "outside" users...
This should have been clearly stated in the release notes, would be great if you can update them so others don't update pre-maturely and run into the same problem...
No, just a policy assigned to a group allowing access to a bucket with the same name as the user, and the users added to that group:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}/*"
            ]
        }
    ]
}
```

_Originally posted by @flixr in https://github.com/minio/minio/issues/12646#issuecomment-876610382_

**Comment by flixr** [comment]
Thanks for the quick update on this.

While with 2021-07-08T19-43-25Z now the bucket is shown for users with this policy, I cannot list it's contents. I just get `There are no Rewind Objects yet.`

In the minio log:
```
Jul 09 07:59:07 rc-minio01 minio[426634]: original error -> (user_objects.go:51: Access Denied.)
Jul 09 07:59:07 rc-minio01 minio[426634]: error versioning bucket: Access Denied.
```

But the bucket does not have versioning enabled...

Also now with the root credentials, the bucket list is completely empty!
With a user with readwrite on all buckets, I can see them though...

**Comment by Enrico204** [comment]
@flixr FYI you're not the only one with this issue: https://github.com/minio/minio/issues/12676#issuecomment-877803790
