### ISSUE TITLE
The default accessKey and secretKey counter with "unauthorized" error

### ISSUE THREAD

**Issue by sunsdy2018** [minio/minio#12656]
My OS is Windows 10.

The version of minio.exe is：
![image](https://user-images.githubusercontent.com/38706610/125055722-184b1c00-e0da-11eb-920e-4368dc1dc3bc.png)

Use the following command to start minio.exe:
![image](https://user-images.githubusercontent.com/38706610/125055829-331d9080-e0da-11eb-9347-1955c9b5344c.png)

Open the browser and access the url using the default accessKey and secretKey as follows:
![image](https://user-images.githubusercontent.com/38706610/125056015-66601f80-e0da-11eb-9a4b-8b1c7aabce9d.png)

**Comment by klauspost** [comment]
I cannot reproduce on Win 10 + minio version `RELEASE.2021-07-08T19-43-25Z`:

![image](https://user-images.githubusercontent.com/5663952/125060339-8f69bb80-e0ac-11eb-9753-d94833ce7e20.png)

![image](https://user-images.githubusercontent.com/5663952/125060647-de175580-e0ac-11eb-9d59-6e1ef024c41e.png)

**Comment by harshavardhana** [comment]
Seems to be working as intended as well across platforms @sunsdy2018 - would be able to provide more information?
