### ISSUE TITLE
Console does not list nor allow to add buckets by regular users

### ISSUE THREAD

**Issue by markovendelin** [minio/minio#12650]
With the replacement of WEB interface shown to the users with console, regular (non-admin) users cannot

- list their buckets
- create new buckets even if permissions are available

Users policy:

```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}-*"
            ]
        }
    ]
}
```

Version:
RELEASE.2021-07-08T01-15-01Z

**Comment by harshavardhana** [comment]
Duplicate of #12646

**Comment by harshavardhana** [comment]
Refer to #12651 why it doesn't work
