### ISSUE TITLE
Allow non-admin users to create new buckets

### ISSUE THREAD

**Issue by markovendelin** [minio/minio#12664]
Continuation of #12651

With the non-admin user account, Console does not allow to create new buckets while user does have permission to do so. Filing as a bug since earlier WebUI allowed to do so.

User permissions:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}-*"
            ]
        }
    ]
}
```

Note that the permissions allow to create buckets with some specific names. I wonder whether it would make sense to show GUI buttons allowing to create buckets in "Object browser" and under "Buckets" without checking policies regarding it. If it is not allowed, API would report it and then just showing the error message would be sufficient.

**Comment by harshavardhana** [comment]
@markovendelin what is the error that you see can you share some screenshots? and what specific buckets does user create here that fails?

**Comment by markovendelin** [comment]
Sorry, should have added the screenshot. 

I don't see "Create bucket" button, as shown in the screenshot below (screenshot has bucket names and sizes removed, otherwise they are shown).

No error in Console UI, can't tell much about minio logs right now. Please let me know if you want me to dig them up.

![no_bucket_create](https://user-images.githubusercontent.com/3975391/125125324-15fcb800-e102-11eb-8b33-7d7f307042a3.png)

**Comment by harshavardhana** [comment]
> I don't see "Create bucket" button, as shown in the screenshot below (screenshot has bucket names and sizes removed, otherwise they are shown).

If you don't have this option then again its a console UI issue just like Change Password.

**Comment by harshavardhana** [comment]
Oh wait you can create the buckets in the `Buckets` section @markovendelin can you check?

**Comment by markovendelin** [comment]
No, I cannot - same as in Object browser. So, I guess it is GUI issue indeed and I should open it in Console repo. Will close as soon as will get the conformation from you.

**Comment by harshavardhana** [comment]
> No, I cannot - same as in Object browser. So, I guess it is GUI issue indeed and I should open it in Console repo. Will close as soon as will get the conformation from you.

Yes it is console UI issue, policy is not validated correctly.

**Comment by markovendelin** [comment]
@harshavardhana : thank you very much for the fast response! Issue moved to Console.
