### ISSUE TITLE
Created service account didn't inherit permissions from parent

### ISSUE THREAD

**Issue by ghost** [minio/minio#12662]
After creating a service account with an existing user that have permissions to login into the console and see several buckets 
![image](https://user-images.githubusercontent.com/38687952/125099702-96a6be80-e0d8-11eb-9f8a-336a6f853440.png)

the mentioned service account can't login into the console and also see no buckets when trying to access with an s3 client
![image](https://user-images.githubusercontent.com/38687952/125100053-f7ce9200-e0d8-11eb-98f2-384a33340387.png)

Shouldn't the created service account have the same permissions?

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-07-08T19-43-25Z
* Server setup and configuration: distributed cluster
* Operating System and version (`uname -a`): ubuntu server 20.04

**Comment by vadmeste** [comment]
> Shouldn't the created service account have the same permissions?

It depends on how you created the service account, could you show what you did to create the service account ?

**Comment by harshavardhana** [comment]
You can't login using service accounts again through console, console is meant for user logins only once service accounts are created use them with your application.

**Comment by ravindk89** [comment]
https://docs.min.io/minio/baremetal/security/minio-identity-management/user-management.html#service-accounts now explicitly mentions that Service Accounts are intended for programmatic use.

**Comment by dmaggo** [comment]
Just to clarify, the newest release https://github.com/minio/minio/releases/tag/RELEASE.2021-07-12T02-44-53Z fixed my problem that the newly created service account also didn't work with applications like an s3-browser. 
I think this point here was the problem that you guys fixed: "Dynamic policies for users in various configurations"

Thanks.
