### ISSUE TITLE
Documentation: Update MinIO Docker Quickstart Guide Documentation to Mention Minio Console

### ISSUE THREAD

**Issue by wcedmisten** [minio/minio#12660]
**Is your feature request related to a problem? Please describe.**
When following the [MinIO Docker Quickstart Guide](https://docs.min.io/docs/minio-docker-quickstart-guide.html), no mention is made of the Minio Console which is included in the image. When following the first docker command in the guide:

```
$ docker run -p 9000:9000 \
>   -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
>   -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
>   minio/minio server /data
```

The following output is shown:
```
API: http://<my IP>:9000  http://127.0.0.1:9000 

Console: http://<my IP>:40843 http://127.0.0.1:40843 

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (40843), please use --console-address ":PORT" to choose a static port.
```

**Describe the solution you'd like**
Modify the quickstart commands to specify a fixed port for the console to be hosted on, and expose the port in the docker command. E.g.:

```
$ docker run -p 9000:9000 -p 9001:9001 \
>   -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
>   -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
>   minio/minio server --console-address :9001 /data
```

This would allow the console to be visited from localhost:9001. Currently, the console can only be accessed from `http://<my IP>:40843`, but visiting `http://127.0.0.1:40843` does not work, because the port is not exposed from the container.

**Describe alternatives you've considered**
* Creating a separate section in the quickstart guide that mentions the Minio console and how to expose the port, but does not modify the original docker command.
* Not modifying the quickstart docs because it's a Minio Console issue

**Additional context**
Motivation for this change comes from this stackoverflow post which I believe points to a minor insufficiency with the quickstart docs: https://stackoverflow.com/questions/68317358/minio-local-dashboard-is-not-opening/68318238#68318238

**Comment by xoxys** [comment]
Minio should think about adding a breaking change section in the change log. On every release an admin has to read every single line in the changelog very carefully to avoid an outage and even if it was done its freaking had to find out what all those changelog items really mean and how they interfere to running instances.

**Comment by harshavardhana** [comment]
> Minio should think about adding a breaking change section in the change log. On every release an admin has to read every single line in the changelog very carefully to avoid an outage and even if it was done its freaking had to find out what all those changelog items really mean and how they interfere to running instances.

@xoxys We will add the "Breaking Change:" section or at least things to look out for section. 

But NOTE: if you have a production setup you are always advised to test it locally in a separate instance.  Willy nilly upgrading instances in production is *naive* way to do devops and administration. 

If you have questions about the release you can definitely ask at https://slack.min.io - if you want more SLA-based responses you are also advised to get a subscription with MinIO.

**Comment by ravindk89** [comment]
@harshavardhana given we are moving towards podman, should we just remove this tutorial entirely? I'm planning on doing that for the nextgen [docs](https://docs.min.io/minio/baremetal/tutorials/minio-installation.html#docker-installation) as well and replacing them with the podman-focused guide. Alternatively I can just do the fix above as it's relatively minor, and then come back around for a more complete re-write.

@wcedmisten if you hit the `127.0.0.1:9000` port in your browser, does it auto-redirect? This should be the expected behavior, but with docker networking I'm less sure of what will happen.

**Comment by wcedmisten** [comment]
It does redirect, but then can't it connect to the redirected address `http://127.0.0.1:<dynamic port>`, presumably because that port isn't exposed from the docker container. The redirect *does* work when running the command with `--console-address :9001` and `-p 9001:9001`.

**Comment by ravindk89** [comment]
OK, good to know - thanks for checking that.

**Comment by chayder** [comment]
Hello, Excuse me, thanks for thread and information.

I have this same issue but from a .yml file for deploy a compose or stack group of services.

I haven't idea of how use this "--console-address :9001" flag in this scope. this is possible or exists any alternative? or i need to have deploy minio service how standalone service with a run command?

Excuse me if this aren't place for this question, but is same issue and i also need help. Very thanks.

Pd.: I also will grateful a documentation update with this news root environments vars and --console-address flag, for standalone container and compose (or stack) deploys as well. Thanks

**Comment by Stellagosa** [comment]
> Hello, Excuse me, thanks for thread and information.
> 
> I have this same issue but from a .yml file for deploy a compose or stack group of services.
> 
> I haven't idea of how use this "--console-address :9001" flag in this scope. this is possible or exists any alternative? or i need to have deploy minio service how standalone service with a run command?
> 
> Excuse me if this aren't place for this question, but is same issue and i also need help. Very thanks.
> 
> Pd.: I also will grateful a documentation update with this news root environments vars and --console-address flag, for standalone container and compose (or stack) deploys as well. Thanks

```
version: '3'
services:
  minio-demo:
    image: minio/minio:latest
    container_name: minio-demo
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address :9001 /data
```

**Comment by wadakatu** [comment]
> > Hello, Excuse me, thanks for thread and information.
> > I have this same issue but from a .yml file for deploy a compose or stack group of services.
> > I haven't idea of how use this "--console-address :9001" flag in this scope. this is possible or exists any alternative? or i need to have deploy minio service how standalone service with a run command?
> > Excuse me if this aren't place for this question, but is same issue and i also need help. Very thanks.
> > Pd.: I also will grateful a documentation update with this news root environments vars and --console-address flag, for standalone container and compose (or stack) deploys as well. Thanks
> 
> ```
> version: '3'
> services:
>   minio-demo:
>     image: minio/minio:latest
>     container_name: minio-demo
>     volumes:
>       - ./minio/data/:/data
>       - ./minio/conf/:/root/.minio
>     ports:
>       - 9000:9000
>       - 9001:9001
>     environment:
>       MINIO_ROOT_USER: minio
>       MINIO_ROOT_PASSWORD: minio123
>     command: server --console-address :9001 /data
> ```

If I use the command `server --console-address :9001 /data`, I get the error like `ERROR Unable to start the server: --console-address cannot be same as --address` in the log.

Is there anyone who faced same problem? 

Moreover, what is the difference between --address and --console-address?

**Comment by ardinusawan** [comment]
Hei I have similar problem but with docker compose. The file is from [official docs](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml)

```version: '3.7'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio:RELEASE.2021-07-08T19-43-25Z
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2021-07-08T19-43-25Z
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2021-07-08T19-43-25Z
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2021-07-08T19-43-25Z
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

Need help 🙏

**Comment by harshavardhana** [comment]
> > > Hello, Excuse me, thanks for thread and information.
> > > I have this same issue but from a .yml file for deploy a compose or stack group of services.
> > > I haven't idea of how use this "--console-address :9001" flag in this scope. this is possible or exists any alternative? or i need to have deploy minio service how standalone service with a run command?
> > > Excuse me if this aren't place for this question, but is same issue and i also need help. Very thanks.
> > > Pd.: I also will grateful a documentation update with this news root environments vars and --console-address flag, for standalone container and compose (or stack) deploys as well. Thanks
> > 
> > 
> > ```
> > version: '3'
> > services:
> >   minio-demo:
> >     image: minio/minio:latest
> >     container_name: minio-demo
> >     volumes:
> >       - ./minio/data/:/data
> >       - ./minio/conf/:/root/.minio
> >     ports:
> >       - 9000:9000
> >       - 9001:9001
> >     environment:
> >       MINIO_ROOT_USER: minio
> >       MINIO_ROOT_PASSWORD: minio123
> >     command: server --console-address :9001 /data
> > ```
> 
> If I use the command `server --console-address :9001 /data`, I get the error like `ERROR Unable to start the server: --console-address cannot be same as --address` in the log.
> 
> Is there anyone who faced same problem?
> 
> Moreover, what is the difference between --address and --console-address?

I have no idea how you can get that error

```
docker-compose -f test.yaml up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting minio-demo ... done
Attaching to minio-demo
minio-demo    | API: http://172.23.0.2:9000  http://127.0.0.1:9000 
minio-demo    | 
minio-demo    | Console: http://172.23.0.2:9001 http://127.0.0.1:9001 
minio-demo    | 
minio-demo    | Documentation: https://docs.min.io
```

and my `test.yaml`

```yaml
version: '3'
services:
  minio-demo:
    image: minio/minio:latest
    container_name: minio-demo
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address :9001 /data
```

**Comment by harshavardhana** [comment]
> Hei I have similar problem but with docker compose. The file is from [official docs](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml)
> 
> ```
> 
> # starts 4 docker containers running minio server instances.
> # using nginx reverse proxy, load balancing, you can access
> # it through port 9000.
> services:
>   minio1:
>     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
>     hostname: minio1
>     volumes:
>       - data1-1:/data1
>       - data1-2:/data2
>     expose:
>       - "9000"
>     environment:
>       MINIO_ROOT_USER: minio
>       MINIO_ROOT_PASSWORD: minio123
>     command: server http://minio{1...4}/data{1...2}
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
> 
>   minio2:
>     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
>     hostname: minio2
>     volumes:
>       - data2-1:/data1
>       - data2-2:/data2
>     expose:
>       - "9000"
>     environment:
>       MINIO_ROOT_USER: minio
>       MINIO_ROOT_PASSWORD: minio123
>     command: server http://minio{1...4}/data{1...2}
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
> 
>   minio3:
>     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
>     hostname: minio3
>     volumes:
>       - data3-1:/data1
>       - data3-2:/data2
>     expose:
>       - "9000"
>     environment:
>       MINIO_ROOT_USER: minio
>       MINIO_ROOT_PASSWORD: minio123
>     command: server http://minio{1...4}/data{1...2}
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
> 
>   minio4:
>     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
>     hostname: minio4
>     volumes:
>       - data4-1:/data1
>       - data4-2:/data2
>     expose:
>       - "9000"
>     environment:
>       MINIO_ROOT_USER: minio
>       MINIO_ROOT_PASSWORD: minio123
>     command: server http://minio{1...4}/data{1...2}
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
> 
>   nginx:
>     image: nginx:1.19.2-alpine
>     hostname: nginx
>     volumes:
>       - ./nginx.conf:/etc/nginx/nginx.conf:ro
>     ports:
>       - "9000:9000"
>     depends_on:
>       - minio1
>       - minio2
>       - minio3
>       - minio4
> 
> ## By default this config uses default local driver,
> ## For custom volumes replace with volume driver configuration.
> volumes:
>   data1-1:
>   data1-2:
>   data2-1:
>   data2-2:
>   data3-1:
>   data3-2:
>   data4-1:
>   data4-2:
> ```
> 
> Need help

@ardinusawan what is the problem? - I don't see any problem bringing up MinIO

**Comment by wadakatu** [comment]
> I have no idea how you can get that error
> 
> ```
> docker-compose -f test.yaml up
> WARNING: The Docker Engine you're using is running in swarm mode.
> 
> Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.
> 
> To deploy your application across the swarm, use `docker stack deploy`.
> 
> Starting minio-demo ... done
> Attaching to minio-demo
> minio-demo    | API: http://172.23.0.2:9000  http://127.0.0.1:9000 
> minio-demo    | 
> minio-demo    | Console: http://172.23.0.2:9001 http://127.0.0.1:9001 
> minio-demo    | 
> minio-demo    | Documentation: https://docs.min.io
> ```
> 
> and my `test.yaml`
> 
> ```yaml
> version: '3'
> services:
>   minio-demo:
>     image: minio/minio:latest
>     container_name: minio-demo
>     volumes:
>       - ./minio/data/:/data
>       - ./minio/conf/:/root/.minio
>     ports:
>       - 9000:9000
>       - 9001:9001
>     environment:
>       MINIO_ROOT_USER: minio
>       MINIO_ROOT_PASSWORD: minio123
>     command: server --console-address :9001 /data
> ```

Thank you for your comment.

I solved the problem of `ERROR Unable to start the server: --console-address cannot be same as --address` thanks to your yml file example.

I appreciated your help.

**Comment by GeeCastro** [comment]
For those who want the console on the same port, note that the June tag works: `image: minio/minio:RELEASE.2021-06-17T00-10-46Z`

**Comment by ardinusawan** [comment]
> > Hei I have similar problem but with docker compose. The file is from [official docs](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml)
> > ```
> > 
> > # starts 4 docker containers running minio server instances.
> > # using nginx reverse proxy, load balancing, you can access
> > # it through port 9000.
> > services:
> >   minio1:
> >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> >     hostname: minio1
> >     volumes:
> >       - data1-1:/data1
> >       - data1-2:/data2
> >     expose:
> >       - "9000"
> >     environment:
> >       MINIO_ROOT_USER: minio
> >       MINIO_ROOT_PASSWORD: minio123
> >     command: server http://minio{1...4}/data{1...2}
> >     healthcheck:
> >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> >       interval: 30s
> >       timeout: 20s
> >       retries: 3
> > 
> >   minio2:
> >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> >     hostname: minio2
> >     volumes:
> >       - data2-1:/data1
> >       - data2-2:/data2
> >     expose:
> >       - "9000"
> >     environment:
> >       MINIO_ROOT_USER: minio
> >       MINIO_ROOT_PASSWORD: minio123
> >     command: server http://minio{1...4}/data{1...2}
> >     healthcheck:
> >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> >       interval: 30s
> >       timeout: 20s
> >       retries: 3
> > 
> >   minio3:
> >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> >     hostname: minio3
> >     volumes:
> >       - data3-1:/data1
> >       - data3-2:/data2
> >     expose:
> >       - "9000"
> >     environment:
> >       MINIO_ROOT_USER: minio
> >       MINIO_ROOT_PASSWORD: minio123
> >     command: server http://minio{1...4}/data{1...2}
> >     healthcheck:
> >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> >       interval: 30s
> >       timeout: 20s
> >       retries: 3
> > 
> >   minio4:
> >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> >     hostname: minio4
> >     volumes:
> >       - data4-1:/data1
> >       - data4-2:/data2
> >     expose:
> >       - "9000"
> >     environment:
> >       MINIO_ROOT_USER: minio
> >       MINIO_ROOT_PASSWORD: minio123
> >     command: server http://minio{1...4}/data{1...2}
> >     healthcheck:
> >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> >       interval: 30s
> >       timeout: 20s
> >       retries: 3
> > 
> >   nginx:
> >     image: nginx:1.19.2-alpine
> >     hostname: nginx
> >     volumes:
> >       - ./nginx.conf:/etc/nginx/nginx.conf:ro
> >     ports:
> >       - "9000:9000"
> >     depends_on:
> >       - minio1
> >       - minio2
> >       - minio3
> >       - minio4
> > 
> > ## By default this config uses default local driver,
> > ## For custom volumes replace with volume driver configuration.
> > volumes:
> >   data1-1:
> >   data1-2:
> >   data2-1:
> >   data2-2:
> >   data3-1:
> >   data3-2:
> >   data4-1:
> >   data4-2:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Need help
> 
> @ardinusawan what is the problem? - I don't see any problem bringing up MinIO

My problem is same like the author.

**Comment by chayder** [comment]
> > > Hei I have similar problem but with docker compose. The file is from [official docs](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml)
> > > ```
> > > 
> > > # starts 4 docker containers running minio server instances.
> > > # using nginx reverse proxy, load balancing, you can access
> > > # it through port 9000.
> > > services:
> > >   minio1:
> > >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> > >     hostname: minio1
> > >     volumes:
> > >       - data1-1:/data1
> > >       - data1-2:/data2
> > >     expose:
> > >       - "9000"
> > >     environment:
> > >       MINIO_ROOT_USER: minio
> > >       MINIO_ROOT_PASSWORD: minio123
> > >     command: server http://minio{1...4}/data{1...2}
> > >     healthcheck:
> > >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> > >       interval: 30s
> > >       timeout: 20s
> > >       retries: 3
> > > 
> > >   minio2:
> > >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> > >     hostname: minio2
> > >     volumes:
> > >       - data2-1:/data1
> > >       - data2-2:/data2
> > >     expose:
> > >       - "9000"
> > >     environment:
> > >       MINIO_ROOT_USER: minio
> > >       MINIO_ROOT_PASSWORD: minio123
> > >     command: server http://minio{1...4}/data{1...2}
> > >     healthcheck:
> > >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> > >       interval: 30s
> > >       timeout: 20s
> > >       retries: 3
> > > 
> > >   minio3:
> > >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> > >     hostname: minio3
> > >     volumes:
> > >       - data3-1:/data1
> > >       - data3-2:/data2
> > >     expose:
> > >       - "9000"
> > >     environment:
> > >       MINIO_ROOT_USER: minio
> > >       MINIO_ROOT_PASSWORD: minio123
> > >     command: server http://minio{1...4}/data{1...2}
> > >     healthcheck:
> > >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> > >       interval: 30s
> > >       timeout: 20s
> > >       retries: 3
> > > 
> > >   minio4:
> > >     image: minio/minio:RELEASE.2021-07-08T19-43-25Z
> > >     hostname: minio4
> > >     volumes:
> > >       - data4-1:/data1
> > >       - data4-2:/data2
> > >     expose:
> > >       - "9000"
> > >     environment:
> > >       MINIO_ROOT_USER: minio
> > >       MINIO_ROOT_PASSWORD: minio123
> > >     command: server http://minio{1...4}/data{1...2}
> > >     healthcheck:
> > >       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
> > >       interval: 30s
> > >       timeout: 20s
> > >       retries: 3
> > > 
> > >   nginx:
> > >     image: nginx:1.19.2-alpine
> > >     hostname: nginx
> > >     volumes:
> > >       - ./nginx.conf:/etc/nginx/nginx.conf:ro
> > >     ports:
> > >       - "9000:9000"
> > >     depends_on:
> > >       - minio1
> > >       - minio2
> > >       - minio3
> > >       - minio4
> > > 
> > > ## By default this config uses default local driver,
> > > ## For custom volumes replace with volume driver configuration.
> > > volumes:
> > >   data1-1:
> > >   data1-2:
> > >   data2-1:
> > >   data2-2:
> > >   data3-1:
> > >   data3-2:
> > >   data4-1:
> > >   data4-2:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Need help
> > 
> > 
> > @ardinusawan what is the problem? - I don't see any problem bringing up MinIO
> 
> My problem is same like the author.

Hello everyone, 

I found that actual image version use two flags for define ports that are listening, you can set this ports with _--address ':[port]'_ and _--console-address ':[console_port]'_

both flags need are defining for avoid warnings.

1. For original warning: "WARNING: Console endpoint is listening on a dynamic port (40843), please use --console-address ":PORT" to choose a static port." you need also define port for console web view with above flags (--console-address). 

If you dont define this flag, web console will launch in a random port.

2. With '--address' flag  you can define a different port for background api service, and can be able api and console running in differents ports.

3. Refer to @Chichilele : "For those who want the console on the same port, note that the June tag works: image: minio/minio:RELEASE.2021-06-17T00-10-46Z"

Can i suggest give a better name to version to identify differences?, maybe something more mnemonic?. For dev team.

4. Here any examples over how to run this new version with flags:

- Docker run:

docker run -p 9000:9000 -p 9001:9001 \
-e "MINIO_ROOT_USER=test" \
-e "MINIO_ROOT_PASSWORD=test_key" \
minio/minio:latest server --address :9000 --console-address :9001 /data

By default api service running in port 9000, but if you use other service, by example portainer, this service also use port 9000, you can define differents ports with this flags.

- docker-compose.yml

For compose.yml file, refer previous answers, we need modify _command_ key in minio service definition, with any similar to:

version: '3'
services:
  minio-demo:
    image: minio/minio:latest
    container_name: minio-demo
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address :9001 /data

this last command key define run command for container, here we can define flags mentioned.

- docker-stack.yml

For stack.yml file, you can use above example, but you maybe need define _entrypoint_ and _command_ key in file with any differences:

[...]
entrypoint: sh
command: "-c '/usr/bin/minio server --address ':9000' --console-address ':9001' /data' "
[...]

Note: last stack example are based in minio service integration with another service in docker stack orchestation.

I hope that this information will be clear, excuse me if i not know how insert prettier code fragments.

**Comment by dgoo2308** [comment]
@harshavardhana is there a way with a nginx proxy path to have console and minio on the same domain? 

I have only one domain for minio!
  
I also tried to set `MINIO_SERVER_URL` and  `MINIO_BROWSER_REDIRECT_URL` to e.g. `https://mydomain/minio` and `https://mydomain/console` but that results in an error e.g.
```
ERROR Invalid MINIO_SERVER_URL value is environment variable: URL contains unexpected resources, expected URL to be of http(s)://minio.example.com format: https://example.com/minio
```
