### ISSUE TITLE
Browser console hosting improvements/ideas

### ISSUE THREAD

**Issue by momiji** [minio/minio#12661]
## Current Behavior

The new browser UI (console) is now available on a different port when starting minio.
This seems to be a new technical choice that allows splitting between the UI and the buckets.

However I find it difficult to setup now, because the UI is now hosted on a different port, ant it is not possible to prevent the redirection to this new port.

## Possible Solution
Without reverting to previous brower hosting (under /minio), I think it will be interesting to add new options to handle the redirection. I found several proposal when searching in the issues.

1. prevent redirection at all (MINIO_BROSER_REDIRECT=off)
- the new UI is only accessible if the user knows its' location, otherwise we only have the XML with AllAccessDiabled error
- we may setup a front proxy (nginx/haproxy/...) to redirect https to the console when the name is something specific to the console like, different that what is used for the buckets

2. provide the redirection url (MINIO_BROWSER_REDIRECT=https://console.mys3.mydomain)
- the users are automatically redirected to this dedicated URL
- as point 1. we need to setup the front proxy to handle the URL to redirect to minio console port

3. host the console in /minio as before
- prevents the use of a "minio" bucket, as before

4. implement browser detection logic in the front proxy
- but I feel this is much harder to do

## Your Environment
* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

I tested on RHEL, with latest minio docker file:

$ podman run --rm --network=host -v $PWD/data:/data -it minio/minio --version
minio version RELEASE.2021-07-08T19-43-25Z

**Comment by harshavardhana** [comment]
> 1. provide the redirection url (MINIO_BROWSER_REDIRECT=https://console.mys3.mydomain)
> 
> * the users are automatically redirected to this dedicated URL
> * as point 1. we need to setup the front proxy to handle the URL to redirect to minio console port

This is a neat idea, and definitely worth exploring and implementing. 

> * prevents the use of a "minio" bucket, as before

This is not possible anymore.
