### ISSUE TITLE
new feature breaks backwards compatiability

### ISSUE THREAD

**Issue by davidhadas** [minio/minio#12671]
## Expected Behavior
Backwards compatibility

## Current Behavior
Running minio from latest, minio stopped working due to https://github.com/minio/minio/commit/cdeccb5510f25d0019682f978c2c0aa02a5e12bf
Reason being 
1. changes in the default externalized behaviour 
2. existing config led to minio not working and writing to screen the error from this code:
        "WARNING: Console endpoint is listening on a dynamic port (%s), please use --console-address \":PORT\" to choose a static port.",

## Possible Solution
Keeping backwards compatibility should be mandatory when ever feasible.
Adding a config for a separate console port should not change backwards compatibility

## Steps to Reproduce (for bugs)
Most likely you can see this when starting minio in Kube with this spec (have not tried it..)
spec:
      containers:
          ports:
            - containerPort: 9000
              protocol: TCP
          image: 'minio/minio'
          args:
            - server
            - /storage

Instead, I was using a more elaborate spec:
spec:
      containers:
        - resources: {}
          name: minio
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: M1N10OSpss
            - name: MINIO_NOTIFY_KAFKA_ENABLE_HOOK
              value: 'on'
            - name: MINIO_NOTIFY_KAFKA_BROKERS_HOOK
              value: 'kafka-service:9092'
            - name: MINIO_NOTIFY_KAFKA_TOPIC_HOOK
              value: mytest
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          image: 'minio/minio'
          args:
            - server
            - /storage

## Context
I encountered this issue as I restarted my pod and since I am using a policy to always pull the image

## Regression

No

## Your Environment
Running Minio on Openshift with today's minio from docket hub

**Comment by harshavardhana** [comment]
@davidhadas there is no backward compatibility in UI - it is a project-wide decision. We are not planning to change back anything here. 

Documentation is updated on what is done and release notes are updated on what to expect. If you do not wish to upgrade don't do it. If you upgrade keep in mind things to consider.

https://github.com/minio/minio#test-using-minio-console

**Comment by davidhadas** [comment]
@harshavardhana 
1. Classifying this as a  UI issue is wrong. UI backwards compatibility is a minor issue - this is a backwards comaptiability issue of the basic service config -  and therefore users will be affected..!
2. When projects have minor and major releases, it is expected that major releases will include non backwards compatiability  but minor changes will not include such issues. 
3. Asking users to freeze to a version means they do not get security updates  - so this is not a working solutions for users. 

I am not making any statements against having this feature
All I am saying  is that  when a user have a working setup of minio with some existing config  and suddenly it stops working since the minio team decided to "add a feature" - this is plain bad for the project and its users

**Comment by harshavardhana** [comment]
> All I am saying is that when a user have a working setup of minio with some existing config and suddenly it stops working since the minio team decided to "add a feature" - this is plain bad for the project and its users

I don't think anything of this is broken here all the features work as is @davidhadas - I tried your spec it all works fine locally for me. 

You are not saying anything here other than showing what the error is.
