### ISSUE TITLE
new minio server won't start when using an external proxied ip address / if proxy ip disabled, SSO fails with wrong callback url 

### ISSUE THREAD

**Issue by thebrooder** [minio/minio#12688]
Upgraded to release RELEASE.2021-07-12T02-44-53Z from 2021-04-22T15-44-28Z breaks mino server located on a private vlan with service externally proxied with public IP address.    minio server fails to start when --address/--console-address parameter is not validated as a local host ip address (using public external proxy ip fails to start).
```
ERROR Unable to validate passed arguments: host in server address should be this server
      > Please check --address parameter
```
If proxy config is removed by changing the address parameter to be a valid "local" ip address, then keycloak SSO will break because the "public" callback/redirect URL that is generated for SSO by minio now uses  the local private ip address that is not accessible outside the private vlan.

## Expected Behavior
Minio should not try and validate the --address/--console-address ip addresses as local network interfaces before starting since a valid external load/balancer proxy configuration will break with this config. Release 2021-04-22T15-44-28Z, (pre console) the Minio Browser application SSO does not generate a redirect URL that uses a local ip address.

## Current Behavior
If --address or --console-address ip is not detected as a local interface, mino fails to start.  
If --address or --console-address is assigned to a private ip, 127.0.0.1, or 0.0.0.0 then service will start but keycloak SSO will break in console web application because self-generating call-back/redirect URL is invalid and doesn't route through an external public proxy ip address. 

## Possible Solution
Disable the local ip address validation, or  allow an external proxy URL configuration parameter that can be added and used for SSO generating callback/redirect URL (or other proxied URL's).

## Steps to Reproduce (for bugs)

1.  configure an externally hosted proxy/load balancer with public ip that points to minio.RELEASE.2021-07-12T02-44-53Z 
2.  configure minio --address/--console-address to use an external public IP
3.  start minio -> `error please check --address parameter`

#### Alternate configuration
1.  configure externally hosted proxy/loadbalancer with public ip
2.  configure minio with --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 and using keycloak SSO
3.  start minio -> service starts successfully
4.  but now connect with web browser and "Login with SSO" times out because `redirect_url=http://0.0.0.0` - same problem also happens if the --address is assigned to other alternate private ip addresses.

## Context
Minio installed in private VLAN with external proxied load balancer and public Keycloak SSO service. 

## Regression
Is this issue a regression? Yes
Problem does not occur with  2021-04-22T15-44-28Z as SSO redirect URL's generated by "Minio Browser" application do not hard-code local ip addresses in URL.

## Your Environment
* minio version RELEASE.2021-07-12T02-44-53Z
* Server setup and configuration:
* standalone Ubuntu 20.04 LTS, in private VLAN with public proxy/loadbalancer

**Comment by harshavardhana** [comment]
You can fix all of this by setting the correct REDIRECT_URL points to your console ingress

```
MINIO_IDENTITY_OPENID_REDIRECT_URI=http://your-console-dns/oauth_callback
```

for Console to be redirected to a custom ingress 

```
MINIO_BROWSER_REDIRECT_URL=http://your-console-dns/
```

**Comment by harshavardhana** [comment]
Closing this as just a configuration issue.
