### ISSUE TITLE
Minio kills itself every 12 hours

### ISSUE THREAD

**Issue by pkavajin** [minio/minio#12682]
Hey,

every 12 hours we see huge IO loads from minio which basically starve the io so much, minio itself isn't responding anymore.
Might be related to minio/minio#6541

Couldn't find any documentation on how to disable the scanning, but found documentation on how to turn some screws to make it run smoother, but even when dramatically increasing these settings we don't see a change in behaviour and still have minio die every 12 hours :/

## Expected Behavior
Minio doesn't create so much io load it can't handle traffic anymore

## Current Behavior
It actually does all 12 hours :/

## Possible Solution
* Allow disabling data usage scanner(?)
* Document working configurations for HDD based setups

## Your Environment
Current configuration:

$ ./mc admin config get foo/ scanner 
scanner delay=150.0 max_wait=120s cycle=2m 

$ ./mc admin config get foo/ ​heal   
heal bitrotscan=off max_sleep=30s max_io=10 

our setup consists of 24 HDDs running at 7200 rpms which have up to 10 TB of storage.
Currently we're using a fraction of that, and already run into this behaviour.

We're running minio 2021-06-07T21-40-51Z on k8s

Might be a misconfiguration from our side, currently having a hard time finding out sane settings to run minio on HDDs as the defaults apparently are not working out for our use case.

Thanks for any help in advance!

**Comment by harshavardhana** [comment]
@pkavajin those settings are not the issue here. 

Tell us what is the current setup like

- how much RAM do you have?
- how much I/O are you throwing at MinIO?
- share the container logs on why it dies?
- share the k8s events output on container does it restart, killed ?

**Comment by pkavajin** [comment]
Regarding IO:
![image](https://user-images.githubusercontent.com/28445986/125321119-a7f00500-e33c-11eb-94ce-e728916ee7ad.png)

And in regards of util, its pretty visible that every 12 hours something is going crazy:
![image](https://user-images.githubusercontent.com/28445986/125321244-c6560080-e33c-11eb-9ba0-4fcaa1626ba7.png)

6 Servers,
24 Disks in total
10 GB Mem + 4 CPUs per pod

Containers are not getting restarted, minio just gets really slow and slower and somewhen totally stops answering calls.

Regarding logs there apparently is some problem, lots of errors, but apparently the format logs are currently broken on minio, instead of a log message its just showing the go type, not sure if thats already a known issue:
```
{"deploymentid":"81d62034-f9cb-473e-8070-9b44d2f0cec6","level":"ERROR","errKind":"MINIO","time":"2021-07-12T15:58:57.229789207Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*errors.errorString","source":["cmd/peer-rest-client.go:703:cmd.(*peerRESTClient).UpdateMetacacheListing()","cmd/metacache-set.go:249:cmd.(*listPathOptions).updateMetacacheListing()","cmd/metacache-set.go:631:cmd.(*erasureObjects).listPath.func3.1()"]}}
{"deploymentid":"81d62034-f9cb-473e-8070-9b44d2f0cec6","level":"ERROR","errKind":"MINIO","time":"2021-07-12T15:58:59.508051752Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*errors.errorString","source":["cmd/peer-rest-client.go:703:cmd.(*peerRESTClient).UpdateMetacacheListing()","cmd/metacache-set.go:249:cmd.(*listPathOptions).updateMetacacheListing()","cmd/metacache-set.go:631:cmd.(*erasureObjects).listPath.func3.1()"]}}
{"deploymentid":"81d62034-f9cb-473e-8070-9b44d2f0cec6","level":"ERROR","errKind":"MINIO","time":"2021-07-12T15:58:59.508051752Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*errors.errorString","source":["cmd/peer-rest-client.go:703:cmd.(*peerRESTClient).UpdateMetacacheListing()","cmd/metacache-set.go:249:cmd.(*listPathOptions).updateMetacacheListing()","cmd/metacache-set.go:631:cmd.(*erasureObjects).listPath.func3.1()"]}}
```

**Comment by harshavardhana** [comment]
@pkavajin 

- first question are you using LVM underneath? - why do I see that you are using some LUKS encryption? - If yes please remove LUKS encryption from your disks.  You are better off using MinIO's encryption for data at rest encryption that provides tamper-proofing as well.  LUKS-based encryption is terrible for performance-driven use cases. 
- you can change the logging in containers by in tenant spec to see more errors
```
logging:
   anonymous: false 
   json: false
```

> 10 GB Mem + 4 CPUs per pod

This is not sufficient if you PUT a lot of load on MinIO - as it is it HDD based setup with restricted memory and low IOPS

**Comment by harshavardhana** [comment]
Closing this issue as it looks like a setup problem if you have production-level requirements @pkavajin please subscribe https://min.io/pricing we can provide deeper investigation and architecture help.
