### ISSUE TITLE
Can't get to Admin Web Console

### ISSUE THREAD

**Issue by worthwhileindustries** [minio/minio#12690]
As a test --

`docker run -p 9000:9000 -p 9001:9001 minio/minio:RELEASE.2021-07-08T01-15-01Z server /data --console-address="127.0.0.1:9001"`

I tried running this. Everything starts up. When I try to go to the console whether I include the --console-address or not I can't seem to get to the web interface.

## Expected Behavior
Pulls up the web interface when going to the admin console

## Current Behavior
![image](https://user-images.githubusercontent.com/3536254/125364932-9d2f7300-e330-11eb-8093-f83790822e1a.png)

## Steps to Reproduce (for bugs)

1. `docker run -p 9000:9000 -p 9001:9001 minio/minio:RELEASE.2021-07-08T01-15-01Z server /data --console-address="127.0.0.1:9001"`
2. got to the web console found below
API: http://172.17.0.2:9000  http://127.0.0.1:9000 

Console: http://localhost:9001 

Documentation: https://docs.min.io
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables

## Your Environment
Ubuntu 20
Docker version 19.03.13, build 4484c46d9d

**Comment by harshavardhana** [comment]
> * `docker run -p 9000:9000 -p 9001:9001 minio/minio:RELEASE.2021-07-08T01-15-01Z server /data --console-address="127.0.0.1:9001"`

if you run it like this how is the console supposed to be exposed to your host system? @worthwhileindustries 

Just run it like `--console-address ":9001"`  you even modified the copy pasted value incorrectly.
