### ISSUE TITLE
Azure gateway documentation is incorrect / outdated. Cannot connect to Console UI

### ISSUE THREAD

**Issue by tmoschou** [minio/minio#12692]
## Expected Behavior
The [Azure gateway documentation](https://github.com/minio/minio/blob/master/docs/gateway/azure.md#run-minio-gateway-for-microsoft-azure-blob-storage) should explain how to run Azure gateway and connect to console UI correctly.

## Current Behavior

Run 
```
docker run -p 9000:9000 --name azure-s3 \
 -e "MINIO_ROOT_USER=azurestorageaccountname" \
 -e "MINIO_ROOT_PASSWORD=azurestorageaccountkey" \
 minio/minio gateway azure
 ```

- MinIO warns about a dynamically allocated port for the console address. `WARNING: Console endpoint is listening on a dynamic port (45727), please use --console-address ":PORT" to choose a static port.`
- The console port is not forwarded when using Docker (needs `-p 9001:9001`)
- When the console port is bound using `--console-address :9001` the console is inaccessible using `MINIO_ROOT_USER` / `MINIO_ROOT_PASSWORD` as credentials. UI shows `Unauthorized`. This previously used to work for the embedded dashboard.
- When trying to create a console user using `mc admin user ...`, the CLI errors.
    ```
    mc admin user add myazure/
    Enter Access Key: console
    Enter Secret Key:
    mc: <ERROR> Unable to add new user. This 'admin' API is not supported by server in 'mode-gateway-azure'.
    ```

This [comment](https://github.com/minio/console/issues/176#issuecomment-820821376) seems to suggest that console will never work with gateway, in which case, MinIO launching an embedded console (and allowing `--console-address`) is rather confusing, as is the presence of the subsection [Test using MinIO Console](https://github.com/minio/minio/blob/master/docs/gateway/azure.md#test-using-minio-console).

I have not tested the other gateways but I presume their documentation is outdated also.

## Context
We are wishing to use MinIO Azure Gateway for local development and in cloud. 
We wish to use Azure Blob storage as it is cheaper, then attached disks. 

## Regression
Yes - Previously worked with `minio/minio:RELEASE.2021-06-17T00-10-46Z`, prior to moving to Console UI

## Your Environment
* Version used (`minio --version`): `RELEASE.2021-07-08T19-43-25Z`
* Server setup and configuration: Docker

**Comment by harshavardhana** [comment]
> mc admin user add myazure/
> Enter Access Key: console
> Enter Secret Key:
> mc: <ERROR> Unable to add new user. This 'admin' API is not supported by server in 'mode-gateway-azure'.

This is not supported without `etcd` in gateway read about etcd being a must for credentials to persist

> * When the console port is bound using `--console-address :9001` the console is inaccessible using `MINIO_ROOT_USER` / `MINIO_ROOT_PASSWORD` as credentials. UI shows `Unauthorized`. This previously used to work for the embedded dashboard.

This fixed in latest release do not use `:latest` tag instead pick `RELEASE.2021-07-12T02-44-53Z`

**Comment by harshavardhana** [comment]
FWIW updated the docs as well here e25ae1c01f8b3f75e6a8ca392a2faea105a479d8
