### ISSUE TITLE
Minio supports virtual appliance image

### ISSUE THREAD

**Issue by mmukul** [minio/minio#12699]
**Is your feature request related to a problem? Please describe.**
Does Minio supports virtual appliance image with complete minio stack

**Describe alternatives you've considered**
OVA as an virtual appliance image for minio

**Comment by harshavardhana** [comment]
@mmukul we support VMware vsphere dpp platform beyond that maintaining OVA is not planned.

https://min.io/product/private-cloud-vmware-tanzu
