### ISSUE TITLE
Do not have enough permissions to access this resource

### ISSUE THREAD

**Issue by soulwarT** [minio/minio#12708]
创建用户设置策略之后还是无法创建桶
![image](https://user-images.githubusercontent.com/79443972/125589905-b1f940b0-9cc2-470e-86d0-28782b35ff7d.png)
这是策略
![image](https://user-images.githubusercontent.com/79443972/125589970-c07e4b6c-b350-4b4f-ba15-f8115bb4d0a0.png)

**Comment by harshavardhana** [comment]
Closing the issue as incomplete 

- with all issue templates removed
- no MinIO version mentioned

**Comment by soulwarT** [comment]
版本7.0.2
