### ISSUE TITLE
AWS SDK STS requests get redirected to console when running in browser

### ISSUE THREAD

**Issue by UchihaYuki** [minio/minio#12701]
## Expected Behavior

It shouldn't be redirected.

## Current Behavior

It works when I set MINIO_BROWSER=off, and gets redirected to console when MINIO_BROWSER=on

## Steps to Reproduce (for bugs)

The following is what aws-sdk does in simple code
```javascript
const body = new URLSearchParams()
body.append("Action", "AssumeRoleWithWebIdentity")
body.append("WebIdentityToken", "xxx")
body.append("Version", "2011-06-15")
body.append("DurationSeconds", "86000")

fetch(`https://s3.example.com`, {
      method: 'POST',
      body
}).then()
```
The problem is, in either environment (MINIO_BROWSER=off and MINIO_BROWSER=off). The following code works:
```javascript
const body = new URLSearchParams()
body.append("Action", "AssumeRoleWithWebIdentity")
body.append("WebIdentityToken", "xxx")
body.append("Version", "2011-06-15")
body.append("DurationSeconds", "86000")

fetch(`https://s3.example.com/?${body.toString()}`, {
      method: 'POST'
}).then()
```

## Context

I want to use aws-sdk wrapper for this api to make my code consistency.

## Your Environment

* Version used (`minio --version`): https://dl.min.io/server/minio/release/linux-amd64/minio_20210712024453.0.0_amd64.deb
* AWS SDK version: aws-sdk@22.944.0 (javascript)

**Comment by ravindk89** [comment]
Note: based on some other [pulls](https://github.com/minio/minio-js/pull/929) we've had, making STS calls with JSON POST body vs query params has worked in the past. 

Original code for the STS block:

```javascript
const sts = new STS({
      region: US-EAST,
      endpoint: `https://s3.example.com`,
    });
const r = await sts.assumeRoleWithWebIdentity({
      WebIdentityToken: this.account.idToken,
      RoleArn: '',
      RoleSessionName: '',
    }).promise()
```

**Comment by vadmeste** [comment]
@UchihaYuki can you paste instead that code that is using AWS SDK ?

**Comment by ravindk89** [comment]
@vadmeste grabbed it from the Slack thread and placed it above.
