### ISSUE TITLE
Unable to update replication metadata after deletion of object with replication

### ISSUE THREAD

**Issue by hkirov** [minio/minio#12703]
## Expected Behavior

Meta data to be updated without errors. Replication Status to be COMLETE.

## Current Behavior

There is error: "Error: Unable to update replication metadata for .......(741da3e9-3d07-44e7-b6cc-8d59e5e04ec9): Storage resources are insufficient for the write operation ........ (*fmt.wrapError)"
Object stands with "Replication Status: PENDING" even after being replicated

## Steps to Reproduce (for bugs)

1. configure active-active bucket replication (not tested on one way it may be enough)
2. ....
3. `mc replicate add mymino/repbuck --remote-bucket content --arn 'arn:minio:replication::....:repbuck' --replicate "delete,delete-marker"`
4. ....
5. upload object to the bucket `mc cp somefile.bin myminio/repbuck`
6. delete object `mc rm myminio/repbuck/somefile.bin `
7. upload other file with the same object name `mc cp filetwo.bin myminio/repbuck/somefile.bin`

## Regression

Same happens in RELEASE.2021-06-17T00-10-46Z. Not sure before that.

## Your Environment

* Version used (`minio --version`): 2021-07-12T02:44:53Z
* Server setup and configuration: distributed bare-metal installation on two clusters  
* Operating System and version (`uname -a`): `Linux tafl-serv1 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by hkirov** [comment]
This is messages from minio console log:

> Jul 13 18:32:07 site1 minio[2990]: API: SYSTEM()
Jul 13 18:32:07 site1 minio[2990]: Time: 18:32:07 BST 07/13/2021
Jul 13 18:32:07 site1 minio[2990]: DeploymentID: cfc01be1-9ea9-4b9d-8b61-b6023a50e226
Jul 13 18:32:07 site1 minio[2990]: Error: Unable to update replication metadata for storage/cont_farm2g/mladen/mladen1.mp4(741da3e9-3d07-44e7-b6cc-8d59e5e04ec9): Storage resources are insufficient for the write operation storage/cont_farm2g/mladen/mladen1.mp4 (*fmt.wrapError)
Jul 13 18:32:07 site1 minio[2990]:        2: cmd/bucket-replication.go:748:cmd.replicateObject()
Jul 13 18:32:07 site1 minio[2990]:        1: cmd/bucket-replication.go:1034:cmd.(*ReplicationPool).AddWorker()

`mc ls --versions site1/storage/cont_farm2g/mladen/mladen1.mp4`

> [2021-07-12 11:58:18 EEST] 836KiB 30e039c0-e088-410a-8734-af7f247d5ee3 v4 PUT mladen1.mp4
[2021-07-12 11:58:04 EEST] 836KiB 741da3e9-3d07-44e7-b6cc-8d59e5e04ec9 v3 PUT mladen1.mp4
[2021-07-12 11:56:52 EEST]     0B 91cc290f-bdc7-4fc4-8a54-bce3fbb19e63 v2 DEL mladen1.mp4
[2021-07-08 23:55:07 EEST] 836KiB 5d786d95-a8ed-4c6e-b31c-561ea09e3042 v1 PUT mladen1.mp4

`mc ls --versions site2/storage/cont_farm2g/mladen/mladen1.mp4`

> [2021-07-12 11:58:18 EEST] 836KiB 30e039c0-e088-410a-8734-af7f247d5ee3 v4 PUT mladen1.mp4
[2021-07-12 11:58:04 EEST] 836KiB 741da3e9-3d07-44e7-b6cc-8d59e5e04ec9 v3 PUT mladen1.mp4
[2021-07-12 11:56:52 EEST]     0B 91cc290f-bdc7-4fc4-8a54-bce3fbb19e63 v2 DEL mladen1.mp4
[2021-07-08 23:55:07 EEST] 836KiB 5d786d95-a8ed-4c6e-b31c-561ea09e3042 v1 PUT mladen1.mp4

`mc stat site1/storage/cont_farm2g/mladen/mladen1.mp4`

> Name      : mladen1.mp4
Date      : 2021-07-12 11:58:18 EEST 
Size      : 836 KiB 
ETag      : b3059755a8624d325565c47a6a8fb670 
VersionID : 30e039c0-e088-410a-8734-af7f247d5ee3 
Type      : file 
Metadata  :
  Content-Type: video/mp4 
Replication Status: PENDING 


`mc stat site2/storage/cont_farm2g/mladen/mladen1.mp4`

> Name      : mladen1.mp4
Date      : 2021-07-12 11:58:18 EEST 
Size      : 836 KiB 
ETag      : b3059755a8624d325565c47a6a8fb670 
VersionID : 30e039c0-e088-410a-8734-af7f247d5ee3 
Type      : file 
Metadata  :
  Content-Type: video/mp4 
Replication Status: REPLICA

**Comment by harshavardhana** [comment]
I think this has been fixed by #12711 // cc @poornas @vadmeste  please confirm

**Comment by vadmeste** [comment]
This doesn't seem an issue per se, the cluster wasn't able to update the replication status in the source cluster. The worst that could happen in this case is that the source object will be double replicated which seems to be acceptable.

@poornas any comment?

**Comment by poornas** [comment]
This is not related to #12711 . 
The original replication operation failed to update the metadata from `PENDING` to `COMPLETED` because of insufficient storage resources. When the scanner picks this object for healing, the replication status should update to `COMPLETED` - Note that this will not be double replicated as there is a HEAD operation to check if the object version is already replicated before attempting it.

**Comment by hkirov** [comment]
This is happening on a cluster with all drives online without errors. What is causing "insufficient storage resources"?

**Comment by harshavardhana** [comment]
> This is happening on a cluster with all drives online without errors. What is causing "insufficient storage resources"?

Temporary disconnections, network saturation, and some other underlying setup issues?

**Comment by hkirov** [comment]
> > This is happening on a cluster with all drives online without errors. What is causing "insufficient storage resources"?
> 
> Temporary disconnections, network saturation, and some other underlying setup issues?

Strange. I was with the impression that this happens every time. It is the same every time when I tried that. I've tested this again in our second lab installation and the results were the same. Can you try to reproduce it?

- create active-active server side bucket replication with --replicate "delete,delete-marker" (not tested on one way it may be enough)
- upload object to the bucket
- delete object from the bucket
- upload file with the same object name to the bucket

In my experience this leads to "insufficient storage resources" error.
