### ISSUE TITLE
Unable to access the website

### ISSUE THREAD

**Issue by zrkcoder** [minio/minio#12718]
Minio version：
![image](https://user-images.githubusercontent.com/71759908/125727282-90ea39e7-5d64-4354-86b8-72c719918c2d.png)

Error Image:
![image](https://user-images.githubusercontent.com/71759908/125727087-2c1ddf83-6baa-4ef7-b448-d9f2d029aa55.png)

**Comment by harshavardhana** [comment]
Looks like this is a known issue with windows setting incorrect mime type

https://github.com/minio/minio/issues/12654#issuecomment-876984107

Please follow the workaround.
