### ISSUE TITLE
original error -> (user_login.go:50: invalid Login)

### ISSUE THREAD

**Issue by imkos** [minio/minio#12719]
![image](https://user-images.githubusercontent.com/17872894/125760079-f4571a27-1209-4547-9c1c-fc546e996c76.png)

image: minio/minio:RELEASE.2021-07-12T02-44-53Z

Cannot log in to the console.

**Comment by cchris-org** [comment]
Same here. Can't login

**Comment by vadmeste** [comment]
@imkos did you open http://address:9001/ and you weren't able to login using MINIO_ROOT_USER & MINIO_ROOT_PASSWORD ?

**Comment by harshavardhana** [comment]
@imkos closing this issue

First, describe in detail what doesn't login - what is the user and level of permissions etc.  Let's reopen when you have provided such details.

**Comment by imkos** [comment]
Why should I close the issue? Start this issue according to my yaml above, and the issue can be reproduced 100%

**Comment by imkos** [comment]
@harshavardhana This issue cannot be reopened.
