### ISSUE TITLE
Add state parameter for OIDC

### ISSUE THREAD

**Issue by georglauterbach** [minio/minio#12713]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to integrate MinIO into an OIDC provider, in my case Authelia, only to realize that MinIO does not support the state parameter at all. Please have a look at the comments in  #11398, especially @james-d-elliott's comments. It is a **recommended** parameter according to the RFC.

**Describe the solution you'd like**

Please, somehow integrate the state parameter.

**Describe alternatives you've considered**

Not using this parameter, AFAIK, comes with decreased security - something no one wants. There are no alternatives, and **no**, using Console is not an alternative.

**Additional context**

- https://datatracker.ietf.org/doc/html/rfc6749#section-11.2.2
- https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

And please see #11398.

**Comment by harshavardhana** [comment]
@georglauterbach not sure what you mean we always use state parameter in our latest release.

We used to support implicit flow but we do not anymore - we specifically set state parameter since we have moved to authorization flow.

**Comment by georglauterbach** [comment]
> @georglauterbach not sure what you mean we always use state parameter in our latest release.
> 
> We used to support implicit flow but we do not anymore - we specifically set state parameter since we have moved to authorization flow.

Oh. I will test the latest release and report back and close if this works.

**Comment by georglauterbach** [comment]
I can confirm state is now not an issue anymore. Sorry for the noise.
