### ISSUE TITLE
MINIO_BROWSER_REDIRECT_URL not support location proxy pass

### ISSUE THREAD

**Issue by ZxcSoft** [minio/minio#12727]
nginx proxy minio by using location proxy . but when start minio. it seem failed.
```
ERROR Invalid MINIO_BROWSER_REDIRECT value is environment variable: URL contains unexpected resources, expected URL to be of http(s)://minio.example.com format: https://www.example.com/file-console/
```

## Expected Behavior

minio start up success，and i can acces the console page.

## Current Behavior

console proxy by nginx location proxy not support， it is only support like  http(s)://minio.example.com

## Steps to Reproduce (for bugs)

nginx config like
···
        location ^~/file/ {
            proxy_pass http://127.0.0.1:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
        }

        location ^~/file-console/ {
            proxy_pass http://127.0.0.1:9001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
        }
···

start shell like

```
#!/bin/bash
export MINIO_ROOT_USER=admin
export MINIO_ROOT_PASSWORD=xxxxxx
export MINIO_BROWSER_REDIRECT_URL='https://www.example.com'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

nohup ${DIR}/minio server --console-address ":9001" --address ":9000" ${DIR}/data > out.log 2>&1 &

```

## Regression

 Is this issue a regression? Yes
version : minio version RELEASE.2021-07-12T02-44-53Z
#12665

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2021-07-12T02-44-53Z
* Server setup and configuration:  
* Operating System and version (`uname -a`): Linux 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
No we cannot support random locations - it needs to be at root URL @ZxcSoft - unfortunately this is out of scope.

**Comment by djerfy** [comment]
@ZxcSoft there are 2 options for me:

* use another domain, by example minio-console.example.com
* use `proxy_redirect` on nginx and set a custom redirection

**Comment by harshavardhana** [comment]
> * use another domain, by example minio-console.example.com

👍🏽

**Comment by serge-salamanka** [comment]
hi, devs! this is really a breaking change for my usage case: i am using docker containers behind proxy accessable on port and access service endpoints with `http://host:port/service`
This is very important and now is not possible :(

And it is so hard to understand your motivation to impose on how to use internet (with domain access only).

**Comment by harshavardhana** [comment]
> hi, devs! this is really a breaking change for my usage case: i am using docker containers behind proxy accessable on port and access service endpoints with `http://host:port/service`
> This is very important and now is not possible :(
> 
> And it is so hard to understand your motivation to impose on how to use internet (with domain access only).

For now, it's not supported, we shall try to support it in the future but for now, we do not have the necessary cycles to address it - Sorry.  

Feel free to send a PR to https://github.com/minio/console we are happy to accept it.

**Comment by 030** [comment]
@serge-salamanka-1pt Did you already create a PR?
