### ISSUE TITLE
Setting the lifecycle for the bucket did not take effect

### ISSUE THREAD

**Issue by evt-byte** [minio/minio#12730]
Deployed in a k8s environment with 4 pods.
Set the lifecycle for the bucket, it is set successfully and can be queried, but the expired object is not deleted.

## Expected Behavior

Reach lifecycle expiration time, automatically delete expired objects.

## Current Behavior

The lifecycle expiration time is reached and the expired object is not automatically deleted.

## Steps to Reproduce (for bugs)

1.Deployment is complete, wait for the service to start successfully and initialization is complete
2.Create aliases and create bucket
3.Use `mc ilm add --expiry-days 1 client/lifecycle1` to set the lifecycle for the bucket, the expiration time is 1 day
4.Query the bucket's lifecycle settings：
bash-4.4$ mc ilm ls client/lifecycle1
          ID          |     Prefix     |  Enabled   | Expiry |  Date/Days   |  Transition  |    Date/Days     |  Storage-Class   |          Tags          
----------------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------------
 c3nu5e2jpg2vi2lbiblg |                |    ✓       |  ✓     |   1 day(s)   |     ✗        |                  |                  |                        
----------------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------------

5.Upload a file to a bucket that has a lifecycle set
6.Wait 1 day and check if the file is deleted automatically
7.Not deleted
bash-4.4$ mc ls client/lifecycle1 
[2021-07-15 08:00:05 UTC] 100MiB test.25
[2021-07-15 07:25:25 UTC] 100MiB test.lifecycle
bash-4.4$ date
Fri Jul 16 09:09:35 UTC 2021
bash-4.4$ 

## Context

Need lifecycle to automatically delete expired files, this is a very critical feature, we need it.

## Your Environment

* Version used (`minio --version`): minio-RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration: Distributed deployment with no special settings
* Operating System and version (`uname -a`): Linux  4.18.0-240.22.1.el8_3.x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@evt-byte, according to the S3 specification, the object will only be removed in the midnight that follows the elapsed 24 hours. You can check with `mc stat alias/bucket/object`.

**Comment by evt-byte** [comment]
@vadmeste I executed this command with the following result：
bash-4.4$ mc stat client/core1/t.0
Name      : t.0
Date      : 2021-07-15 07:22:44 UTC 
Size      : 100 MiB 
ETag      : 38c7f52dae469114a8d43b09f45f127e-7 
Type      : file 
Expiration: 2021-07-17 00:00:00 UTC (lifecycle-rule-id: expire-core1) 
Metadata  :
  Content-Type: text/plain 
Encrypted :
  X-Amz-Server-Side-Encryption: AES256 

Is this normal? I thought lifecycle was the beginning of the object creation time and the end of the period of 1 day.
Like: 
Date         : 2021-07-15 07:22:44 UTC 
Expiration : 2021-07-16 07:22:44 UTC (lifecycle-rule-id: expire-core1)

**Comment by vadmeste** [comment]
It is part of the S3 spec. The expiration is correct.

**Comment by evt-byte** [comment]
OK, I got it, thanks a lot. @vadmeste 👍

**Comment by cbfischer** [comment]
Hi, @vadmeste , the lifecycle worked as well only in the root bucket folder (or preffix). 
Is there a way to expire all files recursively, even the file was placed into a folder? (like: /mybucket/folder1/folder2/folder3/here.txt).

mc ilm add --expiry-days "1" play/mybucket

**Comment by klauspost** [comment]
@cbfischer  `mc ilm add --expiry-days "1" play/mybucket/folder1/folder2/folder3/` adds with prefix.

**Comment by cbfischer** [comment]
@klauspost , but I have millions of folders into the bucket and I need to do lifecycle recursive. Is there a way to do that? Like  (play/bucket/*)

**Comment by klauspost** [comment]
@cbfischer Yes, that is similar to adding no prefix.
