### ISSUE TITLE
Exception after stop minio cluster and then restart cluster

### ISSUE THREAD

**Issue by moyuanz** [minio/minio#12731]
1. our cluster has 2 server pool, each node having 2 disks, each server pool having 2 nodes, like below
minio server http://minio-{1...2}/miniodata/data{1...2} \
                    http://minio-{3...4}/miniodata/data{1...2} ）

2. we already have created several thousands buckets and objects in cluster
3. stop cluster
4. restart cluster 

## Expected Behavior
cluster restart normally

## Current Behavior
Exception happened at node 1.

![Capture](https://user-images.githubusercontent.com/37684059/125926510-05743563-510a-4990-b42b-62923383354d.PNG)

**Comment by vadmeste** [comment]
@moyuanz please follow the template next time.

What MinIO server version is this ?

**Comment by harshavardhana** [comment]
Please upgrade your server this has been fixed quite some time ago @moyuanz
