### ISSUE TITLE
An exception occurred while restarting

### ISSUE THREAD

**Issue by Jam-Don** [minio/minio#12737]
I'm using the latest version

our cluster has 2 server pool, each node having 2 disks, each server pool having 2 nodes, like below
minio server http://minio-{1...2}/miniodata/data{1...2}
http://minio-{3...4}/miniodata/data{1...2} ）

we already have created several thousands buckets and objects in cluster

stop cluster

restart cluster
## Expected Behavior

cluster restart normally

## Current Behavior

Exception happened at node 1.
![image](https://user-images.githubusercontent.com/57789488/126090414-61ad6efa-39a0-4eec-b1c3-ec6abaf3dae5.png)

**Comment by harshavardhana** [comment]
Please upgrade to latest this has been fixed many releases ago.

**Comment by harshavardhana** [comment]
Oh my bad looks like a recent issue. Let me check it out..

**Comment by harshavardhana** [comment]
> we already have created several thousands buckets and objects in cluster

First of all, it's naive to create thousands of buckets - looks like you have architectured your system incorrectly.  You should generally have fewer buckets and do not use it like some Dropbox like system providing one bucket per user. 

However, the issue is weird because it looks like the crash is happening because of multiple scanner's running on the same system.

How often is this reproducible? @Jam-Don

**Comment by moyuanz** [comment]
> 
> 
> > we already have created several thousands buckets and objects in cluster
> 
> First of all, it's naive to create thousands of buckets - looks like you have architectured your system incorrectly. You should generally have fewer buckets and do not use it like some Dropbox like system providing one bucket per user.
> 
> However, the issue is weird because it looks like the crash is happening because of multiple scanner's running on the same system.
> 
> How often is this reproducible? @Jam-Don

Always. Actually we create 100K buckets.
Any suggestion to how many buckets are reasonable in production environment?

**Comment by harshavardhana** [comment]
> Any suggestion to how many buckets are reasonable in production environment?

Not more than 100 @Jam-Don, 1000 perhaps the worst , 100k buckets are really a poor way to manage your deployment.

**Comment by klauspost** [comment]
@Jam-Don Could you confirm which version you are running.

Also please include all output from the server. It is just getting cut off where it is getting interesting.

**Comment by harshavardhana** [comment]
@klauspost I was able to reproduce this when running `warp`

```
fatal error: concurrent map read and map write

goroutine 949361 [running]:
runtime.throw(0x1f5745e, 0x21)
        runtime/panic.go:1117 +0x72 fp=0xc0039eb828 sp=0xc0039eb7f8 pc=0x438312
runtime.mapaccess1_faststr(0x1c3bb00, 0xc00ebcf920, 0xc011b00420, 0x13, 0x0)
        runtime/map_faststr.go:21 +0x465 fp=0xc0039eb898 sp=0xc0039eb828 pc=0x413fa5
github.com/minio/minio/cmd.(*dataUsageCache).flatten(0xc0017f8af0, 0x1c0000, 0x0, 0x0, 0x0, 0x0, 0xe, 0x0, 0xe, 0x0, ...)
        github.com/minio/minio/cmd/data-usage-cache.go:343 +0x12c fp=0xc0039eba60 sp=0xc0039eb898 pc=0x15ebf8c
github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage.func2(0xc001ec8670, 0xc00b18cd00, 0xc, 0x10, 0xc002580de0, 0x2283a90, 0xc009dbc340, 0xc, 
0x4, 0x4, ...)
        github.com/minio/minio/cmd/erasure.go:433 +0xbd8 fp=0xc0039ebf28 sp=0xc0039eba60 pc=0x182c478
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc0039ebf30 sp=0xc0039ebf28 pc=0x472621
created by github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage
        github.com/minio/minio/cmd/erasure.go:387 +0x7ec

goroutine 1 [chan receive, 27 minutes]:
github.com/minio/minio/cmd.serverMain(0xc0002af860)
        github.com/minio/minio/cmd/server-main.go:551 +0xafd
github.com/minio/cli.HandleAction(0x1b94c00, 0x1fbc588, 0xc0002af860, 0xc00003b300, 0x0)
        github.com/minio/cli@v1.22.0/app.go:500 +0xc2
github.com/minio/cli.Command.Run(0x1f1d616, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1f4834b, 0x1b, 0x0, ...)
        github.com/minio/cli@v1.22.0/command.go:225 +0x9bb
github.com/minio/cli.(*App).Run(0xc0002ae4e0, 0xc0001a8120, 0x6, 0x6, 0x0, 0x0)
        github.com/minio/cli@v1.22.0/app.go:261 +0x768
github.com/minio/minio/cmd.Main(0xc0001a8120, 0x6, 0x6)
        github.com/minio/minio/cmd/main.go:167 +0x89
main.main()
        github.com/minio/minio/main.go:35 +0x45
```

**Comment by klauspost** [comment]
@harshavardhana Which version is this? `crawlAndGetDataUsage` was renamed quite a while ago.

I believe this sync call fixes that: https://github.com/minio/minio/pull/12279/files#diff-48117f63998d81f4709606c85accf2a5b2945a645b181fa25683640febd78c9dR511 - and the function is different anyway.

**Comment by harshavardhana** [comment]
> @harshavardhana Which version is this? `crawlAndGetDataUsage` was renamed quite a while ago.
> 
> I believe this sync call fixes that: https://github.com/minio/minio/pull/12279/files#diff-48117f63998d81f4709606c85accf2a5b2945a645b181fa25683640febd78c9dR511 - and the function is different anyway.

My bad it was some other random version, sorry it's not the same
