### ISSUE TITLE
Can not reach /minio/v2/metrics/cluster prometheus metrics with ssl enabled

### ISSUE THREAD

**Issue by ramazanjusip** [minio/minio#12741]
Hi!

I get `server returned HTTP status 403 Forbidden` on prometheus when I try to reach metrics endpoint `/minio/v2/metrics/cluster` by https (minio with ssl enabled). If I remove `--certs-dir` all works fine without ssl. S3 API works as expected with https.

## Expected Behavior
Metrics endpoint `https://<minio_server>:9000/minio/v2/metrics/cluster` must be available.

## Current Behavior
Prometheus can not retreive metrics from minio and returns `server returned HTTP status 403 Forbidden`.

## Possible Solution
Currently using metrics_path: `/minio/prometheus/metrics` with much less and informative metrics available.

## Steps to Reproduce (for bugs)
1. Run minio server with ssl certificate 
```
minio --certs-dir=/mnt/minio/certs server /mnt/minio
```
*Does not depend on which MINIO_PROMETHEUS_AUTH_TYPE is set.

2. Configure minio exporter in prometheus.yml Prometheus configuration file with:
```
'metrics_path': '/minio/v2/metrics/cluster', 'scheme': 'https', 'static_configs': [{'targets': ['<minio_server>:9000']}]
```

## Context
I want to configure monitoring with full metrics available from `/minio/v2/metrics/cluster` but currently using less with '/minio/prometheus/metrics'.

## Your Environment
* MinIO version: RELEASE.2020-03-25T07-03-04Z
* OS version: CentOS Linux release 8.3.2011

**Comment by vadmeste** [comment]
Investigating this..

**Comment by vadmeste** [comment]
> MinIO version: RELEASE.2020-03-25T07-03-04Z
This an old version and `/minio/v2/metrics/cluster` is not implemented in that version.

Please upgrade if you want more complete prometheus information.
