### ISSUE TITLE
STS Permissions in Assume Role Started Giving 403 Errors In RELEASE.2021-07-12T02-44-53Z

### ISSUE THREAD

**Issue by vpillinger** [minio/minio#12756]
The July 15, 2021 update of Minio broke something related to custom policies in Assume Role STS requests.

## Expected Behavior
Custom policies apply to assumed roles.

## Current Behavior
The user of the assumed role gets a 403 "Access Denied" response.

## Possible Solution
After debugging, I have no clue why the access is denied, but I tied it specifically to version minio.RELEASE.2021-07-15T22-27-34Z because reverting to .RELEASE.2021-07-12T02-44-53Z fixed the problem. 

## Steps to Reproduce (for bugs)

1. Create an assumed role with the following parameters:
```
const policy = {
	Version: '2012-10-17',
	Statement: [
		{
			Sid: Math.random().toString().substr(2, 8),
			Action: ['s3:AbortMultipartUpload', 's3:ListMultipartUploadParts', 's3:PutObject'],
			Effect: 'Allow',
			Resource: `arn:aws:s3:::*`,
		},
	],
};

const params: AWS.STS.AssumeRoleRequest = {
	RoleArn: config.fileStorage.ROLE_ARN,
	RoleSessionName: `uploader${Math.random()}`,
	Policy: JSON.stringify(policy),
	DurationSeconds: 3600,
};
const { Credentials } = await sts.assumeRole(params).promise();
return {
	accessKeyId: Credentials.AccessKeyId,
	secretAccessKey: Credentials.SecretAccessKey,
	sessionToken: Credentials.SessionToken,
	expiration: Credentials.Expiration,
};
```
2. Use the resulting creds to upload a file:
```
const testKey = 'test/abc123';
const putParams: AWS.S3.PutObjectRequest = {
	Bucket: fileStorage.bucket,
	Body: 'someData',
	Key: testKey,
};
const credentials = await getTemporaryUploadCreds(testKey);

/** An S3 authenticated with the creds for STS */
const s3 = new AWS.S3({
	...fileStorage.getConfig(),
	credentials,
});

const res = await s3.putObject(putParams).promise();

```

**NOTE: The request will work if no policy is set at all in the params, as it will default to the user's original policy**

## Context

This is used to provide clients with the ability to upload multi-part files to a specific key(s) without requiring the server to sign keys for every part.

## Regression
> YES
One of the PRs in minio.RELEASE.2021-07-15T22-27-34Z caused this issue. Most likely this one related to STS changes: https://github.com/minio/minio/pull/12716/files

## Your Environment

* Version used (`minio --version`): minio.RELEASE.2021-07-15T22-27-34Z
* Server setup and configuration: Minio setup as per Laravel Homestead: https://github.com/laravel/homestead/blob/main/scripts/features/minio.sh
With the following policy setup:
```
# Create minio access group, create new user then add to group.
mc admin user add homestead homestead_app secretkey
mc admin group add homestead rwUsers homestead_app
mc admin policy set homestead readwrite group=rwUsers
```
* Operating System and version (`uname -a`): #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> 	Policy: JSON.stringify(policy),

This needs to be base64 @vpillinger

**Comment by EBallou** [comment]
Is this related to https://github.com/minio/console/issues/871
