### ISSUE TITLE
prefix usage is not supported

### ISSUE THREAD

**Issue by moinologics** [minio/minio#12769]
getting this error and some functionalities not working

Error: prefix usage is not supported (*errors.errorString)
       2: cmd/admin-handlers-users.go:1110:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

VERSION:
  RELEASE.2021-07-15T22-27-34Z

**Comment by harshavardhana** [comment]
This is fixed in master ab7584eeac28cc4cb601e06dd1c759dde0b0dcef

**Comment by moinologics** [comment]
how to upgrade to fixed this?

because no release for commit ab7584e

**Comment by alphayan** [comment]
me too.
I google for hours!

**Comment by harshavardhana** [comment]
> how to upgrade to fixed this?

Wait for the release @ProgrammingPlanet or build from source `go install github.com/minio/minio@master`
