### ISSUE TITLE
Small Object Storage  Very Slow,does there has any way to improve the performance?

### ISSUE THREAD

**Issue by SigmaGavin** [minio/minio#12762]
My minio version is:Version: 2021-06-17T00:10:46Z
My minio cluster have 4 drivers
My  driver used zfs, 30 device makes one dirver.such as:

here are my zfs speed:
![image](https://user-images.githubusercontent.com/26948255/126484348-ddadd6e7-8ebf-444a-93f5-d2166ff30b89.png)

here are my  uploading a large object  to minio server's speed:
223M/s
here are my  uploading  many small objects  to minio server's speed:
4M/s
here are my  "rclone copy  minio:/testspeed/data/ /tmp -P"  to minio server's speed:
50M/s

I have read the  minio  blog:
  https://blog.min.io/minio-optimizes-small-objects/
  https://blog.min.io/small_objects/

I used "mc cp <path-to-archive>.tar play/mybucket --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true"",the speed is:
189M/s

but  i have to upload small files  without ".tar".  " tar" the small files spend a lot of time.So, is there any way to impove the performance to upload a lot of small files?Dose there have any  "attr" to do this?Such as   "X-Amz-Meta-Snowball-Auto-Extract=true".
I know you have improve the performance of upload small files in thre relese 2021.04.22,but it seems not efficient,my speed still "4M/s".so hope your helps!

**Comment by harshavardhana** [comment]
Do not use ZFS, use XFS and provide single drives directly to MinIO instead of providing single drive.
