### ISSUE TITLE
minio/spark-select via scala 2.12

### ISSUE THREAD

**Issue by Rozzerus** [minio/minio#12761]
Hi dears collegues,
 The minio is great.
But when I try to use spark-select  I have a problem.
I use scala 2.12 in my project.
And I want to improve my performance.
But spark-select doesn't work via scala 2.12.
It's only for 2.11
Do you plan to update this and will be supporting this scala 2.12 version?
Please give me know something about this. It's really Important for me.

**Comment by harshavardhana** [comment]
spark-select project is deprecated and not maintained anymore.

There won't be any new additional updates sorry.
