### ISSUE TITLE
Object count from mc admin info doesn't change

### ISSUE THREAD

**Issue by jinjyoo** [minio/minio#12760]
I have a K8s cluster with 6 Minio pods in K8s which I've been running `mc admin info <alias>` against periodically for the past two weeks in order to track object counts - but for the past few days, the returned object count has been staying static (despite high ongoing Minio activity).

## Expected Behavior

`mc admin info <alias>` returns an updated object count.

## Current Behavior

`mc admin info <alias>` (presumably) isn't returning an updated object count.

## Steps to Reproduce (for bugs)

1.

## Context

* This Minio cluster was suffering from high disk saturation until two weeks ago - we decided to trim the object count since it was at over 4 million objects, mostly concentrated in one bucket. One another note - **one of the Minio pods has been temporarily scaled down** since it was suffering connectivity issues, and has been kept down since before this issue (so it shows up as `offline` as expected).
* Attempting to delete older objects via `mc rm` was causing problems (slow, and causing some PUT operations elsewhere to fail - probably due to the heavy disk saturation), so we disabled the PUT operations to the big bucket and **then ran `rm -rf` from each pod on the same directories**, which ran smoothly; then we re-enabled the PUTs to the bucket, and observed normal behavior (the directories were recreated when PUTs began being sent to them, etc.).
* Over the next week, we monitored the object count with `mc admin info <alias>` - the object count went down steadily at first (presumably from lag in updating the object count since `mc` wasn't used). **Eventually it went down below 200K, before climbing back up (which is expected)**.
* ~5 days ago, we ran the manual `rm -rf` cleanup again, and right afterwards, set up an hourly cleanup job (just a K8s cronjob that cleans up objects in the big bucket that are older than 3 days). The cleanup job has been working since then (there are successful delete logs), but since around the time we ran the second manual cleanup, the object count reported by `mc admin info` has been fixed at `1,152,745`, rather than changing like it did after the first manual cleanup.

Since `mc admin info` was working as expected after our first manual cleanup, I'm not sure if it's related; and uptime is being updated for each server, just not the object count. It's not critical functionality-wise that we can see object counts, but we'd like to be able to monitor it for a while to assess how the cleanup job is doing, since we don't want the object count to balloon and cause degraded performance again.

We also ran `mc admin info --debug --json <alias>` and didn't see anything unusual:
```
mc: <DEBUG> GET /minio/admin/v3/info HTTP/1.1
Host: minio:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-08-20T00:23:01Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20210720//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210720T150914Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 3249
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Tue, 20 Jul 2021 15:09:14 GMT
Server: MinIO/DEVELOPMENT.2021-04-15T16-38-02Z
Vary: Origin
X-Amz-Request-Id: 1693884CD8A11320
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  57.230647ms

{
    "status": "success",
    "info": {
        "mode": "online",
        "deploymentID": "409f8b68-65f9-4c5a-a783-6245f3ce7a0b",
        "buckets": {
            "count": 4
        },
        "objects": {
            "count": 1152745
        },
        "usage": {
            "size": 13992660108
        },
        "services": {
            "vault": {
                "status": "disabled"
            },
            "ldap": {}
        },
        "backend": {
            "backendType": "Erasure",
            "offlineDisks": 1,
            "onlineDisks": 5,
            "rrSCData": 4,
            "rrSCParity": 2,
            "standardSCData": 3,
            "standardSCParity": 3
        },
        "servers": [
            {
                "state": "ok",
                "endpoint": "minio-0.minio:9000",
                "uptime": 429071,
                "version": "2021-04-15T16:38:02Z",
                "commitID": "1f04e47d11d8d884ea1e23f4d383841f15ee1cb4",
                "network": {
                    "minio-0.minio:9000": "online",
                    "minio-1.minio:9000": "online",
                    "minio-2.minio:9000": "online",
                    "minio-3.minio:9000": "online",
                    "minio-4.minio:9000": "online",
                    "minio-5.minio:9000": "offline"
                }
            },
            {
                "state": "ok",
                "endpoint": "minio-1.minio:9000",
                "uptime": 441496,
                "version": "2021-04-15T16:38:02Z",
                "commitID": "1f04e47d11d8d884ea1e23f4d383841f15ee1cb4",
                "network": {
                    "minio-0.minio:9000": "online",
                    "minio-1.minio:9000": "online",
                    "minio-2.minio:9000": "online",
                    "minio-3.minio:9000": "online",
                    "minio-4.minio:9000": "online",
                    "minio-5.minio:9000": "offline"
                }
            },
            {
                "state": "ok",
                "endpoint": "minio-2.minio:9000",
                "uptime": 435256,
                "version": "2021-04-15T16:38:02Z",
                "commitID": "1f04e47d11d8d884ea1e23f4d383841f15ee1cb4",
                "network": {
                    "minio-0.minio:9000": "online",
                    "minio-1.minio:9000": "online",
                    "minio-2.minio:9000": "online",
                    "minio-3.minio:9000": "online",
                    "minio-4.minio:9000": "online",
                    "minio-5.minio:9000": "offline"
                }
            },
            {
                "state": "ok",
                "endpoint": "minio-4.minio:9000",
                "uptime": 435442,
                "version": "2021-04-15T16:38:02Z",
                "commitID": "1f04e47d11d8d884ea1e23f4d383841f15ee1cb4",
                "network": {
                    "minio-0.minio:9000": "online",
                    "minio-1.minio:9000": "online",
                    "minio-2.minio:9000": "online",
                    "minio-3.minio:9000": "online",
                    "minio-4.minio:9000": "online",
                    "minio-5.minio:9000": "offline"
                }
            },
            {
                "state": "offline",
                "endpoint": "minio-5.minio:9000"
            },
            {
                "state": "ok",
                "endpoint": "minio-3.minio:9000",
                "uptime": 431771,
                "version": "2021-04-15T16:38:02Z",
                "commitID": "1f04e47d11d8d884ea1e23f4d383841f15ee1cb4",
                "network": {
                    "minio-0.minio:9000": "online",
                    "minio-1.minio:9000": "online",
                    "minio-2.minio:9000": "online",
                    "minio-3.minio:9000": "online",
                    "minio-4.minio:9000": "online",
                    "minio-5.minio:9000": "offline"
                }
            }
        ]
    }
}
``` 

## Your Environment

* `minio` version is on `RELEASE.2020-11-06T23-17-07Z` (technically we're using a very minor fork), which we've been using in other clusters for at least a few months 
* `mc` version is `RELEASE.2020-08-20T00-23-01Z`

**Comment by harshavardhana** [comment]
> * `minio` version is on `RELEASE.2020-11-06T23-17-07Z` (technically we're using a very minor fork), which we've been using in other clusters for at least a few months

Please upgrade to latest @jinjyoo

**Comment by jinjyoo** [comment]
Hm, I don't think we'd be able to upgrade for a while, but I can bring it up. For an upgrade we'd need to cycle out all the Minio pods anyway, which might help on this issue even if it's for the current older version - I'll check if we can do that.

I'll update if there's a resolution from that, thanks!

**Comment by harshavardhana** [comment]
> Hm, I don't think we'd be able to upgrade for a while, but I can bring it up. For an upgrade we'd need to cycle out all the Minio pods anyway, which might help on this issue even if it's for the current older version - I'll check if we can do that.

Community support is only for newer releases,  let us know if you can see with the latest release.  

If you want to have production support and more deeper engagement you should buy a subscription https://min.io/pricing

Going to close this issue.
