### ISSUE TITLE
Exception: cannot download after uploading the same object name to cover a file smaller than 5M

### ISSUE THREAD

**Issue by BoilingWine** [minio/minio#12774]
I cannot download after uploading the same object name to cover a file smaller than 5M.(< part size)

 when I download the file with sdk or http, returns an error prompt：You did not provide the number of bytes specified by the Content-Length HTTP header   ||  Can't access this website

version：version RELEASE.2021-04-22T15-44-28Z  
sdk-java 8.x

**Comment by harshavardhana** [comment]
> I cannot download after uploading the same object name to cover a file smaller than 5M.(< part size)
> 
> when I download the file with sdk or http, returns an error prompt：You did not provide the number of bytes specified by the Content-Length HTTP header || Can't access this website
> 
> version：version RELEASE.2021-04-22T15-44-28Z
> sdk-java 8.x

Please provide a more detailed example here @BoilingWine 

- we have no idea about your setup - there are no details shared? 
- is it consistently reproducible? 
- what else is different in your setup? 

I just tried locally there is nothing that points me to your issue, also please upgrade to latest to test again.

**Comment by BoilingWine** [comment]
1. three server node, an node with two data node，use nginx as the entrance
2. Always reproduce
3.operation:  there is an file smailler than 5m，than I am uploading an file with the same object name and the size greater than 5m

**Comment by harshavardhana** [comment]
> * three server node, an node with two data node，use nginx as the entrance
> * Always reproduce
>   3.operation:  there is an file smailler than 5m，than I am uploading an file with the same object name and the size greater than 5m

@BoilingWine just upgrade this is already fixed.
