### ISSUE TITLE
Backup from Cloudron over Minio dosent work

### ISSUE THREAD

**Issue by pr0tectors** [minio/minio#12779]
I am using Cloudron and from 2 Apps i got only one can be backed up. This worked in the version around "MAI"
But now i always get HTTP 500 Errors

This was MAI 2021 after talking with the Cloudron Programmer

I am using a SelfSigned Certificate
## Current Behavior

Backup to Minio for 1 APP from Cloudron does not Work

## Possible Solution
Trying to debug the backtrace a bit for fun:
https://github.com/minio/minio/blob/RELEASE.2021-03-26T00-00-41Z/cmd/object-handlers.go#L2272 seems to be last point of error. It seems somewhere in https://github.com/minio/minio/blob/7be71094710b966be624f10eeea25df02660493e/cmd/fs-v1-multipart.go#L369 failed

##TRACE -> mc admin trace --verbose myminio
sub.domain.com:8081 [REQUEST s3.NewMultipartUpload] [2021-07-22T18:35:48:000] [Client IP: 888.888.888.888]
sub.domain.com:8081 POST /bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc?uploads
sub.domain.com:8081 Proto: HTTP/1.1
sub.domain.com:8081 Host: sub.domain.com:8081
sub.domain.com:8081 User-Agent: aws-sdk-nodejs/2.906.0 linux/v14.15.4
sub.domain.com:8081 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
sub.domain.com:8081 X-Amz-Date: 20210722T183548Z
sub.domain.com:8081 Authorization: AWS4-HMAC-SHA256 Credential=USERNAMELOGIN/20210722/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5f7cd65b658392d118792612ea625fab196a6fc4fe6503993bd0dd26552271bb
sub.domain.com:8081 Connection: close
sub.domain.com:8081 Content-Length: 0
sub.domain.com:8081 Content-Type: application/octet-stream
sub.domain.com:8081
sub.domain.com:8081 [RESPONSE] [2021-07-22T18:35:48:000] [ Duration 106.668ms  ↑ 101 B  ↓ 638 B ]
sub.domain.com:8081 200 OK
sub.domain.com:8081 Accept-Ranges: bytes
sub.domain.com:8081 Content-Security-Policy: block-all-mixed-content
sub.domain.com:8081 Vary: OriginAccept-Encoding
sub.domain.com:8081 X-Content-Type-Options: nosniff
sub.domain.com:8081 X-Frame-Options: deny
sub.domain.com:8081 Content-Length: 300
sub.domain.com:8081 Content-Type: application/xml
sub.domain.com:8081 Server: MinIO
sub.domain.com:8081 Strict-Transport-Security: max-age=31536000; includeSubDomains
sub.domain.com:8081 X-Amz-Request-Id: 169430BBBA120DCF
sub.domain.com:8081 X-Xss-Protection: 1; mode=block
sub.domain.com:8081 <?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>naise</Bucket><Key>snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Key><UploadId>307b62bd-3c01-40cc-b910-d3013cdaa57e</UploadId></InitiateMultipartUploadResult>
sub.domain.com:8081
sub.domain.com:8081 [REQUEST s3.PutObjectPart] [2021-07-22T18:35:48:000] [Client IP: 888.888.888.888]
sub.domain.com:8081 PUT /bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc?partNumber=1&uploadId=307b62bd-3c01-40cc-b910-d3013cdaa57e
sub.domain.com:8081 Proto: HTTP/1.1
sub.domain.com:8081 Host: sub.domain.com:8081
sub.domain.com:8081 User-Agent: aws-sdk-nodejs/2.906.0 linux/v14.15.4 callback
sub.domain.com:8081 Connection: close
sub.domain.com:8081 Content-Length: 10485760
sub.domain.com:8081 Content-Type: application/octet-stream
sub.domain.com:8081 X-Amz-Date: 20210722T183548Z
sub.domain.com:8081 Authorization: AWS4-HMAC-SHA256 Credential=USERNAMELOGIN/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=e4d49c9f6c31f683315e2a8e81de693f9e6e33ae76d3363eb6aa8ed57700f454
sub.domain.com:8081 Content-Md5: STxG/TBDVjcI/bKYEzZUDg==
sub.domain.com:8081 Expect: 100-continue
sub.domain.com:8081 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
sub.domain.com:8081 <BODY>
sub.domain.com:8081 [RESPONSE] [2021-07-22T18:35:48:000] [ Duration 1.694ms  ↑ 120 B  ↓ 971 B ]
sub.domain.com:8081 500 Internal Server Error
sub.domain.com:8081 X-Frame-Options: deny
sub.domain.com:8081 X-Xss-Protection: 1; mode=block
sub.domain.com:8081 Content-Length: 614
sub.domain.com:8081 Content-Security-Policy: block-all-mixed-content
sub.domain.com:8081 Content-Type: application/xml
sub.domain.com:8081 Strict-Transport-Security: max-age=31536000; includeSubDomains
sub.domain.com:8081 Vary: OriginAccept-Encoding
sub.domain.com:8081 X-Content-Type-Options: nosniff
sub.domain.com:8081 Accept-Ranges: bytes
sub.domain.com:8081 Server: MinIO
sub.domain.com:8081 X-Amz-Request-Id: 169430BBCBFF9252
sub.domain.com:8081 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(open /home/pi/data/.minio.sys/multipart/b91e0d981c97d3d2742f52ca542beb053b032cc0ece4b7ac55fcd19d233cb4cf/307b62bd-3c01-40cc-b910-d3013cdaa57e/fs.json: operation not permitted)</Message><Key>snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Key><BucketName>naise</BucketName><Resource>/bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Resource><RequestId>169430BBCBFF9252</RequestId><HostId>d5aab97f-1878-40a6-a688-edf3b50b4960</HostId></Error>
sub.domain.com:8081
sub.domain.com:8081 [REQUEST s3.PutObjectPart] [2021-07-22T18:35:51:000] [Client IP: 888.888.888.888]
sub.domain.com:8081 PUT /bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc?partNumber=2&uploadId=307b62bd-3c01-40cc-b910-d3013cdaa57e
sub.domain.com:8081 Proto: HTTP/1.1
sub.domain.com:8081 Host: sub.domain.com:8081
sub.domain.com:8081 Authorization: AWS4-HMAC-SHA256 Credential=USERNAMELOGIN/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=c65d52e7aa8a4990bfdc1ef5da9ac366147535869c0c171cadd038967ffcfe40
sub.domain.com:8081 Connection: close
sub.domain.com:8081 Content-Length: 10485760
sub.domain.com:8081 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
sub.domain.com:8081 X-Amz-Date: 20210722T183551Z
sub.domain.com:8081 Content-Md5: i87wkESD8ul0BZqagIR6kg==
sub.domain.com:8081 Content-Type: application/octet-stream
sub.domain.com:8081 Expect: 100-continue
sub.domain.com:8081 User-Agent: aws-sdk-nodejs/2.906.0 linux/v14.15.4 callback
sub.domain.com:8081 <BODY>
sub.domain.com:8081 [RESPONSE] [2021-07-22T18:35:51:000] [ Duration 5.056ms  ↑ 120 B  ↓ 971 B ]
sub.domain.com:8081 500 Internal Server Error
sub.domain.com:8081 Vary: OriginAccept-Encoding
sub.domain.com:8081 X-Amz-Request-Id: 169430BC684ED5AF
sub.domain.com:8081 X-Content-Type-Options: nosniff
sub.domain.com:8081 X-Xss-Protection: 1; mode=block
sub.domain.com:8081 Content-Length: 614
sub.domain.com:8081 Content-Type: application/xml
sub.domain.com:8081 Server: MinIO
sub.domain.com:8081 Strict-Transport-Security: max-age=31536000; includeSubDomains
sub.domain.com:8081 Accept-Ranges: bytes
sub.domain.com:8081 Content-Security-Policy: block-all-mixed-content
sub.domain.com:8081 X-Frame-Options: deny
sub.domain.com:8081 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(open /home/pi/data/.minio.sys/multipart/b91e0d981c97d3d2742f52ca542beb053b032cc0ece4b7ac55fcd19d233cb4cf/307b62bd-3c01-40cc-b910-d3013cdaa57e/fs.json: operation not permitted)</Message><Key>snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Key><BucketName>naise</BucketName><Resource>/bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Resource><RequestId>169430BC684ED5AF</RequestId><HostId>d5aab97f-1878-40a6-a688-edf3b50b4960</HostId></Error>
sub.domain.com:8081
sub.domain.com:8081 [REQUEST s3.PutObjectPart] [2021-07-22T18:35:53:000] [Client IP: 888.888.888.888]
sub.domain.com:8081 PUT /bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc?partNumber=3&uploadId=307b62bd-3c01-40cc-b910-d3013cdaa57e
sub.domain.com:8081 Proto: HTTP/1.1
sub.domain.com:8081 Host: sub.domain.com:8081
sub.domain.com:8081 Content-Length: 10485760
sub.domain.com:8081 Content-Md5: XE5r4e8Fyucn6FmvAipM0g==
sub.domain.com:8081 User-Agent: aws-sdk-nodejs/2.906.0 linux/v14.15.4 callback
sub.domain.com:8081 X-Amz-Date: 20210722T183553Z
sub.domain.com:8081 Authorization: AWS4-HMAC-SHA256 Credential=USERNAMELOGIN/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=c6450e83bd8072b64598295a7f09a0bca31c779758b41d8d236208f2bbf049ff
sub.domain.com:8081 Connection: close
sub.domain.com:8081 Content-Type: application/octet-stream
sub.domain.com:8081 Expect: 100-continue
sub.domain.com:8081 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
sub.domain.com:8081 <BODY>
sub.domain.com:8081 [RESPONSE] [2021-07-22T18:35:53:000] [ Duration 4.564ms  ↑ 120 B  ↓ 971 B ]
sub.domain.com:8081 500 Internal Server Error
sub.domain.com:8081 X-Xss-Protection: 1; mode=block
sub.domain.com:8081 Accept-Ranges: bytes
sub.domain.com:8081 Content-Length: 614
sub.domain.com:8081 Content-Security-Policy: block-all-mixed-content
sub.domain.com:8081 Server: MinIO
sub.domain.com:8081 Vary: OriginAccept-Encoding
sub.domain.com:8081 X-Frame-Options: deny
sub.domain.com:8081 Content-Type: application/xml
sub.domain.com:8081 Strict-Transport-Security: max-age=31536000; includeSubDomains
sub.domain.com:8081 X-Amz-Request-Id: 169430BD0B859F82
sub.domain.com:8081 X-Content-Type-Options: nosniff
sub.domain.com:8081 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(open /home/pi/data/.minio.sys/multipart/b91e0d981c97d3d2742f52ca542beb053b032cc0ece4b7ac55fcd19d233cb4cf/307b62bd-3c01-40cc-b910-d3013cdaa57e/fs.json: operation not permitted)</Message><Key>snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Key><BucketName>naise</BucketName><Resource>/bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Resource><RequestId>169430BD0B859F82</RequestId><HostId>d5aab97f-1878-40a6-a688-edf3b50b4960</HostId></Error>
sub.domain.com:8081
sub.domain.com:8081 [REQUEST s3.PutObjectPart] [2021-07-22T18:36:08:000] [Client IP: 888.888.888.888]
sub.domain.com:8081 PUT /bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc?partNumber=1&uploadId=307b62bd-3c01-40cc-b910-d3013cdaa57e
sub.domain.com:8081 Proto: HTTP/1.1
sub.domain.com:8081 Host: sub.domain.com:8081
sub.domain.com:8081 Connection: close
sub.domain.com:8081 Content-Length: 10485760
sub.domain.com:8081 Content-Md5: STxG/TBDVjcI/bKYEzZUDg==
sub.domain.com:8081 Content-Type: application/octet-stream
sub.domain.com:8081 Expect: 100-continue
sub.domain.com:8081 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
sub.domain.com:8081 Authorization: AWS4-HMAC-SHA256 Credential=USERNAMELOGIN/20210722/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=57224ae7576d3d8fef847c2a501b1bcbe5dd822bf601451f79f159158ab370ab
sub.domain.com:8081 X-Amz-Date: 20210722T183608Z
sub.domain.com:8081 User-Agent: aws-sdk-nodejs/2.906.0 linux/v14.15.4 callback
sub.domain.com:8081 <BODY>
sub.domain.com:8081 [RESPONSE] [2021-07-22T18:36:08:000] [ Duration 4.233ms  ↑ 120 B  ↓ 971 B ]
sub.domain.com:8081 500 Internal Server Error
sub.domain.com:8081 X-Xss-Protection: 1; mode=block
sub.domain.com:8081 Accept-Ranges: bytes
sub.domain.com:8081 Content-Length: 614
sub.domain.com:8081 Server: MinIO
sub.domain.com:8081 Vary: OriginAccept-Encoding
sub.domain.com:8081 X-Content-Type-Options: nosniff
sub.domain.com:8081 X-Frame-Options: deny
sub.domain.com:8081 Content-Security-Policy: block-all-mixed-content
sub.domain.com:8081 Content-Type: application/xml
sub.domain.com:8081 Strict-Transport-Security: max-age=31536000; includeSubDomains
sub.domain.com:8081 X-Amz-Request-Id: 169430C07DAC8910
sub.domain.com:8081 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(open /home/pi/data/.minio.sys/multipart/b91e0d981c97d3d2742f52ca542beb053b032cc0ece4b7ac55fcd19d233cb4cf/307b62bd-3c01-40cc-b910-d3013cdaa57e/fs.json: operation not permitted)</Message><Key>snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Key><BucketName>naise</BucketName><Resource>/bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc</Resource><RequestId>169430C07DAC8910</RequestId><HostId>d5aab97f-1878-40a6-a688-edf3b50b4960</HostId></Error>
sub.domain.com:8081

## Context
Well i cant take an Backup of 1APP, witch worked before

## Regression
I can reproduce this issues always

minio version RELEASE.2021-07-22T05-23-32Z
My starter:
export MINIO_ROOT_USER=
export MINIO_ROOT_PASSWORD=
export MINIO_DOMAIN=sub.domain.com
export MINIO_DISK_USAGE_CRAWL=off

minio server --address ":8081" --console-address ":443" --certs-dir /home/pi/.minio/certs/CAs/ ~/data

Linux hole 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

**Comment by harshavardhana** [comment]
> `InternalError`We encountered an internal error, please try again.: cause(open /home/pi/data/.minio.sys/multipart/b91e0d981c97d3d2742f52ca542beb053b032cc0ece4b7ac55fcd19d233cb4cf/307b62bd-3c01-40cc-b910-d3013cdaa57e/fs.json: operation not permitted)snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.encnaise/bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc169430BC684ED5AFd5aab97f-1878-40a6-a688-edf3b50b4960
> sub.domain.com:8081

Issue seems to be that your disk is dying and returning errors.

**Comment by pr0tectors** [comment]
> 
> 
> > `InternalError`We encountered an internal error, please try again.: cause(open /home/pi/data/.minio.sys/multipart/b91e0d981c97d3d2742f52ca542beb053b032cc0ece4b7ac55fcd19d233cb4cf/307b62bd-3c01-40cc-b910-d3013cdaa57e/fs.json: operation not permitted)snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.encnaise/bucket/snapshot/app_5b67e84d-40da-4604-80ec-45e8d610c839.tar.gz.enc169430BC684ED5AFd5aab97f-1878-40a6-a688-edf3b50b4960
> > sub.domain.com:8081
> 
> Issue seems to be that your disk is dying and returning errors.

Well testet the External Disk on another Storage and PC works fine. But if it is the Disk why i can backup something else on minio?

**Comment by harshavardhana** [comment]
> Well testet the External Disk on another Storage and PC works fine. But if it is the Disk why i can backup something else on minio?

The error is indicative of a problem in the disk, there is nothing more MinIO can do here.

**Comment by pr0tectors** [comment]
So you tell me its the Harddrive where i can copy without issues everything on it? and Backup also other datas from other apps? Makes no sense but well lets se what happens if i change the Disk.

**Comment by harshavardhana** [comment]
> So you tell me its the Harddrive where i can copy without issues everything on it? and Backup also other datas from other apps? Makes no sense but well lets se what happens if i change the Disk.

what is the filesystem being used underneath? does it have LUKS etc?

**Comment by pr0tectors** [comment]
/dev/sda1       on  /home/pi/data                    type  fuseblk     (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
no LUKS

**Comment by harshavardhana** [comment]
> /dev/sda1 on /home/pi/data type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
> no LUKS

Ah, you are using FUSE? it won't work with MinIO we need to have `fnctl` locking support on the filesystem and I am 100% sure most filesystems based on FUSE do not implement this properly. Other than GlusterFS.  

If you are going to go out of your way to use random filesystems it won't work, that's why stick to what we recommend using "XFS" 

> For the best experience we recommend that you use distributions that ship fairly recent Linux kernel such as CentOS 8, Ubuntu 18.04 LTS along with XFS as the choice for your backend filesystem.

Closing this issue as out of scope..
