### ISSUE TITLE
Copying a file onto itself does not rewrite LastModified

### ISSUE THREAD

**Issue by adamhooper** [minio/minio#12777]
If I use `CopyObject` with source=destination and metadata-directive=REPLACE, the timestamp of the file should update.

## Expected Behavior

On S3:

```
$ touch x
$ aws s3 cp x s3://my-bucket/x
$ aws s3 ls s3://my-bucket/
2021-07-22 10:45:52          0 x
$ aws s3 cp s3://my-bucket/x s3://my-bucket/x --metadata-directive=REPLACE
copy: s3://my-bucket/x to s3://my-bucket/x
$ aws s3 ls s3://my-bucket/
2021-07-22 10:47:36          0 x
```

## Current Behavior

Currently, the LastModified of `x` won't change when I replace it with itself.

```
$ AWS_ACCESS_KEY_ID=minio_access AWS_SECRET_ACCESS_KEY=minio_secret aws --endpoint-url http://172.19.0.4:9000 s3 ls my-bucket
2021-07-22 10:45:52          0 x
```

## Context

I'm trying to mark objects for deletion at a specific date using lifecycle rules and tags. So I add a tag and overwrite the object, implying: "delete at least 24 hours from now -- now being the expiration date." If minio doesn't update LastModified, the lifecycle rule can delete the object earlier than I want.

Workaround: with minio I can copy `x` to a new file, copy the new file back to `x` and then delete the new file. Ouch.

## Your Environment

* Version used (`minio version RELEASE.2021-07-08T01-15-01Z`):
* Server setup and configuration: Docker `minio server /data`
* Operating System and version (`uname -a`): `Linux ares 5.12.15-300.fc34.x86_64 #1 SMP Wed Jul 7 9:46:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@adamhooper AFAIK CopyObject does not change modTime in AWS S3

**Comment by adamhooper** [comment]
@harshavardhana Perhaps this has changed? I copy/pasted my session log and only changed the bucket name.

**Comment by harshavardhana** [comment]
> @harshavardhana Perhaps this has changed? I copy/pasted my session log and only changed the bucket name.

Okay will fix it.
