### ISSUE TITLE
Clean dirty physical file in disk which minio doesn't used anymore.

### ISSUE THREAD

**Issue by loyalPlayer** [minio/minio#12784]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
minio cluster of 4 instance. one of them (Let's say it's instance-3) was out of service ever, but it has been recovered now. 
the file file1 was removed in minio cluster when instance-3 was out of service.
physical file of file1 in data disk should also be cleaned in instance-3 after instance-3 was recovered.

**Describe alternatives you've considered**
Provide a cleanup interface such as mc clean or other methods

**Additional context**
None

**Comment by harshavardhana** [comment]
> minio cluster of 4 instance. one of them (Let's say it's instance-3) was out of service ever, but it has been recovered now.
> the file file1 was removed in minio cluster when instance-3 was out of service.
> physical file of file1 in data disk should also be cleaned in instance-3 after instance-3 was recovered.

This cleans up either 

```
~ mc admin heal -r --remove alias/
```

We also run auto-healing on a regular basis

**Comment by loyalPlayer** [comment]
> > minio cluster of 4 instance. one of them (Let's say it's instance-3) was out of service ever, but it has been recovered now.
> > the file file1 was removed in minio cluster when instance-3 was out of service.
> > physical file of file1 in data disk should also be cleaned in instance-3 after instance-3 was recovered.
> 
> This cleans up either
> 
> ```
> ~ mc admin heal -r --remove alias/
> ```
> 
> We also run auto-healing on a regular basis

Thanks a lot! I should spend more time to research by myself, sorry to disturb by this problem of low quality...
