### ISSUE TITLE
Minio memory consumption keeps increasing.

### ISSUE THREAD

**Issue by smanglapanw** [minio/minio#12798]
I am performing a write load test on minio.  Minio version:- minio/minio:RELEASE.2021-07-15T22-27-34Z

1) trying with file size of 400 KB file to be written in memory 
2) using the locust tool for load testing. 
3) Minio memory consumption keeps increasing even on very small rps e.g. 7 or 8
4) Ran the load test for 1 hour. 
memory usage of minio reached from 125 MB to 3.5 GB 
5) start with a fresh minio servers. minio servers configuration is 
number of servers:- 4
cpu:- 3 cores
memory :- 6 GB 
6) request is not getting failed .. but only issue is memory doesn't release even load test is stopped. 

I want to understand how the minio use the memory. Does it need a very huge memory size. 

from previous issues I found that 
```Note: MinIO allocates 10MiB per read and writes on a bufPool . This memory is reused so for example if you have 1000 concurrent connections you will see 10G memory usage.
MinIO erasure coding uses 10MiB buffer per stream so if you are uploaded 1000 concurrent streams it will use 1000 * 10 = 10GiB memory. Now, this memory is not given back to GC because MinIO reuses same 10GiB for the next 1000 concurrent operations. So if your concurrent operations increase the memory is always allocated and reused again and again.
you will always know that there is a top-level limit based on the client's concurrent requirement. If you can show that just uploading a single stream leaks memory then it makes sense, but without that I don't think what you are seeing is unusual.


```

But I am not seeing any of these behaviors .. 
Can someone help in understanding what should I expect in case of memory usage? Minio is critical component of my system, so much memory swallowing is something not acceptable.

**Comment by smanglapanw** [comment]
@harshavardhana , attached the profile dump , which I took during running of the same test. 
[Uploading profile.zip…]()

**Comment by puneettrehan** [comment]
@harshavardhana I work with @smanglapanw. Can you please help answering some questions?
1. We are looking to support 400 rps read, 400 rps write simultaneously on our cluster. 
2. Avg data we are reading and writing if 1MB per request.
3. We are facing 2 issues. On Write tests as @smanglapanw  mentioned we are seeing memory keep growing even when concurrent writes are ~8.
4. Another issue we are facing is that reads at 400 rps starts failing. Approx 33% reads are failing with exception
No such file or directory: 'read_1Mb.txt.b6d81b360a5672d80c27430f39153e2c.part.minio' -> 'read_1Mb.txt'
We are using python client library.

our configuration is 
number of servers:- 4
cpu:- 3 cores
memory :- 6 GB

Also if you can suggest node configuration based on traffic we want to support for minio.

**Comment by smanglapanw** [comment]
[
[Uploading profile.zip…]()
](url)

**Comment by harshavardhana** [comment]
> @harshavardhana , attached the profile dump , which I took during running of the same test.
> Uploading profile.zip…

Doesn't seem like profile was uploaded.

**Comment by harshavardhana** [comment]
> @harshavardhana I work with @smanglapanw. Can you please help answering some questions?
> 
> 1. We are looking to support 400 rps read, 400 rps write simultaneously on our cluster.
> 2. Avg data we are reading and writing if 1MB per request.
> 3. We are facing 2 issues. On Write tests as @smanglapanw  mentioned we are seeing memory keep growing even when concurrent writes are ~8.
> 4. Another issue we are facing is that reads at 400 rps starts failing. Approx 33% reads are failing with exception
>    No such file or directory: 'read_1Mb.txt.b6d81b360a5672d80c27430f39153e2c.part.minio' -> 'read_1Mb.txt'
>    We are using python client library.
> 
> our configuration is
> number of servers:- 4
> cpu:- 3 cores
> memory :- 6 GB
> 
> Also if you can suggest node configuration based on traffic we want to support for minio.

is the python client running on the same server as MinIO?

**Comment by smanglapanw** [comment]
@harshavardhana ,  no, we are sending the request through locust. Though locust and minio are in same namespace.

**Comment by smanglapanw** [comment]
[Uploading profile.zip…]()

**Comment by harshavardhana** [comment]
> Uploading profile.zip…

Still not there try putting the profile to `mc cp profile.zip play/testbucket/profile-github12798.zip`

**Comment by smanglapanw** [comment]
@harshavardhana , copied the profile.zip to above mentioned bucket.

**Comment by harshavardhana** [comment]
> I am performing a write load test on minio. Minio version:- minio/minio:RELEASE.2021-07-15T22-27-34Z

Looks like from the profile you are using an older version of MinIO 

>      576MB  1.73% 66.74%      576MB  1.73%  github.com/minio/minio/pkg/argon2.NewIDKey.func1

We do not have this package anymore in our repo anywhere and it's only used by `madmin-go` API for only specific requests so will show up only in `mc` not on the server.

There are also listing operations that seem to be spending time in allocation here, perhaps your application is doing a lot of listing operations? 

> 7767.37MB 23.38% 23.38%  7767.37MB 23.38%  github.com/klauspost/compress/s2.NewReader

Active in-use objects are only this much

```
File: minio
Type: inuse_space
Time: Jul 26, 2021 at 12:24pm (PDT)
Showing nodes accounting for 47713.99kB, 96.35% of 49523.24kB total
Dropped 474 nodes (cum <= 247.62kB)
Dropped 19 edges (freq <= 49.52kB
```

So whatever you are seeing is just part of the `alloc_space` basically now part of the GC to pick it up and clean it.  This happens automatically inside Go runtime and you do not have to worry about it. 

So whatever it is doesn't look abnormal or anything - just that we need to see why are there so many listing calls when all you are doing is PUT / GET operations.

Nevertheless, you are also not running the latest version of MinIO instead you are on an older release - the profile clearly shows that you are using binaries that seem to be using some old code that was removed couple of months ago.

**Comment by puneettrehan** [comment]
@harshavardhana we are using this image version minio/minio:RELEASE.2021-07-15T22-27-34Z.

Does it has to do anything with client sdk?
Our minio image seems fairly new.

**Comment by harshavardhana** [comment]
> @harshavardhana we are using this image version minio/minio:RELEASE.2021-07-15T22-27-34Z.
> 
> Does it has to do anything with client sdk?
> Our minio image seems fairly new.

100% guaranteed that you are not running latest from the profile output. My suggestion tear down the setup and freshly deploy and test again..

**Comment by puneettrehan** [comment]
@harshavardhana You were right. Our image was older on this cluster. We were using.minio/minio:RELEASE.2021-03-10T05-11-33Z

Can you please suggest that what could be reason for read failure at high RPS?
At 400 rps starts failing. Approx 33% reads are failing with exception
No such file or directory: 'read_1Mb.txt.b6d81b360a5672d80c27430f39153e2c.part.minio' -> 'read_1Mb.txt'
We are using python client library.

**Comment by harshavardhana** [comment]
> @harshavardhana You were right. Our image was older on this cluster. We were using.minio/minio:RELEASE.2021-03-10T05-11-33Z
> 

Please upgrade.

> Can you please suggest that what could be reason for read failure at high RPS?
> At 400 rps starts failing. Approx 33% reads are failing with exception
> No such file or directory: 'read_1Mb.txt.b6d81b360a5672d80c27430f39153e2c.part.minio' -> 'read_1Mb.txt'
> We are using python client library.

This is client side failure something to do with minio-py can you share the code ?

**Comment by harshavardhana** [comment]
> Can you please suggest that what could be reason for read failure at high RPS?
> At 400 rps starts failing. Approx 33% reads are failing with exception
> No such file or directory: 'read_1Mb.txt.b6d81b360a5672d80c27430f39153e2c.part.minio' -> 'read_1Mb.txt'
> We are using python client library.

Please open a new issue, I don't think there is an issue here related to memory at the moment please upgrade and test. Closing this issue.

**Comment by puneettrehan** [comment]
@harshavardhana this is the script.  We are using minio client document.

[Uploading locustfile.py_read.zip…]()
[Uploading locustfile.py_read.zip…]()

**Comment by harshavardhana** [comment]
Again your uploads are not working - I can't access the code @puneettrehan please upload it to `play/` and tell us where it.

**Comment by puneettrehan** [comment]
@harshavardhana this is the script.  We are using minio client document.

@harshavardhana uploaded to play/testbucket/read-github12798.zip

**Comment by harshavardhana** [comment]
```
        #Read get file from bucket
        try:
           start_time = time.time()
           self.client.fget_object(
                "loadtest", "read_1Mb.txt", "read_1Mb.txt" ,
            )
        except (SystemExit, KeyboardInterrupt):
            raise
        except:
            total_time = int((time.time() - start_time) * 1000)
            events.request_failure.fire(
                request_type=DOWNLOAD, name="fget_object", response_time=total_time, response_length=0,
                exception=DOWNLOAD_FAIL)
            logging.exception(DOWNLOAD_FAIL)
        else:
            total_time = int((time.time() - start_time) * 1000)
            events.request_success.fire(
                request_type=DOWNLOAD, name="fget_object", response_time=total_time, response_length=0)

```
You seem to be reading the same file again and again what is the purpose of this script? - of course, this can race because there is no locking involved from your end locally. 

`fget_object()` tries to download as `.part` file and renames this part file, it can fail since the object is same and the Etag will be same concurrent operations can run over each other. 

This looks like an implementation issue on your end.
