### ISSUE TITLE
minio gateway nas mode - bucket events to webhook target does not work.

### ISSUE THREAD

**Issue by lsraj** [minio/minio#12807]
I have started minio (July 22 release) in gateway nas mode with etcd as below.

```
[root@raj-440 ]# export MINIO_ACCESS_KEY=minio
[root@raj-440 ]# export MINIO_SECRET_KEY=minioSecret
[root@raj-440 ]# export MINIO_ETCD_ENDPOINTS=http://127.0.0.1:2379
[root@raj-440 ]# 
[root@raj-440 ]# 
[root@raj-440 ]# minio -v
minio version RELEASE.2021-07-22T05-23-32Z
[root@raj-440 ]# 
[root@raj-440 ]# mc -v
mc version RELEASE.2021-06-13T17-48-22Z
[root@raj-440 ]# 
[root@raj-440 ]# ./minio gateway nas --address 172.22.12.61:9003 /mnt/nfs_export3

[root@raj-440 ]# mc -v
mc version RELEASE.2021-06-13T17-48-22Z
[root@raj-440 ]# 
[root@raj-440]# ./mc admin config get wh notify_webhook
mc: <ERROR> Unable to get server '[notify_webhook]' config. This 'admin' API is not supported by server in 'mode-gateway-nas'.
[root@raj-440]# 

```

I dont see any issue in server mode.

**Comment by lsraj** [comment]
At minio documentation page - https://docs.min.io/docs/minio-bucket-notification-guide.html, I see this note:

NOTE: Gateway mode does not support bucket notifications (except NAS gateway).

Since I am starting in gateway nas, I am assuming it should work.

**Comment by harshavardhana** [comment]
You can't do it like this 

```
[root@raj-440 ]#
[root@raj-440]# ./mc admin config get wh notify_webhook
mc: Unable to get server '[notify_webhook]' config. This 'admin' API is not supported by server in 'mode-gateway-nas'.
```

You need to use environment values

**Comment by lsraj** [comment]
Here is what I have done (followed along https://github.com/minio/thumbnailer). 

```
[root@raj-440 thumbnailer]# cat config/webhook.json 
{
  "config": {
    "endPoint": "172.22.12.61",
    "port": 9003,
    "secure": false,
    "accessKey": "minio",
    "secretKey": "minioSecret",
    "bucket": "images",
    "destBucket": "images-processed",
    "prefix": "",
    "suffix": ".jpg",
    "events": [
      "s3:ObjectCreated:*"
    ]
  }
}


[root@raj-440 thumbnailer]# 
[root@raj-440 thumbnailer]# NODE_ENV=webhook node thumbnail-webhook.js

Webhook listening on all interfaces at port 3000!
Please update minio server config as explained in `https://docs.min.io/docs/minio-server-configuration-guide.html` to enable webhook notification target.
{
	"webhook": {
		"1": {
			"enable": true,
			"endpoint": "http://localhost:3000"
		}
	}
}
Once server config is updated, please restart your minio server.

Now we proceed to use "mc" to enable receiving events over webhook.

   $ mc mb myminio/images
   $ mc mb myminio/images-processed
   $ mc event add myminio/images arn:minio:sqs:us-east-1:1:webhook --event put --suffix .jpg
```

Then attempted to config webhook endpoint to minio as below:
```
[root@raj-440 newMinio]# ./mc admin config set wh notify_webhook:1 queue_limit="0"  endpoint="http://localhost:3000" queue_dir=""
mc: <ERROR> Unable to set 'notify_webhook:1 queue_limit=0 endpoint=http://localhost:3000 queue_dir=' to server. This 'admin' API is not supported by server in 'mode-gateway-nas'.
[root@raj-440 newMinio]# 
```
BTW, I was able to setup webhook for minio server mode OK.

**Comment by lsraj** [comment]
I made another attempt by setting env vars. etcd endpoint up. webhook endpoint up. Unfortunately this continue to fail.

```
[root@raj-440 newMinio]# export MINIO_ACCESS_KEY=minio
[root@raj-440 newMinio]# export MINIO_SECRET_KEY=minioSecret
[root@raj-440 newMinio]# export MINIO_ETCD_ENDPOINTS=http://127.0.0.1:2379
[root@raj-440 newMinio]# 
[root@raj-440 newMinio]# export MINIO_NOTIFY_WEBHOOK_ENABLE=on
[root@raj-440 newMinio]# export MINIO_NOTIFY_WEBHOOK_ENDPOINT="http://localhost:3000"
[root@raj-440 newMinio]# 
[root@raj-440 newMinio]# ./minio gateway nas --address 172.22.12.61:9003 /mnt/nfs_export3
....
....
API: http://172.22.12.61:9003 
RootUser: minio 
RootPass: minioSecret 
SQS ARNs: arn:minio:sqs::_:webhook 
....
....



[root@raj-440 newMinio]# ./mc admin config get wh notify_webhook
mc: <ERROR> Unable to get server '[notify_webhook]' config. This 'admin' API is not supported by server in 'mode-gateway-nas'.
[root@raj-440 newMinio]#
```

**Comment by harshavardhana** [comment]
> [root@raj-440 newMinio]# ./mc admin config get wh notify_webhook
> mc: <ERROR> Unable to get server '[notify_webhook]' config. This 'admin' API is not supported by server in 'mode-gateway-nas'.
> [root@raj-440 newMinio]#

This will not work @lsraj in gateway you need to just use env variables and `mc event add` to enable the notifications that's all.

**Comment by harshavardhana** [comment]
> [root@raj-440 newMinio]# ./minio gateway nas --address 172.22.12.61:9003 /mnt/nfs_export3
> ....
> ....
> API: http://172.22.12.61:9003 
> RootUser: minio 
> RootPass: minioSecret 
> SQS ARNs: arn:minio:sqs::_:webhook 
> ....
> ....

As you can see its already configured you just need to use it on the buckets

> mc event add myminio/images arn:minio:sqs::_:webhook --event put --suffix .jpg

**Comment by lsraj** [comment]
> As you can see its already configured you just need to use it on the buckets
> 
> > mc event add myminio/images arn:minio:sqs::_:webhook --event put --suffix .jpg

This worked. Thanks @harshavardhana. Few things to notice and consideration for fixing.
`minio in server mode` does not necessarily need setting `MINIO_NOTIFY_WEBHOOK_ENABLE` and `MINIO_NOTIFY_WEBHOOK_ENDPOINT` env before starting the server - client `mc` does that magic. The advantage of this approach - no additional changes to running server. Where as `minio gateway nas` shall need these variables since client `mc` not able to set webhook endpoint. Why is this behavior different? is it possible to fix this?

I noticed and tested successfully - etcd is not required for minio gateway nas and webhook target. Could you confirm?

**Comment by harshavardhana** [comment]
> I noticed and tested successfully - etcd is not required for minio gateway nas and webhook target. Could you confirm?

Yes it is not required - etcd is needed for IAM i.e if you want STS, Multi-users, LDAP support

**Comment by harshavardhana** [comment]
> This worked. Thanks @harshavardhana. Few things to notice and consideration for fixing.
> `minio in server mode` does not necessarily need setting `MINIO_NOTIFY_WEBHOOK_ENABLE` and `MINIO_NOTIFY_WEBHOOK_ENDPOINT` env before starting the server - client `mc` does that magic. The advantage of this approach - no additional changes to running server. Where as `minio gateway nas` shall need these variables since client `mc` not able to set webhook endpoint. Why is this behavior different? is it possible to fix this?

It is different because it's NAS gateway and we really don't want to encourage usage of the NAS gateway usage in perpetuity. If you have a legacy requirement fine, use it.  But don't expect everything to work with NAS gateway.
