### ISSUE TITLE
Login with SSO: Client secret not provided in request

### ISSUE THREAD

**Issue by mieseprem** [minio/minio#12819]
We try to upgrade our MinIO version from RELEASE.2021-06-17T00-10-46Z. We face two issues with ALL versions after RELEASE.2021-06-17T00-10-46Z. We are aware of the breaking change regarding the embedded console service.

Our upgrade steps included:
* added "--console-address ':9002'" to ...minio server... command line in entry point script
* added MINIO_BROWSER_REDIRECT_URL and MINIO_SERVER_URL environment vars to deployment (further non-changed env vars: MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_IDENTITY_OPENID_CONFIG_URL, MINIO_IDENTITY_OPENID_CLIENT_ID, MINIO_IDENTITY_OPENID_CLAIM_NAME)

## Expected Behavior
As like in version RELEASE.2021-06-17T00-10-46Z I can choose between login with MINIO_ROOT credentials or login with OpenID.

## Current Behavior
* there is no option to login as local user if MINIO_IDENTITY env vars are present:
![grafik](https://user-images.githubusercontent.com/50367822/127344462-1fac9e5b-4718-400f-9d7a-fc4ba894ca81.png)

* using "Login with SSO" doesn't work anymore. In minio service the following error message appears:
> original error -> (user_login.go:62: invalid Login)
> debugging error: oauth2: cannot fetch token: 401 Unauthorized
> Response: {"error":"unauthorized_client","error_description":"Client secret not provided in request"}

I tried with all theese releases:
RELEASE.2021-07-27T02-40-15Z (current latest)
RELEASE.2021-07-22T05-23-32Z (x)
RELEASE.2021-07-21T22-15-23Z
RELEASE.2021-07-15T22-27-34Z
RELEASE.2021-07-12T02-44-53Z (y)
RELEASE.2021-07-08T19-43-25Z (y)
RELEASE.2021-07-08T01-15-01Z (y)

With none of them I was able to connect to MinIO. I found special behaviour with (x) as this doesn't even show Console in Browser and with (y) that wasn't able to connect to OpenID provider (using wrong address)
However, the main issue is that with latest RELEASE OpenID authorization seems to be broken at all.

## Possible Solution
I'm not sure if there was a notable change in how to configure MINIO_IDENTITY_OPENID. I think not as I can't find any new recommendations at [Configure MinIO for Authentication using OpenID](https://docs.min.io/minio/baremetal/security/openid-external-identity-management/configure-openid-external-identity-management.html#set-the-openid-configuration-settings)

## Steps to Reproduce (for bugs)
Build and run Docker image locally
1. [Dockerfile.txt](https://github.com/minio/minio/files/6894150/Dockerfile.txt)
2. [docker-entrypoint.sh.txt](https://github.com/minio/minio/files/6894168/docker-entrypoint.sh.txt)
3. docker build -t minio/minio:LOCAL.latest .
4. docker run --rm -d --name minio-latest -p 9000:9000 -p 9002:9002 -e MINIO_ROOT_USER=minio -e  MINIO_ROOT_PASSWORD=minio123 -e MINIO_BROWSER_REDIRECT_URL=http://localhost:9002 -e MINIO_SERVER_URL=http://localhost:9000 -e MINIO_IDENTITY_OPENID_CONFIG_URL=https://keycloak.url/.well-known/openid-configuration -e MINIO_IDENTITY_OPENID_CLIENT_ID=minioClient -e MINIO_IDENTITY_OPENID_CLAIM_NAME=policyMinio minio/minio:LOCAL.latest

## Context
-

## Regression
I don't know

## Your Environment
Should all be clear due to information above

**Comment by mieseprem** [comment]
I am aware of #12816 but it doesn't seem related to this issue for me. That's why I opened a new issue.

**Comment by harshavardhana** [comment]
> * added "--console-address ':9002'" to ...minio server... command line in entry point script
> * added MINIO_BROWSER_REDIRECT_URL and MINIO_SERVER_URL environment vars to deployment (further non-changed env vars: MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_IDENTITY_OPENID_CONFIG_URL, MINIO_IDENTITY_OPENID_CLIENT_ID, MINIO_IDENTITY_OPENID_CLAIM_NAME)

We do not support Implicit Flow anymore please provide, we only support AuthorizationFlow.

```
MINIO_IDENTITY_OPENID_CLIENT_SECRET
```
