### ISSUE TITLE
Client disconnected before response was ready

### ISSUE THREAD

**Issue by evt-byte** [minio/minio#12829]
When transferring a file, deleting a pod in a distributed deployment cluster will cause the transfer to fail with the error message:Client disconnected before response was ready.

## Expected Behavior

A 4-pod distributed deployment with the deletion of a pod should not affect the transfer of files.

## Current Behavior

The transmission was interrupted when the pod was deleted.

## Steps to Reproduce (for bugs)

1.Confirm cluster status is OK.
2.Prepare to upload files using MC and add the parameter --debug.
3.Deleting a pod in a cluster to automatically revive it (k8s).
4.The file transfer failed with a file size of 5G~10G.

## Context

More than half of the pods working should not affect the transmission quality.

## Your Environment

* Version used (`minio --version`):minio-RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration:4pod in k8s
* Operating System and version (`uname -a`):Linux-suse

**Comment by evt-byte** [comment]
Here is the mc --debug log.
[mc--debug.log](https://github.com/minio/minio/files/6904587/mc--debug.log)

**Comment by evt-byte** [comment]
When the pod is deleted, the following log message appears on the server：
1.Disk: /export  -\u003e .minio.sys/buckets/core5/.usage-cache.bin/42862fdd-7f5d-4397-96e1-3582410ab927/part.1 - content hash does not match - expected 0ec524320ce14ef9242fbd89938e14751c95645471386ea95668d860c3054c4a, got 3924bbe2155150ffdf469612ff2da582ef3c7c776ed1265692bccb601e9c4415 (*errors.errorString)

2.diskBlocks(0)/dataBlocks(2) - too few shards given (*fmt.wrapError)

For log issue 1, It looks like the problem is caused by inconsistent data, but why doesn't autohealing take effect?
issue 2,  I don't understand what this `too few shards given` means, at this point the deleted pod is up.

Thanks a lot for the analysis.
BR//evt

**Comment by evt-byte** [comment]
Got a new log info :
"deploymentid":"b1e4a1ec-cbae-4a2a-9764-2cb978ff1215","level":"ERROR","errKind":"MINIO","time":"2021-07-30T01:52:30.144580196Z""api":{"name":"SYSTEM","args":{}},"error":{"message":"rle symbol 144 \u003e= max 36 (msgp.errWrapped)"

"deploymentid":"b1e4a1ec-cbae-4a2a-9764-2cb978ff1215","level":"ERROR","errKind":"MINIO","time":"2021-07-30T02:04:30.289071343Z","api":{"name":"SYSTEM","args":{}},"error":{"message":"rle symbol 175 \u003e= max 31 (msgp.errWrapped)"

**Comment by harshavardhana** [comment]
@evt-byte an HTTP is a single connection that belongs to either one of the pods - so if you decide to delete the pod that is actively serving the request - of course, it shall disconnect which causes `mc` to disconnect as well. 

There is no transparent connection move that will happen to other pods that's not how HTTP works.

**Comment by evt-byte** [comment]
@harshavardhana  OK, I got it,  what is the `rle symbol` and `too few shards given`?
Why does autohealing not work well?

**Comment by harshavardhana** [comment]
> @harshavardhana  OK, I got it,  what is the `rle symbol` and `too few shards given`?
> Why does autohealing not work well?

That can be ignored - if you have errors please upgrade we have fixed a whole bunch of healing related issues in recent releases.

Make sure to test upgrade in a separate non production environment first.

**Comment by harshavardhana** [comment]
> Got a new log info :
> "deploymentid":"b1e4a1ec-cbae-4a2a-9764-2cb978ff1215","level":"ERROR","errKind":"MINIO","time":"2021-07-30T01:52:30.144580196Z""api":{"name":"SYSTEM","args":{}},"error":{"message":"rle symbol 144 \u003e= max 36 (msgp.errWrapped)","source":["/opt/ericsson/go/src/github.com/minio/minio/cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()","/opt/ericsson/go/src/github.com/minio/minio/cmd/logger/logonce.go:93:logger.LogOnceIf()","/opt/ericsson/go/src/github.com/minio/minio/cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()","/opt/ericsson/go/src/github.com/minio/minio/cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()"
> 
> "deploymentid":"b1e4a1ec-cbae-4a2a-9764-2cb978ff1215","level":"ERROR","errKind":"MINIO","time":"2021-07-30T02:04:30.289071343Z","api":{"name":"SYSTEM","args":{}},"error":{"message":"rle symbol 175 \u003e= max 31 (msgp.errWrapped)","source":["/opt/ericsson/go/src/github.com/minio/minio/cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()","/opt/ericsson/go/src/github.com/minio/minio/cmd/logger/logonce.go:93:logger.LogOnceIf()","/opt/ericsson/go/src/github.com/minio/minio/cmd/data-usage-cache.go:546:cmd.(*dataUsageCache).load()","/opt/ericsson/go/src/github.com/minio/minio/cmd/erasure.go:461:cmd.erasureObjects.nsScanner.func3()"
> 

Also I see that you are compiling code yourself - I see that /opt/ericsson here.

We do not support you building custom binaries. 

Also NOTE: I need to remind you are under AGPLv3 violation here if you are using MinIO with proprietary purposes. Please consult a software lawyer for more information.

**Comment by evt-byte** [comment]
Thanks for the heads up, we are using Apache 2.0.

**Comment by harshavardhana** [comment]
> Thanks for the heads up, we are using Apache 2.0.

Unfortunately, we can't really help beyond this if you want to stick to Apache 2.0 - please upgrade or you need to fix the bugs yourself. 

Carefully avoiding the AGPLv3 code is quite disengenous.

**Comment by evt-byte** [comment]
@harshavardhana 
We are planning to upgrade to the latest AGPL version, and when we try to upgrade, we have this case that we need to support upgrade and rollback, does minio support such rollback(Large between different versions)? At the moment, it seems that upgrade to AGPL is possible but rollback to apache is not(done the upgrade-rollback test).

**Comment by harshavardhana** [comment]
> @harshavardhana 
> We are planning to upgrade to the latest AGPL version, and when we try to upgrade, we have this case that we need to support upgrade and rollback, does minio support such rollback? At the moment, it seems that upgrade to AGPL is possible but rollback to apache is not(done the upgrade-rollback test).

No it is not possible to rollback.

**Comment by evt-byte** [comment]
> 
> 
> > @harshavardhana
> > We are planning to upgrade to the latest AGPL version, and when we try to upgrade, we have this case that we need to support upgrade and rollback, does minio support such rollback? At the moment, it seems that upgrade to AGPL is possible but rollback to apache is not(done the upgrade-rollback test).
> 
> No it is not possible to rollback.

All right, I got it. Thank you very much for your reply.
