### ISSUE TITLE
Share file

### ISSUE THREAD

**Issue by fusengine** [minio/minio#12824]
why when i want to share a file it gets the ip address of docker and not the url, moreover i can't find anything on documentation concerning the change of the API link.

Do you have an idea??

<img width="1070" alt="Capture d’écran 2021-07-29 à 11 13 49" src="https://user-images.githubusercontent.com/7295655/127465963-5f23b5f1-7603-4064-8102-337cf3db58e7.png">

**Comment by mieseprem** [comment]
Have you tried to set MINIO_SERVER_URL?

**Comment by harshavardhana** [comment]
> Have you tried to set MINIO_SERVER_URL?

This one ^^
