### ISSUE TITLE
Bucket usage info goes back and forth from higher to lower and back again to higher

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#12822]
## Expected Behavior
Usage always reports correct values with ever-increasing count unless objects are deleted

## Current Behavior
Usage varies at various intervals and reports a completely different picture 
of the number of objects on the cluster. 

For example various intervals

Cycle 1
```
114 MiB Used, 1 Bucket, 116,560 Objects
120 drives online, 0 drives offline
```

Cycle 2
```
149 MiB Used, 1 Bucket, 152,944 Objects
120 drives online, 0 drives offline
```

Cycle 3
```
165 MiB Used, 1 Bucket, 168,674 Objects
120 drives online, 0 drives offline
```

Cycle 4
```
188 MiB Used, 1 Bucket, 192,198 Objects
120 drives online, 0 drives offline
```

Cycle 5
```
218 MiB Used, 1 Bucket, 223,789 Objects
120 drives online, 0 drives offline
```

Cycle 6
```
229 MiB Used, 1 Bucket, 234,322 Objects
120 drives online, 0 drives offline
```

Cycle 7 -- Error
```
178 MiB Used, 1 Bucket, 181,743 Objects
120 drives online, 0 drives offline
```

Cycle 8 -- Error
```
156 MiB Used, 1 Bucket, 160,079 Objects
120 drives online, 0 drives offline
```

## Possible Solution
Not sure but have tracked it down to there must be something missing 

```
commit 2ca9c533efb56a45959277da7395fb883d43eb8e
Author: Klaus Post <klauspost@gmail.com>
Date:   Wed May 19 23:38:30 2021 +0200
    feat: implement in-progress partial bucket updates (#12279)
```

## Steps to Reproduce (for bugs)
Just create a lot of objects observe usage going back and forth.

## Regression
Yes most probably

## Your Environment
```
git tag --contains 2ca9c533efb56a45959277da7395fb883d43eb8e
RELEASE.2021-05-20T22-31-44Z
RELEASE.2021-05-22T02-34-39Z
RELEASE.2021-05-26T00-22-46Z
RELEASE.2021-05-27T22-06-31Z
RELEASE.2021-06-07T21-40-51Z
RELEASE.2021-06-09T18-51-39Z
RELEASE.2021-06-14T01-29-23Z
RELEASE.2021-06-17T00-10-46Z
RELEASE.2021-07-08T01-15-01Z
RELEASE.2021-07-08T19-43-25Z
RELEASE.2021-07-12T02-44-53Z
RELEASE.2021-07-15T22-27-34Z
RELEASE.2021-07-21T22-15-23Z
RELEASE.2021-07-22T05-23-32Z
RELEASE.2021-07-27T02-40-15Z
```

**Comment by Rush** [comment]
I noticed the same thing. I am actually still trying to mirror my previous cluster with 1.5mln small objects to the new one but the usage statistics basically make no sense.

In fact even the object count seems underestimated.

**Comment by harshavardhana** [comment]
Update: Usage stabilizes after few hours of back and forth, it looks like a bloomfilter issue of sort. 

Dynamism is okay in updates but looks like initial usage runs are a bit erratic and should be fixed.
