### ISSUE TITLE
Web interface localhost:9000 not working/ redirects to console address port using latest minio.exe on Windows 10

### ISSUE THREAD

**Issue by dwolfschlaeger** [minio/minio#12834]
## Expected Behavior
In previous versions, starting the minio.exe server via Windows Cmd/ Powershell and accessing localhost:9000 made it possible to enter the credentials and use the web interface to create bucket etc.

## Current Behavior
accessing localhost:9000  redirects to localhost:<specific or dynamic> and keeps loading forever

## Steps to Reproduce (for bugs)
1. Download: https://dl.min.io/server/minio/release/windows-amd64/minio.exe
2. Open CMD
3. Enter: minio.exe server D:\test
4. Open browser and enter: localhost:9000

## Your Environment
I use the minio server for local development in Windows 10.
minio release date 2021-07-30

**Comment by dwolfschlaeger** [comment]
Is anyone epxeriencing the same? Until now, I did not have any problems using the minio server in the described manner. The problem occured when I was helping a student I supervise setting up his development environment for the first time on his notebook. 
I appreciate your help in advance :)

**Comment by vadmeste** [comment]
> accessing localhost:9000 redirects to localhost: and keeps loading forever

Is it litterally redirecting to `localhost:` without any port ? 

Can you start using `--console-address ":9001"` and try to open http://localhost:9001 ?
