### ISSUE TITLE
Minio "Tools -> Logs" page doesn't show the `MINIO_SERVER_URL` URL

### ISSUE THREAD

**Issue by carlosedp** [minio/minio#12850]
## Expected Behavior

Minio console "Tools -> Logs" page should also show the API URL from `MINIO_SERVER_URL` environment var if configured.

## Current Behavior

Currently it's only showing the URLs based on the container IPs.

![image](https://user-images.githubusercontent.com/20382/127931389-60f1b3a8-7edc-48f8-9f2e-b52d93a80480.png)

## Steps to Reproduce (for bugs)

1. Deploy Minio with `MINIO_SERVER_URL` different from the IPs used by the container/application.
2. Check that the page doesn't show the URL.

## Context

It would be clearer if the API address is correctly shown instead of the IPs (that in this bug example, mean nothing since one IP is localhost and the other is the internal Kubernetes IP.

## Your Environment
* Version used (`minio --version`): Latest container image from `minio/minio`. minio version RELEASE.2021-07-30T00-02-00Z.
* Server setup and configuration: K3s cluster.
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
This is on purpose @carlosedp MINIO_SERVER_URL is meant as an external ingress endpoint, it has nothing to do with MinIO internal ports where it's listening on. 

We can of course change it but what is the intention behind this ask?

**Comment by carlosedp** [comment]
Hi @harshavardhana, I just found it counter-intuitive since there is no point in this case showing up the internal IPs while other references (like sharing a file or bucket link) and the console reference in the same page already use the server external endpoints.
