### ISSUE TITLE
signature: AWS SDK PHP presigned requests not working with minio

### ISSUE THREAD

**Issue by ghost** [minio/minio#1285]
Hello Guys,

im trying to use minio with the official aws sdk under php (version 3.17.3).
However trying to get an presigned request does not work and minio rejects it with:
`SignatureDoesNotMatch`

Im using the sdk together with laravel like this:

``` php
$key = 'REDACTED';
$s3     = \Storage::disk('s3');
$client = $s3->getDriver()->getAdapter()->getClient();
$bucket = \Config::get('filesystems.disks.s3.bucket');

$command = $client->getCommand('GetObject', [
    'Bucket' => $bucket,
    'Key'    => $key
]);

$request = $client->createPresignedRequest($command, '+20 minutes');

return (string) $request->getUri();
```

The request i am getting back is something like this:
`https://HOST/BUCKET/REDACTED?X-Amz-Content-Sha256=REDACTED&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REDACTED&X-Amz-Date=REDACTED&X-Amz-SignedHeaders=Host&X-Amz-Expires=1200&X-Amz-Signature=REDACTED`

The main problem here is:
`X-Amz-Content-Sha256 and X-Amz-SignedHeaders`

I found a quick fix by editing

S3SignatureV4.php:

``` php
public function signRequest(
    RequestInterface $request,
    CredentialsInterface $credentials
) {
    if (!$request->hasHeader('x-amz-content-sha256')) {
        $request = $request->withHeader(
            'X-Amz-Content-Sha256',
            $this->getPayload($request)
        );
    }

    return parent::signRequest($request, $credentials);
}
```

to

``` php
public function signRequest(
    RequestInterface $request,
    CredentialsInterface $credentials
) {
    return parent::signRequest($request, $credentials);
}
```

SignatureV4.php:

``` php
public function presign(
------snip-----
    $parsed['query']['X-Amz-SignedHeaders'] = 'Host';
------snip-----
```

to

``` php
public function presign(
------snip-----
    $parsed['query']['X-Amz-SignedHeaders'] = 'host';
------snip-----
```

I guess the X-Amz-Content-Sha256 could be some unsupported thingy however uppercase/lowercase host should be supported by minio.

BTW: The SDK says 
`
    /**
     * Always add a x-amz-content-sha-256 for data integrity.
     */
`

This should be supported, i guess all other sdk's will implement the same features. Or just simply ignore it and proceed with the request, whatever.

Thanks

**Comment by harshavardhana** [comment]
Thanks for the heads up will validate on our end @techscorpion

**Comment by harshavardhana** [comment]
> $key = 'REDACTED';
> $s3     = \Storage::disk('s3');
> $client = $s3->getDriver()->getAdapter()->getClient();
> $bucket = \Config::get('filesystems.disks.s3.bucket');
> 
> $command = $client->getCommand('GetObject', [
>     'Bucket' => $bucket,
>     'Key'    => $key
> ]);
> 
> $request = $client->createPresignedRequest($command, '+20 minutes');
> 
> return (string) $request->getUri();

is there link to a full php example that i can download?

**Comment by harshavardhana** [comment]
> public function presign(
> ------snip-----
>     $parsed['query']['X-Amz-SignedHeaders'] = 'Host';
> ------snip-----

This would be a bug if signed headers have uppercase values, they should always be lowercased before sending to the server.  Perhaps S3 supports that too on server side but the Signature V4 spec indicates that they should be lower cased

http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

> To create the signed headers list, convert all header names to lowercase, sort them by character code, and use a semicolon to separate the header names. The following pseudocode describes how to construct a list of signed headers. Lowercase represents a function that converts all characters to lowercase.
> 
> SignedHeaders =
> Lowercase(HeaderName0) + ';' + Lowercase(HeaderName1) + ";" + ... + Lowercase(HeaderNameN)
> Build the signed headers list by iterating through the collection of header names, sorted by lowercase character code. For each header name except the last, append a semicolon (';') to the header name to separate it from the following header name.
> 
> Example signed headers
> 
> content-type;host;x-amz-date\n

**Comment by harshavardhana** [comment]
> public function signRequest(
>     RequestInterface $request,
>     CredentialsInterface $credentials
> ) {
>     if (!$request->hasHeader('x-amz-content-sha256')) {
>         $request = $request->withHeader(
>             'X-Amz-Content-Sha256',
>             $this->getPayload($request)
>         );
>     }
> 
> ```
> return parent::signRequest($request, $credentials);
> ```
> 
> }

This we don't support yet, can you open a separate bug for this ? - support "X-Amz-Content-Sha256" with pre-signed requests? 

Thanks.

**Comment by ghost** [comment]
Okay, opened one.
Does this mean that the aws sdk has a bug? I would file that to them then

**Comment by ghost** [comment]
@harshavardhana:

To replicate:
- Create a new laravel project
- Add s3 to flysystem `composer require league/flysystem-aws-s3-v3 ~1.0` (https://laravel.com/docs/5.2/filesystem)
- Change S3 config in config/filesystems.php

```
        's3'        => [
            'driver' => 's3',
            'key'    => '',
            'secret' => '',
            'region' => '',
            'bucket' => '',
            'endpoint' => '', # Minio URL here
        ]
```
- Take a controller route or just a normal quick route and try:

```
   $key = 'XXX;
    $s3     = \Storage::disk('s3');
    $client = $s3->getDriver()->getAdapter()->getClient();
    $bucket = \Config::get('filesystems.disks.s3.bucket');

    $command = $client->getCommand('GetObject', [
        'Bucket' => $bucket,
        'Key'    => $key
    ]);

    $request = $client->createPresignedRequest($command, '+20 minutes');

    return (string) $request->getUri();
```

This uses the SDK directly through `$s3->getDriver()->getAdapter()->getClient()` because laravel filesystem decorades the flysystem which decorades the native sdk.

Hope that helps as this is PHP and not Go :)
However here is how to use the standalone SDK:
http://martinbean.co.uk/blog/2015/06/18/creating-a-signed-url-with-aws-sdk-v3/

**Comment by harshavardhana** [comment]
> Does this mean that the aws sdk has a bug? I would file that to them then

Yep this is a bug, no other aws SDK does this. Thanks for the detailed instructions @tehscorpion will test it and support x-amz-content-sha256 for pre-signed.

**Comment by ghost** [comment]
Here you go:
https://github.com/aws/aws-sdk-php/pull/952

:) ill close it.

**Comment by harshavardhana** [comment]
> Here you go:
> aws/aws-sdk-php#952
> 
> :) ill close it.

Thanks @tehscorpion for pushing this through :-)
