### ISSUE TITLE
docs: Document setcap Linux equivalent for all other platforms. 

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1286]
`minio: <ERROR> Please run ‘minio’ as a non-root user.`

Version: 2016-03-21T21:08:51Z

**Comment by harshavardhana** [comment]
https://gist.github.com/kujohn/7209628 - we will document this for all platforms which don't have setcap. This is not a OSX related issue.

**Comment by harshavardhana** [comment]
Another simpler way is just do this - 'go get github.com/harshavardhana/pf' and run 'sudo pf' by default will forward all ":80" to ":9000"

**Comment by harshavardhana** [comment]
> Another simpler way is just do this - 'go get github.com/harshavardhana/pf' and run 'sudo pf' by default will forward all ":80" to ":9000"

👎  Actually this would be a bad idea, it should be kernel which decides so using 'pf' and 'rdr' at kernel level woould be better.

**Comment by GarimaKapoor** [comment]
Minio Server does not limit root privileges anymore.
