### ISSUE TITLE
ui exec delete empty directory will delete current folder all files and folder

### ISSUE THREAD

**Issue by cccfs** [minio/minio#12868]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

Retrieval process：
https://user-images.githubusercontent.com/73505347/128119953-22949ddc-c10f-4b17-bfb0-ecd18301a89a.mp4

**Comment by harshavardhana** [comment]
This is fixed in RELEASE.2021-07-30T00-02-00Z please upgrade.
