### ISSUE TITLE
minio status displays: `Error: disk path full` but has free space

### ISSUE THREAD

**Issue by buildwithdemis** [minio/minio#12872]
## Expected Behavior
the `systemctl status minio.service` shouldn't display disk full error

## Current Behavior
on every node when I check the status of minio server. ti displays the following error

user@minio1:~$ sudo systemctl status minio.service 
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-08-04 12:35:34 UTC; 1h 56min ago
     Docs: https://docs.min.io
 Main PID: 35754 (minio)
    Tasks: 54
   CGroup: /system.slice/minio.service
           └─35754 /usr/local/bin/minio server http://minio{1...8}/data{1...2}

Aug 04 14:32:02 minio1 minio[35754]:        3: cmd/metacache-set.go:952:cmd.listPathRaw()
Aug 04 14:32:02 minio1 minio[35754]:        2: cmd/global-heal.go:258:cmd.(*erasureObjects).healErasureSet()
Aug 04 14:32:02 minio1 minio[35754]:        1: cmd/background-newdisks-heal-ops.go:426:cmd.monitorLocalDisksAndHeal.func2()
Aug 04 14:32:15 minio1 minio[35754]: API: SYSTEM()
Aug 04 14:32:15 minio1 minio[35754]: Time: 14:32:15 UTC 08/04/2021
Aug 04 14:32:15 minio1 minio[35754]: DeploymentID: 8d962271-b05b-413f-a9c4-79614bbb378e
Aug 04 14:32:15 minio1 minio[35754]: Error: mkdir /data1/echis/2337a2cdd55c4dad9d23e7f3eafd5c76: no space left on device (*fs.PathError)
Aug 04 14:32:15 minio1 minio[35754]:        3: cmd/xl-storage.go:2111:cmd.(*xlStorage).RenameData()
Aug 04 14:32:15 minio1 minio[35754]:        2: cmd/storage-rest-server.go:711:cmd.(*storageRESTServer).RenameDataHandler()
Aug 04 14:32:15 minio1 minio[35754]:        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

## Other errors
Error: Heal attempt failed for echis/efc15a0114c847b29c86e0c01538d713: Storage reached its minimum free disk threshold. 
Error: mkdir /data1/echis/b94fd8eb68b14c5fb64129ad4da10cae: no space left on device 

## Context
the system is operational I can see that on:
1. mc admin info alias
2. mc admin trace alias: this output displays successful get and put objects.
3. `df -h` displays only 20% used space
4. `df -i` displays only 66% of inodes used

## Your Environment
* minio version `RELEASE.2021-06-14T01-29-23Z`
* Server setup and configuration: distributed,8 node 2drive/node
* Operating System and version (`Linux minio1 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`):
Ubuntu 18.04

**Comment by harshavardhana** [comment]
> Aug 04 14:32:15 minio1 minio[35754]: Error: mkdir /data1/echis/2337a2cdd55c4dad9d23e7f3eafd5c76: no space left on device (*fs.PathError)

Your backend disk is returning this error which filesystem is under use here?

**Comment by buildwithdemis** [comment]
ext4

**Comment by harshavardhana** [comment]
> ext4

Yeah, you have run out of the number of directories per prefix - ext4 has 64k limitation - you should re-format the drives to use XFS. 

We mention this here boldly https://github.com/minio/minio/blob/master/docs/minio-limits.md#minio-server-limits-per-tenant

> For best deployment experience MinIO recommends operating systems RHEL/CentOS 8.x or later, Ubuntu 18.04 LTS or later. These operating systems package the latest 'xfsprogs' that support large scale deployments.
