### ISSUE TITLE
Objects not getting permanently deleted in bucket with versioning enabled

### ISSUE THREAD

**Issue by kevintb** [minio/minio#12873]
I'm having problems with objects not getting deleted from a MinIO bucket. When I try to permanently delete an object by version-id the command runs without error:
```
$ mc rm minio-pebble/bucket/GROUP/file1.obj --version-id null
Removing `minio-pebble/bucket/GROUP/file1.obj` (versionId=null).
```

But the file is not actually deleted:
```
$ mc ls minio-pebble/bucket/GROUP/file1.obj --versions
[2021-03-20 21:59:46 UTC] 789KiB null v1 PUT file1.obj
```

This instance of MinIO had several hundred objects added to the bucket before versioning was enabled so their version-ids were all "null". Using the MinIO client, I was able to delete all but 4 of the objects without issue but have not been able to delete the remaining 4 objects.

This issue is occurring in a client's system so I have to scrub the output. I have read other issues mentioning trailing spaces and special characters sequences in object names can cause issues so I used "mc stat --json" to verify there were no trailing spaces and manually verified there were no special character sequences (like '//', from [8873](https://github.com/minio/minio/issues/8873)).

## Expected Behavior
I'm expecting when I run the command `mc rm minio-pebble/bucket/GROUP/file1.obj --version-id null` the file is permanently deleted.

## Current Behavior
After the statement `mc rm minio-pebble/bucket/GROUP/file1.obj --version-id null` is run the file will still appear with the statement `mc ls minio-pebble/bucket/GROUP/file1.obj --versions`.

## Steps to Reproduce (for bugs)

I do not have a reliable method for reproducing the objects that cannot be deleted from a bucket. However, the steps to the issue are listed below:
1. Upload file to MinIO bucket.
2. Enable versioning for bucket.
3. Delete file from bucket with a specific version.
4. List file that should have been deleted.

## Context

I'm working on a MinIO cluster with objects that cannot be deleted.

## Your Environment

* mc version RELEASE.2021-03-23T05-46-11Z
* MinIO server version: 2021-03-17T02:33:02Z
* 4 drives in the cluster (all online).
* OS is Centos 7.7.1908 (Linux k8s-access 3.10.0-1062.18.1.el7.x86_64 Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by harshavardhana** [comment]
> * mc version RELEASE.2021-03-23T05-46-11Z
> * MinIO server version: 2021-03-17T02:33:02Z

Please upgrade your cluster @kevintb

**Comment by kevintb** [comment]
@harshavardhana Thanks for responding. 

I have upgraded one of our clusters to 2021-07-30T00:02:00Z to experiment with.

We're still trying to understand how these objects got into the state where they could not be deleted. Are there issues with using 'ctrl-c' to kill 'mc cp' or 'mc rm --recursive --versions --force' commands?

**Comment by harshavardhana** [comment]
> We're still trying to understand how these objects got into the state where they could not be deleted. Are there issues with using 'ctrl-c' to kill 'mc cp' or 'mc rm --recursive --versions --force' commands?

No there shouldn't be

**Comment by harshavardhana** [comment]
@kevintb once you upgrade you can also use `mc admin inspect` to share with us the object that is in the current state.

**Comment by klauspost** [comment]
You can share the output from `mc admin inspect minio-pebble/bucket/GROUP/file1.obj/xl.meta` of the object you are not observing to be deleted.

Post the output file here. If the metadata contains sensitive information, share the decryption key on `dev@minio.io`, otherwise post it here along with the data.

**Comment by harshavardhana** [comment]
Closing this issue since there is no follow up.
