### ISSUE TITLE
Provide MinIO client inside MinIO server docker image

### ISSUE THREAD

**Issue by tomwassing** [minio/minio#12889]
**Is your feature request related to a problem? Please describe.**
The server docker image does not include the minio client. Having access to the mc client would significantly simplify our docker deployment and build pipeline.

**Describe the solution you'd like**
Having access to the 'mc' MinIO client inside the MinIO server docker image

**Comment by harshavardhana** [comment]
Docker image is kept minimal for the service alone, mc is provided as a separate container.

Can you explain what is complicated today ?

**Comment by tomwassing** [comment]
We want to change the policy of a bucket. This would require us to add an additional mc container to our deployment or build a new image.

**Comment by harshavardhana** [comment]
> We want to change the policy of a bucket. This would require us to add an additional mc container to our deployment or build a new image.

How hard it is to do that ? And why are you building a new image we provide this pre-built?

**Comment by harshavardhana** [comment]
I don't think there is good evidence here to include `mc` inside MinIO - they are kept separate on purpose at this point in time.

Unless there are challenges in using mc as a container we do not see this to be a problem.
