### ISSUE TITLE
Can't use a custom region - The region is wrong

### ISSUE THREAD

**Issue by imtomjorge** [minio/minio#12886]
## Expected Behavior
Minio Gateway must using custom region that I've added with following arguments:
```
 -e "MINIO_REGION=fr-par" \
 -e "MINIO_REGION_NAME=fr-par" \
```
Tried with the first one only, then the second one only, then both.

## Current Behavior
The system does not detect the region and these 2 arguments.
```
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par' (minio.ErrorResponse)
       5: cmd/api-errors.go:2045:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:1005:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1105:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:1065:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
No idea at all.

## Steps to Reproduce (for bugs)

1. Deploy a Minio Gateway container
2. Try to log in with S3 credentials on Web UI (IPv4:9001)
3. Check output of the docker container

## Context
I want to use an S3 compliant provider, with their region "fr-par".

## Regression
No.

## Your Environment
* Version used (`minio --version`): NA
* Server setup and configuration: Debian Buster
* Operating System and version (`uname -a`): Linux 5.10.28 #1 SMP Mon May 24 14:34:16 UTC 2021 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@imtomjorge what argument did you pass to MinIO gateway ?

**Comment by imtomjorge** [comment]
> @imtomjorge what argument did you pass to MinIO gateway ?

Hello,
Here is my docker run command:
```
 docker run -p 9001:9001 --name minio-s3 \
 -e "MINIO_REGION=fr-par" \
 -e "MINIO_REGION_NAME=fr-par" \
 -e "MINIO_ROOT_USER=MyAccessKey" \
 -e "MINIO_ROOT_PASSWORD=MySecretKey" \
 minio/minio gateway s3 https://mys3providerendpoint.tld --console-address ":9001"
```

I'm not the first one, as another customer experienced this issue:
https://minio.slack.com/archives/C3NDUB8UA/p1626253903431000

Thanks! 👍

**Comment by klauspost** [comment]
@imtomjorge 'us-east-1' is from the request. The server expects 'fr-par'. Check whatever client is generating the request and set the correct region there.

**Comment by imtomjorge** [comment]
@klauspost, thanks a lot for your help.
 I'm currently trying to log in with access and secret key to MinioGUI.
How can I proceed to check the request origin?

**Comment by harshavardhana** [comment]
> @klauspost, thanks a lot for your help.
> I'm currently trying to log in with access and secret key to MinioGUI.
> How can I proceed to check the request origin?

Looks like console region name is not set correctly.

**Comment by imtomjorge** [comment]
> > @klauspost, thanks a lot for your help.
> > I'm currently trying to log in with access and secret key to MinioGUI.
> > How can I proceed to check the request origin?
> 
> Looks like console region name is not set correctly.

How can I correctly set the region name?
I've tried to use each one, then both, but the issue persists.
` -e "MINIO_REGION=fr-par" \ `
`  -e "MINIO_REGION_NAME=fr-par" \`

**Comment by harshavardhana** [comment]
> > > @klauspost, thanks a lot for your help.
> > > I'm currently trying to log in with access and secret key to MinioGUI.
> > > How can I proceed to check the request origin?
> > 
> > 
> > Looks like console region name is not set correctly.
> 
> How can I correctly set the region name?
> I've tried to use each one, then both, but the issue persists.
> `-e "MINIO_REGION=fr-par" \`
> ` -e "MINIO_REGION_NAME=fr-par" \`

It looks like an issue with console we will verify

**Comment by harshavardhana** [comment]
I just tested seems to be working totally fine 

```
AWS_PROFILE=s3 MINIO_REGION_NAME=france minio gateway s3 https://s3.amazonaws.com
API: http://10.0.0.67:9000 
RootUser: minio 
RootPass: minio123 

Console: http://10.0.0.67:42901 http://172.17.0.1:42901 http://172.18.0.1:42901 http://172.19.0.1:42901 http://127.0.0.1:42901               
RootUser: minio 
RootPass: minio123 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set mys3 http://10.0.0.67:9000 minio minio123

Documentation: https://docs.min.io

WARNING: The console endpoint is listening on a dynamic port (42901), please use --console-address ":PORT" to choose a static port.
```

I don't any issue logging into console with `minio` and `minio123`

**Comment by imtomjorge** [comment]
> I just tested seems to be working totally fine
> 
> ```
> AWS_PROFILE=s3 MINIO_REGION_NAME=france minio gateway s3 https://s3.amazonaws.com
> API: http://10.0.0.67:9000 
> RootUser: minio 
> RootPass: minio123 
> 
> Console: http://10.0.0.67:42901 http://172.17.0.1:42901 http://172.18.0.1:42901 http://172.19.0.1:42901 http://127.0.0.1:42901               
> RootUser: minio 
> RootPass: minio123 
> 
> Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
>    $ mc alias set mys3 http://10.0.0.67:9000 minio minio123
> 
> Documentation: https://docs.min.io
> 
> WARNING: The console endpoint is listening on a dynamic port (42901), please use --console-address ":PORT" to choose a static port.
> ```
> 
> I don't any issue logging into console with `minio` and `minio123`

Thanks for your investigation.
But I’ve deployed the console from Docker container, and both:
`-e "MINIO_REGION=fr-par" \
-e "MINIO_REGION_NAME=fr-par" \ `
Aren’t working at all with Docker deployment.

**Comment by harshavardhana** [comment]
This error is generated because we do not pass this region information to your backend server implementation - this is meant for termination of the region at MinIO level. 

What is happening here is that your S3 compatible implementation is wrong it is expecting ListBuckets() to have a region configured that is not correct. 

Region is bucket specific not ListBuckets() specific so your S3 compatible implementation needs to be fixed to allow `us-east-1` for ListBuckets() calls. 

> Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par' (minio.ErrorResponse)

**Comment by imtomjorge** [comment]
> This error is generated because we do not pass this region information to your backend server implementation - this is meant for termination of the region at MinIO level.
> 
> What is happening here is that your S3 compatible implementation is wrong it is expecting ListBuckets() to have a region configured that is not correct.
> 
> Region is bucket specific not ListBuckets() specific so your S3 compatible implementation needs to be fixed to allow `us-east-1` for ListBuckets() calls.
> 
> > Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par' (minio.ErrorResponse)

Hello @harshavardhana,
Thanks a lot for your help.
I will request more details, and help from my S3 provider.
I will keep updated this issue! :)

**Comment by Timost** [comment]
Hi @imtomjorge,
I'm facing the same issue, did you end up finding a solution ? I'm guessing this was on scaleway, did they provide any help on this ?

**Comment by Seishiro93** [comment]
@Timost @imtomjorge 
I am in the same situation as you. And I don't think Scaleway is going to change anything on their side.
I am looking at this alternative https://github.com/noobaa. For the moment I have no opinion on the solution but the promise seems very interesting
