### ISSUE TITLE
MinIO memory usage continues to rise, then goes down

### ISSUE THREAD

**Issue by wzc900810** [minio/minio#12881]
Hosts configuration：
CPU：2C
MEMORY：4G
OS：Amazon Linux release 2 (Karoo)

Minio running on 3 different hosts with 6 disks and the following is my docker-compose configuration：
`version: '3'

services:
  minio1:
    image: docker-image.paxengine.com.cn/public/minio:RELEASE.2021-07-15
    container_name: minio1
    hostname: minio1
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data1/minio1-data1:/data1
      - /data2/minio1-data2:/data2
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=minio-dev
      - MINIO_ROOT_PASSWORD=minio123-dev
    extra_hosts:
      - "minio1:192.168.99.35"
      - "minio2:192.168.99.36"
      - "minio3:192.168.99.37"
    command: server --address ":9000" --console-address ":9001" http://minio{1...3}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3`

MinIO has three buckets, 40G of data, and about 2 million objects

There will always be a host that uses more than 90% of memory and the container will automatically restart after a period of downtime。

the following is the profile file：
[profile.zip](https://github.com/minio/minio/files/6935461/profile.zip)

**Comment by harshavardhana** [comment]
2 millon objects and using 4g memory is not possible to have a setup running. 

Please use proper setup for your scale deploy a minimum of 8G memory or limit your I/O by setting

MINIO_API_REQUESTS_MAX=32

**Comment by harshavardhana** [comment]
Inuse space v/s alloc space

```
(pprof) top
Showing nodes accounting for 217.34MB, 96.48% of 225.26MB total
Dropped 506 nodes (cum <= 1.13MB)
Showing top 10 nodes out of 82
      flat  flat%   sum%        cum   cum%
  186.95MB 82.99% 82.99%   186.95MB 82.99%  github.com/minio/minio/cmd.NewReplicationPool
       6MB  2.66% 85.65%        6MB  2.66%  github.com/minio/minio/internal/bpool.(*BytePoolCap).Get
    5.04MB  2.24% 87.89%     5.04MB  2.24%  github.com/minio/minio/cmd.newExpiryState
    4.96MB  2.20% 90.09%     4.96MB  2.20%  github.com/minio/minio/cmd.newTransitionState
    4.15MB  1.84% 91.93%     4.15MB  1.84%  bytes.makeSlice
    4.02MB  1.78% 93.72%     4.02MB  1.78%  github.com/ncw/directio.AlignedBlock
       2MB  0.89% 94.61%        2MB  0.89%  github.com/minio/minio/cmd.glob..func5
    1.99MB  0.88% 95.49%     1.99MB  0.88%  github.com/bits-and-blooms/bitset.New
    1.53MB  0.68% 96.17%     1.53MB  0.68%  reflect.mapassign
    0.71MB  0.31% 96.48%     1.22MB  0.54%  github.com/go-openapi/analysis.(*Spec).analyzeSchema
```

v/s

```
(pprof) top
Showing nodes accounting for 4799.45MB, 41.12% of 11672.85MB total
Dropped 1991 nodes (cum <= 58.36MB)
Showing top 10 nodes out of 277
      flat  flat%   sum%        cum   cum%
  949.60MB  8.14%  8.14%   949.60MB  8.14%  io.ReadAll
  847.65MB  7.26% 15.40%   972.11MB  8.33%  github.com/minio/minio/cmd.(*dataUsageCache).copyWithChildren
  731.33MB  6.27% 21.66%   769.57MB  6.59%  net/url.parseQuery
  574.77MB  4.92% 26.59%   574.77MB  4.92%  github.com/ncw/directio.AlignedBlock
  395.38MB  3.39% 29.97%  1374.56MB 11.78%  github.com/minio/minio/cmd.(*folderScanner).scanFolder.func1
  336.21MB  2.88% 32.85%   337.82MB  2.89%  path.Join
  259.33MB  2.22% 35.08%   400.58MB  3.43%  github.com/minio/minio/cmd.(*dataUsageCache).DecodeMsg
  248.37MB  2.13% 37.20%   301.90MB  2.59%  github.com/minio/minio/cmd.(*dataUsageCache).find
  243.30MB  2.08% 39.29%   258.91MB  2.22%  net/textproto.(*Reader).ReadMIMEHeader
  213.50MB  1.83% 41.12%   213.50MB  1.83%  github.com/minio/minio/cmd.(*dataUsageEntry).addChild (inline)
```

As you can see need to use more than 4G of allocspace but this needs to be cleaned up automatically by Go GC which is not triggered unfortunately that is why it leads to a crash. 

You can set GOGC=10 or something from default 100 to allow GO to garbage collect quickly.

**Comment by wzc900810** [comment]
> Inuse space v/s alloc space
> 
> ```
> (pprof) top
> Showing nodes accounting for 217.34MB, 96.48% of 225.26MB total
> Dropped 506 nodes (cum <= 1.13MB)
> Showing top 10 nodes out of 82
>       flat  flat%   sum%        cum   cum%
>   186.95MB 82.99% 82.99%   186.95MB 82.99%  github.com/minio/minio/cmd.NewReplicationPool
>        6MB  2.66% 85.65%        6MB  2.66%  github.com/minio/minio/internal/bpool.(*BytePoolCap).Get
>     5.04MB  2.24% 87.89%     5.04MB  2.24%  github.com/minio/minio/cmd.newExpiryState
>     4.96MB  2.20% 90.09%     4.96MB  2.20%  github.com/minio/minio/cmd.newTransitionState
>     4.15MB  1.84% 91.93%     4.15MB  1.84%  bytes.makeSlice
>     4.02MB  1.78% 93.72%     4.02MB  1.78%  github.com/ncw/directio.AlignedBlock
>        2MB  0.89% 94.61%        2MB  0.89%  github.com/minio/minio/cmd.glob..func5
>     1.99MB  0.88% 95.49%     1.99MB  0.88%  github.com/bits-and-blooms/bitset.New
>     1.53MB  0.68% 96.17%     1.53MB  0.68%  reflect.mapassign
>     0.71MB  0.31% 96.48%     1.22MB  0.54%  github.com/go-openapi/analysis.(*Spec).analyzeSchema
> ```
> 
> v/s
> 
> ```
> (pprof) top
> Showing nodes accounting for 4799.45MB, 41.12% of 11672.85MB total
> Dropped 1991 nodes (cum <= 58.36MB)
> Showing top 10 nodes out of 277
>       flat  flat%   sum%        cum   cum%
>   949.60MB  8.14%  8.14%   949.60MB  8.14%  io.ReadAll
>   847.65MB  7.26% 15.40%   972.11MB  8.33%  github.com/minio/minio/cmd.(*dataUsageCache).copyWithChildren
>   731.33MB  6.27% 21.66%   769.57MB  6.59%  net/url.parseQuery
>   574.77MB  4.92% 26.59%   574.77MB  4.92%  github.com/ncw/directio.AlignedBlock
>   395.38MB  3.39% 29.97%  1374.56MB 11.78%  github.com/minio/minio/cmd.(*folderScanner).scanFolder.func1
>   336.21MB  2.88% 32.85%   337.82MB  2.89%  path.Join
>   259.33MB  2.22% 35.08%   400.58MB  3.43%  github.com/minio/minio/cmd.(*dataUsageCache).DecodeMsg
>   248.37MB  2.13% 37.20%   301.90MB  2.59%  github.com/minio/minio/cmd.(*dataUsageCache).find
>   243.30MB  2.08% 39.29%   258.91MB  2.22%  net/textproto.(*Reader).ReadMIMEHeader
>   213.50MB  1.83% 41.12%   213.50MB  1.83%  github.com/minio/minio/cmd.(*dataUsageEntry).addChild (inline)
> ```
> 
> As you can see need to use more than 4G of allocspace but this needs to be cleaned up automatically by Go GC which is not triggered unfortunately that is why it leads to a crash.
> 
> You can set GOGC=10 or something from default 100 to allow GO to garbage collect quickly.

Thank you for your reply, how to change the value of GCGO?

**Comment by harshavardhana** [comment]
> Thank you for your reply, how to change the value of GCGO?

Set the environment variable GOGC=10 in your container deployment.

**Comment by wzc900810** [comment]
> > Thank you for your reply, how to change the value of GCGO?
> 
> Set the environment variable GOGC=10 in your container deployment.

Add GOGC=10 to the environment configuration in docker-compose.yml, like
![image](https://user-images.githubusercontent.com/6902998/128447177-ce91391e-8201-404d-953f-f1ee3023cee6.png)
Is it right？

**Comment by harshavardhana** [comment]
> Is it right？

Correct @wzc900810

**Comment by wzc900810** [comment]
> > Is it right？
> 
> Correct @wzc900810

Thank you

**Comment by klauspost** [comment]
alloc_space is lifetime allocs, so it is a useless metric. This is expected usage. You should give your instances more RAM. As mentioned GOGC will reduce the overhead at a CPU cost.
