### ISSUE TITLE
signature: Support "X-Amz-Content-Sha256" with pre-signed requests

### ISSUE THREAD

**Issue by ghost** [minio/minio#1288]
Open as enhancement request.

As stated in #1285

**Comment by ghost** [comment]
For anyone who is using the AWS PHP SDK and running into the problem that you cannot use minio with presigned requests i just monkey patched one function.

Im using https://antecedent.github.io/patchwork/

insert the following lines to `bootstrap/autoload.php` as the first lines:

``` php
require __DIR__.'/../vendor/antecedent/patchwork/Patchwork.php';
require __DIR__.'/patches.php';
```

create `patches.php` under `bootstrap/`:

``` php
<?php
// Patching aws framework to use it with minio
use Aws\Credentials\CredentialsInterface;
use Psr\Http\Message\RequestInterface;

Patchwork\redefine('Aws\Signature\S3SignatureV4::signRequest', function (RequestInterface $request, CredentialsInterface $credentials) {
    return parent::signRequest($request, $credentials);
});
```

And make sure u are using no opcache because monkey patching does not work properly right now with apc/opcache extensions.

This is not a permanent solution since minio should be supporting `X-Amz-Content-Sha256` please hurry up :+1:

**Comment by harshavardhana** [comment]
> And make sure u are using no opcache because monkey patching does not work properly right now with apc/opcache extensions.
> 
> This is not a permanent solution since minio should be supporting X-Amz-Content-Sha256 please hurry up

Is there no way to turn it off in PHP sdk?  to not generate payload for presigned requests?

**Comment by ghost** [comment]
As i see the actual state of the sdk its not possible, i can investigate further... i see there is a function which says:

``` php
    protected function getPresignedPayload(RequestInterface $request)
    {
        return 'UNSIGNED-PAYLOAD';
    }
```

Maybe its another bug? Because this the client is using some other function which adds the header and THEN calls the function above:

``` php
        $parsed = $this->createPresignedRequest($request, $credentials);
        $payload = $this->getPresignedPayload($request);
```

`createPresignedRequest` creates the header and `getPresignedPayload` should be returning `UNSIGNED-PAYLOAD`.

The SDK says the following:

```
Important

When transferring payload in a single chunk, you can optionally choose to include the payload hash in the signature calculations, referred as signed payload (if you don't include it, the payload is considered unsigned). The signing procedure discussed in the following section applies to both, but note the following differences:

    Signed payload option – You include the payload hash when constructing the canonical request (that then becomes part of StringToSign, as explained in the signature calculation section). You also specify the same value as the x-amz-content-sha256 header value when sending the request to S3.

    Unsigned payload option – You include the literal string UNSIGNED-PAYLOAD when constructing a canonical request, and set the same value as the he x-amz-content-sha256 header value when sending the request to S3.

When you send your request to S3, the x-amz-content-sha256 header value informs S3 whether the payload is signed or not. Amazon S3 can then create signature accordingly for verification. 
```

Further they say the following:

```
You don't include a payload hash in the Canonical Request, because when you create a presigned URL, you don't know the payload content because the URL is used to upload an arbitrary payload. Instead, you use a constant string UNSIGNED-PAYLOAD. 
```

**Comment by harshavardhana** [comment]
Ah this looks like a bug, since it was not their intention to do it but it is happening underneath. Supporting payload verification with presigned is fine too on server side it adds an additional layer.

But the payload mismatch can only be triggered after all the data has been sent and verified, presigned is quicker without that since you already trust that URL. Unless you specifically need payload hash with presigned it shouldn't be made default behavior - so it can be considered as a bug in SDK.

**Comment by ghost** [comment]
I filed another https://github.com/aws/aws-sdk-php/issues/954 :sleepy:

**Comment by jeskew** [comment]
@harshavardhana The PHP SDK (and other AWS SDKs) always include a X-Amz-Content-Sha256 header containing the string 'UNSIGNED PAYLOAD' when constructing presigned requests. This is what S3 expects and is intentional behavior in the SDK.

**Comment by harshavardhana** [comment]
> @harshavardhana The PHP SDK (and other AWS SDKs) always include a X-Amz-Content-Sha256 header containing the string 'UNSIGNED PAYLOAD' when constructing presigned requests. This is what S3 expects and is intentional behavior in the SDK.

I agree - here the X-Amz-Content-Sha256 - "sha256" of the actual payload. not "UNSIGNED-PAYLOAD"

**Comment by harshavardhana** [comment]
> I agree - here the X-Amz-Content-Sha256 - "sha256" of the actual payload. not "UNSIGNED-PAYLOAD"

Will investigate and post more details.
