### ISSUE TITLE
Can't deploy Minio Gateway with a S3 compliant provider

### ISSUE THREAD

**Issue by imtomjorge** [minio/minio#12884]
## Expected Behavior
The container should be running, and reach the compliant provider S3 endpoint.

## Current Behavior
Argument S3 gateway can't be approved, because it reaches local IPv4 on port 53.
`ERROR Invalid argument: lookup mys3providerendpoint.tld on MyLocalIPv4:53: no such host`

## Possible Solution
No idea at all.

## Steps to Reproduce (for bugs)
1. Install docker and docker compose
2. Get Access and Secret key from your S3 compliant provider.
3. Replace values by keys, and endpoint:
```
 docker run -p 9001:9001 --name minio-s3 \
 -e "MINIO_ROOT_USER=ACCESSKEY" \
 -e "MINIO_ROOT_PASSWORD=SECRETKEY" \
 minio/minio gateway s3 https://mys3providerendpoint.tld
```
4. Then type enter.
5. Type docker ps -a and see container failing. Docker logs [containerID] return no output.

## Context
I've tried to set up Minio Gateway to use Minio Console with an S3 compliant provider.

## Regression
No.

## Your Environment

* Version used (`minio --version`): NC
* Server setup and configuration: Debian Buster
* Operating System and version (`uname -a`): Linux 5.10.28 #1 SMP Mon May 24 14:34:16 UTC 2021 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> `ERROR Invalid argument: lookup mys3providerendpoint.tld on MyLocalIPv4:53: no such host`

Your DNS lookup is failing nothing to do with S3 gateway here.

**Comment by harshavardhana** [comment]
Please fix your DNS issue first most probably your container cannot lookup the domain name, if the domain name lookup succeeds it will work fine as long as your S3 compliant provider implements S3 appropriately. 

Closing this issue.
