### ISSUE TITLE
K8s rolling update breaks URL patterns

### ISSUE THREAD

**Issue by tibeer** [minio/minio#12890]
Performing a rolling upgrade from docker image
RELEASE.2021-06-17T00-10-46Z to anything greater results
in inaccessibility.

## Expected Behavior
Performing a K8s rolling update should not break URL patterns.

## Current Behavior
When performing a rolling update in K8s to a release from 2021-07 or later, minio strangely malforms the URL to a high range, random port. When entering the URL to the web-UI **https://foo.bar.com/**, a random port gets appended
(like this: **https://foo.bar.com:33711/**) while it should stay like this: **https://foo.bar.com/**.
This behavior started to appear in versions from 2021-07 and later.

## Possible Solution
I have no idea what is causing this behavior.

## Steps to Reproduce (for bugs)

Replace the image in the deployment with a never version and try to access the web-UI again.
Deployment yaml:
```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    deployment.kubernetes.io/revision: "14"
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: minio
    meta.helm.sh/release-namespace: minio
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2021-07-28T07:45:01Z"
  generation: 33
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-8.0.10
    heritage: Helm
    release: minio
  name: minio
  namespace: minio
  resourceVersion: "14038067"
  uid: foobar
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
      release: minio
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: foobar
        checksum/secrets: foobar
      creationTimestamp: null
      labels:
        app: minio
        release: minio
      name: minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: minio
        - name: MINIO_DOMAIN
          value: foo.bar.com
        image: RELEASE.2021-06-17T00-10-46Z # replace this with the new value: minio/minio:RELEASE.2021-07-08T01-15-01Z
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: export
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccount: minio
      serviceAccountName: minio
      terminationGracePeriodSeconds: 30
      volumes:
      - name: export
        persistentVolumeClaim:
          claimName: minio
      - name: minio-user
        secret:
          defaultMode: 420
          secretName: minio
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-05T12:35:23Z"
    lastUpdateTime: "2021-08-05T12:35:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
```

Here are some steps taken:
1. Updating to *RELEASE.2021-07-08T01-15-01Z* results in URL malformation like this: **https://foo.bar.com:33711/**
2. Updating to *RELEASE.2021-07-08T19-43-25Z* results in URL malformation like this: **https://foo.bar.com:45495/**
3. Updating to *RELEASE.2021-07-12T02-44-53Z* results in URL malformation like this: **https://foo.bar.com:34415/**
4. Downgrading to an older (broken) version to check if the port is static:
  *RELEASE.2021-07-08T01-15-01Z* results in URL malformation like this: **https://foo.bar.com:42543/**
5. Downgrading again to the last functional version:
  *RELEASE.2021-06-17T00-10-46Z* results in a working URL again: **https://foo.bar.com/**

I tried also older versions than the last working and upgrading again from there. The pattern keeps the same: Every release starting with *RELEASE.2021-07* malforms URLs to random ports.

## Context
Updating minio to a newer version.
Affect: Minio becomes useless for us as the Web-UI is not accessible any more.

## Regression
No

## Your Environment
RELEASE.2021-06-17T00-10-46Z (last functional)
RELEASE.2021-07-08T01-15-01Z and greater broken
Kubernetes v1.20.5

**Comment by harshavardhana** [comment]
It's not a malformed URL read https://github.com/minio/minio#things-to-consider

And also read the relevant release notes when this changed.

**Comment by 030** [comment]
It is a pity that semantic versioning is not considered. Apart from that, [the applicable release note the maintainer is referring to](https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z) is probably:

```
Embedded MinIO Browser removed replaced with MinIO Console project https://github.com/minio/console, this is a breaking change

MinIO redirects browser access requests to the configured server port (i.e. 127.0.0.1:9000) to the configured Console port. MinIO uses the hostname or IP address specified in the request when building the redirect URI. The URL and port must be accessible by the client for the redirection to work
```

**Comment by berendt** [comment]
@030 Thank you for the direct reference to the release notes. That makes it much easier for us.

**Comment by 030** [comment]
@tibeer Just reverted to `RELEASE.2021-06-17T00-10-46Z` and fortunately this version still works! I have disabled the auto update of Minio and we have to investigate how to migrate our current setup to the newest Minio version. For now we will apply security updates to the `RELEASE.2021-06-17T00-10-46Z` in order to keep using Minio. It works great, but from now on we will parse the release notes for breaking changes.
