### ISSUE TITLE
Non-root user on Docker error: Unable to initialize backend: mkdir /data/.minio.sys: permission denied

### ISSUE THREAD

**Issue by DHFW** [minio/minio#12899]
When I start Docker container with `--user $(id -u):$(id -g)` I get this error: 
`ERROR Unable to initialize backend: mkdir /data/.minio.sys: permission denied`

My 100x user has rights on the host to create files, directories etc. The volume is mounted to a directory where this user has access to.

Without the `--user ` parameter it works, but when uploading a file with the UI/console it is saved on the host as root, which means I cannot do anything with my 100x user with the files (i.e. if I want to move the files). I want to use the 100x user (which I also use for other services that write to disk on the host via volume mounting without problems.

The docs are clear about this, but it does not work.

## Expected Behavior
Files/folders should be created with the user I enter in the `--user` parameter, like described in the docs.

## Current Behavior
`ERROR Unable to initialize backend: mkdir /data/.minio.sys: permission denied` after starting the container.

## Steps to Reproduce (for bugs)
Create a new docker container using a image (i.e.: RELEASE.2021-06-07T21-40-51Z or RELEASE.2021-08-05T22-01-19Z).
```
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  --user $(id -u):$(id -g) \
  --name minio1 \
  -e "MINIO_ROOT_USER=xxx" \
  -e "MINIO_ROOT_PASSWORD=xxx" \
  -v ${HOME}/data:/data \
  minio/minio server /data
```

See error in the container logs
ERROR Unable to initialize backend: mkdir /data/.minio.sys: permission denied

## Context
First time user using Minio.
I tried via Docker and via Portainer and enter the user parameter 1007:1007 via the user property.
Also tried with MINIO_USERNAME=1007 and MINIO_GROUPNAME=1007 via the env vars.
It runs fine without the user parameter, but then my files are stored as root what I don't want.

## Regression
Is this issue a regression? (Yes / No): Yes

## Your Environment
* Version used (`minio --version`): RELEASE.2021-06-07T21-40-51Z and RELEASE.2021-08-05T22-01-19Z
* Server setup and configuration: Linux
* Operating System and version (`uname -a`): Linux xxx 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
```
~ mkdir -p ~/data
Bucket created successfully `/home/harsha/data`.
~  docker run   -p 9000:9000   -p 9001:9001   --user $(id -u):$(id -g)   --name minio1   -e "MINIO_ROOT_USER=minio"   -e "MINIO_ROOT_PASSWORD=minio123"   -v ${HOME}/data:/data  minio/minio server /data
API: http://172.17.0.4:9000  http://127.0.0.1:9000       

Console: http://172.17.0.4:34045 http://127.0.0.1:34045    

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (34045), please use --console-address ":PORT" to choose a static port.
```

**Comment by DHFW** [comment]
Well thank you. While not really helpful, I forgot to mention that I already had a minio service running. I discovered that the files were written with root user so I emptied the directory (as I thought), but I didn't saw there are hidden files in .minio.sys directory which the 1007 user has no permissions on, hence the error message. So I tried to delete those files, but I'm not allowed (I don't have root priviles on the host, it is an hosted environment).

So I setup a new directory on the host machine and created a new Docker container and now it works with the user I specified (1007). 

Just leaving this here for others that might face the same issue.

**Comment by harshavardhana** [comment]
> Well thank you. While not really helpful, I forgot to mention that I already had a minio service running. I discovered that the files were written with root user so I emptied the directory (as I thought), but I didn't saw there are hidden files in .minio.sys directory which the 1007 user has no permissions on, hence the error message. So I tried to delete those files, but I'm not allowed (I don't have root priviles on the host, it is an hosted environment).
> 
> So I setup a new directory on the host machine and created a new Docker container and now it works with the user I specified (1007).
> 
> Just leaving this here for others that might face the same issue.

Yes you need to change permissions and it should be present if you happen to change the uid/gid to the drives.
