### ISSUE TITLE
Minio Request Signature from downloadable link isn't working 

### ISSUE THREAD

**Issue by bhuiyanmobasshir94** [minio/minio#12892]
When I am trying to download using minio object download link, its giving me error with this message
`<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>Main v1.35.zip</Key>
<BucketName>graaho</BucketName>
<Resource>/graaho/Main v1.35.zip</Resource>
<RequestId>169873C0E29BE1E4</RequestId>
<HostId>fc666c59-55ba-444c-8a7e-6a3d832422cd</HostId>
</Error>`

## Expected Behavior
In the previous version, it worked great, but in a recent error, I am facing this. Besides, in the generated link I can find the IP different than my actual one.

**Comment by harshavardhana** [comment]
Please share more details, there is nothing to go around.

**Comment by bhuiyanmobasshir94** [comment]
I started working on the latest Minio version on my windows server. So I have a bucket that I use for sharing the downloadable files. When I go to the sharable link for the file, I always find a different IP address than my server's actual IP address (maybe the private one) and if I substitute the IP in the provided link with my public IP of the server it shows an error on the browser. 

![image](https://user-images.githubusercontent.com/31741188/128957050-40572248-73c9-42df-9f51-0b4af535b3fe.png)

Here is the error from the browser when I substitute my server IP with provided IP in the link -  

![image](https://user-images.githubusercontent.com/31741188/128957182-77e805b6-ce04-4ac0-8a9c-e0607eac1f0f.png)

I am using a Windows Server on the Amazon Ec2 instance.

**Comment by harshavardhana** [comment]
> I started working on the latest Minio version on my windows server. So I have a bucket that I use for sharing the downloadable files. When I go to the sharable link for the file, I always find a different IP address than my server's actual IP address (maybe the private one) and if I substitute the IP in the provided link with my public IP of the server it shows an error on the browser.
> 
> ![image](https://user-images.githubusercontent.com/31741188/128957050-40572248-73c9-42df-9f51-0b4af535b3fe.png)
> 
> Here is the error from the browser when I substitute my server IP with provided IP in the link -
> 
> ![image](https://user-images.githubusercontent.com/31741188/128957182-77e805b6-ce04-4ac0-8a9c-e0607eac1f0f.png)
> 
> I am using a Windows Server on the Amazon Ec2 instance.

You need to set MINIO_SERVER_URL to generate presigned for right endpoint.

**Comment by bhuiyanmobasshir94** [comment]
Thank you so much for your information.

**Comment by sugniii** [comment]
> > 我开始在我的 Windows 服务器上使用最新的 Minio 版本。所以我有一个用于共享可下载文件的存储桶。当我转到文件的可共享链接时，我总是找到与服务器实际 IP 地址不同的 IP 地址（可能是私有地址），如果我将提供的链接中的 IP 替换为服务器的公共 IP，它会显示一个浏览器上的错误。
> > ![图像](https://user-images.githubusercontent.com/31741188/128957050-40572248-73c9-42df-9f51-0b4af535b3fe.png)
> > 当我用链接中提供的 IP 替换我的服务器 IP 时，这是来自浏览器的错误 -
> > ![图像](https://user-images.githubusercontent.com/31741188/128957182-77e805b6-ce04-4ac0-8a9c-e0607eac1f0f.png)
> > 我在 Amazon Ec2 实例上使用 Windows Server。
> 
> 您需要设置 MINIO_SERVER_URL 以生成正确端点的预签名。

是否可以给个例子?

**Comment by klauspost** [comment]
@sugniii You cannot just change the IP. That is part of the signature.

Use the `--address=1.2.3.4:9000` (change to the IP you want) parameter.

To set MINIO_SERVER_URL, you can use `SET MINIO_SERVER_URL=minio.mydomain.com` on Windows which reflects your public IP. Consult your OS documentation.

**Comment by sugniii** [comment]
> @sugniii您不能只更改 IP。这是签名的一部分。
> 
> 使用`--address=1.2.3.4:9000`（更改为您想要的 IP）参数。
> 
> 要设置 MINIO_SERVER_URL，您可以`SET MINIO_SERVER_URL=minio.mydomain.com`在反映您的公共 IP 的 Windows 上使用。请查阅您的操作系统文档。

老哥,稳,是否留个联系方式像您讨教一下?
我记得之前旧版本的点击分享后的链接在浏览器打开是可以直接展示的,为什么现在都是直接弹窗下载?

**Comment by sugniii** [comment]
> @sugniii您不能只更改 IP。这是签名的一部分。
> 
> 使用`--address=1.2.3.4:9000`（更改为您想要的 IP）参数。
> 
> 要设置 MINIO_SERVER_URL，您可以`SET MINIO_SERVER_URL=minio.mydomain.com`在反映您的公共 IP 的 Windows 上使用。请查阅您的操作系统文档。

command: server --address ":9000" --console-address ":9001" http://minio{1...4}/data
并且设置了环境变量MINIO_SERVER_URL: http://192.168.0.3:9000
启动后四个docker节点没有报错,但是控制面板无法登录,
已确定账号密码正确.

**Comment by sugniii** [comment]
> @sugniii You cannot just change the IP. That is part of the signature.
> 
> Use the `--address=1.2.3.4:9000` (change to the IP you want) parameter.
> 
> To set MINIO_SERVER_URL, you can use `SET MINIO_SERVER_URL=minio.mydomain.com` on Windows which reflects your public IP. Consult your OS documentation.

谢谢您 | thanks you,我之前不知道错误设置了什么导致用您说的的方式后无法使用,后面还原到最初的时候再尝试后可以了,
还有那个弹窗直接下载的问题我也发现了,是我愚蠢了,未去设置它的content-type
还是很感谢.

**Comment by bhuiyanmobasshir94** [comment]
@harshavardhana I tried to set MINIO_SERVER_URL with my Amazon EC2 public Ip/domain address but I couldn't log in then but when I unset this environment variable I can log in to the console. And you know without going into the console we can't get a sharable link.

My purpose is to share a file to the public to download using my public Ip/dns.

**Comment by Chu-Te-Ethan-Chen** [comment]
@bhuiyanmobasshir94 
Hi, I encountered the same problem like you and I found out a solution that might works. [reproduction link](https://github.com/Jordon-Chen/minio-docker-compose)
Just add `MINIO_BROWSER_REDIRECT_URL` and `MINIO_SERVER_URL` in the docker-compose.yaml.

```
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    ......
    MINIO_BROWSER_REDIRECT_URL: http://localhost:9001 # https://console.minio.example.net
    MINIO_SERVER_URL: http://localhost:9000 # https://minio.example.net
```

reference:
- [Deploy MinIO on Docker Compose](https://docs.min.io/docs/deploy-minio-on-docker-compose)
- [Reminder from minio](https://github.com/minio/minio/blob/master/README.md#things-to-consider)
