### ISSUE TITLE
Env. Variable MINIO_PROMETHEUS_URL not usable for distributed multi tenant cluster

### ISSUE THREAD

**Issue by ghost** [minio/minio#12891]
Each tenant/instance of minio in a distributed cluster setup should only see its own metrics.

A prometheus instance scrapes with different jobs the metrics from different tenants and than it is not possible to set a variable per each minio tenant/instance so that a tenant/instance can only see its own metrics.

It is not possible with setting the environment variable "MINIO_PROMETHEUS_URL" like described here: https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/minio-metrics-and-alerts.html

**Comment by harshavardhana** [comment]
This is only needs to be set for Prometheus URL there is also JOB_ID that can be set.

Please explain your setup there is nothing to go about in your issue report.

**Comment by ghost** [comment]
With prometheus we scrape metrics from 3 tenants from our distributed minio cluster. So i have 3 jobs. If i set now the prometheus url and the job_id in our example for "minio-dmm", this is set for all tenants in the cluster isn't? because it is a system variable and every instance will check if this variable is set and so also all the other instances will show the metrics from this specific "minio-dmm" instead of their own for example "minio-es".

![prometheus](https://user-images.githubusercontent.com/38687952/128472880-0e0b50d5-842f-430f-813c-07f6d391586f.jpg)

**Comment by harshavardhana** [comment]
> With prometheus we scrape metrics from 3 tenants from our distributed minio cluster. So i have 3 jobs. If i set now the prometheus url and the job_id in our example for "minio-dmm", this is set for all tenants in the cluster isn't? because it is a system variable and every instance will check if this variable is set and so also all the other instances will show the metrics from this specific "minio-dmm" instead of their own for example "minio-es".
> 
> ![prometheus](https://user-images.githubusercontent.com/38687952/128472880-0e0b50d5-842f-430f-813c-07f6d391586f.jpg)

Correct set two variables to get the dashboard 

- MINIO_PROMETHEUS_URL
- MINIO_PROMETHEUS_JOB_ID (when you have non default job_id)
