### ISSUE TITLE
Delete selected button in Object browser in Minio Console doesn't remove empty folder instead removes other files 

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [minio/minio#12896]
## Expected Behavior

It should remove empty folders 

## Current Behavior

Removes all files beside empty folders

## Context

I have an test bucket with following files
![image](https://user-images.githubusercontent.com/65945812/128478683-04020e7a-60b9-4ec0-ae59-4ab998c05ce2.png)
 When I am hitting `Delete Selected` button I see following 
![image](https://user-images.githubusercontent.com/65945812/128478984-da215a71-afda-4b4a-a819-8b080a31fabd.png)
On the other side Here is what I see in server side 
![image](https://user-images.githubusercontent.com/65945812/128479736-064c8d80-eb2c-4345-8f45-d694d795ee72.png)
![image](https://user-images.githubusercontent.com/65945812/128480156-8c472331-4e7c-45fe-bb9d-45f68996afc2.png)

As it seems files are still there.
This is a 12 node setup with 4 parity and 8 data blocks. 

This folders are empty.
one of them created in Object Browser directly, another one from alpine container using s3fs, I dont think that was the problem but anyway.
Also How can I access to old UI/object browser
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by vadmeste** [comment]
> Version used (minio --version):

I believe this is already fixed and released, could you try with the recent release ? please reopen this issue if you still see it.
