### ISSUE TITLE
The default accessKey and secretKey counter with "unauthorized" error

### ISSUE THREAD

**Issue by prchanda** [minio/minio#12905]
### Discussed in https://github.com/minio/minio/discussions/12674

<div type='discussions-op-text'>

I am facing the same issue in Windows 10 host. Here is the windows version I am using:

![image](https://user-images.githubusercontent.com/35064849/128606644-b26ca85c-586c-4f0c-8916-ef493da4a5ab.png)

The version of minio.exe is：
![image](https://user-images.githubusercontent.com/35064849/128606675-0f30878d-c47d-4760-9330-537fe3d15206.png)

Using the following command to start minio.exe:
![image](https://user-images.githubusercontent.com/35064849/128607004-5230e8d8-8a06-4ec6-9ba8-62a08a0c1072.png)

Opened the browser and accessed the url http://127.0.0.1:9080/login to login with custom user credentials. Getting 401 error:
![image](https://user-images.githubusercontent.com/35064849/128607091-93399949-160d-4a3f-96fb-74d2da5a0d43.png)
![image](https://user-images.githubusercontent.com/35064849/128607147-f34662ac-2fda-4091-9c0b-7f15703404cb.png)

</div>

**Comment by parthibd** [comment]
Same here.
