### ISSUE TITLE
DELETE markers not replicated during resync

### ISSUE THREAD

**Issue by hkirov** [minio/minio#12919]
With Two-Way Server-Side Bucket Replication setup replication works fine. Objects and DELETE markers are getting replicated correctly. We have network and hardware issues in the past as a result some objects reside only on one of the sites with COMPLETED status. To get them re-replicated we issued `mc replicate resync` on both sites at 22:00. Markers for objects deleted between 2200 and 0100 are missing on the other site. Markers for objects deleted before 2200 or after 0100 were replicated correctly.

## Expected Behavior

DELETE markers to be replicated normally

## Current Behavior

markers for deleted objects during resync are not replicated.

## Steps to Reproduce (for bugs)

1. configure Two-Way Server-Side Bucket Replication with `--replicate "delete,delete-marker,existing-objects"`
2. upload enough data to the bucket
3. run `mc replicate resync` on both clusters
4. delete some objects before during resync
5. check object status on both clusters after resync

## Your Environment

* Version used (`minio --version`):  Version: 2021-08-05T22:01:19Z
* Server setup and configuration: two baremetal clusters with 5 nodes each
* Operating System and version (`uname -a`): Linux tafl-serv1 5.4.0-74-generic 83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by poornas** [comment]
>We have network and hardware issues in the past as a result some objects reside only on one of the sites with COMPLETED status. 

This is odd - replication status is marked as `COMPLETED` only after the version is replicated to other site, otherwise it will remain in `PENDING` or `FAILED` state until the scanner visits these object versions and re-queues them for retry. There should be no reason to use `resync` command unless the other site is lost and you are bringing up a new cluster in its place.

Having said that, if a delete marker or version permanent deletion is pending replication - you should be able to see the status with `mc stat --vid xxx  --debug alias/bucket/object` which will report additional headers like `X-Minio-Replication-DeleteMarker-Status` or `X-Minio-Replication-Delete-Status` with Pending/Failed status if it is not yet sync'd. Both the `resync` and regular healing of replication failures happens when the scanner visits these objects and they get picked for re-queuing - depending on the size of your namespace, this may take a while. 

Can you paste the output of `mc stat --debug --vid ` on a delete marker version that has not yet replicated?

**Comment by hkirov** [comment]
> > We have network and hardware issues in the past as a result some objects reside only on one of the sites with COMPLETED status.
> 
> This is odd - replication status is marked as `COMPLETED` only after the version is replicated to other site, otherwise it will remain in `PENDING` or `FAILED` state until the scanner visits these object versions and re-queues them for retry. There should be no reason to use `resync` command unless the other site is lost and you are bringing up a new cluster in its place.

At the time there was minio issue too which changed status to 'COMPLETED' from 'FAILED' without completing the replication. It was fixed in #12726 I think. However this is past.

> Having said that, if a delete marker or version permanent deletion is pending replication - you should be able to see the status with `mc stat --vid xxx --debug alias/bucket/object` which will report additional headers like `X-Minio-Replication-DeleteMarker-Status` or `X-Minio-Replication-Delete-Status` with Pending/Failed status if it is not yet sync'd. Both the `resync` and regular healing of replication failures happens when the scanner visits these objects and they get picked for re-queuing - depending on the size of your namespace, this may take a while.
> 
> Can you paste the output of `mc stat --debug --vid ` on a delete marker version that has not yet replicated?

Here is it:
> mc ls --versions us/content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4
> [2021-08-07 13:28:16 EEST]  61MiB 4ee0e306-2de8-4fdb-a7e8-8188a7c08070 v1 PUT f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4

>mc ls --versions nl/content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4
>[2021-08-09 22:42:51 EEST]     0B c1196e07-152c-4ded-9368-cce8a94d25a9 v2 DEL f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4
>[2021-08-07 13:28:16 EEST]  61MiB 4ee0e306-2de8-4fdb-a7e8-8188a7c08070 v1 PUT f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4

>mc stat --debug --vid c1196e07-152c-4ded-9368-cce8a94d25a9 nl/content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4
mc: <DEBUG> GET /content/?location= HTTP/1.1
Host: nl.webvideocore.net:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-07-27T06-46-19Z
Authorization: AWS4-HMAC-SHA256 Credential=oLzWhKNZHY8p/20210810/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210810T200135Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 10 Aug 2021 20:01:35 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 169A0A710BAB6D9A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: GB
mc: <DEBUG>  >> Organization: Sectigo Limited
mc: <DEBUG>  >> Expires: 2022-05-26 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: The USERTRUST Network
mc: <DEBUG>  >> Expires: 2030-12-31 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: GB
mc: <DEBUG>  >> Organization: Comodo CA Limited
mc: <DEBUG>  >> Expires: 2028-12-31 23:59:59 +0000 UTC
mc: <DEBUG> Response Time:  180.063287ms

mc: <DEBUG> HEAD /content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4?versionId=c1196e07-152c-4ded-9368-cce8a94d25a9 HTTP/1.1
Host: nl.webvideocore.net:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-07-27T06-46-19Z
Authorization: AWS4-HMAC-SHA256 Credential=oLzWhKNZHY8p/20210810/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210810T200135Z

mc: <DEBUG> HTTP/1.1 405 Method Not Allowed
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Tue, 10 Aug 2021 20:01:35 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Delete-Marker: true
X-Amz-Request-Id: 169A0A710E76A8A0
X-Amz-Version-Id: c1196e07-152c-4ded-9368-cce8a94d25a9
X-Content-Type-Options: nosniff
X-Minio-Replication-Delete-Status: COMPLETE
X-Minio-Replication-Deletemarker-Status: REPLICA
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: GB
mc: <DEBUG>  >> Organization: Sectigo Limited
mc: <DEBUG>  >> Expires: 2022-05-26 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: The USERTRUST Network
mc: <DEBUG>  >> Expires: 2030-12-31 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: GB
mc: <DEBUG>  >> Organization: Comodo CA Limited
mc: <DEBUG>  >> Expires: 2028-12-31 23:59:59 +0000 UTC
mc: <DEBUG> Response Time:  77.814065ms

mc: <DEBUG> GET /content/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=screenrec_videos%2Ff_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4 HTTP/1.1
Host: nl.webvideocore.net:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-07-27T06-46-19Z
Authorization: AWS4-HMAC-SHA256 Credential=oLzWhKNZHY8p/20210810/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210810T200135Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 349
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 10 Aug 2021 20:04:39 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 169A0A71132D7B29
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: GB
mc: <DEBUG>  >> Organization: Sectigo Limited
mc: <DEBUG>  >> Expires: 2022-05-26 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: The USERTRUST Network
mc: <DEBUG>  >> Expires: 2030-12-31 23:59:59 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: GB
mc: <DEBUG>  >> Organization: Comodo CA Limited
mc: <DEBUG>  >> Expires: 2028-12-31 23:59:59 +0000 UTC
mc: <DEBUG> Response Time:  3m3.41300272s

mc: <ERROR> Unable to stat `nl/content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4`. 405 Method Not Allowed
 (2) stat-main.go:130 cmd.parseAndCheckStatSyntax(..) Tags: [nl/content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4]
 (1) client-url.go:199 cmd.url2Stat(..) Tags: [nl/content/screenrec_videos/f_zyIKFVl90iX2RN5tOYGMqxk7HbrQZ4vd.mp4]
 (0) client-s3.go:1499 cmd.(*S3Client).getObjectStat(..)
 Release-Tag:RELEASE.2021-07-27T06-46-19Z | Commit:addaf66de8af | Host:anduril | OS:linux | Arch:amd64 | Lang:go1.16.6 | Mem:1.9 MB/75 MB | Heap:1.9 MB/67 MB.

**Comment by hkirov** [comment]
Successfully replicated markers have no X-Minio-Replication-Delete-Status, just `X-Minio-Replication-Deletemarker-Status: COMPLETED` or `X-Minio-Replication-Deletemarker-Status: REPLICA`

Here are stats for such markers:
[okstat-debug-vid.txt](https://github.com/minio/minio/files/6964471/okstat-debug-vid.txt)

**Comment by poornas** [comment]
Was able to repro this issue,  resyncing replication on both sides of active active replication at the same time can cause previously replicated delete marker to get permanently deleted. We will need to introduce overhead of an extra stat to check if delete marker version is present before attempting to send a delete replication request to allow for this type of resync. 

@hkirov, will send a fix  - btw you would only see `X-Minio-Replication-Deletemarker-Status` when delete marker is replicated. `X-Minio-Replication-Delete-Status` will be seen in the headers only when a versioned delete of deletemarker is in progress.
