### ISSUE TITLE
Can you provide the jar package of org.apache.hadoop.spark.hadoop.fs.s3a.S3AFileSystem?

### ISSUE THREAD

**Issue by liergou99** [minio/minio#12918]
I only found org.apache.hadoop.fs.s3a.S3AFileSystemin hadoop-aws-***.jar, but I didn't find the jar package of org.apache.hadoop.spark.hadoop.fs.s3a.S3AFileSystem

**Comment by balamurugana** [comment]
Why is this issue here?
