### ISSUE TITLE
Dropshare: An object already exists as your prefix, choose a different prefix to proceed

### ISSUE THREAD

**Issue by tjosten** [minio/minio#1291]
Dropshare has the optional capability to create so-called landing pages for uploads (example: http://dsh.re/4c6b5).

In the S3 bucket, the files will be created as follows:
- Screen-Shot-2016-04-05-09-54-49-qatYXznMAz (HTML file)
- Screen-Shot-2016-04-05-09-54-49-qatYXznMAz/Screen-Shot-2016-04-05-09-54-49.png (Actual file)

This virtual folder structure is important, because it contains the optional obfuscation part (-qatYXznMAz) whereas the actual file does not (so the filename looks nice).

In the landing page HTML file, the actual file (in case it is an image) is referenced like this:

`<img src="/Screen-Shot-2016-04-05-10-41-10-nu6MF4ZcSr/Screen-Shot-2016-04-05-10-41-10.png" />`

This works fine with Amazon S3, OpenStack Swift and DreamObjects (and any other S3 compatible service we have tested).

minio however denies the upload of the actual file with the error response HTTP 409:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ObjectExistsAsPrefix</Code><Message>An object already exists as your prefix, choose a different prefix to proceed.</Message><Key></Key><BucketName></BucketName><Resource>/dropshare/Screen-Shot-2016-04-05-09-54-49-qatYXznMAz/Screen-Shot-2016-04-05-09-54-49.png</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

**Comment by krishnasrinivas** [comment]
if you create an object `Screen-Shot-2016-04-05-09-54-49-qatYXznMAz`, at the backend it will create a file with name `Screen-Shot-2016-04-05-09-54-49-qatYXznMAz`, now if you try to create object `Screen-Shot-2016-04-05-09-54-49-qatYXznMAz/Screen-Shot-2016-04-05-09-54-49.png`, minio will try to create the directory `Screen-Shot-2016-04-05-09-54-49-qatYXznMAz/` and fail as a file already exists with that name

**Comment by harshavardhana** [comment]
> Dropshare has the optional capability to create so-called landing pages for uploads (example: http://dsh.re/4c6b5).
> 
> In the S3 bucket, the files will be created as follows:
> 
> Screen-Shot-2016-04-05-09-54-49-qatYXznMAz (HTML file)
> Screen-Shot-2016-04-05-09-54-49-qatYXznMAz/Screen-Shot-2016-04-05-09-54-49.png (Actual file)

This style of approach is good for all flat namespace environment but it is not suitable for Filesystem / POSIX backends.  The tradeoff we choose is already explained by @krishnasrinivas. 

The problem with having file structure like this is not being able to copy out this data to local fs - or perhaps need to have tools which write copy data back in a custom format. 

Will keep the bug open for future debates on this, but for now we are relying on POSIX namespace.

**Comment by jariangibson** [comment]
Was going to try out Minio with Dropshare.  Glad I found this. Bummer.

**Comment by jariangibson** [comment]
So did some testing on this.  I get error 409 from Dropshare client.  Error is request failed: conflict (409).  Seeing same backend issues in Minio bucket.

**Comment by tjosten** [comment]
Yes, this is exactly what has been explained above.

**Comment by patrikarvidsson** [comment]
For what it matters, +1 on this.

**Comment by yauh** [comment]
Sorry to see this unsupported still but I understand the technical reasoning behind it. This makes it behave considerably different to S3. Would love to see it fixed sometime in the future. 
For what it's worth, maybe I was lured in by the marketing claims on the min.io website where it says

> MinIO is the defacto standard for S3 compatibility

**Comment by tjosten** [comment]
Update from my side: Minio will be natively supported by Dropshare with the next update, I have worked around the POSIX Filesystem issue described above and received frequent feedback to add Minio in the last months, so there we go…
