### ISSUE TITLE
Access Keys and Secret Keys Not Working in Docker Container

### ISSUE THREAD

**Issue by CUCraigT** [minio/minio#12922]
Access Keys and Secret Keys Not Working in Docker Container. I am mapping a secret_key and access_key file into the container and mapping them to the appropriate ENV vars, but it does not create those access keys/users.

## Expected Behavior

Access keys/users should be created in the system but nothing is happening.

## Current Behavior

Root user and password work when passed as ENV vars to the container, but nothing else is created. They ARE being set as ENV vars within the container. I get no errors; just nothing happens.

Docker container with Minio version: `minio version RELEASE.2021-08-05T22-01-19Z`

![image](https://user-images.githubusercontent.com/16640818/128896524-a57c4cfb-83a0-4802-adcb-e8068d91fde1.png)

## Possible Solution
Have a way to create the access keys, secret keys, and ideally tie them to a policy all programmatically with containers.

## Steps to Reproduce (for bugs)

1. Here is the command I am using to start my Docker container locally:
```
docker run -p 9000:9000 -p 9001:9001 -v /mydirectory/keys:/keys -e "MINIO_ROOT_USER=minioadmin" -e "MINIO_ROOT_PASSWORD=Password" -e "MINIO_ACCESS_KEY_FILE=/keys/access_key" -e "ACCESS_KEY_FILE=/keys/access_key" -e "SECRET_KEY_FILE=/keys/secret_key" minio/minio server /mnt/data --console-address :9001
```

2. `printenv` from within the container:
```
MINIO_ACCESS_KEY_FILE=/keys/access_key
ACCESS_KEY_FILE=/keys/access_key
LANG=C.utf8
HOSTNAME=410c42dd45e0
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_ROOT_USER=minioadmin
container=oci
PWD=/
HOME=/root
TERM=xterm
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD=Password
MINIO_ROOT_PASSWORD_FILE=secret_key
SECRET_KEY_FILE=/keys/secret_key
SHLVL=1
MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
MINIO_SECRET_KEY_FILE=secret_key
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_CONFIG_ENV_FILE=config.env
_=/usr/bin/printenv
```

3. Go look at the users in the GUI (not there)
4. I also tried using aws s3 cli to connect and get `An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The Access Key Id you provided does not exist in our records.`

## Context

We really love the GUI and configuration that MinIO provides, and we need to run it within a container (small deployment ultimately within Kubernetes). However, we also want to be able to spin it up quickly from a manifest file utilizing secrets already defined. Those are then used within our application and to set the user within MinIO. It looks like you used to be able to do this, and I can do this with another solution, but we do like and want the web GUI of MinIO

## Regression

Possibly, but I have never been able to get it to work

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-08-05T22-01-19Z`
* Server setup and configuration: Mac with Docker Desktop
* Operating System and version (`uname -a`): Mac `20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

**Comment by harshavardhana** [comment]
Root credentials are not regular users not sure what is the issue here so they are not visible from the "users" section in the console UI, you haven't created any new users. 

Not sure what you are expecting to work.

**Comment by CUCraigT** [comment]
> Root credentials are not regular users not sure what is the issue here so they are not visible from the "users" section in the console UI, you haven't created any new users.
> 
> Not sure what you are expecting to work.

The root user is fine. The user specified in the access_key and secret_key file is not created as a normal user. Contents of those files (using the documented creds for an example):
```
[root@9fa6779e0751 /]# cat keys/access_key 
AKIAIOSFODNN7EXAMPLE
[root@9fa6779e0751 /]# cat keys/secret_key 
wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

**Comment by harshavardhana** [comment]
> The root user is fine. The user specified in the access_key and secret_key file is not created as a normal user. Contents of those files (using the documented creds for an example):

That is never documented that it will create a normal user @CUCraigT `MINIO_ACCESS_KEY` is a legacy environment variable that was replaced by MINIO_ROOT_USER

Now if you set both MINIO_ROOT_USER overrides MINIO_ACCESS_KEY that's all. To create a user you need to use `mc admin user add`  not using environment variables.

**Comment by CUCraigT** [comment]
> > The root user is fine. The user specified in the access_key and secret_key file is not created as a normal user. Contents of those files (using the documented creds for an example):
> 
> That is never documented that it will create a normal user @CUCraigT `MINIO_ACCESS_KEY` is a legacy environment variable that was replaced by MINIO_ROOT_USER
> 
> Now if you set both MINIO_ROOT_USER overrides MINIO_ACCESS_KEY that's all. To create a user you need to use `mc admin user add` not using environment variables.

Got it. Thanks. Just some confusion here (https://docs.min.io/docs/minio-docker-quickstart-guide.html) with the terms Access Key and Secret Key. Assumed that was like AWS used them for the users vs. the root user. Appreciate the follow up, and I will script it in a startup script with `mc admin user add`.
