### ISSUE TITLE
Anonymous Bucket accesing via Browser(MinIO Console)

### ISSUE THREAD

**Issue by dboc** [minio/minio#12923]
Hi,

I notice that the MinIO Console does not have the same behavior as old MinIO Browser when accessing anonymous bucket.

I have an old MinIO release whit MinIO Browser on, the final user can access via browser anonymously the bucket content.

I made how to reproduce the behavior in an Old Version, and the missbehavior in the latest version.

My Question is: is it a bug? 

## Expected Behavior

Acessing anonymously a bucket in MinIO Console and show the content

## Current Behavior

Acessing anonymously a bucket in MinIO Console make an erro and do not show anything

## Possible Solution

Looking how the old MinIO Browser did it

## Steps to Reproduce (for bugs)

Anonymous Bucket(MinIO Brownser) - RELEASE.2021-08-05T22-01-19Z

MINIO_ROOT_USER 	mysecret-OLD-duser
MINIO_ROOT_PASSWORD 	mysecret-OLD-password
command = minio gateway nas /export

`mc admin info old-minio`
```
●  old-minio.k8s.my.domain
   Uptime: 23 hours
   Version: 2021-06-17T00:10:46Z
```

`mc anonymous set public old-minio/public`
```
Access permission for `old-minio/public` is set to `public
```

`mc anonymous get old-minio/public`
```
Access permission for `old-minio/public` is `public`
```

Accessing via Browser(Chrome)

http://old-minio.k8s.my.domain/minio/public

![image](https://user-images.githubusercontent.com/7704278/128912752-6cf71540-a547-46ea-afa2-821f6d0e26bc.png)

Anonymous Bucket(MinIO Console) -  RELEASE.2021-08-05T22-01-19Z

MinIO with MinIO Console Interface -
MINIO_ROOT_USER 	mysecret-NEW-user
MINIO_ROOT_PASSWORD 	mysecret-NEW-password
MINIO_BROWSER_REDIRECT_URL 	http://new-minio.k8s.my.domain

command = minio gateway nas /export --console-address ":9001"

`mc admin info new-minio`
```
●  new-minio-s3.k8s.my.domain
   Uptime: 1 minute
   Version: 2021-08-05T22:01:19Z
```

`mc anonymous set public new-minio/public`
```
Access permission for `new-minio/public` is set to `public
```

`mc anonymous get new-minio/public`
```
Access permission for `new-minio/public` is `public`
```

Accessing via Browser(Chrome)
* new-minio.k8s.my.domain - console URL

http://new-minio.k8s.my.domain/object-browser/public

![image](https://user-images.githubusercontent.com/7704278/128913070-b77b0e3b-5044-4f73-be36-57a20d11e046.png)

Output Brownser Console:

```
The resource from “http://new-minio.k8s.my.domain/object-browser/styles/root-styles.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
The resource from “http://new-minio.k8s.my.domain/object-browser/static/css/main.8cfac526.chunk.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
The resource from “http://new-minio.k8s.my.domain/object-browser/static/js/2.147ecdb8.chunk.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
The resource from “http://new-minio.k8s.my.domain/object-browser/static/js/main.30880e75.chunk.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
The resource from “http://new-minio.k8s.my.domain/object-browser/static/css/2.60e04a19.chunk.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
The resource from “http://new-minio.k8s.my.domain/object-browser/static/js/2.147ecdb8.chunk.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
Loading failed for the <script> with source “http://new-minio.k8s.my.domain/object-browser/static/js/2.147ecdb8.chunk.js”. public:1:1
The resource from “http://new-minio.k8s.my.domain/object-browser/static/js/main.30880e75.chunk.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). public
Loading failed for the <script> with source “http://new-minio.k8s.my.domain/object-browser/static/js/main.30880e75.chunk.js”. public:1:1
```
## Regression

Yes, it is a regression:
Version working:  RELEASE.2021-08-05T22-01-19Z (MinIO Browser)
Version not working: RELEASE.2021-08-05T22-01-19Z(MinIO Console)

## Your Environment

* Version used (`minio --version`):
Version working:  RELEASE.2021-08-05T22-01-19Z (MinIO Browser)
Version not working: RELEASE.2021-08-05T22-01-19Z(MinIO Console)
* Server setup and configuration:
Look at the section Steps to Reproduce (for bugs)
* Operating System and version (`uname -a`):
container:
Version working:
`uname -a`
```
Linux old-minio-hm-75c4c4757-5wvfs 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Version not working:
`uname -a`
```
Linux minio-hm-cc54fd856-ljfdd 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
Anonymous buckets are not supported anymore @dboc - you want to have a UI for anonymous buckets you need to build this yourself. 

This is a breaking change mentioned in the release notes.  We may try to do it in future, but for now this is not something we are planning to do.
