### ISSUE TITLE
Receive 403 Forbidden when making request to signed url with Content-Type header in request.

### ISSUE THREAD

**Issue by gregoryper** [minio/minio#12924]
I generate presigned url using AWSSDK in C# for binary file in S3 bucket.

When I make request to this url and specify Content-Type in request (in C#/Javascript..) I receive Http 403 Forbidden with this error:

<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>folder/somefile.msi</Key><BucketName>my-bucket</BucketName><Resource>/my-bucket/folder/somefile.msi</Resource><RequestId>1699FD2F9B75D704</RequestId><HostId>288ec5b1-c10a-4efd-9a18-3ef752d8d2ba</HostId></Error>

If I don't add this header to request then the file is downloaded.
However we have services with deployed code that already using the header that cannot be easily changed.

Why is this happen ? 
The error doesn't make sense because the signature is correct   - because I'm able to download the file without this header.

Maybe there is some configuration needed on our Minio instance ?

**Comment by harshavardhana** [comment]
> When I make request to this url and specify Content-Type in request (in C#/Javascript..) I receive Http 403 Forbidden with this error:

If you can't specify random headers in the request that do not match your original signature. Verify if your code adds content-type as part of signed headers. If it is added as signed headers then you need to make sure to match that correctly. 

If you want to customize a differ content-type you should use `response-content-type` query param to customize the content-type returned by server.

Also please provide more detailed issue reporting - your issue reporting lacks basic etiquette that should be followed for open source projects

- No MinIO build version specified
- No reproducer specified
- No other environment-related settings specified 

This as vague as it can get, closing this issue until more information is presented.
