### ISSUE TITLE
Login fails using TLS

### ISSUE THREAD

**Issue by Varstahl** [minio/minio#12920]
Providing root user/pass through environment doesn't work if minio find certificates and is accessed via HTTPS

## Current Behavior

When using TLS with the correct user and password, login returns `{"code":401,"detailedMessage":"invalid Login","message":"invalid Login"}`

![image](https://user-images.githubusercontent.com/284077/128874017-f2d26845-4b2c-4430-8f38-3ecb79df8f38.png)

## Steps to Reproduce (for bugs)

1. place certificates in `/etc/minio/certs`
2. runs with HTTPS and login fails
3. delete/rename certificates
4. successful login

## Your Environment

* Version used (`minio --version`): RELEASE.2021-08-05T22-01-19Z
* Operating System and version (`uname -a`): Linux 5.4.0-80-generic # 90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Systemd script:
```
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
Environment="MINIO_ACCESS_KEY=—"
Environment="MINIO_VOLUMES=/usr/local/share/minio/"
Environment="MINIO_OPTS=-C /etc/minio --address 0.0.0.0:9000 --console-address :9001"
Environment="MINIO_SECRET_KEY=—"
Environment="MINIO_ROOT_USER=—"
Environment="MINIO_ROOT_PASSWORD=—"

WorkingDirectory=/usr/local/

User=minio
Group=minio

ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"

ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

Restart=always
LimitNOFILE=65536
TasksMax=infinity
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```

**Comment by harshavardhana** [comment]
@Varstahl do your certs have the IP of the hostname? If they are not added you should make sure to set 

MINIO_SERVER_URL=https://minio-domain:9000

**Comment by Varstahl** [comment]
That was it, I was reading the TLS documentation and the line in the Readme slipped by me, my bad.

**Comment by Heshmatkhah** [comment]
Hi,
I can't find anything about `MINIO_SERVER_URL`  nither in [MinIO Server Config Guide](https://docs.min.io/docs/minio-server-configuration-guide.html) or [How to secure access to MinIO server with TLS](https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html) or [Generate Let's Encrypt certificate using Certbot for MinIO](https://docs.min.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio)
There is no documentation for this option in the current version documentations.
Would you please add this to the documentations?

**Comment by harshavardhana** [comment]
> Hi,
> I can't find anything about `MINIO_SERVER_URL` nither in [MinIO Server Config Guide](https://docs.min.io/docs/minio-server-configuration-guide.html) or [How to secure access to MinIO server with TLS](https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html) or [Generate Let's Encrypt certificate using Certbot for MinIO](https://docs.min.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio)
> There is no documentation for this option in the current version documentations.
> Would you please add this to the documentations?

https://github.com/minio/minio#test-minio-connectivity it's available in the first page.

**Comment by rrossouw01** [comment]
thanks @harshavardhana for me this worked for console login when using https with self-signed cert.

docker run -d -p 9000:9000 -p 9001:9001 --name minio1 -v /TANK/MINIO-REPO:/data -e "MINIO_ROOT_USER=<redacted>" -e "MINIO_ROOT_PASSWORD=<redacted>" **_-e MINIO_SERVER_URL="https://192.168.1.112:9000"_** -v /home/rrosso/.minio/certs/:/tmp/certs quay.io/minio/minio server /data --console-address ":9001" --certs-dir /tmp/certs
