### ISSUE TITLE
How do i add multiple hard drives to minio?

### ISSUE THREAD

**Issue by abipal15** [minio/minio#1292]
I have a storage server with 12 TB capacity. 

/dev/sda1 2TB
/dev/sda2 2TB
/dev/sda3 2TB
/dev/sda4 2TB
 ...

I want to allocate all drives to minio instance. How do I do it?

**Comment by krishnasrinivas** [comment]
Right now multi-disk/multi-node minio server is under development.
However single disk minio server is already ready to use, you can combine the 6 disks using [LVM](https://en.wikipedia.org/wiki/Logical_Volume_Manager_%28Linux%29) and run minio on top of the virtual disk.

**Comment by harshavardhana** [comment]
Will be fixed by #1319

**Comment by harshavardhana** [comment]
master branch now has multiple drive support for single server.
