### ISSUE TITLE
Using self-signed certificate doesn't work

### ISSUE THREAD

**Issue by torarnv** [minio/minio#1293]
Using certificate and key produced by https://golang.org/src/crypto/tls/generate_cert.go

Gives

`Put https://localhost:9000/my-bucket/: x509: certificate signed by unknown authority`

When trying to create a bucked in the web UI.

I'm assuming this is because minio only trusts certs signed by one of the root CA in the system. I could install my generated cert as a trusted root cert system-wide, but that would only fix the issue for minio's web UI. Any client that would connect to minio would also need this system wide root cert.

Edit: Even after trusting the cert system-wide on OSX (which makes chrome eg. not warn when visiting https://localhost:9000), it still gives the error

Not sure how to fix it :/

**Comment by harshavardhana** [comment]
> Gives
> 
> Put https://localhost:9000/my-bucket/: x509: certificate signed by unknown authority
> 
> When trying to create a bucked in the web UI.

Is this issue valid still @torarnv ?

**Comment by harshavardhana** [comment]
Closing this issue as out of scope. Please reopen if there are SSL related issues.

**Comment by k0nsl** [comment]
Sorry for opening this issue again, but it is in fact relevant.

I am seeing this in my log after I added a Let's Encrypt certificate:

```
2016/09/18 01:57:03 http: TLS handshake error from my_ip:59777: remote error: tls: unknown certificate authority
```

I can access the associated subdomain perfectly via Chromium and Firefox. I don't know what gives.

**Comment by harshavardhana** [comment]
> 2016/09/18 01:57:03 http: TLS handshake error from my_ip:59777: remote error: tls: unknown certificate authority

Can you explain how did you configured Letsencrypt TLS?  - if you have used 'letsencrypt-auto' tool then you need to copy `fullchain.pem` properly file to make sure the CA authority is present properly. 

This can happen so that the aforementioned distribution under use doesn't yet ship the new updated CA authority files as mentioned here - https://github.com/certbot/certbot/issues/2026

Let us know. Thanks for testing Minio @k0nsl

**Comment by k0nsl** [comment]
Thanks for the heads up about copying `fullchain.pem` to `$HOME/.minio/certs`. I had completely overlooked that.

Anyway, I copied it and restarted the Minio server and I'm still seeing that error:

```
2016/09/18 04:27:52 http: TLS handshake error from my_ip:33187: remote error: tls: unknown certificate authority
```

This is barring that I haven't done something incorrectly. Maybe I am not supposed to copy `fullchain.pem` to `$HOME/.minio/certs`?

[EDIT: On the other hand I've successfully got CyberDuck to work with my Minio instance and I can create, edit and delete without problem. Really nice!
The `remote error` above was when I tried to use a backup plugin for WordPress. I really wanted to use Minio as a backup solution for some of my WordPress based blogs.]

**Comment by harshavardhana** [comment]
> Thanks for the heads up about copying fullchain.pem to $HOME/.minio/certs. I had completely overlooked that.

You need to replace `fullchain.pem` to `$HOME/.minio/certs/public.crt` instead from existing file.  Let me know how it goes. 

> [EDIT: On the other hand I've successfully got CyberDuck to work with my Minio instance and I can create, edit and delete without problem. Really nice!
> The remote error above was when I tried to use a backup plugin for WordPress. I really wanted to use Minio as a backup solution for some of my WordPress based blogs.]

Really great to know, happy to help in anyway we can sorry for all the trouble.

**Comment by aniztar** [comment]
Hello @harshavardhana ,
I am reopening this as I am facing the same issue. 

1. I generated certificates using -  [generate_cert.go](https://golang.org/src/crypto/tls/generate_cert.go?m=text).
2. I have renamed the generated pem files to public.cert and private.key and moved them to ~/.minio/certs/

But I am still seeing this issue when i try to create a bucket
`Put https://127.0.0.1:9000/myBucket/: x509: certificate signed by unknown authority`

Also, I am running the minio server using the below instructions found on the website -

```
wget https://dl.minio.io/server/minio/release/linux-amd64/minio
chmod +x minio
./minio server /mnt/data
```

Have I missed something? Or is this a known issue?

**Comment by harshavardhana** [comment]
Yes you need to trust the certs generated by self signed on the client @aniztar

**Comment by aniztar** [comment]
Got it... Thank you

**Comment by senthu-neyan** [comment]
check the system time,
