### ISSUE TITLE
 how to upgrade my minio without the Internet, there is only a LAN

### ISSUE THREAD

**Issue by wuyuan0717** [minio/minio#12935]
**Is your feature request related to a problem? Please describe.**
without the Internet, there is only a LAN,no mirror server

**Describe the solution you'd like**
hope that `mc admin update` supports reading Minio binary files uploaded to the server to update the version

**Describe alternatives you've considered**
upgrade from Source??

**Comment by harshavardhana** [comment]
Download binary and replace the binary - restart server.

https://min.io/download#/linux
