### ISSUE TITLE
Facing issue while upload large(>500MB) file through MinIO SDK

### ISSUE THREAD

**Issue by jaybhusari-bh** [minio/minio#12937]
Facing issue with Multipart upload while uploading large file >500MB

## Expected Behavior

It should be possible to do a multipart upload of a large object in Minio with no errors being thrown.

## Current Behavior

When completing the multipart upload, even if we give file of size 700mbs , still on Minio We see a file of size
515mb which is corrupted with below logs:
API: PutObjectPart(bucket=quad, object=FIle11AugPart2.pdf)
Time: 10:58:37 UTC 08/11/2021
DeploymentID: b68f8947-1ce3-4f16-80af-31b138c30404
RequestID: 169A3A911C6AD185
RemoteHost: 34.218.12.88
Host: cde-dev-image.cde.fullstream.ai
UserAgent: MinIO (Linux; amd64) minio-java/8.0.3
Error: file not found (cmd.StorageErr)
       uploadID=896e6895-6541-4c48-aec6-04bb6ac2f5ea, uploadIDDir=/minio-quad-dev-storage/quad-dev/.minio.sys/multipart/6492b9b7cdecf260e1e79cbab7da635b5fea85d00f4177b38769eef463a63f52/896e6895-6541-4c48-aec6-04bb6ac2f5ea
       1: cmd/fs-v1-multipart.go:94:cmd.(*FSObjects).backgroundAppend()

## Steps to Reproduce (for bugs)

1. Create a large file > 550 mbs.
2. Upload the large file with the S3 Java client. We are using
CreateMultipartUpload(), uploadPart() and completeMultipartUpload() methods of Minio Java SDK to achieve resumable upload of files.
3. We  have setup minio cluster onto Kubernetes in which we are facing issue to upload >500mb files.
The file uploads with the size of 515mbs which is also corrupted.

## Your Environment

* Version used (`minio --version`) Image Tag: RELEASE.2021-06-17T00-10-46Z
* Server setup and configuration: Kubernetes Deployment with nginx/1.21.1(as deployment pod)

**Comment by harshavardhana** [comment]
> 515mb which is corrupted with below logs:
> API: PutObjectPart(bucket=quad, object=FIle11AugPart2.pdf)
> Time: 10:58:37 UTC 08/11/2021
> DeploymentID: b68f8947-1ce3-4f16-80af-31b138c30404
> RequestID: 169A3A911C6AD185
> RemoteHost: 34.218.12.88
> Host: cde-dev-image.cde.fullstream.ai
> UserAgent: MinIO (Linux; amd64) minio-java/8.0.3
> Error: file not found (cmd.StorageErr)
> uploadID=896e6895-6541-4c48-aec6-04bb6ac2f5ea, uploadIDDir=/minio-quad-dev-storage/quad-dev/.minio.sys/multipart/6492b9b7cdecf260e1e79cbab7da635b5fea85d00f4177b38769eef463a63f52/896e6895-6541-4c48-aec6-04bb6ac2f5ea
> 1: cmd/fs-v1-multipart.go:94:cmd.(*FSObjects).backgroundAppend()

what is your backend filesystem here @jaybhusari-bh ?

**Comment by jaybhusari-bh** [comment]
AWS s3 bucket mount to EC2 instance through s3fs

**Comment by harshavardhana** [comment]
> AWS s3 bucket mount to EC2 instance through s3fs

You are trying to run MinIO on top of s3fs?

**Comment by balamurugana** [comment]
@jaybhusari-bh Just use [MinioClient.putObject()](https://minio-java.min.io/io/minio/MinioClient.html#putObject-io.minio.PutObjectArgs-) which does automatic multipart instead of using low level APIs. There is high chance you are using those low level APIs incorrectly.

**Comment by jaybhusari-bh** [comment]
> > AWS s3 bucket mount to EC2 instance through s3fs
> 
> You are trying to run MinIO on top of s3fs?
@harshavardhana  I have deployed minio as kubernetes deployment pods and using k8s persistent volume attached to s3fs mounted s3 bucket to local ec2 instances

**Comment by harshavardhana** [comment]
> > @harshavardhana  I have deployed minio as kubernetes deployment pods and using k8s persistent volume attached to s3fs mounted s3 bucket to local ec2 instances

Unable to understand - i want to know what is the filesystem on the backend directory for MinIO.

**Comment by jaybhusari-bh** [comment]
> @jaybhusari-bh Just use [MinioClient.putObject()](https://minio-java.min.io/io/minio/MinioClient.html#putObject-io.minio.PutObjectArgs-) which does automatic multipart instead of using low level APIs. There is high chance you are using those low level APIs incorrectly.
@balamurugana These scenario is working for our another minio setup where we have directly installed minio client(without kubernetes) 
mc version : RELEASE.2021-02-14T04-28-06Z

**Comment by jaybhusari-bh** [comment]
> > > @harshavardhana  I have deployed minio as kubernetes deployment pods and using k8s persistent volume attached to s3fs mounted s3 bucket to local ec2 instances
> 
> Unable to understand - i want to know what is the filesystem on the backend directory for MinIO.
Below is the data location inside k8s pod(running on ec2 instance)
minio server  /minio-quad-dev-storage/quad-dev/
where this pod location /minio-quad-dev-storage/quad-dev/ is pointed to my local ec2 instance s3fs mount location to my aws s3 bucket

**Comment by harshavardhana** [comment]
> > > > @harshavardhana  I have deployed minio as kubernetes deployment pods and using k8s persistent volume attached to s3fs mounted s3 bucket to local ec2 instances
> > 
> > Unable to understand - i want to know what is the filesystem on the backend directory for MinIO.
> Below is the data location inside k8s pod(running on ec2 instance)
> minio server  /minio-quad-dev-storage/quad-dev/
> where this pod location /minio-quad-dev-storage/quad-dev/ is pointed to my local ec2 instance s3fs mount location to my aws s3 bucket
> 

S3FS is not a POSIX filesystem @jaybhusari-bh this will not work.

You don't need to have S3FS for MinIO to run in front your AWS S3 bucket just use the `minio gateway s3` 

This is working as expected you cannot use non POSIX filesystems like S3FS

**Comment by jaybhusari-bh** [comment]
Is there any option we can use `minio gateway s3` just with iam policy(without access key and secret key)
