### ISSUE TITLE
arm64:  data of version before minio.RELEASE.2021-02-01T22-56-52Z  cannot downloaded after upgrade to version after minio.RELEASE.2021-02-07T01-31-02Z  

### ISSUE THREAD

**Issue by loyalPlayer** [minio/minio#12943]
I upgrade minio server from minio.RELEASE.2020-10-28T08-16-50Z to minio.RELEASE.2021-03-17T02-33-02Z.

- clusters of x86 works well

- clusters of arm64 works well with new buckets (created after upgrade), but cannot download any file from old buckets (created before upgrade).

I try upgrade and downgrade many times by all release versions between minio.RELEASE.2020-10-28T08-16-50Z and minio.RELEASE.2021-03-17T02-33-02Z and I found that this problem starts at version minio.RELEASE.2021-02-07T01-31-02Z  

## Expected Behavior

Works well after upgrade cluster deployed on arm64 to version after minio.RELEASE.2021-02-07T01-31-02Z  

## Current Behavior

clusters of x86 works well
clusters of arm64 works well with new buckets (created after upgrade), but cannot download any file from old buckets (created before upgrade).
1. Cannot download any file from old buckets (created before upgrade).
2. when I download file from old buckets, server log would print "API: GetObject XXXXXXXXX ... Error: file is corrupted XXXX" about this file.
3. there is much "content hash does not match" in server log
4. server log print "Unable to migrate IAM users and policies to new format: file is corrupted" 
5. server log print "IAM sub-system is partially initialized, some users may not be available" 
6.  After downgrade to version before, I can download any file from old buckets (created before upgrade), cannot download any file from new buckets (created after upgrade)

## Possible Solution

I just found this problem. I'll update this part if I have any clues

## Steps to Reproduce (for bugs)

1. deploy a distributed minio on arm64 os
2. make bucket and put some object on minio
3. upgrade to version after minio.RELEASE.2021-02-07T01-31-02Z 
4. download object from bucket created before upgrade by mc client or java client.
5. mc blocks and print We encountered an internal error, please try again.: cause(file is corrupted)

**Comment by klauspost** [comment]
Use the latest version. Anything written by `RELEASE.2021-02-07T01-31-02Z` will become unreadable, so it should not be used due to https://github.com/minio/minio/pull/11901
