### ISSUE TITLE
webhook event with void x-minio-origin-endpoint 

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#12954]
minio version RELEASE.2021-08-05T22-01-19Z

bucket configured with event notification. The event file is missing the value for x-minio-origin-endpoint:

<pre>
{
  "eventVersion": "2.0",
  "eventSource": "minio:s3",
  "awsRegion": "",
  "eventTime": "2021-08-13T12:17:09.597Z",
  "eventName": "s3:ObjectCreated:Put",
  "userIdentity": {
    "principalId": "francesco"
  },
  "requestParameters": {
    "principalId": "francesco",
    "region": "",
    "sourceIPAddress": "1.0.0.189"
  },
  "responseElements": {
    "content-length": "0",
    "x-amz-request-id": "169ADCD68C2F2554",
    "x-minio-deployment-id": "9dfc7906-fe0b-4ba4-b336-c517d881df45",
    "x-minio-origin-endpoint": ""
  },
  "s3": {
    "s3SchemaVersion": "1.0",
    "configurationId": "Config",
    "bucket": {
      "name": "francesco",
      "ownerIdentity": {
        "principalId": "francesco"
      },
      "arn": "arn:aws:s3:::francesco"
    },
    "object": {
      "key": "out%2FNuovo+documento+di+testo.txt",
      "eTag": "d41d8cd98f00b204e9800998ecf8427e",
      "contentType": "application/octet-stream",
      "userMetadata": {
        "content-type": "application/octet-stream",
        "x-minio-internal-inline-data": "true",
        "x-minio-internal-tier-free-versionID": "81ed06fa-95ca-4e44-868e-db3f5122ae1c"
      },
      "versionId": "83921a9f-8447-4376-bc01-58f3e581858f",
      "sequencer": "169ADCD69F0C4241"
    }
  },
  "source": {
    "host": "1.0.0.189",
    "port": "",
    "userAgent": "MinIO (windows; amd64) minio-go/v7.0.12"
  }
}
</pre>

**Comment by harshavardhana** [comment]
@fdefilippo set the correct endpoint with MINIO_SERVER_URL

**Comment by fdefilippo** [comment]
thank you.
