### ISSUE TITLE
Make smallFileThreshold Configurable

### ISSUE THREAD

**Issue by vijayanandnandam** [minio/minio#12960]
**Is your feature request related to a problem? Please describe.**
`smallFileThreshold` is set to a value optimal for SSD / Nvme and not for HDD
**Describe the solution you'd like**
make this size configurable so that minio can be tuned for millions of small files on HDD. my current requirement is to store 100 million files on 10x16tb hdd. so this will help in reducing IO. 

**Describe alternatives you've considered**
(May be changing it and compiling minio myself 🤔 ?)
**Additional context**

**Comment by harshavardhana** [comment]
@vijayanandnandam HDDs already are covered by NVMe's - it is not required for these intricate things to be configurable. 

If we find the current value doesn't fit we may change it to optimal value properly. In all our tests the value chosen is sufficient and increases IOPS by orders of magnitude on both NVMe and HDDs. 


> make this size configurable so that minio can be tuned for millions of small files on HDD. my current requirement is to store 100 million files on 10x16tb hdd. so this will help in reducing IO.

It is already tuned enough changing this value won't change much for you.

**Comment by vijayanandnandam** [comment]
ok thanks @harshavardhana i am closing this.
