### ISSUE TITLE
ILM does not purge old non-current objects

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#12961]
## Expected Behavior

ILM should purge old non-current objects as per the ILM policy:
```
{
  "Rules": [
    {
      "ID": "expire-non-current",
      "Status": "Enabled",
      "Expiration": {
        "ExpiredObjectDeleteMarker": true
      },
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 30
      }
    }
  ]
}
```

## Current Behavior

Old non-current objects are not purged.

## Steps to Reproduce (for bugs)

1.
Start minio: `minio server /tmp/export/disk{1...4}`

minio is modified with this change to set the uploaded objects time to be of previous year:
```
--- a/cmd/erasure-object.go
+++ b/cmd/erasure-object.go
@@ -949,6 +949,8 @@ func (er erasureObjects) putObject(ctx context.Context, bucket string, object st
                modTime = UTCNow()
        }
 
+       modTime = modTime.AddDate(-1, 0, 0)
+
```

2.
mc mb min/test
mc version enable min/test
mc ilm  import min/test < lifecycle.json
mc cp /etc/passwd min/test
mc rm min/test/passwd

3.
After waiting 15-20 minutes:
krishna@escape:~$ mc ls --versions min/test
[2021-08-13 13:04:56 PDT]     0B 471d72d4-fd75-4eea-8c02-e2cbffeb7e2a v2 DEL passwd
[2020-08-13 13:04:39 PDT] 2.5KiB 82370526-b3e9-44c0-b85a-e277724ea534 v1 PUT passwd

i.e the file is still not purged.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

minio master branch latest. On linux.

**Comment by harshavardhana** [comment]
This is tested and working as per AWS S3 implementation
