### ISSUE TITLE
can`t set minio notify

### ISSUE THREAD

**Issue by wuyuan0717** [minio/minio#12973]
## Expected Behavior

successful to set minio notification

## Current Behavior

![image](https://user-images.githubusercontent.com/14838846/129541898-0439b7af-b920-4868-82d7-98a70db26c90.png)

## Your Environment

2021-08-05T22:01:19Z of MinIO
RELEASE.2021-07-27T06-46-19Z of mc

**Comment by klauspost** [comment]
@wuyuan0717 For debugging purposes please list your elastic version as well as minio server output from the call, if any.

**Comment by wuyuan0717** [comment]
> @wuyuan0717 For debugging purposes please list your elastic version as well as minio server output from the call, if any.
`7.6.2 of elasticsearch`
`minio server no  any output，I was looking at the log when I executed the order` ，`tail -f -n100 xxx`

![image](https://user-images.githubusercontent.com/14838846/129649825-2e152b84-f341-485b-875b-f169d88f4ad9.png)

**Comment by harshavardhana** [comment]
> successful to set minio notification

Is your elastic running on the same system as MinIO?

**Comment by klauspost** [comment]
Please share how you are running MinIO and Elastic. If you are running both in Docker, using 127.0.0.1 in MinIO will not see 127.0.0.1 in ES container, AFAIK.

**Comment by harshavardhana** [comment]
No follow up closing the issue.

**Comment by wuyuan0717** [comment]
> No follow up closing the issue.

Sorry，I've been busy recently and forgot to pay attention to this matter.
 `No docker,just singleton mode running MinIO and Elastic：`
 download minio from` https://dl.min.io/server/minio/release/windows-amd64/minio.exe`, then run `minio.exe server D:\`
 download mc from` https://dl.min.io/client/mc/release/windows-amd64/mc.exe`, then run `mc.exe alias set minio  http://127.0.0.1:9000 minioadmin minioadmin`
Today i built elastic on another server,but the elastic notification still cannot be set, which is the same exception as before.
Can you provide your version information and execution method? Let me try.
![image](https://user-images.githubusercontent.com/14838846/130201470-455218e2-37a6-4e02-8f5f-06822fef30fc.png)

**Comment by wuyuan0717** [comment]
Is it because my elastic version is too high that the setting is not successful? the elastic`s version is 7.6.2
or that the key step of setting up notifications was missing during the installation of Minio?

**Comment by harshavardhana** [comment]
> and execution method? Let me try.
> ![image](https://user-images.githubusercontent.com/14838846/130201470-455218e2-37a6-4e02-8f5f-06822fef30fc.png)

The connection closed by foreign host is most probably due to some proxy settings that you have locally or MinIO server crashed for some reason - do you see MinIO server running properly? @wuyuan0717

**Comment by harshavardhana** [comment]
Closing this issue due to in-activity.
