### ISSUE TITLE
Login Minio with new user Error

### ISSUE THREAD

**Issue by tadtjolly** [minio/minio#12971]
when i create user with mc. I'm can not login in the website

## Steps to reproduce the behavior
linux: open terminal 
1. mc admin user add myminio testnewuser testnewuser
2. i'm login user in website myMinio 
![image](https://user-images.githubusercontent.com/23700487/129503707-aea5c079-6754-4af9-a03b-761a7e5447b7.png)
3. log in the minio server: access key not exist
![image](https://user-images.githubusercontent.com/23700487/129503990-69745ea8-7c43-4ddf-81e7-6bad61a4a60e.png)

## Your Environment
![image](https://user-images.githubusercontent.com/23700487/129504115-d80d2d05-0d95-4e8a-8f05-726f55360965.png)

**Comment by harshavardhana** [comment]
You need to make sure to add a policy, without a policy no user is allowed login
