### ISSUE TITLE
minio config ldap success,but the policy can't assign to the group

### ISSUE THREAD

**Issue by centrexzj** [minio/minio#12981]
mino's version is : RELEASE.2021-08-05T22-01-19Z

my ldap config is:

export MINIO_IDENTITY_LDAP_SERVER_ADDR="192.168.33.250:389"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="ou=a,dc=isuanyun,dc=com;ou=b,dc=isuanyun,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=groupOfUniqueNames))"
export MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="cn=admin,dc=isuanyun,dc=com"
export MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="123456"
export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="dc=isuanyun,dc=com"
export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(&(objectclass=posixAccount)(cn=%s))"
export MINIO_IDENTITY_LDAP_STS_EXPIRY=24h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on

when i am not assign a policy to the ldap group ,i login by the console

Error: expecting a policy to be set for user `cn=manager1,cn=manager1_ou,cn=manager1,ou=suanyun,dc=isuanyun,dc=com` or one of their groups: `cn=manager1_ou,cn=manager1,ou=suanyun,dc=isuanyun,dc=com`,`cn=android_ou,cn=android,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=bsp_ou,cn=bsp,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=itsupport_ou,cn=itsupport,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=web_ou,cn=web,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=java_ou,cn=java,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=manager_ou,cn=manager,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=product_ou,cn=product,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=project_ou,cn=project,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=qtc_ou,cn=qtc,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=hr_ou,cn=hr,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=ios_ou,cn=ios,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=market_ou,cn=market,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=php_ou,cn=php,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=cplusplus_ou,cn=cplusplus,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=testunit_ou,cn=testunit,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=ui_ou,cn=ui,ou=cqfgyjy,dc=isuanyun,dc=com` - rejecting this request (*errors.errorString)
       3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:577:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
       1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()

when i set a policy to one of the ldap group  and all user will use the policy.

i want to set a single policy to every ldap group?

someone can help me ?

**Comment by harshavardhana** [comment]
You need to setup policy for each group or a user.

**Comment by centrexzj** [comment]
i set a policy to one of the group ,but ervery user use the policy

**Comment by centrexzj** [comment]
i set policy to two ldap group,

[root@rh2288hv2 run]# ./mc admin policy set minio1 consoleAdmin group=cn=manager_ou,cn=manager,ou=cqfgyjy,dc=isuanyun,dc=com
Policy `consoleAdmin` is set on group `cn=manager_ou,cn=manager,ou=cqfgyjy,dc=isuanyun,dc=com`
[root@rh2288hv2 run]# ./mc admin policy set minio1 cqfgyjy group=cn=java_ou,cn=java,ou=cqfgyjy,dc=isuanyun,dc=com
Policy `cqfgyjy` is set on group `cn=java_ou,cn=java,ou=cqfgyjy,dc=isuanyun,dc=com`

but i login in console use two user in the two group ,the policy is not effect

**Comment by harshavardhana** [comment]
It needs to be exact 

```
mc admin policy set minio1 consoleAdmin group='cn=manager1_ou,cn=manager1,ou=suanyun,dc=isuanyun,dc=com'
```

It doesn't look like you have `cn=manager_ou`  and also make sure the `group='args'` are passed in single quotes.

**Comment by centrexzj** [comment]
i have use  the group='args',it's also not working

![](https://images.isuanyun.com/images/2021/08/17/jx2aHMWWAm.png)

![](https://images.isuanyun.com/images/2021/08/17/Xshell_XDdlA0F7jl.png)

![](https://images.isuanyun.com/images/2021/08/17/Xshell_bEKDDt6dbK.png)

![](https://images.isuanyun.com/images/2021/08/17/chrome_sX0fK7ZTlM.png)

![](https://images.isuanyun.com/images/2021/08/17/chrome_e9OAaREXG6.png)

![](https://images.isuanyun.com/images/2021/08/17/chrome_am8SCSgBmA.png)

![](https://images.isuanyun.com/images/2021/08/17/chrome_ORC8dCfKGw.png)

**Comment by harshavardhana** [comment]
I am not able to see what is wrong here - your login is working fine.

**Comment by centrexzj** [comment]
The two user groups use different policies, but the permissions are the same

**Comment by harshavardhana** [comment]
> The two user groups use different policies, but the permissions are the same

You have given enough permissions to show the dashboard and UI in both policies.

admin API do not honor resources that is wrong in your modified policy. S3 APIs however apply resources upon when a request is made console cannot evaluate them for displaying UI for such type of resource based restrictive access.

**Comment by lizhenwei** [comment]
> The two user groups use different policies, but the permissions are the same

modify your env like this:
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectclass=groupOfUniqueNames)(uniquemember=%d))

**Comment by chenwei0930** [comment]
> mino's version is : RELEASE.2021-08-05T22-01-19Z
> 
> my ldap config is:
> 
> export MINIO_IDENTITY_LDAP_SERVER_ADDR="192.168.33.250:389" export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="ou=a,dc=isuanyun,dc=com;ou=b,dc=isuanyun,dc=com" export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=groupOfUniqueNames))" export MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="cn=admin,dc=isuanyun,dc=com" export MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="123456" export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="dc=isuanyun,dc=com" export MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(&(objectclass=posixAccount)(cn=%s))" export MINIO_IDENTITY_LDAP_STS_EXPIRY=24h export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
> 
> when i am not assign a policy to the ldap group ,i login by the console
> 
> Error: expecting a policy to be set for user `cn=manager1,cn=manager1_ou,cn=manager1,ou=suanyun,dc=isuanyun,dc=com` or one of their groups: `cn=manager1_ou,cn=manager1,ou=suanyun,dc=isuanyun,dc=com`,`cn=android_ou,cn=android,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=bsp_ou,cn=bsp,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=itsupport_ou,cn=itsupport,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=web_ou,cn=web,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=java_ou,cn=java,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=manager_ou,cn=manager,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=product_ou,cn=product,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=project_ou,cn=project,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=qtc_ou,cn=qtc,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=hr_ou,cn=hr,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=ios_ou,cn=ios,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=market_ou,cn=market,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=php_ou,cn=php,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=cplusplus_ou,cn=cplusplus,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=testunit_ou,cn=testunit,ou=cqfgyjy,dc=isuanyun,dc=com`,`cn=ui_ou,cn=ui,ou=cqfgyjy,dc=isuanyun,dc=com` - rejecting this request (*errors.errorString) 3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse() 2: cmd/sts-handlers.go:577:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity() 1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()
> 
> when i set a policy to one of the ldap group and all user will use the policy.
> 
> i want to set a single policy to every ldap group?
> 
> someone can help me ?

I meet this problem too, had you resolved this problem?

**Comment by R-Studio** [comment]
I have the same issue.

**Comment by ArloSmile** [comment]
Minio is integrated with openldap and can only be authorized to users, not to groups.

**Comment by harshavardhana** [comment]
> Minio is integrated with openldap and can only be authorized to users, not to groups.

You can authorize to groups just provide `policy attach --group=group-dn`
