### ISSUE TITLE
Consider adopting chef cookbook: https://github.com/donaldguy/minio-chef

### ISSUE THREAD

**Issue by donaldguy** [minio/minio#1299]
I wrote a small Chef cookbook to help me get minio into my CD pipeline: https://github.com/donaldguy/minio-chef

Obviously it could use more work to verify it actually works cross platform and expand its capabilities

And it could use some InSpec tests

Its just my work, so I could probably transfer copyright in full if you care.

Its a start anyway.

**Comment by donaldguy** [comment]
If you take over it, consider publishing to http://supermarket.chef.io

**Comment by harshavardhana** [comment]
This is good work thanks! @donaldguy

**Comment by harshavardhana** [comment]
> I wrote a small Chef cookbook to help me get minio into my CD pipeline: https://github.com/donaldguy/minio-chef
> 
> Obviously it could use more work to verify it actually works cross platform and expand its capabilities
> 
> And it could use some InSpec tests
> 
> Its just my work, so I could probably transfer copyright in full if you care.
> 
> Its a start anyway.

Its upto you, if you wish to maintain it. Otherwise we are happy to maintain it as well - either way works for us.

Will keep this bug open for the time being once we work through the details and publish it to supermarket.chef.io

**Comment by ghost** [comment]
I would be more than happy to help maintain the cookbook. I'm currently using it.

**Comment by harshavardhana** [comment]
@donaldguy - can you send a pull request to https://github.com/minio/minio-chef - you can keep the copyright if you wish or we can change the ownership if that is more comfortable for you going forward. 

We will be happy to publish this at http://supermarket.chef.io. Let us know what works for you. 

Thanks a lot @gregf . will ping you once the repo transfer is complete.  Thanks again @donaldguy for doing this.
