### ISSUE TITLE
Possibility to define HTTP header name for JWT

### ISSUE THREAD

**Issue by DougTrajano** [minio/minio#12991]
**Is your feature request related to a problem? Please describe.**

I use OAuth2 Proxy in my stack that sets the JWT in `x-auth-request-access-token`, I want to be able to define the HTTP header name that MinIO STS will use the JWT. If that, I'll be able to reuse the same JWT that I created in other applications.

**Describe the solution you'd like**

An environment variable/argument (e.g. `MINIO_IDENTITY_OPENID_JWT_HEADER`) that I can define the location of the JWT.

**Additional context**

I'm using MinIO STS in my MinIO S3 Gateway with Keycloak as my OpenID Provider. See below the sample configuration:

```yaml
MINIO_ETCD_ENDPOINTS: {{ minio.etcd.endpoints }}
MINIO_IDENTITY_OPENID_CLIENT_ID: minio
MINIO_IDENTITY_OPENID_CLIENT_SECRET: {{ minio.openid.secret }}
MINIO_IDENTITY_OPENID_CONFIG_URL: http://{{ keycloak.url }}/auth/realms/master/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL: https://{{ keycloak.url }}/auth
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM: master
MINIO_IDENTITY_OPENID_REDIRECT_URI: https://{{ minio.url }}/oauth_callback
MINIO_IDENTITY_OPENID_CLAIM_NAME: minio_policies
MINIO_IDENTITY_OPENID_SCOPES: openid,email,minio_policies,profile
MINIO_IDENTITY_OPENID_VENDOR: keycloak
MINIO_ROOT_PASSWORD: {{ minio.root.password }}
MINIO_ROOT_USER: {{ minio.root.user }}
```

**Comment by harshavardhana** [comment]
We comply with AWS STS API here @DougTrajano - cannot add custom extensions in this manner.

Will close this for now as "won't fix" since this is outside the scope for now.
