### ISSUE TITLE
cannot login after moving from http to https

### ISSUE THREAD

**Issue by harridu** [minio/minio#12992]
I had setup minio on bare metal using /etc/default/minio and the systemd service, as found in the debian package. The web interface was working fine (using http), but since I put the certificate chain and key file into /etc/minio/certs I cannot login anymore. The web interface works  (using https, as expected), but if I try to login using name and password given in /etc/default/minio there is a big red bar with the text
```
{"code":401,"detailedMessage":"invalid Login","message":"invalid Login"}
```
If I remove/rename /etc/minio/certs and restart minio, then the web interface is back to http, but I can login again. /etc/default/minio is not touched.

## Expected Behavior
* https should be supported for the web interface. Check
* http does not work anymore. Check
* I can login using the credentials from the config file.

## Current Behavior
cannot login using user and password from the config file.

## Context
We are trying to setup some local S3 storage for our gitlab runners, but now we are stuck.

## Your Environment
* minio version RELEASE.2021-08-05T22-01-19Z
* Debian 11 on amd64
* Linux nasl005.ac.aixigo.de 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

/etc/default/minio:
```
MINIO_ROOT_USER="minio"
MINIO_ROOT_PASSWORD="secret"
MINIO_VOLUMES="/space/minio01/data/"
MINIO_OPTS="-C /etc/minio --address :9000 --console-address :9001"
```

**Comment by harshavardhana** [comment]
> MINIO_ROOT_USER="minio"
> MINIO_ROOT_PASSWORD="secret"
> MINIO_VOLUMES="/space/minio01/data/"
> MINIO_OPTS="-C /etc/minio --address :9000 --console-address :9001"

Make sure to set MINIO_SERVER_URL that supports your certs @harridu

**Comment by harridu** [comment]
Still doesn't work.
```
MINIO_ROOT_USER="minio"
MINIO_ROOT_PASSWORD="secret"
MINIO_VOLUMES="/space/minio01/data/"
MINIO_SERVER_URL="https://minio.dev.example.com"
MINIO_OPTS="-C /etc/minio --address :9000 --console-address :9001"
```
CN of the certificate is "CN = *.dev.examplec.om".

The Subject Alternative Name entry says
```
            X509v3 Subject Alternative Name: 
                DNS:*.dev.example.com, DNS:dev.example.com
```

**Comment by harshavardhana** [comment]
did you trust the cert by dropping it in `~/.minio/certs/CAs` folder?

**Comment by harridu** [comment]
No, certificate chain (public.crt) and key file (private.key) are stored in /etc/minio/certs. AFAICT minio looks into this directory by default, so I omitted the --certs-dir on the minio command line. 
```
find /etc/minio -ls
  1838117      4 drwxr-xr-x   3 root     root         4096 Aug 17 17:07 /etc/minio
  1840806      4 drwxr-xr-x   3 minio-user minio-user     4096 Aug 17 16:43 /etc/minio/certs
  1841389      8 -rw-r--r--   1 minio-user minio-user     4112 Aug 17 16:40 /etc/minio/certs/public.crt
  1841387      4 -rw-------   1 minio-user minio-user     1675 Aug 17 16:39 /etc/minio/certs/private.key
  1841391      4 drwx------   2 minio-user minio-user     4096 Aug 17 22:47 /etc/minio/certs/CAs
  1841392      4 -rw-r--r--   1 minio-user minio-user     1647 Dec  6  2017 /etc/minio/certs/CAs/DigiCertSHA2SecureServerCA.crt.pem
```

**Comment by harshavardhana** [comment]
>   1841389      8 -rw-r--r--   1 minio-user minio-user     4112 Aug 17 16:40 /etc/minio/certs/public.crt

This needs to be present in /etc/minio/certs/CAs

**Comment by harridu** [comment]
This did not help, either. Its a client certificate, with CA:false (critical). And the CA file is already in this directory.

As written before, there is no problem with https. The web browser accepts the certificate provided by minio. Some internal authentication mechanism appears to be broken. 

Is there a comprehensive reference of command line flags and environment variables for minio somewhere?

**Comment by chrisarnott86** [comment]
I can confirm I'm finding exactly the same issue. I can't login if I define a certificate for https. Removing `--certs-dir ...` from the `MINIO_OPTS` line in `/etc/default/minio` enables login without any other changes. I'm on Debian 10.10. Minio version RELEASE.2021-08-17T20-53-08Z

**Comment by chrisarnott86** [comment]
I fixed it. I had to add the fqdn to the `MINIO_OPTS` e.g.
`--address minio.example.com:9000` instead of just `--address :9000`

**Comment by rl-simons** [comment]
I've the same problem, however specifying FQDN on "--address" and/ or "--console-address" doesn't work in a container.

**Comment by k-jingyang** [comment]
> I've the same problem, however specifying FQDN on "--address" and/ or "--console-address" doesn't work in a container.

It works for me. I'm using a `docker-compose.yml` with the following settings:

```
  hostname: YOUR_FQDN
  ports:
    - 9000:9000
    - 9001:9001
  command:   server /data --address "YOUR_FQDN:9000" --console-address ":9001"
```

I didn't have to specify `MINIO_SERVER_URL` though. I'm on `RELEASE.2021-07-12T02-44-53Z`

**Comment by rl-simons** [comment]
Ah ha! Think it's fixed with specifying the hostname of the container.
Thank you.

**Comment by aaghof** [comment]
> Still doesn't work.
> 
> ```
> MINIO_ROOT_USER="minio"
> MINIO_ROOT_PASSWORD="secret"
> MINIO_VOLUMES="/space/minio01/data/"
> MINIO_SERVER_URL="https://minio.dev.example.com"
> MINIO_OPTS="-C /etc/minio --address :9000 --console-address :9001"
> ```
> 
> CN of the certificate is "CN = *.dev.examplec.om".
> 
> The Subject Alternative Name entry says
> 
> ```
>             X509v3 Subject Alternative Name: 
>                 DNS:*.dev.example.com, DNS:dev.example.com
> ```

MINIO_OPTS="-C /etc/minio --address domain:443 --console-address domain:9001"

**Comment by rl-simons** [comment]
I got this to work doing the following:
* Specify the container hostname as the MINIO_SERVER_URL value
* Set --address <MINIO_SERVER_URL value>:9000 --console-address <MINIO_SERVER_URL value>:9001
* Remove reference to "MINIO_SERVER_URL" completely
Also make sure you've specified the --cert-dir option with the folder for your cert/keys and CA certs. Re: My server certificate includes the CA chain.
