### ISSUE TITLE
Distributed minio data loss

### ISSUE THREAD

**Issue by yingjianjian** [minio/minio#13001]
I currently have 9 disks. When I hot-swappable the disks, I unplug the 5 disks and plug them back in, and the historical data is lost. Is this normal?

I think the historical data should not be lost after inserting it back into the disk

## Your Environment

* Version used (`minio --version`):
* minio version RELEASE.2021-08-05T22-01-19Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
With 9 disks you have only 4 parity if you replace 5 disks of course you will loose data. 

You cannot loose more than the parity.
