### ISSUE TITLE
Disk going temporarily Offline for GetObject from Thanos

### ISSUE THREAD

**Issue by reddymh** [minio/minio#13017]
Running Minio Operator on rancher k8s cluster with below tenant config

No of pods: 32
No Of volumes per pod: 4

Thanos is firing the s3 api(GetObject) the response is slow , sometimes error and going some of the disk temporary offline.

**MinIO Version:** minio:RELEASE.2021-07-15T22-27-34Z

Memory and CPU is going very high and after setting the below parameters memory came in control but the CPU is too high and observed disk is going temporarily offline.

  MAX API Limit: 1500
  API_DEADLINE: 2m

**Logs:**

API: SYSTEM()
Time: 15:36:23 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
Error: Marking https://perf-ss-0-13.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6 temporary offline; caused by Post "https://perf-ss-0-13.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6/refresh?owner=perf-ss-0-0.perf-hl.mn-perf.svc.cluster.local%3A9000&quorum=8&source=%5Berasure-object.go%3A373%3AerasureObjects.GetObjectInfo%28%29%5D&uid=e9b34da1-e58a-42fd-aa21-23c9d3d816e1": dial tcp 10.62.23.150:9000: i/o timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/lock-rest-client.go:66:cmd.(*lockRESTClient).callWithContext()
       3: cmd/lock-rest-client.go:102:cmd.(*lockRESTClient).restCall()
       2: cmd/lock-rest-client.go:131:cmd.(*lockRESTClient).Refresh()
       1: internal/dsync/drwmutex.go:284:dsync.refresh.func1()

API: HeadObject(bucket=perf, object=01FC43SBXEM19N25Q6C1MTGERS/meta.json)
Time: 15:36:27 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
RequestID: 169D0DC436F2A776
RemoteHost: 10.62.7.83
Host: perf-ss-0-0.perf-hl.mn-perf.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.2 thanos-store/0.18.0 (go1.15.7)
Error: Marking https://perf-ss-0-13.perf-hl.mn-perf.svc.cluster.local:9000/minio/storage/export/v37 temporary offline; caused by Post "https://perf-ss-0-13.perf-hl.mn-perf.svc.cluster.local:9000/minio/storage/export/v37/readversion?disk-id=8ed9cb02-bfbb-4d95-b451-be98de24982d&file-path=01FC43SBXEM19N25Q6C1MTGERS%2Fmeta.json&read-data=false&version-id=&volume=perf": dial tcp 10.62.23.150:9000: i/o timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/storage-rest-client.go:151:cmd.(*storageRESTClient).call()
       3: cmd/storage-rest-client.go:505:cmd.(*storageRESTClient).ReadVersion()
       2: cmd/erasure-metadata-utils.go:131:cmd.readAllFileInfo.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Client https://perf-ss-0-13.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6 online

API: SYSTEM()
Time: 13:05:46 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
Error: Marking https://perf-ss-0-17.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6 temporary offline; caused by Post "https://perf-ss-0-17.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6/lock?owner=perf-ss-0-0.perf-hl.mn-perf.svc.cluster.local%3A9000&quorum=9&source=%5Bdata-scanner.go%3A102%3ArunDataScanner%28%29%5D&uid=62bb4b8f-ff71-4616-9fe2-6878bfad1336": net/http: TLS handshake timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/lock-rest-client.go:66:cmd.(*lockRESTClient).callWithContext()
       3: cmd/lock-rest-client.go:102:cmd.(*lockRESTClient).restCall()
       2: cmd/lock-rest-client.go:121:cmd.(*lockRESTClient).Lock()
       1: internal/dsync/drwmutex.go:393:dsync.lock.func1()

API: HeadObject(bucket=perf, object=01FBRA4D8MFVBPR8JEKTY7V3WY/meta.json)
Time: 13:05:21 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
RequestID: 169D057DD5B0DB83
RemoteHost: 10.62.6.8
Host: perf-ss-0-0.perf-hl.mn-perf.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.2 thanos-store/0.18.0 (go1.15.7)
Error: Marking https://perf-ss-0-25.perf-hl.mn-perf.svc.cluster.local:9000/minio/storage/export/v37 temporary offline; caused by Post "https://perf-ss-0-25.perf-hl.mn-perf.svc.cluster.local:9000/minio/storage/export/v37/readversion?disk-id=359894e5-6716-4619-9c2a-6056ab62a032&file-path=01FBRA4D8MFVBPR8JEKTY7V3WY%2Fmeta.json&read-data=false&version-id=&volume=perf": dial tcp 10.62.8.45:9000: i/o timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/storage-rest-client.go:151:cmd.(*storageRESTClient).call()
       3: cmd/storage-rest-client.go:505:cmd.(*storageRESTClient).ReadVersion()
       2: cmd/erasure-metadata-utils.go:131:cmd.readAllFileInfo.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 13:44:37 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
Error: Marking https://perf-ss-0-7.perf-hl.mn-perf.svc.cluster.local:9000/minio/peer/v15 temporary offline; caused by Post "https://perf-ss-0-7.perf-hl.mn-perf.svc.cluster.local:9000/minio/peer/v15/peermetrics?": dial tcp 10.62.2.40:9000: i/o timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/peer-rest-client.go:67:cmd.(*peerRESTClient).callWithContext()
       3: cmd/peer-rest-client.go:953:cmd.(*peerRESTClient).GetPeerMetrics()
       2: cmd/notification.go:1393:cmd.(*NotificationSys).GetClusterMetrics.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 13:44:37 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
Error: Marking https://perf-ss-0-18.perf-hl.mn-perf.svc.cluster.local:9000/minio/peer/v15 temporary offline; caused by Post "https://perf-ss-0-18.perf-hl.mn-perf.svc.cluster.local:9000/minio/peer/v15/peermetrics?": dial tcp 10.62.19.63:9000: i/o timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/peer-rest-client.go:67:cmd.(*peerRESTClient).callWithContext()
       3: cmd/peer-rest-client.go:953:cmd.(*peerRESTClient).GetPeerMetrics()
       2: cmd/notification.go:1393:cmd.(*NotificationSys).GetClusterMetrics.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 13:44:38 UTC 08/20/2021
DeploymentID: abf70913-9345-4b36-8f50-7166fe89b4cc
Error: Marking https://perf-ss-0-28.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6 temporary offline; caused by Post "https://perf-ss-0-28.perf-hl.mn-perf.svc.cluster.local:9000/minio/lock/v6/rlock?owner=perf-ss-0-4.perf-hl.mn-perf.svc.cluster.local%3A9000&quorum=8&source=%5Berasure-object.go%3A163%3AerasureObjects.GetObjectNInfo%28%29%5D&uid=c503c79b-6b83-4612-9b3a-548dc028c2cf": dial tcp 10.62.3.41:9000: i/o timeout (*fmt.wrapError)
       5: internal/rest/client.go:147:rest.(*Client).Call()
       4: cmd/lock-rest-client.go:66:cmd.(*lockRESTClient).callWithContext()
       3: cmd/lock-rest-client.go:102:cmd.(*lockRESTClient).restCall()
       2: cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).RLock()
       1: internal/dsync/drwmutex.go:389:dsync.lock.func1()

## Expected Behavior
Disk should not go offline.

## Current Behavior
Observed disk is going temporarily offline which is affecting the api response.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Please upgrade to latest release @reddymh we made a lot of performance improvements recently.

**Comment by reddymh** [comment]
@harshavardhana   after upgrading minio to RELEASE.2021-08-17T20-53-08Z but still disks are going temporary offline.

**Logs:**

API: SYSTEM()
Time: 17:32:00 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Get "https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/minio/health/live": context deadline exceeded (*url.Error)
       5: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       4: internal/logger/logonce.go:94:logger.LogOnceIf()
       3: cmd/admin-server-info.go:58:cmd.getLocalServerProperty()
       2: cmd/peer-rest-server.go:362:cmd.(*peerRESTServer).ServerInfoHandler()
       1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 17:32:01 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDFWHJZ6E671V3J7TTHEV7KB/index/becda533-8bad-4c06-9611-5db395f536c7/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 17:32:01 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDF12P0XEE19Y612D1DENMBG/index/d077423a-52b1-4b10-a182-b4c605edc177/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 17:32:01 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDAQR4XC7J3C6MGWVBW6HW47/index/674fca7f-fa85-4f13-a9e6-47b3955433ac/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 17:32:02 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDT64EX7SMN5M99GWEN62KX1/index/3e2c07b0-8695-4239-8c46-d676d84b2bde/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 17:32:03 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDE5KRZ55QDRXJMGZ018YYHY/index/f18f1086-6ff4-41a6-a857-88c5057fa785/part.2), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 17:32:03 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDET6YNBAHKJ1Q2WN3ZNFSBM/index/43caec61-5394-4d65-9fd4-5a1c48984266/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 17:32:03 UTC 08/24/2021
DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDEKB7DM7J4J6CMMCFJ41GZC/index/19af98ea-d1e4-46db-91e9-f8797f6bfd82/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

**Comment by harshavardhana** [comment]
> @harshavardhana   after upgrading minio to RELEASE.2021-08-17T20-53-08Z but still disks are going temporary offline.
> 
> **Logs:**
> 
> API: SYSTEM()
> Time: 17:32:00 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Get "https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/minio/health/live": context deadline exceeded (*url.Error)
>        5: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
>        4: internal/logger/logonce.go:94:logger.LogOnceIf()
>        3: cmd/admin-server-info.go:58:cmd.getLocalServerProperty()
>        2: cmd/peer-rest-server.go:362:cmd.(*peerRESTServer).ServerInfoHandler()
>        1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()
> 
> API: SYSTEM()
> Time: 17:32:01 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDFWHJZ6E671V3J7TTHEV7KB/index/becda533-8bad-4c06-9611-5db395f536c7/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
> 
> API: SYSTEM()
> Time: 17:32:01 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDF12P0XEE19Y612D1DENMBG/index/d077423a-52b1-4b10-a182-b4c605edc177/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
> 
> API: SYSTEM()
> Time: 17:32:01 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDAQR4XC7J3C6MGWVBW6HW47/index/674fca7f-fa85-4f13-a9e6-47b3955433ac/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
> 
> API: SYSTEM()
> Time: 17:32:02 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDT64EX7SMN5M99GWEN62KX1/index/3e2c07b0-8695-4239-8c46-d676d84b2bde/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
> 
> API: SYSTEM()
> Time: 17:32:03 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDE5KRZ55QDRXJMGZ018YYHY/index/f18f1086-6ff4-41a6-a857-88c5057fa785/part.2), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
> 
> API: SYSTEM()
> Time: 17:32:03 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDET6YNBAHKJ1Q2WN3ZNFSBM/index/43caec61-5394-4d65-9fd4-5a1c48984266/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
> 
> API: SYSTEM()
> Time: 17:32:03 UTC 08/24/2021
> DeploymentID: 5698739d-fe02-419b-b4c7-9e1aeaeb68f9
> Error: Error(disk not found) reading erasure shards at (https://perf-ss-0-20.perf-hl.mn-perf.svc.cluster.local:9000/export: telemetry/01FDEKB7DM7J4J6CMMCFJ41GZC/index/19af98ea-d1e4-46db-91e9-f8797f6bfd82/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
>        2: cmd/bitrot-streaming.go:152:cmd.(*streamingBitrotReader).ReadAt()
>        1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

You have some serious network issues

**Comment by reddymh** [comment]
@harshavardhana  this is failing when we try to get the data from last 2 or 7 days from thanos...but its works for 12 hrs and 24 hrs...for single widget in grafana it works for 2 or 7 days ...if we refresh entire dashboard then we are getting the above error

**Comment by harshavardhana** [comment]
> @harshavardhana  this is failing when we try to get the data from last 2 or 7 days from thanos...but its works for 12 hrs and 24 hrs...for single widget in grafana it works for 2 or 7 days ...if we refresh entire dashboard then we are getting the above error
> 

We have multiple petabytes running with this release in production, with much larger workloads such as Cohesity, Veeam, Rubrik to name a few.

There are some setup issues on your end @reddymh 

Setup issues we only debug for paid customers https://min.io/pricing 

If this is a production cluster you are advised to get a subscription with us.

**Comment by klauspost** [comment]
>  dial tcp 10.62.19.63:9000: i/o timeout

This means the server isn't reachable, and the disk should go offline. So AFAICT it is behaving as expected.
