### ISSUE TITLE
last build windows version  console page can't open ;awalys loading

### ISSUE THREAD

**Issue by Perfect404** [minio/minio#13016]
last build  windows version , console web page can't open ; loading~~~~~~~~

**Comment by klauspost** [comment]
Set `--address=IP:PORT` parameter on your server.

If you still have problems, open an issue and *provide your setup information*.

**Comment by Perfect404** [comment]
still the same 
![截图_20210822101044](https://user-images.githubusercontent.com/17940206/130339614-610d4ef6-bdaf-4580-88bc-711ca1c552eb.png)
![截图_20210822101104](https://user-images.githubusercontent.com/17940206/130339615-bb041daa-0964-4185-aaee-77ab15e17c6e.png)
![截图_20210822101120](https://user-images.githubusercontent.com/17940206/130339618-d1a13dce-3411-401d-a451-f394bb957a19.png)
