### ISSUE TITLE
Server-Side Bucket Replication duplicates files on replica

### ISSUE THREAD

**Issue by Dynkine** [minio/minio#13013]
Files uploaded to master node are twice as size on the disk on a replica node
## Expected Behavior

I expect that the file is replicated only once and is equal in total size on disk to the file on master
## Current Behavior

Uploaded to master file has duplicated size on disk on replica node. 

Master

du --time -sh /mnt/minio/data0/test/1gb/*
342M	2021-08-19 15:22	/mnt/minio/data0/test/1gb/08b78c82-683a-4fcc-90fd-4103b51c495a
4.0K	2021-08-19 15:22	/mnt/minio/data0/test/1gb/xl.meta

Replica

du --time -sh /mnt/minio/data0/test/1gb/*
342M	2021-08-19 15:22	/mnt/minio/data0/test/1gb/18d41f86-630d-4cbe-9151-10ff320acf65
342M	2021-08-19 15:22	/mnt/minio/data0/test/1gb/6e670fc8-95e6-4287-9df7-33e1414f5748
4.0K	2021-08-19 15:22	/mnt/minio/data0/test/1gb/xl.meta
## Possible Solution

none
## Steps to Reproduce (for bugs)

1. Upload file to master with replication enabled
2.  Check the minio datadir on replica

We've run tests with different size of files.

Each file we uploaded 1000 times to check for errors

Results

30mb file - no duplicates found 

40mb file - 1 duplicate

50mb file - 1 duplicate

60mb file - 5 duplicates

200mb file - 12 duplicates

1gb file - 98 duplicates

2gb file - 52 duplicates 

## Context

We can not properly esimate the required disk space
## Your Environment

* Version used (`minio --version`): RELEASE.2021-07-22T05-23-32Z
* Server setup and configuration: 
4 CPU 8gb RAM SSD disks 10Gib network
no bandwidth limitation on replication
* Operating System and version (`uname -a`): CentOS 8

**Comment by klauspost** [comment]
@Dynkine Is it possible for you to attach the `xl.meta` here?

**Comment by Dynkine** [comment]
> @Dynkine Is it possible for you to attach the `xl.meta` here?

I ran the 10gb file upload ( to get the error for sure) 

1. fallocate -l 10737418240 10gb
2. minio-cli cp  /root/10gb  minio/test/
3. Here is Master node

root@master:~$ du --time -sh /mnt/minio/data0/test/10gb/*
3.4G	2021-08-20 12:08	/mnt/minio/data0/test/10gb/fc16acf4-f98f-4449-871b-f90b9680ef5a
12K	2021-08-20 12:08	/mnt/minio/data0/test/10gb/xl.meta


root@master:~$ minio-cli  stat  minio/test/
Name      : 10gb
Date      : 2021-08-20 12:08:25 UTC
Size      : 10 GiB
ETag      : 21697dce4bbfa7556394cff44fc885ae-640
VersionID : 4732abf1-cc43-4483-b263-81e309588ccb
Type      : file
Metadata  :
  Content-Type: application/octet-stream
Replication Status: COMPLETED

4. Here is how it looks on replica 
root@replica:~$ du --time -sh /mnt/minio/data0/test/10gb/*
3.4G	2021-08-20 12:10	/mnt/minio/data0/test/10gb/05efa11e-ce56-4f24-b36b-20148a4dd357
3.4G	2021-08-20 12:11	/mnt/minio/data0/test/10gb/73bbcdf8-ca15-41d7-bff3-1972febfd249
12K	2021-08-20 12:11	/mnt/minio/data0/test/10gb/xl.meta


root@replica:~$ minio-cli  stat  minio-tp/test/
Name      : 10gb
Date      : 2021-08-20 12:08:25 UTC
Size      : 10 GiB
ETag      : 21697dce4bbfa7556394cff44fc885ae-640
VersionID : 4732abf1-cc43-4483-b263-81e309588ccb
Type      : file
Metadata  :
  Content-Type: application/octet-stream
Replication Status: REPLICA


root@replica:~t$ minio-cli ls  --versions minio/test/
[2021-08-20 12:08:25 UTC]  10GiB 4732abf1-cc43-4483-b263-81e309588ccb v1 PUT 10gb

5. xl.meta file attached
[xl.meta.zip](https://github.com/minio/minio/files/7021389/xl.meta.zip)

**Comment by klauspost** [comment]
Interesting. Only `73bbcdf8ca1541d7bff31972febfd249` is referenced in the metadata, meaning we leaked the other.

@harshavardhana @poornas We should probably have a look if there is a way we can potentially leak data directories on concurrent operations when specifying a destination version id. While #13014 will prevent concurrent operations it shouldn't happen in the first place.

**Comment by harshavardhana** [comment]
> du --time -sh /mnt/minio/data0/test/1gb/*
> 342M 2021-08-19 15:22 /mnt/minio/data0/test/1gb/08b78c82-683a-4fcc-90fd-4103b51c495a
> 4.0K 2021-08-19 15:22 /mnt/minio/data0/test/1gb/xl.meta
> 
> Replica
> 
> du --time -sh /mnt/minio/data0/test/1gb/*
> 342M 2021-08-19 15:22 /mnt/minio/data0/test/1gb/18d41f86-630d-4cbe-9151-10ff320acf65
> 342M 2021-08-19 15:22 /mnt/minio/data0/test/1gb/6e670fc8-95e6-4287-9df7-33e1414f5748
> 4.0K 2021-08-19 15:22 /mnt/minio/data0/test/1gb/xl.meta

Wait are you saying that you upload this only once?

**Comment by Dynkine** [comment]
> > du --time -sh /mnt/minio/data0/test/1gb/*
> > 342M 2021-08-19 15:22 /mnt/minio/data0/test/1gb/08b78c82-683a-4fcc-90fd-4103b51c495a
> > 4.0K 2021-08-19 15:22 /mnt/minio/data0/test/1gb/xl.meta
> > Replica
> > du --time -sh /mnt/minio/data0/test/1gb/*
> > 342M 2021-08-19 15:22 /mnt/minio/data0/test/1gb/18d41f86-630d-4cbe-9151-10ff320acf65
> > 342M 2021-08-19 15:22 /mnt/minio/data0/test/1gb/6e670fc8-95e6-4287-9df7-33e1414f5748
> > 4.0K 2021-08-19 15:22 /mnt/minio/data0/test/1gb/xl.meta
> 
> Wait are you saying that you upload this only once?

Exactly)) that is the point of my bug report. You upload the file once. It is uploaded normally to master and replicate two copies on replica

**Comment by harshavardhana** [comment]
> Exactly)) that is the point of my bug report. You upload the file once. It is uploaded normally to master and replicate two copies on replica

what are the permissions for the credentials used in replication?

**Comment by poornas** [comment]
Due to the size of the upload and time to finalize, looks like the scanner is re-queuing these objects multiple times leading to competing uploads. The issue is amplified because this seems to be a test cluster where the scanner is looking at a small namespace and possibly poor bandwidth.  Doing a HEAD on the target version before performing replication is not sufficient to avoid dups for these long uploads - we will need additional state or poll target to abort competing uploads after one of them finalizes. There are downsides to both approaches, taking a look.

**Comment by harshavardhana** [comment]
> Due to the size of the upload and time to finalize, looks like the scanner is re-queuing these objects multiple times leading to competing uploads. The issue is amplified because this seems to be a test cluster where the scanner is looking at a small namespace and possibly poor bandwidth. Doing a HEAD on the target version before performing replication is not sufficient to avoid dups for these long uploads - we will need additional state or poll target to abort competing uploads after one of them finalizes. There are downsides to both approaches, taking a look.

@poornas @klauspost added a locker for replication that serializes the replication calls for the same objects being overwritten, if we do that - it is possible to have a single object on the destination.

This still allows GetObjects() to be free of write locks - perhaps is a better solution.

**Comment by Dynkine** [comment]
> Due to the size of the upload and time to finalize, looks like the scanner is re-queuing these objects multiple times leading to competing uploads. The issue is amplified because this seems to be a test cluster where the scanner is looking at a small namespace and possibly poor bandwidth. Doing a HEAD on the target version before performing replication is not sufficient to avoid dups for these long uploads - we will need additional state or poll target to abort competing uploads after one of them finalizes. There are downsides to both approaches, taking a look.

As I wrote in the description , the issue occurs for a smaller files as well. My bandwidth is 10gib without any limitations

**Comment by harshavardhana** [comment]
.
> 
> As I wrote in the description , the issue occurs for a smaller files as well. My bandwidth is 10gib without any limitations

Can you run iperf between source and target? - I have run an exact setup locally.

Could not reproduce it until I throttled the bandwidth just like @poornas mentioned.

So looks like your 10G is not really 10G.

**Comment by Dynkine** [comment]
> .
> 
> > As I wrote in the description , the issue occurs for a smaller files as well. My bandwidth is 10gib without any limitations
> 
> Can you run iperf between source and target? - I have run an exact setup locally.
> 
> Could not reproduce it until I throttled the bandwidth just like @poornas mentioned.
> 
> So looks like your 10G is not really 10G.

Sure. I tolkd that yje network is 10Gbit/s

Here is the iperf result from the server where the origina file was uploaded from to master node

Connecting to host $minio_master_host, port 5201
[  5] local 192.0.2.11 port 35746 connected to 192.0.2.12 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  1.77 GBytes  1.77 GBytes/sec    0   1.66 MBytes
[  5]   1.00-2.00   sec  1.71 GBytes  1.71 GBytes/sec    0   2.11 MBytes
[  5]   2.00-3.00   sec  1.63 GBytes  1.63 GBytes/sec    0   7.97 MBytes
[  5]   3.00-4.00   sec  1.64 GBytes  1.64 GBytes/sec    0   7.97 MBytes
[  5]   4.00-5.00   sec  1.61 GBytes  1.61 GBytes/sec    0   7.97 MBytes
[  5]   5.00-6.00   sec  1.63 GBytes  1.63 GBytes/sec    0   7.97 MBytes
[  5]   6.00-7.00   sec  1.61 GBytes  1.61 GBytes/sec    0   8.39 MBytes
[  5]   7.00-8.00   sec  1.66 GBytes  1.66 GBytes/sec    0   8.39 MBytes
[  5]   8.00-9.00   sec  1.67 GBytes  1.67 GBytes/sec    0   8.39 MBytes
[  5]   9.00-10.00  sec  1.62 GBytes  1.62 GBytes/sec    0   8.39 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  16.6 GBytes  1.66 GBytes/sec    0             sender
[  5]   0.00-10.04  sec  16.5 GBytes  1.65 GBytes/sec                  receiver

iperf Done.

1.65 Gigabytes = 13.2 Gigabits

Iperf result from master node to replica 

Connecting to host $minio_replica_host, port 5201

[  5] local 192.0.2.12  port 18296 connected to 192.0.2.13 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  1.01 GBytes  1.01 GBytes/sec  320   1.05 MBytes
[  5]   1.00-2.00   sec  1.02 GBytes  1.02 GBytes/sec  753   1.17 MBytes
[  5]   2.00-3.00   sec   785 MBytes  0.77 GBytes/sec  1614   1.29 MBytes
[  5]   3.00-4.00   sec  1.03 GBytes  1.03 GBytes/sec  1972   1.06 MBytes
[  5]   4.00-5.00   sec   851 MBytes  0.83 GBytes/sec  373   3.25 MBytes
[  5]   5.00-6.00   sec   649 MBytes  0.63 GBytes/sec  4119   1.37 MBytes
[  5]   6.00-7.00   sec   982 MBytes  0.96 GBytes/sec  2017   2.53 MBytes
[  5]   7.00-8.00   sec  1.01 GBytes  1.01 GBytes/sec    0   2.82 MBytes
[  5]   8.00-9.00   sec  1015 MBytes  0.99 GBytes/sec    0   3.07 MBytes
[  5]   9.00-10.00  sec   786 MBytes  0.77 GBytes/sec  6110   1.37 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  9.02 GBytes  0.90 GBytes/sec  17278             sender
[  5]   0.00-10.04  sec  9.01 GBytes  0.90 GBytes/sec                  receiver

iperf Done.

0.9 Gigabytes = 7.2 Gigabits

**Comment by poornas** [comment]
>@poornas @klauspost added a locker for replication that serializes the replication calls for the same objects being overwritten, if we do that - it is possible to have a single object on the destination.
>This still allows GetObjects() to be free of write locks - perhaps is a better solution.

yes, that would be much cleaner.
