### ISSUE TITLE
Resource name contains bad components such as ".." or ".". API error on play.min.io

### ISSUE THREAD

**Issue by aymanbagabas** [minio/minio#13022]
I'm trying to create an object with the name '.' but I keep getting this error. The object name restrictions https://docs.min.io/docs/minio-server-limits-per-tenant.html don't include '.'

This doesn't happen when I use AWS S3 endpoints.

## Expected Behavior

Minio server should accept '.' object names.

## Current Behavior

Minio doesn't accept '..' and '.' for an object name.

**Comment by harshavardhana** [comment]
> This doesn't happen when I use AWS S3 endpoints.

Yes because AWS S3 uses a database for their namespace, we use filesystems, and `.` and `..` have special meaning on `filesystems` 

So we will never accept such object names.
