### ISSUE TITLE
standalone mode Quite slow

### ISSUE THREAD

**Issue by simon4545** [minio/minio#13027]
## Expected Behavior
Faster?

Here are my build shell
`
wget https://dl.min.io/server/minio/release/linux-amd64/minio

mkdir /mnt/sd{a..h}/data{1..8}

MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server  /mnt/sd{a..h}/data{1..8} --console-address ":9001"

./mc alias mymin http://127.0.0.1:9000 admin password

./mc mb mymin/test

dd if=/dev/zero of=1GB.bin bs=1M count=1024

./mc cp ./1GB.bin mymin/test/1GB.bin
`

My system driver is NVME 2TiB with 1.9Gb write/read speed by dd command. I have mount 8*8T HDD  into /mnt folder.
but "mc cp " is quite slow ,about 100MiB/s.

**Comment by harshavardhana** [comment]
@simon4545 single stream writes are always pegged at single drive speed. You need to write multiple streams to get the throughput.

Run warp to get the actual numbers https://github.com/minio/warp
