### ISSUE TITLE
Add support for SSE-S3 header in ListObjects response

### ISSUE THREAD

**Issue by Alevsk** [minio/minio#13046]
## Expected Behavior
Currently we are listing objects on a particular bucket like this, `withMetadata` is true
```
for lsObj := range client.listObjects(ctx, bucketName, minio.ListObjectsOptions{Prefix: prefix, Recursive: recursive, WithVersions: withVersions, WithMetadata: withMetadata}) {
```
however the returned objects contains `nil` on the metadata field, `UserMetadata` contains some values

<img width="526" alt="Screen Shot 2021-08-23 at 15 18 43" src="https://user-images.githubusercontent.com/1795553/130527139-0c9fc4ee-844f-4676-a371-af34cf60bdf6.png">

Similar operation works via mc

```
mc stat "miniok8s/test/2021-08-23 12.53.45.jpg" --insecure --json
{
 "status": "success",
 "name": "2021-08-23 12.53.45.jpg",
 "lastModified": "2021-08-23T14:44:38-07:00",
 "size": 131663,
 "etag": "95638e7512478a02a30c23839bd3c121",
 "type": "file",
 "expires": "0001-01-01T00:00:00Z",
 "expiration": "0001-01-01T00:00:00Z",
 "metadata": {
  "Content-Type": "application/octet-stream",
  "X-Amz-Server-Side-Encryption": "AES256"
 }
}
```

The goal is to display encryption related information for an object on the UI but that information is not getting populated on the object struct

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> The goal is to display encryption-related information for an object on the UI but that information is not getting populated on the object struct

Encryption related information is never sent back in UserMetadata @Alevsk

**Comment by Alevsk** [comment]
> > on the object struct
> 
> Encryption related information is never sent back in UserMetadata @Alevsk

Is there a way to tell the user if a particular object is encrypted at rest? this is just for UI purpose, is not necessary to display encryption details

**Comment by harshavardhana** [comment]
> Is there a way to tell the user if a particular object is encrypted at rest? this is just for UI purpose, is not necessary to display encryption details

We can enhance the ListObjects to display that @Alevsk that has never been added since UserMetadata is not where this information is captured.
