### ISSUE TITLE
MinIO helm repo 404 error

### ISSUE THREAD

**Issue by alexander-bruun** [minio/minio#13044]
I'm unable to add the minio helm repo to my repo list locally:
![image](https://user-images.githubusercontent.com/87643857/130486200-f3cb8151-747a-45c6-8929-a3da7ff747f2.png)

## Expected Behavior

To be able to add the repo.

## Current Behavior

I get 404 when trying to add the helm repo as stated in docs.

## Possible Solution

Setup a proper helm repo for the minio chart.

## Steps to Reproduce (for bugs)

1. helm repo add minio https://charts.min.io/

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Yes you cannot yet @alexander-bruun - there is some issue with Github indexing the `index.yaml`  we are working with Github support for that.

You can use the https://github.com/minio/minio/blob/master/helm-releases/minio-1.0.1.tgz directly.

**Comment by harshavardhana** [comment]
This is fixed now, thanks to GitHub support.
