### ISSUE TITLE
 Can the value of 'conntent-type' be supported  as the header of headers exchanges

### ISSUE THREAD

**Issue by a523** [minio/minio#13053]
**Is your feature request related to a problem? Please describe.**
I need to process the images in the minio.  Then, I through the bucket notifications push messages to rabbitmq when put object. I know that in general, I should reduce unnecessary messages with a filter: "suffix=.jpeg" approach. However, in our business, we use the MD5 value of the object as the object key, not the file name. So that's not going to work.

Another way, I found, the minio supported "headers" type exchanges, It looks like different buckets and events  can be bound in different queues. But not support 'conntent-type="xxxx"'. Will my problem be solved if it support this feature?

**Describe the solution you'd like**
support 'conntent-type="xxxx" in the type of "headers" exchanges

**Describe alternatives you've considered**

**Additional context**

**Comment by klauspost** [comment]
@a523 Could you please elaborate on what you would like. It looks like you would like the `content-type` to be sent in (rabbitmq) notifications, but from your post it is not that clear. Please edit the original post.

**Comment by harshavardhana** [comment]
@a523 we support bucket names as the routing target which is considered sufficient.

Going to the content-type becomes too wide and too generic. You can write your own webhook server and then filter the content based on notifications - this webhook in turn writes to your rabbitmq target instead.

**Comment by a523** [comment]
OK, Thanks
