### ISSUE TITLE
mc not supporting username and password

### ISSUE THREAD

**Issue by Trikke76** [minio/minio#13066]
mc admin update ALIAS https://minio-mirror.example.com/minio

this doesn't work if the repo needs a username and password
as far as i can see mc doesn't support username and password

it would be great if there was support for --user and --password

**Comment by vadmeste** [comment]
> mc admin update ALIAS https://minio-mirror.example.com/minio

Did you try with `mc admin update ALIAS https://username:password@minio-mirror.example.com/minio` ?

**Comment by Trikke76** [comment]
yes i tried but it's not working i get a timeout 
even it works with curl

**Comment by vadmeste** [comment]
> yes i tried but it's not working i get a timeout

MinIO server needs to have access to the download URL. To check, you need to try curl command in a server that is hosting MinIO server

**Comment by Trikke76** [comment]
root@patrik-on-2:~# curl --output minio http://myuser:mypassword@myhostname:8081/artifactory/minio-server/minio
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 88.0M  100 88.0M    0     0  18.5M      0  0:00:04  0:00:04 --:--:-- 18.9M

working just fine

**Comment by Trikke76** [comment]
root@patrik-on-2:~# mc admin update patrik-on-2 http://myuser:mypassword@myhostname:8081/artifactory/minio-server/minio
Killed

ok never mind i found the option --debug seems it authorizes but fails somewhere else


Host: patrik-on-2.vm.cumuli.be:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2021-07-27T06-46-19Z
Transfer-Encoding: chunked
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20210825//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210825T115555Z
Accept-Encoding: gzip

Killed

**Comment by harshavardhana** [comment]
You can't update to a binary in this manner, you need to first have a mirror of exact layout as dl.min.io and then you need to update in this manner.

```
mc admin update alias http://endpoint/minio.sha256sum
```
