### ISSUE TITLE
AssumeRoleWithWebIdentity without OIDC provider

### ISSUE THREAD

**Issue by uhfath** [minio/minio#13074]
Is it possible to use AssumeRoleWithWebIdentity endpoint without specifying OIDC provider for token verification?
The idea is that JWTs are already self-contained and verification is needed only in cases of revoked tokens.
In our project there is no separate OIDC provider and JWTs are issued by a backend server without OIDC protocol.
For such simple cases it would be great to have this feature.
Unless I'm missing something and there is a way for not specifying OIDC?

**Comment by harshavardhana** [comment]
OIDC compatibility is necessary for us to have a well-published mechanism to validate JWT tokens. 

JWT tokens are validated against a JWKS endpoint that publishes the x.509 certs. 

We do not want to re-invent the wheel by providing some custom approach here.  If you cannot use OIDC then this is not the right solution for you. 

Sorry we cannot disable OIDC for WebIdentity().
