### ISSUE TITLE
MinIO Bucket Notifications should include Tag data for Put / PutObjectTagging

### ISSUE THREAD

**Issue by ravindk89** [minio/minio#13072]
**Is your feature request related to a problem? Please describe.**

In local testing, it seems that `PutObject` and `PutObjectTagging` event notifications do not include the object tags.

This might not be something AWS does, but in discussions internally, we should still try to do the right thing. 

Having both metadata and tags in bucket event notifications would also help customers who want to do metadata/tag-based operations on objects (i.e. search).

**Describe the solution you'd like**

Bucket Notification events should include non-internal metadata and tags for `PutObject` and `PutObjectTagging` ops

**Comment by harshavardhana** [comment]
> In local testing, it seems that `PutObject` and `PutObjectTagging` event notifications do not include the object tags.

We also notify `x-amz-meta` - I think that is sufficient for any search based lookups. - This is an extension to S3 behavior already.

**Comment by ravindk89** [comment]
I'll defer to you here @harshavardhana - not sure how common it is to use tags vs meta for search. I think based on this, it might make sense to at some point put a doc together on using meta + notifs + external search and just not talking about tags for external search?

**Comment by harshavardhana** [comment]
> I'll defer to you here @harshavardhana - not sure how common it is to use tags vs meta for search. I think based on this, it might make sense to at some point put a doc together on using meta + notifs + external search and just not talking about tags for external search?

I think it is better to close this out and revist this in future if needed.
