### ISSUE TITLE
Encryption at gateway not working

### ISSUE THREAD

**Issue by Xartos** [minio/minio#13090]
**Note:** Maybe I misunderstand the documentation but as I understand it when setting up minio gateway in single encryption mode the files get encrypted **in** the gateway and then sent to the backing s3 without encryption it at server side. Thus eliminating the need of supporting server-side encryption both at the client and the backing object storage.

Illustration of my assumption:

```
                        MinIO in Gateway mode
                      ┌─────────────────────────────────────┐
                      │                                     │
┌───────────┐ No SSE  ├────────────────┐       ┌────────────┤ No SSE  ┌─────────────┐
│ S3-client ├────────►│ Minio frontend ├──────►│ Encryption ├────────►│ Backing S3  │
└───────────┘         ├────────────────┘       └────────────┤         └─────────────┘
                      │                                     │
                      └─────────────────────────────────────┘
```

If this assumption is wrong, then this issue is obsolete.

## Expected Behavior

Starting MinIO in gateway mode with single encryption enabled I expect the files sent to minio to be encrypted and then the encrypted files are sent to the backing S3 without any server side encryption.

## Current Behavior

When I send a file to minio (no SSE configured at the client), minio adds a SSE header to the request that is going to the backing S3. If the backing S3 doesn't support SSE it will respond with a "InvalidRequest" error and no more message.

## Steps to Reproduce (for bugs)

1. Set the following environment variables
```bash
MINIO_ROOT_PASSWORD=secret-key
MINIO_ROOT_USER=access-key
MINIO_KMS_SECRET_KEY=kms-key:some-random-secret
MINIO_KMS_AUTO_ENCRYPTION=on
```
2. Start minio in gateway mode
```bash
minio gateway s3 https://s3-backend.com
```
3. Try to upload a file via minio
```console
$ mc cp test.txt minio/my-bucket/
mc: <ERROR> Failed to copy `test.txt`. Error response code InvalidRequest.

$ mc --debug cp test.txt minio/my-bucket/
.
.
.
mc: <DEBUG> PUT /my-bucket/test.txt HTTP/1.1
Host: 1.2.3.4:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/DEVELOPMENT.2021-06-13T18-09-40Z
Content-Length: 177
Authorization: AWS4-HMAC-SHA256 Credential=3447c581b06d4f2c8d15756e48c8fca0/20210827/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Type: text/plain
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20210827T123043Z
X-Amz-Decoded-Content-Length: 5
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 295
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 27 Aug 2021 12:30:43 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 169F29B4048904C3
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message></Message><Key>test.txt</Key><BucketName>my-bucket</BucketName><Resource>/my-bucket/test.txt</Resource><RequestId>169F29B4048904C3</RequestId><HostId>39dabb8a-1ce6-453c-9fd3-1a1e39f93b96</HostId></Error>mc: <DEBUG> Response Time:  101.56399ms

mc: <ERROR> Failed to copy `test.txt`. Error response code InvalidRequest.
 (3) cp-main.go:579 cmd.doCopySession(..) Tags: [test.txt]
 (2) common-methods.go:573 cmd.uploadSourceToTargetURL(..) Tags: [test.txt]
 (1) common-methods.go:326 cmd.putTargetStream(..) Tags: [minio, http://1.2.3.4:9000/my-bucket/test.txt]
 (0) client-s3.go:1056 cmd.(*S3Client).Put(..)
 Release-Tag:DEVELOPMENT.2021-06-13T18-09-40Z | Commit:2c52cdf27c7b | Host:minio-gateway-6b8b487f76-4gxj5 | OS:linux | Arch:amd64 | Lang:go1.16.5 | Mem:3.2 MB/75 MB | Heap:3.2 MB/66 MB
```

Requests traced from minio to backend:
```
---------START-HTTP---------
PUT /my-bucket/test.txt/.minio/data HTTP/1.1
Host: s3-backend.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.13
Content-Length: 37
Authorization: AWS4-HMAC-SHA256 Credential=3447c581b06d4f2c8d15756e48c8fca0/20210827/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-server-side-encryption;x-amz-server-side-encryption-context, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210827T123118Z
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Context: bnVsbA==
Accept-Encoding: gzip

HTTP/1.1 400 Bad Request
Content-Length: 232
Accept-Ranges: bytes
Content-Type: application/xml
Date: Fri, 27 Aug 2021 12:31:18 GMT
X-Amz-Request-Id: tx00000000000000833ce4f-006128db16-110c43f-default

<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRequest</Code><BucketName>my-bucket</BucketName><RequestId>tx00000000000000833ce4f-006128db16-110c43f-default</RequestId><HostId>110c43f-default-default</HostId></Error>---------END-HTTP---------
```

Here we can clearly see that minio is adding the `X-Amz-Server-Side-Encryption` flags to the requests to the backend

## Context

I'm trying to setup minio to be a transparent encryption proxy so that the clients uploading doesn't need to have encryption support and the backing S3 doesn't need to have support for it. 

## Regression

No

## Your Environment

* Version used (`minio --version`): RELEASE.2021-08-25T00-41-18Z
* Server setup and configuration: See "Steps to Reproduce"
* Operating System and version (`uname -a`): docker container

**Comment by Xartos** [comment]
One thing to add is that it's a swift s3 backend this issue occurs.
I tried Exoscale S3 and that works without any issues and [it doesn't support server side encryption](https://community.exoscale.com/documentation/storage/quick-start/#s3-unsupported-features)

So I guess the main issue is that swift S3 (without SSE support) don't like when you have the `X-Amz-Server-Side-Encryption` header and responds with this error, while exoscale just ignores the header and proceeds.

**Comment by Xartos** [comment]
Sorry for spamming, but I just confirmed my suspicions.

If I modify [this](https://github.com/minio/minio/blob/master/cmd/gateway/s3/gateway-s3.go#L469-L473) to:

```go
	putOpts := miniogo.PutObjectOptions{
		UserMetadata:         opts.UserDefined,
		ServerSideEncryption: nil,
		UserTags:             tagMap,
	}
```

Then I get it to work as I want it to. So I guess somewhere in the code it thinks that I want to have SSE enabled and adds the header. So I guess there would need to be a way for forcing it to not use SSE?

**Comment by harshavardhana** [comment]
Closing as duplicate of #12335
