### ISSUE TITLE
StatObject on non-existing key crashes for azure

### ISSUE THREAD

**Issue by Vafilor** [minio/minio#13101]
## Expected Behavior
When you attempt to run `stat` on a non-existant key, you should get an error response with `NoSuchKey`.

## Current Behavior

Minio crashes with 

```Can't make a deep copy of the http.Request because at least one of the following is not nil:TransferEncoding, Form, PostForm, MultipartForm, or Trailer.```

and you get a `connection closed` response.

## Possible Solution

N/A
[minio_error.log](https://github.com/minio/minio/files/7073253/minio_error.log)

## Steps to Reproduce (for bugs)

1. Run docker as follows, providing username and password for an azure gateway
```
docker run \
 -p 9000:9000 \
 -p 9001:9001 \
 --name azure-s3 \
 -e "MINIO_ROOT_USER=<username>" \
 -e "MINIO_ROOT_PASSWORD=<password>" \
 minio/minio:RELEASE.2021-08-25T00-41-18Z gateway azure --console-address ":9001"
```

2.  Use this program, filling in credentials, and a non-existing file name. https://github.com/minio/minio-go/blob/master/examples/s3/statobject.go
3. Observe container crash

## Context
I'm writing a "check" to make sure the artifact repository and permissions are correctly set up. Part of this is checking if a file exists, so I know if I can create a file by that name or not.

## Regression
Yes. It was working in `RELEASE.2021-06-17T00-10-46Z.hotfix.49f6035b1`

## Your Environment

* Version used: `RELEASE.2021-08-25T00-41-18Z` 
* Server setup and configuration: docker container running locally, run an API request against it.
* Operating System and version (`uname -a`): `

```
Darwin andrey-macbook.local 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64
```

**Comment by harshavardhana** [comment]
This crash seems to be inside azure library

```
2021/08/26 23:18:52 http: panic serving 172.17.0.1:65194: Can't make a deep copy of the http.Request because at least 
one of the following is not nil:TransferEncoding, Form, PostForm, MultipartForm, or Trailer.
goroutine 544 [running]:
```

Because of this code

```
github.com/Azure/azure-pipeline-go/pipeline.Request.Copy(0xc0001ff500, 0x33c97c1)
        github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/request.go:79 +0x415
github.com/Azure/azure-storage-blob-go/azblob.(*storageError).Error(0xc0006fc5a0, 0xc000644480, 0xc000466b88)
        github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:74 +0x505
github.com/Azure/azure-pipeline-go/pipeline.WriteRequestWithResponse(0xc000644480, 0xc0001ff400, 0xc001386360, 0x45134
c0, 0xc0006fc5a0)
```

Opened an upstream issue https://github.com/Azure/azure-storage-blob-go/issues/304

**Comment by vadmeste** [comment]
It looks like upgrading Azure blob library fixes this issue. Testing with mint now.

**Comment by vadmeste** [comment]
Upgrading Azure library fixes stat issues but the crash still happens when running mint it.

It looks like this commit https://github.com/minio/minio/commit/a2cd3c9a1d138f4d1cc65ef6f06041e041508713 is causing the issue.

**Comment by fmuyassarov** [comment]
> Upgrading Azure library fixes stat issues but the crash still happens when running mint it.
> 
> It looks like this commit [a2cd3c9](https://github.com/minio/minio/commit/a2cd3c9a1d138f4d1cc65ef6f06041e041508713) is causing the issue.

I have tested with MinIO container image that was built before that commit landed and I'm not seeing MinIO crashing anymore.
Image: ` minio/minio:RELEASE.2021-07-22T05-23-32Z`

**Comment by vadmeste** [comment]
@fmuyassarov yes I sent a PR which is under review now.
