### ISSUE TITLE
Minio disk space is slowly running out(file not found (cmd.StorageErr))

### ISSUE THREAD

**Issue by rvadim** [minio/minio#13116]
The disk space of a working minio cluster is slowly running out. At the same time, the size of the buckets does not grow or does not grow equally. There are a lot of errors at the logs of each minio node:
```
{"deploymentid":"776475dd-8193-4864-a757-09f8af1bd12d","level":"ERROR","errKind":"MINIO","time":"2021-08-31T13:29:18.354630938Z","api":{"name":"SYSTEM","args":{}},"error":{"message":"file not found (cmd.StorageErr)","source":["cmd/metacache-set.go:683:cmd.(*erasureObjects).saveMetaCacheStream.func3()","cmd/metacache-stream.go:774:cmd.newMetacacheBlockWriter.func1.2()","cmd/metacache-stream.go:790:cmd.newMetacacheBlockWriter.func1()"]}}
```
When you restart the nodes, the space is quickly freed(in our case near 10%) up and there are no errors for a while.

![screenshot 2021 08 31-15_42_56](https://user-images.githubusercontent.com/7434399/131513791-d97072de-a098-4348-9020-c5f7b1a4cdcd.png)
![screenshot 2021 08 31-15_44_51](https://user-images.githubusercontent.com/7434399/131513658-189bdafa-0771-4b93-b166-2daa8c8712c2.png)

## Expected Behavior
No need to regulary restart minio nodes, due to nodes restarts cause errors.

## Current Behavior
Several terabytes of disk space disappears in 2-3 days.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
Unknown, maybe just regular usage.

## Regression
Yes, after upgrade to `RELEASE.2021-08-05T22-01-19Z`

## Your Environment
* Version used (`minio --version`): `RELEASE.2021-08-05T22-01-19Z`
* Server setup and configuration:  Kuberetes 2 zones with statefulset
* Operating System and version (`uname -a`): `Linux app74 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
```
      - args:
        - minio
        - server
        - --json
        - https://minio-z0-{0...3}.minio-z0.it.svc:9000/data{0...3}
        - https://minio-z1-{0...3}.minio-z1.it.svc:9000/data{0...3}
```

**Comment by rvadim** [comment]
The same effect for inodes:
![screenshot 2021 08 31-15_56_59](https://user-images.githubusercontent.com/7434399/131515692-f2e077d5-40ee-4ed6-af47-72d8bafbcaca.png)

**Comment by rvadim** [comment]
Forgot to write, reproduced twice.

**Comment by klauspost** [comment]
@rvadim Listings will persist some state, that will live up to 15 minutes after the listing finished. Also to speed up "deleting" the data is moved to `/.minio.sys/tmp` before being picked up and deleted by another process.

You can try upgrading to the latest version, some things have changed. 

If it is still the same, it would be great to know which folders the data is placed in, so we know where the data is being kept alive.

**Comment by klauspost** [comment]
The `file not found` indicates that lists are being generated, but are aborted/deleted after 15 minutes. I submitted #13119 that removes the error since it is harmless.

**Comment by rvadim** [comment]
@klauspost thank you! I will try to upgrade to latest version.

**Comment by harshavardhana** [comment]
> @klauspost thank you! I will try to upgrade to latest version.

Closing this @rvadim please upgrade and let us know.
