### ISSUE TITLE
The number of buckets is incorrect

### ISSUE THREAD

**Issue by wzc900810** [minio/minio#13130]
Hosts configuration：
CPU：2C
MEMORY：8G
OS：Amazon Linux release 2 (Karoo)

Minio running on 4 different hosts with 4 disks and the following is my docker-compose configuration：
version: '3'

services:
  minio1:
    image: docker-image.paxengine.com.cn/public/minio:RELEASE.2021-07-15
    container_name: minio1
    hostname: minio1
    restart: always
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxx
      - MINIO_API_REQUESTS_MAX=30
      - GOGC=10
    extra_hosts:
      - "minio1:192.168.238.130"
      - "minio2:192.168.238.131"
      - "minio3:192.168.238.132"
      - "minio4:192.168.238.133"
    command: server --address ":9000" --console-address ":9001" http://minio{1...4}/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

The number of buckets from the prometheus monitor and the console dashboard does not match the number of buckets from the console buckets and the number from the mc ls command

![prometheus](https://user-images.githubusercontent.com/6902998/131777026-f3342116-b790-4dd5-95b8-30834271aa4c.jpg)
![console_dashboard](https://user-images.githubusercontent.com/6902998/131777027-d0d7108a-2d15-420c-b983-18fa51d61224.jpg)
![console_buckets](https://user-images.githubusercontent.com/6902998/131777034-2677134b-2506-49ac-867e-074f48906276.jpg)
![mc ls](https://user-images.githubusercontent.com/6902998/131777037-54f5569d-28fa-4e75-828e-5def04f165f4.jpg)

**Comment by harshavardhana** [comment]
@wzc900810 when did you create these buckets ?

**Comment by harshavardhana** [comment]
> image: docker-image.paxengine.com.cn/public/minio:RELEASE.2021-07-15

Also please upgrade to latest 

```
- MINIO_API_REQUESTS_MAX=30
- GOGC=10
```

Not sure why you have these random settings ..

**Comment by wzc900810** [comment]
> @wzc900810 when did you create these buckets ?

The time created is in the screenshot of the mc ls command, the time is Beijing time

**Comment by wzc900810** [comment]
> > image: docker-image.paxengine.com.cn/public/minio:RELEASE.2021-07-15
> 
> Also please upgrade to latest
> 
> ```
> - MINIO_API_REQUESTS_MAX=30
> - GOGC=10
> ```
> 
> Not sure why you have these random settings ..

I've updated to the latest version(RELEASE.2021-08-31T05-46-54Z), but it's still the same

`- MINIO_API_REQUESTS_MAX=30
- GOGC=10
`
You told me about these settings  https://github.com/minio/minio/issues/12881

**Comment by harshavardhana** [comment]
> I've updated to the latest version(RELEASE.2021-08-31T05-46-54Z), but it's still the same
> 
> >

The bucket should appear after the scanner has scanned the namespace, it won't show up right away- - I see that you created the bucket just now. @wzc900810

**Comment by wzc900810** [comment]
> > I've updated to the latest version(RELEASE.2021-08-31T05-46-54Z), but it's still the same
> > >
> 
> The bucket should appear after the scanner has scanned the namespace, it won't show up right away- - I see that you created the bucket just now. @wzc900810

In the test environment, it has been 20 hours since the bucket was created and it still does not show

**Comment by harshavardhana** [comment]
> In the test environment, it has been 20 hours since the bucket was created and it still does not show

yes if you have really slow hardware and your others buckets are taking longer to scan. Updating the new buckets will take time.

**Comment by harshavardhana** [comment]
As you can see now its showing '4' buckets.

**Comment by wzc900810** [comment]
> Do not see any issue here, just your deployment is slow.

Okay, I got it, thanks.

**Comment by wzc900810** [comment]
> Do not see any issue here, just your deployment is slow.

Is the time of scanning related to the number of objects? The more objects, the longer it takes?

**Comment by harshavardhana** [comment]
> Is the time of scanning related to the number of objects? The more objects, the longer it takes?

Yes that is correct.
