### ISSUE TITLE
Not login MinIO Console

### ISSUE THREAD

**Issue by dboc** [minio/minio#13137]
Hi,

I update a MinIO Server(16 server,2 disk) and I can't login in MinIO Console using the MINIO_ROOT_USER and MINIO_ROOT_PASSWORD. I have been using this specific MinIO before the new MinIO Console.
With MINIO_ROOT_USER and MINIO_ROOT_PASSWORD I use 'mc' client and work normally, but did not work in MinIO Console.

I try this solution: https://github.com/minio/minio/issues/12964 but it not works.

## Expected Behavior

Login in MinIO Console with MINIO_ROOT_USER and MINIO_ROOT_PASSWORD.

## Current Behavior

NOT Login in MinIO Console with MINIO_ROOT_USER and MINIO_ROOT_PASSWORD.

## Steps to Reproduce (for bugs)

Try to login in http://x.x.x.101:9010 , image below

![minio_error](https://user-images.githubusercontent.com/7704278/131915780-f663acf4-711b-4c5c-988a-e11e50a10990.png)

Response:
```
"response": {
  "status": 401,
  "statusText": "Unauthorized",
  "httpVersion": "HTTP/1.1",
  "headers": [
    {
      "name": "Content-Type",
      "value": "application/json"
    },
    {
      "name": "Server",
      "value": "MinIO Console"
    },
    {
      "name": "X-Content-Type-Options",
      "value": "nosniff"
    },
    {
      "name": "X-Frame-Options",
      "value": "DENY"
    },
    {
      "name": "X-Xss-Protection",
      "value": "1; mode=block"
    },
    {
      "name": "Date",
      "value": "Thu, 02 Sep 2021 20:34:41 GMT"
    },
    {
      "name": "Content-Length",
      "value": "73"
    },
    {
      "name": "Connection",
      "value": "close"
    }
    ],
  "cookies": [],
  "content": {
    "mimeType": "application/json",
    "size": 73,
    "text": "{\"code\":401,\"detailedMessage\":\"invalid Login\",\"message\":\"invalid Login\"}\n"
  },
  "redirectURL": "",
  "headersSize": 249,
  "bodySize": 322
},
```

Trace:
`mc admin trace cluster`
```
2021-09-02T17:34:21:000 [200 OK] sts.AssumeRole x.x.x.101:9000/ x.x.x.101    634.926ms    ↑ 126 B ↓ 1.1 KiB
```

Describing my environment

* 16 Server with 2 disk(500GB)
`minio admin info`
```
●  x.x.x.101:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.102:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.103:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.104:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.105:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.106:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.107:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.108:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.109:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.110:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.111:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.112:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.113:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.114:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.115:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

●  x.x.x.116:9000
   Uptime: 7 minutes
   Version: 2021-08-31T05:46:54Z
   Network: 16/16 OK
   Drives: 2/2 OK

7.9 TiB Used, 3 Buckets, 20,949,849 Objects
32 drives online, 0 drives offline
```

MinIO Version:
`minio --version`
```
Minio version RELEASE.2021-08-31T05-46-54Z
```
O.S.:
`uname -a`
```
Linux MACHINE01 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
```

`cat /etc/systemd/system/minio.service`

```
[Unit]
Description=Minio Server
After=network-online.target
Wants=network-online.target

[Service]
User=minio
Group=minio

WorkingDirectory=/opt/minio
EnvironmentFile=/opt/minio/vars
ExecStart=/usr/local/bin/minio server http://x.x.x.{101...116}/mnt/disk{01...02}/tenant0 --console-address ":9010"

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```

`cat /opt/minio/vars`
```
MINIO_ROOT_USER='myrootkey'
MINIO_ROOT_PASSWORD='mypassword'
MINIO_PROMETHEUS_AUTH_TYPE='public'
MINIO_UPDATE='on'
MINIO_STORAGE_CLASS_STANDARD='EC:2'
```

`ls -alh /opt/minio`
```
drwxr-xr-x 2 minio minio 4,0K set  2 15:15 .
drwxr-xr-x 3 root  root  4,0K jun 16 10:19 ..
-rwxr-xr-x 1 minio minio  21M ago 18 11:09 mc
-rwxr-xr-x 1 minio minio  89M set  2 15:15 minio
-rw-r--r-- 1 minio minio  160 ago 17 16:26 vars
```

`ls -alh /usr/local/bin/minio`
```
lrwxrwxrwx 1 root root 16 jun 18 13:32 /usr/local/bin/minio -> /opt/minio/minio
```

## Context

I have been using this specific MinIO before the new MinIO Console. When the MinIO Console was embededd in MinIO I try to use it but unsuccessfully.
But I can still use MinIO with mc client and the API.

I cannot do another fresh MinIO install because I have a lot of data!

## Regression

No

## Your Environment

* Version used (`minio --version`):

`minio --version`
```
Minio version RELEASE.2021-08-31T05-46-54Z
```
* Server setup and configuration:
See the section 'Steps to Reproduce (for bugs)'
* Operating System and version (`uname -a`):
O.S.:
`uname -a`
```
Linux MACHINE01 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@dboc please share the server logs here.. also when you are logging into the server do `mc admin trace -a --funcname admin* --funcname sts* -v` and share the results here.

**Comment by harshavardhana** [comment]
> 7.9 TiB Used, 3 Buckets, 20,949,849 Objects
> 32 drives online, 0 drives offline

Also remember if you are using MinIO AGPLv3 version under commercial project you are violating the licensing terms here. 

You are advised to get a subscription from us to get a license exception from us https://min.io/pricing

**Comment by harshavardhana** [comment]
> ```
> 2021-09-02T17:34:21:000 [200 OK] sts.AssumeRole x.x.x.101:9000/ x.x.x.101    634.926ms    ↑ 126 B ↓ 1.1 KiB
> ```

This shows that credentials were obtained - there is an admin call that seems to have failed here subsequently.

**Comment by dboc** [comment]
Hi @harshavardhana 

Here the log:

`mc admin trace cluster -a --funcname admin* --funcname sts* -v`

```
x.x.x.101:9000 [REQUEST sts.AssumeRole] [2021-09-03T14:26:35:000] [Client IP: x.x.x.101]
x.x.x.101:9000 POST /
x.x.x.101:9000 Proto: HTTP/1.1
x.x.x.101:9000 Host: x.x.x.101:9000
x.x.x.101:9000 Authorization: AWS4-HMAC-SHA256 Credential=administrator/20210903//sts/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=5cc7b3efec0dd1619a9381e73e098dd27de0bc79254b8a13c303b91922245981
x.x.x.101:9000 Content-Length: 57
x.x.x.101:9000 Content-Type: application/x-www-form-urlencoded
x.x.x.101:9000 User-Agent: Go-http-client/1.1
x.x.x.101:9000 X-Amz-Date: 20210903T172635Z
x.x.x.101:9000 Action=AssumeRole&DurationSeconds=3600&Version=2011-06-15
x.x.x.101:9000 [RESPONSE] [2021-09-03T14:26:36:000] [ Duration 919.599ms  ↑ 126 B  ↓ 1.1 KiB ]
x.x.x.101:9000 200 OK
x.x.x.101:9000 Accept-Ranges: bytes
x.x.x.101:9000 Content-Type: application/xml
x.x.x.101:9000 Server: MinIO
x.x.x.101:9000 Vary: Origin
x.x.x.101:9000 X-Amz-Request-Id: 16A15FE94113E75D
x.x.x.101:9000 X-Content-Type-Options: nosniff
x.x.x.101:9000 X-Xss-Protection: 1; mode=block
x.x.x.101:9000 Content-Length: 772
x.x.x.101:9000 Content-Security-Policy: block-all-mixed-content
x.x.x.101:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
x.x.x.101:9000 <?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><AssumeRoleResult><AssumedRoleUser><Arn></Arn><AssumeRoleId></AssumeRoleId></AssumedRoleUser><Credentials><AccessKeyId>1QLBVC7EQ47AK4H44JSS</AccessKeyId><SecretAccessKey>MgVJBVIMIGB0sy1HVYlWvgNTpS9RtaJww7ro3rJk</SecretAccessKey><Expiration>2021-09-03T18:26:35Z</Expiration><SessionToken>eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIxUUxCVkM3RVE0N0FLNEg0NEpTUyIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoiY29uc29sZUFkbWluIn0.9YPO2aSB_uIh21t56GAsOXyIM7srsQ-pEf_iaYpAKG3WVM4CzTaEDw8R-_jwgioaOsUg5ubUvEZOX6JEuI8HTQ</SessionToken></Credentials></AssumeRoleResult><ResponseMetadata><RequestId>16A15FE94113E75D</RequestId></ResponseMetadata></AssumeRoleResponse>
x.x.x.101:9000
```

About the license, we are not using in a commercial software, this specific MinIO are not a production environment, we are testing it to be use in an governmental software. And we are in contact with Niase, Kris and Sriraj to contract MinIO Support ... but there is a long way burocracy that we are solving.

**Comment by harshavardhana** [comment]
> `mc admin trace cluster -a --funcname admin* --funcname sts* -v`

Looks like the `admin` call was never triggered here and there is no mention of that.  Do you have some kind of proxy in between UI and MinIO? 

> About the license, we are not using in a commercial software, this specific MinIO are not a production environment, we are testing it to be use in an governmental software. And we are in contact with Niase, Kris and Sriraj to contract MinIO Support ... but there is a long way burocracy that we are solving.

Understood @dboc

**Comment by dboc** [comment]
No, there is not a proxy between.

I have a similar MinIO, a minor environment with 5 servers and 2 disk each, in the same subnetwork.
And that MinIO it works, and in MinIO with 16 server and 2 disck each do not work.

These environments its about the same, only the difference is the credentials, IPs and the amount of data in it.
I tryied about everithing to solve it,  I looked for some configuration diferrence between then... but nothing. The unique difference its that 16 machines have the same UUID Disk because i had to clone these VMs to deploy minio after, but I believe that is not affect MinIO

Here is the log with a similar MinIO, a minor environment with 5 servers and 2 disk each, in the same subnetwork. Here it works
`mc admin trace cluster-minor -a --funcname admin* --funcname sts* -v`

```
x.x.x.51:9000 [REQUEST sts.AssumeRole] [2021-09-03T19:11:19:000] [Client IP: x.x.x.51]
x.x.x.51:9000 POST /
x.x.x.51:9000 Proto: HTTP/1.1
x.x.x.51:9000 Host: x.x.x.51:9000
x.x.x.51:9000 Authorization: AWS4-HMAC-SHA256 Credential=admin123/20210903//sts/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=914ed7c9509f38d7f4d6dcc0a7c7aff510d17f898d5d202a2140ed45a9b0c0ff
x.x.x.51:9000 Content-Length: 57
x.x.x.51:9000 Content-Type: application/x-www-form-urlencoded
x.x.x.51:9000 User-Agent: Go-http-client/1.1
x.x.x.51:9000 X-Amz-Date: 20210903T191119Z
x.x.x.51:9000 Action=AssumeRole&DurationSeconds=3600&Version=2011-06-15
x.x.x.51:9000 [RESPONSE] [2021-09-03T19:11:19:000] [ Duration 110.763ms  ↑ 126 B  ↓ 1.1 KiB ]
x.x.x.51:9000 200 OK
x.x.x.51:9000 X-Amz-Request-Id: 16A165A06EED5422
x.x.x.51:9000 X-Content-Type-Options: nosniff
x.x.x.51:9000 X-Xss-Protection: 1; mode=block
x.x.x.51:9000 Accept-Ranges: bytes
x.x.x.51:9000 Content-Type: application/xml
x.x.x.51:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
x.x.x.51:9000 Vary: Origin
x.x.x.51:9000 Content-Length: 772
x.x.x.51:9000 Content-Security-Policy: block-all-mixed-content
x.x.x.51:9000 Server: MinIO
x.x.x.51:9000 <?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><AssumeRoleResult><AssumedRoleUser><Arn></Arn><AssumeRoleId></AssumeRoleId></AssumedRoleUser><Credentials><AccessKeyId>R5ZL2EFT1A2HDT4Z7XMN</AccessKeyId><SecretAccessKey>olwJBlKJaSd5UGytRGr+O8cXUWmLj6ANJkJF+vhh</SecretAccessKey><Expiration>2021-09-03T20:11:19Z</Expiration><SessionToken>eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJSNVpMMkVGVDFBMkhEVDRaN1hNTiIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoiY29uc29sZUFkbWluIn0.-LDqiRWhbwx3a3vsD3sHvvns-DTMkmqbI7YFKrQNEIU0f3tXCjrSiLh-fPh6iDSdaBQpFBZVrMrwWHxzsiHfZA</SessionToken></Credentials></AssumeRoleResult><ResponseMetadata><RequestId>16A165A06EED5422</RequestId></ResponseMetadata></AssumeRoleResponse>
x.x.x.51:9000
x.x.x.51:9000 [REQUEST admin.AccountInfo] [2021-09-03T19:11:19:000] [Client IP: x.x.x.51]
x.x.x.51:9000 GET /minio/admin/v3/accountinfo?prefix-usage=true
x.x.x.51:9000 Proto: HTTP/1.1
x.x.x.51:9000 Host: x.x.x.51:9000
x.x.x.51:9000 X-Amz-Date: 20210903T191119Z
x.x.x.51:9000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJSNVpMMkVGVDFBMkhEVDRaN1hNTiIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoiY29uc29sZUFkbWluIn0.-LDqiRWhbwx3a3vsD3sHvvns-DTMkmqbI7YFKrQNEIU0f3tXCjrSiLh-fPh6iDSdaBQpFBZVrMrwWHxzsiHfZA
x.x.x.51:9000 Authorization: AWS4-HMAC-SHA256 Credential=R5ZL2EFT1A2HDT4Z7XMN/20210903//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=7cde5fa07f06830d3f1396b9284728f4d89eec7c3ed70fb3af47bb740db285be
x.x.x.51:9000 Content-Length: 0
x.x.x.51:9000 User-Agent: MinIO (linux; amd64) madmin-go/0.0.1
x.x.x.51:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x.x.x.51:9000
x.x.x.51:9000 [RESPONSE] [2021-09-03T19:11:20:000] [ Duration 730.045ms  ↑ 98 B  ↓ 3.1 MiB ]
x.x.x.51:9000 200 OK
x.x.x.51:9000 Accept-Ranges: bytes
x.x.x.51:9000 Content-Security-Policy: block-all-mixed-content
x.x.x.51:9000 Content-Type: application/json
x.x.x.51:9000 Server: MinIO
x.x.x.51:9000 Vary: OriginAccept-Encoding
x.x.x.51:9000 X-Amz-Request-Id: 16A165A075A38FBD
x.x.x.51:9000 X-Xss-Protection: 1; mode=block
x.x.x.51:9000 Content-Length: 3247580
x.x.x.51:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
x.x.x.51:9000 X-Content-Type-Options: nosniff
x.x.x.51:9000 {"AccountName":"R5ZL2EFT1A2HDT4Z7XMN","Server":{"Type":2,"GatewayOnline":false,"OnlineDisks":null,"OfflineDisks":null,"StandardSCData":[8],"StandardSCParity":2,"RRSCData":[8],"RRSCParity":2},"Policy":{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["admin:*"]},{"Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::*"]}]},"Buckets":[{"name":"documento-eletronico","size":60131989295,"prefixUsage":{"0001a025-d14e-42c6-bc00-108b13066ca2.pdf":92086,"0002920c-4ecc-4497-a0a6-d132cea9408d.pdf":112552,"0004d75d-92ae-4882-bfb9-ad52134c8137.pdf":95041,"00055b1b-cb1a-4067-8f42-e51154c0b233.pdf":355805,"000e34c9-2845-4031-b904-dc918b86dbbc.pdf":138791,"000ea31d-369e-4bb0-9753-c8d00b5b7e34.pdf":355743,"001168ed-fc2c-4939-9e1d-437176332b81.pdf":132464,"00124545-6b4b-4ed6-8d29-f442d5eee1ca.pdf":421353,"00137e14-df19-4b59-9b76-7a4ef0984eb6.pdf":419609,"001387f4-939e-4801-b7c9-24f06cb97e76.pdf":133775,"00169ffe-d302-44bd-a155-1ff306729425.pdf":356463,"00185cd1-ca1f-4d75-bb70-50f199df39cd.pdf":443854,"001bc..................................
```

Are there another trace that i could run? what you suggest!? Deploy MinIO Console apart?

**Comment by harshavardhana** [comment]
> Are there another trace that i could run? what you suggest!? Deploy MinIO Console apart?

As you can see `AccountInfo` needs to work, if that doesn't work there is some other network communication issue to MinIO inside the console UI. 

@dboc would be possible to provide direct access to nodes using ssh keys? https://github.com/harshavardhana.keys

**Comment by dboc** [comment]
Thanks @harshavardhana 
I will talk to our security office about how we can provide your access. 
Unfortunately, we will have to schedule it, I am out of office from today until 07/09. 
I will let you know.

**Comment by harshavardhana** [comment]
> I will talk to our security office about how we can provide your access.
> Unfortunately, we will have to schedule it, I am out of office from today until 07/09.
> I will let you know.

Sure @dboc

**Comment by gstorme** [comment]
I have a similar problem after upgrading from RELEASE.2020-05-01T22-19-14Z to RELEASE.2021-06-07T21-40-51Z, and then to RELEASE.2021-09-03T03-56-13Z.
Since RELEASE.2021-09-03T03-56-13Z I cannot logon to the new console, but admin access with `mc` is still working.

I run a single minio instance in docker.
The `mc admin trace minio --funcname admin* --funcname sts* -v` does not show anything, `mc admin trace minio` gives output, but doesn't show any of the login attempts.

I get this after trying to login on console:

![image](https://user-images.githubusercontent.com/3859276/132516314-85dea086-1d30-483e-9546-fe167b55fd9c.png)

**Comment by vadmeste** [comment]
@gstorme if you are not able to see admin trace output, then this is a different issue. Please create a new issue.

**Comment by dboc** [comment]
@harshavardhana 
I sended a private mensagem to your email with instruction how to access the nodes.

**Comment by harshavardhana** [comment]
> @harshavardhana 
> I sended a private mensagem to your email with instruction how to access the nodes.

Thanks

**Comment by dboc** [comment]
Hi @harshavardhana 

As you think that are the VM cloning, we will reconstruct all the VMs.
I will destroy one VM, then create another one and wait to MinIO reconstruct the data...I will do this for all 16 VMs.

Maybe this will spend 2 weeks, I will let you know when I done, then I will test MinIO Console again.

**Comment by harshavardhana** [comment]
> As you think that are the VM cloning, we will reconstruct all the VMs.
> I will destroy one VM, then create another one and wait to MinIO reconstruct the data...I will do this for all 16 VMs.

Okay @dboc

**Comment by harshavardhana** [comment]
Going to close this out @dboc since we have upgraded the console release please test again.

**Comment by dboc** [comment]
@harshavardhana Great! It works!
We had been reconstructing the cluster, but now that works, we stop it and we are making some test. 

Thanks a lot!

**Comment by harshavardhana** [comment]
> @harshavardhana Great! It works! We had been reconstructing the cluster, but now that works, we stop it and we are making some test.
> 
> Thanks a lot!

👍🏽
