### ISSUE TITLE
buckets are not shown to logged in ldapuser, if policy is set to group 

### ISSUE THREAD

**Issue by hillar** [minio/minio#13136]
## Expected Behavior

if policy is set to ldap group 
`mc admin policy set <alias> readonly group='cn=...' `
all ldap group members should see buckets etc ...

## Current Behavior

ldapuser can log in, but not see buckets und stuff ...

----
set up ldap config 

```
mc admin config set <alias> \
identity_ldap \
server_addr=...

```

restart to apply config

```
mc admin service restart <alias>
```

set to group policy
```
mc admin policy set <alias> readonly group='cn=...' 
```

check group info

```
mc admin group info <alias> 'cn=..'
Group: cn=...
Status: 
Policy: readonly
Members: 
```

check policy info

```
mc admin policy info <alias> readonly
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketLocation",
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
```

login to webconsole

:/

-----

workaround to fix for single user is to set 'personal policy' 

```
mc admin policy set <alias> readonly user='cn=...' 
```

## Context

to many users to have personal policies for everybody.. thats why groups are invented :/

## Your Environment

version 2021-08-31T05:46:54Z

**Comment by kannappanr** [comment]
@hillar With readonly policy, I don't think they can see the list of buckets. You should also add 
`s3:ListAllMyBuckets` permission to your policy

**Comment by harshavardhana** [comment]
> @hillar With readonly policy, I don't think they can see the list of buckets. You should also add
> `s3:ListAllMyBuckets` permission to your policy

Yes that is correct - at least we need ListBucket() permission on a specific bucket.

**Comment by hillar** [comment]
ok... however user sees list of buckets, if same policy is is applied to user.  with `mc admin policy set <alias> readonly user='cn=...' `

**Comment by hillar** [comment]
did that

```
 mc admin policy info <alias> readonly
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketLocation",
    "s3:GetObject",
    "s3:ListAllMyBuckets"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}

```
still no list for `GET /api/v1/buckets` just `{"buckets":null}`

**Comment by hillar** [comment]
RTFM problem, sorry

must be: 

```
"s3:ListBucket"
```


for working freeipa test see https://github.com/donatello/minio-ldap-testing/pull/1
