### ISSUE TITLE
Add step-by-step guide for Azure web app docker deployment

### ISSUE THREAD

**Issue by MatinF** [minio/minio#13148]
We have a number of users that wish to deploy a MinIO Azure gateway via docker on an Azure web app.

This seems like a very popular use case, yet we cannot find any online step by step tutorials. Could MinIO add an official guide for this? If not, can somebody outline the steps involved in setting this up here?

**Comment by harshavardhana** [comment]
You are not able to read here ?  

https://az.minio.io/

Referenced from https://azuremarketplace.microsoft.com/en-us/marketplace/apps/minio.minio-blob-s3-gw?tab=Overview
