### ISSUE TITLE
Storage resources are insufficient for the read operation

### ISSUE THREAD

**Issue by rvadim** [minio/minio#13141]
When disconnecting 4 disks out of 16 in one zone(1 of 4 servers), we get 500 errors and minio errors of the form:
```
Storage resources are insufficient for the read operation "..." (cmd.InsufficientReadQuorum)
```

```
        "backend": {
            "backendType": "Erasure",
            "offlineDisks": 4,
[trim_status_pretty.json.gz](https://github.com/minio/minio/files/7104110/trim_status_pretty.json.gz)

            "onlineDisks": 28,
            "rrSCParity": 2,
            "standardSCParity": 4
        },
```

## Expected Behavior
No errors.

## Current Behavior
500 errors on read and write.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Setup 4 disks 4 servers
2. Upload data
3. Stop 1 server

## Context
Users unable to download or upload data until maintenance will complete

## Regression
No idea

## Your Environment

* Version used (`minio --version`): `RELEASE.2021-08-05T22-01-19Z`
* Server setup and configuration: 2 STS in kubernetes 4 servers x 4 disks x 2 zones
```
  minio_args:
    - minio
    - server
    - --json
    - https://minio-z0-{0...3}.minio-z0.it.svc.k8s:9000/data{0...3}
    - https://minio-z1-{0...3}.minio-z1.it.svc.k8s:9000/data{0...3}
```
[trim_status_pretty.json.gz](https://github.com/minio/minio/files/7104111/trim_status_pretty.json.gz)

**Comment by harshavardhana** [comment]
@rvadim you are running two zones it is not expected to work and it is working as intended.

Each zone is self contained and tolerant. Your tolerance is not across nodes. 

Also in k8s how are you doing maintenance?  Did you just drain the pod?

**Comment by harshavardhana** [comment]
Oh wait you took down only 

> minio-z0-0minio-z0.it.svc.k8s:9000

this node, this is expected to work unless there is a call that has changed the quorum requirement. Which was the exact API that returned '500' ? 

Do you have some client log that you can share?

**Comment by harshavardhana** [comment]
> ```
> Storage resources are insufficient for the read operation "..." (cmd.InsufficientReadQuorum)
> ```

For which API do you see this error?

**Comment by rvadim** [comment]
> this node, this is expected to work unless there is a call that has changed the quorum requirement. Which was the exact API that returned '500' ?
```
{
    "path": "/docker-mirror",
    "request_query": "max-keys=1&prefix=s3%2Fdocker-mirror%2Fdocker%2Fregistry%2Fv2%2Fblobs%2Fsha256%2F73%2F73d1bee16c193b441897e07538268853b873ec91fd18a2616726afbad50faa24%2Fdata",
    "bytes_sent": 803,
    "vhost": "minio.",
    "status": 500,
    "request_proto": "HTTP/2.0",
    "upstream_response_time_float": 0.004,
    "request_length": 9,
    "method": "GET",
    "http_user_agent": "aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)",
  }
  ```
  ```
  {
    "request_proto": "HTTP/1.1",
    "method": "GET",
    "vhost": "minio.",
    "status": 500,
    "request_query": "list-type=2&prefix=&encoding-type=url&max-keys=1000&delimiter=",
    "bytes_sent": 964,
    "duration": 0.135,
    "http_referrer": "",
    "http_user_agent": "MinIO (amd64; amd64) minio-java/dev",
    "path": "/office-tv-data",
  }
  ```

**Comment by rvadim** [comment]
Ah, sorry. All but 1 error are about healing, I actually don't understand source of the 500.

**Comment by rvadim** [comment]
Full error:
error.message:
```
Storage resources are insufficient for the read operation bucket/object.log (cmd.InsufficientReadQuorum)
```
error.source:
```
cmd/global-heal.go:237:cmd.(*erasureObjects).healErasureSet.func1(), cmd/global-heal.go:269:cmd.(*erasureObjects).healErasureSet.func2(), cmd/metacache-set.go:941:cmd.listPathRaw(), cmd/global-heal.go:258:cmd.(*erasureObjects).healErasureSet(), cmd/background-newdisks-heal-ops.go:445:cmd.monitorLocalDisksAndHeal.func2()
```

**Comment by rvadim** [comment]
Also some errors are 503 from all nodes on object GET.

**Comment by harshavardhana** [comment]
Okay, that's just ListObjects that failed @rvadim is not PUT/GET operation which would have worked anyways.  Looks like this is because the docker registry wishes to do ListObjects() and that failed. 

But this wouldn't be a problem if it was retried, AFAIK this is a transient call that failed.

**Comment by harshavardhana** [comment]
> ```
> Storage resources are insufficient for the read operation bucket/object.log (cmd.InsufficientReadQuorum)
> ```

This is unrelated to taking down the node here, this is something else.

**Comment by harshavardhana** [comment]
@rvadim is there anything that you want us to look at ?
