### ISSUE TITLE
Object sharing is effective

### ISSUE THREAD

**Issue by ggdream** [minio/minio#13149]
There are many objects that need to be set with a longer validity period, and even need to be permanently open. Why is it set to a fixed value, 7 days? The currently found method must manually modify the strategy, and there is no corresponding sdk-api support. Want to know what the authors think? Why is it designed like this?

**Comment by kannappanr** [comment]
According to AWS S3, maximum presigned url expiration value is 7 days. There is no fixed value.

**Comment by harshavardhana** [comment]
> There are many objects that need to be set with a longer validity period, and even need to be permanently open. Why is it set to a fixed value, 7 days? The currently found method must manually modify the strategy, and there is no corresponding sdk-api support. Want to know what the authors think? Why is it designed like this?

AWS S3 spec mandates no more than 7 days for expiration for presigned URLs.

If you want your assets to be public all the time make sure to set those assets to be publicly readable as `mc policy set download`

**Comment by ggdream** [comment]
> > There are many objects that need to be set with a longer validity period, and even need to be permanently open. Why is it set to a fixed value, 7 days? The currently found method must manually modify the strategy, and there is no corresponding sdk-api support. Want to know what the authors think? Why is it designed like this?
> 
> AWS S3 spec mandates no more than 7 days for expiration for presigned URLs.
> 
> If you want your assets to be public all the time make sure to set those assets to be publicly readable as `mc policy set download`

Thanks
