### ISSUE TITLE
listIAMConfigItems  goroutine leak

### ISSUE THREAD

**Issue by dshmyz** [minio/minio#13152]
## Steps to Reproduce (for bugs)

1.Delete the policy file under the `.minio.sys` directory
2.Restart the Minio service

## Context

I use the 3 * 2 (3 servers and 2 disks) mode. After the policy file in one node is accidentally missing, the Minio of the other two nodes will continue to try to execute the init method during startup. In this process, I use pprof analysis and find that the number of goroutines continues to increase until the server memory overflows.

## Your Environment

* Version used (`minio --version`): minio-RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration:
* Operating System and version (`uname -a`): centos 7

**Comment by harshavardhana** [comment]
This code path is fully reimplemented. Please upgrade and test.

**Comment by harshavardhana** [comment]
> This code path is fully reimplemented. Please upgrade and test.

Closing this since this is not the same code path anymore. Please upgrade and test - let us know.
