### ISSUE TITLE
Running minio server with HTTPs / nginx reverse proxy

### ISSUE THREAD

**Issue by DatanoiseTV** [minio/minio#1315]
I am trying to reverse proxy using proxy_pass with nginx to terminate SSL.

> ./mc config host add minio https://ym3s.foo.io XXXXX YYYYY
> ./mc --debug ls minio  
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
> 0
> 
> mc: <DEBUG> Response Time:  121.218448ms
> 
> mc: <ERROR> Unable to stat ‘minio’. Bucket name cannot be empty.

Unfortunately something goes wrong.

**Comment by harshavardhana** [comment]
> I am trying to reverse proxy using proxy_pass with nginx to terminate SSL.
> 
> ./mc config host add minio https://ym3s.foo.io XXXXX YYYYY
> ./mc --debug ls minio
> 
> <?xml version="1.0" encoding="UTF-8"?>
> SignatureDoesNotMatchThe request signature we calculated does not match the signature you provided./3L1373L137
> 0
> 
> mc: Response Time: 121.218448ms
> 
> mc: Unable to stat ‘minio’. Bucket name cannot be empty.
> Unfortunately something goes wrong.

Can you paste you nginx proxy configuration? have you set properly? 

```
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
```

**Comment by DatanoiseTV** [comment]
It was my fault. proxy_headers were not set. Now it works. Thanks!
