### ISSUE TITLE
The MinIO Console page could not be loaded

### ISSUE THREAD

**Issue by ALI1416** [minio/minio#13153]
Version used: RELEASE.2021-09-03T03-56-13Z
Operating System and version: win10 pro 20H2
Browser: Google browser 93.0
Browser console output: 
![截图20210907154429382](https://user-images.githubusercontent.com/39152510/132306872-4bd9529f-7602-4d9a-b447-6bf186ebb95d.jpg)

**Comment by harshavardhana** [comment]
duplicate of https://github.com/minio/console/issues/802
