### ISSUE TITLE
console login not working after upgrade and no trace output

### ISSUE THREAD

**Issue by gstorme** [minio/minio#13162]
I am running a single minio instance in docker.
I upgraded from RELEASE.2020-05-01T22-19-14Z -> RELEASE.2021-06-07T21-40-51Z -> RELEASE.2021-09-03T03-56-13Z.
Since RELEASE.2021-09-03T03-56-13Z, I'm not able to logon with the access key/secret that I used before.
These credentials are still working fine for the `mc` commands though.

I tried #12964 but this didn't solve it, and #13137 looks similar, but the problem is that I don't get any useful output from the `mc admin trace` command.

## Expected Behavior
Minio console login works, and `mc admin trace -v` returns output when I try to logon to the console.

## Current Behavior
`mc admin trace -v` does not return any output during the console login.
It does output file operations, api calls,...

![image](https://user-images.githubusercontent.com/3859276/132542609-94d3fbd6-43d4-43d5-8ee6-24210040a95d.png)

## Steps to Reproduce (for bugs)
Hard to say, I'm not able to reproduce this myself... only occurs on my existing minio instance that I've upgraded.
I setup a fresh minio docker instance on a test server and followed the same upgade path, and both the console login and the `mc admin trace` are working as expected.

## Your Environment
Debian 4.9.88-1+deb9u1
Docker version 18.03.1-ce, build 9ee9f40
Minio version:
   Version: 2021-09-03T03:56:13Z
   Network: 1/1 OK

`docker run -d -p 9000:9000 -p 9001:9001 --name minio1 -v /var/log/minio:/data -v /etc/minio:/r
oot/.minio minio/minio:RELEASE.2021-09-03T03-56-13Z server /data --console-address ":9001"`

**Comment by harshavardhana** [comment]
Can you share `docker logs` for this instance?

**Comment by harshavardhana** [comment]
> Minio console login works, and `mc admin trace -v` returns output when I try to logon to the console.

```
mc admin trace -a -v --funcname sts* --funcname admin* 
```

**Comment by gstorme** [comment]
```
~# docker logs minio1 --tail 500
Configuration file config/config.json migrated from version '28' to '29' successfully.
Configuration file config/config.json migrated from version '29' to '30' successfully.
Configuration file config/config.json migrated from version '30' to '31' successfully.
Configuration file config/config.json migrated from version '31' to '32' successfully.
Configuration file config/config.json migrated from version '32' to '33' successfully.
Configuration file config/config.json migrated from version '33' to new KV format successfully.
API: https://172.17.0.2:9000  https://127.0.0.1:9000
Console: https://172.17.0.2:9001 https://127.0.0.1:9001
```

Yes, `mc admin trace -a -v --funcname sts* --funcname admin* minio` is the command I use to get output from the console login tries. On my production that had existing data, this does not return anything. On the fresh test instance, this returns all requests and responses.

**Comment by harshavardhana** [comment]
> API: https://172.17.0.2:9000  https://127.0.0.1:9000
> Console: https://172.17.0.2:9001 https://127.0.0.1:9001

Yes this is because the server is talking over perhaps a private IP and its not available for access. You need to set 

> MINIO_SERVER_URL=http://{hostname}:9000

**Comment by gstorme** [comment]
Oh, great it's all working again now. Thanks!

**Comment by igsol** [comment]
> You need to set
> 
> > MINIO_SERVER_URL=http://{hostname}:9000

Or you need to add server IP addresses and names into SAN of [self-signed] SSL certificates deployed on the servers, isn't it?
Of course if you need http**S**.
