### ISSUE TITLE
Internal error, malformed chunked encoding

### ISSUE THREAD

**Issue by igsol** [minio/minio#13163]
The modern Minio version returns "Internal Error". The old version works.

## Expected Behavior
No error from Minio or to permit a user set the desired limit in Minio config.

## Current Behavior
Our application has worked flawlessly with old Minio versions.
Recently we updated Minio to the latest version: RELEASE.2021-09-03T03-56-13Z

After that our application started to get errors from Minio:
`We encountered an internal error, please try again.: cause(malformed chunked encoding)`
It happens when the application uploads relatively big files.

The error message itself is quite odd, we didn't change chunk encoding.
We didn't change any settings in Minio service.

After investigation I found the guilty code: https://github.com/minio/minio/blame/1f262daf6fe369a57d8e183b3e3758644407e485/cmd/streaming-signature-v4.go#L222
So the 1MiB limit for chunk size was just hard-coded!
And if the receiving chunk size if larger than the new limit the "malformed chunked encoding" error is returned regardless the real cause
similarly with other error cases.
See https://github.com/minio/minio/blame/1f262daf6fe369a57d8e183b3e3758644407e485/cmd/streaming-signature-v4.go#L253

Our application works in the high performance environment and uses several carefully tuned parameters.
One of them is the ASW HTTP chunk size. We found that the best performance is achieved with 2MiB chunks in our environment.

## Possible Solution
With Minio I see the following problem:
1. The error message is confusing. It doesn't tell the real reason for the error.
I'd suggest returning an explicit error reason, for instance "employed chunk size exceeds the 1MiB limit".
2. Hard-coded constants should be avoided! For a software that is deployed in different environment, this "One 1 MB is a reasonable max limit" is inappropriate IMHO.  We suggest to get rid of the hard coded constant and make it a Minio configuration parameter.
3. Our application is regularly tested against many other S3 compatible cloud applications including AWS S3.
No other applications except Minio complain about large chunk sizes. And I has not been able to find some documented **upper** limit in AWS S3 API docs.
If Minio introduces this limit because you believe it's a good design, then the documentation should be updated.

## Regression
- [x] Yes, PR#: https://github.com/minio/minio/pull/11801

**Comment by harshavardhana** [comment]
We will investigate, do you have a sample code @igsol ?

**Comment by igsol** [comment]
@harshavardhana 
Unfortunately I can't provide a sample code. We used not publicly available application.

**Comment by harshavardhana** [comment]
> Unfortunately I can't provide a sample code. We used not publicly available application.

Are you using AGPLv3 MinIO with proprietary software here? @igsol

**Comment by harshavardhana** [comment]
Without a reproducer, we have nothing else to go about here as none of the AWS SDKs or MinIO SDKs have any errors. We have thousands of other customers as well using in production so I don't think this is an issue in MinIO itself. 

if you are using AGPLv3 MinIO with a proprietary code you are in violation of the license terms. We advise that you consult an expert, you are of course advised getting a subscription with us  https://min.io/pricing to avoid any violation of license terms.

**Comment by igsol** [comment]
> Are you using AGPLv3 MinIO with proprietary software here?

I use MinIO downloaded from page https://min.io/download#/linux
We don't use MinIO in the production, but for testing, because our customers could use MinIO in their production with our software.

**Comment by igsol** [comment]
> I don't think this is an issue in MinIO itself.

You want to say that hard-coded constants are not an issue, right?

**Comment by harshavardhana** [comment]
> You want to say that hard-coded constants are not an issue, right?

No, it is not an issue as per AWS S3 spec. That's why it would be interesting to know a snippet of the code if not the entire code for us to look at where it might be a problem.  AWS S3 in some places is vague, it would be helpful for us to test with AWS S3 as well. 

> We don't use MinIO in the production, but for testing, because our customers could use MinIO in their production with our software.

If your customers are using MinIO in production then they are liable as well. https://min.io/compliance should provide some guidance on this topic.

**Comment by igsol** [comment]
> No, it is not an issue as per AWS S3 spec.

From AWS docs https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

> Decide the payload chunk size. You need this when you write the code.
> 
> The chunk size must be at least 8 KB. We recommend a chunk size of a least 64 KB for better performance. This chunk size applies to all chunks except the last one. The last chunk you send can be smaller than 8 KB. If your payload is small and can fit into one chunk, then it can be smaller than the 8 KB.

So as you can see AWS has low limit, but has not upper limit. And they even urge to use "least 64 KB for better performance".
We found that MinIO has best performance if we use quite large chunks, i.e. 2MiB and with 1MiB the IOPs is just twice higher...
 
> That's why it would be interesting to know a snippet of the code if not the entire code for us to look at where it might be a problem. AWS S3 in some places is vague, it would be helpful for us to test with AWS S3 as well.

Unfortunately I can't help with snippet :( But the author of the PR#11801 could used some unit-test when he introduced the hard-coded limit. If so I guess it's not big deal to modify his test.

> If your customers are using MinIO in production then they are liable as well. https://min.io/compliance should provide some guidance on this topic.

I  would clarify this question. We as a software developers don't use code from MinIO. We don't use MinIO binaries in production and don't modify and distribute MinIO. We developing AWS S3 client code which works with many other S3-compatible service software, not limiting to MinIO. And our code is not in Go :)

How our existing or future customers use MinIO is responsibility of our customers and we can't be responsible for them ;)

**Comment by harshavardhana** [comment]
> I would clarify this question. We as a software developers don't use code from MinIO. We don't use MinIO binaries in production and don't modify and distribute MinIO. We developing AWS S3 client code which works with many other S3-compatible service software, not limiting to MinIO. And our code is not in Go :)
> 
> How our existing or future customers use MinIO is responsible of our customers and we can't be responsible for them ;)

It's not as simple as this, I would urge you to consult a software license expert (lawyer).

**Comment by harshavardhana** [comment]
> So as you can see AWS has low limit, but has not upper limit. And they even urge to use "least 64 KB for better performance".
> We found that MinIO has best performance if we use quite large chunks, i.e. 2MiB and with 1MiB the IOPs is just twice higher...

Let me check if this can be done in one of our SDKs.

**Comment by harshavardhana** [comment]
> After that our application started to get errors from Minio:
> `We encountered an internal error, please try again.: cause(malformed chunked encoding)`
> It happens when the application uploads relatively big files.
> 
> The error message itself is quite odd, we didn't change chunk encoding.
> We didn't change any settings in Minio service.

@aead ^^ can you comment here?

**Comment by igsol** [comment]
> It's not as simple as this, I would urge you to consult a software license expert (lawyer).

Thanks for your suggestion :)
