### ISSUE TITLE
Access Denied when curl, not in the browser

### ISSUE THREAD

**Issue by setop** [minio/minio#13164]
When curling "/" of minio instance, a 403 is returned.
In a webbrowser, the login is displayed.

## Expected Behavior

Same behavior in curl than in the webbrowser : a 307.

## Current Behavior
curl : 403
firefox : 307

## Possible Solution

It seems there is a filter on the user agent. If I do 'curl -A 'firefox user agent' then I get the same response as in firefox.

## Steps to Reproduce (for bugs)

1. curl https://minio.local/

## Context

I want to use GET / as part of the monitoring of the service. A 403 is reported as an error. I need a 2xx or a 3xx.

## Regression

no

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-05-22T02-34-39Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux 4.19.0-16-amd64

**Comment by harshavardhana** [comment]
This is an expected behavior @setop if you want to turn-off MinIO console UI you can setup `MINIO_BROWSER=off`

**Comment by vadmeste** [comment]
> I want to use GET / as part of the monitoring of the service. A 403 is reported as an error. I need a 2xx or a 3xx.

https://docs.min.io/docs/minio-monitoring-guide.html

**Comment by setop** [comment]
Kinda weird at first sight but make sens after all.

I'll see if I can tweak my monitoring agent.

Thanks for the quick reply.
