### ISSUE TITLE
Cluster Does stops working when 1 server goes offline

### ISSUE THREAD

**Issue by ahmedkunwar** [minio/minio#13175]
I have 3 servers each with 4 drives. as soon as i stop any 1 of these servers the cluster stops working, other 2 nodes start giving error that disks are offline.

PI: SYSTEM()
Time: 07:16:01 EDT 09/09/2021
DeploymentID: fdfe95b5-9dac-4927-a1ad-980175574732
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       2: cmd/erasure-server-pool.go:1474:cmd.(*erasureServerPools).ListBuckets()
       1: cmd/background-newdisks-heal-ops.go:376:cmd.monitorLocalDisksAndHeal()

API: SYSTEM()
Time: 07:16:11 EDT 09/09/2021
DeploymentID: fdfe95b5-9dac-4927-a1ad-980175574732
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       2: cmd/erasure-server-pool.go:1474:cmd.(*erasureServerPools).ListBuckets()
       1: cmd/background-newdisks-heal-ops.go:376:cmd.monitorLocalDisksAndHeal()

API: SYSTEM()
Time: 07:16:21 EDT 09/09/2021
DeploymentID: fdfe95b5-9dac-4927-a1ad-980175574732
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       2: cmd/erasure-server-pool.go:1474:cmd.(*erasureServerPools).ListBuckets()
       1: cmd/background-newdisks-heal-ops.go:376:cmd.monitorLocalDisksAndHeal()

API: SYSTEM()
Time: 07:16:31 EDT 09/09/2021
DeploymentID: fdfe95b5-9dac-4927-a1ad-980175574732
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       2: cmd/erasure-server-pool.go:1474:cmd.(*erasureServerPools).ListBuckets()
       1: cmd/background-newdisks-heal-ops.go:376:cmd.monitorLocalDisksAndHeal()

command that i am using to execute cluster is as follows:
minio server https://172.16.10{1.151,1.152,0.20}:9000/test/drive{1...4}

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
@ahmedkunwar Please add version information. 

It seems like you already have disks healing when you are pulling a server offline. An unhealthy system does not have the same fault tolerance as a healthy system.

**Comment by ahmedkunwar** [comment]
> @ahmedkunwar Please add version information. 
> 
> It seems like you already have disks healing when you are pulling a server offline. An unhealthy system does not have the same fault tolerance as a healthy system.

I am using latest version
RELEASE. 2021-09-03T03-56-13Z

**Comment by vadmeste** [comment]
> minio server https://172.16.10{1.151,1.152,0.20}:9000/test/drive{1...4}

You are running three pools here, this behavior is expected. All pools need to be up.

**Comment by klauspost** [comment]
Oh, that is a pool setup. Surprised me as well.

**Comment by ahmedkunwar** [comment]
> > minio server https://172.16.10{1.151,1.152,0.20}:9000/test/drive{1...4}
> 
> You are running three pools here, this behavior is expected. All pools need to be up.

What i have to do to get the required functionality so that cluster stays up even after one node is down

**Comment by klauspost** [comment]
@ahmedkunwar If you can't have a continuous ip range, use host names so you can do `https://minio-{1...3}:9000/test/drive{1...4}`.

**Comment by ahmedkunwar** [comment]
Now i am running it in cluster mode on docker using the following command

docker run -d --name minio   --restart=always   --net=host   -e MINIO_ACCESS_KEY=minio   -e MINIO_SECRET_KEY=minio123   -v /data/minio1/data1:/minio/data1   -v /data/minio1/data2:/minio/data2 -v /data/minio1/data3:/minio/data3 -v /data/minio1/data4:/minio/data4  minio/minio server --address :9000   http://host1/minio1/data{​​​​​1...4}​​​​​ \ http://host2/minio1/data{​​​​​1...4}​​​​​ 

On running this host1 gives no error but host2 gives error. Images of logs are attached below

![IMG_20210910_121124.jpg](https://user-images.githubusercontent.com/88528080/132814554-090b4afe-40b7-46fd-972c-a9a849d1cd63.jpg)

![IMG_20210910_120825.jpg](https://user-images.githubusercontent.com/88528080/132814636-af703c8c-31ef-4bdc-9a47-fbf77cb73709.jpg)

**Comment by ahmedkunwar** [comment]
Plus i have pulled latest images on both sides.
Console is working on host1

**Comment by harshavardhana** [comment]
> [http://host1/minio1/data{​​​​​1...4}​​​​​ \](http://host1/minio1/data%7B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B1...4%7D%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%C2%A0%5C) [http://host2/minio1/data{​​​​​1...4}​​​​​](http://host2/minio1/data%7B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B1...4%7D%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)

This is wrong setup @ahmedkunwar

**Comment by ahmedkunwar** [comment]
Can you please guide

**Comment by harshavardhana** [comment]
> @ahmedkunwar If you can't have a continuous ip range, use host names so you can do `https://minio-{1...3}:9000/test/drive{1...4}`.

@ahmedkunwar - you should setup like this.
