### ISSUE TITLE
Some these features are disabled as server is running in non-erasure coded mode.

### ISSUE THREAD

**Issue by jicki** [minio/minio#13173]
## Current Behavior

create bucket:  Some these features are disabled as server is running in non-erasure coded mode.

## Possible Solution

NO

## Steps to Reproduce (for bugs)

mc admin subnet health minio
                                              
● Admin Info ... ✔ 
● CPU Info ... ✔ 
● Disk Info ... ✔ 
● OS Info ... ✔ 
● Mem Info ... ✔ 
● Process Info ... ✔ 
● Server Config ... ✔ 
● Drive Test ... ✔ 
● Network Test ... ✔ 
*********************************************************************************
                                   WARNING!!
     ** THIS FILE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR ENVIRONMENT ** 
     ** PLEASE INSPECT CONTENTS BEFORE SHARING IT ON ANY PUBLIC FORUM **
*********************************************************************************

## Context

how to solve this problem ?

## Your Environment

* Version used (`minio --version`):    `minio version RELEASE.2021-05-27T22-06-31Z`
* Server setup and configuration: `http://minio-{1...4}/export{1...9}`
* Operating System and version (`uname -a`):  `Linux minio-1 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@jicki no idea what you are reporting here, please describe your issue properly.

**Comment by guleng** [comment]
@harshavardhana  I have the same problem.
![image](https://user-images.githubusercontent.com/40238640/140050762-5b55fcde-984b-425c-b26e-a3babce47b21.png)

**Comment by klauspost** [comment]
@guleng Use erasure coded mode: https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html
