### ISSUE TITLE
Configure SSL/TLS on docker container

### ISSUE THREAD

**Issue by chrizonline** [minio/minio#13170]
## Expected Behavior
I've a VM and it is running Ubuntu 18.04.5 LTS.

On Ubuntu, I've setup minio to run as docker container with SSL in the following way:
```
docker run -d -p 9000:9000 --name minio -v /home/chrizonline/Desktop/minio/config:/root/.minio -v /home/chrizonline/Desktop/minio/data:/data -e "MINIO_ROOT_USER=minio" -e "MINIO_ROOT_PASSWORD=minio123" minio/minio server /data
```

In `/home/chrizonline/Desktop/minio/config`:

```
|--/home/chrizonline/Desktop/minio/config
|   |--certs
|   |   |--private.key
|   |   |--public.crt
```

In the docker container, I've verified the private.key and public.crt are in `~/.minio/certs`:

```
$ docker exec -it <container_id> /bin/sh
sh-4.4# ls -la ~/.minio/certs
total 20
drwxrwxr-x 3 1000 1000 4096 Sep  8 13:33 .
drwxrwxr-x 3 1000 1000 4096 Sep  8 13:32 ..
drwx------ 2 root root 4096 Sep  8 13:33 CAs
-rw------- 1 1000 1000 1704 Sep  8 13:20 private.key
-rw-rw-r-- 1 1000 1000 1419 Sep  8 13:20 public.crt
sh-4.4# ls -la ~/.minio/certs/CAs
total 8
drwx------ 2 root root 4096 Sep  8 13:33 .
drwxrwxr-x 3 1000 1000 4096 Sep  8 13:33 ..
```

I generated the private.key and public.crt the following way:

```
openssl req -newkey rsa:2048 -nodes -keyout private.key -x509 -days 365 -out public.crt
```

When I run aws cli command to list s3, I'm expected to see the list of bucket. But I'm getting an error regarding verification failed for self signed certificate. 

```
$ aws s3 ls --endpoint-url https://192.168.1.10:9000

SSL validation failed for https://192.168.1.10:9000/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)
```

The aws cli configuration is as follows:

~/.aws/config

```
[default]
region = ap-southeast-1
```

~/.aws/credentials

```
[default]
aws_access_key_id = minio
aws_secret_access_key = minio123
```

Based on other issues reported, what I've done would have gotten SSL to work on docker. May I know where did I go wrong and how do I fix this?

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-09-03T03-56-13Z
* Operating System and version (`uname -a`): Linux itoadmin-virtual-machine 5.4.0-81-generic # 91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@chrizonline self signed certs need to be trusted by AWS CLI - which part do you think this is a MinIO problem?

**Comment by chrizonline** [comment]
Hi @hackintoshrao, thank you for pointing me the to right direction. I didn't know that. 

For others who may have encountered the same problem as me, you could verify by turning off ssl verification `--no-verify-ssl`. Of course this is not recommended for production case.

```
aws s3 ls --endpoint-url https://192.168.1.10:9000 --no-verify-ssl
```
