### ISSUE TITLE
ARM64 Docker Image

### ISSUE THREAD

**Issue by cooperlees** [minio/minio#13172]
**Is your feature request related to a problem? Please describe.**
Can we please add building / uploading of a ARM64n image of minio please.

**Describe the solution you'd like**
Anyways to do it. One solution is to use a GitHub WorkFlow like I have on other projects: https://github.com/psf/black/blob/main/.github/workflows/docker.yml
- Happy to contribute if you add the Docker secrets to this repository, but I don't want to break what ever automation you have today

**Describe alternatives you've considered**
I do have x86_64 boxes, but I develop a lot on my M1 Mac cause it's small and fast.

**Additional context**
N/A

**Comment by harshavardhana** [comment]
We already publish a mult-arch container @cooperlees just `docker pull minio/minio` on your ARM64

**Comment by harshavardhana** [comment]
If you are looking for Darwin arm64 then the binary is here https://dl.minio.io/server/minio/release/darwin-arm64/minio - there is no container image for Darwin specifically - since there is no container runtime on Mac.

**Comment by cooperlees** [comment]
Yes, I apologize, I looked at tags and only saw amd64, I thought. Must be time to get off the computer today (I even wasted time building the image myself!) - Sorry to waste your time.

**Comment by harshavardhana** [comment]
> Yes, I apologize, I looked at tags and only saw amd64, I thought. Must be time to get off the computer today (I even wasted time building the image myself!) - Sorry to waste your time.

https://hub.docker.com/layers/minio/minio/RELEASE.2021-09-03T03-56-13Z/images/sha256-52a8b5fc08291252d58a82948e1ed27b6457dabe07de953bc1b4a698d579b576?context=explore
