### ISSUE TITLE
Unsupported action 's3:ListObjects'

### ISSUE THREAD

**Issue by FrenchBen** [minio/minio#13188]
## Expected Behavior

I expect Minio to support a policy for listing objects as normal object storage do.
See: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

## Current Behavior

`Unsupported action 's3:ListObjects'`
`Unsupported action 's3:ListObjectsV2'`
Neither `ListObjects` or `ListObjectsV2` are supported. 
<img width="860" alt="Screen Shot 2021-09-10 at 10 22 12 AM" src="https://user-images.githubusercontent.com/3965324/132893086-657e68f9-0dfa-4039-a5fa-4874d0156720.png">

## Possible Solution

Without the explicit policy, you can still list objects? 🤔 

## Steps to Reproduce (for bugs)

1. Create new minio server
2. Create new user
3. Assign policy to user so they can read/list objects
4. Observe failure

## Context

Trying to limit what a user can see/read

## Regression

yes, as it's not compatible with AWS object store

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
docker

**Comment by harshavardhana** [comment]
Action is called `s3:ListBucket` @FrenchBen  there is no action called `s3:ListObjects` and `s3:ListObjectsV2` support. Both are `s3:ListBucket` which is basically List inside a bucket.

**Comment by harshavardhana** [comment]
> Action is called `s3:ListBucket` @FrenchBen there is no action called `s3:ListObjects` and `s3:ListObjectsV2` support. Both are `s3:ListBucket` which is basically List inside a bucket.

We may support the newer actions but for now just use s3:ListBucket

**Comment by FrenchBen** [comment]
@harshavardhana thanks for the comment - from AWS docs, the above is very much valid.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html

`ListBucket` - Returns a list of all buckets owned by the authenticated sender of the request.
`ListObject` - Returns some or all (up to 1,000) of the objects in a bucket with each request.

These are 2 different operations that typically warrant 2 different permissions.

**Comment by harshavardhana** [comment]
> @harshavardhana thanks for the comment - from AWS docs, the above is very much valid.
> https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html
> 
> `ListBucket` - Returns a list of all buckets owned by the authenticated sender of the request.
> `ListObject` - Returns some or all (up to 1,000) of the objects in a bucket with each request.
> 
> These are 2 different operations that typically warrant 2 different permissions. 

Correct we are not supporting those yet. No reason to have two ways to do same thing.

**Comment by kannappanr** [comment]
These actions certainly do not exist in AWS S3. Atleast I could not create them.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:ListObjects",
            "Resource": "*"
        }
    ]
}
```
I get the following error for the policy mentioned above

Ln 7, Col 22Invalid Action: The action s3:ListObjects does not exist. Did you mean s3:ListBucket? The API called ListObjects authorizes against the IAM action s3:ListBucket.

**Comment by FrenchBen** [comment]
Thanks for confirming the issue exists within AWS as well @kannappanr

**Comment by setop** [comment]
> > Action is called `s3:ListBucket` @FrenchBen there is no action called `s3:ListObjects` and `s3:ListObjectsV2` support. Both are `s3:ListBucket` which is basically List inside a bucket.
> 
> We may support the newer actions but for now just use s3:ListBucket

The [minio documentation](https://docs.min.io/minio/vsphere/tutorials/policy-management.html#configure-the-new-policy) basically tells to refer to the AWS documentation.

How to know what is actually implemented and what is not ?

**Comment by harshavardhana** [comment]
> How to know what is actually implemented and what is not ?

Read here https://docs.min.io/minio/baremetal/security/minio-identity-management/policy-based-access-control.html#minio-policy

**Comment by rmGFW** [comment]
> > Action is called `s3:ListBucket` @FrenchBen there is no action called `s3:ListObjects` and `s3:ListObjectsV2` support. Both are `s3:ListBucket` which is basically List inside a bucket.
> 
> We may support the newer actions but for now just use s3:ListBucket

does listBucket support prefix match , i already add this to the policy ,but the minio python client still get error of access denied.(use client.list_objects)
