### ISSUE TITLE
Docker: "/usr/bin/minio: No such file or directory"

### ISSUE THREAD

**Issue by caugner** [minio/minio#13181]
Our app's CI tests broke over night, because `/usr/bin/minio` has been moved to `/opt/bin/minio`.

## Expected Behavior
Minio should be runnable via `/usr/bin/minio`, or this breaking change should have been announced in the release notes.

## Current Behavior
`/usr/bin/minio` has vanished since 39d51ce84513a45061906bda087b2443bc712522, so running `/usr/bin/minio` causes a "No such file or directory" error, and Minio does not start.

## Possible Solution
1. Add a symlink from `/usr/bin/minio` to `/opt/bin/minio`.
2. Add a script at `/usr/bin/minio` that emits a warning and calls `/opt/bin/minio` with the same parameters.

## Steps to Reproduce (for bugs)
1. Run `docker run -it --rm --entrypoint /usr/bin/minio minio/minio`

### Before

```console
$ docker run -it --rm --entrypoint /usr/bin/minio minio/minio
NAME:
  minio - High Performance Object Storage

DESCRIPTION:
  Build high performance data infrastructure for machine learning, analytics and application data workloads with MinIO

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   start object storage server
  gateway  start object storage gateway

FLAGS:
  --certs-dir value, -S value  path to certs directory (default: "/root/.minio/certs")
  --quiet                      disable startup information
  --anonymous                  hide sensitive information from logging
  --json                       output server logs and startup information in json format
  --help, -h                   show help
  --version, -v                print the version

VERSION:
  RELEASE.2021-05-20T22-31-44Z
```

### Now

```console
$ docker run -it --rm --entrypoint /usr/bin/minio minio/minio
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/minio": stat /usr/bin/minio: no such file or directory: unknown.
```

## Context

We use a custom command for using Minio as a service in our GitLab CI/CD tests:

```
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/minio/minio
      alias: minio
      entrypoint: [""]
      command: ["sh", "-c", "mkdir -p /data/$MINIO_BUCKET && /usr/bin/minio server /data"]
```

## Regression

https://github.com/minio/minio/blob/39d51ce84513a45061906bda087b2443bc712522/Dockerfile.release#L34-L39

## Your Environment

* Version used (`minio --version`): `RELEASE.2021-09-09T21-37-07Z`
* Server setup and configuration: Ubuntu 20.04 LTS
* Operating System and version (`uname -a`): `Linux ***redacted*** 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
>     - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/minio/minio
>       alias: minio
>       entrypoint: [""]
>       command: ["sh", "-c", "mkdir -p /data/$MINIO_BUCKET && /usr/bin/minio server /data"]

This is an unexpected usage and a hack not sure why was this path hardcoded? - there are multiple cleaner alternatives here which will always work

>     - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/minio/minio
>       alias: minio
>       entrypoint: [""]
>       command: ["sh", "-c", "mkdir -p /data/$MINIO_BUCKET && minio server /data"]


even better

>     - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/minio/minio
>       alias: minio
>       entrypoint: [""]
>       command: ["sh", "-c", "mkdir -p /data/$MINIO_BUCKET && /usr/bin/docker-entrypoint.sh minio server /data"]

I don't think it makes sense to bring /usr/bin/minio back again - we have never documented such a requirement and there is no reason to add unexpected symlinks inside the container.

**Comment by caugner** [comment]
@harshavardhana By the way, you have suggested to use `/usr/bin/minio` in the entrypoint yourself: https://github.com/minio/minio/issues/4769#issuecomment-320319655

**Comment by klauspost** [comment]
@caugner Mentioning a workaround 4 years ago in passing does not make it official.
