### ISSUE TITLE
Multi-part put fails with fs.json: operation not permitted

### ISSUE THREAD

**Issue by solence** [minio/minio#13185]
We have two Minio instances with a common NFSv4 backend mounted to /data in their containers. Manual file uploads work as expected, multi-part uploads fail.

## Expected Behavior
Multi-part uploads are possible, using putObject of the Java SDK.

## Current Behavior
The uploads fails every time with the following exception:
/data/.minio.sys/multipart/b1d3a50987b70b72e197b045900e837811de9dee313043399732950c02a42738/f833b67f-7729-4021-8c23-4f13f3ef4b7e/fs.json: operation not permitted)

The log output is as follows:

API: PutObjectPart(bucket=88f848ce670d0959d7cb1721af00ad3cbb94498759ad2519f8d1b5292b0cc625, object=dc5dcc73f10f5b20b1182938d09627fd39876836c01f51cc319d39eb4e6404ea)
DeploymentID: 02b9e3ac-d418-40de-81c4-25287e6d242c
RequestID: 16A37EF551D77E6C
RemoteHost: dd5bede100d5dcb080d9ec65f3379775a685e6d3af239001c5825a5bd7dd9bec
Host: minio.\*\*censored\*\*
UserAgent: MinIO (Linux; amd64) minio-java/8.2.2
Error: *fs.PathError
       4: cmd/api-errors.go:2037:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2062:cmd.toAPIError()
       2: cmd/object-handlers.go:2626:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()

## Possible Solution
No idea :)

## Steps to Reproduce (for bugs)
Use Minio instances in containers, mount NFSv4 share via Docker volume, try to upload multi-part file.

## What I tried already
- I have already check file system permissions, but they are correct.
- Manual uploads in the UI work even with huge files.
- There is multiple TB of free space.
- sync mount option with NFSv4 mount makes no difference
- partSize set or -1 makes no difference
- objectSize set or -1 makes no difference
 

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-08-25T00-41-18Z
* Server setup and configuration: Docker host with 2 cores, 24 GB RAM, NFSv4 mount for each container
* Operating System and version (`uname -a`): Linux daa44889cb25 4.12.14-122.63-default #1 SMP Mon Mar 1 15:26:35 UTC 2021 (f196504) x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Make sure your backend supports fcntl locks, if your filesystem cannot support that MinIO single drive mode will not work.

This looks like your NFS backend issue make sure your mount support fnctl locks, if it cannot do that it won't work.

**Comment by harshavardhana** [comment]
> Make sure your backend supports fcntl locks, if your filesystem cannot support that MinIO single drive mode will not work.
> 
> This looks like your NFS backend issue make sure your mount support fnctl locks, if it cannot do that it won't work.

Looks like filesystem issue underneath closing.

**Comment by solence** [comment]
Thanks for the hint, that was very helpful! Sorry for the late response, I was desperately trying to enable locking in my NFSv4 setup, but eventually gave up and switched to CIFS. Now everything works as expected.

**Comment by harshavardhana** [comment]
> Thanks for the hint, that was very helpful! Sorry for the late response, I was desperately trying to enable locking in my NFSv4 setup, but eventually gave up and switched to CIFS. Now everything works as expected.

👍🏽

**Comment by larivierec** [comment]
I'm getting this error with a k8s in-cluster setup and a btrfs synology volume with NFS. 

I have tried sync, async and with the lock and no lock options. If I check the manual for nfs on synology it's supposed to support `fcntl` locks out of the box.

Is there anything else I can look at?

**Comment by JeanFrancoisMir** [comment]
Hello @harshavardhana, I do encounter the same issue here with my NAS

> Make sure your backend supports fcntl locks, if your filesystem cannot support that MinIO single drive mode will not work.
> This looks like your NFS backend issue make sure your mount support fnctl locks, if it cannot do that it won't work.

Could you elaborate on what this means ? How can I verify that my mount support fnctl locks ? I don't find much information online on what fnctl means and how I can "enable" it to be honnest. Thanks !

**Comment by harshavardhana** [comment]
> Hello @harshavardhana, I do encounter the same issue here with my NAS
> 
> > Make sure your backend supports fcntl locks, if your filesystem cannot support that MinIO single drive mode will not work.
> > This looks like your NFS backend issue make sure your mount support fnctl locks, if it cannot do that it won't work.
> 
> Could you elaborate on what this means ? How can I verify that my mount support fnctl locks ? I don't find much information online on what fnctl means and how I can "enable" it to be honnest. Thanks !

You would need to ask your NAS vendor it shows up in first Google search

https://docstore.mik.ua/orelly/networking_2ndEd/nfs/ch11_02.htm

**Comment by schwichti** [comment]
@harshavardhana 
> Make sure your backend supports fcntl locks, if your filesystem cannot support that MinIO single drive mode will not work.
> 
> This looks like your NFS backend issue make sure your mount support fnctl locks, if it cannot do that it won't work.

Is it possible to workaround file locks by using multi-drive mode?
