### ISSUE TITLE
close md5 calc in gateway mode 

### ISSUE THREAD

**Issue by TestMsr** [minio/minio#13191]
it costs high cpu usage ,but no use expect gateway nas

## Expected Behavior

close md5 calculate while in gateway mode

## Current Behavior

All test in single thread upload

PUT 10GB files to s3 storage
cost 3.81s

PUT 10GB files to minio gateway s3 storage
cost 48.84s (not exactly,beacause of my custom sha1 calc)

pprof:
flat cum name
24.70s 24.70s crypto/md5.block
17.05s 17.05s crypto/sha1.blockAVX2  

time sha1sum 10gb.file:~17.56s
time md5sum 10gb.file:~28.96s

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
 2021-04-18T19:26:29Z
* Server setup and configuration:
 minio gateway s3 http://127.0.0.1:12345
* Operating System and version (`uname -a`):
Linux 3.10.0-862.el7.x86_64  x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
md5 is an S3 spec requirement, which cannot be changed if you want S3 spec behavior.

If you wish to avoid S3 spec behavior then start MinIO with --no-compat

**Comment by TestMsr** [comment]
> md5 is an S3 spec requirement, which cannot be changed if you want S3 spec behavior.
> 
> If you wish to avoid S3 spec behavior then start MinIO with --no-compat

thanks for your reply.

i  forgot the enc and compress in gateway mode while using s3，so it's needed

but the no-compat options seems to be no usage in whole project afer #11577
