### ISSUE TITLE
Problem with Docker image tags

### ISSUE THREAD

**Issue by murphybytes** [minio/minio#13203]
I'm not sure if this is a bug, but I was working on a script to pull the latest image tag from minio/minio on Docker Hub and I noticed an inconsistency with the tags.  If you look at the latest push, at least the latest push at the time I wrote this you'll see that it is tagged "RELEASE.2020-10-28T08-16-50Z-51-g7fdffa036", the previous tag is "RELEASE.2021-09-09T21-37-07Z.fips" which is what I'd expect.  Compare the years in the two releases I've referenced and you'll see that the previous one has no association with the actual date that the image was pushed.  It would be good if you'd use a semver to tag but in lieu of that, if you refer to a date in the tag, please make it consistent with the date that the image was pushed.

**Comment by harshavardhana** [comment]
That is just weird way you are pulling in information. You need to look for GitHub tags first for latest and pull the right container image.

Latest on docker hub is not the latest tag, we use docker not as just a push target for various containers we build for our customers and backports.

So look for GitHub tags first and then pull the right container.

**Comment by mtiller** [comment]
@harshavardhana So I see the GitHub tags, but why are you using zulu time as your tag?!?  It just seems like such a poor choice.  I learn nothing from such release tags about potential backward incompatibilities, the stability of the release, etc.  What is the purpose here?  You might as well just use the commit hash since it says just as much about compatibility and stability (i.e., nothing).  I just don't understand this system at all.

**Comment by harshavardhana** [comment]
> @harshavardhana So I see the GitHub tags, but why are you using zulu time as your tag?!? It just seems like such a poor choice. I learn nothing from such release tags about potential backward incompatibilities, the stability of the release, etc. What is the purpose here? You might as well just use the commit hash since it says just as much about compatibility and stability (i.e., nothing). I just don't understand this system at all.

@mtiller all MinIO latest releases are compatible with all the data that it created since it was released.
