### ISSUE TITLE
Loss of a single disk leaves out the entire server.

### ISSUE THREAD

**Issue by gllenass** [minio/minio#13208]
Hello guys doing some availabilty tests, when I umount a server's disk, all minio's service in that node goes down, not only the disk.
We have 4 virtual machines (vmware) running RHEL 8, 32GB, 8 Vcpus and 4 disks 100 GB each. 
On a virtualbox lab, same scheme but virtual machines with less resources, running CentOS we got the same result.

Minio:  Version: 2021-09-09T21:37:07Z
Minio configured as a service on each vm, runnig in this way: 

[root@mn-apl01 ~]# systemctl status minio.service
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2021-09-13 16:56:13 EDT; 23h ago
     Docs: https://docs.min.io
 Main PID: 1922 (minio)
    Tasks: 20
   Memory: 263.3M
   CGroup: /system.slice/minio.service
           └─1922 /usr/local/bin/minio server http://mn-apl0{1...4}/disk{1...4} --console-address :9001

This are the steps:

[root@mn-apl01 minio-binaries]# mcli admin info minio1
●  mn-apl02:9000
   Uptime: 1 minute
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK

●  mn-apl03:9000
   Uptime: 4 hours
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK

●  mn-apl04:9000
   Uptime: 2 hours
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK

●  mn-apl01:9000
   Uptime: 2 hours
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK

1.3 GiB Used, 2 Buckets, 9 Objects
16 drives online, 0 drives offline

Now umount disk3 on mn-apl02 server:

	Sep 13 13:52:08 mn-apl02 systemd[8180]: disk3.mount: Succeeded.
	Sep 13 13:52:08 mn-apl02 kernel: XFS (dm-5): Unmounting Filesystem

Sep 13 13:52:14 mn-apl02 minio[9920]: Found unformatted drive http://mn-apl02:9000/disk3, attempting to heal...
Sep 13 13:52:15 mn-apl02 minio[9920]: Disk `/disk3` the same as the system root disk.
**Sep 13 13:52:15 mn-apl02 minio[9920]: Disk will not be used. Please supply a separate disk and restart the server.
Sep 13 13:52:15 mn-apl02 minio[9920]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 13 13:52:15 mn-apl02 minio[9920]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x28ce466]**
Sep 13 13:52:15 mn-apl02 minio[9920]: goroutine 341 [running]:
Sep 13 13:52:15 mn-apl02 minio[9920]: github.com/minio/minio/cmd.(*erasureSets).HealFormat(0xc001c4bc80, 0x45b2f38, 0xc014310f00, 0xc000568000, 0x0, 0x33d915c, 0x8, 0x0, 0x0, 0x0, ...)
Sep 13 13:52:15 mn-apl02 minio[9920]: #011github.com/minio/minio/cmd/erasure-sets.go:1295 +0xa86
Sep 13 13:52:15 mn-apl02 minio[9920]: github.com/minio/minio/cmd.(*erasureServerPools).HealFormat(0xc0025c05c0, 0x45b2f38, 0xc00048b7c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Sep 13 13:52:15 mn-apl02 minio[9920]: #011github.com/minio/minio/cmd/erasure-server-pool.go:1509 +0x332
Sep 13 13:52:15 mn-apl02 minio[9920]: github.com/minio/minio/cmd.healDiskFormat(0x45b2f38, 0xc00048b7c0, 0x45fcec0, 0xc0025c05c0, 0x10000, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
Sep 13 13:52:15 mn-apl02 minio[9920]: #011github.com/minio/minio/cmd/background-heal-ops.go:124 +0xb6
Sep 13 13:52:15 mn-apl02 minio[9920]: github.com/minio/minio/cmd.(*healRoutine).AddWorker(0xc000cff710, 0x45b2f38, 0xc00048b7c0, 0x45fcec0, 0xc0025c05c0)
Sep 13 13:52:15 mn-apl02 minio[9920]: #011github.com/minio/minio/cmd/background-heal-ops.go:93 +0x4ac
Sep 13 13:52:15 mn-apl02 minio[9920]: created by github.com/minio/minio/cmd.initBackgroundHealing
Sep 13 13:52:15 mn-apl02 minio[9920]: #011github.com/minio/minio/cmd/background-heal-ops.go:71 +0x98
Sep 13 13:52:15 mn-apl02 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 13 13:52:15 mn-apl02 systemd[1]: minio.service: Failed with result 'exit-code'.
Sep 13 13:52:15 mn-apl02 systemd[1]: minio.service: Service RestartSec=100ms expired, scheduling restart.
Sep 13 13:52:15 mn-apl02 systemd[1]: minio.service: Scheduled restart job, restart counter is at 30.
Sep 13 13:52:15 mn-apl02 systemd[1]: Stopped MinIO.
Sep 13 13:52:15 mn-apl02 systemd[1]: Started MinIO.

and then, mounting the disk again...

Sep 13 14:42:42 mn-apl02 kernel: XFS (dm-5): Mounting V5 Filesystem
Sep 13 14:42:42 mn-apl02 kernel: XFS (dm-5): Ending clean mount
Sep 13 14:43:06 mn-apl02 minio[13577]: Waiting for all MinIO sub-systems to be initialized.. lock acquired
Sep 13 14:43:06 mn-apl02 minio[13577]: Verifying if 2 buckets are consistent across drives...
Sep 13 14:43:06 mn-apl02 minio[13577]: Automatically configured API requests per node based on available memory on the system: 277
Sep 13 14:43:06 mn-apl02 minio[13577]: All MinIO sub-systems initialized successfully
Sep 13 14:43:06 mn-apl02 minio[13577]: Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Sep 13 14:43:06 mn-apl02 minio[13577]: Status:         16 Online, 0 Offline.

[root@mn-apl01 minio-binaries]# mcli admin info minio1
●  mn-apl02:9000
   Uptime: 2 minutes
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK●  mn-apl03:9000
   Uptime: 5 hours
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK●  mn-apl04:9000
   Uptime: 3 hours
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK●  mn-apl01:9000
   Uptime: 3 hours
   Version: 2021-09-09T21:37:07Z
   Network: 4/4 OK
   Drives: 4/4 OK1.3 GiB Used, 2 Buckets, 9 Objects
16 drives online, 0 drives offline

Thanks.

**Comment by harshavardhana** [comment]
> Sep 13 13:52:15 mn-apl02 minio[9920]: panic: runtime error: invalid memory address or nil pointer dereference

This shouldn't happen looks like a recent bug @gllenass

**Comment by harshavardhana** [comment]
> Sep 13 13:52:14 mn-apl02 minio[9920]: Found unformatted drive http://mn-apl02:9000/disk3, attempting to heal...
> Sep 13 13:52:15 mn-apl02 minio[9920]: Disk `/disk3` the same as the system root disk.
> **Sep 13 13:52:15 mn-apl02 minio[9920]: Disk will not be used. Please supply a separate disk and restart the server.**

This mainly happens because the mount is missing and now the mount is part of the root disk - that is rejected, but this should be simply ignored and moved on as it used to be before. 

All we have to do is skip this `rootDisk`

**Comment by gllenass** [comment]
Another strange behavior that I notice I do not know if it is normal or not, that when the service is down on a node if I login to web console  /Dasboard is blank. If I click on any other object: users, logs, trace, bucket I see content but not with Dashboard
Evidence: 

![imagen](https://user-images.githubusercontent.com/19175271/133334022-24f0cb73-5ccb-4dfc-93c6-621ff835118d.png)

stopping service on one node: 

[root@mn-apl02 ~]# systemctl stop minio.service
[root@mn-apl02 ~]# systemctl status minio.service
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2021-09-14 17:09:07 EDT; 4s ago

Login again: blank page

![imagen](https://user-images.githubusercontent.com/19175271/133334424-f37d0972-aac8-465f-bc66-5e61024cb1e1.png)

viewing source page:
![imagen](https://user-images.githubusercontent.com/19175271/133334771-5eaa3d62-3b45-426d-93db-9ce98dc53ff5.png)

click on other objects , is OK
![imagen](https://user-images.githubusercontent.com/19175271/133334833-c613fc4a-b1b2-4108-9ac4-5b1fea396a93.png)

**Comment by gllenass** [comment]
@harshavardhana

**Comment by harshavardhana** [comment]
> Another strange behavior that I notice I do not know if it is normal or not, that when the service is down on a node if I login to web console /Dasboard is blank. If I click on any other object: users, logs, trace, bucket I see content but not with Dashboard
> Evidence:

That is a separate bug in console UI @gllenass that is fixed as well.
