### ISSUE TITLE
Configurable base url for console

### ISSUE THREAD

**Issue by yoonsio** [minio/minio#13200]
Ingress can be configured to use same domain name for both api and console.
```
API: https://minio.example.com
Console: https://minio.example.com/console
```
However console fails to load static resources because it is expecting different base URL.
```
https://minio.example.com/styles/root-styles.css
instead of
https://minio.example.com/console/styles/root-styles.css
```

**Describe the solution you'd like**

Add environment variable `MINIO_BROWSER_URL` to configure base url for console.

**Describe alternatives you've considered**

Assign unique domain to api and console.

**Comment by harshavardhana** [comment]
You can set MINIO_BROWSER_REDIRECT_URL

**Comment by stevedef** [comment]
> MINIO_BROWSER_REDIRECT_URL

I believe this only redirects user to browser url. Static resources are still loaded from base domain.

**Comment by harshavardhana** [comment]
> I believe this only redirects user to browser url. Static resources are still loaded from base domain.

That is part of the console project to support different base domain @yoonst not MinIO servers problem. You may open an issue here  https://github.com/minio/console
