### ISSUE TITLE
Is there a way that I can start up minio without console or with old web UI?

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/minio#13212]
the old web UI can upload objects wtith mouse drag, it's much convinient than console web. However, when I start minio with latest version, I can not access old web UI, is there a way I can use old web UI?

**Comment by klauspost** [comment]
@HaoLiuHust No. The old UI is removed.

**Comment by HaoLiuHust** [comment]
do you have plan to support upload folder or drag files to brower? It is very useful for users just use brower

**Comment by klauspost** [comment]
@HaoLiuHust That would be a reasonable feature to add in my personal opinion, but I can't tell if it is on the current roadmap.

**Comment by harshavardhana** [comment]
> do you have plan to support upload folder or drag files to brower? It is very useful for users just use brower

You can open an issue at https://github.com/minio/console
