### ISSUE TITLE
When downloading multiple files through Web UI all zipped files are without file extension

### ISSUE THREAD

**Issue by kcindric** [minio/minio#13216]
When selecting multiple files to download all files are downloaded inside a .zip file but don't have file extensions although in the UI file types are visible.
![image](https://user-images.githubusercontent.com/44549361/133439187-69294b19-2114-4162-9580-fface189bf49.png)
File types visible inside the UI

![image](https://user-images.githubusercontent.com/44549361/133439300-012629b5-3db1-432b-8a73-afe62032bfe1.png)
Files without a file type extension in .zip file

## Expected Behavior
Each file should have a file extension based on its own file type (i.e. .pdf or .jpg).

## Current Behavior
Files get downloaded without a file extension

## Steps to Reproduce (for bugs)
1. Select multiple files
2. Download selected files

## Your Environment
VERSION
2020-12-29T23:29:29Z
PLATFORM
Host: 3992ecc53998 | OS: linux | Arch: amd64
RUNTIME
Version: go1.15.6 | CPUs: 8

**Comment by klauspost** [comment]
This functionality no longer exists.

Furthermore the object names are exactly as they are uploaded by design.
