### ISSUE TITLE
Error(disk not found)even mc admin info shows all disks are online

### ISSUE THREAD

**Issue by waem14** [minio/minio#13217]
## Expected Behavior

No disk errors when mc admin info biminio_prod shows all disks are online.

## Current Behavior

It always got errors even mc admin info biminio_prod show all disks are online.

Sep 15 21:28:38 sg-bimin-6z01 minio: Error: Error(disk not found) reading erasure shards at (http://sg-bimin-6z05.serv1.server.local:9000/data06/minio: eon/678/025f2d1caed940fa707c7fdfc03c4b81026000010c452741_0.gt/916c3013-d21b-4f28-aef2-3f21a15bed77/part.3), will attempt to reconstruct if we have quorum (*fmt.wrapError)
Sep 15 21:28:43 sg-bimin-6z01 minio: Error: Marking http://sg-bimin-6z05.serv1.server.local:9000/minio/lock/v6 temporary offline; caused by Post "http://sg-bimin-6z05.serv1.server.local:9000/minio/lock/v6/rlock?owner=sg-bimin-6z01.serv1.server.local%3A9000&quorum=4&source=%5Berasure-object.go%3A163%3AerasureObjects.GetObjectNInfo%28%29%5D&uid=5f249376-3ba4-4e8f-8da9-02a66c482c1f": read tcp 10.104.200.16:41908->10.104.200.20:9000: read: connection reset by peer (*fmt.wrapError)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

minio version RELEASE.2021-09-03T03-56-13Z
[root@sg-bimin-6z01 log]# uname -a
Linux sg-bimin-6z01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
> Sep 15 21:28:43 sg-bimin-6z01 minio: Error: Marking http://sg-bimin-6z05.serv1.server.local:9000/minio/lock/v6 temporary offline; caused by Post "http://sg-bimin-6z05.serv1.server.local:9000/minio/lock/v6/rlock?owner=sg-bimin-6z01.serv1.server.local%3A9000&quorum=4&source=%5Berasure-object.go%3A163%3AerasureObjects.GetObjectNInfo%28%29%5D&uid=5f249376-3ba4-4e8f-8da9-02a66c482c1f": read tcp 10.104.200.16:41908->10.104.200.20:9000: read: connection reset by peer (*fmt.wrapError)

This could be a temporary error. If you look at the logs you should find that http://sg-bimin-6z05.serv1.server.local:9000 is online again.

**Comment by harshavardhana** [comment]
These errors are temporary, this shows that your network is overloaded at some point here.

**Comment by waem14** [comment]
do you have recommended network configuration for minio linux production environment?

i have found only https://github.com/minio/minio/blob/master/docs/deployment/kernel-tuning/README.md.

**Comment by harshavardhana** [comment]
> do you have recommended network configuration for minio linux production environment?

No there are no such settings necessary, your network should already be ideal, to begin with. You cannot solve network shot comings with tuning. 

Optimizing deployments and architecture guidance is part of our subscription - if you have a production requirement we advice that you take up a subscription with us https://min.io/pricing

**Comment by ravindk89** [comment]
We do publish general guidelines [here](https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html#deployment-recommendations) and hardware recommendations for large-scale data infra [here](https://min.io/product/reference-hardware). But as Harsha noted, doing situation-specific tuning and optimization is something we provide through SUBNET, as it requires dedicated engineering resources to do properly.

**Comment by klauspost** [comment]
Not seeing any actionable issue here.

**Comment by zcerhub** [comment]
You can refer to that https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/. Connection Reset appears in my environment when accessing Minio in the Argo Workflow task. Conntrack's handling of TCP window outsourcing caused NAT failure. TCP would respond to RST to Minio.You can capture the packet that communicates with the Minio server from the client and confirm whether the client received a delayed packet from Minio before sending the rst packet to Minio. If so, you can determine the reason for the connection reset when accessing Minio. The solution is to follow the method in the blog.
