### ISSUE TITLE
Credential mandatory with TLS enabled

### ISSUE THREAD

**Issue by ealfatt** [minio/minio#13211]
Even if the TLS is enabled, credential are requested in order to invoke minio API (e.g. create bucket, upload object, object listing)
The error message we receive is "access denied"
Of course, if we set the credential in our client everything work fine.
 
## Expected Behavior

When the TLS in enabled we expect only to use only TLS certificate and no user and password are needed

## Current Behavior

User and password are request even if the TLS is enabled.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by vadmeste** [comment]
> Expected Behavior
> When the TLS in enabled we expect only to use only TLS certificate and no user and password are needed

MinIO follows S3 specification here. We cannot do anything here.
