### ISSUE TITLE
How to get minio working on a subdomain with nginx

### ISSUE THREAD

**Issue by msfjarvis** [minio/minio#1322]
I host my [website](http://msfjarvis.me) on a baremetal scaleway server and have it serving a download [index](http://msfjarvis.me/downloads) of my work. Now, I want to serve an instance of minio through it. but rather than host it on msfjarvis.me:9000/ I want it to use minio.msfjarvis.me/ over port 80 (or 443 when I get my SSL cert). I setup nginx to route 127.0.0.1:900 to minio.msfjarvis.me/ by making this file : 

```
server {
    listen 80;
    server_name http://minio.msfjarvis.me;
    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:9000;
    }
}
```

at /etc/nginx/sites-available/ghost (never mind the file name) and then symlinking it to /etc/nginx/sites-enabled/ghost .

My configuration is as follows : 

```
Ubuntu 14.04 x86_64
nginx 1.4.6
minio : latest build from minio.io/download
```

Any help/pointing out would be appreciated, even though I understand that most probably this is not minio at fault.

**Comment by krishnasrinivas** [comment]
@MSF-Jarvis your nginx config looks right, will check and get back. In the meanwhile can you add:

```
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
```

and check?

**Comment by msfjarvis** [comment]
Thanks, will try and report. You guys are quick, appreciate your dedication
to your offering.

**Comment by msfjarvis** [comment]
Not working. Reloaded nginx too

**Comment by harshavardhana** [comment]
@MSF-Jarvis  - can you try this config

```
server {
    listen 80;
    server_name minio.msfjarvis.me;

    location / {
        proxy_pass http://localhost:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by msfjarvis** [comment]
@harshavardhana no luck. Restarted nginx and minio as well

**Comment by harshavardhana** [comment]
> @harshavardhana no luck. Restarted nginx and minio as well

What is the error that you see?

**Comment by msfjarvis** [comment]
> What is the error that you see?

There's no specific error, just can't access it through the [link](http://minio.msfjarvis.me)

**Comment by harshavardhana** [comment]
> There's no specific error, just can't access it through the link

Do you have CNAME entry in your DNS? for this host?

**Comment by msfjarvis** [comment]
msfjarvis.me and www.msfjarvis.me have A records pointing to the server's public IP. I have a CNAME for blog.msfjarvis.me for GitHub Pages

**Comment by harshavardhana** [comment]
> msfjarvis.me and www.msfjarvis.me have A records pointing to the server's public IP. I have a CNAME for blog.msfjarvis.me for GitHub Pages

You have to add a CNAME pointing to minio.msfjarvis.me, DNS resolution is failing.

**Comment by msfjarvis** [comment]
@harshavardhana CNAME doesn't take an URI in my provider : 

> INVALID_ADDR : 'msfjarvis.me:9000' should not be an IP/ URL for CNAME record.(host name: minio)

**Comment by msfjarvis** [comment]
Thanks to everyone who helped! Solved on gitter

**Comment by MFrancesco** [comment]
@MSF-Jarvis what about sharing the solution ?
Having same issure here

**Comment by msfjarvis** [comment]
I don't remember exactly, sorry about that @MFrancesco, I simply use @mholt's caddy webserver now. Relevant documentation here : https://github.com/caddyserver/examples/tree/master/minio

Thanks to @koolhead17 for the write up, tho I figured it out myself ;)

**Comment by MFrancesco** [comment]
Don't worry @MSF-Jarvis , i figured out by myself :)
I'm succesfully accessing minio through my 3d level domain without problems now. 
nginx server block

```
server {
    listen 80;
    server_name subdomain.domain.com;

    location / {
       proxy_pass http://localhost:MINIOPORT;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

starting minio as

`./minio server --address=localhost:MINIOPORT /miniofolder`

Tested and running on a scaleway instance too

**Comment by Sincan2** [comment]
I try build nginx version: nginx/1.10.1 (Ubuntu)

`apt-get install nginx`

```
server {
        listen          80;

        server_name     domain;

    location / {
       proxy_pass http://localhost:6969;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

starting minio

`./minio server --address=localhost:6969 /miniofolder`

root@S3:~# curl -IL http://domain/sincan2/dansa.jpg
HTTP/1.1 200 OK
Server: nginx/1.10.1 (Ubuntu)
Date: Sun, 23 Oct 2016 04:24:02 GMT
Content-Type: image/jpeg
Content-Length: 41598
Connection: keep-alive
Accept-Ranges: bytes
Last-Modified: Fri, 21 Oct 2016 13:11:56 GMT
Vary: Origin
X-Amz-Request-Id: W09YS9YYT3EUE1K2

root@S3:~#

all done this ok
