### ISSUE TITLE
Applying lifecycle management only to the content inside a prefix

### ISSUE THREAD

**Issue by warunapww** [minio/minio#13237]
I want to apply a lifecycle management rule only to the content inside a _'persistent prefix'_ (made up word)
Note that  the _'persistent prefix'_ : `testprefix` is created by the following command

`mc mb minio/testbucket/testprefix`

Also note that 'persistent prefix' get listed with or without files inside the prefix

```
mc ls minio/testbucket -r
[2021-09-17 18:21:45 UTC]    12B file1
[2021-09-17 18:03:52 UTC]     0B testprefix/
```

I have also enabled the versioning for the `testbucket`
```
mc ls minio/testbucket -r --versions
[2021-09-17 18:21:45 UTC]    12B c889bb0d-94f2-45f3-bd74-258d4cb0ee6f v2 PUT file1
[2021-09-17 18:21:34 UTC]    12B 18cb99f9-f0a4-4062-be13-9bef5adf6f59 v1 PUT file1
[2021-09-17 18:03:52 UTC]     0B null v1 PUT testprefix/
```

The requirement is to apply a lifecycle management rule for the content inside the `minio/testbucket/testprefix`. So that the rule won't apply to the _'persistent prefix'_ , so that the `testprefix` will not be deleted.

I tried the following rules
```
1. mc ilm add minio/testbucket/testprefix --expiry-days 1
2. mc ilm add minio/testbucket/testprefix/ --expiry-days 1
3. mc ilm add minio/testbucket/testprefix/* --expiry-days 1
```

The rules 1 and 2 deleted the 'persistent prefix'.
The 3rd rule does not get applied to the files inside the 'persistent prefix'.

Is there away to achieve my requirement?
Let me know if you need more information

## Your Environment

* mc --version
`mc version RELEASE.2021-07-27T06-46-19Z`

* MinIO servers version
`2021-07-30T00:02:00Z`
 
* Server setup and configuration:
Cluster of 4 MinIO nodes

* Operating System and version (`uname -a`):
`Linux user 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vadmeste** [comment]
I am not able to reproduce this. Could you start from scratch again and provide all steps to reproduce this ?

**Comment by klauspost** [comment]
@warunapww Note that prefixes does not need to be created. They are created as a side effect of using it on objects.

You are creating an object called `testprefix/`. To "create" it you simply upload an object that uses it.

**Comment by harshavardhana** [comment]
@klauspost @vadmeste what is user expecting here is to use `prefix/` as bucket equivalent top level folder to be preserved. 

@warunapww it will be preserved if the prefix itself doesn't match the expiry since the prefix here is also an object the way you are creating it. If you wish to persist top level folder you need to apply the expiration policies for a sub-folder under prefix/

The another rules based would be to use tags on  objects where you can make sure to delete only objects with specific tags but leave out the top level folder. Then only objects matching the tags shall be deleted.

Other than these two there are no other provisions to preserve top level folder.

**Comment by warunapww** [comment]
Thanks for the responses.

Actually command 2. works as expected
`2. mc ilm add minio/testbucket/testprefix/ --expiry-days 1`

The 'persistent prefix' did not get deleted by the lifecycle management rule. The rule is applied only to the content inside `minio/testbucket/testprefix/ `

**Comment by harshavardhana** [comment]
> The 'persistent prefix' did not get deleted by the lifecycle management rule. The rule is applied only to the content inside `minio/testbucket/testprefix/ `

Okay great!
