### ISSUE TITLE
XmlParserException in java-client library when try to getObject\putObject

### ISSUE THREAD

**Issue by KotskinKotskin** [minio/minio#13230]
Hi. I use minio lib v 8.2.0 and docker image of minio v.RELEASE.2021-09-15T04-54-25Z, new setup. When i try to putObject or getObject i get XmlParserException, when method getRegion called from io.minio.MinioClient.getObject. I didnt configure location on my server and my minioClient (i try, but this didnt help). Bucket and file created.

## Expected Behavior
1. When i use MinioClient.getObject i get the object

## Current Behavior
1.  When i use MinioClient.getObject i get the XmlParserException

## Possible Solution
More information about LocationConstraint and region settings.

## Steps to Reproduce (for bugs)

1. Setup docker image 
docker run   -d   --name minio -e MINIO_ACCESS_KEY=XXXX-e MINIO_SECRET_KEY=XXX -v /mnt/data:/data -p 8888:9000   minio/minio:latest   --   server /data --console-address :8888
2. Create bucket "upload" via web interface
3. Add 8.2.0. lib to project
4. Initiate minioClient via spring bean
5. 
```
    @Lazy
    @Bean
    fun minio(): MinioClient {
        try {
            return MinioClient.builder()
                    .endpoint(minioClientProperties.endpoint)
                    .credentials(minioClientProperties.accessKey,  minioClientProperties.secretKey)
                    .build()
        } catch (e: Exception) {
            logger.error(e) { "cant connect to minio" }
            throw e
        }
    }
```

5. try to put object with this bean:
```
   try {
            minioClient.putObject(
                    PutObjectArgs.builder().bucket(minioClientProperties.defaultBucket).`object`(objectName).stream(
                            inputStream, fileSize, -1)
                            .build())
        } catch (e: Exception) {
            throw TechnicalException(
                message = "Failed to put object to the minio",
                cause = e
            )
        }
```

## Context
i try to put and get object from Kotlin(spring) application.

## Your Environment
minio java lib v 8.2.0
docker image v.RELEASE.2021-09-15T04-54-25Z

**Comment by harshavardhana** [comment]
> Hi. I use minio lib v 8.2.0 and docker image of minio v.RELEASE.2021-09-15T04-54-25Z, new setup. When i try to putObject or getObject i get XmlParserException, when method getRegion called from io.minio.MinioClient.getObject. I didnt configure location on my server and my minioClient (i try, but this didnt help). Bucket and file created.
> 
> ## Expected Behavior
> 1. When i use MinioClient.getObject i get the object
> 
> ## Current Behavior
> 1. When i use MinioClient.getObject i get the XmlParserException
> 
> ## Possible Solution
> More information about LocationConstraint and region settings.
> 
> ## Steps to Reproduce (for bugs)
> 1. Setup docker image
>    docker run   -d   --name minio -e MINIO_ACCESS_KEY=XXXX-e MINIO_SECRET_KEY=XXX -v /mnt/data:/data -p 8888:9000   minio/minio:latest   --   server /data --console-address :8888
> 2. Create bucket "upload" via web interface
> 3. Add 8.2.0. lib to project
> 4. Initiate minioClient via spring bean
> 
> ```
>     @Lazy
>     @Bean
>     fun minio(): MinioClient {
>         try {
>             return MinioClient.builder()
>                     .endpoint(minioClientProperties.endpoint)
>                     .credentials(minioClientProperties.accessKey,  minioClientProperties.secretKey)
>                     .build()
>         } catch (e: Exception) {
>             logger.error(e) { "cant connect to minio" }
>             throw e
>         }
>     }
> ```
> 
> 1. try to put object with this bean:
> 
> ```
>    try {
>             minioClient.putObject(
>                     PutObjectArgs.builder().bucket(minioClientProperties.defaultBucket).`object`(objectName).stream(
>                             inputStream, fileSize, -1)
>                             .build())
>         } catch (e: Exception) {
>             throw TechnicalException(
>                 message = "Failed to put object to the minio",
>                 cause = e
>             )
>         }
> ```
> 
> ## Context
> i try to put and get object from Kotlin(spring) application.
> 
> ## Your Environment
> minio java lib v 8.2.0
> docker image v.RELEASE.2021-09-15T04-54-25Z

Are you trying to upload to console port ? You need to upload to MinIO API endpoint not console port.

**Comment by KotskinKotskin** [comment]
@harshavardhana thanks for answer, your right. i forget to expose api endpoint and try do stuff via console port :(. Closed
