### ISSUE TITLE
Helm chart monitoring 

### ISSUE THREAD

**Issue by dyvol777** [minio/minio#13236]
if you enable `metrics.serviceMonitor.enabled: true` in values:
1. In prometheus you would see 3x targets, because 3 services created. 
2. Also, in ServiceMonitor exist bearerTokenSecret. To use this ServiceMonitor, you need manual actions(generate token and create secret). 

## Possible Solution
1. PodMonitor instead of ServiceMonitor.
2. Use env `MINIO_PROMETHEUS_AUTH_TYPE: public` by default and don't use bearerTokenSecret

**Comment by harshavardhana** [comment]
feel free to send a fix @dyvol777
