### ISSUE TITLE
Ability to view service account policy

### ISSUE THREAD

**Issue by djmattyg007** [minio/minio#13245]
**Is your feature request related to a problem? Please describe.**

Right now I have no way of checking what the policy for a service account user is.

**Describe the solution you'd like**

There should be a way to view the policy, both through `mc` and through the web UI.

**Describe alternatives you've considered**

I've considered digging through MinIO's configuration on disk, but I have no idea if these policies are even stored in plain text. This feels like a very tedious idea compared to just having an easy way to view the policy.

**Additional context**

It would also be nice to be able to update the policy after the user has been created. Right now I have to store a copy of the policy outside of MinIO, so that if I ever need to "update" the policy I still have a copy of it. I put "update" in quotes because I still have to create a new service account, switch over the credentials for anything using this policy, and then delete the old service account.

**Comment by vadmeste** [comment]
@djmattyg007, we have `mc admin user svcacct info <alias> <service-account-access-key --json` which shows the policy document for that service account.

**Comment by djmattyg007** [comment]
@vadmeste Thanks for confirming that. I find the `svcacct` subcommands to be quite unintuitive compared to the rest of `mc`.

**Comment by harshavardhana** [comment]
> @vadmeste Thanks for confirming that. I find the `svcacct` subcommands to be quite unintuitive compared to the rest of `mc`.

Please open a GitHub issue describing them at minio/mc project.
