### ISSUE TITLE
Minio stopped reading from network socket

### ISSUE THREAD

**Issue by wyssp8** [minio/minio#13251]
Hi there
 
We are receiving Elastic ECE snapshots with minio. There are more than 120TB that should be ingested into a S3 bucket but the connection gets stuck at 35-65% of processed data on every try. Usually after 3-5 days of uploading.
The TCP connection is in established state and we see TCP keep-alives every few seconds coming using tcpdump.
But our Recv-Q as shown below rises and stays still the same.
```
# netstat -apn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp   3913938      0 10.***.***.35:9001      10.***.***.31:35032     ESTABLISHED 31101/minio
...
```
 
After resolving the connection to the socket name and getting the file descriptor of it:
```
# lsof -p 31101 | grep 35032
minio   31101 minio   52u     IPv4          475841405      0t0          TCP ***00014.***.ch:etlservicemgr->***00010.***.ch:35032 (ESTABLISHED)
 
# ls -la /proc/31101/fd | grep 475841405
lrwx------ 1 minio minio 64 Sep 17 12:23 52 -> socket:[475841405]
```
 
We could confirm with `strace -f -p 31101`  that there are no `read` or similar calls on FD 52 (the network socket).
 
Also the prometheus metrics show 49 inflight requests for the node on api="putobjectpart", no other calls are stuck:
```
...
minio_s3_requests_inflight_total{api="putobject",server="***00014.***.ch:9001"} 0
minio_s3_requests_inflight_total{api="putobjectpart",server="***00013.***.ch:9001"} 3
minio_s3_requests_inflight_total{api="putobjectpart",server="***00014.***.ch:9001"} 49
...
```
 
Is there a way to debug this issue? We could do a SIGABRT on the minio process if we really have to, if there is no other option to get the goroutine dump without terminating the process.
Or just so see what and where the inflight requests are.
 
Regards,
Patrick

**Comment by harshavardhana** [comment]
@wyssp8 are you using single drive mode?

**Comment by wyssp8** [comment]
Hello @harshavardhana, we are using 2 drives.

Here the output from mc admin info:

```
***00014:~ # mc admin info minio
●  ***00013.***.ch:9001
   Uptime: 1 week
   Version: 2021-06-17T00:10:46Z
   Network: 3/3 OK
   Drives: 2/2 OK

●  ***00015.***.ch:9001
   Uptime: 1 week
   Version: 2021-06-17T00:10:46Z
   Network: 3/3 OK
   Drives: 2/2 OK

●  ***00014.***.ch:9001
   Uptime: 1 week
   Version: 2021-06-17T00:10:46Z
   Network: 3/3 OK
   Drives: 2/2 OK
```
Regards,
Patrick

**Comment by harshavardhana** [comment]
@wyssp8 have you tried upgrading and testing?

**Comment by klauspost** [comment]
> if there is no other option to get the goroutine dump without terminating the process.

`mc admin profile start --type=goroutines myminio&&sleep 10&&mc admin profile stop myminio` will return a zip file with goroutines.

Usually this behavior is packet loss that results in stuck TCP connections.

**Comment by wyssp8** [comment]
I did an upgrade to version 2021-09-18T18:09:59Z

Now i will test again the scenario and come back after i got the new results.

**Comment by wyssp8** [comment]
After the upgrade to version 2021-09-18T18:09:59Z, this behavior didn't happend again for some small test snapshots.

Now i started a big one and i will tell if the issue is still here. This will take some days.

**Comment by harshavardhana** [comment]
Thanks @wyssp8

**Comment by harshavardhana** [comment]
@wyssp8 please let us know how things went, we can close this issue if there is nothing to report.

**Comment by wyssp8** [comment]
@harshavardhana the upgrade fixed my issue.

Regards,
Patrick
