### ISSUE TITLE
FS mode: Starting `minio server /data` with existing folders fails on RELEASE.2021-09-18T18-09-59Z

### ISSUE THREAD

**Issue by davidwessman** [minio/minio#13252]
Our setup runs `minio server /data` and we create a folder inside the directory for our default bucket:

`/data/bucket-name`

and it has been working for a long time. Now it raises errors when Minio is started.

## Expected Behavior

1.`minio server /data`
2. Folders in `/data` should be turned into working buckets.

## Current Behavior

1. minio/server starts
2. Error messages when started for folders that have not been created via API.
```
API: SYSTEM()
Time: 14:16:58 CEST 09/20/2021
DeploymentID: e8fe0578-4bf8-491f-a686-d5ea69580755
Error: volume not found (cmd.StorageErr)
       1: cmd/bucket-targets.go:329:cmd.(*BucketTargetSys).load()

API: SYSTEM(bucket=bucket-name)
Time: 14:16:58 CEST 09/20/2021
DeploymentID: e8fe0578-4bf8-491f-a686-d5ea69580755
Error: volume not found (cmd.StorageErr)
       1: cmd/notification.go:642:cmd.(*NotificationSys).load()

API: SYSTEM()
Time: 14:16:58 CEST 09/20/2021
DeploymentID: e8fe0578-4bf8-491f-a686-d5ea69580755
Error: volume not found (cmd.StorageErr)
       2: cmd/bucket-metadata-sys.go:483:cmd.(*BucketMetadataSys).concurrentLoad()
       1: cmd/bucket-metadata-sys.go:493:cmd.(*BucketMetadataSys).load()
API: http://192.168.1.233:9000  http://127.0.0.1:9000 
```
3. API requests for the bucket generates 404.

## Steps to Reproduce (for bugs)

1. Create new empty folder for `data`, create a folder inside for a default bucket.
2. Start `minio server /data`
3. Try to access bucket via API

### Via docker

```sh
tag="RELEASE.2021-09-18T18-09-59Z"

docker pull minio/minio:$tag &&
docker run --rm \
           -e MINIO_ROOT_USER=$MINIO_ROOT_USER \
           -e MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD \
           -e MINIO_REGION_NAME=$MINIO_REGION_NAME \
           -v `pwd`/tmp/minio:/data \
           -p 9000:9000 \
           -p 9001:9001 \
           minio/minio:$tag server /data --console-address ":9001"
           
# No errors in log
mkdir tmp/minio/bucket-name

docker run --rm \
           -e MINIO_ROOT_USER=$MINIO_ROOT_USER \
           -e MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD \
           -e MINIO_REGION_NAME=$MINIO_REGION_NAME \
           -v `pwd`/tmp/minio:/data \
           -p 9000:9000 \
           -p 9001:9001 \
           minio/minio:$tag server /data --console-address ":9001"
# errors in log and bucket returns 404.
```

if I switch to RELEASE.2021-09-15T04-54-25Z it works.

## Context

Running Minio locally for development and testing.

## Regression

Yes, works on RELEASE.2021-09-15T04-54-25Z

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-09-18T18-09-59Z
* Server setup and configuration: Just username, password, region and endpoint. 
* Operating System and version (`uname -a`): Darwin MBP 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

**Comment by klauspost** [comment]
@vadmeste This should only be for erasure coded backends.

**Comment by pbeza** [comment]
I can confirm the problem. Any workaround?

**Comment by davidwessman** [comment]
> I can confirm the problem. Any workaround?

Use RELEASE.2021-09-15T04-54-25Z or create the buckets via the API instead of just an existing folder is the only way I found.

**Comment by harshavardhana** [comment]
Creating folders on backend directly was never supported, however you can start with existing folders it was a feature supported only in FS mode.

Ideally that was only meant for NAS gateway mode. But this is a behavior change that was added in #13232 

@vadmeste we should fix this to keep older behavior for FS mode.

**Comment by harshavardhana** [comment]
> 3\. Try to access bucket via API

which API are you talking about here @davidwessman ?

**Comment by davidwessman** [comment]
> > 3\. Try to access bucket via API
> 
> 
> 
> which API are you talking about here @davidwessman ? 

I am using ruby aws-sdk-s3 and tried to upload a file.

**Comment by davidwessman** [comment]
Thank you for quick fix! 🙂
