### ISSUE TITLE
RequestTimeTooSkewed when running multithread/process load test on minio on same network and the same NTP client config.

### ISSUE THREAD

**Issue by geraldo-netto** [minio/minio#13253]
Dear Friends,

I would like to ask your help for a situation we are facing with minio server
Basically we have a scenario using curl to insert binary data on minio server
The data size varies between 32 mb and 1gb and we are stress testing minio with 1, 2, 4 and 8 parallel processes
(we also have a multithread version written for junit using minio java sdk)
The server has 24 cpus, 96 gb of ram and tbs of disk (nvme) running centos 7 and the latest minio version running on docker (only 32gb of memory is pinned to minio)
The client has 16 cpus, 64 gb of ram and 4 tb of disk (nvme) running linux mint bare metal and curl 7.68
we use 2 scripts, one to fork the other which effectively calls curl with all the parameters (script attached)

## Expected Behavior

If minio is unable to responde in a timely fashion, minio should return a [RequestTimeoutException](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/glacier/model/RequestTimeoutException.html)

## Current Behavior

Tests were running fine, but when using files of 512 mb or bigger (random binary data) with 8 parallel curl processes
We start to receive this exception:

```xml
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the server&#39;s time is too large.</Message><Resource>/temp/32mb.bin</Resource><RequestId></RequestId><HostId>76d9f20d-016c-4ea4-bfcc-ef1f28bb2101</HostId></Error>
````

But the server and the client are on the same network and have the same NTP server (on upper right the time between server and client can be checked):

![Screenshot 2021-09-20 180500](https://user-images.githubusercontent.com/20527108/134041336-bc2f2dcb-3042-409f-b30d-4baf7a241e85.png)
[s3-perf.txt](https://github.com/minio/minio/files/7197386/s3-perf.txt)

**Comment by harshavardhana** [comment]
> ```
> ```
> <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the server&#39;s time is too large.</Message><Resource>/temp/32mb.bin</Resource><RequestId></RequestId><HostId>76d9f20d-016c-4ea4-bfcc-ef1f28bb2101</HostId></Error>
> ```

This is clearly the sign of network time that has been skewed @geraldo-netto there is nothing surprising here other than your NTP setup is broken.

**Comment by geraldo-netto** [comment]
Hi @harshavardhana ,

But then, I don`t understand why with 1 or 2 or 4 curl instances done 100 times in parallel, it works and then only when I run with 8 curl instances in parallel, after a while it starts to fail
Also, the NTP config. are equal and checking the time (screenshot attached in previous message), there is less than 1 second of difference

**Comment by klauspost** [comment]
@geraldo-netto You are generating the signature of the start of your script. So it it takes too long to execute the delay is too long. Calculate the signature for every request.

Signature time is checked when the request arrives, so it is a clientside problem.
