### ISSUE TITLE
"Broken pipe" on upload with RELEASE.2021-09-18T18-09-59Z 

### ISSUE THREAD

**Issue by andrej-urvantsev** [minio/minio#13267]
After upgrading to `RELEASE.2021-09-18T18-09-59Z` upload functionality stopped working(download works fine though).

Downgrading to `RELEASE.2021-09-15T04-54-25Z` solves the issue.

On the client side:
```
Caused by: java.net.SocketException: Broken pipe
	at sun.nio.ch.NioSocketImpl.implWrite(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.write(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl$2.write(Unknown Source) ~[?:?]
	at java.net.Socket$SocketOutputStream.write(Unknown Source) ~[?:?]
	at okio.OutputStreamSink.write(JvmOkio.kt:53) ~[okio-jvm-2.7.0.jar:?]
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103) ~[okio-jvm-2.7.0.jar:?]
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235) ~[okio-jvm-2.7.0.jar:?]
	at okio.RealBufferedSink.write(RealBufferedSink.kt:145) ~[okio-jvm-2.7.0.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271) ~[okhttp-4.8.1.jar:?]
	at okio.ForwardingSink.write(ForwardingSink.kt:29) ~[okio-jvm-2.7.0.jar:?]
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218) ~[okhttp-4.8.1.jar:?]
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235) ~[okio-jvm-2.7.0.jar:?]
	at okio.RealBufferedSink.write(RealBufferedSink.kt:193) ~[okio-jvm-2.7.0.jar:?]
	at io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:57) ~[minio-8.3.0.jar:8.3.0]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.8.1.jar:?]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.8.1.jar:?]
	at io.minio.S3Base.execute(S3Base.java:532) ~[minio-8.3.0.jar:8.3.0]
	at io.minio.S3Base.putObject(S3Base.java:1919) ~[minio-8.3.0.jar:8.3.0]
	at io.minio.S3Base.putObject(S3Base.java:1150) ~[minio-8.3.0.jar:8.3.0]
```

**Comment by andrej-urvantsev** [comment]
Not sure if it's related to #13251 or not.

**Comment by klauspost** [comment]
Interesting. This narrows the bisect quite a bit. I don't see anything in the change log that could be directly linked to this.

@lazystone What is your server setup?

**Comment by andrej-urvantsev** [comment]
Distributed setup: 4 nodes x 1 drive.

**Comment by klauspost** [comment]
Most likely cause is Go 1.16.8 -> 1.17.1 upgrade.

**Comment by klauspost** [comment]
@lazystone TLS, no TLS? Nothing in the server logs?

**Comment by andrej-urvantsev** [comment]
No TLS.

I think that's the relevant logs(sorry for screenshot - can't copy from Grafana):
![image](https://user-images.githubusercontent.com/2885029/134326483-937f3634-4165-4faa-b7ca-d8ddb92409a1.png)

**Comment by klauspost** [comment]
@lazystone Yeah, these are internal calls and not the incoming requests, but looks to be the same issue (server dropping the connection).

Let me try to see if I can build a binary with the old Go version. Then we can prove/disprove the theory.

**Comment by klauspost** [comment]
I put a Go 1.16.8 build up on https://download.klauspost.com/minio.DEVELOPMENT.2021-09-18T18-09-59Z-GO116.gz

If it is possible for you to test that, that would help a lot in possibly identifying the issue.

**Comment by andrej-urvantsev** [comment]
That's complicated, unless there is a docker image - I'm running MinIO as a StatefulSet in k8s

**Comment by harshavardhana** [comment]
> Not sure if it's related to #13251 or not.

It seems not @lazystone

**Comment by harshavardhana** [comment]
> No TLS.
> 
> I think that's the relevant logs(sorry for screenshot - can't copy from Grafana):
> ![image](https://user-images.githubusercontent.com/2885029/134326483-937f3634-4165-4faa-b7ca-d8ddb92409a1.png)

These logs are unrelated and it's not called by Prometheus - there is someone who is calling `mc admin subnet health` on this cluster

**Comment by harshavardhana** [comment]
> Not sure if it's related to #13251 or not.

Unrelated @lazystone

**Comment by andrej-urvantsev** [comment]
`RELEASE.2021-09-23T04-46-24Z` works fine, so the only one release which doesn't work for upload for us it's `RELEASE.2021-09-18T18-09-59Z`.

**Comment by harshavardhana** [comment]
> `RELEASE.2021-09-23T04-46-24Z` works fine, so the only one release which doesn't work for upload for us it's `RELEASE.2021-09-18T18-09-59Z`.

okay, that is strange there is nothing that has changed though which would cause such a change. If this is fixed we should just close the issue and move on for now.

**Comment by northway** [comment]
After upgrading from `2021-09-03T03:56:13Z` to `2021-09-24T00-24-24Z` I'm having a `Broken pipe` issue with Nginx.

* Yes, I have TLS configured.

```
2021/09/27 15:20:40 [error] 4558#4558: *234 SSL_write() failed (32: Broken pipe) while sending request to upstream, client: 193.224.0.67, server: s3.domain.com, request: "PUT /test1/file1.xml HTTP/1.1", upstream: "https://127.0.0.1:9000/test1/file1.xml", host: "s3.domain.com"
2021/09/27 15:20:40 [error] 4558#4558: *234 upstream prematurely closed connection while reading response header from upstream, client: 193.224.0.67, server: s3.domain.com, request: "PUT /test1/file1.xml HTTP/1.1", upstream: "https://127.0.0.1:9000/test1/file1.xml", host: "s3.domain.com"
```

Nginx proxy config:

```
    # To allow special characters in headers
    ignore_invalid_headers off;

    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;

    # To disable buffering
    proxy_buffering off;

    location / {
        proxy_set_header X-Real-IP $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        proxy_connect_timeout 300;
        # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;

        proxy_pass https://localhost:9000; # If you are using docker-compose this would be the hostname i.e. minio
        # Health Check endpoint might go here. See https://www.nginx.com/resources/wiki/modules/healthcheck/
        # /minio/health/live;
    }
 ```

**Comment by northway** [comment]
After I rolled back to version `2021-09-03T03:56:13Z`, everything works as expected.

**Comment by ryanlelek** [comment]
Hi, not intending to hijack.
I encountered a similar issue with "latest" [2021-09-24 Release](https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-09-24T00-24-24Z)

Rolling back to [2021-09-03 Release](https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-09-03T03-56-13Z) as @northway suggested fixed my issue as well.
More detail below.

- New Cluster (no data)
- 2 Machines, 2 disks each for testing/eval.
- No Nginx, Load Balancer, K8s.
- Yes, using TLS
- Had success with standalone, wanted to take the "next step" while limiting new additions. So cluster was next.

Issue - Any upload would respond with "broken pipe" or similar connections. Small files ~100MiB would give this error around chunk 5MiB. So I decided to try even smaller. first 4MiB and then 1KiB. All failed with similar error.

So I disabled firewall rules, uninstalled Debian apparmor, just to see. Still the issue persisted.
Switching clients (GUI, minio-client on macOS, minio-client on Linux), didn't seem to change much
Got to searching and found this (thank you!)

To reproduce, this happened to be on Debian 11 with 2, 10GB disks in a cloud provider. Total 4 disks.
Here's the systemd unit file.
Other than that, it's a clean install.
```
[Unit]
Description=Minio Cloud File Server
After=syslog.target

[Service]
Environment=MINIO_ROOT_USER=ryan
Environment=MINIO_ROOT_PASSWORD=letmeinnow
Environment=MINIO_SERVER_URL=https://files.cloud.mystiks.io
Environment=MINIO_BROWSER_REDIRECT_URL=https://www.mystiks.com
ExecStart=/usr/local/bin/minio server https://files-{1...{{COUNTMACHINES}}}.cloud.mystiks.io/mnt/disk{1...{{COUNTDISKS}}}_{{DATETIME}}/data \
  --certs-dir /usr/local/certs \
  --address "${IP_ADDRESS_PUBLIC}:443" \
  --console-address "${IP_ADDRESS_PUBLIC}:9876"

RestartSec=5s
Restart=Always

[Install]
WantedBy=multi-user.target
```

Once I replaced `/usr/local/bin/minio` with the rolled-back version on both machines and issued `systemctl restart minio` all went well!

I'll monitor this over the next couple of weeks to provide additional details you request
-R

**Comment by ryanlelek** [comment]
Hi, not intending to hijack.
I encountered a similar issue with "latest" [2021-09-24 Release](https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-09-24T00-24-24Z)

Rolling back to [2021-09-03 Release](https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-09-03T03-56-13Z) as @northway suggested fixed my issue as well.
More detail below.

- New Cluster (no data)
- 2 Machines, 2 disks each for testing/eval.
- No Nginx, Load Balancer, K8s.
- Yes, using TLS
- Had success with standalone, wanted to take the "next step" while limiting new additions. So cluster was next.

Issue - Any upload would respond with "broken pipe" or similar connections. Small files ~100MiB would give this error around chunk 5MiB. So I decided to try even smaller. first 4MiB and then 1KiB. All failed with similar error.

So I disabled firewall rules, uninstalled Debian apparmor, just to see. Still the issue persisted.
Switching clients (GUI, minio-client on macOS, minio-client on Linux), didn't seem to change much
Got to searching and found this (thank you!)

To reproduce, this happened to be on Debian 11 with 2, 10GB disks in a cloud provider. Total 4 disks.
Here's the systemd unit file.
Other than that, it's a clean install.
```
[Unit]
Description=Minio Cloud File Server
After=syslog.target

[Service]
Environment=MINIO_ROOT_USER=minioroot
Environment=MINIO_ROOT_PASSWORD=minioadminpass
Environment=MINIO_SERVER_URL=https://files.example.com
Environment=MINIO_BROWSER_REDIRECT_URL=https://www.example.com
ExecStart=/usr/local/bin/minio server https://files-{1...2}.files.example.com/mnt/disk{1...2}_20211001/data \
  --certs-dir /usr/local/certs \
  --address "${IP_ADDRESS_PUBLIC}:443" \
  --console-address "${IP_ADDRESS_PUBLIC}:9876"

RestartSec=5s
Restart=Always

[Install]
WantedBy=multi-user.target
```

Once I replaced `/usr/local/bin/minio` with the rolled-back version on both machines and issued `systemctl restart minio` all went well!

I'll monitor this over the next couple of weeks to provide additional details you request
-R
