### ISSUE TITLE
Unable to upload file in minio server

### ISSUE THREAD

**Issue by ellurunaresh** [minio/minio#13266]
I'm using latest minio docker image from docker registry. While running docker I was getting error below

API: SYSTEM()
Time: 08:14:10 UTC 09/22/2021
DeploymentID: a203af28-c4c0-469d-9758-2d231e02f34f
**Error: volume not found (cmd.StorageErr)
         2: cmd/bucket-metadata-sys.go:483:cmd.(*BucketMetadataSys).concurrentLoad()
         1: cmd/bucket-metadata-sys.go:493:cmd.(*BucketMetadataSys).load()**

Even I tried in browser with **http://localhost:9001** where I was trying to upload a file from the computer. Please find attached screenshot.

![image](https://user-images.githubusercontent.com/10192331/134309547-b0c276c9-5a27-4cf8-8662-c91279bba691.png)

* Version used (`minio --version`): RELEASE.2021-09-18T18-09-59Z
* Operating System and version:
  - Windows 10, 64 bit
  - WSL 2 environment

**Comment by klauspost** [comment]
This should already be fixed by https://github.com/minio/minio/pull/13254 which will be in next release.
