### ISSUE TITLE
minio fails to start in Docker 1.11

### ISSUE THREAD

**Issue by hairyhenderson** [minio/minio#1329]
When I start the [minio/minio](https://hub.docker.com/r/minio/minio/) image after upgrading to Docker 1.11, I see:

```
minio: <ERROR> Please run ‘minio’ as a non-root user.
```

Which is weird, because that check first makes a call to `isContainerized` (https://github.com/minio/minio/blob/2bb262cc567c71da6556baf386a53fbe0440249e/main.go#L73).

Digging a little deeper, I see that `isContainerized` checks for the existence of `/.dockerinit` (https://github.com/minio/minio/blob/af907a35a9fc51497772529053e3174fa38bbb86/runtime-checks.go#L33), which is where that function would've returned `true` in Docker 1.10.

The problem is, `/.dockerinit` was removed from Docker 1.11 (see https://github.com/docker/docker/pull/19490).

This _may_ work if https://github.com/minio/minio/blob/af907a35a9fc51497772529053e3174fa38bbb86/runtime-checks.go#L39 is patched as follows:

``` patch
- if strings.Contains(string(cgroupData), "/docker-") {
+ if strings.Contains(string(cgroupData), "/docker") {
```

I may PR this change, but I'm not too sure what the implications are.

An alternative is simply to set the environment variable `ALLOW_CONTAINER_ROOT=true`, so this isn't a massive show-stopper.

**Comment by hairyhenderson** [comment]
Oh, and an even simpler fix may be to just replace (or supplement) the check for `/.dockerinit` with a check for `/.dockerenv`... :wink:

**Comment by harshavardhana** [comment]
Although accepted the patch the docker container is already fixed from 'release' branch.
