### ISSUE TITLE
S3 Gateway Mode + KES Encryption + Object Lock/WORM = not working

### ISSUE THREAD

**Issue by furio** [minio/minio#13314]
I've started minio RELEASE.2021-09-24T00-24-24Z in gateway mode, with transparent encryption (`MINIO_KMS_AUTO_ENCRYPTION=on`)  with KES.
The destination bucket on S3 has object lock enabled with default governance mode with 1 day retention

I ran `./mc cp README.md mys3/202109-xxx-test-crypto-lock/ --debug --insecure --md5`
And i get
```
mc: <ERROR> Failed to copy `README.md`. Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters
 (3) cp-main.go:585 cmd.doCopySession(..) Tags: [README.md]
 (2) common-methods.go:562 cmd.uploadSourceToTargetURL(..) Tags: [README.md]
 (1) common-methods.go:324 cmd.putTargetStream(..) Tags: [mys3, https://127.0.0.1:9000/202109-xxx-test-crypto-lock/README.md]
 (0) client-s3.go:1029 cmd.(*S3Client).Put(..)
```

## Expected Behavior
The object should be uploaded with the proper md5 being calculated and sent to AWS S3

## Current Behavior
The file is not being uploaded, with the error:
```
mc: <ERROR> Failed to copy `README.md`. Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters
 (3) cp-main.go:585 cmd.doCopySession(..) Tags: [README.md]
 (2) common-methods.go:562 cmd.uploadSourceToTargetURL(..) Tags: [README.md]
 (1) common-methods.go:324 cmd.putTargetStream(..) Tags: [mys3, https://127.0.0.1:9000/202109-xxx-test-crypto-lock/README.md]
 (0) client-s3.go:1029 cmd.(*S3Client).Put(..)
```

## Possible Solution
I've put some breakpoints in the minio source code, and during the upload phase i get this stack:
![](https://i.imgur.com/ANgQjqQ.jpg)

in `gateway-s3.go` the function `PutObject` set `SendContentMd5: true,`  ( `md5Base64, sha256Hex`  vars are empty) but is ignored in `api-put-object-streaming.go :: putObjectDo` it seems that the funcyion "above" `putObject` has the compute code

I've changed in `core.go`
```
// PutObject - Upload object. Uploads using single PUT call.
func (c Core) PutObject(ctx context.Context, bucket, object string, data io.Reader, size int64, md5Base64, sha256Hex string, opts PutObjectOptions) (UploadInfo, error) {
	hookReader := newHook(data, opts.Progress)
	return c.putObjectDo(ctx, bucket, object, hookReader, md5Base64, sha256Hex, size, opts)
}
```
to
```
// PutObject - Upload object. Uploads using single PUT call.
func (c Core) PutObject(ctx context.Context, bucket, object string, data io.Reader, size int64, md5Base64, sha256Hex string, opts PutObjectOptions) (UploadInfo, error) {
	hookReader := newHook(data, opts.Progress)
	return c.putObject(ctx, bucket, object, hookReader, size, opts)
}
```

And the upload of a small file works (with encrypted dare ecc) but i don't know if this is a valid solution :) (I haven't analyzed for multipart)

## Steps to Reproduce (for bugs)
1. Start a KES
2. Start MINIO in gateway S3 mode with TLS, `MINIO_KMS_AUTO_ENCRYPTION=on`, amd connected to KES 
3. Set a bucket in S3 with object lock with default options enabled (governance + day retention)
4. Upload via mc

## Context
Migrating data with transparent encryption to a bucket with WORM/Object lock enabled

## Regression
Don't know if it's a regression

## Your Environment
Minio version: RELEASE.2021-09-24T00-24-24Z
Latest kes/mc
Linux Ubuntu 20.04

**Comment by harshavardhana** [comment]
Using encryption on MinIO layer requires a custom backend format on AWS S3 - this creates a lot of problems if you have object locking enabled. 

Since the implementation does not understand versioned buckets at all because MinIO Gateway itself doesn't implement Object locking APIs at gateway layer. 

The scope of the gateway implementation currently won't change and we are not considering expanding it to support versioning as well while supporting encryption at the gateway layer. 

This is too much of a complexity for which gateway is not designed.  Closing this issue since this is not actionable for us for now also updated the S3 known limitations list in this commit 
5d7ed8ff7dab91ec470c75db20cc8a5d13761a12
