### ISSUE TITLE
Completing multipart upload multiple times fails

### ISSUE THREAD

**Issue by semberal** [minio/minio#13318]
Hi,

I noticed an incompatibility between minio and S3 API. When I try to complete multipart upload multiple times, the first request succeeds, but all the subsequent ones fail with:

```
botocore.errorfactory.NoSuchUpload: An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
```

Here is a minimal python script, which reproduces the behavior (fails with Minio, succeeds with S3):

```python
#!/usr/bin/env/python
import boto3
from botocore.client import Config


bucket = "bucket1"
key="key2"

s3 = boto3.client(
    's3',
    endpoint_url='http://localhost:9000',
    aws_access_key_id='minioadmin',
    aws_secret_access_key='minioadmin',
    config=Config(signature_version='s3v4'),
    region_name='us-east-1'
)

create_response = s3.create_multipart_upload(Bucket=bucket, Key=key)
upload_id = create_response["UploadId"]

upload_part_response = s3.upload_part(Bucket=bucket, Key=key, UploadId = upload_id, Body=b'abc', PartNumber=1)

s3.complete_multipart_upload(Bucket=bucket, Key=key, UploadId=upload_id, MultipartUpload={"Parts": [{"ETag": upload_part_response["ETag"], "PartNumber": 1}]})
s3.complete_multipart_upload(Bucket=bucket, Key=key, UploadId=upload_id, MultipartUpload={"Parts": [{"ETag": upload_part_response["ETag"], "PartNumber": 1}]})

print("OK")
```

**Comment by harshavardhana** [comment]
@semberal please explain your setup details first, just throwing a code here is not useful for us.

**Comment by harshavardhana** [comment]
Okay I read the issue this is correct MinIO is a strictly consistent object store so 

> ```python
> s3.complete_multipart_upload(Bucket=bucket, Key=key, UploadId=upload_id, MultipartUpload={"Parts": [{"ETag": upload_part_response["ETag"], "PartNumber": 1}]})
> s3.complete_multipart_upload(Bucket=bucket, Key=key, UploadId=upload_id, MultipartUpload={"Parts": [{"ETag": upload_part_response["ETag"], "PartNumber": 1}]})
> ```

So your first call already succeeded we do not remember again your upload-id, however, AWS S3 remembers for easily 24hrs for no reason. After that, it will return the same error as MinIO.
