### ISSUE TITLE
Login With SSO - endless loop

### ISSUE THREAD

**Issue by mieseprem** [minio/minio#13323]
It seems there is a breaking change between RELEASE.2021-09-18T18-09-59Z and RELEASE.2021-09-23T04-46-24Z when working with MINIO_IDENTITY_OPENID_*
I had a look at the diff https://github.com/minio/minio/compare/RELEASE.2021-09-18T18-09-59Z...RELEASE.2021-09-23T04-46-24Z and the only thing I can imagin that could be the cause is https://github.com/minio/minio/commit/c25b4823011d654ca3c8da7fc3c127023f1146e4. But even there I can't find a note regarding breaktin changes between 0.9.x and 0.10.x (which would also contradict semantic versioning).

I can't provide any logs as I didn't found any.

## Expected Behavior
Open MinIO in Browser -> press on "Login With SSO" -> redirect to OpenID provider -> login -> access to MinIO

## Current Behavior
Open MinIO in Browser -> press on "Login With SSO" -> press on "Login With SSO" -> press on "Login With SSO" ...

## Possible Solution
I don't know any workaround. The POD log remain unchanged at this:
```text
 You are running an older version of MinIO released 19 hours ago 
 Update: Run `mc admin update` 


API: https://minio.url  

Console: https://console.url 

Documentation: https://docs.min.io 
```

## Steps to Reproduce (for bugs)

1. Deploy MinIO with release RELEASE.2021-09-18T18-09-59Z and provide the following environment variables with proper values:
- MINIO_BROWSER_REDIRECT_URL
- MINIO_IDENTITY_OPENID_CLAIM_NAME
- MINIO_IDENTITY_OPENID_CLIENT_ID
- MINIO_IDENTITY_OPENID_CLIENT_SECRET
- MINIO_IDENTITY_OPENID_CONFIG_URL
- MINIO_ROOT_PASSWORD
- MINIO_ROOT_USER
- MINIO_SERVER_URL
2. Login and verify all is fine
3. Upgrade to release RELEASE.2021-09-23T04-46-24Z (or RELEASE.2021-09-24T00-24-24Z - same result)
4. Try to login again (will fail)

## Context
I tried to upgrade MinIO to the current release but found a non functional environment afterwards.

## Regression
I don't know

## Your Environment

Run MinIO as Service in Openshift.

**Comment by harshavardhana** [comment]
This is fixed in 84dcd25a36bdaa00ad4167282bc2ca19e6b29f26
