### ISSUE TITLE
STS and serviceaccount access

### ISSUE THREAD

**Issue by fcomte** [minio/minio#13325]
We are using minio and keycloak.
User can access minio with a policy like that : 

```   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::${jwt:preferred_username}",
     "arn:aws:s3:::${jwt:preferred_username}/*"
    ]
   }
  ```

## Expected Behavior
service account created by sts user can get access the same level of access.

## Current Behavior
service account created by sts users can't get access to the policy mapped for sts users because i guess ${jwt:preferred_username} means nothing for the serviceaccount.

**Comment by fcomte** [comment]
Thx i will test that ! Can you tell me if the service account expire when the parent token expire ?

**Comment by harshavardhana** [comment]
> Thx i will test that ! Can you tell me if the service account expire when the parent token expire ?

@fcomte - Service accounts do not expire they are meant to be static credentials unlike STS credentials. They are meant for applications that have no ability to do auto-renewals - If you wish to remove service accounts automatically when users are deleted on IDP it is supported with 

- LDAP directly
- Keycloak IDP only

```
MINIO_IDENTITY_OPENID_VENDOR              (string)    Specify vendor type for vendor specific behavior to checking validity of temporary credentials and service accounts on MinIO
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM      (string)    Specify Keycloak 'realm' name, only honored if vendor was set to 'keycloak' as value, if no realm is specified 'master' is default
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL  (string)    Specify Keycloak 'admin' REST API endpoint e.g. http://localhost:8080/auth/admin/
```

**Comment by fcomte** [comment]
perfect thx

**Comment by tanrobotix** [comment]
Hi @harshavardhana , I wonder how "_**to remove service accounts automatically when users are deleted on Keycloak IDP**_"
I've tried setting up those envs and setting up Keycloak audience mapper security-admin-console, and add it to the role, etc...

- On minio: i configured the 3 env variables you mentioned above
- On keycloak: enabled service account for the client, added realm-management role to the service account roles.

However, it didn't work. After the user was deleted from keycloak, I'm still able to use the associated service account with minio client. Would you mind providing more step detail to configure
