### ISSUE TITLE
Service accounts have wrong permissions after changed STS users

### ISSUE THREAD

**Issue by aitchjoe** [minio/minio#13334]
## Expected Behavior

1. Login MinIO console as GitLab SSO user, in console the user can see for example: bucket1 and bucket2.
1. Create service account sa1, `mc ls` with sa1, the results are bucket1 and bucket2.
1. Change the user's GitLab groups, for example only bucket1.
1. Re-login console, the user only see bucket1.
1. Create service account sa2, `mc ls` with sa2, the result is only bucket1.

## Current Behavior

1. Login MinIO console as GitLab SSO user, in console the user can see for example: bucket1 and bucket2.
1. Create service account sa1, `mc ls` with sa1, the results are bucket1 and bucket2.
1. Change the user's GitLab groups, for example only bucket1.
1. Re-login console, the user only see bucket1.
1. Create service account sa2, `mc ls` with sa2, the results are **still** bucket1 and bucket2.
1. **Restart** all MinIO instance (not console).
1. Re-login and create sa3, `mc ls` with sa3, the result is only bucket1.

## Possible Solution

Maybe need invalid MinIO server's cache after each STS users login.

## Your Environment

* minio version RELEASE.2021-09-24T00-24-24Z
* console version 0.10.2 - 2269af82
* Ubuntu 20.04 LTS (Focal Fossa)
* GitLab Community Edition 13.9.0

**Comment by vadmeste** [comment]
It is little bit confusing when you say STS user but I guess you mean Gitlab users ?

Just to confirm, how did you create the service account ?

**Comment by aitchjoe** [comment]
Yes, STS user are GitLab user. I created service account in MinIO web console (alone, not embedded in MinIO server).

**Comment by harshavardhana** [comment]
Recommended approach here is to use https://github.com/minio/minio/pull/13651 the role_arn based approach instead of SSO logins based on remote policies. 

Such that the policies and roles can be controlled locally on MinIO.
