### ISSUE TITLE
security_token not checked 

### ISSUE THREAD

**Issue by insigh** [minio/minio#13335]
put is successfully even if random security_token is supplied.
## Expected Behavior

put is refused if a wrong security_token is supplied.
## Current Behavior

put is accepted and successful.
## Possible Solution

i have tried some old versions of minio that are of the expected bahavior; such as 2021-07-15T22-27-34Z
## Steps to Reproduce (for bugs)

1.  deploy a minio server 
2.  add a bucket in the web browser
3.  put a file using libs3 sdk (BucketContext with a wrong security_token)
4.  put is successful, which is expected refused by minio server, as old version's behavior.

## Your Environment

* Version used (`minio --version`):  2021-09-18T18-09-59Z
* Server setup and configuration: default
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@insigh please share entire code.

**Comment by klauspost** [comment]
Trying a few variations, I was unable to reproduce.

S3v4 with wrong secret key:

```
<DEBUG> PUT /testbucket/inspect.595275b9.enc HTTP/1.1
Host: play.min.io
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
Content-Length: 38
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211001/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20211001T105642Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 457
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 01 Oct 2021 10:56:42 GMT
Server: nginx/1.14.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 16A9E2E277EECE9C
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E2E277EECE9C</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
```

S3v2, with wrong secret:
```
<DEBUG> PUT /testbucket/inspect.595275b9.enc HTTP/1.1
Host: play.min.io
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
Content-Length: 38
Authorization: AWS **REDACTED**:**REDACTED**
Content-Type: application/octet-stream
Date: Fri, 01 Oct 2021 10:57:47 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 457
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 01 Oct 2021 10:57:46 GMT
Server: nginx/1.14.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 16A9E2F18A2B30BC
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E2F18A2B30BC</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
```

Without signature:
```
<DEBUG> PUT /testbucket/inspect.595275b9.enc HTTP/1.1
Host: play.min.io
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
Content-Length: 38
Content-Type: application/octet-stream
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 349
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 01 Oct 2021 10:56:33 GMT
Server: nginx/1.14.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 16A9E2E05FD706A3
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E2E05FD706A3</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
```
With random Bearer/JWT:

```
 PUT /testbucket/inspect.595275b9.enc HTTP/1.1
Host: play.min.io
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
Content-Length: 38
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMzA4NjkzMCwiaWF0IjoxNjMzMDg2OTMwfQ.jay98qLfGfU5WjDK4nX6eYE8HHhQwL5RIBFaQfH9Fvw
Content-Type: application/octet-stream
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 349
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 01 Oct 2021 11:16:05 GMT
Server: nginx/1.14.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 16A9E3F138408461
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E3F138408461</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
```

**Comment by harshavardhana** [comment]
> Trying a few variations, I was unable to reproduce.
> 
> S3v4 with wrong secret key:
> 
> ```
> <DEBUG> PUT /testbucket/inspect.595275b9.enc HTTP/1.1
> Host: play.min.io
> User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
> Content-Length: 38
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211001/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> Content-Type: application/octet-stream
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20211001T105642Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 403 Forbidden
> Content-Length: 457
> Accept-Ranges: bytes
> Connection: keep-alive
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/xml
> Date: Fri, 01 Oct 2021 10:56:42 GMT
> Server: nginx/1.14.0 (Ubuntu)
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Bucket-Region: us-east-1
> X-Amz-Request-Id: 16A9E2E277EECE9C
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E2E277EECE9C</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
> ```
> 
> S3v2, with wrong secret:
> 
> ```
> <DEBUG> PUT /testbucket/inspect.595275b9.enc HTTP/1.1
> Host: play.min.io
> User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
> Content-Length: 38
> Authorization: AWS **REDACTED**:**REDACTED**
> Content-Type: application/octet-stream
> Date: Fri, 01 Oct 2021 10:57:47 GMT
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 403 Forbidden
> Content-Length: 457
> Accept-Ranges: bytes
> Connection: keep-alive
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/xml
> Date: Fri, 01 Oct 2021 10:57:46 GMT
> Server: nginx/1.14.0 (Ubuntu)
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Bucket-Region: us-east-1
> X-Amz-Request-Id: 16A9E2F18A2B30BC
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E2F18A2B30BC</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
> ```
> 
> Without signature:
> 
> ```
> <DEBUG> PUT /testbucket/inspect.595275b9.enc HTTP/1.1
> Host: play.min.io
> User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
> Content-Length: 38
> Content-Type: application/octet-stream
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 403 Forbidden
> Content-Length: 349
> Accept-Ranges: bytes
> Connection: keep-alive
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/xml
> Date: Fri, 01 Oct 2021 10:56:33 GMT
> Server: nginx/1.14.0 (Ubuntu)
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Bucket-Region: us-east-1
> X-Amz-Request-Id: 16A9E2E05FD706A3
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E2E05FD706A3</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
> ```
> 
> With random Bearer/JWT:
> 
> ```
>  PUT /testbucket/inspect.595275b9.enc HTTP/1.1
> Host: play.min.io
> User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc/DEVELOPMENT.GOGET
> Content-Length: 38
> Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMzA4NjkzMCwiaWF0IjoxNjMzMDg2OTMwfQ.jay98qLfGfU5WjDK4nX6eYE8HHhQwL5RIBFaQfH9Fvw
> Content-Type: application/octet-stream
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 403 Forbidden
> Content-Length: 349
> Accept-Ranges: bytes
> Connection: keep-alive
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/xml
> Date: Fri, 01 Oct 2021 11:16:05 GMT
> Server: nginx/1.14.0 (Ubuntu)
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Bucket-Region: us-east-1
> X-Amz-Request-Id: 16A9E3F138408461
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>inspect.595275b9.enc</Key><BucketName>testbucket</BucketName><Resource>/testbucket/inspect.595275b9.enc</Resource><Region>us-east-1</Region><RequestId>16A9E3F138408461</RequestId><HostId>c1758167-4426-454f-9aae-5c3dfdf6df64</HostId></Error>
> ```

Will close this based on this.

**Comment by insigh** [comment]
@klauspost thank you very much for your instantly reply, but i still have some doubt, looking forward to your reply.
the result between different minio version:
![image](https://user-images.githubusercontent.com/13135790/136489967-e8f12e0e-8ae0-4f66-ab5e-ea4e9a9f5f1b.png)

the code using LibS3 api to access minio:
![image](https://user-images.githubusercontent.com/13135790/136490105-22cfffe5-91e1-4c5b-86ef-7f2e869f5c17.png)

could you please tell me how to make it behave the same, thanks very much!

**Comment by harshavardhana** [comment]
@insigh please run `mc admin trace -v` and share us the results when it fails.

**Comment by klauspost** [comment]
@insigh So you still provide a valid access/secret key? Let me check that combo.

**Comment by klauspost** [comment]
Confirmed, when otherwise valid credentials are passed `X-Amz-Security-Token` is ignored. Checking internally if this is by design.

**Comment by insigh** [comment]
> @insigh So you still provide a valid access/secret key? Let me check that combo.
Yes, valid access/secret key is provided. and what is expected is that when invalid token is provided, bucket test return  errorcode other than ok.

**Comment by klauspost** [comment]
@aead noted:
> For static S3 credentials there is no `X-Amz-Security-Token`. I don't know what AWS does if you use static credentials but provide a (invalid) security token. Since the static credentials are valid without a token
>it may be possible that AWS ignores the provided security token or they may return a error complaining that a security token should not be passed for this access key.

We may have changed whether we ignore `X-Amz-Security-Token`. I will leave this to @aead to decide if this is a bug.

**Comment by harshavardhana** [comment]
If x-amz-security-token is specified without a valid value for static credentials we reject such malicious requests.

**Comment by harshavardhana** [comment]
@insigh you should share `mc admin trace -v` with us.

**Comment by insigh** [comment]
@harshavardhana 
Thanks, here are mc admin trace info below:
1. behavior of version "RELEASE-2021-07-15T22-27-34Z"
![image](https://user-images.githubusercontent.com/13135790/136641800-0564deab-7d57-4c92-9df0-197a692344b7.png)
2. behavior of the version "RELEASE-2021-09-18T18-09-59Z"
![image](https://user-images.githubusercontent.com/13135790/136641947-1a1ec8da-0e4e-4331-aa28-55c572c07c5c.png)

**Comment by harshavardhana** [comment]
> @harshavardhana 
> Thanks, here are mc admin trace info below:
> 1. behavior of version "RELEASE-2021-07-15T22-27-34Z"
> ![image](https://user-images.githubusercontent.com/13135790/136641800-0564deab-7d57-4c92-9df0-197a692344b7.png)
> 2. behavior of the version "RELEASE-2021-09-18T18-09-59Z"
> ![image](https://user-images.githubusercontent.com/13135790/136641947-1a1ec8da-0e4e-4331-aa28-55c572c07c5c.png)
> 

This is not an intended change looks like, we should fix it.

Will check the behavior with AWS S3
