### ISSUE TITLE
Caching not working when request is made from same instance as of minio or same region as minio instance. 

### ISSUE THREAD

**Issue by manigarg31** [minio/minio#13353]
If request is made from same instance as minio, cache.json looks like this:
cat cache.json
{"version":"1.0.0","stat":{"size":2110,"modTime":"0001-01-01T00:00:00Z","name":"","dir":false},"checksum":{"algorithm":"highwayhash256S","blocksize":1048576},"meta":{"etag":"2f282b84e7e608d5852449ed940bfc51"},"hits":5,"bucket":"test","object":"100MB.bin"}
After MINIO_CACHE_AFTER these hits, cache.json is removed and new cache.json is made when we again make a request

Else:
cat cache.json
{"version":"1.0.0","stat":{"size":104857600,"modTime":"0001-01-01T00:00:00Z","name":"","dir":false},"checksum":{"algorithm":"highwayhash256S","blocksize":1048576},"meta":{"X-Minio-Internal-actual-size":"104857600","X-Minio-Internal-compression":"klauspost/compress/s2","content-type":"application/macbinary","etag":"2f282b84e7e608d5852449ed940bfc51","expires":"Mon, 01 Jan 0001 00:00:00 GMT","last-modified":"Mon, 04 Oct 2021 06:19:28 GMT"},"hits":8,"bucket":"test","object":"100MB.bin"}

Caching is not working when get request is made from same instance or from same region as minio instance. While it works fine when getting objects over vpn

**Comment by harshavardhana** [comment]
@manigarg31 please explain your setup details - there is literally nothing shared here for us to help you.

**Comment by manigarg31** [comment]
Running minio in docker:
docker run  --env MINIO_COMPRESS="true" --env MINIO_COMPRESS_EXTENSIONS="" --env MINIO_COMPRESS_MIMETYPES="" --env MINIO_CACHE="on" --env MINIO_CACHE_DRIVES="/mnt/data1"  --env MINIO_CACHE_QUOTA=80 --env MINIO_CACHE_AFTER=5 --env MINIO_CACHE_WATERMARK_LOW=70 --env MINIO_CACHE_WATERMARK_HIGH=90 --env MINIO_PROMETHEUS_AUTH_TYPE="public" -p 9000:9000 -p 9001:9001 --name minio17 -v /var/lib/minio:/data -v /home/ubuntu/minio1:/mnt/data1 minio/minio server /data --console-address ":9001"

**Comment by harshavardhana** [comment]
> Running minio in docker:
> docker run --env MINIO_COMPRESS="true" --env MINIO_COMPRESS_EXTENSIONS="" --env MINIO_COMPRESS_MIMETYPES="" --env MINIO_CACHE="on" --env MINIO_CACHE_DRIVES="/mnt/data1" --env MINIO_CACHE_QUOTA=80 --env MINIO_CACHE_AFTER=5 --env MINIO_CACHE_WATERMARK_LOW=70 --env MINIO_CACHE_WATERMARK_HIGH=90 --env MINIO_PROMETHEUS_AUTH_TYPE="public" -p 9000:9000 -p 9001:9001 --name minio17 -v /var/lib/minio:/data -v /home/ubuntu/minio1:/mnt/data1 minio/minio server /data --console-address ":9001"

which version of MinIO is this?

**Comment by manigarg31** [comment]
minio version RELEASE.2021-10-02T16-31-05Z

**Comment by manigarg31** [comment]
> > Running minio in docker:
> > docker run --env MINIO_COMPRESS="true" --env MINIO_COMPRESS_EXTENSIONS="" --env MINIO_COMPRESS_MIMETYPES="" --env MINIO_CACHE="on" --env MINIO_CACHE_DRIVES="/mnt/data1" --env MINIO_CACHE_QUOTA=80 --env MINIO_CACHE_AFTER=5 --env MINIO_CACHE_WATERMARK_LOW=70 --env MINIO_CACHE_WATERMARK_HIGH=90 --env MINIO_PROMETHEUS_AUTH_TYPE="public" -p 9000:9000 -p 9001:9001 --name minio17 -v /var/lib/minio:/data -v /home/ubuntu/minio1:/mnt/data1 minio/minio server /data --console-address ":9001"
> 
> which version of MinIO is this?

minio version RELEASE.2021-10-02T16-31-05Z

**Comment by manigarg31** [comment]
Any update on this?

**Comment by harshavardhana** [comment]
> Any update on this?

No updates - community issues have no SLA @manigarg31 we will get to it when we can.

**Comment by poornas** [comment]
@manigarg31 , cache is not useful in front of a server in fs mode - you may as well remove the cache here.
The cache.json you posted above belong to two different objects - if you notice, the size and compression info are differing between the two. You seem to have turned on compression in b/w and overwritten the object which explains why a new cache.json was created

**Comment by manigarg31** [comment]
> @manigarg31 , cache is not useful in front of a server in fs mode - you may as well remove the cache here.
> The cache.json you posted above belong to two different objects - if you notice, the size and compression info are differing between the two. You seem to have turned on compression in b/w and overwritten the object which explains why a new cache.json was created

@poornas  No compression was already turned on but this happens whenever we make a call from python api whereas it works fine if we make a curl call.

If we use ssd as cache and hdd as storage, so is caching not useful in this case also?

**Comment by poornas** [comment]
>If we use ssd as cache and hdd as storage, so is caching not useful in this case also?

you could use it like this

I tried to repro this and the object gets cached after 5 hits with the same settings. It is possible that object could not be cached because usage was close to the high watermark.

**Comment by manigarg31** [comment]
Cool, Thanks.

**Comment by harshavardhana** [comment]
> I tried to repro this and the object gets cached after 5 hits with the same settings. It is possible that object could not be cached because usage was close to the high watermark.

Closing this as a non-issue at the moment.
