### ISSUE TITLE
Login with minio version with console and OIDC fails with no logs in minio stdout but older webbrowser works

### ISSUE THREAD

**Issue by husa570** [minio/minio#13355]
Running minio as container against a IDP (keycloak) and it works with the old version with the web browser
Pulling image from local repository

**This config works**

docker run -d -p 443:9000 --name minio \
  -e "MINIO_IDENTITY_OPENID_CONFIG_URL=https://myidp.mgmt.exampledomain.net:8443/auth/realms/minio-local/.well-known/openid-configuration" \
  -e "MINIO_IDENTITY_OPENID_CLIENT_ID=minio-local-client" \
  -e "MINIO_IDENTITY_OPENID_CLAIM_NAME=groups" \
  -e "MINIO_ROOT_USER=minio_admin" \
  -e "MINIO_ROOT_PASSWORD=myminiopassword" \
  -e "MINIO_PROMETHEUS_AUTH_TYPE=public" \
  -e "MINIO_DOMAIN=s3.proj9.exampledomain.net" \
  -v /usr/share/zoneinfo/Europe/Stockholm:/etc/localtime:ro \
  -v /srv/s3data/disk1:/data1 \
  -v /srv/s3data/disk2:/data2 \
  -v /srv/s3data/disk3:/data3 \
  -v /srv/s3data/disk4:/data4 \
  -v /srv/minio/cert:/root/.minio/certs \
  library/minio/minio:RELEASE.2021-06-09T18-51-39Z server /data{1...4}

**The setup below dosent work,** get redirected to the IDP but after successful login back to sso login page on built-in minio console
Nothing useful in "docker logs minio"

docker run -d -p 443:9000 -p 9001:9001 --name minio \
  -e "MINIO_IDENTITY_OPENID_CONFIG_URL=https://myidp.mgmt.exampledomain.net:8443/auth/realms/minio-local/.well-known/openid-configuration" \
  -e "MINIO_IDENTITY_OPENID_CLIENT_ID=minio-local-client" \
  -e "MINIO_IDENTITY_OPENID_CLAIM_NAME=groups" \
  -e "MINIO_ROOT_USER=myminioadmin" \
  -e "MINIO_ROOT_PASSWORD=myminiopassword" \
  -e "MINIO_PROMETHEUS_AUTH_TYPE=public" \
  -e "MINIO_DOMAIN=s3.proj9.exampledomain.net" \
  -e "MINIO_IDENTITY_OPENID_REDIRECT_URI=https://myminio.proj9.exampledomain.net:9001/oauth_callback" \
  -e "MINIO_SERVER_URL=https://myminio.proj9.exampledomain.net:443" \
  -e "MINIO_BROWSER_REDIRECT_URL=https://myminio.proj9.exampledomain.net:9001" \
  -v /usr/share/zoneinfo/Europe/Stockholm:/etc/localtime:ro \
  -v /srv/s3data/disk1:/data1 \
  -v /srv/s3data/disk2:/data2 \
  -v /srv/s3data/disk3:/data3 \
  -v /srv/s3data/disk4:/data4 \
  -v /srv/minio/cert:/root/.minio/certs \
  library/minio/minio:RELEASE.2021-10-02T16-31-05Z server /data{1...4} --console-address ":9001"

uname -a
Linux myminio 5.3.18-24.78-default #1 SMP Mon Aug 2 21:00:23 UTC 2021 (a13100d) x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:           20.10.6-ce
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        8728dd246c3a
 Built:             Thu Apr 15 12:00:00 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd246c3a
  Built:            Thu Apr 15 12:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit:

I did not delete the data1-4 efter upgrade so the policys are still there according to miniomc.
When I "downgrade" to the first config (docker stop minio, docker rm minio and docker run as above) i works again.
So the policys in minio seems to be correct

Im stuck, what have I done wrong?

**Comment by harshavardhana** [comment]
> library/minio/minio:RELEASE.2021-06-09T18-51-39Z server /data{1...4}

You should upgrade to the latest release @husa570 

This works as intended, the callback URL for me is http://10.0.0.67:9001/oauth_callback

```
export MINIO_IDENTITY_OPENID_CONFIG_URL=https://gitlab.com/.well-known/openid-configuration
export MINIO_IDENTITY_OPENID_CLIENT_ID="b0088c3836bb029393942f71ed7c8ac0add7f0856e6c86e67b0ff98f85c48658"
export MINIO_IDENTITY_OPENID_CLIENT_SECRET="ed72087b37624e89816ac27c1355420902045274edd7baad2ae29b1b0e8436fe"
export MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
export MINIO_IDENTITY_OPENID_CLAIM_USERINFO="on"
export MINIO_IDENTITY_OPENID_CLAIM_NAME="groups"

minio server /tmp/xl{1...4} --console-address ":9001"
```

If you have trouble with some extra logs you can enable 

```
export _MINIO_SERVER_DEBUG=on
```

This should print some errors related to your IDP.

**Comment by husa570** [comment]
Thanks the **_MINIO_SERVER_DEBUG=on** really helped.
At the time when I open this issue I was using the latest version (at least to my understanding).

According to [https://docs.min.io/minio/baremetal/security/openid-external-identity-management/configure-openid-external-identity-management.html](url)
"The following example code sets all environment variables related to configuring an OIDC provider for external identity management. 
The minimum required variable is MINIO_IDENTITY_OPENID_CONFIG_URL:" 

_and_

[https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#envvar.MINIO_IDENTITY_OPENID_CLIENT_SECRET](url) "
"Optional
Specify the client secret MinIO uses when authenticating user credentials against the OIDC compatible provider. This field may be optional depending on the provider.

This environment variable corresponds with the identity_openid client_secret setting."

_and_

[https://docs.min.io/minio/baremetal/console/minio-console.html](url) 
in the documentation I didnt understand that the **MINIO_IDENTITY_OPENID_CLIENT_SECRET** was needed for the console but not for older versions with the web browser. 
But with **_MINIO_SERVER_DEBUG=on** the mapping between minio and the console made more sense.

**Comment by harshavardhana** [comment]
> Thanks the **_MINIO_SERVER_DEBUG=on** really helped. At the time when I open this issue I was using the latest version (at least to my understanding).
> 
> According to [https://docs.min.io/minio/baremetal/security/openid-external-identity-management/configure-openid-external-identity-management.html](url) "The following example code sets all environment variables related to configuring an OIDC provider for external identity management. The minimum required variable is MINIO_IDENTITY_OPENID_CONFIG_URL:"
> 
> _and_
> 
> [https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#envvar.MINIO_IDENTITY_OPENID_CLIENT_SECRET](url) " "Optional Specify the client secret MinIO uses when authenticating user credentials against the OIDC compatible provider. This field may be optional depending on the provider.
> 
> This environment variable corresponds with the identity_openid client_secret setting."
> 
> _and_
> 
> [https://docs.min.io/minio/baremetal/console/minio-console.html](url) in the documentation I didnt understand that the **MINIO_IDENTITY_OPENID_CLIENT_SECRET** was needed for the console but not for older versions with the web browser. But with **_MINIO_SERVER_DEBUG=on** the mapping between minio and the console made more sense.

Client_Secret is needed if your IDP doesn't support implicit flow.
