### ISSUE TITLE
Deleting an object is not replicated back to the source when the source is down.

### ISSUE THREAD

**Issue by tifling85** [minio/minio#13352]
I am using active-active bucket replication. I made two cluster of minio, and both have the same configurations. Each cluster has 3 nodes and 2 drivers per node(thus 6 drivers total).
I need to test replication when one cluster is unavailable.
I upload files (test1-1, test1-2) to cluster A, and files (test3-1, test3-2) to cluster B. The files are successfully replicated.
I turn off cluster B and delete all objects from cluster A.
I turn on cluster B, waiting for replication.
As a result, all objects on cluster A are deleted, but files 3-1 and 3-2 remain on cluster B.

## Expected Behavior
Two cluster becoming fully sync.

## Current Behavior
Deleting an object is not replicated back to the source when the source is down.

## Possible Solution
???

## Steps to Reproduce (for bugs)

1. creating clusters.

`mcli admin info tifweb-1`
> ●  10.179.37.146:9000
>    Uptime: 2 days 
>    Version: 2021-09-24T00:24:24Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> ●  10.179.37.223:9000
>    Uptime: 2 days 
>    Version: 2021-09-24T00:24:24Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> ●  10.179.37.248:9000
>    Uptime: 2 days 
>    Version: 2021-09-24T00:24:24Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 

`mcli admin info tifweb-3`
> ●  10.179.37.125:9000
>    Uptime: 1 hour 
>    Version: 2021-09-24T00:24:24Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> ●  10.179.37.172:9000
>    Uptime: 1 hour 
>    Version: 2021-09-24T00:24:24Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 
> 
> ●  10.179.37.233:9000
>    Uptime: 1 hour 
>    Version: 2021-09-24T00:24:24Z
>    Network: 3/3 OK 
>    Drives: 2/2 OK 

2. Сreate a buckets and set up replication.

```
mcli mb tifweb-1/loki-bucket
mcli mb tifweb-3/loki-bucket
```

```
mcli version enable tifweb-1/loki-bucket
mcli version enable tifweb-3/loki-bucket
```

```
mcli admin bucket remote add tifweb-1/loki-bucket http://minio:miniostorage@tifweb-3:9000/loki-bucket --service "replication"
mcli admin bucket remote add tifweb-3/loki-bucket http://minio:miniostorage@tifweb-1:9000/loki-bucket --service "replication"
```

```
mcli replicate add tifweb-1/loki-bucket --remote-bucket loki-bucket --arn "arn:minio:replication::fabaaa52-8535-4298-a13c-de1552cd7a19:loki-bucket" --replicate "delete,delete-marker,existing-objects"
mcli replicate add tifweb-3/loki-bucket --remote-bucket loki-bucket --arn "arn:minio:replication::b4fa00c6-9d1d-42b9-80df-32996cd7d0b2:loki-bucket" --replicate "delete,delete-marker,existing-objects"
```

3. upload files and check synchronization
```
mcli cp test1-1 tifweb-1/loki-bucket
mcli cp test1-2 tifweb-1/loki-bucket
mcli cp test3-1 tifweb-3/loki-bucket
mcli cp test3-2 tifweb-3/loki-bucket
```

`mcli ls --versions tifweb-1/loki-bucket`                                                                            

> [2021-10-04 05:30:11 MSK]     4B 24c760c6-d1c2-46b5-83fd-a3ba210bc50b v1 PUT test1-1                                                    
> [2021-10-04 05:30:15 MSK]     7B 904905e6-bee7-4562-889f-02fcfefcb4ee v1 PUT test1-2                                                    
> [2021-10-04 05:30:24 MSK]    10B 81496c97-e2f5-407d-93cf-281a895141ee v1 PUT test3-1                                                    
> [2021-10-04 05:30:21 MSK]    10B 0a4b4cec-8d14-4fef-8782-ae1dda74a1ee v1 PUT test3-2

`mcli ls --versions tifweb-3/loki-bucket`

> [2021-10-04 05:28:33 MSK]     4B ee29e3f3-698f-40dd-aec3-e69b0cb3206c v1 PUT test1-1
> [2021-10-04 05:28:36 MSK]     7B 3256b23d-0e38-4249-9262-586d7ca183ec v1 PUT test1-2
> [2021-10-04 05:27:32 MSK]    10B e651f434-1bf8-40f4-a037-3557bcba97f8 v1 PUT test3-1
> [2021-10-04 05:27:36 MSK]    10B 9911fbd9-915e-4f64-afea-810f318793f5 v1 PUT test3-2

4. Shut down the cluster B, delete all objects on cluster A.
```
mcli rm --force --versions tifweb-1/loki-bucket/test1-1
mcli rm --force --versions tifweb-1/loki-bucket/test1-2
mcli rm --force --versions tifweb-1/loki-bucket/test3-1
mcli rm --force --versions tifweb-1/loki-bucket/test3-2
```

5. Turn on cluster B, check objects.
`mcli ls --versions tifweb-1/loki-bucket`   # cluster A is correct, there are no objects

`mcli ls --versions tifweb-3/loki-bucket`

> [2021-10-04 05:30:24 MSK]    10B 81496c97-e2f5-407d-93cf-281a895141ee v1 PUT test3-1
> [2021-10-04 05:30:21 MSK]    10B 0a4b4cec-8d14-4fef-8782-ae1dda74a1ee v1 PUT test3-2

Cluster B contains its own objects. Replicated objects have been deleted.

6. "mcli stat" on cluster A does not output anything:
`mcli stat --versions tifweb-1/loki-bucket/`

7. "replicate resync" on cluster A does nothing:
`mcli replicate resync tifweb-1/loki-bucket --remote-bucket "arn:minio:replication::fabaaa52-8535-4298-a13c-de1552cd7a19:loki-bucket"`

## Context
I want to set up full replication.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-09-24T00-24-24Z
* Server setup and configuration:
* Operating System and version (`uname -a`): 4.18.0-240.1.1.el8_3.x86_64

**Comment by klauspost** [comment]
@tifling85 How long did you wait? Getting to failed replications can take hours.

**Comment by tifling85** [comment]
> @tifling85 How long did you wait? Getting to failed replications can take hours.

More than 2 days.
I also tested replication of deletion markers in a similar situation. Replication was successful.

**Comment by tifling85** [comment]
Thanks.
What release will this bugfix have?

**Comment by klauspost** [comment]
@tifling85 Next release.
