### ISSUE TITLE
Loss of metadata associated with the file extension

### ISSUE THREAD

**Issue by AdrianSeguraOrtiz** [minio/minio#13369]
When using the fput_object() function with the default content_type parameter, files uploaded to minio lack the metadata associated with the file extension. 

## Expected Behavior
It is my understanding that the default value "application/octet-stream" should automatically detect the file type and add the corresponding metadata to it, however, I suspect it does not exercise this function.

## Current Behavior
Currently, files are uploaded to minio without the metadata corresponding to their content type. This could be deduced in the minio graphical interface when the icons of files of different types are the same.

## Steps to Reproduce (for bugs)
My actual code:

```py
images = Path(folder).glob("data/*.jp2")
for image in images:
    image_name = Path(image).name.split("_", 2)[2]
    client.fput_object(
        "mybucket",
        image_name,
        image,
    )
```

## Your Environment
Python version: 3.9.6
Minio version: 6.0.2

**Comment by klauspost** [comment]
You should set the correct content type on upload. I don't know the Python details, but I seems like it would be something like

```
images = Path(folder).glob("data/*.jp2")
for image in images:
    image_name = Path(image).name.split("_", 2)[2]
    client.fput_object(
        "mybucket",
        image_name,
        image,
        content_type="image/jp2",
    )
```

**Comment by harshavardhana** [comment]
> You should set the correct content type on upload. I don't know the Python details, but I seems like it would be something like
> 
> ```
> images = Path(folder).glob("data/*.jp2")
> for image in images:
>     image_name = Path(image).name.split("_", 2)[2]
>     client.fput_object(
>         "mybucket",
>         image_name,
>         image,
>         content_type="image/jp2",
>     )
> ```

Closing.
