### ISSUE TITLE
POST request for STS credentials is not working

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13367]
HI Team,

I have configured the LDAP through env variables on tenant .my default login id blocked.Minio console blocked all logins. after LDAP configuration done.

but when i am running POST request command with ldap user. I am not getting the STS details.

-bash-4.2$ POST https://172.x.x.x:30003?
Auction=AssumeRoleWithLDAPIdentity&LDAPUsername=euserh&LDAPPassword=Pwd@2019&Version=2011-06-15&DurationSeconds=7200
[17] 26506
[18] 26507
[19] 26508
[20] 26519
[18]   Done                    LDAPUsername=euserh
-bash-4.2$ Please enter content (application/x-www-form-urlencoded) to be POSTed:
![ldap_minio](https://user-images.githubusercontent.com/68953135/136162930-af2bcab6-a9f3-438e-85ac-6f5fe2c0f079.png)
![image](https://user-images.githubusercontent.com/68953135/136163654-6e8374f2-d2cf-4a25-84f9-e114723ee941.png)

**Comment by harshavardhana** [comment]
@Bhagi33 you need to put quotes doing `curl -X POST "..."`

**Comment by Bhagi33** [comment]
Hi Harsh,
I checked with curl command its not working. here x.x.x.x(LB IP of Tenant minio cluster service IP):30003. You can see attached screen shot.

-bash-4.2$ curl -k POST "https://x.x.x.x:30003?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=xxxxx&LDAPPassword=xxxxxxxx&Version=2011-06-15&DurationSeconds=7200&policy=consoleAdmin"
curl: (6) Could not resolve host: POST; Unknown error
curl: (3) [globbing] illegal character in range specification at pos 108

#####################
 curl -k --globoff POST "https://x.x.x.x:30003?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=egmoanh&LDAPPassword=xxxxxx&Version=2011-06-15"
curl: (6) Could not resolve host: POST; Unknown error
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>16ABA7685C22B0BE</RequestId><HostId>247a975d-85d3-4071-b72d-93becebd462c</HostId></Error>-bash-4.2$

Note:https://x.x.x.x:30003=MInio cluster service and its port
##########################


![image](https://user-images.githubusercontent.com/68953135/136323204-b663f1a0-419e-4230-ace4-e5e098ca185d.png)

**Comment by harshavardhana** [comment]
> -bash-4.2$ curl -k POST "https://x.x.x.x:30003?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=xxxxx&LDAPPassword=xxxxxxxx&Version=2011-06-15&DurationSeconds=7200&policy=consoleAdmin"

Correct command 

> curl -k -X POST "https://x.x.x.x:30003?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=xxxxx&LDAPPassword=xxxxxxxx&Version=2011-06-15&DurationSeconds=7200"

**Comment by Bhagi33** [comment]
Hi Harsh,
Please find this output
 curl -k -X POST "https://x.x.x.x:30003?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=xxxxxx&LDAPPassword=xxxxxx&Version=2011-06-15"
curl: (3) [globbing] illegal character in range specification at pos 108

**Comment by harshavardhana** [comment]
> curl: (3) [globbing] illegal character in range specification at pos 108

Please your curl looks like it's broken.

**Comment by Bhagi33** [comment]
the previous error it has ocurred due to password contained [, now i changed my password and tried..
but some how able to see out put in xml format... but error is coming..

not sure about that error.. can you ple look into this.

-bash-4.2$ curl -k -X POST "https://xxxxxx:30003?Auction=AssumeRoleWithLDAPIdentity&LDAPUsername=umbahar&LDAPPassword=passwd@123&Version=2011-06-15"
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BadRequest</Code><Message>An error occurred when parsing the HTTP request POST at &#39;/&#39;</Message><Resource>/</Resource><RequestId></RequestId><HostId>247a975d-85d3-4071-b72d-93becebd462c</HostId></Error>-bash-4.2$
![image](https://user-images.githubusercontent.com/68953135/136328789-83b6243a-87b8-4d6a-85c8-a96d695b2099.png)

**Comment by harshavardhana** [comment]
Its not Auction -> Action

**Comment by Bhagi33** [comment]
Hi Harsh,

Due to k8s cluster issue, yesterday i coudnot test STS service for LDAP user.
Today when i tested with ldap  user, i had set existing policy to user .but still its asking for the policy.

Please let me know, do we need to create new IAM policy??
why existing policy is not accepting.

[euserh@serverk8s ~]$ ./mc admin policy list test --insecure
writeonly
consoleAdmin
diagnostics
readonly
readwrite

#############################################
[euserh@serverk8s ~]$ ./mc admin user list test --insecure
enabled    8RP994JOGQ78GNPEY57V  consoleAdmin
enabled    uid=euserh,cn=NS...  writeonly

#############################
[euserh@serverk8s~]$ curl -k -X POST "https://x.x.x.x:30009?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=euserh&LDAPPassword=Pwd@123&Version=2011-06-15&policy=writeonly"
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>expecting a policy to be set for user `CN=euserh,OU=CA,OU=User,OU=P0licy,OU=ID,OU=comman,DC=example,DC=net` or one of their groups: `` - rejecting this request</Message></Error><RequestId>16AC132F1DE3429B</RequestId></ErrorResponse>[euserh@serverk8s ~]$

**Comment by Bhagi33** [comment]
Hi Harsh,

I created new polices and applied to the LDAP user "euser" and also applied the same policy to group as well. But still error is throwing saying that Policy to be set for the user.
Please guide and support to solve this.

[euser@server1 ~]$ curl -k -X POST "https://x.x.x.x:30009?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=euser&LDAPPassword=passwd@123&Version=2011-06-15&policy=allaccess"
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>expecting a policy to be set for user `cn=developuser,ou=BA,ou=account,ou=P1,ou=ID,ou=Data,dc=example,dc=net` or one of their groups: `` - rejecting this request</Message></Error><RequestId>16ACA6F5488C1A99</RequestId></ErrorResponse>[euser@server1 ~]$
[euser@server1 ~]$ ./mc admin user list test --insecure
enabled    uid=euser,cn=NS...  allacess
enabled    uid=johnch,cn=NS...  mypolicy
[euser@server1 ~]$ ./mc admin policy list test --insecure                                                                          readwrite
writeonly
consoleAdmin
diagnostics
mypolicy
newwrite
readonly
allacess
[euser@server1 ~]$ ./mc admin group list test --insecure
cn=developuser,ou=BA,ou=account,ou=P1,ou=ID,ou=Data,dc=example,dc=net

[euser@server1 ~]$
./mc admin policy info test allaccess --insecure
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "admin:*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:*"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
