### ISSUE TITLE
Client complaints about content hash mismatch but the object is OK in MinIO

### ISSUE THREAD

**Issue by to-ny** [minio/minio#13376]
## Expected Behavior
We are fetching objects from MinIO using the AWS S3 Java SDK:

```java
var request = new GetObjectRequest(bucketName, key);
return amazonS3.getObject(request).getObjectContent();
```

We expect to receive the content of the object.

## Current Behavior
The client throws the following exception while trying to read the input stream:

```
Exception: com.amazonaws.SdkClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt.
	at com.amazonaws.services.s3.internal.DigestValidationInputStream.validateMD5Digest(DigestValidationInputStream.java:79)
	at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:61)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:166)
	(...)
```

When we check the file itself or its content with `mc`, everything seems OK.

## Possible Solution
The only idea we have would be to force MinIO to re-calculate the hash of the files. We didn't find such a procedure in the documentation. 
We didn't find much information online for a possible solution and we are more than open if you have suggestions on how to resolve this. It looks like disabling the client's hash verification would be a bad idea.

## Steps to Reproduce (for bugs)
It's hard to reproduce since it's related to our specific objects and, as it looks, their compromised content hash.

## Context
2 weeks ago our underlying storage system had a major problem. We were able to restore all the files and we performed `mc heal` on all documents to verify there were no more orange or red blocks.

## Regression
N/A

## Your Environment
* Version used (`minio --version`): minio/minio:RELEASE.2021-09-23T04-46-24Z
* Server setup and configuration: 4 instances deployed on Docker Swarm
* Operating System and version (`uname -a`): N/A

Thanks for your help

**Comment by klauspost** [comment]
@to-ny We don't do community debugging on such old versions. 

You can upgrade to latest version of minio/mc. If it still displays the issue run `mc admin inspect myminio/mybucket/pathtoobject/**`. Send the file+displayed key here if the file isn't confidential. If it is, send the key to `klaus@minio.io` and I can take a look.

**Comment by klauspost** [comment]
(You can upload the file to out playground using `mc mb play/brokenfile&&mc cp inspect.xxxxxxxxx.enc play/brokenfile/` replace file name with the correct one)

**Comment by to-ny** [comment]
Thank you for your help @klauspost.

I cannot explain it but upgrading MinIO to the latest version resolved our issue.

**Comment by to-ny** [comment]
Unfortunately, after a day, the problem came back for some files.

@klauspost I followed your procedure to upload one of the corrupted files:
```sh
sh-4.4# mc mb play/brokenfile && mc cp inspect.93642440.enc play/brokenfile/ 
Bucket created successfully `play/brokenfile`.
inspect.93642440.enc:          38 B / 38 B 
```

I sent the key to you by email.

**Comment by to-ny** [comment]
I'm not sure the previous `mc admin inspect` was correctly performed so I'm doing it for another file to be sure:

```sh
mc: Encrypted file data successfully downloaded as inspect.0a8fba6c.enc
mc: Decryption key: 0a8fba6ce35a183c2849a1c022ae762eb571a44900e048a05865dca45cb358b8a07d80a0
```

```sh
sh-4.4# mc cp inspect.0a8fba6c.enc play/brokenfile/ 
inspect.0a8fba6c.enc:          38 B / 38 B
```
Now I'm able to see the binary content through `mc cat` but when I try to open the file, it says it is corrupted... I'm afraid the content of the files is damaged as well.

**Comment by klauspost** [comment]
@to-ny 38 bytes means nothing was found. Check that you are using the correct object path and add `/**`.

If `mc cat` cannot retrieve it, it sounds like it was corrupted.

**Comment by to-ny** [comment]
Hi @klauspost, thanks for your quick reply. I'm surprised the inspect file is always empty, the file is present and not empty, as you can see below:

```sh
sh-4.4# mc ls prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text   
[2021-09-20 11:29:54 UTC]  20KiB 2238740-2238744-application-vnd.oasis.opendocument.text

sh-4.4# mc admin inspect prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text/**
mc: Encrypted file data successfully downloaded as inspect.878fd0f8.enc
mc: Decryption key: 878fd0f8c90756f224159640140f611e3053b71db7dc5424f40571a266edd5116197b285

sh-4.4# mc cp inspect.878fd0f8.enc play/brokenfile/ 
inspect.878fd0f8.enc:          38 B / 38 B
```

I can see the bytes with `mc cat` command but when I try to visualize the document after `mc cp` it, it's corrupted indeed... So I'm afraid it's on our side

**Comment by klauspost** [comment]
Are you sure you are on the latest version?

Testing in your uploaded file on play:

```
λ mc admin inspect play/brokenfile/inspect.878fd0f8.enc/**
mc: Encrypted file data successfully downloaded as inspect.5ed94fd3.enc
mc: Decryption key: 5ed94fd337b492d05b30eea5f6b2e18038f05cd69c8c2170cd1f61040a0757326399da99

mc: The decryption key will ONLY be shown here. It cannot be recovered.
mc: The encrypted file can safely be shared without the decryption key.
mc: Even with the decryption key, data stored with encryption cannot be accessed.
```

Either way, `mc admin inspect prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta` should be enough information to get started.

**Comment by to-ny** [comment]
Hi @klauspost, 

We are now using version`RELEASE.2021-06-14T01-29-23Z`.

**Comment by klauspost** [comment]
@to-ny ok. That doesn't version doesn't accept wildcards for mc inspect. See my previous msg.

**Comment by harshavardhana** [comment]
> We are now using version`RELEASE.2021-06-14T01-29-23Z`.

That is not latest @to-ny please use latest and share the results that @klauspost asked here.

**Comment by to-ny** [comment]
@klauspost , @harshavardhana I'm sorry about the typo, the version I'm using is `minio/minio:RELEASE.2021-09-23T04-46-24Z`.
I made a mistake and mixed the previous/new version while posting here.
Thanks for your help.

**Comment by harshavardhana** [comment]
> 2 weeks ago our underlying storage system had a major problem. We were able to restore all the files and we performed `mc heal` on all documents to verify there were no more orange or red blocks.

when you ran `mc admin heal` did you run it with `--scan=deep` ? 

Also, can you share

```
~ mc stat alias/bucketname/object
```

```
~ mc cat alias/bucketname/object | md5sum
```

Output?

**Comment by to-ny** [comment]
I think we ran the `heal` operation multiple times, with a deeper scan too. To be sure, I ran it again this morning with the following result:

```sh
sh-4.4# mc admin heal prod/something-prod -r --scan deep
 ◑  something-prod/2285044-2285050-application-pdf
    0/44,047 objects; 19 GiB in 10m44s
    ┌────────┬────────┬─────────────────────┐
    │ Green  │ 44,050 │ 100.0% ████████████ │
    │ Yellow │      0 │   0.0%              │
    │ Red    │      0 │   0.0%              │
    │ Grey   │      0 │   0.0%              │
    └────────┴────────┴─────────────────────┘
```

And here's the output of the commands you sent:

```sh
sh-4.4# mc stat prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text
Name      : 2238740-2238744-application-vnd.oasis.opendocument.text
Date      : 2021-09-20 11:29:54 UTC 
Size      : 20 KiB 
ETag      : 5ed4e014663e0a8b386ab9913548e5e2 
VersionID : 0d4faa9e-4958-407c-bded-1dd6d4736721 
Type      : file 
Metadata  :
  Content-Type: application/vnd.oasis.opendocument.text 

sh-4.4# mc cat prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text | md5sum
9e25658f3d8db25754e065f725417e95  -
```

I guess the ETag and the md5sum output should be the same and this is why the client's md5 verification is failing?

**Comment by harshavardhana** [comment]
> I guess the ETag and the md5sum output should be the same and this is why the client's md5 verification is failing?

correct are there any messages related to this object name on the server logs?

**Comment by to-ny** [comment]
Unfortunately, I don't see any mention of the object in `mc admin console`

**Comment by harshavardhana** [comment]
> Unfortunately, I don't see any mention of the object in `mc admin console`

Don't use that command - look for it more deeply @to-ny login to the servers

**Comment by to-ny** [comment]
Well, I checked in the logs of the Docker containers too, but I see the same logs. Is there another place I should check?

**Comment by harshavardhana** [comment]
> Well, I checked in the logs of the Docker containers too, but I see the same logs. Is there another place I should check?

@to-ny 

> mc cat prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text > oodc.text

is this file readable?

**Comment by to-ny** [comment]
No, it says the file is corrupted... I guess MinIO can't help in this regard

**Comment by harshavardhana** [comment]
> No, it says the file is corrupted... I guess MinIO can't help in this regard

did you replace the drives, swap the drives in some fashion? @to-ny

**Comment by harshavardhana** [comment]
> 2 weeks ago our underlying storage system had a major problem. We were able to restore all the files and we performed `mc heal` on all documents to verify there were no more orange or red blocks.

what did you do to restore? if you swapped drives and changed position it won't work really.

**Comment by to-ny** [comment]
Our underlying storage system had a problem and we had to move the whole storage to a new "location".

Pratically speaking, we stopped the Docker instances, updated the mounted volumes to a new location and restarted the instances. The content of the volumes didn't change and wasn't swap.

**Comment by harshavardhana** [comment]
> Our underlying storage system had a problem and we had to move the whole storage to a new "location".
> 

This process has screwed something up, AFAICS - how many drives do you have per server? and how much of content? 

> Pratically speaking, we stopped the Docker instances, updated the mounted volumes to a new location and restarted the instances. The content of the volumes didn't change and wasn't swap.

Yeah it may look that way, it doesn't look like that's what happened.

**Comment by harshavardhana** [comment]
Can you upgrade to the latest release and provide what @klauspost asked in the beginning by using the glob to give us the entire content from the disks so that we can try to reconstruct it. 

We can see if the drive order has been messed up etc.

**Comment by to-ny** [comment]
Oh yes, I'm sorry I forgot to run the command again with the suffix `/xl.meta`

Here's the output:

```sh
sh-4.4# mc admin inspect prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta 
mc: Encrypted file data successfully downloaded as inspect.6aeebe88.enc
mc: Decryption key: 6aeebe88107a1606a95d2c981dad8ae04551da694b685938d96d5b3de9f042f6058caace

sh-4.4# mc mb play/brokenfile && mc cp inspect.6aeebe88.enc play/brokenfile  
Bucket created successfully `play/brokenfile`.
inspect.6aeebe88.enc:               2.83 KiB / 2.83 KiB
```

Thank you for your help

**Comment by harshavardhana** [comment]
> ```shell
> sh-4.4# mc admin inspect prod/something-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta 
> ```

Can you add the `glob` support i.e get the `part` files as well?

**Comment by to-ny** [comment]
I'm sorry I don't see any documentation on this `glob` feature, what command should I type to obtain this?

**Comment by klauspost** [comment]
@to-ny That would be `/**` instead of `/xl.meta` available on the most recent releases.

**Comment by klauspost** [comment]
Just to confirm the metadata looks fine:
```
λ mc cat play/brokenfile/inspect.6aeebe88.enc|inspect --key=6aeebe88107a1606a95d2c981dad8ae04551da694b685938d96d5b3de9f042f6058caace >inspect.zip&&xl-meta inspect.zip 
{
	"minio1:9000/21656abe-4b24-430e-8c02-6e5b6378040c/espacio-documents-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta": {"Versions":[{"Type":1,"V2Obj":{"ID":"DU+qnklYQHy97R3W1HNnIQ==","DDir":"C+zI0FWjSh2r6FF8mTYIEQ==","EcAlgo":1,"EcM":2,"EcN":2,"EcBSize":10485760,"EcIndex":3,"EcDist":[3,4,1,2],"CSumAlgo":1,"PartNums":[1],"PartETags":[""],"PartSizes":[20931],"PartASizes":[20931],"Size":20931,"MTime":1632137394908547760,"MetaSys":{},"MetaUsr":{"content-type":"application/vnd.oasis.opendocument.text","etag":"5ed4e014663e0a8b386ab9913548e5e2"}}}]},
	"minio2:9000/cae453a2-70a5-4261-bdf4-7f5b517df090/espacio-documents-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta": {"Versions":[{"Type":1,"V2Obj":{"ID":"DU+qnklYQHy97R3W1HNnIQ==","DDir":"C+zI0FWjSh2r6FF8mTYIEQ==","EcAlgo":1,"EcM":2,"EcN":2,"EcBSize":10485760,"EcIndex":4,"EcDist":[3,4,1,2],"CSumAlgo":1,"PartNums":[1],"PartETags":[""],"PartSizes":[20931],"PartASizes":[20931],"Size":20931,"MTime":1632137394908547760,"MetaSys":{},"MetaUsr":{"etag":"5ed4e014663e0a8b386ab9913548e5e2","content-type":"application/vnd.oasis.opendocument.text"}}}]},
	"minio3:9000/bf138f27-2843-4837-a3c1-72d84ee9cdbf/espacio-documents-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta": {"Versions":[{"Type":1,"V2Obj":{"ID":"DU+qnklYQHy97R3W1HNnIQ==","DDir":"C+zI0FWjSh2r6FF8mTYIEQ==","EcAlgo":1,"EcM":2,"EcN":2,"EcBSize":10485760,"EcIndex":1,"EcDist":[3,4,1,2],"CSumAlgo":1,"PartNums":[1],"PartETags":[""],"PartSizes":[20931],"PartASizes":[20931],"Size":20931,"MTime":1632137394908547760,"MetaSys":{},"MetaUsr":{"content-type":"application/vnd.oasis.opendocument.text","etag":"5ed4e014663e0a8b386ab9913548e5e2"}}}]},
	"minio4:9000/0e7649f8-f1b9-4aba-97c4-ceade15274fe/espacio-documents-prod/2238740-2238744-application-vnd.oasis.opendocument.text/xl.meta": {"Versions":[{"Type":1,"V2Obj":{"ID":"DU+qnklYQHy97R3W1HNnIQ==","DDir":"C+zI0FWjSh2r6FF8mTYIEQ==","EcAlgo":1,"EcM":2,"EcN":2,"EcBSize":10485760,"EcIndex":2,"EcDist":[3,4,1,2],"CSumAlgo":1,"PartNums":[1],"PartETags":[""],"PartSizes":[20931],"PartASizes":[20931],"Size":20931,"MTime":1632137394908547760,"MetaSys":{},"MetaUsr":{"etag":"5ed4e014663e0a8b386ab9913548e5e2","content-type":"application/vnd.oasis.opendocument.text"}}}]}
}
```

**Comment by to-ny** [comment]
Indeed, it seems the objects are fine, as the `heal` output suggests... At this point, our best clue is to retrieve a former backup of the objects and restore the corrupted ones. Unfortunately, the backup isn't done through MinIO and we will have to find a way to make this process properly.

I'm not sure you guys can do much more, as you already took much time and effort to help us figure out the potential cause/solution.

In any case, thanks a lot for your support @klauspost & @harshavardhana. If you don't see anything else to add, we can close this issue.

**Comment by klauspost** [comment]
ok, closing for now.
