### ISSUE TITLE
[gateway] Files encrypted with KMS at gateway layer are unreadable if tampered with backend

### ISSUE THREAD

**Issue by othomas** [minio/minio#13370]
## Expected Behavior
When a file gets encrypted with Minio Gateway with KES (MINIO_KMS_AUTO_ENCRYPTION = "on"), stored to an S3 bucket, and moved to another path or moved to another bucket, we would expect this file to be decrypted and read correctly.

## Current Behavior
Unfortunately when moving a file after it has been encrypted, to another bucket with a different name, or to a different path within the same bucket, decryption of the file fails. This is annoying in case we want to implement replication rules between different regions : the files replicated in the other regions are not readable.
We reviewed the code and observed that actually bucket name and file path are used at two places:

- in the context argument when Minio asks for a new encryption key or asks to decrypt a file encryption key to KES
- in the etag used to seal the key (those 2 values are used to derive the key). file `cmd/internal/key.go` , function `func (key ObjectKey) Seal(extKey []byte, iv [32]byte, domain, bucket, object string) SealedKey`

## Possible Solution
We would like to have the possibility to use any other value to derive the key, different from bucket name and path (actually not tied to the location where the file is stored)
Or having the possiblity to disable this derivation even if it would lower security 

## Steps to Reproduce (for bugs)
Run minio in gateway mode, connected to a KES, with MINIO_KMS_AUTO_ENCRYPTION = "on"
Upload a file with mc or aws cli to a bucket A through the gateway --> File gets encrypted and stored into bucket A
Copy or move the file from Bucket A to Bucket B, without going through the minio gateway 
Try to read the encrypted file from the bucket B through the gateway, with mc or aws cli
Result: HTTP 500 error or HTTP 503 Access Denied error (depending if the error is raised by the context arg issue , or the unsealing)

## Context
Trying to replicate files encrypted with a KES through minio Gateway and upload to a bucket , to another AWS region, using AWS replication rules. This replication rule is part of a disaster recovery strategy.

## Regression
It doesn't seem to be a regression as using bucket name / path to derive the keys increase security. However it doesn't seem to be documented anywhere as a limitation in the doc, that's why it could be considered as an issue.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-09-24T00-24-24Z, and also latest
* Server setup and configuration: Minio in gateway mode, connected to a KMS
* Operating System and version (`uname -a`): Darwin MacBook-Pro-2.local 20.3.0 Darwin Kernel Version 20.3.0

**Comment by harshavardhana** [comment]
> Run minio in gateway mode, connected to a KES, with MINIO_KMS_AUTO_ENCRYPTION = "on" Upload a file with mc or aws cli to a bucket A through the gateway --> File gets encrypted and stored into bucket A Copy or move the file from Bucket A to Bucket B, without going through the minio gateway Try to read the encrypted file from the bucket B through the gateway, with mc or aws cli Result: HTTP 500 error or HTTP 503 Access Denied error (depending if the error is raised by the context arg issue , or the unsealing)

Doing a backend move without going through a gateway - while also enabling encryption is something that we cannot support. 

Gateway once used should always be used you cannot tamper the backend which is what you did. Tampering is not allowed and won't be supported.
