### ISSUE TITLE
add support for config.env in chart

### ISSUE THREAD

**Issue by jr0dd** [minio/minio#13374]
I was curious if this is something you would approve @harshavardhana? I can always work up a pr to add config.env as a secret volume mount in the chart. I'm currently using kustomize to patch, but figured others may also get a use out of it if included.

**Comment by harshavardhana** [comment]
> I was curious if this is something you would approve @harshavardhana? I can always work up a pr to add config.env as a secret volume mount in the chart. I'm currently using kustomize to patch, but figured others may also get a use out of it if included.

Sure @jr0dd that is possible

**Comment by jr0dd** [comment]
> > I was curious if this is something you would approve @harshavardhana? I can always work up a pr to add config.env as a secret volume mount in the chart. I'm currently using kustomize to patch, but figured others may also get a use out of it if included.
> 
> 
> 
> Sure @jr0dd that is possible

Alright. I'll work something up in the next couple days.
