### ISSUE TITLE
Log disk UUID when finding disk in unexpected location

### ISSUE THREAD

**Issue by neumantm** [minio/minio#13394]
**Is your feature request related to a problem? Please describe.**
I've deployed minio on Kubernetes using the operator.
I'm using manually created `local` PersistantVolumes as described in https://docs.min.io/minio/k8s/tenant-management/deploy-minio-tenant.html#id5.
I've just encountered the new error `found a disk in an unexpected location` (introduced by https://github.com/minio/minio/pull/13326/).
I probably mixed up the binding between the PVs and the PVCs at some point (recreating the tenant or something).
Now I find it very confusing and cumbersome to identify which of the bindings need to be changed how.

**Describe the solution you'd like**
It would already help a bit if the disk UUID would be added to the log as I can lookup the disk id of a disk in the filesystem (inspecting `.minio.sys/format.json`) but not the expected location.

**Comment by harshavardhana** [comment]
@neumantm this is already fixed in 

```
commit 0c48b1d993d5623896a321a24713c326e63d7947
Author: Harshavardhana <harsha@minio.io>
Date:   Fri Oct 8 11:37:19 2021 -0700

    fix: benchmarking test initialization
    
    > go test -run=none -bench=Benchmark github.com/minio/minio/cmd
    
    Runs now without any crashes.
    
    fixes #13380
```
