### ISSUE TITLE
bucket name does not match

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#13395]
## Current Behavior

Bucketname not match occurs occasionally during bucket building
![image](https://user-images.githubusercontent.com/27141040/136653910-e1e72e3a-92ae-4d8c-b2f9-5225c742e6b1.png)

## Steps to Reproduce (for bugs)
here is my code 
if (!client.bucketExists(BucketExistsArgs.builder().bucket(bucketName).build())) {
            client.makeBucket(MakeBucketArgs.builder().bucket(bucketName).build());
            setBucketPolicy(bucketName, READ_WRITE);
            //            client.setBucketPolicy(minioProp.getBucketName(), "*.*", PolicyType.READ_ONLY);
        }

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2021-10-08T23-58-24Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
* Linux hadoop003 3.10.0-957.el7.x86_64 minio/minio#1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> As per the trace, the server is returning S3 error. Nothing can be done at client side. Please enable `MinioClient.traceOn()` and open respective issue at server side with the output.

@kendn1993 please share this output here

**Comment by harshavardhana** [comment]
I check the server code there is no place where the server would return "bucket name does not match"
