### ISSUE TITLE
crossdomain.xml vulnerability 

### ISSUE THREAD

**Issue by liyehaha** [minio/minio#13401]
crossdomain.xml vulnerability 
https://www.acunetix.com/vulnerabilities/web/insecure-crossdomain-xml-file/

## Expected Behavior
cross domain policy should be editable by users

## Current Behavior
hard coding

## Possible Solution
it can be mounted before started

**Comment by harshavardhana** [comment]
Our crossdomain.xml mimics AWS S3 crossdomain.xml 

It is not meant to be configurable.

**Comment by exe-r** [comment]
Sorry for bringing this up again @harshavardhana, I understand that it aligns with S3 crossdomain.xml but what's the downside of having this configurable for other use cases? This is still reported as a vulnerability, in some cases domain=* might be restricted to prevent this?
