### ISSUE TITLE
Download all as zip not functioning

### ISSUE THREAD

**Issue by jessezondervan** [minio/minio#13408]
## Expected Behavior
I clicked a few files in the opentopography database (https://opentopography.s3.sdsc.edu/minio/dataspace/OTDS.012020.4326.1/raster/slope/), after which a zip folder should start downloading.

## Current Behavior
Nothing happens.

## Steps to Reproduce (for bugs)
Access this link in any of the following browsers which I tried (Brave, Microsoft Edge, Firefox) and try to download any three files:
https://opentopography.s3.sdsc.edu/minio/dataspace/OTDS.012020.4326.1/raster/slope/

## Your Environment

Online on a Windows 10 machine via the browsers detailed above.

**Comment by klauspost** [comment]
This functionality removed in current versions. We do not provide community support for older versions.
