### ISSUE TITLE
Upgrading Minio cluster tenant -- Not applying the changes to the pods

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13419]
Hi Team,

I upgraded my minio tenant cluster via Helm and also with " kubectl minio tenant upgrade minio --image docker.io/minio/minio:RELEASE.2021-10-08T23-58-24Z --namespace ldap-minio".

kubectl minio tenant info minio -n test-minio
But Tenant status is showing status as "Updating Tenant Version".  There is no change in pod(like rolling upgrades/pod restarts).
I am able to see updated Version of image in Tenant but not in pods.

My minio Operator version:minio/operator:v4.2.8
Minio Tenant old version Image:  minio/minio:RELEASE.2021-09-24T00-24-24Z  
upgraded minio version: docker.io/minio/minio:RELEASE.2021-10-08T23-58-24Z

Please let us know, how this upgrade happens in Minio Operator environment Tenant and its pods.

Why rolling upgrade is not happening.

**Comment by harshavardhana** [comment]
Not related to MinIO - moved the original issue to operator https://github.com/minio/operator/issues/866
