### ISSUE TITLE
Bitrot healing does not work for part.x files

### ISSUE THREAD

**Issue by stgrosshh** [minio/minio#13423]
In latest minio release 2021-10-10 bitrot seems not to be healed when occurring in part.x files on MacOS, in a 4 drive setup.

## Expected Behavior

Bitrot should be corrected in part.x file
## Current Behavior

Swapped Bytes are detected as bitrot in log and healing is attempted but not executed:

Error: Disk: /Users/xx/data/minio/1  -> erasure-test/training.pdf/c2019552-6981-4851-817a-2ae006e6f1aa/part.1 - content hash does not match - expected e0b26fe19afb676f3e0603fd350c8a39102d5fb689de82031d92fce14ed72206, got 148646b70e9db9ab486679db8e4e25ec5bdb2a00ccd57da8ffdc553200e399f5 (*errors.errorString)
       2: cmd/bitrot-streaming.go:183:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
Healing required, attempting to heal bitrot for erasure-test/a320-line-training.pdf

File content is not changed but still contains corrupted content.
## Steps to Reproduce (for bugs)

1. Startup a minio server with 4 drives like minio server 1 2 3 4 --console-address ":9999"
2. Upload a larger file (4 MB in my test)
2. edit one of the part.1 files and swap 2 characters
3. call heal from UI - no corruption is shown, no healing is displayed
4. call preview or download from UI - Log message as above is displayed in console log
5. check part.1 file content. Still contains swapped bytes and is obviously not healed

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-10-10T16-53-30Z
* Server setup and configuration: MacBook Pro, Minio server started with 4 drives (dev setup, drives emulated with local directories)
* Operating System and version (`uname -a`): MacOS BigSur Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
> * Startup a minio server with 4 drives like minio server 1 2 3 4 --console-address ":9999"
> * Upload a larger file (4 MB in my test)
> * edit one of the part.1 files and swap 2 characters
> * call heal from UI - no corruption is shown, no healing is displayed
> * call preview or download from UI - Log message as above is displayed in console log
> * check part.1 file content. Still contains swapped bytes and is obviously not healed

You need to heal using `--scan=deep`  UI might not allow this yet. - try doing `mc admin heal -r --scan=deep`

**Comment by harshavardhana** [comment]
The UI doesn't support deep scanning yet, you can enable periodic bitrot scanning using 

```
~ mc admin config set play/ heal
KEY:
heal  manage object healing frequency and bitrot verification checks

ARGS:
bitrotscan  (on|off)    perform bitrot scan on disks when checking objects during scanner
max_sleep   (duration)  maximum sleep duration between objects to slow down heal operation. eg. 2s
max_io      (int)       maximum IO requests allowed between objects to slow down heal operation. eg. 3
```

```
~ mc admin config set play/ heal bitrotscan=on
```

Or manually run `mc admin heal -r --scan=deep`

**Comment by stgrosshh** [comment]
mc admin heal -r --scan=deep  only works, if you enable  bitrotscan=on with "mc admin config set" first.
Should be documented that way.

Thanks

**Comment by harshavardhana** [comment]
> mc admin heal -r --scan=deep only works, if you enable bitrotscan=on with "mc admin config set" first. Should be documented that way.

Read `docs/config/README.md` https://github.com/minio/minio/tree/master/docs/config#healing 

Bitrot is not a daily affair set this to 'on' carefully in a production setup.

**Comment by stgrosshh** [comment]
I see, but the log message "Healing required, attempting to heal bitrot for erasure-test/a320-line-training.pdf" is puzzling then, cause healing is not performed due to the config.
