### ISSUE TITLE
helm chart 3.1.9: mc image tag doesn't exist (RELEASE.2021-10-07T04-19-58Z)

### ISSUE THREAD

**Issue by awoimbee** [minio/minio#13420]
The helm chart references tag `RELEASE.2021-10-07T04-19-58Z` of repository `quay.io/minio/mc` (https://github.com/minio/minio/blob/f5a55c44d41362c3061c94f149031869f1a82bb1/helm/minio/values.yaml#L28). But This tag doesn't exist (https://quay.io/repository/minio/mc?tag=latest&tab=tags).
The latest tag on Quay is `latest` from 5 days ago (which matches 2021-10-07) and after that it's `RELEASE.2021-09-23T05-44-03Z`.

Please add tag `RELEASE.2021-10-07T04-19-58Z` to `quay.io/minio/mc`.

EDIT:
Same issue with helm chart v3.1.8, missing tag `RELEASE.2021-10-06T23-36-31Z`
helm chart v3.1.7 & missing `RELEASE.2021-10-02T16-31-05Z`
At this point I stoped testing

**Comment by harshavardhana** [comment]
Oh my bad, will publish mc tag.

**Comment by harshavardhana** [comment]
Updated `mc` image - thanks for reminder @awoimbee
