### ISSUE TITLE
Minio Console is using docker ip for presigned-url file share. How do we tell it to use external URL?

### ISSUE THREAD

**Issue by apit** [minio/minio#13429]
My setup is using minio+nginx docker-compose example behind a proxy. Sometimes I use Minio Console Object Browser to quickly share files.

## Expected Behavior
Generated pre-signed URL should be using external domain name

## Current Behavior
Pre-signed URL is using container IP and I can't find a way to configure it to use an external URL.

## Steps to Reproduce (for bugs)

Use Minio Console's Object Browser to share files. Generated URL is like http://172.26.0.5:9000/messaging/config/channel-config.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6Zxx which can't be used outside host machine.

## Your Environment
Docker setup, similar to https://docs.min.io/docs/deploy-minio-on-docker-compose
Image: quay.io/minio/minio:RELEASE.2021-09-09T21-37-07Z
OS: Ubuntu

**Comment by harshavardhana** [comment]
Did you read https://github.com/minio/minio#test-using-minio-console?

**Comment by apit** [comment]
Sorry. Apparently, I read legacy docs and skipped this repo README. The information I need here is on the[ upcoming docs](https://docs.min.io/minio/baremetal/console/minio-console.html) too. Great job on the new docs site btw, seems clear and structured better.
