### ISSUE TITLE
`endpoint` does not allow `path`

### ISSUE THREAD

**Issue by lshz0088** [minio/minio#13437]
**Is your feature request related to a problem? Please describe.**

When I use the `Java SDK`, in the construction method of `MinioClient`, I find that `endpoint` does not allow `path`. As shown in the following source code.

Then, if my `Minio service` is deployed after nginx and uses' location 'for proxy, for example, my full URL should be like this` http://a.b.com/file/minio/login `, there is one more layer of 'file', so how should I configure it?

```java
if (!"/".equals(url.encodedPath())) {
    throw new InvalidEndpointException(endpoint, "no path allowed in endpoint");
}
```

**Describe the solution you'd like**

Can I cancel this restriction?

**Comment by harshavardhana** [comment]
> Can I cancel this restriction?

No you cannot - hosting S3 APIs other `/` is not allowed.
