### ISSUE TITLE
Impossible to rotate root credentials

### ISSUE THREAD

**Issue by tcpdump9** [minio/minio#13447]
In current release RELEASE.2021-06-17T00-10-46Z and later looks impossible to rotate root user credentials. 
## Expected Behaviour
After changing MINIO_ROOT_USER and MINIO_ROOT_PASSWORD container start successfully, root is able to log in with new credentials

## Current Behaviour
After starting a container with updated ENV variables it fails with 
"ERROR Unable to initialize gateway backend: The access key ID you provided does not exist in our records."

## Possible Solution
There was similar request https://github.com/minio/minio/issues/10911 but looks like page it linked https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials where edited.

**Comment by vadmeste** [comment]
@tcpdump9 What gateway is this ?

**Comment by tcpdump9** [comment]
@vadmeste In our case the only thing we are using is ceph radosgw

**Comment by vadmeste** [comment]
Can you paste all environment variables that you are passing to gateways? You can redact sensitive information.

**Comment by harshavardhana** [comment]
> @vadmeste In our case the only thing we are using is ceph radosgw

If you want MinIO to not use the same credential to your backend service you need to make sure that you set AWS_ACCESS_KEY_ID to use a separate credential to talk to backend while you can freely change your root credential. 

If you don't do that and just change root sure we have to use the same cred to talk to backend, which is invalid for the backend.

https://github.com/minio/minio/blob/master/docs/gateway/s3.md#using-binary-in-ec2 

Read how we do it with AWS S3.
