### ISSUE TITLE
minio gateway inside docker fail 

### ISSUE THREAD

**Issue by juleslagarde** [minio/minio#13444]
minio gateway inside docker fail

It's problably a misconfiguration on my part but I can't see where

 `http: TLS handshake error from 172.17.0.3:57140: remote error: tls: bad certificate`

## Steps to Reproduce (for bugs)

replace HOST_IP by your own ip

1. `cd /ssl`
2. `certgen -ca -host HOST_IP`
3. `cp /ssl/server.crt /ssl/CAs/`  #edit added a step
3. run a s3 serveur:  `docker run -e MINIO_ROOT_USER=minio -e MINIO_ROOT_PASSWORD=miniopass -p 9002:9000 -v /ssl:/ssl minio/minio server /data --certs-dir /ssl`
4. run minio gateway: `docker run -e MINIO_ROOT_USER=minio -e MINIO_ROOT_PASSWORD=miniopass -v /ssl:/ssl -p 9000:9000 -p 9001:9001 minio/minio gateway s3 "https://HOST_IP:9002" --certs-dir /ssl --console-address ":9001"`
5. try to login: https://HOST_IP:9001
6. observe: `http: TLS handshake error from 172.17.0.3:57140: remote error: tls: bad certificate`

## Context

Just trying to run minio gateway as a s3 proxy (with TLS)

## Your Environment

* Version used (`minio --version`): RELEASE.2021-10-13T00-23-17Z
* Server setup and configuration: Centos 7.9
* Operating System and version (`uname -a`): Centos 7.9

**Comment by harshavardhana** [comment]
You need to trust certs if you are talking to untrusted backend for TLS. 

Your public certs should be present at `/ssl/CAs`

**Comment by juleslagarde** [comment]
First thanks a lot for your help

Second
I forgot a step : 
`cp /ssl/server.crt /ssl/CAs/`
Is that what you meant by saying "Your public certs should be present at /ssl/CAs" ?

Because, I still have the problem.

 My understanding is that it doesn't trust the IP of the docker container (which is normal since it's not in the certificate)
But why does it need to trust it ? I never mentioned it. (I have always used the host IP and not the docker IP)

**Comment by juleslagarde** [comment]
@harshavardhana could you reopen ? Thanks

**Comment by klauspost** [comment]
@juleslagarde This seem smore like a setup issue on your side and not a MinIO issue, so this will not be reopened.

Meanwhile see https://docs.min.io/minio/baremetal/security/encryption/transport-layer-security.html or you can ask for others with a similar setup on [community slack](https://slack.min.io/).

**Comment by juleslagarde** [comment]
I bypassed the issue using minio binary (without docker).
It works fine now

@harshavardhana @klauspost
So, if this is an issue with my configuration, it's linked with docker.
