### ISSUE TITLE
Get object inside a ZIP archive got EOF

### ISSUE THREAD

**Issue by fadeer** [minio/minio#13441]
Hi,

I'm trying to use S3 ZIP feature, to store small files in a zip file, but download very small file in a zip always got EOF error. Error message includes:

```
We encountered an internal error, please try again.: cause(unexpected EOF)
We encountered an internal error, please try again.: cause(EOF)
```

## Steps to Reproduce

1. Create a test zip file, include file from 1 byte to 512, [smalls.zip](https://github.com/minio/minio/files/7345384/smalls.zip)
2. Download files inside zip one-by-one. File which size below 95 bytes always failed, `smalls.zip/test/small-files/50.txt`. 
3. Using minio-go library, aws js sdk v2 got same error. As exapmles in [readme](https://github.com/minio/minio/blob/master/docs/extensions/s3zip/README.md).

## Your Environment
1. Test Minio Server Version: 2021-06-17T00:10:46Z and 2021-10-13T00:23:17Z
2. minio-go library and aws js sdk v2 are latest version.

**Comment by klauspost** [comment]
~@fadeer Please share your setup.~ NM, reproed.
