### ISSUE TITLE
OIDC login returns expected element type <AssumeRoleWithWebIdentityResponse> but have <html>

### ISSUE THREAD

**Issue by alborotogarcia** [minio/minio#13451]
Always get redirected back to console login screen after a successful log in with OIDC.

## Current Behavior

Having following the docs for [keycloak](https://github.com/minio/minio/blob/master/docs/sts/keycloak.md) setting policy to readwrite, and validating that it gets returned with 
```
curl --data "grant_type=password&client_id=minio&client_secret=xxxxxxx&username=xxxxxx&password=xxxxxx" https://authserver/auth/realms/myrealm/protocol/openid-connect/token
```

I get the following:

```
original error -> (user_login.go:64: invalid Login)
debugging error: expected element type <AssumeRoleWithWebIdentityResponse> but have <html>
```

I found that the solution works for the legacy helm chart image **minio/minio:RELEASE.2021-02-14T04-01-33Z,** and setting Implicit Flow. But I can't make it work on any other later releases.

## Steps to Reproduce (for bugs)

The following environment was set for the minio deployment:
```
            - name: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
            - name: MINIO_IDENTITY_OPENID_CONFIG_URL
              value: "https://authserver/auth/realms/realm/.well-known/openid-configuration"
            - name: MINIO_OPERATOR_TLS_ENABLE
              value: "off"
            - name: MINIO_IDENTITY_OPENID_CLIENT_ID
              value: minio
            - name: CONSOLE_PORT
              value: "9090"
            - name: MINIO_IDENTITY_OPENID_SCOPES
              value: "openid,profile,email"
            - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
              value: "policy"
            - name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
              value: "on"
            - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
              value: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
            - name: MINIO_SERVER_URL
              value: "http://minio.mydomain"
            - name: MINIO_DOMAIN
              value: "minio.mydomain"
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "http://minio.mydomain"
            - name: _MINIO_SERVER_DEBUG
              value: "on"
```
* Server setup and configuration:
k3s cluster, traefik ingress.
* Operating System and version (`uname -a`):
Ubuntu 20.04

## Context

I am pursuing to deploy minio with OIDC support on k3s.

## Your Environment

* Version used (`minio --version`):
RELEASE.2021-07-30T00-02-00Z and later.

**Comment by harshavardhana** [comment]
>             - name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
>               value: "on"

Why do you have this on? - this is not necessary this is only useful if you are using gitlab like OIDC's which do not support extra claims without reaching out on an ad-hoc call. 

You shouldn't be necessary to do this at all. 

>             - name: MINIO_SERVER_URL
>               value: "http://minio.mydomain"
>             - name: MINIO_DOMAIN
>               value: "minio.mydomain"
>             - name: MINIO_BROWSER_REDIRECT_URL
>               value: "http://minio.mydomain"

Your browser and server cannot redirect to same URL both needs to be different be on a different port. 

There are tons of mistakes here and none of them looks like you followed our docs properly.  Moving this to a discussion.
