### ISSUE TITLE
After MinIO disk failure and back to online, disk usage always increasing

### ISSUE THREAD

**Issue by waem14** [minio/minio#13467]
## Expected Behavior

We have setup MinIO distribution.  6 disks on each servers. One of them failed. We have formatted and make it back to online. 
After it back to online, objects on all disks should be healed properly.

## Current Behavior

 
After it back to online, disk usage keep increasing when comparing with other disks as you could see in purple line. 

<a href="https://ibb.co/hW8rZ1m"><img src="https://i.ibb.co/HzgRxpH/Screen-Shot-2564-10-19-at-09-26-57.png" alt="Screen-Shot-2564-10-19-at-09-26-57" border="0"></a>

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
* 
minio version RELEASE.2021-09-03T03-56-13Z

Linux sg-bimin-6z01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> ## Expected Behavior
> We have setup MinIO distribution. 6 disks on each servers. One of them failed. We have formatted and make it back to online. After it back to online, objects on all disks should be healed properly.
> 
> ## Current Behavior
> After it back to online, disk usage keep increasing when comparing with other disks as you could see in purple line.
> 
> [![Screen-Shot-2564-10-19-at-09-26-57](https://camo.githubusercontent.com/53bbc079ccf3d18731b513110572586688174e238d14f6d877d8bf9e94caa536/68747470733a2f2f692e6962622e636f2f487a67527870482f53637265656e2d53686f742d323536342d31302d31392d61742d30392d32362d35372e706e67)](https://ibb.co/hW8rZ1m)
> 
> ## Possible Solution
> ## Steps to Reproduce (for bugs)
> 
> ## Context
> ## Regression
> ## Your Environment
> * Version used (`minio --version`):
> * Server setup and configuration:
> * Operating System and version (`uname -a`):
> 
> minio version RELEASE.2021-09-03T03-56-13Z
> 
> Linux sg-bimin-6z01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

To help us you need to provide more information @waem14 

Please share server logs, `mc admin info` output etc and also `df -i` and `df -h` values from across nodes.

**Comment by waem14** [comment]
@harshavardhana  Today, we've upgraded MinIO to Version RELEASE.2021-10-13T00-23-17Z but it seems to me that it doesn't make disk /data03 on sgserver6z08 back to normal. Our MinIO is 8 servers (sgserver6z[01-08]). 6 disks per server


1. df -h
[minio_df-h.txt](https://github.com/minio/minio/files/7379254/minio_df-h.txt)
2. df -i
[minio_df-i.txt](https://github.com/minio/minio/files/7379293/minio_df-i.txt)
3. systemd configuration
[minio_systemd.txt](https://github.com/minio/minio/files/7379257/minio_systemd.txt)
4. MinIO log on sgserver6z08
[minio.log](https://github.com/minio/minio/files/7379270/minio.log)

**Comment by klauspost** [comment]
@waem14 More space is used, but less inodes. 

Are you sure the disk you added was formatted the same as the existing drives? I am thinking mostly about block size here.

**Comment by waem14** [comment]
@klauspost  inodes for /data03o on all servers are 750143168. They're the same but the issue occurred in /data03 on sgserver6z08 only.

**Comment by klauspost** [comment]
@waem14 I am just looking at sgserver6z08/data03. It shows ~5% used inodes compared to expected 7%, which indicates it still has less objects, but taking up more storage.

So less objects take up more space, making me suspect block size is different on the new drive.

**Comment by waem14** [comment]
@klauspost  I've run sudo blockdev --getfra /dev/sdd1 to get blocksize of /data03 for all servers. I have run below commands to check blocksize on all servers. But they got the same result. 

/dev/sdd1                   7.0T  5.4T  1.7T  77% /data03

 cat /proc/partitions |grep sdd1
   8       49 7501431808 sdd1

cat /sys/class/block/sdd1/size
15002863616

blockdev --getfra /dev/sdd1
256

**Comment by klauspost** [comment]
@waem14 It is the file system block size, not the device block size.

AFAICT for xfs it should be `sudo xfs_info /dev/vgh/root`, Could you check that?

Look for the `data     =                       bsize=4096   blocks=52428800, imaxpct=25`

**Comment by waem14** [comment]
@klauspost  Yes, they're the same for all 8 servers.
`sudo xfs_info /dev/sdd1
meta-data=/dev/sdd1              isize=512    agcount=32, agsize=58604992 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=0 spinodes=0
data     =                       bsize=4096   blocks=1875357952, imaxpct=5
         =                       sunit=64     swidth=64 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal               bsize=4096   blocks=521728, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0`

**Comment by harshavardhana** [comment]
> @klauspost Yes, they're the same for all 8 servers. `sudo xfs_info /dev/sdd1 meta-data=/dev/sdd1 isize=512 agcount=32, agsize=58604992 blks = sectsz=4096 attr=2, projid32bit=1 = crc=1 finobt=0 spinodes=0 data = bsize=4096 blocks=1875357952, imaxpct=5 = sunit=64 swidth=64 blks naming =version 2 bsize=4096 ascii-ci=0 ftype=1 log =internal bsize=4096 blocks=521728, version=2 = sectsz=4096 sunit=1 blks, lazy-count=1 realtime =none extsz=4096 blocks=0, rtextents=0`

@waem14 please share the logs from all servers.

**Comment by waem14** [comment]
@harshavardhana I cannot upload logs on github.  Please find logs in https://wetransfer.com/downloads/636190744cff8ee3d8bbafa56ab3d2f320211021124109/6bd2260597f25fe8c1fc379017a9f37720211021124159/822698

**Comment by harshavardhana** [comment]
> @harshavardhana I cannot upload logs on github. Please find logs in https://wetransfer.com/downloads/636190744cff8ee3d8bbafa56ab3d2f320211021124109/6bd2260597f25fe8c1fc379017a9f37720211021124159/822698

All the logs look clean mainly pointing to some sha256 mismatch related to vertica.

Can you run `du -sh /backend_disk/.minio.sys` and share it here?

**Comment by waem14** [comment]
@harshavardhana  We've run heal with recursive and remove option. It seems the disk usage stopped increasing and now it's similar to other disks as you could see in below graph. I've run du -h, du -i and du -sh /data03/minio/.minio.sys for all servers. It seems Inode on /data03/minio is different from others.

[df_logs.log](https://github.com/minio/minio/files/7407561/df_logs.log)

nohup /opt/minio-binaries/mc admin heal biminio_prod/vertica/ --recursive --remove > mc_eon_remove.out &
![Screen Shot 2564-10-25 at 12 01 10](https://user-images.githubusercontent.com/89503658/138642370-d4942a9a-dacd-488d-8d64-c9ab89a0907c.png)

**Comment by klauspost** [comment]
@waem14 Thanks for reporting back. Probably just temporary files then.

If you need further support look into our [subscription offers](https://min.io/pricing).

**Comment by waem14** [comment]
@klauspost  @harshavardhana thank you for your support
