### ISSUE TITLE
replication kafka events not fired

### ISSUE THREAD

**Issue by CraigGoodspeed** [minio/minio#13469]
1) Attach kafka events put,replica to a bucket. 
2) In another environment create a replication strategy to replicate documents to the bucket in step 1.
3) Upload file to bucket verify event is fired.
4) Upload file to bucket in step 3, verify replication takes place.
5) Replica event associated with kafka is not fired. 

## Expected Behavior
Event should be fired just as in step 3.

## Current Behavior
No event is fired.

## Steps to Reproduce (for bugs)
I have created a repository to reproduce this -- [here](https://github.com/CraigGoodspeed/minio_kafka_replication)

1) docker-compose up --build
2) logon to the site server localhost:9001 (user: minio pass: minio123)
3) Upload file into the configuration bucket. event is successfully fired.
4) log onto the central server -- localhost:9002 (user: minio pass: minio123)
5) upload file into the configuration bucket.
6) notice no event is fired even though the replication has already taken place.

## Context
The application i am currently busy with requires offline/online capability. The central and site will not always be connected. I would like to upload files into a configured store using the prefix and suffix option. Then when the site gets notified there is a new configuration file the application needs to  refresh according to this configuration.
## Regression
No
## Your Environment
The docker and docker compose will illustrate the issue quite clearly.

**Comment by vadmeste** [comment]
@CraigGoodspeed thanks for the report. Can you mention your MinIO server version here ?

**Comment by CraigGoodspeed** [comment]
> @CraigGoodspeed thanks for the report. Can you mention your MinIO server version here ?

Sure, its contained within the dockerfile --> FROM minio/minio:RELEASE.2021-10-13T00-23-17Z

**Comment by klauspost** [comment]
Note that replication does not fire events on the destination server. This is by design and matches AWS S3 behavior.

**Comment by CraigGoodspeed** [comment]
Hi @klauspost 

Thank you, then if I understand correctly...

The alternative is to attach an event at the source, to then perform updates from there?

so something like 

```
mc event add ALIAS/BUCKET ARN --event replica
```

Sincere apologies for wasting your time, I didn't see anything in the documentation to suggest this would be the expected behavior.

**Comment by harshavardhana** [comment]
> Note that replication does not fire events on the destination server. This is by design and matches AWS S3 behavior.

Source events are already triggered for replica events when they are successful or failure.

So this is expected behavior @CraigGoodspeed
