### ISSUE TITLE
minio fail to start

### ISSUE THREAD

**Issue by liujiaxiang** [minio/minio#13465]
version:minio version RELEASE.2020-07-02T00-15-09Z
start command:./minio server /minio_data/data1 /minio_data/data2 /minio_data/data3 /minio_data/data4
description:It was normal before，after restarting the server, it will not start normally.
logs:
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/minio/minio/cmd.(*xlSets).getHashedSet(0xc000764640, 0x1c10721, 0x17, 0x40c2d6)
	github.com/minio/minio@/cmd/xl-sets.go:600 +0x9f
github.com/minio/minio/cmd.(*xlSets).NewNSLock(0xc000764640, 0x1fb2fc0, 0xc000212e40, 0x1bf791e, 0xa, 0xc0006624f0, 0x1, 0x1, 0xc000212e01, 0xc0006624f0)
	github.com/minio/minio@/cmd/xl-sets.go:369 +0x6b
github.com/minio/minio/cmd.(*xlZones).NewNSLock(0xc0006ab180, 0x1fb2fc0, 0xc000212e40, 0x1bf791e, 0xa, 0xc0006624f0, 0x1, 0x1, 0x48, 0x50)
	github.com/minio/minio@/cmd/xl-zones.go:86 +0x94
github.com/minio/minio/cmd.initSafeMode(0x1fb2fc0, 0xc0002a4240, 0x1ff7580, 0xc0006ab180, 0x0, 0x0)
	github.com/minio/minio@/cmd/server-main.go:184 +0x134
github.com/minio/minio/cmd.serverMain(0xc0000bab60)
	github.com/minio/minio@/cmd/server-main.go:512 +0xb5e
github.com/minio/cli.HandleAction(0x1894500, 0x1c839b8, 0xc0000bab60, 0xc0000b6900, 0x0)
	github.com/minio/cli@v1.22.0/app.go:500 +0x7c
github.com/minio/cli.Command.Run(0x1bf29c0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c1a6fb, 0x1b, 0x0, ...)
	github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).Run(0xc0000ba1a0, 0xc0000b6120, 0x6, 0x6, 0x0, 0x0)
	github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/minio/cmd.Main(0xc0000b6120, 0x6, 0x6)
	github.com/minio/minio@/cmd/main.go:169 +0x89
main.main()
	github.com/minio/minio@/main.go:37 +0x45

**Comment by harshavardhana** [comment]
> version:minio version RELEASE.2020-07-02T00-15-09Z
> start command:./minio server /minio_data/data1 /minio_data/data2 /minio_data/data3 /minio_data/data4
> description:It was normal before，after restarting the server, it will not start normally.
> logs:
> panic: runtime error: index out of range [-1]

You seem to be running older MinIO on backend disks with newer data format.
