### ISSUE TITLE
Solution for querying objects by tags

### ISSUE THREAD

**Issue by jgazeau** [minio/minio#13463]
Hi all,

I know that it's not possible for now to make complex queries on objects using the S3 API (And It will probably stay like this in the future as it is not the purpose of S3).
For example:  `listObjects` containing specific `tags`.

One possible option would be to delegate and manage indexing of objects in an external database so we could query in it to retrieve objects by tags.

Do you know if there are other solutions for this usecase ? Or maybe do you have something planned in the future to do so ?

Thank you very much for your answer.

Jordan.

**Comment by harshavardhana** [comment]
@jgazeau AWS S3 has no such API, you need to use bucket notifications to keep the content on some DB and then query that DB.

https://docs.min.io/docs/minio-bucket-notification-guide.html
