### ISSUE TITLE
Not being able to login with SSO - minio-policy claim missing from the JWT token 

### ISSUE THREAD

**Issue by MohamadTahir** [minio/minio#13468]
failing to login with openId

## Expected Behavior
being able to login with openId.

## Current Behavior
after logging with openid and being redirected back to the minio console, the user is not logged in

## Steps to Reproduce (for bugs)
we have set the below environment variables in the docker-compose (we are setting all of the other necessary env variables)
```
MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
MINIO_IDENTITY_OPENID_CLAIM_PREFIX: minio-
MINIO_IDENTITY_OPENID_SCOPES: "common-minio-console"
```

when we click on 'Login with SSO' the user is redirected to the our login screen, after logging in they are redirected back to the minio login screen,

checking the logs from docker we find the following error.

Logs
```
minio3_1  | DeploymentID: 2eccc545-d379-496d-86f7-1fa3999ba179
minio3_1  | RequestID: 16AF6D6D2374902B
minio3_1  | RemoteHost: 10.10.80.85
minio3_1  | Host: minio3:9000
minio3_1  | UserAgent: Go-http-client/1.1
minio3_1  | Error: minio-policy claim missing from the JWT token, credentials will not be generated (*errors.errorString)
minio3_1  |        4: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
minio3_1  |        3: cmd/sts-handlers.go:427:cmd.(*stsAPIHandlers).AssumeRoleWithSSO()
minio3_1  |        2: cmd/sts-handlers.go:523:cmd.(*stsAPIHandlers).AssumeRoleWithWebIdentity()
minio3_1  |        1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()
```

using postman to send a request with the same settings and checking the jwt.
```
{
  "iss": "<ourDomain>",
  "nbf": 1634645249,
  "iat": 1634645249,
  "exp": 1634648849,
  "aud": "common-minio-console",
  "scope": [
    "common-minio-console",
    "email",
    "openid",
    "profile"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "minio-console",
  "sub": "<id>",
  "auth_time": 1634645249,
  "idp": "local",
  "minio-policy": "admin:*,s3:*",
  "jti": "400650C349F8483FAB57B721697A27DE"
}
```

as far as I can see the `minio-policy` is there.

## Context
We are currently unable to login to the minio console, with either password/username or the openid. having the openid is a must for our group.

## Your Environment
We are running minio as a 3 node cluster installed with docker compose, all the 3 instances have the same configurations, there is a nginx infront of the instances, the connection to the nginx is secured with ssl, the nginx does the ssl termination then redirects the requests to the instances.

**Comment by vadmeste** [comment]
>   "minio-policy": "admin:*,s3:*",

Policy name is the canned name of the policy stored in your MinIO deployment. `mc admin policy list <alias>`  to list the name of the canned policies ,`mc admin policy add` to create a new one.

**Comment by shkarface** [comment]
@vadmeste  This was the first thing we tried before trying the `admin:*,s3:*, we tried setting it to `consoleAdmin` because checking the source code suggested that this was the policy that needed to be in the claim.

```sh
$ mc admin policy list s3
- readonly
- readwrite
- writeonly
- consoleAdmin
- diagnostics
```

The JWT now contains:

```json
{
  "minio-policy": "consoleAdmin"
}
```

But the issue is still there.

**Comment by harshavardhana** [comment]
> MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
> MINIO_IDENTITY_OPENID_CLAIM_PREFIX: minio-

If you set this only claim_name shall be used claim_prefix is not useful @MohamadTahir

**Comment by shkarface** [comment]
The prefix is just used as a test, we've also tried 
```sh
CLAIM_NAME: minio-policy
```

which is also the same as setting:
```sh
CLAIM_PREFIX: minio-
CLAIM_NAME: policy
```

This does not really contribute to the issue in any way.

**Comment by harshavardhana** [comment]
@shkarface you also need to use id_token not auth_token

**Comment by shkarface** [comment]
> @shkarface you also need to use id_token not auth_token

@harshavardhana  Can you please elaborate? we still have this issue.

**Comment by shkarface** [comment]
@harshavardhana Can we please reopen this issue as we still have it and we're locked out of the console browser
