### ISSUE TITLE
Provide a public Server API

### ISSUE THREAD

**Issue by toby3d** [minio/minio#13480]
**Is your feature request related to a problem? Please describe.**  
In the process of writing Minio-related code tests, I encountered not the most trivial ways to provide a temporary server for the test data. Although the server can be started up and used without directly installing the binary to the system, the practice of running it still causes some problems. For example, CPU spikes when `go test` is invoked, no guarantees that the server is ready for clients, and customization through a limited set of flags only.

**Describe the solution you'd like**  
I would like to have some kind of test or real server object with the ability to customize it and use it in every test without fear of race and a guarantee of being ready to use after initialization/startup.

**Describe alternatives you've considered**  
I created a utility to instantiate the Minio server on a random port using a temporary directory:
```go
package util

import (
	"context"
	"io/ioutil"
	"log"
	"net"
	"os"
	"time"

	"github.com/minio/madmin-go"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	miniocmd "github.com/minio/minio/cmd"
)

type MinioConfig struct {
	AccessKeyID     string
	Bucket          string
	SecretAccessKey string
}

// DefaultMinioConfig describes default
//nolint: gochecknoglobals
var DefaultMinioConfig = MinioConfig{
	AccessKeyID:     "minioadmin",
	Bucket:          "testing",
	SecretAccessKey: "minioadmin",
}

// TestMinio creates a MinIO server with temporary bucket on random port. It
// MUST be used ONCE PER TestMain function.
//
// Returns prepared Client and Cleanup function.
func TestMinio(cfg MinioConfig) (*minio.Client, func()) {
	if cfg.Bucket == "" {
		cfg.Bucket = DefaultMinioConfig.Bucket
	}

	if cfg.AccessKeyID == "" {
		cfg.AccessKeyID = DefaultMinioConfig.AccessKeyID
	}

	if cfg.SecretAccessKey == "" {
		cfg.SecretAccessKey = DefaultMinioConfig.SecretAccessKey
	}

	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		log.Fatalln(err)
	}

	addr := l.Addr().String()

	if err := l.Close(); err != nil {
		log.Fatalln(err)
	}

	admin, err := madmin.New(addr, cfg.AccessKeyID, cfg.SecretAccessKey, false)
	if err != nil {
		log.Fatalln(err)
	}

	tempDir, err := ioutil.TempDir("", "")
	if err != nil {
		log.Fatalln(err)
	}

	go miniocmd.Main([]string{"minio", "server", "--quiet", "--address", addr, tempDir})

	// NOTE(toby3d): there is no reliable way to wait for the server to start
	time.Sleep(1 * time.Second)

	client, err := minio.New(addr, &minio.Options{
		Creds:  credentials.NewStaticV4(cfg.AccessKeyID, cfg.SecretAccessKey, ""),
		Secure: false,
	})
	if err != nil {
		log.Fatalln(err)
	}

	if err := client.MakeBucket(context.Background(), cfg.Bucket, minio.MakeBucketOptions{}); err != nil {
		log.Fatalln(err)
	}

	// noling: errcheck
	return client, func() {
		admin.ServiceStop(context.Background())
		os.RemoveAll(tempDir)
	}
}
```

This utility has the following problems:
* Use only in `TestMain(m *testing.M)`, otherwise races are possible;
* It requires a non-fixed wait time to prepare the server for work, which adds fragility to the tests and requires the use of time.Sleep;
* Requires a directory for temporary files. This is not essentially a problem, but would like to work with objects in memory, which would speed up tests considerably and not require garbage collection after execution;

**Additional context**
This issue and solution options are roughly similar to minio/kes#164 issue.

**Comment by klauspost** [comment]
> Use only in TestMain(m *testing.M), otherwise races are possible;

You could use a [sync.Once](https://pkg.go.dev/sync#Once), but TestMain is also fine. Nothing unusual about setting it up there.

> It requires a non-fixed wait time to prepare the server for work, which adds fragility to the tests and requires the use of time.Sleep;

You should be able to [query health](https://docs.min.io/minio/baremetal/monitoring/healthcheck-probe.html#cluster-write-quorum) to avoid random waits.

> Requires a directory for temporary files. 

Yes. That is however nothing exceptional for Go tests.

**Comment by toby3d** [comment]
> ...TestMain is also fine. Nothing unusual about setting it up there.

In general, yes, it is normal practice to use the data prepared in `TestMain` in tests. But it requires special design of data in tests to prevent their modification by other tests. In theory, the probability of race remains if the tests are run in parallel with one connection from TestMain.

> You should be able to [query health](https://docs.min.io/minio/baremetal/monitoring/healthcheck-probe.html#cluster-write-quorum) to avoid random waits.

Okay, I'll see if this solves the problem of using the timer. 👀

**Comment by klauspost** [comment]
> In theory, the probability of race remains if the tests are run in parallel with one connection from TestMain.

Not really. Use different/random buckets for your tests and set them up as you need them. The `*minio.Client` itself is naturally thread safe.

**Comment by harshavardhana** [comment]
We have solution here and we do not need to spend time on any overhaul AFAICS.

Closing this issue
