### ISSUE TITLE
Inconsistent etag in list_objects and stat_object in minio azure gateway

### ISSUE THREAD

**Issue by Ajk4** [minio/minio#13497]
ETags in list_objects and stat_object have different values with Minio Azure Gateway 

ETag in lists looks like  `0x8D9953E36AF2607-1`
ETag when querying single object looks like `9810707c8811be7b187e0d2acabb0cad`

## Expected Behavior
ETag should be the same for an object whether I'm using list_object or stat_object.

## Current Behavior
Different ETag in list_objects and stat_object with Minio Azure Gateway 

## Steps to Reproduce (for bugs)
Example python code reproducing issue. It's not python-client specific. If i'm using rust code same happens
```
from minio import Minio

minio_storage = Minio("fillme", "fillme", "fillme", secure=False)  # Minio Azure Gateway 

bucket_name = 'test-bucket'
object_name = 'test-object'

if not minio_storage.bucket_exists(bucket_name):
    minio_storage.make_bucket(bucket_name)
filepath = 'FILLME'
minio_storage.fput_object(bucket_name, object_name, filepath)

for obj in minio_storage.list_objects(bucket_name):
    print(obj.etag)
print(minio_storage.stat_object(bucket_name, object_name).etag)
```
prints:
```
0x8D9953E36AF2607-1
9810707c8811be7b187e0d2acabb0cad
```

## Your Environment

We use `minio/minio:RELEASE.2021-10-08T23-58-24Z` docker image for serving azure gateway

**Comment by harshavardhana** [comment]
> ETag in lists looks like `0x8D9953E36AF2607-1`
> ETag when querying single object looks like `9810707c8811be7b187e0d2acabb0cad`

We return what is sent by the Azure backend @Ajk4 - we can do special handling for Head because we can get the value from extended metadata that we store along with the object. 

Unfortunately, we cannot do that with Listing, since azure doesn't send this information as part of the List response.

**Comment by harshavardhana** [comment]
I don't think we can do anything about here.

**Comment by klauspost** [comment]
@harshavardhana Could we use `0x...` etag form always?

**Comment by harshavardhana** [comment]
> @harshavardhana Could we use `0x...` etag form always?

No we cannot many S3 applications fail otherwise.

**Comment by harshavardhana** [comment]
There is no way to fix this unfortunately without overly complicating the current Gateway implementation.

If there is a commercial requirement @Ajk4 please engage us https://min.io/pricing if you need this addressed more comprehensively.
