### ISSUE TITLE
the entire cluster space will reduced when disk offline

### ISSUE THREAD

**Issue by jiangfucheng** [minio/minio#13505]
**Is your feature request related to a problem? Please describe.**

Hi, I have some problem for this PR(https://github.com/minio/minio/pull/11852). When some disk offline, the number of parity blocks will increase, then it will cause a problem:
the space of entire cluster will reduced, because there are fewer data blocks in this erasure set, it will take up more space. so, when this erasure set is full, the entire cluster will can not write any object, it will waste some disk space.

**Describe the solution you'd like**

I found it can re-shard that data in this PR, but i didn't find the relevant code. is it possible add some option to turn off this feature? Or supply some method to re-shard this data when healing. 
Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by klauspost** [comment]
@jiangfucheng We don't do resharding. It is expensive and there is little to no gains, so we have no plans for it.

You should not run your cluster in a degraded state long enough for this to matter. 

If it is, download and reupload your objects.
