### ISSUE TITLE
POST multipart/form-data requests with file > 1MB for upload : rejected

### ISSUE THREAD

**Issue by yalau27** [minio/minio#13518]
Minio does not accept POST multi/form-data requests containing a HTTP "File" header field for files having a size above 1MB.

```
Oct 26 14:55:31 VM minio[82042]: API: PostPolicyBucket(bucket=zotero)
Oct 26 14:55:31 VM minio[82042]: Time: 14:55:31 CEST 10/26/2021
Oct 26 14:55:31 VM minio[82042]: DeploymentID: e9e62f4e-24ec-4da8-ac1e-b0f45a874290
Oct 26 14:55:31 VM minio[82042]: RequestID: 16B195E076991F64
Oct 26 14:55:31 VM minio[82042]: RemoteHost: 127.0.0.1
Oct 26 14:55:31 VM minio[82042]: Host: 127.0.0.1:9000
Oct 26 14:55:31 VM minio[82042]: UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Oct 26 14:55:31 VM minio[82042]: Error: Data size larger than expected (*errors.errorString)
Oct 26 14:55:31 VM minio[82042]:        4: cmd/handler-utils.go:281:cmd.validateFormFieldSize()
Oct 26 14:55:31 VM minio[82042]:        3: cmd/handler-utils.go:302:cmd.extractPostPolicyFormValues()
Oct 26 14:55:31 VM minio[82042]:        2: cmd/bucket-handlers.go:865:cmd.objectAPIHandlers.PostPolicyBucketHandler()
Oct 26 14:55:31 VM minio[82042]:        1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()
```

Files bigger than 1MB should be accepted. The 1MB limit should be applied only to other HTTP header field as described in file `cmd/globals.go` (constant `maxFormFieldSize`).

It currently works for files having a size less than 1MB.

The problem comes from function `validateFormFieldSize()` in file `cmd/handler-utils.go` that verifies if all value's fields exceeds S3 limit, including the "File" field.

A solution could consist in verifying if k value is different from "File".

We are currently using Minio as an S3 storage to install a Zotero server. Files with a size above 1MB cannot be uploaded.

* Version used (`minio --version`): RELEASE.2021-10-02T16-31-05Z
* Server setup and configuration: `/usr/local/bin/minio server -C /etc/minio --address 127.0.0.1:9000 --console-address 127.0.0.1:35000 /var/s3`
* Operating System and version (`uname -a`): Debian 11, Linux VM-IUT2 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**Comment by klauspost** [comment]
The error indicates you are trying to upload a bucket policy:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html

> Bucket policies are limited to 20 KB in size.

If you are trying to upload a file your call is incorrect.

**Comment by yalau27** [comment]
Hi,

The POST request (see below; the S3 policy is less than 20KB) that triggered the 
error is a Browser-based S3 file upload using a POST Upload request as in :
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

Such request includes both a "policy" field and a "file" field. As it is a 
"multipart/form-data", function `PostPolicyBucketHandler()` is consequently 
called.

I might have missed something.

Thank you for your help.

Best,

=== POST Upload REQUEST ===

POST /zotero/ HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; 
boundary=---------------------------2438860c9c856edf7d498422b2d94514
Content-Length: 1815714
Connection: keep-alive

-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="key"

4ff4064d19d59844920181c5b1f294d0
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="acl"

private
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="Content-MD5"

T/QGTRnVmESSAYHFsfKU0A==
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="success_action_status"

201
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="policy"

eyJleHBpcmF0aW9uIjoiMjAyMS0xMC0yNVQxMjo1MToyOVoiLCJjb25kaXRpb25zIjpbeyJidWNrZXQiOiJ6b3Rlcm8ifSx7ImtleSI6IjRmZjQwNjRkMTlkNTk4NDQ5MjAxODFjNWIxZjI5NGQwIn0seyJhY2wiOiJwcml2YXRlIn0seyJDb250ZW50LU1ENSI6IlRcL1FHVFJuVm1FU1NBWUhGc2ZLVTBBPT0ifSxbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwiMTgxMzczNiIsIjE4MTM3MzYiXSx7InN1Y2Nlc3NfYWN0aW9uX3N0YXR1cyI6IjIwMSJ9LHsieC1hbXotY3JlZGVudGlhbCI6InpvdGVyb1wvMjAyMTEwMjVcL2V1LXdlc3QtMVwvczNcL2F3czRfcmVxdWVzdCJ9LHsieC1hbXotYWxnb3JpdGhtIjoiQVdTNC1ITUFDLVNIQTI1NiJ9LHsieC1hbXotZGF0ZSI6IjIwMjExMDI1VDExNTEyOVoifV19
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="x-amz-algorithm"

AWS4-HMAC-SHA256
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="x-amz-credential"

zotero/20211025/eu-west-1/s3/aws4_request
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="x-amz-date"

20211025T115129Z
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="x-amz-signature"

16ec57aebffe5633bad4b93949794427583fa8d6ed4674d82ec644e1a2109e42
-----------------------------2438860c9c856edf7d498422b2d94514
Content-Disposition: form-data; name="file"

[... Removed ...]

Le 27/10/2021 à 16:11, Klaus Post a écrit :
> The error indicates you are trying to upload a bucket policy:
> 
> https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html 
> <https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html>
> 
>     Bucket policies are limited to 20 KB in size.
> 
> If you are trying to upload a file your call is incorrect.

**Comment by klauspost** [comment]
@yalau27 Sorry, my mistake. Specify a file name.

`Content-Disposition: form-data; name="file"; filename="MyFilename.jpg"`

We have to treat it this way, otherwise we risk DOS from unbounded memory allocs.

**Comment by harshavardhana** [comment]
> @yalau27 Sorry, my mistake. Specify a file name.
> 
> `Content-Disposition: form-data; name="file"; filename="MyFilename.jpg"`
> 
> We have to treat it this way, otherwise we risk DOS from unbounded memory allocs.

This is also an AWS S3 spec expects in this situation.

**Comment by yalau27** [comment]
Thanks ! That was the problem.

Best,
