### ISSUE TITLE
Floating metric minio_bucket_usage_object_total in unloaded cluster

### ISSUE THREAD

**Issue by foxsibirsky** [minio/minio#13525]
Hello. I have a minio cluster 4 nodes with 2 disks per node.
There are 2 buckets 79 000 objects and 2 300 000 objects give or take..
Curent version minio is 2021-10-13T00:23:17Z

The cluster doesn't have any payload from users for a times. But I see the cluster  metric **minio_bucket_usage_object_total** is not constant. It is floating. For smal bucket +/- 1-2 obejcts, for big bucket +/- 1000-2000 objects. 
I've tried to run healing process, but after it didn't change anything.

I get and show this metric with basic tool - prometheus + grafana dashboard.
I suppose, this behaviour can affect to the sync process, like mc mirror S3 -> Filesystem
For instance I attached a graph for big bucket.

## Environment
* Version used (`minio --version`): 2021-10-13T00:23:17Z
* Server setup and configuration: KVM virtual machine, Oracle Linux OEL 7.6, XFS filesystem, minio cluster 4 nodes with 2 disks per node.
* Operating System and version (`uname -a`):` Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Mon Jun 17 15:42:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by harshavardhana** [comment]
> Hello. I have a minio cluster 4 nodes with 2 disks per node.
> There are 2 buckets 79 000 objects and 2 300 000 objects give or take..
> Curent version minio is 2021-10-13T00:23:17Z

how long has it been since you uploaded the objects?

**Comment by foxsibirsky** [comment]
> > Hello. I have a minio cluster 4 nodes with 2 disks per node.
> > There are 2 buckets 79 000 objects and 2 300 000 objects give or take..
> > Curent version minio is 2021-10-13T00:23:17Z
> 
> how long has it been since you uploaded the objects?

Last obect was loaded 14 days ago.

**Comment by foxsibirsky** [comment]
Example
![image](https://user-images.githubusercontent.com/46556927/139191971-30ced39e-e1d4-4cf9-b025-baa183c929e6.png)

**Comment by harshavardhana** [comment]
> > > Hello. I have a minio cluster 4 nodes with 2 disks per node.
> > > There are 2 buckets 79 000 objects and 2 300 000 objects give or take..
> > > Curent version minio is 2021-10-13T00:23:17Z
> > 
> > how long has it been since you uploaded the objects?
> 
> Last obect was loaded 14 days ago.
> 

Can you share output of `mc admin top locks --json --stale alias/` and also attach the output of `curl` output to the Prometheus scrape endpoint.

**Comment by foxsibirsky** [comment]
> Can you share output of `mc admin top locks --json --stale alias/` and also attach the output of `curl` output to the Prometheus scrape endpoint.
```
{
 "status": "success",
 "locks": {
  "time": "2021-10-28T09:14:17.320161664Z",
  "resource": ".minio.sys/runDataScanner.lock",
  "type": "WRITE",
  "source": "[data-scanner.go:102:runDataScanner()]",
  "serverlist": [
   "1.2.3.231:9000",
   "1.2.3.232:9000",
   "1.2.3.234:9000",
   "1.2.3.233:9000"
  ],
  "owner": "1.2.3.233:9000",
  "id": "62e41eed-07c1-42d6-a9a8-223020da46b3",
  "quorum": 3
 }
}
```
`mc admin top locks`
```
Time                  Type    Resource
17 hours              WRITE   .minio.sys/runDataScanner.lock

```
And file [prometheus_scrape.txt](https://github.com/minio/minio/files/7438450/prometheus_scrape.txt) with curl output from one node

**Comment by harshavardhana** [comment]
Everything seems to be running fine 

```
# HELP minio_node_scanner_bucket_scans_finished Total number of bucket scans finished since server start
# TYPE minio_node_scanner_bucket_scans_finished counter
minio_node_scanner_bucket_scans_finished{server="1.2.3.231:9000"} 56
minio_node_scanner_bucket_scans_finished{server="1.2.3.232:9000"} 57
minio_node_scanner_bucket_scans_finished{server="1.2.3.233:9000"} 69
minio_node_scanner_bucket_scans_finished{server="1.2.3.234:9000"} 62
# HELP minio_node_scanner_bucket_scans_started Total number of bucket scans started since server start
# TYPE minio_node_scanner_bucket_scans_started counter
minio_node_scanner_bucket_scans_started{server="1.2.3.231:9000"} 58
minio_node_scanner_bucket_scans_started{server="1.2.3.232:9000"} 57
minio_node_scanner_bucket_scans_started{server="1.2.3.233:9000"} 69
minio_node_scanner_bucket_scans_started{server="1.2.3.234:9000"} 62
# HELP minio_node_scanner_directories_scanned Total number of directories scanned since server start.
# TYPE minio_node_scanner_directories_scanned counter
minio_node_scanner_directories_scanned{server="1.2.3.231:9000"} 2.013138e+06
minio_node_scanner_directories_scanned{server="1.2.3.232:9000"} 2.330929e+06
minio_node_scanner_directories_scanned{server="1.2.3.233:9000"} 2.562779e+06
minio_node_scanner_directories_scanned{server="1.2.3.234:9000"} 2.322364e+06
# HELP minio_node_scanner_objects_scanned Total number of unique objects scanned since server start.
# TYPE minio_node_scanner_objects_scanned counter
minio_node_scanner_objects_scanned{server="1.2.3.231:9000"} 1.349703e+06
minio_node_scanner_objects_scanned{server="1.2.3.232:9000"} 1.561846e+06
minio_node_scanner_objects_scanned{server="1.2.3.233:9000"} 1.721939e+06
minio_node_scanner_objects_scanned{server="1.2.3.234:9000"} 1.551311e+06
# HELP minio_node_scanner_versions_scanned Total number of object versions scanned since server start.
# TYPE minio_node_scanner_versions_scanned counter
minio_node_scanner_versions_scanned{server="1.2.3.231:9000"} 1.349703e+06
minio_node_scanner_versions_scanned{server="1.2.3.232:9000"} 1.561846e+06
minio_node_scanner_versions_scanned{server="1.2.3.233:9000"} 1.721939e+06
minio_node_scanner_versions_scanned{server="1.2.3.234:9000"} 1.551311e+06
```

```
# HELP minio_bucket_usage_object_total Total number of objects
# TYPE minio_bucket_usage_object_total gauge
minio_bucket_usage_object_total{bucket="bucket1",server="1.2.3.231:9000"} 2.390983e+06
minio_bucket_usage_object_total{bucket="bucket2",server="1.2.3.231:9000"} 77901
minio_bucket_usage_object_total{bucket="test",server="1.2.3.231:9000"} 2
```

I don't know what you are saying here is wrong?

**Comment by foxsibirsky** [comment]
Hm.. I don't understand one thing. In the node exporter [source code](https://github.com/joe-pll/minio-exporter/blob/master/minio_exporter.go) I see func bucketStats objNum int64, at the same time I see 2.390983e+06. 
Could this make a deviations in the graph?

And ok. If you didn't see any problems, please close the issue.

**Comment by harshavardhana** [comment]
> Hm.. I don't understand one thing. In the node exporter [source code](https://github.com/joe-pll/minio-exporter/blob/master/minio_exporter.go) I see func bucketStats objNum int64, at the same time I see 2.390983e+06. Could this make a deviations in the graph?
> 
> And ok. If you didn't see any problems, please close the issue.

That project is old and not maintained in 3+yrs , you should be reading latest docs.
