### ISSUE TITLE
make bucket failed

### ISSUE THREAD

**Issue by ldocao-decathlon** [minio/minio#13521]
## Expected Behavior

```
aws --endpoint-url https://play.min.io:9000 s3 mb s3://my-personal-bucket
make_bucket failed: s3://my-personal-bucket Could not connect to the endpoint URL: "https://s3.aACVD.amazonaws.com/my-personal-bucket"
```

## Current Behavior
I don't understand why the region is automatically replaced by aACVD

## Steps to reproduce
List current buckets work:

```
aws --endpoint-url https://play.min.io:9000 s3 ls
2021-09-01 03:26:17 ala123
2021-09-30 14:44:17 bucketa
2021-10-27 11:23:32 event-storage
2021-10-27 11:34:51 hello
2021-10-27 11:31:33 mymusic
2021-10-14 10:01:38 ps-test
2021-09-22 11:19:03 ptammitest-new
2021-10-27 11:19:36 test
2021-10-27 11:18:09 test-source
2021-10-27 11:22:51 test-target
2021-10-13 08:28:37 test123
2021-10-27 11:41:35 tzcvmlfcuzufztf
```

But not make bucket:

```
aws --endpoint-url https://play.min.io:9000 s3 mb s3://my-personal-bucket
make_bucket failed: s3://my-personal-bucket Could not connect to the endpoint URL: "https://s3.aACVD.amazonaws.com/my-personal-bucket"
```

## Your Environment
aws-cli/2.2.43 Python/3.9.7 Darwin/20.6.0 source/arm64 prompt/off
Darwin FRL-C02GC09CQ6LW 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

**Comment by klauspost** [comment]
@ldocao-decathlon Use "path style" bucket links. You must specify that in the client so it doesn't use subdomains for buckets.
