### ISSUE TITLE
Installing via Homebrew on Apple Silicon

### ISSUE THREAD

**Issue by johndbritton** [minio/minio#13522]
## Expected Behavior

Installing using `brew install minio/stable/mc` succeeds.

## Current Behavior

It fails, as follows:

```sh
brew install minio/stable/mc
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the minio/stable tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/minio/homebrew-stable/mc.rb:19

mc: The x86_64 architecture is required for this software.
Error: mc: An unsatisfied requirement failed this build.
```

## Possible Solution

Two parts:
1. Resolve the warning message, which should be handled by https://github.com/minio/homebrew-stable/pull/36
2. Update the Homebrew formula to support `arm64` per https://github.com/minio/minio/issues/12856

## Steps to Reproduce (for bugs)

1. Run `brew install minio/stable/mc` on an Apple Silicon Mac running macOS Monterey (12.0.1)
2. See warning and error message above.

## Context

My team depends on `minio` as part of our development workflow and we've automated installation and management using Homebrew. I see there is a build for `arm64` but the Homebrew formula needs to be updated to support it.

## Regression

N/A

## Your Environment

* Version used (`minio --version`): N/A
* Server setup and configuration: N/A
* Operating System and version (`uname -a`): Darwin jdb-pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

**Comment by harshavardhana** [comment]
Please send a PR to support Apple Silicon @johndbritton we do not cycles to test this on our end.

**Comment by johndbritton** [comment]
@harshavardhana I added support for ARM here: https://github.com/minio/minio/issues/13522

**Comment by harshavardhana** [comment]
> @harshavardhana I added support for ARM here: https://github.com/minio/minio/issues/13522

This looks like an issue do you have a PR?

**Comment by johndbritton** [comment]
Pasted the wrong link.

https://github.com/minio/homebrew-stable/pull/38
