### ISSUE TITLE
minio consumes nearly 90% disk io

### ISSUE THREAD

**Issue by cg-zhou** [minio/minio#13524]
##  Description
* minio version: 2021-09-09T21:37:07Z
* hosted in docker

Help....I start a minio server in docker, and find that it consumes nearly 90% disk IO.
After close all the business logic services, the situation didn't comes better.
Then I start the trace in the minio console, and find there are lots of `os.Rename` and `os.MkdirAll` calls.
Is it a bug? What could I do to get more information about this issue?

![image](https://user-images.githubusercontent.com/9943470/139181973-1dd52cc0-8668-47fd-aa7a-687dc2dade71.png)

![image](https://user-images.githubusercontent.com/9943470/139180900-7e8a99ec-4153-4e74-b284-a8804edd97ce.png)

**Comment by harshavardhana** [comment]
> Then I start the trace in the minio console, and find there are lots of `os.Rename` and `os.MkdirAll` calls.
> Is it a bug? What could I do to get more information about this issue?

can you share the output of `mc admin trace -a alias/` run for 5 minutes.  it seems like there is some I/O going on.

**Comment by harshavardhana** [comment]
> * minio version: 2021-09-09T21:37:07Z
> * hosted in docker

Also please upgrade - we can resume debugging after you upgraded.

**Comment by cg-zhou** [comment]
> > Then I start the trace in the minio console, and find there are lots of `os.Rename` and `os.MkdirAll` calls.
> > Is it a bug? What could I do to get more information about this issue?
> 
> can you share the output of `mc admin trace -a alias/` run for 5 minutes. it seems like there is some I/O going on.

I trace for about 1 minute, it seems lots of `Rename` and `MkdirAll` in the `.minio.sys` folder, as the picture shows below.
Additional, on the server, there are about 244 Buckets and 161 GiB Usage.

![image](https://user-images.githubusercontent.com/9943470/139185833-6dba1281-fcc4-49a5-9c50-88ccd8a6c9d3.png)

**Comment by harshavardhana** [comment]
Oh this is expected @cg-zhou - this is a normal routine that runs. 

But not sure why it should be taking 90% disk, did you make changes to scanner settings?

**Comment by klauspost** [comment]
For very small buckets is may write comparably a lot. These must be empty or very close to that.

`mc admin config get alias scanner` to see your scanner settings. You can adjust `cycle` to run less frequent.

**Comment by cg-zhou** [comment]
@harshavardhana , @klauspost Thanks a lot.
After change the scanner settings, It seems a little better now
The 90% disk IO may be related to disk performance, maybe I need to test disk hardware more.
