### ISSUE TITLE
Encountered Unknown AWSError 'XAmzContentSHA256Mismatch': The provided 'x-amz-content-sha256' header does not match what was computed.

### ISSUE THREAD

**Issue by gyl30** [minio/minio#13535]
I am using AWS SDK for C++ to connect to minio. I occasionally encounter such errors when uploading files. How can I solve them? Minio runs in dokcer, the output of minio -v is minio version RELEASE.2021-08-05T22-01-19Z, the operating system is ubuntu 20.04, the output of unmae -a is Linux u 5.11.0-38-generic #42~ 20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[WARN] 2021-10-29 06:49:10.795 AWSErrorMarshaller [140736246822656] Encountered Unknown AWSError 'XAmzContentSHA256Mismatch': The provided 'x-amz-content-sha256' header does not match what was computed.
[ERROR] 2021-10-29 06:49:10.795 AWSClient [140736246822656] HTTP response code: 400
Resolved remote host IP address: 192.168.3.24
Request ID: 16B26D9FE0154A88
Exception name: XAmzContentSHA256Mismatch
Error message: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message: The provided 'x-amz-content-sha256' header does not match what was computed.
11 response headers:
accept-ranges : bytes
content-length : 500
content-security-policy : block-all-mixed-content
content-type : application/xml
date : Fri, 29 Oct 2021 06:49:10 GMT
server : MinIO
strict-transport-security : max-age=31536000; includeSubDomains
vary : Accept-Encoding
x-amz-request-id : 16B26D9FE0154A88
x-content-type-options : nosniff
x-xss-protection : 1; mode=block
[WARN] 2021-10-29 06:49:10.795 AWSClient [140736246822656] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.

**Comment by gyl30** [comment]
Oh, yes, this is the startup parameter of docker

`
docker run -ti -p 19000:19000 -p 18000:18000 --name minio -e "MINIO_ROOT_USER=xxxxx" -e "MINIO_ROOT_PASSWORD=xxxxx" minio/minio server /data --address '0.0.0.0:19000' --console-address '0.0.0.0:18000'
`

**Comment by gyl30** [comment]
This is the first log of errors



[INFO] 2021-10-29 07:51:47.817 Aws::Config::AWSConfigFileProfileConfigLoader [140737353978624] Initializing config loader against fileName /root/.aws/credentials and using profilePrefix = 0
[INFO] 2021-10-29 07:51:47.817 Aws::Config::AWSConfigFileProfileConfigLoader [140737353978624] Initializing config loader against fileName /root/.aws/config and using profilePrefix = 1
[INFO] 2021-10-29 07:51:47.817 Aws::Config::AWSConfigFileProfileConfigLoader [140737353978624] Unable to open config file /root/.aws/credentials for reading.
[INFO] 2021-10-29 07:51:47.817 Aws::Config::AWSProfileConfigLoader [140737353978624] Failed to reload configuration.
[INFO] 2021-10-29 07:51:47.817 Aws::Config::AWSConfigFileProfileConfigLoader [140737353978624] Unable to open config file /root/.aws/config for reading.
[INFO] 2021-10-29 07:51:47.817 Aws::Config::AWSProfileConfigLoader [140737353978624] Failed to reload configuration.
[INFO] 2021-10-29 07:51:47.818 CurlHttpClient [140737353978624] Initializing Curl library with version: 7.53.1, ssl version:
[WARN] 2021-10-29 07:51:47.819 ClientConfiguration [140737353978624] Retry Strategy will use the default max attempts.
[INFO] 2021-10-29 07:51:47.819 EC2MetadataClient [140737353978624] Creating AWSHttpResourceClient with max connections 2 and scheme http
[INFO] 2021-10-29 07:51:47.819 CurlHandleContainer [140737353978624] Initializing CurlHandleContainer with size 2
[WARN] 2021-10-29 07:54:27.293 ClientConfiguration [140736406218496] Retry Strategy will use the default max attempts.
[INFO] 2021-10-29 07:54:27.293 CurlHandleContainer [140736406218496] Pool grown by 2
[INFO] 2021-10-29 07:54:27.293 CurlHandleContainer [140736406218496] Connection has been released. Continuing.
[ERROR] 2021-10-29 07:54:28.293 CurlHttpClient [140736406218496] Curl returned error code 28 - Timeout was reached
[ERROR] 2021-10-29 07:54:28.293 EC2MetadataClient [140736406218496] Http request to retrieve credentials failed
[WARN] 2021-10-29 07:54:28.293 EC2MetadataClient [140736406218496] Request failed, now waiting 0 ms before attempting again.
[INFO] 2021-10-29 07:54:28.293 CurlHandleContainer [140736406218496] Connection has been released. Continuing.
[ERROR] 2021-10-29 07:54:29.293 CurlHttpClient [140736406218496] Curl returned error code 28 - Timeout was reached
[ERROR] 2021-10-29 07:54:29.293 EC2MetadataClient [140736406218496] Http request to retrieve credentials failed
[ERROR] 2021-10-29 07:54:29.293 EC2MetadataClient [140736406218496] Can not retrive resource from http://169.254.169.254/latest/meta-data/placement/availability-zone
[INFO] 2021-10-29 07:54:29.293 EC2MetadataClient [140736406218496] Unable to pull region from instance metadata service
[INFO] 2021-10-29 07:54:29.293 CurlHandleContainer [140736406218496] Initializing CurlHandleContainer with size 25
[INFO] 2021-10-29 07:54:29.294 CurlHandleContainer [140736406218496] Pool grown by 2
[INFO] 2021-10-29 07:54:29.294 CurlHandleContainer [140736406218496] Connection has been released. Continuing.
[INFO] 2021-10-29 07:54:29.297 CurlHandleContainer [140736406218496] Connection has been released. Continuing.
[INFO] 2021-10-29 07:56:55.364 CurlHandleContainer [140736238429952] Connection has been released. Continuing.
[WARN] 2021-10-29 07:56:58.054 AWSErrorMarshaller [140736238429952] Encountered Unknown AWSError 'XAmzContentSHA256Mismatch': The provided 'x-amz-content-sha256' header does not match what was computed.
[ERROR] 2021-10-29 07:56:58.054 AWSClient [140736238429952] HTTP response code: 400
Resolved remote host IP address: 192.168.3.24
Request ID: 16B27152DA87294E
Exception name: XAmzContentSHA256Mismatch
Error message: Unable to parse ExceptionName: XAmzContentSHA256Mismatch Message: The provided 'x-amz-content-sha256' header does not match what was computed.
11 response headers:
accept-ranges : bytes
content-length : 498
content-security-policy : block-all-mixed-content
content-type : application/xml
date : Fri, 29 Oct 2021 07:56:58 GMT
server : MinIO
strict-transport-security : max-age=31536000; includeSubDomains
vary : Accept-Encoding
x-amz-request-id : 16B27152DA87294E
x-content-type-options : nosniff
x-xss-protection : 1; mode=block
[WARN] 2021-10-29 07:56:58.054 AWSClient [140736238429952] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.

**Comment by harshavardhana** [comment]
Please provide an entire sample code that we can compile and test. 

Without that we can't really help much here.
