### ISSUE TITLE
Minio clusters cannot be forwarded through nginx

### ISSUE THREAD

**Issue by DamonJason** [minio/minio#13536]
I have a problem. Please help me solve it

minio version:  minio/minio:latest
minio cluster:
  minio server --address 0.0.0.0:7013 --console-address 0.0.0.0:7015 http://192.168.1.1/data http://192.168.1.2/data http://192.168.1.3/data http://192.168.1.4/data 

nginx:
        location /img/ {
            proxy_pass "http://192.168.1.1:7013/img/";
            proxy_redirect default;
        }
In this way, the configuration can be accessed successfully

nginx:
upstream minio_backend {
  server 192.168.1.1:7013   weight=100 max_fails=1 fail_timeout=30s;
  server 192.168.1.2:7013   weight=100 max_fails=1 fail_timeout=30s;
  server 192.168.1.3:7013   weight=100 max_fails=1 fail_timeout=30s;
  server 192.168.1.4:7013   weight=100 max_fails=1 fail_timeout=30s;
}   
        location /img/ {
            proxy_pass "http://minio_backend/img/";
            proxy_redirect default;
        }
In this way, the configuration will report an error 403
code: SignatureDoesNotMatch, message: The request signature we calculated does not match the signature you provided. Check your key and signing method.

How can I access the service through any IP of the cluster？

**Comment by vadmeste** [comment]
@dxl727754275, please follow this documentation, https://docs.min.io/docs/setup-nginx-proxy-with-minio.html.
