### ISSUE TITLE
upload a folder recursively

### ISSUE THREAD

**Issue by ThyrixYang** [minio/minio#13539]
I can only select to upload a file in the console.
And I did not find any API for doing this directly. 
I think this is a reasonable feature, and I have found some posts for this issue:
https://stackoverflow.com/questions/66136763/how-to-upload-a-directory-to-minio-using-python
https://stackoverflow.com/questions/48451433/how-to-upload-folder-structure-to-minio-objectstorage
https://github.com/minio/minio-js/issues/758

**Comment by klauspost** [comment]
The closest API for that is when using `X-Amz-Meta-Snowball-Auto-Extract`. See more about it here: https://blog.min.io/minio-optimizes-small-objects/

We added support for that in the [Go client](https://pkg.go.dev/github.com/minio/minio-go/v7#Client.PutObjectsSnowball), but you can manually do it in others as well.

**Comment by charboubmustapha** [comment]
any news about the implementation of this feature please

**Comment by klauspost** [comment]
@charboubmustapha See the linked issue.
