### ISSUE TITLE
Bucket Name can't Support Chinese

### ISSUE THREAD

**Issue by bluelzx** [minio/minio#13537]
I have a problem. Please help me solve it
enter minio console website page,
on Create Bucket page,
when i put chinese words on to Bucket Name field
it will return back "Bucket name contains invalid characters" error info on the page
some one can fix this?
i know this issue is on 
minio/pkg/s3utils/utils.go 
validBucketName or validBucketNameStrict,on this code can  Support Chinese?
plesese,thank you

**Comment by klauspost** [comment]
Upgrade to version 2021-10-23T03:28:24Z or latest.

**Comment by harshavardhana** [comment]
> I have a problem. Please help me solve it enter minio console website page, on Create Bucket page, when i put chinese words on to Bucket Name field it will return back "Bucket name contains invalid characters" error info on the page some one can fix this? i know this issue is on minio/pkg/s3utils/utils.go validBucketName or validBucketNameStrict,on this code can Support Chinese? plesese,thank you

Bucket names do not support chinese characters as per 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html
