### ISSUE TITLE
Error: Unable to write all the data to client Storage resources are insufficient for the read operation xx/shard-01/upkooftnoaejoarygfxwuwfjsvlohrhf (*fmt.wrapError)

### ISSUE THREAD

**Issue by intfish123** [minio/minio#13543]
## Current Behavior
I use distriubte minio server as clickhouse's s3 storage, and when i insert data, it will happend.

Error: Unable to write all the data to client Storage resources are insufficient for the read operation xx/shard-01/bslnomlwdnjciagxoaiunrtoctehhmbs (*fmt.wrapError)
3: cmd/object-handlers.go:521:cmd.objectAPIHandlers.getObjectHandler()
2: cmd/object-handlers.go:575:cmd.objectAPIHandlers.GetObjectHandler()
1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()

## Steps to Reproduce (for bugs)
1. Use clickhouse-21.8.4.51 and 5 minio servers
2. Insert data to clickhouse

## Regression
 Regression

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-10-13T00-23-17Z
* Server setup and configuration:  
export MINIO_ETCD_ENDPOINTS="http://172.16.16.180:2379,http://172.16.16.181:2379,http://172.16.16.182:2379"
export MINIO_PUBLIC_IPS=172.16.16.180,172.16.16.181,172.16.16.182,172.16.16.183,172.16.16.184,172.16.16.185
export MINIO_DOMAIN=cluster.minio.com
export MINIO_PROMETHEUS_AUTH_TYPE="public"

/root/minio/minio server --config-dir /etc/minio --address 0.0.0.0:9090 --console-address ":9091" \
http://172.16.16.{180...185}/minio_ssd/data

* Operating System and version (`uname -a`): Linux root 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Error: Unable to write all the data to client Storage resources are insufficient for the read operation xx/shard-01/bslnomlwdnjciagxoaiunrtoctehhmbs (*fmt.wrapError)

This looks like your nodes are getting disconnected during read operation - what is your setup like?

**Comment by harshavardhana** [comment]
Closing this issue for the moment, since there are not enough details about the environment or anything else to go about. 

Feel free to add them we shall re-open.
