### ISSUE TITLE
Minio console Login issue

### ISSUE THREAD

**Issue by spbho** [minio/minio#13545]
## Expected Behavior

Should be able to Login console properly and it shouldn't go back to Login page again after login

## Current Behavior

Able to login to console after multiple attempts and after login upon selecting anything from console like buckets it is going back to Login page again

## Steps to Reproduce (for bugs)

I am using minio as a gateway and installing it as a helm chart using these files and rest of the files from helm
 https://github.com/minio/minio/blob/RELEASE.2021-10-13T00-23-17Z/helm/minio/templates/gateway-deployment.yaml
https://github.com/minio/minio/blob/RELEASE.2021-10-13T00-23-17Z/helm/minio/templates/console-service.yaml
Dockerfile- https://github.com/minio/minio/blob/RELEASE.2021-10-13T00-23-17Z/Dockerfile.dev

With Older version of Minio, I am able to login to browser properly but with console it is not working as expected. I want to understand if any other configuration needs to be done. Couldn't find any issue in pod logs

## Context

I am trying to login to console properly, after trying with LoadBalancer service I want to test with ingress as with ingress I am unable to see login page also

## Your Environment

* Version used (`minio --version`): RELEASE.2021-10-13T00-23-17Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@spbho what gateway mode are you in?

**Comment by spbho** [comment]
It's nas

**Comment by harshavardhana** [comment]
> It's nas

@spbho so you have created users to login to console?

**Comment by spbho** [comment]
I have set default values
rootUser: ""
rootPassword: ""

**Comment by harshavardhana** [comment]
> I have set default values
> rootUser: ""
> rootPassword: ""

NOTE: you cannot have many gateway instances without using a centralized `etcd` for credential storage - this is why login will fail always. 

If you wish to have everything working make sure to setup etcd - or just deploy single gateway instance.

**Comment by spbho** [comment]
with LDAP details configured, while login through console I am getting Invalid Login error Bad request
Error: LDAP server error: LDAP auth failed for DN uid=,ou=,dc=,dc=: LDAP Result Code 49 "Invalid Credentials": Invalid Credentials (*fmt.wrapError)
       3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:595:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
       1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()

I have tested same details with older release RELEASE.2020-06-14T18-32-17Z, it is working fine

**Comment by harshavardhana** [comment]
> with LDAP details configured, while login through console I am getting Invalid Login error Bad request Error: LDAP server error: LDAP auth failed for DN uid=,ou=,dc=,dc=: LDAP Result Code 49 "Invalid Credentials": Invalid Credentials (*fmt.wrapError) 3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse() 2: cmd/sts-handlers.go:595:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity() 1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()

your LDAP auth is wrong @spbho - you need to configure etcd as well. 

> I have tested same details with older release RELEASE.2020-06-14T18-32-17Z, it is working fine

The older release doesn't support LDAP login through UI - you are using different credentials to login here so it's not the same.

You need to enable your LDAP setup to use Bind mode - https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/external-authentication-with-ad-ldap-identity-provider.html#minio-external-identity-management-ad-ldap check the documentation on how to do it.

**Comment by spbho** [comment]
I am able to login to console with LDAP details using Loadbalancerip. However to generate temporary credentials using those details while setting policy getting this error
./mc alias set minio http://Loadbalancerip:9000  LDAPusername LDAPpassword
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://LBIP:9000/probe-bucket-sign-axgi0vik4ba3/?location=": dial tcp LBIP:9000: connect: no route to host.
 ./mc alias set minio http://Loadbalancerip:serviceport LDAPusername LDAPpassword
mc: <ERROR> Unable to initialize new alias from the provided credentials. XML syntax error on line 1: element <link> closed by </head>.

minioAPIPort: "9000"
minioConsolePort: "9001"

Referring these :
https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/AssumeRoleWithLDAPIdentity.html#minio-sts-assumerolewithldapidentity
https://github.com/minio/minio/blob/master/docs/sts/ldap.md#sample-post-request
