### ISSUE TITLE
letsencrypt integration: What to do if the certificate chain and key are renewed?

### ISSUE THREAD

**Issue by harridu** [minio/minio#13549]
## Expected Behavior
The documentation on https://docs.min.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio.html should describe how to tell minio to use the new certificate and key on a renewal, without interrupting the service, of course. AFAICT it is not sufficient to put the new files in place.

**Comment by harshavardhana** [comment]
On baremetal setups MinIO will automatically reload them using inotify if the certs are changed in place.

If the certs are changed in k8s it rolls the pods anyways.
