### ISSUE TITLE
Policy evaluation logic: IAM Policy + PutBucketPolicy

### ISSUE THREAD

**Issue by pawelkuc** [minio/minio#13540]
I have the following 
* bucket tree defined:
```
my-minio
├─...
├─test1.0 // no bucket policy
├─test1.1 // no bucket policy 
├─test1.2 {with Bucket Policy: Deny Get Object}
├─test1.3 {with Bucket Policy: Allow Get Object}
├─test1.4 // no bucket policy
├─test1.5 {with Bucket Policy: Allow List Bucket}
├─...
```

* IAM Policies (Configuration: Console > Users > [username] > Policies > Assign Policies)
```
All buckets:
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:ListBucket","s3:GetBucketLocation"], "Resource":["arn:aws:s3:::*"]}]}			listBucket
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject"],                         "Resource":["arn:aws:s3:::*"]}]}			getObject
{"Version":"2012-10-17","Statement":[{"Effect":"Deny", "Action":["s3:GetObject"],                         "Resource":["arn:aws:s3:::*"]}]}			getObject_deny

bucket specific:
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetBucketLocation","s3:ListBucket"], "Resource":["arn:aws:s3:::test1.0"]}]}	listBucket_allow_test10
{"Version":"2012-10-17","Statement":[{"Effect":"Deny", "Action":["s3:ListBucket"],                        "Resource":["arn:aws:s3:::test1.0"]}]}	listBucket_deny_test10

bucket specific:
{"Version":"2012-10-17","Statement":[{"Effect":"Deny", "Action":["s3:GetObject"],                         "Resource":["arn:aws:s3:::test1.0/*"]}]}	getObject_deny_test10
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject"],                         "Resource":["arn:aws:s3:::test1.1/*"]}]}  getObject_allow_test11
```

* Bucket Policies (Configuration: minio-go > `SetBucketPolicy(ctx, bucketName, policy1)` )
```
bucket's content
{"Version":"2012-10-17","Statement":[{"Effect": "Deny", "Action":["s3:GetObject"],                        "Principal": {"AWS": ["*"]},"Resource": ["arn:aws:s3:::test1.2/*"],"Sid": ""}]}`
{"Version":"2012-10-17","Statement":[{"Effect": "Allow","Action":["s3:GetObject"],                        "Principal": {"AWS": ["*"]},"Resource": ["arn:aws:s3:::test1.3/*"],"Sid": ""}]}`

bucket:
{"Version":"2012-10-17","Statement":[{"Effect": "Allow","Action":["s3:ListBucket","s3:GetBucketLocation"],"Principal": {"AWS": ["*"]},"Resource": ["arn:aws:s3:::test1.5"],"Sid": ""}]}`
```

### My Policy evaluation logic test results:
1. For the scenario when the Bucket Policy is not involved (i.e. buckets test1.0, 1.1, 1.4) everything works as expected.
2. For the Bucket Policy cases (i.e. buckets 1.2, 1.3) I have some unexpected results. For example (2nd case in my table) I have `ListBucket` and `GetBacket` set to `Allow` for all (* wildcard) and the Bucket Policy (minio-go > `SetBucketPolicy(ctx, bucketName, policy1)`) `GetObject` for test1.2 to `Deny` and for test1.3 to `Allow`. I would expect `GetObject` Deny for test1.2 as the final result but I see Allow. Generally it looks like the Bucket Policy settings doesn't affect the final result (ref. other cases from my test). Maybe I am missing something here?
![minio-policies_boolean-algebra](https://user-images.githubusercontent.com/30234110/139439937-6e32298d-4ebf-434a-aa0d-dc5c141ea948.png)

## Expected Behavior
The resulting permissions are the total permissions of the two types: IAM Policy + Bucket Policy

## Current Behavior
It looks like the Bucket Policy settings doesn't affect the final result at all.

## Possible Solution
I don't know

## Steps to Reproduce (for bugs)

1. Create IAM Policy called `listBucket`:
```
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:ListBucket","s3:GetBucketLocation"], "Resource":["arn:aws:s3:::*"]}]}
```
2. Create IAM Policy called `getObject`:
```
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::*"]}]}
```
3. Assign those policies to a test user. 
4. create some buckets. e.g. test1.0, test1.2, test1.3. Put some content inside.
5. Apply Bucket Policy (Deny to GetObject) to test1.2 using this code https://github.com/minio/minio-go/blob/master/examples/s3/setbucketpolicy.go, using:
```
policy := `{"Version": "2012-10-17","Statement": [{"Action": ["s3:GetObject"],"Effect": "Deny","Principal": {"AWS": ["*"]},"Resource": ["arn:aws:s3:::test1.2/*"],"Sid": ""}]}
```
6. Login as the test user (Console)
7. Try to download something from test1.2. We should have Deny here but you can easily download anything you like.  

## Context
security issue

## Regression
I don't know

## Your Environment

* Version used (`minio --version`): RELEASE.2021-10-23T03-28-24Z
* Server setup and configuration: local test environment, Docker Desktop for Windows 10 (WSL2), Kubernetes
* Operating System and version (`uname -a`): Windows 10 Pro x64 19043.1288 + WSL2

**Comment by harshavardhana** [comment]
@pawelkuc Bucket policies only get applied for anonymous requests.

IAM policies affect all authenticated requests.

Bucket policies do not get applied to authenticated requests.
