### ISSUE TITLE
Multi cluster Replication - LDAP integrated

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13557]
Hi Team,

I want to implement replication  for Multi cluster Minio(Located in different Locations) & LDAP Integrated on both clusters.

Can you please guide how to implement replication on LDAP integrated Minio clusters.
./mc admin replicate add backup1 backup2 --insecure                                                             mc: <ERROR> Unable to add sites for replication. This 'admin' API is not supported by server in 'mode-server-distributed-xl'

Note: these policies to both clusters. tried to apply the attached polices to LDAP user But at a time only one policy is applying.

**Comment by harshavardhana** [comment]
> ./mc admin replicate add backup1 backup2 --insecure mc: Unable to add sites for replication. This 'admin' API is not supported by server in 'mode-server-distributed-xl'

As mentioned here the API is only available in MinIO distributed setup

**Comment by Bhagi33** [comment]
Hi Harshavardhana,

I have deployed 2 minio Tenants (Operator available), As per the helm chart values.yaml if we provide servers>=4 means distributed. I assumed my deployed teanant is running in Distributed mode.
Can you please clear this doubt and help me to setup replication between 2 LDAP integrated Minio clusters

**Comment by Bhagi33** [comment]
can you please respond and dont close the issues immediately.
