### ISSUE TITLE
Status code 304 should not be an error code

### ISSUE THREAD

**Issue by TestMsr** [minio/minio#13560]
https://github.com/minio/minio/blob/caadcc3ed82be3276a338fb01d6e9b0390fc5097/cmd/http-stats.go#L189-L196

it's a common code while browser send request with if-not-modified-since header
## Possible Solution

add case for 304

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
Rather, 3xx response codes should not be in error category: https://github.com/minio/minio/blob/caadcc3ed82be3276a338fb01d6e9b0390fc5097/cmd/http-stats.go#L182
