### ISSUE TITLE
user provisioning with external identity

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#13569]
**Is your feature request related to a problem? Please describe.**

When configuring the`identity_openid` IdP provider for Minio, I can no longer manage policy assignments to users and groups using `mc` or the Minio Console.

**Describe the solution you'd like**

- Minio should optionally accept a group claim in place of a policy claim. When a group claim is provided, the corresponding minio group is used to manage the users policy assignment(s). This provides independence between the IdP and details of what policies are implemented in minio.

- Minio should optionally be able to provision users from SSO logins. That is, minio internal users are created just-in-time on first-time SSO logins. This would allow minio admins to alter the policies directly on individual users after they have been granted minio access by the IdP admins.

**Describe alternatives you've considered**
none

**Additional context**
In a corporate setting the IdP is managed by a security team.  While the SSO gained using the corporate IdP is a convenience, outsourcing policy assignments to an external team pretty much kills the feature.

**Comment by harshavardhana** [comment]
This is being implemented by allowing a mapping for client_id to a set of policies to be controlled by the admin, allowing for policies that can be presented for each client_id. 

And single deployment also can support multiple IDP endpoints as well in this process. 

This is a work in progress.

**Comment by chrisbecke** [comment]
Good to hear there is work on this.
At the moment, enabling an IdP disables the regular logins. If multiple IdPs are going to be supported, does that imply the regular logins will (optionally) be available in parallel?

**Comment by harshavardhana** [comment]
> At the moment, enabling an IdP disables the regular logins. If multiple IdPs are going to be supported, does that imply the regular logins will (optionally) be available in parallel?

It is in theory possible to do those as well but that is not what we are planning right now. What I meant by multiple IDPs means multiple endpoints for OpenID.

**Comment by harshavardhana** [comment]
This is merged as part of https://github.com/minio/minio/pull/13651

**Comment by harshavardhana** [comment]
#14223 allows for policy assignments directly to the provider - NOTE: Caveat is console UI logins are not yet supported which will eventually be implemented. 

Closing this issue as fixed from MinIO's API point of view.
