### ISSUE TITLE
Rate limiting cannot be disabled

### ISSUE THREAD

**Issue by rluetzner** [minio/minio#13561]
## Expected Behavior

As mentioned [here](https://github.com/minio/minio/blob/master/docs/throttle/README.md) it should be possible to deactivate rate limiting.

> NOTE: A zero value of requests_max means unlimited and that is the default **behavior.**

## Current Behavior

I've added logging to look at the actual value used and realized that the following line of code will prevent the desired behavior. 

init() in handler-api.go:66

```golang
if cfg.RequestsMax <= 0 {
		[...]
	} else {
		[...]
	}
```

## Possible Solution

If I understand correctly the above code should say `<` instead of `<=`, but I don't know how this will affect the following code initializing the `requestsPool`. Going by related code pieces (e.g. getRequestsPool()) `requestsPool` should be `nil` when not using any rate limiting.

## Steps to Reproduce (for bugs)

 Reproduction is trivial. Just look at the state of the `globalAPIConfig` fields after starting MinIO.

## Context

We received an error message about rate limiting and went investigating, because we never configured such a thing.

## Regression

This might be a regression, I don't know.

I went back in `git log` for a while, but couldn't find out if this ever worked.

## Your Environment

* Version used (`minio --version`): issue is present on the current master branch
* Server setup and configuration: unimportant
* Operating System and version (`uname -a`): Linux IT-FR-NB-RS-19 5.10.16.3-microsoft-standard-WSL2 Nr.1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
> As mentioned [here](https://github.com/minio/minio/blob/master/docs/throttle/README.md) it should be possible to deactivate rate limiting.
> 
> > NOTE: A zero value of requests_max means unlimited and that is the default **behavior.**

The documentation needs to be updated. The expected behavior is that we still limit the number of requests to avoid out-of-memory crash.

**Comment by harshavardhana** [comment]
> > As mentioned [here](https://github.com/minio/minio/blob/master/docs/throttle/README.md) it should be possible to deactivate rate limiting.
> > > NOTE: A zero value of requests_max means unlimited and that is the default **behavior.**
> 
> The documentation needs to be updated. The expected behavior is that we still limit the number of requests to avoid out-of-memory crash.

Yes @vadmeste
