### ISSUE TITLE
Unable to set notify_elasticsearch

### ISSUE THREAD

**Issue by roeelavi** [minio/minio#13572]
Trying to set notify_elasticsearch and getting an Error "mc: <ERROR> Unable to set 'notify_elasticsearch:primary url="https://elasticserver:9200" index="tst-minio-logs" username="logstashwriter" password="P@ssw0rd" format="namespace"' to server: not connected to server/service."
## Expected Behavior
mc admin config set minio notify_elasticsearch:primary url="https://elasticserver:9200" index="tst-minio-logs" username="logstashwriter" password="P@ssw0rd" format="namespace"
successfully set.....

## Your Environment
The minio server has four disks on it. and both client and server can comunicate with elasticserver using "curl https://elasticserver:9200"
minio version 2021-06-17T00:10:46Z

**Comment by mshanmu** [comment]
@roeelavi , This error indicates minio pod cannot reach the https://elasticserver:9200. So, check whether you can reach https://elasticserver:9200 from one of the pods

**Comment by roeelavi** [comment]
it could be that the container does not recognize the host trusted rootCA. i will try it.

**Comment by harshavardhana** [comment]
> Trying to set notify_elasticsearch and getting an Error "mc: Unable to set 'notify_elasticsearch:primary url="https://elasticserver:9200" index="tst-minio-logs" username="logstashwriter" password="P@ssw0rd" format="namespace"' to server: not connected to server/service."
> 
> ## Expected Behavior
> mc admin config set minio notify_elasticsearch:primary url="https://elasticserver:9200" index="tst-minio-logs" username="logstashwriter" password="P@ssw0rd" format="namespace" successfully set.....
> 
> ## Your Environment
> The minio server has four disks on it. and both client and server can comunicate with elasticserver using "curl https://elasticserver:9200" minio version 2021-06-17T00:10:46Z

Make sure your endpoint is reachable.
