### ISSUE TITLE
[hdfs-gateway] "fatal error: concurrent map writes" after updating to latest Minio

### ISSUE THREAD

**Issue by danochoa** [minio/minio#13587]
Running Minio in hdfs gateway mode crashes with `fatal error: concurrent map writes` when listing files in certain directories. And the client gets `mc: <ERROR> Unable to list folder. Server not initialized, please try again.`. It's consistent on a handful of directories but I haven't found a pattern among them. The issue seems to have started after [minio.RELEASE.2021-03-04T00-53-13Z](https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-03-04T00-53-13Z) . This problem did not exist in earlier versions.

## Expected Behavior

`mc ls local/directory-x/` should list files for any/all directories.

## Current Behavior
`mc ls local/directory-x/` fails for certain directories.

## Possible Solution
I don't have a solution but maybe some helpful info. I tested a bunch of versions and the last working version was [minio.RELEASE.2021-03-04T00-53-13Z](https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-03-04T00-53-13Z). Anything after that fails with the same error message.

## Steps to Reproduce (for bugs)
1. Run Minio server version `RELEASE.2021-03-04T00-53-13Z`.
2.  List files.
```
$ mc ls local/directory-1/
[2021-11-05 00:37:19 CDT]     0B subdir1/
[2021-11-05 00:37:19 CDT]     0B subdir2/
```
3. Update to Minio server version `RELEASE.2021-11-03T03-36-36Z`.
4. List files.
```
$ mc ls local/directory-1/
mc: <ERROR> Unable to list folder. Server not initialized, please try again.
```
5. Inspect Minio server logs:
```
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: fatal error: concurrent map writes
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: fatal error: concurrent map writes
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: goroutine 479 [running]:
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: runtime.throw({0x2d16a88, 0x2622acf})
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: runtime/panic.go:1198 +0x71 fp=0xc000033440 sp=0xc000033410 pc=0x435851
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: runtime.mapdelete_faststr(0x28e4740, 0xc000242ae0, {0xc000f0f800, 0xb7})
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: runtime/map_faststr.go:385 +0x135 fp=0xc0000334a0 sp=0xc000033440 pc=0x412f95
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: github.com/minio/minio/cmd/gateway/hdfs.(*hdfsObjects).ListObjects.func1({_, _}, {_, _}, {_, _})
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: github.com/minio/minio/cmd/gateway/hdfs/gateway-hdfs.go:455 +0x2b7 fp=0xc0000339d8 sp=0xc0000334a0 pc=0x2622757
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: github.com/minio/minio/cmd.listObjects.func2()
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: github.com/minio/minio/cmd/object-api-common.go:325 +0x136 fp=0xc000033f28 sp=0xc0000339d8 pc=0x23fcd36
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: github.com/minio/minio/internal/sync/errgroup.(*Group).Go.func1()
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: github.com/minio/minio/internal/sync/errgroup/errgroup.go:123 +0x1cb fp=0xc000033fe0 sp=0xc000033f28 pc=0xfcff2b
Nov 05 05:12:14 ip-10-10-10-10.prod.org1.comus-west-1.compute.internal minio[3503]: runtime.goexit()
```
HTTP trace logs didn't seem helpful.

## Context
I attempted to upgrade to the latest Minio server version and started having this issue. I ended up having to revert to an older version for now.

## Your Environment
* Operating System and version (`uname -a`):
`Linux hostname 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by danochoa** [comment]
I did some more testing by building Minio from source based on commits after RELEASE.2021-03-04T00-53-13Z. Last working build was at commit 097e5eba9fc7d69958c197db1f9b346cbc88f7d2. The bug seems to be introduced in commit 3ff5f55dcbba1ae05893cee1ffe9e1500248d9c1.

**Comment by klauspost** [comment]
[ListObjects](https://github.com/minio/minio/blob/421160631a025fb09f771563c117cd1544bbef44/cmd/gateway/hdfs/gateway-hdfs.go#L409) is the problem, it concurrently read/writes to the map. Since `populateDirectoryListing` also modifies the map the solution isn't trivial, except a wide mutex, including when `populateDirectoryListing` is called.

Basically the entire `getObjectInfo` should be mutex locked.
