### ISSUE TITLE
STS access does not work after migrating to RELEASE.2021-11-03T03-36-36Z

### ISSUE THREAD

**Issue by fcomte** [minio/minio#13589]
I just migrate to RELEASE.2021-11-03T03-36-36Z
STS token can be generate but all access are forbidden.
My policy is the same as before but it seems that the generated account have no policy mapped to it

**Comment by vadmeste** [comment]
@fcomte can you provide more information ? 
1. Older version that you were using
2. What's the exact error that you are seeing
3. Any suspicious log after upgrading ?
4. What type of deployment is this ? (distributed erasure setup ?)

**Comment by fcomte** [comment]
- I were using : RELEASE.2021-10-02T16-31-05Z
- There is no error except : an access denied to any resources
- It is deployed with the last version of the kubernetes
- It's a distributed setup : 4 servers and 18 disks each server.

**Comment by vadmeste** [comment]
Any logs ? Can you paste it here ?

**Comment by fcomte** [comment]
an mc admin trace on the minio server : 

```
2021-11-05T14:29:51:000 [403 Forbidden] s3.ListBuckets minio-datanode-pool-0-0.minio-datanode-hl.minio-datanode.svc.cluster.local:9000/ 192.168.253.166    262µs       ↑ 217 B ↓ 549 B
```

on the client side with mc configured with

```
coder@vscode-236578-68c478dcbc-jrbkq:~/work$ mc ls s3
mc: Configuration written to `/home/coder/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/home/coder/.mc/share`.
mc: Initialized share uploads `/home/coder/.mc/share/uploads.json` file.
mc: Initialized share downloads `/home/coder/.mc/share/downloads.json` file.
mc: <ERROR> Unable to list folder. Access Denied.
```

**Comment by fcomte** [comment]
This is the session token, it has the claim policy :

```
{
  "accessKey": "M4I4DTCZDR15PK4VC0YK",
...
  "policy": "stsonly",
...
}
```

And i have this policy on the server side :
```
coder@vscode-402831-6695cf4854-xkffc:~/work$ mc admin policy list minio
projet-methodo-ipc  
readonly            
writeonly           
...
stsonly
```

**Comment by vadmeste** [comment]
@fcomte can you paste `mc admin policy info minio stsonly` ?

**Comment by fcomte** [comment]
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:ListBucket"
   ],
   "Resource": [
    "arn:aws:s3:::donnees"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::donnees/*"
   ]
  }
 ]
}
```

**Comment by fcomte** [comment]
```
coder@vscode-402831-6695cf4854-xkffc:~/work$ mc ls minio/donnees
[2021-11-05 15:54:37 UTC]     0B BPE/
[2021-11-05 15:54:37 UTC]     0B ESTEL/
[2021-11-05 15:54:37 UTC]     0B ETAT_CIVIL/
[2021-11-05 15:54:37 UTC]     0B FILOSOFI/
[2021-11-05 15:54:37 UTC]     0B GEOGRAPHIE/
[2021-11-05 15:54:37 UTC]     0B RP/
```

of course with a admin account i can see this bucket

**Comment by vadmeste** [comment]
@fcomte you need `s3:ListAllMyBuckets` for this ` [403 Forbidden] s3.ListBuckets minio`

**Comment by olevitt** [comment]
Hi,

I work with @fcomte, we just tried adding 
```
{
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
```
to the stsonly policy, with no success, still having `mc: <ERROR> Unable to list folder. Access Denied`
Note that the policy was working just fine in `RELEASE.2021-10-02T16-31-05Z`, without the "listAllMyBuckets" action.  
I believe this issue should stay open.

We will work on making a reproductible example and narrow down which version, if any, has the regression / change.

In the meantime, I suggest we reopen this issue

**Comment by harshavardhana** [comment]
you need to move to `RELEASE.2021-11-05T09-16-26Z`  it was fixed specifically here. 

```
commit 112f9ae0875f608e234f88ce2f307362ce2d7240
```

The issue was upstream JWT library broke their API
