### ISSUE TITLE
Add systemd Version Note to minio-service Documentation

### ISSUE THREAD

**Issue by utkonos** [minio/minio#13598]
## Expected Behavior
Running service using the systemd script.

## Current Behavior
Script exits with an error:
```
systemd[1]: /etc/systemd/system/minio.service:13: Unknown key name 'ProtectProc' in section 'Service', ignoring.
```

## Possible Solution
Add a note to the readme or documentation stating the version of systemd that the startup script requires based on its syntax.

## Steps to Reproduce (for bugs)
1. Start with Ubuntu 20.04 LTS
2. `wget https://dl.min.io/server/minio/release/linux-amd64/minio_20211105091626.0.0_amd64.deb`
3. `dpkg -i minio_20211105091626.0.0_amd64.deb`
4. `service minio status`

## Context
There is one line in the systemd startup script which sets `ProtectProc=invisible`. This is documented here:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectProc=

However, this feature was only added to systemd in a recent release:
https://github.com/systemd/systemd/blob/5df64f148dfbf058187e042259830df6edf84388/NEWS#L1379

I suggest a note be added to the readme or documentation somewhere that notes the above. This way users don't need to track down what the error is and what it means if they are using a long term service version of Ubuntu (the common best practice for production systems).

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-11-05T09-16-26Z
* Server setup and configuration: Fresh install of Ubuntu 20.04.3 LTS
* Operating System and version (`uname -a`): `Linux minio 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Feel free to send a fix @utkonos

**Comment by utkonos** [comment]
For many independenly funded open source projects, I would. But you all charge $1000 a month for the paid version of this software. Fix it yourself.

**Comment by harshavardhana** [comment]
> ```
> systemd[1]: /etc/systemd/system/minio.service:13: Unknown key name 'ProtectProc' in section 'Service', ignoring.
> ```

this doesn't exit it says "ignoring" and the service actually starts. 

```
~ wget https://dl.min.io/server/minio/release/linux-amd64/minio_20211105091626.0.0_amd64.deb
--2021-11-07 09:19:44--  https://dl.min.io/server/minio/release/linux-amd64/minio_20211105091626.0.0_amd64.deb
Resolving dl.min.io (dl.min.io)... 178.128.69.202
Connecting to dl.min.io (dl.min.io)|178.128.69.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27588938 (26M) [application/x-debian-package]
Saving to: ‘minio_20211105091626.0.0_amd64.deb’

minio_20211105091626.0.0_amd6 100%[===============================================>]  26.31M  1.36MB/s    in 6.2s    

2021-11-07 09:19:51 (4.25 MB/s) - ‘minio_20211105091626.0.0_amd64.deb’ saved [27588938/27588938]

~ sudo dpkg -i minio_20211105091626.0.0_amd64.deb
[sudo] password for harsha: 
Selecting previously unselected package minio.
(Reading database ... 279483 files and directories currently installed.)
Preparing to unpack minio_20211105091626.0.0_amd64.deb ...
Unpacking minio (20211105091626.0.0) ...
Setting up minio (20211105091626.0.0) ...

~ sudo emacs /etc/default/minio
MINIO_VOLUMES="/tmp/data"

~ sudo adduser minio-user

~ sudo service minio start

~  sudo service minio status
● minio.service - MinIO
     Loaded: loaded (/etc/systemd/system/minio.service; disabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-11-07 09:21:17 PST; 1min 55s ago
       Docs: https://docs.min.io
    Process: 1534424 ExecStartPre=/bin/bash -c if [ -z "${MINIO_VOLUMES}" ]; then echo "Variable MINIO_VOLUMES not set in /etc/default/minio"; exit 1; fi (code=exited, status=0/SUCCESS)
   Main PID: 1534425 (minio)
      Tasks: 13
     Memory: 52.0M
     CGroup: /system.slice/minio.service
             └─1534425 /usr/local/bin/minio server /tmp/data
```

This is not an issue - systemd happily ignores that which it doesn't understand.
