### ISSUE TITLE
Active active replication configuration error

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13590]
Hi Team,

I have deployed 2 tenants in different namespace
Want to implement active active bucket replication. but facing with error  even remote server is up and bucket is available.

Please quick help is needed

services up and running on both clusters is available and its up

**Comment by klauspost** [comment]
The error is described. Your certificates are not correct. There is no `insecure` mode for replication, so you need those set up correctly to use TLS.

**Comment by Bhagi33** [comment]
Ok. But i am using minio's inbuilt certificates only..  PLease let me know how to fix this with certificates.

**Comment by harshavardhana** [comment]
> Ok. But i am using minio's inbuilt certificates only.. PLease let me know how to fix this with certificates.

You are using direct IPs you need to use ingress domains for setting up replication.  TLS certs are generated for your DNS names in your deployment not for IPs.

**Comment by Bhagi33** [comment]
thanks @harshavardhana 
Can you help me on this.
I have one query, i have configured/tested active active replication its working successfully but without SSL.
how to trust certificate between two minio cluster 1 & minio cluster2(tenants).As i was not able to mount volume & volumemounts into the tenant[taught to create a cm for the certificate to be trusted and mount that cm to the tenant]
Ex:
volumeMounts:
        - name: trust-public-cert
          mountPath: /etc/ssl/certs/public.crt
volumes:
      - name: trust-public-cert
        configMap:
          name: trust-cert
