### ISSUE TITLE
Minio console doesn't work well with STS account

### ISSUE THREAD

**Issue by fcomte** [minio/minio#13608]
I have wrong assertion of the user permission from the minio console : 

![image](https://user-images.githubusercontent.com/48868412/140772495-9a0a1ddf-c13d-49b7-bacb-b126452162e3.png)

When 
## Expected Behavior
Both permission for those two buckets for the user tm8enk

## Current Behavior

I have two kinds of rule on my policy for STS users : 

The user bucket based on a jwt claim : 
```
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::${jwt:preferred_username}",
     "arn:aws:s3:::${jwt:preferred_username}/*"
    ]
   },
```

Some static groups : 

```
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::projet-test-fred",
     "arn:aws:s3:::projet-test-fred/*"
    ],
    "Condition": {
     "StringEquals": {
      "jwt:preferred_username": [
       "tm8enk"
      ]
     }
    }
   }
```

## Your Environment
It's the last minio image : RELEASE.2021-11-05T09-16-26Z
and it seems to be a regression because in version RELEASE.2021-10-02T16-31-05Z everything was good.

**Comment by vadmeste** [comment]
@fcomte can you explain more what's wrong here ? I am not able to figure it out from the issue description.

**Comment by fcomte** [comment]
For my bucket  "tm8enk" there is no manage button.. 
And If I go inside the bucket i can't upload data

![image](https://user-images.githubusercontent.com/48868412/140776819-dfce9a52-4939-4697-ac9f-cec9a53bd673.png)

**Comment by vadmeste** [comment]
@fcomte and your sts user has one policy document with two rules that you pasted above ?

**Comment by fcomte** [comment]
yes , in fact i have a lot of others : one for each static groups ( at least ten rules for static groups )

**Comment by harshavardhana** [comment]
This is because of some policy refactor on the console UI https://github.com/minio/console/pull/1162 @vadmeste

**Comment by harshavardhana** [comment]
>    {
>     "Effect": "Allow",
>     "Action": [
>      "s3:*"
>     ],
>     "Resource": [
>      "arn:aws:s3:::projet-test-fred",
>      "arn:aws:s3:::projet-test-fred/*"
>     ],
>     "Condition": {
>      "StringEquals": {
>       "jwt:preferred_username": [
>        "tm8enk"
>       ]
>      }
>     }
>    }

This should be `${jwt:preferred_username}` are sure this is the correct policy?

**Comment by fcomte** [comment]
All my policy for static groups of users are without ${} and they all work well with both the console and the mc client.
I can try to switch the syntax but my problem is relative to the syntax : 

```
  {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::${jwt:preferred_username}",
     "arn:aws:s3:::${jwt:preferred_username}/*"
    ]
   }
```

this rule make my console really strange : The bucket is not manageable. Upload from the console are desactivated but everything is working well the API using the mc client
For example with the console when i list bucket and i look at the network exchange for the working bucket 'projet-test-fred' 
```
allowedActions: null
creation_date: "2021-09-13T15:44:00Z"
details: {quota: {}, versioning: true}
manage: true
```

but for the bucket 'tm8enk' which is my preferred username
```
allowedActions: null
creation_date: "2021-09-08T14:50:27Z"
details: {quota: {}}
name: "tm8enk"
objects: 209
rw_access: {read: true, write: true}
size: 8420706659
```

So you can see that there is no "manage: true" for this bucket

**Comment by harshavardhana** [comment]
@fcomte the issue is because console policy refactor is not catering for these variables from claims the way it should be handled because console lacks some amount of context on a few things.

If the console can extract the JWT claims and then apply them for policy evaluation properly it would work automatically IMO.

**Comment by harshavardhana** [comment]
Closing as duplicate of https://github.com/minio/console/issues/1209
