### ISSUE TITLE
Undocumented behaviour regression removing policies starting in RELEASE.2021-11-05T09-16-26Z

### ISSUE THREAD

**Issue by kevinlul** [minio/minio#13618]
## Expected Behavior

Prior to RELEASE.2021-11-05T09-16-26Z, policies could be removed regardless of whether they were applied, and they would be automatically removed from users and groups.

## Current Behavior

Since RELEASE.2021-11-05T09-16-26Z (RELEASE.2021-11-09T03-21-45Z is also affected), attempting to remove a policy that is applied returns an XMinioAdminPolicyInUse error. "The policy cannot be removed, as it is in use"

This change is not described in the [release notes](https://github.com/minio/minio/releases/tag/RELEASE.2021-11-05T09-16-26Z), which were not available most of the day of release.

## Possible Solution

Revert the regression or document the change. The releases are labelled as "bugfix releases", but this is a significant behaviour change.

## Steps to Reproduce (for bugs)

1. Start a standalone instance of MinIO.
2. Create a new user with `mc`.
3. Create a new policy with `mc`.
4. Assign the policy to the user with `mc`.
5. Attempt to remove the policy with `mc`.

## Context

Trying to not have existing code broken by undocumented changes in "bugfix releases".

## Regression

Yes, in RELEASE.2021-11-05T09-16-26Z

## Your Environment

* Version used (`minio --version`): RELEASE.2021-11-05T09-16-26Z, RELEASE.2021-11-09T03-21-45Z
* Server setup and configuration: Linux and Docker
* Operating System and version (`uname -a`): Ubuntu 20.04

**Comment by harshavardhana** [comment]
This is not undocumented this is an expected behavior change to comply with AWS S3 IAM behavior.

This is also not a significant behavior change meaning it was never supposed to work in that manner anyways. So it is a bugfix.

if you rely on it it means you were expecting something that you shouldn't expect in the first place. 

However will update release notes.
