### ISSUE TITLE
Empty response from minio API on Windows 2012 R2

### ISSUE THREAD

**Issue by chcoust** [minio/minio#13610]
Hello all, 

## Expected Behavior
I'm trying to host a minio instance on a Windows 2012 R2 server with latest binaries.
The "console" is running fine, but API doesnt seem to respond to requests.

## Current Behavior
After login to the working console
```
Invalid Login
Details
Post "http://10.0.3.113:9000/": EOF
```

http request to the API
```
λ wget http://127.0.0.1:9000 --verbose
--2021-11-08 13:56:28--  http://127.0.0.1:9000/
Connecting to 127.0.0.1:9000... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
```

I got no exceptions in logs, no errors/warnings in logs nor in Windows Events.
I can't find any related posts on Google matching my issue. 
May be related to certs ? or forced HTTP/2 protocol ?

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-11-05T09-16-26Z
* Server setup and configuration: 'old' OS, but working VM, Windows firewall OFF, no Antivirus running on the server.
* Operating System and version (`uname -a`): Windows 2012 R2, lastest Windows Update

**Comment by kannappanr** [comment]
@chcoust Maybe there is some sort of firewall that is blocking access to MinIO at port 9000

You can check that out by connecting to that ipaddress and port using telnet

```
 telnet <IPADDRESS> <PORT>
```

**Comment by chcoust** [comment]
@kannappanr Thanks for the hint.

Even if my firewall was off, i tried telneting the default 9000 port without minio running and it was hanging.

An old service on the server was already running on port 9000, but minio didnt tell me that on startup and still started.
I managed to find the old service with this PowerShell command :

`Get-Process -Id (Get-NetTCPConnection -LocalPort 9000).OwningProcess`

Starting minio on another port solved my issue.

Problem solved !
Thanks
