### ISSUE TITLE
Post "https://10.0.156.108:9000/": x509: cannot validate certificate for 10.0.156.108 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by n1vgabay** [minio/minio#13617]
I set TLS enabled.
Certs created in **cert-manager** and push to a secret in tls type with 3 keys.
**ca.crt**, **tls.crt**, **tls.key**
![image](https://user-images.githubusercontent.com/48561558/140933911-48a5db9e-f608-480e-b05d-b7f2794abdde.png)
![image](https://user-images.githubusercontent.com/48561558/140933956-03d0d375-f12d-4d69-893c-03f551fbc557.png)

## Expected Behavior
Expected is to login via my user name and password who's already worked before.
Just because I enabled TLS and assign it (Not sure if currcuetly) ,I need to be able to connect to Minio UI via the web browser.

## Current Behavior
It seems that minio accept this certificate, but when trying to connect it shows me the message of:
`Post "https://10.0.156.108:9000/": x509: cannot validate certificate for 10.0.156.108 because it doesn't contain any IP SANs`

## Possible Solution
Configure the TLS certificate to add somehow IP SAN's / rather pass the cert to different PATH of minio.
Now i'm assiging the certs via secret who includes the proper key as I described above.

## Context
I can't connect minio server using this tls cert created by cert-manager.

## Version used (`minio --version`): 
- RELEASE.2021-10-13T00-23-17Z
- Helm release chart
- standalone mode
## Server setup and configuration: 
- Terraform 1.0.7
- Kube version 1.19

**Comment by vadmeste** [comment]
`Post "https://10.0.156.108:9000/": x509: cannot validate certificate for 10.0.156.108 because it doesn't contain any IP SANs`

This means the generated certificate does not contain any IP address registered. You need to add `10.0.156.108` the cert-manager certificate resource or use any address registered in `dnsNames`

**Comment by n1vgabay** [comment]
@vadmeste 
Why I can connect to Minio GUI and not to server itself?
Is it because I could reach the console via https://localhost and not the actual server which is direct to another dns/ip address?

Can I direct this dns to be stable and not be changed every deploy?

**Comment by harshavardhana** [comment]
> Can I direct this dns to be stable and not be changed every deploy?

Yes this is correct deployment style.
