### ISSUE TITLE
MinIO is high cpu and slow put/get data when sync camera from client to minio

### ISSUE THREAD

**Issue by nhokit92** [minio/minio#13628]
When we sync camera with 100 stream concurrent from client to minio, then MinIO is high cpu and slow put/get data and client will show error timeout or tls handshake timeout 
## Expected Behavior

Minio fast with put/get data from client camera 
## Current Behavior

When we sync camera with 100 stream concurrent from client to minio, then MinIO is high cpu and slow put/get data and client will show error timeout or tls handshake timeout. We are using nginx proxy with ssl pass to upstream minio port 9000
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-09-03T03-56-13Z
* Server setup and configuration: Nginx proxy ssl pass to upstream minio port 9000
* Operating System and version (`uname -a`): Ubuntu 20

**Comment by klauspost** [comment]
Is MinIO or nginx handling TLS?

Start your upload. When CPU is starting to rise, execute:

`mc admin profile start --type=cpu,mem,goroutines MYMINIO && sleep 60 && mc admin profile stop MYMINIO` (replace MYMINIO with your alias.

Post the `profile.zip` it outputs here.

**Comment by nhokit92** [comment]
Hi Klauspost
We use nginx proxy pass through upstream minio local port 9002 and camera client connect direct to domain public in nginx proxy with ssl
[profile.zip](https://github.com/minio/minio/files/7513410/profile.zip)

**Comment by nhokit92** [comment]
precent peformance server, load average is high when compare with minio server normal 
![image](https://user-images.githubusercontent.com/32564944/141131292-3bc9045f-d605-42c0-9b81-dafdc074fb1f.png)

**Comment by harshavardhana** [comment]
> precent peformance server, load average is high when compare with minio server normal ![image](https://user-images.githubusercontent.com/32564944/141131292-3bc9045f-d605-42c0-9b81-dafdc074fb1f.png)

nginx is running on the same server as MinIO. This is a suboptimal configuration.

Also there is no real CPU usage here it's hardly anything is used here

**Comment by harshavardhana** [comment]
Most probably disks are slow here for 100 concurrent streams and not able to handle the load.

**Comment by klauspost** [comment]
No significant CPU usage inside MinIO. It is not your bottleneck.

**Comment by nhokit92** [comment]
> > precent peformance server, load average is high when compare with minio server normal ![image](https://user-images.githubusercontent.com/32564944/141131292-3bc9045f-d605-42c0-9b81-dafdc074fb1f.png)
> 
> nginx is running on the same server as MinIO. This is a suboptimal configuration.
> 
> Also there is no real CPU usage here it's hardly anything is used here

hi harshavardhana
so we should use nginx on other server unlinke minio for optimize ? 
this reason is disk I/O is slow ? can you help us explain, thanks so much

**Comment by nhokit92** [comment]
> No significant CPU usage inside MinIO. It is not your bottleneck.

Hi klauspost
this reason is disk I/O up/down slow ? can you help us find reason, thank so much

**Comment by harshavardhana** [comment]
> this reason is disk I/O is slow ? can you help us explain, thanks so much

System and architecture reviews are not part of community support @nhokit92 - you will have to perform some disk I/O operations and see if there are iowaits etc. Check how much network bandwidth is being used etc.

If this is critical deployment you are free to get subscription with us for more hands-on support https://min.io/pricing
