### ISSUE TITLE
How to start minio with nologin user

### ISSUE THREAD

**Issue by ideaviewes** [minio/minio#13625]
How to start minio with nologin user
I add the varible in /etc/profile
`
export MINIO_ROOT_USER=admin
export MINIO_ROOT_PASSWORD=123456
`
then /etc/source，

`
sudo -Hu www echo $MINIO_ROOT_USER
`
it echo admin
but I start minio with 
`
 sudo -Hu www /www/server/minio/minio server  --console-address 0.0.0.0:37536 /www/wwwroot/data &
`
the log 
WARNING: Detected default credentials 'minioadmin:minioadmin'

Is there any thinng wrong?

## Your Environment
OS:     CentOS Linux release 7.9.2009 (Core)
minio: RELEASE.2021-10-23T03-28-24Z

**Comment by harshavardhana** [comment]
> Is there any thinng wrong?

Yes you set env on your local shell and then you are using `sudo`  - sudo creates a new shell ENV and it not transferable from your current shell.

**Comment by ideaviewes** [comment]
@harshavardhana ，Thanks，I  also wrote a shell  minio.sh。
`
#!/bin/sh
export MINIO_ROOT_USER=admin

export MINIO_ROOT_PASSWORD=123456

nohup /www/server/minio/minio server  --console-address 0.0.0.0:37536 /www/wwwroot/data &
`
then 
`
sudo -Hu www sh minio.sh
`
the same problem, Could you please tell me the right way to do it？

**Comment by harshavardhana** [comment]
```
export MINIO_ROOT_PASSWORD=minio123
export MINIO_KMS_KES_CERT_FILE=/home/harsha/root.cert
export MINIO_KMS_KES_KEY_FILE=/home/harsha/root.key
export MINIO_ROOT_USER=minio
export MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373
export MINIO_KMS_KES_KEY_NAME=my-minio-key
export MINIO_KMS_AUTO_ENCRYPTION=on

minio server ~/test --console-address 0.0.0.0:37536
```

```
~ ~/run-fs.sh
API: http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                 
RootUser: minio 
RootPass: minio123 
SQS ARNs: arn:minio:sqs::1:kafka 

Console: http://0.0.0.0:37536 
RootUser: minio 
RootPass: minio123 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minio minio123

Documentation: https://docs.min.io
```

**Comment by ideaviewes** [comment]
Thank you，But the user www's shell is /sbin/nologin
It cant't run minio server ~/test --console-address 0.0.0.0:37536 directly，use sudo cause environment variables useless

**Comment by ideaviewes** [comment]
I got it finally
First wirte a mini.conf
vim /www/server/minio/minio.conf


MINIO_VOLUMES="/www/wwwroot/data"
MINIO_OPTS="-C /www/www/server/minio --address :9000 --console-address 0.0.0.0:37536"
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=123456


Second  write a  systemd shell

vim /etc/systemd/system/minio.service 

[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/www/server/minio/minio

[Service]
User=www
Group=www
EnvironmentFile=/www/server/minio/minio.conf
ExecStart=/www/server/minio/minio server $MINIO_OPTS $MINIO_VOLUMES
Restart=always
LimitNOFILE=65536
TimeoutStopSec=infinity
SendSIGKILL=no
[Install]
WantedBy=multi-user.target
