### ISSUE TITLE
A problem with changing the AES256 protocol for minio default object encryption

### ISSUE THREAD

**Issue by binnetwork** [minio/minio#13635]
Hello, as the title says, I want to change the default protocol AES256 for miniO object encryption. I checked the official document and found that it supports other encryption protocols such as AES-256-GCM and Chacha20-Poly1305, but I don't know how to change it. Is there an article about how to change it? If so, could you please give me a link? Thank you very much!

**Comment by harshavardhana** [comment]
You cannot change that - AES256 is the only supported encryption methodology for now following AWS S3 spec.

MinIO automatically chooses Chach20 or AES-GCM based on the processor instructions you do not have to do anything on your end.
