### ISSUE TITLE
Update error: dial tcp 127.0.1.1:443: connect: connection refused

### ISSUE THREAD

**Issue by THD-Thomas-Lang** [minio/minio#13639]
After upgrading to the most recent minio version the login to the website doesn´t work anymore.

Restoring a snapshot of an older version (2021-03) everything works.

Please find details on this stackoverflow question.
https://stackoverflow.com/questions/69924769/minio-dial-tcp-127-0-1-1443-connect-connection-refused

Environment:
- Current debian
- Current minio version
- Valid and signed certificate

**Comment by klauspost** [comment]
You are starting your server on port 9000, but you try to connect to port 443.

You are forcing the server url to be `https://fqdn.org`, but it should be `https://fqdn.org:9000`.
