### ISSUE TITLE
console login issue - minio s3 gateway for AWS S3

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13637]
Hi Team,
I want to deploy minio s3 gateway for AWS s3. While searching for the how to deploy this, i got doubts.
unders helm sections of minio/minio , i see values.yaml file mentioned that only nas gateway is supported.
1)but i want to go for the s3 gateway. what about S3 gateway. Please provide information.
2)how to install minio gateway s3 
3) i gone through this document. But its not clear for the beginners.https://docs.min.io/docs/minio-gateway-for-s3.html, 
![image](https://user-images.githubusercontent.com/68953135/141260796-bf448741-ef82-4379-a320-007e1e23a7bd.png)

**Comment by harshavardhana** [comment]
@Bhagi33 there are no plans to support S3 gateway on our helm charts - however, you can write your own deployment yaml.

**Comment by Bhagi33** [comment]
@harshavardhana 
I deployed minio s3 gateway aws successfully  minio console is not logging in. it doesnt say access denied/wrong,but simply credentials are taken and processed to login but its not logging in.

**Comment by boyka2405** [comment]
@harshavardhana - I am also facing the same issue. I am using bitnami/minio helm chart to deploy the minio as s3 gateway. Helm chart is installed correctly and I got below output

`NAME: minio
LAST DEPLOYED: Fri Nov 12 12:03:25 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: minio
CHART VERSION: 9.0.7
APP VERSION: 2021.11.9

** Please be patient while the chart is being deployed **
MinIO&reg; deployed as a S3 Gateway

MinIO&reg; can be accessed via port  on the following DNS name from within your cluster:

   minio.default.svc.cluster.local

To get your credentials run:

   export ROOT_USER=$(kubectl get secret --namespace default minio -o jsonpath="{.data.root-user}" | base64 --decode)
   export ROOT_PASSWORD=$(kubectl get secret --namespace default minio -o jsonpath="{.data.root-password}" | base64 --decode)

To connect to your MinIO&reg; server using a client:

- Run a MinIO&reg; Client pod and append the desired command (e.g. 'admin info'):

   kubectl run --namespace default minio-client \
     --rm --tty -i --restart='Never' \
     --env MINIO_SERVER_ROOT_USER=$ROOT_USER \
     --env MINIO_SERVER_ROOT_PASSWORD=$ROOT_PASSWORD \
     --env MINIO_SERVER_HOST=minio \
     --image docker.io/bitnami/minio-client:2021.11.5-debian-10-r3 -- admin info minio

To access the MinIO&reg; web UI:

- Get the MinIO&reg; URL:

   NOTE: It may take a few minutes for the LoadBalancer IP to be available.
         Watch the status with: 'kubectl get svc --namespace default -w minio'
   export SERVICE_IP=$(kubectl get svc --namespace default minio --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
   echo "MinIO&reg; web URL: http://$SERVICE_IP:9001/minio"
`

The console doesn't accept the credentials and there is no error in pod logs

**Comment by harshavardhana** [comment]
Gateway login was fixed in #13694 - to require full persistence please enable etcd.
