### ISSUE TITLE
minio's compress didn't work in windows server

### ISSUE THREAD

**Issue by wang1163619** [minio/minio#13656]
I uses the minio baremetal , and deploy it in my own windows server (windows server 2019).
just one disk.
everything is under control, all function is work well ,except the compression feature

## Expected Behavior
before you  uploading a picture,  the picrue size is 1,3M,  after uploading successfull ,  you should get the  picture' size is below the 1.3M , I think it is compress feature should be.

## Current Behavior
I upload a png type picture, which has been configed the configration the MINI type.
uploaded successfull , I got the picture size is 1.3M , the origining picture is 1.3 M.

## Possible Solution
may be, I don't know how to 'export MINIO_COMPRESS="on"' in windows server. 

I execute the following comand in powershell ,and restart the minio services, but I got the same result:
$env:MINIO_COMPRESS="on"
$env:MINIO_COMPRESS_EXTENSIONS=".png"
$env:MINIO_COMPRESS_MIMETYPES="image/png"

## Your Environment

* Curent Version is  RELEASE.2021-11-05T10-05-06Z
* Server setup and configuration:
* windows server 2019

**Comment by harshavardhana** [comment]
> may be, I don't know how to 'export MINIO_COMPRESS="on"' in windows server.

you need to do 

```
setx MINIO_COMPRESS "on"
```

In powershell

**Comment by wang1163619** [comment]
I execute the following comand in powershell ,and restart the minio services,  but I got the same result:
$env:MINIO_COMPRESS="on"
$env:MINIO_COMPRESS_EXTENSIONS=".png"
$env:MINIO_COMPRESS_MIMETYPES="image/png"

**Comment by kannappanr** [comment]
@wang1163619 I tried 
```
mc admin config set myminio compression enable="off" extensions="" mime_types=""
```

on Windows.
 Then copied a file of size 14,517,256 bytes to MinIO. I checked the size of the file in the backend and it was
```
11/14/2021  01:14 AM        14,420,880 ZoomInstaller.exe
               1 File(s)     14,420,880 bytes
```

**Comment by wang1163619** [comment]
@kannappanr 
Thank you for your quick reply,
the rate of the compress is so lower, how would I improve it ?

**Comment by harshavardhana** [comment]
> the rate of the compress is so lower, how would I improve it ?

you cannot compress an already compressed content.

**Comment by kannappanr** [comment]
for example, the same file, I simply did a zip on it.
```
>dir ZoomInstaller*
11/01/2020  10:41 AM        14,517,256 ZoomInstaller.exe
11/14/2021  08:10 PM        14,382,835 ZoomInstaller.zip
```
It is already a compressed object. Just like mentioned previously by Harsha, we cannot magically compress as the data is already compressed and randomized. The example was to just show that it works.
