### ISSUE TITLE
Alternative Backends: Tape Library Support (Related to #5582)

### ISSUE THREAD

**Issue by gpmidi** [minio/minio#13652]
**Is your feature request related to a problem? Please describe.**
Online storage is expensive. Many times cold storage is desirable such as for backup storage. 

**Describe the solution you'd like**
A way to offload storage of objects to tape. If a request is made for an object that's not otherwise available, then pull from tape. Ideally all objects would be read in from the tape on the same pass (not the whole tape, but that pass only, assuming LTO-like). As an intermediate giving tunables or scripts to allow the user to control what triggers a full vs single-point read would be ideal. This is mainly due to limited load/unload cycles, pass-limits, etc each tape has in its lifetime safe lifetime. 
I suspect implementing the hooks into the minio gateway and then having a separate "tape daemon" that handles the calls would be the way to go. 

**Describe alternatives you've considered**
* All cloud services (glacial, gcp options, etc) are 80%-90% more in cost PER MONTH than what tape costs me overall. 
* Ceph's RADIOS S3 gateway could be used to handle this by use of its operations intercept hooks. But that means Ceph. 

**Additional context**
I'm thinking of writing this fully or partially myself; this is mostly looking for information on what would be needed to get it merged into the main line. 

Someone also submitted #5582 a while back which is similar I think.

**Comment by klauspost** [comment]
@gpmidi We don't have any plans for this, and it doesn't seem likely we will go this direction, since it would be infeasible for an S3 API to work with this.

We offer transparent tiering to "slower", but tape is not feasible. It would require AWS Glacier interface, which would like be a separate product from MinIO.

If you have a commercial case for this, feel free to write `hello@minio.io` and we can discuss further there.

**Comment by gpmidi** [comment]
> We offer transparent tiering to "slower", but tape is not feasible. It would require AWS Glacier interface...

Why isn't it feasible? Seems to be quite a few options for this route to me. The only catch is providing a way to help tune access costs or outright refuse without an ok.

**Comment by harshavardhana** [comment]
> Why isn't it feasible? Seems to be quite a few options for this route to me. The only catch is providing a way to help tune access costs or outright refuse without an ok.

Feasibility is about the complexity involved in handling Tape systems - no natural filesystem-like interfaces - no libraries available to use with Go without some myriad dependencies and sort of incompatible implementations with various vendors.

Unless a tape vendor can provide us platform-independent libraries which are well maintained and usable.  We are yet to see something on these lines. 

We are not going to complicate our codebase at this point.

**Comment by wzrdtales** [comment]
> Unless a tape vendor can provide us platform-independent libraries which are well maintained and usable. We are yet to see something on these lines.

uuuuuh LTFS?
