### ISSUE TITLE
S3 gateway fails if s3_compatible_service_endpoint is specified with IAM EC2 role

### ISSUE THREAD

**Issue by kwikwag** [minio/minio#13668]
## Expected Behavior

Setting up MinIO for S3 gateway on an AWS VM with an IAM EC2 role setup for S3 should work with or without specifying an explicit S3 endpoint.

## Current Behavior

Works up to a certain version. Image `quay.io/minio/minio:RELEASE.2021-10-08T23-58-24Z` and beyond stopped working properly.

## Possible Solution

Either revert to the same functionality as earlier versions, or issue out a warning about this behavior change when an S3 endpoint is explicitly defined.

## Steps to Reproduce (for bugs)

1. Create an Ubuntu 20.04 AWS VM (e.g. in us-east-2) with an IAM EC2 role setup for S3 access to a bucket (e.g. `mybucket`). Install `docker-compose`, etc.
2. Create `docker-compose.yml` file as specified (see Files below; e.g. under `~/docker`). 
3. Create test directory and some files: `mkdir ~/test && cd ~/test && echo world > hello.txt && mkdir secrets && cd secrets && echo -n 123456789 > root_user && echo -n 123456789 > root_password`.
4. Set-up `mc`:  

```sh
alias mc="docker run --network host --rm -v ~/.mc:/root/.mc -v ~/test:/root/test quay.io/minio/mc"
mc alias set mys3 http://localhost:9000 $(cat ~/data/server/secrets/minio_access_key) $(cat ~/data/server/secrets/minio_secret_key)
```

5. Run `mc cp /root/test/hello.txt mys3/mybucket/hello.txt`. It will succeed.
6. Now, change `docker-compose.yml` so that image used is with the tag `RELEASE.2021-10-08T23-58-24Z` or a newer tag (up to and including `RELEASE.2021-11-09T03-21-45Z`). Re-run the above command. It will fail with "The AWS Access Key Id you provided does not exist in our records."
7. Finally, while still using tag `RELEASE.2021-10-08T23-58-24Z`, comment out the last arguments (the s3-compatible service endpoint `https://s3.us-east-2.amazonaws.com`). It will work.

## Context

While troubleshooting permissions to S3 I followed [advice](https://github.com/minio/minio/issues/8372) to specify the S3 endpoint explicitly. Little did I know that this crippled me because of the above regression bug. When I changed to an old version, it just worked. When trying to reproduce the bug in a minimal setup, I noticed that without the S3 endpoint it works just fine.

## Regression
Is this issue a regression? *Yes*
Functions as expected in `quay.io/minio/minio:RELEASE.2021-10-06T23-36-31Z`
Failed to work in `quay.io/minio/minio:RELEASE.2021-10-08T23-58-24Z` and most recently `RELEASE.2021-11-09T03-21-45Z`

## Your Environment

* Version used (`minio --version`): See Regression
* Server setup and configuration: AWS VM docker-compose with IAM role set up for EC2->S3 access.
* Operating System and version (`uname -a`): Ubuntu 20.04

### `docker-compose.yml`

```docker-compose
version: "3.7"
services:
  minio:
#    image: quay.io/minio/minio:RELEASE.2021-10-08T23-58-24Z
    image: quay.io/minio/minio:RELEASE.2021-10-06T23-36-31Z
    environment:
      - MINIO_ROOT_USER_FILE=/secrets/root_user
      - MINIO_ROOT_PASSWORD_FILE=/secrets/root_password
    ports:
      - "9000:9000"
    volumes:
      - ~/test/secrets:/secrets
    command:
      - gateway
      - s3
      - "https://s3.us-east-2.amazonaws.com"
```

**Comment by harshavardhana** [comment]
@kwikwag this is expected because we try to auto-probe the right set of credentials mechanism to use. 

Because of this we cannot support custom endpoints with chained credentials - you need to use https://s3.amazonaws.com - and make sure to have right set of permissions as documented here

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation"
             ],
             "Resource": [
                 "arn:aws:s3:::*"
             ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:HeadBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket",
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}
```

Using S3 region endpoints returns a different set of HTTP errors which we cannot use to deduce the correct credential mechanism to use with the backend.  My suggestion is to use the following policy with the right credential and it will work.

We may try to simplify in the future but for now, gateway is in codefreeze. Thanks

**Comment by kwikwag** [comment]
@harshavardhana Are you sure? As I mentioned:

    Functions as expected in quay.io/minio/minio:RELEASE.2021-10-06T23-36-31Z
    Failed to work in quay.io/minio/minio:RELEASE.2021-10-08T23-58-24Z and most recently RELEASE.2021-11-09T03-21-45Z
