### ISSUE TITLE
Improve handling of certificates stored as symlinks

### ISSUE THREAD

**Issue by balazsrunge** [minio/minio#13662]
Hi,

I would like to suggest the improvement of handling cetificates stored via symlinks:

**Is your feature request related to a problem? Please describe.**
If certificates are stored on the Minio pod under symlinks then those will be reloaded only once in 24 hours.
(Please see: https://github.com/aead/minio/blob/master/pkg/certs/certs.go, function watchSymlinks)
If the certificate's ttl (time to leave) is less then 24 hours, then Minio cannot be used until the certs will be reloaded.

**Describe the solution you'd like**
We implemented a workaround for it:
At startup certificates are copied to a directory which is configured as --certs-dir for Minio.
The script stores the md5sum of the certificates and if both public and private key is updated then it copies them to said directory.
In this way (not using symlinks) Minio almost immediately recognize the renewed certificates and reloads them.
The solution we would like to be implemented:
Check for the update of certificates given as symlinks continuously for example by storing and checking the contents of the old and new certs.
As soon as certs are renewed those should be reloaded like certificates stored directly in the --certs-dir (not as symlinks).

**Describe alternatives you've considered**
An alternative solution would be to make the time between certificate reloads from symlinks configurable.

Thanks,
Balazs Runge

**Comment by harshavardhana** [comment]
How do you handle reloads of certs from secret mounts to automatically populate? 

We can definitely add something - of SIGHUP like support that can reload certs as they are renewed.

Please show us the workaround that you currently implemented.

**Comment by balazsrunge** [comment]
Thanks harshavardhana for considering the change!

We are not reloading the certificates, Minio does it with the watch function (also in: https://github.com/aead/minio/blob/master/pkg/certs/certs.go), because our workaround copies the files under the symlinks to a location (not as symlinks) where those can be discovered via the watch function. 
We did not modified the Minio code rather we have a helper script implemented (/minio/certs is the directory where Minio search for the certificates): [certs_copy.txt](https://github.com/minio/minio/files/7545472/certs_copy.txt).
The script is started at pod startup.

**Comment by harshavardhana** [comment]
This is already fixed in minio/pkg#17
