### ISSUE TITLE
latest tag(11.09) dose not work well as previous version

### ISSUE THREAD

**Issue by HaoLiuHust** [minio/minio#13660]
I am using minio as gateway mode, with previous version, users can list object in a buckect, after upgrade to latest, it always timeout:
![image](https://user-images.githubusercontent.com/7233091/141762437-470588a4-16ac-4683-aadc-2c70df67895e.png)

**Comment by klauspost** [comment]
@HaoLiuHust Please provide the information requested in the issue form.

**Comment by harshavardhana** [comment]
duplicate of #13608
