### ISSUE TITLE
[XL] Bring transaction framework for healing/recovery of previous incomplete transactions. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1366]

**Comment by harshavardhana** [comment]
We need to re-evaluate on how we should implement this.

**Comment by GarimaKapoor** [comment]
@fwessels please update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
@harshavardhana can you add a few situations that need to be handled?

**Comment by harshavardhana** [comment]
> @harshavardhana can you add a few situations that need to be handled?

We are going to implement this along with disk based quorum for multi node setup
- A lock file i.e a hash or a directory hierarchy would be used. 
- This lock file is used as a consensus for quorum requirements
- This lock file also has journal information of previously failed transaction - for example a DeleteBucket ensued during a disk failure etc. This transaction information is used to rollback. 

A transaction lock + journal provides a way to provide consensus, rollback. This is a currently agreed design.

**Comment by krishnasrinivas** [comment]
Is the lock file a replacement for nsLock{}? if not what is it locking?

**Comment by harshavardhana** [comment]
> Is the lock file a replacement for nsLock{}? if not what is it locking?

Yes it is replacement for nsLock.

**Comment by harshavardhana** [comment]
Closing this github issue also as stale due to age. We can re-open when we plan in introducing this feature in future.
