### ISSUE TITLE
user specific SSL - in minio tenant -error

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13667]
Hi Team,
I have deployed minio operator in k8s. Now i deployed Tenant with external SSL(user created) with roorCA,intermediate CA .
I created the tls secret and added in tenant.
 externalCertSecret:
    - name: external-tls-ssl-minio
      type: kubernetes.io/tls
But facing this issue, Please can u help me

x509: certificate is valid for nsc-pass.minio.ericsson.com, not minio-pool-0-3.minio-hl.minio-ssl.svc.cluster.local

![image](https://user-images.githubusercontent.com/68953135/141946579-70ef239b-08f9-403c-8ea3-2ba86416c30b.png)

**Comment by harshavardhana** [comment]
Your certificates should be valid for the tenant headless service names @Bhagi33 as well to avail internode TLS.

You need to fix those read the error messages on the screen.

**Comment by Bhagi33** [comment]
do we need to create a certificate for this hostanme which is generated in side pod.
minio-pool-0-2.minio-hl.minio-ssl.svc.cluster.local 
DNS= *.minio-hl.*.svc.cluster.local
how to create wild card san for this. i tried creating certs with that DNS but its not accepting.
The request is INVALID.For SAN certificate requests, 

Please suggest how to . Dont close the issue immediately,

**Comment by harshavardhana** [comment]
> do we need to create a certificate for this hostanme which is generated in side pod. minio-pool-0-2.minio-hl.minio-ssl.svc.cluster.local DNS= _.minio-hl._.svc.cluster.local how to create wild card san for this. i tried creating certs with that DNS but its not accepting. The request is INVALID.For SAN certificate requests,
> 

It needs to be simply wildcard.

> minio-pool-0-2.minio-hl.minio-ssl.svc.cluster.local

Like 

> *.minio-hl.minio-ssl.svc.cluster.local

**Comment by Bhagi33** [comment]
thanks @harshavardhana 
I have one query, i have configured/tested active active replication its working successfully but without SSL.
how to trust certificate between two minio cluster 1 & minio cluster2(tenants).As i was not able to mount volume & volumemounts into the tenant[taught to create a cm for the certificate to be trusted and mount that cm to the tenant]
Ex:
volumeMounts:
        - name: trust-public-cert
          mountPath: /etc/ssl/certs/public.crt
volumes:
      - name: trust-public-cert
        configMap:
          name: trust-cert
