### ISSUE TITLE
Service user login only works while logged in in web console

### ISSUE THREAD

**Issue by bpedersen2** [minio/minio#13676]
## Expected Behavior
The service user should work regardless of the web console login

## Current Behavior
Log in web console as an IAM user (oidc) and create a service user.
Configure creditials for mc client
use mc client -> after IAM login expires (here  5min):

```
mc admin speedtest resiopc1 --size 1MiB 
mc: <ERROR> Failed to execute speedtest. The Access Key Id you provided does not exist in our records.
```

After logout/login in the web console  it works again for 5 min.

mc version:  RELEASE.2021-11-16T20-37-36Z
minio version: RELEASE.2021-11-09T03:21:45Z (docker)

**Comment by harshavardhana** [comment]
Are you using gateway?

**Comment by justinfenn** [comment]
I've also been seeing this in server mode with FS storage.  I _think_ it started happening somewhere between releases `RELEASE.2021-10-27T16-29-42Z` and `RELEASE.2021-11-05T09-16-26Z`.  I haven't been able to reliably reproduce the issue on a fresh instance, but I get the same behavior where logging in to the web console temporarily "fixes" service accounts until they become unrecognized again.

**Comment by bpedersen2** [comment]
> Are you using gateway?

No, this is a test instance running in docker:
```command: server --console-address ":9001" http://minio1/data{1...4}```

**Comment by harshavardhana** [comment]
> I've also been seeing this in server mode with FS storage. I _think_ it started happening somewhere between releases `RELEASE.2021-10-27T16-29-42Z` and `RELEASE.2021-11-05T09-16-26Z`. I haven't been able to reliably reproduce the issue on a fresh instance, but I get the same behavior where logging in to the web console temporarily "fixes" service accounts until they become unrecognized again.

@donatello ^^

**Comment by harshavardhana** [comment]
> I've also been seeing this in server mode with FS storage. I _think_ it started happening somewhere between releases `RELEASE.2021-10-27T16-29-42Z` and `RELEASE.2021-11-05T09-16-26Z`. I haven't been able to reliably reproduce the issue on a fresh instance, but I get the same behavior where logging in to the web console temporarily "fixes" service accounts until they become unrecognized again.

how are you running FS Mode? @justinfenn

**Comment by harshavardhana** [comment]
> `command: server --console-address ":9001" http://minio1/data{1...4}`

Looks like this is also a local setup with a wrong command line you are better off just using `/data{1...4}` there is no benefit in adding `http://minio1` for a local instance.

**Comment by justinfenn** [comment]
>how are you running FS Mode? @justinfenn

Running in docker with a command like `docker run --rm -v /path/to/vol:/data minio/minio:RELEASE.2021-11-09T03-21-45Z server /data --console-address :9090`.

**Comment by harshavardhana** [comment]
I can reproduce this - it's the policy mapping that is missing.

**Comment by harshavardhana** [comment]
> I can reproduce this - it's the policy mapping that is missing.

This only affects OpenID users.
