### ISSUE TITLE
Error: Storage resources are insufficient for the read operation .minio.sys/config/iam/policydb/sts-users/OWH17KFCTVOWWHJPDWYM.json (cmd.InsufficientReadQuorum)

### ISSUE THREAD

**Issue by beer1970** [minio/minio#13677]
## Expected Behavior
Harbor images are pushed to our k8s minio s3 buckets with write actions and pulled as read actions.

## Current Behavior
We are getting someteimes 500 errors read/write when pushing or pulling data from out minio environment in k8s cluster

API: SYSTEM
Time: 20:42:23:0
DeploymentID: 381a5c41-b0a8-4dfb-913c-36ee9999e20c
Error: Storage resources are insufficient for the read operation .minio.sys/config/iam/policydb/sts-users/OWH17KFCTVOWWHJPDWYM.json (cmd.InsufficientReadQuorum)
cmd/iam.go:333:cmd.(*IAMSys).watch()

API: SYSTEM
Time: 21:17:23:0
DeploymentID: 381a5c41-b0a8-4dfb-913c-36ee9999e20c
Error: Storage resources are insufficient for the read operation .minio.sys/config/iam/policydb/sts-users/OWH17KFCTVOWWHJPDWYM.json (cmd.InsufficientReadQuorum)
cmd/iam.go:333:cmd.(*IAMSys).watch()

API: SYSTEM
Time: 21:18:04:0
DeploymentID: 381a5c41-b0a8-4dfb-913c-36ee9999e20c
Error: Unable to update replication metadata for l12m-gitlab-artifacts-cicd-p-az1/tmp/uploads/1636983269-29-0545-8548-bc72cda45dfe1189a007f0906668d6db(3efc77ce-a844-47de-adc9-20e910ad1ebb): Storage resources are insufficient for the write operation / (*errors.errorString)
cmd/bucket-replication.go:454:cmd.replicateDelete()
cmd/bucket-replication.go:1375:cmd.(*ReplicationPool).AddExistingObjectReplicateWorker()

## Possible Solution
none found

## Steps to Reproduce (for bugs)
Difficult to reproduce as the errors are random, sometimes each few seconds and sometimes 10 minutes in between. 

## Context
The push image fails or the read from the bucket.

## Regression
No

## Your Environment
sh-4.4$ minio --version
minio version RELEASE.2021-11-09T03-21-45Z

**Comment by harshavardhana** [comment]
The errors look handpicked and not associated with any errors related to client.

Please paste all the relevant logs

**Comment by beer1970** [comment]
The error we see on the client pushing images to minio 

`Pushing image to harbor.cicd-p-az1.l12m.nl/base-images/build/consul-sidecar_ubi:1.10.2 
error pushing image: failed to push to destination harbor.cicd-p-az1.l12m.nl/base-images/build/consul-sidecar_ubi:1.10.2: PATCH https://harbor.cicd-p-az1.l12m.nl/v2/base-images/build/consul-sidecar_ubi/blobs/uploads/89132042-a307-41d0-b599-38a2d129954a?_state=REDACTED: UNKNOWN: unknown error; SerializationError: failed to decode S3 XML error response
	status code: 400, request id: , host id: 
caused by: expected element type <Error> but have <html>`

is not the same as which we see in minio logs except from the timing. not sure what you mean with hand picked? 

Error: Storage resources are insufficient for the read operation .minio.sys/config/iam/policydb/sts-users/OWH17KFCTVOWWHJPDWYM.json (cmd.InsufficientReadQuorum)

Can be coincidence and not related.

**Comment by harshavardhana** [comment]
> Pushing image to harbor.cicd-p-az1.l12m.nl/base-images/build/consul-sidecar_ubi:1.10.2 error pushing image: failed to push to destination harbor.cicd-p-az1.l12m.nl/base-images/build/consul-sidecar_ubi:1.10.2: PATCH https://harbor.cicd-p-az1.l12m.nl/v2/base-images/build/consul-sidecar_ubi/blobs/uploads/89132042-a307-41d0-b599-38a2d129954a?_state=REDACTED: UNKNOWN: unknown error; SerializationError: failed to decode S3 XML error response status code: 400, request id: , host id: caused by: expected element type <Error> but have <html>

this doesn't look like our error - we never return HTML errors @beer1970 looks like ingress is giving up here.

**Comment by harshavardhana** [comment]
> Error: Storage resources are insufficient for the read operation .minio.sys/config/iam/policydb/sts-users/OWH17KFCTVOWWHJPDWYM.json (cmd.InsufficientReadQuorum)

This has nothing to do with the issues you are seeing.

**Comment by beer1970** [comment]
Ok thanks for the quick respons. We will dive futher in the issues.
Do you know what causes the error Storage resources are insufficient for the read operation ? As we see a lot of them during the day?

**Comment by harshavardhana** [comment]
> Do you know what causes the error Storage resources are insufficient for the read operation ? As we see a lot of them during the day?

That happens because of network issues on the setup @beer1970

**Comment by beer1970** [comment]
For the setup we use minio-operator , do you mean with network issues on the setup a wrong settup in the minio-operator or setup in the network like with nfs or ingress? We are searching in the dark, any help is welcome

**Comment by harshavardhana** [comment]
> For the setup we use minio-operator , do you mean with network issues on the setup a wrong settup in the minio-operator or setup in the network like with nfs or ingress? We are searching in the dark, any help is welcome

The issue with harbor is your ingress has some limits that is returning an error.

There are other issues such as networking issues between nodes.

**Comment by harshavardhana** [comment]
> Pushing image to harbor.cicd-p-az1.l12m.nl/base-images/build/consul-sidecar_ubi:1.10.2 error pushing image: failed to push to destination harbor.cicd-p-az1.l12m.nl/base-images/build/consul-sidecar_ubi:1.10.2: PATCH https://harbor.cicd-p-az1.l12m.nl/v2/base-images/build/consul-sidecar_ubi/blobs/uploads/89132042-a307-41d0-b599-38a2d129954a?_state=REDACTED: UNKNOWN: unknown error; SerializationError: failed to decode S3 XML error response status code: 400, request id: , host id: caused by: expected element type <Error> but have <html>

For now, this failure is through your ingress, closing the issue. Don't think there is anything else we can do on our end.

**Comment by harshavardhana** [comment]
If you have nginx based ingress here make sure to have all the settings mentioned here to be in-place before uploading through `harbor` https://docs.min.io/docs/setup-nginx-proxy-with-minio.html

**Comment by beer1970** [comment]
@harshavardhana we needed the proxy_request_buffering setting set to off . This fixed our issue in harbor with minio through nginx.

**Comment by harshavardhana** [comment]
> @harshavardhana we needed the proxy_request_buffering setting set to off . This fixed our issue in harbor with minio through nginx. 

Yes these are already documented in our docs.
