### ISSUE TITLE
Resource policy not working listing objects in Minio console

### ISSUE THREAD

**Issue by AndreaTrevisan** [minio/minio#13684]
We have assigned a policy to a user to give read/write access to a specific bucket. After logging into minio console with this user browsing the specified bucket remains pending. If we change the same policy to allow access to all buckets the problem does not arise.
## Expected Behavior

GET http://{{domain}}/api/v1/buckets/schemabucket returns allowedActions: [ "s3:*" ] 
{access: "PRIVATE", allowedActions: [ "s3:*" ] , name: "schemabucket"}
## Current Behavior

GET http://{{domain}}/api/v1/buckets/schemabucket returns allowedActions: null 
{access: "PRIVATE", allowedActions: null, name: "schemabucket"}

## Steps to Reproduce (for bugs)

1. Create the bucket named schemabucket. 
2. Create the policy with the following json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::schemabucket"
            ]
        }
    ]
}
3. Assign the policy to a user
4. Log into minio console with the user
5. Browse the bucket schemabucket

## Context

Not admin users cannot access their resources
## Regression

Yes
## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-11-09T03-21-45Z
* Server setup and configuration: binary minio standalone mode
* Operating System and version (`uname -a`):  3.10.0-1160.25.1.el7.x86_64 Linux
![Screenshot (4)](https://user-images.githubusercontent.com/76003494/142410247-64a325a3-c128-4ab8-9970-d60004e49119.png)

**Comment by harshavardhana** [comment]
This is a duplicate problem https://github.com/minio/console/issues/1209
, fixed in console project https://github.com/minio/console/pull/1226
