### ISSUE TITLE
Wrong unit of measurement being used in grafana

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#13685]
SI decbytes unit of measurement is being used for various panels like  Current Usable Capacity, Data Usage Growth etc., Thereby, leading to incorrect information being displayed.

## Expected Behavior

IEC bytes unit of measurement
## Current Behavior

SI decbytes unit of measurement
## Steps to Reproduce (for bugs)

1. Load the MinIO grafana json 
2. Notice the numbers shown in Current Usable Capacity and Data Usage Growth does not matchup with real numbers

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> 2\. Notice the numbers shown in Current Usable Capacity and Data Usage Growth does not matchup with real numbers

FWIW they do match with real numbers it was using 1000 instead of 1024 - they were not wrong in any manner.
