### ISSUE TITLE
Minio Gateway directory Mount

### ISSUE THREAD

**Issue by jjmm0312** [minio/minio#13698]
**Is your feature request related to a problem? Please describe.**

When using minio s3 gateway, i can't mount persistent directory for storing iam users.

For minio server, I found the option 
`./minio server /data`
So I can store user data in /data directory.

But For minio gateway, there is no option about mount directory.
So iam cache is expired after 5 minutes.

I want to store user data more than 5 minutes.

**Describe the solution you'd like**
I hope a feature for gateway persistent directory.

Like this.
`./minio gateway s3 /data`

If so, i can store data more than 5 minutes in the local /data directory.

Thanks

**Comment by harshavardhana** [comment]
> When using minio s3 gateway, i can't mount persistent directory for storing iam users.

You need to use etcd to persist your users.

**Comment by jjmm0312** [comment]
I tried to set etcd, but i got message
`This admin API is not supported by server in 'mode-gateway-s3'`
