### ISSUE TITLE
Err occured

### ISSUE THREAD

**Issue by wuyuan0717** [minio/minio#13697]
`API: SYSTEM() Time: 22:55:54 CST 10/31/2021 DeploymentID: d0bbaf78-42d1-4439-a7c6-cb6f4cbe6aa0 Error: EOF (*errors.errorString) 1: cmd/iam-etcd-store.go:573:cmd.(*IAMEtcdStore).watch()`
`API: AssumeRoleSSOCommon() Time: 17:43:17 CST 10/31/2021 DeploymentID: d0bbaf78-42d1-4439-a7c6-cb6f4cbe6aa0 RequestID: 16B3144A071275C5 RemoteHost: 10.14.250.9 Host: 10.16.0.110:9366 UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 Error: Invalid STS API version , expecting 2011-06-15 (*errors.errorString) 3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse() 2: cmd/sts-handlers.go:271:cmd.(*stsAPIHandlers).AssumeRoleWithSSO() 1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()`

please，What caused the above error?  thanks a lot

There is another problem:

`Error: rle symbol 183 >= max 36 (msgp.errWrapped)`
`Error: sequence stream 1, repeat requested, but no history (msgp.errWrapped)`
`Error: tableLog too large (msgp.errWrapped)`
`Error: rle symbol 107 >= max 36 (msgp.errWrapped)`
`Error: CRC check failed (msgp.errWrapped)`

## Your Environment

* Version used (`minio --version`):  2021-05-18T00:53:28Z
* Operating System and version (`uname -a`):  Linux u-oss-xt-01 3.10.0-862.el7.x86_64

**Comment by harshavardhana** [comment]
@wuyuan0717 you are using a quarantined release. Please upgrade to latest.

**Comment by wuyuan0717** [comment]
When I use etcd to deploy a federated Minio cluster, ip:10.100.8.11-12, data1-data4, two nodes and four disks (cluster1), and now the cluster disk is full, I create a new cluster with two nodes and four disks (cluster2) to join the Federation for capacity expansion. Cluster2 can access the buckets and files in cluster1. The problem now is, Buckets in cluster1 cluster can be accessed, but new files cannot be uploaded. Cluster2 cluster can create buckets and upload files

**Comment by harshavardhana** [comment]
> When I use etcd to deploy a federated Minio cluster, ip:10.100.8.11-12, data1-data4, two nodes and four disks (cluster1), and now the cluster disk is full, I create a new cluster with two nodes and four disks (cluster2) to join the Federation for capacity expansion. Cluster2 can access the buckets and files in cluster1. The problem now is, Buckets in cluster1 cluster can be accessed, but new files cannot be uploaded. Cluster2 cluster can create buckets and upload files

You cannot federate you need to use server pools https://github.com/minio/minio/blob/master/docs/distributed/README.md#expanding-existing-distributed-setup read here on how.
