### ISSUE TITLE
Problems in etcd expansion

### ISSUE THREAD

**Issue by checkHup** [minio/minio#13719]
excuse me
 I am using etcd to build Minio clusters, but the following errors are always displayed： 
  **specified policy consoleAdmin, not found Specified canned policy does not exist (*fmt.wrapError)**
![image](https://user-images.githubusercontent.com/94658844/142808283-c2c97291-632b-4849-8288-7c283ac6d5c2.png)
![image](https://user-images.githubusercontent.com/94658844/142808318-e6a330c5-1839-4053-b73b-349f5f473ec9.png)

**Comment by harshavardhana** [comment]
> excuse me
> I am using etcd to build Minio clusters, but the following errors are always displayed：
> *_specified policy consoleAdmin, not found Specified canned policy does not exist (_fmt.wrapError)__

Please use the issue template to fill out all the details properly. I can't understand what you are doing clearly from the description. 

We can't imagine your setup, please explain to help us.
