### ISSUE TITLE
go install failed with go.mod contains replace directives

### ISSUE THREAD

**Issue by tisonkun** [minio/minio#13713]
```
GO111MODULE=on go install github.com/minio/minio@latest
go: downloading github.com/minio/minio v0.0.0-20211120015410-3da9ee15d316
go install: github.com/minio/minio@latest (in github.com/minio/minio@v0.0.0-20211120015410-3da9ee15d316):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

https://github.com/minio/minio/blob/3da9ee15d316808c59bd6e7d374e388a01a734dc/go.mod#L98

**Comment by harshavardhana** [comment]
> GO111MODULE=on go install github.com/minio/minio@latest
> go: downloading github.com/minio/minio v0.0.0-20211120015410-3da9ee15d316
> go install: github.com/minio/minio@latest (in github.com/minio/minio@v0.0.0-20211120015410-3da9ee15d316):
> 	The go.mod file for the module providing named packages contains one or
> 	more replace directives. It must not contain directives that would cause
> 	it to be interpreted differently than if it were the main module.

Replace directives are needed `clone` the source and run `make install`
