### ISSUE TITLE
Etcd, LDAP feature for S3 Gateway mode

### ISSUE THREAD

**Issue by jjmm0312** [minio/minio#13721]
**Is your feature request related to a problem? Please describe.**

Hello.
I am using Minio s3 gateway and I want to use etcd and LDAP.

I tried to set, but i got message
`This admin API is not supported by server in 'mode-gateway-s3'`

On #13698, i got answer that I should use etcd for persist my data.
But minio said not supported.

How can I set this feature and if i can't, is there any plan about this features for s3 gateway mode? 

Thanks.

**Comment by vadmeste** [comment]
> I tried to set, but i got message
> This admin API is not supported by server in 'mode-gateway-s3'

What you exactly tried here ?

**Comment by jjmm0312** [comment]
At first, I clicked the etcd, LDAP button in minio console. Console shows that message.

After that, I tried mc command on terminal.

Like this
`mc admin config set myminio etcd endpoints=http://myendpoint`
 
Terminal shows same message
`This admin API is not supported by server in 'mode-gateway-s3'`

**Comment by harshavardhana** [comment]
Using `mc admin config set` is not supported you need to use only environment variables with gateway.

MINIO_ETCD_ENDPOINTS
