### ISSUE TITLE
single drive mode leaves fs.json in .minio.sys/buckets

### ISSUE THREAD

**Issue by sfischme** [minio/minio#13726]
Minio keeping outdated data in .minio.sys/buckets

## Expected Behavior
Minio only keeps the data it needs in .minio.sys/buckets

## Current Behavior
Minio keeps old data in .minio.sys and doesn't clean it up

## Steps to Reproduce (for bugs)
1. run minio in: minio server /data
2. put 1M files into different buckets
3. delete some files
4. look into .minio.sys/buckets and see that these files still exist

## Your Environment

* Version used (`minio --version`): 2021-11-09T03:21:45Z
* Server setup and configuration: synology NAS linux with ext4
* Operating System and version (`uname -a`): Linux data 3.10.105 #25556 SMP Sat Aug 28 02:16:13 CST 2021 x86_64 GNU/Linux synology_broadwell_rs3618xs

**Comment by harshavardhana** [comment]
> * run minio in: minio server /data
> * put 1M files into different buckets
> * delete some files
> * look into .minio.sys/buckets and see that these files still exist

Can you provide more details @sfischme ? can you provide `tree` command output?

**Comment by sfischme** [comment]
Nothing specific to see in `tree`. It's just a lot of subdirectories that no longer exist in the bucket itself.

**Comment by sfischme** [comment]
There exist also directories in .minio.sys/buckets for buckets that were long deleted. Shouldn't they be cleaned up?

**Comment by harshavardhana** [comment]
> There exist also directories in .minio.sys/buckets for buckets that were long deleted. Shouldn't they be cleaned up?

when was this - if you have been using it historically then we do clear them we fixed some bug some time ago. 

Please let us know if this is historical.

**Comment by sfischme** [comment]
We updated from a 6month old version to the latest one.

**Comment by sfischme** [comment]
Can we delete buckets and sub-directories that no longer exist in .minio.sys/buckets while the instance is up and running?

**Comment by harshavardhana** [comment]
> We updated from a 6month old version to the latest one.

yeah, it was fixed some time ago. 

> Can we delete buckets and sub-directories that no longer exist in .minio.sys/buckets while the instance is up and running?

Yes you can.
