### ISSUE TITLE
Policy fail to restrict user in mc client

### ISSUE THREAD

**Issue by ceabq** [minio/minio#13728]
Policy not working when use mc client, but work in web console

```
{  
    "Version": "2012-10-17",  
    "Statement": [  
        {  
            "Effect": "Deny",  
            "Action": [  
                "s3:*"  
            ],  
            "Resource": [  
                "arn:aws:s3:::*"  
            ]  
        }  
    ]  
}  
```

## Expected Behavior

Disallow user to do any s3 action
## Current Behavior

On mc client, user can see, upload,download,delete
![image](https://user-images.githubusercontent.com/83302491/142953886-6d6e95fa-b35d-436b-9f3d-af47ef488cad.png)
![image](https://user-images.githubusercontent.com/83302491/142953933-3b07d699-7a6d-4334-8426-0df319739a69.png)
But policy worked in web console
![image](https://user-images.githubusercontent.com/83302491/142954054-6063d4e2-aba5-400e-8151-b392760ba464.png)

## Steps to Reproduce (for bugs)

1. use web console to create a user with this policy
2. login on both side(client and web console)
3.
4.

## Context

I'm trying to having multiple user and restrict them to not see each other bucket, after I found out I can not restrict, I write this policy to test where the problem is.
## Regression
No

## Your Environment

* Version used (`minio --version`):
* minio server: minio version RELEASE.2021-10-10T16-53-30Z
* minio client: mc version RELEASE.2021-10-07T04-19-58Z
* Server setup and configuration:
* binary install, start server with "MINIO_SERVER_URL=hide MINIO_ROOT_USER=hide MINIO_ROOT_PASSWORD=hide minio server /root/datas/dataminio1 /root/datas/dataminio2 /root/datas/dataminio3 /root/datas/dataminio4 /root/datas/dataminio5 --address ":8443" --console-address ":8880""
* Operating System and version (`uname -a`):
* Debian GNU/Linux 10 (buster)
* Linux locallocal 4.19.0-5-amd64  SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> On mc client, user can see, upload,download,delete

Can you show `mc admin user info alias/ <username>` ?

**Comment by ceabq** [comment]
> mc admin user info alias/

AccessKey: testupuser
Status: enabled
PolicyName: denyall
MemberOf:



And this is the denyall policy
![image](https://user-images.githubusercontent.com/83302491/142956376-72959a65-e3ec-4351-9c1a-a633b45d95c4.png)

**Comment by harshavardhana** [comment]
and can you show what you have is `mc alias list testupuser` ?

**Comment by harshavardhana** [comment]
You also know that you don't need an explicit "Deny" right? @ceabq all users are denied by default.

**Comment by harshavardhana** [comment]
I can't seem to reproduce this at all

```
~ mc admin user add play/ newuser newuser12345
Added user `newuser` successfully.

~ mc admin policy add play/ denyall /tmp/deny-all.json
Added policy `denyall` successfully.

~ MC_HOST_newuser=https://newuser:newuser12345@play.min.io mc ls newuser
mc: <ERROR> Unable to list folder. Access Denied.

~  mc admin policy set play/ denyall user=newuser
Policy `denyall` is set on user `newuser`

~ MC_HOST_newuser=https://newuser:newuser12345@play.min.io mc ls newuser
mc: <ERROR> Unable to list folder. Access Denied.

```

Looks like your `alias` is configured wrongly with credentials with higher privilege.  Closing this issue.

**Comment by ceabq** [comment]
> You also know that you don't need an explicit "Deny" right? @ceabq all users are denied by default.

I just made another user and test it(without selecting any policy, but it still have access with any bucket)
web console can't even login
![image](https://user-images.githubusercontent.com/83302491/142957002-bc12db2e-aafc-44a7-be05-132087121447.png)
![image](https://user-images.githubusercontent.com/83302491/142957017-76046c1a-f457-47fc-ac43-d028092bf46b.png)

![image](https://user-images.githubusercontent.com/83302491/142957113-d1710d2c-6298-41cb-8d0c-83b27e7e5076.png)

**Comment by ceabq** [comment]
> mc alias list testupuser

![image](https://user-images.githubusercontent.com/83302491/142957213-2ba438d5-8969-4800-9b1b-530d727d4116.png)

**Comment by harshavardhana** [comment]
> I can't seem to reproduce this at all
> 
> ```
> ~ mc admin user add play/ newuser newuser12345
> Added user `newuser` successfully.
> 
> ~ mc admin policy add play/ denyall /tmp/deny-all.json
> Added policy `denyall` successfully.
> 
> ~ MC_HOST_newuser=https://newuser:newuser12345@play.min.io mc ls newuser
> mc: <ERROR> Unable to list folder. Access Denied.
> 
> ~  mc admin policy set play/ denyall user=newuser
> Policy `denyall` is set on user `newuser`
> 
> ~ MC_HOST_newuser=https://newuser:newuser12345@play.min.io mc ls newuser
> mc: <ERROR> Unable to list folder. Access Denied.
> ```
> 
> Looks like your `alias` is configured wrongly with credentials with higher privilege. Closing this issue.

Read this @ceabq

**Comment by ceabq** [comment]
I ask someone in slack, he said it is probably a api version problem.

**Comment by ceabq** [comment]
> I ask someone in slack, he said it is probably a api version problem.

**Comment by ceabq** [comment]
> MC_HOST_newuser=

![image](https://user-images.githubusercontent.com/83302491/142958099-6fb105eb-159f-44e8-88cc-5f42dcd1345e.png)
A new user without any policy seems to have access

**Comment by harshavardhana** [comment]
> ![image](https://user-images.githubusercontent.com/83302491/142958099-6fb105eb-159f-44e8-88cc-5f42dcd1345e.png)
> A new user without any policy seems to have access

which version of MinIO are you running?

**Comment by ceabq** [comment]
@harshavardhana After upgradeing server to the newest version(from 2021-10-10T16:53:30Z to 2021-11-09T03-21-45Z).
This problem is sovled.
Thanks for your help

**Comment by harshavardhana** [comment]
Did you read the release notes and CVE published here? https://github.com/minio/minio/security/advisories/GHSA-v64v-g97p-577c 

You should upgrade.

**Comment by ceabq** [comment]
> Did you read the release notes and CVE published here? [GHSA-v64v-g97p-577c](https://github.com/minio/minio/security/advisories/GHSA-v64v-g97p-577c)
> 
> You should upgrade.

Sorry, I did not see it.
