### ISSUE TITLE
Deploying new minio console with URL prefix

### ISSUE THREAD

**Issue by toshi-k** [minio/minio#13736]
**Is your feature request related to a problem? Please describe.**
I'm updating MinIO in my web server.
Since MinIO console was updated drastically, I have to reconfigure it now.
But I can't find a way to deploy console with URL prefix like `http://mydomain/console` rather than `http://mydomain`.

**Describe the solution you'd like**
The typical way to deploy new MinIO without prefix would be like below.
`minio server /mnt/data –console-address “:9001”`
I'm happy if I can deploy new console like below with URL prefix.
`minio server /mnt/data –console-address “:9001/console”`

**Describe alternatives you've considered**
I tried URL rewrite by the ReverceProxy/LoadBalancer, but it didn't work.
Since new console is a complicated system than before, URL prefix have to be considered in the application side.

**Additional context**
Deploying console with URL prefix was available before.

**Comment by harshavardhana** [comment]
@toshi-k we do not allow sub-path setup for console UI.

**Comment by toshi-k** [comment]
@harshavardhana Thank you for your comment. I hope it will be supported in the future.

**Comment by Aronlele** [comment]
I have a same problem. old version has a support,but now latest version cannot

**Comment by harshavardhana** [comment]
> I have a same problem. old version has a support,but now latest version cannot

No versions supported sub-path-based properly yet. It may be supported in future there are no guarantees. 

This is a console feature please ask in the relevant project https://github.com/minio/console

**Comment by Aronlele** [comment]
> > I have a same problem. old version has a support,but now latest version cannot
> 
> No versions supported sub-path-based properly yet. It may be supported in future there are no guarantees.
> 
> This is a console feature please ask in the relevant project https://github.com/minio/console

Old version cannot change request url，for example，I add a prefix path /minio in nginx ,url is http://xxxx.com/minio/  ,proxy_pass http://xxx:9000,  all things is ok,but latest version ,maybe delete /minio

**Comment by toshi-k** [comment]
@Aronlele You're right. We are on the same page !
