### ISSUE TITLE
ListObject Error：panic: "POST /minio/storage/data/disk21/v42/walkdir?dir-path=&disk-id=2b299fe2-1b4d-476d-bcc7-774113ea92a4&forward=&prefix=&recursive=true&report-notfound=false&volume=bucket_name": send on closed channel

### ISSUE THREAD

**Issue by yeatesss** [minio/minio#13743]
## Expected Behavior
No errors reported in the logs

## Current Behavior
The log will indicate that an error is reported when concurrent ListObjects of multiple Buckets are performed and these Buckets have hundreds of thousands of Objects

> [2654697] panic: "POST /minio/storage/data/disk21/v42/walkdir?dir-path=&disk-id=2b299fe2-1b4d-476d-bcc7-774113ea92a4&forward=&prefix=&recursive=true&report-notfound=false&volume=bucket_name": send on closed channel
> [2654697]: goroutine 94062 [running]: 
> [2654697]: runtime/debug.Stack()
> [2654697]:         runtime/debug/stack.go:24 +0x65
> [2654697]: cmd.setCriticalErrorHandler.func1.1()
> [2654697]:         cmd/generic-handlers.go:468 +0x8e
> [2654697]: panic({0x1f6f520, 0x2641b60})
> [2654697]:         runtime/panic.go:1038 +0x215
> [2654697]: cmd.(*httpStreamResponse).CloseWithError(...)
> [2654697]:         cmd/storage-rest-server.go:935
> [2654697]: cmd.(*storageRESTServer).WalkDirHandler.func1()
> [2654697]:         cmd/metacache-walk.go:369 +0xbb
> [2654697]: panic({0x1f6f520, 0x2641b60})
> [2654697]:         runtime/panic.go:1038 +0x215
> [2654697]: cmd.(*httpStreamResponse).CloseWithError(...)
> [2654697]:         cmd/storage-rest-server.go:935
> [2654697]: cmd.(*storageRESTServer).WalkDirHandler(0xc00176f0e8, {0x2680c30, 0xc00b967c20}, 0xc01e789300)
> [2654697]:         cmd/metacache-walk.go:372 +0x809
> [2654697]: net/http.HandlerFunc.ServeHTTP(...)
> [2654697]:         net/http/server.go:2046
> [2654697]: cmd.httpTraceHdrs.func1({0x2680c30, 0xc00b967c20}, 0x0)
> [2654697]:         cmd/handler-utils.go:372 +0x53
> [2654697]: net/http.HandlerFunc.ServeHTTP(0x2680bd0, {0x2680c30, 0xc00b967c20}, 0x10)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.addCustomHeaders.func1({0x2680bd0, 0xc026742630}, 0xc01e7878c0)
> [2654697]:         cmd/generic-handlers.go:451 +0x3c2
> [2654697]: net/http.HandlerFunc.ServeHTTP(0x21ac240, {0x2680bd0, 0xc026742630}, 0x39)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setRequestValidityHandler.func1({0x2680bd0, 0xc026742630}, 0xc01e789300)
> [2654697]:         cmd/generic-handlers.go:365 +0x90d
> [2654697]: net/http.HandlerFunc.ServeHTTP(0x7fd01f040c98, {0x2680bd0, 0xc026742630}, 0x7fd046188f08)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setHTTPStatsHandler.func1({0x2688040, 0xc00b97ad20}, 0xc01e789300)
> [2654697]:         cmd/generic-handlers.go:279 +0x10e
> [2654697]: net/http.HandlerFunc.ServeHTTP(0xc0291d6c30, {0x2688040, 0xc00b97ad20}, 0xc01d2d1348)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setRequestLimitHandler.func1({0x2688040, 0xc00b97ad20}, 0xc01e789300)
> [2654697]:         cmd/generic-handlers.go:111 +0x38f
> [2654697]: net/http.HandlerFunc.ServeHTTP(0x22803ec, {0x2688040, 0xc00b97ad20}, 0x1a67156)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setCrossDomainPolicy.func1({0x2688040, 0xc00b97ad20}, 0x8)
> [2654697]:         cmd/crossdomain-xml-handler.go:43 +0xef
> [2654697]: net/http.HandlerFunc.ServeHTTP(0xc01e789300, {0x2688040, 0xc00b97ad20}, 0x1)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setBrowserRedirectHandler.func1({0x2688040, 0xc00b97ad20}, 0xc01e789300)
> [2654697]:         cmd/generic-handlers.go:140 +0x183
> [2654697]: net/http.HandlerFunc.ServeHTTP(0xc01e789300, {0x2688040, 0xc00b97ad20}, 0x2)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setAuthHandler.func1({0x2688040, 0xc00b97ad20}, 0xc01e789300)
> [2654697]:         cmd/auth-handler.go:514 +0x3d8
> [2654697]: net/http.HandlerFunc.ServeHTTP(0xc01e789200, {0x2688040, 0xc00b97ad20}, 0x1)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc00184c3c0, {0x2688040, 0xc00b97ad20}, 0xc01e789100)
> [2654697]:         github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
> [2654697]: github.com/rs/cors.(*Cors).Handler.func1({0x2688040, 0xc00b97ad20}, 0xc01e789100)
> [2654697]:         github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
> [2654697]: net/http.HandlerFunc.ServeHTTP(0x40, {0x2688040, 0xc00b97ad20}, 0xc01d2d19f8)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: cmd.setCriticalErrorHandler.func1({0x2688040, 0xc00b97ad20}, 0x26676c0)
> [2654697]:         cmd/generic-handlers.go:475 +0x83
> [2654697]: net/http.HandlerFunc.ServeHTTP(0x4a09a6, {0x2688040, 0xc00b97ad20}, 0xa0)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: internal/http.(*Server).Start.func1({0x2688040, 0xc00b97ad20}, 0x10000c01d2d1af0)
> [2654697]:         internal/http/server.go:102 +0x1b6
> [2654697]: net/http.HandlerFunc.ServeHTTP(0xc00c029a6c, {0x2688040, 0xc00b97ad20}, 0x4670ce)
> [2654697]:         net/http/server.go:2046 +0x2f
> [2654697]: net/http.serverHandler.ServeHTTP({0xc00a5cce70}, {0x2688040, 0xc00b97ad20}, 0xc01e789100)
> [2654697]:         net/http/server.go:2878 +0x43b
> [2654697]: net/http.(*conn).serve(0xc02b349e00, {0x26a2bd8, 0xc002accd80})
> [2654697]:         net/http/server.go:1929 +0xb08
> [2654697]: created by net/http.(*Server).Serve
> [2654697]:         net/http/server.go:3033 +0x4e8

## Possible Solution
I found that the problem may be that Request's ctx was cancelled, but I don't know where it was cancelled, or that the error doesn't affect the functionality.

when I use context.background() to create a new ctx to pass there will be no error`writer.CloseWithError(s.storage.WalkDir(context.background(), WalkDirOptions{
		Bucket:         volume,
		BaseDir:        dirPath,
		Recursive:      recursive,
		ReportNotFound: reportNotFound,
		FilterPrefix:   prefix,
		ForwardTo:      forward,
	}, writer))`

## Steps to Reproduce (for bugs)
1.Concurrent ListObject() with minio-golang-sdk
`ch:= c.ListObjects(context.Background(), bucketname, ListObjectsOptions{
				Prefix:     "",
				Recursive:  true,
				MaxKeys:    500,
				WithMetadata: true,
				WithVersions: true,
			})`

## Your Environment

* Version used (`minio --version`): commitId:c791de0e1eae2f9ae743e1fb866dcf1481748746
* Operating System and version (`uname -a`):Linux ubuntu 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Thanks we shall take a look @Yeatesss

**Comment by klauspost** [comment]
Regression from #13597 - I will look at a fix.

**Comment by harshavardhana** [comment]
> Regression from #13597 - I will look at a fix.

Most likely @klauspost
