### ISSUE TITLE
grafana panels: "normal" and "replication" panel should use different ids

### ISSUE THREAD

**Issue by bpedersen2** [minio/minio#13748]
## Expected Behavior
I should be able to import both the normal and the replication panel in the same grafana folder.

## Current Behavior

The current json files result in a "A panel with the same name and id already exists" error.

## Possible Solution

At least use a different ID for the panels.
Better would be to also use a different title.

(side note: I would have expected the replication panel to only show the replication-related data,
instead it actually is a full status + repliction panel, that could get better documented)

## Steps to Reproduce (for bugs)

1. import first the normal panel in grafana
2. then try to import the replication panel

**Comment by harshavardhana** [comment]
They do use different IDs as published here

https://grafana.com/grafana/dashboards/13502

https://grafana.com/grafana/dashboards/15305

**Comment by bpedersen2** [comment]
But not the ones linked in the docs at 
https://github.com/minio/minio/blob/master/docs/metrics/prometheus/grafana/minio-replication.json
https://github.com/minio/minio/blob/master/docs/metrics/prometheus/grafana/minio-overview.json

They both  end with:
"title": "MinIO Overview",
  "uid": "TgmJnqnnk",
  "version": 18

**Comment by harshavardhana** [comment]
@bpedersen2 let me fix those - thanks
