### ISSUE TITLE
LDAP support Issue with AssumeRoleWithLDAPIdentity()

### ISSUE THREAD

**Issue by eclipsetalk** [minio/minio#13749]
Hello,
I'm encountering an LDAP error with minio. I can access the LDAP server via the _ldapsearch_ command line, so the LDAP settings I set in the helm chart seem to be correct.

```
API: AssumeRoleWithLDAPIdentity()
Time: 17:11:21 UTC 11/23/2021
DeploymentID: 97376237-985e-4788-a91f-8167e49a0df3
RequestID: 16BA3C166D1F4815
RemoteHost: 10.211.135.68
Host: minio-3.minio-headless.minio.svc.cluster.local:9000
UserAgent: Go-http-client/1.1
Error: LDAP server error: Unable to find user DN: User DN for user1 not found (*fmt.wrapError)
       3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:599:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
       1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()
```
It seems MinIO STS AssumeRoleWithLDAPIdentity endpoint fails but I have no idea as to why. Has anyone experienced this issue before?

## Your Environment
* Version used (`minio --version`): minio version DEVELOPMENT.2021-10-27T16-29-42Z
* Server setup and configuration: Running on a container in a K8 pod
* Operating System and version (`uname -a`): Linux minio-0 5.4.0-1015-gkeop #16~18.04.1-Ubuntu SMP Thu Apr 22 17:08:08 UTC 2021 x86_64 GNU/Linux

Any ideas on how to debug this?
Thank you in advance for any pointers.

**Comment by harshavardhana** [comment]
This is purely a configuration issue read the detailed documentation here.

https://docs.min.io/minio/baremetal/security/ad-ldap-external-identity-management/external-authentication-with-ad-ldap-identity-provider.html#minio-external-identity-management-ad-ldap

**Comment by eclipsetalk** [comment]
It's not clear to me how to set up AssumeRoleWithLDAPIdentity via helm chart for LDAP integration with minio. Is there any sample you could share?
Thank you
