### ISSUE TITLE
Minio refuses to start when having even number of disks.

### ISSUE THREAD

**Issue by xaviermerino** [minio/minio#13741]
Hello everyone!

I have a small test setup of 4 VMs (d3.xlarge) with 3 disks each. In total I have 12 disks. This is an even number of disks and also a multiple of 4. I was wondering if I'm using the ellipsis syntax wrong, or maybe something else :sweat_smile:.

## Expected Behavior
I was expecting Minio to start but didn't happen.

## Current Behavior
I currently get something like: 
```
Invalid command line arguments: Incorrect number of endpoints provided [http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive{1...3}/minio]
      > Please provide correct combination of local/remote paths
```

## Steps to Reproduce (for bugs)

1. Deployed 4 VMs with 3 disks each.
2. Execute:
```
minio server http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive{1...3}/minio http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive{1...3}/minio http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive{1...3}/minio http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive{1...3}/minio
```

## Context
I was just trying to start minio. For some odd reason, this error does not occur if I list each disk individually like this:
```
minio server http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive3/minio \
http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive3/minio \
http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive3/minio \
http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive3/minio
```

I'm not sure if this is what the ellipsis is doing and therefore interchangeable or if there is some other magic behind that syntax. Using this the servers start and list 4 servers with 3 disks each, as I was expecting. Also, is there a limit on how many listings you can add this way? I read somewhere about 32 being a limit.

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2021-11-09T03-21-45Z
```
* Operating System and version (`uname -a`):
```
Linux ec2-18-219-185-212.us-east-2.compute.amazonaws.com 5.11.0-1020-aws #21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
> Invalid command line arguments: Incorrect number of endpoints provided [http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive{1...3}/minio]

Your DNS is not resolvable to local nodes - you need to use private IPs on EC2 not public DNS names that do not resolve to the node you are running to. 

> minio server http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
> http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
> http://ec2-18-219-185-212.us-east-2.compute.amazonaws.com/mnt/drive3/minio \
> http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
> http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
> http://ec2-3-143-1-60.us-east-2.compute.amazonaws.com/mnt/drive3/minio \
> http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
> http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
> http://ec2-3-145-57-0.us-east-2.compute.amazonaws.com/mnt/drive3/minio \
> http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive1/minio \
> http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive2/minio \
> http://ec2-18-223-206-229.us-east-2.compute.amazonaws.com/mnt/drive3/minio

Also, this entire syntax is wrong.  You should make /etc/hosts entries with your private IPs om the ec2 machines and name them accordingly as

```
server1
server2
...
serverN
```

Then your final command line will be 

```
minio server http://server{1...3}/mnt/drive{1...3}/minio
```

**Comment by xaviermerino** [comment]
@harshavardhana I had modified the /etc/hosts file to look like this:
```
172.31.10.101 ec2-3-15-18-210.us-east-2.compute.amazonaws.com
172.31.8.231 ec2-3-143-203-70.us-east-2.compute.amazonaws.com
172.31.9.73 ec2-18-119-102-129.us-east-2.compute.amazonaws.com
172.31.14.67 ec2-3-21-12-223.us-east-2.compute.amazonaws.com
172.31.3.243 ec2-18-116-69-69.us-east-2.compute.amazonaws.com
172.31.0.204 ec2-3-144-253-65.us-east-2.compute.amazonaws.com
172.31.8.166 ec2-18-219-83-232.us-east-2.compute.amazonaws.com
```
I could change the name given, but these are generated automatically, so I would rather not to. But running the command listed above works. Here's `mc admin` listing the hosts:
```
ubuntu@ec2-18-119-102-129:~$ mc admin info hdfs/
●  ec2-18-119-102-129.us-east-2.compute.amazonaws.com:9000
   Uptime: 16 minutes 
   Version: 2021-11-09T03:21:45Z
   Network: 4/4 OK 
   Drives: 3/3 OK 

●  ec2-3-143-203-70.us-east-2.compute.amazonaws.com:9000
   Uptime: 16 minutes 
   Version: 2021-11-09T03:21:45Z
   Network: 4/4 OK 
   Drives: 3/3 OK 

●  ec2-3-144-253-65.us-east-2.compute.amazonaws.com:9000
   Uptime: 16 minutes 
   Version: 2021-11-09T03:21:45Z
   Network: 4/4 OK 
   Drives: 3/3 OK 

●  ec2-3-21-12-223.us-east-2.compute.amazonaws.com:9000
   Uptime: 16 minutes 
   Version: 2021-11-09T03:21:45Z
   Network: 4/4 OK 
   Drives: 3/3 OK 

115 B Used, 1 Bucket, 5 Objects
12 drives online, 0 drives offline
```

I was wondering why the other command (the ellipsis style) did not work, or if it does something else in the background. Are those two styles similar?

**Comment by harshavardhana** [comment]
> @harshavardhana I had modified the /etc/hosts file to look like this:
> 
> ```
> 172.31.10.101 ec2-3-15-18-210.us-east-2.compute.amazonaws.com
> 172.31.8.231 ec2-3-143-203-70.us-east-2.compute.amazonaws.com
> 172.31.9.73 ec2-18-119-102-129.us-east-2.compute.amazonaws.com
> 172.31.14.67 ec2-3-21-12-223.us-east-2.compute.amazonaws.com
> 172.31.3.243 ec2-18-116-69-69.us-east-2.compute.amazonaws.com
> 172.31.0.204 ec2-3-144-253-65.us-east-2.compute.amazonaws.com
> 172.31.8.166 ec2-18-219-83-232.us-east-2.compute.amazonaws.com
> ```
> 
> I could change the name given, but these are generated automatically, so I would rather not to. But running the command listed above works. Here's `mc admin` listing the hosts:
> 
> ```
> ubuntu@ec2-18-119-102-129:~$ mc admin info hdfs/
> ●  ec2-18-119-102-129.us-east-2.compute.amazonaws.com:9000
>    Uptime: 16 minutes 
>    Version: 2021-11-09T03:21:45Z
>    Network: 4/4 OK 
>    Drives: 3/3 OK 
> 
> ●  ec2-3-143-203-70.us-east-2.compute.amazonaws.com:9000
>    Uptime: 16 minutes 
>    Version: 2021-11-09T03:21:45Z
>    Network: 4/4 OK 
>    Drives: 3/3 OK 
> 
> ●  ec2-3-144-253-65.us-east-2.compute.amazonaws.com:9000
>    Uptime: 16 minutes 
>    Version: 2021-11-09T03:21:45Z
>    Network: 4/4 OK 
>    Drives: 3/3 OK 
> 
> ●  ec2-3-21-12-223.us-east-2.compute.amazonaws.com:9000
>    Uptime: 16 minutes 
>    Version: 2021-11-09T03:21:45Z
>    Network: 4/4 OK 
>    Drives: 3/3 OK 
> 
> 115 B Used, 1 Bucket, 5 Objects
> 12 drives online, 0 drives offline
> ```
> 
> I was wondering why the other command (the ellipsis style) did not work, or if it does something else in the background. Are those two styles similar?

Well you need to make sure that ellipses can satisfy the node distribution as well.

You cannot use distinct args to join them together. Distinct args are meant for expansion and shouldn't be used as a get go deployment.

You should setup hosts the way I asked you to do. Providing individual args without ellipses MinIO can't choose sufficient HA based ordering.

That's why you should use the way I suggested.

**Comment by xaviermerino** [comment]
Sounds good! Thank you for your explanation!
