### ISSUE TITLE
Incorrect error message thrown during audit publishing

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#13754]
Setup an audit webhook with elasticsearch endpoint and notice there is a incorrect error message every time there is an audit published. 

API: SYSTEM()
Time: 19:39:49 UTC 11/24/2021
DeploymentID: 599cc902-b1ae-480a-9ee6-63b3ca639d83
Error: http://<elastic:9200>/ returned '201 Created', please check your endpoint configuration (*errors.errorString)
       3: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       2: internal/logger/logonce.go:94:logger.LogOnceIf()
       1: internal/logger/target/http/http.go:165:http.(*Target).startHTTPLogger.func1()

https://github.com/minio/minio/blob/master/internal/logger/target/http/http.go#L160 is only accepting 200 as valid status code. It should be accepting all 2xx status codes as success.

## Expected Behavior

No error message thrown every time an audit message is published

## Current Behavior

Incorrect error message is thrown, like below,

API: SYSTEM()
Time: 19:39:49 UTC 11/24/2021
DeploymentID: 599cc902-b1ae-480a-9ee6-63b3ca639d83
Error: http://<elastic:9200>/ returned '201 Created', please check your endpoint configuration (*errors.errorString)
       3: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       2: internal/logger/logonce.go:94:logger.LogOnceIf()
       1: internal/logger/target/http/http.go:165:http.(*Target).startHTTPLogger.func1()

## Possible Solution

Accept all 2xx codes
## Steps to Reproduce (for bugs)

1. Setup an elasticsearch cluster
2. Configure an audit webhook to it
3. Do MinIO operations using mc binary, like mc mb etc.,
4. Notice the incorrect error message thrown in the logs

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio/minio:RELEASE.2021-11-03T03-36-36Z

**Comment by harshavardhana** [comment]
> API: SYSTEM() Time: 19:39:49 UTC 11/24/2021 DeploymentID: 599cc902-b1ae-480a-9ee6-63b3ca639d83 Error: http://elastic:9200/ returned '201 Created', please check your endpoint configuration (*errors.errorString) 3: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf() 2: internal/logger/logonce.go:94:logger.LogOnceIf() 1: internal/logger/target/http/http.go:165:http.(*Target).startHTTPLogger.func1()
> 
> https://github.com/minio/minio/blob/master/internal/logger/target/http/http.go#L160 is only accepting 200 as valid status code. It should be accepting all 2xx status codes as success.

Unfortunately, we only accept 200 for now. @mshanmu

**Comment by mshanmu** [comment]
Let me a spin up a quick PR for this. Already setup accepts 201. Please see acceptedResponseStatusCode() function

**Comment by harshavardhana** [comment]
> Let me a spin up a quick PR for this. Already setup accepts 201. Please see acceptedResponseStatusCode() function

Yes it does there is another place that its missing.

**Comment by harshavardhana** [comment]
Here is the PR https://github.com/minio/minio/pull/13755

**Comment by mshanmu** [comment]
Great, thanks @harshavardhana
