### ISSUE TITLE
Audit Webhook: Update Auth_token documentation

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#13753]
https://docs.min.io/minio/baremetal/monitoring/logging/minio-logging.html#id2

When publishing audits through webhook, the above documentation mentions 

"Replace TOKEN with a JSON Web Token (JWT) to use for authenticating to the webhook endpoints. Omit for endpoints which do not require authentication."

This information is incorrect. 

Try doing "mc admin config set minio audit_webhook:elastic endpoint="<endpoint>" auth_token="<JWT token>". This will never work, every time failing with 401 error.

The reason is in, https://github.com/minio/minio/blob/master/internal/logger/target/http/http.go#L89 , it sets the Authorization header without "Bearer" keyword. I think this was a oversight.

But it is a good oversight :), thereby, allows the customer to set any type of authorization, which is very much desired, like below,

$ echo -n 'user:password' | base64
dXNlcjpwYXNzd29yZA==
$
$ mc admin config set minio audit_webhook:elastic endpoint="<endpoint>" auth_token="Basic dXNlcjpwYXNzd29yZA=="

I confirmed that this works well. 

Similarly, for JWT token, it will be like below,

$ mc admin config set minio audit_webhook:elastic endpoint="<endpoint>" auth_token="Bearer token"

Tried through the environment variables MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_<IDENTIFIER> and it did not work.

## Steps to Reproduce (for bugs)

1. Setup an audit webhook with auth token
2. Notice it does not work

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio/minio:RELEASE.2021-11-03T03-36-36Z

**Comment by harshavardhana** [comment]
> The reason is in, https://github.com/minio/minio/blob/master/internal/logger/target/http/http.go#L89 , it sets the Authorization header without "Bearer" keyword. I think this was a oversight.

It is not an oversight @mshanmu it is to support `Splunk` like endpoints so you need provide the actual mechanism as well.

I.e add `Bearer <your_token>`

**Comment by harshavardhana** [comment]
> $ mc admin config set minio audit_webhook:elastic endpoint="" auth_token="Bearer token"

This will work as long as your token is honored at the elastic endpoint.

**Comment by mshanmu** [comment]
Right, I am asking for updating the documentation. The documentation is not correct.

**Comment by harshavardhana** [comment]
> https://docs.min.io/minio/baremetal/monitoring/logging/minio-logging.html#id2

We need to update the docs @ravindk89 we should say we take "free_form" tokens to allow non-Bearer tokens presented by various HTTP endpoints such as 

- Splunk HTTP event target
- Logstash Basic auth target

**Comment by ravindk89** [comment]
So specifically, `MINIO_LOGGER_WEBHOOK_AUTH_TOKEN` or its cmd analog `audit_webhook auth_token` supports specifying both Bearer tokens and plaintext (or encoded) passwords, depending on what the remote requires

- For JWT authentication, specify `Bearer {TOKEN}`
- For basic authentication, specify `Basic {PASSWORD}`

Does that sound right @harshavardhana ?
