### ISSUE TITLE
Python Get Replication Config Issue

### ISSUE THREAD

**Issue by Suween** [minio/minio#13752]
Hello, 

I was told to post my [issue](https://github.com/minio/minio-py/issues/1164) from the minio-py here since it seems like a server bug (?). 

## Expected Behavior
Using 'Minio.get_bucket_replication()' from the minio-py on a bucket with existing and working Replication Configurations should return the config object without issue

## Current Behavior
'Minio.get_bucket_replication()' raises an error requesting a 'role' for the ReplicationConfig Class
![image](https://user-images.githubusercontent.com/20570625/143299798-78b804b0-e63c-4fac-a41a-86856d1e4c2a.png)

## Possible Solution
server return a default role, or in the python api, not raising error on empty roles

## Steps to Reproduce (for bugs)

Here's the log -> It start a connection to the local minio cluster docker-compose and tries to get the replication rules for the bucket 'some-bucket'

---------START-HTTP---------
GET /some-bucket?location= HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (Windows; AMD64) minio-py/7.1.1
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211124T163814Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Server: nginx/1.19.2
Date: Wed, 24 Nov 2021 16:38:11 GMT
Content-Type: application/xml
Content-Length: 128
Connection: keep-alive
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16BA88DBB80B9B70
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
GET /some-bucket?replication= HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (Windows; AMD64) minio-py/7.1.1
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211124T163814Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Server: nginx/1.19.2
Date: Wed, 24 Nov 2021 16:38:11 GMT
Content-Type: application/xml
Content-Length: 642
Connection: keep-alive
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16BA88DBB8C95F20
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<ReplicationConfiguration><Rule><ID>c6em39bbms9fjtfqslv0</ID><Status>Enabled</Status><Priority>1</Priority><DeleteMarkerReplication><Status>Disabled</Status></DeleteMarkerReplication><DeleteReplication><Status>Disabled</Status></DeleteReplication><Destination><Bucket>arn:minio:replication::a0cd6d61-ecc0-4273-876c-e5f786b58fba:some-bucket</Bucket></Destination><SourceSelectionCriteria><ReplicaModifications><Status>Enabled</Status></ReplicaModifications></SourceSelectionCriteria><Filter><Prefix></Prefix></Filter><ExistingObjectReplication><Status>Enabled</Status></ExistingObjectReplication></Rule><Role></Role></ReplicationConfiguration>
----------END-HTTP----------

## Context
I'm having an issue w
[log.txt](https://github.com/minio/minio/files/7598315/log.txt)
ith the bucket [get_replication_config](https://docs.min.io/docs/python-client-api-reference.html#get_bucket_replication) function. 

I have a local [docker-compose](https://docs.min.io/docs/deploy-minio-on-docker-compose.html) which I want to replicate on a similarly deployed remote cluster. 
From the UI, I can without issue set the replication from one cluster to another. It works great.  Files that are put on the local cluster are replicated without issues.

Now I wanted to code it, so first step I did was to try fetching the current replication to see what's inside a Replication Config and it doesn't work. 

## Your Environment
minio version RELEASE.2021-09-24T00-24-24Z
off the shelf [docker-compose](https://docs.min.io/docs/deploy-minio-on-docker-compose.html)
MSYS_NT-10.0 STAT1238 2.10.0(0.325/5/3) 2018-07-25 13:06 x86_64 Msys

**Comment by harshavardhana** [comment]
This is an implementation issue in Python SDK we will fix it @Suween
