### ISSUE TITLE
MinIO Signature Mismatch

### ISSUE THREAD

**Issue by namanrawal47** [minio/minio#13767]
## Expected Behavior
When using the mc command-line utility, running `mc ls mybucket/` should display the contents of my bucket. 

## Current Behavior
`mc ls mybucket/` results in "mc: <ERROR> Unable to list folder. The request signature we calculated does not match the signature you provided. Check your key and signing method."

## Possible Solution
No clue.

## Steps to Reproduce (for bugs)
1. Install the kong-ingress controller on AWS EKS (https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/deployment/eks/)
2. Set up ingress rules to point to Minio service in Kubernetes on port 9000
3. Access Minio using `mc` after setting up config.json locally

## Context
I have several data-sensitive applications that I cannot share here, but they perform calculations and upload results to MinIO. I noticed that all integration tests involving MinIO were failing because of the above error. The files are uploaded successfully based on application logs, but they are inaccessible via `mc`. I also cannot log into the Minio Console after port-forwarding the container. I am getting a 403 Forbidden when I try to do so. 

## Regression
No

## Your Environment
* Version used (`minio --version`): RELEASE.2021-11-03T03-36-36Z
* Server setup and configuration: Minio container image comes from Iron Bank (Dept. of Defense hosted container registry). All MinIO data is stored in container under /data. Using MINIO_ROOT_USER and MINIO_ROOT_PASSWORD as opposed to access and secret key environment variables. 
* Operating System and version (`uname -a`): Client machine is OSX. MinIO runtime is Linux s3-minio-898488fcd-ltjtn 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@namanrawal47 most probably you have a few things wrong like this

- incorrect LB configuration i.e not preserving Host header
- incorrect secret key

This is a simple basic setup issue.
