### ISSUE TITLE
Missing Prometheus metrics in Dashboard

### ISSUE THREAD

**Issue by ElfoLiNk** [minio/minio#13769]
## Expected Behavior

Minio Dashboard should show Prometheus metrics

## Current Behavior

Dashboard doesn't have metrics

<img width="1426" alt="Screenshot 2021-11-26 at 20 21 01" src="https://user-images.githubusercontent.com/1236551/143623188-ddc7f783-4b66-4c9d-9ca4-f7173bfae214.png">

## Steps to Reproduce (for bugs)

Add prometheus url to minio:

MINIO_PROMETHEUS_URL:        http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090/prometheus

Prometheus operator is scraping correctly minio metrics with the service monitor:

<img width="392" alt="Screenshot 2021-11-26 at 20 43 19" src="https://user-images.githubusercontent.com/1236551/143624582-048cb87f-1ea5-4ecc-b428-d869ae9d8677.png">

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: kubernetes helm chart
* Operating System and version (`uname -a`): Linux minio-3 5.4.120+ #1 SMP Wed Aug 18 10:20:32 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> MINIO_PROMETHEUS_URL: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090/prometheus

This is wrong there is no `/prometheus` @ElfoLiNk

**Comment by harshavardhana** [comment]
> Prometheus operator is scraping correctly minio metrics with the service monitor:

Also incorrectly setup 4 jobs @ElfoLiNk you only need to setup one. i.e you need to only talk over LB endpoint. 

A single endpoint for scraping gets data from all servers that's why its called `/cluster` metrics. 

You should re-do things on your end. Since the job_id is different you should set the proper job_id as well 

https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html#minio-metrics-collect-using-prometheus 

Read here how to set that up in the environment.

**Comment by ElfoLiNk** [comment]
> > MINIO_PROMETHEUS_URL: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090/prometheus
> 
> This is wrong there is no `/prometheus` @ElfoLiNk

It's correct in my setup with

```
prometheus:
  prometheusSpec:
    routePrefix: /prometheus
```

> > Prometheus operator is scraping correctly minio metrics with the service monitor:
> 
> Also incorrectly setup 4 jobs @ElfoLiNk you only need to setup one. i.e you need to only talk over LB endpoint.
> 
> A single endpoint for scraping gets data from all servers that's why its called `/cluster` metrics.
> 
> You should re-do things on your end. Since the job_id is different you should set the proper job_id as well
> 
> https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html#minio-metrics-collect-using-prometheus
> 
> Read here how to set that up in the environment.

The scraping setup is done automatically with the Service Monitor for prometheus operator:
https://github.com/minio/minio/blob/master/helm/minio/templates/servicemonitor.yaml

**Comment by harshavardhana** [comment]
> The scraping setup is done automatically with the Service Monitor for prometheus operator:
> https://github.com/minio/minio/blob/master/helm/minio/templates/servicemonitor.yaml

That is wrong and it should set up only one @ElfoLiNk, not for all pods. This can lead to duplicate metrics.
