### ISSUE TITLE
Broken link `https://docs.minio.io/categories/17` in NOTES.txt

### ISSUE THREAD

**Issue by bmitchinson** [minio/minio#13775]
Both lines 25 and 45 point to a broken docs URL in notes.txt 
https://github.com/minio/minio/blob/master/helm/minio/templates/NOTES.txt

## Expected Behavior
Post install message should point to a live docs url

## Current Behavior
Post install message points to a broken url

## Possible Solution
Updating the link
(Wish I could help / submit a PR but, not sure where that doc is at now)

## Steps to Reproduce (for bugs)
Install and notice the out of date link

## Context
N/A

## Regression
N/A

**Comment by harshavardhana** [comment]
> Both lines 25 and 45 point to a broken docs URL in notes.txt https://github.com/minio/minio/blob/master/helm/minio/templates/NOTES.txt

which helm are you talking about here? @bmitchinson

**Comment by ravindk89** [comment]
I've never seen that URL structure before - i'm assuming it's just meant to point at `https://docs.min.io` I can push a fix EOD to at least direct to our web docs properly.

**Comment by bmitchinson** [comment]
> > Both lines 25 and 45 point to a broken docs URL in notes.txt https://github.com/minio/minio/blob/master/helm/minio/templates/NOTES.txt
> 
> which helm are you talking about here? @bmitchinson

I'm using helm version:
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

I installed the "vanilla" minio helm chart, latest version, with the command documented in the readme:

```
helm install --namespace minio --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio
```

**Comment by harshavardhana** [comment]
> > > Both lines 25 and 45 point to a broken docs URL in notes.txt https://github.com/minio/minio/blob/master/helm/minio/templates/NOTES.txt
> > 
> > 
> > which helm are you talking about here? @bmitchinson
> 
> I'm using helm version:
> 
> ```
> version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
> ```
> 
> I installed the "vanilla" minio helm chart, latest version, with the command documented in the readme:
> 
> ```
> helm install --namespace minio --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio
> ```

Which repository @bmitchinson ?
