### ISSUE TITLE
MinIO distributed cluster found a disk in an unexpected location

### ISSUE THREAD

**Issue by torbendury** [minio/minio#13774]
When upgrading from `minio/minio:RELEASE.2021-09-24T00-24-24Z` to any higher version, the cluster is sweeping itself away and results in a `CrashLoopBackOff`.

I run a 4 node distributed cluster on k8s with local disk nodes.

## Expected Behavior

I wanted to do an update to the next available version. Everything should start up as always.

## Current Behavior

MinIO is logging the following errors:

```
ERROR Unable to initialize backend: found a disk in an unexpected location, pool: 0, found (set=0, disk=0) expected (set=0, disk=2): /storage/disc0(8cc2e8e5-e7e7-4e54-b6d1-535884943d49)
```

```
ERROR Unable to initialize backend: found a disk in an unexpected location, pool: 0, found (set=0, disk=2) expected (set=0, disk=0): http://minio-0.minio.s3-storage.svc.cluster.local:9000/storage/disc0(e7f6ca14-54f0-4880-93ec-500f493c2013)
```

## Possible Solution

I don't know, in the above mentioned issue everything was working perfectly. Did you change the behavior in any way in newer versions? Are (in a StatefulSet) minio-0 to minio-4 not allowed to run in a defined pool, but need to be hard assigned to their node?

## Steps to Reproduce (for bugs)

1. Run MinIO distributed cluster in above version
2. Update to any newer version in the release list

## Context

I was trying to do an update.

## Regression

--

## Your Environment

* Version used (`minio --version`): Later versions than `RELEASE.2021-09-24T00-24-24Z`

* Server setup and configuration: 4 Kubernetes nodes, tainted specially for MinIO cluster. Local disks attached.
* Operating System and version (`uname -a`): -

**Comment by harshavardhana** [comment]
> When upgrading from `minio/minio:RELEASE.2021-09-24T00-24-24Z` to any higher version, the cluster is sweeping itself away and results in a `CrashLoopBackOff`.

This is not a crash - it is showing a message that you should read and it's important.

Upgrade to the latest RELEASE.2021-11-24T23-19-33Z - server won't stop but you need to fix your drives. @torbendury 

You have swapped your drives on the nodes.

**Comment by torbendury** [comment]
We didn't swap drives, the disks are still on the same nodes. The Pods `minio-0` - `minio-3` are scheduled randomly on those nodes. Do the Pods need to always be scheduled on the same node?

**Comment by torbendury** [comment]
Maybe i found something, @harshavardhana - could it be that you never intended specific MinIO instances to start up with _any_ disk, and recently added a check that enforces the matching disks to be present?

**Comment by klauspost** [comment]
@torbendury It is nothing new. Disks should never change location. We added an additional check for it, but disks have always been required to be mounted on the same locations.

If you get the message, disks were swapped at some point. Swapping disks can lead to instability and/or data loss.

**Comment by harshavardhana** [comment]
> We didn't swap drives, the disks are still on the same nodes. The Pods `minio-0` - `minio-3` are scheduled randomly on those nodes. Do the Pods need to always be scheduled on the same node?

Yes, they need to pin to the same nodes - we expect that you use local pv that pins pods to same nodes.

**Comment by torbendury** [comment]
@klauspost @harshavardhana Thank you for the clarification! I will try to re-work this into Local PVs. To achieve this, I need to know which MinIO instance is expecting which disk. Is this persisted in some config, so I can read it out?

I saw that I can see an expected disk UUID when it shows the error above, but this error was logged on our development environment and I certainly don't want to crash our production environment to see the right UUID.

**Comment by klauspost** [comment]
@torbendury You can inspect `.minio.sys/format.json` to see id and the expected location.

```JSON
{
    "version": "1",
    "format": "xl",
    "id": "e5586419-9e44-4338-8edf-d9dc83d3c876",
    "xl":
    {
        "version": "3",
        "this": "ebe81a43-a30a-4f97-b41c-28e118ede82e",
        "sets":
        [
            [
                "ebe81a43-a30a-4f97-b41c-28e118ede82e",
                "c789f7e1-2b52-442a-b518-aa2dac03f3a1",
                "da9eca31-ff50-47b1-bae7-abb1f2edf2f2",
                "016f14b1-3bf8-4a0f-bdb8-144fbfc674c3",
                "77fd5d45-4510-4b31-8b67-c7a9dd003fbe",
                "e78900af-efb9-4b68-9fcc-1e59e9c74231",
                "a1394869-c449-4fb3-81a0-23ee825e2c43",
                "4a9c36c7-9efd-406b-8dd1-40b159167a4f"
            ]
        ],
        "distributionAlgo": "CRCMOD"
    }
}
```
In this example, the disk should be at the first position in the first set.

If you need further assistance, feel free to look at our [subscription offer](https://min.io/pricing).
