### ISSUE TITLE
DeleteObject() API doesn't delete 'null' versions properly on suspended buckets. MultiObjectDelete does

### ISSUE THREAD

**Issue by kreynolds** [minio/minio#13783]
When a bucket is created with versioning and then versioning is disabled, objects are no longer deletable

## Expected Behavior
If a bucket had versioning enabled then disabled, objects should be deletable.

## Current Behavior
The server responds with 204 deleted but the object is not deleted.

## Steps to Reproduce (for bugs)

1. Create a bucket that is versioned
2. Turn off versioning
3. Write an object to that bucket
4. Delete the object from that bucket (object is not deleted)

## Context
I have a software system with a test suite that tests different features with and without versioning enabled on buckets. It runs against multiple S3-style stores including minio. The tests reuse a bucket created on each store for each test, toggling versioning as necessary to support the test case. This works fine everywhere but minio, where objects are no longer deletable once the bucket has gone from versioned to unversioned.

## Regression
I do not know if this is a regression, but it has not worked since I've been using minio for about 8 months. Currently retried with RELEASE.2021-11-24T23-19-33Z and the bug is still present

## Your Environment
MacOS Docker compose environment
* RELEASE.2021-11-24T23-19-33Z
* Running the published docker image tagged above

**Comment by harshavardhana** [comment]
Of course, you can delete them @kreynolds  once versioning is enabled it is no longer an "un-versioned" - bucket. 

You can only suspend versioning on a bucket this is as per AWS S3 implementation behavior and required for compliance reasons. 

Once versioned is suspended deleting the version still creates a delete marker by preserving the latest version on the object. 

To delete all versions you need to use `mc rm --versions` to delete each of those individual versions.

**Comment by reynokel** [comment]
This was closed prematurely. I think you missed the part where versioning is disabled again before an object is added.

1. Create a new empty bucket with versioning off.
2. Toggle versioning on then back off.
3. Add an object, then try to delete it, and it cannot be deleted.

It is expected that an empty bucket created with versioning disabled behaves the same as an empty bucket with versioning enabled and then disabled, and in fact this is how S3 works if I run exactly the same test against an S3 bucket.

**Comment by harshavardhana** [comment]
> This was closed prematurely. I think you missed the part where versioning is disabled again before an object is added.
> 
> 1. Create a new empty bucket with versioning off.
> 2. Toggle versioning on then back off.
> 3. Add an object, then try to delete it, and it cannot be deleted.
> 
> It is expected that an empty bucket created with versioning disabled behaves the same as an empty bucket with versioning enabled and then disabled, and in fact this is how S3 works if I run exactly the same test against an S3 bucket.

Of course, I can do this 

```
~ minio server /tmp/fresh{1...4}
```

```
~ mc mb myminio/testbucket/
Bucket created successfully `myminio/testbucket/`.
```

```
~ mc version enable myminio/testbucket/
myminio/testbucket/ versioning is enabled
```

```
~ mc version suspend myminio/testbucket/
myminio/testbucket/ versioning is suspended
```

```
~ mc cp /etc/hosts myminio/testbucket/
/etc/hosts:                 207 B / 207 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 2.05 KiB/s 0s
```

```
~ mc rm myminio/testbucket/hosts 
Removing `myminio/testbucket/hosts`.
```

As expected per AWS S3 spec we need to create a `null` Delete marker
```
~ mc ls --versions myminio/testbucket/
[2021-11-29 13:53:12 PST]     0B null v1 DEL hosts
```

```
~ mc rm -r --force --versions myminio/testbucket/
Removing `myminio/testbucket/hosts` (versionId=null, modTime=2021-11-29 21:53:12.379 +0000 UTC).
```

```
~ mc ls --versions myminio/testbucket/
```

All gone!  @kreynolds @reynokel you need to read up on AWS S3 spec on how versioning works https://github.com/minio/minio/tree/master/docs/bucket/versioning

**Comment by kreynolds** [comment]
I understand you keep referencing the spec .. I've read the spec. What I'm telling you is that this is not how S3 actually works. Here is a sample script to demonstrate the difference, which I believe is a bug in minio (account creds not shown):

```ruby
def test_delete_object(client, bucket)
  # Enable then suspend versioning
  client.put_bucket_versioning(bucket: bucket, versioning_configuration: { status: 'Enabled' })
  client.put_bucket_versioning(bucket: bucket, versioning_configuration: { status: 'Suspended' })

  # Put and delete an object
  client.put_object(key: 'deletion-test-file', bucket: bucket, body: 'test body')
  client.delete_object(key: 'deletion-test-file', bucket: bucket)

  # Read the object
  client.get_object(key: 'deletion-test-file', bucket: bucket).body.read
end

# Using Minio
minio_client = Aws::S3::Client.new(minio_options)
minio_client.create_bucket(bucket: 'deletion-test') rescue nil
# This does not raise an exception, it returns the body of the object
body = test_delete_object(minio_client, minio_bucket)
puts "Body of file from Minio -> #{body.inspect}"

# Using s3
s3_client = Aws::S3::Client.new(s3_options)
# Here a NoSuchKey exception is raised instead of returning the object
begin
  body = test_delete_object(s3_client, s3_bucket)
rescue Aws::S3::Errors::NoSuchKey
  puts "AWS has returned an exception"
end
```

If you run this script, it will return
```
Body of file from Minio -> "test body"
AWS has returned an exception
```

Minio is _not_ doing the same thing that S3 is doing, and I'd argue that returning the body of a deleted object is a bug in any case.

**Comment by harshavardhana** [comment]
> Minio is _not_ doing the same thing that S3 is doing, and I'd argue that returning the body of a deleted object is a bug in any case.

Let me investigate.
