### ISSUE TITLE
Error: Bucket not found

### ISSUE THREAD

**Issue by DanJake** [minio/minio#13800]
Time to time I'm getting the following from the log:
`
API: SYSTEM()
`
`
Time: 07:23:16 UTC 11/30/2021
`
`
DeploymentID: 0d8dc639-9071-4560-96c1-64296d7ae91b
`
`
Error: Bucket not found: favicon.ico (cmd.BucketNotFound)
`

I tried to reproduce this error in the following command:
`
aws --endpoint-url=https://myminio.server.com  s3 cp --recursive /backup s3://test
`
Where "test" it's non-existent backet

I had next output:
`
upload failed: ./tmp.txt to s3://test/tmp.txt An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
`
But there is no information about this in the minio logs

Someone has any idea what it might be?

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-06-17T00-10-46Z
* Kubernetes: v1.20.11

**Comment by vadmeste** [comment]
@DanJake this looks just like a verbose log that we need to remove, maybe you can paste the whole log that you saw so we know where exactly it is logging.

**Comment by klauspost** [comment]
`favicon.ico` is a browser accessing the API endpoint.

**Comment by klauspost** [comment]
It just blindly tries to fetch it, obviously failing since it doesn't understand S3 API.

Seems like it should just be ignored, or filter when out if you have a reverse proxy that can do that.

**Comment by DanJake** [comment]
It is the whole log:
API: SYSTEM()
Time: 07:23:16 UTC 11/30/2021
DeploymentID: 0d8dc639-9071-4560-96c1-64296d7ae91b
Error: Bucket not found: favicon.ico (cmd.BucketNotFound)
5: cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
4: cmd/auth-handler.go:343:cmd.checkRequestAuthTypeCredential()
3: cmd/auth-handler.go:275:cmd.checkRequestAuthType()
2: cmd/bucket-listobjects-handlers.go:326:cmd.objectAPIHandlers.ListObjectsV1Handler()
1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 07:19:01 UTC 11/30/2021
DeploymentID: 0d8dc639-9071-4560-96c1-64296d7ae91b
Error: Bucket not found: server-info (cmd.BucketNotFound)
5: cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
4: cmd/auth-handler.go:343:cmd.checkRequestAuthTypeCredential()
3: cmd/auth-handler.go:275:cmd.checkRequestAuthType()
2: cmd/bucket-listobjects-handlers.go:326:cmd.objectAPIHandlers.ListObjectsV1Handler()
1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

**Comment by klauspost** [comment]
`favicon.ico` as described. 

`server-info` also seems like a non-exiting bucket being listed.

Not all endpoints log the same amount of errors.
