### ISSUE TITLE
Distributed node mode not working with tmpfs fs due to o_direct

### ISSUE THREAD

**Issue by fviard** [minio/minio#13818]
Distributed mode is not able to operate, when the "disks", that we are trying to use, are located within a tmpfs filesystem.

As I think is common, to perform some tests, I often create "throwable" temporary disks with tmpfs.  
But, I could also have used directly the "/tmp" mount, that is also, most of the time,  a tmpfs. 

## Expected Behavior
I would expect that Minio is able to start and operate correctly with these folders, despite the filesystem to be a tmpfs.  
Or, in the worse case scenario, have a proper error.

## Current Behavior
Minio goes into a failure loop and is unable to operate.  
Also, errors are not making any sense.  
Because Minio looks like to have a problem opening the "writable...tmp" file, but when you look at the filesystem, everything is correct, files were successfully created with a good ACL.

```
Unable to use the drive http://localhost/mnt/test/export1: open /mnt/test/export1/.minio.sys/tmp/.writable-check-6ef915da21eee6f7.tmp: invalid argument
Unable to use the drive http://localhost/mnt/test/export2: open /mnt/test/export2/.minio.sys/tmp/.writable-check-3cb59def47f5b4be.tmp: invalid argument
Unable to use the drive http://localhost/mnt/test/export3: open /mnt/test/export3/.minio.sys/tmp/.writable-check-01a5be46ea945c68.tmp: invalid argument
Unable to use the drive http://localhost/mnt/test/export4: open /mnt/test/export4/.minio.sys/tmp/.writable-check-be088403554048fa.tmp: invalid argument

API: SYSTEM()
Time: 01:46:43 CET 12/03/2021
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:317:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
       2: cmd/server-main.go:643:cmd.newObjectLayer()
       1: cmd/server-main.go:523:cmd.serverMain()
Waiting for a minimum of 2 disks to come online (elapsed 1s)
```

strace:
```
[pid 2693148] faccessat(AT_FDCWD, "/mnt/test/export1/.minio.sys/speedtest", R_OK|W_OK <unfinished ...>
[pid 2693143] <... epoll_pwait resumed>[{EPOLLOUT, {u32=1748813856, u64=139841589004320}}], 128, 272, NULL, 5964696545465496) = 1
[pid 2693151] <... getrandom resumed>"\x8f\x60\x1c\xa3\xdd\x10\x3e\xd2", 8, 0) = 8
[pid 2693148] <... faccessat resumed>)  = 0
[pid 2693151] openat(AT_FDCWD, "/mnt/test/export2/.minio.sys/tmp/.writable-check-8f601ca3dd103ed2.tmp", O_WRONLY|O_CREAT|O_EXCL|O_DIRECT|O_CLOEXEC, 0666 <unfinished ...>
[pid 2693143] epoll_pwait(4,  <unfinished ...>
[pid 2693148] getrandom( <unfinished ...>
[pid 2693143] <... epoll_pwait resumed>[{EPOLLOUT, {u32=1748813856, u64=139841589004320}}], 128, 0, NULL, 824634293720) = 1
[pid 2693151] <... openat resumed>)     = -1 EINVAL (Invalid argument)
[pid 2693148] <... getrandom resumed>"\x3d\x0e\x18\x50\xbe\x3b\x0e\x7d", 8, 0) = 8
[pid 2693141] <... nanosleep resumed>NULL) = 0
```

## Possible Solution
I saw in other parts of the code, that there is a "read" with fallback to not using "O_DIRECT" flag in case a "invalid argument" errno is encountered. I think that it would be good to do that here also.

Or, a filesystem type detection could be done, to globally disable the "O_DIRECT".

Or, worse solution, have the failure with a correct error making it explicit that a FS without o_direct, like tmpfs couldn't be used.

I don't like at all the last solution, because it is really convenient to be able to use tmpfs for some special situations.  
But, in all cases, a simple "warning" at startup could be enough.

## Steps to Reproduce (for bugs)

1. `sudo mkdir /mnt/test && sudo chmod 777 -R /mnt/test`
2. `sudo mount -t tmpfs -o size=300M tmpfs /mnt/test`
3. `./minio server "http://localhost/mnt/test/export1" "http://localhost/mnt/test/export2" "http://localhost/mnt/test/export3" "http://localhost/mnt/test/export4"`

## Your Environment

* Version used (`minio --version`):  
  `RELEASE.2021-11-24T23-19-33Z`
* Server setup and configuration:
* Operating System and version (`uname -a`): 
  `5.4.0-70-generic #78-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`

Thanks

**Comment by harshavardhana** [comment]
@fviard Unfortunately we cannot support tmpfs based setups for distributed setup. Adding fallbacks is too tricky - we have added in some scenarios where unknowingly filesystems may return errors. But we do expect that from the get-go the disks support O_DIRECT. 

We run all our tests in container environments and GitHub CI/CD with no issues what would be the problem on your end?

**Comment by harshavardhana** [comment]
Adding fallbacks in certain places in the code is very tricky, our users bring in a myriad of silly setups and loose data we can't have them run without O_DIRECT. 

It is forced agreed but with good intentions.  A warning is not sufficient and we used to have warnings and everyone seems to ignore them naturally.

**Comment by harshavardhana** [comment]
> * `sudo mkdir /mnt/test && sudo chmod 777 -R /mnt/test`
> * `sudo mount -t tmpfs -o size=300M tmpfs /mnt/test`
> * `./minio server "http://localhost/mnt/test/export1" "http://localhost/mnt/test/export2" "http://localhost/mnt/test/export3" "http://localhost/mnt/test/export4"`

Instead of doing this just do this - you don't need to do any `tmpfs` mount etc. 

```
./minio server /mnt/test/export{1...4}
```

**Comment by harshavardhana** [comment]
You want a distributed TLS setup here is another script

```sh
#!/bin/bash

uuid1="export1"
uuid2="export2"
uuid3="export3"
uuid4="export4"

MINIO=./minio
mkdir -p "/mnt/test/$uuid1" "/mnt/test/$uuid2" "/mnt/test/$uuid3" "/mnt/test/$uuid4"
mkdir -p "/mnt/cfg-$uuid1/certs/CAs" "/mnt/test/cfg-$uuid2/certs/CAs" "/mnt/test/cfg-$uuid3/certs/CAs" "/mnt/test/cfg-$uuid4/certs/CAs"
mkdir -p "/mnt/test/certs-tmp"
(cd /tmp/certs-tmp && \
     openssl ecparam -genkey -name prime256v1 | openssl ec -out private.key && \
     openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=localhost" && \
     cp private.key public.crt /mnt/test/cfg-$uuid1/certs && \
     cp private.key public.crt /mnt/test/cfg-$uuid2/certs && \
     cp private.key public.crt /mnt/test/cfg-$uuid3/certs && \
     cp private.key public.crt /mnt/test/cfg-$uuid4/certs && \
     cp public.crt /mnt/test/cfg-$uuid1/certs/CAs && \
     cp public.crt /mnt/test/cfg-$uuid2/certs/CAs && \
     cp public.crt /mnt/test/cfg-$uuid3/certs/CAs && \
     cp public.crt /mnt/test/cfg-$uuid4/certs/CAs && \
     rm -rf ../certs-tmp
)

${MINIO} server -C /mnt/test/cfg-$uuid1 --address localhost:9001 "https://localhost:9001/mnt/test/${uuid1}" "https://localhost:9002/mnt/test/${uuid2}" "https://localhost:9003/mnt/test/${uuid3}" "https://localhost:9004/mnt/test/${uuid4}"&
${MINIO} server -C /mnt/test/cfg-$uuid2 --address localhost:9002 "https://localhost:9001/mnt/test/${uuid1}" "https://localhost:9002/mnt/test/${uuid2}" "https://localhost:9003/mnt/test/${uuid3}" "https://localhost:9004/mnt/test/${uuid4}"&
${MINIO} server -C /mnt/test/cfg-$uuid3 --address localhost:9003 "https://localhost:9001/mnt/test/${uuid1}" "https://localhost:9002/mnt/test/${uuid2}" "https://localhost:9003/mnt/test/${uuid3}" "https://localhost:9004/mnt/test/${uuid4}"&
${MINIO} server -C /mnt/test/cfg-$uuid4 --address localhost:9004 "https://localhost:9001/mnt/test/${uuid1}" "https://localhost:9002/mnt/test/${uuid2}" "https://localhost:9003/mnt/test/${uuid3}" "https://localhost:9004/mnt/test/${uuid4}"
```

**Comment by fviard** [comment]
Thanks for the tips.  

As I said, at worst, just show a proper error message, because it could happen like it did to me. And then, error messages do not make any sense, so it can take a very long time to understand what is going on.  

That being said, as far as I know, tmpfs might be the only commonly encountered fs on Linux throwing an error for o_direct. It's the only one documented explicitly in the open manpage. And they don't support it without a real reason, but in fact even if it was accepting the argument, it would make absolutely no difference to use it.
So I'm quite confident that on Linux, you can fallback or have fs detection ignoring it without any consequence at all.

**Comment by harshavardhana** [comment]
> That being said, as far as I know, tmpfs might be the only commonly encountered fs on Linux throwing an error for o_direct. It's the only one documented explicitly in the open manpage. And they don't support it without a real reason, but in fact even if it was accepting the argument, it would make absolutely no difference to use it.

There are some such as container environments that bring random CSI's which do not support O_DIRECT and then they put their critical data on it. 

> So I'm quite confident that on Linux, you can fallback or have fs detection ignoring it without any consequence at all.

Of course, we can, but the problem is not that at all. If we do fallback people ignore and never fix their setup. 

> As I said, at worst, just show a proper error message, because it could happen like it did to me. And then, error messages do not make any sense, so it can take a very long time to understand what is going on.

Yes, this is do-able not sure why it's not showing such a message anymore. Most probably error has been masked and not referenced properly. 

Let me add correct messages.

**Comment by harshavardhana** [comment]
Here is what we were supposed to throw as an error

```
~ ./minio server "http://localhost/mnt/test/export1" "http://localhost/mnt/test/export2" "http://localhost/mnt/test/export3" "http://localhost/mnt/test/export4"
Unable to use the drive http://localhost/mnt/test/export1: disk does not support O_DIRECT
Unable to use the drive http://localhost/mnt/test/export2: disk does not support O_DIRECT
Unable to use the drive http://localhost/mnt/test/export3: disk does not support O_DIRECT
Unable to use the drive http://localhost/mnt/test/export4: disk does not support O_DIRECT
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure your disk supports O_DIRECT
      HINT:
        Disks do not support O_DIRECT flags, MinIO erasure coding requires filesystems with O_DIRECT support
```

**Comment by fviard** [comment]
This will be a lot clearer thanks!
