### ISSUE TITLE
Incompatible signature algorithm - XMinioAdminUpdateApplyFailure

### ISSUE THREAD

**Issue by northway** [minio/minio#13824]
Hi!

I want to update my distributed MinIO setup, but I'm getting this error message:

```
{"Code":"XMinioAdminUpdateApplyFailure","Message":"Incompatible signature algorithm","Resource":"/minio/admin/v3/update","Region":"hu-central-1","RequestId":"16BD3C85889922BA","HostId":"d946e4aa-2da2-46ab-aee5-85d4c5d3a4fd"}
```

## Your Environment

* Version used: `2021-11-05T09:16:26Z`
* Server setup and configuration: Distributed Docker
* Operating System and version: `Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

## Full error log

```
mcli: <DEBUG> POST /minio/admin/v3/update?updateURL= HTTP/1.1
Host: REDACTED
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mcli/RELEASE.2021-11-16T20-37-36Z
Transfer-Encoding: chunked
Authorization: AWS4-HMAC-SHA256 Credential=admin/20211203//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211203T115303Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 225
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 03 Dec 2021 11:53:47 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: hu-central-1
X-Amz-Request-Id: 16BD3C85889922BA
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminUpdateApplyFailure","Message":"Incompatible signature algorithm","Resource":"/minio/admin/v3/update","Region":"hu-central-1","RequestId":"16BD3C85889922BA","HostId":"d946e4aa-2da2-46ab-aee5-85d4c5d3a4fd"}
mcli: <DEBUG> TLS Certificate found:
mcli: <DEBUG>  >> Country: NL
mcli: <DEBUG>  >> Organization: GEANT Vereniging
mcli: <DEBUG>  >> Expires: 2022-05-11 23:59:59 +0000 UTC
mcli: <DEBUG> TLS Certificate found:
mcli: <DEBUG>  >> Country: US
mcli: <DEBUG>  >> Organization: The USERTRUST Network
mcli: <DEBUG>  >> Expires: 2033-05-01 23:59:59 +0000 UTC
mcli: <DEBUG> TLS Certificate found:
mcli: <DEBUG>  >> Country: GB
mcli: <DEBUG>  >> Organization: Comodo CA Limited
mcli: <DEBUG>  >> Expires: 2028-12-31 23:59:59 +0000 UTC
mcli: <DEBUG> Response Time:  44.266629598s

mcli: <ERROR> Unable to update the server. Incompatible signature algorithm
 (0) admin-update.go:109 cmd.mainAdminServerUpdate(..)
 ```

Any suggestion how to fix this?

**Comment by klauspost** [comment]
Is the `MINIO_UPDATE_MINISIGN_PUBKEY` environment variable set?

**Comment by northway** [comment]
> Is the `MINIO_UPDATE_MINISIGN_PUBKEY` environment variable set?

Hmmm, yes it is! 

Altough I just checked my playbook and for sure I did not set it...

**Comment by klauspost** [comment]
@northway I will let @harshavardhana look at this. For now just let it be.

**Comment by harshavardhana** [comment]
> * Server setup and configuration: Distributed Docker

For docker setups you should pull the containers not do `mc admin update` @northway - this can lead to consistent `image:tag` and a different binary in the container.

We can't allow it.

**Comment by harshavardhana** [comment]
Tested this locally not reproducible 

```
./minio server /tmp/fs/

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 2 months ago ┃
┃ Update: Run `mc admin update`                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

API: http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                 
RootUser: minio 
RootPass: minio123 

Console: http://10.0.0.67:35779 http://172.16.3.3:35779 http://172.17.0.1:35779 http://172.18.0.1:35779 http://127.0.0.1:35779         
RootUser: minio 
RootPass: minio123 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minio minio123

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (35779), please use --console-address ":PORT" to choose a static port.
Restarting on service signal
API: http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                 
RootUser: minio 
RootPass: minio123 

Console: http://10.0.0.67:45103 http://172.16.3.3:45103 http://172.17.0.1:45103 http://172.18.0.1:45103 http://127.0.0.1:45103         
RootUser: minio 
RootPass: minio123 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minio minio123

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (45103), please use --console-address ":PORT" to choose a static port.
```

```
~ mc admin update myminio/
Server `myminio/` updated successfully from 2021-09-23T04:46:24Z to 2021-11-24T23-19-33Z
```

I suspect the error is either 

- there is a download failure of signature information from dl.minio.io - or there is a write error on the Docker container. 
- We are not able to persist the information for signature verification.

As I explained doing `mc admin update` inside container environments is not expected and not supported. The update mechanisms for containers are different.

```
~ mc admin update
```

Is meant for bare-metal setups only.

**Comment by northway** [comment]
> As I explained doing `mc admin update` inside container environments is not expected and not supported. The update mechanisms for containers are different.

Okay, so I just simply pull the latest image on all nodes and the update is done...?

Because doc pages at the https://docs.min.io and https://docs.min.io/minio/baremetal/reference/minio-cli/minio-mc-admin/mc-admin-update.html covering only the bare-metal solution.

On the Docker Hub page there's a little bit more, but not quite enough IMO:

> `mc admin update` is disabled in kubernetes/container environments, container environments provide their own mechanisms to rollout of updates.

...

> NOTE: some releases might not allow rolling upgrades, this is always called out in the release notes and it is generally advised to read release notes before upgrading. In such a situation mc admin update is the recommended upgrading mechanism to upgrade all servers at once.

In a stateless Docker setup, what is the correct way to update the distributed cluster? (I'm not using the MinIO Operator)

**Comment by harshavardhana** [comment]
> Because doc pages at the https://docs.min.io and https://docs.min.io/minio/baremetal/reference/minio-cli/minio-mc-admin/mc-admin-update.html covering only the bare-metal solution.

Docker containers are not bare-metal @northway - if you wish to run bare-metal just run the binaries not containers.

> In a stateless Docker setup, what is the correct way to update the distributed cluster? (I'm not using the MinIO Operator)

Update the image and roll the containers - if you don't use operator and stick to containers your options are limited.

**Comment by northway** [comment]
> Docker containers are not bare-metal @northway - if you wish to run bare-metal just run the binaries not containers.

There's no need for the defensive tone, I wasn't blaming anybody (I see that others do in the issues). The MinIO documentation is outstanding, but I think this use case is not covered too well (maybe it was intentional?).

BTW: We've already migrated most of our clusters to bare-metal. This one will be migrated as well, but until we do so, it needs to be updated.

> Update the image and roll the containers - if you don't use operator and stick to containers your options are limited.

Thanks, I just wanted a confirmation before I pull the trigger.

P.S.: @harshavardhana I recognize your contribution to this community, please keep up the good work! ❤️

**Comment by harshavardhana** [comment]
> There's no need for the defensive tone, I wasn't blaming anybody (I see that others do in the issues). The MinIO documentation is outstanding, but I think this use case is not covered too well (maybe it was intentional?).

Updating containers generally we defer to container updating practices which usually everyone follows like updating `nginx`.

```
~ mc admin update
```

Was designed before - software delivery mechanisms are different in different setups and it's not aged well.  For example, someone running RPM/DEB installation will face the same issues. You just have to follow the best practices for whatever mechanism is used. 

Most end up using some other kind of orchestration mechanisms such as ansible or k8s. Without this kind of automation in place. `mc admin update` is one choice.

But that requires full internet access which is also rare in most setups that we encounter. So `mc admin update`s use-case is quite limited.

**Comment by northway** [comment]
> Was designed before - software delivery mechanisms are different in different setups and it's not aged well. For example, someone running RPM/DEB installation will face the same issues. You just have to follow the best practices for whatever mechanism is used.

Okay, so a stateless Docker system should be updated with a standard docker pull, an RPM/DEB installation should be updated with the newest package and so on, right?

Therefore the `mc admin update` is only viable when someone just pulls binary from the download site without any orchestration or packaging system?

**Comment by harshavardhana** [comment]
> Okay, so a stateless Docker system should be updated with a standard docker pull, an RPM/DEB installation should be updated with the newest package and so on, right?

Yes

> Therefore the `mc admin update` is only viable when someone just pulls binary from the download site without any orchestration or packaging system?

Correct.

**Comment by northway** [comment]
Thank you for clearing this! 🙏
