### ISSUE TITLE
Snowball objects upload succeeds when payload is in unknown compression format

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#13832]
More information is available https://github.com/minio/minio-java/runs/4417379826?check_suite_focus=true#step:6:216

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio.RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
@balamurugana Could you describe the repro? Are you sure you are requesting the correct object. Maybe check what is extracted.

**Comment by balamurugana** [comment]
I tested compression data produced by java is not readable by `github.com/golang/snappy`. This means the java code tried to upload junk data as snowball objects but this call succeeded in the minio server. This is the actual bug.

I will be removing snappy compression support of snowball objects in `minio-java` once this issue is addressed.

**Comment by harshavardhana** [comment]
> I tested compression data produced by java is not readable by `github.com/golang/snappy`. This means the java code tried to upload junk data as snowball objects but this call succeeded in the minio server. This is the actual bug.

What server supports is a format called `s2` by @klauspost https://pkg.go.dev/github.com/klauspost/compress/s2#section-readme 

It does support reading `golang/snappy` though,  so must be something special with Java implementation of Snappy that is off. 

> I will be removing snappy compression support of snowball objects in `minio-java` once this issue is addressed.

You should use Gzip or Zstd instead.  I have written an example using aws-sdk-java https://github.com/harshavardhana/s3tar here with Gzip compression.

**Comment by klauspost** [comment]
@balamurugana You must use a Snappy *stream* - I suspect that is your problem. Snappy defines block encoding and stream encoding. Blocks are without headers or any identification - and require blocks to be in memory, so it cannot be used for streaming.

Gzip will limit you to ~100-200MB/s on the server side, so it is a less-than-optimal solution, though it will most often compress better than Snappy. If you cannot make Snappy work, see if there is a good (streaming) zstandard or LZ4 implementation.

**Comment by klauspost** [comment]
@balamurugana This. See https://github.com/xerial/snappy-java#compatibility-notes

> The original Snappy format definition did not define a file format. It later added a "framing" format to define a file format, but by this point major software was already using an industry standard instead -- represented in this library by the SnappyOutputStream and SnappyInputStream methods.

I guess you have to use `SnappyFramedOutputStream`.

**Comment by balamurugana** [comment]
> @balamurugana This. See https://github.com/xerial/snappy-java#compatibility-notes
> 
> > The original Snappy format definition did not define a file format. It later added a "framing" format to define a file format, but by this point major software was already using an industry standard instead -- represented in this library by the SnappyOutputStream and SnappyInputStream methods.
> 
> I guess you have to use `SnappyFramedOutputStream`.

`SnappyFramedOutputStream` works. Irrespective of this, minio server should return an error if junk data is passed.

**Comment by klauspost** [comment]
@balamurugana Yeah, seems like a missing error check.

**Comment by balamurugana** [comment]
@klauspost `400 Bad Request` with minio specific error code or what AWS Snowball Edge returns.

**Comment by klauspost** [comment]
@balamurugana Yeah. In most cases that would apply, but other things like permissions or object locking should return as such.

**Comment by klauspost** [comment]
See #13836

**Comment by harshavardhana** [comment]
AWS Snowball doesn't support Snappy etc @balamurugana - it's only MinIO specific feature. 

Gzip should be default because that is what is expected by AWS Snowball functionality @klauspost - however, having an option to use other mechanisms is also good. 

Since minio-java gets used with AWS targets as well.

**Comment by klauspost** [comment]
Yeah. For `minio-go` it is disabled by default with a note it is only "safe" for MinIO hosts.
