### ISSUE TITLE
Unable to set custom metadata for folder like object

### ISSUE THREAD

**Issue by jumpapex** [minio/minio#13835]
## Expected Behavior

If I upload object with name ends with '/'(like folder), custom meta data could not set on it.
But custom meta data could be set on nomal object(name not ends with '/')

custom meta data shoud be able to be set on object with name ends with '/'
## Current Behavior

custom meta data is not able to be set on object with name ends with '/'

## Steps to Reproduce (for bugs)

1. 
s3 put -u cs3-001/zero-size filename=zero-size x-amz-meta-part-size=1048576
s3 put -u cs3-001/zero-size2/ filename=zero-size x-amz-meta-part-size=1048576
2.
mc stat myminio/cs3-001/
**Name      : zero-size**
Date      : 2021-12-06 14:39:18 CST
Size      : 0 B
ETag      : d41d8cd98f00b204e9800998ecf8427e
Type      : file
Metadata  :
  X-Amz-Meta-Part-Size: 1048576
  Content-Type        : binary/octet-stream
**Name      : zero-size2/**
Size      : 0 B
Type      : folder
Metadata  :
  Versioning: Un-versioned
  Location: us-east-1
  Policy: none

3.
4.

## Context

The object ends with '/' may have additional properties, but first it should behavior like a normal object.

## Regression
 Not sure

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: centos stream 8.3
* Operating System and version (`uname -a`): Linux centos83 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> custom meta data shoud be able to be set on object with name ends with '/'

are you using a single drive setup or erasure coded? @jumpapex

**Comment by harshavardhana** [comment]
If you are not on a single drive setup, you can add metadata on directories in erasure-coded deployments. 

Closing this issue as working.
