### ISSUE TITLE
Environment variables NAME, REGION and COMMENT not being used/loaded

### ISSUE THREAD

**Issue by jsabater** [minio/minio#13837]
Having configured the following variables in the `/etc/default/minio` file:

```
MINIO_SERVER_URL="https://minio.mydomain.com:9000"
MINIO_SITE_NAME="MinIO test server"
MINIO_SITE_REGION="Europe"
MINIO_SITE_COMMENT"Nothing to see here. Move along. Move along..."
MINIO_BROWSER=on
MINIO_ROOT_USER="minio"
MINIO_ROOT_PASSWORD="<password>"
MINIO_VOLUMES="/usr/local/share/minio/"
MINIO_OPTS="--config-dir /etc/minio --certs-dir /etc/minio/certs --address :9000 --console-address :9001"
```

The server is (re)started via `systemctl (re)start minio` and, when visiting the console (web based object browser) at https://minio.mydomain.com:9001/, when you go to `Settings: Region`, no values appear in the "Server location" or the "Comment" fields. Also, the name does not appear to be anywhere (e.g. web page title, dashboard, etc.), albeit I have not found a specific field where one could change it.

I am running version `2021-11-24T23:19:33Z` on Debian Bullseye 11 AMD64 (inside a LXC on Proxmox 7.1 [1]) installed from [this Debian package](https://dl.min.io/server/minio/release/linux-amd64/minio_20211124231933.0.0_amd64.deb). Nothing else is running in the container.

[1] Linux minio1 5.13.19-2-pve #1 SMP PVE 5.13.19-4 (Mon, 29 Nov 2021 12:10:09 +0100) x86_64 GNU/Linux

As far as I have been able to figure out from the documentation, these three variables should be loaded from environment variables. Only thing I can think of is:

1. It's a bug (wrong string in the documentation or wrong variable being loaded in the code).
2. These three variables were not present the very first time I started the server (iterative process, you know), so maybe MinIO stored blank values in its internal database and, when I added them later, they were ignored. So it's not a bug.

Thanks in advance.

**Comment by harshavardhana** [comment]
@jsabater environment variables are never visible through `mc admin config` or `console UI` - those values are meant for persistence on disk.

When you set through ENV all the default values are overridden. This is working as expected as per the design. 

Whatever is set through ENV is not visible through `mc admin config` or `Console UI` Settings dashboard. 

Either you should use Settings Dashboard by setting through UI or through ENV.

**Comment by jsabater** [comment]
Thanks for the quick feedback. Just so that I understand this, the design is such as:

1. When I set ENV variables, they always take precedence.
2. Even if I set up values through the Console UI, they will be overwritten upon restart by ENV variables.
3. ENV variable values won't ever appear in the Console UI or the console client.

Is this correct?

**Comment by harshavardhana** [comment]
> Is this correct?

Yes
