### ISSUE TITLE
Minio policy to access specific subfolder inside bucket via web console

### ISSUE THREAD

**Issue by vikram-opensrc** [minio/minio#13867]
Expected Behavior: User should be able to access the specific folder for which access is given via policy
{
 "Version":"2012-10-17",
 "Statement": [
   {
     "Sid": "AllowStatement1",
     "Action": ["s3:ListAllMyBuckets", "s3:GetBucketLocation"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::*"]
   },
  {
     "Sid": "AllowStatement4B",
     "Effect": "Allow",
     "Action": ["s3:GetObject", "s3:PutObject"],
     "Resource": ["arn:aws:s3:::my-bucket"]
   }
  {
     "Sid": "AllowStatement2B",
     "Action": ["s3:ListBucket"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::my-bucket"],
     "Condition":{"StringEquals":{"s3:prefix":["","media"],"s3:delimiter":["/"]}}
    },
  {
     "Sid": "AllowStatement3",
     "Action": ["s3:ListBucket"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::my-bucket"],
     "Condition":{"StringLike":{"s3:prefix":["media/*"]}}
    },
   {
     "Sid": "AllowStatement4B",
     "Effect": "Allow",
     "Action": ["s3:GetObject", "s3:PutObject"],
     "Resource": ["arn:aws:s3:::my-bucket/media/*"]
   }
 ]
}

Actual Behavior:
User is able to get inside the bucket. But not able to get any content inside the bucket.
View with admin user:
![image](https://user-images.githubusercontent.com/15107282/145358092-b8d06f02-2904-4888-81bd-e7890731f606.png)

View with user with policy:
![image](https://user-images.githubusercontent.com/15107282/145357960-fddbf8cb-4e7a-4562-be2a-694504caec42.png)

**Comment by klauspost** [comment]
You are listing the root of the bucket. The user is not allowed to do that. 

There is no "selective filtering" on results, so you are either allowed to list the prefix you are sending or you are not.

**Comment by vikram-opensrc** [comment]
Ok. So is it possible to provide a user access to only a particular sub folder inside a bucket? If yes could you guide me as to how?

**Comment by klauspost** [comment]
I can't think of a way.

For the folder to be visible it would require the root to be list-able, which would basically make the entire bucket list-able.
