### ISSUE TITLE
[DOC] Persistence storage (Quickstart guide)

### ISSUE THREAD

**Issue by thbar** [minio/minio#13868]
I am following the guidelines here:

https://github.com/minio/minio/blob/master/docs/docker/README.md

In particular, this section:

> To create a MinIO container with persistent storage, you need to map local persistent directories from the host OS to virtual config ~/.minio and export /data directories. To do this, run the below commands

It mentions `~/.minio` but I believe it is not mapped to host if you follow the recommended commands:

```
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  --name minio1 \
  -v /mnt/data:/data \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  quay.io/minio/minio server /data --console-address ":9001"
```

I am opening this issue to verify my understanding but also improve the documentation if needs be.

Is there a recommendation on what to do to persist `~/.minio`, if my understanding is correct?

Thanks!

**Comment by ravindk89** [comment]
I think this is a minor error - the line `-v /mnt/data:/data` mounts the local path `/mnt/data` to the container path `/data`. 

The mounting of `~/.minio` to the container I would guess is to allow keeping things like TLS certs. If the example had a line `-v ~/.minio:~/.minio` I think it would meet the intent.

All of this said, @thbar I would recommend you use our [Next Gen Web Docs](https://docs.min.io/minio/baremetal/installation/deploy-minio-standalone.html#deploy-standalone-minio-in-a-container). That is where the focus of our documentation is moving forward. I can still clean this up, but our github based docs are a lower priority than keeping our web docs up-to-date.
