### ISSUE TITLE
selfsigned ssl is not working in Tenant - curl: (35) Peer reports it experienced an internal error 

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13876]
Hi,
On EKS cluster i have deployed operator and teanant, for internal communication i enabled autocert and i also am using external certs for external communication(self signed certs with public.crt and private.key).
 externalCertSecret:
      - name: aws-lb-tls-secret
        type: kubernetes.io/tls
      requestAutoCert: true

![image](https://user-images.githubusercontent.com/68953135/145568914-6344b965-e9cf-401e-a672-ff7c6f88d383.png)

But, not able to access minio externally. I verified created secret with selfsigned certs are placed.

 kubectl describe po test-ss-0-2 -n minio2
Name:         test-ss-0-2
Namespace:    minio2
Priority:     0
Node:         ip-x-x-x-x.us-east-2.compute.internal/x.x.x.x
Start Time:   Thu, 09 Dec 2021 12:53:07 +0100
Labels:       app=minio
              app.kubernetes.io/managed-by=Helm
              controller-revision-hash=test-ss-0-8644686bc6
              statefulset.kubernetes.io/pod-name=test-ss-0-2
              v1.min.io/console=test-console
              v1.min.io/pool=ss-0
              v1.min.io/tenant=test
Annotations:  kubernetes.io/psp: eks.privileged
              meta.helm.sh/release-name: test
              meta.helm.sh/release-namespace: minio2
              min.io/revision: 0
Status:       Running
IP:           x.x.x.x
IPs:
  IP:           x.x.x.x
Controlled By:  StatefulSet/test-ss-0
Containers:
  minio:
    Container ID:  docker://790e2a2fd4e51f82e11c0e8d51dbf032bacf72f3af63cc6aaad5b5b661a3f13d
    Image:         minio/minio:RELEASE.2021-10-06T23-36-31Z
    Image ID:      docker-pullable://minio/minio@sha256:73ae939f2833f645e79c40c63da7c4bccb1ff4c183705101c37463969ae3b4b7
    Ports:         9000/TCP, 9443/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      server
      --certs-dir
      /tmp/certs
      --console-address
      :9443
    State:          Running
      Started:      Thu, 09 Dec 2021 12:53:18 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      MINIO_ROOT_USER:               minio
      MINIO_ROOT_PASSWORD:           minio
      MINIO_ACCESS_KEY:              minio
      MINIO_SECRET_KEY:              minio123
      MINIO_ACCESS_KEY_OLD:          minio
      MINIO_SECRET_KEY_OLD:          minio123
      MINIO_UPDATE:                  on
      MINIO_UPDATE_MINISIGN_PUBKEY:  RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
      MINIO_ARGS:                    <set to the key 'MINIO_ARGS' in secret 'operator-webhook-secret'>  Optional: false
      MINIO_ENDPOINTS:               https://test-ss-0-{0...3}.test-hl.minio2.svc.cluster.local/export{0...3}/data
      MINIO_OPERATOR_VERSION:        v4.3.5
      MINIO_ROOT_USER:               <set to the key 'accesskey' in secret 'minio-secret'>  Optional: false
      MINIO_ROOT_PASSWORD:           <set to the key 'secretkey' in secret 'minio-secret'>  Optional: false
      MINIO_SERVER_URL:              https://minio.minio2.svc.cluster.local:443
    Mounts:
      /export0 from data0 (rw)
      /export1 from data1 (rw)
      /export2 from data2 (rw)
      /export3 from data3 (rw)
      /tmp/certs from test-tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-z77cv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  data0:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data0-test-ss-0-2
    ReadOnly:   false
  data1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data1-test-ss-0-2
    ReadOnly:   false
  data2:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data2-test-ss-0-2
    ReadOnly:   false
  data3:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data3-test-ss-0-2
    ReadOnly:   false
  test-tls:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          aws-lb-tls-secret
    SecretOptionalName:  <nil>
    SecretName:          test-tls
    SecretOptionalName:  <nil>
    SecretName:          operator-tls
    SecretOptionalName:  <nil>
  default-token-z77cv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-z77cv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

**Comment by Bhagi33** [comment]
Its urgent , please respond.

**Comment by klauspost** [comment]
@Bhagi33 If you need urgent responses, look into our [Subscription Offer](https://min.io/pricing) where we operate on an SLA.

It could be you are getting this error: https://github.com/golang/go/blob/master/src/crypto/tls/handshake_client_test.go#L2165 - though I can't pin down the exact place it is generated.

It seems to show up when an invalid cert is used. Check your generation method.

**Comment by harshavardhana** [comment]
> It seems to show up when an invalid cert is used. Check your generation method.

Mostly public.crt and private.key's are wrong.

**Comment by harshavardhana** [comment]
Looks like an Ingress TLS configuration error - closing.

**Comment by Bhagi33** [comment]
previously i tried with openssl self signed. now I tried self signed ssl with certmanager as well.. 
I am sure there is no issue with SSL certs.  i verified certs are copied inside pod.

curl -k https://*.aws.com:30022
curl: (35) Peer reports it experienced an internal error

What exactly you mean. Ingress TLS configuration error  I have not yet enabled Ingress for this Minio.

**Comment by Bhagi33** [comment]
Hi Team,
Can you please respond.
