### ISSUE TITLE
it allways occur the error "max key length is 3072 bytes" in the mysql 8.0.26 when I config the settings of "bucket notifaction" in the minio

### ISSUE THREAD

**Issue by aming439836** [minio/minio#13892]
when I config the setting of the bucket notifacation in the Minio client  by the mysql version 8.0.26 ,and it allways ocuurs the error "unable to set 'notify_mysql:.................................'to server .Error 1071:Specified key was too long; max key length is 3072 bytes.  why about it ? how to reslove it ?

**Comment by harshavardhana** [comment]
Please open a proper GitHub issue with reproducer etc.
