### ISSUE TITLE
S3 Select WHERE IS clause doesn't work 

### ISSUE THREAD

**Issue by lenahi** [minio/minio#13900]
Sample input csv file:
c1|c2|c3
1|2|3
1||3

Code Sample(python3.8):
result = s3.select_object_content(
Bucket=bucket_name,
Key=s3object,
ExpressionType='SQL',
Expression='select * from S3object where _2 IS NOT NULL',
InputSerialization={
'CSV': {"FileHeaderInfo": "IGNORE", 'FieldDelimiter': '|'}
},
OutputSerialization={'CSV': {}},
)

## Expected Behavior
the query should works and return the data which is not null. and the "IS" keyword is supported by boto3.

## Current Behavior
An error occurred (ParseSelectFailure) when calling the SelectObjectContent operation: :1:33: unexpected token "IS"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
You can use `select * from S3object where _2 != ''`. I am not sure if an empty value is NULL on S3.

That being said the `IS (NOT) NULL` does not work.

**Comment by lenahi** [comment]
hello:
The "IS" key word is supported by boto3, but seems not support by minio by feedback from boto3.
please check the ticket opend below.
https://github.com/boto/boto3/issues/3091#issuecomment-992720679

You are right, an empty value is NULL on S3. 
I tried your suggestion select * from S3object where _2 != ''.  yes, it can success get the not null data.

For the comparison operators, what's the correct proper syntax? I tried the following which did not work:
 "select * from S3object where _2 != '' and _2 > 1"?
"select * from S3object  where _2 > 1 "? 
the above all get error below:
 _error: An error occurred (InternalError) when calling the SelectObjectContent operation: Could not convert []byte{} to a number

**Comment by LenaJava** [comment]
Hello, Primes:
Thanks a lot for your support.

The "IS" key word is supported by boto3, but seems not support by minio by feedback from boto3.
please check the ticket opend below.
boto/boto3#3091 (comment)<https://github.com/boto/boto3/issues/3091#issuecomment-992720679>
You are right, an empty value is NULL on S3.
I tried your suggestion select * from S3object where _2 != ''. yes, it can success get the not null data.
but how can I get the data that not null and > {data}?
such as:
"select * from S3object where c2 != '' and c2 > 1"?
seems this is not works with error below:
error: An error occurred (InternalError) when calling the SelectObjectContent operation: Could not convert []byte{} to a number

**Comment by klauspost** [comment]
@LenaJava An empty value is not a number, so it cannot be compared against a number.

I sent in #13914 which will allow you to do `select * from S3object where _2 != '' AND _2 > 1`.

**Comment by LenaJava** [comment]
I tried select * from S3object  where _2 != '' AND _2 > 1 did not work.
there has error:
S3 query failed, error=An error occurred (InternalError) when calling the SelectObjectContent operation: Could not convert []byte{} to a numbe

**Comment by lenahi** [comment]
That's great, thanks a lot.
