### ISSUE TITLE
panic: "GET /bucket/?continuation-token=MjAyMS0xMS0wNV...

### ISSUE THREAD

**Issue by kgrodzicki** [minio/minio#13915]
I have a setup with MinIO hot tier and warm tier and "mc mirror" mirroring from the hot tier to warm tier server.
MinIO warm tier server panics with invalid memory address or nil pointer dereference. There is no congestion on the CPU or available memory on the hardware machine. 

## Expected Behavior

The server should not panic with the "memory address or nil pointer dereference. ". It should provide log message that describes problem and maybe suggest a solution to it.

## Current Behavior

Warm tier server logs panics stacktraces. See attached [server.log](https://github.com/minio/minio/files/7719012/server.log) file.

## Steps to Reproduce (for bugs)

None

## Regression
 Not sure

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-12-10T23-03-39
* Server setup and configuration:
Hot tier: 4 disks 0,5TB SSD
Warm tier: 4 disks 15TB HDD (4TB used by the server atm)
Hardware: 
* Operating System and version (`uname -a`):
Linux server 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
@kgrodzicki I have added a PR #13917 that removes the symptoms of the problem. 

That said you should check your system, in particular if connections between servers are stable.

**Comment by kgrodzicki** [comment]
@klauspost thank you for the fast reply and PR!

The MinIO hot tier, mc mirror process and MinIO warm tier server are running on the same hardware, I guess connections between the servers should not be a problem.

In case of this panic, does it mean that TCP connection is already closed?

**Comment by klauspost** [comment]
@kgrodzicki This happens when no remote servers are marked as online. It probably isn't related to tiering.
