### ISSUE TITLE
Read files without checksum through HDFS gateway

### ISSUE THREAD

**Issue by zijie0** [minio/minio#13927]
## Expected Behavior

Some files on HDFS might not have corresponding checksum info, for example in deltalake: https://github.com/delta-io/delta/issues/865

We should be able to read this kind of files via MinIO HDFS gateway.

## Current Behavior

Reading files without checksum would throw an exception:

```
API: GetObject(bucket=some_bucket, object=some_delta_table/_delta_log/00000000000000000000.json)
Time: 12:20:03 UTC 12/13/2021
DeploymentID: 9af18baf-b9bd-45c7-b570-2d1a6e0d6f60
RequestID: 16C04FCC5A225C8D
RemoteHost: xx.xx.xx.xx
Host: yy.yy.yy.yy:9011
UserAgent: Botocore/1.21.21 Python/3.8.10 Windows/10
Error: unsupported checksum type: 0 (*errors.errorString)
       3: cmd/gateway/hdfs/gateway-hdfs.go:295:hdfs.hdfsToObjectErr()
       2: cmd/gateway/hdfs/gateway-hdfs.go:636:hdfs.(*hdfsObjects).getObject()
       1: cmd/gateway/hdfs/gateway-hdfs.go:597:hdfs.(*hdfsObjects).GetObjectNInfo.func1()
```

## Possible Solution

Maybe we could add some configuration parameters for HDFS gateway to disable the checksum check.

The error seems to be reported by hdfs library: 
https://github.com/colinmarc/hdfs/blob/f2f512db170db82ad41590c4ba3b7718b13317d2/internal/transfer/block_reader.go#L157-L166

I'm not sure if there's any parameter to control the checksum validation behavior.

## Steps to Reproduce (for bugs)

1. Write an delta table to HDFS storage through Spark.
2. Setup a MinIO HDFS gateway following the [instructions](https://docs.min.io/docs/minio-gateway-for-hdfs.html).
3. Read the same delta table through s3 protocol, here we used Python package [s3fs](https://github.com/fsspec/s3fs).
4. Read failed and error log reported by MinIO.

## Context

Could not use MinIO HDFS gateway for all deltalake tables. It would also affect other scenarios when checksum is disabled on HDFS.

## Regression

No.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration: Using Docker.
* Operating System and version (`uname -a`):  Linux 3.10.0-1160.15.2.el7.x86_64

**Comment by harshavardhana** [comment]
Gateway implementations is not taking anymore features.

Please use MinIO distributed setup and migrate from HDFS.  Gateway scope is meant for you to migrate data to MinIO distributed setups.

Perpetually use of HDFS is not our goal here.
