### ISSUE TITLE
Unable to deploy in distributed mode, works in standalone

### ISSUE THREAD

**Issue by rwb99** [minio/minio#13920]
long story shorting I'm setting up nextcloud talk as a "private" chatting alternative.

I'm able to get 4 standalone minio instances working but when i try to connect then it all stops working.

## Expected Behavior

being able to access the control panel from any of the ips used in deployment

## Current Behavior

This site can’t be reached x.x.x.x refused to connect. + errors that dont bring up much on google.
## Possible Solution

pray to our lord and savior the IT gods
~~no idea i've been tinkering with it all day I'm hungry now ):~~

## Steps to Reproduce (for bugs)

1. follow [this](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-18-04) guide 
2. work ✅
3. change /usr/local/share/minio/ -> http://1.cdn.rb99.club http://2.cdn.rb99.club http://3.cdn.rb99.club http://4.cdn.rb99.club
4. sudo service minio restart
5. no work ❌

## Context

i wanna set minio as main storage in nextcloud install.
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
ubuntu 

didn't feel like redacting info just dont stalk ok... its creepy... it probaly makes it easier to diagnose.
![image](https://user-images.githubusercontent.com/63825594/146263997-bd5fbf0b-37a2-4c55-b1e2-bc941aa83ec9.png)

**Comment by harshavardhana** [comment]
> This site can’t be reached x.x.x.x refused to connect. + errors that dont bring up much on google.

First, 

- make sure to fix your firewall so that it can be reached. 
- make sure `minio` binaries are the same on all the nodes we do not allow mix and match 
- make sure MinIO service can read the data drives (you have 'file access denied') - means you need to fix drive permissions. 

These are the most basic things you have to ensure works.

Also wrong command style 

> change /usr/local/share/minio/ -> http://1.cdn.rb99.club http://2.cdn.rb99.club http://3.cdn.rb99.club http://4.cdn.rb99.club

Use ellipses style

> change /usr/local/share/minio/ -> http://{1...4}.cdn.rb99.club

**Comment by rwb99** [comment]
i tried http://{1...4}.cdn.rb99.club first that didn't work. 

i just tried  

MINIO_VOLUMES="http://{1...4}.cdn.rb99.club/usr/local/share/minio/" 

& now it says "ERROR Unable to initialize backend: Unsupported backend format"

i dont have drives im using the internal storage of the vps's the file path is /usr/local/share/minio/

**Comment by rwb99** [comment]
on all 4 servers 

MINIO_VOLUMES="/usr/local/share/minio/" 

they all work standalone 

but if any of the following wont work

MINIO_VOLUMES="http://{1...4}.cdn.rb99.club" 

MINIO_VOLUMES="http://1.cdn.rb99.club http://2.cdn.rb99.club http://3.cdn.rb99.club http://4.cdn.rb99.club" 

MINIO_VOLUMES="http://{1...4}.cdn.rb99.club/usr/local/share/minio/" 


-------------------
my config

MINIO_ROOT_USER="redacted"
MINIO_ROOT_PASSWORD="redacted"
MINIO_OPTS="-C /etc/minio --address 78.47.110.204:42069 --console-address 78.47.110.204:12345"
MINIO_VOLUMES="http://{1...4}.cdn.rb99.club/usr/local/share/minio/"

--------------------

config is the same on all except the ip

**Comment by harshavardhana** [comment]
> MINIO_VOLUMES="http://{1...4}.cdn.rb99.club/usr/local/share/minio/"

If you used this before in single drive mode - you need to move content present here. 

> MINIO_OPTS="-C /etc/minio --address 78.47.110.204:42069 --console-address 78.47.110.204:12345"

You can also set `--address` if your cdn.rb99 resolves to these IPs.

**Comment by rwb99** [comment]
Dec 16 00:44:47 rb99 minio[5700]: API: SYSTEM()
Dec 16 00:44:47 rb99 minio[5700]: Time: 00:44:47 UTC 12/16/2021
Dec 16 00:44:47 rb99 minio[5700]: Error: Marking http://3.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42 temporary offline; caused by Post "http://3.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 78.47.110.204:42069: connect: connection refused (*fmt.>Dec 16 00:44:47 rb99 minio[5700]:        6: internal/rest/client.go:149:rest.(*Client).Call()
Dec 16 00:44:47 rb99 minio[5700]:        5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
Dec 16 00:44:47 rb99 minio[5700]:        4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
Dec 16 00:44:47 rb99 minio[5700]:        3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
Dec 16 00:44:47 rb99 minio[5700]:        2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
Dec 16 00:44:47 rb99 minio[5700]:        1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Dec 16 00:44:48 rb99 minio[5700]: Client http://3.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42 online
Dec 16 00:44:57 rb99 minio[5700]: API: SYSTEM()
Dec 16 00:44:57 rb99 minio[5700]: Time: 00:44:57 UTC 12/16/2021
Dec 16 00:44:57 rb99 minio[5700]: Error: Marking http://4.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42 temporary offline; caused by Post "http://4.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 71.234.189.151:42069: connect: connection refused (*fmt>Dec 16 00:44:57 rb99 minio[5700]:        6: internal/rest/client.go:149:rest.(*Client).Call()
Dec 16 00:44:57 rb99 minio[5700]:        5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
Dec 16 00:44:57 rb99 minio[5700]:        4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
Dec 16 00:44:57 rb99 minio[5700]:        3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
Dec 16 00:44:57 rb99 minio[5700]:        2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
Dec 16 00:44:57 rb99 minio[5700]:        1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Dec 16 00:44:57 rb99 minio[5700]: ERROR Unable to initialize backend: Unsupported backend format [fs] found on /usr/local/share/minio
Dec 16 00:44:57 rb99 systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 00:44:57 rb99 systemd[1]: minio.service: Failed with result 'exit-code'.
Dec 16 00:44:57 rb99 systemd[1]: minio.service: Scheduled restart job, restart counter is at 11.
Dec 16 00:44:57 rb99 systemd[1]: Stopped MinIO.
Dec 16 00:44:57 rb99 systemd[1]: Starting MinIO...
Dec 16 00:44:57 rb99 systemd[1]: Started MinIO.

**Comment by rwb99** [comment]
not sure why it adds the "/minio/storage" 

http://x.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42
http://x.cdn.rb99.club:42069/usr/local/share/minio/v42

**Comment by rwb99** [comment]
also its not the firewall

**Comment by harshavardhana** [comment]
> [ttp://3.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42](http://3.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42) temporary offline; caused by Post "http://3.cdn.rb99.club:42069/minio/storage/usr/local/share/minio/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 78.47.110.204:42069: connect: connection refused (*fmt.>Dec 16 00:44:47 rb99 minio[5700]: 6: internal/rest/client.go:149:rest.(*Client).Call()

Your ports are not open https://github.com/minio/minio#deployment-recommendations

**Comment by rwb99** [comment]
they were

i just changed /usr/local/share/minio/ to /data & it works now

originally i mkdir /usr/local/share/minio/ for the tutorial 

but i re did it mkdir /data 

MINIO_VOLUMES="http://{1...4}.cdn.rb99.club/data"

IT WORKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/63825594/146289950-f39f970c-20f0-482b-9ff4-59f1653d6b28.png)

**Comment by rwb99** [comment]
![image](https://user-images.githubusercontent.com/63825594/146291186-afe4bfc7-7be5-48d4-a534-f0f9dd002c48.png)

that's so cool

any good way of limiting the amount of available storage per "drive"?
![image](https://user-images.githubusercontent.com/63825594/146291314-ab372072-476f-4286-9817-49791f4d0e22.png)

**Comment by rwb99** [comment]
or will it auto limit to the lowest one because its like raid? that's fine as i dont need much space i plan on it being like snapchat where most stuff is deleted unless saved

**Comment by klauspost** [comment]
> any good way of limiting the amount of available storage per "drive"?

That is not how MinIO works. Use similar sized drives with no "extra" data.

**Comment by rwb99** [comment]
> > any good way of limiting the amount of available storage per "drive"?
> 
> That is not how MinIO works. Use similar sized drives with no "extra" data.

If money didn't exist I would. I don't get paid for this it's just for fun.

I would have just used 2 servers but it made me use 4.

I can't do standalone because it won't let me make buckets and i wanted to set nextcloud data directory to s3 compatible so i wouldn't have to worry about the little storage I get on hetzner. 

I really am only doing this because bordem, the experience & because i don't use Snapchat for anything but talking to friends & it keeps killing my phone battery so i thought why not use nextcloud talk + minio.
