### ISSUE TITLE
Search for objects based on the object's tags

### ISSUE THREAD

**Issue by rkedward** [minio/minio#13939]
**Is your feature request related to a problem? Please describe.**
I can assign tags to an object but I can't search for an object based on its user-applied tags.

**Describe the solution you'd like**
I'd like to be able to find objects that match either ALL or ANY tag values in a given name-value set. 

**Describe alternatives you've considered**
Use a secondary index.

**Additional context**

**Comment by harshavardhana** [comment]
There is no "Search" in S3 API @rkedward - you need to build this yourself outside of MinIO.
