### ISSUE TITLE
root admin user does not have consoleAdmin privilege

### ISSUE THREAD

**Issue by bpedersen2** [minio/minio#13949]
Starting  with release RELEASE.2021-12-18T04-42-33Z the root user (set via MINIO_ROOT_USER) does not have web console admin privileges in a fresh (docker-based) installation. 

## Expected Behavior
The root user defined via MINIO_ROOT_USER has console admin privileges per default

## Current Behavior
The root user does not have admin capabilities in the web console. The user still  has the admin rights via the mc admin  tool. 
Problem: As the root user is not available for setting additional access policies I can not grant consoleAdmin /diagnotics for this user.

 Yes

 RELEASE.2021-12-18T04-42-33Z -> bad
 RELEASE.2021-12-10T23-03-39Z  -> good

 Server setup and configuration:
deployed via docker-compose

**Comment by bpedersen2** [comment]
Note: if upgrading from a working install (RELEASE.2021-12-10T23-03-39Z ) everything works as expected.

**Comment by bpedersen2** [comment]
Looks like https://github.com/minio/minio/pull/13947 should fix this.

**Comment by klauspost** [comment]
@bpedersen2 Correct.
