### ISSUE TITLE
cannot create bucket

### ISSUE THREAD

**Issue by betterlq** [minio/minio#13948]
## Expected Behavior

I shoud be able to create bucket after setup minio by docker.
## Current Behavior

but I can create a bucket, the button is greyed out, it seems access deny.
## Steps to Reproduce (for bugs)

1.
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  --name myminio \
  -e "MINIO_ROOT_USER=minio" \
  -e "MINIO_ROOT_PASSWORD=minio123" \
  -v /root/application/minio/data:/data \
  quay.io/minio/minio server /data --console-address ":9001"
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-12-18T04-42-33Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux localhost.localdomain 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is a regression in the Console UI behavior fixed in #13947
