### ISSUE TITLE
XL/rpcClient: Handle network disconnects

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1395]
Currently gorpc does not reconnect if there is a network disconnect. This should be handled.

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by GarimaKapoor** [comment]
@nl5887 please update the timeline for the fix.

**Comment by krisis** [comment]
I am working on this issue. I hope to send a PR by EOD Aug 14th.
