### ISSUE TITLE
Help! I found that the Create Bucket button can't be clicked

### ISSUE THREAD

**Issue by dongzhe1208** [minio/minio#13956]
I use docker run to deploy the minio lateset, when my deployment is completed, after I successfully logged in to the http://IP:9000,
I found that the Create Bucket button can't be clicked, Why? I did it. Is there a problem?
![image](https://user-images.githubusercontent.com/89840314/146862846-f9d30607-909c-4c72-804f-e52fe1ee0cd3.png)

**Comment by harshavardhana** [comment]
Update to RELEASE.2021-12-20T22-07-16Z

**Comment by wojiushixiaobai** [comment]
me too. /(ㄒoㄒ)/~~
success: `quay.io/minio/minio:latest`
fail: `minio/minio:latest`

faulty documentation: http://docs.minio.org.cn/

**Comment by harshavardhana** [comment]
> me too. /(ㄒoㄒ)/~~ use: `quay.io/minio/minio:latest` not: `minio/minio:latest`

Use the correct tags `RELEASE.2021-12-20T22-07-16Z`
