### ISSUE TITLE
"Create Bucket" button is greyed out, Dashboard lacking essential functions

### ISSUE THREAD

**Issue by mosjr** [minio/minio#13951]
Just installed minio as usual on Ubunu 20.04 following the get started instructions.  I launch the server by the command "minio server /path/to/data" 
In the dashboard many buttons are greyed out and the 
dashboard is missing many options
I used to install minio following the same steps and it would work ok, this time it is broken

![Screenshot from 2021-12-20 14-20-49](https://user-images.githubusercontent.com/43234391/146766969-b355a28b-95b1-4b66-96bd-4f640fe2debf.png)

**Comment by chowel** [comment]
I have the same problem;When I do, I'm using a Java client to Create Bucket,putObject is OK

**Comment by juancash** [comment]
I have the same problem

**Comment by nederxal** [comment]
Hello, same probleme here (Widnows or Linux).

I downloaded the latest version for a try and now I can't do anything in the web interface.

```
.\minio.exe -v
minio.exe version RELEASE.2021-12-18T04-42-33Z
```

**Comment by enra64** [comment]
Same here... Not even the root user can't do anything, like show bucket content... On the other hand, some other more restricted user is able to list the bucket contents?

Edit: just went back to minio/minio:RELEASE.2021-12-10T23-03-39Z, works there

**Comment by nederxal** [comment]
Seems the correction will arrives with   https://github.com/minio/minio/pull/13947

wait and see

**Comment by taisph** [comment]
I have a user in a group with the `consoleAdmin` policy which is seeing the same screen as @elnaggar-dev after upgrading to RELEASE.2021-12-18T04-42-33Z. Adding the policy directly on the user works around this issue.

**Comment by harshavardhana** [comment]
> I have a user in a group with the `consoleAdmin` policy which is seeing the same screen as @elnaggar-dev after upgrading to RELEASE.2021-12-18T04-42-33Z. Adding the policy directly on the user works around this issue.

@donatello ^^
