### ISSUE TITLE
mc if alias is not configured, data copied to a directory with that name in current workdir

### ISSUE THREAD

**Issue by Daniel-Nashed** [minio/minio#13964]
## Expected Behavior
I am not sure if there is a way to tell `mc` to not use an not existing alias as a directory.  
Changing the default behavior would break existing functionality. So I would propose a new option. 

## Current Behavior
If the alias is not configured a directory is assumed, which could cause unwanted copy operations.  

## Possible Solution
Instead an error should be returned, that the alias is not found.   
This should be an option instead of changing the current behavior.  
Maybe there is an option that I did not find?

## Context
Backup application which should store databases remotely, not on it's own data directory.  
It happens when an admin provides the wrong configuration or in a Docker container does not move it from the home directory, which is empty on every restart. Explicitly specifying the configuration is not a complete solution for all cases.

## Environment

mc version RELEASE.2021-11-16T20-37-36Z
CentOS Stream 
Linux 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is expected. Please configure an alias. If you don't do it - it chooses local directory.

**Comment by Daniel-Nashed** [comment]
OK, I am not saying the default configuration should change.  
But thanks for indirectly confirming there is no option to disable the functionality.  

If the configuration is wrong or lost, this would cause unwanted copy to a local disk.  
This can fill the local disk which can cause the server to stop working.  
For many customers securing their environment is important.  
I will document it as a critical limitation when using `mc` in our software.  

Thanks  
Daniel
