### ISSUE TITLE
STS check Audience 'aud' in JWT

### ISSUE THREAD

**Issue by DAGorchakov** [minio/minio#13960]
According to [code](https://github.com/minio/minio/blob/b14527b7afa15e14f4fd8ad671adcc4ca472948b/cmd/sts-handlers.go#L360) 'aud' == clientID, so I add mapping audience to client 'ua.minio' with wrong 'aud' and try to enter Minio and it is success  

![image](https://user-images.githubusercontent.com/17656075/146932745-e773e7f7-9cdf-4f0d-ac43-7264c9c8ea6f.png)

## Expected Behavior
According to [RFC6819](https://datatracker.ietf.org/doc/html/rfc6819#section-5.1.5.5) minio have to check 'aud' and reject request to enter if it is wrong

## Current Behavior
Nowadays, I can enter minio with any audience in client mapping

## Possible Solution
Can you make minio to check this key?

## Context
This fix helps to prevent from getting wrong client rights in multiclient setup of keycloak

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-12-20T22-07-16Z
* Operating System and version (`uname -a`): Linux 3.10.0-1160.49.1.el7.x86_64 Red Hat Enterprise Linux Server 7.9 (Maipo)

**Comment by harshavardhana** [comment]
"aud" is not the only thing that is valid @DAGorchakov some IDPs require "azpClaim" as a fallback.

```
        if !audValues.Contains(globalOpenIDConfig.ClientID) {
                // if audience claims is missing, look for "azp" claims.
                // OPTIONAL. Authorized party - the party to which the ID
                // Token was issued. If present, it MUST contain the OAuth
                // 2.0 Client ID of this party. This Claim is only needed
                // when the ID Token has a single audience value and that
                // audience is different than the authorized party. It MAY
                // be included even when the authorized party is the same
                // as the sole audience. The azp value is a case sensitive
                // string containing a StringOrURI value
                azpValues, ok := iampolicy.GetValuesFromClaims(m, azpClaim)
                if !ok {
                        writeSTSErrorResponse(ctx, w, true, ErrSTSInvalidParameterValue,
                                errors.New("STS JWT Token has `aud` claim invalid, `aud` must match configured OpenID Client ID"))
                        return
                }
                if !azpValues.Contains(globalOpenIDConfig.ClientID) {
                        writeSTSErrorResponse(ctx, w, true, ErrSTSInvalidParameterValue,
                                errors.New("STS JWT Token has `azp` claim invalid, `azp` must match configured OpenID Client ID"))
                        return
                }
        }
```

So if your azp is valid then we allow it anyways. We are working with the RFC expectation.s.
