### ISSUE TITLE
500/invalid login to localhost MinIO console using default root user/pass

### ISSUE THREAD

**Issue by faebiedev** [minio/minio#13966]
Getting 500s/invalid login when trying to log into MinIO console using default root user/pass `minioadmin`

## Expected Behavior
Previously, while running MinIO locally, I could log into console using default root user/pass `minioadmin`.

```
API: http://xx.xx.xxx.238:9000  http://10.0.0.215:9000  http://127.0.0.1:9000             
RootUser: minioadmin 
RootPass: minioadmin 

Console: http://xx.xx.xxx.238:56451 http://10.0.0.215:56451 http://127.0.0.1:56451       
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://xx.xx.xxx.238:9000 minioadmin minioadmin

Documentation: https://docs.min.io
```

## Current Behavior
When attempting to login, I get 500 Invalid Login

![Screen Shot 2021-12-21 at 2 40 47 PM](https://user-images.githubusercontent.com/53846457/147007146-e822adfb-d28c-4548-87a1-7e508f6afc43.png)

```
mc admin trace local
mc: <ERROR> Unable to listen to http trace. Access Denied.
```
```
API: SYSTEM()
Time: 14:41:09 PST 12/21/2021
DeploymentID: 5e1e0fcf-563c-452d-8235-50a1fa48dd5f
Error: Access Denied. (*errors.errorString)
       requestHeaders={"method":"GET","reqURI":"/minio/admin/v3/trace?err=false&internal=false&os=false&s3=true&storage=false&threshold=0s","header":{"Host":["localhost:9000"],"User-Agent":["MinIO (darwin; amd64) madmin-go/0.0.1 mc/RELEASE.2021-12-20T23-43-34Z"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]}}
       4: cmd/auth-handler.go:154:cmd.validateAdminSignature()
       3: cmd/auth-handler.go:165:cmd.checkAdminRequestAuth()
       2: cmd/admin-handlers.go:1112:cmd.adminAPIHandlers.TraceHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

## Context
Trying to develop/access console locally

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-12-20T22-07-16Z`
* Server setup and configuration:
* Operating System and version (`uname -a`): `Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64`

**Comment by harshavardhana** [comment]
Closing as per https://github.com/minio/minio/issues/13965#issuecomment-999143617
