### ISSUE TITLE
401s/unauthorized login to localhost MinIO console

### ISSUE THREAD

**Issue by faebiedev** [minio/minio#13965]
Recently started getting 401s/unauthorized login when trying to log into MinIO console using default root user/pass `minioadmin`

## Expected Behavior
Previously, while running MinIO locally, I could log into console using default root user/pass `minioadmin`. 
```
API: http://xx.xx.xx.238:9000  http://10.0.0.215:9000  http://127.0.0.1:9000             
RootUser: minioadmin 
RootPass: minioadmin 

Console: http://xx.xx.xx.238:53672 http://10.0.0.215:53672 http://127.0.0.1:53672       
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://xx.xx.xx.238:9000 minioadmin minioadmin

Documentation: https://docs.min.io
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
```

## Current Behavior
When attempting to login, I get 401 Unauthorized. 

![Screen Shot 2021-12-21 at 1 10 43 PM](https://user-images.githubusercontent.com/53846457/146998176-ea58404b-e681-437b-acbc-09340e78fac7.png)

```
mc admin trace local
mc: <ERROR> Unable to listen to http trace. Access Denied.
```

```
API: SYSTEM()
Time: 13:12:36 PST 12/21/2021
DeploymentID: 5e1e0fcf-563c-452d-8235-50a1fa48dd5f
Error: Access Denied. (*errors.errorString)
       requestHeaders={"method":"GET","reqURI":"/minio/admin/v3/trace?err=false&internal=false&os=false&s3=true&storage=false&threshold=0s","header":{"Host":["localhost:9000"],"User-Agent":["MinIO (darwin; amd64) madmin-go/0.0.1 mc/RELEASE.2021-12-20T23-43-34Z"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]}}
       4: cmd/auth-handler.go:154:cmd.validateAdminSignature()
       3: cmd/auth-handler.go:165:cmd.checkAdminRequestAuth()
       2: cmd/admin-handlers.go:1045:cmd.adminAPIHandlers.TraceHandler()
       1: net/http/server.go:2049:http.HandlerFunc.ServeHTTP()
```

## Context
Trying to develop/access console locally

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-08-31T05-46-54Z`
* Server setup and configuration: 
* Operating System and version (`uname -a`): Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): `minio version RELEASE.2021-08-31T05-46-54Z`

Please upgrade @belac9001

**Comment by faebiedev** [comment]
still getting failed login after updating, 500 error with invalid login/timeout
```
{code: 500,…}
code: 500
detailedMessage: "Post \"http://10.88.191.238:9000/\": dial tcp 10.88.191.238:9000: i/o timeout"
message: "invalid Login"
```

**Comment by harshavardhana** [comment]
> ```
> {code: 500,…}
> code: 500
> detailedMessage: "Post \"http://10.88.191.238:9000/\": dial tcp 10.88.191.238:9000: i/o timeout"
> message: "invalid Login"
> ```

Yes your server is not reachable @belac9001 - make sure its reachable either by using 

- --net=host to the expose the ports locally 
- or use MINIO_SERVER_URL=http://localhost:9000

**Comment by faebiedev** [comment]
hey, thx for reply, can close #13966, wasn't sure if this would get replies with it being closed

**Comment by faebiedev** [comment]
> > ```
> > {code: 500,…}
> > code: 500
> > detailedMessage: "Post \"http://10.88.191.238:9000/\": dial tcp 10.88.191.238:9000: i/o timeout"
> > message: "invalid Login"
> > ```
> 
> Yes your server is not reachable @belac9001 - make sure its reachable either by using
> 
> * --net=host to the expose the ports locally
> * or use MINIO_SERVER_URL=http://localhost:9000

thanks! setting MINIO_SERVER_URL fixed the issue
