### ISSUE TITLE
 Unable to initialize remote tier pending deletes journal: no local disk found

### ISSUE THREAD

**Issue by bmmpp** [minio/minio#13979]
I used  centos systemd to start, stop minio server and used systemctl enalbe minio.service to set server start self.
 when centos reboot the minio server will start self, but start failed.

Time: 11:30:56 CST 12/23/2021
Error: WARNING: Expected number of all hosts (2) to be remote +1 (2) (*errors.errorString)
       4: cmd/peer-rest-client.go:943:cmd.newPeerRestClients()
       3: cmd/notification.go:1276:cmd.NewNotificationSys()
       2: cmd/server-main.go:219:cmd.newAllSubsystems()
       1: cmd/server-main.go:451:cmd.serverMain()

API: SYSTEM()
Time: 11:30:56 CST 12/23/2021
Error: Marking http://xx.xx.0.15:9000/minio/storage/usr/share/minio/data/v42 temporary offline; caused by Post "http://xx.xx.0.15:9000/minio/storage/usr/share/minio/data/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp xx.xx.0.15:9000: connect: network is unreachable (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 11:30:56 CST 12/23/2021
Error: Marking http://xx.xx.0.6:9000/minio/storage/usr/share/minio/data3/v42 temporary offline; caused by Post "http://xx.xxx.0.6:9000/minio/storage/usr/share/minio/data3/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp xx.xx.0.6:9000: connect: network is unreachable (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 11:30:56 CST 12/23/2021
Error: Marking http://xx.xx.0.6:9000/minio/storage/usr/share/minio/data4/v42 temporary offline; caused by Post "http://xx.xx.0.6:9000/minio/storage/usr/share/minio/data4/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp xx.xx.0.6:9000: connect: network is unreachable (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 11:30:56 CST 12/23/2021
Error: Marking http://xx.xx.0.15:9000/minio/storage/usr/share/minio/data2/v42 temporary offline; caused by Post "http://xx.xx.0.15:9000/minio/storage/usr/share/minio/data2/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp xx.xx.0.15:9000: connect: network is unreachable (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 11:30:56 CST 12/23/2021
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:317:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
       2: cmd/server-main.go:643:cmd.newObjectLayer()
       1: cmd/server-main.go:523:cmd.serverMain()
Waiting for a minimum of 2 disks to come online (elapsed 1s)

Disk `http://xx.xx.0.15:9000/usr/share/minio/data` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
Disk `http://xx.xx.0.15:9000/usr/share/minio/data2` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.

API: SYSTEM()
Time: 11:30:57 CST 12/23/2021
DeploymentID: e9dd4667-63de-4086-a2e8-fe44ce819f16
Error: dataUpdateTracker.start: No drives specified (*errors.errorString)
       1: cmd/data-update-tracker.go:207:cmd.(*dataUpdateTracker).start()

API: SYSTEM()
Time: 11:30:57 CST 12/23/2021
DeploymentID: e9dd4667-63de-4086-a2e8-fe44ce819f16
Error: Disk: http://xx.xx.0.6:9000/usr/share/minio/data3 returned Server expects 'storage' API version 'v42', instead found 'v42' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-11-24T23-19-33Z) (*fmt.wrapError)
       endpoint=http://xx.xx.0.6:9000/usr/share/minio/data3
       2: cmd/prepare-storage.go:50:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:224:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 11:30:57 CST 12/23/2021
DeploymentID: e9dd4667-63de-4086-a2e8-fe44ce819f16
Error: Disk: http://xx.xx.0.6:9000/usr/share/minio/data4 returned Server expects 'storage' API version 'v42', instead found 'v42' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-11-24T23-19-33Z) (*fmt.wrapError)
       endpoint=http://xx.xx.0.6:9000/usr/share/minio/data4
       2: cmd/prepare-storage.go:50:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:224:cmd.(*erasureSets).connectDisks.func2()
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Automatically configured API requests per node based on available memory on the system: 120
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
ERROR Unable to initialize remote tier pending deletes journal: no local disk found

## Expected Behavior

please help!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2021-11-24T23-19-33Z
* Server setup and configuration:  Two nodes, two hard disks per node
* Operating System and version (`uname -a`): Linux VM-0-6-centos 4.18.0-305.7.1.el8_4.x86_64 #1 SMP Tue Jun 29 21:55:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This setup looks completely broken. Not sure what we can do here. 

You may have to redo your setup. You might have missed quite a few things here setting up the system.
