### ISSUE TITLE
x509: certificate is not valid for any names, but wanted to match minio-ss-0-1.minio-hl.tenant.svc.cluster.local 

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13973]
Hi Team,

****Testing - CASE1-SSL: Tested with below case , observing error**
requestAutoCert: false,
externalCaCertSecret:
    - name: cacert-secret
       type: kubernetes.io/tls
 externalCertSecret:
      - name: cert-secret
        type: kubernetes.io/tls

1. I deployed Minio operator in EKS cluster .An trying to configure ssl with external certificate(). but facing issues
2.  successfully I created a own CA .crt ,CA.key and certificate is signed by own CA , i.e public.crt and private.key.
3.  in below san.conf file i mentioned all dns names to validate minio cluster and EKS LB dns name. 
4.  [san.conf.txt](https://github.com/minio/minio/files/7762484/san.conf.txt)
5. But minio cluster is throwing this below error .

Please help me to resolve this issue
Error: 
API: SYSTEM()
Time: 11:57:18 UTC 12/22/2021
Error: https://minio-ss-0-1.minio-hl.tenant.svc.cluster.local:9000/export/data as has incorrect configuration: Post "https://minio-ss-0-1.minio-hl.tenant.svc.cluster.local:9000/minio/bootstrap/v1/verify?": x509: certificate is not valid for any names, but wanted to match minio-ss-0-1.minio-hl.tenant.svc.cluster.local (*fmt.wrapError)
       1: cmd/server-main.go:533:cmd.serverMain()
![image](https://user-images.githubusercontent.com/68953135/147091152-8ab59d0e-2d14-4345-b8e4-865f11e50cf1.png)

**Testing - CASE2-SSL: with below configuration(no external certs used)**
requestAutoCert: true
certConfig:
    commonName: "*.elb.us-east-2.amazonaws.com"
    organizationName:
    - xxxxxxx
    dnsNames:
    - "*.elb.us-east-2.amazonaws.com"
    
mc mb --with-lock minio2/target
mc: <ERROR> Unable to make bucket `minio2/target`. Put "https://k8s-minio-miniocon-xxxxxxxxxxxxxxxxxxxxx.elb.us-east-2.amazonaws.com:30022/target/": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

Please let us know we are not able to process with SSL in EKS cluster. Need your support in addressing the issue.

**Comment by harshavardhana** [comment]
Read the docs here https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-tls-via-customer-provided-certificates

You have missed important steps.
