### ISSUE TITLE
Error: too many open files, please increase 'ulimit -n' (cmd.StorageErr)

### ISSUE THREAD

**Issue by XuRong233** [minio/minio#13970]
## Current Behavior
The object non-lifecycle management is configured in the console, so that the non-current version of the file expires in 1 day.
Error: Error: too many open files, please increase'ulimit -n' (cmd.StorageErr)
ls -l /proc/23692/fd/ | wc -l
ulimit -n
1024
Modifying ulimit to 50000, restarting the service still reports an error.
Finally, the process will be killed and the service restarted without error, but deleting the non-current version object does not take effect.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> Modifying ulimit to 50000, restarting the service still reports an error.
> Finally, the process will be killed and the service restarted without error, but deleting the non-current version object does not take effect.

Nothing is reported really in this issue, no version information - no setup details. Nothing. 

Closing this as an incomplete issue.
