### ISSUE TITLE
Log Cache Errors in disk-cache.go

### ISSUE THREAD

**Issue by Miroka96** [minio/minio#13977]
Hi,

as I am currently trying to debug unknown cache errors (of minio gateway with encryption enabled, but anyway...) I would like to see them directly without building my own container. Currently, I can only see os.RemoveAll calls from disk-cache-backend.go in the trace log. The mentioned disk-cache.go file has several unhandled errors from calls to the dcache.Put method.

Best,
Miroka

**Comment by harshavardhana** [comment]
We have an issue template, we expect that you follow that @Miroka96 - this entire issue doesn't make any sense.
