### ISSUE TITLE
Administrartor cannot change his own password 

### ISSUE THREAD

**Issue by Feiniu6ABC** [minio/minio#13987]
When the user log in as a console admin, he cannot modify his own password, if he tries to do this the server responds with
`{"code":500,"detailedMessage":"an error occurred, please try again","message":"User is not allowed to be same as admin access key"}
`
Though an administrator cannot modify his own password, he can modify anyone else's password or account policy.

## Expected Behavior

Admin user can modify his own passwords or other non-admin users' password, but he cannot modify other administrators' password or policy, disablling other administrator account is also not allowed.

## Current Behavior

The administrator cannot change his own password, but he can change other administrator's password or account policy.

## Steps to Reproduce (for bugs)

1. Log in to the web page as an administrator
2. Click on users in the left bar and then select himself
3. Click on the lock icon on in the upper right of the web page to change password
4. Input the nwe password and confirm
5. At this point, it shows an error on the web page saying "User is not allowed to be same as admin access key"
6. Select another administrator, repeat the previous steps to change his password
7. The password is chagned (this is nonsense, a malicious administrator can destroy the whole database)

## Your Environment

* Version used (`minio --version`): version RELEASE.2021-11-16T20-37-36Z
* Server setup and configuration:
* Operating System and version (`uname -a`): MINGW64_NT-10.0-19042 DESKTOP-KSDCPBK 3.1.7-340.x86_64 2021-10-12 16:29 UTC x86_64 Msys
![企业微信截图_16403347782539](https://user-images.githubusercontent.com/41153766/147335024-b1a21e42-dfc8-4962-865d-351e7b22e9ed.png)

**Comment by harshavardhana** [comment]
Values set through environment variables cannot be changed through UI.

**Comment by harshavardhana** [comment]
Disabiling password change is allowed with explicit Deny rule.

Read about deny rules in our documentation.

**Comment by harshavardhana** [comment]
You can also disable access for admin to avoid certain admin APIs. Again read documentation.

**Comment by Feiniu6ABC** [comment]
> Values set through environment variables cannot be changed through UI.

Thanks for your reply!

I logged in using the default username and password which is "minioadmin", then create a console admin named "jojo1" as in the screenshot. When the console admin "jojo1" is logged in he cannot change his own password, which seems to be unreasonable.
