### ISSUE TITLE
Minio service is not coming up in docker swarm 

### ISSUE THREAD

**Issue by rahul4ver93** [minio/minio#13995]
Hi Team,

I am getting the below error while trying to bring up the minio service in docker swarm using secrets.

YAML FILE:

    minio:
        #network_mode: host
        #image: minio/minio
        image: xray-ai-assist-docker-stable-local.artifactory-na.xx.com/minio_https:V2
        #build:
        #  context: .
        #  dockerfile: Dockerfile_minio
        container_name: "minio_https"
        #depends_on:
        #    - pgdb
        environment:
            MINIO_ACCESS_KEY: /run/secrets/minio_user
            MINIO_SECRET_KEY: /run/secrets/minio_pwd
        restart: unless-stopped
        ports:
            - 9002:9000
            - 9003:9000
        volumes:
            - minio-data:/data

        #command: server /data
        #command: server --address 0.0.0.0:9001 /data
        command: server --address hic029493.dc.xx.com:9002 --console-address hic029493.dc.xx.com:9003 /data
        healthcheck:
            test: ["CMD", "curl", "-f", "https://hic029493.dc.xx.com:9002/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        secrets:
            - minio_user
            - minio_pwd

ERROR:

[e373050a@HIC029493 xray]$ docker service logs xray_minio

xray_minio.1.of178rnx8svp@xx.dc.xx.com    | ERROR Unable to validate passed arguments: host in server address should be this server
xray_minio.1.of178rnx8svp@xx.dc.xx.com    |       > Please check --address parameter
xray_minio.1.of178rnx8svp@xx.dc.xx.com    |       HINT:
xray_minio.1.of178rnx8svp@xx.dc.xx.com    |         --address binds to a specific ADDRESS:PORT, ADDRESS can be an IPv4/IPv6 address or hostname (default port is ':9000')
xray_minio.1.of178rnx8svp@xx.dc.xx.com    |               Examples: --address ':443'
xray_minio.1.of178rnx8svp@xx.dc.xx.com    |                         --address '172.16.34.31:9000'
xray_minio.1.slowr82j73y9@xx.dc.xx.com    | ERROR Unable to validate passed arguments: host in server address should be this server
xray_minio.1.slowr82j73y9@xx.dc.xx.com    |       > Please check --address parameter
xray_minio.1.of178rnx8svp@xx.dc.xx.com    |                         --address '[fe80::da00:a6c8:e3ae:ddd7]:9000'
xray_minio.1.slowr82j73y9@xx.dc.xx.com    |       HINT:
xray_minio.1.slowr82j73y9@xx.dc.xx.com    |         --address binds to a specific ADDRESS:PORT, ADDRESS can be an IPv4/IPv6 address or hostname (default port is ':9000')
xray_minio.1.slowr82j73y9@xx.dc.xx.com    |               Examples: --address ':443'
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    | ERROR Unable to validate passed arguments: host in server address should be this server
xray_minio.1.slowr82j73y9@xx.dc.xx.com    |                         --address '172.16.34.31:9000'
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    |       > Please check --address parameter
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    |       HINT:
xray_minio.1.slowr82j73y9@xx.dc.xx.com    |                         --address '[fe80::da00:a6c8:e3ae:ddd7]:9000'
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    |         --address binds to a specific ADDRESS:PORT, ADDRESS can be an IPv4/IPv6 address or hostname (default port is ':9000')
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    |               Examples: --address ':443'
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    |                         --address '172.16.34.31:9000'
xray_minio.1.7gpwfr9eo2uo@xx.dc.xx.com    |                         --address '[fe80::da00:a6c8:e3ae:ddd7]:9000'

**Comment by harshavardhana** [comment]
> command: server --address hic029493.dc.xx.com:9002 --console-address hic029493.dc.xx.com:9003 /data

This should resolve to the local interface in the container for us to bind()

> [xray_minio.1.of178rnx8svp@xx.dc.xx.com](mailto:xray_minio.1.of178rnx8svp@xx.dc.xx.com) | ERROR Unable to validate passed arguments: host in server address should be this server

The error describes this already.

**Comment by rahul4ver93** [comment]
Hello Harshavardhana,

But can you clarify whether its an image issue for minio or is it a yaml file issue ?

**Comment by rahul4ver93** [comment]
Please clarify the steps i need to take to resolve this issue as i need to communicate the same to backend team

**Comment by harshavardhana** [comment]
> Hello Harshavardhana,
> 
> But can you clarify whether its an image issue for minio or is it a yaml file issue ?

It's a yaml file issue. Also we do not support custom container images.

**Comment by rahul4ver93** [comment]
Please just let me know what changes needs to be done for for minio in yaml.

I am not quite clear about it.
