### ISSUE TITLE
Add ability to inject Kubernetes secrets as environment variables from chart

### ISSUE THREAD

**Issue by patoarvizu** [minio/minio#14004]
**Is your feature request related to a problem? Please describe.**
Right now it's only possible to inject hard-coded strings as environment variables using the `environment` values [field](https://github.com/minio/minio/blob/master/helm/minio/values.yaml#L313) but it's not really possible to inject them as references to secrets/configmaps.

**Describe the solution you'd like**
Either make the existing `values` field more generic to allow to inject both hard-coded values and secret/configmap references (using some `toYaml` magic), or have a second field (e.g. `environmentSecretRefs`) to be able to inject secret references specifically.

**Describe alternatives you've considered**
There are no alternatives that don't involve some prohibitive amount of effort or complexity.

**Additional context**
I'm trying to set OIDC authentication and don't want to set the `MINIO_IDENTITY_OPENID_CLIENT_SECRET` environment variable in plain text in code.

**Comment by harshavardhana** [comment]
For a more involved deployment @patoarvizu we recommend that you use our operator - that provides the functionality that you need https://github.com/minio/operator 

helm/chart in this repo is meant for limited usecases.  Production deployments should go to the operator.

**Comment by patoarvizu** [comment]
Ah, understood. Thanks! 👍
