### ISSUE TITLE
GlobalStorageClass cannot be updated correctly

### ISSUE THREAD

**Issue by nervtech** [minio/minio#14005]
When changing the default EC configuration using environment variables:

MINIO_STORAGE_CLASS_RRS
MINIO_STORAGE_CLASS_STANDARD

globalStorageClass in Globals.go can not updated by 
globalStorageClass.Update(sc) in config-current.go@lookupConfigs() correctly

it maybe because of the pass-by-value problem in globalStorageClass.Update() method

## Expected Behavior

putObject with StorageClass, parityDrives will assign correctly by globalStorageClass.GetParityForSC method

## Current Behavior

when putObject with RRS StorageClass, and MaxParity is False,
parityDrives will be Assigned by globalStorageClass.GetParityForSC(opts.UserDefined[xhttp.AmzStorageClass])
However, any value obtained by globalStorageClass is not initialized at this time.
parityDrives always equal to defaultRRSParity, which value is minParityDisks = 2

STANDARD is same as RRS, however in this case , although the parityDrives value is 0, the value of er.defaultParityCount will be looked up. The result is correct.

## Possible Solution

modify Update method in storage-class.go with pass-by-pointer way:

func (sCfg *Config) Update(newCfg Config) {
	ConfigLock.Lock()
	defer ConfigLock.Unlock()
	sCfg.RRS = newCfg.RRS
	sCfg.Standard = newCfg.Standard
}
(The scope of influence still to be confirmed)

## Steps to Reproduce (for bugs)

1. set environment variables: MINIO_STORAGE_CLASS_RRS=EC:3;MINIO_STORAGE_CLASS_STANDARD=EC:3
2. print globalStorageClass.GetParityForSC value in putObject method(erasure_object.go@788)
3. upload some data with go-sdk by REDUCED_REDUNDANCY StorageClass
4. found that the printed value is 2(minParityDisks)

## Your Environment

* Version used (`minio --version`):
RELEASE.2021-12-27T07-23-18Z
* Server setup and configuration:
APP_ARGS=server /Volumes/data1/data{1...8} --console-address :10001;MINIO_STORAGE_CLASS_RRS=EC:3;MINIO_STORAGE_CLASS_STANDARD=EC:3
* Operating System and version (`uname -a`):
Darwin nervdeMacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
> MINIO_STORAGE_CLASS_RRS=EC:3 MINIO_STORAGE_CLASS_STANDARD=EC:4

I see that CLASS_STANDARD is updated properly however not RRS

```json
  "status": "success",
  "info": {
    "mode": "online",
    "deploymentID": "b07b43ed-02ab-46c3-b293-e0b073986171",
    "buckets": {
      "count": 1
    },
    "objects": {
      "count": 2
    },
    "usage": {
      "size": 82
    },
    "services": {
      "kms": {
        "status": "disabled"
      },
      "ldap": {}
    },
    "backend": {
      "backendType": "Erasure",
      "onlineDisks": 16,
      "rrSCParity": 2,
      "standardSCParity": 4
    },
```
