### ISSUE TITLE
Documentation: Minio Operator

### ISSUE THREAD

**Issue by pfriedland** [minio/minio#14016]
Could you please improve the documentation for Minio Operator users for mc sql ... parquet files?

**Describe the solution you'd like**

Enabling Parquet Format

Parquet is DISABLED by default since hostile crafted input can easily crash the server.

If you are in a controlled environment where it is safe to assume no hostile content can be uploaded to your cluster you can safely enable Parquet.
To enable Parquet set the environment variable MINIO_API_SELECT_PARQUET=on.

For Minio Operator users, you set the environment variable by doing ________

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
Parquet support is not complete and may never be complete on our end. 

For operator however you can enable the parquet environment values in the deployment spec it is already documented how to do it
 https://docs.min.io/minio/k8s/operator-console/operator-console.html#id1

Look at the Console UI to deploy a tenant and add custom environment variables.
