### ISSUE TITLE
Keycloak IDP user removal and Service Account

### ISSUE THREAD

**Issue by tanrobotix** [minio/minio#14026]
## Expected Behavior
After the user is deleted from Keycloak, the associated service account is also deleted/disabled

## Current Behavior
The service account still works after the user is deleted

## Steps to Reproduce (for bugs)
On Keycloak, create a test user
Add a policy attribute with value readwrite to the user
Login to Minio Console with the test user and create a service account
Configure Minio Client with the newly created service account -> able to list buckets
Back to Keycloak, delete the user
List buckets again using minio client -> still works

## Your Environment
* Version used (`minio version RELEASE.2021-12-20T22-07-16Z`):
* Server setup and configuration:

```
MINIO_IDENTITY_OPENID_CONFIG_URL=https://keycloak-idp.domain.example/auth/realms/test-realm/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_CLIENT_ID=client-id-test
MINIO_IDENTITY_OPENID_CLIENT_SECRET=<hidden>
MINIO_ROOT_USER=<hidden>
MINIO_ROOT_PASSWORD=<hidden>
MINIO_SERVER_URL=https://example.com
MINIO_BROWSER_REDIRECT_URL=https://example.com
MINIO_IDENTITY_OPENID_SCOPES=openid
MINIO_IDENTITY_OPENID_VENDOR=keycloak
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=test-realm
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=https://keycloak-idp.domain.example/auth/admin
MINIO_ACCESS_KEY_FILE=access_key
MINIO_SECRET_KEY_FILE=secret_key
MINIO_ROOT_USER_FILE=access_key
MINIO_ROOT_PASSWORD_FILE=secret_key
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_UPDATE_MINISIGN_PUBKEY=<hidden>
MINIO_CONFIG_ENV_FILE=config.env
HOME=/root
```
* Operating System and version (`Linux a988454148df 5.11.0-40-generic #44~20.04.2-Ubuntu`):

## Keycloak configuration:
At first I followed the instructions [keycloak sts](https://github.com/minio/minio/blob/master/docs/sts/keycloak.md). However I was not able to query the users as keycloak returned 403 error.

```
curl -H "Authorization: Bearer eyxxxxxxxxxx..." \
  "https://keycloak-idp.domain.example/auth/admin/realms/test-realm/users/{userid}"
```

Then only after adding the **realm-management** role to **client-id-test**, I could get the requested user: on the tab **Roles**, select client role **realm-management** , add role **manage-users**

**Comment by harshavardhana** [comment]
@tanrobotix you need to provide more details on the setup etc. Closing this until you provide enough information by filling out the issue template properly and a reproducer if any.

**Comment by tanrobotix** [comment]
Hi @harshavardhana , I added the detail info, would you please reopen the isssue.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana , I added the detail info, would you please reopen the isssue.

Thanks please make sure to follow this from next time.

**Comment by titansmc** [comment]
right, we face the same issue. In our case would be enough to just being able to identify the existing service accounts with the OIDC/LDAP users, so we can go through them and close the ones that are gone. In our case, we lock accounts in LDAP by setting some hash in the password field that doesn't match any password they potential user may type. How would Minio then know whether this account is gone or not?

**Comment by harshavardhana** [comment]
> right, we face the same issue. In our case would be enough to just being able to identify the existing service accounts with the OIDC/LDAP users, so we can go through them and close the ones that are gone. In our case, we lock accounts in LDAP by setting some hash in the password field that doesn't match any password they potential user may type. How would Minio then know whether this account is gone or not?

LDAP has nothing to do with this issue. In case of LDAP we will see the UserDN is missing on the LDAP server this tells us that this user is gone.

**Comment by Enrico204** [comment]
For completeness: this issue was already reported to the security team nearly 1 year ago. The response was that this (the fact that a service account survives the deletion of the IDP account) is not a security issue, but "an administrative issue". The suggested "fix" was adding a step for manual Service Account deletion (`mc admin user svacct rm`) in the user removal procedure.

While I don't agree, I understand that there is no way for MinIO (as "OIDC Service Provider") to be notified for a user deletion from the IDP (AFAIK). Also, there is no way to query for user info/existence from SP to IDP in the OIDC standard. Specific implementations may expose specific non-standard endpoints for querying the user list (e.g., Keycloak as Admin REST APIs).

A possible "mitigation" is add an option for disabling service account altogether, or limit service accounts creation to admins / non IDP-users.

**Comment by harshavardhana** [comment]
> For completeness: this issue was already reported to the security team nearly 1 year ago. The response was that this (the fact that a service account survives the deletion of the IDP account) is not a security issue, but "an administrative issue". The suggested "fix" was adding a step for manual Service Account deletion (`mc admin user svacct rm`) in the user removal procedure.
> 
> While I don't agree, I understand that there is no way for MinIO (as "OIDC Service Provider") to be notified for a user deletion from the IDP (AFAIK). Also, there is no way to query for user info/existence from SP to IDP in the OIDC standard. Specific implementations may expose specific non-standard endpoints for querying the user list (e.g., Keycloak as Admin REST APIs).
> 
> A possible "mitigation" is add an option for disabling service account altogether, or limit service accounts creation to admins / non IDP-users.
> 

Automatic way is already added, but something seems to be missing and we haven't had time to debug this further.

Will reply back when we have further updates @Enrico204

**Comment by titansmc** [comment]
Being able to list service account for a specific IDP account would already be a success (as minio admin), since this way we can manually search for existing service accounts of disabled IDP users. Is that possible?

**Comment by harshavardhana** [comment]
> Being able to list service account for a specific IDP account would already be a success (as minio admin), since this way we can manually search for existing service accounts of disabled IDP users. Is that possible?

When you login to the UI you will see what your service accounts are for the incoming user @titansmc

**Comment by harshavardhana** [comment]
I see why this happened and perhaps why this broke, the format of the ParentUser changed to be base64 encoded value - a fix looks simple and here is the relevant fix

https://github.com/minio/minio/pull/14154

**Comment by titansmc** [comment]
how do you (minio servers) determine that a user has been deleted from keycloak ? what has been exactly fixed here ?

**Comment by harshavardhana** [comment]
> how do you (minio servers) determine that a user has been deleted from keycloak ? what has been exactly fixed here ?

@titansmc you need to set

```
MINIO_IDENTITY_OPENID_VENDOR                (string)    Specify vendor type for vendor specific behavior to checking validity of temporary credentials and service accounts on MinIO
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM        (string)    Specify Keycloak 'realm' name, only honored if vendor was set to 'keycloak' as value, if no realm is specified 'master' is default
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL    (string)    Specify Keycloak 'admin' REST API endpoint e.g. http://localhost:8080/auth/admin/
```

For automatic expiration of local accounts 

```
MINIO_IDENTITY_OPENID_VENDOR=keycloak
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=minio
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://localhost:8080/auth/admin/
```

You need to enable admin API access for your realm and account https://github.com/minio/minio/blob/master/docs/sts/keycloak.md#enable-keycloak-admin-rest-api-support

**Comment by rch-asl** [comment]
Hey @harshavardhana,

I've added the 3 following env variables at the docker start:
```
MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://192.168.2.132:8080/auth/admin/
MINIO_IDENTITY_OPENID_VENDOR=keycloak
MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=minio
```

My openid config is:
```
$ mc admin config get myminio identity_openid 
identity_openid display_name= config_url=http://192.168.2.132:8080/auth/realms/minio/.well-known/openid-configuration client_id=account client_secret=<hidden> claim_name=policy claim_userinfo= role_policy= claim_prefix= redirect_uri= redirect_uri_dynamic=off scopes= 
```

The Admin REST API seems to work. However, the service account credentials are still working when deleting the associated user...

Minio Version: RELEASE.2022-05-03T20-36-08Z
Keycloak Version: 18.0.0-legacy
