### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by wuyuan0717** [minio/minio#14027]
## Expected Behavior

1.First, upload the file using the url of preSignedPutObject
2. download file using the url of preSignedGetObject
3. then,upload file  again using the url of step 1
4.   now download file again using the url of step 2,you will found `minio admin trace --status-code 503 minio`    the wrong log was output:
`2022-01-05T09:06:12:000 [503 Service Unavailable] s3.GetObject 10.100.15.79:9000/private-bucket/va/acctOpenPhoto/20220105/101120220105134933000097.png 10.100.0.53       8.314ms      ↑ 170 B ↓ 811 B`

The download request will return:
`<Error>
<Code>SlowDown</Code>
<Message>Resource requested is unreadable, please reduce your request rate</Message>
<Key>va/acctOpenPhoto/20211230/201120211230145403000029.png</Key>
<BucketName>private-bucket</BucketName>
<Resource>/private-bucket/va/acctOpenPhoto/20211230/201120211230145403000029.png</Resource>
<RequestId>16C751F5FE899649</RequestId>
<HostId>6f8cbacd-c812-4e95-9244-d88d33ed3e19</HostId>
</Error>`

of course,minio log has occured:
`API: SYSTEM()
Time: 17:07:53 CST 01/05/2022
DeploymentID: 6f8cbacd-c812-4e95-9244-d88d33ed3e19
Error: unexpected EOF (msgp.errWrapped)
       4: cmd/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:721:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:463:cmd.erasureObjects.nsScanner.func3()`

`API: SYSTEM()
Time: 17:07:53 CST 01/05/2022
DeploymentID: 6f8cbacd-c812-4e95-9244-d88d33ed3e19
Error: sequence stream 0, repeat requested, but no history (msgp.errWrapped)
       4: cmd/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:721:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:463:cmd.erasureObjects.nsScanner.func3()`

`API: SYSTEM()
Time: 17:07:53 CST 01/05/2022
DeploymentID: 6f8cbacd-c812-4e95-9244-d88d33ed3e19
Error: sequence stream 0, repeat requested, but no history (msgp.errWrapped)
       4: cmd/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:721:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:463:cmd.erasureObjects.nsScanner.func3()`

`API: SYSTEM()
Time: 17:09:14 CST 01/05/2022
DeploymentID: 6f8cbacd-c812-4e95-9244-d88d33ed3e19
Error: tableLog too large (msgp.errWrapped)
       4: cmd/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/data-usage-cache.go:721:cmd.(*dataUsageCache).load()
       1: cmd/erasure.go:463:cmd.erasureObjects.nsScanner.func3()`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): 2021-05-18T00:53:28Z
* Server setup and configuration: Linux  3.10.0-862.el7.x86_64 SMP  x86_64 x86_64 x86_64 GNU/Linux
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): 2021-05-18T00:53:28Z

You need to upgrade to latest release and report again @wuyuan0717

**Comment by wuyuan0717** [comment]
> > * Version used (`minio --version`): 2021-05-18T00:53:28Z
> 
> You need to upgrade to latest release and report again @wuyuan0717

In this case, is the previous version not supported?

> > * Version used (`minio --version`): 2021-05-18T00:53:28Z
> 
> You need to upgrade to latest release and report again @wuyuan0717

Or this problem has been solved in the new version

**Comment by harshavardhana** [comment]
> In this case, is the previous version not supported?

For community users, we expect that you use the latest version and report issues if any.  Also 

- there is no detail about your setup nothing is mentioned how it is setup
- there is no detail about the reproducer code etc. 

Because what you are saying doesn't make sense just for PUT to succeed and then GET fail.

**Comment by wuyuan0717** [comment]
> * there is no detail about your setup nothing is mentioned how it is setup

![image](https://user-images.githubusercontent.com/14838846/148197249-24adeeca-4174-4991-a10f-c157ecad9550.png)
i`m sorry， i forgot ,setup scripts file

**Comment by klauspost** [comment]
@wuyuan0717 Did you upgrade?

**Comment by wuyuan0717** [comment]
> @wuyuan0717 Did you upgrade?

Yes, I'm upgrading, and then verify again whether this problem will reappear after completion. If it reappears, I'll contact you again
