### ISSUE TITLE
Error: When Minio node client uses bucketExists to determine whether it exists, if the directory does not exist, it will report an error directly and will not return false

### ISSUE THREAD

**Issue by xinlingqudongX** [minio/minio#14028]
## Expected Behavior
When Minio node client uses bucketExists to determine whether it exists, if the directory does not exist, it will report an error directly and will not return false
should be return false

## Current Behavior

Report an error and prompt：S3Error: Are you using the correct endpoint URL

## Steps to Reproduce (for bugs)

1.Start minio
2.Use the bucketExists method of node minio client to determine whether the directory exists

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2022-01-03T18-22-58Z
* Server setup and configuration:
* Operating System and version (`uname -a`):Centos 8
* Node Version:v16.13.0
* Minio Client Version:7.0.25

**Comment by harshavardhana** [comment]
> Report an error and prompt：S3Error: Are you using the correct endpoint URL

You didn't specify the correct endpoint here.

**Comment by xinlingqudongX** [comment]
> > Report an error and prompt：S3Error: Are you using the correct endpoint URL
> 
> You didn't specify the correct endpoint here.

我指定了endpoint，我的意思是如果有文件夹，bucketExists方法返回的是真，但是没有文件夹时，我使用就会报错
I specified the endpoint, I mean if there is a folder, the bucketExists method returns true, but when there is no folder, I will get an error when I use it.

```typescript
// 如果upload文件夹不存在，那么将会报错，而不是返回假
// If the upload folder does not exist, an error will be reported instead of false
const uploadTmp = 'upload';
const exists = await minio.bucketExists(uploadTmp);
if (!exists) {
    await minio.makeBucket(uploadTmp, '');
}
```
