### ISSUE TITLE
can't login , it returns "expected element type <ErrorResponse> but have <html>"

### ISSUE THREAD

**Issue by PetalQ** [minio/minio#14035]
## Current Behavior

can't login now.
![image](https://user-images.githubusercontent.com/28222123/148365005-67289dd4-c0c8-4f9f-ac53-8ce83c4c2d14.png)
![image](https://user-images.githubusercontent.com/28222123/148365029-99ab5771-efd4-474b-9e28-199f8d045300.png)

## Steps to Reproduce (for bugs)

1.wget https://dl.min.io/server/minio/release/linux-amd64/minio --no-check-certificate
2.chmod +x minio
3../minio server ./iofiles/
4.open web and login

## Context

i try minio demo, but can't login.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-01-04T07-41-07Z
* Server setup and configuration: default
* Operating System and version (`uname -a`):Linux test 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You have some other service running at port 9000 that returns HTML

**Comment by PetalQ** [comment]
> You have some other service running at port 9000 that returns HTML
I'm sure that port 9000 is used by minio
![image](https://user-images.githubusercontent.com/28222123/148370331-e74ed292-0acd-4c55-b800-427417f960a1.png)
@harshavardhana

**Comment by harshavardhana** [comment]
> > You have some other service running at port 9000 that returns HTML
> I'm sure that port 9000 is used by minio
> ![image](https://user-images.githubusercontent.com/28222123/148370331-e74ed292-0acd-4c55-b800-427417f960a1.png)
> @harshavardhana 

Check if you have enabled some MINIO_SERVER_URL pointing to console port.

**Comment by vadmeste** [comment]
@withyanni by the way, it looks like MinIO is only listening on tcp6 interface. There is something odd in your setup.
