### ISSUE TITLE
IAM API for Dynamic Role/Policy/Account Management

### ISSUE THREAD

**Issue by sempervictus** [minio/minio#14032]
**Is your feature request related to a problem? Please describe.**
We are working on a piece of Rust designed to stream _large_ files (CryoEM data) to S3 from a facility used by people from labs the world over. Since the researchers belong to groups/orgs (varying over time, highly dynamic, and sometimes several at at time), and have user-level retention and permission policies assigned to their subtree in the org bucket, we need to be able to dynamically create them via the IAM API when new ones are detected based on the path name of their sample data. For example, when `monitored_subtree/LabName/JohnDoe_20220103_SampleName/` is created, we parse out the organization and user name from the sample path. Before we run async stream uploads of the giant source files to S3, we have
```rust
    pub async fn ensure_user(&self, uname: String) -> Result<(),Box<dyn Error>> {
        let tu_req = GetUserRequest {user_name: Some(uname.clone())};
        match self.iam.get_user(tu_req).await {
            Err(e) => {
                println!("Could not get user due to {:#?}", e);
                let cu_req = rusoto_iam::CreateUserRequest {
                    user_name: uname.clone(),
                    path: Some(self.bucket.clone().into()),
                    permissions_boundary: Some(self.bucket.clone()),
                    tags: None,
                };
                match self.iam.create_user(cu_req).await {
                    Ok(_) => {}
                    Err(e) => println!("Could not create user {} due to {:#?}", &uname, e)
                };
            }
            Ok(r) => println!("User {} exists: {:#?}", &uname, r)
        };
        Ok(())
    }
```
which obviously fails since there's no IAM endpoint (it comes back with an STS one strangely enough).

**Describe the solution you'd like**
In order to dynamically manage the permissions around S3 content from static foreign code, the relevant IAM functionality needs to be exposed via the API. Specifically user, group, and policy object CRUD endpoints to permit referencing of subjects and policies created this way on the fly. Currently only the management of `s3::` subjects is supported via the S3 API itself.

**Describe alternatives you've considered**
We run Ceph internally under our OpenStack environments, but the storage paradigm does not meet the cost constraints under which the research is conducted.
On the sync-code-side, i've looked at options like shelling-out for the `mcli` binary (we have our own "distro" forked off Arch here hence not `mc`) but not a fan of doing that in _their_ environment since it can create problems if they move binaries/break their stuff (which researchers do nearly constantly)/change the host-level dependencies (libc or whatever) to mess up the dependency chain. There's also a security angle to this which i strongly dislike as my actual job title is security architect - something privileged enough to RW research data should be self-contained and well-vetted (not shelling out to things we dont control and which could be replaced with a bin/script that will `rm -rf /research_data/*` as instructed by name-a-hostile-foreign-lab). On our end the entire stack is wrapped in grsec/pax/ossec/various-nids+nips/waf/SDN security/xtables/secret-sauce so we'd like to keep the client-side in a single static MUSL-embedded Rust binary to separate domains of concern (once "we" touch the data, it needs to be handled correctly).

**Additional context**
This is for grant-strapped scientists who cannot afford to use public cloud for this sort of thing (a single sample _download_ by a researcher can be more than a thousand dollars in egress costs), nor afford to have someone curating permissions/retention/etc. Grant money cannot be used in any way other than the grant specifies which means that despite absurdly expensive equipment on-hand, they are otherwise completely crippled and unable to make use of the data it generates in relevant timeframes - there are biologists with USB drives **running around** during COVID trying to cure COVID, literally. The O strain is spreading faster than they can copy data over USB (and way faster than they can sneaker-net or courier it back to their labs). This effort will put them on a WAN backbone (scalable Cogent fiber) with dedicated faster-than-wire storage infrastructure to drastically reduce the time to effect on-target for these critical data sets (which show the atomic structure of molecules used to target antigens/vaccines/etc). The implications of getting this working are wide-ranging.

**Comment by harshavardhana** [comment]
> In order to dynamically manage the permissions around S3 content from static foreign code, the relevant IAM functionality needs to be exposed via the API. Specifically user, group, and policy object CRUD endpoints to permit referencing of subjects and policies created this way on the fly. Currently only the management of `s3::` subjects is supported via the S3 API itself.

This really doesn't make sense @sempervictus you are asking for things that our API is not going to change for. 

https://github.com/minio/madmin-go use the API here for all your work and that is the correct way to go. We are not going to do this on our end.

**Comment by sempervictus** [comment]
Thanks for pinging back - i've gone the route of rewriting parts of that client in GoLang already. Actually on a call w/ your folks currently :smile: 
Given that MinIO can meet or exceed capabilities of Amazon's S3 when properly built, i still think that there is significant value to being able to abstract these API calls to the real back-end as people's tooling is built against IAM API (and the talent who built it is often not there anymore).

**Comment by harshavardhana** [comment]
> Given that MinIO can meet or exceed capabilities of Amazon's S3 when properly built, I still think that there is significant value to being able to abstract these API calls to the real back-end as people's tooling is built against IAM API (and the talent who built it is often not there anymore).

There may be some perceived value in this but this is a significant effort, there should be good reasons why the current model doesn't work.  

CRUD-based API might provide some value but on our end, it can complicate the entire flow, this would require us at this point in time to re-implement the SDKs and come up with multiple endpoints to validate already published functionalities - potentially exposing ourselves to newer vulnerabilities.  Right now we do not have development cycles to design another parallel API.

We may get to it if there is value in it for the future but for now we are not looking to write AWS IAM API equivalent on MinIO.

**Comment by sempervictus** [comment]
Thanks a ton, and completely understood (as i mentioned in the original submission - been there, feel your pain). I see you have dabbled in the dark arts of [rust yourself](https://github.com/harshavardhana/minio-rust) - join the dark side, we have cookies (and no GC) :wink:.
On the exposure consideration, i tend to agree that having mappings between varying paradigms can create logic bugs and creates situations where "the useful parts" of API are scaffolded with a translation tier but more complex thing's arent (and then the rabbithole to wonderland of constantly having to add little-used features because there's a base of users now).
I'm going to teach the sync tool to discern between endpoint types through a simple enum of useragents or just target URLs and then call out to IAM via their API or to you guys via yours (once i get a proper client working in Rust).

**Comment by sempervictus** [comment]
This is certainly fun - looks like the domain-specific pieces of your user request encryption aren't really implemented in the Rust client libs i've found so far and SIO for Rust isn't at the same level of completion as it is for Go. Ring (the crypto library underpinning SIO in Rust) doesn't do PBKDF/Argon2 so this might need to be implemented raw in our internal client using Orion or similar for feature-parity. Was really hoping to just get it working in an existing Rust client library :confounded:
