### ISSUE TITLE
Minio Speedtest produces no output

### ISSUE THREAD

**Issue by seanrmurphy** [minio/minio#14040]
I cannot get any output from Speedtest - minio is deployed in our k8s cluster using the
helm chart. (I'm also getting no output from diagnostics - I guess this is related).

I tried running speedtest via the browser interface - after perhaps a couple of minutes
I see 0B/s PUT and GET and the test continues; eventually I navigate away from the
page.

I tried running speedtest via the cli and observed similar behaviour: it just indicates
that the speedtest is running and eventually prints

```
root@mgmt-k8s-beta:~# ./mc admin speedtest minio
(With 64 MiB object size, 32 concurrency) PUT: 0 B/s GET: 0 B/s
⠴ Running speedtest^Croot@mgmt-k8s-beta:~# 
```

## Expected Behavior

Speedtest returns some result or else fails ideally giving a reason for failure.

## Current Behavior

Speedtest does not seem to terminate and from time to time updates showing
0B/s for GET and PUT.

## Possible Solution

Don't know any specific solution. Prob also worth pointing out that this runs
on our Openstack cluster using Ceph volumes - the minio disks are sitting
on those volumes (not ideal in general, but this seems to be the best solution
for us).

## Steps to Reproduce (for bugs)

I did not do anything v special - I installed minio via the helm chart, made some
small changes for our environment. Worth noting that it has been possible to
write small objects to the cluster and the web interface is working fine for
creating buckets, users etc.

## Context

I want to understand if my minio installation is healthy.

## Regression

No.

## Your Environment

Running inside k3s sitting on top of an Openstack cluster with Ceph behind it.
Minio drives are provisioned using the Openstack Ceph CSI provider.

Minio version: 2021-11-24T23:19:33Z
Host OS: Ubuntu 20.04, kernel 5.4.0-89-generic

**Comment by harshavardhana** [comment]
Please upgrade your MinIO version.

**Comment by harshavardhana** [comment]
> root@mgmt-k8s-beta:~# ./mc admin speedtest minio
> (With 64 MiB object size, 32 concurrency) PUT: 0 B/s GET: 0 B/s
> ⠴ Running speedtest^Croot@mgmt-k8s-beta:~#

The main reason here is that your drives are too slow and failed - however, we made the speed test more robust in recent releases. So please upgrade.
