### ISSUE TITLE
Can you publicize the github warehouse address of the dockerfile uploaded on your Dockerhub? Have bugs

### ISSUE THREAD

**Issue by ghost** [minio/minio#14048]
minio/minio: 2021.12.29 The scripts in the default script directory of the mirror do not have execution permission, and the data directory permission exception will be thrown directly at startup.
![image](https://user-images.githubusercontent.com/71524776/148519044-faa3f124-f1ec-459c-8619-bb50fea1d2b4.png)
![image](https://user-images.githubusercontent.com/71524776/148519372-4788bfa8-16ed-4dff-ab4b-0921a3a1ac0e.png)

**Comment by harshavardhana** [comment]
@freemankevin Bitnami is not our product they just package our binaries. Please ask in their repos or use the official ones published by us at 

```
minio/minio:RELEASE.2022-01-07T01-53-23Z
quay.io/minio/minio:RELEASE.2022-01-07T01-53-23Z
```

**Comment by ghost** [comment]
Oh, is that so? Seeing that they release so many and frequently, I thought it was official.Thanks.

**Comment by harshavardhana** [comment]
> Oh, is that so? Seeing that they release so many and frequently, I thought it was official.Thanks.

Bitnami builds their own image we do not support that image.  We recommend that you use MinIO published images https://docs.min.io/docs/minio-docker-quickstart-guide based of RHEL UBI8

**Comment by ghost** [comment]
OK, thanks.
