### ISSUE TITLE
Add MINIO_CONSOLE_URL to control redirection from API root

### ISSUE THREAD

**Issue by srstsavage** [minio/minio#14052]
**Is your feature request related to a problem? Please describe.**
Currently minio tries to redirect the browser to the console address (random port or `--console-address`)
when a request is made to the server root and console isn't disabled (`MINIO_BROWSER` is not set to `off`).
In various deployment/proxy situations it would be useful for the redirected console URL to be decoupled from
the internal port used for the console, or to redirect to a standalone console instance.

**Describe the solution you'd like**
Add `MINIO_CONSOLE_URL` env var and redirect browser requests to server root to that URL.

**Describe alternatives you've considered**
¯\\_(ツ)_/¯

**Additional context**
Thanks!

**Comment by harshavardhana** [comment]
> Currently minio tries to redirect the browser to the console address (random port or `--console-address`)
> when a request is made to the server root and console isn't disabled (`MINIO_BROWSER` is not set to `off`).
> In various deployment/proxy situations it would be useful for the redirected console URL to be decoupled from
> the internal port used for the console, or to redirect to a standalone console instance.

if you wish you are advised to set the correct REDIRECT_URLs properly but not redirecting on browser is not something we want to do and it is as per design. 

This is out of scope for us sorry.
