### ISSUE TITLE
Minio dashboard ingress

### ISSUE THREAD

**Issue by dharmendrakariya** [minio/minio#14050]
**Is your feature request related to a problem? Please describe.**

same as like client we should create dashboard ingress as well

**Describe the solution you'd like**

helm chart ingress creation for minio dashoard.

**Describe alternatives you've considered**
N/A

**Additional context**

I can provide PR if you allow

**Comment by harshavardhana** [comment]
> I can provide PR if you allow

Feel free to send whenever you can @dharmendrakariya

**Comment by dharmendrakariya** [comment]
> > I can provide PR if you allow
> 
> Feel free to send whenever you can @dharmendrakariya

Thanks, I will, soon @harshavardhana

**Comment by dharmendrakariya** [comment]
@harshavardhana I think I didnt go through thoroughly. its already there. Sorry! I am closing this.
