### ISSUE TITLE
Internal error not descriptive enough to determine root cause of 500 server error.

### ISSUE THREAD

**Issue by jcalcote** [minio/minio#14051]
We're receiving the following error via our S3 client (jclouds):

```
org.jclouds.aws.AWSResponseException: 
request 
	PUT 
	http://10.200.83.195:9000/minio18ce4481-7154-4d4a-8352-e2fc8fdd0aa0-bucket/Hammerspace_v2/0002DD/F4/0002DDF4149D746711C163C7D897F5212A54888E0D8ABE27AE6D0B818FBDFFA71C0E0000000000001000 
	HTTP/1.1 
	
failed with code 500, 
error: 
	AWSError{
		requestId='16C813615CF1C455', 
		requestToken='null', 
		code='InternalError', 
		message='We encountered an internal error, please try again.', 
		context='{
			Resource=/minio18ce4481-7154-4d4a-8352-e2fc8fdd0aa0-bucket/Hammerspace_v2/0002DD/F4/0002DDF4149D746711C163C7D897F5212A54888E0D8ABE27AE6D0B818FBDFFA71C0E0000000000001000, 
			HostId=3L137
		}'
	}
```
(I've reformatted it to make it easier to see the problem.)

This bug is about how the minio server is returning 500 (internal server error) and an error structure, but the error structure doesn't indicate what actually happened on the back end. This would not be so bad if minio were reasonable at logging server side internal errors somewhere. All this says (effectively) is that "We encountered an internal error, please try again." How will trying again fix an "out of disk space" issue (if that is in fact what's going on here)? Wouldn't it be better to put a _little_ more detail in the 500 error report?

## Your Environment
* Version used (`minio --version`): 
VERSION:
  2018-08-02T23:11:36Z

* Operating System and version (`uname -a`):
Linux \<hostname> 3.10.0-1127.el7.x86_64 \<poundsign>1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
VERSION:
2018-08-02T23:11:36Z

This version has reached EOL long time ago. Please upgrade.
