### ISSUE TITLE
Data usage not clear

### ISSUE THREAD

**Issue by Kirutian** [minio/minio#14066]
## Expected Behavior
Server Dashboard total bucket usage and drive space used are not synced.

## Current Behavior
We have 4 buckets on a dedicated server to a single Minio instance. We expect the used space on the drive to match the total usage of all buckets.

![Screenshot from 2022-01-09 13-19-35](https://user-images.githubusercontent.com/55530216/148699362-9af8ece5-1dc0-4713-91b6-19cfac935330.png)

## Your Environment

* Version used (`minio --version`): Version 2021-12-10T23:03:39Z
Rocky Linux 8.5/ Podman using docker image

**Comment by harshavardhana** [comment]
> We have 4 buckets on a dedicated server to a single Minio instance. We expect the used space on the drive to match the total usage of all buckets.

That is not going to be the same @Kirutian - filesystem usage is different than usage seen by the actual objects in the usage calculation.

**Comment by Kirutian** [comment]
That makes no sense. There's a huge discrepancy. What accounts for the discrepancy? I can tell you that the buckets indeed hold over 8TB, yet the dashboard shows it holding less than half.

**Comment by harshavardhana** [comment]
> That makes no sense. There's a huge discrepancy. What accounts for the discrepancy? I can tell you that the buckets indeed hold over 8TB, yet the dashboard shows it holding less than half.

That is not yet updated, the scanner takes time to update - if you upload content and check right away it won't show up. Wait for some time it will show the actual values later. 

You want to speed this up and use more IOPS change the scanner settings `mc admin config set alias/ scanner` to see what all values you can tune.

**Comment by Kirutian** [comment]
We'll try that. Thank you. This is sort of a test run in actual production to see if Minio is a good fit for us.
