### ISSUE TITLE
Downloading Erasure object is much slower than speedtest

### ISSUE THREAD

**Issue by shivabohemian** [minio/minio#14067]
## Expected Behavior

Downloading erasure object should be as fast as speedtest is when we start minio locally.
<img width="1418" alt="截屏2022-01-10 下午2 49 33" src="https://user-images.githubusercontent.com/39078424/148728272-f6d392c5-c798-4ca6-a5e3-f4e995062fca.png">

## Current Behavior

It's much slower...
<img width="741" alt="截屏2022-01-10 下午2 53 32" src="https://user-images.githubusercontent.com/39078424/148728526-0b102337-e053-4982-ac1e-4fd171d001ff.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm trying to test the speed when using minio.

## Regression

No

## Your Environment

* Version used (`minio --version`):latest
* Server setup and configuration: minio server ~/soft/minio/data{1...4} --console-address :9001
* Operating System and version (`uname -a`):Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by harshavardhana** [comment]
> ## Expected Behavior
> Downloading erasure object should be as fast as speedtest is when we start minio locally. <img alt="截屏2022-01-10 下午2 49 33" width="1418" src="https://user-images.githubusercontent.com/39078424/148728272-f6d392c5-c798-4ca6-a5e3-f4e995062fca.png">
> 
> ## Current Behavior
> It's much slower... <img alt="截屏2022-01-10 下午2 53 32" width="741" src="https://user-images.githubusercontent.com/39078424/148728526-0b102337-e053-4982-ac1e-4fd171d001ff.png">
> 
> ## Possible Solution
> ## Steps to Reproduce (for bugs)
> 
> ## Context
> I'm trying to test the speed when using minio.
> 
> ## Regression
> No
> 
> ## Your Environment
> * Version used (`minio --version`):latest
> * Server setup and configuration: minio server ~/soft/minio/data{1...4} --console-address :9001
> * Operating System and version (`uname -a`):Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

Speed test shows maximum available i.e when multiple files are downloaded. Downloading a single file will not fully use all the bandwidth.

**Comment by shivabohemian** [comment]
But why am I using Minio to download erasure files slower than a normal file server(such as nginx), and it can't read as fast as the hard disk itself




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio] Downloading Erasure object is much slower than speedtest (Issue #14067)





  
Expected Behavior
 
Downloading erasure object should be as fast as speedtest is when we start minio locally. 
 
Current Behavior
 
It's much slower... 
 
Possible Solution
 
Steps to Reproduce (for bugs)
 
Context
 
I'm trying to test the speed when using minio.
 
Regression
 
No
 
Your Environment
  
Version used (minio --version):latest
 
Server setup and configuration: minio server ~/soft/minio/data{1...4} --console-address :9001
 
Operating System and version (uname -a):Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
   
Speed test shows maximum available i.e when multiple files are downloaded. Downloading a single file will not fully use all the bandwidth.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by harshavardhana** [comment]
> But why am I using Minio to download erasure files slower than a normal file server(such as nginx), and it can't read as fast as the hard disk itself

@shivabohemian you are not reading what I wrote - please re-read what I wrote.

**Comment by shivabohemian** [comment]
Ok, can I think that you guys put bandwidth restriction when downloading  a single file ?

**Comment by klauspost** [comment]
@shivabohemian No.

You can test end-to-end with https://github.com/minio/warp
