### ISSUE TITLE
 Unable to initialize gateway backend : operation not supported when starting minio on mounted folders

### ISSUE THREAD

**Issue by m-brgs** [minio/minio#14060]
Hi

Any help appreciated

I'm trying to start minio with docker and the data folder location is a sub-directory of a ftps mounted folder on the host.

Minio keeps crashing with the error : Unable to initialize gateway backend: open /data/.minio.sys/format.json: operation not supported

Some directories are being created in /data/.minio.sys (e.g. buckets  multipart  tmp) but format.json is not created. As minio seems to be running as root, I don't expect to have a permission issue

## Expected Behavior

Minio starts correctly when writing to a folder whitch is an ftps mount

## Current Behavior

Minio won't start

## Possible Solution

I tried to start minio with a volume on the actual host (not a mounted directory). It's all good. Then a copied the format.json folder to the mounted keeping the permission the same (i.e. read-only on owner; nothing for everybody else).

Then started minio on the mounted folder as the data volume and it works. I don't know what "operation" minio can't do but maybe it's similar to a chmod ?

It's a quick fix but I worry this could be an issue after the launch, when minio is being used. That would be a really bad experience.

## Steps to Reproduce (for bugs)

```docker-compose.yml
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-01-07T01-53-23Z
    command: gateway nas /data --console-address ":9001"
    expose:
      - "9000" # API
      - "9001" # Web Admin Console  
    secrets:
      - source: minio_user
        target: my_access_key
      - source: minio_pass
        target: my_secret_key
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/my_access_key
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/my_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - "/mnt/minio/data:/data" # /mnt/minio is a ftps mount

secrets:
  minio_user:
    external: true
  minio_pass:
    external: true
```

Start container : `sudo docker stack deploy -c docker-compose.yml minio`

I tried two drives with ftps : 
- ovh backup storage mounted in fstab as : `curlftpfs#FTPSERVERDN /mnt/minio fuse rw,user,_netdev 0 0`
- Synology NAS shared drive : `sudo curlftpfs 'IP:PORT' /mnt/minio -o 'ssl,no_verify_peer,no_verify_hostname,user=USER:PASS'`

## Context

N/A

## Regression

No

## Your Environment

* Version used : `quay.io/minio/minio:RELEASE.2022-01-07T01-53-23Z`
* Operating System and version (`uname -a`): `Linux hostname 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
We need fcntl and O_DIRECT support on your backend disks for NAS gateway. 

You cannot use any random filesystems with NAS gateway here.
