### ISSUE TITLE
Shared links from console stop working before expiration date when using oidc auth

### ISSUE THREAD

**Issue by pupkinsen** [minio/minio#14075]
## Expected Behavior
Link to a file shared from the console should be accessible up to its expiration date.

## Current Behavior
Link to a file shared from the console is inaccessible after one hour.
error mesage example:
```
<Error>
<Code>InvalidAccessKeyId</Code>
<Message>The Access Key Id you provided does not exist in our records.</Message>
<Key>path/filename.ext</Key>
<BucketName>bucket</BucketName>
<Resource>/bucket/path/filename.ext</Resource>
<RequestId>16C905B36D3486B0</RequestId>
<HostId>d1ca0725-d6bc-4d04-bd9c-8a26a72f3b49</HostId>
</Error>
```

## Possible Solution
Seems like this happens because the sts key obtained by the console expires one hour after the user logs in.
Don't know what could be the optimal solution but setting the key expiration period to a bigger value might be enough for my case.
Browsing through the docs I've found this environment value:
```
CONSOLE_STS_DURATION
```
Might be relevant but it does not seem to work in the embedded console.

## Steps to Reproduce (for bugs)

1. Configure minio to work with oidc auth (Keycloak in my case)
2. Log into console with a keycloak user credentials.
3. Share a link to a file, set the expiration period to 7 days.
4. Log out.
5. Try to open the link after an hour or two.

## Context
I am testing minio capabilities to integrate into an existing infrastructure. The users need to log in with their existing credentials, and oidc works perfectly for that. But link sharing is a strongly requested feature which does not seem to work for me.  

## Regression
No

## Your Environment
docker image: minio/minio:RELEASE.2022-01-08T03-11-54Z

**Comment by harshavardhana** [comment]
This is a known issue and there is no fix yet - https://github.com/minio/console/issues/922 .

Generate service accounts for your OIDC user and then use `mc` to generate relevant links for now.
