### ISSUE TITLE
Can't load/save config "An error occurred, please try again" - upgrade from RELEASE.2020-01-03T19-12-21Z to RELEASE.2022-01-08T03-11-54Z 

### ISSUE THREAD

**Issue by ming12713** [minio/minio#14072]
Upgrade minio from RELEASE.2020-01-03T19-12-21Z to  RELEASE.2022-01-08T03-11-54Z sucuess
Anything is ok ,but get some errors when save/load configure
## Expected Behavior
set notification with rabbitmq
```
mc admin config set minio/ notify_amqp:1 exchange="minio" exchange_type="fanout"  url="amqp://loshu:loshu@10.0.162.6:30781" delivery_mode="0" routing_key="minio"
```

## Current Behavior
console config error
<img width="1139" alt="截屏2022-01-10 下午10 01 38" src="https://user-images.githubusercontent.com/5196113/148781311-b5f51c19-a874-4451-b3dd-5969ebc00c88.png">

 mc set rabbitmq errors
```
mc admin config set minio/ notify_amqp:1 exchange="minio" exchange_type="fanout"  url="amqp://loshu:loshu@10.0.162.6:30781" delivery_mode="0" routing_key="minio"  queue_dir="/tmp/events"
mc: <ERROR> Unable to set 'notify_amqp:1 exchange=minio exchange_type=fanout url=amqp://loshu:loshu@10.0.162.6:30781 delivery_mode=0 routing_key=minio queue_dir=/tmp/events' to server. We encountered an internal error, please try again. (ReadMapCB: expect { or n, but found �, error found in #1 byte of ...|À��W��b�
                                                                                                               o|..., bigger context ...|À��W��b�
                                                                                                                                                 o����sz��e��E&��������,�Ţ�'�0�vM|�|...).

```
minio service log
```
Jan 10 22:56:34 loshu-bdt05 minio[64217]: API: SetConfigKV()
Jan 10 22:56:34 loshu-bdt05 minio[64217]: Time: 14:56:34 UTC 01/10/2022
Jan 10 22:56:34 loshu-bdt05 minio[64217]: DeploymentID: 41712749-9e82-4a5c-bd97-ae71ff343008
Jan 10 22:56:34 loshu-bdt05 minio[64217]: RequestID: 16C8F096D543E74B
Jan 10 22:56:34 loshu-bdt05 minio[64217]: RemoteHost: 10.0.169.239
Jan 10 22:56:34 loshu-bdt05 minio[64217]: Host: 10.0.160.115:9199
Jan 10 22:56:34 loshu-bdt05 minio[64217]: UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2022-01-07T06-01-38Z
Jan 10 22:56:34 loshu-bdt05 minio[64217]: [144B blob data]
Jan 10 22:56:34 loshu-bdt05 minio[64217]: [44B blob data]
Jan 10 22:56:34 loshu-bdt05 minio[64217]: 5: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
Jan 10 22:56:34 loshu-bdt05 minio[64217]: 4: cmd/admin-handler-utils.go:181:cmd.toAdminAPIErrCode()
Jan 10 22:56:34 loshu-bdt05 minio[64217]: 3: cmd/admin-handler-utils.go:168:cmd.toAdminAPIErr()
Jan 10 22:56:34 loshu-bdt05 minio[64217]: 2: cmd/admin-handlers-config-kv.go:127:cmd.adminAPIHandlers.SetConfigKVHandler()
Jan 10 22:56:34 loshu-bdt05 minio[64217]: 1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
Unsure

## Your Environment

```
mc admin info minio
●  10.0.160.112:9199
   Uptime: 2 hours
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK

●  10.0.160.113:9199
   Uptime: 2 hours
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK

●  10.0.160.114:9199
   Uptime: 2 hours
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK

●  10.0.160.115:9199
   Uptime: 2 hours
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK
```
```
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-01-10 19:38:51 CST; 2h 32min ago
     Docs: https://docs.min.io
  Process: 16678 ExecStartPre=/bin/bash -c if [ -z "${MINIO_VOLUMES}" ]; then echo "Variable MINIO_VOLUMES not set in /etc/default/minio"; exit 1; fi (code=exited, status=0/SUCCESS)
 Main PID: 16680 (minio)
   CGroup: /system.slice/minio.service
           └─16680 /usr/local/bin/minio server --address :9199 --console-address :9001 http://10.0.160.112/mnt/disk5 http://10.0.160.112/mnt/disk6 http://10.0.160.112/mnt/disk7 http://10.0.160.112/mnt/...

Jan 10 22:04:12 loshu-bdt02 minio[16680]: RemoteHost: 10.0.169.239
Jan 10 22:04:12 loshu-bdt02 minio[16680]: Host: 10.0.160.112:9199
Jan 10 22:04:12 loshu-bdt02 minio[16680]: UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2022-01-07T06-01-38Z
Jan 10 22:04:12 loshu-bdt02 minio[16680]: [144B blob data]
Jan 10 22:04:12 loshu-bdt02 minio[16680]: [44B blob data]
Jan 10 22:04:12 loshu-bdt02 minio[16680]: 5: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
Jan 10 22:04:12 loshu-bdt02 minio[16680]: 4: cmd/admin-handler-utils.go:181:cmd.toAdminAPIErrCode()
Jan 10 22:04:12 loshu-bdt02 minio[16680]: 3: cmd/admin-handler-utils.go:168:cmd.toAdminAPIErr()
Jan 10 22:04:12 loshu-bdt02 minio[16680]: 2: cmd/admin-handlers-config-kv.go:127:cmd.adminAPIHandlers.SetConfigKVHandler()
Jan 10 22:04:12 loshu-bdt02 minio[16680]: 1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

**Comment by ming12713** [comment]
mc load config error 
```
mc admin config export minio > minio
mc admin config import minio < minio
mc: <ERROR> Unable to set server config. We encountered an internal error, please try again.
```

**Comment by harshavardhana** [comment]
> mc load config error 
> ```
> mc admin config export minio > minio
> mc admin config import minio < minio
> mc: <ERROR> Unable to set server config. We encountered an internal error, please try again.
> ```

Please upgrade to latest. Looks like your JSON config is corrupted.

**Comment by harshavardhana** [comment]
@ming12713 

```
mc admin config history minio/
RestoreId: 1e81871e-2572-4461-8dd5-c130c5e10907
Date: Wed, 01 Dec 2021 02:07:33 GMT

region name="us-east-1"

RestoreId: 0da29868-4b71-4718-995e-19313ddc0ce6
Date: Mon, 06 Dec 2021 08:13:22 GMT

cache drives="/" expiry="90" quota="80" exclude="" after="0" watermark_low="70" watermark_high="80"

RestoreId: 007c7a09-c12c-4f0f-a65e-2086abf629a7
Date: Tue, 07 Dec 2021 07:21:49 GMT

subnet license=

RestoreId: 081172be-a1c6-421a-abef-af3b08938655
Date: Tue, 07 Dec 2021 07:24:06 GMT

subnet license= api_key=

RestoreId: 2ba5e33a-ee8b-4bed-9c2b-95dbd221a6bb
Date: Mon, 13 Dec 2021 18:26:34 GMT

api requests_max="0" cors_allow_origin="*" replication_workers="250" replication_failed_workers="8"

RestoreId: 27dd0d96-60aa-4b43-bc73-ec4b7442a104
Date: Tue, 21 Dec 2021 14:39:47 GMT

notify_mqtt broker="tcp://broker.emqx.io:1883" topic="/minio/events/test"

RestoreId: 16ad04ce-3bbc-4b4f-9214-2b8d1e14fa38
Date: Wed, 22 Dec 2021 08:10:33 GMT

region name=eu-west-1

RestoreId: 02d7a9c8-9e69-4074-9132-9ac4676f436a
Date: Wed, 22 Dec 2021 09:39:58 GMT

subnet license= api_key=72a68ad4-6fdc-42e4-9833-076f2524fa90

RestoreId: 199d3026-9dee-4d7d-bcd2-3acc6f68b4cb
Date: Sat, 25 Dec 2021 22:23:44 GMT

scanner delay=100

RestoreId: 1acf6dc3-a6ce-43e0-b1e6-5137bc20caff
Date: Wed, 05 Jan 2022 15:50:18 GMT

audit_webhook enable=off
```

You can restore

```
mc admin config restore minio/ <restore_id>
```

**Comment by harshavardhana** [comment]
or you can just do same `config` file and then

```
site name= region= 
```

```
mc admin config import minio/ < config
```

**Comment by ming12713** [comment]
> mc admin config restore minio/

@harshavardhana restore failed 
```
 mc admin config history minio/
RestoreId: 014697ef-9c19-4153-8bce-a116d2881057
Date: Sun, 09 Jan 2022 08:05:42 GMT

notify_mqtt:1 broker=tcp://10.0.162.6:30518 password=loshu queue_dir= queue_limit=0 reconnect_interval=0s keep_alive_interval=0s qos=1 topic=minio username=loshu

RestoreId: 1062e538-992a-4012-b2d1-442eb71a270e
Date: Sun, 09 Jan 2022 08:05:42 GMT

compression enable=off

```

```
mc admin config restore minio/ 014697ef-9c19-4153-8bce-a116d2881057
mc: <ERROR> Unable to restore server configuration. We encountered an internal error, please try again. (ReadMapCB: expect { or n, but found �, error found in #1 byte of ...|À��W��b�
                                                                                                                                                                                      o|..., bigger context ...|À��W��b�
     o����sz��e��E&��������,�Ţ�'�0�vM|�|...).
```

**Comment by harshavardhana** [comment]
You can do this https://github.com/minio/minio/issues/14072#issuecomment-1009180395

**Comment by ming12713** [comment]
> or you can just do same `config` file and then
> 
> ```
> site name= region= 
> ```
> 
> ```
> mc admin config import minio/ < config
> ```
thanks .
i had try ,but ,import config failed too! 

```
site name= region= 
storage_class standard= rrs=EC:2 
# cache drives= exclude= expiry=90 quota=80 after=0 watermark_low=70 watermark_high=80 range=on commit= 
# compression enable=off allow_encryption=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml,binary/octet-stream 
# etcd endpoints= path_prefix= coredns_path=/skydns client_cert= client_cert_key= 
# identity_openid config_url= client_id= client_secret= claim_name=policy claim_userinfo= role_policy= claim_prefix= redirect_uri= redirect_uri_dynamic=off scopes= 
# identity_ldap server_addr= user_dn_search_base_dn= user_dn_search_filter= group_search_filter= group_search_base_dn= tls_skip_verify=off server_insecure=off server_starttls=off lookup_bind_dn= lookup_bind_password= 
# identity_tls skip_verify=off 
# policy_opa url= auth_token= 
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_workers=250 replication_failed_workers=8 transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m 
heal bitrotscan=off max_sleep=1s max_io=100 
scanner delay=10 max_wait=15s cycle=1m 
# logger_webhook enable=off endpoint= auth_token= client_cert= client_key= queue_size=100000 
# audit_webhook enable=off endpoint= auth_token= client_cert= client_key= queue_size=100000 
# audit_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off version= 
# notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key= 
# notify_amqp enable=off url= exchange= exchange_type= routing_key= mandatory=off durable=off no_wait=off internal=off auto_deleted=off delivery_mode=0 publisher_confirms=off queue_limit=0 queue_dir= 
# notify_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir= version= 
# notify_mqtt enable=off broker= topic= password= username= qos=0 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0 
# notify_nats enable=off address= subject= username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 streaming=off streaming_async=off streaming_max_pub_acks_in_flight=0 streaming_cluster_id= queue_dir= queue_limit=0 
# notify_nsq enable=off nsqd_address= topic= tls=off tls_skip_verify=off queue_dir= queue_limit=0 
# notify_mysql enable=off format=namespace dsn_string= table= queue_dir= queue_limit=0 max_open_connections=2 
# notify_postgres enable=off format=namespace connection_string= table= queue_dir= queue_limit=0 max_open_connections=2 
# notify_elasticsearch enable=off url= format=namespace index= queue_dir= queue_limit=0 username= password= 
# notify_redis enable=off format=namespace address= key= password= queue_dir= queue_limit=0 
subnet license= api_key=

```

```
mc admin config import minio < minio                                                                                                                                                      
mc: <ERROR> Unable to set server config. We encountered an internal error, please try again.

```

**Comment by harshavardhana** [comment]
> mc: <ERROR> Unable to set server config. We encountered an internal error, please try again.

This really doesn't make sense - are you disks local disks or some kind of networked disks? @ming12713

**Comment by harshavardhana** [comment]
can you provide the output of 

```
mc admin inspect minio/.minio.sys/config/config.json/**
```

and attach the output here?

**Comment by ming12713** [comment]
> > mc:  Unable to set server config. We encountered an internal error, please try again.
> 
> This really doesn't make sense - are you disks local disks or some kind of networked disks? @ming12713

all disks is local disks

**Comment by ming12713** [comment]
> mc admin inspect minio/.minio.sys/config/config.json/**

```
min at min-dev in /tmp/backup-minio 
$ mc admin inspect minio/.minio.sys/config/config.json/**
zsh: no matches found: minio/.minio.sys/config/config.json/**
(base) 
min at min-dev in /tmp/backup-minio 
$ mc admin inspect minio/.minio.sys/config/
mc: File data successfully downloaded as inspect.17c35511.zip
(base)

```
![Screenshot from 2022-01-11 09-33-09](https://user-images.githubusercontent.com/5196113/148865757-adcbede0-5bd7-4349-a107-5cd9885b71fa.png)


config file is empty

**Comment by ming12713** [comment]
> can you provide the output of
> 
> ```
> mc admin inspect minio/.minio.sys/config/config.json/**
> ```
> 
> and attach the output here?



> can you provide the output of
> 
> ```
> mc admin inspect minio/.minio.sys/config/config.json/**
> ```
> 
> and attach the output here?

**Comment by ming12713** [comment]
> can you provide the output of
> 
> ```
> mc admin inspect minio/.minio.sys/config/config.json/**
> ```
> 
> and attach the output here?
minio admin config export minio is follow
[#14072](https://github.com/minio/minio/issues/14072#issuecomment-1009516863)

**Comment by ming12713** [comment]
=

**Comment by harshavardhana** [comment]
If you are in zsh then you need to escape `**`  or use bash

```
~ bash
~ mc admin inspect alias/.minio.sys/config/config.json/**
download.
~ CTRL-D
```

to come out of bash

**Comment by ming12713** [comment]
> mc admin inspect alias/.minio.sys/config/config.json/**
[inspect.8fbfdd3f.zip](https://github.com/minio/minio/files/7843208/inspect.8fbfdd3f.zip)

**Comment by ming12713** [comment]
> If you are in zsh then you need to escape `**` or use bash
> 
> ```
> ~ bash
> ~ mc admin inspect alias/.minio.sys/config/config.json/**
> download.
> ~ CTRL-D
> ```
> 
> to come out of bash
thanks, output info
[inspect.8fbfdd3f.zip](https://github.com/minio/minio/files/7843212/inspect.8fbfdd3f.zip)

**Comment by harshavardhana** [comment]
> mc admin info minio
> ●  10.0.160.112:9199
>    Uptime: 2 hours
>    Version: 2022-01-08T03:11:54Z
>    Network: 4/4 OK
>    Drives: 6/6 OK
> 
> ●  10.0.160.113:9199
>    Uptime: 2 hours
>    Version: 2022-01-08T03:11:54Z
>    Network: 4/4 OK
>    Drives: 6/6 OK
> 
> ●  10.0.160.114:9199
>    Uptime: 2 hours
>    Version: 2022-01-08T03:11:54Z
>    Network: 4/4 OK
>    Drives: 6/6 OK
> 
> ●  10.0.160.115:9199
>    Uptime: 2 hours
>    Version: 2022-01-08T03:11:54Z
>    Network: 4/4 OK
>    Drives: 6/6 OK

did you move around the servers in this setup? 

.            └─16680 /usr/local/bin/minio server --address :9199 --console-address :9001 http://10.0.160.112/mnt/disk5 http://10.0.160.112/mnt/disk6 http://10.0.160.112/mnt/disk7 http://10.0.160.112/mnt/...

This is a bad way to setup MinIO - I think you re-do your setup to use ellipses otherwise here you are losing HA while service is coming up.

**Comment by harshavardhana** [comment]
> Upgrade minio from RELEASE.2020-01-03T19-12-21Z to RELEASE.2022-01-08T03-11-54Z sucuess

I didn't realize this was a very old upgrade - I will verify this upgrade path how it is working.

**Comment by ming12713** [comment]
> > Upgrade minio from RELEASE.2020-01-03T19-12-21Z to RELEASE.2022-01-08T03-11-54Z sucuess
> 
> I didn't realize this was a very old upgrade - I will verify this upgrade path how it is working.

i had try ,test cluster is same as prod cluster, test cluster upgrade is ok ,but test cluster no data , so ,i thinks promblem is .minio.sys ? 
test cluster data dir is empty ,prod cluster data dir not empty!

**Comment by harshavardhana** [comment]
> i had try ,test cluster is same as prod cluster, test cluster upgrade is ok ,but test cluster no data , so ,i thinks promblem is .minio.sys ?
> test cluster data dir is empty ,prod cluster data dir not empty!

The issue is because the version is too old - we need to check if there is an issue with upgrades with such old versions. your setup is almost 2yrs old.

**Comment by ming12713** [comment]
> > i had try ,test cluster is same as prod cluster, test cluster upgrade is ok ,but test cluster no data , so ,i thinks promblem is .minio.sys ?
> > test cluster data dir is empty ,prod cluster data dir not empty!
> 
> The issue is because the version is too old - we need to check if there is an issue with upgrades with such old versions. your setup is almost 2yrs old.

ok,thanks

**Comment by ming12713** [comment]
> > mc admin info minio
> > ●  10.0.160.112:9199
> > Uptime: 2 hours
> > Version: 2022-01-08T03:11:54Z
> > Network: 4/4 OK
> > Drives: 6/6 OK
> > ●  10.0.160.113:9199
> > Uptime: 2 hours
> > Version: 2022-01-08T03:11:54Z
> > Network: 4/4 OK
> > Drives: 6/6 OK
> > ●  10.0.160.114:9199
> > Uptime: 2 hours
> > Version: 2022-01-08T03:11:54Z
> > Network: 4/4 OK
> > Drives: 6/6 OK
> > ●  10.0.160.115:9199
> > Uptime: 2 hours
> > Version: 2022-01-08T03:11:54Z
> > Network: 4/4 OK
> > Drives: 6/6 OK
> 
> did you move around the servers in this setup?
> 
> . └─16680 /usr/local/bin/minio server --address :9199 --console-address :9001 http://10.0.160.112/mnt/disk5 http://10.0.160.112/mnt/disk6 http://10.0.160.112/mnt/disk7 http://10.0.160.112/mnt/...
> 
> This is a bad way to setup MinIO - I think you re-do your setup to use ellipses otherwise here you are losing HA while service is coming up.

in my test cluster 
i replace ip to hostname ,and data dir to {...}, and get some erros for .minio.sys/backend

![Screenshot from 2022-01-11 11-31-40](https://user-images.githubusercontent.com/5196113/148876734-2bc6cc3c-149f-4aa1-9134-a21e937f53be.png)


it seems minio not reslove hostname !

cat /etc/default/minio
```
# Remote volumes to be used for MinIO server.
#MINIO_VOLUMES=http://10.0.169.199/mnt/minio1 http://10.0.169.199/mnt/minio2 \
#               http://10.0.169.199/mnt/minio3 \
#               http://10.0.168.231/mnt/minio1 http://10.0.168.231/mnt/minio2 \
#               http://10.0.168.231/mnt/minio3
MINIO_VOLUMES=http://loshu-kk0{1...2}:9199/mnt/minio{1...3}
# Use if you want to run MinIO on a custom port.
MINIO_OPTS="--address :9199 --console-address :9001
```

**Comment by harshavardhana** [comment]
> # Remote volumes to be used for MinIO server.
> MINIO_VOLUMES=http://loshu-kk0{1...2}:9199/mnt/minio{1...3}
> MINIO_OPTS="--address :9199 --console-address :9001

You cannot convert setups with ellipses like this from single command line @ming12713 - you have to re-do the setup.

**Comment by harshavardhana** [comment]
It will not work @ming12713

**Comment by ming12713** [comment]
> > # Remote volumes to be used for MinIO server.
> > MINIO_VOLUMES=[http://loshu-kk0{1...2}:9199/mnt/minio{1...3}](http://loshu-kk0%7B1...2%7D:9199/mnt/minio%7B1...3%7D)
> > MINIO_OPTS="--address :9199 --console-address :9001
> 
> You cannot convert setups with ellipses like this from single command line @ming12713 - you have to re-do the setup.

thanks. follow is work
```
MINIO_VOLUMES=http://10.0.168.231:9199/mnt/minio{1...3} http://10.0.169.199:9199/mnt/minio{1...3}
```

You cannot convert setups with ellipses like this from single command line @ming12713 - you have to re-do the setup.

**Comment by ming12713** [comment]
> > > # Remote volumes to be used for MinIO server.
> > > MINIO_VOLUMES=[http://loshu-kk0{1...2}:9199/mnt/minio{1...3}](http://loshu-kk0%7B1...2%7D:9199/mnt/minio%7B1...3%7D)
> > > MINIO_OPTS="--address :9199 --console-address :9001
> > 
> > 
> > You cannot convert setups with ellipses like this from single command line @ming12713 - you have to re-do the setup.
> 
> thanks. follow is work
> 
> ```
> MINIO_VOLUMES=http://10.0.168.231:9199/mnt/minio{1...3} http://10.0.169.199:9199/mnt/minio{1...3}
> ```
> 
> You cannot convert setups with ellipses like this from single command line @ming12713 - you have to re-do the setup.

like this ? ``` MINIO_VOLUMES=http://loshu-kk0{1...2}/mnt/minio{1...3} ``` 
if not ,please tell me the right way ! thanks !

reslove hostname in /etc/hosts/
```
10.0.169.199 loshu-kk01
10.0.168.231 loshu-kk02
```

**Comment by klauspost** [comment]
@ming12713 You are welcome to try, but as Harsha writes you should re-do your setup. It is a fundamentally bad setup.

If you need further assistance look into our [subscription offer](https://min.io/pricing) where we can go into more details.

**Comment by ming12713** [comment]
> @ming12713 You are welcome to try, but as Harsha writes you should re-do your setup. It is a fundamentally bad setup.
> 
> If you need further assistance look into our [subscription offer](https://min.io/pricing) where we can go into more details.

@klauspost i just follow 


> @ming12713 You are welcome to try, but as Harsha writes you should re-do your setup. It is a fundamentally bad setup.
> 
> If you need further assistance look into our [subscription offer](https://min.io/pricing) where we can go into more details.

@klauspost we setup cluster follow official [bkm  ](https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html)

<img width="941" alt="截屏2022-01-11 下午9 51 42" src="https://user-images.githubusercontent.com/5196113/148955619-a90f5627-192c-4020-afa8-70cb6bf1dff5.png">

this bkm is wrong? , BTW my quesion is configure load error ,thanks ~

**Comment by harshavardhana** [comment]
Tested the upgrade here it looks good

```
./minio.RELEASE.2020-01-03T19-12-21Z server ~/minio-old{1...4}

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 2 years ago ┃
┃ Update: Run `mc admin update`                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Status:         4 Online, 0 Offline. 
Endpoint:  http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://127.0.0.1:9000                                  
AccessKey: minioadmin 
SecretKey: minioadmin 

Browser Access:
   http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://127.0.0.1:9000                                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.185:9000 minioadmin minioadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
Restarting on service signal
Automatically configured API requests per node based on available memory on the system: 167
Status:         4 Online, 0 Offline. 
API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://127.0.0.1:9000                                   
RootUser: minioadmin 
RootPass: minioadmin 

Console: http://10.0.0.185:46193 http://172.17.0.1:46193 http://172.19.0.1:46193 http://172.20.0.1:46193 http://127.0.0.1:46193                  
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.185:9000 minioadmin minioadmin

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (46193), please use --console-address ":PORT" to choose a static port.
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
```

I don't see the problems here.
