### ISSUE TITLE
Error: config file not found

### ISSUE THREAD

**Issue by shivabohemian** [minio/minio#14081]
## Expected Behavior

When I start minio in erasure coding mode, there should be no errors

## Current Behavior

An error is as follows, but it doesn't seem to have any effect.
<img width="1081" alt="截屏2022-01-11 上午11 16 43" src="https://user-images.githubusercontent.com/39078424/148875750-d19e9d59-cc60-462c-b7d4-f50252895d8d.png">

## Possible Solution

Maybe there is no ".usage.json" file before the bucket is created

## Steps to Reproduce (for bugs)

1. Start minio with 4 drives 
2. Log in console
3. Create a bucket
4. Now you can see the error
## Regression

maybe

## Your Environment

* Version used (`minio --version`):latest
* Server setup and configuration:server /Volumes/data{1...4} --console-address :9001
* Operating System and version (`uname -a`):Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by harshavardhana** [comment]
> When I start minio in erasure coding mode, there should be no errors

Yes agreed PR sent #14082

**Comment by shivabohemian** [comment]
Great job~
