### ISSUE TITLE
minio管理页面显示的桶大小与实际不符，相差较大！

### ISSUE THREAD

**Issue by liuxianqing** [minio/minio#14088]
我做了一个双机热备份，开始，主服务器的管理页面桶显示大小为1.2T，但是备份的‘minio’，桶里竟然备份出了8.2T，然后我去服务器中查了实际大小，发现桶中的数据确实是8.2T，但是为什么管理页面只显示了1.2T的桶大小

**Comment by liuxianqing** [comment]
为什么封我

**Comment by klauspost** [comment]
@liuxianqing Use English please. 

(Google Translate)

> I made a dual-system hot backup. At first, the bucket size on the management page of the main server showed that the size was 1.2T, but the backup 'minio' actually backed up 8.2T in the bucket. Then I went to the server to check the actual size and found that The data in the bucket is indeed 8.2T, but why does the management page only display the bucket size of 1.2T

Usage takes a while to update. The usage will update once the files have been scanned.
