### ISSUE TITLE
"Invalid set drive count" error when try to expand minio cluster

### ISSUE THREAD

**Issue by RezaBabapour** [minio/minio#14091]
There is a existing minio cluster deployed in docker container, It runs with this command on each server:
```
minio server --address ${Loc_IP}:9000 http://minio.alpha{08...15}/minio_disks/data{1...6}
```
I want to expand it with 4 other servers same as existing servers with this command:
```
minio server --address ${Loc_IP}:9000 http://minio.alpha{08...15}/minio_disks/data{1...6} http://minio.beta{01...04}/minio_disks/data{1...6}
```

## Expected Behavior
Expanding cluster with 4 new server as [distributed-minio doc](https://docs.min.io/docs/distributed-minio-quickstart-guide.html) said.

## Current Behavior
Getting blow error in new nodes:
```
ERROR Invalid command line arguments: Invalid set drive count. Acceptable values for 24 number drives are [4 6 8 12]
       > Please provide correct combination of local/remote paths
       HINT:
         For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```
I don't understand the part `Acceptable values for 24 number drives are [4 6 8 12]`
## Your Environment

* minio version RELEASE.2020-11-06T23-17-07Z.2020-11-10T12-56-38Z
* There is no configuration, minio runs inside docker container. build from source 
* Linux minio 4.19.0-13-amd64 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You are using a very old version of MinIO you are advised to upgrade.

Also please stick to our releases and do not custom build your own containers. Use published containers at 

- minio/minio:latest
- quay.io/minio/minio:latest
