### ISSUE TITLE
Web console: bucket contents not shown for IAM  user

### ISSUE THREAD

**Issue by bpedersen2** [minio/minio#14099]
## Expected Behavior
A  IAM user with  the following policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:HeadBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:GetBucketPolicyStatus"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mytestbucket"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:delimiter": [
                        "/"
                    ],
                    "s3:prefix": [
                        "",
                        "*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::mytestbucket/*"
            ]
        }
    ]
}
```
should be able to see the bucket contents in the console.

## Current Behavior
The user can see the bucket, but it is shown as  empty. 
The use can successfully upload files.
A user with consoleAdmin role does see the content.

## Steps to Reproduce (for bugs)

1. Create a  IAM user  with role 'consoletest'
2. Create a IAM policy 'consoletest' wiht above content
3. create a bucket mytestbucket as admin and upload some file
4.  login as the test user  -> no files are shown in the console

## Your Environment
* Version used (`minio --version`): MinIO VERSION 
2022-01-08T03:11:54Z  (docker)
* Server setup and configuration:   minio server --console-address ":9001" http://minio1/data{1...4}

* Operating System and version (`uname -a`): 
```Linux  5.11.0-1021-oracle #22~20.04.1-Ubuntu SMP Fri Oct 22 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by bpedersen2** [comment]
Additional Info: 
Trace shows a 403 forbidden for HeadBucket

**Comment by bpedersen2** [comment]
After removing the condition it seems to work as expected. Is the condtion incorrect or is this a bug?

**Comment by bpedersen2** [comment]
Sorry, It now works using the mc client, but not in  the web console.

**Comment by bpedersen2** [comment]
More debugging: 
after allowing : 
```
                 "s3:GetBucketTagging",
                "s3:GetBucketPolicy",
```

It fails with s3.GetBucketTagging 404 Not found

**Comment by bpedersen2** [comment]
Maybe needs a documentation update as it works with: 
==> GetBucketTagging is required for the web console

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketPolicyStatus",
                "s3:HeadBucket",
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:GetBucketTagging"
            ],
            "Resource": [
                "arn:aws:s3:::mytestbucket",
                "arn:aws:s3:::mytestbucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::mytestbucket/*"
            ]
        }
    ]
}
```

**Comment by harshavardhana** [comment]
@Alevsk ^^
