### ISSUE TITLE
Minio console-address configuration via env vars

### ISSUE THREAD

**Issue by garyhuntddn** [minio/minio#14107]
The change to the use of the command-line parameter ```--console-address``` requires the use of the ```command``` parameter in docker/docker-compose.

I would consider it better if that parameter could be supplied via an env var so that the ```command``` doesn't need to be overwritten.

Lines 396-420 in ```common-main.go``` concern themselves with setting the ```globalMinioConsoleHost``` and ```globalMinoConsolePort```.

From what I can tell the same logic could be introduced into function ```handleCommonEnvVars``` to perform the same but with env vars as the source e.g. ```MINIO_CONSOLE_HOST``` and ```MINIO_CONSOLE_PORT```.

I'm happy to have a stab at a PR if this is something the community would like.

**Comment by harshavardhana** [comment]
> From what I can tell the same logic could be introduced into function `handleCommonEnvVars` to perform the same but with env vars as the source e.g. `MINIO_CONSOLE_HOST` and `MINIO_CONSOLE_PORT`.

It will be called `MINIO_CONSOLE_ADDRESS=":9090"` or `MINIO_CONSOLE_ADDRESS="mydomain.com:9090"`

**Comment by garyhuntddn** [comment]
Nicely done @harshavardhana - I hadn't realised it would be that trivial to implement as it seems the support code was already in place for the way that the console args are interpreted.
