### ISSUE TITLE
Unable to read 'format.json' corrupted backend format, specified disk mount has unexpected previous content

### ISSUE THREAD

**Issue by RezaBabapour** [minio/minio#14100]
This issue is following issue https://github.com/minio/minio/issues/14092#issue-1100500920
After removing `.minio.sys` I get this error and cluster won't start:

```
Unable to read 'format.json' from http://minio.alpha15:9000/minio_disks/data6: some unexpected files '[{large-files 0001-01-01 00:00:00 +0000 UTC} {videos 0001-01-01 00:00:00 +0000 UTC} {files 0001-01-01 00:00:00 +0000 UTC} {images 0001-01-01 00:00:00 +0000 UTC} {stickers 0001-01-01 00:00:00 +0000 UTC} {backups 0001-01-01 00:00:00 +0000 UTC} {mySoft 0001-01-01 00:00:00 +0000 UTC} {.minio.sys 0001-01-01 00:00:00 +0000 UTC}]' found on /minio_disks/data6: corrupted backend format, specified disk mount has unexpected previous content
```
The cluster don't initialize. How I can recreate cluster? 

## Expected Behavior
Minio receate `.minio.sys` directory.

## Current Behavior
Looks like new created `.minio.sys` is corrupted.

**Comment by harshavardhana** [comment]
> ```
> Unable to read 'format.json' from http://minio.alpha15:9000/minio_disks/data6: some unexpected files '[{large-files 0001-01-01 00:00:00 +0000 UTC} {videos 0001-01-01 00:00:00 +0000 UTC} {files 0001-01-01 00:00:00 +0000 UTC} {images 0001-01-01 00:00:00 +0000 UTC} {stickers 0001-01-01 00:00:00 +0000 UTC} {backups 0001-01-01 00:00:00 +0000 UTC} {mySoft 0001-01-01 00:00:00 +0000 UTC} {.minio.sys 0001-01-01 00:00:00 +0000 UTC}]' found on /minio_disks/data6: corrupted backend format, specified disk mount has unexpected previous content
> ```

you shouldn't delete `.minio.sys`  - I specifically asked you to delete `.minio.sys/config/` - its going to a lot of manual work to recover now. https://github.com/minio/minio/issues/14092#issuecomment-1011233633
