### ISSUE TITLE
recovered elements not visible in bucket

### ISSUE THREAD

**Issue by yelhouti** [minio/minio#14111]
## Expected Behavior
We recreating a node with content from a previous node files should be present

## Current Behavior
Buckets are visible but no files in them

## Steps to Reproduce (for bugs)
1. create a cluster
2. add a bucket
3. add come files
3. backup the PV
4. destroy the cluster 
5. install in a new cluster
6. copy back the PV content
7. check inside the buckets

## Context
I was trying to retrieve a bucket from a crashed cluster.

**Comment by klauspost** [comment]
We do not support any manual modification of backend files.

You should never "backup" and "restore" backend files. Use replication or other methods for backup.
