### ISSUE TITLE
Minio web interface redirecting me to console

### ISSUE THREAD

**Issue by yelhouti** [minio/minio#14110]
## Expected Behavior
When I install minio using the chart and try to open minio in a browser it shouldn't redirect me to 9001

## Current Behavior
It redirects redirects me to https://minio.mydomain.com:9001

## Possible Solution
Maybe this is the new behavior and you don't have anymore two servers one just for viewing that I expose via ingress and the other for the console where I can create policies... that is internal.

## Steps to Reproduce (for bugs)
1. install the chart using helm.
2. enable ingress but not consoleIngress

try to access the ingress.

## Context
I am trying to reduce the surface risk as was described in the previous doc, by not exposing a server with more functionalities that publicly needed.

## Regression
Yes

## Your Environment
RELEASE.2021-12-29T06-49-06Z

**Comment by vadmeste** [comment]
@yelhouti if I understood correctly, you want to disable MinIO Console ? you can set this, MINIO_BROWSER=off

**Comment by yelhouti** [comment]
not exactly, I want to be able to access minio using the browser. Bu tif I remember correctly, they where 2 interfaces.
1. console with full access...
2. another one with only the possibility of browsing buckets...

I want to expose the two 2 but not the 1

**Comment by klauspost** [comment]
@yelhouti What is visible depends on permissions.

**Comment by yelhouti** [comment]
@klauspost but you used to have two interfaces right ?

**Comment by klauspost** [comment]
@yelhouti The legacy browser has been replaced. The S3 API and Console now operate on different ports.

**Comment by yelhouti** [comment]
@klauspost thanks for confirming, I will refrain from exposing the console to the public then.

**Comment by yelhouti** [comment]
@klauspost do you know by any chance an S3 viewer that can be locally or hosted and points to an S3 bucket ?

**Comment by klauspost** [comment]
@yelhouti The console does that. There are plenty of alternatives out there.
