### ISSUE TITLE
Why doesn't the SDK have an admin API

### ISSUE THREAD

**Issue by shivabohemian** [minio/minio#14119]
**Is your feature request related to a problem? Please describe.**
If I want to get data usage info of bucket, I can't find a sdk interface. But I found that the http api called "/accountinfo" may meet my need.

**Describe the solution you'd like**
Is it possible to make admin API into SDK？

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
https://github.com/minio/madmin-go - use this @shivabohemian

**Comment by shivabohemian** [comment]
Great job!!!
