### ISSUE TITLE
ListObjects order issue

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1411]
In an XL setup, at `fs` layer, if `object-tar/part.json` is the 1000th entry and `object/part.json` is 1001'st entry

the client side will receive in the order:

```
object-tar
object
```

which is incorrect.

**Comment by krishnasrinivas** [comment]
it can be fixed by doing this:
- leaf directory will have `?` in the end : `object-tar?/part.json` `object?/part.json`
- in the comparison function for sort, when we compare two strings for ex. `object-tar?/` and `object?/` we should compare after stripping `?/`

**Comment by harshavardhana** [comment]
Adding a new character is not safe. It still wont hold good for all UTF-8 characters

**Comment by krishnasrinivas** [comment]
can objectname have `?` because `?` in URL is for options

**Comment by harshavardhana** [comment]
Yes objectname can have `?`

**Comment by krishnasrinivas** [comment]
instead of `?` can have `.__leaf__` suffix which will look cleaner on the backend

advantages:
- fix issue #1411 by stripping off `.__leaf__` use the resulting strings for comparison function in Sort at `FS`
- it will help XL code in detecting if a directory is a leaf node just by looking at the name and does not have to do a listing inside it.

**Comment by krishnasrinivas** [comment]
fixed by 247e835d7bb01d3592765946e8296b494a0aa846
