### ISSUE TITLE
Retrieval of cluster metrics hang if one node is down

### ISSUE THREAD

**Issue by atlasz911** [minio/minio#14130]
## Expected Behavior
Retrieving metrics data from http://<server:port>/minio/v2/metrics/cluster should be provided within a reasonable period even if one of the nodes is unavailable.

## Current Behavior
It appears that the metric collector keeps waiting for connection timeout (about 1 minute for me) when one of the nodes crashed or is shut down intentionally.

## Possible Solution
Maybe offline nodes could be skipped when collecting metrics?

## Steps to Reproduce (for bugs)
I set up a small test cluster with 4 nodes to work on metrics collection for monitoring.

1) Run command
time curl -sSL -H "Authorization: Bearer <token>" http://<server:port>/minio/v2/metrics/cluster
It returns data within a fraction of seconds
real    0m0.171s
user    0m0.012s
sys     0m0.012s

2) Stop any node instance and leave the rest running
systemctl stop minio

3) Checking cluster status
[root@minio1 ~]# /opt/minio/bin/mc admin info local
●  minio1.domain.local:4443
   Uptime: 2 days
   Version: 2022-01-08T03:11:54Z
   Network: 3/4 OK
   Drives: 1/1 OK

●  minio2.domain.local:4443
   Uptime: offline
   Drives: 0/1 OK

●  minio3.domain.local:4443
   Uptime: 2 days
   Version: 2022-01-08T03:11:54Z
   Network: 3/4 OK
   Drives: 1/1 OK

●  minio4.domain.local:4443
   Uptime: 18 hours
   Version: 2022-01-08T03:11:54Z
   Network: 3/4 OK
   Drives: 1/1 OK

20 MiB Used, 32 Buckets, 193 Objects
3 drives online, 1 drive offline

Minio had enough time ti register that one node is unavailable.

4) Re-run the command to collect metrics from http api:
time curl -sSL -H "Authorization: Bearer <token>" http://<server:port>/minio/v2/metrics/cluster
The command provides the expected data but it took over a minute to finish. My agent times out long before that.
real    1m4.354s
user    0m0.016s
sys     0m0.015s

## Context
If I loose the ability to reliably collect metrics when one node goes down than I loose the ability to follow-up on additional consequent issues while the node is unavailable.

## Regression
Version: 2022-01-08T03:11:54Z

## Your Environment
* Version used (`minio --version`):
Version: 2022-01-08T03:11:54Z

* Server setup and configuration:
MINIO_VOLUMES="http://minio1.domain.local:4443/opt/minio/data\
               http://minio2.domain.local:4443/opt/minio/data\
               http://minio3.domain.local:4443/opt/minio/data\
               http://minio4.domain.local:4443/opt/minio/data\
"
MINIO_ROOT_USER=root
MINIO_ROOT_PASSWORD=**********
MINIO_BROWSER=on
MINIO_OPTS="--address minio1.domain.local:4443 --console-address :4444"

* Operating System and version (`uname -a`):
[root@minio1 ~]# cat /etc/os-release | grep PRET
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
[root@minio1 ~]# uname -a
Linux minio1.local 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Tue Dec 21 19:02:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> If I loose the ability to reliably collect metrics when one node goes down than I loose the ability to follow-up on additional consequent issues while the node is unavailable.

This doesn't make sense @atlasz911 can you provide more details about the setup here? 

> 4\. Re-run the command to collect metrics from http api:
>     time curl -sSL -H "Authorization: Bearer " http://server:port/minio/v2/metrics/cluster
>     The command provides the expected data but it took over a minute to finish. My agent times out long before that.
>     real    1m4.354s
>     user    0m0.016s
>     sys     0m0.015s

which services are you talking to here? 


```
 mc admin info admin/

API: SYSTEM()
Time: 19:07:54 UTC 01/19/2022
DeploymentID: 75622cb2-2abc-4e9b-b9b0-eab210b0b52f
Error: Get "http://127.0.0.1:9102/minio/health/live": dial tcp 127.0.0.1:9102: connect: connection refused (*url.Error)
       5: internal/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       4: internal/logger/logonce.go:92:logger.LogOnceIf()
       3: cmd/admin-server-info.go:58:cmd.getLocalServerProperty()
       2: cmd/peer-rest-server.go:340:cmd.(*peerRESTServer).ServerInfoHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
●  127.0.0.1:9100
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9101
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9102
   Uptime: offline
   Drives: 0/1 OK 

●  127.0.0.1:9103
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9104
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9105
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9106
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9107
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9108
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9109
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9110
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

●  127.0.0.1:9111
   Uptime: 1 minute 
   Version: 2022-01-18T20:44:38Z
   Network: 11/12 OK 
   Drives: 1/1 OK 

11 drives online, 1 drive offline
```

I tested the response after node going down is very minimal 

```
time curl -s 127.0.0.1:9103/minio/v2/metrics/cluster >/dev/null

API: SYSTEM()
Time: 19:09:00 UTC 01/19/2022
DeploymentID: 75622cb2-2abc-4e9b-b9b0-eab210b0b52f
Error: /peermetrics "http://127.0.0.1:9102/minio/peer/v18": remote server offline (*rest.NetworkError)
       peerAddress=127.0.0.1:9102
       5: internal/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       4: internal/logger/logonce.go:92:logger.LogOnceIf()
       3: cmd/notification.go:1498:cmd.(*NotificationSys).GetClusterMetrics()
       2: cmd/metrics-v2.go:1714:cmd.(*minioClusterCollector).Collect()
       1: github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446:prometheus.(*Registry).Gather.func1()

real	0m0.027s
user	0m0.000s
sys	0m0.004s
```

Looks like you have other networking problems here @atlasz911

**Comment by harshavardhana** [comment]
Also, I suspect that your DNS resolution or some port binding is still active which leads to a 1minute of timeout - there is nothing that can be done about that.
