### ISSUE TITLE
Certain Bucket Metrics are not Reporting

### ISSUE THREAD

**Issue by dcpontius** [minio/minio#14144]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Some of the bucket metrics have stopped appearing in exported Prometheus metrics.

## Expected Behavior

Bucket metrics such as minio_bucket_usage_object_total, minio_bucket_usage_total_bytes, minio_bucket_usage_object_total should be among the metrics exported on :9000/minio/v2/metrics/cluster.  These appear to be used by the Minio dashboard view as well as by external Prometheus-based monitoring tools.

## Current Behavior

These metric values are not exported, and the Minio Console dashboard view displays zero buckets, despite the fact that the actual buckets can be browsed from the same webui.

## Steps to Reproduce (for bugs)

1. curl localhost:9000/minio/v2/metrics/cluster | grep bucket_usage

## Context

My Grafana dashboards have stopped working, and the Minio Console webui dashboard view is not working.

## Regression

Yes.  Had worked properly in November 2021 time-frame.  Suspect commit 818f0201f (12/17/2021) as culprit, but I cannot directly identify the defect.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version DEVELOPMENT.2022-01-19T18-48-00Z

Linux dcp-hub-vm-2-9b8c3ef9 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Mon Jul 26 08:06:24 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> * minio version DEVELOPMENT.2022-01-19T18-48-00Z

are you building from source? @dcpontius

**Comment by dcpontius** [comment]
I believe we are building from source; I'm somewhat removed from the VM build procedure, but I believe we are.  Previously, when I first saw this behavior, we were pinned to the 12/29/2021 code, and we updated yesterday to see if the problem was still present.  I also tested this on a completely different system using (your binaries) RELEASE.2021-10-27T16-29-42Z and it does not have this issue.

Also, my boss informed me that I should have ticketed this under our SUBNET account;  Is it possible to edit that, or would I have to kill this ticket and re-enter it on SUBNET?

**Comment by dcpontius** [comment]
Correction!  My test on a different system was using your binaries dated minio version RELEASE.2022-01-08T03-11-54Z, which would be more recent than the commit that I originally referenced, so it would suggest that the problem may lie in our build settings.  Are there any settings that would cause those metrics to be omitted?

**Comment by harshavardhana** [comment]
> Correction! My test on a different system was using your binaries dated minio version RELEASE.2022-01-08T03-11-54Z, which would be more recent than the commit that I originally referenced, so it would suggest that the problem may lie in our build settings. Are there any settings that would cause those metrics to be omitted?

Well building your own is not supported for any production deployment,  you shouldn't do that - you need to use our official releases.

> Also, my boss informed me that I should have ticketed this under our SUBNET account; Is it possible to edit that, or would I have to kill this ticket and re-enter it on SUBNET?

Please open it here https://subnet.min.io
