### ISSUE TITLE
There is no quota function support in all SDKs

### ISSUE THREAD

**Issue by gitYuZui** [minio/minio#14141]
**Is your feature request related to a problem? Please describe.**
The management side supports the quota function, but it seems that no method can be found in the SDK

**Additional context**
![image](https://user-images.githubusercontent.com/29330008/150365729-017b34dd-931a-48d5-9c54-a54e3431ade6.png)
![image](https://user-images.githubusercontent.com/29330008/150366349-a21c0022-c2f4-4b49-9aa0-f8d3818790d5.png)
![image](https://user-images.githubusercontent.com/29330008/150366406-15ce362e-f556-4b06-977c-a288cdbfe3ca.png)

**Comment by klauspost** [comment]
https://pkg.go.dev/github.com/minio/madmin-go#AdminClient.SetBucketQuota

https://pkg.go.dev/github.com/minio/madmin-go#AdminClient.GetBucketQuota
