### ISSUE TITLE
MinIO UI crashing when upgrading to 2022.1.8

### ISSUE THREAD

**Issue by alanlekah** [minio/minio#14151]
## Expected Behavior
On 2021.12.29, you'd expect to go to the bucket that you click on when you're a non-admin user.

## Current Behavior
We upgraded from minio 2021.12.29 to 2022.1.8. We're seeing with users that aren't the admin/root user that when they try accessing any bucket, that you'll hit a white screen and you'll see a console react error in the webpage.

The react error is as follows: 

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined
```

## Steps to Reproduce (for bugs)

We're using the following helm values in the latest helm bitnami/minio chart:

    --set global.storageClass="gp2" 
    --set persistence.size="80Gi" 
    --set mode="distributed"

With a read only user created using a custom IAM policy set like the following:

```
{ "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": [ "s3:Get*", "s3:List*" ], "Resource": [ "arn:aws:s3:::*" ] } ] }
```

## Context
Unable to upgrade to latest minio

## Your Environment
On EKS 1.19

**Comment by harshavardhana** [comment]
Yes fixed already in in minio/console - wait for the next release @alanlekah
