### ISSUE TITLE
Office example run failed about `sts assume-role`

### ISSUE THREAD

**Issue by ggdream** [minio/minio#14156]
[examples folder code](https://github.com/minio/minio/blob/master/docs/sts/assume-role.go)

Run it, i got:
![image](https://user-images.githubusercontent.com/60403489/150668701-5d58a9e1-17b7-4b44-be09-72095625f0a5.png)
How to solve this problem please? In addition, if you need to upload files, there will also be a token error problem. I'm guessing it's a permission issue, but I didn't find any relevant examples

**Comment by harshavardhana** [comment]
> How to solve this problem please? In addition, if you need to upload files, there will also be a token error problem. I'm guessing it's a permission issue, but I didn't find any relevant examples

There is no bucket called `minio` allowed - its a reserved `bucketname` - you can have any other bucket name - but not `minio`
