### ISSUE TITLE
minio retrive empty object after recreating cluster

### ISSUE THREAD

**Issue by RezaBabapour** [minio/minio#14165]
## NOTE
This issue is following discussion #14101
The problem is our `.minio.sys` is removed, and according to discussion #14101 I created a new empty cluster with same servers, disks and buckets. Then I used it's `.minio.sys` configuration in old minio cluster. The cluster started normally without any error but only some of objects can be download without problem(about 10% or less).
The problem is when I want to download some other objects minio retrieves empty object. The size of all objects are correct.  
I get `404 not found` in `mc admin trace target`

##  Expected Behavior
All objects can be download after indexing in finished

## Current Behavior
Only about 10% of objects recovered correctly.  
In 

## Possible Solution
Maybe I can write a code to merge objects and upload them somewhere else. But I can't read object metadata inside buckets. And I don't know how erasure code split data between servers and disks.

## Steps to Reproduce (for bugs)
1. Stop cluster ,Remove `.minio.sys`. 
2. Create new fresh cluster somewhere and move it's `.minio.sys` to old cluster.

## Your Environment
* Version used (`minio --version`): RELEASE.2022-01-08T03-11-54Z
* Server setup and configuration: no specific  configration
* Operating System and version (`uname -a`): docker container on top of debian buser

**Comment by klauspost** [comment]
@RezaBabapour As we noted in the previous issues, it was an attempt you made at your own risk, after you deleted all cluster disk/config information.

There is nothing we can do without a detailed look through all of your files and maybe custom code to reconstruct your data. We do not offer that as a community service.

Sorry, we cannot help you further.
