### ISSUE TITLE
error x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by CobbyJ** [minio/minio#14163]
Hello,

Im just wondering if anyone can help, been struggling for a few days to get a CA SSL to work but have had 0 luck, we have our own SSL.

we are using a distributed setup

we are getting this error "**error x509 certificate signed by unknown authority**"

I add it to **/home/minio-user/.minio/certs/CAs** along with my public.crt

Does the CA need to be names anything specific? and does anything need to be added to my public.crt?

It is a bundle CA is this correct?

No matter what i do im still getting a broken chain error when checking the ssl.

Any help would be amazing, i have been searching for days and tried all sorts of things.

**Comment by vadmeste** [comment]
> we are getting this error "error x509 certificate signed by unknown authority"

Where are you seeing this ?

**Comment by CobbyJ** [comment]
From a ssl checker and also when we use a mc client - works when we do --insecure but we want to it secure.

The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. You can fix this by following Sectigo's Certificate Installation Instructions for your server platform (use these instructions for InstantSSL). Pay attention to the parts about Intermediate certificates.

should we be using the CA bundle?

**Comment by vadmeste** [comment]
> should we be using the CA bundle?

yes

**Comment by CobbyJ** [comment]
What should it be names and file extension?

**Comment by harshavardhana** [comment]
> What should it be names and file extension?

It should be part of  public.crt

**Comment by CobbyJ** [comment]
still cant get it working. i have added my ca-bundle to to my public.crt and still the same.

Are you able to grab me on slack or direct emails so i can send you further details?

**Comment by ravindk89** [comment]
@CobbyJ that level of support requires [professional engagement](https://min.io/pricing). You can engage in the Discussions tab or ask in our [Community Slack](https://minio.slack.com)
