### ISSUE TITLE
ExecStart and AssertFileIsExecutable in systemd unit (RPM install) use incorrect path to binary

### ISSUE THREAD

**Issue by holgr** [minio/minio#14179]
## Expected Behavior
Updating using the minio RPM (currently `minio-20220125195604.0.0.x86_64.rpm`) ends with a successful restart afterwards.

## Current Behavior
Restarting the service via `systemctl` is not possible.

## Possible Solution
Fix the `minio.service` that comes with the RPM to point to the installed minio binary. `ExecStart` (and `AssertFileIsExecutable`) use the wrong path. Currently the systemd unit uses `/opt/bin/minio` but the RPM installs it in `/usr/local/bin/minio`.

## Steps to Reproduce (for bugs)
1. Install minio-20220125195604.0.0.x86_64.rpm
2. Try (re)starting the service `systemctl restart minio.service`

## Regression
The previously installed version was `minio-20220108031154.0.0-1.x86_64` which had a correct systemd unit as far as I can remember.

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-01-25T19-56-04Z`
* Server setup and configuration: `CentOS Stream 8`, minio server installation via RPM on `https://min.io/download#/linux`
* Operating System and version (`uname -a`): `Linux mss1 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Changed the minio.service - next release shall have it at `/usr/local/bin/minio`
