### ISSUE TITLE
Distributed instance degraded in case of 1 drive have issues

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#14174]
I have distributed minio installation consists of 3 nodes with 4 disks each. Parity set by default EC:4 in this case. When I disconnect up to 4 disks from any node all works fine - users can read and write file without performance issues. But today I got problem with one of the disks. It's performance decreased dramatically but disk still was available in system. When I logged in to this node I see system load 20.0+/ I ran atop and saw that access time to one of the drives are too much (more that 1000 ms.). Other drives works fine. But all my clients got and error with code "SlowDown" and can't download and upload files. I've remove this disk from the system and everything is fine again.

## Expected Behavior
Minio should understand that drive queue is too long and response time is too much and mark this disk as failed.

## Current Behavior
Minio instance with 12 disks stop working even if one disk becomes partially broken (ls on this disk show input/output error).

## Possible Solution
Don't know.

## Steps to Reproduce (for bugs)
1. Eject one disk.
2. Hit with the hammer.
3. Insert back.

## Context
Distributed minio installation stops working.

## Your Environment
* Version used (`minio --version`): 2021-12-10T23:03:39Z
* Server setup and configuration: 3 nodes with 4 drives each in distributed mode.
* Operating System and version (`uname -a`): Linux minio-2.bazis.net 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Unmount a partially failed drive:

> For nodes with one or more drives that are either partially failed or operating in a degraded state (increasing disk errors, SMART warnings, timeouts in MinIO logs, etc.), you can safely unmount the drive if the cluster has sufficient remaining healthy drives to maintain read and write quorum. **Missing drives are less disruptive to the deployment than drives that are reliably producing read and write errors.**

https://docs.min.io/minio/baremetal/installation/restore-minio.html
