### ISSUE TITLE
MinIO buckets are empty for IAM accounts

### ISSUE THREAD

**Issue by Crapshit** [minio/minio#14176]
## Expected Behavior

A IAM user with the following policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:ListBucket","s3:GetBucketLocation"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mycache"]
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mycache/*"]
    }
  ]
}
```
should be able to see the bucket contents in the console.

## Current Behavior

The user can see the bucket in the MinIO web console, but it is shown as empty.
The use can successfully upload files and/or create paths, but does not see them afterwards.
A user with consoleAdmin role / MINIO_ROOT_USER does see the content.
The IAM user with above policy can only see the content with the MinIO client on command line.

## Steps to Reproduce (for bugs)

1. Create an IAM policy named "mycache" with above content 
2. Create an IAM user named "mycache" assigned to "mycache" policy
3. Create bucket "mycache" as MinIO root user and create some path and upload a file
4. Login with IAM user and browse bucket -> no files are shown in the console
5. Upload some files and create some paths with IAM user.
6. Check bucket with root user again -> files are shown in the console
7. Check bucket with IAM user via MinIO client again -> files are shown on the command line
8. Via MinIO client you are also able to download/upload/delete files.

## Your Environment

* Version used (`minio --version`):
Multiple versions seems to be affected. Tested with below versions:
``
RELEASE.2021-12-09T06-19-41Z
``
``
RELEASE.2022-01-08T03-11-54Z
``
* Server setup and configuration:
Docker container setup:
``
server --address 0.0.0.0:9000 --console-address ":9001" https://minio{1...2}/export{1...4}"
``
* Operating System and version (`uname -a`):
``
Linux minio1 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 9 16:09:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
``

**Comment by klauspost** [comment]
You don't allow `s3:ListBucket` for prefixes. I suspect if you put it in the second section with `arn:aws:s3:::mycache/*` it will work.

**Comment by Crapshit** [comment]
@klauspost thank you very much.
Let me verify it tomorrow morning.

But it doesn't explain me why it was working before with the older version from 2020 I'm still using and why it is working with these mentioned versions 2021/2022 via MinIO client on command line.

**Comment by harshavardhana** [comment]
> But it doesn't explain me why it was working before with the older version from 2020 I'm still using and why it is working with these mentioned versions 2021/2022 via MinIO client on command line.

Console UI changed a few things - this is a Console UI-related issue and its already fixed.  We shall be making a new release.
