### ISSUE TITLE
Listing service account doesn't work with latest master

### ISSUE THREAD

**Issue by titansmc** [minio/minio#14173]
## Expected Behavior
List all the service account

## Current Behavior
empty

## Steps to Reproduce (for bugs)
1. OIDC configured minio
2. Create a svc acoount for an oidc user
3. with minio root credentials list them
4. empty shown

## Context
```
11:50 $ mc admin user svcacct list --help
NAME:
  mc admin user svcacct list - List services accounts

USAGE:
  mc admin user svcacct list ALIAS TARGET-ACCOUNT

TARGET-ACCOUNT:
  Could be a MinIO user, STS or LDAP account.
  
    1. List all service accounts for user 'foobar'.
     $ mc admin user svcacct list myminio/ foobar
```
mc command says that you can list svc accounts for any account (including STS), but when I create one as OIDC user, then I go to the CLI as minio root and try to list all the service account but it doesn't display any account.

## Regression
not sure

## Your Environment

* Version used (`minio --version`): minio version DEVELOPMENT.GOGET
* Server setup and configuration: minio operator running over CentOS 7
* Operating System and version (`uname -a`): `3.10.0-1160.45.1.el7.x86_64`

**Comment by harshavardhana** [comment]
> mc command says that you can list svc accounts for any account (including STS), but when I create one as OIDC user, then I go to the CLI as minio root and try to list all the service account but it doesn't display any account.

You cannot list via `root` account @titansmc - root won't list other service accounts.

**Comment by harshavardhana** [comment]
> > mc command says that you can list svc accounts for any account (including STS), but when I create one as OIDC user, then I go to the CLI as minio root and try to list all the service account but it doesn't display any account.
> 
> You cannot list via `root` account @titansmc - root won't list other service accounts.

This is behaving as expected - login to the UI and delete the relevant service accounts.  `mc` doesn't have the context here so it won't be able to list out the relevant service accounts when it's an OIDC user.

**Comment by titansmc** [comment]
but the `mc` command states 

```TARGET-ACCOUNT:
  Could be a MinIO user, STS or LDAP account.```
  
So do you mean this description is wrong? The usage is as following `mc admin user svcacct list ALIAS TARGET-ACCOUNT`
