### ISSUE TITLE
some file multipart can not move to /cache/sha256(bucket+objectkey) from /cache/sha256(bucket+objectkey)/uploadId/

### ISSUE THREAD

**Issue by yfanswer** [minio/minio#14183]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Possible Solution
cmd/disk-cache.go
![Uploading image.png…]()

## Steps to Reproduce (for bugs)
1. MINIO_CACHE="on"；
2. upload with FPutObject method；
3. Repeat the second step until the problem occurs；

## Context
golang version:1.17.5
minio gateway s3

**Comment by harshavardhana** [comment]
this doesn't make sense @yfanswer can you provide more details?

**Comment by harshavardhana** [comment]
To be fixed in #14181
