### ISSUE TITLE
Unable to initialize OpenID: 503 Service Unavailable

### ISSUE THREAD

**Issue by DougTrajano** [minio/minio#14194]
I'm trying to set up MinIO with Keycloak as the Identity Provider.

```log
API: SYSTEM()
Time: 02:33:17 UTC 01/27/2022
DeploymentID: e70ad74f-e74e-4084-8e00-89d0aa276fd1
Error: Unable to initialize OpenID: 503 Service Unavailable (*fmt.wrapError)
       2: cmd/config-current.go:463:cmd.lookupConfigs()
       1: cmd/gateway-main.go:237:cmd.StartGateway()
```

## Troubleshooting steps

- I ran a curl command to `https://<<KEYCLOAK-URL>>/auth/realms/master/.well-known/openid-configuration` and it returns the JSON with the openid-configuration.
- I figured out that the problem happens in a second request in the Identity Provider configuration process. It happens when calling `https://<<KEYCLOAK-URL>>/auth/realms/master/protocol/openid-connect/certs`.

## Context
- I'm using MinIO in a Kubernetes cluster with Istio Service Mesh

## Your Environment
* Version used (`minio --version`): `2021.5.27-debian-10-r8`

**Comment by harshavardhana** [comment]
> * I'm using MinIO in a Kubernetes cluster with Istio Service Mesh

Remove istio it's terrible and don't use it in MinIO production deployments.
