### ISSUE TITLE
MinIO speed test fail on the very first run

### ISSUE THREAD

**Issue by Crapshit** [minio/minio#14196]
## Expected Behavior

MinIO speedtest is running/working on the first/initial run.

## Current Behavior

MinIO speedtest will fail on the very first run with the following error:
```
Error: Bucket not found: .minio.sys/speedtest (cmd.BucketNotFound)
       4: cmd/peer-rest-server.go:1211:cmd.selfSpeedtest.func2.2()
       3: sync/once.go:68:sync.(*Once).doSlow()
       2: sync/once.go:59:sync.(*Once).Do()
       1: cmd/peer-rest-server.go:1209:cmd.selfSpeedtest.func2()
```
## Steps to Reproduce (for bugs)

1. Run MinIO with below version
2. After creating a MinIO cluster with this version run directly a speedtest

## Your Environment

* Version used (`minio --version`):
``quay.io/minio/minio:RELEASE.2022-01-27T03-53-02Z``
* Server setup and configuration:
Docker container setup:
``server --address 0.0.0.0:9000 --console-address ":9001" https://minio{1...2}/export{1...4}"``
* Operating System and version (`uname -a`):
``Linux minio1 3.10.0-1160.49.1.el7.x86_64 minio/minio#1 SMP Tue Nov 9 16:09:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux``

**Comment by vadmeste** [comment]
I am not able to reproduce. What about `mc admin info <alias>` ?

**Comment by harshavardhana** [comment]
> I am not able to reproduce. What about `mc admin info <alias>` ?

I think it's a fresh setup issue @vadmeste since it expects a bucket present.

**Comment by harshavardhana** [comment]
@Crapshit as a workaround create `mkdir -p /export{1..4}/.minio.sys/speedtest` on all the nodes.  Sending a fix right now.

**Comment by Crapshit** [comment]
@harshavardhana 
Thank you.
I can confirm that this is now working with version ``quay.io/minio/minio:RELEASE.2022-01-28T02-28-16Z``
