### ISSUE TITLE
Very slow healing process

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#14198]
## NOTE
I have 3 nodes with 4 disks each. 2 days ago I've lost two disks at one node. I've replaced it with new ones and healing process starts automatically. But it's really very slow. I see the network load and it show me only 10-15 Mbps while servers connected via gigabit interfaces. Disk usage at healthy drives is 1.1 TB. With this healing speed process will take approx. 6 days. It this normal behavior?

## Expected Behavior
Faster healing process.

## Current Behavior
Slow healing process.

## Steps to Reproduce (for bugs)
1. Replace one disk with new one.

## Your Environment

* Version used (`minio --version`): 2021-12-10T23:03:39Z
* Server setup and configuration: 3 nodes with 4 disks, 1 Gbps network
* Operating System and version (`uname -a`): Linux minio-2.bazis.net 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Yes, healing is not aggressive in terms of resources, otherwise it could easily cause disruptions to regular services.

6 days sounds reasonable. Bigger objects will heal faster.

**Comment by AlexZIX** [comment]
May it will be a good idea to add option like "transformation priority" in RAID controllers? Then user can choose between performance and fault tolerance. I use 16 TB disks. Healing of 1 TB takes 6 days. It means that all 16 TB will takes 96 days or 3 month. This period are reasonable too? I haven't seen in docs limits for disk size.
Also I have another minio setup on NVME drives which gives me 3 GB/s to random read and write and 1 Gbps network between  nodes. Minio also will heal data on 10 Mbps? Which parameter minio use for understanding which load are normal for healing process and doesn't slowdown all system?

**Comment by harshavardhana** [comment]
> 

@Alevsk `mc admin config set alias/ heal`  would show you the necessary options.

**Comment by Alevsk** [comment]
> > 
> 
> 
> 
> @Alevsk `mc admin config set alias/ heal`  would show you the necessary options. 

cc @AlexZIX

**Comment by AlexZIX** [comment]
@harshavardhana I've reviewed docs of mc admin and output of help but wasn't found any settings of healing performance.

**Comment by AlexZIX** [comment]
Thanks. Found it and set:

root@minio-1:~# mc admin config set minio-cold heal max_io=500 max_sleep=100ms

Will check tomorrow how many data was healed during today. 
It this settings applies to all nodes in my distributed setup or I should run this command on each node?

**Comment by harshavardhana** [comment]
> Thanks. Found it and set:
> 
> root@minio-1:~# mc admin config set minio-cold heal max_io=500 max_sleep=100ms
> 
> Will check tomorrow how many data was healed during today. It this settings applies to all nodes in my distributed setup or I should run this command on each node?

It's a central command everything applies cluster wide.

**Comment by AlexZIX** [comment]
@harshavardhana 

Hi, may be it will be interesting for you as real test. According to your advice I've set following minio settings:

mc admin config set minio-cold heal max_io=1500 max_sleep=1ms

After that the speed of healing really increased but minio still can't use total throughput of network and disk. I've replaced all 4 disks at one of my servers for testing and healing process started. Each normal of 8 remaning disks have 1.1 TB of data and this data starts healing to the new disks. After 10 days of this process I can see that real network load is 64 Mbps accoring nload and my firewall (https://imgur.com/a/CmnDbjH) and disks load approx. 15% according atop. So the full healing process of 4 disks filled with 1.1 TB of data takes approximately 2 weeks even with this tuning.

**Comment by klauspost** [comment]
@AlexZIX Healing is not meant to consume all resources. That would be way to disruptive to services.

What you are seeing is expected behavior.

**Comment by AlexZIX** [comment]
@klauspost I agree that healing process should have low priority but minio should have possibility to tune it.
As I described in topic I have 3 nodes with 4 disks each - total 12 disks. According docs default EC value for this installation equals 4 which means that I can lost up to 4 random disks. Suppose I'll lost one node and will replace it with 4 new disks. Healing will start and my system continue works as expected. But this process will be completed in few weeks or even months (I use 5 TB disks in my installation). And during this time I can't lost disks anymore or I'll lost all my information. This situation looks like situation with RAID5 when it lost one of disks. Load on remaining disks becomes higher and possibility to lost of of it becomes higher too during rebuilding of array. So there is only 3 solutions as I see:

1. Use 4 nodes instead of 3.
2. Use EC:6.
3. Use large count of small disks instead small count of large disks.
4. Tune my cluster to increase healing priority.

Of course 1 and 2 solutions is better but it's more expensive. In case of 3rd solution I'm not really sure that healing will be faster. In case of 4th I see that I have some unused resources (network throughput, disks IOPS) but can't tell minio to use it even if I really want to do that.

Also for now when I have real experience in minio I understand my mistake - I should really use large count of small disks (up to 1.2 TB) instead of small count of large disks (5 TB in my case). For now I have 1.1 TB used on each disks and 2 weeks for healing. When my disks will filled with 4 TB this process may never finish.
