### ISSUE TITLE
Single drive FS mode - Truncated Response without Continuation Token (RELEASE.2022-01-25T19-56-04Z)

### ISSUE THREAD

**Issue by mesobreira** [minio/minio#14190]
Hello,

Sorry to reopen this issue  #14132 , but it seems that the problem persists with the latest version.
This issue was closed because you said it was resolved by issue #14143 .
But I updated the minio yesterday and we still have the same problem.

I left attached the trace in verbose mode as you requested (check the line 170229) and the profile.

minio --version
mini version RELEASE.2022-01-25T19-56-04Z
[trace.minio-2.txt.zip](https://github.com/minio/minio/files/7944188/trace.minio-2.txt.zip)
[profile.zip](https://github.com/minio/minio/files/7944190/profile.zip)

**Comment by klauspost** [comment]
I honestly cannot see how this can happen with the current code.

Example, `X-Amz-Request-Id: 16CDDEB55761E83A`

**Comment by mesobreira** [comment]
@klauspost, do you need any additional info from me?? 
We can reproduce this situation easily.

**Comment by harshavardhana** [comment]
@mesobreira please share the code if you can.

**Comment by mesobreira** [comment]
Hello @harshavardhana  and @klauspost , 

Please find attached the script we made to reproduce the situation.
It's a simple Python script (using boto3). We can execute it in your environment.
It seems that the problem occurs when we have a concurrency between ListObjectV2 and Delete operations.
When we launch a single instance of the python script the problem does not happen.
But when we have 2 or more instances, we receive truncated reponse without continuation token.
 
[s3-scripts.zip](https://github.com/minio/minio/files/7971440/s3-scripts.zip)

**Comment by klauspost** [comment]
Ah, so when a queued response no longer exists.

Rather tricky situation. I will see if that can be solved without huge complications. Maybe just re-calling the function when that situation occurs could be done.

**Comment by klauspost** [comment]
@mesobreira I have a proposed fix in #14221, but I haven't been able to verify it yet.

**Comment by harshavardhana** [comment]
Would be able to test this? https://github.com/minio/minio/pull/14221 @mesobreira

**Comment by mesobreira** [comment]
Hello,

I tried to implement a loop to do successive retries.

 _while((response['KeyCount'] == 0) and (response['IsTruncated'] is True)):
          print(f"[Retry-ListAfterDelete]: Retry {retry} Truncated But KeyCount is 0")
          response=s3.list_objects_v2(Bucket=bucketName,Prefix=prefix,MaxKeys=maxKeys)
          retry = retry+1_

And I have observed that one retry is not enough in some cases.
There are cases where there are 9 tries of the same request:

_[Retry-ListAfterDelete]: Retry 1 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 2 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 3 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 4 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 5 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 6 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 7 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 8 Truncated But KeyCount is 0
[Retry-ListAfterDelete]: Retry 9 Truncated But KeyCount is 0_

So, the retry mechanism is a possible workaround, but it cannot be a permanent solution for 2 reasons:
- There is no guarantee of the success of the new attempt.
- Performance issues can happen due to increased latency.

Nevertheless, I also think that this retry mechanism should be implemented on the Minio side to minimize RTT latency.

What do you think ?

**Comment by klauspost** [comment]
> Nevertheless, I also think that this retry mechanism should be implemented on the Minio side to minimize RTT latency.

That is what is being done in the PR above.

If you can't build locally, here is a link to a linux/amd64 compile: https://download.klauspost.com/minio-retry-fs-listobjects.gz you can use for testing.

**Comment by mesobreira** [comment]
Thanks @klauspost .
I tested the version you provided, and it works fine. I have done several tests without any problems.
Good job !!
