### ISSUE TITLE
Uploaded object with Content-Encoding set is still compressed

### ISSUE THREAD

**Issue by jhwz** [minio/minio#14195]
When uploading an object via the minio-go SDK, I send a JSON file (which has no extensions) which is compressed with gzip with ContentType: "application/json" and ContentEncoding: "gzip"

When it gets uploaded to the server (with compression turned on) it still gets compressed. I may be misunderstanding, but shouldn't the content-encoding header indicate that the body is already compressed?

Looking at the [docs](https://docs.min.io/docs/minio-compression-guide.html) it says that only the content-type header is checked, why not the content-encoding?

I know I can set a suffix, or change the content-type header but if possible I'd rather keep it correct (because the content-type is still application/json?)

## Expected Behavior
Already compressed bodies aren't compressed again

## Current Behavior
Compresses objects even if content-encoding is set

## Possible Solution
Respect the content-encoding header

## Steps to Reproduce (for bugs)

1. Upload gzipped JSON file with no extension
2. Copy the file back down and it will be faulty

## Context
I keep a list of objects stored automatically under XIDs (UUIDs) which can have a variety of content-types. I always compress the files before sending them up and use the content-type header to correctly identify the type

## Your Environment
Here's the compression line from the server config
```
compression extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml allow_encryption=off 
```

**Comment by harshavardhana** [comment]
There is no content-encoding honored,  MinIO compression is server-side for all the blobs. If you want to ignore - you should ignore the content-type based not content-encoding.
