### ISSUE TITLE
Minio Web fails with react minification error when users are not having s3:PutObject 

### ISSUE THREAD

**Issue by roelsgaard** [minio/minio#14197]
I have a user with the following policy

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket/*"
            ]
        }
    ]
}
`
 
## Expected Behavior
The user should be able to view his buckets as well as browse the folders and items within.

## Current Behavior
When using minio web the user is allowed to view his buckets but when browsing the bucket a blank white screen is shown.
The Web console shows react minification issue causing the html to fail.

## Possible Solution
I have added all supported s3 actions to the allow list, which made the issue go away.
I then removed each policy one at a time to see which one was causing the issue.

Removing s3:PutObject causes the issue. 

I then tried adding only the s3:PutObject along with my existing actions and all is great - however the user should not be allowed to  put objects into the storage.

My thoughts is that there is simply som malformed react conditions around when to show the upload button causing the minifier to fail when the s3:PutObject is not present.

**Comment by klauspost** [comment]
@roelsgaard Are you running the latest version?

**Comment by roelsgaard** [comment]
@klauspost I'm running in docker on latest tag - redeploying approx once every week.
However the minio servere reports version 2022-01-08T03:11:54Z.

**Comment by klauspost** [comment]
@roelsgaard Probably this issue then: https://github.com/minio/console/issues/1461

Retest with latest. Feel free to open an issue if it still reproduces.
