### ISSUE TITLE
No data for minio minio_node_process_uptime_seconds in Grafana

### ISSUE THREAD

**Issue by BradleyDHobbs** [minio/minio#14219]
This is essentially the same as #12165 but with a different metric. 

## Expected Behavior
I would expect my minio server to expose all the available metrics. 

https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/minio-metrics-and-alerts.html#available-metrics

## Current Behavior
It looks like minio is not exposing all of the available metrics. 

I have tried both metric endpoints for minio:

- /minio/v2/metrics/cluster
- /minio/prometheus/metrics

## Steps to Reproduce (for bugs)

1. configure prometheus according to https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html and metrics_path: /minio/v2/metrics/cluster
2. configure garafana, and import dashbord by id 13502
3. dashbord panels N/A

## Your Environment

- Version used (minio --version): Version: 2021-12-09T06:19:41Z
- Server setup and configuration: prometheus auth using bearer token, others default config
- Minio Operating System: Windows Server 2019 Standard. Minio running as windows service
- Prometheus Operating System and version (uname -a): Linux linuxhubapp1 5.4.0-96-generic 109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

scrape_configs:

- job_name: minio-job
bearer_token: my bearer token
metrics_path: /minio/v2/metrics/cluster
scheme: http
static_configs:
  - targets: ['****"]

**Comment by harshavardhana** [comment]
@BradleyDHobbs how are you running the service?

**Comment by BradleyDHobbs** [comment]
It's using WinSW (https://github.com/winsw/winsw) as a wrapper with this config pointing to the minio.exe

    #Check script run as administrator
    if (!([Security.Principal.WindowsPrincipal] 
    [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start- 
    Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs; exit }

    Set-Location -Path $PSScriptRoot

    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri "https://github.com/winsw/winsw/releases/download/v2.8.0/WinSW.NET4.exe" -OutFile "minio- 
    service.exe"

    $config = @'
    <service>
    <id>MinIO</id>
    <name>MinIO</name>
    <description>MinIO is a high performance object storage server</description>
    <executable>minio.exe</executable>
    <env name="MINIO_ROOT_USER" value="minio"/>
    <env name="MINIO_ROOT_PASSWORD" value="minio"/>
    <arguments>server C:\minio\data --console-address ":9001"</arguments>
    <logmode>rotate</logmode>
    </service>
    '@

    Set-Content "minio-service.xml" $config

    Start-Process -WorkingDirectory $PSScriptRoot -FilePath "$($PSScriptRoot)\minio-service.exe" -ArgumentList "install" - 
    NoNewWindow -PassThru -Wait

    Write-Host "Installation done"

Then it runs as a Windows Service with the path pointing to minio-service.exe

**Comment by harshavardhana** [comment]
```
~ MINIO_PROMETHEUS_AUTH_TYPE=public minio server ~/test
```

```
~ curl -s https://localhost:9000/minio/v2/metrics/cluster | grep uptime
# HELP minio_node_process_uptime_seconds Uptime for MinIO process per node in seconds.
# TYPE minio_node_process_uptime_seconds gauge
minio_node_process_uptime_seconds{server="127.0.0.1:9000"} 21.270161937
```

Of course, single drive mode doesn't expose all metrics mentioned in the docs because single drive mode has no information to provide for those details. 

Our main Prometheus docs are geared towards a multi-drive, multi-node setup. 

It seems to be working fine for single drive setups.

**Comment by harshavardhana** [comment]
> * Version used (minio --version): Version: 2021-12-09T06:19:41Z

Please upgrade.
