### ISSUE TITLE
[Feature request] Add support for configurable S3 uploading limits

### ISSUE THREAD

**Issue by zeinali0** [minio/minio#14215]
Would it be possible to add support for configurable s3 gateway [limits](https://github.com/minio/minio/blob/b5d35c7e092f0518415f47cc86d8cf56171100a5/cmd/utils.go#L168)?
There are some situation we may gonna change these limits.
Like poor network connection we gonna let user upload in smaller part size (less than 5mb)
Or limit total object size

**Comment by harshavardhana** [comment]
Gateway is in code freeze, it is not taking any new features.

We also do not want to add non-S3 specific extensions here in this scenario.
