### ISSUE TITLE
SIGSEGV in github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:538

### ISSUE THREAD

**Issue by pradig** [minio/minio#14211]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

SIGSEGV in github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:538

## Expected Behavior

no crash

## Current Behavior

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c01fb]

goroutine 219 [running]:
github.com/minio/minio/cmd.getLocalDiskStorageMetrics.func1({0x51ea730, 0xc000635bc0})
	github.com/minio/minio/cmd/metrics-v2.go:1620 +0x23b
github.com/minio/minio/cmd.(*MetricsGroup).RegisterRead.func1.1()
	github.com/minio/minio/cmd/metrics-v2.go:227 +0x2b
github.com/minio/minio/cmd.(*timedValue).Get(0xc0009b15e0)
	github.com/minio/minio/cmd/utils.go:912 +0x32
github.com/minio/minio/cmd.(*MetricsGroup).Get(0x2de2a0c)
	github.com/minio/minio/cmd/metrics-v2.go:262 +0x3f
github.com/minio/minio/cmd.populateAndPublish({0xc000635d00, 0x7, 0x0}, 0xc00058ff10)
	github.com/minio/minio/cmd/metrics-v2.go:1804 +0x66
github.com/minio/minio/cmd.(*minioNodeCollector).Collect(0xc0000a7a20, 0xc001adfce0)
	github.com/minio/minio/cmd/metrics-v2.go:1817 +0xe6
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x102
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:538 +0xb4d

## Steps to Reproduce (for bugs)

1. start minio.RELEASE.2022-01-27T03-53-02Z or later 
2.
3.
4.

## Context

does not crash with minio.RELEASE.2022-01-25T19-56-04Z

## Your Environment

* Version used (`minio --version`): minio.RELEASE.2022-01-27T03-53-02Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux minio 5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Start script:
#!/bin/bash
export DATA_PATH=/var/lib/minio
export MINIO_ROOT_USER=abc
export MINIO_ROOT_PASSWORD=xyz
export MINIO_PROMETHEUS_URL="http://xxx.yyy.zzz:9090"
export CONSOLE_PROMETHEUS_JOB_ID="minio-cluster"
export MINIO_PROMETHEUS_AUTH_TYPE="public"
$HOME/bin/minio server --console-address :9001 --address :9000 $DATA_PATH

**Comment by harshavardhana** [comment]
> export DATA_PATH=/var/lib/minio
> export MINIO_ROOT_USER=abc
> export MINIO_ROOT_PASSWORD=xyz
> export MINIO_PROMETHEUS_URL="http://xxx.yyy.zzz:9090"
> export CONSOLE_PROMETHEUS_JOB_ID="minio-cluster"
> export MINIO_PROMETHEUS_AUTH_TYPE="public"
> $HOME/bin/minio server --console-address :9001 --address :9000 $DATA_PATH

This is a regression added from #14117

**Comment by harshavardhana** [comment]
> export CONSOLE_PROMETHEUS_JOB_ID="minio-cluster"

BTW this needs to be `MINIO_PROMETHEUS_JOB_ID=`  not `CONSOLE_`

**Comment by harshavardhana** [comment]
PR sent #14212 should fix this issue, however, @pradig you shouldn't be scraping `/node` metrics - those are mainly meant for very limited use cases - you should be ideally scraping `/cluster` instead.

**Comment by pradig** [comment]
Thanks, this is what I actually do:
https://xxx.yyy.zzz:9000/minio/v2/metrics/cluster

**Comment by pradig** [comment]
disregard my previous comment, my test system is still scraping /node
