### ISSUE TITLE
Lost users and IAM policies

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#14224]
I have distributed minio setup of 3 nodes with 4 drives on each. Yesterday I've replaced all 4 disks on 1 node. Healing process stared and I went sleep. Today I found that all my users and IAM polices not exists anymore - only users and policies which exists by default. At the same time all my bucket with data still exists. Also my admin account still exists. I can't understand how minio can lost all users with policies. 

## Expected Behavior
Users and IAM policies should not have disappeared when I replaced drives.

## Current Behavior
Users and IAM policies was disappeared when I replaced drives.

## Steps to Reproduce (for bugs)

1. Setup minio cluster with 3 nodes and 4 drives on each.
2. Create IAM policy and user.
3. Remove all 4 drives on one node and replace it with new ones.

## Context
All services which uses my S3 stopped working.

## Your Environment
* Version used (`minio --version`): 2021-12-10T23:03:39Z
* Server setup and configuration: 3 nodes with 4 drives on each
* Operating System and version (`uname -a`): Linux minio-1 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> I have distributed minio setup of 3 nodes with 4 drives on each. Yesterday I've replaced all 4 disks on 1 node. Healing process stared and I went sleep. Today I found that all my users and IAM polices not exists anymore - only users and policies which exists by default. At the same time all my bucket with data still exists. Also my admin account still exists. I can't understand how minio can lost all users with policies.

Yes, this was a bug that was fixed in later releases already. @AlexZIX 

```
commit b7c5e45fff935994791f89237a4891185c55b91f (tag: RELEASE.2022-01-08T03-11-54Z)
Author: Harshavardhana <harsha@minio.io>
Date:   Fri Jan 7 19:11:54 2022 -0800

    heal: isObjectDangling should return false when it cannot decide (#14053)
    
    In a multi-pool setup when disks are coming up, or in a single pool
    setup let's say with 100's of erasure sets with a slow network.
    
    It's possible when healing is attempted on `.minio.sys/config`
    folder, it can lead to healing unexpectedly deleting some policy
    files as dangling due to a mistake in understanding when `isObjectDangling`
    is considered to be 'true'.
    
    This issue happened in commit 30135eed86f470407123775f3c11ecd3e991337b
    when we assumed the validMeta with empty ErasureInfo is considered
    to be fully dangling. This implementation issue gets exposed when
    the server is starting up.
    
    This is most easily seen with multiple-pool setups because of the
    disconnected fashion pools that come up. The decision to purge the
    object as dangling is taken incorrectly prior to the correct state
    being achieved on each pool, when the corresponding drive let's say
    returns 'errDiskNotFound', a 'delete' is triggered. At this point,
    the 'drive' comes online because this is part of the startup sequence
    as drives can come online lazily.
    
    This kind of situation exists because we allow (totalDisks/2) number
    of drives to be online when the server is being restarted.
    
    Implementation made an incorrect assumption here leading to policies
    getting deleted.
    
    Added tests to capture the implementation requirements.
```
