### ISSUE TITLE
Change hostname in presigned-url

### ISSUE THREAD

**Issue by lromor** [minio/minio#14241]
**Is your feature request related to a problem? Please describe.**
Oftentimes different services are interacting with a minio service accessible via different names or ips. An example is:
1. We generate an presigned *url* from an internal service with some name minio-name1.
2. The *url* is given to a client which can only access the same minio server at minio-name2.

This creates a host mismatch when the server validates the signature as the requesting host is minio-name2 but the signature was made via minio-name1.

**Describe the solution you'd like**
Allow to customize the host during the signing process.

**Describe alternatives you've considered**
create name aliases so that the same host can be used in the internal service, manually sign, or create a new client instance or session and compute the presigned-url with that.

**Comment by vadmeste** [comment]
@lromor generating presigned URLs is an offline process. Any hostname can be provided to the SDK that is generating the presigned URL.

**Comment by lromor** [comment]
Thank you for your answer @vadmeste.

I think I understand that, but in my application I'm using a single minio client instance configured to interact with an internal address minio-name1. Instantiating a minio client it's not an offline process (although the presigned-url generation is). My problem is very similar to #10222. So I can instantiate the minio client only if I can connect to minio-name1, but at that point I can only generate presigned urls for the host minio-name1 and this is very limiting.

**Comment by klauspost** [comment]
> Instantiating a minio client it's not an offline process

I am pretty sure it is. Either way, it is a client-side issue and not a server-side. If there is a problem with a specific client feel free to open an issue there, with code examples.

**Comment by lromor** [comment]
Thank you @klauspost , it indeed makes more sense to open an issue there.
