### ISSUE TITLE
boto3 `upload_part_copy` allows empty string in `CopySourceRange` param

### ISSUE THREAD

**Issue by jjnesbitt** [minio/minio#14246]
When using the boto3 client against a minio instance (as documented [here](https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html)), and trying to perform an object part copy (relevant boto3 [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.upload_part_copy)), the `CopySourceRange` accepts the empty string as valid and equal to not including the header at all. However, against production S3, including the empty string here raises the following error:

```
ClientError('An error occurred (InvalidArgument) when calling the UploadPartCopy operation: The
x-amz-copy-source-range value must be of the form bytes=first-last where first and last are the
zero-based offsets of the first and last bytes to copy')
```

## Expected Behavior
This error is also raised in minio.

## Current Behavior
This error is not raised, and no byte range is used.

## Steps to Reproduce
```python
client = boto3.client(
    's3',
    endpoint_url='http://localhost:9000',
    aws_access_key_id='minioAccessKey',
    aws_secret_access_key='minioSecretKey',
    region_name='us-east-1',
)

upload_id = client.create_multipart_upload(Bucket=dest_bucket,Key=dest_key)['UploadId']
client.upload_part_copy(
    Bucket=dest_bucket,
    Key=dest_key,
    UploadId=upload_id,
    CopySource=f'{source_bucket}/{source_key}',
    CopySourceRange='',
    PartNumber='1',
)
```

**Comment by harshavardhana** [comment]
If you send empty we just treat is fully Copy @AlmightyYakob

**Comment by harshavardhana** [comment]
We could return an error.

**Comment by jjnesbitt** [comment]
> If you send empty we just treat is fully Copy @AlmightyYakob

Yes, which is contrary to what S3 actually does. This led to me writing code that passes an empty string if full copy is desired, which succeeded locally against minio, but failed against prod S3.

> We could return an error.

I think this is a good idea :+1:
