### ISSUE TITLE
Minio gateway tries to connect minio server each time request made

### ISSUE THREAD

**Issue by egasimov** [minio/minio#14244]
Hi everyone,
I have encountered with some difficulties during setting up minio gateway mode and want to get your thoughts.

Goal:  Configuration of Minio-S3 Gateway with Minio-S3(standalone mode) so that when a client sends request for a object, then provide it from its cache. rather than ask from Minio-S3

Motivation: sometimes, there should be network connection issues between gateway and server. in that case getting an object is not possible.

Questions:
1.When minio-gateway is started, it will immediately try to connect Minio-S3 server && testing a scenario - 'getting randomly generated named object from Minio-S3'
 
Q: is there anyway to change that behaviour ?

2.When client sends request for a object to download, minio-gateway asks first Minio-S3 to be sure that object with given name exists rather than checking first from its cache to respond to request.

When an object exists in cache and server is unreachable for some reasons, Client wants to get an object, namely 'example.txt'. 
The following output shown cuz in minio-gateway is unable to connect minio-server
<ERROR> Unable to validate source 

Let`s make scenario from scratch.
```
$ .\mc.exe alias set gw-s3 http://localhost:9000 m-gw-client-user m-gw-client-pwd
$ .\mc.exe cp gw-s3/mybucket/example.txt .
...example.txt:  5.45 KiB / 5.45 KiB [=========================================================================================] 435.43 KiB/s 0s
```
P.S: it is cached after first get request for object configured through env variable: MINIO_CACHE_AFTER.
 And let's stop the Minio-Server, and ask for the same object again.
```
$ .\mc.exe cp gw-s3/mybucket/example.txt .

 .\mc.exe: <ERROR> Unable to validate source gw-s3/mybucket/example.txt.
```
Q: is there anyway to disable that behaviour so that when object existing in the cache, no need to ask/connect to Minio-Server ?

**Comment by klauspost** [comment]
This is by design.

Upstream is the source-of-truth. So a cached version must check upstream before it knows if the cached version is valid.
