### ISSUE TITLE
MinIO S3 Gateway: InvalidAccessKeyId and Prefix Denied

### ISSUE THREAD

**Issue by DougTrajano** [minio/minio#14252]
## Expected behavior

I would like to have MinIO Gateway with multiple replicas.

## Current Behavior

We are using MinIO as a gateway for Amazon S3. We also use Keycloak and MinIO STS to generate temporary credentials.

When we got temporary AK/SK and try to connect with MinIO using boto3 it raises an `InvalidAccessKeyId`.

We can see the following error in one of the MinIO replicates:

```
API: SYSTEM()
Time: 02:33:30 UTC 01/13/2022
DeploymentID: f7bffa46-9073-45ec-b99d-c2149e21ddfa
Error: Prefix access is denied: jarvis-bucket/ (cmd.PrefixAccessDenied)
       5: cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
       4: cmd/auth-handler.go:343:cmd.checkRequestAuthTypeCredential()
       3: cmd/auth-handler.go:275:cmd.checkRequestAuthType()
       2: cmd/bucket-handlers.go:1183:cmd.objectAPIHandlers.HeadBucketHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

We realized that the problem only happens when we are using more than one replica in our MinIO deployment.

## Context

- Kubernetes version: 1.21
- MinIO version: 2021.5.27-debian-10-r8

**Comment by vadmeste** [comment]
@DougTrajano did you configure the gateway with etcd ?

**Comment by harshavardhana** [comment]
> MinIO version: 2021.5.27-debian-10-r8

Please upgrade.

**Comment by harshavardhana** [comment]
> * MinIO version: 2021.5.27-debian-10-r8

Please upgrade and let us know issue persists.
