### ISSUE TITLE
Support float IP for Minio cluster

### ISSUE THREAD

**Issue by DanielQujun** [minio/minio#14267]
Dear minio team:
  I encountered a problem when I tried to start a distributed Minio cluster in our customer's environment, when starting the 3 Minio instances with 2 drivers on 3 VM, The minio keep scrolling logs as below:

```
Unable to read 'format.json' from http://minio-0.minio-svc.minio.svc.cluster.local:39000/export-0: http: Server closed

Unable to read 'format.json' from http://minio-1.minio-svc.minio.svc.cluster.local:39000/export-0: Not allowed (POST /minio/storage/export-0/v24/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Unable to read 'format.json' from http://minio-2.minio-svc.minio.svc.cluster.local:39000/export-0: Not allowed (POST /minio/storage/export-0/v24/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Unable to read 'format.json' from http://minio-0.minio-svc.minio.svc.cluster.local:39000/export-1: http: Server closed

Unable to read 'format.json' from http://minio-1.minio-svc.minio.svc.cluster.local:39000/export-1: Not allowed (POST /minio/storage/export-1/v24/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Unable to read 'format.json' from http://minio-2.minio-svc.minio.svc.cluster.local:39000/export-1: Not allowed (POST /minio/storage/export-1/v24/readall?disk-id=&file-path=format.json&volume=.minio.sys on S3 API)

Waiting for a minimum of 3 disks to come online (elapsed 10s)
```
FYI: minIO version is  RELEASE.2021-01-08T21-18-21Z

This is weird for me since I deployed this helm chart many times before and it's always stable and quick to get started. and I found 
 the issue by searching the logs, https://github.com/minio/minio/issues/11176, But it's not the same case.
 
After a long time of testing, I realized that this might be these "minio-{0...2}|.minio-svc.minio.svc.cluster.local" resolved to the float IPs that did not exist on the VMs(these minIO instances run as host network pods), after I change these DNS records to the real VM's IPs, the Cluster started at all of sudden.

I  tried the latest version, can't start either. but with different logs:
```
Unable to read 'format.json' from http://minio-2.minio-svc.minio.svc.cluster.local:39000/export-1: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment
```

I looked through the code, found that this error comes from `methodNotAllowedHandler`,https://github.com/minio/minio/blob/2ee337ead5784d60971973b5399c20ebd9fdce44/cmd/handler-utils.go#L432
```
func methodNotAllowedHandler(api string) func(w http.ResponseWriter, r *http.Request) {
	return errorResponseHandler
}

// If none of the http routes match respond with appropriate errors
func errorResponseHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	}
	desc := "Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment"
```
Since not familiar with minio, I can't figure out why the code goes here. tried to set some debug point on IDE, still failed to locate the reason.. :face_exhaling:

**How to reproduce **
1. write DNS records to 3 hosts, such as:
```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.1.14 minio-0.minio-svc.minio.svc.cluster.local
192.168.1.15 minio-1.minio-svc.minio.svc.cluster.local
192.168.1.16 minio-2.minio-svc.minio.svc.cluster.local
```
2. run the command below on 3 hosts
```
docker run -it --rm  -v /tmp/minio-hosts:/etc/hosts -p 39000:39000 -e MINIO_ROOT_PASSWORD=minio123456 -e MINIO_ROOT_USER=minio --entrypoint bash  hub.tiduyun.com:5000/system/minio:latest
```
3. start minio
```
	minio server http://minio-{0...2}.minio-svc.minio.svc.cluster.local/export-{0...1} --address :39000
```

Hope we can support the scenario, even though the MinIO cluster runs behind float IP is rare. there are also some clusters that support it, like ES publish IP, ETCD advertise.

**Comment by harshavardhana** [comment]
No we cannot support this @DanielQujun we need to know the IP that belongs to the server where the disks exist to make sure we can register local disks.

So without that it's not possible to setup MinIO in it's current form.

**Comment by DanielQujun** [comment]
@harshavardhana, thanks for your explanation, will we support this in the future? I think there might have been some cases that minIO runs behind a proxy, for instance our customers deploy minIO on the VMS which provides by different Cloud Platform, so they need float IPs to communicate with each other.
In my naive thoughts, maybe we can add a advertise IP parameter for MinIO instance? but not sure it is doable~

**Comment by harshavardhana** [comment]
> @harshavardhana, thanks for your explanation, will we support this in the future? I think there might have been some cases that minIO runs behind a proxy, for instance our customers deploy minIO on the VMS which provides by different Cloud Platform, so they need float IPs to communicate with each other.

No we will not @DanielQujun

**Comment by DanielQujun** [comment]
@harshavardhana Hi, How about logging this error more verbosely? cause it really takes me a long time to figure out because I did not know minIO can't start If they don't know each other's real IPs. though It may be documented somewhere I did not notice.

Do you think that is worthing to do? I'm willing to finish this task.  It would be very helpful if you would like to point some directions,  I have looked through the mux library, but still have no idea why we get that error.

In fact, I wish I could know and contribute minIO more, cause we're using minIO as the backend of Loki at a big scale, there might be thousands of hosts and APPs that need to store logs into minIO.

**Comment by harshavardhana** [comment]
> @harshavardhana Hi, How about logging this error more verbosely? cause it really takes me a long time to figure out because I did not know minIO can't start If they don't know each other's real IPs. though It may be documented somewhere I did not notice.
> 
> Do you think that is worthing to do? I'm willing to finish this task. It would be very helpful if you would like to point some directions, I have looked through the mux library, but still have no idea why we get that error.
> 
> In fact, I wish I could know and contribute minIO more, cause we're using minIO as the backend of Loki at a big scale, there might be thousands of hosts and APPs that need to store logs into minIO.

That is because we do not know which IP belongs to which node to register local drives as handlers for performing remote calls.

These are precisely the problem we can't support such floating IPs support right now, unless there is a way to indicate that locality of such IPs.

It is not easy to allow without complicating the deployment model.

MinIO wants to keep it's deployment simple and predictable.

Comparing this with etcd is not correct they can't scale beyond 7 nodes at max. Most deployments we have seen are hardly 3 nodes maximum.

MinIO is being deployed at 10x that scale, we cannot honestly complicate our code and use a chatty discovery protocol. There are really no potential upsides here for us.

**Comment by DanielQujun** [comment]
Got it! Thanks for your patience and thorough explanation.
