### ISSUE TITLE
Minio helm chart does not allow use of workload identity in GKE

### ISSUE THREAD

**Issue by brokenjacobs** [minio/minio#14264]
**Is your feature request related to a problem? Please describe.**
Using the minio helm chart in gateway mode with GCS requires a service account jsonkeyfile to be created, instead of allowing the library to use application default credentials (ADC) via the clusters' workload identity support. I'm not certain if this support is in minio or not, but it likely should be for users deploying at GCP.

**Describe the solution you'd like**
I'd like to be able to NOT specify a json keyfile or project, but instead allow the GCP libraries for object storage to leverage application default credentials and GKE workload identity.

**Describe alternatives you've considered**
Creating a keyfile and loading it as a secret into my cluster is an alternative. But key rotation becomes a major pain.

**Comment by harshavardhana** [comment]
Feel free to make these changes @brokenjacobs - happy to accept a PR.

**Comment by brokenjacobs** [comment]
Totally down for that, but I don't know if Minio itself has support for ADC? There is a link to it in the docs but no explanation on how to accomplish it?

Put another way, if I can figure out how to manually adjust a deployment to have acceptable values that will work, I'd be happy to put the changes into helm to support it.

**Comment by harshavardhana** [comment]
> Totally down for that, but I don't know if Minio itself has support for ADC? There is a link to it in the docs but no explanation on how to accomplish it?
> 
> Put another way, if I can figure out how to manually adjust a deployment to have acceptable values that will work, I'd be happy to put the changes into helm to support it.

Currently, GCS gateway is in code-freeze and not taking anymore features @brokenjacobs so you need to get the workload identity file and mount it on the pod and let the path be specified to look at this file to be used.

Native support for GCS gateway is currently beyond the scope.

**Comment by harshavardhana** [comment]
If this can be done cleanly we are willing to accept a PR that doesn't use credentials.json file.

**Comment by harshavardhana** [comment]
Actually this is not going to be needed anymore since we are going to remove the gateway in June this feature implementation will be invalid anyways. 

Refer #14331
