### ISSUE TITLE
Cannot delete compressed files

### ISSUE THREAD

**Issue by eddbbt** [minio/minio#14279]
Minio request timeout when trying to delete a compressed file
Unfortunately, that's not a consistent behavior.

## Expected Behavior
Zip and tar.gz files should be deleted from bucket

## Current Behavior
Randomly the delete calls for compressed files such as zip and tar.gz files return a timeout, sometimes it works.
No further logs are returned from minio and/or from the console monitoring features or the go client, just a generic error ( with 500 status code from web console)

## Possible Solution
no idea

## Steps to Reproduce (for bugs)

- start minio server
- upload compressed files alongside with standard files, or standalone
- delete some files, even the compressed files
- try to reupload the same files once again and then delete them
- now it should timeout
- if not, repeat upload then delete
- bucket should be empty, but that's not required

yes, I've followed https://github.com/minio/minio/tree/release/docs/debugging
api calls from mc stacktrace verbose
![immagine](https://user-images.githubusercontent.com/76206659/153214815-c0b37e04-4c21-45e4-abe4-d2b8a73d41bc.png)

subnet health cannot be retrieved (maybe beacuse its a single node cluser?)
![immagine](https://user-images.githubusercontent.com/76206659/153215141-79c33522-8931-408b-be7e-e2c02f16cd23.png)

## Context
Same event occur with both minio golang library and minio browser console, in different pc's

## Regression
No

## Your Environment
tested with three pc's both with different environments:
first one: 
Linux Mint 20.1 Cinnamon
kernel 5.4.0-97-generic
minio server  RELEASE.2022-02-07T08-17-33Z 

second one:
PopOS! 21.10
kernel 5.4.0-97-generic
minio server  RELEASE.2022-02-07T08-17-33Z 

third one: 
- Ubuntu 20.04.1 LTS
- minio version RELEASE.2021-06-09T18-51-39Z

screenshots
![immagine](https://user-images.githubusercontent.com/76206659/153193201-2ac5a0f6-4839-4470-b299-abdd66b4170c.png)

![immagine](https://user-images.githubusercontent.com/76206659/153193239-ea59ef60-4087-4a97-815c-e0e140be2021.png)

**Comment by klauspost** [comment]
So this is in single-drive setup? 

What filesystem are you storing data on?

**Comment by eddbbt** [comment]
@klauspost yes it is single drive

filesystem is ext4 in all of the workstation, at least one of them (mine) has journaling enabled, if that makes any difference

**Comment by klauspost** [comment]
@nkn134 The server filesystem. This looks like the underlying server filesystem has issues.

Are the archives significantly bigger than the other files that work?

**Comment by klauspost** [comment]
Testing doesn't reproduce:
![image](https://user-images.githubusercontent.com/5663952/153228865-aa24e2ce-83e3-4404-957b-296ab342c464.png)

I suspect your FS is blocking, maybe writing back cached data or something like it.

**Comment by harshavardhana** [comment]
Closing this as it doesn't look like a MinIO issue as such.
