### ISSUE TITLE
mc ilm restore fails and minio deletes data on AWS S3 remote tier

### ISSUE THREAD

**Issue by tomaz-beltram** [minio/minio#14278]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Object data is restored to local minio server.

## Current Behavior

Restore command fails. Checking contents of remote tier bucket before and after failed retrieve shows that data was deleted after some time.

  mc: <ERROR> Unable to send restore request. 200 OK
   (1) ilm-restore.go:248 cmd.showRestoreStatus(..)
   (0) client-s3.go:2719 cmd.(*S3Client).Restore(..)
   Release-Tag:RELEASE.2022-02-07T09-25-34Z | Commit:dabc6c598e5e | Host:build-vm | OS:linux | Arch:amd64 | Lang:go1.17.6 |   Mem:2.7 MB/16 MB | Heap:2.7 MB/7.8 MB
  mc: <ERROR> Unable to check for restore status unexpected restore header
    (1) ilm-restore.go:271 cmd.showRestoreStatus(..)
   (0) client-s3.go:1588 cmd.(*S3Client).getObjectStat(..)
   Release-Tag:RELEASE.2022-02-07T09-25-34Z | Commit:dabc6c598e5e | Host:build-vm | OS:linux | Arch:amd64 | Lang:go1.17.6 | Mem:2.8 MB/16 MB | Heap:2.8 MB/7.8 MB

## Steps to Reproduce (for bugs)

1. create AWS S3 bucket:
  mc mb s3/remote-tier
2. create local minio bucket:
  mc mb first/test
3. configure remote tier and ilm:
  mc admin tier add s3 first AWS --access-key * --secret-key * --bucket remote-tier --prefix minio/ --storage-class "STANDARD" --endpoint http://s3.amazonaws.com
  mc ilm add --transition-days 0 --storage-class AWS first/test
4. store object and run ilm restore
  mc cp README first/test
  mc ilm restore first/test/README 

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2022-02-01T18-00-14Z
mc version RELEASE.2022-02-07T09-25-34Z

* Server setup and configuration:
./minio server --address :9001 /srv/minio/first{1...4}

* Operating System and version (`uname -a`):
Linux build-vm 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andriytk** [comment]
Reproduced the issue:

```
$ mc ls local/tb2
[2022-02-16 11:31:21 GMT]  19KiB STANDARD README.md
$ mc ilm restore local/tb2/README.md
Sent restore requests to 1 object(s)...
mc: <ERROR> Unable to check for restore status unexpected restore header
0/1 object(s) successfully restored..
$ mc ls local/tb2
$ mc admin tier 
```

The object disappeared from the local bucket after the failed restoration.

Shouldn't it check whether the object already exists and, if so, don't restore anything?

**Comment by vadmeste** [comment]
This issue is actually fixed, but you need latest MinIO server and latest mc.

**Comment by vadmeste** [comment]
> The object disappeared from the local bucket after the failed restoration.

Interesting. I wil check that.

**Comment by andriytk** [comment]
> This issue is actually fixed, but you need latest MinIO server and latest mc.

@vadmeste, could you please point out in which PR it was fixed? I'm using minio server commit 362e14fa1 (v3.5.2) and the latest mc (from today's master). Thank you.

**Comment by andriytk** [comment]
> > The object disappeared from the local bucket after the failed restoration.
> 
> Interesting. I wil check that.

Actually, the restored object eventually appeared in the local bucket after a few minutes (like 4 or 5 mins) since the 1st restore command was made, and it does not disappear on the restore command after this any more:

```
$ mc ilm restore local/tb2/README.md
Sent restore requests to 1 object(s)...
mc: <ERROR> Unable to check for restore status unexpected restore header
0/1 object(s) successfully restored..
$ mc ls local/tb2
[2022-02-16 12:07:19 GMT]  19KiB STANDARD README.md
```

Should it really take so long to restore after the 1st `mc ilm restore` command?

Also, why `mc` complains with the error and shows that `0/1 object(s) successfully restored` - what does it mean? Is this expected?

**Comment by tomaz-beltram** [comment]
I can confirm that with latest mc and minio versions ilm restore works for my use case as expected.
mc version RELEASE.2022-02-16T05-54-01Z
minio version RELEASE.2022-02-16T00-35-27Z

```
$ ./mc ilm restore first/test/README
Sent restore requests to 1 object(s)...
1/1 object(s) successfully restored.
```

**Comment by andriytk** [comment]
That's cool! I still wonder in which PR it was fixed...

**Comment by andriytk** [comment]
I've updated my minio server to the latest version (from today) and indeed - there is no error from the restore command any more. But the object is still not listing:

```
$ mc ilm restore local/tb2/README.md
Sent restore requests to 1 object(s)...
1/1 object(s) successfully restored..
$ mc ls local/tb2
$ 
```

UPD: OK, the object appeared in the bucket eventually after 5 mins! It's still not clear to me - why it takes so long. Running the restore command again does not make the object disappear. Looks like it disappears after the 1st restore command since the object is put/updated locally.

**Comment by vadmeste** [comment]
> UPD: OK, the object appeared in the bucket eventually after 5 mins! It's still not clear to me - why it takes so long. Running the restore command again does not make the object disappear. Looks like it disappears after the 1st restore command since the object is put/updated locally.

It would be great if you open a new ticket with steps to reproduce this.
