### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Sam-Sundar** [minio/minio#14274]
We are using MinIO inside our Kubernetes cluster and are using a SSL certificate and we loaded the same inside minio pod as mentioned in this [link](https://github.com/minio/minio/tree/master/docs/tls/kubernetes)

When we try to access Minio, we are getting this error. Also when we GET an object from our code, Minio is throwing below error like `Error: unable to verify the first certificate.` even though the certificate is valid and from a proper CA.
When we use self-signed, this is the error.
```
Error: self signed certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
at TLSSocket.emit (events.js:198:13)
at TLSSocket.EventEmitter.emit (domain.js:448:20)
at TLSSocket._finishInit (_tls_wrap.js:633:8)
code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
```
How to resolve this ?
Environment details:
`Kubernetes deployment with minio/minio:RELEASE.2021-06-17T00-10-46Z image`

![image](https://user-images.githubusercontent.com/83000807/153134891-7576e5dc-6426-49da-8f88-95836ea1be36.png)
![image](https://user-images.githubusercontent.com/83000807/153135077-373b6dd7-e67d-45f6-b7ff-0a08b9669b96.png)

**Comment by harshavardhana** [comment]
Please upgrade to latest release first

you are showing some JavaScript exception here - did you trust the certs on the client node?

**Comment by Sam-Sundar** [comment]
Hey @harshavardhana,

We are not checking cert. at client side by setting this env
NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by harshavardhana** [comment]
> Hey @harshavardhana,
> 
> We are not checking cert. at client side by setting this env
> NODE_TLS_REJECT_UNAUTHORIZED=0

I don't think your client is honoring that. You need to check your client behavior here.

This is nothing to do with MinIO server.
