### ISSUE TITLE
can't login with temporary credentials got with AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by jpchev** [minio/minio#14282]
I managed to plug my min.io cluster to an Identity Provider (Keycloack) via openid connect.
I can login to the min.io embedded UI via the Keycloack, now I'm trying to login via the temporary credentials which I can successfully get using the AssumeRoleWithWebIdentity API:

this call

`curl -v -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "Action=AssumeRoleWithWebIdentity&WebIdentityToken=<TOKEN>&Version=2011-06-15&DurationSeconds=86000" http://minio-0:9000/`

returns the temporary credentials, but then
when I use these credentials to connect via the mc client, I get an error, saying that the security token is invalid, am I missing something?

`mc alias set minio-https http://localhost:9000 <key> <secret> --api S3v4`
Added `minio-https` successfully.

`mc ls minio-https`
mc: <ERROR> Unable to list folder. The security token included in the request is invalid

How can I pass the security token?
Thanks

**Comment by harshavardhana** [comment]
That's not how you use them - yo uare missing session_token - temporary credentials shouldn't be persisted - use it the way its documented here https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#specify-temporary-host-configuration-through-environment-variable

**Comment by jpchev** [comment]
thanks but how to pass the session token in a Javascript function as the following?
Should it be encoded in the endpoint along withe the key id and the secret?

```
const client = new Minio.Client({
                    endPoint: 'minio-0',
                    port: 9000,
                    useSSL: false
                })
```

**Comment by harshavardhana** [comment]
Did you not read https://github.com/minio/minio-js/blob/master/docs/API.md#1--constructor @jpchev ?

**Comment by jpchev** [comment]
no, ok, I got it experimenting
