### ISSUE TITLE
mc add mysql notify got "Error 1071: Specified key was too long; max key length is 3072 bytes"

### ISSUE THREAD

**Issue by yuuri** [minio/minio#14284]
when i run mc command 

`mc admin config set yuuri notify_mysql:myinstance table="minio_images"  dsn_string='user:password@tcp(host:3306)/miniodb'`

## Expected behavior

> Successfully applied new settings.
> Please restart your server 'mc admin service restart yuuri.

## Actual behavior

> mc: <ERROR> Unable to set 'notify_mysql:myinstance table=minio_images dsn_string=user:password@tcp(host:3306)/miniodb' to server. Error 1071: Specified key was too long; max key length is 3072 bytes.

## Regression

Yes

(https://github.com/minio/minio/pull/13414) and (https://github.com/minio/minio/pull/13974) .

It seem not complete reslove problem , becuase utf8mb4 can store up to four bytes per character.

## Your Environment

* Version used (`minio --version`):

> minio version RELEASE.2022-01-08T03-11-54Z

* Operating System and version (`uname -a`):

  > Linux yuuriso 4.15.0-96-generic 97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bpedersen2** [comment]
This error regularly pops up with newer mysql version ( as utf8mb4 is now the default): You cannot create an index/ primary key on a column that is too wide. The key length is limited to the mentioned 3072 bytes, so in utf8mb4 that means a column with max. 3072/4 = 768 chars. One possible solution is to use a 2-byte utf8 encoding.

See https://forums.mysql.com/read.php?25,666766,666838#msg-666838

**Comment by xutao123777** [comment]
minioadmin:minioadmin@tcp(127.0.0.1:3306)/blog?charset=ascii      
minioadmin:minioadmin@tcp(xxx.xxx.xxx.xxx:3306)/blog?charset=utf8                What character set should be used？

**Comment by harshavardhana** [comment]
Fixed in #14350
