### ISSUE TITLE
Data loss after upgrade with missing node in distributed mode

### ISSUE THREAD

**Issue by vintikzzz** [minio/minio#14294]
Got data loss after losing node, upgrading and healing.

## Expected Behavior
After losing one of three nodes and replacing it with new one and after heal expecting healthy cluster.

## Current Behavior
After losing one of three nodes and replacing it with  new one and after heal got data loss, part of files gone and another part was corrupted (partly lost). 

## Steps to Reproduce (for bugs)
1. Start cluster with three nodes with minio version `RELEASE.2020-08-07T01-23-07Z`
2. Replace one node with new one
3. Do rolling update to new version `RELEASE.2022-02-07T08-17-33Z`
4. Do a heal with `mc admin heal` of replaced node

## Context
1. We started our cluster with 3 nodes, with 2 drives in (RAID 1). Our configuration was
```
/opt/minio server --address :9000 http://kvm73.advm/minio-storage/storage1 http://kvm73.advm/minio-storage/storage2 http://kvm73.advm/minio-storage/storage3 http://kvm73.advm/minio-storage/storage4 http://kvm74.advm/minio-storage/storage1 http://kvm74.advm/minio-storage/storage2 http://kvm74.advm/minio-storage/ste3 http://kvm74.advm/minio-storage/storage4 http://kvm103.advm/minio-storage/storage1 http://kvm103.advm/minio-storage/storage2 http://kvm103.advm/minio-storage/ste3 http://kvm103.advm/minio-storage/storage4
```
With minio version `RELEASE.2020-08-07T01-23-07Z`

2. After a year we realized that we need to add additional drives. So we decided to remove raid (just break it to 2 standard drives) and add 2 additional drives to each node. So finally we had 3 nodes with 4 hard drives on each. Minio configuration stayed the same, all data was allocated only on one drive on each node.
3. Then we rsynced data from folders to separate drives on the first node. We had to turn off minio server instance there for a long period to finish rsync operation. Then we tried to start it and got:
```
Jan 28 22:44:16 kvm103.advm minio[4092]: Error: Following error has been printed 3 times.. UUID on positions 0:8 do not match with, expected 909eedc0-89d9-4dce-b2c9-183dcc9e6714 got a5f7dd32-34c2-40a9-9878-24d0ca87215d
```
4. We started healing process of that node, but heal silently finishes after 10 minutes after start with no result.
5. After that, we upgraded minio to fresh version `RELEASE.2022-02-07T08-17-33Z` in believe that it will solve healing process.
6. Finally we started heal again and part of our data became unavailable. Heal process is currently running:
![image](https://user-images.githubusercontent.com/150981/153582106-ac21c046-de6f-46a9-8f27-01fde499ea78.png)

Is there any chance that all our data became available after heal?

## Regression
Is this issue a regression? **No**

## Your Environment
* Version used (`minio --version`):
old version:
```
$ ./minio.old --version
minio.old version RELEASE.2020-08-07T01-23-07Z
```
new version:
```
$ ./minio --version
minio version RELEASE.2022-02-07T08-17-33Z
```
* Server setup and configuration:
```
# Volume to be used for MinIO server.
MINIO_VOLUMES="http://kvm73.advm/minio-storage/storage1 http://kvm73.advm/minio-storage/storage2 http://kvm73.advm/minio-storage/storage3 http://kvm73.advm/minio-storage/storage4 http://kvm74.advm/minio-storage/storage1 http://kvm74.advm/minio-storage/storage2 http://kvm74.advm/minio-storage/ste3 http://kvm74.advm/minio-storage/storage4 http://kvm103.advm/minio-storage/storage1 http://kvm103.advm/minio-storage/storage2 http://kvm103.advm/minio-storage/ste3 http://kvm103.advm/minio-storage/storage4"
# Use if you want to run MinIO on a custom port.
MINIO_OPTS="--address :9000"
```
* Operating System and version (`uname -a`):
```
Linux kvm74.advm 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by klauspost** [comment]
Your homegrown expansion method will never work. First of all, you should never touch backend files, and you cannot just slap on more harddrives and expect it to work. I don't know if you read the [expansion documentation](https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html#expand-a-distributed-minio-deployment) and just choose to ignore it. Doesn't matter much now.

From your description it seems like there is now just random files thrown on to random disks, meant for a different setup. I highly doubt the green files are even usable.

I honestly don't see how we can help you. Healing is likely just making things worse. It relies on a stable setup. You destroyed that when you started moving files and changed the cluster setup.

**Comment by vintikzzz** [comment]
@klauspost just for clarification:
1. We haven't changed mount positions.
2. We haven't changed minio configuration, it stays the same all the time.
3. We haven't randomly changed data on disks.

Currently we don't understand what restriction we neglected.

To prevent me and others from similar mistakes could you answer additional questions.
1. Is it possbile to replace one hard drive with larger one after full data sync? Will minio crash after that?
2. Should we use heal after replacing failed node with new clean one?
3. Is there any docs how to do safe node replacement after fail?

Right now I understand that our data might be corrupted, but we need to understand how to avoid such problems in future.

**Comment by klauspost** [comment]
> After a year we realized that we need to add additional drives. So we decided to remove raid (just break it to 2 standard drives) and add 2 additional drives to each node. So finally we had 3 nodes with 4 hard drives on each. Minio configuration stayed the same, all data was allocated only on one drive on each node.

> Then we rsynced data from folders to separate drives on the first node.

You should never touch backend files. These are big no-nos. `UUID on positions 0:8 do not match` is a huge warning sign that your drives changed positions.

Follow the [setup guides](https://docs.min.io/minio/baremetal/installation/deployment-and-management.html) especially [using labels in fstab to ensure consistent mounting](https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html#local-jbod-storage-with-sequential-mounts).

When a drive fails; [replace it](https://docs.min.io/minio/baremetal/installation/restore-minio.html#minio-restore-hardware-failure-drive). When a node fails; [replace it](https://docs.min.io/minio/baremetal/installation/restore-minio.html#node-failure-recovery).

Expand by adding [another server pool](https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html). Decommission old [server pools](https://docs.min.io/minio/baremetal/installation/decommission-pool.html).

Perform tests on a staging cluster. Get [a subscription](https://min.io/pricing) where we can validate your setup and guide you through all of the things above.

**Comment by vintikzzz** [comment]
@klauspost BIG Thank You!
