### ISSUE TITLE
Cannot create a user using boto3

### ISSUE THREAD

**Issue by vladimirtiukhtin** [minio/minio#14298]
## Expected Behavior
User created

## Current Behavior
```
botocore.exceptions.ClientError: An error occurred (MissingParameter) when calling the CreatePolicy operation: Invalid STS API version 2010-05-08, expecting 2011-06-15
```

## Steps to Reproduce (for bugs)
```
import boto3

iam = boto3.client(
    service_name='iam',
    endpoint_url='https://example.com
)
iam.create_user(
    UserName="test"
)
```

## Context
I am trying to automate user creation

## Your Environment
RELEASE.2022-02-07T08-17-33Z

**Comment by harshavardhana** [comment]
@vladimirtiukhtin we never mention that we support AWS IAM APIs - use https://github.com/minio/madmin-go or `mc admin user add..`
