### ISSUE TITLE
Unable to migrate from RELEASE.2021-07-08T01-15-01Z to latest RELEASE.2022-02-07T08-17-33Z

### ISSUE THREAD

**Issue by gughappriya** [minio/minio#14315]
### Discussed in https://github.com/minio/minio/discussions/14263

<div type='discussions-op-text'>

<sup>Originally posted by **gughappriya** February  7, 2022</sup>
## Expected Behavior
if we use sse enabled in both versions of minio , when data thats added using RELEASE.2021-07-08T01-15-01Z upgraded to RELEASE.2022-02-07T08-17-33Z . The data should be upgraded with no issues
```
Priyasekar@PriyaSekars-MacBook-Pro ibm-minio-operator % mc cp --insecure sse-test/bucket/testing-encrypt.txt  ./test-downloaded-from-minio-1010.txt
success
```

## Current Behavior
if we use sse enabled in both versions of minio , when data thats added using RELEASE.2021-07-08T01-15-01Z upgraded to RELEASE.2022-02-07T08-17-33Z, results in error
```
Priyasekar@PriyaSekars-MacBook-Pro ibm-minio-operator % mc cp --insecure sse-test/bucket/testing-encrypt.txt  ./test-downloaded-from-minio-1010.txt
mc: <ERROR> Failed to copy `https://localhost:9000/bucket/testing-encrypt.txt`. Server side encryption specified but KMS is not configured
```

## Steps to Reproduce (for bugs)
1. Add data to bucket using RELEASE.2021-07-08T01-15-01Z 
2. Upgrade minio version to RELEASE.2021-11-03T03-36-36Z
3. Using minio cp to copy the data added from previous version of minio 
4. It fails with the error 
```
mc: <ERROR> Failed to copy `https://localhost:9000/bucket/testing-encrypt.txt`. Server side encryption specified but KMS is not configured
```

**Detailed story :**
So to give the full story of what we tried lets call this old release(RELEASE.2021-07-08T01-15-01Z ) as X and the later release(RELEASE.2022-02-07T08-17-33Z) we tried as Y
**Scenario :** We added data using the X version of minio and then later upgraded to Y version. The data we added was not readable anymore
1. With SSE enabled we added data to buckets using X version of minio.
```
mc --insecure config host add sse-test https://localhost:9000/
mc ls --insecure sse-test

mc cp --insecure --encrypt sse-test/bucket/ ./testing.txt sse-test/bucket/testing-encrypt.txt
./testing.txt:                         21 B / 21 B

mc stat --insecure sse-test/bucket/testing-encrypt.txt
Name      : testing-encrypt.txt
Date      : 2021-12-13 17:53:35 CST
Size      : 21 B
ETag      : 3a5eba4d91f3dbbe047f24ce02cd2530
Type      : file
Metadata  :
  Content-Type: text/plain
Encrypted :
  X-Amz-Server-Side-Encryption: AES256

mc cat --insecure sse-test/bucket/testing-encrypt.txt
Hello Hello Hello!!!
```
2. When we upgraded to Y version of minio we got the following error on reading
`cause: com.amazonaws.services.s3.model.AmazonS3Exception: Server side encryption specified but KMS is not configured (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: 16BC9A97099E0EE9; S3 Extended Request ID: 52bff882-da55-46c7-a8bb-a7cb76534d2d), S3 Extended Request ID: 52bff882-da55-46c7-a8bb-a7cb76534d2d)`
3. in order to fix this we applied a fix which we thought could resolve the issue like below

             
          if [ ! -z "${MINIO_SSE_MASTER_KEY}" ]; then
                  keyval=($(echo "${MINIO_SSE_MASTER_KEY}" | tr ":" "\n"))
          
                  reencodedval=($(echo -n "${keyval[1]}"|xxd -r -p |base64))
          
                  MINIO_KMS_SECRET_KEY=("${keyval[0]}:$reencodedval")
                  export MINIO_KMS_SECRET_KEY
              fi
          
            The fix can be explained as follows
            1.take or reuse MINIO_SSE_MASTER_KEY 's value (not the secret ref of name/key)
            2. parse wire-master-key:${hex_encoded_key}  in 2 part - > 1st: wire-master-key  , 2nd: ${hex_encoded_key}
            3.for 2nd: ${hex_encoded_key}  -> decode it by hex and encoded by base64, save it in ${base64_encoded_key}
            4.combine the 2 part again: wire-master-key:${base64_encoded_key}
            5.add KMS_SECRET_KEY env var with the value of wire-master-key:${base64_encoded_key}
4. When we tried to read the data added using X version of minio
```
priyasekar@PriyaSekars-MacBook-Pro ibm-minio-operator %  mc cp --insecure sse-test/bucket/testing-encrypt.txt  ./test-downloaded-from-minio-1010.txt
����g�Vf�g� ��ծ)X�bM���B�ޡ"��(���d\�;�|...)st:9000/bucket/testing-encrypt.txt`. We encountered an internal error, please try again.: cause(readObjectStart: expect { or n, but found �, error found in #2 byte of ...| ������6XX�
priyasekar@PriyaSekars-MacBook-Pro ibm-minio-operator % mc cat --insecure sse-test/bucket/testing-encrypt.txt
����g�Vf�g� ��ծ)X�bM���B�ޡ"��(���d\�;�|...).cket/testing-encrypt.txt`. We encountered an internal error, please try again.: cause(readObjectStart: expect { or n, but found �, error found in #2 byte of ...| ������6XX�

```
## Configuration
We have container based environment which runs on ubi image.
SSE_S3 is used 
MINIO_ACCESS_KEY
MINIO_SECRET_KEY
MINIO_SSE_MASTER_KEY = wire-master-key:XYZ
This is the KMS secret key thats used in both versions of minio
```
docker_kms_secret_encryption_env() {
    if [ -f "$MINIO_KMS_SECRET_KEY_FILE" ]; then
        KMS_SECRET_KEY_FILE="$MINIO_KMS_SECRET_KEY_FILE"
    else
        KMS_SECRET_KEY_FILE="/run/secrets/$MINIO_KMS_SECRET_KEY_FILE"
    fi

    if [ -f "$KMS_SECRET_KEY_FILE" ]; then
        MINIO_KMS_SECRET_KEY="$(cat "$KMS_SECRET_KEY_FILE")"
        export MINIO_KMS_SECRET_KEY
    fi
}
```
</div>

**Comment by harshavardhana** [comment]
> if [ ! -z "${MINIO_SSE_MASTER_KEY}" ]; then
>            keyval=($(echo "${MINIO_SSE_MASTER_KEY}" | tr ":" "\n"))
>    
>            reencodedval=($(echo -n "${keyval[1]}"|xxd -r -p |base64))
>    
>            MINIO_KMS_SECRET_KEY=("${keyval[0]}:$reencodedval")
>            export MINIO_KMS_SECRET_KEY
>        fi

This is not the correct fix you are doing things wrong here. MINIO_SSE_MASTER_KEY is not portable to MINIO_KMS_SECRET_KEY - it never was. 

Even in release  
RELEASE.2021-07-08T01-15-01Z there was no support for MINIO_SSE_MASTER_KEY, MINIO_KMS_MASTER_KEY

Looks like you are coming from a time when we had  MINIO_SSE_MASTER_KEY, MINIO_KMS_MASTER_KEY - this was always mentioned that it's meant for testing purposes only.

So if you used it to store production data that won't be recoverable unfortunately and this has been deprecated for close to a year now.

**Comment by harshavardhana** [comment]
To re-iterate data written with MINIO_SSE_MASTER_KEY was never meant to be readable with MINIO_KMS_SECRET_KEY .

This was changed in this commit all the variables are removed 

```
commit 3455f786faf047eeb13a32418188de11b7f753e8
Author: Andreas Auernhammer <aead@mail.de>
Date:   Thu Apr 22 17:45:30 2021 +0200

    kms: encrypt IAM/config data with the KMS (#12041)
    
    This commit changes the config/IAM encryption
    process. Instead of encrypting config data
    (users, policies etc.) with the root credentials
    MinIO now encrypts this data with a KMS - if configured.
    
    Therefore, this PR moves the MinIO-KMS configuration (via
    env. variables) to a "top-level" configuration.
    The KMS configuration cannot be stored in the config file
    since it is used to decrypt the config file in the first
    place.
    
    As a consequence, this commit also removes support for
    Hashicorp Vault - which has been deprecated anyway.
    
    Signed-off-by: Andreas Auernhammer <aead@mail.de>
```

So looks like you have manually hacked around things on your own not knowing the actual implications.

**Comment by aaronmcohen** [comment]
Thank you @harshavardhana for the insight. How would you recommend we move forward from where we are?

**Comment by harshavardhana** [comment]
> Thank you @harshavardhana for the insight. How would you recommend we move forward from where we are?

Setup an instance that can read the older content, setup a new instance with relevant settings such as KMS_SECRET_KEY and `mc mirror` - drop the older setup once complete.
