### ISSUE TITLE
windows Program Files (x86) start fail

### ISSUE THREAD

**Issue by xuanshuangqi** [minio/minio#14318]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Possible Solution

windows Program Files (x86) start fail
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

error is panic: Invalid schema provided to SchemaValidator: open c:\program files (x86)\hengshi\lib\minio-windows-2022-01-08t03-11-54z\.root: The system cannot find the file specified.
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
We do not support 32bit windows @xuanshuangqi 

> error is panic: Invalid schema provided to SchemaValidator: open c:\program files (x86)\hengshi\lib\minio-windows-2022-01-08t03-11-54z.root: The system cannot find the file specified.

Also the binary looks like not published by MinIO
