### ISSUE TITLE
MinIO Okta integration problems (OIDC)

### ISSUE THREAD

**Issue by marekm-gain** [minio/minio#14328]
## Expected Behavior
When I setup MinIO integration with Okta, it should let you in into minio console after pressing Login with SSO button and providing your creds in Okta. I'm on K8S.

## Current Behavior
After pressing login button, MinIO is redirecting to Okta for logging. After successful login Okta is redirecting back to MinIO. Redirect contains code and state fields but MinIO is not authorizing me and returns 401 on session. See screenshot:
![Screen Shot 2022-02-14 at 17 54 21](https://user-images.githubusercontent.com/80689944/154296294-64d937b7-49c3-4a5d-bd6a-2e883a552e3d.png)

I've used "code" field returned by Okta to receive JWT token manually (with a curl) and it looks fine.
```
{
  "ver": 1,
  "jti": "AT.xxxx",
  "iss": "https://okta_endpoint/oauth2/default",
  "aud": "api://default",
  "iat": 1644856282,
  "exp": 1644859882,
  "cid": "0oa2i56hsk2MFZn8P1d7",
  "uid": "00ux4dimavdr85cHL1d6",
  "scp": [
    "openid",
    "minio"
  ],
  "sub": "xxx@example.com",
  "name": "xxx xxx",
  "cds_id": "bf65449b-39e3-41c7-acb4-40d4dafcc01f",
  "policy": "consoleAdmin"
}
```

So to sum it up I'm ending back on login page with login button and Okta team is confirming they can see my succesfull logins for minio service.

There is nothing in minio logs. I've set `_MINIO_SERVER_DEBUG: "on"`, I've checked container logs as well as mc clients calls like:
```
mc admin console --debug 
mc admin trace -v -a
```

## Possible Solution
I've tried different versions of MinIO. I've initially tried it as gateway mode, but I've also verified same behavior for standalone. I've tried configuration with etcd. Nothing helped.

## Steps to Reproduce (for bugs)

1. Configure Minio with following:
```
MINIO_IDENTITY_OPENID_CONFIG_URL: "https://okta_endpoint/oauth2/default/.well-known/oauth-authorization-server"
MINIO_IDENTITY_OPENID_CLIENT_ID: "yyy"
MINIO_IDENTITY_OPENID_CLIENT_SECRET: "xxx"
MINIO_IDENTITY_OPENID_REDIRECT_URI: "https://example.com/"
MINIO_IDENTITY_OPENID_SCOPES: "minio"
MINIO_IDENTITY_OPENID_CLAIM_NAME: "policy"`
```
2. Setup Okta service that with consoleAdmin as a policy claim and minio as a scope.
3. Try logging in.

## Context
Following company wide policies I want to integrate with Okta.

## Regression
Not a regression.

## Your Environment
* Version used (`minio --version`): RELEASE.2022-02-01T18-00-14Z (but I've tried a lot of different ones)
* Server setup and configuration: quay.io/minio/minio docker image with minio identity config described above
* Operating System and version (`uname -a`): quay.io/minio/minio docker image

**Comment by harshavardhana** [comment]
You haven't setup any claims on Okta for the connection here.

Your jwt is a proof for that, it will not work that's why.

**Comment by ravindk89** [comment]
@harshavardhana The claim has `policy` field - do we look elsewhere for that specific value?

**Comment by harshavardhana** [comment]
> @harshavardhana The claim has `policy` field - do we look elsewhere for that specific value?

That's not the JWT - using `code` obtained JWT is not a id_token - the claims need to be added to `id_token`

**Comment by marekm-gain** [comment]
Ok I've now configured my own Okta test environment to be able to test any changes and I've made sure that policy claim is set on id_token.

Here is the id_token get by using 'code' field returned by pressing Login button:
```
{
  "sub": "00u3x5qq1dsoiQIfB5d7",
  "name": "xxx xxxx",
  "ver": 1,
  "iss": "https://dev-4657357.okta.com/oauth2/default",
  "aud": "0oa3x5rzhgr5wMrHq5d7",
  "iat": 1645193208,
  "exp": 1645196808,
  "jti": "ID.XILzsKF2WVy1-1hGuvIZWISJ2EcYBHFUy3-r7Y3WPpU",
  "amr": [
    "pwd"
  ],
  "idp": "00o3x5qpvyZMtX6EK5d7",
  "preferred_username": "xxx@xxx.xx",
  "auth_time": 1645188957,
  "at_hash": "_Uj9m4h2NgD-XwbFdRkZdg",
  "policy": "consoleAdmin"
}
```

But the behavior is exactly the same, despite policy claim present.

**Comment by harshavardhana** [comment]
> Ok I've now configured my own Okta test environment to be able to test any changes and I've made sure that policy claim is set on id_token.
> 
> Here is the id_token get by using 'code' field returned by pressing Login button:
> 
> ```
> {
>   "sub": "00u3x5qq1dsoiQIfB5d7",
>   "name": "xxx xxxx",
>   "ver": 1,
>   "iss": "https://dev-4657357.okta.com/oauth2/default",
>   "aud": "0oa3x5rzhgr5wMrHq5d7",
>   "iat": 1645193208,
>   "exp": 1645196808,
>   "jti": "ID.XILzsKF2WVy1-1hGuvIZWISJ2EcYBHFUy3-r7Y3WPpU",
>   "amr": [
>     "pwd"
>   ],
>   "idp": "00o3x5qpvyZMtX6EK5d7",
>   "preferred_username": "xxx@xxx.xx",
>   "auth_time": 1645188957,
>   "at_hash": "_Uj9m4h2NgD-XwbFdRkZdg",
>   "policy": "consoleAdmin"
> }
> ```
> 
> But the behavior is exactly the same, despite policy claim present.

When you attempt to login, run `mc admin trace alias/ --funcname 'sts*' -v` and share it here ?

**Comment by marekm-gain** [comment]
This is not giving me anything. Nor the -a switch.
Here is the output with debug:
```
^Csh-4.4# mc admin trace mymino --funcname 'sts*' -v --debug
mc: <DEBUG> GET /minio/admin/v3/trace?err=false&internal=false&os=false&s3=true&storage=false&threshold=0s HTTP/1.1
Host: example.com
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2022-02-07T09-25-34Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20220218//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220218T160934Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Security-Policy: block-all-mixed-content
Content-Type: text/event-stream
Date: Fri, 18 Feb 2022 16:09:35 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Accel-Buffering: no
X-Amz-Request-Id: 16D4ED34B9301691
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Let's Encrypt
mc: <DEBUG>  >> Expires: 2022-05-09 13:53:08 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Internet Security Research Group
mc: <DEBUG>  >> Expires: 2025-09-15 16:00:00 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Organization: Digital Signature Trust Co.
mc: <DEBUG>  >> Expires: 2024-09-30 18:14:03 +0000 UTC
mc: <DEBUG> Response Time:  697.319ms
```

**Comment by harshavardhana** [comment]
yeah this means that there is no login request being sent to minio

**Comment by marekm-gain** [comment]
Ah ok, so the requirement here is that minio needs to be accessible from outside world?

**Comment by harshavardhana** [comment]
> Ah ok, so the requirement here is that minio needs to be accessible from outside world?

Well, Console needs to reach MinIO - so if you are behind some proxy, etc. you need to make sure MinIO is reachable - see how this is here https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/nginx.conf

**Comment by marekm-gain** [comment]
So this is a standalone one node instance running console and server. I can connecting to it from client run on my local machine. Redirect URL works fine to minio console, however if Okta is expected to initiate some connection to Minio it will not work, as it is not exposed to outside world. It's only accessible via private network.

**Comment by harshavardhana** [comment]
> So this is a standalone one node instance running console and server. I can connecting to it from client run on my local machine. Redirect URL works fine to minio console, however if Okta is expected to initiate some connection to Minio it will not work, as it is not exposed to outside world. It's only accessible via private network.

No, it is not that console should be able to make some connection to MinIO with a request obtained with JWT from Okta. From what I can see there is nothing that is being presented to MinIO as JWT @marekm-gain .

What I mean is that even the attempt to even reach MinIO from the UI is not happening. You can run MinIO server with `_MINIO_SERVER_DEBUG=on` and attempt a login and see what is going on and share it here.

**Comment by marekm-gain** [comment]
I have `_MINIO_SERVER_DEBUG=on`, this is the full output from container. There is nothing showing up when I'm attempting to login on minio console web UI. When I switch off Okta everythings work well.
```
 You are running an older version of MinIO released 2 weeks ago
 Update:
Run `mc admin update`
API: https://example.com
Console: https://10.42.3.72:9001 https://127.0.0.1:9001
Documentation: https://docs.min.io
== DEBUG Mode enabled ==
Currently set environment settings:
MINIO_ACCESS_KEY_FILE=access_key
GATEWAY_AZURE_CONSOLE_SERVICE_PORT_HTTPS=443
GATEWAY_AZURE_PORT_443_TCP_PROTO=tcp
_MINIO_SERVER_DEBUG=on
HOSTNAME=example-com-55758ff96b-sxtq7
MINIO_KMS_SECRET_KEY_FILE=kms_master_key
MINIO_IDENTITY_OPENID_CLIENT_ID=0oa3x5rzhgr5wMrHq5d7
MINIO_ETCD_PORT_2379_TCP_PROTO=tcp
GATEWAY_AZURE_CONSOLE_PORT=tcp://10.43.38.68:443
MINIO_ETCD_PORT_2379_TCP=tcp://10.43.103.198:2379
MINIO_ETCD_PORT_2380_TCP_ADDR=10.43.103.198
MINIO_ETCD_PORT_2380_TCP_PROTO=tcp
GATEWAY_AZURE_PORT_443_TCP_PORT=443
MINIO_IDENTITY_OPENID_REDIRECT_URI=https://example.com
MINIO_ETCD_PORT=tcp://10.43.103.198:2379
GATEWAY_AZURE_CONSOLE_PORT_443_TCP_PROTO=tcp
MINIO_ETCD_PORT_2379_TCP_PORT=2379
GATEWAY_AZURE_CONSOLE_PORT_443_TCP_ADDR=10.43.38.68
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
container=oci
MINIO_IDENTITY_OPENID_SCOPES=openid profile
MINIO_ETCD_PORT_2380_TCP_PORT=2380
GATEWAY_AZURE_CONSOLE_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.43.0.1:443
MINIO_ETCD_SERVICE_PORT_PEER=2380
PWD=/
HOME=/
MINIO_ETCD_PORT_2380_TCP=tcp://10.43.103.198:2380
MINIO_ETCD_SERVICE_HOST=10.43.103.198
KUBERNETES_SERVICE_PORT_HTTPS=443
GATEWAY_AZURE_SERVICE_PORT=443
KUBERNETES_PORT_443_TCP_PORT=443
MINIO_ETCD_SERVICE_PORT_CLIENT=2379
MINIO_IDENTITY_OPENID_CLIENT_SECRET=xxxxxx
GATEWAY_AZURE_SERVICE_HOST=10.43.36.242
2022/02/18 17:12:32 Serving console at https://[::]:9001
MINIO_ETCD_PORT_2379_TCP_ADDR=10.43.103.198
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
GATEWAY_AZURE_PORT_443_TCP_ADDR=10.43.36.242
MINIO_ROOT_USER_FILE=access_key
MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
GATEWAY_AZURE_PORT=tcp://10.43.36.242:443
GATEWAY_AZURE_SERVICE_PORT_HTTPS=443
MINIO_ROOT_PASSWORD_FILE=secret_key
MINIO_SERVER_URL=https://example.com
SHLVL=1
MINIO_PROMETHEUS_AUTH_TYPE=public
KUBERNETES_SERVICE_PORT=443
GATEWAY_AZURE_CONSOLE_SERVICE_HOST=10.43.38.68
GATEWAY_AZURE_CONSOLE_PORT_443_TCP=tcp://10.43.38.68:443
MINIO_UPDATE_MINISIGN_PUBKEY=RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
MINIO_SECRET_KEY_FILE=secret_key
PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MINIO_CONFIG_ENV_FILE=config.env
GATEWAY_AZURE_PORT_443_TCP=tcp://10.43.36.242:443
GATEWAY_AZURE_CONSOLE_PORT_443_TCP_PORT=443
MINIO_ETCD_SERVICE_PORT=2379
KUBERNETES_SERVICE_HOST=10.43.0.1
MINIO_IDENTITY_OPENID_CONFIG_URL=https://dev-4657357.okta.com/oauth2/default/.well-known/openid-configuration
CONSOLE_PBKDF_SALT=f6f78cdb-c161-4151-b494-6128c29016a9
CONSOLE_PBKDF_PASSPHRASE=f6f78cdb-c161-4151-b494-6128c29016a9
CONSOLE_MINIO_SERVER=https://example.com
CONSOLE_IDP_URL=https://dev-4657357.okta.com/oauth2/default/.well-known/openid-configuration
CONSOLE_IDP_CLIENT_ID=xxx
CONSOLE_IDP_SECRET=xxx
CONSOLE_IDP_HMAC_SALT=f6f78cdb-c161-4151-b494-6128c29016a9
CONSOLE_IDP_HMAC_PASSPHRASE=xxx
CONSOLE_IDP_SCOPES=openid profile
CONSOLE_IDP_CALLBACK=https://example.com
CONSOLE_MINIO_REGION=
CONSOLE_CERT_PASSWD=
======
minio: <DEBUG> starting scanner cycle
minio: <DEBUG> dataUpdateTracker: cycle bloom filter: 188 -> 189
minio: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 189
```

**Comment by harshavardhana** [comment]
@marekm-gain there is no login attempt coming to MinIO - Console WebUI is not even sending the callback request. So it means that the entire configuration is sort of wrong here. 

> CONSOLE_IDP_CALLBACK=https://example.com

You should have MinIO also have console started as `--console-address example.com:9001`  @marekm-gain
