### ISSUE TITLE
Cannot login MinIO Console: Invalid login, details: Expected element type <Error> but have <html>

### ISSUE THREAD

**Issue by jwenjian** [minio/minio#14332]
## Expected Behavior
Can login MinIO console successfully

## Current Behavior
After input username and password, the UI prompts an error:
error title: Invalid login
error detail: Expected element type <Error> but have <html>

In chrome devtools, the captured login request is in below screenshots
![image](https://user-images.githubusercontent.com/25657798/154436420-54cf0842-13d2-45a8-93d5-889038220e89.png)

## Possible Solution
Nah

## Steps to Reproduce (for bugs)

1. Prepare a RHEL 8.4 server
2. create a local folder

mkdir /mnt/minio
chcon -Rt container_file_t /mnt/minio

3. start minio server
podman run -d --restart=always -p 9000:9000 -p 9001:9001 -v /mnt/minio:/data -e "MINIO_ROOT_USER=myminioadmin" -e "MINIO_ROOT_PASSWORD=myminioadminpassword" [quay.io/minio/minio](http://quay.io/minio/minio) server /data --console-address ":9001"

4. open browser and input username / password to login

## Context
If the issue exists, we cannot recommend our customer to use MinIO as a S3 storage server

## Regression
No

## Your Environment
* Version used (`minio --version`):  `quay.io/minio/minio  RELEASE.2022-02-12T00-51-25Z  279b6aaea553  3 days ago    252 MB`
* Server setup and configuration: `-e "MINIO_ROOT_USER=myminioadmin" -e "MINIO_ROOT_PASSWORD=myminioadminpassword" [quay.io/minio/minio](http://quay.io/minio/minio) server /data --console-address ":9001" `
* Operating System and version (`uname -a`):  `Linux localhost.localdomain 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@jwenjian you seem to have something else running on the port 9000 that is causing html to be returned instead.

**Comment by jwenjian** [comment]
@harshavardhana port 9000 is mapping to minio container port 9000, so I have no idea why this error is happened

**Comment by jwenjian** [comment]
logs of `mc admin trace local --debug`:

```
[root@localhost ~]# ./mc admin trace local --debug -v
mc: <DEBUG> GET /minio/admin/v3/trace?err=false&internal=false&os=false&s3=true&storage=false&threshold=0s HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2022-02-16T05-54-01Z
Authorization: AWS4-HMAC-SHA256 Credential=myminioadmin/20220217//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220217T164107Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Security-Policy: block-all-mixed-content
Content-Type: text/event-stream
Date: Thu, 17 Feb 2022 16:41:07 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Accel-Buffering: no
X-Amz-Request-Id: 16D4A058CB056B49
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  502.511127ms

```

**Comment by harshavardhana** [comment]
> @harshavardhana port 9000 is mapping to minio container port 9000, so I have no idea why this error is happened

This error is happening because you have another entity that replies back an error as HTML - either there is already another entity running on port 9000 that is not returning back calls for the browser.

**Comment by harshavardhana** [comment]
```
~ podman run -d --restart=always -p 9000:9000 -p 9001:9001 -v /tmp/minio:/data -e "MINIO_ROOT_USER=myminioadmin" -e "MINIO_ROOT_PASSWORD=myminioadminpassword" quay.io/minio/minio server /data --console-address ":9001"

Trying to pull quay.io/minio/minio:latest...
Getting image source signatures
Copying blob 4af7314918ee done  
Copying blob fdf7c3c4a3fe done  
Copying blob e5393aecefb7 done  
Copying blob d57f25aceb79 done  
Copying blob 19679eed24a2 done  
Copying blob 2dbc6a31bcc7 done  
Copying blob 3cd53d2fb14d done  
Copying config 2c6d15ec8b done  
Writing manifest to image destination
Storing signatures

a7b0a959b96ba868cad766735a432965b6bfe0a743e23ab201dc02b7122725e2
```

```
podman logs a7b0a959b96b
API: http://10.0.2.100:9000  http://127.0.0.1:9000     

Console: http://10.0.2.100:9001 http://127.0.0.1:9001   

Documentation: https://docs.min.io
```

![logged-in](https://user-images.githubusercontent.com/622699/154439788-e9100b6e-711f-4a95-86cc-f4e88b415383.png)

**Comment by harshavardhana** [comment]
I am pretty sure you have another php-fpm like service running that uses SO_REUSEPORT or something @jwenjian

**Comment by harshavardhana** [comment]
Use 

```
podman run -d --restart=always -p 9002:9002 -p 9001:9001 -v /tmp/minio:/data -e "MINIO_ROOT_USER=myminioadmin" -e "MINIO_ROOT_PASSWORD=myminioadminpassword" quay.io/minio/minio server /data --console-address ":9001" --address ":9002"
```

**Comment by jwenjian** [comment]
u

> Use
> 
> ```
> podman run -d --restart=always -p 9002:9002 -p 9001:9001 -v /tmp/minio:/data -e "MINIO_ROOT_USER=myminioadmin" -e "MINIO_ROOT_PASSWORD=myminioadminpassword" quay.io/minio/minio server /data --console-address ":9001" --address ":9002"
> ```
> 
> and see if this changes the behavior.

@harshavardhana this works...

**Comment by jwenjian** [comment]
When I use the command `podman run -d --restart=always -p 9002:9002 -p 9001:9001 -v /tmp/minio:/data -e "MINIO_ROOT_USER=myminioadmin" -e "MINIO_ROOT_PASSWORD=myminioadminpassword" quay.io/minio/minio server /data --console-address ":9001" --address ":9002"` to run the minio,  there is no other process listening on port 9000.

**Comment by harshavardhana** [comment]
> 
> @harshavardhana this works...

Then you do have something running on port 9000, perhaps something setup-related. Closing this

**Comment by jwenjian** [comment]
It turns out the http_proxy and https_proxy issue, when unset the http_proxy and https_proxy before running minio container, everything is fine even on port 9000.

**Comment by harshavardhana** [comment]
> It turns out the http_proxy and https_proxy issue, when unset the http_proxy and https_proxy before running minio container, everything is fine even on port 9000.

👍🏽
