### ISSUE TITLE
Unable to initialize OpenID : connection refused

### ISSUE THREAD

**Issue by buttonman** [minio/minio#14348]
## Expected Behavior

minio works well with keycloak openid

## Current Behavior

when I started minio deployment in kubernetes with following enviroments

- name: MINIO_IDENTITY_OPENID_CONFIG_URL
   value: http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration
- name: MINIO_IDENTITY_OPENID_CLIENT_ID
   value: minio
- name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
   value: bef93891-0602-4d7f-8e60-532573996792

occurs following error

`
Error: Unable to initialize OpenID: Get "http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration": dial tcp 34.64.220.64:32499: connect: connection refused (*fmt.wrapError)
       7: cmd/config-current.go:502:cmd.lookupConfigs()
       6: cmd/config-current.go:748:cmd.loadConfig()
       5: cmd/config.go:233:cmd.initConfig()
       4: cmd/config.go:193:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:370:cmd.initAllSubsystems()
       2: cmd/server-main.go:297:cmd.initServer()
       1: cmd/server-main.go:514:cmd.serverMain()
`

so, I tried to curl in minio pod, it works

`kubectl exec -it pod-name bash`
`curl http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration`

## Possible Solution
NA

## Steps to Reproduce (for bugs)
see above

## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2021-02-14T04-01-33Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> `Error: Unable to initialize OpenID: Get "http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration": dial tcp 34.64.220.64:32499: connect: connection refused (*fmt.wrapError) 7: cmd/config-current.go:502:cmd.lookupConfigs() 6: cmd/config-current.go:748:cmd.loadConfig() 5: cmd/config.go:233:cmd.initConfig() 4: cmd/config.go:193:cmd.(*ConfigSys).Init() 3: cmd/server-main.go:370:cmd.initAllSubsystems() 2: cmd/server-main.go:297:cmd.initServer() 1: cmd/server-main.go:514:cmd.serverMain()`

This is quite simply an error that shows we can't connect to it. I don't think we can do anything about this on our end @buttonman 

> `kubectl exec -it pod-name bash`
> `curl http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration`

Can you provide the output of this command?

**Comment by buttonman** [comment]
but i can get config from http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration in pod with curl and it also possible to get from browser with the url

why does http get fail in  current.go:502:cmd.lookupConfigs() ?

`{"issuer":"http://34.64.220.64:32499/auth/realms/artiference","authorization_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/auth","token_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/token","introspection_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/token/introspect","userinfo_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/userinfo","end_session_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/logout","jwks_uri":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/certs","check_session_iframe":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"id_token_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"request_object_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"response_modes_supported":["query","fragment","form_post","query.jwt","fragment.jwt","form_post.jwt","jwt"],"registration_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"introspection_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"introspection_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"authorization_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"authorization_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"authorization_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"],"claim_types_supported":["normal"],"claims_parameter_supported":true,"scopes_supported":["openid","profile","web-origins","email","offline_access","roles","phone","address","microprofile-jwt"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"require_request_uri_registration":true,"code_challenge_methods_supported":["plain","S256"],"tls_client_certificate_bound_access_tokens":true,"revocation_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/revoke","revocation_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"revocation_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"device_authorization_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/auth/device","backchannel_token_delivery_modes_supported":["poll","ping"],"backchannel_authentication_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/ext/ciba/auth","backchannel_authentication_request_signing_alg_values_supported":["PS384","ES384","RS384","ES256","RS256","ES512","PS256","PS512","RS512"],"require_pushed_authorization_requests":false,"pushed_authorization_request_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/ext/par/request","mtls_endpoint_aliases":{"token_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/token","revocation_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/revoke","introspection_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/token/introspect","device_authorization_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/auth/device","registration_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/clients-registrations/openid-connect","userinfo_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/userinfo","pushed_authorization_request_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/ext/par/request","backchannel_authentication_endpoint":"http://34.64.220.64:32499/auth/realms/artiference/protocol/openid-connect/ext/ciba/auth"}}`

**Comment by harshavardhana** [comment]
> `Error: Unable to initialize OpenID: Get "http://34.64.220.64:32499/auth/realms/artiference/.well-known/openid-configuration": dial tcp 34.64.220.64:32499: connect: connection refused (*fmt.wrapError) 7: cmd/config-current.go:502:cmd.lookupConfigs() 6: cmd/config-current.go:748:cmd.loadConfig() 5: cmd/config.go:233:cmd.initConfig() 4: cmd/config.go:193:cmd.(*ConfigSys).Init() 3: cmd/server-main.go:370:cmd.initAllSubsystems() 2: cmd/server-main.go:297:cmd.initServer() 1: cmd/server-main.go:514:cmd.serverMain()`

Are you setting up Keycloak also when deploying MinIO? - AFAICS this is simply order of deployment issue. i.e MinIO pod starts before keycloak is started. 

curl works because keycloak would have started by the time you are attempting to curl.

**Comment by harshavardhana** [comment]
Looks like a setup issue - ran keycloak locally and runs perfectly fine.

Make sure to setup keycloak first 
```
docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:17.0.0 start-dev
Unable to find image 'quay.io/keycloak/keycloak:17.0.0' locally
17.0.0: Pulling from keycloak/keycloak
df5cd4b3d61f: Pull complete 
fdee1701bdd9: Pull complete 
60aeb37f943a: Pull complete 
d944c0267ce3: Pull complete 
Digest: sha256:ab3b72a44813902fe44c9b927527f96096d4f9cbc4c881234b7b6bbc884d8dd8
Status: Downloaded newer image for quay.io/keycloak/keycloak:17.0.0
Updating the configuration and installing your custom providers, if any. Please wait.
2022-02-18 16:49:45,011 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 3471ms
2022-02-18 16:49:47,134 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
2022-02-18 16:49:47,580 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-02-18 16:49:47,611 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-02-18 16:49:47,623 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-02-18 16:49:47,812 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
2022-02-18 16:49:48,944 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2022-02-18 16:49:50,334 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_669767, Site name: null
2022-02-18 16:49:50,392 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2022-02-18 16:49:51,648 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
2022-02-18 16:49:51,720 INFO  [io.quarkus] (main) Keycloak 17.0.0 on JVM (powered by Quarkus 2.7.0.Final) started in 6.603s. Listening on: http://0.0.0.0:8080
2022-02-18 16:49:51,720 INFO  [io.quarkus] (main) Profile dev activated. 
2022-02-18 16:49:51,720 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, infinispan-client, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-02-18 16:49:51,721 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

```
 MINIO_IDENTITY_OPENID_CONFIG_URL=http://localhost:8080/realms/minio/.well-known/openid-configuration MINIO_IDENTITY_OPENID_CLIENT_ID=minio MINIO_IDENTITY_OPENID_CLIENT_SECRET=account  minio server ~/test
API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                           
RootUser: minioadmin 
RootPass: minioadmin 
SQS ARNs: arn:minio:sqs::_:webhook 

Console: http://10.0.0.185:39929 http://172.17.0.1:39929 http://172.18.0.1:39929 http://172.19.0.1:39929 http://127.0.0.1:39929              
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.185:9000 minioadmin minioadmin

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (39929), please use --console-address ":PORT" to choose a static port.
```
