### ISSUE TITLE
Using "is not missing" clause in SelectObjectContent results in "invalid arithmetic operator"

### ISSUE THREAD

**Issue by supriyo-biswas** [minio/minio#14358]
## Expected Behavior
As per https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-glacier-select-sql-reference-select.html#s3-glacier-select-sql-reference-from, the "is not missing" clause can be used to check for omitted fields.

I uploaded a file with the following content to Amazon S3:
```
{"request":{"uri":"/1","header":{"User-Agent":"test"}}}
{"request":{"uri":"/2","header":{}}}
```

Querying the aforementioned file with the query `select * from s3object[*] as s where s.request.header['User-Agent'] is not missing` results in the first line being returned, as shown below:

```
$ aws s3api select-object-content --bucket $BUCKET --key test.json --input-serialization 'JSON={Type=LINES},CompressionType=NONE' --output-serialization 'JSON={}' --expression-type SQL --expression "select * from s3object[*] as s where s.request.header['User-Agent'] is not missing" output
$ cat output 
{"request":{"uri":"/1","header":{"User-Agent":"test"}}}
```

## Current Behavior
When using minio, running the aforementioned query results in an error:

```
$ aws s3api select-object-content --profile minio --endpoint-url $MINIO_ENDPOINT --bucket $BUCKET --key test.json --input-serialization 'JSON={Type=LINES},CompressionType=NONE' --output-serialization 'JSON={}' --expression-type SQL --expression "select * from s3object[*] as s where s.request.header['User-Agent'] is not missing" output

An error occurred (InternalError) when calling the SelectObjectContent operation: invalid arithmetic operator
```

## Possible Solution
Go isn't exactly my forte but referring to https://github.com/minio/minio/blob/master/internal/s3select/sql/parser.go I didn't find "missing" as being one of the recognized keywords, therefore I suspect it is not implemented at this time.

## Steps to Reproduce (for bugs)
Please see above.

## Context
I'm trying to query JSON files where a certain field is missing.

## Regression
No

## Your Environment
* Version used (`minio --version`): RELEASE.2022-02-18T01-50-10Z
* Server setup and configuration: Minio running in single filesystem mode
* Operating System and version (`uname -a`): ```Linux storage1 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by klauspost** [comment]
There is no "MISSING". You may be able to check using `select * from s3object[*] as s where s.request.header['User-Agent'] is not null`.

Please provide a sample JSON for reproduction.

**Comment by supriyo-biswas** [comment]
> There is no "MISSING".

Not sure what you're referring to? This is a verbatim quote from the S3 documentation linked above:

> If you don't want Amazon S3 Select to return empty records when it doesn't find a match, you can test for the value MISSING. The following query returns the same results as the previous query, but with the empty values omitted:
> ```
> SELECT id FROM S3Object[*].Rules[*].id WHERE id IS NOT MISSING
> ```

> Please provide a sample JSON for reproduction.

Please see my original post where I provided the following test file:

```
{"request":{"uri":"/1","header":{"User-Agent":"test"}}}
{"request":{"uri":"/2","header":{}}}
```

> You may be able to check using `select * from s3object[*] as s where s.request.header['User-Agent'] is not null`.

I'll add another reply shortly once I've had the chance to test it both against S3 and Minio.

**Comment by supriyo-biswas** [comment]
> You may be able to check using `select * from s3object[*] as s where s.request.header['User-Agent'] is not null`.

Using `is not null` is fine on S3 and produces the expected result, whereas it causes the same error on minio, "An error occurred (InternalError) when calling the SelectObjectContent operation: invalid arithmetic operator".

**Comment by klauspost** [comment]
I suspect "invalid arithmetic operator" is from `s3object[*]`. Just use `s3object`

> Not sure what you're referring to?

MinIO does not support MISSING keyword.

**Comment by supriyo-biswas** [comment]
> I suspect "invalid arithmetic operator" is from `s3object[*]`. Just use `s3object`

Unfortunately, the error is precisely because of the `is not null` condition. Please find the test cases below.

With the previously provided JSON but running the query `select * from s3object[*] as s where s.request.header['User-Agent'] = 'test'`, which shows the error is not due to `[*]`:

```
$ aws s3api select-object-content --profile minio --endpoint-url $MINIO_ENDPOINT --bucket s3-select-1 --key test.json --input-serialization 'JSON={Type=LINES},CompressionType=NONE' --output-serialization 'JSON={}' --expression-type SQL --expression "select * from s3object[*] as s where s.request.header['User-Agent'] = 'test'" output
$ cat output
{"request":{"uri":"/1","header":{"User-Agent":"test"}}}
```

Regardless, if I change it to `s3object as s`, the query also works as expected:

```
$ aws s3api select-object-content --profile minio --endpoint-url $MINIO_ENDPOINT --bucket s3-select-1 --key test.json --input-serialization 'JSON={Type=LINES},CompressionType=NONE' --output-serialization 'JSON={}' --expression-type SQL --expression "select * from s3object as s where s.request.header['User-Agent'] = 'test'" output
$ cat output 
{"request":{"uri":"/1","header":{"User-Agent":"test"}}}
```

But, once I change the condition from an equality to a `IS NOT NULL`, I get the error about an invalid arithmetic operator:

```
$ aws s3api select-object-content --profile minio --endpoint-url $MINIO_ENDPOINT --bucket s3-select-1 --key test.json --input-serialization 'JSON={Type=LINES},CompressionType=NONE' --output-serialization 'JSON={}' --expression-type SQL --expression "select * from s3object as s where s.request.header['User-Agent'] is not null" output 

An error occurred (InternalError) when calling the SelectObjectContent operation: invalid arithmetic operator
```

**Comment by klauspost** [comment]
Thanks for testing. I will see if I can include it 👍🏼
