### ISSUE TITLE
When using nginx 443, I get The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by tombburnell** [minio/minio#14354]
I am trying to proxy my images on me minio server via nginx and while it works on http/80 it fails on https/443 with the  error:

<Error>
<Code>InvalidRequest</Code>
<Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
<Resource>/s3images/a5aaa4d4ed6cccf4a92082c06.jpg</Resource>
<RequestId/>
<HostId>61d9d5e6-088b-4207-a3a0-1eae8421d15f</HostId>
</Error>

My website also under the same nginx proxy but another URL is working fine.

I am currently using certbox for the ssl cert.

I am using a bucket called s3images which is set as public. My nginx config looks like this.

server {
    listen       80;
    listen       443 ssl;
    server_name  mysite.sly.io;
    ssl_certificate /etc/letsencrypt/live/artcore.sly.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/artcore.sly.io/privkey.pem; # managed by Certbot
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

     client_max_body_size 50M;

     # To disable buffering
     proxy_buffering off;
   location /s3images/ {
            auth_basic          off;

            proxy_pass http://localhost:9000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;
            
           

ubuntu 20
minio version RELEASE.2022-02-18T01-50-10Z
nginx -V
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled

**Comment by harshavardhana** [comment]
> `InvalidRequest` The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. /s3images/a5aaa4d4ed6cccf4a92082c06.jpg 61d9d5e6-088b-4207-a3a0-1eae8421d15f

well this is because your client is not sending right authorization header @tombburnell

**Comment by harshavardhana** [comment]
> I am using a bucket called s3images which is set as public. My nginx config looks like this.

how did you make your bucket public and are you using a persistent layer for MinIO? 

For example here

```
~ mc mb play/testbucket
~ mc cp /etc/hosts play/testbucket/
~ mc policy set public play/testbucket/
~ curl https://play.min.io/testbucket/hosts
127.0.0.1	localhost
127.0.1.1	nano

147.75.201.93  testbucket.play.min.io
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

And https://play.min.io is behind nginx and with certbot

```
server {
        listen 443 ssl default_server;
 	server_name play.min.io;

	ssl_certificate /home/play.min.io-certs/public.crt;
	ssl_certificate_key /home/play.min.io-certs/private.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers 'HIGH:!aNULL:!MD5';
  
	# To allow special characters in headers
 	ignore_invalid_headers off;
  	# Allow any size file to be uploaded.
   	# Set to a value such as 1000m; to restrict file size to a specific value
    	client_max_body_size 0;
     	# To disable buffering
      	proxy_buffering off;

	location / {
          proxy_request_buffering off;
	  proxy_set_header X-Real-IP $remote_addr;
	  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	  proxy_set_header X-Forwarded-Proto $scheme;
	  proxy_set_header Host $http_host;
	  
	  proxy_connect_timeout  300;
	  # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
          proxy_http_version 1.1;
	  proxy_set_header Connection "";
	  
	  proxy_pass https://play.min.io:9000;
	}
}
```

Looks like you have botched your local setup and using a persistent layer to preserve previous settings.

**Comment by tombburnell** [comment]
I created the bucket in the gui and selected public in the drop down option.

I’m  just trying to fetch the object (an image) via web browser. It works fine with http, do I need an auth header for https?

I haven’t touched any persistent layer options. 

is there any diagnostic info I can post from my minio setup?

**Comment by harshavardhana** [comment]
> I created the bucket in the gui and selected public in the drop down option.
> 
> I’m  just trying to fetch the object (an image) via web browser. It works fine with http, do I need an auth header for https?
> 
> I haven’t touched any persistent layer options. 
> 
> is there any diagnostic info I can post from my minio setup?
> 

There is nothing that you can, it just simply looks like you are not doing things right. 

From the browser perhaps you are sending a wrong request, i.e your code is adding a wrong authorization header.

**Comment by tombburnell** [comment]
Hmm I think I've figured it out. 
I have basic authentication on my website to keep it private for now and I think the basic-auth headers are causing the problem.

If I start with a fresh incognito browser then it works, but once I log into my website, the requests to minio start to fail.
I have basic auth disabled on the path in ngnix but I guess the headers are still being passed.

Why does that header cause a problem? Is there a workaround? Maybe I can get nginx to remove the header.

This is request header from chrome debug

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
**Authorization: Basic ZGFuOmRydW1uYmFzcw==**
Connection: keep-alive
Cookie: ph_phc_OB0ud9u8eQeSIDmKgal82BizbkylWTVEX77zC2sRYbk_posthog=%7B%22distinct_id%22%3A%2217f1486e9601211-09367b36df555d-36667401-384000-17f1486e9611283%22%2C%22%24device_id%22%3A%2217f1486e9601211-09367b36df555d-36667401-384000-17f1486e9611283%22%2C%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%2C%22%24referrer%22%3A%22%24direct%22%2C%22%24referring_domain%22%3A%22%24direct%22%2C%22%24sesid%22%3A%5B1645316860261%2C%2217f1486e9659b0-0553836d21c55f-36667401-384000-17f1486e966f2%22%5D%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24enabled_feature_flags%22%3A%7B%7D%7D
Host: mysite.sly.io
If-Modified-Since: Sun, 20 Feb 2022 00:25:00 GMT
If-None-Match: "2eab396ca8f4907a0219f1b5d245f5f0"
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Comment by tombburnell** [comment]
ok I've added the following to ngnix and now it is working

            proxy_set_header Authorization "";

**Comment by harshavardhana** [comment]
> **Authorization: Basic ZGFuOmRydW1uYmFzcw==**

you can't add your own authorization techniques when using MinIO @tombburnell

**Comment by wangglbj** [comment]
@harshavardhana  I have a similar problem when testing on the OpenShift cluster. is my command wrong? i didn't find my nginx config.  Thanks

```
# curl -H 'Authorization: Basic bWluaW86bWluaW8xMjM=' http://minio-api-velero.apps.symt01.com
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><Resource>/</Resource><RequestId></RequestId><HostId>412a029f-de23-4f51-8511-427afce56658</HostId></Error>
```

**Comment by klauspost** [comment]
@wangglbj Read the response above, and what the error message says:

Basic Auth is not a valid auth method for S3.
