### ISSUE TITLE
can't delete object

### ISSUE THREAD

**Issue by eunahbae** [minio/minio#14360]
**i try to delete an a object with minio client and minio-console ui 
but, the object is not deleted.**

**NOTE**
**We are using sparkapp, and we frequently use read/write parquet inside the app.
The app encountered an error(app crash)and tried to delete the path used by the app. But it cannot be deleted.**

```
/ #mc rm  --rescurvie ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat/pp-data/
Removing `ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat/pp-data/name=train/part-02095-e07a20b8-11c7-4d9e-8805-e0af7a502c09-c000-ce760145-fd97-4a00-b00b-c4c0ecc1e8b2.snappy.parquet`.
...

/ # mc ls ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat
[2022-02-21 05:30:44 UTC] 0B leaf-data/
[2022-02-21 05:30:44 UTC] 0B pp-data/

```

## Expected Behavior
The file should not be listed with the mc ls command

## Current Behavior
The file is listed after delete. It also exists on disk at server

## Possible Solution
There could be a probleme in the delete

## Steps to Reproduce (for bugs)
1)delete a file with mc delete
2)list files in bucket with mc tree
3)the file is not deleted

## Your Environment

* Version used (`minio-operator`): RELEASE.2022-01-08T03-11-54Z
* Environment name and version (e.g. kubernetes v1.20.8):  9 nodes
* Server type and version:  CentOS Linux release 7.9.2009 (Core) 
* Operating System and version (`uname -a`): 3.10.0-1160.el7.x86_64
* Link to your deployment file:

**Comment by dvaldivia** [comment]
moved this to the minio repo.

Do you have versioning enabled on that bucket?

**Comment by klauspost** [comment]
Please upgrade.

Does `mc ls --recursive --versions ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat` show anything?

**Comment by eunahbae** [comment]
We are not using versioning for that bucket. 
Should I enable versioning?

![image](https://user-images.githubusercontent.com/100104697/154911833-31ffc917-a8d8-49ce-85d4-47e446b2d3d2.png)
[output.txt](https://github.com/minio/minio/files/8107453/output.txt)

**Comment by klauspost** [comment]
@eunahbae No, if you don't need versioning, no need to enable.

Retry, but before that run `mc admin trace --all ai2 >tracelog.txt` and keep that running for the operation.

Please post the *correct* cli you used. `--rescurvie` is not a valid parameter.

Post your MinIO *server* setup. All details.

**Comment by harshavardhana** [comment]
> / #mc rm  --rescurvie ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat/pp-data/
> Removing `ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat/pp-data/name=train/part-02095-e07a20b8-11c7-4d9e-8805-e0af7a502c09-c000-ce760145-fd97-4a00-b00b-c4c0ecc1e8b2.snappy.parquet`.
> ...
> 
> / # mc ls ai2/dmd-data/official/dna-data/predict-data/1.3.12.28.x4/anocat
> [2022-02-21 05:30:44 UTC] 0B leaf-data/
> [2022-02-21 05:30:44 UTC] 0B pp-data/

top-level folders will exist if you have others object in that folder and also

**Comment by eunahbae** [comment]
--rescurvie was a typo. I wrote the command with --recursive.


Is there no solution to the problem that the object cannot be deleted?

**Comment by harshavardhana** [comment]
> --rescurvie was a typo. I wrote the command with --recursive.
> 
> Is there no solution to the problem that the object cannot be deleted?

You are only showing top level folders here. The object seems to be deleted already.

**Comment by harshavardhana** [comment]
> > --rescurvie was a typo. I wrote the command with --recursive.
> > Is there no solution to the problem that the object cannot be deleted?
> 
> You are only showing top level folders here. The object seems to be deleted already.

Also you must upgrade as a community user.
