### ISSUE TITLE
Minio sometimes timed out for unknown reason (cannot login, cannot put/get objects). Need helps to troubleshoot.

### ISSUE THREAD

**Issue by v-tamld2** [minio/minio#14361]
Recently our minio cluster has become quite unstable. The first symptom is that we could not login to console due to timeout at request `/api/v1/login/oauth2/auth` (we are using Keycloak as the IDP). Then uploading as well as retrieving objects via presigned url did not work either. After restarting, it works fine for about one day then the issue happens again.
## Expected Behavior
Minio should be stable.

## Current Behavior
It just randomly timed out. Sometimes we could login after several retries but sometimes retries didn't help. During that time, other operations also failed. We could not upload nor retrieve objects via presigned urls. Since it timed out when calling `/api/v1/login/oauth2/auth`, we guess the issue might be with the IDP. However our Keycloak as well as other services that also uses Keycloak are still running fine. We only found this type of logs during the failing period:
```
API: AssumeRoleWithWebIdentity()
Time: 09:38:53 UTC 02/18/2022
DeploymentID: bbc96650-2033-402f-ae31-c71d3f36d82a
RequestID: 16D4D7BD88482DD1
RemoteHost: 10.xxx.xxx.xxx
Host: xxx
UserAgent: Go-http-client/1.1
Error: .minio.sys/has incomplete body (cmd.IncompleteBody)
4: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
3: cmd/sts-handlers.go:508:cmd.(*stsAPIHandlers).AssumeRoleWithSSO()
2: cmd/sts-handlers.go:559:cmd.(*stsAPIHandlers).AssumeRoleWithWebIdentity()
1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```
The message is kind of vague so it would be great if anyone can provide us with some clues or directions to troubleshoot.
## Possible Solution
Do not have any solution other than to restart minio.

## Steps to Reproduce (for bugs)
Although it happens randomly, we could reproduce the same situation by trying to perform `speedtest` using minio client (`mc admin speedtest myminio`). Actually, speedtest on cli didn't work for us at all (on the other hand, running speedtest from console works just fine). It just kept running with no sign of progress. Then after we terminated the speed test, all of the operations timed out. At first we thought speed test was the cause but the problem still happens even when no speed test is performed.

## Regression
No

## Your Environment

* Version used (`minio --version`): we originally used `RELEASE.2021-10-27T16-29-42Z`, then the issue happened so we upgraded to `RELEASE.2022-02-07T08-17-33Z`, thinking upgrade would help but it did not.
* Server setup and configuration: minio cluster with 4 nodes on k8s, used NFS disk.

**Comment by klauspost** [comment]
This looks like a timeout or a disconnecting client. My guess would be internal connections that hang. You are take a look to see if you can identify the calls with `mc admin trace --all myminio`, but it will take some filtering to find the info.

We offer this kind of troubleshooting as part of our [subscription package](https://min.io/pricing).

Edit:

> NFS disk.

This is likely the cause of your problems. MinIO is for direct attached storage, others are "at your own risk".
