### ISSUE TITLE
V. slow object listing due to FetchOwner in S3 Gateway

### ISSUE THREAD

**Issue by McPonolith** [minio/minio#14379]
MinIO is incorrectly asking for owner information when listing objects, which can result in a slow down of 4-6x the normal query time.

---

When MinIO is running as a S3 Gateway, the following command:
```
    aws --debug --endpoint http://localhost:9000 s3 ls s3://XXX/YYY
```
Results in a request to MinIO with:
```
    http://localhost:9000/XXX?list-type=2&prefix=YYY&delimiter=%2F&encoding-type=url
```
However MinIO changes this query to:
```
    https://XXX.s3.dualstack.eu-west-2.amazonaws.com/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1000&prefix=YYY
```

We have observed that on some of our IAM roles, requesting the owner for each object, results in the query taking 4-6x longer (Outside of MinIO). We have yet to work out why this is the case as the result is still returned correctly, its under the same account, and they're both being passed in via ENV with session token. On some roles it returns immediately, on others it chugs on each page. This appears to be a AWS issue that we are running into.

However we would not be encountering this issue if MinIO did not incorrectly add the fetch-owners to the request, as we have no need to fetch the owners

---

The following commands also result in fetch-owner always being set to True

```
aws --debug --endpoint http://localhost:9000 s3api list-objects-v2 --bucket XXX --delimiter / --encoding-type url --max-items 1000 --prefix YYY/

http://localhost:9000/XXX?list-type=2&delimiter=%2F&encoding-type=url&prefix=YYY%2F

https://XXX.s3.dualstack.eu-west-2.amazonaws.com/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1000&prefix=YYY%2F
```

```
aws --debug --endpoint http://localhost:9000 s3api list-objects-v2 --bucket XXX --delimiter / --encoding-type url --no-fetch-owner --max-items 1000 --prefix YYY/

http://localhost:9000/XXX?list-type=2&delimiter=%2F&encoding-type=url&prefix=YYY%2F&fetch-owner=false

https://XXX.s3.dualstack.eu-west-2.amazonaws.com/?delimiter=%2F&amp;encoding-type=url&amp;fetch-owner=true&amp;list-type=2&amp;max-keys=1000&amp;prefix=YYY%2F&#34;
```

---

In order to extract the URL that MinIO was using to hit S3, we enabled Charles Proxy, which resulted in the certificate failing to validate and ended up printing out the URL that MinIO was using to communicate with S3. The url that aws-cli used to communicate with MinIO was extracted by running the above commands in debug mode.

MinIO was ran by first activating aws-vault and then running the following command:
```
docker run -e MINIO_ROOT_USER='minioadmin' -e MINIO_ROOT_PASSWORD='minioadmin'  -e AWS_ACCESS_KEY_ID -e  AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -p 9000:9000 -p 9001:9001 -it minio/minio:RELEASE.2021-11-09T03-21-45Z gateway s3 --console-address :9001
```
MinIO Version: RELEASE.2021-11-09T03-21-45Z

**Comment by klauspost** [comment]
Correct, minio will always fetch the remote owners.

**Comment by McPonolith** [comment]
Just to add this can make a request go from 2s to 11-21s. So while I understand it's low priority it might be high impact for some users. Im gonna look at solving it from the IAM side as I have no idea why a different role would cause such issues, but I have seen frequent issues about listing taking a while on these GitHub issues, for some, it might be due to this issue.

**Comment by harshavardhana** [comment]
We are not planning to change this, fetch-owner is added by default for Listobjects as it is needed for gateway.

We have never seen any issue with this with AWS S3. Looks like you need to talk to AWS S3 support about why fetch-owner is causing higher delays than without it.

**Comment by harshavardhana** [comment]
Adding to this AWS S3 gateway is in code freeze so there won't be any change for now.

**Comment by McPonolith** [comment]
It appears `s3:GetBucketOwnershipControls` was required. We had a rule to allow allow S3 actions, but then there was a whitelist in another role, which blocked this one.

Could we get `s3:GetBucketOwnershipControls` added to the minimum permissions as stated here https://docs.min.io/docs/minio-gateway-for-s3.html. Also I noticed `s3:HeadBucket` is no longer (if ever) a valid action.

The following minimum policy is what I have used and can verify works (without s3:GetBucketAcl listing objects are very slow)
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketAcl",
                "s3:GetObject",
                "s3:PutObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3::: mybucket",
                "arn:aws:s3::: mybucket/*"
            ]
        }
    ]
}
```
