### ISSUE TITLE
Minio not seeing certificate change

### ISSUE THREAD

**Issue by jrauti** [minio/minio#14377]
I'm building Minio cluster in order to test it. I have four node cluster running fine with Let's Encrypt certificates. I forced certificate update with certbot (on different server) and moved new certificates on place with rsync. I can't see Minio picking up the change even though I can see timestamp on files changing. Folder which is used is ~/.minio/certs and it seems to use them certs fine from there. With lsof I can see that Minio is monitoring something with fsnotify as it has anon_inode:inotify on /proc/fd. Is there way to debug this? /home/miniouser is on XFS filesystem which is on top of the LVM. 

## Expected Behavior
New certificate is supposed to found automatically and used. I can see change #5963 which is supposed to enable this. 

## Current Behavior
New certificate is not used. Restarting the server picks up the change. Tried this on one of the 4 nodes.

## Steps to Reproduce (for bugs)

1. Install Minio to AlmaLinux from RPM.
2. Should work as described. 
3.
4.

## Context
I'm trying to get certificate management as automatic as can be as Let's Encrypt certificates have short lifespan.

## Regression
Yes? 

## Your Environment
minio version RELEASE.2022-02-18T01-50-10Z
Linux on Vmware

AlmaLinux release 8.5 (Arctic Sphynx)

**Comment by klauspost** [comment]
Your filesystem may not supply change notifications. You can reload by sending `SIGHUP` to the process.

**Comment by jrauti** [comment]
Ok. I'm pretty sure that default is that notices are delived as systemd seems to doing it a lot. Anyway SIGHUP solution works and that is enough for me. Thanks.
