### ISSUE TITLE
mc admin speedtest abnormal behavior

### ISSUE THREAD

**Issue by lddlww** [minio/minio#14383]
**minio and mc version：**
```
minio version RELEASE.2022-02-12T00-51-25Z
mc version RELEASE.2022-02-13T23-26-13Z
```
**minio distribute cluster topology:**
```
8 minio nodes，24 drives per node
erasure set size：16
standary parity：2
```
**tolerance：**
```
tolerance node：1
tolerance drive（per erasure set）：2
```
**problem：**
when i stop one minio node，then use ```mc admin speedtest myminio --duration 1m```  for benchmark, but it always failed and return fast, and i use ```mc admin console myminio``` to check logs，it throw follow error：
```
10.2.16.7  API: ObjectSpeedtestHandler()
10.2.16.7  Time: 03:08:07 UTC 02/23/2022
10.2.16.7  DeploymentID: df5c01b8-c94c-409f-9f3a-6ff44285a60b
10.2.16.7  RequestID: 16D64B76415E1523
10.2.16.7  RemoteHost: 127.0.0.1
10.2.16.7  UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2022-02-13T23-26-13Z
10.2.16.7  Error: Storage resources are insufficient for the write operation .minio.sys/tmp/578a1592-e592-4842-a705-c3c0909bf270/f5428b1f-59e5-4127-8a37-5561bac7feab/part.1 (cmd.InsufficientWriteQuorum)
10.2.16.7         4: cmd/peer-rest-server.go:1210:cmd.selfSpeedtest.func2.2()
10.2.16.7         3: sync/once.go:68:sync.(*Once).doSlow()
10.2.16.7         2: sync/once.go:59:sync.(*Once).Do()
10.2.16.7         1: cmd/peer-rest-server.go:1208:cmd.selfSpeedtest.func2()
```

however i use ```mc cp x.test myminio/test```  it always successfully，so i am confused about ```mc admin speedtest``` behavior, does it bugs?

**Comment by harshavardhana** [comment]
It is not abnormal, it is expected to see the actual peak with the workload of speedtest and it logs these errors that's when it has reached the peak.

**Comment by lddlww** [comment]
thanks for reply

however ```mc admin speedtest``` return fast and nothing put and get operate，like follow：
```
        THROUGHPUT      IOPS
PUT     0 B/s   0 objs/s
GET     0 B/s   0 objs/s

Speedtest: MinIO 2022-02-12T00:51:25Z, 8 servers, 192 drives, 64 MiB objects, 20 threads
```

```
 time  mc admin speedtest myminio --duration 10m

        THROUGHPUT      IOPS
PUT     0 B/s   0 objs/s
GET     0 B/s   0 objs/s

Speedtest: MinIO 2022-02-12T00:51:25Z, 8 servers, 192 drives, 64 MiB objects, 20 threads

real    0m5.629s
user    0m0.045s
sys     0m0.013s
```

**Comment by harshavardhana** [comment]
> when i stop one minio node，then use `mc admin speedtest myminio --duration 1m` for benchmark, but it always failed and return fast, and i use `mc admin console myminio` to check logs，it throw follow error：

if you stop a node in an 8 node configuration we do not have the necessary quorum to perform writes, speed test is not designed for this kind of situation. 

It is meant to benchmark a running system not when you are taking down nodes changing parity by reducing the overall tolerance etc. 

Benchmark when all nodes are up.

**Comment by harshavardhana** [comment]
> time  mc admin speedtest myminio --duration 10m

Also this is bogus value you don't have to run for 10mins you get results by just running default configuration i.e with autotuning.

**Comment by lddlww** [comment]
but when i use ```mc cp``` it work

**Comment by lddlww** [comment]
> however i use `mc cp x.test myminio/test` it always successfully

i always return ok

**Comment by harshavardhana** [comment]
of course it will work @lddlww but speedtest requires all peers online to run

**Comment by lddlww** [comment]
when i use ```minio version RELEASE.2022-02-07T08-17-33Z``` version，i stop one minio node, speedtest works normally
```
time mc admin speedtest myminio --duration 5m -v

   	THROUGHPUT   	IOPS         
PUT	306 MiB/s	4 objs/s	
GET	458 MiB/s	7 objs/s	

Speedtest: MinIO 2022-02-07T08:17:33Z, 4 servers, 4 drives, 64 MiB objects, 24 threads

PUT:
   * http://10.5.17.100:9022: 99 MiB/s 1 objs/s
   * http://10.5.17.97:9022: 0 B/s 0 objs/s
 error: /speedtest "http://10.5.17.97:9022/minio/peer/v20": remote server offline   * http://10.5.17.98:9022: 105 MiB/s 1 objs/s
   * http://10.5.17.99:9022: 102 MiB/s 1 objs/s
GET:
   * http://10.5.17.100:9022: 140 MiB/s 2 objs/s
   * http://10.5.17.97:9022: 0 B/s 0 objs/s
 error: /speedtest "http://10.5.17.97:9022/minio/peer/v20": remote server offline   * http://10.5.17.98:9022: 159 MiB/s 2 objs/s
   * http://10.5.17.99:9022: 159 MiB/s 2 objs/s

real	10m20.793s
user	0m3.175s
sys	0m2.007s
```

**Comment by harshavardhana** [comment]
> time mc admin speedtest myminio --duration 5m -v
> 
>    	THROUGHPUT   	IOPS         
> PUT	306 MiB/s	4 objs/s	
> GET	458 MiB/s	7 objs/s	
> 
> Speedtest: MinIO 2022-02-07T08:17:33Z, 4 servers, 4 drives, 64 MiB objects, 24 threads
> 
> PUT:
>    * http://10.5.17.100:9022: 99 MiB/s 1 objs/s
>    * http://10.5.17.97:9022: 0 B/s 0 objs/s
>  error: /speedtest "http://10.5.17.97:9022/minio/peer/v20": remote server offline   * http://10.5.17.98:9022: 105 MiB/s 1 objs/s
>    * http://10.5.17.99:9022: 102 MiB/s 1 objs/s
> GET:
>    * http://10.5.17.100:9022: 140 MiB/s 2 objs/s
>    * http://10.5.17.97:9022: 0 B/s 0 objs/s
>  error: /speedtest "http://10.5.17.97:9022/minio/peer/v20": remote server offline   * http://10.5.17.98:9022: 159 MiB/s 2 objs/s
>    * http://10.5.17.99:9022: 159 MiB/s 2 objs/s
> 
> real	10m20.793s
> user	0m3.175s
> sys	0m2.007s

this is not normal - if you think this is normal then you don't understand the reason for benchmarks.

**Comment by lddlww** [comment]
> this is not normal - if you think this is normal then you don't understand the reason for benchmarks.

it won't throw the ```insufficient for write operation error``` which likely erasure set can't write:（i stop two minio nodes）
```
time mc admin speedtest myminio --duration 5m -v

   	THROUGHPUT	IOPS         
PUT	0 B/s 	0 objs/s	
GET	0 B/s 	0 objs/s	

Speedtest: MinIO 2022-02-07T08:17:33Z, 4 servers, 4 drives, 64 MiB objects, 24 threads

PUT:
   * http://10.5.17.100:9022: 0 B/s 0 objs/s
 error: Storage resources are insufficient for the write operation .minio.sys/tmp/3112dad1-f237-4894-b93f-eb544a2997df/42884bbd-d58b-4833-9c35-ba5641e831fb/p
 error: /speedtest "http://10.5.17.97:9022/minio/peer/v20": remote server offline   * http://10.5.17.98:9022: 0 B/s 0 objs/s
 error: /speedtest "http://10.5.17.98:9022/minio/peer/v20": remote server offline   * http://10.5.17.99:9022: 0 B/s 0 objs/s
 error: Storage resources are insufficient for the write operation .minio.sys/tmp/4c8a5399-df7f-4261-929b-c61eb8a7a940/234f9f24-f48c-4ff5-86ba-8e7145c8605d/p
   * http://10.5.17.100:9022: 0 B/s 0 objs/s
 error: Storage resources are insufficient for the write operation .minio.sys/tmp/3112dad1-f237-4894-b93f-eb544a2997df/42884bbd-d58b-4833-9c35-ba5641e831fb/p
 error: /speedtest "http://10.5.17.97:9022/minio/peer/v20": remote server offline   * http://10.5.17.98:9022: 0 B/s 0 objs/s
 error: /speedtest "http://10.5.17.98:9022/minio/peer/v20": remote server offline   * http://10.5.17.99:9022: 0 B/s 0 objs/s

real	0m4.101s
user	0m0.069s
sys	0m0.050s

```

**Comment by lddlww** [comment]
in  ```minio version RELEASE.2022-02-12T00-51-25Z``` version,  i stop one minio node that not beyond ```erasure set quorum```; however, after i use ```mc admin speedtest```, the output logs throw ```Storage resources are insufficient for the write operation``` error which likely erasure set can't write

**Comment by harshavardhana** [comment]
I ran a 12 node setup

```
#!/bin/bash

set -x

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
export MINIO_STORAGE_CLASS_STANDARD=EC:4
export MINIO_PROMETHEUS_AUTH_TYPE="public"
export MINIO_API_DELETE_CLEANUP_INTERVAL="5s"
export MINIO_CI_CD=1

killall -9 minio
# rm -rf /tmp/dist

scheme="http"
nr_servers=12

args=""
for ((i=0;i<$[${nr_servers}];i++)); do
    addr="127.0.0.1"
    args="$args $scheme://$addr:$[9100+$i]/tmp/dist/path1/$i"
done

echo $args


for ((i=0;i<$[${nr_servers}];i++)); do
    access="minio"
    secret="minio123"
    (MINIO_ACCESS_KEY=${access} MINIO_SECRET_KEY=${secret} ./minio server --address ":$[9100+$i]" $args 2>&1 | tee /tmp/log$i.txt) &
done
```

And then took one of the servers down 

```
mc support perf test1 --size 4k

        THROUGHPUT      IOPS       
PUT     1.7 MiB/s       440 objs/s
GET     2.0 MiB/s       515 objs/s

Speedtest: MinIO 2022-02-22T18:59:28Z, 12 servers, 12 drive, 3.9 KiB object, 8 threads
```

No issues everything works, In your case what is happening is you have EC:2 which is very close to the quorum ratio so removing a node means you have 2 parity gone, now you do not have anymore drives left for parity which essentially means we will fail to perform I/O even if one of the disk goes offline in the middle of the I/O.

From `mc admin speedtest` results it shows that you have a very poor setup with poor networking etc.

**Comment by lddlww** [comment]
> 8 minio nodes，24 drives per node
> erasure set size：16
> standary parity：2

thanks for your patience，however according to https://min.io/product/erasure-code-calculator， this topology can tolerance 1 node or 2 drives（per erasure set）fails， but it seems not

did i miss something？

**Comment by harshavardhana** [comment]
> thanks for your patience，however according to [https://min.io/product/erasure-code-calculator，](https://min.io/product/erasure-code-calculator%EF%BC%8C) this topology can tolerance 1 node or 2 drives（per erasure set）fails， but it seems not

Your setup is wrong @lddlww as explained in a separate discussion. You do not have the correct setup for the right HA.

**Comment by lddlww** [comment]
how can i set to satisfy right HA？

**Comment by lddlww** [comment]
reference to minio calculator result，it can tolerance 1 node or 2 drives fails，and minio cluster could be write continually ， is it right？
![image](https://user-images.githubusercontent.com/27006237/155445306-bab24c38-87fa-4c17-a537-30d433a22542.png)

**Comment by harshavardhana** [comment]
> reference to minio calculator result，it can tolerance 1 node or 2 drives fails，and minio cluster could be write continually ， is it right？

This is correct when you make sure you have right setup.

**Comment by lddlww** [comment]
@harshavardhana  thank you very much
