### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by Muhammad02468** [minio/minio#14407]
@harshavardhana 
Hello and good day to you!

I'm facing the issue of accessing the objects via share URL. I have tried by minio console >> bucket>>object>>share, as well as mc share but both URLs, give the same signature issue.

Please help me out in solving the problem.
--------------------------------------------------------------------------------
Error in browser:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>Farewell.xlsx</Key>
<BucketName>usman-test</BucketName>
<Resource>/usman-test/Farewell.xlsx</Resource>
<RequestId>16D6CB957EB4717A</RequestId>
<HostId>77d151bf-5c6d-4081-8edf-c5eab75b41d5</HostId>
<script/>
</Error>
----------------------------------------------------------------------------------

root@minio:/mnt/disk1/minio# mc ls minio/usman-test
[2022-02-09 07:41:31 UTC]  14KiB STANDARD EID DUTIES .ods
[2022-02-09 07:41:31 UTC]  75KiB STANDARD Escalation_matrix (10-08-2021) - LATEST.XLSX
[2022-02-09 07:41:31 UTC] 8.3KiB STANDARD Farewell Funds.xlsx
[2022-02-09 07:41:31 UTC] 9.9KiB STANDARD Farewell.xlsx
[2022-02-10 04:54:38 UTC] 802KiB STANDARD ngn and video.xlsx

root@minio:/mnt/disk1/minio# mc share download minio/usman-test/Farewell.xlsx
URL: http://192.168.12.4:9000/usman-test/Farewell.xlsx
Expire: 7 days 0 hours 0 minutes 0 seconds
Share: http://192.168.12.4:9000/usman-test/Farewell.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20220224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220224T180806Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&versionId=505f1962-006a-4ed4-90f2-adb01f1c27c7&X-Amz-Signature=acc9448929400d68a65d89b97d6466cb6e65ab772d9be6c65eec5732bc150ced

root@minio:/mnt/disk1/minio# minio --version
minio version RELEASE.2022-02-07T08-17-33Z

root@minio:/mnt/disk1/minio# curl http://192.168.12.4:9000/usman-test/Farewell.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20220224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220224T180806Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&versionId=505f1962-006a-4ed4-90f2-adb01f1c27c7&X-Amz-Signature=acc9448929400d68a65d89b97d6466cb6e65ab772d9be6c65eec5732bc150ced -v
[1] 152571
[2] 152572
[3] 152573
[4] 152574
[5] 152576
[6] 152578
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
X-Amz-Expires=604800: command not found
X-Amz-Date=20220224T180806Z: command not found
X-Amz-SignedHeaders=host: command not found
X-Amz-Credential=minioadmin%2F20220224%2Fus-east-1%2Fs3%2Faws4_request: command not found
X-Amz-Signature=acc9448929400d68a65d89b97d6466cb6e65ab772d9be6c65eec5732bc150ced: command not found
[1]   Exit 23                 curl http://192.168.12.4:9000/usman-test/Farewell.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256
[2]   Exit 127                X-Amz-Credential=minioadmin%2F20220224%2Fus-east-1%2Fs3%2Faws4_request
[3]   Exit 127                X-Amz-Date=20220224T180806Z
[4]   Exit 127                X-Amz-Expires=604800
[5]-  Exit 127                X-Amz-SignedHeaders=host
[6]+  Done                    versionId=505f1962-006a-4ed4-90f2-adb01f1c27c7

----------------------------------------------------------------------------------
"minio": {
                        "url": "http://192.168.12.4:9000",
                        "accessKey": "minioadmin",
                        "secretKey": "123@123@123",
                        "api": "s3v4",
                        "path": "auto"
----------------------------------------------------------------------------------

**Comment by harshavardhana** [comment]
You should quote the URL for curl command.

And do not tag developers
