### ISSUE TITLE
LDAP user under Principal

### ISSUE THREAD

**Issue by titansmc** [minio/minio#14413]
## Expected Behavior
LDAP user in bucket policy would work like:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
       "AWS": [
        "arn:aws:iam::user=cn=Joe Smith,cn=Users,dc=domain,dc=org"
       ]
      },
      "Action": "s3:ListBucket",
      "Resource": [
        "arn:aws:s3:::mur"
      ],
      "Sid": ""
    }
  ]
}
```

## Current Behavior
it doesn't work

## Steps to Reproduce (for bugs)
Just apply a policy like this to a cluster that configures LDAP

## Regression
don't know

## Your Environment

* Version used (`minio --version`): 2022-02-07T08:17:33Z

**Comment by harshavardhana** [comment]
We do not support Principals other than anonymous users, principals  are AWS concept we do not carry them in our implementation.
