### ISSUE TITLE
MINIO_IDENTITY_OPENID_CLAIM_NAME possible values

### ISSUE THREAD

**Issue by dmoreira97DLTT** [minio/minio#14412]
Hello all.

As the docs state, the env var "MINIO_IDENTITY_OPENID_CLAIM_NAME" can be of type:

> string or []string or comma_separated_value
(https://docs.min.io/docs/minio-sts-quickstart-guide.html)

I'm using an helm installation of MinIO chart and seem to be unable to assign any value other than a simple string to this var. My objective is to have something like "policy, groups", in order to look for policies according to the groups a user is a member of and to have a default policy for users that aren't in any group yet. For a better context, here's the chart relevant part:

```
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "[policy,groups]"
```

I've tried all kinds of lists, arrays, csv and strings, but nothing seems to be accepted.

## Expected Behavior

The expected behavior would be for the env var to accept the list and look for policies according to the list elements' values. In this case, to look for a default policy and then for policies matching the groups' names.

## Current Behavior

The env var only does one of each separately once it only accepts a simple string as values. If set to "policy" it looks for the desired policy, if set to "groups" it looks for policies matching the groups present in the jwt token, and the same for "roles".

If there's any more info needed, feel free to ask for it.

Any help would be greatly appreciated, thanks.

**Comment by harshavardhana** [comment]
CLAIM_NAME can be just one, the corresponding JWT can have `[]string` and `comma separated values`
