### ISSUE TITLE
Possible disk leak?

### ISSUE THREAD

**Issue by xxhdx1985126** [minio/minio#14422]
During our minio fault-tolerance tests, we found the following issue:

If we go through the following steps, a disk may not be discovered by other nodes in the cluster.

1. stop minio;
2. umount a disk;
3. start minio;
4. format the unmounted disk;
5. mount the disk again;

After the above steps, although the umounted disk can be healed on re-mount, no later object puts would take effects on that disk, and other nodes keep poping up the error: 
`Error: Following error has been printed 3 times.. Disk: http://XXX.XXX.XXX.XXX:9199/data01/minio returned Unexpected RPC call at this path '/minio/storage/data01/minio/v43/readall' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (XXXXXXXXX) (*fmt.wrapError)`

After some source code reading, we think that this is because the umounted disk related RPCs are not registered on minio started because it's not online and will not be registered on disk connect.

The version we were testing was: RELEASE.2021-12-29T06-49-06Z

## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Possible Solution
Register disk RPCs even if disks are offline, or register disk rpc on disk connected

## Steps to Reproduce (for bugs)

1. stop minio;
2. umount a disk;
3. start minio;
4. format the unmounted disk;
5. mount the disk again;

## Your Environment

* Version used (`minio --version`): RELEASE.2021-12-29T06-49-06Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
This completely looks like an incorrect setup, what you are describing doesn't make sense.

However please upgrade to the latest.
