### ISSUE TITLE
The Usage and Total Object Usage of the miniO dashboard should be the same as the actual disk Usage

### ISSUE THREAD

**Issue by shizhiliuyu** [minio/minio#14421]
**Is your feature request related to a problem? Please describe.**
The Usage and Total Object Usage of the MiniO dashboard are incorrect
**Describe the solution you'd like**
The Usage and Total Object Usage of the MiniO dashboard are incorrect

**Describe alternatives you've considered**
The Usage and Total Object Usage of the miniO dashboard should be the same as the actual disk Usage
**Additional context**
![HXW}YIACQB)XXKOQZXQ29T](https://user-images.githubusercontent.com/93238483/155912736-6db86aea-144b-458b-85ed-1884600ba042.png)

**Comment by harshavardhana** [comment]
Actual disk usage calculates parity as well. The usage on dashboard is an ever growing value that gets calculated to the real value of your actual "objects" on the namespace.

So what it is showing is the exact value of usage on the cluster in terms of your objects. 

Disk space calculation is something you do on top of it per node level to monitor disk space utilization.

**Comment by shizhiliuyu** [comment]
Does going to the data directory directly through the mv command affect the actual display indicator

**Comment by hc930914** [comment]
Without using the MV command, I checked the disk space of the host computer, which occupied 300g, but the Minio dashboard only showed 50g. Is there any way to solve this problem

**Comment by harshavardhana** [comment]
> Without using the MV command, I checked the disk space of the host computer, which occupied 300g, but the Minio dashboard only showed 50g. Is there any way to solve this problem

yes that is because there is a lot of storage space filesystem uses such as per object there are extra 4k blocks used etc. so of course, it will be higher than your actual objects that are uploaded.  you upload a lot of tiny objects this is expected. 

you are simply not aware of how filesystems usage is calcuated.

**Comment by hc930914** [comment]
My image storage is incremental. The incremental data of one day is about 50g, which was counted as 50g last Friday. So far, it has not changed
