### ISSUE TITLE
Notification events for AMQP are not functioning or configurable

### ISSUE THREAD

**Issue by nathanjent** [minio/minio#14433]
## Expected Behavior

I configure an AMQP notification to RabbitMQ using environment variables for the MinIO Docker container. An SQS ARN is displayed in the MinIO logs: `arn:minio:sqs::_:amqp`. I add a "put" event to a bucket using the ARN.  I receive messages in RabbitMQ whenever an object is uploaded to the bucket.

## Current Behavior

I configure an AMQP notification to RabbitMQ using environment variables for the MinIO Docker container. The SQS ARN is not displayed in the logs. I get the following error when attempting to add a notification event to the bucket using the expected ARN: `arn:minio:sqs::_:amqp`.

    mc.exe: <ERROR> Unable to enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.

## Steps to Reproduce (for bugs)

Follow the steps in this guide: https://docs.min.io/minio/baremetal/monitoring/bucket-notifications/publish-events-to-amqp.html

1. Set configuration for an AMQP notification
2. Restart MinIO to check that SQS ARN is displayed
3. Create a bucket
4. Attempt to add an event to the bucket

## Context

Upload notifications are no longer being sent to our message queue service, RabbitMQ.

## Regression
Is this issue a regression? Yes

I have determined that the bug was introduced in this release: https://github.com/minio/minio/releases/tag/RELEASE.2022-02-12T00-51-25Z.

## Your Environment

* Version used (`minio --version`):
  RELEASE.2022-02-12T00-51-25Z or latest

* Server setup and configuration:

      # This is the service defined in Docker compose

      s3:
        image: quay.io/minio/minio:RELEASE.2022-02-12T00-51-25Z
        command: server /data --console-address=:9001 --certs-dir=/etc/minio/ssl/
        restart: always
        depends_on:
            - mq
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
            MINIO_NOTIFY_AMQP_ENABLE_mq: 'on'
            MINIO_NOTIFY_AMQP_URL_mq: 'amqp://guest:guest@mq:5672'
            MINIO_NOTIFY_AMQP_EXCHANGE_mq: amq.direct
            MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_mq: direct
            MINIO_NOTIFY_AMQP_ROUTING_KEY_mq: dev-newjob
            MINIO_NOTIFY_AMQP_MANDATORY_mq: 'off'
            MINIO_NOTIFY_AMQP_DURABLE_mq: 'on'
            MINIO_NOTIFY_AMQP_COMMENT_mq: "RabbitMQ settings"
        volumes:
            - s3_data:/data
            - ./.certs/s3-key.pem:/etc/minio/ssl/private.key:ro
            - ./.certs/s3.pem:/etc/minio/ssl/public.crt:ro
        ports:
            - 9000:9000
            - 9001:9001

* Operating System and version (`uname -a`):
  Running the official container images from quay.io using Docker.

**Comment by harshavardhana** [comment]
Please use latest release @nathanjent

**Comment by nathanjent** [comment]
> Please use latest release @nathanjent

I am seeing the same issue with the latest release of the container image: RELEASE.2022-02-26T02-54-46Z

**Comment by harshavardhana** [comment]
> I am seeing the same issue with the latest release of the container image: RELEASE.2022-02-26T02-54-46Z

Thanks @nathanjent 

> I configure an AMQP notification to RabbitMQ using environment variables for the MinIO Docker container. The SQS ARN is not displayed in the logs. I get the following error when attempting to add a notification event to the bucket using the expected ARN: `arn:minio:sqs::_:amqp`.

The event notification here is wrong you are using `_mq` and but using a default SQS ARN - you should first get the right ARN from the server banner or `mc admin info --json` output @nathanjent 

Your SQS ARN will be `arn:minio:sqs::mq:amqp`

**Comment by harshavardhana** [comment]
Closing this issue since you have used an incorrect ARN

**Comment by nathanjent** [comment]
> > I configure an AMQP notification to RabbitMQ using environment variables for the MinIO Docker container. The SQS ARN is not displayed in the logs. I get the following error when attempting to add a notification event to the bucket using the expected ARN: `arn:minio:sqs::_:amqp`.
> 
> The event notification here is wrong you are using `_mq` and but using a default SQS ARN - you should first get the right ARN from the server banner or `mc admin info --json` output @nathanjent
> 
> Your SQS ARN will be `arn:minio:sqs::mq:amqp`

Sorry. I should have been more consistent in my report. I must have copied the `arn:minio:sqs::_:amqp` ARN during my previous configuration. I tried to run both with a notification identifier and without. 

I am currently testing with the `_mq` appended to the environment variables and attempting to add an event with `mc event add docker/dev-job arn:minio:sqs::mq:amqp --event put` but the logs do not print the SQS ARN on startup and I still receive this error:

    mc.exe: <ERROR> Unable to enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.

**Comment by harshavardhana** [comment]
Looks like similar to #14451 will get back
