### ISSUE TITLE
Permission Error on btrfs subvolumes

### ISSUE THREAD

**Issue by LinTechSo** [minio/minio#14431]
## Expected Behavior
upload files on minio would succeed.
## Current Behavior
get " We encountered an internal error, please try again.: cause(Rename across devices not allowed, please fix your backend configuration" error
## Steps to Reproduce (for bugs)
1. mkdir /export/bucket_test  (bucket)
2. btrfs subvolume create /export/bucket_test/dir_test
3. try upload files in minio ui on dir_test path

##Your Environment
minio latest version

logs:
API: SYSTEM()
Time: 09:07:53 UTC 03/01/2022
DeploymentID: ec16481e-c9e7-47dd-84c2-44024827ee97
Error: Rename across devices not allowed, please fix your backend configuration (/export/.minio.sys/tmp/1471526d-bc2b-4107-bb11-90be30b0661e/2536b148-6582-4f84-8341-84d4d57b89da)->(/export/test/digi/test-job.yaml) (*fmt.wrapError)
       3: cmd/web-handlers.go:2428:cmd.toWebAPIError()
       2: cmd/web-handlers.go:2438:cmd.writeWebErrorResponse()
       1: cmd/web-handlers.go:1323:cmd.(*webAPIHandlers).Upload()

API: SYSTEM()
Time: 09:07:53 UTC 03/01/2022
DeploymentID: ec16481e-c9e7-47dd-84c2-44024827ee97
Error: Rename across devices not allowed, please fix your backend configuration (/export/.minio.sys/tmp/1471526d-bc2b-4107-bb11-90be30b0661e/2536b148-6582-4f84-8341-84d4d57b89da)->(/export/test/digi/test-job.yaml) (*fmt.wrapError)
       5: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
       4: cmd/api-errors.go:2034:cmd.toAPIError()
       3: cmd/web-handlers.go:2429:cmd.toWebAPIError()
       2: cmd/web-handlers.go:2438:cmd.writeWebErrorResponse()
       1: cmd/web-handlers.go:1323:cmd.(*webAPIHandlers).Upload()

I can verify that within the container, I can access and write to that path:
ls -la /export/test/digi 
drwxrwxrwx 1 root root  0 Feb 28 21:44 digi

**Comment by harshavardhana** [comment]
> get " We encountered an internal error, please try again.: cause(Rename across devices not allowed, please fix your backend configuration" error

As mentioned here we do not allow you having multiple different sub-volumes - we do not support that - for us entiry volume that is presented should be a single volume.

**Comment by harshavardhana** [comment]
> (*fmt.wrapError)
> 5: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
> 4: cmd/api-errors.go:2034:cmd.toAPIError()
> 3: cmd/web-handlers.go:2429:cmd.toWebAPIError()
> 2: cmd/web-handlers.go:2438:cmd.writeWebErrorResponse()
> 1: cmd/web-handlers.go:1323:cmd.(*webAPIHandlers).Upload()

Also this is not the latest version - we do not have this code anymore and has been not there for more than 1yr.

**Comment by LinTechSo** [comment]
minio needs write permission on btrfs subvolume.

**Comment by LinTechSo** [comment]
hi @harshavardhana, thanks. so what should we do? actually, we need this scenario to store isolated users' data in different subvolumes with a specific quota (looking for tenant disk usage detail). is there any alternative solution? is there any way to expose the directory per bucket usage metrics in minio ?
