### ISSUE TITLE
Distributed minio Error Logs 

### ISSUE THREAD

**Issue by wybaron** [minio/minio#14439]
## Deployment mode
```bash
./minio --config-dir /etc/MinIO/data1 server --address :9001 \
http://172.27.12.6{1...4}/mnt/minio1/DATA1 \
http://172.27.12.6{1...4}/mnt/minio2/DATA1 \
http://172.27.12.6{1...4}/mnt/minio3/DATA1 \
http://172.27.12.6{1...4}/mnt/minio4/DATA1
```

## Log source

![image](https://user-images.githubusercontent.com/19605510/156286770-91eb3486-53bb-40c7-b536-af54700c3ba7.png)

```bash
# mc admin info Devops
●  172.27.12.61:9001
   Uptime: 1 hour
   Version: 2022-02-18T01:50:10Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1st

●  172.27.12.62:9001
   Uptime: 1 hour
   Version: 2022-02-18T01:50:10Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1st

●  172.27.12.63:9001
   Uptime: 1 hour
   Version: 2022-02-18T01:50:10Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1st

●  172.27.12.64:9001
   Uptime: 1 hour
   Version: 2022-02-18T01:50:10Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1st

4.8 TiB Used, 2 Buckets, 232 Objects
16 drives online, 0 drives offline

```

## Verbose logs
```bash
API: SYSTEM
Time: 08:52:14:0
Error: Marking http://172.27.12.64:9001/minio/storage/mnt/minio2/DATA1/v43 temporary offline; caused by Post "http://172.27.12.64:9001/minio/storage/mnt/minio2/DATA1/v43/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 172.27.12.64:9001: connect: connection refused (*fmt.wrapError)
internal/rest/client.go:151:rest.(*Client).Call()
cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
cmd/format-erasure.go:387:cmd.loadFormatErasure()
cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM
Time: 08:52:14:0
Error: Marking http://172.27.12.64:9001/minio/storage/mnt/minio3/DATA1/v43 temporary offline; caused by Post "http://172.27.12.64:9001/minio/storage/mnt/minio3/DATA1/v43/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 172.27.12.64:9001: connect: connection refused (*fmt.wrapError)
internal/rest/client.go:151:rest.(*Client).Call()
cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
cmd/format-erasure.go:387:cmd.loadFormatErasure()
cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM
Time: 08:52:14:0
Error: Marking http://172.27.12.64:9001/minio/storage/mnt/minio4/DATA1/v43 temporary offline; caused by Post "http://172.27.12.64:9001/minio/storage/mnt/minio4/DATA1/v43/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 172.27.12.64:9001: connect: connection refused (*fmt.wrapError)
internal/rest/client.go:151:rest.(*Client).Call()
cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
cmd/format-erasure.go:387:cmd.loadFormatErasure()
cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```
## Issues that require assistance
- How to customize the time zone in which logs are displayed?
```Time: 08:52:14:0```

- What causes errors in the logs and how to fix them？
```bash
Marking http://172.27.12.64:9001/minio/storage/mnt/minio4/DATA1/v43 temporary offline; caused by Post "http://172.27.12.64:9001/minio/storage/mnt/minio4/DATA1/v43/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 172.27.12.64:9001: connect: connection refused (*fmt.wrapError)
```

**Comment by harshavardhana** [comment]
> * `Time: 08:52:14:0`
> *

Time is displayed in UTC. 

> ```shell
> Error: Marking http://172.27.12.64:9001/minio/storage/mnt/minio4/DATA1/v43 temporary offline; caused by Post "http://172.27.12.64:9001/minio/storage/mnt/minio4/DATA1/v43/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 172.27.12.64:9001: connect: connection refused (*fmt.wrapError)
> ```

Your server is not reachable here 

> ```shell
> ./minio --config-dir /etc/MinIO/data1 server --address :9001 \
> http://172.27.12.6{1...4}/mnt/minio1/DATA1 \
> http://172.27.12.6{1...4}/mnt/minio2/DATA1 \
> http://172.27.12.6{1...4}/mnt/minio3/DATA1 \
> http://172.27.12.6{1...4}/mnt/minio4/DATA1
> ```

This is a poor way to set up you should simply do, WIPE all your drives and re-do your setup like this. 

```
 ./minio --config-dir /etc/MinIO/data1 server --address :9001 http://172.27.12.6{1...4}/mnt/minio{1...4}/DATA1
```

**Comment by wybaron** [comment]
- I want to change this time zone to non-UTC format, how should I change it?
- I already have a lot of data and can't make adjustments for a short period of time.opposite,I'm more concerned about why this happens, Other nodes do not have similar error logs

**Comment by harshavardhana** [comment]
> * I want to change this time zone to non-UTC format, how should I change it?

No, you cannot

> * I already have a lot of data and can't make adjustments for a short period of time.opposite,I'm more concerned about why this happens, Other nodes do not have similar error logs

You haven't shared all your logs here @wybaron please do so otherwise there is no other way for me to help you here.

**Comment by wybaron** [comment]
Thank you for your answer!

log:
```bash
Status: 16 Online, 0 Offline.
API: http://172.27.12.61:9001 http://172.17.0.1:9001 http://127.0.0.1:9001
Console: http://172.27.12.61:19001 http://172.17.0.1:19001 http://127.0.0.1:19001
Documentation: https://docs.min.io

API: SYSTEM
Time: 02:02:06:0
DeploymentID: ad30d2b2-c031-49e4-b779-de02a585338c
Error: Marking http://172.27.12.62:9001/minio/lock/v7 temporary offline; caused by Post "http://172.27.12.62:9001/minio/lock/v7/lock?": dial tcp 172.27.12.62:9001: connect: connection refused (*fmt.wrapError)
internal/rest/client.go:151:rest.(*Client).Call()
cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).Lock()
internal/dsync/drwmutex.go:404:dsync.lock.func1()

API: SYSTEM
Time: 02:02:10:0
DeploymentID: ad30d2b2-c031-49e4-b779-de02a585338c
Error: Marking http://172.27.12.63:9001/minio/lock/v7 temporary offline; caused by Post "http://172.27.12.63:9001/minio/lock/v7/lock?": dial tcp 172.27.12.63:9001: connect: connection refused (*fmt.wrapError)
internal/rest/client.go:151:rest.(*Client).Call()
cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).Lock()
internal/dsync/drwmutex.go:404:dsync.lock.func1()

API: SYSTEM
Time: 02:02:13:0
DeploymentID: ad30d2b2-c031-49e4-b779-de02a585338c
Error: Marking http://172.27.12.64:9001/minio/lock/v7 temporary offline; caused by Post "http://172.27.12.64:9001/minio/lock/v7/lock?": read tcp 172.27.12.61:25016->172.27.12.64:9001: read: connection reset by peer (*fmt.wrapError)
internal/rest/client.go:151:rest.(*Client).Call()
cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).Lock()
internal/dsync/drwmutex.go:404:dsync.lock.func1()
```

**Comment by harshavardhana** [comment]
> ```shell
> API: SYSTEM
> Time: 02:02:06:0
> DeploymentID: ad30d2b2-c031-49e4-b779-de02a585338c
> Error: Marking http://172.27.12.62:9001/minio/lock/v7 temporary offline; caused by Post "http://172.27.12.62:9001/minio/lock/v7/lock?": dial tcp 172.27.12.62:9001: connect: connection refused (*fmt.wrapError)
> internal/rest/client.go:151:rest.(*Client).Call()
> cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
> cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
> cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).Lock()
> internal/dsync/drwmutex.go:404:dsync.lock.func1()
> 
> API: SYSTEM
> Time: 02:02:10:0
> DeploymentID: ad30d2b2-c031-49e4-b779-de02a585338c
> Error: Marking http://172.27.12.63:9001/minio/lock/v7 temporary offline; caused by Post "http://172.27.12.63:9001/minio/lock/v7/lock?": dial tcp 172.27.12.63:9001: connect: connection refused (*fmt.wrapError)
> internal/rest/client.go:151:rest.(*Client).Call()
> cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
> cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
> cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).Lock()
> internal/dsync/drwmutex.go:404:dsync.lock.func1()
> 
> API: SYSTEM
> Time: 02:02:13:0
> DeploymentID: ad30d2b2-c031-49e4-b779-de02a585338c
> Error: Marking http://172.27.12.64:9001/minio/lock/v7 temporary offline; caused by Post "http://172.27.12.64:9001/minio/lock/v7/lock?": read tcp 172.27.12.61:25016->172.27.12.64:9001: read: connection reset by peer (*fmt.wrapError)
> internal/rest/client.go:151:rest.(*Client).Call()
> cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
> cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
> cmd/lock-rest-client.go:116:cmd.(*lockRESTClient).Lock()
> internal/dsync/drwmutex.go:404:dsync.lock.func1()
> ```

This only happens you start the server since they are not coordinated - it is only concerning if you repeatedly see these errors. If not you can ignore them.

**Comment by wybaron** [comment]
Okay, I see what you're saying. Is this a question below? Do you need to open a new question?
![image](https://user-images.githubusercontent.com/19605510/156309908-1f4bd53a-f40d-4a06-9e5a-94de48983e08.png)

**Comment by harshavardhana** [comment]
> Okay, I see what you're saying. Is this a question below? Do you need to open a new question?

That is an internal trace and you won't be able to understand this without knowing the code - it has nothing to do with the error you saw. its just an initial error during startup.
