### ISSUE TITLE
the bug when I try to expand my cluster

### ISSUE THREAD

**Issue by k8ses** [minio/minio#14443]
## Expected Behavior

expand my minio cluster.
## Current Behavior

```shell
##the error log
http://minio4:9000/data/minio1 has incorrect configuration: Expected endpoint http://minio1/data/minio1, seen http://minio1:9000/data/minio1
```
## Steps to Reproduce (for bugs)

1.satrt a cluster
```shell
nohup ./minio server http://minio{1,2}/data/minio{1...4} &
```
2.expand the cluster,the error log will appear
```shell
nohup ./minio server http://minio{1,2}/data/minio{1...4} http://minio{3,4}/data/minio{1...4}  --console-address ":9001"  &
```
## Your Environment

* Version used (`minio --version`):minio version RELEASE.2022-02-26T02-54-46Z
* Server setup and configuration: default
* Operating System and version : CentOS Linux release 7.5.1804 (Core)

**Comment by vadmeste** [comment]
> http://minio{1,2}

`{1,2}` format is not supported, you need to use `{1...2}`

**Comment by k8ses** [comment]
> > [http://minio{1,2}](http://minio%7B1,2%7D)
> 
> `{1,2}` format is not supported, you need to use `{1...2}`

thank you for your help.
