### ISSUE TITLE
The latest release not starting anymore w/ Erasure Code

### ISSUE THREAD

**Issue by dplaton** [minio/minio#14442]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I used Minio for the past few months on my laptop for local development. All this time I used the following command to start Minio on my local laptop with erasure code enabled (because we need versioning).

```
./minio server --address localhost:9000 --console-address :9090 /data{1...4}
```
This worked perfectly up to version `RELEASE.2022-01-04`. Today I upgraded to the latest version `RELEASE.2022-02-26T02-54-46Z` and this doesn't work anymore.

## Expected Behavior

Starting the server with erasure code and 4 drives should work on a local machine.

## Current Behavior

Running the above command throws a lot of errors in the console 
```Formatting 1st pool, 1 set(s), 4 drives per set.
WARNING: Host local has more than 2 drives of set. A host failure will result in data becoming unavailable.
Disk `/Users/xxx/workspace/WebPA/minio-server/data1` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
Disk `/Users/xxx/workspace/WebPA/minio-server/data2` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
Disk `/Users/xxx/workspace/WebPA/minio-server/data3` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
Disk `/Users/xxx/workspace/WebPA/minio-server/data4` the same as the system root disk.
Disk will not be used. Please supply a separate disk and restart the server.
```

There are no folders in the same directory since I always relied on Minio to create them. Also, Minio runs under my local user

## Steps to Reproduce (for bugs)

1. Download the latest version of Minio
2. Go to the folder you download it (or copy the binary file someplace else)
3. Start the server using `./minio server ./data{1...4}` (or any other folder name)
4. The above errors should come up right away

## Regression

Yes, this used to work in `RELEASE.2022-01-04`

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2022-02-26T02-54-46Z`
* Server setup and configuration: macOS v11.6.2 (BigSur)
* Operating System and version (`uname -a`): `Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64`

**Comment by vadmeste** [comment]
@dplaton since this is a toy setup intended for testing only, you need to set this in the environment: MINIO_CI_CD=on
