### ISSUE TITLE
mc: <ERROR> Unable to list folder. XML syntax error on line 1: attribute name without = in element

### ISSUE THREAD

**Issue by mogupta** [minio/minio#14469]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

`./mc ls ominio --debug`

returns the following for a server running on arm64 but another server returns buckets 
I am running a standalone minio server on two servers
The docker container on ominio server was stop and restarted 

```
mc: <DEBUG> GET / HTTP/1.1
Host: minio.mydomain.com:9000
User-Agent: MinIO (linux; arm64) minio-go/v7.0.23 mc/RELEASE.2022-03-03T21-12-24Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20220304/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220304T004112Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 5558
Accept-Ranges: bytes
Cache-Control: max-age=31536000
Content-Type: text/html; charset=utf-8
Date: Fri, 04 Mar 2022 00:41:13 GMT
Last-Modified: Wed, 09 Feb 2022 01:01:02 GMT
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  211.332911ms

mc: <ERROR> Unable to list folder. XML syntax error on line 1: attribute name without = in element
 (1) ls.go:248 cmd.doList(..) Tags: [http://minio.mydomain.com:9000/]
 (0) client-s3.go:2111 cmd.(*S3Client).listInRoutine(..)
 Release-Tag:RELEASE.2022-03-03T21-12-24Z | Commit:f13defa54577 | Host:minio | OS:linux | Arch:arm64 | Lang:go1.17.7 | Mem:2.5 MB/16 MB | Heap:2.5 MB/7.9 MB
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
 Trying to copy / list buckets

## Regression
 No

## Your Environment

* Version used (`minio --version`):   2021-11-24T23:19:33Z
* Server setup and configuration: using docker stand alone
* Operating System and version (`uname -a`):  Linux minio 5.11.0-1019-oracle #20~20.04.1-Ubuntu SMP Tue Sep 21 14:20:46 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by harshavardhana** [comment]
> mc: <DEBUG> GET / HTTP/1.1
> Host: minio.mydomain.com:9000
> User-Agent: MinIO (linux; arm64) minio-go/v7.0.23 mc/RELEASE.2022-03-03T21-12-24Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20220304/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> X-Amz-Date: 20220304T004112Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Content-Length: 5558
> Accept-Ranges: bytes
> Cache-Control: max-age=31536000
> Content-Type: text/html; charset=utf-8
> Date: Fri, 04 Mar 2022 00:41:13 GMT
> Last-Modified: Wed, 09 Feb 2022 01:01:02 GMT
> Vary: Accept-Encoding
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> mc: <DEBUG> Response Time:  211.332911ms
> 
> mc: <ERROR> Unable to list folder. XML syntax error on line 1: attribute name without = in element

Your server is returning XML - perhaps have a load balancer here that is broken.

**Comment by mogupta** [comment]
Minio dashboard is working fine. Please provide direction

**Comment by mogupta** [comment]
I am not using a load balancer.

**Comment by mogupta** [comment]
Found the solution. I started portainer on port 9000 and it didn't even complain.
