### ISSUE TITLE
Deploying a distributed MinIO cluster with Docker Compose, unlimited errors 

### ISSUE THREAD

**Issue by jioushan** [minio/minio#14460]
I don't understand, I use Docker Compose to deploy a distributed MinIO cluster,
After deployment, it cannot be started, and nginx keeps reporting errors!

Based on the official Compose URL

https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml

The most terrifying thing is that the clone's container cannot be terminated and deleted. 

> LOG

Creating root_nginx_1  ... error

ERROR: for root_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "/root/nginx.conf" to rootfs at "/etc/nginx/nginx.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "/root/nginx.conf" to rootfs at "/etc/nginx/nginx.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by ureykane** [comment]
because you forgot to put the nginx.conf file in the same directory 

https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/nginx.conf
