### ISSUE TITLE
set_bucket_versioning not working

### ISSUE THREAD

**Issue by shahabtrojan** [minio/minio#14477]
## Expected Behavior
It should enable bucket versioning when the sdk function is called

## Current Behavior
Instead of enabling bucket versioning i am getting an error that this feature is not implemented as seen in the screenshot below

![minio issue](https://user-images.githubusercontent.com/63194487/156787114-90b24474-4ab3-475a-ad6a-854888ae8396.png)

## Steps to Reproduce (for bugs)
1. As seen in the screenshot, by using the python client trying to set versioning on an existing bucket it fails with the said error

## Your Environment

* Version used (`minio --version`): RELEASE.2022-02-26T02-54-46Z
* Server setup and configuration: Minio server running on docker in our local environment
* Operating System and version (`uname -a`): Linux 6841da7e8527 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Single drive setups doesn't support versioning on buckets
