### ISSUE TITLE
Support for Cache-Control header at bucket and object level

### ISSUE THREAD

**Issue by UchihaYuki** [minio/minio#14486]
**Is your feature request related to a problem? Please describe.**
I put lots of static files (at least not change that much) on minio as well, like mp3, jpeg, I'd like them to be cached on the browser side, instead of making a new request everytime.

**Describe the solution you'd like**
Set Cache-Control header at both bucket and object level by code, mc.exe, and web interface.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by harshavardhana** [comment]
upload the object with the http header name and the value - use the api - will be returned back during getobject or headobject call.
