### ISSUE TITLE
Get 403 error when turn on Cache Everything on Cloudflare

### ISSUE THREAD

**Issue by UchihaYuki** [minio/minio#14484]
I will hide some info in the following details:

The command I use:
```bash
mc rb --debug --force my-minio/my-bucket
```
The error I got:
```
mc: <DEBUG> HEAD /course/ HTTP/1.1
Host: ***
User-Agent: MinIO (windows; amd64) minio-go/v7.0.11 mc/RELEASE.2021-06-13T17-48-22Z
Authorization: ***
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220306T083848Z

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 372
Cf-Cache-Status: BYPASS
Cf-Ray: 6e79c6fbbcb791b1-SIN
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 06 Mar 2022 08:38:49 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=gj6GJFSlaZqew1T%2FA36AgvEqP%2B5mk%2FIaEQAGkT26K5XrIoGhW3K04jnRJE7GIkmMKbL7OaIDk%2FmoIf6eVxqHku1ouMnzfAwNGL74nva6kAKAfSbo%2FynP3KJsyTsf5Pg%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16D9BDE4C65D52DD
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```

It will work, if I just turn off Cache Everything Page Rule for my minio instance domain.

**Comment by harshavardhana** [comment]
Caching of HTTP requests is not allowed for MinIO - AWS Signature v4 requests do not allow replays of previous HTTP responses.

**Comment by UchihaYuki** [comment]
From `Cf-Cache-Status: BYPASS`, we can see that Cloudflare has given the request directly to minio, but why minio return 403. I still don't get it.

**Comment by UchihaYuki** [comment]
A relative question I asked on Cloudflare:
https://community.cloudflare.com/t/why-is-cf-cache-status-bypass-in-this-specific-case/363036

**Comment by UchihaYuki** [comment]
Hi, I find it's caused by signature doesn't match:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><BucketName>course</BucketName><Resource>/course/</Resource><RequestId>16D9D532CBA40512</RequestId><HostId>7bbeea80-374e-4359-aa15-ab35b3733dde</HostId></Error>
```
Which request header might cause this? Do you have any idea?

**Comment by UchihaYuki** [comment]
It seems, it's cloudflare have turned the HEAD request into GET request, which cause the signature mismatch. How no idea why this happens.

**Comment by UchihaYuki** [comment]
from `mc --debug`, I can see it's a HEAD request, but from `mc admin trace -a -v`, I can see it's a GET request. Which is so sooo weird.

**Comment by harshavardhana** [comment]
> It seems, it's cloudflare have turned the HEAD request into GET request, which cause the signature mismatch. How no idea why this happens.

That's called caching.

**Comment by RiverChu0** [comment]
Hello, I have the same problem. Open the cloudflare CDN proxy, and the signature is wrong. Setting only DNS is normal. Have you solved it now?
