### ISSUE TITLE
MinIO server fails to start from systemd on Ubuntu 20.04

### ISSUE THREAD

**Issue by finid** [minio/minio#14487]
## Expected Behavior
After installing it on Ubuntu 20.04, MinIO server should start when prompted with the `sudo systemctl start minio` command, just as it starts with the `sudo minio server /mnt/data` command.

## Current Behavior
Trying to start MinIO server on Ubuntu 20.04 after installing it using `sudo systemctl start minio` fails. However, I can start it with the `sudo minio server /mnt/data` command.

## Possible Solution

As the systemd start script is automatically set up by default, just as the `minio` command is, make it possible to start the MinIO server using `sudo systemctl start minio`, just as it is with `minio server /mnt/data`. Or provide some documentation on what to do to successfully start MinIO with systemd.

## Steps to Reproduce (for bugs)

1. Spin up a fresh Ubuntu 20.04 server
2. Download and install the MinIO server
3. Try to start it using `sudo systemctl start minio`
4. Attempt fails with the following in the log:

```
minio.service: Failed to determine user credentials: No such process
minio.service: Failed at step USER spawning /bin/bash: No such process
```

Note that I can start MinIO server using `sudo minio server /mnt/data` without specifying any credentials, and it starts with the default credentials.

## Context
Just trying to start a MinIO server I just installed on Ubuntu 20.04.

## Regression
Not certain

## Your Environment

* Version used (`minio --version`): RELEASE.2022-03-05T06-32-39Z
* Server setup and configuration: MinIO Standalone mode on Ubuntu 20.04
* Operating System and version (`uname -a`): Linux 5.4.0-100-generic  SMP x86_64 x86_64 x86_64

**Comment by harshavardhana** [comment]
You need to configure the installation first by editing /etc/default/minio

**Comment by finid** [comment]
Is there an official doc that shows how to do that correctly? And given that MinIO can be started with the `minio` command and with systemd, what's the preferred method of starting it?

**Comment by finid** [comment]
One reason I'm bringing this up is that if started with the `minio` command, the server creates a directory that's separate from what's needed to start it with systemd. And I can find nothing about `/etc default/minio` in the official doc, but would be happy if somebody would point me to one.

**Comment by harshavardhana** [comment]
> Is there an official doc that shows how to do that correctly? And given that MinIO can be started with the `minio` command and with systemd, what's the preferred method of starting it?

You could have googled this yourself https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html#create-the-systemd-service-file
