### ISSUE TITLE
Unable to restart MinIO server remotely using the MinIO client mcli 

### ISSUE THREAD

**Issue by finid** [minio/minio#14494]
## Expected Behavior

Expected the MinIO server to restart after stopping it with `mcli admin service stop` and then trying to restart it using the `mcli admin service restart` command remotely.

## Current Behavior

Stopping it works, but trying to restart it fails with the following error messages:

```
mcli: <ERROR> Unable to restart the server. Post "https://server-ip:9000/minio/admin/v3/service?action=restart": dial tcp server-ip:9000: connect: connection refused.
```
And running the command with the ``-debug` flag gives a little bit more output, which does not help much:

```
mcli: <ERROR> Unable to restart the server. Post "https://server-ip:9000/minio/admin/v3/service?action=restart": dial tcp server-ip:9000: connect: connection refused
 (0) admin-service-restart.go:123 cmd.mainAdminServiceRestart(..)
 Release-Tag:RELEASE.2022-03-03T21-12-24Z | Commit:f13defa54577 | Host:kamit | OS:linux | Arch:amd64 | Lang:go1.17.7 | Mem:2.3 MB/16 MB | Heap:2.3 MB/7.8 MB.
```

## Steps to Reproduce (for bugs)

1. Start the server normally
2. From remote machine stop the server using `mcli admin service stop` command
3. Then try to restart it using the `mcli admin service restart` command

## Context

Trying to become familiar with all the client commands, and would like to be able to stop and restart the server remotely. Stopping it works, but not restarting it.

There's nothing in the server's firewall log (ufw.log) and in syslog to indicate where the problem might be.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-03-05T06-32-39Z
* Server setup and configuration: MinIO in Standalone mode
* Operating System and version (`uname -a`): Linux ubuntu-20 5.4.0-100-generic #113-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by finid** [comment]
Thinking about this, it makes sense that the connection is refused, because after stopping the MinIO server successfully, nothing is listening on port 9000. So how is the command expected to be able to restart the server?

**Comment by harshavardhana** [comment]
> Thinking about this, it makes sense that the connection is refused, because after stopping the MinIO server successfully, nothing is listening on port 9000. So how is the command expected to be able to restart the server?

You answered your own question.

**Comment by finid** [comment]
So what is that command supposed to accomplish?

**Comment by finid** [comment]
At least for the benefit of others who might be thinking along the same lines as I was, you can stop a MinIO server remotely, but you can not then restart it. You can, however, restart it if it's online when you issued the command to restart it. Think reboot. But feel free to correct me if I'm wrong.

**Comment by harshavardhana** [comment]
> So what is that command supposed to accomplish?

the command accomplishes "stop" - what you did - it never says that it is "restartable"

> At least for the benefit of others who might be thinking along the same lines as I was, you can stop a MinIO server remotely, but you can not then restart it. You can, however, restart it if it's online when you issued the command to restart it. Think reboot. But feel free to correct me if I'm wrong.

"restart" is meant to restart a running instance.
