### ISSUE TITLE
Ability to use Google Cloud Compute Engine instance service account for lifecycle management

### ISSUE THREAD

**Issue by Corey-Sprung-TELUS** [minio/minio#14496]
**Is your feature request related to a problem? Please describe.**
Currently the only way to use GCS for lifecycle management is using a service account key, This is a pretty insecure way to get access to GCS. If an instance is running within google cloud on a GCE (Compute Engine) the server is already provided a default service account that it's running on. Add the ability for the lifecycle management to use that service account if available. 

**Describe the solution you'd like**
To have an option that if this is running within Google Cloud to use the default GCE service account and not provide the service account key.

**Comment by harshavardhana** [comment]
Gateway is not taking anymore features, and is going to be removed in #14331
