### ISSUE TITLE
Rust aws-sdk-s3 can't communicate with Minio: "Query Parameters are not supported"

### ISSUE THREAD

**Issue by leecbaker** [minio/minio#14498]
When attempting to load a file from Minio, the AWS official SDK is not able to retrieve an object. The following error is returned:

```
Error: ServiceError { err: GetObjectError { kind: Unhandled(Custom("no root element")), meta: Error { code: None, message: None, request_id: None, extras: {} } }, raw: Response { inner: Response { status: 400, version: HTTP/1.0, headers: {"x-amzn-errortype": "InvalidRequestContent", "content-type": "application/json", "content-length": "65", "server": "Werkzeug/1.0.1 Python/3.8.12", "date": "Mon, 07 Mar 2022 23:59:21 GMT"}, body: SdkBody { inner: Once(Some(b"{\"Type\": \"User\", \"Message\": \"Query Parameters are not supported\"}")), retryable: true } }, properties: SharedPropertyBag(Mutex { data: PropertyBag, poisoned: false, .. }) } }
```

## Expected Behavior
I expect to be able to fetch a file (GetObject) from Minio in the same way that I can fetch a file from S3; my expectation is that S3 and Minio have compatible interfaces.

## Current Behavior
When attempting to fetch an object from Minio, an error message is returned that says "Query Parameters are not supported".

This same error message can be seen by sending a request directly from `curl`:

```bash
> curl http://127.0.0.1:3001/dnasolves-match-data/v2/12\?x-id\=GetObject
{"Type": "User", "Message": "Query Parameters are not supported"}%
>
```

## Steps to Reproduce (for bugs)

1. Configure access credentials for AWS or Minio via environment variables, or another method.
2. Run below code to access a file in an S3 bucket
3. Observe that file can be accessed if in S3, but not minio

```rust
use http::Uri;
use std::str::FromStr;
use url::Url;

use std::error::Error;

use aws_config::meta::region::RegionProviderChain;
use aws_sdk_s3::{Client as S3Client, Endpoint, Region};

async fn f() -> Result<(), Box<dyn Error>> {
    let uri = Url::from_str("s3://bucket/file.txt")?;

    // Point to S3
    // let s3_endpoint: Option<String> = None;
    // or point to Minio
    let s3_endpoint: Option<String> = Some("http://127.0.0.1:3001".to_owned());

    let region_provider = RegionProviderChain::default_provider().or_else(Region::new("us-east-1"));
    let shared_config = aws_config::from_env().region(region_provider).load().await;

    let s3_config = if let Some(s3_endpoint) = s3_endpoint {
        let s3_endpoint_uri = Uri::from_str(&s3_endpoint)?;
        let endpoint = Endpoint::immutable(s3_endpoint_uri);
        aws_sdk_s3::config::Builder::from(&shared_config)
            .endpoint_resolver(endpoint)
            .build()
    } else {
        aws_sdk_s3::config::Builder::from(&shared_config).build()
    };

    let client = S3Client::from_conf(s3_config);

    let resp = client
        .get_object()
        .key(uri.path()[1..].to_string())
        .bucket(uri.host_str().expect("Valid S3 bucket name"))
        .send()
        .await?;
    let data = resp.body.collect().await;
    data.unwrap().into_bytes().to_vec();

    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    f().await?;
    Ok(())
}
```

```bash
AWS_PROFILE=... RUST_LOG=trace  RUST_BACKTRACE=1 cargo run
```

## Context
Using a local minio instance to host files, I'm trying to access files stored in Minio using the S3 client. This works in python with the AWS SDK (boto3), but not in rust.

We use Minio to host files in test environments, and S3 in production environments.

## Regression
Unknown if this is a regression.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-03-05T06-32-39Z
* Server setup and configuration: Running minio via command line `minio server`
* Operating System and version (`uname -a`): Darwin machine.localdomain 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by harshavardhana** [comment]
```
> curl http://127.0.0.1:3001/dnasolves-match-data/v2/12\?x-id\=GetObject
{"Type": "User", "Message": "Query Parameters are not supported"}%
>
```

MinIO doesn't return any JSON error at all - are you communicating to Console UI Port here? @leecbaker

**Comment by leecbaker** [comment]
@harshavardhana Thanks for your reply. You're correct that I had the wrong port configured- this was actually AWS SAM CLI's lambda endpoint running on that port. My mistake, sorry for wasting your time!
