### ISSUE TITLE
Webhook HEAD request missing authorisation token

### ISSUE THREAD

**Issue by kgrodzicki** [minio/minio#14507]
When creating a Notification Endpoint and using the WebhookNotification Endpoint with auth token the HEAD requests from the MinIO server does not include the authorisation token.

## Expected Behavior

The HEAD request from MinIO server does not include the authorisation token configured in WebhookNotification Endpoint. 

## Current Behavior

The HEAD request from MinIO server does not include the authorisation token configured in WebhookNotification Endpoint. 

## Possible Solution

Include authorisation token in the same way as for POST requests.

## Steps to Reproduce (for bugs)

Example setup with docker compose and echo server [https://github.com/flow-lab/minio-webhook-head](https://github.com/flow-lab/minio-webhook-head)

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by vadmeste** [comment]
@kgrodzicki this is not an issue per se. I don't this how this affected you.

**Comment by klauspost** [comment]
@kgrodzicki The HEAD requests are just to confirm there is a network connection. I will add a PR with the change and we can discuss if we need it there.

**Comment by klauspost** [comment]
I presume this is just to clean up some error reported?

**Comment by kgrodzicki** [comment]
@klauspost @vadmeste thank you for the fast reply and fix! I guess when configuring webhook with authentication I expect that all requests to it will be including it. And yes, there were error logs on the server side as well. Thank you again for the fix! :)
