### ISSUE TITLE
Support negations in lifecycle tags

### ISSUE THREAD

**Issue by Elessar8** [minio/minio#14508]
**Is your feature request related to a problem? Please describe.**
I would like to create a lifecycle rule that expires all objects that do not have a specific tag.

**Describe the solution you'd like**
`mc ilm add --expire-days "30" --tags "foo != bar"`

 **Alternative solutions**
Being able to create a lifecycle rule that only matches objects that do not have a tag (i.e. they have no tags at all).
This would need a syntax to describe the numbers of tags an object has.

**Additional context**
Objects in our minio storage can be created for various reasons. Some of those require the object to be expired after a certain amount of time, but only if none of the other reasons have been met.

**Comment by vadmeste** [comment]
Negation doesn't exist in S3 protocol. It is not possible to do that.
