### ISSUE TITLE
Is all root(not mixed) disk distributed deployment not available?

### ISSUE THREAD

**Issue by schemacs** [minio/minio#14501]
I setup a cluster of 3 nodes from [Deploy MinIO on Docker Compose](https://docs.min.io/docs/deploy-minio-on-docker-compose.html) without mount volumes to have a test. 

## Expected Behavior

Started and ran as expected(a S3 alternative).

## Current Behavior

All three minio containers logged:
```
minio1_1  | Error: Disk `http://minio4:9000/data2` is part of root disk, will not be used (*errors.errorString)
minio1_1  |        7: cmd/erasure-sets.go:1257:cmd.markRootDisksAsDown()
minio1_1  |        6: cmd/format-erasure.go:792:cmd.initFormatErasure()
minio1_1  |        5: cmd/prepare-storage.go:222:cmd.connectLoadInitFormats()
minio1_1  |        4: cmd/prepare-storage.go:326:cmd.waitForFormatErasure()
minio1_1  |        3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
minio1_1  |        2: cmd/server-main.go:640:cmd.newObjectLayer()
minio1_1  |        1: cmd/server-main.go:491:cmd.serverMain()
minio1_1  | ERROR Unable to initialize backend: disk not found
```

## Possible Solution

Allow all(not mixed) root disk deployment as [this comment](https://github.com/minio/minio/issues/10519#issuecomment-695178179) explained in #10519 ?

## Steps to Reproduce (for bugs)

```bash
wget https://raw.githubusercontent.com/minio/minio/5d6f6d8d5bb6289dda2e7064d1ce1d872e1d85f2/docs/orchestration/docker-compose/{docker-compose.yaml,nginx.conf}
cat >remove-mount.patch <<EOF
--- docker-compose.yaml
+++ docker-compose.yaml
@@ -26,3 +25,0 @@
-    volumes:
-      - data1-1:/data1
-      - data1-2:/data2
@@ -33,3 +29,0 @@
-    volumes:
-      - data2-1:/data1
-      - data2-2:/data2
@@ -40,3 +33,0 @@
-    volumes:
-      - data3-1:/data1
-      - data3-2:/data2
@@ -47,3 +37,0 @@
-    volumes:
-      - data4-1:/data1
-      - data4-2:/data2
@@ -65,11 +52,0 @@
-## By default this config uses default local driver,
-## For custom volumes replace with volume driver configuration.
-volumes:
-  data1-1:
-  data1-2:
-  data2-1:
-  data2-2:
-  data3-1:
-  data3-2:
-  data4-1:
-  data4-2:
EOF
patch -p0 < remove-mount.patch
docker-compose up
```

**Comment by harshavardhana** [comment]
Set CI=true or MINIO_CI_CD=true

**Comment by schemacs** [comment]
I wonder should this env var/feature be documented somewhere? This simple [search](https://github.com/minio/minio/search?q=MINIO_CI_CD&type=code) gives nothing except some golang and shell code.

**Comment by harshavardhana** [comment]
> I wonder should this env var/feature be documented somewhere? This simple [search](https://github.com/minio/minio/search?q=MINIO_CI_CD&type=code) gives nothing except some golang and shell code.

No this is not documented because these are not meant for any production deployments.

**Comment by schemacs** [comment]
Oh, I got it, but the error message could be more informative by including this advice setting MINIO_CI_CD if not for production?

**Comment by klauspost** [comment]
@schemacs No. This will never be supported, so if you set it, you are on your own.

**Comment by JuncusEffusus** [comment]
@klauspost i see another value for MINIO_CI_CD which is set to 'on' in [14442](https://github.com/minio/minio/issues/14442).
do MINIO_CI_CD=on and MINIO_CI_CD=true have the same effect? 
is there any more infomation about MINIO_CI_CD? for instance, i want to expand the minio, so use MINIO_CI_CD , i need not mkdir myself althought it's not a good idea, is it right? 
 thanks.
