### ISSUE TITLE
AMQP exchange Configuration : durable does not take effect

### ISSUE THREAD

**Issue by zj5220924** [minio/minio#14516]
I create a AMQPNotification Endpoint on minio console like below:
![图片](https://user-images.githubusercontent.com/54430024/157637786-f5b1546f-c92b-45a5-be3c-70f6f2b2b473.png)

config.json:
"notify_amqp":{"_":[{"key":"enable","value":"on"},{"key":"url","value":"amqp://minio:12sate34@172.30.200.214:5672/minio"},{"key":"exchange","value":"minio-events"},{"key":"exchange_type","value":"fanout"},{"key":"routing_key","value":""},{"key":"mandatory","value":"false"},**{"key":"durable","value":"true"}**,{"key":"no_wait","value":"false"},{"key":"internal","value":"false"},{"key":"auto_deleted","value":"false"},**{"key":"delivery_mode","value":"2"}**,{"key":"publisher_confirms","value":"off"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""}]}

 the exchenge minio-events was created automatic, but it doesn't effect on "{"key":"durable","value":"true"}":
![图片](https://user-images.githubusercontent.com/54430024/157607799-a1ea6dc8-f91e-42e6-b18e-6bc3cdcfd08d.png)

**Comment by zj5220924** [comment]
Anyone focus on this？

**Comment by harshavardhana** [comment]
> Anyone focus on this？

Nope @zj5220924 feel free to work on it and send a PR.

**Comment by zj5220924** [comment]
Oh，I'm not good at coding，just test on this

**Comment by zj5220924** [comment]
> 

Oh，I'm not good at coding，just test on this，so I should need your help，thanks！

**Comment by harshavardhana** [comment]
> Oh，I'm not good at coding，just test on this，so I should need your help，thanks！

Then you should wait for us to get some free cycles to look at this issue.
