### ISSUE TITLE
Can not remove existing "svcacct"

### ISSUE THREAD

**Issue by DirkDittmarMonday** [minio/minio#14530]
## Expected Behavior
The svcacct should be removed

## Current Behavior
The svcacct is not removed ... `mc` is getting a 500 from the server

## Steps to Reproduce (for bugs)
1. `mc alias set provisioning $MINIO_URL $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD`
2. `mc admin user add provisioning $USER $PASS`
3. `mc admin policy set provisioning readwrite user=$USER`
4. `mc admin user enable provisioning $USER`
5. `mc admin user svcacct add provisioning $USER --access-key $SVCACCT_ACCESS_KEY --secret-key $SVCACCT_SECRET_KEY`
6. `mc --debug admin user svcacct rm provisioning $SVCACCT_ACCESS_KEY`

leads to this output:
```
mc: <DEBUG> DELETE /minio/admin/v3/delete-service-account?accessKey=minio-fmserver HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/RELEASE.2022-03-09T02-08-36Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20220311//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220311T141307Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 243
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Fri, 11 Mar 2022 14:13:07 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16DB5909C9FD575F
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"InternalError","Message":"We encountered an internal error, please try again. (signature is invalid)","Resource":"/minio/admin/v3/delete-service-account","RequestId":"16DB5909C9FD575F","HostId":"5642f036-1ddf-4a7c-84b4-9f711b3ff0f2"}
mc: <DEBUG> Response Time:  5.181206ms

mc: <ERROR> Unable to remove a new service account. We encountered an internal error, please try again. (signature is invalid)
 (1) admin-user-svcacct-rm.go:69 cmd.mainAdminUserSvcAcctRemove(..) Tags: [provisioning, minio-fmserver]
 (0) admin-user-svcacct-rm.go:69 cmd.mainAdminUserSvcAcctRemove(..)
 Release-Tag:RELEASE.2022-03-09T02-08-36Z | Commit:bd00af5a71bc | Host:didi-Precision-5550 | OS:linux | Arch:amd64 | Lang:go1.17.7 | Mem:3.4 MB/22 MB | Heap:3.4 MB/12 MB.
```

and on the server side I found something like this:
```
API: DeleteServiceAccount()
Time: 13:32:55 UTC 03/11/2022
DeploymentID: 5642f036-1ddf-4a7c-84b4-9f711b3ff0f2
RequestID: 16DB56D82513BC4A
RemoteHost: 172.17.0.15
Host: minio-1.minio-headless.dev.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2022-03-09T03-10-33Z
Error: signature is invalid (*errors.errorString)
       5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
       4: cmd/admin-handler-utils.go:217:cmd.toAdminAPIErrCode()
       3: cmd/admin-handler-utils.go:204:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:987:cmd.adminAPIHandlers.DeleteServiceAccount()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

## Your Environment
* Minio-Version: 2022-03-08T22:28:51Z
* `mc`-Version: RELEASE.2022-03-09T02-08-36Z

**Comment by vadmeste** [comment]
@DirkDittmarMonday I am not to reproduce this using the same MinIO/mc versions. Could you describe your MinIO setup ?

**Comment by harshavardhana** [comment]
> @DirkDittmarMonday I am not to reproduce this using the same MinIO/mc versions. Could you describe your MinIO setup ?

This looks like the user has modified the internal session token @vadmeste

**Comment by harshavardhana** [comment]
```
 harsha in ~ λ kubectl exec -it mc /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@mc /]# mc admin user add all-nodes/ testuser testuser123
Added user `testuser` successfully.
[root@mc /]# mc admin policy set all-nodes readwrite user=testuser
Policy `readwrite` is set on user `testuser`
[root@mc /]# #mc admin user enable all-nodes testuser
[root@mc /]# mc admin user svcacct add all-nodes testuser --access-key hello --secret-key hello1234
Access Key: hello
Secret Key: hello1234
[root@mc /]# mc admin user svcacct rm all-nodes hello

[root@mc /]# 
```

Seems to work fine @DirkDittmarMonday 

> API: DeleteServiceAccount()
> Time: 13:32:55 UTC 03/11/2022
> DeploymentID: 5642f036-1ddf-4a7c-84b4-9f711b3ff0f2
> RequestID: 16DB56D82513BC4A
> RemoteHost: 172.17.0.15
> Host: minio-1.minio-headless.dev.svc.cluster.local:9000
> UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2022-03-09T03-10-33Z
> Error: signature is invalid (*errors.errorString)
>        5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
>        4: cmd/admin-handler-utils.go:217:cmd.toAdminAPIErrCode()
>        3: cmd/admin-handler-utils.go:204:cmd.toAdminAPIErr()
>        2: cmd/admin-handlers-users.go:987:cmd.adminAPIHandlers.DeleteServiceAccount()
>        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

Looks like you have changed the production root credentials here @DirkDittmarMonday 

@vadmeste it's the change in root credentials that causes this problem.

**Comment by DirkDittmarMonday** [comment]
@vadmeste ... I've build a simple example project and everything works fine. I have to figure out what is going on in kubenetes that leads to the problem ...
@harshavardhana ... I think you're right about the root credentials change. The project is a helm chart and the secret is created with the chart. I get the problem when I uninstall minio and reinstall it. The PVCs are still there after uninstall. But helm deleted the secret and so helm create a new secret on reinstall. The PVCs however will be reused by minio. If I get you right that could cause the problem?

**Comment by harshavardhana** [comment]
> @harshavardhana ... I think you're right about the root credentials change. The project is a helm chart and the secret is created with the chart. I get the problem when I uninstall minio and reinstall it. The PVCs are still there after uninstall. But helm deleted the secret and so helm create a new secret on reinstall. The PVCs however will be reused by minio. If I get you right that could cause the problem?

correct its a root credential change you need to preserve the previous root credential for now. I am sending a fix where this can get de-coupled from "Root" credential change.
