### ISSUE TITLE
S3 Select: ScanRange does not seem to be suported

### ISSUE THREAD

**Issue by karlanke** [minio/minio#14539]
This was generally intuition, with select operations taking far longer than an equivalent call to s3. I then searched this repo, and couldn't find any instances of ScanRange, the param that s3 uses. It's also not mentioned in the docs, where other discussion of supported features lives.

## Expected Behavior
Given a call from Python such as:
```
response = self.s3_client.select_object_content(
                    Bucket=bucket,
                    Key=key,
                    ExpressionType='SQL',
                    Expression=f"select * from s3object s where s.pk = 'pk'",
                    InputSerialization={'CSV': {'FileHeaderInfo': 'Use', 'FieldDelimiter': '|'}},
                    OutputSerialization={'JSON': {}},
                    ScanRange={
                        'Start': 0,
                        'End': 1000
                    }
                )
```
I expect the call to return fairly quickly, even if the underlying file is several gigs

## Current Behavior
A call similar to that one (with python and minio running in docker) takes 16 seconds.

## Your Environment
* Version used (`minio --version`): docker minio/minio:RELEASE.2021-09-15T04-54-25Z

**Comment by harshavardhana** [comment]
ScanRange was never implemented @karlanke - however, please upgrade to the latest release.
