### ISSUE TITLE
HeadObject causing RequestedRangeNotSatisfiable if key does not exist

### ISSUE THREAD

**Issue by snorwin** [minio/minio#14531]
As soon as replication on a bucket is enabled and a you try to perform a `HeadObject` a RequestedRangeNotSatisfiable error is returned if the key does not exist.

## Expected Behavior
```
{
  AcceptRanges: "bytes",
  CacheControl: "private",
  ContentLength: 0
} NotFound: Not Found
	status code: 404, request id: 16DB6D40A1E7D5BB, host id: 
```

## Current Behavior
```
{
  AcceptRanges: "bytes",
  ContentLength: 0
} RequestedRangeNotSatisfiable: Requested Range Not Satisfiable
	status code: 416, request id: 16DB6CB10E18FA61, host id: 
```

## Possible Solution
IDK

## Steps to Reproduce (for bugs)
1. Create 2 MinIO cluster in distributed mode
2. Create a bucket and enable versioning and replcation
3. Run the following code:
```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

func main() {
	sess := session.Must(session.NewSession())
	svc := s3.New(sess, &aws.Config{
		Endpoint:         aws.String("https://s3-minio"),
		Region:           aws.String("minio"),
		DisableSSL:       aws.Bool(true),
		S3ForcePathStyle: aws.Bool(true),
		Credentials:      credentials.NewStaticCredentials("minioadmin", "minioadmin", ""),
	})

	req := &s3.HeadObjectInput{
		Bucket: aws.String("test"),
		Key:    aws.String("//foo//bar"),
	}

	fmt.Println(svc.HeadObject(req))
}

```

## Context
This issue causes https://github.com/vmware-tanzu/velero/issues/4734

## Your Environment
* Version used (`minio --version`): RELEASE.2022-03-08T22-28-51Z
* Operating System and version (`uname -a`): Kubernetes v1.21.6+bb8d50a (OpenShift 4.8.28)

**Comment by harshavardhana** [comment]
@poornas looks like a regression

**Comment by snorwin** [comment]
@poornas and @harshavardhana thank you a lot for the quick fix 😊.
