### ISSUE TITLE
MinIO stops processing requests (SlowDown) that never clears

### ISSUE THREAD

**Issue by nocturo** [minio/minio#14547]
## Expected Behavior
MinIO SlowDown to starts accepting traffic after the conditions for it have passed.

## Current Behavior
Currently, MinIO starts working very hard and after about a day of requests at a rate of around ~800 r/s we start getting 503 service unavailable errors with the following error:

`<Error><Code>SlowDown</Code><Message>A timeout exceeded while waiting to proceed with the request, please reduce your request rate</Message><Resource>/testo</Resource><RequestId>16DC3E00873CF18C</RequestId><HostId>b79f3100-3842-4a69-841c-c285668b4924</HostId></Error>`

All requests are now stalled until a restart, even if I let it sit like that for days. (like if it had to dump data from RAM to disk) It hasn't consumed all of available RAM either:

` 249509 minio     20   0  173.0g  84.8g  24280 S 115.7  22.5 161732:24 /usr/local/bin/minio server --console-address :9001 http://10.255.254.1{1...2}:9000/mnt/disk{1...60}/data`

The API/console continues to work, but the S3 endpoint does not work from any client. They all get 503s.

## Steps to Reproduce (for bugs)
1. At around a steady rate of around 800 r/s doing PUT and GET afterward in this setup, MinIO stops processing requests.

## Context
We are using 2 nodes in a cluster mode with `MINIO_FS_OSYNC="true"` to guarantee a write before returning success. Disks are formatted using XFS and there are no apparent system issues. Max open files have been increased to 16 million.

## Regression
No. Tried updating versions a couple of times during testing and it was the same.

## Your Environment

* Version used (`minio --version`): `2022-02-26T02:54:46Z`
* Server setup and configuration: `Two bare metal servers with 2x6230R, 384GB RAM, 60x6T drives, MinIO running directly on bare metal through systemd`
* Operating System and version (`uname -a`): `Linux ceph01-tor1 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): `2022-02-26T02:54:46Z`

Please upgrade to the latest release.

**Comment by harshavardhana** [comment]
> We are using 2 nodes in a cluster mode with `MINIO_FS_OSYNC="true"` to guarantee a write before returning success. Disks are formatted using XFS and there are no apparent system issues. Max open files have been increased to 16 million.

This is not useful @nocturo you should never do that all the writes are persistent already. This is only meant for `FS` mode.

**Comment by harshavardhana** [comment]
Closing this as this is not a MinIO issue per se - just wrong configuration and setup issues.

**Comment by nocturo** [comment]
@harshavardhana we had issues where we write and immediately then do a GET and get a 404, that's why we went with `MINIO_FS_OSYNC` option to force a write instead. Should I open an issue for that instead if this is wrong?

**Comment by harshavardhana** [comment]
> @harshavardhana we had issues where we write and immediately then do a GET and get a 404, that's why we went with `MINIO_FS_OSYNC` option to force a write instead. Should I open an issue for that instead if this is wrong?

@nocturo what kind of filesystem are you using?

**Comment by nocturo** [comment]
@harshavardhana XFS

**Comment by harshavardhana** [comment]
and these are regular drives? @nocturo

**Comment by nocturo** [comment]
Yes, regular HDDs.

**Comment by harshavardhana** [comment]
> @harshavardhana we had issues where we write and immediately then do a GET and get a 404, that's why we went with `MINIO_FS_OSYNC` option to force a write instead. Should I open an issue for that instead if this is wrong?

This is impossible to happen unless you have some kind of filesystem corruption here or you have some weird setup.  Feel free to open a new issue.
