### ISSUE TITLE
There is only one way to set bucket policy?

### ISSUE THREAD

**Issue by xieweilie** [minio/minio#14543]
**Set whether the bucket policy can only override the policy JSON**
// Assume policyJson contains below JSON string;
// {
//     "Statement": [
//         {
//             "Action": [
//                 "s3:GetBucketLocation",
//                 "s3:ListBucket"
//             ],
//             "Effect": "Allow",
//             "Principal": "*",
//             "Resource": "arn:aws:s3:::my-bucketname"
//         },
//         {
//             "Action": "s3:GetObject",
//             "Effect": "Allow",
//             "Principal": "*",
//             "Resource": "arn:aws:s3:::my-bucketname/myobject*"
//         }
//     ],
//     "Version": "2012-10-17"
// }
//
minioClient.setBucketPolicy(
    SetBucketPolicyArgs.builder().bucket("my-bucketname").config(policyJson).build());

**help**
**There is only one way to set bucket policy?**
This setting is overwritten every time。
If I want to add a path policy, I need to getbucket every time, then modify the policy JSON, and then setbucket?
I want to modify it directly。

**Comment by harshavardhana** [comment]
Incomplete issue closing.
