### ISSUE TITLE
Set whether the bucket policy can only override the policy JSON

### ISSUE THREAD

**Issue by xieweilie** [minio/minio#14542]
**Version 8.3.7. If I want to add an access policy for a file path, do I want to get the policy JSON from getbucketpolicy, then add this path based on this JSON, and then set bucketpolicy to overwrite this policy JSON? In the case of concurrency, there will be problems, or is there any other way? For example, add or modify directly.**

**Comment by harshavardhana** [comment]
Closing this since this is an incomplete issue.
