### ISSUE TITLE
S3 Gateway assumes all buckets are in us-east-1

### ISSUE THREAD

**Issue by keefbaker** [minio/minio#14558]
## Expected Behavior

When using minio s3 gateway against AWS it should detect which region the bucket is in and use that for the url

## Current Behavior
it assumes the bucket is in us-east-1

```
API: ListObjectsV2(bucket=mybucket-sandbox-a)
Time: 13:52:50 UTC 03/16/2022
DeploymentID: fb7e2805-9942-480f-8cc6-4a2095a85d92
RequestID: 16DCE0D525AA541F
RemoteHost: 127.0.0.6
Host: minio.monitoring.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.25.0 (go1.17.7)
Error: Get "https://mybucket-sandbox-a.s3.dualstack.us-east-1.amazonaws.com/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1000&prefix=": 301 response missing Location header (*url.Error)
```

## Possible Solution
Either allow minio to read AWS_REGION env var and take that or take the info from AWS

## Steps to Reproduce (for bugs)
All I did with this was set up the minio gateway using the helm chart with:

```
    auth:
      s3:
        accessKey: miniouser
        secretKey: "redacted"
```

i am using KIAM to pass AWS credentials and that works for everything else in the cluster and this DOES pick up the buckets, it just assumes they're in US-EAST-1

using the following docker image:
docker.io/bitnami/minio:2022.3.5-debian-10-r2

I have tried switching the s3 endpoint out for https://s3.eu-west-2.amazonaws.com but then the credentials it gets from IAM then do not work as it seems to assume it needs to use the passed access keys rather than the ones from the metadata endpoint.

Is there something I'm missing here?

**Comment by harshavardhana** [comment]
> using the following docker image:
> docker.io/bitnami/minio:2022.3.5-debian-10-r2

Please use MinIO published images @keefbaker

**Comment by keefbaker** [comment]
No problem, I just switched to minio/minio:RELEASE.2022-03-17T06-34-49Z

And the problem is identical.

```

Error: Get "https://bucket-redacted.s3.dualstack.us-east-1.amazonaws.com/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1000&prefix=": 301 response missing Location header (*url.Error)
       4: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2137:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:252:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

**Comment by keefbaker** [comment]
If this isn't normal minio behaviour, is there potentially a missing permission in IAM that might cause this? We use organizations and SCP may be blocking something.

**Comment by keefbaker** [comment]
Yep. It was our SCPs blocking getBucketLocation from us-east-1
