### ISSUE TITLE
min.io generates large number of errors in Azure Blob

### ISSUE THREAD

**Issue by ngrigoriev** [minio/minio#14551]
I have noticed that when using as Azure Blob gateway, min.io generates a large number of errors on the Blob side. However, all these errors seem to be harmless, they are registered but do not seem to affect the operations.

Usually I see almost 50% or 30% of the errors comparing to the normal operations - depending on the traffic and the applications.

The errors are logged as "ClientOtherError" and seem to be 100% for GetBlobProperties operation. It seems that this kind of error can be returned as a normal response to an operation that check for something that exists (https://docs.microsoft.com/en-us/rest/api/storageservices/storage-analytics-logged-operations-and-status-messages).

I would like to understand which S3 operation results in these errors. The problem I see with this today is that the large number of errors reported by Azure makes it pointless to monitor the Blob metrics for errors.

Another thought - it may be not necessarily min.io itself but Azure SDK.

## Expected Behavior
min.io does not trigger Azure Blob errors

## Current Behavior
min.io triggers Azure Blob errors of type ClientOtherError (on GetBlobProperties operation).

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
- use min.io with Azure storage
- perform the operations like putObject 

## Context
Trying to use Azure Blob via min.io and have a way to monitor the Blob for errors.

## Regression
no

## Your Environment
- latest min.io
- using it as Azure storage gateway

Thanks!

**Comment by harshavardhana** [comment]
MinIO Gateway azure is being removed #14331 - these are normal errors that happens with Azure and printed by Azure SDK we have no control over it.
