### ISSUE TITLE
mc mirror --watch will render source minio cluster unresponsive  if objects cant be copied

### ISSUE THREAD

**Issue by steschuser** [minio/minio#14566]
We have a Source Minio and a Backup Minio and we want to keep them in sync
To do that, we run a mc mirror command as systemd process

`mc mirror --watch --remove --overwrite -q source backup`

This works fine, until some objects cannot be copied. In our current case, there are files that are encrypted via SSE-C
We see a Bad Request 400
`source/bucket/files/encrypted.pdf -> backup/bucket/files/supplier/encrypted.pdf
mc: <ERROR> Failed to copy https://source.storage.systems/bucket/files/encrypted.pdf. 400 Bad Request
Total: 0 B, Transferred: 12.41 KiB, Speed: 250.40 KiB/s`

The command will retry to copy the source until the source server becomes unresponsive.
In the log file we see:
`mc: <ERROR> Unable to list comparison retrying.. A timeout exceeded while waiting to proceed with the request, please reduce your request rate
mc: <ERROR> Unable to list comparison retrying.. A timeout exceeded while waiting to proceed with the request, please reduce your request rate`

And any other command, like mc ls source, will return a timeout or 503
`failed with SlowDown: A timeout exceeded while waiting to proceed with the request, please reduce your request rate
    status code: 503, request id: 16DCCF96A5683759, host id: `

## Expected Behavior
Don*t kill source...
Fail gracefully on objects that cannot be copied

## Current Behavior
Source becomes unresponsive.

## Steps to Reproduce (for bugs)
1. Have a minio source with one SSE-C encrypted file
2. Have a minio backup 
3. Start mc mirror --watch  --remove --overwrite -q source backup`

## Your Environment
minio running as docker
```version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2021-08-25T00-41-18Z
    restart: always
    volumes:
      - /etc/ssl/:/root/.minio/certs
      - /etc/kes/t:/kes/
      - /srv/data01:/data01
    ports:
      - "9006:9000"
      - "9007:9001"
    environment:
      MINIO_KMS_KES_ENDPOINT: "kes:7374"
      MINIO_KMS_KES_KEY_FILE: /kes/app.key
      MINIO_KMS_KES_CERT_FILE: /kes/app.cert
      MINIO_KMS_KES_KEY_NAME: my-app
      MINIO_SERVER_URL: "https://source.storage.systems"
      MINIO_BROWSER_REDIRECT_URL: "https://source-console.storage.systems"
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: pass
    command: minio server /data01 --console-address ":9001"
    healthcheck:

      test: ["CMD", "curl", "-f", "https://source.storage.systems:9006/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3```

**Comment by ravindk89** [comment]
A few things:

- What version of `mc` are you running?
- Have you tested this with a more recent MinIO Release? The image specified is almost 6 months old.

The nature of `mc mirror --watch` implies retrying operations, though those ops *should* fail gracefully. Some of that might be on the quirks of single-drive MinIO vs erasure-coded MinIO, but I'll defer that to the engineers.

**Comment by harshavardhana** [comment]
> image: minio/minio:RELEASE.2021-08-25T00-41-18Z

Please use always latest as a community member @steschuser and also latest `mc`

**Comment by steschuser** [comment]
Thanks for the response
I tried this with latest *mc*

```
mc version RELEASE.2022-03-17T20-25-06Z
```

The result is the same, the source ends up unresponsive.
I'll upgrade the minio images later.  This is a system in production and Id like to keep downtimes to a minimum.

**Comment by harshavardhana** [comment]
> I'll upgrade the minio images later. This is a system in production and Id like to keep downtimes to a minimum.

MinIO upgrade is what I am talking about.

**Comment by steschuser** [comment]
This is now running with latest stable Image
`image: minio/minio:RELEASE.2022-03-17T06-34-49Z`

The problem persists. After roughly 5 minutes source minio becomes unresponsive

**Comment by harshavardhana** [comment]
> The problem persists. After roughly 5 minutes source minio becomes unresponsive

Thanks @steschuser

**Comment by steschuser** [comment]
Hello @harshavardhana @klauspost 

any update on this?
Could you reproduce this bug?

**Comment by harshavardhana** [comment]
> Hello @harshavardhana @klauspost
> 
> any update on this? Could you reproduce this bug?

No update will get back, once our pressing priorities are handled.

**Comment by harshavardhana** [comment]
ping @vadmeste

**Comment by vadmeste** [comment]
I was able to reproduce this issue. I think we just need more goroutines cleanup when error happens during mirroring. However the new version doesn't quit anymore for such error.

**Comment by harshavardhana** [comment]
> I was able to reproduce this issue. I think we just need more goroutines cleanup when error happens during mirroring. However the new version doesn't quit anymore for such error.

@vadmeste we need to make sure server should cancel routines as well

**Comment by harshavardhana** [comment]
mc mirror has been fixed to close the "watch" calls to the server, - a server-side fix is also needed to ensure - that the rogue client cannot abuse this on the server.  // cc @vadmeste

**Comment by steschuser** [comment]
hello again,

thanks for this.
Ill try with new mc mirror next week.
Is there an issue tracking the server side of this bug?

**Comment by harshavardhana** [comment]
This is the issue for server side of the bug
