### ISSUE TITLE
Expanding existing drives/partitions

### ISSUE THREAD

**Issue by hege-li** [minio/minio#14573]
Hello, apparently Slack is open only for @min.io users (?), so I'll try asking here.

I'm currently testing a 4 server distributed setup, all servers have a single /data drive.

All the documentation and previous discussions suggests that Minio storage can only be expanded by adding new server pool to a cluster.

Yet when I simply expand/resize the existing /data drives (using LVM+lvextend which is a completely common operation for virtual/cloud servers), I can verify using minio console and prometheus statistics (/minio/v2/metrics/cluster) that all minio_cluster_disk_free_inodes, minio_node_disk_free_bytes etc increase accordingly even without restart.

So is this an officially supported way of expanding storage or not? Is there still some internal fixed storage size saved somewhere that prevents using the full new space, as reported even by console and prometheus metrics?

**Comment by harshavardhana** [comment]
Please join https://slack.min.io or https://join.slack.com/t/minio/shared_invite/zt-11qsphhj7-HpmNOaIh14LHGrmndrhocA 

> Yet when I simply expand/resize the existing /data drives (using LVM+lvextend which is a completely common operation for virtual/cloud servers), I can verify using minio console and prometheus statistics (/minio/v2/metrics/cluster) that all minio_cluster_disk_free_inodes, minio_node_disk_free_bytes etc increase accordingly even without restart.

You can do that but we do that as long as your filesystem supports it, but we do not recommend such deployments or support them in production environments.


> So is this an officially supported way of expanding storage or not? Is there still some internal fixed storage size saved somewhere that prevents using the full new space, as reported even by console and prometheus metrics?

Official way is to not use LVM instead provide JBODs to MinIO.

**Comment by hege-li** [comment]
> Official way is to not use LVM instead provide JBODs to MinIO.

If we want to nitpick a little, using LVM here or not doesn't make any difference. A "JBOD" in a virtualized environment, is nothing but virtual block device. Even a JBOD disk and it's associated filesystem can be resized easily.

**Comment by harshavardhana** [comment]
> If we want to nitpick a little, using LVM here or not doesn't make any difference. A "JBOD" in a virtualized environment, is nothing but virtual block device. Even a JBOD disk and it's associated filesystem can be resized easily.

Virtualized environments are largely at the mercy of the virtualized storage controller, however, from an I/O point of view removing one "extra" layer such as LVM would benefit you immensely. 

If layering is the game - removal of an additional layer always helps - in this case, LVM.

**Comment by deguzmanricardo16** [comment]
> Please join https://slack.min.io or https://join.slack.com/t/minio/shared_invite/zt-11qsphhj7-HpmNOaIh14LHGrmndrhocA
> 
> > Yet when I simply expand/resize the existing /data drives (using LVM+lvextend which is a completely common operation for virtual/cloud servers), I can verify using minio console and prometheus statistics (/minio/v2/metrics/cluster) that all minio_cluster_disk_free_inodes, minio_node_disk_free_bytes etc increase accordingly even without restart.
> 
> You can do that but we do that as long as your filesystem supports it, but we do not recommend such deployments or support them in production environments.
> 
> > So is this an officially supported way of expanding storage or not? Is there still some internal fixed storage size saved somewhere that prevents using the full new space, as reported even by console and prometheus metrics?
> 
> Official way is to not use LVM instead provide JBODs to MinIO.

Can you share a new invite link?

**Comment by snailAlice** [comment]
May I ask how much the overall cluster performance will drop if you use the LVM method? Is there a specific calculation report for this that you can refer to?

**Comment by harshavardhana** [comment]
> May I ask how much the overall cluster performance will drop if you use the LVM method? Is there a specific calculation report for this that you can refer to?

LVM is very poor in performance, gives almost 50% of what a drive is capable in our tests.
