### ISSUE TITLE
[root disk usage] minio not working anymore with local folders (root disk issue)

### ISSUE THREAD

**Issue by jpchev** [minio/minio#14582]
minio doesn't work anymore with local folders as data directories.
I have 3 virtual machines, each with 6 local folders under /export/
```
[centos@s3-n1-vm ~]$ ls -l /export/
drwxr-xr-x. 3 centos centos 4096 Mar 19 11:21 data1
drwxr-xr-x. 3 centos centos 4096 Mar 19 11:21 data2
drwxr-xr-x. 3 centos centos 4096 Mar 19 11:21 data3
drwxr-xr-x. 3 centos centos 4096 Mar 19 11:21 data4
drwxr-xr-x. 3 centos centos 4096 Mar 19 11:21 data5
drwxr-xr-x. 3 centos centos 4096 Mar 19 11:21 data6
```
I run minio on each virtual machine with
`minio server http://minio-{0...2}/export/data{1...6}`

## Current Behavior
error messages as the following, and minio instances don't start correctly

Error: Disk `/export/data6` is part of root disk, will not be used (*errors.erro
rString)
Error: Disk `http://minio-2:9000/export/data5` is part of root disk, will not be
 used (*errors.errorString)

## Possible Solution
worked in minio version RELEASE.2022-01-08T03-11-54Z

## Steps to Reproduce (for bugs)

1. 
```
mkdir -p /export/{data1,data2,data3,data4,data5,data6}
chown centos:centos -R /export;
```
2.
`minio server http://minio-{0...2}/export/data{1...6}`

## Regression
Is this issue a regression? Yes
release: minio version RELEASE.2022-03-17T06-34-49Z
it worked in minio version RELEASE.2022-01-08T03-11-54Z

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-03-17T06-34-49Z
* Server setup and configuration: 3 virtual machines, each with a minio process launched with the command `minio server http://minio-{0...2}/export/data{1...6}`
* Operating System and version (`uname -a`): `Linux s3-n1-vm.lan 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
set `CI=true` - since that's what you want

**Comment by jpchev** [comment]
what is CI, a minio option?

**Comment by klauspost** [comment]
This is an unsupported configuration. If you set the `CI=on`, you can make it run for a test/playground setup.

**Comment by jpchev** [comment]
Ok thanks, but could you please explain where to set that parameter and what is its purpose?
Also, why the thing is not working on the latest release, and worked in a previous release (January 2022)

**Comment by klauspost** [comment]
@jpchev It is an environment variable. `CI=on minio server http://minio-{0...2}/export/data{1...6}` should work.

It still works, but was never a supported setup. You are bypassing all availability features when you share data folders. Each folder should be a clean physical disk.

**Comment by jpchev** [comment]
Ok thanks for the info, I guess CI is used for your CI/CD pipeline right? In it you might want to mock up the data disks
