### ISSUE TITLE
admin config to return env variables

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#14588]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to know the env variables being set on a cluster. It is good to return env variables as part of admin config export API response

**Describe the solution you'd like**
The env variables should be returned as a env: key= value prefixed by a comment, that way it can be exported to other clusters.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by klauspost** [comment]
@kannappanr I just sent a PR that adds runtime info to server info. I added a placeholder for MinIO env vars, where we can add env vars with `MINIO` prefix: https://github.com/minio/madmin-go/pull/75/files#diff-46ab8d7c52533584f96ba53eaeadd8cf52839f1c5d175c059ceb909c2c3e0715R808

**Comment by harshavardhana** [comment]
We already have `--env` command line option, we can simply return everything with `MINIO_` prefix when asked with `mc admin config export alias/ --env` 

Additionally filter by sub-system with `mc admin config get alias/ notify_webhook --env`

**Comment by harshavardhana** [comment]
> We already have `--env` command line option, we can simply return everything with `MINIO_` prefix when asked with `mc admin config export alias/ --env`
> 
> Additionally filter by sub-system with `mc admin config get alias/ notify_webhook --env`

@kannappanr ^^

**Comment by harshavardhana** [comment]
@donatello since you are doing the work for ENVs - moving this to you to finish the rest of the things where we can query ENV values.

**Comment by harshavardhana** [comment]
This is fixed and released - closing as fixed by #15465
