### ISSUE TITLE
Lifecycle rule does not work for tags with quote characters

### ISSUE THREAD

**Issue by bood** [minio/minio#14593]
## Expected Behavior

Lifecycle rule should work with tag with quote characters in it, e.g. Key="term, Value=term-3m" (which is set incorrectly by accident)

## Current Behavior

No expiration information is added to the object

```
$ mc stat mybucket/default/static/abnormal.pdf
Name      : abnormal.pdf
Date      : 2022-03-20 22:43:12 CST
Size      : 41 KiB
ETag      : a7a9a49045c6cf3342cfe3f5c18caf9b
Type      : file
Metadata  :
  X-Amz-Tagging-Count: 1
  Content-Type       : application/pdf
```

## Steps to Reproduce (for bugs)

```bash
$ mc tag set mybucket/default/static/abnormal.pdf '"term=term-3m"'
$ mc tag list mybucket/default/static/abnormal.pdf
Name  : http://****/default/static/abnormal.pdf ()
"term : term-3m"
$ mc ilm add --expiry-days "30" --tags '"term=term-3m"' mybucket/default
```

problem does not exist for normal tag like `mc tag set mybucket/default/static/normal.pdf "term=term-3m"`

```
$ mc tag set mybucket/default/static/normal.pdf term=term-3m
$ mc tag list mybucket/default/static/normal.pdf
Name : http://****/default/static/normal.pdf ()
term : term-3m
$ mc stat mybucket/default/static/normal.pdf
Name      : normal.pdf
Date      : 2022-03-20 22:43:09 CST
Size      : 41 KiB
ETag      : a7a9a49045c6cf3342cfe3f5c18caf9b
Type      : file
Expiration: 2022-06-19 08:00:00 CST (lifecycle-rule-id: term-3m)
Metadata  :
  X-Amz-Tagging-Count: 1
  Content-Type       : application/pdf
```

## Context

I made mistake in one of our script and set tags with quotes in it. I was expecting adding some new lifecycle rules with those new tags would solve the expiration issue but it did not.

## Your Environment

```
$ mc --version
mc version RELEASE.2021-11-16T20-37-36Z
$ minio --version
minio version DEVELOPMENT.2021-03-26T12-16-37Z
$ minio --version (upgraded and tried this one too)
minio version DEVELOPMENT.2021-06-18T09-39-33Z
```

**Comment by harshavardhana** [comment]
> ```shell
> $ mc tag set mybucket/default/static/abnormal.pdf '"term=term-3m"'
> $ mc tag list mybucket/default/static/abnormal.pdf
> Name  : http://****/default/static/abnormal.pdf ()
> "term : term-3m"
> $ mc ilm add --expiry-days "30" --tags '"term=term-3m"' mybucket/default
> ```

This is working as expected @bood - you have added quotes as key 

```
"term
```

and its value as

```
term-3m"
```

This is different than your actual expected tag `term-3m` - so this is not a bug instead an application error i.e you are setting wrong tags.

**Comment by bood** [comment]
@harshavardhana I have included the quote in the lifecycle settings too, I assume it should work but it didn't.

Note I used the following command to add the corresponding rule

`mc ilm add --expiry-days "30" --tags '"term=term-3m"' mybucket/default`

and the actual setting returned from server:

```
$ mc ilm ls mybucket/default --json
...
   {
    "Expiration": {
     "Days": 30,
     "DeleteMarker": false
    },
    "ID": "c8rk7s7blarpibo87plg",
    "Filter": {
     "And": {
      "Tags": [
       {
        "Key": "\"term",          <--- Note the quote here
        "Value": "term-3m\""
       }
      ]
     }
    },
    "Status": "Enabled"
   }
```
