### ISSUE TITLE
After a successful upload, file can not be found

### ISSUE THREAD

**Issue by nocturo** [minio/minio#14596]
## Expected Behavior
After upload, be able to retrieve the file.

## Current Behavior
In our testing of uploading a million files to the MinIO cluster, about 200 failed with these symptoms. After a successful upload, neither HEAD on the file nor GET works.

## Context
We have a test setup with two 60 drive servers (2x6230R, 384GB ram, 60x6TB HDD) and during our test run, a number of files say that have been uploaded but we cannot retrieve them back. MinIO is configured in cluster mode:
`MINIO_VOLUMES="http://10.255.254.1{1...2}:9000/mnt/disk{1...60}/data"`

the file system is XFS. MinIO running on bare metal Ubuntu 20.04.

Log of the problem can be seen here:
https://gist.github.com/nocturo/b688a26823a6c9afda00276b7a5b2779

## Your Environment

* Version used (`minio --version`): `2022-03-11T23:57:45Z`
* Operating System and version (`uname -a`): `Linux ceph01-tor1 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is because of the wrong code in your application https://gist.github.com/nocturo/b688a26823a6c9afda00276b7a5b2779 - you haven't even sent CompleteMultipartUpload() here that would complete the multipart upload. 

```
1647856277 HTTP/1.1 200 OK

Cache-Control: no-cache

Content-Security-Policy: block-all-mixed-content

Content-Type: text/event-stream

Strict-Transport-Security: max-age=31536000; includeSubDomains

Vary: Origin

Vary: Accept-Encoding

X-Accel-Buffering: no

X-Amz-Request-Id: 16DE5C828E0411DF

X-Content-Type-Options: nosniff

X-Xss-Protection: 1; mode=block

Date: Mon, 21 Mar 2022 09:50:40 GMT

Transfer-Encoding: chunked




1647856277 <?xml version="1.0" encoding="UTF-8"?>
 ÜﬂA@^A
```

There is no XML here for the complete multipart.

**Comment by harshavardhana** [comment]
another issue is 

```
1647856277 HEAD /testo/file1test174_1_473.bin HTTP/1.1

Authorization:AWS4-HMAC-SHA256 Credential/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1edb6048df26e706f25b4736f1ec13fa964241bc15e6c692bc3f5a662b0e3e77

host:testo.192.168.100.201

x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

x-amz-date:20220321T095117Z

```

you have `testo.192.168.100.201` - looks like you are writing a custom SDK and some custom requests - there is no way this can resolve.

**Comment by harshavardhana** [comment]
From what this looks like a client upload error 

- CompleteMultipartUpload has garbage XML
- GetObject() is performed on unresolvable endpoint

**Comment by nocturo** [comment]
@harshavardhana Looks like it was just cut off during logging. Here is the failed request again with full logging:
https://gist.github.com/nocturo/8f610bb052c655f5db194c64995aede5

and here is a good one:
https://gist.github.com/nocturo/e4e6ff65ddb6adba88ae48c3678c83df

**Comment by harshavardhana** [comment]
> @harshavardhana Looks like it was just cut off during logging. Here is the failed request again with full logging:
> https://gist.github.com/nocturo/8f610bb052c655f5db194c64995aede5
> 
> and here is a good one:
> https://gist.github.com/nocturo/e4e6ff65ddb6adba88ae48c3678c83df

Can you provide a reproducer code for this?

**Comment by nocturo** [comment]
@harshavardhana I can't share the source code as it has some proprietary libraries used from prod, but I can share the build artifact (exe) if that helps?

**Comment by harshavardhana** [comment]
> @harshavardhana I can't share the source code as it has some proprietary libraries used from prod, but I can share the build artifact (exe) if that helps?

Are you testing this on windows? And MinIO is on Windows as well?

**Comment by nocturo** [comment]
Just the test app is a Windows C++ one, MinIO is on Ubuntu 20.04 servers.

**Comment by nocturo** [comment]
We  will try to strip out out components and use your SDK and try to make a reproducer that way so we can share it.
