### ISSUE TITLE
installing under windows, when the file is written to the mounted network disk, a file path error will be prompted

### ISSUE THREAD

**Issue by rogerhesong** [minio/minio#14604]
when the file is written to the mounted network disk, a file path error will be prompted：
![image](https://user-images.githubusercontent.com/12381976/159437496-3d149942-8bff-4020-886a-a048a647c733.png)
Normal when writing to local disk

**Comment by harshavardhana** [comment]
@rogerhesong how are you running on networked path are you using `\\servername\path` style? - we expect that you run in this style

```
minio server \\servername\path
```

**Comment by rogerhesong** [comment]
> @rogerhesong how are you running on networked path are you using `\\servername\path` style? - we expect that you run in this style
> 
> ```
> minio server \\servername\path
> ```
My mount command：net use E: \\XXX-hangzhou.nas.aliyuncs.com\myshare  ,then Create a folder named hesong , and then run minio.exe server E:\hesong  --console-address ":9001"

**Comment by rogerhesong** [comment]
> @rogerhesong how are you running on networked path are you using `\\servername\path` style? - we expect that you run in this style
> 
> ```
> minio server \\servername\path
> ```


The file path is \ in front of it and / in the back. Does the program mistakenly think it is the Linux system path？
