### ISSUE TITLE
MinIO is crashing [SingleDrive] [Windows] [PopulatedDrive]

### ISSUE THREAD

**Issue by Svisstack** [minio/minio#14608]
## NOTE

After installing MinIO Server as Service using single disk standalone storage is crashing all the time when the load will appear.

## Expected Behavior

I expect that the software will not crash.

## Current Behavior

(cut)

## Possible Solution

Unfortunately, I have no idea what's happening based on the log.

## Steps to Reproduce (for bugs)

1. Start MinIO Server Single Drive Setup with data already populated in the Drive
2. Redirect load to the server
3. Wait for the crash

## Context

I'm trying to expose the S3 compatible API to our storage attached to a Windows machine to test MinIO.

## Regression

No idea.

## Your Environment

* Version used (`minio --version`):

```
minio --version
minio version RELEASE.2022-03-22T02-05-10Z
```

* Server setup and configuration:
```
<service>
  <id>MinIOExternal9002</id>
  <name>MinIOExternal9002</name>
  <description>MinIO is a high performance object storage server</description>
  <executable>minio.exe</executable>
  <env name="MINIO_ROOT_USER" value="x"/>
  <env name="MINIO_ROOT_PASSWORD" value="y"/>
  <arguments>server G:/ --address ":9002" --console-address ":9102" </arguments>
  <logmode>rotate</logmode>
</service>
```

* Operating System and version (`uname -a`):

Windows Server 2019 DataCenter

**Comment by harshavardhana** [comment]
the crash looks truncated @Svisstack can you paste the entire crash?

**Comment by Svisstack** [comment]
[external_9002.zip](https://github.com/minio/minio/files/8325901/external_9002.zip)
@harshavardhana Take a look at the archive.

**Comment by Svisstack** [comment]
@harshavardhana let me know if you see anything there and if the logs are correct; otherwise let me know how I can help identify the problem.

**Comment by harshavardhana** [comment]
> @harshavardhana let me know if you see anything there and if the logs are correct; otherwise let me know how I can help identify the problem.

Your zip file is empty @Svisstack

**Comment by Svisstack** [comment]
[external_9002.zip](https://github.com/minio/minio/files/8328392/external_9002.zip)

@harshavardhana Fixed archive.

**Comment by harshavardhana** [comment]
this is not something strange you basically ran out of threads on the system. Your system is not capable of handling more than 10,000 threads 

```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw({0x34a5ca5, 0x7ffbb39d2220})
        runtime/panic.go:1198 +0x76
runtime.checkmcount()
        runtime/proc.go:760 +0x8c
runtime.mReserveID()
        runtime/proc.go:776 +0x36
runtime.startm(0xc000090000, 0x0)
        runtime/proc.go:2477 +0x90
runtime.handoffp(0xffffffff)
        runtime/proc.go:2519 +0x2ac
runtime.retake(0xd342681c51dc)
        runtime/proc.go:5537 +0x1e7
runtime.sysmon()
        runtime/proc.go:5445 +0x377
runtime.mstart1()
        runtime/proc.go:1407 +0x9d
runtime.mstart0()
        runtime/proc.go:1365 +0x6c
runtime.mstart()
        runtime/asm_amd64.s:248 +0x5
```

**Comment by Svisstack** [comment]
@harshavardhana Did you mean it's not supported on Windows Server 2019 or did the system is misconfigured?

**Comment by kannappanr** [comment]
@Svisstack You can issue `mc admin config set <ALIAS> api requests_max=50`  or some number that will work for your setup

**Comment by harshavardhana** [comment]
> @harshavardhana Did you mean it's not supported on Windows Server 2019 or did the system is misconfigured?

No, what you are doing won't work you are exhausting the system limits.

**Comment by Svisstack** [comment]
Thanks for letting me know. If I may sugest something; rejecting the request could be better option than crashing the whole application as you will probably run into that same issue multiple times into the future if the app will keep crashing for other folks.

**Comment by Svisstack** [comment]
@harshavardhana  No guys after a little bit of thinking this is a serious bug. Windows do not have any thread limit; which mean the limit your software is hitting is probably related to the Golang itself; and it's a serious error that you will not respect that limit and crash the whole application including the 10k routines that works correctly in the moment of the crash, destabilizing the whole application and possibly corrupting the data.

**Comment by Svisstack** [comment]
Please put yourself in the user's shoes, it's hard to rely on the software that by design can crash when it will take some amount of unspecified load.

**Comment by Svisstack** [comment]
@harshavardhana @kannappanr There is a chance of comment on this matter? I'm trying to understand if I'm missing something here or indeed there is a limit in this software that will prevent full hardware saturation.

**Comment by harshavardhana** [comment]
> @harshavardhana @kannappanr There is a chance of comment on this matter? I'm trying to understand if I'm missing something here or indeed there is a limit in this software that will prevent full hardware saturation.

There is nothing to comment we have already told what you are doing is wrong. Your system is not capable and there is a top level limit in Go runtime on the number of threads. 

We can arbitrarily limit this on our end as well.

**Comment by Svisstack** [comment]
> @Svisstack You can issue `mc admin config set <ALIAS> api requests_max=50` or some number that will work for your setup

@kannappanr There is a way to set this using command line parameters?

**Comment by Svisstack** [comment]
> > @harshavardhana @kannappanr There is a chance of comment on this matter? I'm trying to understand if I'm missing something here or indeed there is a limit in this software that will prevent full hardware saturation.
> 
> There is nothing to comment we have already told what you are doing is wrong. Your system is not capable and there is a top level limit in Go runtime on the number of threads.
> 
> We can arbitrarily limit this on our end as well.

The system limits are far away as this is very powerful machine with 1TB of RAM etc; The only limit which is hit here is thread limit set arbitrarily in go. I can't saturate the hardware because of this; There is a way to change this limit? 

There is a state:
 (a) system limits are not approached
 (b) software is crashing with load
 (c) crash is causing the API not to work and break existing requests
