### ISSUE TITLE
installing under windows, when the file is written to the mounted network disk, Path separator error [Windows]

### ISSUE THREAD

**Issue by rogerhesong** [minio/minio#14605]
when the file is written to the mounted network disk, a file path error will be prompted：
![image](https://user-images.githubusercontent.com/12381976/159449658-791fd186-8e1a-48ee-b09e-65ec3b435da3.png)
![image](https://user-images.githubusercontent.com/12381976/159464776-6b79de71-4809-43b3-872e-7f2a182e4062.png)

The file path is \ in front of it and / in the back. Does the program mistakenly think it is the Linux system path？
Normal when writing to local disk

**Comment by harshavardhana** [comment]
which windows version is this? @rogerhesong

**Comment by rogerhesong** [comment]
> which windows version is this? @rogerhesong

Windows server 2019

**Comment by rogerhesong** [comment]
> which windows version is this? @rogerhesong

Windows server 2019 @harshavardhana

**Comment by rogerhesong** [comment]
> 这是哪个windows版本？@rogerhesong

minio version:RELEASE.2022-03-17T06-34-49Z

**Comment by klauspost** [comment]
Windows doesn't really care about mixed separator paths. Tried a few variations:

```Go
package main

import (
	"log"
	"os"
)

func main() {
	open("main.go")
	open(`d:\temp/main/main.go`)
	open(`c:\go\src\vendor\modules.txt`)
	open(`c:\go/src\vendor\modules.txt`)
	open(`c:\go/src/vendor/modules.txt`)
}

func open(s string) {
	log.Println("Opening", s)
	f, err := os.Open(s)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	fi, err := f.Stat()
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Opened fine, size:", fi.Size())
}
```

Output:
```
d:\temp\main
λ go run main.go
2022/03/23 10:04:24 Opening main.go
2022/03/23 10:04:24 Opened fine, size: 448
2022/03/23 10:04:24 Opening d:\temp/main/main.go
2022/03/23 10:04:24 Opened fine, size: 448
2022/03/23 10:04:24 Opening c:\go\src\vendor\modules.txt
2022/03/23 10:04:24 Opened fine, size: 920
2022/03/23 10:04:24 Opening c:\go/src\vendor\modules.txt
2022/03/23 10:04:24 Opened fine, size: 920
2022/03/23 10:04:24 Opening c:\go/src/vendor/modules.txt
2022/03/23 10:04:24 Opened fine, size: 920
```

So maybe your remote setup isn't able to handle the path for one reason or another.

**Comment by rogerhesong** [comment]
> Windows doesn't really care about mixed separator paths. Tried a few variations:
> 
> ```go
> package main
> 
> import (
> 	"log"
> 	"os"
> )
> 
> func main() {
> 	open("main.go")
> 	open(`d:\temp/main/main.go`)
> 	open(`c:\go\src\vendor\modules.txt`)
> 	open(`c:\go/src\vendor\modules.txt`)
> 	open(`c:\go/src/vendor/modules.txt`)
> }
> 
> func open(s string) {
> 	log.Println("Opening", s)
> 	f, err := os.Open(s)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer f.Close()
> 	fi, err := f.Stat()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	log.Println("Opened fine, size:", fi.Size())
> }
> ```
> 
> Output:
> 
> ```
> d:\temp\main
> λ go run main.go
> 2022/03/23 10:04:24 Opening main.go
> 2022/03/23 10:04:24 Opened fine, size: 448
> 2022/03/23 10:04:24 Opening d:\temp/main/main.go
> 2022/03/23 10:04:24 Opened fine, size: 448
> 2022/03/23 10:04:24 Opening c:\go\src\vendor\modules.txt
> 2022/03/23 10:04:24 Opened fine, size: 920
> 2022/03/23 10:04:24 Opening c:\go/src\vendor\modules.txt
> 2022/03/23 10:04:24 Opened fine, size: 920
> 2022/03/23 10:04:24 Opening c:\go/src/vendor/modules.txt
> 2022/03/23 10:04:24 Opened fine, size: 920
> ```
> 
> So maybe your remote setup isn't able to handle the path for one reason or another.

@klauspost   
I write a web application and use log4net to record logs in the form of files. It is normal to write to the mounted network disk
，as shown in the screenshot below：
![image](https://user-images.githubusercontent.com/12381976/159727449-bf9acc8d-a97d-49ec-b01f-cdb4ba934644.png)
or
![image](https://user-images.githubusercontent.com/12381976/159727526-2af630ef-08b7-47e6-8a7e-a053cf4f5e72.png)

It's all normal

**Comment by rogerhesong** [comment]
I have another question.  use the same environment, the latest versions of Windows Server 2019 and Minio, write the path on the mounted network disk, and then use NSSM or winsw tool to register and run in the background, it will be prompted that you have no permission：
![image](https://user-images.githubusercontent.com/12381976/161364277-ad68580c-8045-45a7-92d3-46ceead396d2.png)
the network disk has permission, you can read and write files directly, and windows service also uses the maximum permission of localsystem  @harshavardhana @klauspost

**Comment by harshavardhana** [comment]
Unable to reproduce this issue, looks like an environmental problem on your end on your OS.
