### ISSUE TITLE
Minio Service Restarting continuously on some servers

### ISSUE THREAD

**Issue by saurabhp0119** [minio/minio#14603]
The MinIO service on some servers in a cluster is restarting continuously with high ram and cpu utilisation

## Current Behavior
The service restarts every 10 minutes or so, sometimes faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
The following error keeps repeating in the log
API: PutObject(bucket=cis-production, object=corpus=universities/source=niche-universities-source9/year=2021/month=11/day=18/hour=16/098093cd57fffcfe012e6aeacbb43537)
Time: 16:17:03 UTC 11/18/2021
DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
RequestID: 16B8B03894607B68
RemoteHost: 127.0.0.1
Host: 10.10.0.100:8991
UserAgent: MinIO (Linux; x86_64) minio-py/6.0.2
Error: Drive http://10.10.0.109:8991/mnt/drive4, path (cis-production/corpus=universities/source=niche-universities-source9/year=2021/month=11/day=18/hour=16/098093cd57fffcfe012e6aeacbb43537) returned an error (Server expects 'storage' API version 'v36', instead found 'v36' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-06-07T21-40-51Z)) (*fmt.wrapError)
       4: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: internal/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/erasure-metadata-utils.go:139:cmd.readAllFileInfo.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: HeadObject(bucket=cis-production, object=corpus=journals/source=ingentaconnect/year=2021/month=11/day=18/hour=16/f13ffc2363bc52e3942b5a8426cddaf6)
Time: 16:17:04 UTC 11/18/2021
DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
RequestID: 16B8B038E53DC346
RemoteHost: 127.0.0.1
Host: 10.10.0.100:8991
UserAgent: MinIO (Linux; x86_64) minio-py/6.0.2
Error: Drive http://10.10.0.109:8991/mnt/drive4, path (cis-production/corpus=journals/source=ingentaconnect/year=2021/month=11/day=18/hour=16/f13ffc2363bc52e3942b5a8426cddaf6) returned an error (Server expects 'storage' API version 'v36', instead found 'v36' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-06-07T21-40-51Z)) (*fmt.wrapError)
       4: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: internal/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/erasure-metadata-utils.go:139:cmd.readAllFileInfo.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: GetObject(bucket=cis-production, object=corpus=media-corpus/source=medium/year=2021/month=11/day=18/hour=16/0eba6b71b38e7e4138f0235ae0c8f089)
Time: 16:17:04 UTC 11/18/2021
DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
RequestID: 16B8B03925EDD0B8
RemoteHost: 127.0.0.1
Host: 10.10.0.100:8991
UserAgent: MinIO (Linux; x86_64) minio-py/6.0.2
Error: Drive http://10.10.0.109:8991/mnt/drive4, path (cis-production/corpus=media-corpus/source=medium/year=2021/month=11/day=18/hour=16/0eba6b71b38e7e4138f0235ae0c8f089) returned an error (Server expects 'storage' API version 'v36', instead found 'v36' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-06-07T21-40-51Z)) (*fmt.wrapError)
       4: internal/logger/logonce.go:54:logger.(*logOnceType).logOnceIf()
       3: internal/logger/logonce.go:94:logger.LogOnceIf()
       2: cmd/erasure-metadata-utils.go:139:cmd.readAllFileInfo.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

## Your Environment

Version used (minio --version):Version: 2021-06-07T21:40:51Z
Server setup and configuration: distributed MinIO running on bear-metal servers. (20 machines 10 disk each)
Operating System and version (uname -a): Linux hz-minio01.nferx.com 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Version used (minio --version):Version: 2021-06-07T21:40:51Z

Please upgrade @saurabhp0119

**Comment by harshavardhana** [comment]
> Server setup and configuration: distributed MinIO running on bear-metal servers. (20 machines 10 disk each)

Production systems please buy a subscription https://min.io/pricing - or upgrade to latest.

**Comment by saurabhp0119** [comment]
Service log file.
[service.log.tar.gz](https://github.com/minio/minio/files/8321162/service.log.tar.gz)
