### ISSUE TITLE
Grafana Dashboard: Variable "DS_PROMETHEUS" not set

### ISSUE THREAD

**Issue by ParanoidAndroidDev** [minio/minio#14618]
I try to use the MinIO Overview Dashboard with the Grafana Operator in Kubernetes. I can deploy the dashboard using the url to the minio-overview.json but when loading the site in Grafana it fails with errors (see screenshot)

## Expected Behavior

The dashboard should be loaded without errors

## Current Behavior

When loading the site of the dashboard inside Grafana I get the following errors:
![Screenshot 2022-03-24 102723](https://user-images.githubusercontent.com/48406717/159885398-e0068f4d-c93f-4f4b-9a22-5a373d5d3dbb.png)

## Possible Solution

When I manually define the "DS_PROMETHEUS" variable as a data source in the Grafana UI, then it works

## Steps to Reproduce (for bugs)

1. Deploy Grafana Operator in Kubernetes Cluster
2. Create a GrafanaDashboard resource with the URL of the MinIO Overview Dashboard (https://raw.githubusercontent.com/minio/minio/master/docs/metrics/prometheus/grafana/minio-overview.json)
3. Navigate to the dashboard inside Grafana

## Your Environment

* Kubernetes Version: 1.21.5
* Grafana Operator Version: 4.2.0
* Grafana Operator Image: docker.io/bitnami/grafana-operator:4.2.0-debian-10-r4

**Comment by harshavardhana** [comment]
It is meant for you to define it, a properly configured Grafana automatically sets this value.

**Comment by ParanoidAndroidDev** [comment]
Thank you for your reply!
It helped me figure out where my error was. I found that you can add definitions of datasources in your spec file for the GrafanaDashboard Resource in Kubernetes. But since I am using a custom Helm template library to generate the spec files which don't support that, I didn't see it.
Thanks again!
