### ISSUE TITLE
mc: <ERROR> Unable to set 'storage_class standard=EC:10 rrs=' to server. Standard storage class parity 10 should be less than or equal to 2.

### ISSUE THREAD

**Issue by wswn5456** [minio/minio#14615]
hi, I'm testing MinIO , 
my version:   
`RELEASE.2022-03-17T06-34-49Z.` 
my cluster:
`CentOS 7.9, update to  Kernel 5.4.184-1.el7.elrepo.x86_64 
4 nodes * 5 drivers   `
I tried to set standard=EC:10 ,but faild. 
`mc admin config set myminio storage_class standard=EC:10 rrs=`
why it should be less than or equal to 2 ?

**Comment by harshavardhana** [comment]
EC value is parity it cannot be greater than set size / 2

**Comment by wswn5456** [comment]
thx for the explanation, I thought it was drivers / 2 before.
