### ISSUE TITLE
Access issue after last update

### ISSUE THREAD

**Issue by Romeo84** [minio/minio#14622]
Hello!

After I updated last version Minio via instruction provided via following link

[https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-18-04](url)

I can't login via my dot net client using Your Minio S3 client, also now I can't login via WinScp client (plz see attached screenshot).

<a href='https://postimg.cc/TpfRXcqP' target='_blank'><img src='https://i.postimg.cc/TpfRXcqP/Scr001.png' border='0' alt='Scr001'/></a>

<a href='https://postimg.cc/NKxDzQGM' target='_blank'><img src='https://i.postimg.cc/NKxDzQGM/Scr002.png' border='0' alt='Scr002'/></a>

I tried to give full permissions on various service account and user, even try with root (super) user. But in didn't help.

Could You plz advice either what did I wrong or there some bug in last version? Thanks a lot!

My environment is: Ubuntu Server 20.04 LTS

**Comment by harshavardhana** [comment]
@Romeo84 can you provide more details

**Comment by Romeo84** [comment]
Sure, hare are screens of my user settings in minio web-console

<a href="https://postimg.cc/jwZNKjwg" target="_blank"><img src="https://i.postimg.cc/90jBdRWh/Scr003.png" alt="Scr003"/></a><br/><br/>
<a href="https://postimg.cc/D40GzK12" target="_blank"><img src="https://i.postimg.cc/VvBWDf6b/Scr004.png" alt="Scr004"/></a><br/><br/>
<a href="https://postimg.cc/3Wxm12VP" target="_blank"><img src="https://i.postimg.cc/gcvsYDDk/Scr005.png" alt="Scr005"/></a><br/><br/>
<a href="https://postimg.cc/s1HSNvR1" target="_blank"><img src="https://i.postimg.cc/SNkrjMTL/Scr006.png" alt="Scr006"/></a><br/><br/>


Is it enough information? 
Thanks!

**Comment by harshavardhana** [comment]
I can't tell what is wrong @Romeo84

**Comment by Romeo84** [comment]
It seems to me eventually I'll have to download one of previous version on minio..
But we will see, maybe someone could advise me.

**Comment by harshavardhana** [comment]
> It seems to me eventually I'll have to download one of previous version of minio..
> But we will see, maybe someone could advise me.

yes what is wrong I am not sure yet.

**Comment by Romeo84** [comment]
Solved - was problems with user access to storage folder on disk.
