### ISSUE TITLE
Very low upload speed on vps with windows server operating system

### ISSUE THREAD

**Issue by sei666** [minio/minio#14626]
I began to check the exe version of minio and found that on all current versions of the windows server operating system, the upload of files is very slow if you upload them from a local computer. Archived versions of minio were checked and it turned out that this problem started with version minio.RELEASE.2020-10-18T21-54-12Z and all subsequent versions also suffer from this problem. Latest version of minio that works fine minio.RELEASE.2020-10-12T21-53-21Z. 
Operating systems tested: Windows Server 2012, Windows Server 2016,Windows Server 2019, Windows Server 2022.

**Comment by harshavardhana** [comment]
Nothing is really shared from point of view of application and reproducer.

Closing.
