### ISSUE TITLE
Minio API responded with message=Unsuccessful response from server without XML error: The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by rogerhesong** [minio/minio#14633]
When I use the net SDK to do the PresignedPostPolicyAsync and return it to the front end for use, when I use the new minioclient, when the endpoint is the domain name, I will be prompted that the underlying connection was closed. This domain name has been bound to port 9000. When I use IP to bring port 9000, it is normal

## Expected Behavior

![image](https://user-images.githubusercontent.com/12381976/160248105-bc453c4f-f3d2-45db-8bac-3d3ff3b67f0d.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/12381976/160247367-5d6bf437-d505-496b-9957-7c040a7daafc.png)

##  Environment
* Version used (RELEASE.2022-03-17T06-34-49Z):
* Server setup and configuration:
* Operating System and version (minio server: Windows server 2019，Minio for PresignedPostPolicyAsync： .NET SDK 1.1.1):

**Comment by harshavardhana** [comment]
This is because your DNS doesn't resolve properly from the client

**Comment by rogerhesong** [comment]
> This is because your DNS doesn't resolve properly from the client

@harshavardhana but I can use DNS to access pictures from my browser，the pictures  uploaded through 9001 port
