### ISSUE TITLE
Gateway with kms single encryption not working

### ISSUE THREAD

**Issue by gsardone** [minio/minio#14644]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 
Minio Gateway single encryption kms not working

## Expected Behavior
Set encryption on bucket to perform single encryption at the gateway side

## Current Behavior
When on console try to add encryption on bucket with KMS and kms key id the following error is returned:

Internal server erro
"A header you provided implies functionality that is not implemented"

## Steps to Reproduce (for bugs)

1. Deploy minio server
2. Deploy kms server (https://github.com/minio/kes/wiki/Filesystem-Keystore)
3. Deploy minio gateway with kms env configuration
4. Enable bucket encryption

## Context
Encryption data

## Your Environment
Minio version DEVELOPMENT.2022-03-17T02-57-36Z
Kes version 0.18.0
Minio gateway version DEVELOPMENT.2022-03-17T02-57-36Z

**Comment by harshavardhana** [comment]
We do not support single encryption at gateway anymore.
