### ISSUE TITLE
Multipart upload fails with InvalidPart

### ISSUE THREAD

**Issue by simaotwx** [minio/minio#14651]
We use Nextcloud in conjunction with MinIO Gateway so that we can use our Azure Blob Storage for storing our data.
After updating our system, I noticed that uploads of bigger files aren't working.
This is because multipart upload is used.

## Expected Behavior

The upload should succeed (see RELEASE.2022-03-17T06-34-49Z)

## Current Behavior

The upload fails with 400 Bad Request and following message (shortened for brevity):
```
InvalidPart (client): One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
```
This happens on RELEASE.2022-03-24T00-43-44Z and later (older versions since RELEASE.2022-03-17T06-34-49Z may be affected as well but I haven't tested them).

## Possible Solution

Revert relevant commits or fix regression (see below)

## Steps to Reproduce (for bugs)

1. Set up MinIO Gateway (command `minio gateway azure`) and set up and configure Nextcloud 23.0.3 to use MinIO as S3 storage
2. Upload a larger file, for example, size of 100 MiB
3. Upload runs for a moment and then aborts with an S3 error
4. The error in the Nextcloud log is "InvalidPart (client): One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag."

(Logs not captured since it's a live production system and I can't set it back to the broken version)

## Context

This issue broke our Nextcloud instance in production. A user was trying to upload large files and it failed resulting in a Support Ticket.

## Regression

Yes.

I think following links are related:
https://github.com/minio/minio/pull/14631
https://github.com/minio/minio/pull/14627
https://github.com/minio/minio/pull/14578
https://github.com/minio/minio/pull/14578#issuecomment-1072920804

## Your Environment

Version used: [RELEASE.2022-03-26T06-49-28Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-03-26T06-49-28Z)
Server setup:
* MinIO in Docker (Docker Compose v2)
* Used on local machine only
* No special MinIO configuration
* `minio gateway azure`
* Running on a Linux VM (Ubuntu 20.04)
* VM runs on Azure and is stateless (image built using Packer, deployed using Terraform, uses separate disk for data, OS disk is always fresh)
* Operating System and version: `Linux twx-nextcloud 5.13.0-1017-azure #19~20.04.1-Ubuntu SMP Mon Mar 7 11:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```

**Comment by harshavardhana** [comment]
Gateway will be removed, so we are not working on anything gateway specific. Refer #14331

**Comment by simaotwx** [comment]
IMO that's not fair as the last version supporting Gateway would be left broken.

**Comment by harshavardhana** [comment]
> IMO that's not fair as the last version supporting Gateway would be left broken.

No one asked you to upgrade @simaotwx use the one that works for you. We haven't added anything new for 2yrs.
