### ISSUE TITLE
panic: "GET .............": invalid WriteHeader code 0

### ISSUE THREAD

**Issue by hkirov** [minio/minio#14652]
After update to 2022-03-26T06:49:28Z we started to observe minio panic messages in syslog such as:
```
Mar 29 12:14:51 tafl-serv1 minio[2985]: panic: "GET /content/LkcB": invalid WriteHeader code 0
Mar 29 12:14:51 tafl-serv1 minio[2985]: panic: "GET /content/docs/cplugError.html/": invalid WriteHeader code 0

```
Couple of full panic logs are in attached file.
[minio_panic.txt](https://github.com/minio/minio/files/8371140/minio_panic.txt)

## Expected Behavior

No panic events and proper error message of the issue if any.

## Current Behavior

Panic messages in minio log.

## Regression

Yes. There were no such messages in previous version installed. Not sure which one that was. Most likely 2022-02-18T01:50:10Z.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-03-26T06-49-28Z
* Server setup and configuration: distributed bare-metal installation
* Operating System and version (`uname -a`): Linux tafl-serv1 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Looks like a regression from https://github.com/minio/minio/pull/14345/files#diff-e7bc5ddd6854880db5918a96700afb6815d4c52c9a66734d00ef9974e6c8ebc4R429

Seems we can get to object-handlers.go:456 with a nil error, which returns `var noError = APIError{}` giving a code 0. It will be a few days until I can get to this, but maybe @poornas can take a look.
