### ISSUE TITLE
Tiering with any S3-compatible object storage

### ISSUE THREAD

**Issue by pongnguy** [minio/minio#14658]
**Is your feature request related to a problem? Please describe.**
I would like to cold storage stale data to an S3 storage provider not presently configured in Minio tiering, however it is S3 compatible.

**Describe the solution you'd like**
Minio supports tiering to warm/cold storage using lifecycle rules.  However the tiering appears to be limited to specific providers (i.e. another Minio cluster, AWS S3, etc.).  Every S3 implementation is slightly different (for example, the AWS S3 options asks me for the region, and the list is specific to AWS).  Therefore it is not clear that picking Minio would work reliably with a different (although S3 compatible) storage provider.  Would it be possible to add a generic S3 compatible storage provider for tiering?

**Describe alternatives you've considered**
I tried creating tiering to another Minio cluster, however I would like to use a different S3 storage provider for cold storage.

**Additional context**
There are other well-known and reliable object storage providers (e.g. Backblaze B2) which could be used for tiering.

**Comment by ravindk89** [comment]
I do not believe we have any restrictions requiring tiering use MinIO as the S3 remote.

https://docs.min.io/minio/baremetal/lifecycle-management/transition-objects-to-s3.html

The requirement is, as you noted, an S3-compatible remote. We have no control over whether other object storage providers have correctly implemented the S3 specification.

You would have to test against other providers and see what happens. If it fails, the first step would be to coordinate with that team to ensure that their system is appropriately handling S3 API calls. If so, we can then look and see if there is a bug in handling on our end. I don't know of any users personally using something like B2, but Im not aware of  any reason that would not work given the control knobs we provide for configuring a remote tier.

**Comment by pongnguy** [comment]
Thank you.
