### ISSUE TITLE
Support custom kafka Producer.RequiredAcks

### ISSUE THREAD

**Issue by cobolbaby** [minio/minio#14663]
The problem we encountered is that when the Kafka QPS is high, it is difficult to guarantee the stability of the Kafka cluster, and the request response time has intermittent jitter. The bottleneck is the synchronization of partition replicas. 

So I hope that users can customize the level of ACK to ensure that Minio is efficient enough when pushing a large number of messages. For scenarios with huge write volume, `sarama.WaitForAll` may not be the best choice.

https://github.com/minio/minio/blob/fc9668baa51a3652db961f3f1a617a3eade160f9/internal/event/target/kafka.go#L289-L291

**Comment by harshavardhana** [comment]
So not see a need to add this without sacrificing certain delivery guarantees.

Please update why this is needed with more clarity.

**Comment by cobolbaby** [comment]
@harshavardhana Relevant explanations have been added.  Could you please reopen the issue?
