### ISSUE TITLE
Unable to use helm chart to install minio

### ISSUE THREAD

**Issue by lcphill** [minio/minio#14679]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Following these instructions: https://github.com/minio/minio/tree/master/helm/minio

## Expected Behavior

Expected behavior: Helm chart install completes, all artifacts working.

## Current Behavior

Unable to provide credentials/secret (various ways/means attempted).

Effectively, this is what I am unable to get passed:

$ kubectl logs minio-thanos-54fd86f899-drntb -n thanos
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters

Using this command for helm install:

$ helm install minio-thanos ./minio -n thanos --debug --set existingSecret=thanos-minio-secret

Note: I created the same secret in both the default and the thanos namespace (all to no avail):

$ k describe secret thanos-minio-secret -n default
$ k describe secret thanos-minio-secret -n thanos
Name:         thanos-minio-secret
Type:  Opaque
Data
====
rootPassword:  5 bytes
rootUser:      5 bytes

As for minio/values.yaml, I have tried every combination / every variation of:

rootUser: <provide a value or not, does not succeed either way>
rootPassword: <provide a value or not, does not succeed either way>

existingSecret: <provide a value or not, does not succeed either way>

## Possible Solution

Edit instructions such that we (users) can follow and successfully run helm install.

## Steps to Reproduce (for bugs)

1. Follow the instructions from this page: https://github.com/minio/minio/tree/master/helm/minio
2. Also see above.
3.
4.

## Context

Context: attempting to create a demonstration S3 store to use with thanos' storage.

## Your Environment

* Version used (`minio --version`): The helm chart says: 3.6.3
* Server setup and configuration: Linux/x64
* Operating System and version (`uname -a`): 5.16.10-1.el7.elrepo.x86_64 (Linux/x64)

**Comment by harshavardhana** [comment]
> #
> rootPassword: 5 bytes rootUser: 5 bytes

A you haven't specified the correct valid length for the rootPassword - check the error message printed.

**Comment by lcphill** [comment]
Hi,

Please elaborate on the credential requirements, or point us to the wiki page / README page the specifies the credential requirements, such as: minimum length (not just passphrase, but also user name), any special characters (such as characters sets, repeating characters, character case and so forth).

Thank you.

**Comment by harshavardhana** [comment]
> Hi,
> 
> Please elaborate on the credential requirements, or point us to the wiki page / README page the specifies the credential requirements, such as: minimum length (not just passphrase, but also user name), any special characters (such as characters sets, repeating characters, character case and so forth).
> 
> Thank you.

Access key length 3 minimum - any ASCII
Secret key length 8 minimum - any ASCII

**Comment by lcphill** [comment]
Hi, Correcting my 'secret' to be >= 8 characters, the minio pod is created. However, the "make user job/pod" is failing:

```
$ helm install minio-thanos ./minio -n thanos --debug --set existingSecret=thanos-minio-secret
pod/minio-thanos-54fd86f899-47vl6                            1/1     Running   0          17s
pod/minio-thanos-make-user-job-6rpmm                         0/1     Error     1          17s
$ k logs minio-thanos-make-user-job-6rpmm -n thanos
Connecting to MinIO server: http://minio-thanos:9000
Added `myminio` successfully.
Creating user 'minio'
mc: <ERROR> Unable to add new user. The secret key is invalid. (secret key length should be between 8 and 40).
```

Where do I set the credentials for the "make user" job/pod?  Is that in values somewhere?
I left root user/root passhprase as blank in values.yaml (I did set "existingSecret" in values.yaml, which I presume is duplicitous with stating the same at the command line).

**Comment by lcphill** [comment]
Ahh, I think I found it:

```
users:
  ## Username, password and policy to be assigned to the user
  ## Default policies are [readonly|readwrite|writeonly|consoleAdmin|diagnostics]
  ## Add new policies as explained here https://docs.min.io/docs/minio-multi-user-quickstart-guide.html
  ## NOTE: this will fail if LDAP is enabled in your MinIO deployment
  ## make sure to disable this if you are using LDAP.
  - accessKey: minio
    secretKey: minio
```

^ Presume correct the above and resbumit.

**Comment by lcphill** [comment]
With correction above, two more issues:

1. Make User -- I guess I can hunt in value.yamls for configmap..

```
Warning  FailedMount  93s (x10 over 5m42s)  kubelet            MountVolume.SetUp failed for volume "minio-configuration" : configmap "minio-thanos" not found
```

2. Make Bucket:

```
$ k logs minio-thanos-make-bucket-job-8wblm -n thanos
Connecting to MinIO server: http://minio-thanos:9000
Added `myminio` successfully.
Bucket 'thanos-sidecar' already exists.
Suspending versioning for 'thanos-sidecar'
mc: <ERROR> Unable to suspend versioning. A header you provided implies functionality that is not implemented.
```

^ I'll try to battle (or just comment out from values.yaml), but I cannot turn up anything related to the 'suspend versioning' issue a la search.

**Comment by lcphill** [comment]
[ _battling grub set root_ ... ]

I was able to get through the helm install by commented out the bucket section. I can make my own bucket.
Just following up.

**Comment by trymzet** [comment]
Yeah this pw length thing also caught me, plus another missing doc that if you specify `--set buckets[0].name`, you must also specify the bucket `policy` and `purge` parameters, as they don't seem to have any defaults set and this breaks things down the line.
