### ISSUE TITLE
listusers hang when  IAM sub-system initialization fails

### ISSUE THREAD

**Issue by polaris-megrez** [minio/minio#14674]
## Expected Behavior
IAM sub-system initialization fails
![image](https://user-images.githubusercontent.com/92494511/161235109-a6f61907-fbfb-476d-860a-af4bade7017b.png)

Execute GET on /minio/admin/v3/list-users failed
## Current Behavior
Interface /minio/admin/v3/list-users hang

## Steps to Reproduce (for bugs)
Run Latest MinIO and create a single version first
```
exprot access_key=w7fs7xk6gikiRbbCJY
export secret_key=hvGcKlh+2IMNYbUa
minio server -C /home/minio/.minio --quiet  /export1
```
stop MinIO  and change access_key secret_key
```
exprot access_key=FG5jm7bUE0adThi2ob
export secret_key=Rgd9DI0,[i5%T@u=V
minio server -C /home/minio/.minio --quiet  /export1
```
IAM sub-system initialization fails
```
API: SYSTEM()
Time: 13:59:08 UTC 04/01/2022
DeploymentID: 55e9b21c-c811-43e7-a61f-ca93c3ed0bca
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
```
GET on /minio/admin/v3/list-users hang

## Context
Unexpected listing behavior

## Regression
Not sure.

## Your Environment
Master and previous versions

**Comment by harshavardhana** [comment]
The correct way to get out of this is purge all the .minio.sys/config/iam 

Also changing access credentials has no bearing on the failure to load users. 

Looks like you have an old release locally and you never really migrated properly.
