### ISSUE TITLE
decommission Fail

### ISSUE THREAD

**Issue by k8ses** [minio/minio#14675]
## Expected Behavior
decommission a server poll

## Current Behavior
I tried to decommission a sever poll . Then it is still alive.

## Possible Solution
My command is wrong.

## Steps to Reproduce (for bugs)
1. docker pull minio/minio:latest
2. docker run -itd --network=host --name=minio-test -v /data/minio1:/data1 -v /data/minio2:/data2 -e "MINIO_ROOT_USER=minio" -e "MINIO_ROOT_PASSWORD=heLlOMinio2022" -e "MINIO_PROMETHEUS_AUTH_TYPE=public" minio/minio:latest server http://minio{1...2}/data{1...2}  http://minio{3...4}/data{1...2} --address :8900 --console-address ":8901"
3. upload files
4. ./mc alias set minio http://ip:8900 minio heLlOMinio2022
5. ./mc admin decommission status minio
6. ./mc admin decommission cancel minio/ http://minio{3...4}/data{1...2} --debug 

## Context
I like minio . So I want to test all situations of minio .

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-03-05T06-32-39Z
* Server setup and configuration: default 
* Operating System and version (`uname -a`): Centos 7.5

**Comment by harshavardhana** [comment]
@k8ses you didn't even attempt to decommission all you did was cancel the decommission. Canceling decommission  means your pool is still alive.

**Comment by k8ses** [comment]
@harshavardhana I'm sorry for my mistake.
