### ISSUE TITLE
Error: unknown type of IAM file listed

### ISSUE THREAD

**Issue by hkirov** [minio/minio#14701]
After update to RELEASE.2022-04-01T03-41-39Z "unknown type of IAM file" error messages frequently started to appear in minio logs. There were no such errors in RELEASE.2022-03-26T06-49-28Z. The error messages looks like:

>  API: SYSTEM()
>  Time: 07:51:04 UTC 04/06/2022
>  DeploymentID: 2eee7e69-2611-4406-ae62-3aa3c57f876c
>  Error: unknown type of IAM file listed: config/history/fde61d27-5959-46d7-812a-f45901500e1d.kv (*errors.errorString)
>         5: cmd/iam-object-store.go:452:cmd.(*IAMObjectStore).listAllIAMConfigItems()
>         4: cmd/iam-object-store.go:460:cmd.(*IAMObjectStore).loadAllFromObjStore()
>         3: cmd/iam-store.go:436:cmd.(*IAMStoreSys).LoadIAMCache()
>         2: cmd/iam.go:187:cmd.(*IAMSys).Load()
>         1: cmd/iam.go:390:cmd.(*IAMSys).watch()

## Regression
 Yes

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-04-01T03-41-39Z
* Server setup and configuration: distributed bare-metal installation
* Operating System and version (`uname -a`): Linux tafl-serv3 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
its harmless, ignore its fixed in #14698
