### ISSUE TITLE
Stale upload directories not removed

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#14718]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

It looks like stale empty upload directories are left behind even after cleanup routine was run. See below,

[mshanmu@minio-n2 multipart]$ pwd
/mnt/vdb/vol22/data/.minio.sys/multipart
[mshanmu@minio-n2 multipart]$ ls -lR
.:
total 0
drwxr-sr-x. 2 adminuser adminuser 6 Feb  8 11:51 24756df80332fde63ce51d4d5fdff5c3929e02fc05e5694ffcaa7f98d55ff0c7
drwxr-sr-x. 2 adminuser adminuser 6 Mar 23 13:48 38fbbf0a3c70b98a951bad333c26420f9ded9ce06643ac5752217ddf2ef409e5
drwxr-sr-x. 2 adminuser adminuser 6 Feb  8 11:50 4c748978d4d114bafbbc2b67ff820ee3742b3646a4faf65101c8ae0f83436486
drwxr-sr-x. 2 adminuser adminuser 6 Feb  8 11:54 8853286857779ea86141cb3a6924886244ebcde8042f808d096d6d7ff7a263a1
drwxr-sr-x. 2 adminuser adminuser 6 Feb  8 11:54 b06a7ef2fcb1610a93efa6ce5b0e331e0750525add25c1e38704b629090abd35

./24756df80332fde63ce51d4d5fdff5c3929e02fc05e5694ffcaa7f98d55ff0c7:
total 0

./38fbbf0a3c70b98a951bad333c26420f9ded9ce06643ac5752217ddf2ef409e5:
total 0

./4c748978d4d114bafbbc2b67ff820ee3742b3646a4faf65101c8ae0f83436486:
total 0

./8853286857779ea86141cb3a6924886244ebcde8042f808d096d6d7ff7a263a1:
total 0

./b06a7ef2fcb1610a93efa6ce5b0e331e0750525add25c1e38704b629090abd35:
total 0
[mshanmu@minio-n2 multipart]$ 

## Expected Behavior

No empty directories are left behind.

## Current Behavior

Lots of empty directories left behind under .minio.sys/multipart directory

## Possible Solution

Manually remove

## Steps to Reproduce (for bugs)

1. Create a bucket
2. Using mc, copy a large file to the bucket and cancel it before it completes
3. Wait for the cleanup routine to run
4. Notice empty directories under .minio.sys/multipart directory

## Context

Using kubernetes, on container creation, it takes a very long time for the container creation to complete, since, kubernetes tries to chown/chmod all directories and files during mounting of PV.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-01-08T03-11-54Z
* Server setup and configuration: Kubernetes
* Operating System and version (`uname -a`): Linux

**Comment by harshavardhana** [comment]
They are removed in intervals every 6 hours, 24 hours and older

```
stale_uploads_expiry            (duration)  set to expire stale multipart uploads older than this value, defaults to 24 hours
stale_uploads_cleanup_interval  (duration)  set to change intervals when stale multipart uploads are expired, defaults to every 6 hours
```
 
Make it faster if you want.

**Comment by harshavardhana** [comment]
Also please upgrade this @mshanmu

**Comment by mshanmu** [comment]
@harshavardhana , Please take a closer look into the issue. This happens after stale uploads cleanup routine was run. The cleanup routine does remove the part files and related directories, but, it seems to leave out the root directory.

Will upgrade and let you know as well.

**Comment by harshavardhana** [comment]
> @harshavardhana , Please take a closer look into the issue. This happens after stale uploads cleanup routine was run. The cleanup routine does remove the part files and related directories, but, it seems to leave out the root directory.

This was fixed in the past, so please upgrade and let us know if the issue persists. Sticking to older releases won't do you any good.

**Comment by mshanmu** [comment]
I have upgraded the cluster to RELEASE.2022-04-01T03-41-39Z and setup a 1 hour interval.

[mshanmu@minio-m1 MinIO]$ mc admin config get minio api
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_workers=250 replication_failed_workers=8 transition_workers=100 stale_uploads_cleanup_interval=1h stale_uploads_expiry=1h delete_cleanup_interval=5m disable_odirect=off gzip_objects=off 
[mshanmu@minio-m1 MinIO]$

[mshanmu@minio-n1 multipart]$ pwd
/mnt/vdb/vol24/data/.minio.sys/multipart
[mshanmu@minio-n1 multipart]$ ls -lR
.:
total 0
drwxr-sr-x. 3 adminuser adminuser 50 Apr  8 18:55 9f644968d592995287d42a0a5c8158a6121ca66a76d4c89f54193777def7835d
drwxrwsr-x. 2 adminuser adminuser  6 Mar 23 13:57 deacc21523d8c52886849f457483280217647e53646c0c4f14ea867cf0720461
drwxrwsr-x. 3 adminuser adminuser 50 Apr  8 16:38 e84e6f36826b0bb14753c0a3db4d79fb0f530a2631c8b5cd2f8e3824fb15738a

./9f644968d592995287d42a0a5c8158a6121ca66a76d4c89f54193777def7835d:
total 0
drwxr-sr-x. 3 adminuser adminuser 65 Apr  8 18:55 0ef76124-6f0d-473a-a6aa-7077aa1060c5

./9f644968d592995287d42a0a5c8158a6121ca66a76d4c89f54193777def7835d/0ef76124-6f0d-473a-a6aa-7077aa1060c5:
total 4
drwxr-sr-x. 2 adminuser adminuser  34 Apr  8 18:55 d120cef0-da83-406a-a950-36748d734218
-rw-r--r--. 1 adminuser adminuser 390 Apr  8 18:55 xl.meta

./9f644968d592995287d42a0a5c8158a6121ca66a76d4c89f54193777def7835d/0ef76124-6f0d-473a-a6aa-7077aa1060c5/d120cef0-da83-406a-a950-36748d734218:
total 16392
-rw-r--r--. 1 adminuser adminuser 8389120 Apr  8 18:55 part.2
-rw-r--r--. 1 adminuser adminuser 8389120 Apr  8 18:55 part.5

./deacc21523d8c52886849f457483280217647e53646c0c4f14ea867cf0720461:
total 0

./e84e6f36826b0bb14753c0a3db4d79fb0f530a2631c8b5cd2f8e3824fb15738a:
total 0
drwxrwsr-x. 3 adminuser adminuser 65 Apr  8 16:38 c989eb1a-89c3-4312-a118-6f527b61d0b0

./e84e6f36826b0bb14753c0a3db4d79fb0f530a2631c8b5cd2f8e3824fb15738a/c989eb1a-89c3-4312-a118-6f527b61d0b0:
total 4
drwxrwsr-x. 2 adminuser adminuser  62 Apr  8 16:38 a41e3e4a-4832-4af9-addf-baec4981a792
-rw-rw-r--. 1 adminuser adminuser 480 Apr  8 16:38 xl.meta

./e84e6f36826b0bb14753c0a3db4d79fb0f530a2631c8b5cd2f8e3824fb15738a/c989eb1a-89c3-4312-a118-6f527b61d0b0/a41e3e4a-4832-4af9-addf-baec4981a792:
total 32784
-rw-rw-r--. 1 adminuser adminuser 8389120 Apr  8 16:38 part.1
-rw-rw-r--. 1 adminuser adminuser 8389120 Apr  8 16:38 part.2
-rw-rw-r--. 1 adminuser adminuser 8389120 Apr  8 16:38 part.4
-rw-rw-r--. 1 adminuser adminuser 8389120 Apr  8 16:38 part.5
[mshanmu@minio-n1 multipart]$ 

Will let you know the results on Monday.

**Comment by mshanmu** [comment]
[mshanmu@minio-n1 multipart]$ ls -lR
.:
total 0
drwxrwsr-x. 2 adminuser adminuser 6 Mar 23 13:57 deacc21523d8c52886849f457483280217647e53646c0c4f14ea867cf0720461

./deacc21523d8c52886849f457483280217647e53646c0c4f14ea867cf0720461:
total 0
[mshanmu@minio-n1 multipart]$ 

It looks like the new ones were cleaned up, but the older ones still are not cleaned up.

**Comment by harshavardhana** [comment]
> [mshanmu@minio-n1 multipart]$ ls -lR .: total 0 drwxrwsr-x. 2 adminuser adminuser 6 Mar 23 13:57 deacc21523d8c52886849f457483280217647e53646c0c4f14ea867cf0720461
> 
> ./deacc21523d8c52886849f457483280217647e53646c0c4f14ea867cf0720461: total 0 [mshanmu@minio-n1 multipart]$
> 
> It looks like the new ones were cleaned up, but the older ones still are not cleaned up.

Old ones will not be that is expected.

**Comment by mshanmu** [comment]
Thanks @harshavardhana
