### ISSUE TITLE
How to configure remove the minio tmp file .minio.sys/tmp quickly?

### ISSUE THREAD

**Issue by shy-stone** [minio/minio#14715]
## NOTE
Hello,When I write a lot of data into minio, the temporary file dir. named like .minio.sys/tmp/ in Minio grows too fast. How to modify the configuration of minio to quickly delete the temporary files? Temporary files take up a lot of space。

minio version RELEASE.2022-02-07T08-17-33Z
The minio.cnf like this
```
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=minio!@#
MINIO_VOLUMES="http://10.206.16.103/iotp/data/env/minio/data1 http://10.206.16.103/iotp/data/env/minio/data2 http://10.206.16.103/iotp/data/env/minio/data3 http://10.206.16.103/iotp/data/env/minio/data4 http://10.206.16.60/iotp/data/env/minio/data1 http://10.206.16.60/iotp/data/env/minio/data2 http://10.206.16.60/iotp/data/env/minio/data3 http://10.206.16.60/iotp/data/env/minio/data4 http://10.206.16.94/iotp/data/env/minio/data1 http://10.206.16.94/iotp/data/env/minio/data2 http://10.206.16.94/iotp/data/env/minio/data3 http://10.206.16.94/iotp/data/env/minio/data4 http://10.206.16.138/iotp/data/env/minio/data1 http://10.206.16.138/iotp/data/env/minio/data2 http://10.206.16.138/iotp/data/env/minio/data3 http://10.206.16.138/iotp/data/env/minio/data4 "
MINIO_OPTS="--address 0.0.0.0:21185 --console-address 0.0.0.0:21188"
```
I will use the mc command to clean up the data that is used up an hour ago, but the temporary file directory like .minio.sys/tmp/ will keep growing and will eventually blow up my disk.

## Expected Behavior

keep minio tmp takes a lot of space
## Current Behavior

The minio data dir like .minio.sys takes a lots of disk space

**Comment by shy-stone** [comment]
Lower versions like minio version RELEASE.2021-02-24T18-44-45Z don't have this problem

**Comment by harshavardhana** [comment]
You still haven't explained what you are doing with a reproducer.. please explain.

Also your entire setup is wrong the way it is setup by listing out individual nodes.

You need to make sure to use ellipses syntax.

**Comment by shy-stone** [comment]
75/5000 
The minio cluster has been started successfully, and data can be written. The configuration is also obtained from the official website,and the ellipses syntax is not the only way to do it.You keep saying that my configuration is wrong,I understand what you mean, but that's not the problem.We change the configuration as you say, i get the same result.I just want to know how to clear temporary files, and you haven't answered my question
![image](https://user-images.githubusercontent.com/46125480/162550949-d0b44666-3acc-4a59-a07e-291f5536fc62.png)
![image](https://user-images.githubusercontent.com/46125480/162551026-1b8d3044-805f-4649-b0e8-44734ea2829b.png)
![image](https://user-images.githubusercontent.com/46125480/162551188-32a8dc3a-c063-4feb-ab83-ba8dd200b4e5.png)
I just want to know how to clear temporary files quickly in  the .minio.sys dir

**Comment by harshavardhana** [comment]
> The minio cluster has been started successfully, and data can be written. The configuration is also obtained from the official website,and the ellipses syntax is not the only way to do it.You keep saying that my configuration is wrong,I understand what you mean, but that's not the problem.We change the configuration as you say, i get the same result.I just want to know how to clear temporary files, and you haven't answered my question

the documentation you are referring is Chinese documentation not maintained by us our official docs are at https://docs.min.io - please use those.
