### ISSUE TITLE
Add limit of user number information

### ISSUE THREAD

**Issue by maslow** [minio/minio#14711]
**Is your feature request related to a problem? Please describe.**

[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
](https://docs.min.io/docs/minio-server-limits-per-tenant.html
I have seen these minio limits in this page, but cannot find users limits. 
Does minio has the limit of user number.   Is there some problems should be noticed if creating 100K users in one minio cluster(single tenant). )

Consider that, add these information in the server limits page.

**Comment by harshavardhana** [comment]
There are no limits on the number of users, of course if you want millions of users use external IDP instead.
