### ISSUE TITLE
How to configure remove the minio tmp file quickly?

### ISSUE THREAD

**Issue by shy-stone** [minio/minio#14713]
## NOTE
Hello,When I write a lot of data into minio, the temporary file dir. named like .minio.sys/tmp/ in Minio grows too fast. How to modify the configuration of minio to quickly delete the temporary files? Temporary files take up a lot of space。

## Expected Behavior
keep minio tmp takes a lot of space 

## Current Behavior
The minio data dir like .minio.sys takes a lots of disk space

## Possible Solution
any configure like expire or delay policy

## Steps to Reproduce (for bugs)
write a lot of data in minio storage

**Comment by harshavardhana** [comment]
@shy-stone please explain your setup in detail. You haven't provided any reproducer etc with this issue report.

**Comment by shy-stone** [comment]
The minio.cnf like this
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=minio!@#
MINIO_VOLUMES="http://10.206.16.103/iotp/data/env/minio/data1 http://10.206.16.103/iotp/data/env/minio/data2 http://10.206.16.103/iotp/data/env/minio/data3 http://10.206.16.103/iotp/data/env/minio/data4 http://10.206.16.60/iotp/data/env/minio/data1 http://10.206.16.60/iotp/data/env/minio/data2 http://10.206.16.60/iotp/data/env/minio/data3 http://10.206.16.60/iotp/data/env/minio/data4 http://10.206.16.94/iotp/data/env/minio/data1 http://10.206.16.94/iotp/data/env/minio/data2 http://10.206.16.94/iotp/data/env/minio/data3 http://10.206.16.94/iotp/data/env/minio/data4 http://10.206.16.138/iotp/data/env/minio/data1 http://10.206.16.138/iotp/data/env/minio/data2 http://10.206.16.138/iotp/data/env/minio/data3 http://10.206.16.138/iotp/data/env/minio/data4 "
MINIO_OPTS="--address 0.0.0.0:21185 --console-address 0.0.0.0:21188"
All other configurations are default

**Comment by shy-stone** [comment]
I will use the mc command to clean up the data that is used up an hour ago, but the temporary file directory like  .minio.sys/tmp/  will keep growing and will eventually blow up my disk.

**Comment by harshavardhana** [comment]
> MINIO_VOLUMES="http://10.206.16.103/iotp/data/env/minio/data1 http://10.206.16.103/iotp/data/env/minio/data2 http://10.206.16.103/iotp/data/env/minio/data3 http://10.206.16.103/iotp/data/env/minio/data4 http://10.206.16.60/iotp/data/env/minio/data1 http://10.206.16.60/iotp/data/env/minio/data2 http://10.206.16.60/iotp/data/env/minio/data3 http://10.206.16.60/iotp/data/env/minio/data4 http://10.206.16.94/iotp/data/env/minio/data1 http://10.206.16.94/iotp/data/env/minio/data2 http://10.206.16.94/iotp/data/env/minio/data3 http://10.206.16.94/iotp/data/env/minio/data4 http://10.206.16.138/iotp/data/env/minio/data1 http://10.206.16.138/iotp/data/env/minio/data2 http://10.206.16.138/iotp/data/env/minio/data3 http://10.206.16.138/iotp/data/env/minio/data4 "

this entire setup is wrong, also which version of MinIO is this?

**Comment by shy-stone** [comment]
![image](https://user-images.githubusercontent.com/46125480/162406482-294d89ee-1d20-4205-a6d4-5e8946e218f6.png)
minio version RELEASE.2022-02-07T08-17-33Z

**Comment by shy-stone** [comment]
I just want to know how to configure to clean the temporary file directory of minio
Lower versions like  minio version RELEASE.2021-02-24T18-44-45Z don't have this problem

**Comment by shy-stone** [comment]
This is a self-built environment with self disk, and 4 sets with 16 disk.
