### ISSUE TITLE
Minio: Unable to initialize a connection to KES if key already exists.

### ISSUE THREAD

**Issue by Angelote2022** [minio/minio#14716]
Bug description:

Minio is unable to initialize a connection to KES if key already exists. When I start minio and there are no keys in vault everything is fine, no errors and encryption works. If I restart minio then  service breaks and doesn't start. I have to remove the keys from vault to have a clean minio start.

Error:

`ERROR Unable to initialize a connection to KES as specified by the shell environment: key already exists`

The problem is the following code in the **common-main.go** file:

defaultKeyID := env.Get(config.EnvKESKeyName, "")
		KMS, err := kms.NewWithConfig(kms.Config{
			Endpoints:    endpoints,
			DefaultKeyID: defaultKeyID,
			Certificate:  certificate,
			RootCAs:      rootCAs,
		})
		if err != nil {
			logger.Fatal(err, "Unable to initialize a connection to KES as specified by the shell environment")
		}

		// We check that the default key ID exists or try to create it otherwise.
		// This implicitly checks that we can communicate to KES. We don't treat
		// a policy error as failure condition since MinIO may not have the permission
		// to create keys - just to generate/decrypt data encryption keys.
		if err = KMS.CreateKey(defaultKeyID); err != nil && !errors.Is(err, kes.ErrKeyExists) && !errors.Is(err, kes.ErrNotAllowed) {
			logger.Fatal(err, "Unable to initialize a connection to KES as specified by the shell environment")
		}
		GlobalKMS = KMS

Encryption is enabled and minio works nicely for the first time you create:

```
KES configuration
MINIO_KMS_KES_ENDPOINT="https://my_kes:7373"
MINIO_KMS_KES_KEY_FILE="/home/user/kes_config/private.key"
MINIO_KMS_KES_CERT_FILE="/home/user/kes_config/client.crt"
MINIO_KMS_KES_KEY_NAME="devops-minio"
```

`./mc admin info ch1 --json`

`{
    "status": "success",
    "info": {
        "mode": "online",
        "deploymentID": "93795958-1ef1-47f2-a8c5-dba6d5b9da44",
        "buckets": {
            "count": 2
        },
        "objects": {
            "count": 9184
        },
        "usage": {
            "size": 118496843
        },
        "services": {
            "kms": {
                "status": "online",
                "encrypt": "success",
                "decrypt": "success"
            },
            "ldap": {}
        },
        "backend": {
            "backendType": "FS"
        },
        "servers": [
            {
                "state": "online",
                "endpoint": "my_server:7000",
                "uptime": 62,
                "version": "2022-02-26T02:54:46Z",
                "commitID": "b7c90751b04e4acd015f3240ad2fa14bac39cf94",
                "network": {
                    "my_server:7000": "online"
                },
                "drives": [
                    {
                        "path": "/data",
                        "state": "ok",
                        "totalspace": 199518404608,
                        "usedspace": 292909056,
                        "availspace": 199225495552,
                        "pool_index": 0,
                        "set_index": 0,
                        "disk_index": 0
                    }
                ],
                "mem_stats": {
                    "Alloc": 40844304,
                    "TotalAlloc": 136465304,
                    "Mallocs": 598882,
                    "Frees": 525424,
                    "HeapAlloc": 40844304
                }
            }
        ]
    }
}`

Expected behavior
Minio should start after check key already exists 

Additional context
This was tested against minio version RELEASE.2022-02-26T02-54-46Z
KES server version:  0.19.1
Vault: K/V Engine Version 1             Vault version 1.9.1

**Comment by harshavardhana** [comment]
You should be upgrading MinIO since you upgraded Kes as well, the error responses have changed. 

That is why older release is not working with newer kes.

**Comment by Angelote2022** [comment]
Hi, Thanks for your quick response @harshavardhana I have stopped and updated the Minio version

From minio version RELEASE.2022-02-26T02-54-46Z
To minio version RELEASE.2022-04-09T15-09-52Z

But I get no access to my previous encrypted bucket. I can list all the non encrypted buckets and minio stop/start without issues.

`mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(invalid ciphertext: key ID mismatch)
 (1) stat.go:211 cmd.statURL(..) Tags: [https://XXXXXX.com:7000/postgres/]
 (0) client-s3.go:2130 cmd.(*S3Client).listInRoutine(..)
 Release-Tag:RELEASE.2022-03-17T20-25-06Z | Commit:84a7b83eda09 | Host:ch1-minio-dev | OS:linux | Arch:amd64 | Lang:go1.17.8 | Mem:3.2 MB/16 MB | Heap:3.2 MB/7.9 MB`

Is there any way to recreate these keys and have access again? Or do I need re-create the bucket because data is unrecoverable?

Thanks

**Comment by harshavardhana** [comment]
@aead can you check here?

**Comment by Angelote2022** [comment]
Thanks again @harshavardhana   More logs here:

`Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Time: 09:56:38 UTC 04/11/2022
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: DeploymentID: 93795958-1ef1-47f2-a8c5-dba6d5b9da44
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RequestID: 16E4CF0848446354
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RemoteHost: 172.23.64.82
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Host: xxxxxxxxxxxxxx.com:7000
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.23 mc/RELEASE.2022-03-17T20-25-06Z
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Error: Failed to decrypt ETag: invalid ciphertext: key ID mismatch (*errors.errorString)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        2: cmd/bucket-listobjects-handlers.go:249:cmd.objectAPIHandlers.ListObjectsV2Handler()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: API: ListObjectsV2(bucket=postgres)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Time: 09:56:38 UTC 04/11/2022
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: DeploymentID: 93795958-1ef1-47f2-a8c5-dba6d5b9da44
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RequestID: 16E4CF0848446354
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RemoteHost: 172.23.64.82
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Host: xxxxxxxxxxxxxx.com:7000
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.23 mc/RELEASE.2022-03-17T20-25-06Z
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Error: invalid ciphertext: key ID mismatch (kes.Error)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        4: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        3: cmd/api-errors.go:2137:cmd.toAPIError()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        2: cmd/bucket-listobjects-handlers.go:250:cmd.objectAPIHandlers.ListObjectsV2Handler()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: API: ListObjectsV2(bucket=postgres)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Time: 09:56:38 UTC 04/11/2022
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: DeploymentID: 93795958-1ef1-47f2-a8c5-dba6d5b9da44
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RequestID: 16E4CF084F22DDD1
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RemoteHost: 172.23.64.82
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Host: xxxxxxxxxxxxxx.com:7000
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.23 mc/RELEASE.2022-03-17T20-25-06Z
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Error: Failed to decrypt ETag: invalid ciphertext: key ID mismatch (*errors.errorString)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        2: cmd/bucket-listobjects-handlers.go:249:cmd.objectAPIHandlers.ListObjectsV2Handler()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: API: ListObjectsV2(bucket=postgres)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Time: 09:56:38 UTC 04/11/2022
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: DeploymentID: 93795958-1ef1-47f2-a8c5-dba6d5b9da44
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RequestID: 16E4CF084F22DDD1
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: RemoteHost: 172.23.64.82
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Host: xxxxxxxxxxxxxx.com:7000
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.23 mc/RELEASE.2022-03-17T20-25-06Z
Apr 11 09:56:38 ch1-minio-dev minio[2780621]: Error: invalid ciphertext: key ID mismatch (kes.Error)
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        4: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        3: cmd/api-errors.go:2137:cmd.toAPIError()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        2: cmd/bucket-listobjects-handlers.go:250:cmd.objectAPIHandlers.ListObjectsV2Handler()
Apr 11 09:56:38 ch1-minio-dev minio[2780621]:        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()`

**Comment by Angelote2022** [comment]
I can copy new files to the existing bucket and I see the encryption is enabled and works. But I want list files it returns a Key ID mismatch.

```
mc cp minio_20220409150952.0.0_amd64.deb ch1/postgres/220409150952.0.0_amd64.deb:  

27.25 MiB / 27.25 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 87.44 MiB/s 0s

mc ls ch1/postgres

mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(invalid ciphertext: key ID mismatch)

mc stat ch1/postgres/minio_20220409150952.0.0_amd64.deb

Name      : minio_20220409150952.0.0_amd64.deb
Date      : 2022-04-11 10:14:10 UTC
Size      : 27 MiB
ETag      : c176c4f99e0e8ca189d9aebf91004165-2
Type      : file
Metadata  :
  Content-Type: application/x-debian-package
Encrypted :
  X-Amz-Server-Side-Encryption: AES256

```

**Comment by harshavardhana** [comment]
ping @aead

**Comment by aead** [comment]
> If I restart minio then service breaks and doesn't start. I have to remove the keys from vault to have a clean minio start.

@Angelote2022 
Based on what you described above you did the following:
 1. Updated MinIO.
 2. Encountered: `ERROR Unable to initialize a connection to KES as specified by the shell environment: key already exists`
 3. Removed keys from Vault such that MinIO start again.
 4. Updated KES.

Now, you cannot access existing objects that where created before upgrading MinIO.
This is the cause because you deleted the keys at Vault. You are now seeing this error:
`invalid ciphertext: key ID mismatch` because you created a new key with the same name as the previous one.

Before, there was a key named `devops-minio`. That you deleted and created a new one, again named `devops-minio`.
The problem is that these keys are completely different. There is no way to re-create a key unless you have a backup of it.
Despite they having the same name there content will be completely different. Therefore, you are not able to decrypt existing objects with the newly created key.
Unless you have a backup of your keys at Vault, there is no way to recover the existing data. They are encrypted with a key that got deleted.

**Comment by Angelote2022** [comment]
@aead 
I can confirm following versions work for me:

Minio: RELEASE.2022-04-09T15-09-52Z
KES: 0.19.2
Mc client: RELEASE.2022-04-07T21-43-27Z

The key problem was because I changed from Vault K/V v1 to v2. I have recreated the keys and Minio restarts without errors now.
The previous encrypted backups need to be saved before update and recreate keys.

Many thanks,
Angel.
