### ISSUE TITLE
MInio Service restarting constantly after upgrade, and total used storage and number of objects also reduced

### ISSUE THREAD

**Issue by saurabhp0119** [minio/minio#14725]
We upgraded minio version to RELEASE.2022-01-08T03-11-54Z. After that the services are constantly restarting on all servers, and the total used storage size and object count has reduced.

* Version used (`minio --version`): RELEASE.2022-01-08T03-11-54Z
* Server setup and configuration: 20 servers, 10 disks each
* Operating System and version (`uname -a`): 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Errors seen in minio console command: All 20 minjo servers show similar kind of errors.

10.10.0.101  API: SYSTEM()
10.10.0.101  Time: 11:55:22 UTC 04/10/2022
10.10.0.101  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.101  Error: Storage resources are insufficient for the write operation <file/path> (cmd.InsufficientWriteQuorum)
10.10.0.101        18: cmd/data-scanner.go:879:cmd.(*scannerItem).applyHealing()
10.10.0.101        17: cmd/data-scanner.go:1040:cmd.(*scannerItem).applyActions()
10.10.0.101        16: cmd/xl-storage.go:498:cmd.(*xlStorage).NSScanner.func1()
10.10.0.101        15: cmd/data-scanner.go:487:cmd.(*folderScanner).scanFolder.func1()
10.10.0.101        14: cmd/os-readdir_unix.go:172:cmd.readDirFn()
10.10.0.101        13: cmd/data-scanner.go:420:cmd.(*folderScanner).scanFolder()
10.10.0.101        12: cmd/data-scanner.go:542:cmd.(*folderScanner).scanFolder.func2()
10.10.0.101        11: cmd/data-scanner.go:588:cmd.(*folderScanner).scanFolder()
10.10.0.101        10: cmd/data-scanner.go:542:cmd.(*folderScanner).scanFolder.func2()
10.10.0.101         9: cmd/data-scanner.go:588:cmd.(*folderScanner).scanFolder()
10.10.0.101         8: cmd/data-scanner.go:542:cmd.(*folderScanner).scanFolder.func2()
10.10.0.101         7: cmd/data-scanner.go:588:cmd.(*folderScanner).scanFolder()
10.10.0.101         6: cmd/data-scanner.go:542:cmd.(*folderScanner).scanFolder.func2()
10.10.0.101         5: cmd/data-scanner.go:588:cmd.(*folderScanner).scanFolder()
10.10.0.101         4: cmd/data-scanner.go:326:cmd.scanDataFolder()
10.10.0.101         3: cmd/xl-storage.go:455:cmd.(*xlStorage).NSScanner()
10.10.0.101         2: cmd/storage-rest-server.go:214:cmd.(*storageRESTServer).NSScannerHandler()
10.10.0.101         1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

10.10.0.101  API: SYSTEM()
10.10.0.101  Time: 11:55:22 UTC 04/10/2022
10.10.0.101  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.101  Error: Marking http://10.10.0.108:8991/minio/storage/mnt/drive1/v43 temporary offline; caused by Post "http://10.10.0.108:8991/minio/storage/mnt/drive1/v43/listvols?disk-id=af665c11-0dcd-42a6-b2d3-46b7510d5392": read tcp 10.10.0.101:58670->10.10.0.108:8991: read: connection reset by peer (*fmt.wrapError)
10.10.0.101         5: internal/rest/client.go:149:rest.(*Client).Call()
10.10.0.101         4: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
10.10.0.101         3: cmd/storage-rest-client.go:328:cmd.(*storageRESTClient).ListVols()
10.10.0.101         2: cmd/erasure-healing.go:220:cmd.listAllBuckets.func1()
10.10.0.101         1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

10.10.0.101  API: HeadObject(bucket=<bucket>, object=<object/path>)
10.10.0.101  Time: 11:55:22 UTC 04/10/2022
10.10.0.101  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.101  RequestID: 16E486ED22C284AE
10.10.0.101  RemoteHost: 127.0.0.1
10.10.0.101  UserAgent: MinIO (Linux; x86_64) minio-py/6.0.2
10.10.0.101  Error: Marking http://10.10.0.108:8991/minio/storage/mnt/drive5/v43 temporary offline; caused by Post "http://10.10.0.108:8991/minio/storage/mnt/drive5/v43/readversion?disk-id=505c6923-4d20-4745-8d6e-56f069e6c8d6&file-path=<sgsdsh>&read-data=false&version-id=&volume=<volume>": read tcp 10.10.0.101:58684->10.10.0.108:8991: read: connection reset by peer (*fmt.wrapError)
10.10.0.101         5: internal/rest/client.go:149:rest.(*Client).Call()
10.10.0.101         4: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
10.10.0.101         3: cmd/storage-rest-client.go:502:cmd.(*storageRESTClient).ReadVersion()
10.10.0.101         2: cmd/erasure-metadata-utils.go:136:cmd.readAllFileInfo.func1()
10.10.0.101         1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

10.10.0.101  API: SYSTEM()
10.10.0.101  Time: 12:01:05 UTC 04/10/2022
10.10.0.101  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.101  Error: Marking http://10.10.0.114:8991/minio/lock/v7 temporary offline; caused by Post "http://10.10.0.114:8991/minio/lock/v7/rlock?": read tcp 10.10.0.101:49612->10.10.0.114:8991: read: connection reset by peer (*fmt.wrapError)
10.10.0.101         5: internal/rest/client.go:149:rest.(*Client).Call()
10.10.0.101         4: cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
10.10.0.101         3: cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
10.10.0.101         2: cmd/lock-rest-client.go:111:cmd.(*lockRESTClient).RLock()
10.10.0.101         1: internal/dsync/drwmutex.go:408:dsync.lock.func1()

10.10.0.101  API: SYSTEM()
10.10.0.101  Time: 12:01:05 UTC 04/10/2022
10.10.0.101  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.101  Error: Marking http://10.10.0.114:8991/minio/lock/v7 temporary offline; caused by Post "http://10.10.0.114:8991/minio/lock/v7/rlock?": read tcp 10.10.0.101:49612->10.10.0.114:8991: read: connection reset by peer (*fmt.wrapError)
10.10.0.101         5: internal/rest/client.go:149:rest.(*Client).Call()
10.10.0.101         4: cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
10.10.0.101         3: cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
10.10.0.101         2: cmd/lock-rest-client.go:111:cmd.(*lockRESTClient).RLock()
10.10.0.101         1: internal/dsync/drwmutex.go:408:dsync.lock.func1()

10.10.0.101  API: SYSTEM()
10.10.0.101  Time: 12:01:05 UTC 04/10/2022
10.10.0.101  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.101  Error: Marking http://10.10.0.114:8991/minio/lock/v7 temporary offline; caused by Post "http://10.10.0.114:8991/minio/lock/v7/rlock?": read tcp 10.10.0.101:49612->10.10.0.114:8991: read: connection reset by peer (*fmt.wrapError)
10.10.0.101         5: internal/rest/client.go:149:rest.(*Client).Call()
10.10.0.101         4: cmd/lock-rest-client.go:65:cmd.(*lockRESTClient).callWithContext()
10.10.0.101         3: cmd/lock-rest-client.go:97:cmd.(*lockRESTClient).restCall()
10.10.0.101         2: cmd/lock-rest-client.go:111:cmd.(*lockRESTClient).RLock()
10.10.0.101         1: internal/dsync/drwmutex.go:408:dsync.lock.func1()

10.10.0.100  API: SYSTEM()
10.10.0.100  Time: 12:06:18 UTC 04/10/2022
10.10.0.100  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.100  Error: Get "http://10.10.0.117:8991/minio/health/live": dial tcp 10.10.0.117:8991: connect: connection refused (*url.Error)
10.10.0.100         5: internal/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
10.10.0.100         4: internal/logger/logonce.go:92:logger.LogOnceIf()
10.10.0.100         3: cmd/admin-server-info.go:58:cmd.getLocalServerProperty()
10.10.0.100         2: cmd/peer-rest-server.go:340:cmd.(*peerRESTServer).ServerInfoHandler()
10.10.0.100         1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

10.10.0.100  API: SYSTEM()
10.10.0.100  Time: 12:06:18 UTC 04/10/2022
10.10.0.100  DeploymentID: dc7de264-e06d-4e57-9100-9eaee858d835
10.10.0.100  Error: Get "http://10.10.0.117:8991/minio/health/live": dial tcp 10.10.0.117:8991: connect: connection refused (*url.Error)
10.10.0.100         5: internal/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
10.10.0.100         4: internal/logger/logonce.go:92:logger.LogOnceIf()
10.10.0.100         3: cmd/admin-server-info.go:58:cmd.getLocalServerProperty()
10.10.0.100         2: cmd/peer-rest-server.go:340:cmd.(*peerRESTServer).ServerInfoHandler()
10.10.0.100         1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

**Comment by harshavardhana** [comment]
> We upgraded minio version to RELEASE.2022-01-08T03-11-54Z. After that the services are constantly restarting on all servers, and the total used storage size and object count has reduced.

always upgrade to latest release, we do not support community users upgrading to random releases.
