### ISSUE TITLE
Customize Cache-Control/Content-Type when HTTP get an object?

### ISSUE THREAD

**Issue by fzyzcjy** [minio/minio#14745]
Hi thanks for this wonderful library! I hope to customize Cache-Control/Content-Type when HTTP get an object. More specifically, I hope to exist an API like:

```
minio.set_object_metadata('my_bucket_name', 'my_object.txt', cache_control='public, max-age=0, must-revalidate', content_type='text/plain; charset=utf8')
```

After doing that, when someone is visiting `http://minio:9000/my_bucket_name-my_object.txt`, he should receive HTTP response header `Content-Type: text/plain; charset=utf8` and `Cache-Control: public, max-age=0, must-revalidate` etc.

I wonder whether we can do this? I have checked the doc without finding something like "setting metadata to the *original* object instead of creating a new one".

P.S. Why I need this: I use `rclone` to sync a local folder to a minio bucket. But moreover, I need to let some files have special cache-control and special content-type, so I hope to exist an API customizing it.

**Comment by harshavardhana** [comment]
You need to set these headers when doing PutObject, there is no set metadata like S3 API. To update metadata you need to use copy_object onto itself and adding new metadata..

Along with metadata-directive to replace.

**Comment by fzyzcjy** [comment]
Thanks for the reply! That sounds wasting - a whole object is copied just to replace metadata :(

**Comment by harshavardhana** [comment]
> Thanks for the reply! That sounds wasting - a whole object is copied just to replace metadata :(

It is not @fzyzcjy

**Comment by fzyzcjy** [comment]
Thanks, then it sounds pretty reasonable
