### ISSUE TITLE
Minio: Unable to login to minio server after ssl changes 

### ISSUE THREAD

**Issue by Rajalakshmihm** [minio/minio#14748]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 

we have done minio setup. Everything seems to be fine untill we did SSL configurations.
we have generated CSR file for Eth0 inet IP address and implemented the cert and started the service.
After that login is blocked throwing below error.

Post "https://172.25.X.X:8086/(Eth1 ip address)": x509: certificate is valid for 53.18.232.20(Eth0 ip address, not 172.25.130.133

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-03-22T02-05-10Z
* Server setup and configuration:  minio on linux
* Operating System and version (`uname -a`): Linux 4.12.14-122.113-default #1 SMP Tue Mar 1 11:43:17 UTC 2022 (fe89a8c) x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Learn how to read the errors .. 

> Post "https://172.25.X.X:8086/(Eth1 ip address)": x509: certificate is valid for 53.18.232.20(Eth0 ip address, not 172.25.130.133
