### ISSUE TITLE
Access minio is  slow

### ISSUE THREAD

**Issue by ming12713** [minio/minio#14758]
## Description
In the production environment, we use  nginx proxy with minio service.Recently access console and api is  very slow, Used curl to access any endpoint in the cluster and observe it for a period of time. If anothers clients put or get objects, there will be a certain probability of delay

curl `http://10.0.160.115:9199` total response time is 175.155s 
<img width="1280" alt="屏幕快照 2022-04-15 18 57 41" src="https://user-images.githubusercontent.com/5196113/163577348-a4baceae-ccf0-4ce3-b767-94bf59fd3c43.png">

**normal status** 
<img width="1280" alt="屏幕快照 2022-04-15 18 44 20" src="https://user-images.githubusercontent.com/5196113/163577600-fc7997cc-3dfa-4765-ac01-c12a8b9729c2.png">

## Your Environment
```
mc admin info minio
●  10.0.160.113:9199
   Uptime: 1 week
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK

●  10.0.160.114:9199
   Uptime: 1 week
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK

●  10.0.160.115:9199
   Uptime: 1 week
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK

●  10.0.160.112:9199
   Uptime: 1 week
   Version: 2022-01-08T03:11:54Z
   Network: 4/4 OK
   Drives: 6/6 OK
```

minio version
```
minio -v
minio version RELEASE.2022-01-08T03-11-54Z
```

**Comment by harshavardhana** [comment]
Please upgrade @ming12713 to latest release

and if you want us to look at performance and hardware issues please get a subscription with us.. https://min.io/pricing
