### ISSUE TITLE
BucketName unable to be resolved from Presigned URL

### ISSUE THREAD

**Issue by gitaugakwa** [minio/minio#14759]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

When generating a Presigned URL, you get a URL in the format `http://bucket.localhost:PORT/folder/object?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=&X-Amz-Date=20220415T155005Z&X-Amz-Expires=300&X-Amz-Signature=&X-Amz-SignedHeaders=host&x-amz-acl=private&x-id=PutObject`.
This allows you to send a PUT request to the URL and thus put an object into the bucket.

## Current Behavior

On Windows, for the `bucket.localhost:PORT` hostname to be resolved, you have to add `127.0.0.1 gylfie-temp.localhost` to your host file. I'd like to assume that the subdomain value doesn't make it to the server.
This also returns the following errer
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>SignatureDoesNotMatch</Code>
	<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
	<Key>object</Key>
	<BucketName>folder</BucketName>
	<Resource>/folder/object</Resource>
	<RequestId>16E61D6FF925A188</RequestId>
	<HostId>609d2480-f49a-41be-845f-5beeb928e3e2</HostId>
</Error>
```

This makes it seem that it is unable to recognize the bucket name from the URL

## Steps to Reproduce (for bugs)

1. Generate a Presigned URL
2. Send a PUT request to URL ( with the host values stated above)

## Context

When you want to put an object into an S3 bucket using a Presigned URL

## Regression

No

## Your Environment

* Version used (`minio --version`):
```
PS ~> minio --version
minio.exe version RELEASE.2022-04-12T06-55-35Z
```
* Server setup and configuration:
```
minio server --address :5003 --console-address :6003 "C:\S3"
```
* Operating System and version (`uname -a`):
```
PS ~> uname -a
MSYS_NT-10.0-19044 DESKTOP-NECU1RT 3.3.3-341.x86_64 2022-01-18 13:00 UTC x86_64 Msys
```

**Comment by harshavardhana** [comment]
This is your client side code problem, make sure to set path style access.

**Comment by gitaugakwa** [comment]
> This is your client side code problem, make sure to set path style access.

What do you mean by that?
