### ISSUE TITLE
Errors when replicating with AWS

### ISSUE THREAD

**Issue by sgammon** [minio/minio#14755]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

When adding a replication rule to a Minio bucket, it should work to replicate objects up to the bucket

## Current Behavior

When adding a regular S3 bucket, Minio forces versioning to be active on both sides. So on my remote bucket, and on my Minio bucket, I activate versioning, fill in the requisite details, and then upload a file (empty bucket beforehand), but get this error:

```
storage-usw1-pd1-jgk6 minio[24123]: Error: Unable to replicate for object social/img_placeholder.svg(0c5cb16a-ab9a-409b-816a-5bee1ced35a7): This operation does not accept a version-id. (*errors.errorString)
storage-usw1-pd1-jgk6 minio[24123]:        2: cmd/bucket-replication.go:1169:cmd.replicateObjectToTarget()
storage-usw1-pd1-jgk6 minio[24123]:        1: cmd/bucket-replication.go:906:cmd.replicateObject.func2()
```

Completely normal S3 bucket in region `us-west-1` with Transfer Acceleration active (but not in use via replication config).

As an alternative, I tried using the _Tiers_ feature, but adding a tier for S3 or GCS both fail with the error:
```
Remote tier backend already in use
```

This error seems unconditional; it doesn't matter what inputs I put in for each type, it simply won't let me save the tier.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
All I did was install Minio on two servers, in distributed mode, following the Minio guide. Then I configured an empty bucket and the above replication configuration.

## Context
We're trying to replicate our data from Minio to S3

## Regression
I'm not sure

## Your Environment
`minio --version`:
```
minio version RELEASE.2022-04-12T06-55-35Z
```

`uname -a`:
```
Linux storage-usw1-pd1-jgk6 5.13.0-1023-gcp #28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

`lsb_release -a`:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by harshavardhana** [comment]
We do not support replicating to AWS S3 - you can only replicate to MinIO to MinIO deployments. 

You can use Tiering but Tiering should be on an empty bucket.
