### ISSUE TITLE
MiniO Gateway expose multiple volumes under the same NFS filesystem 

### ISSUE THREAD

**Issue by gal999** [minio/minio#14750]
I am using Minio in Gateway mode to expose NetApp NFS volumes to S3 buckets.
In NetApp, the root volume is "/", I'm trying to expose the root volume under the root i have additional volumes uder ther root
Files Tree will look like this on NetApp system (left corner of the tree is the root " "): 
![image](https://user-images.githubusercontent.com/41475345/163389584-80a23c4c-3375-4da8-a7ca-7879550c51ad.png)

When I try to upload files / folders via the MiniO console(UI) or MC (Minio client) I get an error.
Note :
NetApp looks in each volume under " \ " for filesystem, and the issue is how we are attempting to write the data across several volumes.

  
## Expected Behavior

Upload file to s3 buckets without errors.

## Current Behavior

Getting error:
![image](https://user-images.githubusercontent.com/41475345/163371079-8204fa7b-2e71-4e32-9974-74802ba81e8d.png)

Error: Rename across devices not allowed, please fix your backend configuration (/export/.minio.sys/tmp/a09fe8a7-f472-4e13-8b54-5457a3fb143f/faf82586-d008-4f02-b2aa-10e19481e8e5)->(/export/data_2/gal/review01.PNG) (*fmt.wrapError) 

## Steps to Reproduce (for bugs)

1.  NetApp - create few NFS volume.
2. OpenShift- Create Storage Class for the NFS, Create PV & PVC 
3. Run the Helm command for install:
```
 helm install --namespace <your_namespace> --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio --debug --set replicas=8 --set securityContext.enable=false --set resources.requests.memory=1Gi --set buckets="" --set users="" --set mode=gateway --set persistence.existingClaim="<PVC_name>" --set persistence.accessMode=ReadWriteMany
```
5. Try to upload file

## Your Environment

* Version used  RELEASE.2022-02-01T18-00-14Z
* Server setup and configuration OpenShift cluster 4.9.13
* Operating System and version (`uname -a`): CoreOS

**Comment by harshavardhana** [comment]
@gal999 all these use-cases are not supported, and won't be supported for any time in future.

Refer #14331
