### ISSUE TITLE
MinIO doesn't start on read-only filesystem

### ISSUE THREAD

**Issue by haslersn** [minio/minio#14763]
On Kubernetes, one can create containers with `securityContext.readOnlyRootFilesystem: true`. However, the MinIO container then fails to start.

## Expected Behavior

Some admins prefer to have a read-only root filesystem for security reasons, so MinIO should start successfully on such a filesystem.

## Current Behavior

```
ERROR Unable to create directory specified config-dir=/.minio: mkdir /.minio: read-only file system
```

## Possible Solution

- Make it a warning instead of an error
- Or only try to create the config directory, if it's **really** needed. On my MinIO server, the config directory has no content. 

## Your Environment

image: minio/minio:RELEASE.2022-04-01T03-41-39Z

**Comment by harshavardhana** [comment]
Of course we cannot @haslersn it is something we have no interest supporting.

**Comment by haslersn** [comment]
I was able to work around this issue by mounting an empty directory on `/.minio`. Why do you require to create this directory, if nothing gets written into it?

I think another "possible solution" is to change the official MinIO images such that the directory already exists. Then MinIO wouldn't try to create it, because it already exists.

**Comment by haslersn** [comment]
> Of course we cannot

@harshavardhana why "of course"?

Maybe you misunderstood the issue. The disks where MinIO stores data of course need to be read-write. I was just talking about the ephemeral root filesystem of the container. It is delivered with the container image and everything that gets written to it is ephemeral. It only persists until the container is restarted. Currently the official container tries to create the directory `/.minio` which is outside of the persistent volumes.

I was able to work around this issue by mounting an empty directory on `/.minio`.

Why do you even require to create this directory, if nothing gets written into it?

I think another "possible solution" is to change the official MinIO images such that the directory already exists. Then MinIO wouldn't try to create it, because it already exists.

**Comment by haslersn** [comment]
By examining the source code, I found out that the path to this config directory is configured via `--config-dir`, which is deprecated. It's also hidden since commit 7d636a7c139b51267b3f6e85804bf7ee8fb494a6, so I didn't find it in the help page or documentation. If `--config-dir` is deprecated, then why do you still require that MinIO has permission to create it on the filesystem?

**Comment by harshavardhana** [comment]
@haslersn let's not bike shed this further we have no plans to support this.
