### ISSUE TITLE
forbidden auth with aws-sdk/client-s3 (v3) in browser

### ISSUE THREAD

**Issue by maslow** [minio/minio#14762]
The same problem with [https://github.com/aws/aws-sdk-js-v3/issues/2465](https://github.com/aws/aws-sdk-js-v3/issues/2465)

1. minio version: 2022-4-12
2. the same code with same user run correctly in Node.js （ aws-sdk v3、aws-sdk v2、minio js sdk all tested ok）
3. the same code with same user run correctly in Browsers ( aws-sdk v2、minio js sdk tested ok, but aws-sdk v3 )

We got 403 response signature not match with aws-sdk v3. 

The problem code demo:

```js
const { S3, ListObjectsCommand } = require('@aws-sdk/client-s3')
const s3 = new S3({
    endpoint: 'http://127.0.0.1:9020', 
    region: 'us-east-1',
    credentials: {
      accessKeyId: token.accessKeyId,
      secretAccessKey: token.secretAccessKey,
      sessionToken: token.sessionToken,
      expiration: token.expiration
    },
    forcePathStyle: true
  })

  const cmd3 = new ListObjectsCommand({ Bucket: 'test' })
  const res = await s3.send(cmd3)
  console.log(res)
```

**Comment by harshavardhana** [comment]
This is a bug in AWS SDK v3 they do not properly honor port as part of signature calculation.

Read my analysis here you need to report this upstream and let them fix their SDK

https://github.com/minio/minio/discussions/14709#discussioncomment-2541505

This is why it works with V2 version.

**Comment by maslow** [comment]
> This is a bug in AWS SDK v3 they do not properly honor port as part of signature calculation.
> 
> Read my analysis here you need to report this upstream and let them fix their SDK
> 
> [#14709 (comment)](https://github.com/minio/minio/discussions/14709#discussioncomment-2541505)
> 
> This is why it works with V2 version.

Thanks VERY MUCH!  we've worked long time with this problem.  respect for your reply so soon!
