### ISSUE TITLE
Getting error when create Minio Distributed with 4 AWS Instances using public IP.

### ISSUE THREAD

**Issue by luanvu2307** [minio/minio#14770]
i follow this tutorial (https://awstip.com/distributed-minio-object-storage-setup-on-aws-infra-efe667eea003 ) to create Minio Distributed on 4 Nodes ( 4 AWS Instances). I completely done it by config 4 private IPs of them in /etc/hosts. However, when i change into 4 public IPs, they cannot find each other.

This is config of /etc/hosts with 4 private IP of those Instances.
![image](https://user-images.githubusercontent.com/62737753/163796940-88e11b3c-ed28-4c0a-aceb-9f57ae30d5d2.png)

When I change into 4 Public IP:
![image](https://user-images.githubusercontent.com/62737753/163797074-957b7493-9cd4-44f8-8944-0331c44985ed.png)

The Error:
![image](https://user-images.githubusercontent.com/62737753/163797132-1542c4bd-0ebb-4715-9b94-ae9fc624ff1d.png)

**Comment by harshavardhana** [comment]
Public IPs shouldn't be used in this manner since your instances ports are not routable over public IP, as in instances do not have the public IP on any interface on the instance.

On AWS Public IP is virtual. You need to use the private IP since that is the interface IP.

**Comment by luanvu2307** [comment]
I completely test on 4 virtual machines from a VPS that my team deployed on Virtualizor with public IPs( buying). However, my team wants to replace a virtual machine with an AWS Instance ( 3 VMs and 1 AWS Instance). AWS Instance can be seen as a backup server in case 3 VMs crash. The result is that 3 VMs can connect to each other but cannot do to AWS Instance.

Do you have any suggestions for us? 
Are there any ways for VMs that connect to AWS Instance?

**Comment by harshavardhana** [comment]
> I completely test on 4 virtual machines from a VPS that my team deployed on Virtualizor with public IPs( buying). However, my team wants to replace a virtual machine with an AWS Instance ( 3 VMs and 1 AWS Instance). AWS Instance can be seen as a backup server in case 3 VMs crash. The result is that 3 VMs can connect to each other but cannot do to AWS Instance.
> 
> Do you have any suggestions for us? Are there any ways for VMs that connect to AWS Instance?

There is no way. This is not MinIO's problem. You need to fix your networking..
