### ISSUE TITLE
Cannot delete Service Account after removing its policy

### ISSUE THREAD

**Issue by martialblog** [minio/minio#14784]
After creating a Service Account with a policy, then deleting said policy, the Service Account cannot be deleted anymore. 

I know the WebUI says "You cannot modify the Service Account optional policy after saving." I can still edit it though.

Error in UI:
```
We encountered an internal error, please try again. (illegal base64 data at input byte 0)
```

Error in Console:
```
minio_1  | API: DeleteServiceAccount()
minio_1  | Time: 14:22:02 UTC 04/20/2022
minio_1  | DeploymentID: dfd72018-48e7-460a-abb6-9bc42927c805
minio_1  | RequestID: 16E7A0BD1BA1B1CF
minio_1  | RemoteHost: 172.24.0.2
minio_1  | Host: 172.24.0.2:9000
minio_1  | UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
minio_1  | Error: illegal base64 data at input byte 0 (base64.CorruptInputError)
minio_1  |        5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
minio_1  |        4: cmd/admin-handler-utils.go:217:cmd.toAdminAPIErrCode()
minio_1  |        3: cmd/admin-handler-utils.go:204:cmd.toAdminAPIErr()
minio_1  |        2: cmd/admin-handlers-users.go:998:cmd.adminAPIHandlers.DeleteServiceAccount()
minio_1  |        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

## Expected Behavior
Either I woudn't be able to edit the Service Account's policy, like the UI mentions. and-or I should be able to delete the Service Account.

## Current Behavior
After creating a Service Account with a policy, then deleting said policy, the Service Account cannot be deleted anymore. 

## Possible Solution
Maybe the Service Account's policy shouldn't be modifiable in the UI?

## Steps to Reproduce (for bugs)

1. Start fresh minio tenant
2. Create a new user 
3. Give the new user a policy (i.e. readwrite)
4. Login with the new user
5. Create a Service Account with a Policy
6. Remove the Service Account's policy afterwards
7. Delete the Service Account
8. Encounter Error `(illegal base64 data at input byte 0)`

## Context
Just trying Service Accounts and their policies while testing the product.

## Regression
No? Don't know

## Your Environment
* Version used (`minio --version`): RELEASE.2022-04-16T04-26-02Z
* Server setup and configuration: Simple docker-compose with `docker.io/minio/minio:latest`

**Comment by mbentley** [comment]
Curious if you found a way to delete it afterward as I found myself in the same situation - was testing policies and removed the policy in testing, not realizing that I couldn't.  I tried using `mc` but that did not work; same error as the UI.

**Comment by martialblog** [comment]
Yeah `mc` runs into the same error, which is expected since the backend fails at the same function `DeleteServiceAccount()`

```
mc admin user svcacct remove minio KuoiCo6SvzVw
mc: <ERROR> Unable to remove the specified service account. 
We encountered an internal error, please try again. (illegal base64 data at input byte 0).
```

It's all functions that try to read the policy, more specifically the function `globalIAMSys.GetServiceAccount` I think.

```
Error: illegal base64 data at input byte 0 (base64.CorruptInputError)
       5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
       4: cmd/admin-handler-utils.go:217:cmd.toAdminAPIErrCode()
       3: cmd/admin-handler-utils.go:204:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:731:cmd.adminAPIHandlers.UpdateServiceAccount()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

Error: illegal base64 data at input byte 0 (base64.CorruptInputError)
       5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
       4: cmd/admin-handler-utils.go:217:cmd.toAdminAPIErrCode()
       3: cmd/admin-handler-utils.go:204:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:834:cmd.adminAPIHandlers.InfoServiceAccount()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

A workaround is to delete the user who created the service account, which is a bit unpleasant.

I think a solution would be to actually enforce what is mentioned in the UI "You cannot modify the Service Account optional policy after saving.". The input box could be read-only when modifying the service account.
