### ISSUE TITLE
MinIO Helm Chart, wrong TargetPort and Endpoints for MinIO API Access

### ISSUE THREAD

**Issue by theruin0000** [minio/minio#14789]
I changed MinIO API Access port to '44443' at 'values.yaml' then tried to install the chart

![image](https://user-images.githubusercontent.com/6334991/164407115-245f44d2-0086-4ca6-984b-01ff453c2dae.png)

![image](https://user-images.githubusercontent.com/6334991/164405733-468e2636-8417-4172-88f8-b362ebd87ee1.png)

But the service still indicates port '9000'

![image](https://user-images.githubusercontent.com/6334991/164405386-c56cc9e2-7de4-4d44-9c2b-445e4c159801.png)

Currently, MinIO API is running well on port '44443'

![image](https://user-images.githubusercontent.com/6334991/164405559-ad5b3448-c617-4602-b17f-9e92e07442f4.png)

## Expected Behavior

The TargetPort and port of Endpoints should be set as I set

## Current Behavior

The TargetPort and port of Endpoints indicate 9000

## Possible Solution

Just use port '9000' for MinIO API but I want to change it

## Steps to Reproduce (for bugs)

1. Change 'minioAPIPort' and 'port' of service from '9000' to '44443'
2. Do installing the chart with 'helm upgrade --install my-release minio/minio -f values.yaml -n minio'
3. Check the service info with 'kubectl describe services -n minio'

## Context

Cannot use the service IP to access MinIO API

## Regression

It's on latest version, I didn't try on older version

## Your Environment

* Version used (`minio --version`): 
![image](https://user-images.githubusercontent.com/6334991/164408915-ca5840a2-c53b-4b60-bf85-e8030a97eaa3.png)

* Server setup and configuration: Try to run on kubernetes
![image](https://user-images.githubusercontent.com/6334991/164409307-3a1bd908-ab1b-4433-9723-0d30c2147232.png)

* Operating System and version (`uname -a`): Linux master 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 17:53:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Feel free to send a fix @theruin0000

**Comment by theruin0000** [comment]
@harshavardhana 

Excuse me but I have a question

I understood it's fixed, but it's still reproduced at recent version (RELEASE.2022-04-30T22-23-53Z)

![image](https://user-images.githubusercontent.com/6334991/166206263-83ccbd04-8f7c-4f87-9fd4-b373a41a4877.png)

Should I do something more?

**Comment by theruin0000** [comment]
> Feel free to send a fix @theruin0000

@harshavardhana 

Sorry to bother you but I wonder how it is going

Please refer to my comment
