### ISSUE TITLE
Download returns an empty file

### ISSUE THREAD

**Issue by munizjuh** [minio/minio#14785]
## Expected Behavior
Download an file correctly as it is saved on the disc

## Current Behavior
When clicking to download any file it downloads a empty file called "download", but when creating a temporary URL to share the file, the file downloads perfectly

## Steps to Reproduce (for bugs)

1. Install MinIO as a windows service with the following the steps described here: https://github.com/minio/minio-service/tree/master/windows

minio-service.p1
```
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs; exit }

Set-Location -Path $PSScriptRoot

$config = @'
<service>
  <id>MinIO</id>
  <name>MinIO</name>
  <description>MinIO is a high performance object storage server</description>
  <executable>minio.exe</executable>
  <env name="MINIO_ROOT_USER" value="minio"/>
  <env name="MINIO_ROOT_PASSWORD" value="minio123"/>
  <arguments>server C:\minio</arguments>
  <logmode>rotate</logmode>
</service>
'@

Set-Content "minio-service.xml" $config

Start-Process -WorkingDirectory $PSScriptRoot -FilePath "$($PSScriptRoot)\minio-service.exe" -ArgumentList "install" -NoNewWindow -PassThru -Wait

Write-Host "Installation done"
```

Write-Host "Installation done"`

And minio-service.xml:

```
<service>
  <id>MinIO</id>
  <name>MinIO</name>
  <description>MinIO is a high performance object storage server</description>
  <executable>minio.exe</executable>
  <env name="MINIO_ROOT_USER" value="minio"/>
  <env name="MINIO_ROOT_PASSWORD" value="minio123"/>
  <arguments>server C:\minio</arguments>
  <logmode>rotate</logmode>
</service>
```

2. Create a bucket and upload a file
3. Try the download file
4. Get back empty download

## Context
The only similar issue I have found was a problem with the MINIO_SERVER_URL key, but I didn't set this key, the url is the default SERVER_IP:9000 

## Your Environment
* Version used (`minio --version`): RELEASE.2022-04-07T21-43-27Z
* Operating System and version (`uname -a`): Windowns Server 2016

**Comment by harshavardhana** [comment]
Please upgrade to latest release @munizjuh

**Comment by mjnagel** [comment]
@harshavardhana I ran into the same issue on `RELEASE.2022-04-12T06-55-35Z`, upgrading does seem to have fixed it. Is there a different Github issue with more information about this or affected version range?

**Comment by harshavardhana** [comment]
> @harshavardhana I ran into the same issue on `RELEASE.2022-04-12T06-55-35Z`, upgrading does seem to have fixed it. Is there a different Github issue with more information about this or affected version range?

It was in console UI.

**Comment by mjnagel** [comment]
For anyone else looking I found the issue - https://github.com/minio/console/issues/1844 

MinIO Console [0.15.13](https://github.com/minio/console/releases/tag/v0.15.13) was the first console release with the fix, which was included in [MinIO `RELEASE.2022-04-16T04-26-02Z`](https://github.com/minio/minio/releases/tag/RELEASE.2022-04-16T04-26-02Z).
