### ISSUE TITLE
there is a logic bug in wildcard.MatchSimple

### ISSUE THREAD

**Issue by tmgj** [minio/minio#14790]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

> // MatchSimple - finds whether the text matches/satisfies the pattern string.
// supports only '*' wildcard in the pattern.
// considers a file system path as a flat name space.

Above are the comments in your `wildcard/match.go` file. So, as I understand it, the following calls to `MatchSimple` are all expected to get `false`:
- `wildcard.MatchSimple("a?", "aa")`
- `wildcard.MatchSimple("a?a", "aaa")`
- `wildcard.MatchSimple("my-?-bucket/abc", "my-k-bucket/abc")`
- `wildcard.MatchSimple("my-?-bucket/abc*", "my-k-bucket/abc")`
## Current Behavior

But, they all get `true`.

## Possible Solution

In my opinion, the problem lies in the `deepMatchRune` function in `wildcard/match.go` file.
```go
func deepMatchRune(str, pattern []rune, simple bool) bool {
	for len(pattern) > 0 {
		switch pattern[0] {
		default:
			if len(str) == 0 || str[0] != pattern[0] {
				return false
			}
		case '?':
			if len(str) == 0 && !simple {
				return false
			}
		case '*':
			return deepMatchRune(str, pattern[1:], simple) ||
				(len(str) > 0 && deepMatchRune(str[1:], pattern, simple))
		}
		str = str[1:]
		pattern = pattern[1:]
	}
	return len(str) == 0 && len(pattern) == 0
}
```
The code about `case '?'` causes this bug, I think.

## Steps to Reproduce (for bugs)

```go
package main

import (
	"fmt"
	"github.com/minio/pkg/wildcard"
)

func main() {
	fmt.Println(wildcard.MatchSimple("a?", "aa"))                            // true
	fmt.Println(wildcard.MatchSimple("a?a", "aaa"))                          // true
	fmt.Println(wildcard.MatchSimple("my-?-bucket/abc", "my-k-bucket/abc"))  // true
	fmt.Println(wildcard.MatchSimple("my-?-bucket/abc*", "my-k-bucket/abc")) // true
}
```
I'm sorry I can't provide a screenshot of the results due to constraints, but you can easily reproduce this bug by running the code above.

## Your Environment

* Version used (`minio --version`): I install MinIO by `go install github.com/minio/minio@latest`.
* golang version: go1.17
* Operating System and version (`uname -a`): Windows10  x64

**Comment by harshavardhana** [comment]
That comment is not updated, we have supported ? In between strings for some time now.
