### ISSUE TITLE
Download file from server very slowly

### ISSUE THREAD

**Issue by BUAADreamer** [minio/minio#14808]
I deploy minio in my own server and find that download a file by using public url is very slow, speed is about 60kb/s

as shown in the follow picture

![屏幕截图 2022-04-25 001601](https://user-images.githubusercontent.com/64362896/164985879-4efc61c0-8540-45ce-994c-6f6122433677.png)

**Comment by harshavardhana** [comment]
Not MinIO issue, look at your network.
