### ISSUE TITLE
speed of download files from public url is too slow

### ISSUE THREAD

**Issue by BUAADreamer** [minio/minio#14809]
how to increase speed of download files from public url?
## Expected Behavior

download file whose size is 3MB, from public url, expect speed at least can be equals to my computer speed.
## Current Behavior

I deploy minio in my own server and find that download a file by using public url is very slow, speed is about 60kb/s
![1](https://user-images.githubusercontent.com/64362896/164986964-7f9890e7-3325-40a4-b999-85c78f06968e.png)
![2](https://user-images.githubusercontent.com/64362896/164987284-35d2a895-2320-4e77-abc2-ffbb87f87354.png)

## Possible Solution

I have tried to make it readonly however speed is a little slow
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):latest
* Server setup and configuration:refer to config in [https://blog.csdn.net/Ever_Ardour/article/details/120838919](https://blog.csdn.net/Ever_Ardour/article/details/120838919)
* Operating System and version (`uname -a`):ubuntu20.04 server in AliCloud

**Comment by harshavardhana** [comment]
You file size is 23MiB your download speed on the internet is limited.
