### ISSUE TITLE
How to config Nginx to redirect to all Minio Distributed Node URLs

### ISSUE THREAD

**Issue by luanvu2307** [minio/minio#14810]
I want to add Nginx to Minio Distributed 4 nodes to auto redirect to each URL of every node as a load balancer when uploading data or requesting.
Here is my Minio Distributed
![image](https://user-images.githubusercontent.com/62737753/165014700-823fede9-9136-4281-820e-b837fe195030.png)

And I setup Nginx config at /etc/nginx/sites-enabled/minio  
![image](https://user-images.githubusercontent.com/62737753/165014870-de911dd9-2bb0-4b22-b199-cf25addbb17a.png)

This is status of nginx:
![image](https://user-images.githubusercontent.com/62737753/165014976-dd34438a-2d75-4d01-8866-d7d006d890a9.png)

I install Nginx on a AWS Instance and this is result when I curl. 
3.1.194.48 is public IP of instance.
![image](https://user-images.githubusercontent.com/62737753/165014919-bc368ece-30f3-4c06-9ac5-ff30a4ca5dfe.png)

Are there any issues?

**Comment by harshavardhana** [comment]
@luanvu2307 what you have done is enough and nginx is already redirecting traffic to all nodes

**Comment by luanvu2307** [comment]
How do I check efficiency of load balancer ? I think when I call to public IP of Nginx Instance, it automatically redirects to IPs of each node. @harshavardhana

**Comment by harshavardhana** [comment]
> How do I check efficiency of load balancer ? I think when I call to public IP of Nginx Instance, it automatically redirects to IPs of each node. @harshavardhana

This is not our problem you need to ask nginx developers
