### ISSUE TITLE
Cannot delete directories when versioning is suspended but never enabled

### ISSUE THREAD

**Issue by gavol** [minio/minio#14823]
When versioning is suspended in a bucket (but actually has never been enabled), it is not possible to remove empty directories.

## Expected Behavior
When versioning is never enabled on a bucket, I would expect directory removal to just work.

## Current Behavior
I am using minio (in distributed mode) version RELEASE.2022-04-26T01-20-24Z, deployed in Kubernetes with Helm (chart version 3.6.3).

I let Helm create my bucket with the following config:

```
buckets:
  - name: mybucket
    policy: none
    purge: false
    versioning: false
```

That actually translates in the following command to be executed:

```
${MC} version suspend myminio/$BUCKET
```

Once the bucket has been created, I can check its versioning status:

```
mc version info minio/mybucket
minio/mybucket versioning is suspended 
```

Then I create a directory in the bucket via the console web interface. That works fine.
At the same time, any attempt do delete that directory (always from the web interface) fails. A "success" message is shown, but the directory is still there.

The only way to remove it is to run ```mc rm``` with the ```--versions``` option.

To be noted that versioning have never actually been enabled on the bucket.

## Possible Solution
The only solution I have found is to not touch at all the versioning status of a bucket, when versioning is not needed. In that case its versioning status is ```un-versioned```.

For the Helm chart case, that is enough to not set at all the ```versioning``` parameter. In that case, the versioning status of the bucket is not modified. Here is the piece of code being executed:

```
      # set versioning for bucket
      if [ ! -z $VERSIONING ] ; then
        if [ $VERSIONING = true ] ; then
            echo "Enabling versioning for '$BUCKET'"
            ${MC} version enable myminio/$BUCKET
        elif [ $VERSIONING = false ] ; then
            echo "Suspending versioning for '$BUCKET'"
            ${MC} version suspend myminio/$BUCKET
        fi
      else
          echo "Bucket '$BUCKET' versioning unchanged."
      fi
```
That seems to be very similar to what is described in https://github.com/minio/minio/issues/13783.

## Steps to Reproduce (for bugs)
1. Create a bucket;
2. Suspend versioning on that bucket;
3. Create a new directory in that bucket via the web interface;
4. Try to delete that directory via the web interface.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-04-26T01-20-24Z in Kubernetes, deployed using Helm chart version 3.6.3
* Server setup and configuration: minio in distributed mode
* Operating System and version (`uname -a`): Linux CentOS 7

**Comment by harshavardhana** [comment]
You don't need to enabled @gavol suspending is as good as triggering versioning semantics.

Will check with AWS S3 on compatible behavior here. You need to use mc rm --versions to delete the content because AWS S3 mandates we create a delete marker with null version when versioning is suspended once.

**Comment by gavol** [comment]
Thanks a lot for your very fast answer.

I was just thinking that https://github.com/minio/minio/pull/13795 was supposed to fix such a behavior, as my case is very similar to the one described here: https://github.com/minio/minio/issues/13783#issuecomment-982791272, with the only difference that for my bucket versioning has never been explicitly enabled.

Anyway, there is a solution for that. At the same time, Helm chart users should just be warned that setting the ```versioning``` option to ```false``` may have some unexpected side effect.
