### ISSUE TITLE
MinIO crash: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#14821]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Found a MinIO crash with the below trace,

`
fatal error: concurrent map writes

goroutine 4841638037 [running]:
runtime.throw({0x2db4de2, 0xc021ac4660})
	runtime/panic.go:1198 +0x71 fp=0xc01d279cd8 sp=0xc01d279cd8 pc=0x435851
runtime.mapassign_faststr(0xcbd9e0c6cca18, 0x0, {0x2d8c4e3, 0x6})
	runtime/map_faststr.go:211 +0x39c fp=0xc01d279d40 sp=0xc01d279cd8 pc=0x412dfc
github.com/minio/minio/cmd.ReportMetrics.func1.1({0x2d9529c, 0xa}, {0x2d8842a, 0x4}, {0x2d958c8, 0xa}, {0x2dcfe58, 0x1d}, {0x2d9753e, 0xb, ...})
github.com/minio/minio/cmd/metrics-v2.go:1706 +0x79 fp=0xc01d279d40 sp=0xc01d279d40 pc=0x2450199
github.com/minio/minio/cmd.populateAndPublish({0xc00158b650, 0xe, 0x5cbf160}, 0xc01d279fa8)
github.com/minio/minio/cmd/metrics-v2.go:1738 +0x11e fp=0xc01d279f70 sp=0xc01d279e40 pc=0x245047e
github.com/minio/minio/cmd.ReportMetrics.func1()
github.com/minio/minio/cmd/metrics-v2.go:1702 +0x98 fp=0xc01d279fe0 sp=0xc01d279f70 pc=0x24500d8
runtime.goexit()
runtime/asm_amd64.s:1581 +0x1 fp=0xc01d279fe8 sp=0xc01d279fe0 pc=0x4693c1
created by github.com/minio/minio/cmd.ReportMetrics
github.com/minio/minio/cmd/metrics-v2.go:1700 +0xf0
`

## Expected Behavior

no crashes

## Current Behavior

crash

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-01-08T03:11:54Z
* Server setup and configuration: K8s
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): RELEASE.2022-01-08T03:11:54Z

Please upgrade @mshanmu

**Comment by mshanmu** [comment]
I have already upgraded, but saw this one in the logs. 

Also, I looked at the code https://github.com/minio/minio/blame/master/cmd/metrics-v2.go and it has not changed in the last 4 months and it seems possible there is a concurrent issue here https://github.com/minio/minio/blame/master/cmd/metrics-v2.go#L1951

**Comment by harshavardhana** [comment]
> I have already upgraded, but saw this one in the logs.
> 
> Also, I looked at the code https://github.com/minio/minio/blame/master/cmd/metrics-v2.go and it has not changed in the last 4 months and it seems possible there is a concurrent issue here https://github.com/minio/minio/blame/master/cmd/metrics-v2.go#L1951

that cannot happen unless internally populatePublish was called concurrently which is not possible either. This looks like some prometheus misconfiguration on your end.
