### ISSUE TITLE
During High Disk utilization, minio pod goes offline on disk read timeout

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#14827]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

During periods of high disk IO (using HDD), the minio pod thinks all the other minio pods are offline on read timeout. This causes put requests in its queue to fail with 503 errors. Ideally, I would have assumed even if it cannot read/write to its own disk, if other pods can function normally, it should be okay to write the object with 1 server being offline. Now, in this scenario, it thinks all the other servers are offline, ie., complete quorum loss and replies with 503 errors.

See below for the logs in minio-pod-0-2,

```
<snip>
Error: Drive /export/data, path (.minio.sys/buckets/.usage.json) returned an error (context deadline exceeded)
<snip>
Error: Marking http://minio-pod-0-1/minio/storage/export/data/v44 temporary offline: caused by Post "http://minio-pod-0-1/minio/storage/export/data/v44/readversion?disk-id=<snip>&file-path=buckets%2F.usage.json&read-data=true&version-id=&volume=.minio.sys": context deadline exceeded
Error: Marking http://minio-pod-0-0/minio/storage/export/data/v44 temporary offline: caused by Post "http://minio-pod-0-0/minio/storage/export/data/v44/readversion?disk-id=<snip>&file-path=buckets%2F.usage.json&read-data=true&version-id=&volume=.minio.sys": context deadline exceeded
Error: Marking http://minio-pod-0-3/minio/storage/export/data/v44 temporary offline: caused by Post "http://minio-pod-0-3/minio/storage/export/data/v44/readversion?disk-id=<snip>&file-path=buckets%2F.usage.json&read-data=true&version-id=&volume=.minio.sys": context deadline exceeded
Error: Marking http://minio-pod-0-4/minio/storage/export/data/v44 temporary offline: caused by Post "http://minio-pod-0-4/minio/storage/export/data/v44/readversion?disk-id=<snip>&file-path=buckets%2F.usage.json&read-data=true&version-id=&volume=.minio.sys": context deadline exceeded
<snip>
```

It is possible this may have been done by design, if true, if you can explain, it will be really helpful.

## Expected Behavior

Read Disk timeout does not cause it to mark all other pods offline.

## Current Behavior

Read Disk timeout causes it to mark all other pods offline. 

## Steps to Reproduce (for bugs)

1. High number of requests with corresponding Disk IO reaching 100% utilization

## Your Environment

* Version used (`minio --version`): RELEASE.2022-04-16T04-26-02Z
* Server setup and configuration: K8s v1.21.3
* Operating System and version (`uname -a`): Linux 3.x kernel

**Comment by harshavardhana** [comment]
This is expected @mshanmu - there is no way for MinIO to do anything here.

**Comment by harshavardhana** [comment]
Depending on IOPs you have you should limit your application. 

```
MINIO_API_REQUESTS_MAX                    (number)    set the maximum number of concurrent requests (default: '0')
MINIO_API_REQUESTS_DEADLINE               (duration)  set the deadline for API requests waiting to be processed (default: '10s')
```

> * Version used (`minio --version`): RELEASE.2022-04-16T04-26-02Z
> * Server setup and configuration: K8s v1.21.3
> * Operating System and version (`uname -a`): Linux 3.x kernel

On top of all this you are also using Linux 3.x

**Comment by aitchjoe** [comment]
hi @harshavardhana we have the same problem and modified `MINIO_API_REQUESTS_MAX`  / `MINIO_API_REQUESTS_DEADLINE` even `MINIO_API_CLUSTER_DEADLINE`, but the problem still exists.

From the call stack:

```
    "error": {
        "message": "Marking http://10.134.48.38:8080/minio/storage/data02/v44 temporary offline; caused by Post \"http://10.134.48.38:8080/minio/storage/data02/v44/readversion?disk-id=ee39f898-5d3e-461c-86ca-3e95891d18ca&file-path=buckets%2F.usage.json&read-data=true&version-id=&volume=.minio.sys\":context deadline exceeded (*fmt.wrapError)",
        "source": [
            "internal/rest/client.go:151:rest.(*Client).Call()",
            "cmd/storage-rest-client.go:153:cmd.(*storageRESTClient).call()",
            "cmd/storage-rest-client.go:505:cmd.(*storageRESTClient).ReadVersion()",
            "cmd/erasure-metadata-utils.go:139:cmd.readAllFileInfo.func1()",
            "internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"
        ]
    }
```

We checked [cmd/storage-rest-client.go](https://github.com/minio/minio/blob/RELEASE.2022-04-16T04-26-02Z/cmd/storage-rest-client.go#L734):

```
	restClient := rest.NewClient(serverURL, globalInternodeTransport, newCachedAuthToken())
```

and [cmd/server-main.go](https://github.com/minio/minio/blob/RELEASE.2022-04-16T04-26-02Z/cmd/server-main.go#L193):

```
	globalInternodeTransport = newInternodeHTTPTransport(&tls.Config{
		RootCAs:            globalRootCAs,
		CipherSuites:       fips.CipherSuitesTLS(),
		CurvePreferences:   fips.EllipticCurvesTLS(),
		ClientSessionCache: tls.NewLRUClientSessionCache(tlsClientSessionCacheSize),
	}, rest.DefaultTimeout)()
```

and the [DefaultTimeout](https://github.com/minio/minio/blob/RELEASE.2022-04-16T04-26-02Z/internal/rest/client.go#L38) is 10 seconds. So I guess there is no way to change the timeout of storage api?

**Comment by klauspost** [comment]
@aitchjoe What you are looking at is the dial timeout to establish a connection.

If your system cannot establish a connection within 10 seconds your harddrives aren't the problem. You probably have network issues. Maybe check your DNS.

The timeout for request to return headers is 15 minutes, and operations that expect to run for a long time will send headers early.

**Comment by aitchjoe** [comment]
Thanks @klauspost but is there any way to change the timeout to avoid "context deadline exceeded" when call http://10.134.48.38:8080/minio/storage/data02/v44/readversion api? I konw the best way is tuning IO perfomance etc, just want to make sure.

**Comment by klauspost** [comment]
@aitchjoe No, you should investigate and fix the underlying issue. 

1) It is unlikely this is actually the issue you are hitting. Dial timeouts are usually marked as such.
2) You should investigate and fix the actual issue in your setup.

**Comment by aitchjoe** [comment]
Ok, thanks!

**Comment by mshanmu** [comment]
@harshavardhana / @klauspost , Questions,

1. Why does a read timeout on local disk causes a timeout on remote readversion REST calls?
2.  Assuming MINIO_API_REQUESTS_MAX is set to a lower number, will "429 Too Many Requests" error be thrown when concurrent requests exceed that limit?
3. IIUC, MINIO_API_REQUESTS_DEADLINE is the timeout for pending requests in the queue rather than request being processed? 
4. If MINIO_API_REQUESTS_DEADLINE is in fact the timeout for requests being processed, is there any negative impact if I set it to a really high value, say 5 minutes? Of course, if MINIO_API_REQUESTS_MAX is set, the number of concurrent requests will be limited.

**Comment by klauspost** [comment]
> will "429 Too Many Requests" error be thrown when concurrent requests exceed that limit

No, requests are blocked until `MINIO_API_REQUESTS_DEADLINE` has expired. There are no timeouts for requests that are processing, the deadline is purely for blocked requests.

As for why the error pops up, I cannot tell you. If you want a deeper analysis of your setup look into https://min.io/pricing

**Comment by mshanmu** [comment]
@klauspost , Thanks for the explanation !! I would like to provide a simple example for my benefit and others,

For simplicity sake, assume, 1 minio server, with MINIO_API_REQUESTS_MAX=10, MINIO_API_REQUESTS_DEADLINE=20 minutes and if there are 200000 Requests per second, only 10 requests will be actively processed and remaining 199990 requests will be accepted and waiting, i.e., 199990 http connections with corresponding 199990 goroutines are created and all waiting. Each blocked request will wait indefinitely until 20 minute expiry or a single request is processed. 

Is this an accurate description? If yes, just curious, why not limit the connections/goroutines at the golang http server using netutil.LimitListener? Is the idea to offload it to a load balancer?
