### ISSUE TITLE
Custom certificate authorities are not used

### ISSUE THREAD

**Issue by rl-simons** [minio/minio#14835]
Hello,

I'm trying to use a custom certificate authority with Minio to send notifications to RabbitMQ which is secured with TLS. Root CA has been addeded to ".minio/certs/CAs/" as documented, however unknown certificate authority is returned by Minio when accessing RabbitMQ. Adding certificates to Linux certificate store resolves the issue.

Certificates:
`.minio/certs/public.crt`
`.minio/certs/private.key`
`.minio/certs/CAs/ca.crt`

Adding certificates to Linux certificate store is not a work around I'd like to use, as I aim to use a container image created using "Dockerfile.scratch" so will not have a certificate store included.

## Expected Behavior
Minio should connect to RabbitMQ with no error messages when storing custom root CAs in ".minio/certs/CAs" or other location defined by "--certs-dir" option.

## Current Behavior
Minio errors with message, when custom root CA is not in OS certificate store, but is available in ".minio/certs/CAs"
`Error: x509: certificate signed by unknown authority (x509.UnknownAuthorityError)`

## Possible Solution
Seems that Minio is not behaving as documented, and using custom root CAs. Minio does however read "public.crt" and "private.key" for access to Minio console & api.

## Steps to Reproduce (for bugs)
1.  Create custom CA & public private key
2. Copy custom CA to ".minio/certs/CAs/"
3. Copy server public cert to ".minio/certs/public.crt"
4. Copy server private key to ".minio/certs/private key"
5. Start Minio with a command such as:
`env MINIO_NOTIFY_AMQP_ENABLE_rabbitmq=On \`
`  MINIO_NOTIFY_AMQP_URL_rabbitmq=amqps://rabbitmq:5672/ \`
`  MINIO_NOTIFY_AMQP_EXCHANGE_rabbitmq=bucketevents \`
`  MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_rabbitmq=fanout \`
`  MINIO_NOTIFY_AMQP_ROUTING_KEY_rabbitmq=bucketlogs \`
`  MINIO_NOTIFY_AMQP_DELIVERY_MODE_rabbitmq=0 \`
`  MINIO_NOTIFY_AMQP_DURABLE_rabbitmq=False \`
`  MINIO_NOTIFY_AMQP_INTERNAL_rabbitmq=False \`
`  MINIO_NOTIFY_AMQP_AUTO_DELETED_rabbitmq=False \`
`  MINIO_NOTIFY_AMQP_QUEUE_DIR_rabbitmq=/home/user/minio/queues/AQMP/ \`
`  minio \`
`    server /home/user/minio/export \`
`    --address :9000 \`
`    --console-address :9001`
6. On start Minio presents error message:
`API: SYSTEM()
Time: 09:27:08 UTC 04/29/2022
DeploymentID: fd4c49b4-8505-4db2-a276-e64342519bc
Error: x509: certificate signed by unknown authority (x509.UnknownAuthorityError)
      14: internal/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
      13: internal/logger/logonce.go:92:logger.LogOnceIf()
      12: internal/event/target/amqp.go:336:target.NewAMQPTarget()
      11: internal/config/notify/parse.go:134:notify.fetchSubSysTargets()
      10: internal/config/notify/parse.go:392:notify.FetchRegisteredTargets()
       9: internal/config/notify/parse.go:95:notify.RegisterNotificationTargets()
       8: internal/config/notify/parse.go:86:notify.GetNotificationTargets()
       7: cmd/config-current.go:545:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:385:cmd.initConfigSubsystem()
       2: cmd/server-main.go:352:cmd.initServer()
       1: cmd/server-main.go:531:cmd.serverMain()`

`API: SYSTEM()
Time: 09:27:08 UTC 04/29/2022
DeploymentID: fd4c49b4-8505-4db2-a276-e64342519bce
Error: Unable to initialize notification target(s): one or more targets are offline. Please use `mc admin info --json` to check the offline targets (*fmt.wrapError)
       7: cmd/config-current.go:547:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:385:cmd.initConfigSubsystem()
       2: cmd/server-main.go:352:cmd.initServer()
       1: cmd/server-main.go:531:cmd.serverMain()`

`API: SYSTEM()
Time: 09:27:08 UTC 04/29/2022
DeploymentID: fd4c49b4-8505-4db2-a276-e64342519bce
Error: Unable to initialize notification target(s): one or more targets are offline. Please use `mc admin info --json` to check the offline targets (*fmt.wrapError)
       7: cmd/config-current.go:552:cmd.lookupConfigs()
       6: cmd/config-current.go:801:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:385:cmd.initConfigSubsystem()
       2: cmd/server-main.go:352:cmd.initServer()
       1: cmd/server-main.go:531:cmd.serverMain()`

## Context
I want to use docker container based on "Dockerfile.scratch" and custom root CAs.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-04-26T01-20-24Z
* Server setup and configuration: Debian Linux
* Operating System and version (`uname -a`): Linux {hostname} 5.10.89-v7+ SMP Tue Jan 4 19:51:16 GMT 2022 armv7l GNU/Linux

**Comment by harshavardhana** [comment]
You cannot use Dockerfile.scratch please use official published container images.

Scratch is not possible because of lack of OS in the container level.

**Comment by rl-simons** [comment]
Could you please provide a more detailed explanation. This error occurs even if not using Docker.scratch. The error occurs if running on a linux computer where the custom CA root is not included within OS certificate store. Documentation details the configuration is possible.

**Comment by harshavardhana** [comment]
> Could you please provide a more detailed explanation. This error occurs even if not using Docker.scratch. The error occurs if running on a linux computer where the custom CA root is not included within OS certificate store. Documentation details the configuration is possible.

Just use our published containers based on RHEL-UBI8

**Comment by rl-simons** [comment]
Using the published Docker image doesn't include the custom CA certs and therfore the problem will exist.
As noted above this occurs when using the native binary on bare metal.
What is the purpose of -S and - - certs-dir? What is the scenario these are for if not as described in the documentation to address the outlined issue?

**Comment by harshavardhana** [comment]
> Using the published Docker image doesn't include the custom CA certs and therfore the problem will exist. As noted above this occurs when using the native binary on bare metal. What is the purpose of -S and - - certs-dir? What is the scenario these are for if not as described in the documentation to address the outlined issue?

Everything thing should work as documented.

**Comment by rl-simons** [comment]
Sorry for the late reply, have been away a couple of days.

Yes everything should work as expected, but it doesn't.  What is the role of CAs directory if not to store custom CA certificates for communicating with external services? Documentation `https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html` section 4 and here `https://docs.min.io/minio/baremetal/security/network-encryption/minio-tls.html`, and this blog post: `https://blog.min.io/secure-minio-1/amp/`
**MinIO may need to talk to other services, like an audit log service, securely. Hence, MinIO has to be able to verify the TLS certificates of these services, and therefore, needs the certificate(s) of the issuing CAs. Such CA certificates should be placed into the certs/CAs/ directory**

This is exactly what I'm trying to do and as stated it doesn't work.

Reviewing your comments, yes I could mount the hosts CA store inside the docker container, however that's not really an option in my scenario and this issue occurs on baremetal.

Minio as documented should add the CA certificates in the CAs directory to it's certificate pool.

**Comment by harshavardhana** [comment]
We deploy this every day I don't see how it will not work. It works locally on my laptop and elsewhere in countless other deployments. I can't imagine on my end what you might have done wrong - you would have to figure it out yourself unfortunately sorry.
