### ISSUE TITLE
Unable to make bucket `alias/bucket`. The specified bucket does not exist

### ISSUE THREAD

**Issue by timrabl** [minio/minio#14836]
I've setup a fresh distributed MinIO cluster consisting of 8 nodes, each with a 1 TB virtual hard disk, 4vCPUS and 4GB of RAM.
The cluster is virtualized on QEMU/KVM, each node runs the latest 20.04.4 LTS (Focal Fossa).

All MinIO nodes are in the same Layer 2 subnet. Node to node communiaction is encrypted over TLS.
So each node has it's own ECDSA-SHA512 / prime256v1 key pair, signed by a CA ( distributed to every nodes trust store )

Client to cluster / node communication goes over the WAN to a HAProxy loadbalancer cluster ( 3 nodes, round robin ).
Communication is encrypted over TLS too, but TLS is terminated here to serve official Let's Encrypt certificates to the WAN.

One might think that everything works wonderfully, because the cluster is online in the web interface and all healthcheck endpoints return a HTTP/200 (OK) when queried using the MinIO client, but i can't create a new bucket. Neither trough the webUI nor via the MinIO client.

## Expected Behavior

`mcli mb cluster1/test` does create a new bucket and return the typical MinIO bucket created successfuly messgae, e.q HTTP/200 (OK).
Alternatively, bucket creation works via the web interface.

## Current Behavior
Please assume that:
* `ip.client.example.org` is the WAN IP of the requesting client
* `client.example.org` is the clients hostname
* `console.minio.example.org` is the MinIO Console endpoint behind the loadbalancer cluster
* `minio.example.org` is the MinIO API endpoint behind the loadbalancer cluster
* `node8.example.org` is the hostname of of the eighth MinIO node
* `cluster1` is the configured alias (admin credentials) on `client.example.org`
* `test` is the name of the bucket, that failed

Neither the WebUI (console.minio.example.org) nor `mcli --debug mb cluster1/test` creates a new bucket.
Instead MinIO CLI returns HTTP/404 (NOT FOUND) with the following error message:

> mcli: <DEBUG> PUT /test/ HTTP/1.1
> Host: minio.example.org
> User-Agent: MinIO (linux; amd64) minio-go/v7.0.24 mcli/RELEASE.2022-04-26T18-00-22Z
> Content-Length: 0
> Authorization: AWS4-HMAC-SHA256 Credential=cluster1/20220429/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20220429T105831Z
> Accept-Encoding: gzip
> 
> mcli: <DEBUG> HTTP/1.1 404 Not Found
> Content-Length: 304
> Accept-Ranges: bytes
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/xml
> Date: Fri, 29 Apr 2022 10:58:30 GMT
> Server: MinIO
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Strict-Transport-Security: max-age=15768000
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Request-Id: 16EA58DACCD60727
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> 
> \<?xml version="1.0" encoding="UTF-8"?\>
> \<Error\>\<Code\>NoSuchBucket\</Code\>\<Message\>The specified bucket does not exist\</Message\>\<Key\>test/\</Key\>\<BucketName\>minio\</BucketName\>\<Resource\>/test/\</Resource\>\<RequestId\>16EA58DACCD60727\</RequestId\>\<HostId>00c0033a-b572-4fae-8d99-6e72f6abd885\</HostId\>\</Error\>mcli: \<DEBUG\> TLS Certificate found:
> mcli: \<DEBUG\>  >> Country: US
> mcli: \<DEBUG\>  >> Organization: Let's Encrypt
> mcli: \<DEBUG\>  >> Expires: 2022-07-06 19:46:04 +0000 UTC
> mcli: \<DEBUG\> TLS Certificate found:
> mcli: \<DEBUG\>  >> Country: US
> mcli: \<DEBUG\>  >> Organization: Internet Security Research Group
> mcli: \<DEBUG\>  >> Expires: 2025-09-15 16:00:00 +0000 UTC
> mcli: \<DEBUG\> TLS Certificate found:
> mcli: \<DEBUG\>  >> Organization: Digital Signature Trust Co.
> mcli: \<DEBUG\>  >> Expires: 2024-09-30 18:14:03 +0000 UTC
> mcli: \<DEBUG\> Response Time:  156.009ms
> 
> mcli: <ERROR> Unable to make bucket `cluster1/test`. The specified bucket does not exist
>  (1) mb-main.go:149 cmd.mainMakeBucket(..) Tags: [cluster1/test]
>  (0) client-s3.go:1344 cmd.(*S3Client).MakeBucket(..)
>  Commit:276e1db70d7b | Release-Tag:RELEASE.2022-04-26T18-00-22Z | Host:client.example.org | OS:linux | Arch:amd64 | Lang:go1.17.9 | Mem:3.1 MB/17 MB | Heap:3.1 MB/7.7 MB

Output of `mcli admin trace --verbose --errors cluster1`:

> node8.example.org:9000 [REQUEST s3.PutObject] [2022-04-29T11:43:21:000] [Client IP: ip.client.example.org]
> node8.example.org:9000 PUT /test/
> node8.example.org:9000 Proto: HTTP/1.1
> node8.example.org:9000 Host: minio.example.org
> node8.example.org:9000 Authorization: AWS4-HMAC-SHA256 Credential=XV9GIRC0PYSO1TWM61EO/20220429/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=\<\<CUSTOM REDACTED\>\>
> node8.example.org:9000 Content-Length: 0
> node8.example.org:9000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.24
> node8.example.org:9000 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> node8.example.org:9000 X-Forwarded-For: ip.client.example.org
> node8.example.org:9000 X-Amz-Date: 20220429T094321Z
> node8.example.org:9000 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJYVjlHSVJDMFBZU08xVFdNNjFFTyIsImV4cCI6MTY1MTIyODU3MCwicGFyZW50IjoiYWRtaW4ifQ.6TyLAFX4KNPojCbYljdF9lWHXqpjeZi4lPVz-zn5jJtyFSFhSN3DQ8ChRmsvMSGZBUeQl3rqU0nyRY_0_SHL8w
> node8.example.org:9000 X-Forwarded-Port: 443
> node8.example.org:9000 X-Forwarded-Proto: https
> node8.example.org:9000 <BODY>
> node8.example.org:9000 [RESPONSE] [2022-04-29T11:43:21:000] [ Duration 6.923ms  ↑ 149 B  ↓ 627 B ]
> node8.example.org:9000 404 Not Found
> node8.example.org:9000 Content-Length: 304
> node8.example.org:9000 Content-Security-Policy: block-all-mixed-content
> node8.example.org:9000 Server: MinIO
> node8.example.org:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
> node8.example.org:9000 X-Amz-Request-Id: 16EA54C0F6F517C1
> node8.example.org:9000 Accept-Ranges: bytes
> node8.example.org:9000 Content-Type: application/xml
> node8.example.org:9000 Vary: Origin,Accept-Encoding
> 
> node8.example.org:9000 X-Content-Type-Options: nosniff
> node8.example.org:9000 X-Xss-Protection: 1; mode=block
> node8.example.org:9000 <?xml version="1.0" encoding="UTF-8"?>
> \<Error\>\<Code\>NoSuchBucket\</Code\>\<Message\>The specified bucket does not exist\</Message\>\<Key\>test/\</Key\>\<BucketName\>minio\</BucketName\>\<Resource\>/test/\</Resource\>\<RequestId>16EA54C0F6F517C1\</RequestId\>\<HostId\>00c0033a-b572-4fae-8d99-6e72f6abd885\</HostId\>\</Error\>

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Sping up 8 VM's (4vCPU's, 4GB RAM, 1TB Hard Disk mounted under /minio, formatted as ext4)
2. Create a minio user called `minio` (home path `/opt/minio/`)
3. Make sure /minio is owned by user `minio`
4. Install the latest minio binary under minio users home path
5. Create a systemd service file that runs the minio server as user `minio` with all variables located in `/etc/default/minio`
6. Change the required varibales to ur needs
7. Create a certificate infrastructure ( CA on each node and sign node certs with CA )
8. Start ststemd MinIO Service

## Context
Mentioned above...

## Regression
Maybe, maybe not...
Before that I used the binary version `RELEASE.2021-12-29T06-49-06Z`, where the error also occurred initially, but disappeared by itself after a while.

## Your Environment
* Server setup and configuration:
* * 3 x HAProxy a Loadbalancer for client connections, QEMU/KVM 20.04.4 LTS (Focal Fossa) 2vCPUS, 1G RAM
* * 8 x MinIO Nodes, QEMU/KVM 20.04.4 LTS (Focal Fossa) 4 vCPU's, 4GB RAM, 1TB ext4 Virtual HardDisk
* Operating system / version: `Linux [*REDACTED*] 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* MinIO server Version: `RELEASE.2022-04-29T01-27-09Z`
* MinIO client version: `RELEASE.2022-04-26T18-00-22Z`
* MinIO server binary permissions:
```root@node8.example.org:/opt/minio# ls -laht .
total 90M
drwxr-x--- 3 minio minio 4.0K Apr 29 11:30 .minio
drwxr-xr-x 3 minio minio 4.0K Apr 29 11:30 .
-rwxr-x--- 1 minio minio  90M Apr 29 11:29 minio
drwxr-xr-x 3 root  root  4.0K Apr 29 11:27 ..
```
* MinIO hard drive permissions:
```root@node8.example.org:/minio# ls -laht .
total 28K
drwxr-x---  4 minio minio 4.0K Apr 29 11:43 .
drwxr-xr-x  8 minio minio 4.0K Apr 29 11:31 .minio.sys
drwxr-xr-x 19 root  root  4.0K Apr 29 11:19 ..
drwxr-x---  2 minio minio  16K Apr 29 11:19 lost+found
```

**Comment by klauspost** [comment]
@timrabl You post everything, *except* the commandline params you use to start the cluster.

I suspect you haven't actually linked your cluster and you have separate servers that don't know anything about eachother.

**Comment by kannappanr** [comment]
Here it is assuming that you are doing DNS style addressing, with minio being the bucket and test being the object name. I think some of the env variables set here might be wrong

**Comment by timrabl** [comment]
> @timrabl You post everything, _except_ the commandline params you use to start the cluster.
> 
> I suspect you haven't actually linked your cluster and you have separate servers that don't know anything about eachother.

Sorry, i forgot ^^

So this is the systemd unit file...
```
root@node8:~# cat /etc/systemd/system/minio.service
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/opt/minio/minio

[Service]
WorkingDirectory=/usr/local

User=minio
Group=minio

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/opt/minio/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```

... that leads to minio server running as:
```
root@node8:~# ps -ax | grep minio
29063 ?        Ssl    6:21 /opt/minio/minio server --address :9000 --console-address :9001 https://node{1...8}.example.org/minio
```

**Comment by harshavardhana** [comment]
It's using DNS style with no DNS lookup present on the system. Naturally it's converting MakeBucket into a PutObject operation.

**Comment by timrabl** [comment]
> It's using DNS style with no DNS lookup present on the system. Naturally it's converting MakeBucket into a PutObject operation.

Can you explain to me what you mean by "no DNS lookup present on the system" ?
The internal resolvers correctly resolve the hostnames to the corresponding IP addresses, and the TCP ports 9000 and 9001 are also open on all VM's. As already mentioned, all machines are on the same subnet.

**Comment by harshavardhana** [comment]
> > It's using DNS style with no DNS lookup present on the system. Naturally it's converting MakeBucket into a PutObject operation.
> 
> Can you explain to me what you mean by "no DNS lookup present on the system" ? The internal resolvers correctly resolve the hostnames to the corresponding IP addresses, and the TCP ports 9000 and 9001 are also open on all VM's. As already mentioned, all machines are on the same subnet.

It's your mc configuration @timrabl

**Comment by timrabl** [comment]
> > > It's using DNS style with no DNS lookup present on the system. Naturally it's converting MakeBucket into a PutObject operation.
> > 
> > 
> > Can you explain to me what you mean by "no DNS lookup present on the system" ? The internal resolvers correctly resolve the hostnames to the corresponding IP addresses, and the TCP ports 9000 and 9001 are also open on all VM's. As already mentioned, all machines are on the same subnet.
> 
> It's your mc configuration @timrabl

So thanks for the support first, so this was my MinIO config (local) when opening the issue:

```
➜  ~ cat .mcli/config.json
{
        "version": "10",
        "aliases": {
                "admin": {
                        "url": "https://minio.example.org",
                        "accessKey": "admin",
                        "secretKey": "[*REDACTED*]",
                        "api": "S3v4",
                        "path": "dns"
                }
        }
}
```

But even after changing the "path" option of my mc config to "auto", I get the same error.
```
➜  ~ cat .mcli/config.json
{
        "version": "10",
        "aliases": {
                "admin": {
                        "url": "https://minio.example.org",
                        "accessKey": "admin",
                        "secretKey": "[*REDACTED*]",
                        "api": "S3v4",
                        "path": "auto"
                }
        }
}
```

In addition, I can't create a bucket via the web interface, which has nothing to do with my MinIO client.

**Comment by timrabl** [comment]
> assuming that you are doing DNS style addressing, with minio being the bucket and test being the object name.

@kannappanr I think I'm using DNS style addressing (according to @harshavardhana).
But I have to admit that I don't really know how to tell.

The environment variables with which the MinIO server starts are attached:
```
root@node8:~# cat /etc/default/minio
MINIO_DOMAIN="example.org"
MINIO_VOLUMES="https://node{01...08}.example.org/minio"
MINIO_OPTS="--address :9000 --console-address :9001"
MINIO_ROOT_USER="admin"
MINIO_ROOT_PASSWORD="[*REDACTED*]"
MINIO_API_CORS_ALLOW_ORIGIN="https://minio.example.org"
MINIO_BROWSER_REDIRECT_URL="https://console.minio.example.org"
MINIO_SERVER_URL="https://minio.example.org"
```

**Comment by harshavardhana** [comment]
> MINIO_DOMAIN="example.org"

you do not need this @timrabl

**Comment by harshavardhana** [comment]
> MINIO_API_CORS_ALLOW_ORIGIN="https://minio.example.org"
> MINIO_BROWSER_REDIRECT_URL="https://console.minio.example.org"
> MINIO_SERVER_URL="https://minio.example.org"

All these settings are wrong you have a subdomain hosted at top level MINIO_DOMAIN this causes MINIO to parse `minio` to be the bucket name here. since you have enabled DNS style requests.

MINIO_DOMAIN should match MINIO_SERVER_URL domain such as keep it same as 

```
MINIO_DOMAIN=minio.example.org
```

Is the correct setting here.

**Comment by timrabl** [comment]
Thanks @harshavardhana, changing the domain to minio.example.org solved the problem.
Even if minio.example.org is not a subdomain in this case, but I think that MinIO just doesn't check the NS entries on the resolvers (example.org), which is why it's called "dns style addressing" and not "dns addressing".
