### ISSUE TITLE
Minio crashes with segmentation fault if MINIO_IDENTITY_OPENID_CONFIG_URL does not specify port number

### ISSUE THREAD

**Issue by univac490** [minio/minio#14841]
MINIO_IDENTITY_OPENID_CONFIG_URL=https://host.example.com/auth/realms/demo/.well-known/openid-configuration

causes segmentation fault

MINIO_IDENTITY_OPENID_CONFIG_URL=https://host.example.com:443/auth/realms/demo/.well-known/openid-configuration

works.

## Expected Behavior

no segmentation fault

## Current Behavior

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe45ee9]

goroutine 1 [running]:
github.com/minio/minio/internal/config/identity/openid.LookupConfig(0xc003204c30, {0x49a8b20, 0xc003212000}, 0x4615128, {0x0, 0x0})
	github.com/minio/minio/internal/config/identity/openid/jwt.go:824 +0x1209
github.com/minio/minio/cmd.lookupConfigs(0x49e6070, {0x4a53080, 0xc002baf260})
	github.com/minio/minio/cmd/config-current.go:520 +0x12a8
github.com/minio/minio/cmd.loadConfig({0x4a53080, 0xc002baf260})
	github.com/minio/minio/cmd/config-current.go:800 +0x5e
github.com/minio/minio/cmd.initConfig({0x4a53080, 0xc002baf260})
	github.com/minio/minio/cmd/config.go:235 +0x1a5
github.com/minio/minio/cmd.(*ConfigSys).Init(...)
	github.com/minio/minio/cmd/config.go:195
github.com/minio/minio/cmd.initConfigSubsystem({0x49e6070, 0xc0004f6580}, {0x4a53080, 0xc002baf260})
	github.com/minio/minio/cmd/server-main.go:385 +0x4f
github.com/minio/minio/cmd.initServer({0x49e6070, 0xc0004f6580}, {0x4a53080, 0xc002baf260})
	github.com/minio/minio/cmd/server-main.go:352 +0x2d7
github.com/minio/minio/cmd.serverMain(0xc0001196c0)
	github.com/minio/minio/cmd/server-main.go:531 +0xfbb
github.com/minio/cli.HandleAction({0x2166d40, 0x4614fa8}, 0x6)
	github.com/minio/cli@v1.22.0/app.go:500 +0x7b
github.com/minio/cli.Command.Run({{0x25bfa8f, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x25f7ca1, 0x1b}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.22.0/command.go:225 +0x9f7
github.com/minio/cli.(*App).Run(0xc000119040, {0xc00011c000, 0x5, 0x5})
	github.com/minio/cli@v1.22.0/app.go:261 +0x7ac
github.com/minio/minio/cmd.Main({0xc00011c000, 0x5, 0x5})
	github.com/minio/minio/cmd/main.go:168 +0x59
main.main()
	github.com/minio/minio/main.go:33 +0x2e

## Possible Solution

line 783:

configURLDomain, _, err = net.SplitHostPort(p.URL.Host)
if err != nil {
	configURLDomain = p.URL.Host
}

## Steps to Reproduce (for bugs)

Configure OIDC using environment variables with MINIO_IDENTITY_OPENID_CONFIG_URL without port.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-04-29T01-27-09Z
* Server setup and configuration: Docker container
* Operating System and version (`uname -a`): <pre>Linux minio-1 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux</pre>

**Comment by harshavardhana** [comment]
@univac490 the correct fix is different https://github.com/minio/minio/pull/14842

**Comment by harshavardhana** [comment]
Fixed by #14842
