### ISSUE TITLE
fatal error: concurrent map iteration and map write on github.com/minio/minio/cmd.cloneMSS crashing MinIO

### ISSUE THREAD

**Issue by j-mie** [minio/minio#14856]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Not to crash

## Current Behavior

https://gist.github.com/jamie-34254/a0246a63dd0dd11fe064386ef64239e5

## Steps to Reproduce (for bugs)

Not 100% sure

## Context

Causes a MinIO instance to crash causing cluster stability issues

## Regression

It didn't happen a few months ago but does happen after we upgraded to a newer release, can't remember which version we were on but I believe it was from 2020 so quite an old release.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-04-26T01-20-24Z
* Server setup and configuration: 4 minio servers in a cluster with caching enabled
* Operating System and version (`uname -a`): `Linux minio-04 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Do not use disk caching with distributed setup, this is not supported.

**Comment by harshavardhana** [comment]
However let's fix the crash.. 

```
Apr 30 21:16:53 minio-04 minio[15080]: fatal error: concurrent map iteration and map write
Apr 30 21:16:53 minio-04 minio[15080]: goroutine 739511348 [running]:
Apr 30 21:16:53 minio-04 minio[15080]: runtime.throw({0x2617dd8, 0x110})
Apr 30 21:16:53 minio-04 minio[15080]:         runtime/panic.go:1198 +0x71 fp=0xc00b5f7740 sp=0xc00b5f7710 pc=0x4370f1
Apr 30 21:16:53 minio-04 minio[15080]: runtime.mapiternext(0x2254de0)
Apr 30 21:16:53 minio-04 minio[15080]:         runtime/map.go:858 +0x4eb fp=0xc00b5f77b0 sp=0xc00b5f7740 pc=0x40fbeb
Apr 30 21:16:53 minio-04 minio[15080]: github.com/minio/minio/cmd.cloneMSS(0xc276c0b500)
Apr 30 21:16:53 minio-04 minio[15080]:         github.com/minio/minio/cmd/utils.go:129 +0x98 fp=0xc00b5f7858 sp=0xc00b5f77b0 pc=0x1f20698
Apr 30 21:16:53 minio-04 minio[15080]: github.com/minio/minio/cmd.(*diskCache).put(_, {_, _}, {_, _}, {_, _}, {_, _}, 0x24, ...)
Apr 30 21:16:53 minio-04 minio[15080]:         github.com/minio/minio/cmd/disk-cache-backend.go:889 +0x3b6 fp=0xc00b5f7b78 sp=0xc00b5f7858 pc=0x1cd5436
Apr 30 21:16:53 minio-04 minio[15080]: 
```
