### ISSUE TITLE
Feature Request: Admin command to mark drive/endpoint as offline

### ISSUE THREAD

**Issue by networkjackbb** [minio/minio#14859]
The current documentation states that to replace a failing drive, one should "unmount the failed drive".

https://docs.min.io/minio/baremetal/installation/restore-minio.html

However, this doesn't cover situations where the drive has not yet failed but it's doom is imminent from certain signals (slowness, SMART, etc....)

The problem comes in when attempting to (on linux) "umount" the drive mount. Without resorting to using the "FORCE" parameter to umount, any reasonable amount of activity by MinIO against said drive will prevent it from being umount'ed because it is "busy"/ i.e. has open files.

This needs to be handled more gracefully from a management/sysops standpoint. We need an explicit "mc admin" command that will mark a specific drive as "offline".

When I perform a "mc admin info --json", I get a very complete list of endpoints:

  "endpoint": "http://nst3.XXXXXXX.net:9000/nstdata/disk4/minio",
  "path": "/nstdata/disk4/minio",
  "state": "ok",
  "uuid": "986bd328-0d87-4da5-a61e-6466508f5a01",

so what is needed now, is some form of "mc admin manage” command which will take one UUID parameter which then marks that endpoint as being “offline”. MinIO should then close any files it may have open on that drive, and then performing a graceful umount and drive replacement is possible.

**Comment by harshavardhana** [comment]
We already mark unresponsive drives offline after x amount of failures. 

We do not need any other explicit calls to mark this behavior. 

MinIO is not a privileged process to manage your drives, they need to managed outside using something like a CSI layer for example DirectPV.

**Comment by networkjackbb** [comment]
This has nothing to do with asking MinIO to "manage the drive".
This request is to have something explicit and purposeful and controlled for MinIO to gracefully stop using the drive so **I** can manage it. This request is not meant for drives that have _already_ failed. That scenario is already covered as you explain.

This feature request is for two specific use cases for when a non-failed drive needs to be replaced:
1. A drive that is showing pre-failure attributes.
2. A drive that is to be replaced with some drive that is bigger/better/faster so as to "upgrade" the cluster.

Telling your enterprise customers: "just yank the drive", is not a "professional-level" response.

**Comment by networkjackbb** [comment]
Based on your commentary, it seems like perhaps you read something into the last sentence of the original message that was not intended to be there:

"MinIO should then close any files it may have open on that drive, and then performing a graceful umount and drive replacement is possible."

I was not suggesting that the actions listed **after** the comma in the sentence were to be performed by MinIO. I, as the sysadmin of that system, would be performing them.

**Comment by klauspost** [comment]
> Without resorting to using the "FORCE" parameter to umount,

That is the reason for not forcing? If the drive is physically broken or needs a reformat there is no purpose in a safe unmount.

**Comment by harshavardhana** [comment]
@networkjackbb for us the drive is actually just a folder we have no idea that it is actually a "drive" - so to mark a drive offline will not be "trivial" because that is a state that we need to persist - an in-memory state won't be that useful if someone restarts MinIO on that node. 

To do this cleanly MinIO needs to fully manage the drive which is not part of our design.  Yanking the drive is the best way since MinIO handles "hotswapping" - you can always remove the drive while MinIO is running and then add a fresh one - reformat and mount same location. MinIO will detect it and heal the drive all without restarting the service on that node.

Since we provide this kind of hotswapping functionality, you do not need to resort to old-school IT practices anymore.

**Comment by networkjackbb** [comment]
@klauspost
> > Without resorting to using the "FORCE" parameter to umount,
> 
> That is the reason for not forcing? If the drive is physically broken or needs a reformat there is no purpose in a safe unmount.

I'm not sure where you are getting this "broken"/"needs a reformat" scenario from considering I enumerated two specific instances that were NOT about a broken drive.

**Comment by networkjackbb** [comment]
@harshavardhana
> for us the drive is actually just a folder we have no idea that it is actually a "drive"

That's not exactly true, is it? MinIO certainly does keep track of "drive" characteristics:

from _mc admin info --json_:
```
"endpoint": "http://nst3.XXXXXXX.net:9000/nstdata/disk6/minio",
"path": "/nstdata/disk6/minio",
"state": "ok",
"uuid": "bb26357b-9f43-48dc-8c3a-05d1c02f6dde",
"totalspace": 3998832455680,
"usedspace": 16969531392,
"availspace": 3981862924288,

```

 - so to mark a drive offline will not be "trivial" because that is a state that we need to persist - an in-memory state won't be that useful if someone restarts MinIO on that node.

Uh... you have a "state" variable right there. And if someone restarts MinIO, that's OK in terms of a management scenario. I'm referencing a use case for a set of serial operations to mark an endpoint offline and stay offline long enough to gracefully "umount" the drive.

> To do this cleanly MinIO needs to fully manage the drive which is not part of our design.

I disagree that MinIO needs to manage anything. You already have a state in MinIO for when an endpoint is not accessible (because of true failure) and I assume you close any file system handles to anything on that mount point. All I'm asking for is a admin verb that short-circuit commands MinIO to get to that same exact state for a specific endpoint bypassing any of your normal file-system failure detection code. This state only needs to persist for a short time. I'm assuming that you already have some sort of built-in delay before attempting to access the same folder to see if there is a usable file system underneath it. My "umount" would occur during that window.


> Since we provide this kind of hotswapping functionality, you do not need to resort to old-school IT practices anymore.

"old-school IT practices" are good because they are dependable in the face of multiple layers of hardware/firmware/kernel/userspace complexities.  My long years of experience in managing just these kinds of systems has informed me that "Yanking a drive" type operations lean over into the "playing with fire" category.

Adding this kind of verb should not be hard and provides a simple way to facilitate a common IT task.

You want people to learn about, play with and eventually adopt your product. Providing them with these kinds of quality of life type features is an easy win and shows that MinIO is mindful about being a good citizen in its operating environment.

**Comment by klauspost** [comment]
@networkjackbb Both remote and local drives are transiently monitored and taken offline if they appear to have issues.

> I enumerated two specific instances that were NOT about a broken drive

> A drive that is showing pre-failure attributes.

The drive should be replaced and full disk healing should be done by MinIO. You should not need/attempt to copy data from it.

> A drive that is to be replaced with some drive that is bigger/better/faster so as to "upgrade" the cluster.

This is not how you expand capacity, see https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html on how to add additional capacity.

If you want a drive offline for replacement, unmount it. There is no need for additional operator complexity, adding extra tasks for an operation.

**Comment by networkjackbb** [comment]
@klauspost 
> Both remote and local drives are transiently monitored and taken offline if they appear to have issues.
> 
> > I enumerated two specific instances that were NOT about a broken drive
> 
> > A drive that is showing pre-failure attributes.
> 
> The drive should be replaced and full disk healing should be done by MinIO. You should not need/attempt to copy data from it.

I'm not sure where you are getting these ideas.

I **am** trying to replace the drive. I'm asking for something that will tell MinIO to gracefully let go of the drive. Then I will un-mount using standard OS level methods.

I am **not** and never stated anything even remotely related to trying to copy data from it. Again, not sure where you are reading into my statements any attempt at doing so.


> 
> > A drive that is to be replaced with some drive that is bigger/better/faster so as to "upgrade" the cluster.
> 
> This is not how you expand capacity, see https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html on how to add additional capacity.

I've read those documents and those ideas are great if you have unlimited drive slots or budgets to replace node hardware/networks, etc. 

Upgrading capacity in a resilient storage system by sequentially replacing a disk with one of larger capacity so as to not disturb any upper layer processes that depend on it is a well-known "old-school IT practice."

And why is it important what the underlying reason is for me needing to replace the drive? It's not. Don't get off topic.



> 
> If you want a drive offline for replacement, unmount it. There is no need for additional operator complexity, adding extra tasks for an operation.

Klaus, I suggest you take a deep breath and go back and read from the beginning. You have completely missed the point and added a whole bunch of irrelevant ideas to the discussion so far.

**Comment by networkjackbb** [comment]
@klauspost @harshavardhana 
Might I suggest a little more humility and openness from the two of you in regards to how people interact/use/deploy your software. You might actually learn something from other people and in turn end up with a better product that more people will accept and utilize.

**Comment by harshavardhana** [comment]
@networkjackbb thanks will think about it - for now, let's close this discussion.
