### ISSUE TITLE
ERROR Unable to initialize a connection to KES 

### ISSUE THREAD

**Issue by MehdiAroui** [minio/minio#14879]
## Expected Behavior
MinIO Server should connect to the KES instance

## Current Behavior
MinIO Server enable to start and got the error **"ERROR Unable to initialize a connection to KES as specified by the shell environment: Method Not Allowed"**

## Context
Enabling the encryption of objects.

## Environment
* Version used : **RELEASE.2022-04-12T06-55-35Z** and **RELEASE.2022-05-04T07-45-27Z**

**Comment by harshavardhana** [comment]
Please share your kes server config - looks like you made some setup mistakes here.

**Comment by harshavardhana** [comment]
Ah looks like yes, all wrong kes deployment and configuration - please read https://github.com/minio/kes/wiki on how to setup KES properly.

**Comment by tgeci** [comment]
Hello!
I am having the same issue, any hints. I read wiki few times and did not find the solution. Is there any option to get more information what the problem is ?

Here is my kes config
```
        address: 0.0.0.0:8383 
        admin:
            identity: false  # We disable the admin identity since we don't need it in this guide 
        log: 
            error: on
        tls:
            key: /tls/tls.key    # The KES server TLS private key
            cert: /tls/tls.crt    # The KES server TLS certificate
        keystore:
            vault:
              approle:
                id: ***private information***
                retry: 15s
                secret: ***private information***
              endpoint: https://vault:8200
              status:
                ping: 10s
              tls:
                ca: /tls/ca.crt
              version: v1
        policy:
            minio:
              allow:
              - /v1/key/create/minio-key*
              - /v1/key/generate/minio-key*
              - /v1/key/decrypt/minio-key*
              identities:
              - ***private information***
```
