### ISSUE TITLE
minio SDK for R 

### ISSUE THREAD

**Issue by Psr18delhi** [minio/minio#14874]
**Is your feature request related to a problem? Please describe.**
I can't use the minio in my r code

**Describe the solution you'd like**
Similar to Python SDK can you add the R Supportive SDK. 

**Describe alternatives you've considered**
Currently, I am using reticulate to call mino python package, and then I am using the functionality. 

**Additional context**

**Comment by harshavardhana** [comment]
Python SDK is what we have, we currently have no bandwidth for another language SDK. May be in future.
