### ISSUE TITLE
feat: Support getObjectAttributes() ("?attributes" parameter) to returns object attributes

### ISSUE THREAD

**Issue by smesh** [minio/minio#14884]
## Expected Behavior
getObjectAttributes() should return object attributes

## Current Behavior
getObjectAttributes() returns object itself instead of its attributes

## Steps to Reproduce (for bugs)
Request url is the same url as for object, plus "?attributes" parameter.
For example, /sample-bucket/sample-folder/sample-object.json?attributes

## Your Environment
minio.exe version RELEASE.2022-02-24T22-12-01Z
Windows 10

**Comment by harshavardhana** [comment]
We do not implement this API @smesh

**Comment by smesh** [comment]
I could use headObject() instead of getObjectAttributes(). I'm OK if this issue will be closed.

**Comment by harshavardhana** [comment]
> I could use headObject() instead of getObjectAttributes(). I'm OK if this issue will be closed.

getObjectAttributes() mostly looks like an unnecessary API at this moment, It returns a combination of Head + ListParts output.

It seems a bit excessive at this point in time, closing.

**Comment by jfantinhardesty** [comment]
@harshavardhana GetObjectAttributes is not entirely an unnecessary API. In particular it allows you to get a list of all the parts of an object without needing the UploadID associated with the multipart upload that ListParts requires. This is useful when you may want to know the parts associated with an object after it has already been uploaded. Any chance this could be reopened to implement this API?

**Comment by harshavardhana** [comment]
> @harshavardhana GetObjectAttributes is not entirely an unnecessary API. In particular it allows you to get a list of all the parts of an object without needing the UploadID associated with the multipart upload that ListParts requires. This is useful when you may want to know the parts associated with an object after it has already been uploaded. Any chance this could be reopened to implement this API?

For now we have no cycles to implement this API, feel free to send a pull request we will happily review it and accept it @jfantinhardesty
