### ISSUE TITLE
Implement object integrity support such as CRC32C, SHA256

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#14885]
**Is your feature request related to a problem? Please describe.**
> Amazon S3 uses checksum values to verify the integrity of data that you upload to or download from Amazon S3. In addition, you can request that another checksum value be calculated for any object that you store in Amazon S3. You can select from one of several checksum algorithms to use when uploading or copying your data. Amazon S3 uses this algorithm to compute an additional checksum value and store it as part of the object metadata.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

**Describe the solution you'd like**
Implement support for https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

**Describe alternatives you've considered**
There are no other alternatives

**Additional context**
Just S3 compliance

**Comment by klauspost** [comment]
Multipart is the tricky one, but it seems like it is  checksum of checksums: [source](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html)

> Checksums with multipart upload operations

> When you upload an object to Amazon S3, you can specify a checksum algorithm for Amazon S3 to use. Amazon S3 uses MD5 by default to verify data integrity; however, you can specify an additional checksum algorithm to use. When using MD5, Amazon S3 calculates the checksum of the entire multipart object after the upload is complete. This checksum is not a checksum of the entire object, but rather a checksum of the checksums for each individual part.

> When you instruct Amazon S3 to use additional checksums, Amazon S3 calculates the checksum value for each part and stores the values. You can use the API or SDK to retrieve the checksum value for individual parts by using GetObject or HeadObject


CRC32C is Castagnoli.

Trailing Checksum is very useful, but the docs are too sparse to give any indication of what it does, so we will have to see what S3 is doing.

**Comment by harshavardhana** [comment]
It's nothing surprising @klauspost it's just like the checksum we do today.

It adds trailer header at the end of a PUT to save the checksum and this checksum is used again as verification when someone is doing a GET object back.

**Comment by daghendrik** [comment]
Support for the new additional checksum algorithms in [PutObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) would be great. 

For me, it's not really clear what format they expect the values of the (CRC) checksums to be sent as (Base64 of what? Decimal? Hex lowercase? Hex uppercase?) which is why I've opened an AWS support case. I'll report back my findings.

**Comment by klauspost** [comment]
@daghendrik MD5 and SHA256 are both hex, so I would guess that to be the case. But let me know what you hear back.

**Comment by daghendrik** [comment]
My bad. I did a simple base64 encode of the hexString using btoa(hex) in JavaScript (treating it as a regular string).

Updating my code, taking into account that I'm dealing with a hex string and not a regular string fixed it:

`btoa(hexString.match(/\w{2}/g).map(a => {return String.fromCharCode(parseInt(a, 16));} ).join(""))`

CRC32 on AWS S3 are indeed Base64 of hex strings. My mistake.

**Comment by klauspost** [comment]
Base64 of hex? Do you have an example?

**Comment by daghendrik** [comment]
If you upload a file to S3 via the AWS Management console (like demonstrated [here:](https://www.youtube.com/watch?v=Xt6Lv4LrBQE&t=2s) you'll get a Base64 string in the "Additional checksums" field in the AWS console.

You can take the same file and run a CRC32 checksum on it ([online](https://emn178.github.io/online-tools/crc32_checksum.html))  and then take the output (which is hex representation of the checksum) and do a Base64 hash of that hex ([online](https://emn178.github.io/online-tools/base64_encode.html)). If you encode the hash as a regular string, it won't match what AWS outputs, but if you encode it taking account that the input is Hex, the output matches

![image](https://user-images.githubusercontent.com/1830026/176886980-2d87fd04-e6b7-4c3f-b8d4-113ce2eabf35.png)

![image](https://user-images.githubusercontent.com/1830026/176886934-30a22789-23bc-42f3-a9a7-e82ee20ab7ac.png)

My mistake was that I encoded the hex value using JavaScript's "btoa()", not taking into account that it takes a JavaScript string as parameter. Hope this made sense. Let me know if you want me to clarify something.

**Comment by klauspost** [comment]
What you are showing is straight up base64 of the raw 4 bytes. I will do my own investigation to check what S3 expects/works with.

**Comment by tylerchr** [comment]
The godocs in the AWS Go SDK for [`s3.PutObjectInput`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#PutObjectInput) clarify that the `Checksum{CRC32,CRC32C,SHA1,SHA256}` header

> specifies the base64-encoded (n)-bit {CRC32,CRC32C,SHA1,SHA256} digest of the object.

In practice I found that they map to the `x-amz-checksum-{crc32,crc32c,sha1,sha256}` headers, and confirmed that they must be the base64-encoded digest of the object contents. I also found that you may only provide one of these checksum fields, and the request fails if multiple are provided (this was not obvious from the docs linked by OP). Note too that if a checksum is provided when an object is uploaded, it is also present on `GetObject` and `HeadObject` responses for that object.

+1 for this request. I attempted to test MinIO as an S3 replacement for something today and got all the way through setting it up before I discovered the incompatibility. Completely understandable—the checksums are kind of new—but unfortunately this disqualifies MinIO for that particular use case.

**Comment by klauspost** [comment]
I can take a stab at this. Thanks for the additional info @tylerchr

**Comment by harshavardhana** [comment]
@klauspost we can close this issue?

**Comment by klauspost** [comment]
Trailing checksums are still missing. I am however in the testing phase currently.

**Comment by harshavardhana** [comment]
Is this done @klauspost we can close this?

**Comment by klauspost** [comment]
Sure. No need to keep this open.
