### ISSUE TITLE
Minio Dex Integration problems

### ISSUE THREAD

**Issue by manigarg31** [minio/minio#14886]
Getting following error on minio while integrating with dex:

**Expected 'code id_token' response type - got [code id_token], login not allowed**

Response types supported on dex:

 **"grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "response_types_supported": [
    "code",
    "id_token"
  ],**

ENV variables added on minio:

MINIO_IDENTITY_OPENID_ENABLE: "on"
MINIO_IDENTITY_OPENID_CONFIG_URL: "https://***/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID: "***"
MINIO_IDENTITY_OPENID_CLIENT_SECRET: "****"
MINIO_IDENTITY_OPENID_ROLE_POLICY: "readwrite"

Can someone please help me with this?

**Comment by harshavardhana** [comment]
Please upgrade your MinIO
