### ISSUE TITLE
panic: runtime error: index out of range [7] with length 4

### ISSUE THREAD

**Issue by Marshy891** [minio/minio#14895]
## Current Behavior
MinIO crashes with the following output 

`panic: runtime error: index out of range [7] with length 4`
`goroutine 2329493 [running]:`
`github.com/minio/minio/cmd.shuffleDisksAndPartsMetadataByIndex({_, _, _}, {_, _, _}, {{0xc03d03d805, 0x7}, {0xc03d03d80d, 0x68}, ...})`
`github.com/minio/minio/cmd/erasure-metadata-utils.go:196 +0x4fc`
`github.com/minio/minio/cmd.erasureObjects.getObjectWithFileInfo({{}, 0x4, 0x2, 0x0, 0x0, 0xc000814a80, 0xc000814a98,0xc000814ab0, 0xc000814a20, 0xc000814a38, ...}, ...)`
`github.com/minio/minio/cmd/erasure-object.go:287 +0xca`
`github.com/minio/minio/cmd.erasureObjects.GetObjectNInfo.func5()`
`github.com/minio/minio/cmd/erasure-object.go:272 +0x17b`
`created by github.com/minio/minio/cmd.erasureObjects.GetObjectNInfo`
`github.com/minio/minio/cmd/erasure-object.go:271 +0x13e5`
`minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT`
`minio.service: Failed with result 'exit-code'.`

## Steps to Reproduce (for bugs)
mcli mirror minioserver1\bucket minioserver2\bucket

## Your Environment
minio version RELEASE.2022-05-08T23-50-31Z
mcli version RELEASE.2022-05-09T04-08-26Z
Ubuntu 20.04.4 LTS

**Comment by klauspost** [comment]
@Marshy891 Have you made any changes to the backend files? Backed up, restored, moved them or similar?

**Comment by harshavardhana** [comment]
> `panic: runtime error: index out of range [7] with length 4`
> `goroutine 2329493 [running]:`
> `github.com/minio/minio/cmd.shuffleDisksAndPartsMetadataByIndex({_, _, _}, {_, _, _}, {{0xc03d03d805, 0x7}, {0xc03d03d80d, 0x68}, ...})`

This looks like a forced replacement of some kind @klauspost moving to an 8 disk setup from a 4 disk setup.

**Comment by harshavardhana** [comment]
> mcli mirror minioserver1\bucket minioserver2\bucket

This is hardly how this happened, it looks like you moved data in the backend drives here.
