### ISSUE TITLE
exec mc replicate status get error: Replication status not available

### ISSUE THREAD

**Issue by ace1573** [minio/minio#14916]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
It should shows replication status of current bucket.

## Current Behavior
It shows: Replication status not available.

## Steps to Reproduce (for bugs)

1. mc replicate add minio2/test --remote-bucket 'arn:minio:replication::0e08bd71-82d3-4268-ad2c-403747ae2666:test' --replicate "delete,delete-marker,existing-objects"
2. mc replicate ls minio2/test: 
ID                   | Priority | Status   | Prefix                    | Tags                      | DestBucket           | StorageClass
c9v1ksuls46i124kcm50 | 0        | Enabled  |                           |                           | arn:minio:replica... |
3. mc replicate status minio2/test:
Replication status not available.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-10-06T23-36-31Z
* Server setup and configuration: setup withs docker-compose
* Operating System and version (`uname -a`): Linux 3.10.0-957.el7.x86_64

**Comment by harshavardhana** [comment]
Please upgrade your setup @ace1573
