### ISSUE TITLE
Loki started giving error with latest version of minio

### ISSUE THREAD

**Issue by manigarg31** [minio/minio#14914]
On upgrading minio to version [RELEASE.2022-05-08T23-50-31Z] Loki (version - 2.5.0 [latest])started giving following error:

<img width="958" alt="Screenshot 2022-05-11 at 12 24 48 PM" src="https://user-images.githubusercontent.com/48922749/168220247-f5221c5f-f961-4d5f-ae34-6b68e2bb6e86.png">

It was working fine with minio version: RELEASE.2022-03-24T00-43-44Z

Loki config has minio url as: s3://minio-hostname.:9000, also tried with http://minio-hostname.:9000

**Comment by harshavardhana** [comment]
Still no information, no setup details nothing - are we to assume things on our end? - 

your hostname is invalid here since it ends with a `.` at the end @manigarg31 please fix that.

**Comment by manigarg31** [comment]
> Still no information, no setup details nothing - are we to assume things on our end? -
> 
> your hostname is invalid here since it ends with a `.` at the end @manigarg31 please fix that.

The . at the end is to use minio as hostname and not as region.

Setup:
Minio running as 4 node cluster on K8s. It is managed using helm. Helm version using - 4.0.2
Loki is running in distributed mode on k8s. It is also managed via helm

**Comment by harshavardhana** [comment]
> > Still no information, no setup details nothing - are we to assume things on our end? -
> > your hostname is invalid here since it ends with a `.` at the end @manigarg31 please fix that.
> 
> The . at the end is to use minio as hostname and not as region.
>

Correct that hostname is wrong.  Valid hostnames do not end with `.` at the end.  `.` is a domain separator. Please fix your host DNS entry keep it RFC compatible.

> Setup: Minio running as 4 node cluster on K8s. It is managed using helm. Helm version using - 4.0.2 Loki is running in distributed mode on k8s. It is also managed via helm

**Comment by thoro** [comment]
@harshavardhana Please fix this bug. It's absolutely fine for a hostname (domain) to contain a dot in the end!

https://serverfault.com/questions/803033/should-i-append-a-dot-at-the-end-of-my-dns-urls#:~:text=The%20dot%20at%20the%20end,general%20public%20usually%20doesn't.

http://www.dns-sd.org/trailingdotsindomainnames.html

It is used to prevent search-path lookups. I.e. a fully qualified domain!

**Comment by harshavardhana** [comment]
@Thoro no it is not. We are not going to fix it.. those are for DNS server configuration. These are not valid hostnames.

**Comment by thoro** [comment]
It's about having a fully qualified domain name vs. having it not. It prevents the search path lookups and is absolutely valid.

It's clearly stated in the RFC that it's valid.

Please refer to the "correct" wikipedia article about domain names, instead of hostnames: https://en.wikipedia.org/wiki/Domain_name

which clearly states:

> The empty label is reserved for the root node and when fully qualified is expressed as the empty label terminated by a [dot](https://en.wikipedia.org/wiki/Full_stop).

Edit1:

Regardless of this, it's a valid use case, and a bug in the pkg/net package. It's especially often used in combination with kubernetes.

Edit2:

Additionally: https://man7.org/linux/man-pages/man7/hostname.7.html

> If the input name ends with a trailing dot, the trailing dot is
       removed, and the remaining name is looked up with no further
       processing.
