### ISSUE TITLE
Temporary link to the separate file from uploaded archive

### ISSUE THREAD

**Issue by chelmike** [minio/minio#14917]
Hello!

Recently, in minio was implemented the ability to download files from uploaded archive separately (https://blog.min.io/small-file-archives/). And now is it possible to get a temporary link to a file from an archive, using method **getPresignedObjectUrl**?
I tried to use it by analogy (as I successfully use **putObject**, **listObjects**, **getObject**), adding extra headers block in builder of arguments, including special header - "x-minio-extract" = "true", and URL to the file inside the archive was successfully generated. But minio answered on this URL so:
_<Message>
There were headers present in the request which were not signed
</Message>_
Is such a functionality not implemented yet?

Regards, Michael

**Comment by harshavardhana** [comment]
You should generate such a link yourself @chelmike the protocol is presented by AWS S3 write code to generate such a presigned URL - set relevant HTTP headers and you will have the same functionality.
