### ISSUE TITLE
MinIO cluster - SlowDown', error code: 503

### ISSUE THREAD

**Issue by hegedussz** [minio/minio#14910]
We have a Minio Cluster (4 node - VM )

We made a benchmark test. (Download a file. Example: wget. curl) 
Info: Simultaneous connections (150 pcs)

**Problem:** Minio Cluster down,  A timeout exceeded while waiting to proceed with the request, please reduce your request rate. Code: SlowDown', error code: 503

MinIO Server version: 2022-04-16T04:26:02Z

Performance test: 
```
mcli support perf asd/
        THROUGHPUT      IOPS      
PUT     403 MiB/s       6 objs/s 
GET     1.3 GiB/s       21 objs/s
```
It is a normal operation?

**Comment by harshavardhana** [comment]
If you run `mc support perf` we block S3 connections until the benchmark is complete, so this is normal.

**Comment by harshavardhana** [comment]
> **Problem:** Minio Cluster down, A timeout exceeded while waiting to proceed with the request, please reduce your request rate. Code: SlowDown', error code: 503

You do not have enough IOPs left of the system - we can't guide you on what kind of hardware you should get for what you want. Please ask around in https://slack.min.io

You want production help come over to https://min.io/pricing
