### ISSUE TITLE
new api listObjectByTags to list objects by specific tag(s)

### ISSUE THREAD

**Issue by DeathKing** [minio/minio#14922]
**Is your feature request related to a problem? Please describe.**
What I currently do is enumerating all objects then quering and selecting, which will perform a large amount of useless requests.

I would like to know:

1. Is this correct to use minio tag feature for this purpose? Should I use metadata instead?
2. If there is any chance that implementing this API in futher version.
3. If there exists solution better than enumerate-query-and-select in such a scenario.

**Describe the solution you'd like**

Implementing API like `listObjectsByTag` whose API is much like `listObjects` but supports `tags` options in `listOps` parameter, such that this API will return objects only whose tag is superclass of `tag`.

for simplicity, the `tag` option SHOULD NOT be fancy like mongodb document query like `{tag: { age: {$gt: 18}}}`, but a simple key-value pair instead so that the engine only perform simple string comparasion in each tag value field.

**Describe alternatives you've considered**

API `listObjectsV2WithTags` which like `listObjectsV2WithMetadata` but returns object with tags instead may be an alternative solution. Tag filtering could be done locally in this case. (but also result in unnecessary data transmition).

**Additional context**

**Comment by harshavardhana** [comment]
This is not an S3 API @DeathKing - extensions to S3 API are carefully implemented. For now we will not be implementing this.
