### ISSUE TITLE
XFS quota inside minio buckets

### ISSUE THREAD

**Issue by eddienko** [minio/minio#14921]
**Is your feature request related to a problem? Please describe.**
I have the following use case. I have a directory called /storage/users/ that is made available using standalone minio. Inside this directory there is a bucket for each user. The underlying filesystem is XFS and each user directory is associated to a different project with a quota set by the OS. I.e.

```
$ mc ls myserver
username1/
username2/
...etc..
```

This does not work when copying files to each user bucket because cross device issues (i.e. minio copies files to /storage/users/.minio.sys/tmp/filename and then tries to rename it to each user directory and this will fail because of the XFS quota).

**Describe the solution you'd like**
I would like either 1) this to work or 2) find an alternative solution or better setup

**Describe alternatives you've considered**
The current alternative I have considered is to change the code to use copy/remove instead of rename: https://github.com/eddienko/minio/commit/20a1b53d91a003d0446c38f4ad105d124babb692

I understand the above may not be desirable in the general case. Maybe there could be an environment variable to allow for this? Otherwise I would welcome comments if this changes would have a real impact (i.e. am I breaking something somewhere else).

**Comment by harshavardhana** [comment]
This is a feature of DirectPV - use that https://github.com/minio/directpv
