### ISSUE TITLE
Cannot create more than one remote bucket with the same source

### ISSUE THREAD

**Issue by giusepperagusa** [minio/minio#14926]
When I try to create more than one remote bucket it fails with a strange error citing a "label".

## Expected Behavior
More than one remote creation succeeds.

## Current Behavior
First remote creation succeeds.
Second remote creation fails with error:

mcli: <ERROR> Unable to configure remote target. The remote target with this label already exists.

## Steps to Reproduce (for bugs)

mcli mb local/replicatest1
mcli version enable local/replicatest1

mcli mb remote/replicatest1
mcli version enable remote/replicatest1
mcli mb remote/replicatest2
mcli version enable remote/replicatest2

mcli admin bucket remote add local/replicatest1 https://Administrators:supersecret@s3-remote.example.com/replicatest1 --service "replication"
mcli admin bucket remote ls local/

mcli admin bucket remote add local/replicatest1 https://Administrators:supersecret@s3-remote.example.com/replicatest2 --service "replication"

## Context
I am trying to set up more than one remote involving always the same local bucket and some other remote buckets; I will then setup replication rules using these remote definitions.

## Regression
No (never succeeded)

## Your Environment
Local env:
CentOS Linux release 8.3.2011 (kernel 4.18.0-240.22.1.el8_3.x86_64)
minio version RELEASE.2021-04-18T19-26-29Z (4 local XFS filesystems on different disks)
mcli version RELEASE.2022-05-09T04-08-26Z

Remote env:
Kubernetes 1.18.3
MinIO Operator installed with Helm chart 4.0.11 - server container version minio/minio:RELEASE.2021-04-06T23-11-00Z (4 PVCs on NFS-based CSI storage)

**Comment by harshavardhana** [comment]
> mcli admin bucket remote add local/replicatest1 https://Administrators:supersecret@s3-remote.example.com/replicatest1 --service "replication" mcli admin bucket remote ls local/
> 
> mcli admin bucket remote add local/replicatest1 https://Administrators:supersecret@s3-remote.example.com/replicatest2 --service "replication"

> minio version RELEASE.2021-04-18T19-26-29Z (4 local XFS filesystems on different disks)

Please upgrade we support Multi-destination buckets in later releases.
