### ISSUE TITLE
can't get principal from audit logs

### ISSUE THREAD

**Issue by jpchev** [minio/minio#14925]
hi there, we want to store all audit logs in order to keep track of what users do in our installation.
We use min.io with an external identity provider and we see data as the following in our audit logs

      "userIdentity": {
        "principalId": "_g18SBgf2drwReqUmRBRgDhrPK1DYLKxp9ucvR38-CM"
      },

so how can we get the user (in the IDP) corresponding to this principalId?

Is there an API taking this principalId and returning the user associated?

Thanks

**Comment by harshavardhana** [comment]
> "userIdentity": {
>     "principalId": "_g18SBgf2drwReqUmRBRgDhrPK1DYLKxp9ucvR38-CM"
>   },

Well, this is the unique ID presented by your IDP, if you want to do reverse lookup you should write a tool to use this ID and ask your IDP to give you the username. 

This is part of the Bucket Notification API - however, if you need audit logging you should be using Audit logging not bucket notification that provides a much more lower-level information. 

https://github.com/minio/minio/tree/master/docs/logging#audit-http-target

**Comment by jpchev** [comment]
ok, thanks a lot
