### ISSUE TITLE
Policy claim missing from the JWT token, credentials will not be generated

### ISSUE THREAD

**Issue by jaspercloud** [minio/minio#14939]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Login with Keycloak

## Current Behavior
Policy claim missing from the JWT token

## Steps to Reproduce (for bugs)
JWT content
```json
{
    "exp": 1652858115,
    "iat": 1652857815,
    "jti": "4c36f035-b971-4273-8ae1-8f12fe4e16b7",
    "iss": "http://192.168.30.128:3080/auth/realms/test",
    "sub": "002c6d7a-3d95-4deb-9c48-70c9efa2f7f5",
    "typ": "Bearer",
    "azp": "test",
    "session_state": "f5edc908-0092-4379-86b4-0bdf47007f09",
    "acr": "1",
    "realm_access": {
        "roles": ["test"]
    },
    "scope": "openid profile email",
    "sid": "f5edc908-0092-4379-86b4-0bdf47007f09",
    "email_verified": false,
    "preferred_username": "test"
}
```

## Context
Trying to login with Keycloak-SSO. how to set policy in jwt.
![QQ拼音截图20220518152056](https://user-images.githubusercontent.com/3040720/168980777-f48d0a42-55e0-446a-ae27-ba0e6a40cd76.png)

**Comment by jaspercloud** [comment]
how to set    "policy": "consoleAdmin"

**Comment by harshavardhana** [comment]
@jaspercloud there are no setup details provided closing
