### ISSUE TITLE
Service Account listing does not error out on non-existing user

### ISSUE THREAD

**Issue by sinhaashish** [minio/minio#14937]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Using `mc` to list service account for a user.
For valid user `alpha`
```
$ mc admin user svcacct list myminio alpha
svcalpha            
```
For non existing user , `alpha1` in this case , there is no error . 
```
$ mc admin user svcacct list myminio alpha1
```

User present in system 
```
ashish@ashish:~/code/go/src/github/minio/mc$ ./mc admin user list myminio
enabled    alpha                 consoleAdmin        
enabled    beta                  consoleAdmin
```

## Expected Behavior

mc service account listing for non existing user must error out as shown below
```
ashish@ashish:~/code/go/src/github/minio/mc$ ./mc admin user svcacct list myminio alpha1
mc: <ERROR> Unable to list service accounts. The specified user does not exist. (Specified user does not exist).
```

## Current Behavior

No output put on console for service account list of an non existing user
```
/mc admin user svcacct list myminio alpha1
```

## Steps to Reproduce (for bugs)

1. Create a user and service account in MinIO
2. List the service account for that user. Listing is successful
3. List the service account for any arbitarry user not present in the system. Listing shows nothing . It must error out

## Regression
 No

## Your Environment

* Version used (`minio --version`): master
* Server setup and configuration:
* Operating System and version (`uname -a`):  
Linux ashish 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This should be fixed by #14977
