### ISSUE TITLE
bucket content not always updated in stats

### ISSUE THREAD

**Issue by MarcusEbert** [minio/minio#14933]
We have a single ZFS server with 100TB local storage. Access to it is provided via different protocols, one of them via minio. 
Files are stored in a way that each file is fully readable by any file access tool (and therefore other protocols).
server is started via:
`MINIO_COMPRESS="off" MINIO_ROOT_USER=$USER MINIO_ROOT_PASSWORD=$PASSWORD MINIO_PROMETHEUS_AUTH_TYPE="public" ./minio server --console-address ":8080" /data/ & `

There are different buckets on it, like `userdata` which is in `/data/userdata/` on the local filesystem, to which files are transferred via minio and also via other tools.
Usage statistics is retrieved via http using the `minio_bucket_usage_object_total` and ` minio_bucket_usage_total_bytes`  properties for each bucket through `/minio/v2/metrics/cluster`.

## Expected Behavior
`minio_bucket_usage_object_total` and `  minio_bucket_usage_total_bytes` should be updated periodically to reflect any new file no matter if transferred via minio or other tools. 

## Current Behavior
`minio_bucket_usage_object_total` and  `minio_bucket_usage_total_bytes` are only updated when files are transferred via minio. Files transferred through other protocols/tools are not accounted for in those statistics. Files transferred to the storage with other tools however can accessed for read via minio with no problem, so minio is aware of those files somehow already. 

## Possible Solution
When deleting the bucket information about stored files in`/data/.minio.sys/`, then the whole system is scanned and all current files are accounted for correctly. Whatever minio is doing in that case, it would be good it could be done periodically to account for all files in the stats.

## Steps to Reproduce (for bugs)

1. set up a standalone minio server with the above command line
2. copy 10G of files via minio to it
3. copy another 10G of files via another protocol or local cp to it
4. query `/minio/v2/metrics/cluster` and compare the output for bucket size and usage objects with what is really on disk

## Context
The server needs to support different methods of file access for r/w and we need to query the usage stats over the network so client tools are able to decided if there is enough space to copy more data over. 

## Your Environment
* Version used (`minio --version`): 2022-05-08T23:50:31Z (also present on previous versions)
* Server setup and configuration:  zfs (raidz3) for disk management
* Operating System and version (`uname -a`): CentOS 7.9

**Comment by harshavardhana** [comment]
> There are different buckets on it, like `userdata` which is in `/data/userdata/` on the local filesystem, to which files are transferred via minio and also via other tools.

We do not support that and NAS gateway is going away refer #14331 - this won't be supported sorry.
