### ISSUE TITLE
Ability to set-up disk per bucket (cross-mount support)

### ISSUE THREAD

**Issue by avengerweb** [minio/minio#14934]
**Is your feature request related to a problem? Please describe.**
In company we have several NAS-servers which already redundant, distributed and replicated. They contain a lot of data that is used by existing applications and users (we can't switch to minio in one hop). So, we decided to use minio as NAS **gateway** (support will be ended soon). What we do, is mount each nas (n1, n2, n3) to FS (/var/s3/n1...n3) and point minio to /var/s3. It's works for GET requests, and represented as 3 buckets. Problems starts with uploading data, because minio expects **.minio/tmp** to be on same device to use syscall for moving files from temporary directory. Workaround - we mounted tmp folder into n1 and considered n2 and n3 as a readonly. And it worked this way for a while. Sad part of story, is gateway support will be removed in one month. We started to look on single disk setup; however, it fails to start because of "cross-mount" check (_Cross-device mounts detected on path (/data) at following location_). So, it is not work at all.

**Describe the solution you'd like**
* Flag to disable "cross-device" check in single disk mode
* Have ability to configure tmp directory location for each bucket 
* or just having subdirectory for tmp files (.minio/tmp/BUCKET_NAME/...), so admins could mount whatever they want

**Describe alternatives you've considered**
Only way left is having instance for each NAS, but it make user experience not very convenient.

**Comment by avengerweb** [comment]
I can work on PR for this change if you approve idea.

**Comment by harshavardhana** [comment]
@avengerweb no we are not going to support it - NAS gateway is frozen no new features will be taken refer #14331

**Comment by avengerweb** [comment]
> @avengerweb no we are not going to support it - NAS gateway is frozen no new features will be taken refer #14331 

It's not about nas gateway. I'm talking about single node set-up when I have 3 devices (3 disks) each of this disk represent whole bucket.

**Comment by harshavardhana** [comment]
> It's not about nas gateway. I'm talking about single node set-up when I have 3 devices (3 disks) each of this disk represent whole bucket.

They are the same - single disk setup == nas gateway

**Comment by avengerweb** [comment]
> Newer MinIO NAS/Single drive setups will move to single data and 0 parity mode (that will re-purpose the erasure-coded backend used for distributed setups but with 0 parity). This would allow for distributed setup features to be available for single drive deployments as well such as

Quoting you from #14331. So, that mean you actually plan to support single-disk setups in new versions. What I'm asking is about support of multiple "devices" (either mounted nas/share or just hardware mounted drive) all restrictions of using them right now seems synthetic, so it is not hard to implement it. However, looks like you don't want to see such features in your code?

I know that you drive users to use minio features distributed, replication, erasure, etc. That is cool features but only when you have previously s3 or you are building from scratch. If we are talking about larger companies, for example company that I working in, they store data for 50+ years already, and like I said initially we just can't migrate in one step. We need to put it over our existing infrastructure (distributed, replicated, redundant) then rewrite all of our software that use storage and only after we could try to migrate on offered by minio set-up. It is even in your features overview page:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/2055581/169119199-8be968f3-536e-44dc-b356-ec66c3594d3a.png">

**Comment by klauspost** [comment]
@avengerweb You are welcome to write `sales@min.io` with your commercial case.
