### ISSUE TITLE
Reading and writing efficiency is too low

### ISSUE THREAD

**Issue by lecssmi** [minio/minio#14936]
## Expected Behavior
   Distributed cluster should provide a higher read and write speed.

## Current Behavior
  The read and write speed is even slower than a single node.

## Steps to Reproduce (for bugs)

1.  Prepare 4 machines, each with a raid disk.
2.  Install minio on each node  enabling ec mode.
3.  Use speedtest or other command to read/write big object , and watch iostat on each node.

## Your Environment
* Version used :  RELEASE.2022-01-07T06-01-38Z
* Operating System and version (`uname -a`):  Linux localhost.localdomain 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*  Set up and Configuration:  ./minio server --address :9909 --console-address :19909 http://192.168.154.129/data01/minio  http://192.168.154.130/data01/minio http://192.168.154.131/data01/minio http://192.168.154.132/data01/minio

**Comment by harshavardhana** [comment]
> * Version used :  RELEASE.2022-01-07T06-01-38Z

please upgrade, also for performance debugging please get a subscription and evaluate the architecture with us https://min.io/pricing

**Comment by lecssmi** [comment]
> 

This version is relatively new, so why upgrade?

**Comment by harshavardhana** [comment]
> > 
> 
> This version is relatively new, so why upgrade?

Read https://min.io/pricing - all community users upgrade.

**Comment by klauspost** [comment]
> Distributed cluster should provide a higher read and write speed.

@lecssmi no. High availability comes with reads/writes to multiple disks per object, that is physically unavoidable. With bigger installs speed will scale. With 4 disks you don't get any scaling benefit. With +16 disks you will begin to see benefits.

Write `sales@min.io` if you want your a deeper performance analysis of your system.
