### ISSUE TITLE
Cannot add replication rule on newly-created remote bucket after local server upgrade

### ISSUE THREAD

**Issue by giusepperagusa** [minio/minio#14931]
After upgrading to latest MinIO server locally, when I try to create a replication rule based on a newly created remote bucket, it fails with a strange "RoleArn invalid for AWS replication configuration" error.
A replication rule can be successfully created if based on a pre-existing remote bucket created with the previous version of MinIO server (RELEASE.2021-04-18T19-26-29Z) - the ARN returned for the new remote bucket is markedly different in the middle "UUID" part.

## Expected Behavior
Replication rule creation succeeds based both on pre-existing and newly-created remote buckets.

## Current Behavior
First replication rule creation succeeds, based on pre-existing remote bucket:

```
[user@host ~]$ mcli replicate add local/replicatest1 --arn 'arn:minio:replication::dc86070c11425bff35a400611a16dac36aa77f986c8e77dbd531bd07e485d524:replicatest1' --remote-bucket replicatest1
Replication configuration rule applied to local/replicatest1 successfully.

```
New remote bucket creation succeeds:

```
[user@host ~]$ mcli admin bucket remote add local/replicatest1 https://Administrators:supersecret@s3-remote.example.com/replicat
est2 --service "replication"
Remote ARN = `arn:minio:replication::289e330e-4312-4b9a-a7a8-e51173392ec5:replicatest2`.

```
Second replication rule creation fails with error:

```
[user@host~]$ mcli replicate add local/replicatest1 --arn 'arn:minio:replication::289e330e-4312-4b9a-a7a8-e51173392ec5:replicatest2' --remote-bucket replicatest2
mcli: <ERROR> Could not add replication rule. RoleArn invalid for AWS replication configuration: arn:minio:replication::289e330e-4312-4b9a-a7a8-e51173392ec5:replicatest2.

```
ARNs for pre-existing and newly-created remote buckets are markedly different:

```
[user@host~]$ mcli admin bucket remote ls local/
Remote URL                                Source              ->Target               ARN                                                          SYNC PROXY
https://s3-remote.example.com     replicatest1        ->replicatest1         arn:minio:replication::dc86070c11425bff35a400611a16dac36aa77f986c8e77dbd531bd07e485d524:replicatest1                        proxy
https://s3-remote.example.com     replicatest1        ->replicatest2         arn:minio:replication::289e330e-4312-4b9a-a7a8-e51173392ec5:replicatest2                                                    proxy

```

## Steps to Reproduce (for bugs)
See example commands above for details.
1. Create remote bucket
2. Upgrade MinIO server locally
3. Add new remote bucket
4. Create replication rules based on pre-exisitng and newly-created remote buckets

## Context
I am trying to set up more than one replication involving always the same local bucket and some other remote buckets; I have updated the local MinIO server and I am working both with pre-existing and newly-created remote buckets.

## Regression
No (just upgraded now)

## Your Environment
Local env:
CentOS Linux release 8.3.2011 (kernel 4.18.0-240.22.1.el8_3.x86_64)
minio version RELEASE.2022-05-08T23-50-31Z (4 local XFS filesystems on different disks)
mcli version RELEASE.2022-05-09T04-08-26Z

Remote env:
Kubernetes 1.18.3
MinIO Operator installed with Helm chart 4.0.11 - server container version minio/minio:RELEASE.2021-04-06T23-11-00Z (4 PVCs on NFS-based CSI storage)

**Comment by harshavardhana** [comment]
Pre existing configuration cannot be disturbed, you need to create new settings in a fresh manner

**Comment by giusepperagusa** [comment]
> Pre existing configuration cannot be disturbed, you need to create new settings in a fresh manner

But the problem is exactly that the pre-existing remote bucket works (replication rule can be successfully added on top) while the newly-created one doesn't (replication rule adding on top fails).

I do not understand which "new settings" you are referring to and up to what extent I should re-create them "in a fresh manner".

I suggest that a note in the docs could be very handy since upgrades only once a year could be quite common for a software that works so well :-)
