### ISSUE TITLE
Legacy objects cannot be decrypted using KES after minio upgrade

### ISSUE THREAD

**Issue by bosi95** [minio/minio#14946]
Hi, 

I used minio version RELEASE.2021-04-22T15-44-28Z and now upgraded to version RELEASE.2022-03-26T06-49-28Z.
The issue is that I cannot access the "legacy" objects (i.e.: created with the older minio version, before the upgrade) after the upgrade takes place. 

## Expected Behavior
I want to access the "legacy" objects after the upgrade.

## Current Behavior
My setup involves a Hashicorp vault and now I configured KES version v0.19.2 and the vault according to [https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore](KES). 

Creating/pushing new objects to the minio servers works fine but when I try to list the objects created before the upgrade, then I receive the following error (mc **ls/stat** <legacy bucket>):
**decryption failed: ciphertext is not authentic**

From KES I get HTTP error 400.

Are the two minio versions compatible or the "upgrade gap" is to big ?
My assumption was that if I upgrade minio and insert a KES between the vault and minio then the behavior would be the same. Neither minio nor the vault would notice that KES is there.

## Steps to Reproduce (for bugs)
1. Create/push on object the the minio servers with version RELEASE.2021-04-22T15-44-28Z 
2. Upgrade minio version to RELEASE.2022-03-26T06-49-28Z
3. Setup KES v0.19.2
4. Try to list the legacy objects via mc ls/stat

Best regards.
Balint Ujvari

**Comment by harshavardhana** [comment]
Yes that is correct you need to migrate the content to new KES setup by using a new fresh setup. There is no auto migration allowed.
