### ISSUE TITLE
Minio browser console not working: Error: Unable to migrate IAM users and policies to new format

### ISSUE THREAD

**Issue by MattManjosKodiak** [minio/minio#14947]
After upgrading an old cluster from 2021-01-05T05-22-38Z to 2022-05-08T23-50-31Z, we are unable to get any meaningful access to the minio console in a web browser. All CLI and S3-based requests go through fine using the credentials from `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`, but the web console (after logging in successfully with those same credentials) shows no buckets, admin options, etc. In the minio server logs, we're getting:

```
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]: API: SYSTEM()
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]: Time: 14:18:06 UTC 05/19/2022
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]: DeploymentID: 9128de69-9fc5-4bb8-83a1-67b787d3afef
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]: Error: expected policy (consoleAdmin) missing from the JWT claim , rejecting the request (*errors.errorString)
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]:        5: cmd/iam.go:1628:cmd.(*IAMSys).IsAllowedSTS()
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]:        4: cmd/iam.go:1715:cmd.(*IAMSys).IsAllowed()
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]:        3: cmd/admin-handlers-users.go:1108:cmd.adminAPIHandlers.AccountInfoHandler.func1()
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]:        2: cmd/admin-handlers-users.go:1183:cmd.adminAPIHandlers.AccountInfoHandler()
May 19 07:18:06 tb1-srv1-03-minio1-1 minio[3060973]:        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

## Expected Behavior
In our testing environment, I was able to upgrade between these releases and see full functionality on the minio console web browser interface. On this cluster, I see no buckets or admin options (screenshot to follow in comments)

## Current Behavior
None of the browser console features work

## Context
We still appear to be able to access all of our data, using `mc` and S3 requests, but the browser console is unavailable

## Regression
No/Unknown

## Your Environment
* Version used (`minio --version`): 2022-05-08T23-50-31Z
* Server setup and configuration: 12 servers, 6 disks each `"http://10.10.4.{30...41}:9000/mnt/data{0...5}/minio"`
* Operating System and version (`uname -a`): `Ubuntu 18.04.4 LTS 4.15.0-99-generic #100-Ubuntu SMP`

The only environment variables are:
```
MINIO_ROOT_USER=***
MINIO_ROOT_PASSWORD=***

MINIO_STORAGE_CLASS_STANDARD="EC:4"
MINIO_STORAGE_CLASS_RRS="EC:4"

MINIO_PROMETHEUS_AUTH_TYPE="public"
```

```
mcli admin config get myminio api 
requests_max=0
requests_deadline=10s
cluster_deadline=10s
cors_allow_origin=*
remote_transport_deadline=2h
list_quorum=optimal
replication_workers=250
replication_failed_workers=8
transition_workers=100
stale_uploads_cleanup_interval=6h
stale_uploads_expiry=24h
delete_cleanup_interval=5m
disable_odirect=off
gzip_objects=off
gzip_objects=off
```

```
mcli admin config get myminio identity_openid
config_url=
client_id=
claim_prefix=
claim_name=policy
scopes=
enable=
display_name=
client_secret=
claim_userinfo=
role_policy=
redirect_uri=
redirect_uri_dynamic=off
redirect_uri_dynamic=off
```

```
mcli admin config get myminio identity_ldap
server_addr=
group_search_filter=
group_search_base_dn=
tls_skip_verify=off
server_insecure=off
server_starttls=off
user_dn_search_base_dn=
user_dn_search_filter=
lookup_bind_dn=
lookup_bind_password=
lookup_bind_password=
lookup_bind_password=
lookup_bind_password=
lookup_bind_password=
lookup_bind_password=
```

**Comment by MattManjosKodiak** [comment]
Here's a screenshot of the browser experience when logged in with credentials from `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`:

![image](https://user-images.githubusercontent.com/93544002/169337003-4d5b54b2-f614-46ec-8879-f8aa78b54ece.png)

**Comment by MattManjosKodiak** [comment]
Trying to list policies from the cluster appears to be busted as well. This command sits forever with no local output and no console logs generated on the servers:

```mcli admin policy list --debug myminio```

It also does not generate any events when looking at `admin trace` for what it's worth

My mcli version is `RELEASE.2022-05-09T04-08-26Z`

**Comment by MattManjosKodiak** [comment]
Oh, and this experience happens with `Firefox 100.0.1 (64-bit)` as well as `Chrome Version 101.0.4951.64 (Official Build) (64-bit)`, both on Linux, using fresh/cache cleared sessions as well as incognito/private mode

**Comment by MattManjosKodiak** [comment]
One possible deviation I just found between our testing and this production environment server is that there seem to be some user accounts created on the production cluster:
```
./config/iam
./config/iam/users
./config/iam/users/minioBktAdm
./config/iam/users/minioBktAdm/identity.json
./config/iam/users/minioBktAdm/identity.json/xl.meta
./config/iam/groups
./config/iam/groups/objAdm
./config/iam/groups/objAdm/members.json
./config/iam/groups/objAdm/members.json/xl.meta
./config/iam/policydb
./config/iam/policydb/groups
./config/iam/policydb/groups/objRW.json
./config/iam/policydb/groups/objRW.json/xl.meta
./config/iam/policydb/groups/bktAdm.json
./config/iam/policydb/groups/bktAdm.json/xl.meta
./config/iam/policies
./config/iam/policies/RO-All
./config/iam/policies/RO-All/policy.json
./config/iam/policies/RO-All/policy.json/xl.meta
```

I'm not sure how to list these, or how to reset IAM so that the ROOT_USER with ROOT_PASSWORD are able to load the console

Logging in with any of these accounts (I have the passwords for them) also results in the same broken browser experience with the same `missing from the JWT claim` console log

**Comment by MattManjosKodiak** [comment]
As expected, 

```mcli admin user list --debug myminio```
```mcli admin group list --debug myminio```

also both hang and never finish, just like `mcli admin policy list` above. It seems like something's messed up with the users and/or policies configuration here.

**Comment by harshavardhana** [comment]
basically your upgrade went kaput, you have to share the server logs for us to see what might be wrong.

**Comment by MattManjosKodiak** [comment]
Here are the logs from node1 - please let me know if logs from the other 11 nodes would be helpful

**Comment by MattManjosKodiak** [comment]
[node1-logs.txt](https://github.com/minio/minio/files/8732212/node1-logs.txt)

**Comment by MattManjosKodiak** [comment]
Seems noteworthy:
```
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:285:cmd.(*IAMSys).Init()
```

**Comment by MattManjosKodiak** [comment]
Here is another upload of the logs from `mcli admin console` format output this time
[logs.txt](https://github.com/minio/minio/files/8732238/logs.txt)

**Comment by MattManjosKodiak** [comment]
Seems like this is the root of our problem here:
```
10.10.4.30  API: SYSTEM()
10.10.4.30  Time: 13:35:51 UTC 05/19/2022
10.10.4.30  DeploymentID: 9128de69-9fc5-4bb8-83a1-67b787d3afef
10.10.4.30  Error: Unable to migrate IAM users and policies to new format: readObjectStart: expect { or n, but found �, error found in #1 byte of ...|�P������|9�|..., bigger context ...|�P������|9Ͳ/�^Q��i�[~�I;^Od�3�C^@�fDiQ���q9B�^Z^F���K|... (*fmt.wrapError)
10.10.4.30         1: cmd/iam.go:284:cmd.(*IAMSys).Init()

10.10.4.30  API: SYSTEM()
10.10.4.30  Time: 13:35:51 UTC 05/19/2022
10.10.4.30  DeploymentID: 9128de69-9fc5-4bb8-83a1-67b787d3afef
10.10.4.30  Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
10.10.4.30         1: cmd/iam.go:285:cmd.(*IAMSys).Init()
```

**Comment by harshavardhana** [comment]
yeah this is gone you can't recover from this `rm -rf /backend_disks/.minio.sys/config` and restart all servers. Looks like you did some kind of a rolling upgrade - https://github.com/minio/minio#upgrading-minio (refer how to upgrade safely)

There is nothing to do here from our end.
