### ISSUE TITLE
In single filesystem mode, avoid combining multipart uploads to improve I/O performance

### ISSUE THREAD

**Issue by supriyo-biswas** [minio/minio#14948]
**Is your feature request related to a problem? Please describe.**

Currently, minio, in its single filesystem mode, [combines all multipart objects to a single object](https://github.com/minio/minio/blob/6cfb1cb6fd329f2ea7de20a8691c1e7f63763f9f/cmd/fs-v1-multipart.go#L77). However, combining the objects back in this way leads to additional I/O usage, which makes it difficult to run minio and avoid severe performance degradation with a few concurrent uploads, especially on resource constrained, HDD-based systems.

While it is debatable whether minio should be run on such systems, a wide plethora of smaller server providers advertise "storage VPSes" which are inexpensive systems in this exact configuration and it is often useful to run minio on them.

**Describe the solution you'd like**
Instead of combining all multipart objects in this way, each individual part should be stored as-is on disk and when `CompleteMultipartUpload` is received, a file referring to each part should be written to the disk, instead of performing an append.

IIUC the `xl.meta` file does something similar today, but only for the purpose of serving a part from the combined object, in response to the GetObject API (`GET /...?partNumber=X`).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by harshavardhana** [comment]
@supriyo-biswas we will be moving to a single drive erasure like backend soon - the following work here #14331 - the existing functionality will work as-is for NAS Gateway deployments.

**Comment by supriyo-biswas** [comment]
Thank you for the quick reply. To confirm, the implementation of #14331 will avoid combination of object parts and be similar to what I outlined above?

**Comment by harshavardhana** [comment]
> Thank you for the quick reply. To confirm, the implementation of #14331 will avoid combination of object parts and be similar to what I outlined above?

That's what I meant.
