### ISSUE TITLE
Cannot create one-to-many replication between latest and older MinIO

### ISSUE THREAD

**Issue by giusepperagusa** [minio/minio#14943]
After upgrading to latest MinIO server locally, when I try to create a one-to-many replication from a local (pre-existing bucket, created when running RELEASE.2021-04-18T19-26-29Z) bucket towards two other buckets running on an another MinIO server instance (still  running RELEASE.2021-04-06T23-11-00Z), the second replication rule creation fails with a strange "RoleArn invalid for AWS replication configuration" error.
I successfully re-created from scratch (after local upgrade of both MinIO CLI and server) the two remote bucket references.
Creation of the first replication rule succeeds.
Creation of the second replication rule fails.

## Expected Behavior
Replication rule creation succeeds for more than one replication rule.

## Current Behavior
Remote buckets are correctly listed:

```
[user@host ~]$ mcli admin bucket remote ls local
Remote URL                                Source      ->Target       ARN                                                                                                      SYNC PROXY
https://s3-remote.example.com     replicatest1->replicatest1 arn:minio:replication:westeurope:344d717d-cbf9-44fa-b557-d2862888f3a3:replicatest1                            proxy
https://s3-remote.example.com     replicatest1->replicatest2 arn:minio:replication:westeurope:42c89547-cb23-4047-acb7-a7e5a2250389:replicatest2                            proxy

```

First replication rule creation succeeds:

```
[user@host ~]$ mcli replicate add local/replicatest1 --arn arn:minio:replication:westeurope:344d717d-cbf9-44fa-b557-d2862888f3a3:replicatest1' --remote-bucket replicatest1
Replication configuration rule applied to local/replicatest1 successfully.

```

Second replication rule creation fails with error:

```
[user@host ~]$ mcli replicate add local/replicatest1 --arn 'arn:minio:replication:westeurope:42c89547-cb23-4047-acb7-a7e5a2250389:replicatest2' --remote-bucket replicatest2
mcli: <ERROR> Could not add replication rule. RoleArn invalid for AWS replication configuration: arn:minio:replication:westeurope:42c89547-cb23-4047-acb7-a7e5a2250389:replicatest2.

```

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
See example commands above for details.
1. Create two remote buckets connecting one local bucket and two different buckets on another MinIO server
2. Create first replication rule based on first remote bucket
3. Try to create second replication rule based on second remote bucket

## Context
I am trying to set up more than one replication involving always the same local bucket and some other buckets on a differnt MinIO server instance; I have recently updated the local MinIO server (but not the remote one) and I am trying to setup sync from a pre-existing local bucket.

## Regression
No (just upgraded now)

## Your Environment
Local env:
CentOS Linux release 8.3.2011 (kernel 4.18.0-240.22.1.el8_3.x86_64)
minio version RELEASE.2022-05-08T23-50-31Z (4 local XFS filesystems on different disks)
mcli version RELEASE.2022-05-09T04-08-26Z

Remote env:
Kubernetes 1.18.3
MinIO Operator installed with Helm chart 4.0.11 - server container version minio/minio:RELEASE.2021-04-06T23-11-00Z (4 PVCs on NFS-based CSI storage)

**Comment by harshavardhana** [comment]
@giusepperagusa all servers should be using latest version.
