### ISSUE TITLE
NATS JetStream

### ISSUE THREAD

**Issue by lromor** [minio/minio#14942]
**Is your feature request related to a problem? Please describe.**

NATS streaming (stan) is getting deprecated and superseeded by NATS JetStream. It would be nice if you could upgrade the support to bucket events for the new interface.

**Describe the solution you'd like**
Having a similar/identical interface to connect to NATS JetStream

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
We really do not have time to explore here many flavors of NATs, happy to accept PRs if someone can work on it - closing until then.
