### ISSUE TITLE
Unable to remove bucket

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#14957]
I want to remove the empty bucket but got an error - request limit exceed (see screenshot attached). At the same time I can create new buckets, upload and download files. And I know that the real request rate far from limits.

## Expected Behavior
Bucket should be removed after push Remove button.

## Current Behavior
Bucket doesn't removed because of request limit exceed error.

## Possible Solution
Don't know.

## Steps to Reproduce (for bugs)
1. Create bucket,
2. Upload file.
3. Delete file.
4. Delete bucket.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-05-19T18-20-59Z
* Server setup and configuration: distributed setup with 3 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-1 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
![image_2022-05-21_223815856](https://user-images.githubusercontent.com/13428863/169666730-a3f68aa5-2ea1-4125-9b9f-ed16b9f89766.png)

**Comment by harshavardhana** [comment]
@AlexZIX you need to first attempt a remove using `mc rb --force`  - have you made sure you do not have any other files on the system?

**Comment by harshavardhana** [comment]
just run this 

```py
import urllib3
def force_delete(self, bucket, prefix):
    if bucket is None or bucket == "":
        raise Exception('bucket name is invalid')
    self._execute('DELETE', bucket, prefix, headers={'x-minio-force-delete': 'true'})

from minio import Minio
setattr(Minio, "force_delete", force_delete)
httpClient = urllib3.PoolManager(cert_reqs="CERT_NONE")
minioClient = Minio(
        'localhost:9000',
        access_key='5M2WHXMG1051MNICT2YN',
        secret_key='cW12h8Evcv9xnC6wjVijve4dpiweUb06u1kydiXM',
        secure=False,
        http_client=httpClient
        )
minioClient.force_delete("media-images", "")
```

Make the relevant changes locally to forcibly delete the bucket.
