### ISSUE TITLE
MinIO server not starting using systemctl and certificates generated with certgen

### ISSUE THREAD

**Issue by finid** [minio/minio#14950]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Trying to set up a MinIO server in Standalone mode. When I generate a certificate using the `certgen` utility and start the server with the `minio server` command, all works well, provided I put the certificates in `${HOME}/.minio/certs` and pass that to the command with the `--certs-dir` flag. 

However, when I try to start the server using `systemctl` command, it fails. The error message is:

```
ERROR Unable to load the TLS configuration: Invalid TLS certificate
> Please check the content of your certificate data
HINT: Only PEM (x.509) format is accepted as valid public & private certificates
```
Certificates files ending in .crt and .pem fall under the same PEM format for X.509 certificates, so I have no clue what to do here.

If I opt to generate a certificate using `certbot` (Let's Encrypt) instead, which gives me certificates in `.pem` format, I get the opposite effect, because it seems that MinIO does not expect the certificates files with that extension.

The command used to generate the cert is `certgen -ecdsa-curve P256 -host domain-name,ip-address`. Also tried  with `certgen -ed25519 -ecdsa-curve P256 -host domain-name,ip-address`. That failed too.

## Expected Behavior

The MinIO service should start when started using `systemctl` and I should be able to access the MinIO Console via HTTPS. 

## Current Behavior

MinIO fails to start using `systemctl` with the error given above, but starts when invloed with the `minio server` command

## Steps to Reproduce (for bugs)

1. Install MinIO server
2. Install Certgen and generate a cert using the `certgen` command 
3. Start MinIO using `systemctl`
4. Check the status using `systemctl`
5. View the error generated using `sudo grep minio /var/log/syslog`

## Context

Trying to run MinIO in standalone mode and be able to access the MinIO Console via HTTPS. But not able to make a headway because can't start MinIO with `systemctl`.

## Regression

Not sure.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-05-08T23-50-31Z
* Certgen version: Certgen 1.2
* Server setup and configuration: MinIO in Standalone mode with one storage volume
* Operating System and version (`uname -a`): Linux 5.4.0-107-generic #121-Ubuntu SMP ... x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)

**Comment by harshavardhana** [comment]
> If I opt to generate a certificate using `certbot` (Let's Encrypt) instead, which gives me certificates in `.pem` format, I get the opposite effect, because it seems that MinIO does not expect the certificates files with that extension.

You need to rename the certs properly by renaming the .pem as `.crt`  i.e `public.crt`
 
Now regarding certgen - I just used default options
```
certgen -host "127.0.0.1,localhost"
```

```
#!/bin/bash

set -x

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"
export MINIO_STORAGE_CLASS_STANDARD=EC:4
export MINIO_PROMETHEUS_AUTH_TYPE="public"
export MINIO_API_DELETE_CLEANUP_INTERVAL="5s"
export MINIO_CI_CD=1

killall -9 minio
rm -rf /tmp/dist

scheme="https"
nr_servers=12

addr="localhost"
args=""
for ((i=0;i<$[${nr_servers}];i++)); do
    args="$args $scheme://$addr:$[9100+$i]/tmp/dist/path1/$i"
done

echo $args


for ((i=0;i<$[${nr_servers}];i++)); do
    access="minio"
    secret="minio123"
    (MINIO_ACCESS_KEY=${access} MINIO_SECRET_KEY=${secret} ./minio server --address ":$[9100+$i]" $args 2>&1 | tee /tmp/log$i.txt) &
done
```

```
~ ./run-dist.sh
```

```
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Finished loading IAM sub-system (took 0.0s of 0.0s to load data).
Status:         12 Online, 0 Offline. 
API: https://10.0.0.185:9104  https://172.17.0.1:9104  https://172.18.0.1:9104  https://172.19.0.1:9104  https://127.0.0.1:9104                           

Console: https://10.0.0.185:41505 https://172.17.0.1:41505 https://172.18.0.1:41505 https://172.19.0.1:41505 https://127.0.0.1:41505              

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (41505), please use --console-address ":PORT" to choose a static port.

```


MinIO is up and running looks like you are making mistakes in your environment. 

Which version of certgen are you using? @finid

**Comment by finid** [comment]
I'm using the latest Certgen, that is Certgen 1.2, and left the certs as generated by Certgen, that is, `public.crt` and `private.key`. Like yours, my setup also works when started with the `minio server` command. It's when I start MinIO with `systemctl` that it fails with the error given in my original post. Have you tried starting your MinIO instance with `systemctl start minio`?

**Comment by finid** [comment]
FYI, @harshavardhana, here's part of the content of the README file in Let's Encrypt's `live` directory:

```
WARNING: DO NOT MOVE OR RENAME THESE FILES!
         Certbot expects these files to remain in this location in order
         to function properly!

We recommend not moving these files. For more information, see the Certbot
User Guide at https://certbot.eff.org/docs/using.html#where-are-my-certificates.
```
So renaming the `.pem` files generated by `certbot` is not a good idea.

**Comment by harshavardhana** [comment]
> FYI, @harshavardhana, here's part of the content of the README file in Let's Encrypt's `live` directory:
> 
> ```
> WARNING: DO NOT MOVE OR RENAME THESE FILES!
>          Certbot expects these files to remain in this location in order
>          to function properly!
> 
> We recommend not moving these files. For more information, see the Certbot
> User Guide at https://certbot.eff.org/docs/using.html#where-are-my-certificates.
> ```
> 
> So renaming the `.pem` files generated by `certbot` is not a good idea.

You have to create a symlink or copy of these files into MinIO certs folder. Do this via post-hook scripts that certbot can execute after a successful cert renewal.

MinIO will automatically reload them.

> I'm using the latest Certgen, that is Certgen 1.2, and left the certs as generated by Certgen, that is, `public.crt` and `private.key`. Like yours, my setup also works when started with the `minio server` command. It's when I start MinIO with `systemctl` that it fails with the error given in my original post. Have you tried starting your MinIO instance with `systemctl start minio`?

System ctl is no different, unless it's some configuration on your end. As long as minio server works this is not a certgen problem.
