### ISSUE TITLE
Error occurs in stand-alone

### ISSUE THREAD

**Issue by GONETHEN** [minio/minio#14964]
> ``` 
> @echo off
> echo.
> echo run minio server...
> echo.
> 
> title minio
> 
> cd "D:\minio"
> minio.exe server 'D:\minio\data' --console-address ":9xxx" --address ":9xxx"
> pause
> ```

1.there is only one disk partition
2.when i run this .bat script, the following error occurred
![image](https://user-images.githubusercontent.com/15726529/169944547-dbcc1da3-ac81-4b54-b871-18a5b2053ecc.png)

## Your Environment

* Version used (`minio --version`):minio.exe version RELEASE.2022-05-23T18-45-11Z
* Server setup and configuration:
* Operating System and version (`uname -a`):windows server 2019

**Comment by harshavardhana** [comment]
Change your setup like this

```
minio.exe server  --console-address ":9xxx" --address ":9xxx" 'D:\minio\data'
```

**Comment by GONETHEN** [comment]
> Change your setup like this
> 
> ```
> minio.exe server  --console-address ":9xxx" --address ":9xxx" 'D:\minio\data'
> ```

still not resolved
![image](https://user-images.githubusercontent.com/15726529/169963538-f1398113-a810-4bf6-a88e-40d4794de2db.png)
