### ISSUE TITLE
Minio (Docker) - Signed URLs not working (always returning permission denied)

### ISSUE THREAD

**Issue by titiviking** [minio/minio#14967]
I've setup Minio using Docker and it is running. I can access the GUI and managed to setup a bucket that currently contains already 1 file.

I've created a webapp (on Tomcat) acting as a client application and owner of the bucket.
This client exposes an API to obtain a signed URL that is returned to the customer.

This URL however cannot be used, as any URL created returns an "Access Denied".

A trace at level of Minio confirms the Access denied, but does not provide additional information on the reason of denial.
I'm stuck as I don't known what to look for.

Code of client application:
```
MinioClient minioClient =
          MinioClient.builder()
              .endpoint("http://files.mydomain.com")  //resolved to the container host
              .credentials("BGBKXKS1CH27RC134U97", "3falkCIfwoRxS19FtCqksBzjD9QU5KdLOaCigABz")
              .build();

@GetMapping("/getdownload")
    String getSignedURLDownload(@RequestParam(value = "name", defaultValue = "Logo.ai") String filename) { 
            try {
                // Check whether 'my-bucketname' exists or not.
                boolean found =
                        minioClient.bucketExists(BucketExistsArgs.builder().bucket("my-bucket").build());
                if (found) {
                    System.out.println("Bucket exists");
                } else {
                    System.out.println("Bucket does not exist");
                }
                
                String url =
                        minioClient.getPresignedObjectUrl(
                                GetPresignedObjectUrlArgs.builder()
                                        .method(Method.GET)
                                        .bucket("my-bucket")
                                        .object(filename)
                                        .expiry(2, TimeUnit.HOURS)
                                        .build());
                System.out.println(url);
                return url;
            } catch (ErrorResponseException | InsufficientDataException | InternalException | InvalidKeyException | InvalidResponseException | IOException | NoSuchAlgorithmException | XmlParserException | ServerException ex) {
                Logger.getLogger(S3Controller.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("End of function, something failed...");
            return null;
    }
```

Example URL:
http://files.mydomain.com/my-bucket/Logo.ai?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BGBKXKS1CH27RC134U97%2F20220524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220524T151759Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=8e9fa306d78588ff459a5dfeec97bf36a0258681f4a916c1247da49aca2ece5f

Example response:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>Logo.ai</Key>
<BucketName>my-bucket</BucketName>
<Resource>/my-bucket/Logo.ai</Resource>
<RequestId>16F2138A3F1AD4E5</RequestId>
<HostId>9f9f0642-bb49-490d-b9f0-9e165a391ee7</HostId>
</Error>
```

## Expected Behavior
Signed URL returned to customer should work.

## Current Behavior
Signed URLs are not working and return "Access Denied"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2022-05-08T23-50-31Z
* Server setup and configuration: 
- Minio as Docker container on Synology.
- Tomcat running in dedicated container, running the Minio Java client
- Minio server accessed using signedURL over Synology reverse proxy (all necessary headers configured)
* Operating System and version (`uname -a`):  Linux 8981da0815b4 3.10.108 #42218 SMP Mon Oct 18 19:16:10 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied.</Message>
> <Key>Logo.ai</Key>
> <BucketName>my-bucket</BucketName>
> <Resource>/my-bucket/Logo.ai</Resource>
> <RequestId>16F2138A3F1AD4E5</RequestId>
> <HostId>9f9f0642-bb49-490d-b9f0-9e165a391ee7</HostId>
> </Error>

This means that presigned URL is correct but your user doesn't have the right permissions.

**Comment by titiviking** [comment]
This is strange because I used the account to request the SignedURL. So I would expect that if the user does not have the right permissions, their would be no SignedURL returned...


The credentials used in the client application (on the Tomcat) represent a Service Account that is linked to a user.
That user has a policy assigned that is described as follows:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket"
            ]
        }
    ]
}
```

Not being an expert, but I interpret the above as the ability to take any action on that specific bucket (aka owner of the bucket).

Am I missing something ?

**Comment by titiviking** [comment]
I beleive I may have found the issue...
The resource I specifiy must contain a wilcard to ensure I can to the put on the objects inside the bucket...
I looked up documentation, but I was not able to find anything related to that part...

```
"Resource": [
                "arn:aws:s3:::my-bucket/*"
            ]
```

**Comment by harshavardhana** [comment]
> I beleive I may have found the issue... The resource I specifiy must contain a wilcard to ensure I can to the put on the objects inside the bucket... I looked up documentation, but I was not able to find anything related to that part...
> 
> ```
> "Resource": [
>                 "arn:aws:s3:::my-bucket/*"
>             ]
> ```

It's widely documented on how to write policies, when in doubt use the canned policies such as "readwrite" 

Closing this as a non issue. Presigned URLs are purely client side operations with no network call involved - so even if you have incorrect policy attached. Presigned URLs will be generated ..
