### ISSUE TITLE
When Minio runs on Windows Server 2012 R2, it throws an error

### ISSUE THREAD

**Issue by minefujiko9293** [minio/minio#14973]
When Minio runs on Windows Server 2012 R2, it throws an error。

----------------------------------------------------------------------------------------------------------------------
API: SYSTEM()
Time: 02:06:15 UTC 05/25/2022
DeploymentID: 38331576-91c0-4f96-aa07-355726effe74
Error: srcVolume: .minio.sys/tmp, srcPath: 3f6d8daf-7dc7-477f-9872-7874c3309098,
 dstVolume: .minio.sys/buckets:, dstPath: cgs-out/.usage-cache.bin - error file
access denied (*errors.errorString)
       5: cmd\xl-storage.go:1984:cmd.(*xlStorage).RenameData.func1()
       4: cmd\xl-storage.go:2236:cmd.(*xlStorage).RenameData()
       3: cmd\xl-storage-disk-id-check.go:391:cmd.(*xlStorageDiskIDCheck).Rename
Data()
       2: cmd\erasure-object.go:575:cmd.renameData.func1()
       1: internal\sync\errgroup\errgroup.go:123:errgroup.(*Group).Go.func1()
---------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/23348616/170164232-ee274d1a-a177-422c-915e-cb9d2cd058cb.png)

version:2022-01-04T07:41:07Z 
Windows Server 2012 R2 Standard

**Comment by harshavardhana** [comment]
Erasure code is not fully supported on Windows and its experimental @MineFurjiko please send fixes if you want to use Windows with erasure coding.

**Comment by harshavardhana** [comment]
Re-opening incase @klauspost you would want to fix this?

**Comment by klauspost** [comment]
This indicates a problem in the setup. This should only happen when you are sharing disks, or your system isn't properly connected.

Share setup and upgrade to latest.

**Comment by minefujiko9293** [comment]
> This indicates a problem in the setup. This should only happen when you are sharing disks, or your system isn't properly connected.
> 
> Share setup and upgrade to latest.

This is my start script:
-----------------------------------------------------------
set MINIO_ROOT_USER=minioadmin
set MINIO_ROOT_PASSWORD=minioadmin..
minio.exe server E:\MinIO\Data\{1...4} --console-address ":9001"
-----------------------------------------------------------.
**By the way, this host is a virtual host. Is the "sharing disks" you said related to it**

_Running on my personal computer (system win10), I have never seen this error.
But when I was ready to deploy it to the production environment (Windows Server 2012), I found this error._

**Comment by klauspost** [comment]
> Running on my personal computer (system win10), I have never seen this error.

Same for me. 

Is there any kind of AV running on the system? Is `E:\` local or remote?

**Comment by minefujiko9293** [comment]
> > Running on my personal computer (system win10), I have never seen this error.
> 
> Same for me.
> 
> Is there any kind of AV running on the system? Is `E:\` local or remote?

Yesterday, I took the disk where the Minio data was located offline and online again through the disk manager of windows. Now after a night, I haven't seen this mistake for the time being. I will continue to monitor and reply in a few days. thank you

**Comment by klauspost** [comment]
Typically these errors crop up from AV, since they lock the file for scanning. Since these temp files have just been written they are likely to be picked up for scanning.

Closing for now.
