### ISSUE TITLE
GET file returning with empty file

### ISSUE THREAD

**Issue by Sam-Sundar** [minio/minio#14984]
Hey Guys,

With earlier version of Minio, we used to directly `GET` the file like below

`<domain>/minio/download/<bucket>/<file>?token=`

With latest version where API and Console are on different ports, we tried to expose both the ports as SVC and behind an ingress where `/` routes to console and `/minio` routes to API and tried getting the file like below, but it's failing and showing this error response. Can you please let us know how to download the file through GET method. 
![image](https://user-images.githubusercontent.com/83000807/170651399-0296969d-5360-4fa3-9157-bcb26f468d5e.png)

P.S: The buckets are public.

`<domain>/minio/download/<bucket>/<file>?token=`

**Comment by harshavardhana** [comment]
You should use S3 API. You can't use using unpublished endpoints to download files.
