### ISSUE TITLE
504 error occurs when there are too many files in the directory

### ISSUE THREAD

**Issue by lixh00** [minio/minio#14985]
`There are 11544 files in the directory, it would be great if it could support paging`

![image](https://user-images.githubusercontent.com/72033265/170659444-57b3dcc3-62fe-42e6-9328-9845bfdc3181.png)
![image](https://user-images.githubusercontent.com/72033265/170659595-825f6a17-7cfb-4d92-ad95-2a67cf63cba2.png)

**Comment by harshavardhana** [comment]
This is simply your backend disks do not respond fast enough and you have proxy_read_timeout that is too low for your setup.

Please fix it.

**Comment by harshavardhana** [comment]
Also next time please use the issue template to report the issue properly. Your entire issue lacks setup details, MinIO version etc.

This is a basic etiquette to follow. We can't imagine your setup.
