### ISSUE TITLE
[RESOLVES #10744] ZScaler proxy conflicts with port 9000 causing already exists errors

### ISSUE THREAD

**Issue by kwhickey** [minio/minio#14992]
Found resolution of https://github.com/minio/minio/issues/10744, which I can't comment on because it's locked. Just putting this here for documenting the root cause, and this can be closed (or comment moved to that issue).

This was an intermittent error when using Spark locally to write to "S3" via MinIO living in a docker container. It seemed a race condition or cache issue since it would only come up occasionally, but then would go away. 

It caused:

```
pyspark.sql.utils.AnalysisException: path s3a://<bucket>/<object> already exists 
```

or 

```
FileAlreadyExistsException: path is a file
```

It turns out developer laptops running a ZScaler proxy had that proxy using port 9000 while the minio docker container was _also_ listening on port 9000. Somehow this caused duplicative traffic to minio and probably duplicative writes of the same object. 

Changing docker configuration to have minio bind its internal target API port of 9000 to a different published port (NOT 9000) and then directing traffic to that new port fixed this issue. 

The intermittent nature seems to be related to how the proxy works, not sure how.

**Comment by harshavardhana** [comment]
Its because they use SO_REUSE port
