### ISSUE TITLE
Is there a way to restore the object when the hardware fails?

### ISSUE THREAD

**Issue by dunghn87** [minio/minio#15007]
Is there a way to restore the object when the hardware fails?
Here my cluster http://minio{1...4}/data/disk{1...4} http://minio{5...8}/data/disk{1...4}

minio1: not found
minio2: /data/disk{1..4}/butket/objectname/xl.meta
minio3: /data/disk{1..4}/butket/objectname/xl.meta
minio4: not found

minio5: not found
minio6: not found
minio7: not found
minio8: not found

I Lost Quorum 
MinIO VERSION 2022-02-05T04:40:59Z

_Originally posted by @dunghn87 in https://github.com/minio/minio/discussions/14717#discussioncomment-2853244_

**Comment by vadmeste** [comment]
@dunghn87 is this a single pool ? can you paste arguments that you pass to MinIO ?
