### ISSUE TITLE
Docker unable to initialize new alias using container name but work using docker internal IP address

### ISSUE THREAD

**Issue by IQ1998** [minio/minio#15006]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I use docker compose to setup minio and minio mc as a way to automatically create a bucket. However when adding host using the container name it returns an error: `mc: <ERROR> Unable to initialize new alias from the provided credentials. Invalid Request (invalid hostname).`
## Expected Behavior
It should add the host successfully.

## Current Behavior
Cannot add the host, it returns the above error.

## Possible Solution
I'm sorry I have no idea how to fix this. but it is reproducible in both my machine and my company's server.

## Steps to Reproduce (for bugs)

```
version: '3'
services:

  # The Application
  mobi_minio:
    container_name: mobi_minio
    image: minio/minio
    env_file: minio.env
    restart: always
    command: server /data
    networks:
      - mobidev
  mobi_minio_client:
    image: minio/mc
    networks:
      - mobidev
    depends_on:
      - mobi_minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add mobi_minio http://mobi_minio:9000 4ha8IjQnyMk1omzRb 9LLvoIbTSH49YnwmT) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb mobi_minio/mobidev;
      /usr/bin/mc policy set download mobi_minio/mobidev;
      exit 0;
      "

networks:
  mobidev:
    external: true


```
The `minio.env` file:
```
MINIO_ACCESS_KEY=4ha8IjQnyMk1omzRb
MINIO_SECRET_KEY=9LLvoIbTSH49YnwmT
```

1. Create a docker network using `docker network create mobidev`
2. Use the above docker-compose file using `docker compose up -d --build`
3. Use docker logs and log the mc container, you can see the error

I did go inside the mc container and run using the minio container internal IP address and it works `mc config host add mobi_minio http://172.19.0.2:9000` --> ```Added `mobi_minio` successfully```

I also make sure both are in the same container, here is the output of `docker network inspect mobidev`:
```
[
    {
        "Name": "mobidev",
        "Id": "dad76165faef3c8a897dd0d06dee7a8b274c3ee213252d51f2ec3abb7108ad51",
        "Created": "2022-05-31T09:12:53.763746595+07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "6d542db5face18d818a1c3cd1fecef4520971c08c369c69d4132e6359170c5b5": {
                "Name": "mobi_minio",
                "EndpointID": "dde3ae4032bf461f04b808806eda8f5cc03baeb69fb85e49f6029ae86818fcf4",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "756df7eae7f56a6b01b024d1b747d46f5388a4b4fa1cd63a0519c23a21b96126": {
                "Name": "services_mobi_minio_client_1",
                "EndpointID": "b6aeb3050e0c8fe289759305982b5e450289f67163a30626a6c5202e566ba419",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

I did notice that `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` are deperecated and to use `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` instead. I did try that but its till gave the above error.

## Context
I was trying to setup a simple minio service to use in my company's web application.

## Your Environment

* minio version RELEASE.2022-05-26T05-48-41Z (currently latest docker image)
* mc version RELEASE.2022-05-09T04-08-26Z (currently latest docker image)
* Server setup and configuration: (I don't know any relevant information regarding this, if anyone need anything please let me know)
* Host operating system and version (my local machine use Fedora 34): Linux localhost.localdomain 5.13.19-200.fc34.x86_64 #1 SMP Sat Sep 18 16:32:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Host operating system and version (company server use CentOS 8): Linux <company domain> 4.18.0-305.7.1.el8_4.x86_64 #1 SMP Tue Jun 29 21:55:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Local machine's Docker version: Docker version 20.10.8, build 3967b7d
* Local machine's docker compose version: docker-compose version 1.29.1
* Server machine's Docker version: Docker version 20.10.16, build aa7e414
* Server machine's docker compose version: Docker Compose version v2.5.0

I may have made a rookie mistake along the way. If so I apologize. Thanks anyone in advance

**Comment by harshavardhana** [comment]
> container_name: mobi_minio

This is an invalid hostname - rename it to something like `mobi-minio`

**Comment by IQ1998** [comment]
Damn and here I am searching for if there is any issue with Docker. It was indeed a rookie mistake after all. Thank you for the response
