### ISSUE TITLE
Use TLS can't login get  500  Post "https://back.minio.cn/": dial tcp: lookup back.minio.cn on 10.19.36.3:53: server misbehaving

### ISSUE THREAD

**Issue by 631068264** [minio/minio#15018]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Current Behavior

gen tls cert   follow https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html
```sh
cd  /data/minio/config/certs

openssl req -x509 -sha256 -nodes -days 36500 -newkey rsa:2048 -keyout private.key -out public.crt -subj "/CN=back.minio.cn" -addext "subjectAltName = DNS:back.minio.cn"
```

```sh
docker run -d -p 9000:9000 -p 5000:5000 --name minio -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=12345678" -e "MINIO_SERVER_URL=https://back.minio.cn" -v /data/minio/config:/root/.minio   -v /data/minio/data:/data  harbor.uniin.cn:4443/library/minio server --console-address ":5000" /data
```

logs
```
docker logs -f minio

WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance
API: https://back.minio.cn

Console: https://172.17.0.3:5000 https://127.0.0.1:5000

Documentation: https://docs.min.io
Finished loading IAM sub-system (took 0.0s of 0.0s to load data).

```
login error
<img width="985" alt="image" src="https://user-images.githubusercontent.com/8144089/171415476-1a88b5fd-762f-4f83-84d4-bdeeba32ab59.png">

response

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/8144089/171415689-9347cabe-9be5-4616-9aa1-e8d34f77add4.png">

## Your Environment

* Version used (`minio --version`):   minio version RELEASE.2022-05-26T05-48-41Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux 10-19-64-205 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Fix your DNS @631068264
