### ISSUE TITLE
minio  latest version  not support gateway hdfs

### ISSUE THREAD

**Issue by guandatawangjialin** [minio/minio#15010]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/102361568/171149546-8500d910-b394-4434-8e3f-2af907aa6402.png">

**Comment by klauspost** [comment]
https://github.com/minio/minio/issues/14331

**Comment by slachiewicz** [comment]
maybe it's possible to move gateway hdfs/azure to separate project so it can evolve ?
