### ISSUE TITLE
listing object keys containing control-characters not supported without encoding-type=url

### ISSUE THREAD

**Issue by jt121dot5** [minio/minio#15023]
## Expected Behavior

1) listobject result set should not return duplicate keys
2) listobject result set should return the key that was uploaded, not a corrupted version of it

## Current Behavior

After uploading object keys containing control-characters:

1) listobjects will return a corrupted (substituted?) version of the key.  The control-char is replaced with a utf8 encoded 'question mark' icon - byte sequence %EF%BF%BD
2) the substitution is not unique, which creates duplicate keys in the listobjects result set
3) the substituted keys in listobject result set cannot be used since they do not match the actual object keys that were uploaded

## Steps to Reproduce (for bugs)

create two unix file w/ a control-char in the name:

	echo > "X^V^AY"    # depends on your shell...  X ctrl-v ctrl-a Y
	echo > "X^V^BY"    # depends on your shell...  X ctrl-v ctrl-b Y

upload those files.
I'm using a data appliance - the HTML for the object put looks like this:
> PUT /atime5/WIN/X%02Y HTTP/1.1<0D> 
> authorization: AWS4-HMAC-SHA256 Credential=a12345678/20220601/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-meta-parsec-oid,Signature=c48378641f18e1ffaac417f080ec331d910c3d65d43dfcc320b3e49155454dd8<0D> 
> content-length: 5<0D> 
> host: 172.22.15.92:9000<0D> 
> user-agent: Parsec Labs, LS Series Enterprise Datamover (5.2.0)<0D> 
> x-amz-content-sha256: 41af286dc0b172ed2f1ca934fd2278de4a1192302ffa07087cea2682e7d372e3<0D> 
> x-amz-date: 20220601T205523Z<0D> 

use listobjectsv2 and inspect the results

keys in the result should be (in hex):
	%58%01%59
	%58%02%59

keys in result will actually be:
	%58%EF%BF%BD%59
	%58%EF%BF%BD%59

The keys returned are not correct, and they duplicate one another.
	
## Regression

unknown

## Your Environment

linux - redhat 7.5
minio.RELEASE.2022-05-26T05-48-41Z

I logged into the server and looked at the file name it stored in the file system - it made two files with the correct names.

**Comment by harshavardhana** [comment]
@jt121dot5 we need to the exact request and response please provide `mc admin trace -v` output when you run the application - from what I can tell right now. 

The returned value is actually the URL encoded form of the key because that is what the client asked for we should see if these control characters are somehow handled properly by the Go's XML parser as there are some known limitations in XML regarding certain characters.

**Comment by harshavardhana** [comment]
FWIW here is what I did

```
~ echo "1" > "X^V^AY"
~ echo "1" > "X^V^BY"
~ mc cp "X^V^BY" play/testbucket/
~ mc cp "X^V^AY" play/testbucket/
~ mc ls play/testbucket/
[2022-06-01 17:13:21 PDT]     2B STANDARD X^V^AY
[2022-06-01 17:13:51 PDT]     2B STANDARD X^V^BY
```

No duplicates here.

**Comment by harshavardhana** [comment]
The URL encoded form for that control sequences should be 

```
mc: <DEBUG> PUT /testbucket/X%5EV%5EBY HTTP/1.1
```

For `X^V^BY`

From what it looks like the application is doing is

```
PUT /atime5/WIN/X%02Y HTTP/1.1<0D>
```

Something completely wrong.

**Comment by jt121dot5** [comment]
The ^ symbols represent control characters, not the actual ^ character

echo "1" > "X control+A Y"
echo "1" > "X control+B Y"

The shell I use runs w/ an cmdline editor enabled, and so to type a control char, the control-a and control-b need to be preceded by a control-v .

I'm not using MC .

Please try again using control-characters in the file names.

**Comment by jt121dot5** [comment]
echo 1 > `printf 'X\\001Y'`     # backquotes around the printf and args
echo 1 > `printf 'X\\002Y'`

will make two files w/ the control-chars in them without any special keyboard effort.

If you run ls - the output will vary based on your environment.
If you run ls | less     then it might look like this:
X^AY
X^BY

where the ^A and the ^B are control chars.

**Comment by jt121dot5** [comment]
I'll figure out in more detail where the issue is and make a more succinct ticket - closing this one.

**Comment by harshavardhana** [comment]
> echo 1 > `printf 'X\\001Y'` # backquotes around the printf and args echo 1 > `printf 'X\\002Y'`
> 
> will make two files w/ the control-chars in them without any special keyboard effort.
> 
> If you run ls - the output will vary based on your environment. If you run ls | less then it might look like this: X^AY X^BY
> 
> where the ^A and the ^B are control chars.

Okay let me try those ..

**Comment by jt121dot5** [comment]
I did try w/ MC last night, and it worked, but it worked because MC requests a special encoding for the listobject results - encoding-type=url

S3 consumers that use the std encoding will receive corrupted results - due to the substitutions that occur.   The keys in the result-set may also no longer be unique, as the same substitution might be applied to multiple keys.

The substitutions leave the consumer unable to access the actual stored keys (since the reported ones don't exist), and the duplicate keys in the result-set make for an invalid reply.

This breaks "S3 Browser" for instance.

AWS returns the special chars as XML encoded special chars, which lets the consumer decode and use the keys.
`
AWS returns:   Contents><Key>X&#x1;Y</Key><LastModified>2022-06-02T15:44:23.000Z</LastModified><ETag>&quot;b026324c6904b2a9cb4b88d6d61c81d1&quot;</ETag><Size>2</Size><StorageClass>STANDARD</StorageClass></Contents>
`

I believe there are two issues -
 * if the encoding of the reply can't be accomplished, that should arguably be an error condition rather than for minio to return incorrect data
 * if AWS can work with a given key, then so should minio.  Our product doesn't get to control what keys folks use - and so we try to test for the edge-cases.

**Comment by harshavardhana** [comment]
> S3 consumers that use the std encoding will receive corrupted results - due to the substitutions that occur. The keys in the result-set may also no longer be unique, as the same substitution might be applied to multiple keys.

STD encodings cannot support control characters in XML @jt121dot5 which is impossible to do Go in XML parser (it's a bit poor). This is why `mc` uses `URL` encoding so do all other AWS SDKs treat `URL` encoding as default. - for example `AWS CLI`

However, I want to know which exact characters lead to this and how to create them. I tries `printf` that didn't work :-).

**Comment by harshavardhana** [comment]
> * if AWS can work with a given key, then so should minio.  Our product doesn't get to control what keys folks use - and so we try to test for the edge-cases.

If this is your product you should use URL encoding that will help all situations work properly.

**Comment by jt121dot5** [comment]
>However, I want to know which exact characters lead to this and how to create them

The web tool here consumes/hides the special chars I type.  I'll attach a text/script file in a few minutes.

>STD encodings cannot support control characters in XML 

They do - but they need to be escaped.  This is what AWS does.  Again - the web tool here is hiding some of the detail in the examples I've typed.

>If this is your product you should use URL encoding that will help all situations work properly.

I'm reluctant to change a commercial product to work around an issue w/ Minio.  It seems better to adjust minio to follow the AWS behavior - that way, other tool sets work properly too.

**Comment by jt121dot5** [comment]
[New Text Document (14).txt](https://github.com/minio/minio/files/8825998/New.Text.Document.14.txt)

**Comment by harshavardhana** [comment]
> They do - but they need to be escaped. This is what AWS does. Again - the web tool here is hiding some of the detail in the examples I've typed.
> 

This problem is more so for us because of Go's XML parsing limits. 

> > If this is your product you should use URL encoding that will help all situations work properly.
> 
> I'm reluctant to change a commercial product to work around an issue w/ Minio. It seems better to adjust minio to follow the AWS behavior - that way, other tool sets work properly too.

The reason to change this is beneficial for everyone. URL encoding is simpler for XML and more portable.

**Comment by harshavardhana** [comment]
I see from AWS S3 replies 

```
aws s3 ls s3://harshavardhana/special/ --profile s3
2022-06-02 10:18:19          2 XY
2022-06-02 10:18:19          2 XY
2022-06-02 10:18:19          2 XY
```

This is what AWS S3 returns, not sure how you can tell if they are duplicates or not?

**Comment by jt121dot5** [comment]
If you pipe the cmd into less, you'll be able to see the control chars more clearly.
However, I just installed aws-cli and it uses boto, which asks for url encoding of the listobjects results - so the test isn't useful.

I did find the golang xml function you were referring to - and yup, it doesn't support sending some chars.

If I were you though, I'd consider making a private version of that routine which would return an error rather than silently corrupting the XML data it's trying to send.  Minio is one of the big dogs w/r/t S3, and so returning an error instead of corrupted data seems like a given.
And then, once you have your own escape function, you could more easily make it more compatible w/ AWS w/r/t XML escaping/encoding.

None of this is a serious problem for me though.  I noticed the deviation in behavior between Minio vs AWS and have been putting effort into this ticket as a courtesy.

Other work calls me away.   If you fix minio, then that's great, otherwise - who puts control chars into file names anyway ...  ;-)

Thanks, -Jeff

**Comment by harshavardhana** [comment]
Yeah well, the Go's escaping is sort of incomplete here @jt121dot5 the quotes are 

```
<ETag>&#34;b026324c6904b2a9cb4b88d6d61c81d1&#34;</ETag>
```

However 

```
X�Y
```

Control characters are not.

**Comment by harshavardhana** [comment]
Okay I found what they are doing - they are basically doing NIO based XML encoding https://github.com/eclipse-ee4j/jaxb-ri/blob/484a01bc0367453fdef3de5cf6b5bde6563bd2a4/jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/marshaller/NioEscapeHandler.java#L76

**Comment by harshavardhana** [comment]
I shall close this out, as URL encoding is the preferred approach for special character objects such as these that cannot be handled in a more portable way. 

Here is my analysis of this.  AWS S3 seems to do some kind of specialized XML extension to XML 1.0 - for the encoding that is not in the published RFC for XML 1.0 parser - this breaks portability guarantees.

AWS approach here is wrong, as this simply breaks the XML unmarshalling as well - when Go XML tries to unmarshal this

I tried with aws-sdk-go, but without URL encoding it doesn't work.
```
./aws 
Failed to list vadmeste, SerializationError: failed to decode REST XML response
	status code: 200, request id: Q1ZGZFFCXAN9RK44
caused by: XML syntax error on line 2: illegal character code U+0001
```

So looks like AWS has broken this and is perhaps not consistent with all their SDKs .

**Comment by jt121dot5** [comment]
I understand that you've made your decision, but consider another two-cents' worth of perspective from a guy whose been doing this sort of thing software since the late 70's?

If the server (minio) silently returns corrupted data, then it's a server problem since it's not obvious to the consumer that the data being returned is corrupted/unusable.

If, however, the consumer requests a certain encoding format, and minio does it's best to somehow encode to that, but yet the customer's code then throws an error, it becomes a customer problem.
It might not be a huge problem though, since the customer now knows there is a problem and so can work to correct for it -- by changing their code and requested different encoding, or maybe by just using a different xml decoder.

No worries though - I'll look into workarounds - I'll even pass the info along to the folks who make the commercial s3 browser that I use to manage such things, since it is tripped up by this too.  :-)

-Jeff

**Comment by harshavardhana** [comment]
> If the server (minio) silently returns corrupted data, then it's a server problem since it's not obvious to the consumer that the data being returned is corrupted/unusable.

Okay let me correct you right here @jt121dot5 MinIO is not sending any corrupted data it is sending what is being marshalled by Go stdlib XML library which is following XML spec 1.0, 

IT simply replaces control character byte sequences with standard common byte sequences

> [Definition:] A character is an atomic unit of text as specified by ISO/IEC 10646 [ISO/IEC 10646]. Legal characters are tab, carriage return, line feed, and the legal graphic characters of Unicode and ISO/IEC 10646. The use of "compatibility characters", as defined in section 6.8 of [Unicode], is discouraged.

Now by the time, we get access to this - its already converted to something that we cannot convert back.

```
                        if !isInCharacterRange(r) || (r == 0xFFFD && width == 1) {
                                esc = escFFFD
                                break
                        }
                        continue
```

What it means is that they are not simply encoded in any proprietary XML format like AWS S3, or any such XML 1.0 extensions that AWS S3 seems to follow.

Just like I demonstrated how this kind of proprietary code fails their own SDK while talking to AWS S3 bucket.

```
./aws 
Failed to list vadmeste, SerializationError: failed to decode REST XML response
	status code: 200, request id: EMK49T9ZJ84HA8DA
caused by: XML syntax error on line 2: illegal character code U+0001
```

We can try to mimic whatever AWS S3 does to the nail or simply say what Go says, avoid bad practices stick to XML 1.0 standards.  Right now the choice is that this is not a big deal to support - but if it comes to that we can fork Go's encoding/xml and extend this.

**Comment by jt121dot5** [comment]
Thank you for your time.  Be well.

**Comment by harshavardhana** [comment]
> Thank you for your time. Be well.

FWIW we fixed this on our end @jt121dot5
