### ISSUE TITLE
Error: Disk /mnt/data is part of root disk, will not be used (*errors.errorString)

### ISSUE THREAD

**Issue by topmask** [minio/minio#15039]
Follow this tutorial to install
https://www.digitalocean.com/community/tutorials/how-to-set-up-minio-object-storage-server-in-standalone-mode-on-ubuntu-20-04

Unable to start with the following error
Error: Disk /mnt/data is part of root disk, will not be used (*errors.errorString)

How to solve the problem please?

**Comment by xuan-git** [comment]
+1 ,RELEASE.2022-05-26T05-48-41Z  done

**Comment by harshavardhana** [comment]
Please set CI=true https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#deploy-minio-as-single-node-single-drive

**Comment by harshavardhana** [comment]
> Follow this tutorial to install https://www.digitalocean.com/community/tutorials/how-to-set-up-minio-object-storage-server-in-standalone-mode-on-ubuntu-20-04
> 
> Unable to start with the following error Error: Disk /mnt/data is part of root disk, will not be used (*errors.errorString)
> 
> How to solve the problem please?

When in doubt read official docs, old third-party tutorials may not be updated.

**Comment by topmask** [comment]
thank you, problem solved
