### ISSUE TITLE
Minio on macos + docker no longer starts with RELEASE.2022-06-02T02-11-04Z

### ISSUE THREAD

**Issue by malcolmstill** [minio/minio#15042]
## Expected Behavior
Minio should start with `minio:latest` / `minio:RELEASE.2022-06-02T02-11-04Z`

## Current Behavior

As per older issues (https://github.com/minio/minio/issues/9554, https://github.com/minio/minio/issues/10277), with `RELEASE.2022-06-02T02-11-04Z` minio fails to start and complains about requiring `O_DIRECT` support.

As stated in https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#pre-existing-data, it seems single drive mode now uses erasure coding (which requires `O_DIRECT`?). Where before the recommendation was to ensure you run in filesystem / single drive mode for macos + docker, it seems this may no longer be possible? As stated in that link it suggests running an older version of minio.

## Possible Solution
Run older version (e.g. `RELEASE.2022-05-26T05-48-41Z`) of minio (precluding future updates)

## Steps to Reproduce (for bugs)

1. Start `minio` on macos + docker with version `RELEASE.2022-06-02T02-11-04Z`
2. Minio will error on startup complaining about requiring `O_DIRECT` support.

## Regression

See versions above.

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-06-02T02-11-04Z`
* Server setup and configuration: minio invoked with `minio server --console-address :9001 /data`
* Operating System and version (`uname -a`): `Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`

**Comment by harshavardhana** [comment]
@malcolmstill we need a backend that supports O_DIRECT we cannot do without that.

We suggest that you use binary directly on macOS host as workaround for now.

Will see if this can be disabled on macOS docker instances.

**Comment by malcolmstill** [comment]
@harshavardhana thank you for the quick response and fix for this.
