### ISSUE TITLE
golang/pkg/http: wrongly capitalizes `ETag` header

### ISSUE THREAD

**Issue by andrewkerr9000** [minio/minio#1504]
PUTting an object into Minio running in docker (`Minio/DEVELOPMENT.2016-04-17T22-42-41Z`) returns a response with ETag header named `Etag` (note capitalization). I've observed this with Wireshark running on MacOS host, so it isn't being changed withing my JVM.

The Java AWS SDK expects the header name to be `ETag` and is case sensitive (RFC 2616 be damned). Validation will fail as it cannot find response's ETag.

All relevant code in Minio AFAICS always uses `ETag` (`api-headers.go`, from the commit introducing ETag) so I am confused.

**Comment by harshavardhana** [comment]
> PUTting an object into Minio running in docker (Minio/DEVELOPMENT.2016-04-17T22-42-41Z) returns a response with ETag header named Etag (note capitalization). I've observed this with Wireshark running on MacOS host, so it isn't being changed withing my JVM.
> 
> The Java AWS SDK expects the header name to be ETag and is case sensitive (RFC 2616 be damned). Validation will fail as it cannot find response's ETag.
> 
> All relevant code in Minio AFAICS always uses ETag (api-headers.go, from the commit introducing ETag) so I am confused.

It is the problem of Golang http.CanonicalHeaderKey() but that never stopped Java AWS SDK to not work. The complaint is probably because Etag is empty and Java AWS SDK tries to verify this value during a `GetObject()`. can you also paste the actual error? 

Do you have an actual response header dump?

**Comment by andrewkerr9000** [comment]
Request:

```
PUT /mah-bukkit/foo HTTP/1.1
Host: 192.168.99.100:9000
Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20160506/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-date, Signature=f5dbd3c2a9313cfcff3d003c7d8fb3f8f8ada40da3da8ef5ab2da1968be3d860
X-Amz-Date: 20160506T133847Z
User-Agent: aws-sdk-java/1.10.33 Mac_OS_X/10.11.4 Java_HotSpot(TM)_64-Bit_Server_VM/25.77-b03/1.8.0_77
Content-Type: application/octet-stream
Content-Length: 11
Connection: Keep-Alive
Expect: 100-continue

i am a file
```

Response:

```
''EY@?cdc#(lx
m#HTTP/1.1 200 OK
Accept-Ranges: bytes
Etag: "e4807c9accee9290631b071da33d9515"
Server: Minio/DEVELOPMENT.2016-04-17T22-42-41Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: FCRCHHSG9K3MPSQ5
Date: Fri, 06 May 2016 13:38:47 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

**Comment by andrewkerr9000** [comment]
Java AWS SDK 1.10.33 (wrapped in awscala 0.5.5, but that's not causing the problem)

**Comment by andrewkerr9000** [comment]
From `com.amazonaws.services.s3.model.ObjectMetada`:

```
    public String getETag() {
        return (String)metadata.get(Headers.ETAG);
    }
```

`Headers.ETAG` is `public static final String ETAG = "ETag";` `metadata` is a `Map<String, Object>`.  ETag is stored in `metada` (which can be seen with debugger) but with the key `Etag`. This method of course returns `null`.

There's also special handling for the ETag header to strip double quotes in `com.amazonaws.services.s3.internal.AbstractS3ResponseHandler#populateObjectMetadata` which gets `Headers.ETAG` which isn't being hit.

Exception is

```
Exception encountered when invoking run on a nested suite - Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 5IB8mszukpBjGwcdoz2VFQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@7859e786, bucketName: mah-bukkit, key: foo)
com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 5IB8mszukpBjGwcdoz2VFQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@7859e786, bucketName: mah-bukkit, key: foo)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1402)
    at awscala.s3.S3$class.putObject(S3.scala:231)
```

**Comment by andrewkerr9000** [comment]
To clarify: this is happening during a `putObject`. I am aware of the workaround `System.setProperty("com.amazonaws.services.s3.disableGetObjectMD5Validation","true")` for `getObject`.

**Comment by harshavardhana** [comment]
> To clarify: this is happening during a putObject. I am aware of the workaround System.setProperty("com.amazonaws.services.s3.disableGetObjectMD5Validation","true") for getObject.
> 
> Exception encountered when invoking run on a nested suite - Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 5IB8mszukpBjGwcdoz2VFQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@7859e786, bucketName: mah-bukkit, key: foo)
> com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 5IB8mszukpBjGwcdoz2VFQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@7859e786, bucketName: mah-bukkit, key: foo)
>     at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1402)
>     at awscala.s3.S3$class.putObject(S3.scala:231)

There should be a way to disable this validation? - this is not really necessary in general since server validates what was sent by computing and matching the md5sums. 

I don't know why they do that again.  The bug is inside Golang http trying to canonicalize the ETag while ignoring our setting. 

```
api-headers.go:         w.Header().Set("ETag", "\""+objInfo.MD5Sum+"\"")
```

**Comment by andrewkerr9000** [comment]
MD5 checking for `PutObjectRequest` is only disabled if the SDK thinks server side encryption is being used - either an SSE customer key or SSE aws key management params need to be set in the `PutObjectRequest`.

**Comment by harshavardhana** [comment]
> MD5 checking for PutObjectRequest is only disabled if the SDK thinks server side encryption is being used - either an SSE customer key or SSE aws key management params need to be set in the PutObjectRequest.

do you have a sample AWS SDK sample for this test? would you mind referencing it here? - Thanks

**Comment by andrewkerr9000** [comment]
It is only possible to use server side encryption over HTTPS - the SDK ensures this to prevent keys being transmitted in plaintext. I haven't yet configured certificates for Minio and my JVM so I don't know if this will hit further problems.

Scala, using the Java SDK:

``` scala
val s3: AmazonS3 = ???
val putObjectRequest = new PutObjectRequest("bucket name", "key", new StringInputStream("object contents"), new ObjectMetadata())
putObjectRequest.setSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams("aws kms key ID"))
s3.putObject(putObjectRequest)
```

**Comment by harshavardhana** [comment]
> It is only possible to use server side encryption over HTTPS - the SDK ensures this to prevent keys being transmitted in plaintext. I haven't yet configured certificates for Minio and my JVM so I don't know if this will hit further problems.
> 
> Scala, using the Java SDK:
> 
> val s3: AmazonS3 = ???
> val putObjectRequest = new PutObjectRequest("bucket name", "key", new StringInputStream("object contents"), new ObjectMetadata())
> putObjectRequest.setSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams("aws kms key ID"))
> s3.putObject(putObjectRequest)

Minio server does not support server side encryption, we will see how we can address this by fixing ETag.  Even we set the proper "ETag" header.  Golang http server mangles it by canonicalizing it.

**Comment by andrewkerr9000** [comment]
We have a workaround using an embedded proxy, LittleProxy, to rewrite headers. It's a bit mad, but it works for our purposes.

**Comment by harshavardhana** [comment]
After reading the related RFC and reading through golang bugs https://github.com/golang/go/issues/823, it is in-fact the right behavior

```
The server could emit everything lower case if it wanted to
(and maybe it should, just to make the point).  Clients or servers
that insist on a particular case are in violation of the RFC.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

    Field names are case-insensitive.
```

So in this case aws-sdk-java is misbehaving and should be fixed.

**Comment by harshavardhana** [comment]
Also the newest RFC as well - https://tools.ietf.org/html/rfc7230#section-3.2 

```
   Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.
```

**Comment by harshavardhana** [comment]
Additionally looks like you are using an older release - https://github.com/aws/aws-sdk-java/releases/tag/1.10.33 

Recent releases since Jan 21st have the following fix 

```
commit f4c90ece32e3a6d15b1e6e028188f9701bf90494
Author: Arjen Hoekstra <arjen.hoekstra@mendix.com>
Date:   Wed Jan 6 12:00:25 2016 +0100

    Case-insensitive equals check for response headers

diff --git a/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/AbstractS3ResponseHandler.java b/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/AbstractS3ResponseHandler.java
index cb4ddf2..bcd58ec 100644
--- a/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/AbstractS3ResponseHandler.java
+++ b/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/AbstractS3ResponseHandler.java
@@ -110,29 +110,29 @@ public abstract class AbstractS3ResponseHandler<T>
                 metadata.addUserMetadata(key, header.getValue());
             } else if (ignoredHeaders.contains(key)) {
                 // ignore...
-            } else if (key.equals(Headers.LAST_MODIFIED)) {
+            } else if (key.equalsIgnoreCase(Headers.LAST_MODIFIED)) {
                 try {
                     metadata.setHeader(key, ServiceUtils.parseRfc822Date(header.getValue()));
                 } catch (Exception pe) {
                     log.warn("Unable to parse last modified date: " + header.getValue(), pe);
                 }
-            } else if (key.equals(Headers.CONTENT_LENGTH)) {
+            } else if (key.equalsIgnoreCase(Headers.CONTENT_LENGTH)) {
                 try {
                     metadata.setHeader(key, Long.parseLong(header.getValue()));
                 } catch (NumberFormatException nfe) {
                     log.warn("Unable to parse content length: " + header.getValue(), nfe);
                 }
-            } else if (key.equals(Headers.ETAG)) {
+            } else if (key.equalsIgnoreCase(Headers.ETAG)) {
                 metadata.setHeader(key, ServiceUtils.removeQuotes(header.getValue()));
-            } else if (key.equals(Headers.EXPIRES)) {
+            } else if (key.equalsIgnoreCase(Headers.EXPIRES)) {
                 try {
                     metadata.setHttpExpiresDate(DateUtils.parseRFC822Date(header.getValue()));
                 } catch (Exception pe) {
                     log.warn("Unable to parse http expiration date: " + header.getValue(), pe);
                 }
-            } else if (key.equals(Headers.EXPIRATION)) {
+            } else if (key.equalsIgnoreCase(Headers.EXPIRATION)) {
                 new ObjectExpirationHeaderHandler<ObjectMetadata>().handle(metadata, response);
-            } else if (key.equals(Headers.RESTORE)) {
+            } else if (key.equalsIgnoreCase(Headers.RESTORE)) {
                 new ObjectRestoreHeaderHandler<ObjectRestoreResult>().handle(metadata, response);
             } else {
                 metadata.setHeader(key, header.getValue());
```

Seems like it might be fixed already @andrewkerr9000

**Comment by harshavardhana** [comment]
Can you validate and let us know @andrewkerr9000 ? - happy to send a patch upstream if its not working for you. 

https://github.com/aws/aws-sdk-java/pull/590

**Comment by harshavardhana** [comment]
> Can you validate and let us know @andrewkerr9000 ? - happy to send a patch upstream if its not working for you.
> 
> aws/aws-sdk-java#590

Closing - working as expected - Please reopen if aws-sdk-java issue persists.
