### ISSUE TITLE
WebUI/listObjects() show/return object. Download/getObject() return empty file / cause error "NoSuchKey"

### ISSUE THREAD

**Issue by RAlfoeldi** [minio/minio#15040]
The WebUI displays a file with a plausible size of 740B.
![Screenshot 2022-06-05 144902](https://user-images.githubusercontent.com/7020711/172051220-9a34eaec-ce89-4d45-bf86-9dee621b7669.png)

Downloading this file via WebUI results in an empty file:
![Screenshot 2022-06-05 145130](https://user-images.githubusercontent.com/7020711/172051315-61a88480-432f-4625-a8b6-fa2842ab17bd.png)

API access by way of listObjects() returns an Iterator<Result<Item>> results, which includes the above mentioned objectName.

Calling getObject() with the objectName from above causes an ErrorResponseException with an errorResponseCode "NoSuchKey".

## Expected Behavior
Parts of Minio seem to think the file exists, others don't. A displayed / listed objectName should be retrievable.

## Current Behavior
See description.

Trace of a download attempt by WebUI:
![Screenshot 2022-06-05 150522](https://user-images.githubusercontent.com/7020711/172051825-0428eaee-96ee-4a3f-8c90-828d77a61fd0.png)

## Context
Usecase is a regular low intensity consistency check with a cassandra db. We traverse all Minio objects and check if cassandra is up-to-date.

## Regression
na

## Your Environment
MinIO VERSION 2022-04-16T04:26:02Z
4 dedicated Rasp-4B with 8GB each with dedicated 2TB SSD.
Linux rasp-3 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

This has been working like a charm for about a year with > 16 Mio object and 2 TB data.

**Comment by harshavardhana** [comment]
@RAlfoeldi please upgrade to latest and also use strict quorum `mc admin config set alias/ api list_quorum=strict`. This is the default anyways.

**Comment by RAlfoeldi** [comment]
@harshavardhana : Thanks for your quick reply. I've updated the cluster and am now on

Version: 2022-06-03T01:40:53Z

The behavior is still as described above. 

Could you reopen the issue?

**Comment by harshavardhana** [comment]
> @harshavardhana : Thanks for your quick reply. I've updated the cluster and am now on
> 
> Version: 2022-06-03T01:40:53Z
> 
> The behavior is still as described above.
> 
> Could you reopen the issue?

Just set the list_quorum to strict

**Comment by RAlfoeldi** [comment]
@harshavardhana .... done. Same effect.
![Screenshot 2022-06-05 154414](https://user-images.githubusercontent.com/7020711/172053678-a355aab5-446a-4bd8-af2e-130f690aad95.png)

**Comment by kannappanr** [comment]
What is the size of the object in the listobject output?

**Comment by RAlfoeldi** [comment]
@kannappanr 748B

![Screenshot 2022-06-05 162326](https://user-images.githubusercontent.com/7020711/172055286-954a918a-f5ac-4ef2-8270-fab60bba1a2d.png)
 
Accessing this exact same object results in:
![Screenshot 2022-06-05 162751](https://user-images.githubusercontent.com/7020711/172055517-fd388496-e453-4c6b-b311-a31bcaf1c5cd.png)

**Comment by harshavardhana** [comment]
mc support inspect alias/bucket/object-name/** - please share the output

**Comment by RAlfoeldi** [comment]
[inspect.e3122c14.zip](https://github.com/minio/minio/files/8840463/inspect.e3122c14.zip)

**Comment by harshavardhana** [comment]
@RAlfoeldi are you using a transitioned setup here? looks like your objects have been Transitioned over to AWS buckets

**Comment by harshavardhana** [comment]
So what you are seeing is valid here.. we do show the namespace entry for the object since they are readable entries from the backend. 

IT looks like your object has been deleted from your transitioned tier here so we can't get the data out.

**Comment by harshavardhana** [comment]
The expected path on the AWS tier is

```
779a25f1-8599-4ab0-b4c9-9adc2b850f83/webcam-local-images/fc/0c/fc0c2300-7b08-4c13-9fbb-51f033069125
```

>               "x-minio-internal-transition-status": "Y29tcGxldGU="

Says transition was complete

>               "x-minio-internal-transition-tier": "QVdTLVRFU1Q=",

The transition tier name is "AWS-TEST"

Looks like you did some cleanup on your AWS buckets - or someone has misconfigured this for you.

**Comment by RAlfoeldi** [comment]
@harshavardhana Correct. 

This bucket had a lifecycle rule to transition to AWS. That lifecycle rule was removed as no longer relevant, but some objects remain on AWS as there is  - at the moment - no way to retrieve everything back to minio.

AWS does not have the subdirectory ../fc/0c. ~~But it was NEVER(!) manually changed.~~ See the screenshot of the folders "around" 0c below. The only system with access was minio. As this is a test/dev bucket I have no problem just deleting the object. From my POV I'm fine with this issue remaining closed.

But it does suggest that minio has (had) some kind of bug.

Thanks for the support and effort and greetings from Switzerland.

Edit: On second thoughts... I cannot be absolutely sure that - as this is a test/dev bucket - that the AWS bucket was never reset. I don't think so, but thinking isn't knowing. If that were the case, I would owe you guys a cup of coffee. Redeemable anytime you're in Switzerland.

![Screenshot 2022-06-05 201431](https://user-images.githubusercontent.com/7020711/172064589-6ff02239-f38a-4ce0-b60f-8da9f222344c.png)

**Comment by RAlfoeldi** [comment]
Just an update: This has just happend in a production env in which **most certainly nobody touched the aws buckets.**

@harshavardhana :  Please ping me if you're interested in further info. Otherwise I'll just delete the missing entry.

**Comment by harshavardhana** [comment]
@krisis ^^ you may be interested in this.

**Comment by harshavardhana** [comment]
> Just an update: This has just happend in a production env in which **most certainly nobody touched the aws buckets.**
> 
> @harshavardhana : Please ping me if you're interested in further info. Otherwise I'll just delete the missing entry.

Please do share @RAlfoeldi

**Comment by krisis** [comment]
@RAlfoeldi Could you share the following information redacting anything that may be sensitive?
1.  `mc ilm export ALIAS/bucket` - ILM policy configured on the MinIO bucket where you see this issue in production
2. `mc support inspect ALIAS/bucket/object-name` - for the object under investigation
3. `mc admin tier ls ALIAS` output

**Comment by RAlfoeldi** [comment]
@krisis : Coming Monday. On the road.

**Comment by harshavardhana** [comment]
> @krisis : Coming Monday. On the road.

Just checking back.. @RAlfoeldi

**Comment by RAlfoeldi** [comment]
@krisis @harshavardhana Sorry. While "on the road" some things got backed up that I had to take care of.

I have a slight problem. I used the lifecycle configuration to backout data as local storage was running low. After extending local storage I removed the ilm configuration in order to keep data locally.  I can now see the tier, but it seems that I can no longer access it. 

`mc ilm export` requires a bucket.  The UI only allows creating a new ilm.
`mc admin tier` returns: 
Name                  |Type  |Endpoint                  |Bucket                |Prefix                |Region        |Storage-Class
AWS-TEST              |s3    |https://s3.amazonaws.com  |lisicam-test          |lisicam-test          |eu-central-1  |
LISICAM-BACKOUT-PROD  |s3    |https://s3.amazonaws.com  |lisicam-backout-prod  |lisicam-backout-prod  |eu-central-1  |

Is there any way to access existing policies? Attaching an existing policy to a new bucket and then exporting doesn't seem to be an option.

Making matters worse, I personally did not delete the object causing the problem, but a regular cleanup task did. So I can't give you the result of `mc support inspect` 

My logs show
Jun 16 17:39:25 rasp-3 java[3297368]: DEBUG walker-1             c.a.webcam.webcamserver.utils.MaintenanceWalker    File: 1C/bern1/2022/05/28/15/bern1-20220528-152515.meta
Jun 16 17:39:25 rasp-3 java[3297368]: DEBUG walker-1             c.a.webcam.webcamserver.storage.cloud.MinioStorage Object 1C/bern1/2022/05/28/15/bern1-20220528-152515.meta does not exist.`

indicating that the object was listed, but when accessed wasn't there. This is the same behavior as described above.

And in this case I can assure you that nobody touched the AWS storage.

If you're interested, I can give you full access to the minio instance. There is nothing confidential in the storage.,

Edit: There is still "hope". I've restarted the MaintenanceWalker task and with a little bit of luck, we'll get another error.

**Comment by harshavardhana** [comment]
> Making matters worse, I personally did not delete the object causing the problem, but a regular cleanup task did. So I can't give you the result of `mc support inspect`

what is the regular cleanup task?

**Comment by RAlfoeldi** [comment]
Regular cleanup task: Business logic that gets rid of no longer needed data. 20220528-152515 is an image from 15:25 and 15 seconds. After 7 days everything under an interval of 5 minutes is deleted. 15:25 is still there. 15:30 is still there. Everything between that has been deleted.

**Comment by krisis** [comment]
> mc ilm export requires a bucket. The UI only allows creating a new ilm.

Yes, ilm-export command requires a bucket as an argument. I'd like to see the ILM policy configured on `webcam-local-images` bucket. Could you paste the output of `mc ilm export ALIAS/webcam-local-images`?

Can you confirm that you don't have any ILM policies configured on your AWS buckets `lisicam-test` and `lisicam-backout-prod`?

> Is there any way to access existing policies? Attaching an existing policy to a new bucket and then exporting doesn't seem to be an option.

`mc ilm export ALIAS/bucket` is how you can access an existing ILM policy on a bucket. If this isn't working for you, could you paste the commands you ran and any error messages you observed at that time?

**Comment by RAlfoeldi** [comment]
Both ILMs have been removed from the buckets - as no longer required and actually counterproductive - and are no longer accessible - at least for me.

```
ansible@ral-xps15:~$ mc ilm export local/webcam-local-images
mc: <ERROR> Unable to get lifecycle configuration. The lifecycle configuration does not exist.
```

They do however still appear to be active. `mc admin tier info local` returns
```
┌────────────────────┬────────┬────┬───────┬───────┬────────┐
│        Name        │  API   │Type│ Usage │Objects│Versions│                                                         
├────────────────────┼────────┼────┼───────┼───────┼────────┤
│      STANDARD      │internal│hot │1.7 TiB│9162320│9162320 │
├────────────────────┼────────┼────┼───────┼───────┼────────┤
│      AWS-TEST      │   s3   │warm│44 GiB │204073 │ 204073 │                                                         
├────────────────────┼────────┼────┼───────┼───────┼────────┤
│LISICAM-BACKOUT-PROD│   s3   │warm│164 GiB│1122094│1122094 │
└────────────────────┴────────┴────┴───────┴───────┴────────┘   
```
as I would expect as the transitioned data isn't returned to local storage.

As to AWS ILMs... seeing is believing:
![Screenshot 2022-06-22 201537](https://user-images.githubusercontent.com/7020711/175108217-1b3e9a29-5bd2-4792-825d-a87aae33b22c.png)

No ILM on S3.

I can attach the **tier** to a new test-ilm bucket and then export that.

mc ilm export local/test-ilm returns:

```
ansible@ral-xps15:~$ mc ilm export local/test-ilm
{
 "Rules": [
  {
   "ID": "caplpnb6g3gv4vqs4fog",
   "Status": "Enabled",
   "Transition": {
    "StorageClass": "LISICAM-BACKOUT-PROD",
    "Days": 30
   }
  }
 ]
}
```

Happy to provide anything else.

MaintenanceWalker is reactivated and there is a good chance we'll get a "live" error in the next hours.

**Comment by RAlfoeldi** [comment]
Have a bunch of "phantom objects".

UI displays object:
![Screenshot 2022-06-23 121736](https://user-images.githubusercontent.com/7020711/175276883-0db5f751-3222-44b8-b9b0-50c53a929c8f.png)

Download is "successful":
![Screenshot 2022-06-23 121756](https://user-images.githubusercontent.com/7020711/175276992-073db31a-083c-4b92-9a16-437fcff1ab0a.png)

File size is 0:
![Screenshot 2022-06-23 121820](https://user-images.githubusercontent.com/7020711/175277045-f9c588db-4853-49df-9f53-f9b4d6e7b1d5.png)

Inspect.zip
[inspect.11d04585.zip](https://github.com/minio/minio/files/8966307/inspect.11d04585.zip)

Applicationlog:
```
Jun 23 10:33:34 rasp-3 java[3643862]: ErrorResponse(code = NoSuchKey, message = The specified key does not exist., bucketName = webcam-images, objectName = 1F/aletsch1/2021/10/15/10/aletsch1-20211015-104100.bin, resource = /webcam-images/1F/aletsch1/2021/10/15/10/aletsch1-20211015-104100.jpg, requestId = 16FB362389DE5891, hostId = 779a25f1-8599-4ab0-b4c9-9adc2>
Jun 23 10:33:34 rasp-3 java[3643862]: request={method=PUT, url=https://storage.xxx.ch/webcam-images/1F/aletsch1/2021/10/15/10/aletsch1-20211015-104100.jpg, headers=x-amz-copy-source: /webcam-images/1F/aletsch1/2021/10/15/10/aletsch1-20211015-104100.bin
Jun 23 10:33:34 rasp-3 java[3643862]: Host: storage.xxx.ch
Jun 23 10:33:34 rasp-3 java[3643862]: Accept-Encoding: identity
Jun 23 10:33:34 rasp-3 java[3643862]: User-Agent: MinIO (Linux; aarch64) minio-java/8.3.3
Jun 23 10:33:34 rasp-3 java[3643862]: Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
Jun 23 10:33:34 rasp-3 java[3643862]: x-amz-content-sha256: UNSIGNED-PAYLOAD
Jun 23 10:33:34 rasp-3 java[3643862]: x-amz-date: 20220623T093334Z
Jun 23 10:33:34 rasp-3 java[3643862]: Authorization: ██
Jun 23 10:33:34 rasp-3 java[3643862]: }
Jun 23 10:33:34 rasp-3 java[3643862]: response={code=404, headers=Accept-Ranges: bytes
Jun 23 10:33:34 rasp-3 java[3643862]: Content-Length: 435
Jun 23 10:33:34 rasp-3 java[3643862]: Content-Security-Policy: block-all-mixed-content
Jun 23 10:33:34 rasp-3 java[3643862]: Content-Type: application/xml
Jun 23 10:33:34 rasp-3 java[3643862]: Date: Thu, 23 Jun 2022 09:33:34 GMT
Jun 23 10:33:34 rasp-3 java[3643862]: Server: MinIO
Jun 23 10:33:34 rasp-3 java[3643862]: Strict-Transport-Security: max-age=31536000; includeSubDomains
Jun 23 10:33:34 rasp-3 java[3643862]: Vary: Origin
Jun 23 10:33:34 rasp-3 java[3643862]: Vary: Accept-Encoding
Jun 23 10:33:34 rasp-3 java[3643862]: X-Amz-Bucket-Region: bern1
Jun 23 10:33:34 rasp-3 java[3643862]: X-Amz-Request-Id: 16FB362389DE5891
Jun 23 10:33:34 rasp-3 java[3643862]: X-Content-Type-Options: nosniff
Jun 23 10:33:34 rasp-3 java[3643862]: X-Xss-Protection: 1; mode=block
Jun 23 10:33:34 rasp-3 java[3643862]: }
Jun 23 10:33:34 rasp-3 java[3643862]:         at io.minio.S3Base.execute(S3Base.java:645)
Jun 23 10:33:34 rasp-3 java[3643862]:         at io.minio.S3Base.execute(S3Base.java:440)
Jun 23 10:33:34 rasp-3 java[3643862]:         at io.minio.S3Base.executePut(S3Base.java:772)
Jun 23 10:33:34 rasp-3 java[3643862]:         at io.minio.MinioClient.copyObject(MinioClient.java:464)
Jun 23 10:33:34 rasp-3 java[3643862]:         at ch.xxx.webcam.webcamserver.storage.cloud.MinioStorage._minioCopy(MinioStorage.java:1129)
Jun 23 10:33:34 rasp-3 java[3643862]:         at ch.xxx.webcam.webcamserver.storage.cloud.MinioStorage.rename(MinioStorage.java:617)
Jun 23 10:33:34 rasp-3 java[3643862]:         at ch.xxx.webcam.webcamserver.utils.MaintenanceWalker.checkBinSuffix(MaintenanceWalker.java:263)
```

**Comment by krisis** [comment]
@RAlfoeldi Would it be possible for you to enable some sort of audit logging at the AWS S3 bucket side? We could observe which application (incl. MinIO) is deleting objects from the remote tier bucket. This may help us get closer to the issue's root cause.
Logging options available on AWS S3 - https://docs.aws.amazon.com/AmazonS3/latest/userguide/logging-with-S3.html

**Comment by RAlfoeldi** [comment]
@krisis Will do.

**Comment by RAlfoeldi** [comment]
@krisis Is this the format you're expecting? This is the "normal server access" logging. CloudTrail seems to offer more, but if this is enough for you, I'll leave it at that.

[2022-06-24-20-15-52-E57292FC31505440.txt](https://github.com/minio/minio/files/8980493/2022-06-24-20-15-52-E57292FC31505440.txt)

**Comment by krisis** [comment]
@RAlfoeldi this is enough. Thank you!

**Comment by RAlfoeldi** [comment]
This is interesting...

```
8a773242a607d4792b3d244578745b62a4312a90dc2174ba1d9ef9e47ce8d9bc lisicam-backout-prod [25/Jun/2022:11:01:40 +0000] 2a02:121f:2e1f::1:3 arn:aws:iam::496449058729:user/minio QKF9NEB9SRN40PG4 REST.DELETE.OBJECT lisicam-backout-prod/779a25f1-8599-4ab0-b4c9-9adc2b850f83/webcam-images/15/a1/15a109aa-4af6-4c1a-912b-060573e31f12 "DELETE /lisicam-backout-prod/779a25f1-8599-4ab0-b4c9-9adc2b850f83/webcam-images/15/a1/15a109aa-4af6-4c1a-912b-060573e31f12 HTTP/1.1" 204 - - - 28 - "-" "MinIO (linux; arm64) minio-go/v7.0.27" - yjTsZaLsTl47jTeQRrpJCMW+2H8x6bgvbWZGc0i/NptNYKWJUjymP4lZGwrDfR1P7sRcA8eifFA= SigV4 ECDHE-RSA-AES128-GCM-SHA256 AuthHeader lisicam-backout-prod.s3.dualstack.eu-central-1.amazonaws.com TLSv1.2 -
```
Extract:
```
user/minio QKF9NEB9SRN40PG4 REST.DELETE.OBJECT
```
while no business logic deletes happened.

Only two users have access to the bucket. minio and root.

![Screenshot 2022-06-25 174841](https://user-images.githubusercontent.com/7020711/175781126-e0e3ef79-fb02-46d7-b436-01cf8a5b70fc.png)

I have no idea what minio does in the background, but as it doesn't "repatriate" data when an ILM is removed I would assume it should have no reason to delete data.

~~Full logs coming up...~~

[lisicam-logs.zip](https://github.com/minio/minio/files/8985160/lisicam-logs.zip)

**Comment by harshavardhana** [comment]
@RAlfoeldi was this object ever restored using Restore object API ?

**Comment by harshavardhana** [comment]
Also is your setup on ARM64?

**Comment by RAlfoeldi** [comment]
@harshavardhana No. 

Everything older than 24 hours is basically long term "cold" storage. I'm vaguely aware that ```mc ilm restore``` exists, but wouldn't even know how to use it :-)

ARM64? Yes. 4 x Raspberry 4, 8GB.

**Comment by harshavardhana** [comment]
100% confirms that

```
func (s3 *warmBackendS3) Remove(ctx context.Context, object string, rv remoteVersionID) error {
        ropts := minio.RemoveObjectOptions{}
        if rv != "" {
                ropts.VersionID = string(rv)
        }
        err := s3.client.RemoveObject(ctx, s3.Bucket, s3.getDest(object), ropts)
        return s3.ToObjectError(err, object)
}
```

the following code was called.

> Everything older than 24 hours is basically long term "cold" storage. I'm vaguely aware that `mc ilm restore` exists, but wouldn't even know how to use it :-)

So you do have ILM expiration also configured on the source?

**Comment by harshavardhana** [comment]
Can you capture `deletion-journal.bin` and `deletion-journal.ro.bin` from the backend disks on all hosts @RAlfoeldi and attach it here? 

Should be present at `/backend_disk/.minio.sys/ilm/`

**Comment by RAlfoeldi** [comment]
> So you do have ILM expiration also configured on the source?

I **HAD** an ILM configured. 

(Edit: "_Everything older than 24 hours is basically long term "cold" storage_" might have been misleading. "cold" storage referred to cold in a business sense as in seldom accessed - NOT as you would use the term as a specific storage tier. Sorry.)

I was running out of local storage and ILM was the stopgap for **1-2 weeks**.

As soon as I doubled local storage I removed the ILM. I had beforehand asked on Slack if there was a way to move data back to local storage and got the answer from one of your team members "not yet, but we're thinking about implementing it". As the UI allowed removing an ILM I assumed already transitioned data would remain on remote storage, but no new data would be moved.

So the current situation is:
- no ILM configured
- but due to previous, now removed ILM, 164 GB and 1122094 objects on AWS.

deletion journals coming. Might be tomorrow. Its almost midnight local time here in Switzerland :-)

Edit: @harshavardhana The deletion-journal.bin file is 2 bytes? On all 4 nodes. deletion-journal.ro.bin is not present. Sure you want them?

![Screenshot 2022-06-25 234819](https://user-images.githubusercontent.com/7020711/175791436-4efa3b1e-6c3c-4af9-910a-47ee10e31854.png)

**Comment by harshavardhana** [comment]
> > So you do have ILM expiration also configured on the source?
> 
> I **HAD** an ILM configured.
> 
> (Edit: "_Everything older than 24 hours is basically long term "cold" storage_" might have been misleading. "cold" storage referred to cold in a business sense as in seldom accessed - NOT as you would use the term as a specific storage tier. Sorry.)
> 
> I was running out of local storage and ILM was the stopgap for **1-2 weeks**.
> 
> As soon as I doubled local storage I removed the ILM. I had beforehand asked on Slack if there was a way to move data back to local storage and got the answer from one of your team members "not yet, but we're thinking about implementing it". As the UI allowed removing an ILM I assumed already transitioned data would remain on remote storage, but no new data would be moved.
> 
> So the current situation is:
> 
> * no ILM configured
> * but due to previous, now removed ILM, 164 GB and 1122094 objects on AWS.
> 
> deletion journals coming. Might be tomorrow. Its almost midnight local time here in Switzerland :-)
> 
> Edit: @harshavardhana The deletion-journal.bin file is 2 bytes? On all 4 nodes. deletion-journal.ro.bin is not present. Sure you want them?
> 
> ![Screenshot 2022-06-25 234819](https://user-images.githubusercontent.com/7020711/175791436-4efa3b1e-6c3c-4af9-910a-47ee10e31854.png)

I meant do you have any ILM expiration configured?

**Comment by RAlfoeldi** [comment]
@harshavardhana No expiration configured.

I repeat my offer to give you guys full mc access to the minio instance. There is nothing confidential or critical on it.

**Comment by harshavardhana** [comment]
> @harshavardhana No expiration configured.
> 
> I repeat my offer to give you guys full mc access to the minio instance. There is nothing confidential or critical on it.

Sure please borrow ssh keys from https://github.com/harshavardhana.keys and send access details to harsha ( a ) min.io (or just mc access)

**Comment by RAlfoeldi** [comment]
@harshavardhana you have mail + access.

**Comment by krisis** [comment]
@RAlfoeldi Could you add my ssh keys too - https://github.com/krisis.keys? 
Meanwhile, could you share the names of  objects whose transitioned data have gone missing since you have enabled the AWS server logs? It would be great if you could attach the output of `mc support inspect` for a sample of such objects. 

I am trying to learn more about the S3 API portions of your business logic to concurrently work on a simple reproducer for this issue. Could you provide a high level overview of how the application logic manages the lifecycle of a single object?

**Comment by RAlfoeldi** [comment]
@krisis 

ssh keys? Will do. Edit: Your keys are already configured. Until 2 days ago your public key was included in Harshavardhana's.

I would feel more comfortable sending you the business logic by mail. As you'll see there should be no relevance to this issue and therefore no need to document it here. Nothing special or secret, but anyway. If that is ok for you, I would need a mail address.

**Comment by krisis** [comment]
@RAlfoeldi thanks. And I agree with you that email works better for a high level overview of application logic - kp (at) minio.io.

**Comment by RAlfoeldi** [comment]
@krisis 
> Meanwhile, could you share the names of objects whose transitioned data have gone missing since you have enabled the AWS server logs? It would be great if you could attach the output of `mc support inspect` for a sample of such objects.

That is almost impossible for me to say. The AWS logs are opaque - at least for me. I have no way of getting at the original minio name from the AWS logs.

It is also almost impossible for me to recognize which objects "went missing" during the AWS logs timeframe as I only notice them as missing when I access them and that can be a day or a month after they were "deleted" on AWS S3.

I've sent the business logic and some code snippets by mail.

**Comment by krisis** [comment]
@RAlfoeldi Thank you. I shall go over your email and ask for further information as needed.

**Comment by RAlfoeldi** [comment]
Update: minio continues to delete files on S3 even though NO delete calls to the local minio instance happen.

The attached aws s3 access logs show a large amount of deletes on/around 28.06.

The attached screen shot shows the missing delete activity on the local minio instance..

![Screenshot 2022-07-05 102923](https://user-images.githubusercontent.com/7020711/177285742-d6c21617-e470-4cb3-9049-e83743a7bac5.png)

[s3-logs.zip](https://github.com/minio/minio/files/9044717/s3-logs.zip)

**Comment by RAlfoeldi** [comment]
@krisis , @harshavardhana: 
I think my previous comment strongly indicates that minio is deleting data without any external reason to do so. I've deactivated all business code cleanup/delete tasks in order to make bug tracking easier, but will have to turn those on soon/now. I also don't feel comfortable with leaving my cluster open to external access indefinitely, so I will be commenting out your ssh keys.
Give me a ping when you're actively doing something on this issue and I'll put your ssh keys back in and deactivate any business code that does deletes.
Greeting from Switzerland
Rainer

**Comment by krisis** [comment]
@RAlfoeldi Thank you for sharing the business logic with us to help reproduce this issue locally. So far, my attempts at recreating the issue haven't been successful. At the moment, we have all the data we think we need. I shall update this issue if I need more information or make progress with my investigation.

**Comment by krisis** [comment]
@RAlfoeldi, could you run `mc admin trace ...` while the MaintenanceWalker job is running and attach the output here?
This will help us know the S3 API calls involved around the time the issue is observed.
  
Do you recall since which MinIO release are you observing this issue? This might gives us some leads what change may be causing this issue.

**Comment by RAlfoeldi** [comment]
@krisis First time noticed MinIO VERSION 2022-04-16T04:26:02Z. First use of lifecycle will have been with a slightly older version.

MaintenanceWalker does not delete anything. It traverses the complete namespace of a minio bucket lazily (lowest thread prio, rate limited). Doing this, it notices problems in that listObjects() returns objectNames that are then not present when retrieved.

Business logic deletes objects. This happens in kind of erratic intervals and is hard to catch.

```mc admin trace``` coming up. May take a day or two as I'm currently on vacation in a remote location with limited internet.

@krisis Even if I'm certainly no minio expert: You did see the logs indicating that minio is deleting data on S3 without ANY delete calls to the local minio instance? Unless there is some kind of a minio cleanup task that regularly does something on S3 (which would be strange in and of itself), that does seem ... interesting?

I repeat my offer to clarify any questions in a call. You have my contact information.

Greetings from the Swiss Alps

**Comment by harshavardhana** [comment]
@RAlfoeldi did you ever enable versioning on your bucket on MinIO?

**Comment by RAlfoeldi** [comment]
@harshavardhana I am almost certain, that versioning was never enabled. But I would hesitate to make a definitive statement. If versioning was ever enabled, then only for a very short time (think 30 seconds) to "try it out in the UI" as it makes absolutely no business sense.
@krisis ```mc admin trace``` may have to wait until 01.-02.08. The current heatwave in Europe makes staying in the mountains an unresitable option :-)
@both: The credentials you have for mc access are still valid.

**Comment by krisis** [comment]
@RAlfoeldi would you be able to build MinIO off of https://github.com/krisis/minio/tree/gh-15040 and run it in your setup? This branch has couple of logs with call-stack information added to pinpoint the codepath responsible for the bug. Since the issue is reproducible consistently in your setup, these logs will help us get closer to the root cause. Let us know if you need any assistance in building for your platform architecture.

**Comment by RAlfoeldi** [comment]
@krisis Will do. Sorry for the delay.

**Comment by krisis** [comment]
@RAlfoeldi were you able to give the build with debug logs a spin on your setup?

**Comment by harshavardhana** [comment]
@RAlfoeldi we will close this, for now, please let us know when you have the logs - we can re-open the issue.
