### ISSUE TITLE
Federation alternative plan

### ISSUE THREAD

**Issue by ftx0day** [minio/minio#15047]
Hi,
We plan to build enterprise-grade object storage with MinIO。
We originally planned to use Federation，but  we hear that  'Federation feature is deprecated and should be avoided for future deployments'.
Servers Pool looks like can not solve cluster failure problem.

How do I choose about this?  Can we still use Federation?
I'd like to have your feedback on this.

Thanks

**Comment by harshavardhana** [comment]
There are no alternative plans @ftx0day - server pools are designed for this to scale up a local cluster. If you want DR then you need to configure replicated buckets. 

That's about it.
