### ISSUE TITLE
Write failed. Insufficient number of disks online (*errors.errorString) [network issue]

### ISSUE THREAD

**Issue by yinhen** [minio/minio#15058]
## NOTE

PutObject to my  minio cluster, but sometimes meet this error: Write failed. Insufficient number of disks online (*errors.errorString)，I'm sure all my nodes are online. It doesn't happed to all my putObject request . If retry do this request, it may be ok.

## Expected Behavior
PutObject ok

## Current Behavior
Meet the error above.

## Steps to Reproduce (for bugs)
It can't be reproduced.

## Regression
No

## Your Environment
* Version used (`https://github.com/minio/minio/releases/tag/RELEASE.2021-10-23T03-28-24Z`):
* Server setup and configuration: 64 nodes，with 4 hdds,each one 18TB，EC：12:4；
* Operating System and version (`uname -a`):2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
1. Upgrade
2. Check if same as https://github.com/minio/minio/issues/15054
3. Post Logs and your setup information.

**Comment by harshavardhana** [comment]
This mainly looks like a setup issue - it's a 64 node setup :-) @klauspost  

> PutObject to my minio cluster, but sometimes meet this error: Write failed. Insufficient number of disks online (*errors.errorString)，I'm sure all my nodes are online. It doesn't happed to all my putObject request . If retry do this request, it may be ok.

You are loosing quorum because nodes disconnect temporarily.
