### ISSUE TITLE
Failed object removal

### ISSUE THREAD

**Issue by szabokacsa** [minio/minio#15050]
## NOTE
I was not able to remove a 1GB file from the bucket. I tried multiple options but none of them worked, I even tried to force delete the bucket.

![c488778f-e0b9-48d6-bdcf-45a746ecb629](https://user-images.githubusercontent.com/3647735/171430938-d6666999-0e39-4ed4-aca3-71bcb883cd7f.jpg)

After the delete attempts, it is still there, but minio tells that there is no object in the bucket, when I asked disk usage api:

![image](https://user-images.githubusercontent.com/3647735/171431070-819d78ed-dce6-4f2b-b381-924ba603a5a3.png)

I uploaded a file to check that I am able to remove the newly uploaded file or not but after the uploading the file, it dissapeared.
The bucket limit is 1GB, and the 1GB file is stucked, but based on disk usage it has free spaces, and the upload was successful, but later the file disappeared.

![image](https://user-images.githubusercontent.com/3647735/172343539-c44f9949-1766-46aa-a215-373c70cf08a2.png)

Later the minio server was restarted but the 1GB file still was stucked.

## Expected Behavior
I expected that the file is removed, when I called force object removal.
I expected that the file and the bucket are removed, when I called force bucket removal.

## Current Behavior
When forced object removal is called, the object is stucked on bucket.
When forced bucket removal is called, the minio does not delete the bucket because of the stucked object.

## Steps to Reproduce (for bugs)

1. go client created 1-1 bucket on 1-1 minio cluster with 2 side replications with 1GB bucket limit.
2. A 1GB big file is uploaded to validate replication. (file is uploaded with mc command)
3. The replication worked and the file was available on both minio cluster. (replication was created by go client)
4. The replication was teared down by go client.
5.  go client tried to delete the object before deleting the bucket on each separated minio cluster.
6.  go client got successful response for delete attempt.
7.  go client tried to delete bucket but it failed with _**"The bucket you tried to delete is not empty. You must delete all versions in the bucket."**_ error.
8.  With mc command, I was able to delete the file from the bucket on the minio cluster, where the file was uploaded.
9.  With mc command, I was not able to delete from the bucket where the file is replicated. I think I should be able to delete replicated object after the replication was teared down.

MC command (delete with version-id):
![image](https://user-images.githubusercontent.com/3647735/172396248-c9ec2b2d-3a00-4649-b709-55b5ccc63535.png)

Trace log:
![image](https://user-images.githubusercontent.com/3647735/172396473-73db80a0-6e24-4dff-8186-2343f815e473.png)

MC command (delete with force flag):
![image](https://user-images.githubusercontent.com/3647735/172396761-cd2fe5c0-c617-43c8-a697-39a27c10980b.png)

Trace log:
![image](https://user-images.githubusercontent.com/3647735/172396813-bd42de7e-e3ca-4064-887a-4b5d8d9d3f09.png)

Mc command (delete all file with force flag)::
![image](https://user-images.githubusercontent.com/3647735/172397458-c1633107-48c2-4d28-8343-693d1f74edfb.png)

Trace log:
[forceFileDelete.txt](https://github.com/minio/minio/files/8853751/forceFileDelete.txt)

Trace log about Bucket deletion:
![image](https://user-images.githubusercontent.com/3647735/172397685-0f5f3efd-76e6-4dbf-a46f-7380235eea01.png)

## Context
Because of this issue the bucket stucked, but i want to clean up all minio resources related to that bucket.

## Regression
No

## Your Environment

Minio client version: RELEASE.2022-02-23T03-15-59Z
Mino version: RELEASE.2022-01-03T18-22-58Z
Minio go client version: github.com/minio/minio-go/v7 v7.0.21

Minio setup: minio servers with 4 disk, ready for replication. Run in kubernetes pod.
Bucket setup: versioning enabled, 2 side replication
Operating System: Linux minio-64d7766797-9wd6c 5.10.69-talos #1 SMP Mon Nov 15 08:09:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Please upgrade @szabokacsa you can't be using old releases as community member.

Once upgraded you will be able to purge these.
