### ISSUE TITLE
Unable To Upload Files Larger than ~100kb

### ISSUE THREAD

**Issue by MykalMachon** [minio/minio#15054]
When uploading a file that is larger than ~100kb to my MinIO instance I get an error. I've been able to upload and access smaller files via the Python API and the console with no issues. The issue seems to be _only_ with files larger than ~100kb in size. 

I am running NGINX as a reverse proxy to expose MinIO to the internet, but:
1. I'm doing all my testing on my local network and am bypassing NGINX by going right to the host IP/Port
2. I've setup NGINX to have an unlimited upload size for the subdomains used by MinIO so that likely isn't the issue. 

I have over 3tb of available storage on the drive MinIO is mounted to so I don't think it's a lack of space either. The MinIO web console shows this as well in the Monitoring > Metrics section. 

## Expected Behavior
1. upload a file from either the MinIO console, or the MinIO SDK
4. Receive a success message
5. Be able to access that file 

## Current Behavior
1. I try to upload a file to my server via the console, or in an application via the SDK, and receive the following message in my server logs. 
```
API: SYSTEM()
Time: 00:24:16 UTC 06/08/2022
DeploymentID: 6ffa5378-58c4-4fe9-86ba-02e65fee7b94
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/public/.usage-cache.bin (cmd.InsufficientWriteQuorum)
       2: internal/logger/logger.go:278:logger.LogIf()
       1: cmd/erasure-single-drive.go:3172:cmd.(*erasureSingle).nsScanner.func3()
```
2. no file is uploaded

## Possible Solution
I'm not sure what is causing this, I've tried a number of things including a fresh install of the image and nothing seems to be working. 

## Steps to Reproduce (for bugs)
* attempt to upload a file that's greater than ~100kb in size from the web console. 
* attempt to upload a file that's greater than ~100kb in size via the from the Python SDK, see below for code
```py
def main():
  client = Minio(
    "192.168.1.123:8011",
    access_key="some-user",
    secret_key="some-password",
    secure=False
  )

  # make a bucket, or write to it
  found = client.bucket_exists('test-bucket')
  if not found:
    client.make_bucket('test-bucket')
  else:
    print("Bucket 'pybucket' already exists...")

  # upload a file
  client.fput_object(
    'test-bucket',
    f'test-from-the-internet-{datetime.now()}.txt',
    './test-file.txt'
  )
  print('things worked 🎉')

  return None

if __name__ == "__main__":
  try:
    main()
  except S3Error as exc:
    print(f"error occured {exc}")
```

I wasn't sure exactly what I should be tracing, so I may need a bit of help to figure out which trace commands I should be running to debug things. 

## Context
I'm trying to use MinIO as bucket/object storage for an application that I'm currently developing. I'm currently using an S3 bucket for file storage, but figured I'd give MinIO a shot as I already have a local server, and could save some money on cloud costs to start. 

I also like that MinIO can run clustered across multiple machines, which would allow me to scale out to cloud or other services if need be. 

## Regression
No, I just setup MinIO the other day and noticed it because I was trying to use it with one of my existing applications. 

## Your Environment

* Version used:
```
minio version RELEASE.2022-06-07T00-33-41Z
commit: e2d4d097e754dd3df2f0f6c6104bfc88fb943737
go version: go1.18.3
```
* Server setup and configuration: I'm running an [Unraid server](https://unraid.net/), and using the [official MinIO](https://unraid.net/community/apps?notTheDroidYoureLookingFor=YWhleXFiYm5ndXBic25jeGF5bWx1bGJvcXFlanJlamI%3D&q=Minio#r) docker image with the following settings: 
  * Web UI: mapped to port 8011
  * Console UI: mapped to port 8012
  * Data: /mnt/user/minio/buckets
  * Config: /mnt/user/minio/config
  * username and password will remain private for obvious reasons
* Operating System and version (`uname -a`):
```
Linux SERVERNAME 5.15.43-Unraid #1 SMP Wed May 25 11:54:05 PDT 2022 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux
```

Please let me know if you need anymore information from me to help debug things!
Thanks in advance 😄

**Comment by harshavardhana** [comment]
@MykalMachon what is your backend filesystem?

**Comment by MykalMachon** [comment]
> @MykalMachon what is your backend filesystem? 

The drive its on is using XFS

**Comment by harshavardhana** [comment]
> The drive its on is using XFS

can you show me your mount options? and also `df -h`

**Comment by harshavardhana** [comment]
are you running this on pre-existing content? @MykalMachon

**Comment by MykalMachon** [comment]
@harshavardhana, thanks for the quick support on this.

> can you show me your mount options?

I have one drive setup to use BTRFS, and two drives drive setup to use XFS (1 runs as a parity drive). 
I'm not sure if this is what you're asking by mount options though.. Unraid makes most of these decisions for you with defaults so I could be missing the question completely. 

> and also df -h 

```bash
Filesystem      Size  Used Avail Use% Mounted on
rootfs          7.6G 1005M  6.7G  13% /
tmpfs            32M  1.3M   31M   4% /run
/dev/sda1        29G  742M   28G   3% /boot
overlay         7.6G 1005M  6.7G  13% /lib/firmware
overlay         7.6G 1005M  6.7G  13% /lib/modules
devtmpfs        8.0M     0  8.0M   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
cgroup_root     8.0M     0  8.0M   0% /sys/fs/cgroup
tmpfs           128M  400K  128M   1% /var/log
/dev/md1        3.7T  241G  3.5T   7% /mnt/disk1
/dev/sdb1       233G   27G  207G  12% /mnt/cache
shfs            3.7T  241G  3.5T   7% /mnt/user0
shfs            3.7T  241G  3.5T   7% /mnt/user
/dev/loop2       20G  5.3G   15G  27% /var/lib/docker
/dev/loop3      1.0G  4.2M  905M   1% /etc/libvirt
```

> are you running this on pre-existing content?

I am not, no. Everything in my MinIO instance was uploaded through the web UI or the Python SDK.

**Comment by harshavardhana** [comment]
Show me `mount` command output @MykalMachon

**Comment by harshavardhana** [comment]
also can you show us how you are running MinIO @MykalMachon

**Comment by MykalMachon** [comment]
> Show me mount command output

I've attached the mount output here: [mount output.txt](https://github.com/minio/minio/files/8858122/mount.output.txt)

> also can you show us how you are running MinIO

I'm running it using Unraid's Community Applications Store as a Docker container. 
MinIO has an "Official" listing in their store so all you have to do is click "Install" and set some variables to be used in the Docker run command. 

![Minio Unraid Screenshot](https://user-images.githubusercontent.com/7844994/172527240-b51bfc74-b6db-4e10-9e5c-83ac552471c5.png)

It's all just a GUI ontop of the Docker command line. So all the GUI in the screenshot does is construct a Docker run command for the Minio/Minio image and run it. Once the app is setup you can interface with it exactly as you would with any Docker application. 

### Edit
on second look Minio is not an official listing in the store, and this may just be an issue with how the image is setup within Unraid (unless you have an idea on why this is happening). 

If that's the case, I'll probably just try getting MinIO onto my Ubuntu VM, Unraid is just a bit easier to maintain and is my goto for things while I experiment.

**Comment by harshavardhana** [comment]
You are not using XFS here @MykalMachon you are mounting something called as `shfs` which looks like a non POSIX filesystem and its also faking O_DIRECT support

```
shfs on /mnt/user type fuse.shfs (rw,nosuid,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other)
```

We need O_DIRECT support to work this is exactly why we are not able to get any write operations successful > 100kb

Please use `/mnt/disk1` directly not `fuse` layer.
