### ISSUE TITLE
Docker Compose Minio keep after reboot

### ISSUE THREAD

**Issue by Michi9090** [minio/minio#15067]
Hi

I am using this Compose File:
https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml

The services are created on a synology NAS with version 7.0.1. I create the services and everything works fine. The services are created with a id, for example minio1-29423725nfdja3289h. After the reboot of the NAS the old services keep stopped and new ones are created. After 10 reboots I have about 50 services... but only 4 are running as supposed.

What am I doing wrong?

**Comment by harshavardhana** [comment]
@Michi9090 this is not the right place to ask how to run Docker services question. Please ask Docker or Synology on how to keep them running on their system.
