### ISSUE TITLE
minio do not release sockets for terminated S3 sessions

### ISSUE THREAD

**Issue by hkirov** [minio/minio#15079]
Minio don't release file descriptors of terminated S3 connections. Over time open file descriptors continue to increase. At some point minio stops accepting S3 connections hitting "api requests_max" limit (10946 currently).
In our setup S3 API calls are handled by first node mainly. On attached graph is shown increased file descriptor and memory usage on node 1 while other nodes are stable.
![minio_resources](https://user-images.githubusercontent.com/6442852/173452317-1d5d8122-7cc9-4378-a00e-91e485cb8dc8.png)
In attached file is a list of open files by minio on node 1. There are a many entries like:

> minio   351597 minio   12u     sock                0,9      0t0  261762612 protocol: TCPv6
> minio   351597 minio   13u     sock                0,9      0t0  252398385 protocol: TCPv6
> minio   351597 minio   14u     sock                0,9      0t0  252993898 protocol: TCPv6
> minio   351597 minio   15u     sock                0,9      0t0  254313718 protocol: TCPv6
> minio   351597 minio   16u     sock                0,9      0t0  251837612 protocol: TCPv6

[lsof_minio.txt](https://github.com/minio/minio/files/8894779/lsof_minio.txt)

## Expected Behavior

Resources to be freed accordingly.

## Current Behavior

Resources are not freed and service stops after some time.

## Possible Solution

We have a high rate of headobject request for nonexistent objects returning 404. This may not be handled correctly by minio.

## Regression

Maybe. We were running RELEASE.2021-08-05T22-01-19Z without issues for some time but the load of the cluster is increased too.  

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-04-12T06-55-35Z
* Server setup and configuration: baremetal cluster with 5 nodes
* Operating System and version (`uname -a`): Linux nl1.webvideocore.net 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): minio version RELEASE.2022-04-12T06-55-35Z

This has already been fixed @hkirov - please upgrade.
