### ISSUE TITLE
CA cert not used for connection to KES

### ISSUE THREAD

**Issue by moljor** [minio/minio#15074]
directory:
/location/client.crt
/location/client.key
/location/CAs/ca.crt

using flag: --certs-dir /location

env variables:
MINIO_KMS_KES_ENDPOINT="https://url.with-own.domain:7373"
MINIO_KMS_KES_KEY_FILE=/location/client.key
MINIO_KMS_KES_CERT_FILE=/location/client.crt

VERSION: RELEASE.2022-06-11T19-55-32Z

## Expected Behavior
Own CA but using certs-dir with the CA certificate, the connection to KES should be valid and working.

## Current Behavior
Connection does not work:

ERROR Unable to initialize a connection to KES as specified by the shell environment: Post "https://url.with-own.domain:7373/v1/key/create/keyname": x509: certificate signed by unknown authority

rollback to version RELEASE.2022-06-07T00-33-41Z fixes the issue.

**Comment by vadmeste** [comment]
I am able to reproduce. Sending a fix.

**Comment by harshavardhana** [comment]
@vadmeste it was always expected that you set the CAPATH for Kes separately.

**Comment by vadmeste** [comment]
> @vadmeste it was always expected that you set the CAPATH for Kes separately.

umm, yes but the code is not doing that anyway.

/cc @aead

**Comment by harshavardhana** [comment]
> > @vadmeste it was always expected that you set the CAPATH for Kes separately.
> 
> umm, yes but the code is not doing that anyway.
> 
> /cc @aead

@vadmeste CAPATH is honored AFAIK it is not defaulting itself to MinIO's internal CAs folder to make sure backwards compatibility is maintained.

Otherwise you need to make sure the MinIO's internal certs are updated in conjunction with KES CAPATH value.

**Comment by aead** [comment]
@moljor Currently, you can work around this by setting `MINIO_KMS_KES_CAPATH=<location>/CAs` This seems like a regression.

@harshavardhana From a UX standpoint, you should be able to add the CA certificate for KES either to the `certs/CAs` directory **or** set `MINIO_KMS_KES_CAPATH`. If you did at least one, MinIO should be able to connect to KES, no?

**Comment by vadmeste** [comment]
> Otherwise you need to make sure the MinIO's internal certs are updated in conjunction with KES CAPATH value.

Yes, before the regression, it was doing that. After the regression, it is not loading /path/to/certs/CAs/ anymore. My fix reverts the old behavior before the regression.

**Comment by moljor** [comment]
> MINIO_KMS_KES_CAPATH

Thanks @aead I did not find that setting in the documentation and that'll be the perfect workaround indeed.
