### ISSUE TITLE
[single drive FS] Objects are not displayed after a node of an earlier version is upgraded to the latest version

### ISSUE THREAD

**Issue by shizhiliuyu** [minio/minio#15075]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 

## Expected Behavior
After upgrading to the new version, services should be provided based on the original data files, and the objects in the bucket should be displayed on console

## Current Behavior
After replacing the image minio/minio: relea.2022-06-11t19-55-32z Only objects in the bucket such as directory object files are no longer displayed

## Possible Solution
Re-identify buckets (objects in the host directory)

## Steps to Reproduce (for bugs)
This is the earliest deployment order
1、docker run -itd --restart=always -p 9000:9000 -p 9001:9001 --name minio  -e "MINIO_ACCESS_KEY=AKIAIKKKKKKK" -e "MINIO_SECRET_KEY=AKIAIKKKKKKK"  -v /mnt/data/minio:/data minio/minio:RELEASE.2021-07-30T00-02-00Z  server /data --console-address ":9001"
After some time the file has been uploaded
![image](https://user-images.githubusercontent.com/93238483/173333319-a04079bf-2d55-46de-8ce6-1a681cde645c.png)

Delete the old container at this point
2、docker rm -f minio

Replace the image with minio/minio using the original startup command: relea.2022-06-11t19-55-32z
3、docker run -itd --restart=always -p 9000:9000 -p 9001:9001 --name minio  -e "MINIO_ACCESS_KEY=AKIAIKKKKKKK" -e "MINIO_SECRET_KEY=AKIAIKKKKKKK"  -v /mnt/data/minio:/data minio/minio:RELEASE.2022-06-07T00-33-41Z  server /data --console-address ":9001"

4、The files in the bucket displayed on the console are directories only
![image](https://user-images.githubusercontent.com/93238483/173334150-3f5aa5de-f2a2-412e-81bd-46a2ee41697c.png)

## Context
The production environment only allows docker to deploy a single node, which requires the new minio life cycle function. Now the effect is that files in the old bucket cannot be accessed.

## Regression
NO

## Your Environment

* Version used (`minio --version`): Docker images 【old：RELEASE.2021-07-30T00-02-00Z update to RELEASE.2022-06-07T00-33-41Z】
* Server setup and configuration: 8C32G
* Operating System and version (`uname -a`): 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please read #14331 on why this won't work. Old single drive mode behavior has been deprecated And removed.
