### ISSUE TITLE
docs: Public vs private? 

### ISSUE THREAD

**Issue by danyaljj** [minio/minio#1508]
Is it possible to make some objects public? (neither AccessKey and SecretKey is needed) While some of them protected (not accessible without AccessKey and SecretKey).

**Comment by harshavardhana** [comment]
> Is it possible to make some objects public? (neither AccessKey and SecretKey is needed) While some of them protected (not accessible without AccessKey and SecretKey).

You can easily configure publicly accessible objects using bucket policy,  minio supports Amazon S3 bucket policies not ACL's.

**Comment by koolhead17** [comment]
Hello @danyaljj

Say once you have Minio Server installed & mc client is in place, If not please follow https://github.com/minio/minio/blob/master/README.md 

You can use `mc access` command to create an object public.

```
 $ mc access set public myminio/shared
```

This will make your object `shared` world accessible. 

You can also run 

```
$ mc access --help
Name:
   mc access - Manage bucket access permissions.

USAGE:
   mc access [FLAGS] set PERMISSION TARGET [TARGET...]
   mc access [FLAGS] get TARGET [TARGET...]

PERMISSION:
   Allowed permissions are: [private, readonly, public, authorized].

FLAGS:
  --help, -h                    Help of access.
  --config-folder, -C "/Users/koolhead17/.mc"   Path to configuration folder.
  --quiet, -q                   Suppress chatty console output.
  --no-color                    Disable color theme.
  --json                    Enable json formatted output.
  --debug                   Enable debugging output.

EXAMPLES:
   1. Set bucket to "private" on Amazon S3 cloud storage.
      $ mc access set private s3/burningman2011

   2. Set bucket to "public" on Amazon S3 cloud storage.
      $ mc access set public s3/shared

   3. Set bucket to "authenticated" on Amazon S3 cloud storage to provide read access to IAM Authenticated Users group.
      $ mc access set authorized s3/shared-authenticated

   4. Get bucket permissions.
      $ mc access get s3/shared

   5. Get bucket permissions.
      $ mc access get gcs/miniocloud
```

Hope, it helps. also feel free to join our community chat channel https://gitter.im/minio/minio I am @koolhead17 there. Will be more than happy to help you. :)

**Comment by tmbdev** [comment]
There is no "mc access" subcommand.

There is an "mc policy public" command. But either using that or setting access to public through the UI still doesn't allow anonymous downloads through localhost:9000/myminio/bucket/file

**Comment by harshavardhana** [comment]
> There is an "mc policy public" command. But either using that or setting access to public through the UI still doesn't allow anonymous downloads through localhost:9000/myminio/bucket/file

what are you trying to do can you paste some commands? @tmbdev

**Comment by tmbdev** [comment]
Overall, I'm trying to use minio as a data server for machine learning.

For that, I need key-protected uploads and unprotected downloads.

I can upload after logging in with "mc cp" or "mc mirror".

For downloading, I would like something like "curl http://localhost:9000/minio/foobar/foo.data" to work

**Comment by harshavardhana** [comment]
> I can upload after logging in with "mc cp" or "mc mirror".
> 
> For downloading, I would like something like "curl http://localhost:9000/minio/foobar/foo.data" to work

This works perfectly fine what version of Minio are you using? @tmbdev 

```
$ mc policy download home/video.test
Access permission for ‘home/video.test’ is set to ‘download’
$ wget http://localhost:9000/video.test/video_test
--2017-01-22 17:50:25--  http://localhost:9000/video.test/video_test
wget: /home/harsha/.netrc:3: unknown token "api.heroku.com"
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:9000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11619328 (11M) [video/mp4]
Saving to: ‘video_test’

video_test                           100%[====================================================================>]  11.08M  --.-KB/s    in 0.04s   

2017-01-22 17:50:25 (265 MB/s) - ‘video_test’ saved [11619328/11619328]

$ rm video_test 
```

**Comment by tmbdev** [comment]
Thanks; I had accidentally included the "/minio/" part in the URL, that's why it failed.

**Comment by danyaljj** [comment]
Any ideas on this question? 
http://stackoverflow.com/questions/42616518/minio-hows-bucket-policy-related-to-anonymous-authorized-access

**Comment by harshavardhana** [comment]
> Any ideas on this question?
> http://stackoverflow.com/questions/42616518/minio-hows-bucket-policy-related-to-anonymous-authorized-access

@danyaljj answered.

**Comment by srghma** [comment]
How to set public bucket policy on minio using awscli (zsh)


```sh
# docs
# https://docs.minio.io/docs/aws-cli-with-minio
# https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-policy.html

MINIO_ACCESS_KEY=s3_access_key
MINIO_SECRET_KEY=s3_secret_key

docker run \
  --env MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY \
  --env MINIO_SECRET_KEY=$MINIO_SECRET_KEY \
  -d \
  -p 9000:9000 \
  --name myminio \
  minio/minio \
  server /data

POLICY='{ "Version": "2012-10-17", "Statement": [{ "Sid": "MakeItPublic", "Effect": "Allow", "Principal": "*", "Action": "s3:GetObject", "Resource": "arn:aws:s3:::mailassets/*" }] }'
docker run \
  --link myminio:minio \
  --env AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY \
  --env AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY \
  --env AWS_DEFAULT_REGION=us-east-1 \
  --entrypoint='' \
  mesosphere/aws-cli \
  /bin/sh -c "\
  aws configure set default.s3.signature_version s3v4 && \
  aws --endpoint-url http://minio:9000 s3 mb s3://mailassets && \
  aws --endpoint-url http://minio:9000 s3api put-bucket-policy --bucket mailassets --policy '$POLICY' && \
  aws --endpoint-url http://minio:9000 s3 ls"
```

after that I'm able to upload image and access it using url like `http://localhost:9000/mailassets/image.png`

**Comment by srghma** [comment]
oops, unassigned koolhead17 accidentally, dont know how to fix it

**Comment by harshavardhana** [comment]
Not a problem @srghma GitHub automatically did that.
