### ISSUE TITLE
Unable to initialize disk caching: Unsupported cache format [xl] found

### ISSUE THREAD

**Issue by conduongtong** [minio/minio#15088]
I added some test cache disk mount then restart server and get message "Unable to initialize disk caching: Unsupported cache format [xl] found". I cannot access to browser to change setting.
How can I restore setting?
Settings look like this:
![image](https://user-images.githubusercontent.com/43648013/173809415-14f38cf9-a153-408c-bc80-9282107bcea3.png)

I try to access docker container to run mc command but not found
I try with https://play.min.io:9443/ and it died too
My image: quay.io/minio/minio:RELEASE.2021-11-24T23-19-33Z

**Comment by harshavardhana** [comment]
You cannot re-use a previously used disk with cache, provide a fresh drive.

**Comment by conduongtong** [comment]
> You cannot re-use a previously used disk with cache, provide a fresh drive.

How can I restore my images or change setting back to normal?
