### ISSUE TITLE
dll files are added as fodlers

### ISSUE THREAD

**Issue by mohan636143** [minio/minio#15126]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 
The dlls uploaded are being uploaded as folders instead of files

## Expected Behavior
Dll files that are updated should be uploaded,viewed and should be read as files instead of folders

## Steps to Reproduce (for bugs)
1. Create a bucket
2. Create a folder say "main/sub"
3. Create another sub folder say "sub1/sub2"
4. Upload a dll file
5. Open file browser where the local mount path is
6. Check for the dll file in the path "main/sub/sub1/sub2". Instead of looking as file it is looking as folder.

Latest version screenshot:

![image](https://user-images.githubusercontent.com/24471825/174756917-ac08e8f2-ceca-464f-8365-d63662f56103.png)

Working Screenshot : 

![image](https://user-images.githubusercontent.com/24471825/174754635-664d8174-0a58-4318-99d4-27bf5e70e19f.png)

## Your Environment

* Version used :latest as on 21-June-2022
* The same is working fine in version : "RELEASE.2022-05-26T05-48-41Z"

**Comment by klauspost** [comment]
Later versions runs [Single-Node Single-Drive](https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html) which enables more features.

This replaces the storage as direct files.

**Comment by mohan636143** [comment]
> Later versions runs [Single-Node Single-Drive](https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html) which enables more features.
> 
> This replaces the storage as direct files.

Hi @klauspost : Is there any configuration settings that can be set so that we can see the files in legacy mode only.

By the way forgot to mention we are using minio as a docker container.
This new mode is causing difficulties so request you to suggest an alternative

**Comment by klauspost** [comment]
@mohan636143 No. You can no longer do that. Feel free to pin the version you use.
