### ISSUE TITLE
500 Internal Server Error for "mc ls --zip --recursive"

### ISSUE THREAD

**Issue by ssi444** [minio/minio#15121]
In the article https://blog.min.io/small-file-archives / describes how to view the contents of zip archives. In one of the minio installations, we use this feature (Version: 2022-01-08T03:11:54 I, 4-node cluster). And everything works fine.

We recently deployed another installation (Version: 2022-01-08T03:11:54Z, 1-node). When trying to view the contents of the archive, minio writes an error:

`mcli admin trace -a -v l1`

```
API: ListObjectsV2(bucket=test1)
Time: 19:34:44 UTC 06/20/2022
DeploymentID: e9c3c0f2-859b-42f9-80ef-251303f58029
RequestID: 16FA6B34114EFC08
RemoteHost: 172.17.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.24 mcli/RELEASE.2022-04-16T21-11-21Z
Error: unknown version (*errors.errorString)
       4: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2128:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:252:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

...
REPEATED 8 TIMES
...

API: ListObjectsV2(bucket=test1)
Time: 19:34:48 UTC 06/20/2022
DeploymentID: e9c3c0f2-859b-42f9-80ef-251303f58029
RequestID: 16FA6B3508AA8C4C
RemoteHost: 172.17.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.24 mcli/RELEASE.2022-04-16T21-11-21Z
Error: unknown version (*errors.errorString)
       4: cmd/api-errors.go:2103:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2128:cmd.toAPIError()
       2: cmd/bucket-listobjects-handlers.go:252:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```

The client outputs an error
```
mcli: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(unknown version)
```

## Expected Behavior
Returning the list of files in the archive. Moreover, if you fill in the archive again, then you can again list the files inside it. But only 1 time

## Current Behavior
Error, after the first output of the file list.

## Steps to Reproduce (for bugs)
```
$ docker pull minio/minio:RELEASE.2022-06-17T02-00-35Z
# OR
docker pull minio/minio:RELEASE.2022-01-08T03-11-54Z
$ mkdir -p minio-data
$ docker run -it --rm --name m1 -p 9000:9000 -p 9001:9001 -v $(pwd)/minio-data:/data -e MINIO_ROOT_USER=minio -e $ MINIO_ROOT_PASSWORD=miniominio minio/minio:RELEASE.2022-01-08T03-11-54Z server /data --console-address ":9001"
$ mcli alias set l1 http://127.0.0.1:9000 minio miniominio
$ mcli mb l1/test1
# create zip-file archive.zip with several files
$ FILE="err.zip"
$ mcli cp $FILE l1/test1/$FILE
$ mcli ls --zip -r l1/test1/$FILE
[2022-06-20 21:35:45 MSK]  26KiB STANDARD err.zip/err.txt
[2022-06-20 21:35:45 MSK]  16KiB STANDARD err.zip/err1.txt
$ mcli ls --zip -r l1/test1/$FILE
mcli: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(unknown version)
```

## Context
Storing a list of files for 1 day (for archived data) not as a set of individual files, but as a zip archive. If necessary, a list of files is obtained and the user is provided with a link to a specific file from the archive

## Regression
We assumed that such an error occurs only in new versions, so we deployed exactly the same version as on an already running cluster. But it didn't help. The next difference is that on a 4-node instance, minio is running without a container, and on a 1-node instance in a container. We tried to run a 1-node without a container, but it also didn't work.
Perhaps the reason is the number of nodes?

## Your Environment

* Version used (`minio --version`):
  * 2022-01-08T03:11:54Z
  * 2022-06-17T02:00:35Z
* Server setup and configuration:
* Operating System and version (`uname -a`): 
  * Linux test-polygon 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (Docker version 20.10.8, build 3967b7d)
  * Darwin iMac-Serg.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 (Docker version 20.10.16, build aa7e414)

**Comment by harshavardhana** [comment]
> docker pull minio/minio:RELEASE.2022-01-08T03-11-54Z

are you not using latest release? @ssi444

**Comment by ssi444** [comment]
> are you not using latest release? @ssi444

@harshavardhana 
We have tried the following releases:
 - 2022-01-08T03:11:54Z
 - 2022-06-17T02:00:35Z
 
The behavior of minio is the same in both cases.

**Comment by harshavardhana** [comment]
would you be able to share the zip file? @ssi444

**Comment by ssi444** [comment]
> would you be able to share the zip file? @ssi444

It can be any zip.  We created using regular macos and linux tools @harshavardhana

**Comment by klauspost** [comment]
@harshavardhana Don't we have mint for Single-Node Single-Drive? Maybe we should set it up now that it is released?

This should have been caught by [testGetObjectS3Zip](https://github.com/minio/minio-go/blob/3237a5a7c17fb7beb0607b23c6831238b118ef93/functional_tests.go#L3323)

**Comment by harshavardhana** [comment]
> @harshavardhana Don't we have mint for Single-Node Single-Drive? Maybe we should set it up now that it is released?
> 
> This should have been caught by [testGetObjectS3Zip](https://github.com/minio/minio-go/blob/3237a5a7c17fb7beb0607b23c6831238b118ef93/functional_tests.go#L3323)

We do and if is not getting caught @klauspost

**Comment by harshavardhana** [comment]
This doesn't get caught because the error happens upon second read (listing) https://github.com/minio/minio-go/blob/3237a5a7c17fb7beb0607b23c6831238b118ef93/functional_tests.go#L343

@klauspost the test validates only situation that happens on a first attempt.

**Comment by ssi444** [comment]
Everything works well. Thanks!
