### ISSUE TITLE
CopyObject: read/write on closed pipe

### ISSUE THREAD

**Issue by mathieu-jamendo** [minio/minio#15128]
Hello,

The CopyObject S3 API is failing with Minio in erasure coded mode.

## Expected Behavior
A new version of the object is created with updated metadata.

## Current Behavior
I get this error stack in the Minio log:

```
API: CopyObject
Time: Tue Jun 21 2022 08:56:55 GMT+0200 (Central European Summer Time)
DeploymentID: 3234941a-ebbb-4f7d-9133-3b56838f80cd
RequestID: 16FA96FA5C4657DF
RemoteHost: 192.168.152.12
UserAgent: Boto3/1.21.41 Python/3.10.5 Linux/4.19.0-17-cloud-amd64 Botocore/1.24.41
Error: io: read/write on closed pipe (*errors.errorString)

Backtrace: 
0: internal/logger/logger.go:278:logger.LogIf()
1: cmd/erasure-encode.go:87:cmd.(*Erasure).Encode()
2: cmd/erasure-object.go:1062:cmd.erasureObjects.putObject()
3: cmd/erasure-object.go:871:cmd.erasureObjects.PutObject()
4: cmd/erasure-sets.go:945:cmd.(*erasureSets).PutObject()
5: cmd/erasure-server-pool.go:1151:cmd.(*erasureServerPools).CopyObject()
6: cmd/object-handlers.go:1505:cmd.objectAPIHandlers.CopyObjectHandler()
7: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

Using the trace function I also see "Internal.ReadXL 403 Forbidden" messages that seem to be concomitant with the CopyObject call. The request return 500 to the client.

## Steps to Reproduce (for bugs)
1. Create a Minio cluster in erasure coding mode
2. Create a bucket with object lock and versioning enabled
3. Upload an object to the bucket
4. Try to use CopyObject to update the object metadata

Using Python boto3:

```
self.s3.copy_object(Key=key, Bucket=bucket_name,
                CopySource={"Key": key, "Bucket": bucket_name},
                Metadata={"ContentDisposition": 'attachment; filename*=UTF-8\'\'{}'.format(content_disposition)},
                MetadataDirective="REPLACE")
```

## Context
I use this API to copy an object on the same path while updating the metadata (Content-Dispostion). Versioning and object lock are enabled.

## Regression
This must be a regression since I has made a script that was used to update the objects metadata and it was working before. When I tried to run it again it didn't work anymore. Worked with ```2022-04-16T04-26-02Z```.

## Your Environment
* Version used (`minio --version`): ```2022-06-17T02:00:35Z```
* Server setup and configuration: 4 servers with 6 drives and EC:3
* Operating System and version (`uname -a`): ```5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux```

**Comment by harshavardhana** [comment]
@mathieu-jamendo please share the entire script - also please share your setup details such as how many drives etc including full command line parameters.
