### ISSUE TITLE
Prometheus receives wrong values of internode traffic 

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#15136]
## Expected Behavior
I've replaced broken drives at one of my nodes and healing process was started. After few hours of healing I've checked my Prometheus for understanding how many data transfers between nodes during this process. I have 3 nodes: minio-1, minio-2 and minio-3. Disks was replaced at minio-2. But according to statistics in Grafana I see that minio-1 and minio-3 are receiving traffic and no one node aren't sending it. 

## Current Behavior
In my opinion during healing process minio-1 and minio-3 should sending traffic and minio-2 should receiving it.

## Steps to Reproduce (for bugs)
1. Replace one of drives with empty one
2. See the "Internode traffic" diagram in Grafana.

## Regression
Don't know - never checked it before

## Your Environment
![image_2022-06-22_050925683](https://user-images.githubusercontent.com/13428863/174928165-5c03ecf8-d87f-42fa-ba55-60dd51c8d7e2.png)

* Version used (`minio --version`): minio version RELEASE.2022-05-19T18-20-59Z
* Server setup and configuration: 3 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-2.bazis.net 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> In my opinion during healing process minio-1 and minio-3 should sending traffic and minio-2 should receiving it.

First of all the internode value was kind of off and was calculating other unnecessary values. Also the logic that you are thinking is not right - all nodes will participate in healing the drive so there will always be RX/TX of some amount between all the nodes. 

However for correctness it was fixed in 

```
~  git tag --contains 7413045f0e
RELEASE.2022-06-11T19-55-32Z
RELEASE.2022-06-17T02-00-35Z
RELEASE.2022-06-20T23-13-45Z
```
