### ISSUE TITLE
Missing JWT policy claim after upgrading to RELEASE.2022-06-20T23-13-45Z

### ISSUE THREAD

**Issue by ryansun96** [minio/minio#15137]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

OIDC login that worked fine in RELEASE.2022-06-17T02-00-35Z stopped working after upgrading to RELEASE.2022-06-20T23-13-45Z.

## Expected Behavior

OIDC login should continue to work after the update.

## Current Behavior

Error: Policy claim missing from the JWT token, credentials will not be generated after successful authorization by OIDC provider (Auth0).

## Steps to Reproduce (for bugs)

1. Configure OIDC login in RELEASE.2022-06-17T02-00-35Z and verify that it's working 
2. Upgrade to RELEASE.2022-06-20T23-13-45Z
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration: docker image minio/minio
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@ryansun96 please share your entire OIDC settings please and also a sample JWT Token obtained from your IDP - if not please provide an `mc admin trace -v -a --funcname sts* alias/` output

**Comment by harshavardhana** [comment]
Closing as incomplete issue.
