### ISSUE TITLE
Failed to calculate dst hash: Forbidden: Forbidden status code: 403

### ISSUE THREAD

**Issue by bigbangus** [minio/minio#15131]
I changed my domain nameservers to use cloudflare and updated my swag nginx reverse proxy to use dns validation and run through the cloudflare API key. Everything seems to be working OK except my minio docker won't play nice with the remote rclone instance. I keep getting: "Failed to calculate dst hash: Forbidden: Forbidden status code: 403" However that same remote server has duplicati running through minio as well making backups and there is no issue using the same credentials (unchanged). Why would duplicati work fine through minio but rclone have tons of 403 errors when trying to calculate the hash? I also added my remote server IP to the whitelist in crowdsec to avoid any undesired bouncing.

## Your Environment
* Version: minio version RELEASE.2022-06-17T02-00-35Z (commit-id=55ee94bed030874c35c8adc85f2d942765231f33)
* Server setup and configuration: 
* Operating System and version: Linux UnraidBackup 5.15.46-Unraid #1 SMP Fri Jun 10 11:08:41 PDT 2022 x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux

**Comment by harshavardhana** [comment]
@bigbangus there is really no explanation of setup details, there is nothing for us to go around - are we supposed to imagine your setup?
