### ISSUE TITLE
Is there a gateway function to connect multiple clusters to one endpoint?

### ISSUE THREAD

**Issue by pjy324** [minio/minio#15156]
We would like to set up multiple MinIOs (i.e., multiple endpoints separated by regions) in Hive/HDFS.
Unfortunately, only one endpoint can be set in Hive/HDFS.

Does it have the ability to access multiple minIO clusters with one endpoint?

---------------------------------

So we're adding a function to redirect based on bucket path, using nginx.
When inquiring about S3API, I want to divide it into prefixes (ep1,ep2) and redirect it to each minio endpoint. 

1. Configured test cluster and nginx server
- nginx : xxx.xxx.xxx.0:9000
- minio endpoint 1 : xxx.xxx.xxx.1:9000
(bucket : test, key : test/test1.txt)
- minio endpoint 2 : xxx.xxx.xxx.2:9000
(bucket : test, key : test/test2.txt)

2. The Nginx Config is set as follows

For example, the following
- hdfs dfs -ls s3a://ep1.test/ --> I want to access the test bucket of minio endpoint1
- hdfs dfs -ls s3a://ep2.test/ --> I want to access the test bucket of minio endpoint2

```
location ~* ^/ep1.(.*) {
                rewrite ^/ep1.(.*) /$1 break;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;

                proxy_http_version     1.1;

                proxy_buffering        off;
                proxy_intercept_errors on;

                proxy_set_header        Connection '';

                proxy_pass_header       Authorization;
                proxy_pass_header       x-amz-date;


                proxy_pass             http://xxx.xxx.xxx.1:9000;
}
```

3. Attempted to execute commands in HDFS.
  - hdfs dfs -ls s3a://ep1.test/
The minio audit logs has 403,400 errors

**Comment by harshavardhana** [comment]
No there is no such thing and it is out of scope for us.
