### ISSUE TITLE
Possible race condition on delete of empty prefix

### ISSUE THREAD

**Issue by jensmartin** [minio/minio#15157]
Possible race condition on empty prefix / folder under heavy delete / put / copy operations on the same prefix.

This is similar to the issue reported here: 
https://github.com/minio/minio/discussions/14954

## Expected Behavior
Copy and put operations should not fail because of Minio internally deleting empty prefixes.

## Current Behavior
Copy and put operations fail with 404 when the prefix is empty  for a very short while at almost the same time.

Example of error logged by Minio when this happens:

API: CopyObject
DeploymentID: 35d43a28-ca71-4e80-b675-fa0a48dcecc1
Host: minio.production.svc.cluster.local:9000
UserAgent: aws-sdk-java/2.17.197 Linux/5.4.0-107-generic OpenJDK_64-Bit_Server_VM/11.0.15+10-LTS Java/11.0.15 scala/2.13.8 kotlin/1.6.21-release-334(1.6.21) vendor/Azul_Systems__Inc. io/sync http/Apache cfg/retry-mode/legacy

Error: file not found (cmd.StorageErr)
6: internal/logger/logger.go:278:logger.LogIf()
5: cmd/fs-v1-helpers.go:360:cmd.fsRenameFile()
4: cmd/fs-v1.go:1112:cmd.(*FSObjects).putObject()
3: cmd/fs-v1.go:690:cmd.(*FSObjects).CopyObject()
2: cmd/object-handlers.go:1505:cmd.objectAPIHandlers.CopyObjectHandler()
1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()

API: PutObject
DeploymentID: 35d43a28-ca71-4e80-b675-fa0a48dcecc1
Host: minio.production.svc.cluster.local:9000
UserAgent: aws-sdk-java/2.17.197 Linux/5.4.0-107-generic OpenJDK_64-Bit_Server_VM/11.0.15+10-LTS Java/11.0.15 scala/2.13.8 kotlin/1.6.21-release-334(1.6.21) vendor/Azul_Systems__Inc. io/sync http/Apache cfg/retry-mode/legacy

Error: file not found (cmd.StorageErr)
6: internal/logger/logger.go:278:logger.LogIf()
5: cmd/fs-v1-helpers.go:360:cmd.fsRenameFile()
4: cmd/fs-v1.go:1112:cmd.(*FSObjects).putObject()
3: cmd/fs-v1.go:1017:cmd.(*FSObjects).PutObject()
2: cmd/object-handlers.go:1834:cmd.objectAPIHandlers.PutObjectHandler()
1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()

## Possible Solution
Lock the prefix before deletion so that new put /copy operations would recreate it

## Steps to Reproduce (for bugs)
We only observe this under parallel operations (100-200 per second) on the same prefix, so creating a generic reproducer is not that easy.
Based on our logs this is a very simplified version of what happens (when these type of operations are running in parallel):

Put prefixA/objectB
Delete prefixA/objectB
Minio internally deletes prefixA
Put prefixA/objectC - 404

## Context
We are using Minio as distributed file storage, all files are normally short lived and we have rapid puts and deletes of objects.

## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2022-06-17T02-00-35Z
* Server setup and configuration: Minio helm install on Kubernetes - Running on Ubuntu 20.04
* Operating System and version (`uname -a`): Linux minio-645749dccd-rzk2v 5.4.0-107-generic 121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@jensmartin you are using a legacy backend now, please plan to migrate to erasure code single drive mode setup a fresh volume and then mc mirror your content from existing setup.

We won't be further improving on the legacy backend anymore.

**Comment by jensmartin** [comment]
Thanks @harshavardhana, we will upgrade and re-test.
Is there any easy way to see that we are running with the erasure code backend?

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana, we will upgrade and re-test. Is there any easy way to see that we are running with the erasure code backend?

You are not because of this 

```
Error: file not found (cmd.StorageErr)
6: internal/logger/logger.go:278:logger.LogIf()
5: cmd/fs-v1-helpers.go:360:cmd.fsRenameFile()
4: cmd/fs-v1.go:1112:cmd.(*FSObjects).putObject()
3: cmd/fs-v1.go:1017:cmd.(*FSObjects).PutObject()
2: cmd/object-handlers.go:1834:cmd.objectAPIHandlers.PutObjectHandler()
1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

You can check `/backend/.minio.sys/format.json`
