### ISSUE TITLE
use user and password in the below command to login minio, but failed

### ISSUE THREAD

**Issue by chenbodeng719** [minio/minio#15153]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

use user and password in the below command to login minio
```
helm install --namespace minio --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio
```

## Current Behavior

use the above command, bud fail to login

## Possible Solution

use user and password in the below command is ok
```
helm install --namespace minio --set accessKey=rootuser,secretKey=rootpass123 --generate-name minio/minio
```
maybe the wiki need to be updated.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version 8.0.10
* Server setup and configuration:
* Operating System and version (`uname -a`): Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@chenbodeng719 don't know what this issue is about - I can definitely login via rootUser

```
kubectl create secret generic my-minio-secret --from-literal=rootUser=foobarbaz --from-literal=rootPassword=foobarbazqux
```

You need to first create this and then

```
helm install --set existingSecret=my-minio-secret minio/minio
```

**Comment by chenbodeng719** [comment]
@harshavardhana Nope, the secret file still needs accessKey and secretKey instead of rootUser and rootPassword. I tried rootUser, it doesn't work. The wiki would mislead people.

**Comment by harshavardhana** [comment]
> @harshavardhana Nope, the secret file still needs accessKey and secretKey instead of rootUser and rootPassword. I tried rootUser, it doesn't work. The wiki would mislead people.

Our helm MinIO release v4.0.2 @chenbodeng719 you are using 8.0.10 which is an older deprecated helm chart.

https://github.com/minio/minio/tree/master/helm/minio read the docs properly.

**Comment by chenbodeng719** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/104059106/175197118-5db47786-069d-43f1-93a3-1155f0cbba1e.png">

I search the version, can't find 4.0.2?

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/tree/master/helm/minio#configure-minio-helm-repo

**Comment by chenbodeng719** [comment]
thx a lot. The minio repo on the server was set by my colleague when he installed kubeflow.

**Comment by chenbodeng719** [comment]
@harshavardhana Hi, do you know how minio get the old data location after expanding the cluster? I know that there is hash function to do it.But after explanding, I think the hash function wiil calculate a new loction? Do I misunderstand it?

**Comment by chenbodeng719** [comment]
I guess there is a parallel request to all the pools to get where the old data is. After this, hash function is used for which set is used for the old data in one pool.
