### ISSUE TITLE
Service Account - accessKey Max Length issue

### ISSUE THREAD

**Issue by dharapvj** [minio/minio#15164]
While minio does not check fox max length for access keys of regular users, it still checks the max length for accesskeys for new service accounts. Perhaps this is a oversight. There is no reason why access keys for service account should be restricts to maximum 20 characters.

## Expected Behavior

User should be able to create service account with accessKey longer than 20 characters.

## Current Behavior

User gets error below error when accesskey longer than 20 characters is specified.
```
mc: <ERROR> Unable to add a new service account. The access key is invalid. (access key length should be between 3 and 20)
```

## Possible Solution

[This code block](https://github.com/minio/minio/blob/master/internal/auth/credentials.go#L243-L245) should stop checking for max length. This code block is invoked as part of new svc account creation [here](https://github.com/minio/minio/blob/master/cmd/iam.go#L935)

## Steps to Reproduce (for bugs)

1. Provide access key of 21 characters to get the error.
`mc admin user svcacct add --debug --access-key "e12345678901234567890" --secret-key "testsecret2" minio <existing user>`
2. Provide access key of 20 characters to get svc account created successfully.
`mc admin user svcacct add --debug --access-key "e1234567890123456789" --secret-key "testsecret2" minio <existing user>`

## Your Environment

* Version used (`minio --version`): RELEASE.2022-03-03T21-21-16Z
* Server setup and configuration: Kubernetes based minio-ha operator
* Operating System and version (`uname -a`): Ubuntu 20.04

**Comment by harshavardhana** [comment]
That is correct we do not want you to create accessKeys bigger than 20 characters - the restriction is on purpose to match AWS S3's AccessKey, SecretKey lengths.
