### ISSUE TITLE
Cleanup not adjustable

### ISSUE THREAD

**Issue by jensmartin** [minio/minio#15162]
After setting up a single node with erasure coding we are not able to adjust the cleanup interval.
The .tmp/trash folder fills up and disk runs out of disk space.

## Expected Behavior
When setting either MINIO_DELETE_CLEANUP_INTERVAL or using mc:
`mc admin config set api delete_cleanup_interval`
We expect cleanup to happen on that interval

## Current Behavior
Cleanup only happens every 5 minutes

## Steps to Reproduce (for bugs)
Set either MINIO_DELETE_CLEANUP_INTERVAL=30s env variable or mc admin config set api delete_cleanup_interval=30s
Put and delete data to minio and observe that cleanup only happens after 5 minutes.

## Context
Output of json part of xl.meta:
`{"api":{"_":[{"key":"requests_max","value":"0"},{"key":"requests_deadline","value":"10s"},{"key":"cluster_deadline","value":"10s"},{"key":"cors_allow_origin","value":"*"},{"key":"remote_transport_deadline","value":"2h"},{"key":"list_quorum","value":"strict"},{"key":"replication_workers","value":"250"},{"key":"replication_failed_workers","value":"8"},{"key":"transition_workers","value":"100"},{"key":"stale_uploads_cleanup_interval","value":"6h"},{"key":"stale_uploads_expiry","value":"24h"},{"key":"delete_cleanup_interval","value":"30s"},{"key":"disable_odirect","value":"off"},{"key":"gzip_objects","value":"off"}]},"audit_kafka":{"_":[{"key":"enable","value":"off"},{"key":"topic","value":""},{"key":"brokers","value":""},{"key":"sasl_username","value":""},{"key":"sasl_password","value":""},{"key":"sasl_mechanism","value":"plain"},{"key":"client_tls_cert","value":""},{"key":"client_tls_key","value":""},{"key":"tls_client_auth","value":"0"},{"key":"sasl","value":"off"},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"version","value":""}]},"audit_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""},{"key":"queue_size","value":"100000"}]},"cache":{"_":[{"key":"drives","value":""},{"key":"exclude","value":""},{"key":"expiry","value":"90"},{"key":"quota","value":"80"},{"key":"after","value":"0"},{"key":"watermark_low","value":"70"},{"key":"watermark_high","value":"80"},{"key":"range","value":"on"},{"key":"commit","value":""}]},"callhome":{"_":[{"key":"enable","value":"off"},{"key":"frequency","value":"24h"}]},"compression":{"_":[{"key":"enable","value":"off"},{"key":"allow_encryption","value":"off"},{"key":"extensions","value":".txt,.log,.csv,.json,.tar,.xml,.bin"},{"key":"mime_types","value":"text/*,application/json,application/xml,binary/octet-stream"}]},"credentials":{"_":[{"key":"access_key","value":"minioadmin"},{"key":"secret_key","value":"minioadmin"}]},"etcd":{"_":[{"key":"endpoints","value":""},{"key":"path_prefix","value":""},{"key":"coredns_path","value":"/skydns"},{"key":"client_cert","value":""},{"key":"client_cert_key","value":""}]},"heal":{"_":[{"key":"bitrotscan","value":"off"},{"key":"max_sleep","value":"1s"},{"key":"max_io","value":"100"}]},"identity_ldap":{"_":[{"key":"server_addr","value":""},{"key":"user_dn_search_base_dn","value":""},{"key":"user_dn_search_filter","value":""},{"key":"group_search_filter","value":""},{"key":"group_search_base_dn","value":""},{"key":"tls_skip_verify","value":"off"},{"key":"server_insecure","value":"off"},{"key":"server_starttls","value":"off"},{"key":"lookup_bind_dn","value":""},{"key":"lookup_bind_password","value":""}]},"identity_openid":{"_":[{"key":"enable","value":""},{"key":"display_name","value":""},{"key":"config_url","value":""},{"key":"client_id","value":""},{"key":"client_secret","value":""},{"key":"claim_name","value":"policy"},{"key":"claim_userinfo","value":""},{"key":"role_policy","value":""},{"key":"claim_prefix","value":""},{"key":"redirect_uri","value":""},{"key":"redirect_uri_dynamic","value":"off"},{"key":"scopes","value":""}]},"identity_plugin":{"_":[{"key":"url","value":""},{"key":"auth_token","value":""},{"key":"role_policy","value":""},{"key":"role_id","value":""}]},"identity_tls":{"_":[{"key":"skip_verify","value":"off"}]},"logger_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""},{"key":"queue_size","value":"100000"}]},"notify_amqp":{"_":[{"key":"enable","value":"off"},{"key":"url","value":""},{"key":"exchange","value":""},{"key":"exchange_type","value":""},{"key":"routing_key","value":""},{"key":"mandatory","value":"off"},{"key":"durable","value":"off"},{"key":"no_wait","value":"off"},{"key":"internal","value":"off"},{"key":"auto_deleted","value":"off"},{"key":"delivery_mode","value":"0"},{"key":"publisher_confirms","value":"off"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""}]},"notify_elasticsearch":{"_":[{"key":"enable","value":"off"},{"key":"url","value":""},{"key":"format","value":"namespace"},{"key":"index","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"},{"key":"username","value":""},{"key":"password","value":""}]},"notify_kafka":{"_":[{"key":"enable","value":"off"},{"key":"topic","value":""},{"key":"brokers","value":""},{"key":"sasl_username","value":""},{"key":"sasl_password","value":""},{"key":"sasl_mechanism","value":"plain"},{"key":"client_tls_cert","value":""},{"key":"client_tls_key","value":""},{"key":"tls_client_auth","value":"0"},{"key":"sasl","value":"off"},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""},{"key":"version","value":""}]},"notify_mqtt":{"_":[{"key":"enable","value":"off"},{"key":"broker","value":""},{"key":"topic","value":""},{"key":"password","value":""},{"key":"username","value":""},{"key":"qos","value":"0"},{"key":"keep_alive_interval","value":"0s"},{"key":"reconnect_interval","value":"0s"},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_mysql":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"dsn_string","value":""},{"key":"table","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"},{"key":"max_open_connections","value":"2"}]},"notify_nats":{"_":[{"key":"enable","value":"off"},{"key":"address","value":""},{"key":"subject","value":""},{"key":"username","value":""},{"key":"password","value":""},{"key":"token","value":""},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"cert_authority","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""},{"key":"ping_interval","value":"0"},{"key":"streaming","value":"off"},{"key":"streaming_async","value":"off"},{"key":"streaming_max_pub_acks_in_flight","value":"0"},{"key":"streaming_cluster_id","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_nsq":{"_":[{"key":"enable","value":"off"},{"key":"nsqd_address","value":""},{"key":"topic","value":""},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_postgres":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"connection_string","value":""},{"key":"table","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"},{"key":"max_open_connections","value":"2"}]},"notify_redis":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"address","value":""},{"key":"key","value":""},{"key":"password","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""}]},"policy_opa":{"_":[{"key":"url","value":""},{"key":"auth_token","value":""}]},"policy_plugin":{"_":[{"key":"url","value":""},{"key":"auth_token","value":""}]},"region":{"_":[{"key":"name","value":""}]},"scanner":{"_":[{"key":"delay","value":"10"},{"key":"max_wait","value":"15s"},{"key":"cycle","value":"1m"}]},"site":{"_":[{"key":"name","value":""},{"key":"region","value":""}]},"storage_class":{"_":null},"subnet":{"_":[{"key":"license","value":""},{"key":"api_key","value":""},{"key":"proxy","value":""}]}}
`

## Your Environment

* Version used (`minio --version`): RELEASE.2022-06-20T23-13-45Z
* Server setup and configuration: Minio helm install on Kubernetes - Running on Ubuntu 20.04
* Operating System and version (`uname -a`): Linux minio-645749dccd-rzk2v 5.4.0-107-generic 121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You run out disk space in 5mins? - what kind of storage do you have?

**Comment by jensmartin** [comment]
In this setup we have 100 GB SSD disk. 
Running with legacy backend we never crossed 2 GB of usage, so it should be plenty. 

We are doing heavy writes and deletes of short lived objects.

**Comment by harshavardhana** [comment]
> When setting either MINIO_DELETE_CLEANUP_INTERVAL or using mc:

I do not know where you got this ENV value the key is actually

```
MINIO_API_DELETE_CLEANUP_INTERVAL=30s
```

Also the value is set on the second attempt first attempt is always 5minutes

**Comment by harshavardhana** [comment]
So it is working as expected just tested locally.

**Comment by jensmartin** [comment]
I have corrected the ENV variable but still do not see any increased cleanups. 
Would appreciate if you could give some more guidence on how to debug this?
When you say the first attempt is always 5 minutes, is this 5 minutes after startup or 5 minutes after a file have been put in trash?

![image](https://user-images.githubusercontent.com/763227/175390860-ec37195b-19ef-432e-8df6-6191257ec823.png)


Output of the env in the container:
```
kubectl exec -it minio-749b748fff-65xtp -- env | grep MINIO_API
MINIO_API_DELETE_CLEANUP_INTERVAL=30s
```

**Comment by harshavardhana** [comment]
> When you say the first attempt is always 5 minutes, is this 5 minutes after startup or 5 minutes after a file have been put in trash?

The initial run is always after 5mins, subsequently, after that, it will be whatever you configured - the interval is between runs after the previous completion.

**Comment by harshavardhana** [comment]
I added print statements

```
MINIO_API_DELETE_CLEANUP_INTERVAL=30s minio server ~/test
First attempt 5m0s
Automatically configured API requests per node based on available memory on the system: 130
Finished loading IAM sub-system (took 0.0s of 0.0s to load data).
Status:         1 Online, 0 Offline. 
API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://127.0.0.1:9000                     
RootUser: minioadmin 
RootPass: minioadmin 

Console: http://10.0.0.185:36023 http://172.17.0.1:36023 http://172.19.0.1:36023 http://172.20.0.1:36023 http://127.0.0.1:36023           
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.185:9000 minioadmin minioadmin

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (36023), please use --console-address ":PORT" to choose a static port.
Next attempt 30s
Next attempt 30s
...
```

As you can see the 30s is honored after 5mins

**Comment by harshavardhana** [comment]
NOTE: The cleanup is serial it cleans up one object at a time so in-case you have very high ingest and deletes, this won't work for you. You also have 100g disk space its not a practical setup TBH.

**Comment by chrned** [comment]
> NOTE: The cleanup is serial it cleans up one object at a time so in-case you have very high ingest and deletes, this won't work for you.

@harshavardhana Does this mean that the erasure code single drive mode is generally not recommended for use cases with a high rate of writes and deletes?

**Comment by harshavardhana** [comment]
> > NOTE: The cleanup is serial it cleans up one object at a time so in-case you have very high ingest and deletes, this won't work for you.
> 
> @harshavardhana Does this mean that the erasure code single drive mode is generally not recommended for use cases with a high rate of writes and deletes?

Not really you just need sufficient space, run it in a more practical scenario such as have some wiggle room.
