### ISSUE TITLE
Publish GitHub release after and only when release artifacts has been created

### ISSUE THREAD

**Issue by invidian** [minio/minio#15176]
**Is your feature request related to a problem? Please describe.**

As a user performing regular updates, I use release notifications as a tracker for new versions of minio and when I need to update my fleet.

At the moment, when I get notification about the latest release, the Docker images are not ready to pull yet, often for a longer period, which makes me periodically check if the images are pullable finally before I update my fleet.

**Describe the solution you'd like**

It would be great if the release process could do the following:
1. Push release tag to trigger release pipelines
2. Wait for release pipelines to finish, publishing all Docker images etc. (optionally also create a draft GitHub release)
3. Publish a release as a last step of release pipeline.

**Additional context**

This is similar to https://github.com/projectcalico/calico/issues/6048.

As GitHub allows users to subscribe to project releases only, I think it should be treated as any other communication channel like mailing list or a newsletter. When getting news about a new release, potentially bringing some new features I've been waiting for, I'd expect everything to be ready to use it. Having no release artifacts at this time seem counter intuitive and a poor user experience to me.

**Comment by harshavardhana** [comment]
> As GitHub allows users to subscribe to project releases only, I think it should be treated as any other communication channel like mailing list or a newsletter. When getting news about a new release, potentially bringing some new features I've been waiting for, I'd expect everything to be ready to use it. Having no release artifacts at this time seem counter intuitive and a poor user experience to me.

Agreed, we generally follow this pattern anyways.

**Comment by invidian** [comment]
Hm, but this is not the case right now, right? At least latest release is not pullable for me:
```console
$ docker pull minio/minio:RELEASE.2022-06-25T15-50-16Z
Error response from daemon: manifest for minio/minio:RELEASE.2022-06-25T15-50-16Z not found: manifest unknown: manifest unknown
```

**Comment by harshavardhana** [comment]
> ```
> $ docker pull minio/minio:RELEASE.2022-06-25T15-50-16Z
> Error response from daemon: manifest for minio/minio:RELEASE.2022-06-25T15-50-16Z not found: manifest unknown: manifest unknown
> ```

Seems to be pullable for me.

**Comment by invidian** [comment]
The release https://github.com/minio/minio/releases/tag/RELEASE.2022-06-25T15-50-16Z has been published at `2022-06-26T16:11:59Z`, while https://hub.docker.com/layers/minio/minio/minio/RELEASE.2022-06-25T15-50-16Z/images/sha256-819cb0e0361491e6f2f99cdac5f17d5d695a55e9d84be857e82600c017c3ffd6?context=explore shows that the image has been pushed at `Jun 26, 2022 at 6:32 pm`. I reported this issue at `2022-06-26T16:20:35Z` so exactly between this two timestamps.

The image is now pullable, yes, but that's not the point here.

**Comment by harshavardhana** [comment]
> The release https://github.com/minio/minio/releases/tag/RELEASE.2022-06-25T15-50-16Z has been published at `2022-06-26T16:11:59Z`, while https://hub.docker.com/layers/minio/minio/minio/RELEASE.2022-06-25T15-50-16Z/images/sha256-819cb0e0361491e6f2f99cdac5f17d5d695a55e9d84be857e82600c017c3ffd6?context=explore shows that the image has been pushed at `Jun 26, 2022 at 6:32 pm`. I reported this issue at `2022-06-26T16:20:35Z` so exactly between this two timestamps.

The published image is UTC - Docker hub shows your local TZ.

**Comment by invidian** [comment]
Ah, sorry about that, wrong copy paste from the browser. Still, my point stands:
```console
$ gh release view -R minio/minio --json createdAt -q .createdAt RELEASE.2022-06-25T15-50-16Z
2022-06-26T16:08:32Z
$ docker pull minio/minio:RELEASE.2022-06-25T15-50-16Z && docker inspect minio/minio:RELEASE.2022-06-25T15-50-16Z | jq -r '.[0].Created'
RELEASE.2022-06-25T15-50-16Z: Pulling from minio/minio
Digest: sha256:4dea81aab916ce6c3c5d5284cd1a86214fb89d56e8a2733d37704d4394318575
Status: Image is up to date for minio/minio:RELEASE.2022-06-25T15-50-16Z
docker.io/minio/minio:RELEASE.2022-06-25T15-50-16Z
2022-06-26T16:29:18.617005146Z
```

**Comment by harshavardhana** [comment]
Ideally, we push images before we add a release tag on GitHub - it was done the other way round today. However, we tend to follow first push images and then add a GitHub release tag. 

That's why I closed the issue because I am aware what happened.

**Comment by invidian** [comment]
Tag and the actual release publishing are two independent actions. Do you think this could be improved? If so, I think this issue should be reopened.

**Comment by harshavardhana** [comment]
> Tag and the actual release publishing are two independent actions. Do you think this could be improved? If so, I think this issue should be reopened.

We do tags, and then we manually write release notes. If you rely on tags then it won't work for you - you should look for GitHub releases (i.e release notes attached) 

No, we won't be changing anything that we are doing today. What we always want to make sure is that before we write (add a github release with release notes)  we have containers/artifacts already pushed.

**Comment by invidian** [comment]
>We do tags, and then we manually write release notes.

Make sense.

>If you rely on tags then it won't work for you - you should look for GitHub releases (i.e release notes attached)

Make sense as well. GitHub only sends notifications for releases, not pushed tags, so all good here :+1: 

>No, we won't be changing anything that we are doing today. What we always want to make sure is that before we write (add a github release with release notes) we have containers/artifacts already pushed.

Well, just making sure seem like a (positive) change to a process :wink: Thanks! Do you have some documentation about the release process where this could be added perhaps? I hope manual verification will be sufficient then.

**Comment by invidian** [comment]
I see images are available at the time of the release, thanks again for taking it into account!

**Comment by invidian** [comment]
It seems sometimes this isn't the case:
```console
$ date -u; docker pull minio/minio:RELEASE.2023-01-02T09-40-09Z
Tue  3 Jan 11:13:28 UTC 2023
Error response from daemon: manifest for minio/minio:RELEASE.2023-01-02T09-40-09Z not found: manifest unknown: manifest unknown
```

**Comment by invidian** [comment]
```console
$ date -u; docker pull minio/minio:RELEASE.2023-01-25T00-19-54Z
Wed 25 Jan 09:59:10 UTC 2023
Error response from daemon: manifest for minio/minio:RELEASE.2023-01-25T00-19-54Z not found: manifest unknown: manifest unknown
```

**Comment by harshavardhana** [comment]
> ```
> $ date -u; docker pull minio/minio:RELEASE.2023-01-25T00-19-54Z
> Wed 25 Jan 09:59:10 UTC 2023
> Error response from daemon: manifest for minio/minio:RELEASE.2023-01-25T00-19-54Z not found: manifest unknown: manifest unknown
> ```

this was a mistake in release process @invidian - pushing them now.

**Comment by invidian** [comment]
```console
$ date -u; docker pull minio/minio:RELEASE.2023-11-06T22-26-08Z
Wed  8 Nov 09:21:33 UTC 2023
Error response from daemon: manifest for minio/minio:RELEASE.2023-11-06T22-26-08Z not found: manifest unknown: manifest unknown
```

**Comment by harshavardhana** [comment]
Looks like a network error pushing again.
