### ISSUE TITLE
Spammy logs with "At least one of the pre-conditions you specified did not hold"

### ISSUE THREAD

**Issue by mathieu-jamendo** [minio/minio#15179]
## NOTE
Hello,

I just upgraded from 2022-06-20T23-13-45Z to 2022-06-25T15:50:16Z.

Since then I have an important number of log lines looking like this:

```
API: GetObject
Time: Mon Jun 27 2022 08:42:27 GMT+0200 (Central European Summer Time)
DeploymentID: 3234941a-ebbb-4f7d-9133-3b56838f80cd
RequestID: 16FC6DABD7C24457
RemoteHost: 192.168.152.12
UserAgent: Mozilla/5.0 (Linux; Android 11; CPH2269 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36
Error: At least one of the pre-conditions you specified did not hold (cmd.PreConditionFailed)

Backtrace: 
0: internal/logger/logger.go:278:logger.LogIf()
1: cmd/api-errors.go:2123:cmd.toAPIErrorCode()
2: cmd/api-errors.go:2148:cmd.toAPIError()
3: cmd/object-handlers.go:424:cmd.objectAPIHandlers.getObjectHandler()
4: cmd/object-handlers.go:604:cmd.objectAPIHandlers.GetObjectHandler()
5: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()`
```

They weren't there before, but I don't see any impact on my workload yet. If there is no impact, then this should be a debug log and shouldn't clutter the logs of a production setup. If there is an impact then we face a regression since the last version.

## Expected Behavior
These log lines doesn't appear anymore.

## Current Behavior
The logs are cluttered with these lines.

## Possible Solution
Set this type of log as a debug log if this isn't the symptom of a regression, fix the regression otherwise.

## Steps to Reproduce (for bugs)
Upgrade from 2022-06-20T23-13-45Z to 2022-06-25T15:50:16Z.
Serve files to clients with Cache-Control header enabled.

## Regression
Regression since last version, possibly related to https://github.com/minio/minio/commit/1cfb03fb7431d3d530ed0703527f571b49779a5d

## Your Environment
Version used (`minio --version`): 2022-06-25T15:50:16Z

**Comment by vadmeste** [comment]
Taking a look
