### ISSUE TITLE
Helm Chart: service port set to minioAPIPort

### ISSUE THREAD

**Issue by cabal-daniel** [minio/minio#15175]
## NOTE
Currently it's hard set to port 9000 but I believe it should be set to MinioAPIPort which is the containerPort of the deployment.
https://github.com/minio/minio/blob/master/helm/minio/templates/service.yaml#L39

If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Feel free to send a PR
