### ISSUE TITLE
Expanded MinIO can fail to initialize due to DNSError

### ISSUE THREAD

**Issue by haslersn** [minio/minio#15189]
I think this already came up in issue #13067 (deleted).

In a MinIO cluster with at least two pools, if the DNS name for one of the replicas doesn't resolve, then the replicas belonging to a different pool fail to initialize. According to the log, this seems to be due to a DNSError. When starting the MinIO cluster up, it fails to initialize as a whole.

This problem affects Kubernetes setups (including those created by minio-operator), where MinIO replicas are Pods, in the following way: When a Kubernetes node with required local volumes is down or a Pod's volumes cannot be mounted for some other reason, then the Pod cannot be created. As long as the Pod is not created, the Pod's name will not resolve through Kubernetes's DNS. Hence, the MinIO cluster fails to initialize as long as not all Pods are created successfully.

The issue only affects deployments with at least two pools, because the DNSError only appears on replicas/Pods belonging to a different pool.

## Expected Behavior

A failure to resolve the name of a MinIO replica should have the same effect as a failure to reach the replica's IP. That is, it should be treated gracefully, just as a failure to reach a replica's IP is treated gracefully already.

## Current Behavior

A failure to resolve the name of a MinIO replica can delay or entirely prevent cluster initialization.

## Context

One setup where this occurs is the setup from this comment: https://github.com/minio/minio/issues/14868#issuecomment-1118472489

## Your Environment

* Version used: 2022-06-20T23:13:45Z

**Comment by harshavardhana** [comment]
@haslersn we have operator that works fine with statefulset with expansion - and IP resolution.

Not sure what this issue is about. DNS must resolve that is required and it won't change.

Pools are not optional entities they have to be present to have a consistent view of a namespace, they can't be gracefully rejected as non existent entities.

This issue is out of scope for us.

**Comment by haslersn** [comment]
This issue isn't about the case where a whole pool doesn't resolve. It's about the case, where we have a pool consisting of multiple servers (e.g. 4) and only a single server's name doesn't resolve.

For instance, in a MinIO setup created by minio-operator with a pool of 4 Pods where only 3 can be successfully created, it looks like this:

```
$ host minio-ss-0-0.minio.s3.svc.cluster.local
minio-ss-0-0.minio.s3.svc.cluster.local has address 10.100.34.51

$ host minio-ss-0-1.minio.s3.svc.cluster.local
minio-ss-0-1.minio.s3.svc.cluster.local has address 10.100.100.152

$ host minio-ss-0-2.minio.s3.svc.cluster.local
minio-ss-0-2.minio.s3.svc.cluster.local has address 10.100.164.154

$ host minio-ss-0-3.minio.s3.svc.cluster.local
Host minio-ss-0-3.minio.s3.svc.cluster.local not found: 3(NXDOMAIN)
[1]    3150 exit 1     host minio-ss-0-3.minio.s3.svc.cluster.local
```

When there is a second pool, then all Pods in that pool fail to initialize, because they cannot resolve `minio-ss-0-3.minio.s3.svc.cluster.local`, even though they can resolve the other 3 names from the first pool.

**Comment by harshavardhana** [comment]
That is expected behavior for now on k8s environment.

**Comment by haslersn** [comment]
> That is expected behavior for now on k8s environment.

The [distributed quickstart guide](https://docs.min.io/docs/distributed-minio-quickstart-guide.html) explicitly mentions high availability and MinIO [markets itself](https://min.io/) as “Native to Kubernetes”. With that in mind, are you sure that you want the expected behavior on Kubernetes to be not highly available?

**Comment by harshavardhana** [comment]
> The [distributed quickstart guide](https://docs.min.io/docs/distributed-minio-quickstart-guide.html) explicitly mentions high availability and MinIO [markets itself](https://min.io/) as “Native to Kubernetes”. With that in mind, are you sure that you want the expected behavior on Kubernetes to be not highly available?

@haslersn it is highly available, you are conflating many things here. What you did is delete a statefulset which leads to deletion of DNS for all pods and all pods have to reinitialize. 

If a single pod is gone or down there will be no problem. Let me lock this conversation as this is not going anywhere.
