### ISSUE TITLE
console login forwarding to wrong port

### ISSUE THREAD

**Issue by Someone275** [minio/minio#15190]
So im running docker version lastest pull
starting docker
docker run -p 9000:9000 -p 9001:9001 --name minio -e "MINIO_SERVER_URL=https://5.domain.com" -e "MINIO_ROOT_USER=login" -e "MINIO_ROOT_PASSWORD=secure" -v /etc/letsencrypt/live/5.domain.com:/root/.minio/certs -v /storage/S3docker:/data quay.io/minio/minio server /data --console-address ":9001" --address ":9000"

so when i go to my browser 5.domain.com:9001 i get my login screen
i put in login info
click login i get
Post "https://5.domain.com/": dial tcp x.x.x.5:443: i/o timeout

its sending out to the wrong port the machine can't have port 443 open as it used for other services at this time

so what are the option for a fix that will let this work on a none standard port
as soon as i add MINIO_SERVER_URL it forces it to try port 443 if i remove https to http then it forces port 80
all of witch won't work for us

**Comment by harshavardhana** [comment]
@Someone275 please fix your MINIO_SERVER_URL to point to right port which is exposed.
