### ISSUE TITLE
Uploading 25g files by slices is severely blocked in the fs.appendFileMapMu.Lock() of the backgroundappend function

### ISSUE THREAD

**Issue by liangfujian** [minio/minio#15193]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
fs.appendFileMapMu.Lock() is blocked or  file.Lock() is blocked  very sort

## Current Behavior
fs.appendFileMapMu.Lock() is blocked or  file.Lock() is blocked  very long
![1656474938962](https://user-images.githubusercontent.com/50279811/176348142-f3a2c443-2b25-435b-9d1a-b93fd9516834.png)

## Steps to Reproduce (for bugs)
1.s3cmd put file25G s3://test1 --debug

## Your Environment

* Version used (`minio --version`): minio version development.goget
* Server setup and configuration:
* Operating System and version (`uname -a`):linux x86_64

**Comment by harshavardhana** [comment]
@liangfujian please migrate to using single drive erasure mode, instead of FS mode which is deprecated. 

> fs.appendFileMapMu.Lock() is blocked or file.Lock() is blocked very long

This is waiting on purpose because it's coalescing the writes into a single file.

**Comment by liangfujian** [comment]
But the waiting time is too long. 5g files will be blocked for half an hour
