### ISSUE TITLE
Issue: Notification s3.object.key

### ISSUE THREAD

**Issue by joaofranciscosantos** [minio/minio#15200]
## Expected Behavior

In the following example, under `Records[0].s3.object.key` I should get `users/ABC` and not `users%2FABC`.
```json
{"EventName":"s3:ObjectCreated:Post","Key":"","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"","eventName":"s3:ObjectCreated:Post","userIdentity":{"principalId":""},"requestParameters":{"principalId":"","region":"","sourceIPAddress":""},"responseElements":{"x-amz-request-id":"","x-minio-deployment-id":"","x-minio-origin-endpoint":""},"s3":{"s3SchemaVersion":"1.0","configurationId":"","bucket":{"name":"","ownerIdentity":{"principalId":""},"arn":""},"object":{"key":"users%2FABC","size":132,"eTag":"","contentType":"image/png","userMetadata":{"X-Amz-Meta-Id-Pod":"0","X-Amz-Meta-Id-Session":"c6de5991-199c","X-Amz-Meta-Source":"1","content-type":"image/png"},"sequencer":""}},"source":{"host":"","port":"","userAgent":""}}]}
```

## Current Behavior

Minio is sending a notification with escaped key, after an object is created in bucket. A GET operation with this key will result in an error since path is being escaped.

I tried to trace the origin of error and it seems is coming from this repository. 
https://github.com/minio/minio/blob/c7ed6eee5e0b1743fc49f34047d6e70ae7e35928/cmd/notification.go#L854
https://github.com/minio/minio/blob/c7ed6eee5e0b1743fc49f34047d6e70ae7e35928/cmd/notification.go#L1227-L1230

## Possible Solution
I don't know why the key needs to be escaped but probably one solution is to do

```javascript
keyName = strings.ReplaceAll(url.QueryEscape(args.Object.Name), "%2F", "/")
```

## Steps to Reproduce
1. Add a notification event for when an object is created in bucket. 
2. Log the event message and search inside `Records`

## Context
It does not match AWS SDK, which provides the field `Records[0].s3.object.key` with correct key path.
With minio sdk, you have to always `unescape` the key, which should not be required.

## Your Environment
Minio latest image but most likely any image will do.
I consumed the event notification with minio-js library 7.0.28 but it does not do any manipulation with key.

**Comment by harshavardhana** [comment]
The escaped key is what AWS S3 event info structure mandates @joaofranciscosantos 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html

> The s3 key provides information about the bucket and object involved in the event. The object key name value is URL encoded. For example, "red flower.jpg" becomes "red+flower.jpg" (Amazon S3 returns "application/x-www-form-urlencoded" as the content type in the response).

**Comment by haggen** [comment]
Weirdly enough my application doesn't decode the key and still works with S3+SNS. Perhaps Amazon doesn't follow its own documentation?
