### ISSUE TITLE
Add runtimeClassName support to helm chart

### ISSUE THREAD

**Issue by dnskr** [minio/minio#15217]
**Is your feature request related to a problem? Please describe.**
The feature request related to the problem with files relabeling when MinIO pods run on nodes with enabled SELinux.
The solution described in the [discussions](https://github.com/minio/minio/discussions/14854) and require `runtimeClassName` to be set on MinIO pods.

**Describe the solution you'd like**
Add `runtimeClassName` value to minio helm chart.

**Comment by steve-gray** [comment]
As per https://github.com/minio/minio/issues/15217 and the associated discussions, without this work to enable skipping of most of the leg-work of an SELinux relabel, it's essentially impossible to use Minio in any modern managed Kubernetes environment. As most platforms default to an SELinux variant (EKS, OCI/EKS, AKS etc....), it essentially means a restart of Minio with a scaled number of files can take exponential amounts of time, and lead to low availability of the service.

**Comment by harshavardhana** [comment]
This is a low priority to get runtimeClassName support for vanilla helm chart - it's the operator issue https://github.com/minio/operator/issues/1194 that is of high priority.
