### ISSUE TITLE
minio memory usage increases

### ISSUE THREAD

**Issue by XuRong233** [minio/minio#15224]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Reduced memory usage
## Current Behavior
There are currently 520,000 files, and 10,000 are uploaded every day
192.168.8.66
top - 11:16:40 up 195 days,  2:41,  2 users,  load average: 0.17, 0.28, 0.23
Tasks: 119 total,   2 running, 115 sleeping,   2 stopped,   0 zombie
%Cpu(s):  2.9 us,  3.5 sy,  0.0 ni, 92.1 id,  1.2 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  2914376 total,  1411816 free,  1073944 used,   428616 buff/cache
KiB Swap:  8388604 total,  8055548 free,   333056 used.   112392 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                             
19167 root      20   0 1977232 297152  10880 S   7.3 10.2   3198:01 minio                                                                                                                                               
 8177 root      20   0  161288   4888   4340 S   1.0  0.2   0:12.18 sshd                                                                                                                                                
    9 root      20   0       0      0      0 R   0.3  0.0 126:43.22 rcu_sched                                                                                                                                           
 4877 root      20   0  162072   2204   1552 R   0.3  0.1   0:00.03 top                                                                                                                                                 
 8257 root      20   0  162812   2692   1544 S   0.3  0.1   0:05.26 top                                                                                                                                                 
    1 root      20   0  128148   3100   1576 S   0.0  0.1   2:39.43 systemd                                                                                                                                             
    2 root      20   0       0      0      0 S   0.0  0.0   0:05.32 kthreadd                                                                                                                                            
    4 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                        
    6 root      20   0       0      0      0 S   0.0  0.0   2:10.10 ksoftirqd/0                                                                                                                                         
    7 root      rt   0       0      0      0 S   0.0  0.0   0:03.79 migration/0                                                                                                                                         
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh                                                                                                                                              
   10 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain                                                                                                                                       
   11 root      rt   0       0      0      0 S   0.0  0.0   1:34.68 watchdog/0                                                                                                                                          
   12 root      rt   0       0      0      0 S   0.0  0.0   1:48.30 watchdog/1                                                                                                                                          
   13 root      rt   0       0      0      0 S   0.0  0.0   0:04.24 migration/1                                                                                                                                         
   14 root      20   0       0      0      0 S   0.0  0.0  15:45.00 ksoftirqd/1 

192.168.8.67
top - 11:16:40 up 195 days,  2:41,  2 users,  load average: 0.17, 0.28, 0.23
Tasks: 119 total,   2 running, 115 sleeping,   2 stopped,   0 zombie
%Cpu(s):  2.9 us,  3.5 sy,  0.0 ni, 92.1 id,  1.2 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  2914376 total,  1411816 free,  1073944 used,   428616 buff/cache
KiB Swap:  8388604 total,  8055548 free,   333056 used.   112392 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                             
19167 root      20   0 1977232 297152  10880 S   7.3 10.2   3198:01 minio                                                                                                                                               
 8177 root      20   0  161288   4888   4340 S   1.0  0.2   0:12.18 sshd                                                                                                                                                
    9 root      20   0       0      0      0 R   0.3  0.0 126:43.22 rcu_sched                                                                                                                                           
 4877 root      20   0  162072   2204   1552 R   0.3  0.1   0:00.03 top                                                                                                                                                 
 8257 root      20   0  162812   2692   1544 S   0.3  0.1   0:05.26 top                                                                                                                                                 
    1 root      20   0  128148   3100   1576 S   0.0  0.1   2:39.43 systemd                                                                                                                                             
    2 root      20   0       0      0      0 S   0.0  0.0   0:05.32 kthreadd                                                                                                                                            
    4 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H                                                                                                                                        
    6 root      20   0       0      0      0 S   0.0  0.0   2:10.10 ksoftirqd/0                                                                                                                                         
    7 root      rt   0       0      0      0 S   0.0  0.0   0:03.79 migration/0                                                                                                                                         
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh                                                                                                                                              
   10 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain                                                                                                                                       
   11 root      rt   0       0      0      0 S   0.0  0.0   1:34.68 watchdog/0                                                                                                                                          
   12 root      rt   0       0      0      0 S   0.0  0.0   1:48.30 watchdog/1                                                                                                                                          
   13 root      rt   0       0      0      0 S   0.0  0.0   0:04.24 migration/1                                                                                                                                         
   14 root      20   0       0      0      0 S   0.0  0.0  15:45.00 ksoftirqd/1 

## Possible Solution
How much should MINIO_API_REQUESTS_MAX be set to.

## Your Environment

* Version used :2022-05-04T07:45:27Z
* Server setup and configuration:Two sites, each site uses two servers and 4 drivers,Two sites setup bucket synchronization.
* Operating System and version :Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> * Version used :2022-05-04T07:45:27Z

Please upgrade to latest release

> ## Context
> ## Regression
> ## Your Environment
> * Version used :2022-05-04T07:45:27Z
> * Server setup and configuration:Two sites, each site uses two servers and 4 drivers,Two sites setup bucket synchronization.
> * Operating System and version :Linux localhost.localdomain 3.10.0-1160.el7.x86_64 [Full restructure in accordance with #1](https://github.com/minio/minio/pull/1) SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Also, don't use CentOS 7.x - it is preferred that you move to the latest kernels for better performance, memory usage reduction etc.
