### ISSUE TITLE
Configure MinIO for higher GET throughput

### ISSUE THREAD

**Issue by Dwijad** [minio/minio#15226]
Hi
 I have setup a distributed MinIO cluster with 6 nodes with 4 drives each of size `835 GiB`. Each node(`CentOS 7.5`) has been allocated `4 CPU` and `16 GB RAM` and are connected through `10Gbps` network interfaces. The disk type used in each nodes are `HDD`.

I did a number of throughput bench-marking using `mc CLI` and built-in speedtest feature from minio console(web UI). The combined maximum throughput for GET and PUT operations are around `1.1Gbps-1.3Gbps`.  

But Our application requirements requires significantly higher GET throughput than PUT throughput. Is there a way to configure the minIO cluster for higher GET throughput(around 80%) ?

minio version `RELEASE.2022-06-30T20-58-09Z (commit-id=f9a4ad7904905cd92b61306644c1d403686cf68e)`
Runtime: `go1.18.3 linux/amd64`

Thanks

**Comment by harshavardhana** [comment]
For performance and architecture overview please subscribe to support https://min.io/pricing

**Comment by klauspost** [comment]
@DwijadasDey I will give you a freebie: Your network is likely already saturated.
