### ISSUE TITLE
Deleting objects leaves empty folders that cannot be deleted via the GUI/mc

### ISSUE THREAD

**Issue by dwrolvink** [minio/minio#15256]
## Expected Behavior
Calling `mc rm <target>/<bucket>/folder/path -r --force` will remove all objects in that path AND remove that folder.

Same for selecting the folder in the GUI and running delete on it.

## Current Behavior
All objects are deleted (as far as I can tell) but all the empty folders remain

## Context
We use this bucket to temporarily store information that needs to be backed up. Having these empty folders remain will add up and the list will get longer and longer, which is mostly just annoying, not sure if it will have a performance impact or not.

## Regression

I have not found any other issues talking about this problem, nor can I find any docs on how one would remove (empty) folders.

## Your Environment
```
MinIO VERSION 
2022-06-10T16:59:15Z

mc version RELEASE.2021-05-26T19-19-26Z

stemcells:
- alias: default
  os: ubuntu-bionic
  version: 1.88
```

**Comment by harshavardhana** [comment]
Please upgrade your mc.
