### ISSUE TITLE
Expand a single node to multiple nodes

### ISSUE THREAD

**Issue by Blue-Pheasant** [minio/minio#15251]
**Is your feature request related to a problem? Please describe.**
I have a problem about expand a single node to multi node. Is it possible to expand without migrate data. I'm also quite confused about how to scale a distributed system, what are the requirements for the number of servers and disks to follow. I really need your explanation on this. Thank you.

**Describe the solution you'd like**
I plan to create a distributed system then transfer data from single node over.

**Comment by harshavardhana** [comment]
It is going to be added in future. It's part of the plan please watch out for future releases there is no set ETA 

Everything is explained in the documentation here https://docs.min.io/minio/baremetal/installation/expand-minio-distributed.html#expand-minio-distributed
