### ISSUE TITLE
Web interface fails with Lynx

### ISSUE THREAD

**Issue by rdebath** [minio/minio#15253]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

The web interface is impossible to use in a secure manner setting up tunnels to chromium.
 
## Expected Behavior
It should be possible to login and use the majority of the system management interface.
Especially creation of user and service accounts, creation of buckets checking logs and configuring notifications.

## Current Behavior
You need to enable JavaScript to run this app.

## Possible Solution
Don't require Javascript unless it's actually necessary to run code using the CPU of the client.

## Steps to Reproduce (for bugs)
```
localhost-tmp$ lynx http://127.0.0.1:9001
   You need to enable JavaScript to run this app.

   [background.svg] [background-wave-orig2.svg]
   [Loader.svg]
localhost-tmp$
```

## Context
Have reconnect SSH to setup a tunnel to the docker server to thread the big fat web browser through the encryption.

## Regression
Unknown

## Your Environment
* Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/amd64)
* docker pull minio/minio
* Linux 426f74b5a1da 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
we can't possibly support `lynx` or `links`.  It's working the way it should please use a real browser.

**Comment by harshavardhana** [comment]
If you want `CLI` we have a beautiful CLI written called [mc](https://github.com/minio/mc) - you can automate everything and more.

**Comment by rdebath** [comment]
It is a management interface so yes, I am serious.

The only reason to run javascript on the client is to overcome limitations in the way that CSS can display and react to user input. (The other reason doesn't apply here ... using the browser as an application host to offload processing for computations that the server doesn't need to know)
 
As it's a management interface NOBODY CARES WHAT IT LOOKS LIKE as long as it does the job.

So a trivial HTML forms interface is very appropriate. Maybe some CSS if you can't bear to look at the default style for some reason.

As for your CLI, yes, it is a bit ugly, kinda like git, but that's not really a problem. The problem is that it's unvalidated software that has to be installed on the docker host or in installed in another container. This is obviously a pain. It's easier to setup the tunnel.

Having said all this, it's only a minor point against as reconfiguration isn't a common job and the limitations can be scripted around.
