### ISSUE TITLE
 the number and size of the files displayed on the console are not timely.

### ISSUE THREAD

**Issue by XuRong233** [minio/minio#15254]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Current Behavior
Upload a file on one of the sites. The files of the two sites are synchronized. You can see the file just uploaded on both sides, but the number and size of the files displayed on the console are not timely.

![2](https://user-images.githubusercontent.com/46958156/177935925-13e63ae3-26dc-456a-80bd-8c5d32d23e1a.png)
![1](https://user-images.githubusercontent.com/46958156/177935938-760277fd-a026-4dd0-87a8-4a0e045c5a78.png)

## Your Environment

* Version used (2022-06-11T19:55:32Z):
* Server setup and configuration:Two sites, each site uses two servers and 4 drivers
* Operating System and version (Linux localhost 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux ):

**Comment by harshavardhana** [comment]
Bucket usage calculation is not realtime. It updates in cycles.
