### ISSUE TITLE
Server side replication with tag filter doesn't try to replicate if destination was down and went back up

### ISSUE THREAD

**Issue by Liad-n** [minio/minio#15263]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

* Objects get tagged when destination bucket is down
* Destination gets back online
* Objects with the relevant tag will get replicated to the destination after a while 

## Current Behavior

* Objects get tagged when destination bucket is down
* Destination gets back online
* Objects with the relevant tag don't get replicated to the destination, only gets replicated if you retag the objects with the relevant tag.

## Possible Solution

Maybe there needs to be a polling mechanism to check every once in a while whether objects with the relevant tags exist in the source that haven't been replicated yet.

## Steps to Reproduce (for bugs)

1. Create a bucket in the source with versioning enabled
2. Create a bucket in the destination with versioning and locking enabled
3. Create replication with a tag filter, without deletes or delete markers
4. disconnect the destination
5. tag the objects with the tag to be replicated and then reconnect the destination
6. Any object tagged in the time the destination has been offline won't be replicated.
7. Tag the object again when the destination is online
8. The object will be replicated

## Context

* I created a server-side replication with a bucket that replicates objects with the tag hello:world
* The remote (destination) MinIO server is down
* The objects get tagged locally with the hello:world tag while the destination is down
* The destination is back online, but the objects won't get replicated unless you retag the objects.
* The objects are retagged, and get replicated immediately.

## Your Environment

* Version used (minio --version): minio version RELEASE.2022-07-08T00-05-23Z
* commit: ed0cbfb31e00644013e6c2073310a2268c04a381
* go version: go1.18.3
* Server setup and configuration: minio running on k3s 1.22.5 as a pod
* Operating System and version (uname -a):
* Linux 5.13.0-30-generic https://github.com/minio/minio/pull/33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by poornas** [comment]
>disconnect the destination
tag the objects with the tag to be replicated and then reconnect the destination
Any object tagged in the time the destination has been offline won't be replicated.
Tag the object again when the destination is online

When you tagged the objects on the source, was a replication status shown in `mc stat <alias>/<bucket>/<object>`? If the replication rule applies to the object, you should see a replication status -  the inbuilt replication healing process will take care of syncing the object when it visits this part of the namespace again.

 It may not be synced immediately after the destination comes up, its dependent on the scanner visit. When you re-tagged the object, you essentially did a metadata update that got queued and replicated actively since the destination was up. Don't see a bug here

**Comment by harshavardhana** [comment]
Closing based on the @poornas response

**Comment by Liad-n** [comment]
> 

Ok I understand, in my usecase I need the replication to happen as fast as possible once the destination gets connected. Is there a way to make the scanner visit on demand without tagging the objects again? 
Thanks again for the great (!) support and product.

**Comment by Liad-n** [comment]
> > disconnect the destination
> > tag the objects with the tag to be replicated and then reconnect the destination
> > Any object tagged in the time the destination has been offline won't be replicated.
> > Tag the object again when the destination is online
> 
> When you tagged the objects on the source, was a replication status shown in `mc stat <alias>/<bucket>/<object>`? If the replication rule applies to the object, you should see a replication status - the inbuilt replication healing process will take care of syncing the object when it visits this part of the namespace again.
> 
> It may not be synced immediately after the destination comes up, its dependent on the scanner visit. When you re-tagged the object, you essentially did a metadata update that got queued and replicated actively since the destination was up. Don't see a bug here

> 

Ok I understand, in my usecase I need the replication to happen as fast as possible once the destination gets connected. Is there a way to make the scanner visit on demand without tagging the objects again? 
Thanks again for the great (!) support and product.

**Comment by poornas** [comment]
>Is there a way to make the scanner visit on demand without tagging the objects again?

by tagging the objects again, you are essentially forcing it to perform replication right away. Even without this intervention, it would get replicated when scanner visits. If 2 way active-active replication is in place, automatic proxying happens on GET/HEAD to fetch the object from the cluster that has it.

There is also a feature in the works to identify and sync unreplicated objects interactively on a prefix.
