### ISSUE TITLE
SignatureDoesNotMatch when uploading file with a pre signed request

### ISSUE THREAD

**Issue by zubozrout** [minio/minio#15268]
Hi,
I am trying to switch from localstack to minio for a local development of a express.js app and I seem to be bumping into an issue with presigned url file uploads.

I am aware of this report with the same title: https://github.com/minio/minio/issues/9564 but unfortunately my case seems to be different. Also, exactly the same approach works for me when using localstack or even full blown S3 environment spinned up in the AWS.

So, I am using docker-compose and this is basically what I have in for minio:

```
minio:
  image: minio/minio:latest
  command: server /data --console-address ":9001"
  environment:
    - MINIO_ROOT_USER=test
    - MINIO_ROOT_PASSWORD=supersecret # Access key length should be at least 3, and secret key length at least 8 characters
  ports:
    - "9000:9000"
    - "9001:9001"
  volumes:
    - file_storage:/data
```
and this what I have for localstack:
```
localstack:
  image: localstack/localstack:latest
  container_name: localstack_development
  ports:
    - "4563-4599:4563-4599"
  environment:
    - SERVICES=s3
    - DEBUG=1
    - DATA_DIR=/tmp/localstack/data
    - DISABLE_CORS_CHECKS=1
    - DISABLE_CUSTOM_CORS_S3=1
    - DISABLE_CUSTOM_CORS_APIGATEWAY=1
  volumes:
    - file_storage:/tmp/localstack/:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
```

In both cases my express.js app uses `import AWS from 'aws-sdk';` and it seems to be able to connect to the file storage just fine and call various functions too. However, when it gets to signing urls, this fails with minio unfortunately.

Here are (I suppose) the relevant bits of code:
```
const signedUrl = await S3GetSignedFileUploadUrl({
  Bucket: bucketName,
  // ACL: "public-read",
  Key: key,
  Expires: 10000,
  ContentType: contentType
});
return {
  signedUrl: signedUrl.replace(/^(https?:\/\/)[^.:]*/, "$1localhost")
};
```
with `S3GetSignedFileUploadUrl` being a wrapper for Promise + `s3.getSignedUrl`.

One thing that may be of importance here as well a source of potential issues may be the fact I am replacing `minio` in the singed url with localhost as the dockerised app accesses that with `http://minio:9000` (using `depends_on: - minio` inside docker-compose) and therefore generates a url with the same while it is useful for me to use localhost instead as I am accessing the node app directly as exposed via docker.

A GET request to http://localhost:9000 works and redirects me to an admin UI on http://localhost:9001 so I know that url should work, but maybe it can mess up with the signature? No idea, but not the case with localstack.

The frontend file upload code then looks as follows:
```
const signedUrl = await getSignedUrl({
    data: {
        key: file.name,
        contentType: file.type,
        fileSize: file.size
    }
});

const fileUploadResponse = await fetch(signedUrl, {
    method: "PUT",
    mode: "cors",
    credentials: "omit",
    headers: {
        "Content-Type": file.type,
        // "x-amz-acl": "public-read"
    },
    body: file
});
```

The code above is simplified. But should show all the basics. And in comparison to the other issue linked above, I have "x-amz-acl" commented out. If uncommented both on the frontend and backend (ACL) that makes no difference.

## Expected Behavior
I would expect this to work the same as locakstack. If there are differences then it would be awesome to get to the bottom of this so that me as well as anyone else who may bump into the same issue can make this work.

## Current Behavior
Presigned url gets generated, is returned to an app, but then using that url in a POST request to upload a file fails for me with an error "403 Forbidden" and the following message:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>xxx.jpg</Key><BucketName>bucket</BucketName><Resource>/bucket/xxx.jpg</Resource><RequestId>1700DB1EC946D5A6</RequestId><HostId>76962638-e199-4ade-bd19-577db54fced3</HostId></Error>
```

I expect I am likely doing something wrong but I've tried figuring this out for quite a long time + also haven't find anything really useful online so am turning into this sort of thing as a last resource. Therefore I would be very much grateful for any hints or more details on this one.

Thank you.

**Comment by harshavardhana** [comment]
> const signedUrl = await S3GetSignedFileUploadUrl({
>   Bucket: bucketName,
>   // ACL: "public-read",
>   Key: key,
>   Expires: 10000,
>   ContentType: contentType
> });
> return {
>   signedUrl: signedUrl.replace(/^(https?:\/\/)[^.:]*/, "$1localhost")
> };

You cannot just change hostname whenever you feel like - signature relies on Host header to be same.

**Comment by zubozrout** [comment]
Thank you @harshavardhana, also for you quick response!

I'll try to figure out how to make this work locally then. Will need some docker/nginx magic I don't see atm.
Still interesting localstack seems to ignore that though, but I've read somewhere S3 is a bit less strict with this.

**Comment by zubozrout** [comment]
This is it: https://github.com/minio/minio/issues/11870 but I don't see a solution there either sadly :(.

Not sure why that thread was closed shortly after the last post there though since I believe that user was very right ;). Signed url is generated on the server and it is based on the initial `endpoint` configuration. So nothing that can be altered.

That makes any implementation of this quite ugly. Either some nginx docker service magic (proxy also altering headers perhaps?) if that's going to work or simply modifying /etc/hosts on each and every development device manually.
