### ISSUE TITLE
Strange behaviour with the console

### ISSUE THREAD

**Issue by klibr007** [minio/minio#15276]
## NOTE
Hello everybody since yesterday my minio that I launched within a container via docker-compose show me a strange page when I try to get to the console. I see no traces in the logs and I don't even understand what backend it's refering to. I just have this on my screen. 

![image](https://user-images.githubusercontent.com/50625221/178506502-20335a6c-facd-495f-8d41-7899f61f966f.png)

I tried changing the image deleting all volume mounted but the result remains the same. Does anybody have an idea ?

## Expected Behavior
Work properly like it did within the previous days 

## Current Behavior
error 403 that I can't comprehend

## Steps to Reproduce (for bugs)
I have no clue since it just sarted out of nowhere

## Your Environment

* Version used (`minio --version`): quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z
* Server setup and configuration: launched with docker-compose 
* Operating System and version (`uname -a`): running in docker on Ubuntu 20.04.4 LTS

**Comment by harshavardhana** [comment]
@klibr007 please share your docker compose

Also enable `_MINIO_SERVER_DEBUG=on` to see more information on console login failures

**Comment by klibr007** [comment]
@harshavardhana here is my compose file
```# docker-compose.yml
version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z
    restart: always
    command: server /data --console-address ":9001" 
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /srv/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadm
      - MINIO_ROOT_PASSWORD=minioadm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      
```

**Comment by harshavardhana** [comment]
I can't seem to reproduce this - were you able to enable _MINIO_SERVER_DEBUG?

**Comment by klibr007** [comment]
@harshavardhana no I haven't found any variables related to the log level for the docker image and this MINIO_SERVER_DEBUG doesn't seem to work
 I think you said it here https://github.com/minio/minio/discussions/14213#discussioncomment-2079746

**Comment by vadmeste** [comment]
By the way, it is `_MINIO_SERVER_DEBUG` not `MINIO_SERVER_DEBUG`. It should print more logs

**Comment by klibr007** [comment]
@vadmeste indeed it prints more logs but nothing about http traffic it just prints the environment settings

**Comment by vadmeste** [comment]
@klibr007 can you check with the browser developer console ? any network failure ?

**Comment by klibr007** [comment]
@vadmeste I actually get this. 


![image](https://user-images.githubusercontent.com/50625221/178707513-aff90567-6baf-4a87-8674-016cf7b93950.png)

**Comment by harshavardhana** [comment]
> @vadmeste I actually get this.

Looks like your console port is talking to MinIO port

**Comment by harshavardhana** [comment]
> version: '3.7'
> 
> services:
>   minio:
>     image: quay.io/minio/minio:RELEASE.2022-06-20T23-13-45Z
>     restart: always
>     command: server /data --console-address ":9001" 
>     ports:
>       - 9000:9000
>       - 9001:9001
>     volumes:
>       - /srv/minio/data:/data
>     environment:
>       - MINIO_ROOT_USER=minioadm
>       - MINIO_ROOT_PASSWORD=minioadm
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3

how is this deployment exposed? @klibr007 please show us your LB settings - perhaps you have another MinIO running at port 9001.

**Comment by klibr007** [comment]
@harshavardhana you're right problem solved the proxy was forwarding on the API port 9000 instead of 9001
Thanks a lot 
@vadmeste thank you too !

**Comment by martinbohlmann** [comment]
## Same issue

Hi all. I just installed Minio and had the same issue on Mac. I used the shared `docker-compose.yaml` file and I got the same behavior. The console login (9001) connects to port 9001 instead of API at 9000. How did you fix it?

I used Chrome and Firefox and both gave me the same result. Also, I can´t find a configuration to explicitly tell Minio what the API port is.

Thanks for your support.

![Minio_error](https://user-images.githubusercontent.com/9382438/180651477-22adaa81-53c3-4fc2-b782-de67cc944bd0.jpg)

PS: Actually I have the error when using the `latest` version. I reported a BUG under https://github.com/minio/console/issues/2197 with the details.

**Comment by martinbohlmann** [comment]
Never mind, it seems the browser had cashed cookies from other apps I run on port 9000 before. I did a hard refresh and it works. Thanks
