### ISSUE TITLE
Allow X-Frame-Options to be configurable via env variables or the UI

### ISSUE THREAD

**Issue by benmarte** [minio/minio#15275]
**Is your feature request related to a problem? Please describe.**
I want to load minio as an iframe in my application but the X-Frame-option deny does not allow me to embed minio in my app.

**Describe the solution you'd like**
It would be great if this option could be enabled via environment variables or a configuration setting via the UI.

**Describe alternatives you've considered**
Being able to set this via environment variables would be great for people using helm and kubernetes.

**Additional context**
Here is an example of how keycloak accomplishes this via the UI:

![image](https://user-images.githubusercontent.com/693275/178492565-7be9d287-f065-463e-a85f-ce68d9fb7bc8.png)

https://www.keycloak.org/docs/latest/server_admin/index.html#clickjacking

**Comment by harshavardhana** [comment]
This is currently a low-priority item.

**Comment by harshavardhana** [comment]
This will be allowed and removed from the Console UI - https://github.com/minio/console/commit/5a59f8e3f44b8f1557efc49b7df79c437e542e13
