### ISSUE TITLE
LDAP group search filter doesn't work with Active directory

### ISSUE THREAD

**Issue by maxisam** [minio/minio#15272]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

it should read group in the error message but it doesn't

## Possible Solution
I wonder it is because active directory use memberOf for group attribute

**Comment by harshavardhana** [comment]
There is nothing reported in this issue that allows us to help you - LDAP has been running in production with active directory at multiple customers.

so whatever you are doing is perhaps wrong but without much details we can't really help you.

**Comment by maxisam** [comment]
You are so fast, I was about to say I figured it out. Should use %d instead of %s on group search

**Comment by harshavardhana** [comment]
> You are so fast, I was about to say I figured it out. Should use %d instead of %s on group search

👍🏽
