### ISSUE TITLE
Problem with systemd file on Ubuntu focal

### ISSUE THREAD

**Issue by AxisNL** [minio/minio#15279]
Hi,

getting started with minio, but I have problems with the systemd script on https://github.com/minio/minio-service/blob/master/linux-systemd/minio.service. I'm pretty sure I followed the guides. This is a freshly installed Ubuntu focal machine.

Now I know I can start it manually, but I want a nice service :) We use puppet to keep to this standard of managing service files and services, etc.

```
# systemctl status minio.service 
- minio.service - MinIO
     Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-07-12 15:01:47 AST; 3s ago
       Docs: https://docs.min.io
    Process: 35515 ExecStartPre=/bin/bash -c if [ -z "${MINIO_VOLUMES}" ]; then echo "Variable MINIO_VOLUMES not set in /etc/default/minio"; exit 1; fi (code=exited, status=0/SUCCESS)
    Process: 35516 ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES (code=exited, status=1/FAILURE)
   Main PID: 35516 (code=exited, status=1/FAILURE)

Jul 12 15:01:47 hostname.local systemd[1]: minio.service: Scheduled restart job, restart counter is at 5.
Jul 12 15:01:47 hostname.local systemd[1]: Stopped MinIO.
Jul 12 15:01:47 hostname.local systemd[1]: minio.service: Start request repeated too quickly.
Jul 12 15:01:47 hostname.local systemd[1]: minio.service: Failed with result 'exit-code'.
Jul 12 15:01:47 hostname.local systemd[1]: Failed to start MinIO.
```

Looks like the service isn't reading the environment file.

```
# cat /etc/systemd/system/minio.service
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/

User=minio
Group=minio
ProtectProc=invisible

EnvironmentFile=/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=1048576

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```

and the environment file:

```
# cat /etc/default/minio 

# Volume to be used for MinIO server.
MINIO_VOLUMES="/var/lib/minio/data"
# Use if you want to run MinIO on a custom port.
MINIO_OPTS="--address :9000 --console-address :9001"
# Root user for the server.
MINIO_ROOT_USER=adminuser
# Root secret for the server.
MINIO_ROOT_PASSWORD=adminpass

# set this for MinIO to reload entries with 'mc admin service restart'
MINIO_CONFIG_ENV_FILE=/etc/default/minio
```

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-07-08T00-05-23Z (commit-id=ed0cbfb31e00644013e6c2073310a2268c04a381)
* Server setup and configuration: Ubuntu 20.04 LTS
* Operating System and version (`uname -a`): Linux hostname.local 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AxisNL** [comment]
Dang, why is it that every time you take the time to create an issue, you find the source of the problem :D

```
Jul 12 15:16:32 hostname.local minio[2628]: ERROR Unable to read the config environment file: open /etc/default/minio: permission denied
Jul 12 15:16:32 hostname.local systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
```
Apparently the environment file needs to be readable by the user running the daemon. Perhaps update the docs on https://github.com/minio/minio-service/tree/master/linux-systemd ? I would expect root to read the file, and then spawn the command as the service user.

**Comment by harshavardhana** [comment]
> Apparently the environment file needs to be readable by the user running the daemon. Perhaps update the docs on https://github.com/minio/minio-service/tree/master/linux-systemd ? I would expect root to read the file, and then spawn the command as the service user.

Yes that is required.

**Comment by ravindk89** [comment]
https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html

we do have some docs on this, but we are also actively restructuring our docs - I can fold this particular request in as part of some ongoing work.
