### ISSUE TITLE
Minio Helm Chart version 4.0.4 is broken

### ISSUE THREAD

**Issue by lamida** [minio/minio#15294]
## Expected Behavior
I am testing minio helm chart (the latest version 4.0.4) and expect the following to run successfully.
```
helm install my-minio minio/minio --version 4.0.4  --set rootUser=test --set rootPassword=ultimatesecret --set mode=standalone
```

## Current Behavior

The `*-make-user-job-*` pods failed with this error:
```
Connecting to MinIO server: http://my-minio:9000
Added `myminio` successfully.
/config/add-user: line 83: /config/accessKey_and_secretKey_tmp: Read-only file system
```

## Possible Solution
https://github.com/minio/minio/pull/15293

## Steps to Reproduce (for bugs)
1.  This will be failed: `helm install my-minio minio/minio --version 4.0.4  --set rootUser=test --set rootPassword=ultimatesecret --set mode=standalone`
2. This will be fine: `helm install my-minio minio/minio --version 4.0.3  --set rootUser=test --set rootPassword=ultimatesecret --set mode=standalone`

## Context
I am trying to test minio helm chart and encounter this issue.

## Your Environment
* Version used (`minio --version`): latest from master branch
* Server setup and configuration: Linux
* Operating System and version (`uname -a`): Linux pop-os 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Fixed by #15293, update to v4.0.5
