### ISSUE TITLE
Decomissioning fails, possibly due to IncompleteBody errors

### ISSUE THREAD

**Issue by haslersn** [minio/minio#15314]
I'm currently trying to decommission a pool in a MinIO cluster with two pools. The decommissioning always fails.

Before decommissioning, the pool had over 500 GB used per drive. Now it has 228 GB used per drive.

When trying to decommission again, MinIO seems to iterate over all the objects, but doesn't remove any more objects from the pool, because it stays at 228 GB.

During decommissioning (both initially and now when running it again), there are a lot of these errors in the MinIO log. (Speculation: perhaps this error occurs with every object in the pool and that's why MinIO doesn't remove them?)

```
minio-old-zone0-0 minio API: SYSTEM()
minio-old-zone0-0 minio Time: 11:51:07 UTC 07/16/2022
minio-old-zone0-0 minio DeploymentID: 73a34713-7b8c-4d45-98ba-6e9c6a8cc1df
minio-old-zone0-0 minio Error: cluster01-gitlab-registry/docker/registry/v2/blobs/sha256/d7/d7b6e6950809eba24f1016ab5db1f80078bcf58caf57ac47c626630e462eae86/data has incomplete body (cmd.IncompleteBody)
minio-old-zone0-0 minio        2: internal/logger/logger.go:270:logger.LogIf()
minio-old-zone0-0 minio        1: cmd/erasure-server-pool-decom.go:745:cmd.(*erasureServerPools).decommissionPool.func1()
minio-old-zone0-0 minio 
```

All of the objects where this error occurs seem to be readable (e.g. with `mc cat`) just fine. So they are not corrupted.

## Expected Behavior

Decommissioning should succeed to migrate those objects.

## Your Environment

MinIO 2022-07-13T23:29:44Z on Kubernetes via containerd, bare metal, linux `5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@haslersn are these objects encrypted?

**Comment by haslersn** [comment]
Yes

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/15320 this would fix your problem @haslersn
