### ISSUE TITLE
Minio does not detect a secure connection (SSE-C) when running behind a reverse proxy (Traefik)

### ISSUE THREAD

**Issue by 4n70w4** [minio/minio#15315]
Hi! Actual description: https://github.com/minio/minio/issues/6093

Many years later is there a convenient way to do this?

My case is to encrypt the contents of the data in case the minio-server hardware administrators make leak data.
The interception of encryption keys can be 100% neglected.

I really and sincerely do not need a minio backend with https. Doing https to make https is a pity to waste resources on this.

For example, I have a long reverse proxy chain. Some nodes in the chain work strictly on http.
The fact that the last couple of nodes (traefik https => minio https) work on https will not save the entire chain from interceptions.

```
closed specific network (http) => data exchange point (http) => region balancer (https) => data center (http) => traefik (https) => minio (https)
```

If you want to guarantee security, then you need to check the security of the entire chain, not just the last mile. Otherwise it's all in vain.

It is not realistic to check the security of the entire chain of proxy servers on the minio side.

**Comment by harshavardhana** [comment]
For SSE-C you need to enable TLS on MinIO not sufficient just on proxies @4n70w4 

Your connection is not secure and SSE-C mandates all incoming connections must honor TLS.

If you are worried about resource, just use SSE-S3, provides the same level of at rest protection.

**Comment by 4n70w4** [comment]
I can generate an endless list of reasons why I don't need tls on the minio backend.

> MinIO can do certain things, but it can't do everything under the sun.

**Comment by klauspost** [comment]
@4n70w4 If you have commercial requests for MinIO please write `sales@min.io` with your business case. This issue is resolved.
