### ISSUE TITLE
Bucket size and object count wrong after mirroring a huge amount of small objects

### ISSUE THREAD

**Issue by ntimo** [minio/minio#15319]
I copied data from one minio server to another using the mc mirror command, approximately 700.000 files. After the copy job was done the new minio bucket on the server does not show correct stats it only shows that there are 29.000 objects in the bucket and that the bucket size is 80MB while its around 15GB in reality. 

## Expected Behavior
Object count should be correct after copying all objects using mc mirror
Bucket size should be correct after copying all objects using mc mirror

## Current Behavior
Object count are not correct after copying all objects using mc mirror
Bucket size are not correct after copying all objects using mc mirror

## Possible Solution
I have no clue. Is there a way to have MinIO recalculate these stats?

## Steps to Reproduce (for bugs)
1. Create a new MinIO server on HDDs
2. Use mc mirror to copy a huge amount of small files (e.g. 700.000)
3. Check the bucket size and file cound using minio console

## Your Environment
Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
MinIO Version: RELEASE.2022-07-15T03-44-22Z

**Comment by harshavardhana** [comment]
@ntimo the object stats are not updated in real-time they take time to reflect. You need to wait for some time before it gets updated.
