### ISSUE TITLE
An error occurred, please try again Storage resources are insufficient for the write operation .minio.sys/config/iam/policydb/sts-users/brZ3hqrT_v0VYG49guhz8keEnUCaFcpDcBHzbMzyN6w.json

### ISSUE THREAD

**Issue by raj-katonic** [minio/minio#15326]
I have provided minio server with 4 disks (kubernetes pvcs) of size 35GB each. 
Versioning is enabled on my bucket.
As observed, the default behaviour of MinIO is to replicate the data.
As per calculations, in this case bucket in Minio should not be able to hold data more than 70GB.
When we upload data through the console, it works as expected. MinIO restricts uploading data more than the threshold.

BUT, when we write data into MinIO bucket using python library or dd commands where bucket is mounted, the data is stored in such a way that when we fully fill the minio bucket, minio server goes down throwing the following message.

An error occurred, please try again Storage resources are insufficient for the write operation .minio.sys/config/iam/policydb/sts-users/brZ3hqrT_v0VYG49guhz8keEnUCaFcpDcBHzbMzyN6w.json

For workaround: I tried setting quota to minio bucket, BUT quota restrictions are not working when uploading data through python library.

Ways to Reproduce:

- deploy minIO on kubernetes.
- attach 4 pvcs of 35GB each
- create a bucket with versioning enabled
- set a 60GB quota to the bucket.
- upload 70GB data through python library minio

**Comment by harshavardhana** [comment]
> BUT, when we write data into MinIO bucket using python library or dd commands where bucket is mounted, the data is stored in such a way that when we fully fill the minio bucket, minio server goes down throwing the following message.

It is expected that you will lose cluster access because MinIO cannot really function without disk space available.   You need to provide enough storage space to handle your growth.

**Comment by novneet03** [comment]
I have also experienced the same issue , my total PVC size is 80 GB and I have set the quota of 60 GB. But minio stores data more than 60 GB ignoring the quota size and reaches the maximum PVC utilization which results to disconnecting the minio from all transport end point

**Comment by mshanmu** [comment]
> I have also experienced the same issue , my total PVC size is 80 GB and I have set the quota of 60 GB. But minio stores data more than 60 GB ignoring the quota size and reaches the maximum PVC utilization which results to disconnecting the minio from all transport end point

MinIO uses usage scanner to calculate storage size and it is not instantaneous. You can tweak the configuration to run it faster, see here https://github.com/minio/minio/tree/master/docs/config#usage-scanner
