### ISSUE TITLE
IAM Policy does not support "NotAction"

### ISSUE THREAD

**Issue by nafisrdn** [minio/minio#15328]
We want to make our policies cleaner by making the statements to only one, we found the solution from IAM documentation by using the "NotAction".

## Expected Behavior

Should successfully create an admin policy with the "NotAction"

## Current Behavior

Failed to create new admin policy with "Unable to add new policy. Action must not be empty." error message

## Steps to Reproduce (for bugs)

1. Go to MinIO Console
2. Click a "Create a policy" from console
3. Fill in the policy title with "my-policy" name
4. Fill in the policy content with:
`{
        "Version": "2012-10-17",
        "Statement": [
                {
                        "Effect": "Allow",
                        "NotAction": "s3:*BucketPolicy*",
                        "Resource": [
                                "arn:aws:s3:::my-bucket",
                                "arn:aws:s3:::my-bucket/*"
                        ]
                }
        ]
}`
5. Save the policy

## Context

I was trying to make the policy cleaner and shorter

From:
```
{
        "Version": "2012-10-17",
        "Statement": [
                {
                  "Action": [
                          "s3:*"
                  ],
                  "Effect": "Allow",
                  "Resource": [
                        "arn:aws:s3:::my-bucket",
                        "arn:aws:s3:::my-bucket/*"
                  ]               
                },
                {
                        "Effect" : "Deny",
                        "Action" : [ 
                                "s3:GetBucketPolicy",
                                "s3:PutBucketPolicy", 
                                "s3:DeleteBucketPolicy" 
                        ],
                        "Resource": [
                                "arn:aws:s3:::my-bucket",
			       "arn:aws:s3:::my-bucket/*"
                        ]
                }
        ]
}
```

To:
`{
        "Version": "2012-10-17",
        "Statement": [
                {
                        "Effect": "Allow",
                        "NotAction": "s3:*BucketPolicy*",
                        "Resource": [
                                "arn:aws:s3:::my-bucket",
                                "arn:aws:s3:::my-bucket/*"
                        ]
                }
        ]
}`

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-07-17T15-43-14Z (commit-id=b6eb8dff649b0f46c12d24e89aa11254fb0132fa)
* Server setup and configuration: Docker Container
* Operating System and version (`uname -a`): Linux 21f69ad3aea9 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nafisrdn** [comment]
I tried the policy with "Policy Simulator" from Amazon, and it's worked
![amazon-ok](https://user-images.githubusercontent.com/37695356/179472510-75f9f824-7c82-4572-b04f-a92d60dca8ed.PNG)

**Comment by harshavardhana** [comment]
NotAction it is not supported yet.

**Comment by mahi072** [comment]
Hi, This is Mahima Yadav.
Is this issue still open? I would like to contribute in this issue. 
If yes, please guide me through this.

Waiting for your reply.

**Comment by donatello** [comment]
@mahi072 Yes this feature is not yet implemented. If you are interested, the policy evaluation logic is here https://github.com/minio/pkg/tree/main/iam/policy

**Comment by mahi072** [comment]
Hi,

Sure I'll have a look on this policy logic and come back to you.

Thanks & Regards,
Mahima Yadav

**Comment by mahi072** [comment]
Hi @donatello, can you please provide me some more materials to understand this issue much better, as this is my 1st contribution.

**Comment by mahi072** [comment]
Hi @harshavardhana @donatello, I'm working on this issue.
I was actually trying to launch the server page using some default address provided in MinIO documentations, but I was getting timeOut error for that.
If you can please help me in this to resolve.
Please find the command and error attachment below:

![command](https://user-images.githubusercontent.com/89216134/198829691-d9e24975-4e04-49fb-9a6d-f4831beb5519.jpg)
![server page](https://user-images.githubusercontent.com/89216134/198829693-8578da24-8be4-4613-a694-330d819b1397.jpg)
