### ISSUE TITLE
Prometheus Stats collector logs too often

### ISSUE THREAD

**Issue by adrian-tarau** [minio/minio#15334]
## Expected Behavior
When one or more nodes are down, there should be ideally no logging performed about such an event. Even if there is a need to log, some exponential backoff policy should be used, so it does not log so often. The node should be reported down in Prometheus stats. There should be a metric in cluster metrics (/minio/v2/metrics/cluster) to indicate the node's status.

## Current Behavior
Currently, if a node is down, the node is not mentioned in Prometheus cluster metrics (/minio/v2/metrics/cluster), and MinIO is logging complaints about unavailable nodes, and they clutter the logs with unnecessary reporting.

## Steps to Reproduce (for bugs)
Bring a node down, and you will see logged at least once per second the following error:
```
API: SYSTEM()
Time: 13:26:08 UTC 07/18/2022
DeploymentID: 07cb3e3d-5b6e-4529-b523-fc605ed1499b
Error: /getbucketstats "http://minioXXX:9000/minio/peer/v21": remote server offline (*rest.NetworkError)
       peerAddress=minioXXX:9000
       1: cmd/notification.go:132:cmd.(*NotificationGroup).Go.func1()

API: SYSTEM()
Time: 13:26:08 UTC 07/18/2022
DeploymentID: 07cb3e3d-5b6e-4529-b523-fc605ed1499b
Error: /getbucketstats "http://minioXXX:9000/minio/peer/v21": remote server offline (*rest.NetworkError)
       peerAddress=minioXXX:9000
       5: cmd/notification.go:611:cmd.(*NotificationSys).GetClusterBucketStats()
       4: cmd/bucket-replication.go:1835:cmd.getLatestReplicationStats()
       3: cmd/metrics.go:461:cmd.bucketUsageMetricsPrometheus()
       2: cmd/metrics.go:100:cmd.(*minioCollector).Collect()
       1: github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:446:prometheus.(*Registry).Gather.func1()
```

## Your Environment
* A 14 node cluster with version RELEASE.2022-03-14T18-25-24Z 
* Linux 4.1.12-124.30.1.el6uek.x86_64 #2 SMP Wed Aug 7 18:44:21 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dormanze** [comment]
My suggestion:
1. Identify nodes with host.name.
2. Add VariableLabels to the two indicators of node status
#15391

**Comment by polaris-phecda** [comment]
> My suggestion:
> 
> 1. Identify nodes with host.name.
> 2. Add VariableLabels to the two indicators of node status
>    [add onlineMap and offlineMap record node status #15391](https://github.com/minio/minio/pull/15391)

Another question of log didn't resolve in your pr.
