### ISSUE TITLE
MinIO can't find objects

### ISSUE THREAD

**Issue by djhoese** [minio/minio#15352]
I've been using MinIO in some integration tests for a while now where I needed an S3 endpoint. The last time I used it was in early May where as part of my tests I would create a directory and add an image to it and then start up MinIO from `docker run` to serve that directory as a bucket. It seems that ever since `RELEASE.2022-06-02T02-11-04Z ` this no longer works, but I can't tell from the release notes if this is something I need to change in my usage or a bug.

AWS CLI shows the bucket on the server fine, but listing the contents/objects of the bucket shows no results.

## Expected Behavior

When listing a bucket with `aws s3 ls`, see the objects in the `/data` directory.

## Current Behavior

Empty, but successful (200), listing.

## Steps to Reproduce (for bugs)

```bash
mkdir -p /tmp/mytest/mybucket
touch /tmp/mytest/mybucket/test.txt
docker run --rm -d -p 9999:9000 --name testminio -v /tmp/mytest:/data minio/minio:"RELEASE.2022-06-02T02-11-04Z" server /data --console-address ":9001"

AWS_ACCESS_KEY_ID="minioadmin" AWS_SECRET_ACCESS_KEY="minioadmin" aws s3 ls --endpoint-url "http://localhost:9999/" s3://
# \2022-07-19 14:27:30 mybucket

AWS_ACCESS_KEY_ID="minioadmin" AWS_SECRET_ACCESS_KEY="minioadmin" aws s3 ls --endpoint-url "http://localhost:9999/" s3://mybucket
AWS_ACCESS_KEY_ID="minioadmin" AWS_SECRET_ACCESS_KEY="minioadmin" aws s3 ls --endpoint-url "http://localhost:9999/" s3://mybucket/

docker kill testminio
```

I've also tried changing ownership of the directory and files from my own user to `root:root` and same results. As noted below, using a previous version like `RELEASE.2022-05-26T05-48-41Z` works and lists the `test.txt`.

```
sudo chown -R root:root /tmp/mytest/
```

And I've made sure to delete the .sys directory inbetween tests:

```
sudo rm -r /tmp/mytest/.minio.sys
```

## Context

See above for how I'm using this.

## Regression

Yes. Works in `RELEASE.2022-05-26T05-48-41Z`, fails in `RELEASE.2022-06-02T02-11-04Z`.

## Your Environment

* Version used (`minio --version`): See above for release names.
* Server setup and configuration: docker on Ubuntu/PopOS (docker.io 20.10.12) and MacOS.
* Operating System and version (`uname -a`): `Linux janet 5.17.15-76051715-generic #202206141358~1655919116~21.10~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by djhoese** [comment]
I should also note that my aws is configured with the recommend s3 signature version:

```
$ aws configure get default.s3.signature_version
s3v4
```

**Comment by harshavardhana** [comment]
We do not support filesystem mode anymore @djhoese you should see what is removed 

feat: Single drive XL implementation (#14970) (05/30/22) (Harshavardhana)

We have removed the legacy FS mode and it is not supported anymore. You cannot dump files on the backend directly anymore for MinIO to be discovered in single drive mode.

#14331 please read this thread.

**Comment by djhoese** [comment]
Wow. Thanks for letting me know. That PR title wasn't clear to me that it removed something related to "FS mode" or "pre-existing data".

I think the "Pre-existing data" section on the dockerhub page needs to be updated then:

https://hub.docker.com/r/minio/minio/

```
When deployed on a single drive, MinIO server lets clients access any pre-existing data in the data directory. For example, if MinIO is started with the command minio server /mnt/data, any pre-existing data in the /mnt/data directory would be accessible to the clients.

The above statement is also valid for all gateway backends.
```

**Comment by harshavardhana** [comment]
hub.docker.com is not updated with the latest README.md

**Comment by djhoese** [comment]
That's understandable, but is it something the maintainers of MinIO have the ability to change?

**Comment by harshavardhana** [comment]
> That's understandable, but is it something the maintainers of MinIO have the ability to change?

Yes just changed.

**Comment by ravindk89** [comment]
https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#pre-existing-data has a bit more detail.

**Comment by djhoese** [comment]
@ravindk89 At least for that last case where there are existing files/folders and no MinIO backend data, MinIO via the docker container was not raising an error. It was happy to accept requests, list buckets, but not list objects.
