### ISSUE TITLE
Minio memory usage increases

### ISSUE THREAD

**Issue by XuRong233** [minio/minio#15365]
Two sites, each site uses two servers and 4 drivers.Two site buckets are synchronized asynchronously.At present, a bucket is 9.9G, 680,455 objects, and about 10,000 objects are uploaded every day. It is possible that the memory usage of 68 and 69 is very different. There have been two times that the minio service on 69 hangs up because the memory usage of 69 is too large.
66.67Hosts configuration：
CPU：1
MEMORY：2.8G
OS：Linux release
68.69Hosts configuration：
CPU：1
MEMORY：2.8G
OS：Linux release

#!/bin/bash
export MINIO_ACCESS_KEY=qhadmin
export MINIO_SECRET_KEY=P8z77-vcs
/opt/minio/minio server \
--config-dir /opt/minio \
--address "192.168.8.67:25001" \
--console-address ":25011" \
http://192.168.8.66:25001/data/miniodata1 \
http://192.168.8.66:25001/data/miniodata2 \
http://192.168.8.67:25001/data/miniodata1 \
http://192.168.8.67:25001/data/miniodata2 \

#!/bin/bash
export MINIO_ACCESS_KEY=qhadmin
export MINIO_SECRET_KEY=P8z77-vcs
/opt/minio/minio server \
--config-dir /opt/minio \
--address "192.168.8.68:25001" \
--console-address ":25011" \
http://192.168.8.68:25001/data/miniodata1 \
http://192.168.8.68:25001/data/miniodata2 \
http://192.168.8.69:25001/data/miniodata1 \
http://192.168.8.69:25001/data/miniodata2 \
                 68             69            66            67
2022.7.15	194M	161M	197.9M	308.4M		
2022.7.18	359M	628M	199.6M	311.6M
2022.7.19	342.9M	731.2M	190.1M	266.4M
2022.7.20	409M	778.9M	186.2M	265.1M
2022.7.21	528M	934M	188.6M	300.9M

The following is the number of api requests I track and count on each server through MinIO server http.
5min	getObject	putObject	HeadObject	HeadBucket	GetBucketLocation	PutBucketPolicy	sum
66	        216	                0	                0	                0	                 0	                        0	                        216
67	        213	                55	                225	                0	                 23	                        0	                         516
68	        777	                55（67 async）0	                55(67 async)	 0	                        55	                         942
69	        783	                0	               108	                0	                 0	                         0	                         891
							
10min	getObject	putObject	HeadObject	HeadBucket	GetBucketLocation	PutBucketPolicy	sum
66	        591	                0	                 0	                0	                0                             	0	                        591
67	        589	                245	                 631              	0	                62                     	0	                        1527
68	        1416	        244(67 async)	 0	                244(67 async)	0                         	244	                        1660
69	        1418	        0	                 0	                240              	0                       	0                          	 1658

## Your Environment

* Version used (`2022-05-04T07:45:27Z`):
* Server setup and configuration:Server setup and configuration:Two sites, each site uses two servers and 4 drivers.
* Operating System and version (`Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`):

**Comment by harshavardhana** [comment]
> CPU：1
> MEMORY：2.8G
> OS：Linux release
> 68.69Hosts configuration：
> CPU：1
> MEMORY：2.8G
> OS：Linux release

This is terrible amount of memory for MinIO servers, please give it some meaningful resources to operate.
