### ISSUE TITLE
How can I forcibly remove a bucket with a retention policy ?

### ISSUE THREAD

**Issue by baofengzhouyu** [minio/minio#15371]
**Is your feature request related to a problem? Please describe.**
I got an error when i delete a bucket with a retention policy.

mc rb minio/tmp2  --force
mc: <ERROR> Failed to remove `minio/tmp2`. Object, 'tiflash.zip (Version ID=97141b9d-3078-47ed-afe3-174643514122)' is WORM protected and cannot be overwritten.

**Describe the solution you'd like**
I want to remove this bucket tmp2 without retaining any data.

**Describe alternatives you've considered**
I try to do the following ,i got the same error.

mc retention clear minio/tmp2/ -r
Unable to clear object retention on `minio/tmp2/tiflash.zip`: Object is WORM protected and cannot be overwritten.
mc: <ERROR> Invalid URL Object is WORM protected and cannot be overwritten
mc: <ERROR> Unable to find any object/version to clear its retention.

**Additional context**
![image](https://user-images.githubusercontent.com/49833028/180182080-a41d50d4-87e5-44e8-ada4-d9767ab5fa98.png)

**Comment by polaris-phecda** [comment]
The retention policy you set is Governance mode  or Compliance mode？

- In compliance mode, a protected object version can't be overwritten or deleted by any user including the root user in your AWS account.
- In governance mode, users can't overwrite or delete an object version or alter its lock settings unless they have special  permissions. If you try to delete objects protected by governance mode and have s3:BypassGovernanceRetention  or s3:GetBucketObjectLockConfiguration permissions, the operation will succeed.

tips：
[object-lock-retention-modes](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock-overview.html#object-lock-retention-modes)
I found these content at [bucket-object-lock.go](https://github.com/minio/minio/blob/master/cmd/bucket-object-lock.go)

**Comment by baofengzhouyu** [comment]
> 您设置的保留策略是治理模式还是合规模式？
> 
> * 在合规模式下，任何用户（包括您的 AWS 账户中的根用户）都不能覆盖或删除受保护的对象版本。
> * 在治理模式下，用户不能覆盖或删除对象版本或更改其锁定设置，除非他们具有特殊权限。如果您尝试删除受治理模式保护且具有 s3:BypassGovernanceRetention 或 s3:GetBucketObjectLockConfiguration 权限的对象，则操作将成功。
> 
> Tips： [object-lock-retention-modes我在](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock-overview.html#object-lock-retention-modes)[bucket-object-lock.go](https://github.com/minio/minio/blob/master/cmd/bucket-object-lock.go) 找到了这些内容[](https://github.com/minio/minio/blob/master/cmd/bucket-object-lock.go)



> The retention policy you set is Governance mode or Compliance mode？
> 
> * In compliance mode, a protected object version can't be overwritten or deleted by any user including the root user in your AWS account.
> * In governance mode, users can't overwrite or delete an object version or alter its lock settings unless they have special  permissions. If you try to delete objects protected by governance mode and have s3:BypassGovernanceRetention  or s3:GetBucketObjectLockConfiguration permissions, the operation will succeed.
> 
> tips： [object-lock-retention-modes](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock-overview.html#object-lock-retention-modes) I found these content at [bucket-object-lock.go](https://github.com/minio/minio/blob/master/cmd/bucket-object-lock.go)

Thank you for your reply.
I've set both modes，I forgot that one was earlier. how can i get the modes config ?
My user permission is s3:*.
![image](https://user-images.githubusercontent.com/49833028/180197061-11265406-68e3-4d31-a05c-efc9e3cff53e.png)

**Comment by baofengzhouyu** [comment]
Thank you for your reply.
 I've set both modes，I forgot that one was earlier. how can i get the modes config ?
 My user permission is s3:*. 
![image](https://user-images.githubusercontent.com/49833028/180197061-11265406-68e3-4d31-a05c-efc9e3cff53e.png)
