### ISSUE TITLE
Rare bug: uploaded file is corrupted

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#1537]
```
~/w/gospace/src/github.com/minio/mc $ mc rm myminio/bucket1/1gb.bin
Removed ‘myminio/bucket1/1gb.bin’.
~/w/gospace/src/github.com/minio/mc $ mc session resume TGbiAkQk
mc: <ERROR> Session ‘TGbiAkQk’ not found. 
~/w/gospace/src/github.com/minio/mc $ mc cp 1gb.bin myminio/bucket1
mc: <ERROR> Failed to copy ‘1gb.bin’. Object key is missing, object key cannot be empty
1gb.bin:                             1024.00 MB / 1024.00 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 24.54 MB41s
~/w/gospace/src/github.com/minio/mc $ mc ls myminio/bucket1/
[2016-05-08 20:17:06 CET] 4.0GiB 4gb.bin
[2016-05-08 20:05:54 CET] 8.0GiB 8gb.bin
[2016-05-08 20:32:48 CET]     0B 1gb.bin/
~/w/gospace/src/github.com/minio/mc $ mc ls myminio/bucket1/1gb.bin/
mc: <ERROR> Unable to stat ‘myminio/bucket1/1gb.bin/’. Requested file ‘/bucket1/1gb.bin/’ not found
~/w/gospace/src/github.com/minio/mc $ 
```

I didn't touch anything after this bug so we can be sure when we debug

**Comment by harshavardhana** [comment]
@vadmeste are you using the latest master?

**Comment by vadmeste** [comment]
@harshavardhana, a205aca6d272fa1cd070da6dc2d21008555bc8a5 is the last commit of minio that I've compiled today

**Comment by vadmeste** [comment]
```
~/w/gospace/src/github.com/minio/minio $ minio version
Version: 2016-05-08T18:58:16Z
Release-Tag: DEVELOPMENT.2016-05-08T18-58-16Z
Commit-ID: a205aca6d272fa1cd070da6dc2d21008555bc8a5
```

**Comment by harshavardhana** [comment]
> ~/w/gospace/src/github.com/minio/minio $ minio version
> Version: 2016-05-08T18:58:16Z
> Release-Tag: DEVELOPMENT.2016-05-08T18-58-16Z
> Commit-ID: a205aca6d272fa1cd070da6dc2d21008555bc8a5

Yeah that seems latest enough can you paste the backend details here? - it seems like the `1gb.bin` deletion failed some other sort of backend issue.  

Also is it possible to access this box?

**Comment by harshavardhana** [comment]
> ~/w/gospace/src/github.com/minio/minio $ minio version
> Version: 2016-05-08T18:58:16Z
> Release-Tag: DEVELOPMENT.2016-05-08T18-58-16Z
> Commit-ID: a205aca
> Yeah that seems latest enough can you paste the backend details here? - it seems like the 1gb.bin deletion failed some other sort of backend issue.
> 
> Also is it possible to access this box?

Found the problem no need.

**Comment by vadmeste** [comment]
great, tried to install tmate for Debian but it turned out it needs recent version of some libraries, also tmate.io only provides x86 static binary..

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/1539 - the fix is here..

**Comment by krishnasrinivas** [comment]
@harshavardhana what was the bug?

**Comment by harshavardhana** [comment]
> @harshavardhana what was the bug?

The bug was part of the go-routine itself,  an err value spilled over and it tried to delete the file received errFileNotFound. 

Removing that part fixes the problem of not completing the multipart.
