### ISSUE TITLE
MinIO File upload failues to the bucket : Error: healErasureSet: No non-healing disks found (*errors.errorString)

### ISSUE THREAD

**Issue by nisam76** [minio/minio#15380]
API: SYSTEM()
Time: 07:51:51 UTC 07/15/2022
DeploymentID: f1d71a5d-ce1b-410f-80dd-17b695e21ee4
Error: healErasureSet: No non-healing disks found (*errors.errorString)
       1: cmd/background-newdisks-heal-ops.go:427:cmd.monitorLocalDisksAndHeal.func2()
Found drives to heal 1, proceeding to heal content...
Healing disk '/data' on 1st pool

API: SYSTEM()
Time: 07:52:01 UTC 07/15/2022
DeploymentID: f1d71a5d-ce1b-410f-80dd-17b695e21ee4
Error: healErasureSet: No non-healing disks found (*errors.errorString)
       1: cmd/background-newdisks-heal-ops.go:427:cmd.monitorLocalDisksAndHeal.func2()
Found drives to heal 1, proceeding to heal content...
Healing disk '/data' on 1st pool

## Expected Behavior
File operation should be successful.

## Current Behavior
File operations fails.

We tried upgrade of image 
                Existing Image                   phx-epddtr-prd.bmc.com/bmc/lp0lz:21303-v1-bitnami-minio-2021.4.18-debian-10-r0
                New latest Image             phx-epddtr-prd.bmc.com/bmc/lpade:minio-2022.7.17-debian-11-r0
Didn;t solve the problem and we couldnt login to minio console after the upgrade.
Reverted to the original image and that resoved the issue !!!!!!!!!!!!

## Your Environment
Deployed on K8S Cluster.

**Comment by harshavardhana** [comment]
@nisam76 upgrading for such old releases requires that you upgrade all servers together - you cannot upgrade one server at a time. 

Also we do not support bitnami container images please migrate to using our official container images and use our operator for best experience on k8s. 

If you want production support please sign up https://minio.io/pricing
