### ISSUE TITLE
Trace MinIO server http incomplete record

### ISSUE THREAD

**Issue by XuRong233** [minio/minio#15383]
I updated the minio version to 2022-07-17T15:43:14Z; use mc admin trace -v minio-server > trace.log to trace the MinIO server http, and found that the records are incomplete.
Like this:
192.168.8.69:25001 [REQUEST s3.GetObject] [0001-01-01T08:05:43:000] [Client IP: ]
192.168.8.69:25001  
192.168.8.69:25001 Proto: 
192.168.8.69:25001 Host: 
192.168.8.69:25001 
192.168.8.69:25001 [RESPONSE] [0001-01-01T08:05:43:000] [ Duration 0s  ↑ 0 B  ↓ 0 B ]
192.168.8.69:25001 0 
192.168.8.69:25001 
192.168.8.69:25001 
192.168.8.69:25001 [REQUEST s3.HeadObject] [0001-01-01T08:05:43:000] [Client IP: ]
192.168.8.69:25001  
192.168.8.69:25001 Proto: 
192.168.8.69:25001 Host: 
192.168.8.69:25001 
192.168.8.69:25001 [RESPONSE] [0001-01-01T08:05:43:000] [ Duration 0s  ↑ 0 B  ↓ 0 B ]
192.168.8.69:25001 0 
192.168.8.69:25001 
192.168.8.69:25001 
192.168.8.68:25001 [REQUEST s3.GetObject] [0001-01-01T08:05:43:000] [Client IP: ]
192.168.8.68:25001  
192.168.8.68:25001 Proto: 
192.168.8.68:25001 Host: 

## Your Environment

* Version used (` 2022-07-17T15:43:14Z`):
* Server setup and configuration:Two sites, each site uses two servers and 4 drivers.
* Operating System and version (`Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`):

**Comment by harshavardhana** [comment]
You need to upgrade your mc also when you upgrade server.
