### ISSUE TITLE
ArtifactHub Repository out of date

### ISSUE THREAD

**Issue by austince** [minio/minio#15388]
The minio/minio repository on ArtifactHub is using `helm.min.io` instead of `charts.min.io`: https://artifacthub.io/packages/helm/minio/minio
Does anyone have control over this on ArtifactHub? I've created a new repo there, pointing to `charts.min.io`, but would be happy to remove it if the original one is updated: https://artifacthub.io/packages/helm/minio-official/minio

**Comment by harshavardhana** [comment]
We do not publish to artifacthub or maintain it - we publish officially operators on operatorhub and that is what we maintain. 

We have no plans to update artifacthub updated you can simply follow our docs here https://github.com/minio/minio/tree/master/helm/minio
