### ISSUE TITLE
When changing bucket permissions or deleting a bucket, the page jumps to the login interface

### ISSUE THREAD

**Issue by noovertime7** [minio/minio#15382]
## Expected Behavior
change bucket permissions

## Current Behavior
When changing bucket permissions or deleting a bucket, the page jumps to the login interface,

Background log：
![lQLPJxaE3bI__cnNAi7NB32w7cMcHzvKvvsC2sED3YCEAA_1917_558](https://user-images.githubusercontent.com/100392073/180376546-706a7e9d-1033-4e4e-a00f-de60851b1c62.png)

API: AccountInfo()
Time: 06:12:42 UTC 07/22/2022
DeploymentID: fe2dd602-b7c1-4bcd-a2fd-9af5e24954db
RequestID: 170412020F95C843
RemoteHost: 172.17.0.2
Host: 172.17.0.2:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
Error: config file not found (*errors.errorString)
       2: cmd/admin-handlers-users.go:1064:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()

## Possible Solution
Hoping for help

## Steps to Reproduce (for bugs)

1.Change the deployment mode to binary, and the problem is not resolved
2.Reinstall the system, the problem is not solved
3.Deployed on k8S, the problem is not solved

## Context
My app uses Minio as object storage and I've been having trouble loading images for a week because I can't adjust bucket permissions

## Your Environment

*  minio version RELEASE.2022-01-04T07-41-07Z
*  Minio started with this command：  server /data --console-address ":9001"
*  Linux ecs-10.1.3.45.novalocal 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*  Docker version 20.10.14, build a224086

**Comment by harshavardhana** [comment]
> * minio version RELEASE.2022-01-04T07-41-07Z

You should definitely upgrade - this issue is already fixed @noovertime7

**Comment by noovertime7** [comment]
The latest minio image is used. If you need to upgrade, do you have the image version number to upgrade

**Comment by harshavardhana** [comment]
> The latest minio image is used. If you need to upgrade, do you have the image version number to upgrade

https://github.com/minio/minio/releases/tag/RELEASE.2022-07-17T15-43-14Z

**Comment by noovertime7** [comment]
Thanks a lot. I have modified it successfully using SDK just now
