### ISSUE TITLE
minio compression not working in Latest version RELEASE.2022-07-17T15-43-14Z

### ISSUE THREAD

**Issue by ramkicse** [minio/minio#15392]
## Expected Behavior

once compression is enabled using `mc admin config set myminio compression enable=on` then all following uploaded files should reduced the file size in disk space

## Current Behavior

before enable compression i checked 
```
mc du myminio/b1/
mc ls myminio/b1/
```
both above commands showing 55.7KB file size
i removed the file and enable commpression, and upload the file still shows 
same file size.
one month back i tested old version minio that time shows reduced value.

## Steps to Reproduce (for bugs)

1. `mc mb myminio/buk1`
2. `mc cp aaa.txt myminio/buk1`
3. `mc ls myminio/buk1`
4. `mc du myminio/buk1`
5. `mc rm myminio/buk1/aaa.txt`
6.  ` mc admin config set myminio/buk1 compression  enable=on`
7.  `mc admin config get myminio/buk1 compression`
8.  `mc cp aaa.txt myminio/buk1`
9. ` mc ls myminio/buk1`
10.  `mc du myminio/buk1`

before and after compression still value are same

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2022-07-17T15-43-14Z (commit-id=b6eb8dff649b0f46c12d24e89aa11254fb0132fa)
Runtime: go1.18.4 linux/amd64
```
* Server setup and configuration:
* Operating System and version (`uname -a`):
` Linux LAPTOP-469CQHO1 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
![minio_commpress](https://user-images.githubusercontent.com/1916923/180640184-536cb93d-3e2c-429f-afaf-50917ff52c4d.jpg)

**Comment by klauspost** [comment]
@ramkicse Files below or at 4KB are not compressed. It is rarely a gain and just takes resources. Files typically takes up 4K on disk anyway.

**Comment by ramkicse** [comment]
@klauspost  kindly check again. now i added 55.7KB file.
even i tested 1.5GB file also. kindly check the screenshot
![minio_commpress](https://user-images.githubusercontent.com/1916923/180640248-a0b66682-f4e3-4a9a-a32e-bf50e957e32e.jpg)

**Comment by klauspost** [comment]
@ramkicse You cannot see compression using the S3 API. It is transparent, so using du the file will always have the uncompressed size.

**Comment by klauspost** [comment]
You are welcome to send `mc support inspect myminio/buk1/aaa.txt/**` and I can tell you the compressed size.

**Comment by ramkicse** [comment]
i ran mc support inspect myminio/buk1/aaa.txt/**

here the file
[inspect.c01798e6.zip](https://github.com/minio/minio/files/9175467/inspect.c01798e6.zip)

**Comment by klauspost** [comment]
The file is compressed to 30 bytes.

**Comment by ramkicse** [comment]
> The file is compressed to 30 bytes.

how i can get those details

**Comment by klauspost** [comment]
You can observe the size on disk, or compile the [xl-meta](https://github.com/minio/minio/tree/master/docs/debugging/xl-meta) tool to inspect metadata.

**Comment by klauspost** [comment]
The `xl.meta` file itself will also contain `X-Minio-Internal-compression`:

![image](https://user-images.githubusercontent.com/5663952/180641127-4c89e2b9-7c92-43a4-a1f4-8b3af148a21c.png)

**Comment by ramkicse** [comment]
> You can observe the size on disk, or compile the [xl-meta](https://github.com/minio/minio/tree/master/docs/debugging/xl-meta) tool to inspect metadata.

ok thankyou @klauspost  
any otherway to show ? may be UI

**Comment by klauspost** [comment]
No UI.

**Comment by ramkicse** [comment]
> The `xl.meta` file itself will also contain `X-Minio-Internal-compression`:
> 
> ![image](https://user-images.githubusercontent.com/5663952/180641127-4c89e2b9-7c92-43a4-a1f4-8b3af148a21c.png)

thanks

**Comment by ramkicse** [comment]
> The `xl.meta` file itself will also contain `X-Minio-Internal-compression`:
> 
> ![image](https://user-images.githubusercontent.com/5663952/180641127-4c89e2b9-7c92-43a4-a1f4-8b3af148a21c.png)

@klauspost 2 months back i tested minio (may 2 month old version) using UI console, that time i enabled compression and upload 5 GB file, then its added some metadata related to compression automatically, like compression type is S2 and few more.

now latest version its not showing anything, i can see the compresson  size is 30 via xl-meta tool.
2 month back that time i can see the compressed size in du and ls command

**Comment by klauspost** [comment]
It is as it is expected to be.
