### ISSUE TITLE
XL: CompleteMultipartUpload() code issue (13th)

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1540]
```
        for index, part := range parts {
                wg.Add(1)
                go func(index int, part completePart) {
                        defer wg.Done()
                        partSuffix := fmt.Sprintf("%.5d.%s", part.PartNumber, part.ETag)
                        multipartPartFile := path.Join(mpartMetaPrefix, bucket, object, uploadID, partSuffix)
                        tmpMultipartObjSuffix := path.Join(tmpMetaPrefix, bucket, object, partNumToPartFileName(part.PartNumber))
                        rErr := xl.storage.RenameFile(minioMetaBucket, multipartPartFile, minioMetaBucket, tmpMultipartObjSuffix)
                        if rErr != nil {
                                errs[index] = rErr
                                log.Errorf("Unable to rename file %s to %s, failed with %s", multipartPartFile, tmpMultipartObjSuffix, rErr)
                                return
                        }
                        multipartObjSuffix := path.Join(object, partNumToPartFileName(part.PartNumber))
                        rErr = xl.storage.RenameFile(minioMetaBucket, tmpMultipartObjSuffix, bucket, multipartObjSuffix)
                        if rErr != nil {
                                if dErr := xl.storage.DeleteFile(minioMetaBucket, tmpMultipartObjSuffix); dErr != nil {
                                        errs[index] = dErr
                                        log.Errorf("Unable to delete file %s, failed with %s", tmpMultipartObjSuffix, dErr)
                                        return
                                }
                                log.Debugf("Delete file succeeded on %s", tmpMultipartObjSuffix)
                                errs[index] = rErr
                                log.Errorf("Unable to rename file %s to %s, failed with %s", tmpMultipartObjSuffix, multipartObjSuffix, rErr)
                        }
                }(index, part)
        }
```

Here rename to a temporary location is not needed. Renaming to tmp location is useful only for DeleteObject operation (so that it can be renamed back if there was a quorum error)

For the code above as this is a rename process, if there was a quorum error during rename it can just be renamed back. But renaming few parts and not renaming few parts will be harmful. In the end either all should be renamed or none.

If we use hardlinks we can handle this situation, instead of rename just create hardlinks at the destination, if hardlinks were created successfully for all the parts we can delete the part files in .minio/multipart

Also lock needs to be held for the entire process, else if two complete-multipart-uploads compete it can create a corrupted object as few parts will be of one uploadID and few parts will be of another uploadID.

**Comment by harshavardhana** [comment]
> Here rename to a temporary location is not needed. Renaming to tmp location is useful only for DeleteObject operation (so that it can be renamed back if there was a quorum error)
> 
> For the code above as this is a rename process, if there was a quorum error during rename it can just be renamed back. But renaming few parts and not renaming few parts will be harmful. In the end either all should be renamed or none.
> 
> If we use hardlinks we can handle this situation, instead of rename just create hardlinks at the destination, if hardlinks were created successfully for all the parts we can delete the part files in .minio/multipart
> 
> Also lock needs to be held for the entire process, else if two complete-multipart-uploads compete it can create a corrupted object as few parts will be of one uploadID and few parts will be of another uploadID.

This is correct, we need to hold locks here,  but hardlink idea is not needed. We can hold lock and not move to temp location.

**Comment by krishnasrinivas** [comment]
still, even if we hold locks, the transaction is : _all the part files should be renamed or none should be renamed._ things will go wrong if few renames succeed and few don't.

Corner case though. If we want to handle it hardlinks is one solution, because if creation of hardlinks for all the part files fail, we still have the files at the `.minio/multipart` location intact.

**Comment by harshavardhana** [comment]
> still, even if we hold locks, the transaction is : all the part files should be renamed or none should be renamed. things will go wrong if few renames succeed and few don't.

This is true, but in current scenario we agreed that small window of this sort is fine.  We fix it not here but outside we allow this to be easy to recover.  That is why the actual meta file is written after all the parts have been renamed. You would end with lot of dangling files though, but these can be cleared outside of the operation itself.

**Comment by harshavardhana** [comment]
> This is true, but in current scenario we agreed that small window of this sort is fine. We fix it not here but outside we allow this to be easy to recover. That is why the actual meta file is written after all the parts have been renamed. You would end with lot of dangling files though, but these can be cleared outside of the operation itself.

Another thing is to avoid all these issues we need to have a transaction support and log which provides the authority of knowing what operations went in and what should be rolled back.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/1539 - this patch now removes the Rename code for temp location.

**Comment by krishnasrinivas** [comment]
fixes by harsha and https://github.com/minio/minio/pull/1606 make the code much better.
