### ISSUE TITLE
Feature Request: Versioning support for minio edge

### ISSUE THREAD

**Issue by sjdrc** [minio/minio#15423]
# What I want to accomplish

I want to be able to read SQLite databases directly from minio buckets over http, while caching regularly accessed files.

#### Querying SQLite databases

I have tested [michalc/sqlite-s3-query](https://github.com/minio/minio/tree/master/docs/disk-caching) and am able to query databases directly from minio buckets that have versioning enabled.

#### Caching

I would also like to utilise [minio disk caching](https://github.com/minio/minio/tree/master/docs/disk-caching) to keep regularly accessed databases close to the services that query the databases. 

## The problem

`minio gateway` is being deprecated and does not support versioning as per #10108.

I understand that `minio gateway` is being replaced with `minio edge`:

>This issue shall be closed now, we haven't moved `minio gateway s3` to `minio edge` yet - this will be subsequently finished which would bring `minio edge` to speak to only MinIO servers.

_Originally posted by @harshavardhana in https://github.com/minio/minio/issues/14331#issuecomment-1144450728_

## My question

Would it be possible for `minio edge` to support proxying upstream buckets given that it will only have to deal with minio and not the convoluted Azure/GCP versioning backends? This feature would be amazing for a number of applications, such as transparently caching machine learning datasets on training machines. This would make life a lot easier for things like neural network training pipelines.

## Our current solution

We've currently been solving this issue by using an rclone fuse mount to an s3 bucket and reading SQLite databases over this mount. `rclone mount` has a [caching feature](https://rclone.org/commands/rclone_mount/#vfs-file-caching), but we have found a number of issues with the fuse mount, and ideally we will move the caching off to something else (like `minio edge`, for example). This solution is also quite brittle and a significant amount of engineering has gone into building and debugging issues with it.

**Additional context**
Minio is damn awesome, and we want to use it wherever we can!

**Comment by harshavardhana** [comment]
Edge catching may be able to support versioning but it's not a priority at the moment.

**Comment by sjdrc** [comment]
Thanks for the fast response! Glad to know that you may consider this feature.

In the meantime, do you have any ideas for how we could accomplish this without disk caching?

I've looked into [Policy-Based Object Tiering](https://min.io/product/automated-data-tiering-lifecycle-management) which states:

> MinIO can programmatically configure object storage tiering so that objects transition from one state or class to another based on any number of variables

[This example](https://docs.min.io/minio/baremetal/lifecycle-management/transition-objects-to-s3.html#create-and-apply-the-transition-rule) shows how to transition objects after a certain amount of time, but is there a mechanism to move an object to a higher tier upon access? Looks like Amazon supports this through a feature called [S3 Intelligent-Tiering](https://aws.amazon.com/s3/storage-classes/intelligent-tiering/).

**Comment by sjdrc** [comment]
@harshavardhana I'm unable to deploy a disk caching gateway to another minio instance with the current chart - it looks like this has already been deprecated? Is there a way I can run minio in edge mode to allow for the disk caching use-case currently?

**Comment by harshavardhana** [comment]
> @harshavardhana I'm unable to deploy a disk caching gateway to another minio instance with the current chart - it looks like this has already been deprecated? Is there a way I can run minio in edge mode to allow for the disk caching use-case currently?

We do not allow new gateway deployments anymore, if you were already using it will continue to work but not new deployments.

**Comment by harshavardhana** [comment]
There are no current plans and we are moving away from this as an important usecase
