### ISSUE TITLE
Feature request: bring back the legacy FS backend

### ISSUE THREAD

**Issue by lachesis** [minio/minio#15455]
**Is your feature request related to a problem? Please describe.**
Minio should support serving a simple filesystem directory over the S3 API and via the console. The files should be stored in simple directories with their names equivalent to their object names (whenever possible by underlying filesystem). This format is incredibly simple and portable, allowing basic filesystem tools to be used to manage the repository, and preventing data from becoming captive in minio.

**Describe the solution you'd like**
I would like Minio to work like it used to, back in RELEASE.2022-05-26T05-48-41Z, where the "legacy" FS backend still worked.

**Describe alternatives you've considered**
I've considered pinning that old version forever, but that seems unwise from security point of view. I've also considered other tools, but I like minio better.

**Additional context**
Some related threads and links:
#15352
#14331
https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#pre-existing-data

**Comment by harshavardhana** [comment]
@lachesis that ship has sailed - we are not bringing it back - read here https://blog.min.io/deprecation-of-the-minio-gateway/

**Comment by lachesis** [comment]
Unfortunate; I do not consider POSIX filesystems to be "legacy technologies". Very well, I will pin at the old version indefinitely at home, and if I am ever looking for a cloud gateway product at work, I will _not_ be using minio anymore.
