### ISSUE TITLE
vanilla helm chart:  decreasing the number of replicas results in error (looking for a proper way to change topology)

### ISSUE THREAD

**Issue by one1zero1one** [minio/minio#15451]
## Expected Behavior
Changing the number of replicas should result in having less replicas while functionality is maintained.

## Current Behavior

Changing the number of replicas from 4 to 3 results in containers failing with error:

```
ERROR Invalid command line arguments: Incorrect number of endpoints provided [http://min-io-minio-{0...2}.min-io-minio-svc.data.svc.cluster.loc
al/export]
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

## Steps to Reproduce (for bugs)

1. Deploy chart (in my case via ArgoCD) with defaults, with `replicas: 4` in `values.yaml`
2. Decrease the values of replicas.

## Context
I'm running minio chart with 4 replicas (in 4 different az). I would like to reduce the number of replicas to 1, as I'm trying to reduce the cost of inter-az traffic. The end goal is to move the replicas to the same az, so my plan is first to scale down then to scale back up while limiting to the same az. I am trying to do this on a production system.

I have tried:
- decreasing the replicas one by one -> error
- changing the mode to standalone -> a new PV/C is created, which means I would need to migrate the data (downtime).

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
Deploying with ArgoCD to EKS 1.22, helm chart `4.0.6`

**Comment by harshavardhana** [comment]
@one1zero1one this is expected and by design - you can't just go from erasure coding to not having erasure coding on the same setup.
