### ISSUE TITLE
Latency when we load bucket 

### ISSUE THREAD

**Issue by Ilhaame** [minio/minio#15467]
When we request Loki trough Minio we get this error message on Grafana : 

![image](https://user-images.githubusercontent.com/87648804/182823404-4bf73be7-2b24-4a8e-aff0-7ff9a3a2f372.png)

When we try to open bucket from the Minio Interface we get some latency : 

![image](https://user-images.githubusercontent.com/87648804/182823119-66ef4ac7-d303-44a1-8095-230976c0e082.png)

-- 

To know, i have this issue since i update the version. Before, I was on the version minio.RELEASE.2022-04-26T01-20-24Z with mc version mc.RELEASE.2022-02-02T02-03-24Z, and know i have the version minio.RELEASE.2022-07-17T15-43-14Z with mc version mc.RELEASE.2022-07-15T09-20-55Z

Thanks for your helps

**Comment by harshavardhana** [comment]
@Ilhaame how many objects do you have and how they are spread out? Are you using versions ? 

Please also explain your setup details there is nothing much to go in this issue reporting.

**Comment by Ilhaame** [comment]
Thanks for your response.


how many objects do you have and how they are spread out?
We have 35 043 objects:
![image](https://user-images.githubusercontent.com/87648804/182872144-a1af507e-26ae-4de1-adbe-00d2907d88cf.png)


Are you using versions ?
Yes:
![image](https://user-images.githubusercontent.com/87648804/182872509-b44a0247-5f83-40a9-8e00-63c09e1f0b3f.png)

We have 2 nodes with 8 drives: 
![image](https://user-images.githubusercontent.com/87648804/182874285-7b239335-692f-4832-a18e-e757470ffa2a.png)


When i start a bucket and start trace we can see some request with IP location return 404 not found where as there are others request with dns name in location return 200 OK

![image](https://user-images.githubusercontent.com/87648804/182875861-5bea1370-0a38-4b32-ac16-e61c0b753610.png)

**Comment by harshavardhana** [comment]
> We have 35 043 objects:

The issue you reported is for a bucket with 2million objects https://user-images.githubusercontent.com/87648804/182823119-66ef4ac7-d303-44a1-8095-230976c0e082.png 

how are they spread out? @Ilhaame

**Comment by Ilhaame** [comment]
We have 15 buckets in our primary minio.
The bucket with 2million objectis is for production.
And the bucket with 35 043 is for testing environement etc .
We have the same problem with all bucket (latency and timeout when I run a grafana query since 7 days).

Thanks for your response

how are they spread out ?

For the primary, we have 2 nodes , and we send loki data with a VIP address.
The objects are distributed between the four disks of each node, therefore on eight disks in total.

After 15 days in general, but it depends on the buckets, the objects are moved to minio archiv , so on four disks.
Normaly, You have to see the distribution on the disks as Raid,

**Comment by harshavardhana** [comment]
Can you capture `mc admin trace -a` when you run `grafana` query?

**Comment by Ilhaame** [comment]
Hi @harshavardhana, 

there are the logs with grafana query . I also added the logs when I open a bucket 

[log.zip](https://github.com/minio/minio/files/9267105/log.zip)

![image](https://user-images.githubusercontent.com/87648804/183042435-bbc6b7ff-ea35-411e-a013-16ce14480325.png)

Thanks

**Comment by harshavardhana** [comment]
@Ilhaame looks like you have enabled versioned bucket and you have a lot of versions on the bucket which is taking time to load. 

Can you do `mc ls -r --versions` and see how much time it will take in total . So the issue is a lot of versions in xl.meta.

**Comment by harshavardhana** [comment]
And also as I suspected the Loki dumps the data incorrectly without a proper hierarchy - and this is slowing down the listing as the number of objects increase your problems will increase. 

```
logRequestGrafana.txt:2022-08-05T10:22:20.401 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/c4d035ff014caf12%3A1826ce1e256%3A1826ce1e290%3Ac325f46b 172.23.3.113      12.734ms     ↑ 2.4 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:20.801 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/1e8dbae4493257b2%3A1826ce1eb06%3A1826ce1eb07%3A6d9d8682 172.23.3.113      10.673ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.099 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/4240542e6442fdfa%3A1826ce148d3%3A1826ce148d4%3Abd5b483e 172.23.3.113      10.582ms     ↑ 1.2 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.200 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/4e073e5b71d0f90b%3A1826ce1e206%3A1826ce1e283%3Abf549b35 172.23.3.113      11.225ms     ↑ 2.3 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.292 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/1b958a9ad67a328d%3A1826ce22508%3A1826ce22509%3Af3b2a968 172.23.3.113      19.464ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.292 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/38520086ef479e56%3A1826ce15696%3A1826ce157f3%3Ab9294077 172.23.3.113      19.727ms     ↑ 1.3 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.292 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/20d60b872b33098e%3A1826cd67c6e%3A1826ce223d7%3A3ffd4cea 172.23.3.113      20.65ms      ↑ 2.1 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.300 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/df6be0abaab44549%3A1826ce1f890%3A1826ce1f891%3Aa6adaa11 172.23.3.113      22.03ms      ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.391 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/46cf048c414ed4a%3A1826ce1f0c1%3A1826ce1f0c2%3A423f0ec9 172.23.3.113      23.421ms     ↑ 1.9 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.400 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/d73f367c9f94e126%3A1826ce14b30%3A1826ce14b32%3A43f46997 172.23.3.113      21.108ms     ↑ 1.1 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.394 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/9b7d162683808703%3A1826ce22508%3A1826ce22509%3A8203f6cd 172.23.3.113      27.256ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.393 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/f35a6dc857950f5c%3A1826ce148d3%3A1826ce1490b%3A4deaeba1 172.23.3.113      44.536ms     ↑ 1.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.403 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/bf5e587ce1fdcc19%3A1826ce1d3e8%3A1826ce1d3e9%3A3fb54b60 172.23.3.113      42.523ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.396 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/6b326357eebde184%3A1826ce22b5d%3A1826ce22b5e%3A8c043b6a 172.23.3.113      50.889ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.401 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/2f8544a1e3e2e935%3A1826ce234f7%3A1826ce234fe%3Acd3d1d01 172.23.3.113      56.564ms     ↑ 2.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.492 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/2a514103b8f14b78%3A1826ce14e81%3A1826ce15660%3A15fd63c1 172.23.3.113      12.429ms     ↑ 1.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.501 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/3bc9fbdcb630c6fa%3A1826ce22c19%3A1826ce22c2c%3A5eb72b63 172.23.3.113      12.462ms     ↑ 2.3 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:21.591 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/4e4f329da90f6a50%3A1826cd67c6e%3A1826ce223d6%3Adb7e42bb 172.23.3.113      11.157ms     ↑ 2.1 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:22.391 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/508b320fe5e92b56%3A1826d159b51%3A1826d18c7b1%3Ac0df3249 172.23.3.113      116.256ms    ↑ 601 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:22.592 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/e7c96fbb6481c4e9%3A1826ce21b2b%3A1826ce21b3c%3A4ea329e2 172.23.3.113      10.555ms     ↑ 2.2 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.410 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-integration2/fake/9214c42d2337632%3A1826ce1ba71%3A1826ce1bab7%3Ab470400 172.23.3.113      28.631ms     ↑ 1.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.411 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-integration2/fake/40f57fb667f420c7%3A1826ce1c44b%3A1826ce1c44c%3A58ffc5ed 172.23.3.113      28.74ms      ↑ 1.1 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.440 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-integration2/fake/45a15e2c1240d11%3A1826ce1d7fb%3A1826ce1d835%3Aa386f749 172.23.3.113      14.799ms     ↑ 1.3 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.440 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-integration2/fake/65d817d7adbbfb83%3A1826ce1a0e9%3A1826ce1a14f%3Aa2f7ee66 172.23.3.113      14.645ms     ↑ 1.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.445 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-integration2/fake/21c1745a05039f62%3A1826ce1ba71%3A1826ce1ba72%3Acc3ef72 172.23.3.113      18.062ms     ↑ 1.2 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.450 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-integration2/fake/85cbad398c0c6af0%3A1826ce1af8d%3A1826ce1afb8%3A65975775 172.23.3.113      15.155ms     ↑ 1.3 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.447 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-integration2/fake/26a51f2fe0be931a%3A1826ce1a8d1%3A1826ce1af6b%3Aa72246e 172.23.3.113      19.828ms     ↑ 1.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.501 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-integration2/fake/ca3f5de20320bc1c%3A1826ce1c857%3A1826ce1d79e%3Ae7d9281 172.23.3.113      11.477ms     ↑ 1.5 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.511 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-integration2/fake/a2873cfc904cb292%3A1826ce1a4f1%3A1826ce1a4f3%3Ada8d111 172.23.3.113      10.679ms     ↑ 1.1 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:24.515 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-integration2/fake/b376704c1569e023%3A1826ce1a0e9%3A1826ce1a0ea%3A18be4ae5 172.23.3.113      10.954ms     ↑ 1.2 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:25.193 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/fc7e3a2c8a2dfb6a%3A1826d149dd9%3A1826d18b8a9%3A4c2a317e 172.23.3.113      27.623ms     ↑ 568 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.048 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/47550e2ec089c970%3A1826ce286f5%3A1826ce286f6%3A28bce2c5 172.23.3.113      15.806ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.048 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/c5a0fc7e9ab927d3%3A1826ce29753%3A1826ce29754%3Ad73ee94c 172.23.3.113      17.365ms     ↑ 2.0 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.057 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/7d13342ca2057a9e%3A1826ce297a5%3A1826ce297a6%3A6696683f 172.23.3.113      24.752ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.140 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/f35f92414177da04%3A1826ce250f2%3A1826ce250ff%3Ab818dde4 172.23.3.113      9.161ms      ↑ 2.3 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.240 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/51ce187e06531439%3A1826ce26b02%3A1826ce26b03%3Aacc8391e 172.23.3.113      11.403ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.239 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/77fb824e28aae688%3A1826ce27b3c%3A1826ce27b3d%3Aaf17c3f6 172.23.3.113      13.226ms     ↑ 1.9 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.248 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/707b13da33fa0257%3A1826ce27c7e%3A1826ce27c7f%3A664c8b1f 172.23.3.113      12.881ms     ↑ 1.9 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.350 [200 OK] s3.PutObject mni-des-p01.csm.intra:9000/loki-production2/fake/f7bba19619210965%3A1826ce26c31%3A1826ce26c32%3A307b755c 172.23.3.113      13.576ms     ↑ 1.8 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.240 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/a5fc6ea8b6e3637a%3A1826d170608%3A1826d198115%3A5d267a5c 172.23.3.113      122.051ms    ↑ 549 KiB ↓ 408 B
logRequestGrafana.txt:2022-08-05T10:22:50.440 [200 OK] s3.PutObject mni-des-p02.csm.intra:9000/loki-production2/fake/d405fb3e9efe859e%3A1826ce27c7e%3A1826ce27c7f%3A45a6ab15 172.23.3.113      9.017ms      ↑ 1.9 KiB ↓ 408 B
```

Look at the key name here every object is inside a prefix called `fake` and no other further hierarchy. This means that just to list that prefix it needs to 

- Readdir of all entries
- Read xl.meta for each of those entries
- Sort them

These are expensive and totally unnecessary complications of how the namespace is laid out. These are filesystem limits because Readdir() would never return in the time we want them to return..

**Comment by harshavardhana** [comment]
I don't think anything can be done here this has nothing to do with upgrade - it is simply you reached a scale that cannot be scaled anymore for your deployment, this requires an architecture overhaul of your deployment.

2 nodes 8 drives are not sufficient for whatever you want to do here - you have also enabled versioning not sure if this is something you want to do. AFAIK Loki doesn't understand a versioned bucket so they would be creating lots of uncontrolled versions on the objects they operator on.

Architecture review and recommendation is part of support and subscription - if you want architecture help we would be happy to go over this https://min.io/pricing

**Comment by Ilhaame** [comment]
thank you for your investigation, 

Just to be sure if it's the same problem. In the other bucket (create a week ago) we have only 53459 Objects and 2 versions in the directory Fake and we have the latency and timeout with query grafana

mc ls -r --versions & mc admin trace -a :
[log (2).zip](https://github.com/minio/minio/files/9267902/log.2.zip)

**Comment by harshavardhana** [comment]
Yes look at the number of objects here @Ilhaame here 

```
~  wc -l version.txt  
64462 version.txt
```

You have so many delete markers on the same object this is what I meant by repeatedly recreating and deleting them 

```
~  grep DEL version.txt  | wc -l
1226
```

You will get a timeout also because your Grafana query expects the results to arrive in X amount of time however when you do a recursive listing your total time taken exceeds this. 

`mc ls` returns properly because it doesn't have such premature timeouts 

None of the individual list responses take more than 600ms all of them complete fine and there are no errors. You simply have to increase your Grafana query timeout. 

```
~ grep -v ms LogBucket2.txt 
2022-08-05T12:21:11.503 [200 OK] s3.GetBucketObjectLockConfig mni-lan-p01.csm.intra:9000/loki-production2/?object-lock=  172.23.8.13       605µs       ↑ 98 B ↓ 530 B
2022-08-05T12:21:11.546 [404 Not Found] s3.GetBucketTagging mni-lan-p01.csm.intra:9000/loki-production2/?tagging=  172.23.8.13       525µs       ↑ 98 B ↓ 669 B
```

As I said this is just an architectural issue you deployed on systems that are not fast enough for Grafana/Loki your setup will not scale. 

If you do not need versioning you shouldn't enable it.
