### ISSUE TITLE
minio server will not list existing files in bucket directories

### ISSUE THREAD

**Issue by ExpandingMan** [minio/minio#15478]
## NOTE
On doing e.g. `minio server dir`, minio recognizes any subdirectory of `dir` as a bucket, but it does not recognize any files contained in `dir` (at top level or otherwise).

## Expected Behavior
The server scans the directory.  It's possible there is an option to get it to do this that I'm not aware, but after some digging I can't seem to find anything like this.

## Current Behavior
The server seems to recognize all directories, but no file nodes.

## Steps to Reproduce (for bugs)
1. `cd dir`
2. `mkdir bucket`
3. `echo 'this is a test' > bucket/test.txt`
4. `minio server .`
5. Either through API or web GUI, server sees `bucket` as a bucket but does not see `test.txt`

## Context
I maintain [a very simple wrapper](https://gitlab.com/ExpandingMan/Minio.jl) around minio in Julia.  Several packages in the Julia ecosystem depend on this, mostly for testing S3-related functionality.  We currently have a number of unit tests in multiple packages that depend on this behavior of minio which seems to have been changed as of 1.0.

## Regression
I consider this a regression in that this used to work as expected.  I thought maybe it was just a change in default options, but I cannot even seem to find a reasonable workaround with the current behavior.

## Your Environment
```
minio version RELEASE.2022-07-17T15-43-14Z (commit-id=b6eb8dff649b0f46c12d24e89aa11254fb0132fa)
Runtime: go1.18.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```
```
Linux asus-desk-1 5.15.57-2-MANJARO x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
> On doing e.g. `minio server dir`, minio recognizes any subdirectory of `dir` as a bucket, but it does not recognize any files contained in `dir` (at top level or otherwise).

This has been changed - we used to support legacy FS mode in the past that has been deprecated and on purpose. If you have an existing deployment it will continue to work but we do not allow any fresh deployments where existing backend files are supported anymore. 

@ExpandingMan please read https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#deploy-minio-as-single-node-single-drive

**Comment by ExpandingMan** [comment]
Is there any workaround for reproducing the old behavior?  I'm sure this was done for a good reason, but it seems very strange that there doesn't seem to be any way to tell min.io to re-index the directories, it clearly breaks a lot of obvious use cases.  The linked documentation states the current behavior but does not explain it.

**Comment by harshavardhana** [comment]
> Is there any workaround for reproducing the old behavior? I'm sure this was done for a good reason, but it seems very strange that there doesn't seem to be any way to tell min.io to re-index the directories, it clearly breaks a lot of obvious use cases. The linked documentation states the current behavior but does not explain it.

Just use old releases @ExpandingMan

**Comment by ravindk89** [comment]
@ExpandingMan there are a few reasons, but the simplest ones are:

- Filesystem mode cannot provide the same feature set as our erasure coding backend. Deprecating FS mode means our ecosystem is no longer fragmented with an entire section of deployments that are missing core S3 features like versioning or object locking.
- Supporting this fragmented ecosystem adds a significant engineering and support burden. Divergent backends increase the time taken to diagnose and address user queries. A single, consistent, and predictable backend helps us better channel our resources moving forward.

We understand that are users who rely on the FS mode setup. You can always pin to that version of MinIO if the need to retain that functionality is important.

It's worth noting that even with single-node single-drive, you can use `mc cp` and `mc mv` to populate the MinIO deployment with files on any given FS drive or folder. This will allow MinIO to erasure code the files as expected. Apps can then access the objects via the S3 API as expected. Or if you really need POSIX-style access, apps can wrap the `mc` CLI through subsystem calls.
