### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by jiumiemo** [minio/minio#15487]
## NOTE
Creating a large number of buckets, minio exits when the number of buckets reaches 30,000+.

## Expected Behavior
The program continues to run.

## Current Behavior
The program exited abnormally.

## Steps to Reproduce (for bugs)

1.Create buckets continuously.
2.The number of created buckets ranges from 30,000 to 60,000.

## Your Environment

* Version used (`minio --version`):RELEASE.2021-03-17T02-33-02Z
* Server setup and configuration:minio server /storage/data/data{0...3} --address :9000
* Operating System and version (`uname -a`):

**Comment by jiumiemo** [comment]
Error log:

fatal error: concurrent map iteration and map write

goroutine 900648 [running]:
runtime.throw({0xaaaacaf2b8f7, 0x26})
	runtime/panic.go:1198 +0x54 fp=0x4002119730 sp=0x4002119700 pc=0xaaaac9c843a4
runtime.mapiternext(0x40021198a8)
	runtime/map.go:858 +0x538 fp=0x40021197b0 sp=0x4002119730 pc=0xaaaac9c5c1a8
github.com/minio/minio/cmd.(*dataUsageCache).flatten(0x4002119ef8, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0, ...}, ...})
	github.com/minio/minio/cmd/data-usage-cache.go:342 +0xac fp=0x4002119980 sp=0x40021197b0 pc=0xaaaacab54f1c
github.com/minio/minio/cmd.(*dataUsageCache).dui(0x4002119ef8, {0xaaaacb727088, 0x1}, {0x401a9e0000, 0x121ed, 0x15199})
	github.com/minio/minio/cmd/data-usage-cache.go:249 +0xa4 fp=0x4002119b70 sp=0x4002119980 pc=0xaaaacab541d4
github.com/minio/minio/cmd.(*erasureServerPools).NSScanner.func3.1()
	github.com/minio/minio/cmd/erasure-server-pool.go:516 +0x238 fp=0x4002119d50 sp=0x4002119b70 pc=0xaaaacaba8138
github.com/minio/minio/cmd.(*erasureServerPools).NSScanner.func3(0x400b4daf10, 0x40127d14a0, 0x400b7270e0, {0x401a9e0000, 0x121ed, 0x15199}, 0x400b4efe30, 0x400c0b6a20, 0x400b4efe50, 0x400112d880)
	github.com/minio/minio/cmd/erasure-server-pool.go:535 +0xf4 fp=0x4002119f80 sp=0x4002119d50 pc=0xaaaacaba7cd4
runtime.goexit()
	runtime/asm_arm64.s:1133 +0x4 fp=0x4002119f80 sp=0x4002119f80 pc=0xaaaac9cba864
created by github.com/minio/minio/cmd.(*erasureServerPools).NSScanner
	github.com/minio/minio/cmd/erasure-server-pool.go:494 +0x348

**Comment by harshavardhana** [comment]
Please upgrade @jiumiemo - this has been fixed long time ago.

**Comment by jiumiemo** [comment]
https://github.com/minio/minio/pull/13052
Is this merge fixed? ：）

**Comment by klauspost** [comment]
Yes, upgrade.
