### ISSUE TITLE
XL: listObject incorrectly lists file as directory.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1548]
For missing special multipart file.

```
$ mc ls localhost/testbucket/
[2016-05-08 17:04:41 PDT]     0B bigfile.5gb/
```

Incorrectly lists the file as directory.

**Comment by harshavardhana** [comment]
```
$ mc ls localhost/testbucket/bigfile.5gb/
mc: <ERROR> Unable to stat ‘localhost/testbucket/bigfile.5gb/’. Requested file ‘/testbucket/bigfile.5gb/’ not found
```

**Comment by krishnasrinivas** [comment]
@harshavardhana do you have the setup? i think this might have happened after the `uploads.json` change, new binary with older backend. new code could not find `uploads.json` and thought it's a directory. Not sure. Access to setup or steps to reproduce the problem will help.

**Comment by harshavardhana** [comment]
No this happens if you have deleted 0000.multipart file from backend

**Comment by krishnasrinivas** [comment]
@harshavardhana we are not supposed to modify the backend directly, if we do we can not guarantee the working of minio as expected.

**Comment by harshavardhana** [comment]
> @harshavardhana we are not supposed to modify the backend directly, if we do we can not guarantee the working of minio as expected.

No the point is if it was deleted i.e corrupted or missing, we shouldn't list these entries as directories.

**Comment by krishnasrinivas** [comment]
@harshavardhana you can close this as agreed on chat.
