### ISSUE TITLE
Replication status under site replication is inconsistent

### ISSUE THREAD

**Issue by bh4t** [minio/minio#15486]
The group status under site replication doesn't show the correct status.

Steps to reproduce: (Testing was done on existing data)
- Tried creating two sites. The first site has some pre-existing data.
- The first site has 2 groups. Group 1 (enabled) with no policies.
   and Group 2 (disabled) with no policies.
- Replicate the sites.

There are no server logs that report failure related to groups.
The console UI shows both the groups but the replication status reports a
failure which doesn't seem correct. 
I noticed that the Group that was disabled in site 1 was enabled Site 2.

Attaching the screenshots below. 

![Screenshot from 2022-08-05 14-35-17](https://user-images.githubusercontent.com/109562845/183224716-4a1ee357-7120-4e36-ba80-d38547778a9d.png)
![Screenshot from 2022-08-05 17-36-31](https://user-images.githubusercontent.com/109562845/183226525-1ccc9de9-5369-441c-aead-ada3cdeefdc9.png)
![Screenshot from 2022-08-05 17-36-40](https://user-images.githubusercontent.com/109562845/183226528-adf82ad7-54de-447b-8f15-e0dea9dca518.png)

Version:
minio version RELEASE.2022-08-02T23-59-16Z (commit-id=76f950c6632fe67b17e9f0cc00905d7093ef837d)

Browser : Chrome
OS: Linux.

**Comment by cniackz** [comment]
If I follow these steps, I don't see the same problem. In my case, I actually see an error in MinIO:

```
API: SRPeerReplicateIAMItem()
Time: 14:57:03 UTC 08/08/2022
DeploymentID: 1235cb54-aff5-4f78-8224-4376cfa93480
RequestID: 1709667CC4B48080
RemoteHost: 192.168.0.13
Host: 192.168.0.13:9002
UserAgent: MinIO (darwin; amd64) madmin-go/0.0.1
Error: Specified group does not exist (cmd.SRError)
       3: internal/logger/logger.go:259:logger.LogIf()
       2: cmd/admin-handlers-site-replication.go:209:cmd.adminAPIHandlers.SRPeerReplicateIAMItem()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

Where no group is being replicated and the errors are consistent:

<img width="1840" alt="Screen Shot 2022-08-08 at 10 58 36 AM" src="https://user-images.githubusercontent.com/6667358/183448501-6b8f3ade-63fa-4709-9b7a-d8e8595e0690.png">

So I wonder how to reproduce this issue, will try different approach and see if I can reproduce it.
Perhaps, I need to replicate directly from console as from `mc` command is working differently.

The intention I have is to get the exact steps, so we can cover this scenario with a test.
