### ISSUE TITLE
xl/Object: aws cli fails to complete multipart.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1549]
`upload: atul/data-sets/freebase-rdf-2013-06-02-00-00.shasumn to s3://testbucket/freebase-rdf-2013-06-02-00-00.shasumn
upload: atul/data-sets/freebase-rdf-2013-06-02-00-00.gz to s3://testbucket/freebase-rdf-2013-06-02-00-00.gz
upload failed: atul/data-sets/infodump-all.zip to s3://testbucket/infodump-all.zip
A client error (EntityTooSmall) occurred when calling the CompleteMultipartUpload operation: Your proposed upload is smaller than the minimum allowed object size.` 

Fixed by #1538

**Comment by piersf** [comment]
What was the fix for this?
I happen to get the same error when using the boto3 module?

Thanks

**Comment by harshavardhana** [comment]
> What was the fix for this?
> I happen to get the same error when using the boto3 module?

Could you create a new issue pretty please? - there is no information here that can help us help you.

**Comment by piersf** [comment]
Thanks!
Figured it out. It was the size of the part that I was using with upload_part() operation. The minimum size of each part should be 5Mb unless it is the last part where there is no size limit.
