### ISSUE TITLE
Download a file with OnlyOffice,but minio return 400 Bad Request

### ISSUE THREAD

**Issue by qqxadyy** [minio/minio#15493]
I got a file share link from minio console like this:

http://ip:port/bucketName/fileName.doc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=IG1WBN2TQ02QJ7Z5XMC1%2F20220808%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220808T080749Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJJRzFXQk4yVFEwMlFKN1o1WE1DMSIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoiY29uc29sZUFkbWluIn0.Fkl187a8qfjVJ4C1prygtHw0--WYdjbiI2M_-B3KbuGz3LMuMS6tN1-cd5lLAyKs7Ir2yakv8ONYzCxWp-mm_Q&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=369045b8d5347f38d9bb6704684b397115fb6a212e6de65b4d88802d9ec87c8c

And I copy this url into browser, it works and can download a file.

But when I use OnlyOffice,  it will download this file and show in it's editor ,but OnlyOffice got a 400 error, below is the whole error:
`[2022-08-08T08:09:41.265] [ERROR] nodeJS - error downloadFile:url=http://10.0.100.71:9000/pritest/333.doc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=IG1WBN2TQ02QJ7Z5XMC1%2F20220808%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220808T080749Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJJRzFXQk4yVFEwMlFKN1o1WE1DMSIsImV4cCI6MzYwMDAwMDAwMDAwMCwicG9saWN5IjoiY29uc29sZUFkbWluIn0.Fkl187a8qfjVJ4C1prygtHw0--WYdjbiI2M_-B3KbuGz3LMuMS6tN1-cd5lLAyKs7Ir2yakv8ONYzCxWp-mm_Q&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=369045b8d5347f38d9bb6704684b397115fb6a212e6de65b4d88802d9ec87c8c;attempt=3;code:undefined;connect:undefined;(id=290168968)
Error: Error response: statusCode:400; headers:{"accept-ranges":"bytes","content-length":"228","content-type":"application/xml","server":"MinIO","vary":"Origin","date":"Mon, 08 Aug 2022 08:09:41 GMT"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)`

It seems that minio return the xml info like this:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Invalid Request</Message><Resource>/pritest/333.doc</Resource><RequestId></RequestId><HostId>c1d6cdc2-a914-4d73-87c9-3348fe1131a5</HostId></Error>`

So hows can I work with this situation?
Thanks!

**Comment by harshavardhana** [comment]
@qqxadyy you haven't shared much details here.. if your browser can download this then the bug is in Only office tool .

You should talk to their authors.

**Comment by qqxadyy** [comment]
> @qqxadyy you haven't shared much details here.. if your browser can download this then the bug is in Only office tool .
> 
> You should talk to their authors.

@harshavardhana But I think the infos are enough , and the xml is from the minio service,  because it's not from nginx or apache server's default 400 page, it's from minio service's inner logic ,isn't it?
