### ISSUE TITLE
minio conn't run issues

### ISSUE THREAD

**Issue by Fredericwu** [minio/minio#15503]
Expected Behavior:
minIO should start normally using provided linstor-csi as its backend

Current Behavior:
minIO fails to start when provided backend is linstor-csi(container storage class). See error message in Title.

Test describe:
Deploy minio on k8s three-node cluster,the backend used is linstor-csi.
The linstor resource can be created through csi and the status is normal,But k8s pod can’t run, only one Minio pod is running.storage class & persistent volume are good.
See below for more details!

Deploy Minio command:
helm install --set mode=distributed,service.type=NodePort,persistence.storageClass=linstor1,persistence.size=3Gi,accessKey=miniotest,secretKey=miniopasswd,replicas=4 --generate-name minio/minio

Test Environment:

root@vplx2kn1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

root@vplx2kn1:~# kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
vplx2kn1   Ready    master   13d   v1.18.0
vplx2kn2   Ready    master   12d   v1.18.0
vplx2kn4   Ready    master   12d   v1.18.0

k8s pod status:

root@vplx2kn1:~# kubectl get pod -o wide
NAME                               READY   STATUS             RESTARTS   AGE     IP            NODE       NOMINATED NODE   READINESS GATES
minio-1659925454-0                 1/1     Running            1          6h41m   10.244.2.82   vplx2kn2   <none>           <none>
minio-1659925454-1                 0/1     CrashLoopBackOff   82         6h41m   10.244.0.58   vplx2kn1   <none>           <none>
minio-1659925454-2                 0/1     CrashLoopBackOff   82         6h41m   10.244.1.47   vplx2kn4   <none>           <none>
minio-1659925454-3                 0/1     CrashLoopBackOff   82         6h41m   10.244.1.46   vplx2kn4   <none>           <none>

k8s pod status:

root@vplx2kn1:~# kubectl get pod -o wide
NAME                               READY   STATUS             RESTARTS   AGE     IP            NODE       NOMINATED NODE   READINESS GATES
minio-1659925454-0                 1/1     Running            1          6h41m   10.244.2.82   vplx2kn2   <none>           <none>
minio-1659925454-1                 0/1     CrashLoopBackOff   82         6h41m   10.244.0.58   vplx2kn1   <none>           <none>
minio-1659925454-2                 0/1     CrashLoopBackOff   82         6h41m   10.244.1.47   vplx2kn4   <none>           <none>
minio-1659925454-3                 0/1     CrashLoopBackOff   82         6h41m   10.244.1.46   vplx2kn4   <none>           <none>

k8s pod logs:

root@vplx2kn1:~# kubectl describe pod  minio-1659925454-1
Name:         minio-1659925454-1
Namespace:    default
Events:
Type     Reason   Age                       From               Message
----     ------   ----                      ----               -------

Warning  BackOff  4m55s (x1904 over 6h39m)  kubelet, vplx2kn1  Back-off restarting failed container

root@vplx2kn1:~# kubectl logs  minio-1659925454-1

 You are running an older version of MinIO released 1 year ago
 Update: Run `mc admin update`
Name:         minio-1659925454-1
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Run the following command to add write permissions: `sudo chown -R <your-username>. <path> && sudo chmod u+rxw <path>`
root@vplx2kn1:~#

If you need more inforation,please let me know,thanks

**Comment by harshavardhana** [comment]
> You are running an older version of MinIO released 1 year ago  Update: Run `mc admin update` Name:         minio-1659925454-1 ERROR Unable to initialize backend: Unable to write to the backend       > Please ensure MinIO binary has write permissions for the backend       HINT:         Run the following command to add write permissions: `sudo chown -R <your-username>. <path> && sudo chmod u+rxw <path>` root@vplx2kn1:~#

Well we do not have write permissions on the mounts, we have no idea how you are provisioning these PVCs so please provide correct permissions that allow MinIO with "write" access on these PVCs.

**Comment by Fredericwu** [comment]
How to deploy new minio using helm command, I didn't find relevant command online.
I tried to deploy minio using the following command, but an error occurred：
helm install --set mode=distributed,service.type=NodePort,persistence.storageClass=linstor1,persistence.size=3Gi,accessKey=miniotest,secretKey=miniopasswd,replicas=4 --generate-name minio/minio:RELEASE.2022-07-29T19-40-48Z
Error: INSTALLATION FAILED: failed to download "minio/minio:RELEASE.2022-07-29T19-40-48Z"

**Comment by Fredericwu** [comment]
Thanks for your help, after I replaced the minio image, all pods are running, but I can't use minio.
so please provide correct permissions that allow MinIO with "write" access on these PVCs.
I have a question: maybe i need to set the fsgroup in the minio chart? I don't know which user minio normally runs as?

**Comment by harshavardhana** [comment]
> I have a question: maybe i need to set the fsgroup in the minio chart? I don't know which user minio normally runs as?

MinIO by default in container runs as root, you can change that with fsgroup and security context.

**Comment by Fredericwu** [comment]
Deploy Minio command: provide correct write permissions by setting securityContext.fsGroup

root@vplx2kn1:~# helm install --set mode=distributed,service.type=NodePort,persistence.storageClass=linstor1,persistence.size=3Gi,accessKey=miniotest,secretKey=miniopasswd,replicas=4,image.repository=minio/minio,image.tag=RELEASE.2021-12-29T06-49-06Z,securityContext.fsGroup=1000 --generate-name minio/minio


root@vplx2kn1:~# kubectl get pod -o wide
NAME                        READY   STATUS             RESTARTS   AGE     IP            NODE       NOMINATED NODE   READINESS GATES
minio-1660221416-0          1/1     Running            0          2m44s   10.244.2.98   vplx2kn2   <none>           <none>
minio-1660221416-1          1/1     Running            0          2m44s   10.244.1.85   vplx2kn4   <none>           <none>
minio-1660221416-2          1/1     Running            0          2m44s   10.244.0.71   vplx2kn1   <none>           <none>
minio-1660221416-3          1/1     Running            0          2m44s   10.244.1.84   vplx2kn4   <none>           <none>

root@vplx2kn1:~# kubectl get pvc
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
export-minio-1660221416-0   Bound    pvc-c01c6e1e-c875-4657-ae28-158be2abf840   3Gi        RWO            linstor1       2m50s
export-minio-1660221416-1   Bound    pvc-0876b70a-260a-4a77-b597-6732e76e0a4b   3Gi        RWO            linstor1       2m50s
export-minio-1660221416-2   Bound    pvc-29baddb5-7590-471b-8108-45f6a030962c   3Gi        RWO            linstor1       2m50s
export-minio-1660221416-3   Bound    pvc-cba00a60-dfd8-4e9c-89ef-1ea5a5fc130c   3Gi        RWO            linstor1       2m50s

root@vplx2kn1:~# kubectl get svc 
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubernetes             ClusterIP   10.96.0.1        <none>        443/TCP          16d
minio-1660221416       NodePort    10.104.209.205   <none>        9000:32000/TCP   3m47s
minio-1660221416-svc   ClusterIP   None             <none>        9000/TCP         3m47s

all minio pod are running,but i cannot connect minio via nodeip+port


log info:
root@vplx2kn1:~# kubectl logs minio-1660221416-0 | tail -n 30


API: SYSTEM()
Time: 12:45:08 UTC 08/11/2022
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/prepare-storage.go:272:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:321:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
       2: cmd/server-main.go:648:cmd.newObjectLayer()
       1: cmd/server-main.go:527:cmd.serverMain()
Waiting for a minimum of 2 disks to come online (elapsed 6m32s)

Unable to use the drive http://minio-1660221416-0.minio-1660221416-svc.default.svc.cluster.local:9000/export: file access denied
Unable to read 'format.json' from http://minio-1660221416-1.minio-1660221416-svc.default.svc.cluster.local:9000/export: Unexpected RPC call at this path '/minio/storage/export/v43/readall' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-12-29T06-49-06Z)

Unable to read 'format.json' from http://minio-1660221416-2.minio-1660221416-svc.default.svc.cluster.local:9000/export: Unexpected RPC call at this path '/minio/storage/export/v43/readall' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-12-29T06-49-06Z)

Unable to read 'format.json' from http://minio-1660221416-3.minio-1660221416-svc.default.svc.cluster.local:9000/export: Unexpected RPC call at this path '/minio/storage/export/v43/readall' - *rolling upgrade is not allowed* - please make sure all servers are running the same MinIO version (RELEASE.2021-12-29T06-49-06Z)


API: SYSTEM()
Time: 12:45:08 UTC 08/11/2022
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/prepare-storage.go:272:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:321:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
       2: cmd/server-main.go:648:cmd.newObjectLayer()
       1: cmd/server-main.go:527:cmd.serverMain()
Waiting for a minimum of 2 disks to come online (elapsed 6m33s)

root@vplx2kn1:~# 

If you need more information,please let me know!
