### ISSUE TITLE
"A timeout occurred while trying to lock a resource, please reduce your request rate" when trying to list objects

### ISSUE THREAD

**Issue by itzhoujun** [minio/minio#15508]
## NOTE
code:
```
public void test() throws Exception {
        log.info("start test object list");
        long start = System.currentTimeMillis();
        int count = this.listAll("");
        log.info("test object list complete, spend: {}s, count: {}", (System.currentTimeMillis() - start) / 1000, count);
    }

    private int listAll(String prefix) {
        int count = 0;
        Iterable<Result<Item>> parts = minioClient.listObjects(ListObjectsArgs.builder()
                .prefix(prefix)
                .bucket("test")
                .recursive(true)
                .build());
        Iterator<Result<Item>> iterator = parts.iterator();
        while (iterator.hasNext()) {
            try {
                iterator.next().get();
                count++;
            } catch (Exception e) {
                log.info("list object error: {}", e.getMessage(), e);
            }
        }
        return count;
    }
```
console log:
```
2022-08-09 21:26:03.047  INFO 68233 --- [   scheduling-1] com.service.TestService            : list object error: A timeout occurred while trying to lock a resource, please reduce your request rate

io.minio.errors.ErrorResponseException: A timeout occurred while trying to lock a resource, please reduce your request rate
	at io.minio.S3Base$1.onResponse(S3Base.java:690) ~[minio-8.4.2.jar:8.4.2]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.10.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_312]

2022-08-09 21:26:03.047  INFO 68233 --- [   scheduling-1] com.service.TestService            : test object list complete, spend: 10s, count: 2000
```

## Your Environment

* Version used (`minio --version`): RELEASE.2022-08-05T23-27-09Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): ubuntu18.04 4.15.0-180-generic

**Comment by itzhoujun** [comment]
MinIO Server Log:
```
API: ListObjectsV2(bucket=test)
Time: 02:09:23 UTC 08/10/2022
DeploymentID: 5bc4bac3-0087-447d-ab43-27ced0f0350a
RequestID: 1709D9C070110FAF
RemoteHost: 100.72.162.151
Host: minio:9000
UserAgent: MinIO (Linux; amd64) minio-java/8.4.2
Error: context deadline exceeded (context.deadlineExceededError)
       5: internal/logger/logger.go:259:logger.LogIf()
       4: cmd/erasure-single-drive.go:2907:cmd.(*erasureSingle).ListObjects()
       3: cmd/erasure-single-drive.go:2942:cmd.(*erasureSingle).ListObjectsV2()
       2: cmd/bucket-listobjects-handlers.go:238:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
@itzhoujun can you provide `mc support profile` output when you run your java code against MinIO? 

Also please explain your setup how many disks do you have?

**Comment by itzhoujun** [comment]
@harshavardhana one server and one disk.
[profile.zip](https://github.com/minio/minio/files/9295957/profile.zip)

**Comment by harshavardhana** [comment]
> API: ListObjectsV2(bucket=test)
> Time: 02:09:23 UTC 08/10/2022
> DeploymentID: 5bc4bac3-0087-447d-ab43-27ced0f0350a
> RequestID: 1709D9C070110FAF
> RemoteHost: 100.72.162.151
> Host: minio:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.2
> Error: context deadline exceeded (context.deadlineExceededError)
>        5: internal/logger/logger.go:259:logger.LogIf()
>        4: cmd/erasure-single-drive.go:2907:cmd.(*erasureSingle).ListObjects()
>        3: cmd/erasure-single-drive.go:2942:cmd.(*erasureSingle).ListObjectsV2()
>        2: cmd/bucket-listobjects-handlers.go:238:cmd.objectAPIHandlers.ListObjectsV2Handler()
>        1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()

This is helpful @itzhoujun thanks

**Comment by harshavardhana** [comment]
Found the bug @itzhoujun PR sent - please validate if you can.

**Comment by itzhoujun** [comment]
@harshavardhana Hi, merging blocked. How to run the latest version?

**Comment by harshavardhana** [comment]
> @harshavardhana Hi, merging blocked. How to run the latest version?

You can't merge :-) you should take the patch compile it and then run it.

**Comment by itzhoujun** [comment]
> > @harshavardhana Hi, merging blocked. How to run the latest version?
> 
> You can't merge :-) you should take the patch compile it and then run it.

it is not easy for me. When will the fix be released?
