### ISSUE TITLE
MinIO can hide some entries (does not happen with AWS S3)

### ISSUE THREAD

**Issue by ddzialak** [minio/minio#15504]
If we upload "dir1/file" and "dir1" objects at the same time then second key will hide first one.

## Expected Behavior

It should be possible to list both objects at the same time as it is in AWS S3.

## Current Behavior

When using aws cli, virtual directory tree is hidden by a file (see steps to reproduce).

## Steps to Reproduce (for bugs)

1. Create bucket
  `aws  s3 --endpoint http://localhost:9000/ mb s3://test`

2. Prepare testing data (notice we have file named `dir1`)
  `mkdir dir1; echo data > dir1/dir1; touch dir1/entry`

3. Upload whole `dir1` to the bucket:
  `aws  s3 --endpoint http://localhost:9000/  sync ./ s3://test`
  `upload: dir1/dir1 to s3://test/dir1/dir1`
  `upload: dir1/entry to s3://test/dir1/entry`

4. Upload **file** `dir1`:
  `{ cd dir1; aws  s3 --endpoint http://localhost:9000/ cp dir1 s3://test; }`
  `upload: ./dir1 to s3://test/dir1`

5. List objects: (ALL should be visible, but only file is shown, the same happen on MinIO Console in the browser)
  `aws  s3 --endpoint http://localhost:9000/ ls --recursive s3://test`
  `2022-08-09 12:16:15          5 dir1`
6. Remove `dir1` entry:
  `aws  s3 --endpoint http://localhost:9000/ rm s3://test/dir1`
  `delete: s3://test/dir1`

7. And then previous subtree is visible:
  `aws  s3 --endpoint http://localhost:9000/ ls --recursive s3://test`
  `2022-08-09 12:15:15          5 dir1/dir1`
  `2022-08-09 12:15:15          0 dir1/entry`

## Your Environment

* Version used (`minio --version`):
  ```
   docker exec -ti s3minio  minio --version
   minio version RELEASE.2022-08-08T18-34-09Z (commit-id=e178c55bc3615311fac283c542055907c3d48410)
   Runtime: go1.18.5 linux/amd64
   License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
   Copyright: 2015-2022 MinIO, Inc.
   ```
* Server setup and configuration: default docker image of minio/minio
* Operating System and version (`uname -a`):
   ```
   docker exec -ti s3minio  uname -a
   Linux e84cc0e93fe2 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
   ```

**Comment by vadmeste** [comment]
> If we upload "dir1/file" and "dir1" objects at the same time then second key will hide first one.

Yes, this is expected. This is not supported and it doesn't seem anyone needed this for now. Even if requested, I don't think we are going to change anything to support this.

**Comment by harshavardhana** [comment]
Yes this is mentioned on patterns of objects to avoid. Since we use filesystem hierarchy as the backend you can't have conflicting namespaces.

Read the object name restrictions section https://docs.min.io/docs/minio-server-limits-per-tenant.html
