### ISSUE TITLE
One MinIO  Pod deadLock when  rollout restart cluster frequently

### ISSUE THREAD

**Issue by yudoutingle** [minio/minio#15519]
I am running a MinIO cluster on Kubernetes, running in distributed mode with 8 nodes. Sometimes one of the node randomly starts to fail to initialize when we rollout restarted the minio cluster, but the `mc admin info xxx` seems look like well and all pods status is running， which  mistake us the cluster is healthy.
During this situation, S3 clients will receive randomly Server not initialized, please try again, depending on if the actual node handling the request is the faulty node, since in the context of a Kubernetes service, requests are load balanced on "healthy" nodes.
we dump the threads stack and find that the pod  minio-6  has deadlocked.
```
goroutine 1 [sleep]:
time.Sleep(0x1528be4d)
        runtime/time.go:193 +0x12e
github.com/minio/minio/internal/dsync.(*DRWMutex).Unlock(0xc000950770)
        github.com/minio/minio/internal/dsync/drwmutex.go:576 +0x229
github.com/minio/minio/cmd.(*distLockInstance).Unlock(0xc0035753e0, 0xc003691140)
        github.com/minio/minio/cmd/namespace-lock.go:184 +0x33
github.com/minio/minio/cmd.initServer({0x51ea730, 0xc0006c1a40}, {0x527e790, 0xc002d3aee0})
        github.com/minio/minio/cmd/server-main.go:354 +0x542
github.com/minio/minio/cmd.serverMain(0xc000703520)
        github.com/minio/minio/cmd/server-main.go:548 +0xcae
github.com/minio/cli.HandleAction({0x289e700, 0x4dbde00}, 0x6)
        github.com/minio/cli@v1.22.0/app.go:500 +0x7b
github.com/minio/cli.Command.Run({{0x2dd22d2, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x2e10ba9, 0x1b}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.22.0/command.go:225 +0x9f7
github.com/minio/cli.(*App).Run(0xc000702ea0, {0xc00004c0a0, 0xa, 0xa})
        github.com/minio/cli@v1.22.0/app.go:261 +0x7ac
github.com/minio/minio/cmd.Main({0xc00004c0a0, 0xa, 0xa})
        github.com/minio/minio/cmd/main.go:168 +0x59
main.main()
        github.com/minio/minio/main.go:33 +0x2e
```

### Expected Behavior
The pod status should not be running when it not initialized.

**Comment by yudoutingle** [comment]
The server version is `RELEASE.2022-01-27T03-53-02Z`

**Comment by harshavardhana** [comment]
Please upgrade @yudoutingle
