### ISSUE TITLE
From which version did the minio and s3-java-sdk change to the http protocol by default?

### ISSUE THREAD

**Issue by HappyToSummer** [minio/minio#15523]
I'm using minio server version RELEASE.2021-08-17T20-53-08Z. Creating AWSCredentials for getObject operation using AWS SDK for Java

when this version ，the code can works
` 
        ClientConfiguration clientConfig = new ClientConfiguration();
        clientConfig.withProtocol(Protocol.HTTPS);
        AmazonS3 amazonS3Client = new AmazonS3Client(credentials, clientConfig);
`
But recently i update the minio server to this(image: 'docker.io/bitnami/minio:2022.8.5-debian-11-r0'),i find s3 ClientConfiguration must set to HTTP can use 
` 
        clientConfig.withProtocol(Protocol.HTTP);
`
otherwise it throws an Exception，like 
![image](https://user-images.githubusercontent.com/12726154/184276145-661183e9-afba-4f39-9b04-74e1bd161d64.png)

i search the release page can't find any message，i want know which version did this change from?
Is it something to do with this configuration?  https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html

**Comment by harshavardhana** [comment]
This AWS SDK behavior nothing to do with MinIO. You should ask if AWS SDK changed their default behavior.

**Comment by HappyToSummer** [comment]
> This AWS SDK behavior nothing to do with MinIO. You should ask if AWS SDK changed their default behavior.

but i did not update AWS SDK，i just update minio
