### ISSUE TITLE
too many files in `.minio.sys/buckets/**/.usage-cache.bin `, can i delete ?

### ISSUE THREAD

**Issue by maslow** [minio/minio#15533]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I have 1.5K+ buckets, and minio generated hundreds of files  in `/mnt/oss-0/0/.minio.sys/buckets/**/.usage-cache.bin` for each bucket.  

Too many these files cost 100% inodes of disk, and minio goes down. 

Can I just delete `/.usage-cache.bin` files to resolve this problem?

And what is the functionality of  `/.usage-cache.bin` ?

**Comment by maslow** [comment]
16 volumes in 1 disk, all /.usage-cache.bin files have more than 20M.

**Comment by kannappanr** [comment]
What is the version of MinIO?

**Comment by harshavardhana** [comment]
Please state your MinIO version

**Comment by maslow** [comment]
Version: minio:2022.4.12
Linux: Linux iZ8vbgalm1f4e9ffn55w74Z 5.10.60-9.al8.x86_64 #1 SMP Mon Sep 6 21:30:37 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Version: minio:2022.4.12 Linux: Linux iZ8vbgalm1f4e9ffn55w74Z 5.10.60-9.al8.x86_64 #1 SMP Mon Sep 6 21:30:37 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

Please upgrade.

**Comment by maslow** [comment]
ok ,thanks!
