### ISSUE TITLE
how to disable X-Frame-Options in header when access from local

### ISSUE THREAD

**Issue by Xyberonz** [minio/minio#15548]
Is there a easy way(with command) to remove X-Frame-Options header , so i can iframe it in my website.
i don't know why quest minio console from localhost still set `X-Frame-Options: DENY`,  difficult to iframe console page.
And localhost should be a trusted domain source, not necessary force DENY.

**Comment by harshavardhana** [comment]
X-Frame-Options is set to SAMEORIGIN - not sure which version you are using. Please use the latest releases.

**Comment by Xyberonz** [comment]
submit this issue use version 2022-01-04T07:41:07Z .
after your response, I try to use latest docker releases verison "MinIO VERSION 2022-08-13T21:54:44Z" , by still get default "DENY".
And try to set Configuration - API - Cors Allow Origin , by still no working.

version:
![image](https://user-images.githubusercontent.com/24947060/185455341-989bcd66-5d47-4798-aa7a-a3ad771046c7.png)

get request:
![image](https://user-images.githubusercontent.com/24947060/185455449-c9c6d70c-39d9-4bc0-a714-e33b4d9b948a.png)

set CORS:
![image](https://user-images.githubusercontent.com/24947060/185455502-b13a870f-4517-41ac-ad38-3bb095942f41.png)

error:
![image](https://user-images.githubusercontent.com/24947060/185455599-6b4c5474-4388-4b00-b0e0-ba08f7808e15.png)

**Comment by tounaf** [comment]
@djerryz , You can use NGINX as proxy for minio . Try this docs [setup-nginx-proxy-with-minio](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html).
