### ISSUE TITLE
Error: Error(file is corrupted) reading erasure shards

### ISSUE THREAD

**Issue by zakiharis** [minio/minio#15547]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
no file corrupted error

## Current Behavior
Got this error when minio start. even on fresh start. Basically I just Run Standalone MinIO on Docker.

```
Formatting 1st pool, 1 set(s), 1 drives per set.
Automatically configured API requests per node based on available memory on the system: 221
Status:         1 Online, 0 Offline. 
API: http://172.17.0.4:19999  http://127.0.0.1:19999 

Console: http://172.17.0.4:27831 http://127.0.0.1:27831 

Documentation: https://docs.min.io
Finished loading IAM sub-system (took 0.0s of 0.1s to load data).

API: SYSTEM()
Time: 08:45:19 UTC 08/18/2022
DeploymentID: 0a681782-ec50-4e75-9219-b46d5c7e31fa
Error: Error(file is corrupted) reading erasure shards at (/data: .minio.sys/buckets/.usage-cache.bin/af4b740b-dac7-4ff1-9d97-d77394d9ed65/part.1), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       3: internal/logger/logger.go:278:logger.LogIf()
       2: cmd/bitrot-streaming.go:156:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()

API: SYSTEM()
Time: 08:45:19 UTC 08/18/2022
DeploymentID: 0a681782-ec50-4e75-9219-b46d5c7e31fa
Error: unexpected EOF (*errors.errorString)
       6: internal/logger/logger.go:278:logger.LogIf()
       5: internal/logger/logonce.go:73:logger.(*logOnceType).logOnceIf()
       4: internal/logger/logonce.go:113:logger.LogOnceIf()
       3: cmd/data-usage-cache.go:919:cmd.(*dataUsageCache).load()
       2: cmd/erasure-single-drive.go:3019:cmd.(*erasureSingle).nsScanner()
       1: cmd/erasure-single-drive.go:3232:cmd.(*erasureSingle).NSScanner.func2()

API: SYSTEM()
Time: 08:52:22 UTC 08/18/2022
DeploymentID: 0a681782-ec50-4e75-9219-b46d5c7e31fa
Error: Error(file is corrupted) reading erasure shards at (/data: .minio.sys/buckets/thanos/.usage-cache.bin/17c34dc5-3c19-44d1-a645-ed5cbcc51899/part.1), will attempt to reconstruct if we have quorum (*fmt.wrapError)
       3: internal/logger/logger.go:278:logger.LogIf()
       2: cmd/bitrot-streaming.go:156:cmd.(*streamingBitrotReader).ReadAt()
       1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
```

## Possible Solution
not so sure on this

## Steps to Reproduce (for bugs)

1. Nuke /data
2. Run Standalone MinIO on Docker.
3. Get thanos-compactor or thanos-store to connect to the minio
4. Got error as above

## Context
I'm trying to use minio as an object storage for thanos

## Regression
No

## Your Environment

* Version used (`minio --version`): 
minio version RELEASE.2022-06-20T23-13-45Z (commit-id=b3ebc69034bff982ca2c1a6ca43afd20838e99d5)
Runtime: go1.18.3 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
Licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

* Server setup and configuration:
I run standalone MinIO on Docker

* Operating System and version (`uname -a`):
Linux 8e3580b28174 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This looks like some drive level issue, you can simply purge the .minio.sys/ 

We have been running standalone on regular disks without any problems. Mostly looks like your docker volume is corrupted here.

Also please upgrade to latest.
