### ISSUE TITLE
Support for prefixing console with reverse proxy path

### ISSUE THREAD

**Issue by jdheyburn** [minio/minio#15550]
**Is your feature request related to a problem? Please describe.**

I'm looking to see if its possible to have my minio instance behind a reverse proxy, both the server and the console, at the same domain.

I'd like to have my server available at `https://minio.example.com`, and the console at `https://minio.example.com/ui/`.

I'm aware that minio supports path-style requests such that `https://minio.example.com/bucket/object` can be used to retrieve `object` in `bucket`, and so this would conflict with a bucket named `ui`. However seeing as buckets cannot be fewer than 3 characters, this conflict will not happen.

I'm using Caddy to reverse proxy, where my config is:

```Caddy
[minio.example.com](http://minio.example.com/) {
  reverse_proxy /ui/* localhost:CONSOLE_PORT
  reverse_proxy localhost:SERVER_PORT
}
```

This is causing some stuff to break on the console, see the screenshot below. I am unsure if it because the web server doesn't know that its assets are available at `/ui/` and not `/`.

![image](https://user-images.githubusercontent.com/34041368/185458233-d8def669-1b90-4310-9345-af9647e83250.png)

**Describe the solution you'd like**

A configurable way to define the root path that the console is being served at, behind the reverse proxy.

**Describe alternatives you've considered**

I _could_ just have another virtual host for the web interface (i.e. `minio-ui.example.com`, but I like the simplicity of having a single domain.

**Additional context**

Please let me know if there's a better way of doing the above - thank you!

**Comment by harshavardhana** [comment]
You need to just say `MINIO_BROWSER_REDIRECT_URL=http://minio.domain.com/console`  @jdheyburn 

and add `location /console { }` point to your proxy_pass to relevant port
