### ISSUE TITLE
use gdb to debug minio report Dwarf Error: wrong version in compilation unit header (is 0, should be 2, 3, or 4)

### ISSUE THREAD

**Issue by Vince-Orcadt** [minio/minio#15567]
inio]# gdb minio 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/vince/minio/minio...**_Dwarf Error: wrong version in compilation unit header (is 0, should be 2, 3, or 4)_** [in module /home/vince/minio/minio]
(_**no debugging symbols found**_)...done.
warning: Missing auto-load scripts referenced in section .debug_gdb_scripts
of file /home/vince/minio/minio
Use `info auto-load python [REGEXP]' to list them.

**Comment by harshavardhana** [comment]
This is not how you debug Go-based programs @Vince-Orcadt - not sure what you are trying to do but this is not something that will work with Go-based programs such as MinIO.
