### ISSUE TITLE
Standard storage class parity 8 should be less than or equal to 6

### ISSUE THREAD

**Issue by madcatlove** [minio/minio#15576]
We are preparing to use MinIO, but we cannot set standard storage class parity to 8.
I know the parity of the erasure set is half of disks in node, but it doesn't work.

I think the number of nodes seems to be affected ... (maybe..)
please tell me how to calculate the erasure set size  given #nodes, #disks

thanks!

Our environment
minio version : RELEASE.2022-08-11T04-37-28Z
number of minio node : 3
number of disks per node : 16
= total disk : 48

**Comment by harshavardhana** [comment]
You cannot set EC:8 because that is not your stripe size, your symmetric stripe size calculated that spreads across 3 nodes is 12 so your EC:6 is the maximum value. 

https://min.io/product/erasure-code-calculator use this calculator to see the right values.
