### ISSUE TITLE
Getting 500 Internal Server Error when trying to use s3 zip feature minio-go

### ISSUE THREAD

**Issue by binnie268** [minio/minio#15572]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 

When trying to call minio.GetObject with path: "my-bucket/archive.zip/test-10.csv", no error occurs. However, when returning the file stream and trying to call minioFileStream.stats(), and internal server error is thrown in golang when I try to get the file a second time.

Also using the mc cli, when doing mc ls --zip --recursive my-bucket/archive.zip, it works only for the first time. After that, trying the command again, I get an error.

When doing mc cat --zip my-bucket/archive.zip/test-10.csv, getting magic number error.

**Specs:**
- MacBook Pro, running Kubernetes locally with an instance of minio-server.
- test-10.csv was zipped using the command zip -r archive.zip . -x ".*" -x "__MACOSX"

## Expected Behavior

`// Add extract header to request:
	opts.Set("x-minio-extract", "true")

	// Download API.md from the archive
	rd, err := s3Client.GetObject(context.Background(), "your-bucket", "path/to/file.zip/data.csv", opts)
	if err != nil {
		log.Fatalln(err)
	}
	rd, err = io.Copy(os.Stdout, rd)
	if err != nil {
		log.Fatalln(err)
	}

       fileStats, err := rd.stats();
	if err != nil {
		log.Fatalln(err)
	}
`

should not throw error, and should return the stats even if I want to retrieve the zip multiple times
## Current Behavior

When checking the minio logs, getting this error the second time we try to get the file using x-extract-minio: 
```
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.34 mc/RELEASE.2022-08-11T00-3048Z
Error: invalid input: magic number mismatch (*errors.errorString)
  5: cmd/api-errors.go:2045:cmd.toAPIErrorCode()
  4: cmd/api-errors.go:2070:cmd.toAPIError()
  3: cmd/s3-zip-handlers.go:451:cmd.objectAPIHandlers.headObjectInArchiveFileHandler()
  2: cmd/object-handlers.go:785:cmd.objectAPIHandlers.HeadObjectHandler()
  1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

```

Also, when running  mc ls --zip --recursive my-bucket/archive.zip, the first time it works. Second time errors is thrown with:
```
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.34 mc/RELEASE.2022-08-11T00-3048Z
Error: msgp: attempted to decode type "int" with method for "array" (msg.TypeError)
  4: cmd/api-errors.go:2045:cmd.toAPIErrorCode()
  3: cmd/api-errors.go:2070:cmd.toAPIError()
  2: cmd/bucket-listobjects-handlers.go:254:cmd.objectAPIHandlers.ListObjectsV2Handler()
  1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

```

## Steps to Reproduce (for bugs)

1. Zip n number of 1 GB csv files with prefix name test-n.csv, then run zip -r archive.zip . -x ".*" -x "__MACOSX" to zip them.
2. Copy the zip to your minio bucket "my-bucket" using cli mc cp ~/data/archive.zip  myminio/my-bucket/ 
3. After copy is down. retrieve use minio-go library to get the csv in the zip using header: x-minio-extract: true in the options and path "my-bucket/archive.zip/test-1.csv (1GB file)
4.When minio object returns, call it's minio object method, stats -> minioObject.stats(). Err will be thrown. Checking in the minio logs, error is:
```
UserAgent: MinIO (darwin; amd64) minio-go/v7.0.34 mc/RELEASE.2022-08-11T00-3048Z
Error: invalid input: magic number mismatch (*errors.errorString)
  5: cmd/api-errors.go:2045:cmd.toAPIErrorCode()
  4: cmd/api-errors.go:2070:cmd.toAPIError()
  3: cmd/s3-zip-handlers.go:451:cmd.objectAPIHandlers.headObjectInArchiveFileHandler()
  2: cmd/object-handlers.go:785:cmd.objectAPIHandlers.HeadObjectHandler()
  1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

```
## Context

We are trying to prevent streaming the whole zip to the pod and instead just retrieve 1 csv that we need to validate against using minio s3 zip feature.

## Your Environment

* Version used (`minio --version`): minio version 7.0.34
* Server setup and configuration: local Kubernetes 1.21 version running with go 1.16 in Docker Desktop version 3.6.0. We are also deploying the minio chart version [RELEASE.2021-06-17T00-10-46Z](https://github.com/minio/minio/commit/e4fbc6a9ffc098d474d3b1e2f828c6c02cc6ce9b)
* Operating System and version (`uname -a`): MacBook Pro 2019 15 inch.

**Comment by harshavardhana** [comment]
Please attach the sample zip file @binnie268

**Comment by binnie268** [comment]
[samplefile1.zip](https://github.com/minio/minio/files/9409957/samplefile1.zip)

@harshavardhana  I just created a dummy zip with 2 csvs

**Comment by harshavardhana** [comment]
> * Server setup and configuration: local Kubernetes 1.21 version running with go 1.16 in Docker Desktop version 3.6.0. We are also deploying the minio chart version [RELEASE.2021-06-17T00-10-46Z](https://github.com/minio/minio/commit/e4fbc6a9ffc098d474d3b1e2f828c6c02cc6ce9b)

You need to upgrade @binnie268

**Comment by klauspost** [comment]
```
λ mc cp samplefile1.zip play/testbucket
...\samplefile1.zip:  394 B / 394 B [========================================================================] 807 B/s 0s 

λ mc ls -zip play/testbucket/samplefile1.zip
[2022-08-24 18:25:03 CEST]   909B STANDARD samplefile1.zip/sample-test-1.csv
[2022-08-24 18:25:03 CEST]   909B STANDARD samplefile1.zip/sample-test-2.csv

λ mc ls -zip play/testbucket/samplefile1.zip
[2022-08-24 18:25:03 CEST]   909B STANDARD samplefile1.zip/sample-test-1.csv
[2022-08-24 18:25:03 CEST]   909B STANDARD samplefile1.zip/sample-test-2.csv

```

There was a bug fix for single-drive mode a while ago. Upgrading should fix it.

**Comment by binnie268** [comment]
@klauspost  @harshavardhana  thank you!! I upgraded to the latest version and can confirm that it works now :)
