### ISSUE TITLE
HelmChart: Extend to support conditions in policies

### ISSUE THREAD

**Issue by mersl** [minio/minio#15582]
Today, one can ask the helm chart to create policies also. 
( Values .policies )  
Unfortunatelty, it only allows to set name, resource and action, but it doesn't allow to set also conditions.

**Proposed solution**
Extend the Helm Chart to inject conditions if defined in helm values like it exists with action.

**alternatives**
run a hand crafted job after minio got deployed to incl the json policy with conditions. It's really ugly in my mind ;-)

**Additional**
using the 'customCommands' option in the chart seems not to be an alternative since mc loves to read a json **file** with a policy and does not allow a json text as command line argument

**Comment by harshavardhana** [comment]
Feel free to send a PR @mersl

**Comment by dormanze** [comment]
We can discuss it together @harshavardhana 
Several optimization schemes I think of:
1. Modify the value of values.policies as follows:
```
policies: [{"PolicyName":"listbuckets","Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:ListAllMyBuckets"],"Resource":["arn:aws:s3:::*"]}]}]
```
2. When prefabricating policies, use the shell to read the values and splice JSON
3. Extend the ability of MC to support parsing yaml

**Comment by mersl** [comment]
> We can discuss it together @harshavardhana Several optimization schemes I think of:
> 
>     1. Modify the value of values.policies as follows:
> 
> 
> ```
> policies: [{"PolicyName":"listbuckets","Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:ListAllMyBuckets"],"Resource":["arn:aws:s3:::*"]}]}]
> ```

I would prefer the current structure as it avoids the 'json overhead'

>     3. Extend the ability of MC to support parsing yaml
I would appreciate that in general, but this won't be a requirement here

Pls check [PR 15599](https://github.com/minio/minio/pull/15599) with my preferred approach ;)
