### ISSUE TITLE
MinIO does not start with self signed cert after upgrade to version RELEASE.2022-08-25T07-17-05Z

### ISSUE THREAD

**Issue by ntimo** [minio/minio#15592]
## Expected Behavior
Minio should start with KES and not trough a cert is self signed error.

## Current Behavior
Minio won't  start and give the following error:
```
ERROR Unable to initialize a connection to KES as specified by the shell environment: Post "https://kes/v1/key/create/minio": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "localhost")
```

## Possible Solution
Rollback to version "RELEASE.2022-08-13T21-54-44Z" of minio.

## Steps to Reproduce (for bugs)
1. Setup kes and generate a cert with kes identity new --ip "127.0.0.1" --dns "kes" localhost
2. Then start a minio server that should use the kes instance with the following environments vars:
```
      - MINIO_KMS_KES_ENDPOINT=https://kes
      - MINIO_KMS_KES_KEY_FILE=/etc/minio-kes/client.key
      - MINIO_KMS_KES_CERT_FILE=/etc/minio-kes/client.crt
      - MINIO_KMS_KES_CAPATH=/etc/minio-kes/public.crt
      - MINIO_KMS_KES_KEY_NAME=minio
      - MINIO_KMS_AUTO_ENCRYPTION=on
 ```
3. See minio does not start

## Regression
I think so yes.

## Your Environment
MinIO is run in Docker using the minio/minio image.
KES is also run via docker and minio and kes are in the same docker network thanks to composes network building.
Old working MinIO Version: RELEASE.2022-08-13T21-54-44Z
Broken MinIO Version:  RELEASE.2022-08-25T07-17-05Z

**Comment by harshavardhana** [comment]
> ```
> ERROR Unable to initialize a connection to KES as specified by the shell environment: Post "https://kes/v1/key/create/minio": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "localhost")
> ```

Your cert is actually wrong @ntimo

**Comment by harshavardhana** [comment]
> * Setup kes and generate a cert with kes identity new --ip "127.0.0.1" --dns "kes" localhost

You are missing `--dns localhost`

**Comment by ntimo** [comment]
Thanks @harshavardhana that indeed solved it. I still don't really get how it could work before then but thanks any ways :)
