### ISSUE TITLE
mirroring to synchronise doesn't work as it should

### ISSUE THREAD

**Issue by schoenfbe** [minio/minio#15606]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

mc mirror with either --overwrite or -a flag doesn´t do anything, it just "finishes" in 0s, mirroring nothing.
The goal is to get a newer version onto a remote bucket, replacing the old one, but keeping both versions (versioning and object locking are enabled).
I've three different MinIO deployments now, 2 old ones, 1 new.
Old ones: original data, and its backup (both single distributions, no versioning)
New one: distributed MinIO with versioning and object locking enabled

I've now tried to mirror some data from the backup to the new setup, which worked, and to subsequently overwrite that with the current data, so there´d be the backup as version 1, and the current as version 2
## Expected Behavior

Data on new distributed MinIO should be overwritten and versioning should take place.

## Current Behavior

mc mirror simply does nothing, no matter if I use

mc mirror old_minio/bucked1 new_minio/bucket1
or
mc mirror -a old_minio/bucked1 new_minio/bucket1
or
mc mirror --overwrite old_minio/bucked1 new_minio/bucket1

## Steps to Reproduce (for bugs)

1. Create MinIO deployment in distributed mode
2. mirror data from backup (mc mirror old_minio/bucked1 new_minio/bucket1)
3. try mirroring data from original source
4. MinIO shows finished progressbar with 0-2s of "work", no mirroring takes place

## Your Environment

* Version used (`minio --version`): MinIO VERSION 2022-08-22T23:53:06Z (new)
* MinIO VERSION 2022-05-08T23:50:31Z (old original)
* MinIO VERSION 2022-05-08T23:50:31Z (old backup)
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
mc mirror is not designed to use versioning and it is never meant to be.

What you need is server side replication use that instead.

**Comment by schoenfbe** [comment]
@harshavardhana but that is not what I want, I want the old version to be version one, the newer one to be version 2, we can´t use server side replication as the old deployments can´t be versioned.

The new deployment should replace both old ones, that's why all data needs to be mirrored there.
