### ISSUE TITLE
 I use docker to start Minio，There is only one directory，Minio becomes erasure mode.

### ISSUE THREAD

**Issue by liujiaxiang** [minio/minio#15611]
I used the following command:
  docker run -d -p 9000:9000 -p 9090:9090 --name minio \
    -e "MINIO_ROOT_USER=user12345" \
    -e "MINIO_ROOT_PASSWORD=key12345" \
    -v /mnt/data:/data \
    -v /mnt/config:/root/.minio \
    minio/minio server /data --console-address ':9090'

There is only one directory，Why did Minio become the erasure mode？

**Comment by harshavardhana** [comment]
This has been changed since some time now, we deprecated gateway's and FS mode https://blog.min.io/deprecation-of-the-minio-gateway/
