### ISSUE TITLE
Windows environment variables are not read as expected

### ISSUE THREAD

**Issue by abbychau** [minio/minio#15617]
## Expected Behavior
Root User and RootPass are set to $MINIO_ROOT_USER and $MINIO_ROOT_PASSWORD when the server starts.

## Current Behavior
I can still use minioadmin to log in and cannot use abby to login.

## Steps to Reproduce (for bugs)
![image](https://user-images.githubusercontent.com/350283/187427605-903d746b-dee4-49e0-8fee-4f9efba1f1ca.png)

as shown above

## Context
I want to start the server with predefined username and password.

## Regression
Is this issue a regression? Yes 
RELEASE.2022-08-26T19-53-15Z (go1.18.5 windows/amd64)

## Your Environment
* Version used (`minio --version`): RELEASE.2022-08-26T19-53-15Z (go1.18.5 windows/amd64)
* Server setup and configuration: Win11 + PowerShell 7.2.6
* Operating System and version (`uname -a`): windows 11

**Comment by klauspost** [comment]
Could you try running from the `cmd.exe` prompt?
```
SET MINIO_ROOT_USER=abby
SET MINIO_ROOT_PASSWORD=aassddff
minio server [...]
```

**Comment by ravindk89** [comment]
Maybe also run `dir env` or `Get-ChildItem -Path Env:` to get all environment variables and validate they were set successfully. 

I believe you may also need to use a different syntax, e.g. `$Env:MINIO_ROOT_USER` and `$Env:MINIO_ROOT_PASSWORD`

**Comment by harshavardhana** [comment]
This is not very useful way to start MinIO on windows follow our documentation here https://github.com/minio/minio-service/tree/master/windows
