### ISSUE TITLE
minio pvc mounting taking time because of securitycontext labeling.

### ISSUE THREAD

**Issue by vjvel** [minio/minio#15629]
we tried to restart the minio pods and it was taking more time to mount the pvc, PVC size 1.8TB and data is around 800GB since it has securitycontext in the statefulset. its taking so much for relabelling the pvc to mount in minio pod.  Its around 4hour to mount. Is there any option to skip the labelling and reduce the time to mount.

 name: MINIO_OPERATOR_VERSION
      value: v4.3.0

Tenant is using this minio version
image: minio/minio:RELEASE.2021-10-06T23-36-31Z

**Comment by harshavardhana** [comment]
You should be using latest operator please upgrade and also upgrade your MinIO version.
