### ISSUE TITLE
Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by onurcanozavci** [minio/minio#15627]
## Current Behavior
 ``` 
 <Error>
<Code>InvalidRequest</Code>
<Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
<Resource>/screen-browser-app-ocp</Resource>
<RequestId/>
<HostId>761c982d-5161-4e66-9a24-37b653b1cbd4</HostId>
</Error>
``` 
  When there is a utf-8 char which is URL encoded on the requested path we are having the error above.

 * `http://minio.com/my-bucket/index.js?aa=KRED%u0130LER` this is an example query where we are having this issue. **"%u0130"** is url-encoded form of "İ" (a Turkish letter)
 * When we run the same query like  `http://minio.com/my-bucket/index.js?aa=KREDLER` there is no issue. 

What could be solution for this behavior? 

## Your Environment

* Version used: 2022.6.3-debian-11-r0-v1.1

**Comment by kannappanr** [comment]
@taran-p Can you PTAL?

**Comment by onurcanozavci** [comment]
In addition, 

* For our other minio server which is at version "RELEASE.2019-10-02T21-19-38Z" we are not having this issue for the same application. 
* Our buckets are publics and we are not logging in to minio to reach files. Therefore, we don't think this behavior caused by application side. 
* We deployed minio that we are having issue via helm chart and I could not see a related configuration on default values.yaml.
* We are serving our buckets via nginx, but error doesn't change when we query minio-api directly without nginx.

Is there a configuration that we should add to our server?

**Comment by klauspost** [comment]
@onurcanozavci What you are sending is [not a valid url](https://go.dev/play/p/8S6OEvF0iGx). Check your encoding method.
