### ISSUE TITLE
Minio not working with quota hard limit

### ISSUE THREAD

**Issue by vjvel** [minio/minio#15628]
we have minio operator and in one of the tenant we faced issue with file upload.  It is throwing the error   "An error occured while uploading" for the bucket which has the quota.

quota hard limit is 10TB but the available data is 1.8TB only.  With disabling the quota helps to upload the files. I am not sure how to check those logs in the backend. I enabled the trace  in minio console  but could't get any details.

 name: MINIO_OPERATOR_VERSION
      value: v4.3.0

Tenant is using this minio version
image: minio/minio:RELEASE.2021-10-06T23-36-31Z

**Comment by klauspost** [comment]
@vjvel First, upgrade minio. We do not provide community support this old versions.
