### ISSUE TITLE
Workaround to restore legacy fs mode

### ISSUE THREAD

**Issue by funkypenguin** [minio/minio#15633]
This is not so much a bug as a workaround so that others like us can find a solution to restore the "old" fs behaviour..

It's clear that FS / legacy backend is deprecated and not coming back. HOWEVER, it was super-useful in a client's use-case (*allowing users to rclone / batch-transfer large files to be consumed by [hosted Plex / Jellyfin / Emby apps](https://seedpli.city), which don't necessarily support S3 API*). There's really no alternative to Minio in this case.

Note that the [docs re pre-existing data](https://docs.min.io/minio/baremetal/installation/deploy-minio-single-node-single-drive.html#pre-existing-data) indicate that in the case of:

> Existing filesystem folders, files, and MinIO backend data

.. then:

> MinIO resumes in the legacy filesystem (“Standalone”) mode with no erasure-coding features

So our workaround was simply to create the following `format.json` in `/path-to-existing-data/.minio.sys/`:

```
{"version":"1","format":"fs","id":"avoid-going-into-snsd-mode-legacy-is-fine-with-me","fs":{"version":"2"}}
```

When Minio starts, it recognizes this as "existing" (above), and happily starts in legacy mode! 👍🏻 

Related issues:
#15352
#15455
#14331

**Comment by funkypenguin** [comment]
@lachesis this may solve the issue you raised in https://github.com/minio/minio/issues/15455

**Comment by harshavardhana** [comment]
There is no workaround @funkypenguin if you have an existing setup it continues to work. Fresh setups are not allowed - if you manually wish to create your own `format.json` you are free to do so.

**Comment by mwc-fd** [comment]
I have an “existing setup” (several hundred gigs of data that minio has been happily serving since 2018) and found out about this unfortunate decision by way of a routine software upgrade. What I’ve seen suggests that the “legacy” backend will still work, but this does not appear to be the case. What’s the newest version of Minio I can downgrade to?

**Comment by naisanzaa** [comment]
I wasn't able to find the change log why the `filesystem` mode was removed. Why was it removed?

**Comment by harshavardhana** [comment]
> I wasn't able to find the change log why the `filesystem` mode was removed. Why was it removed?

Architecture decision @naisanzaa we are moving on.
