### ISSUE TITLE
Failed to fetch last day tier stats

### ISSUE THREAD

**Issue by hrenard** [minio/minio#15639]
When I use `mc admin tier info`, my cluster throws :

```
API: TierStats()
Time: 15:58:34 UTC 08/29/2022
DeploymentID: f1062927-f415-47dd-affc-cca707c4a193
RequestID: 170FDB368BC435D0
RemoteHost: 10.244.94.63
Host: hot-pool-0-4.hot-hl.minio-hot.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
Error: failed to fetch last day tier stats: Post "https://hot-pool-0-3.hot-hl.minio-hot.svc.cluster.local:9000/minio/peer/v24/getlastdaytierstats": net/http: timeout awaiting response headers (*fmt.wrapError)
       objectLocation=cmd.auditObjectOp{Name:"buckets/.usage.json", Pool:1, Set:1, Disks:[]string{"https://hot-pool-0-0.hot-hl.minio-hot.svc.cluster.local:9000/export", "https://hot-pool-0-1.hot-hl.minio-hot.svc.cluster.local:9000/export", "https://hot-pool-0-2.hot-hl.minio-hot.svc.cluster.local:9000/export", "https://hot-pool-0-3.hot-hl.minio-hot.svc.cluster.local:9000/export", "https://hot-pool-0-4.hot-hl.minio-hot.svc.cluster.local:9000/export"}}
       4: internal/logger/logger.go:259:logger.LogIf()
       3: cmd/notification.go:1630:cmd.(*NotificationSys).GetLastDayTierStats()
       2: cmd/tier-handlers.go:294:cmd.adminAPIHandlers.TierStatsHandler()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()
```

And I get a `504 Gateway Time-out`.
The cluster is healthy and runs version `2022-08-02T23:59:16Z`.
It also impacts the console which can't load the tiers' config.
Another annoying side effect is that some nodes are marked offline temporarily because of this call.

**Comment by harshavardhana** [comment]
> Error: failed to fetch last day tier stats: Post "https://hot-pool-0-3.hot-hl.minio-hot.svc.cluster.local:9000/minio/peer/v24/getlastdaytierstats": net/http: timeout awaiting response headers (*fmt.wrapError)

Well, indeed the issue is that you have network issues on the setup, we have waited for at least 15mins to get a response here from the peer. 

The entire call to the peer server response is an in-memory call so there is no reason the server will be spending 15mins, mostly your node is not responding.

**Comment by harshavardhana** [comment]
Also @hrenard please describe your setup you seem to skim the entire issue template - we cannot imagine your setup.

**Comment by hrenard** [comment]
Sorry for the template. 
I use the k8s operator `v4.4.27`, I got 1 pool with 5 nodes and 5 disks.
I'm not convinced it's a network issue because `mc admin info` is all green, the Grafana dashboard seems fine, we're using the cluster with no issue and right after the command finally fails, the nodes that are marked offline temporarily get reconnected.

**Comment by harshavardhana** [comment]
> Sorry for the template. I use the k8s operator `v4.4.27`, I got 1 pool with 5 nodes and 5 disks. I'm not convinced it's a network issue because `mc admin info` is all green, the Grafana dashboard seems fine, we're using the cluster with no issue and right after the command finally fails, the nodes that are marked offline temporarily get reconnected.

can this be reproduced all the time? @hrenard

**Comment by hrenard** [comment]
Yes at every call (round-robin balanced). It's not always the same node throwing the error nor being marked offline.

**Comment by hrenard** [comment]
I don't know if it helps but `mc admin tier ls` works. 
It seems to be only the `/getlastdaytierstats` endpoint which fails.

**Comment by harshavardhana** [comment]
okay can you do this? `mc support profile --duration 30 alias/` - at the same time run `mc admin tier info`  - please share the profile.zip once saved locally.

**Comment by hrenard** [comment]
Yes. [Here it is](https://hot-objects.liiib.re/share/profile.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=hougo%2F20220901%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220901T160502Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=43a26b9efaf6f5ee5bc3078c6046c9a80aae6d389fb00e6b1a049495b5c269ea).

**Comment by harshavardhana** [comment]
> Yes. [Here it is](https://hot-objects.liiib.re/share/profile.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=hougo%2F20220901%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220901T160502Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=43a26b9efaf6f5ee5bc3078c6046c9a80aae6d389fb00e6b1a049495b5c269ea).

Here is the bug

```
File: minio
Type: cpu
Time: Sep 1, 2022 at 9:01am (PDT)
Duration: 35.09s, Total samples = 42.44s (120.96%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 38.13s, 89.84% of 42.44s total
Dropped 624 nodes (cum <= 0.21s)
Showing top 10 nodes out of 121
      flat  flat%   sum%        cum   cum%
    33.02s 77.80% 77.80%     33.04s 77.85%  github.com/minio/minio/cmd.(*lastDayTierStats).forwardTo
     1.10s  2.59% 80.40%      1.33s  3.13%  runtime.step
     0.89s  2.10% 82.49%      2.49s  5.87%  runtime.pcvalue
     0.68s  1.60% 84.10%      0.68s  1.60%  runtime.futex
     0.62s  1.46% 85.56%      0.67s  1.58%  syscall.Syscall
     0.57s  1.34% 86.90%      0.59s  1.39%  syscall.Syscall6
     0.49s  1.15% 88.05%      4.14s  9.75%  runtime.gentraceback
     0.26s  0.61% 88.67%      0.28s  0.66%  runtime.lock2
     0.25s  0.59% 89.26%      0.25s  0.59%  runtime.(*moduledata).textAddr
     0.25s  0.59% 89.84%      0.51s  1.20%  runtime.scanobject
```

```
(pprof) peek forwardTo
Showing nodes accounting for 42.44s, 100% of 42.44s total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                            33.04s   100% |   github.com/minio/minio/cmd.(*lastDayTierStats).addStats
    33.02s 77.80% 77.80%     33.04s 77.85%                | github.com/minio/minio/cmd.(*lastDayTierStats).forwardTo
                                             0.02s 0.061% |   runtime.asyncPreempt
----------------------------------------------------------+-------------
```
