### ISSUE TITLE
Console lets you enable bucket quotas with single-disk deployments

### ISSUE THREAD

**Issue by ryester19** [minio/minio#15630]
According to the [readme on bucket quotas](https://github.com/minio/minio/blob/8e4a45ec41720d1669bc82a0f41ca38ce78a5c71/docs/bucket/quota/README.md?plain=1#L7), quotas are not supported in single-disk deployments. However, in the console, I am still able to enable and edit the quota size within the bucket options. I am using a single-disk deployment.

![image](https://user-images.githubusercontent.com/17807258/187720876-5f1d5ceb-66d0-4715-9f15-2cff3651d8a0.png)

## Expected Behavior
Disabled is shown under the Quota option, just like Replication and Object Locking

## Current Behavior
The Quota section has a continually spinning icon underneath the label, with a pencil icon next to it that lets you change settings you shouldn't be able to 

## Your Environment

* Version used (`minio --version`): RELEASE.2022-08-26T19-53-15Z
* Server setup and configuration: Podman under Arch Linux
* Operating System and version (`uname -a`): Linux 5.19.5-arch1-1 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is enabled because it is supported.

**Comment by harshavardhana** [comment]
Replication and Object Locking must be enabled as well. This is a feature request for console.

**Comment by ryester19** [comment]
Okay, thank you. The console doesn't give any notification that you're still using the legacy Standalone mode. Emptying the storage volume now has Minio starting in SNSD mode, and the original issue has disappeared
