### ISSUE TITLE
HelmChart ServiceMonitor cluster metrics issues

### ISSUE THREAD

**Issue by briend** [minio/minio#15632]
Minio exposes two metrics, `cluster` and `node`.  As described in the docs, `cluster` only needs to be scraped once, from any server (pod).  `node` (if desired) should be scraped from all the servers (pods).

https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html

There are a couple problems with the existing helm chart.

1.  The `cluster` metrics endpoint is the only option available. There should be an option to scrape the `Node` metrics as well.
2. The `cluster` metrics endpoint is scraped from every single pod, leading to extra metrics. A 32 node minio cluster would have 32X more metrics series, making Alerts and Grafana dashboard design more cumbersome as well as wasting prometheus storage, resources, etc. 

One simple change is to switch the existing ServiceMonitor to use the `node` metrics instead of `cluster`:

https://github.com/minio/minio/blob/bcedc2b0d972de0bf9fe8b99f10560ddd3e73fcb/helm/minio/templates/servicemonitor.yaml#L38

That should be disabled by default since I don't think most people want all those per-pod (node) metrics.  The `cluster` metric is trickier to scrape just one time, it seems. Other k8s projects might use a pod label to designate which pod is the "master" and the one that should be scraped.  As a sort of hackish work-around, I added a Prometheus Probe to our fork of the helm chart, and pointed it at the Service instead of any particular pod, effectively "scraping just once per minio cluster".

```
{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ template "minio.fullname" . }}-cluster
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{ else }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  jobName: {{ template "minio.fullname" . }}
  prober:
    url: {{ template "minio.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
    path: /minio/v2/metrics/cluster
    scheme: http
  {{- if .Values.metrics.serviceMonitor.relabelConfigsCluster }}
{{ toYaml .Values.metrics.serviceMonitor.relabelConfigsCluster | indent 2 }}
  {{- end }}
  targets:
    staticConfig:
      static:
      - {{ template "minio.fullname" . }}.{{ .Release.Namespace }}
      {{- if not .Values.metrics.serviceMonitor.public }}
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      bearerTokenSecret:
        name: {{ template "minio.fullname" . }}-prometheus
        key: token
      {{- end }}
{{- end }}
```

Here's an example of it rendered:

```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  annotations:
    meta.helm.sh/release-name: minio-test1
    meta.helm.sh/release-namespace: minio
  creationTimestamp: "2022-08-19T18:53:01Z"
  generation: 6
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-4.0.4
    heritage: Helm
    release: minio-test1
  name: minio-test1-cluster
  namespace: minio
  resourceVersion: "683562286"
  uid: 538220c8-56e5-419b-a63a-18981acce6f2
spec:
  jobName: minio-test1
  prober:
    path: /minio/v2/metrics/cluster
    scheme: http
    url: minio-test1.minio:9000
  targets:
    staticConfig:
      static:
      - minio-test1.minio
```

This `Probe` seems to work just fine and greatly simplifies the metrics, and enjoys all the benefits that the Service provides: automatically using a Ready pod in the case that one is down, etc.

The main problem with this approach is that the Prometheus Operator `Probe`  is somewhat obscure, and this isn't the intended use of Probes according to a few issues: https://github.com/prometheus-operator/prometheus-operator/issues/4026 

Another benefit is that the Grafana dashboard queries can be much simpler.  There are lots of queries that have to skirt around the duplicated series using `topk`, `max`, or questionable `sum by (server)` (doesn't that inflate metrics?):

https://github.com/minio/minio/blob/bcedc2b0d972de0bf9fe8b99f10560ddd3e73fcb/docs/metrics/prometheus/grafana/minio-dashboard.json#L356

If interested I could prepare a PR to add both `node` and `cluster` metric scraping options, and simplified queries for the Grafana dashboard.  I'm not sure if using the Probe is a great choice for everyone, so I'll hold off until that is evaluated more.

**Comment by harshavardhana** [comment]
@briend you want a fully baked solution use our operator, vanilla helm charts you need to debug on your own, and get some community help. 

We do not really maintain it ourselves nor neither we test it on a regular basis.

**Comment by briend** [comment]
I made this issue to get (community) feedback on whether Prometheus Operator `Probe` was a good solution to this problem. Should I just submit a PR?

**Comment by harshavardhana** [comment]
> I made this issue to get (community) feedback on whether Prometheus Operator `Probe` was a good solution to this problem. Should I just submit a PR?

Yes, please - submit a PR @briend
