### ISSUE TITLE
JavaScript Client API : listIncompleteUploads response size is NaN

### ISSUE THREAD

**Issue by kuainaiyang** [minio/minio#15637]
node local-file-uploader-list.js
{
  key: 'Adobe Acrobat Pro DC 2022_MacApp.dmg',
  uploadId: '7d5afe21-6889-4bff-9887-7fb76e113e0d',
  initiator: { id: '', displayName: '' },
  owner: { id: '', displayName: '' },
  storageClass: '',
  initiated: 2022-09-01T05:53:50.134Z,
  size: NaN
}
End

**Comment by harshavardhana** [comment]
You need to provide the exact object name @kuainaiyang we do not implement listing hierarchically ListMultipartUploads()

**Comment by harshavardhana** [comment]
> size: NaN

Also Size is not returned in S3 API for ListMultipartUploads()

**Comment by kuainaiyang** [comment]
> > size: NaN
> 
> Also Size is not returned in S3 API for ListMultipartUploads()
@harshavardhana Because my file is relatively large, so I want to see what percentage of the file has been uploaded, is there any way to achieve this?
