### ISSUE TITLE
Expires header in PutObject ignored if days are single digit

### ISSUE THREAD

**Issue by thorstent** [minio/minio#15645]
Full disclosure: I'm an AWS employee

One can use the Expires header in a PutObject request, which will result in GetObject returning that Expires header for the object.  
However, the following value for Expires is ignored: `Fri, 1 Sep 2023 01:01:01 GMT`. With `Fri, 01 Sep 2023 01:01:01 GMT` it works though (note the two-digit day).  
By ignored I mean that the expired 

Now this behavior is correct as far as RFC 9110 Section 5.6.7 is concerned, where it states the day has two digits. However the official S3 SDK uses RFC 1123 for dates, which has the same format, just days are single digit when possible. This means the following code will not work as intended:
```
PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                .bucket("testbucket")
                .key("testfile")
                .expires(Instant.parse("2023-09-01T01:01:01Z"))
                .build();
PutObjectResponse putObjectResponse = s3Client.putObject(putObjectRequest, RequestBody.fromString("testcontent"));
```

As this code will generate the header `Expires: Fri, 1 Sep 2023 01:01:01 GMT`.

My suggestion is to make the date parser more permissive to allow single-digit days. This is in line with the recommendation at the end of Section 5.6.7, `Recipients of timestamp values are encouraged to be robust in parsing timestamps unless otherwise restricted by the field definition.`

I'm running the MinIO version RELEASE.2022-07-26T00-53-03Z  docker image.

**Comment by harshavardhana** [comment]
@thorstent can you provide a full example?  I am not able to reproduce this with AWS CLI.

```
~ aws s3api put-object --profile play --endpoint-url https://play.minio.io --bucket testbucket1 --key hosts --expires "2023-09-01T01:01:01Z" --body /etc/hosts
{
    "ETag": "\"f538a81a37ffb8374f8feefe44b73a15\""
}
```

```
~ mc stat play/testbucket1/hosts
Name      : hosts
Date      : 2022-09-04 16:54:52 PDT 
Size      : 206 B  
ETag      : f538a81a37ffb8374f8feefe44b73a15 
Type      : file 
Expires   : 2023-09-01 01:01:01 UTC 
Metadata  :
  Content-Type: binary/octet-stream 
```

**Comment by thorstent** [comment]
@harshavardhana  I just looked at what the CLI does and the CLI is correct in that it sends the date as `Fri, 01 Sep 2023 01:01:01 GMT` However, the SDK does not send the date correctly:

You can use the following test class. You will see in the wirelog: `"Expires: Fri, 1 Sep 2023 01:01:01 GMT[\r][\n]"`

Alternative would be to use postman to construct the request with this header.

```
package test;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.core.config.Configurator;
import org.testng.annotations.Test;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.S3Configuration;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.services.s3.model.PutObjectResponse;

import java.net.URI;
import java.time.Instant;

public class ExpiresTest  {

    protected S3Client s3Client;

    public ExpiresTest() {
        Region region = Region.US_WEST_2;
        S3Configuration s3Configuration = S3Configuration.builder()
                .checksumValidationEnabled(false)
                .build();
        s3Client = S3Client.builder()
                .endpointOverride(URI.create("http://localhost:9000"))
                .serviceConfiguration(s3Configuration)
                .region(region)
                .build();
    }

    @Test()
    public void putExpires() {
        Configurator.setLevel("org.apache.http.wire", Level.DEBUG);
        PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                .bucket("testbucket")
                .key("testfile")
                .expires(Instant.parse("2023-09-01T01:01:01Z"))
                .build();
        PutObjectResponse putObjectResponse = s3Client.putObject(putObjectRequest, RequestBody.fromString("testcontent"));
    }
}

```

**Comment by harshavardhana** [comment]
Added relaxed support to cater for AWS SDK limitations @thorstent

**Comment by thorstent** [comment]
@harshavardhana thanks for the fix. However, I fear the problem seems to exist for all headers that contain dates. Look at this example:

```
    @Test
    public void ifHeader() {
        Configurator.setLevel("org.apache.http.wire", Level.DEBUG);
        PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                .bucket("testbucket")
                .key("testfile")
                .build();
        PutObjectResponse putObjectResponse = s3Client.putObject(putObjectRequest, RequestBody.fromString("testcontent"));

        GetObjectRequest getObjectRequest = GetObjectRequest.builder()
                .bucket("testbucket")
                .key("testfile")
                .ifUnmodifiedSince(Instant.parse("2022-08-09T01:01:01Z"))
                .build();
        ResponseInputStream<GetObjectResponse> getObjectResponse = s3Client.getObject(getObjectRequest);

    }
```

This should give us a 412 return code, but it results in 200, because the ifUnmodifiedSince is ignored. So I think this generalizes to all date headers. However, interesting enough the following code **works** as intended:

```
    @Test
    public void expiresHeader() {
        Configurator.setLevel("org.apache.http.wire", Level.DEBUG);
        PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                .bucket("testbucket")
                .key("testfile")
                .build();
        PutObjectResponse putObjectResponse = s3Client.putObject(putObjectRequest, RequestBody.fromString("testcontent"));

        GetObjectRequest getObjectRequest = GetObjectRequest.builder()
                .bucket("testbucket")
                .key("testfile")
                .responseExpires(Instant.parse("2023-09-01T01:01:01Z"))
                .build();
        ResponseInputStream<GetObjectResponse> getObjectResponse = s3Client.getObject(getObjectRequest);

    }
```

The difference is that in this code the date is in a request parameter, the request looks as follows: `GET /testbucket/testfile?response-expires=Fri%2C%201%20Sep%202023%2001%3A01%3A01%20GMT`, this decodes as follows: `GET/testbucket/testfile?response-expires=Fri, 1 Sep 2023 01:01:01 GMT`

**Comment by harshavardhana** [comment]
I will take a look at all time parsing for http time format and perhaps do a comprehensive change.
