### ISSUE TITLE
Can't use `_` or `-` in hostnames

### ISSUE THREAD

**Issue by chibenwa** [minio/minio#15658]
If there is a `-` or `_` in host names of nodes of a MinIO cluster, client requests are not handled properly and this leads to runtime exceptions.

I needed to re-create a cluster without those characters.

## Expected Behavior

I expect MinIO to correctly handle those valid host names.

## Current Behavior

While MinIO starts the S3 API is un-responsive.

## Steps to Reproduce (for bugs)

Use `minio{1...3}-deployment.domain.org` for host schema

## Context

https://issues.apache.org/jira/browse/JAMES-3814

## Regression

No, looks unlikely to me.

## Your Environment

```
$ uname -a
Linux interview1-HP-ProBook-440-G6 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ravindk89** [comment]
What version of MinIO are you running, and how did you start the deployment? How are you managing incoming connections to the cluster (load balancer, reverse proxy, etc.) What are the actual error message and logs?

We need all the above information to properly investigate/diagnose this. It would be unusual if widespread given that this URL structure is standard in Kubernetes and as far as I know we have not had reports of issues in known K8s deployments.

**Comment by harshavardhana** [comment]
Using _ is not recommended however you can use with `-` 

> Use `minio{1...3}-deployment.domain.org` for host schema

This is very normal in all our k8s deployments, make sure your DNS resolves - that's your local issue.
