### ISSUE TITLE
Clearer error message on quorum loss

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#15666]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

This is just a byproduct of https://github.com/minio/minio/issues/15239 issue.

When an object gets into a bad state either through network failure, disk failure, user error or minio bug, where it lost quorum, the error message being returned by minio server really confuses the user.

MinIO returns "503 Service Unavailable" with "Resource requested is unreadable. please reduce your request rate". 

Both pieces of information are incorrect, since MinIO service is running well and fine for other objects and buckets and also has lots of capacity to handle the requests.

## Expected Behavior

Points the user in the right direction. 

## Current Behavior

Makes the user think that there is a server capacity issue. 

## Possible Solution

Something like "500 Internal Error" with "Object has inconsistent read quorum, use x-minio-force-delete header flag to delete it"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@mshanmu is the reason it's not something that should happen and even if it happens then it's a bug. This is why I added based on some learnings here 

- #15661
- #15649

To avoid such eventualities - there may be other cases that I shall add to cover more corner cases things you saw.

**Comment by mshanmu** [comment]
> @mshanmu is the reason it's not something that should happen and even if it happens then it's a bug. This is why I added based on some learnings here
> 
>     * [fix: trigger Heal when xl.meta needs healing during PUT #15661](https://github.com/minio/minio/pull/15661)
> 
>     * [verify RenameData() versions to be consistent #15649](https://github.com/minio/minio/pull/15649)
> 
> 
> To avoid such eventualities - there may be other cases that I shall add to cover more corner cases things you saw.

Makes sense, Thanks, @harshavardhana !!

**Comment by harshavardhana** [comment]
This is addressed in the latest releases to proactively heal objects instead of throwing errors later.
