### ISSUE TITLE
Memory usage with memory budget of 200mb

### ISSUE THREAD

**Issue by ell1e** [minio/minio#15664]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

With recent docker image update (in the last 3 months ish), the memory usage went up considerably. I now get constant out of memory crashes with a memory budget of 200mb when previously it ran fine with a 170mb limit with the same workload.

## Expected Behavior
No such significant worsening in memory use

## Current Behavior
Seems to need more than 15% more memory for same workload

## Possible Solution
Find out why and fix it, I guess? If possible

## Steps to Reproduce (for bugs)
I guess I can just describe my work load here, it's a few buckets just for my own use (uploading a changing document every week or so) in the range of 1MB to 30MB (some have images in them). Probably creating and adding around 10 such files per week with their varying sizes and keeping them in the minio storage. I also set the expiration on some which I'm guessing still doesn't work, sadly, but that shouldn't make a huge difference. The latest 10 of these files are fetched by about 1 human user per day and about 1 bot user every 5 minutes or so to check for changes. So in overall you could say a pretty boring and minuscule workload.

## Regression
Yes. Since I only occasionally update the docker image I sadly can't give you the exact version that regressed.

## Your Environment

* Version used (`minio --version`): latest in official docker image
* Server setup and configuration: a small private VPS running in KVM, hosted by Hetzner
* Operating System and version (`uname -a`): `Linux hetznerprod-alpine 5.15.62-1-virt #2-Alpine SMP Thu, 25 Aug 2022 06:18:18 +0000 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@ell1e 170 to 200 mib is hardly any memory usage. You seem to be in some esoteric use case here.

Go is a garbage collected language so it is natural that things might increase in memory at various intervals.

MinIO while works under low memory conditions it is not expected to squeezed at this level.

If you want to aggressively purge memory you should use something called as GOGC=10 from its default 100 value you will run fine.

**Comment by ell1e** [comment]
Well, the interesting part is the change, not the total. 15% is not hardly any change, IMHO. Edit: I also only got it to work reliably at 250mb now, so might be up to a 40% increase

**Comment by harshavardhana** [comment]
> Well, the interesting part is the change, not the total. 15% is not hardly any change, IMHO. Edit: I also only got it to work reliably at 250mb now, so might be up to a 40% increase

If you calculate at such low level you can always say X increase. That is a useless metric at that time - 1MiB to 2MiB is 100% growth it's not meaningful however 

You should let Go be aggressive with its GC by setting the value to 10 as an environment variable. 

There is nothing to optimize here further.

**Comment by ell1e** [comment]
I mean for files under 50MB I wouldn't consider this a low level and I'm wondering a bit what is even using that up, but fair enough.

**Comment by harshavardhana** [comment]
> I mean for files under 50MB I wouldn't consider this a low level and I'm wondering a bit what is even using that up, but fair enough.

Many things have changed we do not expect users to run in < 1GiB environments we never test it, our laptops are 8GiB on the lower end. 

200MiB capped is not something we are going to be able to work on the support it in any meaningful way without compromising on features.

**Comment by ravindk89** [comment]
I'll add to this - RAM constrains concurrent connections. We have a formula [here](https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html#requests-per-node)

Since this is a single-node setup, each connection should require ~25MB. Your current container could tolerate less than 10 concurrent connections, which in and of itself artificially constrains performance of standard S3 operations like multipart uploads.

Our [recommendation](https://docs.min.io/minio/baremetal/installation/deploy-minio-distributed.html#memory-allocation) is for ~8GiB minimum. If you are absolutely memory-constrained, you may need to pin to older versions if you want to maintain a specific predictable footprint. As noted, we cannot meaningfully optimize at <1GiB usage levels.
