### ISSUE TITLE
ilm can not support the AbortIncompleteMultipartUpload config

### ISSUE THREAD

**Issue by jianwang-beijing** [minio/minio#15681]
## Expected Behavior
```
mc ilm import local/debug
{
  "Rules": [
    {
      "ID": "r-upload-file",
      "Filter": {
        "Tag": {
          "Key": "isTempFile",
          "Value": "true"
        }
      },
      "Status": "Enabled",
      "Expiration": {
        "Days": 16
      }
    },
    {
      "ID": "r-mutipart-file",
      "Filter": {
        "Prefix": ""
      },
      "Status": "Enabled",
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 16
      }
    }
  ]
}
```
can set lifecycle rule successfully.
## Current Behavior
get the error:
> mc: <ERROR> Unable to set new lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.

## Possible Solution
no idea, maybe it is same with https://github.com/minio/minio/issues/12281

## Steps to Reproduce (for bugs)
1. create a bucket: local/debug
2. run: mc ilm import local/debug
3. copy and paste the lifecyle config(this can be get from `Expected Behavior`)
4. change the lifecyle config and rerun the ilm command

![image](https://user-images.githubusercontent.com/54609180/189821545-574d46ea-f971-4157-97b8-7b265ed62ceb.png)

## Context
can not set the mutipart file lifecycle and delete the mutipart files manually
## Regression
No
## Your Environment

* Version used (`minio --version`): 
mc version RELEASE.2022-08-28T20-08-11Z (commit-id=a64491e101feeaf68735a20c204d06993ba531e5)
Runtime: go1.18.5 darwin/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
* Server setup and configuration:
Default
* Operating System and version (`uname -a`): Darwin JimmyMacBookPro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

**Comment by vadmeste** [comment]
@jianwang-beijing MinIO doesn't support AbortIncompleteMultipartUpload in the lifecycle, multipart uploads are automatically purged after 24 hours, you can double check by inspecting 'stale_uploads_expiry' in 'mc admin config get <alias>'

**Comment by Gun9niR** [comment]
> @jianwang-beijing MinIO doesn't support AbortIncompleteMultipartUpload in the lifecycle, multipart uploads are automatically purged after 24 hours, you can double check by inspecting 'stale_uploads_expiry' in 'mc admin config get '

Is there any documentation about the retention period of incomplete multipart uploads?
