### ISSUE TITLE
missing fault tolerance

### ISSUE THREAD

**Issue by kuznetsovkk** [minio/minio#15683]
## Expected Behavior
After two years of successful use of the minio, suddenly faced with the fact that some files become unavailable with an incomplete cluster configuration: stopping 1 of 3 nodes (2 of 6 disks) makes some files in some buckets unavailable:

```
$ mcli cp --debug cluster/images/docker/registry/v2/blobs/sha256/00/001c52e26ad57e3b25b439ee0052f6692e5c0f2d5d982a00a8819ace5e521452/data  ./data
...
mcli: <DEBUG> GET /images/?location= HTTP/1.1
...
mcli: <DEBUG> HTTP/1.1 503 Service Unavailable.
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Tue, 13 Sep 2022 14:23:40 GMT
Server: MinIO
Strict-Transport-Security: max-age=16000000; includeSubDomains; preload;
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1714718ECCDC77BD
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Content-Length: 0
...

```
healing doesnt help:
```
mcli admin heal  -r --scan deep cluster/images/docker/registry/v2/blobs/sha256/00/
 ◒  images/docker/registry/v2/bl…2e7317ec601627ebaff387c5d55fea/data
    0/86 objects; 662 MiB in 3s
    ┌────────┬─────┬─────────────────────┐
    │ Green  │ 169 │  97.1% ████████████ │
    │ Yellow │   0 │   0.0%              │
    │ Red    │   0 │   0.0%              │
    │ Grey   │   0 │   0.0%              │
    └────────┴─────┴─────────────────────┘
```

Because of this issue now wecant say, we have high availability cluster.

## Your Environment
* Version used (`minio --version`): 2022-07-26T00:53:03Z
* Server setup and configuration: 1 erasure set, 3 nodes, 2 disks per node (6 disks)
minio server --address :9000 --console-address :9443 https://s3-app01.localdomain/u01 https://s3-app01.localdomain/u02 https://s3-app02.localdomain/u01 https://s3-app02.localdomain/u02 https://s3-app03.localdomain/u01 https://s3-app03.localdomain/u02
haproxy is using for load balancing in front of minio nodes
* Operating System and version (`uname -a`):
Linux S3-APP01.localdomain 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@kuznetsovkk 

> minio server --address :9000 --console-address :9443 https://s3-app01.localdomain/disk01 https://s3-app01.localdomain/u02 https://s3-app02.localdomain/u01 https://s3-app02.localdomain/u02 https://s3-app03.localdomain/u01 https://s3-app03.localdomain/u02

This setup is wrong you are going to loose quorum this way. You have to use ellipses syntax and but you cannot fix it retroactively anymore in this setup.

In this setup you have manually split the erasure spread.

Get bucket location API requires read quorum available however I suspect that you have more than one node that is disconnected during the call.

It is better to share with us some more details such as server logs etc for us to help you.

**Comment by kuznetsovkk** [comment]
Previously this configuration worked correctly: stopping 1 node in 3-nodes cluser keep the cluster online in rw-mode.
We have several other minio clusters configured in a similar way, and their fault tolerance is not lost with the loss of less than half of the nodes.
We cannot use the ellipsis configuration due to differences in server names because of some legacy. For example:
ab-node1x, cd-node-2-y, ef-node-z3
etc. We use ansible-role to configure our clusters:
https://github.com/atosatto/ansible-minio/blob/master/templates/minio.env.j2#L5
and we have such inventory:

```
minio_server_cluster_nodes:
  - 'https://s3-app01.localdomain/u01'
  - 'https://s3-app01.localdomain/u02'
  - 'https://s3-app02.localdomain/u01'
  - 'https://s3-app02.localdomain/u02'
  - 'https://s3-app03.localdomain/u01'
  - 'https://s3-app03.localdomain/u02'
```

**Comment by harshavardhana** [comment]
@kuznetsovkk with lots of nodes - is this setup used for commercial purposes?

**Comment by kuznetsovkk** [comment]
No, social purpose without commercial purpose

**Comment by harshavardhana** [comment]
@kuznetsovkk please share the server logs.

**Comment by kuznetsovkk** [comment]
> @kuznetsovkk please share the server logs.

[journalctl.log](https://github.com/minio/minio/files/9558727/journalctl.log)
[trace.log](https://github.com/minio/minio/files/9558728/trace.log)

at the client side:

```
$ mcli cp cluster/harbor-images/docker/registry/v2/blobs/sha256/00/001c52e26ad57e3b25b439ee0052f6692e5c0f2d5d982a00a8819ace5e521452/data ./data2
mcli: <ERROR> Unable to validate source `cluster/harbor-images/docker/registry/v2/blobs/sha256/00/001c52e26ad57e3b25b439ee0052f6692e5c0f2d5d982a00a8819ace5e521452/data`.
```

**Comment by harshavardhana** [comment]
@kuznetsovkk we need some more information here we need logs from all servers, we also need `mc support inspect cluster/harbor-images/docker/registry/v2/blobs/sha256/00/001c52e26ad57e3b25b439ee0052f6692e5c0f2d5d982a00a8819ace5e521452/data/**`

**Comment by kuznetsovkk** [comment]
> @kuznetsovkk we need some more information here we need logs from all servers, we also need `mc support inspect cluster/harbor-images/docker/registry/v2/blobs/sha256/00/001c52e26ad57e3b25b439ee0052f6692e5c0f2d5d982a00a8819ace5e521452/data/**`
[inspect.581a9af8.zip](https://github.com/minio/minio/files/9559756/inspect.581a9af8.zip)
About logs from other servers: I dont think you need logs from the offline node. Logs from the last online node I will give you a bit later (I do not think that they will differ from those already provided)

**Comment by harshavardhana** [comment]
Looks like you have manually manged the paths in the zip file @kuznetsovkk please re-upload without modifying them manually. Otherwise I can't really help you here.

**Comment by harshavardhana** [comment]
Okay I see why you have this problem - it looks like you have some storage class set with EC:0 the parity chosen is '0' here 

```
~  ../xl-meta xl.meta.1 | jq .Versions[].Metadata.V2Obj.EcN
0
```

```
~ ../xl-meta xl.meta.1 | jq .Versions[].Metadata.V2Obj.EcM
6
```

Did you change your storage class by any chance? @kuznetsovkk

**Comment by kuznetsovkk** [comment]
> Did you change your storage class by any chance? @kuznetsovkk

No:
```
$ mcli admin config history cluster
RestoreId: 39618cc4-d0d1-46f1-a927-76fef72587da
Date: Thu, 08 Sep 2022 11:15:17 GMT

audit_webhook enable=on endpoint=https://splunk-hec.localdomain/services/collector/raw auth_token=Splunk token

$ mcli admin config get cluster storage_class
storage_class standard= rrs=EC:2
```

**Comment by harshavardhana** [comment]
@kuznetsovkk there is nothing to fix here you need to bring that node up - you should simply set storage_class forcibly on this setup not sure why this would happen since MinIO automatically uses the default storage class.

You should re-upload the object and it will get new parity blocks. Right now it doesn't have any parity block so if you take down a node you lose quorum as expected.

I mostly suspect this because you are not using ellipses syntax so it is not picking up the number of drives available properly. The way to fix right now 

- First, bring the node back up - hope fully you have the drives intact on them 
- Also make sure to set the storage-class forcibly to a desired value such as `EC:3` for the 6 disk setup.

**Comment by harshavardhana** [comment]
You can set this via environment variable `MINIO_STORAGE_CLASS_STANDARD=EC:3`  and forcibly re-upload all the `container images`  @kuznetsovkk 

Please also share if you have set some special environment variables in your setup.  I strongly advice against using legacy syntax for distributed setup - you can create DNS aliases locally and still come up with ellipses syntax. Not sure why that was never followed.

**Comment by kuznetsovkk** [comment]
> You can set this via environment variable `MINIO_STORAGE_CLASS_STANDARD=EC:3` and forcibly re-upload all the `container images` @kuznetsovkk
> 
> Please also share if you have set some special environment variables in your setup. I strongly advice against using legacy syntax for distributed setup - you can create DNS aliases locally and still come up with ellipses syntax. Not sure why that was never followed.

About ellipses syntax: it's not obvious from the documentation. And it is not used in the ansible role. So it's not obvious to the author of the role either.
We set next env vars in /etc/default/minio:
```
MINIO_OPTS="--address :9000 --console-address :9443"
MINIO_ROOT_USER=  
MINIO_ROOT_PASSWORD=
MINIO_PROMETHEUS_AUTH_TYPE="public"
MINIO_SERVER_URL=
MINIO_IDENTITY_OPENID_CONFIG_URL=
MINIO_IDENTITY_OPENID_CLIENT_ID=    
MINIO_IDENTITY_OPENID_CLIENT_SECRET= 
MINIO_IDENTITY_OPENID_REDIRECT_URI= 
MINIO_IDENTITY_OPENID_CLAIM_NAME=
MINIO_IDENTITY_OPENID_SCOPES=
CONSOLE_PBKDF_PASSPHRASE=      
CONSOLE_PBKDF_SALT=      
CONSOLE_MINIO_SERVER=
```
Why shouldn't heal restore parity blocks?

**Comment by klauspost** [comment]
> About ellipses syntax: it's not obvious from the documentation.

Please point to the documentation for that. As far as I can see there are plenty of "MinIO requires using expansion notation `{x...y}`", but we should of course fix where it isn't.

> Why shouldn't heal restore parity blocks?

The objects was uploaded without parity, so there is nothing to heal from. Object parity is fixed from the time it is uploaded.

**Comment by kuznetsovkk** [comment]
This behavior seems to be non-obvious. Especially considering that the cluster configuration has not changed. Some of the objects were written without parity blocks for some unknown reason.
Now I will have to somehow identify these objects myself and fix them (via forcibly re-upload). Although the server seems to have enough to fix it automatically.

If I hadn't noticed it myself, I wouldn't have known it. How can you find out about such events? Isn't it wrong behavior when there are objects in the cluster without parity blocks?

**Comment by klauspost** [comment]
>  Isn't it wrong behavior when there are objects in the cluster without parity blocks?

No, it should do what it's asked to. Either from global configuration or custom storage class provided on upload.

**Comment by kuznetsovkk** [comment]
I am making a cluster of 3 nodes with 2 disks each (6 disks in total) and I expect such a configuration to be fault-tolerant if one of the nodes is unavailable. What am I doing wrong? Is the problem only in the  {...} syntax, or have I missed something else?

**Comment by kuznetsovkk** [comment]
> No, it should do what it's asked to. Either from global configuration or custom storage class provided on upload.

Application is harbor (goharbor.io), it puts docker images to a minio bucket using s3 storage backend:
https://goharbor.io/docs/2.6.0/install-config/configure-yml-file/#backend
https://github.com/docker/docker.github.io/blob/master/registry/storage-drivers/s3.md

> storageclass: (optional) The  storage class applied to each registry file. Defaults to STANDARD. Valid options are STANDARD and REDUCED_REDUNDANCY.

We dont use storageclass option, so I expect is uses STANDARD storage class.
At the minio side, the parity block for the standard class is not set, according to the documentation, this means m/2 (3 in my case).

**Comment by klauspost** [comment]
If it hasn't changed, there is something strange. We will see if we can replicate.

**Comment by harshavardhana** [comment]
> > No, it should do what it's asked to. Either from global configuration or custom storage class provided on upload.
> 
> Application is harbor (goharbor.io), it puts docker images to a minio bucket using s3 storage backend: https://goharbor.io/docs/2.6.0/install-config/configure-yml-file/#backend https://github.com/docker/docker.github.io/blob/master/registry/storage-drivers/s3.md
> 
> > storageclass: (optional) The  storage class applied to each registry file. Defaults to STANDARD. Valid options are STANDARD and REDUCED_REDUNDANCY.
> 
> We dont use storageclass option, so I expect is uses STANDARD storage class. At the minio side, the parity block for the standard class is not set, according to the documentation, this means m/2 (3 in my case).

For now the fix is set the storage class and reupload the content to get the correct storage class to have the parity.

It cannot be retroactively added on objects. It would seem like you did some upgrade and that upgrade set some dummy values that caused the setup to use a storage class with incorrect values.

That is why the workaround is set the storage class either through environment or mc admin config set  - these contents must be re-uploaded if you they need to have more tolerance.

**Comment by harshavardhana** [comment]
I mostly suspect your non ellipses setup that is the culprit here since that syntax is legacy and has not been referenced in our doc from years. It has been long deprecated.. however existing set-ups continue to work.. 

Ansible you are using is not MinIO supported you should be using this that provides the right syntax https://github.com/minio/ansible-minio

**Comment by kuznetsovkk** [comment]
> I mostly suspect your non ellipses setup that is the culprit here since that syntax is legacy and has not been referenced in our doc from years. It has been long deprecated.. however existing set-ups continue to work..

I have a lot of files and a lot of buckets in the cluster. To re-upload files without parity blocks, I first need to make a list of such files. How can I search for files without a parity block without stopping one of the cluster nodes?

**Comment by klauspost** [comment]
@kuznetsovkk There is no way to separate them without custom scripts. That goes beyond what we can offer as a community service.

If you want deeper support, I suggest you look into our subscriptions offers: https://min.io/pricing

**Comment by harshavardhana** [comment]
> I have a lot of files and a lot of buckets in the cluster. To re-upload files without parity blocks, I first need to make a list of such files. How can I search for files without a parity block without stopping one of the cluster nodes?

Best way first is to enable the storage-class setting and then proceed to look for the objects. You can do it via `mc ls --json -r | jq .key -r` and pass this result to `mc support inspect --export=json alias/bucket/object/xl.meta | jq .` and look for ecM to be '0'
