### ISSUE TITLE
Helm Chart Job Ordering

### ISSUE THREAD

**Issue by corinz** [minio/minio#15695]
## NOTE

I use the Helm Chart to deploy minio and i specify the following keys:
- buckets:
- customCommands

A command in the customCommands key references a bucket that is created via the buckets job.

Since the customCommands job is executed first, it cannot resolve a bucket that has not been created, and fails.

Is it possible to the chart user order these jobs, or to preference the "primitives" like the bucket job first?

## Expected Behavior
customCommands runs dead last

## Current Behavior
customCommands runs first

## Possible Solution
Implemented ordering?

## Context
Really kills the automation aspect of the buckets key, since I will have to manually create the buckets in customCommands

**Comment by harshavardhana** [comment]
@corinz feel free to send a fix.
