### ISSUE TITLE
Helm Chart default additionalLabels and additionalAnnotations give warnings

### ISSUE THREAD

**Issue by kasuboski** [minio/minio#15694]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

The chart should not produce helm warnings.

## Current Behavior
When using minio as a child chart and using the additionalLabels key you get the below warning.

```
coalesce.go:223: warning: destination for additionalLabels is a table. Ignoring non-table value ([])
coalesce.go:175: warning: skipped value for minio.additionalLabels: Not a table.
coalesce.go:175: warning: skipped value for minio.additionalLabels: Not a table.
```
## Possible Solution
The `additionalLabels` and `additionalAnnotations` keys in `values.yaml` should default to `{}` vs `[]`.

This seems like the same issue described in https://github.com/helm/helm/issues/8283

## Steps to Reproduce (for bugs)

1. Add minio as a child chart
2. Set values for additionalLabels
3. Run `helm lint`
4. Notice the warnings

## Context

The warnings show for consumers of the helm chart, but `helm lint --strict` doesn't seem to fail with it.

## Regression

Not that I'm aware of

## Your Environment

Noticed this on chart versions 4.0.3 and 4.0.14

**Comment by harshavardhana** [comment]
Feel free to send a fix @kasuboski
