### ISSUE TITLE
Bucket notification elasticsearch - able to connect to insecure https elasticsearch

### ISSUE THREAD

**Issue by skyser2003** [minio/minio#15704]
**Is your feature request related to a problem? Please describe.**
Feature

**Describe the solution you'd like**
To be able to connect to an insecure https elasticsearch

**Describe alternatives you've considered**

**Additional context**
Hello, I'm trying to us the bucket notification system using elasticsearch,
and I've tried many hours to find out that it couldn't connect to an insecure https elasticsearch.

Elasticearch allows user management system only when https is enabled,
but since I'm on a private network, I do not need an actual secure https certificates.

So I just want to use it as it is, an insecure elasticsearch, 
but minio's elasticsearch bucket notification system doesn't seem to allow to connect to it.

Is it that there exists such method, but I'm just missing it,
or it's just no one cared about it in the past,
or is this feature disallowed for purpose?

**Comment by vadmeste** [comment]
@skyser2003 you can put the elasicsearch public key in ~/.minio/certs/CAs/  to configure MinIO to trust the elasticsearch public certificate. After that, you will need to restart MinIO server.
