### ISSUE TITLE
Unclear error message when running minio server with two disks

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1570]
When running `minio server /mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk` throws `FATA[0000] Initializing object layer failed.             Error={Cause:Command-line arguments [/mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk] is not valid. Type:*errors.errorString}` which is not clear what's wrong with the arguments.

**Comment by harshavardhana** [comment]
> When running minio server /mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk throws FATA[0000] Initializing object layer failed. Error={Cause:Command-line arguments [/mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk] is not valid. Type:*errors.errorString} which is not clear what's wrong with the arguments.

You have to enable 'error' logging to see other messages which are printed, right now the "config.json" only prints "fatal" by default.

**Comment by harshavardhana** [comment]
> When running minio server /mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk throws FATA[0000] Initializing object layer failed. Error={Cause:Command-line arguments [/mnt/sdb1/bala/mydisk /mnt/sdc1/bala/mydisk] is not valid. Type:*errors.errorString} which is not clear what's wrong with the arguments.
> You have to enable 'error' logging to see other messages which are printed, right now the "config.json" only prints "fatal" by default.

We need to change config default to "error" instead of fatal.

**Comment by balamurugana** [comment]
I think its not a good idea.  If user sets to log level to `fatal`, he will see the same unclear error message.  Its better to fix the error message.

**Comment by balamurugana** [comment]
I am able to run with two disks now.  But there is different error now. See https://github.com/minio/minio/issues/1579
