### ISSUE TITLE
ERROR Unable to initialize backend: errno 524

### ISSUE THREAD

**Issue by SeibertronSS** [minio/minio#15719]
## NOTE
I installed the minio (v4.0.2) in kubernetes by helm, but I got the error `ERROR Unable to initialize backend: errno 524`.
Specifically, I used a pre-created pvc. It looks like there was an error when minio initialized on pvc's filesystem.
By the way, it is ok if I install the latest version in the same way.

## Current Behavior
`ERROR Unable to initialize backend: errno 524`

## Steps to Reproduce (for bugs)

1. helm install minio minio-4.0.2.tgz --namespace test

## Your Environment

* Version used: v4.0.2
* Server setup and configuration:
* Operating System and version: CentOS8, Kubernetes v1.19.9

**Comment by harshavardhana** [comment]
Where is the PVC coming from @SeibertronSS ?

**Comment by SeibertronSS** [comment]
I created it manually and it is based on NFS.

**Comment by harshavardhana** [comment]
> I created it manually and it is based on NFS.

The error is returned by your NFS implementation we can't really do anything here.  Please check with your NFS vendor we require that backend disks support O_DIRECT for reads/writes

You should bring actual disks not network mounts.

**Comment by SeibertronSS** [comment]
Thank you very much! But I still have a question, why the latest version of minio can be installed? @harshavardhana

**Comment by harshavardhana** [comment]
> Thank you very much! But I still have a question, why the latest version of minio can be installed? @harshavardhana

We have deprecated FS mode https://blog.min.io/deprecation-of-the-minio-gateway/ so you can't use it in the same manner as before.

**Comment by SeibertronSS** [comment]
I found another strange phenomenon. I add nolock to NFS, I can already start minio from the path of NFS-based pvc in docker, but I can't start it with kubernetes. @harshavardhana

**Comment by SeibertronSS** [comment]
I can't use the latest version of minio because of a problem with our code.

**Comment by harshavardhana** [comment]
> I found another strange phenomenon. I add nolock to NFS, I can already start minio from the path of NFS-based pvc in docker, but I can't start it with kubernetes. @harshavardhana

These are all NFS quirks, don't use it - provide us a regular disk with filesystem such as XFS or ext4.

**Comment by SeibertronSS** [comment]
Due to the technical selection of the project and the company's regulations, I cannot use other file systems.
