### ISSUE TITLE
Unclear error message when previously ran minio server with fresh disks

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1571]
1. Ran minio server `minio server /d0 /d1 /d2 /d3`
2. Stop and rerun minio server fresh `/d1 /d2 /d3` like `minio server /d0 /d1 /d2 /d3` causes below error

```
FATA[0000] Initializing object layer failed.             Error={Cause:I/O error.  did not meet read quorum. Type:*errors.errorString}
```

Which is not clear to the user what's wrong with given arguments

**Comment by harshavardhana** [comment]
> FATA[0000] Initializing object layer failed.             Error={Cause:I/O error.  did not meet read quorum. Type:*errors.errorString}

How many disks were not available from previous run?

**Comment by balamurugana** [comment]
> How many disks were not available from previous run?

None. Steps were followed
1. Run minio server `$ minio server /mnt/sd{b..e}1/bala/mydisk`
2. Freshen up `/mnt/sd{c..e}1/bala/mydisk`
3. Run minio server again `$ minio server /mnt/sd{b..e}1/bala/mydisk`

The expected behaviour is the server start freshly again.

**Comment by harshavardhana** [comment]
> None. Steps were followed
> 
> Run minio server $ minio server /mnt/sd{b..e}1/bala/mydisk
> Freshen up /mnt/sd{c..e}1/bala/mydisk
> Run minio server again $ minio server /mnt/sd{b..e}1/bala/mydisk
> The expected behaviour is the server start freshly again.

What does it mean by freshen up?

**Comment by balamurugana** [comment]
They are new disks now is they are replaced with new disks

**Comment by harshavardhana** [comment]
> Run minio server $ minio server /mnt/sd{b..e}1/bala/mydisk
> Freshen up /mnt/sd{c..e}1/bala/mydisk
> Run minio server again $ minio server /mnt/sd{b..e}1/bala/mydisk

Not able to reproduce this can you paste the step by step instructions here? on what you did?

**Comment by harshavardhana** [comment]
Fresh disks

```
$ minio server /tmp/test{1,2,3,4,5,6,7,8}
...
AccessKey: KEBIYDZ87HCIH5D17YCN  SecretKey: bVX1KhipSBPopEfmhc7rGz8ooxx27xdJ7Gkh1mVe  Region: us-east-1
....
```

```
$ rm -rf /tmp/test*/.minio
```

```
$ minio server /tmp/test{1,2,3,4,5,6,7,8,9,10}
...
AccessKey: KEBIYDZ87HCIH5D17YCN  SecretKey: bVX1KhipSBPopEfmhc7rGz8ooxx27xdJ7Gkh1mVe  Region: us-east-1
....
```

Is this what you mean by freshen up?
