### ISSUE TITLE
Add bucket stats in SDKs

### ISSUE THREAD

**Issue by yc-cui** [minio/minio#15728]
**Is your feature request related to a problem? Please describe.**
I observed `mc admin info play` has the ability to obtain bucket stats(bucket size, objects num...) as mentioned in [https://github.com/minio/minio/issues/6577#issuecomment-566754811](https://github.com/minio/minio/issues/6577#issuecomment-566754811)
However, didn't find any API that allow developers to  do this in these SDKs such as [https://min.io/docs/minio/linux/developers/javascript/API.html](https://min.io/docs/minio/linux/developers/javascript/API.html), only get the  bucket name and creation date using `listBuckets`.

**Describe the solution you'd like**
Add bucket stats API.

**Describe alternatives you've considered**
To get bucket stats, one can get the bucket name and then get the objects list and then compute the total size ,  finally get the bucket size and objects num. However, I don't think it's a good idea.

**Additional context**

**Comment by harshavardhana** [comment]
Bucket stats are not S3 APIs they are simply MinIO extensions available via Prometheus and other admin API means.

Adding them will break things with S3 API. We cannot extend APIs in this manner without any specific commerical requirements.

For now the intent is to keep the things the way they are.
