### ISSUE TITLE
Storage resources are insufficient for the write operation .minio.sys/config/config.json)

### ISSUE THREAD

**Issue by PelePeluche** [minio/minio#15735]
## NOTE
I get that error every 5 seconds when I try to run docker with minio

API: SYSTEM()
Time: 14:27:38 UTC 09/22/2022
DeploymentID: 40a7634b-4213-4dcb-82cf-92d7121932c6
Error: write /data/.minio.sys/tmp/3b8688a4-4753-451f-917a-8a2c9e5f5772/xl.meta: invalid argument (*fs.PathError)
       6: internal/logger/logger.go:259:logger.LogIf()
       5: cmd/storage-errors.go:174:cmd.osErrToFileErr()
       4: cmd/xl-storage.go:2387:cmd.(*xlStorage).RenameData()
       3: cmd/xl-storage-disk-id-check.go:373:cmd.(*xlStorageDiskIDCheck).RenameData()
       2: cmd/erasure-object.go:733:cmd.renameData.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to initialize config system: migrateConfigToMinioSys: Storage resources are insufficient for the write operation .minio.sys/config/config.json)

## Context
This is my docker-compose.yml

  minio:
    container_name: minio
    restart: always
    image: minio/minio:latest
    command: server /data --console-address "9001"
    networks:
      - feldico_docker_network
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_PORT: '9000'
      MINIO_CONSOLE_PORT: '9001'
      MINIO_ROOT_USER: 'myUser'
      MINIO_ROOT_PASSWORD: 'myPass'
    volumes:
      - ./cdn:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.minio.rule=Host(`local-cdn.something.com`)'
      - 'traefik.http.routers.minio.entrypoints=web'
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'

## Your Environment
* Linux pop-os 5.17.5-76051705-generic #202204271406~1653440576~22.04~6277a18 SMP PREEMPT Wed May 25 01 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
> Error: write /data/.minio.sys/tmp/3b8688a4-4753-451f-917a-8a2c9e5f5772/xl.meta: invalid argument (*fs.PathError)

invalid argument most likely means the disk having '/data/' doesn't support O_DIRECT, is '/data/' pointing to an actual disk here ?

**Comment by PelePeluche** [comment]
Thank you! That was the problem. For some reason my partner with the same configuration got that path right, even though the folder is called 'cdn' and not 'data'. I had to make that path change.

**Comment by cb-inycom** [comment]
Hi everyone.

I got the same error using a similar docker-compose.yml file.

@PelePeluche could you please explain how did you solve the error?
Could you share your final docker-compose.yml file?
