### ISSUE TITLE
minio support keycloak authorization like policy or otherwise

### ISSUE THREAD

**Issue by vklonghml** [minio/minio#15730]
currently, minio use keycloak to authenticate, but can not use keycloak role and policy to authorization, that you create policy or role in keycloak could not use in minio, you need create policy in minio independent. Want to ask, if there is a roadmap or plan, that minio support authorization like keycloak or any other third project?

**Comment by harshavardhana** [comment]
you can write your own authorization plugin if needed @vklonghml 

```
~ mc admin config set alias/ policy_plugin
KEY:
policy_plugin  enable Access Management Plugin for policy enforcement

ARGS:
url*        (url)       plugin hook endpoint (HTTP(S)) e.g. "http://localhost:8181/v1/data/httpapi/authz/allow"
auth_token  (string)    authorization token for plugin hook endpoint
comment     (sentence)  optionally add a comment to this setting
```

**Comment by vklonghml** [comment]
> you can write your own authorization plugin if needed @vklonghml
> 
> ```
> ~ mc admin config set alias/ policy_plugin
> KEY:
> policy_plugin  enable Access Management Plugin for policy enforcement
> 
> ARGS:
> url*        (url)       plugin hook endpoint (HTTP(S)) e.g. "http://localhost:8181/v1/data/httpapi/authz/allow"
> auth_token  (string)    authorization token for plugin hook endpoint
> comment     (sentence)  optionally add a comment to this setting
> ```

is this a standard method, like webhook method, or there are other plans

**Comment by harshavardhana** [comment]
> is this a standard method, like webhook method, or there are other plans

There are no other plans this is it, a generic endpoint you can write whatever you want to integrate with keycloak.
