### ISSUE TITLE
Problems with fetching added metadata to a file

### ISSUE THREAD

**Issue by kad-willej** [minio/minio#15746]
## NOTE

When I add metadata to a file, it will correctly store the metadata but incorrectly retrieve the metadata.

## Expected Behavior
Fetching data will return something like this or a correctly formed Map: 
```
userMetadata = {Metadata@10820} 
 map = {Collections$UnmodifiableMap@10823}  size = 1
  "X-Amz-Meta-Pdftype" -> "A4"
```

## Current Behavior
```
userMetadata = {Metadata@10820} 
 map = {Collections$UnmodifiableMap@10823}  size = 3
  "Value" -> "A4"
  "Items" -> null
  "Key" -> "X-Amz-Meta-Pdftype"
```
The key value pairs in the map seem to be malformed. 

## Possible Solution
\-

## Steps to Reproduce (for bugs)

1. Add user meta data to a file 
2. See it correctly being added in the minio admin portal (X-Amz-Meta-Pdftype is added)
3. Retrieve the files through the following command:
```java
 minioClient.listObjects(
                    ListObjectsArgs.builder()
                            .bucket(properties.getBucket())
                            .recursive(true)
                            .prefix(prefixUrl)
                            .includeUserMetadata(true)
                            .build()
);
```
4. Debug that the Item object has wrongly mapped key value pairs. 

## Regression

Tried versions (with Docker):
minio/minio.RELEASE.2022-07-04T21-02-54Z <- Works
minio/minio.RELEASE.2022-08-26T19-53-15Z <- Fails
minio/minio:RELEASE.2022-09-22T18-57-27Z <- Also fails

In combination with either the Java SDK 8.4.4 or the 8.2.2 package. I'm not sure which has caused the issue either the SDK or Minio. But it only appears when updating the server.

**Comment by harshavardhana** [comment]
The output of XML format has changed due to the Go XML changes the library needs to be parse them with new changes.

@balamurugana

**Comment by harshavardhana** [comment]
This has been fixed in minio-java and released.
