### ISSUE TITLE
Cannot start service minio: failed to initialize logging driver:error creating loki logger

### ISSUE THREAD

**Issue by raghadsalameh1** [minio/minio#15756]
I just started to explore [MinIO](https://github.com/minio/minio/tree/master/docs/docker) and I'm trying to run the following command:
```
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  quay.io/minio/minio server /data --console-address ":9001"
```

## Expected Behavior
The container will run without any issue

## Current Behavior
docker: Error response from daemon: failed to initialize logging driver: error creating logger: error creating loki logger: loki: option loki-url is invalid parse "https://<user_id>:<password>@logs-us-west1.grafana.net/loki/api/v1/push": net/url: invalid userinfo.

## Your Environment
* Version used: latest 
* Operating System and version: WSL Ubuntu 20.04 LTS

**Comment by harshavardhana** [comment]
> docker: Error response from daemon: failed to initialize logging driver: error creating logger: error creating loki logger: loki: option loki-url is invalid parse "https://<user_id>:@logs-us-west1.grafana.net/loki/api/v1/push": net/url: invalid userinfo.

This is your docker configuration issue not MinIO @raghadsalameh1 please fix it on your end.

**Comment by raghadsalameh1** [comment]
For those who face the same issue, I think the problem is that the default logging driver for MinIO is Loki. You can overcome this issue by stating that you want to use a local logging driver. if you are using docker-compose file you can add
```
logging:
      driver: local
```
to the service minio. This works for me.

**Comment by harshavardhana** [comment]
> For those who face the same issue, I think the problem is that the default logging driver for MinIO is Loki. You can overcome this issue by stating that you want to use a local logging driver. if you are using docker-compose file you can add
> 
> ```
> logging:
>       driver: local
> ```
> 
> to the service minio. This works for me.

No it is not - logging driver in your setup is Loki. This has nothing to do with MinIO.
