### ISSUE TITLE
mc mirror fails with umlaut (ä,ü,ö) and whitespace in filename

### ISSUE THREAD

**Issue by schoenfbe** [minio/minio#15761]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

mc mirror fails when mirroring two deployments always on the same file, and a restart will result in the same error, reeor logs however do not make much sense to me.

Logs from "mc mirror old_ls local_ls --debug" (only for the error):

mc: <ERROR> Failed to copy `https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png`. Put "http://172.17.0.2:9000/folder/subfolder/1002253-B%C3%BCgelkurier%206%3A20.png": http: ContentLength=1336204 with Body length 0
 (3) mirror-main.go:503 cmd.(*mirrorJob).monitorMirrorStatus(..) Tags: [https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png]
 (2) common-methods.go:611 cmd.uploadSourceToTargetURL(..) Tags: [https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png]
 (1) common-methods.go:341 cmd.putTargetStream(..) Tags: [local_ls, http://172.17.0.2:9000/folder/subfolder/1002253-Bügelkurier 6:20.png]
 (0) client-s3.go:1112 cmd.(*S3Client).Put(..)
 Commit:c2c2ab4299bb | Release-Tag:RELEASE.2022-08-11T00-30-48Z | Host:Inkoginkgo | OS:linux | Arch:amd64 | Lang:go1.18.5 | Mem:11 MB/38 MB | Heap:11 MB/27 MB
...Hutchison_Drei_April-Mai2020.png:  33.08 MiB / 33.08 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 1.47 MiB/s
mc: <ERROR> Unable to list comparison retrying.. Get "https://URL/folder/?continuation-token=MDFfcmF3LzEwMzAyNTMtMDVfMDRfcHJvZm90b19sZWFzaW5nLnBuZw%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=": context canceled
 (1) difference.go:192 cmd.differenceInternal(..) Tags: [https://URL/, http://172.17.0.2:9000/]
 (0) client-s3.go:2245 cmd.(*S3Client).listRecursiveInRoutine(..)
 Release-Tag:RELEASE.2022-08-11T00-30-48Z | Commit:c2c2ab4299bb | Host:Inkoginkgo | OS:linux | Arch:amd64 | Lang:go1.18.5 | Mem:11 MB/38 MB | Heap:11 MB/27 MB

Where you can see that the file with "Ü" poses a problem, whereas a file without an umlaut/whitespace poses no problem.

## Expected Behavior

mc mirror should just mirror all buckets and files between two deployments
## Current Behavior

mc mirror stops with "failed to copy" and "unable to list comparison retrying" errors
## Possible Solution

Currently trying to manually download the problematic file and put in on the ne deployment, this is however difficult cause the folder has so many items it causes the minio webinterface to timeout
## Steps to Reproduce (for bugs)

1. mc mirror old_minio new_minio

## Context

Can´t backup server.

## Your Environment

* Version used (`minio --version`): Cluster - MinIO VERSION 
2021-12-29T06:49:06Z, Local - MinIO VERSION 
2022-08-26T19:53:15Z

Thanks for help.

**Comment by harshavardhana** [comment]
> mc: Failed to copy `https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png`. Put "http://172.17.0.2:9000/folder/subfolder/1002253-B%C3%BCgelkurier%206%3A20.png": http: ContentLength=1336204 with Body length 0
> (3) mirror-main.g

is this source?  or target? @schoenfbe

**Comment by schoenfbe** [comment]
> > mc: Failed to copy `https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png`. Put "http://172.17.0.2:9000/folder/subfolder/1002253-B%C3%BCgelkurier%206%3A20.png": http: ContentLength=1336204 with Body length 0
> > (3) mirror-main.g
> 
> is this source? or target? @schoenfbe

@harshavardhana thanks for the fast reply, the "https://URL/..." part is source (I'm not allowed to post the actual URLs to our servers)
and the "http://172.17....." part is the local backup (target) I currently try to mirror to.

my best guess so far is that it's a problem with the ASCII characters with ä/ö/ü?

**Comment by schoenfbe** [comment]
@harshavardhana I've tried a few options with --exclude, excluding either "ü", the filename, or the scrambled filename, always with the same result.
I'm currently letting it mirror with --watch, since my hope was that that would continue, and it does, even if the error persists.
Now it is showing a few more files with a similar pattern:

(showing original filename => scrambled filename):

1023204-Microsoft Re 24213125381 05*2020.png => 023204-Microsoft%20Re%2024213125381%2005%2A2020.png
1023356-timetrack apple MN3QQH2KK4 05*2020.png => 1023356-timetrack%20apple%20MN3QQH2KK4%2005%2A2020.png
1023232-BKS-KK-AUSZUG 05*2020.png => 1023232-BKS-KK-AUSZUG%2005%2A2020.png

from these errors I gather that the error might not be the "ä/ö/ü" characters, but the whitespaces?

**Comment by harshavardhana** [comment]
> mc: Failed to copy `https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png`. Put "http://172.17.0.2:9000/folder/subfolder/1002253-B%C3%BCgelkurier%206%3A20.png": http: ContentLength=1336204 with Body length 0

The error is because of stream getting closed - so the object on the source cluster has some issue, it is not an actual object. You can try

```
mc cat source/bucket/object | md5sum
```

and see if it's readable.

**Comment by schoenfbe** [comment]
> > mc: Failed to copy `https://URL/folder/subfolder/1002253-Bügelkurier 6:20.png`. Put "http://172.17.0.2:9000/folder/subfolder/1002253-B%C3%BCgelkurier%206%3A20.png": http: ContentLength=1336204 with Body length 0
> 
> The error is because of stream getting closed - so the object on the source cluster has some issue, it is not an actual object. You can try
> 
> ```
> mc cat source/bucket/object | md5sum
> ```
> 
> and see if it's readable.

@harshavardhana when I just use mc cat source/bucket/object | md5sum

with the object as 1002253-Bügelkurier 6:20.png, it tells me error, unable to read from 1002253-Bügelkurier`. Object does not exist., however when I put the name in quotation marks, so:

mc cat source/bucket/"1002253-Bügelkurier 6:20.png" | md5sum,

it finds the file and outputs 516daa076b7a2818f4740ac2fb96d22b  -

so the problem seems to be the whitespaces in the filename, and the file seems readable

edit:
we also downloaded the file with mc cat old_ls/free-finance/01_raw/"1002253-Bügelkurier 6:20.png" > file.png and could open the file after pulling it from the docker container, so the files are fine.

**Comment by vadmeste** [comment]
I find it hard that this is a MinIO issue, how easy for you to try to mirror again only the subfolder that contains the problematic file ? also can you check from the uptime of 'mc admin info' if one node is restarted

**Comment by schoenfbe** [comment]
@vadmeste 

no problem at all, running with this command now:
mc mirror old_ls/free-finance/01_raw local_ls/free-finance/01_raw

output is similar, but with a different file:
mc: <ERROR> Failed to copy `https://URL/free-finance/01_raw/1023207-Vidaflex Re 2245-1881 05*2020.png`. Put "http://172.17.0.2:9000/free-finance/01_raw/1023207-Vidaflex%20Re%202245-1881%2005%2A2020.png": http: ContentLength=66513 with Body length 0
mc: <ERROR> Unable to list comparison retrying.. Canceling upon user request

mc admin info yields for:
source:
URL
   Uptime: 2 hours 
   Version: 2021-12-29T06:49:06Z


17 GiB Used, 4 Buckets, 159,497 Objects

local:
●  172.17.0.2:9000
   Uptime: 3 hours 
   Version: 2022-08-26T19:53:15Z
   Network: 1/1 OK 
   Drives: 1/1 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Disks per erasure set: 1

16 GiB Used, 4 Buckets, 143,807 Objects
1 drive online, 0 drives offline

no restarts or other issues

also, I've come to realize that it's not one problematic file, but any file concerning a whitespace, for instance mc cat like  @harshavardhana suggested also stops after the first whitespace, unless the filename is passed in quotation marks.

**Comment by vadmeste** [comment]
@schoenfbe is the issue also reproduciable with the local server ?

**Comment by vadmeste** [comment]
@schoenfbe my guess is that you have a weird setup in the first server, any logs in server side ?

**Comment by schoenfbe** [comment]
> @schoenfbe is the issue also reproduciable with the local server ?

@vadmeste no, the local server only contains files that were mirrored successfully, so none of thr problematic ones.

**Comment by schoenfbe** [comment]
> @schoenfbe my guess is that you have a weird setup in the first server, any logs in server side ?

it might be, the server is quite old and it's my current goal to replace it with a new one, but for that, saving all the data is necessary.

I just let it run with --debug again and saw a Service Unavailable error:

begin edit (added first part of debug):
---

mc: <DEBUG> GET /free-finance/01_raw/1023135-surname%name%20Re%2010%2005%2A2020.png HTTP/1.1
Host: URL
User-Agent: MinIO (linux; amd64) minio-go/v7.0.34 mc/RELEASE.2022-08-11T00-30-48Z
Authorization: AWS4-HMAC-SHA256 Credential=PdcS2d2S2NpWi9CXwtNe/20220927/us-east-1/s3/aws4_request, SignedHeaders=host;if-match;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "e882e2e3200df9f8481055ab68418b01"
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220927T112602Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 206680
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: image/png
Date: Tue, 27 Sep 2022 11:26:08 GMT
Etag: "e882e2e3200df9f8481055ab68418b01"
Expect-Ct: enforce, max-age=31536000
Last-Modified: Mon, 25 Jul 2022 17:46:51 GMT
Permissions-Policy: interest-cohort=()
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Request-Id: 1718B3FDC4C23B49
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Let's Encrypt
mc: <DEBUG>  >> Expires: 2022-11-15 01:52:24 +0000 UTC
mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: Internet Security Research Group
mc: <DEBUG>  >> Expires: 2025-09-15 16:00:00 +0000 UTC
mc: <DEBUG> Response Time:  5.842746579s

end edit.
---
mc: <DEBUG> PUT /free-finance/01_raw/1023135-surname%20name%20Re%2010%2005%2A2020.png HTTP/1.1
Host: 172.17.0.2:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.34 mc/RELEASE.2022-08-11T00-30-48Z
Content-Length: 207125
Authorization: AWS4-HMAC-SHA256 Credential=admin/20220927/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Type: image/png
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20220927T112602Z
X-Amz-Decoded-Content-Length: 206680
Accept-Encoding: gzip

**_mc: <DEBUG> HTTP/1.1 503 Service Unavailable_**
Content-Length: 432
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 27 Sep 2022 11:26:08 GMT
Retry-After: 120
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1718B3FD50A3A273
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SlowDown</Code><Message>**_Resource requested is unreadable, please reduce your request rate_**</Message><Key>01_raw/1023135-surname name Re 10 05*2020.png</Key><BucketName>free-finance</BucketName><Resource>/free-finance/01_raw/1023135-surname name Re 10 05*2020.png</Resource><RequestId>1718B3FD50A3A273</RequestId><HostId>79752275-f749-49d2-ba70-8a61b7472f54</HostId></Error>mc: <DEBUG> Response Time:  6.068313748s

The "Resource requested is unreadable, please reduce your request rate" part is also weird, since there shouldn't be that many requests, but mc mirror seems to be trying and retrying again and again.

mc: <DEBUG> HTTP/1.1 503 Service Unavailable seems to imply that there might be something missing which it would need to complete?

**Comment by vadmeste** [comment]
@schoenfbe can you do `mc admin top locks local_ls` ?

**Comment by schoenfbe** [comment]
> mc admin top locks local_ls

@vadmeste answer is "mc: Please use 'mc support top locks'"

that then yields:

mc support top locks local_ls
mc: <ERROR> Unable to get server locks list. This 'admin' API is not supported by server in 'mode-server-xl-single'.

**Comment by schoenfbe** [comment]
@harshavardhana @vadmeste 

I also just looked through the already mirrored files, and there are a few which I'd have expected to fail, like "number-companyname RG Nr. some-integer-number v. 26.06.2020 € 1.279,20.png" (where "number" is an integer for the company, "companyname" is just that, and "some-integer-number" represents another integer number for the receipt), and there are other files in similar format which were mirrored correctly.



all the remaining errors that I can see contain characters like ":" and "*", so maybe that somehoew produces errors?
I'm honestly quite at a loss right now as to qhat might cause the errors.

I've also given more resources to our server in the hopes of improving something, but that just lead to faster generation of errors.

**Comment by vadmeste** [comment]
@schoenfbe it is better if you upload logs of the new server, I think we should see something there.

**Comment by schoenfbe** [comment]
> @schoenfbe it is better if you upload logs of the new server, I think we should see something there.

@vadmeste probably stupid question, but how do I get those?

**Comment by vadmeste** [comment]
> @vadmeste probably stupid question, but how do I get those?

it is the standard output, `journalctl -u minio` if you are using systemd

**Comment by schoenfbe** [comment]
> > @vadmeste probably stupid question, but how do I get those?
> 
> it is the standard output, `journalctl -u minio` if you are using systemd

@vadmeste 

sh: journalctl: command not found

**Comment by schoenfbe** [comment]
@vadmeste if that helps, how I'm running everything right now is with a docker container containing my local minio, running on my laptop with:

docker run -p 9000:9000 -p 9001:9001 -v /path/data:/data -e "MINIO_ROOT_USER=name" -e "MINIO_ROOT_PASSWORD=password" quay.io/minio/minio:RELEASE.2022-08-26T19-53-15Z server /data --console-address ":9001"

and 

docker run --net=host -it --entrypoint=/bin/sh quay.io/minio/mc

where both minios are added via:

mc alias set local_ls http://172.17.0.2:9000 $"name" $"password"
mc alias set old_ls URL $"name" $"password"

**Comment by vadmeste** [comment]
@schoenfbe you can do `docker ps` and `docker logs <container-id>` to print minio container log

**Comment by schoenfbe** [comment]
> @schoenfbe you can do `docker ps` and `docker logs <container-id>` to print minio container log

@vadmeste 

thanks, didn't get that.

There's thousands of errors of the same kind, all seem to look like this:

API: SYSTEM()
Time: 12:04:57 UTC 09/27/2022
DeploymentID: 79752275-f749-49d2-ba70-8a61b7472f54
Error: mkdir /data/free-finance/01_raw/1023204-Microsoft Re integer-num 05*2020.png: invalid argument (*fs.PathError)
       6: internal/logger/logger.go:259:logger.LogIf()
       5: cmd/storage-errors.go:171:cmd.osErrToFileErr()
       4: cmd/xl-storage.go:2417:cmd.(*xlStorage).RenameData()
       3: cmd/xl-storage-disk-id-check.go:373:cmd.(*xlStorageDiskIDCheck).RenameData()
       2: cmd/erasure-object.go:721:cmd.renameData.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

**Comment by vadmeste** [comment]
@schoenfbe it looks like volume is not able to create a directory with a name containing a space in it, you can try that manually

**Comment by schoenfbe** [comment]
> @schoenfbe it looks like volume is not able to create a directory with a name containing a space in it, you can try that manually

@vadmeste no, that's the thing, there are already thousands of objects synced which do contain whitespaces, and creating directories and documents with whitespaces in them manually also is no problem

**Comment by klauspost** [comment]
@schoenfbe `*` cannot be part of the path. Most filesystems will refuse to create that.

**Comment by schoenfbe** [comment]
> @schoenfbe `*` cannot be part of the path. Most filesystems will refuse to create that.

@klauspost thanks, that might be it, I just tried to create them manually, and my system doesn't complain, but replaces "*" and ":" both with "_", so that's probably also what's keeping mc mirror from even creating those files.

Is there any workaround for something like that, or can MinIO handle it between servers?
cause then it would just mean that the local backup is pointless, but if I can mirror those to a different MinIO deployment it might be fine?

thanks for the info, I totally overlooked that

**Comment by schoenfbe** [comment]
@klauspost it seems that minio accepts such traffic tho, and the problem is a local one.

I've tried `mc cp` with a problematic file to another minio deployment, which worked fine, and the same commant to my local deployment didn't work.

Can I assume that `mc cp` and `mc mirror` will work the same, and that mirroring between two minio deployments on the same cluster (as they should later be) will pose no problems of thast kind?

However, all that still only works if I put the filename in quotation marks like `source/bucket/folder/"filename.png"`, if I don't have those, the file is not found by `mc cp`at least, which terminates after the first whitespace

**Comment by vadmeste** [comment]
> Can I assume that mc cp and mc mirror will work the same, and that mirroring between two minio deployments on the same cluster (as they should later be) will pose no problems of thast kind?

Yes, if the file exists in the first old deployment, most likely it will work with the second deployment

> However, all that still only works if I put the filename in quotation marks like source/bucket/folder/"filename.png", if I don't have those, the file is not found by mc cpat least, which terminates after the first whitespace

This is a total independent thing, you always need to quote arguments with special characters in your shell environment

**Comment by harshavardhana** [comment]
> @schoenfbe `*` cannot be part of the path. Most filesystems will refuse to create that.

It's a bug in your filesystem all Linux filesystems allow it. So your new set-up is using something strange but that was not originally used.

**Comment by harshavardhana** [comment]
> Error: mkdir /data/free-finance/01_raw/1023204-Microsoft Re integer-num 05*2020.png: invalid argument (*fs.PathError)

Invalid argument is your backend filesystem implementation bug - I can successfully upload a file with '*' in it on XFS disks locally. 

```
~ mc cp /etc/hosts "play/testbucket/free-finance/01_raw/1023204-Microsoft Re integer-num 05*2020.png"
/etc/hosts:                           206 B / 206 B ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.39 KiB/s 0s
```

```
~ mc ls play/testbucket/free-finance/01_raw/
[2022-09-30 00:24:44 PDT]   206B STANDARD 1023204-Microsoft Re integer-num 05*2020.png
```

Will close this since this is not our issue, you should use XFS filesystem.
