### ISSUE TITLE
Metadata marshal update was a breaking change

### ISSUE THREAD

**Issue by tudorbarbu** [minio/minio#15775]
## Previous Behavior

```json
{
   "X-Amz-Meta-Data":"X",
   "content-type":"application/octet-stream"
}
```

## Current Behavior

```json
{
   "Items":[
      {
         "Key":"content-type",
         "Value":"application/octet-stream"
      },
      {
         "Key":"X-Amz-Meta-Data",
         "Value":"X"
      }
   ]
}
```

## Possible Solution

This change should be documented.

## Context

This has caused breakages in CI since it is using the latest minio version while the application was running in an environment with minio RELEASE.2022-05-08T23-50-31Z

## Regression

#15511
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@tudorbarbu this is actually a MinIO extension not part of S3 API so we don't see the need to document it. It is meant to be used internally by our SDKs and they have been updated as such to allow parsing the new XML style.
