### ISSUE TITLE
Minio deploy Multi-Node as one cluster

### ISSUE THREAD

**Issue by modigithub** [minio/minio#15778]
Hi, at the Moment i have an chicken-and-egg problem. If i want to start server 1 i got the following error from the journal ctl:![image](https://user-images.githubusercontent.com/108171635/193418174-e4ed1561-6b2d-46b6-98e6-a319a6ec8394.png)
And if i start server 2 i got the following message:
![image](https://user-images.githubusercontent.com/108171635/193418181-4213a6a9-460d-40e2-854d-2d643d171776.png)

I followed the official documentation:
https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html
At point 5) Run the MinIO Server Process, i alway got the errory as described above.

Server 1 config:
![image](https://user-images.githubusercontent.com/108171635/193418295-3b0fa8f7-f9a7-49b0-8c0c-d92e12349ad4.png)

Server 2: config:
![image](https://user-images.githubusercontent.com/108171635/193418283-c96b3ed1-f4bd-476d-8669-8345024e590e.png)

If i run every server standalone with the volume "/var/lib/minio/DiskModiDemo" everything is working fine. But if i want to use both server as a cluster (to expand storage ...) something went wrong. The only thing i does different is the Disk configuration. On both Server i have the same Disk path but not labed and not mor than one.

Is there a gernal problem or does i have an missconfiguration?
I want to run  two different server as one object storage server.

**Comment by harshavardhana** [comment]
You cannot use a single drive and then expand into a cluster @modigithub - you have to use fresh drives for multi-node deployment. 

The error indicates what is the issue here.
