### ISSUE TITLE
RemoveObject call freeze, nothing changed

### ISSUE THREAD

**Issue by echoface** [minio/minio#15782]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

step 0: upload a video file through API (after testing, common file can be delete correctly)
step 1: select it and click delete

## Expected Behavior
object be delete in a short duration

## Current Behavior
freeze and nothing change, file remain..

## Possible Solution
another case, when i upload same file from console ui 

## Steps to Reproduce (for bugs)
![minio_delete](https://user-images.githubusercontent.com/10153981/193603451-275c44cb-4cfd-4f58-b342-0588f9d1948c.gif)

## Context
test this on two different version

## Regression
 Is this issue a regression? (No) 

## Your Environment
```
➜  minio --version
minio version RELEASE.2022-10-02T19-29-29Z (commit-id=f696a221af84fcff27266fd934a427d346547b93)
Runtime: go1.18.6 darwin/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```
* Server setup and configuration:
```
download from brew or wget from site
#!/usr/bin/env sh

export MINIO_ROOT_USER=xxxxxxxxxxxxxx
export MINIO_ROOT_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXX
#export MINIO_SERVER_URL=http://ltosapi.echoface.cn

minio server /Users/gh/minio --console-address ":9001"
```
* Operating System and version (`uname -a`):
* 
Darwin 192.168.1.3 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Comment by echoface** [comment]
write a bits code delete file. no response, no err, no timeout.  
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/10153981/193617711-9a70879c-9233-4be9-be0b-ef5e007c2ba2.png">

**Comment by harshavardhana** [comment]
@echoface we can't resolve your IP here and port.  Add `minioClient.TraceOn(os.Stderr)`

**Comment by echoface** [comment]
find out:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/10153981/193712480-bd951eef-79fd-4306-a02b-31e4bd7a19aa.png">
RemoveObject fail and freeze caused by another connection read this file without close the connection. but this behavior still not expected, return a ErrLocked/Occupied but freeze/hang

**Comment by harshavardhana** [comment]
> RemoveObject fail and freeze caused by another connection read this file without close the connection. but this behavior still not expected, return a ErrLocked/Occupied but freeze/hang

It is not freezing or hang the lock is retried upto 30mins @echoface and it gives up after 30mins. So if you are having conflicting locks your delete (write lock) is serializing on the read lock.
