### ISSUE TITLE
The output of `s3.ListObjectsV2` omits the key corresponding to the prefix

### ISSUE THREAD

**Issue by findinpath** [minio/minio#15815]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Same as in AWS S3, MinIO offers the possibility to create "directory" objects.
If we call from the `AmazonS3` client the listing functionality with a prefix corresponding to a directory object, we would expect that (same as when doing the listing against AWS S3 API) the "directory" object (corrresponding to the prefix followed by a trailing `/`) is also provided.
However when doing the same call against MinIO the "base" directory object is omited.

## Expected Behavior

Given that we have the key:

- `directory/` corresponding to an object with `application/x-directory` media type

in the  AWS S3 object storage,

when we do

```
        ListObjectsV2Request request = new ListObjectsV2Request()
                .withBucketName(getBucketName(uri))
                .withPrefix("directory/")
                .withDelimiter(null);
       ListObjectsV2Result listings = s3.listObjectsV2(request)
```

the listing will contain an object summary with the key 'directory/`.

## Current Behavior

When doing the above mentioned call with an `AmazonS3` client, the listing will be empty.

I am testing against `minio/minio:RELEASE.2021-07-15T22-27-34Z` container.

## Steps to Reproduce (for bugs)

1. Create a directory with the key "directory"

```
    protected static void createDirectory(AmazonS3 client, String bucketName, String key)
    {
        // create meta-data for your folder and set content-length to 0
        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentLength(0);
        metadata.setContentType(DIRECTORY_MEDIA_TYPE.toString());
        // create empty content
        InputStream emptyContent = new ByteArrayInputStream(new byte[0]);
        // create a PutObjectRequest passing the folder name suffixed by /
        PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, key + PATH_SEPARATOR, emptyContent, metadata);
        // send request to S3 to create folder
        client.putObject(putObjectRequest);
    }
```

2. Do the listing

```
        ListObjectsV2Request request = new ListObjectsV2Request()
                .withBucketName(getBucketName(uri))
                .withPrefix("directory/")
                .withDelimiter(null);
       ListObjectsV2Result listings = s3.listObjectsV2(request)
```

The listing will be empty when checking against MinIO.

## Your Environment

* Version used (`minio --version`): `minio/minio:RELEASE.2021-07-15T22-27-34Z`
* Server setup and configuration: Docker
* Operating System and version (`uname -a`): N/A

**Comment by vadmeste** [comment]
@findinpath could you double check with the latest MinIO version ?

**Comment by findinpath** [comment]
Tested with `RELEASE.2022-08-22T23-53-06Z.hotfix.5fa3967bb` and the functionality is fixed and works exactly as in S3.

**Comment by harshavardhana** [comment]
> Tested with `RELEASE.2022-08-22T23-53-06Z.hotfix.5fa3967bb` and the functionality is fixed and works exactly as in S3.

you shouldn't be using this you need to use latest release RELEASE.2022-10-05T14-58-27Z
