### ISSUE TITLE
Invalid urls for presigned PUT requests

### ISSUE THREAD

**Issue by ikitommi** [minio/minio#15811]
When using minio inside a gitlab ci-pipeline, the putobject url signing returns invalid urls.

## Expected Behavior

Get a signing url with host/bucket/key, e.g. `http://s3:9000/my-bucket/123`

## Current Behavior

Get a signing url with host/bucket/key, e.g. `http://my-bucket.s3:9000/123`

## Context

Can't run `minio/minio` with gitlab ci-pipeline with presigned puts.

## Your Environment

```
Running with gitlab-runner 15.4.0 (43b2dc3d)
  on ubuntu-docker-runner hYUf1qgo
  feature flags: FF_NETWORK_PER_BUILD:true
```

```
Pulling docker image minio/minio:latest ...
```

**Comment by harshavardhana** [comment]
Well this is client side problem , you need to enable path style based presigned URL nothing to do with MinIO server.

Enable path style in your gitlab-ci or whichever pipeline that generates this designed URL

**Comment by ikitommi** [comment]
Thanks for the quick reply. 

Is there a way to force minio to always use path-style presigned urls? Minio defaults to path-based when accesses with ip-address (e.g. from host into docker network), and to virtual-host-style when accesses with name (withing the docker network)? The latter fails with presigned urls.

**Comment by harshavardhana** [comment]
> Is there a way to force minio to always use path-style presigned urls? Minio defaults to path-based when accesses with ip-address (e.g. from host into docker network), and to virtual-host-style when accesses with name (withing the docker network)? The latter fails with presigned urls.

This is an issue of the client SDK that you are using @ikitommi not MinIO.
