### ISSUE TITLE
My minio started as a single disk, but the storage was erasure block storage

### ISSUE THREAD

**Issue by RunInto** [minio/minio#15824]
I deleted the ~/.minio/ and the.minio.sys/ under the bucket, and restarted it. It's still erasureproof block storage.

I want to single disk, not block run, how to do?

**Comment by vadmeste** [comment]
@RunInto it is still single disk without data redunduncy. 

The new format supports much more S3 features. The old format is deprecated for new deployments but still supports old deployments.

**Comment by RunInto** [comment]
@vadmeste How does the new format of SNSD mode ensure high availability of data by utilizing the underlying storage volume? please.

**Comment by klauspost** [comment]
@RunInto It does not. It merely stores metadata and other file information in a similar format. But if your drive dies you lose all your data.

It will however allow you to use all features like versioning, locking, etc.

You should not use SNSD in production unless you, yourself can guarantee the storage will never fail.
