### ISSUE TITLE
MINIO Client fails to handle URL encoded paths correctly on Google Cloud Storage

### ISSUE THREAD

**Issue by cboettig** [minio/minio#15841]
This issue matches previously reported issue https://github.com/minio/minio/issues/7277.  As documented there, this issue does not occur with the most recent version of MINIO server, or with other clients that use the S3v4 API.  But MINIO claims to support Google Cloud Storage as well, and to work across cloud providers, and does so using the S3v2 API, where paths requiring URL encoding create problems. (Apologies if this should be filed separately as an issue for the minio client)

## Expected Behavior

I would like to be able to use minio client to access data on Google Cloud storage that has characters that must be escaped.  I can list data in these directories, e.g.

```
cboettig@thelio:~$ mc ls neon/neon-is-transition-output/provisional/dpid=DP1.20288.001/ms=2021-07/site=BARC/
[2021-12-29 00:19:35 PST] 572KiB /neon-is-transition-output/provisional/dpid%3DDP1.20288.001/ms%3D2021-07/site%3DBARC/BARC_L0_to_L1_Water_Quality_DP1.20288.001__2021-07-01.avro
[2021-12-29 00:19:34 PST] 572KiB /neon-is-transition-output/provisional/dpid%3DDP1.20288.001/ms%3D2021-07/site%3DBARC/BARC_L0_to_L1_Water_Quality_DP1.20288.001__2021-07-02.avro
```

I'd expect `mc cp` to work on these paths.

## Current Behavior

Instead, it fails with: 

```
 mc cp -r  neon/neon-is-transition-output/provisional/dpid=DP1.20288.001/ms=2021-07/site=BARC/ test

.001__2021-07-30.avro`. The specified key does not exist.
mc: <ERROR> Failed to copy `https://storage.googleapis.com/neon-is-transition-output/provisional/dpid%!D(MISSING)DP1.20288.001/ms%!D(MISSING)2021-07/site%!D(MISSING)BARC/BARC_L0_to_L1_Water_Quality_DP1.20288.001__2021-07-31.avro`. The specified key does not exist.
```

Note minio client has encoded the `=` as `%!D(MISSING)` instead of `%3D` here, no idea why .  Using percent-encoded paths to start with as input `mc cp` doesn't help either, as minio client says 

```
mc: <ERROR> Unable to validate source `neon/neon-is-transition-output/provisional/dpid%3DDP1.20288.001/ms%3D2021-07/site%3DBARC/`.
```

## Steps to Reproduce (for bugs)

Apologies that the above examples access a private bucket, but should be reproducible with basic commands on any Google Cloud Storage path that uses html-escaped characters in the path.  

## Context

Trying to use minio client to access data from GCS

## Regression
nope

## Your Environment

```

mc version RELEASE.2021-11-05T10-05-06Z

Linux thelio 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by harshavardhana** [comment]
This has nothing to do with `mc` the issue is Google Cloud doesn't implement encoding-type URL properly as per AWS S3 standards @cboettig 

You should ask GCS S3 layer to be fixed here - see here what works and what doesn't work with Google Cloud

https://gist.github.com/harshavardhana/5d4d7410afb02ec9837e2b4d82a932e7

**Comment by harshavardhana** [comment]
Also please open an issue related to `mc` at https://github.com/minio/mc/issues not here.

**Comment by cboettig** [comment]
awesome, thanks for the reply and apologies for the wrong location. Do you want me to open this particular one in `minio/mc` (I'm guessing not since as you say it's really a GCS problem)
