### ISSUE TITLE
Minio Console can not be served on subpath using the latest Minio version

### ISSUE THREAD

**Issue by siddjellali** [minio/minio#15859]
Hello, 

Subpath seems to be not working [#14761](https://github.com/minio/minio/pull/14761)

**nginx**
```
location /s3/ {
	rewrite ^/s3/(.*)$ $1 break;
	proxy_pass http://localhost:9001/s3/;
	expires -1;
 }
```

**Dockerfile**
```
ENV CONSOLE_SUBPATH /s3/
ENV MINIO_BROWSER_REDIRECT_URL http://localhost:9001/s3
```
`Version: DEVELOPMENT.2022-10-08T20-11-00Z`

![image](https://user-images.githubusercontent.com/3965823/195706680-b56dd7b9-68a2-4895-9a64-57967aea69a2.png)

BASE HTML balise seems good...

![image](https://user-images.githubusercontent.com/3965823/195706833-b27968b6-2945-42f7-9e91-79d84ef8e3fd.png)

Thanks for your support.

**Comment by harshavardhana** [comment]
> `Version: DEVELOPMENT.2022-10-08T20-11-00Z`

You are compiling your own ? 

> ENV CONSOLE_SUBPATH /s3/

This is useless to set

> location /s3/ {
> 	rewrite ^/s3/(.*)$ $1 break;
> 	proxy_pass http://localhost:9001/s3/;
> 	expires -1;
>  }

This is wrong https://github.com/minio/minio/pull/14761#issue-1205981691

Correct

```
location /s3/ {
	rewrite ^/s3/(.*)$ $1 break;
	proxy_pass http://localhost:9001/;
	expires -1;
 }
```

MINIO_BROWSER_REDIRECT_URL="http://localhost:8000/s3"  for starting MinIO

**Comment by siddjellali** [comment]
Excellent, thanks a lot.
Do you know if it's possible to have the same with API as well ?

**Comment by harshavardhana** [comment]
> Do you know if it's possible to have the same with API as well ?

No that is not allowed in S3 API

**Comment by carlvine500** [comment]
1. nginx.conf

```
    server {
        listen 7077;
        location /minio/ {
          rewrite "^/minio/(.*)$" /$1 break;
          proxy_pass http://localhost:9001;
        }
    }
```
2. docker command:
```
 docker run -p  9000:9000 -d -p 9001:9001 -e "MINIO_BROWSER_REDIRECT_URL=http://localhost:9001/minio/" -e "MINIO_ROOT_USER=minio111" -e "MINIO_ROOT_PASSWORD=minio111" quay.io/minio/minio server /data --console-address ":9001"
```
3. browser  url: http://192.168.1.14:7077/minio/login


![1211671780629_ pic](https://user-images.githubusercontent.com/7055460/209292226-e2e9f322-7951-4420-8f5c-d5aeee0625e7.jpg)
