### ISSUE TITLE
LDAP server error: LDAP is not configured

### ISSUE THREAD

**Issue by acheglakov** [minio/minio#15853]
LDAP server error: LDAP is not configured
## Expected Behavior

Update to RELEASE.2022-10-08T20-11-00Z broke my AD settings.

## Current Behavior

I used mcli admin update command. After update I got a message: "LDAP server error: LDAP is not configured" . 
I use minio in distributed environment with systemd scripts. AD settings are in systemd environment file. 

## Possible Solution

Downgraded to RELEASE.2022-10-05T14-58-27Z - it works fine.

## Steps to Reproduce (for bugs)

1. Distributed cluster version RELEASE.2022-10-05T14-58-27Z and above
2. Redhat8. Systemd service script with variable EnvironmentFile = /etc/default/minio
3. /etc/default/minio contains environment variables MINIO_VOLUMES, MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_IDENTITY_LDAP_SERVER_ADDR=... and so on
4. Upgrade to RELEASE.2022-10-08T20-11-00Z

## Context

AD do not work

## Regression

No
## Your Environment

* Version used (`minio --version`): RELEASE.2022-10-08T20-11-00Z
* Server setup and configuration: systemd scripts
* Operating System and version (`uname -a`): RedHat 8, Linux 4.18

**Comment by donatello** [comment]
Could you list the ldap related config parameters in use in your setup?

**Comment by acheglakov** [comment]
Hello!

Just from one node, others have similar config:
[root@node-t-as1 ~]# cat /etc/systemd/system/minio-test00.service
[Unit]
Description=Minio test00
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/test00/minio-test00


StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
WorkingDirectory=/usr/local/

User=minio-test00
Group=minio-test00

PermissionsStartOnly=true

EnvironmentFile=/etc/default/minio-test00
ExecStartPre=/bin/bash -c "[ -n \"${MINIO_VOLUMES}\" ] || echo \"Variable MINIO_VOLUMES not set in /etc/default/minio-test00\""

ExecStart=/usr/local/bin/test00/minio-test00 server $MINIO_OPTS $MINIO_VOLUMES
Restart=always

StandardOutput=journal
StandardError=inherit
LimitNOFILE=65536
TimeoutStopSec=0

KillSignal=SIGTERM

SendSIGKILL=no

SuccessExitStatus=0

[Install]
WantedBy=multi-user.target


[root@node-t-as1 ~]# cat /etc/default/minio-test00

MINIO_VOLUMES="https://node-t-as{1...6}.example.com:9000/data/test00"
MINIO_OPTS="--address node-t-as1.example.com:9000 -C /etc/minio-test00 --console-address :9050"

MINIO_ROOT_USER="LOGIN"
MINIO_ROOT_PASSWORD="PASSWORD"

MINIO_IDENTITY_LDAP_SERVER_ADDR="example.com:636"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="CN=testuser,OU=Users,DC=example,DC=com"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="password"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="DC=example,DC=com"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(&(objectCategory=user)(sAMAccountName=%s))"
MINIO_IDENTITY_LDAP_USERNAME_FORMAT="cn=%s,OU=Users,DC=example,DC=com"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="cn=test-group,OU=Groups,DC=example,DC=com"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=group)(member=%s))"
MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE="cn"
MINIO_IDENTITY_LDAP_STS_EXPIRY=1h
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on

MINIO_PROMETHEUS_URL="http://node-t-mc1:9090/"
MINIO_PROMETHEUS_JOB_ID="test00-9000"

**Comment by donatello** [comment]
These are not supported any more - if you restart your service with these removed, I believe it will work. You should be seeing some error messages at startup regarding this.

```
MINIO_IDENTITY_LDAP_USERNAME_FORMAT
MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE
```

**Comment by donatello** [comment]
I am closing this as I expect this will resolve the problem, if not please reopen it.
