### ISSUE TITLE
does not allow sso

### ISSUE THREAD

**Issue by Iceforestik** [minio/minio#15866]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

does not allow sso

## Expected Behavior

there should be an entry into the minio console
## Current Behavior

I type in my username and password after clicking on the Login with SSO button, I get back to the Login with SSO page and after that the login does not request any more, since it has filled out, but the console does not log in.

## Your Environment

* Version used (`minio --version`): 
minio version RELEASE.2022-10-05T14-58-27Z (commit-id=4bdf41a6c70ff5809c3db5c427f3cbee1a725b79)
Runtime: go1.18.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
* Operating System and version (`uname -a`):
Linux iceforest 5.4.0-128-generic #144~18.04.1-Ubuntu SMP Thu Sep 22 11:08:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

my openid config:
![изображение](https://user-images.githubusercontent.com/47591939/195806489-eab1d5cf-462f-49be-8bc2-109a03d51b21.png)
keycloak config:
![изображение](https://user-images.githubusercontent.com/47591939/195806611-b38aaa85-11d0-4be0-b126-f695f27b13ce.png)
![изображение](https://user-images.githubusercontent.com/47591939/195806767-82dd5358-03ac-44a5-b292-e022baf5b085.png)
![изображение](https://user-images.githubusercontent.com/47591939/195806810-b237fd41-c3e9-4b03-9fd2-d9230bbb0590.png)
![изображение](https://user-images.githubusercontent.com/47591939/195806923-d5129ff8-0486-415e-98eb-127b066448a8.png)
minio users:
![изображение](https://user-images.githubusercontent.com/47591939/195807055-0b2719b1-470f-4926-8fac-8c97c6bc2142.png)
![изображение](https://user-images.githubusercontent.com/47591939/195807138-54be73e1-291a-41b4-99f1-f76a1b19b39f.png)
minio policy:
![изображение](https://user-images.githubusercontent.com/47591939/195807218-74ac2af5-39bb-4eca-8a27-4112e86114f9.png)
![изображение](https://user-images.githubusercontent.com/47591939/195807299-5705c44a-404b-4853-9d67-273df01b1395.png)
additional information
if you remove scopes from the settings
![изображение](https://user-images.githubusercontent.com/47591939/195820209-c6409351-9bea-44e4-97cc-7261bc7e1a4f.png)
![изображение](https://user-images.githubusercontent.com/47591939/195820260-d5ad890f-79e7-4927-8ce0-8f0434871e41.png)
if you put OpenID in scope, then we get a 401 error
![изображение](https://user-images.githubusercontent.com/47591939/195824392-167b8fa1-a509-48ef-862c-29ef2dade171.png)

tell me, please, how can I determine why they are not allowed? it does not give out any errors. but as if he is missing something

**Comment by bpedersen2** [comment]
Looking at the policy I think you are not granting enough rights for the console, see https://github.com/minio/minio/issues/14099

**Comment by ravindk89** [comment]
just checking - your `policy` claim for that user has `readwriteuserjwt` as the value - but that policy does not appear to exist on MinIO. Can you change that value to `consoleAdmin` to start?

Once you confirm you can log in with the admin credentials, then it makes more sense to try restricting access based on S3 Resource and such.

**Comment by Iceforestik** [comment]
> just checking - your `policy` claim for that user has `readwriteuserjwt` as the value - but that policy does not appear to exist on MinIO. Can you change that value to `consoleAdmin` to start?
> 
> Once you confirm you can log in with the admin credentials, then it makes more sense to try restricting access based on S3 Resource and such.

> Looking at the policy I think you are not granting enough rights for the console, see #14099

I put the policy=consoleAdmin attribute in keycloak, but the error remained, I really already broke my whole head how to configure it
![изображение](https://user-images.githubusercontent.com/47591939/195971139-f0569d38-1a01-4b92-addc-252a1dd25aa4.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971160-e7f289e2-b19e-43f5-a054-bd31c6d3b128.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971171-a887b50b-3cce-42a0-ba01-049d43c3d685.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971188-36f4ffc1-4705-4144-b1d5-af3e6b45ede9.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971192-d7fa3b7b-19ab-4c3e-b4bc-bedb731f1ab5.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971198-af851cfa-b12d-417a-a36e-b56e71a5ac79.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971207-b0a3f35d-3e7e-4b2e-9532-b8cf76686080.png)
![изображение](https://user-images.githubusercontent.com/47591939/195971237-4dfa2bc0-aa12-4c43-85c9-4add76501bf4.png)

**Comment by donatello** [comment]
Could you do a server trace in a terminal with a command like:

```
mc admin trace -v -a --funcname 'sts.*' myminio
```

and then do a login attempt and show the results here?

So far I am not able to tell if the IDP is granting access and issuing a JWT.

**Comment by Iceforestik** [comment]
i dont know what is it, but now it works. thx
