### ISSUE TITLE
Mock slow S3 connections using minio

### ISSUE THREAD

**Issue by sighingnow** [minio/minio#15864]
**Is your feature request related to a problem? Please describe.**

Hi folks, we are searching for tools that can serve as a compatible S3 store but provides a _configurable_ and _stable_ slow (at the configured value) read / write throughput, for testing purpose.

Minio looks promising for us but I failed to find how to tuned such settings. May I know if such feature has already been supported by minio?

Thanks!

**Comment by harshavardhana** [comment]
You should use `tc` to configure the appropriate client speed on the client NIC.  You can't arbitrarily slowdown the server that is not what MinIO is meant for.

**Comment by sighingnow** [comment]
> You should use tc to configure the appropriate client speed on the client NIC. You can't arbitrarily slowdown the server that is not what MinIO is meant for.

I see. Thanks anyway!
