### ISSUE TITLE
File sharing error with docs/orchestration/docker-compose

### ISSUE THREAD

**Issue by KaymeKaydex** [minio/minio#15876]
iv got generated link for file share into my minio
`http://192.168.176.2:9000/test/b46xpy.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=SDBI8D1VXUG0OD0YBCXA%2F20221016%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221016T140018Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJTREJJOEQxVlhVRzBPRDBZQkNYQSIsImV4cCI6MTY2NTkzMjQwNiwicGFyZW50IjoibWluaW8ifQ.bnKbii7FhG0MeLGNH5ZC97GU_izZb5kgQMSsWsUQnTL5dC9apyWsmSbQc4OyfdyYLctRlO2svvzhxfIQj_8uwg&X-Amz-SignedHeaders=host&versionId=bbd197a2-1526-44a6-be74-aea5b0bd323d&X-Amz-Signature=09db4acc199ba0fef85ce32fae5959896b71c3c44af2355f9d78764a56804fff`
I replaced host to localhost 
then I created request, and got such error: 
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
<Key>b46xpy.jpg</Key>
<BucketName>test</BucketName>
<Resource>/test/b46xpy.jpg</Resource>
<RequestId>171E90FC16B4AE65</RequestId>
<HostId>92a93f42-872d-4f31-8182-fdad501c304f</HostId>
</Error>`

**Comment by KaymeKaydex** [comment]
I found similar problem https://github.com/minio/minio/issues/8897?ysclid=l9bf4q2q7j809259524

**Comment by harshavardhana** [comment]
You cannot replace URL names `host` is part of signature calculation.
