### ISSUE TITLE
No HTTP tracing in latest releases

### ISSUE THREAD

**Issue by titiviking** [minio/minio#15872]
Previous versions did proper tracing when using the command `mc admin trace -v s3minio` .
However the latest versions don't display the http traces anymore:

```
[root@2d152d1250c3 /]# mc admin trace -v s3minio
172.17.0.5:3000 [REQUEST s3.GetBucketLocation] [0001-01-01T00:00:00:000] [Client IP: ]
172.17.0.5:3000
172.17.0.5:3000 Proto:
172.17.0.5:3000 Host:
172.17.0.5:3000
172.17.0.5:3000 [RESPONSE] [0001-01-01T00:00:00:000] [ Duration 0s  ↑ 0 B  ↓ 0 B ]
172.17.0.5:3000 0
172.17.0.5:3000
172.17.0.5:3000
172.17.0.5:3000 [REQUEST s3.GetBucketLocation] [0001-01-01T00:00:00:000] [Client IP: ]
172.17.0.5:3000
172.17.0.5:3000 Proto:
172.17.0.5:3000 Host:
172.17.0.5:3000
172.17.0.5:3000 [RESPONSE] [0001-01-01T00:00:00:000] [ Duration 0s  ↑ 0 B  ↓ 0 B ]
172.17.0.5:3000 0
172.17.0.5:3000
172.17.0.5:3000
172.17.0.5:3000 [REQUEST s3.GetBucketObjectLockConfig] [0001-01-01T00:00:00:000] [Client IP: ]
172.17.0.5:3000
172.17.0.5:3000 Proto:
172.17.0.5:3000 Host:
172.17.0.5:3000
172.17.0.5:3000 [RESPONSE] [0001-01-01T00:00:00:000] [ Duration 0s  ↑ 0 B  ↓ 0 B ]
172.17.0.5:3000 0
172.17.0.5:3000
172.17.0.5:3000
```

**Comment by klauspost** [comment]
@titiviking Please post exact MinIO and mc versions.

**Comment by titiviking** [comment]
Minio:    Version: RELEASE.2022-10-08T20-11-00Z (go1.18.7 linux/amd64)
MC:        mc version RELEASE.2022-05-09T04-08-26Z

**Comment by klauspost** [comment]
@titiviking Please upgrade `mc` to a matching version and retry.

**Comment by titiviking** [comment]
With exact same version it works... surprised there is no warning or backward compatibility, but hey it's fixed at least for now.

**Comment by klauspost** [comment]
@titiviking You should always keep the versions in sync.

**Comment by harshavardhana** [comment]
> With exact same version it works... surprised there is no warning or backward compatibility, but hey it's fixed at least for now.

Older `mc` cannot tell that its talk to newer MinIO. `mc` must follow server release cycles.
