### ISSUE TITLE
minio admin web with nginx proxy manager , download image not working 403

### ISSUE THREAD

**Issue by MilesWuCode** [minio/minio#15877]
## Expected Behavior
i use docker and nginx proxy manager on one site server
```sh
docker run -d \
--name minio \
-v ${PWD}/data:/data \
-p 3105:9000 \
-p 3106:9001 \
-e MINIO_ROOT_USER=admin \
-e MINIO_ROOT_PASSWORD=password \
-e MINIO_SERVER_URL="https://minio.miles-home.cc" \
-e MINIO_BROWSER_REDIRECT_URL="https://minio-console.miles-home.cc" \
--restart unless-stopped \
minio/minio:latest \
server /data \
--address ":9000" \
--console-address ":9001"
```

## Current Behavior
minio admin :
create public buckets and  upload a.json b.jpg
only json file can be download
b.jpg can not preview and download

## Possible Solution
disabled
```sh
-e MINIO_SERVER_URL="https://minio.miles-home.cc" \ 
```
## Steps to Reproduce (for bugs)
![Screenshot 2022-10-17 2 06 31 PM](https://user-images.githubusercontent.com/1192835/196101372-176c1b78-ad16-459b-a7b7-1203a0679040.png)

![Screenshot 2022-10-17 2 07 14 PM](https://user-images.githubusercontent.com/1192835/196101396-b432a2ef-c2fc-4ef1-a3c0-afa2a65a05ab.png)

Metadata is empty
![Screenshot 2022-10-17 2 06 56 PM](https://user-images.githubusercontent.com/1192835/196101451-e03a53e1-295c-4b0e-b273-abc428bd4154.png)

## Your Environment

* Version used (`minio --version`):  minio/minio:RELEASE.2022-10-15T19-57-03Z
* Operating System and version (`uname -a`): Linux miles 5.15.0-50-generic Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please share your nginx config..
