### ISSUE TITLE
403 Forbidden when downloading via MINIO Console or any other S3 tool

### ISSUE THREAD

**Issue by PeterPilley** [minio/minio#15895]
## NOTE
Version: 2022-07-17T15:43:14Z
We have a Minio cluster set running on a docker swarm, we are using traefik to manage the connections.
We have a bucket that is a mix of videos and images, the issue we are seeing is we can upload to the nominated bucket fine, however if we try and download the files we are seeing a 403 Forbidden response.

If we create a shared link from the MINIO console the file is available. Which made me think permissions were the issue however the identity we are using has read/write access to the bucket. Do we need to set a seperate policy?

Checking the logs I cannot see any error messages or notifications.
Using trace within the Minio Console I can see LockR.lock 403 Forbidden (checking the issues here I can see this is apparently normal?)

## Expected Behavior
Uploads and Downloads should behave the same with read/write policy 

## Current Behavior
Uploads via MINIO Console or s3cmd or cyberduck work fine, downloads with either present 403

## Possible Solution
None

## Steps to Reproduce (for bugs)
* Create Bucket 
* Add Content
* Attempt to download content

## Context
We cannot use all the features within Minio

## Your Environment
Docker: Docker version 20.10.17, build 100c701
Configuration: Swarm with 3 managers, 3 workers, 
Proxy: Traefik
Operating System: Ubuntu 20.04

**Comment by harshavardhana** [comment]
> Uploads via MINIO Console or s3cmd or cyberduck work fine, downloads with either present 403

You do not have the right permissions @PeterPilley

**Comment by PeterPilley** [comment]
Hi @harshavardhana

So its a policy or access rules issue? Is the default policy to allow upload but not download?

**Comment by PeterPilley** [comment]
I have been working on this overnight and I cannot see any permission that should resolve this, @harshavardhana are you able to assist.

I have tried with the same credentials to download the file via mc and it is fine.

If I try to download via the Minio Console or Cyberduck I get a 403 Forbidden. The account has READWRITE permissions which I understood means they have full get/putObject permissions.

I have tested all the files uploaded and can actually download some of them but only around 10% the rest present forbidden.

I have tried a custom access rule but I cannot see any other way to set the "right permissions" so would really appreciate some guidance

**Comment by PeterPilley** [comment]
Just completed a test using the python minio library and can confirm I can upload and download items as expected, the same files when attempting to download via Cyberduck or via Minio Console present Forbidden.

I have also confirmed that using Cyberduck or Minio Console I can create and upload an object but cannot download, I can delete an object or prefix in Minio Console but I cannot delete a prefix in Cyberduck.
