### ISSUE TITLE
`The TagValue you have provided is invalid` breaks Console and tag deletion

### ISSUE THREAD

**Issue by pschichtel** [minio/minio#15903]
We have a minio instance with a couple of buckets that seem to have invalid tag values. I'm not sure how we managed to even write these values (has there recently been a problem with the validation in the tagging API?). These few affected buckets completely break the console login. Additionally, using mcli, I cannot remove the tags from the affected buckets.

It is always the same issue: `The TagValue you have provided is invalid`. The UI stays white after login, but the error can be found in the log.

## Expected Behavior

My expectation would have been, that invalid values can't even be added to objects. However assuming this could happen (e.g. through bugs), it should at least be possible to delete the broken tags. And in any case the console should not completely break, just because some of the buckets are invalid. It should either discard the invalid information, discard the invalid buckets/objects or at least display a useful message in the UI instead of a white blank page.

## Current Behavior
It is probably not currently possible to add invalid tags (not sure, since we remove these in out system), however if an invalid tag ends up on a bucket/project you won't be able to remove it and you won't be able to login to the console.

## Possible Solution
The login should handle the HTTP 400 response properly and continue with the remaining useful data and/or display a message indicating this issue.
The API should _at least_ allow to delete invalid tags, but I guess other operations could work too.

## Steps to Reproduce (for bugs)

1. Given a minio instance that has invalid tags on a bucket
2. try logging in to the console
3. try deleting the tags by running `mcli tag remove --debug your-minio/the-bucket`

## Your Environment

* Version used (`minio --version`): https://github.com/minio/minio/releases/tag/RELEASE.2022-10-05T14-58-27Z

**Comment by harshavardhana** [comment]
Any existing tags that were incompatible is not supported anymore.

We used to support a wider array of tag values which was wrong so we moved the tags to be more in line with S3 compatible behavior.

You can write an API call directly to wipe them.

**Comment by pschichtel** [comment]
We are using the regex `[^\p{L}\p{Z}\p{N}_.:/=+\-@]` from https://docs.aws.amazon.com/directoryservice/latest/devguide/API_Tag.html to replace invalid characters with underscores.

**Comment by harshavardhana** [comment]
> We are using the regex `[^\p{L}\p{Z}\p{N}_.:/=+\-@]` from https://docs.aws.amazon.com/directoryservice/latest/devguide/API_Tag.html to replace invalid characters with underscores.

This not true for all services, AWS S3 doesn't support this.

**Comment by pschichtel** [comment]
oh. is there a correct regex or list of characters that is supported?

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-go/blob/master/pkg/tags/tags.go#L72 @pschichtel

**Comment by harshavardhana** [comment]
> 3\. try deleting the tags by running `mcli tag remove --debug your-minio/the-bucket`

is this not allowed you say? @pschichtel can provide the full output?

**Comment by pschichtel** [comment]
```
mcli: <DEBUG> GET /8a38cb42-a396-4b97-a1cb-7d68411370f5/?location= HTTP/1.1
Host: some-host
User-Agent: MinIO (linux; amd64) minio-go/v7.0.34 mcli/RELEASE.2022-08-23T05-45-20Z
Authorization: 
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20221019T164633Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 19 Oct 2022 16:46:33 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 171F863F42BBD3DD
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mcli: <DEBUG> TLS Certificate found: 
mcli: <DEBUG>  >> Country: US
mcli: <DEBUG>  >> Organization: Let's Encrypt
mcli: <DEBUG>  >> Expires: 2022-12-26 19:42:58 +0000 UTC
mcli: <DEBUG> TLS Certificate found: 
mcli: <DEBUG>  >> Country: US
mcli: <DEBUG>  >> Organization: Internet Security Research Group
mcli: <DEBUG>  >> Expires: 2025-09-15 16:00:00 +0000 UTC
mcli: <DEBUG> TLS Certificate found: 
mcli: <DEBUG>  >> Organization: Digital Signature Trust Co.
mcli: <DEBUG>  >> Expires: 2024-09-30 18:14:03 +0000 UTC
mcli: <DEBUG> Response Time:  114.46329ms

mcli: <DEBUG> DELETE /8a38cb42-a396-4b97-a1cb-7d68411370f5/?tagging= HTTP/1.1
Host: some-host
User-Agent: MinIO (linux; amd64) minio-go/v7.0.34 mcli/RELEASE.2022-08-23T05-45-20Z
Authorization: 
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20221019T164633Z
Accept-Encoding: gzip

mcli: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 349
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 19 Oct 2022 16:46:33 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 171F863F438DCB76
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidTag</Code><Message>The TagValue you have provided is invalid</Message><BucketName>8a38cb42-a396-4b97-a1cb-7d68411370f5</BucketName><Resource>/8a38cb42-a396-4b97-a1cb-7d68411370f5/</Resource><RequestId>171F863F438DCB76</RequestId><HostId>076af6dd-a831-4ead-bfaa-d3530535b849</HostId></Error>mcli: <DEBUG> TLS Certificate found: 
mcli: <DEBUG>  >> Country: US
mcli: <DEBUG>  >> Organization: Let's Encrypt
mcli: <DEBUG>  >> Expires: 2022-12-26 19:42:58 +0000 UTC
mcli: <DEBUG> TLS Certificate found: 
mcli: <DEBUG>  >> Country: US
mcli: <DEBUG>  >> Organization: Internet Security Research Group
mcli: <DEBUG>  >> Expires: 2025-09-15 16:00:00 +0000 UTC
mcli: <DEBUG> TLS Certificate found: 
mcli: <DEBUG>  >> Organization: Digital Signature Trust Co.
mcli: <DEBUG>  >> Expires: 2024-09-30 18:14:03 +0000 UTC
mcli: <DEBUG> Response Time:  14.464088ms

mcli: <ERROR> Unable to remove tags for https://some-host/8a38cb42-a396-4b97-a1cb-7d68411370f5. The TagValue you have provided is invalid
 (0) client-s3.go:2536 cmd.(*S3Client).DeleteTags(..)
 Release-Tag:RELEASE.2022-08-23T05-45-20Z | Commit:07fffc3bc88f70a73c3714d9af23122f611b76cf | Host:cln888 | OS:linux | Arch:amd64 | Lang:go1.19 | Mem:2.6 MB/25 MB | Heap:2.6 MB/12 MB.
 ```

**Comment by pschichtel** [comment]
this is what the server logged:

```json
{
  "deploymentid": "076af6dd-a831-4ead-bfaa-d3530535b849",
  "level": "ERROR",
  "errKind": "ALL",
  "time": "2022-10-19T16:46:33.425914139Z",
  "api": {
    "name": "DeleteBucketTagging",
    "args": {
      "bucket": "8a38cb42-a396-4b97-a1cb-7d68411370f5"
    }
  },
  "remotehost": "some-ip",
  "host": "some-host",
  "requestID": "171F863F438DCB76",
  "userAgent": "MinIO (linux; amd64) minio-go/v7.0.34 mcli/RELEASE.2022-08-23T05-45-20Z",
  "error": {
    "message": "The TagValue you have provided is invalid (*tags.errTag)",
    "source": [
      "internal/logger/logger.go:259:logger.LogIf()",
      "cmd/api-errors.go:2164:cmd.toAPIErrorCode()",
      "cmd/api-errors.go:2189:cmd.toAPIError()",
      "cmd/bucket-handlers.go:1623:cmd.objectAPIHandlers.DeleteBucketTaggingHandler()",
      "net/http/server.go:2084:http.HandlerFunc.ServeHTTP()"
    ]
  }
}
```

**Comment by harshavardhana** [comment]
Yeah I think during delete we can avoid parsing things, let me send a fix for this.

**Comment by pschichtel** [comment]
Thanks @harshavardhana for the quick fix. Your pull request doesn't seem to do something about not being able to login. Do you consider that a non-issue since this issue can't really be reached in newer versions?

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana for the quick fix. Your pull request doesn't seem to do something about not being able to login. Do you consider that a non-issue since this issue can't really be reached in newer versions?

If you clear the tags then you can login, what the console login is performing is GetBucketTags() for the bucket and fails due to the invalid XML present on the disk.

**Comment by pschichtel** [comment]
Yes sure, but the handling of the situation could be better in the console. But I guess it's not really worth the effort for such an edge case.

**Comment by harshavardhana** [comment]
> Yes sure, but the handling of the situation could be better in the console. But I guess it's not really worth the effort for such an edge case.

Console UI can't do much here.
