### ISSUE TITLE
I uploaded files myself using via FileZilla, I cant show my files in minio console.

### ISSUE THREAD

**Issue by muhammedfurkan** [minio/minio#15919]
I uploaded big files using via Filezilla to minio volumes directory. I can't show my uploaded files in minio console. How can I do that?

## My Environment
* Version used (`minio --version`): mc version RELEASE.2022-10-20T23-26-33Z (commit-id=ad254a8fe2c7a72c3ae8a1a0ec44b799d9f6ef9a)

* Server setup and configuration:
* Operating System and version (`uname -a`): Linux server 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 16 12:17:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
@muhammedfurkan How did you do that. I haven't heard of filezilla supporting S3?

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html

Uploading files directly to the MinIO Volume is no longer supported from the 2022-06-02 release. 

You can either pin to that release, or find an S3-compatible file transfer utility to move files in and out of MinIO.

If you have a legacy deployment that you upgrade, you can retain the FS behavior. However there are no guarantees that we will retain that indefinitely. We have moved to a consistent erasure coded backend.
