### ISSUE TITLE
minio_bucket_usage_object_total doesn't get updated.

### ISSUE THREAD

**Issue by brianphhuang** [minio/minio#15913]
Recently, we found that `minio_bucket_usage_object_total` dones't get updated when we keep writing objects to MinIO cluster. Not sure it's caused by one of the buckets which stores all the objects at the root level without prefix.

## Expected Behavior
`minio_bucket_usage_object_total` keeps increasing when objects are ingested into MinIO.

## Current Behavior
`minio_bucket_usage_object_total`  gets stuck when the flat bucket (stores all the objects at root level).

## Steps to Reproduce (for bugs)
1. Create a bucket
2. Keep putting objects into that bucket.
3. `minio_bucket_usage_object_total`  will increase as objects are ingested at the root level into that bucket.
4. `minio_bucket_usage_object_total` gets stuck when the number is around 100 million.

## Your Environment
* Version used (`minio --version`):
 RELEASE.2022-07-26T00-53-03Z
* Server setup and configuration: 
 Helm chart deployment on K8s and 12 pods (1 pod lives in 1 K8s worker node) with 10 disks by each, 120 disks in total.

**Comment by harshavardhana** [comment]
@auxe9800 dumping objects in that manner at the root of the bucket will cause listings to fail as the filesystems stop responding to list such paths. 

We expect that you create a proper object hierarchy, this is why beyond 100m entries at the root prefix we collapse them. You should build your application properly to use object storage here.

We have no interest in encouraging these kinds of usage patterns
