### ISSUE TITLE
Create share link fails with default duration if there is a time change (DST) during the period

### ISSUE THREAD

**Issue by Elektordi** [minio/minio#15931]
Minio with the default settings (7 days limit on link expiration) fails with error "Expires cannot be greater than 7 days." if there is a time change (DST) which add time during the following 7 days.
(In France, we will add an hour on this sunday, 2022-10-30)

I think the bug in on the frontend.

## Expected Behavior
Share link should be displayed on the UI, as usual.

## Current Behavior
When clicking on the share button, an API call is made to:
https://xxxxxxxx/api/v1/buckets/xxxxx/objects/share?prefix=xxxxxxxxx=&version_id=null&expires=608400s
And response is:
{"code":500,"detailedMessage":"Expires cannot be greater than 7 days.","message":"an error occurred, please try again"}

## Possible Solution
The frontend should treat the time delta as dst-aware, so in my case, the default duration of 7d should be understood as 2022-10-24 10:00 to 2022-10-31 09:00, to compensate DST and send an API within the max length by default.

## Steps to Reproduce (for bugs)
1. Change your computer date to 2022-10-24 10:00:00 and timezone to Paris
2. Go to minio console
3. Open a bucket on click on a file
4. Click Share

## Context
We have a use case of non-technical users uploading images (maps) on minio console and then sending links to partners.
This monday, they all thought the console was broken because of this bug... :sweat_smile:  I explain them to change duration to 6d23h to "fix" the problem!

## Regression
No

## Your Environment
Our Minio is running on Kubernetes v1.17.2 (vanilla)
Image: minio/minio:RELEASE.2022-07-30T05-21-40Z

My browser is Firefox 105.0 on Ubuntu 20.04.5 LTS
Some of the others users I know are using Chrome on Windows 10.

**Comment by harshavardhana** [comment]
@Elektordi Console UI doesn't support lengthy expiration links via UI https://github.com/minio/console/issues/922 

However, you are advised to use `mc share download` for automation for now instead of UI.
