### ISSUE TITLE
unexpected disk ordering refusing to use the disk: expecting {host8}, found {host7}, refusing to use the disk (*fmt.wrapError)

### ISSUE THREAD

**Issue by nafisrdn** [minio/minio#15946]
We're expanding our MinIO to 8 Servers with 1 drive each, but 2 drives are offline.

## Expected Behavior
Should all servers and drives are online.

## Current Behavior
All servers are online but 2 drives offline
<img width="191" alt="minioasd" src="https://user-images.githubusercontent.com/37695356/197931392-86f2ce8f-d6d0-49d7-8189-3e27aef40d38.png">

with error log:
`Error: Following error has been printed 3 times.. Detected unexpected disk ordering refusing to use the disk: expecting http://minio8:9000/data_minio, found http://minio7:9000/data_minio, refusing to use the disk (*fmt.wrapError)
`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Expanding to 8 servers with 1 drive each.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-02-26T02-54-46Z
* Server setup and configuration:
* Operating System and version (`uname -a`): 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@nafisrdn as the message indicates you have incorrectly replaced the drives - please fix it.
