### ISSUE TITLE
Bucket replication support exclude files to replicate by prefix

### ISSUE THREAD

**Issue by creeew** [minio/minio#15942]
Some files cannot be replicated. And there's only a way that "version extension prefix-exclude" to exclude prefix matched file to be replicated, but file disable versioning if using version prefix-exclude.

In bucket replication setting, we can configure prefix in object filter. Objects could be replicated if the object's name matched the prefix.
That would be great if MinIO have a feature that objects cannot be replicated if object's name matched the prefix. Just like version extension prefix-exclude do.

https://github.com/minio/minio/blob/1673778633fd9b6c9b407fcd6a46536fa7692bbe/internal/bucket/replication/replication.go#L178
Object must be checked by this function "FilterActionableRules" before be replicated. Maybe we could add another check in this function. If prefix start with "!" means exclude, matched object cannot be replicated.
e.g.
prefix: !asd
file1: asd.jpg, file2: zxc.jpg
file2 can be replicate but file1 not

**Comment by harshavardhana** [comment]
We are not going to further extend this to do reverse of the existing logic @creeew
