### ISSUE TITLE
site-replication: Avoid making one host the single point of failure

### ISSUE THREAD

**Issue by omarkohl** [minio/minio#15944]
## Is your feature request related to a problem? Please describe.

If the host where I configure the site-replication goes down, then all hosts in the other site can no longer replicate data, despite other hosts being available in the local site. The other way around, if the replication target host in the remote site goes down, then all local hosts fail to replicate data to the remote site.

### Example

Setup:
* Two sites: site1, site2
* Three nodes in site1: site1-node{1...3}
* Three nodes in site2: site2-node{1...3}
* One client that can reach all sites and nodes

On **site1-node1**:
```bash
minio server http://site1-node{1...3}/site1/disk{1...4}
```

On **site2-node1**:
```bash
minio server http://site2-node{1...3}/site2/disk{1...4}
```

On **site1-node1**:
```bash
mc admin replicate site1-node1 site2-node1
```

Shut down **site1-node1**.

Now any changes (e.g. object creations) in site2 will no longer be replicated to site1. Changes in site1 will be replicated correctly to site2, indicating that all hosts seem to have an awareness of the target where they should replicate to. What is missing are _alternative targets_ (i.e. all the other hosts in site1 as targets for all hosts in site2).

## Describe the solution you'd like

As long as any (or enough) hosts in the other site are available, the replication should continue. Otherwise one host becomes a single point of failure for the site-replication.

An alternative syntax might help:

```bash
mc admin replicate add http://site1-node{1...3} http://site2-node{1...3}
```

**Comment by ravindk89** [comment]
@poornas i had assumed that site replication should not rely on any single node in a given site - assuming this is a bug? e.g. even if my alias is for `site1-node1`, the resulting replication config should include all hosts in `site1`.

Otherwise we would need some guidance in our docs around setting an alias for the load balancer or something similar that is configured for multiple hosts - afaik `mc alias set` does not support multi-host configs.

**Comment by poornas** [comment]
@omarkohl, if you configure a node endpoint in site replication, what you are seeing is expected - for proper failover, you should be using a loadbalancer in front of each site and configuring site replication with LB urls.

Check out https://github.com/minio/sidekick - this is a lightweight loadbalancer that you can  run for each site to loadbalance requests to the nodes in the site. Then edit your site replication config to use this loadbalancer endpoint with `mc admin replicate edit`

**Comment by ravindk89** [comment]
I'm opening a docs ticket to make this more explicit, both in terms of expected setup and behavior. 

Adding sidekick docs is out of scope at this time, so at the very least we need to make this behavior very clear. @omarkohl feel free to comment or otherwise follow that issue.
