### ISSUE TITLE
User metadata not retrieved with latest minio docker

### ISSUE THREAD

**Issue by kad-willej** [minio/minio#15955]
## NOTE

When I installed yesterday the docker container again. I couldn't fetch the usermetadata anymore (minio-java lib), it returns an empty list instead of the data.

## Expected Behavior

The usermetaData is filled with results

## Current Behavior

the usermetaData returns an empty list

## Steps to Reproduce (for bugs)

1. Use putobject with usermetadata
2. fetch listObject (includeUserMetadata(true))
3. item.get().usermetaData()

## Regression

Yes its a regression it worked before (docker: minio/minio:latest at 26-10-2022)

## Your Environment

Env: official docker container
minio version: RELEASE.2022-02-26T02-54-46Z

**Comment by harshavardhana** [comment]
This has been changed which SDK are you using? @kad-willej

**Comment by harshavardhana** [comment]
Upgrade your Java dependency https://github.com/minio/minio-java/commit/f909b02fc86d9f455fcb82502ab820efaa6f6865

**Comment by kad-willej** [comment]
I have installed 8.4.5 which seems to be the latest on maven?

**Comment by harshavardhana** [comment]
> I have installed 8.4.5 which seems to be the latest on maven?

and you need to upgrade server as well.

**Comment by kad-willej** [comment]
If you look at the ticket you see I installed the lastest docker server.

**Comment by kad-willej** [comment]
I was the one who also reported the previous bug, but there seems te be a new regression.

**Comment by harshavardhana** [comment]
> I was the one who also reported the previous bug, but there seems te be a new regression.

I don't see any regression @kad-willej I am using minio-java listObjects() works fine.
