### ISSUE TITLE
Prometheus metric "minio_cluster_disk_offline_total" seems stuck even though all disks are online

### ISSUE THREAD

**Issue by enrico2828** [minio/minio#15959]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

We notice that some of our Minio pods in Kubernetes keep reporting wrong # of disks offline for a long time. All disks are online. It seems the metric is somehow "stuck". A restart seems to lead to reporting accurate numbers again.

## Expected Behavior
The prometheus metric should report the accurate number as seen in the UI of with the `mc admin info` command.

## Current Behavior
Some pods are stuck on a very high number. This kind of very high number of offline disks can only occur during restart of some servers (which sometimes we have to do due to repairs or upgrades) en is temporarily. When the server or Minio pod comes back online, then the # of disks offline should be updated.

## Possible Solution
Workaround seems to be to restart the pod after which the numbers are accurate again.

## Steps to Reproduce (for bugs)
We noticed that on a production server. At the moment we don't have the facility to try to explicitly reproduce it.

## Context
If the number is not reported correctly it leads to false alarms which will make us turn off the alarm. If there is a real disk failure, we will not notice.

## Regression
Unknown.

## Your Environment
OpenShift 4.10
Minio Version: 2022-09-17T00:09:45Z
Minio Operator 4.5.1
![CleanShot 2022-10-28 at 09 51 47](https://user-images.githubusercontent.com/14042813/198541655-0a9c4a11-c2c2-4ef0-9ee5-abb2ec7b4219.png)

**Comment by vadmeste** [comment]
@enrico2828 do you still have the issue or it is gone away ?

**Comment by enwelder** [comment]
@vadmeste I experienced it today so yes it is a current issue.

**Comment by vadmeste** [comment]
@enrico2828 can you run

`curl -s -H "Authorization: Bearer $(mc admin prometheus generate <alias> --json | jq -r .bearerToken)" https://<your-minio-endpoint>/minio/v2/metrics/cluster  | grep minio_cluster_disk` and check if it is the same output ?

Please edit <alias> and <your-minio-endpoint> first.

**Comment by harshavardhana** [comment]
@enrico2828 is this cluster used for commercial purposes?

**Comment by enwelder** [comment]
The metrics are reported correctly now after restarting the pods. I tried to reproduce the behavior, but for the moment cannot. 
@harshavardhana we are a public service, not for profit organisation and by the way license acquisition is in progress.

**Comment by acheglakov** [comment]
Hello!
I have the same issue.

for i in cl1 s1 s2 s3 s4 s5 s6; do curl -k -H "Authorization: Bearer TOKEN" https://node-$i.example.com:9000/minio/v2/metrics/cluster > cluster_$i; done

grep "^minio_cluster_disk_o"  cluster_*
cluster_s1:minio_cluster_disk_offline_total{server="node-s1.example.com:9000"} 0
cluster_s1:minio_cluster_disk_online_total{server="node-s1.example.com:9000"} 6
cluster_s2:minio_cluster_disk_offline_total{server="node-s2.example.com:9000"} 0
cluster_s2:minio_cluster_disk_online_total{server="node-s2.example.com:9000"} 6
cluster_s3:minio_cluster_disk_offline_total{server="node-s3.example.com:9000"} 0
cluster_s3:minio_cluster_disk_online_total{server="node-s3.example.com:9000"} 6
cluster_s4:minio_cluster_disk_offline_total{server="node-s4.example.com:9000"} 0
cluster_s4:minio_cluster_disk_online_total{server="node-s4.example.com:9000"} 6
cluster_s5:minio_cluster_disk_offline_total{server="node-s5.example.com:9000"} 1
cluster_s5:minio_cluster_disk_online_total{server="node-s5.example.com:9000"} 5
cluster_s6:minio_cluster_disk_offline_total{server="node-s6.example.com:9000"} 0
cluster_s6:minio_cluster_disk_online_total{server="node-s6.example.com:9000"} 6
cluster_cl1:minio_cluster_disk_offline_total{server="node-s1.example.com:9000"} 0
cluster_cl1:minio_cluster_disk_online_total{server="node-s1.example.com:9000"} 6

mcli admin info myminio

●  node-s1.example.com:9000
   Uptime: 1 week
   Version: 2022-10-08T20:11:00Z
   Network: 6/6 OK
   Drives: 1/1 OK
   Pool: 1

●  node-s2.example.com:9000
   Uptime: 1 day
   Version: 2022-10-08T20:11:00Z
   Network: 6/6 OK
   Drives: 1/1 OK
   Pool: 1

●  node-s3.example.com:9000
   Uptime: 8 hours
   Version: 2022-10-08T20:11:00Z
   Network: 6/6 OK
   Drives: 1/1 OK
   Pool: 1

●  node-s4.example.com:9000
   Uptime: 1 week
   Version: 2022-10-08T20:11:00Z
   Network: 6/6 OK
   Drives: 1/1 OK
   Pool: 1

●  node-s5.example.com:9000
   Uptime: 1 week
   Version: 2022-10-08T20:11:00Z
   Network: 6/6 OK
   Drives: 1/1 OK
   Pool: 1

●  node-s6.example.com:9000
   Uptime: 6 hours
   Version: 2022-10-08T20:11:00Z
   Network: 6/6 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 6

22 GiB Used, 6 Buckets, 853 Objects
6 drives online, 0 drives offline

Nodes reboot automatically for security updates

**Comment by enwelder** [comment]
The problem reappeared 2 days ago, seemingly out of nowhere, as the Minio pods have been online for about a week by now. Out of the 8 pods, 3 are reporting that there are disks offline, each with a different number also (5, 1 and 7)
I really think that it could be a problem that the disks indeed are temporarily unavail
![CleanShot 2022-11-09 at 09 35 13](https://user-images.githubusercontent.com/14042813/200781518-82c1d910-826b-4141-b041-9ac1b4c9139a.png)
able (maybe also a network outage), but then the metric is never updated correctly when the disks [reappear.
![CleanShot 2022-11-09 at 09 37 40](https://user-images.githubusercontent.com/14042813/200781533-6de9a55b-ab74-4800-8aaa-4b7cc4a2799d.png)

**Comment by harshavardhana** [comment]
@enrico2828 the value here is cached up to 30secs - are you seeing these values not change even after 30secs? 

what is the time difference between Console UI output v/s Prometheus query?

**Comment by enwelder** [comment]
@harshavardhana here is the results:
The prometheus query in the na-minio-pool-0-7 pod gives
```
# HELP minio_cluster_disk_offline_total Total drives offline
# TYPE minio_cluster_disk_offline_total gauge
minio_cluster_disk_offline_total{server="na-minio-pool-0-7.na-minio-hl.na-minio.svc.cluster.local:9000"} 5
# HELP minio_cluster_disk_online_total Total drives online
# TYPE minio_cluster_disk_online_total gauge
minio_cluster_disk_online_total{server="na-minio-pool-0-7.na-minio-hl.na-minio.svc.cluster.local:9000"} 427
# HELP minio_cluster_disk_total Total drives
# TYPE minio_cluster_disk_total gauge
minio_cluster_disk_total{server="na-minio-pool-0-7.na-minio-hl.na-minio.svc.cluster.local:9000"} 432
```

The mc admin info command gives:
```
●  na-minio-pool-0-7.na-minio-hl.na-minio.svc.cluster.local:9000
   Uptime: 1 week
   Version: 2022-09-17T00:09:45Z
   Network: 8/8 OK
   Drives: 54/54 OK
   Pool: 1

Pools:
   1st, Erasure sets: 27, Disks per erasure set: 16

37 TiB Used, 63 Buckets, 7,100,850 Objects, 8 Versions
432 drives online, 0 drives offline
```

The prometheus data does not seem to refresh :(

**Comment by harshavardhana** [comment]
@enrico2828 I tried with the latest release I am unable to reproduce this problem even on a multiple-pool setup and taking down nodes at random. 

I see after 30secs the Prometheus metrics start reporting the correct values.

**Comment by enwelder** [comment]
@harshavardhana I just checked and since my last report the three pods never went back to zero but stayed in their non zero reported offline disks state. I have just restarted the pods, and now they are correctly reporting 0 disks..
I will keep an eye on the instance for when it goes back to non zero and will try to relate it to something that might have happened in the cluster.
![CleanShot 2022-11-11 at 20 30 56](https://user-images.githubusercontent.com/14042813/201416728-7760bb1d-3b3f-4e14-9b41-036734fe53c7.png)

**Comment by hepengju** [comment]
we meet this too.  minio_cluster_disk_online_total  16 --> 7  --> 16 --> 7 ...
RELEASE.2022-08-11T00-30-48Z
![image](https://user-images.githubusercontent.com/26279882/202385401-ca1f52b8-98b8-45b5-831a-11d024812b7e.png)

**Comment by harshavardhana** [comment]
> we meet this too. minio_cluster_disk_online_total 16 --> 7 --> 16 --> 7 ...

@hepengju this issue is not about changing online/offline - in your case at regular intervals, it looks like your nodes are getting disconnected. This issue is quite different than your cluster.

Prometheus continues to say offline even after other nodes say online disks. However, we haven't been able to reproduce this locally.

**Comment by hepengju** [comment]
thank you for your reply, maybe it's different about this issue, but our nodes is always online.
![image](https://user-images.githubusercontent.com/26279882/202393392-cf8a1493-2dec-4f28-9f82-9e4fff2c6918.png)

**Comment by XTUxiongda** [comment]
> > we meet this too. minio_cluster_disk_online_total 16 --> 7 --> 16 --> 7 ...
> 
> @hepengju this issue is not about changing online/offline - in your case at regular intervals, it looks like your nodes are getting disconnected. This issue is quite different than your cluster.
> 
> Prometheus continues to say offline even after other nodes say online disks. However, we haven't been able to reproduce this locally.

My situation is the same as that of him. I just mentioned a discussion[https://github.com/minio/minio/discussions/16081](url) 
The indicator data minio_cluster_disk_online_total collected by prometheus shows that the line has been disconnected repeatedly, but the mc admin info has been displayed normally

**Comment by acheglakov** [comment]
You could reproduce this issue for clusters with lack of resources (CPU or RAM). For example start several instances on a different ports with limited amount of RAM in VM and give some load.

**Comment by enwelder** [comment]
Yesterday it happened again. The sequence was as follows:
- there were 3 physical disk failures in 2 nodes
- the 3 failed disks were removed from the minio cluster by deleting the PVC en restarting the Minio pods
- Upon restart, the 2 minio pods where claiming 3 healthy disks
- temporarily it looked all good, and the metrics reported all nodes have healthy disks
- some time later, I suddenly received an alert for 2 of the 8 minio pods reporting missing offline disks 
It remains a mystery to me why the Minio pods would report that, and why only 2 of the 8, and why always a deviating amount of missing disks? 
It is quite a problem because we do not get reliable information now from the metrics / alerts on missing disks.
![CleanShot 2022-11-23 at 09 15 30](https://user-images.githubusercontent.com/14042813/203498915-e871e45a-935e-4e30-b5e2-f4882ec5f5db.png)

**Comment by harshavardhana** [comment]
> Yesterday it happened again. The sequence was as follows:
> 
> * there were 3 physical disk failures in 2 nodes
> * the 3 failed disks were removed from the minio cluster by deleting the PVC en restarting the Minio pods
> * Upon restart, the 2 minio pods where claiming 3 healthy disks
> * temporarily it looked all good, and the metrics reported all nodes have healthy disks
> * some time later, I suddenly received an alert for 2 of the 8 minio pods reporting missing offline disks
>   It remains a mystery to me why the Minio pods would report that, and why only 2 of the 8, and why always a deviating amount of missing disks?
>   It is quite a problem because we do not get reliable information now from the metrics / alerts on missing disks.
>   ![CleanShot 2022-11-23 at 09 15 30](https://user-images.githubusercontent.com/14042813/203498915-e871e45a-935e-4e30-b5e2-f4882ec5f5db.png)

I will try to reproduce this once again with your conditions.

**Comment by akong77** [comment]
I have the same problem.Prometheus always show 3 disk offline.But I make sure all disk online.

root@minio-4:~# mc admin info minio4-akong --insecure
●  minio-1.aspa.idv.tw:9000
   Uptime: 1 day
   Version: 2022-11-17T23:20:09Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  minio-2.aspa.idv.tw:9000
   Uptime: 1 day
   Version: 2022-11-17T23:20:09Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  minio-3.aspa.idv.tw:9000
   Uptime: 1 day
   Version: 2022-11-17T23:20:09Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  minio-4.aspa.idv.tw:9000
   Uptime: 3 minutes
   Version: 2022-11-17T23:20:09Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 16

1.6 TiB Used, 4 Buckets, 103,774 Objects, 85,061 Versions
16 drives online, 0 drives offline

How to fix it?
