### ISSUE TITLE
Storage resources are insufficient for the read operation .minio.sys/buckets/.background-heal.json (cmd.InsufficientReadQuorum)

### ISSUE THREAD

**Issue by fhemberger** [minio/minio#15966]
I'm running minio on my Synology NAS (DS414) in standalone mode.

Lately I decided to automatically shut down my NAS overnight and have it come back online in the morning. Unfortunately, this always causes the same error in minio, each time the system starts again:

```
Error: Storage resources are insufficient for the read operation .minio.sys/buckets/.background-heal.json (cmd.InsufficientReadQuorum)
4: internal/logger/logger.go:259:logger.LogIf()
3: cmd/data-scanner.go:125:cmd.readBackgroundHealInfo()
2: cmd/data-scanner.go:200:cmd.runDataScanner()
1: cmd/data-scanner.go:83:cmd.initDataScanner.func1()
```

Running `mc admin info local`, it states `Drives: 0/1 OK`.

I'm using the default [systemd unit file](https://github.com/minio/minio-service/blob/master/linux-systemd/minio.service) provided by minio to manage the service.

All bucket data seems to be fine and I can "solve" this issue by deleting `.minio.sys/buckets/.background-heal.json` manually and restarting the service. Same issue appears after the next shutdown/restart of the NAS.

## Environment
* minio version: `RELEASE.2022-10-08T20-11-00Z`, `RELEASE.2022-10-15T19-57-03Z`  
  (I noticed this behavior both releases, haven't tested it with older ones.)
* Synology DSM 7.1.1-42962 Update 1
* Operating System and version (`uname -a`):  
  Linux DiskStation 3.2.101 #42962 SMP Tue Sep 20 22:51:18 CST 2022 armv7l GNU/Linux synology_armadaxp_ds414
* `systemctl --version`: systemd 219  
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK +SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

This *may* be related to Synology's vastly outdated kernel and/or systemd version.

**Comment by harshavardhana** [comment]
@fhemberger it seems like if you do that - your persistent data is gone.

You would have to consult Synology docs for how to persist data on it.

**Comment by fhemberger** [comment]
@harshavardhana Persisted data in all my buckets are fine. I'm using minio for restic among other. When I validate my backups, everything checks out just fine.

Please reopen the issue.

**Comment by harshavardhana** [comment]
If everything is fine what is the problem? - we expect certain files we write to `.minio.sys/` folder to be readable if that is not readable then it won't work. 

So you need to check your deployment here.

**Comment by fhemberger** [comment]
Everything works *except with this single file* above. minio runs as root (yes, I know it's not desirable, but everything else is a hassle on Synology), file acces rights are not the issue. This error only occurs when the NAS is powered down over night, not when it's running 24/7. So I guess the service is not terminated properly when the system shuts down (maybe a signal is sent despite a different setting in the unit).  

I'm following the deployment as described on your site, with your systemd unit.

So a little help debugging this would be appreciated. Like is there anything written to disk (e.g. metadata) when the service exits that might cause this behavior on startup? As `mc admin heal` is deprecated, is there another way to check the data integrity on a standalone installation? What is the purpose of `.background-heal.json`? (just contains a single line, no reference to any file stored in the data directory)

**Comment by harshavardhana** [comment]
> So a little help debugging this would be appreciated. Like is there anything written to disk (e.g. metadata) when the service exits that might cause this behavior on startup? As `mc admin heal` is deprecated, is there another way to check the data integrity on a standalone installation? What is the purpose of `.background-heal.json`? (just contains a single line, no reference to any file stored in the data directory)

There is no reason for this file to be present for a single drive usage or even expected. I think we should simply ignore it for single-drive mode. There is nothing to heal in single drive mode there is no erasure coding no HA.

**Comment by fhemberger** [comment]
@harshavardhana Thanks for the change! I'll take a look and see if it fixes my problem for good.
