### ISSUE TITLE
It takes a lot of time to restart when building a Minio  cluster across cities

### ISSUE THREAD

**Issue by Jerryhax** [minio/minio#15975]
## Expected Behavior
startup minio cluster in in 1-2s

## Current Behavior
startup minio cluster in in 15-20s
(The four working nodes of K8S are distributed in four different cities)

## Steps to Reproduce (for bugs)

1. Distributed mino is running in the K8S cluster
2. kubectl     scale -n myminio  statefulset mymino   --replicas=0
3. kubectl     scale -n myminio  statefulset mymino   --replicas=4

## Context
The time from startup to normal login is too long.(about 18s)

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2022-02-24T22-12-01Z
* Server setup and configuration:
* Operating System and version (`uname -a`):Linux node2.mydomian.com.cn 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* K8s Version:Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by harshavardhana** [comment]
This is not supported @Jerryhax -. MinIO must not be deployed in a stretch cluster without bandwidth guarantees.

**Comment by harshavardhana** [comment]
> * Distributed mino is running in the K8S cluster
> * kubectl     scale -n myminio  statefulset mymino   --replicas=0
> * kubectl     scale -n myminio  statefulset mymino   --replicas=4

This is nothing but an incorrect k8s deployment - if you stretch your cluster in this manner. DNS requests will be very slow and you have an unstable k8s cluster.

**Comment by klauspost** [comment]
@Jerryhax You can write `sales@min.io` and we can help you configure your cluster properly and you can get direct support.

**Comment by Jerryhax** [comment]
thinks for reply. 
'kubectl scale' is used to restart the distributed mini cluster conveniently.
> It also takes about 15 seconds to restart the minio running on the physical node.
It only takes about 2 seconds to restart the distributed minio cluster witch nodes together.
