### ISSUE TITLE
Client_id claim missing from the JWT token, credentials will not be generated

### ISSUE THREAD

**Issue by huangyutongs** [minio/minio#15990]
## The minio I created using minio-operator Below is my configuration
```
MINIO_IDENTITY_OPENID_CLIENT_SECRET="123456"
MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
MINIO_ROOT_USER="1234"
MINIO_ROOT_PASSWORD="1234"
MINIO_IDENTITY_OPENID_CONFIG_URL="https://sts.baidu.cn/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID="minio"
MINIO_BROWSER="on"
MINIO_STORAGE_CLASS_STANDARD="EC:2"
MINIO_IDENTITY_OPENID_CLAIM_NAME="client_id"
MINIO_IDENTITY_OPENID_REDIRECT_URI="https://minio.baidu.cn/oauth_callback"
```
minio-console show
![image](https://user-images.githubusercontent.com/48778924/199393985-dfbb83fb-19f7-4a01-baf0-2498f9c5bb27.png)

to track  ，jwt decodes to
```
mc admin trace -v -a hub

{
  "nbf": 1667361129,
  "exp": 1667364729,
  "iss": "https://sts.baidu.cn",
  "aud": "https://sts.baidu.cn/resources",
  "client_id": "minio",
  "sub": "2089",
  "auth_time": 1667361129,
  "idp": "local",
  "name": "test",
  "preferred_username": "test",
  "family_name": "test",
  "email": "test@baidu.com",
  "EnCodeName": "test",
  "avatar": "http://baidu.com/bizmail/2ADdQ7liaC4uadU5ePibkzLqdAdJedcidcUO3JQjVEwA/110",
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "amr": [
    "pwd"
  ]
}
```

I create local policy，When I use CLAIM_NAME="idp" it logs in fine
```
MINIO_IDENTITY_OPENID_CLIENT_SECRET="123456"
MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
MINIO_ROOT_USER="1234"
MINIO_ROOT_PASSWORD="1234"
MINIO_IDENTITY_OPENID_CONFIG_URL="https://sts.baidu.cn/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID="minio"
MINIO_BROWSER="on"
MINIO_STORAGE_CLASS_STANDARD="EC:2"
MINIO_IDENTITY_OPENID_CLAIM_NAME="idp"
MINIO_IDENTITY_OPENID_REDIRECT_URI="https://minio.baidu.cn/oauth_callback"
```

I create 2089 policy，When I use CLAIM_NAME="sub" it still logs in fine
```
MINIO_IDENTITY_OPENID_CLIENT_SECRET="123456"
MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
MINIO_ROOT_USER="1234"
MINIO_ROOT_PASSWORD="1234"
MINIO_IDENTITY_OPENID_CONFIG_URL="https://sts.baidu.cn/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID="minio"
MINIO_BROWSER="on"
MINIO_STORAGE_CLASS_STANDARD="EC:2"
MINIO_IDENTITY_OPENID_CLAIM_NAME="sub"
MINIO_IDENTITY_OPENID_REDIRECT_URI="https://minio.baidu.cn/oauth_callback"
```

CLAIM_NAME  Does not support underscore?

**Comment by harshavardhana** [comment]
> MINIO_IDENTITY_OPENID_CLAIM_NAME="client_id"

This is not a claim name @hyt05

**Comment by squidward05** [comment]
> MINIO_IDENTITY_OPENID_CLAIM_NAME="client_id"

Which of the jwts I returned above are valid CLAIM NAMEs?

**Comment by donatello** [comment]
@hyt05 Any of the keys in the JWT payload can be used as a claim for setting access policies in MinIO. Keys with underscores should also work (I have verified this), but currently my test setup cannot generate a JWT with `client_id` as a claim. Not sure why it didn't work for you. Could you check if a claim like `family_name` is working for you?

**Comment by squidward05** [comment]
> @hyt05 Any of the keys in the JWT payload can be used as a claim for setting access policies in MinIO. Keys with underscores should also work (I have verified this), but currently my test setup cannot generate a JWT with `client_id` as a claim. Not sure why it didn't work for you. Could you check if a claim like `family_name` is working for you?

family_name  CLAIM  works for me，
find something interesting，When using a successful family_name CLAIM
```mc admin trace -v -a hub```
Parse jwt display
```
{
  "EnCodeName": "6dbudEd5pixd6YCa",
  "accessKey": "QBOEdYddKFdZd0Hd7WJA",
  "amr": [
    "pwd"
  ],
  "at_hash": "aKdXdNb5dBieTCLHpD",
  "aud": "minio",
  "auth_time": 1667526867,
  "avatar": "http://baidu.com/bizmail/2ADdQ7liaC4uadU5ePibkzLqdAdJedcidcUO3JQjVEwA/110",
  "email": "test@baidu.com",
  "exp": 166d75d325,
  "family_name": "test",
  "iat": 1667530825,
  "idp": "local",
  "iss": "https://sts.baidu.cn",
  "name": "test",
  "nbf": 1667530825,
  "preferred_username": "test",
  "sid": "8034addd2f1959972c2ddd0518e66",
  "sub": "2089"
}
```
when using unsuccessful ```client_id``` CLAIM
```mc admin trace -v -a hub ```
Parse jwt display
```
{
  "nbf": 1667361129,
  "exp": 1667364729,
  "iss": "https://sts.baidu.cn",
  "aud": "https://sts.baidu.cn/resources",
  "client_id": "minio",
  "sub": "2089",
  "auth_time": 1667361129,
  "idp": "local",
  "name": "test",
  "preferred_username": "test",
  "family_name": "test",
  "email": "test@baidu.com",
  "EnCodeName": "test",
  "avatar": "http://baidu.com/bizmail/2ADdQ7liaC4uadU5ePibkzLqdAdJedcidcUO3JQjVEwA/110",
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "amr": [
    "pwd"
  ]
}
```

I noticed that using CLAIM with success，The jwt parsed by minio is missing part of the claim

**Comment by donatello** [comment]
I think there is a difference in how your OpenID service is returning tokens. The JWT is being parsed fine by MinIO AFAICT - you can decode the JWT from the trace output on some service like https://jwt.ms to see the actual content of the token - the highlighted part below is the token:

![image](https://user-images.githubusercontent.com/200059/200045831-44a52385-7f0b-4afc-9595-74284d77c6a5.png)

When you are using `client_id` as the claim, your IDP is sending a token with the claim `"aud":  "https://sts.baidu.cn/resources"` which means the token is not meant for minio. The audience claim must be the value of the client_id config parameter in minio (here it is = `minio`). I am not why your IDP is behaving this way though.

**Comment by harshavardhana** [comment]
> When you are using `client_id` as the claim, your IDP is sending a token with the claim `"aud": "https://sts.baidu.cn/resources"` which means the token is not meant for minio. The audience claim must be the value of the client_id config parameter in minio (here it is = `minio`). I am not why your IDP is behaving this way though.

It is a spec deviation here @donatello - we can perhaps close this issue since this is a non-standard behavior.

**Comment by alb-car** [comment]
I believe this is a case of an undocumented, yet required, environment variable missing: `MINIO_IDENTITY_OPENID_CLAIM_USERINFO="on"`.

In my situation, I was trying to configure MinIO with OIDC in Docker-Compose. I was following [this page](https://min.io/docs/minio/container/operations/external-iam/configure-openid-external-identity-management.html) and had the following configuration for my MinIO container:

```
  minio:
    image: minio/minio:RELEASE.2022-11-26T22-43-32Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "username"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_IDENTITY_OPENID_CONFIG_URL: "https://external_idp/.well-known/openid-configuration"
      MINIO_IDENTITY_OPENID_CLIENT_ID: "my_client_id"
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: "my_client_secret"
      MINIO_IDENTITY_OPENID_CLAIM_NAME: "policy"
      MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email"
      MINIO_IDENTITY_OPENID_REDIRECT_URI: "http://localhost:9001/oauth_callback"
  command: server /data --console-address ":9001"
```
Upon logging in, the same error as the original post's screenshot would appear (saying *Policy* instead).

But if I started MinIO without OIDC, configured the same exact values under *Settings* > *Identity Openid* **AND turned Claim UserInfo ON**, then, upon restarting, SSO would work. Without it, the same error would be returned.

Both the OIDC section and the [list of envs](https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-config.html) in the docs do not mention a variable for this setting.

Adding a `MINIO_IDENTITY_OPENID_CLAIM_USERINFO` env, with values `true`, `ON`, `1` all failed, but by setting it to `on` (yes, lower-case), it worked:
```
      MINIO_IDENTITY_OPENID_CLAIM_USERINFO: "on"
```

Maybe the documentation is incorrect, or maybe the env (which is admittedly sketchy) is not meant to exist.
Issue #16134 certainly didn't make debugging this any easier...

I hope this helps.

**Comment by harshavardhana** [comment]
> I believe this is a case of an undocumented, yet required, environment variable missing: `MINIO_IDENTITY_OPENID_CLAIM_USERINFO="on"`.

This is not required, this is only required if your OIDC does not provide enough information to MinIO in JWT instead requires us to reach out to a userinfo endpoint.

The userinfo endpoint is mainly used to expire credentials that are no longer active.

**Comment by harshavardhana** [comment]
@donatello could you send an update for the docs to indicate USERINFO is needed in cases where OIDC doesn't send the policy via JWT handshake?

**Comment by harshavardhana** [comment]
// cc @ravindk89 ^^

**Comment by ravindk89** [comment]
I'll follow up w/ @donatello here - this is distinct from our Admin API  support right? 

It would be helpful to understand when exactly to toggle this - is it only if the returned JWT has malformed or incorrect listings for `aud` or are there other points to check?
