### ISSUE TITLE
workaround for fs mode does not work

### ISSUE THREAD

**Issue by gdkrmr** [minio/minio#15999]
I upgraded from an older version of minio and and launching the new version (RELEASE.2022-10-29T06-21-33Z (go1.19.2 linux/amd64)) gives me the following error:

```
ERROR Unable to use the drive /mnt/datafs/data: Drive /mnt/datafs/data: found backend type fs, expected xl or xl-single: Invalid arguments specified
```

There is a file `.minio.sys/format.json` that indicates that the fs backend should be used but I keep getting the same error. `/mnt/datafs` is a btrfs volume but minio seems to think that `/mnt/datafs/data` is a drive.

**Comment by harshavardhana** [comment]
There is no workaround @gdkrmr this has been changed - you need to migrate https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/migrate-fs-gateway.html

**Comment by stavros-k** [comment]
Does an image roll back will allow it to run for now? Or rolling back to a previous image will break it more?

**Comment by harshavardhana** [comment]
> Does an image roll back will allow it to run for now? Or rolling back to a previous image will break it more?

You can of course rollback @stavros-k it should work I don't see why not.

**Comment by stavros-k** [comment]
> > Does an image roll back will allow it to run for now? Or rolling back to a previous image will break it more?
> 
> You can of course rollback @stavros-k it should work I don't see why not.

Thanks.
