### ISSUE TITLE
add bucket comments or remakes

### ISSUE THREAD

**Issue by A-BenMao** [minio/minio#16014]
**Is your feature request related to a problem? Please describe.**
Now, when you create a bucket, you cannot enter information about the bucket, such as its purpose, who is responsible, etc. I think this note function is very useful, especially for devops.

**Describe the solution you'd like**
When you create a bucket, you can have an input box to hold comments

**Additional context**
The mc should also synchronize changes

**Comment by harshavardhana** [comment]
This is not part of S3 API, once its available in AWS S3 - MinIO will implement them.

**Comment by harshavardhana** [comment]
> Now, when you create a bucket, you cannot enter information about the bucket, such as its purpose, who is responsible, etc. I think this note function is very useful, especially for devops.

You can store tags on the bucket - use the tag values as comment. Something like `notes="my engineering bucket"`
