### ISSUE TITLE
We encountered an internal error, please try again.: cause(decryption failed: ciphertext is not authentic)

### ISSUE THREAD

**Issue by MomentQYC** [minio/minio#16017]
## Expected Behavior

Console access to files in storage buckets with SSE-S3 encryption set,like this.
![image](https://user-images.githubusercontent.com/62551256/200260209-722a3511-090e-468b-b4fc-b6363138e492.png)

## Current Behavior

An error was displayed and the file could not be loaded.
![image](https://user-images.githubusercontent.com/62551256/200260497-caa9bf65-db31-41b5-a413-90e7506ae2b4.png)

## Possible Solution

I have no idea because I have never performed an operation that could affect encryption.

## Steps to Reproduce (for bugs)

1.Access to the web console.
2.Open the target storage bucket.

## Regression

Some files may have remote access errors (Access Denied)
I can't manipulate files in the storage bucket, either in the web console or in mcli

## Your Environment

* Version used (`minio --version`):minio version RELEASE.2022-10-29T06-21-33Z (commit-id=d765b89a63c225ca271ef6d031a7bcc8fe9137df)
* Server setup and configuration:
```
MINIO_VOLUMES="/mnt/data"
MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373
MINIO_KMS_KES_KEY_FILE=/path/to/root.key
MINIO_KMS_KES_CERT_FILE=/path/to/root.cert
MINIO_KMS_KES_KEY_NAME=my-minio-key
MINIO_ROOT_USER=*
MINIO_ROOT_PASSWORD=*
MINIO_DOMAIN=https://example.com
```
No problems with permissions
* Operating System and version (`uname -a`):
```
Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

PS:
Writing through the API is still valid.
KMS configuration has never been changed.

**Comment by harshavardhana** [comment]
> MINIO_VOLUMES="/mnt/data"
> MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373
> MINIO_KMS_KES_KEY_FILE=/path/to/root.key
> MINIO_KMS_KES_CERT_FILE=/path/to/root.cert
> MINIO_KMS_KES_KEY_NAME=my-minio-key
> MINIO_ROOT_USER=*
> MINIO_ROOT_PASSWORD=*
> MINIO_DOMAIN=https://example.com

yeah because you started a local server pointing to public KES instance. This instance can be purged anytime so your keys will be lost. 

Please re-do your setup and use a local KES deployment.

**Comment by MomentQYC** [comment]
> 

So how should I decrypt the encrypted files?

**Comment by harshavardhana** [comment]
> So how should I decrypt the encrypted files?

You cannot the master key from the public KES server because has been deleted - we had to re-do the setup. You should re-upload all your content. 

You should never rely on a public KES instance to store content locally. You should run a local KES (KMS) server that is managed by you.

**Comment by MomentQYC** [comment]
> You should never rely on a public KES instance to store content locally. You should run a local KES (KMS) server that is managed by you.

Is there a way to test if the KES server is successfully set up? I tried to replace it and this resulted in the web console not being able to log in.
Also does it mean that the previous files cannot be decrypted?

**Comment by harshavardhana** [comment]
> Is there a way to test if the KES server is successfully set up? I tried to replace it and this resulted in the web console not being able to log in.
> Also does it mean that the previous files cannot be decrypted?

you cannot just blindly replace KES previously configured, you have to entirely redo your setup. 

> Also does it mean that the previous files cannot be decrypted?

Yes that is correct you made a mistake.

**Comment by MomentQYC** [comment]
> 

Given that the encrypted files are still accessible, I assume that read and write operations are still possible
If I add an unencrypted bucket, is it not affected by this config?

**Comment by harshavardhana** [comment]
> Given that the encrypted files are still accessible, I assume that read and write operations are still possible
> If I add an unencrypted bucket, is it not affected by this config?

That is happening because the KES is active and it is using the new key. Your previous data was with a different key.  do you understand?

**Comment by MomentQYC** [comment]
> That is happening because the KES is active and it is using the new key. Your previous data was with a different key. do you understand?

I get it,thanks.
