### ISSUE TITLE
objectLayer: Save md5sum/content-type/content-encoding validated during PutObject

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1602]

**Comment by harshavardhana** [comment]
PutObject currently does not save any additional metadata we need to save all the special metadata presented to us over the HTTP request for each object. 

Simple examples we need to store are 
- md5sum sent by the client in the hex form, saved along with the object. 
- content-type if set the client application explicitly, 'mc' does that. 
- x-amz-meta\* tags if any, can be made generic.
- x-minio-meta\* tags if any, can be made generic. 

Easier would be store them in a simple map to be able to unmarshal easily.  This needs to be stored along with the object. in a special form and GetObject() will unmarshal this data during GET operation before replying back to the client.

**Comment by balamurugana** [comment]
TBD how to store the such meta data content.

**Comment by harshavardhana** [comment]
> TBD how to store the such meta data content.

Can you update the tentative date here @balamurugana ?

**Comment by balamurugana** [comment]
After the discussion we would need to store in information as `meta.json` as a separate put object.

**Comment by harshavardhana** [comment]
> After the discussion we would need to store in information as meta.json as a separate put object.

Yes this is correct it can be a proper meta file which is created along with the object as metadata file. possibly just a map of all the entries given in the PutObject() call as the last argument. Right now only 'md5sum' is populated. 

Similarly for NewMultipartUpload should take a map[string]string as well - good thing is multipart already has a structure as it is saved as is.

**Comment by balamurugana** [comment]
To be fixed on 18-May-2016

**Comment by balamurugana** [comment]
Current limitation to CreateFile()/RenameFile() calls do not allow to create a meta data file as `mybucket/path/to/my/objectt/meta.json`
