### ISSUE TITLE
could not delete an empty folder in bucket

### ISSUE THREAD

**Issue by vklonghml** [minio/minio#16020]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

could not delete an empty folder in bucket

## Expected Behavior

delete an empty folder in bucket

## Steps to Reproduce (for bugs)

1.minioCli.RemoveObject(context.Background(), bucketName, objName, opt)
objName is an empty dir, whatever objName is "dir" or "dir/", RemoveObject return success, but objName still exist in bucket

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2022-10-15T19-57-03Z (commit-id=85fc7cea979b8da1689798e1e290847fd6517c55)
Runtime: go1.18.7 darwin/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc
* Server setup and configuration:
minio server ./data/ --console-address 127.0.0.1:9002 --address 127.0.0.1:9000
* Operating System and version (`uname -a`):
elrepo.x86_64 #1 SMP Tue Oct 27 16:04:41 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@vklonghml according to the S3 spec, deletion will always return success in all cases, this makes it harder to troubleshoot.

Can you do `mc ls --recurive --versions <alias>/bucket/dir` ?

**Comment by vklonghml** [comment]
[2022-11-09 16:52:16 CST]     0B STANDARD null v1 PUT dir1/
[2022-11-09 16:52:27 CST]     0B STANDARD null v1 PUT dir2/
[2022-11-09 16:52:37 CST]     0B STANDARD null v1 PUT dir3/
[2022-11-09 16:51:52 CST]     0B STANDARD null v1 PUT dir4/

**Comment by vklonghml** [comment]
> @vklonghml according to the S3 spec, deletion will always return success in all cases, this makes it harder to troubleshoot.
> 
> Can you do `mc ls --recurive --versions <alias>/bucket/dir` ?

[2022-11-09 16:52:16 CST]     0B STANDARD null v1 PUT dir1/
[2022-11-09 16:52:27 CST]     0B STANDARD null v1 PUT dir2/
[2022-11-09 16:52:37 CST]     0B STANDARD null v1 PUT dir3/
[2022-11-09 16:51:52 CST]     0B STANDARD null v1 PUT dir4/

**Comment by klauspost** [comment]
Your bucket is not empty. It has 4 objects.

Just because an object key ends in a `/` doesn't make it less of an object. There is no concept of "directories" in S3, only objects.
