### ISSUE TITLE
`Prefix access is denied` error while accessing data in S3

### ISSUE THREAD

**Issue by revolutionisme** [minio/minio#16032]
We have setup minio with s3 gateway and it has all the permissions necessary to access the relevant buckets. Even with that, we are getting the following error continuously. Minio is currently being used with Kubeflow and none of the metrics sent out from the pipeline are also showing up. 

```
minio 
minio API: SYSTEM()
minio Time: 14:37:37 UTC 11/07/2022
minio DeploymentID: 3b3f7a08-f532-4468-91ed-facfd3d66e12
minio Error: Prefix access is denied: metrics/ (cmd.PrefixAccessDenied)
minio        5: cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
minio        4: cmd/auth-handler.go:331:cmd.checkRequestAuthTypeCredential()
minio        3: cmd/auth-handler.go:269:cmd.checkRequestAuthType()
minio        2: cmd/bucket-listobjects-handlers.go:324:cmd.objectAPIHandlers.ListObjectsV1Handler()
minio        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
minio 
minio API: SYSTEM()
minio Time: 14:38:07 UTC 11/07/2022
minio DeploymentID: 3b3f7a08-f532-4468-91ed-facfd3d66e12
minio Error: Prefix access is denied: metrics/ (cmd.PrefixAccessDenied)
minio        5: cmd/bucket-policy.go:53:cmd.(*PolicySys).IsAllowed()
minio        4: cmd/auth-handler.go:331:cmd.checkRequestAuthTypeCredential()
minio        3: cmd/auth-handler.go:269:cmd.checkRequestAuthType()
minio        2: cmd/bucket-listobjects-handlers.go:324:cmd.objectAPIHandlers.ListObjectsV1Handler()
minio        1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```
## Expected Behavior
The metrics are stored and registered, and the error from the minio logs go away

## Current Behavior
Metrics are not showing up in the UI, we are getting the error docmented above. 

## Context

We have set up Minio (with IRSA) with Kubeflow and all the artifacts and logs are being stored properly. But when it comes to metrics, minio is throwing this error and its not very clear where to start looking and how to debug this issue. 

## Your Environment

* Version used (`minio --version`): RELEASE.2022-02-01T18-00-14Z
* Server setup and configuration: EKS -> v1.21.14-eks-fb459a0
* Operating System and version (`uname -a`): 5.4.209-116.367.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
MinIO Gateway is deprecated we do not support it anymore for community releases, if you are a subscribed customer then feel free to reach out to us at https://subnet.min.io
