### ISSUE TITLE
Content-MD5 verification not working for non-multipart PUT object

### ISSUE THREAD

**Issue by felixbuenemann** [minio/minio#1603]
I have noticed that both on minio 2016-04-17 and master the verification of the Content-MD5 header for PUT object ist not working.

Sending a bad checksum will not return the expected BadDigest error.

Tested on 2016-04-17 with FS and master with FS and XL backends.

Correct MD5 Hex: 1b61b1084812eebe8ad8f7e108148e1e
Correct MD5 Base64: G2GxCEgS7r6K2PfhCBSOHg==

Wrong MD5 Hex: 1b61b1084812eebe8ad8f7e108148e1f
Wrong MD5 Base64: G2GxCEgS7r6K2PfhCBSOHw==

``` sh
# try with correct content-md5
aws --profile minio --endpoint-url http://localhost:9000 s3api put-object --bucket test \
  --key Earth10k.jpg --body ~/Pictures/Earth10k.jpg --content-type "image/jpeg" \
  --content-md5 G2GxCEgS7r6K2PfhCBSOHg==
# Got:
{
    "ETag": "\"1b61b1084812eebe8ad8f7e108148e1e\""
}
# try with wrong content-md5
aws --profile minio --endpoint-url http://localhost:9000 s3api put-object --bucket test \
  --key Earth10k.jpg --body ~/Pictures/Earth10k.jpg --content-type "image/jpeg" \
  --content-md5 G2GxCEgS7r6K2PfhCBSOHw==
# Got:
{
    "ETag": "\"1b61b1084812eebe8ad8f7e108148e1e\""
}
# Expected:
A client error (BadDigest) occurred when calling the PutObject operation: The Content-Md5 you specified did not match what we received.
```

@harshavardhana Has already found the bug and will push a fix shortly.

**Comment by matti** [comment]
I'm getting `3aws: BadDigest: The Content-Md5 you specified did not match what we received.` when using minio as docker registry backend. Could this issue be back?

**Comment by harshavardhana** [comment]
> I'm getting 3aws: BadDigest: The Content-Md5 you specified did not match what we received. when using minio as docker registry backend. Could this issue be back?

@matti - you should open a new bug.
