### ISSUE TITLE
Unable to read ILM configuration. EOF

### ISSUE THREAD

**Issue by carlosjpr-collab** [minio/minio#16063]
## Expected behavior
I am trying to execute:
docker run --rm --network=host -v mc:/root/.mc minio/mc --debug ilm import minio/test< test.json
## Actual behavior
I am getting:
mc: <ERROR> Unable to read ILM configuration. EOF
 (1) ilm-import.go:106 cmd.mainILMImport(..) Tags: [minio/test]
 (0) ilm-import.go:79 cmd.readILMConfig(..)

## mc --version

 Release-Tag:RELEASE.2022-11-07T23-47-39Z | Commit:bc16bde337ad | Host:master | OS:linux

## System information
test.json

**Comment by klauspost** [comment]
You already posted an issue on mc: https://github.com/minio/mc/issues/4364
