### ISSUE TITLE
Error: unknown type of IAM file listed: config/tier-config.bin

### ISSUE THREAD

**Issue by brsolomon-deloitte** [minio/minio#16078]
## Current Behavior

MinIO logs are flooded with the following error:

```
API: SYSTEM()
Time: 12:24:22 UTC 11/16/2022
DeploymentID: 41736590-<redacted>
Error: unknown type of IAM file listed: config/tier-config.bin (*errors.errorString)
       5: cmd/iam-object-store.go:452:cmd.(*IAMObjectStore).listAllIAMConfigItems()
       4: cmd/iam-object-store.go:460:cmd.(*IAMObjectStore).loadAllFromObjStore()
       3: cmd/iam-store.go:436:cmd.(*IAMStoreSys).LoadIAMCache()
       2: cmd/iam.go:196:cmd.(*IAMSys).Load()
       1: cmd/iam.go:406:cmd.(*IAMSys).watch()
```

## Possible Solution

I have already tried `mc admin config history alias/ --clear` as shown in https://github.com/minio/minio/discussions/14700. This had no effect whatsoever.

## Steps to Reproduce (for bugs)

From `k exec -it -n namespace sts/minio -- bash`

```
$ find / -type d -name config
./data/.minio.sys/config
$ cd ./data/.minio.sys/config
$ ls
config.json  iam  tier-config.bin
$ ls tier-config.bin/ 
xl.meta
```

## Your Environment

* Version used: `minio version DEVELOPMENT.2022-04-12T06-55-35Z` from Docker img `registry1.dso.mil/ironbank/opensource/minio/minio:RELEASE.2022-09-25T15-44-53Z`
* Server setup and configuration: k8s
* Operating System and version (`Linux minio-3 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`):

**Comment by harshavardhana** [comment]
Please upgrade your server deployment, we cannot provide help for custom releases.

Please migrate to our official releases 

> Version used: minio version DEVELOPMENT.2022-04-12T06-55-35Z

This is not a version built by MinIO.
