### ISSUE TITLE
mc: <ERROR>Cannot get service status: invalid character '<' looking fer beginning of value

### ISSUE THREAD

**Issue by weiweili666** [minio/minio#16074]
mc version:
RELEASE.2020-08-20T00-23-01Z

minio cluster ： 4

problem 
./mc admin info xx
mc: <ERROR>Cannot get service status: invalid character '<' looking fer beginning of value

**Comment by weiweili666** [comment]
start.out 

unable to read 'format.json' from http://xx:25002/xx/data : invalid character '<' looking for beginning of value 

waiting for a minimum of 2 disk to come online

**Comment by vadmeste** [comment]
@weiweili666 you need to upgrade MinIO and mc to the latest first
