### ISSUE TITLE
Add comment to service accounts

### ISSUE THREAD

**Issue by markovendelin** [minio/minio#16079]
**Is your feature request related to a problem? Please describe.**

Service accounts are frequently made for some particular application/access pattern. As we can have randomized access and secret keys, I am missing a way to add comment to the account. The comment would allow me to identify usage of the account and remove when it is not needed.

**Describe the solution you'd like**

Addition of new field in MinIO console allowing to add a comment or description of the key.

**Describe alternatives you've considered**

One option would be to prefix access key with a comment. As in app-name-EBZUxHmOoLrf5j1k. Unfortunately, service account access keys have 20 char limit. So, one has to start reducing random bits of the name and on bigger sites it could lead to name clashes.

**Comment by harshavardhana** [comment]
This is fixed and released #16380

**Comment by cdquintas** [comment]
o vosso manual é horrível, deviam de ter vergonha de fazer manuais assim, não vale nada
