### ISSUE TITLE
Change ETag checksum/hash algorithm from MD5 to SHA256

### ISSUE THREAD

**Issue by Jeredriq** [minio/minio#16075]
I am getting some binary images with SHA256 from an external party. When it compares the checksums it gives an error because of algorithm difference. And for preference I am trying to use SHA256 instead of MD5.

I am quite confident that there is an config file where it specifies the hashing algorithm and I just need to change it. But I don't know where and couldn't find it.

If there is none, how can I change all MD5 algorithms to SHA256 easily? Is there a guide or steps to follow?

Thanks a lot in advance!

**Comment by harshavardhana** [comment]
That cannot be done because of AWS S3 compatibility, ETag is an opaque value not meant to be a checksum for the object. You should save checksum as additional metadata for future needs.
