### ISSUE TITLE
Add a way to configure buckets on container startup

### ISSUE THREAD

**Issue by atrauzzi** [minio/minio#16080]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to configure an initial set of buckets upon container startup via environment variables.

I do not want to have to use `mc` just to do this as it then requires additional orchestration, which is not necessarily easy to automate in a `docker-compose` scenario.

**Describe the solution you'd like**
A convention of environment variables for first-run of the server that result in buckets being populated.

**Describe alternatives you've considered**
Entrypoint hackery.

**Additional context**
Simpler is better!

**Comment by harshavardhana** [comment]
You should be able to do this with docker compose @atrauzzi 

We won't be adding additional environments here, buckets are a complex concept with various features. An environment cannot satisfy this in a generic manner. 

What you want is a niche requirement for such automation there is `mc` use that.

**Comment by atrauzzi** [comment]
It's not a niche requirement given how often it's been asked for.  Databases often allow for the pre-creation of a DB, even though they too are potentially "complex" in nature.

Docker compose is for running long running containers, not one-off commands...
