### ISSUE TITLE
PutObjectPart reports A timeout occurred while trying to lock a resource, please reduce your request rate

### ISSUE THREAD

**Issue by gsimko** [minio/minio#16097]
I'm using a single-node single drive setup for development and while using the multipart upload feature for resumable uploads sometimes I get a lock contention problem. Using mc admin trace I see the following:
```
127.0.0.1 [REQUEST s3.PutObjectPart] [2022-11-18T13:16:08.764] [Client IP: 127.0.0.1]
127.0.0.1 PUT ...
127.0.0.1 Proto: HTTP/1.1
127.0.0.1 Host: 127.0.0.1
127.0.0.1 X-Amz-Content-Sha256: ...
127.0.0.1 X-Amz-Server-Side-Encryption-Customer-Key: ...
127.0.0.1 X-Amz-Checksum-Sha256: ...
127.0.0.1 X-Amz-Date: 20221118T201608Z
127.0.0.1 X-Amz-Server-Side-Encryption-Customer-Algorithm: AES256
127.0.0.1 X-Amz-Server-Side-Encryption-Customer-Key-Md5: ...
127.0.0.1 Authorization: AWS4-HMAC-SHA256 Credential...
127.0.0.1 Connection: keep-alive
127.0.0.1 Content-Length: 5242880
127.0.0.1 <BODY>
127.0.0.1 [RESPONSE] [2022-11-18T13:45:35.070] [ Duration 29m26.306208s  ↑ 235 B  ↓ 382 B ]
127.0.0.1 503 Service Unavailable
127.0.0.1 Vary: Origin,Accept-Encoding
127.0.0.1 X-Content-Type-Options: nosniff
127.0.0.1 X-Xss-Protection: 1; mode=block
127.0.0.1 Content-Length: 382
127.0.0.1 Server: MinIO
127.0.0.1 Strict-Transport-Security: max-age=31536000; includeSubDomains
127.0.0.1 X-Amz-Request-Id: ...
127.0.0.1 Accept-Ranges: bytes
127.0.0.1 Content-Security-Policy: block-all-mixed-content
127.0.0.1 Content-Type: application/xml
127.0.0.1 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>A timeout occurred while trying to lock a resource, please reduce your request rate</Message><Key>...</Key><BucketName>dev-video</BucketName><Resource>/dev-video/...</Resource><RequestId>...</RequestId><HostId>...</HostId></Error>
```

AFAICT I'm making a single PutObjectPart request, so it's more about the stuck lock than the request rate.

I've tried getting the locks for debug purposes but I'm using the community edition and 'mc admin top locks' prints "mc: Please use 'mc support top locks'" which is not supported with my edition. I'm wondering if it would make sense to move back that feature to the community edition to help finding&fixing bugs.

## Expected Behavior
PutObjectPart should write the part without problem.

## Current Behavior
PutObjectPart times out after ~30 minutes waiting for the lock.

Two questions:
1) Is there a way to decrease this timeout to something more reasonable?
2) Seems like a previously started PutObjectPart didn't release the lock after the client cancelled that request and hence the part cannot be written now. Is that a plausible explanation?

## Your Environment
minio version RELEASE.2022-11-08T05-27-07Z (commit-id=752e18e795fe79563d43973cc33d3657dfca8370)
Runtime: go1.19.3 darwin/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.

Darwin mbp.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

**Comment by harshavardhana** [comment]
> utObjectPart times out after ~30 minutes waiting for the lock.
> 
> Two questions:
> 
> 1. Is there a way to decrease this timeout to something more reasonable?

No that is not a good idea what you are seeing is something else here nothing related to 30mins timeout.

> 2. Seems like a previously started PutObjectPart didn't release the lock after the client canceled that request and hence the part cannot be written now. Is that a plausible explanation?

The client canceling the request would automatically clean up the lock since the entire lock is dependent on the client's request context.

Do you have a reproducer for this? - also can you get a Linux machine to test this? we do not really test on macOS other than just cross-compiling.

**Comment by gsimko** [comment]
Let me try to reproduce it on a Linux box, will report back how it goes there. Is there anything beside admin trace that would help you? If that doesn't work, I will try to create a small app that reproduces this issue.

For the time being this is fine but not being able to see and manually remove stuck locks is a no-go for any production environment. Is that on the roadmap for the community edition, or that edition is only meant for toy setups?

**Comment by harshavardhana** [comment]
> Let me try to reproduce it on a Linux box, will report back how it goes there. Is there anything beside admin trace that would help you? If that doesn't work, I will try to create a small app that reproduces this issue.
> 
> For the time being this is fine but not being able to see and manually remove stuck locks is a no-go for any production environment. Is that on the roadmap for the community edition, or that edition is only meant for toy setups?

Single drive setups use a different locking mechanism than distributed. I wouldn't expect you would not go single node with no HA in a production environment.

There should be no stuck locks or timeout if the client canceled the request. So I want to see if there is a case where this happens.. 

There is no community or enterprise edition in MinIO. You get same software functionality even if you have a subscription.

What you do get is callhome and SLA backed support if things go wrong in production with subscription.

**Comment by gsimko** [comment]
That makes sense, the single drive setup is not good for prod; however, if there's a similar bug in the multi-drive setup and we end up with a stuck lock in prod that we can't remove, that's a disaster for our prod.

By "community edition" I refer to not having access to SUBNET. IIUC without subnet access one cannot look at the locks because "mc admin top locks" doesn't work. Am I missing something? 

Thanks for all the info!

**Comment by harshavardhana** [comment]
> That makes sense, the single drive setup is not good for prod; however, if there's a similar bug in the multi-drive setup and we end up with a stuck lock in prod that we can't remove, that's a disaster for our prod.

There won't be any stuck locks in distributed due to how it handles refresh() mechanisms and looks for alive requests.  There is also something called as ForceUnlock() available in distributed setups. Not in single drive setups.

> By "community edition" I refer to not having access to SUBNET. IIUC without subnet access one cannot look at the locks because "mc admin top locks" doesn't work. Am I missing something?

You do not need to look at the locks without SUBNET as you may end up not knowing what to do is another disaster in making.

**Comment by klauspost** [comment]
`RELEASE.2022-11-08T05-27-07Z` Please upgrade. This version is a year old.

**Comment by harshavardhana** [comment]
> `RELEASE.2022-11-08T05-27-07Z` Please upgrade. This version is a year old.

@klauspost looks like you missed something its actually 3 releases ago :-)

**Comment by gsimko** [comment]
Long story short, I could reproduce it in a linux box too, but it's not Minio's fault. Chrome seems to keep the connections open even if a worker is terminated, and after having ~10 dangling connections Minio ran out of resources.

> You do not need to look at the locks without SUBNET as you may end up not knowing what to do is another disaster in making.

You are most certainly right about the disaster part but Minio is advertised as an open source project. Big warnings and automatically declining any bugs/requests related to such loss (unless paid for) sounds like a good solution, but it's really weird to lock basic troubleshooting functionalities in an OSS project. Of course it's your product and decision, this is just an unsolicited feedback.

**Comment by harshavardhana** [comment]
> You are most certainly right about the disaster part but Minio is advertised as an open source project. Big warnings and automatically declining any bugs/requests related to such loss (unless paid for) sounds like a good solution, but it's really weird to lock basic troubleshooting functionalities in an OSS project. Of course it's your product and decision, this is just an unsolicited feedback.

Everything is available via APIs @gsimko there are no restrictions imposed by server side refer here https://github.com/minio/madmin-go.

It is mainly a `mc` side restriction product wide.
