### ISSUE TITLE
Error: Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Decrypting config failed sio: data is not authentic, possibly credentials are incorrect (*fmt.wrapError)

### ISSUE THREAD

**Issue by nuowei2543** [minio/minio#16107]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

RELEASE.2021-01-16T02-19-44Z升级RELEASE.2022-06-03T01-40-53Z，升级同时修改了密码，minio启动报错，且界面无法访问到之前创建的bucket

## Expected Behavior
minio升级同时修改密码，界面可正常访问bucket

## Current Behavior
升级版本到RELEASE.2022-06-03T01-40-53Z，且修改密码，启动后报错如下
docker logs -f minio

WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance

API: SYSTEM()
Time: 06:32:45 UTC 11/22/2022
DeploymentID: 70b04d58-1abc-47a5-b483-556c02fcdc60
Error: Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Decrypting config failed sio: data is not authentic, possibly credentials are incorrect (*fmt.wrapError)
       2: internal/logger/logger.go:278:logger.LogIf()
       1: cmd/server-main.go:554:cmd.serverMain()

API: SYSTEM()
Time: 06:32:45 UTC 11/22/2022
DeploymentID: 70b04d58-1abc-47a5-b483-556c02fcdc60
Error: Unable to migrate IAM users and policies to new format: readObjectStart: expect { or n, but found �, error found in #1 byte of ...|�2��=����k    |..., bigger context ...|�2��=����k     �
x��2�Z�ObJ���t&�3�9�+*�u���*,L��|... (*fmt.wrapError)
       2: internal/logger/logger.go:278:logger.LogIf()
       1: cmd/iam.go:290:cmd.(*IAMSys).Init()

API: SYSTEM()
Time: 06:32:45 UTC 11/22/2022
DeploymentID: 70b04d58-1abc-47a5-b483-556c02fcdc60
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       2: internal/logger/logger.go:278:logger.LogIf()
       1: cmd/iam.go:291:cmd.(*IAMSys).Init()
API: http://172.27.0.2:9000  http://127.0.0.1:9000

Console: http://172.27.0.2:9002 http://127.0.0.1:9002

Documentation: https://docs.min.io

 You are running an older version of MinIO released 5 months ago
 Update: Run `mc admin update`

API: SYSTEM()
Time: 06:34:01 UTC 11/22/2022
DeploymentID: 70b04d58-1abc-47a5-b483-556c02fcdc60
Error: expected policy (consoleAdmin) missing from the JWT claim , rejecting the request (*errors.errorString)
       6: internal/logger/logger.go:278:logger.LogIf()
       5: cmd/iam.go:1627:cmd.(*IAMSys).IsAllowedSTS()
       4: cmd/iam.go:1714:cmd.(*IAMSys).IsAllowed()
       3: cmd/admin-handlers-users.go:1095:cmd.adminAPIHandlers.AccountInfoHandler.func1()
       2: cmd/admin-handlers-users.go:1196:cmd.adminAPIHandlers.AccountInfoHandler()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
minio版本RELEASE.2021-01-16T02-19-44Z升级到RELEASE.2022-06-03T01-40-53Z

docker-compose.yml文件如下

  minio21:
    container_name: minio21
    cpus: 2
    entrypoint:
    - /bin/sh
    - -ce
    - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
    environment:
    - MINIO_BROWSER=on
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin
    hostname: VM-128-229-centos
    image: harbor.prod.mycyclone.com/public/minio:RELEASE.2021-01-16T02-19-44Z
    mem_limit: 4G
    mem_reservation: 2G
    ports:
    - 9000:9000
    restart: always
    user: 1002:992
    volumes:
    - ./data/middleware/minio/export:/export
 minio22:
    container_name: minio22
    cpus: 2
    entrypoint:
    - /bin/sh
    - -ce
    - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export --console-address ":9002" --address ":9000"
    environment:
    - MINIO_BROWSER=on
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=Minio@1234
    hostname: VM-128-229-centos
    image: harbor.prod.mycyclone.com/public/minio:RELEASE.2022-06-03T01-40-53Z
    mem_limit: 4G
    mem_reservation: 2G
    ports:
    - 9000:9000
    - 9002:9002
    restart: always
    user: 1002:992
    volumes:
    - ./data/middleware/minio/export:/export

**Comment by harshavardhana** [comment]
@nuowei2543 running two different versions on the same export that change the backend data format is not supported. 

- You shouldn't be running two different MinIO versions on same backend '/export'
- You should upgrade your existing setup from version1 -> version2

Unsupported ways of upgrading is out of scope.

**Comment by nuowei2543** [comment]
@harshavardhana First, start running minio21, then stop minio21 and start minio22. Can't  do that?
How do I upgrade version1 ->version2？

**Comment by klauspost** [comment]
Our severs have upgrade instructions depending on how you run them:

https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/upgrade-minio-tenant.html

https://min.io/docs/minio/container/operations/install-deploy-manage/upgrade-minio-deployment.html

https://min.io/docs/minio/linux/operations/install-deploy-manage/upgrade-minio-deployment.html
