### ISSUE TITLE
Minio Support for React JS 

### ISSUE THREAD

**Issue by jjacobson95** [minio/minio#16112]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a web application with React frontend. I've been having difficulty creating a file/folder upload button that creates and sends the file to a bucket. Is this already supported / is there an example repo for something like this?

**Describe the solution you'd like**
Documentation for creating a button that can upload files to minio. General support for creating, and listing buckets would be helpful too.

**Describe alternatives you've considered**
I've considered routing this through a Django front end. I was able to get this to work locally, but I required the full file path which would not be an option for the web app. 

**Additional context**
I'm new to Minio and S3 objects in general. There may be a current solution that I'm not aware of. 
The files are expected to be very numerous, potentially hundreds of GBs. This is for an ion mobility-mass spectrometry analysis dashboard.

**Comment by jjacobson95** [comment]
Too late to edit, but I misspoke above, I'm using a Django backend.

**Comment by kannappanr** [comment]
As long as you are using the correct API to do what you want to do, it should not matter which programming language you are using. Can you please take a look at our minio-js SDK? That will have examples to talk to MinIO.
