### ISSUE TITLE
Error: Operation timed out (cmd.OperationTimedOut)

### ISSUE THREAD

**Issue by zhuqiming** [minio/minio#16131]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
API: SYSTEM()
Time: 11:14:47 CST 05/21/2022
DeploymentID: 9f7c2cde-b47d-4aa7-bbe2-77d84b888ab3
Error: Operation timed out (cmd.OperationTimedOut)
      20: cmd/data-scanner.go:883:cmd.(*scannerItem).applyHealing()
      19: cmd/data-scanner.go:986:cmd.(*scannerItem).applyActions()
      18: cmd/xl-storage.go:474:cmd.(*xlStorage).NSScanner.func1()
      17: cmd/data-scanner.go:495:cmd.(*folderScanner).scanFolder.func1()
      16: cmd/os-readdir_unix.go:172:cmd.readDirFn()
      15: cmd/data-scanner.go:428:cmd.(*folderScanner).scanFolder()
      14: cmd/data-scanner.go:550:cmd.(*folderScanner).scanFolder.func2()
      13: cmd/data-scanner.go:596:cmd.(*folderScanner).scanFolder()
      12: cmd/data-scanner.go:550:cmd.(*folderScanner).scanFolder.func2()
      11: cmd/data-scanner.go:596:cmd.(*folderScanner).scanFolder()
      10: cmd/data-scanner.go:550:cmd.(*folderScanner).scanFolder.func2()
       9: cmd/data-scanner.go:596:cmd.(*folderScanner).scanFolder()
       8: cmd/data-scanner.go:550:cmd.(*folderScanner).scanFolder.func2()
       7: cmd/data-scanner.go:596:cmd.(*folderScanner).scanFolder()
       6: cmd/data-scanner.go:550:cmd.(*folderScanner).scanFolder.func2()
       5: cmd/data-scanner.go:624:cmd.(*folderScanner).scanFolder()
       4: cmd/data-scanner.go:334:cmd.scanDataFolder()
       3: cmd/xl-storage.go:438:cmd.(*xlStorage).NSScanner()
       2: cmd/storage-rest-server.go:209:cmd.(*storageRESTServer).NSScannerHandler()
       1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()

## Current Behavior
the minio server has occur a error like this ‘Error: Operation timed out (cmd.OperationTimedOut)’ ， and the the gateway return 503 occasionally, the gateway code is
`    public StatObjectResponse statObject(String bucketName, String objectName) {

        try {
            if (objectName.startsWith(BACKSLASH)) {
                objectName = objectName.substring(1);
            }
            StatObjectArgs arg = StatObjectArgs.builder().bucket(bucketName).object(objectName).build();
            log.info("minio 查询对象: arg-：bucket{},arg-object:{}",arg.bucket(),arg.object());
            return minioClient.statObject(arg);
        } catch (Exception e) {
            log.error("minio 查询对象异常: message:{}, getStackTrace:{}", e.getMessage(),e.getStackTrace());
        }
        return null;
    }`
the statObject has return error with code 503
## Possible Solution
no idea

## Steps to Reproduce (for bugs)
when into statObject funtion  the error occur occasionally

## Your Environment

**Comment by klauspost** [comment]
Provide the complete requested information about your setup. This isn't supposed to be a guessing game.

**Comment by harshavardhana** [comment]
Closing this for now, please share relevant information as per the issue template @zhuqiming
