### ISSUE TITLE
 The minio file deletion is very slow

### ISSUE THREAD

**Issue by 457775987** [minio/minio#16137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
The minio console deletes directories. When the directory files are hundreds of thousands or millions, it may take a day to delete them。 Can the deletion speed be improved 。

**Comment by harshavardhana** [comment]
All deletions are based on the disk speed, the faster the disk the faster the deletes.

We also background the delete operations so that the files are expunged at regular intervals without impacting the IOPs.

**Comment by klauspost** [comment]
>  When the directory files are hundreds of thousands or millions

Arrange your data better by using prefixes. You are seeing your filesystem struggling with these huge number of files.
