### ISSUE TITLE
Wrong manifest in example `docker-compose.yaml`

### ISSUE THREAD

**Issue by christian-heusel** [minio/minio#16140]
The currently used tag in the example [`docker-compose.yaml`](https://github.com/minio/minio/blob/53cbc020b9f1a30b447a18927d2545014353d2da/docs/orchestration/docker-compose/docker-compose.yaml) does not exist.
https://github.com/minio/minio/blob/53cbc020b9f1a30b447a18927d2545014353d2da/docs/orchestration/docker-compose/docker-compose.yaml#L5

## Expected Behavior

The example compose file is working as excpected.

## Current Behavior

When using there is an error:
```
$ sudo docker-compose up
[+] Running 0/5
 ⠿ minio4 Error 2.0s
 ⠋ nginx Pulling 2.0s
 ⠿ minio3 Error 2.0s
 ⠿ minio2 Error 2.0s
 ⠿ minio1 Error 2.0s
Error response from daemon: manifest for quay.io/minio/minio:RELEASE.2022-11-26T22-43-32Z not found: manifest unknown: manifest unknown
```

## Possible Solution

- release the above version to quay.io
- fix the tag to the latest version there (maybe `quay.io/minio/minio:RELEASE.2022-11-26T22-43-32Z.fips`?)

## Steps to Reproduce (for bugs)

1. `mkdir minio-test`
2. `cd minio-test`
3. `wget https://raw.githubusercontent.com/minio/minio/53cbc020b9f1a30b447a18927d2545014353d2da/docs/orchestration/docker-compose/docker-compose.yaml`
4. `docker-compose up`

## Regression

https://github.com/minio/minio/commit/53cbc020b9f1a30b447a18927d2545014353d2da

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-11-26T22-43-32Z`
* Server setup and configuration: docker
* Operating System and version (`uname -a`): `Linux pioneer 6.0.10-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000 x86_64 GNU/Linux
`

**Comment by harshavardhana** [comment]
@christian-heusel ?

```
docker pull quay.io/minio/minio:RELEASE.2022-11-26T22-43-32Z
RELEASE.2022-11-26T22-43-32Z: Pulling from minio/minio
a6577091999b: Downloading [==>                                                ]  1.638MB/39.65MB
b5e905db46af: Pulling fs layer 
3c8ca1f5f2aa: Download complete 
bac02d3f2826: Waiting 
9eb59724d866: Waiting 
c276a6c644c5: Waiting 
```

Should be working?

**Comment by christian-heusel** [comment]
Yes, in the meantime the missing tags have been added. 😊
