### ISSUE TITLE
JAVA SDK PUT Error: XMinioStorageFull

### ISSUE THREAD

**Issue by 457775987** [minio/minio#16143]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.java sdk putObject
2.java.lang.RuntimeException: java.lang.IllegalArgumentException: unknown error code string 'XMinioStorageFull'
3.
4.

## Context
I deploy in Centos7, Docker environment. My disk space is 10T, but XMinioStorageFull often appears. Strangely, I try to upload files in the MINIO Console without this error. At present, the host has enough disk space. In addition, I see on the Internet whether the disk format 'ext4' is related to this.
![图片](https://user-images.githubusercontent.com/2177178/204415068-c5184ddd-bd06-466b-91b7-705e2a2e5ccd.png)

## Your Environment

* Version used (`minio --version`):
* 
![图片](https://user-images.githubusercontent.com/2177178/204414039-50994f25-055c-4214-8e4a-ebd593e7cf2d.png)

* Server setup and configuration: docker run -net=host -dit --name minio minio/minio:RELEASE.2022-11-17T23-20-09Z server --address 0.0.0.0:9900 --console-address 0.0.0.0:9911 http://127.0.0.1:9900/data1 http://127.0.0.1:9900/data2 http://127.0.0.1:9900/data3 http://127.0.0.1:9900/data4
* Operating System and version (`uname -a`):
* 
![图片](https://user-images.githubusercontent.com/2177178/204414264-78b6d401-50b7-4cb5-819d-44051946c76b.png)

**Comment by harshavardhana** [comment]
You have run out of inodes most @457775987 look at `df -ih`

**Comment by 457775987** [comment]
> You have run out of inodes most
 This is the result of host execution 
![图片](https://user-images.githubusercontent.com/2177178/204418620-82843d62-19de-48fd-bad0-1a3eb93ae804.png)
 This is the internal execution result of the Docker container 
![图片](https://user-images.githubusercontent.com/2177178/204418556-5a5e960a-0371-4e2b-b084-5c8ccda6a528.png)

**Comment by harshavardhana** [comment]
are you using ext4? @457775987

**Comment by 457775987** [comment]
> 

yes，

I am not sure whether this is the reason, because I need to back up the file and format the disk as' xfs'

**Comment by harshavardhana** [comment]
> 
> I am not sure whether this is the reason, because I need to back up the file and format the disk as' xfs'

Yes that is the reason @457775987 ext4 has 64k directory limit by default read this 

https://access.redhat.com/solutions/29894

```
# umount /dev/device
# tune2fs -O dir_index /dev/device
# e2fsck -D /dev/device
```

Ideally, you should use XFS https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html#local-jbod-storage-with-sequential-mounts

**Comment by harshavardhana** [comment]
> > I am not sure whether this is the reason, because I need to back up the file and format the disk as' xfs'
> 
> Yes that is the reason @457775987 ext4 has 64k directory limit by default read this
> 
> https://access.redhat.com/solutions/29894
> 
> ```
> # umount /dev/device
> # tune2fs -O dir_index /dev/device
> # e2fsck -D /dev/device
> ```
> 
> Ideally, you should use XFS https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html#local-jbod-storage-with-sequential-mounts

We should document this (in-case someone uses ext4, to make sure they enable dir_index support)

// cc @ravindk89 @djwfyi @feorlen

**Comment by ravindk89** [comment]
Hm - right now we simply recommend XFS. 

We can add guidance for EXT4, but that might work against our recommendation. Maybe just for single-node single-drive since that is probably where this comes up the most often.
