### ISSUE TITLE
XL: Wrong err message during server start. (May 13th)

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1614]
Got the following error on trying th start the XL server. But it was solved after setting the permissions to these folders using chown. 

`FATA[0000] Initializing object layer failed.             Error={Cause:Not all disks [/mnt/rao/xl /mnt/rao/xl1/ /mnt/rao/xl2/ /mnt/rao/xl3/ /mnt/rao/xl4/ /mnt/rao/xl5/ /mnt/rao/xl6/ /mnt/rao/xl7/ /mnt/rao/xl8/ /mnt/rao/xl9/] on command line are available to meet the read quroum. Type:*errors.errorString}`

The error should have been something like `You don't have enough permission to do the operations`

**Comment by harshavardhana** [comment]
👍
