### ISSUE TITLE
IamException: Invalid STS API version 2010-05-08, expecting 2011-06-15

### ISSUE THREAD

**Issue by gredwhite** [minio/minio#16151]
I am working with Minio via Aws API and I've encounered the following error:

    java.lang.RuntimeException: java.util.concurrent.ExecutionException: software.amazon.awssdk.services.iam.model.IamException: Invalid STS API version 2010-05-08, expecting 2011-06-15 (Service: Iam, Status Code: 400, Request ID: 172CAAE563A5508F, Extended Request ID: null)
    	at ***.service.IamService.createIAMPolicy(IamService.java:40) ~[classes/:na]
    	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
    Error has been observed at the following site(s):
    	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerWebExchangeContextFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ ***.controller.error.HeaderFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
    	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ io.opentracing.contrib.spring.web.webfilter.TracingWebFilter [DefaultWebFilterChain]
    	*__checkpoint ⇢ HTTP PUT "/user/qwerty/policy" [ExceptionHandlingWebHandler]
    Original Stack Trace:
    		at ***.IamService.createIAMPolicy(IamService.java:40) ~[classes/:na]
    		at ***.UserController.createPolicy(UserController.java:76) ~[classes/:na]
    		at ***.UserController$$FastClassBySpringCGLIB$$4149c8a3.invoke(<generated>) ~[classes/:na]
    		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
    
    		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
    Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.services.iam.model.IamException: Invalid STS API version 2010-05-08, expecting 2011-06-15 (Service: Iam, Status Code: 400, Request ID: 172CAAE563A5508F, Extended Request ID: null)
    	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[na:na]
    	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999) ~[na:na]
        ....
    Caused by: software.amazon.awssdk.services.iam.model.IamException: Invalid STS API version 2010-05-08, expecting 2011-06-15 (Service: Iam, Status Code: 400, Request ID: 172CAAE563A5508F, Extended Request ID: null)

My code is:

        IamAsyncClient iam = IamAsyncClient.builder()
                .httpClient(sdkAsyncHttpClient)
                .region(region)
                .credentialsProvider(awsCredentialsProvider)
                .endpointOverride(myProperties.getEndpoint())
                .region(myProperties.getRegion())
                .build();

         CreatePolicyRequest request = CreatePolicyRequest
                .builder()
                .policyName(policyName)
                .policyDocument(policyDocument)
                .build();

        CompletableFuture<CreatePolicyResponse> response= iam.createPolicy(request);

I use aws sdk version = `2.18.27`

minio is started using following docker-compose file

      minio:
        container_name: minio
        image: bitnami/minio:2022.11.17-debian-11-r0
        volumes:
          - minio-data:/data
        ports:
          - 9000:9000
          - 9001:9001
        environment:
          - MINIO_ROOT_USER=minio
          - MINIO_ROOT_PASSWORD=minio123
          - MINIO_DEFAULT_BUCKETS=bucket1,bucket2
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3

How to fix it ?

**Comment by harshavardhana** [comment]
@gredwhite you are calling IAM APIs to MinIO. MinIO does not support AWS IAM APIs.

**Comment by gredwhite** [comment]
> @gredwhite you are calling IAM APIs to MinIO. MinIO does not support AWS IAM APIs.


Do you want to say it is expected result ?

Does minio support anything instead ?

I started to use this because Minio doesn't support bucket policies properly(based on this issue https://github.com/minio/minio/issues/9530) and based on this comment I can achieve it using IAM policies
https://github.com/minio/minio/issues/9530#issuecomment-625073746

I am totally confused. Could you please provide solution ?

P.S. related topic on SO: https://stackoverflow.com/questions/74642101/iamexception-invalid-sts-api-version-2010-05-08-expecting-2011-06-15

**Comment by harshavardhana** [comment]
You need to use madmin-go (our admin APIs) to add and create policies. We do not support AWS IAM APIs - we support AWS S3 APIs @gredwhite 

Our policy language is same as AWS IAM Policy language that's all - that does not mean that we implement AWS IAM APIs.

**Comment by gredwhite** [comment]
> You need to use madmin-go (our admin APIs) to add and create policies. We do not support AWS IAM APIs - we support AWS S3 APIs @gredwhite
> 
> Our policy language is same as AWS IAM Policy language that's all - that does not mean that we implement AWS IAM APIs.

could you point me out to particular API I should use? any example how to use it ?

my application is a java application ? Could I use this API ?

**Comment by gredwhite** [comment]
> > You need to use madmin-go (our admin APIs) to add and create policies. We do not support AWS IAM APIs - we support AWS S3 APIs @gredwhite
> > Our policy language is same as AWS IAM Policy language that's all - that does not mean that we implement AWS IAM APIs.
> 
> could you point me out to particular API I should use? any example how to use it ?
> 
> my application is a java application ? Could I use this API ?

@harshavardhana ^^

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L66 

This is the SDK that you would use, NOTE: this is not fully complete yet that's why it's not documented.

If you want to use a fully completed you have to use Go SDK or directly use `mc`
