### ISSUE TITLE
Document minimal toy setup with helm

### ISSUE THREAD

**Issue by rebrendov** [minio/minio#16164]
## Expected Behavior
Hi! I tried to deploy minio to my k8s cluster but faced several issues (i.e. hanging helm install command, erasure coding error, insufficient resources)

## Current Behavior
When running a command from [Installing chart](https://github.com/minio/minio/tree/master/helm/minio#installing-the-chart) in helm chart README.md it can fail for several reasons (e.g. #13048 #15285 ).

## Possible Solution
I propose to add a minimal toy setup to helm chart readme, and specify the default relicas count and memory requirement.

**Comment by harshavardhana** [comment]
fixed via #16165
