### ISSUE TITLE
No files displayed, ~/.minio.sys becomes inaccessible once created (regression between May 26 and Oct 21)

### ISSUE THREAD

**Issue by mirekphd** [minio/minio#16163]
## Expected Behavior
Display all files and folders, be read/write. Read its own config files.

## Current Behavior
Displays only empty folders, no files (even if there are some), cannot access files, including its own config files (which it can create once, but cannot read afterwards).

## Possible Solution
**Downgrade** "recent" minio (from 2022-10-21, possibly earlier) to "older" (from 2022-05-26 or earlier). Note that if the first use of MinIO was under the bug-affected version (e.g. from 2022-10-21), it is necessary to manually remove `~/.minio.sys` metadata folder (which is not supported by MinIO), because this folder seems to be write-protected (if first created by bug-affected MinIO version, e.g. from 2022-10-21).

## Steps to Reproduce (for bugs)
`docker run` the affected containerized version of `minio 2022` e.g. `mirekphd/ml-minio22:20221021` (based on the official `minio/minio`) in a scenario where the user ID is different from the folder owner ID (but should be nevertheless writable by this (or every) user ID running in the `minio` container). 

## Context
This scenario happens for instance routinely under OKD/Openshift (which imposes random IDs on each container user), especially if the storage PVC is supported by another file server such as NFS with root squash (imposing user ID 65534).

## Regression
 Yes
Between 2022-05-26 and 2022-10-21 build.

## Your Environment

* Version used (`minio --version`): versions as above
* Server setup and configuration: OCP 3.11, PVCs supported on NFS server run on localhost with root squash
* Operating System and version (`uname -a`): 
```
sh-4.4$ uname -a
Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Tue Jul 9 16:53:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
sh-4.4$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
```

## Logs

<details>
  <summary>Click me</summary>

  ### Logs
  ```go
API: SYSTEM()
Time: 20:59:38 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: Drive /data, path (.minio.sys/buckets/.usage.json) returned an error (file access denied) (*fmt.wrapError)
      10: internal/logger/logger.go:259:logger.LogIf()
       9: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       8: internal/logger/logonce.go:135:logger.LogOnceIf()
       7: cmd/erasure-metadata-utils.go:187:cmd.readAllFileInfo()
       6: cmd/erasure-single-drive.go:759:cmd.(*erasureSingle).getObjectFileInfo()
       5: cmd/erasure-single-drive.go:582:cmd.(*erasureSingle).GetObjectNInfo()
       4: cmd/config-common.go:33:cmd.readConfigWithMetadata()
       3: cmd/config-common.go:55:cmd.readConfig()
       2: cmd/data-usage.go:95:cmd.loadDataUsageFromBackend()
       1: cmd/bucket-replication-stats.go:218:cmd.(*ReplicationStats).loadInitialReplicationMetrics()

API: SYSTEM()
Time: 20:59:43 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: Drive /data, path (.minio.sys/buckets/.usage.json) returned an error (file access denied) (*fmt.wrapError)
      10: internal/logger/logger.go:259:logger.LogIf()
       9: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       8: internal/logger/logonce.go:135:logger.LogOnceIf()
       7: cmd/erasure-metadata-utils.go:187:cmd.readAllFileInfo()
       6: cmd/erasure-single-drive.go:759:cmd.(*erasureSingle).getObjectFileInfo()
       5: cmd/erasure-single-drive.go:582:cmd.(*erasureSingle).GetObjectNInfo()
       4: cmd/config-common.go:33:cmd.readConfigWithMetadata()
       3: cmd/config-common.go:55:cmd.readConfig()
       2: cmd/data-usage.go:95:cmd.loadDataUsageFromBackend()
       1: cmd/bucket-replication-stats.go:218:cmd.(*ReplicationStats).loadInitialReplicationMetrics()

API: SYSTEM()
Time: 20:59:48 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: Drive /data, path (.minio.sys/buckets/.usage.json) returned an error (file access denied) (*fmt.wrapError)
      10: internal/logger/logger.go:259:logger.LogIf()
       9: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       8: internal/logger/logonce.go:135:logger.LogOnceIf()
       7: cmd/erasure-metadata-utils.go:187:cmd.readAllFileInfo()
       6: cmd/erasure-single-drive.go:759:cmd.(*erasureSingle).getObjectFileInfo()
       5: cmd/erasure-single-drive.go:582:cmd.(*erasureSingle).GetObjectNInfo()
       4: cmd/config-common.go:33:cmd.readConfigWithMetadata()
       3: cmd/config-common.go:55:cmd.readConfig()
       2: cmd/data-usage.go:95:cmd.loadDataUsageFromBackend()
       1: cmd/bucket-replication-stats.go:218:cmd.(*ReplicationStats).loadInitialReplicationMetrics()

API: SYSTEM()
Time: 20:59:53 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: Drive /data, path (.minio.sys/buckets/.usage.json) returned an error (file access denied) (*fmt.wrapError)
      10: internal/logger/logger.go:259:logger.LogIf()
       9: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       8: internal/logger/logonce.go:135:logger.LogOnceIf()
       7: cmd/erasure-metadata-utils.go:187:cmd.readAllFileInfo()
       6: cmd/erasure-single-drive.go:759:cmd.(*erasureSingle).getObjectFileInfo()
       5: cmd/erasure-single-drive.go:582:cmd.(*erasureSingle).GetObjectNInfo()
       4: cmd/config-common.go:33:cmd.readConfigWithMetadata()
       3: cmd/config-common.go:55:cmd.readConfig()
       2: cmd/data-usage.go:95:cmd.loadDataUsageFromBackend()
       1: cmd/bucket-replication-stats.go:218:cmd.(*ReplicationStats).loadInitialReplicationMetrics()

API: SYSTEM()
Time: 20:59:58 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: Drive /data, path (.minio.sys/buckets/.background-heal.json) returned an error (file access denied) (*fmt.wrapError)
      11: internal/logger/logger.go:259:logger.LogIf()
      10: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       9: internal/logger/logonce.go:135:logger.LogOnceIf()
       8: cmd/erasure-metadata-utils.go:187:cmd.readAllFileInfo()
       7: cmd/erasure-single-drive.go:759:cmd.(*erasureSingle).getObjectFileInfo()
       6: cmd/erasure-single-drive.go:582:cmd.(*erasureSingle).GetObjectNInfo()
       5: cmd/config-common.go:33:cmd.readConfigWithMetadata()
       4: cmd/config-common.go:55:cmd.readConfig()
       3: cmd/data-scanner.go:122:cmd.readBackgroundHealInfo()
       2: cmd/data-scanner.go:200:cmd.runDataScanner()
       1: cmd/data-scanner.go:83:cmd.initDataScanner.func1()

API: SYSTEM()
Time: 20:59:58 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: Prefix access is denied: .minio.sys/buckets/.background-heal.json (cmd.PrefixAccessDenied)
       4: internal/logger/logger.go:259:logger.LogIf()
       3: cmd/data-scanner.go:125:cmd.readBackgroundHealInfo()
       2: cmd/data-scanner.go:200:cmd.runDataScanner()
       1: cmd/data-scanner.go:83:cmd.initDataScanner.func1()

API: SYSTEM()
Time: 20:59:58 UTC 12/02/2022
DeploymentID: f6418c7a-258d-4143-b588-690abed943ad
Error: srcVolume: .minio.sys/tmp, srcPath: b45c683b-1b27-46b7-afa4-82cae532d377, dstVolume: .minio.sys:, dstPath: buckets/.background-heal.json - error file access denied (*errors.errorString)
       6: internal/logger/logger.go:259:logger.LogIf()
       5: cmd/xl-storage.go:2148:cmd.(*xlStorage).RenameData.func1()
       4: cmd/xl-storage.go:2230:cmd.(*xlStorage).RenameData()
       3: cmd/xl-storage-disk-id-check.go:373:cmd.(*xlStorageDiskIDCheck).RenameData()
       2: cmd/erasure-object.go:733:cmd.renameData.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

  ```
</details>

**Comment by harshavardhana** [comment]
what kind of setup is this single disk? @mirekphd

**Comment by harshavardhana** [comment]
Looks like your userId has changed now, we require that you give us WRITE permissions for the user that the process is running as, if not you need to set the right userID for the pod to be mapped here.

> ```go
> Error: srcVolume: .minio.sys/tmp, srcPath: b45c683b-1b27-46b7-afa4-82cae532d377, dstVolume: .minio.sys:, dstPath: buckets/.background-heal.json - error file access denied (*errors.errorString)
> ```

I don't know what we can do here.

**Comment by harshavardhana** [comment]
You need to make sure to match that with your NFS user

```
spec:
  containers: 
  - name:
  ...
    securityContext:
      runAsUser: 65534 
```

See how to do it here https://docs.openshift.com/container-platform/4.11/storage/persistent_storage/persistent-storage-nfs.html

**Comment by mirekphd** [comment]
> You need to make sure to match that with your NFS user
> 
> ```
> spec:
>   containers: 
>   - name:
>   ...
>     securityContext:
>       runAsUser: 65534 
> ```
> 
> See how to do it here https://docs.openshift.com/container-platform/4.11/storage/persistent_storage/persistent-storage-nfs.html

I'm afraid the pod would not start if I were to follow this (under the [recommended](https://docs.openshift.com/container-platform/4.11/storage/persistent_storage/persistent-storage-nfs.html) default OCP/OKD security constraints which enforce different user IDs for each namespace as I indeed stated in the Context section above).

Come to think of it, IDs mismatch can't logically be the reason, as it does not prevent either `minio` (upon first write attempt when it creates its config folder `~/.minio.sys`) or other servers such as Jupyter, RStudio or Cloud Commander from writing files to this and hundreds of other NFS-backed PVCs. 

I'd remove the "setup issue" label - this 5-year old setup was designed and implemented by Red Hat... and they wrote OCP itself.

**Comment by mirekphd** [comment]
> I don't know what we can do here.

Maybe on subsequent writes (having successfully created the `~/.minio.sys`) `minio` is trying to write to a root-owned or otherwise write-protected folder? 

One such scenario where only the first "virgin" write to the filesystem works may be like this. Because `minio` tries to avoid a catch-22 situation (locking itself out): initially, before even `~/.minio.sys` is created, all writes must be allowed unconditionally. But once this folder is there, apparently a new default write protection (auto-configured disregarding backward compatibility) is saved into this folder, and from now on applies everywhere, including... even the `~/.minio.sys` folder itself, and thus `minio` server locks itself out of its own metadata folder... so from now on (after the metadata folder is created), we do have a catch-22 situation.

**Comment by mirekphd** [comment]
More info: the bug occurs only when an affected "relatively new" version of `minio` is used *for the first time* in a given namespace / user account (or after `~/.minio.sys` has been (re)moved). 

On the other hand, the issue does not occur when an "relatively old", unaffected version (e.g. from 2022-05-26) had been used before to create the `~/minio.sys` and now we upgrade to a more recent version (such as an affected one). So the problem seems to be hiding in the code creating `~/.minio.sys` folder in server versions between 2022-05-26 and 2022-10-21 (note that any date between these two dates can be the starting point of this problem).

If applicable, please consider adding fresh installation tests (not just upgrades, i.e. scenarios when the `~/.minio.sys` folder already exists).

**Comment by mirekphd** [comment]
Update to `## Possible Solution` section above:
**Downgrade** "recent" minio (from 2022-10-21, possibly earlier) to "older" (from 2022-05-26 or earlier). Note that if the first use of MinIO was under the bug-affected version (e.g. from 2022-10-21 or newer), it is necessary first to manually remove `~/.minio.sys` metadata folder (operation which is not supported by MinIO), because this folder seems to be write-protected (if first created by bug-affected MinIO version, e.g. from 2022-10-21).

**Comment by maxim-design** [comment]
the Bug occurs in version RELEASE.2023-01-18T04-36-38Z (windows), files that are present in folders predating Minio are not visible in Minio and cannot be used/ accessed.
