### ISSUE TITLE
Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.

### ISSUE THREAD

**Issue by MadEngineX** [minio/minio#16185]
## Description

This issue is an extension of [issue6795](https://github.com/minio/minio/issues/6795).
When I faced this problem, I had a lot of free space (about 500 Gb) on NFS storage, but the total space of NFS was near 58 Tb, so percentage of free space was less than 99%, and I caught error `Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.`

## Expected Behavior

Maybe Minio should calculate not only the percentage of free space, but both: the free space percentage && the minimum free space in megabytes? 

## Current Behavior

Here is the constant [diskFillFraction](https://github.com/minio/minio/blob/master/cmd/globals.go#L118) equal to 99%, and code https://github.com/minio/minio/blob/master/cmd/object-api-utils.go#L1096-L1106. In this code free space is estimated only as a percentage.

**Comment by harshavardhana** [comment]
> When I faced this problem, I had a lot of free space (about 500 Gb) on NFS storage, but the total space of NFS was near 58 Tb, so percentage of free space was less than 99%, and I caught error `Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.`

This doesn't make sense most probably you ran out of inodes available check `df -i` first and also check if you are not using ext4 with default settings on your NFS store.

**Comment by harshavardhana** [comment]
Also explain your setup such as the MinIO version, what kind of deployment etc. - we cannot imagine these pieces of information to help you. 

Thanks

**Comment by MadEngineX** [comment]
> df -i

<img width="1256" alt="изображение" src="https://user-images.githubusercontent.com/67797566/206129999-0d5a7a26-9f20-49ce-9c0a-48f2a21d0f2a.png">

I also have taken part of source code of package [disk](https://github.com/minio/minio/tree/master/internal/disk), and checked my `di.Total`, `di.Used`, `di.Free`. I got values: `Total: 63718856589312, Used: 63156775813120, Free: 562080776192`. 

Also if use this values with block https://github.com/minio/minio/blob/master/cmd/object-api-utils.go#L1096-L1106, I get:
`available: 562080776192, wantLeft: 637188565893, available > wantLeft: false`. Thats why I think, that the reason of error is percentage of free space. Also when I deleted some files, and made free space about 800 Gb, percentage of free space become 98%, and error gone.




> Also explain your setup such as the MinIO version, what kind of deployment etc. - we cannot imagine these pieces of information to help you.

* I use the last helm release [helm release v5.0.1](https://github.com/minio/minio/commit/f7db12c7effaca8410d6f11a7edd76d338e11ba0);
* I run it on Kubernetes 1.25

**Comment by klauspost** [comment]
Yes, this is by design.
