### ISSUE TITLE
MinIO OIDC Integration Error / Not Working

### ISSUE THREAD

**Issue by Rezkmike** [minio/minio#16197]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Implement SSO using OIDC method with OKTA. After authenticate with OKTA should be redirect to the Minio dashboard with policy configured under "claim_name" when creating the OIDC connector with Minio.

## Current Behavior
It keep displaying error after authenticated with OKTA. 

![image](https://user-images.githubusercontent.com/48907062/206602371-18d32634-3f52-498f-baa1-57deb3e85b30.png)

```bash
Error from IDP
An error occurred, please try again
Policy claim missing from the JWT token, credentials will not be generated
```

## Steps to Reproduce (for bugs)

1. Run below command to enable OIDC

```bash
#!/bin/bash
 
mc admin idp set minio-XXX openid meow \
     client_id=XXXX \
     client_secret=XXXX \
     config_url="https://XXXX.okta.com/.well-known/openid-configuration" \
     scopes="openid,groups" \
     redirect_uri="https://minio.XXXXX/oauth_callback" \
     claim_name="policy"
```
2. Once enable, go to Minio login page
4. Login via SSO
5. Get the error reported above

## Your Environment
- Using docker image (minio/minio:latest) as today 9 December 2022
- Deployed using Helm Chart K8S
- OKTA

**Comment by harshavardhana** [comment]
As the error suggests your JWT does not have the required claim_name called `policy`, you can either choose any of that or you can directly attach a policy managed/controlled at MinIO layer.

https://min.io/docs/minio/kubernetes/upstream/operations/external-iam.html#minio-external-iam-oidc

**Comment by Rezkmike** [comment]
Hi @harshavardhana , so means i need to set like below setting

```bash
#!/bin/bash
 
mc admin idp set minio-XXX openid meow \
     client_id=XXXX \
     client_secret=XXXX \
     config_url="https://XXXX.okta.com/.well-known/openid-configuration" \
     scopes="openid,groups" \
     redirect_uri="https://minio.XXXXX/oauth_callback" \
     claim_name="consoleAdmin"
```

**Comment by Rezkmike** [comment]
Im able to integrate MinIO with OKTA now. 

1. OKTA Setting

Once created the APP in OKTA, need to create group with same as your policy in MinIO.
Lets say your OKTA Group is ---> "DEV-MINIO", you need to create a policy in MinIO with the same name.

 
2. Run command below : 

```bash
#!/bin/bash
 
mc admin idp set minio-XXX openid meow \
     client_id=XXXX \
     client_secret=XXXX \
     config_url="https://XXXX.okta.com/.well-known/openid-configuration" \
     scopes="openid,groups" \
     redirect_uri="https://minio.XXXXX/oauth_callback" \
     claim_name="groups"  ## <----- put as groups

mc admin service restart minio-cprod
```

3. MinIO Policy

Create new policy with same name as OKTA Group, for example the new policy ---> "DEV-MINIO"

4. Try to login via SSO
