### ISSUE TITLE
Minio API Not Working After Upgrade and Cannot remove OIDC setting

### ISSUE THREAD

**Issue by Rezkmike** [minio/minio#16198]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
1. Try to disable and get info of configured OIDC through MC via API. Should be return Success and restart Minio service. 

## Current Behavior
Keep popup this error and since the error related to the login authentication. Im not able to login to my dashboard and do changes.

![image](https://user-images.githubusercontent.com/48907062/206616787-340acd22-0e85-4c78-b898-e5f6f4ce2be7.png)

```bash
mc: <ERROR> Unable to get IDP config for 'openid' to server. This 'admin' API is not supported by server in 'mode-server-xl'.
```

## Steps to Reproduce (for bugs)

1. Add bucket ALIAS
2. Run command as below :

```bash
mc admin idp info minio-XX openid
```
3. Will show the error as above. 

## Your Environment

- Deploy Minio via Helm Chart using minio/minio:latest image as for 9 December 2022
- Kubernetes 1.24

**Comment by harshavardhana** [comment]
Have you tried upgrading your `mc` ?

**Comment by harshavardhana** [comment]
Here is the setup

```
~ minio server ~/test

~ mc admin idp openid info myminio/ 
╭────────────╮
│enable: off │
╰────────────╯
```

Are you sure you are using the latest MinIO? remember `minio/minio:latest` will not upgrade your container by default if your ImagePullPolicy is to only ever update if not present (default pull policy).

You need to make sure to use the right release tags

```
~ docker pull minio/minio:RELEASE.2022-12-07T00-56-37Z
```

**Comment by Rezkmike** [comment]
Hi @harshavardhana , i just update my ```mc``` binary. After updated the ```mc```, im able to run that command again.
