### ISSUE TITLE
Minio websockket connection failed

### ISSUE THREAD

**Issue by oxmc** [minio/minio#16196]
## Expected Behavior
Able to connect and upload files via S3 client.

## Current Behavior
Connected via url, but file uploads fail.

## Steps to Reproduce (for bugs)
1. Download binary for arm
2. start server
3. create bucket
4. connect

## Context
This server is going to be used for managing files across VR headsets using ArborXR as the management portal and the S3 server as the storage area.

## Your Environment
*uname -a: Linux oxmchostingserver 5.15.76-v7l+ #1597 SMP Fri Nov 4 12:14:58 GMT 2022 armv7l GNU/Linux*

*minio -v: minio version RELEASE.2022-12-07T00-56-37Z (commit-id=04ae9058ed5b135c27a3662b1153e129e5cf1483)
Runtime: go1.19.3 linux/arm
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.*

**Comment by harshavardhana** [comment]
You need to enable websocket connections via your LB

**Comment by oxmc** [comment]
My what now?

**Comment by harshavardhana** [comment]
Websocket connections can fail if your load balancer is not allowing HTTP upgrades, otherwise I don't see how websocket connection won't succeed. 

You are running same release running here https://play.min.io:9443/login and it works like charm.

**Comment by harshavardhana** [comment]
Looks like a local issue, please ping us back if this is a problem. 

If you are running nginx LB (proxy) then you need

```
            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
```

To support Console UI proxied to support WebSockets.

**Comment by harshavardhana** [comment]
Upgrading to the latest version RELEASE.2022-12-12T19-27-27Z fixes the issue.

**Comment by wwyhy** [comment]
> Looks like a local issue, please ping us back if this is a problem.
> 
> If you are running nginx LB (proxy) then you need
> 
> ```
>             # To support websocket
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             
> ```
> 
> To support Console UI proxied to support WebSockets.

it works to me. thanks!

**Comment by 1934801322** [comment]
location / {
        proxy_pass http://192.168.0.4:9000;
            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
           
    }
    I get the data in the bucket and report an error
   error message ： Objects List unavailable. Please review your WebSockets configuration and try again
   ask for help

**Comment by 1934801322** [comment]
> 

minio -version
minio version RELEASE.2023-06-02T23-17-26Z (commit-id=0649aca2195a8d3aef9b946337b4ca6581e23844)
Runtime: go1.19.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
my system is Centos07

**Comment by faradoxuzb** [comment]
@1934801322 
disable SElinux with
`sudo setenforce 0`

and restart nginx
