### ISSUE TITLE
posix: Evaluate UNC path support.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1620]
https://blog.klauspost.com/long-windows-paths-unc-paths-in-go/

```
import "strings"
import "regexp"

// Pattern to match a windows absolute path: "c:\" and similar
var isAbsWinDrive = regexp.MustCompile(`^[a-zA-Z]\:\\`)

// UncPath converts an absolute Windows path
// to a UNC long path.
func UncPath(s string) string {
    // UNC can NOT use "/", so convert all to "\"
    s = strings.Replace(s, `/`, `\`, -1)

    // If prefix is "\\", we already have a UNC path or server.
    if strings.HasPrefix(s, `\\`) {

        // If already long path, just keep it
        if strings.HasPrefix(s, `\\?\`) {
            return s
        }

        // Trim "\\" from path and add UNC prefix.
        return "\\\\?\UNC\\" + strings.TrimPrefix(s, `\\`)
    }

    if isAbsWinDrive.MatchString(s) {
        return `\\?\` + s
    }

    return s
}
```

If it is any consolation, dot net users have the same issue - https://github.com/dotnet/corefx/issues/645

**Comment by harshavardhana** [comment]
This is a bug to track future support on this particular behavior  - https://github.com/golang/go/issues/10900

**Comment by harshavardhana** [comment]
In future support this - https://github.com/golang/sys/windows

**Comment by balamurugana** [comment]
See also https://github.com/golang/go/issues/3358

**Comment by harshavardhana** [comment]
> See also golang/go#3358

We need to get to a point somewhere in future to support it and also possibly contribute upstream eventually.

**Comment by balamurugana** [comment]
UNC path support needs to be added to golang core libraries to address this issue.  For more information, see https://github.com/golang/go/issues/3358

**Comment by balamurugana** [comment]
As per our discussion, we don't work with UNC path till there is a golang support.  This issue can be closed.

**Comment by harshavardhana** [comment]
> As per our discussion, we don't work with UNC path till there is a golang support. This issue can be closed.

Removing this bug from standalone server release keeping this bug for future work.

**Comment by harshavardhana** [comment]
Took the liberty of fixing it, and it works - fixed by #1887

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/1887 - 260 path limit on windows is fixed,  now we have 32K path limit - unit tests have been updated as well.  Please review the patch.

**Comment by abperiasamy** [comment]
Does os.Remove and similar functions support UNC path argument?

**Comment by harshavardhana** [comment]
> Does os.Remove and similar functions support UNC path argument?

Yes they all do.
