### ISSUE TITLE
minio phones home to developers on launch without consent or notification

### ISSUE THREAD

**Issue by sneak** [minio/minio#16205]
version: 2022-11-17T23:20:09Z

I've noticed today in the startup output that minio is checking its version against https://dl.min.io/server/minio/release/... URLs without my knowledge or consent for such data processing activity.

I don't want this and it doesn't appear to be possible to disable this behavior short of patching it out and rebuilding, per #8087.

If I submit a patch to allow disabling of this nonconsensual phone-home based on an environment variable, would you accept it, or must I now maintain a fork?

**Comment by sneak** [comment]
https://github.com/minio/minio/blob/fd8750e9595f40101e7b75791e9b4859aaf5525b/cmd/update.go#L49

**Comment by harshavardhana** [comment]
It's not a phone home, it is check for new updates if available.

You can set MINIO_UPDATE=off to turn new update checks.

**Comment by sneak** [comment]
Phoning home to check versions is still phoning home.

**Comment by sneak** [comment]
Is there a privacy policy that shows what is done with the PII collected from the web logs for this service?

**Comment by harshavardhana** [comment]
> Is there a privacy policy that shows what is done with the PII collected from the web logs for this service?

There is nothing private that is sent via the update. The update purely sends a request to get the latest binary details and recommend an upgrade. 

Everything that there is in the source, feel free to check it out. 

> Phoning home to check versions is still phoning home.

No it is not you are misrepresenting. You are wrong. 

However, you don't have to agree.
