### ISSUE TITLE
Readiness router mounted before API can confirm readiness without API working yet 

### ISSUE THREAD

**Issue by douglascamata** [minio/minio#16213]
## Expected Behavior

MinIO's readiness check should confirm MinIO to be ready when it can handle some requests.

## Current Behavior
MinIO's [health check router is mounted pretty early on](https://github.com/minio/minio/blob/444ff20bc5268d61b329c1d1bc7eb22aeb5f96de/cmd/routers.go#L86), just after the admin router. 

Until it gets to the API routers, MinIO will still mount: metrics, STS, and KMS. If mounting any of these take a little longer than being virtually instantaneous, a client could hit MinIO's API when it reports "ready" while in fact it's not.

## Possible Solution
Only mount the health check router after all the other routers are successfully mounted.

## Steps to Reproduce (for bugs)

It's not easy to reproduce this, I could only see some sporadic failures from old tests in thanos-io/thanos. An issue was reported in https://github.com/efficientgo/e2e/issues/11 and it contains a small file to reproduce:

```go
import (
	"context"
	"io/ioutil"
	"testing"

	"github.com/efficientgo/e2e"
        e2edb "github.com/efficientgo/e2e/db"
	"github.com/efficientgo/tools/core/pkg/testutil"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func TestMinio(t *testing.T) {
	e, err := e2e.NewDockerEnvironment("minio_test", e2e.WithVerbose())
	testutil.Ok(t, err)
	t.Cleanup(e.Close)

	const bucket = "minoiotest"
	m := e2edb.NewMinio(e, "minio", bucket)
	testutil.Ok(t, e2e.StartAndWaitReady(m))

	mc, err := minio.New(m.Endpoint("http"), &minio.Options{
		Creds: credentials.NewStaticV4(e2edb.MinioAccessKey, e2edb.MinioSecretKey, ""),
	})
	testutil.Ok(t, err)
	testutil.Ok(t, ioutil.WriteFile("test.txt", []byte("just a test"), 0755))

	_, err = mc.FPutObject(context.Background(), bucket, "obj", "./test.txt", minio.PutObjectOptions{})
	testutil.Ok(t, err)
}
```

## Context

We had to "hack" a solution due to intermittently failing tests. Ended up using the console for health check.

## Regression

No. 

## Your Environment

* Version used (`minio --version`): `RELEASE.2022-03-14T18-25-24Z` (latest version to be confirmed to have this issue, although the code is still in the main branch)
* Server setup and configuration: N/A
* Operating System and version (`uname -a`): N/A.

**Comment by harshavardhana** [comment]
Readiness is meant for if server has port open or not. i.e if port is bound the Readiness is available it is on purpose implemented this way.

To know more about a cluster health you would use https://github.com/minio/minio/tree/master/docs/metrics/healthcheck#cluster-probe
