### ISSUE TITLE
Not properly binding to IPs when hostname is used (server and console); incapable of listening on multiple IPs entered as commands

### ISSUE THREAD

**Issue by zajdee** [minio/minio#16219]
If a server has multiple interfaces and/or hostname points to multiple IP addresses (IPv4 and/or IPv6 and/or a mix thereof), the `minio` server is incapable of properly listening on all IPs. For example, if a FQDN points to multiple IPs:
```
# host server.com
server.com has address 192.0.2.1
server.com has address 192.0.2.2
server.com has IPv6 address 2001:db8:1:2::1
server.com has IPv6 address 2001:db8:1:3::1
```
and Minio is launched with
```
MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server /mnt/data  --address server.com:9000  --console-address "server.com:9001"
```
Then:
- Minio server only picks one address to listen on the "console" port; it does not listen on any other address included in the FQDN
- Minio only picks one address from the FQDN to listen on the "server" port; additionally, it listens on IPv4 `localhost` (`127.0.0.1:9000`) and IPv6 `localhost` (`[::1]:9000`), even if it was not instructed to do so.

For example, `localhost` cannot be specified as a console hostname now, because the app then only binds to `127.0.0.1:9001` and not `[::1]:9001`.

Minio is also incapable of having multiple addresses specified on the command line; if there are multiple `--address` or `--console-address` options, only the last one (of each type) seems to be considered by the application. There is no failure reported, however.

## Expected Behavior
- if a hostname is specified, it should be resolved at the launch time and app should listen on on all the addresses the hostname points to
- if the operator desires to specify multiple addresses in another way (e.g. on a command line), the application should be capable of understanding so and listening on 

## Current Behavior
See above.

## Possible Solution (all three together)
- Allow multiple `--address`/`--console-address` options to be specified on the command line.
- For listening, use all IPs a hostname resolves to
- Fix the bind/listen code to properly handle listening when multiple IPs are specified

## Steps to Reproduce (for bugs)
See above.

## Context
If my server has multiple IPs, I cannot explicitly bind Minio to selected ones, using a hostname or an explicit list of addresses. I can only bind it to one address. If my environment is dual-stacked (IPv4+IPv6), I can bind to only one protocol when explicitly selecting address(es) to bind on (and not using the `any`/`unspecified` address, `::`).

## Your Environment
* Version used (`minio --version`): Latest Minio binary from the project website; `Version: RELEASE.2022-12-07T00-56-37Z (go1.19.3 linux/amd64)`
* Server setup and configuration: IPv4/IPv6 dual-stacked, multi-homed, multiple IPs on the machine
* Operating System and version (`uname -a`): `Linux server.local 5.17.6-051706-generic #202205090841 SMP PREEMPT Mon May 9 08:51:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> * Minio only picks one address from the FQDN to listen on the "server" port; additionally, it listens on IPv4 `localhost` (`127.0.0.1:9000`) and IPv6 `localhost` (`[::1]:9000`), even if it was not instructed to do so.

We always listen on 127.0.0.1 since Console UI reaches out to MinIO locally regardless of the specific IP being specified.

This is working as expected.

**Comment by harshavardhana** [comment]
> * Minio server only picks one address to listen on the "console" port; it does not listen on any other address included in the FQDN

It will only pick up the first address @zajdee also as per design.

**Comment by zajdee** [comment]
Then the design is wrong. This is not how server applications work.

**Comment by zajdee** [comment]
@harshavardhana can you please NOT close apparent bugs? This leads to extra work when opening another ones.

**Comment by harshavardhana** [comment]
> Then the design is wrong. This is not how server applications work.

We have certain requirements, design is our choice you don't have to agree.

Listening on multiple IPs when host resolves to multiple IPs is something that can be done with some considerations. However it is not something we will work on right now, if it's important to you feel free to send a PR.

**Comment by KaliszAd** [comment]
Thank you @zajdee for opening a bug report after our discussion. @harshavardhana this is making life difficult e.g. when using MinIO on a dev machine and everywhere you would like for MinIO to dual-stack.

You cannot expect for it to work on both localhost addresses (IPv4 and IPv6) as almost all other server software does by default unless you also want to listen on every other address on the machine too, which is a really bad security practice even if you firewall correctly - security works in layers and reducing attack surface is always the best approach. There is no way to specify multiple addresses explicitly too - a recurring issue from my research here in the issue tracker. e.g. https://github.com/minio/minio/issues/8676 and it causes some confusion in other issues, usually related to IPv6 as that is usually where the problem hits.

**Comment by harshavardhana** [comment]
@KaliszAd we pass the serverAddress passed via DNS directly to Go's net/http ListenAndServe() framework. This doesn't support listening on multiple IPs via DNS resolving to multiple IPs.

This is something Go has to natively fix. 

```
 dig nano

; <<>> DiG 9.18.1-1ubuntu1.2-Ubuntu <<>> nano
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54526
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;nano.                          IN      A

;; ANSWER SECTION:
nano.                   0       IN      A       127.0.1.1
nano.                   0       IN      A       127.0.1.2

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Dec 12 13:11:53 PST 2022
;; MSG SIZE  rcvd: 65
```

```go
package main

import (
        "fmt"
        "html"
        "log"
        "net/http"
)

func main() {
        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
        })

        log.Fatal(http.ListenAndServe("nano:8080", nil))
}
```

```
Active Internet connections (only servers)
tcp        0      0 127.0.1.1:8080          0.0.0.0:*               LISTEN      756579/server       
```

This is why it is not something of a priority right now. You are free to send a fix if this is a pressing requirement.

This issue will remain closed since we are not planning to work on this right now @zajdee

**Comment by ravindk89** [comment]
https://github.com/minio/minio/pull/16223 addresses at least the reported issue within MinIO. Someone - perhaps a developer very experienced with IPv4/IPv6 network stacks - would have to engage with the upstream Go libraries to help patch this for the larger ecosystem.

**Comment by harshavardhana** [comment]
Thanks @ravindk89 I realized that it was easier for us than upstream Go since we manage the listeners appropriately.
