### ISSUE TITLE
Rebalancing transfers almost all data to other pool

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/minio#16212]
Site-replication between sites with different capacity.
The site with the smallest capacity had one server pool (one node, 4 disks of 1GB each) which reached full capacity.
Expanded this site by adding a new server pool. (same capacity in new pool, 4 disks of 1GB each)
We tried 'mc admin rebalance' to rebalance data over pools. It didn't balance, it just transferred as much possible data to the new pool.

## Expected Behavior
'mc admin rebalance status'

Per-pool usage before rebalancing:
- Pool-0 : 0.97%
- Pool-1 : 0.13%

Per-pool usage after rebalancing:
- Pool-0: 0.55%
- Pool-1: 0.55%

Not exactly 0.55%-0.55%, but at least somewhat close.

## Current Behavior
'mc admin rebalance status'

Per-pool usage before rebalancing:
- Pool-0 : 0.97%
- Pool-1 : 0.13%

Per-pool usage after rebalancing:
- Pool-0: 0.11%
- Pool-1: 0.99%

## Steps to Reproduce (for bugs)
1. Fill one server pool with data
2. Expand by adding a server pool with same capacity
3. mc admin rebalance

## Your Environment

* Version used (`minio --version`): RELEASE.2022-11-17T23-20-09Z (commit-id=a22b4adf4c5cc3e4db13fe92da683ef1ce45cd5a)
* Operating System and version (`uname -a`):Linux minio01 5.10.0-15-amd64 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

**Comment by klauspost** [comment]
What is your object size distibution?

**Comment by hamalchristiaan** [comment]
Most files were 15MiB. There are no larger files than 15MiB.
I did upload a lot of the same files over and over again (versions) to fill the server pool.

**Comment by harshavardhana** [comment]
@hamalchristiaan whats your pool sizes? can you provide output of 

```
mc admin decom status alias/
```

**Comment by hamalchristiaan** [comment]
Before:
![mc_admin_decom_status_before](https://user-images.githubusercontent.com/120193730/207023484-5b68ebae-074b-4502-94ac-f1bece108eb4.png)

After:
![mc_admin_decom_status_after](https://user-images.githubusercontent.com/120193730/207023482-c720fdeb-5364-4d03-9e34-542deab6653d.png)

(This was the second time I reproduced this)

**Comment by harshavardhana** [comment]
I think this is a tuning mistake in the code when calculating FreePercentGoal when used == total that causes the skew however the After() isn't that bad. // cc @krisis 

The affinity is given directly to the new pool which is generally desired practically since the newer pool is usually of better hardware (newer)

**Comment by hamalchristiaan** [comment]
Screenshots were made after reproducing this issue. The After() isn't that bad this time around.
First time when I encountered this problem, the 2nd pool really went to 99% (1.9 GiB or 2GiB).

**Comment by hamalchristiaan** [comment]
I tried this again with a new setup. This time I used one bucket without versioning, no replication whatsoever.
(All files are 10MiB)

Before:
![decom_status1](https://user-images.githubusercontent.com/120193730/207292522-a0e5d573-af02-40be-a21c-842c3aa9067f.png)
![rebalance_status1](https://user-images.githubusercontent.com/120193730/207292536-f3aec88d-66f3-4842-afc8-604d37a1dc4e.png)

After:
![decom_status2](https://user-images.githubusercontent.com/120193730/207292656-95b3a754-966b-4fea-b376-ce08591c6919.png)
![rebalance_status2](https://user-images.githubusercontent.com/120193730/207292664-640ff832-970b-450b-a3d0-2a88c1767a33.png)

**Comment by krisis** [comment]
I am looking into this issue now. I managed to recreate this issue locally. I shall post my findings here as soon as I arrive at the root cause.

**Comment by krisis** [comment]
@hamalchristiaan I think I found the main issue in rebalance process's internal accounting which lead to almost all the objects being moved to the new pool in your test. This PR https://github.com/minio/minio/pull/16240 should fix this issue. Could you test this PR and let us know if the issue is resolved?
