### ISSUE TITLE
When is latest version RELEASE.2022-12-12T19-27-27Z pushed to quay.io/minio/minio

### ISSUE THREAD

**Issue by nodesocket** [minio/minio#16229]
**Is your feature request related to a problem? Please describe.**
When is the latest version `RELEASE.2022-12-12T19-27-27Z` pushed to [https://quay.io/minio/minio](https://quay.io/repository/minio/minio?tab=tags)?

**Describe the solution you'd like**
Push `RELEASE.2022-12-12T19-27-27Z` up.

Thanks very much! Is this not automated? Just curious.

**Comment by harshavardhana** [comment]
It is being pushed right now.

**Comment by nodesocket** [comment]
@harshavardhana how long does the push take? I see `latest` tag was updated but no tag `RELEASE.2022-12-12T19-27-27Z`?

**Comment by harshavardhana** [comment]
> @harshavardhana how long does the push take? I see `latest` tag was updated but no tag `RELEASE.2022-12-12T19-27-27Z`?

It takes time @nodesocket - how long I don't know, there was a failure in uploading to quay.io for some reason (network related) - it should be available now.
