### ISSUE TITLE
minio web console request returns bad header content type

### ISSUE THREAD

**Issue by withnate1216** [minio/minio#16226]
## Expected Behavior
if we do not login to the web console. the web console request should return the header content-type text/html

## Current Behavior
the web console request returns the header content-type according to the request url. If  request url is end with  .txt , the response header content-type is text/plain

## Possible Solution
Fix the response header content-type to text/html , so the browser will redirect to login page automatically

## Steps to Reproduce (for bugs)
1. start minio with docker
2. open browser, browse 127.0.0.1:9001/aaa.txt
3. this request returns html body but the content-type is text/plain
4. it do not redirect to login page automatically

## Your Environment
minio version RELEASE.2022-07-30T05-21-40Z (commit-id=e6eab2091f632622fadbe3b25bb4732125b2d5df)

**Comment by harshavardhana** [comment]
Please use latest release.

**Comment by withnate1216** [comment]
@harshavardhana I update the docker image to the latest version , this problem still exists.
minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
