### ISSUE TITLE
Helm: provide the ability to run bucket/user/etc jobs during install

### ISSUE THREAD

**Issue by OvervCW** [minio/minio#16235]
**Is your feature request related to a problem? Please describe.**
I've created a Helm chart that installs Minio as a subchart. The application in my Helm chart depends on Minio having certain users and buckets available, but these are currently only created when the chart finishes installing. Since the installation waits for my application to become ready, this never happens and the installation times out in this catch 22 situation.

**Describe the solution you'd like**
I would like there to be an option to run the initialization jobs during the installation itself, for example as part of Minio's startup logic. Many of the Bitnami charts do their initialization this way.

**Describe alternatives you've considered**
The only alternative I can think of is to deploy Minio as a standalone chart before installing my own chart, but I prefer to install them together since they are tightly coupled, and in fact the main chart generates some resources (e.g. secrets) that the Minio chart depends on.

**Additional context**
N/A

**Comment by harshavardhana** [comment]
Good idea feel free to send a PR @OvervCW

**Comment by harshavardhana** [comment]
Feel free to send a PR here, this is not a priority for us closing.
