### ISSUE TITLE
Whether encrypted transmission is supported when logging in

### ISSUE THREAD

**Issue by purple-WL** [minio/minio#16230]
The login interface is as follows:
POST /minio/webrpc HTTP/2
Host: xxxxx

{"id":1,"jsonrpc":"2.0","params":{"username":"minioadmin","password":"minioadmin"},"method":"Web.Login"}

Whether the username and password parameters can be encrypted?

**Comment by harshavardhana** [comment]
Hello @purple-WL you are using an ancient version of MinIO, please upgrade.
