### ISSUE TITLE
Site failure recovery doesn't work as documented

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/minio#16234]
Site failure recovery requires 2 steps that don't work:
Step 3. Expand the existing site replication by adding the newly deployed site
Step 4. Remove the lost site from the site replication configuration

## Expected Behavior
Step 3. Expand the existing site replication by adding the newly deployed site:
expecting command 'mc admin replicate add siteA siteB siteC' to work

Step 4. Remove the lost site from the site replication configuration:
expecting command 'mc admin replicate remove siteA siteB --force' to work

## Current Behavior
'mc admin replicate add siteA siteB siteC' output: 
mc: <ERROR> Unable to add sites for replication. Error received when contacting a peer site (unable to create admin client for siteB/: Remote service endpoint https://siteB:9000 not available
remote target is offline for endpoint https://siteB:9000).

'mc admin replicate remove siteA siteB --force' output:
mc: <ERROR> Unable to remove cluster replication. Error received when contacting a peer site (unable to update peer siteB/: unable to create admin client for siteB/: Remote service endpoint https://siteB:9000/ not available
remote target is offline for endpoint https://siteB:9000/).

## Steps to Reproduce (for bugs)
1. Site replication active between site A and site B.
2. Crash Site B.
3. Create Site C as described in the first 2 steps of site failure recovery
4. Try 'mc admin replicate add siteA siteB siteC'
5. Try 'mc admin replicate remove siteA siteB --force'

## Your Environment
* Version used (`minio --version`): RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
* Operating System and version (`uname -a`): Linux minio-repl02 5.10.0-15-amd64 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

**Comment by poornas** [comment]
If site C is being brought in place of site B, there is an error here in your order of steps - you need to first remove the association with the defunct Site B
```

1. Site replication active between site A and site B.
2. Crash Site B.
3. Create Site C as described in the first 2 steps of site failure recovery
4. 'mc admin replicate remove siteA siteB --force'
5. 'mc admin replicate add siteA siteC'

```

**Comment by hamalchristiaan** [comment]
I used the order of steps as documented:
![image](https://user-images.githubusercontent.com/120193730/207536947-d93ae4e2-b58f-4854-8e07-002a97037735.png)

So removing the association with the defunct Site B would be first. But that command doesn't work as expected...

**Comment by harshavardhana** [comment]
// cc @ravindk89

**Comment by ravindk89** [comment]
Thanks - cc @djwfyi .

I'll move this to docs for us to work on.
