### ISSUE TITLE
Bug with bucket permissions

### ISSUE THREAD

**Issue by Igorgro** [minio/minio#16238]
I installed a minio server to use it as cache for gitlab runner but faced with strange issue with permissions. I've created a bucket named `gitlab` and a user. Also I created the policy to allow this user only to acces this specific bucket. The policy content is the following:
<details>
  <summary>Policy source</summary>

  ```json
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": [
                  "s3:PutObject",
                  "s3:PutObjectTagging",
                  "s3:DeleteObject",
                  "s3:GetObject",
                  "s3:GetObjectTagging",
                  "s3:GetObjectVersion",
                  "s3:ListAllMyBuckets",
                  "s3:ListBucket"
              ],
              "Resource": [
                  "arn:aws:s3:::gitlab"
              ]
          }
      ]
  }
  ```
  
</details>

and assigned it to that user. But when I'm logging in (through web console_ as that user, I only have permission to list bucket and to list bucket contents. I cannot download and upload anything. The most strange thing is that if I replace `arn:aws:s3:::gitlab` with `arn:aws:s3:::gitlab*`, then the user recieves all permissions and can upload and download objects. I've tried to retype all names manually in case of typo but this didn't help.

## Expected Behavior
All permissions works as expected

## Current Behavior
Permissions only work when policy contains an asterisk

## Steps to Reproduce (for bugs)

1. Install minio using docker with 4 data volumes
2. Login as root and create a user, a bucket and a policy (see earlier) which allows that user to perform only specific operations on that bucket
3. Login as that user to the web console and try to download/upload something

## Context
I'm trying to create a user which can be used by gitlab runner, but using astersisk in permissions looks a weird solution for me, because there probably can be another buckets which can match that pattern.

## Your Environment

* Version used (`minio --version`):
    ```
    minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
    Runtime: go1.19.4 linux/amd64
    License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
    Copyright: 2015-2022 MinIO, Inc.
    ```
* Server setup and configuration: Docker with default configuration
* Operating System and version (`uname -a`): `Linux myserver 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is an expected behavior, just specifying bucket resource doesn't not mean you get write access.

Asterisk is the way to tell how the resources must match the incoming HTTP resource names.

**Comment by Igorgro** [comment]
@harshavardhana thank you for your explanation. I was reading the docs during setup and it contains the following text:
```quote
The following sample document provides a template:
...
"Resource" : "arn:aws:s3:::*",
...

For the Statement.Resource key, you can replace the * with the specific bucket to which the policy statement should apply
```

I've interpreted is as that I can just write `arn:aws:s3:::gitlab` and everything will be ok, but faced with this not obvius  behavior.

**Comment by harshavardhana** [comment]
> @harshavardhana thank you for your explanation. I was reading the docs during setup and it contains the following text:
> 
> ```
> The following sample document provides a template:
> ...
> "Resource" : "arn:aws:s3:::*",
> ...
> 
> For the Statement.Resource key, you can replace the * with the specific bucket to which the policy statement should apply
> ```
> 
> I've interpreted is as that I can just write `arn:aws:s3:::gitlab` and everything will be ok, but faced with this not obvious behavior.

@ravindk89 ^^
