### ISSUE TITLE
mac check in GCM failed

### ISSUE THREAD

**Issue by sathishkumar-p** [minio/minio#16244]
### Discussed in https://github.com/minio/minio/discussions/16218

<div type='discussions-op-text'>

<sup>Originally posted by **sathishkumar-p** December 12, 2022</sup>
:wave: Hi everyone!
I am using the Minio Admin Client to access the Minio cluster.
I am getting the following error while listing the users. **InvalidCipherTextException: mac check in GCM failed**</div>

**Comment by harshavardhana** [comment]
Can you share a sample code please? Are you running a FIPS based server ?

**Comment by sathishkumar-p** [comment]
Hi Harshavardhana,
![image](https://user-images.githubusercontent.com/25504642/207553253-f3898ff9-dbbd-4459-97d1-ff67cade2ac3.png)

**Comment by sathishkumar-p** [comment]
> FIPS

What is FIPS mode ?

**Comment by harshavardhana** [comment]
> Hi Harshavardhana, ![image](https://user-images.githubusercontent.com/25504642/207553253-f3898ff9-dbbd-4459-97d1-ff67cade2ac3.png)

which operating system is your java running on ?and which version of minio-java are you using?

**Comment by sathishkumar-p** [comment]
Java (17) is running as a docker container under Ubuntu 20.04.5 LTS OS. 
Minio Admin Client version: 8.3.6
Minio Server: DEVELOPMENT.2022-01-28T02-28-16Z

![image](https://user-images.githubusercontent.com/25504642/207768007-fcda56da-9369-46d7-a3ef-fec2d6409788.png)

**Comment by harshavardhana** [comment]
> Java (17) is running as a docker container under Ubuntu 20.04.5 LTS OS. Minio Admin Client version: 8.3.6 Minio Server: DEVELOPMENT.2022-01-28T02-28-16Z
> 
> ![image](https://user-images.githubusercontent.com/25504642/207768007-fcda56da-9369-46d7-a3ef-fec2d6409788.png)

You have to upgrade your server @sathishkumar-p and let us know.

**Comment by sathishkumar-p** [comment]
I have upgraded. Still, the same issue is there.
![image](https://user-images.githubusercontent.com/25504642/208037370-5437d4dd-0504-4da8-ac5e-4165a12d25fd.png)
While calling minioAdminClient.listusers(). Its fails with the same error. 
![image](https://user-images.githubusercontent.com/25504642/208038694-2ec02888-2f0b-4a64-8174-6d4265ccc8e9.png)

**Comment by harshavardhana** [comment]
@aead ^^

**Comment by sathishkumar-p** [comment]
Any help?

**Comment by harshavardhana** [comment]
> I have upgraded. Still, the same issue is there.

This version is unsupported by MinIO why are you using bitnami container when we publish official images? - it is such a useless confusion created by them. 

They are also building images in the wrong Go version 1.18.9. 

```
./minio -v
minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```

Here is the official build

**Comment by harshavardhana** [comment]
I tried minio-java code it seems to work perfectly fine with our official release @sathishkumar-p

**Comment by sathishkumar-p** [comment]
Thanks for your time and support @harshavardhana. I will check that.
