### ISSUE TITLE
minio play mp3 and drag control ,minio is error 503

### ISSUE THREAD

**Issue by lijieaa** [minio/minio#16242]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
minio play mp3 and drag control,play perfect

## Current Behavior
minio play mp3 and drag control ,minio is error 503

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
* Server setup and configuration:
./minio server --console-address :9989 --address :9988 /opt/edu/data
* Operating System and version (`uname -a`):
Linux iZ2ze9x33g3xag4kqqpnm9Z 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Can you share `mc admin trace -v alias` output, while you are attempting to drag mp3 seek

**Comment by lijieaa** [comment]
> Can you share `mc admin trace -v alias` output, while you are attempting to drag mp3 seek
Accept: */*
Accept-Encoding: identity;q=1, *;q=0
Accept-Language: zh-CN,zh;q=0.9,en-GB;q=0.8,en-US;q=0.7,en;q=0.6
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
<BLOB>
[RESPONSE] [2022-12-14T14:08:46.519] [ Duration 10.00024s  ↑ 91 B  ↓ 361 B ]
503 Service Unavailable
Accept-Ranges: bytes
Retry-After: 120
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Vary: Origin
X-Amz-Request-Id: 173093EF03779B12
X-Xss-Protection: 1; mode=block
Content-Length: 361
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
<BLOB>

**Comment by lijieaa** [comment]
> Can you share `mc admin trace -v alias` output, while you are attempting to drag mp3 seek
<Error>
<Code>SlowDown</Code>
<Message>A timeout exceeded while waiting to proceed with the request, please reduce your request rate</Message>
<Resource>/test/7731511f1f4bf5b8209fbaa1a3d49a49/豪记之星10.wav.mp3</Resource>
<RequestId>1730942BDAEFA048</RequestId>
<HostId>7caed2fc-d60f-4e60-ac9f-3f11ddcf9777</HostId>
</Error>

what's problem? I don't know

**Comment by harshavardhana** [comment]
> > Can you share `mc admin trace -v alias` output, while you are attempting to drag mp3 seek
> 
> `SlowDown` A timeout exceeded while waiting to proceed with the request, please reduce your request rate /test/7731511f1f4bf5b8209fbaa1a3d49a49/豪记之星10.wav.mp3 1730942BDAEFA048 7caed2fc-d60f-4e60-ac9f-3f11ddcf9777
> what's problem? I don't know

Okay it's because you have ran out of number of API requests.

What is your server RAM size? You either need to reduce number of requests to your server or add more RAM.

**Comment by lijieaa** [comment]
> RAM size

thank  you

**Comment by lijieaa** [comment]
> > > Can you share `mc admin trace -v alias` output, while you are attempting to drag mp3 seek
> > 
> > 
> > `SlowDown` A timeout exceeded while waiting to proceed with the request, please reduce your request rate /test/7731511f1f4bf5b8209fbaa1a3d49a49/豪记之星10.wav.mp3 1730942BDAEFA048 7caed2fc-d60f-4e60-ac9f-3f11ddcf9777
> > what's problem? I don't know
> 
> Okay it's because you have ran out of number of API requests.
> 
> What is your server RAM size? You either need to reduce number of requests to your server or add more RAM.

minio can config limit http range size to reduce read byte to RAM?

**Comment by harshavardhana** [comment]
> minio can config limit http range size to reduce read byte to RAM?

No it is not something to do with range-get it is something to do with your server either you are running on a very low end system or your browser is sending 100's of requests that are overwhelming your server.
