### ISSUE TITLE
lockR.Lock 

### ISSUE THREAD

**Issue by jsls2517** [minio/minio#16241]
minio version DEVELOPMENT.2022-12-13T09-20-20Z
centos8 4.18.0-348.7.1.el8_5.x86_64

```bash
mc rm  --force --dangerous  --recursive  --versions --bypass s3/warp-benchmark-bucket
```
Using 'mc' to delete the object and then using 'umount' to unmount the disk of a node of the cluster will cause the deletion to get stuck.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/13162606/207484495-6fb0c545-30c8-4b85-b7aa-1337c90d2900.png">

**Comment by harshavardhana** [comment]
The delete is actually not stuck here, it has simply lost quorum, leading to client retrying the request.

Please explain your deployment, deployment version of MinIO.

You haven't explained anything about your setup for us to help you, closing the issue as incomplete
