### ISSUE TITLE
Cannot delete objects properly

### ISSUE THREAD

**Issue by jsls2517** [minio/minio#16245]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Can continue to delete

## Current Behavior

Using 'mc' to delete the object and then using 'umount' to unmount the disk of a node of the cluster will cause the deletion to get stuck.

## Steps to Reproduce (for bugs)

1. mc rm  --force --dangerous  --recursive  --versions --bypass s3/warp-benchmark-bucket
2. ssh s3-pool2-node6
3. umount -l /mnt/disk9

## Context

https://github.com/minio/minio/issues/16241

## Your Environment

* Version used (`minio --version`): minio version DEVELOPMENT.2022-12-13T09-20-20Z
* Server setup and configuration: MINIO_VOLUMES="http://s3-pool1-node{1...6}:9000/mnt/disk{1...36} http://s3-pool2-node{1...6}:9000/mnt/disk{1...36}"
* Operating System and version (`uname -a`): 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jsls2517** [comment]
I now have to use 'ForceUnlock' to force the lock to be released in order to continue the deletion

**Comment by harshavardhana** [comment]
> I now have to use 'ForceUnlock' to force the lock to be released in order to continue the deletion

It actually doesn't make sense, when you do `umount -l /mnt/disk9` can you perform `mc admin info` - before doing any deletes?

**Comment by harshavardhana** [comment]
Looks like you have some other setup issue here @wenbingzhang 

```
~ mc cp /etc/hosts play/testbucket/
/etc/hosts:                           226 B / 226 B ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.31 KiB/s 0s
```

Then proceed to umount the drive

```
~ umount -l /home/play/data1
```

```
~ mc rm -r --force play/testbucket/
Removed `play/testbucket/hosts`.
```

```
~ mc ls play/testbucket/
<empty>
```

I think there is something wrong on your end on your setup, a single drive missing doesn't mean DELETE will wait or slow down in some manner.

**Comment by jsls2517** [comment]
> Looks like you have some other setup issue here @wenbingzhang
> 
> ```
> ~ mc cp /etc/hosts play/testbucket/
> /etc/hosts:                           226 B / 226 B ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.31 KiB/s 0s
> ```
> 
> Then proceed to umount the drive
> 
> ```
> ~ umount -l /home/play/data1
> ```
> 
> ```
> ~ mc rm -r --force play/testbucket/
> Removed `play/testbucket/hosts`.
> ```
> 
> ```
> ~ mc ls play/testbucket/
> <empty>
> ```
> 
> I think there is something wrong on your end on your setup, a single drive missing doesn't mean DELETE will wait or slow down in some manner.

Be sure to run 'mc rm -r --force' first, and then 'umount -l'

**Comment by jsls2517** [comment]
> mc admin info



> > I now have to use 'ForceUnlock' to force the lock to be released in order to continue the deletion
> 
> It actually doesn't make sense, when you do `umount -l /mnt/disk9` can you perform `mc admin info` - before doing any deletes?

<img width="380" alt="image" src="https://user-images.githubusercontent.com/13162606/207604492-8d228071-a36d-4794-ade2-97bb64b33514.png">

**Comment by harshavardhana** [comment]
> Be sure to run 'mc rm -r --force' first, and then 'umount -l'

does it matter?

**Comment by jsls2517** [comment]
> > Be sure to run 'mc rm -r --force' first, and then 'umount -l'
> 
> does it matter?

Execute 'umount -l' first, it can be deleted normally

**Comment by harshavardhana** [comment]
> Execute 'umount -l' first, it can be deleted normally

I just showed that in my comment @wenbingzhang - I can't see what you are seeing, are your disks, not regular disks? are they some network volumes?

**Comment by harshavardhana** [comment]
Oh wait you mean there must be an active delete in progress.

**Comment by jsls2517** [comment]
First run 'mc rm -r -force', there needs to be enough data in the bucket to reproduce it

**Comment by jsls2517** [comment]
> > Execute 'umount -l' first, it can be deleted normally
> 
> I just showed that in my comment @wenbingzhang - I can't see what you are seeing, are your disks, not regular disks? are they some network volumes?

It's a normal disk

**Comment by jsls2517** [comment]
> Oh wait you mean there must be an active delete in progress.

Yes

**Comment by harshavardhana** [comment]
Okay, I tried with active setup and deletes of around 100k objects while umounting and mounting the disks repeatedly, but I do not see any such hangs.

I suspect you have some other issues with the setup.

**Comment by jsls2517** [comment]
> Okay, I tried with active setup and deletes of around 100k objects while umounting and mounting the disks repeatedly, but I do not see any such hangs.
> 
> I suspect you have some other issues with the setup.

My bucket data size is 1.5PB. File size in 5M-1G

**Comment by jsls2517** [comment]
I only set MINIO_VOLUMES and MINIO_BROWSER=off

**Comment by jsls2517** [comment]
`mc admin info `

●  s3-pool1-node1:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 1

●  s3-pool1-node2:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 1

●  s3-pool1-node3:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 1

●  s3-pool1-node4:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 1

●  s3-pool1-node5:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 1

●  s3-pool1-node6:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 1

●  s3-pool2-node1:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 2

●  s3-pool2-node2:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 2

●  s3-pool2-node3:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 2

●  s3-pool2-node4:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 2

●  s3-pool2-node5:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 2

●  s3-pool2-node6:9000
   Uptime: 1 day 
   Version: 2022-12-13T09:20:20Z
   Network: 12/12 OK 
   Drives: 36/36 OK 
   Pool: 2

Pools:
   1st, Erasure sets: 18, Drives per erasure set: 12
   2nd, Erasure sets: 18, Drives per erasure set: 12

**Comment by wenbingzhang** [comment]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/13162606/207751342-6de7158f-2355-4cc1-9826-72196cf4d701.png">
Found a large number of 409 states

**Comment by wenbingzhang** [comment]
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/13162606/207751600-d13a1621-5b43-4c27-b563-f2f5a470a913.png">
Found a large number of 409 states

**Comment by jsls2517** [comment]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/13162606/207751737-6762c182-989b-4595-baa5-705b71f92e43.png">
Found a large number of 409 status

**Comment by jsls2517** [comment]
mc: <ERROR> Failed to remove `s3/warp-benchmark-bucket`. A timeout occurred while trying to lock a resource, please reduce your request rate

**Comment by jsls2517** [comment]
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/13162606/207754410-3a84e046-2316-4080-8287-8fc3595c6eb5.png">

**Comment by harshavardhana** [comment]
> My bucket data size is 1.5PB. File size in 5M-1G

@wenbingzhang is this a commercial deployment?

**Comment by jsls2517** [comment]
> > My bucket data size is 1.5PB. File size in 5M-1G
> 
> @wenbingzhang is this a commercial deployment?

We are still in the testing phase

**Comment by jsls2517** [comment]
curl -I http://localhost:9000/minio/health/cluster
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Request-Id: 17313B90A8728649
X-Content-Type-Options: nosniff
X-Minio-Write-Quorum: 8
X-Xss-Protection: 1; mode=block
Date: Fri, 16 Dec 2022 09:20:29 GMT

**Comment by harshavardhana** [comment]
> > > My bucket data size is 1.5PB. File size in 5M-1G
> > 
> > 
> > @wenbingzhang is this a commercial deployment?
> 
> We are still in the testing phase

What is the overall application that is this is going to be used for ?

**Comment by jsls2517** [comment]
> > > > My bucket data size is 1.5PB. File size in 5M-1G
> > > 
> > > 
> > > @wenbingzhang is this a commercial deployment?
> > 
> > 
> > We are still in the testing phase
> 
> What is the overall application that is this is going to be used for ?

Used to store active data for a short period of time

**Comment by jsls2517** [comment]
Abandon "mc" and use sdk's ListObjectsV2 and RemoveObject to delete correctly
