### ISSUE TITLE
Bucket objects not showing when using server version (RELEASE.2022-12-07T00-56-37Z)

### ISSUE THREAD

**Issue by a-als205** [minio/minio#16256]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

From the Buckets page, clicking on Browse of a single bucket, would load the `buckets/bucket-name/browse` page and show bucket's content/files. 

## Current Behavior

The `buckets/bucket-name/browse` page loads but the files do not show up and the files listing area would keep showing the Loading message.

## Possible Solution

Upgrading to the latest version `RELEASE.2022-12-12T19-27-27Z` fixes the issue. 

## Steps to Reproduce (for bugs)

Follow the general official guidelines:
1. run `wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20221207005637.0.0_amd64.deb`
2. run `dpkg -i minio_20221207005637.0.0_amd64.deb`
3. restart MinIO 
4. Open the browser on `localhost:9001`
5. Go to a bucket that has files in it, you will get the loading message.

It is important to note that the ObjectManager does get the `101` response code but the objects/files don't get retrieved for some reason.

## Context

Opening this issue to bring attention to this exact release. There were multiple reports of similar issues in the last week #16196 and #16200. It is up to Dev to decide what to do with the version.

## Your Environment

* Version used (`minio --version`): Multiple Versions 
* Operating System and version (`uname -a`): `Linux [name] 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` & `Linux VirtualBox 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`. Same behaviour on both versions.

**Comment by harshavardhana** [comment]
> Upgrading to the latest version `RELEASE.2022-12-12T19-27-27Z` fixes the issue.

the fix is released, not sure what this issue is about?
