### ISSUE TITLE
minio client CORS error

### ISSUE THREAD

**Issue by jainprabhash** [minio/minio#16250]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
calls from minio client should not result in CORS error

## Current Behavior
The prefetch OPTIONS call returns 200. but the client.listBuckets() fails showing CORS error.

## Possible Solution
"Access-Control-Allow-Origin": "*" can be added in the request headers.

## Steps to Reproduce (for bugs)
I have configured my minio client as 
`const mc = new minio.Client( {
    endPoint: "45.79.125.225",
    port: 9001,
    useSSL: false,
    accessKey: "XXXXXXXXXXXXXXXX",
    secretKey: "XXXXXXXXXXXXXXXXXXXXXXXXX",
  }
);`

and then, I am calling it as
`import mc from "../utils/minio";
const getBuckets = async () => {
    const res = await mc.listBuckets();
    setBuckets(res);
  };

  useEffect(() => {
    getBuckets();
  }, []);`

## Context
I was not getting  any solution to the 7 day limit on the file sharing URL. That's why I went towards the SDK approach.

## Your Environment

React 18
minio 7.0.32

**Comment by harshavardhana** [comment]
CORS allow origin is set to '*' by default for all S3 resources via browser - can you share the error?

**Comment by klauspost** [comment]
Also, which server (and version) you are running this against.

**Comment by harshavardhana** [comment]
Closing, please respond back with the answers to our questions - we can re-open.
