### ISSUE TITLE
Support removing a site from the replication config even if that site is down

### ISSUE THREAD

**Issue by ravindk89** [minio/minio#16265]
## Expected Behavior

Related to discussion in https://github.com/minio/docs/issues/677

The current site replication behavior has a logical progression that makes recovery complicated. 
Specifically:

1. Removing a site requires removing the entire replication config via `mc admin replicate remove --force --all`. This allows removing a site that is offline/unhealthy, since we otherwise try to update the entire replication config across all sites.
2. Since site replication requires that no more than one site have data, this means you would have to wipe all other remaining sites before rebuilding the configuration
3. This complicates recovery by substantially increasing the amount of data to re-replicate

In discussion with @poornas this is an oversight that resulted from trying to avoid a situation similar to the following:

1. Site C goes down and is not expected to come back online
2. Admin removes Site C from the replication configuration
3. Site C somehow comes back up
4. Site A, B, D have their replication config excluding Site C. SiteC still thinks it's a part of the full set

The above would allow for Site C to replicate data to A/B/D and result in an undesired replication state, until someone reset Site C's setup.

Our docs already warn to completely wipe the unhealthy site before bringing it back up, *but* a user could still do this by accident - thus the current logic. However, in discussion with @poornas , it is more important to avoid having to re-replicate a large amount of data to multiple sites in more complex replication configurations. 

## Current Behavior

Removing a site requires completely resetting the site replication configuration, which also requires wiping all but one site in the config as per the existing site replication configuration rules.

## Possible Solution

we need to support syntax similar to the following:

```shell
$> mc admin replicate remove --force --dangerous HEALTHY_SITE_ALIAS UNHEALTHY_SITE_ALIAS
```

Running without `--dangerous` should output something similar to the following if the target site is offline or unhealthy:

```
WARNING: UNHEALTHY_SITE_ALIAS is offline or unreachable.
Include the --dangerous flag to force remove UNHEALTHY_SITE_ALIAS from the existing configuration.

Using this flag does NOT update UNHEALTHY_SITE_ALIAS, and if that deployment comes back online it can continue replicating as per the original site replication configuration.
You MUST completely wipe the UNHEALTHY_SITE_ALIAS deployment before bringing it back online, if ever, to avoid an unstable replication state.
```

If the site is online, then there's no real issue with removing it, since we can maintain a consistent replication state.

## Steps to Reproduce (for bugs)

See linked DOCS issue 

## Context

This may affect any user with multi-site replication configurations who needs to perform site recovery.

## Regression

No

## Your Environment

See linked DOCS issue

**Comment by harshavardhana** [comment]
Good idea @ravindk89 we should be able to allow dangerous behavior here.

**Comment by ravindk89** [comment]
@poornas should i make a corresponding `minio/mc` issue?

**Comment by harshavardhana** [comment]
> @poornas should i make a corresponding `minio/mc` issue?

It looks like `mc admin replicate remove --all --force` was designed for the removal of all sites even when some sites are down, it does not allow partial removal that's all. In this case however it is acceptable solution.. IMHO

There are no other changes needed @ravindk89

**Comment by ravindk89** [comment]
> > @poornas should i make a corresponding `minio/mc` issue?
> 
> It looks like `mc admin replicate remove --all --force` was designed for the removal of all sites even when some sites are down, it does not allow partial removal that's all. In this case however it is acceptable solution.. IMHO
> 
> There are no other changes needed @ravindk89

As Poorna noted, it works fine if you only have two sites (it's basically the same). For 3+ sites it's an issue - I don't know how much we're seeing that in the wild already, but the docs need to call out that at least for now there's a bit of a roadbump on that specific topology for recovery.

Ideally we just patch the behavior in server and this stops being a consideration.

**Comment by harshavardhana** [comment]
I think those are super niche cases, for example when you want to completely remove `mc admin replicate remove --all --force` is what is useful and available to use.

I am not sure what else we need to do here, I think it's unsafe to dangerously remove only "one" site from the entire multi-site replication setup for good reasons, so such a feature is not available and not needed IMO.

**Comment by ravindk89** [comment]
@harshavardhana as it stands, if anyone has 2+ site replication, a single site failure requires a complete wipe of all but one replication site.

If someone has even a few hundred TB of data cross sites, this is a massive amount of data to restore. It's also very unusual for any site recovery design to involve a wipe of all sites due to the loss of a single site.

I think `mc admin replicate remove --force --dangerous` is correct for removing a single site from a larger site replication configuration. There are problems that can arise, but we can cover that in documentation and CLI guidance. Otherwise we have to explain to customers/users that our implementation of site replication can actually tolerate the loss of no more than one site, otherwise you have to redo the entire thing + clear data from all but one site.

**Comment by poornas** [comment]
> I think `mc admin replicate remove --force --dangerous` is correct for removing a single site from a larger site replication configuration. There are problems that can arise, but we can cover that in documentation and CLI guidance. Otherwise we have to explain to customers/users that our implementation of site replication can actually tolerate the loss of no more than one site, otherwise you have to redo the entire thing + clear data from all but one site.

We don't need an extra flag - the --force flag is sufficient. We just need to make it clear in the docs that if peer is down/returned an error the removal needs to be re-tried with peer alias

**Comment by ravindk89** [comment]
No objections - and that is in fact the plan for the docs.

**Comment by ravindk89** [comment]
@poornas so I tested this as follows by building from your branch:

1. Run three SNSD setups with fresh drives:

```
./minio server ~/minio/minio-1/minio --address ":9000"
./minio server ~/minio/minio-2/minio --address ":9001"
./minio server ~/minio/minio-3/minio --address ":9002"
```

2. Create alias and replication config

```
mc admin alias set site1 http://localhost:9000 minioadmin minioadmin
mc admin alias set site2 http://localhost:9001 minioadmin minioadmin
mc admin alias set site3 http://localhost:9002 minioadmin minioadmin 
```

3. Shut down site 2 (CTRL+C) . Confirmed via logs that site2 is down

```
API: SYSTEM()
Time: 00:05:42 UTC 12/22/2022
DeploymentID: e789b5a3-6c9d-4361-b539-94b1956315e0
Error: Site replication error(s): 
'ReplicationStatus' on site site1 (1c61693e-f08e-4d16-bdb3-60a144aae7b2): succeeded
'ReplicationStatus' on site site3 (e789b5a3-6c9d-4361-b539-94b1956315e0): succeeded
'ReplicationStatus' on site site2 (f8ea1940-f48b-4cc6-85ee-4ca6b24e51d9): failed(Remote service endpoint http://localhost:9001 not available
        remote target is offline for endpoint http://localhost:9001) (cmd.SRError)
       4: internal/logger/logger.go:258:logger.LogIf()
       3: cmd/site-replication.go:3749:cmd.(*SiteReplicationSys).healBuckets()
       2: cmd/site-replication.go:3655:cmd.(*SiteReplicationSys).healRoutine()
       1: cmd/site-replication.go:3630:cmd.(*SiteReplicationSys).startHealRoutine()
```

4. Attempt to remove the downed site

```
mc admin replicate remove site1 site2 --force --debug                                                                                                                1 ✘ 
mc: <DEBUG> PUT /minio/admin/v3/site-replication/remove?api-version=1 HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2022-12-13T00-23-28Z
Content-Length: 31
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20221222//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: a5cb41876b41e4e2f3d29e34fb552514123543c344383b8426283eb02a11fedc
X-Amz-Date: 20221222T000635Z

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 292
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Thu, 22 Dec 2022 00:06:35 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1732F4D23BDBD2D0
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioSiteReplicationConfigMissingError","Message":"Site not found in site replication configuration (unable to find site replication configuration)","Resource":"/minio/admin/v3/site-replication/remove","RequestId":"1732F4D23BDBD2D0","HostId":"1c61693e-f08e-4d16-bdb3-60a144aae7b2"}
mc: <DEBUG> Response Time:  816.723µs

mc: <ERROR> Unable to remove cluster replication. Site not found in site replication configuration (unable to find site replication configuration)
 (1) admin-replicate-remove.go:120 cmd.mainAdminReplicationRemoveStatus(..) Tags: [site1, site2]
 (0) admin-replicate-remove.go:120 cmd.mainAdminReplicationRemoveStatus(..)
 Release-Tag:RELEASE.2022-12-13T00-23-28Z | Commit:4b4cab0441f0 | Host:ravindk-minio-thinkpad | OS:linux | Arch:amd64 | Lang:go1.19.4 | Mem:3.3 MB/26 MB | Heap:3.3 MB/12 MB.
```

```
API: SiteReplicationRemove()
Time: 00:05:46 UTC 12/22/2022
DeploymentID: 1c61693e-f08e-4d16-bdb3-60a144aae7b2
RequestID: 1732F4C6E2171B5B
RemoteHost: [::1]
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2022-12-13T00-23-28Z
Error: unable to create admin client for site2: Remote service endpoint http://localhost:9001 not available
        remote target is offline for endpoint http://localhost:9001 (cmd.SRError)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/admin-handlers-site-replication.go:481:cmd.adminAPIHandlers.SiteReplicationRemove()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SiteReplicationRemove()
Time: 00:06:35 UTC 12/22/2022
DeploymentID: 1c61693e-f08e-4d16-bdb3-60a144aae7b2
RequestID: 1732F4D23BDBD2D0
RemoteHost: [::1]
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2022-12-13T00-23-28Z
Error: unable to find site replication configuration (cmd.SRError)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/admin-handlers-site-replication.go:481:cmd.adminAPIHandlers.SiteReplicationRemove()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()

API: SiteReplicationRemove()
Time: 00:07:05 UTC 12/22/2022
DeploymentID: 1c61693e-f08e-4d16-bdb3-60a144aae7b2
RequestID: 1732F4D92B267F01
RemoteHost: [::1]
Host: localhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2022-12-13T00-23-28Z
Error: unable to find site replication configuration (cmd.SRError)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/admin-handlers-site-replication.go:481:cmd.adminAPIHandlers.SiteReplicationRemove()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

*However* the site did appear to remove successfully despite the API and mc errors. So it *is* working, it's just a little odd.

Worth noting that `mc admin replicate status` hangs until it times out, but that's out of scope.

Per Slack convo, this is expected - we are force removing an unreachable site. Some level of API errors are expected at this time. I'll ensure the docs cover this as part of the expected response and push users to `mc admin replicate info` to validate the final configuration.

LGTM otherwise.

**Comment by harshavardhana** [comment]
> Per Slack convo, this is expected - we are force removing an unreachable site. Some level of API errors are expected at this time. I'll ensure the docs cover this as part of the expected response and push users to `mc admin replicate info` to validate the final configuration.

This is not correct, we don't need to error out, we have a way to indicate the operation was partial - so `mc` can properly show some operations were successful and some were not.

**Comment by harshavardhana** [comment]
Here are the new changes minio and `mc` shows the correct results. 

```
+ make install
Checking dependencies
Building minio binary to './minio'
Installing minio binary to '/home/harsha/go/bin/minio'
Installation successful. To learn more, try "minio --help".
+ pkill -9 minio
+ rm -rf /tmp/minio/
+ site1_pid=1698017
+ ./minio server /tmp/minio/minio-1 --address :9000
+ site2_pid=1698018
+ ./minio server /tmp/minio/minio-2 --address :9001
+ site3_pid=1698019
+ sleep 3
+ ./minio server /tmp/minio/minio-3 --address :9002
+ export MC_HOST_site1=http://minioadmin:minioadmin@localhost:9000
+ MC_HOST_site1=http://minioadmin:minioadmin@localhost:9000
+ export MC_HOST_site2=http://minioadmin:minioadmin@localhost:9001
+ MC_HOST_site2=http://minioadmin:minioadmin@localhost:9001
+ export MC_HOST_site3=http://minioadmin:minioadmin@localhost:9002
+ MC_HOST_site3=http://minioadmin:minioadmin@localhost:9002
+ mc admin replicate add site1 site2 site3
Requested sites were configured for replication successfully.
+ sleep 5
+ kill 1698018
+ mc admin replicate remove site1 site2 --force --debug
mc: <DEBUG> PUT /minio/admin/v3/site-replication/remove?api-version=1 HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/2.0.0 mc/DEVELOPMENT.2022-12-17T07-26-04Z
Content-Length: 31
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20221222//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: a5cb41876b41e4e2f3d29e34fb552514123543c344383b8426283eb02a11fedc
X-Amz-Date: 20221222T075559Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 273
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Thu, 22 Dec 2022 07:56:00 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 17330E6FA6F339BD
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  965.097438ms

Following site [site2] was removed partially, some operations failed:
ERROR: 'unable to update peer site2: Put "http://localhost:9001/minio/admin/v3/site-replication/peer/remove?api-version=1": dial tcp 127.0.0.1:9001: connect: connection refused'
```

```
#!/bin/bash

set -x

make install

pkill -9 minio
rm -rf /tmp/minio/

(./minio server /tmp/minio/minio-1 --address ":9000" 2>&1 >/tmp/site1.log)&
site1_pid=$!
(./minio server /tmp/minio/minio-2 --address ":9001" 2>&1 >/tmp/site2.log)&
site2_pid=$!
(./minio server /tmp/minio/minio-3 --address ":9002" 2>&1 >/tmp/site3.log)&
site3_pid=$!

sleep 3

export MC_HOST_site1=http://minioadmin:minioadmin@localhost:9000
export MC_HOST_site2=http://minioadmin:minioadmin@localhost:9001
export MC_HOST_site3=http://minioadmin:minioadmin@localhost:9002

mc admin replicate add site1 site2 site3

sleep 5

kill ${site2_pid}

mc admin replicate remove site1 site2 --force --debug
```

The PR should be complete now.
