### ISSUE TITLE
helm: add policy on svcacct

### ISSUE THREAD

**Issue by orblazer** [minio/minio#16267]
**Is your feature request related to a problem? Please describe.**
When we want create service accounts with custom policy we need use custom command like that :
```sh
admin user svcacct add --access-key "gitlab" --secret-key "<redacted>" \
  --policy "$(echo '{"Statement":[{"Action":["s3:ListBucket","s3:GetObject","s3:DeleteObject","s3:PutObject"],"Effect":"Allow","Resource":["arn:aws:s3:::gitlab-*/*","arn:aws:s3:::git-lfs/*","arn:aws:s3:::tmp/*"]}],"Version":"2012-10-17"}' \
  > policy.json && echo "policy.json")" myminio "admin"
```

**Describe the solution you'd like**
simply add `policy` section with same structure as `policies`

**Describe alternatives you've considered**
- Create 1 user and 1 policy for each service accounts, but that require useless user can be access to console.
- Keep my comand generator

**Comment by harshavardhana** [comment]
Please send a PR @orblazer
