### ISSUE TITLE
Drives per erasure set way smaller than expected

### ISSUE THREAD

**Issue by khalidhameed71** [minio/minio#16268]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Setting up a new cluster with 38 nodes and 12 disks per node. Each disk is of 4TB.
38 x 12 = 456 total disks.

I expected 38 erasure sets of 12 disks each to be created, since 12 is the highest number between 4 and 16 which 456 is evenly divisible by.

## Current Behavior

228 erasure sets with 2 drivers per set are created.

```
●  minio11.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio12.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio13.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio14.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio15.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio16.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio17.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio18.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio19.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio20.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio21.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio22.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio23.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio24.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio25.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio26.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio27.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio28.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio29.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio30.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio31.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio32.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio33.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio34.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio35.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio36.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio37.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio38.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio39.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio40.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio41.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio42.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio43.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio44.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio45.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio46.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio47.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

●  minio48.abc.xyz:9000
   Uptime: 1 minute
   Version: 2022-12-12T19:27:27Z
   Network: 38/38 OK
   Drives: 12/12 OK
   Pool: 1

Pools:
   1st, Erasure sets: 228, Drives per erasure set: 2

```

MinIO Erasure Code Calculator (https://min.io/product/erasure-code-calculator) also seems to break with this configuration and gives the message "Minimum 4 servers are recommended for high availability".
![calculator](https://user-images.githubusercontent.com/66066309/208084976-e4035345-9a97-4327-a5a7-ab9e220975cf.PNG)

## Steps to Reproduce (for bugs)

1. Setup a new cluster using systemd and config file (/etc/default/minio)
2. Start the service on all cluster nodes
3. Check status with **mc admin info** command

## Context

Disk failure tolerance will be reduced.

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```

mc --version:
```
mc version RELEASE.2022-12-13T00-23-28Z (commit-id=4b4cab0441f000db100c5b5d9329221181bf61f2)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

* Server setup and configuration:
MinIO Config File (/etc/default/minio):
```
MINIO_VOLUMES=http://minio{11...48}.abc.xyz/data/minio{01...12}

MINIO_OPTS="--console-address :10000"

MINIO_ROOT_USER=****
MINIO_ROOT_PASSWORD=****

MINIO_PROMETHEUS_AUTH_TYPE="public"
MINIO_PROMETHEUS_URL="http://minio11.abc.xyz:9090"

MINIO_CONFIG_ENV_FILE=/etc/default/minio
```

MinIO running as systemd service. Service file:

```
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/

User=miniosuper
Group=miniosuper
ProtectProc=invisible

EnvironmentFile=/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=1048576

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```

* Operating System and version (`uname -a`):
```
RHEL 8.4
Linux minio11.abc.xyz 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ravindk89** [comment]
Can you do `mc admin info --json` and upload the results here? You can redact PII such as hostnames prior to upload. There's a little more fine-grained detail there for us to look at.

**Comment by khalidhameed71** [comment]
@ravindk89 Sure. Please find attached.

[mc admin info --json.txt](https://github.com/minio/minio/files/10247358/mc.admin.info.--json.txt)

**Comment by harshavardhana** [comment]
Yeah this because of how many drives you have and how many nodes you have.

That are not symmetrically divisible that allows full HA and spread across servers.

Mathematically there is no combination that can provide proper distribution across 38 nodes

Either use 36 or bring one more 39. Using non divisible factors would lead to this behavior. Nodes have to be divisible by erasure stripes 38 is only divisible by 2 and then suddenly it's a prime number 19.

This is why we recommend that for such large deployments you need to take our help via subscription.

Building large for profit deployments must get paid support, otherwise you are basically putting all your users at risk 

- wrong setup without consulting MinIO engineers
- no architecture review, doing things on your own

Please redo your setup, there is nothing to be surprised here. Please reach out to us at https://subnet.min.io/subscribe

**Comment by harshavardhana** [comment]
> I expected 38 erasure sets of 12 disks each to be created, since 12 is the highest number between 4 and 16 which 456 is evenly divisible by.

There is mistake in your understanding, you can't just divide the final number of drives for symmetry. You need your erasure stripes to be divisible by number of nodes as well.

38 is not divisible by 12 so MinIO chooses symmetry that is only 2. You could potentially do an asymmetric setup by forcing the erasure count.

However that will lead to more disks per node participating than the others leading to incorrect network and drive performance utilization.

This is why we always repeatedly convey that please come to us for help via proper channels.

**Comment by ravindk89** [comment]
I'll revisit the docs on this, based on a quick reading. We had language at one point talking about how nodes play into the calculation, but removed it because it was complicated to fully conceptualize.

What we have [right now](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html) is intended as a simple guidance, but I think it's not helping. I'm going to remove all references to the specific logic for now, until we can make a proper breakdown of the logic (maybe with diagrams). We have the erasure code calculator, but it's not unreasonable for users to want to understand the _how_ a little more.
