### ISSUE TITLE
Security issue Server-Side 

### ISSUE THREAD

**Issue by williamaurreav23** [minio/minio#16270]
In a version RELEASE.2022-10-24T18-35-07Z y console V0.21.2  found a issue relative to the security. a possible door that allow the attackers filter using a tools like that allowed the posible doors . 
the situations happends when in our enviroment validate a posibble security issues and the results was the version that we build in our own server  have this 
the issue consist in when you sen a request using res api services in http://host/api/v1/configs/identity_openid
and in the values pass a cookie like this 
headers         value 
cookie           token:cookie token    
and passing this parameters
{"key_values":[
{"key":"config_url","value":"http://127.0.0.1"},
{"key":"client_id","value":"fghjnkm"},
{"key":"client_secret","value":"dfgcvhbjnk"},
{"key":"claim_name","value":"policy"},
{"key":"claim_prefix"},
{"key":"claim_userinfo"},
{"key":"redirect_uri"},
{"key":"scopes"}
]}

**Comment by harshavardhana** [comment]
> In a version RELEASE.2022-10-24T18-35-07Z y console V0.21.2 found a issue relative to the security. a possible door that allow the attackers filter using a tools like that allowed the posible doors . the situations happends when in our enviroment validate a posibble security issues and the results was the version that we build in our own server have this the issue consist in when you sen a request using res api services in http://host/api/v1/configs/identity_openid and in the values pass a cookie like this headers value cookie token:cookie token and passing this parameters {"key_values":[ {"key":"config_url","value":"http://127.0.0.1"}, {"key":"client_id","value":"fghjnkm"}, {"key":"client_secret","value":"dfgcvhbjnk"}, {"key":"claim_name","value":"policy"}, {"key":"claim_prefix"}, {"key":"claim_userinfo"}, {"key":"redirect_uri"}, {"key":"scopes"} ]}

What a vague security report, please read how to report security issues properly.

You are not saying anything in this issue report.

Please come back with something more concrete then we can guide you.
