### ISSUE TITLE
Can the production environment delete objects quickly?

### ISSUE THREAD

**Issue by PanErheng** [minio/minio#16274]
## NOTE
Because the storage in the production environment is full, but I use the mc rm prd/images -- force - r command to execute too slowly, and the deletion speed is not as fast as the writing speed. Do I have a good method, or can I delete the files on the disk directly?

## Your Environment

* Version used (`minio --version`):mini: RELEASE 2022-05-26T05-48-41Z
* Server setup and configuration:48 cores, 32G memory
* Operating System and version (`uname -a`):Linux mini185 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker warm environment, and 4-node cluster. Now there are about 10 million storage objects

**Comment by harshavardhana** [comment]
@PanErheng all performance related stuff and architecture reviews are part of paid subscription. Feel free to sign up https://subnet.min.io/subscribe 

Also please upgrade to latest release.
