### ISSUE TITLE
Prometheus : server healing metrics

### ISSUE THREAD

**Issue by broferek** [minio/minio#16276]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

All healing metrics are different for each server. Unfortunately, when calling /minio/v2/metrics/cluster endpoint, Prometheus only retrieves the number for the server where the API call is done.

## Expected Behavior

Let's say my pool is made up of 2 servers (minio-01 and minio-02).

For instance, for minio_heal_objects_total, I would expect
```
minio_heal_objects_total{server="minio-01:9000",type="object"} 1.225772e+06
minio_heal_objects_total{server="minio-02:9000",type="object"} 1973
```

## Current Behavior

At the moment, I only have the metrics of minio-01 if it is the one which is configured in my Prometheus config.

## Possible Solution

Report the metrics for each server in the pool as it is already done for many metrics such as

```
minio_s3_time_ttfb_seconds_distribution{api="putobjectpart",le="10.000",server="minio-01:9000"} 1907
minio_s3_time_ttfb_seconds_distribution{api="putobjectpart",le="10.000",server="minio-02:9000"} 275
minio_s3_time_ttfb_seconds_distribution{api="putobjectpart",le="2.500",server="minio-01:9000"} 1907
minio_s3_time_ttfb_seconds_distribution{api="putobjectpart",le="2.500",server="minio-02:9000"} 275
minio_s3_time_ttfb_seconds_distribution{api="putobjectpart",le="5.000",server="minio-01:9000"} 1907
minio_s3_time_ttfb_seconds_distribution{api="putobjectpart",le="5.000",server="minio-02:9000"} 275
```
## Steps to Reproduce (for bugs)

1. Make an API call to /minio/v2/metrics/cluster for a given server
2. Note that healing metrics are only returned for the server where the API call is done

## Context

I'm trying to get a per server view of the healing metrics by only making one API call instead of getting this information from each node making up the pool which would end up in having a lot of duplicate metrics.

## Regression
 No

## Your Environment

* Version used (`minio --version`): RELEASE.2022-11-26T22-43-32Z
* Server setup and configuration: Podman container 
* Operating System and version (`uname -a`): Rocky 9

**Comment by harshavardhana** [comment]
We will fix this ..

**Comment by broferek** [comment]
Thanks @harshavardhana, really looking forward to getting it fixed

I wanted to add that you could also take a look at `minio_cluster_disk_online_total`.

I came across this strange case where a disk was reported as down when calling a particular server and not from another.

I was expecting the metric to give an overall status of the cluster. But that doesn't seem to be the case.

So it might be useful to output the metric for each node in the pool as well.

**Comment by harshavardhana** [comment]
@broferek disk offline discrepancy is already fixed, you would have to upgrade.

**Comment by broferek** [comment]
ok I'll do it

**Comment by harshavardhana** [comment]
@vadmeste we need to bring clustered view for healing metrics
