### ISSUE TITLE
XL/fs: Implement comprehensive unit tests for multipart upload.

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1628]
multipart unit tests:
- complete multipart upload with unsorted parts should give error
- complete multipart with one of the parts less than 5mb (which is not the last one) should give error

data integrity tests: (https://github.com/minio/minio/issues/1580 https://github.com/minio/minio/issues/1582)
create 10MB file using multipart
- verify if md5sum matches for the entire file
- verify if md5sum matches for range 5MB+1byte to `eof`
- verify if md5sum matches for 10MB-1byte to `eof`

**Comment by harshavardhana** [comment]
Implement tests for 
- ListsMultipartUpload - for all cases including marker and upload-id-marker.
- ListMultipartObjectParts - for all cases with part-number-marker.

**Comment by hackintoshrao** [comment]
@harshavardhana : Please add In progress label.

**Comment by hackintoshrao** [comment]
@krishnasrinivas : Complete multipart tests are ready, just adding more cases, Case for PartSize less than 5Mb done.

**Comment by hackintoshrao** [comment]
10th June.

**Comment by hackintoshrao** [comment]
@harshavardhana : Can you close this issue. I'll open an issue just for AbortMultipart.
