### ISSUE TITLE
Post "{Minio Server URL}": dial tcp {IP ADDRESS}:443: i/o timeout on Multi-node/Multi-drive installation with LB

### ISSUE THREAD

**Issue by treatys** [minio/minio#16299]
Hello I previously used HAProxy as loadbalancer. After getting
`Post "https://gos1.storage.getmedia.network/": dial tcp 185.64.219.119:443: i/o timeout`
I switched to Nginx (due to more documentation resources). I am also using Nginx for TLS termination. As it’s used with Keepalived, I configured glusterfs volume for storing Letsencrypt certs. Certbot generates certificates in standalone mode on separate VM using proxy. Certificate lifecycle works fine…

The problem is I cannot log into Minio using proxy. If I use mc to log into single host, it works fine. I cannot log into the cluster using the loadbalancer.

I need to achieve a fully HA environment for my object storage. As I used HAProxy as well as Nginx, I suppose this is a general problem with loadbalancing.

## Expected Behavior
To log into the MinIO cluster via Loadbalanced URL.

## Current Behavior
`Post "https://gos1.storage.getmedia.network/": dial tcp 185.64.219.119:443: i/o timeout` while trying to log in the console.

I cannot reach cluster via `mc` command while I use Loadbalanced URL. While I try connect directly to cluster member, I am able to reach it.

## Possible Solution
I expect my Nginx is missing some headers. I followed tutorials and official documentation site.

## Steps to Reproduce (for bugs)
1. Install a MinIO Server in Multi-node/Multi-drive configuration
2. Try to login via `mc` or MinIO Console

## Context
I am trying to establish HA cluster solution for my applications. As loadbalancing does not work, it is not usable for our use case.

## Your Environment

* Minio version: 
```
minio version RELEASE.2022-12-07T00-56-37Z (commit-id=04ae9058ed5b135c27a3662b1153e129e5cf1483)
Runtime: go1.19.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```
* OS version: `Linux gmc1019 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux`
* Hostnames are mapped via `/etc/hosts`

**MinIO config:**
```
MINIO_ACCESS_KEY="XXXXXXX"
MINIO_VOLUMES="http://gos1/-{1...4}.storage.getmedia.network:9000/mnt/minio-drive-{1...4}/minio"
MINIO_OPTS="-C /etc/minio --address 0.0.0.0:9000 --console-address 0.0.0.0:9001"
MINIO_SECRET_KEY="XXXXXXX"
MINIO_SERVER_URL="https://gos1.storage.getmedia.network/"
MINIO_BROWSER_REDIRECT_URL="https://console.gos1.storage.getmedia.network/"
MINIO_ROOT_USER="XXXXXX"
MINIO_ROOT_PASSWORD="XXXXXX"
```

**Nginx site config:**
```
upstream gos1_server {
	server gos1-1.storage.getmedia.network:9000;
	server gos1-2.storage.getmedia.network:9000;
	server gos1-3.storage.getmedia.network:9000;
	server gos1-4.storage.getmedia.network:9000;	
}

upstream gos1_console {
	ip_hash;
	server gos1-1.storage.getmedia.network:9001;
	server gos1-2.storage.getmedia.network:9001;
	server gos1-3.storage.getmedia.network:9001;
	server gos1-4.storage.getmedia.network:9001;
}

server {
	listen       80;
	listen  [::]:80;
	server_name  gos1.storage.getmedia.network;

	include snippets/certbot.conf;
	include snippets/minio_host.conf;

	include snippets/force-https.conf;
	include snippets/enable-https.conf;
	include snippets/autowire-certs.conf;

	location / {
		include snippets/minio_server_loc.conf;

		proxy_pass http://gos1_server/;
	}
}

server {
	listen       80;
	listen  [::]:80;
	server_name  console.gos1.storage.getmedia.network;

	include snippets/certbot.conf;
	include snippets/minio_host.conf;

	include snippets/force-https.conf;
	include snippets/enable-https.conf;
	include snippets/autowire-certs.conf;

	location / {
		include snippets/minio_console_loc.conf;

		proxy_pass http://gos1_console/;
	}
}

server {
	listen       9000;
	listen  [::]:9000;
	server_name  _;

	include snippets/minio_host.conf;

	location / {
		include snippets/minio_server_loc.conf;

		proxy_pass http://gos1_server/;
	}
}

server {
	listen       9001;
	listen  [::]:9001;
	server_name  _;

	include snippets/minio_host.conf;

	location / {
		include snippets/minio_console_loc.conf;

		proxy_pass http://gos1_console/;
	}
}
```

**minio_host.conf** snippet:
```
ignore_invalid_headers off;
client_max_body_size 0;
proxy_buffering off;
proxy_request_buffering off;
```

**minio_server_loc.conf** snippet:
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

proxy_read_timeout 300;
proxy_send_timeout 300;
proxy_connect_timeout 300;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
chunked_transfer_encoding off;
```

**minio_console_loc.conf** snippet:
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-NginX-Proxy true;

real_ip_header X-Real-IP;

proxy_connect_timeout 300;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

chunked_transfer_encoding off;
```

**Comment by treatys** [comment]
Turns out I missconfigured firewall on our cluster and forget to enable hair pinning. Works fine now!

**Comment by harshavardhana** [comment]
> Turns out I missconfigured firewall on our cluster and forget to enable hair pinning. Works fine now!

🍰
