### ISSUE TITLE
Request an Range of a object causes very high IO load

### ISSUE THREAD

**Issue by hobbut** [minio/minio#16324]
## NOTE

I'm experiencing very high I/O load when i'm requesting more than 1.1MB chunk from the object.

## Expected Behavior
I/O load shouldn't be so high and the amount data read should be closer to the amount data served to user.

## Current Behavior
For 10000 requests of 1.1MB each (11GB data) For 11GB data received minio read from disks 235GB of data.
x21 read amplification
![image](https://user-images.githubusercontent.com/563097/209820897-e2abef1d-55eb-4a44-9321-f0906c468ae5.png)

## Steps to Reproduce (for bugs)

1. Upload 1GiB object to bucket
2. Run ab with Range header -H"Range: bytes=1-1100000" `ab -c32 -n10000 -H"Range: bytes=1-1100000" http://minio.test.server/test-bucket/1G`
3. Monitor IO on minio nodes. I used iotop `iotop -a -P -t | grep minio` to see accumulated I/O for minio process on each server

## Your Environment

* 4 servers with 8x1TB SSD disks. Minio running in container on each server
* minio version DEVELOPMENT.2022-12-07T00-56-37Z (commit-id=04ae9058ed5b135c27a3662b1153e129e5cf1483)
Runtime: go1.18.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
* `Linux as11 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@hobbut this is normal, MinIO is an erasure coded system and there is always more to read to erasure decode.

You are asking for a range many concurrent times and many times over. Each of these reads() do need an X amount of shards to fill-fill the request.

There is nothing surprising here. Also why are you compiling your own binaries please use officially published ones.

**Comment by harshavardhana** [comment]
To know all the calls that happen on the disk do 

```
mc admin trace -a --funcname os* --funcname storage* alias/
```

**Comment by hobbut** [comment]
@harshavardhana I also tried with the officially published binary. The results are same

```
minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```

There is not problem with `Range: bytes=1-1048574` 2.9GB data read on each node
But starting with `Range: bytes=1-1048575` there is the problem. 58.75GB IO on each node for the same benchmark

`ab -c32 -n10000 -H"Range: bytes=1-1048574" http://server/test-bucket/1G_nochunks/1G`
![image](https://user-images.githubusercontent.com/563097/209921345-a03a72eb-24df-4e37-bd75-9a9b9c6d475b.png)

`ab -c32 -n10000 -H"Range: bytes=1-1048575" http://server/test-bucket/1G_nochunks/1G`
![image](https://user-images.githubusercontent.com/563097/209921145-da79086e-53c9-483a-9044-65f25242b63c.png)
