### ISSUE TITLE
Site Replication Resuming doesn't work when the secondary MinIO have failed about 10min and recovered

### ISSUE THREAD

**Issue by next0262** [minio/minio#16339]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

I built Primary MinIO Cluster(4 servers / 4 disks) and Secondary MinIO Cluster(4 servers / 4 disks) and applied site replication between them. While replicating, i injected failures to Secondary's 4 minio servers about 10min and recovered. I expected that the recovered 4 minio servers of Secondary will continue to run that replication (As minio doc. mentioned, the scanner will detect it and resume that replication on the recovered secondary).  

## Current Behavior

However, it is totally hanged and stopped. It didn't resume on the failed objects (2.0GiB)

root@sre-6-19:/home/sre/wjkim/chaos-mesh# mc replicate status minio1/test2
Summary:
Replication Status    | Size (Bytes)    | Count
   Failed             | 2.0 GiB         | 2
   Replicated         | 1.8 GiB         |
   Replica            | 0 B             |

Remote Target Statuses:
● arn:minio:replication::28214266-6eae-4001-a049-4550a606825e:test2
Replication Status    | Size (Bytes)    | Count
   Failed             | 2.0 GiB         | 2
   Replicated         | 1.8 GiB         |

root@sre-6-19:/home/sre/wjkim/chaos-mesh# mc replicate diff minio1/test2
[2022-12-31 08:57:30 UTC] [2022-12-31 08:54:18 UTC] FAILED   dea4fc6f-c6fb-405f-af2a-5fb765906ab0 PUT seq1_1_1024M_file
[2022-12-31 08:52:09 UTC] [2022-12-31 08:55:19 UTC] PENDING  9bdabb35-da9f-49be-8d18-25ae555c7eed PUT seq1_1_2048M_file
[2022-12-31 08:57:29 UTC] [2022-12-31 08:54:18 UTC] FAILED   927d3fea-9666-4225-8e76-d81ca53ebb48 PUT seq1_2_1024M_file
[2022-12-31 08:52:09 UTC] [2022-12-31 08:55:19 UTC] PENDING  16f65880-61ee-4207-aca6-1a168be15811 PUT seq1_2_2048M_file

Errors of primary minio servers  (I think it has a lock problem)
- Error : failed to get lock for object: seq1_1_2048M_file bucket:test2 arn

I already did the solutions mentioned in followings, but they didn't work:

Site Healing
Any MinIO deployment in the site replication configuration can resynchronize damaged [replica-eligible data](https://min.io/docs/minio/linux/operations/install-deploy-manage/multi-site-replication.html#minio-site-replication-what-replicates) from the peer with the most updated (“latest”) version of that data.

Changed in version RELEASE.2022-08-11T04-37-28Z: Failed or pending replications requeue automatically when performing any GET or HEAD API method. For example, using [mc stat](https://min.io/docs/minio/linux/reference/minio-mc/mc-stat.html#command-mc.stat), [mc cat](https://min.io/docs/minio/linux/reference/minio-mc/mc-cat.html#command-mc.cat), or [mc ls](https://min.io/docs/minio/linux/reference/minio-mc/mc-ls.html#command-mc.ls) commands after a site comes back online prompts healing to requeue.

Changed in version RELEASE.2022-12-02T23-48-47Z: If one site loses data for any reason, resynchronize the data from another healthy site with [mc admin replicate resync](https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-replicate.html#mc.admin.replicate.resync). This launches an active process that resynchronizes the data without waiting for the passive MinIO scanner to recognize the missing data.

https://blog.min.io/multi-site-replication-resync/

## Possible Solution

- The solution i found is restarting all servers of Primary. Then, it resumes that replication. but it still has the problem that the replicate status of secondary is changed inconsistently whenever i request like this:

root@sre-6-19:/home/sre/wjkim/chaos-mesh# mc replicate status minio1/test2
Summary:
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 11 GiB          |
   Replica            | 0 B             |

Remote Target Statuses:
● arn:minio:replication::28214266-6eae-4001-a049-4550a606825e:test2
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 6.0 GiB         |

● arn:minio:replication::5fdf45b3-d1fe-48ad-ab8f-fd84903688b8:test
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 3.9 GiB         |

● arn:minio:replication::600887b7-69e3-4026-892b-c514578798cd:test
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 781 MiB         |
root@sre-6-19:/home/sre/wjkim/chaos-mesh# mc replicate status minio1/test2
Summary:
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 7.8 GiB         |
   Replica            | 0 B             |

Remote Target Statuses:
● arn:minio:replication::28214266-6eae-4001-a049-4550a606825e:test2
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 7.8 GiB         |

root@sre-6-19:/home/sre/wjkim/chaos-mesh# mc replicate status minio1/test2
Summary:
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 11 GiB          |
   Replica            | 0 B             |

Remote Target Statuses:
● arn:minio:replication::28214266-6eae-4001-a049-4550a606825e:test2
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 6.0 GiB         |

● arn:minio:replication::5fdf45b3-d1fe-48ad-ab8f-fd84903688b8:test
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 3.9 GiB         |

● arn:minio:replication::600887b7-69e3-4026-892b-c514578798cd:test
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 781 MiB         |

root@sre-6-19:/home/sre/wjkim/chaos-mesh# mc replicate status minio1/test2
Summary:
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 7.8 GiB         |
   Replica            | 0 B             |

Remote Target Statuses:
● arn:minio:replication::28214266-6eae-4001-a049-4550a606825e:test2
Replication Status    | Size (Bytes)    | Count
   Failed             | 0 B             | 0
   Replicated         | 7.8 GiB         |

## Steps to Reproduce (for bugs)

1. Provision Primary MinIO Cluster & Secondary MinIO Cluster
2. Apply site replication between them
3. While replicating, inject failure on Secondary about 10 min and recover
4. check if this replication resumes automatically, but it doesn't work

## Your Environment

* Version used (`minio --version`): minio:RELEASE.2022-09-22T18-57-27Z
* Server setup and configuration: primary 4 servers/4disks ----------site replication---------- secondary 4 servers/4disks
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@next0262 please upgrade and redo your tests - we have fixed a bunch of things in resyncing and site-recovery.

**Comment by next0262** [comment]
@harshavardhana  could you let me know from which version this issue is resolved?? I don't want to change my version too much

**Comment by harshavardhana** [comment]
> @harshavardhana could you let me know from which version this issue is resolved?? I don't want to change my version too much

@next0262 as a community user you should be upgrading always for bug-fixes, if you are looking for long term support for your deployment you should be looking for support subscription with us https://min.io/pricing

**Comment by harshavardhana** [comment]
Closing this since there has been major fixes that cover the disaster recovery scenario for site-replication.
