### ISSUE TITLE
bug:  panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by youtehub** [minio/minio#16336]
Operating system: ubuntu 20.04

Software: alist rclone minio

This error was reported when minio was running.

Principle: After using rclone to mount webdav, as the local hard disk of ubuntu, put a separate folder of rclone mounted disk into the running directory of minio for external access. When minio starts up normally, it is identified as a bucket

![image](https://user-images.githubusercontent.com/18629921/210150971-07c14f32-9202-4820-a754-fd17fa6d8e87.png)

What is stored on the web disk is the original file processed by minio after being uploaded locally. minio is used here to restore the file mounted to the local disk to a video file，minio acts as a file - to - file restorer

![image](https://user-images.githubusercontent.com/18629921/210151235-64cc583c-9397-4f04-8a13-fa509d327c96.png)
![image](https://user-images.githubusercontent.com/18629921/210151244-1de0c6e0-7cb1-40d6-a4ee-2e0c383a46e2.png)
![image](https://user-images.githubusercontent.com/18629921/210151261-346ca06d-7845-487a-aaa0-e896aa9e0625.png)

In a nutshell, this error was caused by mounting a network drive. Although mounting a network drive is not officially recommended, it is required to do so in conjunction with rclone's implementation

rclone: [Mount a webdav share with Rclone on FreeBSD](https://blog.socruel.nu/freebsd/mount-webdav-with-rclone-on-freebsd.html)

panic: runtime error: index out of range [1] with length 1

goroutine 759 [running]:
github.com/minio/minio/cmd.shuffleDisksAndPartsMetadata({_, _, _}, {_, _, _}, {{0xc00164cb81, 0x7}, {0xc0005d0ac0, 0x3a}, ...})
	github.com/minio/minio/cmd/erasure-metadata-utils.go:269 +0x3e5
github.com/minio/minio/cmd.shuffleDisksAndPartsMetadataByIndex({_, _, _}, {_, _, _}, {{0xc00164cb81, 0x7}, {0xc0005d0ac0, 0x3a}, ...})
	github.com/minio/minio/cmd/erasure-metadata-utils.go:241 +0x189
github.com/minio/minio/cmd.erasureObjects.getObjectWithFileInfo({0x1, 0x0, 0x0, 0x0, 0xc001462c90, 0xc001462ca8, 0xc001462cc0, 0xc001462c30, 0xc001462c48, 0xc001462c60}, ...)
	github.com/minio/minio/cmd/erasure-object.go:294 +0xca
github.com/minio/minio/cmd.erasureObjects.GetObjectNInfo.func5()
	github.com/minio/minio/cmd/erasure-object.go:279 +0x154
created by github.com/minio/minio/cmd.erasureObjects.GetObjectNInfo
	github.com/minio/minio/cmd/erasure-object.go:278 +0x13fe

**Comment by klauspost** [comment]
It is not very clear what you have done here. It seems like the file was written with one minio setup and then the backend files were transferred to another.

You are not are not allowed to copy or modify the backend files in any way. This is unsupported and not possible. Please refer to our [documentation](https://min.io/docs/minio/kubernetes/upstream/) for proper usage.

If I am wrong, please share an exact reproducer with each step you performed to get to this state.

**Comment by youtehub** [comment]
Thank you for your answer, the problem seems to be here, the array is out of bounds for a special reason,
![image](https://user-images.githubusercontent.com/18629921/210152296-5137702f-2920-4374-b60c-b1cb317ae9b0.png)
