### ISSUE TITLE
integrated virus scan?

### ISSUE THREAD

**Issue by harridu** [minio/minio#16349]
I'd love to replace nextcloud by minio as our upload and download server. Problem: Scanning for viruses and malware seems to require a notification mechanism to an external service doing the job. Error-prone. Painful. No sample implementation available. And it might collide with the integrated encryption, AFAICT.

Would it be possible to integrate an optional virus scan during upload?

Actually I thought I am not the first one asking for such a feature, but looking at the closed issues on github I haven't found similar requests before. Hopefully I wasn't too blind to see.

**Comment by harshavardhana** [comment]
@harridu scanning for anti viruses is an external job.

You first scan and then upload if it's not a virus. There is nothing MinIO needs to do here.
