### ISSUE TITLE
XL: Multiple meta data files may cause version confusion

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1635]
Currently XL stores various meta data into independent different files eg. multipart information is stored into separate JSON file, EC information are stored in separate JSON file and proposed other meta data will be stored in meta.json.

As we use quick to store each json file which uses separate independent version numbers.  Whereas we would need to use top level version in XL code which is also versioned.

**Comment by harshavardhana** [comment]
> As we use quick to store each json file which uses separate independent version numbers. Whereas we would need to use top level version in XL code which is also versioned.

We don't use quick for internal XL operations, we just use simple unmarshalling and marshalling.

**Comment by GarimaKapoor** [comment]
Bala, Can you update the timeline of the fix.

**Comment by balamurugana** [comment]
This bug is a place holder to indicate how XL config files are stored in the backend.  Hence there is no direct fix available.

**Comment by harshavardhana** [comment]
With the new design we have reduced this to 3 files which carry the versioning from `format.json`, closing  not relevant anymore.
