### ISSUE TITLE
XL: data corruption/loss may happen if underlying disks are renamed - May 20th

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1636]
Its known that physical disks may named different on each run of operating system especially in GNU/Linux, eg. a device `sdi` may appear as `sdk` in next reboot.

In a system where UUID of disk file system is not used in fstab or mount command to mount such disks may lead XL to place data in a wrong set of disk order.  This will lead to data corruption and loss.

This needs to be fixed.

**Comment by GarimaKapoor** [comment]
Please update the timeline.
