### ISSUE TITLE
XL : Timeout during high concurrent load. - May 19th

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1637]
When [exec-concurent.go](https://gist.github.com/hackintoshrao/6f821cc7185e39cce3733c138390fc29) executed at concurrency set to 500 resulting in tests being failed due to timeout of multiple operations.

**Comment by harshavardhana** [comment]
@hackintoshrao can you attach blocking profile output here for review?

**Comment by hackintoshrao** [comment]
Sure.

**Comment by hackintoshrao** [comment]
Block profiles reveal that locking is consuming lot of much of time, which is inevitable for now. 
[150block-2.pdf](https://github.com/minio/minio/files/267291/150block-2.pdf)

**Comment by harshavardhana** [comment]
> Block profiles reveal that locking is consuming lot of much of time, which is inevitable for now. 
> 150block-2.pdf

The interesting observation here is that the calls for MakeBucket are not fast enough , this can be really reduced to a smaller value with a simple change. 

```
 sync.(*Mutex).Lock 91.87mins(17.78%)
```

**Comment by harshavardhana** [comment]
This is a fixed problem now, closing.. Will re-open if seen again.
