### ISSUE TITLE
rotate secrets of serviceaccount

### ISSUE THREAD

**Issue by farodin91** [minio/minio#16377]
**Is your feature request related to a problem? Please describe.**
I would like to rotate secrets of serviceaccount.

**Describe the solution you'd like**
1. set a lifetime (for example 3months) on creation of a serviceaccount 
2. use serviceaccount
3. after sometime, create new serviceaccount with lifetime
4. old service account gets disable or removed after end of lifetime

**Comment by harshavardhana** [comment]
For that you have something called as STS that expire based on DurationSeconds @farodin91 https://github.com/minio/minio/tree/master/docs/sts
