### ISSUE TITLE
expired object still remain on disk 

### ISSUE THREAD

**Issue by zhousbo** [minio/minio#16373]
Hello 
I have distributed minio, with 6 nodes.  Every node has 12 disk ,each disk  6TB 

The bucket configured ilm policy, that will expired after 90 days, and not configured versioned objects.

we found that the objects disappered in bucket when we use command mc ls minio/bucket/ 

but we can find the object on the local disk , the minio seems doesn't delete versioned objects .

## Expected Behavior
when objects expired ,it should delete both in buckets and local disk

## Current Behavior
objects delete in buckets ,but not delete on disk

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-05-08T23-50-31Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux nma07-302-j18-sev-r4900-2u33 5.4.210-1.el7.elrepo.x86_64 #1 SMP Tue Aug 9 17:41:27 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@zhousbo what you are saying is not possible, also please upgrade to latest when reporting issues. You are using 6 months old version.

**Comment by zhousbo** [comment]
Use command "mc rm --force --recursive --dangerous --versions  minio/bucket/" and the objects finally deleted.

**Comment by ravindk89** [comment]
@zhousbo - if you have a versioned bucket + an expiration rule, but that expiration rule does not contain any `noncurrentversion-expiration` behaviors - then what you are describing is expected and as per S3 spec.

Expiration in a versioned bucket starts by creating a delete marker. If you have no further rules on noncurrent versions, then the data will 'disappear' from listing, but otherwise remain behind.

It might be worth double checking your ILM rules.

**Comment by krisis** [comment]
@zhousbo If you still have the setup intact, could you share the output of the following commands,
1.  `mc version info minio/bucket` - to know if versioning is enabled on this bucket.
2. `mc ilm export minio/bucket` - to know more about the ILM policy configured on this bucket
3. `mc stat minio/bucket/object` - where `object` is one of the objects which should have expired but hasn't yet.

**Comment by zhousbo** [comment]
> 
1. The bucket is un-versioned 
mc version info voice/voice-data/
voice/voice-data/ is un-versioned

3. Because these ilm policy not working, so, I delete it , 
{"Rules":[{"Expiration":{"Days":90},"ID":"voiceData","Status":"Enabled"},{"Expiration":{"Days":60},"ID":"celbgkp2fhf0to57udp0","Filter":{"Prefix":"AUDIO/DX/AH/"},"Status":"Enabled"},{"Expiration":{"Days":60},"ID":"celbhk12fhf15tm90rs0","Filter":{"Prefix":"AUDIO/DX/GD/"},"Status":"Enabled"},{"Expiration":{"Days":60},"ID":"celbhl92fhf1479lkj7g","Filter":{"Prefix":"AUDIO/DX/JS/"},"Status":"Enabled"},{"Expiration":{"Days":60},"ID":"celbhm12fhf14hlmpqbg","Filter":{"Prefix":"AUDIO/DX/JX/"},"Status":"Enabled"},{"Expiration":{"Days":60},"ID":"celbhmp2fhf14r5rqeg0","Filter":{"Prefix":"AUDIO/DX/SH/"},"Status":"Enabled"},{"Expiration":{"Days":60},"ID":"celbhnh2fhf14u93anl0","Filter":{"Prefix":"AUDIO/DX/ZJ/"},"Status":"Enabled"}]}
4. The expired Object disapperd in the bucket, so, I can't stat it. I tried to stat objects which not expired , the attr seems normal.

**Comment by krisis** [comment]
@zhousbo Yes, `mc stat` does expire obejcts past their expiry, if they haven't yet been removed. Could you share the `xl.meta` (metadata) file of an object which hasn't been expired as expected. e.g if the object was `voice-data/AUDIO/DX/AH/obj-1` in the bucket `voice`, the corresponding metadata file can be found at `/minio_drive_mount_point/voice/voice-data/AUDIO/DX/AH/obj-1/xl.meta`. Replace `minio_drive_mount_point` with the path where the drives on MinIO nodes are mounted at.

**Comment by harshavardhana** [comment]
Please reach out with relevant information @zhousbo, we will close tracking this issue on our end.
