### ISSUE TITLE
issue in connecting with minio client through port number

### ISSUE THREAD

**Issue by pawar-kapil** [minio/minio#16371]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I recently mapped my minio server API IP to a domain. Before this I used to connect to the minio client in the following manner till very recently:
`
const mc = new minio.Client({
  endPoint: "xx.yy.zz.oo",
  port: 9003,
  useSSL: false,
  accessKey: "xxxxxxxxxxxxxx",
  secretKey: "xxxxxxxxxxxxxxxxxxxxxxxx",
});
`

but now, if I try to connect like this (with the domain as endpoint, instead of IP) the `?location` call gets stuck (screensshot attached)
<img width="718" alt="Screenshot 2023-01-06 at 2 42 38 AM" src="https://user-images.githubusercontent.com/118595994/210881482-d3605f30-81a9-4a53-a7ae-9880656a33b1.png">

if I try without the port number, then the `?location` call gives `302 Moved Temporarily` response status. And although the `getObject` call finally gets through successfully, but first time this also results in  `302 Moved Temporarily` response. (screensshot attached)
<img width="611" alt="Screenshot 2023-01-06 at 2 45 18 AM" src="https://user-images.githubusercontent.com/118595994/210881899-128bc064-d32b-46a8-a2e0-b0b8767aa21a.png">

## Expected Behavior
the call should go through successfully with the port number

## Current Behavior
the call goes through successfully without the port number, although after returning `302 Moved Temporarily` response first.

## Steps to Reproduce (for bugs)

1. map the server API IP to a domain.
2. try connecting with minio client through the domain

## Context
It results in too many 302 responses

## Your Environment

* minio 7.0.32
* React 18:
* mac

**Comment by harshavardhana** [comment]
@pawar-kapil it looks like your S3 endpoint expects a region based endpoint

This is nothing to do with MinIO SDK.
