### ISSUE TITLE
Make Docker images available in the AWS ECR Public Gallery

### ISSUE THREAD

**Issue by gmeligio** [minio/minio#16381]
**Is your feature request related to a problem? Please describe.**
Hello. It would be great if the official MinIO Docker image was available in AWS ECR Public. I'm using AWS for many projects and prefer using the ECR registry to the Docker Hub because of all the integrations within AWS. Thank you.

**Describe the solution you'd like**
1. Create a `minio` public registry alias in AWS ECR ([AWS Documentation](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registry-settings.html))
2. Push Docker images to AWS ECR Public ([Amazon ECR login GitHub action](https://github.com/aws-actions/amazon-ecr-login), [Docker push Github Action](https://github.com/docker/build-push-action))

**Describe alternatives you've considered**
I'm using https://gallery.ecr.aws/bitnami/minio, which is updated often.

**Additional context**
1. [Higher limits in general, in particular, higher pull rate limits than Docker Hub](https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html)
1. [Security features of AWS ECR Public ](https://docs.aws.amazon.com/AmazonECR/latest/public/security-iam.html)

**Comment by harshavardhana** [comment]
@gmeligio please use quay.io/minio/minio there are no such limits.

Will check out ECR

**Comment by gmeligio** [comment]
Thank you, @harshavardhana. It helps using quay.io to increase pull rate limits. I switched to that registry. If you can still consider AWS ECR Public would be even better for my case.

**Comment by harshavardhana** [comment]
We discussed internally, quay.io/minio/minio:latest works for everyone if you have docker pull limits - AWS ECR requires AWS (cloud) access for us to push - we really don't want to perpetuate that.

**Comment by gmeligio** [comment]
Thank you for considering it @harshavardhana . I understand your decision and I will continue using quay.io
