### ISSUE TITLE
XL: writeErasure consumes 66% of memory

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#1638]
writeErasure consumes 66% of memory, is it expected?

I observed this during 1 GB of `mc cp` file transfer. 

Here is the memory profiler file. 
[aa.pdf](https://github.com/minio/minio/files/264096/aa.pdf)

**Comment by harshavardhana** [comment]
From the pdf out of total used 5.8MB

```
5871.86kB of 6165.96kB total (95.23%)
```

writeErasure is using 4MB

```
main.XL.writeErasure 4096kB(66.43%)
of 4116.26kB(66.76%)
```

This the right amount that we expect at any given point in time with in erasure code. 
Closing this bug as it's not a memory issue.
