### ISSUE TITLE
Allow MinIO to run as a brew service

### ISSUE THREAD

**Issue by timgent** [minio/minio#16382]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

After updating I'm unable to run `minio` as a brew service.

## Expected Behavior
`brew services list` to show minio, and allow starting/stopping etc

## Current Behavior
```bash
brew services start minio
Error: Formula `minio` has not implemented #plist, #service or installed a locatable service file
```

## Context
Makes it harder for people to get setup with minio locally

## Regression
Yes, but I don't know what version I had before that worked with `brew services`

## Your Environment
Installed minio with `brew install minio/stable/minio`
* Version used (`minio --version`):
```
minio version RELEASE.2023-01-02T09-40-09Z (commit-id=1cd8e1d8b633550e18a108a0f042941afab6e923)
Runtime: go1.19.4 darwin/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration: Just uses defaults
* Operating System and version (`uname -a`):
```
Darwin tim-gs-mbp.lan 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
```

**Comment by sanju-naik** [comment]
@harshavardhana Based on the discussion in this thread - https://github.com/minio/minio/issues/3564 , seemed like we should be able to run minIO as brew service, i.e running `brew services start minio` , but it still throws the error mentioned in this issue. 

`Error: Formula `minio` has not implemented #plist, #service or installed a locatable service file`

So is running minIO as brew service not supported yet?

**Comment by timgent** [comment]
In case it's helpful I used this to set it up as a service manually:

`/opt/homebrew/Cellar/minio/RELEASE.2023-02-10T18-48-39Z_1/homebrew.mxcl.minio.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.minio</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/bin/minio</string>
		<string>server</string>
		<string>~/.minio/</string>
		<string>--address=:9000</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/opt/homebrew/var/log/minio.log</string>
	<key>StandardOutPath</key>
  <string>/opt/homebrew/var/log/minio.log</string>
	<key>WorkingDirectory</key>
	<string>/opt/homebrew</string>
</dict>
</plist>
```

**Comment by r-scheele** [comment]
Hi @timgent please uninstall minio, clean up the configuration files and install it again. 
`brew uninstall minio`

`rm -rf /opt/homebrew/etc/minio`

`bew install minio`

`brew services start minio`
==> Successfully started `minio` (label: homebrew.mxcl.minio)

**Comment by citizenrich** [comment]
This removes everything using etc, including for other formula, `rm -rf /opt/homebrew/etc`. I recommend not doing this.
