### ISSUE TITLE
1-time link // advanced retention policy

### ISSUE THREAD

**Issue by adRn-s** [minio/minio#16389]
_Is your feature request related to a problem? Please describe._
**No problem at all, but I'd like to serve files in S3 that are only downloadable 1 time.**

_Describe the solution you'd like_
**Ideally, this would be sent to the user by email, and actually they'd get to download the file as many times as they want, but only from the IP address they use to access it in the first place. This would emulate [my current system](fex.belwue.de/).**

_Describe alternatives you've considered_
**None. Can't see how [this](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectRetention.html) would be related.**

_Additional context_
**Similar issue I found: #5955 (link in that answer is broken).**

**Comment by harshavardhana** [comment]
@adRn-s this is not part of S3 API - there is no single expiration revocable support. 

You would have to build this in your application not MinIO server.

We would love to have something like this, but unfortunately S3 API currently has no such provisions.

So sorry about that we would not be implementing this feature for now.
