### ISSUE TITLE
minio 集群节点退役

### ISSUE THREAD

**Issue by Myxg** [minio/minio#16395]
minio==RELEASE.2022-01-04T07-41-07Z
集群现有2个pool，共6个节点，需要将其中一个pool及其中的3个节点退役，在执行mc admin decommission status minio时报错：“mc: <ERROR> Unable to get status for all pools. This 'admin' API is not supported by server in 'mode-server-distributed-xl'.”
是minio版本的原因吗？

**Comment by kannappanr** [comment]
Yes. Please upgrade to the latest version for both mc and minio
