### ISSUE TITLE
LDAP/AD - nested groups

### ISSUE THREAD

**Issue by janzhanal** [minio/minio#16398]
**Is your feature request related to a problem? Please describe.**
I was strugling with configuration of LDAP/AD setup due to nested groups used

**Describe the solution you'd like**
I would like to add to manual ([minio/docs/sts//ldap.md](https://github.com/minio/minio/tree/master/docs/sts/ldap.md)) following:
If you are using Active directory with nested groups please update filtering options with
:1.2.840.113556.1.4.1941: - LDAP_MATCHING_RULE_IN_CHAIN

example:
```
group_search_filter: (&(objectClass=group)(member:1.2.840.113556.1.4.1941:=%d))
user_dn_search_filter: (&(memberOf:1.2.840.113556.1.4.1941:=CN=group,DC=dc,DC=net)(sAMAccountName=%s))
```

**Describe alternatives you've considered**
As an alternative I would propose adding option/variable (bool) that can be used to set "subtree" searching. But the first option is for sure less work...

If you agree I can submit pull request for the manual.

**Comment by harshavardhana** [comment]
@janzhanal please submit a PR.
