### ISSUE TITLE
objects: Locking should move from xl-erasure-v1 to xl-objects.go 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1639]

**Comment by krishnasrinivas** [comment]
should also fix all the race conditions that we have https://github.com/minio/minio/issues/1644 https://github.com/minio/minio/issues/1624  https://github.com/minio/minio/issues/1650  https://github.com/minio/minio/issues/1649

**Comment by GarimaKapoor** [comment]
Krishna, Can you update the timeline for this?

**Comment by krishnasrinivas** [comment]
fix by: 18th
