### ISSUE TITLE
Helm Chart: `buckets[].versioning` does not work

### ISSUE THREAD

**Issue by mattupstate** [minio/minio#16394]
## Expected Behavior

When specifying `--set buckets[0].name=mybucket,buckets[0].versioning=true` the bucket should have versioning enabled.

## Current Behavior

When specifying `--set buckets[0].name=my-bucket,buckets[0].versioning=true` the bucket does not have versioning enabled. 

## Possible Solution

Given the value for the `OBJECTLOCKING ` variable defaults to `false`, I'm guessing changing the conditional [here](https://github.com/minio/minio/blob/master/helm/minio/templates/_helper_create_bucket.txt#L88) to something like:

```
if [ $OBJECTLOCKING = false ] ; then
```

## Steps to Reproduce (for bugs)

1. Install the Helm chart specifying the bucket information and versioning option:

        $ helm install --set replicas=1,drivesPerNode=4,buckets[0].name=mybucket,buckets[0].versioning=true minio/minio

2. Take note of the post-job log output, it should look like:

        Connecting to MinIO server: http://minio:9000
        Added `myminio` successfully.
        Creating bucket 'mybucket'
        Bucket created successfully `myminio/mybucket`.
        Bucket 'mybucket' versioning unchanged.
        Setting policy of bucket 'mybucket' to 'none'.
        Access permission for `myminio/mybucket` is set to `private`

3. The minio server logs if they happen to help:

        Defaulted container "minio" out of: minio, debugger-svvqr (ephem), debugger-8tmt9 (ephem)
        WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
        MinIO Object Storage Server
        Copyright: 2015-2023 MinIO, Inc.
        License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
        Version: RELEASE.2023-01-06T18-11-18Z (go1.19.4 linux/arm64)
        
        Status:         4 Online, 0 Offline.
        API: http://172.17.0.12:9000  http://127.0.0.1:9000
        Console: http://172.17.0.12:9001 http://127.0.0.1:9001
        
        Documentation: https://min.io/docs/minio/linux/index.html

> NOTE: Getting the logs of the post-job is very annoying. The container runs so quick it's hard to get the logs before the job+pod is deleted by a Helm hook.

## Context

I'm trying to setup a minimal local development environment with versioning enabled for buckets. I tried the workaround of setting `makeBucketJob.exitCommand` to something like:

    mc --insecure version enable myminio/mybucket

Which results in 

```
Defaulted container "minio-make-bucket" out of: minio-make-bucket, minio-make-user
Connecting to MinIO server: http://minio:9000
Added `myminio` successfully.
Bucket 'mybucket' versioning unchanged.
Setting policy of bucket 'mybucket' to 'none'.
Access permission for `myminio/mybucket` is set to `private`
mc: <ERROR> Unable to enable versioning: `SetVersion` is not supported for `filesystem`.
```

But, given my limited experience with Minio, I have no idea what the last error means or what else might be wrong.

**Comment by omegazeng** [comment]
The same issue
* values

```yaml
mode: distributed
replicas: 4
pools: 1

buckets:
  - name: mybucket
    policy: none
    purge: false
    versioning: true
```

* version
```text
helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION  
minio           default         1               2023-05-25 09:37:06.808800995 +0000 UTC deployed        minio-5.0.9                             RELEASE.2023-04-28T18-11-17Z

k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8", GitCommit:"0ce7342c984110dfc93657d64df5dc3b2c0d1fe9", GitTreeState:"clean", BuildDate:"2023-03-15T13:39:54Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8", GitCommit:"0ce7342c984110dfc93657d64df5dc3b2c0d1fe9", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:02Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}
```

**Comment by harshavardhana** [comment]
vanilla helm chart is not maintained by us, we have no way to test this. feel free to work on a fix and send it.

Closing this issue as non-actionable on us.

**Comment by mattupstate** [comment]
So the helm chart source is in this repo but the minio team doesn't maintain it? That's quite confusing and your response is disappointing. The issue should remain open so long as the source remains in this repo.

**Comment by klauspost** [comment]
@mattupstate We don't keep feature requests open unless we expect to resolve them.

This is an open source project. As Harsha said you are welcome to contribute.  Alternatively you are welcome to engage with us commercially if you are looking for specific fixes. You can reach us at `hello@min.io`.
