### ISSUE TITLE
When minio cluster upgrade from the version 2022-03-26T06 to the lasted, downloading for a long time error with connection refused happens

### ISSUE THREAD

**Issue by suntao1983** [minio/minio#16419]
When minio cluster upgrade from the version 2022-03-26T06 to the lasted, downloading for a long time error with connection refused happens：
Error: Marking minio-2:9000 offline temporarily: caused by Post "http://minio-2:9000/minio/storage/dataset/minio6/v49/readall?disk-id=&file-path=format.json&volume=.minio.sys: dial tcp10.77.115.3:9000: connect: conection refused"

**Comment by vadmeste** [comment]
@suntao1983 is minio-2 crashing sometimes ?
