### ISSUE TITLE
MinIO becomes unresponsive when a disk is offline / faulty - zombifies when process is killed

### ISSUE THREAD

**Issue by rluetzner** [minio/minio#16422]
We noticed that MinIO became unresponsive and after some analysis figured out that one of the disks seems to be failing. The SMART values for the disk confirm a high error rate.

From the logs we were able to see that MinIO intermittently marked the disk as offline, but even so the system remained unresponsive.

We used 'mc trace' and discovered a lot of `lock conflict`s for `lock.RLock`. Sadly we didn't save the log output. We also observed that minio was maxing out the CPU on the affected system.

We proceeded with (forcefully) unmounting the drive, but MinIO still didn't respond.

We're running MinIO as a systemd service, so we stopped the service, but MinIO didn't respond and the service got stuck in the 'Stopping' state. After waiting multiple minutes, we ended up killing the MinIO process, which made it end up zombified. In the end we had to reboot the entire machine to get MinIO online again.

## Expected Behavior

MinIO should not become unresponsive if a disk is offline.

We should always be able to shutdown MinIO in a reasonable time.

## Current Behavior

MinIO can become unresponsive if a disk is offline. It is very likely related to the disk being close to dying.

It's possible to get MinIO stuck and not be able to shut it down. The process will end up zombified if killed.

## Possible Solution

n/a

## Steps to Reproduce (for bugs)

We were unable to reproduce the issue and have since replaced the faulty disk. However, we've seen the zombified process multiple times, always related to MinIO being unresponsive.

The hard part is finding out how to get MinIO stuck.

1. MinIO is unresponsive for any reason.
2. Stop systemd service.
3. Kill the MinIO process.

## Context

MinIO was unresponsive for multiple hours until we figured out the faulty disk. It's been running fine since we swapped the disk.

## Regression

It's probably not a regression, but I found similar (although old) issues:
* #4887
* #5190 

## Your Environment

* Version used (`minio --version`): RELEASE.2022-11-17T23-20-09Z
* Server setup and configuration: 2 nodes (bare metal) with 16 disks, EC:2
* Operating System and version (`uname -a`): Linux apollo2 5.3.18-24.96-default Nr.1 SMP Mon Nov 22 08:33:36 UTC 2021 (9a413cc) x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
We disconnect a drive if we have had no response from it within 30 seconds.
If it works, but just very slow, there isn't much we can do. We can't just start disconnecting disks because they are slow.

Lock conflicts are expected. Yes, MinIO tries to complete the queued operations before it shuts down. That is by design.

I can't see what I can do here.

**Comment by harshavardhana** [comment]
@rluetzner can you provide some more details about your disks and overall setup? 

Are these disks HDDs, NVMe's or remote disks?

When server is in this state you should always send a SIGABRT signal to forcibly crash the process and get the runtime stack dump.

This would provide us more information, I can't see how to reproduce this though. I have tried things like xfs_freeze to simulate a similar behavior but they all run fine without any problems.

You also have 2 nodes which is not enough for HA for any reasonable setup. Our minimum recommended is 4 for a production setup.

**Comment by rluetzner** [comment]
Thank you both for the quick answer. What @klauspost said already mostly explains why this might be happening. My theory is that due to the high error rate, the disk responds very slowly (trying to adjust for faulty sectors) and incoming requests stack up in MinIO. I'm guessing these requests are unaffected by timeouts because the underlying systemcall is hanging.

Having MinIO try and finish all queued operations is the right call. Thanks for confirming my suspicion.

@harshavardhana  we're using XFS formatted HDDs that are locally attached to the two nodes. Both servers are in the same location, so there should be very little network latency.

> When server is in this state you should always send a SIGABRT signal to forcibly crash the process and get the runtime stack dump.

That would be a `kill -6`, right? Until now we've always used `kill -9`. I didn't even think of generating a dump. If we come across this issue again, I'll be sure to try that.

I'm aware of the limitations of a setup with less than 4 nodes. Nevertheless, it should be able to cope with one of the disk being offline. In fact, if we simply unmount one of the disks, everything works as expected.

Also thanks for making me aware of `xfs_freeze`. Interesting that you couldn't reproduce the issue with it. So it seems to be a very specific behavior of the faulty disk that is causing this issue.

I'll report back if we come across any new findings.

**Comment by harshavardhana** [comment]
Thanks @rluetzner

**Comment by tdsn0007** [comment]
I have the same problem with same ambient (2 servers).

**Comment by klauspost** [comment]
https://github.com/minio/minio/pull/16427

**Comment by harshavardhana** [comment]
> #16427

Does this fix this problem? @klauspost ?

**Comment by klauspost** [comment]
For remote nodes probably. But I don't see what we can do about this anyway.

**Comment by larssb** [comment]
We're seeing this on a 4 servers 4 disks per node MinIO vm-cluster. Version 2023-03-24T21:41:23Z of MinIO. Further, I experience not being able to login to the faulty node over SSH at all. So either the CPU is totally over burdened or the node is generally down ... we see:

```text
INFO: task minio:41956 blocked for more than 129 seconds
          Not tainted KERNEL_VERSION #154-Ubuntu
```

And when this happens the entire cluster gets degraded and unresponsive and we see errors in the `journal log` on other nodes that points to the VM having these `...blocked for more than 120 seconds` on its console ... in errors in the log like:

```text
c9b1a2e45eb.lck) returned an error (drive is faulty) (*fmt.wrapError)
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       11: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       10: internal/logger/logonce.go:149:logger.LogOnceIf()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        9: cmd/erasure-object.go:560:cmd.readAllXL()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        8: cmd/erasure-object.go:628:cmd.erasureObjects.getObjectFileInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        7: cmd/erasure-object.go:704:cmd.erasureObjects.getObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        6: cmd/erasure-object.go:446:cmd.erasureObjects.GetObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        5: cmd/erasure-sets.go:773:cmd.(*erasureSets).GetObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        4: cmd/erasure-server-pool.go:913:cmd.(*erasureServerPools).GetObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        3: cmd/object-handlers.go:666:cmd.objectAPIHandlers.headObjectHandler()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        2: cmd/object-handlers.go:863:cmd.objectAPIHandlers.HeadObjectHandler()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: API: HeadObject(bucket=BUCKET_NAME, object=backupstore/volumes/e3/1e/pvc-18ae9661-cb6d-4331-b4ab-7bc78d0c43f5/locks/lock-8e504c9b1a2e45eb.lck)
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: Time: 08:50:27 UTC 04/10/2023
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: DeploymentID: 0b7bba48-644f-46b8-91aa-05a4411aeb19
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: RequestID: 175486AA5C9721A7
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: RemoteHost: IPv4
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: Host: IPv4:9199
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: UserAgent: aws-sdk-go/1.34.2 (go1.14.15; linux; amd64)
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: Error: Drive http://ipv4:9199/minio-data4, path (availability-prod-cluster-velero/backupstore/volumes/e3/1e/pvc-18ae9661-cb6d-4331-b4ab-7bc78d0c43f5/locks/lock-8e504c9b1a2e45eb.lck) returned an error (drive is faulty) (*fmt.wrapError)
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       11: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       10: internal/logger/logonce.go:149:logger.LogOnceIf()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        9: cmd/erasure-object.go:560:cmd.readAllXL()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        8: cmd/erasure-object.go:628:cmd.erasureObjects.getObjectFileInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        7: cmd/erasure-object.go:704:cmd.erasureObjects.getObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        6: cmd/erasure-object.go:446:cmd.erasureObjects.GetObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        5: cmd/erasure-sets.go:773:cmd.(*erasureSets).GetObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        4: cmd/erasure-server-pool.go:913:cmd.(*erasureServerPools).GetObjectInfo()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        3: cmd/object-handlers.go:666:cmd.objectAPIHandlers.headObjectHandler()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        2: cmd/object-handlers.go:863:cmd.objectAPIHandlers.HeadObjectHandler()
Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

Is the error a symptom of the error in the vm console? And further, when we then hard reset then VM through the hyper-converged infrastructure's WebUI the cluster is up again and acting without issue and no `drive is faulty` errors for some time. Until it happens again.

What's a good approach on this problem?

Thank you so much

**Comment by klauspost** [comment]
@larssb There isn't much to go by. The error indicates a problem outside of MinIO is blocking for it to get resources. The error message says the scheduler cannot switch *to* MinIO.

For more detailed analysis I suggest you [engage commercially with us](https://min.io/pricing).

**Comment by harshavardhana** [comment]
> We're seeing this on a 4 servers 4 disks per node MinIO vm-cluster. Version 2023-03-24T21:41:23Z of MinIO. Further, I experience not being able to login to the faulty node over SSH at all. So either the CPU is totally over burdened or the node is generally down ... we see:
> 
> ```
> INFO: task minio:41956 blocked for more than 129 seconds
>           Not tainted KERNEL_VERSION #154-Ubuntu
> ```
> 
> And when this happens the entire cluster gets degraded and unresponsive and we see errors in the `journal log` on other nodes that points to the VM having these `...blocked for more than 120 seconds` on its console ... in errors in the log like:
> 
> ```
> c9b1a2e45eb.lck) returned an error (drive is faulty) (*fmt.wrapError)
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       11: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       10: internal/logger/logonce.go:149:logger.LogOnceIf()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        9: cmd/erasure-object.go:560:cmd.readAllXL()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        8: cmd/erasure-object.go:628:cmd.erasureObjects.getObjectFileInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        7: cmd/erasure-object.go:704:cmd.erasureObjects.getObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        6: cmd/erasure-object.go:446:cmd.erasureObjects.GetObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        5: cmd/erasure-sets.go:773:cmd.(*erasureSets).GetObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        4: cmd/erasure-server-pool.go:913:cmd.(*erasureServerPools).GetObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        3: cmd/object-handlers.go:666:cmd.objectAPIHandlers.headObjectHandler()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        2: cmd/object-handlers.go:863:cmd.objectAPIHandlers.HeadObjectHandler()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: API: HeadObject(bucket=BUCKET_NAME, object=backupstore/volumes/e3/1e/pvc-18ae9661-cb6d-4331-b4ab-7bc78d0c43f5/locks/lock-8e504c9b1a2e45eb.lck)
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: Time: 08:50:27 UTC 04/10/2023
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: DeploymentID: 0b7bba48-644f-46b8-91aa-05a4411aeb19
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: RequestID: 175486AA5C9721A7
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: RemoteHost: IPv4
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: Host: IPv4:9199
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: UserAgent: aws-sdk-go/1.34.2 (go1.14.15; linux; amd64)
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]: Error: Drive http://ipv4:9199/minio-data4, path (availability-prod-cluster-velero/backupstore/volumes/e3/1e/pvc-18ae9661-cb6d-4331-b4ab-7bc78d0c43f5/locks/lock-8e504c9b1a2e45eb.lck) returned an error (drive is faulty) (*fmt.wrapError)
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       11: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:       10: internal/logger/logonce.go:149:logger.LogOnceIf()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        9: cmd/erasure-object.go:560:cmd.readAllXL()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        8: cmd/erasure-object.go:628:cmd.erasureObjects.getObjectFileInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        7: cmd/erasure-object.go:704:cmd.erasureObjects.getObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        6: cmd/erasure-object.go:446:cmd.erasureObjects.GetObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        5: cmd/erasure-sets.go:773:cmd.(*erasureSets).GetObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        4: cmd/erasure-server-pool.go:913:cmd.(*erasureServerPools).GetObjectInfo()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        3: cmd/object-handlers.go:666:cmd.objectAPIHandlers.headObjectHandler()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        2: cmd/object-handlers.go:863:cmd.objectAPIHandlers.HeadObjectHandler()
> Apr 10 08:50:27 minio-pr-backp-02-vk minio[1467800]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> ```
> 
> Is the error a symptom of the error in the vm console? And further, when we then hard reset then VM through the hyper-converged infrastructure's WebUI the cluster is up again and acting without issue and no `drive is faulty` errors for some time. Until it happens again.
> 
> What's a good approach on this problem?
> 
> Thank you so much

This means your disks are hung, your infrastructure is not keeping up

**Comment by harshavardhana** [comment]
@larssb were you using XFS?

**Comment by LarsBingBong** [comment]
@harshavardhana ( larssb from another account ) - I sure am yes.

**Comment by harshavardhana** [comment]
The issue is mostly due to unresponsive drives, and there is nothing more we can do. Your workload is more than what this setup is capable of.

Tasks getting blocked on disk I/O. MinIO can only be as fast as the drives here.
