### ISSUE TITLE
logs are flooded by wrong time

### ISSUE THREAD

**Issue by arm2arm** [minio/minio#16436]
```
mc admin logs myminio
....
Time: 00:00:00 UTC 01/01/0001
Time: 00:00:00 UTC 01/01/0001
Time: 00:00:00 UTC 01/01/0001
Time: 00:00:00 UTC 01/01/0001
Time: 00:00:00 UTC 01/01/0001
...
...
```

minio version:
```
./mc --version
mc version RELEASE.2022-12-24T15-21-38Z (commit-id=176072dee43de613569aaa56061eba9d6d550290)
Runtime: go1.19.4 linux/amd64
```

**Comment by harshavardhana** [comment]
AFAICS everything shows perfectly fine 

```
mc admin logs myminio/
 API: SYSTEM()
 Time: 09:58:41 UTC 01/19/2023
 DeploymentID: 74a3c9fd-44e2-42db-b1c0-4643882eac25
 Error: Unable to update audit webhook targets: [Post "http://test.com": dial tcp 67.225.146.248:80: i/o timeout] (*errors.errorString)
       10: internal/logger/logger.go:258:logger.LogIf()
        9: cmd/config-current.go:594:cmd.applyDynamicConfigForSubSys()
        8: cmd/config-current.go:655:cmd.applyDynamicConfig()
        7: cmd/config-current.go:515:cmd.lookupConfigs()
        6: cmd/config-current.go:773:cmd.loadConfig()
        5: cmd/config.go:227:cmd.initConfig()
        4: cmd/config.go:199:cmd.(*ConfigSys).Init()
        3: cmd/server-main.go:458:cmd.initConfigSubsystem()
        2: cmd/server-main.go:425:cmd.initServer()
        1: cmd/server-main.go:630:cmd.serverMain()
```

Looks like you have incompatible MinIO version and mc version

**Comment by arm2arm** [comment]
Just updated them and I have following minio versions:
```
[root@araid064 ~]# clush -g m /root/mc --version | grep version 
araid064.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
araid063.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
minio01.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
minio03.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
minio02.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
minio04.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
[root@araid064 ~]# clush -g m /root/minio --version | grep version 
araid064.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
araid063.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
minio01.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
minio02.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
minio04.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
minio03.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
[root@araid064 ~]# 

```
Do I miss something?

**Comment by harshavardhana** [comment]
> Just updated them and I have following minio versions:
> 
> ```
> [root@araid064 ~]# clush -g m /root/mc --version | grep version 
> araid064.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> araid063.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> minio01.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> minio03.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> minio02.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> minio04.niz: mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> [root@araid064 ~]# clush -g m /root/minio --version | grep version 
> araid064.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
> araid063.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
> minio01.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
> minio02.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
> minio04.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
> minio03.niz: minio version RELEASE.2023-01-18T04-36-38Z (commit-id=698862ec5d2ef7c1b4c6140f8720f2d25c5d7f11)
> [root@araid064 ~]# 
> ```
> 
> Do I miss something?

I have no idea, it clearly looks something off in your deployment and OS settings.
