### ISSUE TITLE
Unable to start decommissioning 

### ISSUE THREAD

**Issue by arm2arm** [minio/minio#16434]
## Expected Behavior
decommissioning started successfully 

## Current Behavior
```
root@araid060 ~]# mc admin decommission start  myminio http://araid0{63...64}.niz/store/{1...4}
mc: <ERROR> Unable to start decommission on the specified pool. Decommission cannot be started, rebalance is already in progress.
[root@araid060 ~]# 
```

## Possible Solution
Unknown 

## Steps to Reproduce (for bugs)

* setup minio with 2 pools
* add data over 500K objects
* start rebalance
* stop rebalance
```
./mc admin rebalance stop myminio
Rebalance stopped for myminio
```
* start decommissioning
```
root@araid060 ~]# mc admin decommission start  myminio http://araid0{63...64}.niz/store/{1...4}
mc: <ERROR> Unable to start decommission on the specified pool. Decommission cannot be started, rebalance is already in progress.
```

## Context
cannot replace/remove pool with the old hardware 

## Regression
unable to start decommission 

## Your Environment

* mc version RELEASE.2022-12-24T15-21-38Z (commit-id=176072dee43de613569aaa56061eba9d6d550290)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.

**Comment by harshavardhana** [comment]
@arm2arm why are you wasting time doing rebalancing when you want to decommission?

**Comment by arm2arm** [comment]
this was a wrong decision, we had 2 pools with different ages, successfully added 3-rd (new) pool.
removed faulty pool. so got 2 pools left 1 middle-aged and 1 brand new hardware.
started rebalance and later realized the middle aged hardware became unstable, overheating hba controllers.

**Comment by klauspost** [comment]
I investigated this, but couldn't find the place where rebalance marks itself as finished - maybe I am missing something, but unless the operation is completely removed once it completes it seems that the state will "stick around".

**Comment by harshavardhana** [comment]
I found the problem @klauspost sending a fix.

**Comment by arm2arm** [comment]
it works!! thank you!
