### ISSUE TITLE
Disable all forms of healing

### ISSUE THREAD

**Issue by STRATZ-Ken** [minio/minio#16446]
**Is your feature request related to a problem? Please describe.**
My company uses Minio for basic BLOB storage.  This allows us to store 2-3Mb files, about 1 million per bucket.  This data is good for a while but we purge every so often.  The data is NOT super important so we have them on 6TB HDD (slow) drives, which are working great.  However, last night we had some issues and some drives swapped.  I fixed that. Now its in healing mode. But the heal is taking about 80% of the HDDs ability.  So no new data cannot come in without massive timeouts.  Lost data is not an issue for us, if its lost, no big deal. For this reason we would love a way to disable this completely.

**Describe the solution you'd like**
An ability to completely disable all types of heals, as my hardware cannot keep up with 6TB x 19 drives x 3 nodes of data. (Each about 60% full).

Also a way to disable to current heal would be great as well.

**Comment by harshavardhana** [comment]
You can simply add delays to heal to make it practically slow, but we cannot allow for healing to be completely disabled.

These kind of knobs are dangerous for our most common deployments where they care about their data.

Set 

```
mc admin config set alias/ heal max_io=1 max_sleep=87600h
```

**Comment by STRATZ-Ken** [comment]
@harshavardhana Is a reboot required for settings to take effect? The load looks pretty much the same overall.

**Comment by klauspost** [comment]
@STRATZ-Ken No, not if I recall correctly. But `mc` will tell you when you've executed the command.

**Comment by harshavardhana** [comment]
> @harshavardhana Is a reboot required for settings to take effect? The load looks pretty much the same overall.

Settings should immediately take affect, you may reboot as well.
