### ISSUE TITLE
Minio fails to write objects when a single host is offline

### ISSUE THREAD

**Issue by Jazz9** [minio/minio#16444]
## Expected Behavior
Minimal user impact when a host is down

## Current Behavior
When we pkill minio or shutdown on a single host ( one of six ), minio doesn't respond to writes. reads are ok.

## Steps to Reproduce (for bugs)
1. pkill minio

## Your Environment
6 hosts, 11 drives on hba, xfs formatted, ubuntu server 22.04

*Version RELEASE.2023-01-12T02-06-16Z
*OS Linux min04 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* only real setting change is MINIO_STORAGE_CLASS_STANDARD=EC:2

This is currently a dev cluster so we can try code / changes.

**Comment by Jazz9** [comment]
tested two other versions:
RELEASE.2022-12-07T00-56-37Z - works as expected.
RELEASE.2023-01-18 - doesn't work.

**Comment by klauspost** [comment]
Should be fixed in next release through #16427

**Comment by klauspost** [comment]
@Jazz9 A new release was just made. Could you check that? It could be https://github.com/minio/minio/pull/16431 that caused this.

**Comment by Jazz9** [comment]
Is there a deb version or do we need to build it?

**Comment by klauspost** [comment]
https://dl.min.io/server/minio/release/linux-amd64/minio_20230120020544.0.0_amd64.deb

**Comment by harshavardhana** [comment]
@Jazz9 please update us, this is fixed as per our understanding for the time being.

**Comment by Jazz9** [comment]
Thankyou for the fix - we have tested this with 1 and 2 hosts down. All works as expected.
