### ISSUE TITLE
[Regression] S3 DeleteObjects: when object is a directory - the returned object key is wrong 

### ISSUE THREAD

**Issue by lallinger-tech** [minio/minio#16445]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

When trying to delete an object of type directory (for example 'my_dir/') using S3 DeleteObjects the returned object key is wrong for **subsequent** requests - the actual returned object key is the name of the directory + "__XLDIR__". (and for the example - 'my_dir__XLDIR__').
## Expected Behavior

When trying to delete an object of type directory (for example 'my_dir/') using DeleteObjects the returned the same object key (and for the example - should be 'my_dir/').

## Steps to Reproduce (for bugs)

1. create a folder `my_dir/`
2. put a file in the folder
3. delete the folder using DeleteObjects => returned value is `my_dir`
4. delete the folder again using DeleteObjects => returned value is `my_dir__XLDIR__`

## Regression
 yes: #10643 

## Your Environment

* Version used (`minio --version`): RELEASE.2023-01-20T02-05-44Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
@lallinger-arbeit Can you confirm you are testing on a versioned bucket?

**Comment by harshavardhana** [comment]
@lallinger-arbeit are you using versioned buckets ?

**Comment by lallinger-tech** [comment]
@harshavardhana no, not as far as i know

**Comment by klauspost** [comment]
I found the issue. Sending a PR in a minute.
