### ISSUE TITLE
Delete data when activate versioning

### ISSUE THREAD

**Issue by Ilhaame** [minio/minio#16454]
Hello, 

I have a problem when I activate versioning in my bucket. 
We have minio on 2 nodes and we use another minio for replication.

For add replication in my bucket, we should activate versioning. 
And when i activate versionning we have a problem with deleteting data.

I add some rules for delete data but it's  not working:
{
"status": "success",
"target": "minio/velero",
"config": {
  "Rules": [
   {
    "Expiration": {
     "ExpiredObjectDeleteMarker": true
    },
    "ID": "cevbqgg0u2896rndqc6g",
    "Status": "Enabled"
   },
   {
    "ID": "cf4k19o0u28bkmlkb1rg",
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 1,
     "NewerNoncurrentVersions": 0
    },
    "Status": "Enabled"
   }
  ]
}
}

we have the data with label DEL but this data is not realy deleted 

and the storage of my nodes keeps growing, because the older versions and files in the directory is not deleted.
but when i check gui minio, the directory is empty.

Is it normal? 

Thanks for your help

**Comment by harshavardhana** [comment]
> Is it normal?

Yes, it is normal you need to make sure to expire your delete markers as well. You need to set ILM on both sites with replication to delete on both sites.

ILM rules apply in 24hr+(midnight-hour) window. Expiration is also triggered after the fact the version has become expired with +1day and then the midnight of that day. 

So it all depends on when the object was uploaded and when it became "expired"

**Comment by harshavardhana** [comment]
You want to make sure that application deletes the content - make your application version aware, or use `mc rm -r --versions --non-current`  if you want to delete them right away.
