### ISSUE TITLE
XL/fs: Investigate and track down performance issues related to PutObject/PutObjectPart

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1646]
Interestingly just a regular FS behaves the same way, i think this issue is not really inside XL anymore. 

```
$ mc mirror ~/tests test/testbucket/test1
...asesRequest.html: 311.79 MB / 6.65 GB  ▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    4.58 % 6.33 MB17m1s
```

Even a multipart is around. 

```
...ests/bigfile.5gb: 1.56 GB / 6.65 GB  ▓▓▓▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   23.50 % 15.28 MB5m38s
...
...ests/bigfile.5gb: 3.57 GB / 6.65 GB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░   53.73 % 20.87 MB2m28s
...ests/bigfile.5gb: 3.58 GB / 6.65 GB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░   53.83 % 20.88 MB2m28s
```

This is just local SSD, provides 250-350MB/sec Removing md5sum check also leads only minor benefit

```
$ mc mirror ~/tests test/testbucket/test3
...ventsResult.html: 230.24 MB / 6.65 GB  ▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    3.38 % 8.17 MB13m20s
...odelRequest.html: 233.00 MB / 6.65 GB  ▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    3.42 % 8.20 MB13m19s
```

So we are looking at something else is going on here which needs investigation.

**Comment by harshavardhana** [comment]
On test machine while uploading 1 TB single file, the upload speed slows down as upload size size increases periodically.  

```
1TB:          17.53 GB / 1024.00 GB ┃█░░░░░░░░░░░░░░░┃   1.71 % 46.27 MB6h0m13s
```

**Comment by harshavardhana** [comment]
This is how i see the progress so far, its consistent at speed 35, the upload is still in progress. 

```
minio@minio2:~/atul$ mc cp 1TB myminio93/atul
1TB:          363.57 GB / 1024.00 GB ┃▓▓▓▓▓█░░░░░░░░░┃  35.51 % 35.28 MB5h19m6s
1TB:          363.58 GB / 1024.00 GB ┃▓▓▓▓▓█░░░░░░░░░┃  35.51 % 35.28 MB5h19m6s
1TB:          363.59 GB / 1024.00 GB ┃▓▓▓▓▓█░░░░░░░░░┃  35.51 % 35.28 MB5h19m5s
1TB:          485.93 GB / 1024.00 GB ┃▓▓▓▓▓▓█░░░░░░░┃  47.45 % 35.25 MB4h19m59s
1TB:          485.95 GB / 1024.00 GB ┃▓▓▓▓▓▓█░░░░░░░┃  47.46 % 35.25 MB4h19m58s
```

**Comment by hackintoshrao** [comment]
The exec-concurrent tests at concurrency of 500 shows that tests for PutObject in most of the go routines fails by timing out,  play/sanctity/logs/concurrent.log is the log for the same. Looks like this is closely related to #1641 and #1637 .

**Comment by hackintoshrao** [comment]
Here is the block profile for exec-concurrent ( `sudo ./exec-concurrent "TestResumablePutObject"` ) at concurrency level of 500, ran the test with increased timeout of one hour. 
[500putblock.pdf](https://github.com/minio/minio/files/266240/500putblock.pdf)

**Comment by harshavardhana** [comment]
> Here is the block profile for exec-concurrent ( sudo ./exec-concurrent "TestResumablePutObject" ) at concurrency level of 500, ran the test with increased timeout of one hour. 
> 500putblock.pdf

The block profile is not giving much info, the usage of sync.Lock and sync.Wait is expected. To avoid locks they have to made even more granular to multiple levels.

There is no single button fix for this one.

**Comment by hackintoshrao** [comment]
[500putcpu.pdf](https://github.com/minio/minio/files/267365/500putcpu.pdf), From CPU profile its evident that `getAllUniqueVols` consume half the CPU.

**Comment by harshavardhana** [comment]
Closing as duplicate of #1637
