### ISSUE TITLE
Disallow SSE-C when using bucket replication (or site replication)

### ISSUE THREAD

**Issue by omarkohl** [minio/minio#16463]
**Is your feature request related to a problem? Please describe.**

Currently SSE-C (Server-Side Encryption with Client-Managed Keys) is not compatible with Bucket Replication (as [documented](https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-c.html#sse-c-is-incompatible-with-bucket-replication)) and by implication also not compatible with server-side site replication (because as far as I can tell server-side site replication uses bucket replication under the hood).

The problem is that SSE-C is something out of control for the server i.e. the client can decide whether to use it or not. This leads to a situation where for data safety or availability reasons the MinIO server has been configured to use server-side site replication, a client unwittingly uses SSE-C and those objects are never replicated. This is even worse if one or multiple clients modify the same SSE-C object in several sites, leading to what _seems to be (from the client's point of view) a data inconsistency_, because the changes to the object are never replicated.

Problems:

* Clients receive no error message when trying to PUT an SSE-C object even if the server is using bucket replication
* The replication status reports nothing is wrong

Am I right in assuming the same problem applies to Object Lifecycle Management i.e. it does not work for objects encrypted via SSE-C?

**Describe the solution you'd like**

* Either support SSE-C in combination with Bucket Replication (preferred solution)
* or make client operations using SSE-C fail
* or reflect the fact that some objects can't be replicated (because they are SSE-C encrypted) in the replication status

Maybe worthwhile mentioning that AWS supports replicating SSE-C encrypted objects.

> S3 Replication supports objects that are encrypted with SSE-C.

[Source](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-config-for-kms-objects.html#replicationSSEC)

**Comment by harshavardhana** [comment]
SSE-C is unsupported by bucket replication as per AWS S3, so we follow the same behavior. SSE-C cannot be supported since we do not have access to the encryption details and we shouldn't be saving this information on the server side.

This is unsupported.

**Comment by omarkohl** [comment]
> SSE-C is unsupported by bucket replication as per AWS S3, so we follow the same behavior.

As mentioned at the end of my ticket above this is not true, or am I misunderstanding something?

Maybe worthwhile mentioning that **AWS supports replicating SSE-C encrypted objects**.

> S3 Replication supports objects that are encrypted with SSE-C.

[Source](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-config-for-kms-objects.html#replicationSSEC)

**Comment by omarkohl** [comment]
> SSE-C cannot be supported since we do not have access to the encryption details and we shouldn't be saving this information on the server side.

I of course agree with not saving the encryption information, but wouldn't it be possible to replicate the encrypted objects without trying to decrypt them? I assume this is what AWS is doing.

**Comment by harshavardhana** [comment]
ah looks like they sneakily added that, we can add it as well.

**Comment by harshavardhana** [comment]
After some internal discussions and also from our past experience

- SSE-C has never seen wider adoption in the community, mostly because in our all deployments DevOps and IT wants to manage the KMS and keys instead of applications.
- Most applications do not support SSE-C, and also do not know how to manage the keys safely on the client side.
- Predominantly SSE-KMS and SSE-S3 are widely used and supported.

Here is what we have decided and we would want to deviate away from AWS S3 here, by saying that SSE-C headers will be rejected on buckets that have replication configured and will never be supported.

This is to make sure that we discourage SSE-C usage, and eventually want our customers and users to adopt more simpler and robust mechanisms such as SSE-KMS and SSE-S3.

Will be making this change and resolving this issue.
