### ISSUE TITLE
CORS 'Access-Control-Allow-Origin' header missing in responses

### ISSUE THREAD

**Issue by diegofmole** [minio/minio#16479]
This is related with the issue https://github.com/minio/minio/issues/11111.
We had just faced that issue in our kubernetes environment (we don't use helm charts there) and, as it was said in the previous issue, the root cause was related to minIO configs that were corrupted. 

I want to share the way to fix it, as in the other issue some people suggest to recreate the volume so the configs were created again, but that was not possible in our env, and I guess is not always posible to delete the existing volume.

We tried to manually set the cors config again using the minIO CLI, and there is how the solution to the problem appeared!
```
user@user-mbp minio % mc admin config set dc-fs api "cors_allow_origin=*"
mc: <ERROR> Unable to set 'api cors_allow_origin=*' to server: found invalid keys (extend_list_cache_life=0s ) for 'api' sub-system, use 'mc admin config reset myminio api' to fix invalid keys.

user@user-mbp minio % mc admin config reset dc-fs api
Key is successfully reset.

user@user-mbp minio % mc admin config set dc-fs api "cors_allow_origin=*"
Successfully applied new settings.
```

*How we narrow down the issue to a minIO config issue that only appears after the upgrade?*
CORS wasn't working in one env that was updated some time ago, but *it was working fine* in another env that was still using a previous minIO version. We upgrade that env that was working fine, and we started facing the CORS issue there, meaning that after the upgrade, minIO brakes the CORS config in some way. But, using that new minIO version with a fresh installation, that was working fine. So the problem only raised after the upgrade.

_Originally posted by @harshavardhana in https://github.com/minio/minio/issues/11111#issuecomment-797853784_

**Comment by harshavardhana** [comment]
> user@user-mbp minio % mc admin config set dc-fs api "cors_allow_origin=*"

which version of MinIO are you running @diegofmole - please provide more details in your issue report. 

Please provide details on which version to which version the upgrade was performed.

**Comment by diegofmole** [comment]
We were using:
- RELEASE.2021-06-14T01-29-23Z tag

And we upgrade to:
- RELEASE.2022-11-26T22-43-32Z tag

**Comment by harshavardhana** [comment]
Its because of deprecated keys

> mc: <ERROR> Unable to set 'api cors_allow_origin=*' to server: found invalid keys (extend_list_cache_life=0s ) for 'api' sub-system, use 'mc admin config reset myminio api' to fix invalid keys.

Let me check what challenges are here and if we can automatically handle it.
