### ISSUE TITLE
Platform mismatch after upgrading one node

### ISSUE THREAD

**Issue by ghost** [minio/minio#16499]
## Expected Behavior

Upgrade a single node from RELEASE.2022-12-12T19-27-27Z to RELEASE.2023-01-25T00-19-54Z should work so I can upgrade the cluster one node at a time

## Current Behavior

Node upgraded to RELEASE.2023-01-25T00-19-54Z returns the following error:

```
Jan 30 14:27:25 node1 podman[125401]: Waiting for atleast 1 remote servers with valid configuration to be online
Jan 30 14:27:25 node1 podman[125401]: Following servers have mismatching configuration [https://node2:9000/minio-data-1 has incorrect configuration: Expected platform 'OS: linux | Arch: amd64', found to be on '' https://node3:9000/minio-data-1 has incorrect configuration: Expected platform 'OS: linux | Arch: amd64', found to be on '' https://node4:9000/minio-data-1 has incorrect configuration: Expected platform 'OS: linux | Arch: amd64', found to be on '']
```

## Possible Solution

I suspect it's related to a change in eb561e1c052d3f3845e7652a21c8a7485d403df7

## Steps to Reproduce (for bugs)

1. Setup 4 node cluster with RELEASE.2022-12-12T19-27-27Z - in my case I'm using podman
2. Upgrade 1 node to RELEASE.2023-01-25T00-19-54Z
3. The upgraded node will be unable to join the cluster

## Context

Upgrade cluster one node at a time

## Regression

I think so - eb561e1c052d3f3845e7652a21c8a7485d403df7

## Your Environment

RELEASE.2022-12-12T19-27-27Z (3x nodes) and RELEASE.2023-01-25T00-19-54Z (1x node)

RHEL 9 running `minio/minio` podman container.

`Linux node1 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 30 07:36:03 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> Upgrade a single node from RELEASE.2022-12-12T19-27-27Z to RELEASE.2023-01-25T00-19-54Z should work so I can upgrade the cluster one node at a time

That is not how we expect clusters to be upgraded MinIO is designed to upgrade all servers at once. 

Please upgrade via the supported methodology and do not roll your own. https://min.io/docs/minio/linux/operations/install-deploy-manage/upgrade-minio-deployment.html
