### ISSUE TITLE
The minio reports an error after running for a period of time, and then the minio starts to slow down

### ISSUE THREAD

**Issue by William6789** [minio/minio#16498]
### **Error Log：**

API: SYSTEM(bucket=0000, object=2022/1208/99fdf9ae-9897-4633-8d54-28626dd32fbc.jpeg)
Time: 13:18:59 UTC 01/09/2023
DeploymentID: 5c578595-9ef6-4ff6-b5fe-3dadb57b625b
Error: file not found (cmd.StorageErr)
       5: cmd/erasure-healing.go:501:cmd.erasureObjects.healObject()
       4: cmd/erasure-healing.go:873:cmd.erasureObjects.HealObject()
       3: cmd/erasure-sets.go:1318:cmd.(*erasureSets).HealObject()
       2: cmd/erasure-server-pool.go:1609:cmd.(*erasureServerPools).HealObject()
       1: cmd/background-heal-ops.go:114:cmd.(*healRoutine).run()

API: SYSTEM(bucket=0000, object=2022/12/dcc65cd7-260e-4c20-83af-38f55f8d1a13.pdf)
Time: 05:01:15 UTC 01/15/2023
DeploymentID: 5c578595-9ef6-4ff6-b5fe-3dadb57b625b
Error: diskBlocks(0)/dataBlocks(3) - too few shards given (*fmt.wrapError)
       3: cmd/erasure-utils.go:50:cmd.writeDataBlocks()
       2: cmd/erasure-decode.go:269:cmd.Erasure.Decode()
       1: cmd/erasure-lowlevel-heal.go:31:cmd.Erasure.Heal.func1()

API: SYSTEM(bucket=0000, object=2022/12/dcc65cd7-260e-4c20-83af-38f55f8d1a13.pdf)
Time: 05:01:15 UTC 01/15/2023
DeploymentID: 5c578595-9ef6-4ff6-b5fe-3dadb57b625b
Error: too few shards given (*errors.errorString)
      18: cmd/erasure-encode.go:84:cmd.(*Erasure).Encode()
      17: cmd/erasure-lowlevel-heal.go:39:cmd.Erasure.Heal()
      16: cmd/erasure-healing.go:446:cmd.erasureObjects.healObject()
      15: cmd/erasure-healing.go:873:cmd.erasureObjects.HealObject()
      14: cmd/erasure-sets.go:1318:cmd.(*erasureSets).HealObject()
      13: cmd/erasure-server-pool.go:1609:cmd.(*erasureServerPools).HealObject()
      12: cmd/data-scanner.go:837:cmd.(*scannerItem).applyHealing()
      11: cmd/data-scanner.go:942:cmd.(*scannerItem).applyActions()
      10: cmd/xl-storage.go:434:cmd.(*xlStorage).NSScanner.func1()
       9: cmd/data-scanner.go:755:cmd.(*folderScanner).deepScanFolder.func1()
       8: cmd/os-readdir_unix.go:163:cmd.readDirFn()
       7: cmd/data-scanner.go:716:cmd.(*folderScanner).deepScanFolder.func1()
       6: cmd/os-readdir_unix.go:163:cmd.readDirFn()
       5: cmd/data-scanner.go:773:cmd.(*folderScanner).deepScanFolder()
       4: cmd/data-scanner.go:351:cmd.scanDataFolder()
       3: cmd/xl-storage.go:401:cmd.(*xlStorage).NSScanner()
       2: cmd/storage-rest-server.go:176:cmd.(*storageRESTServer).NSScannerHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 05:01:15 UTC 01/15/2023
DeploymentID: 5c578595-9ef6-4ff6-b5fe-3dadb57b625b
Error: too few shards given (*errors.errorString)
      12: cmd/data-scanner.go:842:cmd.(*scannerItem).applyHealing()
      11: cmd/data-scanner.go:942:cmd.(*scannerItem).applyActions()
      10: cmd/xl-storage.go:434:cmd.(*xlStorage).NSScanner.func1()
       9: cmd/data-scanner.go:755:cmd.(*folderScanner).deepScanFolder.func1()
       8: cmd/os-readdir_unix.go:163:cmd.readDirFn()
       7: cmd/data-scanner.go:716:cmd.(*folderScanner).deepScanFolder.func1()
       6: cmd/os-readdir_unix.go:163:cmd.readDirFn()
       5: cmd/data-scanner.go:773:cmd.(*folderScanner).deepScanFolder()
       4: cmd/data-scanner.go:351:cmd.scanDataFolder()
       3: cmd/xl-storage.go:401:cmd.(*xlStorage).NSScanner()
       2: cmd/storage-rest-server.go:176:cmd.(*storageRESTServer).NSScannerHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

### **Your Environment：**
System OS：Rocky Linux release 9.0 (Blue Onyx)
minio Version："RELEASE.2021-04-22T15-44-28Z"

**Comment by harshavardhana** [comment]
> ### **Your Environment：**
> System OS：Rocky Linux release 9.0 (Blue Onyx) minio Version："RELEASE.2021-04-22T15-44-28Z"

This is an age old version, please upgrade.

**Comment by harshavardhana** [comment]
> > System OS：Rocky Linux release 9.0 (Blue Onyx) minio Version："RELEASE.2021-04-22T15-44-28Z"

Do not try to stick to the Apache version of MinIO to avoid license obligations, if you want to trust your data and you are security conscious please upgrade.
