### ISSUE TITLE
Multipart uploads cannot be read after ILM restore

### ISSUE THREAD

**Issue by VicSilva13** [minio/minio#16502]
## Expected Behavior
Objects that were uploaded in multiple parts should be readable after restoring them from an ILM tier were they had previously transitioned to.

## Current Behavior
Multipart uploads cannot be read after ILM restore

## Steps to Reproduce (for bugs)

1. Configure an ILM transition rule with (to test this quickly it should be set to 0 days) 
2. Upload an object that is above the size threshold to make it a multipart upload
3. Restore said object
4. Try reading it in any capacity

## Your Environment
Client: Tested using the MinIO Client (Windows: RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e) & Linux: RELEASE.2022-12-13T00-23-28Z (commit-id=4b4cab0441f000db100c5b5d9329221181bf61f2)) and https://s3browser.com/
Server: 
 - Windows: RELEASE.2023-01-25T00-19-54Z (commit-id=50d58e9b2dbbfbe2f3afa2c16ae701f9c1cf03ec)
 - Linux: RELEASE.2023-01-12T02-06-16Z (commit-id=7bc95c47a322971aff7d4d4c270dcf28a933e84b)

Sample xl.meta file: [xlmeta.zip](https://github.com/minio/minio/files/10535451/xlmeta.zip)

**Comment by klauspost** [comment]
Does the server log any errors? Could you post those?

**Comment by VicSilva13** [comment]
To add some more context:
The error that the MinIO client throws is "<ERROR> Unable to read from `vs1/test/03trz2wm.0li.160189155.tmp`. Resource requested is unreadable, please reduce your request rate."
When I use the S3 Browser the file is not even visible. Same is the case when I do an mc ls.

The error my MinIO server throws is this: Reading erasure shards at (C:\Users\Administrator\Desktop\minio: test/test17M/be5c92b1-6e18-4274-80b5-e7252a3c0a34/part.1) returned 'file not found', will attempt to reconstruct if we have quorum (*fmt.wrapError)

**Comment by VicSilva13** [comment]
I guess the issue is that minio is searching for the file like it would search for any file, but with these files it has to look for the multipart folder in minio.sys since that is where the files are restored to.

**Comment by klauspost** [comment]
What is the size of this object?

**Comment by VicSilva13** [comment]
It happens to all files above the multipart upload size threshold. So on my Linux server the threshold is set to 4MB, while on Windows it is set to 16MB. I checked that all objects over 4MB on my Linux server and all files over 16MB on my Windows server have this issue.

**Comment by klauspost** [comment]
Thanks. Finally could you post a sample `test/test17M/be5c92b1-6e18-4274-80b5-e7252a3c0a34/xl.meta` (it doesn't have to be that specific object). We should have enough to investigate then.

**Comment by VicSilva13** [comment]
I added it to my bug report.
Additional info: I was using an Azure Blob Storage as ILM tier

**Comment by klauspost** [comment]
```JSON
{
  "Versions": [
    {
      "Header": {
        "Flags": 2,
        "ModTime": "2023-01-30T12:17:00.0827647+01:00",
        "Signature": "92bd1e7a",
        "Type": 1,
        "VersionID": "00000000000000000000000000000000"
      },
      "Idx": 0,
      "Metadata": {
        "Type": 1,
        "V2Obj": {
          "CSumAlgo": 1,
          "DDir": "vlySsW4YQnSAteclKjwKNA==",
          "EcAlgo": 1,
          "EcBSize": 1048576,
          "EcDist": [
            1
          ],
          "EcIndex": 1,
          "EcM": 1,
          "EcN": 0,
          "ID": "AAAAAAAAAAAAAAAAAAAAAA==",
          "MTime": 1675077420082764700,
          "MetaSys": {
            "X-Minio-Internal-actual-size": "MTc4MjU3OTI=",
            "x-minio-internal-transition-status": "Y29tcGxldGU=",
            "x-minio-internal-transition-tier": "TUlOSU9FQ0JMT0I=",
            "x-minio-internal-transitioned-object": "MGI5YjE1MDktNTBlNS00ZWJmLWJkYzAtNGExNzUyZmU4M2IyL3Rlc3QvMDgvYzEvMDhjMWY4NWQtYWYwMS00YzJkLWE2MmYtMzM0ZjE0NzFkZTI4",
            "x-minio-internal-transitioned-versionID": "MjAyMC0xMC0wMg=="
          },
          "MetaUsr": {
            "X-Amz-Restore-Expiry-Days": "1",
            "X-Amz-Restore-Request-Date": "Mon, 30 Jan 2023 11:17:11 GMT",
            "content-type": "application/octet-stream",
            "etag": "d7f0e9878e982a33237d7f6f946e7951-2",
            "x-amz-restore": "ongoing-request=\"false\", expiry-date=\"Wed, 01 Feb 2023 00:00:00 GMT\""
          },
          "PartASizes": [
            16777216,
            1048576
          ],
          "PartETags": null,
          "PartNums": [
            1,
            2
          ],
          "PartSizes": [
            16777216,
            1048576
          ],
          "Size": 17825792
        },
        "v": 1674605994
      }
    }
  ]
}
```
