### ISSUE TITLE
The error that is marked as fixed in #15442 still occurs: "A timeout occurred while trying to lock a resource, please reduce your request rate"

### ISSUE THREAD

**Issue by arthur-vilgursky** [minio/minio#16514]
There is a single Minio instance with three XFS drives. There is a public bucket, locking and versioning are disabled. When i try to either delete or replace (put a new content) some objects that are downloaded frequently, i get this error: "A timeout occurred while trying to lock a resource, please reduce your request rate". I've tried to do it in Web console, PHP and JS SDKs, `mc cp` and raw HTTP PUT request with Postman, the result was either the same or i've got an error 499 if SDK set a lower timeout than Minio has. There are some other issues related to this error, but only this one seems to represent a similar scenario:
https://github.com/minio/minio/issues/15442
it is makred as fixed on Sep 8, 2022, but updating to RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96) was one of the first things that i've tried and it did not help. I've asked in Slack here
https://minio.slack.com/archives/C3NDUB8UA/p1672306442249319
and got an advice to change FS from ext4 to XFS, but it did not help either. One of the files that trigger this error is `/Localizations/production.json`, its size is 1.5 MB, and it is downloaded frequently, 7-8 requests per second in average from a different client each time. Other files in the same directory that are not downloaded frequently can be removed and deleted, even if their content is the same. If i remove the folders that correspond to that file on all of three drives with a plain rm (not mc rm), it disappears and then i can upload a new one but then get the same error instantly when i try to upload it again.

## Expected Behavior
Object can be updated or deleted 

## Current Behavior
I get this error
```
A timeout occurred while trying to lock a resource, please reduce your request rate
```
The only option to delete is to use plain rm on all drives, a new one can be uploaded instead, but it means a few seconds of downtime

## Steps to Reproduce (for bugs)
1. Set up a single Minio server with 3 XFS drives
/usr/local/bin/minio server /mnt/nvme{1...3}/storage 
2. Upload a 1 MB+ file
3. Set up a dozen of clients to download that file simultaneously
4. Try to delete or update the file

## Context
The file is a translations list for a mobile application, every time a user starts the application, it downloads it. It isn't possible to update these translations in other way than rm hack described above

## Regression
Possibly a regression of what is fixed for
https://github.com/minio/minio/issues/15442

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)
Runtime: go1.19.4 linux/amd64
```
* Server setup and configuration:
```
/usr/local/bin/minio server /mnt/nvme{1...3}/storage 
```
* Operating System and version (`uname -a`):
```
Linux storage 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
* `mc admin config export`:
```
subnet license= api_key= proxy= 
# callhome enable=off frequency=24h 
site name= region= 
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_priority=auto transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m disable_odirect=off gzip_objects=off 
scanner speed=default 
# compression enable=off allow_encryption=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml,binary/octet-stream 
# identity_openid enable= display_name= config_url= client_id= client_secret= claim_name=policy claim_userinfo= role_policy= claim_prefix= redirect_uri= redirect_uri_dynamic=off scopes= vendor= keycloak_realm= keycloak_admin_url= 
# identity_ldap server_addr= srv_record_name= user_dn_search_base_dn= user_dn_search_filter= group_search_filter= group_search_base_dn= tls_skip_verify=off server_insecure=off server_starttls=off lookup_bind_dn= lookup_bind_password= 
# identity_tls skip_verify=off 
# identity_plugin url= auth_token= role_policy= role_id= 
# policy_plugin url= auth_token= 
# logger_webhook enable=off endpoint= auth_token= client_cert= client_key= queue_size=100000 
# audit_webhook enable=off endpoint= auth_token= client_cert= client_key= queue_size=100000 
# audit_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off version= 
# notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key= 
# notify_amqp enable=off url= exchange= exchange_type= routing_key= mandatory=off durable=off no_wait=off internal=off auto_deleted=off delivery_mode=0 publisher_confirms=off queue_limit=0 queue_dir= 
# notify_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir= version= 
# notify_mqtt enable=off broker= topic= password= username= qos=0 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0 
# notify_nats enable=off address= subject= username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 jetstream=off streaming=off streaming_async=off streaming_max_pub_acks_in_flight=0 streaming_cluster_id= queue_dir= queue_limit=0 
# notify_nsq enable=off nsqd_address= topic= tls=off tls_skip_verify=off queue_dir= queue_limit=0 
# notify_mysql enable=off format=namespace dsn_string= table= queue_dir= queue_limit=0 max_open_connections=2 
# notify_postgres enable=off format=namespace connection_string= table= queue_dir= queue_limit=0 max_open_connections=2 
# notify_elasticsearch enable=off url= format=namespace index= queue_dir= queue_limit=0 username= password= 
# notify_redis enable=off format=namespace address= key= password= queue_dir= queue_limit=0 
# etcd endpoints= path_prefix= coredns_path=/skydns client_cert= client_cert_key= 
# cache drives= exclude= expiry=90 quota=80 after=0 watermark_low=70 watermark_high=80 range=on commit= 
storage_class standard= rrs=EC:1 
heal bitrotscan=off max_sleep=1s max_io=100
```
* Response on error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>RequestTimeout</Code>
    <Message>A timeout occurred while trying to lock a resource, please reduce your request rate</Message>
    <Key>Localizations/production.json</Key>
    <BucketName>pcc2</BucketName>
    <Resource>/pcc2/Localizations/production.json</Resource>
    <Region>general</Region>
    <RequestId>REDACTED</RequestId>
    <HostId>REDACTED</HostId>
</Error>
```
* `mc admin trace` entry:
```
2022-12-29T18:57:38.981 [503 Service Unavailable] s3.PutObject REDACTED_HOST/pcc2/Localizations/production.json REDACTED_IP    5m1.309072s  ↑ 1.4 MiB ↓ 424 B
```
* `lsblk -f`:
```
NAME        FSTYPE LABEL  UUID                                 FSAVAIL FSUSE% MOUNTPOINT
nvme0n1                                                                       
├─nvme0n1p1 swap          73e4a078-9120-4b37-8855-77ccacca6ba2                [SWAP]
├─nvme0n1p2 ext3          c13b2c78-f391-4f20-99d7-0608ead73ad2    767M    16% /boot
└─nvme0n1p3 ext4          8ebbe113-c632-4cc9-84e3-b82408810e96  104.5G    71% /
nvme1n1                                                                       
└─nvme1n1p1 xfs    Minio1 bc7de3b4-c3ad-4b52-bb7d-9d221da4dbd6  450.3G     6% /mnt/nvme1
nvme2n1                                                                       
└─nvme2n1p1 xfs    Minio2 5ab5c44c-2eaf-40ef-9db0-a9f5a8bae3a8  450.3G     6% /mnt/nvme2
nvme3n1                                                                       
└─nvme3n1p1 xfs    Minio3 ac7f63c9-9d07-4e1d-82d8-6c2f185f230c  450.3G     6% /mnt/nvme3
```
* `/etc/fstab` content:
```
proc /proc proc defaults 0 0
# /dev/nvme0n1p1
UUID=73e4a078-9120-4b37-8855-77ccacca6ba2 none swap sw 0 0
# /dev/nvme0n1p2
UUID=c13b2c78-f391-4f20-99d7-0608ead73ad2 /boot ext3 defaults 0 0
# /dev/nvme0n1p3
UUID=8ebbe113-c632-4cc9-84e3-b82408810e96 / ext4 defaults 0 0

# Storage Disks
LABEL=Minio1 /mnt/nvme1 xfs defaults,noatime 0 2
LABEL=Minio2 /mnt/nvme2 xfs defaults,noatime 0 2
LABEL=Minio3 /mnt/nvme3 xfs defaults,noatime 0 2
```
* `mc cp` failure log: https://pastebin.com/Huw6QsE7

**Comment by klauspost** [comment]
What you are seeing is expected behavior. Locks are handed out on a per object basis. When you continuously have multiple readers of an object, the writer is unlikely to ever get a lock. We do not distinguish between read and write locks, but for a write lock to succeed all readers have to be released.

We are investigating locking alternatives, which would include more fine-grained locks and functionality that will block read locks once a write lock request comes in for a version. But there is no timeframe for that feature.

The underlying (file) system does not matter here.

**Comment by arthur-vilgursky** [comment]
Are there any ways to change it now, maybe there is some sort of force unlock option or any different behavior when versioning is enabled?

**Comment by klauspost** [comment]
It is locked for a reason. Forcing unlocks would just break things even more.,

Behavior is the same with versioning, but may improve in the future.
