### ISSUE TITLE
The minio synchronized data monitoring index is wrong. How to repair the monitoring index data

### ISSUE THREAD

**Issue by yueyangqingshu** [minio/minio#16519]
I synchronized about 2 t of data from the source server by using the mc cp command. The console metrics of the synchronized target minio did not match the number of buckets, the number of objects and the number of disks. The data is stored on the disk and can be accessed. At present, the data and synchronization are finished, and the mirror command of mc is executed for incremental synchronization. Is there any way to repair the console monitoring? I couldn't find a solution in the documentation on the official website

![image](https://user-images.githubusercontent.com/54011177/216215352-5dc392d5-1705-4f66-b0eb-b369ff91e95f.png)
![image](https://user-images.githubusercontent.com/54011177/216215385-7963f35b-9627-453d-a886-ad1e7e692d5e.png)

**Comment by yueyangqingshu** [comment]
The actual number of buckets is 72, but the statistics panel only has 55 and a lot of other metrics are wrong
I really need your help

**Comment by harshavardhana** [comment]
The metrics gets updated in time, there is no realtime update.

**Comment by harshavardhana** [comment]
Also you haven't explained anything about your set-up. We cannot imagine your deployment - please state all of these while reporting issues in the future.
