### ISSUE TITLE
Shorter signed-urls

### ISSUE THREAD

**Issue by yunylz** [minio/minio#16525]
Hello, I've been using minio on my Node.JS REST API and I really like it but I have some routes where I respond the client with pre-signed URLs and they make the result look extremely long so I was wondering if there's any chance we could get shorter pre-signed urls? For example, this is how akamai signed URLs are

`https://example.com/images/hello.jpg?auth=exp=1670101719~acl=/images/*~hmac=532c5eaee0fb1e6718125a0a3ea4d690d48f0cbbae61cffe8a9808c0a811859b`

Meanwhile minio on the other hand... is extremely... LONG

`https://example.com/example-bucket/images/hello.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XsoFHNBBWEy6voES/20230202/eu-central-1/s3/aws4_request&X-Amz-Date=20230202T020625Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=737e07111f3a11296da67e5d72417aedee3a12a08f06062a1f87936641a89367`

**Comment by harshavardhana** [comment]
Unfortunately everything here is S3 compatible and we can't change such things.

Sorry 😔
