### ISSUE TITLE
Wrong notify_kafka config cause minio server crash~

### ISSUE THREAD

**Issue by shibozai** [minio/minio#16522]
## Expected Behavior

When kafka config is outdated or invalid,Minio will ignore the invalid config and running normally.

## Current Behavior

My minio's old version is 2022-03-26T06:49:28Z,and I've added a notify_kafka config by using "mc admin config set notify_kafka" command,it works well at that time. Then I upgrade my minio server version to 2023-01-02T09-40-09Z, and the kafka server is down before the upgrade.And then I've found that my minio can not work normally,the log shows that there's a nil pointer error at the line 324 of internal/event/target/kafka.go.
https://github.com/minio/minio/blob/2278fc8f47eadf4a53452334bdd0dfbe3183a6b0/internal/event/target/kafka.go#L319-L327

## Possible Solution

Since I can't use "mc admin config set" to switch notify_kafka off( I don't know why ;( ),also I can't see the old config in the dashboard( also has no clue ),so I removed all xl.meta files under '.minio.sys/config/config.json' and restart minio.And for now my minio has running normally without crash.
For the code(to be honest,i'm not good at GO),i can't find the initialization of 'target.producer' before this line 324,so I think maybe you should validate the 'target.producer' whether it's nil or not before call its 'Close()' func.

## Steps to Reproduce (for bugs)

1.Config a wrong kafka server host
2.Start minio
3.Wait for lazyinit of kafka notification

## Your Environment

* Version used (`minio --version`):2023-01-02T09-40-09Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
Fix in #16523
