### ISSUE TITLE
ListObjectsV2 got "reading first part metadata: EOF (*fmt.wrapError)" exception sometimes

### ISSUE THREAD

**Issue by chenheng87** [minio/minio#16520]
## NOTE
when list object with multiFiles(300_000+)，'We encountered an internal error, please try again.: cause(reading first part metadata: EOF)' sometimes happened.

## Expected Behavior
always success

## Current Behavior
sometimes got this exception:
```
API: ListObjectsV2
Time: Invalid Date
DeploymentID: bb92e039-6fc2-4ff1-9c09-44b9a330fdf6
RequestID: 173FF2E7D205B0C8
RemoteHost: AA.BB.CC.DD
UserAgent: MinIO (Windows 10; amd64) minio-java/8.4.6
Error: Resuming listing from drives failed reading first part metadata: .minio.sys/buckets/bbtmp/.metacache/3e392086-efc3-4b0e-8d8a-6c116b5e6e00/block-0.s2 has incomplete body, proceeding to do raw listing (*fmt.wrapError)
```
## Your Environment

* Version used (`minio --version`):minio-RELEASE.2023-01-02T09-40-09Z
* Server setup and configuration: minio server --address ":9000" --console-address ":9001" ./data
* Operating System and version (`uname -a`):Linux NewArcBAK1 3.10.0-1160.71.1.el7.x86_64  SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@chenheng87 please explain your setup, share some logs. 

You haven't done none of this. Closing as insufficient information.
