### ISSUE TITLE
fsGroup: unknown field Validation error in helm chart

### ISSUE THREAD

**Issue by christophsing** [minio/minio#16521]
We do have a Problem applying your helm chart because we are running in a fsGroup issue. 
seems to be similar to this issue:

https://github.com/minio/operator/issues/612

```
error: error validating "/tmp/minio.yaml": error validating data: [ValidationError(Job.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(Job.spec.template.spec.containers[1].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false
```

```
❯ kubectl explain pod.spec.containers.securityContext.fsGroup
error: field "fsGroup" does not exist
```
fsGroup does not exist in containers - just in pod spec itself:
```
❯ kubectl explain pod.spec.securityContext.fsGroup
KIND:     Pod
VERSION:  v1

FIELD:    fsGroup <integer>
```

## Expected Behavior
applying helm chart straigt out of your repo without customizing the chart.

## Current Behavior
deployment not possible becaues of fsGroup in containers section.
already fixed in your Code: 
https://github.com/minio/minio/pull/16402

but not in:
```
❯ helm search repo minio    
NAME            CHART VERSION   APP VERSION                     DESCRIPTION                                       
minio/minio     5.0.4           RELEASE.2022-12-12T19-27-27Z    Multi-Cloud Object Storage                        
```

## Possible Solution
remove the field from containers section - as this field is not available there. 

field has no impact there and could be removed

## Steps to Reproduce (for bugs)

1. helm template  . | kubectl apply -f -
2. the error above will show up then.

## Context
we try to use good upstream charts without copy, download and modify those charts

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Released v5.0.5
