### ISSUE TITLE
OpenID Connect and LDAP based with DN

### ISSUE THREAD

**Issue by mvbsm** [minio/minio#16532]
**Is your feature request related to a problem? Please describe.**
I would like to have mapping of OpenID Connect to LDAP based on claim from Keycloak with DN and link same users.

**Describe the solution you'd like**
I would like to have integration with OpenID Connect and simultaneously LDAP to control user service accounts & groups from mc admin and also have an uniform Keycloak login page.

**Describe alternatives you've considered**
There is no solution that has all the features.

**Additional context**
No any other context or screenshots about the feature request.

**Comment by harshavardhana** [comment]
Currently, this is out of scope, we may do it in the future to make OpenID and LDAP co-exist. But currently, it's a bigger design change.

We are not currently venturing into this area - if you have a production requirement please subscribe to your deployment so we may expedite this https://min.io/pricing
