### ISSUE TITLE
scraping endpoint forwards requests from port 9000 to port 9001/dashboard

### ISSUE THREAD

**Issue by christophsing** [minio/minio#16533]
scraping minio pods with an older version of minio works as expected. 
with this latest helm chart and minio version the pod is forwarding a scraping request to port http://localhost:9001/dashboard instead of delivering the metrics from http://ocalhost:9000/minio/v2/metrics/cluster

## Expected Behavior
inside the minio pod a curl from the metrics works as expected:
```
sh-4.4$ curl localhost:9001/minio/v2/metrics/cluster
# HELP minio_audit_failed_messages Total number of messages that failed to send since start
# TYPE minio_audit_failed_messages counter
minio_audit_failed_messages{server="minio-0.minio-svc.storage.svc.cluster.local:9000",target_id="sys_console_0"} 0
minio_audit_failed_messages{server="minio-1.minio-svc.storage.svc.cluster.local:9000",target_id="sys_console_0"} 0
```

## Current Behavior
minio is forwarding scraping request to dashboard login instead of delivering metrics

## Possible Solution
check older working code 

## Steps to Reproduce (for bugs)

1. kubectl exec -it -n storage minio-0 -- /bin/sh
2. curl localhost:9001/minio/v2/metrics/cluster
3. leave pod
4. kubectl port-forward -n storage minio-0 9000
5. open browser and http://localhost:9000/minio/prometheus/metrics

## Context
Scraping of minio is not possible with this setup

## Regression
yes

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
MinIO has no such forward rules, unless you are passing in some random user agents that are setting Mozilla as part of their user-agent.

Browser will always redirect for /minio requests that's by design.
