### ISSUE TITLE
Minio suddenly expects a different storage for existing files

### ISSUE THREAD

**Issue by redhead** [minio/minio#16546]
## Context

Originally, we ran into [the issue with CORS headers not being sent back correctly](https://github.com/minio/minio/issues/11111). We tried to resolve it by deleting the `minio_sys` expecting that the configuration will be somehow restored automatically. This actually worked and the CORS headers started to work. Also, it seemed our app worked with the original files and the new uploads too. 

However, now the data in buckets are not accessible (the files are not found by our app, although they are present in the buckets), we tried uploading new files, and that worked (upload and download too). We examined the storage and found out that the old files have a different folder/file structure than the new files uploaded: Instead of just the file itself, there is a folder of the same name as the uploaded file containing part and xl.meta file. 

So my suspicion is that minio suddenly expects a different file/folder structure for the old files (that is creating for the new files). And as we are not able to find a good way out of this, I am rather asking here. Do you have an idea what we should do about it?

## Expected Behavior
After deleting `minio_sys` folder, we expected that everything will work fine.

## Current Behavior
Files uploaded before deleting `minio_sys` folder are not accessible now even though they exist in the buckets on the correct paths. Newly uploaded files work fine.

## Your Environment
* Version used (`minio --version`): RELEASE.2022-07-24T01-54-52Z
* Server setup and configuration: no custom configuration (before or after)

**Comment by harshavardhana** [comment]
> So my suspicion is that minio suddenly expects a different file/folder structure for the old files (that is creating for the new files). And as we are not able to find a good way out of this, I am rather asking here. Do you have an idea what we should do about it?

It is not sudden @redhead this has been communicated in the past https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html

There is no transparent migration from previous FS to new backend you need to migrate your setup.

**Comment by redhead** [comment]
But we use the same version of minio without any custom configuration.
