### ISSUE TITLE
Downloading Items results in a 403

### ISSUE THREAD

**Issue by PeterPilley** [minio/minio#16554]
Running minio in swarm mode, attempting to download content from the minio store fails with s3browser, cyberduck and minio console

## Expected Behavior
Attempting to download items within the object browser should download the file

## Current Behavior
Unexpected response status code (403)., if I share the item and get a presigned url I am able to view. but cannot download using any tool

## Possible Solution
None

## Steps to Reproduce (for bugs)

1. Upload content
2. attempt to download

## Context
Has been an issue since last year, I have moved to the latest release of minio to see if it has been resolved but dont think it has.

Current Policy
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::data/",
                "arn:aws:s3:::data/*",
                "arn:aws:s3:::data/image",
                "arn:aws:s3:::data/image/*",
                "arn:aws:s3:::data/video",
                "arn:aws:s3:::data/video/*"
            ]
        }
    ]
}

**Comment by PeterPilley** [comment]
Just ran a test with the minio python library with the same user account and can download content without any issue. 

so via cyberduck or minio console s3.getObject results in 403, using minio library s3.getObject results in 200

**Comment by ravindk89** [comment]
> Running minio in swarm mode

I don't think we have ever supported Docker Swarm. Our guidance thus far is to either use Compose or K8s. 

Absent any logs from Swarm or MinIO here there's also very little for us to follow up on.

**Comment by ravindk89** [comment]
@PeterPilley absent any further information I don't see how we can help. Again, Swarm is not one of the deployment models we support, so between that an no logs, trace data, etc. - we have to close this.

If you want to revisit this, I suggest using a combination of `mc admin trace` and watching MinIO logs while testing so you have a clearer picture of where calls succeed/fail.
