### ISSUE TITLE
Running `mb` inside a bucket seems to cause path recursion

### ISSUE THREAD

**Issue by chjz1024** [minio/minio#16558]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Should raise an error indicating it's not proper to create a bucket inside a bucket.

## Current Behavior

The command runs without a warning, but I cannot use the web console to list the objects inside the path(bucket). No local directory is created either.

## Steps to Reproduce (for bugs)

1. Create an alias for the deployment as detuser
2. Create a bucket named share.

```shell
chjz@b2x2080ti:~$ mc mb detuser/share/chjz
Bucket created successfully `detuser/share/chjz`.
chjz@b2x2080ti:~$ mc ls detuser/share/chjz
[2023-02-07 22:36:30 CST]     0B STANDARD /
chjz@b2x2080ti:~$ mc ls detuser/share/
[2023-02-07 22:37:03 CST]     0B chjz/
chjz@b2x2080ti:~$ ls
Desktop    Downloads    miniconda3      Music     Public  Templates  workspace
Documents  linuxserver  minio-binaries  Pictures  snap    Videos
```

## Your Environment

* Version used (`minio --version`):
```shell
$ minio --version
minio version RELEASE.2023-01-31T02-24-19Z (commit-id=2d0f30f062e9ec3da8887e5ee64f59f5cea03240)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration: As above.
* Operating System and version (`uname -a`):
```shell
$ uname -a
Linux System-Product-Name 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
> ```shell
> chjz@b2x2080ti:~$ mc mb detuser/share/chjz
> Bucket created successfully `detuser/share/chjz`.
> chjz@b2x2080ti:~$ mc ls detuser/share/chjz
> [2023-02-07 22:36:30 CST]     0B STANDARD /
> chjz@b2x2080ti:~$ mc ls detuser/share/
> [2023-02-07 22:37:03 CST]     0B chjz/
> ```

This is on purpose @chjz1024 it is not recursion, it just shows the top level folder as `/`  since that is where the folder ends as `chjz/` 

Nothing to be confused with.

**Comment by harshavardhana** [comment]
To elaborate what you did was create an `object` that ends with `/` that's all. It is called a directory object but it is totally unnecessary to do this. 

We have allowed this to keep it similar to AWS S3 but we think that this is a wrong feature and should never be used in reality - and you simply should just upload an object

```
mc cp myfile detuser/share/chjz/myfile
```

This automatically creates the parent directories, you do not need to do things like POSIX folders.

**Comment by chjz1024** [comment]
@harshavardhana Many thanks! Exactly solved my question.
