### ISSUE TITLE
Lifecycle configuration not syncronized across minio servers properly

### ISSUE THREAD

**Issue by cskoszeg** [minio/minio#16553]
## Your Environment
minio-version: "RELEASE.2022-12-07T00-56-37Z"
mc-version: "RELEASE.2022-08-23T05-45-20Z"
kes-version: "0.21.1"

## Fault description
Hi,
We have 4 server minio cluster with 1disk/server. When I stop one server and configure lifecycle rule on a bucket it works perfect. After I start the stopped minio instance and fetch the configured lifecycle config from the just started minio it shows different/none config. The rest of the nodes shows correct ilm config. It seems that the ilm config not synced among servers correctly.
Please correct the fault as it is not intermittent and affects the storage health/capacity

## Steps to Reproduce (for bugs)

mc ilm set s3/test --expiry-days 100              # where s3 is the address of the minio service load ballanced by k8s
#stop one minio server <minioX>
mc ilm edit -id=<id_of _the_rule_above> s3/test --expiry-days 101 
#start minio server <minioX>
mc ilm ls <minioY>/test          #shows correct value 101, where <minioY> the address of the minio Y (not eq X)
mc ilm ls <minioX>/test          #shows 100, the value set before stop/start
#And it remains forever until I issue service restart. Fom now 'mc ilm ls s3/test' sometimes shows incorrect (100) value depends on which node the request goes to.

## Expected Behavior
The ILM settings should be syncronized across the minio cluster

## Current Behavior
See at reproduction

## Possible Solution
When minio starts up, sync all ILM settings and join the cluster synced.

**Comment by harshavardhana** [comment]
@cskoszeg can you test this with latest release?

**Comment by poornas** [comment]
Tried to repro the issue with a bare metal setup - killing and starting one of the nodes in between ilm updates shows correct config.

It appears you are just issuing stop , start on docker container - is this correct @cskoszeg? lifecycle config is cached in memory and will not be reloaded if you just pause the container.

**Comment by cskoszeg** [comment]
> It appears you are just issuing stop , start on docker container

Actually restart kubernetes pod with the minio or alternatively scale statefulset to 3 from 4 and back to 4 after adding ILM rule.

**Comment by harshavardhana** [comment]
Before we go any further @poornas, @cskoszeg we expect issue reports with the latest releases. We do not address any older issues that may or may not have been fixed. 

As a community user, you should always upgrade, test and if seen again report here.

**Comment by harshavardhana** [comment]
Let's take this via subnet https://subnet.min.io/issues/7483
