### ISSUE TITLE
A successful single put object causes failure of running multipart put - May 18th

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1655]
Steps to reproduce
1. Start minio server

``` bash
minio server d{0..7}
```
1. create a bucket

``` bash
mc mb myminio/mybucket
```
1. upload a big file then upload small file

``` bash
mc cp zero101 myminio/mybucket/zero& sleep 2; mc cp zero4 myminio/mybucket/zero
```

We get error `mc: <ERROR> Failed to copy ‘zero101’. Object key is missing, object key cannot be empty`

minio version

``` bash
$ minio version
Version: 2016-05-17T00:30:55Z
Release-Tag: DEVELOPMENT.2016-05-17T00-30-55Z
Commit-ID: 1760687c83aa43f8d2ba99d44d0ba12f5fa88be8
```

**Comment by harshavardhana** [comment]
This bug is same issue as parallel multipart put.

**Comment by GarimaKapoor** [comment]
Harsha, please update the timeline for the fix.

**Comment by harshavardhana** [comment]
Fixed in the current master - fixed by @krishnasrinivas
