### ISSUE TITLE
lost users when normally using

### ISSUE THREAD

**Issue by wann-he** [minio/minio#16556]
I lost all users when normally using.
Some accesskey occasionally appears for a while and disappeared when use it. And the permissions granted to the ak is the same with it used to be.Now I can't recognize where the problem is.

minio server version is  2022-07-26T00:53:03Z

**Comment by harshavardhana** [comment]
@wann-he please report issues properly. Also make sure you upgrade to latest, enable audit logging to see who is accessing the cluster.

Without any such report we shall close this issue.
