### ISSUE TITLE
After expand tenant pools,the Server Failures Tolerated still the same

### ISSUE THREAD

**Issue by npu21** [minio/minio#16557]
**Is your feature request related to a problem? Please describe.**

For example ,if a tenant  deployed with 4 servers and 1 drive per server ,the Server Failures Tolerated(default Erasure Code Parity) will be 2. 
After expanding this tenant with a new pool which is also 4 servers and 1 drive per server, now there're 8 servers and 8 dirves.
However, the minio cluster still tolerate 2 server down.
If bring down two pool pods, the wirte/read will come error.

**Describe the solution you'd like**

The Server Failures Tolerated expanded accordingly  also.
Is there a way to recalculate the Erasure Code Parity or other way to also expand the Server Failures Tolerated?

**Comment by harshavardhana** [comment]
That is expected, pool expansion is by design only for capacity expansion and throughput. It does not expand on HA or server failure tolerance. 

If you want higher tolerance, move to a higher SLA setup.
