### ISSUE TITLE
Support decommissioning on ILM tiered buckets

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#16565]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Decommissioning should work even if tiering is enabled

## Current Behavior
Decommissioning doesn't work if tiering is enabled

## Steps to Reproduce (for bugs)
1. Start MinIO with 2 or more pools
2. Enable ILM tiering on buckets and have some objects tiered
3. Try decommissioning on one of the pools
4. It will fail to start

## Regression
No

**Comment by harshavardhana** [comment]
This is fixed and merged #16751
