### ISSUE TITLE
[feature] Option to disable croos mounts checks

### ISSUE THREAD

**Issue by aureq** [minio/minio#16576]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Problem statement

I'm currently running minio at home on a small cluster (3 nodes). I have some volumes that are replicated across the 3 nodes using Longhorn. One of the purpose of minio is to receive backups for my Kubernetes volumes (since Minio is compatible with S3).

In order to cut cost on local storage, I have purchased some extra online storage (one-time fee). I expose that online storage via a locally mounted mount-point on my 3 nodes using rclone / fuse.

However, I'm unable to project that remote mount-point into a sub-folder of Minio (for data, not `.minio.sys`) because Minio detects there's an intermediate mount-point by reading `/proc/mounts`. See [`checkCrossMounts(path string)`](https://github.com/minio/minio/blob/master/internal/mountinfo/mountinfo_linux.go#L88-L115). This effectively prevents minio from starting and becoming online.

I _could_ map the mount-point to `/export`, however since the content of `.minio.sys` seems to be permanently accessed (read and write), this kills the performances of that remote mount-point and my internet connection.

## Feature request

It would be amazing to be able to configure minio so it doesn't check for any intermediate mounts in `/export` sub-folders so it would be possible to project other mount-points while allowing `.minio.sys` to be replicated across the cluster.

## Alternatives

I initial considered projecting the remote mount-point in `/export` but unfortunately this wasn't a viable option due to `.minio.sys` being constantly accessed (read/write) which kills performance as well as creating a lot of network traffic.

I also considered recompiling minio myself (minus the call to the function above) but the cost of maintenance for each upgrade feels quite prohibitive.

I could also go with another volume provider like CEPH or OpenEBS, but

* It took me quite some time to get Longhorn working that I'd rather prefer not change my storage layer (I don't have any spare hardware to experiment with this)
* Since I can't test, I also have not much guarantee the alternative of using CEPH would work either with a remote mount-point.

**Comment by harshavardhana** [comment]
@aureq cross mounts are not allowed and will never be allowed. 

We require the backend paths to be on the same drive to allow atomic renames()

You may fork and make changes. But we won't do unsafe changes in MinIO.

**Comment by aureq** [comment]
This is quite annoying since I'm running a single minio pod at a time (also due to cost). I understand this is not what minio would recommend, however this would help community users on a low budget to use this software quite nicely.

I also think that, if minio was to implement, it should come with some extra warning to make it clear this is not a supported option.

**Comment by harshavardhana** [comment]
> This is quite annoying since I'm running a single minio pod at a time (also due to cost). I understand this is not what minio would recommend, however this would help community users on a low budget to use this software quite nicely.
> 

Unfortunately we can't, we can't compromise on rename() guarantees. You may not care but we are storage system we have to care.

> I also think that, if minio was to implement, it should come with some extra warning to make it clear this is not a supported option.

It is shown as an error when you start the server. That is sufficient in this context.
