### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by xinmeipublic** [minio/minio#16586]
when I start 10K goroutine download files from minio server, the following problems occur with 100% probability:

Get "http://192.168.4.232:9000/test49/6598.bin": dial tcp 192.168.4.232:9000: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
read tcp 192.168.4.18:65221->192.168.4.232:9000: wsarecv: An existing connection was forcibly closed by the remote host.
read tcp 192.168.4.18:65414->192.168.4.232:9000: wsarecv: An existing connection was forcibly closed by the remote host.
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
read tcp 192.168.4.18:65311->192.168.4.232:9000: wsarecv: An existing connection was forcibly closed by the remote host.
A timeout exceeded while waiting to proceed with the request, please reduce your request rate
A timeout exceeded while waiting to proceed with the request, please reduce your request rate

The information of minio server is as follows:
1. Minio server is deployed in windows environment
2. 4 Notes * 4 Drivers

Test script：
`package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"strconv"
	"sync"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

// 创建指定大小的文件
func createFile(size int64, count int64) {
	var wg sync.WaitGroup
	bT := time.Now()
	fmt.Println("Now time: ", bT)
	for i := int64(1); i <= count; i++ {
		wg.Add(1)

		go func(i int64) {
			defer wg.Done()
			p := "./../files"
			os.MkdirAll(p, os.ModeDir)
			path := fmt.Sprintf("%s/%d.bin", p, i)
			f, err := os.Create(path)
			if err != nil {
				log.Fatal(err)
			}
			defer f.Close()

			if err := f.Truncate(size); err != nil {
				log.Fatal(err)
			}
		}(i)

	}
	wg.Wait()
	eT := time.Since(bT)
	fmt.Println("End time: ", eT)

}

func readAllIntoMemory(filename string, id string) (content []byte, err error) {
	fp, err := os.Open(fmt.Sprintf("./../files/%s.bin", filename)) // 获取文件指针
	if err != nil {
		return nil, err
	}
	defer fp.Close()
	fileInfo, err := fp.Stat()
	if err != nil {
		return nil, err
	}
	buffer := make([]byte, fileInfo.Size())
	_, err = fp.Read(buffer) // 文件内容读取到buffer中
	if err != nil {
		return nil, err
	}
	p := "./../copy"
	p = fmt.Sprintf("%s%s", p, id)
	os.MkdirAll(p, os.ModeDir)
	filename = fmt.Sprintf("%s.bin", filename)
	fo, err := os.OpenFile(path.Join(p, filename), os.O_WRONLY|os.O_CREATE, 0666) // 获取文件指针
	if err != nil {
		return nil, err
	}
	defer fo.Close()
	fo.Write(buffer)
	return buffer, nil
}

func copyFiles(count int64) {
	var wg sync.WaitGroup

	id := int64(0)
	testTime := int64(10)

NEXT:

	if testTime > 0 {
		id += 1
		testTime -= 1
	} else {
		return
	}

	bT := time.Now()
	fmt.Println("Now time: ", bT)
	for i := int64(1); i <= count; i++ {
		wg.Add(1)
		go func(i int64, id int64) {
			_, err := readAllIntoMemory(strconv.FormatInt(i, 10), strconv.FormatInt(id, 10))
			if err != nil {
				fmt.Println(1, err)
			}
			wg.Done()
		}(i, id)
	}
	wg.Wait()
	eT := time.Since(bT) // 从开始到当前所消耗的时间
	fmt.Println("Run time: ", eT)

	goto NEXT
}

func uploadMinio(count int64) {
	ctx := context.Background()
	endpoint := "192.168.4.232:9000"
	accessKeyID := "admin"
	secretAccessKey := "12345678"
	useSSL := false
	// minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln("创建 MinIO 客户端失败", err)
		return
	}
	log.Printf("创建 MinIO 客户端成功")

	testTimes := 2
	id := 47

NEXT:

	if testTimes > 0 {
		testTimes -= 1
		id += 1
	} else {
		return
	}
	// 创建一个叫 mybucket 的存储桶。
	bucketName := "test"
	bucketName = fmt.Sprintf("%s%d", bucketName, id)
	location := "beijing"

	// err = minioClient.MakeBucket(bucketName, location)
	err = minioClient.MakeBucket(ctx, bucketName, minio.MakeBucketOptions{Region: location})
	if err != nil {
		// 检查存储桶是否已经存在。
		exists, err := minioClient.BucketExists(ctx, bucketName)
		if err == nil && exists {
			log.Printf("存储桶 %s 已经存在", bucketName)
		} else {
			log.Fatalln("查询存储桶状态异常", err)
		}
	}
	log.Printf("创建存储桶 %s 成功", bucketName)

	var wg sync.WaitGroup
	bT := time.Now()
	fmt.Println("Now time: ", bT)
	for i := int64(1); i <= count; i++ {
		wg.Add(1)
		go func(i int64) {

			// 指定上传文件为 test.txt
			objectName := fmt.Sprintf("%d.bin", i)
			// 指定上传文件路径
			filePath := fmt.Sprintf("./../files/%s", objectName)
			// 指定上传文件类型
			contentType := "application/octet-stream"

			// 调用 FPutObject 接口上传文件。
			_, err = minioClient.FPutObject(ctx, bucketName, objectName, filePath, minio.PutObjectOptions{ContentType: contentType})

			// 调用 FPutObject 接口上传文件。
			// file, err := os.Open(filePath)
			// if err != nil {
			// 	fmt.Println(err)
			// 	return
			// }
			// defer file.Close()
			// fileStat, err := file.Stat()
			// if err != nil {
			// 	fmt.Println(err)
			// 	return
			// }
			// _, err = minioClient.PutObject(ctx, bucketName, objectName, file, fileStat.Size(), minio.PutObjectOptions{ContentType: contentType})
			if err != nil {
				log.Fatalln("上传文件失败", err)
			}
			wg.Done()
		}(i)
	}
	wg.Wait()
	eT := time.Since(bT) // 从开始到当前所消耗的时间
	fmt.Println("Run time: ", eT)

	goto NEXT

	// log.Printf("上传文件 %s 成功\n", objectName)

}

func download(count int64) {
	ctx := context.Background()
	endpoint := "192.168.4.232:9000"
	accessKeyID := "admin"
	secretAccessKey := "12345678"
	useSSL := false
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln("创建 MinIO 客户端失败", err)
		return
	}
	log.Printf("创建 MinIO 客户端成功")
	// 创建一个叫 mybucket 的存储桶。
	bucketName := "test49"
	// location := "beijing"
	var wg sync.WaitGroup

	testTimes := 4
	id := 0

NEXT:

	if testTimes > 0 {
		testTimes -= 1
		id += 1
	} else {
		return
	}

	bT := time.Now()
	fmt.Println("Now time: ", bT)
	for i := int64(1); i <= count; i++ {
		wg.Add(1)
		go func(i int64) {
			defer wg.Done()
			// 指定上传文件为 test.txt
			objectName := fmt.Sprintf("%d.bin", i)
			// 指定上传文件路径
			p := "./../output"
			p = fmt.Sprintf("%s%d", p, id)
			os.MkdirAll(p, os.ModeDir)
			filePath := path.Join(p, objectName)
			// err := minioClient.FGetObject(ctx, bucketName, objectName, filePath, minio.GetObjectOptions{})

			object, err := minioClient.GetObject(ctx, bucketName, objectName, minio.GetObjectOptions{})
			if err != nil {
				fmt.Println(err)
				return
			}
			defer object.Close()
			localFile, err := os.Create(filePath)
			if err != nil {
				fmt.Println(err)
				return
			}
			defer localFile.Close()
			if _, err = io.Copy(localFile, object); err != nil {
				fmt.Println(err)
				return
			}
		}(i)
	}
	wg.Wait()
	eT := time.Since(bT) // 从开始到当前所消耗的时间
	fmt.Println("Run time: ", eT)
	goto NEXT
}

func main() {
	// var size = int64(1024 * 100)
	var count = int64(10000)
	// 生成指定大小文件
	// createFile(size, count)

	// 内存读取到文件中
	// copyFiles(count)

	// 上传minio
	// uploadMinio(count)

	// 上传minio
	download(count)
}
`

**Comment by harshavardhana** [comment]
As the error message indicates you are running out of number of requests possible on your setup.

You cannot just run random number of goroutines concurrently and expect them to work. Each deployment must be sized appropriately.

Please bring in more resources for MinIO to handle your workload.
