### ISSUE TITLE
XL : Server frozen during Object insertion ops. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1659]
While running `exec-concurrent.go` tests at a concurrency level of 500 , most of the `putObject` tests freeze and eventually timeout. What's really concerning is that the CPU shows inactivity, so the timeout is not due to server busy with processing. Seems to be a serious issue, need to investigate more. 

Here are some of the tests to replicate it 
`sudo ./exec-concurrent "TestResumableFPutObject”`
`sudo ./exec-concurrent "TestFPutObject”`
`sudo ./exec-concurrent "TestResumablePutObject”`

**Comment by harshavardhana** [comment]
This issue is still there, able to reproduce successfully.

**Comment by harshavardhana** [comment]
This issue is non-existant after avoiding usage of `crand.Reader` using `bytes.Repeat` resolves the problem of bootstrap time for large go-routines.
