### ISSUE TITLE
Access for buckets ignored in  RELEASE.2023-02-09T05-16-53Z update

### ISSUE THREAD

**Issue by markovendelin** [minio/minio#16590]
I have access given to users through

```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}-*"
            ]
        }
    ]
}
```

So far, it worked well: users could create the buckets as needed and use them. However, with RELEASE.2023-02-09T05-16-53Z, users lost access to all such buckets. If you login into console as a user, no buckets are listed under "Object browser" nor under Admin/Buckets.

In RELEASE.2023-01-25T00-19-54Z, all works as expected. Users have access to buckets and can see them in console as well.

* Server setup and configuration: docker/Standalone/ZFS

**Comment by harshavardhana** [comment]
Console UI doesn't support this anymore for some reason @markovendelin 

Have you tried `mc ls` ?

**Comment by harshavardhana** [comment]
Looks like some regression will verify @markovendelin - `mc ls` works.

**Comment by harshavardhana** [comment]
I found the problem

**Comment by markovendelin** [comment]
Thanks for lightning-fast response! I haven't tried `mc ls`, it just failed with Kopia and I started digging into it via console. As you found the bug already, I presume there is no need to test with `mc`. Please let me know if `mc` test is still needed.

**Comment by harshavardhana** [comment]
> Thanks for lightning-fast response! I haven't tried `mc ls`, it just failed with Kopia and I started digging into it via console. As you found the bug already, I presume there is no need to test with `mc`. Please let me know if `mc` test is still needed.

Not needed @markovendelin
