### ISSUE TITLE
Programmatically manage svcacct account for external entities configured with OIDC

### ISSUE THREAD

**Issue by alexisdondon** [minio/minio#16595]
**Is your feature request related to a problem? Please describe.**
I would like oidc STS have the same functional scope that other externals managed entities allowing mc admin user svcacct to programmatically add/edit/delete an service account for an external user.

The user can do this manually in the minio console but my users are not intended to well know the session policy to put to restrict the account at just what needed.

**Describe the solution you'd like**
same than other external managed entities it could be that minio take a decision about the id of the user to be mapped from the jwt content like a configured claim name (up to the organisation to manage a proper unique id in the oidc jwt)

**Describe alternatives you've considered**
Create managed user programmatically instead of user svcacct to give access and secret key to the external user.

**Additional context**
Not needed.

**Comment by harshavardhana** [comment]
For that you need to find a way to authenticate to OIDC via using something called as credentials grant. With Credentials Grant you get a JWT then use

https://pkg.go.dev/github.com/minio/minio-go/v7@v7.0.47/pkg/credentials#NewSTSClientGrants

Once you have those grants, assuming you have the right permissions generalize it by passing these credentials to https://pkg.go.dev/github.com/minio/madmin-go/v2?utm_source=godoc#Options

https://pkg.go.dev/github.com/minio/madmin-go/v2?utm_source=godoc#AdminClient.AddServiceAccount

And there you go you have a programmatic way to do it. Of course, this is Go language-specific and purposefully so written in the cloud native language of choice.

So you can automate in whatever way you want here.

**Comment by alexisdondon** [comment]
Thanks for the response.

My expectations was more to have the same admin experience with oidc than ldap/AD on all of this admin commands:

https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-user-svcacct.html#mc-admin-user-svcacct

```
mc admin user svcacct add | Adds a new access keys to an existing MinIO or AD/LDAP user
mc admin user svcacct list | Lists the existing access keys associated to a MinIO or AD/LDAP user.
mc admin user svcacct remove | Removes a access keys from a MinIO or AD/LDAP user.
mc admin user svcacct info | Returns detailed information on a access keys.
mc admin user svcacct edit | Modifies the secret key or inline policy associated with a access keys.
mc admin user svcacct enable | Enables a access keys.
mc admin user svcacct disable | Disables a access keys.
```

But maybe i have to make this issue here https://github.com/minio/mc ?

**Comment by harshavardhana** [comment]
It isn't that straight forward with `mc` since OIDC is interactive @alexisdondon - to automate this requires effort and most don't do this like a day to day business.

**Comment by alexisdondon** [comment]
Hi,

If minio console stay the place where the user create his minio service account could we think about just :
- list, remove, info, edit, enabled, disable.

It seems to me that minio register some kind of concatenation of sub and iss https://github.com/minio/minio/blob/7e76d66184ac219f30314d5cffc4d2ef62529fa7/cmd/iam.go#L713

So something like mc admin user svcacct disable sub=someSub could alow an administrator to do this.

It should be really useful for security to:
- force rotation of service account
- force deletion or disable service account.

**Comment by alexisdondon** [comment]
Maybe this actions are alread doable and miss some documentation as this link say that minio console is the way to do aand mc admin user svcacct do not manage oidc sts accesskey creation but what about the other actions?
https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-user-svcacct.html
