### ISSUE TITLE
On Mac OSX venture 13.x the local DNS  resolver seems to be  ignored

### ISSUE THREAD

**Issue by ar4hc** [minio/minio#16608]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

i use a locals (single node , bare metal) minio server on my mac book with OSX 13.2,
minio get started with `MINIO_SERVER_URL=http://minio.test:9000`
and a resolver in ` /etc/resolver/test`like

```
nameserver 127.0.0.1
domain test
search_order 1
```

pointing to a local dnsmasq, brew installed, with a config like
`address=/.test/192.168.1.2`, the fixed IP of my mac but given by an dhcp in the net.

opening http://minio.test:9000` in the browser gives the login page, but then mini gives an error that it could not resolve 'minio.test' using the  __default__ DNS server (given by dhcp).

Given that OSX dns config is ... interesting at least, this could be a misconfig on my end but..

So the browser usees the resolver and subsequentliy the local  dnsmasq, 
but minios login process  ignores that setting somehow...

## Expected Behavior

minio should honor the macs resolver DNS config...

## Current Behavior

minio uses the upstream DNS server directly, ignorien local config.

## Possible Solution

Duplicate the local dns config into the upstream DNS if possible. (Ugly...)
 
## Steps to Reproduce (for bugs)

1. Use OSX 13.2 with a resolver config for a local .test TLD and dnsmasq giving a catchall IP far all DNS queries
2. start minio with a MINIO_SERVER_URL containing a .test host name
3. open minio browser console,
4. login and
5.  get error about DNS server can't resolve host name

## Context

Can only use localhost as server name for local development.

## Regression

No.

## Your Environment

* Version used (`minio --version`):
```
 minio version RELEASE.2023-02-10T18-48-39Z (commit-id=d0f4cc89a5d0ca45e7ba00fbb7733c2fead3f44e)
Runtime: go1.19.4 darwin/amd64
```

* Server setup and configuration:
  ``` 
   MINIO_SERVER_URL=http://minio.test:9000 MINIO_ROOT_USER=minio MINIO_ROOT_PASSWORD=no minio server /.../data/minio/data/ --console-address ":9001"
  ```

* Operating System and version (`uname -a`):
22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
This is nothing to do with us, you need to report it in Go DNS stack.

**Comment by ar4hc** [comment]
some background in from [go](https://pkg.go.dev/net#hdr-Name_Resolution), with no osx mentioned,  and [SO](https://stackoverflow.com/a/70475373/1073105)

**Comment by ar4hc** [comment]
My test with the mentioned env were inconclusive, i assume DNS caching issues... :/

**Comment by harshavardhana** [comment]
I don't think there is anything we can do here, we are simply limited by Go's behavior at this point for DNS resolution.
