### ISSUE TITLE
why ext4 is faster than xfs?

### ISSUE THREAD

**Issue by Q0heleth** [minio/minio#16602]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version RELEASE.2022-12-07T00-56-37Z
Linux SHPL007176132 5.15.13-1.el7.elrepo.x86_64 #1 SMP Tue Jan 4 17:33:28 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
4 minio servers ,each server has 4 disks.
I use Warp and mc support perf for benchmark. The results show ext4 perform a little better than xfs.
why document recommend xfs? Should I use ext4?

**Comment by harshavardhana** [comment]
@Q0heleth because it doesn't honor O_DIRECT semantics, ext4 is broken and if used in production you can loose data.
