### ISSUE TITLE
Latest MinIO chart (5.0.6) has an invalid template

### ISSUE THREAD

**Issue by atalakey4work** [minio/minio#16604]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
helm install/upgrade work as expected.

## Current Behavior
Error: UPGRADE FAILED: parse error at (minio/templates/poddisruptionbudget.yaml:2): unexpected ")" in if

## Possible Solution
Fix the following template: https://github.com/minio/minio/blob/master/helm/minio/templates/poddisruptionbudget.yaml#L2

## Steps to Reproduce (for bugs)

1. helm repo add minio https://charts.min.io/
2. helm install --namespace minio --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio

**Comment by harshavardhana** [comment]
Please fix @atalakey4work - we do not really use or test it.

**Comment by atalakey4work** [comment]
https://github.com/minio/minio/pull/16605
