### ISSUE TITLE
Incompatible APIs between S3 and Minio

### ISSUE THREAD

**Issue by hao-dong-annalise** [minio/minio#16600]
## Expected Behavior

We are using both Minio and S3 as our backend storage depends on the deployment type.
We noticed that there are some incompatible APIs between S3 and Minio when using AWS SDK for JavaScript v3 https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html

## Current Behavior

For most of the S3 comments of this library for example HeadObjectCommand, GetObjectCommand etc. Although there's a separate parameter Bucket, to get them work with Minio, we have to include bucket name also in the parameter for storage key which is Key. While if we do this for S3, S3 will just treat the additional bucket name in storage key as an additional folder name, so one more layer of folder as the bucket name.
For example:
If bucket is "images", and storage key is "sc/abc.jpg",
This is what we have to do for Minio:
headResponse = await s3Client.send(
  new HeadObjectCommand({
    Bucket:"images",
    Key: "images/sc/abc.jpg",
  }),
);
Otherwise we will get an error NoSuchBucket.
While for S3, we should do:
headResponse = await s3Client.send(
  new HeadObjectCommand({
    Bucket:"images",
    Key: "sc/abc.jpg",
  }),
);
If we use the similar format as for Minio, we will end up getting one more "images" folder under the "images" bucket.
Also the special CopyObjectCommand, which has Bucket and Key for the copy target, and CopySource for the copy source.
If copy one file to the same bucket, for Minio, it needs to be:
await s3.send(
  new CopyObjectCommand({
    Bucket: "images",
    Key: "images/sc/def.jpg",
    CopySource: "images/sc/abc.jpg",
  }),
);
For S3, it needs to be:
await s3.send(
  new CopyObjectCommand({
    Bucket: "images",
    Key: "sc/abc.jpg",
    CopySource: "images/sc/def.jpg",
  }),
);

## Possible Solution

Not sure what is the root cause, but for the same library, we expect Minio and S3 behave in the same way. Since the commands are the same, suppose the issues are because of the way Minio parses those commands sent from the library.

## Steps to Reproduce (for bugs)

1. Create same bucket "images" in S3 and Minio, and same file "sc/abc.jpg"
2. Use a S3Client from the library to send a command like the HeadObjectCommand to access the file
3. For S3, the command should be like below:
headResponse = await s3Client.send(
  new HeadObjectCommand({
    Bucket:"images",
    Key: "sc/abc.jpg",
  }),
);
4. While for Minio, the command has to be like below, otherwise will get a NoSuchBucket error.
headResponse = await s3Client.send(
  new HeadObjectCommand({
    Bucket:"images",
    Key: "images/sc/abc.jpg",
  }),
);

## Context

Because of this inconsistency, we have to write code to distinguish between S3 and Minio, which really against the claim that Minio is fully S3 compatible.

## Regression

No

## Your Environment

* minio/minio:RELEASE.2022-11-17T23-20-09Z or latest version from docker hub
* as the reproduce steps
* docker

**Comment by harshavardhana** [comment]
@hao-dong-annalise you are not doing things right you need to turn off the Bucket DNS feature in the AWS SDK that is enabled by default. 

AWS S3 by default uses a bucket DNS approach - however, MinIO is only path-style by default. So this confusion may arise. 

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#forcepathstyle

Please re-check your code with the relevant changes.

**Comment by hao-dong-annalise** [comment]
Thanks @harshavardhana for the quick response, will check that out.
