### ISSUE TITLE
IAM subsystem fails to initialize on replaced node

### ISSUE THREAD

**Issue by klein-sipgate** [minio/minio#16618]
The setup consists of 4 nodes with 4 disks each and EC:4 is configured, so it should be able to handle the failure of one complete node. The setup is behind an haproxy load balancer.

We replaced a node after failure (node04).

We made sure that
* Each node has the exact same version of the operating system (Debian Bullseye)
* Each node has the exact same version of minio (20230210184839.0.0 installed from the debian package)
* The new node has the same hostname and IP address as the failed one
* All disks were empty when the node rejoined the cluster

The replaced node starts minio and heals the drives, we see data appear on all disks, but we also see these log lines when minio is started.

```
Feb 14 15:30:54 node04 systemd[1]: Starting MinIO...
Feb 14 15:30:54 node04 systemd[1]: Started MinIO.
Feb 14 15:30:54 node04 minio[33497]: Waiting for all MinIO sub-systems to be initialized.. lock acquired
Feb 14 15:30:54 node04 minio[33497]: Automatically configured API requests per node based on available memory on the system: 13
Feb 14 15:30:54 node04 minio[33497]: All MinIO sub-systems initialized successfully in 31.618401ms
Feb 14 15:30:54 node04 minio[33497]: API: SYSTEM()
Feb 14 15:30:54 node04 minio[33497]: Time: 14:30:54 UTC 02/14/2023
Feb 14 15:30:54 node04 minio[33497]: DeploymentID: ce2b0419-88a0-4a8c-8579-08725d0184bd
Feb 14 15:30:54 node04 minio[33497]: Error: Unable to initialize IAM sub-system, some users may not be available: not authorized: insufficient permissions (*fmt.wrapError)
Feb 14 15:30:54 node04 minio[33497]:        3: internal/logger/logger.go:258:logger.LogIf()
Feb 14 15:30:54 node04 minio[33497]:        2: cmd/iam.go:313:cmd.(*IAMSys).Init()
Feb 14 15:30:54 node04 minio[33497]:        1: cmd/server-main.go:653:cmd.serverMain.func3()
Feb 14 15:30:54 node04 minio[33497]: MinIO Object Storage Server
```

Now, approximately 25% of requests fail with errors like

```
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.
```

Meanwhile, when looking at the `mc admin info` output, the cluster looks healthy. 
```
mc admin info dev
●  node01:9000
   Uptime: 2 minutes 
   Version: 2023-02-10T18:48:39Z
   Network: 4/4 OK 
   Drives: 4/4 OK 
   Pool: 1

●  node02:9000
   Uptime: 2 minutes 
   Version: 2023-02-10T18:48:39Z
   Network: 4/4 OK 
   Drives: 4/4 OK 
   Pool: 1

●  node03:9000
   Uptime: 2 minutes 
   Version: 2023-02-10T18:48:39Z
   Network: 4/4 OK 
   Drives: 4/4 OK 
   Pool: 1

●  node04:9000
   Uptime: 2 minutes 
   Version: 2023-02-10T18:48:39Z
   Network: 4/4 OK 
   Drives: 4/4 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 16

62 MiB Used, 3 Buckets, 175 Objects
16 drives online, 0 drives offline
```

The `mc admin heal` command is also happy with the current situation:

```
mc admin heal dev
No active healing is detected for new disks.
```

## Expected Behavior
The node should recover from the failure and Minio should sync data and IAM information.

## Current Behavior
Data seems to be synced, IAM seems to be synced as well (we see `.minio.sys/config/iam` directories and files being synced and identical to the other nodes) but the IAM system fails to initialize and users cannot authenticate to the system.

## Steps to Reproduce (for bugs)

* Configure cluster of 4 nodes
```
MINIO_VOLUMES="https://node0{1...4}:9000/data/disk{1...4}"
MINIO_OPTS="--console-address :9001"
MINIO_ROOT_USER=root
MINIO_ROOT_PASSWORD=veryverysecret
MINIO_SERVER_URL="https://s3-storage:9000"
MINIO_STORAGE_CLASS_STANDARD="EC:4"
MINIO_STORAGE_CLASS_RRS="EC:2"
```
* Login to console with root credentials
* Create access key
* Create mc alias 
```
mc alias set dev https://s3-storage:9000 ....
```
* Make sure you can auth and up/download files
* Replace a node
  * Re-install operating system
  * Create a new xfs filesystem on all disks (mkfs.xfs)
  * Re-install minio
  * Re-deploy minio config
  * Start minio on the replaced node
* Watch log and see disks heal
* Try to upload files and see how roughly every fourth attempt fails
```
dd if=/dev/zero of=test.file bs=1M count=1
i=1; while [ $i -lt 100 ]; do mc cp test.file dev/dev/test.$i; i=$((i+1)); echo; done
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.

/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.78 MiB/s 0s
/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.60 MiB/s 0s
/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.50 MiB/s 0s
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.

/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.35 MiB/s 0s
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.

/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.49 MiB/s 0s
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.

/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.73 MiB/s 0s
/home/klein/test.file:               1.00 MiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.51 MiB/s 0s
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.

/home/klein/test.file:               608.00 KiB / 1.00 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━ 4.70 MiB/s^C
mc: <ERROR> Failed to copy `/home/klein/test.file`. The Access Key Id you provided does not exist in our records.
```

## Your Environment
* Version used (`minio --version`):
```
minio --version
minio version RELEASE.2023-02-10T18-48-39Z (commit-id=d0f4cc89a5d0ca45e7ba00fbb7733c2fead3f44e)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
  * See above
* Operating System and version (`uname -a`):
  * `Linux node04 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> eb 14 15:30:54 node04 minio[33497]: All MinIO sub-systems initialized successfully in 31.618401ms
> Feb 14 15:30:54 node04 minio[33497]: API: SYSTEM()
> Feb 14 15:30:54 node04 minio[33497]: Time: 14:30:54 UTC 02/14/2023
> Feb 14 15:30:54 node04 minio[33497]: DeploymentID: ce2b0419-88a0-4a8c-8579-08725d0184bd
> Feb 14 15:30:54 node04 minio[33497]: Error: Unable to initialize IAM sub-system, some users may not be available: not authorized: insufficient permissions (*fmt.wrapError)
> Feb 14 15:30:54 node04 minio[33497]:        3: internal/logger/logger.go:258:logger.LogIf()
> Feb 14 15:30:54 node04 minio[33497]:        2: cmd/iam.go:313:cmd.(*IAMSys).Init()
> Feb 14 15:30:54 node04 minio[33497]:        1: cmd/server-main.go:653:cmd.serverMain.func3()
> Feb 14 15:30:54 node04 minio[33497]: MinIO Object Storage Server

This has nothing to do with replaced node @klein-sipgate this issue is related to your encryption system. 

You have configured kes and kes is rejecting calls from this MinIO node. You need to first fix that.

**Comment by harshavardhana** [comment]
The error is generated by `kes`

```
~ git grep "not authorized: insufficient permissions"
error.go:       ErrNotAllowed = NewError(http.StatusForbidden, "not authorized: insufficient permissions")
```

**Comment by klein-sipgate** [comment]
Ouch. Thanks. We will look into that.

**Comment by klein-sipgate** [comment]
It would be very helpful to have this information on the documentation about node replacemant: Maybe you can add it?

https://min.io/docs/minio/linux/operations/data-recovery/recover-after-node-failure.html#minio-restore-hardware-failure-node

**Comment by harshavardhana** [comment]
We would love to document things to make it easier, but I unable to understand what was missing?.

The documentation states that the configuration must be same if you replace a node. The issue that you saw is purely a problem of misconfiguration.

**Comment by klein-sipgate** [comment]
It was actually just that the newly setup node had a new client certificate that had not yet been configured in kes. We had not considered/understood that the node needs a kes connection for the IAM subsystem. Is the IAM data also encrypted?

The documentation could state that, if you use kes with authentication, then you either have to re-deploy the old certificate to the new node or grant kes access to the new certificate identity.
