### ISSUE TITLE
Consistent loading...

### ISSUE THREAD

**Issue by zuihou** [minio/minio#16612]
## Expected Behavior
Normal access

## Current Behavior
Access “object browser” ，view files in a bucket and keep loading...
 
## Steps to Reproduce (for bugs)
  
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/8500410/218624714-7d1a132b-d0e6-43bb-929e-6d76efb35641.png">

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-01-25T00-19-54Z (commit-id=50d58e9b2dbbfbe2f3afa2c16ae701f9c1cf03ec)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```

nohup /home/pjjs/minio/minio server --config-dir /home/pjjs/minio/config /home/pjjs/minio_data --address 172.26.3.90:9000 --console-address 172.26.3.90:9090  > /home/pjjs/minio/minio.log 2>&1 &
```
* Operating System and version (`uname -a`):
```
Linux localhost.localdomain 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
If you have millions of objects dumped under a prefix without hierarchy the access may take time. There is nothing special here.
