### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by zuihou** [minio/minio#16611]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Normal access

## Current Behavior
Access console prompt "Access Denied"

## Steps to Reproduce (for bugs)
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/8500410/218623904-008f66df-4847-44d5-ac6b-ce0b790667b9.png">

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-02-10T18-48-39Z (commit-id=d0f4cc89a5d0ca45e7ba00fbb7733c2fead3f44e)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```
nohup /home/pjjs/minio/minio server --config-dir /home/pjjs/minio/config /home/pjjs/minio_data --address 172.26.3.90:9000 --console-address 172.26.3.90:9090  > /home/pjjs/minio/minio.log 2>&1 &
```
* Operating System and version (`uname -a`):
```
Linux localhost.localdomain 5.10.0-4.uelc20.x86_64 #1 SMP Tue Feb 8 15:27:25 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@zuihou looks like your login user doesn't have bucket list permissions.
