### ISSUE TITLE
MinIO stop working normally evei if count of failed drives less than parity

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#16620]
I have 4 servers with 4 drives on each in my minio setup. I set the EC as following:

MINIO_STORAGE_CLASS_STANDARD=EC:6

It means that I can lost up to 6 drives total and my MinIO cluster should continue read/write operations as usual. I've started filling this cluster with data few days ago (rclone from another storage) and after 4 TB was copied I've tried to shutdown one node for testing. So I lost only 4 drives - even not 6. In a few seconds rclone speed decreases from 20 MB/s to 1 KB/s, MinIO web console becomes unavailable and only mc allows me to list files at my minio and copy it to local PC with the same speed as before. Speed of copying files back from PC to MinIO cluster was few bytes per second. Then I powered on this node and after connecting back to cluster write speed returns to 20 MB/s and MinIO web console start working. So the questions is why my cluster degraded when I lost only 4 drives which less than EC:6? Does MinIO really should work at same speed for write operations n case of drive failure or only read operations will works as intended?

I've discussed with some other MinIO cluseter's owner and they tell me about same problems in case of few drives or nodes becomes failed, so not only my setup have this issue.

## Expected Behavior
MinIO should tolerate lost disks less than N when EC:N and continue process read/write operations at fast speed.

## Current Behavior
When MinIO lost 4 disks and parity set to 6 write operations becomes unavailable because its speed less that 1 kbps.

## Steps to Reproduce (for bugs)
1. Setup cluster with 4 nodes with 4 drives on each.
2. Start copy process from somewhere to this cluster.
3. Shutdown one node.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2023-01-12T02-06-16Z (commit-id=7bc95c47a322971aff7d4d4c270dcf28a933e84b)
* Server setup and configuration: 4 nodes with 4 drives on each, EC: 6
* Operating System and version (`uname -a`): Linux minio-cold-1 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You need to upgrade the setup there was bug introduced in some releases that caused a performance regression when disks were down.

```
commit d08e3cc89526a11c8a263d763cfd8e869860ca72
Author: Harshavardhana <harsha@minio.io>
Date:   Thu Jan 19 18:50:54 2023 +0530

    add a way to avoid blocking queueHealTask() depending on caller (#16433)

commit d98116559bcf46d2e2a32ce270873a13fe57501c
Author: Anis Elleuch <vadmeste@users.noreply.github.com>
Date:   Thu Jan 19 09:54:22 2023 +0100

    Use async healing in PutObject call (#16431)
```

These two fixed the bug in RELEASE.2023-01-20T02-05-44Z - you should upgrade to latest RELEASE.2023-02-10T18-48-39Z

**Comment by klauspost** [comment]
Furthermore, it is not expected that MinIO will be seamless when servers are lost. It will take some time for other nodes to realize that a node is unavailable.

**Comment by AlexZIX** [comment]
@harshavardhana thanks, will try to update.
@klauspost I understand that this process isn't seamless. I've tried to disable this node for 1 hour but MinIO still process only the read operations.

Also I see that in such case my prometheus can't collect metrics from this cluster time by time. I mean first 5 minutes it can. then 5 minutes can't then can again and so on in a circle.

**Comment by harshavardhana** [comment]
@Alevsk the fix is in when you upgrade, let us know how it goes.

**Comment by Alevsk** [comment]
I think you mean @AlexZIX 😛

**Comment by harshavardhana** [comment]
> I think you mean @AlexZIX stuck_out_tongue

Sometimes I mean you @Alevsk 🍰

**Comment by AlexZIX** [comment]
@harshavardhana thanks, after update to 2023-02-10T18:48:39Z it works as intended. I've tried to shutdown one node and rclone still copy files at 20 MB/s seamlessly. Then I bring this node online again and after few minutes powered off another node and copy process still works as if nothing happened.  Now I can go home happy :)
