### ISSUE TITLE
Is there a way to get file permission (ACL) ?

### ISSUE THREAD

**Issue by tafel** [minio/minio#16639]
## Expected Behavior

I have a private S3 bucket. All files are private, except a few of them, which are uploaded (`putObject` method) to the bucket with the metadata `x-amz-acl = 'public-read'`

This metadata is used by the S3 provider to manage permissions on the file.

When retrieving file stats with `statObject`, this permission information should be available. Or is there another way to know what are files permissions? 

## Current Behavior

I didn't find a way to get this information. `statObject` returns some data, but not file permissions. The `x-amz-acl` metadata is used by the S3 provider to set permission, but is unfortunately not persisted in file metadata.

## Context

I'm using an auto-resize-image API route, which fetches the high quality image, does some cropping dynamically, and returns the cropped image (highly simplified description). But if this image is a private one, it should throw an access denied error. Since the API has obviously all needed permissions to manage public AND private files, I need to find a way to retrieve permissions information per-file.

## Your Environment

* Version used (`minio --version`): 7.0.32 (npm package version)
* Server setup and configuration: Node JS 18.14.0, NPM 9.3.1
* Operating System and version (`uname -a`): Linux a958aca36f8c 5.15.0-60-generic 66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 GNU/Linux (docker image node:18.14.0-alpine3.17)

**Comment by tafel** [comment]
Sorry, wrong git repo... I posted my question in minio-js instead.

**Comment by harshavardhana** [comment]
There are no ACLs in MinIO - you have PutBucketPolicy() where you can control anonymous access to your assets.
