### ISSUE TITLE
After upgrade, minio console is not working properly

### ISSUE THREAD

**Issue by justinmarygopal** [minio/minio#16633]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am using minio operator 4.4.10 and upgraded minio tenant version to RELEASE.2022-01-08T03-11-54Z. After upgrade, There is no bucket in minio console . Also there is no dashboard, Admin or tools in left menu.
With mc, everything works fine. I get below error from minio: Could you please help?
Error: Unable to initialize IAM sub-system, some users may not be available readObjectStart: expect { or n, but found �, error found in #1 byte of ...|��>��z2�t~�|..., bigger context ...|��>��z2�t~����L�C��G
                                  ��e�}�Io3�jTN�"i3�R,B���*�|... (*fmt.wrapError)
       1: cmd/iam.go:282:cmd.(*IAMSys).Init()

## Current Behavior

I am using minio operator 4.4.10 and upgraded minio tenant version to RELEASE.2022-01-08T03-11-54Z. After upgrade, There is no bucket in minio console . Also there is no dashboard, Admin or tools in left menu.
With mc, everything works fine. I get below error from minio: Could you please help?
Error: Unable to initialize IAM sub-system, some users may not be available readObjectStart: expect { or n, but found �, error found in #1 byte of ...|��>��z2�t~�|..., bigger context ...|��>��z2�t~����L�C��G
                                  ��e�}�Io3�jTN�"i3�R,B���*�|... (*fmt.wrapError)
       1: cmd/iam.go:282:cmd.(*IAMSys).Init()

## Possible Solution
MinIO console needs to show all buckets

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):RELEASE.2022-01-08T03-11-54Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by justinmarygopal** [comment]
I am using minio operator 4.4.10 and upgraded minio tenant version to RELEASE.2022-01-08T03-11-54Z. After upgrade, There is no bucket in minio console . Also there is no dashboard, Admin or tools in left menu.
With mc, everything works fine. I get below error from minio: Could you please help?
Error: Unable to initialize IAM sub-system, some users may not be available readObjectStart: expect { or n, but found �, error found in https://github.com/minio/minio/pull/1 byte of ...|��>��z2�t�|..., bigger context ...|��>��z2�t����L�C��G
��e�}�Io3�jTN�"i3�R,B���*�|... (*fmt.wrapError)
1: cmd/iam.go:282:cmd.(*IAMSys).Init()

**Comment by justinmarygopal** [comment]
Could you please help?

**Comment by harshavardhana** [comment]
Looks like you are facing an old issue you should have used operator v4.5.8 

Your IAM users are now broken and you are using a 1yr old release. To get out of this you would have to delete .minio.sys/config/iam folder on all drives on all nodes and restart the deployment.

**Comment by justinmarygopal** [comment]
I am not able to find the folder .minio.sys/config/iam, should I login inside pod, I am not able to see there

**Comment by harshavardhana** [comment]
It will be inside your drive that is presented to MinIO.

**Comment by justinmarygopal** [comment]
If we remove the folder, will it recreate the users and policies or lost?  Will it have impact

**Comment by harshavardhana** [comment]
> If we remove the folder, will it recreate the users and policies or lost? Will it have impact

yes they are possibly lost, you seem to be using more than an year old release as a community user we never recommend you wait so long as there are many fixes that happen along the way you would have missed.

**Comment by justinmarygopal** [comment]
Thank you, we have done that. Inside config folder, some pods are having config.json, should we remove that as well?

**Comment by justinmarygopal** [comment]
After this change, pods had got restarted and I am seeing multiple restarts are happening in some pods with below error code:     
Last State:     Terminated
      Reason:       Error
      Exit Code:    2
Could you please suggest?

**Comment by harshavardhana** [comment]
> After this change, pods had got restarted and I am seeing multiple restarts are happening in some pods with below error code:
> Last State: Terminated
> Reason: Error
> Exit Code: 2
> Could you please suggest?

You need to cleanly delete them first and then scale back the pods to '0' and then scale back to original replicas

**Comment by justinmarygopal** [comment]
Should I delete all pods and try once?

**Comment by justinmarygopal** [comment]
After deleting the pods, still I am seeing the restart of pods and pod log shows below entries: Could you please help?

goroutine 43151555 [IO wait]:
internal/poll.runtime_pollWait(0x7fa773ee8e90, 0x72)
        runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc007a82500, 0xc00060bc00, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc007a82500, {0xc00060bc00, 0x617, 0x617})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc007a82500, {0xc00060bc00, 0xc0246fb428, 0x6ca90f})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc01c86d7e8, {0xc00060bc00, 0xc01e98a540, 0xc0246fb4d0})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc02348a660, {0xc00060bc00, 0x0, 0x409b6d})
        crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0188be278, {0x5cb6c40, 0xc02348a660})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0188be000, {0x5cbf1a0, 0xc01c86d7e8}, 0x1de016ebb1275f7e)
        crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0188be000, 0x0)
        crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0188be000, {0xc008455000, 0x1000, 0x0})
        crypto/tls/conn.go:1277 +0x16f
net/http.(*connReader).Read(0xc007085500, {0xc008455000, 0x1000, 0x1000})
        net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc0070bc4e0)
        bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc0070bc4e0, 0x4)
        bufio/bufio.go:139 +0x5d
net/http.(*conn).readRequest(0xc01fd40f00, {0x5d0f730, 0xc023e07cc0})
        net/http/server.go:963 +0x1f8
net/http.(*conn).serve(0xc01fd40f00, {0x5d0f7d8, 0xc0035faa50})
        net/http/server.go:1856 +0x865
created by net/http.(*Server).Serve
        net/http/server.go:3034 +0x4e8

**Comment by justinmarygopal** [comment]
Do we have any update?

**Comment by wuyuandu** [comment]
Hello, did deleting the ima folder have any other effects on your minio


> 我们有任何更新吗？

**Comment by justinmarygopal** [comment]
Yes, we have pod restarts with the log below in pod:
goroutine 43151555 [IO wait]:
internal/poll.runtime_pollWait(0x7fa773ee8e90, 0x72)
runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc007a82500, 0xc00060bc00, 0x0)
internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc007a82500, {0xc00060bc00, 0x617, 0x617})
internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc007a82500, {0xc00060bc00, 0xc0246fb428, 0x6ca90f})
net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc01c86d7e8, {0xc00060bc00, 0xc01e98a540, 0xc0246fb4d0})
net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc02348a660, {0xc00060bc00, 0x0, 0x409b6d})
crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0188be278, {0x5cb6c40, 0xc02348a660})
bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0188be000, {0x5cbf1a0, 0xc01c86d7e8}, 0x1de016ebb1275f7e)
crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0188be000, 0x0)
crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0188be000, {0xc008455000, 0x1000, 0x0})
crypto/tls/conn.go:1277 +0x16f
net/http.(*connReader).Read(0xc007085500, {0xc008455000, 0x1000, 0x1000})
net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc0070bc4e0)
bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc0070bc4e0, 0x4)
bufio/bufio.go:139 +0x5d
net/http.(*conn).readRequest(0xc01fd40f00, {0x5d0f730, 0xc023e07cc0})
net/http/server.go:963 +0x1f8
net/http.(*conn).serve(0xc01fd40f00, {0x5d0f7d8, 0xc0035faa50})
net/http/server.go:1856 +0x865
created by net/http.(*Server).Serve
net/http/server.go:3034 +0x4e8
