### ISSUE TITLE
Fd and go routine leak

### ISSUE THREAD

**Issue by tgfree7** [minio/minio#16654]
we have a leak of open files and goroutines. See screenshot.
![7D5070CD-4F61-4EC9-8C56-B2E0FFB34F66](https://user-images.githubusercontent.com/16217209/219935592-36a2f446-d004-484f-a473-43608e1cbfa3.png)
![A148EA2B-A908-43CC-B9B8-C73838BB206C](https://user-images.githubusercontent.com/16217209/219935595-6c55e78c-3723-4a47-b96c-a28d20a8efb5.png)
And there are the trace info and profile info 
[202302191030-profile.zip](https://github.com/minio/minio/files/10776378/202302191030-profile.zip)
[202302191000-trace.log](https://github.com/minio/minio/files/10776380/202302191000-trace.log)

## Your Environment

* Version minio version RELEASE.2021-11-24T23-19-33Z
* mode: 4 hosts ；Erasure sets: 16，1 Drives per
* 
![0E2107F4-C4AE-471D-8FE6-25BD87433997](https://user-images.githubusercontent.com/16217209/219935733-56481836-4636-49cb-8d38-6050a3cace27.png)

**Comment by harshavardhana** [comment]
This has been long fixed @tgfree7 you need to upgrade to latest.

**Comment by tgfree7** [comment]
> This has been long fixed @tgfree7 you need to upgrade to latest.

@hackintoshrao please show me the reason or issue,is a minio bug？

**Comment by harshavardhana** [comment]
> > This has been long fixed @tgfree7 you need to upgrade to latest.
> 

@tgfree7 you can look at our release notes and read through the code. This was a bug in the past and it has been already fixed more than 1yr ago.

If you have a production deployment then look at our subscription plans https://min.io/pricing for SLA based guaranteed replies.
