### ISSUE TITLE
16609-cad68ce tag image can't pull

### ISSUE THREAD

**Issue by ogontaro** [minio/minio#16669]
I happened to find an image with the tag 16609-cad68ce that I could not pull.
The dockerhub link is there, so I don't think it's a typo for the tag or something.
https://hub.docker.com/layers/minio/minio/16609-cad68ce/images/sha256-974ee5600e6679f70ab8dc67779423b55a4c18657bf8c925f3e9b606fe342bc1?context=explore

## Expected Behavior
To be able to pull the image with the command docker pull minio/minio:16609-cad68ce

## Current Behavior
docker pull minio/minio:16609-cad68ce
Error response from daemon: manifest for minio/minio:16609-cad68ce not found: manifest unknown: manifest unknown

## Possible Solution
Rebuild the image named 16609-cad68ce and push it to dockerhub correctly

**Comment by harshavardhana** [comment]
You can't use random tags that we push to docker hub for normal uses. We push these containers for testing purposes internally, they are not meant for public use.

Use regular docker releases.
