### ISSUE TITLE
Unable to restart a canceled decommission

### ISSUE THREAD

**Issue by kuhn-exys** [minio/minio#16667]
## Expected Behavior

As per [documentation](https://blog.min.io/decommissioning/) (see section "Cancel Server Pool Decommissioning"), it should be possible to cancel a decommission and later restart it.

## Current Behavior

Decommissioning with the following (silent) command:

```bash
$ ./mc admin decommission cancel ALIAS TARGET
```
Confirming the cancellation status:

```bash
$ ./mc admin decommission status ALIAS TARGET
Decommission of pool TARGET was canceled, you may start again
```

but if I try to restart the decommission process, it yields an error:

```bash
$ ./mc admin decommission start ALIAS TARGET
mc: <ERROR> Unable to start decommission on the specified pool: decommission is already in progress.
```

I did wait for a couple of hours, in case it took some time for the cancellation to actually take place :man_shrugging: but the output doesn't change.

## Possible Solution

Not really sure... there seems to be an inconsistency between how `mc admin decommission status` and `mc admin decommission start` see the internal `canceled` status :thinking: 

## Steps to Reproduce (for bugs)

I guess:

1. set up a two pool cluster
2. start decommission of one of the pools
3. cancel the decommission
4. try to restart the decommission process

## Context

I've been decommissioning a pool where one of the nodes kept failing. Since the node had some downtime, the decommission process kept slowing down (until reaching about 1.9 KiB/s :sweat_smile: ) and didn't get up to speed once the node was restarted, so reading the documentation I realized that I could try cancelling and then restarting the decommission process to hopefully have it restart with normal speeds...

## Regression

No.

## Your Environment

* Version used (`minio --version`):

```
minio version RELEASE.2023-01-20T02-05-44Z (commit-id=0f591d245d3a1810b0e6aebbf3f32937227f68f8)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

* Server setup and configuration:
  - Two server pools (one new and one old), two nodes per pool, two 920GB disks per node
  - Installed and configured MinIO directly on the system via DEB package
* Operating System and version (`uname -a`):

```
Linux minio02 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vadmeste** [comment]
This is already fixed with this commit, https://github.com/minio/minio/commit/d67a846ec4f9bd14ac8df9adea7c81943fe5f5c5

Please upgrade the server to the latest and try again.
