### ISSUE TITLE
Different buckets sizes in web console and prometheus data

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#16660]
## NOTE
I have few buckets and want to track its sizes. But I see some differences in web console and my grafana. Some buckets sizes differs up to 1 TB. See screenshots. So the questions is why the sizes are differ and which sizes right?

![image](https://user-images.githubusercontent.com/13428863/220056866-065000f2-bf70-4232-aa82-748617df9899.png)
![image](https://user-images.githubusercontent.com/13428863/220056943-6e5979cb-2a5f-4ef8-9742-a7dc3e382f07.png)

## Expected Behavior
Buckets sizes should be the same in prometheus metrics and in web console.

## Current Behavior
The sizes are differ.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2023-02-17T17-52-43Z (commit-id=84bb7d05a998a096b96acd68ea94053d28a87eb3)
* Server setup and configuration: 4 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-cold-1 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@AlexZIX this because how you are dividing the bytes in IEC v/s SI units

Prometheus seems to be incorrectly doing this in SI units, we recommend using IEC and that is what console UI uses.

**Comment by harshavardhana** [comment]
https://www.claudiokuenzler.com/blog/1253/grafana-check-disk-byte-graph-wrong-data

**Comment by AlexZIX** [comment]
Ok, @harshavardhana thanks for the explanation.
