### ISSUE TITLE
MinIO Dashboard not display basic metric,prometheus run with  basic auth and tls

### ISSUE THREAD

**Issue by gtlions** [minio/minio#16661]
## Context
MinIO dashboard can't show monitor info:
```bash
We can't retrieve advanced metrics at this time
MinIO Dashboard will display basic metrics as we couldn't connect to Prometheus successfully.

Please try again in a few minutes. If the problem persists, you can review your configuration and confirm that Prometheus server is up and running.
```

how set minio parameter or variable, when the prometheus server run with basic auth and tls?

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2022-09-22T18-57-27Z (commit-id=20c89ebbb30f44bbd0eba4e462846a89ab3a56fa)
Runtime: go1.18.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
* Server setup and configuration:
minio config:
```bash
MINIO_ROOT_USER="xxxxx"
MINIO_ROOT_PASSWORD="xxxxxxx"
MINIO_VOLUMES="http://minio01.host/data01 http://minio01.host/data02 http://minio01.host/data03 http://minio02.host/data01 http://minio02.host/data02 http://minio02.host/data03 http://minio03.host/data01 http://minio03.host/data02 http://minio03.host/data03"
MINIO_OPTS="--address :9000 --console-address :9001"
export MINIO_PROMETHEUS_AUTH_TYPE="jwt"
export MINIO_PROMETHEUS_JOB_ID=MinIO
MINIO_PROMETHEUS_URL="https://prometheus.host:9090"
```

prometheus enable tls and basic_auth:
- config
```bash
  # MinIO
  - job_name: MinIO
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MzA0NzU4MTIsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJhZG1pbiJ9.tJmQuhdCqWr8bRuqIbb9bv32kqyHSMTW5C-QtHdaDy-UuzlBO4OcHigleIx2hQMsx13OC0NzhRYzbO9Bl8KMtA
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio01.host:9000']
```

- prometheus web.config.file:
```bash
basic_auth_users:
  root: $2y$12$9L9oq/2UfExibrKFkYSJVuLMrKhc7mMII.zAvRJBH/9jCaqZgT4He
tls_server_config:
  cert_file: /home/tls/xxx.crt
  key_file: /home/tls/xxx.key
```
- prometheus run with `--web.config.file`.

* Operating System and version (`uname -a`):
Linux v142 5.10.0-60.58.0.86.oe2203.x86_64 #1 SMP Thu Oct 13 01:14:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
If your Prometheus is authenticated you need to provide username:password in the URL itself

> MINIO_PROMETHEUS_URL="https://prometheus.host:9090"

To 

> MINIO_PROMETHEUS_URL="https://username:password@prometheus.host:9090"

Also please upgrade to latest release before reporting issues.
