### ISSUE TITLE
using python api but https cant verify cert

### ISSUE THREAD

**Issue by ywythu** [minio/minio#16671]
hello ! I have created a minio-tenant on k8s with minio operator followed the instruction on doc, but the service minio and tenant console are https, and I cant connect to minio through python api , giving the following error. Can I close the ssl verify to use http request or other solution would be appreciated!

also I cant close the ssl on web console , as long as I close it and restart, it automatically back to open

![image](https://user-images.githubusercontent.com/52103957/220242940-32d162a3-61b4-40a4-a49b-d6723eae4e24.png)

error from python api
:
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.43.186.136', port=9443): Max retries exceeded with url: /pic?location= (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`

k8s:  kubectl get all -n minio-tenant
NAME                                               READY   STATUS             RESTARTS           AGE
pod/minio-tenant-log-0                             0/1     CrashLoopBackOff   1045 (3m11s ago)   3d18h
pod/minio-tenant-log-search-api-5f8fdbf878-7rx9q   1/1     Running            4 (3d18h ago)      3d18h
pod/minio-tenant-prometheus-0                      2/2     Running            0                  3d16h
pod/minio-tenant-ss-0-0                            1/1     Running            0                  15h
pod/minio-tenant-ss-0-1                            1/1     Running            0                  15h
pod/minio-tenant-ss-0-2                            1/1     Running            0                  15h

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/minio                            ClusterIP   10.43.114.242   <none>        443/TCP    3d18h
service/minio-tenant-console             ClusterIP   10.43.186.136   <none>        9443/TCP   3d18h
service/minio-tenant-hl                  ClusterIP   None            <none>        9000/TCP   3d18h
service/minio-tenant-log-hl-svc          ClusterIP   None            <none>        5432/TCP   3d18h
service/minio-tenant-log-search-api      ClusterIP   10.43.67.209    <none>        8080/TCP   3d18h
service/minio-tenant-prometheus-hl-svc   ClusterIP   None            <none>        9090/TCP   3d16h

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/minio-tenant-log-search-api   1/1     1            1           3d18h

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/minio-tenant-log-search-api-5f8fdbf878   1         1         1       3d18h

NAME                                       READY   AGE
statefulset.apps/minio-tenant-log          0/1     3d18h
statefulset.apps/minio-tenant-prometheus   1/1     3d16h
statefulset.apps/minio-tenant-ss-0         3/3     3d18h

## Expected Behavior
can use http request connect to minio or other method
any advice would be appreciated

## Current Behavior
python api must use https and i dont have cert

**Comment by harshavardhana** [comment]
This is normal either you trust the cert on your local system 

Or introduce a python client that can ignore the cert

```py
from minio import Minio

# Create client with anonymous access.
client = Minio("play.min.io")

# Create client with access and secret key.
client = Minio("s3.amazonaws.com", "ACCESS-KEY", "SECRET-KEY")

# Create client with access key and secret key with specific region.
client = Minio(
    "play.minio.io:9000",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
    region="my-region",
)

# Create client with custom HTTP client using proxy server.
import urllib3
client = Minio(
    "SERVER:PORT",
    access_key="ACCESS_KEY",
    secret_key="SECRET_KEY",
    secure=True,
    http_client=urllib3.ProxyManager(
        "https://PROXYSERVER:PROXYPORT/",
        timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
        cert_reqs="CERT_NONE",
        retries=urllib3.Retry(
            total=5,
            backoff_factor=0.2,
            status_forcelist=[500, 502, 503, 504],
        ),
    ),
)
```
