### ISSUE TITLE
Unable to replicate metadata for a few special objects

### ISSUE THREAD

**Issue by Hintic** [minio/minio#16674]
## NOTE

When configuring replication between local and remote buckets in Minio, there are repeated errors in the POD logs when copying metadata. However, the objects in error are always the same three. Upon inspecting their information, I have not found any differences between them and other objects. 

## Expected Behavior

No error

## Current Behavior

Report an error every five minutes

## Possible Solution

It is suspected that the disk file permissions are wrong, but there are many objects with the same file permissions as them, and these objects do not throw errors

## Steps to Reproduce (for bugs)

unknown

## Context

```shell
API： SYSTEM()
Time : xxxxx
DeploymentID: xxxxxxxx
Error: Unable to replicate metadata for object xxxxxx：Resource requested is unreadable, please reduce your request rate (* errors.errorString)
  3: internal/logger/logger.go: 258: logger.LogIf()
  2: cmd/bucket-replication.go: 1326: cmd.ReplicateObjectInfo.replicateAll()
  1: cmd/bucket-replication.go: 965: cmd.replicateObject.func2()
```

## Regression

Unknown

## Your Environment

Version used (minio --version): 2022-10-29T06:21:33Z

**Comment by harshavardhana** [comment]
@Hintic please upgrade and let us know further. Please share `mc support inspect` output for the affected object.

**Comment by Hintic** [comment]
The “mc admin trace” command log is as follows：
[503 Service Unavailable] s3.CopyObject xxxxx

Please give me some advice, thanks!

**Comment by harshavardhana** [comment]
> The “mc admin trace” command log is as follows： [503 Service Unavailable] s3.CopyObject xxxxx
> 
> Please give me some advice, thanks!

You should first upgrade to latest release, if the problem persists then please share `mc support inspect` output for the object.
