### ISSUE TITLE
Error in MinIO Console  when listing bucket contents (v. 2023-02-17)

### ISSUE THREAD

**Issue by jsabater** [minio/minio#16676]
In the [latest version of MinIO](https://github.com/minio/minio/releases/tag/RELEASE.2023-02-17T17-52-43Z) installed using the [Debian package](https://dl.min.io/server/minio/release/linux-amd64/minio_20230217175243.0.0_amd64.deb) the object browser in the MinIO Console returns an error in when connecting to the websocket. This was working fine in the previous version, installed the same way.

Example URL would be https://minio.domain.com/browser/bucket-name. This are the messages seen in the console of the browser inspector (tried both Chrome and Firefox):

```
InstallTrigger is deprecated and will be removed in the future. (constants.js:50:14)
Failed to get subsystem status for purpose (content-script.js:95:21)
  Object { rejected: true, message: TypeError }
    message: TypeError: port is undefined
​    rejected: true
​    <prototype>: Object { … }
Firefox can’t establish a connection to the server at wss://minio.domain.com/ws/objectManager. ( BrowserHandler.tsx:89:14)
Error in websocket connection. Attempting reconnection... (BrowserHandler.tsx:124:12)
  onerror BrowserHandler.tsx:124
Websocket Disconnected. Attempting Reconnection... (BrowserHandler.tsx:124:12)
```

Steps to reproduce:

1. Log in to MinIO Console (in my case behind an Nginx reverse proxy).
2. Go to the `Object Browser` (default page).
3. Click on any bucket.

Alternative steps:

1. Log in to MinIO Console (in my case behind an Nginx reverse proxy).
2. Go to `Administrator: Buckets`.
3. Click on any bucket.
4. Click on the `Browse bucket` icon on the top-right corner.

I think this is a regression but I have not been able to find the commit that caused it (I am not familiar with the codebase, admittedly).

My environment is as follows:

* LXC with Debian 11 Bullseye on Proxmox (latest version) running a single-server MinIO instance, installed using Debian packages.
* Default options basically everywhere (it's been working fine update after update, being this the first time I encounter an issue).
* Nginx acting as reverse proxy in front of Minio that proxies requests from `https://minio.domain.com` to `https://minio1.internaldomain.com:9090`. Nginx configuration options taken from the [official docs](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html).

```
# minio --version
minio version RELEASE.2023-02-17T17-52-43Z (commit-id=84bb7d05a998a096b96acd68ea94053d28a87eb3)
Runtime: go1.19.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

# uname -a
Linux minio1 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) x86_64 GNU/Linux
```

Thanks in advance.

**Comment by harshavardhana** [comment]
Yes it does because Console UI needs websocket access via your proxy.

If you use nginx you need to make sure to add connection upgrades 

```
            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
```

**Comment by jsabater** [comment]
For future reference, I've modified the Nginx server block with the following information and it is working fine now:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

`proxy_http_version 1.1;` was already there. `Connection` was set to `""`.

May I suggest updating the [official integration guide](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html) to reflect this need?

Again, thanks for your time.

**Comment by harshavardhana** [comment]
This document doesn't talk about Console UI - https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html @jsabater

**Comment by jsabater** [comment]
You're actually right. I had not realised that. I could not find any other document on the official documentation that acts as a guide to set up Nginx as a reverse proxy for the MinIO Console, hence the reason I used that one. But you're right in that it only talks about the server. Good catch! :-)

**Comment by harshavardhana** [comment]
We will update the doc to update the Console UI requirement.

**Comment by ravindk89** [comment]
https://github.com/minio/docs/issues/727 <- a going to work on this, this week.

**Comment by FosterG4** [comment]
for me this is working.

in your .env 
```
MINIO_SERVER_URL: https://minio.domain.com
MINIO_BROWSER_REDIRECT_URL: https://console.minio.domain.com
```

### #For console.mino.example.com 

APACHE

```
#PROXY-START/
<IfModule mod_proxy.c>
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPreserveHost on
    ProxyPass / http://127.0.0.1:9001/
    ProxyPassReverse / http://127.0.0.1:9001/
    </IfModule>
    
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{HTTP:UPGRADE} WebSocket [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade [NC]
    RewriteRule .* ws://127.0.0.1:9001%{REQUEST_URI} [P,L]
</IfModule>
#PROXY-END/
```


#NGINX

```
server {
    listen 80;
    server_name console.mino.example.com;  # Change this to your actual domain

    location / {
        proxy_pass http://127.0.0.1:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws {
        proxy_pass http://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}


```


### For mino.example.com 

#APACHE

```
#PROXY-START/
<IfModule mod_proxy.c>
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPreserveHost on
    ProxyPass / http://127.0.0.1:9000/
    ProxyPassReverse / http://127.0.0.1:9000/
    </IfModule>
#PROXY-END/

```

# NGINX

```
server {
    listen 80;
    server_name mino.example.com;  # Change this to your actual domain

    location / {
        proxy_pass http://127.0.0.1:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

```
