### ISSUE TITLE
How to expand replicas of the minio cluster deployed by helm?

### ISSUE THREAD

**Issue by metadeng** [minio/minio#16696]
When I deployed the minio with distributed mode using helm .
Chart :([https://github.com/minio/minio](https://github.com/minio/minio)) 
Version: RELEASE.2022-08-11T00-30-48Z
For the first time setup minio with 2 replicas and drivesPerNode:1 and pool: 1. everythings run well. with the time fly, i found that the default resource consumption (request/limit) was a bit abnormal, the CPU would exceed the threshold, so I changed the number of replicas of chart value.yaml (2-> 4), but can not actually add minio nodes into cluster.
Error as follow:
`Error: Marking minio-2.minio-svc.ns-infra.svc.cluster.local:9000 offline temporarily; caused by Post "http://minio-2.minio-svc.ns-infra.svc.cluster.local:9000/minio/storage/export/v49/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 192.168.45.195:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
API: SYSTEM()
Error: Marking minio-3.minio-svc.ns-infra.svc.cluster.local:9000 offline temporarily; caused by Post "http://minio-3.minio-svc.ns-infra.svc.cluster.local:9000/minio/storage/export/v49/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 192.168.45.199:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:253:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:151:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:538:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
ERROR Unable to initialize backend: http://minio-0.minio-svc.ns-infra.svc.cluster.local:9000/export drive is already being used in another erasure deployment. (Number of drives specified: 4 but the number of drives found in the 1st drive's format.json: 2)`

**Describe the solution you'd like**
Cluster deployment using helm chart can be expanded rapidly (number of replicas)

**Describe alternatives you've considered**
1. setup an etcd endpoint to federate another new minio cluster (heavy on buckets  synchronization)
2. manually update server endpoint in minio for each minio pod.(9000 port conflicts)

**Additional context**
Kubernetes version: v1.20.8

**Comment by harshavardhana** [comment]
@metadeng please use our operator for pool expansion and advanced features 

https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/expand-minio-tenant.html

**Comment by metadeng** [comment]
> @metadeng please use our operator for pool expansion and advanced features
> 
> https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/expand-minio-tenant.html

ya, known the operator before, and we can not to install another new cluster.
had to reslove the problem by manual, and seems it work, correct me if I am wrong on this way:
1. stop minio 
2. remove the .minio.sys folder(include format.json and pool config...etc)
3. buckets synchronization by manual
4. upgrade the minio with right replicas

**Comment by harshavardhana** [comment]
> > @metadeng please use our operator for pool expansion and advanced features
> > https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/expand-minio-tenant.html
> 
> ya, known the operator before, and we can not to install another new cluster. had to reslove the problem by manual, and seems it work, correct me if I am wrong on this way:
> 
> 1. stop minio
> 2. remove the .minio.sys folder(include format.json and pool config...etc)
> 3. buckets synchronization by manual
> 4. upgrade the minio with right replicas

No follow what I recommended. You can't change replicas in helm deployment. What you are suggesting is unsupported.

**Comment by metadeng** [comment]
copy that, thanks for reply anyway
