### ISSUE TITLE
Error: "Standard storage class parity 4 should be less than or equal to 2" on attempted upgrade.

### ISSUE THREAD

**Issue by ScionOfDesign** [minio/minio#16695]
## NOTE
I tried to upgrade from `RELEASE.2022-12-12T19-27-27Z` to `RELEASE.2023-01-02T09-40-09Z` but the container would throw the error `Standard storage class parity 4 should be less than or equal to 2`. Even attempting to upgrade to `RELEASE.2023-01-12T02-06-16Z` causes the same error.

I did not see any clear signs of a change in the Tenant configuration.

## Expected Behavior
MinIO should start up as normal or describe any configuration changes that need to occur in order to fix the issue.

## Current Behavior
The pod crashes and restarts.

## Possible Solution
Stay on `RELEASE.2022-12-12T19-27-27Z` for now.

## Steps to Reproduce (for bugs)
1. Using MinIO operator and the following official [Tenant helm chart](https://github.com/minio/operator/blob/master/helm/tenant/values.yaml), create a tenant configuration like below:
```yaml
tenant:
    name: minio
    image:
      tag: RELEASE.2022-12-12T19-27-27Z
    pools:
    - name: pool-0
      servers: 2
      volumesPerServer: 2
      size: 255Gi
```
2. Attempt to start the tenant and observe the pods start up successfully.
3. Edit the image tag to be `RELEASE.2023-01-12T02-06-16Z` and upgrade the helm deployment.
4. Observe the pods throw the parity error and fail to start.

## Context
I just tried to upgrade our deployment to the latest MinIO today and notices the issue.

## Regression
Don't think so.

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2022-12-12T19-27-27Z (commit-id=a469e6768df4d5d2cb340749fa58e4721a7dee96)`
* Server setup and configuration: 
  - Kubernetes RKE2 Cluster v1.2.4+rke2r1.
  - [Minio Operator](https://github.com/minio/operator/tree/master/helm/operator) helm chart deployed with `v4.5.8`.
  - [Minio Tenant](https://github.com/minio/operator/tree/master/helm/tenant) helm chart deployed with `RELEASE.2022-12-12T19-27-27Z`.
* Operating System and version (`uname -a`): `Linux ***.***.net 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is because what exists on the 
Operator secret configuration - looks like some historical issue, related to Operator deployment.

Set this MINIO_STORAGE_CLASS_STANDARD=EC:2 in your deployment configuration as part of the tenant configuration.

**Comment by ScionOfDesign** [comment]
This worked, thanks!
