### ISSUE TITLE
Multiple Single Node Single Disk Pools

### ISSUE THREAD

**Issue by CyborgPotato** [minio/minio#16711]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

When configuring a server for pools each with a single node and a single disk only a single pool is created.

NOTE: This is not a recommended setup

## Expected Behavior
When using `MINIO_VOLUMES` like:
```bash
MINIO_VOLUMES="http://minio1.example.com:9000/mnt/disk1/minio http://minio2.example.com:9000/mnt/disk1/minio"
```
```bash
MINIO_VOLUMES="http://minio1.example.com:9000/mnt/disk1/minio http://minio2.different.com:9000/mnt/disk1/minio"
```
the expected admin info is expected to be similar to:
```
●  minio1.EXAMPLE.com:9000
   Uptime: 7 minutes 
   Version: 2023-01-25T00:19:54Z
   Network: 1/1 OK 
   Drives: 1/1 OK 
   Pool: 1

●  minio2.EXAMPLE.com:9000
   Uptime: 7 minutes 
   Version: 2023-01-25T00:19:54Z
   Network: 1/1 OK 
   Drives: 1/1 OK 
   Pool: 2

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1
   2nd, Erasure sets: 1, Drives per erasure set: 1
```

## Current Behavior

Instead they are combined into a single pool, with the following `mc admin info`:
```
●  minio1.EXAMPLE.com:9000
   Uptime: 7 minutes 
   Version: 2023-01-25T00:19:54Z
   Network: 2/2 OK 
   Drives: 1/1 OK 
   Pool: 1

●  minio2.EXAMPLE.com:9000
   Uptime: 7 minutes 
   Version: 2023-01-25T00:19:54Z
   Network: 2/2 OK 
   Drives: 1/1 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 2
```

## Steps to Reproduce (for bugs)

1. Install Minio in two nodes that can talk to eachother (docker, nspawn, separate machines)
2. Use `MINIO_VOLUMES` to point at eachother as above
3. View the "bug"

## Regression

No

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-01-25T00-19-54Z (commit-id=RELEASE.2023-01-25T00-19-54Z)
Runtime: go1.19.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```
NOTE: The most recent released has also been used
* Server setup and configuration: NixOS with systemd nspawn and docker containers
* Operating System and version (`uname -a`): `Linux nixos 5.15.94 #1-NixOS SMP Tue Feb 14 18:18:05 UTC 2023 x86_64 GNU/Linux`

**Comment by CyborgPotato** [comment]
Addendum:
Though the docs say the minimum value is 2, I tried using values of 0 and 1 for:
 `MINIO_STORAGE_CLASS_STANDARD` and `MINIO_STORAGE_CLASS_RRS`, and neither worked

**Comment by kannappanr** [comment]
Single node single disk is a way to get started. Pool expansions with single node single disk is not supported

**Comment by cniackz** [comment]
Thank you @DavidCromp for opening this issue. It was my bad in suggesting this since it is not supported.
The conversation was held via Slack conversation in general channel as a reference of what we achieved: https://minio.slack.com/archives/C3NDUB8UA/p1677174388023229
Maybe in the future can be supported for testing or other purposes.
