### ISSUE TITLE
Can't remove empty bucket

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#16728]
## NOTE
I've tried to remove the bucket. Before that I've removed all objects from this bucket using web console. But anyway web console shows me that bucket isn't empty. Also I've tried to use mc. It shows no objects inside my bucket but can't remove it because it's not empty:

root@minio-cold-1:~# mc rb minio-cold-old/1c-backups
mc: <ERROR> Failed to remove `minio-cold-old/1c-backups`. The bucket you tried to delete is not empty.
root@minio-cold-1:~# mc ls minio-cold-old/1c-backups
root@minio-cold-1:~#

![image](https://user-images.githubusercontent.com/13428863/221854508-7d543c12-6468-4ee3-b572-7dba382d6afc.png)
![image](https://user-images.githubusercontent.com/13428863/221854537-bf3a811f-ae4b-4d80-a79d-419e070b27f2.png)

## Expected Behavior
Bucket should be available for removing and the web console should show the empty bucket.

## Current Behavior
I can't remove the bucket and see that it's not empty at the bucket information page.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2023-02-17T17-52-43Z (commit-id=84bb7d05a998a096b96acd68ea94053d28a87eb3)
* Server setup and configuration: 3 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-cold-1 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@AlexZIX what is the output for `mc ls --versions -r minio-cold-old/1c-backups`

**Comment by AlexZIX** [comment]
@harshavardhana there is no versions for this bucket because versioning wasn't enabled. I've just waited for a few days and then remove this bucket without any problems. Seems minio needs some time for understand that the bucket is empty now.

**Comment by harshavardhana** [comment]
> @harshavardhana there is no versions for this bucket because versioning wasn't enabled. I've just waited for a few days and then remove this bucket without any problems. Seems minio needs some time for understand that the bucket is empty now.

It means those were dangling objects and were cleared automatically by the scanner process. Closing this issue from your confirmation.

**Comment by AlexZIX** [comment]
@harshavardhana this issue applies to all buckets which > 100 GB size or > 1000 objects inside. Seems that web console updates buckets statistics after few hours after changing. For ex. I see that new objects appeared in bucket only in few hours after upload finished.
