### ISSUE TITLE
Min.IO Object Browser Not Working

### ISSUE THREAD

**Issue by BraydenGRomeo** [minio/minio#16721]
When viewing any bucket on min.io it does a constant loading effect and does not seem to load with ssl and without.

## Expected Behavior
I expect it to load everything in the bucket.

## Current Behavior
Constant loading 
![image](https://user-images.githubusercontent.com/25654416/221608671-e6c95ccc-232b-4a86-921d-067759f44446.png)

## Possible Solution
Not Sure.

## Steps to Reproduce (for bugs)

1. Head into your bucket on the latest version
2. Thats all

## Context
I'm not able to view files on my buckets online.

## Your Environment
* Version used (`minio --version`): 
![image](https://user-images.githubusercontent.com/25654416/221609699-3bb310bd-0449-42be-9c99-11eacd5242f3.png)
* Server setup and configuration: VPS - 10 GB Ram - 7 cores - Proxmox QEMU - Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
* Operating System and version (`uname -a`): 
![image](https://user-images.githubusercontent.com/25654416/221610076-f1f36735-962b-4aa6-b520-cf8326bd23e0.png)

**Comment by harshavardhana** [comment]
do you have a load balancer? @BraydenGRomeo

**Comment by BraydenGRomeo** [comment]
I do not. @harshavardhana

**Comment by harshavardhana** [comment]
how many objects do you have in nwy bucket? what kind of a disk is this? also which browser are you using? do you see anything suspicious in your browser inspect logs?

**Comment by BraydenGRomeo** [comment]
I've installed MinIO on here before same server same specs and it worked.

3 Objects

HDD

I've Tried Firefox, Chrome, Edge

Heres a screenshot from my console: 
![image](https://user-images.githubusercontent.com/25654416/221612186-837cc4e6-02f2-48fc-beb8-c6e8022f5bf0.png)

@harshavardhana

**Comment by harshavardhana** [comment]
As you can see websocket connections are getting blocked. We need them to be enabled.

You said you didn't have a load balancer there seems to be load balancer rejecting the requests.

**Comment by lukedupin** [comment]
Its not a load balancer issue, its likely a misconfigured apache/nginx issue. I'm attempting to fix the same problem. The websockets connections aren't upgrading correctly in a proxy pass.
