### ISSUE TITLE
Pod Crash frequently with fatal error

### ISSUE THREAD

**Issue by justinmarygopal** [minio/minio#16731]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Pods are getting restarted and logs are having below text:
Error: Server not initialized, please try again (*errors.errorString)
       2: cmd/peer-rest-client.go:718:cmd.(*peerRESTClient).GetLocalDiskIDs()
       1: cmd/notification.go:1241:cmd.(*NotificationSys).GetLocalDiskIDs.func1()
fatal error: concurrent map writes

goroutine 700548 [running]:
runtime.throw({0x2db4de2, 0xc01c258120})
	runtime/panic.go:1198 +0x71 fp=0xc000a89cd8 sp=0xc000a89ca8 pc=0x435851
runtime.mapassign_faststr(0xc000a89d90, 0xc000a89d78, {0x2d8c4e3, 0x6})
	runtime/map_faststr.go:211 +0x39c fp=0xc000a89d40 sp=0xc000a89cd8 pc=0x412dfc
github.com/minio/minio/cmd.ReportMetrics.func1.1({{{0x2d9529c, 0xa}, {0x2d8842a, 0x4}, {0x2d97ebd, 0xb}, {0x2dbe29b, 0x18}, {0x2d9753e, 0xb}}, ...})
	github.com/minio/minio/cmd/metrics-v2.go:1706 +0x79 fp=0xc000a89e40 sp=0xc000a89d40 pc=0x2450199
github.com/minio/minio/cmd.populateAndPublish({0xc000302e10, 0xa, 0xc01cdd4551}, 0xc000a89fa8)
	github.com/minio/minio/cmd/metrics-v2.go:1738 +0x11e fp=0xc000a89f70 sp=0xc000a89e40 pc=0x245047e
github.com/minio/minio/cmd.ReportMetrics.func1()
	github.com/minio/minio/cmd/metrics-v2.go:1702 +0x98 fp=0xc000a89fe0 sp=0xc000a89f70 pc=0x24500d8
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc000a89fe8 sp=0xc000a89fe0 pc=0x4693c1
created by github.com/minio/minio/cmd.ReportMetrics
	github.com/minio/minio/cmd/metrics-v2.go:1700 +0xf0

## Current Behavior
Pods are getting restarted and logs are having below text:
Error: Server not initialized, please try again (*errors.errorString)
       2: cmd/peer-rest-client.go:718:cmd.(*peerRESTClient).GetLocalDiskIDs()
       1: cmd/notification.go:1241:cmd.(*NotificationSys).GetLocalDiskIDs.func1()
fatal error: concurrent map writes

goroutine 700548 [running]:
runtime.throw({0x2db4de2, 0xc01c258120})
	runtime/panic.go:1198 +0x71 fp=0xc000a89cd8 sp=0xc000a89ca8 pc=0x435851
runtime.mapassign_faststr(0xc000a89d90, 0xc000a89d78, {0x2d8c4e3, 0x6})
	runtime/map_faststr.go:211 +0x39c fp=0xc000a89d40 sp=0xc000a89cd8 pc=0x412dfc
github.com/minio/minio/cmd.ReportMetrics.func1.1({{{0x2d9529c, 0xa}, {0x2d8842a, 0x4}, {0x2d97ebd, 0xb}, {0x2dbe29b, 0x18}, {0x2d9753e, 0xb}}, ...})
	github.com/minio/minio/cmd/metrics-v2.go:1706 +0x79 fp=0xc000a89e40 sp=0xc000a89d40 pc=0x2450199
github.com/minio/minio/cmd.populateAndPublish({0xc000302e10, 0xa, 0xc01cdd4551}, 0xc000a89fa8)
	github.com/minio/minio/cmd/metrics-v2.go:1738 +0x11e fp=0xc000a89f70 sp=0xc000a89e40 pc=0x245047e
github.com/minio/minio/cmd.ReportMetrics.func1()
	github.com/minio/minio/cmd/metrics-v2.go:1702 +0x98 fp=0xc000a89fe0 sp=0xc000a89f70 pc=0x24500d8
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc000a89fe8 sp=0xc000a89fe0 pc=0x4693c1
created by github.com/minio/minio/cmd.ReportMetrics
	github.com/minio/minio/cmd/metrics-v2.go:1700 +0xf0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
MinIO Operator:m4.4.10
MinIO Version: RELEASE.2022-01-08T03-11-54Z

**Comment by klauspost** [comment]
Upgrade. This has been fixed.

**Comment by justinmarygopal** [comment]
Whether I have to do operator upgrade or minio tenant upgrade?

**Comment by klauspost** [comment]
MinIO server. But you should probably upgrade both.

**Comment by justinmarygopal** [comment]
Which version of operator or minio has the fix? also, If we upgrade the minio version , whether this operator version will support?

**Comment by harshavardhana** [comment]
> Which version of operator or minio has the fix? also, If we upgrade the minio version , whether this operator version will support?

Always upgrade to latest release when reporting issues.

**Comment by justinmarygopal** [comment]
We had operator version 4.0.2 which didnt have any pod issues. When we moved to 4.4.10, pods are having restart.  Can I use latest tenant version for this operator version?
