### ISSUE TITLE
Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system

### ISSUE THREAD

**Issue by 13567436138** [minio/minio#16746]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Current Behavior

root@cluster3-159:~# kubectl logs -n minio-operator console-59644b45b8-q99j6 
E: 2023/03/03 04:51:30 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):4.5.8
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by houshym** [comment]
I am trying minio-operator, and I have the same issue. The following is the console pod's log.

E: 2023/11/16 15:56:58 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system  Serving operator at http://:9090
