### ISSUE TITLE
Can not delete file which name ends with '/'

### ISSUE THREAD

**Issue by maslow** [minio/minio#16756]
## NOTE
When created a file with name "/test/abc/",  then delete this object url "/test/abc/".  The server response 204, and the object is still existed.

Tip: The url prefix is "/test/", the object key is "abc/"  with a  "/" is the end.

The object is empty, size is 0.

## Expected Behavior
We want to delete this object.

## Current Behavior
The server response 204, and the object is still existed.

We have update minio to latest version, RELEASE.2023-02-27T18-10-45Z.

## Steps to Reproduce (for bugs)
1. Create an object named `/test/abc/` in any bucket.
2. Delete the object and it still exists.

## Context
We use this empty object with "/" ending to emulate directory in minio.

## Regression
 No

## Your Environment

* Version used (`minio --version`): RELEASE.2023-02-27T18-10-45Z
* Server setup and configuration: both arm64 and amd64 can reproduce it.
* Operating System and version (`uname -a`): Linux minio-0 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by harshavardhana** [comment]
There is no path that starts with `/` on MinIO. However deleting folder perfectly works fine

```
mc mb alias/mybucket/foo/folder/
mc rm alias/mybucket/foo/folder/
```
