### ISSUE TITLE
Error: more disks are expected to heal than parity, returned errors: [<nil> <nil> <nil> <nil> <nil> <nil>] (dataErrs [<nil> <nil> <nil> <nil> <nil> <nil>]) -> testba/5/notepad/thumbaaa/f38d14e3-a213-4b19-adc3-c752e4a219c1.jpg(d875822e-dda9-437f-a89e-d632859ccec9) (*errors.errorString)

### ISSUE THREAD

**Issue by huanglihua0623** [minio/minio#16763]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Version used:minio:RELEASE.2022-06-30T20-58-09Z

**Comment by klauspost** [comment]
Upgrade to latest.
