### ISSUE TITLE
SSL using Custom certificates for Minio UI [Minio running in kubernetes pod] 

### ISSUE THREAD

**Issue by that-rahul-guy** [minio/minio#16762]
Hello folks,
We are using Minio as S3 buckets service [installed minio in kubernetes pod].
We're trying to configure SSL  and have the Minio Operator and Tenant UI served over https.
For this we are trying to create Tenant with our custom certificates which is failing to verify the domain while logging in. and asking for SAN address. 
We are using a Wildcard Certificate of our organization [issued by GoDaddy].

![MinioSANissue](https://user-images.githubusercontent.com/100487809/223040959-286a505e-6c57-4f32-bec4-d12fa71a7eb0.png)

Please guide us to relevant documentations or references.
Thanks

**Comment by harshavardhana** [comment]
@that-rahul-guy as the error indicates you shouldn't be using Common Name's anymore in your TLS certs. It is deprecated 

https://min.io/docs/minio/linux/operations/network-encryption.html this documentation should help you get to correct set of certificates
