### ISSUE TITLE
infinite loading...

### ISSUE THREAD

**Issue by dianshane** [minio/minio#16775]
### Discussed in https://github.com/minio/minio/discussions/16613

<div type='discussions-op-text'>

<sup>Originally posted by **zuihou** February 14, 2023</sup>

I am still having then same issue with "latest" and with the last few images i tried before that.
have tried everything from cache to changing browsers. cleaning up the whole stack etc also ckecked for ram and cpu issues.
Any idea is welcome.

## Expected Behavior
Normal access

## Current Behavior
Access “object browser” ，view files in a bucket and keep loading...
 
## Steps to Reproduce (for bugs)
  
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/8500410/218624714-7d1a132b-d0e6-43bb-929e-6d76efb35641.png">

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-01-25T00-19-54Z (commit-id=50d58e9b2dbbfbe2f3afa2c16ae701f9c1cf03ec)
Runtime: go1.19.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```

nohup /home/pjjs/minio/minio server --config-dir /home/pjjs/minio/config /home/pjjs/minio_data --address 172.26.3.90:9000 --console-address 172.26.3.90:9090  > /home/pjjs/minio/minio.log 2>&1 &
```
* Operating System and version (`uname -a`):
```
Linux localhost.localdomain 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```</div>

**Comment by harshavardhana** [comment]
Original discussion says what is the issue, you have perhaps dumped large amount of files on a single prefix shall take time to load.

**Comment by dianshane** [comment]
i left it running for hours
and it also happens on empty buckets and even on freshly installed clusters
its also weird because it sees the files, the count goes up if you upload ( or wont let you delete bucket etc) but it wont list them

**Comment by harshavardhana** [comment]
> i left it running for hours and it also happens on empty buckets and even on freshly installed clusters its also weird because it sees the files, the count goes up if you upload ( or wont let you delete bucket etc) but it wont list them

Ah that means that you have a proxy that is blocking websocket connections. Console UI needs websockets to work.

**Comment by wushilin** [comment]
It is because it is websocket upgrade that your reverse proxy does not support. if you use nginx, please use nginx streams instead.

**Comment by dianshane** [comment]
Hello and thank you for your reply!

I have since fixed it by allowing socket upgrades on my nginx config.

Thank you for you time though.
