### ISSUE TITLE
Minio Console name collides with Midnight Commader

### ISSUE THREAD

**Issue by oe3gwu** [minio/minio#16778]
**Is your feature request related to a problem? Please describe.**
Having Minio Console installed on my Notebook gives issues with Midnight Commander. Both use mc as command. The Path is different, so I always have to execute Midnight Commander with full Path Name.

**Describe the solution you'd like**
Midnight Commander is way older then Minio Console, so I think it is fair if Minio Console would get an other name to execute.

**Describe alternatives you've considered**
There are no alternatives more me. I use both.

**Additional context**
If you need screenshots, just tell me.

**Comment by vadmeste** [comment]
@oe3gwu MinIO Console is not mc. 'mc' is MinIO Client, https://github.com/minio/mc and your inquery is already answered here, https://github.com/minio/mc/blob/master/CONFLICT.md

**Comment by stranljip** [comment]
Sorry to ask you to reopen this - but this issue is utterly annoying at least for Homebrew users. Midnight Commander has been around far longer than MinIO and it always had the binary name `mc`. Being forced to unlink Midnight Commander to do an upgrade is simply not a good way to do this. Since you are maintaining the Homebrew formula yourself I strongly urge you to extend it in order to avoid the conflict with the formula for Midnight Commander.

**Comment by oe3gwu** [comment]
I agree. It is also not respectful to other open source projects to hijack their names. It would be very easy for you to change the name of the client.

**Comment by stranljip** [comment]
An additional remark - your pointer to https://github.com/minio/mc/blob/master/CONFLICT.md is quite irritating. You state "Package managers are free to choose a different name if they like." Then at least be so honest and forthcoming to do that i your very own Homebrew formula.
You are creating a wonderful software which I am using as stable and maintainable solution but this small issue is bothering me and a lot of other users.

**Comment by harshavardhana** [comment]
The decision has been already made in the past, we are not really going back on it. Yes, there are reasons that you don't like it but that's just the way it is. 

Sorry for the inconvenience and trouble, it causes you.
