### ISSUE TITLE
minio ilm tier paralle uploading

### ISSUE THREAD

**Issue by vklonghml** [minio/minio#16771]
**Is your feature request related to a problem? Please describe.**
recently, i just start to research minio source code, and found that ilm function is just one process per cluster, just one node could upload tier object to tier cluster at the same time.

**Describe the solution you'd like**
is there any plan that minio will supports ilm tier parallel uploading, which means that all nodes in cluster could uploading tier object to tier cluster

**Comment by harshavardhana** [comment]
ILM is not one process it is one process per disk

**Comment by vklonghml** [comment]
> ILM is not one process it is one process per disk

yes，but all the goroutine just in one process in one node, which means that uploading tier object will just in one node of a cluster, so the io in one node will be bottleneck, can not use all node io in cluster

**Comment by harshavardhana** [comment]
> yes，but all the goroutine just in one process in one node, which means that uploading tier object will just in one node of a cluster, so the io in one node will be bottleneck, can not use all node io in cluster

Not really @vklonghml each ILM is triggered by a different node per disk. Please read the code again.

**Comment by vklonghml** [comment]
> ach ILM is triggered by a differe

the ILM is processing below the procedure， but runDataScanner function in "data-scanner.go", only a node process 
 will be executed per cluster, it must get a lock like "globalLeaderLock.GetLock(ctx)".

it will start a goroutine for a disk in "cmd/erasure-server-pool.go NSScanner", but only owns the globalLeaderLock node could execute the function, so only one node process could handle the ILM, and only the node could upload the tier object, the other node in cluster io is wasting.

ILM procedure:
cmd/server-main.go serverMain → cmd/data-scanner.go initDataScanner → cmd/data-scanner.go runDataScanner  → cmd/erasure-server-pool.go NSScanner → cmd/erasure.go nsScanner → cmd/xl-storage.go NSScanner → cmd/data-scanner.go applyActions → cmd/data-scanner.go applyLifecycle → cmd/data-scanner.go applyLifecycleAction

if there is any wrong, please let me know, thks

**Comment by harshavardhana** [comment]
> > ach ILM is triggered by a differe
> 
> the ILM is processing below the procedure， but runDataScanner function in "data-scanner.go", only a node process will be executed per cluster, it must get a lock like "globalLeaderLock.GetLock(ctx)".
> 
> it will start a goroutine for a disk in "cmd/erasure-server-pool.go NSScanner", but only owns the globalLeaderLock node could execute the function, so only one node process could handle the ILM, and only the node could upload the tier object, the other node in cluster io is wasting.
> 
> ILM procedure: cmd/server-main.go serverMain → cmd/data-scanner.go initDataScanner → cmd/data-scanner.go runDataScanner → cmd/erasure-server-pool.go NSScanner → cmd/erasure.go nsScanner → cmd/xl-storage.go NSScanner → cmd/data-scanner.go applyActions → cmd/data-scanner.go applyLifecycle → cmd/data-scanner.go applyLifecycleAction
> 
> if there is any wrong, please let me know, thks

The NSScanner call is a remote call for remote disks the execution of ILM happens at that point on the remote disk.

**Comment by vklonghml** [comment]
> > > ach ILM is triggered by a differe
> > 
> > 
> > the ILM is processing below the procedure， but runDataScanner function in "data-scanner.go", only a node process will be executed per cluster, it must get a lock like "globalLeaderLock.GetLock(ctx)".
> > it will start a goroutine for a disk in "cmd/erasure-server-pool.go NSScanner", but only owns the globalLeaderLock node could execute the function, so only one node process could handle the ILM, and only the node could upload the tier object, the other node in cluster io is wasting.
> > ILM procedure: cmd/server-main.go serverMain → cmd/data-scanner.go initDataScanner → cmd/data-scanner.go runDataScanner → cmd/erasure-server-pool.go NSScanner → cmd/erasure.go nsScanner → cmd/xl-storage.go NSScanner → cmd/data-scanner.go applyActions → cmd/data-scanner.go applyLifecycle → cmd/data-scanner.go applyLifecycleAction
> > if there is any wrong, please let me know, thks
> 
> The NSScanner call is a remote call for remote disks the execution of ILM happens at that point on the remote disk.

ok，got， thks
