### ISSUE TITLE
Graphical way to generate Policies

### ISSUE THREAD

**Issue by oe3gwu** [minio/minio#16777]
The Policies are always created as JSON Scripts. That is nice for advanced workflows. But for simple workflows it would be nice to have a GUI based Policy generator where I dont have to edit JSON Files.

## Expected Behavior
GUI Based Policy Generator

## Current Behavior
JSON Scripting for every worflow

## Possible Solution
I would suggest that there is a question if you want to create a policy per gui clicks on currentl available objects or per json script as advanced way to keep the current compatiblity.

## Context
We use Minio im a HAM Radio context with simple rules. It took me hours to find out how I have to write the scripts, because I dont do this every day.

## Your Environment
TrueNAS Installation with Minio Kubernetes Pod's based on K3s. But no matter if Docker, K8s or even Minikube, this should work the same on every platform.

**Comment by oe3gwu** [comment]
Sorry used a bug template for the feature request. If this is a problem please close it and I create a new one.

**Comment by klauspost** [comment]
This will be a part of the included [console](https://github.com/minio/console).

We do plan to extend to what you are proposing. No official timeline, though.

Closing since not an issue.
