### ISSUE TITLE
ILM rules are not applied to versioned objects

### ISSUE THREAD

**Issue by bzakhar** [minio/minio#16783]
## Expected Behavior
We have replication set up between two cluster, which automatically enables versioning on both sites. We notice that deleted objects are not actually deleted, instead a new version (delete marker) is created. According to #16454 this is expected behavior and if an ILM policy is installed on both sites then ILM will take care of purging obsolete object versions and delete markers. We created ILM policy on both sites with the following rules:
```
{
 "status": "success",
 "config": {
  "Rules": [
   {
    "Expiration": {
     "ExpiredObjectDeleteMarker": true
    },
    "ID": "cfv9ca8etighja1mjjeg",
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 1,
     "NewerNoncurrentVersions": 0
    },
    "Status": "Enabled"
   }
  ]
 }
}
```
We expected deleted objects and their delete markers to be automatically expired in 1 day as specified in the policy.

## Current Behavior
Expiration doesn't happen and deleted objects stay in the bucket indefinitely along with their delete markers:
```
$ date
Wed Mar  8 15:26:05 EST 2023
$ mc ls --versions -r site-b/sfs/lz/pulled/SIM_BIN2/SIM_BIN2.SIM_BIN.20230305002328.5.567f6e39-2df6-4805-8d1a-c3fbd4811ad5.stream.gz
[2023-03-06 19:28:29 EST]     0B null v2 DEL SIM_BIN2.SIM_BIN.20230305002328.5.567f6e39-2df6-4805-8d1a-c3fbd4811ad5.stream.gz
[2023-03-04 19:23:44 EST] 220KiB STANDARD 6a87ed3e-c797-4eb2-93c5-cfd08f245e92 v1 PUT SIM_BIN2.SIM_BIN.20230305002328.5.567f6e39-2df6-4805-8d1a-c3fbd4811ad5.stream.gz
$ mc ls --versions -r site-a/sfs/lz/pulled/SIM_BIN2/SIM_BIN2.SIM_BIN.20230305002328.5.567f6e39-2df6-4805-8d1a-c3fbd4811ad5.stream.gz
[2023-03-06 19:28:29 EST]     0B null v2 DEL SIM_BIN2.SIM_BIN.20230305002328.5.567f6e39-2df6-4805-8d1a-c3fbd4811ad5.stream.gz
[2023-03-04 19:23:44 EST] 220KiB STANDARD 6a87ed3e-c797-4eb2-93c5-cfd08f245e92 v1 PUT SIM_BIN2.SIM_BIN.20230305002328.5.567f6e39-2df6-4805-8d1a-c3fbd4811ad5.stream.gz
```

Original objects are obviously older than 1 days (24 hours) set in the policy, yet they are still present along with their delete markers

## Steps to Reproduce (for bugs)
1. Create two clusters and give them aliases `site-a` and `site-b`, create a bucket in site-a with `mc mb site-a/sfs`, then enable replication between them with `mc admin replicate add site-a site-b`.
2. add ILM policy to both sites with `mc ilm add --noncurrent-expire-days 1 --expire-delete-marker site-a/sfs` and `mc ilm add --noncurrent-expire-days 1 --expire-delete-marker site-b/sfs`
3. copy an object into site-a/sfs and then delete it. verify that this created a new delete marker and the previous version of the object is still there.
4. wait for a day or two and check if the object and its delete marker are removed on either site. In our case they are not removed on source site (site-a) and replica (site-b), but sometimes are not found on site-b (possibly due to a replication failure).

## Context
Since the storage utilization grows uncontrollably despite our efforts to keep it down by deleting obsolete objects from the store, we  run out of space regardless how large are backing devices are.

## Regression
Unsure

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2022-10-02T19-29-29Z (commit-id=f696a221af84fcff27266fd934a427d346547b93)`
* Server setup and configuration: simple 4-node cluster with single mount point on each
* Operating System and version (`uname -a`): `Linux miniohost01 5.15.0-6.80.3.1.el8uek.x86_64 #2 SMP Tue Jan 10 11:28:16 PST 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@bzakhar you need to upgrade your setup there was a bug in the release you are running.

**Comment by harshavardhana** [comment]
The bug was ILM ended up creating null versions, on a versioned bucket, which didn't expire the actual content.

**Comment by lukasz-borek** [comment]
@harshavardhana can you put more light on that? Looks like i was hit by the same bug. 

Null version value is not expected value i assume? 
```
[2023-03-17 14:14:22 CET]     0B STANDARD null v2 DEL 2023-03-02T01:14:32Z.pbm.json
[2023-03-02 02:14:42 CET] 1.9KiB STANDARD 0d77fbf6-b1f1-44fb-adaa-d325ebe71126 v1 PUT 2023-03-02T01:14:32Z.pbm.json
```

**Comment by harshavardhana** [comment]
@lukasz-borek it is already fixed you have to upgrade.

**Comment by lukasz-borek** [comment]
@harshavardhana  So ilm will be able to delete objects with null pointer or we need manual cleanup?
