### ISSUE TITLE
heal result is ok, but the file still corrupted

### ISSUE THREAD

**Issue by yuan123h** [minio/minio#16780]
## NOTE

we found the file corrupted. then heal it for more times.
the result is 
![image](https://user-images.githubusercontent.com/7124327/223735603-90ede6a0-80e8-43ab-b863-c9fa8bd54ac6.png)

but this pic is still wrong .
![image](https://user-images.githubusercontent.com/7124327/223735865-1d80a4f1-2fe3-4f2c-a70a-86d86224317d.png)

## Steps to Reproduce (for bugs)
we expand the storage of one node drive. after that ,we found the problem.
theorily, this could not make any sense.

## Your Environment

* Version used (`minio --version`):RELEASE.2020-09-26T03-44-56Z
* Server setup and configuration:  four nodes. one drive per node.
* Operating System and version (`uname -a`):

**Comment by vadmeste** [comment]
@yuan123h can you paste ?

```
mc cat <alias>/<bucket>/<object> | md5sum
```
and
```
mc stat <alias>/<bucket>/<object>
````
?

**Comment by yuan123h** [comment]
![image](https://user-images.githubusercontent.com/7124327/223739167-449b0a10-f100-4dd8-8904-deecebf5711f.png)
thanks

**Comment by vadmeste** [comment]
@yuan123h thanks, let's upgrade to the latest version of MinIO and check again.

**Comment by yuan123h** [comment]
@vadmeste we have tried copying the files of this object directly to a high verion MinIO。 when we get file from the new MinIO cluster ,this pic is still corrupted.

**Comment by yuan123h** [comment]
![image](https://user-images.githubusercontent.com/7124327/223744681-9836c094-a3b0-4387-984d-77b1c49990fa.png)
I think the data file is normal. 
maybe reading data from disk make a mistake

**Comment by yuan123h** [comment]
above thought is wrong . for
![image](https://user-images.githubusercontent.com/7124327/223747303-020cde1a-e51d-4463-b318-1b4b6864507d.png)
obviously， the file data of the pic  has changed.
can we fix it ?

**Comment by harshavardhana** [comment]
You haven't really explained your setup, how many nodes, how many disks ?

**Comment by vadmeste** [comment]
@yuan123h most likley upgrading MinIO will fix the issue

**Comment by yuan123h** [comment]
> You haven't really explained your setup, how many nodes, how many disks ?

four nodes. and one disk per node.

**Comment by yuan123h** [comment]
> @yuan123h most likley upgrading MinIO will fix the issue

fine, i will try it. then report the result.

**Comment by harshavardhana** [comment]
> > You haven't really explained your setup, how many nodes, how many disks ?
> 
> four nodes. and one disk per node.

You should upgrade your setup first, 2020 release is 3 yrs ago

**Comment by yuan123h** [comment]
very thanks for every friends.  After we upgrade the version, the file is ok. We can get the right pic files again.!
