### ISSUE TITLE
XL: After complete-multipart-upload we might be retaining unneeded parts

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1680]
Let's say 10 parts were uploaded, but complete-multipart-upload specifies just 8 parts to be part of the completed object, then we retain the extra two parts after we rename the uploadID from `.minio` to the actual object location.

Fix not urgent as this would be a rare case.

**Comment by harshavardhana** [comment]
> Let's say 10 parts were uploaded, but complete-multipart-upload specifies just 8 parts to be part of the completed object, then we retain the extra two parts after we rename the uploadID from .minio to the actual object location.
> 
> Fix not urgent as this would be a rare case.

We can purge the other parts safely if there are no more uploads pending on that key anymore. We should also see how S3 behaves in this case.

**Comment by harshavardhana** [comment]
Fixed by #1786
