### ISSUE TITLE
SetBucketLifecycle not in effect

### ISSUE THREAD

**Issue by hukang6677** [minio/minio#16804]
Lifecycle was set at 9:40 yesterday morning. And objects not deleted
![image](https://user-images.githubusercontent.com/102129512/224883266-93625c76-0d52-4395-9b01-436adbc0a659.png)
![image](https://user-images.githubusercontent.com/102129512/224883290-41ba2280-b31b-4253-9677-a02cf55cda82.png)
![image](https://user-images.githubusercontent.com/102129512/224883385-cc97a998-20c0-48a2-b9f8-507d09361050.png)
![image](https://user-images.githubusercontent.com/102129512/224883432-742d7e83-ad71-4ec8-a71e-0b5241af0fc9.png)

**Comment by harshavardhana** [comment]
They take more than 48 hours.

**Comment by hukang6677** [comment]
@harshavardhana 
but I set "after 1"
How to explain "after 1" ?
When is the clean operation performed ?

**Comment by harshavardhana** [comment]
1 day + 00:00 UTC window 

- It is the number of days from when the version of the object becomes noncurrent (that is, when the object is overwritten or deleted) that MinIO will perform the action on the specified object or objects.

- MinIO calculates the time by adding the number of days specified in the rule to the time when the new successor version of the object is created and rounding the resulting time to the next day's midnight UTC. For example, in your bucket, suppose that you have a current version of an object that was created on at 1/1/2014 10:30 AM UTC. If the new version of the object that replaces the current version is created at 1/15/2014 10:30 AM UTC, and you specify 3 days in a transition rule, the transition date of the object is calculated as 1/19/2014 00:00 UTC.

**Comment by hukang6677** [comment]
@harshavardhana 
thank you
