### ISSUE TITLE
How we can use single port for web and api 

### ISSUE THREAD

**Issue by gudipudipradeep** [minio/minio#16819]
How we can use single port for web and api inside the minio, Instead of 9000, 90001 for app and web.

**Comment by harshavardhana** [comment]
You cannot @gudipudipradeep

**Comment by gudipudipradeep** [comment]
When we use this endpoint https://xxx.com/minio/health/live in browser it is redirecting 9001 port. can get the response from 9000 port.
because we need some health check port on 9000.
@harshavardhana 

can you help on this

**Comment by harshavardhana** [comment]
Yeah for health checks use `curl https://xxx.com/minio/health/live` - no need to visit this link via browser.

**Comment by gudipudipradeep** [comment]
@harshavardhana we configured cdn service before mino. cdn service vendor saying it should work via browser as well. Am not sure how was relation was build from cdn side.

curl is working as expected and informed to the vendor, even he want it from browser as well.
