### ISSUE TITLE
Infinite Policies, Access Keys and Identity loading

### ISSUE THREAD

**Issue by milkywayfarer** [minio/minio#16810]
## Expected Behavior

Using `MinIO Console`, I should be able to edit `Access Keys`, `Policies` and `Identity` categories.

## Current Behavior

- `Identity/Users` shows a long loader, then an `Error 504.`
- `Identity/Groups` behaviour is the same
- `Policies` behaviour is the same
- `Access Keys` shows a long loader, then assumes that no access keys are present. Upon creation of a key, clicking `Create` does nothing

## Possible Solution

Remove any MinIO config files and allow it to recreate them.

## Steps to Reproduce (for bugs)

1. Start a new MinIO server container using all the `Quick Start` guide parameters.
2. Login as a root user with default credentials, create a policy, a group and a bucket.
3. Logged as the created user, upload some files to the bucket.
4. Remove the MinIO server container, not removing the Docker volume that was created previously (with already uploaded files).
5. Start a new MinIO server container, changing the `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` envs and using previously created volume for `/data`.
6. Login as a root user, not being able to change anything.

## Context

I was trying to rebuild a Docker image with different root user credentials, keeping the volume with my files. Seems like the volume still has an old config, that I want to rebuild anew. Only thing that I can do now is to remove everything completely and spend another night uploading everything again.

## Regression

No

## Your Environment

* Version used (`minio --version`): 
```
minio version RELEASE.2023-03-13T19-46-17Z (commit-id=c7f7e67a100ce35af559e3f49a2ed0b67deaa919)
Runtime: go1.19.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
Home server with an FX-4300 CPU
Docker with Portainer, everything up to date
* Operating System and version (`uname -a`):
`Linux nas 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is actually a bug, we shouldn't be relying on changing root credentials. Looks like some  credential logic code is relying on the admin secret key.

**Comment by milkywayfarer** [comment]
Forgot to provide a log output:
```
API: SYSTEM()
Time: 18:38:12 UTC 03/14/2023
DeploymentID: 9e92bc03-7fe6-42cf-be2b-09191416ca4b
Error: Failure in periodic refresh for IAM (took 0.01s): signature is invalid (*errors.errorString)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/iam.go:466:cmd.(*IAMSys).watch()
```

**Comment by harshavardhana** [comment]
yeah, I reproduced it @milkywayfarer this is actually wrong and unexpected. Possibly a regression.

**Comment by harshavardhana** [comment]
This is because of service accounts supporting expiration #16430 - regression from this PR.
