### ISSUE TITLE
Azure AD OIDC login not working

### ISSUE THREAD

**Issue by rfranks-securenet** [minio/minio#16811]
I have configured Minio with OIDC pointing to an Azure AD application. I have configured the Azure end to send the policy statically set to consoleAdmin at the moment (for testing).

When trying to log in I go through the OIDC flow (authenticating against Azure), and then get thrown back to the login page.

## Expected Behavior
Getting a session in the console after completing the OIDC login flow

## Current Behavior
Get thrown back to the login page

From using wireshark to sniff the HTTP requests, I can see that it POSTs correctly to `/api/v1/login/oauth2/auth`, but then fails when trying to GET from `/api/v1/session` with a `403 Forbidden`:

```
HTTP/1.1 403 Forbidden
Content-Type: application/json
Server: MinIO Console
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Wed, 15 Mar 2023 08:48:53 GMT
Content-Length: 76
Connection: close

{"code":403,"detailedMessage":"Access Denied.","message":"invalid session"}
```

## Steps to Reproduce (for bugs)

1. Install MinIO
2. Configure Azure AD application for OIDC with a claim `policy` which returns a static 'consoleAdmin'
3. Configure MinIO with OIDC as per below /etc/defaults/minio
5. Try to log in using OIDC

```bash
# MINIO_ROOT_USER and MINIO_ROOT_PASSWORD sets the root account for the MinIO server.
# This user has unrestricted permissions to perform S3 and administrative API operations on any resource in the deployment.
# Omit to use the default values 'minioadmin:minioadmin'.
# MinIO recommends setting non-default values as a best practice, regardless of environment

MINIO_ROOT_USER="minioadmin"
MINIO_ROOT_PASSWORD="miniosecretpassword"

# MINIO_VOLUMES sets the storage volume or path to use for the MinIO server.

MINIO_VOLUMES="/data"

MINIO_OPTS="--address :9000 --console-address :9001"

MINIO_IDENTITY_OPENID_CONFIG_URL="https://login.microsoftonline.com/<azure tenant>/v2.0/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID="<client id>"
MINIO_IDENTITY_OPENID_CLIENT_SECRET="<client secret>"
MINIO_IDENTITY_OPENID_SCOPES="profile openid email"
MINIO_IDENTITY_OPENID_REDIRECT_URI="http://localhost:9001/oauth_callback"
MINIO_IDENTITY_OPENID_COMMENT="AzureAD"

# MINIO_SERVER_URL sets the hostname of the local machine for use with the MinIO Server
# MinIO assumes your network control plane can correctly resolve this hostname to the local machine

# Uncomment the following line and replace the value with the correct hostname for the local machine.

#MINIO_SERVER_URL="http://localhost:9000"
#MINIO_BROWSER_REDIRECT_URL="http://localhost:9001"
```

## Context
I am trying to accomplish login via OIDC into Minio.

### Version used (`minio --version`):

minio version RELEASE.2023-03-13T19-46-17Z (commit-id=c7f7e67a100ce35af559e3f49a2ed0b67deaa919)
Runtime: go1.19.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

### Server setup and configuration:
Set up as per [the guide](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#minio-snsd)

### Operating System and version (`uname -a`):
Debian 11  
Linux minio-test-bed0bd 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Comment by biel-justin** [comment]
Any update?

**Comment by jiuker** [comment]
What's your policy like ? @rfranks-securenet  I didn't replica it.

**Comment by jiuker** [comment]
Use the latest minio to see if the problem have been resloved.
