### ISSUE TITLE
[k8s]: Free inode check breaks functionality on cephfs volumes 

### ISSUE THREAD

**Issue by 404notfoundhard** [minio/minio#16815]
## Expected Behavior
if the file system does not use inodes or inodes are expanded dynamically, then disable inodes check

## Current Behavior
Upload failed on ceph fs pv
```sh
bash-4.4$ df -i
Filesystem                 Inodes   IUsed    IFree IUse% Mounted on
ceph-fuse                      52      52        0  100% /export
```
## Possible Solution
https://github.com/minio/minio/pull/4747  
it seems that it has been forgotten

## Steps to Reproduce (for bugs)
1. Deploy on k8s minio wtih tag `RELEASE.2023-03-13T19-46-17Z ` and storageClass cephfs
2. Trying upload files

## Your Environment
* Version used (`minio --version`):
```sh
minio version RELEASE.2023-03-13T19-46-17Z (commit-id=c7f7e67a100ce35af559e3f49a2ed0b67deaa919)
Runtime: go1.19.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Operating System and version (`uname -a`):
k8s v1.22 with cephfs

**Comment by harshavardhana** [comment]
You shouldn't be using MinIO on top of CephFS volumes, use it on a disk filesystem.
