### ISSUE TITLE
Unable to delete empty folder

### ISSUE THREAD

**Issue by cruvie** [minio/minio#16836]
Unable to delete empty folder, and cannot create new folder or file in the empty folder
## Expected Behavior

delete the empty folder 

## Current Behavior

cannot delete empty folder 

## Possible Solution
the method that minio checks a exist folder should improve

## Steps to Reproduce (for bugs)

https://user-images.githubusercontent.com/55651847/225887277-2f27af0b-6de4-4b9a-b541-4b5a39f2b536.mp4

## Context

cannot delete the empty folder so cannot create a new folder with the same name, because the folder created in this empty folder will disappear after click create and the success dialog

## Your Environment

* Version used docker. RELEASE.2023-03-09T23-16-13Z
* Operating System and version Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)

**Comment by ravindk89** [comment]
Try to run `mc admin trace ALIAS/in-so-net` when you attempt this and look at the output. What is happening on the MinIO Server when you attempt this delete operation?

If you use the Browser dev console, do any errors or warnings get returned when running this operation:

Is there versioning enabled on this bucket? Are there objects inside of that prefix?

You can do `mc ls --recursive --versions ALIAS/in-so-net` to confirm.

**Comment by cruvie** [comment]
> 
`mc admin trace ALIAS/in-so-net` not works in docker console , and there no more output in my console with the delete action after I using `docker compose -f docker-compose.yml up ` rerun minio , is there any way to see minio server's output in docker?

**Comment by harshavardhana** [comment]
> > 
> 
> `mc admin trace ALIAS/in-so-net` not works in docker console , and there no more output in my console with the delete action after I using `docker compose -f docker-compose.yml up ` rerun minio , is there any way to see minio server's output in docker?

Don't just copy paste, configure `mc` first and then follow up on what was asked.

**Comment by cruvie** [comment]
> Try to run `mc admin trace ALIAS/in-so-net` when you attempt this and look at the output. What is happening on the MinIO Server when you attempt this delete operation?
> 
> If you use the Browser dev console, do any errors or warnings get returned when running this operation:
> 
> Is there versioning enabled on this bucket? Are there objects inside of that prefix?
> 
> You can do `mc ls --recursive --versions ALIAS/in-so-net` to confirm.

here are the results, it seems no errors 

https://user-images.githubusercontent.com/55651847/226160541-0fc149c6-406c-4437-b15a-6461d5efeae8.mp4

<img width="878" alt="image" src="https://user-images.githubusercontent.com/55651847/226160540-c32c58c5-2d8a-45f2-9e31-a4cc540f1ca2.png">

**Comment by harshavardhana** [comment]
You can do `mc rm --recursive --purge myminio/in-so-net/go_social_update/202212.../167....jpg`  - replace this with real values.

**Comment by cruvie** [comment]
> 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/55651847/226171289-5f7120c7-be32-4968-9180-1f84eb736426.png">
I think something wrong with the empty folder created by my program while testing.

**Comment by ravindk89** [comment]
Generally speaking, don't create explicit folders - just include your prefix/folder structure as part of the object name and the magic happens from there.

If we could understand what the program is doing when it creates the explicit prefix, that might help.

**Comment by cruvie** [comment]
> Generally speaking, don't create explicit folders - just include your prefix/folder structure as part of the object name and the magic happens from there.
> 
> If we could understand what the program is doing when it creates the explicit prefix, that might help.

yes, I know it's no need to create a folder in person . As you can see the suffix .jpg which should be a file not a folder ,due to some net error or something it turns to be a folder 
I supposed that may minio delete the file uses the way of delete a folder(if the two delete actions different), and then cause the unexpected

**Comment by gkdgo** [comment]
> Generally speaking, don't create explicit folders - just include your prefix/folder structure as part of the object name and the magic happens from there.
> 
> If we could understand what the program is doing when it creates the explicit prefix, that might help.

yes, I know it's no need to create a folder in person . As you can see the suffix .jpg which should be a file not a folder ,due to some net error or something it turns to be a folder 
I supposed that may minio delete the file uses the way of delete a folder(if the two delete actions different), and then cause the unexpected

**Comment by harshavardhana** [comment]
> I supposed that may minio delete the file uses the way of delete a folder(if the two delete actions different), and then cause the unexpected

Do you have a way to reproduce this?

**Comment by cruvie** [comment]
> > I supposed that may minio delete the file uses the way of delete a folder(if the two delete actions different), and then cause the unexpected
> 
> Do you have a way to reproduce this?

sorry I can't make it happen again, but I pack the problem runable app, just run `docker compose -f docker-compose.yml up` and visit `http://localhost:9011/browser/in-so-net`, you are unable to  delete the file here. hope the pack can help due with this.
[docker-minIO.zip](https://github.com/minio/minio/files/11108840/docker-minIO.zip)

**Comment by jiuker** [comment]
@gkdgo Do you use macOS or Docker on macOS to deply minio ? And you use Finder to view them?

**Comment by cruvie** [comment]
> @gkdgo Do you use macOS or Docker on macOS to deply minio ?

Docker on macOS

I use mac M2 to develop and test and then copy the `minio` folder to Linux(Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)) and restart minio deplied on Linux(by docker), the problem occured both on my mac and linux.

**Comment by cruvie** [comment]
> @gkdgo Do you use macOS or Docker on macOS to deply minio ?
Docker on macOS

I use mac M2 to develop and test and then copy the `minio` folder to Linux(Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)) and restart minio deplied on Linux(by docker), the problem occured both on my mac and linux.

**Comment by harshavardhana** [comment]
Can you confirm if you have .DS_Store file among those folders copied ?

**Comment by jiuker** [comment]
> > @gkdgo Do you use macOS or Docker on macOS to deply minio ?
> > Docker on macOS
> 
> I use mac M2 to develop and test and then copy the `minio` folder to Linux(Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)) and restart minio deplied on Linux(by docker), the problem occured both on my mac and linux.

Because there is a hide file named `.DS_Store` on the dir. You delete the dir failed for the file. This file will create at you use `Finder` to view the dir. @gkdgo

**Comment by cruvie** [comment]
@jiuker @harshavardhana 
I tried to delete the `.DS_Store` and then deploy it (the file I upload above `docker-minIO.zip`) on linux(Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)) , still cannot delete those folders.

<img width="785" alt="iShot_2023-06-05_09 17 10" src="https://github.com/minio/minio/assets/55651847/74d86547-dd8c-436c-afc1-a88f94175527">

<img width="1188" alt="iShot_2023-06-05_09 12 46" src="https://github.com/minio/minio/assets/55651847/e688304e-17a7-4ba2-bbed-de165c15ed57">

**Comment by jiuker** [comment]
> @jiuker @harshavardhana I tried to delete the `.DS_Store` and then deploy it (the file I upload above `docker-minIO.zip`) on linux(Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)) , still cannot delete those folders.
> 
> <img alt="iShot_2023-06-05_09 17 10" width="785" src="https://user-images.githubusercontent.com/55651847/243230945-74d86547-dd8c-436c-afc1-a88f94175527.png"> <img alt="iShot_2023-06-05_09 12 46" width="1188" src="https://user-images.githubusercontent.com/55651847/243230883-e688304e-17a7-4ba2-bbed-de165c15ed57.png">

@gkdgo That's not the deletion I'm talking about, I'm talking about the deletion of the new file, and so far, the performance is really like that, because this deletion has only one chance to delete. That deletion is because of the presence of that file. You can try adding a file with the same name and delete it again, but of course this hidden file must also be deleted.

**Comment by cruvie** [comment]
@jiuker I don't understand , do you mean once I trigger a delete action, minio will delete the file/folder (maybe its index), and lost the control of the ‘deleted’ file/folder whether the file/folder still exists or not.
Anyway, it's an unexpected behavior , and I don't think `.DS_Store` file has any effect on Linux.
> You can try adding a file with the same name and delete it again

it works with file not folder

**Comment by jiuker** [comment]
@gkdgo This file is generated by macos' Finder. Not for linux

**Comment by cruvie** [comment]
> @gkdgo This file is generated by macos' Finder. Not for linux

I see, so it won't make any effect on Linux right?

**Comment by jiuker** [comment]
@gkdgo There are two issues here, one because of the hidden file deletion directory failure issue, and the other is that deleting an empty directory containing hidden files on the page does not trigger a real delete call. We should only deal with the first issue.

**Comment by jiuker** [comment]
> I see, so it won't make any effect on Linux right?

Yes
