### ISSUE TITLE
Nothing happened when trying to run minio on Windows 10.

### ISSUE THREAD

**Issue by PaienNate** [minio/minio#16845]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Run minio correctly, or just get some log to let me know why.
## Current Behavior
When trying to run minio on windows 10 X64, it display nothing with command.
(I have tried with Admin privilege,Use Administrator account.)
(I have D:\ too)
![image](https://user-images.githubusercontent.com/68044286/226082301-dee4cf0d-0c94-4f9f-9746-fe807a0f98d1.png)

## Possible Solution
I don't know, as I can't find any log so I am very confused.

## Steps to Reproduce (for bugs)
1. Just try to run "minio.exe server D:\"

## Your Environment

![image](https://user-images.githubusercontent.com/68044286/226082385-7ad52add-47e2-4b6c-9528-51c7a87c9529.png)
I guess the version is:
[minio.RELEASE.2023-02-27T18-10-45Z](https://dl.minio.org.cn/server/minio/release/windows-amd64/minio.RELEASE.2023-02-27T18-10-45Z)
Windows 10 X64, with i7-9750h + 32G ddr4 + 1660ti laptop. Administrator account.

**Comment by kannappanr** [comment]
can you run it in command prompt instead of power shell

**Comment by PaienNate** [comment]
> can you run it in command prompt instead of power shell

Sure, and yes there nothing happened too:(

![image](https://user-images.githubusercontent.com/68044286/226087419-9577c622-86b0-40a7-9020-d9e22330fc1b.png)

**Comment by harshavardhana** [comment]
You don't have `minio.exe` @PaienNate - did you download https://dl.minio.io/server/minio/release/windows-amd64/minio.exe ?

**Comment by PaienNate** [comment]
> Refere

![image](https://user-images.githubusercontent.com/68044286/226088121-dd8f3feb-c841-4ebf-87fb-c8aaa55fa937.png)
Actually I have it here, But seems the file I download from "dl.minio.org.cn" has something wrong. I download your file with your link, and works well, thanks!

**Comment by harshavardhana** [comment]
> Actually I have it here, But seems the file I download from "dl.minio.org.cn" has something wrong. I download your file with your link, and works well, thanks!

dl.minio.org.cn is a fake site, download from official repositories following our documentation @PaienNate
