### ISSUE TITLE
request to the prometheus metrics with 403

### ISSUE THREAD

**Issue by metadeng** [minio/minio#16850]
**Is your feature request related to a problem? Please describe.**
when test on version RELEASE.2022-02-16T00-35-27Z to use minio gateway on Azure, everything works fine, except the monitor with metrics, as it response the 403 error.

**Describe the solution you'd like**
1. respone the right metrics data from /minio/v2/metrics/cluster interfce(with bearer_token) on version RELEASE.2022-04-01T03-41-39Z

**Comment by harshavardhana** [comment]
@metadeng we do not support gateway anymore.
