### ISSUE TITLE
replicate update --limit-upload doesn't seem to have an effect

### ISSUE THREAD

**Issue by lestd** [minio/minio#16858]
Submitting as an issue, after attempts at discussion and also on slack. I am able to duplicate the issue after rebuild of everything. I don't have another environment with a different WAN uplink, but cannot seem to have minIO limit the bandwidth, I have to force it with router QoS. As a result, I end up disabling/re-enabling the replication rule (to stop incessant retries), and minIO ends up with many a rising replication count that never clears up.

### Discussed in https://github.com/minio/minio/discussions/16791

<div type='discussions-op-text'>

<sup>Originally posted by **lestd** March 10, 2023</sup>
Hello,

I'm attempting to replicate a bucket over a slow wan link.
I see that GUI options the lowest choice is in MiB, but mc command-line allows for KiB or K, even Bytes.

I am getting no complaints or errors on the following command:
mc replicate update minio/backups --id "(ID)" --limit-upload 300Ki

But the upload bandwidth does not change.

I am able to limit with QoS on my router to prevent traffic from saturating the full pipe. But minio is still saturating the given slice of bandwidth, and I'm getting lots of failed replication (size) and (count). I also regularly have to disable and re-enable the replication rule to slow down the retries.
Lots of this in the log:
Error: Unable to replicate for object backups/data/fa/fa...): A timeout exceeded while waiting to proceed with the request, please reduce your request rate (*errors.errorString)

Does --limit-upload actually work below MiB level? Any suggestions?
</div>

**Comment by harshavardhana** [comment]
`mc` --limit-upload is meant for `client` bandwidth control it has nothing to do with server side replication bandwidth settings.

you need to use `--bandwidth` @lestd

**Comment by lestd** [comment]
Thank you @harshavardhana for the reply.

Attempt to use the --bandwidth flag appears to validate my original question:
`# mc replicate update minio/backups --id <ID> --remote-bucket https://..../backups --bandwidth 500K`
`mc: <ERROR> Unable to update remote target `...` from `backups` -> `backups`. Bandwidth limit for remote target must be atleast 100MBps.`

Docs page for the --bandwidth flag mentions options down to Bytes level. Can this limit be removed to allow lower threshold?
Also, --bandwidth would seem to limit both upload and download simultaneously, unlike the --limit-upload seems to imply.

**Comment by harshavardhana** [comment]
It can't be removed, if is enforced to have reasonable limits from server side. Bandwidth is for all write operations.

The doc page needs to be fixed // cc @ravindk89
