### ISSUE TITLE
XL: Attempt to combine, healFile and healVolume into same code. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1685]

**Comment by harshavardhana** [comment]
The reason is that having a bucket namespace consistent with healing is important for objects to be created. During a CreateFile if volumes are missing and can be healed should be healed before attempting the CreateFile. 

This also means that we can make healing code common and do both the jobs.

**Comment by balamurugana** [comment]
TBD. Its not clear enough how to combine healVolume() and healFile() together.

**Comment by harshavardhana** [comment]
Duplicate of #1745
