### ISSUE TITLE
`mc admin policy set` errors

### ISSUE THREAD

**Issue by janet** [minio/minio#16877]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

👋 Hello! I am seeing an error occur with the linux cli command `mc admin policy set`. I don't believe I saw this before, and the docs seem to still point to use this command. The error message is routing me to use `mc admin policy attach` instead. If that is correct, should the docs be updated? Thank you!

## Expected Behavior
```
mc admin policy set myminio readwritepolicy group=rwusers
```
No error

## Current Behavior

```
mc admin policy set myminio readwritepolicy group=rwusers
mc: <ERROR> Incorrect command. Please use 'mc admin policy attach'.
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2022-10-29T06-21-33Z (commit-id=d765b89a63c225ca271ef6d031a7bcc8fe9137df)
Runtime: go1.19.2 linux/amd64

(`mc --version`): mc version RELEASE.2023-03-20T17-17-53Z (commit-id=88896ae495128646081d8f809b8934c74cb90194)
Runtime: go1.19.7 linux/amd64

* Server setup and configuration:
* Operating System and version (`uname -a`): `Linux a3be1d20dbd7 5.4.0-1072-aws #77~18.04.1-Ubuntu SMP Thu Apr 7 21:38:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> ```
> mc admin policy set myminio readwritepolicy group=rwusers
> mc: <ERROR> Incorrect command. Please use 'mc admin policy attach'.
> ```

Use the new command line not sure why this is an issue @janet 

```
mc admin policy attach myminio/ readwritepolicy --group=rwusers
```

**Comment by harshavardhana** [comment]
> The error message is routing me to use `mc admin policy attach` instead. If that is correct, should the docs be updated? Thank you!

docs are getting there.. should be updated soon.

**Comment by janet** [comment]
@harshavardhana Thanks for the quick reply!

When I try the command you suggest, I get this error:
```
mc: <ERROR> Unable to attach the policy. This 'admin' API is not supported by server in 'mode-server-xl-single'.
```

Is this expected? 

Sorry if flagging as an issue was incorrect! I thought the `policy set` command should work, is that deprecated then based on a specific version?

**Comment by harshavardhana** [comment]
you need to update server as well @janet

**Comment by harshavardhana** [comment]
> Sorry if flagging as an issue was incorrect! I thought the `policy set` command should work, is that deprecated then based on a specific version?

if you upgrade `mc` - you must upgrade your `minio` as well as a practice
