### ISSUE TITLE
Expired files not removed from disk

### ISSUE THREAD

**Issue by prasus** [minio/minio#16879]
We have a MinIO deployment running in our self hosted kubernetes cluster and it works great, but I am having an issue with ILM policies,  We have a non-versioned bucket containing numerous mp4 files, and it has an ILM policy enabled to delete files older than 2 days, the ilm policy is created using the `mc ilm add --expiry-days 2 minio/verification-videos-v1` command.

```
mc ilm ls minio/verification-videos-v1/                                                     
          ID          |     Prefix     |  Enabled   | Expiry |  Date/Days   |  Transition  |    Date/Days     |  Storage-Class   |          Tags          
----------------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------------
 cgd9pkf1mles73aotf0g |                |    ✓       |  ✓     |   2 day(s)   |     ✗        |                  |                  |                        
----------------------|----------------|------------|--------|--------------|--------------|------------------|------------------|------------------------
```

The policy rule works fine and I don't see any files older than 2 days while listing files using  mc cli, but I recently noticed that the deleted files are **are not removed** from the disk. I can see all the files older than 2 days If I inspect the filesystem from the pod, our disk usage is increasing rapidly due to this, forcing us to extend the disk space periodically.

```
mc ls minio/verification-videos-v1 | wc -l
85999

kubectl exec -i minio-4 -- ls /data/verification-videos-v1/ | wc -l
277431
```
```
mc ilm ls minio/verification-videos-v1/ --json 
{
 "status": "success",
 "target": "minio/verification-videos-v1/",
 "config": {
  "Rules": [
   {
    "AbortIncompleteMultipartUpload": {},
    "Expiration": {
     "Date": "0001-01-01T00:00:00Z",
     "Days": 2,
     "DeleteMarker": false
    },
    "ID": "cgd9pkf1mles73aotf0g",
    "Filter": {
     "And": {},
     "Tag": {}
    },
    "NoncurrentVersionExpiration": {
     "NoncurrentDays": 0
    },
    "NoncurrentVersionTransition": {},
    "Status": "Enabled",
    "Transition": {
     "Date": "0001-01-01T00:00:00Z"
    }
   }
  ]
 }
}
```
## Expected Behavior

The following ILM expiration rule on a non-versioned bucket should function in such a way that it removes objects older than the given `--expiry-days` from the underlying disk.

`mc ilm add --expiry-days 2 minio/verification-videos-v1`

## Current Behavior

The expired files are not removed from the storage, even though they are not visible when listing with the mc cli.

## Your Environment
* Version used: `2023-02-10T18-48-39Z`
* Chart: `bitnami/minio`  Version: `v12.1.5`
* Operating System and version: kubernetes deployment using `bitnami/minio` chart, 8 replicas. 
```
mc admin info minio                           
●  minio-0.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-1.minio-headless.minio.svc.cluster.local:9000
   Uptime: 2 days 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-2.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-4.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-5.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-6.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-7.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

●  minio-3.minio-headless.minio.svc.cluster.local:9000
   Uptime: 1 week 
   Version: 2023-02-10T18:48:39Z
   Network: 8/8 OK 
   Drives: 1/1 OK 

218 GiB Used, 13 Buckets, 397,670 Objects
8 drives online, 0 drives offline
```

**Comment by harshavardhana** [comment]
Are there any server logs that you can share @prasus ?

**Comment by prasus** [comment]
Thank you! @harshavardhana 🙏🏿 unfortunately, there are no helpful logs available. Would it be beneficial if I enable debug logging (`BITNAMI_DEBUG: true`) and share the resulting logs with you? Thanks.

**Comment by harshavardhana** [comment]
> Thank you! @harshavardhana 🙏🏿 unfortunately, there are no helpful logs available. Would it be beneficial if I enable debug logging (`BITNAMI_DEBUG: true`) and share the resulting logs with you? Thanks.

ILM must apply if `mc ls` is filtering it. 

> Version: 2023-02-10T18:48:39Z

Have you tried upgrading and checking?

**Comment by prasus** [comment]
Thanks @harshavardhana I will perform an upgrade to the latest bitnami chart and will let you know.

**Comment by prasus** [comment]
Thank you, @harshavardhana  I updated to the `2023-03-22T06:36:24Z` release and it helped to fix it 👍🏿 all files older than two days got removed from the disk.

```
for i in {1..7}; do kubectl exec -i minio-$i -- ls -ltrn /data/verification-videos-v1 | wc -l; done
93223
93224
93224
93224
93225
93225
93225

k exec -i minio-1 -- ls -ltrn /data/verification-videos-v1 | wc -l                                 
93226

before the upgrade:
218 GiB Used, 13 Buckets, 397,670 Objects

after the upgrade:
85 GiB Used, 13 Buckets, 135,564 Objects
```

I will close this for now, will reopen in case if I encounter the same issue again in the future, thanks!
