### ISSUE TITLE
Password MINIO_ROOT_PASSWORD from file

### ISSUE THREAD

**Issue by psztoch** [minio/minio#16875]
**Is your feature request related to a problem? Please describe.**
Note that environment variables are not suitable for passing secrets (such as passwords, key material, ...) to
service processes. Environment variables set for a unit are exposed to unprivileged clients via D-Bus IPC, and
generally not understood as being data that requires protection. Moreover, environment variables are
propagated down the process tree, including across security boundaries (such as setuid/setgid executables),
and hence might leak to processes that should not have access to the secret data.

Check `LoadCredential=` in `man systemd.exec`.

**Describe the solution you'd like**
Add support for new environment variable with location of password file, in example MINIO_ROOT_PASSWD=/etc/minio/minio-root.passwd

**Comment by harshavardhana** [comment]
You can specify 

MINIO_CONFIG_ENV_FILE=/etc/minio/whatever.env

You can specify all your environment values this way.

**Comment by psztoch** [comment]
I will consider it. Nevertheless, no one wants to keep the encrypted configuration, only the password...
And the issue of secure encryption with TMP is covered here by systemd.
I think such an additional parameter would be useful.

**Comment by harshavardhana** [comment]
> I will consider it. Nevertheless, no one wants to keep the encrypted configuration, only the password... And the issue of secure encryption with TMP is covered here by systemd. I think such an additional parameter would be useful.

The MinIO's configuration set via environment variables has other secrets as well that requires protection. So it needs to be a common env file instead of just one file for password.

You are not there yet in terms of usage so you don't see the overall picture yet.

Also this password won't be special anymore #16806 and it never needs to be.
