### ISSUE TITLE
Latest HELM Chart Version 5.0.7 is not installing on k8s 1.24 and SLES OS

### ISSUE THREAD

**Issue by VinayVamsi143** [minio/minio#16889]
Latest HELM Chart Version 5.0.7 is not installing on k8s 1.24 and SLES OS

Expected Behavior
chart should install successfully on provided mounted path on the chart, should be able to access minio
mounted path permission used is 777

Current Behavior
chart is not installing and throwing error says:

API: SYSTEM()
Time: 15:12:18 UTC 03/24/2023
Error: unable to rename (/backuprestore/.minio.sys/tmp -> /backuprestore/.minio.sys/tmp-old/14e0de11-9ae3-4de6-9f5b-f75def6d9011) file access denied, drive may be faulty please investigate (*fmt.wrapError)
6: internal/logger/logger.go:258:logger.LogIf()
5: cmd/prepare-storage.go:88:cmd.bgFormatErasureCleanupTmp()
4: cmd/xl-storage.go:252:cmd.newXLStorage()
3: cmd/object-api-common.go:61:cmd.newStorageAPI()
2: cmd/format-erasure.go:673:cmd.initStorageDisksWithErrors.func1()
1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 15:12:18 UTC 03/24/2023
Error: unable to create (/backuprestore/.minio.sys/tmp) file access denied, drive may be faulty please investigate (*fmt.wrapError)
6: internal/logger/logger.go:258:logger.LogIf()
5: cmd/prepare-storage.go:95:cmd.bgFormatErasureCleanupTmp()
4: cmd/xl-storage.go:252:cmd.newXLStorage()
3: cmd/object-api-common.go:61:cmd.newStorageAPI()
2: cmd/format-erasure.go:673:cmd.initStorageDisksWithErrors.func1()
1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
ERROR Unable to use the drive /backuprestore: drive access denied: Invalid arguments specified

Possible Solution
Chart should install without an issue.

Steps to Reproduce (for bugs)
1.download latest chart version that is 5.0.7.
2. provide valid secret key and access key with valid mount path along with right user access.
3. when you install helm chart in K8s 1.24 and SLES OS version chart is failing to install throws above error

Your Environment
SLES OS
Kubernetes 1.24

Kindly let me know if more details needed.

**Comment by harshavardhana** [comment]
@VinayVamsi143 the answer is same please fix your backend disk permissions.

**Comment by harshavardhana** [comment]
> chart should install successfully on provided mounted path on the chart, should be able to access minio
> mounted path permission used is 777

Its not `chmod` you need to do `chown -R 1000.` since the security context is added.

**Comment by VinayVamsi143** [comment]
RUN chown -R 1000:1000 /export 
RUN chmod -R 777 /export 
this is the command i used to create a Docker conatiner

**Comment by VinayVamsi143** [comment]
> 

@harshavardhana  please check what is wrong with that configuration

**Comment by VinayVamsi143** [comment]
RUN  mkdir -p /backuprestore && chown -R 1000:1000 /backuprestore && chmod -R 777 /backuprestore 

![image](https://user-images.githubusercontent.com/39741400/227587129-6ab8b01f-7184-4a37-92d2-c9f29e3607d9.png)
![image](https://user-images.githubusercontent.com/39741400/227589387-c8c34cb6-9d14-4688-9ebc-acdf968f65d7.png)

@harshavardhana  please find the images above
