### ISSUE TITLE
Minio recursive delete all the folders with the same initial suffix

### ISSUE THREAD

**Issue by muhammad-asn** [minio/minio#16880]
## NOTE
When deleting the folders with `--recursive` flags, it shows not only the associated folders that we wanted to delete
but also another folders with the same suffix.

## Expected Behavior
Only delete the folders with name `test-name-1`.

## Current Behavior
Delete all the folders with the same respective initial suffix. E.g the folder name `test-name-1*`.

From the console:
<img width="1433" alt="Screen Shot 2023-03-23 at 12 55 15" src="https://user-images.githubusercontent.com/88309796/227117774-a2989b04-6a95-4c3f-9778-3e0800bf225e.png">

After the deletion:
<img width="922" alt="Screen Shot 2023-03-23 at 12 56 59" src="https://user-images.githubusercontent.com/88309796/227117848-2b6388f7-dabd-4bcc-8c4b-3550293aefb5.png">

## Steps to Reproduce (for bugs)
1. Create a new folders (with the same respective initial suffix, e.g: `test-1`, `test-100`, `test-1000`) and upload some files in each respective folders. 
2. Delete the folder using `mc` cli. `mc rm --recursive <host>/<bucket_name>/test-1 --force`

## Context
It is terrifying if we want to delete only the associated folders, but in the end all the folders with the same initial suffix also got deleted.

## Regression
-

## Your Environment

* Version used (`minio --version`):
``` bash
$ minio --version
minio version RELEASE.2023-03-20T20-16-18Z (commit-id=05444a0f6af8389b9bb85280fc31337c556d4300)
```
* Server setup and configuration:
In docker
* Operating System and version (`uname -a`):
```
$ uname -a
Linux minio 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
This is normal @muhammad-asn you need to provide `/` at the end to make sure that only relevant prefix gets deleted. This is not unusual since in S3 API everything is a flat key there is no "directory" concept.

**Comment by muhammad-asn** [comment]
Ah I see, thank you.
