### ISSUE TITLE
mc: `attach` is not a recognized command

### ISSUE THREAD

**Issue by ehemmerlin** [minio/minio#16885]
After installing MinIO Release [RELEASE.2023-03-22T06-36-24Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-03-22T06-36-24Z) on an on-premise cluster, the MinIO job fails with this error:
```
Connecting to MinIO server: http://minio-1679593602:9000
Added `myminio` successfully.
User 'console' already exists.
Adding policy 'consoleAdmin' for 'console'
mc: <ERROR> `attach` is not a recognized command. Get help using `--help` flag.
```
## Expected Behavior
MinIO job should end successfully.

## Current Behavior
Currently MinIO job fails.

## Possible Solution
Recently [docs/bucket/replication/setup_replication.sh](https://github.com/minio/minio/commit/fb1492f5317bddb263092b69218c5a2c23025d19#diff-5e276c022dc538e65691a393ca164137a499d8a12afd739d1b19b8ed713cea5d) has been updated with attach instead of set:
```
- mc admin policy set source repladmin-policy user=repladmin
+ mc admin policy attach source repladmin-policy --user=repladmin
```

## Steps to Reproduce
1. Download RELEASE.2023-03-22T06-36-24Z files and put the helm files in the directory /root/minio
2. Install MinIO
```
helm install --namespace minio --set rootUser=rootuser,rootPassword=rootPassword --generate-name --set resources.requests.memory=1Gi --set replicas=3 --values values.yaml /root/minio
```

## Your Environment
* Release: RELEASE.2023-03-22T06-36-24Z
* Server setup and configuration: Kubernetes 1.25.6
* Operating System and version (`uname -a`): Ubuntu 5.4.0-137-generic

**Comment by harshavardhana** [comment]
You need to upgrade `mc` as well @ehemmerlin to get the latest commands.

**Comment by ehemmerlin** [comment]
Thank you @harshavardhana. You mean upgrade mc image tag from RELEASE.2023-01-28T20-29-38Z (which is the actual value in values.yaml file) to RELEASE.2023-03-20T17-17-53Z (which is the latest tag in https://quay.io/repository/minio/mc)?

**Comment by harshavardhana** [comment]
> Thank you @harshavardhana. You mean upgrade mc image tag from RELEASE.2023-01-28T20-29-38Z (which is the actual value in values.yaml file) to RELEASE.2023-03-20T17-17-53Z (which is the latest tag in https://quay.io/repository/minio/mc)?

Correct, I am updating the `mc` image as we speak with new helm release @ehemmerlin
