### ISSUE TITLE
Latest HELM Chart Version 5.0.7 is not installing on k8s 1.24 and SLES OS

### ISSUE THREAD

**Issue by VinayVamsi143** [minio/minio#16888]
**Latest HELM Chart Version 5.0.7 is not installing on k8s 1.24 and SLES OS** 

## Expected Behavior
chart should install successfully on provided mounted path on the chart, should be able to access minio 

## Current Behavior
chart is not installing and throwing error says:

API: SYSTEM()
Time: 15:12:18 UTC 03/24/2023
Error: unable to rename (/backuprestore/.minio.sys/tmp -> /backuprestore/.minio.sys/tmp-old/14e0de11-9ae3-4de6-9f5b-f75def6d9011) file access denied, drive may be faulty please investigate (*fmt.wrapError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/prepare-storage.go:88:cmd.bgFormatErasureCleanupTmp()
       4: cmd/xl-storage.go:252:cmd.newXLStorage()
       3: cmd/object-api-common.go:61:cmd.newStorageAPI()
       2: cmd/format-erasure.go:673:cmd.initStorageDisksWithErrors.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 15:12:18 UTC 03/24/2023
Error: unable to create (/backuprestore/.minio.sys/tmp) file access denied, drive may be faulty please investigate (*fmt.wrapError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/prepare-storage.go:95:cmd.bgFormatErasureCleanupTmp()
       4: cmd/xl-storage.go:252:cmd.newXLStorage()
       3: cmd/object-api-common.go:61:cmd.newStorageAPI()
       2: cmd/format-erasure.go:673:cmd.initStorageDisksWithErrors.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
ERROR Unable to use the drive /backuprestore: drive access denied: Invalid arguments specified

## Possible Solution
Chart should install without an issue. 

## Steps to Reproduce (for bugs)
1.download latest chart version that is 5.0.7. 
2. provide valid secret key and access key with valid mount path along with right user access. 
3. when you install helm chart in K8s 1.24 and SLES OS version chart is failing to install throws above error 

## Your Environment
SLES OS 
Kubernetes 1.24 

Kindly let me know if more details needed.

**Comment by harshavardhana** [comment]
@VinayVamsi143 your folder permissions need to be fixed.

**Comment by VinayVamsi143** [comment]
hi @harshavardhana  i am creating a folder with 777 permission still same issue

**Comment by VinayVamsi143** [comment]
> @VinayVamsi143 your folder permissions need to be fixed.

yes, i am using folder permissions with 777 still it is same issue
