### ISSUE TITLE
Create user script fails due to policy already being attached

### ISSUE THREAD

**Issue by PKizzle** [minio/minio#16897]
## Current Behavior
When upgrading the helm chart and the users and policies specified in the `values.yaml` file already exist the `_helper_create_user.txt` script fails. This is due to the breaking changes introduced with [RELEASE.2023-03-20T17-17-53Z of mc](https://github.com/minio/mc/releases/tag/RELEASE.2023-03-20T17-17-53Z). Instead of setting the policy for a user now it can only be attached. However, if the policy is already attached to the user the mc command will fail.

https://github.com/minio/minio/blob/4c5edacae22bc50f4274eafd6223f1ccc7a6208c/helm/minio/templates/_helper_create_user.txt#L76

## Possible Solution
Logic needs to be added to determine whether the exact same policy is already attached to the user and act accordingly. Another option would be to always remove all policies that shall be updated and re-create and re-attach them each time.

## Steps to Reproduce (for bugs)
1. Install the minio helm chart from github's master branch and update the `values.yaml` file to include users and policies
2. Update some policy and/or user and try to upgrade the helm chart 

## Context
Since this is the development version of the helm chart and has not been released it does only affect those who want to test out the latest changes. 

## Regression
Using a version of the `mc` command that still has the set command available is the best workaround for now. For example use version https://github.com/minio/mc/releases/tag/RELEASE.2023-02-28T00-12-59Z

## Your Environment
* Version used (`minio --version`): [RELEASE.2023-03-24T21-41-23Z](https://github.com/minio/minio/releases/tag/RELEASE.2023-03-24T21-41-23Z)
* Server setup and configuration: Helm chart (github master branch)
* Operating System and version (`uname -a`): Linux 5.15.84-v8+ #&#x2060;11613 SMP PREEMPT aarch64 GNU/Linux - RaspberryPi OS

**Comment by nodesocket** [comment]
I just ran into this issue. What's the fix?

Helm chart `5.0.7`
minio version `tag: RELEASE.2023-03-24T21-41-23Z`
mc version `tag: RELEASE.2023-03-23T20-03-04Z`

**Comment by PKizzle** [comment]
There is no fix available for now. For the time being you could simply use an older mc version as suggested above in the regression section.

**Comment by harshavardhana** [comment]
This is fixed already by allowing failures for this command in the helm charts.
