### ISSUE TITLE
Make removal of /crossdomain.xml a configurable property

### ISSUE THREAD

**Issue by yongyct** [minio/minio#16909]
**Is your feature request related to a problem? Please describe.**
Some security scans will pickup the /crossdomain.xml path and complain about the below:
```
Permissive crossdomain.xml policy files allow external Adobe Flash (SWF) scripts to interact with your website.
Depending on how authorization is restricted on your website, this could inadvertently expose data to other domains or allow invocation of functionality across domains. The cross-domain policy file should permit only domains that can be trusted to make requests that include the user's domain-specific cookies.
See Cross-domain policy file usage recommendations for Flash Player
```
Minio seems to have [implemented a relaxed crossdomain.xml to match what S3](https://github.com/minio/minio/issues/2301) has to support legacy applications. And this is embedded into the [codebase](https://github.com/minio/minio/blob/master/cmd/crossdomain-xml-handler.go). 

**Describe the solution you'd like**
A configuration to remove this crossdomain.xml (or at least be able to specify the allowed domains) will be good for users who don't require support for legacy applications.

**Describe alternatives you've considered**
N.A.

**Additional context**
This will be useful for enterprises who performs regular scans on the deployed storage solutions

**Comment by jiuker** [comment]
@harshavardhana Do you want to add an environment variable, and then this environment variable is on by default, and if it is off you can not show this route, what do you think? I can contribute

**Comment by ArpitKRS** [comment]
Please /assign this issue to me and let's discuss over it.

**Comment by lixingwu** [comment]
Our company's security scan also encountered risk alerts, and we hope to be able to customize the configuration.

**Comment by Teketel** [comment]
Yes, this is becoming security issue while MinIO deployed in large enterprises
Is there a way to configure our own custom `crossdomain.xml`.?

**Comment by harshavardhana** [comment]
> Yes, this is becoming security issue while MinIO deployed in large enterprises
> Is there a way to configure our own custom `crossdomain.xml`.?

who are those enterprises? care to name some of them?
