### ISSUE TITLE
XL: Create unique tmp files 27th

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1690]
The temporary file that we create (and ultimately rename to the actual location) should be unique, because as of now it gets created in as `.minio/tmp/bucket/object` on which race can happen.

**Comment by krishnasrinivas** [comment]
@harshavardhana assign this to me

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the timeline.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the timeline for closing this issue!

**Comment by harshavardhana** [comment]
@balamurugana can you rebase the changes against the rewrite-xl branch?

**Comment by harshavardhana** [comment]
Fixed by #1790
