### ISSUE TITLE
Error: not authorized: insufficient permissions (kes.Error)

### ISSUE THREAD

**Issue by tsohst** [minio/minio#16908]
* Minio is currently not starting in our environment after upgradeing to the newest release in combination with KES
* `Error: not authorized: insufficient permissions (kes.Error)`
* We are unable to find out if there was a change in minio which needs more permissions to use KMS?
  * API-Documentation of KES did not change since 2022, and we've upgraded from a Jan 23 release to the newest
  * https://github.com/minio/kes/wiki/Server-API#api-overview
* These endpoints we're the only one needed before and it seems like minio needs more with newer releases?
 ```
    - /v1/key/create/* 
    - /v1/key/generate/* 
    - /v1/key/decrypt/*
```

## Expected Behavior
* Minio should start as usual

## Current Behavior
```
Mär 28 13:51:57 minio2 minio[13835]: Documentation: https://min.io/docs/minio/linux/index.html
Mär 28 13:51:57 minio2 minio[13835]: API: SYSTEM()
Mär 28 13:51:57 minio2 minio[13835]: Time: 11:51:57 UTC 03/28/2023
Mär 28 13:51:57 minio2 minio[13835]: DeploymentID: e425c60c-3de5-42d3-81c5-09a620eaf8c6
Mär 28 13:51:57 minio2 minio[13835]: Error: not authorized: insufficient permissions (kes.Error)
Mär 28 13:51:57 minio2 minio[13835]:        5: internal/logger/logger.go:258:logger.LogIf()
Mär 28 13:51:57 minio2 minio[13835]:        4: cmd/api-errors.go:2280:cmd.toAPIErrorCode()
Mär 28 13:51:57 minio2 minio[13835]:        3: cmd/api-errors.go:2305:cmd.toAPIError()
Mär 28 13:51:57 minio2 minio[13835]:        2: cmd/healthcheck-handler.go:134:cmd.LivenessCheckHandler()
Mär 28 13:51:57 minio2 minio[13835]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
* After removing the "policy" section in kes config and enable admin identity minio is working again.

## Steps to Reproduce (for bugs)
* Upgrade to RELEASE.2023-03-24T21-41-23Z
* restarting minio service results in error above
* upgrade KES to 2023-02-15T14-54-37Z _did not fix it_

## Context
* Upgraded MINIO from a release of january to: 
  * minio version RELEASE.2023-03-24T21-41-23Z (commit-id=74040b457b50417b58eae7cb17c63428a0e2dd44)
  * kes 2023-02-15T14-54-37Z (commit=8ce403b264e3c6fafb94577dd1c59ae811963e43)

## Your Environment
**We have set the following Env vars for minio regaring KES:**
```
MINIO_KMS_KES_ENDPOINT
MINIO_KMS_KES_ENDPOINT
MINIO_KMS_KES_CERT_FILE
MINIO_KMS_KES_KEY_FILE
MINIO_KMS_KES_CAPATH
MINIO_KMS_KES_KEY_NAME
```
* **This was our kes-config before the upgrade**
```
address: 0.0.0.0:7373

admin:
  identity: disabled 

root: disabled

tls:
  key:  /minio/certs/private.key
  cert: /minio/certs/public.crt

policy:
  minio-kes:
    allow:
    - /v1/key/create/*   
    - /v1/key/generate/* 
    - /v1/key/decrypt/*
    identities:
    - ABCD

log:
  error: on
  audit: on

keystore:
  vault:
    endpoint: https://vault:8200
    engine: "minio-kes"    
    version: "v2"   
    approle:
      id: "YYYYYYY"     
      secret: "ZZZZZZZ"
      retry: 15s
    status:
      ping: 10s
```
* **This is our kes-config AFTER the upgrade to fix the issue**
```
address: 0.0.0.0:7373

admin:
  identity: ABCD

root: disabled

tls:
  key:  /minio/certs/private.key
  cert: /minio/certs/public.crt

log:
  error: on
  audit: on

keystore:
  vault:
    endpoint: https://vault:8200
    engine: "minio-kes"    
    version: "v2"   
    approle:
      id: "YYYYYYY"     
      secret: "ZZZZZZZ"
      retry: 15s
    status:
      ping: 10s
```

**Comment by harshavardhana** [comment]
You need to add

```
allow:
    - /v1/key/create/*   
    - /v1/key/generate/* 
    - /v1/key/decrypt/*
    - /v1/key/list*
    - /v1/status
    - /v1/metrics
```

**Comment by tsohst** [comment]
Where is the correct documentation?
This Site does not seem to reference all endpoints. 
https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html

In fact, was there a breaking Change regarding the endpoints this year? Because it worked with only "create, generate, decrypt" in a Release from the beginning of the year.

**Comment by ravindk89** [comment]
Sure - @harshavardhana @aead what release did we expand the permission set? I'd like to include that as guidance.

I am guessing that encryption still works (since we have create/generate/decrypt), but some subfunctions would fail? Thus not "breaking", just "errors in those areas we lack perms"?

**Comment by harshavardhana** [comment]
> 

It's MinIO not Kes related, MinIO needs more permissions by default now @ravindk89

**Comment by tsohst** [comment]
Since MINIO is not even starting after the upgrade I would say it's breaking?
Interresting is that the KES log was not showing any errors or even the access to these endpoints.
```    
    - /v1/key/list*
    - /v1/status
    - /v1/metrics
```
I will test it later and see if thats the issue.
Wondering why I am the first one having issues with that..

**Comment by ravindk89** [comment]
@tsohst just to confirm, what January release were you using?
