### ISSUE TITLE
Is it possible to provide a plug-in mechanism to support the processing of resource objects?

### ISSUE THREAD

**Issue by Aaron-PanJi** [minio/minio#16901]
**Is your feature request related to a problem? Please describe.**
When using minio as an image server, minio cannot process the image, such as cropping, flipping, thumbnail, etc.
**Describe the solution you'd like**
Provide a plugin mechanism, through which the object requested by the user can be customized.
**Describe alternatives you've considered**
Handle requests with external services,such as imageproxy, nginx_filter_module.

**Additional context**
None

**Comment by harshavardhana** [comment]
Read https://blog.min.io/minio-object-lambda/
