### ISSUE TITLE
No error at upload with HTTP headers that were not signed

### ISSUE THREAD

**Issue by AndreeaCapatina** [minio/minio#16917]
I tried to upload a file to minio server using the pre signed URL obtained with php s3client. Nothing was provided to the Metadata option of the s3client. 
When doing the upload, however,  I added a metadata header `X-Amz-Meta-A: B`.  I notice a different behaviour between minio and AWS in this scenario. 

## Expected Behavior

Minio and AWS should be consistent. Minio should return an error if metadata headers are present in the request but not when generating the signed URL.  
## Current Behavior

AWS returns an error if the upload request contains metadata headers that were not signed. 
With minio, the file is uploaded and the metadata are saved. 

## Steps to Reproduce (for bugs)

1.Make an API call on both AWS and minio to get an upload pre signed URI, like so (here using PHP):
```
$cmd = $client->getCommand('PutObject', [
    'Bucket' => 'mybucket',
    'Key'    => 'image.jpg'
]);

$response = $client->createPresignedRequest($cmd, '+60 minutes')->withMethod('PUT');
$uri = $response->getUri();
```
As we can see, I didn't added any metadata to be signed.
2.  Make an upload request, with at least one metadata header. Here is a simple curl example I used to upload a file:
```
$curl = curl_init();

curl_setopt($curl, CURLOPT_URL,  $uri);

$headers[] = 'X-Amz-Meta-A: B';
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($curl, CURLOPT_PUT, true);

$content = fopen($filePath, 'rb');
curl_setopt($curl, CURLOPT_INFILE, $content);
curl_setopt($curl, CURLOPT_INFILESIZE, filesize($filePath));

$responseBody = curl_exec($curl);
```
3.  For AWS, you should receive an error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><HeadersNotSigned>x-amz-meta-a</HeadersNotSigned></Error>
```
4. Minio currently doesn't return any error and the metadata are saved. 
```
myminio [REQUEST s3.PutObject] [2023-03-29T08:39:56.060] [Client IP: localhost]
myminio PUT /mybucket/image.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20230329%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230329T083956Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=697eced06a5acecc3d646a8ea2d27bab126322917d0d0068b01f5e1a420b1732
myminio Proto: HTTP/1.1
myminio Host: localhost
myminio Accept: */*
myminio Content-Length: 51260
myminio Expect: 100-continue
myminio X-Amz-Meta-A: B
myminio <BLOB>
myminio [RESPONSE] [2023-03-29T08:39:56.066] [ Duration 6.005ms  ↑ 50 KiB  ↓ 0 B ]
myminio 200 OK
myminio X-Amz-Request-Id: 1750D7209BB49BC0
myminio Accept-Ranges: bytes
myminio Content-Length: 0
myminio Content-Security-Policy: block-all-mixed-content
myminio Server: MinIO
myminio Strict-Transport-Security: max-age=31536000; includeSubDomains
myminio Vary: Origin,Accept-Encoding
myminio ETag: "7013d47ff2e11074bb8ed32c3f23b606"
myminio X-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
myminio X-Content-Type-Options: nosniff
myminio X-Xss-Protection: 1; mode=block
myminio x-amz-version-id: 16ebbc9e-1c0b-4e95-9ced-358af3a696de
myminio <BLOB>
```

## Your Environment

* Version used (`minio --version`): 
```minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.19 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```
* Server setup and configuration: Operating System and version (`uname -a`): 
``` 
Linux  4.18.0 #1 SMP Tue Jan 25 12:49:12 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vadmeste** [comment]
@AndreeaCapatina what is the value of X-Amz-SignedHeaders in the presigned link generated for AWS S3 ?

**Comment by AndreeaCapatina** [comment]
@vadmeste the value is `X-Amz-SignedHeaders=host`.

**Comment by harshavardhana** [comment]
Then those headers are not signed, so you can change them. All headers that need to be validated must be part of headers signed.

**Comment by AndreeaCapatina** [comment]
Yes, but how can I make sure that whoever uses the URL is not able to add metadata if I didn't added when I signed it?

**Comment by harshavardhana** [comment]
> Yes, but how can I make sure that whoever uses the URL is not able to add metadata if I didn't added when I signed it?

You need to ask the client to sign the headers first. I am not sure if those SDKs have those provisions you need to consult their documentation.

**Comment by AndreeaCapatina** [comment]
> > Yes, but how can I make sure that whoever uses the URL is not able to add metadata if I didn't added when I signed it?
> 
> You need to ask the client to sign the headers first. I am not sure if those SDKs have those provisions you need to consult their documentation.

I feel that I was not clear enough. 
I am referring to the use case when **I don't want to add any** metadata to a file. I explicitly chose not to add **any** when I generated the pre signed URL. 
But, whoever is using the pre signed URL can set a `X-Amz-Meta-*` header and the header will be saved as metadata. 

As I mentioned in the original description, AWS is returning an error in this scenario, but Minio doesn't.
