### ISSUE TITLE
minio_heal_objects_heal_total metric value is not 0 when the cluster disk is healthy

### ISSUE THREAD

**Issue by vklonghml** [minio/minio#16916]
**Is your feature request related to a problem? Please describe.**
recently, i just deploy a minio cluster with 4 node with 2023-01-28T07-05-05Z version,  after a week, i found the minio_heal_objects_heal_total metric value is not null, the value is 1000+ for every node. 

Then i start to research minio source code, under normal circumstances, that metric value should be 0. Only the objects were being repaired because of disk error or something, that metric value is not 0.

So i want to ask, how this question happened, it is just right, or there is other situation, thanks in advance.

**Comment by harshavardhana** [comment]
Healing can happen on objects when there are temporary

- network disconnects
- you took down a node for maintenance and then brought it back up.

This value is overall healing, its not just about replacing disks.

It simply shows that your cluster is unstable and needs to be healed constantly.

**Comment by vklonghml** [comment]
> Healing can happen on objects when there are temporary
> 
> * network disconnects
> * you took down a node for maintenance and then brought it back up.
> 
> This value is overall healing, its not just about replacing disks.
> 
> It simply shows that your cluster is unstable and needs to be healed constantly.

thank for your quick reply, but 
1) my demo cluster only 4 nodes with 4 disks,
2) the total object is 50000
3) network is local area network,
4) do not execute maintenance operation ever
5) check the node status, they are healthy in one week

so i wander, if there is other situation which could cause the object repair, or there is other method to check object really be repaired
