### ISSUE TITLE
Creating a bucket on deletion of bucket with name doesn't exist

### ISSUE THREAD

**Issue by EwgeniWolowik** [minio/minio#16915]
On deletion of bucket with name doesn't exist bucket will be created with given name

## Expected Behavior
Only correct error message, no creating a bucket on deleting it

## Possible Solution
Found first in RELEASE.2023-03-**22**T06-36-24Z
So changes from RELEASE.2023-03-20T20-16-18Z to RELEASE.2023-03-22T06-36-24Z are reason for the error

## Steps to Reproduce (for bugs)

1. Pull newest minio/minio image
2. Start empty container (no buckets, nothing)
3. Send DELETE bucket REST request (via Postman) with bucket name doesn't exist
4. Receive correct error message
> \<Code>NoSuchBucket\</Code>
> \<Message>The specified bucket does not exist\</Message>
> \<BucketName>abc42\</BucketName>
5. Check container: bucket with given name ('abc42') exists

## Your Environment
Docker images on Windows and Linux

**Comment by harshavardhana** [comment]
@EwgeniWolowik please provide more details. 

- share the postman reproducer
- share output of mc ls alias/ to show the bucket already exists

**Comment by EwgeniWolowik** [comment]
Sure.

- Start server
`docker run --rm --name minio_server -p 9000:9000 -p 9090:9090 -e "MINIO_ROOT_USER=minioadmin" -e "MINIO_ROOT_PASSWORD=minioadmin" minio/minio:latest server /data --console-address ":9090"`

- List buckets by REST via Postman
`curl --location --request GET 'http://minio_server:9000/' --header 'X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' --header 'X-Amz-Date: 20230330T054837Z' --header 'Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230330/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=fec33f3380a7b7974cba2054e821f14da1e1063ad5f98937d00c8c723e8034a7'`

- Answer
> \<?xml version="1.0" encoding="UTF-8"?>
> \<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> &emsp;\<Owner>
> &emsp;&emsp;\<ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4\</ID>
> &emsp;&emsp;\<DisplayName>minio\</DisplayName>
> &emsp;\</Owner>
> &emsp;\<Buckets>\</Buckets>
> \</ListAllMyBucketsResult>

- Delete bucket with name doesn't exist
`curl --location --request DELETE 'http://minio_server:9000/abc42' --header 'X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' --header 'X-Amz-Date: 20230330T054928Z' --header 'Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230330/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=9d796325ff25c3429b89b62de06cb95bc2536f80a0bd754db49c86de563ff36b'`

- Answer
> \<?xml version="1.0" encoding="UTF-8"?>
> \<Error>
> &emsp;\<Code>NoSuchBucket\</Code>
> &emsp;\<Message>The specified bucket does not exist\</Message>
> &emsp;\<BucketName>abc42\</BucketName>
> &emsp;\<Resource>/abc42\</Resource>
> &emsp;\<RequestId>17511C6D354A6883\</RequestId>
> &emsp;\<HostId>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\</HostId>
> \</Error>

- List buckets again
`curl --location --request GET 'http://minio_server:9000/' --header 'X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' --header 'X-Amz-Date: 20230330T055016Z' --header 'Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230330/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=13b2ffc4d810ed31c56a4fcdf068c4a3e09c15eec373a5069492b4154570fcc3'`

- Answer
> \<?xml version="1.0" encoding="UTF-8"?>
> \<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> &emsp;\<Owner>
> &emsp;&emsp;\<ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4\</ID>
> &emsp;&emsp;\<DisplayName>minio\</DisplayName>
> &emsp;\</Owner>
> &emsp;\<Buckets>
> &emsp;&emsp;\<Bucket>
> &emsp;&emsp;&emsp;\<Name>abc42\</Name>
> &emsp;&emsp;&emsp;\<CreationDate>0001-01-01T00:00:00.000Z\</CreationDate>
> &emsp;&emsp;\</Bucket>
> &emsp;\</Buckets>
> \</ListAllMyBucketsResult>

- Delete bucket again (existing bucket) works without error
