### ISSUE TITLE
KMS not configured.

### ISSUE THREAD

**Issue by xulongZheng** [minio/minio#16913]
My execution steps are based on https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore , and https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-kms.html#minio-encryption-sse-kms-quickstart Why is the KMS not configured?

![1679992060397](https://user-images.githubusercontent.com/93906456/228419642-ff182019-5eea-412f-80b1-9dc26e77ecb3.jpg)

**Comment by harshavardhana** [comment]
> My execution steps are based on https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore , and https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-kms.html#minio-encryption-sse-kms-quickstart Why is the KMS not configured?

did you restart MinIO after you configured KMS - please share your server deployment details?

**Comment by xulongZheng** [comment]
> > 我的执行步骤基于 https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore 和 https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-kms.html#minio-encryption-sse-kms-quickstart 为什么没有配置 KMS？
> 
> 您是否在配置 KMS 后重新启动了 MinIO - 请分享您的服务器部署详细信息？

Yes, I not only restart minio service (docker restart minio), but also restart it with mc command (mc admin service restart myminio). myminio, which is an alias

**Comment by harshavardhana** [comment]
What are the KMS settings for the server ?
