### ISSUE TITLE
the value of tags can not be Chinese

### ISSUE THREAD

**Issue by aiwoziyue** [minio/minio#16935]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

My service is deployed on the docker, version mini/mini:RELEASE.2022-11-26T22-43-32Z
## Expected Behavior

The value of tags can be saved normally in Chinese when docker image version is mini/mini:RELEASE.2022-05-03T20-36-08Z.fips

## Current Behavior

An error occurred while saving the Chinese tag value when managing the object's tags on the console management platform.

## Possible Solution

Modification code: Chinese is supported when saving tags

## Regression

No

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2022-11-26T22-43-32Z (commit-id=63fc6ba2cd174ec2cbac2b022314c97bad6b6e4d)
Runtime: go1.19.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.

* Server setup and configuration: unimportance
* Operating System and version (`uname -a`): Linux minio 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Yes that is correct @Yuer-shizi - AWS S3 doesn't support this either.
