### ISSUE TITLE
Can't create/edit notify_webhook's after MinIO Server IP change

### ISSUE THREAD

**Issue by jesssyb** [minio/minio#16931]
Our MinIO servers are hosted on new IP's, and now the mc config commands no longer work to change the endpoints of the configured webhooks because connections to the old server/webhooks can't be established. It also doesn't seem like there is a way to delete webhooks using mc terminal commands.

## Expected Behavior
Expecting to be able to change config endpoints without server error

## Current Behavior
`~mc admin config get myminio notify_webhook
notify_webhook endpoint=http://10.3.74.XX:9000 auth_token= queue_limit=0 queue_dir= client_cert= client_key= 
notify_webhook:PRIMARY endpoint=http://10.3.74.XX:9000/webhook auth_token= queue_limit=0 queue_dir= client_cert= client_key= 
notify_webhook:TEST endpoint=http://10.3.74.XX:9999/webhook auth_token= queue_limit=0 queue_dir= client_cert= client_key= 

 ~ % mc admin config set myminio notify_webhook:SECONDARY \
> endpoint="http://10.3.74.XXX:9999/webhook"

mc: <ERROR> Unable to set 'notify_webhook:SECONDARY endpoint=http://10.3.74.XXX:9999/webhook' to server: error (_:webhook): not connected to target server/service.`

## Your Environment
* Version used: 2023-03-24T21:41:23Z
* Server setup and configuration/Operating System and version: Linux - Debian 11 - Linux minio01 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@jesssyb download the entire config 

```
mc admin config export alias/ > myconfig

### make all the relevant edits by removing the config that you don't want

mc admin config import alias < myconfig
```
