### ISSUE TITLE
minio pool offline a node

### ISSUE THREAD

**Issue by zxl716** [minio/minio#16948]
Minio has 2 pools, one of which consists of 8 nodes, and each node has 8 hard disks, 1T. If a node goes offline, what is the specific operation? At present, the cluster space is sufficient, and I just want to take the nodes in the pool offline and recycle them. Thanks

**Comment by harshavardhana** [comment]
You can lose up to your parity number of servers for both pools. Pools are only meant for expansion they cannot be independently entirely taken down. 

You need quorum on both pools to be operational.
