### ISSUE TITLE
minio build on go 1.20， run with “Error: file not found (cmd.StorageErr)”

### ISSUE THREAD

**Issue by chenshi5012** [minio/minio#16951]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

minio works fine on windows  build with golang 1.19 ,.   but  under 1.20  windows , after build , run with error ": file not found (cmd.StorageErr)"

--------------
API: SYSTEM()
Time: 08:13:36 UTC 04/03/2023
DeploymentID: 36d79ea3-c397-4857-95bd-b23de27b57be
Error: file not found (cmd.StorageErr)
       6: C:\Users\c00603587\Documents\GitHub\minio1\internal\logger\logger.go:259:logger.LogIf()
       5: C:\Users\c00603587\Documents\GitHub\minio1\cmd\xl-storage.go:781:cmd.listVols()
       4: C:\Users\c00603587\Documents\GitHub\minio1\cmd\xl-storage.go:770:cmd.(*xlStorage).ListVols()
       3: C:\Users\c00603587\Documents\GitHub\minio1\cmd\xl-storage-disk-id-check.go:283:cmd.(*xlStorageDiskIDCheck).ListVols()
       2: C:\Users\c00603587\Documents\GitHub\minio1\cmd\erasure-healing.go:237:cmd.listAllBuckets.func1()
       1: C:\Users\c00603587\Documents\GitHub\minio1\internal\sync\errgroup\errgroup.go:123:errgroup.(*Group).Go.func1()
## Expected Behavior

minio works fine , 

## Context
![image](https://user-images.githubusercontent.com/10794822/229453201-43f34feb-112e-4815-a63e-dab01ee26d9b.png)

error may happend here : os_windows.go . lines 133, 

I am not familiar with golang， but i guess bug happen here .   read failed.

## Your Environment
C:\Users\c00603587\Documents\GitHub\minio1>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOCACHE=C:\Users\c00603587\AppData\Local\go-build
set GOENV=C:\Users\c00603587\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Go\lib\pkg\mod
set GONOPROXY=
set GONOSUMDB=*
set GOOS=windows
set GOPATH=C:\Go\lib
set GOPRIVATE=
set GOPROXY=https://***********************/goproxy/
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\c00603587\Documents\GitHub\minio1\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessag
e-length=0 -fdebug-prefix-map=C:\Users\C00603~1\AppData\Local\Temp\go-build2172170082=/tmp/
go-build -gno-record-gcc-switches

**Comment by harshavardhana** [comment]
Thanks for the report, we know the issue - the fix is part of https://github.com/minio/minio/pull/16942

**Comment by chenshi5012** [comment]
> Thanks for the report, we know the issue - the fix is part of #16942

i check your pr ， i suggest  communicate  with @harshavardhana ，to make sure :that won't cause any other problems

**Comment by chenshi5012** [comment]
> > Thanks for the report, we know the issue - the fix is part of #16942
> 
> i check your pr ， i suggest communicate with @harshavardhana ，to make sure :that won't cause any other problems

oops， it  is you .
