### ISSUE TITLE
Unable to login through Console UI with latest image  RELEASE.2023-03-24T21-41-23Z 

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#16957]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Trying to login through Console UI fails with 

```
Expected element type <AssumeRoleResponse> but have <ErrorResponse>
```

## Expected Behavior

Successful login

## Current Behavior

Unable to login. Seems like a regression, it was working well in Dec 2022 MinIO image.

## Steps to Reproduce (for bugs)

1. Install the latest minio image in k8s cluster using minio-operator
2. Try login through Console UI

## Context

Using traefik ingress

## Regression

Yes

## Your Environment

* Version used (`minio --version`): RELEASE.2023-03-24T21-41-23Z
* Server setup and configuration: k8s 1.24
* Operating System and version (`uname -a`): Linux

**Comment by maulindesai** [comment]
@mshanmu i am also face same issue. following are logs of console 

> E: 2023/04/04 10:41:56 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
Serving operator at http://[::]:9090
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value

cert error are solved after removing --certs-dir option from command. but still session token invalid character persist. 

---
**Solved in Version 5.0.2**
Tested after updated latest operator image

**Comment by maulindesai** [comment]
Solved in Version 5.0.2

**Comment by mshanmu** [comment]
@maulindesai , Thanks for the information, but the issue you are talking about was for operator console and the issue I am talking about involves the MinIO console which comes with the minio image.

**Comment by mshanmu** [comment]
Additionally, I don't see any log messages in minio pods.

**Comment by harshavardhana** [comment]
@mshanmu can you show what is your server configuration? Including all environment variables..

**Comment by mshanmu** [comment]
Sorry @harshavardhana , it is a false alarm. I am able to login now. It is possible I might have input wrong credentials.

**Comment by mshanmu** [comment]
Also, With https://github.com/minio/console/pull/2754 PR, the error message will be clearer.
