### ISSUE TITLE
Helm Chart: Allow full configuration of SecurityContext for container and pod

### ISSUE THREAD

**Issue by djessich** [minio/minio#16978]
**Is your feature request related to a problem? Please describe.**
Created deployment with minio/minio Helm chart is insecure.

As best practice a pod should have a valid security context in place. E.g. a pod should never run as root or should never have a read only root filesystem unless required by the pod.

Scanning the created Helm deployment with Datree (or similar tools) shows that the security context is not prepared for the resulting pods leading to an insecure deployment. See following analysis results:

![Screenshot from 2023-04-05 16-42-28](https://user-images.githubusercontent.com/7459639/230116424-f153b89a-8805-4ae2-bdec-7b2429875e9b.png)

![Screenshot from 2023-04-05 16-42-00](https://user-images.githubusercontent.com/7459639/230116613-11e3c446-48f5-4c94-af51-83f3a3e75a17.png)

**Describe the solution you'd like**
Allow configuration of `securityContext` for container(s) and `podSecurityContext` for pod(s).

**Describe alternatives you've considered**
Currently this is not fully possible, only running user can be changed using security context. A patch for the Helm chart is required.

**Additional context**
K3S v1.24.11

**Comment by harshavardhana** [comment]
vanilla helm chart is not maintained by us, we have no way to test this. feel free to work on a fix and send it.

Closing this issue as non-actionable on us.
