### ISSUE TITLE
~1 second lag from new file creation to available reading operation?

### ISSUE THREAD

**Issue by keypointt** [minio/minio#17005]
## NOTE
Hi MinIO maintainers, 

what is the max possible lag between putting a new file and it being available for read?

I have below senario:
* new file creation in MinIO - timestamp: `2023-04-07T20:00:23.838Z`
* application reading file with error log on file not existing - timestamp:        `2023-04-07 20:01:34,996`

I'm using `sidekick` and all write/read requests are to the sidekick url.

And for MinIo cluster/server side setup, it is using `Erasure Coding` mechanism. Where each object is split into data shards and parity shards, which are distributed across the cluster. 
And this cluster has 6 hosts.

So there is ~1 second lag from new file creation to available reading operation?
Is it recommended to sleep for couple seconds between adding a new file and reading this newly added file?

Maybe this is a fake bug and just by design, and please feel free to close this issue if it's not valid.
Thank you!

## Expected Behavior
Read a new file right after adding it as new, and this file should just be available immediately.

## Current Behavior
Seems there is a lag to reach full sync and full availability across all MinIO cluster hosts.

## Possible Solution
sleep for couple seconds between adding a new file and reading this newly added file

## Regression
N/A

## Your Environment

* Version used (`minio --version`): RELEASE.2022-07-24T02-25-13Z
* Server setup and configuration: sidekick, Erasure Coding, cluster has 6 hosts
* Operating System and version (`uname -a`): Linux xinUbuntu 5.15.56-051556-generic #202207212102 SMP Thu Jul 21 21:37:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@keypointt please upgrade your setup before opening issues.

**Comment by harshavardhana** [comment]
> Seems there is a lag to reach full sync and full availability across all MinIO cluster hosts.

There will be no lag unless your backend disks have lag, all write in O_DIRECT with fdatasync() at the end. All these calls are synchronous. So unless your backend disk is faking it, there should be no delay whatsoever.

We test this on a daily basis, so I don't think this is actually a valid issue. What you are reporting seems to be some kind of a setup issue.

**Comment by keypointt** [comment]
Thank you! Then this is a fake issue, I'll close it.
