### ISSUE TITLE
Auto Extraction of Tar Archive bigger than ~5Mb does not work and does not end with a procedure error

### ISSUE THREAD

**Issue by kkochanski** [minio/minio#17033]
While using MinIO's Java SDK to submit a Tar Archive for auto-extraction, MinIO does not extract the Tar, but instead it saves it on the disc and returns successful response. That behaviour occurs only for Tar Archives bigger than ~5Mb. 

## Expected Behavior
- Regardless of archive size, they should be extracted.

## Current Behavior
- Archives smaller than ~5Mb are properly auto-extracted,
- Archives bigger than ~5MB are not auto-extracted and they're saved on the disc instead,
- In both cases, error is not returned.

## Steps to Reproduce (for bugs)

1. Create an archive bigger than 5Mb,
2. Use code snippet below (it's based on `io.minio:minio:8.5.2` MinIO Java SDK),

```
var client = MinioClient.builder()
    .endpoint("<endpoint>")
    .credentials("<key>", "<secret>")
    .build();

client.uploadObject(
    UploadObjectArgs.builder()
        .bucket("<bucket>")
        .object("dummy-value") // Cannot be empty, though in the end, it is still ignored by minio
        .userMetadata(Map.of(
            "snowball-auto-extract", "true"
        ))
        .filename(source)
        .build()
);
```
3. When archive is bigger than ~5Mb, then it will stored at MinIO under the name given in `.object()` method. In that case, `dummy-value`. 

## Context
That error does not occur when submitting archive using MinIO CLI tool. Code snippet below.
```
mc --version
cminio version RELEASE.2022-09-16T09-16-47Z (commit-id=ad4441ef2b4b1d0a6b90b5dd0d71d0423952e417)
Runtime: go1.18.6 darwin/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

mc cp /my/path/archive.tar.gz alias/bucket --attr "X-Amz-Meta-Snowball-Auto-Extract=true"
```

## Your Environment
- Java 
```
openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.3.6.1 (build 17.0.3+6-LTS, mixed mode, sharing)
```
- MinIO Server
```
minio version RELEASE.2023-02-27T18-10-45Z (commit-id=0ff931dc765d5d8fdddcdf7687fec1b0b194fca9)
Runtime: go1.19.6 darwin/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
- MinIO SDK
```
io.minio:minio:8.5.2
```
- Operating System and Version (The same behaviour we're experiencing at Linux machines)
```
Darwin ML-C02F817MMD6V 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
```

**Comment by klauspost** [comment]
You must disable multipart uploads. You omitted that in `mc cp`.

**Comment by kkochanski** [comment]
@klauspost While using `mc`, the existence of `--disable-multipart ` does not change anything.  In other words, whether `multipart` has been disabled or not `mc` uploads and auto-extract correctly (Tested on 7Mb archive). 

The issue is about the Java code and driver. 

I examined the SDK code. While using `uploadObject` method, the under-the-hood code is determining the upload approach while basing on size (5Mb plus - multipart upload) and there is no option to change it - unless trying to extend/overwrite some methods. 

As the final conclusion I would assume that for tar auto-extraction method `uploadObject` should not be used (if the issue is really related to multipart, though while using `mc` it does not change anything) and instead  users should use `uploadSnowballObjects`.

**Comment by klauspost** [comment]
@kkochanski I am not too intimate with the java sdk. 

You are welcome to [ask for a feature](https://github.com/minio/minio-java/issues) on the SDK to control when multipart upload is used.
