### ISSUE TITLE
Not work multi level tier

### ISSUE THREAD

**Issue by lxShaDoWxl** [minio/minio#17047]
Hi! 
Exists 3 minio
minio-1 
minio-2
minio-3

Rules IML in minio-1
1) --transition-days 0 --transition-tier "minio-2"  --tags "move_to_storage=minio-2"
2) --transition-days 0 --transition-tier "minio-3"  --tags "move_to_storage=minio-3"

When adding the "move_to_storage=minio-2" tag to the "test.png" object, then it is transferred to "minio-2", and if after the transfer you add the "move_to_storage=minio-3" tag, then it is not transferred to "minio-3"

## Expected Behavior
move to next tier

## Current Behavior
ignore move to next tier

## Possible Solution
maybe replace  check TransitionComplete to  TransitionComplete & "Storage-Class", and accept transition to next tier

## Context
I am developing an "Intelligent Tiering", because of the current logic, it turns out to be expensive to do more than 2 levels. At level above 2, you have to download the file and put it back at level 1.

## Regression
No

## Your Environment
minio version RELEASE.2023-04-13T03-08-07Z (commit-id=a42650c065fe22c6a6d3ce526d80c5354d4bceac)
docker container

**Comment by harshavardhana** [comment]
This is not supported on purpose and not part of the design yet.
