### ISSUE TITLE
Storage resources are insufficient for the write operation .minio.sys/buckets/.usage-cache.bin

### ISSUE THREAD

**Issue by chetom** [minio/minio#17040]
## General Summary

Fresh installation ( RELEASE.2023-04-13T03-08-07Z (go1.20.3 linux/amd64).

Minio keeps logging errors: 
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/.usage-cache.bin (cmd.InsufficientWriteQuorum)
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/mlodytest/.usage-cache.bin (cmd.InsufficientWriteQuorum)

I don't know how this affects the data.
Tests allow you to upload and download data.

## Expected Behavior

No errors in the system logs.
systemctl status minio.service

## Current Behavior

keep getting the following errors in the system logs:

Apr 14 16:04:52 srvbil01fs02 minio[14480]: API: SYSTEM()
Apr 14 16:04:52 srvbil01fs02 minio[14480]: Time: 14:04:52 UTC 04/14/2023
Apr 14 16:04:52 srvbil01fs02 minio[14480]: DeploymentID: 11823c2a-fde9-4580-a28a-89dc0e91fd09
Apr 14 16:04:52 srvbil01fs02 minio[14480]: Error: Write failed. Insufficient number of drives online (*errors.errorString)
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        5: internal/logger/logger.go:258:logger.LogIf()
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        4: cmd/erasure-object.go:1271:cmd.erasureObjects.putObject()
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        3: cmd/erasure-object.go:954:cmd.erasureObjects.PutObject()
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        2: cmd/data-usage-cache.go:957:cmd.(*dataUsageCache).save()
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        1: cmd/erasure.go:534:cmd.erasureObjects.nsScanner.func3()
Apr 14 16:04:52 srvbil01fs02 minio[14480]: API: SYSTEM()
Apr 14 16:04:52 srvbil01fs02 minio[14480]: Time: 14:04:52 UTC 04/14/2023
Apr 14 16:04:52 srvbil01fs02 minio[14480]: DeploymentID: 11823c2a-fde9-4580-a28a-89dc0e91fd09
Apr 14 16:04:52 srvbil01fs02 minio[14480]: Error: Storage resources are insufficient for the write operation .minio.sys/buckets/mlodytest/.usage-cache.bin (cmd.InsufficientWriteQuorum)
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        2: internal/logger/logger.go:258:logger.LogIf()
Apr 14 16:04:52 srvbil01fs02 minio[14480]:        1: cmd/erasure.go:534:cmd.erasureObjects.nsScanner.func3()
Apr 14 16:36:50 srvbil01fs02 minio[14480]: API: SYSTEM()
Apr 14 16:36:50 srvbil01fs02 minio[14480]: Time: 14:36:50 UTC 04/14/2023
Apr 14 16:36:50 srvbil01fs02 minio[14480]: DeploymentID: 11823c2a-fde9-4580-a28a-89dc0e91fd09
Apr 14 16:36:50 srvbil01fs02 minio[14480]: Error: Storage resources are insufficient for the write operation .minio.sys/buckets/.usage-cache.bin (cmd.InsufficientWriteQuorum)
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        2: internal/logger/logger.go:258:logger.LogIf()
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        1: cmd/erasure.go:428:cmd.erasureObjects.nsScanner.func1()
Apr 14 16:36:50 srvbil01fs02 minio[14480]: API: SYSTEM()
Apr 14 16:36:50 srvbil01fs02 minio[14480]: Time: 14:36:50 UTC 04/14/2023
Apr 14 16:36:50 srvbil01fs02 minio[14480]: DeploymentID: 11823c2a-fde9-4580-a28a-89dc0e91fd09
Apr 14 16:36:50 srvbil01fs02 minio[14480]: Error: Write failed. Insufficient number of drives online (*errors.errorString)
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        5: internal/logger/logger.go:258:logger.LogIf()
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        4: cmd/erasure-object.go:1271:cmd.erasureObjects.putObject()
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        3: cmd/erasure-object.go:954:cmd.erasureObjects.PutObject()
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        2: cmd/data-usage-cache.go:957:cmd.(*dataUsageCache).save()
Apr 14 16:36:50 srvbil01fs02 minio[14480]:        1: cmd/erasure.go:534:cmd.erasureObjects.nsScanner.func3()

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. install minio
2. create bucket
3. upload data

## Context

N/A

## Regression

N/A

## Your Environment

* Version used (`minio --version`):
Version: RELEASE.2023-04-13T03-08-07Z (go1.20.3 linux/amd64)

* Server setup and configuration:
1. Multi-Node Multi-Drive
2. _**mc admin info minio**_ 

- 
- srvbil01fs01:9000
-    Uptime: 1 hour
-    Version: 2023-04-13T03:08:07Z
-    Network: 5/5 OK
-    Drives: 60/60 OK
-    Pool: 1
- srvbil01fs02:9000
-    Uptime: 1 hour
-    Version: 2023-04-13T03:08:07Z
-    Network: 5/5 OK
-    Drives: 60/60 OK
-    Pool: 1
- srvbil01fs03:9000
-    Uptime: 1 hour
-    Version: 2023-04-13T03:08:07Z
-    Network: 5/5 OK
-    Drives: 60/60 OK
-    Pool: 1
- srvbil01fs04:9000
-    Uptime: 1 hour
-    Version: 2023-04-13T03:08:07Z
-    Network: 5/5 OK
-    Drives: 60/60 OK
-    Pool: 1
- srvbil01fs05:9000
-    Uptime: 1 hour
-    Version: 2023-04-13T03:08:07Z
-    Network: 5/5 OK
-    Drives: 60/60 OK
-    Pool: 1
- Pools:
-    1st, Erasure sets: 20, Drives per erasure set: 15
- 163 GiB Used, 1 Bucket, 6 Objects
- 300 drives online, 0 drives offline

 **_mc admin info --json minio | jq .info.backend_**
{
  "backendType": "Erasure",
  "offlineDisks": 0,
  "onlineDisks": 300,
  "rrSCParity": 1,
  "standardSCParity": 2
}

* Operating System and version (`uname -a`):
Ubuntu 22.04 LTS, 
Linux srvbil01fs01 5.15.0-69-generic  x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Your drives may experience intermittent errors, or there may be permission errors or similar preventing the writes to go through. Since all are on different objects it is unlikely that it is a corruption issue. 

All of these files are not critical, and can be recreated after these failures, but it could indicate a problem with your setup.

For a cluster this size you should look into our [subscription offers](https://min.io/pricing), where we can do a more detailed analysis of your cluster.

**Comment by chetom** [comment]
Thank you @klauspost 

Some more information:

Exactly those errors appear even when there is no input/output traffic. only on one of the nodes.
With a frequency of every 1 minute. 

I don't have disk errors in the logs. (checked with smartctl)
I have the right minio-user permissions for directories 
3) what is interesting to me is the number of "buckets/.usage-cache.bin/xl.meta" files is not identical on all nodes. not sure if it's ok.

_root@srvbil01fs01:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc
     **60     540    7071**

root@srvbil01fs02:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc
     **60     540    7071**

root@srvbil01fs03:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc
     **60     540    7071**

root@srvbil01fs04:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc
     **12     108    1413**

root@srvbil01fs05:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc
     **12     108    1413**_

**Comment by harshavardhana** [comment]
> _root@srvbil01fs01:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc **60 540 7071**
> 
> root@srvbil01fs02:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc **60 540 7071**
> 
> root@srvbil01fs03:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc **60 540 7071**
> 
> root@srvbil01fs04:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc **12 108 1413**
> 
> root@srvbil01fs05:/miniostorage# find . | xargs ls -ld | grep "buckets/.usage-cache.bin/xl.meta" | wc **12 108 1413**_

it won't be identical, it is not expected to be identical.

**Comment by chetom** [comment]
@harshavardhana thanks for explanation

**Comment by chetom** [comment]
The previous answer clarified some points but it doesn't solve my problem. I still get these types of errors.

**Comment by harshavardhana** [comment]
> The previous answer clarified some points but it doesn't solve my problem. I still get these types of errors.

It's because your system is unstable at various intervals.

**Comment by chetom** [comment]
- no disk errors (error/fail/asc/ascq)
- no network problems no rx/tx drop/error
- cpu load < 1
- lots of free ram
- system is responsive

1) Errors appear every 30 seconds (regularly) non-stop only on one node - for each bucket. Is it a master node? after an upgrade the errors are logged on a different node.
2) Every time a new bucket is created. i am getting exactly the same error for it again and again.
3) regardless of whether the system is under load or absolutely doing nothing.

I've recently uploaded of 140TB. passed without problems.
Only those errors.

**Comment by harshavardhana** [comment]
Can you generate the inspection output for these files? You copy them out of all the nodes if needed and share it here.

It looks like some quorum is missing.

**Comment by chetom** [comment]
A)

Two inspect files are attached (for .minio.sys/buckets/.usage-cache.bin 
and .minio.sys/buckets/.usage-cache.bin/xl.meta)


For that path following error is generated (every minute):

Error: Storage resources are insufficient for the write 
operation.minio.sys/buckets/.usage-cache.bin (cmd.InsufficientWriteQuorum)

.....

cmd/erasure.go:420:cmd.erasureObjects.nsScanner.*func1()*


B)

For path .minio.sys/buckets/XXXXXXXXXX/.usage-cache.bin (inspect file 
not attached) where XXXXX - bucket name

For that path following error is generated (less regularly):

Error: Storage resources are insufficient for the write operation 
.minio.sys/buckets/XXXXXXXX/.usage-cache.bin (cmd.InsufficientWriteQuorum)

......

cmd/erasure.go:534:cmd.erasureObjects.nsScanner.*func3()*


[inspect-data.zip](https://github.com/minio/minio/files/11497086/inspect-data.zip)

**Comment by harshavardhana** [comment]
@chetom you can delete this file and it will be regenerated. For me it looks like the file doesn't have quorum for some reason.

**Comment by chetom** [comment]
@harshavardhana  ok, do you mean to remove that directory .usage-cache.bin  on all nodes on all disks?
Should I stop the minio service first?

**Comment by harshavardhana** [comment]
> @harshavardhana ok, do you mean to remove that directory .usage-cache.bin on all nodes on all disks?
> Should I stop the minio service first?

No you don't need to stop, you can at once remove that file. It will be re-generated.

**Comment by chetom** [comment]
@harshavardhana I appreciate your help

I've removed .usage-cache.bin from .minio.sys/buckets/ on all nodes/disks.
First thoughts
a) There are still same errors. 
b) .usage-cache.bin directories have started to be created only on nodes 1-3 not on 4-5 (even after 10 minutes)
I understand that's how it's supposed to be, but I am trying to map the state of the system.


Is there any minimal configuration required for these files to provide redundancy/EC for those files?
