### ISSUE TITLE
Cannot set Content-Type with PutObjectsSnowball(...)

### ISSUE THREAD

**Issue by DmitriyVTitov** [minio/minio#17041]
I use `PutObjectsSnowball()` to upload multiple files but cannot set Content-Type. My code looks like this:
```
s.client.PutObjectsSnowball(
		ctx,
		options.Bucket,
		minio.SnowballOptions{
			Opts: minio.PutObjectOptions{ContentType: "image/jpeg"},
		},
		objCh,
	)
```

This code does not work despite I set right CT in options. Minio console shows my files are `Content-Type
application/octet-stream`.

Here is a debugger screenshot:
![image](https://user-images.githubusercontent.com/38575605/232403924-4fb8a286-5c4e-46b0-b1e2-56a57db81245.png)
I followed execution trace up to http.Do() and options are passed correctly all the way so I think the problem is on server side.

**Comment by klauspost** [comment]
Added PR #17042 with proposed fix.
