### ISSUE TITLE
Failed to access the minio file!

### ISSUE THREAD

**Issue by yuluo-yx** [minio/minio#17053]
### env
centos7，docker-compose，chrome

### des
The minio service was successfully deployed using docker, 
![image](https://user-images.githubusercontent.com/77964041/233242892-48179ff1-9305-49cb-a44e-b8856cf40a7d.png)
Photo uploading test succeeded
![image](https://user-images.githubusercontent.com/77964041/233242949-d6a6a301-0920-4b94-bb1d-628e26241617.png)
Click the share button next to it to get the link to the image
![image](https://user-images.githubusercontent.com/77964041/233243038-be58f1a6-fd8f-4187-8053-dfec763c4d16.png)
The link was copied into the browser and cannot be accessed properly
![image](https://user-images.githubusercontent.com/77964041/233243259-06c48cb1-1a22-4230-afa7-3e61695a96ec.png)

Any idea?

**Comment by harshavardhana** [comment]
> ![image](https://user-images.githubusercontent.com/77964041/233243259-06c48cb1-1a22-4230-afa7-3e61695a96ec.png)
> 
> Any idea?

This is because looks like you changed the hostname in the URL, and it won't work.
