### ISSUE TITLE
Access Policy: Setting policy of subdirectory in bucket

### ISSUE THREAD

**Issue by mkash32** [minio/minio#1705]
When we are setting an access policy for a prefix of a directory within a bucket, the trailing '/' is causing a difference in the permissions.
For example,

```
$ mc access readonly myminio/mybucket/mydir`
Access permission for ‘myminio/mybucket/mydir’ is set to ‘readonly’
$ mc access myminio/mybucket/mydir
Access permission for ‘myminio/mybucket/mydir’ is set to ‘readonly’
$ mc access myminio/mybucket/mydir/
Access permission for ‘myminio/mybucket/mydir/’ is set to ‘none’
```

It is not being treated as a directory without the trailing /.

When we are setting the access policy for a bucket there is no distinction between a trailiing / and without it is correctly assumed as a directory.

**Comment by harshavardhana** [comment]
// cc @hackintoshrao - can you take a look - looks like a regex issue?

**Comment by hackintoshrao** [comment]
@harshavardhana : Will investigate more tomorrow.

**Comment by harshavardhana** [comment]
Is this fixed @hackintoshrao @mkash32 ?

**Comment by hackintoshrao** [comment]
@harshavardhana : @mkash32  is on it. Should be pushing a fix today.

**Comment by mkash32** [comment]
@harshavardhana This is actually an issue in minio-go, I'll move this issue over there.
