### ISSUE TITLE
Orphaned access keys with OpenID Connect

### ISSUE THREAD

**Issue by Scapal** [minio/minio#17064]
There was a change in our OpenID connect provider base URL after we upgraded Keycloak. They dropped the "/auth" prefix.
After correcting the URL in MinIO OpenID configuration, it worked again, as expected.

The issue we now have, is that I don't see my Access Keys anymore as if I was another user.
The old Access Keys are still working but I have no way to manage them.

Also, we could not find a way to list all OpenID user access keys. That could prove useful to be able to delete them if they are compromised or if the user left the company.

## Your Environment
Version: 2023-04-20T17:56:55Z

**Comment by harshavardhana** [comment]
> The issue we now have, is that I don't see my Access Keys anymore as if I was another user. The old Access Keys are still working but I have no way to manage them.
> 
> Also, we could not find a way to list all OpenID user access keys. That could prove useful to be able to delete them if they are compromised or if the user left the company.

if you configure userinfo endpoint and allow it they will be purged automatically. If you change fundamental things in OpenID they won't be known to MinIO so we can't act upon such changes.

```
docs/sts/web-identity.md:MINIO_IDENTITY_OPENID_CLAIM_USERINFO        (on|off)    Enable fetching claims from UserInfo Endpoint for authenticated user
```

Currently there is no way to list them though.

**Comment by vfauth** [comment]
> Currently there is no way to list them though.

Could that information be put in the documentation maybe? @harshavardhana
