### ISSUE TITLE
minio helm chart is not able to create buckets if we define bucket information in the values.yaml file in k3s cluster.

### ISSUE THREAD

**Issue by KRISHNA-VKS** [minio/minio#17068]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am running K3s cluster in my windows 10 Hyper V VM with ubuntu 22.04 OS. I wanted the helm chart to create a default bucket after the  helm deployment. I do see a configuration option and applied the below change in the values.yaml file.

buckets:
   - name: bucket2
     policy: none
     purge: false
     versioning: false
     objectlocking: false

I deployed the helm chart using the updated yaml file like this in the k3s environment

helm install --generate-name minio/minio -n infra-ns -f ./minio-upgrade-values.yaml --set mode="standalone" --kubeconfig='/etc/rancher/k3s/k3s.yaml'

The helm chart installation keep on failing.

Alternative path of --set individual values working fine. But i have lot of changes in the values.yaml file and doesn't want to pass each values using --set parameter.

## Expected Behavior
helm chart should be deployed successfully without any issues.

## Current Behavior
helm chart deployment fails.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio = 5.0.7
OS = Ubuntu 22.04.2
Kubernetes = k3s
kubectl version = 1.25

**Comment by harshavardhana** [comment]
vanilla helm chart is not maintained by us, we have no way to test this. feel free to work on a fix and send it.

Closing this issue as non-actionable on us.
