### ISSUE TITLE
Minio not waiting for Certificates. Starting in non secure mode directly

### ISSUE THREAD

**Issue by sathyendranv** [minio/minio#17088]
**Version: RELEASE.2020-12-12T08-39-07Z**

Am using container minio/minio of above version and trying to use minio with TLS certificates (Self Signed). Our Service are generating the Certificates and typical minio is not waiting for the certificates to be in path. Want to force Minio to use TLS/wait until the TLS Certificates.

Mounting the tls certificate as volume mount
    - <path_to_server_certificate.pem>:/root/.minio/certs/public.crt
    - <path_to_server_key.pem>:/root/.minio/certs/private.key
## Expected Behavior
Start minio in Secured mode/Wait on TLS Certificate

## Current Behavior
Container is starting in non secured mode. 

## Possible Solution
Force the container to use TLS with config files. 

## Steps to Reproduce (for bugs)
1. Provide the volume mount paths
2. Don't provide the certificates 
3. 
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-12-12T08-39-07Z
* Server setup and configuration: Xeon 8th Gen, 16GB Ram
* Operating System and version (`uname -a`): Ubuntu 20.04, Docker version 23.0.4

**Comment by harshavardhana** [comment]
Please upgrade @sathyendranv you are using a release that is 3yrs old.
