### ISSUE TITLE
modifying prometheus auth type via  mc admin config set

### ISSUE THREAD

**Issue by ghorofamike** [minio/minio#17083]
It appears that in the documentation, when  one has set up minio via the operator,  its unclear how to change the  variable ```MINIO_PROMETHEUS_AUTH_TYPE```, 
## Expected Behavior
i would expect prometheus would appear somewhere in  this list of options: 
```bash
$ mc admin config set  alias   --env  
KEYS:
subnet                register the cluster to MinIO SUBNET   
callhome              enable callhome to MinIO SUBNET
site                  label the server and its location
api                   manage global HTTP API call specific features, such as throttling, authentication types, etc.
...  
```

i suggest possibly adding the option to modify this environment variable: 
```bash
$ mc admin config set  alias   --env   
KEYS:
subnet                register the cluster to MinIO SUBNET   
callhome              enable callhome to MinIO SUBNET
...
prometheus         change the prometheus metrics endpoint auth type
...
```

## Current Behavior
Currently it appears i can not change this variable via  ``` mc admin config set  alias```

## Possible Solution
It should be possible to change with something of the sort: 
```bash
mc admin config set  alias  prometheus   MINIO_PROMETHEUS_AUTH_TYPE=public   
```

## Your Environment

* Version used (`minio --version`):  ``` minio/minio:RELEASE.2023-04-20T17-56-55Z ``` (minio image), ``` minio/operator:v5.0.4```  sidecar.
* Server setup and configuration:  ```Ks8,  GitVersion:"v1.27.1"``` 
* Operating System and version (`uname -a`):
```Fedora 38, 6.2.12-300.fc38 ```

**Comment by harshavardhana** [comment]
That is not possible @ghorofamike the reason is that this is handler (registration) level implementation - you can't change it dynamically once the server is up.

Just change it as necessary during the deployment phase.

**Comment by ghorofamike** [comment]
> Just change it as necessary during the deployment phase.

How is that done using helm?
