### ISSUE TITLE
Documentation: reverse proxying with NGINX needs proxy_cache_convert_head off

### ISSUE THREAD

**Issue by spomata** [minio/minio#17092]
## Expected Behavior

Reverse proxying example configuration in the docs should include the option:
```
proxy_cache_convert_head off;
```

## Current Behavior

Without this option, I haven't been able to perform any file retrieval from MinIO buckets on my setup.
A "mc admin trace" before and after setting the option pointed me in the right direction: without the explicit declaration, HEAD requests would be converted to GET and fail with 403 - forbidden.

## Possible Solution

Improving documentation to help prospective users.

## Context

Setting up a MinIO SNSD development environment on RHEL 7 behind a NGINX reverse proxy.

## Regression

No

## Your Environment

* Version used (`minio --version`):
* RELEASE.2023-04-20T17-56-55Z
* Server setup and configuration:
RPM install
* Operating System and version (`uname -a`):
RHEL 7
`Linux host 5.4.225-1.el7.elrepo.x86_64 #1 SMP Fri Nov 25 11:40:22 EST 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> A "mc admin trace" before and after setting the option pointed me in the right direction: without the explicit declaration, HEAD requests would be converted to GET and fail with 403 - forbidden.

This is because you have NGINX caching enabled, this is not how by default NGINX behaves.

**Comment by spomata** [comment]
> > A "mc admin trace" before and after setting the option pointed me in the right direction: without the explicit declaration, HEAD requests would be converted to GET and fail with 403 - forbidden.
> 
> This is because you have NGINX caching enabled, this is not how by default NGINX behaves.

I doubt so, a grep of "proxy_cache" only yielded "proxy_cache off;" results.

Still, why not explicitly adding
```
proxy_cache off;
```
to the docs then?

**Comment by harshavardhana** [comment]
Please share your entire nginx.conf
