### ISSUE TITLE
Multipart: partnumber can not be more than 10000

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1709]
```
krishna@escape:~/tmp$ ./miniodebug --endpoint localhost:9000 --accesskey SXO8VW2OFKKP2OG7AC85 --secretkey CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 multipart upload --bucket testbucket --object testobject --uploadid 402bf5d9-3282-4915-93d1-83bc6654b5e4 --number 10001 --file /tmp/5mb                                                              
{10001 0001-01-01 00:00:00 +0000 UTC 5f363e0e58a95f06cbe9bbc662c5dfb6 5242880}
krishna@escape:~/tmp$ 
```

**Comment by harshavardhana** [comment]
@krishnasrinivas - let Akash know what needs to be done.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas update the timeline to fix this.

**Comment by krishnasrinivas** [comment]
`miniodebug --endpoint localhost:9000 --accesskey SXO8VW2OFKKP2OG7AC85 --secretkey CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 multipart new`

this gives you uploadID like `402bf5d9-3282-4915-93d1-83bc6654b5e4`

then do
`miniodebug --endpoint localhost:9000 --accesskey SXO8VW2OFKKP2OG7AC85 --secretkey CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 multipart upload --bucket testbucket --object testobject --uploadid 402bf5d9-3282-4915-93d1-83bc6654b5e4 --number 10001 --file /path/to/a/file`

This should give error, check the error `ErrInvalidMaxParts` in api-errors.go

**Comment by krishnasrinivas** [comment]
do `go get github.com/krishnasrinivas/miniodebug` to get the miniodebug binary

**Comment by mkash32** [comment]
#1730
