### ISSUE TITLE
browser: Object uploads file doesn't appear

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1710]

**Comment by harshavardhana** [comment]
![browser-upload-bug](https://cloud.githubusercontent.com/assets/622699/15445911/06461db0-1ec1-11e6-8bc2-8c4ea5aeeaec.png)

**Comment by GarimaKapoor** [comment]
Update the timeline to resolve this issue!

**Comment by harshavardhana** [comment]
Assigned to @krisis

**Comment by krishnasrinivas** [comment]
This bug is not reproducible, need more info @harshavardhana

**Comment by harshavardhana** [comment]
> This bug is not reproducible, need more info @harshavardhana

May be the latest changes have fixed a few things on XL - try once more with server on hq.minio.io and remotely uploading/accessing the file.
