### ISSUE TITLE
"file name too long" error for some files 

### ISSUE THREAD

**Issue by pyprism** [minio/minio#17106]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am using Minio from the plain Linux server (Ubuntu 22.04). For file upload operation, I am facing this error for some files, here is an example:
```
"We encountered an internal error, please try again.: cause(open /home/prism/prod/minio/data/<bucket name>/manabzamin/2023/4/27/সাউথ-এশিয়া-পারসপেক্টিভসএর-প্রতিবেদন-কঠোর-বার্তা-দিয়েছে-ওয়াশিংটন-গোটা-পৃথিবী-বাংলাদেশের-নির্বাচনের-দিকে-তাকিয়ে.webp/xl.meta: file name too long)"
```
and output of minio -- version
```
minio version RELEASE.2023-02-27T18-10-45Z (commit-id=0ff931dc765d5d8fdddcdf7687fec1b0b194fca9)
Runtime: go1.19.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
As the error says, the file name is too long for the filesystem to handle.

There is nothing we can do about that.
