### ISSUE TITLE
Error: Write failed. Insufficient number of disks online

### ISSUE THREAD

**Issue by summer908** [minio/minio#17125]
phenomenon： minio error, Write failed. Insufficient number of disks online
but, I see to the disk,
There's room for redundancy,the picture
![image](https://user-images.githubusercontent.com/102030092/236095586-60ae7d6b-dcc3-4b48-b6ed-956a9ec6ae71.png)
It was full before,I cleaned it up.
but ,
Request still reported error
for info,
system: centos7.6
minio image:  minio:RELEASE.2020-09-26T03-44-56Z
What should be don  for me

**Comment by harshavardhana** [comment]
@summer908 please upgrade your setup.

**Comment by summer908** [comment]
> Upgrade disk configuration?

**Comment by summer908** [comment]
I still have some doubts. I haven't solved them. Take a look

**Comment by summer908** [comment]
@harshavardhana
