### ISSUE TITLE
Not able to add webhook notification endpoint when another is offline

### ISSUE THREAD

**Issue by SBylemans** [minio/minio#17147]
## Expected Behavior
I should be able to add a new endpoint, regardless whether other endpoints are offline.

## Current Behavior
Trying to add via UI gives:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/5698858/236415636-6a2ed6cc-a17b-4292-b92d-c549f4d60d60.png">

And via minio client:
```
mc: <ERROR> Unable to set '<url>' to server: error (<endpoint-name>:webhook): not connected to target server/service.
```
where `endpoint-name` is different from the endpoint I'm trying to configure.

## Steps to Reproduce (for bugs)
1. Add webhook endpoint that is listening
2.Stop the listening server
3.Try to add another webhook endpoint, it fails

## Context
I'm trying to publish events to a NiFi cluster. I added a notification endpoint for every node, but I only want the primary node to process it. Seeing as the primary node of this cluster can change, I can't just add the endpoint for the primary node and be done with it. If the primary node changes, I don't want to reconfigure it. Only the primary node is online according to minio.

Another issue with this, is that I can't configure an endpoint that is offline. What does minio care if the endpoint is online or not? It knows whether the endpoint is online or not, so why not only send to online endpoints? It is not the problem of minio that the endpoint is online or not, you can warn the user. But if the user wants to preconfigure, it is not able to do so.

**Comment by SBylemans** [comment]
The issue is even worse, I'm not even able to delete a notification endpoint when one is offline...

**Comment by vadmeste** [comment]
@SBylemans what version of MinIO is this ?

**Comment by SBylemans** [comment]
@vadmeste RELEASE.2022-12-02T23-48-47Z

**Comment by harshavardhana** [comment]
> @vadmeste RELEASE.2022-12-02T23-48-47Z

@vadmeste please upgrade your setup

**Comment by SBylemans** [comment]
@harshavardhana We upgraded and now we can't see the notification endpoints in the GUI (we can see them using minio client). And we can't reset them because they are offline, I also can't add one because other ones are offline...

**Comment by Praveenrajmani** [comment]
You can just disable a notification target @SBylemans and can't remove it.

You can disable the existing target by `mc admin config set <alias> <targetname> enable=off`

**Comment by ldeschuyter** [comment]
Upgrade to 2023-05-04T21:44:30Z didn't resolve the issue. Now the "event destinations" are not longer visible.

They are still visible using the mc-client

**Comment by ldeschuyter** [comment]
@Praveenrajmani  disabling didn't work

**Comment by Praveenrajmani** [comment]
Disabling worked for me. I couldn't reproduce this in my end. 

What is the error that you see when trying to disable? Can you share it here?

**Comment by ldeschuyter** [comment]
@Praveenrajmani sure

```
mc admin config set local notify_webhook:nifi3-dsi enable=off
mc: <ERROR> Unable to set 'notify_webhook:nifi3-dsi enable=off' to server: error (nifi2-dsi:webhook): not connected to target server/service.

mc admin info local
●  localhost:9000
   Uptime: 7 hours
   Version: 2023-05-04T21:44:30Z
   Network: 1/1 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

158 GiB Used, 17 Buckets, 31,433 Objects, 26,295 Versions
1 drive online, 0 drives offline

```

**Comment by klauspost** [comment]
Disable the one that isn't working

**Comment by SBylemans** [comment]
@klauspost as said by @ldeschuyter , this was also not possible. When you have multiple webhooks that are offline, you cannot disable one because of the error described above.

**Comment by harshavardhana** [comment]
There are ways to fix it, we simply have to relax the strict validation on all targets // cc @Praveenrajmani
