### ISSUE TITLE
Manage button, and other buttons missing on MINIO console 

### ISSUE THREAD

**Issue by Al4DIN** [minio/minio#17149]
## Expected Behavior

We want to get  access to both Manage button and create bucket on the interface, or too simply just navigate through the minio console.

## Current Behavior

We can't browse the different buckets or try to create one
![image](https://user-images.githubusercontent.com/49256330/236511546-d9bec39d-9f5f-4d61-bebb-c16901479212.png)

## Steps to Reproduce (for bugs)

We deployed minio using the helm charts, and we are using an ingress Nginx gateway to have access to different minio UI's outside the cluster.

To fix this issue, we just refresh our page from 3 to 10 times or we can do the log out log in and it appears again, but couldn't track any bugs in the logs.

## Your Environment

* Version used  
minio-operator-version: v4.4.11
minio-operator-source: https://github.com/minio/operator
minio-tenant-version: 2022-03-03T21-21-16Z
minio-tenant-source: https://github.com/minio/minio
* Server setup and configuration:
Kubernetes cluster v1.25, tested on the v1.21 too and same issue

**Comment by harshavardhana** [comment]
Please upgrade to latest releases @Al4DIN

**Comment by Al4DIN** [comment]
Hello @harshavardhana, I did update the minio-console version to the last one `minio/console:v0.26.4` but I still face the same issue.
I can't upgrade the whole minio to a recent version since minio is one of the components of ou platform and the current used version is matching with other open sources tools and kubernetes version.

**Comment by harshavardhana** [comment]
> Hello @harshavardhana, I did update the minio-console version to the last one `minio/console:v0.26.4` but I still face the same issue. I can't upgrade the whole minio to a recent version since minio is one of the components of ou platform and the current used version is matching with other open sources tools and kubernetes version.

minio/console comes as part of MinIO - you shouldn't be running it separately. That is not supported.

**Comment by Al4DIN** [comment]
No I meant I only updated the console version and kept the other old versions for tenant and operator (trying to get a customized version) since I was thinking the issue is only related to the ui console, but I got your idea.
