### ISSUE TITLE
Support any OpenID Policy variable

### ISSUE THREAD

**Issue by ribeaud** [minio/minio#17145]
**Is your feature request related to a problem? Please describe.**
I think it would be nice to be able to specify _any_ policy variable name, and not to be limited to the list specified [here](https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#policy-variables). I do not understand this limitation by the way. Is it security relevant?

**Describe the solution you'd like**
In my concrete example, I am controlling the OIDC server. I can specify in the client configuration which claims should be sent to **MinIO** as part of the token.

In an ideal world, following policy could be used/defined:
```json
{
"Version": "2012-10-17",
"Statement": [
      {
         "Action": ["s3:ListBucket"],
         "Effect": "Allow",
         "Resource": ["arn:aws:s3:::${jwt:project}"],
         "Condition": {"StringLike": {"s3:prefix": ["${jwt:data_provider}/*"]}}
      },
      {
         "Action": [
         "s3:GetObject",
         "s3:PutObject"
         ],
         "Effect": "Allow",
         "Resource": ["arn:aws:s3:::${jws:project}/${jws:data_provider}/*"]
      }
   ]
}
```

**Describe alternatives you've considered**
The alternative is to strictly stick to the set of **jwt** namespace variables. So you will map _name_ to _data_provider_ but this feels like a hack in my case and does not fully reflect the reality.

**Comment by harshavardhana** [comment]
Policy conditions must be standard conditions, if you make it free-form anyone can mimic and spoof your conditions. 

We can alternatively take inputs asking for additional keys that are set by the user and we can use those to additionally replace and filter. 

This makes our policy JSON even more dynamic than what its already is, we would like to avoid such complexities in critical pieces in AuthZ. 

Current values relying on standard JWT spec are enough and cover most of the areas. Feel free to work on this and send a PR if you must we will take a look and review.

But this is currently out of scope.

**Comment by ribeaud** [comment]
Thanks for your answer which sounds reasonable to me. So, maybe, I am handling my use case the wrong way? 🤔 

Our policies are not based on _any_ of the predefined list, neither user's `preferred_username`, nor user's `website` or `phone_number` (what strange ones by the way...).

The closest one I could envisage is `jwt:groups` but I do not know how to use it. Is that an array? Or a simple string? I could not find any example in the documentation.

**Comment by ravindk89** [comment]
@ribeaud to clarify, what is your goal state here?  Are you trying to isolate users to specific prefixes or something similar?

w.r.t. `jwt:groups` that just depends on what you define upstream, IIRC. So with Keycloak if I map that claim to an array somehow, it would be an array. How exactly that would work depends on how you use it as a condition key.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html#reference_policies_multi-value-conditions-examples

AWS has some guidance here, but I've not tested something like that w/ MinIO.
