### ISSUE TITLE
listobjects may not return all objects for conflict object as parents (python3+boto3+listobjectsv2)

### ISSUE THREAD

**Issue by jt121dot5** [minio/minio#17151]
When a key represents an object as well being a component in another object's key, listobjects appears not to list them.

For example:
object with key = file1
object with key = file1/file2

Two objects exist in the bucket, but only file1 is reported in the list-objects results.

Examples below were reproduced using minio-client, but the original issue was discovered with custom code operating on S3 objects (python3 + boto3 + listobjectsv2)

## Expected Behavior (AWS)

% mc mb aws/bucket
Bucket created successfully `aws/bucket`.

% mc -q cp file1 aws/bucket/file1
`/tmp/file1` -> `aws/bucket/file1`
Total: 0 B, Transferred: 2 B, Speed: 10 B/s

% mc -q cp file2 aws/bucket/file1/file2
`/tmp/file2` -> `aws/bucket/file1/file2`
Total: 0 B, Transferred: 3 B, Speed: 12 B/s

% mc ls aws/bucket
***[2023-05-05 18:03:17 CDT]     2B STANDARD file1***
***[2023-05-05 18:03:38 CDT]     0B file1/***

% mc ls aws/bucket/file1/
[2023-05-05 18:03:29 CDT]     3B STANDARD file2

% mc ls aws/bucket/file1/file2
[2023-05-05 18:03:29 CDT]     3B STANDARD file2

## Current Behavior (minio)

% mc mb m92/bucket
Bucket created successfully `m92/bucket`.

% mc -q cp file1 m92/bucket/file1
`/tmp/file1` -> `m92/bucket/file1`
Total: 0 B, Transferred: 2 B, Speed: 178 B/s

% mc -q cp file2 m92/bucket/file1/file2
`/tmp/file2` -> `m92/bucket/file1/file2`
Total: 0 B, Transferred: 3 B, Speed: 281 B/s

% mc ls m92/bucket
***[2023-05-05 18:02:58 CDT]     2B STANDARD file1***

% mc ls m92/bucket/file1/
***(returns nothing)***
% mc ls m92/bucket/file1/file2
***(returns nothing)***

***And yet the object can be accessed:***
% mc -q cp m92/bucket/file1/file2  XX
`m92/bucket/file1/file2` -> `XX`
Total: 0 B, Transferred: 3 B, Speed: 229 B/s

## Regression

unknown

## Your Environment

linux     
was running: minio.RELEASE.2023-01-02T09-40-09Z
then to: minio.RELEASE.2023-05-04T21-44-30Z

**Comment by harshavardhana** [comment]
@jt121dot5 this is not supported in MinIO.

https://github.com/minio/minio/blob/master/docs/minio-limits.md#object-name-restrictions-on-minio

So it is behaving as designed.

**Comment by jt121dot5** [comment]
>So it is behaving as designed.

Yeah - I was wondering about that.

Any thoughts on supporting this?
Minio appears to be able to store and retrieve an object of issue, and so you're 2/3's of the way there already.  Store and retrieve sound like the more difficult parts to do too.  :-)

Thanks, -Jeff

**Comment by harshavardhana** [comment]
No we will not be able to support it.
