### ISSUE TITLE
Guarantee durability for all OS

### ISSUE THREAD

**Issue by pfreixes** [minio/minio#17165]
**Is your feature request related to a problem? Please describe.**
From my understanding durability is only guaranteed Today if an OS with support for O_DIRECT is used, since OS that do not have support use a regular OpenFile with final Close which will not guarantee that data in memory will be flushed, so in case of having a crash in the application data would be lost.

Consider the example of the `CreateFile` which uses the [following](https://github.com/minio/minio/blob/42fb3cd95e9c5bfbffd449cfce3cc594dab491bd/cmd/xl-storage.go#LL1883C1-L1889C17) lines of code for writing a file

**Describe the solution you'd like**
OS that do not support O_DIRECT should use either the O_SYNC flag or the `Sync` method for flushing the data from the cache.

**Comment by harshavardhana** [comment]
We do not support filesystems that do not support O_DIRECT - O_SYNC is useless actually from a performance point of view. 

If you have a filesystem that does not support O_DIRECT don't use it. Use something that is supported. 

Linux + XFS for production deployments, if you want to experiment go ahead and do it. We really don't want to waste our time doing O_SYNC in place of O_DIRECT.

**Comment by pfreixes** [comment]
I can understand that supporting `sync` might imply a performance degradation, but still some customers might prefer durability against throughput, so why not support a configuration where the `sync` could be turned on?

Also you might want to add a disclaimer here https://github.com/minio/minio/discussions/14339#discussioncomment-2200274

**Comment by klauspost** [comment]
@pfreixes We do not add features just to add features. This seems like a workaround for something that is already a bad idea.

We know the needs of our customers and have not had this come up.

**Comment by pfreixes** [comment]
Oks, so just for confirming in case of making usage of OS that do not support O_DIRECT `minio` can not guarantee durability of the objects stored, is that correct?

**Comment by harshavardhana** [comment]
> Oks, so just for confirming in case of making usage of OS that do not support O_DIRECT `minio` can not guarantee durability of the objects stored, is that correct?

Use a filesystem that supports O_DIRECT.
