### ISSUE TITLE
Query Status of Synchronous (Ative/Active) Replication - healthcheck-probe

### ISSUE THREAD

**Issue by cbfischer** [minio/minio#17163]
Hi,

**Would it be interesting to be able to query the replication status (unauthenticated) to identify whether the cluster is already synchronized. That way load balancer could release access to the cluster ONLY IF the data has already been synchronized, after came out of a cluster failure .**

Consider the following scenario:

1) The Cluster-01 goes offline.
2) The Cluster-02 flags the data that should be resynchronized for when Cluster-01 comes back online.
3) The load balancer identifies that the Cluster-01 is online again (/minio/health/cluster) and starts directing traffic to it. But files are still being synced from the Cluster-02.

If the user tries to read a file that is not yet in the Cluster-01, the file will not be found. Is my understanding correct?

https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html

**Comment by harshavardhana** [comment]
> If the user tries to read a file that is not yet in the Cluster-01, the file will not be found. Is my understanding correct?

MinIO automatically proxies the request and sends the data from cluster-02 so it is transparent.

**Comment by cbfischer** [comment]
> > If the user tries to read a file that is not yet in the Cluster-01, the file will not be found. Is my understanding correct?
> 
> MinIO automatically proxies the request and sends the data from cluster-02 so it is transparent.

Thanks a lot for the explanation. So you can ignore this replication health-check suggestion.

**Comment by poornas** [comment]
Closing issue - this is already addressed by proxying
