### ISSUE TITLE
Minio helm chart: Post Job fails when not running as root and tls enabled

### ISSUE THREAD

**Issue by mungo312** [minio/minio#17174]
When enabling the security contexts for the post run jobs and enabling tls, the jobs fail because it can not safe the configuration.

The issue is quite similar to #16758
It seams like the fix for the above issue intoduced with #17160 and #17148 is not working when tls is enabled.
When tls is enabled the needed certs are mounted to `/etc/minio/mc/certs`, because of this the folder mc is not writeable anymore for the non root user.  

## Expected Behavior
Job should finish

## Current Behavior
Job fails

## Possible Solution
Mount the emptyDir at `/etc/minio/mc` instead of `/etc/minio`

## Your Environment
Minio Helm Chart from Master

**Comment by harshavardhana** [comment]
vanilla helm chart is not maintained by us, we have no way to test this. feel free to work on a fix and send it.

Closing this issue as non-actionable on us.
