### ISSUE TITLE
not able to access AD enabled minIO API using minIO python client

### ISSUE THREAD

**Issue by debimishra89** [minio/minio#17181]
I have an AD enabled minio cluster with a load balancer. 
I am able to login to the console using AD credential.
However I am not able to access anything using minio python client.
```
from minio import Minio
from minio.error import S3Error

client = Minio(
        "dasec-lakehouse-minio.dastc.stee.com:9000",
        access_key="xxxx",  <AD username>
        secret_key="xxxxxxx"  <AD password>
    ) 
```

## Current Behavior
``S3Error: S3 operation failed; code: SignatureDoesNotMatch, message: The request signature we calculated does not match the signature you provided. Check your key and signing method., resource: /, request_id: 175E055C3682C3FA, host_id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
`

## Your Environment
* Version used (`minio --version`): 2023-04-28T18:11:17Z
* Operating System and version (`uname -a`): Ubuntu 20-04

**Comment by harshavardhana** [comment]
@debimishra89 you can't just pass your AD credentials to SDKs, you need to use AssumeRoleWithLDAPIdentity first to generate a temporary token.

https://github.com/minio/minio-py/blob/master/examples/minio_with_ldap_identity_provider.py
