### ISSUE TITLE
Is pip a real dependency of the project ?

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#172]
As I understood, pip is only needed to build mkdocs, so I think it is useless to check it in checkdeps.sh

**Comment by harshavardhana** [comment]
> As I understood, pip is only needed to build mkdocs, so I think it is useless to check it in checkdeps.sh

pip is necessary for mkdocs, checkdeps.sh is executed during the `make`  and so is `mkdocs` with `go generate` - so it is a valid check

**Comment by vadmeste** [comment]
yes, so the project doesn't depend directly on pip, right? I mean isn't it sufficient to check only the presence of mkdocs ? because I guess some people would prefer easy_install which is an alternative of pip..

**Comment by harshavardhana** [comment]
> yes, so the project doesn't depend directly on pip, right? I mean isn't it sufficient to check only the presence of mkdocs ? because I guess some people would prefer easy_install which is an alternative of pip..

You are correct.
