### ISSUE TITLE
XL: ListMultipart: Order of List for objects with Multiple UploadID's. - May 25th

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1720]
With unit tests not able to get a guarantee on the order of objects for `ListMultiparts`.

**Comment by krishnasrinivas** [comment]
@hackintoshrao can you provide more details? can you paste the unit test case for which it is failing?

**Comment by hackintoshrao** [comment]
@krishnasrinivas : Just saw this. This is to do with the comment here https://github.com/minio/minio/blob/master/object-common-multipart.go#L437 . 

```
// FIXME: Currently the code sorts based on keyName/upload-id which is
// in correct based on the S3 specs. According to s3 specs we are
// supposed to only lexically sort keyNames and then for keyNames with
// multiple upload ids should be sorted based on the initiated time.
// Currently this case is not handled.
```

This is not produced consistently since it depends on uuid of UploadID generated.

**Comment by GarimaKapoor** [comment]
Please update the timeline

**Comment by hackintoshrao** [comment]
For the test here https://gist.github.com/hackintoshrao/01fe4f9aff252fca94388eaf9395ebd4 , It failed once with error 

```
    object-api-multipart_test.go:493: Test 1: Metadata 1: Expected Metadata UploadID to be "ada6ab5d-039b-44c9-bd93-a37ab4ffca30", but instead found "88ec98ac-b11c-46dc-880a-be2f76fbf89d"
    object-api-multipart_test.go:493: Test 1: Metadata 2: Expected Metadata UploadID to be "b3e5dd1f-b29b-46d1-bcd4-bedc802e31a0", but instead found "ada6ab5d-039b-44c9-bd93-a37ab4ffca30"
```

But its not consistent.  It is just to do with the order of Result for objects with multiple uploadID's.

**Comment by hackintoshrao** [comment]
```
    object-api-multipart_test.go:494: Test 1: Metadata 1: Expected Metadata UploadID to be "c9138f14-b9a1-4e5c-b0b9-6af3f95cabf7", but instead found "6b3725f3-82a8-4109-8ffd-728ce28ad6ff"
    object-api-multipart_test.go:494: Test 1: Metadata 2: Expected Metadata UploadID to be "6b3725f3-82a8-4109-8ffd-728ce28ad6ff", but instead found "c9138f14-b9a1-4e5c-b0b9-6af3f95cabf7"

```

**Comment by hackintoshrao** [comment]
Sometimes there is more than order related issue, Incorrect result when maxKeys are set 

```
    object-api-multipart_test.go:494: Test 1: Metadata 1: Expected Metadata UploadID to be "b4a37d66-9493-4c01-9ced-d59d7296d331", but instead found "212d2514-3b06-4a10-8434-7a70ad17b95f"

```

**Comment by hackintoshrao** [comment]
One more test to catch the issue https://gist.github.com/hackintoshrao/30346d4be2d00fd8f39c1ef6ce332ebc .

**Comment by hackintoshrao** [comment]
fixed by commit https://github.com/minio/minio/commit/c705712939d8d58c4ae678961c666640544c37b2 from @krishnasrinivas  .
