### ISSUE TITLE
XL: ListMultipart: UploadID Marker entry not skipped. - May 25th

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1721]
When ListMultipart with UploadID Marker is called, the entry corresponding to the UploadID Marker is not skipped in the result.

**Comment by hackintoshrao** [comment]
You can run the test in following link to validate. https://gist.github.com/hackintoshrao/9af326123cfbce721ff771460fc1e855

**Comment by krishnasrinivas** [comment]
@hackintoshrao are you running the latest code because this was fixed two days back 5b95f097d4b24e6e49e44f95d05e1d5a9ce10270

**Comment by hackintoshrao** [comment]
@krishnasrinivas : I'm running from latest, can you try running the test??? 
`go test -run=TestListMultipartUploads`

**Comment by GarimaKapoor** [comment]
@harshavardhana, please update the timeline to fix this issue.

**Comment by hackintoshrao** [comment]
fixed by commit https://github.com/minio/minio/commit/c705712939d8d58c4ae678961c666640544c37b2 from @krishnasrinivas  .
