### ISSUE TITLE
The cluster is not writable when there are multiple pools

### ISSUE THREAD

**Issue by hjun881** [minio/minio#17227]
# bug
When a cluster has two pools and one and a half nodes in one pool are unavailable, the entire cluster will not be writable Another healthy pool should be written instead of the entire cluster being non writable

# resolvent
1. Automatically set to read-only when a pool is not writable, and all write requests are routed to a healthy pool
2.  Manually set the pool read-only, for example:`mc admin decommission readonly myminio`

**Comment by klauspost** [comment]
No. We cannot allow that, since it will lead to inconsistencies.

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/operations/concepts/availability-and-resiliency.html has more guidance on why this behavior exists.
