### ISSUE TITLE
minio replication disable but call SiteReplicationInfo api return result inconsistent

### ISSUE THREAD

**Issue by little-guy-lxr** [minio/minio#17234]
mc admin replicate remove hello --all --force
return suncess

## Expected Behavior
mc admin replicate remove xxxx --all --force
return suncess

after that
 mc admin replicate info xxxx
should return disable

## Current Behavior
mc admin replicate remove xxxx --all --force
return suncess

after that
 mc admin replicate info xxxx
Executing the command multiple times will return a different result each time

<img width="609" alt="image" src="https://github.com/minio/minio/assets/26966109/4a8e94b8-9060-4f8e-b0f8-719219943f25">

Version RELEASE.2023-03-22T06-36-24Z

**Comment by harshavardhana** [comment]
> Version RELEASE.2023-03-22T06-36-24Z

Please upgrade to latest release and re-do your tests.
