### ISSUE TITLE
The specified console static port does not work

### ISSUE THREAD

**Issue by MaxBill** [minio/minio#17236]
## Expected Behavior
use parameter --console-address ":9090" ，Fixed port 9090 should be started

## Current Behavior
use parameter --console-address ":9090" ，The specified console static port does not work，It's still a dynamic port

## Steps to Reproduce (for bugs)
1.Set parameters：--console-address ":9090"
![image](https://github.com/minio/minio/assets/16558525/bc1672cd-b25e-4c55-b41d-d62ea2ecc8bd)
![image](https://github.com/minio/minio/assets/16558525/923f3ec7-9b61-410a-82f9-92e10b1dbfd6)

2.Start Minio Docker Container
![image](https://github.com/minio/minio/assets/16558525/95a37a16-6009-4d43-9fe9-231e0438e4a9)

3.View startup logs
![image](https://github.com/minio/minio/assets/16558525/3781831d-7ac7-4a1e-a435-bdd1310de441)

## Your Environment
* Version used (`minio --version`): RELEASE.2023-05-04T21-44-30Z (commit-id=5569acd95cbc8c7d3fac59cf2aba77baa1b9bbeb)
* Server setup and configuration: minio server --console-address ":9090"
* Operating System and version (`uname -a`): Linux  5.10.120 #0 SMP Sat May 13 08:21:41 2023 x86_64 x86_64 x86_64 GNU/Linux （docker）

**Comment by harshavardhana** [comment]
Please use `minio server --console-address`  directly - you are using a third party UI to start MinIO.

Please ask them to fix it for you.
