### ISSUE TITLE
Root Disabled by Default makes docs misleading

### ISSUE THREAD

**Issue by bck01215** [minio/minio#17232]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Root is disabled when following docs. Following [this guide for linux](https://min.io/docs/minio/linux/index.html) root is disabled. 

## Expected Behavior
To be able to login as root after installing per the docs

## Current Behavior
Account is disabled and I cannot access minio console

## Possible Solution
Update docs

## Steps to Reproduce (for bugs)
1. Follow the install guide on https://min.io/docs/minio/linux/index.html
2. Error occurs when accessing console

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2023-05-04T21-44-30Z (commit-id=5569acd95cbc8c7d3fac59cf2aba77baa1b9bbeb)
* Server setup and configuration: default from link above with single directory
* Operating System and version (`uname -a`): Linux  4.18.0-425.13.1.el8_7.x86_64 #1 SMP Thu Feb 2 13:01:45 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
root is never disabled by default @bck01215 root is only disabled if you ask for it. 

```
MINIO_API_ROOT_ACCESS=off
```

**Comment by bck01215** [comment]
> `MINIO_API_ROOT_ACCESS=off`

Interesting. As stated before, I've followed the docs above.
![image](https://github.com/minio/minio/assets/77836661/fa5e5a70-14ce-47aa-8c82-e4534ecbb52f)

I experience this issue with podman as well. I've completely removed all data and started from scratch.

/etc/default/minio

```
MINIO_ROOT_USER=****
MINIO_ROOT_PASSWORD=****
MINIO_API_ROOT_ACCESS=on #previously absent
MINIO_VOLUMES='/opt/minio'
MINIO_OPTS='--console-address ":5002" --address ":5001"'
MINIO_SERVER_URL=http://minio01.service.com:5001
```
Systemd
```
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
Type=notify

WorkingDirectory=/usr/local

User=root
Group=root

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=1048576

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})
```

**Comment by bck01215** [comment]
@harshavardhana  I tested with [minio-20230131022419.0.0.x86_64.rpm](https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20230131022419.0.0.x86_64.rpm) and the issue does not occur

**Comment by harshavardhana** [comment]
Here is what I did 

```
~ wget https://dl.minio.io/server/minio/release/linux-amd64/minio
~ chmod +x minio
~ MINIO_ROOT_USER=myroot MINIO_ROOT_PASSWORD=myrootpassword ./minio server /tmp/fresh
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2023-05-04T21-44-30Z (go1.20.3 linux/amd64)

Status:         1 Online, 0 Offline. 
S3-API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://172.23.0.1:9000  http://127.0.0.1:9000           
RootUser: myroot 
RootPass: myrootpassword 

Console: http://10.0.0.185:45419 http://172.17.0.1:45419 http://172.19.0.1:45419 http://172.23.0.1:45419 http://127.0.0.1:45419      
RootUser: myroot 
RootPass: myrootpassword 

Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
   $ mc alias set myminio http://10.0.0.185:9000 myroot myrootpassword

Documentation: https://min.io/docs/minio/linux/index.html
Warning: The standard parity is set to 0. This can lead to data loss.

~ mc alias set myroot http://localhost:9000 myroot myrootpassword
Added `myroot` successfully.

~ mc admin info myroot/
●  localhost:9000
   Uptime: 44 seconds 
   Version: 2023-05-04T21:44:30Z
   Network: 1/1 OK 
   Drives: 1/1 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

1 drive online, 0 drives offline
```

Unless you forgot something that you were you playing around with. Check if you have by mistake did `mc admin config set alias/ api root_access=off`

But this is definitely not the default behavior.
