### ISSUE TITLE
How to restore Minio data from raw PVCs backups

### ISSUE THREAD

**Issue by eclipsetalk** [minio/minio#17247]
### Discussed in https://github.com/minio/minio/discussions/17246

<div type='discussions-op-text'>

<sup>Originally posted by **eclipsetalk** May 19, 2023</sup>
Hello,
I'd like to restore Minio buckets contents. I have a backup of the raw PVCs. I have 4  PVCs that contain each a /dump directory with the fragmented files. How can I reconstruct the buckets files contents?
I tried to copy the /dump contents to the target Minio PVCs  but I only got the directory structure copied but no files copied.

Thanks in advance

Eric</div>

**Comment by harshavardhana** [comment]
You can't take backups in that manner, if you do you will lose data. That is not how backups need to be performed with MinIO.

**Comment by eclipsetalk** [comment]
Thanks for the reply. So there is no way to restore or reconstruct the files from raw PVs backup? How are the files stored under the /dump directory?
