### ISSUE TITLE
XL: ListMultipart: `Istruncated` and `NextUploadIDMarker` and `NextKeyMarker` set to wrong values.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1724]
# The uncommented test in the code below reproduces the issue

https://gist.github.com/hackintoshrao/0bb00a5240eec1bf5f3c3071ebee77da . 

Here is the brief description of the issue 
- Set  `MaxUploads`  to be equal to the number of actual entries of the meta information expected. 
- Example: If there is only 1 meta info to list, `MaxUploads` to 1, in this case `IsTruncated` is supposed to be set to false,  `NextUploadIDMarker` and `NextKeyMarker` is supposed to be empty since there are no more entries left to be listed. But instead obtaining `IsTruncated` to be `true` and `NextUploadIDMarker` and `NextKeyMarker` is set to the last entry in the result. 

Again, the test case in the link above reproduces the bug. 
Just copy the code and run 
`$ go test -run=TestListMultipartUploads -v`

Here is the output of the sample run.

```
--- FAIL: TestListMultipartUploads (0.07s)
    object-api-multipart_test.go:577: Test 1: Expected NextUploadIDMarker to be "", but instead found it to be "a76910dd-cd75-4821-9cd1-84c137758962"
    object-api-multipart_test.go:581: Test 1: Expected NextKeyMarker to be "", but instead found it to be "minio-object"
    object-api-multipart_test.go:585: Test 1: Expected keyMarker to be "min", but instead found it to be ""
    object-api-multipart_test.go:589: Test 1: Expected Istruncated to be "false", but found it to "true"
FAIL
exit status 1

```

**Comment by hackintoshrao** [comment]
https://gist.github.com/hackintoshrao/8a03ca4f4db43bb53f150b42406e457f . 
Test in the link above too reproduces the bug.

**Comment by harshavardhana** [comment]
Can you submit the listMultipartUploads tests to the rewrite-xl branch? - it can be tested and validated with the new code change.

**Comment by hackintoshrao** [comment]
@harshavardhana : Sure. Still adding more cases. But will add the current work and keep updating.

**Comment by hackintoshrao** [comment]
fixed by commit https://github.com/minio/minio/commit/c705712939d8d58c4ae678961c666640544c37b2 from @krishnasrinivas  .
