### ISSUE TITLE
XL : ListMultipart: Confirming correct behaviour when `MaxUpload` is set to 0.  - May 25th

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1725]
The uncommented test case in the following link reproduces the issue. 
https://gist.github.com/hackintoshrao/e1884dd608f7094dca6bb37bf6646a42 

I'm not sure of expected behavior when `MaxUpload` is set to 0.  
Here is the observation. 
- When `MaxUplaod` is set to 0, the result contained all entries and Istruncated is set to `false`.

Wanted to know whether that's the expected behavior.
Please comment below and close the issue if that's the expected behavior.
And I'm seeing the same behavior when `MaxUpload` is set to a negative value. Is that expected too?

**Comment by harshavardhana** [comment]
> Here is the observation.
> 
> When MaxUplaod is set to 0, the result contained all entries and Istruncated is set to false.
> Wanted to know whether that's the expected behavior.
> Please comment below and close the issue if that's the expected behavior.
> And I'm seeing the same behavior when MaxUpload is set to a negative value. Is that expected too?

If maxUploads is set to '0' result shouldn't have all the entries. IT should behave similar to Amazon S3.

**Comment by hackintoshrao** [comment]
@harshavardhana : What does S3 do ? It returns empty result right ?

**Comment by hackintoshrao** [comment]
fixed by commit https://github.com/minio/minio/commit/c705712939d8d58c4ae678961c666640544c37b2 from @krishnasrinivas  .
