### ISSUE TITLE
Helm Chart: Policy setup with LDAP

### ISSUE THREAD

**Issue by Darrekt** [minio/minio#17254]
Good day to whom it may concern. I apologise in advance if this is documented somewhere, but I have tried to the very best of my ability to solve my problem on my own, and feel that this is worth bringing up. I have done my best to read all the other issues pertaining to LDAP configuration, but have found nothing that addresses my use case.

**Problem statement**
When using helm-based installs of Minio (such as the one provided in this repo or [bitnami/minio](https://github.com/bitnami/charts/tree/main/bitnami/minio), there is no clear way to have a policy assigned to LDAP user(s) at install time (using helm chart values).

I understand from the documentation that we are supposed to use the `mc` client to assign policies using `mc admin policy set`, but using `kubectl exec` into the `pod` and running `mc` commands with the `local` alias gives me `http` errors, since I have configured Minio to run with TLS. I try to do `mc alias set`, but I get the following error, since the image does not add the certificate I provided into the trust store by default.

```
Get "https://localhost:9000": x509: certificate signed by unknown authority
```

So far, the best solution I can think of would be:

1. `helm install` the minio cluster.
2. Run a separate `Job` after startup with a container that trusts the certificate authority
3. Install and run `mc` commands on that `Job` with the minio root user's credentials to set my desired policies.

Is there any better way to go about doing this? Would greatly appreciate some advice, and maybe it can be added to the documentation!

Additionally, one point of feedback I have is that it is not entirely clear from the docs that I could have used the minio root user's credentials as an access key and secret key when using `mc alias set`. Maybe this can be added to the documentation for `mc alias`. Fair enough user error on my part, but I think it wouldn't hurt to have it be a bit more explicit.

**Comment by harshavardhana** [comment]
vanilla helm chart is not maintained by us, we have no way to test this. feel free to work on a fix and send it.

Closing this issue as non-actionable on us.
