### ISSUE TITLE
[windows] Memory continued to grow, no error log was found

### ISSUE THREAD

**Issue by bravelionet** [minio/minio#17255]
window  server. minio version (RELEASE.2023-04-13T03-08-07Z ) . Memory continued to grow, no error log was found. No solution was found

![image](https://github.com/minio/minio/assets/48754924/e07df5ed-d2c2-4d75-8e18-5a4a9155664c)

**Comment by harshavardhana** [comment]
Please use latest release and let us know.

**Comment by harshavardhana** [comment]
If possible capture profile output.

**Comment by stcleezy** [comment]
We are seeing the same issue, Minio quickly consumes 100% RAM on our Windows Server 2019. System is completely idle. Using the latest 5-18 release.

Logs show this message on repeat:

```
API: SYSTEM
Time: 16:28:38 UTC 05/23/2023
DeploymentID: XXX
RequestID: 
RemoteHost: XXX
UserAgent: 
Error: cmd.StorageErr

Backtrace: 
0: internal\logger\logger.go:258:logger.LogIf()
1: cmd\data-scanner.go:566:cmd.(*folderScanner).scanFolder.func2()
2: cmd\data-scanner.go:613:cmd.(*folderScanner).scanFolder()
3: cmd\data-scanner.go:356:cmd.scanDataFolder()
4: cmd\xl-storage.go:486:cmd.(*xlStorage).NSScanner()
5: cmd\xl-storage-disk-id-check.go:186:cmd.(*xlStorageDiskIDCheck).NSScanner()
6: cmd\erasure.go:503:cmd.erasureObjects.nsScanner.func3()
```

**Comment by klauspost** [comment]
Again, without any useful information this is not reproducible.  The error above is too truncated be be useful - it doesn't show the actual error for example, and it may not be related.

To profile: `mc support profile --type cpu,mem,goroutines --airgap myminio`

**Comment by stcleezy** [comment]
@klauspost I am using the open source version and do not have access to remote support features. Is there any other way to capture useful information?

**Comment by nva-avn-dng** [comment]
I have same issue with open source version on Windows Server 2012, any help ? Plz.

**Comment by stcleezy** [comment]
FWIW we no longer see this issue with the latest version of minio (RELEASE.2023-06-09T07-32-12Z)

**Comment by harshavardhana** [comment]
We have moved go1.19.x due to some odd heap corruptions and runtime crashes. Perhaps that is what fixed this issue? 

Going to close this now.
