### ISSUE TITLE
Uploading the part of a multipart upload with partnumber = 0 gives Success (HTTP 200) + eTag

### ISSUE THREAD

**Issue by WolfgangVogl** [minio/minio#17269]
## NOTE
While playing around with s3 multipart I noticed that (through a bug in my code) i created a presigned url to upload a multipart upload part with a partnumber = 0.

And it happens what minio responded with http 200 (OK) and a proper eTag.

Trying to list the parts using the list-parts doesn't return that uploaded part nor can I complete the multipart-upload using the given eTag. While the multipart upload itself exists I could see a corresponding data file at the windows working dir of ## NOTE
While playing around with s3 multipart I noticed that due to a bug in my code I created a presigned url to upload a multipart upload part with a partnumber = 0.

Nevertheless minio answered the request with http 200 (OK) and an eTag.

When I try to list the parts with list-parts, I don't get back the uploaded part, nor can I complete the multipart upload with the specified eTag.
While the multipart upload exists, I could see a corresponding data file in minio's Windows working directory
(.minio.sys\multipart\8a6756162db131701ef5818f7e32ffc12ff94b947a4ab4ee95095bf8be279200\b35cf7e6-510a-45c4-8fa3-cc31806ac22b\2fe4edf8-eee3-42f3-ad4f-8acf0a54a853\part.0 and part.0.meta).

The aws documentation states, "Part numbers can be any number from 1 to 10,000, inclusive. A part number uniquely identifies a part and also defines its position within the object being created. If you upload a new part with the same part number that was used for a previous part, the previously uploaded part will be overwritten."
Accordingly, I would have expected an error message indicating that I used an incorrect part number.

With the aws cli the behavior is the same as with the generated predefined URL.

I also tested with partnumber = x - then minio correctly displays an error:
`ValueError: invalid literal for int() with base 10: 'x'`.

With partnumber = -1 it also answered with success, but I could not find any file in the local filesystem. (so similar to the case partnumber = 0)

## Expected Behavior
I would expect an error message.
For example, this is what aws s3 replied:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>InvalidArgument</Code>
	<Message>Part number must be an integer between 1 and 10000, inclusive</Message>
	<ArgumentName>partNumber</ArgumentName>
	<ArgumentValue>0</ArgumentValue>
	<RequestId>KGFA6F9HK7NKCDPN</RequestId>
	<HostId>9IU***Kg=</HostId>
</Error>
```
```
PS E:\temp\aws-cli> aws --no-verify-ssl --profile default s3api create-multipart-upload --bucket s3-MYBUCKET-test --key whatever
urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-MYBUCKET-test.s3.eu-central-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
{
    "ServerSideEncryption": "AES256",
    "Bucket": "s3-MYBUCKET-test",
    "Key": "whatever",
    "UploadId": "qAN***S1I-"
}
```
```
PS E:\temp\aws-cli> aws --no-verify-ssl --profile default s3api upload-part --bucket s3-MYBUCKET-test --key whatever --part-number 0 --upload-id qAN***S1I- --body data1.png
urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-MYBUCKET-test.s3.eu-central-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings

An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
```
## Current Behavior
No error is indicated - instead I get an http success code:
`DEBUG - http://127.0.0.1:9060 "PUT /s3-MYBUCKET-test/whatever?partNumber=0&uploadId=ZmE0NzMzMGYtNGNhNy00ZjM5LTk3NDgtYzNhMWFhZDUwZjFlLjEwMTUyODVkLWUxMDQtNDllMS04NTBmLWZhNDU0MmJkNjgxNA HTTP/1.1" 200 0`

## Steps to Reproduce (for bugs)

1.
```
PS E:\temp\aws-cli> aws --no-verify-ssl --profile minio --endpoint-url http://127.0.0.1:9060 s3api create-multipart-upload --bucket s3-MYBUCKET-test --key whatever
{
    "Bucket": "s3-MYBUCKET-test",
    "Key": "whatever",
    "UploadId": "ZmE0NzMzMGYtNGNhNy00ZjM5LTk3NDgtYzNhMWFhZDUwZjFlLjEwMTUyODVkLWUxMDQtNDllMS04NTBmLWZhNDU0MmJkNjgxNA"
}
```

2.
```
PS E:\temp\aws-cli> aws --no-verify-ssl --profile minio --endpoint-url http://127.0.0.1:9060 s3api upload-part --bucket s3-MYBUCKET-test --key whatever --part-number 0 --upload-id ZmE0NzMzMGYtNGNhNy00ZjM5LTk3NDgtYzNhMWFhZDUwZjFlLjEwMTUyODVkLWUxMDQtNDllMS04NTBmLWZhNDU0MmJkNjgxNA --body data1.png
{
    "ETag": "\"564b3c91b52897c69bbaba0e3415fb4c\""
}
```

3.
```
PS E:\temp\aws-cli> aws --no-verify-ssl --profile minio --endpoint-url http://127.0.0.1:9060 s3api list-parts --bucket s3-MYBUCKET-test --key whatever --upload-id ZmE0NzMzMGYtNGNhNy00ZjM5LTk3NDgtYzNhMWFhZDUwZjFlLjEwMTUyODVkLWUxMDQtNDllMS04NTBmLWZhNDU0MmJkNjgxNA
{
    "ChecksumAlgorithm": "",
    "Initiator": {
        "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4",
        "DisplayName": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
    },
    "Owner": {
        "DisplayName": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4",
        "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
    },
    "StorageClass": "STANDARD"
}
```

## Context
I've tried to upload a part of a multipart upload and had an bug that was hard to spot as minio told me "SUCCESS" for the upload itself..
I was trying to upload part of a multi-part upload and had an error that was hard to see because minio was showing me "SUCCESS" for the upload itself....

## Regression
I don't think so.

## Your Environment
* minio.exe version RELEASE.2023-05-18T00-05-36Z (commit-id=9d96b18df03f5978873705ac55959161f018fb48)
* Runtime: go1.19.9 windows/amd64

* Betriebsystemname	Microsoft Windows 10 Enterprise
* Version	10.0.19045 Build 19045

`minio.exe "server" "E:\temp\minio" "--address" ":9060" "--json" "--console-address" ":9001"`

**Comment by klauspost** [comment]
Must be a regression. I will investigate. Thanks for the detailed report.

**Comment by klauspost** [comment]
https://github.com/minio/minio/pull/17270 added, with a bit more checks as well.
