### ISSUE TITLE
Unable to authenticate API using root username and password

### ISSUE THREAD

**Issue by hanzlamateen** [minio/minio#17268]
I want to be able to login using s3 api without creating new authentication credentials from web console. Rather use the root username & password as client secret and key.

## Expected Behavior
It should be able to authenticate.

## Current Behavior
Unable to authenticate

## Steps to Reproduce (for bugs)
1. Used below docker compose file to create container using `docker-compose up -d` command.
```
# docker-compose.yml
version: '2.3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: etherealengine_minio_s3
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: BDlK09hrb8i8iRgYSvJC
      MINIO_ROOT_PASSWORD: D0hAwwGKeBpUFQgjx2w9ySpgC6wsjCLshBi9nWxa
    command: server /data --console-address ":9090"
volumes:
  minio_storage: {}
```
2. Afterwards try to login using S3 Browser tool with secret as `MINIO_ROOT_PASSWORD` and other credentials as mentioned below but it fails.
![image](https://github.com/minio/minio/assets/10975502/860abf6c-20b7-4443-9811-76d76c766ba4)
3. I also tried to login using same credentials as STS for http://127.0.0.1:9090/login but failed.
4. I also tried the default credentials and it failed.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by vadmeste** [comment]
@hanzlamateen what is your MinIO version ? what is the error that you are seeing ?

**Comment by ravindk89** [comment]
Also, if you run

```
mc alias set local http://localhost:9000 <ROOT_USER> <ROOT_PASSWORD>
```

Does it succeed, and can you run `mc admin info local` after?

If so I suspect the issue is you are enabling SSL/TLS connectivity to a MinIO server not running with TLS - your docker setup has no indication of running with TLS enabled.

**Comment by hanzlamateen** [comment]
@vadmeste

`minio --version`
```
minio version RELEASE.2023-05-18T00-05-36Z (commit-id=9d96b18df03f5978873705ac55959161f018fb48)
Runtime: go1.19.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

When I try to login on http://127.0.0.1:9090/login using STS method and credentials as explained above, it just reloads login page.
> It works fine when I login with 'User Credentials' option with above username and password.

Whereas S3 Browser gives error related to unable to get buckets.
![image](https://github.com/minio/minio/assets/10975502/28b3752f-19d4-4e8f-abb0-d9de68bd859a)

**Comment by hanzlamateen** [comment]
@ravindk89 
![image](https://github.com/minio/minio/assets/10975502/a35d1ae5-42fc-4a1b-9d01-8334f696c37e)

**Comment by hanzlamateen** [comment]
Basically, I want to be able to login using s3 api without creating new access key from web console. Rather use the root username & password as client secret and key Or if there is any way to provide those keys in env when initializing container.

**Comment by ravindk89** [comment]
I'm not sure what the issue is here. If you can log in via CLI using those credentials, the credentials work. You can use those in your applications if you so choose, or generate new access keys and policies via CLI. You could do this by running a script after container init. 

For S3 Browser, that's not our product. My suspicion is that you have TLS enabled in the settings where MinIO Server was not started with TLS.  You may also need to configure S3Browser to use Path style instead of DNS style, since MinIO supports path-style by default.

With regards to using STS, how are you constructing the `AssumeRole` API request? 

For Console, logging in with just the root user and pass w/o even invoking STS should work.

**Comment by harshavardhana** [comment]
User is using TLS enabled in S3 browser however server is deployed without TLS certs.

Please fix these things to match what you want from the deployment.
