### ISSUE TITLE
MiniO dualstack AWS bucket error

### ISSUE THREAD

**Issue by cx-IliyaY** [minio/minio#17299]
Hello,
We use MiniO as gateway for our AWS S3 buckets,
recently we have a lot errors of `PutObject` with dualstack endpoint although we use only ipv4.

## Expected Behavior
We expect MiniO not to try upload object via ipv6 endpoint and only via ipv4 endpoint, because we don't except ipv6 in our VPN.

## Current Behavior
As we saw the object is uploaded to S3 bucket successfully but then also we got an error of the same object trying to upload via dualstack endpoint
Error:
`Time: 18:07:43 UTC 05/24/2023
DeploymentID: 23fa463e-1117-4fc1-a5c7-73dd63ef6705
RequestID: 1762269C42FE10B2
RemoteHost: 10.129.33.3
Host: nv-platform-minio:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.13
Error: Put "https://s3.dualstack.us-east-1.amazonaws.com/<bucket-name>/<path>": use of closed network connection (*url.Error)`

## Possible Solution
We have checked the option to disable ipv6 in minio chart/values/environment variables
in all the configurations we have the ipv6 isn't enabled
![image](https://github.com/minio/minio/assets/95761341/f0f10e7e-30d8-48fc-9b44-f816f9bbcf58)

## Your Environment
* Version used (`minio --version`): minio version DEVELOPMENT.2022-04-16T04-26-02Z
* Helm Chart: https://charts.bitnami.com/bitnami , Version: 11.10.10
* Operating System and version (`uname -a`): x86_64 GNU/Linux

**Comment by klauspost** [comment]
We no longer support this version/feature.
