### ISSUE TITLE
Number of empty folders inside .minio.sys/multipart is growing up constantly 

### ISSUE THREAD

**Issue by ypo** [minio/minio#17307]
Number of empty folders inside .minio.sys/multipart is growing up constantly 

## Context

I'm using minio to store files with a very short life-time  (~1 minute )

Files are uploaded using the multipart API  and removed after a short time (~1 minute )

I'm using rusoto_s3 as S3 client (https://github.com/rusoto/rusoto)
```
S3Client::create_multipart_upload()
S3Client::upload_part()
S3Client::complete_multipart_upload()
...
S3Client::delete_object()
```

All files are uploaded correctly

However the number of folders in .minio.sys/multipart is growing up and up. 
All the folders are empty.
After running it for few days, millions of folders are created and the system is slowing down.

## Your Environment

Minio RELEASE.2023-05-18T00-05-36Z with the following docker compose
Docker version 23.0.3,

```
  minio:
    image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z 
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - 9002:9000
      - 9001:9001
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9002/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
```

**Comment by harshavardhana** [comment]
> However the number of folders in .minio.sys/multipart is growing up and up.
> All the folders are empty.
> After running it for few days, millions of folders are created and the system is slowing down.

This should have been fixed, let me check locally.
