### ISSUE TITLE
Add Access-Control-Allow-Origin as response header

### ISSUE THREAD

**Issue by tomaswarynyca** [minio/minio#17317]
## Expected Behavior
> Access-Control-Allow-Origin: *

## Current Behavior
This header does not exist on preflighting

> Access-Control-Allow-Methods: GET,OPTIONS,PUT
Access-Control-Max-Age: 100
Content-Length: 0

## Possible Solution
Modify API to send that header

## Steps to Reproduce (for bugs)
Use fetch from javascript to make a request to a presigned URL

## Context
I have an API that does a redirect to a Presigned URL
When preflighting I get a CORS error

## Your Environment

* Version used (`minio --version`): 2023-05-27T05:56:19Z
* Server setup and configuration: docker
* Operating System and version (`uname -a`): linux

**Comment by halmogbl** [comment]
same problem here

minio version RELEASE.2023-05-27T05-56-19Z (commit-id=394690dcfb1b80532d5785bbf5313a0e57b58a00)

**Comment by tomaswarynyca** [comment]
@harshavardhana thank you for solving the problem!

**Comment by tomaswarynyca** [comment]
@harshavardhana This did not solve the problem!
No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by harshavardhana** [comment]
@tomaswarynyca ?

```
curl -v -XOPTIONS -H "Origin: *" http://localhost:9000/images/README.md
*   Trying 127.0.0.1:9000...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> OPTIONS /images/README.md HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.81.0
> Accept: */*
> Origin: *
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, Content-Disposition, Last-Modified, Content-Language, Cache-Control, Retry-After, X-Amz-Bucket-Region, Expires, X-Amz*, X-Amz*, *
< Vary: Origin
< Date: Sat, 10 Jun 2023 20:40:06 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by tomaswarynyca** [comment]
@harshavardhana fetch redirect in browser sends in request **Origin: null** and minio doesn't send cors headers

> Access-Control-Allow-Methods: GET,OPTIONS,PUT
Access-Control-Max-Age: 100
Content-Length: 0
Date: Sun, 11 Jun 2023 13:11:26 GMT
