### ISSUE TITLE
Access Keys and Policies keep reloading

### ISSUE THREAD

**Issue by wushilin** [minio/minio#17315]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

When I click policies and access keys, it is loading forever. 
Other features on the console seems working fine.

## Expected Behavior
The policies and service accounts should load almost instantly.

## Current Behavior
They are loading forever.

Network debug shows the request is pending forever:
/api/v1/service-accounts

## Possible Solution
Another bug says it was fixed. However, I am still seeing it using the most recent release.
https://github.com/minio/minio/issues/16810

## Steps to Reproduce (for bugs)
It could be data issue. So I am not sure how to properly write reproduce steps.

Backend log shows:

API: SYSTEM()
Time: 14:56:49 UTC 05/30/2023
DeploymentID: 5cb6ce16-a31a-455a-89dc-1e663c1e9fac
Error: Failure in periodic refresh for IAM (took 0.24s): not authorized: insufficient permissions (*errors.errorString)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/iam.go:450:cmd.(*IAMSys).watch()

I am not sure if it is related. I am using the root account.

## Context
I can't see existing policies, nor updating policies

## Regression
Not sure

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2023-05-27T05-56-19Z (commit-id=394690dcfb1b80532d5785bbf5313a0e57b58a00)
Runtime: go1.19.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

* Server setup and configuration:
Very typical setup
/tank/services/minio/minio server --address 192.168.44.100:9000 --console-address 192.168.44.100:9001 /nfs/services/minio/data.1

* Operating System and version (`uname -a`):
Linux bazinga 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You seem to have configured encryption and it's not allowed for certain permissions

**Comment by wushilin** [comment]
Yes I did configure encryption for one bucket. Why it is affecting the
overall access key and policies?

**Comment by wushilin** [comment]
The encryption is working so far. Not sure should I disable the encryption at all, or allow all operations on the KES?

**Comment by harshavardhana** [comment]
> Yes I did configure encryption for one bucket. Why it is affecting the overall access key and policies?

if you configure KMS all your IAM assets are encrypted always. You can't disable encryption once enabled. KMS is a one-way route if you disable your KMS your IAM credentials will be unreadable.

You need to allow all mostly read operations because that is where it's failing the permissions, there are other extra API calls that MinIO needs now such as `/v1/status`, `/v1/metrics` - you need to enable those as well.

**Comment by wushilin** [comment]
Thanks for your reply. I will give it a try.
