### ISSUE TITLE
minio  crashed with  drive  error


starting  two  minio (lasted  version) process  with flowwing  script  
on  windows  server  2012  in  two  diffierent  servers

@set MINIO ROOT USER=minio
@set MINIO_ROOT_PASSWORD=minio1234
aminio.exe server --address "2000--console-address ":2018
http://128.3.40.20/e:/mfiles
http:/128.3.40.20/f:/mfileshttp:/128.10.50.24/f:/mfiles http:/128.10.50.24/g:/mfiles> minio.log




### ISSUE THREAD

**Issue by stepjacky** [minio/minio#17318]
sometimes  its  crashed  with the  flowwing error  message

Drive: http:/128.10.50.24:2000/f:/mfiles returned drive not  found (fmt.wrapError)
Time:
002224UTC05/31/2023
c41ad1c1-50e7-41c2-671c-02eb8e16d56f
UserAgent:
http://128.10.50.24:2000/f:/mfiles returned drive not found (*fnt wrapError)
0:
internal\logger\logger go 248 logger LogAlwaysIfO
1:
cmdprepare-storage go 50 emd glob. fune5 10
2:
ond;erasure-sets. go 217: end (verasureSets) connectisks fune2()

but  when  i  restart its  again  .its  work  ok
how  dose  cause  this  occurrence！

**Comment by klauspost** [comment]
You don't provide any useful information that is requested in the template.

It looks like you are not providing locally attached disks, or something is preventing normal operation.
