### ISSUE TITLE
Integration with Keycloak not working as expected

### ISSUE THREAD

**Issue by raj-katonic** [minio/minio#17359]
## Issue Description

I have recently upgraded Keycloak to version 19.x and followed the Keycloak-MinIO integration document for my platform. Our platform consists of various components, so once a user is logged in to any of the component, he gets access to all the components until the cookie or session expires. However, I'm facing an issue where after logging into the platform, I am prompted to log in again before accessing MinIO. This issue was not present in Keycloak version 13.x. Even though I followed the latest integration document. https://min.io/docs/minio/macos/operations/external-iam/configure-keycloak-identity-management.html#configure-minio-for-keycloak-identity-management

## Versions

- MinIO Server Version: quay.io/minio/minio:RELEASE.2022-11-11T03-44-20Z
- MinIO Console Version: v0.24.x
- Keycloak Version: 19.0.2

## Steps to Reproduce

1. Upgrade Keycloak to version 19.x.
2. Follow the Keycloak-MinIO integration document https://min.io/docs/minio/macos/operations/external-iam/configure-keycloak-identity-management.html#configure-minio-for-keycloak-identity-management.
3. Observe that a second login prompt is displayed before accessing MinIO.

## Expected Behavior

After logging into the platform, I should be able to access MinIO without being prompted for login again.

## Actual Behavior

I am required to log in twice before gaining access to MinIO.

Please let me know if any further details are needed. Thank you!

**Comment by harshavardhana** [comment]
> MinIO Server Version: quay.io/minio/minio:RELEASE.2022-11-11T03-44-20Z

Please upgrade to latest release @raj-katonic and let us know.

**Comment by ravindk89** [comment]
Please also use Keycloak 20 or 21. As part of writing that documentation I tested against both of those versions with a recent version of MinIO and did not encounter a login redirect loop. There were also significant changes in the UI between 20 and 21, and I have to assume the same is true for 19 -> 20/21.

**Comment by raj-katonic** [comment]
Thanks @harshavardhana and @ravindk89 l will upgrade both and let you know

**Comment by ravindk89** [comment]
Ah, one thing I *did* run into is that if I had the keycloak admin panel open and logged in, trying to log into console via SSO would fail due to the browser having some sort of cookie/auth conflict.

Use Console in a private browser or a different browser than whichever one you are logged into Keycloak's admin panel with to make sure you aren't running into some sort of cookie/auth related issue.
