### ISSUE TITLE
Error while attempting PutBucketWebsite with AWS CLI

### ISSUE THREAD

**Issue by kbarrette** [minio/minio#17355]
## Expected Behavior
`PutBucketWebsite` works as expected with AWS CLI

## Current Behavior
```
❯ aws s3 website --endpoint-url=http://localhost:9090 s3://website/

An error occurred (MalformedXML) when calling the PutBucketWebsite operation: The XML you provided was not well-formed or did not validate against our published schema.
```

From the minio server logs:
```
API: SYSTEM()
Time: 19:33:13 UTC 06/05/2023
DeploymentID: bdc166ef-c21e-41cd-97ad-56e6487d27db
Error: expected element type <CreateBucketConfiguration> but have <WebsiteConfiguration> (xml.UnmarshalError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/handler-utils.go:54:cmd.parseLocationConstraint()
       4: cmd/auth-handler.go:369:cmd.authenticateRequest()
       3: cmd/auth-handler.go:488:cmd.checkRequestAuthTypeCredential()
       2: cmd/bucket-handlers.go:738:cmd.objectAPIHandlers.PutBucketHandler()
       1: net/http/server.go:2122:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)
1. Run minio server
2. Attempt to invoke `aws s3 website` as above
3. See an error

## Context
Would like to use minio in test environments rather than AWS S3, and I need website hosting capability

## Regression
No, as far as I know

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2023-05-04T21-44-30Z (commit-id=5569acd95cbc8c7d3fac59cf2aba77baa1b9bbeb)`
* Server setup and configuration: `minio server --address :9090 .`
* Operating System and version (`uname -a`): `darwin 20.6.0`
* AWS CLI version: `aws-cli/2.11.13 Python/3.11.3 Darwin/20.6.0 source/x86_64 prompt/off`

**Comment by harshavardhana** [comment]
@kbarrette we do not support this API and do not plan to do so in near future. If you have a production use case feel free to join us at https://min.io/pricing

You can use projects like https://github.com/harshavardhana/s3www
