### ISSUE TITLE
I hope that the file permissions for uploading to minio can be customized through settings

### ISSUE THREAD

**Issue by cyb-start** [minio/minio#17367]
I uploaded the file to Minio through code，what permissions do I want for the file is `-rw-------`, attempt to use the userMetadata method in PutObjectArgs to customize the permissions for uploading files，but no success.Alternatively, setting permissions through the file method before converting to a file stream was unsuccessful too.
The file format of the minio server now is `my-upload.txt` -> `drwxrwxr-x`,also `my-upload.txt/` have `xl.meta`,file format is `-rw-rw-r--`.
Hope to receive a response

**Comment by cyb-start** [comment]
Through the policy control of Minio, only make file read or write,this is not what I want.

**Comment by harshavardhana** [comment]
You need to use IAM policies `mc admin user add` and `mc admin policy add`.

**Comment by klauspost** [comment]
Also MinIO is an object store, not a filesystem abstraction. Your file permission means nothing in S3 terms.

**Comment by cyb-start** [comment]
Okay, thank you for the answer. At present, I have convinced the leader not to worry about file permissions anymore, as minio single node deployment or distributed deployment ultimately stores metadata xl.meta. He does not need to worry about being implanted into Trojan programs through minio.
