### ISSUE TITLE
Default "readonly" permission doesn't allow to list object

### ISSUE THREAD

**Issue by acolombier** [minio/minio#17379]
## Expected Behavior

The default policy `readonly` should grant user with the ability to list the content of buckets

## Current Behavior

If they try to list the content, they will get permission denied.

## Possible Solution

In [this file](https://github.com/minio/pkg/blob/main/iam/policy/constants.go#LL61C22-L61C22), the line 62 should be changed to
```
Actions:   NewActionSet(GetBucketLocationAction, GetObjectAction, ListObjectAction, ListAllMyBucketsAction),
``` 

Note that will still not allow a user to list the content of versioned bucket, which would need more permissions.

Currently, the workaround is to manually modify this policy or use an other one.

I would be happy to issue a PR if that a behavior you would like to be changed as suggested.

## Steps to Reproduce (for bugs)

1. Assign the default `readonly`
2. Try to list buckets or content of one

## Context

This was achieved on the docker image `RELEASE.2023-05-27T05-56-19Z` but should work on the latest build as well.

## Regression

_Is this issue a regression?_ **No**

## Your Environment

* Version used (`minio --version`): 

```
minio version RELEASE.2023-05-27T05-56-19Z (commit-id=394690dcfb1b80532d5785bbf5313a0e57b58a00)
Runtime: go1.19.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

**Comment by harshavardhana** [comment]
Yes it does not - its working as expected, you want more permissions add more simple.

**Comment by acolombier** [comment]
Is it possible to disable it? Or do we need to delete them after every install?
