### ISSUE TITLE
Can't define policy with ExistingObjectTag on PUT object

### ISSUE THREAD

**Issue by sushiMix** [minio/minio#17370]
## Expected Behavior

Being able to apply rights as described in the documentation: https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#supported-s3-policy-condition-keys with PutObject / PutObjectTagging 

## Current Behavior
Trying to submit the following policy :
`
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": ["s3:GetBucketLocation", "s3:HeadBucket", "s3:ListBucket"],
        "Resource": "arn:aws:s3:::test"
      },
      {
        "Effect": "Allow",
        "Action": ["s3:GetObject"],
        "Resource": "arn:aws:s3:::test/*"
      },
      {
        "Effect": "Deny",
        "Action": ["s3:PutObjectTagging", "s3:PutObject"],
        "Resource": "arn:aws:s3:::test/*",
        "Condition": {
            "StringEquals":
              {"s3:ExistingObjectTag/sealed": "on"}
          }
      }
  ]
}
`

Fails with : 

> There was an error creating a Policy: unsupported condition keys '[s3:ExistingObjectTag/sealed]' used for action 's3:PutObject'. Please check Policy syntax.

## Possible Solution
Update the documentation or code.

## Steps to Reproduce (for bugs)

1. Open the mini console
2. Try to submit the policy in the current behavior description.

## Context
Trying to use object tagging to avoid put on message (versioning mgt is too heavy/complex for our use case).

## Regression
Don't know as my previous version of minio does not support it.

## Your Environment

* mini docker image RELEASE.2023-05-04T21-44-30Z
* single node server.

**Comment by klauspost** [comment]
This must be a validation issue. Since the key will only exist when objects contains the tag. It would seem like we need to accept all  dynamic keys.

**Comment by klauspost** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging-and-policies.html says

> `s3:ExistingObjectTag/<tag-key>` – Use this condition key to verify that an existing object tag has the specific tag key and value.

> Note
> When granting permissions for the PUT Object and DELETE Object operations, this condition key is not supported. That is, you cannot create a policy to grant or deny a user permissions to delete or overwrite an object based on its existing tags.

**Comment by sushiMix** [comment]
@klauspost can you update the minIO documentation ?

<img width="791" alt="image" src="https://github.com/minio/minio/assets/53741704/2ab1118f-f582-4188-baa8-76128b722f27">

**Comment by klauspost** [comment]
@ravindk89
