### ISSUE TITLE
Failed to create remote tier (AWS S3 Bucket) with IAM role

### ISSUE THREAD

**Issue by robert-pudlowski-mox** [minio/minio#17381]
## Expected Behavior
I would love to add remote tier - AWS S3 Bucket using IAM role which is assigned to my service account and EKS worker nodes instead of AWS ACCESS and SECRET KEY

## Current Behavior
`{"Code":"XMinioAdminTierInsufficientPermissions","Message":"failed to perform PUT Prefix access is denied: minio2-object-migraton/probeobject","Resource":"/minio/admin/v3/tier","RequestId":"176681ECF34F935A","HostId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8"}`

I'm using minio client inside of my EKS cluster and when I'm trying to add remote tier - I'm getting the issue with Insufficient Permission. I went through the docs: https://min.io/docs/minio/linux/administration/object-management/transition-objects-to-s3.html but nothing changed. 

I'm able to copy files to the remote S3 bucket from EKS cluster using IAM role with success, but minio client returns error. 
User with attached policies to minio is created with full permissions. 

## Possible Solution
1. Fix the issue with insufficient permissions or
2. Add option to use AWS role in Minio Console - right now there are AWS SECRET and ACCESS KEY required

## Steps to Reproduce (for bugs)

1. Execute inside of EKS cluster with minio: 
`mc alias set myminio http://opencti-minio:9000 XXX XXX
Added `myminio` successfully.`
2. Create policy using yaml file: 
`{
   "Version": "2012-10-17",
   "Statement": [
      {
            "Action": [
               "admin:*"
            ],
            "Effect": "Allow",
            "Sid": "EnableRemoteTierManagement"
      },
      {
            "Action": [
               "*"
            ],
            "Resource": [
                        "arn:aws:s3:::*"

],
            "Effect": "Allow",
            "Sid": "EnableLifecycleManagementRules"
      }
   ]
}`

`mc admin policy add myminio LifecycleAdminPolicy policy_file.yaml`
`Created policy `LifecycleAdminPolicy` successfully.`
3. Attach policy to user:
`mc admin policy attach myminio LifecycleAdminPolicy --user alphaLifecycleAdmin`
`Policy `LifecycleAdminPolicy` successfully attached to user `alphaLifecycleAdmin``
4. Try to add remote tier (S3)
`mc --debug  admin tier add s3 myminio S3TIER --use-aws-role --endpoint https://s3.dualstack.ap-east-1.amazonaws.com --bucket XXXX --region ap-east-1`

`mc: <DEBUG> PUT /minio/admin/v3/tier?force=false HTTP/1.1
Host: opencti-minio:9000
User-Agent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2023-05-30T22-41-38Z
Content-Length: 236
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=ChangeMeAccess/20230607//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 5bbff7fb11e8c56f0a6a843003b522b97022bbc392f5891ba0d1a659ba3a6974
X-Amz-Date: 20230607T222855Z

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 285
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Wed, 07 Jun 2023 22:28:56 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 176680FD325397A4
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminTierInsufficientPermissions","Message":"failed to perform PUT Prefix access is denied: XXXXX/probeobject","Resource":"/minio/admin/v3/tier","RequestId":"176680FD325397A4","HostId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8"}
mc: <DEBUG> Response Time:  1.524802767s

mc: <ERROR> Unable to configure remote tier target: failed to perform PUT Prefix access is denied: XXXXXX/probeobject
 (1) ilm-tier-add.go:382 cmd.mainAdminTierAdd(..) Tags: [s3, myminio, S3TIER]
 (0) ilm-tier-add.go:382 cmd.mainAdminTierAdd(..)
 Release-Tag:RELEASE.2023-05-30T22-41-38Z | Commit:ca1d00741b95 | Host:simple-centos-5494d66c7d-cdrgl | OS:linux | Arch:amd64 | Lang:go1.19.9 | Mem:67 MiB/86 MiB | Heap:67 MiB/72 MiB.`

## Context
I'm trying to configure Lifecycle policy to S3 bucket without AWS Access and Secret KEY

## Regression
no
## Your Environment
Minio RELEASE.2023-05-30T22-41-38Z
EKS 1.22 version
AWS S3 service

**Comment by shtripat** [comment]
@robert-pudlowski-mox below formatted policy json mentioned in your above comment, missing `Resource` entry for first statement
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "admin:"
      ],
      "Effect": "Allow",
      "Sid": "EnableRemoteTierManagement"
    },
    {
      "Action": [
        ""
      ],
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Effect": "Allow",
      "Sid": "EnableLifecycleManagementRules"
    }
  ]
}
```
Can you provide the proper json?

**Comment by shtripat** [comment]
@robert-pudlowski-mox I feel there is small gap in understanding the way `--use-aws-role` works.
You need a role created with attached policy and assign this role to the node.
In this scenario actually MinIO works as s3 client to the AWS. Using the role assigned, it would get creds to connect and create tier to the remote instance.

I was able to follow below steps and setup a tier successfully -

1. Create an EC2 instance
2. Create a role say `test-role` with inline policy with below JSON content
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::my-destination-bucket"
            ],
            "Sid": ""
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::my-destination-bucket/*"
            ],
            "Sid": ""
        }
    ]
}
```
3. Attach this role to the EC2 instance
4. Deploy and start MinIO
```
minio server ./test
```
5. Create an alias to the MinIO instance and create a bucket
```
$ mc alias set myminio http://localhost:9000 minioadmin minioadmin
$ mc mb myminio/test-bucket
$ echo "1" | mc pipe myminio/test-bucket/obj1
```
6. Create a tier for this bucket
```
$ mc admin tier add s3 myminio S3TIER --use-aws-role --endpoint https://s3.amazonaws.com --bucket my-destination-bucket --debug
mc: <DEBUG> PUT /minio/admin/v3/tier?force=false HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2023-06-15T15-08-26Z
Content-Length: 184
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230619//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: 3cac7dac331a88b64719d959287d58d31233f432a4091084ad483ac9c6cece41
X-Amz-Date: 20230619T170154Z

mc: <DEBUG> HTTP/1.1 204 No Content
Content-Length: 0
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Mon, 19 Jun 2023 17:01:54 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 176A1E1BB6DE2CF3
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  179.785351ms

Added remote tier S3TIER of type s3
```
7. Verify the tier by listing
```
$ mc ilm tier list myminio
Name    |Type  |Endpoint                  |Bucket       |Prefix  |Region  |Storage-Class  
S3TIER  |s3    |https://s3.amazonaws.com  |my-destination-bucket  |        |        |               
```

Hope this explains and help!
