### ISSUE TITLE
ListObjectsV2 stoped working after update on Minio

### ISSUE THREAD

**Issue by BrunoTCouto** [minio/minio#17396]
## Expected Behavior
ListObjectsV2 on minio-js stopped working after the last update [RELEASE.2023-06-09T07-32-12Z](https://hub.docker.com/layers/minio/minio/RELEASE.2023-06-09T07-32-12Z/images/sha256-90fec564cd3f01c78f560782b2088213d067836011a4be71a280f0ce3d70610d?context=explore) on minio, using previous docker image works fine [RELEASE.2023-06-02T23-17-26Z](https://hub.docker.com/layers/minio/minio/RELEASE.2023-06-02T23-17-26Z/images/sha256-010f3ddfdfc10b3d42cfff9e8f14fe5895e8d2d38c7bdc5c4d3bdc676d5b21e5?context=explore)

## Current Behavior
Using listObjectsV2 from minio-js stopped working after this last update, the code does not throw any error neither I can see errors on minio log

## Steps to Reproduce (for bugs)

This is a sample code that was working fine before

```ts 
async getStorePhotos(id: string, prefix: string) {
  this.logger.log(`Fetching pictures for store ${id}`);
  const listObjects = this.minioClient.listObjectsV2(
    'images',
    `/${id}/${prefix}`,
    true,
  );

  const objects = (await new Promise((resolve) => {
    const objects = [];
    listObjects.on('data', (obj) => {
      objects.push(obj);
    });
    listObjects.on('error', (error) => {
      this.logger.error(error);
      resolve([]);
    });
    listObjects.on('end', () => {
      resolve(objects);
    });
  })) as Array<BucketItem>;

  const signedUrls = (await Promise.all(
    objects.map(async (object) => this.getSignedUrl(object)),
  )) as Array<string>;

  return signedUrls.filter((file) => file !== null);
}
```

## Context
I list all objects in a bucket to generate pre signed URLs to display images on a TV

**Comment by harshavardhana** [comment]
This looks like a bug in minio-js

**Comment by BrunoTCouto** [comment]
Maybe the issue can be there, but it started after the update on minio, so I was not sure if I posted here or there.

If you guys think its better open the issue there, i will be happy to do it

**Comment by harshavardhana** [comment]
yeah because we changed a few things in ListObjectsV2 for S3 compatibility, such as avoiding `Owner` references if `fetchOwner` is not specified etc.

I suspect minio-js is expecting some elements.

**Comment by harshavardhana** [comment]
do you have a full reproducer? @BrunoTCouto I am no javascript expert - it will help if it is self contained and I can just run it locally.

**Comment by BrunoTCouto** [comment]
I can create a simple repository for you. I will need just some time

**Comment by BrunoTCouto** [comment]
Hi @harshavardhana , I created a minimal project with just one endpoint 

https://github.com/BrunoTCouto/minio-listObjectsV2


You need to fill the `.env` file and then make a GET request passing the name of the bucket, for example `localhost:3000/images`

**Comment by harshavardhana** [comment]
@BrunoTCouto I see all files

```json
curl -s http://localhost:3000/images | jq .
{
  "objects": [
    {
      "name": "nest-cli.json",
      "lastModified": "2023-06-10T20:16:38.861Z",
      "etag": "b6c9c4b64b7092bea720263a47b574cf",
      "size": 171
    },
    {
      "name": "package.json",
      "lastModified": "2023-06-10T20:16:38.862Z",
      "etag": "f959663bc1ff46dcff1fa759d7814e8f",
      "size": 2007
    },
    {
      "name": "tsconfig.build.json",
      "lastModified": "2023-06-10T20:16:38.864Z",
      "etag": "f73d0f011ee462dcdf7f02bbdcde284b",
      "size": 97
    },
    {
      "name": "tsconfig.json",
      "lastModified": "2023-06-10T20:16:38.864Z",
      "etag": "bca7bfe87c64c692d467acbb9df6e926",
      "size": 546
    }
  ]
}
```

```
mc ls myminio/images/
[2023-06-10 13:16:38 PDT]   171B STANDARD nest-cli.json
[2023-06-10 13:16:38 PDT] 2.0KiB STANDARD package.json
[2023-06-10 13:16:38 PDT]    97B STANDARD tsconfig.build.json
[2023-06-10 13:16:38 PDT]   546B STANDARD tsconfig.json
```

```
mc admin info myminio/
●  localhost:9000
   Uptime: 8 minutes 
   Version: 2023-06-10T05:38:08Z
   Network: 1/1 OK 
   Drives: 1/1 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

3.7 GiB Used, 3 Buckets, 39 Objects
1 drive online, 0 drives offline
```

**Comment by BrunoTCouto** [comment]
Well, I'm not sure how I can debug my instance, if i rollback 2023-06-02 it works fine, in 2023-06-09 it just returns me:

```json
{
  objects: []
}
```

**Comment by harshavardhana** [comment]
Trying with the docker image, it also seems to be working fine. Can you show me your deployment configuration?

**Comment by BrunoTCouto** [comment]
![image](https://github.com/minio/minio/assets/23619646/ef84bd45-b229-4b76-99b8-53abca870e2b)

**Comment by BrunoTCouto** [comment]
You can ignore `com.centurylinklabs.watchtower.enable`, he monitors docker apps and updates them when new images are available. He updated today in morning the image and thats why I found the issue

**Comment by harshavardhana** [comment]
> You can ignore `com.centurylinklabs.watchtower.enable`, he monitors docker apps and updates them when new images are available. He updated today in morning the image and thats why I found the issue

yeah, I don't see it, unfortunately. There is nothing special in your config. Unless your data itself is not available. Can you try first with `mc ls alias/images` if that works?

**Comment by harshavardhana** [comment]
Also when you run curl to your `localhost:3000/images` can you run `mc admin trace -v alias/` and share it here?

**Comment by BrunoTCouto** [comment]
Found the issue ! I had a ``/`` on the start of my prefix, removing it makes everything works fine.

Example:

In my code, it was like this

```ts
const listObjects = this.minioClient.listObjectsV2(
  'images',
  `/${id}/${prefix}`,
  true,
);
```

Removing the slash 
```ts
const listObjects = this.minioClient.listObjectsV2(
  'images',
  `${id}/${prefix}`,
  true,
);
```

**Comment by BrunoTCouto** [comment]
Maybe this is related https://github.com/minio/minio/pull/17373

**Comment by harshavardhana** [comment]
Yes that is correct, and its behaving as expected. We were wrongly trimming the leading `/` - we cannot do that anymore due to AWS S3 compliance reasons.

**Comment by BrunoTCouto** [comment]
Thank you @harshavardhana ! 🎉
