### ISSUE TITLE
SignatureDoesNotMatch while response-content-disposition contains & 

### ISSUE THREAD

**Issue by TestMsr** [minio/minio#17390]
## NOTE
presigned url with & in response-content-disposition cause download  failed

## Expected Behavior

download succes with correct filename
## Current Behavior

minio return SignatureDoesNotMatch
## Possible Solution

 the preSignatureV2 func use unescaped queries and then join with &
 if using url.QueryEscape with filename ,the request can be successful, but there is document in s3 to show these value shoud be escaped
## Steps to Reproduce (for bugs)

1.generate url with minio-go
v := url.Values{}
v.Set("response-content-disposition", "file&name")
fmt.Println(minioClient.PresignedGetObject(context.Background(), "bucket", "obj", time.Hour, v))
2.get object with presigned url
3.minio return SignatureDoesNotMatch 

## Your Environment

* Version used (`minio --version`):RELEASE.2023-06-02T23-17-26Z (go1.19.9 linux/amd64)
* Server setup and configuration: docker run -p 9000:9000 -p 9001:9001   quay.io/minio/minio server /data --console-address ":9001"
* Operating System and version (`uname -a`):Linux DELL-PC 5.15.90.1-microsoft-standard-WSL2  x86_64 x86_64 x86_64 GNU/Linux

**Comment by jiuker** [comment]
@TestMsr  I'm using the latest minio-go v7.0.56 and minio RELEASE.2023-06-02T23-17-26Z  it doesn't reproduce your issue. could you post the minimized reproduction code, I'll see if it's for other reasons. Thank you very much.

**Comment by jiuker** [comment]
And here is the test code:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/url"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	ctx := context.Background()
	endpoint := "127.0.0.1:9000"
	accessKeyID := "minioadmin"
	secretAccessKey := "minioadmin"
	useSSL := false

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln(err)
	}

	// Make a new bucket called mymusic.
	bucketName := "mytest"
	v := url.Values{}
	v.Set("response-content-disposition", "file&name")
	fmt.Println(minioClient.PresignedGetObject(ctx, bucketName, "R-C.jfif", time.Hour, v))
}

```
go.mod
```go
require github.com/minio/minio-go/v7 v7.0.56
```
ouput:
```log
http://127.0.0.1:9000/mytest/R-C.jfif?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20230610%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230610T130332Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&response-content-disposition=file%26name&X-Amz-Signature=b7c0ca2f517503e1059dc31bdf11ebb7f2c1a170988e5e3adebc55a24fe2a3be 
```
response-content-disposition are escaped. That's no problem here.
And the url I can download success.
@TestMsr

**Comment by jiuker** [comment]
@TestMsr the PR don't match your case.

**Comment by TestMsr** [comment]
> And here is the test code:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"log"
> 	"net/url"
> 	"time"
> 
> 	"github.com/minio/minio-go/v7"
> 	"github.com/minio/minio-go/v7/pkg/credentials"
> )
> 
> func main() {
> 	ctx := context.Background()
> 	endpoint := "127.0.0.1:9000"
> 	accessKeyID := "minioadmin"
> 	secretAccessKey := "minioadmin"
> 	useSSL := false
> 
> 	// Initialize minio client object.
> 	minioClient, err := minio.New(endpoint, &minio.Options{
> 		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
> 		Secure: useSSL,
> 	})
> 	if err != nil {
> 		log.Fatalln(err)
> 	}
> 
> 	// Make a new bucket called mymusic.
> 	bucketName := "mytest"
> 	v := url.Values{}
> 	v.Set("response-content-disposition", "file&name")
> 	fmt.Println(minioClient.PresignedGetObject(ctx, bucketName, "R-C.jfif", time.Hour, v))
> }
> ```
> 
> go.mod
> 
> ```go
> require github.com/minio/minio-go/v7 v7.0.56
> ```
> 
> ouput:
> 
> ```
> http://127.0.0.1:9000/mytest/R-C.jfif?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20230610%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230610T130332Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&response-content-disposition=file%26name&X-Amz-Signature=b7c0ca2f517503e1059dc31bdf11ebb7f2c1a170988e5e3adebc55a24fe2a3be 
> ```
> 
> response-content-disposition are escaped. That's no problem here. And the url I can download success. @TestMsr
Thanks for your reply.
Use credentials.NewStaticV2 instead,and it can be reproduced.

**Comment by TestMsr** [comment]
@jiuker use credentials.NewStaticV2 instead , and it can be reproduced with your code.

**Comment by jiuker** [comment]
Yes, It reproduced. @TestMsr

**Comment by harshavardhana** [comment]
> @jiuker use credentials.NewStaticV2 instead , and it can be reproduced with your code.

Signature V2 is deprecated, AWS has no real guidelines on special characters for signature V2.

Please use signature v4.
