### ISSUE TITLE
Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed

### ISSUE THREAD

**Issue by yangbeibei69** [minio/minio#17415]
## Expected Behavior
I want to put the object in my bucket,But from time to time will be wrong，Not all file uploads will go wrong.

## Current Behavior
Use java SDK to upload through putObject

## Possible Solution
I don't know.

## Steps to Reproduce (for bugs)
<img width="544" alt="WechatIMG46" src="https://github.com/minio/minio/assets/41147542/742b4c43-ee0d-4acc-a8ad-1893fca837e7">
<img width="818" alt="image" src="https://github.com/minio/minio/assets/41147542/b7c07321-28b9-40ab-8255-1bffeafaf999">

## Context
Minio uses docker to deploy, mapping directory:/work/workspace/minio/data:/data,/work belongs to/dev/vdb1, showing that 900G is available

df -h：
![WX20230614-114005@2x](https://github.com/minio/minio/assets/41147542/bf92e363-d181-4f3e-bc27-4cce3a380d31)

df - i：
![WX20230614-114111@2x](https://github.com/minio/minio/assets/41147542/cfd4843f-5947-4294-a0ce-0651f29e243b)

## Regression
I don't know, may be it was before.

## Your Environment

* Version used (`minio --version`):
`minio version RELEASE.2022-01-04T07-41-07Z`
* Server setup and configuration:
`docker deployment, stand-alone`
* Operating System and version (`uname -a`)
`Linux work01 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
are you using ext4? @yangbeibei69

**Comment by yangz1h** [comment]
> ext4

Yes, using ext4

**Comment by harshavardhana** [comment]
ext4 has a limitation, use our recommended XFS backend filesystem.
