### ISSUE TITLE
Copy files using mc cp sometimes gives me errors like 'Object does not exist' or 'Resource requested is unreadable, please reduce your request rate'

### ISSUE THREAD

**Issue by aronchanisme** [minio/minio#17413]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

**The issue is about coping a file of 550g using `mc cp` to minio. It should work properly while it doesn't in my case.**

I have deployed a cluster of minio via minio operator onto my k8s environment. It's a single tenant with 2 pools. One pool contains 12 server replicas scheduled on a node with 4 drives per replica and the size of every drives is 31 GB, and the other pool containers 12 server replicas scheduled on 3 different nodes with 4 drives per  replica and the size of every drives is 19 GB.

The topology looks like this,
```bash
# pool-0
host-5:  12 server repliacs, 3 disk with 4 pvs per server, each pv is of size 31GB
# pool-2
host-6: 4 server repliacs, 1 disk with 4 pvs per server, each pv is of size 19GB
host-7: 4 server repliacs, 1 disk with 4 pvs per server,, each pv is of size 19GB
host-9: 4 server repliacs, 1 disk with 4 pvs per server,, each pv is of size 19GB
```

In total, the raw capacity is 2.3TB, while the usable capacity is 1.6TB
<img width="631" alt="image" src="https://github.com/minio/minio/assets/46433151/4a429845-42d0-46e5-9fa6-f04034e0f58e">
<img width="1273" alt="image" src="https://github.com/minio/minio/assets/46433151/ce02ff3f-d7bb-4d86-a1c0-8db24121640b">

The csi I use is minio directpv.

versions:
```bash
minio-operator-4.4.27
minio-tenant-4.4.27
mc --version
mc version RELEASE.2023-02-28T00-12-59Z (commit-id=5fbe8c26bab5592f0bc521db00665f8670a0fb31)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## Current Behavior

I failed to copy the big file using `mc cp` to minio. I set the minio endpoint to minio svc ip. 
```bash
root@HOST-10-206-32-16:/tmp/# cat /root/.mc/config.json
{
        "version": "10",
        "aliases": {
                "gcs": {
                        "url": "https://storage.googleapis.com",
                        "accessKey": "YOUR-ACCESS-KEY-HERE",
                        "secretKey": "YOUR-SECRET-KEY-HERE",
                        "api": "S3v2",
                        "path": "dns"
                },
                "local": {
                        "url": "http://localhost:9000",
                        "accessKey": "",
                        "secretKey": "",
                        "api": "S3v4",
                        "path": "auto"
                },
                "minio": {
                        "url": "http://10.96.3.201:80",
                        "accessKey": "******",
                        "secretKey": "******",
                        "api": "S3v4",
                        "path": "auto"
                },
                "play": {
                        "url": "https://play.min.io",
                        "accessKey": "Q3AM3UQ867SPQQA43P2F",
                        "secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
                        "api": "S3v4",
                        "path": "auto"
                },
                "s3": {
                        "url": "https://s3.amazonaws.com",
                        "accessKey": "YOUR-ACCESS-KEY-HERE",
                        "secretKey": "YOUR-SECRET-KEY-HERE",
                        "api": "S3v4",
                        "path": "dns"
                }
        }
}
```

```bash
root@HOST-10-206-32-16:/tmp/# k get svc -nminio-mo 
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
minio            NodePort    10.96.3.201   <none>        80:32177/TCP   5d22h
minio1-console   ClusterIP   10.96.2.238   <none>        9090/TCP       5d22h
minio1-hl        ClusterIP   None          <none>        9000/TCP       5d22h
root@HOST-10-206-32-16:/tmp/# k get ep -nminio-mo 
NAME             ENDPOINTS                                                                  AGE
minio            100.78.216.197:9000,100.78.216.198:9000,100.78.216.199:9000 + 21 more...   5d22h
minio1-console   100.78.216.197:9090,100.78.216.198:9090,100.78.216.199:9090 + 21 more...   5d22h
minio1-hl        100.78.216.197:9000,100.78.216.198:9000,100.78.216.199:9000 + 21 more...   5d22h
root@HOST-10-206-32-16:/tmp/# k get pod -nminio-mo -owide
NAME               READY   STATUS    RESTARTS        AGE     IP               NODE               NOMINATED NODE   READINESS GATES
minio1-pool-0-0    1/1     Running   0               3d11h   100.81.166.244   host-10-206-32-5   <none>           <none>
minio1-pool-0-1    1/1     Running   0               5d22h   100.81.166.205   host-10-206-32-5   <none>           <none>
minio1-pool-0-10   1/1     Running   0               5d22h   100.81.166.210   host-10-206-32-5   <none>           <none>
minio1-pool-0-11   1/1     Running   1 (5d22h ago)   5d22h   100.81.166.211   host-10-206-32-5   <none>           <none>
minio1-pool-0-2    1/1     Running   0               5d22h   100.81.166.200   host-10-206-32-5   <none>           <none>
minio1-pool-0-3    1/1     Running   0               5d22h   100.81.166.201   host-10-206-32-5   <none>           <none>
minio1-pool-0-4    1/1     Running   0               5d22h   100.81.166.204   host-10-206-32-5   <none>           <none>
minio1-pool-0-5    1/1     Running   0               5d22h   100.81.166.202   host-10-206-32-5   <none>           <none>
minio1-pool-0-6    1/1     Running   0               5d22h   100.81.166.207   host-10-206-32-5   <none>           <none>
minio1-pool-0-7    1/1     Running   0               5d22h   100.81.166.206   host-10-206-32-5   <none>           <none>
minio1-pool-0-8    1/1     Running   0               5d22h   100.81.166.208   host-10-206-32-5   <none>           <none>
minio1-pool-0-9    1/1     Running   0               5d22h   100.81.166.209   host-10-206-32-5   <none>           <none>
minio1-pool-1-0    1/1     Running   0               5d22h   100.78.216.197   host-10-206-32-9   <none>           <none>
minio1-pool-1-1    1/1     Running   0               5d22h   100.96.188.7     host-10-206-32-7   <none>           <none>
minio1-pool-1-10   1/1     Running   0               5d22h   100.96.188.10    host-10-206-32-7   <none>           <none>
minio1-pool-1-11   1/1     Running   0               5d22h   100.81.88.9      host-10-206-32-6   <none>           <none>
minio1-pool-1-2    1/1     Running   1 (5d22h ago)   5d22h   100.81.88.6      host-10-206-32-6   <none>           <none>
minio1-pool-1-3    1/1     Running   0               5d22h   100.78.216.198   host-10-206-32-9   <none>           <none>
minio1-pool-1-4    1/1     Running   0               5d22h   100.96.188.8     host-10-206-32-7   <none>           <none>
minio1-pool-1-5    1/1     Running   0               5d22h   100.81.88.7      host-10-206-32-6   <none>           <none>
minio1-pool-1-6    1/1     Running   0               5d22h   100.78.216.200   host-10-206-32-9   <none>           <none>
minio1-pool-1-7    1/1     Running   0               5d22h   100.96.188.9     host-10-206-32-7   <none>           <none>
minio1-pool-1-8    1/1     Running   0               5d22h   100.81.88.8      host-10-206-32-6   <none>           <none>
minio1-pool-1-9    1/1     Running   0               5d22h   100.78.216.199   host-10-206-32-9   <none>           <none>
```

When I use `mc cp` to copy this file from linux os to minio, it gives me errors. Sometimes it's 'Object does not exist', while others it might be like 'Resource requested is unreadable, please reduce your request rate'
<img width="1479" alt="image" src="https://github.com/minio/minio/assets/46433151/92aa840a-88ec-47e8-92d4-fdc343089ae5">
<img width="1472" alt="image" src="https://github.com/minio/minio/assets/46433151/1485055e-ac78-4a8a-9f55-6bc230ef33ca">

I've checked the logs of minio servers but I failed to find some useful information. Attaching the logs.
[minio-mo-log.tar.gz](https://github.com/minio/minio/files/11741370/minio-mo-log.tar.gz)

<img width="1508" alt="image" src="https://github.com/minio/minio/assets/46433151/73906001-108a-4cea-9915-d88bbfabcf08">

## Possible Solution
 not sure if it's related to the relationship between file size and the usable capacity of minio? I reduce the file size, and sometimes the copy works.
 

## Steps to Reproduce (for bugs)

1. Install a minio tenant in a k8s cluster with topology stated as above
2. download mc and set configs with minio endpoints to svc ip
3. prepare some data with big size, like 550g
4. copy the file to minio using `mc cp`

## Context
 private testing
 i 

## Regression
 no

## Your Environment

* Version used (`minio --version`): See above
* Server setup and configuration: See above
* Operating System and version (`uname -a`): `Linux HOST-10-206-32-16 5.10.0-0.deb10.19-amd64 #1 SMP Debian 5.10.149-2~deb10u1 (2022-10-28) x86_64 GNU/Linux`

**Comment by klauspost** [comment]
> the size of every drives is 31 GB

This puts a limit on the maximum object size you can upload. Drives this small are pretty much useless.

What you are seeing is expected behavior.

**Comment by aronchanisme** [comment]
> > the size of every drives is 31 GB
> 
> This puts a limit on the maximum object size you can upload. Drives this small are pretty much useless.
> 
> What you are seeing is expected behavior.

Thanks a lot for the quick reply. However I am still a little bit confused why minio has such a limit on the size of the object to put? Because as per my knowledge, minio should stored the object into pieces, but not a big file on the drive, it that right? If minio does have a limitation regarding the object size, then what's the relationship between drive size and object size? Sometines I can upload an object of 99GB to my minio cluster, while sometimes I failed. What's the reason behind then?

**Comment by klauspost** [comment]
> minio should stored the object into pieces

Objects are not spread across sets. See https://min.io/docs/minio/kubernetes/upstream/operations/concepts/architecture.html and following.

We are experimenting with [spreading object parts across sets](https://github.com/minio/minio/pull/15781). But no conclusion yet.

If you need more information you can write `hello@min.io` and we can help you set up a production ready cluster.

**Comment by aronchanisme** [comment]
> > minio should stored the object into pieces
> 
> Objects are not spread across sets. See https://min.io/docs/minio/kubernetes/upstream/operations/concepts/architecture.html and following.
> 
> We are experimenting with [spreading object parts across sets](https://github.com/minio/minio/pull/15781). But no conclusion yet.
> 
> If you need more information you can write `hello@min.io` and we can help you set up a production ready cluster.

Thank you Kluas. I understand now, that a specific object is stored on a specific erasure set. In this case I need to calculate the size of an erasure set in my cluster to figure out how big an object I can put into minio. It seems like this, 
1. pool-0: 12 servers with 4 pvs per server, and each pv is 31g, then raw capacity should be 31g * 12 = 372g. Considering erasure ratio(which I caculated from usable size and raw size on the web console, is 69%), then the usable size of one set in pool-0 should be 372g * 69% = 256g.
2. pool-1: the result is 157g, if my calculation is correct.

So I assume in my case the limit is 256g for a single object. Please kindly help correct me in case I missed anything. Again thanks a lot for your help.

**Comment by klauspost** [comment]
> So I assume in my case the limit is 256g for a single object. 

Assuming it is the only object in the set, it sounds reasonable without checking the math.

**Comment by aronchanisme** [comment]
> > So I assume in my case the limit is 256g for a single object.
> 
> Assuming it is the only object in the set, it sounds reasonable without checking the math.

Got it, thank you.
