### ISSUE TITLE
Rebalance causes server not initialized crash

### ISSUE THREAD

**Issue by hrenard** [minio/minio#17421]
Hi,

I just added 2 pools on my cluster and started a rebalance but now one of my original node crashes at startup.

## Expected Behavior
The node should start, or I should be able to take manual steps to fix it.

## Current Behavior
```
sidecar 2023/06/14 09:28:20 sidecar.go:48: Starting Sidecar
minio 
minio API: SYSTEM()
minio Time: 09:28:21 UTC 06/14/2023
minio Error: Server not initialized, please try again (*errors.errorString)
minio        6: internal/logger/logger.go:258:logger.LogIf()
minio        5: internal/logger/logger.go:385:logger.CriticalIf()
minio        4: cmd/bucket-object-lock.go:47:cmd.(*BucketObjectLockSys).Get()
minio        3: cmd/erasure-server-pool-rebalance.go:439:cmd.(*erasureServerPools).rebalanceBucket()
minio        2: cmd/erasure-server-pool-rebalance.go:397:cmd.(*erasureServerPools).rebalanceBuckets()
minio        1: cmd/erasure-server-pool-rebalance.go:814:cmd.(*erasureServerPools).StartRebalance.func1()
minio panic: (struct {}) 0x654e0a8
minio 
minio goroutine 382 [running]:
minio github.com/minio/minio/internal/logger.CriticalIf(...)
minio     github.com/minio/minio/internal/logger/logger.go:386
minio github.com/minio/minio/cmd.(*BucketObjectLockSys).Get(0x4f65b80?, {0xc000169200, 0x11})
minio     github.com/minio/minio/cmd/bucket-object-lock.go:47 +0x16c
minio github.com/minio/minio/cmd.(*erasureServerPools).rebalanceBucket(0xc0020524d0, {0x4f65b80, 0xc002d08f80}, {0xc000169200, 0x11}, 0x0)
minio     github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:439 +0x156
minio github.com/minio/minio/cmd.(*erasureServerPools).rebalanceBuckets(0xc0020524d0, {0x4f65b80?, 0xc002d08f80}, 0x0)
minio     github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:397 +0x245
minio github.com/minio/minio/cmd.(*erasureServerPools).StartRebalance.func1(0x6749336244523363?)
minio     github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:814 +0x6a
minio created by github.com/minio/minio/cmd.(*erasureServerPools).StartRebalance
minio     github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:812 +0x2ab
```

## Steps to Reproduce (for bugs)
1. Expand the cluster of 1 pool to 3 pools.
2. Run `mcli admin rebalance start`.
3. 1 node is crashing.

## Regression
I don't know.

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-06-09T07-32-12Z`
* Server setup and configuration: k8s `v1.26.5` with the minio operator `v5.0.5`

**Comment by jiuker** [comment]
@hrenard `Expand the cluster of 1 pool to 3 pools.` How to expand it.

**Comment by jiuker** [comment]
@hrenard Any logs on the node restart?

**Comment by jiuker** [comment]
Because it is still balancing (this balancing information has been saved) but you restarted the node because there is a problem with the boot order causing this problem. From my point of view I can't think of anything that would solve your current problem, but you could delete a file with the rebalance information for each node, it's in `.minio.sys/rebalance.bin` , I'm not sure what that would entail. @hrenard @harshavardhana @klauspost

**Comment by klauspost** [comment]
@jiuker Yes, but it should never crash, so there is a check missing somewhere.

**Comment by hrenard** [comment]
Okay, I just did a `mc admin rebalance stop` and the server properly started. But when I do a `mc admin rebalance start`, the same server (pool 0, node 0) crashes instantly.
```
panic: runtime error: integer divide by zero

goroutine 238530 [running]:
github.com/minio/minio/cmd.(*rebalanceStats).update(...)
	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:66
github.com/minio/minio/cmd.(*erasureServerPools).updatePoolStats(_, _, {_, _}, {{0xc00e18b1d0, 0x11}, {0xc00cabab90, 0x44}, {0x0, 0x0}, ...})
	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:186 +0x1f4
github.com/minio/minio/cmd.(*erasureServerPools).rebalanceBucket.func2({{0xc00cabab90, 0x44}, {0xc008fc9b00, 0x21c, 0x21c}, 0xc01b7bb200, 0x0})
	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:544 +0xad8
created by github.com/minio/minio/cmd.(*erasureServerPools).rebalanceBucket.func3.1
	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:631 +0x13e
```
If I understand correctly there are 2 issues : the crash at rebalance start and the boot ordering.

**Comment by jiuker** [comment]
> Okay, I just did a `mc admin rebalance stop` and the server properly started. But when I do a `mc admin rebalance start`, the same server (pool 0, node 0) crashes instantly.
> 
> ```
> panic: runtime error: integer divide by zero
> 
> goroutine 238530 [running]:
> github.com/minio/minio/cmd.(*rebalanceStats).update(...)
> 	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:66
> github.com/minio/minio/cmd.(*erasureServerPools).updatePoolStats(_, _, {_, _}, {{0xc00e18b1d0, 0x11}, {0xc00cabab90, 0x44}, {0x0, 0x0}, ...})
> 	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:186 +0x1f4
> github.com/minio/minio/cmd.(*erasureServerPools).rebalanceBucket.func2({{0xc00cabab90, 0x44}, {0xc008fc9b00, 0x21c, 0x21c}, 0xc01b7bb200, 0x0})
> 	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:544 +0xad8
> created by github.com/minio/minio/cmd.(*erasureServerPools).rebalanceBucket.func3.1
> 	github.com/minio/minio/cmd/erasure-server-pool-rebalance.go:631 +0x13e
> ```
> 
> If I understand correctly there are 2 issues : the crash at rebalance start and the boot ordering.

And it will restart normal? @hrenard

**Comment by hrenard** [comment]
Yes, when the rebalance is stopped.
