### ISSUE TITLE
Minio randomly ignores and not answer on http requests. (error 499 very often)

### ISSUE THREAD

**Issue by antoxa9898** [minio/minio#17431]
## NOTE

When i am looking at minio trace, i see a lot of 499 errors.

## Expected Behavior
Previously we used version RELEASE.2022-06-03T01-40-53Z and everything was ok.

## Current Behavior
Now we are using version RELEASE.2023-06-09T07-32-12Z
We are using minio as s3 backend for restic. and because of bug in restic it stucks periodically - https://github.com/restic/restic/issues/4193
We dont have this problem on older version of minio. So on new verion when i was trying to troubleshoot what is the problem, after making tcpdump and minio trace i determine that periodically minio reсeives http request and never answer to it.
Unfortunatelly restic dont retry this request. i tried to copy buckets between two minio instances using mc mirror and seen same behaviour - minio stucks on some requests, but mc mirror handles this problem and retry stucked request. This cause 499 error in minio trace. So this is not critical bug but it affects performance, because in case of request stucking mc waits for timeout and retries request.

## Steps to Reproduce (for bugs)

1. install 2 minio instances RELEASE.2023-06-09T07-32-12Z using docker container
2. create bucket on one of instances and fill it with a lot of data - 2-3TB
3. try to mc mirror this bucket from one instance to another
4. run "minio-client admin trace minio | grep 499" in background and you will see periodically 499 errors.
my log for example:
`2023-06-15T11:21:25.226 [499 ] s3.ListObjectsV2 backup2-ti.infra:9000/adru-live-backup-bucket/?continuation-token=ZGF0YS9kNi9kNjI3ZTE3NzNkNTUyNjg0OWJjNTE3ZmQ4ZjdkMGQ5NDdjYzJlMzFjODVlNDFiMjI4NDBhMzMyNTk5MDg5Njc1W21pbmlvX2NhY2hlOnYyLGlkOjMxZDI5NzFkLTIyNzUtNDM5Ny04OTA0LTczMzJmMmMzYzEwMyxwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F  *ip address deleted*    10.288406s   ↑ 93 B ↓ 363 B
2023-06-15T11:21:35.228 [200 OK] s3.ListObjectsV2 backup2-ti.infra:9000/adru-live-backup-bucket/?continuation-token=ZGF0YS9kNi9kNjI3ZTE3NzNkNTUyNjg0OWJjNTE3ZmQ4ZjdkMGQ5NDdjYzJlMzFjODVlNDFiMjI4NDBhMzMyNTk5MDg5Njc1W21pbmlvX2NhY2hlOnYyLGlkOjMxZDI5NzFkLTIyNzUtNDM5Ny04OTA0LTczMzJmMmMzYzEwMyxwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F  *ip address deleted*    7.687774s    ↑ 93 B ↓ 65 KiB`

## Regression
Yes. Problem not appear in version RELEASE.2022-06-03T01-40-53Z and appears after update to  RELEASE.2023-06-09T07-32-12Z 

## Your Environment

* Version used (`minio --version`): "release": "RELEASE.2023-06-09T07-32-12Z"
* Server setup and configuration:  minio installed in docker container
* Operating System and version (`uname -a`): Linux backup2-ti 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
499 is logged when the client disconnects a call before the response is ready.

` 10.288406s` indicates you have a 10 second timeout either somewhere in a load balancer or on the client.

**Comment by antoxa9898** [comment]
Hi, @klauspost 
10 seconds is timeout for client to disconnect if responce is not ready. but when we use restic which have no this timeout(because of bug). he can be stucked for days untill i stop client manually. for example log, when i stopped restic after 3 minutes of stucking:
`backup2-ti.infra:9000 [REQUEST s3.ListObjectsV2] [2023-06-13T13:42:29.573] [Client IP: *ip address deleted*]
backup2-ti.infra:9000 GET /gitlabce-ti-backup-bucket/?continuation-token=ZGF0YS84Ni84NmUwYjJkNmM5MjQyN2Y4NDc5ODQxMTY2NzM1ZWQ5MTQ1MjJkYmQ2ODJiMWIyOGU0YTQ4OWQ1YjEzNjBlODk3W21pbmlvX2NhY2hlOnYyLGlkOjgwNjg0OGQ5LTIyZmUtNGVhMS04Y2UwLTNiMjY0ZmUzMzE5NixwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F
backup2-ti.infra:9000 Proto: HTTP/1.1
backup2-ti.infra:9000 Host: backup2-ti.infra:9000
backup2-ti.infra:9000 User-Agent: MinIO (linux; amd64) minio-go/v7.0.47
backup2-ti.infra:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
backup2-ti.infra:9000 X-Amz-Date: 20230613T104229Z
backup2-ti.infra:9000 Accept-Encoding: gzip
backup2-ti.infra:9000 Authorization: AWS4-HMAC-SHA256 Credential=dWxauUZH/20230613/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=aada23c508a179ff134f02102b76c0bfa637185c45631209e91f4e390fcf1e7a
backup2-ti.infra:9000 Content-Length: 0
backup2-ti.infra:9000 
backup2-ti.infra:9000 [RESPONSE] [2023-06-13T13:46:16.205] [ Duration 3m46.632326s  ↑ 93 B  ↓ 367 B ]
backup2-ti.infra:9000 499 
backup2-ti.infra:9000 Accept-Ranges: bytes
backup2-ti.infra:9000 Content-Length: 367
backup2-ti.infra:9000 Server: MinIO
backup2-ti.infra:9000 X-Xss-Protection: 1; mode=block
backup2-ti.infra:9000 X-Amz-Id-2: 72d75f981226cb333f11a6c3814d7d44cb08a9ccb747a25480b7b374a6305174
backup2-ti.infra:9000 X-Amz-Request-Id: 176831EBDEB1EB48
backup2-ti.infra:9000 X-Content-Type-Options: nosniff
backup2-ti.infra:9000 Content-Security-Policy: block-all-mixed-content
backup2-ti.infra:9000 Content-Type: application/xml
backup2-ti.infra:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
backup2-ti.infra:9000 Vary: Origin,Accept-Encoding
backup2-ti.infra:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ClientDisconnected</Code><Message>Client disconnected before response was ready</Message><BucketName>gitlabce-ti-backup-bucket</BucketName><Resource>/gitlabce-ti-backup-bucket/</Resource><RequestId>176831EBDEB1EB48</RequestId><HostId>72d75f981226cb333f11a6c3814d7d44cb08a9ccb747a25480b7b374a6305174</HostId></Error>
backup2-ti.infra:9000` 
Here we se same error and 3 minutes response duration - 3m46.632326s
I think its not normal situation. It seems that minio will never answer on this request.  Duration can be as big as long as restic runs, untill i stop it.

**Comment by klauspost** [comment]
Listing speed depends on your hardware.

If you are experiencing it stops responding (and not just slow), your backend filesystem stopped responding. This can be seen on non-supported file systems like NFS.

**Comment by antoxa9898** [comment]
we are using ext4 as fs. it not respond only on 1 random request, if client retries request it will respond normally. i tested it on same server with version RELEASE.2022-06-03T01-40-53Z and this problem not appear, then i changed version to RELEASE.2023-06-09T07-32-12Z and problem appers. then i downgraded it back to RELEASE.2022-06-03T01-40-53Z and problem dissapeared. so i thought it is not fs or hardware problem.

**Comment by klauspost** [comment]
That commit range is a bit too wide to give any real information.

**Comment by antoxa9898** [comment]
@klauspost hello again. i tested some versions in this range and determine, that problen not appears in version minio/minio:RELEASE.2022-08-08T18-34-09Z and appears in version minio/minio:RELEASE.2022-08-11T04-37-28Z
this are two neghbour versions. I read changes for problem version and suppose that problem is in this PR https://github.com/minio/minio/pull/15509
Can you please check it?

**Comment by klauspost** [comment]
@antoxa9898 If the PR above is the issue, your drives are indeed hanging.

**Comment by antoxa9898** [comment]
Hi, @klauspost. I was investigating this issue more and found very strange pattern. now i updated to version - RELEASE.2023-08-09T23-30-22Z and have new behaviour. Problem appears randomly and only on s3.ListObjectsV2 operation, and when it appears i see that usually 4 requests goes normally - about 80-100ms and 5th request goes long, for about a minute. its very strange and not seems like hardware problem. You can found this pattern in my minio trace in attach.
[minio-trace.txt](https://github.com/minio/minio/files/12336882/minio-trace.txt)

**Comment by harshavardhana** [comment]
@antoxa9898 you should take a more detailed trace such as `mc admin trace -a --response-duration 1s`

**Comment by antoxa9898** [comment]
hi, @harshavardhana. trace made by your command in attach - 
[minio-trace1.txt](https://github.com/minio/minio/files/12342557/minio-trace1.txt)

**Comment by antoxa9898** [comment]
@harshavardhana i found really weird request time - `2023-08-15T11:34:36.500 [499 ] s3.ListObjectsV2 backup2-ti.infra:9000/pgsql-live-ti-backup-bucket/?continuation-token=ZGF0YS8yZi8yZjBmNmEwMDI3NzU5NzM2ZmE3ZmJiNjZmNGE2MzE0YjQ0ZjdhMzY4YjgwYzMyYmVmZjdhZjI2NmQ4YTk1NzRjW21pbmlvX2NhY2hlOnYyLGlkOjU0ZjZlYTg2LTVmODgtNDUwYS04MGE3LWY3MTNkYzQyZmY1YixwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F  10.10.1.20      41m49.233398s  ⇣  41m49.233353443s       ↑ 93 B ↓ 371 B`
499 - because i manually stopped process which was waiting for reply from minio.

**Comment by harshavardhana** [comment]
I think this bug is because of this #17855

**Comment by harshavardhana** [comment]
> hi, @harshavardhana. trace made by your command in attach - [minio-trace1.txt](https://github.com/minio/minio/files/12342557/minio-trace1.txt)

From the trace it shows that drives are also a bit on the slower side.

**Comment by antoxa9898** [comment]
> I think this bug is because of this #17855

Thanks for information. so we need to wait for near release?

**Comment by harshavardhana** [comment]
> > I think this bug is because of this #17855
> 
> Thanks for information. so we need to wait for near release?

Yes

**Comment by antoxa9898** [comment]
Hi, @harshavardhana. I updated today to last version of minio(2023-08-16T20:17:30Z), but seems that it not helped :( 
i found very long request, which i stoped manually again - 
`2023-08-17T12:38:57.157 [499 ] s3.ListObjectsV2 backup2-ti.infra:9000/pgsql-live-ti-backup-bucket/?continuation-token=ZGF0YS8yNy8yNzQ0OGVjMjQ4YTEyZjdlZGQ5NTQwN2JlYWY3M2E2NTI1YWEzZWVmNjU5Y2RmYjZkNzRjOTgxZjdmYTQ0ZDYwW21pbmlvX2NhY2hlOnYyLGlkOmU0ZjI5ZTZjLTA0YzQtNDU0ZS1hOTQ3LTUxM2JjMTkwMWRlOCxwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F  10.10.1.20      11m52.976345s  ⇣  11m52.976310771s       ↑ 93 B ↓ 371 B`
and a lot of requests that are longer than 1minute. You said that disks are a bit slow, but it seems that so long requets are not because of them. also i dont see r_await more than 10ms by iostat.

**Comment by harshavardhana** [comment]
> Hi, @harshavardhana. I updated today to last version of minio(2023-08-16T20:17:30Z), but seems that it not helped :( i found very long request, which i stoped manually again - `2023-08-17T12:38:57.157 [499 ] s3.ListObjectsV2 backup2-ti.infra:9000/pgsql-live-ti-backup-bucket/?continuation-token=ZGF0YS8yNy8yNzQ0OGVjMjQ4YTEyZjdlZGQ5NTQwN2JlYWY3M2E2NTI1YWEzZWVmNjU5Y2RmYjZkNzRjOTgxZjdmYTQ0ZDYwW21pbmlvX2NhY2hlOnYyLGlkOmU0ZjI5ZTZjLTA0YzQtNDU0ZS1hOTQ3LTUxM2JjMTkwMWRlOCxwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F 10.10.1.20 11m52.976345s ⇣ 11m52.976310771s ↑ 93 B ↓ 371 B` and a lot of requests that are longer than 1minute. You said that disks are a bit slow, but it seems that so long requets are not because of them. also i dont see r_await more than 10ms by iostat.

@antoxa9898 then your issue may be something very different.

Please capture `mc admin trace -a` output and share it here to see all large latencies for internal calls.

**Comment by antoxa9898** [comment]
[minio-trace2.txt](https://github.com/minio/minio/files/12371061/minio-trace2.txt)
here it is. i was capturing for about 5 minutes

**Comment by harshavardhana** [comment]
> [minio-trace2.txt](https://github.com/minio/minio/files/12371061/minio-trace2.txt) here it is. i was capturing for about 5 minutes

and did you see listing being slow during those 5mins? @antoxa9898

**Comment by antoxa9898** [comment]
yes, for example - `2023-08-17T18:06:47.957 [200 OK] s3.ListObjectsV2 backup2-ti.infra:9000/olap-win-backup-bucket/?continuation-token=ZGF0YS8yMC8yMGU3MWU0OGVkNzExOWMxODkwYmZmNmE0MzBmMTVhNGNkZmY5N2Q3MjQzNDNmMTAyZWJlY2NkMDM2YTUyMzRjW21pbmlvX2NhY2hlOnYyLGlkOmRjOTc0ODAxLTJjMGMtNGJhNy05MzE0LTU3ZTcwZWQxYmZmMixwOjAsczowXQ%3D%3D&delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=data%2F  10.10.1.22     1m52.919307s  ⇣  1m52.916220891s      ↑ 93 B ↓ 70 KiB`
line 86546 of log. and again same pattern - 4 requests of listing are about 100ms and then 1 long for about 2 mins.

**Comment by harshavardhana** [comment]
ok yeah if you see each xl.meta reads are in millisecond range @antoxa9898 


```
grep data/ ~/minio-trace2.txt | grep xl.meta | grep -v scanner | grep -v metacach | grep olap-win | grep ms | awk {'print $6'} | sed 's/ms//g' | awk '{sum += $1} END {print sum}'
106243
```

which basically 106.243 seconds to list 10k entries which actually the value you are seeing, I suspect that your drives randomly become even slower at times and client simply timesout. I don't think we can do anything here to help you beyond buying a new hardware with better IOPs guarantees. 

Normally just doing an `os.Open()` should be in microseconds, it can't be in milliseconds. If its in milliseconds you are already losing performance on the IOPs.
