### ISSUE TITLE
Wrong content type with x-amz-meta-snowball-auto-extract

### ISSUE THREAD

**Issue by jarkt** [minio/minio#17434]
I have reasons to use the undocumented x-amz-meta-snowball-auto-extract functionality, which gives the ability of uploading many files in one request.

As I noted there are issues with the content type. If I upload a .js file as part of a tar-stream, I will get the content type "binary/octet-stream".
Otherwise it's "application/x-javascript".

I cannot find a solution to set the right content type. In my opinion it should be possible to configure a manual mapping.

**Comment by harshavardhana** [comment]
We can try to auto interpret it on the server. Tar has no way to specify the right content type.

**Comment by jarkt** [comment]
I would expect the same behaviour as with single upload when no content type is explicit set.
In this case I assume the content type will be mapped at upload time not at request time.

Besides that, is it possible to expand the mapping?

**Comment by harshavardhana** [comment]
We can that's easy part.

**Comment by jarkt** [comment]
Wow. That was fast. Thank you!

But one hint. As I noted there is a difference between single upload and tar-upload. After single upload my .js file has the type
"application/x-javascript". With tar-upload it's "application/javascript".
But the right value would be "text/javascript", since the others seems to be deprecated.

Don't know the source of the values and it's also not a problem for me, but maybe it's not expected.

**Comment by harshavardhana** [comment]
https://github.com/minio/pkg/pull/69 yeah they were coming from here, I updated the mimedb to reflect the newer mime-types.
