### ISSUE TITLE
"jwt:email" OpenID Policy Variables seems to not be usable for user policy

### ISSUE THREAD

**Issue by dod-ia** [minio/minio#17447]
Hi, 

I use the OpenID connect protocol to identify an user. The user policy uses variables from the jwt token to be defined on the fly. In my case, I want to use the email but the policy behavior seems to be not correct.

All actions are from Console GUI. Suppose I have a bucket named `data` with 2 folders `user` and `user@gmail.com`. Some items are stored in them but no subfolder. My SSO returns `user` in `preferred_username` field and `user@gmail.com` in `email` field. I apply the following policy on the user:

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserToSeeBucketListInTheConsole",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "",
                        "${jwt:email}/",
                        "${jwt:preferred_username}/"
                    ]
                }
            }
        }
    ]
}
```
## Expected Behavior

I can explore `user` and `user@gmail.com` repertories.

## Current Behavior

I can explore only `user` repertory. The `user@gmail.com` repertory has a `Denied access`. If i replace `"${jwt:email}/"` with `user@gmail.com/`, the problem is still the same.

## Possible Solution

The problem can be from the @ symbol in the email string. But, if it is the problem, why authorize to use the email from the jwt token ?

## Steps to Reproduce (for bugs)

1. Create a bucket named `data`. Create an `user` and `user@gmail.com` folders inside.
2. Apply the previous policy by replacing `"${jwt:email}/"` with `user@gmail.com/` and  `${jwt:preferred_username}/` by `user/`
3. Try to explore both subfolders

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2023-06-16T02-41-06Z (commit-id=25db1e4eca2f81b760446147006fe255e240e4be)
* Server setup and configuration: docker (quay.io/minio/minio)
* Operating System and version (`uname -a`): Linux b5a4dcc04c78 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@ventaubain can you test this via `mc ls` while using the STS credentials via `MC_HOST_mysts=http://accessKey:secretKey:sessionToken@hostname:port/ mc ls mysts/bucketname/`

Generate the OpenID STS tokens via https://github.com/minio/minio/blob/master/docs/sts/web-identity.md

**Comment by dod-ia** [comment]
Hi,

It was a mistake from me. I check with ` mc` and STS (python API + policy with all rights) and I obtained that:

```data b' user@gmail.com/' None None None None
data b'755/' None None None None
data b'user/' None None None None
data b' user@gmail.com/ape.exe' 2023-06-16 17:02:52.504000+00:00 4de3f09c499b32e3ced3a0189468944c 11878400 None
data b'755/cow-icon-md (1).png' 2023-06-16 20:33:01.008000+00:00 5cc9a12878edc9fc4cc1b7914f79489f 40678 None
data b'user/8158527.png' 2023-06-16 19:00:38.736000+00:00 678d4024a4404d1316a84db35dd9fcb8 30738 None
data b'user/8158527.png' 2023-06-16 19:00:38.736000+00:00 678d4024a4404d1316a84db35dd9fcb8 30738 None
```

` data b' user@gmail.com/ape.exe' 2023-06-16 17:02:52.504000+00:00 4de3f09c499b32e3ced3a0189468944c 11878400 None`

There is **one space** at the beginning of the email... I suppose it was a missclick from me when I create the folder manually in the bucket...

After retrying with a correct name (and the correct policy), the jwt:email seems to work.

But why I can't explore the data/user@gmail.com/ folder from Minio API (work with Console)?

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserToSeeBucketListInTheConsole",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "${jwt:email}/",
                        ""
                    ]
                }
            }
        }
    ]
}
```
```
print(client.list_buckets())

objects = client.list_objects('data', prefix='user@gmail.com')
for obj in objects:
    print(obj.bucket_name, obj.object_name.encode('utf-8'), obj.last_modified,
          obj.etag, obj.size, obj.content_type)
```
```
[Bucket('data'), Bucket('ghgjg')]
minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access Denied., resource: /data, request_id: 176A08F5766F61F2, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: data
```

Sorry for my mistake and thanks for the help !

**Comment by harshavardhana** [comment]
You also need to allow delimiters, you have not specified that in your policy document.

**Comment by dod-ia** [comment]
What do you mean when you say "delimiters" ? add `"s3:delimiter":["/"]` in the `StringLike` ?
