### ISSUE TITLE
Load ./aws/credentials in container

### ISSUE THREAD

**Issue by gnkow** [minio/minio#17449]
**Is your feature request related to a problem? Please describe.**
Loading AWS credentials file in the minio container is troublesome to me. I have a ./aws/credentials file with different profiles which I want to use as the minio credentials. If I set manually the credentials to the MINIO_ROOT_USER MINIO_ROOT_PASSWORD variables I get an error using the boto3 call (showed below) due to the fact that a issued token is used.

**Describe the solution you'd like**
A simple solution would be if MINIO_PROFILE variable would be set then the credentials file defined by MINIO_CREDENTIALS_FILE (default /root/.aws/credentials) would be read loading the aws secret from that specific profile (including token?)

**Describe alternatives you've considered**
Added /root/.aws/credentials file to minio container but I think currently is not supported.

**Additional context**
The goal is to replace the calls made to AWS by our service without alteration of code base.
Currently, in order to use the service something like this must be done:

s3_target = boto3.resource('s3', 
    endpoint_url='https://<minio>:9000',
    aws_access_key_id='<key_id>',
    aws_secret_access_key='<access_key>',
    aws_session_token=None,
    config=boto3.session.Config(signature_version='s3v4'),
    verify=False
)

However I dont want to explicitly call the resource client using explicit variables but rather the profile:

s3_target = boto3.resource('s3', 
    profile='default',
    endpoint_url='https://<minio>:9000',
    config=boto3.session.Config(signature_version='s3v4'),
    verify=False
)

Then the ./aws/credential file would be mounted in both application and minio container for testing purposes. Sorry If anything I ask is really of topic or makes no sense, I'm using minio for 2 days. Love it though!

**Comment by harshavardhana** [comment]
This has nothing to do with MinIO software, we do not need or ever read `~/.aws/credentials` - that is for your application. 

Your application must run on a different container not MinIO container

**Comment by gnkow** [comment]
> This has nothing to do with MinIO software, we do not need or ever read `~/.aws/credentials` - that is for your application.
> 
> Your application must run on a different container not MinIO container

Yes, my application container is not the same as Minio container. But it uses ./aws/credentials profile to create a boto3 session and connect to AWS S3 service. However, if I just replace the endpoint_url by the minio url, it will not work out of the box since Minio uses other credentials and does not take into consideration the token. There should be a mechanism of authenticating only my credentials locally. Sad to see this issue disregarded so quickly.

**Comment by gnkow** [comment]
To simplify the whole question: I have a ./aws/credentials file at my application container which loads a session profile. How to authenticate to minio using this?
