### ISSUE TITLE
posix: Disable unreliable disks.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1744]
Posix as it stands today does not implement a way to handle disk errors.  We need to implement posix to behave in the following manner. 
- Capture and keep track of i/o errors or any disk errors. This is needed to take disk offline after more than 5 consecutive errors for i/o operations. 
- There should be a timer thread which cancels the call if it's taking too long. Also takes the disk offline if its not responding fast enough.

**Comment by harshavardhana** [comment]
This is not assigned yet.

**Comment by harshavardhana** [comment]
Assigned to @balamurugana

**Comment by balamurugana** [comment]
> There should be a timer thread which cancels the call if it's taking too long. Also takes the disk offline if its not responding fast enough.

This issue can be closed as we don't consider this issue now.
