### ISSUE TITLE
Allow PutObject directly to a tier/storage-class

### ISSUE THREAD

**Issue by ydkn** [minio/minio#17445]
**Describe the solution you'd like**
Currently creating a tier in MinIO does not allow to use this tier directly as a storage class.
It would be a nice option to directly upload an object to this tier/storage-class and therefore avoid using a ILM rule to transition the object after some time to this tier. This way it would be possible to avoid requiring more fast storage for the primary MinIO instance when it is already clear that the object needs to be moved to a MinIO instance with slower drives. 

**Additional context**
There is currently a fixed filter allow supporting the two build in storage classes.
https://github.com/minio/minio/blob/142a5b0dcda58dbc2d6649e559f3e1afa7ec6ae5/internal/config/storageclass/storage-class.go#L102

**Comment by harshavardhana** [comment]
That is outside of the scope of the design.
