### ISSUE TITLE
XL: Implement healing at object layer. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1745]
- Healing should take care of healing `format.json` if they don't exist or malformed from existing disks.
- Healing should take care of healing `xl.json` if they don't exist or malformed from existing disks.
- Healing should heal missing buckets if any. 
- Healing should also heal missing erasured blocks.

**Comment by GarimaKapoor** [comment]
Harsha can we close this issue.

**Comment by harshavardhana** [comment]
> Harsha can we close this issue.

No this issue has other things which needs to be fixed after the release. Removing this from XL milestone.

**Comment by krishnasrinivas** [comment]
deadline - 12 June.

**Comment by harshavardhana** [comment]
Moving this out of "Stable Standalone Server Release" as decided.

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the timeline for the healing fix.

**Comment by krishnasrinivas** [comment]
@GarimaKapoor this needs discussion on the API

**Comment by harshavardhana** [comment]
This has been done.
