### ISSUE TITLE
not work only in firefox (http 426)

### ISSUE THREAD

**Issue by mortifia** [minio/minio#17456]
## NOTE
yes and no (it can be avoid with apache/nginx)

## Expected Behavior
work on firefox

## Current Behavior
minio:9000/<bucket>
minio.9000/<bucket>/...

result to  error 426 in firefox only

## Possible Solution
```
# Default is HTTP/1, keepalive is only enabled in HTTP/1.1
        # proxy_http_version 1.1;
        # proxy_set_header Connection "";
        # chunked_transfer_encoding off;
        # To support websockets in MinIO versions released after January 2023
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```

please update doc 

## Steps to Reproduce (for bugs)
win 11
docker
run minio in docker

use firefox

## Your Environment

minio:lastest

**Comment by harshavardhana** [comment]
The doc is updated already, you need to enable Console port load balanced to allow websockets.
