### ISSUE TITLE
minio update error

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#17476]
when I update my minio,this error occures

## Expected Behavior

everything is ok.

## Current Behavior

![image](https://github.com/minio/minio/assets/27141040/c4f87e40-69ac-4e6c-816f-f7511b0c2f5b)

## Steps to Reproduce (for bugs)

1. ./mc admin update minio
2. after a few seconds,it shows that  Failed to parse server response: invalid character '<' looking for beginning of value.

## Context

when I use  ./mc admin update minio info,this erro occurs

## Your Environment

* Version used (`minio --version`):
mc version RELEASE.2020-08-08T02-33-58Z
* Server setup and configuration:
 ![image](https://github.com/minio/minio/assets/27141040/30ebffe1-329d-4101-9300-d4b58fb824f7)
* Operating System and version (`uname -a`):
Linux hadoop003 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You need to make sure your load balancer doesn't timeout the calls.

mc admin update can take time to download and apply the updates.

Your version is also too old, so the mc has changed the API. You should download the binary, replace it locally and restart all servers.

**Comment by kendn1993** [comment]
> You need to make sure your load balancer doesn't timeout the calls.
> 
> mc admin update can take time to download and apply the updates.
> 
> Your version is also too old, so the mc has changed the API. You should download the binary, replace it locally and restart all servers.

hello , after  I download this locally and restart,this error occures.

It shows /home/minio/data drive is already being used in another erasure deployment. how to solve this

![image](https://github.com/minio/minio/assets/27141040/a1564590-8ad3-4579-9426-cec6b91e38e4)

![image](https://github.com/minio/minio/assets/27141040/171b1495-2ead-4abf-9cdf-c825b853ea5b)

**Comment by harshavardhana** [comment]
> > You need to make sure your load balancer doesn't timeout the calls.
> > mc admin update can take time to download and apply the updates.
> > Your version is also too old, so the mc has changed the API. You should download the binary, replace it locally and restart all servers.
> 
> hello , after I download this locally and restart,this error occures.
> 
> It shows /home/minio/data drive is already being used in another erasure deployment. how to solve this
> 
> ![image](https://user-images.githubusercontent.com/27141040/248558477-a1564590-8ad3-4579-9426-cec6b91e38e4.png)
> 
> ![image](https://user-images.githubusercontent.com/27141040/248558397-171b1495-2ead-4abf-9cdf-c825b853ea5b.png)

Ellipses needs to be in sequence you can't just add ellipses for non sequential inputs

**Comment by kendn1993** [comment]
> 
i modiy like this ,this error still occures
![image](https://github.com/minio/minio/assets/27141040/47ef847e-7b3f-41ac-aa73-98c84da68679)


![image](https://github.com/minio/minio/assets/27141040/51c29f65-9a27-40fd-97ef-aff7e71bfb0f)
