### ISSUE TITLE
Is the ListObject operation a high resource consumption for Minio? 

### ISSUE THREAD

**Issue by zhufeizzz** [minio/minio#17472]
## Environment
Runtime: K8S
Minio Server: Suse12 Linux 4C8G * 3
Minio Version: RELEASE.2021-03-17T02-33-02Z

## Context
Minio Usage: 10 million objects in one bucket
Key example: model/xxx/photos/97be7d2e-cd29-11ed-b112-0255ac120130/xxx.png
Objects in one prefix: less than 100
listObject API example:  prefix=model/xxx/photos/97be7d2e-cd29-11ed-b112-0255ac120130/, maxKeys=1000, startAfter=null

## MinioConfig
```
MINIO_ENCRYPT_UTILS=xxx
MINIO_MANAGE_SERVICE_PORT=xxx
MINIO_NODE_IP=xxx
MINIO_POD_IP=xxx

{
	"version": "10",
	"aliases": {
		"local": {
			"url": "http://localhost:9000",
			"accessKey": "",
			"secretKey": "",
			"api": "S3v4",
			"path": "auto"
		}
	}
}
```

## Behavior
When the tps of the listObejct operation increase to 200/s, CPU increase to 90%, Minio create about 20000 threads exceeded pod limit and killed by k8s.

## My question
1. Is there anyway to limit max threads in Minio? Too many threads will lead to lower OS processing performance.
2. Is it recommended to perform high-frequency ListObject operations? Does Minio perform prefix index acceleration on ListObject operations？Do I need to store file meta infomation into another DB to accelerated access, like mysql?
3. Is there any other suggestions for accelerating the performance of List operations?

**Comment by harshavardhana** [comment]
ListObjects is an expensive operation, if your application is List heavy you can't limit MinIO. ListObjects is strictly consistent and requires that we reach the backend disk for readdir() etc.

@zhufeizzz please explain your setup we cannot really help you without it.

**Comment by harshavardhana** [comment]
> Minio Version:

Please state this.

**Comment by zhufeizzz** [comment]
> ListObjects is an expensive operation, if your application is List heavy you can't limit MinIO. ListObjects is strictly consistent and requires that we reach the backend disk for readdir() etc.
> 
> @zhufeizzz please explain your setup we cannot really help you without it.

@harshavardhana 
Related information has been provided.

And how to understand "ListObjects is an expensive operation"?  How does Minio store file metadata? Is there a prefix based query index.

I found that AWS S3 can provide very high listObeject TPS, just a little lower than get opeation.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html
![image](https://github.com/minio/minio/assets/4591255/3ea60c19-8032-4b12-8e5f-faf2477a24a3)

**Comment by harshavardhana** [comment]
> And how to understand "ListObjects is an expensive operation"? How does Minio store file metadata? Is there a prefix based query index.

There is no DB everything is stored on disk. Please upgrade your setup 2021 is like 3yrs ago.

**Comment by zhufeizzz** [comment]
@harshavardhana  Thanks very much for your reply, but my question is still not been answered yet.

1. Is there anyway to limit max threads in Minio? Too many threads will lead to lower OS processing performance.
2. Is it recommended to perform high-frequency ListObject operations? Do I need to store file meta infomation into another DB to accelerated access, like mysql?
3. Is there any other suggestions for accelerating the performance of List operations?

**Comment by harshavardhana** [comment]
Architecture suggestions are not for free @zhufeizzz feel free to become our customer we will provide you with all the guidance https://min.io/pricing

ListObjects performance depends on your backend disks ability to perform readdirs() if you dump all your objects flat then filesystems don't scale.

You should ideally have a hierarchical structure and also split the workload such that individual readdirs() don't go beyond 100k entries.

You must upgrade Listing() has changed dramatically over the years.

**Comment by klauspost** [comment]
1 listing operation returning 1000 results requires the same IOPS as 1000 HeadObject calls in terms of disk utilizations, so designing around frequent usage if ListObjectXX is not recommended.
