### ISSUE TITLE
Return value on delete "VersionId" is breaking clients

### ISSUE THREAD

**Issue by philipp1992** [minio/minio#17494]
## NOTE
When deleting using the javascript aws s3 client, the response that minio delivers differs from  AWS S3 and prior Minio versions, breaking the compatibly with some clients like Noobaa.

AWS S3 Response -**> no VersionId**

```
{ Deleted: [ { Key: 'test/' }, { Key: 'test/bla/' } ], Errors: [] }
```

with minio RELEASE.2023-06-19T19-52-50Z  -> **VersionID: null != undefined -> breaking compatibility**

```
{ Deleted: [ { Key: 'test/', VersionId: 'null' } ], Errors: [] }
```

with minio RELEASE.2023-01-25T00-19-54Z -**> No VersionID**

```
{ Deleted: [ { Key: 'test/' }, { Key: 'test/bla/' } ], Errors: [] }
```

## Expected Behavior
No VersionID being returned when not included in request

## Current Behavior
VersionID is being returned with value null when not included in request 

## Possible Solution
Remove the VersionID key

## Steps to Reproduce (for bugs)
```
var params = {
    Bucket: bucket, 
    Delete: {
        Objects: [
            {
                Key: 'test/',
                VersionId: undefined
            }
         
        ],
    },
};


s3.deleteObjects(params, function(err, res) {
    if (err) {
        console.log(err, err.stack); 
    }
    else {
        console.log(res);
 
    }
}).promise()
```

**Comment by vadmeste** [comment]
@philipp1992 do you know what S3 SDK Nooba is using ?

**Comment by lallinger-tech** [comment]
@vadmeste we tested it using `"aws-sdk": "2.1069.0"` but as AWS itself is not returning a VersionId in this case and MinIO did also not do it until recently, this should be fixed

**Comment by klauspost** [comment]
Possible regression from #17132 here: https://github.com/minio/minio/blob/5a1612fe32cd5aaaf99a2acdfca148c9aac0384e/cmd/bucket-handlers.go#L559-L561

**Comment by klauspost** [comment]
Assigned Harsha - My guess is that this should be cleaned up in the response, but I cannot tell for sure.
