### ISSUE TITLE
--count option for `mc find`

### ISSUE THREAD

**Issue by shoce** [minio/minio#17490]
**Is your feature request related to a problem? Please describe.**
We have millions of objects often changing in minio storage and monitoring the objects with some scripts. Often we need to count objects that are newer or older than some period (or larger or smaller than some size) and we have to do `mc find --newer-than 1d bucket/path/ | wc -l` but it is often too slow because of the big list of files traveling through network. 

**Describe the solution you'd like**
We would benefit a lot if there was an option for `find` to only output the count of the files found, without the names.

**Describe alternatives you've considered**
I have no idea of any alternatives.

**Additional context**
None.

**Comment by klauspost** [comment]
The files would have to be sent from the server anyway, which is the resource intensive part.

I don't really see a point of replacing `| wc -l` with something that will not really make any difference.

(mc find is not doing any serverside filtering)

**Comment by shoce** [comment]
> The files would have to be sent from the server anyway, which is the resource intensive part.
> 
> I don't really see a point of replacing `| wc -l` with something that will not really make any difference.

Yes, I get this. It should utilize some server api that can make the count on the server side without sending all the files names over the wire. I am not familiar with S3 api to know if there is a suitable server api function. Is there any? If there is no such, can it be added?

**Comment by harshavardhana** [comment]
There is no such provisions in S3 API.

**Comment by harshavardhana** [comment]
Your best bet is setup bucket notifications to redis by storing the entire namespace outside of MinIO. Then use that to query all you want for what you want.

**Comment by shoce** [comment]
> Your best bet is setup bucket notifications to redis by storing the entire namespace outside of MinIO. Then use that to query all you want for what you want.

Thanks for your suggestion. 

About S3 in general... this is not the bright future that i pictured when migrated from local file system storage to minio...
