### ISSUE TITLE
Will Minio over SFTP support rename operation?

### ISSUE THREAD

**Issue by zldrobit** [minio/minio#17505]
**Is your feature request related to a problem? Please describe.**
My colleagues and I use WinSCP regularly to upload files. Using WinSCP to upload file via SFTP to MinIO server will cause `*.filepart` rename errors. This is because WinSCP uploads the file with the name `*.filepart` before it is completed, and renames the file after the completion for auto resume.

**Describe the solution you'd like**
Since `mc` tool and s3 interface support rename operation, I suggest adding rename op to the SFTP interface on Minio. This will benefit the users of the popular WinSCP tool.

**Describe alternatives you've considered**
Maybe we could turn off the auto resume function in WinSCP, but it also makes the upload process more unreliable without manual intervention.

**Additional context**
![image](https://github.com/minio/minio/assets/3896992/a5dd1e4f-3213-4717-8021-6483595088ca)

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/tree/master/docs/ftp#minio-ftpsftp-server read what we support - no we are not supporting `rename()`

**Comment by harshavardhana** [comment]
> My colleagues and I use WinSCP regularly to upload files. Using WinSCP to upload file via SFTP to MinIO server will cause `*.filepart` rename errors. This is because WinSCP uploads the file with the name `*.filepart` before it is completed, and renames the file after the completion for auto resume.

Use a better client such as regular `sftp` client.

**Comment by hashworks** [comment]
In theory the SFTP implementation could use the CopyObject API and delete the old object afterward to support rename. Would that be acceptable?

EDIT: sftpgo seems to do that: https://github.com/drakkan/sftpgo/blob/main/docs/s3.md

**Comment by harshavardhana** [comment]
> In theory the SFTP implementation could use the CopyObject API and delete the old object afterward to support rename. Would that be acceptable?
> 
> EDIT: sftpgo seems to do that: https://github.com/drakkan/sftpgo/blob/main/docs/s3.md

That is exactly why we don't want to support it. Rename() is not safe and broken it is not atomic if you use two APIs.

A versioned bucket involves a more complicated implementation than a simply copy and delete.

**Comment by olljanat** [comment]
> **Describe alternatives you've considered**
> Maybe we could turn off the auto resume function in WinSCP, but it also makes the upload process more unreliable without manual intervention.

I can confirm that this method works. It is this setting in WinSCP 
![image](https://github.com/minio/minio/assets/6213926/ae8d0d7b-c9f1-4e68-8b89-208674e4e266)
