### ISSUE TITLE
Minio is performing an upgrade and has been unresponsive

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#17515]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Minio performs an upgrade without any response for up to half an hour

## Expected Behavior

upgrade success

## Current Behavior

Stuck

## Steps to Reproduce (for bugs)

1.  ./mc admin update minio --debug

## Your Environment

* Version used (`minio --version`):
![image](https://github.com/minio/minio/assets/27141040/5273d885-4bd7-4917-bb3a-edd7e0a23358)

* Server setup and configuration:
* Operating System and version (`uname -a`):
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Check/post console (log) output.

**Comment by kendn1993** [comment]
> Check/post console (log) output.





mc: <DEBUG> POST /minio/admin/v3/update?updateURL= HTTP/1.1
Host: 10.10.90.24:9333
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-08-08T02:33:58Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=admin/20230626//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230626T090536Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 275
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Mon, 26 Jun 2023 09:50:38 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 176C2A2DACF15CE9
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminUpdateApplyFailure","Message":"Post \"http://10.10.14.62:9333/minio/peer/v15/serverupdate?\": net/http: timeout awaiting response headers","Resource":"/minio/admin/v3/update","RequestId":"176C2A2DACF15CE9","HostId":"5ce445aa-1c3b-48ab-a35f-457b2e1cf45c"}
mc: <DEBUG> Response Time:  45m2.579662175s

**Comment by kendn1993** [comment]
Is it currently being downloaded? My region is in China

**Comment by klauspost** [comment]
@kendn1993 Logs on the server side. But yes, if servers are unable/very slow to download the update this cannot be used. 

Maybe try a new mc version.

**Comment by harshavardhana** [comment]
You should download the binary replace it on all nodes and restart the cluster.

mc admin update - must be used if you can download directly from dl.min.io otherwise setup a mirror locally and then do

mc admin update https://mylocalmirror/minio.sha256sum
