### ISSUE TITLE
Can't login to SFTP using Active Directory account

### ISSUE THREAD

**Issue by andy812** [minio/minio#17526]
## Expected Behavior
Login to SFTP using AD account

## Current Behavior
I can successfully login to UI using AD account, but can't login to SFTP.

## Steps to Reproduce
1. Run minio with configured LDAP/AD identity
2. Attach policy, for example
```
mc idp ldap policy entities local/
Query time: 2023-06-27T11:19:09Z
Policy -> Entity Mappings:
  Policy: consoleAdmin
    User Mappings:
      CN=Some User,OU=Accounts,DC=example,DC=com
    Group Mappings:
      CN=infra-admins,OU=Groups,OU=Accounts,DC=example,DC=com
```
3. Try to connect to SFTP:
sftp -P 8022 some.user@1.2.3.4
some.user@1.2.3.4's password:
Permission denied, please try again.

4. Minio logs:
```
API: SYSTEM()
Time: 11:20:31 UTC 06/27/2023
DeploymentID: ab7522bc-b824-4d60-a8c1-a053076aa445
Error: [ssh: no auth passed yet, Specified user does not exist, Specified user does not exist, Specified user does not exist] (*ssh.ServerAuthError)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/ftp-server.go:168:cmd.startSFTPServer()
```
But account really exists (and it's consoleAdmin), i use it to login to UI.

## Your Environment
docker-compose installation
minio/minio:RELEASE.2023-06-19T19-52-50Z

Environment variables:
```
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=**********
      - MINIO_IDENTITY_LDAP_SERVER_ADDR=1.2.3.4:389
      - MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=CN=svc-account,OU=ServiceAccounts,OU=Accounts,DC=example,DC=com
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=OU=Accounts,DC=example,DC=com
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(|(sAMAccountName=%s)(userPrincipalName=%s))
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD==**********
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectClass=group)(member=%d))
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN=OU=Accounts,DC=example,DC=com
```
`command: minio server --console-address ":9001" --sftp="address=:8022" --sftp="ssh-private-key=/opt/id_rsa" /data`

**Comment by harshavardhana** [comment]
@andy812 is your `some.user` is getting translated to your LDAP CN properly? can you try logging into Console UI with the same user and password - does that work?

**Comment by andy812** [comment]
> @andy812 is your `some.user` is getting translated to your LDAP CN properly? can you try logging into Console UI with the same user and password - does that work?

yes, it works, i use this AD account to login into Console UI.

**Comment by harshavardhana** [comment]
Okay I will check looks like something simple is missing.
