### ISSUE TITLE
file access denied

### ISSUE THREAD

**Issue by MiroslavVanicky** [minio/minio#17527]
Running on Windows 10, randomly there are these errors in console:

API: PutObject(bucket=datamovetest, object=DM_Folder_1/Organizations/9c2315eb77fa47cfbb0bc1d93caeef87/Mailboxes/22671455afb24e308b0e778250ea8825/ItemsChanges/2021/6.V0000062B)
Time: 12:26:17 UTC 06/27/2023
DeploymentID: e80d84c9-bc32-4986-9d36-5b5b064f7780
RequestID: 176C83B5DDA27098
RemoteHost: 127.0.0.1
Host: 127.0.0.1:9000
UserAgent: APN/1.0
Error: srcVolume: .minio.sys/tmp, srcPath: e472c2c2-80b1-4057-ad36-d053e26c0e1b, dstVolume: datamovetest:, dstPath: DM_Folder_1/Organizations/9c2315eb77fa47cfbb0bc1d93caeef87/Mailboxes/22671455afb24e308b0e778250ea8825/ItemsChanges/2021/6.V0000062B - error file access denied (*errors.errorString)
       6: internal\logger\logger.go:258:logger.LogIf()
       5: cmd\xl-storage.go:2167:cmd.(*xlStorage).RenameData.func1()
       4: cmd\xl-storage.go:2442:cmd.(*xlStorage).RenameData()
       3: cmd\xl-storage-disk-id-check.go:380:cmd.(*xlStorageDiskIDCheck).RenameData()
       2: cmd\erasure-object.go:797:cmd.renameData.func1()
       1: github.com\minio\pkg@v1.7.5\sync\errgroup\errgroup.go:123:errgroup.(*Group).Go.func1()

API: PutObject(bucket=datamovetest, object=DM_Folder_1/Organizations/9c2315eb77fa47cfbb0bc1d93caeef87/Mailboxes/22671455afb24e308b0e778250ea8825/ItemsChanges/2021/6.V0000062B)
Time: 12:26:17 UTC 06/27/2023
DeploymentID: e80d84c9-bc32-4986-9d36-5b5b064f7780
RequestID: 176C83B5DDA27098
RemoteHost: 127.0.0.1
Host: 127.0.0.1:9000
UserAgent: APN/1.0
Error: file access denied (cmd.StorageErr)
       7: internal\logger\logger.go:258:logger.LogIf()
       6: cmd\erasure-object.go:1325:cmd.erasureObjects.putObject()
       5: cmd\erasure-object.go:977:cmd.erasureObjects.PutObject()
       4: cmd\erasure-sets.go:753:cmd.(*erasureSets).PutObject()
       3: cmd\erasure-server-pool.go:960:cmd.(*erasureServerPools).PutObject()
       2: cmd\object-handlers.go:1885:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2109:http.HandlerFunc.ServeHTTP()

## Your Environment

* Version used (`minio --version`): RELEASE.2023-06-23T20-26-00Z (go1.19.10 windows/amd64)
* Operating System and version (`uname -a`):
Edition	Windows 10 Pro
Version	22H2
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by klauspost** [comment]
Typically this shows up when AV software holds file read locks for scanning new files.

Try disabling AV software.
