### ISSUE TITLE
XMinioAdminUpdateApplyFailure

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#17525]
Hi!

I want to update my distributed MinIO setup, but I'm getting this error message:

rename /opt/minio/.minio.old /opt/minio/..minio.old.old: no such file or directory

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2021-10-08T23-58-24Z

## Full error log
mc: <DEBUG> POST /minio/admin/v3/update?updateURL= HTTP/1.1
Host: 10.10.90.24:9333
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-08-08T02:33:58Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=admin/20230627//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230627T004827Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 275
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Tue, 27 Jun 2023 01:33:30 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 176C5DA150D9C1FF
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminUpdateApplyFailure","Message":"Post \"http://10.10.14.62:9333/minio/peer/v15/serverupdate?\": net/http: timeout awaiting response headers","Resource":"/minio/admin/v3/update","RequestId":"176C5DA150D9C1FF","HostId":"5ce445aa-1c3b-48ab-a35f-457b2e1cf45c"}
mc: <DEBUG> Response Time:  45m2.806375247s

mc: <DEBUG> POST /minio/admin/v3/update?updateURL= HTTP/1.1
Host: 10.10.90.24:9333
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-08-08T02:33:58Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=admin/20230627//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230627T013330Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 251
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Tue, 27 Jun 2023 02:18:34 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 176C60169CAA951C
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminUpdateApplyFailure","Message":"rename /opt/minio/.minio.old /opt/minio/..minio.old.old: no such file or directory","Resource":"/minio/admin/v3/update","RequestId":"176C60169CAA951C","HostId":"5ce445aa-1c3b-48ab-a35f-457b2e1cf45c"}
mc: <DEBUG> Response Time:  45m3.820310791s

**Comment by harshavardhana** [comment]
@kendn1993 you don't have enough bandwidth on your end to download directly from dl.min.io - download the binary separately and update all the servers.
