### ISSUE TITLE
sftp issue with executing commands with TLS

### ISSUE THREAD

**Issue by merewind** [minio/minio#17535]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
sftp>ls  should display list of files in sftp bucket 

## Current Behavior
sftp> ls
remote readdir("/"): Failure
- getting same error message if running any of the sftp commands for example `mkdir` 

## Possible Solution
not sure

## Steps to Reproduce (for bugs)
my understanding debugs are not available for sftp
1. login using sftp client with admin user 
2. issue ls command
3. getting the error remote readdir("/"): Failure

## Context
sftp service is un-useable for us 
## Regression
No
## Your Environment

* Version used (`minio --version`): (`minio_new version RELEASE.2023-06-23T20-26-00Z (commit-id=216069d0da24d8a8bfc885344c221a8d91fde614)
Runtime: go1.19.10 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.`)

* Server setup and configuration:
* Operating System and version (`uname -a`):
(`Linux emlog01 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by harshavardhana** [comment]
@merewind you can do `mc admin trace --call ftp` and share the results

**Comment by harshavardhana** [comment]
how did you start the sftp service? @merewind

**Comment by merewind** [comment]
(`MINIO_VOLUMES="/var/minio_volume/data"
MINIO_OPTS="--certs-dir /.minio/certs --address :9100 --console-address :9101 --sftp  address=:8022 --sftp ssh-private-key=/home/minio/.ssh/id_rsa"
MINIO_PROMETHEUS_URL="http://xx.0.203.100:6060"
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=xxx
`)

**Comment by harshavardhana** [comment]
You need to have a bucket first @merewind we do not allow creating buckets via `sftp` - first create the bucket and then you can perform `mkdir` all you want.

**Comment by merewind** [comment]
> @merewind you can do `mc admin trace --call ftp` and share the results

ok I have buckets:
 (`mc ls new
[2023-05-18 19:54:45 EDT]     0B ftp/
[2023-06-01 15:01:46 EDT]     0B loki/
[2023-05-19 11:22:28 EDT]     0B sftp/`)

(`mc admin trace --call ftp new
mc: <ERROR> Unable to start tracing: unknown call name: `ftp`.
`)

**Comment by merewind** [comment]
> You need to have a bucket first @merewind we do not allow creating buckets via `sftp` - first create the bucket and then you can perform `mkdir` all you want.

yep, I did created buckets first. please see mc ls command above

**Comment by harshavardhana** [comment]
Upgrade your `mc` also @merewind to trace `ftp` calls. 

```
sftp -P 8022 minioadmin@localhost
minioadmin@localhost's password: 
Connected to localhost.
sftp> ls
testbucket  
sftp> cd testbucket/
sftp> ls
sftp> mkdir test
sftp> ls
test  
sftp> 
```

I don't see any error @merewind

**Comment by merewind** [comment]
> Upgrade your `mc` also @merewind to trace `ftp` calls.
> 
> ```
> sftp -P 8022 minioadmin@localhost
> minioadmin@localhost's password: 
> Connected to localhost.
> sftp> ls
> testbucket  
> sftp> cd testbucket/
> sftp> ls
> sftp> mkdir test
> sftp> ls
> test  
> sftp> 
> ```
> 
> I don't see any error @merewind

OK, let me do that and I will post the results, thanks

**Comment by harshavardhana** [comment]
> (`mc ls new [2023-05-18 19:54:45 EDT] 0B ftp/ [2023-06-01 15:01:46 EDT] 0B loki/ [2023-05-19 11:22:28 EDT] 0B sftp/`)

You reported first `ls` says read failure, now you are saying it returns actual results. then you said you had `mkdir` failure which I can clearly it's not. 

So looks like you are doing something locally and not saying clearly what you are doing in this issue. 

I am going to close this since this is a non-issue.

**Comment by merewind** [comment]
mc admin trace --call ftp new
2023-06-28T13:27:15.907 [FTP] sftp USER=admin COMMAND=List PARAM=/, Source=[sftp-server-driver.go:338:(*sftpDriver).Filelist()] 127.0.0.1:9100 / 170.961492ms
2023-06-28T13:27:49.356 [FTP] sftp USER=admin COMMAND=List PARAM=/, Source=[sftp-server-driver.go:338:(*sftpDriver).Filelist()] 127.0.0.1:9100 / 63.934169ms

**Comment by merewind** [comment]
@harshavardhana  please see the results for the traces

**Comment by merewind** [comment]
> > (`mc ls new [2023-05-18 19:54:45 EDT] 0B ftp/ [2023-06-01 15:01:46 EDT] 0B loki/ [2023-05-19 11:22:28 EDT] 0B sftp/`)
> 
> You reported first `ls` says read failure, now you are saying it returns actual results. then you said you had `mkdir` failure which I can clearly it's not.
> 
> So looks like you are doing something locally and not saying clearly what you are doing in this issue.
> 
> I am going to close this since this is a non-issue.

@harshavardhana  can you please have a look at the trace resutls?

**Comment by harshavardhana** [comment]
I see it working perfectly fine. I am simply assuming you have a setup issue. 

```
sftp -P 8022 dillon@localhost
dillon@localhost's password: 
Connected to localhost.
sftp> ls
testbucket  
sftp> 
```

?

**Comment by merewind** [comment]
> I see it working perfectly fine. I am simply assuming you have a setup issue.
> 
> ```
> sftp -P 8022 dillon@localhost
> dillon@localhost's password: 
> Connected to localhost.
> sftp> ls
> testbucket  
> sftp> 
> ```
> 
> ?

can you please share your startup config for this? if possible..

**Comment by harshavardhana** [comment]
```
minio server /tmp/disk{1...4} --ftp="address=:8021" --ftp="passive-port-range=30000-40000" --sftp="address=:8022" --sftp="ssh-private-key=/home/harsha/.ssh/id_rsa" &
```

**Comment by merewind** [comment]
so the issue seems to be TLS trust in my case it's enabled on the server; disabling TLS makes SFTP functional
