### ISSUE TITLE
Add security headers to Minio pod in a kubernetes cluster

### ISSUE THREAD

**Issue by Anushakallam** [minio/minio#17551]
Hi team , need one help . I have deployed Minio pod in a kubernetes cluster. How to set the security headers Strict-Transport-Security: max-age=31536000; includeSubDomains   for mino .I have seen the deployment and service file but there is no options for the security headers . Did any one encounter this problem . 

****Strict-Transport-Security: max-age=31536000; includeSubDomains**

**Comment by harshavardhana** [comment]
These are non configurable, unfortunately.
