### ISSUE TITLE
Preview not taking mime-type into account but only file extension

### ISSUE THREAD

**Issue by ssendev** [minio/minio#17557]
The preview at the right only works if the file name ends in .png or another image extension if it has no extension the preview is disabled.

## Expected Behavior
Enable the preview button if a compatible mime type is set

## Current Behavior
The prieview button is disabled even if an image mime type is set

## Steps to Reproduce (for bugs)

1. upload an image with a key of `foo.png`
2. upload the same image with a key of `foo` and set the mime type to `image/png`
3. see that `foo.png` has a the preview while `foo` has not

## Context

The correct mime type is listed at the bottom and is also returned when generating a share url.

## Your Environment

* Version used (`minio --version`): RELEASE.2023-06-29T05-12-28Z (commit-id=aae684641325e1c37375d455c790e58d902bd7b6)
* Server setup and configuration: Docker

**Comment by harshavardhana** [comment]
The reason we do that is because to know content-type we have to spend an additional API call on the object.

We want things to be simple. Preview itself is good to have functionality not a fundamental feature here.

What you are asking goes beyond this and making its scope larger. Just name the file appropriately, it is human friendly and useful for everyone.

**Comment by ssendev** [comment]
Apparently this is the wrong repository and searching in the right one turned up it's a duplicate https://github.com/minio/console/issues/2573

**Comment by ssendev** [comment]
> to know content-type we have to spend an additional API call on the object.

But the correct content type is already displayed so no api call is needed.

![Screenshot from 2023-07-01 18-55-53](https://github.com/minio/minio/assets/450793/5d0239bf-21c5-4382-876e-12b72d670e16)
