### ISSUE TITLE
set cors allow origin on console,but it not wrok

### ISSUE THREAD

**Issue by pastel001** [minio/minio#17550]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.
### description
I want to enable cros. and just want some Origin can access.
I find the setting on web console,
Settings--API--Cors Allow Origin
I modify the default value * to some other value (http://10.170.156.123:9092/).
after restart mino,I still access the object in my bucket

## Expected Behavior

i cant access the object in my bucket
## Current Behavior

I still access the object in my bucket
## Possible Solution

i dont know whether the config is correct
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
[root@iZ2zei9c3qiv1q5bvfv1c0Z minio]# ./minio -version
minio version RELEASE.2023-06-23T20-26-00Z (commit-id=216069d0da24d8a8bfc885344c221a8d91fde614)
Runtime: go1.19.10 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

**Comment by jiuker** [comment]
Cross-domain and site access whitelisting are different. You should use nginx or apiGateway to implement the functionality you describe. @pastel001

**Comment by pastel001** [comment]
> Cross-domain and site access whitelisting are different. You should use nginx or apiGateway to implement the functionality you describe. @pastel001

@jiuker 
so what is the function of "Cross Allow Origin", its description is "List of origins allowed for CORS requests", I think it means if Minio does not allow CORS, this is the list of who can request to ignore CORS, so does Minio can config not allow CORS? Thank you.
![image](https://github.com/minio/minio/assets/10250772/e382f982-a689-4832-bea9-8863f20f33ff)

**Comment by jiuker** [comment]
yeah. It can config. But not work as access whitelist.

**Comment by pastel001** [comment]
> yeah. It can config. But not work as access whitelist.

so what is the function of "Cross Allow Origin", its description is "List of origins allowed for CORS requests"

**Comment by jiuker** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS @pastel001

**Comment by pastel001** [comment]
不好意思啊，你发的链接我看了，我感觉我理解的CORS应该没问题。
Minio默认的Cross Allow Origin是 * 号，我把他修改成了指定的值不就是希望Minio返回的响应头Access-Control-Allow-Origin是指定的值而不是*，从而禁止跨域访问吗？
我一直在问如果我理解的不对，那么我上面发的截图中Minio配置Cross Allow Origin的作用是什么呢？这块我在Minio的文档里面也没找到，我就理解他是开启Minio禁止跨域访问的。
如果我都理解错了，能给我大概解答一下吗，谢谢
@jiuker

**Comment by harshavardhana** [comment]
Cors doesn't disable access to your objects. Cors is meant to disallow cross origin requests from browser.

**Comment by pastel001** [comment]
> Cors doesn't disable access to your objects. Cors is meant to disallow cross origin requests from browser.

I just want to return disallow cross origin requests and I have modified the "Cross Allow Origin" form "*" to a certain value, but I don't get cross origin disable

**Comment by harshavardhana** [comment]
> > Cors doesn't disable access to your objects. Cors is meant to disallow cross origin requests from browser.
> 
> I just want to return disallow cross origin requests and I have modified the "Cross Allow Origin" form "*" to a certain value, but I don't get cross origin disable

@pastel001 it is impossible to disable cross origin requests, you can only allow a certain domains if you want. * means allow everything.
