### ISSUE TITLE
Drive errors but mc admin info shows all disks are online

### ISSUE THREAD

**Issue by vavagyan** [minio/minio#17560]
## Current Behavior

All disks in Web console is online, but Reduced redundancy storage class parity-1
Policy, Access keys, Users pages doesn't open 
On all servers I see errors like this:

Jul 02 05:02:56 debian6 minio[10410]: DeploymentID: 7296570c-cd3a-4158-821a-10cf2822c32f
Jul 02 05:02:56 debian6 minio[10410]: [88B blob data]
Jul 02 05:02:56 debian6 minio[10410]: [32B blob data]
Jul 02 05:02:56 debian6 minio[10410]: [2B blob data]
Jul 02 05:02:56 debian6 minio[10410]: [2B blob data]
Jul 02 05:02:56 debian6 minio[10410]: [1B blob data]
Jul 02 05:02:56 debian6 minio[10410]: [45B blob data]
Jul 02 05:02:56 debian6 minio[10410]:        5: internal/logger/logger.go:258:logger.LogIf()
Jul 02 05:02:56 debian6 minio[10410]:        4: cmd/xl-storage.go:2276:cmd.(*xlStorage).RenameData()
Jul 02 05:02:56 debian6 minio[10410]:        3: cmd/xl-storage-disk-id-check.go:380:cmd.(*xlStorageDiskIDCheck).RenameData()
Jul 02 05:02:56 debian6 minio[10410]:        2: cmd/storage-rest-server.go:744:cmd.(*storageRESTServer).RenameDataHandler()
Jul 02 05:02:56 debian6 minio[10410]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
Jul 02 05:03:56 debian6 minio[10410]: API: SYSTEM(bucket=bucket1, object=appdata_oc41vldjnn6i/avatar/3014941069/avatar.64.png)
Jul 02 05:03:56 debian6 minio[10410]: Time: 01:03:56 UTC 07/02/2023
Jul 02 05:03:56 debian6 minio[10410]: DeploymentID: 7296570c-cd3a-4158-821a-10cf2822c32f
Jul 02 05:03:56 debian6 minio[10410]: Error: Drive /mnt/disk9/minio, path (bucket1/appdata_oc41vldjnn6i/avatar/3014941069/avatar.64.png) returne>
Jul 02 05:03:56 debian6 minio[10410]:        7: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
Jul 02 05:03:56 debian6 minio[10410]:        6: internal/logger/logonce.go:149:logger.LogOnceIf()
Jul 02 05:03:56 debian6 minio[10410]:        5: cmd/erasure-metadata-utils.go:184:cmd.readAllFileInfo()
Jul 02 05:03:56 debian6 minio[10410]:        4: cmd/erasure-healing.go:414:cmd.(*erasureObjects).healObject()
Jul 02 05:03:56 debian6 minio[10410]:        3: cmd/erasure-healing.go:1152:cmd.erasureObjects.HealObject()
Jul 02 05:03:56 debian6 minio[10410]:        2: cmd/erasure-sets.go:1187:cmd.(*erasureSets).HealObject()
Jul 02 05:03:56 debian6 minio[10410]:        1: cmd/erasure-server-pool.go:1996:cmd.(*erasureServerPools).HealObject.func1()
Jul 02 05:03:56 debian6 minio[10410]: API: SYSTEM(bucket=bucket1, object=appdata_oc41vldjnn6i/avatar/3014941069/avatar.64.png)
Jul 02 05:03:56 debian6 minio[10410]: Time: 01:03:56 UTC 07/02/2023
Jul 02 05:03:56 debian6 minio[10410]: DeploymentID: 7296570c-cd3a-4158-821a-10cf2822c32f
Jul 02 05:03:56 debian6 minio[10410]: Error: msgp: too few bytes left to read object (msgp.errShort)
Jul 02 05:03:56 debian6 minio[10410]:        5: internal/logger/logger.go:258:logger.LogIf()
Jul 02 05:03:56 debian6 minio[10410]:        4: cmd/xl-storage.go:1197:cmd.(*xlStorage).UpdateMetadata()
Jul 02 05:03:56 debian6 minio[10410]:        3: cmd/xl-storage-disk-id-check.go:468:cmd.(*xlStorageDiskIDCheck).UpdateMetadata()

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
minio version RELEASE.2023-06-29T05-12-28Z
4 servers, 28 disks per server
Linux debian 6.1.0-9-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Random drive errors can't be detected by `mc admin info` - we do not own the drive.

If a drive is fully faulty and not writable or readable then we show them as offline.

If not it is not possible to take a drive offline for few errors.
