### ISSUE TITLE
XL: mc cat <object-path> results in incorrect md5sum

### ISSUE THREAD

**Issue by krisis** [minio/minio#1756]
The following error message was seen in server instance's stdout

```
Conn.Write wrote more than the declared Content-Length
```

**Comment by harshavardhana** [comment]
> The following error message was seen in server instance's stdout
> 
> Conn.Write wrote more than the declared Content-Length

Have you updated the server? with the latest.. Do you have the setup handy?

**Comment by krisis** [comment]
@harshavardhana Works on current HEAD on rewrite-xl branch.
