### ISSUE TITLE
Methods for detecting compatibility between different versions of data

### ISSUE THREAD

**Issue by Aaron-PanJi** [minio/minio#17570]
## Expected Behavior
Expect Minio software to have tools similar to MC to check data compatibility
## Current Behavior
Minio currently does not have compatible tools for similar test data

## Your Environment

* Version used (`minio --version`):minio.RELEASE.2021-12-09T06-19-41Z,minio.RELEASE.2023-03-22T06-36-24Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
Could you clarify what you are looking for?

**Comment by klauspost** [comment]
(close if no followup - suspected spam account)

**Comment by klauspost** [comment]
@harshavardhana Could you block this user?
