### ISSUE TITLE
Why is `/opt/bin/mc` gzipped in your release Docker image?

### ISSUE THREAD

**Issue by aucampia** [minio/minio#17581]
Your current release docker image has mc inside it, but it is gzipped:

```console
$ docker run --rm -it --entrypoint= quay.io/minio/minio:latest@sha256:99585c5a7bb20b23b4b585c6f6e3a339483be17ad78074b33d7b83a575457b73 bash -c 'ls -al /opt/bin/*'
-rw-r--r--. 1 root root   9391308 Jun 29 06:56 /opt/bin/mc.gz
-rwxr-xr-x. 1 root root 101826560 Jun 29 06:56 /opt/bin/minio
-rw-r--r--. 1 root root       329 Jun 29 06:56 /opt/bin/minio.minisig
-rw-r--r--. 1 root root       100 Jun 29 06:56 /opt/bin/minio.sha256sum
****
```

And here is where it is gzipped:

https://github.com/minio/minio/blob/37cbd114de8b42e434fdb59bb124db8ef29c0e7e/Dockerfile.release#L39

Is there a reason this is done, and could it be avoided? It is a bit odd to first have to gunzip mc before using it.

If there is a reason, a comment in the Dockerfile that explains the reason may be warranted.

**Comment by jiuker** [comment]
see here:
https://github.com/minio/minio/pull/16156#issuecomment-1431444875
@harshavardhana the same comment here

**Comment by harshavardhana** [comment]
It is available in case of debugging when a separate `pod` for `mc` is not feasible, there is no reason to add comments unnecessarily. There are hundreds of other UNIX tools we can't keep writing comments about each of them.

`mc` is our product and it is useful in debugging MinIO

**Comment by harshavardhana** [comment]
> Is there a reason this is done, and could it be avoided? It is a bit odd to first have to gunzip mc before using it.

It is gzipped because we didn't want to overflow the container image, we can certainly remove if no one really cares for the size of the container.
