### ISSUE TITLE
Succeed replication does not trigger Event to WebHook on PUT/POSTObject

### ISSUE THREAD

**Issue by peter-iglaev** [minio/minio#17582]
Succeed replication does not trigger Event to WebHook on PUT/POSTObject

## Expected Behavior
Object is put to source bucket -> Object is replicated to the target bucket -> Minio Sends Request to configured Webhook on PutObject event

## Current Behavior
Object is replicated but there is no any events to WebHook.
Uploading file to the target bucket does generate PutObject event to WebHook.

## Possible Solution
We can see Put Object operation in the logs after replication.
Looks like there is some filter for events or bug.

## Steps to Reproduce (for bugs)

1. Configure replication between two Minio instances
2. Configure web hook for target bucket
3. Upload file to the source bucket. Wait until replication complete
4. Check the webhook, there is no any events

## Your Environment

* minio --version
```
minio version RELEASE.2023-06-19T19-52-50Z (commit-id=f9b8d1c6999e65ab31899cbbe0314f5a4e5257c3)
Runtime: go1.19.10 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

* uname -a
```
Linux minio-wws-0 5.15.0-1038-azure #45-Ubuntu SMP Mon Apr 24 15:40:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by klauspost** [comment]
I believe this is by design, so the same object doesn't trigger multiple callbacks, but @poornas may be able to correct me.

**Comment by peter-iglaev** [comment]
> I believe this is by design, so the same object doesn't trigger multiple callbacks, but @poornas may be able to correct me.

But that's is the new object for target bucket, no? and like I said, we see PutObject operation in the trace logs. but it doesn't trigger the event

**Comment by poornas** [comment]
This is by design - see https://github.com/minio/minio/pull/11683. You can monitor the `s3:Replication:OperationCompletedReplication` from source in lieu of the `s3:PutObject` event on target.

**Comment by peter-iglaev** [comment]
Hey, @poornas!
Thanks for your answer.

Based on documentations [here](https://github.com/minio/minio/blob/master/docs/bucket/replication/README.md#replicating-deletes) and [here](https://repost.aws/questions/QUWy4DeorXSkOOm5otiBZPyg/does-s3-object-replication-trigger-objectcreated-event) I expected it should work.

If there exist any flag to turn it back on?
or what could you recommend us except using  `s3:Replication:OperationCompletedReplication`?
