### ISSUE TITLE
browser:  Add an option to make bucket or a prefix publicly accessible.

### ISSUE THREAD

**Issue by sokoow** [minio/minio#1759]
It'd be nice to have a public share option available, so that one can access objects without needing to key in the access code, i.e. whole thing would behave like a normal webserver.

**Comment by anti1869** [comment]
You can set bucket's ACL to `readonly` with `mc access readonly bucketname`, so that links http://youhost/bucketname/object will be accessible by anonymous users.

**Comment by anti1869** [comment]
Actually, I wonder why have you removed bucket's ACL operations from python client's API? https://github.com/minio/minio-py/pull/368

**Comment by harshavardhana** [comment]
> Actually, I wonder why have you removed bucket's ACL operations from python client's API? minio/minio-py#368

Bucket ACL's are deprecated instead Bucket policies are implemented on the minio server which are in accordance with http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html 

Bucket policy client side API is only implemented by `minio-go` client, we are going to complete other languages subsequently. 

Even 'mc' implements 'access'  command for bucket policies. 'readonly, readwrite, writeonly' are a simpler forms above large set of bucket policies that can be added for any given bucket.

**Comment by GarimaKapoor** [comment]
Closing this, breaking the issue into three different bugs and moving it to stand alone.
