### ISSUE TITLE
Error in helm template

### ISSUE THREAD

**Issue by aztechian** [minio/minio#17601]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Helm chart installs without error

## Current Behavior
Installing helm chart version 5.0.11 causes an error during installation

```
Error: parse error at (minio/templates/post-job.yaml:255): unexpected {{end}} Use --debug flag to render out invalid YAML
```

I'm nearly certain that version 5.0.11 was installing fine approximately 1 week ago. Did that version perhaps get "re-released" with additional changes that now cause it to error?

## Possible Solution

Potential fix provided in PR #17600 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Installation of chart version 5.0.11 causes ArgoCD to fail syncing with the above syntax error. My values were previously working fine with earlier 5.0.x charts.

## Regression

Yes #17554 

## Your Environment

* Version used (`minio --version`): RELEASE.2023-06-19T19-52-50Z
* Server setup and configuration: standalone, vanilla helm chart (without operator)
* Operating System and version (`uname -a`): Kubernetes 1.23, ArgoCD 2.7.4

**Comment by harshavardhana** [comment]
Feel free to send a fix.

**Comment by yaohwu** [comment]
more fix
https://github.com/minio/minio/pull/17605
