### ISSUE TITLE
Howto configure minio with SSL proxy 

### ISSUE THREAD

**Issue by gps1539** [minio/minio#1761]
Is there a recommended way to configure minio with an SSL proxy? 

Looking for a simple/quick way to use minio in a test case that requires S3 over SSL

**Comment by harshavardhana** [comment]
> Is there a recommended way to configure minio with an SSL proxy?
> 
> Looking for a simple/quick way to use minio in a test case that requires S3 over SSL

Yes @gps1539 here are the relevant docs [1][2]

[1] - https://docs.minio.io/docs/setup-nginx-proxy-with-minio-server 
[2] - https://docs.minio.io/docs/setting-up-proxy-using-caddy

**Comment by gps1539** [comment]
Great, thanks for the quick reply

**Comment by gps1539** [comment]
Unfortunately I can not figure out how to use either option.

I'm running minio on a lab server a dhcp address. Can either option work in this way?

With nginx and a sites-enabled file of 

server {
 listen 443;
 server_name test1;
 location / {
   proxy_set_header Host $host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_pass http://172.27.103.16:9000;
 }
}

I get 
 aws --endpoint-url https://172.27.103.16:443 s3 ls

('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

Try caddy and a Caddyfile of 

localhost:443 {
    proxy / localhost:9000 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
}

I get

aws --endpoint-url https://172.27.103.16:443 s3 ls

[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)

**Comment by harshavardhana** [comment]
> I get 
> aws --endpoint-url https://172.27.103.16:443 s3 ls
> 
> ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
> 
> Try caddy and a Caddyfile of
> 
> localhost:443 {
> proxy / localhost:9000 {
> proxy_header Host {host}
> proxy_header X-Real-IP {remote}
> proxy_header X-Forwarded-Proto {scheme}
> }
> }
> 
> I get
> 
> aws --endpoint-url https://172.27.103.16:443 s3 ls
> 
> [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)

SSL should be used for a domain or a public facing IP associated with that domain.  A private IP will not work in this manner.
