### ISSUE TITLE
concurrent map iteration and map write cause minio server crashed 

### ISSUE THREAD

**Issue by oasangqi** [minio/minio#17645]
## Current Behavior
minio server crashed 

## Possible Solution
safely useing golang map 

## Your Environment
* Version used (`minio --version`):
  minio version RELEASE.2022-09-25T15-44-53Z (commit-id=877bd95fa312c5282c3aa0b73c75af43af9c5914)
Runtime: go1.18.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.

* Operating System and version (`uname -a`):
 Linux web108 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

crashed logs as follow
[crash.txt](https://github.com/minio/minio/files/12034683/crash.txt)

**Comment by dormanze** [comment]
I see a lot of IOwait, can you check your disk status first?

**Comment by harshavardhana** [comment]
This has been fixed a long time ago, please upgrade your setup.

**Comment by oasangqi** [comment]
> This has been fixed a long time ago, please upgrade your setup.

got it, thanks!
