### ISSUE TITLE
madmin: invalid encryption algorithm ID

### ISSUE THREAD

**Issue by MomentQYC** [minio/minio#17661]
## Expected Behavior

![image](https://github.com/minio/minio/assets/62551256/f00118a6-2a00-41a5-b6ec-e6138cbfebf3)
```
API: SYSTEM
Time: 23:00:42 UTC 07/14/2023
DeploymentID: 33885295-cea1-4c3a-b98c-26e14f87dc0b
RequestID: 
RemoteHost: 
UserAgent: 
Error: Failure in periodic refresh for IAM (took 0.08s): madmin: invalid encryption algorithm ID (*errors.errorString)

Backtrace: 
0: internal/logger/logger.go:258:logger.LogIf()
1: cmd/iam.go:450:cmd.(*IAMSys).watch()
```

## Current Behavior

No errors.

## Steps to Reproduce (for bugs)

Unknown.

## Context

Related #17657 and [this](https://github.com/minio/minio/discussions/17658)
This makes most of the features unavailable.

## Regression

No
## Your Environment

* Version used (`minio --version`): `RELEASE.2023-07-07T07-13-57Z (commit-id=e20aab25ec26ef3b1e44eac1f6a01f15f043ab42)`
* Server setup and configuration: deb package
* Operating System and version (`uname -a`): `5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This looks like your credentials are hosed, you need to re-add your credentials.

**Comment by MomentQYC** [comment]
> This looks like your credentials are hosed, you need to re-add your credentials.

Can I fix this without adding a certificate?

**Comment by MomentQYC** [comment]
> This looks like your credentials are hosed, you need to re-add your credentials.

Sorry, I still don't quite understand. Could you please provide me with a general overview of the steps or methods involved?

**Comment by MomentQYC** [comment]
> > This looks like your credentials are hosed, you need to re-add your credentials.
> 
> Sorry, I still don't quite understand. Could you please provide me with a general overview of the steps or methods involved?

I removed the affected config and all is fine now, thanks.
