### ISSUE TITLE
Two parallel uploads preseves the first upload

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1767]
When two parallel uploads of same object with different content is run with `mc` command, it preserves first uploaded file.

Steps to reproduce
1. `$ mc mb myminio/mybucket`
2. `mc cp zero100 myminio/mybucket/zero & mc cp zero101 myminio/mybucket/zero &`
3. `mc ls -r myminio/mybucket` gives

```
[2016-05-26 10:23:12 IST] 100MiB zero
```

`zero100` is 100MiB file and `zero101` is 101MiB file

I am not sure whether this is an issue because there is a chance `zero100` got completed successfully after `zero101` completion.

**Comment by harshavardhana** [comment]
This is still reproducible.

**Comment by krishnasrinivas** [comment]
when two `mc`s are started at the same time, there are two possibilities:
1) both create UploadIDs and upload parts to different uploadids. The `mc` that does the last complete-multipart will decide which object stays there. But both the `mc`s succeed.
2) both share the same UploadID, the `mc` that does complete-mutipart first will decide which object stays there. The second `mc` will fail either during upload part or complete multipart call. The first `mc` can fail if the second `mc` uploaded the same part with different md5sum.

Will verify that what is expected is what is happening.

**Comment by krishnasrinivas** [comment]
first try: 1st case(explained above). no error for `mc`s 100M completes first, 101MB completes second.

```
krishna@escape:~$ mc ls myminio/testbucket/
[2016-05-26 15:51:25 IST] 2.2KiB passwd
[2016-05-27 17:46:09 IST] 101MiB zero
[2016-05-27 17:46:21 IST]     0B a/
krishna@escape:~$
```

second try: 1st case. no error for `mc`s 101M completes first, 100M completes second.

```
krishna@escape:~$ mc ls myminio/testbucket/
[2016-05-26 15:51:25 IST] 2.2KiB passwd
[2016-05-27 17:46:27 IST] 100MiB zero
[2016-05-27 17:46:31 IST]     0B a/
krishna@escape:~$
```

third try :

```
krishna@escape:~$ mc cp /tmp/100mb myminio/testbucket/zero & mc cp /tmp/101mb myminio/testbucket/zero &
[1] 4140
[2] 4141
mc: <ERROR> Failed to copy ‘/tmp/100mb’. One or more of the specified parts could not be found.
```

should have given error `uploadid can't be found`

fourth try:

```
krishna@escape:~$ mc cp /tmp/100mb myminio/testbucket/zero & mc cp /tmp/101mb myminio/testbucket/zero &
[1] 4187
[2] 4188
mc: <ERROR> Failed to copy ‘/tmp/101mb’. Object key is missing, object key cannot be empty
```

should have given error `uploadid can't be found`

**Comment by krishnasrinivas** [comment]
fixed some locking code, now it either succeeds or gives error `mc: <ERROR> Failed to copy ‘/tmp/101mb’. The specified multipart upload does not exist.`

**Comment by GarimaKapoor** [comment]
please update the timeline for closing the bug!
