### ISSUE TITLE
A deleted bucket gets resurrected on a subsequent delete

### ISSUE THREAD

**Issue by rsyring** [minio/minio#17672]
## Expected Behavior

I'm using the boto3 client to create, delete, and check for the existence of buckets.  When calling DeleteBucket twice on the same bucket:

* first call should succeed and delete the bucket
* second call should error out with `NoSuchBucket` error code
* the bucket should not be present

## Current Behavior

* first call succeeds and deletes the bucket (confirmed in the minio web console the bucket is not present)
* second call errors out with `NoSuchBucket` error code
* the previously deleted bucket has been resurrected and is now present again

## Steps to Reproduce (for bugs)

```python
# s3-example.py
import boto3

bucket_name = 's3'

s3_client = boto3.client(
    's3',
    aws_access_key_id='root',
    aws_secret_access_key='minrootpass',
    endpoint_url='http://localhost:9200',
)
s3_client.create_bucket(Bucket='issue-example')
s3_client.delete_bucket(Bucket='issue-example')
s3_client.delete_bucket(Bucket='issue-example')
```

And running the example:

```
$ mc ls twt
$ python ~/tmp/s3-example.py 
Traceback (most recent call last):
  File "/home/rsyring/tmp/s3-example.py", line 13, in <module>
    s3_client.delete_bucket(Bucket='issue-example')
  File "/home/rsyring/tmp/virtualenvs/twt/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rsyring/tmp/virtualenvs/twt/lib/python3.9/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the DeleteBucket operation: The specified bucket does not exist
$ mc ls twt
[0000-12-31 19:03:58 LMT]     0B issue-example/
```

The exception is the expected behavior.  What is not expected is that the issue-example bucket would return.

## Context

I'm writing automated tests for code that creates and deletes buckets.  I'm testing error handling code when a bucket is deleted twice.  The bucket being resurrected creates test failures where they are not expected b/c, after calling delete, we expect the bucket to actually be gone.

## Regression

Sorry, don't know.

## Your Environment

* Version: RELEASE.2023-07-11T21-29-34Z (go1.19.11 linux/amd64)
* Running "latest" docker image (single instance of minio)
* Linux meld 6.2.0-24-generic # 24-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 12:03:50 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
I would expect DeleteBucket to be idempotent and return the success result - at least for a while.

Verify against AWS before making changes.

**Comment by rsyring** [comment]
@klauspost thanks for the input.  I'm not sure what the operation being idempotent has to do with this issue.  To clarify:

1. If you only call DeleteBucket once, then a subsequent call to head or list bucket will not show the bucket.
2. If you call DeleteBucket twice on the same bucket, the second will error, but now a subsequent call to head or list bucket will show the bucket.  A call to delete a bucket should not cause it to come back after it's already been deleted.

**Comment by vadmeste** [comment]
@rsyring thanks for reporting this. I sent a fix. It should be included in the next MinIO release

**Comment by rsyring** [comment]
@vadmeste thanks for fixing it.  :)
