### ISSUE TITLE
Batch replicate not working

### ISSUE THREAD

**Issue by CGsama** [minio/minio#17678]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

adding batchfile

## Current Behavior

{"Code":"NoSuchSourceBucket","Message":"The specified bucket [remote-bucket-name] does not exist","Resource":"/minio/admin/v3/start-job",

## Steps to Reproduce (for bugs)

![image](https://github.com/minio/minio/assets/15722562/70d7e21b-2af2-483d-8560-3ec9fb7c9b2d)

run with mc batch start --debug myalias ./filenamel.yaml

## Context

try to replicate to cloud as backup, intent using cheap provider like idrivee2, but got error, then try to use aws still instant throw the same error

## Your Environment

minio version RELEASE.2023-06-09T07-32-12Z (commit-id=6b7c98bd0fde630c6aee78d702b9d37b0200f52c)
Linux minio 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

running the executable alone in tmux

**Comment by CGsama** [comment]
![image](https://github.com/minio/minio/assets/15722562/611c0129-1301-4c5d-b454-61e098e75ac6)
dont think it even talk to the remote server

**Comment by harshavardhana** [comment]
It says that your remote bucket doesn't exist
