### ISSUE TITLE
Setting quotas globally

### ISSUE THREAD

**Issue by sebastian-luna-valero** [minio/minio#17694]
**Is your feature request related to a problem? Please describe.**

There is the `mc quota set` command to set a quota per bucket:
https://min.io/docs/minio/linux/reference/minio-mc/mc-quota-set.html

but I don't think there is a way to configure quotas for all buckets globally?

**Describe the solution you'd like**

A configuration option to set a quota for all buckets in a single place.

**Describe alternatives you've considered**

Manually setting quotas to each bucket individually using the `mc quota set` command:
https://min.io/docs/minio/linux/reference/minio-mc/mc-quota-set.html

**Comment by jiuker** [comment]
`mc ls | awk {print $2} | xargs -I {} mc quota set {} ` It's a thought. BTW this issue should move to `mc`

**Comment by harshavardhana** [comment]
Quotas are per bucket. There is no further extension under plans for this API.

Quotas are already non standard in S3 API. The scope is not going to be expanded further.

If you have a strong commercial requirement feel free to email us at https://min.io/pricing - we can guide you appropriately.
