### ISSUE TITLE
Storage_ Class defaults to empty instead of 4

### ISSUE THREAD

**Issue by hjun881** [minio/minio#17691]
##  `storage_class` defaults to empty, resulting in unknown space when not configured

The official document states that the default is 4, which can be viewed through commands and is empty by default

*  [official documents](https://minio.org.cn/docs/cn/minio/linux/reference/minio-server/minio-server.html)

![image](https://github.com/minio/minio/assets/18508499/ba98ccd1-e43d-4c23-81a4-0b3651306e32)

* Check if the `storage_class` is empty through the command

```bash
$ mcli admin config get log-minio storage_class
storage_class standard= rrs=EC:1 
```

**Comment by harshavardhana** [comment]
This is normal, the calculation is internal for default unset values.
