### ISSUE TITLE
Storage reached its minimum free disk threshold

### ISSUE THREAD

**Issue by rajarathnabalan** [minio/minio#17692]
I am running minio in kubernets with volume mount to disk. Disk size is 50GB and it is filled with only 23GB data. I am facing error on starting minio,

**Error:**
API: SYSTEM()
Time: 08:42:52 UTC 07/20/2023
DeploymentID: 6f948d3d-5df7-4157-97e1-9c5b5165e029
Error: Storage reached its minimum free disk threshold. (cmd.StorageFull)
    2: cmd/fs-v1.go:320:cmd.(*FSObjects).NSScanner()
    1: cmd/data-scanner.go:149:cmd.runDataScanner()

**System info:**
<img width="775" alt="Screenshot 2023-07-20 at 3 19 18 PM" src="https://github.com/minio/minio/assets/31469256/c44ff8a3-0392-4835-b6e4-07fbe6a65a2b">

* Version used (`minio --version`): RELEASE.2021-09-15T04-54-25Z
* Server setup and configuration: kubernets minio container logged in as root
* Operating System and version (`uname -a`): Linux minio-cf57dcd75-fczk7 5.4.0-1056-azure 58~18.04.1-Ubuntu SMP Wed Jul 28 23:14:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rajarathnabalan** [comment]
I also read through issue [6795](https://github.com/minio/minio/issues/6795) not able to solve the problem.

**Comment by vadmeste** [comment]
@rajarathnabalan we don't help issues related to FS mode anymore since it is deprecated and removed long time ago. Otherwise something obvious to check is `df -i`, can you paste it ?

**Comment by harshavardhana** [comment]
FS mode is deprecated, please migrate to supported setups.

If you are using ext4, move to more scalable filesystems such as XFS to avoid ext4 limits.
