### ISSUE TITLE
Running minio on Azure App Service results in Invalid Argument error

### ISSUE THREAD

**Issue by craftzneko** [minio/minio#17704]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Minio works

## Current Behavior
When running minio in a multi container app on Azure App Service using docker compose like this

  storage:
    image: minio/minio
    env_file: ./docker.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: ["-c", "minio server /data"]
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ${WEBAPP_STORAGE_HOME}/storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

Error is generated
Error: write /data/.minio.sys/tmp/90bfce85-d6a3-41ca-bafc-1a6ba65b2b17: invalid argument
(*fs.PathError)

**Comment by harshavardhana** [comment]
@craftzneko please bring a drive with filesystem that can support O_DIRECT for writes.

**Comment by craftzneko** [comment]
Are you aware azure app service doesn't support O_DIRECT then?

**Comment by harshavardhana** [comment]
> Are you aware azure app service doesn't support O_DIRECT then?

That's what the error means.

**Comment by craftzneko** [comment]
Haha brilliant. Will take this up with Microsoft support then as I am using this in a docker compose scenario and azure doesn't support anything except internal container persistantstorage. Cheers for help
