### ISSUE TITLE
Can't pull any images from docker.io

### ISSUE THREAD

**Issue by plasterman117** [minio/minio#17720]
I can not pull any minio images from docker.io. I can reach other docker.io images (docker.io/grafana/grafana:latest for example), but can not reach anything from minio/minio. Is there a way to verify these images are available for pulling?

-bash-4.2$ docker pull minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
Trying to pull repository registry.access.redhat.com/minio/minio ...
Pulling repository registry.access.redhat.com/minio/minio
Trying to pull repository docker.io/minio/minio ...
Trying to pull repository registry.fedoraproject.org/minio/minio ...
Pulling repository registry.fedoraproject.org/minio/minio
Trying to pull repository quay.io/minio/minio ...
Trying to pull repository registry.centos.org/minio/minio ...
Trying to pull repository docker.io/minio/minio ...
manifest for docker.io/minio/minio:RELEASE.2023-07-21T21-12-44Z.fips not found
-bash-4.2$ docker pull minio/minio
Using default tag: latest
Trying to pull repository registry.access.redhat.com/minio/minio ...
Pulling repository registry.access.redhat.com/minio/minio
Trying to pull repository docker.io/minio/minio ...
Trying to pull repository registry.fedoraproject.org/minio/minio ...
Pulling repository registry.fedoraproject.org/minio/minio
Trying to pull repository quay.io/minio/minio ...
Trying to pull repository registry.centos.org/minio/minio ...
Trying to pull repository docker.io/minio/minio ...
manifest for docker.io/minio/minio:latest not found
-bash-4.2$ docker pull minio/minio:RELEASE.2023-07-18T17-49-40Z
Trying to pull repository registry.access.redhat.com/minio/minio ...
Pulling repository registry.access.redhat.com/minio/minio
Trying to pull repository docker.io/minio/minio ...
Trying to pull repository registry.fedoraproject.org/minio/minio ...
Pulling repository registry.fedoraproject.org/minio/minio
Trying to pull repository quay.io/minio/minio ...
Trying to pull repository registry.centos.org/minio/minio ...
Trying to pull repository docker.io/minio/minio ...
manifest for docker.io/minio/minio:RELEASE.2023-07-18T17-49-40Z not found
-bash-4.2$ docker pull minio/minio:RELEASE.2023-07-11T21-29-34Z
Trying to pull repository registry.access.redhat.com/minio/minio ...
Pulling repository registry.access.redhat.com/minio/minio
Trying to pull repository docker.io/minio/minio ...
Trying to pull repository registry.fedoraproject.org/minio/minio ...
Pulling repository registry.fedoraproject.org/minio/minio
Trying to pull repository quay.io/minio/minio ...
Trying to pull repository registry.centos.org/minio/minio ...
Trying to pull repository docker.io/minio/minio ...
manifest for docker.io/minio/minio:RELEASE.2023-07-11T21-29-34Z not found
-bash-4.2$ docker pull minio/minio:RELEASE.2023-06-09T07-32-12Z
Trying to pull repository registry.access.redhat.com/minio/minio ...
Pulling repository registry.access.redhat.com/minio/minio
Trying to pull repository docker.io/minio/minio ...
Trying to pull repository registry.fedoraproject.org/minio/minio ...
Pulling repository registry.fedoraproject.org/minio/minio
Trying to pull repository quay.io/minio/minio ...
Trying to pull repository registry.centos.org/minio/minio ...
Trying to pull repository docker.io/minio/minio ...
manifest for docker.io/minio/minio:RELEASE.2023-06-09T07-32-12Z not found

**Comment by harshavardhana** [comment]
Looks like you have some local issue

```
docker pull minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
RELEASE.2023-07-21T21-12-44Z.fips: Pulling from minio/minio
5329d7039f25: Pull complete 
d056ecbaf8d9: Pull complete 
2acf078768d0: Pull complete 
8d80674977a5: Pull complete 
b3678b1023c0: Pull complete 
f6020b7ce19e: Pull complete 
Digest: sha256:d47c655b7a1ff186c50f802244619087332023dfd8b88f62850761d0cbe7cf63
Status: Downloaded newer image for minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
docker.io/minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
```

**Comment by plasterman117** [comment]
Thank you for verifying that for me. Strange that other repos are working for me but not this one.
