### ISSUE TITLE
Cannot upload to presignePostPolicy after upgrade - The name of the uploaded key is missing

### ISSUE THREAD

**Issue by chris-aeviator** [minio/minio#17725]
## Expected Behavior
After an upgrade from RELEASE.2023-05-04T21-44-30Z to RELEASE.2023-07-21T21-12-44Z previously working postPolicy logic should have not changed.

## Current Behavior
After the upgrade previously working code (see minimal example below) stops working and throws an error 

> The body of your POST request is not well-formed multipart/form-data. (The name of the uploaded key is missing)

The key is beeing sent correctly. 

## Possible Solution

https://github.com/minio/minio/blob/a7c71e4c6ba69a2c66e3bc497eccc435e1377270/cmd/bucket-handlers.go#L1049 looks for the key with a capital "K", whereas form fields are beeing sent as lower caps. I have tested to force an additional "Key" value with no success to the error message.

## Steps to Reproduce (for bugs)
```
const S3_ACCESS="test", S3_SECRET="test1234567"
const Minio = require('minio')   
const s3_endpoint = 'localhost'

const reject = (err) => {
  throw new Error(err)
}


async function fetchData() {
  const resolve = async (data, form) => {
    const fileName = 'test.py';
    const file = new File(['hello world'], fileName, { type: 'text/plain' });
    // Add your file to the form data
    form.append('file', file);
    // Convert the formData object into FormData
    Object.entries(data.formData).forEach(([key, value]) => {
        form.set(key, value)
      });
  
    form.append('file', file)


    const response = await fetch(data.postURL, {
      method: 'POST',
      body: form,
    });

    // console.log(await response.text())


  }
  let fd = new FormData()
  const s3 = new Minio.Client({
    accessKey : S3_ACCESS,
    secretKey : S3_SECRET,
    endPoint  : s3_endpoint,
    port      : 9000,
    useSSL    : false,
    region    : 'us-east-1'
  });


  const fileName = 'test.py'
  const bucket = 'tofu'
  const pathInBucket = `tofu/upload/${fileName}`, 
          policy  = s3.newPostPolicy(),
          expires = new Date;


  policy.setKey(pathInBucket)
  policy.setBucket(bucket)


  s3.presignedPostPolicy(policy, function (err, data) {
    // debugger
    if (err) reject(err)
    // console.dir({data}, {depth: null})
    resolve(data, fd)
  })

}

fetchData()
```

## Context
It brought down our production infrastructure for the past few days, we are trying to find out if a downgrade is an option with not success for reliable information.  

## Regression
Yes - RELEASE.2023-05-04T21-44-30Z was fine.

## Your Environment
RELEASE.2023-07-21T21-12-44Z
quay.io/minio/minio following docker-compose example.
Node.js v20.5.0
 "minio": "^7.1.1" (minio-js)

**Comment by harshavardhana** [comment]
> It brought down our production infrastructure for the past few days, we are trying to find out if a downgrade is an option with not success for reliable information.

why are you running production without production support? @chris-aeviator

**Comment by harshavardhana** [comment]
> looks for the key with a capital "K", whereas form fields are beeing sent as lower caps. I have tested to force an additional "Key" value with no success to the error message.

No this is a canonical value so `Key` is automatically capitalized, something else is missing in your code. 

Let me check why.

**Comment by harshavardhana** [comment]
How would I run your javascript code? can you provide instructions?

**Comment by chris-aeviator** [comment]
> How would I run your javascript code? can you provide instructions?

it's nodeJS code. Make sure to have node >= 18 for native fetch, FormData and File

create a new node project

> yarn init

Paste the code into a index.js file, install minio-js 

> yarn add minio

run it as 
>node index.js

**Comment by harshavardhana** [comment]
I see the bug is in the client code, client code is not sending anything related to `key`

```
localhost:9000 [REQUEST s3.PostPolicyBucket] [2023-07-26T00:54:23.144] [Client IP: 127.0.0.1]
localhost:9000 POST /tofu
localhost:9000 Proto: HTTP/1.1
localhost:9000 Host: localhost:9000
localhost:9000 User-Agent: undici
localhost:9000 Accept-Language: *
localhost:9000 Connection: keep-alive
localhost:9000 Content-Type: multipart/form-data; boundary=----formdata-undici-042335089584
localhost:9000 Sec-Fetch-Mode: cors
localhost:9000 Accept: */*
localhost:9000 Accept-Encoding: gzip, deflate
localhost:9000 Content-Length: 1490
localhost:9000 ------formdata-undici-042335089584
Content-Disposition: form-data; name="file"; filename="test.py"
Content-Type: text/plain

```

This is because of a bug in your @chris-aeviator 

```
    // Add your file to the form data
    form.append('file', file);
    // Convert the formData object into FormData
    Object.entries(data.formData).forEach(([key, value]) => {
        form.set(key, value)
      });
  
    form.append('file', file)
```

A `file` parameter must never be set at the beginning of the form - this is a requirement as per AWS S3 API. 

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html



Name | Description | Required
-- | -- | --
file | The file or text content. **The file or text content must be the last field in the form**. You cannot upload more than one file at a time.Type: File or text contentDefault: None | Yes

Fixing this fixes the problem

```js
const S3_ACCESS="minioadmin", S3_SECRET="minioadmin"
const Minio = require('minio')   
const s3_endpoint = 'localhost'

const reject = (err) => {
  throw new Error(err)
}

async function fetchData() {
  const resolve = async (data, form) => {
    const fileName = 'test.py';
    const file = new File(['hello world'], fileName, { type: 'text/plain' });
      
    // Convert the formData object into FormData
    Object.entries(data.formData).forEach(([key, value]) => {
        form.set(key, value)
      });

    // Make sure file is added at the end.
    form.append('file', file)
      
    const response = await fetch(data.postURL, {
        method: 'POST',
        body: form,
    });

    // console.log(await response.text())
  }
  let fd = new FormData()
  const s3 = new Minio.Client({
    accessKey : S3_ACCESS,
    secretKey : S3_SECRET,
    endPoint  : s3_endpoint,
    port      : 9000,
    useSSL    : false,
    region    : 'us-east-1'
  });


  const fileName = 'test.py'
  const bucket = 'tofu'
  const pathInBucket = `tofu/upload/${fileName}`, 
          policy  = s3.newPostPolicy(),
          expires = new Date;


  policy.setKey(pathInBucket)
  policy.setBucket(bucket)


  s3.presignedPostPolicy(policy, function (err, data) {
    // debugger
    if (err) reject(err)
      // console.dir({data}, {depth: null})
      
    resolve(data, fd)
  })

}

fetchData()
```

The fixed code

**Comment by harshavardhana** [comment]
Now why did it work before? - we were deviating from the spec for years. So we went back to the books. It was also a necessary change to make sure we don't ever have to buffer the stream for POST requests allowing us to be fully "stream" friendly.

This is why you should never be running production infrastructure without our support and blessing @chris-aeviator 

I debugged this for you in 1 hour, please value your time. I hope this incident reminds your organization to consider signing up - https://min.io/pricing is just a few clicks away.

Thanks

**Comment by chris-aeviator** [comment]
@harshavardhana AMAZING! thank you **so much**, this is really something no one expected here. We'll need to re-evaluate certain procedures that have let to this incident (upgrading without prior testing), but I'm considering  a support plan, what's holding us back at the very moment is a min. of 1k$/ mo. Thank you also for the explaination why this worked before, it all makes sense now.
