### ISSUE TITLE
Represent wrong capacity when running decommission command

### ISSUE THREAD

**Issue by blackironj** [minio/minio#17722]
## NOTE

Hello !
I have faced a something wrong after starting `decommission` admin command. 
When I ran `mc admin decommission status` to check status 20hours later, I saw wrong `capacity` like below the screenshot
![wrong-status](https://github.com/minio/minio/assets/43738420/d188e8f1-c9c2-41f5-b78a-a4d96964b558)

I think it worked fine when I checked for hours first

The pool had about 780GiB / 3.5 TiB first but now 16EiB / 3.5TiB.

Any solution to fix it?

Thank you :)

## Expected Behavior

Some hours later, 
decommission status  of the pool should be `Complete`
OR
Remainder should be decreased

## Current Behavior

The status of pool is still `draining` and remainder did not decrease but rather increase ( about 780GiB to 16EiB ).

## Steps to Reproduce (for bugs)

1. `mc admin decommission start citrus-minio http://citrus-minio1/mnt/disk{1...5}/minio`
2. Waiting 20hours
3. `mc admin decommission status`

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-07-07T07-13-57Z (commit-id=e20aab25ec26ef3b1e44eac1f6a01f15f043ab42)
Runtime: go1.19.10 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```
MINIO_VOLUMES="http://citrus-minio1/mnt/disk{1...5}/minio http://citrus-minio2/mnt/disk{1...5}/minio http://citrus-minio3/mnt/disk{1...8}/minio"

MINIO_OPTS="--console-address :9001"
```
* Operating System and version (`uname -a`):
```
Linux lemon 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@blackironj This is fixed in newer releases please upgrade.

**Comment by blackironj** [comment]
@harshavardhana 
Thank you for replying fast
~Are there any problems with upgrading in the current state?~

After upgrading minio and then restart again after cancel it first. It works fine 👍🏼
