### ISSUE TITLE
Upload to minio holds for minutes just after 100% complete

### ISSUE THREAD

**Issue by val1ev** [minio/minio#17729]
I have two instances of minio on my Windows 10 Pro started on different ports and on different disks.
minio version is 2022-02-07T08:17:33Z

First instance works fine with no issues.

But the second one have a weird behavior.
Upload process sticks just after the transfer complete. Tried via 'mc' and via API.

Transfer finishes but minio doesn't close the connection, it needs to wait for a few minutes.
As large the file as long the pause after the transfer before the completion.

For example, for the 100Mb file I have to wait about 2 mins. 

Have no idea what's wrong. There are the same versions of minio on few servers of mine. Everything works fine except this one instance. There are no versioning and compression enabled.

Windows copy command to that minio disk works fine, less than a second.

**Comment by klauspost** [comment]
We do not support versions this old. Also without any real information about setup, we would just be guessing anyway.

Upgrade to latest. If you still experience issues, feel free to open another issue with proper setup information.

**Comment by val1ev** [comment]
Unfortunately I can't upgrade to the latest because I need to support old filesystem ("format": "fs").
So will try to guess the reason by myself.

**Comment by harshavardhana** [comment]
> Unfortunately I can't upgrade to the latest because I need to support old filesystem ("format": "fs"). So will try to guess the reason by myself.

The reason is because of complete multipart upload() behavior in FS mode. It needs to coalesce the parts into single file. 2mins is where it's spending time on that. 

There are ways to avoid this behavior

- do not use multipart uploads, you are on FS mode why bother.
- use multipart uploads however make sure parts are uploaded in order not randomly i.e serialize the uploads 
- upgrade and migrate away from FS mode.

**Comment by val1ev** [comment]
> > Unfortunately I can't upgrade to the latest because I need to support old filesystem ("format": "fs"). So will try to guess the reason by myself.
> 
> The reason is because of complete multipart upload() behavior in FS mode. It needs to coalesce the parts into single file. 2mins is where it's spending time on that.
> 
> There are ways to avoid this behavior
> 
> * do not use multipart uploads, you are on FS mode why bother.
> * use multipart uploads however make sure parts are uploaded in order not randomly i.e serialize the uploads
> * upgrade and migrate away from FS mode.

Thank you for your reply.
Looks like you are right. Decided to migrate away from FS mode.
