### ISSUE TITLE
mc share download 30d not working

### ISSUE THREAD

**Issue by LaurenHuet** [minio/minio#17743]
## Expected Behavior

In the documentation https://min.io/docs/minio/linux/reference/minio-mc/mc-share-download.html 
the example shows being able to set the URL to expire at 30d. However when I try this I receive an error saying the . time: unknown unit "d" in duration 
When i attempt to increase the hours past 7 days i receive an error saying URL cannot exceed more that 7 days.

## Steps to Reproduce (for bugs)

I have tried both of the following however d is an unknown unit
mc share download --recursive --expire 30d00h00m00s pawsey0812/ucsd-collab/
mc: <ERROR> Unable to parse expire=`30d00h00m00s`. time: unknown unit "d" in duration "30d00h00m00s".

mc share download --recursive --expire 30d pawsey0812/ucsd-collab/
mc: <ERROR> Unable to parse expire=`30d`. time: unknown unit "d" in duration "30d".

mc share download --recursive --expire 750h00m00s pawsey0812/ucsd-collab/
mc: <ERROR> Expiry cannot be larger than 7 days. 

## Context
I would like to be able to share this data for longer than 7 days, 30d would be ideal. 

## Your Environment
I am using HPC pawsey 
mc -version
mc version RELEASE.2022-12-13T00-23-28Z (commit-id=4b4cab0441f000db100c5b5d9329221181bf61f2)
Runtime: go1.19.4 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by jiuker** [comment]
We will not support mc with very old version.

**Comment by harshavardhana** [comment]
> We will not support mc with very old version.

and also resigned URLs maximum validity is 7days as per AWS S3 spec, 30days is not going to be supported.

**Comment by ravindk89** [comment]
We'll update the docs to remove that example as well.
