### ISSUE TITLE
mc: <ERROR>  Please register the cluster first by running 'mc license register minio'

### ISSUE THREAD

**Issue by zhl19911203** [minio/minio#17766]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

1、wget https://dl.min.io/client/mc/release/linux-amd64/mc
2、chmod +x mc
3、mc support perf minio

报错mc: <ERROR>  Please register the cluster first by running 'mc license register minio'

## Your Environment
minio/minio:RELEASE.2021-01-16T02-19-44Z  版本

除了这个之外，怎么对minio做性能测试，io测试

**Comment by harshavardhana** [comment]
`mc support` commands require MinIO subscription @zhl19911203 please reach out to us here https://min.io/pricing
