### ISSUE TITLE
is minio support create tier object

### ISSUE THREAD

**Issue by vklonghml** [minio/minio#17779]
tier object: when an object pass to tier remote tiering site, the object in minio is remove but the metadata.

if there is possible that just creating a tier object the above described.

**Comment by harshavardhana** [comment]
> tier object: when an object pass to tier remote tiering site, the object in minio is remove but the metadata.
> 
> if there is possible that just creating a tier object the above described.

No you are asking for MinIO to not store any metadata, no that is not possible. We do not support gateway like functionality anymore.
