### ISSUE TITLE
Zero values of internode data transfer metrics

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#17773]
We use Prometheus for monitoring minio cluster. After upgrade minio to the version 2023-07-07T07:13:57Z following metrics always have zero values:

minio_inter_node_traffic_sent_bytes
minio_inter_node_traffic_received_bytes

* Version used (`minio --version`): 2023-07-07T07:13:57Z
* Server setup and configuration: 4 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-cold-1 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is fixed in later versions @AlexZIX - thanks for the report.
