### ISSUE TITLE
部署咨询

### ISSUE THREAD

**Issue by zhl19911203** [minio/minio#17771]
arm架构，64核心。centos系统，6块4t的磁盘，怎么分布式部署节点比较合适，需要io占用小
几个节点，每个节点磁盘分布

**Comment by jiuker** [comment]
我们将不会给出任何建议。我们这里只讨论bug或者feature。QA环节不在这里完成。

**Comment by jiuker** [comment]
如果你需要QA。 
https://min.io/pricing 你需要填写一些信息。
我们有专业的技术支持团队。
