### ISSUE TITLE
Access-Control-Allow-OriginHeader Not set correctly in container version minio/minio:RELEASE.2023-07-21T21-12-44Z

### ISSUE THREAD

**Issue by wcbzero** [minio/minio#17778]
After upgrading from docker container minio/minio:RELEASE.2023-06-29T05-12-28Z to minio/minio:RELEASE.2023-07-21T21-12-44Z, the Access-Control-Allow-Origin Header header is now set to '*' instead of the configured value.

## Expected Behavior

Set the "Cors Allow Origin" setting to "https://*.example.com"
Perform a request to the bucket with the origin header set
The response should return the "Access-Control-Allow-Origin" set to the value of the origin

## Current Behavior

"Access-Control-Allow-Origin" is set to '*'

## Steps to Reproduce (for bugs)

Set the "Cors Allow Origin" setting to "https://*.example.com" in the admin console
Perform a request to the bucket with the origin header set: ex

```python
import requests

public_url = f"https://minio.example.com/bucket/test"
origin = 'https://other-sub-domain.example.com/'
session = requests.Session()
session.headers.update({'origin': origin})
output = session.get(public_url)
header_value = output.headers['Access-Control-Allow-Origin']

assert header_value == origin

```

The response should return the "Access-Control-Allow-Origin" set to the value of the origin

## Context

We are using the Access-Control-Allow-Origin header on version  RELEASE.2023-06-29T05-12-28Z and the behavior changed on RELEASE.2023-07-21T21-12-44Z

## Regression

Yes

## Your Environment

This instance is running in Azure Kubernetes, using the docker container with tag RELEASE.2023-07-21T21-12-44Z

**Comment by jiuker** [comment]
Yeah, it's a broken change here. And that is acceptable. What business of yours has been affected by this? @wcbzero

**Comment by wcbzero** [comment]
My user's downstream applications had broke previously when the header was set to '*'. We dont have an urgent need to upgrade at this time. Is this a broken change that will be corrected in a future release?

**Comment by harshavardhana** [comment]
> My user's downstream applications had broke previously when the header was set to '*'. We dont have an urgent need to upgrade at this time. Is this a broken change that will be corrected in a future release?

why would it break? `*` is allowed here according to the HTTP spec what is the value that is set for allowed origins on the server?
