### ISSUE TITLE
Unable to enable auto encryption. Server side encryption specified but KMS is not configured.

### ISSUE THREAD

**Issue by bhara03021989** [minio/minio#17794]
We have set up KES and KMS (Vault) with self signed certificates . 
KES to KMS the communication is working fine . I am able to create the key and see them on vault . 
But when using mc client (i.e Minio to KES ) I am getting the error as below :

mc encrypt set SSE-KMS minio-key-encrypt-bucket minioroot/cus360bucket
mc: <ERROR> Unable to enable auto encryption. Server side encryption specified but KMS is not configured.

I have set up every env variable required on all the host in the minio deployment . 

export MINIO_KMS_KES_ENDPOINT=https://172.xxx.xxx.xxx:7373
export MINIO_KMS_KES_CERT_FILE=/home/minio/.minio/certs/public.crt
export MINIO_KMS_KES_KEY_FILE=/home/minio/.minio/certs/private.key
export MINIO_KMS_KES_CAPATH=/home/minio/.minio/certs/CAs/kes-server.cr
export VAULT_TOKEN=hvs.K8zPxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
export VAULT_ADDR='https://example.host.com:8200'

When creating the key :

./kes key create -k minio-key-encrypted-bucket-key -k

Able to see the key on the vault :

 vault kv list kv
Keys
----
minio-key-encrypted-bucket-key

The minio trace looks like the below :

[REQUEST s3.GetBucketLocation] [2023-08-03T08:40:10.772] [Client IP: 172.xxx.xx.xxxx]
GET /cus360bucket/?location=
Proto: HTTP/1.1
Host: example.host.com:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.55 mc/RELEASE.2023-06-06T13-48-56Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20230803T124010Z
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230803/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content
=b8c211e48f5f3b50d60a0245d87de58511d09b6cfb571e445060210a53192cb9
Content-Length: 0

[RESPONSE] [2023-08-03T08:40:10.773] [ Duration 1.177ms  â 77 B  â 128 B ]
200 OK
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Amz-Id-2: eca2f7943b254b3892e77f97f5f8f1af117df9661ae8f3febe2da1a6768504f9
X-Content-Type-Options: nosniff
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin,Accept-Encoding
X-Amz-Request-Id: 1777DFF0E1AB140D
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Content-Length: 128
<?xml version="1.0" encoding="UTF-8"?>
tp://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>

[REQUEST s3.PutBucketEncryption] [2023-08-03T08:40:10.773] [Client IP: 172.xxx.xx.xxxx]
PUT /cus360bucket/?encryption=
Proto: HTTP/1.1
Host: example.host.com:9000
X-Amz-Date: 20230803T124010Z
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230803/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x
e, Signature=0529f7fe2f3cb89f9c3b526c49b8ce3f163d1ff8aadccbae50ea86f7073968d2
Content-Length: 250
Content-Md5: 7xqv0rMaaoRD5ctat/4T9w==
User-Agent: MinIO (linux; amd64) minio-go/v7.0.55 mc/RELEASE.2023-06-06T13-48-56Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
<ServerSideEncryptionConfiguration><Rule><ApplyServerSideEncryptionByDefault><KMSMasterKeyID>minio-key-encrypt-bucket</KMS
:kms</SSEAlgorithm></ApplyServerSideEncryptionByDefault></Rule></ServerSideEncryptionConfiguration>
[RESPONSE] [2023-08-03T08:40:10.775] [ Duration 1.228ms  â 339 B  â 350 B ]
**501 Not Implemented**
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Amz-Id-2: eca2f7943b254b3892e77f97f5f8f1af117df9661ae8f3febe2da1a6768504f9
X-Amz-Request-Id: 1777DFF0E1C62B71
X-Xss-Protection: 1; mode=block
Content-Length: 350
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Server: MinIO
Vary: Origin,Accept-Encoding

 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>Server side encryption specified but KMS is not configured</Message><BucketName>cus360bucket</BucketName><Resource>/cus360bucket/</Resource><RequestId>1777DFF0E1C62B71</RequestId><HostId>eca2f7943b254b3892e77f97f5f8f1af117df9661ae8f3febe2da1a6768504f9</HostId></Error>

**Comment by shtripat** [comment]
I feel you need to set ENV var `MINIO_KMS_KES_KEY_NAME`

**Comment by harshavardhana** [comment]
Key name is not enabled so we don't know which key to use. Please let us know if you have made the relevant 

```
# Add these environment variables to the existing environment file

MINIO_KMS_KES_ENDPOINT=https://HOSTNAME:7373
MINIO_KMS_KES_CERT_FILE=/opt/minio/certs/minio-kes.cert
MINIO_KMS_KES_KEY_FILE=/opt/minio/certs/minio-kes.key

# Allows validation of the KES Server Certificate (Self-Signed or Third-Party CA)
# Change this path to the location of the KES CA Path
MINIO_KMS_KES_CAPATH=/opt/kes/certs/kes-server.cert

# Sets the default KMS key for the backend and SSE-KMS/SSE-S3 Operations)
MINIO_KMS_KES_KEY_NAME=minio-backend-default-key

# Optional, defines the name for the KES server enclave to use.
MINIO_KMS_KES_ENCLAVE=<name>
```

List of mandatory settings and optional settings.

**Comment by bhara03021989** [comment]
@harshavardhana  Thank you for your reply . 
I did put the above env variables - the minio service failed to start and the error as below :
Exiting on signal: TERMINATED
ERROR Unable to initialize a connection to KES as specified by the shell environment: Method Not Allowed
ERROR Unable to initialize a connection to KES as specified by the shell environment: Method Not Allowed

Then , I removed all the keys in the vault and tried again still it failed with the above error . 
Then , I put this env variable "MINIO_KMS_KES_KEY_NAME=minio-default-key" and then it started. 

I was able to create the keys as below :
**mc encrypt set sse-kms minio-key-encrypt-bucket minioroot/cus360bucket**
Auto encryption configuration has been set successfully for minioroot/cus360bucket 

Now , I am no more able to login to the console . It says "not authorized: insufficient permissions"

Can you guide me whats going on here ?

**Comment by harshavardhana** [comment]
> I did put the above env variables - the minio service failed to start and the error as below : Exiting on signal: TERMINATED ERROR Unable to initialize a connection to KES as specified by the shell environment: Method Not Allowed ERROR Unable to initialize a connection to KES as specified by the shell environment: Method Not Allowed

Yeah you are not pointing to the correct KES URL.

**Comment by bhara03021989** [comment]
@harshavardhana  The issue is not the KES URL as you see from my comment above . 
Now , I am no more able to login to the console . It says "not authorized: insufficient permissions"

**Comment by bhara03021989** [comment]
As you see in my comment above :
"MINIO_KMS_KES_KEY_NAME=minio-default-key" has become a mandatory field to have else minio will not start and throw the error as "ERROR Unable to initialize a connection to KES as specified by the shell environment: Method Not Allowed"

the second point is , I am no more able to login to the console . It says "not authorized: insufficient permissions". Can you please re-open the issue  or should i create a new one ?

**Comment by harshavardhana** [comment]
> @harshavardhana The issue is not the KES URL as you see from my comment above . Now , I am no more able to login to the console . It says "not authorized: insufficient permissions"

yeah this is because your kes is not configured correctly - your kes-config.yaml needs 

```
# Create a policy named 'minio' that grants access to the
# /create, /generate, and /decrypt KES APIs for any key name
# KES uses mTLS to grant access to this policy, where only the client
# whose TLS certificate hash matches one of the "identities" can
# use this policy. Specify the hash of the MinIO server TLS certificate
# hash here.
policy:
  minio:
    allow:
    - /v1/key/create/*   # You can replace these wildcard '*' with a string prefix to restrict key names
    - /v1/key/generate/* # e.g. '/minio-'
    - /v1/key/decrypt/*
    - /v1/key/bulk/decrypt
    - /v1/key/list
    - /v1/status
    - /v1/metrics
    - /v1/log/audit
    - /v1/log/error
```

**Comment by harshavardhana** [comment]
Please read the documentation here https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html

**Comment by bhara03021989** [comment]
Let me explain . 
We have LDAP enabled . Without SSE -KMS , It was working well with specific policy attached to AD groups . 

Now ,  SSE-KMS  is set up , since KES uses mTLS so have put the Kes-ca.crt in the default /home/minio/.minio/CAs so that minio can communicate with KES . 
The Identity mentioned in the KES-config.yml is of our minio-public.crt. 
I understand, with Identity hash it will take up the policy mentioned in kes-config.yml . 

Now , since LDAP is enabled and how do I make use of the Groups of LDAP to have their identity hash ? That's my question. Hope I am able to put things now in detail . Appreciate your response and time . Do let me know how must I proceed !

**Comment by bhara03021989** [comment]
My Kes-config is :

address: 0.0.0.0:7373

admin:
  identity: disabled

tls:
  key: /home/minio/kes-certs/kes/kes-server.key
  cert: /home/minio/kes-certs/kes/kes-server.crt

policy:
  kes-policy:
    allow:
    - /v1/key/create/minio-key*
    - /v1/key/generate/minio-key*
    - /v1/key/decrypt/minio-key*
    - /v1/key/list
    - /v1/status
    - /v1/metrics
    - /v1/log/audit
    - /v1/log/error
    identities:

    - 50eb1ef82f14f672fbf3d347e3cc2xxxxxxxx32d0f9b666c739929f29a9f07e9

keystore:
   vault:
     endpoint: https://example.host.com:8200
     engine: "kv/"
     version:  v1
     approle:
       id:     "a2a6316a-0aee-d4a7-09cf-05f1082ec8ac"
       secret: "78badc6b-bc89-bc48-935d-6faf0adff93d"
       retry:  15s
     status:
       ping: 10s
     tls:
       ca: /home/minio/kes-certs/kes/vault_server.crt


But still I am getting authorized error :
./kes policy ls  -k
Error: failed to list policies: not authorized: insufficient permissions

Even though i have list API granted in the config .

**Comment by bhara03021989** [comment]
I am able to create the key :
curl --key /home/minio/.minio/certs/private.key --cert /home/minio/.minio/certs/public.crt --request POST   'https://172.29.xx.xxxx:7373/v1/key/create/minio-key-bucket-1' -k

But unable to list the key . 

curl --key /home/minio/.minio/certs/private.key --cert /home/minio/.minio/certs/public.crt --request GET 'https://172.29.xx.xxx:7373/v1/key/list/minio-key*' -k
{"message":"not authorized: insufficient permissions"}
