### ISSUE TITLE
KES list "message":"not authorized: insufficient permissions"

### ISSUE THREAD

**Issue by bhara03021989** [minio/minio#17813]
kes Version :

 2023-07-26T11-13-07Z

Minio Version:

minio version RELEASE.2023-06-09T07-32-12Z (commit-id=6b7c98bd0fde630c6aee78d702b9d37b0200f52c)
Runtime: go1.19.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

Kes-config.yaml:
==============
address: 0.0.0.0:7373

admin:
  identity: disabled

tls:
  key: /home/minio/kes-certs/kes/kes-server.key
  cert: /home/minio/kes-certs/kes/kes-server.crt

policy:
  minio:
    allow:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    - /v1/key/list
    - /v1/status
    - /v1/metrics
    - /v1/log/audit
    - /v1/log/error
    identities:

    - 50eb1ef82f14f672fbf3d347e3cc2380a78eb32d0f9b666c739929f29a9f07e9

log:
        error : on
        audit : on
keystore:
   vault:
     endpoint: https://example.host.com:8200
     engine: "kv/"
     version:  v1
     approle:
       id:     "a2a6316a-0aee-d4a7-09cf-05f1082ec8ac"
       secret: "55a4a695-9faa-772f-7dec-3c5b6f4da31e"
       retry:  15s
     status:
       ping: 10s
     tls:
       ca: /home/minio/kes-certs/kes/vault_server.crt

The identity has all the required access. 
I am able to create / decrypt/generate but not able to list the keys . 

curl  --key /home/minio/.minio/certs/private.key --cert /home/minio/.minio/certs/public.crt --request GET 'https://172.xx.xx.xxx:7373/v1/key/list/minio-*' -k

**{"message":"not authorized: insufficient permissions"}**

**Comment by harshavardhana** [comment]
Your policy is wrong

```
- /v1/key/create/*
- /v1/key/generate/*
- /v1/key/decrypt/*
- /v1/key/list*
- /v1/status
- /v1/metrics
- /v1/log/audit
- /v1/log/error
```

**Comment by bhara03021989** [comment]
working now changing it to :

policy:
  minio:
    allow:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    - /v1/key/list/*

The documentation needs to be updated took me days on this to work on :-(
Documentation says :

    - /v1/key/list instead of /v1/key/list/*
