### ISSUE TITLE
The cross-domain policy is incorrectly configured. As a result, other users can access other information across domains

### ISSUE THREAD

**Issue by Trae-Young** [minio/minio#17823]
## NOTE
To start minio on Linux, run the following command: /usr/local/minio/minio server --console-address ":60000" --address ":9999" http://ip/data{1.. 16}/minio
It can run smoothly, scan ip:9999 for vulnerabilities, and find vulnerabilities: Improper configuration of cross-domain policy causes other users to access other information across domains, such as:

《cross-domain-policy》
《site-control permitted-cross-domain-policies="all"/》
《allow-access-from domain="*"/》 //The configuration is global, that is, access from any domain is allowed, resulting in cross-domain access vulnerabilities
《/cross-domain-policy》

Hazards: Can be used for cross-domain access and can lead to attacks such as "cross-site forgery requests" or "cross-site eye-tracking" (variations of "cross-site scripting"), resulting in other users' information being read illegally.

## Expected BehaviorThe cross-domain policy is incorrectly configured. As a result, other users can access other information across domains

My problem is probably related to cross-domain policy configuration. As a rookie, I don't know how to solve this vulnerability.

## Possible Solution

Modify the flash security policy to restrict it strictly, for example, to the current domain of the website.

## Steps to Reproduce (for bugs)

1./usr/local/minio/minio server --console-address ":60000" --address ":9999" http://ip/data{1.. 16}/minio
2.There are no other parameters except the account and password.
3.The url detected by the vulnerability is http://ip:9999/.

## Your Environment

* Version used (`minio --version`):   minio version RELEASE.2022-05-26T05-48-41Z
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux  3.10.0-1160.92.1.el7.x86_64   x86_64 x86_64 x86_64 GNU/Linux

**Comment by jiuker** [comment]
What's the minio version you used?

**Comment by Trae-Young** [comment]
> What's the minio version you used?

I've re-edited my question！  minio version RELEASE.2022-05-26T05-48-41Z

**Comment by jiuker** [comment]
We will not support too old minio version for community.
