### ISSUE TITLE
XL: Functional load test failure.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1782]
**TestGetObjectClosedTwice** and **TestFPutObject** from the exec-concurrent load tests are failing on the rewrite-xl branch.

**Comment by harshavardhana** [comment]
This is fixed.. there is a problem in how the locking is handled. The issue is between GetObject and RemoveObject()

**Comment by GarimaKapoor** [comment]
If the issue is fixed we should close it! If the problem is somewhere else we should open the appropriate bug!
