### ISSUE TITLE
Not able to open Minio console in browsers like chrome and Edge

### ISSUE THREAD

**Issue by Anushakallam** [minio/minio#17832]
HI Team , 

I have used RELEASE.2022-07-24T17-09-31Z and also RELEASE.2022-03-05T06-32-39Z .
I have seen a strange behavior where some of our team members are able to access the console and able to login.

but for others when we hit the URL , the page tries to load and after that the login prompt won't appear.
So we have tried to clear the browser cache and also tried to reboot the system and connected to mobile hotspot instead of internet provided by ISP .

The page opened and able to login, but when I tried to refresh again the same issue occurs. the page tries to load and it won't give login prompt .

We have deployed minio as a statefulset and deployment file in kubernetes cluster.

But few people are able to access with out any issues .. Can you please help here.

## Expected Behavior
The URL should open to everyone - Minio console.

## Current Behavior
It opens for few users and they are able to access without any issues.

* Version used (`minio --version`): RELEASE.2022-07-24T17-09-31Z
We have downloaded this image and uploaded to our cloud repository.
* Server setup and configuration:
* # Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"minio","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"minio"}},"serviceName":"minio","template":{"metadata":{"labels":{"app":"minio"}},"spec":{"containers":[{"args":["server","/data","--address",":9000","--certs-dir","/root/.minio/certs/","--console-address",":9001"],"envFrom":[{"configMapRef":{"name":"vpd-config"}}],"image":"vpdacr.azurecr.io/minio:2022-03-05","name":"minio","ports":[{"containerPort":9000},{"containerPort":9001}],"volumeMounts":[{"mountPath":"/data","name":"minio-data"},{"mountPath":"/root/.minio/certs","name":"secret-volume"}]}],"imagePullSecrets":[{"name":"acrsecret"}],"volumes":[{"name":"minio-data","persistentVolumeClaim":{"claimName":"minio-pv-claim","volumes":null}},{"name":"secret-volume","secret":{"items":[{"key":"bundle.crt","path":"public.crt"},{"key":"private.key","path":"private.key"},{"key":"bundle.crt","path":"CAs/public.crt"}],"secretName":"nginx"}}]}}}}
  creationTimestamp: "2022-08-08T05:16:25Z"
  generation: 26
  name: minio
  namespace: default
  resourceVersion: "202810569"
  uid: 5c1989a2-a64f-473a-a3a2-71a21dcd74a1
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-08-07T15:30:04+05:30"
      creationTimestamp: null
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        - --address
        - :9000
        - --certs-dir
        - /root/.minio/certs/
        - --console-address
        - :9001
        envFrom:
        - configMapRef:
            name: vpd-config
        image: vpdacr.azurecr.io/minio:2022-07-24
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: minio-data
        - mountPath: /root/.minio/certs
          name: secret-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acrsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pv-claim
      - name: secret-volume
        secret:
          defaultMode: 420
          items:
          - key: bundle.crt
            path: public.crt
          - key: private.key
            path: private.key
          - key: bundle.crt
            path: CAs/public.crt
          secretName: nginx
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: minio-54d57789c5
  observedGeneration: 26
  readyReplicas: 1
  replicas: 1
  updateRevision: minio-54d57789c5
  updatedReplicas: 1

* Operating System and version (`uname -a`): Kubernetes version 1.21

**Comment by jiuker** [comment]
1. We only support latest minio's version for community. Your version is too old.
2. We support the offical minio image, not for `vpdacr.azurecr.io/minio:2022-07-24`.

You can upgrade it to reproduce the issue. And open another issue for this.
 Or try to get the business support. @Anushakallam
