### ISSUE TITLE
MinIO supports SAML authentication

### ISSUE THREAD

**Issue by nehrajagan** [minio/minio#17868]
I want to integrate MinIO with Keycloak using SAMLAuthN/Authz is performed in KeycloakUser to authenticate user at one place.
I have done configuration in the keycloak and want redirect from MinIO . What should do MinIO side to connect using SAML protocol.

**Comment by harshavardhana** [comment]
No please use OIDC with Keycloak, if you have a commercial requirement then please reach out to us at hello@minio.io
