### ISSUE TITLE
minio memory keeps increasing

### ISSUE THREAD

**Issue by sathishkumar-p** [minio/minio#17869]
## minio memory keeps increasing
I deployed minio with 4 drivers and 4 servers clusters with help of minio operator. Allocated 4GB of Memory for each server. I can see there is gradually increasing the RAM usage. Once its reaches the limit the POD crash and post restart the memory usage will be 500MB from GB.

## Expected Behavior
Garbage collector not cleaning the memory of the minio pod. 

## Current Behavior
Minio POD memory is gradually increasing even when its unused.

## Steps to Reproduce (for bugs)
1. Deployed minio 4 drivers and 4 servers
2. Wait for a few days
3. you can see the ram usage high

## Your Environment
* Version used (`minio --version`): RELEASE.2023-06-23T20-26-00Z 
* Server setup and configuration: Kubernetes Minio operator 4 server and 4 drivers per node
* Operating System and version (`uname -a`): Kubernetes cluster

**Comment by harshavardhana** [comment]
@sathishkumar-p please capture `mc support profile` output

**Comment by harshavardhana** [comment]
Also please use the latest release RELEASE.2023-08-16T20-17-30Z and then report the issue.
