### ISSUE TITLE
Data loss from multiple calls to CompleteMultipartUpload object in a short period of time

### ISSUE THREAD

**Issue by klauspost** [minio/minio#17863]
### Discussed in https://github.com/minio/minio/discussions/17859

<div type='discussions-op-text'>

<sup>Originally posted by **xieys0** August 16, 2023</sup>
## Environment
OS:  Ubuntu22.04.1
Version:  https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230809233022.0.0_amd64.deb

# df -HT
root@ubuntu:~# df -hT
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs  6.3G  2.2M  6.3G   1% /run
/dev/sda2      ext4   479G   12G  443G   3% /
tmpfs          tmpfs   32G     0   32G   0% /dev/shm
tmpfs          tmpfs  5.0M     0  5.0M   0% /run/lock
/dev/sda1      vfat   1.1G  6.1M  1.1G   1% /boot/efi
tmpfs          tmpfs  6.3G  4.0K  6.3G   1% /run/user/0
/dev/sdb       xfs    7.3T   52G  7.3T   1% /mnt/disk1
/dev/sdc       xfs    7.3T   52G  7.3T   1% /mnt/disk2
/dev/sdd       xfs    7.3T   52G  7.3T   1% /mnt/disk3
/dev/sde       xfs    7.3T   52G  7.3T   1% /mnt/disk4

# cat /etc/default/minio
MINIO_ROOT_USER=xxxx
MINIO_ROOT_PASSWORD=xxxx
MINIO_OPTS="--address :9000 --console-address :9001"
MINIO_VOLUMES="/mnt/disk{1...4}"

## Describe
Calling the CompleteMultipartUpload interface multiple times for the same uploadId in a short period of time. The first call returned success, while the other returned uploadId does not exist. The object information can be found, but the object data is missing and cannot be downloaded or restored. There are only xl. meta files in the object folder.

root@ubuntu:/mnt/disk1/test/0CA985D3589645E49ADFAF4391FA754D# ls -la
total 4
drwxr-xr-x 2 minio-user minio-user  29 Aug 15 11:14 .
drwxr-xr-x 3 minio-user minio-user  54 Aug 15 11:14 ..
-rw-r--r-- 1 minio-user minio-user 844 Aug 15 11:14 xl.meta

## Expected Behavior
Object data is not lost

## Current Behavior
Object data is not lost

## Notes
Historical versions and Ubuntu multi node and multi driver environments can still be replicated</div>

**Comment by klauspost** [comment]
(repro in discussion)

**Comment by harshavardhana** [comment]
So I tried reproducing I can't reproduce this on my end

```
~ go test -v --count=100
=== RUN   TestDemo
NewMultipartUpload end, uploadId= ZmIyM2VkNzctMzExZS00NDkwLTgzOGMtNjg4MzgzNDk5NDBmLjNiNjVhZjY5LTNkMzctNDNiMS1hZWFlLWNjMzYxZTk5NWI4Yw
PutObjectPart end
uploadId2= d9b6fe4b-59f6-4ffe-a60a-5b576d7edd5a
Second {   0 0001-01-01 00:00:00 +0000 UTC   0001-01-01 00:00:00 +0000 UTC     }    One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
First {test testObject.data 6a7a32f75cec39d7f42e0d826dc636b7-100 0 0001-01-01 00:00:00 +0000 UTC http://localhost:9000/test/testObject.data  0001-01-01 00:00:00 +0000 UTC     }    <nil>
CompleteMultipartUpload end
--- PASS: TestDemo (2.39s)
```

@klauspost

**Comment by harshavardhana** [comment]
Okay this is actually a nuanced bug because of the interchangeable usage of `base64-uploadID` and `uuid-uploadID` 

In-fact this is incorrectly used in the code itself which causes two locks to be given concurrently on the same path leading to corruption which is expected if there is no serialization.

The fix is to ensure that UUID can never be specified as the uploadID to avoid different locks operating on the same content.
