### ISSUE TITLE
start minio ”fatal error: all goroutines are asleep . deadlock!“

### ISSUE THREAD

**Issue by zzx1314** [minio/minio#17862]
**Is your feature request related to a problem? Please describe.**
I start minio print the following error message，can you help me , what is the reason for this problem

![image](https://github.com/minio/minio/assets/20176085/8518d993-d723-4451-b8d4-2b432e721e5b)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by klauspost** [comment]
This isn't a "guess what the reporter is running" game. Open an issue where you provide the requested information.
