### ISSUE TITLE
minio Package on Chocolatey?

### ISSUE THREAD

**Issue by Vacant0mens** [minio/minio#17887]
**Is your feature request related to a problem? Please describe.**
Minio Packages on Chocolatey.org are over 2 years old.

**Describe the solution you'd like**
an automated way to add the server and client packages to Chocolatey so that automating installs is easier on Windows.

**Additional context**
the listing for the packages say they used to be maintained by `elpatron`, but I'm not sure if it was something they did on their own or if they were actually part of this project.
It would be good if there was a step in the CI/CD pipeline to automatically create the chocolatey packages and send them to chocolatey so that one person wouldn't have to maintain it all the time.

**Comment by harshavardhana** [comment]
We do not maintain it, and we are not planning to maintain it either. We are currently maxed on our bandwidth on various types of package delivery mechanisms.

We are happy to give our blessing to any community-maintained project. Thank you for your understanding.
