### ISSUE TITLE
MINIO_BROWSER_SESSION_DURATION not working

### ISSUE THREAD

**Issue by mrvanes** [minio/minio#17902]
I compiled minio @master
As per merged PR https://github.com/minio/minio/pull/17885 I added MINIO_BROWSER_SESSION_DURATION=1h
Console still expires session after OIDC `exp` claim datestamp.

This invalidates the remark that https://github.com/minio/minio/pull/17885 supersedes https://github.com/minio/minio/pull/17882#issuecomment-1686706075

## Expected Behavior
Console browser session lives as long as MINIO_BROWSER_SESSION_DURATION setting.

## Current Behavior
Console browser session expires on OIDC `exp` claim datestamp.

## Possible Solution
https://github.com/minio/minio/pull/17882

## Steps to Reproduce (for bugs)
1. Compile minio @master
2. Configure OIDC provider
3. Set MINIO_BROWSER_SESSION_DURATION environment variable to something higher than `exp - now`.
4. Login using OIDC
5. Use session after `exp` claim datestamp -> Console session expired, before MINIO_BROWSER_SESSION_DURATION

## Context
https://github.com/minio/minio/issues/16308
https://github.com/minio/minio/issues/16672
https://github.com/minio/console/issues/2511

## Regression
No

## Your Environment
* Version used (`minio --version`): minio version DEVELOPMENT.2023-08-23T10-07-06Z (commit-id=af564b8ba07a7805a578b5f6f2b3827490f74ccd)
* Server setup and configuration: Local deployment
* Operating System and version (`uname -a`): `6.4.11 #7 SMP Sat Aug 19 11:16:47 CEST 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mrvanes** [comment]
The reason why https://github.com/minio/minio/pull/17885 doesn't work is this:
https://github.com/minio/minio/blob/master/internal/config/identity/openid/jwt.go#L130

**Comment by cesnietor** [comment]
we'll take a look @mrvanes  thanks for raising.

**Comment by cesnietor** [comment]
@dvaldivia to add more details on what'd be needed.

**Comment by bpedersen2** [comment]
Seems like a correct behaviour to me. The code expects that  the openid supports offline sessions (which would  typically have a long expiry)  as no refresh token handling seems to be used ( I admit, I did not check in the console FE code wether token refesh happens there).  

So did you try, if it works as  expected if you add offline_access to the scope requested from minio?

**Comment by mrvanes** [comment]
I don't get it.
The code currently doesn't refresh the token and the FE session is closed after the `exp` claim time expires. As described earlier, this is incorrect behaviour because the `exp` claim does not mandate relying party sessions, it mandates the expiration of the token itself, and leaves session expiration to the RP.
I have not experimented with `offline_access`, but as I described that makes no sense since minio should not care about the `exp` claim in the first place.

**Comment by bpedersen2** [comment]
Well, the behaviour now is: 
  if the token has a long expiry, clamp it to MINIO_BROWSER_SESSSION_DURATION, if it is shorter, don' t  prolong it. Seems like a  resonable choice securitywise to  me (  an externally managed expiry can not exceed a minio configured  expiry).

You need a correct configuration on both ends.

**Comment by mrvanes** [comment]
No it's not.

Minio admins usually don't have access to the expiry of the OIDC token and end-users expect to be able to use the FE longer than the token expiry duration (which normally is set to something like minutes, because the token will be _consumed_ within seconds after releasing). It can not be stressed enough that minio gets the `exp` claim wrong, please take your time reading up on the OIDC Core specifications about how the _token_ should be _validated_

https://openid.net/specs/openid-connect-core-1_0.html#IDToken
https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by bpedersen2** [comment]
I find nothing in there which forbids the current behaviour. I would say it is a missing  refresh_token flow in minio, so the console should check if a refersh token is  available, and it  that case try to renew the session.

**Comment by bpedersen2** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens

**Comment by mrvanes** [comment]
You're right, the spec doesn't forbid using the `exp` claim to expire relying party sessions, it's just not intended to be used that way and harms the users of minio.

Unfortunately, you can not use `refresh_tokens` to mimic OP session expiration for the same reason: they're not intended to be used like that and you are not guaranteed to receive the `refresh_token` grant_type. Even if you do, the invalidation of refresh tokens is at the discretion of the end-user, effectively making the RP session indefinite because, like I said, there is no way for the OP to express RP side session expiration. That is (and should be) at the discretion of the relying party, as they _ultimately_ are responsible for the exposed data and _security conditions_ under which it should be accessed.

**Comment by bpedersen2** [comment]
See also https://github.com/minio/console/issues/2643

**Comment by harshavardhana** [comment]
fixed via #18297
