### ISSUE TITLE
Invalid metadata visible in Minio web console

### ISSUE THREAD

**Issue by michalchrust** [minio/minio#17903]
## Expected Behavior
My team uses Minio and minio web console for object management. Every object we upload is pushed with process uid hold for it in a database, every process also has its name that is uploaded as metadata too. Some of objects are uploaded twice to two separate buckets. Despite it is the same file in two locations it is uploaded with different process uid and process name. It is expected that in minio console, every of these object will hold its own process uid and process name.

## Current Behavior
Unfortunately, we spotted, that minio object present in one bucket can have process uid and process name, that belongs to another object and the same with second object. Shown values changes between page refresh.

## Steps to Reproduce (for bugs)
Upload the same object to two separate buckets with different prefixes and metadata. For metadata it is important to provide the same key, but a different value for each object.

## Your Environment

* Version used 2023-06-02T23:17:26Z

**Comment by harshavardhana** [comment]
@MichalChrust please provide a more proper reproducer. 

There is no screenshot or nothing shared for us to see what you are seeing.

**Comment by michalchrust** [comment]
This would be as easiest example:
When I select file 202308110900.tar.gz value of metadata keys X-Amz-Meta-Flowcode and X-Amz-Meta-Processuid can vary as in the below example. I just reclicked the same item in same location. What is important, somewhere in different bucket, there is exactly the same file that contains this second set of metadata.

before refresh:
![image](https://github.com/minio/minio/assets/49342519/25f63b95-5b6c-4718-a5cf-478066a02e09)
After refresh
![image](https://github.com/minio/minio/assets/49342519/bb11be59-f2b1-434a-b180-fb7614d925b6)
