### ISSUE TITLE
SFTP server seems limited to one connection at a time.

### ISSUE THREAD

**Issue by colbee1** [minio/minio#17914]
## NOTE

Want to upload file into bucket using the SFTP capability of minio using FilleZilla.

## Expected Behavior
Upload succeeded

## Current Behavior
The first connection is ok, I can browse over buckets.
When I want to upload a file, FilleZilla open a new connection: waiting, timeout, waiting, timeout...
Connection with minio SFTP server will never get established.

## Steps to Reproduce (for bugs)
1. Connect to minio SFTP server with Fillzilla (using ROOT user in my case)
2. Browse to bucket
3. Upload a file

Or

1. Open two terminal
2. For each one connect to minio sftp server

## Your Environment
Linux: debian 11
Minio version: RELEASE.2023-08-23T10-07-06Z (go1.19.12 linux/amd64)

**Comment by Tipsmark** [comment]
@colbee1  Same problem here, just one connection at the time.... disconnect one and the second comes up immediately. Did you find a solution?
