### ISSUE TITLE
Event Destination - Opensearch Support

### ISSUE THREAD

**Issue by amardeep-s** [minio/minio#17921]
Hi There,

We are trying to configure "Publish Events to Elasticsearch". This works with elasticsearch 7 without any issues.

When we try to connect same with Opensearch 2.9.0 using "Add event destination", it throws error.

Is opensearch not supported?

## Expected Behavior
Opensearch should work with Events and Monitoring because its same as elasticsearch.

## Current Behavior
Error is thrown when adding Opensearch as "Elastic Search Event Destination"
![Screenshot from 2023-08-25 19-59-47](https://github.com/minio/minio/assets/12200525/ac0bf363-72f8-4603-8d29-556887a9bef8)

## Possible Solution
Please confirm if opensearch is supported.

## Steps to Reproduce (for bugs)

1. Run standalone minio server
2. Run a standalone opensearch 2.9.0
3. Go to minio console and add Elastic Search Event Destination

## Your Environment

* minio version RELEASE.2023-07-21T21-12-44Z (commit-id=d004c4538643eb05ea69b919557d5cf7cc332fae)
* docker running on linux
* Linux 5.15.0-78-generic Ubuntu 22.04

**Comment by harshavardhana** [comment]
We have never supported opensearch this is vague to expect elasticsearch target config will work with opensearch.

Please send a PR supporting this as a new target and use their published Go client library.

**Comment by amardeep-s** [comment]
Ok - Thanks.

Can you also confirm if minio will update elasticsearch implementation from a deprecated project https://github.com/olivere/elastic ?

**Comment by harshavardhana** [comment]
We do not use olivere/elastic, we use github.com/elastic/go-elasticsearch/v7

**Comment by amardeep-s** [comment]
Thanks for confirmation. I read this on documentation page https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-elasticsearch.html#publish-events-to-elasticsearch

**Comment by harshavardhana** [comment]
> Thanks for confirmation. I read this on documentation page https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-elasticsearch.html#publish-events-to-elasticsearch

That needs to be updated @ravindk89

**Comment by ravindk89** [comment]
Sure thing - will convert this to a docs issue.
