### ISSUE TITLE
ldap authorization always returns not found if minio is launched after ldap server

### ISSUE THREAD

**Issue by hypercube999** [minio/minio#17926]
I use authentik as ldap directory and docker minio/minio:RELEASE.2023-08-23T10-07-06Z.
Servers are configured and I can login successfully.
But after restarting containers, if minio is started after ldap server (authentik), any attempt to login is unsuccessful, minio displays the message "LDAP server error: Unable to find user DN: User DN for mysuperuser not found".
If you restart the minio, everything works again as required.

## Expected Behavior
Successful authorization in the web interface.

## Current Behavior
An error message is displayed "LDAP server error: Unable to find user DN: User DN for mysuperuser not found"

## Possible Solution
Restart minio or start it after ldap server.

## Steps to Reproduce (for bugs)
1. Install and configure ldap directory server
2. Install and configure minio for authorization via ldap
3. Stop minio and ldap services
4. Launch minio
5. *wait a bit*
6. Start ldap server
7. Try authorization into minio with ldap user

## Your Environment
minio RELEASE.2023-08-23T10-07-06Z
authentik 2023.6.1
5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Yes this is correct, we expect that ldap is running before MinIO is started.

Just like we want the OS to boot first before MinIO is started

Just like we want networking to be available before MinIO is started.
