### ISSUE TITLE
Openldap configuration error

### ISSUE THREAD

**Issue by homuraLan** [minio/minio#17920]
## Expected Behavior
Normal login

## Current Behavior
Unable to log in to the administrator account on the webpage, MC is unable to log in to the ldap account. Please tell me what to do to avoid this issue. What I mean is, when I reverse the situation mentioned earlier, they can log in
![image](https://github.com/minio/mc/assets/96775034/a6cebc9e-763f-43d2-a4a5-5723adca6832)
![image](https://github.com/minio/minio/assets/96775034/741e0118-d030-42f8-a0d4-29fe9bb6f930)

## Steps to Reproduce (for bugs)

1.
```
mc idp ldap add myminio \
   server_addr="ldap.xxxx:636" \
   lookup_bind_dn="cn=admin,xxxx" \
   lookup_bind_password="xxxxx" \
   user_dn_search_base_dn="ou=people,xxxx" \
   user_dn_search_filter="(&(objectClass=inetOrgPerson)(uid=%s))" \
   group_search_filter="(&(objectClass=posixGroup)(memberUid=%s))" \
   group_search_base_dn="ou=group, xxxx" \
   enabled="true" \
   tls_skip_verify="off" \
   server_insecure=off \
   server_starttls="off" \
   srv_record_name="" \
   comment="LDAP configuration for MinIO"
```
2.`mc config host add myminio http://xxx:9000 xxx xxx`

https://github.com/minio/mc/issues/4667

## Your Environment
`mc version RELEASE.2023-08-15T23-03-09Z (commit-id=df68f5cf897d30203bfa3003c0882b3f76edcdd7)
Runtime: go1.19.12 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>`

minio：image: minio/minio:RELEASE.2023-01-20T02-05-44Z.hotfix.e70d789c9

**Comment by harshavardhana** [comment]
It is never documented that you can use mc with ldap.

You are using containers that are not meant for general use by community.

Not sure entirely where you are picking up these instructions from.

Please read the docs.min.io on how to generate service accounts to get ldap setup and use these service accounts with mc.
