### ISSUE TITLE
minio site replication has inconsistent status results

### ISSUE THREAD

**Issue by deajan** [minio/minio#17939]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

When setting up a site replication using `mc admin replicate add site1 site2`, there should be a way to know whether both nodes are in sync or not.

## Expected Behavior
Using `mc admin replicate status site2` when site 2 isn't fully replicated yet should show something like `in progress`, or `7 of 9 files synchronized` or whatever.

## Current Behavior
Currently, `mc admin replicate status site2` is identical to `mc admin replicate status site1` and shows nothing that could indicate that both sites aren't fully synced yet.
```
Bucket replication status:
●  3/3 Buckets in sync

Policy replication status:
●  6/6 Policies in sync

User replication status:
●  2/2 Users in sync

Group replication status:
No Groups present
```

The above is shown even if one is pretty sure that the site replication is not done:
```
# mc admin info site1
●  my.local.test.tld
   Uptime: 1 day
   Version: 2023-05-04T21:44:30Z
   Network: 1/1 OK
   Drives: 4/4 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 4

48 GiB Used, 3 Buckets, 10,018 Objects, 5,129 Versions
4 drives online, 0 drives offline
[root@minio01p ~]# mc admin info site2

●  my.remote.test.tld
   Uptime: 3 minutes
   Version: 2023-08-23T10:07:06Z
   Network: 1/1 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

56 MiB Used, 3 Buckets, 14 Objects, 14 Versions
1 drive online, 0 drives offline
```

I've searched tools like `mc admin replicate resync status` but this one doesn't seem to work.
Also, using details via `mc admin replicate status site2 --json` doesn't give more info
```
{
 "Enabled": true,
 "MaxBuckets": 3,
 "MaxUsers": 2,
 "MaxGroups": 0,
 "MaxPolicies": 6,
 "Sites": {
  "5312d977-defd-4ed7-b5a0-28d337166fbc": {
   "endpoint": "https://my.local.test.tld",
   "name": "minio01p",
   "deploymentID": "5312d977-defd-4ed7-b5a0-28d337166fbc",
   "sync": ""
  },
  "9357ed62-ebdd-4ab0-93e6-29f1aa646ce6": {
   "endpoint": "https://my.remote.test.tld",
   "name": "lacstash",
   "deploymentID": "9357ed62-ebdd-4ab0-93e6-29f1aa646ce6",
   "sync": ""
  }
 },
 "StatsSummary": {
  "9357ed62-ebdd-4ab0-93e6-29f1aa646ce6": {
   "ReplicatedBuckets": 6,
   "ReplicatedTags": 0,
   "ReplicatedBucketPolicies": 6,
   "ReplicatedIAMPolicies": 12,
   "ReplicatedUsers": 4,
   "ReplicatedGroups": 0,
   "ReplicatedLockConfig": 0,
   "ReplicatedSSEConfig": 0,
   "ReplicatedVersioningConfig": 6,
   "ReplicatedQuotaConfig": 0,
   "ReplicatedUserPolicyMappings": 2,
   "ReplicatedGroupPolicyMappings": 0,
   "TotalBucketsCount": 6,
   "TotalTagsCount": 0,
   "TotalBucketPoliciesCount": 6,
   "TotalIAMPoliciesCount": 12,
   "TotalLockConfigCount": 0,
   "TotalSSEConfigCount": 0,
   "TotalVersioningConfigCount": 6,
   "TotalQuotaConfigCount": 0,
   "TotalUsersCount": 4,
   "TotalGroupsCount": 0,
   "TotalUserPolicyMappingCount": 2,
   "TotalGroupPolicyMappingCount": 0
  }
 },
 "BucketStats": {},
 "PolicyStats": {},
 "UserStats": {},
 "GroupStats": {}
}
```
## Possible Solution
?

## Steps to Reproduce (for bugs)
1. Create two minio instances
2. Active site to site replication
3. Before both sites have roughly the same number of files, there's no way to tell if sites are fulle synced

## Context
I was actually trying minio to see whether I could use it for enterprise backups. I would like the backups to be replicated.
The actual test was to move a minio server from place 1 to place 2 by using site migrations.

## Regression
Don't know, first time user.

## Your Environment

Minio version
```
minio version RELEASE.2023-05-04T21-44-30Z (commit-id=5569acd95cbc8c7d3fac59cf2aba77baa1b9bbeb)
Runtime: go1.20.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

Linux version: RHEL 9.2
```
Linux minio01.lab.local 5.14.0-284.25.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Aug 8 04:07:27 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@deajan you should really be using latest release here

Please upgrade the setup first and then perform your tests.

**Comment by deajan** [comment]
Sorry, indeed, I didn't change minio version over time of tests.
I've redone the same replication test setup after upgrading minio version to
```
minio version RELEASE.2023-08-23T10-07-06Z (commit-id=af564b8ba07a7805a578b5f6f2b3827490f74ccd)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

I got about the same results as described above, ie no way to see whether site to site replication nodes are fully synced or not.

**Comment by harshavardhana** [comment]
> Sorry, indeed, I didn't change minio version over time of tests. I've redone the same replication test setup after upgrading minio version to
> 
> ```
> minio version RELEASE.2023-08-23T10-07-06Z (commit-id=af564b8ba07a7805a578b5f6f2b3827490f74ccd)
> Runtime: go1.19.12 linux/amd64
> License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> Copyright: 2015-2023 MinIO, Inc.
> ```
> 
> I got about the same results as described above, ie no way to see whether site to site replication nodes are fully synced or not.

To know you need to use `mc replicate diff` 
Scanner usage gets updated asynchronously it is not realtime.

**Comment by deajan** [comment]
Does `mc replicate diff site/bucket` work for site replication ?
For me, it doesn't return anything, which could of course mean that everything works right.

I've setup a fresh replication, to make sure both nodes are out of sync:
```
# mc admin info site1
●  site1.local
   Uptime: 7 hours
   Version: 2023-08-23T10:07:06Z
   Network: 1/1 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

48 GiB Used, 3 Buckets, 10,871 Objects, 15,843 Versions, 4,346 Delete Markers
1 drive online, 0 drives offline

# mc admin info site2
●  site2.local
   Uptime: 1 minute
   Version: 2023-08-23T10:07:06Z
   Network: 1/1 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

106 MiB Used, 3 Buckets, 67 Objects, 69 Versions
1 drive online, 0 drives offline
```

As said earlier, replicate status isn't verbose enough
```
# mc admin replicate status site2
Bucket replication status:
●  3/3 Buckets in sync

Policy replication status:
●  6/6 Policies in sync

User replication status:
●  2/2 Users in sync

Group replication status:
No Groups present
```

Now when using
```
# mc replicate backlog site2/bucket1
```

I get no viable info
```
∙●∙

enter/spacebar  • ↓/j Move down • ↑/k Move up • q quit
```

So of course if this only shows replication failures, I may not get any errors.
Still, I have no way to know if two nodes are out of sync.

**Comment by deajan** [comment]
Okay, adding `--full` begins to be helpful here:
```
# mc replicate diff site1/bucket1 --full
Unreplicated versions summary
───────────────────────────
Total Unreplicated: 5070 •


┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Attempted At             Created                  Status     VersionID                             Op   Object
│──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│                          2023-08-29 11:55:14 UTC  FAILED     c3f1d49c-c297-44c7-9fa5-384a28d27a16  DEL  somedata/01H8JSH02MT4M09ED23RM8F48Q/chunks/000001
│                          2023-08-29 11:55:14 UTC  FAILED     883b9979-c398-44fa-9df6-14595d8b8403  DEL  somedata/01H8JSH02MT4M09ED23RM8F48Q/deletion-mark.
│                          2023-08-29 11:55:14 UTC  FAILED     15f6fec1-fbc8-4398-898f-e9856be7964b  DEL  somedata/01H8JSH02MT4M09ED23RM8F48Q/index
│                          2023-08-29 11:55:14 UTC  FAILED     a4002eeb-ef4b-4500-8641-0c5fad149103  DEL  somedata/01H8JSH02MT4M09ED23RM8F48Q/meta.json
│                          2023-08-29 11:55:14 UTC  FAILED     e908b979-2653-4a9f-9fd6-29090f84e1a4  DEL  somedata/01H8JSH02MX4WF69J1SEHR8GQP/chunks/000001
│                          2023-08-29 11:55:14 UTC  FAILED     2ee15eeb-be99-4f51-adc1-948f07815578  DEL  somedata/01H8JSH02MX4WF69J1SEHR8GQP/deletion-mark.
│                          2023-08-29 11:55:14 UTC  FAILED     ed956ff1-9eab-4ac5-a54e-4f40c8a9a5b9  DEL  somedata/01H8JSH02MX4WF69J1SEHR8GQP/index
│                          2023-08-29 11:55:14 UTC  FAILED     d62e1d9c-80ca-41c1-8aef-63867a2468cd  DEL  somedata/01H8JSH02MX4WF69J1SEHR8GQP/meta.json
│                          2023-08-29 11:55:14 UTC  FAILED     cb541435-77f6-4e7f-9bab-010bde8131ab  DEL  somedata/01H8K0PVJX7XXX7JNPZ5282N14/chunks/000001
│                          2023-08-29 11:55:14 UTC  FAILED     f7af1900-95ec-4af3-a738-1bcd23fef9c2  DEL  somedata/01H8K0PVJX7XXX7JNPZ5282N14/deletion-mark.
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# mc replicate diff site2/bucket1 --full
Unreplicated versions summary
────────────────────────
Total Unreplicated: 2 •


┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ Attempted At             Created                  Status     VersionID                             Op   Object
│──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ 0001-01-01 00:00:00 UTC  2023-08-29 13:00:45 UTC             ac1d1b95-a729-45b8-92a7-13c2146c950b  PUT  somedataother/01H90P2ZT7EBYZ7GFP2TS17GRC/chunks/000001
│ 0001-01-01 00:00:00 UTC  2023-08-29 13:07:02 UTC             18dba0ec-8cbc-4601-83bb-95f34ae20419  PUT  somedataother/01H90PF42KGQMXKK95K5V64EXH/chunks/000001
│
│
│
│
│
│
│
│
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
enter/spacebar  • ↓/j Move down • ↑/k Move up • q quit
```

I've searched in the prometheus metrics to find anything related to the site replication.
Is there a metric that shows whether site replication works and/or is fully synced ?

**Comment by poornas** [comment]
>I've searched in the prometheus metrics to find anything related to the site replication.

there are metrics related to site replication in latest release. 

> Is there a metric that shows whether site replication works and/or is fully synced ?

you can look at bucket replication statuses to verify at the bucket level - unless you stopped all incoming uploads, the syncing is a continuous process.

If you are doing a one time copy - you should be using batch jobs for this..

**Comment by harshavardhana** [comment]
The metrics have been re-implemented fully, please upgrade and let us know how it goes. Feel free to respond back to this issue we shall re-open and further investigate. 

thank you

**Comment by Vitorio88** [comment]
Good day everyone. I have the following MINIO settings
2 balancers with 4 nodes each
A replica site is configured
Such a question, with the help of a script we load from the Oracle database into one of the buckets of the required data, for example, on 1 cluster on which a replica was created, there is less data and the volume shows less on the web, and on the second cluster the entire volume.
When executing the command mcli du kiev/reports
everything is true both on 1 cluster and on the second
Minio version 2024-02-17T01:15:57Z
The settings are all identical
1 balancer
4 nodes with 4 disks of 50 GB each
When executing the command on one of the balancers of the mcli du kiev/reports command, the calculation is very long, a long delay of more than an hour, on another cluster after 20 minutes, the data volume is 7.1 Gigabytes and the data amount is 746000
Why can there be a delay, I receive information about the cluster perfectly
Thanks for any information, help
