### ISSUE TITLE
m3u8 and ts file are saved as folder using minio container

### ISSUE THREAD

**Issue by newtondotcom** [minio/minio#17930]
m3u8 and ts file are saved as folder when using minio  gui in a docker container, so the files are corrupted.

## Expected Behavior
Files to be usable because they are not and i lost 2 days on this issue.

## Current Behavior
When uploading via gui, the files are saved as folder containing xml and an other type uninteresting. 

## Steps to Reproduce (for bugs)
Try to upload a m3u8 & ts files (elements of an hls project) throught  the minio gui

## Context
I was trying to host a hls project on my S3 to access videos with video-js, to bypass huge tech giants with cookies and paid subscriptions.

## Your Environment

* Version used (`minio --version`): 
minio version RELEASE.2023-08-23T10-07-06Z (commit-id=af564b8ba07a7805a578b5f6f2b3827490f74ccd)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
* Server setup and configuration:
docker running with portainer, hls hosted on apache2
* Operating System and version (`uname -a`): 
Linux vmi1386237.contaboserver.net 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@newtondotcom this is normal and expected. The directory is a data format in how the files are stored as objects on MinIO.
