### ISSUE TITLE
unable to perform read operation with 1/2 nodes storage_class standard=EC:8 rrs=EC:1

### ISSUE THREAD

**Issue by bolshoib** [minio/minio#17935]
Hi,

First of all, thank you for your work and this great tool, MinIO.
I installed MinIO,  Version: 2023-08-16T20:17:30Z
MNMD mode. On linux RHEL 8.8 VM (VmWare)

Our infrastructure is fully virtualized

I have 4 nodes (4 VMs RHEL) with 4 disks each. (Xfs formatted)

I configured storage_class :
mc admin config get miniolab storage_class
storage_class standard=EC:8 rrs=EC:1

When I stop 1 node, I can read and write. Create a bucket, list objects etc. It's ok.
When I stop 2 nodes. I can't do anything. I can't read (or write).

●  miniolab1:9000
   Uptime: 30 minutes
   Version: 2023-08-16T20:17:30Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  miniolab2:9000
   Uptime: 10 seconds
   Version: 2023-08-16T20:17:30Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  miniolab3:9000
   Uptime: 30 minutes
   Version: 2023-08-16T20:17:30Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

●  miniolab4:9000
   Uptime: 4 seconds
   Version: 2023-08-16T20:17:30Z
   Network: 4/4 OK
   Drives: 4/4 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 16

I do not understand.
Normally with 16 disks and 4 nodes with EC:8. I should be able to stop 2 nodes and still read data. exact ?

Merci,

Julien from France

**Comment by harshavardhana** [comment]
yes because you have only 4 nodes, taking down 2 nodes means you only have READ quorum. Of course we need write locks to get the system booted up, so if you have no servers that are booted up then taking down 2 servers during startup won't work.

**Comment by harshavardhana** [comment]
Running 4 nodes is a shoe-string budget if you want a production system go with a minimum of 8 nodes.

**Comment by bolshoib** [comment]
> yes because you have only 4 nodes, taking down 2 nodes means you only have READ quorum. Of course we need write locks to get the system booted up, so if you have no servers that are booted up then taking down 2 servers during startup won't work.
> 
> 

Yes but i can't read with 2 nodes. I understand i can't write with 2 nodes down. But actually i can't read.

**Comment by bolshoib** [comment]
Could you unclosed pls ?

**Comment by bolshoib** [comment]
Sorry,
4 drives by nodes and 4 nodes. 16 drives/4nodes.
EC:8
According with documentation :
Minimum Drives for Read Operations : 8
Minimum Drives for Write Operations : 9
So why i can't perform read operation with 2 nodes down ? (8 drives)

**Comment by ravindk89** [comment]
> yes because you have only 4 nodes, taking down 2 nodes means you only have READ quorum. Of course we need write locks to get the system booted up, so if you have no servers that are booted up then taking down 2 servers during startup won't work.

@bolshoib it is as stated below. 

To confirm - did you turn these nodes off *after the cluster started successfully*, or are you doing a cold start -> two nodes working?

We can update the docs to call out the issue above insofar as needing write quorum to successfully boot.

**Comment by harshavardhana** [comment]
With 4 nodes your tolerance is only 1 node for WRITEs and 2 nodes for READs. However, you should always think WRITEs to be your arbiter not READs.

**Comment by bolshoib** [comment]
> 
Hi. turn these nodes after the cluster started successfully.
I start my cluster : 4 servers. (16 drives)
I create a bucket and upload files in the console.
I stop 1 node (4 drives), I can read data, create buckets and upload files.
If I stop 2 nodes (8 drives), I can no longer access the data in the buckets. I can just see the buckets in the console but I can't access the data. I have an error : Resource requested is unreadable, please reduce your request rate

**Comment by bolshoib** [comment]
Ok Thanks, am new to MinIO. just a clarification :

With 4 nodes 16 disks

I start 4 nodes
4/4 Drives 4/4 Network

curl -I https://miniolab:9000/minio/health/cluster/read
HTTP/1.1 200 OK
curl -I https://miniolab:9000/minio/health/cluster
HTTP/1.1 200 OK
curl -I https://miniolab:9000/minio/health/cluster?maintenance=true
HTTP/1.1 200 OK

I stop 1 node 4 disks
3/4 Drives 3/4 Network
curl -I https://miniolab:9000/minio/health/cluster/read
HTTP/1.1 200 OK
curl -I https://miniolab:9000/minio/health/cluster
HTTP/1.1 200 OK
curl -I https://miniolab:9000/minio/health/cluster?maintenance=true
HTTP/1.1 412 Precondition Failed

I stop 2 nodes 8 disks
2/4 Drives 2/4 Network
curl -I https://miniolab:9000/minio/health/cluster/read
HTTP/1.1 200 OK
curl -I https://miniolab:9000/minio/health/cluster
HTTP/1.1 503 Service Unavailable
curl -I https://miniolab:9000/minio/health/cluster?maintenance=true
HTTP/1.1 412 Precondition Failed

This is normal operation. All right ?

I tested :

If I stop 1 node, the service is maintained.
If I stop 2 nodes, the service is not maintained. (I can't create a bucket, read or write data)

If I lose 7 disks, I can rebuild.
If I lose 8 disks, I can't rebuild.

Why when I stop 2 nodes, i.e. 8 disks, I can't get the bucket ? should I continue to have read access via the console or API ? No ? Is this normal operation?

I think I will have to use replication for my need.
Keep the service operational.

Thanks

**Comment by harshavardhana** [comment]
Creating a bucket is not allowed since you have lost write quorum. No new mutations are allowed until write quorum is restored.

Cluster health always talks about write quorum, and write quorum is the main arbiter here.
