### ISSUE TITLE
XL: When same file is uploaded twice by multipart upload failure happens quicky WRT Amazon S3

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1795]
Not sure whether its a bug or not.  Below is the observation.

I used minio-java in testing to do the below.

When two multipart upload is run in parallel for the same file, the returned error on failure is not consistent.
- When two different upload ids are used for uploading the same file works fine.
- When same upload id is used for two parallel uploads in which one upload is completed successfully and the other one failed with `NoSuchUpload` which is valid.
  In this case, sometimes I get EOFException or SocketException in java. In some runs I get `InternalError` from the server.

The same test with Amazon S3 works fine because we get new upload id every time. Its rare to get same upload id for two parallel uploads.  May be because of network latency.  Whereas minio server and testing are done in same machine.

**Comment by harshavardhana** [comment]
> When same upload id is used for two parallel uploads in which one upload is completed successfully and the other one failed with NoSuchUpload which is valid. In this case, sometimes I get EOFException or SocketException in java. In some runs I get InternalError from the server.

Sometimes getting InternalError is wrong and inconsistent.  We should always get "NoSuchUpload" in this case.

**Comment by krishnasrinivas** [comment]
need to debug, sometimes we get `internal error`

**Comment by krishnasrinivas** [comment]
deadline - 31 may.
