### ISSUE TITLE
Minio integration with ranger

### ISSUE THREAD

**Issue by vishnu-chalil** [minio/minio#17957]
As far as I have understand currently Minio doesn't support integration with Apache ranger and this  closed [issue](https://github.com/minio/minio/issues/12167) confirms that.

But I have seen a ranger s3 plugin [here](https://github.com/ing-bank/apache-ranger-s3-plugin). 

Since Minio is S3 compactible object storage is it possible to use this directly with Minio or with some tweaks does it work?

**Comment by harshavardhana** [comment]
@vishnu-chalil we haven't really seen Apache Ranger be a big requirement, what we have seen however is OpenID/OIDC compatible support to be a common requirement. If Ranger supports that we will work right away.

MinIO also supports custom authN and authZ endpoints where you can write your own broker for this. So overall it would be quite trivial to make Apache Ranger work with MinIO IMO.

But we haven't seen any large-scale production-grade interest in investing our time in it. If that is what you are planning we suggest you reach out to us at hello@min.io we can see how we can help you with it. 

I shall close this similar to https://github.com/minio/minio/issues/12167

**Comment by vishnu-chalil** [comment]
@harshavardhana  I have a send a mail regarding this at hello@min.io. Looking forward to hear from you guys.
