### ISSUE TITLE
Minio lifecycle rule based on local storage

### ISSUE THREAD

**Issue by robert-pudlowski-mox** [minio/minio#17973]
**Is your feature request related to a problem? Please describe.**
Sometimes we may run out of disk space before the lifecycle policy executes.

**Describe the solution you'd like**
I would like to have lifecycle rule based on disk free space (for example move the minio objects to S3 bucket when our local storage - disk is in 70% full.)

**Describe alternatives you've considered**
Create cronjob which is triggered every day in order to check disk usage and execute minio MV command to S3 bucket once the disk is in 70% full.

**Additional context**
I would also ask if there is already any idea how to manage with this issue **IF we are not able to extend local disk** where the minio is running.

**Comment by harshavardhana** [comment]
@robert-pudlowski-mox you may want to use batch expiration, you decide when to run it.

https://github.com/minio/minio/pull/17946

ILM is not designed for proactive expiration or quick expiration. ILM is meant for aging data.

**Comment by robert-pudlowski-mox** [comment]
@harshavardhana  but I dont want to loose the data. I just want to move the objects from Minio to S3 bucket if my disk usage is about to be full (for example 70% - > 7GB out of 10GB)
