### ISSUE TITLE
Move objects once the minio local storage is about to be run out of free disk space.

### ISSUE THREAD

**Issue by robert-pudlowski-mox** [minio/minio#17975]
Is your feature request related to a problem? Please describe.
Sometimes we may run out of disk space so I would like to move the objects to S3 bucket when disk is full for example in 70%.  I don't want to loose the data. 

Describe the solution you'd like
I would like to have rule based on disk free space (for example move the minio objects to S3 bucket when our local storage - disk is in 70% full.)

Describe alternatives you've considered
Create cronjob which is triggered every day in order to check disk usage and execute minio MV command to S3 bucket once the disk is in 70% full.

Additional context
I would also ask if there is already any idea how to manage with this issue IF we are not able to extend local disk where the minio is running

**Comment by harshavardhana** [comment]
@robert-pudlowski-mox This may be useful in some situations but we simply do not have a way to do this without complicating the S3 APIs.

Feel free to work on this feature if you must, MinIO has no plans to encourage single disk usage in this manner.
