### ISSUE TITLE
Minio doesn't wait for connection to finish before shutdown

### ISSUE THREAD

**Issue by ClementGautier** [minio/minio#17976]
Hi 👋

Before you dig in, a quick note on the context: this bug only occurs on Kubernetes using a custom deployment (not the Minio Operator). So, for anyone that have the same issue I'd first recommend using the Minio Operator. This issue is for those stuck with a weird setup.

## Expected Behavior
I'd expect that Minio's HTTP server waits for open connection to close before terminating as it's planned in the code [here](https://github.com/minio/minio/blob/19f70dbfbf2f83fbc047f06c21f87b25c84ace28/internal/http/server.go#L196C1-L197C1).

## Current Behavior
On Kubernetes, killing the pod result in the server shuting down instantly without waiting for the grace period, resulting in an upload error client-side:
```
upload failed: ./tmp_1g to s3://foo/tmp_1g An error occurred (ClientDisconnected) when calling the UploadPart operation: Client disconnected before response was ready
```

## Possible Solution
First we thought it was due to a bug in the stopProcess function that is closing go-routines too soon and made a patch that fixed the issue, cf [this patch](https://github.com/ubbleai/minio/pull/2/files#diff-72de019293f3343c72e9cac268cb0d71fee1057587ee6c061a49b7fcb74f4f05R62). But this didn't fix the issue in our Kubernetes cluster. We added some debug log and see that `srv.requestCount` evaluates to `0` directly after we terminate the pod, even if connections are still actives.

As a workaround we added a preStop lifecycle that actually waits for active connections to terminate before closing:
```
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "while [ $(netstat -aputen | grep -v envoy | grep -v pilot-agen | grep ESTABLISHED | wc -l | xargs) -ne 0 ]; do sleep 1; done"]
```

## Steps to Reproduce (for bugs)
1. Create a Deployment with a minio pod + service exposing the port 9000
2. Create a client pod that sends data in a bucket of that minio
3. Scale down the deployment
4. see that it doesn't wait for the grace period

## Context
We don't use the Minio Operator, just a pretty old Helm chart and I could not reproduce the issue using Minio Operator: the sts waited correctly for the connection to terminate.

## Regression
No (I mean, I don't think it ever worked using our setup)

## Your Environment
* Version used: RELEASE.2023-09-04T19-57-37Z (latest)
* Server setup and configuration: Kubernetes v1.22
* Operating System and version (`uname -a`): Debian 11 / Kernel 5.10.162

**Comment by harshavardhana** [comment]
We cannot wait perpetually, we have a shutdown timeout configure to the value you want via

--shutdown-timeout

**Comment by harshavardhana** [comment]
Scaling down the deployment means forcefully killing the pod, there is no way to apply grace period.

Think of scaling down as kill -9, which is what k8s does. So no that is not correct way to test this.

You should try to graceful kill the process via sigterm for the graceful period to be honored
