### ISSUE TITLE
Add SAML authentification support

### ISSUE THREAD

**Issue by dod-ia** [minio/minio#17984]
**Is your feature request related to a problem? Please describe.**
Currently, Minio supports OpenID but not SAML protocol. Some enterprises or institutions/administrations use SAML for historical reasons and migrating the auth protocol of the SSO is inconceivable for operational and certification reasons. Because of that, using Minio with these partners is not possible and it is problematic to select Minio for a collaborative project.

**Describe the solution you'd like**
To be able to choose OPENID or SAML identification

**Describe alternatives you've considered**
None

**Additional context**
#17868

**Comment by harshavardhana** [comment]
SAML is legacy. Please use OpenID, OIDC. If you have a production and commercial requirement please reach out to us via hello@min.io 

If not this is not something we are interested in adding into MinIO.
