### ISSUE TITLE
Error: Storage resources are insufficient for the read operation .minio.sys/buckets/repliaction-test/.metadata.bin 

### ISSUE THREAD

**Issue by ChiaHung-Yeh** [minio/minio#17983]
### Hello, I am currently encountering a thorny issue. I have deployed a MinIO distributed cluster in Docker, consisting of 5 nodes with 4 disks per node. One node is currently malfunctioning, and the following information is displayed through the MinIO Client:

API: SYSTEM()
Time: 06:22:15 UTC 09/06/2023
DeploymentID: d4a6b593-5d63-4595-9097-c80ac8133a91
Error: Storage resources are insufficient for the read operation .minio.sys/buckets/repliaction-test/.metadata.bin (cmd.InsufficientReadQuorum)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/bucket-metadata-sys.go:520:cmd.(*BucketMetadataSys).refreshBucketsMetadataLoop()

### Displayed through mc admin info mino-221-1
sh-4.4# mc admin info minio-221-1
●  IP:9000
   Uptime: 24 minutes
   Version: 2023-08-23T10:07:06Z
   Network: 4/5 OK
   Drives: 4/4 OK
   Pool: 1

●  IP:9001
   Uptime: 24 minutes
   Version: 2023-08-23T10:07:06Z
   Network: 4/5 OK
   Drives: 4/4 OK
   Pool: 2

●  IP:9000
   Uptime: offline
   Drives: 0/4 OK

●  1IP:9001
   Uptime: 24 minutes
   Version: 2023-08-23T10:07:06Z
   Network: 4/5 OK
   Drives: 4/4 OK
   Pool: 4

● IP:9002
   Uptime: 27 minutes
   Version: 2023-08-23T10:07:06Z
   Network: 4/5 OK
   Drives: 4/4 OK
   Pool: 5

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 4
   2nd, Erasure sets: 1, Drives per erasure set: 4
   4th, Erasure sets: 1, Drives per erasure set: 4
   5th, Erasure sets: 1, Drives per erasure set: 4

102 MiB Used, 3 Buckets, 3 Objects
1 node offline, 16 drives online, 4 drives offline

### My deployment method is

docker run -d -p 9000:9000 -p 9090:9090 \
--name=minio-node1 \
--restart=always \
-e "MINIO_ROOT_USER=minioadmin" \
-e "MINIO_ROOT_PASSWORD=minioadmin" \
-v /data/app/minio-service/minio1/data1:/data1 \
-v /data/app/minio-service/minio1/data2:/data2 \
-v /data/app/minio-service/minio1/data3:/data3 \
-v /data/app/minio-service/minio1/data4:/data4 \
-v /data/app/minio-service/minio1/config:/root/.minio \
--network host \
--hostname "host-node1" \
minio/minio:latest server \
http://IP:9000/data{1...4} \
http://IP:9001/data{1...4} \
http://IP:9000/data{1...4} \
http://IP:9001/data{1...4} \
http://IP:9002/data{1...4} \
--address :9000 \
--console-address ":9090" 

### Currently, my failed node cannot be recovered. Will files on this node be automatically restored to other nodes?

**Comment by harshavardhana** [comment]
No and no, you haven't read why you can't setup things like this. You have multiple pools with no node-level redundancy configured.

That's why there is a quorum loss because one of the pool is offline entirely. This is a setup issue, unfortunately, there isn't anything that be done.
