### ISSUE TITLE
Expected number of all hosts (N) to be remote +1 (N) 

### ISSUE THREAD

**Issue by ChiaHung-Yeh** [minio/minio#17991]
## Deployment Environment
* Server: 2 sets（192.168.33.223、192.168.33.224）
* Dokcer 20.10.11

### A Server（192.168.33.223）：
docker network create -d macvlan \
--subnet=192.168.33.0/24 \
--gateway=192.168.33.1 \
macvlan-minio

**minio-node1**
docker run -d --name=minio-node1 \
--restart=always -p 9000:9000 \
--network macvlan-minio \
--hostname "host-node1" \
-e "MINIO_ROOT_USER=minioadmin" \
-e "MINIO_ROOT_PASSWORD=minioadmin" \
-v /data/app/minio-service/minio1/data1:/data1 \
-v /data/app/minio-service/minio1/data2:/data2 \
-v /data/app/minio-service/minio1/data3:/data3 \
-v /data/app/minio-service/minio1/data4:/data4 \
-v /data/app/minio-service/minio1/config:/root/.minio \
minio/minio:latest server \
http://192.168.33.223:9000/data{1...4} \
http://192.168.33.223:9001/data{1...4} \
http://192.168.33.224:9000/data{1...4} \
http://192.168.33.224:9001/data{1...4} \
--address :9000 \
--console-address ":9090"

**minio-node2**
docker run -d --name=minio-node2 \
--restart=always -p 9001:9001 \
--network macvlan-minio \
--hostname "host-node2" \
-e "MINIO_ROOT_USER=minioadmin" \
-e "MINIO_ROOT_PASSWORD=minioadmin" \
-v /data/app/minio-service/minio2/data1:/data1 \
-v /data/app/minio-service/minio2/data2:/data2 \
-v /data/app/minio-service/minio2/data3:/data3 \
-v /data/app/minio-service/minio2/data4:/data4 \
-v /data/app/minio-service/minio2/config:/root/.minio \
minio/minio:latest server \
http://192.168.33.223:9000/data{1...4} \
http://192.168.33.223:9001/data{1...4} \
http://192.168.33.224:9000/data{1...4} \
http://192.168.33.224:9001/data{1...4} \
--address :9001 \
--console-address ":9091"

### B Server（192.168.33.224）：
docker network create -d macvlan \
--subnet=192.168.33.0/24 \
--gateway=192.168.33.1 \
macvlan-minio

**minio-node3**
docker run -d --name=minio-node3 \
--restart=always -p 9000:9000 \
--network macvlan-minio \
--hostname "host-node3" \
-e "MINIO_ROOT_USER=minioadmin" \
-e "MINIO_ROOT_PASSWORD=minioadmin" \
-v /data/app/minio-service/minio1/data1:/data1 \
-v /data/app/minio-service/minio1/data2:/data2 \
-v /data/app/minio-service/minio1/data3:/data3 \
-v /data/app/minio-service/minio1/data4:/data4 \
-v /data/app/minio-service/minio1/config:/root/.minio \
minio/minio:latest server \
http://192.168.33.223:9000/data{1...4} \
http://192.168.33.223:9001/data{1...4} \
http://192.168.33.224:9000/data{1...4} \
http://192.168.33.224:9001/data{1...4} \
--address :9000 \
--console-address ":9090"

**minio-node4**
docker run -d --name=minio-node4 \
--restart=always -p 9001:9001 \
--network macvlan-minio \
--hostname "host-node4" \
-e "MINIO_ROOT_USER=minioadmin" \
-e "MINIO_ROOT_PASSWORD=minioadmin" \
-v /data/app/minio-service/minio2/data1:/data1 \
-v /data/app/minio-service/minio2/data2:/data2 \
-v /data/app/minio-service/minio2/data3:/data3 \
-v /data/app/minio-service/minio2/data4:/data4 \
-v /data/app/minio-service/minio2/config:/root/.minio \
minio/minio:latest server \
http://192.168.33.223:9000/data{1...4} \
http://192.168.33.223:9001/data{1...4} \
http://192.168.33.224:9000/data{1...4} \
http://192.168.33.224:9001/data{1...4} \
--address :9001 \
--console-address ":9091"

### After all nodes are deployed, print the log information through the command. The log information is shown as follows

docker logs -f minio-node1

API: SYSTEM()
Time: 07:55:19 UTC 09/07/2023
Error: WARNING: Expected number of all hosts (4) to be remote +1 (4) (*errors.errorString)
       7: internal/logger/logger.go:258:logger.LogIf()
       6: cmd/peer-rest-client.go:759:cmd.newPeerRestClients()
       5: cmd/notification.go:1041:cmd.NewNotificationSys()
       4: cmd/server-main.go:318:cmd.initAllSubsystems()
       3: cmd/server-main.go:611:cmd.serverMain.func4()
       2: cmd/server-main.go:423:cmd.bootstrapTrace()
       1: cmd/server-main.go:610:cmd.serverMain()
WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance

# How can I deal with this problem?

**Comment by harshavardhana** [comment]
This is a wrong setup

```
[http://192.168.33.223:9000/data{1...4}](http://192.168.33.223:9000/data%7B1...4%7D)
[http://192.168.33.223:9001/data{1...4}](http://192.168.33.223:9001/data%7B1...4%7D)
[http://192.168.33.224:9000/data{1...4}](http://192.168.33.224:9000/data%7B1...4%7D)
[http://192.168.33.224:9001/data{1...4}](http://192.168.33.224:9001/data%7B1...4%7D)
```

You can't have same IP serving same drives on different ports.

**Comment by ChiaHung-Yeh** [comment]
However, the drivers attached to each node are different

**Comment by ChiaHung-Yeh** [comment]
A Server：
-v /data/app/minio-service/minio1/data1:/data1
-v /data/app/minio-service/minio1/data2:/data2
-v /data/app/minio-service/minio1/data3:/data3
-v /data/app/minio-service/minio1/data4:/data4


B Server：
-v /data/app/minio-service/minio2/data1:/data1
-v /data/app/minio-service/minio2/data2:/data2
-v /data/app/minio-service/minio2/data3:/data3
-v /data/app/minio-service/minio2/data4:/data4
