### ISSUE TITLE
Deploy MinIO: Multi-Node Multi-Drive Cluster startup Failure

### ISSUE THREAD

**Issue by caokunyan** [minio/minio#17997]
## NOTE
Deploy MinIO: Multi-Node Multi-Drive Cluster startup Failure

## Expected Behavior
 minio success

## Current Behavior
my config run:
#!/bin/bash
export MINIO_ROOT_USER=minio@admin2
export MINIO_ROOT_PASSWORD=minio@admin2
nohup /data/minio/run/minio server --config-dir /home/minio/conf \
--address :9000 --console-address :8000 \
http://139.198.117.234/data/minio/data{1...4} \
http://139.198.117.155/data/minio/data{1...4} >> log.log 2>&1 &

Error log：
Unable to read 'format.json' from http://139.198.117.234:9000/data/minio/data1: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

Unable to read 'format.json' from http://139.198.117.234:9000/data/minio/data2: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

Unable to read 'format.json' from http://139.198.117.234:9000/data/minio/data3: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

Unable to read 'format.json' from http://139.198.117.234:9000/data/minio/data4: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

API: SYSTEM()
Time: 09:26:19 UTC 09/08/2023
Error: Read failed. Insufficient number of drives online (*errors.errorString)
       8: internal/logger/logger.go:258:logger.LogIf()
       7: cmd/prepare-storage.go:254:cmd.connectLoadInitFormats()
       6: cmd/prepare-storage.go:312:cmd.waitForFormatErasure()
       5: cmd/erasure-server-pool.go:103:cmd.newErasureServerPools()
       4: cmd/server-main.go:957:cmd.newObjectLayer()
       3: cmd/server-main.go:704:cmd.serverMain.func9()
       2: cmd/server-main.go:423:cmd.bootstrapTrace()
       1: cmd/server-main.go:702:cmd.serverMain()
Waiting for a minimum of 2 drives to come online (elapsed 2m15s)

## Your Environment
minio version：
minio version RELEASE.2023-09-04T19-57-37Z (commit-id=1c99fb106c3e1448ed92f8465d5695d055d432e7)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

Disk mount：
![image](https://github.com/minio/minio/assets/34908820/af659ab7-aa0a-4114-8d1d-de76f2e6111a)

/dev/vdf        9.8G   37M  9.2G   1% /data/minio/data2
/dev/vdd        9.8G   37M  9.2G   1% /data/minio/data3
/dev/vde        9.8G   37M  9.2G   1% /data/minio/data4
/dev/vdc        9.8G   37M  9.2G   1% /data/minio/data1

What steps am I missing, and how should I solve them, thank you！！！

**Comment by harshavardhana** [comment]
Please do not deploy unsupported configuration.

Please check https://docs.min.io for further guidance on supported deployment patterns.
