### ISSUE TITLE
Regression related to starting server on port 0

### ISSUE THREAD

**Issue by liningpan** [minio/minio#17998]
If I understand correctly based on previous issues, `minio` does not allow starting even a SNSD instance with the S3-API on port 0 or letting the OS choose a port.

https://github.com/minio/minio/issues/3314
https://github.com/minio/minio/pull/3318
https://github.com/minio/minio/pull/6179

## Expected Behavior

The server should do one of two things:
1. The server should refuse to start (based on the PRs I can find).
2. If the server can start, it should report the assigned port number.

## Current Behavior

The server starts but does not report the port number.

## Possible Solution

It seems like the console endpoint is already starting on a random available port. I wonder if it is possible to do the same for SNSD setup (typically for integration test environments). 

## Your Environment

```
darwin-arm64 minio.RELEASE.2023-09-04T19-57-37Z
sha256: 1226866f00503fd8dbf2133412c3505e724b845ac71792c806535cd03110c89b
```

**Comment by harshavardhana** [comment]
We have never supported port :0, we will duly error out.
