### ISSUE TITLE
Enable querying of Minio metrics from Mimir 

### ISSUE THREAD

**Issue by jmorenoc-o** [minio/minio#17996]
**Is your feature request related to a problem? Please describe.**

I am using MinIO together with Prometheus without any problem. Also from the integrated MinIO Metrics Dashboard I can query the metrics to Prometheus.

My Prometheus instance is configured to push metrics from MinIO to Mimir.

I would like to be able to query Mimir instead of Prometheus so I have replaced the URL via `MINIO_PROMETHEUS_URL`

Unfortunately MinIO does a validation (healthcheck) through the path `/-/healthy` and this path is NOT available through Mimir.

**Describe the solution you'd like**

Would it be a good idea to allow to configure this path with a property?

**Describe alternatives you've considered**

Another possible solution is that Mimir implements the same endpoint as Prometheus.

In this VictoriaMetrics issue they talk about something similar: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1833

**Additional context**
It should also be noted that Mimir is multi-tenant and an HTTP header `X-Scope-OrgID` is required to allow queries.

https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/

**Comment by harshavardhana** [comment]
Please ask mimir to mimick Prometheus like health check endpoint.
