### ISSUE TITLE
minio Multi-Node Multi-Drive Unable to start

### ISSUE THREAD

**Issue by TalentedBastard** [minio/minio#18002]
## Expected Behavior
start a 2 nodes 4 dirvers minio server 

## Current Behavior
Following servers are currently offline or unreachable, minio server cant running

## Steps to Reproduce (for bugs)

1. selinux disable
2. firewalld disable
3. minio data dir : /data1/minio /data2/minio, both server are same
4. run : minio server http://spider0{2...3}:30001/data{1...2}/minio

## Context

API: SYSTEM()
Time: 08:00:33 UTC 09/09/2023
Error: WARNING: Expected number of all hosts (2) to be remote +1 (2) (*errors.errorString)
       7: internal/logger/logger.go:258:logger.LogIf()
       6: cmd/peer-rest-client.go:772:cmd.newPeerRestClients()
       5: cmd/notification.go:1071:cmd.NewNotificationSys()
       4: cmd/server-main.go:318:cmd.initAllSubsystems()
       3: cmd/server-main.go:611:cmd.serverMain.func4()
       2: cmd/server-main.go:423:cmd.bootstrapTrace()
       1: cmd/server-main.go:610:cmd.serverMain()
WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance

Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://spider02:30001/data1 is unreachable: Post "http://spider02:30001/minio/bootstrap/v1/verify": dial tcp spider02:30001: connect: connection refused http://spider03:30001/data1 is unreachable: Post "http://spider03:30001/minio/bootstrap/v1/verify": dial tcp spider03:30001: connect: connection refused]
Waiting for atleast 1 remote servers with valid configuration to be online

### minio version
minio version RELEASE.2023-09-04T19-57-37Z (commit-id=1c99fb106c3e1448ed92f8465d5695d055d432e7)

### Linux version
CentOS Linux release 7.9.2009 (Core)

### hosts
spider02
spider03

**Comment by harshavardhana** [comment]
@TalentedBastard your hostnames are resolving to localhost. Make sure your DNS names or hostnames resolve to their respective public interfaces.

**Comment by TalentedBastard** [comment]
> Sorry my description caused misunderstanding, my host name is correct, spider02 and 03 points to the correct ip address, I use default port 9000 and update my systemd, The service is running, but i don't know why

**Comment by Littlehhao** [comment]
我也遇到了这个问题，请问如何解决的
