### ISSUE TITLE
why my multiple nodes server storage same

### ISSUE THREAD

**Issue by TalentedBastard** [minio/minio#18014]
## NOTE
i have 2 nodes 4 drivers cluster, one node have 2 drivers

I use 'rclone copy /local_file minio:bucket' to upload a file

## Expected Behavior
+ file upload success and 2 drivers have data because Erasure Code

## Current Behavior
+ file upload success but 4 drivers have same data, 

## Your Environment
+ centos7
+ file type = txt
+ rclone : v1.63.1
+ minio :  RELEASE.2023-09-04T19-57-37Z

**Comment by harshavardhana** [comment]
That's called erasure coding.
