### ISSUE TITLE
plan to issue a fuzz driver to OSS-Fuzz

### ISSUE THREAD

**Issue by secsys-go** [minio/minio#18036]
We are developing a new technique to automatically transform your official unit tests into fuzz drivers. And we plan to issue the generated fuzz driver to OSS-Fuzz. We manually fix some errors so that fuzz driver we issue can work well.

We have issued PR [google/oss-fuzz#10946](https://github.com/google/oss-fuzz/pull/10946) in OSS-Fuzz project, but OSS-Fuzz's contributors require project maintainer to approve this PR before they merge it. Could you please help us review this PR? We are appreciated if you could provide us with some suggestions so that we can improve our fuzz driver's quality.

**Comment by klauspost** [comment]
You sent in a non-compiling pull request. You did not follow up with working code.

We don't want to use the out-dated fuzzing format, but want to use the Go internal method.

If we want to pursue this, we will add our own.

**Comment by secsys-go** [comment]
> You sent in a non-compiling pull request. You did not follow up with working code.
> 
> We don't want to use the out-dated fuzzing format, but want to use the Go internal method.
> 
> If we want to pursue this, we will add our own.

Hi, could you please explain what out-dated fuzzing format is, and what kind of fuzzing format you accept? Thank you.

By the way, you just said "we will add our own". Is it means that MinIO developers are not gonna let community submit fuzzing related code but maintain it by themselves?

**Comment by klauspost** [comment]
> By the way, you just said "we will add our own". Is it means that MinIO developers are not gonna let community submit fuzzing related code but maintain it by themselves?

Correct. 

This is merely a wrapper around the standard library. If you find any issues through your own fuzzing feel free to report them to the issue tracker.

Go added native fuzzing a few versions back. As I said, if we feel the need is for it, we will add it ourselves.
