### ISSUE TITLE
minio support AWS efs in kubernates  

### ISSUE THREAD

**Issue by jilan804** [minio/minio#18043]
i had try to mount EFS(PV) to minio persistence purpose it was mounted, pod also working fine but when i was access with node port minio UI was not working can you please help me any one to share the templates of kubernates YAML files

**Comment by harshavardhana** [comment]
EFS is a network filesystem lacks consistency guarantees that we expect from disk filesystems.

Please use ebs volumes with XFS instead of EFS.
