### ISSUE TITLE
Tiering for existing objects not happening.currently only new objets are getting tiered to target bucket.Method for moving aged data from one bucket to other bucket across tenant

### ISSUE THREAD

**Issue by akash123-eng** [minio/minio#18047]
Hi,

We have deployed minio using minio operator v4.5.8.
We are trying minio tiering . 
have added s3 type tier from bucket of one tenant to bucket of other tenant. 
After that we added ilm rule to transition after 0 days for testing.
New Objects which are added after applying ilm rule are getting tiered but existing object are not getting tiered.

Our requirement is to move aged data from one tenant to other tenant but this is not happening with tiering.

Please advise on how do we can achieve this or should we try any other method than tiering ?

Thank you in advance

**Comment by vadmeste** [comment]
> New Objects which are added after applying ilm rule are getting tiered but existing object are not getting tiered.

Mostly you need to wait until the background scanner scans those objects, how many objects do you have in this cluster ?

**Comment by akash123-eng** [comment]
Thanks for the reply
Not much currently it has only 20 objects and its tiering only new object
added after applying ilm transition rule.

Also there is one more issue if I delete object in the source bucket the
corresponding object which was tiered in the target bucket is also getting
deleted.
Is this expected behavior?

**Comment by vadmeste** [comment]
@akash123-eng why did you remove the issue template ? 

what is your MinIO version ?

> Also there is one more issue if I delete object in the source bucket the
corresponding object which was tiered in the target bucket is also getting
deleted.
Is this expected behavior?

Yes

**Comment by akash123-eng** [comment]
> @akash123-eng why did you remove the issue template ?
I wasn't aware about that.sorry for that

what is your MinIO version ?
 @vadmeste It's deployed as minio operator 4.5.8

Is there any way to prevent deletion of  tiered object in target bucket if object in source bucket is deleted ?

**Comment by harshavardhana** [comment]
> > @akash123-eng why did you remove the issue template ?
> > I wasn't aware about that.sorry for that
> > what is your MinIO version ?
> > @vadmeste It's deployed as minio operator 4.5.8
> 
> Is there any way to prevent deletion of tiered object in target bucket if object in source bucket is deleted ?


No @akash123-eng

**Comment by akash123-eng** [comment]
Ok @harshavardhana 
Thanks for confirming.

Also there is one weird behaviour.

When we added tiering from one tenant bucket to other  tenant bucket and then added ilm rule to transition object after certain days, those objects are getting tiered but when I do "mc du" on source bucket it's showing size as earlier even though object is already tiered.

Ideally source bucket should have only Metadata after tiering but in mc du command also it's showing usage but in storage class it's showing name of tier where it's tiered.
Then how do we confirm after tiering there is actual used space reduction in source bucket ?

Because general usage of tiering is to move storage from expensive to cheap storage.

**Comment by kannappanr** [comment]
```
mc ilm tier info ALIAS
```
Will give you statistics on how much has been tiered to cheap storage in your case

**Comment by akash123-eng** [comment]
Yes it's giving the statistics but in "mc du" command it's showing usage in source bucket too which is confusing to me.

The thing is that in storage class field it's showing tier name to which object was tiered in "mc stat" command but if I do "mc ls" on the source bucket it's showing  as "STANDARD".
As per below doc when object is tiered it should show tier name to which it was tiered instead of STANDARD in mc ls command output.
https://min.io/docs/minio/linux/reference/minio-mc/mc-ls.htm
(Note: I am using updated version of mc command as given in the above doc still it's not showing tier to which it's tiered)

@harshavardhana @vadmeste @kannappanr please give your inputs on above what could be the issue that mc ls is not showing proper tier for the object it's tiered

**Comment by akash123-eng** [comment]
> Yes it's giving the statistics but in "mc du" command it's showing usage in source bucket too which is confusing to me.
> 
> The thing is that in storage class field it's showing tier name to which object was tiered in "mc stat" command but if I do "mc ls" on the source bucket it's showing as "STANDARD". As per below doc when object is tiered it should show tier name to which it was tiered instead of STANDARD in mc ls command output. https://min.io/docs/minio/linux/reference/minio-mc/mc-ls.htm

> (Note: I am using updated version of mc command as given in the above doc still it's not showing tier to which it's tiered)
> @harshavardhana @vadmeste @kannappanr please give your inputs on above what could be the issue that mc ls is not showing proper tier for the object it's tiered

@harshavardhana @vadmeste can you please help on above queries ?

**Comment by akash123-eng** [comment]
@harshavardhana @vadmeste @kannappanr Can you please help on tiering for existing objects? Do I need to upgrade minio version which is currently 4.5.8 and causing issue for existing objects tiering.

Also for tiered objects in storage class field it's showing tier name to which object was tiered in "mc stat" command but if I do "mc ls" on the source bucket it's showing as "STANDARD". As per below doc when object is tiered it should show tier name to which it was tiered instead of STANDARD in mc ls command output. https://min.io/docs/minio/linux/reference/minio-mc/mc-ls.htm

(Note: I am using updated version of mc command as given in the above doc still it's not showing tier to which it's tiered)

It would be really helpful if you can help me on above 2 queries

**Comment by akash123-eng** [comment]
Not needed
