### ISSUE TITLE
XL: Test failure. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1806]
`TestObjectAPIPutObjectPart` is failing with following error on current rewrite-xl branch.

```
K: 71 passed
--- FAIL: TestObjectAPIPutObjectPart (0.41s)
    object-api-multipart_test.go:211: Test 13: SingleNode: Expected to fail with error "EOF", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.
    object-api-multipart_test.go:211: Test 14: SingleNode: Expected to fail with error "Contains more data than specified size of 3 bytes.", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.
    object-api-multipart_test.go:211: Test 13: XL: Expected to fail with error "EOF", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.
    object-api-multipart_test.go:211: Test 14: XL: Expected to fail with error "Contains more data than specified size of 3 bytes.", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.

```

**Comment by harshavardhana** [comment]
> K: 71 passed
> --- FAIL: TestObjectAPIPutObjectPart (0.41s)
>     object-api-multipart_test.go:211: Test 13: SingleNode: Expected to fail with error "EOF", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.
>     object-api-multipart_test.go:211: Test 14: SingleNode: Expected to fail with error "Contains more data than specified size of 3 bytes.", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.
>     object-api-multipart_test.go:211: Test 13: XL: Expected to fail with error "EOF", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.
>     object-api-multipart_test.go:211: Test 14: XL: Expected to fail with error "Contains more data than specified size of 3 bytes.", but instead failed with error "Bad digest: Expected a35 is not valid with what we calculated e2fc714c4727ee9395f324cd2e7f331f" instead.

This was intentional that we don't read '1' more byte to figure out EOF, it was racy and prone to issues. It is okay to return bad digest since that is expected if a client has sent more data than expected.

**Comment by hackintoshrao** [comment]
@harshavardhana : Sure 👍
