### ISSUE TITLE
Unable to configure remote tier target: failed to perform DELETE: Prefix access is denied: redacted/probeobject.

### ISSUE THREAD

**Issue by MiroslavSotirov** [minio/minio#18066]
I'm trying to add AWS S3 tier for cold storage transition. The S3 bucket is configured with object lock enabled and compliance.

It looks like minio is trying PUT/GET/DELETE object during the addition of a new tier. While PUT and GET are successful, DELETE will never succeed in this case since the bucket on the AWS side has compliance enabled and delete operation is prohibited, thus this will never succeed for compliance buckets.

`Unable to configure remote tier target: failed to perform DELETE: Prefix access is denied: redacted/probeobject.`

## Expected Behavior

To be able to add AWS S3 tier with object lock enabled

## Current Behavior

Error is returned when trying to add AWS S3 tier with object lock enabled.

```
mc: <DEBUG> PUT /minio/admin/v3/tier?force=false HTTP/1.1
Host: **REDACTED**
User-Agent: MinIO (linux; amd64) madmin-go/2.0.0 mc/RELEASE.2023-09-13T23-08-58Z
Content-Length: 349
Accept-Encoding: zstd,gzip
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20230920//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: c0f4e4282d01e2c9f99512256e351f0654b843273a4d45bb06f0c5b359a19ed6
X-Amz-Date: 20230920T105006Z

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 289
Accept-Ranges: bytes
Content-Type: application/json
Date: Wed, 20 Sep 2023 10:50:07 GMT
Server: istio-envoy
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin,Accept-Encoding
X-Amz-Id-2: 1a2096bb9208b5671d041125950a83aa65c56760ca9967f80207c0e2dcc132e2
X-Amz-Request-Id: 178695CA9F2754C4
X-Content-Type-Options: nosniff
X-Envoy-Upstream-Service-Time: 689
X-Xss-Protection: 1; mode=block

{"Code":"XMinioAdminTierInsufficientPermissions","Message":"failed to perform DELETE: Prefix access is denied: **REDACTED**/probeobject","Resource":"/minio/admin/v3/tier","RequestId":"178695CA9F2754C4","HostId":"1a2096bb9208b5671d041125950a83aa65c56760ca9967f80207c0e2dcc132e2"}
```

I can see the `probeobject` in the bucket which assumes PUT and GET are working fine, however DELETE is not possible due to compliance mode

## Possible Solution

Bypass DELETE operation for compliance buckets during tier addition.

## Steps to Reproduce (for bugs)

1. Use the UI to add a new AWS S3 tier which has a bucket with object lock and compliance configured
or
2. Use mc to add tier
```
mc ilm tier add s3 minio-alias SOME_NAME_OF_TIER \
                               --endpoint https://s3.ommited.endpoint \
                               --access-key "AWS_KEY" \
                               --secret-key "AWS_SECRET" \
                               --bucket aws_bucket \
                               --region some_region \
                               --storage-class "STANDARD" \
                               --prefix prefix/ --debug
```
## Context

Trying to setup transition from minio object lock enabled bucket to AWS s3 object lock enabled bucket.

## Regression

No
## Your Environment

* Version used (`minio --version`):
mc version: `RELEASE.2023-09-13T23-08-58Z (commit-id=e561bc770e9ba6659a13a094e08a530a9685748c)`
* Server setup and configuration:
minio-operator (kubernetes) `v5.0.9`
minio-tenant (kubernetes) `v5.0.9 - RELEASE.2023-09-16T01-01-47Z`
* Operating System and version (`uname -a`):
kubernetes running on: `Red Hat Enterprise Linux 8.6  kernel: 4.18.0-372.9.1.el8.x86_64`

**Comment by vadmeste** [comment]
If the bucket is versioned, then this error is possible if you do not have some permissions like s3:DeleteObjectVersion

@harshavardhana I am not sure why the tiering code is versioned in the first place, especially the code that initializes the warm s3 bucket, any idea ? or maybe let's wait for @krisis

**Comment by harshavardhana** [comment]
> If the bucket is versioned, then this error is possible if you do not have some permissions like s3:DeleteObjectVersion
> 
> @harshavardhana I am not sure why the tiering code is versioned in the first place, especially the code that initializes the warm s3 bucket, any idea ? or maybe let's wait for @krisis

Because it supports replication as well @vadmeste you can setup a replicated tiered setup.

**Comment by harshavardhana** [comment]
However here we need permissions to delete, so it the backend has compliance configured we should use bypass governance.

If the bucket has legal-hold configured we can't use that bucket. So we should perform those checks and act accordingly.

**Comment by MiroslavSotirov** [comment]
My current policy(added for ref) allows everything including `s3:DeleteObjectVersion`, however, I believe this will only allow deletion in governance mode but not in compliance.

From AWS docs:
> In compliance mode, a protected object version can't be overwritten or deleted by any user, including the root user in your AWS account. When an object is locked in compliance mode, its retention mode can't be changed, and its retention period can't be shortened. Compliance mode helps ensure that an object version can't be overwritten or deleted for the duration of the retention period.
```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"s3:*"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:s3:::BUCKET",
				"arn:aws:s3:::BUCKET/*"
			],
			"Sid": ""
		}
	]
}
```

Maybe there should be no DELETE operation during tier addition for compliance buckets, identifying this with some kind of checkbox during tier setup.

Other than that for a workaround, I'm thinking of trying to add a tier with a regular AWS bucket and then switch it to compliance mode, any thoughts if this is going to work and any possible long-term problems with that?

**Comment by harshavardhana** [comment]
fixed #18108

**Comment by MiroslavSotirov** [comment]
Does not seems to be fixed, i'm getting the same error with `RELEASE.2023-09-30T07-02-29Z`

**Comment by harshavardhana** [comment]
> Does not seems to be fixed, i'm getting the same error with `RELEASE.2023-09-30T07-02-29Z`

It cannot be fixed unfortunately @MiroslavSotirov we need support for Deleting a version from the backend bucket. You cannot use compliance buckets.
