### ISSUE TITLE
Cannot remove file with minio client

### ISSUE THREAD

**Issue by MarcoPereira7** [minio/minio#18067]
I am trying to use minio client to mount a S3 bucket. I have succesfully mounted the bucket and copied files inside but if i try to delete any file via minio client i get an HTTP 501 Not implemented. 

## Expected Behavior
Minio client should be able to delete files inside the bucket.

## Current Behavior
Minio client cannot delete files inside the bucket.

## Steps to Reproduce (for bugs)
Add a host:
`mc config host add s3-bucket https://XXXX:9021 "ACCESS_KEY" SECRET_KEY_ --api S3v4`

Copy a file to the bucket:
`mc cp a s3-bucket/my-bucket/a`

Delete the file in the bucket:
`mc rm s3-bucket/my-bucket/a` -> Returns the following: mc: <ERROR> Failed to remove `s3-bucket/my-bucket/a`. Object does not exist

## Command output
mc: <ERROR> Failed to remove `s3-bucket/my-bucket/a`. The requested functionality is not implemented.

## Your Environment
Minio client version: 
mc version RELEASE.2023-09-07T22-48-55Z (commit-id=9dcef8825fae8d438fc0be518ecd5ca289f6e18f)
Runtime: go1.21.1 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by harshavardhana** [comment]
Is your server on port 9021 MinIO?

**Comment by MarcoPereira7** [comment]
@harshavardhana Yes, the server is listening 9021 but using DELL ISILON.

..

**Comment by MarcoPereira7** [comment]
I tried to delete files using S3 Browser and it works. But with minio client i cannot figure it out why i cannot do the same.

**Comment by harshavardhana** [comment]
Yeah this is because `mc` expects multi-object delete to work @MarcoPereira7 if they don't support that `mc` won't work.

Make sure your endpoint is S3 compatible and that they have implemented some basic S3 APIs.

**Comment by harshavardhana** [comment]
Run `--debug` and see what API they don't support - ask them to support it.
