### ISSUE TITLE
when prometheus get metric ,label is not right?

### ISSUE THREAD

**Issue by h812755591** [minio/minio#18071]
1, alert rule
groups:
- name: minio-alerts
  rules:
  - alert: NodesOffline
    expr: avg_over_time(minio_cluster_nodes_offline_total{job="minio-job"}[5m]) > 0
    labels:
      severity: warn
    annotations:
      summary: "Node down in MinIO deployment"
      description: "Node(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"

  - alert: DisksOffline
    expr: avg_over_time(minio_cluster_drive_offline_total{job="minio-job"}[5m]) > 0
    for: 10m
    labels:
      severity: warn
    annotations:
      summary: "Disks down in MinIO deployment"
      description: "Disks(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"
2, minio deployment 
192.168.2.157 min1.gthpc.com
192.168.2.158 min2.gthpc.com
192.168.2.159 min3.gthpc.com
192.168.2.174 min4.gthpc.com

at the same time ?
i have an nginx ,
192.168.2.161 min4.gthpc.com 

3,when i get metric
when i shutdown min1.gthpc.com
  
avg_over_time(minio_cluster_nodes_offline_total{job="minio-job"}[5m])

![1695267931423](https://github.com/minio/minio/assets/29937880/a11a0cd8-3cf0-4559-8b9a-a77e087aae28)
it will send three  item,in fact ,it should show node which it shutdow,am i right.

**Comment by harshavardhana** [comment]
No that's just a counter, it won't show which node is down. You need to configure node metrics to look at node level metrics and to see if the node is down or not.

**Comment by h812755591** [comment]
but the label 'server' still confused me

**Comment by harshavardhana** [comment]
> but the label 'server' still confused me

That is to show that each server notices that you have the server offline.
