### ISSUE TITLE
aws-sdk-go-v2: operation error S3: PutPublicAccessBlock, https response error StatusCode: 400

### ISSUE THREAD

**Issue by tetra12** [minio/minio#18086]
Minio fails with error to setup a `PutPublicAccessBlock` config in Golang as per AWS Docs [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutPublicAccessBlock.html)

## Expected Behavior

The command must successfully block all public access to the bucket with AWS SDK Go V2

## Current Behavior

Minio fails to create a bucket  public access block policies with an error

## Steps to Reproduce (for bugs)

1. Create a bucket with all default configs: `mc mb lap/buck-foo1`
2. Use the latest AWS-SDK-GO-V2 with the following:
```sh
mc mb lap/buck-foo1
```

```go
_, err := s.client.PutPublicAccessBlock(context.Background(), &s3.PutPublicAccessBlockInput{
  Bucket: aws.String("buck-foo1"),
  PublicAccessBlockConfiguration: &types.PublicAccessBlockConfiguration{
    BlockPublicAcls:       true,
    BlockPublicPolicy:     true,
    IgnorePublicAcls:      true,
    RestrictPublicBuckets: true}})

if err != nil {
  return err
}
```

## Context

I'm trying to implement a bucket public access configuration with a custom CLI

I'm able to successfully use `aws-sdk-go-v2` to manage buckets and objects, but fail to programmatically set public access with the code lifted from AWS

## Your Environment

* Version used (`minio --version`): `dockerhub` RELEASE.2023-09-20T22-49-55Z
* Server setup and configuration: simplest localhost `docker`
* Operating System and version (`uname -a`): Ubuntu 22.04.3 amd64
* AWS SDK Go V2 Version: 
```sh
github.com/aws/aws-sdk-go-v2 v1.21.0
github.com/aws/aws-sdk-go-v2/config v1.18.41
github.com/aws/aws-sdk-go-v2/service/s3 v1.39.0
```

**Comment by harshavardhana** [comment]
This API is not supported on purpose, AWS seems to have come up with new APIs that basically are just the same APIs rehashed into another API. 

```
  PublicAccessBlockConfiguration: &types.PublicAccessBlockConfiguration{
    BlockPublicAcls:       true,
    BlockPublicPolicy:     true,
    IgnorePublicAcls:      true,
    RestrictPublicBuckets: true}})
```

You can write an IAM policy where you can reject

- `BucketPolicies` API can be rejected 
- ACLs are legacy and not supported on MinIO
- Buckets are restricted for public access by default

This API is mostly not very useful and it is not implemented currently on purpose. If you do have a pressing need please reach out to us at hello@min.io - we can see if there is a commercial requirement.

Right now we do not have the bandwidth or cycles to work on this API.

**Comment by tetra12** [comment]
Well, this API is used in AWS `Terraform provider` and many ppl wrote terraform code, which implements this API. Are you still sure you are not interested in implementing this?
```tf
resource "aws_s3_bucket_public_access_block" "s3_bucket" {
bucket = aws_s3_bucket.s3_bucket.id

block_public_acls = true
block_public_policy = true
ignore_public_acls = true
restrict_public_buckets = true
}
```
Using IAM role to assume is another approach to this problem and definitely much more complicated. Note, that current AWS S3 code works perfectly with this provider and hence API
