### ISSUE TITLE
Having Trouble Setting Region From Systemd Env File

### ISSUE THREAD

**Issue by irishgordo** [minio/minio#18089]
Hi there, hope all is going great - really adore MinIO!

I'm having some issues setting configuration constants:
https://github.com/minio/minio/blob/4eeb48f8e09b86db8ec8ce49ca74404d93912ffe/internal/config/constants.go#L26-L84

From the systemd service's EnvironmentFile (/etc/default/minio):
```bash
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local

User=minio-user
Group=minio-user

EnvironmentFile=/etc/default/minio
```
In the /etc/default/minio:
```bash
MINIO_VOLUMES="/mnt/minio-data/data"

MINIO_OPTS="--certs-dir /home/minio-user/.minio/certs --console-address :9001"

MINIO_ROOT_USER=minioadmin

MINIO_ROOT_PASSWORD=minioadmin

MINIO_SITE_REGION="sample-test-1"
MINIO_REGION="sample-test-1"
MINIO_REGION_NAME="sample-test-1"

MINIO_SERVER_URL="https://192.168.3.254:9000"
```

But yet the `Server Location` under the Settings -> Region -> Server Location - remains unset to anything provided in the EnvironmentFile configuration from the SystemD service.

![Screenshot from 2023-09-22 10-48-20](https://github.com/minio/minio/assets/5370752/55cb7816-8416-4fcb-9259-c9261d006084)

## Expected Behavior
That something like:
- MINIO_SITE_REGION
- MINIO_REGION
- MINIO_REGION_NAME
One / all of those could possibly set the Settings -> Region -> Server Location in MinIO.

## Current Behavior
The EnvironmentFile variables concerning Region seemingly not setting Settings -> Region -> Server Location in MinIO

## Context
Just trying to automatically provision MinIO and running into this issue

## Regression
N/A - probably user error :sweat_smile: 

## Your Environment
```
minio version RELEASE.2023-09-20T22-49-55Z (commit-id=9788d85ea3a99eeed8073a57a21ccee71035f152)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

Linux pxe-server-kea 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux
```
- Vagrant VM w/ Libvirt as the Provider, provisioning additionally with Ansible

Thanks again so much for the work on this awesome product!
And thanks for any answers/input!
Super willing to close this out too, if it's not so much a bug but pure-user error :sweat_smile:

**Comment by harshavardhana** [comment]
> * MINIO_SITE_REGION
> * MINIO_REGION
> * MINIO_REGION_NAME
>   One / all of those could possibly set the Settings -> Region -> Server Location in MinIO.

New value is MINIO_SITE_REGION

> The EnvironmentFile variables concerning Region seemingly not setting Settings -> Region -> Server Location in MinIO

Environment file don't set the values in UI, UI values are based on `mc admin config set alias/ site region=<region-name>` 

Setting via environment overrides config settings.

**Comment by irishgordo** [comment]
@harshavardhana  thanks so much for helping me understand that a bit more! :+1:

**Comment by jamie-pate** [comment]
MINIO_SITE_REGION doesn't seem to be in the documentation :sob:
