### ISSUE TITLE
Unable to use the drive with persistence.existingClaim

### ISSUE THREAD

**Issue by mrlioncub** [minio/minio#18096]
Install:
```bash
helm install --set persistence.existingClaim=miniostorage minio/minio --version 5.0.13
$ kubectl get pod
NAME                    READY   STATUS    RESTARTS   AGE
minio-6bc68b9d4-b7mbn   1/1     Running   0          26s
```
After restart pod:
```
$ kubectl delete pod minio-6bc68b9d4-b7mbn
pod "minio-6bc68b9d4-b7mbn" deleted
kubectl get pod
NAME                    READY   STATUS             RESTARTS     AGE
minio-6bc68b9d4-tdqv9   0/1     CrashLoopBackOff   1 (1s ago)   5s
$ kubectl logs minio-6bc68b9d4-tdqv9
ERROR Unable to use the drive /export: drive access denied: Invalid arguments specified
```
When deleting directory /export/.minio.sys pod will start
How to start minio without deleting directory /export/.minio.sys ?

**Comment by harshavardhana** [comment]
> $ kubectl delete pod minio-6bc68b9d4-b7mbn
> pod "minio-6bc68b9d4-b7mbn" deleted
> kubectl get pod
> NAME                    READY   STATUS             RESTARTS     AGE
> minio-6bc68b9d4-tdqv9   0/1     CrashLoopBackOff   1 (1s ago)   5s
> $ kubectl logs minio-6bc68b9d4-tdqv9
> ERROR Unable to use the drive /export: drive access denied: Invalid arguments specified

We cannot use the drive due to permissions, please fix the permissions for the drive. It looks like after restarting your pod has changed the security context or runs as a different user than before. 

This is not a MinIO problem as such, either that or the CSI layer is buggy here.

**Comment by mrlioncub** [comment]
This azure files. Access is allowed:
```
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks 
```
Before and after restarting:
```bash
$ kubectl exec minio-6bc68b9d4-tdqv9 -- ls -al /export
total 4
drwxrwxrwx    2 root     root             0 Sep 22 17:23 .
drwxr-xr-x    1 root     root          4096 Sep 25 03:20 ..
drwxrwxrwx    2 root     root             0 Sep 25 04:45 .minio.sys
```
This helm can't working with Azure Files?

**Comment by harshavardhana** [comment]
> This helm can't working with Azure Files?

Looks like Azure Files here is returning an error where it is disallowing some calls from MinIO I guess we make some posix calls that they do not support.

Please use regular disks with MinIO, it can be virtualized volume blocks that Azure provides as well but not Azure Files.

**Comment by mrlioncub** [comment]
Thanks, I'll try
