### ISSUE TITLE
Crash when invoking csv.NewReader and csv.(*Reader).Read

### ISSUE THREAD

**Issue by secsys-go** [minio/minio#18098]
## NOTE
We used the Fuzz engine to modify some input data of the unit test, `TestRead` in package `internal/s3select/csv`, and then the following deadlock crash appeared. 

## Expected Behavior
We think this deadlock should not happen. It is best to handle it instead of letting it crash.

## Current Behavior
When we invoke `NewReader` with some fuzzed arguments, then if we continue to call the `Read` method on the returned `Reader` object, deadlock happens. It crashes as
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000045380, {0x109d22c?, 0xeedc33?}, 0x10aeaa8)
	D:/.../go1.19/src/testing/testing.go:1494 +0x37a
testing.runTests.func1(0xc000236630?)
	D:/.../go1.19/src/testing/testing.go:1846 +0x6e
testing.tRunner(0xc000045380, 0xc00018fcd8)
	D:/.../go1.19/src/testing/testing.go:1446 +0x10b
testing.runTests(0xc0000003c0?, {0x12145c0, 0x4, 0x4}, {0x1b009db0108?, 0x40?, 0x0?})
	D:/.../go1.19/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc0000003c0)
	D:/.../go1.19/src/testing/testing.go:1726 +0x5d9
main.main()
	_testmain.go:63 +0x1aa

goroutine 6 [chan receive (nil chan)]:
github.com/minio/minio/internal/s3select/csv.(*Reader).Read(0xc0001400f0, {0x0?, 0x0})
	D:/.../minio/internal/s3select/csv/reader.go:67 +0xa5
github.com/minio/minio/internal/s3select/csv.TestRead_POC(0x0?)
	D:/.../minio/internal/s3select/csv/TestRead_POC_test.go:43 +0x177
testing.tRunner(0xc000045520, 0x10aeaa8)
	D:/.../go1.19/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	D:/.../go1.19/src/testing/testing.go:1493 +0x35f
```

## Possible Solution
This crash may be as result of lacking careful argument checks in `NewReader`. It's better to look into the relevant argument checks code.

## Steps to Reproduce (for bugs)
The simplified test code is followed.
```go
data1 := "1,2,3\ta,\x8f,c\t"
data2 := "\t"
data3 := ","

var record sql.Record

r, _ := NewReader(io.NopCloser(strings.NewReader(data1)), &ReaderArgs{
	FileHeaderInfo:             none,
	RecordDelimiter:            data2,
	FieldDelimiter:             data3,
	QuoteCharacter:             defaultQuoteCharacter,
	QuoteEscapeCharacter:       defaultQuoteEscapeCharacter,
	CommentCharacter:           defaultCommentCharacter,
	AllowQuotedRecordDelimiter: false,
	unmarshaled:                true,
})

r.Read(record)
```

## Context
We use fuzz technique to find out this deadlock. We are not sure if this sceanario can actually happen in real world. However, from our points of view, the project should strive to avoid crashes as much as possible and not assume how users will use it. 

## Regression
We are not sure if this issue is a regression.

## Your Environment
Go version: 1.19
Minio commit hash: [c8a57a8](https://github.com/minio/minio/commit/c8a57a8fa273d75ce5cadbb6a9610567a1409826)

**Comment by klauspost** [comment]
`r, _ := NewReader`

You are ignoring the returned error: `expected error UTF-8 encoding is required.`

**Comment by secsys-go** [comment]
However, this project's unit test `TestRead` in `internal/s3select/csv/reader_contrib_test.go` does not check the error either. Should we not assume how users will use it, at least we should not let it crash？

**Comment by klauspost** [comment]
@secsys-go That is not the point of that test. This is an internal package, so there are no external "users".

You cannot import it in any other project.
