### ISSUE TITLE
ListObjectsV2: Invalid combination of marker and prefix when no Marker is set

### ISSUE THREAD

**Issue by milosgajdos** [minio/minio#18093]
**Is your feature request related to a problem? Please describe.**

We're looking into using `minio` for integration testing on one of OSS projects (https://github.com/distribution/distribution). However, we are running into situations that were already reported and somewhat alleviated in https://github.com/minio/minio/pull/5425

We get the following error printed into mini console on one of our tests:
```shell
Error: Invalid combination of marker 'var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001' and prefix 'var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001/test-list-objects-v2/' (cmd.InvalidMarkerPrefixCombination)
       7: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       6: internal/logger/logonce.go:149:logger.LogOnceIf()
       5: cmd/erasure-server-pool.go:1358:cmd.(*erasureServerPools).ListObjects()
       4: cmd/erasure-server-pool.go:1207:cmd.(*erasureServerPools).ListObjectsV2()
       3: cmd/bucket-listobjects-handlers.go:210:cmd.objectAPIHandlers.listObjectsV2Handler()
       2: cmd/bucket-listobjects-handlers.go:156:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
``` 

This happens at least in one situation when a `Prefix` is specified but no `Marker` https://github.com/distribution/distribution/blob/5e6af2f13f78f0755655d93f58b6794aa227e7c1/registry/storage/driver/s3-aws/s3.go#L1077-L1082 which calls `ListObjectsV2PagesWithContext` in `Go` AWS SDK.

**Describe the solution you'd like**

Don't return an error. I am also not entirely sure how the `Marker` ends up being set on that request. Is that because Go AWS SDK is silly? I have not been able to find any info about it in the SDK docs (it = marker being set).

**Comment by harshavardhana** [comment]
yes this is expected we do not allow listing from a marker without a specific prefix supplied. 

> This happens at least in one situation when a `Prefix` is specified but no `Marker` https://github.com/distribution/distribution/blob/5e6af2f13f78f0755655d93f58b6794aa227e7c1/registry/storage/driver/s3-aws/s3.go#L1077-L1082 which calls `ListObjectsV2PagesWithContext` in `Go` AWS SDK.

Its the other way around, what is the reason for setting a marker different and prefix empty??

**Comment by harshavardhana** [comment]
In fact here the marker is wrong 

> ```shell
> Error: Invalid combination of marker 'var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001' and prefix 'var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001/test-list-objects-v2/' (cmd.InvalidMarkerPrefixCombination)
> ```

you want to specify a marker that is inside the prefix 

```
var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001/test-list-objects-v2/
```

StartAfter is a bit meaningless here if it's set at 

```
var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001
```

and you are asking to list objects inside

```
var/folders/k5/l4sqthk96gx22zhccyqw91980000gn/T/TestListObjectsV22270457694/001/test-list-objects-v2/
```

**Comment by harshavardhana** [comment]
okay I see it looks like a user-supplied value which is wrong https://github.com/distribution/distribution/blob/5e6af2f13f78f0755655d93f58b6794aa227e7c1/registry/storage/driver/s3-aws/s3.go#L1050C66-L1050C66

**Comment by harshavardhana** [comment]
A start-after must be a value that is inside the `prefix` supplied for correctness

**Comment by harshavardhana** [comment]
However we could potentially not return an error here as well @milosgajdos

**Comment by harshavardhana** [comment]
what is the expected response here? empty?

**Comment by milosgajdos** [comment]
> Its the other way around, what is the reason for setting a marker different and prefix empty??

As I said, and as you may have seen in the code, we don't set `Marker` at all. We use Pagination methods (https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/making-requests.html); there is also a bit of confusion created by AWS SDK (of course there must be) -- it provides `Marker` field as well as `StartAfter` (which we do use) and calls it a marker 🫠

> Instead of managing these tokens or markers, you can use pagination methods provided by the SDK.

**Comment by milosgajdos** [comment]
> what is the expected response here? empty?

This, I need to have a think about. I'm not sure why this works with S3 - I need to look into it

**Comment by klauspost** [comment]
@milosgajdos If you can grab the requests and output we may be able to figure out what it is doing. 

Semantically `abc/123` *is* after `abc`. It is just pointless. But we may be able to just ignore it in that case.

I can add a PR that does this and ignores "StartAfter", if it is before the prefix requested, and maybe returns an empty result if after.

**Comment by milosgajdos** [comment]
@klauspost thanks, yes, I'll do some experiments later on today and will report back.

**Comment by klauspost** [comment]
Proposed change in https://github.com/minio/minio/pull/18099
