### ISSUE TITLE
Add swift s3 tier error

### ISSUE THREAD

**Issue by rensongqi** [minio/minio#18097]
## NOTE
Hi, I'm using swift s3 as a tier for minio, and I get an error when I add a tier:
`Failed to perform PUT Transfering payloads in multiple chunks using aws-chunked is not supported.`
![1695621355321](https://github.com/minio/minio/assets/49969527/4055782c-2b27-4923-9c20-490f944b7c66)

## Possible Solution
Doesn't minio tier support Swift s3?

## Your Environment
minio version：RELEASE.2023-03-13T19-46-17Z
swift s3 tier version: 2.23.1
swift version: v3.13

**Comment by harshavardhana** [comment]
They do not support streaming signature v4, Swift S3 is broken and not maintained you shouldn't be using that anymore. 

Migrate your deployment to MinIO - feel free to reach out to us at hello@min.io for any migration help.
