### ISSUE TITLE
Error in metrics sent from MinIO to Prometheus

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#18100]
We use Prometheus for monitoring out MinIO cluster. We have 4 nodes with 4 disks on each. Today I've erase one disk for checking healing performance. After erasing disk starts filling with data at approx. 10 MB/s. Then I goes to grafana and see that 3 nodes only receives data at 10 MB/s total and one node (which have erased disk connected) doesn't send or receive data. This is internode data transfer chart. 

![image](https://github.com/minio/minio/assets/13428863/9983e479-0288-49fa-8da8-0a5dad16974c)

## Expected Behavior
As I think I should see that 3 nodes sending data and 1 receives it. Total speed of 3 nodes sending should equal speed of 1 node receiving.

## Current Behavior
3 nodes receiving only and one node have no internode traffic.

## Your Environment

* Version used (`minio --version`): 2023-09-23T03:47:50Z
* Server setup and configuration: 4 nodes with 4 drives on each
* Operating System and version (`uname -a`): Linux minio-cold-4 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AlexZIX** [comment]
It seems that same situation with Node IO metrics. minio-cold-4 is a node where drive was erased and now filling with data at approx. 10 MB/s. But according following chart this node read 10 times more that write.

![image](https://github.com/minio/minio/assets/13428863/056c8c05-4e12-4e56-a85a-09676ddf26bf)

Also there is no more metrics for buckets available. Previously data for Prometheus includes bucket name, size, etc.

**Comment by AlexZIX** [comment]
Also I've found that minio doesn't send information about buckets to Prometheus anymore. Previously we have information about buckets name, sizes, etc. Now it's empty.

**Comment by AlexZIX** [comment]
UPD: no changes after update to 2023-10-07T15:07:38Z - still no information about buckets and wrong data in statistics.

**Comment by AlexZIX** [comment]
Found that now information about buckets moved from minio/v2/metrics/cluster to minio/v2/metrics/bucket

**Comment by caspereijkens** [comment]
Unrelated to your issue, but how does your bucket count look? Ours looks super messy ever since the grafana dashboard queries `minio_cluster_bucket_total` we created a github issue for it as well: https://github.com/minio/minio/issues/18672

I wonder if you are seeing the same?

**Comment by AlexZIX** [comment]
With the latest MinIO it looks followng:

![image](https://github.com/minio/minio/assets/13428863/da78e6fc-5500-4105-aa1e-2087aa484004)
