### ISSUE TITLE
Allow to create internal user without settings a password

### ISSUE THREAD

**Issue by nixargh** [minio/minio#18103]
**Is your feature request related to a problem? Please describe.**
I'm creating new local users with Terraform and then someone creates Access Key for them. If I set password using Terraform it stays at terraform's state that is not secure.

**Describe the solution you'd like**
It would be perfect to allow creating local users w/o password (or with an empty password) and forbid them to login until password is set or Access Key is created.

**Describe alternatives you've considered**
Without such feature I have to change new user's password manully or I have to write some local-exec for Terraform to do it automagically after creation.

**Comment by harshavardhana** [comment]
A user without password is not idiomatic, we won't be doing that.

**Comment by nixargh** [comment]
> A user without password is not idiomatic, we won't be doing that.

You are the owner, so it is up to you but original author of s3 concept, I mean AWS, is doing just like this with their users. User is a user, but he needs a key to enter and key is some other object, not a part of the user like and arm or leg. There are access keys in MinIO but also user's secrets that is a bit confusing actually.
