### ISSUE TITLE
[helm] post-job fails "mc: <ERROR> Unable to initialize new alias from the provided credentials"

### ISSUE THREAD

**Issue by jurim76** [minio/minio#18106]
Helm chart post-job unable to create any object

## Expected Behavior

Helm chart installed correctly, post-job finished correctly

## Current Behavior

minio chart post-job fails with the error during helm install

`kubectl logs minio-cluster-post-job-rp874`
```
mc: <ERROR> Unable to initialize new alias from the provided credentials. The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

## Steps to Reproduce (for bugs)

1. Define bucket in chart values.yaml
```
buckets:
  - name: test
```
  
3. Install helm chart
`helm install minio .`

4. Define mc alias in .mc/config.json
```
"local": {
  "url": "http://localhost:9000",
  "accessKey": "root",
  "secretKey": "****",
  "api": "s3v4",
  "path": "auto"
}
```

5. Forward minio service to localhost
`kubectl port-forward svc/minio 9000:9000`

6. Create minio bucket, using local mc
`mc mb local/test`
```
Bucket created successfully `local/test`
```

## Your Environment

* Version used (`minio --version`): RELEASE.2023-09-23T03-47-50Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux minio-cluster-0 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 x86_64 x86_64 GNU/Linux

Kubernetes version: 1.22
Minio chart version: 15.0.3
mcImage version: RELEASE.2023-09-22T05-07-46Z
Post-job pod env
```
   env:
    - name: MINIO_ENDPOINT
      value: minio
    - name: MINIO_PORT
      value: "9000"
```

**Comment by harshavardhana** [comment]
It looks like secret key is wrong here @jurim76

**Comment by jurim76** [comment]
Thank you
minio pod uses vault annotation, but post-job pod not
I will use external secret in this case
