### ISSUE TITLE
java.io.FileNotFoundException: The specified multipart upload does not exist.

### ISSUE THREAD

**Issue by ghuangups** [minio/minio#18105]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Run teragen against MinIO getting FileNotFoundException.

## Expected Behavior

The job should succeed without failure

## Current Behavior

The map failed with the exception FileNotFoundException.

## Steps to Reproduce (for bugs)

1. Installed this one: minio-20230904195737.0.0.x86_64.rpm
2. Setup a MinIO server with 12 nodes, 3 disk on each node. This is probably not necessary to repro this bug
3. Run teragen to generate say 200 gb data against MinIO.
4. Stack:

`Error: java.io.FileNotFoundException: Completing multipart upload on teragen-out-200g/_temporary/1/_temporary/attempt_1695157064529_0010_m_000109_0/part-m-00109: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 1787BEC2B8E894CC; S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce; Proxy: null), S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce:NoSuchUpload at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:256) at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:121) at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$4(Invoker.java:348) at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:440) at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:344) at org.apache.hadoop.fs.s3a.WriteOperationHelper.finalizeMultipartUpload(WriteOperationHelper.java:350) at org.apache.hadoop.fs.s3a.WriteOperationHelper.completeMPUwithRetries(WriteOperationHelper.java:393) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.lambda$complete$1(S3ABlockOutputStream.java:886) at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.measureDurationOfInvocation(IOStatisticsBinding.java:490) at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:461) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.complete(S3ABlockOutputStream.java:884) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.access$1200(S3ABlockOutputStream.java:691) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.close(S3ABlockOutputStream.java:415) at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77) at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) at org.apache.hadoop.examples.terasort.TeraOutputFormat$TeraRecordWriter.close(TeraOutputFormat.java:96) at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.close(MapTask.java:682) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:805) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/javax.security.auth.Subject.doAs(Subject.java:439) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168) Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 1787BEC2B8E894CC; S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce; Proxy: null), S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3630) at org.apache.hadoop.fs.s3a.WriteOperationHelper.lambda$finalizeMultipartUpload$1(WriteOperationHelper.java:357) at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:119) ... 22 more `

## Regression

Not sure

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2023-09-04T19-57-37Z (commit-id=1c99fb106c3e1448ed92f8465d5695d055d432e7)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

* Server setup and configuration: 12 nodes with 3 HDD disk each node
* Operating System and version (`uname -a`):
Linux xxxxxx.xxxx.xxxxxxxx.com 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@ghuangups please upgrade to latest release and let us know how it goes?

**Comment by harshavardhana** [comment]
And how long was this job running? Can you provide `mc admin config get alias api` output?

**Comment by ghuangups** [comment]
minio version RELEASE.2023-09-23T03-47-50Z (commit-id=22041bbcc469f5ac84207d09b4c4db326ec5fd57)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

**Comment by ghuangups** [comment]
![Screenshot 2023-09-28 at 6 30 18 AM](https://github.com/minio/minio/assets/28374064/f27af7c3-f44f-444d-b024-456d143f0afb)

**Comment by ghuangups** [comment]
Error: java.io.FileNotFoundException: Completing multipart upload on teragen-out-200g/_temporary/1/_temporary/attempt_1695686873460_0003_m_000007_0/part-m-00007: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 178906A04B3ADCF3; S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce; Proxy: null), S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce:NoSuchUpload at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:256) at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:121) at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$4(Invoker.java:348) at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:440) at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:344) at org.apache.hadoop.fs.s3a.WriteOperationHelper.finalizeMultipartUpload(WriteOperationHelper.java:350) at org.apache.hadoop.fs.s3a.WriteOperationHelper.completeMPUwithRetries(WriteOperationHelper.java:393) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.lambda$complete$1(S3ABlockOutputStream.java:886) at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.measureDurationOfInvocation(IOStatisticsBinding.java:490) at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:461) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.complete(S3ABlockOutputStream.java:884) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.access$1200(S3ABlockOutputStream.java:691) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.close(S3ABlockOutputStream.java:415) at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77) at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) at org.apache.hadoop.examples.terasort.TeraOutputFormat$TeraRecordWriter.close(TeraOutputFormat.java:96) at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.close(MapTask.java:682) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:805) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/javax.security.auth.Subject.doAs(Subject.java:439) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168) Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 178906A04B3ADCF3; S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce; Proxy: null), S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3630) at org.apache.hadoop.fs.s3a.WriteOperationHelper.lambda$finalizeMultipartUpload$1(WriteOperationHelper.java:357) at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:119) ... 22 more

**Comment by ghuangups** [comment]
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_priority=auto transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m odirect=on gzip_objects=off root_access=on sync_events=off

**Comment by ghuangups** [comment]
@harshavardhana , thanks!

**Comment by harshavardhana** [comment]
@ghuangups while you are running this job can you capture `mc admin trace alias/ > trace-all.log`  and gzip the file and share it here.

**Comment by ghuangups** [comment]
[trace-all.log.zip](https://github.com/minio/minio/files/12784790/trace-all.log.zip)

**Comment by ghuangups** [comment]
Error: java.io.FileNotFoundException: Completing multipart upload on teragen-out-200g/_temporary/1/_temporary/attempt_1695686873460_0010_m_000008_0/part-m-00008: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 178A3EC7CA97F4E6; S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce; Proxy: null), S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce:NoSuchUpload at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:256) at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:121) at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$4(Invoker.java:348) at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:440) at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:344) at org.apache.hadoop.fs.s3a.WriteOperationHelper.finalizeMultipartUpload(WriteOperationHelper.java:350) at org.apache.hadoop.fs.s3a.WriteOperationHelper.completeMPUwithRetries(WriteOperationHelper.java:393) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.lambda$complete$1(S3ABlockOutputStream.java:886) at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.measureDurationOfInvocation(IOStatisticsBinding.java:490) at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:461) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.complete(S3ABlockOutputStream.java:884) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream$MultiPartUpload.access$1200(S3ABlockOutputStream.java:691) at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.close(S3ABlockOutputStream.java:415) at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77) at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) at org.apache.hadoop.examples.terasort.TeraOutputFormat$TeraRecordWriter.close(TeraOutputFormat.java:96) at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.close(MapTask.java:682) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:805) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:347) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/javax.security.auth.Subject.doAs(Subject.java:439) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168) Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 178A3EC7CA97F4E6; S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce; Proxy: null), S3 Extended Request ID: 9a479d3cc839c6302bcbb4ea220c60760f4c53b090136311ed0bddd815d2b7ce at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3630) at org.apache.hadoop.fs.s3a.WriteOperationHelper.lambda$finalizeMultipartUpload$1(WriteOperationHelper.java:357) at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:119) ... 22 more

**Comment by ghuangups** [comment]
Attempt:
[attempt_1695686873460_0010_m_000008_0](https://ve0304.halxg.cloudera.com:19890/jobhistory/task/task_1695686873460_0010_m_000008)

Failed.

**Comment by ghuangups** [comment]
trace uploaded, also included latest error stack. Thanks @harshavardhana !

**Comment by klauspost** [comment]
You didn't manage to capture the actually failing call

```
λ grep "1695686873460_0010_m_000008_0" trace-all.log
2023-10-01T20:30:11.117 [200 OK] s3.NewMultipartUpload ...
2023-10-01T20:30:11.156 [200 OK] s3.PutObjectPart ...
...
2023-10-01T23:07:49.363 [200 OK] s3.PutObjectPart ... &partNumber=1538
```

So the actual upload takes more than 3 hours. Since the actual call that is failing is missing, I'd guess this is what you are seeing.

Could you post `mc admin config get ALIAS api`?

**Comment by ghuangups** [comment]
# mc admin config get minioserver api
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_priority=auto transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m odirect=on gzip_objects=off root_access=on sync_events=off

**Comment by ghuangups** [comment]
Not sure why the trace did not catch the failing call. I had the trace running all the time until the job itself failed. @klauspost

**Comment by ghuangups** [comment]
Any update? Are there any performance improvement related settings I can try? I'm surprised that it was taking multiple hours to write 150 gb data with magic committer.

**Comment by harshavardhana** [comment]
> Any update? Are there any performance improvement related settings I can try? I'm surprised that it was taking multiple hours to write 150 gb data with magic committer.

We can help you with that if you have a production requirement, please reach out to use at hello@min.io - performance troubleshooting is for commercial engagements only. 

Otherwise, community help is best effort only.

**Comment by harshavardhana** [comment]
The trace doesn't contain any errors at all, this looks like something else that is happening that is not captured. 

Can you enable client like request logging using log4j and share the debug logs from the client side?

**Comment by ghuangups** [comment]
[AWSClientIOException.zip](https://github.com/minio/minio/files/12935173/AWSClientIOException.zip)

**Comment by ghuangups** [comment]
Took another trace while running dfsio against MinIO. Looks like the http connection was reset/break by MinIO, seems a bug from the server side. @harshavardhana , @klauspost

**Comment by ghuangups** [comment]
"YzA0NjZlNTgtZmI3MC00MDMxLTg2ZTMtOWZhZjdjYmI3ZWFjLmVkZmY2MjBhLTdiODUtNDU3Zi1iNmI0LTAwYzNkNWU0ZTY2ZA on benchmarks/TestDFSIO/io_data/test_io_495: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset by peer: Unable to execute HTTP request: Connection reset by peer"

**Comment by klauspost** [comment]
MinIO doesn't have timeouts. Check your load balancer and your network.

**Comment by ghuangups** [comment]
Seems this was http connection reset/break from MinIO: Connection reset by peer: Unable to execute HTTP request: Connection reset by peer"
