### ISSUE TITLE
Public download link of file

### ISSUE THREAD

**Issue by ameue** [minio/minio#18104]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20230920224955.0.0.x86_64.rpm 
* Server setup and configuration: minio server ~/minio 
* Operating System and version (`uname -a`): centos 7

Hello author, I deployed the latest minio service on my Linux server, created a new bucket named file, I set the access policy of this bucket to public, and then I used http:xxx.xxx.xxx. Access the download link of xxx:port/file/test.zip in the browser. The downloaded file is fixedly smaller than 2kb and cannot be opened. What is the reason?

**Comment by harshavardhana** [comment]
Because by default bucket is not public, so you need make your bucket public to access your objects publicly.
