### ISSUE TITLE
audit webhook not working

### ISSUE THREAD

**Issue by umjsio** [minio/minio#18128]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
audit webhook should be triggered whenever there's S3 API call

## Current Behavior
audit webhook is not triggering

## Steps to Reproduce (for bugs)

1. start minio
2. configure audit webhook in the console (currently using https://webhook.site/ for testing)
3. waiting for webhook to be called

## Context
recently upgraded from RELEASE.2023-09-16T01-01-47Z to RELEASE.2023-09-23T03-47-50Z

## Your Environment

* Version used (`minio --version`): RELEASE.2023-09-23T03-47-50Z
* Server setup and configuration: docker single node
* Operating System and version (`uname -a`): Linux 5.15.0-104.119.4.2.el8uek.x86_64

**Comment by shtripat** [comment]
There has been a regression which got fixed as part of https://github.com/minio/minio/pull/18112.
This would be available as part of next release.
