### ISSUE TITLE
Use AWS-IAM-ROLE for copying objects to S3 bucket

### ISSUE THREAD

**Issue by robert-pudlowski-mox** [minio/minio#18121]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
I have REMOTE TIER configured as S3 bucket using AWS IAM ROLE and I would like to manually copy files from my minio bucket to Remote Tier S3 bucket. 

## Current Behavior
When I try to execute command mc cp myminio/opencti-bucket/file.txt s3/bucket/file.txt -  I'm getting error that  The AWS Access Key Id you provided does not exist in our records. But I don't want to use AWS Access Key. I already have Remote Tier configured to use AWS IAM ROLE. 

ILM is working fine using AWS IAM ROLE but single CP or MV command no.

## Possible Solution
Add possibility to use AWS IAM ROLE flag for CP or MV command. 

## Steps to Reproduce (for bugs)

1. Configure Remote Tier as S3 bucket using AWS IAM ROLE (--use-aws-role)
2. Execute copy command: mc cp myminio/opencti-bucket/file.txt s3/bucket/file.txt
3.Error is appearing: The AWS Access Key Id you provided does not exist in our records.
4.

## Context
I can not use CP or MV command in order to move some objects from minio to S3 when I use AWS IAM Role instead of AWS Access Key

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2023-05-18T00-05-36Z
* Server setup and configuration: EKS
* Operating System and version (`uname -a`): Linux

**Comment by harshavardhana** [comment]
@robert-pudlowski-mox can you upgrade to latest and give it a try ?

**Comment by robert-pudlowski-mox** [comment]
@harshavardhana  but should I execute the CP or MOVE command with additional flag --use-aws-role? or I should just execute the same command?  mc cp myminio/opencti-bucket/file.txt s3/bucket/file.txt?

**Comment by robert-pudlowski-mox** [comment]
I updated the MINIo to latest version and I'm getting the same error

```
mc cp --recursive myminio/opencti-bucket s3/bucket/opencti-bucket
mc: <ERROR> Failed to copy `http://opencti-minio:9000/opencti-bucket/import/Artifact/02e7aada-2a91-4880-b62e-28f0e376cded/9174951098e4ca03d8902442071ec42c1d2dc4c9d689d36c7111c78367ce720b`. The AWS Access Key Id you provided does not exist in our records.
```

**Comment by saikumarbaker** [comment]
@harshavardhana  , @robert-pudlowski-mox   i was also looking for the same use case where i need to enable REMOTE TIER as aws s3  . I managed to give permission to my minio pod  via service account and attaching a iam role to it (rbac through eks oidc) . I want to understand if there is a way instead of running the mc commands can we directly setup the remote tier configuration as some env variables in the deployment spec of minio ?

**Comment by harshavardhana** [comment]
Okay so looks like you are making a mistake here. `mc` requires static credentials if you don't have static then you should get those credentials via a script and pass it to mc as a temporary alias like

```
export MC_HOST_s3=https://accesskey:secretkey:sessionToken@s3.amazonaws.com/
mc ls s3/
```

This issue has nothing to do with tiering.
