### ISSUE TITLE
Posibility to have package debian / redhat with latest in the name of the package on https://dl.min.io/server/minio/release/linux-amd64/

### ISSUE THREAD

**Issue by cstisa** [minio/minio#18132]
**Is your feature request related to a problem? Please describe.**

We wanted to automate the process of update of a MinIO deployement using packages via an Configuration Management tool (e.g: ansible) by downloading the .deb or .rpm file from https://[dl.min.io/server/minio/release/linux-amd64/](https://dl.min.io/server/minio/release/linux-amd64/) but unfortunatelly the package name is in the form of _minio_20230923034750.0.0_amd64.deb_  which can not be automated easily.

**Describe the solution you'd like**

We wanted to have the latest release in a form of minio_latest_amd64.rpm or minio_latest_amd64.deb  file format if that is possible.

Thank you.

Best Regards, Edouard Fazenda.

**Comment by harshavardhana** [comment]
We can add a symlink.

**Comment by cstisa** [comment]
Hi @harshavardhana ,

It could be great thanks :) 

Have a nice day.

Best Regards,

**Comment by cstisa** [comment]
Hello, 

Any updates ? 

Thank You.

Best Regards,

**Comment by harshavardhana** [comment]
Sorry this took longer than expected

https://dl.minio.io/server/minio/release/linux-amd64/minio.deb
https://dl.minio.io/server/minio/release/linux-amd64/minio.rpm
https://dl.minio.io/server/minio/release/linux-amd64/minio.apk
