### ISSUE TITLE
Add target type in replication bucket

### ISSUE THREAD

**Issue by G0zsilva** [minio/minio#18149]
Hello guys, 

We are using Minio in our project and we are enjoying it, but a challenge rise and analyzing the code I would like to make a feature suggestion...

When we are going to do a bucket replication, we cannot choose a target type like that is Tiering scenario. 

When we add other storage solutions such as Wasabi or Backblaze, the initial communication of checking API keys even works because S3 api schema, but object replication is often paused due to the function that checks the health status of the destination target:

![image](https://github.com/minio/minio/assets/9352410/8eb42491-ea0a-40c0-834f-4321bb66afa5)

As these solutions do not have the same health routes as Minio, logically dozens of error logs are triggered and replication is paused. At times, replication even works and the object transition occurs due to the logic in the code allowing replication between health check periods. 

When we set the health check to 0 (thinking about ignoring this HC process), it also doesn't work, and replication stops completely.

So initially I thought about making a PR to adjust the problem of disabling the HC using 0, but I thought about whether Minio's planning exists to allow replication of objects using targets that are not just Minio endpoints.

**Comment by harshavardhana** [comment]
Server side replication is only MinIO to MinIO. You cannot use some other vendor as a replication target.

If you want to replicate to S3 like vendors then you should use batch replication

https://min.io/docs/minio/linux/reference/minio-mc/mc-batch-generate.html
