### ISSUE TITLE
Fail to start RELEASE.2023-09-30T07-02-29Z with special characters in access_key and secret_key

### ISSUE THREAD

**Issue by bengtfredh** [minio/minio#18146]
## NOTE
RELEASE.2023-09-30T07-02-29Z fail to start with special character in access_key and secret_key

## Expected Behavior
Until this version minio can run with special character in access_key and secret_key

## Current Behavior
minio give error:
```
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters
```

## Possible Solution
Run with no special character in access_key and secret_key

## Steps to Reproduce (for bugs)

1. Provide access_key and secret_key with special character 
2. Start minio

## Context
minio is not starting
replaced access_key and secret_key with no special character 

## Regression
Is this issue a regression? Yes
Looks like this issue has happen before:
https://github.com/minio/minio/pull/10223

## Your Environment

* Version used (`minio --version`): RELEASE.2023-09-30T07-02-29Z
* Server setup and configuration: podman
* Operating System and version (`uname -a`): Linux 6.5.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@bengtfredh what is the special character?
