### ISSUE TITLE
XL: Reimplement namespace lock to use patricia/radix trie locking

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1814]
https://github.com/tchap/go-patricia

https://github.com/armon/go-radix

**Comment by harshavardhana** [comment]
Assigned this to @balamurugana

**Comment by GarimaKapoor** [comment]
Bala please update the timeline for resolving this issue

**Comment by harshavardhana** [comment]
Clearing this from XL milestone, it's not a blocker.

**Comment by GarimaKapoor** [comment]
Closing this issue, Unit test for namespace will cover the reimplementation.
