### ISSUE TITLE
MinIO listing for one folder - doesn't list file, but HEAD works OK (on conflicting objects as prefixes)

### ISSUE THREAD

**Issue by tomekit** [minio/minio#18148]
I run a single node cluster where MinIO (RELEASE.2023-08-09T23-30-22Z) runs as Podman and writes to CIFS mount on the host.

This listing issue is something I've seen couple times already, yet I don't have any reproducible instructions.

I understand that's is not recommended to run MinIO on CIFS mount and there aren't many guarantees.
On the other hand I've got a situation now where writes to other location works fine, but writes to the broken location: `test/` are consistently broken (the listing doesn't include changes). This leads me to thinking that perhaps it would be beneficial if there is some sort of repair mechanism.

I have full access to the FS, so I can run additional commands to provide more info about what could've gone wrong.

## Current Behavior

```
export BUCKET_NAME=bucket
export ENDPOINT=http://localhost:8333
export AWS_ACCESS_KEY_ID=admin
export AWS_SECRET_ACCESS_KEY=admin

# Create new file
aws --endpoint=$ENDPOINT s3api put-object --bucket $BUCKET_NAME --key test/newFile.txt
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "VersionId": "8560ef25-c654-4267-b504-8be64d0b862a"
}

# MinIO doesn't return it back in the listing: `test/newFile.txt`
aws --endpoint=$ENDPOINT s3api list-objects-v2 --bucket $BUCKET_NAME --prefix test/ --delimiter "/"
{
    "Contents": [
        {
            "Key": "test/",
            "LastModified": "2023-09-30T10:13:41.276000+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD"
        }
    ]
}

# However `head-object` does return the file details.
aws --endpoint=$ENDPOINT s3api head-object --bucket $BUCKET_NAME --key test/newFile.txt
{
    "AcceptRanges": "bytes",
    "LastModified": "2023-09-30T10:57:41+00:00",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "VersionId": "8560ef25-c654-4267-b504-8be64d0b862a",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

## Expected Behavior
```
# Create folder
aws --endpoint=$ENDPOINT s3api put-object --bucket $BUCKET_NAME --key anotherLocation/
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}

# Create file
aws --endpoint=$ENDPOINT s3api put-object --bucket $BUCKET_NAME --key anotherLocation/newFile.txt
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "VersionId": "ffda55d6-ffb2-45b2-b528-02e73af9913f"
}

# `anotherLocation/newFile.txt` file gets returned correctly
aws --endpoint=$ENDPOINT s3api list-objects-v2 --bucket $BUCKET_NAME --prefix anotherLocation/ --delimiter "/"
{
    "Contents": [
        {
            "Key": "anotherLocation/",
            "LastModified": "2023-09-30T10:59:03.222000+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "anotherLocation/newFile.txt",
            "LastModified": "2023-09-30T10:59:12.752000+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD"
        }
    ]
}
```

## Additional info
I was trying to blindly execute `mc admin heal` (https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-heal.html), but I've received:
```
 mc: <ERROR> Unable to get background heal status. This 'admin' API is not supported by server in 'mode-server-xl-single'.
```

Is there any way I could repair my data?

Is there any way I could prevent this happening again?

**Comment by harshavardhana** [comment]
@tomekit you are on a single mount, using cifs which is unreliable.

There is no way to heal or recover from this. There is no redundancy - we print this when the server startups.

**Comment by tomekit** [comment]
Thanks for your response.

> There is no way to heal or recover from this. There is no redundancy - we print this when the server startups.

I've logged in to the box and then deleted the: `xl.meta` file in the affected "broken" folder. Listing works fine again, I can open/save files, version data for files within sub-folders isn't lost. 

Given that the `xl.meta` file that I've deleted was related to empty key: `test/` which was acting as a folder/placeholder, I guess consequences aren't that bad.

**Comment by klauspost** [comment]
> Objects cannot have a conflicting object as its parent. Applications must assign non-conflicting, unique keys.

Details: https://min.io/docs/minio/linux/operations/checklists/thresholds.html#conflicting-objects

**Comment by tomekit** [comment]
Thanks for letting me know.

It seems it's another MinIO inconsistency with AWS S3 API that I wasn't aware of.

Regardless of that, I don't think that conflicting `PUT` that I certainly used here, should lead to corrupted listings. I would've hoped that MinIO would reject such requests.

As per your documentation (https://min.io/docs/minio/linux/operations/checklists/thresholds.html#conflicting-objects
>  the second PUT operation fails because of a naming conflict with the object created by the first.

Given my above request examples I don't think it's the case that PUT operation fails (e.g. with some error code), unless by failure you mean corrupted listing.

**Comment by harshavardhana** [comment]
> Regardless of that, I don't think that conflicting PUT that I certainly used here, should lead to corrupted listings. I would've hoped that MinIO would reject such requests.

We can't reject without converting a write operation into a read operation. This ends up taxing 99.99% of the applications out there.

That's why it's documented on why you shouldn't do it, instead of outrightly rejecting such a scenario.

It is not a corrupted listing, it is simply disallowing to navigate further down the leaf. The leaf for listing ends where the object terminates itself.

**Comment by harshavardhana** [comment]
> the second PUT operation fails because of a naming conflict with the object created by the first.

This documentation must be fixed, we stopped returning errors here long time ago @ravindk89

**Comment by ravindk89** [comment]
@harshavardhana so if I'm understanding correctly, we'll allow the PUT to succeed, but you cannot list at the conflicting prefix level. You can still GET/HEAD, just not LIST.

I assume this might apply if someone attempted to do a deeply nested and poorly constructed tree, e.g.

```
PUT data/key1/foo.txt
PUT data/key1
PUT data/key1/key2/
PUT data/key1/key2/bar.txt
```

For something like this, `LIST data/key1` or `LISTdata/key1/key2` would not return results?

I'll test a bit on my end as well. If we know when this changed precisely I'll make a note.

**Comment by harshavardhana** [comment]
Yes that is correct @ravindk89
