### ISSUE TITLE
Folder's modification date wrong when connected with ftp 

### ISSUE THREAD

**Issue by dennizklnc** [minio/minio#18155]
We can connect with LFTP.Buckets modification  dates are true but when we connect to bucket folders modification date  are 01/01/0001 you can see on attachment.

* Version used (`minio --version`): minio version RELEASE.2023-09-27T15-22-50Z (commit-id=3c470a6b8babc803a2d79e45cccfc806e57a2709)
* Operating System and version (`uname -a`):5.15.0-103.114.4.el8uek.x86_64 #2 SMP Mon Jun 26 10:13:01 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux

<img width="592" alt="Screen Shot 2023-10-02 at 12 40 48" src="https://github.com/minio/minio/assets/146717129/15129047-1805-4d61-a096-48efcb227f30">

**Comment by klauspost** [comment]
There is not concept of "folders" in S3, only prefixes. Since they only exist by name there is no modification date to display.
