### ISSUE TITLE
minio ilm rule not working correctly with tags

### ISSUE THREAD

**Issue by akash123-eng** [minio/minio#18161]
## Expected Behavior
We are trying to tier/transition data from a source bucket to target bucket based on tags irrespective transition days for objects in the source bucket.

when we add ilm rule with tags it should transition data only which has tags and not all the data matching to transition days
So it's taking only transition days in account and not both I.e tags and transition days

## Steps to Reproduce (for bugs)
create a source bucket and a target bucket
add target bucket as a TIER for source bucket using mc ilm tier add command with name **TARGET_TIER**

create 4 folders in mydata alias/tenant
folder1, folder2, folder3, folder4

now add tags using below commands :

```mc tag set myminio/mydata/folder1 "data=old" ```
```mc tag set myminio/mydata/folder2 "data=old" ```

now add ilm rule to transition data which has tags data=old:

``` mc ilm rule add  myminio/mydata --transition-days 0 --transition-tier "TARGET_TIER" --tags "data=old" ```

Now ideally only folder1 and folder2 data should be tiered/transitioned to target bucket
but in our case its tiering all the folders i..e folder1, folder2, folder3, folder4

I thought this might be issue with folder so i created another source bucket added 4 objects there object1.txt,object2.txt,object3.txt,object4.txt and then added tags for 2 objects 
i.e ```mc tag set myminio/mydata1/object1.txt "data=old" ```
 ```mc tag set myminio/mydata1/object2.txt "data=old" ```
 
 
 and then again added ilm rule using 
 ``` mc ilm rule add  myminio/mydata1 --transition-days 0 --transition-tier "TARGET_TIER" --tags "data=old" ```
 
 in this case also all the 4 objects got tiered to target bucket instead of objeect1.txt and object.txt

## Your Environment

* Version used (`minio --version`):
minio kubernetes operator v4.5.8

**Comment by harshavardhana** [comment]
@akash123-eng can you explain about your setup? And share the setup details?

Like MinIO version and number of nodes in this setup?

**Comment by akash123-eng** [comment]
@harshavardhana As mentioned ,we are using minio kubernetes operator v4.5.8.
It's 4 node cluster. 
Does node count affect cli functionality ?
Can you please help on why it's not working with tags properly and how we can do that?

**Comment by harshavardhana** [comment]
@akash123-eng what kind of storage is being managed and where exactly are you tiering this to? 

Please share your `mc ilm export myminio/bucket`

**Comment by akash123-eng** [comment]
@harshavardhana We are having some static file and as mentioned trying to tier from one bucket to other bucket in same minio cluster with s3 type of tier and added ilm rule as mentioned in issue description
Please see below mc ilm ls output:

Transition for latest version (Transition)                                    │
├────────┬─────────┬────────┬─────────────────────┬──────────────┬──────────────┤
│ ID     │ STATUS  │ PREFIX │ TAGS                │ DAYS TO TIER │ TIER         │
├────────┼─────────┼────────┼─────────────────────┼──────────────┼──────────────┤
│ rule-1 │ Enabled │   │ data=old │            0 │ TARGET_TIER │
└────────┴─────────┴────────┴─────────────────────┴──────────────┴──────────────┘
┌────────────────────────────────────────────────────────────────┐

**Comment by akash123-eng** [comment]
@harshavardhana is this happening due to bug in mc ilm cli I.e it's only considering transition days parameter into account and ignoring tags ?

**Comment by harshavardhana** [comment]
> @harshavardhana We are having some static file and as mentioned trying to tier from one bucket to other bucket in same minio cluster with s3 type of tier and added ilm rule as mentioned in issue description Please see below mc ilm ls output:
> 
> Transition for latest version (Transition) │ ├────────┬─────────┬────────┬─────────────────────┬──────────────┬──────────────┤ │ ID │ STATUS │ PREFIX │ TAGS │ DAYS TO TIER │ TIER │ ├────────┼─────────┼────────┼─────────────────────┼──────────────┼──────────────┤ │ rule-1 │ Enabled │ │ data=old │ 0 │ TARGET_TIER │ └────────┴─────────┴────────┴─────────────────────┴──────────────┴──────────────┘ ┌────────────────────────────────────────────────────────────────┐

This is not supported and you shouldn't do it.

Setup separate clusters.

**Comment by akash123-eng** [comment]
@harshavardhana can you please elaborate what do you mean by its not supported ?
We are able to tier objects properly with prefix and transition days. 
It's not working only when tags parameter is used so there is some bug with mc ilm cli or we are not using it properly

**Comment by harshavardhana** [comment]
> @harshavardhana can you please elaborate what do you mean by its not supported ? We are able to tier objects properly with prefix and transition days. It's not working only when tags parameter is used so there is some bug with mc ilm cli or we are not using it properly

It may work but that is something not supported at the moment.

**Comment by akash123-eng** [comment]
@harshavardhana are you saying that currently mc ilm rule works only with prefix and transition days and it doesn't support tags? Can you please explain because our requirement is to transition object based on tags

**Comment by akash123-eng** [comment]
@harshavardhana can you please reply on above?
It would be really helpful

**Comment by klauspost** [comment]
@akash123-eng Please respect that community support is based on best effort. If you need instant replies look into our [subscriptions](https://min.io/pricing) and don't ping people needlessly.

**Comment by akash123-eng** [comment]
@klauspost Apologies for that. Just wanted to understand how mc ilm rule works becasue it's not working with tags which is blocking our task

**Comment by krisis** [comment]
@akash123-eng I couldn't recreate this issue locally with MinIO version `RELEASE.2023-01-12T02-06-16Z`. 
```
$ ./mc ls -r myminio
[2023-10-12 13:11:04 PDT]    20B WARM-1 bucket/obj-1
[2023-10-12 13:11:04 PDT]    20B STANDARD bucket/obj-2
[2023-10-12 13:11:04 PDT]    20B STANDARD bucket/obj-3
[2023-10-12 13:11:04 PDT]    20B STANDARD bucket/obj-4
[2023-10-12 13:11:59 PDT]    20B STANDARD target/f4a8ece8-eeac-4be1-bdf5-1627ca88a6a2/bucket/7e/d0/7ed07597-5354-4b8d-992a-44da4fae1ebb

$ for i in {1..4}; do mc tag list myminio/bucket/obj-${i}; done
Name : http://localhost:9000/bucket/obj-1
data : old
Name : http://localhost:9000/bucket/obj-2
No tags found
Name : http://localhost:9000/bucket/obj-3
No tags found
Name : http://localhost:9000/bucket/obj-4
No tags found
```

From the above output you can see that only `bucket/obj-1` has the tag required to be transitioned to `target` bucket. This is working as expected. It would be helpful if you could share the following information.

1. `mc admin tier ls myminio` or `mc ilm tier ls myminio` depending on your mc version
2. `mc ilm export myminio/data`
3. `mc ls -r myminio/target`
and `mc ls -r myminio/mydata`
This is to learn in detail which objects were transitioned.
4. `mc tag list ...` output for an object which transitioned as expected, i.e with the tag and one object which transitioned unexpectedly, i.e without the tag.

**Comment by harshavardhana** [comment]
Closing the issue as stale and that this is working as expected.
