### ISSUE TITLE
Typo on debugging page

### ISSUE THREAD

**Issue by EugenKon** [minio/minio#18169]
https://github.com/minio/minio/tree/master/docs/debugging

>Default trace is succinct only to indicate the API operations being called and the HTTP response status.

Can not read 'succinct' )

**Comment by ravindk89** [comment]
I think the usage here is [likely intentional](https://www.merriam-webster.com/dictionary/succinct).

That said if you have a better suggestion feel free to edit the documentation and open a PR directly.
