### ISSUE TITLE
More precise object metrics for the prometheus exporter

### ISSUE THREAD

**Issue by AlexanderENTH** [minio/minio#18172]
Hello everyone,
I am building a grafana dashboard using the minio prometheus exporter to monitor our minio instances. Among other requirements I need to cover the following:

**Is your feature request related to a problem? Please describe.**
I need a metric that tracks the last modified dateTime (or seconds) of an object, per bucket. I need this because of monitoring reasons: Sending an alert every time an object of that name has not been uploaded-again / modified in the past x hours.

**Describe the solution you'd like**
Having a metric scraping the name, creation date and last-modified date of objects per bucket per minio instance.

**Describe alternatives you've considered**
I have read the entire documentation and could not find a metric that suits my use-case.

With kind regards,
Alex

**Comment by klauspost** [comment]
We do not plan to add this, and are unlikely to.

Use [bucket notifications](https://min.io/docs/minio/kubernetes/upstream/administration/monitoring.html) or [audit logs](https://min.io/docs/minio/kubernetes/upstream/operations/monitoring/minio-logging.html#minio-logging) and derive the data you need from that.
