### ISSUE TITLE
Support inventory report

### ISSUE THREAD

**Issue by xiaofan-luan** [minio/minio#18179]
**Is your feature request related to a problem? Please describe.**

W've seen many obj storage implement inventory features, here is some list:

S3 https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory-location.html
gcs https://cloud.google.com/storage/docs/insights/inventory-reports
oss https://help.aliyun.com/zh/oss/developer-reference/inventory

With the inventory feature, application can cleanup orphan garbage without list the entire prefix.

**Describe the solution you'd like**

Support inventory feature, follow the format of AWS S3 to generate file list.

**Describe alternatives you've considered**

Better list speed?

**Additional context**

**Comment by xiaofan-luan** [comment]
the inventory feature is important to our application since we've hit very slow list with million small objects

**Comment by harshavardhana** [comment]
@xiaofan-luan for performance related help please reach out to us via hello@min.io

**Comment by harshavardhana** [comment]
Inventory feature will be implemented as part of the MinIO Catalog product stream.

An upcoming of GA of this product will happen in Q1 of this year.

Closing this issue since we are not going to duplicate the effort inside MinIO.

**Comment by xiaofan-luan** [comment]
> MinIO Catalog product

Will this be part of opensource minio? How is this goind on?

**Comment by klauspost** [comment]
https://min.io/product/enterprise/object-store-catalog

> Will this be part of opensource minio? 

It is part of the Enterprise suite.

**Comment by yarikoptic** [comment]
in our case we thought of minio as a possible S3 implementation to test inventory based tool against: https://github.com/dandi/s3invsync .  Is there some "freeware" or limited enterprise suite version to potentially somehow use on CIs?

**Comment by marktheunissen** [comment]
Hi @yarikoptic no, we don't have any freeware version of Catalog.
