### ISSUE TITLE
Cannot be transition data to the target Tiering

### ISSUE THREAD

**Issue by rensongqi** [minio/minio#18176]
## NOTE
Hi, Due to insufficient disk space used by minio, data needs to be migrated to the target Tier. I have configured Lifecycle for the bucket using `minio-go/v7`, set the data to transition to the target tier after 1 day, and currently after 7 days the data has not transitioned to the target tier.   How do I check the current minio transition logs?

![image](https://github.com/minio/minio/assets/49969527/3c55617e-2848-4e1d-bc93-db623342794e)

![image](https://github.com/minio/minio/assets/49969527/fdbcedf5-055e-4908-8b76-4aba4d97fc90)

## Expected Behavior
Target tier should have data

## Current Behavior
No data available for target tier
![image](https://github.com/minio/minio/assets/49969527/5118a711-ae8c-4bcc-aaab-c5edf4adefd4)
## Possible Solution
Caused by too much data?

## Steps to Reproduce (for bugs)
1. Configure bucket lifecycle with `minio-go/v7` 
2. Lifecycle configuration 1 day after being transitioned to the target Tier
3. Waiting 7 days for the target Tier and still no data to be transitioned

## Your Environment
![image](https://github.com/minio/minio/assets/49969527/7706a327-76e4-4270-8064-4ed72d365b88)

Current minio version: 
```bash
minio version RELEASE.2022-08-25T07-17-05Z (commit-id=18dffb26e7aba09074704d169517285ac3870e86)
Runtime: go1.18.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```
Target minio tier version:
```bash
minio version RELEASE.2023-09-23T03-47-50Z (commit-id=22041bbcc469f5ac84207d09b4c4db326ec5fd57)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

Minio services deployed using docker
- Docker version: 22.06.0-beta.0

**Comment by harshavardhana** [comment]
You need to upgrade your source MinIO version @rensongqi.

Tiering is not meant for conserving space on the source, that is not the real goal. You are using it for wrong reasons.

You need to make sure your source cluster is writable and has enough space to hold hot content as well as the metadata needed to tier the content.

Just look at the server logs on the source.
