### ISSUE TITLE
Unable to read environment variables

### ISSUE THREAD

**Issue by MomentQYC** [minio/minio#18181]
## Expected Behavior

Read the username and password from the environment variable set in the file and it works.

## Current Behavior

The username and password set by the environment variable file cannot be used when running with systemd.

## Steps to Reproduce (for bugs)

1. Setting up a brand new instance of Minio
2. Without changing the service file, the environment variable files are as follows
```
MINIO_VOLUMES="/mnt/minio-data/data"

MINIO_OPTS="--console-address :9011"

MINIO_ROOT_USER=USERNAME

MINIO_ROOT_PASSWORD=P@Ssw0rD (Upper and lower case letters, numbers, and special symbols are included.)

MINIO_SITE_REGION="global-test"

MINIO_SERVER_URL="https://example.com"
```
3. run `systemctl start minio`

## Context

I tried to reproduce this scenario manually, then I realized that after I source the environment variable file, minio still doesn't work correctly with the username and password environment variables readable. But after exporting the relevant variables, it's fine.

## Regression

IDK

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-09-30T07-02-29Z (commit-id=22d2dbc4e68a20ada8c82edf1cc68026e7b0e3d6)`
* Server setup and configuration: provided
* Operating System and version (`uname -a`): `5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jiuker** [comment]
Could you try with 
```service
MINIO_ROOT_USER="USERNAME"

MINIO_ROOT_PASSWORD="P@Ssw0rD"
```
@MomentQYC

**Comment by MomentQYC** [comment]
> Could you try with
> 
> ```desktop
> MINIO_ROOT_USER="USERNAME"
> 
> MINIO_ROOT_PASSWORD="P@Ssw0rD"
> ```

Still not working

**Comment by jiuker** [comment]
> > Could you try with
> > ```desktop
> > MINIO_ROOT_USER="USERNAME"
> > 
> > MINIO_ROOT_PASSWORD="P@Ssw0rD"
> > ```
> 
> Still not working

How about 
```service
MINIO_ROOT_USER="USERNAME"

MINIO_ROOT_PASSWORD="PSsw0rD"
```
@MomentQYC

**Comment by MomentQYC** [comment]
> > > Could you try with
> > > ```desktop
> > > MINIO_ROOT_USER="USERNAME"
> > > 
> > > MINIO_ROOT_PASSWORD="P@Ssw0rD"
> > > ```
> > 
> > 
> > Still not working
> 
> How about
> 
> ```desktop
> MINIO_ROOT_USER="USERNAME"
> 
> MINIO_ROOT_PASSWORD="PSsw0rD"
> ```
> 

Still not working

**Comment by jiuker** [comment]
Could you share the minio log?

**Comment by MomentQYC** [comment]
> Could you share the minio log?

Where? If it's in `journald` it's only the output at startup, nothing extra.

**Comment by jiuker** [comment]
> > Could you share the minio log?
> 
> Where? If it's in `journald` it's only the output at startup, nothing extra.

Yes. Share it

**Comment by MomentQYC** [comment]
> > > Could you share the minio log?
> > 
> > 
> > Where? If it's in `journald` it's only the output at startup, nothing extra.
> 
> Yes. Share it

```
minio[32202]: MinIO Object Storage Server
minio[32202]: Copyright: 2015-2023 MinIO, Inc.
minio[32202]: License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio[32202]: Version: RELEASE.2023-09-30T07-02-29Z (go1.21.1 linux/amd64)
minio[32202]: Status:         1 Online, 0 Offline.
minio[32202]: S3-API: https://example.com
minio[32202]: Console: http://(IP):9011 http://(IP):9011 http://127.0.0.1:9011
minio[32202]: Documentation: https://min.io/docs/minio/linux/index.html
minio[32202]: Warning: The standard parity is set to 0. This can lead to data loss
```
That's all

**Comment by harshavardhana** [comment]
> > > > Could you share the minio log?
> > > 
> > > 
> > > Where? If it's in `journald` it's only the output at startup, nothing extra.
> > 
> > 
> > Yes. Share it
> 
> ```
> minio[32202]: MinIO Object Storage Server
> minio[32202]: Copyright: 2015-2023 MinIO, Inc.
> minio[32202]: License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> minio[32202]: Version: RELEASE.2023-09-30T07-02-29Z (go1.21.1 linux/amd64)
> minio[32202]: Status:         1 Online, 0 Offline.
> minio[32202]: S3-API: https://example.com
> minio[32202]: Console: http://(IP):9011 http://(IP):9011 http://127.0.0.1:9011
> minio[32202]: Documentation: https://min.io/docs/minio/linux/index.html
> minio[32202]: Warning: The standard parity is set to 0. This can lead to data loss
> ```
> 
> That's all

It seems to have worked what is not workinh here ?

**Comment by harshavardhana** [comment]
We do not print your root credentials in the systemd logs if that's what you are looking for.

**Comment by MomentQYC** [comment]
> > > > > Could you share the minio log?
> > > > 
> > > > 
> > > > Where? If it's in  it's only the output at startup, nothing extra.`journald`
> > > 
> > > 
> > > Yes. Share it
> > 
> > 
> > ```
> > minio[32202]: MinIO Object Storage Server
> > minio[32202]: Copyright: 2015-2023 MinIO, Inc.
> > minio[32202]: License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> > minio[32202]: Version: RELEASE.2023-09-30T07-02-29Z (go1.21.1 linux/amd64)
> > minio[32202]: Status:         1 Online, 0 Offline.
> > minio[32202]: S3-API: https://example.com
> > minio[32202]: Console: http://(IP):9011 http://(IP):9011 http://127.0.0.1:9011
> > minio[32202]: Documentation: https://min.io/docs/minio/linux/index.html
> > minio[32202]: Warning: The standard parity is set to 0. This can lead to data loss
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's all
> 
> It seems to have worked what is not workinh here ?

Doesn't work, I get an error EOF when I log in with this credentials

**Comment by harshavardhana** [comment]
What EOF error? You have share all the errors that you see.

**Comment by MomentQYC** [comment]
> What EOF error? You have share all the errors that you see.

![image](https://github.com/minio/minio/assets/62551256/5649b688-8bc4-4619-8f3c-d9cb08dbb5df)

**Comment by MomentQYC** [comment]
> > What EOF error? You have share all the errors that you see.
> 
> ![image](https://user-images.githubusercontent.com/62551256/273393909-5649b688-8bc4-4619-8f3c-d9cb08dbb5df.png)

To add to that, the real password have more than 100 digits, with special symbols

**Comment by jiuker** [comment]
Could you share the webpage debug (Chrome use F12) to show what's the request and what's the response? @MomentQYC

**Comment by harshavardhana** [comment]
This EOF error is related to wrong server URL configuration.

> MINIO_SERVER_URL="https://example.com"

You can't use randomly some public domain, you need to use what is the domain for your instance that is accessible from your laptop.

These are all wrong configurations, you simply copy pasted without knowing what these values are.

They are documented to tell you what they are meant to be, please read them. If you don't know why you set this env, just remove it and systemctl restart minio

**Comment by MomentQYC** [comment]
> This EOF error is related to wrong server URL configuration.
> 
> > MINIO_SERVER_URL="https://example.com"
> 
> You can't use randomly some public domain, you need to use what is the domain for your instance that is accessible from your laptop.
> 
> These are all wrong configurations, you simply copy pasted without knowing what these values are.
> 
> They are documented to tell you what they are meant to be, please read them. If you don't know why you set this env, just remove it and systemctl restart minio

@jiuker @harshavardhana 
Thank you. It's solved.
