### ISSUE TITLE
Event notification message missing

### ISSUE THREAD

**Issue by rock1013** [minio/minio#18180]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Our developer report me that some event notification is missing while we have mcli-traced Put request to a log file.
Further we made two notifications path for the same Put event. One is mysql the other is rabbitMQ.
Cases shows that for the same object we put into minio event notification occassionally miss for both paths.
## Expected Behavior
Each event notification should be sent.

## Current Behavior

Event notification occassionally is missing.

## Steps to Reproduce (for bugs)

It's hard for reproduce. But i can share the case.
1. nohup mcli admin trace yxuer --path homework.1school.com.cn/* --method PUT >/home/yxuer/minilog/abc.log &
2. some event missing
3. cat abc.log | grep XXX.JPG to see the put event
![image](https://github.com/minio/minio/assets/13289772/16e09dbf-1670-453f-b6c9-244521b590b8)

## Context

We use event to save duplicated copy from client to server. But now failed.

Client upload a pic. Then java application notice this event and sync the pic to cloud for cdn or internet download.
## Regression
 no

## Your Environment

* Version used (`minio --version`):minio version  
RELEASE.2023-09-30T07-02-29Z (commit-id=22d2dbc4e68a20ada8c82edf1cc68026e7b0e3d6)
Runtime: go1.21.1 linux/amd64
* Server setup and configuration:
MINIO_VOLUMES="http://minio{1...4}.yxuer.com:9000/mnt/disk{1...8}/minio"

MINIO_OPTS="--address :9000 --console-address :9001"

MINIO_ROOT_USER**
MINIO_ROOT_PASSWORD**

MINIO_SERVER_URL=https://minio.yxuer.com
MINIO_BROWSER_REDIRECT_URL=https://minioweb.yxuer.com

MINIO_CONFIG_ENV_FILE=/etc/default/minio
MINIO_PROMETHEUS_AUTH_TYPE=public
MINIO_PROMETHEUS_URL=https://prometheus.yxuer.com/
MINIO_PROMETHEUS_JOB_ID=minio
MINIO_HEAL_MAX_SLEEP=300ms
MINIO_HEAL_MAX_IO=30
MINIO_SCANNER_SPEED=slow

yxuer@server101:~/minilog$ mcli admin config get yxuer notify_mysql
notify_mysql enable=off format=namespace dsn_string= table= queue_dir= queue_limit=0 max_open_connections=2
notify_mysql:mysql-minio format=namespace dsn_string= ***:**@tcp(192.168.3.100:6446)/minio table=minioevent queue_dir= queue_limit=0 max_open_connections=2
notify_amqp:sync-qiniu url=amqp://**@192.168.3.25:5672/yxuer_host exchange=s3_yxuer_minio exchange_type=fanout routing_key= mandatory=on durable=off no_wait=off internal=off auto_deleted=off delivery_mode=2 publisher_confirms=off queue_limit=1000000 queue_dir=/home/minio-user/minioevent
* Operating System and version (`uname -a`):
Linux server101 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Thank you for help.

**Comment by rock1013** [comment]
Yesterday, we made triple paths, webhook mysql amqp. It's interesting that when I found a missing event, in all three paths will not found that message.I'm trying to use mcli watch to see if there will be a log entry.

**Comment by harshavardhana** [comment]
> Yesterday, we made triple paths, webhook mysql amqp. It's interesting that when I found a missing event, in all three paths will not found that message.I'm trying to use mcli watch to see if there will be a log entry.

did you see the event in `mc watch` ?

**Comment by harshavardhana** [comment]
can you share your server logs as well?

**Comment by rock1013** [comment]
@harshavardhana  Thanks for help. Not yet. We just open that watcher. 
[miniol.log](https://github.com/minio/minio/files/12840191/miniol.log)
Here is these two days' journal log with cmd ` journalctl -u minio --since "2023-10-07"`.

**Comment by harshavardhana** [comment]
Here it looks some configuration issue

>  Oct 08 14:13:00 server104 minio[3294]: Error: Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 's3_yxuer_minio' in vhost 'test_host': received 'false' but current is 'true'" (*amqp091.Error)

**Comment by rock1013** [comment]
That amqp is a test one. I've removed this now. Today is lucky day with no report missing. We will continue watching.

**Comment by harshavardhana** [comment]
> That amqp is a test one. I've removed this now. Today is lucky day with no report missing. We will continue watching.

Can you precisely tell what concurrency you see it? Or is it purely random?

**Comment by harshavardhana** [comment]
> That amqp is a test one. I've removed this now. Today is lucky day with no report missing. We will continue watching.

Going to close this issue for now, please report when you have a concrete reproducer and more precise numbers that will help us reproduce it as well. 

Thanks

**Comment by rock1013** [comment]
Hi,@harshavardhana Sorry for no reply. This problem still exists.We config minio in async way sending notification. It seems the sending go routine doesn't work.By the way, the mc-watcher has logged the event of this put;
![image](https://github.com/minio/minio/assets/13289772/4150ed16-9d73-4492-912f-260c85efeb59)
Further, today we receive a list about 1000 picture events missing of yesterday.

**Comment by kirill-k2** [comment]
I can confirm this bug. We have geocluster with 3x2 servers.

It is 100% reproducible after combination of:
1. Remove redundant servers from cluster (shut down one site with 2 servers in our case)
2. Apply any configuration change (events handling for example)
3. Push more than 5 files at one go.
4. Check notification - 1 to 3 files are missing in notification but present in bucket. 
5. Restart whole minio cluster - problem solved

We have tested it on Kafka and Postgres event destinations. No difference.

**Comment by harshavardhana** [comment]
Please use queue_dir to ensure guaranteed delivery; delivery cannot be guaranteed otherwise.
