### ISSUE TITLE
Error while trying to edit MinIO Configuration in the latest version

### ISSUE THREAD

**Issue by E4SdJG528X9FsnpaBz6yxw** [minio/minio#18191]
## NOTE

I try to run minio in Docker using [minio/minio:latest](https://hub.docker.com/layers/minio/minio/latest/images/sha256-26ee726fbc72946b1acd73f74acc9396071c5baaa69e95c0771560799ffcd49f?context=explore), and when I try to edit _Configuration -> Region -> Server location_ it shows me this error message:

> Configuration update failed because server quorum was not met (Storage resources are insufficient for the write operation .minio.sys/config/config.json)

And in Docker's logs it shows this:
```
API: SYSTEM()
Time: 12:57:42 UTC 10/09/2023
DeploymentID: 975aedae-a8b6-43e4-99f0-6f73d56879a7
Error: write /data/minio/.minio.sys/tmp/60b4d744-0415-43ce-bf99-152d0622a5dc/xl.meta: invalid argument (*fs.PathError)
       5: internal/logger/logger.go:258:logger.LogIf()
       4: cmd/storage-errors.go:168:cmd.osErrToFileErr()
       3: cmd/xl-storage.go:2515:cmd.(*xlStorage).RenameData()
       2: cmd/xl-storage-disk-id-check.go:440:cmd.(*xlStorageDiskIDCheck).RenameData.func1()
       1: internal/ioutil/ioutil.go:158:ioutil.(*DeadlineWorker).Run.func1()
```

I tried to restart it, but it didn't work. Corrupted `data/minio/minio/.minio.sys/config/config.json/xl.meta` inside the volume, and then undid it back - the error in the logs changed to: 

```
API: SetConfigKV()
Time: 13:02:29 UTC 10/09/2023
DeploymentID: 975aedae-a8b6-43e4-99f0-6f73d56879a7
RequestID: 178C720A8A04BDF8
RemoteHost: 172.25.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (linux; amd64) madmin-go/2.0.0
Error: Drive /data/minio, path (.minio.sys/config/config.json) returned an error (msgp: attempted to decode type "int" with method for "bin") (*fmt.wrapError)
      13: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
      12: internal/logger/logonce.go:149:logger.LogOnceIf()
      11: cmd/erasure-object.go:601:cmd.readAllXL()
      10: cmd/erasure-object.go:674:cmd.erasureObjects.getObjectFileInfo()
       9: cmd/erasure-object.go:231:cmd.erasureObjects.GetObjectNInfo()
       8: cmd/erasure-sets.go:748:cmd.(*erasureSets).GetObjectNInfo()
       7: cmd/erasure-server-pool.go:795:cmd.(*erasureServerPools).GetObjectNInfo()
       6: cmd/config-common.go:33:cmd.readConfigWithMetadata()
       5: cmd/config-common.go:54:cmd.readConfig()
       4: cmd/config.go:156:cmd.readServerConfig()
       3: cmd/admin-handlers-config-kv.go:195:cmd.setConfigKV()
       2: cmd/admin-handlers-config-kv.go:171:cmd.adminAPIHandlers.SetConfigKVHandler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
API: SetConfigKV()
Time: 13:02:29 UTC 10/09/2023
DeploymentID: 975aedae-a8b6-43e4-99f0-6f73d56879a7
RequestID: 178C720A8A04BDF8
RemoteHost: 172.25.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (linux; amd64) madmin-go/2.0.0
Error: msgp: attempted to decode type "int" with method for "bin" (msgp.TypeError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/api-errors.go:2350:cmd.toAPIErrorCode()
       4: cmd/admin-handler-utils.go:232:cmd.toAdminAPIErrCode()
       3: cmd/admin-handler-utils.go:220:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-config-kv.go:177:cmd.adminAPIHandlers.SetConfigKVHandler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
I then specified minio/minio version to [RELEASE.2023-09-30T07-02-29Z](https://hub.docker.com/layers/minio/minio/RELEASE.2023-09-30T07-02-29Z/images/sha256-87f83e5e223d51416cd47642eb7ccea4bd884581a07e74b958c74e921028b8fd?context=explore) in the docker-compose and it worked **as expected**.

## Steps to Reproduce (for bugs)
1. Run minio/minio:latest in Docker
2. Open http representation Panel. 
3. Try changing some configuration (for example Region).

## Your Environment
* Version used (`minio --version`):
```
minio version RELEASE.2023-10-07T15-07-38Z (commit-id=c27d0583d4d496981140eff822e2abb34a6f0b60)
Runtime: go1.21.1 linux/amd64
```
* Server setup and configuration (docker-compose piece): 

```yaml
version: '2.4'
services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '8900:8900'
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER="username"
      - MINIO_ROOT_PASSWORD="password"
    volumes:
      - ./data/minio:/data
    networks:
      - my_network
    command: minio server /data/minio --console-address ":8900"
```

* Operating System and version (`uname -a`):
`Linux X23092702 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is mostly related to the O_DIRECT change

**Comment by donatello** [comment]
I tested this a new deployment (no existing data), and didnt see this issue when trying with either the binary or the docker image. Will try with some existing data created by an older version.

**Comment by harshavardhana** [comment]
@donatello the error is returned at WriteAll() which is doing O_DIRECT but here the user's folder doesn't support O_DIRECT. 

```
	        if err = s.WriteAll(ctx, srcVolume, pathJoin(srcPath, xlStorageFormatFile), dstBuf); err != nil {
                        if legacyPreserved {
				// Any failed rename calls un-roll previous transaction.                                                                                                 
                                s.deleteFile(dstVolumeDir, legacyDataPath, true, false)
                        }
                        return 0, osErrToFileErr(err)
                }
```

**Comment by donatello** [comment]
I don't see any issue with an existing modified configuration created with version RELEASE.2023-09-30T07-02-29Z and running the newer version on the same drive.

@harshavardhana Taking a look at that

@olexoliinyk0 How did you "undo" the corruption here?

**Comment by harshavardhana** [comment]
> Error: write /data/minio/.minio.sys/tmp/60b4d744-0415-43ce-bf99-152d0622a5dc/xl.meta: invalid argument (*fs.PathError)

This is returned with O_DIRECT @donatello which generally says that disk FS doesn't support O_DIRECT. 

This generally happens if you are using overlayfs which doesn't support O_DIRECT

**Comment by E4SdJG528X9FsnpaBz6yxw** [comment]
> How did you "undo" the corruption here?

@donatello the project was empty, so I tried renaming my `data/minio` folder so it created it anew. 

When that didn't work, I tried to edit `data/minio/minio/.minio.sys/config/config.json/xl.meta` file using editor, removed all non-json characters from there, got "corrupted" error, cmd+z it back and it showed another error I mentioned above (not right away thought). 

Thanks for the response! Hope your fix will solve the issue, will be glad to test it when the Release is published to DockerHub.

**Comment by harshavardhana** [comment]
> When that didn't work, I tried to edit `data/minio/minio/.minio.sys/config/config.json/xl.meta` file using editor, removed all non-json characters from there, got "corrupted" error, cmd+z it back and it showed another error I mentioned above (not right away thought).

You cannot do that @olexoliinyk0 xl.meta is a msgp file so you can't manually edit it.

**Comment by E4SdJG528X9FsnpaBz6yxw** [comment]
I confirm that using the two last releases (with 18194 pr included) the config change problem and all the strange log errors are gone. Thanks!
