### ISSUE TITLE
Unable to download files larger than 1.5 MB

### ISSUE THREAD

**Issue by JRial95** [minio/minio#18192]
## NOTE
I can't download files larger than 1.5 MB, even though I can upload them. The clients that I used are the Python library (minio & boto3) and the MinIO Console.

## Expected Behavior
It's possible to download larger than 1.5 MB without any problem.

## Current Behavior
The server returns the following error:
```
503 SlowDown Resource requested is unreadable, please reduce your request rate
```

The MinIO Console shows this error in the browser's console:
```
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
```

Finally, the server logs indicate:
```
{"deploymentid":"3f14ac17-4563-411a-a802-0c0eedb982fa","level":"ERROR","errKind":"ALL","time":"2023-10-09T14:29:06.383037719Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logger.go:259:logger.LogIf()","cmd/bitrot-streaming.go:156:cmd.(*streamingBitrotReader).ReadAt()","cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()"]}}
```

## Steps to Reproduce (for bugs)
1. Upload a file larger than 1.5 MB.
2. Try to download this file.

## Context
I try to store and retrieve artifacts using MLflow with MinIO as the storage backend.

## Regression
Probably not.

## Your Environment
* Version used: RELEASE.2022-08-26T19-53-15Z (go1.18.5 linux/amd64)
* Server setup and configuration: MinIO Tenant Helm Chart with default values (version: 5.0.6)
* Operating System and version:
  * Orchestrator: Kubernetes v1.23.9+rke2r1
  * Host OS: Ubuntu 20.04.5 LTS (Linux k8s-node1 5.4.0-156-generic <span>#</span>173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by ravindk89** [comment]
> RELEASE.2022-08-26T19-53-15Z (go1.18.5 linux/amd64)

The first step is to upgrade to the latest stable release. This release is more than 1 year out of date at this point.

Please do that first, and let us know if the issue persists.
