### ISSUE TITLE
Disk expansion issue with MinIO deployed on AWS EKS using Helm

### ISSUE THREAD

**Issue by vb3328998** [minio/minio#18201]
Expected Behavior
After expanding the PVC size, MinIO should be able to recognize the additional storage without any issues.

Current Behavior
Even after increasing the PVC size, MinIO still reports a "drive full" error.

Possible Solution
Seeking guidance on the correct procedure to expand storage for MinIO on EKS with ext4 filesystem type.

Steps to Reproduce
Deploy MinIO on AWS EKS using Helm.
Use a PVC backed by an EBS volume with ext4 filesystem.
Fill up the storage to near capacity.
Increase the PVC size.
Observe that even though the underlying EBS volume and ext4 filesystem reflect the increased size, MinIO still reports a "drive full" error.
Context
I'm trying to ensure that my MinIO deployment on EKS can be seamlessly scaled in terms of storage when required. The current behavior poses a challenge to storage scalability.

Regression
No.

Your Environment
Version used: 2022.12.12-debian-11-r0
Server setup and configuration: MinIO deployed on AWS EKS using Helm. PVCs backed by EBS volumes with ext4 filesystem.
Operating System and version: Linux itnio-minio-0 5.10.178-162.673.amzn2.x86_64 #1 SMP Mon Apr 24 23:34:06 UTC 2023 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Deployment using vanilla helm chart is self support only.

We recommend that you use our operator for a more idiomatic experience.

ext4 has many per directory limitations, you should be using XFS by default again another thing you didn't read from our documentation.

> Version used: 2022.12.12-debian-11-r0

And other things that are non MinIO, not using our officially published containers.

**Comment by vb3328998** [comment]
ok thanks,i'll change it
