### ISSUE TITLE
OIDC user can't see the bucket created by themself

### ISSUE THREAD

**Issue by ghost** [minio/minio#18202]
## Expected Behavior
OIDC user creates a bucket then the new bucket will show in the "Object Browsers"

## Current Behavior
OIDC user created the bucket and can't see it

## Steps to Reproduce (for bugs)

1. add policy and binding it to OIDC user
``` json
{{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::ub-${jwt:name}/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::pub-*",
                "arn:aws:s3:::quilt-*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

2. login the Minio webpage via OIDC and add a  bucket named 'test001'

## Context
Users should own the buckets created by themself. otherwise, we need to add a policy statement when the bucket is created

## Your Environment

* Version used (`minio --version`): RELEASE.2023-09-04T19-57-37Z (go1.19.12 X:boringcrypto linux/amd64)
* Server setup and configuration: 
    ```
      - MINIO_IDENTITY_OPENID_ENABLE=on
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=Login
      - MINIO_IDENTITY_OPENID_CONFIG_URL=https://localhost:8000/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=11136b11a7e9df7b2d11
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=11166ad1124d56311edcfe5680cc5f63b6d68511
      - MINIO_IDENTITY_OPENID_REDIRECT_URI=http://localhost:9001/oauth_callback
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=tag
    ```
* Operating System and version (`uname -a`): Linux jump2cn 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Users should own the buckets created by themself. otherwise, we need to add a policy statement when the bucket is created

There is no ownership of buckets created by you as an account.

Your incoming account is ephemeral to MinIO, you need to tell exactly what you are going to create and allowed access for.

If you filter them out in your policy, then it is not possible to list.

Make sure your policy has the right details for the users. Also users must not be allowed to create buckets themselves.

A site maintainer, devops is the owner of the bucket. Users should be allowed read and write access to a specific set of buckets. 

Think of buckets like filesystem volumes, you wouldn't be allowing users to create their own volumes and home directories.

Bucket is the resource that must be managed directly by you and users would get access via policies - is the idiomatic approach.

**Comment by link89** [comment]
@harshavardhana Is there any document about the best practices of setting policies for users login via OAuth? I hope that user should be allowed to have a dedicated bucket or prefix under a specific bucket to store their own data.

**Comment by harshavardhana** [comment]
> @harshavardhana Is there any document about the best practices of setting policies for users login via OAuth? I hope that user should be allowed to have a dedicated bucket or prefix under a specific bucket to store their own data.

That is simply governed by policy, you provide the list of resources they have access to.

You can give entire bucket, multiple buckets, conditionally different buckets at different folders.
