### ISSUE TITLE
internal events queue unexpectedly full

### ISSUE THREAD

**Issue by ClementGautier** [minio/minio#18215]
## Disclaimer
This issue is only applicable to a very old version of the code and only relevant to the `gateway` mode which is not supported anymore. I'm not looking for a "proper" fix because it can't exists in the current context. I'm creating this issue for reference for other people that might stumble upon this bug.

## Context
We upgraded our minio to the latest version we could use given the fact that we are stuck to an old version because we use the gateway mode. We upgraded from `minio/minio:RELEASE.2021-02-14T04-01-33Z` to `minio/minio:RELEASE.2022-10-24T18-35-07Z` and we suddenly got a lot of these `internal events queue unexpectedly full` logs.

 ## Expected Behavior
Given
https://github.com/minio/minio/blob/fc6c7949727ec261cd57fbdb02fa7575d0fd8e61/cmd/event-notification.go#L329
I expected that sendEvent would not send notification in gateway mode but given the stack trace it appears `globalNotificationSys` is not `nil`.

 ## Current Behavior
```
API: SYSTEM()
Time: 14:59:59 UTC 09/05/2023
Error: internal events queue unexpectedly full (*errors.errorString)
1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
2: minio/cmd/object-handlers.go:1982:cmd.objectAPIHandlers.PutObjectHandler()
3: minio/cmd/event-notification.go:337:cmd.sendEvent()
4: minio/cmd/event-notification.go:222:cmd.(*EventNotifier).Send()
5: minio/internal/logger/logger.go:259:logger.LogIf()
```

## Possible Solution
Maybe it have to do with the way the notification system is initialized, I see the code changed from
https://github.com/minio/minio/blob/c4e12dc846ca04c03cab9de69c828b1351631cfc/cmd/notification.go#L1288-L1300
to 
https://github.com/minio/minio/blob/fc6c7949727ec261cd57fbdb02fa7575d0fd8e61/cmd/notification.go#L1015-L1023

Is there a way to disable the notification system as we don't use it? Or a way to know why we have so much notification target?

## Steps to Reproduce (for bugs)
Deploy minio in gateway mode. Register a lot of objects inside and stress it a little.

## Regression
Yes, we didn't see this issue when we used version `minio/minio:RELEASE.2021-02-14T04-01-33Z`

## Your Environment
* Kubernetes 1.22
* Deprecated Helm chart version `8.0.14`
* Minio `minio/minio:RELEASE.2022-10-24T18-35-07Z`

**Comment by klauspost** [comment]
Obviously we do not support this, so there is nothing actionable here.

I will convert this to a discussion in case anyone from the community has an answer for you.
