### ISSUE TITLE
XL: Tests:  Tests for validating namespace lock implementation. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1821]
This is really important, we need to validate to make sure that we clearly understand the possibilities under which deadlocks can arise, and generate wide range of cases for the tests. The implementation is in `namespace-lock.go` .

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by balamurugana** [comment]
To be fixed: 11-Jun-2016
