### ISSUE TITLE
Large uploads intermittently fail with NoSuchUpload or InvalidPart

### ISSUE THREAD

**Issue by sparkblaze** [minio/minio#18212]
Rubrik appliance and the `mc` client both intermittently throw either a `NoSuchUpload` or `InvalidPart` error while transferring large >1TB backup files

## Expected Behavior
The files to be uploaded successfully

## Current Behavior
File uploads fail, usually at the `CompleteMultiPartUpload` phase - ie: after it's uploaded everything

## Steps to Reproduce (for bugs)

1. Upload a large file
2. Repeat as necessary until a request fails 

```
mc.exe: <ERROR> Failed to copy `\\internal.domain\shares\SQL-Backups\CLRTY-T1-DB02\MSSQLSERVER\CONVAL\CONVAL_20231009_1300.bak`. One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
```

```
mc admin trace --errors --verbose minio
400 Bad Request
Accept-Ranges: bytes
Content-Length: 493
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Amz-Request-Id: 178D066D80A78A57
Vary: Origin,Accept-Encoding
X-Amz-Id-2: 3cce38ac773542111b4fb2ea67f22158f9d2423420173ab964feaf244bd25f02
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part&#39;s entity tag.</Message><Key>CONVAL_20231009_1300.bak</Key><BucketName>test</BucketName><Resource>/test/CONVAL_20231009_1300.bak</Resource><RequestId>178D066D80A78A57</RequestId><HostId>3cce38ac773542111b4fb2ea67f22158f9d2423420173ab964feaf244bd25f02</HostId></Error>
```

## Context
Some large files are not included in Rubrik backups stored in an on-premise minio cluster.

## Regression
Possibly? It was an issue we had with a late 2022/early 2023 version, it went away with the `2023-05-27T05:56:19Z` release and has returned since upgrading to `2023-09-23T03:47:50Z`

## Your Environment

* Version used : `RELEASE.2023-09-23T03-47-50Z (commit-id=22041bbcc469f5ac84207d09b4c4db326ec5fd57)`
* Operating System and version (`uname -a`): **CentOS Stream 9** - `5.14.0-366.el9.x86_64`
* Server setup and configuration: 
* 
2x pools of 4x Dell R740xd2s. 

```
MINIO_OPTS='-C /etc/minio --quiet --json --certs-dir /etc/minio/certs --console-address ":9001"'
MINIO_VOLUMES="https://minio-p3-fs{01...04}.internal.domain/minio/data{01...24} https://minio-p3-fs{05...08}.internal.domain/minio/data{01...24}"
```

**Comment by harshavardhana** [comment]
@sparkblaze can you upload an entire `mc admin trace -v minio` output for the entire run?

**Comment by sparkblaze** [comment]
[trace.txt](https://github.com/minio/minio/files/12880103/trace.txt)

I'd go out on a limb and guess the cause is the 4x 499's that are thrown during the upload

```
minio-p3-fs05:9000 [RESPONSE] [2023-10-12T09:54:52.548] [ Duration 53.23815s TTFB 53.238079749s Ôåæ 16 MiB  Ôåô 384 B ]
minio-p3-fs05:9000 499
```

if it is those, what would be the prevailing advice to improve it?

**Comment by harshavardhana** [comment]
you would have to make sure 

- reduce your client concurrency you are reaching limits on your drives 
- increase client timeout from 50+secs to 120 or 2mins to cater to 
  concurrency and the time it takes to write to your drives

**Comment by sparkblaze** [comment]
Is it possible to change the client timeout for the minio client to see if that improves things? I can't see a flag to change it, but maybe I'm looking in the wrong place

At the time this trace was run, that single file was the only file in transit - besides whatever internal stuff Minio is up to.

**Comment by harshavardhana** [comment]
Can you share the code ?

**Comment by sparkblaze** [comment]
If I had any custom code to share :)

The testing I've been doing above was just using `mc cp <large-file> minio/test`

**Comment by harshavardhana** [comment]
> If I had any custom code to share :)
> 
> The testing I've been doing above was just using `mc cp <large-file> minio/test`

so this looks like you have some load balancer in between that has a timeout set for the response? 

check if you are on nginx and you have a response_timeout set to < 60secs which is default, you need to change that to match your worst case for your hardware.

**Comment by sparkblaze** [comment]
There is a Netscaler MPX that is used for load balancing, for Minio, it's only used with GSLB, so unless I'm misunderstanding, it shouldn't be part of the connection for uploads - it should just be providing a host IP back to the client and nothing else.
 
The timeouts occur even if I just point `mc cp` directly at a single host in the cluster.

**Comment by harshavardhana** [comment]
> The timeouts occur even if I just point `mc cp` directly at a single host in the cluster.

Are you doing `mc cp` via the same host as MinIO or from elsewhere? what is the client upload bandwidth?

**Comment by harshavardhana** [comment]
You can try reducing `MC_UPLOAD_MULTIPART_THREADS=1` while using `mc cp` and see how it handles it.

**Comment by sparkblaze** [comment]
`mc cp` has been running from the same DC as the stuff being backed up. Should be minimum 8GB from clients to minio hosts.

Changing `MC_UPLOAD_MULTIPART_THREADS=1` did not do much different. 

I'm now wondering if I have something mysterious going on between the Minio nodes as I get `dial tcp x.x.x.x i/o timeouts` periodically across all of them (not at the same time, but different nodes talking to different nodes and endpoints `lock`, `peermetrics`, `storage/*` ).

It's peaked my interest a bit more as I've noticed that I can also get booted out of the UI at a similar time as errors

```
Marking minio-p3-fs02:9000 offline temporarily; caused by Post "https://minio-p3-fs02:9000/minio/peer/v33/peermetrics": dial tcp 192.168.202.18:9000: i/o timeout (*fmt.wrapError)
```

**Comment by jiuker** [comment]
@sparkblaze Could you share the minio's log?

**Comment by jiuker** [comment]
@sparkblaze Could you share the minio log?

**Comment by sparkblaze** [comment]
Hi, sorry, which logs are you interested in seeing?

The general ones from an upload with `MC_UPLOAD_MULTIPART_THREADS=1` or one that includes the `dial tcp` stuff?

**Comment by jiuker** [comment]
> Hi, sorry, which logs are you interested in seeing?
> 
> The general ones from an upload with `MC_UPLOAD_MULTIPART_THREADS=1` or one that includes the `dial tcp` stuff?

minio-server

**Comment by sparkblaze** [comment]
From just one server or all of them?

Presumably you're only particularly interested in the window where I get a `NoSuchUpload` or `InvalidPart`?

**Comment by jiuker** [comment]
> From just one server or all of them?
> 
> Presumably you're only particularly interested in the window where I get a `NoSuchUpload` or `InvalidPart`?

Some log will show that. You can reproduce it. And cat the log.

**Comment by sparkblaze** [comment]
[minio.service.logs.txt](https://github.com/minio/minio/files/13618516/minio.service.logs.txt)

I still have the same issue when the actual backup runs, but so far today I haven't been able to replicate it actually failing to copy like before, so I've included the `minio.service` logs for the window where I was testing - the same style of errors are thrown throughout the evening when the backups run as well though.

I'll try and replicate the fault again next week, or maybe see how large the `minio.service` logs are for the backup window.

**Comment by harshavardhana** [comment]
From the logs it can be seen that nodes disconnect and reconnect at random.

I mostly think you just have a flaky setup, not optimal for the workload.

**Comment by jiuker** [comment]
@sparkblaze Are your machine times inconsistent?

**Comment by sparkblaze** [comment]
Yes - they're synced to a local NTP source which appears to be working.

Since updating to `2023-12-09T18:17:51Z` the inter-node issues in `minio.service` are considerably _less_, but I still get the same multipart issues, albeit the files that failed last night were nearer 1TB

**Comment by harshavardhana** [comment]
We have many customers already deploy our MinIO releases over the last few months.

They all have various applications using multipart and a combination of such many APIs.

So it purely looks like a setup issue TBH. Closing this is not actionable and we haven't seen any wider reports on this being a bug.
