### ISSUE TITLE
XL: Tests: Unit and functional tests for xl-v1 healing and metadata implementation. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1822]
Need unit and functional tests for `xl-v1-*` files, which includes healing and metadata implementation.

**Comment by krishnasrinivas** [comment]
deadline - 15th June

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
@hackintoshrao healing will be done after the release, so unit tests for healing will go along with it. What other unit tests have you associated with this issue?

**Comment by hackintoshrao** [comment]
@krishnasrinivas : xl-v1-metadata.go needs tests.

**Comment by krishnasrinivas** [comment]
timeline - 20th for xl-v1-metadata.go unit tests
