### ISSUE TITLE
Is it necessary for Minio to use a 9000 port when using an ETCD cluster

### ISSUE THREAD

**Issue by shangzusheng** [minio/minio#18229]
## Expected Behavior
I am using the Docker environment to deploy mini and cluster with ETCD, but I have modified port 9000 to port 9010. The mini service can run normally and create capacity, but when uploading files inside the bucket, a prompt will appear: Your metadata headers exceeded the maximum allowed metadata size

If I use Minio's default 9000 port, it will work fine

## Current Behavior
This is the command I used during deployment

docker run --net=host --name minio -d --restart=always -e TZ=Asia/Shanghai -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123" -e "MINIO_ETCD_ENDPOINTS=http://10.10.7.25:2379,http://10.10.7.191:2379,http://10.10.7.161:2379" -e "MINIO_PUBLIC_IPS=10.10.7.25" -e "MINIO_DOMAIN=minio1:9010" -v /data/minio/data1:/data1 -v /data/minio/data2:/data2 -v /data/minio/data3:/data3 -v /data/minio/data4:/data4 minio/minio:RELEASE.2022-08-13T21-54-44Z.fips  server --console-address ":9011" -address ":9010" http://minio{1...1}:9010/data{1...4}

## Possible Solution
Do I have to use port 9000? There are still other configuration parameters that can be modified to support port 9010

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

minio:RELEASE.2022-08-13T21-54-44Z.fips

**Comment by jiuker** [comment]
`--address` should be fine to you @shangzusheng

**Comment by shangzusheng** [comment]
> `--address` should be fine to you @shangzusheng

@jiuker Looking at the command I ran above, I have used - address and the port can be successfully modified. The page and API ports can be accessed normally, and creating buckets is also normal, but I cannot upload files
![image](https://github.com/minio/minio/assets/31402698/078a5230-853a-44ae-a56b-7f5c7c1532c9)

**Comment by jiuker** [comment]
Oh. `minio:RELEASE.2022-08-13T21-54-44Z.fips` Can you use the latest version to test it? @shangzusheng

**Comment by shangzusheng** [comment]
> Oh. `minio:RELEASE.2022-08-13T21-54-44Z.fips` Can you use the latest version to test it? @shangzusheng

@jiuker Yes, I have also tried using the latest version of the mirror and deploying a minio service without using Docker. I tried it on Windows and it was the same on-site. It works normally with the default port of 9000, and any other port has the same issue.

**Comment by jiuker** [comment]
> MINIO_DOMAIN

Is that normal running that without etcd? @shangzusheng

**Comment by shangzusheng** [comment]
> > MINIO_DOMAIN
> 
> Is that normal running that without etcd? @shangzusheng

@jiuker  I have also verified that mapping port 9000 to port 9010 without the need for ETCD works properly and allows for normal clustering and file uploading.

**Comment by jiuker** [comment]
I found that. Thanks @shangzusheng
