### ISSUE TITLE
`filename` being incorrectly enforced - MalformedPOSTRequest - The file or text content is missing

### ISSUE THREAD

**Issue by jonbarrow** [minio/minio#18235]
Presigned POST URL is failing to upload multi-part data when `filename` is not present

## Expected Behavior
For the upload to succeed

## Current Behavior
Upload fails with the following error

**EDIT**:

This error is thrown because MinIO is enforcing that `filename` be present during multi-part file uploads. This is not to spec. The spec for multi-part uploads says that `filename` is *not* required https://www.ietf.org/rfc/rfc7578.txt

> For form data that represents the content of a file, a name for the file SHOULD be supplied as well, by using a "filename" parameter of the Content-Disposition header field.  _**The file name isn't mandatory for cases where the file name isn't available or is meaningless or private**_; this might result, for example, when selection or drag-and- drop is used or when the form data content is streamed directly from a device.

In cases like S3, where the "file name" is the same as the objects key in the bucket, "where the file name isn't available or is meaningless" applies

In our specific case, "when the form data content is streamed directly from a device" is what applies to us. Our server provides presigned URLs to a game client, which we do not control, and the console is what makes these upload requests as a way to store user generated content

```xml
<Error>
	<Code>MalformedPOSTRequest</Code>
	<Message>The body of your POST request is not well-formed multipart/form-data. (The file or text content is missing)</Message>
	<BucketName>pn-amaj-d1</BucketName>
	<Resource>/pn-amaj-d1/</Resource>
	<RequestId></RequestId>
	<HostId></HostId>
</Error>
```

## Possible Solution
No longer enforcing `filename` to be present on multi-part uploads, bringing things to spec. My team and I are willing to contribute this ourselves

## Steps to Reproduce (for bugs)
```go
policy := minio.NewPostPolicy()

policy.SetBucket(bucket)
policy.SetKey(key)
policy.SetExpires(time.Now().UTC().Add(lifetime))

URL, formData, err := minioClient.PresignedPostPolicy(context.Background(), policy)
if err != nil {
	panic(err)
}

// POST to the URL with the file named "file", omitting the "filename"
```

## Context
I am working with a client which I do not have control over. The client requests presigned s3 URLs to manage user-generated content. When giving the client a presigned POST URL, the upload fails due to the file name not being found despite it existing. Uploads have worked before in s3 cloud providers, such as DigitalOcean Spaces, just not here

The form upload looks like so (trimmed):

```
POST /pn-amaj-d1/ HTTP/1.1
Host: redacted
Accept: */*
Content-Length: 52655
Content-Type: multipart/form-data; boundary=--------BOUNDARY--------24F4113EF847409A

----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="x-amz-credential"

redacted
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="x-amz-date"

20231012T205831Z
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="x-amz-signature"

redacted
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="bucket"

pn-amaj-d1
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="key"

1.bin
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="policy"

redacted
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="x-amz-algorithm"

AWS4-HMAC-SHA256
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="file"

ASH....rest of file contents
```

The client sends it's file data in the `file` field, which is clearly present

## Regression
Not that I am aware of, first time user of MinIO

## Your Environment

The official MinIO Docker container, `minio/minio`

### Version used (`minio --version`):
```
$ minio --version
minio version RELEASE.2023-10-07T15-07-38Z (commit-id=c27d0583d4d496981140eff822e2abb34a6f0b60)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2023 MinIO, Inc.
```

### Operating System and version (`uname -a`):
```
$ uname -a
Linux 5ae9eaa30855 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
Please share the entire code @jonbarrow not snippets, a working example that I can run `go run post.go`

**Comment by jonbarrow** [comment]
It's difficult to provide *everything* this way since, as I said, our code is not the one make the final request, it's a game client which I have no control over. We only provide the client with a presigned URL and form data, which it then uses to upload the user data it needs to

The code for generating the URLs is taken straight from the docs with minimal changes to fit into our server. This is the most I can give you, as this is all that we do

```go
func main() {
	s3Endpoint := os.Getenv("CONFIG_S3_ENDPOINT")
	s3AccessKey := os.Getenv("CONFIG_S3_ACCESS_KEY")
	s3AccessSecret := os.Getenv("CONFIG_S3_ACCESS_SECRET")
	s3Bucket := os.Getenv("CONFIG_S3_BUCKET")

	staticCredentials := credentials.NewStaticV4(s3AccessKey, s3AccessSecret, "")

	minIOClient, err := minio.New(s3Endpoint, &minio.Options{
		Creds:  staticCredentials,
		Secure: true,
	})

	policy := minio.NewPostPolicy()

	policy.SetBucket(s3Bucket)
	policy.SetKey("1.bin")
	policy.SetExpires(time.Now().UTC().Add(lifetime))

	URL, formData, err := minIOClient.PresignedPostPolicy(context.Background(), policy)
	if err != nil {
		panic(err)
	}

	/*
		At this point the URL and formData are encoded and
		sent to the client that requested them. The client
		is what then makes the request. My original post
		has the full raw HTTP request in it, showing all the
		form fields and their contents (unless trimmed/redacted)
	*/
}
```

**Comment by jiuker** [comment]
@jonbarrow 
```log
AWS4-HMAC-SHA256
----------BOUNDARY--------24F4113EF847409A
Content-Disposition: form-data; name="file"
```
You lose the `filename="YourFileName"` 
You can check out https://github.com/minio/minio/issues/17391#issuecomment-1727198665
You should use
```java
      multipartBuilder.addFormDataPart(
          "file",
          objectName,
          RequestBody.create(readAllBytes(new ContentInputStream(1 * MB)), null));
```
maybe. @balamurugana ^^

**Comment by jonbarrow** [comment]
> You should use

As I have already said, we are not the ones actually making the upload request. We are only providing the presigned URLs to a client that is requesting them. The client making the upload request is not something we control

Other S3 providers such as AWS and Spaces from DigitalOcean work without `filename` present, is there any reason why that is not the case here? Or any way to remedy this? Changing how the client works is not something we can feasibly do

The spec for multipart uploads does say that `filename` is *not* required https://www.ietf.org/rfc/rfc7578.txt

> For form data that represents the content of a file, a name for the file SHOULD be supplied as well, by using a "filename" parameter of the Content-Disposition header field.  _**The file name isn't mandatory for cases where the file name isn't available or is meaningless or private**_; this might result, for example, when selection or drag-and- drop is used or when the form data content is streamed directly from a device.

In cases like S3, where the "file name" is the same as the objects key in the bucket, "where the file name isn't available or is meaningless" applies

In our specific case, "when the form data content is streamed directly from a device" is what applies to us. Our server provides presigned URLs to a game client, which we do not control, and the console is what makes these upload requests as a way to store user generated content

**Comment by balamurugana** [comment]
> @jonbarrow
> 
> ```
> AWS4-HMAC-SHA256
> ----------BOUNDARY--------24F4113EF847409A
> Content-Disposition: form-data; name="file"
> ```
> 
> You lose the `filename="YourFileName"` You can check out [#17391 (comment)](https://github.com/minio/minio/issues/17391#issuecomment-1727198665) You should use
> 
> ```java
>       multipartBuilder.addFormDataPart(
>           "file",
>           objectName,
>           RequestBody.create(readAllBytes(new ContentInputStream(1 * MB)), null));
> ```
> 
> maybe. @balamurugana ^^

We have a [functional test](https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L1716) which gets post policy data and uses it to upload data to an object. Please refer that.

**Comment by jonbarrow** [comment]
> We have a [functional test](https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L1716) which gets post policy data and uses it to upload data to an object. Please refer that.

I'm not sure what is being suggested here, or if this is aimed at me or @jiuker? Assuming this is aimed at me, and assuming you are suggesting we use this test as a reference to make uploads, I reiterate again that we are not the client making the upload requests here. No solution involving changes to how the client uploads data will work, as again we have no control over the client. The role we play is *only* providing a 3rd party client with presigned URLs

The issue here is that MinIO is enforcing that `filename` be required on multi-part file uploads, when this is not to spec. I linked the RFC for multi-part uploads, and quoted the relevant sections, in my previous reply. `filename` is not a required field in all cases, which is why uploads fail here but not other S3 providers like AWS or Spaces

**Comment by balamurugana** [comment]
> > We have a [functional test](https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L1716) which gets post policy data and uses it to upload data to an object. Please refer that.
> 
> I'm not sure what is being suggested here, or if this is aimed at me or @jiuker? Assuming this is aimed at me, and assuming you are suggesting we use this test as a reference to make uploads, I reiterate again that we are not the client making the upload requests here. No solution involving changes to how the client uploads data will work, as again we have no control over the client. The role we play is _only_ providing a 3rd party client with presigned URLs
> 
> The issue here is that MinIO is enforcing that `filename` be required on multi-part file uploads, when this is not to spec. I linked the RFC for multi-part uploads, and quoted the relevant sections, in my previous reply. `filename` is not a required field in all cases, which is why uploads fail here but not other S3 providers like AWS or Spaces

The comment is for @jiuker

**Comment by jonbarrow** [comment]
> The comment is for @jiuker

My apologies then! I interpreted this as you possibly building of their comment, which still addressed me

**Comment by jiuker** [comment]
Don't worry. I will check it. If we have plan for this, it will be fixed as soon as possible.  @jonbarrow

**Comment by jiuker** [comment]
> > You should use
> 
> As I have already said, we are not the ones actually making the upload request. We are only providing the presigned URLs to a client that is requesting them. The client making the upload request is not something we control
> 
> Other S3 providers such as AWS and Spaces from DigitalOcean work without `filename` present, is there any reason why that is not the case here? Or any way to remedy this? Changing how the client works is not something we can feasibly do
> 
> The spec for multipart uploads does say that `filename` is _not_ required https://www.ietf.org/rfc/rfc7578.txt
> 
> > For form data that represents the content of a file, a name for the file SHOULD be supplied as well, by using a "filename" parameter of the Content-Disposition header field.  _**The file name isn't mandatory for cases where the file name isn't available or is meaningless or private**_; this might result, for example, when selection or drag-and- drop is used or when the form data content is streamed directly from a device.
> 
> In cases like S3, where the "file name" is the same as the objects key in the bucket, "where the file name isn't available or is meaningless" applies
> 
> In our specific case, "when the form data content is streamed directly from a device" is what applies to us. Our server provides presigned URLs to a game client, which we do not control, and the console is what makes these upload requests as a way to store user generated content

I just want you to change your upload method. And let @balamurugana  give the right instructions. It is not clear to me that you can't change a customer's upload behaviour. @jonbarrow

**Comment by jiuker** [comment]
@jonbarrow Thanks for your patience, I've submitted the pr to fix this.
