### ISSUE TITLE
XL: Tests: Unit tests for Signature v4 parsing. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1824]
Need tests for `signature-*` files.

**Comment by GarimaKapoor** [comment]
Please put a timeline for the fix

**Comment by krisis** [comment]
We have decided that we would test s3 protocol specifics like response XML, error codes and signature verification in https://github.com/minio/s3verify repo. https://github.com/minio/minio/pull/1863 adds tests for code that may not get sufficient coverage in the `s3verify` repo. We could optionally merge this in the interim.

**Comment by harshavardhana** [comment]
> We have decided that we would test s3 protocol specifics like response XML, error codes and signature verification in https://github.com/minio/s3verify repo. #1863 adds tests for code that may not get sufficient coverage in the s3verify repo. We could optionally merge this in the interim.

We don't need to merge anything in interim, we are fine leveraging s3verify here.. Closing as decided.
