### ISSUE TITLE
No access to public images in buckets with url

### ISSUE THREAD

**Issue by safwanghamrawi** [minio/minio#18251]
## Expected Behavior
Access to images in a public buckets like https://my-minio-storage-console-url.com/bucketname/test.jpg and so I can see the image in the browser

## Current Behavior
Actually I have a 200 Response but empty image
![image](https://github.com/minio/minio/assets/3163835/b5e434b8-255b-4fc7-92ad-42a2095ab571)

## Your Environment

* Version used (`minio version RELEASE.2023-09-30T07-02-29Z (commit-id=22d2dbc4e68a20ada8c82edf1cc68026e7b0e3d6)`):
* Server setup and configuration: In a kubernetes cluster using 
  * Helm Chart Version: 5.0.14
  * App Version: RELEASE.2023-09-30T07-02-29Z

**Comment by harshavardhana** [comment]
You need to make sure 

- first your URL is public via by setting the bucket for anonymous access
- then make sure to allow incoming requests for browser via your LB.

The usecase you are asking is normal is used by countless other people.

This is mostly your configuration issue.

**Comment by chamodtharakaperera** [comment]
> ## Expected Behavior
> Access to images in a public buckets like https://my-minio-storage-console-url.com/bucketname/test.jpg and so I can see the image in the browser
> 
> ## Current Behavior
> Actually I have a 200 Response but empty image ![image](https://private-user-images.githubusercontent.com/3163835/275495925-b5e434b8-255b-4fc7-92ad-42a2095ab571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjA4NDAsIm5iZiI6MTcxNzg2MDU0MCwicGF0aCI6Ii8zMTYzODM1LzI3NTQ5NTkyNS1iNWU0MzRiOC0yNTViLTRmYzctOTJhZC00MmEyMDk1YWI1NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTUyOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA0YWMxOTQ4N2E3NTc0ODFjYTE4MGM1MzY0MmY0ZjI5NjQxZmU5NjVmMjJmNzRhMWNmZmEyMGJlNmJjYTJlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6cG-kW-JfPRy8eD3SN2Mjn8u4fHXM3niqWFNfa9aUAo)
> 
> ## Your Environment
> * Version used (`minio version RELEASE.2023-09-30T07-02-29Z (commit-id=22d2dbc4e68a20ada8c82edf1cc68026e7b0e3d6)`):
> * Server setup and configuration: In a kubernetes cluster using
>   
>   * Helm Chart Version: 5.0.14
>   * App Version: RELEASE.2023-09-30T07-02-29Z

Same thing happened to me. The bucket is public and I am using a dockerized version of minio. It is so problematic when accessing public bucket objects. Tried multiple ways but when the file was downloaded it shows as corrupted. But the files are accessible with Presigned URLs without any issue. But the issue with Presigned URLs are they are getting expired quickly. Need a permanent URL solution for this.
