### ISSUE TITLE
Nested objects with content are elided by their parents

### ISSUE THREAD

**Issue by Jamstah** [minio/minio#18258]
## NOTE

If you create two objects with content where one is part of the path prefix of the other, the objects are not listed. This behaviour doesn't match the S3 behaviour and can mean content is undiscoverable.

I found this using the AWS SDK, because the behaviour is different from S3 it failed our tests with minio. Its easily reproducible using the mc command line, so I'll show that here.

## Expected Behavior
The objects should be listed in an `mc find`, and should be listed through the APIs.

## Current Behavior
The deeper file is elided, although the content is still there if you know where to look.

## Possible Solution
I assume its down to how directory structure is faked within minio.

## Steps to Reproduce (for bugs)
```
[root@97b04d0ac9a3 /]# mc config host add minio http://minio:9000 distribution password
Added `minio` successfully.
[root@97b04d0ac9a3 /]# mc mb minio/bucket
Bucket created successfully `minio/bucket`.
[root@97b04d0ac9a3 /]# echo content1 | mc pipe minio/bucket/content1
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━
[root@97b04d0ac9a3 /]# echo content2 | mc pipe minio/bucket/content1/content2
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━
[root@97b04d0ac9a3 /]# mc find minio/bucket
minio/bucket/content1
[root@97b04d0ac9a3 /]# mc ls -r minio/bucket
[2023-10-17 00:55:30 UTC]     9B STANDARD content1
[root@97b04d0ac9a3 /]# mc ls minio/bucket
[2023-10-17 00:55:30 UTC]     9B STANDARD content1
[root@97b04d0ac9a3 /]# mc ls minio/bucket/content1
[2023-10-17 00:55:30 UTC]     9B STANDARD content1
[root@97b04d0ac9a3 /]# mc ls minio/bucket/content1/
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1
content1
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1/
mc: <ERROR> Unable to read from `minio/bucket/content1/`. Object does not exist.
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1/content2
content2
[root@97b04d0ac9a3 /]# mc rm minio/bucket/content1
Removed `minio/bucket/content1`.
[root@97b04d0ac9a3 /]# mc find minio/bucket
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1/content2
mc: <ERROR> Unable to read from `minio/bucket/content1/content2`. Object does not exist.
```

## Context
Found in test, attempting to use minio to run the test suite for the CNCF distribution project: https://github.com/distribution/distribution/blob/main/registry/storage/driver/s3-aws/s3_test.go#L307

## Regression
Don't know, first use.

## Your Environment

* Version used (`minio --version`):
  * docker.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
  * docker.io/minio/mc:RELEASE.2023-10-14T01-57-03Z
* Server setup and configuration: `server /data --console-address ":9001"` - no other config
* Operating System and version (`uname -a`): podman on fedora

**Comment by harshavardhana** [comment]
@Jamstah we do not support this and it is not possible in current scenarios to support it either.

It is mentioned in what to avoid and why it is a bad idea to use objects in this manner .
https://min.io/docs/minio/linux/operations/concepts/thresholds.html

Look at the conflicting objects section.

**Comment by Jamstah** [comment]
So the failure is actually that is accepts the object in the first place: https://github.com/minio/minio/issues/18262
