### ISSUE TITLE
XL: Tests: tree-walk tests for fs and XL. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1825]
Tests for tree-walk implementation of fs and XL needed. Its a high priority test.

**Comment by GarimaKapoor** [comment]
please put a timeline for the fix.

**Comment by balamurugana** [comment]
To be fixed: 11-Jun-2016

**Comment by GarimaKapoor** [comment]
Please update the timeline

**Comment by krisis** [comment]
Will try to send a PR for this issue by Jun 23rd.
