### ISSUE TITLE
Unable to run trace on s3

### ISSUE THREAD

**Issue by beeritis** [minio/minio#18267]
## NOTE

When we try and run a trace command : 

mc admin trace -v  --call s3 localhost -debug

We get the following error :  
{"Code":"InternalError","Message":"We encountered an internal error, please try again. (the limit of `8` subscribers is reached)","Resource":"/minio/admin/v3/trace

## Expected Behavior
Expect S3 trace to work correctly.

## Possible Solution
Advice on what this error means , as I couldn't find anything in the docs

## Steps to Reproduce (for bugs)
Run the command 
# localhost is set to the correct endpoint as other commands work fine
mc admin trace -v  --call s3 localhost -debug

## Context
Trying to debug s3 issues

## Your Environment

* Version used (`minio --version`): **RELEASE.2023-09-04T19-57-37Z (commit-id=1c99fb106c3e1448ed92f8465d5695d055d432e7)**
* Server setup and configuration: RHEL9 , standard system install
* Operating System and version (`uname -a`): 5.14.0-284.30.1.el9_2.x86_64

**Comment by ravindk89** [comment]
How are you starting MinIO here?

**Comment by beeritis** [comment]
> How are you starting MinIO here?

Systemd service : 

```[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/

User=minio
Group=minio
#ProtectProc=invisible

EnvironmentFile=/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=1048576

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```

**Comment by ravindk89** [comment]
https://github.com/minio/minio/blob/master/internal/pubsub/pubsub.go#L66

Errror comes from here as far as I can tell.

Can you provide more detail on the system here? What kind of hardware it is, how you've configured MinIO, etc.

**Comment by harshavardhana** [comment]
It's just running an plethora amount of traces. It is useless to do that.

**Comment by beeritis** [comment]
Not the ideal solution, but a restart of the minio.service seems to have resolved this. Not sure why there were many traces running . I think this was attempts at using the gui method, rather than the terminal which is more reliable.
