### ISSUE TITLE
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive

### ISSUE THREAD

**Issue by staybox** [minio/minio#18266]
Hello,

Our minio runs in Kubernetes. We had a hard drive replaced on one of our servers due to a failure. After replacing the hard drive, errors began to occur inside the Pod Minio. Next, we rebooted the server (worker node) and even more errors appeared inside the Kubernetes minio pod.

Errors:
API: SYSTEM()
Time: 10:10:09 UTC 10/17/2023
DeploymentID: 0d87f32e-8368-42f0-8bbb-c6f79f79e8fe
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive: expecting http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export13, found http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export14, refusing to use the drive (*fmt.wrapError)
       endpoint="http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export14"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:237:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 10:10:09 UTC 10/17/2023
DeploymentID: 0d87f32e-8368-42f0-8bbb-c6f79f79e8fe
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive: expecting http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export7, found http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export11, refusing to use the drive (*fmt.wrapError)
       endpoint="http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export11"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:237:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 10:10:09 UTC 10/17/2023
DeploymentID: 0d87f32e-8368-42f0-8bbb-c6f79f79e8fe
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive: expecting http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export11, found http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export13, refusing to use the drive (*fmt.wrapError)
       endpoint="http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export13"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:237:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 10:10:09 UTC 10/17/2023
DeploymentID: 0d87f32e-8368-42f0-8bbb-c6f79f79e8fe
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive: expecting http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export14, found http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export7, refusing to use the drive (*fmt.wrapError)
       endpoint="http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export7"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:237:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 10:10:10 UTC 10/17/2023
DeploymentID: 0d87f32e-8368-42f0-8bbb-c6f79f79e8fe
Error: drive not found: http://archive-ss-0-3.archive-hl.s3.svc.cluster.local:9000/export2 (*errors.errorString)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/erasure.go:179:cmd.getDisksInfo.func1()
       1: github.com/minio/pkg@v1.7.2/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

## Your Environment

Kubernetes: v1.21.4
Operating System and version: CentOS Linux release 7.9.2009  kernel 3.10.0-1160.el7.x86_64
Minio operator: MINIO_OPERATOR_VERSION:        v4.4.26
Minio image: minio/minio:RELEASE.2023-06-02T23-17-26Z

**Comment by harshavardhana** [comment]
Just like the message says you need to fix your drive ordering and mapping.

Move the drive on export7 to export14

**Comment by Howie516** [comment]
Hi, I would like to ask how to solve it? We also encounter this phenomenon, but pod and node file mount paths are bound one-to-one, so there should be no driver order issues.
 See details: [https://github.com/minio/minio/discussions/18598](url)

**Comment by harshavardhana** [comment]
> Hi, I would like to ask how to solve it? We also encounter this phenomenon, but pod and node file mount paths are bound one-to-one, so there should be no driver order issues.
> See details: [https://github.com/minio/minio/discussions/18598](url)

of course there will be if your pod is scheduled to different servers with PV affinity

**Comment by Howie516** [comment]
We did not use PV affinity, pod is scheduled to appointed node by config hostpath and selectnode

**Comment by harshavardhana** [comment]
Host path leads to these problems as it changes positions. You need to make sure to use local PVs or our project DirectPV.
