### ISSUE TITLE
Nested objects with content are accepted but aren't supported

### ISSUE THREAD

**Issue by Jamstah** [minio/minio#18262]
## NOTE

If you create two objects with content where one is part of the path prefix of the other, the objects are not listed. This behaviour is explicitly listed as not supported in the [documentation](https://min.io/docs/minio/linux/operations/concepts/thresholds.html#conflicting-objects), but the objects are accepted which makes the interface inconsistent.

I found this using the AWS SDK, because the behaviour is different from S3 it failed our tests with minio. Its easily reproducible using the mc command line, so I'll show that here.

## Expected Behavior
Attempting to put an object that causes a conflict should fail with a sensible error.

## Current Behavior
The put is accepted and then the nested file cannot be listed but the content is still stored.

## Possible Solution
Add a nesting check on put

## Steps to Reproduce (for bugs)
```
[root@97b04d0ac9a3 /]# mc config host add minio http://minio:9000 distribution password
Added `minio` successfully.
[root@97b04d0ac9a3 /]# mc mb minio/bucket
Bucket created successfully `minio/bucket`.
[root@97b04d0ac9a3 /]# echo content1 | mc pipe minio/bucket/content1
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━
[root@97b04d0ac9a3 /]# echo content2 | mc pipe minio/bucket/content1/content2
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━
[root@97b04d0ac9a3 /]# mc find minio/bucket
minio/bucket/content1
[root@97b04d0ac9a3 /]# mc ls -r minio/bucket
[2023-10-17 00:55:30 UTC]     9B STANDARD content1
[root@97b04d0ac9a3 /]# mc ls minio/bucket
[2023-10-17 00:55:30 UTC]     9B STANDARD content1
[root@97b04d0ac9a3 /]# mc ls minio/bucket/content1
[2023-10-17 00:55:30 UTC]     9B STANDARD content1
[root@97b04d0ac9a3 /]# mc ls minio/bucket/content1/
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1
content1
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1/
mc: <ERROR> Unable to read from `minio/bucket/content1/`. Object does not exist.
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1/content2
content2
[root@97b04d0ac9a3 /]# mc rm minio/bucket/content1
Removed `minio/bucket/content1`.
[root@97b04d0ac9a3 /]# mc find minio/bucket
[root@97b04d0ac9a3 /]# mc cat minio/bucket/content1/content2
mc: <ERROR> Unable to read from `minio/bucket/content1/content2`. Object does not exist.
```

## Context
Found in test, attempting to use minio to run the test suite for the CNCF distribution project: https://github.com/distribution/distribution/blob/main/registry/storage/driver/s3-aws/s3_test.go#L307

## Regression
Don't know, first use.

## Your Environment

* Version used (`minio --version`):
  * docker.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
  * docker.io/minio/mc:RELEASE.2023-10-14T01-57-03Z
* Server setup and configuration: `server /data --console-address ":9001"` - no other config
* Operating System and version (`uname -a`): podman on fedora

**Comment by klauspost** [comment]
We have removed this check since it is quite costly in terms of additional IO per upload. 

While we may add it as an option, we do not have any current plans to re-implement this as we only ever encounter it in test scenarios - and objects with a trailing slash (which are the only one we see in production) are not affected by this limitation.

**Comment by ravindk89** [comment]
Related to https://github.com/minio/minio/issues/18148#issuecomment-1744000795.

I'll have this fixed today.
