### ISSUE TITLE
XL: Tests: Unit tests and benchmark for object handlers. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1826]
All Object handlers need to be unit tested with wide range of cases, and also benchmark for the handlers could come handy while optimizing specific parts of it. The style of tests would be similar to existing tests in `server_test.go` and `server_test_xl.go`.  We can consider fuzzing some of the handlers.

**Comment by krishnasrinivas** [comment]
deadline - 9th June

**Comment by GarimaKapoor** [comment]
Karthic, What is the status of this issue?

**Comment by hackintoshrao** [comment]
@GarimaKapoor :. As I had said earlier this needed revamp to entire testing framework and new framework for benchmark execution had to be created.  A PR is almost ready for this. But to finish this process for all handlers will take time. Will break it down into more issues and close them as PR's are done.

**Comment by hackintoshrao** [comment]
@harshavardhana :  With Benchmark for GetObject Hanldler This issue can be closed now. Will open more specific issues.
