### ISSUE TITLE
logging: Error log infrastructure

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1827]
In the meeting what we had decided was:
- at the place where error happens we capture the stack trace into an `error` type and return it to the caller.
- the top layer (caller) can decide to print or not the stack trace and error message.

**Comment by krishnasrinivas** [comment]
deadline - 10th June

**Comment by GarimaKapoor** [comment]
Please update the timeline.

**Comment by krishnasrinivas** [comment]
In today's meeting it was decided to implement this for this release.

**Comment by krishnasrinivas** [comment]
deadline - 15th June

**Comment by krishnasrinivas** [comment]
reference code: https://github.com/krishnasrinivas/test/blob/master/pkg/minerrors/errors.go

**Comment by harshavardhana** [comment]
> reference code: https://github.com/krishnasrinivas/test/blob/master/pkg/minerrors/errors.go

Why didn't we explore the possibility of using this? https://github.com/pkg/errors instead?.

http://dave.cheney.net/paste/gocon-spring-2016.pdf an article explaining the theory behind.

**Comment by krishnasrinivas** [comment]
> Why didn't we explore the possibility of using this? https://github.com/pkg/errors instead?.

It was explored, check https://gitter.im/minio/minio?at=57431c7c46fb6493380b7646 but our probe is much better as it can track more information (like function names in the stack trace). This package also carries the same problem as probe ie you have to do errors.Wrap() at every function level.

Also at XL we need the ability to aggregate errors from disks and present as one error message to the caller functions:
https://github.com/krishnasrinivas/test/blob/master/pkg/minerrors/errors.go#L107

**Comment by harshavardhana** [comment]
> It was explored, check https://gitter.im/minio/minio?at=57431c7c46fb6493380b7646 but our probe is much better as it can track more information (like function names in the stack trace). This package also carries the same problem as probe ie you have to do errors.Wrap() at every function level.

Is there a sample output? or atleast how the output looks like?  - btw the stack in `errors` does indeed capture that - https://github.com/pkg/errors/blob/master/stack.go

> Also at XL we need the ability to aggregate errors from disks and present as one error message to the caller functions:
> https://github.com/krishnasrinivas/test/blob/master/pkg/minerrors/errors.go#L107

It used to be but we don't check for that anymore, `reduceError()` has gone because we are not doing error checks in that manner. So that part is not useful anymore. In-fact we do like to see the individual error happened on each disk rather than single error since there was an information loss at `reduceError()`.

**Comment by krishnasrinivas** [comment]
> Is there a sample output? or atleast how the output looks like? - btw the stack in errors does indeed capture that - https://github.com/pkg/errors/blob/master/stack.go

check `go run` output here:  https://gitter.im/minio/minio?at=57431c7c46fb6493380b7646
looks like function names were added recently.

> It used to be but we don't check for that anymore, reduceError() has gone because we are not doing error checks in that manner. So that part is not useful anymore. In-fact we do like to see the individual error happened on each disk rather than single error since there was an information loss at reduceError().

that is correct, logging happens at the topmost layer which needs to have access to all the disk errors, that is why https://github.com/krishnasrinivas/test/blob/master/pkg/minerrors/errors.go#L86 `xlError` needs to have []errors (of the disks) you weren't there when discussion happened on this, we can discuss again.

**Comment by GarimaKapoor** [comment]
Update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
timeline - 21st

**Comment by GarimaKapoor** [comment]
@krishnasrinivas what is the status of this issue?

**Comment by krishnasrinivas** [comment]
@GarimaKapoor i haven't gotten to work on this yet, will try to finish this by tomorrow.

**Comment by harshavardhana** [comment]
This is fixed by #2558
