### ISSUE TITLE
HeadObjectHandler call throws an error

### ISSUE THREAD

**Issue by audo-canva** [minio/minio#18278]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
When calling `HeadObjectHandler`, I'm expecting it to pass through fine without any exceptions or errors.

## Current Behavior
 it's throwing the exception `Error: Unexpected range specification case`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Regression
Yes. The last good release is `RELEASE.2023-05-04T21-44-30Z`. We have not been able to upgrade our version of minio since.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@audo-canva please provide a reproducer, until then closing the issue.
