### ISSUE TITLE
minio inconsistent with Amazon S3

### ISSUE THREAD

**Issue by matwey** [minio/minio#18281]
Hello,

I use AWS JavaScript SDK v3 and I've just found that minio behaves differently from Amazon S3 (and two other "S3-like" cloud providers).
See the minimal code sample at "Steps to Reproduce" section.

## Expected Behavior
I expect minio to return `200 OK` in response to `PutObject` command performed using presigned URL. Like any tested S3 cloud provider does.

## Current Behavior
minio responses with `AccessDenied`: `There were headers present in the request which were not signed`.

## Steps to Reproduce (for bugs)
0. Setup node.js environment with `@aws-sdk/client-s3@3.431.0`, `@aws-sdk/s3-request-presigner@3.431.0`, and `node-fetch@2.0`.
1. Try to run the following node.js code with appropriate minio credentials (`node index.js`):
```javascript
const fetch = require('node-fetch');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const minioParams = {
  region: // ...
  endpoint: // ...
    credentials: {
    accessKeyId: // ...
    secretAccessKey: // ...
  },
};

const bucket = "test";
const key = "hello.txt";
const metadata = {
  "Id": "42",
};

async function getUrl(params) {
  const client = new S3Client(params);
  const command = new PutObjectCommand({ Bucket: bucket, Key: key, Metadata: metadata });
  const url = getSignedUrl(client, command, { expiresIn: 3600 });

  return url;
}

async function run(params) {
  const url = await getUrl(params);

  console.log(url);

  const response = await fetch(url, {
    method: "PUT",
    body: "Hello, World!",
  });

  if (response.ok) {
    console.log("Ok");
  } else {
    console.log(response.statusText);

    const body = await response.text();

    console.log(body);
  }
}

run(minioParams);
```
2. See the error.

## Context
I am trying to PUT the object using presigned URL and I also want to provide some metadata for this object.
I am also sure that my minio credentials are correct, since
```javascript
const metadata = {};
```
fixes the issue. Replacing the `params` with the valid credentials of any S3 cloud provided also fixes the issue.

## Regression
Not sure

## Your Environment
* Version used (`minio --version`):
```
minio version RELEASE.2023-10-07T15:07:38Z (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```
* Server setup and configuration: testing virtual machine with single disk.
* Operating System and version (`uname -a`):
```
Linux linux 5.14.21-150400.24.88-default #1 SMP PREEMPT_DYNAMIC Thu Sep 21 12:45:42 UTC 2023 (2cab595) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jiuker** [comment]
I will check and get back.
