### ISSUE TITLE
Not able to change Minio from standalone to distributed 

### ISSUE THREAD

**Issue by aljabertareq** [minio/minio#18293]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

We have an existing Standalone (not distributed) Minio as a statefulset with one replica. This is deployed on Kubernetes cluster.  We are trying to scale it to 2 pods (more than one replica) by chaning the number of replicas to 2 in the Yaml file. After we do this, data is not getting syned across the 2 pods. How do we make change Minio StateFulSet to a distrubted cluster.

## Expected Behavior
Changing Minio to more than one replica using the configuration file, should start syncing data between the 2 pods.

## Current Behavior

Data is not being synced between the 2 pods.

## Steps to Reproduce (for bugs)

1. Go to Yaml file, change changing replica from 1 to 2 
2. Apply the changes using Helm chart. 
3. Login to Minio console. It forward the request to one replica for one pod when we have data. 
4. check the second pod. you won't see the data presented there. Which means the data is not being synced. 

## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2022-04-09T15-09-52Z
* Server setup and configuration: Kubernetes 
* Operating System and version (`uname -a`): Ubuntu 20.04.6

**Comment by jiuker** [comment]
We never support that. You should set a replication to your old cluster. Checkout the https://min.io/docs/minio/linux/reference/minio-mc/mc-replicate.html.

**Comment by aljabertareq** [comment]
Thanks @jiuker! What do you mean we never supported that? Can you elaborate. Are you saying what we are trying to do is not doable? You can't have replicas?

Alss - what do you mean you should set replication to your old cluster? We only have one cluster.

**Comment by jiuker** [comment]
> Thanks @jiuker! What do you mean we never supported that? Can you elaborate. Are you saying what we are trying to do is not doable? You can't have replicas?
> 
> Alss - what do you mean you should set replication to your old cluster? We only have one cluster.

Yeah. We never have replicas unless you set a cluster to replicate another. @aljabertareq

**Comment by aljabertareq** [comment]
@jiuker  But that's what we are doing using cluster configuration YAML file and it's not working. Would you like me to share YAML file with you?

**Comment by jiuker** [comment]
> https://min.io/docs/minio/linux/reference/minio-mc/mc-replicate.html

No yaml here. Checkout this https://min.io/docs/minio/linux/reference/minio-mc/mc-replicate.html @aljabertareq

**Comment by aljabertareq** [comment]
@jiuker will do. I'll let you know the outcome. Thanks
