### ISSUE TITLE
Minio Transition and Storage resources are insufficient for the read operation Error.

### ISSUE THREAD

**Issue by naveenragamoini** [minio/minio#18290]
Hello,

I have installed minio operator on azure AKS cluster and created a tenant. The inital size of the tenant was 1TB and then I have later expanded it to 5 TB. I have configued Minio transition rules for the buckets which I have created. The tranistion rule is to write the files to the Azure Blob. I am able to see the files name with correct file size on minio console and also I am able to view the files in the Azure blob but when I am trying to download the files, few of them are loaded only half and when I am trying to retrive them using the S3 API I am facing EOF exception. When I saw the tiering stats in the Minio Console I see that only 75% percent of the objects are tired and then when I saw the logs for the other teiring stats it says that "Transition to "FileName" version: with Storage resources are insufficient for the read operation "File Name" (*fmt.wrapError). and also for few buckets the transition is successful for few objects but then for few objects there is an error that remote storage not found. Please find the configuration of the MinIO Tenant. Any help in resolving this is highly appriciated, Thanks in advance

metadata:
  creationTimestamp: "2023-08-09T03:42:05Z"
  generation: 26
  name: test
  namespace: test-namespace
  resourceVersion: "32066053"
  uid: 1ec9ab21-782f-487e-9f7c-53f9205d92c1
scheduler:
  name: ""
spec:
  certConfig:
    commonName: '*.test-hl.test-namespace.svc.cluster.local'
    dnsNames:
    - test-pool-0-{0...3}.test-hl.test-namespace.svc.cluster.local
    - test-pool-1-{0...3}.test-hl.test-namespace.svc.cluster.local
    organizationName:
    - system:nodes
  configuration:
    name: test-env-configuration
  credsSecret:
    name: test-secret
  exposeServices:
    console: true
    minio: true
  externalCertSecret:
  - name: tls-minio
    type: kubernetes.io/tls
  features:
    domains:
      console: https://console-URL:9443
      minio:
      - https://minio-URL
    enableSFTP: true
  image: minio/minio:RELEASE.2023-08-09T23-30-22Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - test
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources: {}
    runtimeClassName: ""
    servers: 4
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "68719476736"
        storageClassName: azurefile
      status: {}
    volumesPerServer: 4
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - test
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-1
          topologyKey: kubernetes.io/hostname
    name: pool-1
    resources: {}
    runtimeClassName: ""
    servers: 4
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "274877906944"
        storageClassName: default
      status: {}
    volumesPerServer: 4
  requestAutoCert: true
  serviceAccountName: test-sa
  users:
  - name: test-user-0
status:
  availableReplicas: 7
  certificates:
    autoCertEnabled: true
    customCertificates:
      minio:
      - certName: tls-minio
        domains:
        - minio-domain-name
        - console-domain-name
        - minio-domain-name
        expiresIn: 79 days, 10 hours, 37 minutes, 47 seconds
        expiry: "2024-01-08T19:32:38Z"
        serialNo: "377614670711493618567756955100165348107270"
      - certName: tls-minio
        domains:
        - R3
        expiresIn: 695 days, 7 hours, 5 minutes, 9 seconds
        expiry: "2025-09-15T16:00:00Z"
        serialNo: "192961496339968674994309121XXXXXX"
      - certName: tls-minio
        domains:
        - ISRG Root X1
        expiresIn: 345 days, 9 hours, 19 minutes, 12 seconds
        expiry: "2024-09-30T18:14:03Z"
        serialNo: "850782002656444175691093891XXXXXXX"
  currentState: Initialized
  drivesOffline: 4
  drivesOnline: 28
  healthStatus: yellow
  pools:
  - legacySecurityContext: false
    ssName: test-pool-0
    state: PoolInitialized
  - legacySecurityContext: false
    ssName: test-pool-1
    state: PoolInitialized
  provisionedUsers: true
  revision: 0
  syncVersion: ""
  usage:
    rawCapacity: 5497558138880
    rawUsage: 262546419712
    tiers:
    - Name: STANDARD
      Type: internal
      totalSize: 75271510309
    - Name: AZURE_TIER
      Type: azure
      totalSize: 0
    - Name: CENTAL_REGION_TIER
      Type: azure
      totalSize: 1472507185954
    - Name: EAST_REGION_TIER
      Type: azure
      totalSize: 1421013109368
    - Name: LRGV_REGION_TIER
      Type: azure
      totalSize: 0
    - Name: TEST_MINIO_TIER
      Type: azure
      totalSize: 0
    - Name: TFMR_REGION_TIER
      Type: azure
      totalSize: 502880587973
    - Name: WEST_REGION_TIER
      Type: azure
      totalSize: 0
  writeQuorum: 12

**Comment by naveenragamoini** [comment]
Can someone please help me with your insights on this issue.

**Comment by krisis** [comment]
@naveenragamoini you may be affected by this bug - https://github.com/minio/minio/issues/18403. We have a fix for it which is under review.
