### ISSUE TITLE
How to Preserve Case Sensitivity for Custom Headers in MinIO .NET SDK's Presigned URLs?

### ISSUE THREAD

**Issue by sajjadkalantari** [minio/minio#18299]
I'm using MinIO in conjunction with the .NET SDK to generate presigned URLs for object downloads. I have a specific requirement to include a custom header in the presigned URL with case sensitivity preserved. However, when I attempt to add headers to the PresignedGetObjectArgs, it appears that the headers are transformed to lowercase in the resulting URL.

Here's a simplified version of the code I'm using:
``` c#
var args = new PresignedGetObjectArgs()
    .WithBucket(model.BucketName)
    .WithExpiry(model.ExpireIn)
    .WithHeaders(new Dictionary<string, string> { { "versionId", model.VersionId } });

return _minioClient.PresignedGetObjectAsync(args);

```

The problem is that the resulting URL ends up with lowercase headers, like this:
http://127.0.0.1:9000/testbucket/1.png?[..someheaders]&versionid=somevalue

What I want is for the custom header "versionId" to retain its original case sensitivity in the presigned URL, like this:
http://127.0.0.1:9000/testbucket/1.png?[..someheaders]&versionId=somevalue

Is there a way to achieve this case-sensitive preservation for custom headers in MinIO's .NET SDK when generating presigned URLs?

**Comment by harshavardhana** [comment]
HTTP headers are case-insensitive that is not possible.

**Comment by sajjadkalantari** [comment]
Is there an alternative method to obtain a presigned URL for a specific version of an object?

**Comment by harshavardhana** [comment]
> Is there an alternative method to obtain a presigned URL for a specific version of an object?

Case will not be sensitive that's all generated presigned URLs will work.

**Comment by sajjadkalantari** [comment]
It doesn't work as intended; it will consistently return the link to the latest version of the object, even if the version ID changes.

**Comment by harshavardhana** [comment]
> It doesn't work as intended; it will consistently return the link to the latest version of the object, even if the version ID changes.

you have to pass the correct versionId on the client side.

**Comment by harshavardhana** [comment]
> The problem is that the resulting URL ends up with lowercase headers, like this: [http://127.0.0.1:9000/testbucket/1.png?[..someheaders]&versionid=somevalue](http://127.0.0.1:9000/testbucket/1.png?%5B..someheaders%5D&versionid=somevalue)
> 
> What I want is for the custom header "versionId" to retain its original case sensitivity in the presigned URL, like this: [http://127.0.0.1:9000/testbucket/1.png?[..someheaders]&versionId=somevalue](http://127.0.0.1:9000/testbucket/1.png?%5B..someheaders%5D&versionId=somevalue)

Okay also this is a bug in `minio-dotnet` 

```
mc share download play/testbucket/cover_102 --vid null
URL: https://play.min.io/testbucket/cover_102
Expire: 7 days 0 hours 0 minutes 0 seconds
Share: https://play.min.io/testbucket/cover_102?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20231023%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231023T190438Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=10f6fbe9cd4d5a9e7ec8e608c22cbc672a0db4ef9b559d8f7db6126d96050e4e
```

Can you please report this issue here https://github.com/minio/minio-dotnet
