### ISSUE TITLE
MultiUpload file interrupts for big files on replication

### ISSUE THREAD

**Issue by AntonUstyugov** [minio/minio#18295]
I have 2 clusters, with not so fast disks on second. I settled bucket replication from one to another.
Some of the file are more than 100Gb, and replication for them constantly fails.
All small files replicated correctly

## Expected Behavior
I expected that all files will be on second site correctly

## Current Behavior
In logs I can see
```
API: SYSTEM()
Time: 04:13:35 UTC 10/23/2023
DeploymentID: 17f127a0-6641-4589-8942-3e17e6400956
Error: unable to replicate for object mybucket/file.zst(f9444ec0-c110-42ae-9acc-f39340d2b5c3): Put "http://minio2:9000/mybucket/file?partNumber=147&uploadId=Mjc0YjZjYzAtOTdjYy00NDEyLTgzMzktYzZiZWY3YmNiYTFmLmNiOGNlNTQ1LWE0MjktNDE5Ni1iNGFkLTA5ZTgxYWY0ZDkyNw": context deadline exceeded (*errors.errorString)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/bucket-replication.go:1505:cmd.ReplicateObjectInfo.replicateAll()
       1: cmd/bucket-replication.go:1045:cmd.replicateObject.func2()
```

In trace:
```
Start replication:
2023-10-23T03:13:27.992 [200 OK] s3.NewMultipartUpload minio2:9000/mybucket/file.zst?uploads=&versionId=f9444ec0-c110-42ae-9acc-f39340d2b5c3  minio1       716µs       ⇣  700.407µs  ↑ 190 B ↓ 355 B
...

Replications fail:
2023-10-23T04:13:34.693 [499 ] s3.PutObjectPart minio2:9000/mybucket/file.zst?partNumber=147&uploadId=Mjc0YjZjYzAtOTdjYy00NDEyLTgzMzktYzZiZWY3YmNiYTFmLmNiOGNlNTQ1LWE0MjktNDE5Ni1iNGFkLTA5ZTgxYWY0ZDkyNw  minio1       845.776ms    ⇣  845.751809ms   ↑ 106 B ↓ 444 B
2023-10-23T04:13:34.696 [204 No Content] s3.AbortMultipartUpload minio2:9000/mybucket/file.zst?uploadId=Mjc0YjZjYzAtOTdjYy00NDEyLTgzMzktYzZiZWY3YmNiYTFmLmNiOGNlNTQ1LWE0MjktNDE5Ni1iNGFkLTA5ZTgxYWY0ZDkyNw  minio1       881.081ms    ⇣  0s         ↑ 77 B ↓ 0 B
2023-10-23T04:13:35.848 [404 Not Found] s3.HeadObject minio2:9000/mybucket/file.zst?versionId=f9444ec0-c110-42ae-9acc-f39340d2b5c3  10.5.10.18       409µs       ⇣  0s         ↑ 106 B ↓ 0 B

```

## Possible Solution
Looks like  it's hardcoded timeout for 1 hour for replication content

## Steps to Reproduce (for bugs)
1. Make bucket replication
2. Upload big file
3. Limit upload speed for the time
4. Wait 1 hour

## Your Environment
* Version used (`minio --version`):
# minio --version
```
minio version RELEASE.2023-09-30T07-02-29Z (commit-id=22d2dbc4e68a20ada8c82edf1cc68026e7b0e3d6)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
client server:
4 servers with network disks
remote server:
1 server with 1 HDD

* Operating System and version (`uname -a`):
Both servers are: Ubuntu 22.04.3 LTS \n \l

**Comment by harshavardhana** [comment]
> Limit upload speed for the time

are you limiting replication band width?

**Comment by AntonUstyugov** [comment]
> > Limit upload speed for the time
> 
> are you limiting replication band width?

no, it's by default. and network Is more or less good (10Gb). The limitation is mostly disk on destination part in my case.

**Comment by harshavardhana** [comment]
> > > Limit upload speed for the time
> > 
> > 
> > are you limiting replication band width?
> 
> no, it's by default. and network Is more or less good (10Gb). The limitation is mostly disk on destination part in my case.

And what is the load balancer here ?

**Comment by AntonUstyugov** [comment]
by the way, I changed hardcoded [timeout for 1 hour for 1 context](https://github.com/minio/minio/blob/RELEASE.2023-09-30T07-02-29Z/cmd/bucket-replication.go#L57) and it fixed my problem temporary.
But what will be better to do for fix? make the timeout as option, or don't close the context, if the website is available, and it's continue to copy data. Not just reset the context and start to upload files from the beginning.

**Comment by harshavardhana** [comment]
> by the way, I changed hardcoded [timeout for 1 hour for 1 context](https://github.com/minio/minio/blob/RELEASE.2023-09-30T07-02-29Z/cmd/bucket-replication.go#L57) and it fixed my problem temporary. But what will be better to do for fix? make the timeout as option, or don't close the context, if the website is available, and it's continue to copy data. Not just reset the context and start to upload files from the beginning.

Yeah it is done on purpose, we really need to avoid having tons of transfers that are taking unending amount of time.

That's why we expect that you match the IOPs of both sites to be same.

You cannot setup replication in this manner .

**Comment by AntonUstyugov** [comment]
wait wait. It's not fixed.
the problem is not in IO. 
you can't copy 15Tb file for example for seconds... or even during hardcoded 1 hour.
If you haven't got 100Gb links between or infinibend network

**Comment by harshavardhana** [comment]
You can't have 4 node setup on one end and 1 drive on another. That's just simply wrong.

**Comment by AntonUstyugov** [comment]
yes
And they have different IP and network. 
One node has doubled IP than all others.
And I want to replicate data for bigger distance, but with much more IO and network on input.
And in that case RTT will be limit. 
I don't see reasons to limit the context with 1 hour, and MinIO then resend all the data in loop between two points.

node count is not the same as node performance. Are you agree?

**Comment by AntonUstyugov** [comment]
For example copy 1Tb file with 1Gb network.
If it will be utilize fully with 0 rtt, and 0 time on new connection it will take ~2.2 hours. 

In my case with 10Gb network ,with IO load in up to 50% of max.
With internal replication, network overhead, and several files in parallel,  MinIO can't finish copy even 100Gb file. 

Could you recommend me optimal settings for it?

**Comment by poornas** [comment]
you seem to have bandwidth limit throttling enabled for replication - check `mc replicate status alias/bucket --json` bandwidthlimit in remoteTargets section. you can remove replication config fully and re-do your bucket replication setup without throttling.

**Comment by AntonUstyugov** [comment]
thanks! 
Is it the limit? it looks like "unlimited"... Should I remove it anyway? 

<img width="396" alt="Screenshot 2023-10-23 at 20 38 50" src="https://github.com/minio/minio/assets/50240284/acd513d7-5ef8-4ef4-b2b5-8e827d7ea841">

**Comment by poornas** [comment]
go ahead and remove it - `mc replicate rm --all --force alias/bucket` ; then `mc replicate add...` without --bandwidth-limit flag. This will most likely not going to improve replication - it will just avert the 1hr context deadline.

**Comment by AntonUstyugov** [comment]
I've made the changes to the settings. With the new replication configuration, the limit remains the same by default, and it's set at a generous capacity.

I would appreciate your input on whether a one-hour replication time is suitable for entire files, regardless of their size, be it 1GB, 10GB, or even 100GB. This timeframe applies to the entire file, not just a specific part. Your insights on this matter would be valuable.

**Comment by slena1** [comment]
> by the way, I changed hardcoded [timeout for 1 hour for 1 context](https://github.com/minio/minio/blob/RELEASE.2023-09-30T07-02-29Z/cmd/bucket-replication.go#L57) and it fixed my problem temporary. But what will be better to do for fix? make the timeout as option, or don't close the context, if the website is available, and it's continue to copy data. Not just reset the context and start to upload files from the beginning.

I also encountered the same issue as you did. How did you modify "changed hardcoded timeout for 1 hour for 1 context"? I searched through their documentation for a long time but couldn't find any relevant configuration.
