### ISSUE TITLE
make-user job in community helm chart broken

### ISSUE THREAD

**Issue by mundry** [minio/minio#18315]
Hi,

since changing the base image of the `mc` container image from ubi-minimal to ubi-micro ([minio/mc#4725](https://github.com/minio/mc/pull/4725)), the make-user step in the community helm chart is broken when using an existing secret for credentials, as [the step uses `sed`](https://github.com/minio/minio/blob/0594d372309510c5a37b09f6134735398d1efaa1/helm/minio/templates/_helper_create_user.txt#L100), which is not included in ubi-micro.

## Expected Behavior
Running the community helm chart with values for an user and credentials from an existing secret defined to run smoothly and create the user according to the given values.

## Current Behavior
The create-user job fails, as `sed` is missing from the `mc` container image. Hence no user is created. The deployment finishes with an error.
```
Connecting to MinIO server: http://minio:9000
Added `myminio` successfully.
/config/add-user: line 89: sed: command not found
```

## Possible Solution
I see a few possible options to resolve this.
* Rolling back the base image to use ubi-minimal again
* Installing sed in the mc container image, based on ubi-micro
* Refactoring the `sed` line in the make-user job to use an available command.
* Dropping the `sed` line altogether. (I'm not sure on the repercussions of this)

## Steps to Reproduce (for bugs)
Create a minio deployment using the community helm chart and specifying the respective values for an user to be created, with credentials from an existing secret.

## Context
Setting up the minio server worked fine. However, the make-user job failed. not creating an user as specified as a result. 
Other jobs part of the chart remain unaffected, as the minio server deployment is executed as expected.

## Regression
Yes
[minio/mc#4725](https://github.com/minio/mc/pull/4725)

## Your Environment
minio: RELEASE.2023-10-25T06-33-25Z
mc: RELEASE.2023-10-24T05-18-28Z

**Comment by PKizzle** [comment]
As a temporary solution I have replaced `sed -i '$a\' $MINIO_ACCESSKEY_SECRETKEY_TMP` with `echo >> $MINIO_ACCESSKEY_SECRETKEY_TMP`. This will always append a newline at the end of the file instead of only if none existed beforehand but with the very limited tools available in ubi-micro that seems to be the best solution at the moment.
