### ISSUE TITLE
Space isn't reclaimed when deleting a bucket

### ISSUE THREAD

**Issue by paulpaul1076** [minio/minio#18341]
I created a bucket:
aws s3api --endpoint http://localhost:9000/ create-bucket --bucket bucket2
Then I uploaded several GB of data there.
Then I deleted it:
 aws s3 --endpoint http://localhost:9000/ rb s3://bucket2 --force
 
**But the space isn't reclaimed, why is it happening, how do I delete it so that space is reclaimed?**

## Expected Behavior
Space should be reclaimed after deleting a bucket

## Current Behavior
Space isn't reclaimed after deleting a bucket.

## Steps to Reproduce (for bugs)
In the general summary

## Your Environment
latest docker image, run locally

**Comment by harshavardhana** [comment]
IT is not automatically reclaimed, deletes() are renamed to `.minio.sys/tmp/.trash/` folder and are cleaned every 5mins.

**Comment by paulpaul1076** [comment]
@harshavardhana so, it is automatically reclaimed, but in 5 minutes? I had minio running for days and nothing got reclaimed.

**Comment by harshavardhana** [comment]
> @harshavardhana so, it is automatically reclaimed, but in 5 minutes? I had minio running for days and nothing got reclaimed.

That is not possible @paulpaul1076 - can you explain further how you observed the usage?

**Comment by paulpaul1076** [comment]
@harshavardhana started the official docker container, created a bucket as described in this post, uploaded data in there, around 5gb or more, removed this bucket, the disk usage on my computer doesn't go down.

**Comment by paulpaul1076** [comment]
Hello, did you have a chance check this? @harshavardhana
