### ISSUE TITLE
Unable to delete a bucket with empty folders

### ISSUE THREAD

**Issue by naveenragamoini** [minio/minio#18340]
Hi,

When I tried to remove the bucket using mc rb --force myminio/bucket-name with files in it. I ran into Resource requested is unwritable, Please reduce request rate error. Then, I manually deleted all the folders from console and used rm command to delete the folders and now all the folders are empty. When I am trying to the use the same command "mc rb --force myminio/bucket-name" It is giving me the same error "Please reduce request rate". FYI I am using the latest version of Minio. I went through the other froums where there was similar kind of issues but none worked. Please find the below logs fro reference.

{
 "status": "error",
 "error": {
  "message": "Failed to remove `myminio/bucket-name`.",
  "cause": {
   "message": "Resource requested is unwritable, please reduce your request rate",
   "error": {
    "Code": "SlowDownWrite",
    "Message": "Resource requested is unwritable, please reduce your request rate",
    "BucketName": "central-region-flood-studies",
    "Key": "",
    "Resource": "/bucket-name/",
    "RequestID": "1792C21ADC1909F5",
    "HostID": "1dddc2873e47f9c08980a09ed48e35083587eddd0c7baf040e5d47da1f8731b9",
    "Region": "",
    "Server": "MinIO"
   }
  },
  "type": "fatal"
 }
}

**Comment by harshavardhana** [comment]
`mc rm --force --purge myminio/bucket-name/folders/` and then `mc rb --force myminio/bucket-name/`

**Comment by naveenragamoini** [comment]
Thanks. Its Working!!!

**Comment by cbfischer** [comment]
> `mc rm --force --purge myminio/bucket-name/folders/` and then `mc rb --force myminio/bucket-name/`

In a replicated environment (site replication Active/Active), DC1 and DC2, we tried to delete a bucket with ~86 million objects, using `mc rm --force dc1/bucket`. 

After deletion, several folders remained empty in the bucket. Different folders on each side. Approximately 60 folders. 

I run `mc rm --force --purge dc1/bucket/folders` and `mc rm --force --purge dc2/bucket/folders`.

On both sides, the folders are now empty, nothing appears using the graphical interface, nor command line.

However, when trying to delete the bucket through the graphical interface, the error "**Not Empty**" returns. 

Using MC:
mc: <ERROR> Failed to remove `dc2/bucket`. **The specified method is not allowed against this resource.**

Version: 2023-11-06T22:26:08Z
Red Hat Enterprise Linux release 9.2 (Plow)

**Comment by wuyudian1** [comment]
@cbfischer   This problem still exists in RELEASE.2024-03-05T04-48-44Z

**Comment by wuyudian1** [comment]
@harshavardhana  this problem still exists in RELEASE.2024-03-05T04-48-44Z

**Comment by harshavardhana** [comment]
Folders are not empty if you do versioned deletes it will create delete markers not actually delete the object.

Learn about replication and versioning first before you invest your time in these features.
