### ISSUE TITLE
Not able to download the file from MinIO if the file name contains some special characters and other language characters(Except English)

### ISSUE THREAD

**Issue by leelakk19** [minio/minio#18347]
We are not able to download the file from MinIO if the file name contains some special characters and other language characters(Except English). I have attached the error thrown in JS console of MinIO page.

Example file names:
1.	SH上海叶水福报价.pdf
2.	ทาสีทั้งหมด (2014-10-20 ลดเหลือ 20k).png

Error thrown:
(Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.at sr (https://minio.xyz.com/static/js/main.e81f26fe.chunk.js:1:282107))

minio version used: 2021-10-13T00:23:17Z
OS and version used: RHEL 8.6

Is there a limitation in minio object naming? Any reference KB for that? please assist, much thanks in advance. 

![minioerror](https://github.com/minio/minio/assets/107595060/abfdc445-7bdd-4fe9-89c8-3f01a24f4c2a)

**Comment by jiuker** [comment]
Could you use the latest version to test？  @leelakk19

**Comment by leelakk19** [comment]
@jiuker thank you for quick response 
If there is no other way I will update and get back with my findings here

**Comment by harshavardhana** [comment]
There is no other fix here, you need to use latest release.
