### ISSUE TITLE
mc throws ObjectLockConfiguration missing error despite it being configured

### ISSUE THREAD

**Issue by VerdantForge** [minio/minio#18350]
When copying a bucket from a remote server to a local one running docker using the `mc` command

```bash
mc cp -r qa/dataset local/dataset
```

I get the following error on each of the objects in the bucket

```bash
mc: <ERROR> Failed to copy `https://****/dataset/file.csv`. Bucket is missing ObjectLockConfiguration
```

I don't have this issue with any other bucket on the machine.
The bucket is configured as follows:

![image](https://github.com/minio/minio/assets/123564396/cd740c68-24c9-4a58-bf8e-5d8461cec9d9)

The only difference between the buckets seems to be that the problematic one is versioned.

Here is the configuration of a bucket from which I can copy with no issues

![image](https://github.com/minio/minio/assets/123564396/a6cab8a0-a484-41db-b7ee-ac8de22ddf8a)

## Your Environment
* QA environment 
```
minio version RELEASE.2023-07-11T21-29-34Z (commit-id=9885a0a6afd80ad5669297ec750cdfa05126e674)
Runtime: go1.19.11 linux/amd64
```

* LOCAL environment
```
minio --version
minio version RELEASE.2023-07-11T21-29-34Z (commit-id=9885a0a6afd80ad5669297ec750cdfa05126e674)
Runtime: go1.19.11 linux/amd64
```

* mc
```
mc --version
mc version RELEASE.2023-09-28T17-48-30Z (commit-id=103272612aee8ae1a3256ede90e2190111069d51)
Runtime: go1.21.1 linux/amd64
```

**Comment by harshavardhana** [comment]
@VerdantForge how many node setup is this?

**Comment by harshavardhana** [comment]
can you share the output of `mc admin info` ?

**Comment by VerdantForge** [comment]
> can you share the output of `mc admin info` ?

```
 mc admin info qa
●  ****
   Uptime: 2 weeks
   Version: 2023-07-11T21:29:34Z
   Network: 1/1 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

50 GiB Used, 8 Buckets, 51,707 Objects, 10 Versions
1 drive online, 0 drives offline
```

```
mc admin info local
●  localhost:9000
   Uptime: 2 hours
   Version: 2023-07-11T21:29:34Z
   Network: 1/1 OK
   Drives: 1/1 OK
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 1

27 GiB Used, 8 Buckets, 969 Objects
1 drive online, 0 drives offline
```

**Comment by harshavardhana** [comment]
The error is because I think your destination bucket doesn't have object locking enabled however you have enabled object locking on the source.

if you want to do `mc cp -r` that automatically preserves the metadata from source to destination you need to make sure both sides have the same configuration.

**Comment by VerdantForge** [comment]
> The error is because I think your destination bucket doesn't have object locking enabled however you have enabled object locking on the source.
> 
> if you want to do `mc cp -r` that automatically preserves the metadata from source to destination you need to make sure both sides have the same configuration.

Ah yes I've created my local bucket using `--with-lock` and it works fine now.  I find the error message confusing though since it never mentions my local bucket but only the remote file, leading me to believe the problem was on that side.
