### ISSUE TITLE
Upgrade HTTP Protocols

### ISSUE THREAD

**Issue by kurtisane** [minio/minio#18358]
**Is your feature request related to a problem? Please describe.**
Performance

**Describe the solution you'd like**
Upgrade to newer/better HTTP Protocols
HTTP/2.0 (really important is h2c since most of the cases MinIO is accessed by server applications [https://datatracker.ietf.org/doc/html/rfc7540#section-3.1](url)) 
HTTP/3 

**Additional context**
Since HTTP/2 is already couple of years old and QUIC/HTTP 3 is getting a more and more traction I find it kinda sad to not have the benefits with MinIO.

Maybe I'm missing something but is there no plans to support those protocols ? 

I'm deploying MinIO behind a Traefik reverse-proxy and so h2c is also quite important to not have the TLS overhead. I think a bunch of people have these situations as well.

**Comment by klauspost** [comment]
We have not found HTTP/2 to provide any measurable difference, and it has proven very unreliable in production usage. HTTP/3 is UDP and likely to provide even more headaches. TLS does not pose any significant overhead if your reverse proxy supports keep-alive. So it is an active choice and we have no current plan of supporting either. 

You are welcome to experiment on adding it on the edge if your clients benefit from it.
