### ISSUE TITLE
Unable to activate TLS in single node

### ISSUE THREAD

**Issue by loganmzz** [minio/minio#18357]
`minio server https://myhost/var/minio/data/test` fails with:

```
ERROR Invalid command line arguments: use path style endpoint for single node setup
      > Please check the endpoint
      HINT:
        Single-Node modes requires absolute path without hostnames:
      Examples:
         $ minio server /data/minio/ #Single Node Single Drive
         $ minio server /data-{1...4}/minio # Single Node Multi Drive
```

## Expected Behavior

Starts server with HTTPS endpoints

## Current Behavior

```
ERROR Invalid command line arguments: use path style endpoint for single node setup
      > Please check the endpoint
      HINT:
        Single-Node modes requires absolute path without hostnames:
      Examples:
         $ minio server /data/minio/ #Single Node Single Drive
         $ minio server /data-{1...4}/minio # Single Node Multi Drive
```

## Possible Solution

Looks like invalid regex. Works fine if I give two URLs (except other host can't be joined, and resulting in invalid cluster)

## Steps to Reproduce (for bugs)

`minio server https://localhost/var/minio/data/test`

## Context

Unable to setup secured endpoints with a single node deployment.

## Regression

Not tested

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-08-29T23-07-35Z (commit-id=07b1281046c8934c47184d1b56c78995ef960f7d)`
* Server setup and configuration: Nothing
* Operating System and version (`uname -a`): Linux RHEL 8 x64

**Comment by vadmeste** [comment]
@loganmzz the error is saying that if you are going to use one disk in your deployment, you do not have to use any http address as argument, just /var/minio/data/test is enough

**Comment by loganmzz** [comment]
> @loganmzz the error is saying that if you are going to use one disk in your deployment, you do not have to use any http address as argument, just /var/minio/data/test is enough

@vadmeste doing so doesnt enable TLS. Or may have miss another setting ?
 Whatever its not what TLS documentation say (https://min.io/docs/minio/linux/operations/network-encryption.html):

> Update MINIO_VOLUMES and any needed services or apps to use an HTTPS URL.

**Comment by brammeleman** [comment]
running into the same problem. Minio says:

```
FATAL Invalid command line arguments: use path style endpoint for single node setup
      > Please check the endpoint
      HINT:
        Single-Node modes requires absolute path without hostnames:
      Examples:
         $ minio server /data/minio/ #Single Node Single Drive
         $ minio server /data-{1...4}/minio # Single Node Multi Drive
```

Does it mean I can't setup a single-node minio with https?

Also [this page](https://min.io/docs/minio/linux/integrations/generate-lets-encrypt-certificate-using-certbot-for-minio.html#) is hinting that it should work, provided links to or copies from the lets encrypt certificates.

**Comment by marktheunissen** [comment]
@brammeleman MinIO starts in TLS mode when the certs are found in $HOME/.minio/certs directory. You can easily setup single-node just make sure the certs are in place.

**Comment by marktheunissen** [comment]
Docs here: https://min.io/docs/minio/linux/operations/network-encryption.html
