### ISSUE TITLE
CURL is no more available in latest docker image.

### ISSUE THREAD

**Issue by dsuhinin** [minio/minio#18378]
## Expected Behavior
`curl` or `wget` has to be available inside that container to make it possible to do a `healthcheck`.

## Current Behavior
in the latest image there is no `curl` or `wget` command.

## Possible Solution
get back `curl` or `wget`.

## Steps to Reproduce (for bugs)
1. pull latest image
2. run container.
3. inside the latest container run -> `curl -f http://localhost:9000/minio/health/live`

**Comment by jiuker** [comment]
https://github.com/minio/minio/issues/18373 check out this. @dsuhinin

**Comment by dsuhinin** [comment]
> #18373 check out this. @dsuhinin

thank you a lot!
