### ISSUE TITLE
healthcheck in docker-compose example incorrect, and curl is removed from docker image and cannot be used for healthcheck.

### ISSUE THREAD

**Issue by snazzer** [minio/minio#18389]
## Expected Behavior
In the example docker-compose file at [docs/orchestration/docker-compose/docker-compose.yaml](https://github.com/minio/minio/blob/8953f88780e2dca654a6d9e1a15f5a470b334860/docs/orchestration/docker-compose/docker-compose.yaml#L14), the health check looks like 

```
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
```

However, in recent images, curl isn't included because the base image in the docker doesn't have it:
```
$ docker run -it --rm --entrypoint curl quay.io/minio/minio:RELEASE.2023-11-01T18-37-25Z
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown.
```

Additionally, the docker-compose has incorrect health check usage, which is why it appears like this works - but it doesn't. The compose file should actually ensure the `service_healthy`. Without this condition health check just means container started is ok.

Suggestion:
```
diff --git a/docs/orchestration/docker-compose/docker-compose.yaml b/docs/orchestration/docker-compose/docker-compose.yaml
index f6d8eb467..7fdc3a362 100644
--- a/docs/orchestration/docker-compose/docker-compose.yaml
+++ b/docs/orchestration/docker-compose/docker-compose.yaml
@@ -57,10 +57,14 @@ services:
       - "9000:9000"
       - "9001:9001"
     depends_on:
-      - minio1
-      - minio2
-      - minio3
-      - minio4
+      minio1:
+        condition: service_healthy
+      minio2:
+        condition: service_healthy
+      minio3:
+        condition: service_healthy
+      minio4:
+        condition: service_healthy```
```

## Current Behavior
See above

## Possible Solution

Either
* include curl in the image
* adjust the healthcheck to use maybe `mc admin info local` as the health check, but it requires authorization. 

## Steps to Reproduce (for bugs)

See description above

## Context

We use minio in a local dev environment, which relies in containers coming up in sequence for the setup. E.g. need minio to come up before preparing data to be pushed into it.

## Regression
Yes, removal of the curl from the image means I have to downgrade image or remove the health check in our own docker-compose

The change to use a minimal, ubi-micro base image probably caused this.

We are currently pinning to `quay.io/minio/minio:RELEASE.2023-10-25T06-33-25Z` in order to have a version with curl.

**Comment by harshavardhana** [comment]
Please use `mc ready local`

**Comment by snazzer** [comment]
> Please use `mc ready local`

Thanks! note that the docs probably should be fixed.

**Comment by harshavardhana** [comment]
It's being updated in the PR #18386

**Comment by mihasia20008** [comment]
> Please use `mc ready local`

@harshavardhana Is it possible to run this command for server, that runs on non-default port?

**Comment by harshavardhana** [comment]
> > Please use `mc ready local`
> 
> @harshavardhana Is it possible to run this command for server, that runs on non-default port?

Set container env

MC_HOST_custom=http://localhost:<favorite_port>

mc ready custom
