### ISSUE TITLE
XL: NoSuchBucket error and bucket never comes back

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1838]
While `mc cp` in progress, a disk is removed, we get NoSuchBucket and the bucket never comes back even after restart.

Steps to reproduce
1. run `mc cp -r` at one end.
2. run `rm -fr /path/to/disk` at another end.

minio version

```
Version: 2016-06-02T16:48:22Z
Release-Tag: DEVELOPMENT.2016-06-02T16-48-22Z
Commit-ID: de21126f7e0565105b467134da16d01465e0c7ac
```

**Comment by harshavardhana** [comment]
This will be fixed by #1832
