### ISSUE TITLE
Webhook not being sent anymore if the link has been cut 

### ISSUE THREAD

**Issue by TheOignon** [minio/minio#18390]
## NOTE

We are simulating a bit the whole webhook interaction and noticed that if our backend for webhook is down at some point, the events are not being sent even after webhook listener being up again.

## Expected Behavior

Webhook event are being sent nicely when the listener is back online / available.

## Current Behavior

Nothing is sent.

## Steps to Reproduce (for bugs)

1. Create some kind of webhook listener (like this one : https://github.com/minio/webhook)
2. Up it and make it available
3. Create the config to send the notify_webhook to point to it
4. See that there's traffic coming in the webhook listener
5. Kill it / restart it
6. Nothing is visible until the Minio cluster / server is restarted

## Context

We don't have any event notification anymore if the link to the tool listening for webhook is down at some point and need manual intervention to restart the cluster

## Your Environment

* Version used (`minio --version`): RELEASE.2023-10-25T06-33-25Z
* Server setup and configuration: 
* Operating System and version (`uname -a`):

**Comment by Praveenrajmani** [comment]
I'll test this today, do you have any server logs that can be shared? @TheOignon

**Comment by Praveenrajmani** [comment]
I wasn't able to reproduce this issue. This is what i did

- Start MinIO
 
```sh
MINIO_CI_CD=1` MINIO_ROOT_USER=minio MINIO_ROOT_PASSWORD=minio123 ./minio server /tmp/disknew{1...4}
```

- Run the webhook server

```sh
➜  webhook git:(main) ./webhook --log-file /tmp/webhooklog.txt
```

- Configure notify_webhook

```sh
>  mc admin config set myminio notify_webhook:1 enable=on endpoint=http://localhost:8080/
>  mc admin service restart myminio
```

- Configure bucket notifications

```sh
> mc event add myminio/testnew arn:minio:sqs::1:webhook
```

and copy some objects in the bucket, you will see some events

- Kill the webhook and start it again
- Copy some more objects and still saw events logged in the log file

**Comment by TheOignon** [comment]
Good day,

Sorry for the delay of response. I'll try your scenario to see what's the behavior on my side. Please note that even though it shouldn't matter, we are using the docker images.
I'll keep you posted anyway.

**Comment by TheOignon** [comment]
Hi,

Seems that it was an issue on our side. Nothing to worry about.
We'll close the issue.
