### ISSUE TITLE
Bucket notification event missing after MinIO restart for target with queue dir

### ISSUE THREAD

**Issue by mctoohey** [minio/minio#18404]
We have a Kafka target configured with a queue directory and are subscribing to PUT object events for all objects on a particular bucket. We have observed that sometimes on a restart of MinIO it is possible for an event to never make it into the queue and is never sent by MinIO to the target.

I ran the following python script to upload 1000 objects sequentially to MinIO in an empty bucket `test_bucket`. `test_file.txt` is a 1 byte file.

```python
from minio import Minio

minio_client = Minio(
    "<minio api endpoint>",
    access_key="<access key>",
    secret_key="<secret>",
    secure=False
)

for i in range(1, 1001):
    minio_client.fput_object('test_bucket', 'test_object' + str(i), "test_file.txt")
```

While this is running I restart MinIO with `mc admin service restart <alias>`.
Then occasionally observe the following error  in the loop.
```
S3Error                                   Traceback (most recent call last)
Cell In[11], line 2
      1 for i in range(1, 1001):
----> 2     minio_client.fput_object('test_bucket', 'test_object' + str(i), "test_file.txt")

File python3.8/site-packages/minio/api.py:998, in Minio.fput_object(self, bucket_name, object_name, file_path, content_type, metadata, sse, progress, part_size, num_parallel_uploads, tags, retention, legal_hold)
    996 file_size = os.stat(file_path).st_size
    997 with open(file_path, "rb") as file_data:
--> 998     return self.put_object(
    999         bucket_name, object_name, file_data, file_size,
   1000         content_type=content_type,
   1001         metadata=metadata, sse=sse, progress=progress,
   1002         part_size=part_size, num_parallel_uploads=num_parallel_uploads,
   1003         tags=tags, retention=retention, legal_hold=legal_hold,
   1004     )

File python3.8/site-packages/minio/api.py:1794, in Minio.put_object(self, bucket_name, object_name, data, length, content_type, metadata, sse, progress, part_size, num_parallel_uploads, tags, retention, legal_hold)
   1790 if upload_id:
   1791     self._abort_multipart_upload(
   1792         bucket_name, object_name, upload_id,
   1793     )
-> 1794 raise exc

File python3.8/site-packages/minio/api.py:1748, in Minio.put_object(self, bucket_name, object_name, data, length, content_type, metadata, sse, progress, part_size, num_parallel_uploads, tags, retention, legal_hold)
   1745 uploaded_size += len(part_data)
   1747 if part_count == 1:
-> 1748     return self._put_object(
   1749         bucket_name, object_name, part_data, headers,
   1750     )
   1752 if not upload_id:
   1753     upload_id = self._create_multipart_upload(
   1754         bucket_name, object_name, headers,
   1755     )

File python3.8/site-packages/minio/api.py:1595, in Minio._put_object(self, bucket_name, object_name, data, headers, query_params)
   1592 def _put_object(self, bucket_name, object_name, data, headers,
   1593                 query_params=None):
   1594     """Execute PutObject S3 API."""
-> 1595     response = self._execute(
   1596         "PUT",
   1597         bucket_name,
   1598         object_name,
   1599         body=data,
   1600         headers=headers,
   1601         query_params=query_params,
   1602         no_body_trace=True,
   1603     )
   1604     return ObjectWriteResult(
   1605         bucket_name,
   1606         object_name,
   (...)
   1609         response.headers,
   1610     )

File python3.8/site-packages/minio/api.py:421, in Minio._execute(self, method, bucket_name, object_name, body, headers, query_params, preload_content, no_body_trace)
    418 region = self._get_region(bucket_name)
    420 try:
--> 421     return self._url_open(
    422         method,
    423         region,
    424         bucket_name=bucket_name,
    425         object_name=object_name,
    426         body=body,
    427         headers=headers,
    428         query_params=query_params,
    429         preload_content=preload_content,
    430         no_body_trace=no_body_trace,
    431     )
    432 except S3Error as exc:
    433     if exc.code != "RetryHead":

File python3.8/site-packages/minio/api.py:404, in Minio._url_open(self, method, region, bucket_name, object_name, body, headers, query_params, preload_content, no_body_trace)
    401 if response_error.code in ["NoSuchBucket", "RetryHead"]:
    402     self._region_map.pop(bucket_name, None)
--> 404 raise response_error

S3Error: S3 operation failed; code: ClientDisconnected, message: Client disconnected before response was ready, resource: /test_bucket/test_object137, request_id: 179587E3DF012445, host_id: 6cd5cec3ec73296278caaa4a7658cc7ec6599e05849be7b07cc8da906ea3aebc, bucket_name: test_bucket, object_name: test_object137
```
The error failed on the PUT request for `test_object137`. However checking MinIO shows that 137 objects are in the bucket and `test_object137` does exist in the bucket. Kafka only received PUT events for objects 1 to 136. So in this situation we have an object that was uploaded to MinIO but the PUT event notification never made it to the target (even after MinIO came back up). It seems like it probably wasn't persisted to the queue.

## Expected Behavior
If an object has been uploaded to MinIO. The put event for that object should be persisted into the queue on disk and eventually be sent to the target. Even if MinIO is restarted.

## Current Behavior
Sometimes it seems like an event can go missing during the restart.

## Steps to Reproduce (for bugs)

1. Start MinIO and configure it with a Kafka target that has queue_dir set.
2. Create a bucket "test_bucket" and make sure it is empty. Configure it to publish PUT object events to the Kafka target.
3. Run the previously mentioned python script that sequentially puts 1000 objects onto MinIO.
4. While the above script is running restart MinIO with `mc admin service restart <alias>`
5. Observe that occasionally the number of objects in the "test_bucket" is different to the number of PUT event notifications received by the Kafka topic.

## Context

Its possible that if an object is uploaded to MinIO while a restart occurs. The bucket notification that should be generated by this object will never reach its target and external services that rely on this will never receive it.

## Regression

Unsure

## Your Environment

* Version used (`minio --version`): `RELEASE.2023-11-01T18-37-25Z`
* Server setup and configuration: Distributed 3 server setup with 4 drives per server 
* Operating System and version (`uname -a`): `Linux minio-ss-1-1 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Praveenrajmani** [comment]
Hi @mctoohey 

Due to the aynchronous nature of the bucket notification mechanism, you may loose some events on restarts. You can set `export MINIO_API_SYNC_EVENTS=on` for making the events synchronous. You can also set this via mc - `mc admin config set <alias> api sync_events=on`

Also, make sure you don't have `_MINIO_DISABLE_API_FREEZE_ON_BOOT` env set.

**Comment by mctoohey** [comment]
Hi @Praveenrajmani 

Thank you for your response. I'm not sure we would want `MINIO_API_SYNC_EVENTS` as it is a global setting for all targets and we would probably only want to do this for targets that write to a queue (as the send call will be very fast in that case).

It's also not clear to me if enabling `MINIO_API_SYNC_EVENTS` would actually help. In the example I gave the client never received a response for uploading `test_object137` even though it was successfully uploaded to MinIO successfully. To me this indicates that the `PutObjectHandler` method did not complete and `sendEvent` may never have been called.

**Comment by Praveenrajmani** [comment]
> In the example I gave the client never received a response for uploading test_object137 even though it was successfully uploaded to MinIO successfully.

If the client doesn't receive a response or if it receives an error response, then the API itself is not complete and there is no guarantee that the object got uploaded successfully.

By default, the events are sent asynchronously and the API response will be written back the client even before the events are published to the targets / persisted in `queue_dir`. With `sync_events` on, the API response will be returned only when the event has been successfully published/persisted. So, if the clients see a 200 OK response for an API, this means the corresponding event is successfully persisted/published.

So, if the servers are restarting, the asynchronous threads cancel out and there is a possibility to miss the events. So, making it synchronous will be useful here.

**Comment by mctoohey** [comment]
Even if we make event notifications synchronous the fact an operation could complete on an object and no notification be sent is not ideal for our use case. Particularly for delete requests.

For example (even with synchronous notifications). If a delete request is made on an object as the server is restarted. It is possible that the object is deleted but the client does not receive a response and no notification is sent. Now we are in a situation where the object is deleted but the client and external services relying on the notification think the object still exists.

If this is the expected behaviour of MinIO then this issue can be closed and I will continue to explore alternative ways of reducing the likelihood of losing events on restart.

**Comment by harshavardhana** [comment]
This requires a different kind of implementation internally because the persistence of objects and notification of events are two separate things that work independently.

The way this can be only ever done is via SYNC_EVENTS which is the whole purpose of this implementation.  We do not return success unless we have persisted in the events.

Like somehow we should be able to even send events if we wrote while the server is shutting down, is simply not possible to do cleanly without overly complicating things. You can try implementing one yourself in a distributed setup you would see the real challenges.

MinIO is not an SQS service of some kind and it doesn't provide those guarantees without asking for delivery guarantees. That is why there is an option to get those delivery guarantees via synchronous event notification.
