### ISSUE TITLE
{ldap:username} in policies treated case-sensitive

### ISSUE THREAD

**Issue by stephanbertl** [minio/minio#18416]
We have a MINIO instance connected to Active Directory LDAP. Works fine so far, however there is an issue with ldap:username substitution. Our LDAP server returns usernames as **uppercase**, eg "DOEJ"

When using the following policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::user-data"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::user-data"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "${ldap:username}/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::user-data/${ldap:username}/*"
            ]
        }
    ]
}
```

## Expected Behavior

We would expect to the LDAP user to have access to their home directory that is written in any case, eg. "user-data/doej".

## Current Behavior

The policy doesn't apply correctly if the directory name isn't the **exact same case** as the {ldap:username}.

**user-data/DOEJ** works ok
**userdata/doej** doesnt.

We can get around this by using the correct casing in the directory names.

**However, when applying an {ldap:username} policy for a whole bucket we are stuck, because bucket names can only be lowercase.**

## Possible Solution
* convert LDAP username to lower-case or compare the values case-insensitive.

## Your Environment
* minio operator with 1 tenant running minio/minio:RELEASE.2023-10-07T15-07-38Z

**Comment by harshavardhana** [comment]
Yes that is expected since the resources are case sensitive.

**Comment by stephanbertl** [comment]
@harshavardhana how can it be fixed. We cannot create buckets for users that have upper case usernames. Uppercase isn't allowed.

I don't believe that we should ignore this. It creates brittleness.

**Comment by harshavardhana** [comment]
> @harshavardhana how can it be fixed. We cannot create buckets for users that have upper case usernames. Uppercase isn't allowed.
> 
> I don't believe that we should ignore this. It creates brittleness.

Uppercase is not allowed for buckets thats just the way things are.

Objects are case sensitive we cannot change that either that can lead to security issues.

You have to simply make sure that your ldap username matches with what kind of objects your users upload and they are required to keep the case sensitivity for the matching folders.
