### ISSUE TITLE
Resource name contains bad components such as &#34;..&#34; or &#34;.&#34;.

### ISSUE THREAD

**Issue by olegantonyan** [minio/minio#18421]
I'm trying to host apt repository on Minio and run into problem. Not sure if this is bug or feature request.

Here's an example repository I've made on Google cloud: https://storage.googleapis.com/repotestubuntu2204
I can add it to the sources.list as follows:
```
deb [trusted=yes allow-insecure=yes] https://storage.googleapis.com/repotestubuntu2204/ /
```
and it will work, that is running `apt update && apt install sample-project` is successful.

But when the same files hosted on local Minio, apt gives an error upon install:
```
root@user-VirtualBox:~# apt install sample-project
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  sample-project
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2502 B of archives.
After this operation, 23,6 kB of additional disk space will be used.
Err:1 http://10.0.2.2:9000/ubuntu2204  sample-project 1.3.5-0
  400  Bad Request [IP: 10.0.2.2 9000]
E: Failed to fetch http://10.0.2.2:9000/ubuntu2204/./sample-project_1.3.5-0_amd64.deb  400  Bad Request [IP: 10.0.2.2 9000]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

The file `http://10.0.2.2:9000/ubuntu2204/./sample-project_1.3.5-0_amd64.deb` is perfectly reachable, that is I can open this url in a browser, or wget it. But both browsers and wget seem to do the trick - they remove `./`, while apt does not. And this leads to the request (captured via wireshark):
```
GET /ubuntu2204/./sample-project_1.3.5-0_amd64.deb HTTP/1.1\r\n
```
which receives a 400 response:
```
    <?xml
        version="1.0"
        encoding="UTF-8"
        ?>
    <Error>
        <Code>
            XMinioInvalidResourceName
            </Code>
        <Message>
            Resource name contains bad components such as &#34;..&#34; or &#34;.&#34;.
            </Message>
        <Resource>
            /ubuntu2204/./sample-project_1.3.5-0_amd64.deb
            </Resource>
        <RequestId>
            17963BF174D2AF93
            </RequestId>
        <HostId>
            dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
            </HostId>
        </Error>
```

Google cloud seems to swallow `./` in request path, but not Minio.
As a workaround I can probably use nginx in front and remove `./`. Or play around with apt repo structure to get rid of `./`. But the difference between Google cloud and Minio makes me think of this as a bug, or at least a feature that should be considered. Didn't try AWS though. 

```
$ ~/.go/bin/minio --version
minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```
installed via go get on openSUSE Tumbleweed
Linux zenbook 6.5.9-1-default #1 SMP PREEMPT_DYNAMIC Wed Oct 25 10:31:37 UTC 2023 (29edc7c) x86_64 x86_64 x86_64 GNU/Linux
Examples apt on Ubuntu 22.04 and 23.10 in VirtualBox

**Comment by klauspost** [comment]
`.` does not make sense on a filesystem level as a folder name. See https://min.io/docs/minio/kubernetes/upstream/operations/concepts/thresholds.html#object-name-limitations

If this is fixed in the application, you will need to rewrite the path.

**Comment by olegantonyan** [comment]
That's how `apt` works. I believe it's hardcoded there.
And while it doesn't make a lot of sense, it also doesn't make any harm as far as I know. `cat /proc/./cpuinfo` is equal to `cat /proc/cpuinfo` when accessing filesystem.

Traversing the filesystem upward via `..` is a common attack vector when you allow to get files directly from filesystem so someone can get `../../../etc/shadow` or something like that. But I'm not aware of any harm possible by accessing `./`
