### ISSUE TITLE
Remove directory fails using SFTP

### ISSUE THREAD

**Issue by mh-ambition-dk** [minio/minio#18434]
Looks like rmdir reports failure when using SFTP even though the directory appear to be removed.

Here is what happens using the "sftp" client:
```
mfh@slice:~$ sftp test@host
test@host's password:
Connected to host.
sftp> cd test/mfh
sftp> mkdir test_dir
sftp> ls
test_dir
sftp> rmdir test_dir
Couldn't remove directory: Failure
sftp> ls
sftp> quit
```

**Comment by zveinn** [comment]
@mh-ambition-dk thanks for reporting!

There should be a fix on it's way.

**Comment by mh-ambition-dk** [comment]
Beautiful! Thanks!
