### ISSUE TITLE
How to use nginx path proxy minio address?

### ISSUE THREAD

**Issue by llody55** [minio/minio#18436]
# nginx.conf
`
server {
        listen       8083;
        listen       [::]:8083;
        server_name  _;
        #root         /usr/share/nginx/html;
        location / {
          root         /usr/share/nginx/html;
        }
        location /oss/ {
            proxy_set_header Host $http_host;
            proxy_pass http://192.168.111.130:9000/;
        }
}
`

How to operate the http://192.168.111.130:9000 interface through the http://192.168.111.130:8083/oss/ path?
I tried to use python script to test and got an error
# minio.py
`
from minio import Minio
from minio.error import S3Error

def main():
    client = Minio(
        "192.168.111.130:8083/oss/",
        access_key="",
        secret_key="",
        secure=False
    )

    objects = client.list_objects("test", recursive=True)
    for obj in objects:
        print(obj.object_name)

if __name__ == "__main__":
    try:
        main()
    except S3Error as exc:
        print("Error occurred:", exc)
`
# error
`
secure=False
  File "C:\Users\llody\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\api.py", line 132, in __init__
    region,
  File "C:\Users\llody\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\helpers.py", line 399, in __init__
    raise ValueError("path in endpoint is not allowed")
ValueError: path in endpoint is not allowed
Exception ignored in: <function Minio.__del__ at 0x000002206DA0A948>
Traceback (most recent call last):
  File "C:\Users\llody\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\api.py", line 155, in __del__
    self._http.clear()
AttributeError: 'Minio' object has no attribute '_http'

`

**Comment by harshavardhana** [comment]
S3 API cannot be hosted on custom paths, paths are resources on object storage you can't come up with arbitrary relative endpoints.
