### ISSUE TITLE
backup bucket of minio to bucket of aws s3

### ISSUE THREAD

**Issue by SmileCaoJ** [minio/minio#18431]
**Is your feature request related to a problem? Please describe.**
backup local storage to public cloud
such as, backup bucket of minio to bucket of aws s3？

**Describe the solution you'd like**
should minio support  backup bucket to other storage？

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
https://min.io/docs/minio/linux/administration/batch-framework.html

**Comment by SmileCaoJ** [comment]
thx
