### ISSUE TITLE
Unable to delete a bucket with empty folders

### ISSUE THREAD

**Issue by vicmunoz** [minio/minio#18444]
Hi, 

Despite removing all objects from bucket and removing the bucket, still is displayed via mc and ui.

```
# mcli ls local
[2023-10-09 11:10:53 UTC]     0B other_bucket/
[0001-01-01 00:00:00 UTC]     0B images-replica/
# mcli ls local/images-replica/
mcli: <ERROR> Unable to list folder. The specified bucket does not exist
# mcli ls local/images-replica
mcli: <ERROR> Unable to list folder. Bucket `images-replica` does not exist.
#
```
In UI, under Administrator-Buckets is still showed and when I click on it it show a red banner on top with message 'The specified bucket does not exist'

How can completely purge the bucket references?

**Comment by klauspost** [comment]
Are you running the latest version?

**Comment by vicmunoz** [comment]
more or less... 
minio version RELEASE.2023-09-07T02-05-02Z (commit-id=703ed46d79bba51d5d781e2297ca0216c99c8536)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

**Comment by harshavardhana** [comment]
Please upgrade to latest release and let us know how it goes @vicmunoz

**Comment by jiuker** [comment]
Can you upload your data catalogue? I think there should be files in there that don't belong to minio, we ran into a similar scenario before. @vicmunoz

**Comment by vicmunoz** [comment]
@jiuker I don't know if you mean this with data catalogue:
```
# ls -l /var/lib/minio/ -a
total 10276
drwxr-xr-x      4 minio minio      51 Nov 14 12:40 .
drwxr-xr-x     43 root  root     4096 Oct  2 12:56 ..
drwxr-xr-x      8 minio minio     148 Nov  1 08:44 .minio.sys
drwxr-xr-x 153212 minio minio 8712192 Nov 13 13:21 other_bucket
# ls -l /var/lib/minio/.minio.sys/
total 4
drwxr-xr-x 3 minio minio  44 Nov 13 13:48 batch-jobs
drwxr-xr-x 8 minio minio 166 Nov 15 09:57 buckets
drwxr-xr-x 4 minio minio  48 Sep 29 14:54 config
-rw-r--r-- 1 minio minio 381 Sep 29 14:54 format.json
drwxr-xr-x 2 minio minio   6 Oct 30 10:59 multipart
drwxr-xr-x 2 minio minio  21 Oct  9 15:25 pool.bin
drwxr-xr-x 3 minio minio 108 Nov 15 09:57 tmp
# ls -l /var/lib/minio/.minio.sys/buckets/
total 0
drwxr-xr-x 3 minio minio 30 Nov 15 01:39 images-replica
drwxr-xr-x 4 minio minio 51 Nov 15 01:39 other_bucket
# ls -l /var/lib/minio/.minio.sys/buckets/images-replica/ -a
total 0
drwxr-xr-x 3 minio minio  30 Nov 15 01:39 .
drwxr-xr-x 8 minio minio 166 Nov 15 09:57 ..
drwxr-xr-x 2 minio minio  29 Nov 15 01:39 .usage-cache.bin
```

**Comment by vicmunoz** [comment]
> Please upgrade to latest release and let us know how it goes @vicmunoz

Is there any bugfix in recent versions that could be related?

**Comment by jiuker** [comment]
> > Please upgrade to latest release and let us know how it goes @vicmunoz
> 
> Is there any bugfix in recent versions that could be related?

No, so you need to update your data.

**Comment by jiuker** [comment]
zip `/var/lib/minio/` , and upload to here @vicmunoz

**Comment by vicmunoz** [comment]
> zip `/var/lib/minio/` , and upload to here @vicmunoz

I can't upload entire /var/lib/minio here, there is sensitive data in the other_bucket

**Comment by jiuker** [comment]
You make a new cluster to reproduce it. @vicmunoz

**Comment by harshavardhana** [comment]
> > Please upgrade to latest release and let us know how it goes @vicmunoz
> 
> Is there any bugfix in recent versions that could be related?

Community users are expected to report issues with latest releases only. If there is a problem we fix it with latest releases.

So you must upgrade first to see if it's a problem still. There are many fixes that go in weekly - it may or may not have been already addressed.

If you have a mission critical deployment then you should consider getting official support via https://min.io/pricing

**Comment by vicmunoz** [comment]
i'm not able to reproduce it. I'll move to recreate this zoombie bucket and use it for other purposes :(
