### ISSUE TITLE
Silently fails when specific passwords are specified for a MinIO container through environment variables.

### ISSUE THREAD

**Issue by dontcrash** [minio/minio#18441]
### UPDATE: Solved, read comment below

I followed the guide as per these instructions [https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html) and can connect to it locally but not from other machines through my Nginx proxy. I get "The request signature we calculated does not match the signature you provided. Check your key and signing method."

![image](https://github.com/minio/minio/assets/32660358/729af603-aa90-4dee-9258-f32c0bdba8b2)

## Expected Behavior

It should log me in.

## Current Behavior

It shows an error message.

## Possible Solution

Possible issue with Nginx config in guide?

## Steps to Reproduce (for bugs)

1. Deploy MinIO on a VM, 172.16.0.2
2. Use your existing Nginx proxy at 172.16.0.3
3. Attempt to access it from a web browser.

## Context

I ensured that the environment variables were set:
MINIO_SERVER_URL=https://storage.domain.tld
MINIO_BROWSER_REDIRECT_URL=https://storage.domain.tld/minio/ui

## Regression

Unsure, have seen many people referencing issues such as this with no real solution. I did note this in the config guide but this is not the case  here "The S3 API signature calculation algorithm does not support proxy schemes where you host the MinIO Server API such as example.net/s3/."

## Your Environment

Two separate Debian 12 virtual machines.
One hosts MinIO, the other hosts my Nginx proxy for LAN.

```nginx
server {

    listen 443 ssl;
    server_name storage.domain.tld;

    http2  on;

    ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;

    allow 172.16.0.0/12;
    deny all;

    # Allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # Disable buffering
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;

       proxy_connect_timeout 300;
       # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
       proxy_http_version 1.1;
       proxy_set_header Connection "";
       chunked_transfer_encoding off;

       proxy_pass http://172.16.0.2:9000;
    }

    location /minio/ui/ {
       rewrite ^/minio/ui/(.*) /$1 break;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-NginX-Proxy true; 

       # This is necessary to pass the correct IP to be hashed
       real_ip_header X-Real-IP; 

       proxy_connect_timeout 300;

       # To support websockets in MinIO versions released after January 2023
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       # Some environments may encounter CORS errors (Kubernetes + Nginx Ingress)
       # Uncomment the following line to set the Origin request to an empty string
       # proxy_set_header Origin '';

       chunked_transfer_encoding off;

       proxy_pass http://172.16.0.2:9090;
   }

}
```

The guide does not mention if the Nginx proxy must be deployed on the same VM/instance as MinIO.
In my usage I have MinIO on one VM and my Nginx proxy on a different VM as this proxy is used for everything internally.

**Comment by dontcrash** [comment]
So this was a weird one, the default password I attempted to use was randomly generated from my password manager, it was originally set to "wE87yy%eZnet77T@PMcifdC$TVYxsrhMed7Z^M9xYfiTESjsYN2cZcv^enUm%o"
Docker created the MinIO container and it said it was listening etc, but would silently fail with the above error message.
I have decided not to close this issue yet as I am thinking there needs to be some changes to documentation regarding password requirements, as clearly I have hit some edge case here.
I am now using a password that consists of a-zA-Z0-9 and it works as expected.

**Comment by harshavardhana** [comment]
> So this was a weird one, the default password I attempted to use was randomly generated from my password manager, it was originally set to "wE87yy%eZnet77T@PMcifdC$TVYxsrhMed7Z^M9xYfiTESjsYN2cZcv^enUm%o" Docker created the MinIO container and it said it was listening etc, but would silently fail with the above error message. I have decided not to close this issue yet as I am thinking there needs to be some changes to documentation regarding password requirements, as clearly I have hit some edge case here. I am now using a password that consists of a-zA-Z0-9 and it works as expected.

what is your MinIO version? @dontcrash

**Comment by dontcrash** [comment]
> > So this was a weird one, the default password I attempted to use was randomly generated from my password manager, it was originally set to "wE87yy%eZnet77T@PMcifdC$TVYxsrhMed7Z^M9xYfiTESjsYN2cZcv^enUm%o" Docker created the MinIO container and it said it was listening etc, but would silently fail with the above error message. I have decided not to close this issue yet as I am thinking there needs to be some changes to documentation regarding password requirements, as clearly I have hit some edge case here. I am now using a password that consists of a-zA-Z0-9 and it works as expected.
> 
> what is your MinIO version? @dontcrash

Latest, pulled from docker, published four days ago.

Pulled from quay.io/minio/minio

**Comment by harshavardhana** [comment]
And how are you specifying these environment variables?

**Comment by zveinn** [comment]
@dontcrash hello!

I've tested this with your exact password and I can not replicate the problem. Can you re-test and double check your pasting in the right password ? Also, make sure you are using the user/pass authentication instead of STS. It sometimes happens that users accidentally switch over without noticing.

**Comment by harshavardhana** [comment]
Closing this as not actionable, looks like a user side configuration issue.

**Comment by dontcrash** [comment]
> @dontcrash hello!
> 
> I've tested this with your exact password and I can not replicate the problem. Can you re-test and double check your pasting in the right password ? Also, make sure you are using the user/pass authentication instead of STS. It sometimes happens that users accidentally switch over without noticing.

Apologies on the delay, have been busy the last few days.

Here is the exact command I ran:

```bash
sudo docker run \
   -p 9000:9000 \
   -p 9090:9090 \
   --name minio \
   -v ~/minio/data:/data \
   -e "MINIO_ROOT_USER=minio" \
   -e "MINIO_ROOT_PASSWORD=wE87yy%eZnet77T@PMcifdC$TVYxsrhMed7Z^M9xYfiTESjsYN2cZcv^enUm%o" \
   quay.io/minio/minio server /data --console-address ":9090"
```

When changing the password to something simpler such as "Abc123!" it would work, I suspect one of these characters was breaking either the hash function of passwords or the storage of it etc.
Could be the $ symbol.

**Comment by zveinn** [comment]
Try encapsulating the MINIO_ROOT_PASSWORD with '
When docker applies the -e variables it might use a bash command to do so, which could be problematic.

**Comment by harshavardhana** [comment]
You should create `docker secret` and then use that instead via `MINIO_ROOT_USER_FILE` and `MINIO_ROOT_PASSWORD_FILE` for complex passwords that require escaping. 

MinIO has no control over it until it gets the value into the environment variable.
