### ISSUE TITLE
Missing Libz library - aws cli necessary for temporary credentials

### ISSUE THREAD

**Issue by rpudlowski93** [minio/minio#18448]
## Expected Behavior

I would like to install aws cli in order to retrieve temporary credentials. It is follow up for issue: 18121

## Current Behavior
I can not install aws cli since new minio image is missing libz library. 

## Steps to Reproduce (for bugs)

1.run minio with RELEASE.2023-11-01T01-57-10Z
2.install aws cli
3.error with loading Libz.so.1 no such file or directory
4.

## Context
I need to copy some objects to S3 without using aws secret and access key. I can do it but I need to retrieve temporary credentials to Aws. Aws cli is necessary.

## Your Environment

**Comment by harshavardhana** [comment]
Same answer as before #18447

**Comment by robert-pudlowski-mox** [comment]
@harshavardhana please check answer from my side.

**Comment by harshavardhana** [comment]
> @harshavardhana please check answer from my side.

I did I replied with new mc support for rotating credentials directly.
