### ISSUE TITLE
Missing Libz library on latest releases od minio.

### ISSUE THREAD

**Issue by rpudlowski93** [minio/minio#18447]
## Expected Behavior
I would like to install Aws Cli on minio container

## Current Behavior
I am not able to install aws cli on minio container using latest minio image.

Missing Libz.so.1 library

## Steps to Reproduce (for bugs)
1. Run minio with REALEASE.2023-11-01T01-57-10Z
2. Install aws cli
3. Error with : error while loading libraries: libz.so.1 cannot open shared object file: No such file or directory 
4.

## Context
I need to have aws cli on minio container. It was working on previous versions. Probably it is issue with missing libraries on RHel 9

## Your Environment
Minio version: REALEASE.2023-11-01T01-57-10Z

**Comment by harshavardhana** [comment]
You cannot install random programs inside  MinIO container image.

We ship `mc` as part of MinIO container which satisfies all your requirements.

**Comment by rpudlowski93** [comment]
@harshavardhana it was already mentioned that MC doesn't support AWS Iam role for moving old objects and in order to do that we need to install aws cli in order to obtain aws temporary credentials and use the MC ENV. We can't use aws secret and access key...

**Comment by robert-pudlowski-mox** [comment]
@harshavardhana  it is follow up for https://github.com/minio/minio/issues/18121#issuecomment-1741791971

How can I retrieve temp credentials via scripting without AWS CLI?

**Comment by harshavardhana** [comment]
> @harshavardhana it was already mentioned that MC doesn't support AWS Iam role for moving old objects and in order to do that we need to install aws cli in order to obtain aws temporary credentials and use the MC ENV. We can't use aws secret and access key...

mc does support temporary credentials via token file now

https://github.com/minio/mc/pull/4744

**Comment by robert-pudlowski-mox** [comment]
@harshavardhana  it is just for Minio Access, but we need to use the temporary credentials for S3 service. Am I wrong?

**Comment by harshavardhana** [comment]
> @harshavardhana it is just for Minio Access, but we need to use the temporary credentials for S3 service. Am I wrong?

No it is for AWS S3 as well 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-oidc

Looks like one thing might be missing here, that we need to add.
