### ISSUE TITLE
Error information in MinIO log messages are showing vague/not useful information

### ISSUE THREAD

**Issue by mshanmu** [minio/minio#18456]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

A vague and not useful error is logged instead of providing the real cause of the problem. Thereby, making it very hard to debug the issue. See below for some examples,

```
{"level":"ERROR","errKind":"ALL","time":"2023-11-07T13:34:57.428816377Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/storage-rest-client.go:171:cmd.(*storageRESTClient).call()","cmd/storage-rest-client.go:608:cmd.(*storageRESTClient).ReadAll()","cmd/format-erasure.go:391:cmd.loadFormatErasure()","cmd/format-erasure.go:327:cmd.loadFormatErasureAll.func1()","github.com/minio/pkg/v2@v2.0.2/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()"]}}
```

Notice, there is a stack trace, but the error message says "***fmt.wrapError**" instead of providing a useful error message.

```
{"level":"ERROR","errKind":"ALL","time":"2023-11-07T13:34:57.444334758Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*errors.errorString","source":["internal/logger/logger.go:258:logger.LogIf()","cmd/prepare-storage.go:254:cmd.connectLoadInitFormats()","cmd/prepare-storage.go:294:cmd.waitForFormatErasure()","cmd/erasure-server-pool.go:104:cmd.newErasureServerPools()","cmd/server-main.go:976:cmd.newObjectLayer()","cmd/server-main.go:718:cmd.serverMain.func9()","cmd/server-main.go:434:cmd.bootstrapTrace()","cmd/server-main.go:716:cmd.serverMain()"]}}
```
Notice, there is a stack trace, but the error message says **"*errors.errorString"** instead of providing a useful error message.

```
{"deploymentid":"75de14ae-d613-4f00-ad71-65c43b936305","level":"ERROR","errKind":"ALL","time":"2023-11-07T13:35:12.677034804Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/lock-rest-client.go:64:cmd.(*lockRESTClient).callWithContext()","cmd/lock-rest-client.go:96:cmd.(*lockRESTClient).restCall()","cmd/lock-rest-client.go:115:cmd.(*lockRESTClient).Lock()","internal/dsync/drwmutex.go:470:dsync.lock.func1()"]}}
```
Notice, there is a stack trace, but the error message says **"*fmt.wrapError"** instead of providing a useful error message.

Also, another suggestion instead of providing hash values for bucket, object and remotehost, It would be really helpful to provide the real name of bucket and object.

Is there any workaround, i.e., any option to go back to the old style?

## Expected Behavior

The real cause of the problem.

## Current Behavior

Vague and not useful information. 

## Steps to Reproduce (for bugs)

1. Setup a MinIO operator and create a tenant
2. Do "kubectl logs -f <minio pod name>"
3. See error messages with no useful information
4.

## Context

Troubleshoot the MinIO issues

## Regression

No idea, only thing I can remember, pre-json log messages, I used to see the error messages 

## Your Environment

* Version used (`minio --version`): RELEASE.2023-11-06T22-26-08Z
* Server setup and configuration: k8s
* Operating System and version (`uname -a`): CentOS 7/Redhat EL9

**Comment by mshanmu** [comment]
More examples,

```
{"deploymentid":"75de14ae-d613-4f00-ad71-65c43b936305","level":"ERROR","errKind":"ALL","time":"2023-11-07T13:35:13.253939393Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logger.go:248:logger.LogAlwaysIf()","cmd/prepare-storage.go:51:cmd.glob..func9.1()","cmd/erasure-sets.go:229:cmd.(*erasureSets).connectDisks.func2()"]}}

{"deploymentid":"75de14ae-d613-4f00-ad71-65c43b936305","level":"ERROR","errKind":"ALL","time":"2023-11-07T13:35:13.722949842Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*fmt.wrapError","source":["internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:149:logger.LogOnceIf()","internal/rest/client.go:319:rest.(*Client).Call()","cmd/peer-rest-client.go:68:cmd.(*peerRESTClient).callWithContext()","cmd/peer-rest-client.go:53:cmd.(*peerRESTClient).call()","cmd/peer-rest-client.go:106:cmd.(*peerRESTClient).LocalStorageInfo()","cmd/notification.go:998:cmd.(*NotificationSys).StorageInfo.func1()"]}}

```

**Comment by mshanmu** [comment]
Just to provide some context. As you know, kubernetes is complex environment and various types of issues are very common in this environment. Like CoreDNS not working or Calico not working properly or infrastructure pieces failing etc.,

In this situation, if we don't know the **specific error** like DNS resolution failed or connection refused, it is unbelievably hard to figure out whether it is MinIO or kubernetes infrastructure issue and how to resolve it.

**Comment by mshanmu** [comment]
Btw, You guys are doing great work providing stable and robust MinIO software. Thanks for that !!

**Comment by harshavardhana** [comment]
Looks like you are using helm to deploy the tenant which used to have the default `anonymous: true` enabled which is why the errors and object/bucket names are hidden.

Just remove it and redeploy you will start seeing non anonymous logs. This is only true with helm based deployment that used to incorrectly enable it by default.

**Comment by mshanmu** [comment]
Thanks, @harshavardhana !! Will try that out.
