### ISSUE TITLE
SFTP home dir per user

### ISSUE THREAD

**Issue by Tipsmark** [minio/minio#18468]
Hi guys, SFTP has improved a lot lately,but I struggle with setting a homedir for a given user. 
I would like user1 to start in bucketA/folder and not be able to see anything in a higher level.

Thank you

**Comment by klauspost** [comment]
@Tipsmark We have no plans for this. MinIO will never be an "sftp server". It will be an S3 server where you have a few options to access data via SFTP for legacy apps.

**Comment by Tipsmark** [comment]
> @Tipsmark We have no plans for this. MinIO will never be an "sftp server". It will be an S3 server where you have a few options to access data via SFTP for legacy apps.

Fair enough - is there some workaround that can be applied? can buckets be hidden from a user?

**Comment by klauspost** [comment]
@Tipsmark It is my understanding that bucket policies are applied.
