### ISSUE TITLE
nginx reverse proxy minio, the console  ui does not display bucket information

### ISSUE THREAD

**Issue by zerotocode398** [minio/minio#18469]
1. Problem
   I use the nginx reverse proxy minio, where the console port is 9000 and the api port is 19999. The web ui port is accessible, but the bucket and other information are empty.。
   
![image](https://github.com/minio/minio/assets/31309558/a995f11f-04d3-462d-b9c1-f64d701fc905)
![image](https://github.com/minio/minio/assets/31309558/6c22990d-b275-4522-950b-3330b3914c52)

2. nginx.conf
```shell
server {
  listen 5057;

  location /minio/ui/ {
    rewrite ^/minio/ui/(.*) /$1 break;
    proxy_pass http://10.2.2.12:9000;
  }
}
```
3. Minio ENV
```shell
export MINIO_DOMAIN=storagex
export MINIO_ROOT_USER=root
export MINIO_ROOT_PASSWORD=123456
export MINIO_SERVER_URL= http://10.2.2.12:9000
export MINIO_BROWSER_REDIRECT_URL=http://10.2.2.12:9000/minio/ui
```
How do I fix this
There is also a question, does nginx reverse proxy minio bucket support the use of external.url

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

We have an existing document that walks through what is necessary to reverse proxy MinIO Console + S3 API using nginx. Can you follow through with that? 

Do buckets exist if you use `mc ls`? What version of MinIO are you using?

The console isn't otherwise showing any errors. So there's not much for us to go on. If you can provide more information we can dig further.

**Comment by harshavardhana** [comment]
> ```shell
> server {
>   listen 5057;
> 
>   location /minio/ui/ {
>     rewrite ^/minio/ui/(.*) /$1 break;
>     proxy_pass http://10.2.2.12:9000;
>   }
> }
> ```

You should only keep this to `/minio` not `/minio/ui`

**Comment by harshavardhana** [comment]
> ```shell
> ```shell
> export MINIO_BROWSER_REDIRECT_URL=http://10.2.2.12:9000/minio/ui
> ```


and this is not needed - I am unable to follow which documentation are you following.

**Comment by zerotocode398** [comment]
> https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
> 
> We have an existing document that walks through what is necessary to reverse proxy MinIO Console + S3 API using nginx. Can you follow through with that?
> 
> Do buckets exist if you use `mc ls`? What version of MinIO are you using?
> 
> The console isn't otherwise showing any errors. So there's not much for us to go on. If you can provide more information we can dig further.

I didn't go into enough detail

web ui with nginx reverse proxy is ok，i want to show bucket with use external.ui，not localtion "/"，eg: location "/buckets" 

mc version && I already executed it mc policy set public with all buckets
```shell
[root@app1 ~]# mc --version
mc version RELEASE.2022-07-15T09-20-55Z (commit-id=48e9183957fce660dcc32a36bbee6f3ee4a9d0e9)
Runtime: go1.18.4 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
[root@app1 ~]# mc ls minio
[0001-01-01 08:05:43 LMT]     0B account-session-rules/
[0001-01-01 08:05:43 LMT]     0B api-auth-rules/
[0001-01-01 08:05:43 LMT]     0B api-risk-rules/
[0001-01-01 08:05:43 LMT]     0B api-tag-rules/
[0001-01-01 08:05:43 LMT]     0B db-backup/
[0001-01-01 08:05:43 LMT]     0B entity-rules/
[0001-01-01 08:05:43 LMT]     0B flink-job/
[0001-01-01 08:05:43 LMT]     0B risk-rules/
[0001-01-01 08:05:43 LMT]     0B schemax/
[0001-01-01 08:05:43 LMT]     0B seedx/
[0001-01-01 08:05:43 LMT]     0B src-ip-rules/
[0001-01-01 08:05:43 LMT]     0B test/
[2023-11-14 11:04:46 CST]     0B thanos-rules/
[0001-01-01 08:05:43 LMT]     0B vuln-risk-rules/
[0001-01-01 08:05:43 LMT]     0B xudf/
```

**Comment by zerotocode398** [comment]
> ```shell
> ```shell
> export MINIO_BROWSER_REDIRECT_URL=http://10.2.2.12:9000/minio/ui
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

if i delete this: export MINIO_BROWSER_REDIRECT_URL=http://10.2.2.12:9000/minio/ui

start minio errors: 
/etc/profile.d/storagex.sh: line 4: export: `http://10.2.2.20:9000': not a valid identifier

[root@app1 ~]# more /etc/profile.d/storagex.sh 
export MINIO_DOMAIN=storagex
export MINIO_ROOT_USER=root
export MINIO_ROOT_PASSWORD=H4ah8ajxna
export MINIO_SERVER_URL= http://10.2.2.20:9000
export MINIO_BROWSER_REDIRECT_URL=http://10.2.2.20:9000/minio

**Comment by zerotocode398** [comment]
> https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
> 
> We have an existing document that walks through what is necessary to reverse proxy MinIO Console + S3 API using nginx. Can you follow through with that?
> 
> Do buckets exist if you use `mc ls`? What version of MinIO are you using?
> 
> The console isn't otherwise showing any errors. So there's not much for us to go on. If you can provide more information we can dig further.

if i reverse proxy with bucket，return xml page
```shell
server {
  listen       5063;
  location /seedx {
     proxy_pass http://10.2.2.20:19999;
  }

   location /minio/ {
      rewrite ^/minio/(.*) /$1 break;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-NginX-Proxy true;

      real_ip_header X-Real-IP;

      proxy_connect_timeout 300;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      chunked_transfer_encoding off;

      proxy_pass http://10.2.2.20:9000;
   }
}
```
![image](https://github.com/minio/minio/assets/31309558/a50a2bf1-976e-44bc-a922-f2333937b59b)
