### ISSUE TITLE
minio/minio:RELEASE.2023-11-15T22-45-58Z.fips fails with mc: <ERROR> `server` is not a recognized command.

### ISSUE THREAD

**Issue by heapifyman** [minio/minio#18463]
Latest fips image [minio/minio:RELEASE.2023-11-15T22-45-58Z.fips](https://hub.docker.com/layers/minio/minio/RELEASE.2023-11-15T22-45-58Z.fips/images/sha256-ce70f6c5cba732b3c457189e8d91c7332b2e4f957b6dca32ccda97ebc90b0c7b?context=explore) does not start.

## Expected Behavior

minio should start up without problems

## Current Behavior

minio fails with error message:

> mc: <ERROR> `server` is not a recognized command. Get help using `--help` flag. 

## Steps to Reproduce (for bugs)

1. Run the example command from https://hub.docker.com/r/minio/minio: `podman run -p 9000:9000 -p 9001:9001 minio/minio:RELEASE.2023-11-15T22-45-58Z.fips  server /data --console-address ":9001"`

## Regression

Probably, because version `minio/minio:RELEASE.2023-11-15T20-43-25Z.fips` seems to start up without problems.

## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2023-11-15T22-45-58Z.fips
* Server setup and configuration: see "Steps to Reproduce (for bugs)"
* Operating System and version (`uname -a`): `Linux latitude5420 6.6.1-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Nov  9 04:27:49 UTC 2023 x86_64 GNU/Linux`

**Comment by jiuker** [comment]
Checked. Thanks.

**Comment by harshavardhana** [comment]
This was a release script mistake, this is being fixed.
