### ISSUE TITLE
Error: /bin/sh: line 1: `microdnf`: command not found

### ISSUE THREAD

**Issue by praneethratna** [minio/minio#18473]
Hi, 
Since the November 1st release `microdnf install git` is giving the error `/bin/sh: line 1: microdnf: command not found` in  [echopype](https://github.com/OSOceanAcoustics/echopype) docker builds. How could we resolve this build error? Is it due to `microdnf` not being used in `minio/minio` anymore?

Here is the complete docker file for which the build is failing - 
```
FROM minio/minio
ARG TARGETPLATFORM

# Install git
RUN microdnf install git

CMD ["minio", "server", "/data"]
``` 
## Expected Behavior
Running `microdnf install git` should have worked without any errors and `git` should been installed successfully. Link to the last successful build - https://github.com/OSOceanAcoustics/echopype/actions/runs/6713927590/job/18246339903.

## Current Behavior
Running `microdnf install git` gives an error `/bin/sh: line 1: microdnf: command not found` and the docker build is failing which is blocking the development of `echopype`. Link to failure build https://github.com/OSOceanAcoustics/echopype/actions/runs/6898099172/job/18767503536.

## Steps to Reproduce (for bugs)
Provided the required links above for failure and success cases.

## Context
Docker Builds are failing in `echopype` package and due to which latest test data is not being fetched.

**Comment by harshavardhana** [comment]
We do not allow adding new tools and binaries into MinIO container anymore.

**Comment by praneethratna** [comment]
@harshavardhana thank you for the clarification!

**Comment by harshavardhana** [comment]
MinIO base image is now RedHat UBI compatible scratch containers - they do not allow adding any new packages.

So anything that is not related to MinIO is not included.
