### ISSUE TITLE
Remove a File based on name across all the folders in minio

### ISSUE THREAD

**Issue by naveenragamoini** [minio/minio#18478]
Hi Team,

When I was tranferring files from a Web URL to Minio. There was a html.temp file created to maintain folder structure. This file is created across all the folders. Now, I want to delete this file with its name in all the folders of the bucket. Seems that it is not possible not now. I need to navigate to each folder and sub folder to delete the file. If this is already present, Kindly provide me the command. 

Thanks,
Naveen

**Comment by kannappanr** [comment]
@naveenragamoini There isn't a command like that. If you know the paths of all these objects from the weburl, you can use DeleteMultipleObjects API and delete upto 1000 objects at a time.
