### ISSUE TITLE
【Q】Does the minio support changing the default language accessed through the browser?

### ISSUE THREAD

**Issue by bczhaoa** [minio/minio#18488]
I have deployed this version of minio:minio/minio:RELEASE.2023-11-15T20-43-25Z, using Docker. When I access minio:minio/minio:RELEASE.2023-11-15T20-43-25Z, from a browser, the default language is English. Can I change the default language to Chinese using Docker parameters?

**Comment by harshavardhana** [comment]
The product is English language based. There is no multi language support.

**Comment by hhywl** [comment]
> The product is English language based. There is no multi language support.

Are there any plans to provide multilingual support?

**Comment by harshavardhana** [comment]
> 
> Are there any plans to provide multilingual support?

Its a significant work, not at the moment.
