### ISSUE TITLE
[Bucket Notification] Make maxConcurrentTargetSendCalls configurable

### ISSUE THREAD

**Issue by fangzhouxie** [minio/minio#18489]
**Is your feature request related to a problem? Please describe.**
Currently maxConcurrentTargetSendCalls is hardcoded to 20,000. We sometimes exceed this limit, resulting in dropped bucket notifications.

**Describe the solution you'd like**
Make maxConcurrentTargetSendCalls configurable.

**Additional context**
I understand that this limit is initially added "to avoid consuming a lot of goroutines when a target is
very slow or there is a bug in a target library" (https://github.com/minio/minio/pull/15435), and that "MinIO needs to handle goroutines as a valued resource for its day to day operations". But I also think it would be nice to allow users to change this limit at their own risks.

**Comment by fangzhouxie** [comment]
bumping this one - can we make maxConcurrentTargetSendCalls configurable and default to 20,000?

**Comment by harshavardhana** [comment]
@fangzhouxie there is no SLA for community issues .

If it's urgent please work on it yourself and send a pull request. Always happy to accept reasonable patches.

**Comment by harshavardhana** [comment]
Closing this issue

> Currently maxConcurrentTargetSendCalls is hardcoded to 20,000. We sometimes exceed this limit, resulting in dropped bucket notifications.

You are already exceeding this means that your notification endpoint is slow to process 20,000 concurrent operations, you should fix that first. 

This value is per node if you have 10 nodes this value is 200,000 so this is more than sufficient for any realistic scenario, we can change this to any other arbitrary value but it won't fix anything.

**Comment by fangzhouxie** [comment]
> Closing this issue
> 
> > Currently maxConcurrentTargetSendCalls is hardcoded to 20,000. We sometimes exceed this limit, resulting in dropped bucket notifications.
> 
> You are already exceeding this means that your notification endpoint is slow to process 20,000 concurrent operations, you should fix that first.
> 
> This value is per node if you have 10 nodes this value is 200,000 so this is more than sufficient for any realistic scenario, we can change this to any other arbitrary value but it won't fix anything.

@harshavardhana Thanks for your reply. We are currently tuning our bucket notification setup to make it less likely to exceed the goroutine limit. If it still happens quite frequently for us, I will send a pull request.
