### ISSUE TITLE
[Bucket Notification] Remove maxBatchLimit

### ISSUE THREAD

**Issue by fangzhouxie** [minio/minio#18490]
**Is your feature request related to a problem? Please describe.**
The [Kafka batch send change](https://github.com/minio/minio/pull/18164) is awesome! But it limits Kafka batch send size to 100 due to `maxBatchLimit`. With 100 Kafka batch send size, our bucket notifications with queues can easily be delayed for 30 minutes when there are a large amount of events (this happens quite frequently for us due to our usage pattern). It would be great if we can configure a larger Kafka batch send size in order to achieve lower latency for bucket notifications with queues.

**Describe the solution you'd like**
Remove `maxBatchLimit`.

**Additional context**
I saw previous discussions about maxBatchLimit in https://github.com/minio/minio/pull/18164#discussion_r1346944423. I do agree that users should be advised to configure a reasonable batch send size, but I don't think it's necessary to enforce a limit on it. I think users should be able to configure a much larger batch send size at their own risks, if they want.

**Comment by Praveenrajmani** [comment]
Relaxing this limit may lead to creation of too many go routines which are uncontrolled. We can set it to a higher and reasonable value perhaps. Will need some suggestions from @harshavardhana on this.

**Comment by harshavardhana** [comment]
> Relaxing this limit may lead to creation of too many go routines which are uncontrolled. We can set it to a higher and reasonable value perhaps. Will need some suggestions from @harshavardhana on this.

@Praveenrajmani what does Kafka generally recommend can you find out?

**Comment by fangzhouxie** [comment]
> > Relaxing this limit may lead to creation of too many go routines which are uncontrolled. We can set it to a higher and reasonable value perhaps. Will need some suggestions from @harshavardhana on this.
> 
> @Praveenrajmani what does Kafka generally recommend can you find out?

Thank you all for looking into this!

Out of my curiosity, why do we think number of go routines is correlated to Kafka batch send size?
- I went through the implementation on MinIO side, and I don't think they are correlated
- I also checked the implementation of `SyncProducer` in sarama, and I still don't think they are correlated

relevant implementation of `SyncProducer` in sarama
```go
func (sp *syncProducer) SendMessages(msgs []*ProducerMessage) error {
	expectations := make(chan chan *ProducerError, len(msgs))
	go func() {
		for _, msg := range msgs {
			expectation := make(chan *ProducerError, 1)
			msg.expectation = expectation
			sp.producer.Input() <- msg
			expectations <- expectation
		}
		close(expectations)
	}()

	var errors ProducerErrors
	for expectation := range expectations {
		if pErr := <-expectation; pErr != nil {
			errors = append(errors, pErr)
		}
	}

	if len(errors) > 0 {
		return errors
	}
	return nil
}
```

**Comment by Praveenrajmani** [comment]
yes, you're correct @fangzhouxie 

```go
go func() {
		for _, msg := range msgs {
			expectation := make(chan *ProducerError, 1)
			msg.expectation = expectation
			sp.producer.Input() <- msg
			expectations <- expectation
		}
		close(expectations)
	}()
```

I see that it only creates one go-routine and sends all the messages synchronously. 

so, it should be fine relaxing the limit. will send a fix.

**Comment by fangzhouxie** [comment]
> yes, you're correct @fangzhouxie
> 
> ```go
> go func() {
> 		for _, msg := range msgs {
> 			expectation := make(chan *ProducerError, 1)
> 			msg.expectation = expectation
> 			sp.producer.Input() <- msg
> 			expectations <- expectation
> 		}
> 		close(expectations)
> 	}()
> ```
> 
> I see that it only creates one go-routine and sends all the messages synchronously.
> 
> so, it should be fine relaxing the limit. will send a fix.

Thank you!
