### ISSUE TITLE
Allow / Propagate deletion of objects using mc batch

### ISSUE THREAD

**Issue by gogo199432** [minio/minio#18495]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up a backup solution using Minio as primary local storage and Backblaze B2 as backup target. The reason for this is that I'm using Minio as the filestore for my Nextcloud instance. As I have found out the replication in the GUI is only supported between minio-to-minio, so the next solution was the new Batch Framework. 

Using that I have managed to backup a test bucket to Backblaze. However if I delete the testobject inside my minio bucket and do the batch job again, the file remains on B2. If I then readd the same file to minio and do the batch job again, now I have the same file twice in B2 under the same name. (Not sure if this is the same as editing the file or not). 

**Describe the solution you'd like**
It would be nice to have a flag or something in the batch job that would allow me to propagate the actual state of my local bucket completely.

**Describe alternatives you've considered**
I wonder if it would be better to setup a second minio instance as a gateway to B2 locally and do minio-to-minio replication. Would this be feasable and easier than the solution above?

As it is today I'm backing up the actual minio volume on my disk as if it were just another folder to a B2 bucket. Is this a proper way to back up minio storage?

**Comment by harshavardhana** [comment]
@gogo199432 good idea but we have limited bandwidth here. Feel free to send a PR here if you need this functionality we are always happy to accept reasonable pull requests.
