### ISSUE TITLE
minio not load data after reboot linux server

### ISSUE THREAD

**Issue by quocnm102** [minio/minio#18507]
I run minio on linux server with one bucket and have many data. I reboot server because of upgrading ram. Then I start minio but I can't login in minio console link this issue https://github.com/minio/minio/issues/5222. I follow this and remove file .minio.sys/tmp and restart minio. So I can login the console. when I go to bucket, although the directory appear all data, the butket in console has no data.

this is log when I can't login minio console

> API: SYSTEM()
Time: 14:34:36 UTC 11/22/2023
Error: unable to rename (/home/l2c/minio/.minio.sys/tmp -> /home/l2c/minio/.minio.sys/tmp-old/e789540e-1f7b-4db8-9605-32c570824fc1) file access denied, drive may be faulty please investigate (*fmt.wrapError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/prepare-storage.go:89:cmd.bgFormatErasureCleanupTmp()
       4: cmd/xl-storage.go:263:cmd.newXLStorage()
       3: cmd/object-api-common.go:63:cmd.newStorageAPI()
       2: cmd/format-erasure.go:673:cmd.initStorageDisksWithErrors.func1()
       1: github.com/minio/pkg/v2@v2.0.2/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
API: SYSTEM()
Time: 14:34:36 UTC 11/22/2023
Error: drive:/home/l2c/minio, srcVolume: .minio.sys/tmp, srcPath: 26029c46-f360-49c0-9ba4-0a62ed6de6cf, dstVolume: .minio.sys:, dstPath: pool.bin - error file access denied (*errors.errorString)
       6: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       5: internal/logger/logonce.go:149:logger.LogOnceIf()
       4: cmd/xl-storage.go:2263:cmd.(*xlStorage).RenameData.func1()
       3: cmd/xl-storage.go:2519:cmd.(*xlStorage).RenameData()
       2: cmd/xl-storage-disk-id-check.go:484:cmd.(*xlStorageDiskIDCheck).RenameData.func1()
       1: internal/ioutil/ioutil.go:158:ioutil.(*DeadlineWorker).Run.func1()
API: SYSTEM()
Time: 14:34:36 UTC 11/22/2023
Error: file access denied (cmd.StorageErr)
      14: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
      13: internal/logger/logonce.go:149:logger.LogOnceIf()
      12: cmd/erasure-object.go:1335:cmd.erasureObjects.putObject()
      11: cmd/erasure-object.go:1015:cmd.erasureObjects.PutObject()
      10: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
       9: cmd/config-common.go:79:cmd.saveConfigWithOpts()
       8: cmd/config-common.go:84:cmd.saveConfig()
       7: cmd/erasure-server-pool-decom.go:471:cmd.poolMeta.save()
       6: cmd/erasure-server-pool-decom.go:517:cmd.(*erasureServerPools).Init()
       5: cmd/erasure-server-pool.go:157:cmd.newErasureServerPools()
       4: cmd/server-main.go:976:cmd.newObjectLayer()
       3: cmd/server-main.go:718:cmd.serverMain.func9()
       2: cmd/server-main.go:434:cmd.bootstrapTrace()
       1: cmd/server-main.go:716:cmd.serverMain()
API: SYSTEM()
Time: 14:34:36 UTC 11/22/2023
Error: saving pool.bin for pool index 0 failed with: Prefix access is denied: .minio.sys/pool.bin (*errors.errorString)
       8: internal/logger/logger.go:258:logger.LogIf()
       7: cmd/erasure-server-pool-decom.go:473:cmd.poolMeta.save()
       6: cmd/erasure-server-pool-decom.go:517:cmd.(*erasureServerPools).Init()
       5: cmd/erasure-server-pool.go:157:cmd.newErasureServerPools()
       4: cmd/server-main.go:976:cmd.newObjectLayer()
       3: cmd/server-main.go:718:cmd.serverMain.func9()
       2: cmd/server-main.go:434:cmd.bootstrapTrace()
       1: cmd/server-main.go:716:cmd.serverMain()
ERROR Unable to initialize backend: Prefix access is denied: .minio.sys/pool.bin

## Expected Behavior

show or load all data on physical directory to bucket on console

## Current Behavior

Although directory has all data, the console butket has no one.

## Steps to Reproduce (for bugs)

1. start minio
2. upload data
3. reboot server linux
4. start minio
5. go to minio console on browser

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2023-11-01T18-37-25Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): linux ubuntu 22.04

**Comment by harshavardhana** [comment]
Fix your drive permissions

**Comment by quocnm102** [comment]
![image](https://github.com/minio/minio/assets/89298427/cae451f6-105a-4d9e-a301-c280ed1e4765)
I set all data file full permissions, but some file are show, not all.

**Comment by quocnm102** [comment]
Sorry, I start minio with normal user (not root). I update data under root permission so minio doesn't show correctly. running minio by root perssion will resolve issue.
Thanks and appreciate for your support.

**Comment by klauspost** [comment]
You should fix permissions and not run as root.
