### ISSUE TITLE
Content-Type not being set properly when using Boto3

### ISSUE THREAD

**Issue by LivingInLimbo** [minio/minio#18509]
## Expected Behavior
Content-Type is set to the Content-Type that was passed passed into Boto3's `upload_file`, `upload_fileobj`, etc.

## Current Behavior
Content-Type is always set to `binary/octet-stream` even when explicitly passing Content-Type

## Possible Solution
Works with `mc cp ./bbt1.jpg minio_bucket/media --attr Content-Type='fake/mime'`

![image](https://github.com/minio/minio/assets/16964323/edc88da5-4e5d-43f5-92e5-89ae20678d7f)

But not when using similar Boto3 functions.

## Steps to Reproduce
```
client = boto3.client('s3', endpoint_url='https://localhost:9001', aws_access_key_id='development', aws_secret_access_key='development', verify=False)
with open('/home/shaunlyne/Pictures/bbt1.jpg', 'rb') as file:
    client.upload_fileobj(file, 'media', 'test', ExtraArgs={'ContentType':'image/png'})
```

## Context
Our production setup using Cloudflare doesn't have this issue with Boto3, hence why I'm posting here and not on Boto3's repo. The headers are being passed into Boto3 but are not being picked up by MinIO:

`2023-11-22 13:27:39,892 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=https://localhost:9001/media/test2, headers={'Content-Type': b'image/png', 'User-Agent': b'Boto3/1.29.5 md/Botocore#1.32.5 ua/2.0 os/linux#6.2.0-36-generic md/arch#x86_64 lang/python#3.10.12 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.5', 'Content-MD5': b'5XojINtKrkHFT3nOx6oW1g==', 'Expect': b'100-continue', 'X-Amz-Date': b'20231122T212739Z', 'X-Amz-Content-SHA256': b'UNSIGNED-PAYLOAD', 'Authorization': b'AWS4-HMAC-SHA256 Credential=development/20231122/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=0a3d872d62e873490a0da93f1ca82f9810b50fec92be22a2ce21e4b57a7e3823', 'amz-sdk-invocation-id': b'02e0b4f9-6f9a-4139-b67b-a00da460c736', 'amz-sdk-request': b'attempt=1', 'Content-Length': '256532'}>
`

![Screenshot from 2023-11-22 13-29-24](https://github.com/minio/minio/assets/16964323/3f977fa6-8e1b-49f2-a4f6-4465d06549eb)

![image](https://github.com/minio/minio/assets/16964323/f68f5342-7f7a-4db7-b32d-1b644f259d97)

## Your Environment

* Version used: minio/minio:RELEASE.2023-11-20T22-40-07Z
* Server setup and configuration: Docker container
* Operating System and version: Linux shaunlyne-XPS-9315 6.2.0-36-generic 22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Here is what I did 

```
minio server ~/test

mc mb local/testbucket
```

```py
import boto3

client = boto3.client('s3', endpoint_url='http://localhost:9000', aws_access_key_id='minioadmin', aws_secret_access_key='minioadmin', verify=False)
with open('README.md', 'rb') as file:
    client.upload_fileobj(file, 'testbucket', 'test', ExtraArgs={'ContentType':'image/png'})
```

```
python test.py
```

```
mc stat myminio/testbucket/test
Name      : test
Date      : 2023-11-22 13:52:52 PST 
Size      : 19 KiB 
ETag      : 9f21ae3fcf31058fd4779184cecfe1bf 
Type      : file 
Metadata  :
  Content-Type: image/png 
```

Looks like some local issue on your end. 

```
localhost:9000 [REQUEST s3.PutObject] [2023-11-22T13:54:15.523] [Client IP: 127.0.0.1]
localhost:9000 PUT /testbucket/test
localhost:9000 Proto: HTTP/1.1
localhost:9000 Host: localhost:9000
localhost:9000 Content-Md5: nyGuP88xBY/Ud5GEzs/hvw==
localhost:9000 Content-Type: image/png
localhost:9000 User-Agent: Boto3/1.24.2 Python/3.10.12 Linux/6.2.0-34-generic Botocore/1.27.2
localhost:9000 Amz-Sdk-Invocation-Id: 45318c61-2e36-43c6-840c-574e2a721f84
localhost:9000 Amz-Sdk-Request: attempt=1
localhost:9000 Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20231122/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=80b612188285d5762ca96403133fe4b751e6e8061833e07da4b3722188bb6881
localhost:9000 Content-Length: 19113
localhost:9000 Expect: 100-continue
localhost:9000 X-Amz-Content-Sha256: fd4e8df485d937f3f3e6eb0556b83b511f58592fad3989b289831c6d6861f062
localhost:9000 X-Amz-Date: 20231122T215415Z
localhost:9000 Accept-Encoding: identity
localhost:9000 <BLOB>
localhost:9000 [RESPONSE] [2023-11-22T13:54:15.536] [ Duration 13.286ms TTFB 0s ↑ 19 KiB  ↓ 0 B ]
localhost:9000 200 OK
localhost:9000 ETag: "9f21ae3fcf31058fd4779184cecfe1bf"
localhost:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:9000 Vary: Origin,Accept-Encoding
localhost:9000 X-Content-Type-Options: nosniff
localhost:9000 X-Xss-Protection: 1; mode=block
localhost:9000 Accept-Ranges: bytes
localhost:9000 Content-Length: 0
localhost:9000 Server: MinIO
localhost:9000 X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
localhost:9000 X-Amz-Request-Id: 179A10984887AEAD
localhost:9000 <BLOB>
localhost:9000 
```

**Comment by LivingInLimbo** [comment]
Thanks for the example, turns out it was a proxy that wasn't propagating the headers.
