### ISSUE TITLE
Deleted object still available from replica

### ISSUE THREAD

**Issue by atlasz911** [minio/minio#18506]
An object deleted from the primary cluster no longer shows up with "mc ls", but is still available when requested via API or "mc cp".

## Expected Behavior
When I delete an object from the cluster and it's not shown in the object listing, than it should no longer be available to download. Even if the object exists in another cluster, where it was replicated and still resides.

## Current Behavior
I remove the object from the primary cluster. It's not shown with "mc ls". "mc ls --versions" shows the previous versions, unless I used "mc rm --versions --force" (than no versions are available of course). When I reach directly for the object via API or "mc cp" command than the object appears to be picked up from the replica and transparently provided to the client.

This is similar to tiering, but much less obvious feature. I expected that an object deleted and removed from object list would not be available anymore.

## Possible Solution
If this is an intended behavior than there could be a new flag for --replicate "" to disable this feature.

## Steps to Reproduce (for bugs)
Attaching output of the script I used to reproduce the problem:

+ **cp -f ../teszt1.bin .**
+ **echo '# Upload to primary'**
**# Upload to primary**
+ **/opt/minio/bin/mc cp teszt1.bin t-minio-a/test/teszt1.bin**
/root/tmp/teszt1.bin:               16.00 KiB / 16.00 KiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.64 KiB/s 0s+ /opt/minio/bin/mc ls --versions t-minio-a/test/teszt1.bin
[2023-11-22 14:13:03 CET]  16KiB STANDARD 4416bf0d-dbf3-4503-835a-b3eb0b8a7362 v1 PUT teszt1.bin
+ **/opt/minio/bin/mc ls --versions t-minio-r/test/teszt1.bin**
[2023-11-22 14:13:03 CET]  16KiB STANDARD 4416bf0d-dbf3-4503-835a-b3eb0b8a7362 v3 PUT teszt1.bin
[2023-11-22 14:12:42 CET]     0B STANDARD add6c1dc-dafa-43f1-8816-7de07404f9a0 v2 DEL teszt1.bin
[2023-11-22 14:12:41 CET]  16KiB STANDARD 81b8f312-2955-4fea-aa7d-4fc79002783c v1 PUT teszt1.bin
+ echo '# Delete from primary check'
**# Delete from primary check**
+ **/opt/minio/bin/mc rm t-minio-a/test/teszt1.bin**
Created delete marker `t-minio-a/test/teszt1.bin` (versionId=6110cea9-7d7e-4039-a532-14a496986595).
+ **/opt/minio/bin/mc ls --versions t-minio-a/test/teszt1.bin**
[2023-11-22 14:13:03 CET]     0B STANDARD 6110cea9-7d7e-4039-a532-14a496986595 v2 DEL teszt1.bin
[2023-11-22 14:13:03 CET]  16KiB STANDARD 4416bf0d-dbf3-4503-835a-b3eb0b8a7362 v1 PUT teszt1.bin
+ **/opt/minio/bin/mc ls --versions t-minio-r/test/teszt1.bin**
[2023-11-22 14:13:03 CET]  16KiB STANDARD 4416bf0d-dbf3-4503-835a-b3eb0b8a7362 v3 PUT teszt1.bin
[2023-11-22 14:12:42 CET]     0B STANDARD add6c1dc-dafa-43f1-8816-7de07404f9a0 v2 DEL teszt1.bin
[2023-11-22 14:12:41 CET]  16KiB STANDARD 81b8f312-2955-4fea-aa7d-4fc79002783c v1 PUT teszt1.bin
+ **rm -f ./teszt1.bin**
+ **/opt/minio/bin/mc cp t-minio-a/test/teszt1.bin .**   ####### **This command should fail to retrieve data!** #######
...-bss.local:4443/test/teszt1.bin: 16.00 KiB / 16.00 KiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 396.50 KiB/s 0s+ echo '#Delete from replica check'
**#Delete from replica check**
+ **/opt/minio/bin/mc rm t-minio-r/test/teszt1.bin**
Created delete marker `t-minio-r/test/teszt1.bin` (versionId=b59bda46-80fb-4678-a204-45d74502eff4).
+ **/opt/minio/bin/mc ls --versions t-minio-a/test/teszt1.bin**
[2023-11-22 14:13:03 CET]     0B STANDARD 6110cea9-7d7e-4039-a532-14a496986595 v2 DEL teszt1.bin
[2023-11-22 14:13:03 CET]  16KiB STANDARD 4416bf0d-dbf3-4503-835a-b3eb0b8a7362 v1 PUT teszt1.bin
+ **/opt/minio/bin/mc ls --versions t-minio-r/test/teszt1.bin**
[2023-11-22 14:13:04 CET]     0B STANDARD b59bda46-80fb-4678-a204-45d74502eff4 v4 DEL teszt1.bin
[2023-11-22 14:13:03 CET]  16KiB STANDARD 4416bf0d-dbf3-4503-835a-b3eb0b8a7362 v3 PUT teszt1.bin
[2023-11-22 14:12:42 CET]     0B STANDARD add6c1dc-dafa-43f1-8816-7de07404f9a0 v2 DEL teszt1.bin
[2023-11-22 14:12:41 CET]  16KiB STANDARD 81b8f312-2955-4fea-aa7d-4fc79002783c v1 PUT teszt1.bin
+ **rm -f ./teszt1.bin**
+ **/opt/minio/bin/mc cp t-minio-a/test/teszt1.bin .** ####### **This command fails as expected.** #######
mc: <ERROR> Unable to prepare URL for copying. Unable to guess the type of copy operation.

## Context
My primary cluster is accessible to users to retrieve data generated and stored in the cluster. After a period defined in ILM the data is removed and should no longer be available to users but I still keep an archive copy for manual retrieval in case of need for legal or other reasons with a 2-3x longer ILM. In this situation users are able to retrieve the data they no longer should if they know the path and object name.

## Regression
No
Problem reproduced with older versions and also my latest  2023-11-06T22:26:08Z.

## Your Environment
Two Minio clusters with versioning enabled. Buckets with identical names with replication setup up in one direction only: t-minio-a -> t-minio-r
Replication set up by command:
mc replicate add t-minio-a/test --remote-bucket https://s3ReplicationRemoteUser:$pwd_s3ReplicationRemoteUser@$mc_srvR/test1 --id $ID1 --priority 10 --replicate "existing-objects"

The clusters intentionally does not replicate delete-markers and have different ILM configured. The replica cluster works as an archive. It holds the data much longer but that data should no longer be available to the users of the primary cluster.

minio version RELEASE.2023-11-06T22-26-08Z (commit-id=754f7a8a395e87a744050476d8b16c16af50a800)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

Linux t-minio-1 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 18:09:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"

**Comment by harshavardhana** [comment]
Your need to make sure to replicate deletes, if you do not then the object is unavailable locally we proxy the requests to replica.

You can turn off proxying enabled by default.

**Comment by atlasz911** [comment]
Incredible! Thank you very much for the quick answer! It solved my problem perfectly.
