### ISSUE TITLE
Enable encryption by default on all buckets using a specified key

### ISSUE THREAD

**Issue by jamie-pate** [minio/minio#18511]
**Is your feature request related to a problem? Please describe.**
When creating buckets the user needs to enable encryption after creating the bucket. This seems like a step that could be easily missed sometimes.

**Describe the solution you'd like**
I'd like a setting in the server that sets encryption to be 'always on' so all buckets are created with the default encryption key.

**Describe alternatives you've considered**
Any alternative would require some script or other frontend other than the MinIO Console

**Comment by harshavardhana** [comment]
Before starting MinIO enable

```
MINIO_KMS_AUTO_ENCRYPTION=on
```

To enable encryption on all buckets.

**Comment by jamie-pate** [comment]
I swear i searched really hard to find that :sob:

Any insight on why it's 'not recommended' ?

https://github.com/minio/minio/blob/master/docs/kms/README.md#using-environment-not-recommended

**Comment by harshavardhana** [comment]
> https://github.com/minio/minio/blob/master/docs/kms/README.md#using-environment-not-recommended

Because you would want to rely on bucket-level configuration instead, just like AWS S3.

**Comment by olljanat** [comment]
@harshavardhana is possible also configure MinIO in way that all new buckets would have separate encryption key?
