### ISSUE TITLE
Minio Operator Bucketdns Incorrect FQDN

### ISSUE THREAD

**Issue by mitchell-mann-tw** [minio/minio#18538]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I'm deploying a minio tenant with the Minio operator. However, when I enable Bucketdns in the values file, I get k8s dns records that do not match the documented behavior.
## Expected Behavior
The documentation states that the Minio service should be accessible at the following DNS record:

> bucket.minio.default.svc.cluster.local

## Current Behavior
I get the following DNS record:

> bucket.default.svc.cluster.local

Key being the "minio" is deleted.
I can confirm that when in a pod, bucket.minio.default.svc.cluster.local is not resolvable. This differs from the expected. 

## Steps to Reproduce (for bugs)

1. Deploy Minio operator
2. Deploy tenant with bucketdns enabled
3. Attempt to resolve bucket.minio.default.svc.cluster.local

## Context

I'm looking to have standard s3 support within the cluster for spark and iceberg.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> > bucket.default.svc.cluster.local

This is expected because the separation is based on namespace - one tenant per namespace; you cannot have six levels of deep DNS in k8s.
