### ISSUE TITLE
Inconsistent listing bucket and existence of bucket in sts oidc when claim policy evolved

### ISSUE THREAD

**Issue by alexisdondon** [minio/minio#18531]
## NOTE

When adding or removing a groups in the claim policy of a token and when accessing content using a web sts oidc session token we can see that mc ls or head operation can have a different behaviour depending on the node that handle the call.

## Expected Behavior

We would like to have a consistence response or at least a workaround to trigger the synchronization or reduce the time needed to have a fully synchornized minio cluster.

## Current Behavior

Current behaviour is a mc or minio console with inconsistent reponse when : 
- listing buckets 
- or clicking on a bucket with inconsistent access denied.

When oidc token of a user get policy claims evolving the first node that see this change or taking the sts request (i don't know) get updated after what it seems that each node will be update of new rights of the user from a 10 minute trigger job on each node during this time the request of the user is inconsistent.

## Possible Solution

First one document how minio take care of new policy claims or new right on a sts oidc user.

Solution could be:
- a golang method to force synchonization of each pod to reduce delay.
- a parameter to override ```globalRefreshIAMInterval```  to have less inconsistent time (if my analysis is true).
- another ideas i don't know well the implementation done.

What's strange also is that sessionToken get already the policy of the user then this information si not really to be synchronized as the information of the policy attached to the user is alread in the request with the sessionToken.

## Steps to Reproduce (for bugs)

1.Confiure a minio instance in distributed mode with oidc, add a user in the group ```bucket1_r```  check this is in the policy claim make a bucket1_r policy that allow read or * on the bucket1.

2. get access with AssumeRoleWithWebIdentity and make a mc ls will return bucket1, or check via minio-console.

3. add this user to a ```bucket2_r``` group in his policy should become [bucket1_r, bucket2_r]

4. get access with AssumeRoleWithWebIdentity and make a mc ls will return bucket1 or sometimes bucket1 & bucket2, check via minio-console the bucket list will be inconsistent and clicking one the new bucket when possible will probably do randomly some access denied.

5. Everything is consistent when every node of the cluster seems to have done an iam synchronization. Digging into the behaviour it seems to me that's the parameter here https://github.com/minio/minio/blob/506f121576b6fa582dfc89c175ceacd66a1f8465/cmd/globals.go#L104  ```globalRefreshIAMInterval``` is the mechanism that allow each minio pod to refresh the new policy added/removed.

I am not sur of this mechanism as i have seen no ducumentation on that.

## Your Environment
* Version used (`minio --version`):RELEASE.2023-09-07T02-05-02Z
* deploy in a cluster kubernetes via operator

**Comment by harshavardhana** [comment]
@alexisdondon please upgrade your cluster to latest. What you seem to be describing is a bug and you do not need to wait for 10mins to synchronize.

Closing this until you upgrade and report us back.
