### ISSUE TITLE
Error when copying files - expected element type <Error> but have <html>

### ISSUE THREAD

**Issue by audouts** [minio/minio#18536]
## Expected Behavior
Files are copied successfully.

## Current Behavior
Errors received, repeatedly for the same files:
`Failed to copy: expected element type <Error> but have <html>`

## Possible Solution
Unknown. The error count went down with several retries but the final, remaining files don't ever get copied.

## Steps to Reproduce (for bugs)
For us, the repro steps are simple.

1. Use rclone to copy files from Minio to another S3-compatible storage.

## Context
We are using rclone to copy all our files to a backup system. We tried the `mc` client but it seemed to saturate the network and timed out without retrying.

## Regression
No

## Your Environment
Docker (Debian 11 host)

minio version RELEASE.2023-04-28T18-11-17Z (commit-id=46d45a6923b5a1813dd9ef18c2fbbf86f0dda906)
Runtime: go1.20.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

**Comment by harshavardhana** [comment]
You are using the wrong port and endpoint @audouts. Do not use the Console UI endpoint. Use API endpoint.

Also, make sure to upgrade your setup before reporting issues.

**Comment by audouts** [comment]
Thanks for the reply @harshavardhana. I have a few follow-up questions, please:

How is it able to copy the vast majority of the files in the port/endpoint are wrong? Shouldn't everything fail?

I'm using port 9000. Isn't that the API port?

I'll upgrade to the latest Docker package.

**Comment by harshavardhana** [comment]
Then you have some other load balancer level issue where its returning HTML instead of XML MinIO API port never returns HTML (ever)

**Comment by audouts** [comment]
Okay. Do you have any idea how I might diagnose it? Of the many thousands of files we're transferring, only 20 have this issue but it keeps occurring.

**Comment by audouts** [comment]
I tried with `mc`:

```
mc: <ERROR> Failed to copy `http://localhost:9000[...]`. <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Which side is saying that the entity is too large?

It's apparently having trouble with any file that is over exactly 1GB.

**Comment by harshavardhana** [comment]
yep its your nginx fix max_body requirement

**Comment by audouts** [comment]
Yes, it's on the provider side. I'll leave them address it.

Thanks for your help!
