### ISSUE TITLE
XL: able to remove object when two disks are down in eight disks setup

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1854]
In a eight disks setup, when two disks are down while `mc cp -r /usr myminio/mybucket` in progress, `mc cp -r` fails with `503 Service Unavailable`, whereas when I do `mc rm myminio/mybucket/usr/include/x86_64-linux-gnu/sys/resource.h` it succeeds.

Is it expected behaviour where two write operations treat write quorum differently?

**Comment by harshavardhana** [comment]
> In a eight disks setup, when two disks are down while mc cp -r /usr myminio/mybucket in progress, mc cp -r fails with 503 Service Unavailable, whereas when I do mc rm myminio/mybucket/usr/include/x86_64-linux-gnu/sys/resource.h it succeeds.
> 
> Is it expected behaviour where two write operations treat write quorum differently?

On a 8 disk setup 2 disks down means you don't have write quorum anymore, we need '4 + 3' here

**Comment by harshavardhana** [comment]
> mc rm myminio/mybucket/usr/include/x86_64-linux-gnu/sys/resource.h it succeeds.

Also `mc rm` success is only because we don't send any error even if there is an error due to s3 protocol. So you will see 'success' even if the objects don't exist or are not accessible. 

So whatever you observe is an expected behavior with the current code, removing `bug` tag from this.

**Comment by balamurugana** [comment]
This issue is fixed by 6332c1d9cd7070db90ce25f394177bdfc0f06496
