### ISSUE TITLE
Single node minio for dev work is unstable

### ISSUE THREAD

**Issue by seperman** [minio/minio#18551]
## Problem
Up until recently I was using a very old version of Minio (`RELEASE.2021-09-03T03-56-13Z`) for dev work on my local Ubuntu box.
It was a very simple solid tool: `minio server --address 127.0.0.1:9002 --console-address 127.0.0.1:9003 /tmp/minio-data`

## Expected Behavior
I downloaded `RELEASE.2023-11-20T22-40-07Z` and expected it to work out of the box. I created a new empty `/tmp/minio-data`.

## Current Behavior
I am constantly getting errors like this:

```
API: NewMultipartUpload(bucket=my-bucket, object=accounts.csv.tgz)
Time: 20:07:33 UTC 11/28/2023
DeploymentID: a78b892b-75f5-4a19-97be-3d558320fc09
RequestID: 179BE24105F6BFAE
RemoteHost: 127.0.0.1
Host: localhost:9002
UserAgent: Boto3/1.29.5 md/Botocore#1.32.5 ua/2.0 os/linux#5.19.0-35-generic md/arch#x86_64 lang/python#3.12.0 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.5
Error: not enough online disks to calculate the available space, expected (1)/(0) (*errors.errorString)
       4: internal/logger/logger.go:258:logger.LogIf()
       3: cmd/erasure-server-pool.go:1548:cmd.(*erasureServerPools).NewMultipartUpload()
       2: cmd/object-multipart-handlers.go:214:cmd.objectAPIHandlers.NewMultipartUploadHandler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
```

```
API: SYSTEM()
Time: 20:13:39 UTC 11/28/2023
DeploymentID: a78b892b-75f5-4a19-97be-3d558320fc09
Error: Write failed. Insufficient number of drives online (offline-disks=1/1) (*fmt.wrapError)
       9: internal/logger/logger.go:258:logger.LogIf()
       8: cmd/erasure-encode.go:115:cmd.(*Erasure).Encode()
       7: cmd/erasure-object.go:1276:cmd.erasureObjects.putObject()
       6: cmd/erasure-object.go:1041:cmd.erasureObjects.PutObject()
       5: cmd/erasure-sets.go:758:cmd.(*erasureSets).PutObject()
       4: cmd/erasure-server-pool.go:990:cmd.(*erasureServerPools).PutObject()
       3: cmd/config-common.go:79:cmd.saveConfigWithOpts()
       2: cmd/config-common.go:84:cmd.saveConfig()
       1: cmd/data-usage.go:58:cmd.storeDataUsageInBackend()
```

```
API: SYSTEM()
Time: 20:13:39 UTC 11/28/2023
DeploymentID: a78b892b-75f5-4a19-97be-3d558320fc09
Error: Storage resources are insufficient for the write operation .minio.sys/tmp/c484b09f-48fd-4f91-9b79-68e4a6c075dc/353291bb-a93f-4c5d-8245-f3b8f0e70a68/part.1 (cmd.InsufficientWriteQuorum)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/data-usage.go:59:cmd.storeDataUsageInBackend()
```

```
API: SYSTEM()
Time: 20:13:52 UTC 11/28/2023
DeploymentID: a78b892b-75f5-4a19-97be-3d558320fc09
Error: Following error has been printed 3 times.. Error: Drive: /tmp/minio-data returned unformatted drive found, /tmp/minio-data (*fmt.wrapError)
       endpoint="/tmp/minio-data"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:63:cmd.glob..func9.1()
       1: cmd/background-newdisks-heal-ops.go:545:cmd.monitorLocalDisksAndHeal.func1()
```

## Steps to Reproduce (for bugs)

1. `minio server --address 127.0.0.1:9002 --console-address 127.0.0.1:9003 /tmp/minio-data`
2. Wait for errors to creep in

## Context
I am thinking about reverting back to the old version. The new version does not seem stable.

## Regression
Yes
I don't know how far back I need to go to get to a stable version of minio again. `RELEASE.2021-09-03T03-56-13Z` works.

## Your Environment
* Version used (`minio --version`): `RELEASE.2023-11-20T22-40-07Z`
* Server setup and configuration: No configurations
* Operating System and version (`uname -a`): `Linux 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by seperman** [comment]
The issue was caused because the 2021 version of Minio could handle files being removed from the storage. For example I could empty `tmp/minio-data` and Minio wouldn't hiccup.
The newer versions of Minio store some other metadata and if the files disappear from under them, they freak out.

**Comment by ravindk89** [comment]
This behavior is [documented](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html) and has been in-place for more than [1 year](https://github.com/minio/minio/releases/tag/RELEASE.2022-10-29T06-21-33Z).

What you are describing is the expected behavior when someone removes files from the backend without going through the S3 API. 

The current recommended route is to migrate apps to use the S3 API. for those that cannot, or for users who want a POSIX-esque environment, you can still use FUSE or `mc` to access the data through MinIO.
