### ISSUE TITLE
adls gen 2

### ISSUE THREAD

**Issue by a-klos** [minio/minio#18558]
## NOTE

I try to deploy a minio in our azure kubernetes cluster (provided by aks). I use the helm chart of release 5.0.14. The objective is to use an azure datalake genv2 (adls) as persistent volume mount. Minio is used in standalone mode. Mounting the alds as persistent volume in the pod seems to work like a charm. Using the minio console ui, i can create buckets and upload file etc. The uploaded files are shown inside the container and in the azure datalake. **BUT**, the uploaded files are note visible in the minio console ui. They become visible, as soon as i launch the container as root user. Is that a bug, or intended behavior? The permissions of the ADLS are set to 777, so permissions shouldn't be an issue. 

## Expected Behavior
Due to the fact, that the permissions of the mount is set to 777, minio console ui should show uploaded files in the buckets, even if the container is run with non root user (1000) 

## Current Behavior
Uploaded files are not shown in the minio console ui after upload.

## Steps to Reproduce (for bugs)

1. create a azure storage account
2. follow instruction for mounting [here](https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision) 
  - secret
  - container in azure storage account
  - storage class
  - persistent volume
  - persistent volume claim (pvc)
3. config values file of the helm chart to use existing pvc and mode=standalone

## Your Environment

* Version used (`minio --version`): 5.0.14
* resource group: rg-core-d
* kubernetes version: 1.27.7
* Node sizes: standard_b2ms
* node pools: 1 node pool
*  adls-serviceaccount: hierarchical namespace: enabled; default access tier: Cool
* adls-serviceaccount-container: see below
![grafik](https://github.com/minio/minio/assets/28005881/2322cd7d-f88b-4d90-acd3-5834765949bd)

**Comment by harshavardhana** [comment]
> use an azure datalake genv2 (adls) as persistent volume mount.

is this a POSIX filesystem - what is the filesystem underneath?

**Comment by harshavardhana** [comment]
> use an azure datalake genv2 (adls) as persistent volume mount.

Please bring real disks and real filesystems like XFS for MinIO. This may be a limitation with adls please check with MSFT.
