### ISSUE TITLE
XL: Get object fails when two disks are down in eight disks setup

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1855]
In a eight disks setup, two disks were went down in different time while `mc cp -r /usr myminio/mybucket` was in progress, get object like `mc cp -r myminio/mybucket ~/tmp` fails with below error

```
mc: <ERROR> Unable to prepare URL for copying. The specified key does not exist.                                                                      
0 B / 301.48 MB    0.00 %
mc: <ERROR> Failed to copy ‘http://127.0.0.1:60000/mybucket/usr/bin/2to3’. Input reader closed pre-maturely. Expected ‘96’ bytes, but only received ‘\
0’ bytes.                                                                                                                                             
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume JIVfHUrS’
```

minio version

```
Version: 2016-06-04T00:31:37Z
Release-Tag: DEVELOPMENT.2016-06-04T00-31-37Z
Commit-ID: 18b3871705311163d6aa237ee873b9ba7c080007
```

**Comment by harshavardhana** [comment]
> mc: <ERROR> Unable to prepare URL for copying. The specified key does not exist.  
> 0 B / 301.48 MB    0.00 %
> mc: <ERROR> Failed to copy ‘http://127.0.0.1:60000/mybucket/usr/bin/2to3’. Input reader closed pre-maturely. Expected ‘96’ bytes, but only received ‘\
> 0’ bytes.  
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume JIVfHUrS’

This is possibly the disk which was chosen listed the file but the read() picked a disk which still didn't have the file.

**Comment by balamurugana** [comment]
To be fixed on: 07-Jun-2016
