### ISSUE TITLE
Where did https://github.com/minio/charts go?

### ISSUE THREAD

**Issue by ChillerDragon** [minio/minio#18573]
I know this issue does not belong into this repository. But there used to be https://github.com/minio/charts which is now 404. What happend there? What is the recommended replacement?

It is still indexed in search engines and the first result when I search on google or duckduckgo for "minio helm chart"

![image](https://github.com/minio/minio/assets/20344300/be238c8f-5442-42ed-86b5-50d5d071447c)

**Comment by ChillerDragon** [comment]
Okay I assume it moved here https://github.com/minio/minio/tree/master/helm/minio

Still think there should be a placeholder redirecting users on the old url which is still heavily indexed on search engines.

**Comment by rochaporto** [comment]
As a note, there's also the repo url that is gone:
```
helm repo add minio https://helm.min.io/
Error: looks like "https://helm.min.io/" is not a valid chart repository or cannot be reached: failed to fetch https://helm.min.io/index.yaml : 404 Not Found
```

This is referenced in places like artifacthub:
https://artifacthub.io/packages/helm/minio/minio
