### ISSUE TITLE
Browser: Implement bucket policy.

### ISSUE THREAD

**Issue by GarimaKapoor** [minio/minio#1858]

**Comment by GarimaKapoor** [comment]
Remco will take a look at it, if not we will reassign it within the team.

**Comment by GarimaKapoor** [comment]
@balamurugana please update the timeline for the fix.

**Comment by harshavardhana** [comment]
ping //cc @balamurugana were you able to talk to @krishnasrinivas about this work you have done?

**Comment by harshavardhana** [comment]
This has been implemented and integrated into browser. Closing
