### ISSUE TITLE
PutObject failed and Detected unexpected drive ordering refusing to use the drive

### ISSUE THREAD

**Issue by Howie516** [minio/minio#18597]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I cannot using milvus to PutObject to minio, error message in minio logs (all 4 pods) as follows:
`API: SYSTEM()
Time: 14:39:47 UTC 12/05/2023
DeploymentID: 90ef9380-a96b-4c19-bfeb-64228a673905
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive: expecting http://milvus-minio-1.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export, found http://milvus-minio-3.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export, refusing to use the drive (*fmt.wrapError)
       endpoint="http://milvus-minio-3.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:241:cmd.(*erasureSets).connectDisks.func2()

API: SYSTEM()
Time: 14:45:05 UTC 12/05/2023
DeploymentID: 90ef9380-a96b-4c19-bfeb-64228a673905
Error: Write failed. Insufficient number of drives online (*errors.errorString)
       9: internal/logger/logger.go:258:logger.LogIf()
       8: cmd/erasure-encode.go:112:cmd.(*Erasure).Encode()
       7: cmd/erasure-object.go:1190:cmd.erasureObjects.putObject()
       6: cmd/erasure-object.go:954:cmd.erasureObjects.PutObject()
       5: cmd/erasure-sets.go:767:cmd.(*erasureSets).PutObject()
       4: cmd/erasure-server-pool.go:940:cmd.(*erasureServerPools).PutObject()
       3: cmd/config-common.go:83:cmd.saveConfigWithOpts()
       2: cmd/config-common.go:88:cmd.saveConfig()
       1: cmd/data-usage.go:52:cmd.storeDataUsageInBackend()

API: SYSTEM()
Time: 14:45:05 UTC 12/05/2023
DeploymentID: 90ef9380-a96b-4c19-bfeb-64228a673905
Error: Storage resources are insufficient for the write operation .minio.sys/tmp/bda9dc41-3169-4757-9d16-74de2c3e7e24/51714ddc-a7c8-4303-82e3-4fedd6023cd1/part.1 (cmd.InsufficientWriteQuorum)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/data-scanner.go:228:cmd.runDataScanner()
       1: cmd/data-scanner.go:80:cmd.initDataScanner.func1()

API: SYSTEM()
Time: 14:45:05 UTC 12/05/2023
DeploymentID: 90ef9380-a96b-4c19-bfeb-64228a673905
Error: Storage resources are insufficient for the write operation .minio.sys/tmp/fac3e1f0-6b0c-4f68-bd93-ceb2cf2bcb0d/3ff00182-09e7-4017-93a6-9550bc0b4a19/part.1 (cmd.InsufficientWriteQuorum)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/data-usage.go:53:cmd.storeDataUsageInBackend()

API: SYSTEM()
Time: 14:45:17 UTC 12/05/2023
DeploymentID: 90ef9380-a96b-4c19-bfeb-64228a673905
Error: Following error has been printed 3 times.. Detected unexpected drive ordering refusing to use the drive: expecting http://milvus-minio-1.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export, found http://milvus-minio-3.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export, refusing to use the drive (*fmt.wrapError)
       endpoint="http://milvus-minio-3.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export"
       3: internal/logger/logger.go:248:logger.LogAlwaysIf()
       2: cmd/prepare-storage.go:62:cmd.glob..func7.1()
       1: cmd/erasure-sets.go:241:cmd.(*erasureSets).connectDisks.func2()`

mc admin trace minio:
`API: PutObject(bucket=milvus-bucket, object=file/insert_log/444833670124586675/444833670124586676/444833670130404652/1/446011509740235315)
Time: 12:06:17 UTC 12/05/2023
DeploymentID: 90ef9380-a96b-4c19-bfeb-64228a673905
RequestID: 179DEE0DDBBC7A71
RemoteHost: 172.18.53.200
Host: milvus-minio-2.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.56
Error: Write failed. Insufficient number of drives online (*errors.errorString)
       8: internal/logger/logger.go:258:logger.LogIf()
       7: cmd/erasure-encode.go:112:cmd.(*Erasure).Encode()
       6: cmd/erasure-object.go:1190:cmd.erasureObjects.putObject()
       5: cmd/erasure-object.go:954:cmd.erasureObjects.PutObject()
       4: cmd/erasure-sets.go:767:cmd.(*erasureSets).PutObject()
       3: cmd/erasure-server-pool.go:940:cmd.(*erasureServerPools).PutObject()
       2: cmd/object-handlers.go:1865:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()`

## Steps to Reproduce (for bugs)

1. Use k8s to deploy four Pods, one driver per pod
2. Call the minio api to write data in large numbers, 100 threads, each thread to write 10,000 data
3. Observe logs and trace
4.

## Your Environment

* Version used (`minio:RELEASE.2023-03-20T20-16-18Z):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by ravindk89** [comment]
```
Detected unexpected drive ordering refusing to use the drive: expecting http://milvus-minio-1.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export, found http://milvus-minio-3.milvus-minio-svc.milvus-nmg.svc.cluster.local:9000/export, 
```

When MinIO starts, it must track the exact topology of the system. That means it knows which drives are on which nodes.

It knows, for example, that the drive currently mounted on the pod X was previously mounted on pod Y. Therefore it will *not* use that volume, as the order/location of drives matter.

In baremetal environments we see this if users deploy without using `/etc/fstab` and labels, where a restart results in drives being mounted in a different order.

In K8s, it's likely related to the PVC/PV configuration. How have you configured the PV/PVC/Storage Class config and how are they mounted to pods?
