### ISSUE TITLE
mc ls is very slow

### ISSUE THREAD

**Issue by ltgentoo** [minio/minio#18594]
We have 4 node clusters of minio with nfs storage in k8s
mc ls is very slow; a subdir with less than 500 objects,take more than 6minutes
## Expected Behavior
mc ls should complete in seconds,not in several minutes

## Current Behavior

mc ls is very slow; a subdir with less than 500 objects,take more than 6minutes

## Possible Solution

our nfs storage is not so fast, but it's so slow,even less than 500 objects ,take more than 6 minutes

## Steps to Reproduce (for bugs)

1. mc ls myinio/xxx/xxx
![image](https://github.com/minio/minio/assets/7405793/53b40034-8c92-43cd-9857-58df9677d150)

## Your Environment

* 2022.2.16
* k8s,  sts 4 node,1 disk each node,
* storage: nfs

**Comment by harshavardhana** [comment]
@ltgentoo the slowness is a function of your backend disk here which is NFS.

Please fix your NFS backend to be of expected level of performance.

**Comment by ltgentoo** [comment]
> @ltgentoo the slowness is a function of your backend disk here which is NFS.
> 
> Please fix your NFS backend to be of expected level of performance.

when we run dd test on nfs,it looks like not too bad，this can lead serveral minutes for ls?
![image](https://github.com/minio/minio/assets/7405793/068a1768-a0ae-49b9-b7b8-ae523c15309b)
![image](https://github.com/minio/minio/assets/7405793/620425f4-8ce1-40b2-9779-79c97033c036)
Is there any other possible reason?

**Comment by harshavardhana** [comment]
Use `oflag=direct conv=fdatasync` keep the block size at 4k `bs=4k`

**Comment by harshavardhana** [comment]
And for reads use iflag=direct
