### ISSUE TITLE
Browser: Implement delete with multi select and confirmation dialogue.

### ISSUE THREAD

**Issue by GarimaKapoor** [minio/minio#1859]

**Comment by GarimaKapoor** [comment]
I want Remco to take a look at browser related bugs.

**Comment by GarimaKapoor** [comment]
@balamurugana please update the timeline for the fix.

**Comment by harshavardhana** [comment]
ping //cc @krishnasrinivas

**Comment by krishnasrinivas** [comment]
working on this.

**Comment by harshavardhana** [comment]
> working on this.

Can this be closed? @krishnasrinivas

**Comment by rushenn** [comment]
Delete functionality is done and right now I'm working on styling. I think multi select feature is yet to be done.

**Comment by GarimaKapoor** [comment]
@rushenn how much more work is pending on this?

**Comment by rushenn** [comment]
@GarimaKapoor only multi select feature is left. I think @krishnasrinivas can give an exact estimate. 

Its's better to close this and open one specifically for multi-select and mass actions.

**Comment by harshavardhana** [comment]
Closing.. can you open for multi-select @rushenn ?
