### ISSUE TITLE
Browser: Implement share.

### ISSUE THREAD

**Issue by GarimaKapoor** [minio/minio#1860]

**Comment by GarimaKapoor** [comment]
Harsha, I did not assign anyone as Remco might take a over the browser. Removing the Assigees for now.

**Comment by GarimaKapoor** [comment]
@balamurugana please update the timeline for the fix.

**Comment by harshavardhana** [comment]
ping //cc @krishnasrinivas

**Comment by krishnasrinivas** [comment]
working on this.

**Comment by harshavardhana** [comment]
This has been fixed 

https://github.com/minio/miniobrowser/pull/202
https://github.com/minio/miniobrowser/pull/201
https://github.com/minio/miniobrowser/pull/200
https://github.com/minio/miniobrowser/pull/196
