### ISSUE TITLE
regression with commit id 52ffedf5271616ccf72742a5da425c76b4755a49, redirections are not working from minio

### ISSUE THREAD

**Issue by sureshkosuru** [minio/minio#18603]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

In order to fix https://github.com/minio/minio/issues/13918, with the commit id 52ffedf5271616ccf72742a5da425c76b4755a49 redirection were disabled. but the issue is with the location for that particular bug. as redirections are disabled all together, it is effecting the features  in the moss, which relied on the minio redirection. 

## Expected Behavior

minio should continue to support redirection 

instead of disabling complete redirection function, location related bug need to be fixed 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Regression
 Yes
 52ffedf5271616ccf72742a5da425c76b4755a49

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> In order to fix #13918, with the commit id 52ffedf5271616ccf72742a5da425c76b4755a49 redirection were disabled. but the issue is with the location for that particular bug. as redirections are disabled all together, it is effecting the features in the moss, which relied on the minio redirection.

There is no `minio gateway` product anymore. This doesn't apply anymore closing this issue.

**Comment by sureshkosuru** [comment]
@harshavardhana 
our mc relied on minio with commit id 43eb05300f1bae547e042b23b3dcd9ecec59cbe8. based on the redirection we have implemented distributed s3 store to connect to multiple s3 vendors. this feature stopped functioning after the commit 52ffedf5271616ccf72742a5da425c76b4755a49, in the vanilla client not supporting our feature. please suggest a way to fix this.
