### ISSUE TITLE
minio backup failure How to retrieve data?

### ISSUE THREAD

**Issue by xujimu** [minio/minio#18609]
I am attempting to backup MinIO on my CentOS 7 system. My Docker run command is as follows:
```
docker run --name minio -tdi --publish 9000:9000 --publish 9001:9001 --volume /home/minio:/data --restart always --privileged=true bitnami/minio:latest

```
I backed up the /home/minio folder, then reset my CentOS 7 system, and restored the /home/minio folder on the new CentOS 7 system. After restoration, I executed the command again:
```
docker run --name minio -tdi --publish 9000:9000 --publish 9001:9001 --volume /home/minio:/data --restart always --privileged=true bitnami/minio:latest

```

The MinIO system started successfully, but the buckets no longer exist. I realize my backup failed. Is there any way to recover my data? Thank you."

**Comment by harshavardhana** [comment]
If you know that backup failed and you don't have the data. We do not have it either :-)
