### ISSUE TITLE
 decommissionObject: PutObject() Storage resources are insufficient for the read operation .minio.sys

### ISSUE THREAD

**Issue by mrf-cyber** [minio/minio#18625]
## NOTE
We added another pool(2) to our minio solution.  In middle of pool's rebalance to get a better distribution, we got a fw issue at SAS Controller and a brand new disk failure with just 200GB writed.
We solved fw issue upgrading to last version and replaced the disk. 
Right now we're decomisioning that pool(2) because we found several errors. When we start decomision it got 16TB of 160TB and now it cant progress. Right now this is the current usage of pool 2 that we're unable to move back to pool 1.

```
│ ID  │ Pools                                                          │ Capacity                         │ Status │
│ 1st │ https://minio{1...1}.minio.local:9000/minio/disk{1...12}/minio │ 155 TiB (used) / 160 TiB (total) │ Active │
│ 2nd │ https://minio{2...2}.minio.local:9000/minio/disk{1...12}/minio │ 1.1 TiB (used) / 160 TiB (total) │ Active │
```

## Expected Behavior
Finish the decomisioning of the pool, for reformat fully again and create again a new pool.
We wanna know if we can do something to finish recover that 1.1TB left in pool 2 or we just lost that TB of data.

## Current Behavior
mc admin decommission start cluster/ https://minio{2...2}.minio.local:9000/minio/disk{1...12}/minio

```
Dec 10 19:18:35 minio2 minio[2584]: Time: 19:18:35 UTC 12/10/2023
Dec 10 19:18:35 minio2 minio[2584]: DeploymentID: 6bee8f0f-9cb1-414d-be0f-327d3215c0be
Dec 10 19:18:35 minio2 minio[2584]: Error: Storage resources are insufficient for the read operation vbo01-standard/XXXX/XXXX/XXXXX.onmicrosoft.com/XXXXXX/e69cc802fbc0494aa8ce7b59ccc6ec8c/Webs/e35b33d7ddd146cbb911bf9df895a3c3/Files/Index/Root.000000000000246A.6858527869 (cmd.InsufficientReadQuorum)
Dec 10 19:18:35 minio2 minio[2584]:        8: internal/logger/logger.go:258:logger.LogIf()
Dec 10 19:18:35 minio2 minio[2584]:        7: cmd/erasure-encode.go:96:cmd.(*Erasure).Encode()
Dec 10 19:18:35 minio2 minio[2584]:        6: cmd/erasure-object.go:1276:cmd.erasureObjects.putObject()
Dec 10 19:18:35 minio2 minio[2584]:        5: cmd/erasure-object.go:1041:cmd.erasureObjects.PutObject()
Dec 10 19:18:35 minio2 minio[2584]:        4: cmd/erasure-sets.go:758:cmd.(*erasureSets).PutObject()
Dec 10 19:18:35 minio2 minio[2584]:        3: cmd/erasure-server-pool.go:1009:cmd.(*erasureServerPools).PutObject()
Dec 10 19:18:35 minio2 minio[2584]:        2: cmd/erasure-server-pool-decom.go:668:cmd.(*erasureServerPools).decommissionObject()
Dec 10 19:18:35 minio2 minio[2584]:        1: cmd/erasure-server-pool-decom.go:910:cmd.(*erasureServerPools).decommissionPool.func2()
Dec 10 19:18:35 minio2 minio[2584]: API: SYSTEM()
Dec 10 19:18:35 minio2 minio[2584]: Time: 19:18:35 UTC 12/10/2023
Dec 10 19:18:35 minio2 minio[2584]: DeploymentID: 6bee8f0f-9cb1-414d-be0f-327d3215c0be
Dec 10 19:18:35 minio2 minio[2584]: Error: decommissionObject: PutObject() Storage resources are insufficient for the read operation .minio.sys/tmp/7c52e739-072a-4fd6-9b18-abf00db7a512/968b5c8e-c0df-4fc1-b239-5d7b10a89d5b/part.1 (*fmt.wrapError)
Dec 10 19:18:35 minio2 minio[2584]:        2: internal/logger/logger.go:258:logger.LogIf()
Dec 10 19:18:35 minio2 minio[2584]:        1: cmd/erasure-server-pool-decom.go:913:cmd.(*erasureServerPools).decommissionPool.func2()

```

After several errors decomisioning stops.

## Possible Solution
-

## Steps to Reproduce (for bugs)
-

## Context
-

## Regression
-

## Your Environment
minio version RELEASE.2023-11-20T22-40-07Z (commit-id=f56a182b719cb262e0628ef3f544371ea8842551)
Runtime: go1.21.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
Linux minio2 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@mrf-cyber you have setup things incorrectly.

First of all you don't have multiple nodes here you are wrongly simulating that here by providing an incorrect command argument.

{2...2} is rather meaningless command line argument.

Your objects don't span across one node at all, so there is no HA.

Beyond that there is some other issue with the objects on disk that it's not readable.

All our tools that can help you in this regard require subscription, so you should onboard yourself as a customer and get your setup fixed first.

So can't help you further than this.

**Comment by mrf-cyber** [comment]
@harshavardhana , thx for your response.

There's no simulation, and as far as we undestood in your online docs there only requierement for a pool is or have 4 nodes with a single disk each one or 4 disk. Then having a pool with single node (12 disk) give us just a node with EC 12:4 resilency. Our nodes got 240TB raw / 160 Usables.

So thanks for help will contact your sales rep.

**Comment by harshavardhana** [comment]
> @harshavardhana , thx for your response.
> 
> There's no simulation, and as far as we undestood in your online docs there only requierement for a pool is or have 4 nodes with a single disk each one or 4 disk. Then having a pool with single node (12 disk) give us just a node with EC 12:4 resilency. Our nodes got 240TB raw / 160 Usables.
> 
> So thanks for help will contact your sales rep.

The first step is to migrate away from this deployment. Set it up properly with a minimum of 4 nodes.. 2 node is a terrible way to run a production system. The way you are doing is even worse you literally have no HA for anything on the system. A single node going offline is sufficient to take the entire deployment down.

As a first step we can't support your existing deployment, we can first help you move to a supported setup.
