### ISSUE TITLE
Error by using "mc idp openid add" 

### ISSUE THREAD

**Issue by AlexA4321** [minio/minio#18629]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

If Yu try to configure OpenID server by calling command:
**`mc idp openid add play NGRS client_id="minio" client_secret="0yuYvQo6TcCMjgDh7aquvTBKLx8TOjRt" config_url="http://iam:8080/auth/realms/master/.well-known/openid-configuration" scopes="openid,groups,email,profile"  redirect_uri="http://minio:9667/oauth_callback" claim_name="policy"`**

## Expected Behavior
An openid server is configured

## Current Behavior
the command exits with error:
mc: <ERROR> Unable to add OpenID IDP config to server. Get "http://iam:8080/auth/realms/NGRS/.well-known/openid-configuration": dial tcp: lookup iam on 127.0.0.53:53: server misbehaving.

## Possible Solution
if this openid server configured with WebUI all works fine. SSO Aproach works fine.

## Steps to Reproduce (for bugs)
1. compose docker-compose.yml 
2. open minio container terminal
3. run command: 
           mc idp openid add play NGRS client_id="minio" client_secret="0yuYvQo6TcCMjgDh7aquvTBKLx8TOjRt" config_url="http://iam:8080/auth/realms/master/.well-known/openid-configuration" scopes="openid,groups,email,profile"  redirect_uri="http://minio:9667/oauth_callback" claim_name="policy"

## Context
docker-compose.yml
=========8<---------------------------

version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-12-07T04-16-00Z
    container_name: minio
    depends_on:
      iam :
        condition: service_healthy
    ports:
      - "9666:9000"
      - "9667:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Pa55w0rd
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9697/"
    command: server --console-address ":9001" /data
  postgresdb:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile_PostgreSQL
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MySecretPassword
      - CDR_DB_NAME=cdr
      - CDR_USER=cdr
      - CDR_PASSWORD=somepassword
      - KEYCLOAK_DB_NAME=keycloak
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=somepassword
    volumes:
      - ./.postgres_db:/var/lib/postgresql/data      
    restart: unless-stopped
  iam:
    container_name: iam
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    volumes:
      - ./keycloak-conf/themes:/opt/jboss/keycloak/themes/
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgresdb
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=somepassword
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
    depends_on:
      - postgresdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://iam:8080/auth/realms/master/.well-known/openid-configuration"]
      interval: 30s
      timeout: 5s
      retries: 15
      start_period: 30s

--------------------->8============

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2023-12-07T04-16-00Z (commit-id=cfed671ea39d56987596e3301d0b6c5ec6cbd1f8)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

* Server setup and configuration:

* Operating System and version (`uname -a`):
Linux DEER-Debian2 5.10.0-0.bpo.15-amd64 #1 SMP Debian 5.10.120-1~bpo10+1 (2022-06-13) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> the command exits with error:
> mc: Unable to add OpenID IDP config to server. Get "http://iam:8080/auth/realms/NGRS/.well-known/openid-configuration": dial tcp: lookup iam on 127.0.0.53:53: server misbehaving.

We cannot resolve the DNS name - so the `error` - nothing surprising here. 

- Fix your DNS to resolve `iam -> ip`
- Provide a fully qualified domain name

**Comment by AlexA4321** [comment]
If  minio can't resolve iam, the full approach shell not working. BUT ! If you configure this wit WebUI - minio can resolve this dns name. It works. But if "mc idp openid add" will be called - iam dns name can't be resolved.

**Comment by AlexA4321** [comment]
If you use a few minutes to proof this - you will see, iam is in container network from all continers (iam, postgress & minio) can be resolved and work fine. This issue touch the "mc" only

**Comment by AlexA4321** [comment]
![Bild 3](https://github.com/minio/minio/assets/153541662/0840ac50-5914-43ef-a6cd-925e7bb964a9)

**Comment by AlexA4321** [comment]
the keycloak service runs on 172.18.0.3
