### ISSUE TITLE
Minio cluster node CPU is occasionally very high

### ISSUE THREAD

**Issue by Gordon-Gan-Jiang** [minio/minio#18628]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

Upload files to the minio cluster through the mc tool, and query objects through the minio sdk. Occasionally, the request status code is 404, and retrying will succeed. As you can see from the minio cluster panel, there are a large number of 404, 403, and 409 status requests in the internal logs. And now the node CPU is very high.

## Your Environment

* Version used (`minio --version`): RELEASE.2022-11-17T21-20-39Z
* Server setup and configuration: CPU(s):40， Architecture:x86_64
* Operating System and version (`uname -a`):  Ubuntu 20.04.5 LTS

**Comment by Gordon-Gan-Jiang** [comment]
<img width="1589" alt="image" src="https://github.com/minio/minio/assets/62733672/46b43821-ad72-4752-b997-5fbb62808b22">

**Comment by Gordon-Gan-Jiang** [comment]
<img width="878" alt="image" src="https://github.com/minio/minio/assets/62733672/81808145-a4fd-4e27-8ba1-6d92ccf56a52">

**Comment by harshavardhana** [comment]
Please upgrade to latest release and report back. You are using a release more than a year old.

**Comment by Gordon-Gan-Jiang** [comment]
The minio cluster has 4 nodes and uses nginx load balancing. The file upload is completed, the SDK is called to obtain the file metadata information, the request response is 404, and the retry request response is 200. Is it possible that the file data is out of sync between minio cluster nodes? For example, when MC is used to upload a folder, node A is connected, but the file metadata information is obtained from node B, and there is a delay in data synchronization between nodes A and B.

**Comment by harshavardhana** [comment]
> The minio cluster has 4 nodes and uses nginx load balancing. The file upload is completed, the SDK is called to obtain the file metadata information, the request response is 404, and the retry request response is 200. Is it possible that the file data is out of sync between minio cluster nodes? For example, when MC is used to upload a folder, node A is connected, but the file metadata information is obtained from node B, and there is a delay in data synchronization between nodes A and B.

No there is no such thing, unless you are using NFS backend.

**Comment by Gordon-Gan-Jiang** [comment]
The minio cluster has been upgraded to the latest version.But there are many 400 and 404 errors in the trace, are these normal? Moreover, the cluster node CPU usage is much higher than before.
![image](https://github.com/minio/minio/assets/62733672/ec6a06fc-7844-4315-a566-6a229e6c51af)

**Comment by Gordon-Gan-Jiang** [comment]
<img width="788" alt="image" src="https://github.com/minio/minio/assets/62733672/47c270a7-8fed-48fa-9ffb-566747ca1d19">
  After updating the version of minio yesterday, a large number of error logs appeared. 
Please help to find out what caused it, thank you
mc admin logs minio
