### ISSUE TITLE
Unable to Auth with AWS Cognito for 

### ISSUE THREAD

**Issue by programmrz** [minio/minio#18623]
I have an existing S3 / Cognito flow that allows an authed user to use an Authorization bearer token to access an S3 file and a policy on the bucket to allow a user to download/access anything in their bucket as long as the authed jwt.sub is the same as the root folder in the bucket. I'd like to move to minio so I set the same policy type, just ALIAS/private/${jwt.sub} but I'm unable to auth with working bearer tokens. 

I am passing the bearer token as I would to auth any other AWS service, and I get 
`The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256` in postman.

On Minio's end, I've added AWS Cognito settings but will admit im am unsure what scopes/claims to configure in cognito.

* Version used (`minio --version`): RELEASE.2023-11-20T22-40-07Z
* Server setup and configuration: Ubuntu, running Minio. allows 443 which gets sent to Minio
* Operating System and version (`uname -a`): Ubuntu 22.04

**Comment by harshavardhana** [comment]
Does AWS Congito support full OpenID spec ? And it yes how is it configured? 

Can you provide us some more information?
