### ISSUE TITLE
Constant ~15% CPU utilisation on Single node deployment

### ISSUE THREAD

**Issue by dalgibbard** [minio/minio#18622]
I'm running a single instance cluster for testing/development, but am finding it's running with constant ~15% (12-18%) CPU utilisation even when not in active use. This is on a Ryzen 5800G.

I have 1 bucket configured, single user, with roughly 500GB of data in it.

I was hoping to just leave it running 24/7, but it's stopping the server CPU from idling, and causing increased cost as a result (as well as using cycles I need for other services).
If it was a cluster trying to maintain quorum/health, it'd make sense. If there were active connections or requests being made, it'd make sense. My other concern is the potential impact to the backend storage if this is performing lots of disk requests etc too (unfortunately, I don't have visibility into what the server is actually doing to establish the impact).

The deployment is a minio docker container, with the data volume mounted from the host, which is mounted from an NFS server.

It seems that the ```mc support profile``` command is shut away behind a SUBNET registration, so I can't easily find what the server is busying itself with.

## Expected Behavior
Single-instance Minio deployments shouldn't use excessive CPU when idle

## Current Behavior
Single-instance Minio deployment is using ~15% CPU constantly when idle.

## Possible Solution
* Whatever constant tasks are being run should be optional/configurable on single-instance deployments for development environments.

## Steps to Reproduce (for bugs)
* Deploy a single-instance server in docker
* Add a single bucket with ~500G of data

## Context
Just using it as a single-instance deployment for convenience of the S3 API compatibility in a development environment, without requiring the cost of a cloud service.
Data within it is backed up elsewhere, and server resilience is not important in this scenario.
Since it's running in a domestic setting, and power costs are high, it's desriable for the server to be as idle/low power as possible when not in use.

## Regression
Unsure, but I don't recall seeing this issue in the past, and have been running the deployment for about a year.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2023-11-20T22-40-07Z (commit-id=f56a182b719cb262e0628ef3f544371ea8842551)
* Server setup and configuration: Docker container, volume mounted from host, which is an NFS mount
* Operating System and version (`uname -a`): ```Linux <host> 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by dalgibbard** [comment]
Update: I'm wondering if this might be the behaviour of the "scanner" as mentioned here: https://github.com/minio/minio/tree/master/docs/config#usage-scanner

Since this isn't a feature I care about (if i've understood correctly that it's just for reporting disk utilisation etc), i've set ```cycle``` to ```1000d```. Hopefully that's sufficient to stop it; though after restarting, minio is still using constant CPU currently.

**Comment by harshavardhana** [comment]
There are many things MinIO needs to take care of on a running system. If you are not happy with MinIO activity just shut it down and use it when you need it.

It is not an nginx it performs house keeping activities, such as 

- health monitoring of the backend drive
- routine activities of cleaning up any temporary files
- cycle=100d is not allowed anymore you can set something called `scanner speed=slowest`

**Comment by sprig** [comment]
> There are many things MinIO needs to take care of on a running system. If you are not happy with MinIO activity just shut it down and use it when you need it.
> 
> It is not an nginx it performs house keeping activities, such as
> 
> * health monitoring of the backend drive
> * routine activities of cleaning up any temporary files
> * cycle=100d is not allowed anymore you can set something called `scanner speed=slowest`

Seems like a copout answer and a strawman argument to me. You might as well turn off all of your servers while you're not using them. 
For the same price you could compare Minio to a database or a smart filesystem, than a database server or a file system. Yet eg `postgres` is not using constant CPU when idling. Nor is `redis`, `zfs` or `samba`.

I don't know what kind of monitoring is available if you enable a commercial license or conne
ct to prometheus but on my instance there is the bare minimum of information being made available to the user: ![Screenshot 2024-04-30 125941](https://github.com/minio/minio/assets/2652983/383d3bdd-2211-4943-82a7-f474ebd0741f)

How does that justify a constant 15% CPU usage?

**Comment by klauspost** [comment]
MinIO is not a database, nor is it a file system. 

There is no point to continuing this. If you can't deal with how MinIO works, just use something else.
