### ISSUE TITLE
some "context deadline exceeded" occurs.

### ISSUE THREAD

**Issue by wangqinghuan** [minio/minio#18620]
we find some Error context deadline exceeded occurs in minio log. Could anyone suport or how to get more detail stack exception?  

> _```
> API: PutObject(bucket=qdmetro-document, object=temp_new/1733206867615678477_0.xlsx)
> Time: 19:41:01 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2800C675B8C
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: PutObject(bucket=qdmetro-document, object=webapp/new_file/order/20231209/1732774352044281858/4/1732774352044281858.pdf)
> Time: 19:41:23 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2855BF07146
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: PutObject(bucket=qdmetro-document, object=temp_new/1733209482625810433_0.xlsx)
> Time: 19:43:33 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2A39DB969B0
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: PutObject(bucket=qdmetro-document, object=temp_new/1733203073104347139_0.xlsx)
> Time: 19:45:01 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2B7F15ABCA5
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: DeleteObject(bucket=qdmetro-iotminio, object=20bf13ff54f5428086bea439c08c7657.jpg)
> Time: 19:45:30 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2BEB3212E13
> RemoteHost: 172.16.210.118
> Host: 172.16.210.114:9000
> UserAgent: MinIO (amd64; amd64) minio-java/dev
> Error: Drive /data, path (qdmetro-iotminio/20bf13ff54f5428086bea439c08c7657.jpg) returned an error (context deadline exceeded) (*fmt.wrapError)
>        8: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        7: internal/logger/logonce.go:149:logger.LogOnceIf()
>        6: cmd/erasure-object.go:590:cmd.readAllXL()
>        5: cmd/erasure-object.go:663:cmd.erasureObjects.getObjectFileInfo()
>        4: cmd/erasure-object.go:755:cmd.erasureObjects.getObjectInfo()
>        3: cmd/erasure-object.go:473:cmd.erasureObjects.GetObjectInfo()
>        2: cmd/erasure-sets.go:760:cmd.(*erasureSets).GetObjectInfo()
>        1: cmd/erasure-server-pool.go:430:cmd.(*erasureServerPools).getPoolInfoExistingWithOpts.func1()
> 
> API: PutObject(bucket=qdmetro-document, object=temp_new/1733206867615678478_0.xlsx)
> Time: 19:47:01 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2D3E6EB890B
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: DeleteObject(bucket=qdmetro-iotminio, object=20bf307cb1354c0ba1d2e3f4d114a7b7.jpeg)
> Time: 19:47:30 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2DAA5566862
> RemoteHost: 172.16.210.118
> Host: 172.16.210.114:9000
> UserAgent: MinIO (amd64; amd64) minio-java/dev
> Error: Drive /data, path (qdmetro-iotminio/20bf307cb1354c0ba1d2e3f4d114a7b7.jpeg) returned an error (context deadline exceeded) (*fmt.wrapError)
>        8: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        7: internal/logger/logonce.go:149:logger.LogOnceIf()
>        6: cmd/erasure-object.go:590:cmd.readAllXL()
>        5: cmd/erasure-object.go:663:cmd.erasureObjects.getObjectFileInfo()
>        4: cmd/erasure-object.go:755:cmd.erasureObjects.getObjectInfo()
>        3: cmd/erasure-object.go:473:cmd.erasureObjects.GetObjectInfo()
>        2: cmd/erasure-sets.go:760:cmd.(*erasureSets).GetObjectInfo()
>        1: cmd/erasure-server-pool.go:430:cmd.(*erasureServerPools).getPoolInfoExistingWithOpts.func1()
> 
> API: PutObject(bucket=qdmetro-document, object=temp_new/1733206867615678479_0.xlsx)
> Time: 19:47:33 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF2DB80B2C0D6
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: DeleteObject(bucket=qdmetro-iotminio, object=20bf307cb1354c0ba1d2e3f4d114a7b7.jpeg)
> Time: 19:50:29 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF3047BE6CB39
> RemoteHost: 172.16.210.118
> Host: 172.16.210.114:9000
> UserAgent: MinIO (amd64; amd64) minio-java/dev
> Error: Drive /data, path (qdmetro-iotminio/20bf307cb1354c0ba1d2e3f4d114a7b7.jpeg) returned an error (context deadline exceeded) (*fmt.wrapError)
>        8: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        7: internal/logger/logonce.go:149:logger.LogOnceIf()
>        6: cmd/erasure-object.go:590:cmd.readAllXL()
>        5: cmd/erasure-object.go:663:cmd.erasureObjects.getObjectFileInfo()
>        4: cmd/erasure-object.go:755:cmd.erasureObjects.getObjectInfo()
>        3: cmd/erasure-object.go:473:cmd.erasureObjects.GetObjectInfo()
>        2: cmd/erasure-sets.go:760:cmd.(*erasureSets).GetObjectInfo()
>        1: cmd/erasure-server-pool.go:430:cmd.(*erasureServerPools).getPoolInfoExistingWithOpts.func1()
> 
> API: PutObject(bucket=qdmetro-document, object=temp_new/1733203073104347138_0.xlsx)
> Time: 19:50:48 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF308C84FCC17
> RemoteHost: 172.16.210.124
> Host: 172.16.210.114:9000
> UserAgent: MinIO (Linux; amd64) minio-java/8.4.3
> Error: context deadline exceeded (context.deadlineExceededError)
>       10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        9: internal/logger/logonce.go:149:logger.LogOnceIf()
>        8: cmd/erasure-object.go:1336:cmd.erasureObjects.putObject()
>        7: cmd/erasure-object.go:1000:cmd.erasureObjects.PutObject()
>        6: cmd/erasure-sets.go:754:cmd.(*erasureSets).PutObject()
>        5: cmd/erasure-server-pool.go:963:cmd.(*erasureServerPools).PutObject()
>        4: cmd/disk-cache.go:867:cmd.newServerCacheObjects.func4()
>        3: cmd/disk-cache.go:712:cmd.(*cacheObjects).PutObject()
>        2: cmd/object-handlers.go:1888:cmd.objectAPIHandlers.PutObjectHandler()
>        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
> 
> API: DeleteObject(bucket=qdmetro-iotminio, object=20c094b2b72e4e3ea733f8c9306e48d2.jpeg)
> Time: 19:51:30 UTC 12/08/2023
> DeploymentID: d54a8b40-bb06-4198-bfb8-21031410e60b
> RequestID: 179EF312A2CD590E
> RemoteHost: 172.16.210.118
> Host: 172.16.210.114:9000
> UserAgent: MinIO (amd64; amd64) minio-java/dev
> Error: Drive /data, path (qdmetro-iotminio/20c094b2b72e4e3ea733f8c9306e48d2.jpeg) returned an error (context deadline exceeded) (*fmt.wrapError)
>        8: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
>        7: internal/logger/logonce.go:149:logger.LogOnceIf()
>        6: cmd/erasure-object.go:590:cmd.readAllXL()
>        5: cmd/erasure-object.go:663:cmd.erasureObjects.getObjectFileInfo()
>        4: cmd/erasure-object.go:755:cmd.erasureObjects.getObjectInfo()
>        3: cmd/erasure-object.go:473:cmd.erasureObjects.GetObjectInfo()
>        2: cmd/erasure-sets.go:760:cmd.(*erasureSets).GetObjectInfo()
>        1: cmd/erasure-server-pool.go:430:cmd.(*erasureServerPools).getPoolInfoExistingWithOpts.func1()
> ```_

**Comment by wangqinghuan** [comment]
we used NFS mount as minio data directory. The NFS mount stats is 
![image](https://github.com/minio/minio/assets/22762150/12a7fd19-f05d-41cd-a8f0-55a2d84f3f8d)
When  erro "context deadline exceeded" occurs, the nfs request rate and time is very low.It seems not NFS block minio write

**Comment by wangqinghuan** [comment]
The cpu usage and network bytes is normal, the cpu load increase due to minio block in erasureObjects.putObject()
 and getObject(). 
![image](https://github.com/minio/minio/assets/22762150/8b8fc5d5-a691-45d2-964f-1c88fef3e775)

**Comment by harshavardhana** [comment]
NFS is not a supported deployment for distributed setup. Use real disks. NFS is notorious for being unreliable. 

MinIO can only work if your backend FS can respond in time; it looks like once in a while, your NFS mount stops responding, so we timeout.

**Comment by wangqinghuan** [comment]
@harshavardhana hi, our client only provides NAS and SAN. I think NAS is network filesystem, SAN  and DAS are block storage.  Is SAN storage better solution for Minio than NAS?
Like the first scenario
![image](https://github.com/minio/minio/assets/22762150/ea95ba37-7ee8-420a-8279-f64a35f20b5c)
https://blog.min.io/no-san-nas/#:~:text=SAN%2FNAS%20devices%20can%27t,architecture%20to%20provide%20higher%20throughput.

**Comment by harshavardhana** [comment]
You can use SAN
