### ISSUE TITLE
Unable to install from source

### ISSUE THREAD

**Issue by LiDaiyan** [minio/minio#18634]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
no error

## Current Behavior
in the stdout, it shows
`go/pkg/mod/github.com/go-openapi/strfmt@v0.21.7/bson.go:21:2: go.mongodb.org/mongo-driver@v1.13.0: verifying module: checksum mismatch
	downloaded: h1:c+OsvIAc3LCdc9dcfowGjT2bWjvLOccxhdguqHJUvbo=
	sum.golang.org: h1:67DgFFjYOCMWdtTEmKFpV3ffWlFnh+CYZ8ZS/tXWUfY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
go/pkg/mod/github.com/go-openapi/strfmt@v0.21.7/bson.go:23:2: go.mongodb.org/mongo-driver@v1.13.0: verifying module: checksum mismatch
	downloaded: h1:c+OsvIAc3LCdc9dcfowGjT2bWjvLOccxhdguqHJUvbo=
	sum.golang.org: h1:67DgFFjYOCMWdtTEmKFpV3ffWlFnh+CYZ8ZS/tXWUfY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
go/pkg/mod/github.com/go-openapi/strfmt@v0.21.7/bson.go:24:2: go.mongodb.org/mongo-driver@v1.13.0: verifying module: checksum mismatch
	downloaded: h1:c+OsvIAc3LCdc9dcfowGjT2bWjvLOccxhdguqHJUvbo=
	sum.golang.org: h1:67DgFFjYOCMWdtTEmKFpV3ffWlFnh+CYZ8ZS/tXWUfY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.`

## Possible Solution
change the mongo-driver version maybe possible.

## Steps to Reproduce (for bugs)

1. type `go install github.com/minio/minio@latest`
2.
3.
4.

## Your Environment

* Version used (`minio --version`): latest
* Server setup and configuration: ubuntu 22.04

**Comment by harshavardhana** [comment]
@LiDaiyan you have some local build issue, `go install` works for me locally.
