### ISSUE TITLE
"A header you provided implies functionality that is not implemented. Use CloudBerry to edit a file. When done editing, it uploads the new file, 

### ISSUE THREAD

**Issue by skirsch** [minio/minio#18635]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by jiuker** [comment]
duplicate #18636
