### ISSUE TITLE
"A header you provided implies functionality that is not implemented." when saving a file

### ISSUE THREAD

**Issue by skirsch** [minio/minio#18636]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

no error when saving back a file after edit.

## Current Behavior

Use CloudBerry to edit a file on the Minio server. When done editing, it uploads the new file, It saves it just fine, but the MinIO server throws back an error about implies functionality that is not implemented.

## Steps to Reproduce (for bugs)

1. use cloudberry explorer
2. double click a text file in a bucket
3. edit the text file
4. quit the editor
5. confirm you want to save
6. see error message in CloudBerry explorer

## Your Environment

* Version used (`minio --version`):  latest. happens on your demo server too!
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by jiuker** [comment]
Could you share the trace log? @skirsch 
see https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-trace.html.

**Comment by klauspost** [comment]
Sounds like you are running an ancient MinIO version. Please report server version and upgrade if needed.

**Comment by skirsch** [comment]
I tried it on the version I was running and also the demo version recommended on the website (play.min.io). Same error. I have no idea what version play.min.io is running. It isn't shown.

I have no idea what version I have. It was just downloaded a week ago. I looked in the documentation for where this is shown, but it appears you cannot find it from the Console anymore, even though I was able to find it yesterday which is bizzare. I don't have root access to my server at this time, but I can run trace from the console shortly. Stay tuned while I get the root login credentials to my server.

**Comment by skirsch** [comment]
The trace shows that cloudberry explorer is making a PutObjectACL call as the third call when uploading and the server is saying that that API is not implemented.

![image](https://github.com/minio/minio/assets/1555174/bdb153a7-ddb5-4c79-82de-f0966541b694)

**Comment by skirsch** [comment]
Also, when trying to upload a file, CloudBerry sends a "HeadObject" request to MinIO. Cyberduck doesn't do this. Apparently, HeadObject is not allowed in a policy (I got an error when I tried adding it), so it always fails with MinIO (works for other S3 compatible servers). 

So my problem is that **PutObjectACL** and **HeadObject** are used by Cloudberry (for updating a file and when uploading a file, respectively) and are **not implemented in MinIO**, causing the errors.

**Comment by skirsch** [comment]
root@skirsch-minio:/# docker run minio/minio --version
minio version **RELEASE.2023-12-02T10-51-33Z** (commit-id=a50f26b7f56e5e6b1df8a648423736319ecdabd6)
Runtime: go1.21.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

**Comment by harshavardhana** [comment]
We do not support PutObjectACL() and it is not going to be ever implemented. HeadObject() works fine. You just have to give it proper permissions. HeadObject -> GetObject() its the same permissions there are no special HeadObject permissions. 

CloudBerry has to simply ignore 501 Not Implemented.

**Comment by harshavardhana** [comment]
> So it always fails with MinIO (works for other S3 compatible servers).

https://awspolicygen.s3.amazonaws.com/policygen.html For example there is no such thing as s3:HeadObject() so whoever is implementing "S3 Compatible" it does not exist.

The correct Action for READ permissions is `s3:GetObject`

**Comment by skirsch** [comment]
Yes, you're right about the policy; HeadObject doesn't exist as a policy.

I wanted to create a bucket for UPLOAD only, so I didn't list Get permission. This worked FINE on Cyberduck... It would upload as expected. CloudBerry makes the HeadObject call and MinIO fails it and wouldn't upload the file. I guess I'll add the Get permission which I didn't want to do.

So one could argue that MinIO is actually doing it correctly and Cloudberry should ignore these errors.

Thanks for the amazingly fast and clear response.
