### ISSUE TITLE
Free space >40GB, replication error "Storage backend has reached its minimum free drive threshold"

### ISSUE THREAD

**Issue by stefan-lange** [minio/minio#18639]
## Expected Behavior
No errors, if there is more than 1 or 2 GB free space left

## Current Behavior
There are at least 40 GB of free space left on every drive. File upload/Site replication does not work and the error is shown
```
Error: unable to replicate for object loki-logs/prod/cd73d82bd1b1d01/18bca207577:18bca207579:b126ba93(null): Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed. (*errors.errorString)
```

## Possible Solution
To me it seems that minio does not use the information of free disk space. Instead it uses the drive usage info `Use%` which is 100% (speculation). Console shows available space
![grafik](https://github.com/minio/minio/assets/1436672/a42a6e93-2230-4547-bf62-727d3f45fa7f)

## Steps to Reproduce (for bugs)

`mc admin trace --verbose xxx`
```
[RESPONSE] [2023-12-12T14:54:27.868] [ Duration 554µs TTFB 542.558µs ↑ 240 B  ↓ 441 B ]
507 Insufficient Storage
...
```

`mc admin subnet health xxx`
```
Command produces stacktrace with latest mc. Maybe this is another issue.
```
<details>
  <summary>Click here to see error/stacktrace of health command</summary>
health flag redefined: config-dir
panic: health flag redefined: config-dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000326f50, {0x14a4238, 0xc0006f7500}, {0x129a19a, 0xa}, {0x12b3508, 0x1c})
        flag/flag.go:1028 +0x3a5
flag.(*FlagSet).StringVar(...)
        flag/flag.go:879
flag.(*FlagSet).String(0x0?, {0x129a19a, 0xa}, {0xc00034be50, 0xe}, {0x12b3508, 0x1c})
        flag/flag.go:892 +0xa5
github.com/minio/cli.StringFlag.ApplyWithError.func1({0x129a19a?, 0xd?})
        github.com/minio/cli@v1.24.2/flag.go:421 +0x8d
github.com/minio/cli.eachName({0x129a19a?, 0xd?}, 0xc0006849a8)
        github.com/minio/cli@v1.24.2/flag.go:94 +0x71
github.com/minio/cli.StringFlag.ApplyWithError({{0x129a19a, 0xd}, {0x12b3508, 0x1c}, {0x129a1a7, 0xd}, 0x0, {0xc00034be50, 0xe}, 0x0}, ...)
        github.com/minio/cli@v1.24.2/flag.go:416 +0x125
github.com/minio/cli.flagSet({0x128f9a0, 0x6}, {0xc0004f8a00, 0x1b, 0xc0006df5e8?})
        github.com/minio/cli@v1.24.2/flag.go:80 +0x12a
github.com/minio/cli.Command.Run({{0x128f9a0, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12c976f, 0x27}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:128 +0x185
github.com/minio/cli.(*App).RunAsSubcommand(0xc00069ca80, 0xc000503520)
        github.com/minio/cli@v1.24.2/app.go:380 +0xca7
github.com/minio/cli.Command.startApp({{0x128f9a6, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12a9a26, 0x17}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:346 +0xb1e
github.com/minio/cli.Command.Run({{0x128f9a6, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12a9a26, 0x17}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:117 +0x418
github.com/minio/cli.(*App).RunAsSubcommand(0xc00069c8c0, 0xc000102680)
        github.com/minio/cli@v1.24.2/app.go:380 +0xca7
github.com/minio/cli.Command.startApp({{0x128e39f, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12a48e2, 0x14}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:346 +0xb1e
github.com/minio/cli.Command.Run({{0x128e39f, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12a48e2, 0x14}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:117 +0x418
github.com/minio/cli.(*App).Run(0xc0001d4000, {0xc00014e000, 0x5, 0x5})
        github.com/minio/cli@v1.24.2/app.go:260 +0xaa7
github.com/minio/mc/cmd.Main({0xc00014e000?, 0x5, 0x5})
        github.com/minio/mc/cmd/main.go:141 +0x431
main.main()
        github.com/minio/mc/main.go:28 +0x2c
</details>

### Reproduce error
* create bucket on server and upload some files
* OR start site replication, e.g. `mc replicate resync start --remote-bucket ...`

## Context
My goal is to combine free space of disks to provide some sort of 'crap-storage' for temporary/unimportant usage.

## Regression
Maybe, but I can say this isn't working for months.

## Your Environment
* Version used (`minio --version`): `2023-12-09T18:17:51Z`
* Operating System and version (`uname -a`): `Linux docker2 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux`
* File system: xfs, no quota
* The drives are full `100%`, but the free space is always at least 40 GB
* Inode usage on every drive is `< 30%`
* Minio runs on k3s
* Space is provided via `persistent volumes` which mount folders
* Block storage cannot be used, because I don't want to shrink partitions

**Comment by klauspost** [comment]
MinIO doesn't fill up space completely - this is by design to remain somewhat operational.

**Comment by stefan-lange** [comment]
> MinIO doesn't fill up space completely - this is by design to remain somewhat operational.

Hm, that was fast. Is this comment still relevant?
https://github.com/minio/minio/issues/6795#issuecomment-590993913

How much space needs to be free for minio to work? 100 GB, 1 TB, 1%?

**Comment by klauspost** [comment]
1% is the hard limit, where we reject new uploads. Start planning expansion at 75% - disk performance degrades significantly above 90%

**Comment by stefan-lange** [comment]
Ok, that's sad. 1% is huge, the former 1GB seemed ok, but there are always 'reasons' for a change.
Disk performance should be the concern of the operator, not Minio.

**Comment by klauspost** [comment]
@stefan-lange It is the "problem" of MinIO when people run their systems beyond reasonable limits. There are too many reasons to go into here.
