### ISSUE TITLE
Polluted user policy mappings with old STS user mappings stalling effective user policies.

### ISSUE THREAD

**Issue by Scapal** [minio/minio#18640]
OpenID Connect users are not applying the policies defined in the `policy` claim.
When exporting the IAM data using `mc admin cluster iam export`, I see entries related to STS users in the `user_mappings.json`.

## Expected Behavior
I would expect the `user_mappings.json` to only contain entries related to the local users present in the `users.json` table.
I would also expect the up to date policy mappings defined in `stsuser_mappings.json`, retrieved from the latest OpenID Connect "policy" claim to be applied.

## Current Behavior
The `updatedAt` in the `user_mappings.json` is "2023-10-19T14:40:53" (only the part after the seconds decimal varies). This file shows the policy mappings as they were back then.

The `updatedAt` and the `policy` fields in the `stsuser_mappings.json` are up to date and accurate.

When using the Console (using OpenID Connect) or using the MinIO Client (with a service account created from the Console), I see that only the old policy is applied.
The permissions in `api/v1/session` called from the Console is correct but is not matching the buckets I have access to.

OpenID users that never logged in before, hence are not in the stalled `user_mappings.json`, have their policies applied correctly. Any change of policies in  the `policy` claim are applied as expected.

## Possible Solution
Is there a way to clean up the `stsuser_mappings.json` to remove stalled info not related to local users.
Even so, why is the `user_mapping.json` taking precedence for STS (OpenID) users ?

## Your Environment
Minio cluster of 4 servers (x4 disks) running version 2023-12-02T10:51:33Z.
OpenID Connect is used as the primary authentication source.
Only 1 local account exists.
No etcd.

**Comment by harshavardhana** [comment]
It should not happen @Scapal have you tried with latest release?

**Comment by Scapal** [comment]
@harshavardhana , yes I have:  2023-12-09T18-17-51Z

**Comment by harshavardhana** [comment]
@Scapal you would have to purge the local entries - there was a bug in the past. Can you wipe it clean and test freshly?

**Comment by Scapal** [comment]
@harshavardhana how would you purge the local entries ? 
I cannot wipe the whole cluster config & data if it is what you mean by test freshly.
Is there a way to access .minio.sys/config/iam/policydb/users/ though a tool or do I have to delete it on each disk of each server ?

**Comment by Scapal** [comment]
Deleting the .minio.sys/config/iam/policydb/users/ unwanted folders on each disk of each server solved the issue. 
Having a low level tool permitting to access the store in a more elegant way would be nice.

Either way, for me there is still a bug since the policy mapping for a STS user shouldn't load mappings from config/iam/policydb/users/ .

There are places in the code where the user type is passed as argument, but other places where both cache are looked up independently of the user type.

With user types consideration : https://github.com/minio/minio/blob/3f72c7fcc72c41c03ceac6f511ad8164f5bd572d/cmd/iam-store.go#L1041
Without regards to the user type: https://github.com/minio/minio/blob/3f72c7fcc72c41c03ceac6f511ad8164f5bd572d/cmd/iam-store.go#L1470

IMHO, we should choose between completely separating the mappings (cache) and handling it correctly or merging them, the current situation looks half baked.

**Comment by harshavardhana** [comment]
No, I am asking that is it reproducible after you have purged everything because I remember fixing a bug related to this already.

**Comment by Scapal** [comment]
After deleting the stalled STS mappings from /.minio.sys/config/iam/policydb/users/ on each disk/server, it stays stable.

Could it be possible that site replication played a role in this ?
I don't use site replication anymore at this point but it is possible that an instance running a slightly older version synchronizing to this instance caused the issue.

Again is there a way to access the .minio.sys object store to troubleshoot a cluster ? Deleting was easy but I was wondering if there was a way to access the files (not the shards) through a cli tool?

**Comment by harshavardhana** [comment]
> Could it be possible that site replication played a role in this ?
> I don't use site replication anymore at this point but it is possible that an instance running a slightly older version synchronizing to this instance caused the issue.

Yes, site-replication had the bug, and it was fixed @Scapal - we do not expect that you manually clean it up. But unfortunately, in this case, we had to.

```
commit 879d5dd2361e7f7f2d27986e8380a7a9efac9ba9
Author: Harshavardhana <harsha@minio.io>
Date:   Thu Nov 30 10:34:18 2023 -0800

    site replication must heal policy mappings with correct userType (#18563)
```
