### ISSUE TITLE
The path to bucket metrics in the docs is incorrect. 

### ISSUE THREAD

**Issue by vanugrah** [minio/minio#18655]
https://github.com/minio/minio/blob/10ca0a6936a0bc3057256ce8d34eb3ba6e63d122/docs/metrics/prometheus/list.md?plain=1#L241

I'm guessing its supposed to be: 

```
/minio/v2/metrics/bucket
```

**Comment by harshavardhana** [comment]
Thanks for pointing it out, feel free to send a fix. Happy to accept.

**Comment by vanugrah** [comment]
Voila:  https://github.com/minio/minio/pull/18661
