### ISSUE TITLE
Validate:  AWS CLI with FS and XL backend.

### ISSUE THREAD

**Issue by GarimaKapoor** [minio/minio#1865]
Aaron has been assigned this bug!

**Comment by harshavardhana** [comment]
// cc @awwalker

**Comment by awwalker** [comment]
Light testing (single commands and operations) done with both XL and FS. Moving onto more stressful tests on XL today.

**Comment by awwalker** [comment]
When doing simultaneous uploads with aws cli cp --recursive 8GB dataset after killing a disk while cp is running there is a panic. The operation completes on other disks but both mc ls and aws s3 ls commands get spotty.

**Comment by awwalker** [comment]
XL and FS both done. AWS cli is responding correctly with latest master. Even taking disks down is working correctly.

**Comment by GarimaKapoor** [comment]
gr8! closing the issue
