### ISSUE TITLE
login invalid user name and password  docker 

### ISSUE THREAD

**Issue by cchalifo999** [minio/minio#18665]
login invalid user name and password with the default  username and the one on the environment variables
Version: RELEASE.2023-12-14T18-51-57Z (go1.21.5 linux/amd64) Running in docker

WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables

with extra environment variables
          -  MINIO_SERVER_HOST=
           - MINIO_BROWSER_REDIRECT_URL=
           - MINIO_SERVER_URL=
and i am running behind a proxy

**Comment by harshavardhana** [comment]
I just ran the latest release with default credentials; it runs fine.

```
minio server /tmp/fresh
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.2023-12-14T18-51-57Z (go1.21.5 linux/amd64)

Status:         1 Online, 0 Offline. 
S3-API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                 
RootUser: minioadmin 
RootPass: minioadmin 

Console: http://10.0.0.185:42627 http://172.17.0.1:42627 http://172.19.0.1:42627 http://127.0.0.1:42627         
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
   $ mc alias set 'myminio' 'http://10.0.0.185:9000' 'minioadmin' 'minioadmin'

Documentation: https://min.io/docs/minio/linux/index.html
Warning: The standard parity is set to 0. This can lead to data loss.
```

Looks like you have some other settings that you need to be made aware of.

**Comment by cchalifo999** [comment]
> I just ran the latest release with default credentials; it runs fine.
> 
> ```
> minio server /tmp/fresh
> WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
> MinIO Object Storage Server
> Copyright: 2015-2023 MinIO, Inc.
> License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> Version: DEVELOPMENT.2023-12-14T18-51-57Z (go1.21.5 linux/amd64)
> 
> Status:         1 Online, 0 Offline. 
> S3-API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                 
> RootUser: minioadmin 
> RootPass: minioadmin 
> 
> Console: http://10.0.0.185:42627 http://172.17.0.1:42627 http://172.19.0.1:42627 http://127.0.0.1:42627         
> RootUser: minioadmin 
> RootPass: minioadmin 
> 
> Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
>    $ mc alias set 'myminio' 'http://10.0.0.185:9000' 'minioadmin' 'minioadmin'
> 
> Documentation: https://min.io/docs/minio/linux/index.html
> Warning: The standard parity is set to 0. This can lead to data loss.
> ```
> 
> Looks like you have some other settings that you need to be made aware of.

did you put the domain name on it

**Comment by cchalifo999** [comment]
> I just ran the latest release with default credentials; it runs fine.
> 
> ```
> minio server /tmp/fresh
> WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
> MinIO Object Storage Server
> Copyright: 2015-2023 MinIO, Inc.
> License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> Version: DEVELOPMENT.2023-12-14T18-51-57Z (go1.21.5 linux/amd64)
> 
> Status:         1 Online, 0 Offline. 
> S3-API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                 
> RootUser: minioadmin 
> RootPass: minioadmin 
> 
> Console: http://10.0.0.185:42627 http://172.17.0.1:42627 http://172.19.0.1:42627 http://127.0.0.1:42627         
> RootUser: minioadmin 
> RootPass: minioadmin 
> 
> Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
>    $ mc alias set 'myminio' 'http://10.0.0.185:9000' 'minioadmin' 'minioadmin'
> 
> Documentation: https://min.io/docs/minio/linux/index.html
> Warning: The standard parity is set to 0. This can lead to data loss.
> ```
> 
> Looks like you have some other settings that you need to be made aware of.

did you add 
    - MINIO_SERVER_URL: 'https://somedomain.com'
    -  MINIO_SERVER_HOST: 'somehost.com'
    -  MINIO_BROWSER_REDIRECT_URL: 'https://somedomain.com'

**Comment by cchalifo999** [comment]
> I just ran the latest release with default credentials; it runs fine.
> 
> ```
> minio server /tmp/fresh
> WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
> MinIO Object Storage Server
> Copyright: 2015-2023 MinIO, Inc.
> License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> Version: DEVELOPMENT.2023-12-14T18-51-57Z (go1.21.5 linux/amd64)
> 
> Status:         1 Online, 0 Offline. 
> S3-API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                 
> RootUser: minioadmin 
> RootPass: minioadmin 
> 
> Console: http://10.0.0.185:42627 http://172.17.0.1:42627 http://172.19.0.1:42627 http://127.0.0.1:42627         
> RootUser: minioadmin 
> RootPass: minioadmin 
> 
> Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
>    $ mc alias set 'myminio' 'http://10.0.0.185:9000' 'minioadmin' 'minioadmin'
> 
> Documentation: https://min.io/docs/minio/linux/index.html
> Warning: The standard parity is set to 0. This can lead to data loss.
> ```
> 
> Looks like you have some other settings that you need to be made aware of.

i finle got it to work

**Comment by tianxingdao** [comment]
> > I just ran the latest release with default credentials; it runs fine.
> > ```
> > minio server /tmp/fresh
> > WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
> > MinIO Object Storage Server
> > Copyright: 2015-2023 MinIO, Inc.
> > License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
> > Version: DEVELOPMENT.2023-12-14T18-51-57Z (go1.21.5 linux/amd64)
> > 
> > Status:         1 Online, 0 Offline. 
> > S3-API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                 
> > RootUser: minioadmin 
> > RootPass: minioadmin 
> > 
> > Console: http://10.0.0.185:42627 http://172.17.0.1:42627 http://172.19.0.1:42627 http://127.0.0.1:42627         
> > RootUser: minioadmin 
> > RootPass: minioadmin 
> > 
> > Command-line: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
> >    $ mc alias set 'myminio' 'http://10.0.0.185:9000' 'minioadmin' 'minioadmin'
> > 
> > Documentation: https://min.io/docs/minio/linux/index.html
> > Warning: The standard parity is set to 0. This can lead to data loss.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looks like you have some other settings that you need to be made aware of.
> 
> i finle got it to work

I have the same problem. Can you tell me how to solve it? thank you.

**Comment by digitalextremist** [comment]
Would bet that the solution for @cchalifo999 was to change `MINIO_SERVER_HOST` to `http` schema.

Had that same issue with the `bitnami` and `quay.io` and outdated `minio/minio` docker images, until this:

```
MINIO_SERVER_HOST=http://ip-or-hostname`
```

Whether that is correct or not is for another day. At least it is working for local development and testing.
