### ISSUE TITLE
cors_allow_origin decode error

### ISSUE THREAD

**Issue by jyxjjj** [minio/minio#18660]
## NOTE

I don't know how to desc it correctly, i found if i set cors with console, then the xl.meta file doesn't have a correct value. and cors will failed. You can see my screenshot for more info.

## Expected Behavior
xl.meta file will be the same with config/api interface response.

## Current Behavior
![image](https://github.com/minio/minio/assets/16695261/74610faa-3c3b-4205-ba12-1f91e11a3f0b)

## Possible Solution
decoder is wrong.

## Steps to Reproduce (for bugs)

1. DO NOT SET MINIO_API_CORS_ALLOW_ORIGIN in env file
2. manually set cors with console page settings/configurations/api
3. read xl.meta (didn't modified)
4. 

## Context
When i set it with console:
```
{"key":"cors_allow_origin","value":"https://xxxxxxxxxx\" replication_workers=\"1\" replication_failed_workers=\"1"}
```
When i manually edit it:
```
see the difference in the screenshot above.
```

there is `\` added and `replication_workers` and `replication_failed_workers` doesn't be a valid key.

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-12-14T18-51-57Z (commit-id=6c89a81af43316fe6c82420034b8a048631a1f70)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
```
wget and systemctl
```
* Operating System and version (`uname -a`):
```
Linux fedora 6.6.6-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Dec 11 17:29:08 UTC 2023 x86_64 GNU/Linux
```

**Comment by jyxjjj** [comment]
The left browser is which config/api returns after i manually edit xl.meta's data.
The right browser is what i manually edited xl.meta's data.

**Comment by jyxjjj** [comment]
When I edit the CORS configuration directly through the console, this data appears with backslashes and CORS fails, when I manually edit this file, CORS works fine, but the console does not render the data properly.

**Comment by jyxjjj** [comment]
The data at the beginning of this file cannot be accessed using a human-readable text editor and I have not modified this.

**Comment by jyxjjj** [comment]
Note again that it was not my modifications that caused problems in the console, but that there was a problem with the console itself which could not be discovered, then resulted in configuration file errors and CORS failure. However, my modifications allowed the console errors to be discovered and CORS successfully.

**Comment by harshavardhana** [comment]
> The data at the beginning of this file cannot be accessed using a human-readable text editor and I have not modified this.

Backend data should not be read directly, it is not supposed to be readable.

**Comment by jyxjjj** [comment]
> > The data at the beginning of this file cannot be accessed using a human-readable text editor and I have not modified this.
> 
> 
> 
> Backend data should not be read directly, it is not supposed to be readable.
> 
> 

You didn't read the whole issue, i didn't say i am reading it, it just a step to describe how this issue happened

**Comment by harshavardhana** [comment]
> You didn't read the whole issue, i didn't say i am reading it, it just a step to describe how this issue happened

The entire issue looks bogus to me, there is nothing you are saying that makes any sense.

**Comment by harshavardhana** [comment]
Set from Console UI

![image](https://github.com/minio/minio/assets/622699/23bd3c82-48c5-432a-a397-83842b9029c3)

Visible in Config Get

```
mc admin config get alias/ api
# MINIO_API_STALE_UPLOADS_CLEANUP_INTERVAL=1h
# MINIO_API_STALE_UPLOADS_EXPIRY=6h
# MINIO_API_DELETE_CLEANUP_INTERVAL=5s
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=https://*.minio.io,https://*.min.io remote_transport_deadline=2h list_quorum=strict replication_priority=auto replication_max_workers=500 transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m odirect=on gzip_objects=off root_access=on sync_events=off 
```

**Comment by jyxjjj** [comment]
> Set from Console UI
> ...
> ...
> 

Yes, that's what I did at first, but I cannot let CORS be success after this.
I didn't do anything else then it didn't send any Access-Control headers.
***Only after i edited this xl.meta*** then i can get CORS headers correctly.

Bucket Policy is:
Anonymous read-only

I didn't installed mc, i don't know if get is correct.

**Comment by jyxjjj** [comment]
## Solved

Tested in `RELEASE.2024-06-11T03-13-30Z` and it was solved.
I am now know how this issue happened.

---

1. Last time( `RELEASE.2023-12-14T18-51-57Z` ), The console has maybe network issue (cloudflare transferred the traffic twice, each time for the half an earth), cannot save the configuration file successfully.
2. I edited it, json file is valid, `mc` and minio itself will successfully get the cors data.
3. Console webpage will not, due to `xl.meta` has data length (maybe) (Yeah, you said it is not for read).

![image](https://github.com/minio/minio/assets/16695261/c7a75e38-3269-40d3-aaf4-7cac1df24aad)

---

I am here to clarify that we both had been wrong.

---

1. My test case was all truly, you should not deny it, but i should not create this issue before i didn't make sure if it is a network issue.
2. I don't know what does `xl.meta`'s file header has, I should decode it via codes. Or edit it manually via `mc` or my codes like you said. Instead of thinking about `hey, is it a console webpage issue?` at the beginning.

---

4. You should not just only say it was not for read/edit, or you don't know why it cannot be.
5. Open Source Community is kind, different with business.
