### ISSUE TITLE
MinIO Grafana dashboard should not discern between minio servers when counting buckets

### ISSUE THREAD

**Issue by caspereijkens** [minio/minio#18672]
The metric `minio_cluster_bucket_total` contains a `server` label which tells which server the metric is coming from. This causes issues in the dashboard because it will differentiate between servers on various tiles.

The Grafana dashboard used to correctly tell us the number of buckets in the the statefulset using 

```
count(count by (bucket) (minio_bucket_usage_total_bytes{job="$scrape_jobs"}))
```
## Expected Behavior
This tile used to look like this:

![image](https://github.com/minio/minio/assets/64551820/beb3c9ea-3b25-4b0e-a2f5-e250181150f6)

## Current Behavior
Now it looks like this:
<img width="1916" alt="Screenshot 2023-12-18 160617" src="https://github.com/minio/minio/assets/64551820/a4ec2ca4-3b58-494c-a24e-5d7f28466822">

This happens because the `minio_cluster_bucket_total` metric also stores which server the metric is coming from. Then the grafana tile differentiates on `server`.

## Possible Solution
Please adjust either the metric or the dashboard to aggregate this metric, by using for example 

```
max(minio_cluster_bucket_total{job="$scrape_jobs"})
```

**Comment by shtripat** [comment]
Latest grafana dashboard has correct expression https://github.com/minio/minio/blob/master/docs/metrics/prometheus/grafana/minio-dashboard.json#L1074 as ` "expr": "max(minio_cluster_bucket_total{job=\"$scrape_jobs\"})"` 

A screenshot from latest dashboard as below
![Screenshot from 2023-12-21 13-12-17](https://github.com/minio/minio/assets/6771252/b81ea968-2dda-4fc8-93d4-6a3220d5cf62)

**Comment by caspereijkens** [comment]
Thanks a lot for fixing this. There are a few more panels where this is an issue though. 

Some examples:

![image](https://github.com/minio/minio/assets/64551820/8cce774c-7df0-431c-a767-4865f7b1d61a)

<img width="926" alt="image" src="https://github.com/minio/minio/assets/64551820/f1c44b06-31e6-47c3-bded-82cc5e593a72">

<img width="943" alt="image" src="https://github.com/minio/minio/assets/64551820/eec3198c-4aa8-464c-a108-c283df2887c9">

**Comment by caspereijkens** [comment]
I can see some merit in displaying the metrics per server but this makes the panels illegible.
