### ISSUE TITLE
Scanner performance too slow on fastest setting.

### ISSUE THREAD

**Issue by Jazz9** [minio/minio#18677]
We have replaced a server in the cluster. The full disk heal is completed but the drives are showing less than expected data. We are trying to complete a full scanner pass ASAP.

The scanner is set to 'fastest' 

![image](https://github.com/minio/minio/assets/39378577/46747478-c3b8-45be-9ba8-ee346a20d9a8)

![image](https://github.com/minio/minio/assets/39378577/76889c26-868c-4b06-aed5-68b29637df48)

Drives are idle
![image](https://github.com/minio/minio/assets/39378577/7b377e14-4396-43f2-b93c-4782b4af2a17)

## Expected Behavior
To have consistent performance of the scanner. To have more than 2 drives active. To maintain a queue depth of 8+ on 'fastest' setting.

## Current Behavior
When Minio is restarted - the scanner uses 12 drives to scan. After 24h the scanner is only using 2.

## Steps to Reproduce (for bugs)
Reformat server with HDD drives - wait 24h. Have a cluster with 200+TB of ~1M files.

## Context
Likelihood of data loss increases with the excessive time to rebuild a node.

## Your Environment
* 6 x ubuntu 22 servers with 12 x enterprise SATA 18TB drives, 2 x 10gbit, 192GB ram.
* Version RELEASE.2023-12-14T18-51-57Z

**Comment by harshavardhana** [comment]
Your average read for metadata is already at 40ms, it cannot be made faster than this.

An entire cycle in total takes 12days.

If you want to run a more targeted heal you can run it proactively via `mc admin heal -r --remove alias/`

**Comment by harshavardhana** [comment]
Your average object size is 414 bytes per object on a SATA disk with erasure coding?.

I have no idea why do you guys do this to yourself. HDDs are never designed for such small objects let alone be erasure coded across nodes.

**Comment by Jazz9** [comment]
How do you figure 414byte file size? ( that is the avg metadata size )

Even with such small file sizes - that doesn't explain the issue? - The drives should be busy on fastest?

**Comment by Jazz9** [comment]
I think I can ask the question better:

The individual drive scanning speed is ok. The 2 drives that are scanning are 140 IOPS / 2-3 queue depth, 40 ms read avg.

The rest of the cluster is not busy. How do we increase the number of drives scanning?
