### ISSUE TITLE
broken repo url in artifacthub helm chart reference

### ISSUE THREAD

**Issue by rochaporto** [minio/minio#18685]
Artifacthub has an entry describing the helm chart from minio:
https://artifacthub.io/packages/helm/minio/minio

Given this is in the `minio` org, it looks supported. There's a note about a code freeze, but the repo referenced is just gone.

## Expected Behavior

Installing the helm chart following the instructions should work:
```
$ helm repo add minio https://helm.min.io/
```

## Current Behavior

The repo url is giving a 404:
```
$ helm repo add minio https://helm.min.io/
Error: looks like "https://helm.min.io/" is not a valid chart repository or cannot be reached: failed to fetch https://helm.min.io/index.yaml : 404 Not Found
```

## Possible Solution

The new location for the community chart - charts.min.io - does not have the versions referenced in artifacthub. A few things:
* maybe update the artifacthub entry to point to the new repo location
* at least reference the community chart in the description in addition to the operator variant
* delete or make it clear the instructions in the repo no longer work

## Steps to Reproduce (for bugs)

The only required step is referenced above.

## Context

Any end user looking for a helm chart might end up finding it in artifacthub. There are several options, but this one looks like an official one (given the `minio` org). Cleaning up old/invalid information will save time to everyone, and linking to the new chart as well.

## Regression

No.

## Your Environment

All info above, nothing specific to the environment.

**Comment by harshavardhana** [comment]
We do not maintain that ourselves, and it has never been updated - please do not use that link refer to our official docs on deploying operator

https://min.io/docs/minio/kubernetes/upstream/index.html

**Comment by rochaporto** [comment]
This one is hosted in this repo.
https://github.com/minio/minio/tree/master/helm/minio

Here's another one called `minio-official`, pointing to that repo:
https://artifacthub.io/packages/helm/minio-official/minio

I did read the disclaimer about this helm chart being community supported, but since you host it... if not here where should i open an issue for the community to try to help users of MinIO?

**Comment by ravindk89** [comment]
I'll poke to see if we still have a login to artifacthub hanging around, but I tested the official entry and it works:

```
    ~/git/mincat-docs    main !1  helm search repo minio-community                                                                                                 ✔  k3d-MINIO ⎈ 
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ravindkminio/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ravindkminio/.kube/config
NAME                    CHART VERSION   APP VERSION                     DESCRIPTION               
minio-community/minio   5.0.14          RELEASE.2023-09-30T07-02-29Z    Multi-Cloud Object Storage
    ~/git/mincat-docs    main !1                                                                                                                                                 ✔ 
    ~/git/mincat-docs    main !1  helm repo list                                                                                                                   ✔  k3d-MINIO ⎈ 
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ravindkminio/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ravindkminio/.kube/config
NAME            URL                    
minio-operator  https://operator.min.io
minio-community https://charts.min.io/ 
    ~/git/mincat-docs    main !1        
```

**Comment by rochaporto** [comment]
@ravindk89 that's correct, the one at charts.min.io is working fine - but doesn't have the versions pointed in the 'minio' artifacthub (8.x.x). The old repo (helm.min.io) is supposed to have those but is now giving a 404, which is fine but might be worth fixing references to it or warning users it's no longer available - and redirect to the new community chart.

**Comment by ravindk89** [comment]
Yep - I'm trying to figure out where the login went, because as noted I think these page have gone largely unmaintained for a long while. 

I will say it's safe to assume any versions listed in the `minio` hub are gone with the wind. I have no idea how we'd restore or export them to the official chart, nor do I think there would be much appetite to make it happen.
