### ISSUE TITLE
Healing of a drive paused on a single file

### ISSUE THREAD

**Issue by Jazz9** [minio/minio#18687]
I have been trying to heal a complete server and the progress has stopped.

It ran overnight and when I checked the progress in the morning, it has been stuck for hours on this file.

![image](https://github.com/minio/minio/assets/39378577/eff97c5e-4763-4e5b-bc3e-170206e0d29d)

Please let me know what info you require to assist debugging.

## Expected Behavior
Continue healing / timeout on file if needed.

## Current Behavior
Healing stops.

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
Reformat and heal the drive.

## Context
I believe it is the root cause for #18679 also.

## Your Environment
6 x ubuntu 22 servers with 12 x enterprise SATA 18TB drives, 2 x 10gbit, 192GB ram.
Version RELEASE.2023-12-14T18-51-57Z

**Comment by harshavardhana** [comment]
There must be something wrong with the object itself - we would need to know a few more things such as 

```
mc support top locks alias/ --json
```

output, you would need a SUBNET subscription for that.

**Comment by Jazz9** [comment]
Is there a way to purchase a support subscription for an issue?

I'll re-run the heal and see if it stops at the same object.

**Comment by harshavardhana** [comment]
@Jazz9 you would have to restart the cluster and run the `mc admin heal -r --json --remove alias/` again

**Comment by Jazz9** [comment]
Also noticed that the Minio admin web portal won't logon either.

All servers point to min04 as the cause in the logs:

![image](https://github.com/minio/minio/assets/39378577/e22b9e64-3517-4542-90b1-d24ff678e96f)

min04 points to a file being the issue:

![image](https://github.com/minio/minio/assets/39378577/5b24c2ac-f32c-426c-a2e6-1d196b168e44)

All drives are accessible in the OS and other minio instances:

![image](https://github.com/minio/minio/assets/39378577/8603c069-4bd6-4166-ba88-b689ec76c060)

There are also these errors:

![image](https://github.com/minio/minio/assets/39378577/36d153de-f62d-483e-8dbb-d278669fb9bb)

I'm going to reboot the minio instance on min04 and report back in 24 hours.

**Comment by klauspost** [comment]
You probably have a disk going bad.

**Comment by Jazz9** [comment]
The files that it is complaining about are across multiple disks - so maybe a controller. 

I've restarted the Minio process and it is working again now. I'll continue to monitor.
