### ISSUE TITLE
XL: Incorrect behaviour for CompleteMultipartUpload. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1868]
Here is the test case to reproduce https://gist.github.com/hackintoshrao/17195ba97df5057ad4082ac8f2649532
## Expected behaviour

See the test. 
## Actual behaviour

See the test.
## Steps to reproduce the behaviour

Run the test. 
## Minio version (paste output of `minio version`)

Latest master
## System information

OSX El Captain 64 bit. 

Here is the brief description of he issue. 
- A Part with the incorrect size parameter is inserted [here](https://gist.github.com/hackintoshrao/17195ba97df5057ad4082ac8f2649532#file-object-api-multipart_test-go-L50) . The actual size of the part is 4, but 6 is send as parameter. (Larger than the actual size). 
- Since there is no check on the actual number of bytes of data read from the reader and the size parameter, the wrong value will be inserted into the json configuration of the part. One solution of the solution could be to put a check inside `PutObjectPart` for mismatch between the size argument and the actual number of bytes read from the `ReadCloser`. Gotto check with the s3 standards that a Part with the incorrect size parameter can be inserted. 
- This leads to incorrect size stored for the part in the config. 
- An incorrect info about the size of  the part in the its json configuration is misleading. 
- Then a completePart array is formed using the malformed part [here](https://gist.github.com/hackintoshrao/17195ba97df5057ad4082ac8f2649532#file-object-api-multipart_test-go-L85) . 
- Then the malformed part is send as input for `CompleteMultipartUpload` [here](https://gist.github.com/hackintoshrao/17195ba97df5057ad4082ac8f2649532#file-object-api-multipart_test-go-L141). 

And when you run the test, FS fails with an `EOF` trying to read the part and surprisingly XL passes. 
Here is the result of the run.

```
=== RUN   TestObjectCompleteMultipartUpload
--- FAIL: TestObjectCompleteMultipartUpload (0.53s)
    object-api-multipart_test.go:1508: Test 1: SingleNode: Expected to fail with error "One or more of the specified parts could not be found", but instead failed with error "EOF"
    object-api-multipart_test.go:1503: Test 1: XL: Expected to fail with <ERROR> "One or more of the specified parts could not be found", but passed instead
FAIL
exit status 1

```

**Comment by harshavardhana** [comment]
> And when you run the test, FS fails with an EOF trying to read the part and surprisingly XL passes.

Surprising fact is XL doesn't read the parts instead it just validates if they match with the data in `xl.json`

**Comment by harshavardhana** [comment]
> Since there is no check on the actual number of bytes of data read from the reader and the size parameter, the wrong value will be inserted into the json configuration of the part. One solution of the solution could be to put a check inside PutObjectPart for mismatch between the size argument and the actual number of bytes read from the ReadCloser. Gotto check with the s3 standards that a Part with the incorrect size parameter can be inserted.

We are supposed to save the size of the data read instead of blindly from the 'size' param, this is equal to the change which we did with single PutObject().

**Comment by krisis** [comment]
This issue should be fixed by EOD Jun 8th

**Comment by krisis** [comment]
This is not an issue with `fs` or `xl` object layer implementations for the following reasons.
1) The test code is invoking multipart methods of `fs` and `xl` implementations, which aren't aware of the s3 protocol, namely signature validation. 
2) The difference in content-length and the size of the request body is caught by the signature verification process and on failing should return `errSignatureMismatch`.

The object layer implementations aren't expected to handle this. So, closing this as not an issue.
