### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by fangzhouxie** [minio/minio#18691]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

No `fatal error: concurrent map read and map write`.

## Current Behavior

```
fatal error: concurrent map read and map write

goroutine 68259931062 [running]:
github.com/minio/console/restapi.(*wsMinioClient).objectManager.func2.1()
        github.com/minio/console@v0.40.0/restapi/ws_objects.go:102 +0x27b
created by github.com/minio/console/restapi.(*wsMinioClient).objectManager.func2 in goroutine 68255006116
        github.com/minio/console@v0.40.0/restapi/ws_objects.go:94 +0x45f

goroutine 1 [chan receive, 30438 minutes]:
github.com/minio/minio/cmd.serverMain(0xc000b02b60)
        github.com/minio/minio/cmd/server-main.go:970 +0xedc
github.com/minio/cli.HandleAction({0x25994e0?, 0x467e1a0?}, 0x6?)
        github.com/minio/cli@v1.24.2/app.go:492 +0x70
github.com/minio/cli.Command.Run({{0x2aee43e, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x2b2b7e7, 0x1b}, {0x0, ...}, ...}, ...)
        github.com/minio/cli@v1.24.2/command.go:242 +0x965
github.com/minio/cli.(*App).Run(0xc000eddc00, {0xc000260120, 0x6, 0x6})
        github.com/minio/cli@v1.24.2/app.go:260 +0xaa7
github.com/minio/minio/cmd.Main({0xc000260120?, 0x6, 0x6})
        github.com/minio/minio/cmd/main.go:215 +0xe8
main.main()
        github.com/minio/minio/main.go:30 +0x28
```

## Steps to Reproduce (for bugs)

Unfortunately, I'm not able to reproduce it. But I'm happy to provide any additional information that may help identify the issue.

## Context

This fatal error occurred in one of the 10 nodes in our MinIO cluster. Our MinIO cluster has been stable. This is the first time we saw this type of fatal error. We didn't notice any abnormal activities in the node before the fatal error happened and killed the node.

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2023-10-24T04-42-36Z (commit-id=2dc917e87f12166e4cfc3b1be24cf2bf70b29bbd)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
A cluster of 10 nodes.
* Operating System and version (`uname -a`):
```
Linux minio-research-ss-2-7 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@fangzhouxie please upgrade to latest release and let us know if this is still reproducible.
