### ISSUE TITLE
listObjects doesn't return Metadata anymore

### ISSUE THREAD

**Issue by mmoser18** [minio/minio#18695]
We recently upgraded to `minio.RELEASE.2023-10-16T04-13-43Z` and had to learn that in this version (and also in later ones that we tried since) the `listObjects`-call does not return the objects' metadata anymore as it used to. Before we had been using `minio.RELEASE.2022-10-24T18-35-07Z`.

For us this is a big issue since we have a job that queries a list of ALL objects and then filters them based on some user-defined metadata field (`x-amz-meta-<something>`). This call was reasonably efficient.

Now the `listObjects`-call does not return any metadata anymore (they are always returned as "null"), thus the subsequent filtering does not work anymore. We would have to read and transfer essentially the *entire* DB each time (using a `getObject`-call for each object returned to get hold of the metadata flags) and this would be prohibitively expensive. 

Is that decision and change in MinIO's behavior to not return the metadata anymore with `listObjects` definitive ? Could that be made dependent on some (optional) argument whether one wants the metadata included in the result or not? 
I consider that really a major breaking change that came without any warning!

**Comment by harshavardhana** [comment]
listObjects() in S3 API never returns user metadata - MinIO only implemented an extension for this API with `metadata=true` query param. 

IT is implemented to be used by `mc mirror` and some other internal tools. It is not meant for something to be relied upon @mmoser18 we have never published the API spec.

Which client SDK are you using? and show us some sample code.

**Comment by mmoser18** [comment]
> listObjects() in S3 API never returns user metadata 

Well - it obviously did the last two or so years since we are using MinIO.

We tried with minio api 8.4.4, 8.5.2 and 8.5.7 (latest)

The code we use to generate that call is
```
import io.minio.MinioClient;
...
 private final MinioClient minioClient;
...
    private Iterable<Result<Item>> getAllAttachments() {
        return minioClient.listObjects(ListObjectsArgs.builder()
            .bucket(bucketName)
            .includeUserMetadata(true)
            .build());
    }
```

**Comment by klauspost** [comment]
Also note the user must have `s3:GetObject` permissions for metadata to be returned.

(and `s3:GetObjectTagging` to receive tags)

**Comment by mmoser18** [comment]
OK - trying to summarize: 
with the latest version(s) there is no option, flag, permission or whatever that would cause the listObjects-call to return metadata again. I.e. we would need to _read the entire DB_ to obtain and filter on metadata-fields which I consider a no-go.

I just read about tags in MinIO (which we hadn't used so far). On first read it appears as a possible solution to change our meta-data-fields to tags. Just one question: The number of tags (i.e. names of these name-value pairs) seems to be limited to 10. But I guess/hope the values are not limited, right? Because in our case these values would be UUIDs and there would be many different values.

**Comment by klauspost** [comment]
@mmoser18 Did you read what we wrote? There is no change and MinIO can return metadata in listings if you A) ask for it and B) the user has permissions for it.

**Comment by mmoser18** [comment]
Ah - sorry: that "metadata=true" was not just referring to the `mc mirror` but can be specified for each listObjects? I had understood that text such that this was only meant for internal tools. 
OK - then we would be back in business.

**Comment by klauspost** [comment]
Yes. You just set it as a parameter on the request. Most of our SDKs should help you. For example in Go you have [ListObjectsOptions.WithMetadata](https://pkg.go.dev/github.com/minio/minio-go/v7#ListObjectsOptions).

**Comment by droslean** [comment]
@klauspost It seems that the metadata is still empty when listing the objects. Is there any other BUG ongoing or this was never fixed?

**Comment by klauspost** [comment]
@droslean Could you post a complete request+response?

**Comment by droslean** [comment]
```go
client.ListObjects(l.ctx, l.bucketName, minio.ListObjectsOptions{Recursive: true, WithMetadata: true})
```

```
 OBJECT: minio.ObjectInfo{ETag:"XXXXXXXX", Key:"common/certifications/PNG/cert.png", LastModified:time.Date(2024, time.January, 18, 15, 1, 53, 288000000, time.UTC), Size:16968, ContentType:"", Expires:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Metadata:http.Header(nil), UserMetadata:minio.StringMap(nil), UserTags:minio.URLMap(nil), UserTagCount:0, Owner:minio.Owner{XMLName:xml.Name{Space:"http://s3.amazonaws.com/doc/2006-03-01/", Local:"Owner"}, DisplayName:"12345", ID:"12345"}, Grant:[]minio.Grant(nil), StorageClass:"STANDARD", IsLatest:false, IsDeleteMarker:false, VersionID:"", ReplicationStatus:"", ReplicationReady:false, Expiration:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), ExpirationRuleID:"", Restore:(*minio.RestoreInfo)(nil), ChecksumCRC32:"", ChecksumCRC32C:"", ChecksumSHA1:"", ChecksumSHA256:"", Internal:(*struct { K int; M int })(nil), Err:error(nil)}

```

**Comment by harshavardhana** [comment]
@droslean what is your server version? type of setup? can you provide `mc stat --debug` output on the object name?

**Comment by droslean** [comment]
@harshavardhana @klauspost I see https://github.com/minio/minio-go/blob/6ad2b4a17816b1e991f73e598885c07704aea7ef/api-list.go#L196

But based on the S3 API documentation that argument doesn't exist. Can you guys help me understand how I can get the metadata when listing the objects?

**Comment by droslean** [comment]
Also, what is the purpose of this: https://github.com/minio/minio-go/blob/6ad2b4a17816b1e991f73e598885c07704aea7ef/api-list.go#L688-L689
?

**Comment by klauspost** [comment]
This is a MinIO extension. S3 does not provide this information as you point out.

**Comment by droslean** [comment]
> This is a MinIO extension. S3 does not provide this information as you point out.

Thanks @klauspost. So using minio as a library against an S3 bucket is unreliable. I guess I should deploy MinIO and let my clients to use it instead of direct calls to S3?

**Comment by klauspost** [comment]
@droslean It is free software. You are free to do what you please. But adding snarky remarks is not going to help you. I will add a note to the documentation when I get around to it.
