### ISSUE TITLE
Validate: Minio SDK with FS and XL Backend

### ISSUE THREAD

**Issue by GarimaKapoor** [minio/minio#1870]

**Comment by koolhead17** [comment]
XL: Done

**Comment by koolhead17** [comment]
FS: Python: Done

**Comment by koolhead17** [comment]
FS: Java, Node, Go : Done

Blocker bug reported: https://github.com/minio/minio-js/issues/455

**Comment by GarimaKapoor** [comment]
Perfect!

**Comment by harshavardhana** [comment]
> Blocker bug reported: minio/minio-js#455

Bug is fixed, need to test again.
