### ISSUE TITLE
claim missing from the JWT token, credentials will not be generated（use keycloak）

### ISSUE THREAD

**Issue by zhengdechang** [minio/minio#18709]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Log in to minio using keycloak
## Current Behavior

![image](https://github.com/minio/minio/assets/77528948/ca72c4f1-bf31-4212-ba83-f4385c8314e3)

## Steps to Reproduce (for bugs)

1.Follow the minio documentation，Document link：
https://min.io/docs/minio/macos/operations/external-iam/configure-keycloak-identity-management.html
2.minio configuration
![image](https://github.com/minio/minio/assets/77528948/a310aa19-08fa-428e-a6a8-d8f156dd1bac)
The problem here is that the claim name and claim prefix cannot be set to empty. The default values have also been tried, but they are not working
3. login
![image](https://github.com/minio/minio/assets/77528948/ca72c4f1-bf31-4212-ba83-f4385c8314e3)

## Your Environment

* Version used (`minio --version`): 2021-12-27T07:23:18Z
* Server setup and configuration:  truenasservice in truenas
* Operating System and version (`uname -a`): ubuntu22.04

**Comment by harshavardhana** [comment]
@zhengdechang 

- upgrade your MinIO
- second make sure your IDP provides the right policy claim name in the JWT.

Documentation explains this already..

**Comment by zhengdechang** [comment]
Do I have to upgrade? I use the service in truenas and upgrading doesn't seem to be that good

**Comment by harshavardhana** [comment]
> Do I have to upgrade? I use the service in truenas and upgrading doesn't seem to be that good

If you are using TrueNAS. You need to ask them to provide you an upgrade path.
