### ISSUE TITLE
impossible to elimate listen on ipv6 of port 9000

### ISSUE THREAD

**Issue by wxmeng04** [minio/minio#18715]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

The purpose is to remove listen on ipv6 address. But the configuration of `--address` is not working.
```
┌──(root💀tcs01)-[~]
└─# systemctl status minio
● minio.service - MinIO
     Loaded: loaded (/lib/systemd/system/minio.service; disabled; preset: enabled)
     Active: active (running) since Wed 2023-12-27 09:10:21 CST; 10s ago
       Docs: https://docs.min.io
    Process: 226952 ExecStartPre=/bin/bash -c if [ -z "${MINIO_VOLUMES}" ]; then echo "Variable MINIO_VOLUMES not set in /etc/default/minio"; exit 1; fi (code=exited, status=0/SUCCESS)
   Main PID: 226954 (minio)
      Tasks: 8
     Memory: 91.6M
        CPU: 476ms
     CGroup: /system.slice/minio.service
             └─226954 /usr/local/bin/minio server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /mnt/minio
```

## Expected Behavior

No tcp listen on ipv6 address.
## Current Behavior

It's listening on both ipv4 and ipv6 of port 9000. However it's listening on ipv4 only for port 9001.
tcp                   LISTEN                 0                      4096                                       127.0.0.1:9000                                         0.0.0.0:*                     users:(("minio",pid=226954,fd=11))                    
tcp                   LISTEN                 0                      4096                                         0.0.0.0:9001                                         0.0.0.0:*                     users:(("minio",pid=226954,fd=9))                     
tcp                   LISTEN                 0                      4096                                           [::1]:9000                                            [::]:*                     users:(("minio",pid=226954,fd=12))                    
tcp                   LISTEN                 0                      4096                                               *:9000                                               *:*                     users:(("minio",pid=226954,fd=10))
## Possible Solution

I'm not sure. It seems not a configuration problem.
## Steps to Reproduce (for bugs)

Install `minio_20231223071911.0.0_amd64.deb` on Debian bookwork and start with below options
*MINIO_OPTS="--address 0.0.0.0:9000 --console-address 0.0.0.0:9001"*

## Your Environment

* Version used (`minio --version`): minio_20231223071911.0.0_amd64.deb
* Server setup and configuration: MINIO_OPTS="--address 0.0.0.0:9000 --console-address 0.0.0.0:9001
* Operating System and version (`uname -a`): Debian 12(bookworm)

**Comment by harshavardhana** [comment]
Just turn off all IPv6 we won't be listening on it as well.

```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
```

**Comment by wxmeng04** [comment]
> Just turn off all IPv6 we won't be listening on it as well.
> 
> ```
> sysctl -w net.ipv6.conf.all.disable_ipv6=1
> ```

Definitely it works if all ipv6 adress is disabled. But the purpose is to not listen on ipv6 for minio only as other service can be configured and as what you have done on port 9001. May I understand you are working on it and the function will be available in future release?

**Comment by wxmeng04** [comment]
To be more concise, please check below listening list. minio is listening on ipv4 of port 9001 as indicated at Line 2. The other three lines for port 9000 include both ipv4 and ipv5.
tcp LISTEN 0 4096 127.0.0.1:9000 0.0.0.0:* users:(("minio",pid=226954,fd=11))
tcp LISTEN 0 4096 0.0.0.0:9001 0.0.0.0:* users:(("minio",pid=226954,fd=9))
tcp LISTEN 0 4096 [::1]:9000 [::]:* users:(("minio",pid=226954,fd=12))
tcp LISTEN 0 4096 *:9000 : users:(("minio",pid=226954,fd=10))
