### ISSUE TITLE
minio ignores certificates, uses http instead of https and denies login

### ISSUE THREAD

**Issue by harridu** [minio/minio#18720]
Maybe its just me, but since I upgraded to minio_20231223071911.0.0_amd64.deb on Debian 12 (real hardware) minio doesn't use the letsencrypt certs anymore. It uses http on port 8443 and 9010. The minioadmin password is not accepted, ie I cannot login.

/etc/default/minio is
```
# see https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio-server-environment-variables
MINIO_ROOT_USER="minioadmin"
MINIO_ROOT_PASSWORD="secret"
MINIO_VOLUMES="/space/minio02/data/"

MINIO_SERVER_URL="https://minio.ac.aixigo.de:9010"
MINIO_BROWSER_REDIRECT_URL="https://minio.ac.aixigo.de:9443"
MINIO_OPTS="-C /etc/minio --address :9010 --console-address :9443"
```

ps -ef shows the expected command line options. The previously installed version was from Nov 6th:

```
:
[UPGRADE] mcli:amd64 20231106041923.0.0 -> 20231120163059.0.0
[UPGRADE] minio:amd64 20231106222608.0.0 -> 20231120224007.0.0
```

## Regression
Yes
Moving back to version 20231120224007.0.0 seems to fix the problem.

## Your Environment

* Version used (`minio --version`): minio_20231223071911.0.0_amd64.deb
* Server setup and configuration: Debian 12, real hardware
* Operating System and version (`uname -a`):  Linux nasl005.ac.aixigo.de 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

**Comment by ravindk89** [comment]
what are the contents of `/etc/minio` ? 

Can you also check the public key config? e.g. `openssl x509 --in /etc/minio/public.crt --noout --text` (I think that's the command).

Has the cert refreshed recently? Had a user who rotated certs, and we found that on cert rotation the user permissions had changed and MinIO could not read the certs - and therefore did not start in HTTPS mode.

**Comment by ravindk89** [comment]
I think one other thing to try is our `certgen` tool and see if that works.

If the certs produced by certgen are fine (they will be self-signed), and letsencrypt are not, then that at least gives us something to look at as part of understanding why it breaks in that specific version.

**Comment by ravindk89** [comment]
https://github.com/minio/minio/releases/tag/RELEASE.2023-12-09T18-17-51Z

I should have double checked the release notes!

`-C` is deprecated in the `2023-12-09` release, as per those release notes.

Change your `MINIO_OPTS` to use `-S` instead of `-C`.

I'll add a warning in the docs as well to help guide users who might miss the migration guidance in the release notes (easy if you are hopping multiple versions).

As an *aside* for other users, other things to check are:
- That the permissions of your cert/private key have not changed due to a recent refresh
- That the public key configuration has not meaningfully changed or been corrupted
- That the key names remain `public.crt` and `private.key`
- That the path provided is read-accessible by the MinIO service user.

**Comment by harridu** [comment]
? https://github.com/minio/minio/releases/tag/RELEASE.2023-12-09T18-17-51Z doesn't mention "-C", as it seems.

**Comment by ravindk89** [comment]
Indeed @harridu , we need to fix that.

The short alias is seen if you do `minio server -h`. 

I checked back as far as a 2022 release and I actually don't see references to `--config-dir, -C` in the help output at all. I imagine your setup must have been running for quite a while, or perhaps you referenced our docs right before we removed those references.

I'll make a quick update to those release notes as well, and hopefully that closes the loop once you verify everything works as expected.

**Comment by harshavardhana** [comment]
You need to use --certs-dir instead of -C, -C command has been long deprecated.

**Comment by harridu** [comment]
Using "--certs-dir" seems to fix the problem. I didn't try "-S" (but I wonder what the "S" is supposed to mean). I didn't expect that "-C" was not the abbr. for "--certs-dir".

Maybe a command line options list as a reference in the documentation would be helpful. There was no indication in the system log that MINIO_SERVER_URL and MINIO_BROWSER_REDIRECT_URL started with "https", but no certificates had been configured and that minio is using http instead. There was no message about the unsupported / deprecated command line option, either. Anything indicating an error would have been very helpful.

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.-certs-dir

The `-S` is a short alias (which, to your point, you'd expect -C but here we are :) )

As far as logging better errors, I will leave that to the engineers to discuss (cc / @harshavardhana ). I think our preference is to not halt-on-startup, but maybe this is worth at least emitting a warning.

Either way, glad we resolved this quickly.

**Comment by harridu** [comment]
You mean it is "-S" for "short" ?

Case can be closed, thank you very much for your fast response. Best wishes for the next year.

**Comment by ravindk89** [comment]
@harridu I'm not sure there's that association - it's like there are some linux utilities where the parameter name and it's alias are completely disconnected, likely to avoid a collision with another parameter or alias. It's enough to consider it `--certs-dir | -S` as the two options for specifying.

**Comment by harshavardhana** [comment]
-S is for secure (certs-dir)
