### ISSUE TITLE
 all filled in with my domain that i use i am unable to download and  preview  from the web console i am using the latest version of the minio-server it hapes with docker and the Binary and   i am also behind nginx proxy  

### ISSUE THREAD

**Issue by cchalifo999** [minio/minio#18723]
MINIO_SERVER_HOST=  
MINIO_SERVER_HOST=  
MINIO_BROWSER_REDIRECT_URL=
 all filled in with my domain that i use i am unable to download and  preview  from the web console i am using the latest version of the minio-server it hapes with docker and the Binary and   i am also behind nginx proxy

**Comment by klauspost** [comment]
Seems like you accidentally deleted the template. Don't make this a guessing game by not providing any useful information - provide:

* Your setup.
* Server versions you are running. 
* Your FULL config (ok to redact secret keys only). 
* Your nginx setup - including full config.
* Your browser.
* The request performed in the browser (use F12)
* The errors you are seeing in the browser.

**Comment by cchalifo999** [comment]
I am going to reinstall the operating system and try from scratch again. I
think there's something wrong with os and I'll get back with you to see if
it solves the problem that I'm having.

**Comment by cchalifo999** [comment]
I was up all night trying to get it to work.

**Comment by cchalifo999** [comment]
> Seems like you accidentally deleted the template. Don't make this a guessing game by not providing any useful information - provide:
> 
>     * Your setup.
> 
>     * Server versions you are running.
> 
>     * Your FULL config (ok to redact secret keys only).
> 
>     * Your nginx setup - including full config.
> 
>     * Your browser.
> 
>     * The request performed in the browser (use F12)
> 
>     * The errors you are seeing in the browser.
I  found out what was the problem  is was because i was using cloud proxey on my domain name when i took off the proxy flag on cloudflare all is good
