### ISSUE TITLE
x509: certificate signed by unknown authority).

### ISSUE THREAD

**Issue by 13567436138** [minio/minio#18726]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

my minio is install by operator.when I want replication one cluster to another.I want to config .
 mc replicate --insecure add --remote-bucket https://admin:markhuang@192.168.229.50:443/c2-n2-bk1 --replicate "delete,delete-marker,existing-objects" --sync minio-cluster-1/c1-n1-bk1 --limit-upload 200Mi

192.168.229.50 is a loadbalancer ip ,but the ip is not in cert's san.so I Have to regenerate the cert to add ip san.

but 
root@karmada-02-a:~/minio/3#  mc replicate --insecure add --remote-bucket https://admin:markhuang@192.168.229.50:443/c2-n2-bk1 --replicate "delete,delete-marker,existing-objects" --sync minio-cluster-1/c1-n1-bk1 --limit-upload 200Mi
mc: <ERROR> unable to configure remote target. Remote service connection error (Remote service endpoint offline, target bucket: c2-n2-bk1 or remote service credentials: admin invalid 
        Get "https://[192.168.229.50]/c2-n2-bk1/?location=": x509: certificate signed by unknown authority).

## Steps to Reproduce (for bugs)

1.
```
root@karmada-02-a:~/minio/3# cat openssl.cnf 
[ req ]
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_ca ]
basicConstraints = critical, CA:TRUE
keyUsage = critical, digitalSignature, keyEncipherment, keyCertSign
[ v3_req_server ]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[ alt_names ]
DNS.1 = minio-pool-0-{0...3}.minio-hl.minio-cluster1.svc.cluster.local
DNS.2 = minio.minio-cluster1.svc.cluster.local
DNS.3 = minio.minio-cluster1 
DNS.4 = minio.minio-cluster1.svc
DNS.5 = *.minio-hl.minio-cluster1.svc.cluster.local
DNS.6 = *.minio-cluster1.svc.cluster.local
IP.1 = 192.168.229.50
IP.2 = 192.168.229.32
```
2.
```
openssl ecparam -name prime256v1 -genkey -noout -out ca.key
chmod 0600 ca.key
openssl req -x509 -new -sha256 -nodes -key ca.key -days 3650 -out ca.crt \
            -subj "/CN=my-CA"  -extensions v3_ca -config ./openssl.cnf
```
3.
```
openssl ecparam -name prime256v1 -genkey -noout -out private.key
chmod 0600 private.key
openssl req -new -sha256 -key private.key -subj "/CN=kubernetes-ca" \
  | openssl x509 -req -sha256 -CA ca.crt -CAkey ca.key -CAcreateserial \
                 -out public.crt -days 365 \
                 -extensions v3_req_server -extfile ./openssl.cnf
```
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
You need to trust both sites, bring their public certs and store it in the TLS secrets config map.

Please read documentation on this.
