### ISSUE TITLE
mc admin update does not use proxy variables

### ISSUE THREAD

**Issue by NotABugItsAFeature** [minio/minio#18730]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
mc uses the proxy variables to update the server version.

## Current Behavior
Connection timeout due to the tool not using the proxy configuration.
Note that for updating the mc tool itself it works properly. (mc update)

## Steps to Reproduce (for bugs)
Use mc admin update behind proxy.

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2024-01-01T16-36-33Z (commit-id=8f13c8c3bfee304e11a56076039f13e343937124)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.

* Operating System and version (`uname -a`):
Linux myserver 4.18.0-513.9.1.el8_9.x86_64 #1 SMP Thu Nov 16 10:29:04 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shtripat** [comment]
Are the same proxy variables set on all MinIO nodes while running `mc admin update`?

**Comment by NotABugItsAFeature** [comment]
Where do I need to configure this? I couldn't find anything in the documentation.
What is the proper way to set the variables?

When updating mc the below did work so I tried with this approach:
https_proxy=myproxy mc update

**Comment by harshavardhana** [comment]
This is not going to work or be supported. For airgapped environment setup a mirror of dl.min.io in your local artifactory and then perform.

```
mc admin update alias/ http://mylocalartifacts/minio.sha256sum
```

We expect the binaries to be laid out in the same manner as our dl.min.io link
