### ISSUE TITLE
Error when updating to RELEASE.2023-11-01T01-57-10Z and later

### ISSUE THREAD

**Issue by nicholaslimck** [minio/minio#18735]
After updating our MinIO deployment to RELEASE.2023-11-01T01-57-10Z, each node fails to start. 

## Expected Behavior
Cluster starts with preexisting configuration on the new version.

## Current Behavior
After upgrading to RELEASE.2023-11-01T01-57-10Z, each node in the cluster fails to boot up with a similar message:
> Waiting for atleast 1 remote servers with valid configuration to be online
Following servers are currently offline or unreachable [http://minio1:9000/export is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": lookup minio1 on 127.0.0.11:53: no such host http://minio2:9000/export is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": lookup minio2 on 127.0.0.11:53: no such host http://minio4:9000/export is unreachable: Post "http://minio4:9000/minio/bootstrap/v1/verify": lookup minio4 on 127.0.0.11:53: no such host]

After trying and failing to find other nodes, the container eventually restarts and continues in an endless loop.

## Steps to Reproduce (for bugs)

1. Deploy MinIO RELEASE.2023-10-25T06-33-25Z or older
2. Upgrade to MinIO RELEASE.2023-11-01T01-57-10Z or newer

## Context
Running a MinIO cluster in Docker Swarm, deployed via docker compose. The cluster has been running for the past few years and upgraded every few months without issues until now.

## Regression
Yes. Upgrades were seamless until this release.

## Your Environment
* Version used (`minio --version`): RELEASE.2023-10-25T06-33-25Z
* Server setup and configuration: Containerised deployment on Docker Swarm, 4 nodes with 1 drive each.
* Operating System and version (`uname -a`): Ubuntu 22.04.3 LTS x86_64

**Comment by harshavardhana** [comment]
> Waiting for atleast 1 remote servers with valid configuration to be online
> Following servers are currently offline or unreachable [http://minio1:9000/export is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": lookup minio1 on 127.0.0.11:53: no such host http://minio2:9000/export is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": lookup minio2 on 127.0.0.11:53: no such host http://minio4:9000/export is unreachable: Post "http://minio4:9000/minio/bootstrap/v1/verify": lookup minio4 on 127.0.0.11:53: no such host]

Your DNS is not reachable here; verify if your DNS is up and running.

**Comment by nicholaslimck** [comment]
> > Waiting for atleast 1 remote servers with valid configuration to be online
> > Following servers are currently offline or unreachable [http://minio1:9000/export is unreachable: Post "http://minio1:9000/minio/bootstrap/v1/verify": lookup minio1 on 127.0.0.11:53: no such host http://minio2:9000/export is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": lookup minio2 on 127.0.0.11:53: no such host http://minio4:9000/export is unreachable: Post "http://minio4:9000/minio/bootstrap/v1/verify": lookup minio4 on 127.0.0.11:53: no such host]
> 
> Your DNS is not reachable here; verify if your DNS is up and running.

@harshavardhana It is up and running. This deployment has worked for over two years and runs as a docker stack deployed using a docker-compose.yml configuration. Furthermore, it runs without issues after reverting the container tag to the prior version. If there was a problem with the DNS configuration, I doubt reverting the container would work.

**Comment by harshavardhana** [comment]
> @harshavardhana It is up and running. This deployment has worked for over two years and runs as a docker stack deployed using a docker-compose.yml configuration. Furthermore, it runs without issues after reverting the container tag to the prior version. If there was a problem with the DNS configuration, I doubt reverting the container would work.

That really doesn't matter. 

> lookup minio4 on 127.0.0.11:53: no such host]

This is a DNS problem not a MinIO problem.

**Comment by harshavardhana** [comment]
These are well-known problems with docker swarm, it's behavior is spotty and buggy when it comes to DNS.

You should simply use `--net=host` and get around this problem.
