### ISSUE TITLE
Cert Expired on min.io

### ISSUE THREAD

**Issue by johnandersen777** [minio/minio#18741]
Expired 30 minutes ago

**Comment by kaankabalak** [comment]
We are aware of this issue and are looking to resolve it as soon as possible. We will keep you updated.

**Comment by jixuuse** [comment]
![图片](https://github.com/minio/minio/assets/26220419/c212e2ee-1ebc-495f-817f-117ed7ec77e7)

**Comment by harshavardhana** [comment]
This is fixed.
