### ISSUE TITLE
Some data in Minio has not been replicated to the target layer

### ISSUE THREAD

**Issue by wuyanfeiwork** [minio/minio#18748]
I have configured tiering rules for the 'mdoc' bucket, specifying that objects older than 1 day should be moved to 'MDOC-ARCHIVE.' Upon inspection, I found that some data has not been tiered to 'MDOC-ARCHIVE,' even though it has been more than 24 hours since the objects were uploaded.

The data that has been successfully tiered was uploaded before I initially configured the tiering rules, while the data that hasn't been tiered was uploaded after the tiering rules were in place. What could be the possible reasons for this behavior?

![image](https://github.com/minio/minio/assets/104751498/bca5c600-11b2-4bf2-80d8-1cf1f0711edf)

The two environment versions are consistent.

Docker Minio Version: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z

**Comment by harshavardhana** [comment]
24hrs is not sufficient time, it requires from the time the object is scheduled for tiering with the 00:00hrs window. 

So effectively 1day tiering means it will be tiered in 2days.

Also always upgrade to latest before reporting issues.

**Comment by wuyanfeiwork** [comment]
> 24hrs is not sufficient time, it requires from the time the object is scheduled for tiering with the 00:00hrs window.
> 
> So effectively 1day tiering means it will be tiered in 2days.
> 
> Also always upgrade to latest before reporting issues.

What is the default scheduled time for tiered storage operations, and is it configurable? @harshavardhana

**Comment by harshavardhana** [comment]
> What is the default scheduled time for tiered storage operations, and is it configurable? @harshavardhana

This is driven via AWS S3 API transition behavior.
