### ISSUE TITLE
Validate: XL/FS should be validated again on windows. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1874]

**Comment by krisis** [comment]
I will be testing on Windows, using mc and miniodebug on xl/fs until Jun 10th. If nothing serious comes up, I shall close this issue.

**Comment by krisis** [comment]
Need to test again with fix for #1887

**Comment by krisis** [comment]
Did the following tests using a suite of s3 tools like `mc`, `aws s3`, `aws s3api`, `miniodebug`,
- Copying small and large objects
- Mirroring golang source
- Recursive listing golang source
- Deleting bucket with large no. of objects
- Multipart upload - both abort and complete end states
- Mulitpart upload using `miniodebug` and `aws s3api` interchangeably within a single multipart-upload operation

N B - No specific tests were done for UNC path related fix.

**Comment by harshavardhana** [comment]
> N B - No specific tests were done for UNC path related fix.

what else is pending on this bug? @krisis were you able to validate anything specific related to UNC path?

**Comment by krisis** [comment]
UNC related unit tests were added as part of PR https://github.com/minio/minio/pull/1958. This covers the set of things that needed to be validated on windows. @harshavardhana could you close this issue if you think so too?

**Comment by harshavardhana** [comment]
Yes, closing.
