### ISSUE TITLE
Unable to modify Transition Days in the console

### ISSUE THREAD

**Issue by wuyanfeiwork** [minio/minio#18753]
As shown in the screenshot, when modifying the lifecycle rule settings in the Minio console and saving the changes after modifying the Transition Days, the page becomes blank. 

In the browser developer tools console, you can see some error messages.

![image](https://github.com/minio/minio/assets/104751498/6480a9a6-ad3f-4682-ab8b-77983923a2de)

![image](https://github.com/minio/minio/assets/104751498/4986b2cf-a867-404c-af89-fe3a6cf4af60)

Docker image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z

**Comment by harshavardhana** [comment]
Upgrade to latest release first, before reporting an issue.

**Comment by rad4day** [comment]
I can confirm this is also broken (in the same way) in minio/minio:latest

**Comment by harshavardhana** [comment]
Then please report it here https://github.com/minio/console/issues
