### ISSUE TITLE
Versioning not completely disabled

### ISSUE THREAD

**Issue by PKizzle** [minio/minio#18750]
## Expected Behavior
Disabling the versioning feature should completely turn of any tracking of file activities. Additionally, in the console for buckets with disabled versioning the two elements "Show deleted objects" and "Rewind" should not be visible.

## Current Behavior
Even though versioning is disabled for a bucket a list of the deleted files is still stored.

## Steps to Reproduce (for bugs)

1. Create a bucket with disabled versioning
2. Upload data to the bucket
3. Delete some data
4. Use the console and enable  "Show deleted objects" to still get the list of deleted objects

## Context
Storing the very long list of deleted objects (as I am mainly using the buckets for backups) seems to me like a waste of storage space as I do not need this information. Also, it seems to affect the console's loading time even if the "Show deleted objects" checkbox is unchecked.

## Your Environment
* Version used (`minio --version`): RELEASE.2024-01-05T22-17-24Z
* Server setup and configuration: MinIO community helm chart 5.0.14 on a 1.29.0 k3s cluster (3x RaspberryPi 4B)
* Operating System and version (`uname -a`): 6.1.21-v8+ aarch64 GNU/Linux

**Comment by harshavardhana** [comment]
Once versioning is enabled you can never disable it @PKizzle that is how AWS S3 wants us to behave.  You can only suspend versioning.

**Comment by PKizzle** [comment]
And when versioning is suspended the tracking of deleted files is intended behavior?

**Comment by harshavardhana** [comment]
Yes `suspended != disabled`

**Comment by PKizzle** [comment]
Just for reference should someone else find this issue and use the community version of the helm chart: When setting versioning to `false` it causes MinIO to always suspend versioning of the bucket which is not the same as disabling it. In order to fix this behavior set versioning to something else than `false` like `unversioned`.
