### ISSUE TITLE
Invalid ellipsis format using systemd scripts

### ISSUE THREAD

**Issue by mhanafi1970** [minio/minio#18763]
## Expected Behavior

Minio server should start using systemd.

## Current Behavior
Keep getting this error. 
<code>
Jan  8 18:49:34 minio-1 minio[42597]: ERROR Unable to prepare the list of endpoints: Invalid ellipsis format in (http://minioib{01..10}:9000/mnt/disk1), Ellipsis range must be provided in format {N...M} where N and M are positive integers, M must be greater than N,  with an allowed minimum range of 4
</code>

Running at command line works.
/usr/local/bin/minio server --console-address :9001 http://minioib{01..10}:9000/mnt/disk1

## Steps to Reproduce (for bugs)
Here is my /etc/default/minio
<pre>
MINIO_VOLUMES="http://minioib{01..10}:9000/mnt/disk1"
MINIO_OPTS="--console-address :9001"
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD='xxxxx'
MINIO_SERVER_URL="http://proxy:9000"
</pre>

And /usr/lib/systemd/system/minio.service

<pre>
Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
Type=notify

WorkingDirectory=/usr/local

User=minio-user
Group=minio-user
ProtectProc=invisible

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service always
Restart=always

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=1048576

# Specifies the maximum number of threads this process can create
TasksMax=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})
</pre>
## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2024-01-01T16-36-33Z (commit-id=8f13c8c3bfee304e11a56076039f13e343937124)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.

* Server setup and configuration:
single SSD drive mounted on /mnt/disk1

* Operating System and version (`uname -a`):
Linux minio-1 4.18.0-477.10.1.el8_8.x86_64 #1 SMP Wed Apr 5 13:35:01 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BNikola** [comment]
Hi @mhanafi1970,
I am getting the same error with similar configuration.
Were you able to solve your issue?

**Comment by klauspost** [comment]
Add a dot more = `...`

**Comment by BNikola** [comment]
Thanks @klauspost I've just figured it out.
