### ISSUE TITLE
Object key case sensitive difference with aws S3

### ISSUE THREAD

**Issue by ggibellato** [minio/minio#18787]
I believe that I found an issue on the object key using minio latest image version as 15-JAN-2024.

The test I have put a file on a bucket and try read back.

The bucket is: "Bucket1"
Object key is: "Folder1/SubFolder/File.zip" 

I am using PutObjectAsync to store the object

No retrieve the object I am make the key lower case and then using GetObjectAsync

When I run the test using my laptop that runs windows 11, it does work.

When I push to GITHUB the test fail telling the object key does not exist.

If I don't lower the key it does work.

The problem is for me on the fact that at S3 it does work with lower key, and as I'm using minio to test my code that will run on aws S3, that for me is an issue.

Maybe this is not an issue for minio but is there a way to make compatible, maybe a configuration option?

Also it is strange that it does work at windows but it doesn't at GITHUB where it is running under Linux.

**Comment by harshavardhana** [comment]
OS brings case sensitivity. We cannot hide the filesystem facts of Windows and mask it.

If you use Windows you need to live with case insensitive nature. 

For production systems to store serious content use Linux.
