### ISSUE TITLE
Prefix access is denied: .minio.sys/config/iam/sts/C1ICY4067BY36S8HDQJK/identity.json

### ISSUE THREAD

**Issue by molinarif02** [minio/minio#18788]
## Issue
After modifying some configuration (added certs dor TLS configuration) and the deployment method (switched from podman to podman-compose) I cannot log into my MinIO instance anymore with the admin user.
I've tried to change the admin password but nothing changed.

## minio.env
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=adminpassword
MINIO_CERT_PASSWD=certpassword

## podman-compose.yaml
version: '3'
services:
  minio:
    container_name: minio
    image: harbor.popso.it/minio/minio
    command: server /data --certs-dir /certs --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5
    volumes:
      - /home/minio/minio.env:/etc/config.env
      - /mnt/minio/data:/data
      - /home/minio/certs:/certs
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env

## Error log
API: SYSTEM()
Time: 09:59:14 UTC 01/15/2024
DeploymentID: ba62640e-20d4-4bf8-8562-25dd6bd3a235
Error: Prefix access is denied: .minio.sys/buckets/.usage-cache.bin (cmd.PrefixAccessDenied)
       3: internal/logger/logger.go:258:logger.LogIf()
       2: cmd/data-scanner.go:207:cmd.runDataScanner()
       1: cmd/data-scanner.go:79:cmd.initDataScanner.func1()

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2023-08-29T23-07-35Z (commit-id=07b1281046c8934c47184d1b56c78995ef960f7d)
* Operating System and version (`uname -a`): Linux 099f649854f0 5.14.0-362.13.1.el9_3.x86_64

**Comment by harshavardhana** [comment]
It looks like you have removed a bunch of folders here.

Kicking around on the backend disks is not allowed if you do strange things with backend disks or someone else does it can lead to unexpected situations where we cannot read the content anymore.

- either you changed the permissions of the user at the disk level 
- or you have some partial state moving from podman to compose - pick one and stick with like approach is recommended.

**Comment by thomashooo** [comment]
【solved】：
sudo chown -R minio:minio /mnt/data/.minio.sys
sudo chmod -R 750 /mnt/data/.minio.sys
