### ISSUE TITLE
Which version should I use for windows server 2008 r2?

### ISSUE THREAD

**Issue by houkunlin** [minio/minio#18782]
## NOTE
in win 11:

```
minio.exe version RELEASE.2024-01-05T22-17-24Z (commit-id=04135fa6cdd68e281094f54eb6edb901059789d0)
Runtime: go1.21.5 windows/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

## Current Behavior

![image](https://github.com/minio/minio/assets/12333292/7fa35642-5dd3-4e76-94eb-90c1de5479b9)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): **RELEASE.2024-01-05T22-17-24Z (commit-id=04135fa6cdd68e281094f54eb6edb901059789d0)**
* Server setup and configuration:
* Operating System and version (`uname -a`): **Windows Server 2008 R2**

**Comment by ravindk89** [comment]
https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2

Windows Server 2008 and 2008R2 are End of Life as of 01/14/2020. We do not guarantee support of the product in EOL operating systems.

**Comment by houkunlin** [comment]
经过我的测试，在 `Windows Server 2008 R2` 系统上 `minio.RELEASE.2023-12-02T10-51-33Z` 可能是最后一个支持的版本。

After my testing, on `Windows Server 2008 R2` system `minio.RELEASE.2023-12-02T10-51-33Z` may be the last supported version.

**Comment by yupeishan** [comment]
> 经过我的测试，在 `Windows Server 2008 R2` 系统上 `minio.RELEASE.2023-12-02T10-51-33Z` 可能是最后一个支持的版本。
> 
> After my testing, on `Windows Server 2008 R2` system `minio.RELEASE.2023-12-02T10-51-33Z` may be the last supported version.


minio.RELEASE.2023-12-02T10-51-33Z  startup error   "kernel32.dll not found"
minio.RELEASE.2023-08-31T15-31-16Z can runs on windows 2008 R2

**Comment by klauspost** [comment]
https://github.com/golang/go/issues/57003
