### ISSUE TITLE
Prometheus minio_s3_requests_ttfb_seconds_distribution metric missing +Inf label value (histogram_quantile function can not be applied)

### ISSUE THREAD

**Issue by cowjen01** [minio/minio#18790]
## Description

As already discussed here: https://github.com/minio/minio/issues/12540, Prometheus metric called `minio_s3_requests_ttfb_seconds_distribution` does not include the required `+Inf` label for the native `histogram_quantile` function computation. The function is returning `NaN` for this reason. From docs:

> The highest bucket must have an upper bound of +Inf. (Otherwise, NaN is returned.) 

## Expected Behavior

The `minio_s3_requests_ttfb_seconds_distribution` metric should also export the `+Inf` label with the counter above the maximal defined distribution step.

## Current Behavior

There are counters for the distribution buckets and not for the values above the maximum limit.

## Possible Solution

Include the `+Inf` label into the latency distribution metrics so the `histogram_quantile()` function can be used for percentile calculation.

## Steps to Reproduce (for bugs)

1. Enable Prometheus metrics exposure
2. Gather Prometheus metrics
3. Inspect `minio_s3_requests_ttfb_seconds_distribution` unique label values

## Your Environment
* Version used (`minio --version`): quay.io/minio/minio:RELEASE.2023-11-15T20-43-25Z
* Server setup and configuration: MinIO operator and tenant deployed using Helm Chart (version `5.0.x`)

**Comment by minio-trusted** [comment]
The fix is merged and released #18807
