### ISSUE TITLE
Issue with Audit Log JSON Format in MinIO Using Single Quotes

### ISSUE THREAD

**Issue by pavelkogen** [minio/minio#18792]
## Expected Behavior

The audit logs in MinIO should be in valid JSON format, which includes using double quotes for strings and object keys.

## Current Behavior

Currently, the MinIO audit logs are using single quotes for strings and object keys, resulting in an invalid JSON format. This improper format causes difficulties in parsing and analyzing the logs.

## Possible Solution

The audit log generation code should be updated to ensure that all JSON objects are formatted with double quotes instead of single quotes, adhering to standard JSON practices.

## Steps to Reproduce (for bugs)

1. Enable audit logging in MinIO.
2. Perform operations that generate audit logs.
3. Examine the generated audit logs.
4. Notice the use of single quotes in the JSON structure.

## Context

This formatting issue with audit logs affects automated log processing and analysis, as the logs are not in a standard, parseable JSON format.

## Regression

No

## Your Environment

* Version used (`minio --version`): 
 
```RELEASE.2024-01-05T22-17-24Z (commit-id=04135fa6cdd68e281094f54eb6edb901059789d0)```

* Server setup and configuration: 

```
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=pass
MINIO_VOLUMES="/opt/s3/"
MINIO_OPTS="-C /etc/minio --address localhost:8080 --console-address localhost:8081"
```
* Operating System and version (`uname -a`): 

```Linux  5.19.0-32-generic 33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux```

Here is an example of the log output, where sensitive data such as IP addresses and keys have been removed:

```
- - [15/Jan/2024 13:17:39] "POST / HTTP/1.1" 200 -
{'version': '1', 'deploymentid': 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'time': '2024-01-15T13:17:39.495122796Z', 'event': '', 'trigger': 'incoming', ... [truncated for brevity] ..., 'parentUser': 'admin'}
webhook
```

The use of single quotes (' ') instead of double quotes (" ") around string values and object keys is the primary concern. This deviation from standard JSON practices results in log entries that are not correctly formatted as valid JSON, thereby hindering automated log processing and integration with various log management tools.

I kindly request that you consider addressing this formatting issue to ensure the logs are produced in standard, valid JSON format. Such a change would greatly aid in the effective and efficient analysis of audit logs.

Thank you for your attention to this matter and for your continued work on MinIO. I am looking forward to a resolution of this formatting issue.

**Comment by harshavardhana** [comment]
We do not ever add single quotes to audit JSON format.

What you are seeing here is what is incorrectly being printed out via your webhook service.

We send the audit as is via struct -> JSON directly. This is the most commonly used feature for 1000s of customers.

I would request you to use better webhook tools that do not interpret the incoming data.
