### ISSUE TITLE
First login lands at blank screen

### ISSUE THREAD

**Issue by jamincollins** [minio/minio#18797]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

After a successful login, the UI ends at a blank screen.

## Expected Behavior

After a successful login, the user should be taken to the normal UI/dashboard.

## Current Behavior

After a successful login, the UI ends at a blank screen.

## Steps to Reproduce (for bugs)

1. Unknown

## Context

Requires that I login twice each time I want to access the UI.  First time results in the blank page.  Going back and logging in a second time results in a usable UI.

## Regression

Unknown

## Your Environment

* Version used (`minio --version`): 
```
$ minio --version
minio version 2023-12-13T23-28-55Z (commit-id=f39e2cba3b29e4fc3b947c54ef7a9eed929660db)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
* Server setup and configuration:
  * Minio running via systemd
  * Nginx reverse proxy in front of it
  * LDAP used for identity

* Operating System and version (`uname -a`): 
```
Linux archive 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
Please use latest release and report again.
