### ISSUE TITLE
MinIO sends an empty JSON to HTTP Webhook at startup

### ISSUE THREAD

**Issue by tariver** [minio/minio#18798]
Greetings!
I have a MinIO installation on distributed mode and setting it up so it would [publish server and audit logs to HTTP Webhook](https://min.io/docs/minio/linux/operations/monitoring/minio-logging.html) which is in my case fluentd using [http plugin](https://docs.fluentd.org/input/http).

What I noticed is that at startup MinIO sends empty JSON both to server and audit logs endpoint. This is not critical but kind of messes up the log flow, since the parser gives it local time of the server instead of the time that is send in the other sent JSONs.

## Expected Behavior
This JSON should not be sent or be not empty.

## Current Behavior
An empty JSON is sent.

## Steps to Reproduce (for bugs)
1. Set up MinIO in distribution mode with the following environment variables:
```
      MINIO_LOGGER_WEBHOOK_ENABLE_OPENSEARCH1="on"
      MINIO_LOGGER_WEBHOOK_ENDPOINT_OPENSEARCH1="http://10.0.0.2:9880/minio.server.log"
      MINIO_LOGGER_WEBHOOK_QUEUE_DIR="/home/minio/events"
      MINIO_AUDIT_WEBHOOK_ENABLE_OPENSEARCH11="on"
      MINIO_AUDIT_WEBHOOK_ENDPOINT_OPENSEARCH11="http://10.0.0.2:9880/minio.audit.log"
      MINIO_AUDIT_WEBHOOK_QUEUE_DIR="/home/minio/audit"
```
2. Create a file `http.conf` with the following fluentd config:
```xml
<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
  <parse>
    @type json
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    keep_time_key true
  </parse>
</source>

<match minio.server.log>
  @type stdout
  format json
</match>

<match minio.audit.log>
  @type stdout
  format json
</match>
```
3. Start the fluentd with `td-agent -c http.conf`. When one of the MinIO nodes is stopped and started again with `systemctl` the stdout will have two empty JSON.
```
{}
{}
```
Other logs work just fine.

MinIO version is `RELEASE.2023-11-11T08-14-41Z`

**Comment by harshavardhana** [comment]
Yes that is on purpose to perform a check if your webhook is active or not.

Just ignore the empty JSON.
