### ISSUE TITLE
Scanner deletes empty buckets

### ISSUE THREAD

**Issue by zeeZ** [minio/minio#18809]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

It appears that the scanner will sometimes delete empty buckets. This happens reliably on simple buckets that previously contained files and are now empty, but can also be manually triggered by running heal with the `-remove` flag (if that is not its intended behavior).

I believe this is because the bucket's data folder is being deleted. The configuration folder in `.minio.sys/buckets` remains intact and recreating the data folder restores configuration.

While trying to reproduce at first I was able to even have new empty buckets deleted by the scanner reliably, then only ones that contained a file previously, then only buckets that contain a file, have the scanner run, delete the file, next scanner run deletes the bucket.

## Expected Behavior

Empty buckets should not be deleted and remain intact.

## Current Behavior

The bucket is deleted.

## Steps to Reproduce (for bugs)

Scanner:
1. `mc mb cluster/testbucket`
2. `touch testfile && mc cp testfile cluster/testbucket/`
3. wait until scanner completes run cycle (`mc admin scanner trace cluster | grep testbucket`)
4. `mc rm cluster/testbucket/testfile`
5. wait until scanner completes run cycle (`mc admin scanner trace cluster | grep testbucket`)
6. `mc ls cluster/testbucket # Bucket does not exist`

Manually:
1. `mc mb play/testbucketpleaseignore`
2. `mc admin heal play/testbucketpleaseignore -remove`
3. `mc ls play/testbucketpleaseignore # Bucket does not exist`

## Regression

Yes, since RELEASE.2024-01-11T07-46-16Z

## Your Environment

* Version used (`minio --version`): 2024-01-16T16:07:38Z
* Server setup and configuration: 4 nodes with 1 disk each

**Comment by harshavardhana** [comment]
The random sporadic failure in our mint tests is related to this @klauspost
