### ISSUE TITLE
Found the below errors in minio, container is up and running,but the site isn't reachable, can someone help me on this?

### ISSUE THREAD

**Issue by psrikar-uptycs** [minio/minio#18805]
Found the below errors in minio, container is up and running,but the site isn't reachable, tried the curl command , got this error,
```
curl http://long-obj2:9000/data1
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><BucketName>data1</BucketName><Resource>/data1</Resource><RequestId>17AB0B2D533B623B</RequestId><HostId></HostId></Error>
```
**Minio errors:**

API: SYSTEM()
Time: 05:16:38 UTC 01/17/2024
Error: Read failed. Insufficient number of drives online (*errors.errorString)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/prepare-storage.go:251:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:311:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:96:cmd.newErasureServerPools()
       2: cmd/server-main.go:743:cmd.newObjectLayer()
       1: cmd/server-main.go:578:cmd.serverMain()
Waiting for a minimum of 1 drives to come online (elapsed 13s)

Unable to read 'format.json' from http://long-obj2:9000/data1: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

Unable to read 'format.json' from http://long-obj2:9000/data2: Do not upgrade one server at a time - please follow the recommended guidelines mentioned here https://github.com/minio/minio#upgrading-minio for your environment

**Comment by harshavardhana** [comment]
@psrikar-uptycs This is because you have a local disk that is not getting registered to be local to that node. 

It looks like you are using docker containers wrongly, please use k8s for a proper distributed setup.
