### ISSUE TITLE
Be able to manage Prometheus tokens "as code" when using JWT

### ISSUE THREAD

**Issue by sebastienbonami** [minio/minio#18802]
**Is your feature request related to a problem? Please describe.**
I'm looking for a proper way "as code" to generate a bearer token for [Monitoring and Alerting using Prometheus](https://min.io/docs/minio/linux/operations/monitoring/collect-minio-metrics-using-prometheus.html) (considering `MINIO_PROMETHEUS_AUTH_TYPE` is not set to "public").

It seems like the only way to generate a token is to run command `mc admin prometheus generate ALIAS` which is acceptable for a test environment, but not for production environments where the process should be automated.

**Describe the solution you'd like**
Ideally, a Terraform provider that can manage these tokens.
Otherwise, a API call or command that is able to list, delete and create tokens (without going through generating a whole Prometheus scrape configuration).

**Describe alternatives you've considered**
Run the `mc admin prometheus generate ALIAS` with a **local-exec** provisioner in Terraform and substract the token generated (and only do it once), which is very cumbersome.

Thank you.

**Comment by harshavardhana** [comment]
mc can be fully automated, even run from terraform.

**Comment by sebastienbonami** [comment]
@harshavardhana I actually thought about it, do you have an example perhaps? I'm looking for a way, using Terraform, to create a token and be able to delete it in the future if it's not needed anymore.

The thing is, there's no mc command to simply create/delete a token. I created a separated issue in the mc project for that: https://github.com/minio/mc/issues/4826

**Comment by harshavardhana** [comment]
There is nothing to delete the token is purely client side.

Just run

```
mc admin prometheus generate alias/
```


This is already automated.
