### ISSUE TITLE
Use Tiering to maintain metadata on tier 1 and data on others tiers.

### ISSUE THREAD

**Issue by tdsn0007** [minio/minio#18821]
**Is your feature request related to a problem? Please describe.**

It's difficult to use hard disks with many small files when needed to update metadata files (like putobjectretention, or something like this). This type of calls have a lot of time of use in disks and maintain disks slow not because of data ingestion, but because of metadata read and updates. Today the majority of the calls are for metadata updates who turn disks busy everytime with reading.

**Describe the solution you'd like**

I want, if is possible, to use tier 1 (nvme) as "caching" only for metadata files (to be more precise, store metadata in this tier 1 and use tier 1 as "caching" because of high speed of the disks) and data files stored on tier 2 or 3 (normal disks). This combinated can provide a LOT of performance in minio deployment with hard disks and necessity of use of metadata updates.

**Describe alternatives you've considered**

I considerated miniocache, but this is only for get/head operations for now (not useful for putobjectretention or something like this, who only read and updates metadata for every file every day).

**Additional context**

We use for Veeam deployments and use for many others deployments (Veeam is the most dificult thing in this context). We tried with 4 servers deployment and with 16 servers deployment (16 servers is better, but not really 4x more performant).

**Comment by ravindk89** [comment]
This is how [Transition ("Tiering")](https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#object-transition-tiering) already works - the metadata remains on the Hot NVME tier, and the data gets migrated to your cold HDD tier. As long as your network is reasonably fast this would meet the overall structure you are discussing.

 > This combinated can provide a LOT of performance in minio deployment with hard disks and necessity of use of metadata updates.

This is only true if the majority of your operations do not require reading the actual data. Once you have to have to touch the HDD, you *will* lose performance. 

If what you are asking for is for a MinIO node to have both NVMe and HDD drives managed per-server, I am reasonably confident we are not going to take up that work.

We've spent countless engineering hours over the years trying to optimize for "HDD + Fast", and the simple physics of HDD functionality is always going to be the bottleneck. It's why we're moving our recommendations to focus on flash storage (NVMe or SSD), as we are seeing consistent long-term performance constraints from HDD deployments that cannot reasonably be worked around without adding increasingly complex functionalities - which is antithetical to how we want to design our product.

**Comment by tdsn0007** [comment]
Hi @ravindk89 , thanks for the update. 

I want to know better about this. Is possible to only go to tier 1 metadata and not data actually? Because for Veeam is a problem to have tiering for data (no problem for metadata stay in another tier).

Second thing: About using disks is for us a not a problem anymore (we use a linux cache for the hard disks and write to disks is very, very fast now). 

The only problem is because millions of millions of API calls to update metadata (putobjectretention) and the disks stay busy reading metadata all the moment and cannot have work time to write data.

But our performance for ingestion of data is very fast now with hard disks (without metadata updates). 

Another thing, actually, when we have metadata on tier 1 and the data goes to cold tier, matadata allways stays on tier 1? If only metadata are going to be in the tiering on tier 1 will be the best of the best world. And I think the majority of the problems will be vanished with Hard Disks and Veeam.

**Comment by tdsn0007** [comment]
And thanks for all the hard work with hard disks and minio! I'm looking close about this.

**Comment by ravindk89** [comment]
> The only problem is because millions of millions of API calls to update metadata (putobjectretention) and the disks stay busy reading metadata all the moment and cannot have work time to write data.

There isn't too much we can do here - I/O is a zero-sum game. Resources that are required for the scanner and/or tiering functionalities are resources that are not available to write data.

If that's a consistent issue, it's possible that the hardware overall is undersized for your workload and target performance.

> Another thing, actually, when we have metadata on tier 1 and the data goes to cold tier, matadata allways stays on tier 1? If only metadata are going to be in the tiering on tier 1 will be the best of the best world. And I think the majority of the problems will be vanished with Hard Disks and Veeam.

Metadata remains on the Hot tier (Tier 1), data is transitioned to the warm/cold tier (Tier 2). GET ops require hitting Tier 1, then Tier 2, and returning to Tier 1 - so your GET will naturally take longer.

Tiering is not immediate, so there is also that - I do not believe we can support immediate tiering as it diverges from the S3 spec. 

As far as overall questions on performance.

We don't provide performance guidance for the Community licensed product - it requires a significant amount of dedicated engineering to address the unique deployment architecture and requirements for each scenario. I would recommend you reach out to hello@min.io for professional engagement if you are seeing consistent performance issues on the Veaam side.
