### ISSUE TITLE
Support servers running behind loadbalancer (different internal vs. external IPs)

### ISSUE THREAD

**Issue by fpytloun** [minio/minio#18825]
**Is your feature request related to a problem? Please describe.**
I would like to deploy MiniO cluster where servers are in multiple racks on different internal networks and their ports exposed via loadbalancer. In such case, provided hostnames are not resolving to local IP (eg. IP of k8s pod).
Also when someone attempts this setup, instead of meaningful error, starting minio server just keeps failing.

```
API: SYSTEM()
Time: 15:39:05 UTC 01/18/2024
Error: Read failed. Insufficient number of drives online (*errors.errorString)
       8: internal/logger/logger.go:258:logger.LogIf()
       7: cmd/prepare-storage.go:254:cmd.connectLoadInitFormats()
       6: cmd/prepare-storage.go:312:cmd.waitForFormatErasure()
       5: cmd/erasure-server-pool.go:104:cmd.newErasureServerPools()
       4: cmd/server-main.go:976:cmd.newObjectLayer()
       3: cmd/server-main.go:718:cmd.serverMain.func9()
       2: cmd/server-main.go:434:cmd.bootstrapTrace()
       1: cmd/server-main.go:716:cmd.serverMain()
Waiting for a minimum of 4 drives to come online (elapsed 26s)
```

It is similar to this question: https://github.com/minio/minio/discussions/17374
But not possible to solve with host network.

**Describe the solution you'd like**
Multiple solutions might apply but simplest would be to just have parameter like `MINIO_SERVERNAME` to define current server endpoint so it can find itself within server pool list.

**Describe alternatives you've considered**
Messing with /etc/hosts which will break SSL verification.

I did not try to set with only current server in /etc/hosts pointing to localhost, eg.:
```
127.0.0.1    minio-0.rack-1.domain.tld
```

**Comment by manju-rn** [comment]
@fpytloun   What is your cluster - in K8s? If yes, then you could just define a ingress and point to respective service names

**Comment by fpytloun** [comment]
> @fpytloun What is your cluster - in K8s? If yes, then you could just define a ingress and point to respective service names

My setup are two regions running separate k8s clusters. So minios within one region can use k8s svc but they need to use these LB endpoints to connect to minios in other region.

**Comment by allanrogerr** [comment]
Please provide the following. Otherwise I will use minio latest to review this.
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by allanrogerr** [comment]
> Messing with /etc/hosts which will break SSL verification.

Please explain further. In my simplified setup, I skipped the portforward. I was able to run distributed minio after modifying the `/etc/hosts` file in the following way:
1.- Determine ip of k8s pod using `ip -br -4 a`
2.- Modify /etc/hosts
```
<ip of k8s pod>     <hostname>.<domain>
```
e.g.
```
10.42.0.11     minio-18825-1.lab.min.dev
```
3.- Start minio on all pods (running on separate networks)
```
CI=on \
minio server https://minio-18825-{0...1}.lab.min.dev:9000/tmp/data{1...2} --address :9000 --console-address :9090 --certs-dir ~/.minio/certs
```

**Comment by allanrogerr** [comment]
> parameter like MINIO_SERVERNAME to define current server endpoint

I would prefer to avoid this since it would break the current style of starting up minio with the same parameters on all servers; and it would be a rather intrusive change for this case - which already has a functioning workaround.

**Comment by fpytloun** [comment]
@allanrogerr Thank you for testing option with `/etc/hosts`. I don't have environment to test this workaround but I think it might work as problem seemed to be that minio node was not able to recognize itself within the pool of servers as no endpoint resolved to it's IP address.

**Comment by allanrogerr** [comment]
I discussed in the team. I will propose a minimal solution.
