### ISSUE TITLE
Performance issues when writing large amounts of small files

### ISSUE THREAD

**Issue by CCTV-six** [minio/minio#18820]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
When attempting to upload a large number of small files, the console outputs the above error message
Error: Failed to upload object: ObjectTooLarge: The specified request includes too many small objects. The maximum number of objects in a request is 1000.

## Current Behavior
Diagnose the root cause of the problem as exceeding the MinIO object limit and take appropriate measures to solve the problem based on the root cause of the problem

**Comment by harshavardhana** [comment]
> When attempting to upload a large number of small files, the console outputs the above error message
> Error: Failed to upload object: ObjectTooLarge: The specified request includes too many small objects. The maximum number of objects in a request is 1000.

Our code base has no such error message; this does not look like MinIO, which returns this error. 

Please elaborate more about the setup and explain it.
