### ISSUE TITLE
Support fqdns without sequential numbering in server pool

### ISSUE THREAD

**Issue by fpytloun** [minio/minio#18824]
**Is your feature request related to a problem? Please describe.**
I have multi-rack setup using domain with non-sequential numbering, eg. rack-2 and rack-4. It is not possible to add these all nodes into single server pool:

- minio-0.rack-2.domain.tld
- minio-1.rack-2.domain.tld
- minio-2.rack-2.domain.tld
- minio-0.rack-4.domain.tld
- minio-1.rack-4.domain.tld
- minio-2.rack-4.domain.tld

**Describe the solution you'd like**
I would like to have support for this notation:

```
minio-{0..2}.rack{2,4}.domain.tld
```

**Describe alternatives you've considered**
Hacks with /etc/hosts but that is not suitable due to SSL certificates verification.

**Comment by harshavardhana** [comment]
Yes you can use the config.yaml approach https://github.com/minio/minio/blob/master/docs/distributed/CONFIG.md

**Comment by fpytloun** [comment]
Thank you, @harshavardhana this is great, I didn't find this approach in docs 👍
