### ISSUE TITLE
Missing object version and size distribution metrics with enabled site replication

### ISSUE THREAD

**Issue by drasikhov** [minio/minio#18838]
Bucket metrics Prometheus endpoint includes the [following metrics](https://min.io/docs/minio/linux/operations/monitoring/metrics-and-alerts.html#distribution-metrics) about object sizes and versions distribution:
- minio_bucket_objects_size_distribution
- minio_bucket_objects_version_distribution

Maybe I've missed something from documentation and it works as expected, but If you will enable site-level replication, these metric are not in the Prometheus data anymore. Bucket-level replication is not affected and metrics are present in that case. Also these metrics are present in the cluster metrics endpoint with any replication configuration, including site-level.

## Expected Behavior
Metrics should probably be there.

## Your Environment
* Version used (`minio --version`): RELEASE.2024-01-16T16-07-38Z
* Server setup and configuration: 2 sites, 4 nodes and 4 drives on each site.
* Operating System and version (`uname -a`): Linux minio-01.example.com 5.15.0-87-generic # 97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 22.04)

**Comment by shtripat** [comment]
I am able to simulate this locally. Will check this in detail and keep posted.
