### ISSUE TITLE
Setting bucket's quotas from SDK

### ISSUE THREAD

**Issue by Vestrond** [minio/minio#18839]
**Is your feature request related to a problem? Please describe.**
Changing bucket quotas currently requires manual intervention through the MinIO console or command line, causing inconvenience and limiting automation possibilities.

**Describe the solution you'd like**
Enable the ability to programmatically modify the quota of any MinIO bucket using any SDK, such as the Python SDK. This would streamline operations and allow for more efficient management of storage resources.

**Describe alternatives you've considered**
Manually adjusting quotas through the MinIO console or command line is the current workaround. However, having a programmatic option via SDKs would greatly enhance flexibility and automation.

**Additional context**
This change would make it easier for folks who want to automatically control storage limits, offering a more user-friendly and seamless experience with MinIO.

**Comment by harshavardhana** [comment]
https://pkg.go.dev/github.com/minio/madmin-go#AdminClient.SetBucketQuota

https://github.com/minio/minio-py/blob/master/minio/minioadmin.py#L692

??

**Comment by Vestrond** [comment]
It's strange, but there's nothing in the documentation about this feature, or about the MinioAdmin class in general.

https://min.io/docs/minio/linux/developers/python/API.html

**Comment by ravindk89** [comment]
The web docs pull from the core S3 API that is available. We don't document `madmin` *yet*, it's on the to-do list but will require resources from the SDK engineering side of things - no timeline on that.

**Comment by hsafe** [comment]
Hello there,
One very important feature to consider in developing it, is to limit it to its sandbox/privileges and avoid a globally privileged account:
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:*"
   ],
   "Resource": [
    "arn:aws:s3:::private-*/*",
    "arn:aws:s3:::public-*/*"
   ]
  }
 ]
}
The account is allowed to run all commands within its limits. Currently your solution is only for a super admin. This is against multi-tenancy paradigm
