### ISSUE TITLE
feat: Correctly setting GOMEMLIMIT to prevent OOM generation 

### ISSUE THREAD

**Issue by jiuker** [minio/minio#18849]
**Is your feature request related to a problem? Please describe.**
Correctly setting GOMEMLIMIT to prevent OOM generation 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
Please outline what all you found @jiuker - whenever you are back - thanks.

**Comment by jiuker** [comment]
GOMEMLIMIT is a threshold for garbage collection (GC). When the used memory approaches this limit, a full GC will be triggered frequently. If a business application is running, this can significantly impact performance, keeping the program's memory usage below this limit. Previously, we could set the percentage of GOGC, for example, setting it to 100%. If the used memory is 1GB during the first GC, then the trigger for the second GC would be 2GB. However, in a virtual machine environment where memory is limited, such as a virtual machine with only 16GB of memory, if the used memory during a GC is 12GB, the theoretically used memory for the next GC would be 24GB. This value far exceeds the physical memory, and the host machine would terminate the process. This generally refers to a full GC. It is recommended to set the value to 90% of the host machine's memory if there is only one minio-server running on the host. @harshavardhana

**Comment by harshavardhana** [comment]
So it is completely okay to set the GOMEMLIMIT to 90% of the actual physical memory available.

**Comment by jiuker** [comment]
> So it is completely okay to set the GOMEMLIMIT to 90% of the actual physical memory available.

Yes, we can set it to 90% of the host machine's memory, but we need a mechanism to automatically obtain the host machine's memory. @harshavardhana However, this approach may not always be entirely reasonable. When multiple applications are deployed on the same node, the available memory becomes smaller, which can affect this value. Generally speaking, if this node is dedicated solely to the deployment of the minio-server without any other applications, setting it to 90% is more reasonable.

**Comment by ginn13** [comment]
<img width="1400" alt="image" src="https://github.com/minio/minio/assets/11777877/639d5d46-809e-4bd0-8089-c20039452d0a">
minio:2024.2.17 gets constantly OOMKilled on a 16GB machine with pod memory limit of 12GB ram, until I set GOMEMLIMIT=4GiB

Actually looks like a memory leak

**Comment by harshavardhana** [comment]
@ginn13, please upgrade to the new release, remove GOMEMLIMIT, and let us know how it goes. OOMs should never happen. However, 12GiB RAM is relatively low if you are an active cluster user and also you have a high volume of data sitting on the namespace.

Most of our production deployments have a minimum of 32GiB per node.

**Comment by dormanze** [comment]
> @ginn13, please upgrade to the new release, remove GOMEMLIMIT, and let us know how it goes. OOMs should never happen. However, 12GiB RAM is relatively low if you are an active cluster user and also you have a high volume of data sitting on the namespace.
> 
> Most of our production deployments have a minimum of 32GiB per node.

RELEASE.2024-02-17T01-15-57Z is a newer version and I don't see any memory usage optimizations between it and the latest RELEASE.2024-02-26T09-33-48Z.
We also have frequent oom issues with the container version.  Each time we have solved it by increasing the container memory or reducing the frequency of listobject.

**Comment by jiuker** [comment]
> <img alt="image" width="1400" src="https://private-user-images.githubusercontent.com/11777877/307547489-639d5d46-809e-4bd0-8089-c20039452d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDYwMzEsIm5iZiI6MTcwOTAwNTczMSwicGF0aCI6Ii8xMTc3Nzg3Ny8zMDc1NDc0ODktNjM5ZDVkNDYtODA5ZS00YmQwLTgwODktYzIwMDM5NDUyZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAzNDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTVmYTk2YjQ3ZDQ2YWVmYmEyMzc5M2FmYmUwZGIyNWFjOWUxNzQyMzk4MjQ0YzU3ODM1YWRjYmQxNWM2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PFfQEi6ho8d5e3KVXxLwujPEhXGSQjTTdnalDzXdHYQ"> minio:2024.2.17 gets constantly OOMKilled on a 16GB machine with pod memory limit of 12GB ram, until I set GOMEMLIMIT=4GiB
> Actually looks like a memory leak

`GOMEMLIMIT` control the GC. Not for REAL MEMERY LIMIT @ginn13 . Minio need 32GB, so need 32GB at all.

**Comment by harshavardhana** [comment]
> Yes, we can set it to 90% of the host machine's memory, but we need a mechanism to automatically obtain the host machine's memory. @harshavardhana However, this approach may not always be entirely reasonable. When multiple applications are deployed on the same node, the available memory becomes smaller, which can affect this value. Generally speaking, if this node is dedicated solely to the deployment of the minio-server without any other applications, setting it to 90% is more reasonable.

@jiuker feel free to send a PR `setMaxMemory()` is the function that you can use here, we can keep this opt-in for now. 

Add a flag --memlimit (hidden) this way we can push this out and have a way to observe the usability of this environment in production deployments.

> RELEASE.2024-02-17T01-15-57Z is a newer version and I don't see any memory usage optimizations between it and the latest RELEASE.2024-02-26T09-33-48Z.
> We also have frequent oom issues with the container version. Each time we have solved it by increasing the container memory or reducing the frequency of listobject.

Listobjects() won't cause OOM; what causes OOM is page-cache build-up. This is Systemd's problem, and it's stupid memory accounting. It falsely pins all the page-cache memory to MinIO's memory. We never use any active memory beyond 16GiB at best. More high-performance systems see memory usage go up to 32Gi this is re-usable memory that we allocate.

@dormanze you may want to turn-off systemd's memory accounting it is dumb.

```
# Turn-off memory accounting by systemd, which is buggy.
MemoryAccounting=no
```

**Comment by nwasya** [comment]
@harshavardhana 
thanks to @jiuker for reporting this issue.
I face same issue since I've updated minio last month.
I have two virtual machines with same resource. the first one is the main one and second one is the one I used to mirror the main instance. and both instances are using docker with 4 replicas.
I updated both instances but on the mirror instance, I'm having memory leak while the main instance goes as well as previous.
![Capture](https://github.com/minio/minio/assets/90377853/3b5ab54f-8324-44f2-8d31-46502c5e99ba)
once a couple of days, I have to restart minio in order to free memory.
I also set GC and GOGC environment variables on my docker-compose file but couldn't see any differences.

**Comment by nwasya** [comment]
@harshavardhana
thanks to @jiuker for reporting this issue.
I face same issue since I've updated minio last month.
I have two virtual machines with same resource. the first one is the main one and second one is the one I used to mirror the main instance. and both instances are using docker with 4 replicas.
I updated both instances but on the mirror instance, I'm having memory leak while the main instance goes as well as previous.
![image](https://github.com/minio/minio/assets/90377853/bfbfccad-27f3-4133-8482-18688a80e3f1)once a couple of days, I have to restart minio in order to free memory.
I also set GC and GOGC environment variables on my docker-compose file but couldn't see any differences.
and this an output of docker stats:

![image](https://github.com/minio/minio/assets/90377853/9783c775-9ec3-47ad-a7ab-b7953a7402fe)

memory keep increasing!

**Comment by jiuker** [comment]
> once a couple of days, I have to restart minio in order to free memory.
> I also set GC and GOGC environment variables on my docker-compose file but couldn't see any differences.
> and this an output of docker stats:

Could you try to set `GOMEMLIMIT ` ?  @nwasya

**Comment by nwasya** [comment]
> Could you try to set `GOMEMLIMIT ` ? @nwasya

yes it woked!
leak stopeed!
Thank you. <3
my memory is 16 and I set it to GOMEMLIMIT=8GiB.
but what if I want to use this on production environment? is that ok? I'm worried about my performance or even data loss.

**Comment by klauspost** [comment]
@nwasya If you are using it in a production environment you should get a [subscription](https://min.io/pricing).

**Comment by huozhirui** [comment]
> > Could you try to set `GOMEMLIMIT ` ? @nwasya
> 
> yes it woked! leak stopeed! Thank you. <3 my memory is 16 and I set it to GOMEMLIMIT=8GiB. but what if I want to use this on production environment? is that ok? I'm worried about my performance or even data loss.

How to set this parameter? Is it in the environment variable?
this?
env: 
   - name: MINIO_MEMLIMIT
      value: 8589934592    # 8Gib

**Comment by harshavardhana** [comment]
yes? or `--memlimit`

**Comment by huozhirui** [comment]
> yes? or `--memlimit`

Can you provide a complete user manual? How do I know if it's effective?

**Comment by jiuker** [comment]
> --memlimit

minio server /data --memlimit 8Gi

**Comment by huozhirui** [comment]
> > --memlimit
> 
> minio server /data --memlimit 8Gi

![image](https://github.com/minio/minio/assets/55824382/4813fa6a-1db5-4a3c-9016-ca62ade44ec4)
When I adjusted the limit to 4GiB, the mini CPU suddenly increased. Is this normal?
<img width="396" alt="image" src="https://github.com/minio/minio/assets/55824382/37e413a3-6554-4589-a75b-cbae9a627d28">

**Comment by jiuker** [comment]
see https://github.com/minio/minio/issues/18849#issuecomment-1965739753
@huozhirui

**Comment by harshavardhana** [comment]
Yes it is normal more GC work @huozhirui
