### ISSUE TITLE
Azure Storage, Support Workload Identity

### ISSUE THREAD

**Issue by michelefa1988** [minio/minio#18848]
**Is your feature request related to a problem? Please describe.**
Azure has added Azure Workload Identities (see https://github.com/Azure/azure-workload-identity and https://azure.github.io/azure-workload-identity/docs/) to AKS. The functionality is stable and is the recommended approach for production authentication to an Azure Storage Account.

AWI is essentially the equivalent of AWS's IAM Roles for Service Accounts and works the same. I.e, your cluster becomes an OIDC identity provider and a specific service account in a specific namespace can be designated as federated principal to which Azure IAM roles can be attached. This is significantly more secure than using credentials (StorageAccountName + secret)

**Describe the solution you'd like**
Support for Azure Workload Identity

**Describe alternatives you've considered**
I couldn't find any mention of this in the documentation.

**Comment by jiuker** [comment]
@michelefa1988 Could you use the env like 
```env
	MINIO_IDENTITY_OPENID_CONFIG_URL="https://login.microsoftonline.com/<azure tenant>/v2.0/.well-known/openid-configuration"
	MINIO_IDENTITY_OPENID_CLIENT_ID="<client id>"
	MINIO_IDENTITY_OPENID_CLIENT_SECRET="<client secret>"
	MINIO_IDENTITY_OPENID_SCOPES="profile openid email"
	MINIO_IDENTITY_OPENID_REDIRECT_URI="http://localhost:9001/oauth_callback"
	MINIO_IDENTITY_OPENID_COMMENT="AzureAD"
```
to resolve your problem?

**Comment by jiuker** [comment]
If you are look the way to config tier. You can check the [doc](https://min.io/docs/minio/linux/reference/minio-mc/mc-ilm-tier-add.html#command-mc.ilm.tier.add )
For this
```
Use Azure Blob Storage as the storage backend for the new Tier.

Requires also specifying the following parameters:

[--account-name](https://min.io/docs/minio/linux/reference/minio-mc/mc-ilm-tier-add.html#mc.ilm.tier.add.-account-name)

[--account-key](https://min.io/docs/minio/linux/reference/minio-mc/mc-ilm-tier-add.html#mc.ilm.tier.add.-account-key)
```
like 
```
mc ilm tier add minio myminio WARM-MINIO-TIER                     \
                               --endpoint https://login.microsoftonline.com/<azure tenant>/v2.0/.well-known/openid-configuration   \
                               --account-name ClientID \
                               --account-key ClientSecret \
                               --bucket mybucket                   \
                               --prefix myprefix/
```
