### ISSUE TITLE
Warning: The standard parity is set to 0. This can lead to data loss.

### ISSUE THREAD

**Issue by furllmm** [minio/minio#18867]
i downloaded windows version and runned server in cmd and says this
how to fix

**Comment by harshavardhana** [comment]
Run a distributed setup with HA.

**Comment by furllmm** [comment]
@harshavardhana  can yu explain

**Comment by klauspost** [comment]
@furllmm https://min.io/docs/minio/windows/operations/concepts.html

**Comment by furllmm** [comment]
i dont understand how to fix
