### ISSUE TITLE
NATS.io creds authentication

### ISSUE THREAD

**Issue by svallebro** [minio/minio#18881]
**Is your feature request related to a problem? Please describe.**
I'm trying to enable nats.io, but my nats deployment is configured with the new decentralized auth using a creds file.
It seems like minio only supports [token auth](https://docs.nats.io/using-nats/developer/connecting/token) and [username + password](https://docs.nats.io/using-nats/developer/connecting/userpass)

**Describe the solution you'd like**
It would be nice to support this kind of authentication from Minio as well.
[https://docs.nats.io/using-nats/developer/connecting/creds](https://docs.nats.io/using-nats/developer/connecting/creds)

**Describe alternatives you've considered**
Spin up an extra container with a NATS server and connect it to the cluster using a leaf node connection
Seems like an overkill solution to handle this missing feature

**Additional context**
This authentication was added to the NATS server from version 2.x

**Comment by jiuker** [comment]
Fix by https://github.com/minio/minio/pull/19139
