### ISSUE TITLE
XL: Read of a large part will cause out of memory error

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1889]
```
98                  var buffer []byte                                                                                                                                             
99                  buffer, err = erasureReadFile(onlineDisks, bucket, pathJoin(object, partName), partName, partSize, eInfos)                                                    
100                 if err != nil {                                                                                                                                               
101                         return err                                                                                                                                            
102                 }
```

If it was a PUT operation of a large file (for example a 4G file on a VM with 3G RAM) this operation will fail with oom error.
@harshavardhana  Was it a conscious decision to do it this way?

**Comment by harshavardhana** [comment]
> 98                  var buffer []byte  
> 99                  buffer, err = erasureReadFile(onlineDisks, bucket, pathJoin(object, partName), partName, partSize, eInfos)  
> 100                 if err != nil {  
> 101                         return err  
> 102                 }
> If it was a PUT operation of a large file (for example a 4G file on a VM with 3G RAM) this operation will fail with oom error.
> @harshavardhana Was it a conscious decision to do it this way?

It was designed little differently before to return just necessary data blocks as the actual size was being read in a loop, it was an oversight i think when the code moved inside erasureReadFile. 

We should fix this, two approaches that i can think of
- Move the loop from inside ReadFile() to the GetObject() - this is how it was previously. 
- My approach would be to take the writer directly and write to it.

**Comment by balamurugana** [comment]
> My approach would be to take the writer directly and write to it.

As per our discussion, we go with this approach.

**Comment by GarimaKapoor** [comment]
please update timeline for the fix
