### ISSUE TITLE
RELEASE.2024-01-18T22-51-28Z prints an excess of debug messages to the console

### ISSUE THREAD

**Issue by pkhamre** [minio/minio#18896]
## Expected Behavior

After upgrading to version **RELEASE.2024-01-28T22-35-53Z** from **RELEASE.2024-01-18T22-51-28Z** the console on the server prints out a whole lot of unnecessary debug messages. These didn't print on previous version.

## Steps to Reproduce (for bugs)

Upgrade to the latest release and watch the console logs.

## Your Environment

Currently running on docker **25.0.1** with the following docker image: **minio/minio:RELEASE.2024-01-28T22-35-53Z**

```
# uname -a
Linux minio-server 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/issue
Ubuntu 20.04.6 LTS
```

**Comment by harshavardhana** [comment]
@pkhamre https://github.com/minio/minio/releases/tag/RELEASE.2024-01-29T03-56-32Z

**Comment by harshavardhana** [comment]
You are too late we already fixed it 🍰
