### ISSUE TITLE
runtime: out of memory - after newest update

### ISSUE THREAD

**Issue by timheerwagen** [minio/minio#18906]
## Expected Behavior

Minio starts as usual.

## Current Behavior

I have been using minio/minio with docker-compose for some time now. However, since the last update, minio crashes immediately on startup.

## Possible Solution

I have tried an older version and everything runs as usual. 
`minio/minio:RELEASE.2024-01-05T22-17-24Z-cpuv1`

[Logs.txt](https://github.com/minio/minio/files/14089132/Logs.txt)

**Comment by harshavardhana** [comment]
This is because you don't have enough memory available on the system and we are pre-allocating memory upto 1G if you are CI/CD like environment set 

CI=true environment variable - we expect that you have a minimum of 1GiB memory to start MinIO for all serious use-cases.

**Comment by harshavardhana** [comment]
Just for understanding

- Single node requires a minimum of 1 GiB memory
- Distributed node requires a minimum of 2 GiB memory
- If CI=true is set then it only expects 256 MiB

These are at the least expected from a deployment from now on. // cc @ravindk89 

Anything lower than 256 MiB is practically meaningless for operational purposes.

**Comment by timheerwagen** [comment]
Thank you for the quick reply and also for the detailed explanation.

The memory was always more than sufficient for small and normal amounts of data, so I'm wondering why this has now changed. 
I don't want to increase any server capacity now to save costs because the system has worked very well and hasn't come close to pushing the server to its limits.

```
Linux ubuntu 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Usage of /:                       11.7% of 77.35GB
Memory usage:                     51%
Swap usage:                       0%

total        used        free      shared  buff/cache   available
Mem:         1908276      885216      119704        1780      903356      836168
```

**Comment by ravindk89** [comment]
@harshavardhana I'll work on documenting these new limits - thanks

**Comment by harshavardhana** [comment]
> The memory was always more than sufficient for small and normal amounts of data, so I'm wondering why this has now changed.
> I don't want to increase any server capacity now to save costs because the system has worked very well and hasn't come close to pushing the server to its limits.

You don't want to is a different problem. I cannot help you there. I just laid out what was expected and why we have made these changes.

**Comment by harshavardhana** [comment]
For safety measures, we can add a "fallback" of sorts, where memory is simply super constrained (so we start anyway) - but that is Pull Request + release away.
