### ISSUE TITLE
Veeam SOSAPI capacity.xml and system.xml are physically created in site-replicated setups

### ISSUE THREAD

**Issue by rluetzner** [minio/minio#18916]
## Expected Behavior

The following two files are supposed to only exist virtually on buckets:
* .system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/capacity.xml
* .system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/system.xml

## Current Behavior

Once the files mentioned above are read in a site-replicated setup, MinIO eventually writes a physical copy to disk. In case of the capacity.xml, this creates infinite versions until the version limit is hit and MinIO starts logging errors.

## Possible Solution

-

## Steps to Reproduce (for bugs)

```bash
# Run two instances of MinIO
MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server ./data1 --console-address ":9001" --address ":9000"
MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server ./data2 --console-address ":9003" --address ":9002"

mc alias set local1 http://localhost:9000 admin password
mc alias set local2 http://localhost:9000 admin password

# Enable site-replication
mc admin replicate add local1 local2

mc mb local1/new-bucket

# Do any of the following operations
mc stat local1/new-bucket/.system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/capacity.xml
mc ls local1/new-bucket/.system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/capacity.xml
mc cat local1/new-bucket/.system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/capacity.xml
```

## Context

Discovered in combination with Veeam 12.

## Regression

-

## Your Environment

* Version used (`minio --version`): RELEASE.2024-01-29T03-56-32Z (commit-id=9987ff570bcea7c26a8faec32910f10f49576d0c)
* Server setup and configuration: as described above
* Operating System and version (`uname -a`): `Linux IT-FR-NB-RS-19 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ravindk89** [comment]
I think this is just an unfortunate consequence of how versioning works.

https://min.io/docs/minio/linux/reference/minio-mc/mc-version-enable.html#mc.version.enable.-excluded-prefixes <- I believe you can use this to exclude the `/.system-` prefix in bucket(s) to prevent those from having versions created, which should solve the issue. Can you give that a shot?

**Comment by klauspost** [comment]
@ravindk89 No. This is a "virtual" object. It doesn't exist, except it does when you ask for it. It is not supposed to be replicated so something is picking it up.

**Comment by ravindk89** [comment]
cc/ @poornas

**Comment by ravindk89** [comment]
@rluetzner while we look into the issue, can you try the prefix-ignore configuration suggested above as a workaround?

**Comment by poornas** [comment]
@rluetzner, this is being fixed - as a workaround you could do `mc rm --force --purge <alias>/<bucket>/.system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/`  on both sites to remove these versions

**Comment by aweisser** [comment]
**Here's a theory:** 
- The first time the virtual object is read by an external caller on site1 a read event triggers the replication subsystem on site1, which now tries to make sure that the object is present on site2. 
- So the replication procedure tries to read the object from site2, to see if it's present or older than the object version on site1.
- Every time the virtual object is read the caller gets UTC now as the creation date. 
- So, for the replication logic there's always a missmatch between the two sites, thus there's something to fix with a PUT Object operation.
- Once triggered, through the initial read operation in step 1, this ends up in a loop, until 10000 object versions are created.

**Comment by aweisser** [comment]
I think to fix this. the site replication needs to be "SOSAPI aware". The virtual object should simply not be replicated at all.

**Comment by rluetzner** [comment]
Thanks for the quick fix. 🙂 

I wanted to add that the suggested workaround also fixes the issue.

```bash
mc version enable --excluded-prefixes ".system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c" local1/new-bucket
mc rm --force --purge local1/new-bucket/.system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/
mc rm --force --purge local2/new-bucket/.system-d26a9498-cb7c-4a87-a44a-8ae204f5ba6c/
```

Once I ran these commands I could stat, list or read the capacity.xml and system.xml files as many times as I wanted and no physical files would be created.
