### ISSUE TITLE
Missing replication rules after setting up site replication

### ISSUE THREAD

**Issue by schnapsidee** [minio/minio#18919]
I just set up site replication via the web UI and while it seems to work just fine for some buckets and users, there are issues with more.
The setup itself worked, there are a bunch of errors telling me that buckets cannot be replicated. One example (I removed the bucket name): 

```
API: SYSTEM()
2024-01-30T18:11:51.214302289Z Time: 18:11:51 UTC 01/30/2024
2024-01-30T18:11:51.214305879Z DeploymentID: 2017b77e-0ffa-4619-b262-1acb61d387db
2024-01-30T18:11:51.214309309Z Error: replication resync of $BUCKETNAME for arn arn:minio:replication::cd76290b-a82b-4756-b3d3-1dfc65fce72c:$BUCKETNAME failed with The replication configuration was not found: $BUCKETNAME (*fmt.wrapError)
       2: internal/logger/logger.go:259:logger.LogIf()
2024-01-30T18:11:51.214314919Z        1: cmd/bucket-replication.go:2589:cmd.(*replicationResyncer).resyncBucket()
```

There are also a couple of users that were not replicated. I restarted the main site a couple of times (`mc admin service restart`) and it replicated additional users each time, but it did not replicate any additional buckets.

I tried `mcli admin replicate resync start` and only got this error: `partial failure in starting site resync`

## Expected Behavior
I expected all buckets and their content to be replicated

## Current Behavior
Some buckets were replicated (including content), most were not.

## Steps to Reproduce (for bugs)
1. Set up Minio Cluster (I have 1000+ buckets, not sure if relevant)
2. Set up second Minio Cluster
3. Set up site replication
4. Check Replication Status

## Your Environment
* Version used: RELEASE.2024-01-11T07-46-16Z

**Comment by harshavardhana** [comment]
> * Version used: RELEASE.2024-01-11T07-46-16Z

Please re-do the entire setup with the latest release @schnapsidee there was a regression in that is already fixed in the latest release.
