### ISSUE TITLE
docker: Image fails to start on Red Hat Enterprise Linux 7.2

### ISSUE THREAD

**Issue by mgardiner** [minio/minio#1891]
## Expected behaviour

Be able to start the Minio docker container.
## Actual behaviour

Fails to start and listing the logs on the failed container shows the following results:
`time="2016-06-10T17:14:56Z" level=fatal msg="Unable to colorize experimental update notification string ‘’." error="inappropriate ioctl for device" probe="{\"cause\":25,\"trace\":[{\"line\":50,\"file\":\"notifier.go\",\"func\":\"main.colorizeUpdateMessage\"},{\"line\":93,\"file\":\"update-main.go\",\"func\":\"main.updateMessage.String\",\"env\":{\"Tags\":[\"\"]}}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"2\",\"host.lang\":\"go1.6\",\"host.name\":\"abbddcef35f5\",\"host.os\":\"linux\",\"mem.heap.total\":\"4.8MB\",\"mem.heap.used\":\"2.0MB\",\"mem.total\":\"7.7MB\",\"mem.used\":\"2.0MB\"}}" 
time="2016-06-10T17:18:35Z" level=fatal msg="Unable to colorize experimental update notification string ‘’." error="inappropriate ioctl for device" probe="{\"cause\":25,\"trace\":[{\"line\":50,\"file\":\"notifier.go\",\"func\":\"main.colorizeUpdateMessage\"},{\"line\":93,\"file\":\"update-main.go\",\"func\":\"main.updateMessage.String\",\"env\":{\"Tags\":[\"\"]}}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"2\",\"host.lang\":\"go1.6\",\"host.name\":\"abbddcef35f5\",\"host.os\":\"linux\",\"mem.heap.total\":\"5.8MB\",\"mem.heap.used\":\"2.0MB\",\"mem.total\":\"7.3MB\",\"mem.used\":\"2.0MB\"}}"`
## Steps to reproduce the behaviour

docker run -p 9000:9000 --name minio1 -v /mnt/export/minio1:/export -v /mnt/config/minio1:/root/.minio  minio/minio /mnt
## Minio version

minio/minio:latest
## System information

RedHat Enterprise Linux 7.2
Docker 1.11.2
Running headless

**Comment by harshavardhana** [comment]
Issue exists at 

notifier.go:47

```
    terminal, err := ts.GetSize()
        if err != nil {
                return "", err
        }
```

GetSize() internally tries to access `/dev/tty` looks like is not accessible under Red Hat Enterprise Linux.

**Comment by harshavardhana** [comment]
We could simply ignore the error and fall back to terminal width of `80x25`
