### ISSUE TITLE
After setting environment variable "MINIO_SERVER_URL", some interface errors occur. 

### ISSUE THREAD

**Issue by bookc-man** [minio/minio#18914]
https://github.com/minio/console/issues/2165

This problem still exists

minio version RELEASE.2024-01-18T22-51-28Z (commit-id=19387cafab76133c2e7642de4aac8c81b9f4f8c7)
Runtime: go1.21.6 linux/amd64
License: GNU AGPLv3 https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

**Comment by jiuker** [comment]
Could you provide nginx.conf and minio pod log？

**Comment by harshavardhana** [comment]
Please upgrade to latest release.

**Comment by wujun4code** [comment]
@bookc-man MINIO_SERVER_URL should be the api endpoint, the latest version fixed now.

**Comment by dom6770** [comment]
I can't get this to work. The console is barely working, especially on /browser or /bucket. Sometimes it's just a blank white page, Sometimes under /browser it shows no buckets, sometimes the error "unexpected end of JSON input" appears, sometimes it's an HTTP ERROR 502. Every reload results in a different result. It's a mess. 

API is s3.example.org
Console is minio.example.org

```
MINIO_BROWSER_REDIRECT_URL=https://minio.example.org
MINIO_SERVER_URL=https://s3.example.org
```

My Caddy file:

```
*.example.org {
    # Minio - API
    @minio-api host s3.example.org
    reverse_proxy @minio-api DockerServer.home.local:9000
	
    # Minio - Console
    @minio-console host minio.example.org
    reverse_proxy @minio-console DockerServer.home.local:9010
}
```

Any help would be highly appreciated.

**Comment by dakolli** [comment]
@dom6770 
I resolved this by removing MINIO_SERVER_URL entirely from the config, it seems to work fine if you add that variable back after logging into the console one time. Must have something to do with authentication within minio but im not sure.

**Comment by MFYDev** [comment]
I searched for very long time and found every related issue is marked as solved. However I am using the latest version, and this issue exists. Nobody who said solved actually posted any helpful info but closed the issue. speechless
