### ISSUE TITLE
Docker: Access Keys effective permissions differ from console output

### ISSUE THREAD

**Issue by rad4day** [minio/minio#18939]
## Desciption

Creating an access key without manually modifying its permissions results in a key which has no permissions.
This breaks existing keys as well as new keys, if there was no policy assigned to the key manually.

## Expected Behavior
The key should inherit the policies assigned to the user unless restricted otherwise, or at least have the permissions shown in the console be accurate.

## Current Behavior
An access key created under a user assigned the default readwrite policy, gets a 403 response on
`mc ls local/`, even though the console shows the following policy as effective for the key:

```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:*"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
```

Possible Solution

## Steps to Reproduce (for bugs)

1. Setup the docker-compose stack as present in docs/orchestration
2. create an access token (with consoleAdmin or other permissions on your user account)
3. add access token as mc alias 
4. get a 403 on mc ls alias/

## Context
This broke during the bugfix release last night and broke some deployments.

## Regression

YES. Broke in RELEASE-2024-01-31

## Your Environment
```
minio version RELEASE.2024-01-31T20-20-33Z (commit-id=24ecc44bac566b25a5bfa9772d946a19ce551035)
Runtime: go1.21.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```
Default docker-compose setup as present in docs/orchestration during the release specified above.

## Images
(All data is localhost throwaway setup)
![image](https://github.com/minio/minio/assets/12465878/639d5f80-673d-45ea-acd5-84036f8a0ce8)
![image](https://github.com/minio/minio/assets/12465878/c54d0e7c-b5af-453a-a6ce-7c5df12ed179)
![image](https://github.com/minio/minio/assets/12465878/6f487cd8-3c17-447e-ac5e-e279dd0eba36)
![image](https://github.com/minio/minio/assets/12465878/de665383-67dd-4131-ab74-0c6ed4ce9c1c)
![image](https://github.com/minio/minio/assets/12465878/983d90f6-4ed2-4762-89ca-4d4911e2eecd)
![image](https://github.com/minio/minio/assets/12465878/b24a71f4-9e10-41e3-9dad-5882ca8a9982)

**Comment by etlam** [comment]
Same here. Existing Access Keys stopped working immediately after the **security update**.

**Comment by vadmeste** [comment]
@donatello this seems to be happening with service accounts derived from the root access key. Taking a look.

**Comment by vadmeste** [comment]
It looks like the added defensive code caused the issue. I see the policy claim is embedded instead of inherited type and I think it is related to a quirk that we did implement long time ago (empty statements). We may need to add a specific code path for owner derived if we cannot get rid of that quirk.

**Comment by etlam** [comment]
**There is a temporary hotfix:**
1. Go to the service account and edit the Access key
2. Click update

**Comment by mariusc23** [comment]
In case it helps, older keys that are 16 characters long continued to work for me, but keys that are 20 characters long do not. The update fix above works for me.

**Comment by donatello** [comment]
I am working on a fix for this.

**Comment by etlam** [comment]
Fix does not seem to work. I updated to latest version (RELEASE.2024-03-03T17-50-39Z) and everything exploded again.
The workaround does not work any longer :(
