### ISSUE TITLE
Creating /tmp files, filling system disk

### ISSUE THREAD

**Issue by micah** [minio/minio#18944]
## Current Behavior
Since I updated to the latest version, Minio is creating files under /tmp, which it does clean up, but these files are filling my system disk. 

I was not expecting these files to appear here.

## Possible Solution

A configuration option to set the temporary directory so that I can manage where these are written. 

## Regression
This is new behavior from an upgrade I did, unfortunately, the upgrade had to traverse many versions to arrive at the latest.

## Your Environment

* Version used (`minio --version`): DEVELOPMENT.2024-01-28T22-52-17Z
* Server setup and configuration: Single Node Single Drive
* Operating System and version (`uname -a`): Debian Bookworm

**Comment by micah** [comment]
This appears to have been a stray process that was started with an old configuration.

**Comment by harshavardhana** [comment]
@micah are you compiling things yourself?
