### ISSUE TITLE
MinIO API unaccessable if MINIO_SERVER_URL is subdomain of MINIO_DOMAIN 

### ISSUE THREAD

**Issue by kasefuchs** [minio/minio#18962]
## Expected Behavior
MinIO API availiable on subdomain of MINIO_DOMAIN.

## Current Behavior
MinIO returns InvalidBucketName error.

## Possible Solution
Check if MinIO API is subdomain of MINIO_DOMAIN.

## Steps to Reproduce 

1. Set MINIO_DOMAIN env to example.com
2. Set MINIO_SERVER_URL env to https://s3.example.com
3. Access https://s3.example.com using browser/S3 client

## Context
I've been trying to host static websites on subdomains of my root domain using the Virtual-Host bucket style.

## Your Environment
* Version used: `RELEASE.2024-01-31T20-20-33Z (commit-id=24ecc44bac566b25a5bfa9772d946a19ce551035)`
* Server setup and configuration: `Docker version 25.0.0, Debian GNU/Linux 12`
* Operating System and version: `Linux pegatron 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux`

**Comment by jiuker** [comment]
https://{bukcet}.domain is another url for bucket action. @harshavardhana @klauspost  cc . If that's ok, close here.

**Comment by harshavardhana** [comment]
This is expected from virtual DNS support. We have no way to differentiate the s3.example.com to be a non virtual DNS request.

To make sure to avoid this domain value must be set to the value that will be the incoming DNS route to MinIO not your top level domain.

For example domain value must be same as MinIO server URL not a subdomain of each other.

This is a configuration issue please fix it.
