### ISSUE TITLE
error on HEAD (*errors.errorString) during bucket replication for existing objects

### ISSUE THREAD

**Issue by manju-rn** [minio/minio#18978]
## Setup
- In 2 separate k8s clusters (say east and west), minio operator based setup is done. 
- Each of the clusters 1 Tenant is installed. Hence, 2 mino servers, one in each cluster
- The minio servers in each cluster is reachable via the traefik ingress
- The bucket in Minio west cluster is replicated to bucket in Minio east cluster. The connectivity is via the public url which points to ingress of the east cluster.  All the replication options are set - Existing objects, Metadatasync, Delete Marker and Deletes
![image](https://github.com/minio/minio/assets/26291847/45948d72-72d9-493f-8cd6-744fea72839e)

What is working:
1. Objects directly uplaoded in minio servers in east or west cluster
2. **NEW** object uploaded in west minio server gets replicated in east minio cluster successfully. 
3. **DELETE** of objects including soft delete and delete all version done in west minio server is successfully deleted in east minio server

What is NOT working:
1. **EXISTING OBJECTS** If the replication is removed in west minio server. Then an object is added and replication is re-added. Then any objects that are added during the time when replication was removed i.e, existing objects, they are not replicated in the east minio server. In fact logs in west minio server continuosly report the following
logs report: 
```
API: SYSTEM()
Time: 02:18:44 UTC 02/06/2024
DeploymentID: 041b3b18-e370-4ea3-895c-eb5b543e10f2
Error: unable to replicate nextcloud-bucket-1/20240131_194949.jpg (6d2feeaa-b7ee-48e1-b992-1899675e8aa6). Target (https://<east minio server:443) returned Access Denied. error on HEAD (*errors.errorString)
       3: internal/logger/logger.go:259:logger.LogIf()
       2: cmd/bucket-replication.go:1440:cmd.ReplicateObjectInfo.replicateAll()
       1: cmd/bucket-replication.go:1050:cmd.replicateObject.func2()
```

## Expected Behavior
- Existing objects from west minio server should be replicated in the east minio server

## Current Behavior
1. **EXISTING OBJECTS** If the replication is removed in west minio server. Then an object is added and replication is re-added. Then any objects that are added during the time when replication was removed i.e, existing objects, they are not replicated in the east minio server. In fact logs in west minio server continuosly report the following
logs report: 
```
API: SYSTEM()
Time: 02:18:44 UTC 02/06/2024
DeploymentID: 041b3b18-e370-4ea3-895c-eb5b543e10f2
Error: unable to replicate nextcloud-bucket-1/20240131_194949.jpg (6d2feeaa-b7ee-48e1-b992-1899675e8aa6). Target (https://<east minio server:443) returned Access Denied. error on HEAD (*errors.errorString)
       3: internal/logger/logger.go:259:logger.LogIf()
       2: cmd/bucket-replication.go:1440:cmd.ReplicateObjectInfo.replicateAll()
       1: cmd/bucket-replication.go:1050:cmd.replicateObject.func2()
```

## Possible Solution
Root cause to be determined

## Your Environment
- In 2 separate k8s clusters (say east and west), minio operator based setup is done. 
- Each of the clusters 1 Tenant is installed. Hence, 2 mino servers, one in each cluster
- The minio servers in each cluster is reachable via the traefik ingress
- The bucket in Minio west cluster is replicated to bucket in Minio east cluster. The connectivity is via the public url which points to ingress of the east cluster.  All the replication options are set - Existing objects, Metadatasync, Delete Marker and Deletes
Minio version: RELEASE.2024-01-18T22-51-28Z  in both the minio servers (east and west clusters)

**Comment by harshavardhana** [comment]
@manju-rn it looks you are using credentials that do not have head object permissions.

**Comment by manju-rn** [comment]
> @manju-rn it looks you are using credentials that do not have head object permissions.

So the new objects do not have this issue of head? since they are created properly. 
Also, how can I check it and provide access? here is the same user with all the permission enabled in target minio server (east)
![image](https://github.com/minio/minio/assets/26291847/c9bebd4e-e3fe-44d8-8eaf-be8b45226d88)
![image](https://github.com/minio/minio/assets/26291847/cccc1b7f-59b7-40f2-997c-7f1bb7733697)

in the west minio server, if I do `mc head alias_of_east_minio_server/bucketname/object` it does return proper result.  Does this command not use head permissions?

**Comment by harshavardhana** [comment]
its the policy that is associated for the credential used to create the bucket replication targets.

**Comment by manju-rn** [comment]
> its the policy that is associated for the credential used to create the bucket replication targets.

thats exactly the screenshots I gave earlier for the user of (east cluster) what was used to create a replication feature in west cluster. All the policies were selected (diagnostics, readwrite, ...). I did all through minio UI.  Is there something I should add to the policy?  **Please guide me which policy may be missing.**

Also, I read through docs https://min.io/docs/minio/linux/administration/bucket-replication.html?ref=con#replication-of-existing-objects and do not see any specific policy - although I selected all

**Comment by harshavardhana** [comment]
Adding all policies is not needed, if you select all then only the lowest policy is applied causing incorrect behavior.

You only need to select readwrite policy.

**Comment by manju-rn** [comment]
> Adding all policies is not needed, if you select all then only the lowest policy is applied causing incorrect behavior.
> You only need to select readwrite policy.

Noted.  Just to be clear. On the target minio server bucket (where the replication is happening) i have provided the images of the Access policies of the bucket.  Please check if this is okay - since this is still not working when user just have "readwrite" access.

How do i check the logs at the target minio server (east minio server in my case)?  while the source minio server does print out the error, the target minio server does not print out anything, is there a debug mode that can be set? Since I would assume that the target minio server is sending out that errors to source

Image:1 - Access policies of Bucket - Cannot edit these, these are all the policies of the bucket
![image](https://github.com/minio/minio/assets/26291847/bd8221b0-0c9b-4642-8da1-e1c86492568a)

Image 2: The user for this bucket. The creds of this user is used in source minio server where replication is created
![image](https://github.com/minio/minio/assets/26291847/6194acfa-3ffb-49e5-bf55-7c2c820168bd)

Image 3: The access of the user
![image](https://github.com/minio/minio/assets/26291847/3f1243be-1068-487a-bf5a-3229d1fa3a83)

**Comment by poornas** [comment]
can you create a alias for the replication user defined on east minio server with 
`mc alias set eastuser <east-ep> <replication-user> <replication-password>`

`mc stat eastuser/nextcloud-bucket-1/20240131_194949.jpg --vid 6d2feeaa-b7ee-48e1-b992-1899675e8aa6` 

The policy of the replication user is not properly loaded or interpreted here - existing object replication needs GetObject permission for preliminary HEAD and is denied this permission by east minio server. It is also possible that one of the nodes does not have IAM system initialized properly - a service restart may fix the issue

Haven't been able to repro this with 2024-01-18 release or latest

**Comment by manju-rn** [comment]
@poornas Thanks for the reply. I will provide the details of the MC commands tomorrow as I had just removed the earlier setup and used Service Mesh (linkerd) to setup the connectivity across the east - west clusters to check if Ingress used in the previous setup may be the cause of the error.   So here are the 2 setup:
1. Setup 1 (see the image 1 below) - **Does not work as explained earlier**
    - Microk8s servers in OnPrem (east) and OCI cluster (west)
    - East Cluster is hosting its service via Cloudflare tunnel to the domain hosted by Cloudflare
    - West is using the domain name, creds and bucket from the minio server in the east
    - minio tenant is setup (using UI) without TLS (as it would be handled by Ingress) and without exposing the service as LoadBalancer / NodePort as Ingress is planned to be used. _All these are made via the minio operator setup UI_
    - Traefik Ingress is used to expose the minio service.  Please see the Ingress manifest used for Setup 1 after the images

2. Setup 2 (see the image 2 below) - **This does work and pretty fast too!**
   -  Microk8s servers in OnPrem (east) and OCI cluster (west)
   - Linkerd Service Mesh is installed in both the clusters and minio service of east is connected to west (using the Service Mirror and Linkerd SMI - Traffic Split option).  see here https://linkerd.io/2020/02/25/multicluster-kubernetes-with-service-mirroring/
   -  Since Linkerd from West cluster directly connects to its own Gateway in East cluster, there is no Traefik Ingress involved

Since the Setup2 does not involve the Traefik Ingress - I am wondering if Ingress is the cause of the issue?  Not sure whether any **specific consideration/ annotations needs to be taken care in ingress manifest**? 

Image 1:
![image](https://github.com/minio/minio/assets/26291847/af5e191c-ef49-42f7-929a-c8a28729600b)

Image 2:
![image](https://github.com/minio/minio/assets/26291847/88439eac-bfbf-4b0c-ac0f-8c267648e287)

Ingress manifest used in setup1 - Note that the TLS is handled by Ingress and hence the replication setup in minio uses "no" TLS
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api-minio-ingress
  namespace: minio-ns
  annotations:
    cert-manager.io/cluster-issuer: cf-cluster-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  rules:
  - host: "<API of east minio server>"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              name: http-minio
  tls:
  - hosts:
    - "<API of east minio server>"
    secretName: api-minio-tls
```

**Comment by manju-rn** [comment]
> The policy of the replication user is not properly loaded or interpreted here - existing object replication needs GetObject permission for preliminary HEAD and is denied this permission by east minio server. It is also possible that one of the nodes does not have IAM system initialized properly - a service restart may fix the issue

but the existing objects will not even be there in the east cluster. For example, I just replicated the Setup 1 as dep[icted in earlier comment 
1. a fresh instance of a minio server (say minio-minipc) is created in east cluster
2. Added another replication rule in west cluster's minio server. 
3. The bucket in the mino-minpc in east cluster is empty and was expected to be filled with this new replication rule. However, the result is
- New objects added to west cluster reflect correctly in minio-minipc
- The existing objects of west cluster still do not show up
- Error reported in minio server of west is the same as was experienced earlier
```
API: SYSTEM()
Time: 02:27:05 UTC 02/07/2024
DeploymentID: 041b3b18-e370-4ea3-895c-eb5b543e10f2
Error: unable to replicate nextcloud-bucket-1/20240131_194859.jpg (762812ed-1f5a-436e-ae29-8e642e90337d). Target (https://minio.minio-minipc<east cluster> :443) returned Access Denied. error on HEAD (*errors.errorString)
       3: internal/logger/logger.go:259:logger.LogIf()
       2: cmd/bucket-replication.go:1441:cmd.ReplicateObjectInfo.replicateAll()
       1: cmd/bucket-replication.go:1051:cmd.replicateObject.func2()
```

Here are the mc commands and their results.  alias `local` is minio in west cluster;  alias `minipc-link1` is the minio-server in `east` cluster;  replication rule is set in `local`
```
sh-5.1# mc ls local
[2024-01-27 13:10:21 UTC]     0B nextcloud-bucket-1/
sh-5.1# mc ls minipc-link1
[2024-01-29 14:41:45 UTC]     0B test-bucket-1/
sh-5.1# mc ls local/nextcloud-bucket-1 | wc -l
138
sh-5.1# mc ls minipc-link1/test-bucket-1 | wc -l
0
sh-5.1# mc cp test-file.txt local/nextcloud-bucket-1
...ies/test-file.txt: 86 B / 86 B ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953 B/s 0ssh-5.1#  mc ls minipc-link1/test-bucket-1
[2024-02-07 02:35:15 UTC]    86B STANDARD test-file.txt
sh-5.1# mc ls local/nextcloud-bucket-1 | wc -l
139
sh-5.1# mc ls minipc-link1/test-bucket-1 | wc -l
1
```
Below are the replication rule set in local. The first rule points to Setup 2 as per my earlier message.  The second rule is as per Setup 1 that I have just recreated.
I also manually ran the resync  - as you can see the output, the 1 file was successful (which was just added above) and rest of the existing objects in west cluster - 174 of them failed

```
sh-5.1# mc replicate ls local/nextcloud-bucket-1
Rules:
Remote Bucket: <mino in east cluster connected via linkerd mirror & SMI>/nextcloud-bucket-1
  Rule ID: cn117qkorndc73fs5djg
  Priority: 1

Remote Bucket: <minio in east cluster connected via traefik ingress>/test-bucket-1
  Rule ID: cn1efikorndc73fs5dk0
  Priority: 2

sh-5.1# mc replicate resync status local/nextcloud-bucket-1 --remote-bucket "arn:minio:replication::a32ffc4b-9066-495f-b7a9-cc28747934b2:test-bucket-1"
No replication resync status available.
sh-5.1# mc replicate resync start local/nextcloud-bucket-1 --remote-bucket "arn:minio:replication::a32ffc4b-9066-495f-b7a9-cc28747934b2:test-bucket-1"
Replication reset started for local/nextcloud-bucket-1 with ID 4f4325bd-0a95-48b8-9c8f-6441bfce32cc
sh-5.1# mc replicate resync status local/nextcloud-bucket-1 --remote-bucket "arn:minio:replication::a32ffc4b-9066-495f-b7a9-cc28747934b2:test-bucket-1"
Resync status summary:
● arn:minio:replication::a32ffc4b-9066-495f-b7a9-cc28747934b2:test-bucket-1
   Status: Completed
   Replication Status | Size (Bytes)    | Count
   Replicated         | 86 B            | 1
   Failed             | 0 B             | 174

```

**Comment by poornas** [comment]
the only difference b/w existing object replication vs incoming uploads is the extra HEAD call  - the logs clearly point to a permissions issue. You may have overwritten the canned `readwrite` policy on your east cluster or given a list of policies to this user that conflict and deny s3:GetObject permission. 

you can check the policies listed for `mc admin user info <east-alias> <repl-user>` 
and `mc admin policy info <east-alias> <policy-name>` for the list of policies printed under PolicyName and compare with your other cluster where it is working correctly. 

btw, as an example  - I am able to repro the issue if I overwrite the canned readwrite policy with an additional deny rule on GetObject.

**Comment by manju-rn** [comment]
@poornas as you could see from access <https://github.com/minio/minio/issues/18978#issuecomment-1928678727> is a read write.  Before this change that was advised from harshavardhan, there is np change done to user. Everything was selected as default in the Minio UI when creating the tenant- the user used to access the console and the repl user is the same.  
**Can you confirm what access policies must be there for this HEAD accecss?**  - is it read write? then it's already there

I am able to successfully repro this issue with all defaults in the minio UI when I access via ingress.  and successfully working when accessing via Traefik.  So may be the defaults for the access in Minio UI are incorrect

**Comment by harshavardhana** [comment]
Can you avoid MinIO UI and do this via `mc` ? @manju-rn

**Comment by manju-rn** [comment]
> Can you avoid MinIO UI and do this via `mc` ? @manju-rn

Here you go. Able to replicate the same again - The alias `minipc-link` is for the east cluster (target).  This same target mino server was used for testing both with Setup 1 (ingress) and Setup2 (Linkerd) - And with Setup 1, the existing objects fail and with Setup 2, the existing object pass.
**There was no change in the user access that was done between the 2 testing**. And hence my observation that somehow it fails from ingress. So was thinking if Traefik ingress does something to HEAD call which might cause this failure

```yml
sh-5.1# mc admin user info minipc-link manju-minio-minipc
AccessKey: manju-minio-minipc
Status: enabled
PolicyName: consoleAdmin
MemberOf: []
sh-5.1# mc admin policy info minipc-link consoleAdmin
{
 "PolicyName": "consoleAdmin",
 "Policy": {
  "Version": "2012-10-17",
  "Statement": [
   {
    "Effect": "Allow",
    "Action": [
     "admin:*"
    ]
   },
   {
    "Effect": "Allow",
    "Action": [
     "kms:*"
    ]
   },
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::*"
    ]
   }
  ]
 }
}
```

**Comment by harshavardhana** [comment]
I suspect you have some ingress caching enabled which is replaying the requests to MinIO, since these are signed requests they will fail if you cache them.

**Comment by harshavardhana** [comment]
With MinIO your ingress must be a pass-through. Since it's working with Linkerd, I am assuming this is just a setup issue for now. 

Closing this issue.

**Comment by manju-rn** [comment]
> With MinIO your ingress must be a pass-through. Since it's working with Linkerd, I am assuming this is just a setup issue for now.
> 
> Closing this issue.

Ah! you seem to be assuming things and jumping to close them!  Have you repro this issue with ingress?  There is no caching at ingress and no additional configuration, this out of box k8s ingress resource (see the manifest I had given earlier).  And it works for all the new Objects, just not for existing object - so how do you explain this? 
I would have assumed minio would be curious and intrested in replicating this setup as this is very common and simple k8s setup.  I have been able to reproduce with completely different clusters with both Traefik and Nginx.

Anyway your decision, If i do not hear further, I would have to stop my evaluation and send my research recommendation to my partners as this being open item - do correct my statement if any below:
_While the new object replication, including soft delete (delete marker) and permanent delete work perfectly fine, the issue is with existing objects replication when ingress is used to expose minio servers (tested with both Traefik and Nginx) with standard k8s ingress resources. Hence if minio is being used, if any downtime of the target backup storage system happens, it will cause replication for those objects to fail which were created during that downtime. Manual intervention in such cases may be required. Current workaround is to make a soft delete at Source and restoring the (non-deleted) version. This marks the object as "new" and it gets replicated properly. However, some automation will be required to track (using events in minio) and control this behavior OR using ansible to invoke MC client to see the differences in objects and take similar action...._

**Comment by slena1** [comment]
"Hello, have you resolved your issue? I seem to have encountered a similar problem when copying files in a Minio bucket. I am experiencing errors when copying files, particularly when the files are over 6GB in size. The error message I receive is 'context deadline exceeded'. This error traceback indicates an issue related to timeout. Here is the backtrace:
0: internal/logger/logger.go:260:logger.LogIf()
1: cmd/bucket-replication.go:1531:cmd.ReplicateObjectInfo.replicateAll()
2: cmd/bucket-replication.go:1051:cmd.replicateObject.func2()
