### ISSUE TITLE
docker-compose.yml部署minio集群无法通过端口映射启动，只有主机模式下才正常

### ISSUE THREAD

**Issue by zhl19911203** [minio/minio#18977]
1、minio版本：quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z

启动报错：
Attaching to test_minio_1
minio_1  | 
minio_1  | API: SYSTEM()
minio_1  | Time: 13:35:45 UTC 02/06/2024
minio_1  | Error: WARNING: Expected number of all hosts (2) to be remote +1 (2) (*errors.errorString)
minio_1  |        7: internal/logger/logger.go:243:logger.LogIf()
minio_1  |        6: cmd/peer-rest-client.go:836:cmd.newPeerRestClients()
minio_1  |        5: cmd/notification.go:1177:cmd.NewNotificationSys()
minio_1  |        4: cmd/server-main.go:378:cmd.initAllSubsystems()
minio_1  |        3: cmd/server-main.go:692:cmd.serverMain.func4()
minio_1  |        2: cmd/server-main.go:491:cmd.bootstrapTrace()
minio_1  |        1: cmd/server-main.go:691:cmd.serverMain()
minio_1  | WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance
minio_1  | ERROR Unable to configure server grid RPC services: grid: local host not found

2、docker-compose.yml内容如下

version: "3.7"
services:
  minio:
    image: "quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z"
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - "./minio/data1:/data1"
      - "./minio/data2:/data2"
      - "./minio/data3:/data3"
      - "./minio/data4:/data4"
    command: server --console-address ":9001" http://192.168.11.163:19000/data{1...4} http://192.168.11.164:19000/data{1...4}
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

在两台服务器执行docker-compose up -d  启动

问题
1、如果是这种端口映射，怎么设置启动参数？
2、如果改成：network=host是可以正常启动的
3、启动参数command里面需要添加端口号吗？有什么要求

**Comment by jiuker** [comment]
Use English plz.
