### ISSUE TITLE
UI: /buckets/add-bucket create lifecycle rule if retention is used

### ISSUE THREAD

**Issue by tsohst** [minio/minio#18981]
**Is your feature request related to a problem? Please describe.**
We've created a bucket, with object lock and 30 days of retention.
My understanding of "retention" was that objects get auto deleted after 30 days - since we've found out they are not.
We've applied a lifecycle rule now which seems to be the correct way for what I've wanted.

**Describe the solution you'd like**
Allow creation of lifecycle rules in "/buckets/add-bucket" when retention is enabled.

**Comment by harshavardhana** [comment]
No retention has nothing to do with deletion.

Retention is about protection against accidental deletes.

All you want is 30days deletion use ILM expiration.
