### ISSUE TITLE
It is not possible to run a multi-node port mapping configuration using docker-compose

### ISSUE THREAD

**Issue by zhl19911203** [minio/minio#18983]
version:  quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z

An error message is reported at startup
Attaching to test_minio_1
minio_1 |
minio_1 | API: SYSTEM()
minio_1 | Time: 13:35:45 UTC 02/06/2024
minio_1 | Error: WARNING: Expected number of all hosts (2) to be remote +1 (2) (*errors.errorString)
minio_1 | 7: internal/logger/logger.go:243:logger.LogIf()
minio_1 | 6: cmd/peer-rest-client.go:836:cmd.newPeerRestClients()
minio_1 | 5: cmd/notification.go:1177:cmd.NewNotificationSys()
minio_1 | 4: cmd/server-main.go:378:cmd.initAllSubsystems()
minio_1 | 3: cmd/server-main.go:692:cmd.serverMain.func4()
minio_1 | 2: cmd/server-main.go:491:cmd.bootstrapTrace()
minio_1 | 1: cmd/server-main.go:691:cmd.serverMain()
minio_1 | WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance
minio_1 | ERROR Unable to configure server grid RPC services: grid: local host not found

docker-compose.yml  content

version: "3.7"
services:
minio:
image: "quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z"
ports:
- "19000:9000"
- "19001:9001"
volumes:
- "./minio/data1:/data1"
- "./minio/data2:/data2"
- "./minio/data3:/data3"
- "./minio/data4:/data4"
command: server --console-address ":9001" [http://192.168.11.163:19000/data{1...4}](http://192.168.11.163:19000/data%7B1...4%7D) [http://192.168.11.164:19000/data{1...4}](http://192.168.11.164:19000/data%7B1...4%7D)
environment:
- MINIO_ROOT_USER=admin
- MINIO_ROOT_PASSWORD=12345678
healthcheck:
test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
interval: 30s
timeout: 20s
retries: 3

Run docker-compose up -d on both servers to start

issue
1. If this is the kind of port mapping, how to set the startup parameters?
2. If you change it to: network=host, it can be started normally
3. Do I need to add the port number to the startup parameter command?

**Comment by harshavardhana** [comment]
You need to enable --net=host since your host IP is not exposed inside container.

MinIO needs the IP that you use to communicate internode to be local to that system.
