### ISSUE TITLE
SHA-1 hash algorithm enabled on SFTP service

### ISSUE THREAD

**Issue by olljanat** [minio/minio#18986]
## NOTE
I found that MinIO has added support for [SFTP](https://min.io/docs/minio/linux/developers/file-transfer-protocol.html) however with quick testing with [ssh-audit](https://github.com/jtesta/ssh-audit) told me that SHA-1 hash algorithm looks be enabled by default and I didn't found way to disable it.

## Expected Behavior
SHA-1 is considered as weak algorithm so it would be better to default to have disabled with possibility to enable it by those who really need it.

## Current Behavior
ssh-audit command output:
```
(kex) diffie-hellman-group14-sha1    -- [fail] using broken SHA-1 hash algorithm
```

**Comment by klauspost** [comment]
@aead I don't expect you to disagree. But just checking.

**Comment by zveinn** [comment]
I'll add this to my list, got a couple of things to take care of first though
