### ISSUE TITLE
s3zip, cors/preflight requests and pre-signed urls.

### ISSUE THREAD

**Issue by lromor** [minio/minio#18998]
**Is your feature request related to a problem? Please describe.**

The s3zip feature described [here](https://github.com/minio/minio/blob/master/docs/extensions/s3zip/README.md) is really neat. In our use case, we would like to fetch many small files at the same time in the browser and this options is great.

There's a catch though, while it works seamlessly, since we are running minio on another origin than the main page and to enable this feature the custom header `x-minio-extract` must be set. 
Because of this,  a lot of pre-flight requests are sent greatly reducing the performance. 

**Describe the solution you'd like**

A simple workaround for other files is to use presigned-urls. In this way the request is considered "simple" , no custom headers are sent and so no preflight requests are generated. Would it make sense to allow `x-minio-extract` to be parsed/exist for presigned urls? 

**Describe alternatives you've considered**

1. Stop using the s3zip feature, using normal files and presigned urls.
2. Use a proxy to have same origin.

**Comment by harshavardhana** [comment]
These features are pretty complex and require a great deal of engineering time. We do not have the resources internally for this. 

We will close this for now; feel free to send a PR yourself. If this is a must-have, we will review, and if it's reasonable, we shall accept it.
