### ISSUE TITLE
Choose which node is responsible for decommissioning

### ISSUE THREAD

**Issue by broferek** [minio/minio#19001]
**Is your feature request related to a problem? Please describe.**
We started to decommission a pool and unfortunately for us, Minio picked up the first node of the pool to be the leader of the decommissioning process. However, this node has a hardware problem that we are struggling to understand which sometimes leads to the loss of one disk which comes back only after a reboot of the node.
So, our decommissioning process is often interrupted.

**Describe the solution you'd like**
We would like to have a configuration or an environment variable to decide which node bears the responsibility of the decommissioning.

**Describe alternatives you've considered**
I haven't found anything so far to work around the problem and we are fighting on a daily basis to resume the decommissioning when the problem happens.

**Comment by jiuker** [comment]
@broferek How did you perform the decommission `mc admin decommission start minio TARGET `?

**Comment by broferek** [comment]
yes this is the command I used.

**Comment by jiuker** [comment]
> yes this is the command I used.

How many nodes do you have ? @broferek

**Comment by broferek** [comment]
We have 2 pools :
- the first one has 8 nodes and is the one we want to decommission
- the second one has 16 nodes and is the one we want to keep after the completion of the decommission

**Comment by jiuker** [comment]
> We have 2 pools :
> 
> * the first one has 8 nodes and is the one we want to decommission
> * the second one has 16 nodes and is the one we want to keep after the completion of the decommission

Could you use `mc alias minio1 pool2Endpoint user password` and `mc admin decommission start minio1 firstPoolCmd`? @broferek

**Comment by harshavardhana** [comment]
This is fixed #19310 with a temporary solution for now.
