### ISSUE TITLE
OpenID Policy Variables conditions not working for admin:*

### ISSUE THREAD

**Issue by GitarPlayer** [minio/minio#19014]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am trying to use OpenID Policy Variables with MINIO_IDENTITY_OPENID_ROLE_POLICY so only a certain jwt:groups group is mapped to rights equivalent to the built-in consoleAdmin policy. The policy is identical to the built-in consoleAdmin but contains conditions to check against a group in the JWT token.

## Expected Behavior
```bash
# builtin policy
bash-5.1$ mc admin policy info dev consoleAdmin
{
 "PolicyName": "consoleAdmin",
 "Policy": {
  "Version": "2012-10-17",
  "Statement": [
   {
    "Effect": "Allow",
    "Action": [
     "admin:*"
    ]
   },
   {
    "Effect": "Allow",
    "Action": [
     "kms:*"
    ]
   },
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::*"
    ]
   }
  ]
 }
}
# my custom policy
bash-5.1$ mc admin policy info jwt-policy
{
 "PolicyName": "jwt-policy",
 "Policy": {
  "Version": "2012-10-17",
  "Statement": [
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::*"
    ],
    "Condition": {
     "ForAnyValue:StringEquals": {
      "jwt:groups": [
       "REDACTED"
      ]
     }
    }
   },
   {
    "Effect": "Allow",
    "Action": [
     "admin:*"
    ],
    "Condition": {
     "ForAnyValue:StringEquals": {
      "jwt:groups": [
       "REDACTED"
      ]
     }
    }
   },
   {
    "Effect": "Allow",
    "Action": [
     "kms:*"
    ],
    "Condition": {
     "ForAnyValue:StringEquals": {
      "jwt:groups": [
       "REDACTED"
      ]
     }
    }
   }
  ]
 },
 "CreateDate": "2024-02-08T10:03:10.092Z",
 "UpdateDate": "2024-02-08T10:26:42.002Z"
}
echo $MINIO_IDENTITY_OPENID_ROLE_POLICY
jwt-policy
```
Upon logging in I expect to see this:
![image](https://github.com/minio/minio/assets/51920729/bc5f4f2b-0315-4d53-acac-71859f4002bb)
Since I expect to have admin:* rights.

## Current Behavior
But I only see this:
![image](https://github.com/minio/minio/assets/51920729/8a5ac604-75f1-4638-99e4-e14dc700d9a4)
So I am confident that the jwt:groups condition evaluates to true. Also that the MINIO_IDENTITY_OPENID_ROLE_POLICY variables maps to an existing policy in minIO. Since I can login and also I can create buckets, delete objects etc. Basically I only get the s3:* action but not the others.

## Steps to Reproduce (for bugs)

1. Setup minIO integration with openid connect (keycloak for example)
2. Configure a role policy
3. Use conditions to match against the jwt:groups in the rule
4. You should only get s3:* but not the rest.

## Context
I would like to manage admin access without using JSON Web Token Claim and with RolePolicy and RoleARN only. I don't want to setup a second OIDC provider just for admin access if possible.

## Regression
No
## Your Environment

```bash
sh-5.1$ minio --version
minio version RELEASE.2024-02-06T21-36-22Z (commit-id=980fb5e2ab3674287207c9388bb8fda7a142cc64)
Runtime: go1.21.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration: https://github.com/minio/minio/tree/master/helm/minio
* Operating System and version (`uname -a`):
* sh-5.1$ uname -a
Linux minio-3 4.18.0-372.64.1.el8_6.x86_64 #1 SMP Thu Jun 29 14:42:09 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
docker pull minio/mc:RELEASE.2024-01-31T08-59-40Z since it's deployed on k8s

**Comment by harshavardhana** [comment]
Admin actions do not support resources or conditions.

**Comment by GitarPlayer** [comment]
could you kindly show me where this is documented if it is? So the next person will not recreate this issue

**Comment by harshavardhana** [comment]
> could you kindly show me where this is documented if it is? So the next person will not recreate this issue

It isn't documented means it's not supported yet.

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#mc-admin-policy-condition-keys

I'll double check (cc. @donatello ) if this list has changed, but it's a very limited list of condition keys. If we further disallow using them on any resource we can simply redact that section and say as much.
