### ISSUE TITLE
Server-side bucket replication Error Message: use of closed network connection (*errors.errorString)

### ISSUE THREAD

**Issue by mymeatball** [minio/minio#19010]
## NOTE
I have two MinIO clusters now.They can be called cluster A and cluster B.Cluster A in AWS Cloud ,and Cluster B in Azure Cloud.The two clouds are connected through a dedicated network line, so the bandwidth is limited.
I have set up bucket replication to copy the objects from the bucket named public in cluster A to the bucket named public in cluster B.
When the file size is not greater than 10GB, bucket copying works normally.But I observed that when the files were larger than 10GB, cluster B still did not see successfully replicated files after a long period of time.

By viewing the console logs of cluster A, it was found that errors occur every time 10GB of file replication occurs.Error message as follow:
```
API: SYSTEM
Time: 02:18:23 UTC 02/08/2024
DeploymentID: 5eaafca1-098e-4568-90f5-bd99e2aef4ef
Error: unable to replicate for object public/bmp.zip(68a95866-487b-44d2-aec1-ea0669a981f2): Put "https://minio-api.example.cn/public/bmp.zip?versionId=68a95866-487b-44d2-aec1-ea0669a981f2": write tcp 10.111.1.1:43602->10.222.2.2:443: use of closed network connection (*errors.errorString)

Backtrace: 
0: internal/logger/logger.go:258:logger.LogIf()
1: cmd/bucket-replication.go:1516:cmd.ReplicateObjectInfo.replicateAll()
2: cmd/bucket-replication.go:1047:cmd.replicateObject.func2()
```

By checking the logs of the load balancer in front of the MinIO cluster, it was found that for files larger than 10GB, an error occurred every time a replication request was made, with a status code of 400 returned.

## Expected Behavior
Need to replication files larger than 10GB successfully.
And, what is the logic behind Bucket replication? Why do errors occur every 10 minutes when copying large files. Then, in the next cycle, the transmission will start again and continue to loop.

## Current Behavior
Bucket replication files larger than 10GB will fail every time.
From the logs of the load balancer, it can be seen that each request will fail after 600 seconds, which looks like it will fail if the large file is not completed within 600 seconds.

## Possible Solution
We need to modify the 600 seconds limited of configuration.
I found a possible solution in issue 16714.https://github.com/minio/minio/issues/16714#issuecomment-1459575780
I tried setting env var MINIO_CONN_READ_DEADLINE and MINIO_CONN_WRITE_DEADLINE, but it didn't seem to solve the problem.
The steps I tried are as follows:
1.Setting env var MINIO_CONN_READ_DEADLINE and MINIO_CONN_WRITE_DEADLINE in the file which /etc/profile.Like this:
export MINIO_CONN_READ_DEADLINE=3600
export MINIO_CONN_WRITE_DEADLINE=3600
2.Execute Command：source /etc/profile
3.Execute Command：systemctl restart minio（All 4 nodes in the cluster perform this operation）

I tried to write env var in /etc/default/minio.I tried to use "60 * time.Minute" to be the value of env var too.But still unsuccessful.
Is there a problem with my steps in setting environment variables? Or is this method useless?

## Steps to Reproduce (for bugs)

1.Set up bucket replication between two MinIO site.
2.Replicating large files with limited network bandwidth
Due to my two clusters being on two different clouds and connected by dedicated network lines, so limited network bandwidth cannot be avoided

## Context

I want to set up Bucket Replication between two MinIO clusters, and the two MinIO clusters on AWS Cloud adn Azure Cloud.

## Your Environment

* Version used (`minio --version`):minio-20231111081441.0.0.x86_64.rpm
* Server setup and configuration:CentOS Linux release 7.6.1810 (Core),have 4 nodes in one cluster and 4 disks on each node.Two clusters have the same configuration.
* Operating System and version (`uname -a`):Linux cnsouth.prod.softwareDownload.mid.minio.comm.04 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
These are typical errors with network, please upgrade your setup.

**Comment by mymeatball** [comment]
What aspect of the upgrade do you mean by "please upgrade your setup."?

Are you talking about bandwidth? I cannot infinitely increase the bandwidth of my network dedicated line. If the problem still exists when encountering larger files, like 1TB file.How should we solve it?

Also, could you please explain to me the reason why I saw the problem occurring within 600 seconds? I can only guess that it is related to the environmental variables MINIO_CONN_READ_DEADLINE and MINIO_CONN_WRITE_DEADLINE seen by another issuse, but I cannot be certain.

**Comment by mymeatball** [comment]
I am looking for a way to increase the 600 second limit, but it seems to be related to the internal logic of the MinIO Server. But as guessed, if 600 seconds is a hard limit. I will encounter the problem again when the file reaches a sufficient size. And it cannot be resolved.

**Comment by jiuker** [comment]
Upgrade minio version.

**Comment by harshavardhana** [comment]
> Are you talking about bandwidth? I cannot infinitely increase the bandwidth of my network dedicated line. If the problem still exists when encountering larger files, like 1TB file.How should we solve it?
> 
> Also, could you please explain to me the reason why I saw the problem occurring within 600 seconds? I can only guess that it is related to the environmental variables MINIO_CONN_READ_DEADLINE and MINIO_CONN_WRITE_DEADLINE seen by another issuse, but I cannot be certain.

what is your bandwidth between source to target ?

**Comment by manju-rn** [comment]
@mymeatball  I had similar issue, however, in my case, it was the memory request and limits at the target that was causing the pods to restart / not respond and hence that 404 error (this is sometimes strange because when it stops responding, it should be a 502 error - somehow minio was not capturing this and just timing out giving 404).

Anyway, I see pattern here, I see minio team have closed your issue without waiting for your details.  Do provide more details, it would help me and I could recreate any network bandwith - I had setup my bandwith to as low as 1mpbs and it did not have an issue even with 15GiB file

**Comment by mymeatball** [comment]
> > Are you talking about bandwidth? I cannot infinitely increase the bandwidth of my network dedicated line. If the problem still exists when encountering larger files, like 1TB file.How should we solve it?
> > Also, could you please explain to me the reason why I saw the problem occurring within 600 seconds? I can only guess that it is related to the environmental variables MINIO_CONN_READ_DEADLINE and MINIO_CONN_WRITE_DEADLINE seen by another issuse, but I cannot be certain.
> 
> what is your bandwidth between source to target ?

About 150Mbps, maximum 300Mbps.

**Comment by mymeatball** [comment]
> Upgrade minio version.

I have been upgraded my cluster to newest version.Version: 2024-02-06T21:36:22Z
But, I see the same error meassge again.Upgraded cluster version cannt solve this problem.Is there anything else I need to configure?

**Comment by mymeatball** [comment]
> @mymeatball I had similar issue, however, in my case, it was the memory request and limits at the target that was causing the pods to restart / not respond and hence that 404 error (this is sometimes strange because when it stops responding, it should be a 502 error - somehow minio was not capturing this and just timing out giving 404).
> 
> Anyway, I see pattern here, I see minio team have closed your issue without waiting for your details. Do provide more details, it would help me and I could recreate any network bandwith - I had setup my bandwith to as low as 1mpbs and it did not have an issue even with 15GiB file

Does your problem also occur during Bucket Replication?
My network bandwith is 150Mbps now. But, i still see the error when the file larger than about 10GB.
My MinIO Cluster have 4 node, 4 CPUs and 8GB memery each node, 4 disks size of 200GB on each node.

**Comment by mymeatball** [comment]
> @mymeatball I had similar issue, however, in my case, it was the memory request and limits at the target that was causing the pods to restart / not respond and hence that 404 error (this is sometimes strange because when it stops responding, it should be a 502 error - somehow minio was not capturing this and just timing out giving 404).
> 
> Anyway, I see pattern here, I see minio team have closed your issue without waiting for your details. Do provide more details, it would help me and I could recreate any network bandwith - I had setup my bandwith to as low as 1mpbs and it did not have an issue even with 15GiB file

The current state of node memery for a node in my MinIO Cluster:
```
[root@host ~]# free -hm
              total        used        free      shared  buff/cache   available
Mem:           7.6G        1.2G        853M        1.1M        5.6G        4.9G
Swap:            0B          0B          0B
```

**Comment by mymeatball** [comment]
I found an interesting question.
The replication file in Error Message, They requests like this:
```
PUT /public/bmp.zip?versionId=59e6715a-2b7f-4898-a6af-3e9e6435b56e HTTP/1.1 
```

After upgrade cluster version today, I was uploaded a large file again, about 20GB. Through looking for load balance logs, Replicate the new upload file is normally,The requests lke this:
```
PUT /public/test.zip?partNumber=916&uploadId=ZjgzNjIzY2ItZTA4Mi00YjYxLThkODQtMmEzMTJiZTE4YjkxLmRjNGM4OTNlLTUxYjEtNGEzNi05YjcyLTQ5MDlmYWIzZWQ4YQ HTTP/1.1
PUT /public/test.zip?partNumber=915&uploadId=ZjgzNjIzY2ItZTA4Mi00YjYxLThkODQtMmEzMTJiZTE4YjkxLmRjNGM4OTNlLTUxYjEtNGEzNi05YjcyLTQ5MDlmYWIzZWQ4YQ HTTP/1.1
```
It look like uploading in parts. And, status code 200 returned of these reuqests.

I need to keep watching.I need to confirm whether there is still a problem with the existing large file and whether there is no problem with the newly uploaded large file.
Can you tell me why two different files are replicated in different ways using Bucket Replication? The non-part upload method seems to have a 600 second limit.

**Comment by manju-rn** [comment]
> Does your problem also occur during Bucket Replication?

Yes

> The current state of node memery for a node in my MinIO Cluster:

Ah okay - I was talking about the k8s node where the minio running where there was a limit set which was causing the issue. Changing the requests and limit (manually and not via minio operator / tenant UI) seemed to have solved this issue. The problem is that the error messages at source side is very limited and does not help in debugging

> Can you tell me why two different files are replicated in different ways using Bucket Replication? The non-part upload method seems to have a 600 second limit.

No idea. You might want to open a new issue and check, since thread being closed, looks like there is nobody from minio checking on this

**Comment by harshavardhana** [comment]
Locking the conversation here to avoid more bike shedding on this topic.

The error is due to network because your WAN link basically gives up and doesn't provide any data transfer for up-to 600 seconds. Quite simply if you don't use multipart upload you end up saturating your network.

For that we cannot fix your network.
