### ISSUE TITLE
FTP/SFTP OIDC authentication

### ISSUE THREAD

**Issue by cedvict** [minio/minio#19013]
## Expected Behavior

Connect to minio with sftp and OIDC authentication.
I deployed minio, configured OIDC Keycloak and defined a policy for bucket access. All this works from the browser

## Current Behavior

Connection fails with permission denied
When I run sftp with a minio idp user, it works fine. But when I do it with an OIDC user it fails

## Possible Solution

No Idea

## Steps to Reproduce (for bugs)

Trying 127.0.0.1:9021 ...
Connected to localhost.
220 Welcome to MinIO FTP Server Version='2023-11-20T22:40:07Z' License='GNU AGPLv3'
Name (localhost:root): cedvict@gmail.com
331 User name ok, password required
Password:
530 Incorrect password, not logged in
ftp: Login failed

sftp -P 9022 cedvict@gmail.com@localhost -v
cedvict@gmail.com@localhost's password:
Permission denied, please try again.

## Your Environment

* Version used (`minio --version`): RELEASE.2023-11-20T22-40-07Z
* Server setup and configuration: Cluster of 4 nodes
* Operating System and version (`uname -a`): Ubuntu 22.04

**Comment by bpedersen2** [comment]
check https://min.io/docs/minio/linux/developers/file-transfer-protocol.html, you can only log in with OIDC service account credentials, not with OIDC directly

**Comment by harshavardhana** [comment]
Both are from different times and different worlds. Only way to bridge them is via service accounts/ access keys do that.
