### ISSUE TITLE
Don't set default Content-Type

### ISSUE THREAD

**Issue by diresi** [minio/minio#1902]
## Expected behaviour

GetObjectHandler should respond with a best-guess Content-Type not depending on the extension.
## Actual behaviour

Files without extension are reported as `application/octet-stream`.
## Steps to reproduce the behaviour

Upload a .png, create a presigned get url and check the Content-Type with curl:

```
$ file test.png 
test.png: PNG image data, 264 x 384, 8-bit/color RGBA, interlaced
$ mc cp test.png ${host}/test/png_without_extension
$ mc share download ${host}/test/png_without_extension
.... copy URL from snippet ....
$ curl -v ${DOWNLOAD_URL} > /dev/null
....
 < Content-Type: application/octet-stream
....
```
## Minio version

git afc310248895
## System information

ubuntu 14.04

I'm aware that the XL Backend can store a predefined Content-Type and also responds it, which is a good thing. What I don't like is that both the fs and the XL backend default to `application/octet-stream`. Just leaving the Content-Type out in `setObjectHeaders` magically fixes this and fills in the correct content type.

Note that this only affects the `api` but not the `web` interface, as it seems that the `web` interface ignores the Content-Type from `GetObjectInfo` and thus triggers the mentioned magic.

**Comment by harshavardhana** [comment]
Fixed by #1918

**Comment by diresi** [comment]
@harshavardhana thanks for quick fix!

**Comment by harshavardhana** [comment]
> @harshavardhana thanks for quick fix!

@diresi Thanks for reporting!
