### ISSUE TITLE
minio_node_drive_free_bytes is missing on releases newer than `RELEASE.2024-01-18T22-51-28Z`

### ISSUE THREAD

**Issue by SvenMark** [minio/minio#19046]
## Expected Behavior

I expect minio to provide a `minio_node_drive_free_bytes` metric on https://HOSTNAME:PORT/minio/v2/metrics/cluster according to the docs.

## Current Behavior
The last version in which the metric was available is `RELEASE.2024-01-18T22-51-28Z`
In newer versions, `RELEASE.2024-01-28T22-35-53Z` and later the metric is not available

## Steps to Reproduce (for bugs)

Run a minio version newer than `RELEASE.2024-01-18T22-51-28Z`

## Context
I want to use the `minio_node_drive_free_bytes` metric to check if there are any drives getting below a certain threshold of free space.

## Regression
The last working version is `RELEASE.2024-01-18T22-51-28Z`

## Your Environment
I am running minio on an OpenShift cluster with version `RELEASE.2024-02-12T21-02-27Z`

**Comment by harshavardhana** [comment]
Have you verified this with 

> https://HOSTNAME:PORT/minio/v2/metrics/node

?

**Comment by harshavardhana** [comment]
Yeah, this is expected. We deprecate the drive-specific metrics on the cluster endpoint instead; this has moved to solely be at the node-specific endpoint.

You should also change your dashboard to not look for this value. https://github.com/minio/minio/blob/master/docs/metrics/prometheus/grafana/minio-dashboard.json

Per node level drive space monitoring you should start using per node scrapers - or use node exporter.
