### ISSUE TITLE
Updating access keys returns Access Denied with non admin users

### ISSUE THREAD

**Issue by MeijerinkB** [minio/minio#19047]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Updating an access key as a normal user should update the key.

## Current Behavior
As a normal user editing an access key belonging to that user results in a 'Access Denied' message in the minio console or using minio cli. This works fine when using the root account to make the same edit. Creating or deleting an access key functions as expected.

We started noticing this from RELEASE.2024-01-31T20-20-33Z onward, so I suspect this has to do with the security fix in that release. Downgrading to RELEASE.2024-01-29T03-56-32Z restores the ability for normal users to edit their access keys.

We tested this in a test deployment and all version after RELEASE.2024-01-29T03-56-32Z up to and including the latest release (RELEASE.2024-02-12T21-02-27Z at the moment) have this behavior.

## Steps to Reproduce (for bugs)
1. Upgrade to, or start a new server on any release RELEASE.2024-01-31T20-20-33Z or newer
2. Try to edit a access key as a non admin user.
3. Edit fails with 'Access Denied.'

## Regression

Regression, this works up to and including RELEASE.2024-01-29T03-56-32Z

## Your Environment
Minio 2024-02-04T22:36:13Z on production server, 2024-02-12T21-02-27Z on testing system.

**Comment by harshavardhana** [comment]
Please upgrade to latest release this is already fixed.

**Comment by MeijerinkB** [comment]
Hi, sorry to reopen this but we are still seeing this behavior on 2024-02-12T21-02-27Z. Is there some manual action required from us to fix this?

**Comment by harshavardhana** [comment]
> Hi, sorry to reopen this but we are still seeing this behavior on 2024-02-12T21-02-27Z. Is there some manual action required from us to fix this?

Yes this is expected for now check the CVE on why it was done this way. 

As a normal user you are not allowed for now to update the service account/ access key.

@donatello ^^ is this correct statement?

**Comment by harshavardhana** [comment]
We won't be reverting back here until we fix this differently to avoid any privilege escalation.

For now simply create a new key with updated policies if any.

**Comment by MeijerinkB** [comment]
O I see. I misinterpreted one of the later changes regarding the root user's access to the access keys as having fixed this, but it does not state that. I'm sorry to have bothered you with this.
