### ISSUE TITLE
Error occurred uploading 'filename.jpg'.

### ISSUE THREAD

**Issue by arjitc** [minio/minio#1905]
## Expected behaviour

The file should upload
## Actual behaviour

Starts upload and then immediately, Error occurred uploading 'filename.jpg'.
## Steps to reproduce the behaviour

./minio server /home/arjit/Photos
Login to Minio Browser
Upload file
## Minio version

```
Version: 2016-06-03T19:32:05Z
Release-Tag: RELEASE.2016-06-03T19-32-05Z
Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074

```
## System information

```
arjit@personal:~$ uname -r
3.16.0-4-amd64
arjit@personal:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G  1.9G   17G  10% /
udev             10M     0   10M   0% /dev
tmpfs            99M   13M   87M  13% /run
tmpfs           248M     0  248M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           248M     0  248M   0% /sys/fs/cgroup
```

**Comment by koolhead17** [comment]
Thanks @arjitc for reporting this.
 I am assuming you are running it on local machine so internet connection will not be an issue here, additionally will need few more some more information,.
1. Size of filename.jpg
2. Linux Distribution

This will help me to reproduce the issue on my end.

**Comment by krishnasrinivas** [comment]
@arjitc also what is the name of the bucket you are uploading the file to?

**Comment by arjitc** [comment]
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.3 (jessie)
Release:        8.3
Codename:       jessie
```

File is around ~2 MB in size.

Weirdly, when I try to create a bucket now, I get a Invalid Bucket Name error,
"Bucket name invalid: Photos"

**Comment by arjitc** [comment]
Hmm, I had a look at http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html again and tried with lowercase "photos" and it works fine now. 

I should've read better initially, my apologies.

**Comment by krishnasrinivas** [comment]
:+1:

**Comment by arjitc** [comment]
Just a suggestion -- can a strtolower() or similar be added to the bucket name input automatically incase someone happens to do this in the future? @krishnasrinivas

**Comment by krishnasrinivas** [comment]
Actually, we will throw a better error message saying 'capital letters not allowed'
