### ISSUE TITLE
getPresignedUrl from @aws-sdk/s3-request-presigner fails with SignatureDoesNotMatch

### ISSUE THREAD

**Issue by quick691fr** [minio/minio#19067]
## Expected Behavior
Presigned URL generated with [@aws-sdk](https://github.com/aws/aws-sdk-js) library should be valid

## Current Behavior
Minio server returns :

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>test.png</Key>
<BucketName>test-seb</BucketName>
<Resource>/test-seb/test.png</Resource>
<Region>us-east-1</Region>
<RequestId>17B46A55B658DD6E</RequestId>
<HostId>3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac</HostId>
</Error>
```

## Steps to Reproduce (for bugs)
I created a online javascript code to show the problem, the presignedUrl is displayes either on page or console, this is using the public play.min.io server on HTTP :

https://codepen.io/quick691fr/pen/dyrajXN

## Context
I can successfully upload file but can't create a presigned link to display image in my app

## Regression
Dunno, I saw some old threads about port not being took into account in asw-sdk library but seems fixed on aws side

## Your Environment
Server is the current online public play.min.io server on port 9000 http

**Comment by harshavardhana** [comment]
It works fine; you are using the wrong credentials.

```js
import { S3Client, PutObjectCommand } from "https://esm.sh/@aws-sdk/client-s3";
import { getSignedUrl } from "https://esm.sh/@aws-sdk/s3-request-presigner";

try {
  const s3Client = new S3Client({
    endpoint: "https://play.min.io:9000",
    region: "us-east-1",
    credentials: {
      accessKeyId: "Q3AM3UQ867SPQQA43P2F",
      secretAccessKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    },
    forcePathStyle: true
  });
  const putCommand = new PutObjectCommand({
    Bucket: "test-seb",
    Key: "test.png"
  });
  getSignedUrl(s3Client, putCommand, { expiresIn: 3600 })
    .then((url) => {
      console.log("presigned URL :", url);
      document.write("presigned URL :", url);
    })
    .catch((err) => {
      console.log(err);
      return Promise.reject(err);
    });
} catch (err) {
  console.log(err);
}
```

```
~ curl -I --upload /etc/hosts "https://play.min.io:9000/test-seb/test.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20240216%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240216T184611Z&X-Amz-Expires=3600&X-Amz-Signature=ce0ce0e1580a53033ee61267e9254b3b12bdf416e50a539b16f6d24873ab3612&X-Amz-SignedHeaders=host&x-id=PutObject"
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
ETag: "9fe7a344ef4227d3e53751e9d88ce41e"
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac
X-Amz-Request-Id: 17B46C571A84D0F1
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Fri, 16 Feb 2024 18:48:00 GMT
```

**Comment by quick691fr** [comment]
I didn't say it's not working in HTTPS, you changed the endpoint

**Comment by quick691fr** [comment]
> I didn't say it's not working in HTTPS, you changed the endpoint

On my dev side I only have a docker install of minio which is not working in HTTPS

I can't find your credentials 
![image](https://github.com/minio/minio/assets/375807/5f8fcf76-f2eb-4fb9-893a-352ce1351862)

Where mine are found on server :
![image](https://github.com/minio/minio/assets/375807/d563b90c-7d1e-49cc-a746-2d7e1c9e7829)

**Comment by quick691fr** [comment]
Just testing with your credentials and HTTPS and still not working :
![image](https://github.com/minio/minio/assets/375807/65671953-4009-40dd-bd3b-d6c6bf6cee09)

![image](https://github.com/minio/minio/assets/375807/629d6c7c-3e6c-4235-a51c-61204f8e1bab)

**Comment by harshavardhana** [comment]
> Just testing with your credentials and HTTPS and still not working : ![image](https://private-user-images.githubusercontent.com/375807/305578987-65671953-4009-40dd-bd3b-d6c6bf6cee09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMzI1MTIsIm5iZiI6MTcwODEzMjIxMiwicGF0aCI6Ii8zNzU4MDcvMzA1NTc4OTg3LTY1NjcxOTUzLTQwMDktNDBkZC1iZDNiLWQ2YzZiZjZjZWUwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwMTEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTk4OGUxODgyNmRhZjY2ZDExN2ZhZjg0YTg2ZTU1NGVlY2RhMzA2MzAwNWJiMGY5YjhhYjliZDAzYmQxNjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CWvpYA71co5TuHfZ6n7C-z_W19HKKYHknUSvSmkJA_k)
> 
> ![image](https://private-user-images.githubusercontent.com/375807/305579019-629d6c7c-3e6c-4235-a51c-61204f8e1bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMzI1MTIsIm5iZiI6MTcwODEzMjIxMiwicGF0aCI6Ii8zNzU4MDcvMzA1NTc5MDE5LTYyOWQ2YzdjLTNlNmMtNDIzNS1hNTFjLTYxMjA0ZjhlMWJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwMTEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTM5ZTBhNjYwMzUwZTU1MzU2ZGQzOWJlZGE4MGIwMjkxMTFiMDUwNTAyYzI0YzNiMTE1YWI0NGZkMGRiZTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aiIGAv3UP917XhuXa59ZSjfcBB2KpJp6213P-Yw7F04)

you do not just post the URL into browser that's just naive thing to do. You need to use this URL to upload `curl --upload <filename>`
