### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by polykit** [minio/minio#19079]
After upgrading to `RELEASE.2024-02-09T21-25-16Z` and onward the server is increasingly consuming memory. It looks like a memory leak to me. I set some resource limits to keep the node healthy.

## Expected Behavior
A more or less constant memory consumption like before the upgrade. I ran `RELEASE.2024-01-11T07-46-16Z` before the problem occurred for the first time.

## Current Behavior
Server component is constantly consuming more memory and is oomkilled eventually.

## Regression
Yes, occurred after upgrading to `RELEASE.2024-02-09T21-25-16Z`. Before that I ran `RELEASE.2024-01-11T07-46-16Z` without any issues.

## Your Environment
* Server setup and configuration: `RELEASE.2024-02-17T01-15-57Z` / k3s Kubernetes 1.28.3 / helm chart without operator
* Operating System and version (`uname -a`): `Ubuntu 22.04.3 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

Is there a way to get some profiler data from the application to debug this issue?

![Screenshot from 2024-02-19 17-57-03](https://github.com/minio/minio/assets/74774964/50ceb53a-c138-4d5f-8d1d-77aeffddb2b0)

**Comment by harshavardhana** [comment]
Please upgrade to latest release multiple memory leak issues fixed.

**Comment by polykit** [comment]
@harshavardhana I'm on latest `RELEASE.2024-02-17T01-15-57Z` and still have this issue.

**Comment by harshavardhana** [comment]
> @harshavardhana I'm on latest `RELEASE.2024-02-17T01-15-57Z` and still have this issue.

@polykit you would need to capture profile for us to investigate - also don't look at `container_set_bytes`. Look for `minio_node_process_resident_memory_bytes` what is the overall used. 

If that says < your container_bytes then the reporting in container_bytes is wrong and its computing page-cached values.

**Comment by harshavardhana** [comment]
> Is there a way to get some profiler data from the application to debug this issue?

Profiling a production system requires a subscription @polykit https://min.io/pricing. Please subscribe. We are happy to help.

**Comment by polykit** [comment]
@harshavardhana the metric `minio_node_process_resident_memory_bytes` is looking even worse. Something happened after upgrading to `RELEASE.2024-02-09T21-25-16Z`. I guess there is no way to downgrade prior that version.

![Screenshot from 2024-02-23 08-42-35](https://github.com/minio/minio/assets/74774964/4281bb60-6582-44dd-b591-12aa372b11e1)

> Profiling a production system requires a subscription @polykit https://min.io/pricing. Please subscribe. We are happy to help.

Thanks for the offer but I don't have that kind of money. I can barely cover operational costs.

**Comment by harshavardhana** [comment]
Please upgrade to newer release there are actually more improvements.

**Comment by polykit** [comment]
I upgraded to `RELEASE.2024-02-24T17-11-14Z` and it's still the same pattern.

**Comment by harshavardhana** [comment]
> I upgraded to `RELEASE.2024-02-24T17-11-14Z` and it's still the same pattern.

Please capture a memory profile and share it with us.

**Comment by douglasawh** [comment]
@harshavardhana we are seeing this issue too. Can you please mark this as open?

**Comment by qume** [comment]
FWIW I have 10 minio nodes, and they all sit around 2-3GB RAM usage. Two nodes will keep climbing in RAM usage until they stop serving requests (just get SlowDownRead responses). 

What is interesting is these are identical LXC containers, 10 of them, connected to one disk each. But only two nodes have what seems like the memory leak.

minio version RELEASE.2024-04-06T05-26-02Z (commit-id=9d63bb1b418f6c1bbcc8434fff5d8aba810ee5d7)

**Comment by klauspost** [comment]
@qume Update. We changed the default allocation.
