### ISSUE TITLE
Minio update fails with missing OFFICIAL tag probe

### ISSUE THREAD

**Issue by markdclark** [minio/minio#1907]
## Expected behaviour

update minio server
## Actual behaviour

fails
## Steps to reproduce the behaviour; list version; execute update

MacBook-Pro-2:~ markclark$ minio version
Version: 2016-02-08T00:13:11Z
Release-Tag: OFFICIAL.2016-02-08T00-13-11Z
Commit-ID: e79a73a3f5fa9b0111ecf2620be84ff5f3e9698a
MacBook-Pro-2:~ markclark$ minio update

FATA[0000] Please report this issue at https://github.com/minio/minio/issues.  error=Update data malformed, missing OFFICIAL tag probe={"cause":{},"trace":[{"line":125,"file":"update-main.go","func":"main.parseReleaseData"},{"line":165,"file":"update-main.go","func":"main.getReleaseUpdate","env":{"Tags":["https://dl.minio.io/server/minio/release/"]}}],"sysinfo":{"host.arch":"amd64","host.cpus":"4","host.lang":"go1.5.3","host.name":"MacBook-Pro-2","host.os":"darwin","mem.heap.total":"5.8MB","mem.heap.used":"1.7MB","mem.total":"8.8MB","mem.used":"1.7MB"}}

**Comment by krishnasrinivas** [comment]
@markdclark 
previously we used to name the builds as minio.OFFICIAL.2016-06-03T19-32-05Z now we name it as minio.RELEASE.2016-06-03T19-32-05Z which broke the `minio update` command.

To update you will have to manually download minio from here https://minio.io/downloads/

Here onwards `minio update` command should not break.
