### ISSUE TITLE
使用【mc admin decommission】迁移数据后，object tag丢失

### ISSUE THREAD

**Issue by q102137601** [minio/minio#19077]
## 现象说明
* 我在使用mc admin decommission 对minio中的数据迁移至另一个容量更大的集群，迁移前所有的object都是设置过tag信息的，数据迁移至新集群后，我重新使用mc tag list 发现所有tag都消失了
![image](https://github.com/minio/minio/assets/43600528/7e872c65-166c-43e1-8363-cd2bac204579)

## 环境信息
* Version used (`minio --version`):
![image](https://github.com/minio/minio/assets/43600528/a4b0cafa-7643-478b-bb22-33b6d9409438)
* Operating System and version (`uname -a`):
![image](https://github.com/minio/minio/assets/43600528/25498852-0d5a-4694-8c12-470b7587f6b3)
* linux version
![image](https://github.com/minio/minio/assets/43600528/40cdb083-accf-488b-9196-7671f42acc17)

**Comment by jiuker** [comment]
1. Use English first
2. Upgrade your minio version

**Comment by q102137601** [comment]
thank ~
Which specific version can solve the problem of tag loss

**Comment by jiuker** [comment]
> thank ~ Which specific version can solve the problem of tag loss

We just support latest version for community. You can upgrade to latest and to see if the bug also appear. @q102137601

**Comment by q102137601** [comment]
Okay, thank you very much
