### ISSUE TITLE
Need to support multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication.

### ISSUE THREAD

**Issue by mymeatball** [minio/minio#19083]
**Is your feature request related to a problem? Please describe.**
I use multipart upload (mc cp , or , PutObject function from go-SDK) to upload Object A into Bucket A in site A. And I need to copy this Object A into Bucket B in Site A. So, I use CopyObject function from go-SDK to do this.
I have setting Bucket Replication to the both Bucket, And the both Bucket will replicate object to same name Bucket in Site B.

I'm viewing that the objects in Bucket A when process Bucket Replication, Objects can replicate to the same name Bucket in Site B from multipart upload. Like this:
```
PUT /BucketA/public/file.zip?partNumber=1&uploadId=XXXYYYZZZ HTTP/1.1
PUT /BucketA/public/file.zip?partNumber=2&uploadId=XXXYYYZZZ HTTP/1.1
PUT /BucketA/public/file.zip?partNumber=3&uploadId=XXXYYYZZZ HTTP/1.1
...
```

But, some objects can't replicate to the same name Bucket in Site B from multipart upload when these in Bucket A. They just in a single PUT operation. This will cause problem that replicate large files to encounter a 600 second timeout limit. Like this:
```
PUT /BucketB/public/file.zip?versionId=e1aadcf2-2ee3-4284-a77a-e255eb4acd24 HTTP/1.1
```

So,I want to multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication. 
I couldn't find any potentially useful parameters in CopyObject function for multipart upload. Can you help me?

**Describe the solution you'd like**
Support multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication.

**Describe alternatives you've considered**
Use ComposeObject function from go-SDK.
I tried to use ComposeObject function to replace CopyObject, Its can work. But this function not looks like use for copy object.

**Additional context**
Always report ERROR "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed." when i tried to use ComposeObject function replace CopyObject. This is not important.

**Comment by harshavardhana** [comment]
Please open issues with clean concise description of what is being done

- share the code
- share your setup details, including minio version
- share what is the intent behind the code and what is the eventual goal

none of these are evident in this issue, this issue is extremely vague.
