### ISSUE TITLE
Need to support multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication.

### ISSUE THREAD

**Issue by mymeatball** [minio/minio#19085]
## NOTE
I use multipart upload (mc cp , or , PutObject function from go-SDK) to upload Object A into Bucket A in site A. And I need to copy this Object A into Bucket B in Site A. So, I use CopyObject function from go-SDK to do this.
I have setting Bucket Replication to the both Bucket, And the both Bucket will replicate object to same name Bucket in Site B.

I'm viewing that the objects in Bucket A when process Bucket Replication, Objects can replicate to the same name Bucket in Site B from multipart upload. Like this:
```
PUT /BucketA/public/file.zip?partNumber=1&uploadId=XXXYYYZZZ HTTP/1.1
PUT /BucketA/public/file.zip?partNumber=2&uploadId=XXXYYYZZZ HTTP/1.1
PUT /BucketA/public/file.zip?partNumber=3&uploadId=XXXYYYZZZ HTTP/1.1
...
```

But, some objects can't replicate to the same name Bucket in Site B from multipart upload when these in Bucket A. They just in a single PUT operation. This will cause problem that replicate large files to encounter a 600 second timeout limit. Like this:
```
PUT /BucketB/public/file.zip?versionId=e1aadcf2-2ee3-4284-a77a-e255eb4acd24 HTTP/1.1
```

So,I want to multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication. 
I couldn't find any potentially useful parameters in CopyObject function for multipart upload. 

## Expected Behavior

Need to support multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication.

## Current Behavior

Need to support multipart upload objects after use CopyObject function from go-SDK when process Bucket Replication.

## Possible Solution

Replicating objects in a single PUT operation after use CopyObject function from go-SDK when process Bucket Replication.

## Steps to Reproduce (for bugs)

1.Use "mc cp" or "PutObject funtion from go-SDK" upload Object A into Bucket A in Site A.
2.Use "CopyObject funtion from go-SDK" copy Object A into Bucket B in Site A.

Control Group A:
3.Setting "Bucket Replication" from Bucket A in Site A to Bucket A in Site B.
4.Viewing the process when Bucket Replication.

Control Group B:
5.Setting "Bucket Replication" from Bucket B in Site A to Bucket B in Site B.
6.Viewing the process when Bucket Replication.

You can see that:
1.The process is "multipart upload" in Bucket A when Bucket Replication. 
2.The process is "in a single PUT operation" in Bucket B when Bucket Replication. 

## Context

If not use "multipart upload object", I will cause problem that replicate large files to encounter a 600 second timeout limit. 
But, If use "multipart upload object",the timeout is 1 hour. So, I need to use "multipart upload object".

Here is an example of how I used CopyObject:
```
	srcOpts := minio.CopySrcOptions{
		Bucket: srcBucketName,
		Object: srcObject,
	}

	dstOpts := minio.CopyDestOptions{
		Bucket: dstBucketName,
		Object: dstObject,
	}
	client, err := MinioClient()
	if err != nil {
		return err
	}

	uploadInfo, err := client.CopyObject(context.Background(), dstOpts, srcOpts)
	if err != nil {
		return err
	}
	log.Println("Successfully copied object:", uploadInfo.Bucket+"/"+uploadInfo.Key)

	return nil
```

## Your Environment

* Version used (`minio --version`): 2024-02-06T21:36:22Z
* Server setup and configuration: CentOS Linux release 7.6.1810 (Core),have 4 nodes in one cluster and 4 disks on each node.Two clusters have the same configuration.
* Operating System and version (`uname -a`): Linux cnsouth.prod.softwareDownload.mid.minio.comm.04 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by poornas** [comment]
server side CopyObject does not need to preserve the multipart object as is - minio server copies it as a single part object. Even with AWS, you will need to copy object using multipart copy - [example](https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html)

Instead of minio-go's CopyObject API, use the ListObjectParts and CopyObjectPart calls exposed in the [core API](https://github.com/minio/minio-go/blob/master/core.go) in the context of a multipart upload similar to the example above.

Is there a purpose in copying same content to different buckets and then replicating this?

**Comment by mymeatball** [comment]
> server side CopyObject does not need to preserve the multipart object as is - minio server copies it as a single part object. Even with AWS, you will need to copy object using multipart copy - [example](https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html)
> 
> Instead of minio-go's CopyObject API, use the ListObjectParts and CopyObjectPart calls exposed in the [core API](https://github.com/minio/minio-go/blob/master/core.go) in the context of a multipart upload similar to the example above.
> 
> Is there a purpose in copying same content to different buckets and then replicating this?

Yes, actually the Bucket A is a temporary Bucket, and Bucket B is a production env Bucket.
I need upload objects into Bucket A (temporary Bucket), and copy objects into Bucket B (production env Bucket) after perform a series of security scans on objects.

**Comment by mymeatball** [comment]
Thank you . I will refer to the core API now.
