### ISSUE TITLE
Minio http://domain.name not works for Multi-Drive Multi-node

### ISSUE THREAD

**Issue by kramchas** [minio/minio#19084]
I got error when i Try configure minio for works like Multi-drive and multi-node
my config file:
/etc/hosts
192.168.1.2 node1
192.168.1.3 node2
192.168.1.4 node3
192.168.1.5 node4

/etc/default/minio
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=miniominio
MINIIO_VOLUMES="/minio-f/"   #when i try to add http://node{1...4}/minio-f   my daemon can't start 
MINIO_OPTS="-C /etc/minio --address :9000 --console-address :9001"

Rhel 8
firewall and selinux disabled
minio-user:minio-user chowned
in all instances have directory /minio-f/
i can ping node1 node2 node3 node4 via hostname
have telnet on port 9000
have tcptraceroute node1 9000

**Comment by harshavardhana** [comment]
> MINIIO_VOLUMES="/minio-f/" #when i try to add [http://node{1...4}/minio-f](http://node%7B1...4%7D/minio-f) my daemon can't start

You can't change /minio-f -> multi-node - first you need to cleanup your data at /minio-f

**Comment by kramchas** [comment]
Hello, i did it and what i need to do next step?

**Comment by kramchas** [comment]
Now i got error:
Waiting for at least 1 remote server with valid configuration to be online
Following servers are currently offline or unreachable [http://node1:9000->http://node4:9000 is unreachable: remote disconnect
403 error

**Comment by harshavardhana** [comment]
> Now i got error:
> Waiting for at least 1 remote server with valid configuration to be online
> Following servers are currently offline or unreachable [http://node1:9000->http://node4:9000 is unreachable: remote disconnect
> 403 error

Yeah make them reachable, make sure credentials are same - make sure DNS is correct.

**Comment by kramchas** [comment]
DNS and credentials are same
DNS1=192.168.1.1
user and group are minio-user:minio-user in all istances

**Comment by kramchas** [comment]
full log error
![Снимок экрана 2024-02-20 150354](https://github.com/minio/minio/assets/148309514/a1ff174d-5f9e-4269-b83e-99f339ea1f2e)

**Comment by ravindk89** [comment]
The displayed error is telling you what you need to diagnose - the node is unreachable. Something on your DNS setup is not working as you expect it to. If MinIO cannot resolve a hostname, it cannot function - that's not something we can fix.

As an aside, please do not at-mention team members to 'bump' an issue. All support here is best-effort only.
