### ISSUE TITLE
"fatal error: concurrent map writes" after upgrade from RELEASE.2023-10-24T04-42-36Z to RELEASE.2024-02-06T21-36-22Z

### ISSUE THREAD

**Issue by crazyeyes2023** [minio/minio#19081]
## NOTE
Running the minio cluster in kubernetes cluster with operator version 5.0.11. After upgrading minio image from RELEASE.2023-10-24T04-42-36Z to RELEASE.2024-02-06T21-36-22Z, all minio pods crash with error "fatal error: concurrent map writes".

Cluster is containing 10 nodes with Ec:3 parity scheme for the nvme disk pools, around 700TB usable capacity. 

We tested some other smaller clusters with this binary upgrade, all works. 

## Expected Behavior
Upgrade went smoothly, without crashloop.

## Current Behavior
All Minio pods start running for a few mins while waiting for reconnecting other nodes, then it will crash and error our "fatal error: concurrent map writes"

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1.Install minio operator/tenant 5.0.11
2. overwrite minio image to RELEASE.2024-02-06T21-36-22Z in values.yaml file
3. helm upgrade the tenant

Not reproducible in the smaller minio cluster

## Context

Unable to upgrade cluster to newer version minio. 

## Regression

No

## Your Environment

* Version used (`minio --version`): MInio version RELEASE.2023-10-24T04-42-36Z prior the upgrade. Try to upgrade to RELEASE.2024-02-06T21-36-22Z. MInio operator version 5.0.10, minio Tenant version 5.0.11
* Server setup and configuration:  10 Dedicated node running kubernetes v1.24.10 containerd. Each host equiped 16x 7.3 TB NvMe drives mounted to file system with xfs. Minio tenant is configure use EC:3 storage class. 
* Operating System and version (`uname -a`): kernel 5.14.0-284.11.1.el9_2.x86_64, Rocky Linux 9.2 (Blue Onyx)

**Comment by jiuker** [comment]
Could you share the pod's yaml and pod's log @crazyeyes2023 ?

**Comment by crazyeyes2023** [comment]
Hi @jiuker , 

Please find the pod yaml output (currently we rolled back to RELEASE.2023-10-24T04-42-36Z binary) and logs (was taken during the crashed loops when the pod running RELEASE.2024-02-06T21-36-22Z)

[minio-research-ss-2-9.log](https://github.com/minio/minio/files/14338800/minio-research-ss-2-9.log)
[minio-research-ss-2-8.log](https://github.com/minio/minio/files/14338801/minio-research-ss-2-8.log)
[minio-research-ss-2-8.yaml.zip](https://github.com/minio/minio/files/14338818/minio-research-ss-2-8.yaml.zip)
[minio-research-ss-2-9.yaml.zip](https://github.com/minio/minio/files/14338819/minio-research-ss-2-9.yaml.zip)

THanks a lot for your help in advance looking into this issue. 

Best regards, 
Kyd

**Comment by harshavardhana** [comment]
Please upgrade all pods to latest release. RELEASE.2024-02-17T01-15-57Z

**Comment by harshavardhana** [comment]
> Cluster is containing 10 nodes with Ec:3 parity scheme for the nvme disk pools, around 700TB usable capacity.

Large clusters like this require a subscription. Please subscribe at https://min.io/pricing

**Comment by harshavardhana** [comment]
Also as a workaround - turn-off kafka notification and upgrade the setup. 

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 37496 [running]:
github.com/minio/minio/internal/event/target.(*KafkaTarget).pingBrokers.func1({{0xc10f29c503?, 0xc359b29fd0?}, 0x6747?, 0xfb?}, 0x9)
        github.com/minio/minio/internal/event/target/kafka.go:349 +0x1cd
created by github.com/minio/minio/internal/event/target.(*KafkaTarget).pingBrokers in goroutine 4776
        github.com/minio/minio/internal/event/target/kafka.go:341 +0xb5

```

**Comment by harshavardhana** [comment]
Also never setup such large clusters without a subscription, you are inviting yourself for outages and unhappy users. You are better of taking our help - we provide 24/7 support for this reason alone. 

Of course we can't do this for free.

**Comment by harshavardhana** [comment]
Another workaround is to configure a single broker.

**Comment by crazyeyes2023** [comment]
Thanks a lot @harshavardhana and @jiuker,

Indeed I just got the quote for support from the minio website and in talk with the team for the subscription.

Again, thanks heaps for your help and fast response for the upgrade issue this time.

**Comment by harshavardhana** [comment]
Wonderful @crazyeyes2023 looking forward.
