### ISSUE TITLE
Error: Unexpected response, download incomplete.

### ISSUE THREAD

**Issue by pschichtel** [minio/minio#19091]
## Expected Behavior

I log into the console of my single node minio server, go to an object in any bucket, click on download and get the file.

## Current Behavior

Currently for me, when I click download I get "Unexpected response, download incomplete" und the "Uploads / Downloads" widget. In the network tab the only request that I see (https://console..../api/v1/buckets/.../objects/download?...) has status 200. Nothing in the minio log. Nothing in the browser console.

Using `mcli cp` works *perfectly fine*. Accessing the objects via s3fs also yielded corrupted files. So something that happens when downloading via console and via s3fs must be broken, that isn't used when using mcli cp.

Restart of minio as well as a reboot of the machine did not help.

## Steps to Reproduce (for bugs)

I have no idea how I entered this state, but for me it is currently happening on every single file. I **might** have started when I attempted to rename a folder with files in it via S3FS, which failed, but I'm not certain that S3FS caused this issue or if this issue caused the failure with S3FS.

## Context
Just downloading files via the console.

## Regression
I don't think so.

## Your Environment

* Version used (`minio --version`):
    ```
    minio version RELEASE.2024-02-17T01-15-57Z (commit-id=b6e98aed0161bb526aaf11fa1672d30eb89dca4b)
    Runtime: go1.21.7 linux/amd64
    License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
    Copyright: 2015-2024 MinIO, Inc.
    ```
* Server setup and configuration: It's deployed in a kubernetes 1.29.1 (k0s) using the minio operator (5.0.12). It's single node (both k8s and minio) and single pool (openebs-hostpath volume on ext4).
* Operating System and version (`uname -a`): `Linux ... 6.7.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> * Server setup and configuration: It's deployed in a kubernetes 1.29.1 (k0s) using the minio operator (5.0.12). It's single node (both k8s and minio) and single pool (openebs-hostpath volume on ext4).

ext4 has recently some known bugs related to O_DIRECT I/O https://news.ycombinator.com/item?id=38589389

You look like you might be affected.

**Comment by harshavardhana** [comment]
We recommend that you use XFS instead.

**Comment by pschichtel** [comment]
@harshavardhana Would that explain that mcli is still working? also the fact that this happens on objects that haven't been touched in a while?

**Comment by pschichtel** [comment]
@harshavardhana I've migrated to XFS, but the issue persists.

**Comment by harshavardhana** [comment]
I have no idea @pschichtel - use `mcli` if it works fine.

**Comment by pschichtel** [comment]
I mean, mcli works fine, but mcli is not an option for some of my use-cases. How can I debug this further? I've noticed that larger files download up to around 90% in the UI and then abort with the said error. Is there a chance that some form of debugging logging could help? This is a personal installation of minio and I do have offsite backups of the data in it, so I'm in the position that I can easily deploy custom binaries to add more logging. But some pointer would be very helpful.

**Comment by harshavardhana** [comment]
Take some mcli admin trace and see where things are failing. Remove any layers between MinIO and browser etc.

**Comment by pschichtel** [comment]
I haven't had time to look at traces yet, but I tried uploading a document via console. That worked and I was able to download it with mcli and successfully compared hashes. Downloading the same file via browser failed though.

Then I had crazy idea of testing a different browser (normally I used firefox): chromium, there the download actually works. Neither browser prints anything in the console when dowloading and the response headers of the .../download?... request seems identical, but in chromium it returns a pdf and in firefox it returns the PDF as a base64 string.

**Comment by harshavardhana** [comment]
> Then I had crazy idea of testing a different browser (normally I used firefox): chromium, there the download actually works. Neither browser prints anything in the console when dowloading and the response headers of the .../download?... request seems identical, but in chromium it returns a pdf and in firefox it returns the PDF as a base64 string.

Yeah its not MinIO related as such. You can provide some network traces etc and open an issue at https://github.com/minio/console
