### ISSUE TITLE
Multi node deployment, data is only stored in all drivers of one node

### ISSUE THREAD

**Issue by zhl19911203** [minio/minio#19108]
## Steps to Reproduce (for bugs)

Started 4 nodes, each with 4 drivers. When uploading a file, the file only exists on all disks of one node, while the other nodes do not store it. Is there a configuration issue

docker-compose.yml content

version: "3.7"
services:
  minio:
    image: "quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z"
    network_mode: host
    volumes:
      - "./minio/data1:/data1"
      - "./minio/data2:/data2"
      - "./minio/data3:/data3"
      - "./minio/data4:/data4"
    command: server --console-address ":9001" http://**.164:9000/data{1...4} http://**.165:9000/data{1...4} http://**.166:9000/data{1...4} http:/**.167:9000/data{1...4}
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## Your Environment
version：quay.io/minio/minio:RELEASE.2024-02-04T22-36-13Z

**Comment by harshavardhana** [comment]
If you run in this manner you are creating 4 pools, you are not spreading out the object across nodes.

For that you need 

```
http://.16{4...7}:9000/data{1...4} 
```
