### ISSUE TITLE
minio fault cannot be automatically recovered

### ISSUE THREAD

**Issue by zhl19911203** [minio/minio#19105]
Minio deploys two nodes, each with 4 drivers, for a total of 8 drivers. There are several issues as follows

1. When deleting four drivers from a node, data can be downloaded through the address, but restarting the node will prevent it from starting. An error message will appear. How can data be restored? Is it automatically restored?

2. How to recover data when deleting one driver from a node, is it automatically recovered? Or manual recovery

3. Can I recover deleted folders using the mc admin heal command?

**Comment by harshavardhana** [comment]
Vague issue closing.
