### ISSUE TITLE
Minio terminates access for users

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#19102]
## NOTE
After upgrading minio to the latest version [RELEASE.2024-02-17T01-15-57Z] it stops allowing the new user connections after approx. one day of working. When user tries to login minio shows error "Invalid credentials". After restart entire cluster it becomes work normally again. Then in one day issue raises again.
Also may be it's meanful - we have 4 nodes with 4 disks on each and now one node is in shutdownstate because of maintanance.

## Regression
Is this issue a regression? Yes
This started from release RELEASE.2024-02-17T01-15-57Z. Previous release which was installed (RELEASE.2024-02-09T21-25-16Z) haven't this issue.

## Your Environment

* Version used (`minio --version`): RELEASE.2024-02-17T01-15-57Z.
* Server setup and configuration: 4 nodes with 4 disks on each.
* Operating System and version (`uname -a`): Linux minio-cold-1 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ravindk89** [comment]
@AlexZIX are you using an external identity manager, or are these MinIO-managed users?

Is it *exactly* 24 hours between the issue?

Are these normal users or service accounts?

**Comment by harshavardhana** [comment]
> Is this issue a regression? Yes
> This started from release RELEASE.2024-02-17T01-15-57Z. Previous release which was installed (RELEASE.2024-02-09T21-25-16Z) haven't this issue.

You have to provide us more details 

- like `mc admin trace -a --funcname admin* --funcname sts* --funcname s3*` output
- does `mc` work fine? 

Until then closing this issue.

**Comment by AlexZIX** [comment]
Today got this issue again and already restarted the cluster. As I understand I must run trace when this issue will occurs next time?

**Comment by harshavardhana** [comment]
> Today got this issue again and already restarted the cluster. As I understand I must run trace when this issue will occurs next time?

Correct

**Comment by AlexZIX** [comment]
> @AlexZIX are you using an external identity manager, or are these MinIO-managed users?
> 
> Is it _exactly_ 24 hours between the issue?
> 
> Are these normal users or service accounts?

@ravindk89 

1. I use minio built-in user manager.
2. No, it's approximately. I've just restarted minio every day because it stop working every day. I'll try to measure time between issues.
3. We use normal user accounts only.

**Comment by AlexZIX** [comment]
It's so strange but this bug no longer appears after upgrading to RELEASE.2024-02-26T09-33-48Z
