### ISSUE TITLE
lifecycle not work

### ISSUE THREAD

**Issue by lygn128** [minio/minio#19119]
add a bucket lifecycle for 1 day expire but not working

## Expected Behavior
after  add a  one day lifecycle on a bucket, the bucket has many objects put some days ago,   but  objects  nums  have no one decrease

## Your Environment
*  mc ilm  rule list myminio/test-lc
ID │ STATUS  │ PREFIX │ TAGS │ DAYS TO EXPIRE │ EXPIRE DELETEMARKER
cncn85qtvihrleti2m00 │ Enabled │ -      │ -    │              1 │ false
* Version used (`minio --version`):  minio version RELEASE.2024-02-04T22-36-13Z (commit-id=f225ca331203032888889c1c4a3f96ee3452b9f9)
* Server setup and configuration:
* Operating System and version (`uname -a`):   centos 8   Linux oss-111 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Expiration of 1 day, requires you to wait 48hrs.

**Comment by lygn128** [comment]
> Expiration of 1 day, requires you to wait 48hrs.

thank you very much, but the objects all are put some days ago, in this situation, i still need to wait 48 hrs?

**Comment by harshavardhana** [comment]
> thank you very much, but the objects all are put some days ago, in this situation, i still need to wait 48 hrs?

lifecycle rule only takes effect after it has been applied; it won't do retroactive ILM.
