### ISSUE TITLE
403 Forbidden Error with SignatureDoesNotMatch on Delta Files Access via Webserver

### ISSUE THREAD

**Issue by ghaffarialireza** [minio/minio#19146]
## Expected Behavior
I expect to connect to Minio to read delta files directly via a Python script without any errors, similar to how interactions with AWS S3 operate without issues.

## Current Behavior
When running a script using Python to read delta files directly, it works fine. However, executing the same operation within a web server environment (e.g., Dagster running on a port) results in a `403 Forbidden` error related to `SignatureDoesNotMatch`.

## Possible Solution
Not sure, but it might be related to how the signature is calculated or managed within a web server context as opposed to a direct script execution.

## Steps to Reproduce (for bugs)
1. Set up Minio with the necessary permissions and configurations.
2. Run a Python script to read delta files directly from Minio; observe that it works as expected.
3. Run the same operation within a web server environment like Dagster.
4. Encounter a `403 Forbidden` error with `SignatureDoesNotMatch`.

## Context
This issue prevents the successful reading of delta files from Minio when running within a web server context, impacting our data processing workflows that rely on accessing these files for further operations.

## Regression
No

## Your Environment
- Version used (minio --version): latest
- Server setup and configuration: Mounted on Docker Desktop
- Operating System and version (uname -a): Ubuntu 22.04
- Error encountered: 
  ```
  ERROR:root:Error reading existing survey IDs from delta files: Generic S3 error: Client error with status 403 Forbidden: <?xml version="1.0" encoding="UTF-8"?>
  <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>after_sale_surveys/_delta_log/_last_checkpoint</Key><BucketName>feedbackly</BucketName><Resource>/feedbackly/after_sale_surveys/_delta_log/_last_checkpoint</Resource><RequestId>17B7FB041590E0DE</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
  ```

- Code snippet causing the issue:
  ```python
  MINIO_STORAGE_OPTIONS = {
      "AWS_BUCKET_NAME": "feedbackly",
      "AWS_DEFAULT_REGION": os.getenv("MINIO_REGION"),
      "AWS_ACCESS_KEY_ID": os.getenv("MINIO_ACCESS_KEY_ID"),
      "AWS_SECRET_ACCESS_KEY": os.getenv("MINIO_SECRET_ACCESS_KEY"),
      "AWS_ENDPOINT_URL": os.getenv("MINIO_ENDPOINT_URL"),
      "AWS_ALLOW_HTTP": "true",
      "AWS_S3_ALLOW_UNSAFE_RENAME": "true",
  }

  data = pl.read_delta(
              source="s3://feedbackly/after_sale_surveys",
              storage_options=storage_options,
              )
  ```

I haven't encountered any issues with AWS S3 under similar circumstances. What could be causing this problem with Minio?

**Comment by harshavardhana** [comment]
You need to make sure proxying doesn't involve caching, if MinIO works without dagster then the problem is outside of MinIO.

**Comment by ghaffarialireza** [comment]
@harshavardhana can you elaborate and help me out a little bit, I have run all locally and I wonder why AWS S3 works without a problem in this way but mine does not! where should I head to?
