### ISSUE TITLE
File descriptors increased rapidly, from 500 to 10,000 in one second.

### ISSUE THREAD

**Issue by adababys** [minio/minio#19159]
## NOTE

when  upload a lot of files to minio，the  minio FD  increased rapidly, from 500 to 10,000 in one second.after stop put files,file descriptors are rapidly decreasing, dropping from 10,000 to around 500 in one second.
Is this a bug or is there a problem with my parameter configuration?
I use nginx

<img width="583" alt="image" src="https://github.com/minio/minio/assets/8872412/acf17cb7-3341-4b61-b641-18eaba2349dd">

* Version used (`minio --version`): 202208
* Server setup and configuration: distributed mode (6 nodes/ 4 disk each) 
* Operating System and version (`uname -a`): novalocal 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*nginx version : 1.12.2

**Comment by ravindk89** [comment]
@shaolila to confirm, you are running MinIO from 2022, and you are using a kernel that has been End of Life'd for a very long time.

We expect community users to follow the latest stable release, and to use a non-EOL OS kernel. We cannot reasonably debug behavior that is years out of date, on an OS kernel that is years out of support.

Please look into upgrading your MinIO deployment and check if the issue persists.

**Comment by adababys** [comment]
> @shaolila to confirm, you are running MinIO from 2022, and you are using a kernel that has been End of Life'd for a very long time.
> 
> We expect community users to follow the latest stable release, and to use a non-EOL OS kernel. We cannot reasonably debug behavior that is years out of date, on an OS kernel that is years out of support.
> 
> Please look into upgrading your MinIO deployment and check if the issue persists.

The recommended kernel version for the 2022 version of MinIO ?
