### ISSUE TITLE
Unable to configure webhook event notification via terraform

### ISSUE THREAD

**Issue by g-kartik** [minio/minio#19152]
I am trying to setup Minio via Terraform. The Minio terraform provider only has the resource for event notification and not webhook endpoint. So it expects that we have already configured the endpoint and ready with SQS queue ARN. So I used the docker terraform provider to spin up the Minio server and pass the endpoint details as environment variables. However I am unable to create them because the endpoint is offline. 

## Expected Behavior
Even if the endpoint is offline, we should be able to configure the webhook event notification and the ARN queue should be created. This would enable users to easily manage the resources using Terraform. 

## Current Behavior
If the endpoint is offline the configuration does not work and the ARN queue is not created.

## Possible Solution
The automatic checking of the webhook endpoint should be controllable via environment variables. Like `VALIDATE_WEBHOOK=false`

## Steps to Reproduce (for bugs)
Replace the vars accordingly
```
resource "docker_image" "minio" {
  name = "minio/minio:latest"
}

resource "docker_container" "minio" {
  name  = "minio-terraform"
  image = docker_image.minio.image_id
  command = ["server", "${var.minio_data_target}", "--console-address", ":9001"]
  env = ["MINIO_ROOT_USER=${var.minio_user}", "MINIO_ROOT_PASSWORD=${var.minio_password}",
          "MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY=${var.minio_notify_webhook_enable_primary}",
          "MINIO_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY=${var.minio_notify_webhook_endpoint_primary}",
          "MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_PRIMARY=${var.minio_notify_webhook_queue_dir_primary}",
          "MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_PRIMARY=${var.minio_notify_webhook_queue_limit_primary}"]
  wait = true
  ports {
    internal = 9000
    external = var.minio_port
  }
  mounts {
    target = var.minio_data_target
    source = var.minio_data_source
    type = "bind"
  }
  healthcheck {
    test = ["CMD", "mc", "ready", "local"]
    interval = "1s"
    retries = 4
    start_period = "1s"
    timeout = "20s"
  }
}

resource "minio_s3_bucket" "mindkosh_bucket"{
  bucket = var.bucket_name
}

resource "minio_s3_bucket_notification" "mindkosh-minio-event-notification" {
  bucket = minio_s3_bucket.mindkosh_bucket.bucket

  queue {
    id        = "${var.event_notification_queue_id}"
    queue_arn = var.event_notification_queue_arn

    events = [
      "s3:ObjectCreated:*",
    ]
  }
}
```

## Your Environment

* Version used (`minio --version`): latest
* Server setup and configuration:
* Operating System and version (`uname -a`): arch linux

**Comment by harshavardhana** [comment]
@g-kartik MinIO expects that if you are creating the target freshly, it must be online. You can have it turned off after once it's configured. 

But we expect a fresh configuration must have the webhook online.
