### ISSUE TITLE
Bug in Calulating the avilable memory in case of container/k8s deployment

### ISSUE THREAD

**Issue by minalkpatil** [minio/minio#19150]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Seems to be bug in cgroupMemLimit function in handler-api.go file. 
output from /sys/fs/cgroup/memory/memory.limit_in_bytes comes with '\n' character appended which is causing parsing error on  line number 73. 
This parsing error is causing misbehavior in availableMemory function specifically in containerized deployments. Here instead of using cgroupmemory limit, code then refers to nodes avilable memory. THis incorrect memory reading sometimes is resulting large value of apiRequestsMaxPerNode  and potentially resulting into minio crash on limited memory deploymets. 

## Expected Behavior
when value is read from "/sys/fs/cgroup/memory/memory.limit_in_bytes" value should be sanitized for whitespaces  

## Current Behavior
Currently values are directly passed for string conversion leading into below conversion error
error occured strconv.ParseUint: parsing "9223372036854771712\n": invalid syntax

## Possible Solution
    buf_str= strings.TrimSpace(string(buf))
    limit, err = strconv.ParseUint(string(buf_str), 10, 64)

## Steps to Reproduce (for bugs)

1.Deploy minio on k8s env with fixed limits
2. Monitor the value of api_max_requests. Ideally value should always remain same. 

## Context
We are trying to run minio on our k8s stack with memory limits configured. This is leading into minio pod crash 

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by minalkpatil** [comment]
Trimmed code to reproduce issue
`package main

import "fmt"
import (
    "os"
    "runtime"
    "strconv"
 //   "strings"

)
const (
    cgroupV1MemLimitFile = "/sys/fs/cgroup/memory/memory.limit_in_bytes"
    cgroupV2MemLimitFile = "/sys/fs/cgroup/memory.max"
    cgroupMemNoLimit     = 9223372036854771712
)

func cgroupMemLimit() (limit uint64) {
    var  buf_str string
    buf, err := os.ReadFile(cgroupV2MemLimitFile)
    if err != nil {
        buf, err = os.ReadFile(cgroupV1MemLimitFile)
    }
    if err != nil {
        return 0
    }
//    buf_str= strings.TrimSpace(string(buf))
    buf_str=string(buf)
    fmt.Println("value as " + string(buf_str))
    limit, err = strconv.ParseUint(string(buf_str), 10, 64)
    if err != nil {
        // The kernel can return valid but non integer values
        // but still, no need to interpret more
     fmt.Println("error occured", err)
        return 0
    }
    fmt.Println("Converted value as ", limit)
    if limit == cgroupMemNoLimit {
                fmt.Println("Max value found")
        // No limit set, It's the highest positive signed 64-bit
        // integer (2^63-1), rounded down to multiples of 4096 (2^12),
        // the most common page size on x86 systems - for cgroup_limits.
        return 0
    }
    return limit
}


func main() {
    fmt.Println("Hello, World!")
    fmt.Println("Runtime " + runtime.GOOS )
    var available uint64
    if runtime.GOOS == "linux" {
        // Useful in container mode
        fmt.Println(" Getting cgroupMemLimit")
        limit := cgroupMemLimit()
        if limit > 0 {
            // A valid value is found
            fmt.Println("found" )
            available = limit
        }       else {
                fmt.Println("Not Found")
        }
    } // for all other platforms limits are based on virtual memory.
    fmt.Println("available " ,available)

}
`

**Comment by harshavardhana** [comment]
fixed by #19153
