### ISSUE TITLE
delete my bucket, got error: 502 Bad Gateway

### ISSUE THREAD

**Issue by wushuaiping** [minio/minio#19166]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
I want to use some functions, such as deleting buckets, setting access permissions for buckets, etc
## Current Behavior
I want delete my bucket, but i got this error:
![image](https://github.com/minio/minio/assets/26813459/e1832965-ec24-4a5a-b78c-c3b70b9da7cc)

I want change Access Policy, but i got this error:
![image](https://github.com/minio/minio/assets/26813459/376c4099-d1da-40f4-99e1-a0fbbd0272d1)

I want set tags, but i got this error:
![image](https://github.com/minio/minio/assets/26813459/992a9cc1-f3ae-41fb-a94d-b4cc6faee8ab)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): Version is latest, Single machine deployment
* Server setup and configuration: CentOS8, 4 core CPU，8G RAM，5T Disk
* Operating System and version (`uname -a`): Linux localhost.localdomain 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
MinIO does not return 502, check if you have an nginx gateway - and make sure its configured properly as per our documentation.

**Comment by wushuaiping** [comment]
> MinIO does not return 502, check if you have an nginx gateway - and make sure its configured properly as per our documentation.

i not use nginx, this is my docker command: 
```
docker run -d --name=minio -p 9000:9000 -p 8081:8081 -v /data/minio-storage:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=xxxx" quay.io/minio/minio server /data --console-address ":8081"
```
Other than that, no configuration has been made, These are the ports I have opened:
![image](https://github.com/minio/minio/assets/26813459/c65ffdc5-e77d-4a52-a2de-530444124442)

**Comment by wushuaiping** [comment]
> MinIO does not return 502, check if you have an nginx gateway - and make sure its configured properly as per our documentation.

May I ask what is the reason for this question? Or is there any solution available, tks :)

**Comment by julienlau** [comment]
I think that minio does return 502: 
for example in case of tiering if you have an object existing in the metadata in the hot tier but the data is stored in the backend tier, then if the backend tier is unavailable minio return 502
