### ISSUE TITLE
The S3 API Request Error Rate for monitoring headobject in MinIO is particularly high.

### ISSUE THREAD

**Issue by adababys** [minio/minio#19167]
## NOTE

![S3_API_Request_Error_Rate](https://github.com/minio/minio/assets/8872412/d0807089-d692-49bb-88e6-a8d10a001f61)
![S3_API_Request_Error_Rate2](https://github.com/minio/minio/assets/8872412/55633985-6c94-4f50-98fc-08a25eba9ffd)
![S3_API_Request_Error_Rate3](https://github.com/minio/minio/assets/8872412/8023dc2c-36c4-4fac-95e5-52c4989412a9)

* Version used (`minio --version`): 202208
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
head object is quite commonly used for checking if file exists or not, if you have such kind of application it will see a lot of 404s - we separate out the metrics now for 4xx and 5xx 

It looks like you are on an ancient release. Community versions only the latest releases are supported, so please upgrade.

**Comment by dahiyahimanshu** [comment]
![image](https://github.com/minio/minio/assets/5242576/1139dc91-45cc-41ab-954a-bda525e58ca0)
We are also getting it lot os 4xx in listObjectV2 and headobject calls

Chart version
```yaml
chart: operator
      version: v5.0.11
```

Added context we are using minio with spark apps without minio spark checkpoint manager
