### ISSUE TITLE
Error  alias set  minio to notify  kafka 

### ISSUE THREAD

**Issue by lbouquinD** [minio/minio#19163]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

when I try to set  evetnt I have the folowing   issue but this error not have sense. 

`mc admin config set myminio/ notify_kafka:myname topic=mytopic queue_dir=/data/appli/temp_notify  brokers="broker1:9092,broker2:9092" --insecure`

## Current Behavior

I have the following message: 
`mc: <ERROR> Unable to set 'notify_kafka:myname  topic=mytopic  queue_dir=/data/appli/temp_notify brokers=broker1:9092,broker2:9092' to server: error (myname:kafka): not connected to target server/service`

## Steps to Reproduce (for bugs)

1. set  alias minio 
2. list bucket  to  make sure you that connected  ( mc ls  myminio/ )    
3. set  event with the previous command I  give. 

## Regression

I don't change anything but before this worked. 
I test network with kafka and everything it's Ok. Netcat  set  connected to all kafka broker since all  node of minio cluster.  
## Your Environment

* Version used (`minio --version`): ```
minio version RELEASE.2023-08-04T17-40-21Z (commit-id=cb089dcb52f0bc8eb58a4c991dfd92a0fec13e62)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc. 
```
* Server setup and configuration:
* Operating System and version (`uname -a`): Linux myVM 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> * minio version RELEASE.2023-08-04T17-40-21Z (commit-id=cb089dcb52f0bc8eb58a4c991dfd92a0fec13e62)

Please upgrade your MinIO version @lbouquinD
