### ISSUE TITLE
minio delete expired  objects slowly

### ISSUE THREAD

**Issue by Mockito-0723** [minio/minio#19168]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I set ilm expired objects after 7 days,but more objects after 1 or 2 months still exists. the driver have reached limit. And I set scanner speed to the fastest, but it seems not effect.
How to slove this provlem?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> I set ilm expired objects after 7 days,but more objects after 1 or 2 months still exists. the driver have reached limit. And I set scanner speed to the fastest, but it seems not effect.
> How to slove this provlem?

Debugging performance and architectural things require a subscription: https://min.io/pricing - please sign up so that we can help.
