### ISSUE TITLE
5 node cluster can not put data how to find root cause?

### ISSUE THREAD

**Issue by lygn128** [minio/minio#19175]
<can not put data>

## Expected Behavior
should put data success

## Current Behavior
1  yesterday can put data;
2  now can not put data;
3  all minio process  is running and have low cpu use;
4 conse logging is hanging

how to solve this? thank you very much.

## Your Environment

* Version used (`minio --version`):  
minio version RELEASE.2024-02-04T22-36-13Z (commit-id=f225ca331203032888889c1c4a3f96ee3452b9f9)
Runtime: go1.21.6 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
* Server setup and configuration:    
5node ， one node have 97 hdd
* Operating System and version (`uname -a`):
Linux oss-116 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lygn128** [comment]
mc admin info myminio       also hang

**Comment by harshavardhana** [comment]
@lygn128 we would need to check the server logs and see if they are all disconnected for some reason.

Also make sure you are always upgrading to latest to report issues as a community member.

**Comment by lygn128** [comment]
> @lygn128 we would need to check the server logs and see if they are all disconnected for some reason.
> 
> Also make sure you are always upgrading to latest to report issues as a community member.

update to latest version and reboot all node ,now can put data,  but now one node  top command show  1000+ load
top - 00:27:57 up 13 days,  3:05,  2 users,  load average: 1056.35, 979.89, 925.61


dmesg -T   show some error:
_[Sun Mar  3 00:05:49 2024] sd 1:0:109:0: [sddb] tag#5003 Sense Key : Recovered Error [current] [descriptor] 
[Sun Mar  3 00:05:49 2024] sd 1:0:109:0: [sddb] tag#5003 ASC=0xb ASCQ=0xa 
[Sun Mar  3 00:24:50 2024] sd 1:0:110:0: [sddc] tag#713 Sense Key : Recovered Error [current] [descriptor] 
[Sun Mar  3 00:24:50 2024] sd 1:0:110:0: [sddc] tag#713 ASC=0xb ASCQ=0xa_ 


but smartctrl  show no err:

           _Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:          0        0         0         0          0      13097.327           0
write:         0        0         0         0          0      18359.325           0
verify:        0        0         0         0          0         34.552           0_

**Comment by harshavardhana** [comment]
> dmesg -T show some error: _[Sun Mar 3 00:05:49 2024] sd 1:0:109:0: [sddb] tag#5003 Sense Key : Recovered Error [current] [descriptor] [Sun Mar 3 00:05:49 2024] sd 1:0:109:0: [sddb] tag#5003 ASC=0xb ASCQ=0xa [Sun Mar 3 00:24:50 2024] sd 1:0:110:0: [sddc] tag#713 Sense Key : Recovered Error [current] [descriptor] [Sun Mar 3 00:24:50 2024] sd 1:0:110:0: [sddc] tag#713 ASC=0xb ASCQ=0xa_
> 
> but smartctrl show no err:

your drive has failed.
