### ISSUE TITLE
Rebalance got stuck and can't be stopped

### ISSUE THREAD

**Issue by olevitt** [minio/minio#19179]
Hi !  
We added a new pool and ran a rebalance which got stuck and now stopping it does nothing as one pool is reporting `None` as rebalance `status`.

## Expected Behavior
Rebalance should not get stuck or at least should be stopped properly

## Current Behavior
Rebalance got stuck and stopping it returns `success` but does not stop. One pool is reporting `None` as rebalance status.

## Steps to Reproduce (for bugs)
Not sure how to reproduce the bug exactly but here is how it happened on our instance :  
* Had 2 pools running
* Added a 3rd one
* Started a rebalance  
* Rebalance got stuck after 36+ hours 
```
Per-pool usage:
┌────────┬────────┬────────┐
│ Pool-0 │ Pool-1 │ Pool-2 │
│ 0.20%  │ 0.21%  │ 0.05%  │
└────────┴────────┴────────┘
Summary: 
Data: 9.0 TiB (4826823 objects, 4826842 versions) 
Time: 38h4m38.483651468s (0s to completion)
```
* Tried to stop it `mc admin rebalance stop` returning `success` but nothing changes in `mc admin rebalance status`
* When getting json status : `{"ID":"RnuW94YgMBKUSSJK26NMAo","stoppedAt":"2024-03-02T14:55:52.546942659Z","pools":[{"id":0,"status":"Completed","used":0.20348239928158965,"progress":{"objects":4826823,"versions":4826842,"bytes":9869868540408,"bucket":"","object":"","elapsed":137078483651468,"eta":0}},{"id":1,"status":"Completed","used":0.2061059035310339,"progress":{"objects":0,"versions":0,"bytes":0,"bucket":"","object":"","elapsed":260224774,"eta":0}},{"id":2,"status":"None","used":0.051272700480432386,"progress":{"objects":0,"versions":0,"bytes":0,"bucket":"","object":"","elapsed":0,"eta":0}}]}
`. Pool2 reports `None` as `status`

We are now stuck in this situation for rebalance / decomission, restarting pods does not change anything and there is nothing relevant in the logs.
Everything else is working just fine (all pods are up, no downtime, data is accessible, sts still works ...)

## Your Environment
* Version : `2024-02-09T21:25:16Z`
* Tenant configuration :  

```yaml
apiVersion: v1
items:
- apiVersion: minio.min.io/v2
  kind: Tenant
  metadata:
    creationTimestamp: "2022-02-10T16:39:24Z"
    generation: 27
    labels:
      app: minio-datanode
    name: minio-datanode
    namespace: minio-datanode
    resourceVersion: "1947682967"
    uid: 249e3083-6152-4d37-a226-527db3c81d94
  scheduler:
    name: ""
  spec:
    certConfig:
      commonName: minio-datanode
      dnsNames:
      - minio-datanode-pool-0-{0...3}.minio-datanode-hl.minio-datanode.svc.cluster.local
      - minio-datanode-pool-1-{0...3}.minio-datanode-hl.minio-datanode.svc.cluster.local
      - minio-datanode-pool-2-{0...3}.minio-datanode-hl.minio-datanode.svc.cluster.local
      organizationName:
      - system:nodes
    configuration:
      name: minio-datanode-configuration
    env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: <redacted>
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: minio-datanode
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: <redacted>
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
      value: <redacted>
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: openid, profile, email, roles
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: policy
    - name: MINIO_DOMAIN
      value: <redacted>
    - name: MINIO_BROWSER
      value: "on"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: <redacted>
    - name: MINIO_SERVER_URL
      value: <redacted>
    - name: _MINIO_DISABLE_API_FREEZE_ON_BOOT
      value: "true"
    image: minio/minio:RELEASE.2024-02-09T21-25-16Z
    imagePullPolicy: IfNotPresent
    imagePullSecret: {}
    liveness:
      httpGet:
        path: /minio/health/live
        port: 9000
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 10
    mountPath: /export
    podManagementPolicy: Parallel
    pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: v1.min.io/tenant
                operator: In
                values:
                - minio
              - key: v1.min.io/pool
                operator: In
                values:
                - pool-0
            topologyKey: kubernetes.io/hostname
      name: pool-0
      nodeSelector:
        datanode: "true"
      resources:
        limits:
          cpu: "30"
          memory: 128Gi
        requests:
          cpu: "5"
          memory: 32Gi
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1117Gi
          storageClassName: minio-disks-datanode
        status: {}
      volumesPerServer: 18
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: v1.min.io/tenant
                operator: In
                values:
                - minio
              - key: v1.min.io/pool
                operator: In
                values:
                - pool-1
            topologyKey: kubernetes.io/hostname
      name: pool-1
      nodeSelector:
        minio-pool1: "true"
      resources:
        limits:
          cpu: "30"
          memory: 128Gi
        requests:
          cpu: "5"
          memory: 32Gi
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2233Gi
          storageClassName: minio-disks-pool1
        status: {}
      volumesPerServer: 18
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: v1.min.io/tenant
                operator: In
                values:
                - minio
              - key: v1.min.io/pool
                operator: In
                values:
                - pool-2
            topologyKey: kubernetes.io/hostname
      name: pool-2
      nodeSelector:
        minio-pool2: "true"
      resources:
        limits:
          cpu: "30"
          memory: 128Gi
        requests:
          cpu: "5"
          memory: 32Gi
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2233Gi
          storageClassName: minio-disks-pool2
        status: {}
      volumesPerServer: 12
    readiness:
      httpGet:
        path: /minio/health/ready
        port: 9000
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 10
    requestAutoCert: true
    serviceMetadata:
      consoleServiceAnnotations:
        v2.min.io: console-svc
      consoleServiceLabels:
        label: console-svc
      minioServiceAnnotations:
        v2.min.io: minio-svc
      minioServiceLabels:
        label: minio-svc
  status:
    availableReplicas: 12
    certificates:
      autoCertEnabled: true
      customCertificates: {}
    currentState: Initialized
    drivesOnline: 192
    healthStatus: green
    pools:
    - legacySecurityContext: false
      ssName: minio-datanode-pool-0
      state: PoolInitialized
    - legacySecurityContext: false
      ssName: minio-datanode-pool-1
      state: PoolInitialized
    - legacySecurityContext: false
      ssName: minio-datanode-pool-2
      state: PoolInitialized
    revision: 0
    syncVersion: v5.0.0
    usage:
      capacity: 314817238900736
      rawCapacity: 374074471612416
      rawUsage: 59426890473472
      usage: 59426890473472
    writeQuorum: 12
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by harshavardhana** [comment]
Please upgrade your setup @olevitt

**Comment by olevitt** [comment]
I just upgraded to the latest `RELEASE.2024-03-03T17-50-39Z`. 
No changes, rebalance is still stuck

**Comment by harshavardhana** [comment]
First from what I can see the rebalance has stopped completely just that the status() indicating things wrong.

It's just cosmetic reporting issue.

**Comment by krisis** [comment]
@olevitt Could you share the MinIO server logs? I understand that there are no rebalance related errors in your logs, but it will help to know what other errors were observed.

**Comment by olevitt** [comment]
> @olevitt Could you share the MinIO server logs? I understand that there are no rebalance related errors in your logs, but it will help to know what other errors were observed.

Here are the logs obtained using `mc admin logs` after upgrading to the latest release `RELEASE.2024-03-05T04-48-44Z`.
Tell me if there are other logs I should grab.

[minio.logs.tar.gz](https://github.com/minio/minio/files/14494235/minio.logs.tar.gz)

**Comment by olevitt** [comment]
I just opened issue #19198 that happens on the same cluster.  
Not sure if it's related or not but it may well be so I'm linking it here

**Comment by olevitt** [comment]
> I just opened issue #19198 that happens on the same cluster. Not sure if it's related or not but it may well be so I'm linking it here

Small update : #19198 has been solved by today's release (`RELEASE.2024-03-10T02-53-48Z`) but this issue is still present (rebalance still stuck)

**Comment by harshavardhana** [comment]
> Small update : #19198 has been solved by today's release (`RELEASE.2024-03-10T02-53-48Z`) but this issue is still present (rebalance still stuck)

@olevitt, the intention of the release was not to fix anything related to this issue. Rebalance is not "really" stuck it simply never says its "complete" 

Do you think that rebalance is running somehow? - no, it is not running. However, it does not say that it is not running.

It's a cosmetic thing.

**Comment by olevitt** [comment]
> > Small update : #19198 has been solved by today's release (`RELEASE.2024-03-10T02-53-48Z`) but this issue is still present (rebalance still stuck)
> 
> @olevitt, the intention of the release was not to fix anything related to this issue. Rebalance is not "really" stuck it simply never says its "complete"
> 
> Do you think that rebalance is running somehow? - no, it is not running. However, it does not say that it is not running.
> 
> It's a cosmetic thing.

Thing is it looks like it's more than just cosmetic, it prevents decommisioning from being started : 
```
gon@laboitemagique:~$ mc admin decommission start sspcloud/ https://minio-datanode-pool-0-{0...3}.minio-datanode-hl.minio-datanode.svc.cluster.local/export{0...17}
mc: <ERROR> Unable to start decommission on the specified pool. Pool rebalance is already started.
```

**Comment by harshavardhana** [comment]
It is cosmetic because it is just a metadata file. Just delete `rm -rf /backend/disks/.minio.sys/rebalance.bin` and you should be good with doing decommission.

Never rebalance for tiny setups like yours in the future; it is the most useless use of your system's IOPs. Let MinIO schedule new objects to the new pool properly. Fundamentally, rebalancing on MinIO is mostly meaningless, and we wanted our design to be that way. It is implemented to ensure that we do not get random FUD. 

If you want to decommission, do so.  Manage your cluster wisely by making more straightforward choices for operating the MinIO setup. Avoid making it a "high" touch environment; deploy and leave it for the applications. 

MinIO admin's job is to replace drives and monitor the setup for outages. Applications do not ask for rebalance; Rewriting objects here and there does not benefit you. 

If your new pool is faster, you should move all your objects, decommissioning your older setup. Please do not use a slow pool perpetually and pay the price by giving different SLAs for different objects on which pool they are. You can never gain on IOPs by pool expansion. So, doing a rebalance will not have any benefits on IOPs for an equivalent scale. A Pool expansion, as the word says, "expansion," is meant for more storage space.

**Comment by olevitt** [comment]
> It is cosmetic because it is just a metadata file. Just delete `rm -rf /backend/disks/.minio.sys/rebalance.bin` and you should be good with doing decommission.

Thanks ! It worked, I was able to start a decommissioning (I had to restart the pods after deleting the `rebalance.bin`)
