### ISSUE TITLE
Objects count not updating after upgrade server.

### ISSUE THREAD

**Issue by xpader** [minio/minio#19172]
Objects count not updating after upgrade minio server to latest container image.

## Expected Behavior
Objects count should updating after some times when put object or delete object.

## Current Behavior
Object count stopped updating, when enable _MINIO_SERVER_DEBUG=on.
Container log output lots of `minio: <DEBUG> applyActions: lifecycle: Secondary scan: NoneAction`.
`mc admin trace` output lots of `[SCANNER] scanner.ScanFolder`, `[SCANNER] scanner.ScanObject`, `[OS] os.OpenFileRFd`.

## Possible Solution
Sometimes some bucket objects count updated after restart server, but some bucket never update now.
Sometimes after run `mc du alias/bucket`, some bucket objects count will update once.

## Steps to Reproduce (for bugs)
1. Pull latest minio container image.
2. Recreate container.
3. Upload lots of files to bucket.
4. Wait for objects count update, never update.

## Context
I'm using minio to store loki logs chunks instead of local filesystem, and watch how many disk space and how many files of loki used.
Without real objects count, this is meaningless.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-02-26T09-33-48Z (commit-id=92788e4cf4aa5fc7c42227642f206482fccecaf1)
* Server setup and configuration: docker run -p 9000:9000 -p 9090:9090 --name minio -v /home/minio:/data -e="MINIO_STORAGE_CLASS_STANDARD=EC:0" -e "MINIO_ROOT_USER=minioadmin" -e "MINIO_ROOT_PASSWORD=**" -e "MINIO_SERVER_URL=http://**:9000" --restart=always -d quay.io/minio/minio server /data --console-address ":9090"
* Operating System and version (`uname -a`): Linux ecs-db2 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xpader** [comment]
mc admin scanner info

```
Scanner Activity: ●∙∙
                                                                                                     	
Overall Statistics                                                                                   	
------------------                                                                                   	
Last full scan time:   0d0h14m; Estimated 3085.62/month                                              	
Current cycle:         86452; Started: 2024-03-01 17:34:09.538333666 +0000 UTC                       	
Active drives:         1                                                                             	
                                                                                                     	
Last Minute Statistics                                                                               	
----------------------                                                                               	
Objects Scanned:       10718 objects; Avg: 433.834µs; Rate: 15433920/day                             	
Versions Scanned:      10718 versions; Avg: 5.551µs; Rate: 15433920/day                              	
Versions Heal Checked: 0 versions; Avg: 0ms                                                          	
Read Metadata:         10718 objects; Avg: 403.27µs, Size: 416 bytes/obj                             	
ILM checks:            10718 versions; Avg: 3.945µs                                                  	
Check Replication:     10718 versions; Avg: 905ns                                                    	
Verify Deleted:        0 folders; Avg: 0ms                                                           	
Yield:                 44.586s total; Avg: 4.16ms/obj                                                	
------------------------------------- Currently Scanning Paths --------------------------------------	
127.0.0.1:9000/data/loki/fake/f47f9872a5a263d7/1
```

Scanner show Estimated 3085.62/month, what is that??? I don't have so many file to scan, what does 3085 month means?

**Comment by harshavardhana** [comment]
the object counts update is not deterministic, it is updated in asynchronous fashion and take time can be hours to days depending on the speed of the drive.

**Comment by xpader** [comment]
Looks like scanner running every 14 minutes?
Everytime when scanner is up, it scanner whole bucket objects not increments?

**Comment by harshavardhana** [comment]
> Looks like scanner running every 14 minutes?
> Everytime when scanner is up, it scanner whole bucket objects not increments?

it scans full bucket every 16 cycles.

**Comment by xpader** [comment]
> > Looks like scanner running every 14 minutes?
> > Everytime when scanner is up, it scanner whole bucket objects not increments?
> 
> it scans full bucket every 16 cycles.

Oh, I can't imagine how long it would take to scan buckets with hundreds of thousands or millions of files. 
The Loki log chunks is a large number of small files.
