### ISSUE TITLE
AzureGov endpoint not working

### ISSUE THREAD

**Issue by mkm29** [minio/minio#19186]
## Expected Behavior

Setting up a lifecycle policy to backup buckets to Azure Blob

## Current Behavior

The azure.net endpoint is used instead of the azure.us, the endpoint is hardcoded [here](https://github.com/minio/minio/blob/d5656eeb6535b20eeb9a925cdad277153e75a33b/cmd/warm-backend-azure.go#L181)

## Possible Solution

Update the codebase to switch off the cloud type to change how the URL is constructed

**Comment by harshavardhana** [comment]
We do not support Gov cloud endpoint @mkm29 yet as we have no way to test it

**Comment by mkm29** [comment]
> We do not support Gov cloud endpoint @mkm29 yet as we have no way to test it

Fair enough. Thanks!

**Comment by jgriff** [comment]
I submitted a PR ([#19188](https://github.com/minio/minio/pull/19188)) to add support for expressing the `--endpoint` argument when configuring an `azure` tier.

With that change, I'm able to configure the lifecycle management to write to an Azure blob storage on Gov cloud (ie, `https://ACCOUNT.blob.core.usgovcloudapi.net`).

**Comment by harshavardhana** [comment]
Closed via #19188
