### ISSUE TITLE
Unable to expand two-node cluster

### ISSUE THREAD

**Issue by TonyNoble** [minio/minio#19197]
I have a two node cluster with one disk each.  Due to infrastructure restrictions, we cannot use sequential hostnames, but MinIO runs with these recognised as a single pool.  We have 
```
MINIO_VOLUMES="https://host-a.domain/apps/data/data1 https://host-b.domain/apps/data/data1"
```
mc shows the pool as follows:
```
# mc admin info mystorage
●  host-a.domain:443
   Uptime: 23 minutes 
   Version: 2024-03-05T04:48:44Z
   Network: 2/2 OK 
   Drives: 1/1 OK 
   Pool: 1st

●  host-b.domain:443
   Uptime: 23 minutes 
   Version: 2024-03-05T04:48:44Z
   Network: 2/2 OK 
   Drives: 1/1 OK 
   Pool: 1st
```

## Expected Behavior
When attempting to expand the cluster, adding a new entry to MINIO_VOLUMES should create a new pool

## Current Behavior
Restart of existing hosts fails with errors:
```
ERROR Unable to initialize backend: /apps/data/data1 drive is already being used in another erasure deployment. (Number of drives specified: 5 but the number of drives found in the 1st drive's format.json: 2)
```

## Steps to Reproduce (for bugs)

1. Start two node Minio cluster with two hosts specified, with one drive each
2. Build third, fourth and fifth nodes with one drive each.  
3. Update all configs appropriately and attempt restart

## Context

We are trying to expand the resiliency of the existing (inherited) setup.  Currently if one node fails, the entire cluster is offline and this is not acceptable for us

## Your Environment

* Version used (`minio --version`):
```
Runtime: go1.21.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```
* Operating System and version (`uname -a`):
```
# uname -a
Linux host-a 4.18.0-513.9.1.el8_9.x86_64 #1 SMP Thu Nov 16 10:29:04 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
You can't just convert a single drive into a multi drive set-up and reuse that drive.

You should read how expansion works in MinIO.

**Comment by TonyNoble** [comment]
@harshavardhana - I did read the documents (that I could find).
According to them, adding a new entry to MINIO_VOLUMES should create a new pool, except in this instance, the behaviour does not match the documentation.  Please don't close this issue with an RTFM when I already have RT'd the FM.
