### ISSUE TITLE
API s3.AbortMultipartUpload Return code 204

### ISSUE THREAD

**Issue by dormanze** [minio/minio#19194]
When I use minio-java to upload a file, the return code is 204 and the file is not uploaded.
![image](https://github.com/minio/minio/assets/37854724/3aebba85-3b2d-4882-9e9a-9bc5c5b50f1f)
The trace log is as follows:
```
minio_trace_20240305075415595.zip:2024-03-05T05:27:52.640 [200 OK] s3.NewMultipartUpload minio-0.minio-headless.kube-system.svc.cluster.local:8989/datacube-dis-manager-1002/1002/default_user/collection/default_batch/2024/0305/bbde811135c646d19d2218d712ac1140-t20240305/Probe-0012-3.zip?uploads=  172.18.0.193      5.171ms      ↑ 129 B ↓ 372 B
minio_trace_20240305075415595.zip:2024-03-05T05:29:42.341 [204 No Content] s3.AbortMultipartUpload minio-1.minio-headless.kube-system.svc.cluster.local:8989/datacube-dis-manager-1002/1002/default_user/collection/default_batch/2024/0305/bbde811135c646d19d2218d712ac1140-t20240305/Probe-0012-3.zip?uploadId=58a76ae5-4c1d-446f-8039-72813271d878  172.18.0.193      4.035ms      ↑ 116 B ↓ 0 B
```
![image](https://github.com/minio/minio/assets/37854724/549e9e09-1bba-4908-b2be-c68011ba9322)
No exception is recorded in the Minio server logs.

## Expected Behavior

File uploaded successfully.

## Current Behavior
File not found.

**Comment by klauspost** [comment]
As the `AbortMultipartUpload` hints the call aborts an upload. Therefore no object is to be expected. This is likely done internally in minio-java due to an error.

If you have a clean reproducer of an issue file it on [minio-java](https://github.com/minio/minio-java) including the source code to your reproducer.

**Comment by wszhangqj** [comment]
> As the `AbortMultipartUpload` hints the call aborts an upload. Therefore no object is to be expected. This is likely done internally in minio-java due to an error.
> 
> If you have a clean reproducer of an issue file it on [minio-java](https://github.com/minio/minio-java) including the source code to your reproducer.

How Do I Determine Whether a File Is Successfully Uploaded?

**Comment by klauspost** [comment]
The SDK should return that information. Not an expert on it, but it seems like it would throw a `MinioException`.
