### ISSUE TITLE
Minio data is lost. Do you have any logs to locate how it was lost

### ISSUE THREAD

**Issue by smallemployees** [minio/minio#19191]
**Is your feature request related to a problem? Please describe.**
Minio data is lost. Do you have any logs to locate how it was lost
**Describe the solution you'd like**
I would like to see if it was deleted through the interface or policy, when it was deleted, and is there a log record
**Describe alternatives you've considered**
I hope there are log records to help me troubleshoot the situation of data loss
**Additional context**

**Comment by harshavardhana** [comment]
@smallemployees you need to configure audit logs in your environment to check who made the S3 API call to delete the objects.

MinIO does not automatically delete objects without any ILM policy.

**Comment by klauspost** [comment]
If/when you need a review of your system for production safety reach out on `hello@min.io`.
