### ISSUE TITLE
Minio server is eating up memory like it has gone crazy (30GB)

### ISSUE THREAD

**Issue by thedevd** [minio/minio#19192]
I have very simple usecase of using minio to store hardly object size less than 10MB, I am running minio server since a month and each day I see the memory is increase by significant amount, and currently it is consuming 30GB memory. 

I have no idea what is happening with minio  server process. 

mc version RELEASE.2023-02-28T00-12-59Z (commit-id=5fbe8c26bab5592f0bc521db00665f8670a0fb31)
Runtime: go1.19.6 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

**Comment by harshavardhana** [comment]
@thedevd we have no idea what you are doing, I suspect mostly you have is page-cache memory. MinIO won't generally use upto 30GiB. 

Please provide the setup and share `mc support profile alias/`
