### ISSUE TITLE
Cluster Read Quorum endpoint (/health/cluster/read) returns always 503 after update from 2024-02-13T15:35:11Z to 2024-03-05T04:48:44Z

### ISSUE THREAD

**Issue by pulchart** [minio/minio#19202]
Cluster Read Quorum endpoint (/health/cluster/read) return always 503 after update from 2024-02-13T15:35:11Z to 2024-03-05T04:48:44Z.  The read / write operation are working.

## Expected Behavior
```
curl -s https://minio.domain/minio/health/cluster/read -w "%{http_code}\n" 
200
```
## Current Behavior

Updated Version: 2024-03-05T04:48:44Z
```
curl -s https://minio.domain/minio/health/cluster -w "%{http_code}\n" 
200
curl -s https://minio.domain/minio/health/cluster/read -w "%{http_code}\n" 
503
```
Previous Version: 2024-02-13T15:35:11Z
```
curl -s https://minio.domain/minio/health/cluster -w "%{http_code}\n" 
200
curl -s https://minio.domain/minio/health/cluster/read -w "%{http_code}\n" 
200
```

## Possible Solution
unknown

## Steps to Reproduce (for bugs)

1. update to 2024-03-05T04:48:44Z
2. run `curl -s https://minio.domain/minio/health/cluster/read -w "%{http_code}\n" `

## Your Environment

```
$ minio --version
minio version RELEASE.2024-03-05T04-48-44Z (commit-id=1b5f28e99b145b0e3a5d99d1801a9b5cbfbdb091)
Runtime: go1.21.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

**Comment by harshavardhana** [comment]
Will check @pulchart

**Comment by harshavardhana** [comment]
@Praveenrajmani I thought this was tested ?

**Comment by Praveenrajmani** [comment]
Sorry, I think i have missed the read test @harshavardhana 

Checking this..

**Comment by Praveenrajmani** [comment]
was able to repro this, will send a fix
