### ISSUE TITLE
Inconsitent Service Account Replication

### ISSUE THREAD

**Issue by pschichtel** [minio/minio#19201]
While diagnosing AccessDenied issues of velero, when recreating a service account, I noticed that sometimes when refreshing the page (or immediately after creating an access key), the newly created key or some random other key (sometimes including the site-replicator-0 key) are not visible.

Polling `/api/v1/service-accounts` on the console host yielded different results too.

It might have been the case, that site replication was disrupted, at least currently the responses seems fine after I fixed KES on the replication target.

## Your Environment

* Version used (`minio --version`): RELEASE.2024-03-05T04-48-44Z
* Server setup and configuration: deployed by operator (5.0.12), replicating to a single-node setup on the same version deployed with docker-compose.
* Operating System and version (`uname -a`): `Linux  6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Both sites would need KMS configured if you have site replication.

If you don't have KMS configured correctly it is not expected to work properly either.

**Comment by pschichtel** [comment]
@harshavardhana yeah that makes sense and I'd be perfectly fine with the site replication breaking in that scenario, but it surprised me, that synchronization within the site broke down. is that still to be expected?

**Comment by pschichtel** [comment]
Also... is it normal that the `/api/v1/service-accounts` endpoint takes >1 second to respond?

**Comment by harshavardhana** [comment]
> Also... is it normal that the `/api/v1/service-accounts` endpoint takes >1 second to respond?

No that is not normal that shows that you have some KMS issues. 


> @harshavardhana yeah that makes sense and I'd be perfectly fine with the site replication breaking in that scenario, but it surprised me, that synchronization within the site broke down. is that still to be expected?

I think we should have error checks in place to make sure both sites have KMS configured if-not fail site replication setup.

// cc @poornas

**Comment by pschichtel** [comment]
My vault seems snappy and the KES too

**Comment by pschichtel** [comment]
@harshavardhana I just double checked: kes responds instantly (20ms) to `/v1/key/list/...` and `/v1/key/encrypt/...` requests. The connection between minio and kes is also instant (~20ms). Should I create a separate issue?
