### ISSUE TITLE
Login with root not possible

### ISSUE THREAD

**Issue by pschichtel** [minio/minio#19218]
If updated to the latest release that includes @poornas' PR that fixes #19206. Service accounts indeed started working again, however I can't login to either of the sites in the console. The browser console shows that the /session fails with "invalid session" and the /admin/site-replication request fails with "Access denied". No other logs that I'm aware of.

## Your Environment

* Version used (`minio --version`): RELEASE.2024-03-07T00-43-48Z
* Server setup and configuration: deployed by operator (5.0.12), replicating to a single-node setup on the same version deployed with docker-compose.
* Operating System and version (`uname -a`): `Linux  6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`

**Comment by pschichtel** [comment]
S3 operations work without issues both with the root user directly as well as with service accounts, so this might be an issue with the console. Happy to move the issue over there if that's indeed the case.

**Comment by pythoninja** [comment]
I can't log in with console too under `ROOT` but can with my custom limited user

**Comment by harshavardhana** [comment]
Closing as duplicate of #19217
