### ISSUE TITLE
possible Memoryleak

### ISSUE THREAD

**Issue by HaveFun83** [minio/minio#19219]
After upgrade from 2023.12.23 to 2024.3.5 / 2024.3.7 we see increased memory usage which looks like a memory leak

![Bildschirmfoto_2024-03-07_09-55-40](https://github.com/minio/minio/assets/38665716/c5dcdf1f-b821-4777-b17f-c1e9c5ed8821)

## Expected Behavior

linear memory usage as before the upgrade

## Current Behavior

constant increased memory usage until pod memory limits are reached and the pod get oom killed

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

degraded service

## Regression

Maybe

## Your Environment

* Version used (`minio --version`): 
DEVELOPMENT.2024-03-07T00-43-48Z
* Server setup and configuration: 
k8s 1.27.11 
4 Pod distributed setup
Pools:
   1st, Erasure sets: 1, Drives per erasure set: 4
74 GiB Used, 14 Buckets, 109,657 Objects
4 drives online, 0 drives offline

* Operating System and version (`uname -a`):
Debian GNU/Linux 11 5.10.0-28-amd64

**Comment by harshavardhana** [comment]
It is not we preallocate memory now.

**Comment by HaveFun83** [comment]
thanks for your support. 

And the memory preallocation is based on the memory resource limits or is there a different parameter that we need to adjust?

Before the upgrade our minio pods used around 1.5G with 2G as limit. After the upgrade they run constantly into the 2G limit end got oom killed. We now raised the limit to 4G but one of the pods is near the limit mark again.

**Comment by harshavardhana** [comment]
You should increase it to 16G minimum

**Comment by weisjohn** [comment]
> You should increase it to 16G minimum

@harshavardhana is this a real suggestion or sarcasm?
This is a huge change in behavior.
