### ISSUE TITLE
Can't login console for  a custom domain without DNS parse

### ISSUE THREAD

**Issue by yasyx** [minio/minio#19237]
Hi，
I deployed Minio server with docker, and I set the 
MINIO_SERVER_URL=http://minio.udesk.local  
MINIO_BROWSER_REDIRECT_URL = http://minio.udesk.local/console/

When it started, the browser have some error like this 
<img width="1139" alt="image" src="https://github.com/minio/minio/assets/12021357/f893f09d-57ef-4a62-bab5-1a8595345f92">

the api path is v1/api/session , in this API, it will call another API (/minio/admin/v3/accountinfo) in Minio server. but the hostname of minio is cannot connected because of it is a custom domain with out DNS.

I read the code of minio and find something like this
![image](https://github.com/minio/minio/assets/12021357/e722573c-c6db-43f0-9431-67d6cb7e56f7)

The CONSOLE_MINIO_SERVER was override by globalMinioEndpoint when the server starting , so I cannot repalce it with my custom value  
 
## Expected Behavior
The minio console can work well with a custom domain with out DNS

## Current Behavior
It have error in browser and login failed .

## Possible Solution
When CONSOLE_MINIO_SERVER has a value, it will not be overridden by globalMinioEndpoint.

## Steps to Reproduce (for bugs)
1. set the env and start servers
MINIO_SERVER_URL=http://minio.udesk.local  
MINIO_BROWSER_REDIRECT_URL = http://minio.udesk.local/console/
2. visit minio via http://minio.udesk.local/console and  check the browser console

## Your Environment
version: [RELEASE.2024-03-05T04-48-44Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-03-05T04-48-44Z)

**Comment by harshavardhana** [comment]
You need a working DNS for minio_server_url to allow Console UI to work.

**Comment by yasyx** [comment]
@harshavardhana Many thanks for your help, I was add a hosts in container to resolve it.
