### ISSUE TITLE
XL: aws s3 cp Md5sum mismatch with a 60gb file. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1923]
## Expected behaviour

Md5sum Match of the inserted object with the object fetched. 
## Actual behaviour

Mismatch witnessed.
## Steps to reproduce the behaviour
- copy from local to Minio
- md5sum ~/60gb
-  aws --endpoint-url http://localhost:9001 s3 cp  ~/60gb s3://zrigwpdoa4bnuwy63nupbjy0vl5kqu
- Copy from Minio back to local 
-  aws --endpoint-url http://localhost:9001 s3 cp  s3://zrigwpdoa4bnuwy63nupbjy0vl5kqu/60gb ~/karthic/  
- md5sum ~/karthic/60gb 
- Mismatch noticed. 
  ## Minio version
  Latest master 
## System information

Minio3 instance

**Comment by hackintoshrao** [comment]
Will check whether same issue is noticed in `mc` too, or its only with `aws  s3` tool.

**Comment by hackintoshrao** [comment]
Had got bad result once. But it looks to be fine now, may be aws cli downloads the parts in parallel and joins them locally, thats why Md5sum right after the download was different.

**Comment by harshavardhana** [comment]
> Had got bad result once. But it looks to be fine now, may be aws cli downloads the parts in parallel and joins them locally, thats why Md5sum right after the download was different.

This issue must be related to #1921
