### ISSUE TITLE
In cluster mode, when one of disk goes offline, putobject Occasionally got 499 from server

### ISSUE THREAD

**Issue by vklonghml** [minio/minio#19236]
## Steps to Reproduce (for bugs)

1.  when one of disk goes offline in a cluster mode
2. using a script put object to cluster, very few of the putobject return 499
3. command "mc admin trace" also got 499, no more else info

## Your Environment

* Version used (`minio --version`):RELEASE.2023-01-02T09-40-09Z
* Operating System and version (`uname -a`):centos8

Expected Behavior
After one disk goes offline, the cluster can continue to function normally.

Current Behavior
In cluster mode, when one of disk goes offline, putobject Occasionally got 499 from server

Possible Solution
n/a

**Comment by jiuker** [comment]
Upgrade to latest version. Plz
