### ISSUE TITLE
Cannot install older minio versions using brew by creating a local tap

### ISSUE THREAD

**Issue by kcaashish** [minio/minio#19248]
If I try to install older versions of minio / mc using brew, I get this error:
```sh
Error: tap/local-minio/minio@release.2024-03-05t04-48-44z: undefined method `<' for nil:NilClass
```

## Expected Behavior
Installation should work.

## Current Behavior
Gives error on `brew` commands, `brew info`, `brew install`.
```sh
> brew install minio@release.2024-03-05t04-48-44z
Error: tap/local-minio/minio@release.2024-03-05t04-48-44z: undefined method `<' for nil:NilClass
```

## Steps to Reproduce (for bugs)
1. Create a new tap
```sh
brew tap-new local-minio
```

2. Extract the desired version
```sh
brew extract --version RELEASE.2024-03-05T04-48-44Z minio/stable/minio tap/local-minio
```

3. Run `brew install`
```sh
brew install minio@release.2024-03-05t04-48-44z
```

## Your Environment

* brew version:
```sh  
brew --version
Homebrew 4.2.12-13-g2d77465
Homebrew/homebrew-core (git revision dae89e1fca2; last commit 2024-03-12)
```
* Operating System and version (`uname -a`):
```sh
Darwin enigmac.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000 arm64
```

**Comment by kcaashish** [comment]
Found out that the issue was because of the class name. Solved by editing the formula and removing `@` from the classname.

```rb
class Minio@release20240305T044844Z < Formula
```
to

```rb
class MinioAT20240305T044844Z < Formula
```

And changing the formula name to `minio@2024-03-05t04-48-44z.rb`.

**Comment by adamency** [comment]
@kcaashish Would you mind sharing the formulae code you built that worked in the end ?
