### ISSUE TITLE
Automatically assigned `console-address` port collides with user-specified `address` port

### ISSUE THREAD

**Issue by masnax** [minio/minio#19255]
We have noticed that minio will occasionally fail to start, complaining with:
```
minio server --address "127.0.0.1:45201"

ERROR Unable to start the server: --console-address port cannot be same as --address port
```

We are using the release: `RELEASE.2024-03-10T02-53-48Z`

I did find https://github.com/minio/minio/issues/18301 which may potentially be related.

I would assume this is happening because we have defined `--address`, but there is no active listener yet so the port is technically free for `--consumer-address` to grab.

**Comment by harshavardhana** [comment]
@masnax choose a different one for both.

--address :45201 --console-address :45202

**Comment by masnax** [comment]
In that case then I would say there should be a check to make sure both are specified or the application errors out.

If the solution is that both flags are required then that's what the application should expect as well.
