### ISSUE TITLE
ERROR Unable to initialize a connection to KES as specified by the shell environment: key already exists

### ISSUE THREAD

**Issue by NadamHL** [minio/minio#19258]
### 版本
| 软件   | 版本                                                         |
| ------ | ------------------------------------------------------------ |
| minio  | RELEASE.2022-02-18T01-50-10Z                                 |
| vault  | v1.11.7 (ddea7a4ee09a3556fbd8d6ccd7df3981b5445b4e)           |
| kes    | 2024-01-11T13-09-29Z   commit=bd277c469de21464889f28baee9cd5fe0f29d05b |
| centos | 7.6.1810 (Core)                                              |

### 报错
```shell
ERROR Unable to initialize a connection to KES as specified by the shell environment: key already exists
```
### 代码
```golang
		// We check that the default key ID exists or try to create it otherwise.
		// This implicitly checks that we can communicate to KES. We don't treat
		// a policy error as failure condition since MinIO may not have the permission
		// to create keys - just to generate/decrypt data encryption keys.
		if err = KMS.CreateKey(defaultKeyID); err != nil && !errors.Is(err, kes.ErrKeyExists) && !errors.Is(err, kes.ErrNotAllowed) {
			logger.Fatal(err, "Unable to initialize a connection to KES as specified by the shell environment")
		}
```
error.go
```golang
	// to create a cryptographic key which already exists.
	ErrKeyExists Error = NewError(http.StatusBadRequest, "key does already exist")
```
- 由于KMS.CreateKey(defaultKeyID)，后端返回“key already exist”，与ErrKeyExists 不一致，导致直接报错：“ERROR Unable to initialize a connection to KES as specified by the shell environment: key already exists
”
- 代码直接更改为如下，会影响其他功能吗
   - ```golang
   		//if err = KMS.CreateKey(defaultKeyID); err != nil && !errors.Is(err, kes.ErrKeyExists) && !errors.Is(err, kes.ErrNotAllowed) {
		if err = KMS.CreateKey(defaultKeyID); err != nil && err.Error() != "key already exists" && !errors.Is(err, kes.ErrNotAllowed) {
			logger.Fatal(err, "Unable to initialize a connection to KES as specified by the shell environment")
		}
     ```

**Comment by NadamHL** [comment]
- 查看`RELEASE.2022-05-23T18-45-11Z`版本，则不会报错。这个是`RELEASE.2022-02-18T01-50-10Z`的bug吗？
<img width="1025" alt="842e7d6b51046b3ba394c16ff42b6c1" src="https://github.com/minio/minio/assets/39847290/4c3d5540-4592-4e12-a291-8826ff5690b8">

**Comment by harshavardhana** [comment]
Please upgrade your MinIO - do not use 2yr old MinIO.

**Comment by NadamHL** [comment]
Can we still use the old version without upgrading?

**Comment by NadamHL** [comment]
- This problem is the current version (RELEASE.2022-02-18T01-50-10Z).
Do you have to upgrade the version before you can solve the bug?
- By testing RELEASE.2022-05-23T18-45-11Z, this version can be used normally and there is no key already exists error.

**Comment by harshavardhana** [comment]
> Can we still use the old version without upgrading?

Read our community support guidelines https://min.io/pricing - you want support for older versions please become a customer.
