### ISSUE TITLE
Why does setting the bucket BucketLifeCycleRule life cycle rule not work in stand-alone mode?

### ISSUE THREAD

**Issue by bigbird-0101** [minio/minio#19252]
## question
Why does setting the bucket BucketLifeCycleRule life cycle rule not work in stand-alone mode?

## version:
RELEASE.2022-01-04T07-41-07Z

## java sdk code
```
String bucketName = "test-expires-delete-marker-v3";LifecycleConfiguration config = new LifecycleConfiguration(List.of(
                new LifecycleRule(Status.ENABLED,
                        null,
                        new Expiration((ResponseDate) null, 1, null),
                        new RuleFilter(bucketName+"/picture/"),
                        bucketName+"picture",
                        null,null,
                        null)));
                minioClient.setBucketLifecycle(SetBucketLifecycleArgs.builder()
                        .bucket(bucketName)
                        .config(config)
                        .build());
```

### my request
`<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Days>1</Days></Expiration><Filter><Prefix>/picture/</Prefix></Filter><ID>test-expires-delete-marker-v31picture</ID><Status>Enabled</Status></Rule></LifecycleConfiguration>`

I hope that the object life cycle I set can be used, and my object can be deleted according to the expiration time I want.

## Current Behavior
However, it has not been deleted currently, and the object has exceeded the expiration time.

**Comment by jiuker** [comment]
Upgrade to latest minio version. Plz
