### ISSUE TITLE
Allow updating endpoint of remote storage in tiering

### ISSUE THREAD

**Issue by orzFly** [minio/minio#19254]
**Is your feature request related to a problem? Please describe.**
`mc ilm tier update` doesn't have a `--endpoint` argument. I am currently deploying two minio instances for SSD and HDD. Currently, I cannot decide a permanent endpoint URL for the next, for example, 10 years.  I hope I can update the endpoint URL.

**Describe the solution you'd like**
Support `--endpoint` in `mc ilm tier update`

**Describe alternatives you've considered**
Start some new minio instances, and copy/move all the files to the new minio.

**Additional context**

**Comment by harshavardhana** [comment]
@orzFly chose a DNS that you will use forever, you can keep changing the IPs whenever you want underneath for that DNS entry.

**Comment by orzFly** [comment]
For those who come across this issue: 

If you really don't want to use a regular DNS name, you can also consider modifying /etc/hosts. If you are using Docker/podman, you can consider the `--add-host` option.
