### ISSUE TITLE
context deadline exceeded (*fmt.wrapError)

### ISSUE THREAD

**Issue by slena1** [minio/minio#19264]
I have been using MinIO bucket replication strategy for file synchronization between two regions for the past 3 months. However, in the last two days, I have noticed that large files (greater than 6GB) are failing to transfer. Upon checking the logs, I found the following error:
Time: 16:08:07 UTC 03/14/2024
DeploymentID: b4f5af36-33a0-4cf1-8cae-762c380d67c8
RequestID:
RemoteHost:
UserAgent:
Error: unable to replicate for object XXX/240306V1844.zip(2b537143-49c8-48b1-ba87-a96be77144d9) to target http://x.x.x.x:9000/: Put "http://x.x.x.x:9000/XXX/240306V1844.zip?partNumber=802&uploadId=NDU5MDUwNzMtYmJlZS00Zjc3LTkyZGUtNjk5NjRlNTZhMjA1LjJkNzlmOTBmLTMyODctNDdjYy05OGRlLTg5NDU5ZDQ3MjFkYQ": context deadline exceeded (*fmt.wrapError)

Backtrace:
0: internal/logger/logger.go:260:logger.LogIf()
1: cmd/bucket-replication.go:1531:cmd.ReplicateObjectInfo.replicateAll()
2: cmd/bucket-replication.go:1051:cmd.replicateObject.func2()

**Comment by harshavardhana** [comment]
Please submit proper bug reports.
