### ISSUE TITLE
S3Error: The Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by abdulrehman192** [minio/minio#19278]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am trying to upload file using javascript.  here is my example code

`const Minio = require('minio');

const minioClient = new Minio.Client({
  endPoint: 'play.min.io',
  port: 9000,
  useSSL: true,
  accessKey: 'u4bmMCAAMKpP5Ucs8PgW',
  secretKey: 'FZ4Ndee4edFLxjEadieMbjW1RV89UzKU3uvnGQ30',
});

const bucket = 'public-files';

async function ensureBucketExists(bucketName) {
  try {
    const exists = await minioClient.bucketExists(bucketName);
    if (!exists) {
      await minioClient.makeBucket(bucketName, 'us-east-1');
      console.log(`Bucket '${bucketName}' created in "us-east-1".`);
    }
  } catch (error) {
    console.error('Error occurred while ensuring bucket exists:', error);
  }
}

async function uploadFileStream(destinationObject, fileStream, metaData) {
  try {
    const buffer = await streamToBuffer(fileStream);
    const length = buffer.length;

    // Upload file using putObject method
    await minioClient.putObject(bucket, destinationObject, buffer, length, metaData);
    console.log(`File uploaded successfully to '${destinationObject}'`);
  } catch (error) {
    console.error('Error occurred while uploading file:', error);
  }
}

// Helper function to convert stream to buffer
function streamToBuffer(stream) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    stream.on('data', (chunk) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', (error) => reject(error));
  });
}

module.exports = {
  ensureBucketExists,
  uploadFileStream,
};`

## Current Behavior
When I try to upload the image or file I get the following error

`S3Error: The Access Key Id you provided does not exist in our records.
    at parseError (C:\Users\mrabd\Desktop\ims\node_modules\minio\dist\main\internal\xml-parser.js:35:13)
    at Object.parseResponseError (C:\Users\mrabd\Desktop\ims\node_modules\minio\dist\main\internal\xml-parser.js:82:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (C:\Users\mrabd\Desktop\ims\node_modules\minio\dist\main\internal\client.js:476:19)
    at async Client.getBucketRegionAsync (C:\Users\mrabd\Desktop\ims\node_modules\minio\dist\main\internal\client.js:526:19)
    at async Client.makeRequestStreamAsync (C:\Users\mrabd\Desktop\ims\node_modules\minio\dist\main\internal\client.js:447:25) {
  code: 'InvalidAccessKeyId',
  bucketname: 'public-files',
  resource: '/public-files',
  region: 'us-east-1',
  requestid: '17BD3C7B1879728E',
  hostid: '3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac',
  amzRequestid: '17BD3C7B1879728E',
  amzId2: '3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac',
  amzBucketRegion: 'us-east-1'
}`

## Your Environment
I setup the minio through easypanel.

**Comment by harshavardhana** [comment]
Please create this key first on play.min.io

**Comment by abdulrehman192** [comment]
I already created a key on my minio console.  I create the minio console through Easypanel. I purchased a VPS server from the hostinger then install the Easypanel on it through EasyPanel I install the minio template. 

My server link is https://ims-minio.zroooe.easypanel.host

**Comment by SHUHAIB-T** [comment]
Hi, 
I created a s3 client 
```js
import * as Minio from "minio";

const s3Client = new Minio.Client({
  endPoint: "s3.amazonaws.com",
  accessKey: "<MY_KEY_ID>",
  secretKey: "<MY_SECRET_KEY>",
});

const bucket = "test-bucket"

const exists = await s3Client.bucketExists(bucket);
if (exists) {
  console.log("Bucket " + bucket + " exists.");
}
```

but I am gettig the following error.
```bash
S3Error: The AWS Access Key Id you provided does not exist in our records.
````

I am running minio locally with docker. do I need to setup anything in minio console

**Comment by klauspost** [comment]
@SHUHAIB-T But you are trying to connect to AWS `endPoint: "s3.amazonaws.com"`

**Comment by IvanCord** [comment]
Same problem here. Does anyone found the solution for this problem?

**Comment by slim-fighting** [comment]
> Same problem here. Does anyone found the solution for this problem?

MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated. Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD

**Comment by tefkah** [comment]
To anyone coming here after May 24th and using `mc` to initialize Minio: 
support for `mc config host add` was seemingly dropped in [this release](https://github.com/minio/minio/releases/tag/RELEASE.2025-05-24T17-08-30Z).

use `mc alias set` instead

**Comment by muratc** [comment]
same problem.

i am using argocd to deploy the minio tenant chart. i have configured it like following:

`
  configuration:
    name: data-minio
  configSecret:
    name: data-minio
    existingSecret: true
`
the data-minio secret has the following:

`
apiVersion: v1
kind: Secret
metadata:
  name: data-minio
type: Opaque
stringData:
  config.env: |-
    export AWS_ACCESS_KEY_ID=admin
    export AWS_SECRET_ACCESS_KEY=password
    export AWS_REGION=us-east-1
    export MINIO_ROOT_USER=admin
    export MINIO_ROOT_PASSWORD=password
`

this doesn't seem to create access keys, because when i try to connect with those credentials i get the same exception "The Access Key Id you provided does not exist in our records".

I am using minio tenant helm chart 7.1.1 and minio image RELEASE.2025-04-22T22-12-26Z.

i couldn't figure this out really. i have tried adding a new access key using console but same error.
