### ISSUE TITLE
Unable to configure server grid RPC services: grid: local host not found

### ISSUE THREAD

**Issue by freemindLi** [minio/minio#19270]
I am using aws ubuntu ec2 machine to install minio,but happend this error,Could you tell me how to fix?
![image](https://github.com/minio/minio/assets/59459626/ffe2ec58-e875-4fba-b525-4d3a6d1488a6)

**The minio version is:**
minio version RELEASE.2024-03-10T02-53-48Z (commit-id=88a89213ff6663f2d3ee1de7f3293497ab9844e8)
Runtime: go1.21.8 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.

**The ec2 basic information is:**
Linux ip-xx-xx-xx-xx 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Post your config/setup - this is not a guessing game.

**Comment by harshavardhana** [comment]
@klauspost it's okay to close for issues that are blatantly incomplete.

On EC2 you need to use internal private IPs not EC2 node DNS IP, which is floating and not associated the node.

**Comment by jamilnoyda** [comment]
> @klauspost it's okay to close for issues that are blatantly incomplete.
> 
> On EC2 you need to use internal private IPs not EC2 node DNS IP, which is floating and not associated the node.

please double check this

**Comment by klauspost** [comment]
@jamilnoyda ?
