### ISSUE TITLE
Support setting `MINIO_IDENTITY_OPENID_CLIENT_SECRET` via docker secrets

### ISSUE THREAD

**Issue by septatrix** [minio/minio#19282]
**Is your feature request related to a problem? Please describe.**
Environment variables have several disadvantages and Docker secrets (or any file based passing of credentials) is more secure. While some Minio configs support setting them via `*_FILE`, this is not the case for the OpenID related values.

**Describe the solution you'd like**
Add a new `MINIO_IDENTITY_OPENID_CLIENT_SECRET_FILE` configuration variable.

**Describe alternatives you've considered**
Adopt a general mechanism where every variable starting with e.g. `file:/` gets interpreted as a secret and tried to be read from a file. This would allow using secrest for every configuration value if one desires and solves this problem for configs added in the future.

**Comment by harshavardhana** [comment]
Feel free to send a fix
