### ISSUE TITLE
Configuration of Redis notification cannot be completed

### ISSUE THREAD

**Issue by vamonet** [minio/minio#19284]
Based on the documentation (see https://min.io/docs/minio/linux/reference/minio-server/settings/notifications/redis.html) for Redis notification setup it should be possible to define an endpoint address with redis username and password but it is not accepted.

## Expected Behavior

Redis address/endpoint with username and password will be accepted and Minio server configured to send notifications to Redis.

## Current Behavior

See steps to reproduce.

## Possible Solution

Code modification???

## Steps to Reproduce (for bugs)

After execuriton of this command:
`$ mcli admin config set minio/ notify_redis address="http://user:pass@localhost:6379" key="minio" format="access"`

You wiil get:
mcli: <ERROR> Unable to set 'notify_redis address=http://user:pass@localhost:6379 key=minio format=access' to server: address http://user@localhost:6379: too many colons in address.

Same for the case without username:
`$ mcli admin config set minio/ notify_redis address="http://localhost:6379" key="minio" format="access"`

Result:
mcli: <ERROR> Unable to set 'notify_redis address=http://localhost:6379 key=minio format=access' to server: address http://localhost:6379: too many colons in address.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-03-03T17-50-39Z (commit-id=09b0e7133ddcb2e2a26a36f2caed59a7b7bc7c88)
* Runtime: go1.21.7 linux/amd64

**Comment by jiuker** [comment]
Could you use `mcli admin config set minio/ notify_redis address="user:pass@localhost:6379" key="minio" format="access"` instead ? @vamonet Don't use `http://` for address.

**Comment by vamonet** [comment]
Thanks but unfortunately it has the same result:
`$ mcli admin config set minio/ notify_redis address="user:pass@localhost:6379" key="minio" format="access"`

Output:
mcli: <ERROR> Unable to set 'notify_redis address=user:pass@localhost:6379 key=minio format=access' to server: address user:pass@localhost:6379: too many colons in address.

If port is ommited then a different error message appears:
`$ mcli admin config set minio/ notify_redis address="user:pass@localhost" key="minio" format="access"`

Output:
mcli: <ERROR> Unable to set 'notify_redis address=user:pass@localhost key=minio format=access' to server: invalid port number.

**Comment by jiuker** [comment]
@vamonet  `mcli admin config set minio/ notify_redis address="localhost:6379" key="minio" format="access" password="password"` try this.

**Comment by vamonet** [comment]
@jiuker I know, it works but for default redis user only not for other users what makes it unusable for our case as the default user is disabled for security reasons :-(

**Comment by jiuker** [comment]
@vamonet Currently, we cannot achieve this effect yet. I will submit a pull request to improve it. Thank you for your feedback.
