### ISSUE TITLE
XL: check performance with different block size

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1928]
check upload/download performance with different block size (4MB, 10MB etc) different sha256 sha128 sha512

cc @balamurugana

**Comment by GarimaKapoor** [comment]
Please update the timeline.

**Comment by GarimaKapoor** [comment]
cc @vadmeste Can you take a look at this issue

**Comment by vadmeste** [comment]
I tried to compare performance based on different block sizes in my local machine. Each time I change the blockSizeV1 in object-common.go, I remove export directories, restart minio server and measure the duration of uploading and downloading a 2 Gb file:

| Block size | Upload | Download |
| --- | --- | --- |
| 4 kb | 2m41s | 6m29s |
| 8 kb | 2m1s | 3m19s |
| 16 kb | 1m33s | 1m43s |
| 32 kb | 1m12s | 54s |
| 64 kb | 1m10s | 30s |
| 128 kb | 1m9s | 18s |
| 256 kb | 1m7s | 11s |
| 1024 kb | 1m3s | 6s |
| 4 M | 1m3s | 4.85s |
| 5 M | 1m2s | 4.32s |
| 6 M | 1m1s | 4.410s |
| 8 M | 1m1s | 4.28s |
| 10 M | 1m0s | 4.225s |
| 15 M | 1m0s | 4.225s |
| 30 M | 1m0s | 3.229s |
| 32 M | 59s | 4.27s |

I will test with a file of 5 gb file this time with block size from 4M to 32 M to have a better comparaison in that range.

**Comment by krishnasrinivas** [comment]
nice, our 10MB blocksize looks ideal.

**Comment by krishnasrinivas** [comment]
@vadmeste another test that can be done is remove one of the data files and download so that reedsolomon.Reconstruct() kicks in during download.

**Comment by vadmeste** [comment]
With a 5gb file:

| Block size | Upload | Download |
| --- | --- | --- |
| 2 M | 3m16s | 13.63s |
| 4 M | 3m15s | 12.128s |
| 5 M | 3m15s | 11.4s |
| 6 M | 3m15s | 11.4s |
| 8 M | 3m16s | 11.4 |
| 10 M | 3m14s | 11.438 |
| 12 M | 3m14s | 11.45s |
| 16 M | 3m16s | 11,625s |

**Comment by vadmeste** [comment]
@krishnasrinivas, I removed data files from the backend in 7 disks / 16 total disks, mc didn't complain but didn't return anything also.. anyway, this issue https://github.com/minio/minio/issues/2072 should be resolved first

**Comment by harshavardhana** [comment]
Looks like 10MB is the correct value and best on average. Closing we can re-open if needed.
