### ISSUE TITLE
XL: memory usage on parallel GETs

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1929]
- After parallel GETs the memory usage stays high at 12 G and not coming down.
- Increasing parallel reads causes the machine to freeze.

to be tested:
- does minio crash if ulimit set on memory (try 1 to 3G of memory)
- does machine hang under lower ulimit.
- call runtime.GC() and see if frees up the memory

![](https://files.gitter.im/abperiasamy/Holodeck/qAII/Screen-Shot-2016-06-18-at-10.16.06-AM.png)

**Comment by krishnasrinivas** [comment]
karthic to look into this @hackintoshrao

**Comment by hackintoshrao** [comment]
Calling Runtime.GC() didn't help.

**Comment by hackintoshrao** [comment]
Here are the hotspots to optimize. 
<img width="1266" alt="screen shot 2016-06-21 at 10 27 34 am" src="https://cloud.githubusercontent.com/assets/2609511/16218428/3a0a71a8-379b-11e6-9b74-9506356e4502.png">

**Comment by hackintoshrao** [comment]
Making GC more aggressive by setting GOGC=10 reduces the impact. Setting GOGC=5 stabilizes the memory usage to 8-10GB. So its clear that the resource consumption is too much for GC to handle, Need a better implementation of memory management in future for `Read Savvy` loads with objects of large sizes.

**Comment by harshavardhana** [comment]
This issue is fixed.
