### ISSUE TITLE
Error ETIMEDOUT on API production

### ISSUE THREAD

**Issue by johnny274** [minio/minio#19296]
MinIO is truly fantastic, but I'm encountering a minor issue: API on development has successfully uploaded the file to the MinIO bucket, but when deployed, the production API throws an error:
```

Error: connect ETIMEDOUT 103.242.53.57:9000 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xxxx',
  port: 9000,
  storageErrors: []
}
```
I'm using with nestJS. Thank you very much!

**Comment by harshavardhana** [comment]
> MinIO is truly fantastic, but I'm encountering a minor issue: API on development has successfully uploaded the file to the MinIO bucket, but when deployed, the production API throws an error:

Sorry @johnny274 I can't help you if you don't describe your setup or provide some more details.

I am gonna close this out until then. Thank you please use the issue template next time, it is there for a reason.
