### ISSUE TITLE
make-svcacct job in community helm chart broken

### ISSUE THREAD

**Issue by andibraeu** [minio/minio#19314]
Hi,

since changing the base image of the mc container image from ubi-minimal to ubi-micro (https://github.com/minio/mc/pull/4725), the make-svcacct step in the community helm chart is broken when using an existing secret for credentials, as [the step uses sed](https://github.com/minio/minio/blob/RELEASE.2024-03-15T01-07-19Z/helm/minio/templates/_helper_create_svcacct.txt#L96), which is not included in ubi-micro.

## Expected Behavior
Running the community helm chart with values for an user and credentials from an existing secret defined to run smoothly and create the user according to the given values.

## Current Behavior
The create-svcacct job fails, as sed is missing from the mc container image. Hence no svcacct is created. The deployment finishes with an error.

Connecting to MinIO server: http://minio:9000
Added `myminio` successfully.
/config/add-svcacct: line 85: sed: command not found

## Possible Solution
Like in https://github.com/minio/minio/issues/18315  the script can be adjusted not to use `sed` anymore. See https://github.com/minio/minio/pull/18459 as an example.

## Steps to Reproduce (for bugs)
Create a minio deployment using the community helm chart and specifying the respective values for an user to be created, with credentials from an existing secret.

## Context
Setting up the minio server worked fine. However, the make-svcacct job failed. not creating a svcacct as specified as a result.
Other jobs part of the chart remain unaffected, as the minio server deployment is executed as expected.

## Regression
Yes
https://github.com/minio/mc/pull/4725

## Your Environment
minio: RELEASE.2024-03-15T01-07-19Z

**Comment by mananpreetsingh** [comment]
This is still the case, I am using the latest available images and getting the same error.

```
Connecting to MinIO server: http://minio:9000                                                                                                                                                                    
Added `myminio` successfully.                                                                                                                                                                                   
/config/add-svcacct: line 85: sed: command not found
```

Using latest image in the helm chart:
```
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-04-06T05-26-02Z

  mcImage:
    repository: quay.io/minio/mc
    tag: RELEASE.2024-03-30T15-29-52Z
```

Did you push the new helmchart version after the fix?
Config map seems causing the issue.

------

confirmed it is the helm chart version issue. New version needs to be pushed to fix this bug.

**Comment by mananpreetsingh** [comment]
FYI @andibraeu  @harshavardhana ^
