### ISSUE TITLE
Bucket shows as empty all of a sudden

### ISSUE THREAD

**Issue by hkashif** [minio/minio#19318]
## NOTE

1. I was originally running RELEASE.2022-11-11T03-44-20Z. I had a bucket with data inside it. Everything working normally.
2. In an effort to setup replication to another remote instance, I upgraded the instance of interest here to RELEASE.2024-03-03-T17-50-39Z. Again, everything seemed to be working normally.
3. I failed to setup the replication with a remote server connection error (not of relevance here I believe)
4. Suddenly, a few hours later, the bucket shows that as empty in the console. It shows the correct object count and the correct total size, but with nothing inside. The minio CLI shows the bucket as empty as well.
5. In an attempt, to resolve this, I reverted to the older Release version. Now, when I login, I can only see a blank screen. The container logs show this:
```
2024/03/21 22:57:41 | stdout | goroutine 2850 [running]:
2024/03/21 22:57:41 | stdout | critical: "GET /minio/admin/v3/accountinfo": {}
2024/03/21 22:57:41 | stdout | 1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
2024/03/21 22:57:41 | stdout | 2: cmd/admin-handlers-users.go:1251:cmd.adminAPIHandlers.AccountInfoHandler()
2024/03/21 22:57:41 | stdout | 3: cmd/bucket-object-lock.go:47:cmd.(*BucketObjectLockSys).Get()
2024/03/21 22:57:41 | stdout | 4: internal/logger/logger.go:384:logger.CriticalIf()
2024/03/21 22:57:41 | stdout | 5: internal/logger/logger.go:258:logger.LogIf()
2024/03/21 22:57:41 | stdout | Error: expected element type <Rule> but have <ExpiryUpdatedAt> (xml.UnmarshalError)
2024/03/21 22:57:41 | stdout | DeploymentID: 368efbe1-bd94-496c-8bf0-c1aee40a004c
2024/03/21 22:57:41 | stdout | Time: 02:57:41 UTC 03/22/2024
2024/03/21 22:57:41 | stdout | API: SYSTEM()
```

## Expected Behavior
I expect to see the data that was originally in the bucket.

## Current Behavior
The bucket shows as empty but the object count and total size seem correct.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A -- I am not sure if this is reproducible

## Context
It's critical. I cannot access the bucket's data anymore.

## Regression
No

## Your Environment

* Version used (`minio --version`): RELEASE.2022-11-11T03-44-20Z and RELEASE.2024-03-03-T17-50-39Z
* Server setup and configuration: docker instance
```
"env_variables" : [
      {
         "key" : "PATH",
         "value" : "/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "container",
         "value" : "oci"
      },
      {
         "key" : "MINIO_ACCESS_KEY_FILE",
         "value" : "access_key"
      },
      {
         "key" : "MINIO_SECRET_KEY_FILE",
         "value" : "secret_key"
      },
      {
         "key" : "MINIO_ROOT_USER_FILE",
         "value" : "access_key"
      },
      {
         "key" : "MINIO_ROOT_PASSWORD_FILE",
         "value" : "secret_key"
      },
      {
         "key" : "MINIO_KMS_SECRET_KEY_FILE",
         "value" : "kms_master_key"
      },
      {
         "key" : "MINIO_UPDATE_MINISIGN_PUBKEY",
         "value" : "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
      },
      {
         "key" : "MINIO_CONFIG_ENV_FILE",
         "value" : "config.env"
      },
      {
         "key" : "MINIO_BROWSER_REDIRECT_URL",
         "value" : "XXXXXXXXXXXXXXXX"
      },
      {
         "key" : "MINIO_ROOT_PASSWORD",
         "value" : "XXXXXXXXXXXXXXXX"
      },
      {
         "key" : "MINIO_ROOT_USER",
         "value" : "XXXXXXXXXXXXXXXX"
      }
```

**Comment by harshavardhana** [comment]
@hkashif - Data that is critical requires production support so https://min.io/pricing is your friend please sign-up.

WE do cannot unfortunately help you for upgrading downgrading in this fashion. From a cursory view, some bucket metadata has an issue. This can be rectified easily, but a support subscription is needed.

Thanks hopefully I was of some help here.
