### ISSUE TITLE
The service cannot start when I change the IP address

### ISSUE THREAD

**Issue by bouyeijiang** [minio/minio#19319]
The service cannot start when I change the IP address

**Comment by harshavardhana** [comment]
Incomplete issue, closing

**Comment by bouyeijiang** [comment]
Is it only me who has encountered this problem?
![image](https://github.com/minio/minio/assets/4083760/8d507645-d1b2-42b7-a78b-0eed92c93e4b)

**Comment by bouyeijiang** [comment]
Or did I lose my restart privileges?

**Comment by klauspost** [comment]
Check file permissions.
