### ISSUE TITLE
Minio client and backend doesn't show directories when deployed in akd with pvc

### ISSUE THREAD

**Issue by ramazan-safiullin** [minio/minio#19321]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Minio client and backend doesn't show directories when deployed in akd with pvc, though single file (no prefixes) are present
## Expected Behavior

directories are present

## Current Behavior

no directories
## Possible Solution

significantly downgrade the minio version
## Steps to Reproduce (for bugs)

1.Deploy on aks with pvc
2.Upload file in the directory
3.No directory
4.

## Your Environment
AKS with pvc

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
@ramazan-safiullin not sure what this issue is about we have no idea what you are reporting closing as incomplete info.

**Comment by ramazan-safiullin** [comment]
@harshavardhana What kind of info would help you? We also have no idea( We tried another s3 client, it works
