### ISSUE TITLE
The Minio Cross-Origin Issue Encountered When Downloading Files on the Server

### ISSUE THREAD

**Issue by KKJava1** [minio/minio#19323]
"When deploying the project to the server, there is a cross-origin issue when accessing Minio via fetch. There are no issues locally. Specifically, the problem arises when downloading images. How can this be resolved? 
The video or picture plays normally, but when downloading via fetch, it directly encounters a cross-origin issue. The error occurs specifically during the download process.""
![微信截图_20240325001206](https://github.com/minio/minio/assets/116629035/382fbd0c-ba30-4b4a-9e75-70b03e30f7f6)

**Comment by KKJava1** [comment]
"Cross-Origin Error Encountered When Invoking Fetch for Subsequent Downloads
![image](https://github.com/minio/minio/assets/116629035/d5e27534-f9d9-4bbf-a616-bdfb11e90604)

**Comment by harshavardhana** [comment]
Incomplete issue closing
