### ISSUE TITLE
too much memory used by folderScanner

### ISSUE THREAD

**Issue by wuyudian1** [minio/minio#19335]
In our test environment, we have a MinIO cluster set up with the official operator, featuring 2 MinIO server nodes with 2 EBS volumes each, running in EC:2 mode. Recently, we upgraded the MinIO version to 2024-03-05T04-48-44Z through the operator. Unfortunately, we've noticed that whenever our scheduled tasks write database backup files to the upgraded MinIO cluster, the memory of the MinIO server pods starts increasing in a stepwise fashion. With each backup execution, the memory consumption escalates stepwise and does not decrease. Our database backup tool creates a new directory in the MinIO bucket for each backup execution and writes the backup files into that directory (in the test environment, each write operation involves around 2GB of data, approximately 1600 files).
![image](https://github.com/minio/minio/assets/10414890/67de3cff-c450-42af-aac6-f955321425c4)

After exporting memory pprof files, I found that the folderScanner object is consuming a significant amount of memory.
![image](https://github.com/minio/minio/assets/10414890/4681ba89-ef86-46f9-bc1b-d536e33e6aab)

In our production environment, which still runs on an older version of MinIO (RELEASE.2023-02-22T18-23-45Z), the database backup tool writes 16GB files (approximately 6500 files) per operation, but we do not observe this kind of stepwise increase in memory. Moreover, the overall memory usage remains very low, consistently around 3GB, whereas in the test environment, with significantly less data written, the RSS memory consumption can reach up to 11GB.

The enclosure "profile.zip" is the original profile.
[profile.zip](https://github.com/minio/minio/files/14745753/profile.zip)

## Expected Behavior

Memory used by folderScanner should release to the OS.

## Current Behavior
It dose not release memory.

## Possible Solution
I have no idea.

## Regression

No

## Your Environment

Our MinIO cluster set up with the official operator, featuring 2 MinIO server nodes with 2 EBS volumes each, running in EC:2 mode.

**Comment by harshavardhana** [comment]
This is page cache memory not used by MinIO, fine tune it such that you don't over use it.

tuned-adm profile throughput-performance 

Can help.

**Comment by klauspost** [comment]
You are looking at alloc_objects - not in-use objects.

Alloc_objects is the total allocation count - and is expected to keep rising as MinIO runs - as that is the point of the metric.

**Comment by wuyudian1** [comment]
@klauspost   
I apologize for the incorrect assumptions I made about analyzing Go language program's memory pprof files due to my lack of necessary expertise. However, after learning some basic knowledge with the help of ChatGPT, I found that under the inuse_space section, the method github.com/klauspost/reedsolomon.AllocAligned occupies a significant amount of space. Is this normal?
![image](https://github.com/minio/minio/assets/10414890/3f709865-91cf-4ddd-9d63-02c2330da531)

**Comment by klauspost** [comment]
@wuyudian1 Yes. These are pre-allocated buffers. This is expected.

**Comment by wuyudian1** [comment]
@klauspost  Thank you for your timely and patient response. I have another question: This [document](https://min.io/docs/minio/linux/operations/checklists/hardware.html#memory) mentions that "MinIO preallocates 2GiB of memory per node in distributed setups," yet the pprof file provided here shows 4GB. My MinIO cluster has two server nodes (hereinafter referred to as Node A and Node B), and I'm a bit confused: Does Node A, in addition to holding its own pre-allocated 2GB of cache, also hold a backup of the cache from Node B? Furthermore, if the cluster has three nodes, does each node need to pre-allocate 6GB of memory?

**Comment by klauspost** [comment]
We recently changed the pre-alloc. The size of the the cluster does not change the alloc.
