### ISSUE TITLE
MC_HOST_minio-local is not a valid identifier

### ISSUE THREAD

**Issue by itsJohnySmith** [minio/minio#19331]
Provided exports for MinIO Client inside
https://github.com/minio/minio/blob/master/helm/minio/templates/NOTES.txt
that are printed by helm after successful installation return error:

bash: export: „MC_HOST_minio-local=http://rootuser:rootpass123@localhost:9000“: not a valid identifier

It is caused by dash inside template:

`  2. export MC_HOST_{{ template "minio.fullname" . }}-local`

Should be changed to MC_HOST_{{ template "minio.fullname" . }}_local in all of its occurrences.

Examples:
```bash
user@virt:~$ export MC_HOST_minio-local=http://rootuser:rootpass123@localhost:9000
bash: export: „MC_HOST_minio-local=http://rootuser:rootpass123@localhost:9000“: not a valid identifier
user@virt:~$ export MC_HOST_minio_local=http://rootuser:rootpass123@localhost:9000
user@virt:~$
```

**Comment by harshavardhana** [comment]
in ENVs you cannot have `-` that is normal and expected. Please use what is supported by ENVs.

**Comment by itsJohnySmith** [comment]
Well you are right, so maybe fix your templates?
