### ISSUE TITLE
Dash in template not a valid identifier.

### ISSUE THREAD

**Issue by itsJohnySmith** [minio/minio#19332]
Well you are right, so maybe fix your templates?

_Originally posted by @itsJohnySmith in https://github.com/minio/minio/issues/19331#issuecomment-2017789347_

**Comment by itsJohnySmith** [comment]
The problematic dash is not in my variable, but in your template:
 2. export MC_HOST_{{ template "minio.fullname" . }}-local

Please look at that file before you simply close this issue. 
https://github.com/minio/minio/blob/master/helm/minio/templates/NOTES.txt

**Comment by harshavardhana** [comment]
The variable comes vis full name please provide one without -

**Comment by itsJohnySmith** [comment]
Oh c'mon man, what part of "it's in the template,  not the variable " did
you not understand? All you need to do is to check that file.

Dne po 25. 3. 2024 17:38 uživatel Harshavardhana ***@***.***>
napsal:

**Comment by klauspost** [comment]
@itsJohnySmith It is not "our templates" - most of the templates are community contributed. You are welcome to submit a pull request instead of spewing attitude in the comments.
