### ISSUE TITLE
Replication metrics broken

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/minio#19334]
MinIO Replication metrics not working as expected.

## Expected Behavior
MinIO providing every replication metric as documented.

## Current Behavior
MinIO only providing some replication metrics.

## Context
We've put time in our own dashboards using elasticsearch as a datasource... Suddenly we don't see half of the replication metrics anymore after upgrading MinIO.

## Regression
Yes, but I can't remember what the previous version was...

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2024-02-26T09-33-48Z (commit-id=92788e4cf4aa5fc7c42227642f206482fccecaf1)

**Comment by poornas** [comment]
replication metrics was changed in https://github.com/minio/minio/releases/tag/RELEASE.2023-08-31T15-31-16Z - you should update your dashboards.
