### ISSUE TITLE
fatal error: concurrent map writes with RELEASE.2024-03-21T23-13-43Z

### ISSUE THREAD

**Issue by flixr** [minio/minio#19344]
We have minio running as binary on a server with 3 pool (4 drives each):
```
●  minio.my-domain.com
   Uptime: 3 minutes 
   Version: 2024-03-21T23:13:43Z
   Network: 1/1 OK 
   Drives: 12/12 OK 
   Pool: 1, 2, 3

Pools:
   2nd, Erasure sets: 1, Drives per erasure set: 4
   3rd, Erasure sets: 1, Drives per erasure set: 4
   1st, Erasure sets: 1, Drives per erasure set: 4

6.5 TiB Used, 33 Buckets, 16,587,449 Objects, 3,145,683 Versions, 23,485 Delete Markers
12 drives online, 0 drives offline
```

Minio failed multiple times with `fatal error: concurrent map writes`

## Expected Behavior
no fatal errors

## Current Behavior
Minio fails. Attached log after last restart.
[minio_fatal_error.log](https://github.com/minio/minio/files/14757135/minio_fatal_error.log)

## Steps to Reproduce (for bugs)
Could not reproduce on dev/staging setup, but that doesn't have 3 pools.

## Regression
Haven't seen this error before, so looks like a regression.

## Your Environment

* Version used (`minio --version`): `2024-03-21T23:13:43Z`
* Server setup and configuration: VM with disks directly passed through
* Operating System and version (`uname -a`): `Linux minio01 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by klauspost** [comment]
Issue is here: https://github.com/minio/minio/blob/a03dac41ebd2c1b9d3f1110ef5d299ffebb8f87b/cmd/iam-store.go#L714-L715

Grabbing a read lock, but still writing to the cache for not found entries...

**Comment by flixr** [comment]
Thanks for the quick fix!
Any estimate when for when there will be a new release including this?

**Comment by harshavardhana** [comment]
> Thanks for the quick fix! Any estimate when for when there will be a new release including this?

Soon no ETA.
