### ISSUE TITLE
systemctl restart minio failed

### ISSUE THREAD

**Issue by 1iza** [minio/minio#19352]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

`systemctl restart minio` and it restart successfully
## Current Behavior

when i `systemctl restart minio`, and minio ERROR Unable to start the server.
## Steps to Reproduce (for bugs)

1. Writting files into minio
2. systemctl restart minio

## Context

`journalctl -u minio -f`

```
Mar 27 16:49:31  systemd[1]: Stopping MinIO...
Mar 27 16:49:31  systemd[1]: minio.service stop-sigterm timed out. Skipping SIGKILL.
Mar 27 16:49:31  minio[123927]: Exiting on signal: TERMINATED
Mar 27 16:49:31  systemd[1]: minio.service stop-final-sigterm timed out. Skipping SIGKILL. Entering failed mode.
Mar 27 16:49:31  systemd[1]: Stopped MinIO.
Mar 27 16:49:31  systemd[1]: Unit minio.service entered failed state.
Mar 27 16:49:31  systemd[1]: minio.service failed.
Mar 27 16:49:31  systemd[1]: Starting MinIO...
Mar 27 16:49:31  systemd[1]: Started MinIO.
Mar 27 16:49:31  minio[102097]: ERROR Unable to start the server: Specified port is already in use
Mar 27 16:49:31  minio[102097]: > Please ensure no other program uses the same address/port
Mar 27 16:49:31  systemd[1]: minio.service: main process exited, code=exited, status=1/FAILURE
Mar 27 16:49:31  systemd[1]: minio.service stop-sigterm timed out. Skipping SIGKILL.
Mar 27 16:49:31  systemd[1]: minio.service stop-final-sigterm timed out. Skipping SIGKILL. Entering failed mode.
Mar 27 16:49:31  systemd[1]: Unit minio.service entered failed state.
Mar 27 16:49:31  systemd[1]: minio.service failed.
```

I think it's because the minio  hasn't completely stopped yet, causing the minio to be unable to start

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-01-31T20-20-33Z
* Server setup and configuration:   Multi-Node Multi-Drive,  3 nodes and 4 drives
* Operating System and version (`uname -a`): 4.18.0-3.2.el7.x86_64

**Comment by jiuker** [comment]
``` Please ensure no other program uses the same address/port ```

**Comment by 1iza** [comment]
> `Please ensure no other program uses the same address/port`

The port is not being used by other programs.
Minio is running normally, and I restart `systemctl restart minio`, but restart failed, and then`systemctl start minio`, minio will start successful. @jiuker

**Comment by harshavardhana** [comment]
There may other reasons why this is happening. Usually after a sigkill the process must not own the port.

In your OS however this might be odd, your drive might be hung as well. Hung syscalls can hung the process.

**Comment by 1iza** [comment]
> There may other reasons why this is happening. Usually after a sigkill the process must not own the port.
> 
> In your OS however this might be odd, your drive might be hung as well. Hung syscalls can hung the process.

I hope to expand the cluster, and the official document suggests restarting at the same time. However, restarting now will fail and cause the cluster to become unavailable. Can I restart one by one（rolling）?  @harshavardhana

**Comment by jiuker** [comment]
> > There may other reasons why this is happening. Usually after a sigkill the process must not own the port.
> > In your OS however this might be odd, your drive might be hung as well. Hung syscalls can hung the process.
> 
> I hope to expand the cluster, and the official document suggests restarting at the same time. However, restarting now will fail and cause the cluster to become unavailable. Can I restart one by one（rolling）? @harshavardhana

mc admin service restart myminio
https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-service.html

**Comment by 1iza** [comment]
> > > There may other reasons why this is happening. Usually after a sigkill the process must not own the port.
> > > In your OS however this might be odd, your drive might be hung as well. Hung syscalls can hung the process.
> > 
> > 
> > I hope to expand the cluster, and the official document suggests restarting at the same time. However, restarting now will fail and cause the cluster to become unavailable. Can I restart one by one（rolling）? @harshavardhana
> 
> mc admin service restart myminio https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-service.html

Expanding the cluster requires modifying the configuration file, and `mc admin service restart myminio` did not reload the configuration.
