### ISSUE TITLE
searchParent - CPU contribution high with high number of prefixes and sub-prefixes

### ISSUE THREAD

**Issue by Gordon-Gan-Jiang** [minio/minio#19351]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Node cpu load balancing

## Current Behavior

The CPU load of some nodes in the cluster is very high, and the CPU usage exceeds 100%.
The CPU node with high load is not specific; node A has high CPU, drops off after a while, and then becomes high CPU on node B.

## Steps to Reproduce (for bugs)

<img width="1149" alt="image" src="https://github.com/minio/minio/assets/62733672/03864674-bbad-4df4-950f-b073179f7caa">

## Your Environment

* Version used (`minio --version`): 2024-03-15T01:07:19Z
* Server setup and configuration: CPU 64c * 4；SATA 8TB * 4*10; memory256 G
* Operating System and version (`uname -a`): Ubuntu 20.04.5 LTS

**Comment by Gordon-Gan-Jiang** [comment]
What do I need to do? Reduce file path prefix duplication?

**Comment by Gordon-Gan-Jiang** [comment]
![image](https://github.com/minio/minio/assets/62733672/6dd26edc-af48-453a-9ab4-17551344851d)

I updated the minio version and found that some nodes still have high CPU. @harshavardhana

**Comment by harshavardhana** [comment]
It looks like you didn't upgrade at all

**Comment by Gordon-Gan-Jiang** [comment]
![image](https://github.com/minio/minio/assets/62733672/cf6a8f9a-a996-4910-8422-fd4051cea12a)
Can you help me check if this version is correct? @harshavardhana

**Comment by harshavardhana** [comment]
If you are able to take the profile please share the ppprof files here please @Gordon-Gan-Jiang

**Comment by Gordon-Gan-Jiang** [comment]
OK
[profile.pprof.zip](https://github.com/minio/minio/files/14900094/profile.pprof.zip)
@harshavardhana

**Comment by harshavardhana** [comment]
```
         .          .    548:   for k, v := range d.Cache {
   626.69s    907.27s    549:           _, ok := v.Children[want]
     4.65s     54.50s    550:           if ok {
         .          .    551:                   found := dataUsageHash(k)
         .          .    552:                   return &found
         .          .    553:           }
         .          .    554:   }
```


@klauspost how is this even possible? - map lookup is causing CPU spike ?

**Comment by klauspost** [comment]
@harshavardhana Would have to be a bazillion entries a the top level. There should be `PrefixManyFolders` events all over the place.

**Comment by harshavardhana** [comment]
> @harshavardhana Would have to be a bazillion entries a the top level. There should be `PrefixManyFolders` events all over the place.

Can we avoid this some how @klauspost we must see that this many Children and compact it way before.

Btw we have mincat for these purposes, we should perhaps remove prefix level usage requirement from the code from MinIO to reduce memory and CPU usage.

**Comment by klauspost** [comment]
@harshavardhana That would mean compacting the bucket and having a full namespace scan on every cycle.

TBH I don't see much point, since the performance of everything else will be horrible with millions of entries at the top level in so many other ways. Sure adding a 1M max to the top will "fix" it - but everything else will be horrible.

**Comment by harshavardhana** [comment]
Yeah but we can't be impacted by bad usage. We should punt bad usage and stop functionality that cannot be provided.

The idea here is we shouldn't pay the price, and never have to deal with this in prod elsewhere. 

We log a message that indicates what we are not going to be able to perform and simply give up on usage calculation altogether until the data pattern is fixed.

**Comment by Gordon-Gan-Jiang** [comment]
Based on your discussion above, is minio more suitable for storing depth-derived file trees rather than breadth-derived file trees?

**Comment by harshavardhana** [comment]
Can you share the memory profile here? @Gordon-Gan-Jiang instead of the `cpu` ?

**Comment by klauspost** [comment]
> Based on your discussion above, is minio more suitable for storing depth-derived file trees rather than breadth-derived file trees?

Correct, as outlined here: https://min.io/docs/minio/linux/administration/object-management.html#object-organization-and-planning (and similar to AWS S3, which limits throughput per prefix).

**Comment by Gordon-Gan-Jiang** [comment]
> 您可以在这里分享内存配置文件吗？@Gordon-Gan-Jiang而不是`cpu`?

[heap.pprof.zip](https://github.com/minio/minio/files/14918233/heap.pprof.zip)

**Comment by harshavardhana** [comment]
@Gordon-Gan-Jiang please provide `mem` profile not heap profile

```
File: minio
Type: inuse_space
Time: Apr 9, 2024 at 4:46am (PDT)
Duration: 600.19s, Total samples = 2.15GB 
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for -1939.38MB, 88.22% of 2198.23MB total
Dropped 324 nodes (cum <= 10.99MB)
Showing top 10 nodes out of 78
      flat  flat%   sum%        cum   cum%
-1788.02MB 81.34% 81.34% -1788.02MB 81.34%  github.com/klauspost/compress/s2.NewWriter.func1
 -159.40MB  7.25% 88.59%  -159.40MB  7.25%  github.com/klauspost/compress/s2.NewWriter
   45.83MB  2.09% 86.51%    45.83MB  2.09%  github.com/ncw/directio.AlignedBlock
  -41.39MB  1.88% 88.39%   -41.39MB  1.88%  sync.(*Pool).pinSlow
   22.15MB  1.01% 87.38%    22.15MB  1.01%  internal/profile.(*Profile).postDecode
  -18.01MB  0.82% 88.20%   -18.01MB  0.82%  github.com/minio/minio/cmd.glob..func8
   -0.42MB 0.019% 88.22% -1702.28MB 77.44%  io.copyBuffer
   -0.13MB 0.0057% 88.22%  -126.39MB  5.75%  github.com/klauspost/compress/s2.(*Writer).writeSync
         0     0% 88.22%   -88.42MB  4.02%  github.com/klauspost/compress/gzhttp.NewWrapper.func1.1
         0     0% 88.22%  -126.39MB  5.75%  github.com/klauspost/compress/s2.(*Writer).AsyncFlush
```

This output is meaningless.

**Comment by Gordon-Gan-Jiang** [comment]
> @Gordon-Gan-Jiang please provide `mem` profile not heap profile
> 
> ```
> File: minio
> Type: inuse_space
> Time: Apr 9, 2024 at 4:46am (PDT)
> Duration: 600.19s, Total samples = 2.15GB 
> Entering interactive mode (type "help" for commands, "o" for options)
> (pprof) top
> Showing nodes accounting for -1939.38MB, 88.22% of 2198.23MB total
> Dropped 324 nodes (cum <= 10.99MB)
> Showing top 10 nodes out of 78
>       flat  flat%   sum%        cum   cum%
> -1788.02MB 81.34% 81.34% -1788.02MB 81.34%  github.com/klauspost/compress/s2.NewWriter.func1
>  -159.40MB  7.25% 88.59%  -159.40MB  7.25%  github.com/klauspost/compress/s2.NewWriter
>    45.83MB  2.09% 86.51%    45.83MB  2.09%  github.com/ncw/directio.AlignedBlock
>   -41.39MB  1.88% 88.39%   -41.39MB  1.88%  sync.(*Pool).pinSlow
>    22.15MB  1.01% 87.38%    22.15MB  1.01%  internal/profile.(*Profile).postDecode
>   -18.01MB  0.82% 88.20%   -18.01MB  0.82%  github.com/minio/minio/cmd.glob..func8
>    -0.42MB 0.019% 88.22% -1702.28MB 77.44%  io.copyBuffer
>    -0.13MB 0.0057% 88.22%  -126.39MB  5.75%  github.com/klauspost/compress/s2.(*Writer).writeSync
>          0     0% 88.22%   -88.42MB  4.02%  github.com/klauspost/compress/gzhttp.NewWrapper.func1.1
>          0     0% 88.22%  -126.39MB  5.75%  github.com/klauspost/compress/s2.(*Writer).AsyncFlush
> ```
> 
> This output is meaningless.

[allocs.pprof.zip](https://github.com/minio/minio/files/14926550/allocs.pprof.zip)
Please help confirm, do you want this?

**Comment by harshavardhana** [comment]
Nah its still wrong, anyway this requires that we don't compute any partials for a setup like yours.

**Comment by Gordon-Gan-Jiang** [comment]
> Nah its still wrong, anyway this requires that we don't compute any partials for a setup like yours.

I don't understand what you want to express. What should I do to optimize CPU consumption? Do I need to adjust the data structure of minio storage files

**Comment by harshavardhana** [comment]
> I don't understand what you want to express. What should I do to optimize CPU consumption? Do I need to adjust the data structure of minio storage files

First, I cannot understand the `in_use` profile. It looks wrong, and the `top` output from `go tool pprof` looks wrong. Either you are compiling this yourself and have modified the code here.

Can you show me the `--version` commit-id of the binary you are using? As you can see, there is `negative` accounting going on, which I suspect is due to some custom modification of the binary.

**Comment by klauspost** [comment]
AFAICT there is nothing more here.
