### ISSUE TITLE
Grafana 8.2.1, Node dashboard: Error updating options e.replace is not a function

### ISSUE THREAD

**Issue by qrkot** [minio/minio#19357]
## NOTE

I imported [Node dashboard json file](docs/metrics/prometheus/grafana/node) into Grafana 8.2.1 and got an error:

![Screenshot from 2024-03-27 18-08-30](https://github.com/minio/minio/assets/98889670/804ef1cc-d427-4e39-9a54-12e051aca96a)

Metrics exporter on Minio node works Ok, I can see metrics in query browser.

## Expected Behavior
There probably shouldn't be such errors after dashboard import.

## Steps to Reproduce (for bugs)
Download [Node dashboard json file](docs/metrics/prometheus/grafana/node) from Github and manually import it into Grafana.

## Your Environment

* Version used: `2024-03-10T02:53:48Z`
* Operating System and version:  `5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

![Screenshot from 2024-03-27 18-14-57](https://github.com/minio/minio/assets/98889670/c5f2db16-014f-4bed-9d84-089b82f2f032)

**Comment by shtripat** [comment]
This grafana version looks quite old. I have 10.4.0 and the dashboard works fine.
Can you try the same?

**Comment by harshavardhana** [comment]
Yeah let's not support EOLed Grafana versions.

https://endoflife.date/grafana
