### ISSUE TITLE
GO SDK V2 client.HeadBucket() fails to find existing buckets.

### ISSUE THREAD

**Issue by luisgarciaalanis** [minio/minio#19362]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

In GO, client.HeadBucket() API to determine if a bucket exists fails with a Bad Request error. The same call works fine with AWS S3 and Digital Oceans Spaces S3 servers.

## Expected Behavior
It should behave like if calling S3.

## Current Behavior
Fails with Bad Request error.

## Possible Solution
Should return the proper error 
## Steps to Reproduce (for bugs)

I am using AWS GO AWS SDK V2.

```
	bucketName := settings.ValueOf(keys.RentisoBucketName)
	_, err := client.HeadBucket(context.TODO(), &s3.HeadBucketInput{
		Bucket: aws.String(bucketName),
	})

	if err != nil {
		var apiError smithy.APIError

		if errors.As(err, &apiError) {
			switch apiError.(type) {
			case *types.NotFound:
				err = nil
			default:
                                 fmt.Println(err) <---------------------- HERE I get Bad Request.
			}
		}
	}
```

Here is a page with an [example](https://docs.aws.amazon.com/code-library/latest/ug/go_2_s3_code_examples.html)

SDK for Go V2

The following code example shows how to determine the existence of an S3 bucket.

```
// BucketBasics encapsulates the Amazon Simple Storage Service (Amazon S3) actions
// used in the examples.
// It contains S3Client, an Amazon S3 service client that is used to perform bucket
// and object actions.
type BucketBasics struct {
	S3Client *s3.Client
}



// BucketExists checks whether a bucket exists in the current account.
func (basics BucketBasics) BucketExists(bucketName string) (bool, error) {
	_, err := basics.S3Client.HeadBucket(context.TODO(), &s3.HeadBucketInput{
		Bucket: aws.String(bucketName),
	})
	exists := true
	if err != nil {
		var apiError smithy.APIError
		if errors.As(err, &apiError) {
			switch apiError.(type) {
			case *types.NotFound:
				log.Printf("Bucket %v is available.\n", bucketName)
				exists = false
				err = nil
			default:
				log.Printf("Either you don't have access to bucket %v or another error occurred. "+
					"Here's what happened: %v\n", bucketName, err)
			}
		}
	} else {
		log.Printf("Bucket %v exists and you already own it.", bucketName)
	}

	return exists, err
}
```
## Context
Run a selfhosted test minio instance.

## Regression
Not that I know of.

## Your Environment
* Version used (`minio --version`):
minio version RELEASE.2024-03-26T22-10-45Z (commit-id=8bce123bba10a3880deb490bab219d5807da725a)
Runtime: go1.21.8 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.

* Server setup and configuration:
OSX
Official Docker image

* Operating System and version (`uname -a`):
from the docker container 
```
Linux 5541ba49d574 6.6.16-linuxkit #1 SMP PREEMPT_DYNAMIC Fri Feb 16 11:55:08 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@luisgarciaalanis, set UsePathStyle to 'true' or use mini-go/v7 - our library works better and avoids all the AWS garbage.
