### ISSUE TITLE
 upload small files very slow

### ISSUE THREAD

**Issue by wjyl** [minio/minio#19369]
I'm uploading small files to MinIO. The file size is randomly distributed between 10B and 1KB. When the number of files in the cluster is relatively small, the upload time is about 8ms, upload QPS 700. There are about 60 million small files in the cluster now, and the QPS has become very low, only less than 200. And the time consumption is fluctuating, ranging from 40ms to 600~700ms periodically.

## My Environment
minio version RELEASE.2024-03-03T17-50-39Z 
Runtime: go1.21.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.

Linux server-host1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

4 nodes, two drives per node, disk size: 11T

**Comment by klauspost** [comment]
We do not perform community performance analysis. Have a look at our [subscriptions](https://min.io/pricing).

In overall terms, the performance will only change if you place all your objects in the same prefix. See https://min.io/docs/minio/linux/administration/concepts.html#minio-admin-concepts-organize-objects
