### ISSUE TITLE
An error occurred when copying a local file to the MinIO storage bucket using the MC client of MinIO

### ISSUE THREAD

**Issue by CCTV-six** [minio/minio#19371]
## Expected Behavior
All shards of the file can be successfully uploaded in the correct order and size without any errors.
## Current Behavior
Failed to upload part: 400 Bad Request (error uploading part, response code from server: 400)
This error occurred when attempting to upload a shard of the file to the MinIO server

**Comment by harshavardhana** [comment]
Incomplete bug reporting, closing.
