### ISSUE TITLE
"Invalid Login" - LDAP Login on latest version

### ISSUE THREAD

**Issue by mari-arondeus** [minio/minio#19389]
"Invalid Login" for Minio Console / Web GUI when using LDAP account on latest version, but not on version released on 2023-03-26. Rolling back to version from the 26th resolved the issue immediately. We don't have a dev environment to test this issue, but it seems easily reproducible. If needed, we can roll forward outside of active hours and pull a trace or logs.

## Expected Behavior
LDAP logins should not be affected by a standard bugfix update.

## Current Behavior
No LDAP users, even those with ConsoleAdmin permissions, are able to login.

## Possible Solution
Roll back to version 2024-03-26

## Steps to Reproduce (for bugs)
1. Upgrade Minio packages to version "minio-20240330094156.0.0-1.x86_64"
2. Run `mc admin service restart <instance>`
3. Attempt to log into Minio Console / Web GUI via an LDAP account

## Your Environment
RHEL 8.9, kver 4.18.0-513.18.1.el8_9.x86_64 - 4-node
MS AD / LDAP auth

**Comment by harshavardhana** [comment]
This is primarily because of LDAP normalization of DN; you need to start using new normalized DN and policies.

I hoped we could have provided a fallback solution here, but we can't have two representations of the same thing due to security constraints.

Can you share the LDAP DN string that you used to associate the policy with? 

// cc @donatello

**Comment by mari-arondeus** [comment]
Sure, let me grab the policy strings we use, but it sounds like this might be a RTFM (or RTFPatch Notes, as it were) issue in this case - is there any documentation you can point me to? If the issue is that we match the identity to multiple groups, that could easily be happening. There's a good bit of overlap between our teams.

Edit: This is what our mappings look like in the 2024-03-26 version. I believe it gets simplified / parsed down in the newer version.
```
Query time: 2024-04-01T18:45:09Z
Policy -> Entity Mappings:
  Policy: consoleAdmin
    Group Mappings:
      CN=NETWORKING,OU=Networking,OU=ITS,OU=Employees,DC=sub,DC=domain,DC=tld
      CN=SysAdmins,OU=Systems Administration,OU=ITS,OU=Employees,DC=sub,DC=domain,DC=tld
      OU=Networking,OU=ITS,OU=Employees,DC=sub,DC=domain,DC=tld
      OU=Systems Administration,OU=ITS,OU=Employees,DC=sub,DC=domain,DC=tld
```
(DC has been redacted for the sake of privacy, but I'm happy to share in a slack session or more private setting.)

**Comment by harshavardhana** [comment]
what is the userDN mapping?

**Comment by mari-arondeus** [comment]
> what is the userDN mapping?

`(sAMAccountName=%s)`

The full configuration is below, redacted for privacy as mentioned above:
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                enable: 1                                                                        │
│  group_search_base_dn: DC=sub,DC=domain,DC=tld  (environment)                                   │
│   group_search_filter: (member=%d)  (environment)                                               │
│        lookup_bind_dn: CN=Sappho LDAP,CN=Service Accounts,DC=sub,DC=domain,DC=tld  (environment)│
│           server_addr: sub-ldaps.domain.tld:636  (environment)                                  │
│user_dn_search_base_dn: DC=sub,DC=domain,DC=tld  (environment)                                   │
│ user_dn_search_filter: (sAMAccountName=%s)  (environment)                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by harshavardhana** [comment]
@mari-arondeus no i meant the final result of the LDAP DN as seen via `ldapsearch` can you show me a sample username?

**Comment by donatello** [comment]
@mari-arondeus You should be able to resolve this problem by recreating the mappings in the **newer** version, using something like `mc  idp ldap policy attach myminio consoleAdmin --group='CN=NETWORKING,OU=Networking,OU=ITS,OU=Employees,DC=sub,DC=domain,DC=tld'` - MinIO will use the normalized DN returned by the server. After that login should work.

The problem arises when such a group mapping already exists, but was done with a group DN (or user DN) value that is not the same as what the LDAP server returns. I will see if there is a good way to handle this.

**Comment by mari-arondeus** [comment]
@donatello this worked like a charm - I got a chance to test it before active hours today. However, for some reason, the ` mc idp ldap policy entities <instance>` command now returns nothing. How should I list what mappings I have assigned now?

**Comment by donatello** [comment]
I'm working on a fix for this.

**Comment by donatello** [comment]
This should be fixed by https://github.com/minio/minio/pull/19406

**Comment by harshavardhana** [comment]
and also #19421
