### ISSUE TITLE
S3 incompatibility issue?

### ISSUE THREAD

**Issue by hrstoyanov** [minio/minio#19381]
I am using  and [EclipseStore](https://eclipsestore.io/) 1.3.1 [AWS S3 plugin](https://docs.eclipsestore.io/manual/storage/storage-targets/blob-stores/aws-s3.html) which talks to a Minio local instance (using Java AWS SDK 2.25.18) , and this errors with ```s3.headObject 400 Bad Request``` a(s seen in the Minio WEB UI Trace panel).  EclipseStore internally does this:

```java
s3Client
                .headObject(HeadObjectRequest
                .builder()
                        .bucket("storage")
                        .key("/")
                .build());
```
for a bucket called "storage" that I created via the Minio web console.  Such  requests fail:
```
software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: 17C12D49CEE8C538, Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)
```

I filed a [bug with the EclipseStore team](https://github.com/eclipse-store/store/discussions/188)  you can check for more details, **but the issue is that this apparently works fine with AWS S3 and fails with Minio**?

## Expected Behavior
The above code should work.

## Current Behavior
In Minio fails the http head request with "s3.headObject 400 Bad Request", but this apparently works fine with AWS S3.

## Possible Solution
Nothing workaround so far.

## Your Environment
* Version used (`minio --version`):
```
minio version RELEASE.2024-03-26T22-10-45Z (commit-id=8bce123bba10a3880deb490bab219d5807da725a)
Runtime: go1.21.8 darwin/arm64
```
* Server setup and configuration:
The bucket is there.
```
minio start
```
* Operating System and version (`uname -a`):
MacOs Sonoma 14.4.1
```
Darwin Hristos-MacBook-Air.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 arm64
```

**Comment by harshavardhana** [comment]
Please make sure to enable path style.

**Comment by hrstoyanov** [comment]
Not sure what  you mean, but if it is "forcePathStyle" like below:
```
 var s3Client = S3Client
                .builder()
                .region(Region.AWS_ISO_GLOBAL)
                .forcePathStyle(true)
                .endpointOverride(URI.create("http://127.0.0.1:9000"))
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("xxx", "yyy"))).build();
```

Then  **NO, it does not work** .

This next one also does not work:
```java
s3Client = S3Client.builder()
                .endpointOverride(new URI(App.endpoint))
                .region(Region.US_EAST_1)
                .serviceConfiguration(e -> e.pathStyleAccessEnabled(true))
                .credentialsProvider(StaticCredentialsProvider.create(credentials))
                .build();
```

**Please re-open the issue**

**Comment by klauspost** [comment]
@hrstoyanov There are thousands of users that are able to make it work, so I'd guess the mistake is on your side - either in your setup or in the plugin.

"does not work" is not really any information we can use. A simple request like HeadObject will of course work, so something is wrong somewhere on your side. Feel free to ask in https://github.com/minio/minio/discussions - maybe see the trace of what i seing sent with `mc admin trace -v ALIAS` on your setup.

**Comment by harshavardhana** [comment]
```
s3Client
                .headObject(HeadObjectRequest
                .builder()
                        .bucket("storage")
                        .key("/")
                .build());
```

The issue is sending object key has `/` - there is no such object as `/`

Not sure what is being expected here

**Comment by hrstoyanov** [comment]
But such a head request is working in AWS S3 - have you tried it there? If Minio claims to be widely compatible with AWS3, that should not generate error in Minio

The idea behind this call, as per the EclipseStore design is, to verify that the bucket exists, or what lives inside it, and the EclipseStore team have  production deployments in AWS that proves such check work.

**Comment by harshavardhana** [comment]
> But such a head request is working in AWS S3 - have you tried it there? If Minio claims to be widely compatible with AWS3, that should not generate error in Minio
> 
> The idea behind this call, as per the EclipseStore design is, to verify that the bucket exists, or what lives inside it, and the EclipseStore team have production deployments in AWS that proves such check work.

It is first of all a wrong expectation here. There is no such object called '/' on MinIO.

This is not a bucket exists check for that there is a separate API. You are calling headobject to verify headbucket.

Perform the right API call and you will be fine.

EclipseStore is buggy here and must be fixed to use the right API.
