### ISSUE TITLE
Signature Mismatch Error When Accessing MinIO Behind an Nginx Proxy from Different Computers

### ISSUE THREAD

**Issue by fengjun2022** [minio/minio#19394]
Bucket permissions: Access Policy = public
Deployment method: Docker RootLess

### Problem Description
Encountering a `SignatureDoesNotMatch` error when trying to access a MinIO server proxied by nginx from different computers and the current computer. After referring to the Minio documentation for nginx proxy, the nginx was modified as follows, please note that the current server_name is written for my local testing purposes.
Here is the nginx configuration:
```
worker_processes auto;
user nginx;  # Set Nginx work process user to nginx
events {
    worker_connections 2048;
}

http {

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 9010;
        listen  [::]:9010;
        server_name 127.0.0.1;
        client_max_body_size 40M;
   # Allow special characters in headers
       ignore_invalid_headers off;
   # Allow any size file to be uploaded.
   # Set to a value such as 1000m; to restrict file size to a specific value

   # Disable buffering
       proxy_buffering off;
       proxy_request_buffering off;   


     location / {
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header Host $http_host;

   proxy_connect_timeout 300;
   # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   chunked_transfer_encoding off;

   proxy_pass http://localhost:9000;
        }
        
### Error Details
When I try to access the web address: 127.0.0.1:9010
I encounter the following error:
<Error>
<script/>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>1.png</Key>
<BucketName>testbucket</BucketName>
<Resource>/testbucket/1.png</Resource>
<RequestId>17C26C56384D1FE0</RequestId>
<HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId>
</Error>

### 
```
Steps Tried to Resolve
Verified the correct access key and secret key were being used.
Checked the MinIO server's network access permissions to ensure firewall and security group rules allow external access.
Tested local port on current computer and accessed it.
Attempted access on different computers using the same client configuration, including the correct server address, port, access key, and secret key.
Ensured all computers attempting access had synchronized system time.
Requesting Assistance
Would appreciate any insights into common configurations or steps that might have been missed, especially regarding configurations needed for accessing from different devices. Any advice on how to resolve the signature mismatch issue would be greatly appreciated.

Environment Information
Docker MinIO version: quay.io/minio/minio latest
Operating System: <docker>

**Comment by fengjun2022** [comment]
I enclose my compose `
version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    user: "${UID}:${GID}"
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - service

networks:
  service:
    external: true



`

**Comment by jiuker** [comment]
https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
check this doc plz.

**Comment by RuBAN-GT** [comment]
Hey everyone,
If I have minio under another port (domain:9500) or path (for example domain/minio), how I can configure my server and client in order to have valid signature calculation?

I tried to add MINIO_SERVER_URL but I still have the error from this issue.

Thanks in advance!
CC: @jiuker

**Comment by n9yty** [comment]
Having this problem as well, seems something in my nginx config but despite having tried numerous suggested "fixes" nothing has worked yet. I keep looking.

**Comment by ShinChven** [comment]
I solved this problem by following this answer: https://stackoverflow.com/a/52598158/2108080
