### ISSUE TITLE
Notification Events on Replicas

### ISSUE THREAD

**Issue by Foxcapades** [minio/minio#19407]
## Expected Behavior

Object events are fired for objects created/deleted/etc by replication.

## Current Behavior

Object events are not fired for objects created/deleted/etc by replication.

## Context

According to replies on AWS re:Post to [this question](https://repost.aws/questions/QUWy4DeorXSkOOm5otiBZPyg/does-s3-object-replication-trigger-objectcreated-event) and [this question](https://repost.aws/questions/QUvWVStqZwTHOsBUdVNVc-ww/questions/QUvWVStqZwTHOsBUdVNVc-ww/does-s3-same-region-replication-trigger-s3-event-notifications-in-the-destination-bucket), we should be able to expect `s3:ObjectCreated:*`, `s3:ObjectRemoved:*`, etc. events fired on replication target instances for objects that have been replicated.

Additionally, the official MinIO replication documentation [here](https://github.com/minio/minio/blob/master/docs/bucket/replication/README.md#replicating-deletes) itself strongly implies that we can expect events on replication saying (in the context of replication):

> On the target bucket, `s3:PutObject` event shows `X-Amz-Replication-Status` status of `REPLICA` in the metadata.

However, in [this thread](https://github.com/minio/minio/issues/17582) this difference in behavior between MinIO and S3 is called "by design".  This ticket also references [this PR](https://github.com/minio/minio/pull/11683).

The linked PR makes a significant, and what I would consider to be breaking, change to the way MinIO behaves, however it is labelled as a bug fix.

It seems the decision was made to make MinIO depart from S3 in this behavior but it doesn't appear to be documented anywhere but in GitHub issues.

If I'm understanding this change correctly, it removes the ability for users to have isolated, self-contained service stacks that are dependent on a singular replica instance of MinIO.  The suggested alternative of "listen to source replication completion events" means that, at least for site replication, each individual system must know about and subscribe to events from all potential source MinIO instances.

## Your Environment

* `Version: RELEASE.2024-03-15T01-07-19Z (go1.21.8 linux/amd64)`
* `Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Yeah, these changes are made to reduce the volume of events generated, as we had customers who wished to avoid double events. 

All our customers wanted this behavior; AWS S3 has overdone many things. We do not blindly make these changes to avoid repeating their mistakes for compatibility.

If you don't like this behavior, you can send a PR, and we can take a look—there are no commitments to merging it.

If you want to have a say in our technical decisions, if you want to keep events for a replica as well feel free to become a customer and let us know you are interested in retaining the ability we may consider your request.
