### ISSUE TITLE
Common prefixes not listed when using CIFS/SMB volumes (since `2024-03-03`)

### ISSUE THREAD

**Issue by adamcharnock** [minio/minio#19418]
## Expected Behavior

When backed by a CIFS/SMB volume, `mc ls` should common prefixes.

This expected behaviour was present up-to and including `RELEASE.2024-02-26T09-33-48Z`.

```
❱ mc ls  main/test/
[2024-04-05 11:30:20 UTC]     0B prefix/
❱ 
```

## Current Behavior

When backed by a CIFS/SMB volume, `mc ls` fails to list common prefixes. This is also true via the s3 API, and via the web console UI.

This current and unexpected behaviour was introduced in `RELEASE.2024-03-03T17-50-39Z`.

```
❱ mc ls  main/test/
❱
```

Note that uploads still succeed, and objects can still be accessed via their full path.

## Possible Solution

List common prefixes when backed by a CIFS/SMB volume. 

## Steps to Reproduce (for bugs)

1. Create samba-backed Minio tenant (I'm using 4 servers, each with 1 volume, using Minio Operator)
2. Create a new bucket (`my-bucket`)
3. Upload a file to a prefix within the bucket (`my-bucket/prefix/file.txt`)
4. Run `mc ls  main/my-bucket/`, note that `prefix` is not listed

## Context

Creating a small (20TB) but expandable object store backed by Hetzner storageboxes. This testing was done on a virtualised kubernetes deployment of 3 notes, prior to deployment to bare-metal hardware.

I spent a few days on this and it drove me nuts 🥜

## Regression

This current and unexpected behaviour was introduced in `RELEASE.2024-03-03T17-50-39Z`.

## Your Environment

* Version used: `RELEASE.2024-03-03T17-50-39Z`, but issue also present in latest release (`RELEASE.2024-03-30T09-41-56Z`)
* Server setup and configuration: 4x minio servers deployed via MinIO Operator
* Operating System and version (`uname -a`):

### Trace

Trace when listing a bucket (via the console UI) that fails to list prefixes:

```
2024-04-05T11:49:08.470 [200 OK] s3.ListObjectsV2 minio-pool-sba-2.minio-hl.minio-system.svc.cluster.local:9000/test/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=  10.50.0.1        5.994ms      ⇣  5.969164ms  ↑ 114 B ↓ 291 B
2024-04-05T11:49:08.493 [200 OK] s3.GetBucketLocation minio-pool-sba-1.minio-hl.minio-system.svc.cluster.local:9000/test/?location=  10.50.0.1        910µs       ⇣  895.521µs  ↑ 114 B ↓ 128 B
2024-04-05T11:49:08.494 [404 Not Found] s3.GetBucketPolicy minio-pool-sba-1.minio-hl.minio-system.svc.cluster.local:9000/test/?policy=  10.50.0.1        604µs       ⇣  593.916µs  ↑ 114 B ↓ 312 B
2024-04-05T11:49:08.495 [404 Not Found] s3.GetBucketTagging minio-pool-sba-1.minio-hl.minio-system.svc.cluster.local:9000/test/?tagging=  10.50.0.1        131µs       ⇣  123.541µs  ↑ 114 B ↓ 299 B
```

### Lowest version which causes this issue:

```
bash-5.1$ minio --version
minio version RELEASE.2024-03-03T17-50-39Z (commit-id=09b0e7133ddcb2e2a26a36f2caed59a7b7bc7c88)
Runtime: go1.21.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

## Tenant definition

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: "2024-04-05T11:06:34Z"
  generation: 10
  name: minio
  namespace: minio-system
  resourceVersion: "14357181"
  uid: 76bcbc68-ef01-4454-97af-d58d0112c284
spec:
  configuration:
    name: minio-env-configuration
  credsSecret:
    name: minio-secret
  exposeServices:
    console: false
    minio: false
  image: minio/minio:RELEASE.2024-03-03T17-50-39Z
  pools:
  - affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: v1.min.io/tenant
                operator: In
                values:
                - minio
              - key: v1.min.io/pool
                operator: In
                values:
                - pool-sba
            topologyKey: kubernetes.io/hostname
          weight: 100
    name: pool-sba
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "0.025"
        memory: 0.1Gi
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    volumesPerServer: 1
  requestAutoCert: false
  users:
  - name: minio-user-adam
status:
  availableReplicas: 4
  certificates:
    autoCertEnabled: false
    customCertificates: {}
  currentState: Initialized
  drivesOnline: 4
  healthStatus: green
  pools:
  - legacySecurityContext: false
    ssName: minio-pool-sba
    state: PoolInitialized
  provisionedUsers: true
  revision: 0
  syncVersion: v5.0.0
  usage:
    capacity: 21990224756736
    rawCapacity: 4294967296
    rawUsage: 7798784
    usage: 7798784
  writeQuorum: 3
```

# CIFS mount options

I first used:

```
- dir_mode=0777
- file_mode=0777
- uid=1000
- gid=1000
- seal
# Loose cache assumes only singe process accessing resource,
# which in this case should be ok
- cache=loose
- noacl
- noperm
- actimeo=600
```

In an effort to solve this issue I then got more conservative, and tried to match the permissions MinIO set when creating files on a local volume (sadly this did not help):

```
- dir_mode=02755
- file_mode=0755
- uid=1000
- gid=1000
- seal
- cache=none
- actimeo=600
 ```

**Comment by harshavardhana** [comment]
yeah this is because of an optimization done for XFS like filesystems. CIFS/SMB they don't provide the same semantics.

**Comment by adamcharnock** [comment]
Wow, that was *fast*! 👏 Thank you.
