### ISSUE TITLE
mc alias set fails with "connection refused" after successful health check

### ISSUE THREAD

**Issue by nirs** [minio/minio#19412]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

After successful health check, accessing minio using mc should not fail with connection refused.

## Current Behavior

Accessing minio when setting mc alias may fail with connection refused.

Maybe the health endpoint reports success before minio is completely ready?

We have seen one failure in 250 runs during a stress test.

## Possible Solution

Retry steps 2 and 3 until they succeed.

## Steps to Reproduce (for bugs)

1. Deploy minio using https://github.com/RamenDR/ramen/blob/main/test/addons/minio/minio.yaml
2. Wait until the deployment is rolled out
3. Try to access the health endpoint until we get 200 OK (Based on https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html#node-liveness)

   ```
   curl -I https://minio.example.net:9000/minio/health/live
   ```

4. Try to set mc alias:

   ```
   mc alias set dr1 ACCESS_KEY SECRET_KEY
   ```

The command may randomly fail (1 failure in 250 runs):

```
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://192.168.122.200:30000/probe-bsign-uhfgywjins9p99ll0dpi4btx3ecb3e/?location=": dial tcp 192.168.122.200:30000: connect: connection refused.
```

Was found in a stress test, we did not collect any logs from the system and it was destroyed right after the failure.

We can collect requested data for a future run. For now we added retries so this does not fail CI builds.

Logs from the failed run:
```
2024-04-03 21:41:53,029 INFO    [dr1/2] Running addons/minio/start
2024-04-03 21:41:53,151 DEBUG   [dr1/2] Deploying minio
2024-04-03 21:41:53,396 DEBUG   [dr1/2] namespace/minio created
2024-04-03 21:41:53,414 DEBUG   [dr1/2] persistentvolumeclaim/minio-storage-pvc created
2024-04-03 21:41:53,429 DEBUG   [dr1/2] deployment.apps/minio created
2024-04-03 21:41:53,481 DEBUG   [dr1/2] service/minio created
2024-04-03 21:41:53,485 DEBUG   [dr1/2] Waiting until minio is rolled out
2024-04-03 21:41:53,555 DEBUG   [dr1/2] Waiting for deployment "minio" rollout to finish: 0 of 1 updated replicas are available...
2024-04-03 21:42:07,710 DEBUG   [dr1/2] deployment "minio" successfully rolled out
2024-04-03 21:42:07,714 DEBUG   [dr1/2] Waiting until minio service is available
2024-04-03 21:42:07,899 DEBUG   [dr1/2] minio service is available in 0.01 seconds
2024-04-03 21:42:07,899 DEBUG   [dr1/2] Setting mc alias dr1
2024-04-03 21:42:08,209 ERROR   Command failed
Traceback (most recent call last):
  ...
drenv.commands.Error: Command failed:
   command: ('addons/minio/start', 'dr1')
   exitcode: 1
   error:
      Traceback (most recent call last):
        ...
      drenv.commands.Error: Command failed:
         command: ('mc', 'alias', 'set', 'dr1', 'http://192.168.122.200:30000', 'XXX-1', 'XXX-2')
         exitcode: 1
         error:
            mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://192.168.122.200:30000/probe-bsign-uhfgywjins9p99ll0dpi4btx3ecb3e/?location=": dial tcp 192.168.122.200:30000: connect: connection refused.
```

## Context

We use minio in a test environment, used in ramen CI.

## Your Environment

minikube based clusters, using latest minikube (1.32.1).

**Comment by shtripat** [comment]
I think `curl -I https://minio.example.net:9000/minio/health/ready` would give you actual readiness of MinIO to serve. It initially takes few secs to initialize the nodes of the cluster and setting up communication between the nodes and figuring out drives to form erasure sets etc.

**Comment by nirs** [comment]
Thanks @shtripat! trying this.

Any reason this is not documented in https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html?

**Comment by harshavardhana** [comment]
you should be using `mc ready` @nirs  not `curl`

**Comment by nirs** [comment]
> you should be using `mc ready` @nirs not `curl`

@harshavardhana I already tried `mc ready`, but it wants an alias, but to set an alias, I need to do a ready check, otherwise `mc alias set` fails.

```
$ mc ready http://192.168.39.171:30000
mc: <ERROR> Couldn't construct anonymous client for `http://192.168.39.171:30000`. Use `mc alias set mycloud http://192.168.39.171:30000 ...` to add an alias. Use the alias for S3 operations.
```

I'm not using curl, the health check is here:
https://github.com/RamenDR/ramen/blob/main/test/drenv/minio.py

**Comment by ravindk89** [comment]
https://min.io/docs/minio/linux/reference/minio-mc/minio-client-settings.html#host-credentials

This might work by setting `MC_HOST_tmpALIAS=hostname -c 'mc ready tmpALIAS'` - if so I can look to update our docs to call this out for anyone using `mc ready` as a readiness interface.

**Comment by nirs** [comment]
> https://min.io/docs/minio/linux/reference/minio-mc/minio-client-settings.html#host-credentials
> 
> This might work by setting `MC_HOST_tmpALIAS=hostname -c 'mc ready tmpALIAS'` - if so I can look to update our docs to call this out for anyone using `mc ready` as a readiness interface.

Cool! it works:

```
$ MC_HOST_dr1=http://192.168.122.185:30000 mc ready dr1
The cluster is ready
```

**Comment by harshavardhana** [comment]
> > you should be using `mc ready` @nirs not `curl`
> 
> @harshavardhana I already tried `mc ready`, but it wants an alias, but to set an alias, I need to do a ready check, otherwise `mc alias set` fails.
> 
> ```
> $ mc ready http://192.168.39.171:30000
> mc: <ERROR> Couldn't construct anonymous client for `http://192.168.39.171:30000`. Use `mc alias set mycloud http://192.168.39.171:30000 ...` to add an alias. Use the alias for S3 operations.
> ```
> 
> I'm not using curl, the health check is here: https://github.com/RamenDR/ramen/blob/main/test/drenv/minio.py

You need to use env for that

```
MC_HOST_alias=http://key:secret@host:port/ mc ready alias/
```

**Comment by nirs** [comment]
One issue with `mc ready`, I don't see any way to add a timeout.

Example using wrong port so it will never succeed:

```
$ MC_HOST_tmp=http://192.168.122.183:30001 mc ready tmp
The cluster is unreachable: Get "http://192.168.122.183:30001/minio/health/cluster": dial tcp 192.168.122.183:30001: connect: no route to host
The cluster is unreachable: Get "http://192.168.122.183:30001/minio/health/cluster": dial tcp 192.168.122.183:30001: connect: no route to host
...
```

I need to control the timeout, so if minio is broken the build will fail quickly and rebuild the clusters.

**Comment by harshavardhana** [comment]
> One issue with `mc ready`, I don't see any way to add a timeout.
> 
> Example using wrong port so it will never succeed:
> 
> ```
> $ MC_HOST_tmp=http://192.168.122.183:30001 mc ready tmp
> The cluster is unreachable: Get "http://192.168.122.183:30001/minio/health/cluster": dial tcp 192.168.122.183:30001: connect: no route to host
> The cluster is unreachable: Get "http://192.168.122.183:30001/minio/health/cluster": dial tcp 192.168.122.183:30001: connect: no route to host
> ...
> ```
> 
> I need to control the timeout, so if minio is broken the build will fail quickly and rebuild the clusters.

you mean like this 

```
timeout 1m mc ready alias/
```
?

**Comment by nirs** [comment]
> > I need to control the timeout, so if minio is broken the build will fail quickly and rebuild the clusters.
> 
> you mean like this
> 
> ```
> timeout 1m mc ready alias/
> ```

This can work, but we will have to run it like this to ensure we can cleanup all child processes on errors:

    MC_HOST_tmp=http://192.168.122.183:30000 timeout --foreground 1m mc ready tmp

And hope that mc never exit with exit code 124.

Accessing http://host/minio/live/ready directly seems easier for our use case.
