### ISSUE TITLE
[linux]Memory continued to grow, no error log was found 

### ISSUE THREAD

**Issue by huozhirui** [minio/minio#19429]
After upgrading the minio version from RELEASE.2023-09-23T03-47-50Z to RELEASE.2024-03-26T22-10-45Z, the data has not changed much, but the single machine memory usage is high
![image](https://github.com/minio/minio/assets/55824382/2c3c4d22-1783-4e7c-9663-bd32dad44a62)

**Comment by harshavardhana** [comment]
Incomplete issue filing, closing.
