### ISSUE TITLE
Millions of files with reduced ECS (14:2) instead of standard (12:4)

### ISSUE THREAD

**Issue by mat-gas** [minio/minio#19438]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

cluster with 4 nodes and 24 disks in each ==> 6 sets of 16 disks

currently configured as EC:4

4 drives down on 1 node evenly impacting 4 sets (2 sets wsith full 16 drives, 4 sets with only 15 drives)

new file created in a set with full 16 disk get a ECS of 12:4 (12 data shards, 4 parity shards)
new file created in a set with reduced nb of disk get a ECS of 11:5

when cluster is back to "normal", all files should have a ECS of 12:4

## Current Behavior

currently, new files are 12:4 or 11:5, but we have a lot of files with ECS 14:2 (we don't know how those were created)

those files have no specific retention metadata (no RRS, nothing)

example xl.meta output using xl-meta command on one of the shards on 1 node with EcM:14 and EcN:2 (whereas those are 12:4 or 11:5 on newly created files)

```
{
  "Versions": [
    {
      "Type": 1,
      "V2Obj": {
        "CSumAlgo": 1,
        "DDir": "LTe0khgaTl2KtgoLqNh9DQ==",
        "EcAlgo": 1,
        "EcBSize": 1048576,
        "EcDist": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          1,
          2
        ],
        "EcIndex": 11,
        "EcM": 14,
        "EcN": 2,
        "ID": "AAAAAAAAAAAAAAAAAAAAAA==",
        "MTime": 1651915502501920624,
        "MetaSys": {
          "x-minio-internal-inline-data": "dHJ1ZQ=="
        },
        "MetaUsr": {
          "content-type": "application/octet-stream",
          "etag": "73ed9c430daca008f67b6a11e41f1397"
        },
        "PartASizes": [
          148992
        ],
        "PartETags": [
          ""
        ],
        "PartNums": [
          1
        ],
        "PartSizes": [
          148992
        ],
        "Size": 148992
      }
    }
  ]
}
```

## Possible Solution

- low priority thread that should ensure files, if no specific metadata has been set, should honor the current/safe retention config?
- add a parameter to `mc admin heal` command to force this check? 

if this is intended, how can we manually fix this on our end?

## Steps to Reproduce (for bugs)

don't know how we ended up like this, but we have millions of files with those reduced parity settings

## Your Environment

minio RELEASE.2024-03-30T09-41-56Z

**Comment by harshavardhana** [comment]
this is an expected EC upgrade. We added a parity to make sure of the loss in HA. If you don't want this default behavior, you may set the value

```
mc admin config set alias/ storage_class optimized=capacity
```

If you choose capacity-optimized, it will automatically turn off parity upgrade.

PS: Your issue title is wrong it is 12:4 becomes 11:5 not 14:2 

> example xl.meta output using xl-meta command on one of the shards on 1 node with EcM:14 and EcN:2 (whereas those are 12:4 or 11:5 on newly created files)

yeah these would have been created way before, someone who had set the value as EC:2. Check the values value via 

```
mc admin config get alias/ storage_class
```

If not force it in your env MINIO_STORAGE_CLASS_STANDARD=EC:4

**Comment by harshavardhana** [comment]
> if this is intended, how can we manually fix this on our end?

It is not intended; there is a way to re-do the parity. If you want production-level help, please subscribe to https://min.io/pricing

As they say, don't drive your car without insurance.
