### ISSUE TITLE
Deprecate `MINIO_SERVER_URL`

### ISSUE THREAD

**Issue by ravindk89** [minio/minio#19462]
**Is your feature request related to a problem? Please describe.**

https://github.com/minio/console/issues/3255

With the above issue, the Console should no longer require `MINIO_SERVER_URL` for determining the correct hostname to use for generating presigned URLs.

Furthermore, in discussion with Engineering, the Console and MinIO Server have tighter communication behavior and also do not rely on `MINIO_SERVER_URL` for any normal functionality. This may also close the need to specify this value for reverse proxy or load balanced setups where TLS cert SANs do not cover the MinIO Server IP.

Therefore it is possible that we can deprecate and remove this environment variable in the next release.

https://github.com/minio/minio/blob/master/cmd/common-main.go#L706-L721 <- the current codepath allocates this variable value to `globalMinIOEndpointUrl`  and `globalMinioEndpoint` respectively. Those values are [checked against](https://github.com/search?q=repo%3Aminio%2Fminio%20globalMinioEndpoint&type=code), but if the default value in absence of `MINIO_SERVER_URL` is sufficient for most setups, then we should be OK.

**Describe the solution you'd like**

Mark as deprecated and remove `MINIO_SERVER_URL`

**Describe alternatives you've considered**

Simply remove the documentation references to the variable, but keep it in code in case we do need it for certain edge cases

**Comment by allanrogerr** [comment]
@ravindk89  The env var `MINIO_SERVER_URL` is relevant in scenarios where the minio server and minio console are no longer colocated on a mutual localhost. This var enabled the minio console to communicate with the minio server. These scenarios are still functional and documented here: https://min.io/docs/minio/linux/administration/minio-console.html#configuration

If these scenarios were defined as invalid setups, then `MINIO_SERVER_URL` would no longer have any meaning. 

Your thoughts?

**Comment by ravindk89** [comment]
> The MinIO Console connects to the MinIO Server using an IP address by default. For example, when the MinIO Server starts up, the server logs include a line API: https://<IP ADDRESS 1> https://<IP ADDRESS 2>. The MinIO Console defaults to connecting using <IP ADDRESS 1>.

So I _think_ at some point this changed, and Console talks to Server w/o consideration of that.

If that _is_ true, and we are no longer bound by issues of Console attempting to talk to Server over some other interface, then I think this doesn't matter anymore?

@harshavardhana we had spoken at least briefly about this, but I do want to be very careful in this. To my knowledge *today*, Console and Server comms are no longer bound by IP/TLS/Hostname-related barriers as they were when that doc was written

**Comment by allanrogerr** [comment]
It also looks like a valid `MINIO_SERVER_URL` is required to properly format a share URL; and not use private IP e.g. 127.0.0.1. Not sure where this is documented.

**Comment by harshavardhana** [comment]
> It also looks like a valid `MINIO_SERVER_URL` is required to properly format a share URL; and not use private IP e.g. 127.0.0.1. Not sure where this is documented.

Not needed anymore

**Comment by allanrogerr** [comment]
Backlogged until discussion with wider team.

**Comment by harshavardhana** [comment]
https://github.com/minio/console/pull/3319 this is the first PR

**Comment by harshavardhana** [comment]
This is mostly complete now; we can stop talking about MINIO_SERVER_URL since the latest release.

**Comment by ravindk89** [comment]
Fantastic @harshavardhana - that's a great relief :)
