### ISSUE TITLE
add-svcacct job broken, Need to release new helm version

### ISSUE THREAD

**Issue by mananpreetsingh** [minio/minio#19461]
New helm chart version should have pushed to fix this issue:
https://github.com/minio/minio/issues/19314

## Expected Behavior
make-svcacct job to work properly.

## Current Behavior

Getting following error if deployed using latest helm charts:
```
Connecting to MinIO server: http://minio:9000                                                                                                                                                                    
Added `myminio` successfully.                                                                                                                                                                                   
/config/add-svcacct: line 85: sed: command not found
```

## Possible Solution
Release new helm chart version with latest code.

## Steps to Reproduce (for bugs)
Create a minio deployment using the community helm chart and specifying the respective values for an user to be created, with credentials from an existing secret.

## Context
Setting up the minio server worked fine. However, the make-svcacct job failed. Not creating a svcacct as specified as a result.

## Regression
Yes https://github.com/minio/mc/pull/4725

## Your Environment
* helm chart version: 5.1.0

**Comment by jiuker** [comment]
@harshavardhana We should release helm-release. 
@mananpreetsingh You can use main branch `helm` dir instead.

**Comment by mananpreetsingh** [comment]
> @mananpreetsingh You can use main branch `helm` dir instead.

@jiuker  Sorry I might be missing something here, How am I suppose to use main branch helm ?

Do you mean clone main branch on local and refrence the helm from local?

If yes we use argo to deploy charts, it won't be possible in that case I guess.

**Comment by jiuker** [comment]
> > @mananpreetsingh You can use main branch `helm` dir instead.
> 
> @jiuker Sorry I might be missing something here, How am I suppose to use main branch helm ?
> 
> Do you mean clone main branch on local and refrence the helm from local?
> 
> If yes we use argo to deploy charts, it won't be possible in that case I guess.


At present, you can only use the `helm` directory. The update to the `helm-release` directory does not include this fix. That means `helm chart version: 5.1.0` is out of date. @mananpreetsingh

**Comment by mananpreetsingh** [comment]
@harshavardhana Any idea when the new release will get deployed?

**Comment by mmoscher** [comment]
@harshavardhana and @jiuker any news when a new helm release will be available? We've got the same issue.
Let me know if there is anything we can support you with!
