### ISSUE TITLE
No such IDP configuration exists Google Oauth2 

### ISSUE THREAD

**Issue by fatsolko** [minio/minio#19474]
Installed minio by helm chart  14.1.7 and trying to setup google oauth2
Got an error.
![Screenshot_6](https://github.com/minio/minio/assets/76652885/3f7cc3fa-0923-464d-af2a-be85688ee9fe)

https://accounts.google.com/.well-known/openid-configuration 
is accessible from pod 
![image](https://github.com/minio/minio/assets/76652885/fcb4a09f-2271-4a1f-8305-0faedd71a48f)

**Comment by harshavardhana** [comment]
Ignored issue template blatantly

- No mention of what MinIO version
- Hidden information about the endpoints in IDP
- 14.1.7 I'm unsure which helm version this is and from where.

Closing the issue as blatantly incomplete, left for us to imagine the setup.
