### ISSUE TITLE
删除的文件没有释放空间怎么解决

### ISSUE THREAD

**Issue by Luoganggang** [minio/minio#19484]
问题：
用mc工具删除大目录文件，但是空间没有立即释放导致存储空间爆满
删除命令：mc rm -r --dangerous --force

分析：
排查删除的文件缓存到了.minio.sys/tmp/.trash/垃圾目录，要过比较久的时间才释放，如何禁用清理文件的缓存或调整缓存释放时间

**Comment by jiuker** [comment]
English first. Will delete it next GC time.

**Comment by Luoganggang** [comment]
> English first. Will delete it next GC time.

How to disable cache cleaning for files or adjust cache release time

> English first. Will delete it next GC time.

Okay, is it possible to disable file cache cleaning or adjust cache release time through configuration?

**Comment by Luoganggang** [comment]
Okay, is it possible to disable file cache cleaning or adjust cache release time through configuration?

**Comment by jiuker** [comment]
5min
