### ISSUE TITLE
LDAP normalization for chinese names get rejected by the LDAP server

### ISSUE THREAD

**Issue by Aliroe** [minio/minio#19485]
中文：更新版本 0406 时，出现与 LDAP 不兼容的情况。能看看是什么问题是吗？
English：When updating version 0406, an incompatibility with LDAP occurred. Can you see what the problem is?
![image](https://github.com/minio/minio/assets/40637160/3fc276f6-2a50-4ba8-8c64-d034e40c2909)
![image](https://github.com/minio/minio/assets/40637160/40df1494-d4f8-4946-820c-0226291ad1a4)

system version：centos7.9,
Using the Linux version of the minio binary：[RELEASE.2024-04-06T05-26-02Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-04-06T05-26-02Z)

**Comment by jiuker** [comment]
What's the item configed? @Aliroe

**Comment by harshavardhana** [comment]
yeah its the normalized Ldap DN which is returning an error from the LDAP server. // cc @donatello

**Comment by harshavardhana** [comment]
This cannot be addressed meaningfully; the LDAP server is misconfigured here, and it seems to be rejecting normalized DNs.

Closing this as nonactionable, please check why your LDAP server returns an error.

**Comment by Aliroe** [comment]
"Does the MinIO version 2024-01-11 support compatibility with the 2024-5-10 version if I roll back? Additionally, is it compatible afterwards? The log content is as follows: May 20 15:51:12 mycluster01.zytk.com run.sh[26216]: Error: Unable to initialize backend: Storage resources are insufficient for the read operation .minio...rapError May 20 15:51:12 mycluster01.zytk.com run.sh[26216]: 6: internal/logger/logger.go:259:logger.LogIf()"
![image](https://github.com/minio/minio/assets/40637160/a4e12cee-0140-44e8-a26b-10a48a440d97)

**Comment by Aliroe** [comment]
> This cannot be addressed meaningfully; the LDAP server is misconfigured here, and it seems to be rejecting normalized DNs.
> 
> Closing this as nonactionable, please check why your LDAP server returns an error.

Presently deployed in binary mode, is it possible for the MinIO version to fallback? Currently, the 24-01-11 version can be utilized subsequent to redeployment, yet cannot be employed after falling back from the 2024-5-10 version. Is there any solution that can comprehensively address this issue?

**Comment by Aliroe** [comment]
```
WARNING: Detected Linux kernel version older than 4.0.0 release, there are some known potential performance problems with this kernel version. MinIO recommends a minimum of 4.x.x linux kernel version for best performance
ERROR Unable to initialize backend: decodeXLHeaders: Unknown xl header version 2
```



"""

Upon commencing with an individual command, this error shall be presented.
"""
