### ISSUE TITLE
can't add a new node to the cluster

### ISSUE THREAD

**Issue by 1360running** [minio/minio#19498]
my cluster with 2 nodes (node1, node2), 3 drivers per node.
this is my /etc/default/minio file for both nodes:

`MINIO_VOLUMES="http://node{1...2}.local:9000/mnt/disk{1...3}"`
`MINIO_OPTS="--console-address :9001"`
`MINIO_ROOT_USER=minioadmin`
`MINIO_ROOT_PASSWORD=minio-secret-key-CHANGE-ME`
`MINIO_SERVER_URL="http://node1.local:9000"`
`MINIO_CONFIG_ENV_FILE=/etc/default/minio`

then later i added a new node (node3)with 6 drivers to the cluster.
this is my /etc/default/minio on the new node, and i also changed $MINIO_VOLUMES on node1 and node2:

`MINIO_VOLUMES="http://node{1...2}.local:9000/mnt/disk{1...3}" http://node3.local:9000/mnt/disk{1...6}`
`MINIO_OPTS="--console-address :9001"`
`MINIO_ROOT_USER=minioadmin`
`MINIO_ROOT_PASSWORD=minio-secret-key-CHANGE-ME`
`MINIO_SERVER_URL="http://node3.local:9000"`
`MINIO_CONFIG_ENV_FILE=/etc/default/minio`

when i restart 2 nodes (==>OK) but i can't start minio's service on node3, the log says: 
> Expected same MINIO_ environment variables and values across all servers: Mismatching environment values: [MINIO_SERVER_URL]

so i changed `MINIO_SERVER_URL="http://node3.local:9000"` to `MINIO_SERVER_URL="http://node1.local:9000"` on node3 and try to start service again but failed. the log still says:
> Expected same MINIO_ environment variables and values across all servers: Mismatching environment values: [MINIO_SERVER_URL]

after many hours trying to find something wrong, i find this in the --json config:
![d1aaaa](https://github.com/minio/minio/assets/166986460/9380c1fb-3255-4b68-9be5-73f619e4cb8f)

the $MINIO_SERVER_URL in node3's section still point to `node3.local:9000` although i changed it point to `node1.local:9000`
maybe this is why i can't start minio's service on node3.
i also tried to remove node3 and add it again but strange, it didn't reload the config, the $MINIO_SERVER_URL in node3's section still point to `node3.local:9000` 
so i rebooted 3 nodes and started the service again. WOW it was up, no problem, checked the --json config, and now it loads the new config:
![cr1](https://github.com/minio/minio/assets/166986460/dc6a5205-35ac-4a4d-ab2a-ef2f76238a71)

![d211](https://github.com/minio/minio/assets/166986460/8df418b5-7ccc-4859-9e0d-eb372fc3a040)

i don't know if this is a bug or something but my question is how can i reload the config without rebooting the servers?
thank you guys.

**Comment by harshavardhana** [comment]
You can't expand by using one node at a time. https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html
