### ISSUE TITLE
Enforce maximum expiration date for access keys

### ISSUE THREAD

**Issue by vfauth** [minio/minio#19493]
**Is your feature request related to a problem? Please describe.**
In my company we use MinIO with OIDC for user management, so users do not exist locally in MinIO. When a user loses permissions or is disabled, if they created an access key beforehand, they will still be able to access data they shouldn't.

To mitigate this issue, I would like to enforce a maximum validity of 7 days for all access keys created on the MinIO instance.

**Describe the solution you'd like**
A global setting would allow the administrator to define a maximum duration in days for access key validity. New access keys must respect this when created.

**Describe alternatives you've considered**
I know about STS, sadly it is more complex to use and many users just want a graphical UI to generate their access key.

**Comment by harshavardhana** [comment]
> In my company we use MinIO with OIDC for user management, so users do not exist locally in MinIO. When a user loses permissions or is disabled, if they created an access key beforehand, they will still be able to access data they shouldn't.


For this you need to provide us access to your user info endpoint. With this we will expire those dangling credentials automatically you do not need a top level expiration.

This is verified every so often

https://github.com/minio/minio/blob/master/cmd/iam.go#L1314

Regarding upper level expiration we allow that with STS.

https://github.com/minio/pkg/blob/75493e8b5589139d187ce9b3cee935adf73a9e8d/policy/sts-action.go#L55

Your use-case is already satisfied by the expiration that happens automatically.
