### ISSUE TITLE
Incorrect handling of conditions. Tracing is not detailed.

### ISSUE THREAD

**Issue by bartwork** [minio/minio#19520]
## NOTE
We use file loading from the froala-editor, from RubyOnRails application: https://froala.com/wysiwyg-editor/docs/options/#imageUploadToS3
Uploading to the YandexCloud bucket works fine, uploading to minio **with the same condition settings** gives an error:
**Access Denied. (Each form field that you specify in a form (except Awsaccesskeyid, Signature) must appear in the list of conditions.)**

## Expected Behavior
Files should download without errors.

## Current Behavior
Files are not downloading. Error - **Access Denied. (Each form field that you specify in a form (except Awsaccesskeyid, Signature) must appear in the list of conditions.)**

## Possible Solution
Possibly incompatible conditional syntax in minio.

![request](https://github.com/minio/minio/assets/5875364/f4dfd75b-4541-4b03-8bb4-5236e8714224)
<img width="469" alt="policy_code" src="https://github.com/minio/minio/assets/5875364/cebf341b-62e5-4079-b71a-e9773fdbca18">

**mc admin trace -v minioserver**

![trace](https://github.com/minio/minio/assets/5875364/cd2d9140-80a9-4822-9585-fe1547af695d)

## Environment
macOS(Intel)
docker - minio:latest
Froala editor v3.2.2
rails 6.1.5.1

**Comment by harshavardhana** [comment]
Please share the code.

**Comment by bartwork** [comment]
The editor JS-code has been minified. But I can look for it. Are the queries generated by the editor not enough? Are the queries generated by the editor not enough? It works fine on another S3 service, but not on minio. Is there any way to get more detailed information about the error, except `mc admin trace -v minioserver`?

<img width="1181" alt="payload" src="https://github.com/minio/minio/assets/5875364/09805e76-dee7-4574-86f1-051e93550d08">

**Comment by harshavardhana** [comment]
No sir we need a reproducible code, it cannot be just random. 

POST /sy seems wrong there can never be bucket name as `/sy`

**Comment by bartwork** [comment]
> POST /sy seems wrong there can never be bucket name as `/sy`
The bucket was hidden. Here is an example of requests and policy.
The problem is the conditions. But the form conditions are described and work fine on another S3 service.

<img width="1680" alt="01" src="https://github.com/minio/minio/assets/5875364/7ac10cff-afff-40d3-8fc5-34f90da2d6e4">
<img width="1680" alt="02" src="https://github.com/minio/minio/assets/5875364/903285b2-53fa-4154-ba90-dbf4444df031">
<img width="1680" alt="03" src="https://github.com/minio/minio/assets/5875364/bd3a8cc9-9cbb-49b6-ae47-5593f898af19">
<img width="1680" alt="04" src="https://github.com/minio/minio/assets/5875364/80a5d861-c075-43fa-9116-dbf0161b8d80">
<img width="1680" alt="05" src="https://github.com/minio/minio/assets/5875364/df8c293c-16e5-40a1-9ba0-ec1999359ab0">
<img width="1680" alt="06" src="https://github.com/minio/minio/assets/5875364/ecb9fd46-474a-4e97-8477-7bffb77a250e">
<img width="1679" alt="byebug" src="https://github.com/minio/minio/assets/5875364/d116f4e0-be0e-4eda-b185-4fe91ba24fb2">

**Comment by harshavardhana** [comment]
The signature field looks like is wrong it must be `Signature` not `signature`

**Comment by bartwork** [comment]
> The signature field looks like is wrong it must be `Signature` not `signature`
Changing to `Signature` didn't help.

<img width="1600" alt="Signature_1" src="https://github.com/minio/minio/assets/5875364/c7744c07-27e8-48bb-8c27-14dba8703aba">

<img width="1600" alt="Signature_2" src="https://github.com/minio/minio/assets/5875364/1c922cd1-3a91-4c08-b985-2b34e204ca46">

**Comment by bartwork** [comment]
Is there an opportunity to somehow find out in more detail which condition the minio doesn’t like? Except `mc admin trace -v minioserver`

**Comment by jiuker** [comment]
Just set the error information keys to condition.

**Comment by jiuker** [comment]
https://github.com/minio/minio/pull/18074/files you can see the `cmd/post-policy_test.go` diff

**Comment by bartwork** [comment]
Thanks! Only, is it possible if I display errors in the source code and rebuild the Minio from the source code? Minio doesn't have such logs?

**Comment by jiuker** [comment]
@harshavardhana cc

**Comment by jiuker** [comment]
> Thanks! Only, is it possible if I display errors in the source code and rebuild the Minio from the source code? Minio doesn't have such logs?

No plan for this. Thanks.

**Comment by harshavardhana** [comment]
> > The signature field looks like is wrong it must be `Signature` not `signature`
> > Changing to `Signature` didn't help.
> 
> <img alt="Signature_1" width="1600" src="https://private-user-images.githubusercontent.com/5875364/322986041-c7744c07-27e8-48bb-8c27-14dba8703aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjU2NDEsIm5iZiI6MTcxMzQyNTM0MSwicGF0aCI6Ii81ODc1MzY0LzMyMjk4NjA0MS1jNzc0NGMwNy0yN2U4LTQ4YmItOGMyNy0xNGRiYTg3MDNhYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMDcyOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU3MGY3ZDM3MTMwYzZiYWYyNmE4NTllNDU2OTFmZjU1ZGRhYjIzNjIxODAyYjBmNWM3NDNhNjljNDJlYTIyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JqabVsFZRY71OIwzFS_Nw0DxzamyngGSoXJNsjzWR3Q"> <img alt="Signature_2" width="1600" src="https://private-user-images.githubusercontent.com/5875364/322986050-1c922cd1-3a91-4c08-b985-2b34e204ca46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjU2NDEsIm5iZiI6MTcxMzQyNTM0MSwicGF0aCI6Ii81ODc1MzY0LzMyMjk4NjA1MC0xYzkyMmNkMS0zYTkxLTRjMDgtYjk4NS0yYjM0ZTIwNGNhNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMDcyOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVhYzk0M2I4MjExMzIwMTI5NTc3NjIwMjU0MjVkMjFhYzE0OTE5ZDhhYzJmNGE4MGY2NjZlNjcwOWQ3ZGY1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pUwBlaZdUm3nLjtVUe8pZ7NUEF9FCN7GLiDbStO0_J8">

@jiuker, the issue is still present. We can give a source log that adds some more conditions and provides more context for debugging this problem.

**Comment by jiuker** [comment]
> Thanks! Only, is it possible if I display errors in the source code and rebuild the Minio from the source code? Minio doesn't have such logs?

Have you solved the issue? @bartwork

**Comment by bartwork** [comment]
> @jiuker, the issue is still present. We can give a source log that adds some more conditions and provides more context for debugging this problem.
Yes, it would be nice. I'll show you the debugging if you send me the tool for this.

**Comment by bartwork** [comment]
> Have you solved the issue? @bartwork
No, the problem is not solved yet.

**Comment by jiuker** [comment]
> > Have you solved the issue? @bartwork
> > No, the problem is not solved yet.

@bartwork Have you add the fileds `Awsaccesskeyid` and `Signature` into policy conditions ?

**Comment by bartwork** [comment]
> @bartwork Have you add the fileds `Awsaccesskeyid` and `Signature` into policy conditions ?
Thank you very much! Adding these fields to the condition solved the problem with the Minio.

`['starts-with', '$signature', ''],`
`['starts-with', '$awsaccesskeyid', ''],`

<img width="453" alt="policy_valid" src="https://github.com/minio/minio/assets/5875364/5b42c2fa-766c-4f52-b74f-97c5da5912d4">

Interesting - but YandexCloud S3 gives an error for these conditions. But I will solve this with different policies for services.

<img width="751" alt="yandex_cloud_s3" src="https://github.com/minio/minio/assets/5875364/9c80fb88-27c9-41e4-8cb8-b922a57b6b83">

Thank you! @jiuker 谢谢! Problem solved.

**Comment by jiuker** [comment]
> 谢谢!

@bartwork You're welcome.

**Comment by harshavardhana** [comment]
> Interesting - but YandexCloud S3 gives an error for these conditions. But I will solve this with different policies for services.

That looks like an incorrect implementation. AWS S3 mandates sending `Awsaccesskeyid` along with a signature; otherwise, there is no way to know which user the request is for.

**Comment by bartwork** [comment]
> That looks like an incorrect implementation. AWS S3 mandates sending `Awsaccesskeyid` along with a signature; otherwise, there is no way to know which user the request is for.
Yes, it looks like it. The main problem with the Minio has been solved. Thank you! 🤝
