### ISSUE TITLE
Failures when expanding the number of drives in a distributed deployment 

### ISSUE THREAD

**Issue by briansays** [minio/minio#19522]
## Expected Behavior
Changing the MINIO_VOLUMES parameter to include the new drive should expand the number of drives in the pool: 

Original: MINIO_VOLUMES="http://10.1.1.{1...6}:9000/mnt/disk{0...3}/minio"
Modified: MINIO_VOLUMES="http:/10.1.1.{1...6}::9000/mnt/disk{0...4}/minio"

## Current Behavior
The services fail to start up as expected and never recover. 

## Steps to Reproduce (for bugs)

1. installed and formatted new drive w/ XFS 
2. updated fstab and mounted drive with minio folder using the correct minio-user permissions 
3. update the /etc/default/minio config file with the new drive 
4. restart the services and watch them fail

## Context
Trying to expand the number of drives in a distributed deployment that has 6 servers (10.1.1.11->10.1.1.16), each server currently has 4 drives in use, and as a function of funding limitations I can only add a single group of drives at a time (i.e. I can buy 6 drives at a time to upgrade the storage.)

The error I'm getting when trying to expand the deployment is: `"ERROR Unable to initialize backend: /mnt/disk0/minio drive is already being used in another erasure deployment. (Number of drives specified: 30 but the number of drives found in the 1st drive's format.json: 24)"` Which to me implies that these new drives are being considered a differnet deployment and thus cannot be combined with the original 24 drives in use. 

Is there a way to go about adding these drives to my existing pool? 

## Regression
No 

## Your Environment
* Version used (`minio --version`): RELEASE.2024-02-13T15-35-11Z (go1.21.7 linux/amd64)
* Server setup and configuration: 6 severs with 10GbE and 200GbE networking, baseline with 4 drives in each server
* Operating System and version (`uname -a`): 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You cannot just randomly expand nodes in this manner. https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html

**Comment by briansays** [comment]
Okay, well that's unfortunate. So, given that I am stuck with this
situation, should I be able to expand all the storage nodes and then
rebuild the deployment one at a time?

That is to say, if i add 10 drives to server 1 and then change the
MINIO_VOLUMES value to be something like:

MINIO_VOLUMES=http://10.1.1.11:9000/mnt/disk{0...9}/minio http://
http://10.1.1.1{2...6}:9000/mnt/disk{0...3}/minio

and then do that for each server until they all have 10 drives? It would
probably take a while and everything would need to restripe across the
pool, right? As long as I don't go lower than 4 drives in any pool I should
be okay data-retention wise I think.

thanks

**Comment by klauspost** [comment]
Read the linked documentation for guidelines. Expansion should not be done in small chunks.
