### ISSUE TITLE
Helm community chart 'extraArgs' broken

### ISSUE THREAD

**Issue by rossigee** [minio/minio#19530]
I'm trying to enable the FTP service on my Minio standalone deployment.

The docs suggest I need to add some cmdline args...

```
--ftp="address=:8021"
--ftp="passive-port-range=10000-10010"
```

The Helm chart `deployment` template uses the `extraArgs` template, which suggests I need to add these as `extraArgs` value...

```
    extraArgs: 
      - --ftp="address=:8021"
      - --ftp="passive-port-range=10000-10010"
```

## Expected Behavior

I would expect (once deployed) the server to be restarted with the extraArgs provided.

## Current Behavior

Whatever I use for 'extraArgs' it produces the following error...

```
Helm upgrade failed for release minio-standalone/minio with chart minio@5.1.0: YAML parse error on minio/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: did not find expected '-' indicator
```

## Possible Solution

Not sure. Maybe it's broken indentation in the templated manifest.

## Steps to Reproduce (for bugs)

1. Add `extraArgs` to an existing, working Helm deployment.

## Context

N/A

## Regression

N/A

## Your Environment

Helm releases are being managed by `flux2` latest version.

**Comment by jiuker** [comment]
```yaml
extraArgs: 
  - --ftp=\"address=:8021\"
  - --ftp=\"passive-port-range=10000-10010\"
```
