### ISSUE TITLE
Connection LDAP no longer works after update (normalization of DN names?)

### ISSUE THREAD

**Issue by ClementDe** [minio/minio#19536]
## NOTE

Hi,
Following the latest update on the normalization of DN names with LDAP, accounts are inaccessible at login.

The tokens are still active but I can no longer access the account.

it seems that the accounts already exist in this form in the policy:

CN=Toto Bou,OU=Users,OU=Blabla,OU=Global,DC=Blabla,DC=lan
does not work anymore

## Current Behavior

The accounts already configured on my minio instance are inaccessible following the update, I have the impression that the standardization has made them inaccessible.

If I run an add cmd again like this:

`mc idp ldap policy attach mgdev consoleAdmin --user="CN=Toto Bou,OU=Users,OU=Blabla,OU=Global,DC=Blabla,DC=lan"`

I have this:

`mc idp ldap policy entities ALIAS`

> Query time: 2024-04-17T12:58:30Z
> Policy -> Entity Mappings:
>    Policy: consoleAdmin
>      User Mappings:
>           CN=Toto Bou,OU=Users,OU=Blabla,OU=Global,DC=Blabla,DC=lan
>           cn=Toto Bou,ou=Users,ou=Blabla,ou=Global,dc=Blabla,dc=lan

instead of a message telling me that the account is already present.

another point I noticed, if I want added a name with an accent like,

`mc idp ldap policy attach mgdev consoleAdmin --user='CN=Clément Bou,OU=Users,OU=Blabla,OU=Global,DC=Blabla,DC=lan'`

I am left with:

`mc idp ldap policy entities ALIAS`

> Query time: 2024-04-17T12:58:30Z
> Policy -> Entity Mappings:
>     Policy: consoleAdmin
>       User Mappings:
>            cn=Cl\c3\a9ment Bou,ou=Users,ou=Blabla,ou=Global,dc=Blabla,dc=lan

Here I cannot connect with the Clément login.

## Possible Solution

it would be necessary to have the possibility of converting the existing one, to no longer see the problem and regain access to existing accounts.
and support the ability to have accents in names.

## Steps to Reproduce (for bugs)

1.Have functional LDAP auth
2.Have an account created with capital letters (so before the update, on a commr version RELEASE.2024-03-26T22-10-45Z I suppose)
3.Update minio to the latest version, you can no longer access the LDAP account
4.See bug description for commands

## Regression
 Yes

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-04-06T05-26-02Z
* Operating System and version (`uname -a`): Debian

thank you for your answers

**Comment by donatello** [comment]
@ClementDe Thanks for the report. To handle converting existing mappings with the older un-normalized name we are bringing a change to IAM export/import that will perform the normalization on import in https://github.com/minio/minio/pull/19528 


> another point I noticed, if I want added a name with an accent like,
> 
> mc idp ldap policy attach mgdev consoleAdmin --user='CN=Clément Bou,OU=Users,OU=Blabla,OU=Global,DC=Blabla,DC=lan'
> 
> I am left with:
> 
> mc idp ldap policy entities ALIAS
> 
>     Query time: 2024-04-17T12:58:30Z
>     Policy -> Entity Mappings:
>     Policy: consoleAdmin
>     User Mappings:
>     cn=Cl\c3\a9ment Bou,ou=Users,ou=Blabla,ou=Global,dc=Blabla,dc=lan
> 
> Here I cannot connect with the Clément login.
> 

When I try to reproduce this locally, I don't see any issue - I am able to login with the accent in the login name.

Would you be able to run a trace?

1. Run `mc admin trace -v -a --funcname 'sts.AssumeRoleWithSSO' ALIAS` in a terminal
2. Attempt to login via the browser
3. Provide the output from the terminal for the login attempt (you may need to redact credentials in this output).

This would give us an idea of why the login attempt is failing.

**Comment by AxicsHD** [comment]
I could reproduce the problem and have found that it is due to the case sensitive search of MinIO in LDAP.
Here is the trace of the application:
![image](https://github.com/minio/minio/assets/44569954/ffe8e36a-1404-4a18-816c-bb3ac1a49aa1)

Now here is the search with the lowercase string from the error message:
![image](https://github.com/minio/minio/assets/44569954/8d1e2e4c-9b3d-4513-896f-cc91595eeb21)

And here the search with CN & OU capitalized as it also comes from the LDAP
![image](https://github.com/minio/minio/assets/44569954/6a2ffd29-b49f-437a-a49c-db334573ae4b)

**Comment by ClementDe** [comment]
Hi,

Thank you for your answers!

I tried IAM export/import following ticket #19528.
I did my export, updated my version then I wanted to import
But I got an error that I'm having trouble understanding:

`mc admin cluster iam import mgdev ./toto-iam-info.zip`
```
mc: <ERROR> Unable to import IAM info. We encountered an internal error, please try again.: cause(error importing GG_MinIOAdmin from group_mappings.json with: Error looking up DN GG_MinIOAdmin: LDAP client: LDAP Result Code 34 "Invalid DN Syntax": 0000208F: NameErr: DSID-03100232, problem 2006 (BAD_NAME), data 8350, best match of:
 'GG_MinIOAdmin'
```

if I consult the groups after this failure:

`mc admin group list mgdev`

before: 

> CN=GG_MinIOAdmin,OU=Security,OU=Groups,OU=Blabla,OU=Global,DC=blabla,DC=lan

after: 

> cn=GG_MinIOAdmin,ou=Security,ou=Groups,ou=Blabla,ou=Global,dc=blabla,dc=lan
> GG_MinIOAdmin
> CN=GG_MinIOAdmin,OU=Security,OU=Groups,OU=Blabla,OU=Global,DC=blabla,DC=lan

So I have several questions:
Does the problem come from the name itself?
the import causes a duplicate and not a replacement? 

This import failed but it still had an effect (update minio ?)because the tokens associated with my account no longer worked, I had to redo the user for it to work again.
Now I can find my account and my tokens, but I have duplicates in the user list:

```
CN=_MinIO,
cn=_MinIO,
```

If I want to delete the old user I do:

`mc idp ldap policy attach mgdev consoleAdmin --user="CN=_MinIO.."`

This deletes the user "cn=" and never the "CN=" :(

------------------

For the username problem here is the log, this matches the previous message:

> <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>LDAP server error: LDAP auth failed for DN cn=Cl\c3\a9ment XXXX,ou=Users,ou=XXX,ou=Global,dc=XXX,dc=XX: LDAP Result Code 49 &#34;Invalid Credentials&#34;: 80090308: LdapErr: DSID-0C090569, comment: AcceptSecurityContext error, data 52e, v4563�</Message></Error><RequestId>17C8E21627D661D2</RequestId></ErrorResponse>

![image](https://github.com/minio/minio/assets/84447702/732a757d-e0f9-45d9-8a8d-7c1b4d28fa34)

**Comment by harshavardhana** [comment]
All of this must be fixed, can you share your IAM export in a ZIP file?

We need all of those to make it work. 

Don't hide things you can change all of this once you give us your IAM file.

We want to see how to add tests to cover these areas

**Comment by ClementDe** [comment]
Hi,
Unfortunately I cannot send you my information without modification, there is information concerning my company.

having only one minio instance, I don't have the means to do many other tests, sorry.

-------
For the normalization problem, I managed to recover operation.

I didn't quite understand how.
I managed to remove duplicates from some accounts by doing an "attach" then "detach" and "attach" again.
The duplicate seems to disappear: the account in "CN=blabla" is no longer present, I only have "cn= blabla".

I also recovered the tokens associated with my "CN=blabla" account following a new "attach" for "cn=blabla" so there was definitely a positive effect with the update.

sorry if that doesn't help you much :/.

-----
For the accent problem on an account like "cn=Clément TOTO" which gives "cn=Cl\c3\a9ment TOTO"
(I don't have accents on the other fields)
I always reproduce with the version "2024-04-18T19:09:19Z"

the account is well found because I have the answer from minio: "mc idp ldap policy attach blabla consoleAdmin --user="cn=Clément TOTO,ou=XXX,ou=XXX,ou=XXXX,dc=XXX,dc=lan""

```
Attached Policies: [consoleAdmin]
To User: cn=Clément TOTO,ou=Users,ou=XXX,ou=XXX,dc=XXX,dc=XXX
```
But when I do: "mc admin user list mgdev"

I get this line:

`enabled cn=Cl\c3\a9ment T... consoleAdmin`

**Comment by harshavardhana** [comment]
There were three different PRs that attempted to address the situation properly

- duplicate mappings are now automatically removed when found via (import/export)
- accessKey preservation for existing local users was being errored has been handled properly
- It also extends tests for other nuanced scenarios like conflicting group names.

With that in mind, we think this issue has been sufficiently addressed. Please open a new issue if you face further problems. 

Remember, IAM export/import is necessary, i.e., before the upgrade, capture an "export" - and import it after the upgrade. 

We are not doing this automatically inside MinIO. We will be making a new release soon.

**Comment by joltcan** [comment]
For anyone coming here and having problems with their access keys tied to LDAP after upgrade from something old, I solved it with some simple `sed`.

First export `mc admin cluster iam export <name>`
Then unpack it: `unzip <name>-iam-info.zip`
Replace uppercase CN/OU/DC: `sed -E 's/(CN=|OU=|DC=)([^,]+)/\L\1\E\2/g' iam-assets/svcaccts.json > iam-assets/svcaccts_lowercase.json`
Check so the lowercase file is ok, then move it: `mv iam-assets/svcaccts_lowercase.json iam-assets/svcaccts.json`
Then pack it up again: `zip -r iam-info-new.zip iam-assets/`
Add the config to the cluster: `mc admin cluster iam import <name> iam-info-new.zip`
