### ISSUE TITLE
Broken permission system when using SFTP

### ISSUE THREAD

**Issue by Oidlichtnwoada** [minio/minio#19542]
For a client I need to implement an SFTP server where he can upload his files, we chose Minio to do this as we can also access it with S3. The client has a folder called "asdftom" within the bucket "import" and should only see the files within this folder and should only be able to upload (preferrable only upload non-existent file ... non-overwrite ... this is also not possible at the moment as I found out) and to download files.

I came up with this policy which works fine with the S3 web console and the SFTP server, except file uploads do not work with SFTP, I get a permission denied error:
```json
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowUserToSeeBucketListInTheConsole",
        "Action": [
          "s3:ListAllMyBuckets",
          "s3:GetBucketLocation"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::import"
        ]
      },
      {
        "Sid": "AllowRootAndFolderListingOfBucket",
        "Action": [
          "s3:ListBucket"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::import"
        ],
        "Condition": {
          "StringEquals": {
            "s3:prefix": [
              "asdftom/"
            ],
            "s3:delimiter": [
              "/"
            ]
          }
        }
      },
      {
        "Sid": "AllowListingOfSpecificFolder",
        "Action": [
          "s3:ListBucket"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::import"
        ],
        "Condition": {
          "StringLike": {
            "s3:prefix": [
              "asdftom/*"
            ]
          }
        }
      },
      {
        "Sid": "AllowSpecificS3ActionsInSpecificFolder",
        "Effect": "Allow",
        "Action": [
            "s3:GetObject", "s3:PutObject"
        ],
        "Resource": [
          "arn:aws:s3:::import/asdftom/*"
        ]
      }
    ]
  }
  ```
  
To make file uploads work the condition from "AllowRootAndFolderListingOfBucket" needs to be removed, resulting in the following policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowUserToSeeBucketListInTheConsole",
        "Action": [
          "s3:ListAllMyBuckets",
          "s3:GetBucketLocation"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::import"
        ]
      },
      {
        "Sid": "AllowRootAndFolderListingOfBucket",
        "Action": [
          "s3:ListBucket"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::import"
        ],
      },
      {
        "Sid": "AllowListingOfSpecificFolder",
        "Action": [
          "s3:ListBucket"
        ],
        "Effect": "Allow",
        "Resource": [
          "arn:aws:s3:::import"
        ],
        "Condition": {
          "StringLike": {
            "s3:prefix": [
              "asdftom/*"
            ]
          }
        }
      },
      {
        "Sid": "AllowSpecificS3ActionsInSpecificFolder",
        "Effect": "Allow",
        "Action": [
            "s3:GetObject", "s3:PutObject"
        ],
        "Resource": [
          "arn:aws:s3:::import/asdftom/*"
        ]
      }
    ]
  }
  ```

It seems like to make FTP work the user must be able to call ListBucket on all locations in the browser, which contradicts the requirement that the client can only see his own folder. It makes no sense to me to use this kind of prerequirement, as listing his own folder should be enough to upload files, "s3:PutObject" should be enough. I am using the latest FileZilla client and Minio in version RELEASE.2024-04-06T05-26-02Z.

## Expected Behavior
File uploads work also if user can only list his own folder.

## Current Behavior
User sees all contents of bucket, if file uploads should be allowed

## Possible Solution
Make it work with the above policy, please.
Also the documentation on FTP/SFTP is quite sparse and does not cover the needed permissions in order to work. It is suggested to work with readwrite in the official video which is quite bad in my opinion and the mapping from FTP operations to S3 actions should be presented in the docs.

## Steps to Reproduce (for bugs)
I think, the issue should be clear and reproducible, if not please call me.

## Context
already presented

## Regression
Minio: RELEASE.2024-04-06T05-26-02Z

## Your Environment
Docker deployment, but code should be the same everywhere ...

**Comment by harshavardhana** [comment]
> It seems like to make FTP work the user must be able to call ListBucket on all locations in the browser, which contradicts the requirement that the client can only see his own folder. It makes no sense to me to use this kind of prerequirement, as listing his own folder should be enough to upload files, "s3:PutObject" should be enough. I am using the latest FileZilla client and Minio in version RELEASE.2024-04-06T05-26-02Z.

FTP/SFTP permissions cannot be as granular as S3 permissions. It is quite simply very complicated. It is designed for simpler use cases; if you have complex requirements, move to S3 API. 

FTP/SFTP is not something we want to perpetuate for long, it is designed for you to eventually migrate to S3 API.

You cannot use FTP/SFTP for simpler use-cases.

**Comment by Oidlichtnwoada** [comment]
@harshavardhana 
I thought it would be nice to upload a file using FTP without needing the see all bucket content ... definitely on the same page with multiple developers ... now I know why you have so few open tickets ... not because the software is error-free, but because meaningful requests are just closed, sad to see ...

**Comment by klauspost** [comment]
@Oidlichtnwoada It is called software engineering and not spending time on fringe functionality, that may be used by 3 people in the lifetime of the product.

MinIO is not and will never be a full featured (S)FTP server. We add enough of it to casually be able to connect legacy software.

**Comment by nesar77** [comment]
Hi @Oidlichtnwoada how did you solve the issue? I need to start an ftps server on Windows; I'm able to get the list of bucktes but not to send the command cd bucketname 'cos I'm getting the  Access failed: 550 Directory change to bucketname..

**Comment by harshavardhana** [comment]
> @harshavardhana I thought it would be nice to upload a file using FTP without needing the see all bucket content ... definitely on the same page with multiple developers ... now I know why you have so few open tickets ... not because the software is error-free, but because meaningful requests are just closed, sad to see ...

If we close it we are not interested in doing it. That's where it ends, if you want some features and you have the scale and requirement come and talk to us at https://min.io/pricing 

Beyond that our decision is final on where the product goes. If you want your own changes you can keep it in your fork.

**Comment by harshavardhana** [comment]
> Hi @Oidlichtnwoada how did you solve the issue? I need to start an ftps server on Windows; I'm able to get the list of bucktes but not to send the command cd bucketname 'cos I'm getting the Access failed: 550 Directory change to bucketname..

Please open a new issue @nesar77

**Comment by harshavardhana** [comment]
@Oidlichtnwoada if you find real bugs in software we are happy to fix. Assessing if an issue makes sense for us is our product right. It is nothing personal.

We close issues unlike other open source communities where things linger around for years. Hoarding on issues is useless,  If we can't get to it in a month to our users we won't be able to anyway.

You want priority and SLA become a customer. 

Locking this issue this is a settled discussion.
