### ISSUE TITLE
Restart minio.service in Debian package postinst

### ISSUE THREAD

**Issue by Cornelicorn** [minio/minio#19556]
**Is your feature request related to a problem? Please describe.**

I'd like to use the debian package on a local repository to upgrade our minio servers. This currently extracts the binary, but does nothing else. The systemd unit is also not updated in the running context.

**Describe the solution you'd like**

A postinst script running `systemctl daemon-reload` and `systemctl try-restart minio.service` or rather their equivalents with debian helper scripts.
This would reload the unit files and restart the service if it's already running, but not start it if it's not running.

**Additional context**

**Comment by harshavardhana** [comment]
We do not want to restart, debian packages are provided for courtesy we have no interest it making it more complex than what it is.
