### ISSUE TITLE
Browser fails to open https://min.io because of invalid certificate

### ISSUE THREAD

**Issue by pre** [minio/minio#19557]
Repro: 

* Open https://min.io
* See `NET::ERR_CERT_AUTHORITY_INVALID`

![image](https://github.com/minio/minio/assets/63895/e40dd36f-726f-4aac-af15-1a4a884ae570)

**Comment by klauspost** [comment]
Seems like "Cisco" is injecting certs. This is the correct cert:

![image](https://github.com/minio/minio/assets/5663952/8cb39655-1c40-4245-9127-6d00fddaa253)

**Comment by pre** [comment]
Jahans, thanks for the info. I didn't think of that. 

I reported this to the team which configures the filterings.
