### ISSUE TITLE
AssumeRoleWithCertificate does return AccessDenied for all admin actions

### ISSUE THREAD

**Issue by stv0g** [minio/minio#19562]
Providing credentials with minio-py's `minio.credentials.CertificateIdentityProvider` to `minio.MinioAdmin` does always return:

```json
{
   "Code":"AccessDenied",
   "Message":"Access Denied.",
   "Resource":"/minio/admin/v3/remove-canned-policy",
   "RequestId":"17C71E5038EDD288",
   "HostId":""
}
```

Using static credentials and `MINIO_ROOT_USER`, `MINIO_ROOT_PASSWORD`, does work as expected.

This is the policy which we use for the certificate used:

```json
{
 "PolicyName": "admin",
 "Policy": {
  "Version": "2012-10-17",
  "Statement": [
   {
    "Effect": "Allow",
    "Action": [
     "admin:*"
    ]
   },
   {
    "Effect": "Allow",
    "Action": [
     "kms:*"
    ]
   },
   {
    "Effect": "Allow",
    "Action": [
     "s3:*"
    ],
    "Resource": [
     "arn:aws:s3:::registry*"
    ]
   }
  ]
 },
 "CreateDate": "2024-04-17T07:52:41.997Z",
 "UpdateDate": "2024-04-17T16:22:02.166Z"
}
```

**Comment by allanrogerr** [comment]
@stv0g Could you provide a small sample of code showing what you are facing please?

**Comment by allanrogerr** [comment]
Also, please provide a trace of MinIO while you are running your python script e.g. `mc admin trace <ALIAS> -v > trace.out`

**Comment by balamurugana** [comment]
This is mostly setup issue. Mostly certificate and.or respective policy assigned could have problem. Nothing can be done at client side.

**Comment by harshavardhana** [comment]
can you share the output of your `openssl x509` @stv0g ?

**Comment by stv0g** [comment]
Sorry, It seems I've fixed it. Sorry for the falsely reported issue
