### ISSUE TITLE
In offline environment, minio requests dl.min.io, causing slow startup

### ISSUE THREAD

**Issue by xianfeiqiang** [minio/minio#19564]
## NOTE

hi, everyone!  I found it very slow to start minio offline, and later I learned that minio would send a DNS request [dl.min.io](http://dl.min.io/) the domain name by grabbing the packets. I parsed it to 127.0.0.1 and the startup was very fast. Does minio have a variable to close the domain name [dl.min.io](http://dl.min.io/) connection?

I found that there is MINIO_UPDATE=off parameter, may it be applicable to docker? This parameter does not take effect during single-node installation. I'm not sure if connecting dl.min.io is used for updates?

## Your Environment

* Version used (`minio --version`):   minio version RELEASE.2022-02-18T01-50-10Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`):   minio version RELEASE.2022-02-18T01-50-10Z

Please upgrade, this has long been fixed.

**Comment by xianfeiqiang** [comment]
@harshavardhana  Can you tell me which version it has been fixed from? I don’t want to skip too many versions

**Comment by klauspost** [comment]
Check the [release notes](https://github.com/minio/minio/releases).
