### ISSUE TITLE
Memory usage (alloc_bytes/heap_inuse_bytes) increased by factor > 10x

### ISSUE THREAD

**Issue by markush81** [minio/minio#19572]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Usual memory usage

## Current Behavior

alloc_bytes and heap_inuse_bytes increased by more than 10x

![image](https://github.com/minio/minio/assets/3304672/7ccd52ed-5676-4154-9c53-f7eb7a3dfea5)

## Possible Solution
---

## Steps to Reproduce (for bugs)
Installed Release 2024-03-26T22-10-45Z coming from 2023-06-23T20-26-00Z

## Context

Memory consumption dramatically increased and causes issues.

## Regression

already has been mentioned in https://github.com/minio/minio/issues/19429

## Your Environment
* Version: 2024-03-26T22:10:45Z
* Server setup and configuration: 
```
●  minio-prd01:9001
   Uptime: 7 minutes 
   Version: 2024-03-26T22:10:45Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
   Pool: 1

●  minio-prd02:9001
   Uptime: 7 minutes 
   Version: 2024-03-26T22:10:45Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
   Pool: 1

●  minio-prd03:9001
   Uptime: 7 minutes 
   Version: 2024-03-26T22:10:45Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
   Pool: 1

●  minio-prd04:9001
   Uptime: 7 minutes 
   Version: 2024-03-26T22:10:45Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
   Pool: 1

Pools:
   1st, Erasure sets: 1, Drives per erasure set: 4

352 GiB Used, 33 Buckets, 583,652 Objects
4 drives online, 0 drives offline
```
* Operating System and version (`uname -a`): 
```
Linux minio-prd01 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
```

**Comment by klauspost** [comment]
MinIO preallocates buffers for incoming data now.

**Comment by dharapvj** [comment]
@klauspost - Is there way to reduce memory allocation to some extent? For same workload giving almost 7-10 time more memory is not making everyone happy in the organization. Do we have some way to override pre-allocation / size of pre-allocation?

**Comment by klauspost** [comment]
@dharapvj This has been partially reverted by #19839 Also `MINIO_MEMLIMIT=10GB` or `--memlimit=10GB` can also set a limit, usually at the expense of additional CPU.

But have your organization reach out on `sales@min.io` to get you set up proper and we can go into more details.
