### ISSUE TITLE
I am using Minio agnet to share some backup files from original azure blob stoage to Minio agnet.  We used Minio helm chat with environment like MINIO_ACCESS_KEY, and MINIO_SECRET_KEY. I don't want share the MINIO_ACCESS_KEY to other memebrs, How do I keep it safe.

### ISSUE THREAD

**Issue by ep23-eps** [minio/minio#19574]
## NOTE
All GitHub issues are addressed on a best-effort basis at MinIO's sole discretion. There are no Service Level Agreements (SLA) or Objectives (SLO). Remember our [Code of Conduct](https://github.com/minio/minio/blob/master/code_of_conduct.md) when engaging with MinIO Engineers and the larger community.

For urgent issues (e.g. production down, etc.), subscribe to [SUBNET](https://min.io/pricing?jmp=github) for direct to engineering support.
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
Ask in https://github.com/minio/minio/discussions (and don't put your entire question in the headline)
