### ISSUE TITLE
Minio at latest is NOT case-sensitive 

### ISSUE THREAD

**Issue by bmizerany** [minio/minio#19588]
## Expected Behavior
I expected putting an object key "UPPERCASE" and then stating it as "uppercase" would produce a "not found"; however, it does not.

## Current Behavior

Minio is (currently) case-insensitive.

## Steps to Reproduce (for bugs)

Create a Minio bucket called `testingminiocase`, and one in S3 (or R2) with the same name.

Run this script against both Minio and S3 (or R2):

```
package main

import (
	"context"
	"log"
	"strings"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	// mc, err := minio.New("localhost:9000", &minio.Options{
	// 	Secure: false,
	// 	Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
	// })
	mc, err := minio.New("s3.amazonaws.com", &minio.Options{
		Secure: true,
		Creds:  credentials.NewEnvAWS(),
	})
	if err != nil {
		panic(err)
	}

	ctx := context.Background()
	_, err = mc.PutObject(
		ctx,
		"testingminiocase",
		"UPPERCASE",
		strings.NewReader("x"),
		1,
		minio.PutObjectOptions{},
	)
	if err != nil {
		panic(err)
	}

	_, err = mc.StatObject(ctx, "testingminiocase", "uppercase", minio.GetObjectOptions{})
	if err != nil {
		log.Println("ERROR:", err)
		log.Println("SUCCESS")
		return
	}

	log.Println("Minio object keys are not case sensitive.")
}
```

```
; go run x.go # Local Minio endpoint
2024/04/23 09:48:38 Minio object keys are not case sensitive.
; go run x.go # S3 (s3.amazonaws.com) endpoint and creds
2024/04/23 09:48:56 ERROR: The specified key does not exist.
2024/04/23 09:48:56 SUCCESS
```

## Context

I'm getting false positives in tests, and when switching back and forth between S3 and Minio I get unexpected and differing behaviors.

## Regression

I think this is a regression?

## Your Environment

```
; minio --version 
minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: devel go1.23-4605dfaf76 Fri Mar 15 18:30:58 2024 +0000 X:rangefunc darwin/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```

```
; uname -a
Darwin MacBook-Pro-2.attlocal.net 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:10 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6031 arm64
```

**Comment by harshavardhana** [comment]
@bmizerany, you should be using Linux. It looks like your Darwin backend drive FS is translating calls from uppercase to lowercase.

**Comment by harshavardhana** [comment]
```
go run /tmp/put.go 
2024/04/23 10:00:54 ERROR: The specified key does not exist.
2024/04/23 10:00:54 SUCCESS
```

```
minio --version
minio version DEVELOPMENT.2024-04-23T05-07-37Z (commit-id=5ea5ab162bf37b87b25da5cd10eab6e1422c2dad)
Runtime: go1.21.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

**Comment by bmizerany** [comment]
@harshavardhana From the Minio docs:

> MinIO is an object storage solution that provides an Amazon Web Services S3-compatible API and supports all core S3 features. MinIO is built to deploy anywhere - public or private cloud, baremetal infrastructure, orchestrated environments, and edge infrastructure.

The behavior Im seeing is very surprising. Maybe docs should call out right upfront that Minio is _mostly_ S3 compatible on Mac?

https://min.io/docs/minio/macos/index.html

**Comment by harshavardhana** [comment]
> @harshavardhana From the Minio docs:
> 
> > MinIO is an object storage solution that provides an Amazon Web Services S3-compatible API and supports all core S3 features. MinIO is built to deploy anywhere - public or private cloud, baremetal infrastructure, orchestrated environments, and edge infrastructure.
> 
> The behavior Im seeing is very surprising. Maybe docs should call out right upfront that Minio is _mostly_ S3 compatible on Mac?
> 
> https://min.io/docs/minio/macos/index.html

MinIO retains your backend filesystem behavior. We do not circumvent the filesystem limits.

If you want case sensitive behavior use a filesystem which is case sensitive.
