### ISSUE TITLE
The disk storage capacity is not very accurat

### ISSUE THREAD

**Issue by yilezhu** [minio/minio#19582]
![image](https://github.com/minio/minio/assets/18655233/39138da9-37db-43a4-b19c-18ad17db1fc0)
MinIO is really easy to use, but I've encountered a minor issue during my work. After uploading files, it seems that the disk capacity does not update immediately. I'm not sure if this is because I'm using it incorrectly. Is there a way to refresh the disk usage immediately?

**Comment by harshavardhana** [comment]
Usage calculation is async it doesn't get updated real time.

It is not expected to be real time.
