### ISSUE TITLE
Suggest minio's ETag calculation algorithm switch to XXHASH that is more faster hash algorithm

### ISSUE THREAD

**Issue by amone-bit** [minio/minio#19593]
Or we can specify our own hash algorithm to calculate ETag.

**Comment by harshavardhana** [comment]
AWS S3 mandates this to be md5sum, you can do --nocompat flag to let go of md5sum requirement entirely.

**Comment by amone-bit** [comment]
I don't understand how to use it. I use the flag like below, but I get a error. Can you give me a demo or some help?
![image](https://github.com/user-attachments/assets/d9483205-6bb9-4f52-a1a3-af022d09ac39)

**Comment by klauspost** [comment]
Apologies. It is `--no-compat`.

**Comment by amone-bit** [comment]
Thank you, `--no-compat` seem can work, but when I upload a pdf file by web console, the ETAG is still calculated.
If I use `--no-compat` flag, and the ETAG is not MD5Sum.So what the ETAG is.
![image](https://github.com/user-attachments/assets/b0d48718-22e8-43e8-82a0-444b7e493f92)
![image](https://github.com/user-attachments/assets/69eb5532-5118-4d49-9b5a-3304bf855aa6)

**Comment by klauspost** [comment]
Literally just a random value.

**Comment by amone-bit** [comment]
I can't find the `--no-compat` info in the help output.Could you tell me where I can find the flag info.

**Comment by harshavardhana** [comment]
> I can't find the `--no-compat` info in the help output.Could you tell me where I can find the flag info.

It is not shown on purpose
