### ISSUE TITLE
file upload to minio failed with I/O error (*fs.PathError)

### ISSUE THREAD

**Issue by reysravanga** [minio/minio#19596]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Observing Minio I/O errors so often when we try to upload the files to minio buckt 

## Expected Behavior
File Should be uploaded Minio Bucket 

## Current Behavior
```
Error: stat /storage/avsftp: input/output error (*fs.PathError)
       5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
       4: cmd/api-errors.go:2137:cmd.toAPIError()
       3: cmd/object-handlers.go:682:cmd.objectAPIHandlers.headObjectHandler()
       2: cmd/object-handlers.go:823:cmd.objectAPIHandlers.HeadObjectHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```
## Possible Solution
restart the minio pod fixes  the problem temporarilty

## Steps to Reproduce (for bugs)
install minio RELEASE.2022-04-09T15-09-52Z and upload small files concurrently 
```
Error: stat /storage/avsftp: input/output error (*fs.PathError)
       5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()
       4: cmd/api-errors.go:2137:cmd.toAPIError()
       3: cmd/object-handlers.go:682:cmd.objectAPIHandlers.headObjectHandler()
       2: cmd/object-handlers.go:823:cmd.objectAPIHandlers.HeadObjectHandler()
       1: net/http/server.go:2047:http.HandlerFunc.ServeHTTP()
```
## Your Environment

* Version used (`minio --version`): RELEASE.2022-04-09T15-09-52Z
* Server setup and configuration:
* Operating System and version (`uname -a`): ubuntu , linux

**Comment by jiuker** [comment]
Upgrade to latest.
