### ISSUE TITLE
Uploading a file using drag and drop sometimes fails (content size is 0, and filename is changed)

### ISSUE THREAD

**Issue by mvelay** [minio/minio#19603]
![Screenshot from 2024-04-24 16-08-49](https://github.com/minio/minio/assets/146741976/a2fc34df-860a-4276-8f09-fb5fa0a7da7a)
[Screencast from 24-04-2024 15:52:25.webm](https://github.com/minio/minio/assets/146741976/75053e43-3826-4531-9f1a-26a034bc1d83)

## Expected Behavior
Uploading a file using drag and drop method should succeed.

## Current Behavior
Sometimes the upload failed with the following behavior:
- content size is 0 Byte
- filename is modified `test_minio.NTF` => ` test_minio.NTF0:-21:1043:44`

## Steps to Reproduce (for bugs)
1. Open a bucket
2. Drag and drop a file

## Context
Upload a file using drag and drop method

## Environment

* Version used (`minio --version`):
minio version RELEASE.2022-07-08T00-05-23Z (commit-id=ed0cbfb31e00644013e6c2073310a2268c04a381)
Runtime: go1.18.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.

* Operating System and version (`uname -a`):
4.18.0-372.9.1.el8.x86_64

**Comment by klauspost** [comment]
Upgrade to latest. If the issue persists open issue on https://github.com/minio/console/issues
