### ISSUE TITLE
Constant i/o operation on almost plain intallation (ARM64/OMV6)

### ISSUE THREAD

**Issue by dominch** [minio/minio#19624]
## Expected Behavior
I wanted to setup my NAS in home network, used Raspberry Pi4 with OpenMediaVault with 4 disks disks and added S3 module (minio) with one bucket for backups. I expected that it will not spin my hard drives when nothing connects with my minio bucket. I quickly found out that there is constant disk activity, as well as constant, high power usage (about 4x than normal). Iotop show about 150-200kB/s read, few bytes write. When I disable minio io operations stops. 
OMV deploys minio in podman as service in container. I can view logs, ports via podman, it uses: quay.io/minio/minio:latest image
I was trying to find anything in bucket settings, it's as easy as newly created: no encryption, no replication etc 

Tracing shows constant operations: 
![image](https://github.com/minio/minio/assets/10815109/0935937e-9cac-4673-a93c-9cd428cd916a)

Also I see that on node exporter monitoring: 
![image](https://github.com/minio/minio/assets/10815109/7622cce7-f38b-4688-997b-14c5d5191c92)

## Current Behavior
For now it will keep my drive spinning all the time on this NAS. This lead to much more power consumption and drive wear. It keeps doing io when network is disconeected from device and for sure it stops when minio service is stopped. 

## Possible Solution
I don't know, investigating problem, but for now I need to manually enable service on demand. 

## Steps to Reproduce (for bugs)
1. Probably something about ARM node, get pi4/pi5
2. install omv6 
3. enable s3 module, 
4. create bucket with defaults 
5. observe iotop activity 

## Context
This makes this NAS much less power efficient and cause drives to wear. There is daily backup setup with this s3 bucket, it takes about 20min each day, but drives are spinning all the time. 

## Regression
Probably not, 

## Your Environment
* Version used (`minio --version`): MinIO VERSION 2024-04-18T19:09:19Z
* Server setup and configuration: It's pi4 4GB, with two hard drives, each one in one usb3. 
* Operating System and version (`uname -a`): Linux omv6 6.1.21-v8+ # 1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by harshavardhana** [comment]
This is normal as we monitor the drives.

**Comment by dominch** [comment]
Thanks for clarification, 
Is there any setting that can alter this behavior? Can we tweak somehow those activities? What kind of checks are performed?

**Comment by harshavardhana** [comment]
> Thanks for clarification, Is there any setting that can alter this behavior? Can we tweak somehow those activities? What kind of checks are performed?

you can modify the source as you please, and turn it off.

**Comment by dominch** [comment]
ok, thanks for direction, probably it's this feature: https://github.com/minio/minio/tree/master/docs/config#usage-scanner
maintaining own, modified version is always possible, but I'll not do that along with everything on chain that leads to official docker minio image. If it's by design and cannot be tweaked then minio is just not for home usage. I already removed it and looking for alternative s3 compatible container solution. 

BTW: after some time - when minio is gone my monitoring reports that background scanners took about 30% of cpu and prevented disks from standby mode causing almost two times more power consumption plus slightly higher temp. It was third data backup on daily cron, so I really did not needed so much operations for this purpose.
