### ISSUE TITLE
how to set regeion as empty or default?

### ISSUE THREAD

**Issue by ghost** [minio/minio#19628]
I have set a value for the region in the manage page but it can't empty it again. The page will alert an error.

## Expected Behavior
user can clean region value or tell the user how to recover to the default value

## Current Behavior
clean `Server Location` and `Comment` in the Setting page, the save action will alert 'key_values in body should have at least 1 items.'

## Possible Solution
a delete API or mc config set key

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2023-09-04T19-57-37Z (commit-id=1c99fb106c3e1448ed92f8465d5695d055d432e7)
Runtime: go1.19.12 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

* Server setup and configuration:
* Operating System and version (`uname -a`):
Linux B09 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
There is no region by default - if you want one set it MINIO_REGION_NAME="us-west-1"

**Comment by ghost** [comment]
so it's not a bug if I clean and save it but get 'key_values in body should have at least 1 items'?

**Comment by harshavardhana** [comment]
First you need to upgrade your setup to latest release.
