### ISSUE TITLE
Storage resources are insufficient for the write operation .minio.sys/buckets/.usage.json

### ISSUE THREAD

**Issue by dove-young** [minio/minio#19622]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

this is a problem reported in issue https://github.com/minio/minio/issues/17040. But it was closed without a solution. 

## Steps to Reproduce (for bugs)

1. install minio to OCP via command 
```
kubectl minio init

oc adm policy add-scc-to-user nonroot -z default -n minio-tenant1

kubectl minio tenant create minio-tenant1 \
--servers 1 \
--volumes 2 \
--capacity 5Gi \
--namespace minio-tenant1 \
--storage-class rook-cephfs

oc adm policy add-scc-to-user cluster-admin -z minio-tenant1-sa -n minio-tenant1
```
2. I got minio runs 
```
oc get po -n minio-tenant1
NAME                   READY   STATUS    RESTARTS   AGE
minio-tenant1-ss-0-0   2/2     Running   0          5m32s
```
3. but minio tenant pod report error.
```
API: SYSTEM()
Time: 04:16:22 UTC 04/26/2024
DeploymentID: 843b1e89-253c-4c65-a0bf-21ad38b00ff6
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/.usage.json (cmd.InsufficientWriteQuorum)
       3: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       2: internal/logger/logonce.go:149:logger.LogOnceIf()
       1: cmd/data-usage.go:60:cmd.storeDataUsageInBackend()

```
4. I followed instructions in this issue https://github.com/minio/minio/issues/17040 to delete directory `.minio.sys/buckets/.usage.json ` in minio tenant pod
5. then recycled minio tenant pod, I see this error comes in a few minutes
```
API: SYSTEM()
Time: 04:25:07 UTC 04/26/2024
DeploymentID: 843b1e89-253c-4c65-a0bf-21ad38b00ff6
Error: node(127.0.0.1:9000): taking drive /export1 offline: unable to write+read for 30.001s (*errors.errorString)
       3: internal/logger/logger.go:250:logger.LogAlwaysIf()
       2: cmd/xl-storage-disk-id-check.go:972:cmd.(*xlStorageDiskIDCheck).monitorDiskWritable.func1.1()
       1: cmd/xl-storage-disk-id-check.go:992:cmd.(*xlStorageDiskIDCheck).monitorDiskWritable.func1.2()
node(127.0.0.1:9000): Read/Write/Delete successful, bringing drive /export1 online

API: SYSTEM()
Time: 04:25:14 UTC 04/26/2024
DeploymentID: 843b1e89-253c-4c65-a0bf-21ad38b00ff6
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/.bloomcycle.bin (cmd.InsufficientWriteQuorum)
       4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       3: internal/logger/logonce.go:149:logger.LogOnceIf()
       2: cmd/data-scanner.go:227:cmd.runDataScanner()
       1: cmd/data-scanner.go:79:cmd.initDataScanner.func1()

API: SYSTEM()
Time: 04:25:14 UTC 04/26/2024
DeploymentID: 843b1e89-253c-4c65-a0bf-21ad38b00ff6
Error: Storage resources are insufficient for the write operation .minio.sys/buckets/.usage.json (cmd.InsufficientWriteQuorum)
       3: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       2: internal/logger/logonce.go:149:logger.LogOnceIf()
       1: cmd/data-usage.go:60:cmd.storeDataUsageInBackend()
```

## Your Environment

* Version used (`minio --version`):
```
kubectl  minio version
Kubectl-Plugin Version: v5.0.14
```
* Server setup and configuration:  

* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
The error message indicates already what is the issue here. 

You have a hung backend disk, we have no write access to that drive.

> API: SYSTEM()
Time: 04:25:07 UTC 04/26/2024
DeploymentID: 843b1e89-253c-4c65-a0bf-21ad38b00ff6
Error: node(127.0.0.1:9000): taking drive /export1 offline: unable to write+read for 30.001s (*errors.errorString)
       3: internal/logger/logger.go:250:logger.LogAlwaysIf()
       2: cmd/xl-storage-disk-id-check.go:972:cmd.(*xlStorageDiskIDCheck).monitorDiskWritable.func1.1()
       1: cmd/xl-storage-disk-id-check.go:992:cmd.(*xlStorageDiskIDCheck).monitorDiskWritable.func1.2()
node(127.0.0.1:9000): Read/Write/Delete successful, bringing drive /export1 online

It keeps going offline and coming back online.

Please use regular disks instead of unstable remote disks.
