### ISSUE TITLE
XL: Cache bitrot calculation

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1962]
Currently bitrot is verified for every GET. The info can be cached so that for subsequent GET we don't verify bitrot.

**Comment by harshavardhana** [comment]
https://github.com/minio/attic/blob/master/cache/metadata/metadata.go possible data structure that can be used.

**Comment by GarimaKapoor** [comment]
please update the timeline.

**Comment by harshavardhana** [comment]
> please update the timeline.

July 1st.
