### ISSUE TITLE
non-default port for minio.

### ISSUE THREAD

**Issue by drook** [minio/minio#1963]
## Expected behaviour

I expected to read about this in docs. Or in `minio --help` output.
## Actual behaviour

No article found. Nothing is explained in `--help` output.
## Steps to reproduce the behaviour

make something listen on tcp/9000. Install minio. Start wondering what to do.
## Minio version
- (paste output of `minio version`)
  Version: 2016-06-03T19:32:05Z
  Release-Tag: RELEASE.2016-06-03T19-32-05Z
  Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074
## System information

Linux enceladus 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Thanks @drook, it is unfortunate you weren't able to find the relevant docs. We will fix it. 

The information is at the 'subcommand' level which explains various options. 

```
$ minio server
NAME:
  minio server - Start object storage server.

USAGE:
  minio server [OPTIONS] PATH

OPTIONS:
  --address ":9000" 

ENVIRONMENT VARIABLES:
  MINIO_ACCESS_KEY: Access key string of 5 to 20 characters in length.
  MINIO_SECRET_KEY: Secret key string of 8 to 40 characters in length.

EXAMPLES:
  1. Start minio server.
      $ minio server /home/shared

  2. Start minio server bound to a specific IP:PORT, when you have multiple network interfaces.
      $ minio server --address 192.168.1.101:9000 /home/shared

  3. Start minio server on Windows.
      $ minio server C:\MyShare

  4. Start minio server 12 disks to enable erasure coded layer with 6 data and 6 parity.
      $ minio server /mnt/export1/backend /mnt/export2/backend /mnt/export3/backend /mnt/export4/backend \
          /mnt/export5/backend /mnt/export6/backend /mnt/export7/backend /mnt/export8/backend /mnt/export9/backend \
          /mnt/export10/backend /mnt/export11/backend /mnt/export12/backend
```

**Comment by harshavardhana** [comment]
Other relevant quick start docs are available at https://docs.minio.io

**Comment by Odaeus** [comment]
This appears to still be an issue, I can't find mention of it in the linked documentation and thankfully stumbled upon this ticket.
