### ISSUE TITLE
The file was deleted after reaching its lifecycle expiration, but the inode still remains. 

### ISSUE THREAD

**Issue by adababys** [minio/minio#19632]
## NOTE
![delete-file-but-not-inode](https://github.com/minio/minio/assets/8872412/e6b0a636-2dda-47cc-8f0c-3ece2e86e6f0)
I have 40 buckets, each with a lifecycle set to expire in 1 day. Each bucket uploads 1.6 million 150K files every day. After a while, the inodes are exhausted. I have observed that the files have been successfully deleted due to the lifecycle policy, but the inodes have not been reclaimed. 

## Expected Behavior
 I believe that when a file is deleted, all inodes associated with the file should be removed and reclaimed.

## Current Behavior
inodes are exhausted. 

* Version used (`minio --version`): 2022-08-22
* Server setup and configuration: 3 nodes with 8 disks each
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment]
MinIO does not manage inodes; your filesystem does. For performance related questions look into our [subscriptions](https://min.io/pricing).

No need to open an issue. You already [https://github.com/minio/minio/discussions/19630](opened a discussion).
