### ISSUE TITLE
Minio downloads files occasionally waiting for response

### ISSUE THREAD

**Issue by stefanxfy** [minio/minio#19659]
## Expected Behavior
1、wget waiting response

![fc9a99c9022435dfce7393ffe0d5f09d](https://github.com/minio/minio/assets/32997428/29bdfeea-b9b6-4ab6-89dc-8664bb43f4a3)

2、ls -l ,Stuck and unresponsive
![7e62fc4f0c4326c70fc5d45296f16674](https://github.com/minio/minio/assets/32997428/e3c4740a-dbc6-4f3d-9794-7c09c438ac98)

3、There are a large number of nfs refresh inode events
trace-cmd
<img width="1676" alt="企业微信截图_44b163a4-9c95-4de7-8646-93655a768a7f" src="https://github.com/minio/minio/assets/32997428/294ac849-3b0d-40b0-a55e-518ba2947b27">

Guessing a large number of NFS refresh inode events, causing Minio to download files normally and become unresponsive, but why are there a large number of NFS refresh inode events? I don't know yet

Does Minio regularly scan the bucket directory? Is there any change in the bucket, such as file expiration?

Is it related to Minio's object lifecycle management? We use mini, and a bucket can store tens or even hundreds of terabytes of files. If we regularly scan the bucket directory, will the scanning behavior affect the normal download function due to the large number of files stored in the bucket.

Please help analyze the reason and how to solve this problem

**Comment by klauspost** [comment]
NFS is not a recommended backend. Use xfs.

We can't help you debugging nfs issues.

**Comment by stefanxfy** [comment]
Why is NFS not recommended for use

> NFS is not a recommended backend. Use xfs.
> 
> We can't help you debugging nfs issues.
