### ISSUE TITLE
Why does Minio not recommend using NFS ?

### ISSUE THREAD

**Issue by stefanxfy** [minio/minio#19664]
Why does Minio not recommend using NFS ?

https://github.com/minio/minio/issues/19659

**Comment by harshavardhana** [comment]
Because NFS is terrible at latency, consistency and performance.

**Comment by stefanxfy** [comment]
> Because NFS is terrible at latency, consistency and performance.

Thanks

**Comment by harshavardhana** [comment]
You can use NFSv4 to some extent with a single node single drive setup. But there are no guarantees on performance etc.

**Comment by stefanxfy** [comment]
> You can use NFSv4 to some extent with a single node single drive setup. But there are no guarantees on performance etc.

Let me describe the current usage background: The customer provided a large NAS storage server, and the virtual machine mounted this NAS to the/mnt directory, and started minio on a single node in the/mnt directory.

There are more than ten virtual machines like this, each storing approximately 5-10T files.

Occasionally, downloading a small file while waiting for a response will occur, and it will last for about 10 minutes. Trace cmd found that there will be a large number of NFS refresh inode events.

It is currently difficult to adjust this deployment method, and this usage scenario will continue to exist. Can you help analyze whether it is related to the mini object lifecycle management function. Or provide other analytical ideas. Thank you.
<img width="1676" alt="企业微信截图_44b163a4-9c95-4de7-8646-93655a768a7f" src="https://github.com/minio/minio/assets/32997428/d99ed229-dd98-470d-b926-6bf7244bbaaf">

**Comment by harshavardhana** [comment]
If backend becomes unavailable we really cannot do much.

**Comment by stefanxfy** [comment]
> If backend becomes unavailable we really cannot do much.

Thanks.
