### ISSUE TITLE
How to use Minio instructions point to a mc client for darwin only

### ISSUE THREAD

**Issue by sebbel** [minio/minio#1966]
Would be nice if this could be more generalized.

**Comment by hackintoshrao** [comment]
@sebbel : Again, thanks for your feedback. Will get this fixed soon.

**Comment by harshavardhana** [comment]
> Would be nice if this could be more generalized.

When you run the server on a particular OS the message is printed for the relevant OS. 

We kept the README.md simpler by picking a OS as it is usually nicer to be able to copy a working link.

**Comment by harshavardhana** [comment]
Closing this 'minio server' command already provides platform specific message, other OS specific messages are kept at - https://docs.minio.io/
