### ISSUE TITLE
MinIO mc CLI can't handle adding lifecycle policies concurrently

### ISSUE THREAD

**Issue by AlbertoPuritano** [minio/minio#19675]
## Expected Behavior
When adding lifecycle policies to a bucket in a concurrent way (es. with IaC tools such as Terraform, or with multithread scripting) MinIO should add all of them to the referenced bucket.

## Current Behavior
At the moment MinIO only adds a single random policy and discards the others, even though the command runs successfully.

## Steps to Reproduce (for bugs)
I only had the chance of encountering this bug via terraform, but it can be simply reproduced by running a couple of concurrent api or cli requests that add bucket lifecycle policies.
1. Use a terraform "null-resource" module
2. Use a local exec provisioner that uses mc: `   provisioner "local-exec" { command = "mc alias --insecure set minio ${self.triggers.endpoint} ${self.triggers.username} ${self.triggers.password} &&  mc --insecure ilm rule add minio/${self.triggers.name} --expire-days ${self.triggers.expiration_days} --prefix ${self.triggers.prefix} }"`

## Context
This issue forced us to add a fixed sleep time between calls to the server in order to make adding lifecycle policies work. 

## Your Environment
* MC -> mc version RELEASE.2024-02-16T11-05-48Z
* PC -> Darwin MacBook.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; RELEASE_ARM64_T6000 arm64
* Server -> MinIO image version RELEASE.2023-11-15T20-43-25Z running on Kubernates Version: {Major:"1", Minor:"25", GitVersion:"v1.25.16+rke2r1"}

**Comment by harshavardhana** [comment]
The call is single atomic @AlbertoPuritano call whichever completes at the end gets to have the final say on the lifecycle configuration.

**Comment by harshavardhana** [comment]
API calls in S3 are atomic, and there is no append() functionality here. 

`mc` cannot circumvent this since it is impossible to atomicity for 

- read
- update
- write

Since there is no such API in AWS S3, both are distinct, self-contained calls. You really want   ILM to be exact and use the API directly; otherwise, using `mc` will not be synchronized properly due to the inherent nature of these APIs.

We cannot make it stateful.
