### ISSUE TITLE
Minio Upgrade from FileSystem Mode to ServerMode

### ISSUE THREAD

**Issue by reysravanga** [minio/minio#19671]
Hi Team, 

I am following the below document for migrating and upgrade the minio from very Old version to stable version in my kubernetes Setup.
https://min.io/docs/minio/container/operations/install-deploy-manage/migrate-fs-gateway.html

Above documents suggests me to use minio client to copy data from old Version to New Minio version , Since i have almost 2 TB data its taking lot of time to copy the data between new and old minio, Also while mirrorring the data from Old minio to new Minio  i should not write the data to old minio which causes the downtime. 

## Expected Behavior
It should b seamless migration and upgrade to mirror data and upgrade minio without downtime

## Current Behavior
1. Mirroring Data is Time consuming and expensive task - copying 2 TB took almost 8 hours 
2. While mirroring data there shouldn't be any writes on the writes on the minio , causes down time for me again.

**Comment by harshavardhana** [comment]
There is no such seamless migration possible,

These are entirely legacy systems, you can simply tar your entire mount on the filesystem and transfer to MinIO and untar on the server side via our snowball extract feature.

https://www.google.com/amp/s/blog.min.io/minio-optimizes-small-objects/amp/
