### ISSUE TITLE
Logs duplication

### ISSUE THREAD

**Issue by MilosK-sp** [minio/minio#19689]
Hello
I'm trying to integrate audit logs with logstash (I'm sending audit logs from minio to logstash TCP port)
for some reason we are receiving logs for the same operation multiple times
any ideas what could be wrong?
I'm using minio:RELEASE.2024-04-18T19-09-19Z docker setup with 4 nodes and 2 drives per node.
Thanks

![Screenshot 2024-05-07 at 15 47 05](https://github.com/minio/minio/assets/166639339/74ea9fb4-864e-478c-85f9-4d9668d558c5)

**Comment by ghost** [comment]
Another thing I have noticed is that when I restart minio cluster (e.g. mc admin service restart <alias>), we start receiving logs for a few operations that were executed while the minio was down or just after it started and logs for those operations are repeating over and over
![Screenshot 2024-05-07 at 16 43 08](https://github.com/minio/minio/assets/166639339/975c771c-cfa3-478f-94b2-5897a656b61e)

I was told to raise the issue here by Klaus Post via the slack channel
He checked and confirmed that there were no apparent changes to latest release
However, I'm not raising this as a bug in recent changes but something that I faced when I tried to integrate audit logs (I'm doing this first time).

**Comment by harshavardhana** [comment]
Please share your configuration `mc admin config export alias/`

**Comment by ghost** [comment]
```
subnet license= api_key= proxy=
# callhome enable=off frequency=24h
drive max_timeout=
site name= region=
api requests_max=0 requests_deadline=10s cluster_deadline=10s cors_allow_origin=*,force-feed-minio.dev.src777.com remote_transport_deadline=2h list_quorum=strict replication_priority=auto replication_max_workers=500 transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m odirect=on gzip_objects=off root_access=on sync_events=off object_max_versions=9223372036854775807
scanner speed=default alert_excess_versions=100 alert_excess_folders=50000
batch replication_workers_wait=0ms keyrotation_workers_wait=0ms expiration_workers_wait=0ms
# compression enable=off allow_encryption=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml,binary/octet-stream
# identity_openid enable= display_name= config_url= client_id= client_secret= claim_name=policy claim_userinfo= role_policy= claim_prefix= redirect_uri= redirect_uri_dynamic=off scopes= vendor= keycloak_realm= keycloak_admin_url=
# identity_ldap enable= server_addr= srv_record_name= user_dn_search_base_dn= user_dn_search_filter= group_search_filter= group_search_base_dn= tls_skip_verify=off server_insecure=off server_starttls=off lookup_bind_dn= lookup_bind_password=
# identity_tls skip_verify=off
# identity_plugin url= auth_token= role_policy= role_id=
# policy_plugin url= auth_token= enable_http2=off
# logger_webhook enable=off endpoint=http://gdc-als-arch01.msgreen.dom:5053 auth_token= client_cert= client_key= proxy= queue_size=100000 queue_dir= batch_size=1
# audit_webhook enable=off endpoint= auth_token= client_cert= client_key= batch_size=1 queue_size=100000 queue_dir=
# MINIO_AUDIT_WEBHOOK_ENABLE_logstash=on
# MINIO_AUDIT_WEBHOOK_ENDPOINT_logstash=http://gdc-als-arch01.msgreen.dom:5053
audit_webhook:logstash
# audit_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off version= queue_size=100000 queue_dir=
# notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
# notify_amqp enable=off url= exchange= exchange_type= routing_key= mandatory=off durable=off no_wait=off internal=off auto_deleted=off delivery_mode=0 publisher_confirms=off queue_limit=0 queue_dir=
# notify_kafka enable=off topic= brokers= sasl_username= sasl_password= sasl_mechanism=plain client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir= version= batch_size=0 compression_codec= compression_level=
# notify_mqtt enable=off broker= topic= password= username= qos=0 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0
# notify_nats enable=off address= subject= username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 jetstream=off streaming=off streaming_async=off streaming_max_pub_acks_in_flight=0 streaming_cluster_id= queue_dir= queue_limit=0
# notify_nsq enable=off nsqd_address= topic= tls=off tls_skip_verify=off queue_dir= queue_limit=0
# notify_mysql enable=off format=namespace dsn_string= table= queue_dir= queue_limit=0 max_open_connections=2
# notify_postgres enable=off format=namespace connection_string= table= queue_dir= queue_limit=0 max_open_connections=2
# notify_elasticsearch enable=off url= format=namespace index= queue_dir= queue_limit=0 username= password=
# notify_redis enable=off format=namespace address= key= password= queue_dir= queue_limit=0 user=
# lambda_webhook enable=off endpoint= auth_token= client_cert= client_key=
# etcd endpoints= path_prefix= coredns_path=/skydns client_cert= client_cert_key=
# cache enable=off endpoint= block_size=
browser csp_policy="default-src 'self' 'unsafe-eval' 'unsafe-inline';" hsts_seconds=0 hsts_include_subdomains=off hsts_preload=off referrer_policy=strict-origin-when-cross-origin
storage_class standard= rrs=EC:1 optimize=availability
heal bitrotscan=off max_sleep=250ms max_io=100 drive_workers=
```

**Comment by klauspost** [comment]
Could be a regression from https://github.com/minio/minio/pull/19275 - but just speculating.

**Comment by ghost** [comment]
is there any inspection that I can perform? I guess admin logs are not very useful

**Comment by ghost** [comment]
is there anything else I could try to provide more info here?

**Comment by klauspost** [comment]
Should be good for now.

**Comment by zveinn** [comment]
I will have a look at this today

**Comment by zveinn** [comment]
can you try running the command shown below and tell me if log duplication stops ?

`
$ mc admin config reset [ALIAS] logger_webhook
`

There seems to be a logger webhook pointing to the same endpoint, even though it is disabled I just want to reset it to make sure it's not causing issues.

**Comment by zveinn** [comment]
Also, if you curl http://gdc-als-arch01.msgreen.dom:5053 what kind of response code do you get ?

**Comment by ghost** [comment]
Executed:
```
mc admin config reset local logger_webhook
'logger_webhook' is successfully reset.
```
but the duplication is still present.

Tried the following:
```
curl -v http://gdc-als-arch01.msgreen.dom:5053
* About to connect() to gdc-als-arch01.msgreen.dom port 5053 (#0)
*   Trying 172.30.170.5...
* Connected to gdc-als-arch01.msgreen.dom (172.30.170.5) port 5053 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: gdc-als-arch01.msgreen.dom:5053
> Accept: */*
>
```
for this we are using logstash TCP input plugin to process requests and send them directly to ELK
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html

**Comment by zveinn** [comment]
hmmm, this could be the culprit right here. I'm pretty sure the logging mechanism is expecting a success response, as in status code 200, once data has been sent. If not, it'll retry. 

Let me run through the code a bit to confirm.

**Comment by zveinn** [comment]
yes, the audit_webhook is sending http post requests, you probably want to use the http input plugin.
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html

**Comment by ghost** [comment]
Ok, I will have a look as well tomorrow
but it makes sense, if the response is not returned the logic will probably timeout and try again
but I would expect that some kind of confirmation is returned since the request was definitely received and processed (I saw it in the log for curl that I performed)

and yes, we are using input plugin
here's how it looks like:
```
input {
  tcp {
    port => 5053
    codec => line
    type => "minio_json"
  }
}
```

**Comment by zveinn** [comment]
You said you were using the TCP plugin right ? 
The TCP plugin probably won't respond to HTTP since it's meant for pure  socket to socket transfer. Like stdout/stderr etc.. 

You probably need the HTTP specific input plugin, that one (most likely) will provide the response needed.

**Comment by ghost** [comment]
yes yes, we are using an input plugin but it's tcp
I will check if we can use http but it makes sense, http seems more suitable for this use case

I'll provide an update here when I test how http plugin works
thanks!

**Comment by ghost** [comment]
After changing the input to plugin to 'http' we don't have duplications anymore.
Thanks a lot!

**Comment by zveinn** [comment]
np!
