### ISSUE TITLE
cannot read logs on docker

### ISSUE THREAD

**Issue by ilteoood** [minio/minio#19693]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I'm actually using MinIO as a test container for my microservice.
Until yesterday, to understand if the container is ready, I used to read the logs and search for the `1 Online` string.

From today, with the latest version released ~14 hours ago, I'm not able to read logs from docker anymore.

## Expected Behavior
I can read logs content using docker apis

## Current Behavior
Logs content is empty

## Steps to Reproduce (for bugs)
This is the code I'm actually using to run it:
```
const s3Port = (await s3Instance.config.endpoint?.())!.port;
    this.runningContainer =
      await S3DockerController.dockerConnection.createContainer({
        Image: IMAGE,
        Cmd: ['server', '/data'],
        HostConfig: {
          PortBindings: {
            '9000': [{ HostPort: `${s3Port}` }],
          },
        },
        ExposedPorts: {
          '9000': {},
        },
        Env: [
          `MINIO_ACCESS_KEY=${parsedEnv.AWS_ACCESS_KEY_ID}`,
          `MINIO_SECRET_KEY=${parsedEnv.AWS_SECRET_ACCESS_KEY}`,
          `MINIO_ADDRESS=0.0.0.0:9000`,
        ],
        name: `${CONTAINER_PREFIX}-${Date.now()}-${s3Port}`,
      });

    await this.runningContainer.start();
   for await (const useStdErr of setInterval(100, 0)) {
      const logs = await this.runningContainer!.logs({
        stdout: true,
        stderr: Boolean(useStdErr),
      });
      const isReady = logs?.toString().includes('1 Online');
      if (isReady) {
        break;
      }
    }
```

## Regression

Yes

RELEASE.2024-05-07T06-41-25Z

## Your Environment
Docker, Node 20

**Comment by harshavardhana** [comment]
```
docker run --rm minio/minio:latest server /data
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: RELEASE.2024-05-07T06-41-25Z (go1.22.2 linux/amd64)

API: http://172.17.0.2:9000  http://127.0.0.1:9000 
WebUI: http://172.17.0.2:41167 http://127.0.0.1:41167 

Docs: https://min.io/docs/minio/linux/index.html
Status:         1 Online, 0 Offline. 
STARTUP WARNINGS:
- Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
- The standard parity is set to 0. This can lead to data loss.
```

Seems to show up fine.

**Comment by harshavardhana** [comment]
You should be using `mc ready` to check if the deployment is ready not read random strings in the output of the UI. 

Those strings can change anytime they are not binding to any contract like an API. Rely on things like liveness and readiness checks for valid ways to monitor if MinIO is online.

**Comment by ilteoood** [comment]
@harshavardhana 
Why asking for a reproduction if then is not used?

Logs gets printer correctly, but when I try to retrieve them from docker's API they don't come up. With the previous release this is not happening.

Atm mc is not a solution, since minio is not used in production.
