### ISSUE TITLE
Single driver minio cannot delete objects

### ISSUE THREAD

**Issue by ooninoo** [minio/minio#19696]
## NOTE
minio deploy with single driver, when keeping runing a period of time，we found delete objects not effect。
![Screen Shot 2024-05-08 at 18 50 26](https://github.com/minio/minio/assets/128034338/be5e6fab-7082-4a50-bce0-07bf318b5533)

try using `--debug`  to see request detail, not found any error.

try using `mc admin trace --call storage local` to seen， no error

but, this problem can resolve by restart minio service.

## Steps to Reproduce (for bugs)

1. mc rm local/dbs/cherrypy-main.zip
2. mc ls local/dbs/

## Environment
minio conf:

```console
MINIO_ROOT_USER=root
MINIO_ROOT_PASSWORD=password
MINIO_BROWSER=off
MINIO_PROMETHEUS_AUTH_TYPE=public
```

minio version:
```console
# minio -version
minio version RELEASE.2024-02-26T09-33-48Z (commit-id=92788e4cf4aa5fc7c42227642f206482fccecaf1)
Runtime: go1.21.7 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
```

mc version:
```console
# mc -version
mc version RELEASE.2024-02-24T01-33-20Z (commit-id=f17313e7ab892fa5c7561a63296b68c1691f9b2b)
Runtime: go1.21.7 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

filesystem is ext4

**Comment by klauspost** [comment]
Upgrade to latest and retry. Also post what filesystem you are using for minio data.

**Comment by ooninoo** [comment]
> Upgrade to latest and retry. Also post what filesystem you are using for minio data.

filesystem is ext4, I will upgrade to the latest version and keep watching

**Comment by harshavardhana** [comment]
Closing this issue.

**Comment by ooninoo** [comment]
> Closing this issue.

why closeing this issue

**Comment by harshavardhana** [comment]
> why closeing this issue

this is already fixed.
