### ISSUE TITLE
feat: Improve SourceIp and UserAgent usability for SFTP connections.

### ISSUE THREAD

**Issue by olljanat** [minio/minio#19698]
**Is your feature request related to a problem? Please describe.**
### SourceIp
SFTP server connects to MinIO by using localhost address
https://github.com/minio/minio/blob/8b660e18f26b36cc11a51aad0d806d03b917784d/cmd/sftp-server-driver.go#L83
which why it is possible to use policy like this to allow access to buckets with S3 but prevent it from SFTP clients:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Condition": {
                "NotIpAddress": {
                    "aws:SourceIp": [
                        "127.0.0.1/32"
                    ]
                }
            }
        }
    ]
}
```

### UserAgent
UserAgent is currently hardcoded in [Go SDK](https://github.com/minio/minio-go/blob/c2fe17945c8d0b203fa01e4d04a8adf93ccf2d9f/api.go#L140C28-L140C34)
which why it is possible to use policy like this to allow access to buckets with S3 but prevent it from SFTP clients:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Condition": {
                "StringNotLike": {
                    "aws:UserAgent": [
                        "MinIO *"
                    ]
                }
            }
        }
    ]
}
```

**Describe the solution you'd like**
It would be nice if SFTP server would have own documented UserAgent which can be used to block SFTP connections.
Also would be nice if `SourceIp` would works same way that for S3 connections. It should be possible to to achieve it by setting SFTP client IP to header `X-Forwarded-For` when calling backend.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by klauspost** [comment]
We do not have any plans for this.

You are welcome to submit a PR or reach out to `sales@min.io` to engage commercially and we can evaluate it in that context.

**Comment by olljanat** [comment]
@klauspost OK, I can create PR but perhaps you still want to comment about right way to implement this?

I was thinking to set `CustomRequestHeaders` in here? (and support for it in minio-go side)
https://github.com/minio/minio/blob/9a267f92708036cb21158e193ebe9dab030864dd/cmd/sftp-server-driver.go#L156-L160

Values would be something like `MinIO SFTP Server` in user agent and `ssh.ConnMetadata.RemoteAddr()` (which should contain client IP) in X-Forwarded-For header.

Context is ability to have MinIO's SFTP server published to internet but block those connections from everyone else than whitelisted sources.
