### ISSUE TITLE
aws:groups does not work in policies

### ISSUE THREAD

**Issue by olljanat** [minio/minio#19700]
## Expected Behavior
#16538 added support for `aws:groups` but as far I see it does not work. Test automation only exists for `jwt:groups` so most likely there is some logic issue.

## Current Behavior
I added logging line
```go
logger.Error(fmt.Sprintf("getConditionValues called: Username %v, claims: %v, groups %v", username, claims, groups))
```
to below this one:
https://github.com/minio/minio/blob/8b660e18f26b36cc11a51aad0d806d03b917784d/cmd/bucket-policy.go#L77-L84
and what I see is messages like these even when user is part of the group:
```
getConditionValues called: Username ANTTQ5LPWPWYV8WFYKUS, claims: map[accessKey:ANTTQ5LPWPWYV8WFYKUS exp:1.715220743e+09 parent:test], groups []
getConditionValues called: Username test, claims: map[], groups []
```

## Possible Solution
Perhaps order of code needs to be changed in way that `cred.Groups` get populated before `getConditionValues` function is called.

**Comment by harshavardhana** [comment]
aws:groups doesn't exist unless you have LDAP or OpenID enabled 

- ldap:groups
- jwt:groups

**Comment by olljanat** [comment]
@harshavardhana hmm, comment in https://github.com/minio/minio/issues/11303#issuecomment-1416679978 and documentation in https://github.com/minio/minio/blob/8b660e18f26b36cc11a51aad0d806d03b917784d/docs/multi-user/README.md?plain=1#L271 are quite confusing.

Isn't MinIO always acting as IDP for users which are created directly to it?

And if either LDAP or OpenID is needed the what is use case of `aws:groups`?
