### ISSUE TITLE
Visualize file without download it minio

### ISSUE THREAD

**Issue by arian360** [minio/minio#19704]
I'm utilizing Minio for file storage, and I want to view certain files directly from my browser without having to download them. I've attempted to generate a pre-signed URL for this purpose, but unfortunately, it still prompts for download. Here's the code snippet I used:

```python
# Generate pre-signed URL with read access for 2 hours
url = MINIO_CLIENT.get_presigned_url(
    "GET",
    "example4-bucket",
    object_name,
    expires=timedelta(hours=2),
)
print("View URL for image.jpg:", url)
```

**Comment by harshavardhana** [comment]
@arian360 that needs to be done via setting up correct content-type for the object so that the browser can invoke HTML5 primitives properly.
