### ISSUE TITLE
Set continuous retry in "mc mirror --retries "

### ISSUE THREAD

**Issue by kamauz** [minio/minio#19711]
**Is your feature request related to a problem? Please describe.**
Having a minio instance installed on an edge location and a minio instance installed on a cloud location, it would be fine to set a continuous retry of the mirror replica in case the source is not reachable

**Describe the solution you'd like**
I would like to set something like `--retry-loop` to continuously retry a replica

**Comment by harshavardhana** [comment]
```
while true;
   mc mirror
done
```

**Comment by kamauz** [comment]
@harshavardhana Yesterday I made some test by running `mc mirror --retries .... ` task. I switched off the source minio instance, but then after the 3 retries the task did not conclude.

If the task does not conclude, a while solution won't help me

On the other hand, the progress bar was never useful for the replica completion in time. I saw a fixed "100%" indication even if it the destination was still pooling the files
