### ISSUE TITLE
a bug? Dockerfile missing path

### ISSUE THREAD

**Issue by i0FFLINE** [minio/minio#19723]
https://github.com/minio/minio/blob/e8d14c0d90db28c455101ace1c3d28a92118b4a7/Dockerfile#L3

`minio` is missing ?

**Comment by jiuker** [comment]
dev Dockerfile

**Comment by i0FFLINE** [comment]
> dev Dockerfile

explain please

**Comment by jiuker** [comment]
You can run `make docker`. That will build minio-server and docker build an dev image.
