### ISSUE TITLE
Activating MINIO_API_SELECT_PARQUET not works

### ISSUE THREAD

**Issue by masalinas** [minio/minio#19721]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I have and active Minio tenant. I activate the environment variable **MINIO_API_SELECT_PARQUET**  from **Minio Operator** (see the capture) to read parquet files. But when try to parse the file from a python sample minio response:

`An error occurred (InternalError) when calling the SelectObjectContent operation (reached max retries: 4): We encountered an internal error, please try again.: cause(parquet format parsing not enabled on server)`

![Captura de pantalla 2024-05-10 a las 23 12 05](https://github.com/minio/minio/assets/1216181/1cee9f36-b2be-45e6-8a24-9590fc74972d)

This is the piece of code in python:

```
import boto3

s3 = boto3.client('s3',
                  endpoint_url='https://localhost:9000',
                  aws_access_key_id='BsvW9jlpYX8TvD9F',
                  aws_secret_access_key='HrGdJapKsXbKEcXABWNQ2CO15v3y9MMk',
                  verify=False,
                  region_name='us-east-1')

r = s3.select_object_content(
    Bucket='uniovi',
    Key='sample.parquet',
    ExpressionType='SQL',
    Expression="select * from s3object",
    InputSerialization={'Parquet': {}},
    OutputSerialization={'CSV': {}},
)

for event in r['Payload']:
    if 'Records' in event:
        records = event['Records']['Payload'].decode('utf-8')
        print(records)
    elif 'Stats' in event:
        statsDetails = event['Stats']['Details']
        print("Stats details bytesScanned: ")
        print(statsDetails['BytesScanned'])
        print("Stats details bytesProcessed: ")
        print(statsDetails['BytesProcessed'])
```

## Expected Behavior
Read parquet files

## Current Behavior
I can not read parquet files

## Your Environment

* Version used (`minio --version`): Minio Operator 5.0.12
* Server setup and configuration: minikube 0.041
* Operating System and version (`uname -a`): Mac sonoma
* Python Boto3 dependency

**Comment by jiuker** [comment]
Post your pod yaml here please. @masalinas

**Comment by masalinas** [comment]
@jiuker I used the helm chart to deploy minio operator in minikube like this

```
$ helm install \
  --namespace minio-operator \
  --create-namespace \
  operator minio-operator/operator
```

The problem is that when I created the minio tenant from the operator console I didn't add the MINIO_API_SELECT_PARQUET environment variable like this:

![Captura de pantalla 2024-05-12 a las 20 56 52](https://github.com/minio/minio/assets/1216181/747f5f9f-c78d-4001-b09a-324328ba2707)

But later editing the tenant I added this env variable like this, but the tenant not change, maybe the unique way to activate the parquet is removing the tenant and recreate again with this env variable?, what do you think?

![Captura de pantalla 2024-05-12 a las 20 58 17](https://github.com/minio/minio/assets/1216181/29045728-0aa5-4e0b-86e1-1dc5808a6f30)

**Comment by harshavardhana** [comment]
Can you provide your tenant yaml via `kubectl describe pods` and also exec into the pod and share `env | grep -i minio_`

**Comment by harshavardhana** [comment]
> Can you provide your tenant yaml via `kubectl describe pods` and also exec into the pod and share `env | grep -i minio_`

Please provide these details, closing this issue until then.
