### ISSUE TITLE
Once Again, PHP SDK with Minio Server

### ISSUE THREAD

**Issue by hernandev** [minio/minio#1973]
## Expected behaviour

A download
## Actual behaviour

`The request signature we calculated does not match the signature you provided. Check your key and signing method.`
## Steps to reproduce the behaviour

``` php
$config = [
    "driver" => "s3",
    "region" => "us-east-1",
    "bucket" => "bucket-name",
    "endpoint" => "https://minio.server.com",
    "version" => "2006-03-01", // or latest
    "credentials" => [
        "key" => "redacted",
        "secret" => "redacted",
    ],
];

$s3 = new S3Client($config);

$cmd = $s3->getCommand('GetObject', [
    'Bucket' => 'bucketname',
    'Key'    => 'objectkey'
]);

$request = $s3->createPresignedRequest($cmd, '+20 minutes');

$url = (string) $request->getUri();
```
## Minio version
- (paste output of `minio version`)
  Version: 2016-06-24T02:14:42Z
  Release-Tag: DEVELOPMENT.2016-06-24T02-14-42Z
  Commit-ID: 41c089a7e048456ccdb2db5f23eaefa759aa5f24
  ## System information

So there are other issues open about it, but none seens to switch the problem on the recent verions

I've built minion from scratch, and PHP SDK is on it's latest version.

If you guys could help understand the why if this problem, i can try to fix and PR.

Thanks so much

**Comment by hackintoshrao** [comment]
@hernandev : Thanks for reporting. Let me try this and revert back you.

**Comment by harshavardhana** [comment]
As debugged this is as aws-sdk-php bug, presigned URL generated is inconsistent with AWS S3 Signature V4 documents. 

For correct results we picked aws-sdk-go and works fine with Minio server. 

```
$ cat /tmp/test.go 
package main

import (
    "log"
    "time"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/credentials"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
)

func main() {
    creds := credentials.NewStaticCredentials("4D0SJ9V12VAWDHTH7LIC",
        "BPSMtJTcQZOJATBW48iXs0RaIkOY7/c268HN0l3W", "")
    config := aws.NewConfig().
        WithCredentials(creds).
        WithRegion("us-east-1").
        WithEndpoint("http://45.79.128.85:9000").
        WithDisableSSL(true).
        WithS3ForcePathStyle(true)

    svc := s3.New(session.New(config))
    req, _ := svc.GetObjectRequest(&s3.GetObjectInput{
        Bucket: aws.String("videos"),
        Key:    aws.String("CODECASTS-less-variaveis-pt-1174.mp4"),
    })
    urlStr, err := req.Presign(15 * time.Minute)

    if err != nil {
        log.Println("Failed to sign request", err)
    }

    log.Println("The URL is", urlStr)
}
```

We will work with aws-sdk-php to close this issue.

**Comment by harshavardhana** [comment]
Closing this as aws-sdk-php upstream issue,  server is working as expected.

**Comment by hernandev** [comment]
For future references on any PHP developer trying to use with minio.io, you can use my patched fork while the issue is not solved into the main SDK repository

**For default SDK**
`composer require codecasts/aws-sdk-php`

**For Laravel integration (Flysystem driver)**
`composer require codecasts/flysystem-aws-s3-v3`

**Comment by kojidev** [comment]
Is is still relevant? Is there an issue in `aws/aws-sdk-php`?
