### ISSUE TITLE
There are some error when runing systemctl status minio,but when everything is ok when runing mc admin info.

### ISSUE THREAD

**Issue by Songfeiyu1** [minio/minio#19740]
Hello,
I am configuring a MINIO system by using 4 servers with 12 drviers on each server, and runing the version with RELEASE.2024-05-10T01-41-38Z. but there will be some error informaiton after i run the command systemctl status minio, here is some error information for some nodes.But when i run the command mc admin info myminio, it shows all drivers and network is ok. So, is it a bug for minio system, or  a configure issue for my minio system?
******************************************************************************************************************************
the logs for node oss243
May 14 22:46:41 oss243.myminio.com minio[2159]: All MinIO sub-systems initialized successfully in 36.115811ms
May 14 22:46:41 oss243.myminio.com minio[2159]: MinIO Object Storage Server
May 14 22:46:41 oss243.myminio.com minio[2159]: Copyright: 2015-2024 MinIO, Inc.
May 14 22:46:41 oss243.myminio.com minio[2159]: License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
May 14 22:46:41 oss243.myminio.com minio[2159]: Version: RELEASE.2024-05-10T01-41-38Z (go1.22.3 linux/amd64)
May 14 22:46:41 oss243.myminio.com minio[2159]: API: http://192.168.100.243:9000  http://192.168.100.243:9000  http://192.168.100.241:9000  http://127.0.0.1:9000
May 14 22:46:41 oss243.myminio.com minio[2159]: WebUI: http://192.168.100.243:9051 http://192.168.100.243:9051 http://192.168.100.241:9051 http://127.0.0.1:9051
May 14 22:46:41 oss243.myminio.com minio[2159]: Docs: https://min.io/docs/minio/linux/index.html
May 14 22:46:41 oss243.myminio.com minio[2159]: Use `mc admin info` to look for latest server/drive info
May 14 22:46:41 oss243.myminio.com minio[2159]:  Status:         24 Online, 24 Offline.

******************************************************************************************************************************
the node for oss244
May 14 22:46:40 oss244.myminio.com minio[2152]: All MinIO sub-systems initialized successfully in>
May 14 22:46:40 oss244.myminio.com minio[2152]: MinIO Object Storage Server
May 14 22:46:40 oss244.myminio.com minio[2152]: Copyright: 2015-2024 MinIO, Inc.
May 14 22:46:40 oss244.myminio.com minio[2152]: License: GNU AGPLv3 - https://www.gnu.org/license>
May 14 22:46:40 oss244.myminio.com minio[2152]: Version: RELEASE.2024-05-10T01-41-38Z (go1.22.3 l>
May 14 22:46:40 oss244.myminio.com minio[2152]: API: http://192.168.100.244:9000  http://192.168.>
May 14 22:46:40 oss244.myminio.com minio[2152]: WebUI: http://192.168.100.244:9051 http://192.168>
May 14 22:46:40 oss244.myminio.com minio[2152]: Docs: https://min.io/docs/minio/linux/index.html
May 14 22:46:40 oss244.myminio.com minio[2152]: Use `mc admin info` to look for latest server/dri>
May 14 22:46:40 oss244.myminio.com minio[2152]:  Status:         24 Online, 24 Offline.

******************************************************************************************************************************
the logs for node oss245

May 14 22:46:41 oss245.myminio.com minio[2142]: Configured max API requests per node based on ava>
May 14 22:46:41 oss245.myminio.com minio[2142]: All MinIO sub-systems initialized successfully in>
May 14 22:46:42 oss245.myminio.com minio[2142]: MinIO Object Storage Server
May 14 22:46:42 oss245.myminio.com minio[2142]: Copyright: 2015-2024 MinIO, Inc.
May 14 22:46:42 oss245.myminio.com minio[2142]: License: GNU AGPLv3 - https://www.gnu.org/license>
May 14 22:46:42 oss245.myminio.com minio[2142]: Version: RELEASE.2024-05-10T01-41-38Z (go1.22.3 l>
May 14 22:46:42 oss245.myminio.com minio[2142]: API: http://192.168.100.245:9000  http://192.168.>
May 14 22:46:42 oss245.myminio.com minio[2142]: WebUI: http://192.168.100.245:9051 http://192.168>
May 14 22:46:42 oss245.myminio.com minio[2142]: Docs: https://min.io/docs/minio/linux/index.html
May 14 22:46:42 oss245.myminio.com minio[2142]: Status:         48 Online, 0 Offline.

******************************************************************************************************************************
the logs for node oss246
May 14 22:46:41 oss246.myminio.com minio[2162]:        1: cmd/erasure-sets.go:239:cmd.(*erasureSets).connectDisks.func2()
May 14 22:46:41 oss246.myminio.com minio[2162]: API: SYSTEM.peers
May 14 22:46:41 oss246.myminio.com minio[2162]: Time: 03:46:41 UTC 05/15/2024
May 14 22:46:41 oss246.myminio.com minio[2162]: DeploymentID: 12988ab7-9030-418e-9486-c45c6b863895
May 14 22:46:41 oss246.myminio.com minio[2162]: Error: Drive: http://oss243.myminio.com:9000/mnt/disk12/minio returned drive not found (*fmt.wrapError)
May 14 22:46:41 oss246.myminio.com minio[2162]:        endpoint="http://oss243.myminio.com:9000/mnt/disk12/minio"
May 14 22:46:41 oss246.myminio.com minio[2162]:        4: internal/logger/logger.go:258:logger.LogAlwaysIf()
May 14 22:46:41 oss246.myminio.com minio[2162]:        3: cmd/logging.go:50:cmd.peersLogAlwaysIf()
May 14 22:46:41 oss246.myminio.com minio[2162]:        2: cmd/prepare-storage.go:51:cmd.init.func22.1()
May 14 22:46:41 oss246.myminio.com minio[2162]:        1: cmd/erasure-sets.go:239:cmd.(*erasureSets).connectDisks.func2()

**************************************************************************************************************************

**Comment by harshavardhana** [comment]
Those messages are normal, they are point in time information which is only during the server start.

Once the server starts they all reconnect back that ensures the correct status.

**Comment by Songfeiyu1** [comment]
> Those messages are normal, they are point in time information which is only during the server start.
> 
> Once the server starts they all reconnect back that ensures the correct status.

Got it, Thank you.
