### ISSUE TITLE
Is there any plan to add a configration for Erasure sets

### ISSUE THREAD

**Issue by Songfeiyu1** [minio/minio#19742]
Hello,
Is there any plan to add a configration for Erasure sets which can customize the number of drviers for a Erasure set?  
As i am running a MINIO with the version of RELEASE.2024-05-10T01-41-38Z by using 4 servers with 48 drivers in totals, and there is 3 Erasure sets with 16 Drives per erasure set by default. i want to change it to 12 Erasure sets with 4 Drives per erasure set.
Thank you.

**Comment by FourSpaces** [comment]
You can set the set size by setting the environment variable `MINIO_ERASURE_SET_DRIVE_COUNT=4`

**Comment by Songfeiyu1** [comment]
Thank you , i have not fond the environment variable of MINIO_ERASURE_SET_DRIVE_COUNT from the docs. and after testing from our end, it`s working for it.

**Comment by harshavardhana** [comment]
> Thank you , i have not fond the environment variable of MINIO_ERASURE_SET_DRIVE_COUNT from the docs. and after testing from our end, it`s working for it.

It is on purpose. This must be set under MinIO's support engineering guidance.

Adding random values here won't benefit everyone without knowing the details.
