### ISSUE TITLE
Since RELEASE.2024-03-26T22-10-45Z console UI is very slow for LDAP authenticated users.

### ISSUE THREAD

**Issue by abisek9186-baloise** [minio/minio#19746]
Console UI is really slow (takes around 20 to 30 seconds to load the object browser). We have around 150 objects across 3 buckets in this minio instance so number of objects should not be an issue.

## Expected Behavior
Console UI should list the objects as fast as root user based login does. 
While browsing via root login, the browsing is very fast,  and akes ~1-2 secs only to load the object browser.

## Current Behavior
Consule UI is realluy slow (takes around 20 to 30 seconds to load the object browser). 
Performance for mc CLI against the MinIO API is consistently fast.

Current env variable which sets the LDAP config for the tenant, is below:

  - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN
    value: "ou=Users,ou=XXX,dc=YYY,dc=com"
  - name: MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER
    value: "(&(objectCategory=person)(sAMAccountName=%s))"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN
    value: "ou=Ressources-GRP,ou=Groups,ou=XXX,dc=YYY,dc=com"
  - name: MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER
    value: "(&(objectClass=group)(member=%d))"

## Your Environment
* Version used (`minio --version`):  Any release after RELEASE.2024-03-26T22-10-45Z behaves the same
* Server setup and configuration: Helm chart based operator installation on OpenShift where operator manages the tenant
* Operating System and version (`uname -a`): OCP 4.14
* MinIO UI/API is exposed through OCP route.

**Comment by harshavardhana** [comment]
@bexsoft we have a community report now for the same issue.

**Comment by acheglakov** [comment]
Hello! We have the same issue. We noticed that the more groups a user has, the slower the console opens. The "mcli ls" command with access keys is also slower.

**Comment by harshavardhana** [comment]
@abisek9186-baloise we haven't been able to reproduce this with any baremetal setups.

**Comment by abisek9186-baloise** [comment]
@harshavardhana thanks for the update. I reported this particular issue on MinIO operator managed MinIO tenants on OpenShift.

**Comment by harshavardhana** [comment]
> @harshavardhana thanks for the update. I reported this particular issue on MinIO operator managed MinIO tenants on OpenShift.

Yeah tried k8s yesterday nothing yet. it looks like we are missing something else here.

Is your LDAP an AD server or OpenLDAP ?

**Comment by abisek9186-baloise** [comment]
We use AD and not OpenLDAP. It could also be an issue with webSockets which I guess used by MinIO console. But we dont see any slowness we use root user to login to MinIO console.
OpenShift routers which publish MinIO routes, are configured to use proxy protocol for all OpenShift routes.
Not sure if below information helps
![image](https://github.com/minio/minio/assets/90322483/fe1e9f85-33ee-487a-a03d-0888930d748d)

**Comment by acheglakov** [comment]
We are using AD and six nodes linux cluster. How could we grub diagnostic info for this issue?

**Comment by harshavardhana** [comment]
Can this be validated against the latest release?

**Comment by abisek9186-baloise** [comment]
Updated to RELEASE.2024-06-13T22-53-53Z

With root user login,
![image](https://github.com/minio/minio/assets/90322483/9d1ebf2f-54df-4559-acdc-bc24b34634e1)

With LDAP user login, now it no longer possible to see the UI.
![image](https://github.com/minio/minio/assets/90322483/bfea332f-d677-4891-bf12-ab8aaf5a66db)

**Comment by harshavardhana** [comment]
Please test with latest release and also provide more details such as mc admin trace -a --response-duration 250ms alias/

**Comment by harshavardhana** [comment]
> Please test with latest release and also provide more details such as mc admin trace -a --response-duration 250ms alias/

Please share this in another 1 day, after that we will consider this issue closed.

**Comment by harshavardhana** [comment]
We are closing this issue as stale with no follow-ups.

**Comment by harshavardhana** [comment]
Was able to reproduce fix in #20320

**Comment by harshavardhana** [comment]
fixed in #20320
