### ISSUE TITLE
minio single-node mode met performance bottleneck

### ISSUE THREAD

**Issue by sunwuyan** [minio/minio#19755]
Hi, 
      since there is no storage class in the kubernetes cluster, but the same network file storage service is mounted on all nodes in the cluster, minio is deployed in the kubernetes cluster in single-node mode. The minio version is RELEASE.2023-07 -11T21-29-34, this minio service has only one bucket, and this bucket contains 200T data. When there are a large number of readers and writers (large files are read and written, and a large number of small files are written), the minio query response time is very long. , I allocated a lot of CPU and memory to this minio pod, but only less than half of it was actually used. The fio test showed that the bandwidth and iops of network file storage are acceptable, and the iops is 13w. I don't know what the bottleneck of minio is at this time. where? How to optimize it? Thanks!

**Comment by harshavardhana** [comment]
> Hi, since there is no storage class in the kubernetes cluster, but the same network file storage service is mounted on all nodes in the cluster, minio is deployed in the kubernetes cluster in single-node mode. The minio version is RELEASE.2023-07 -11T21-29-34, this minio service has only one bucket, and this bucket contains 200T data. When there are a large number of readers and writers (large files are read and written, and a large number of small files are written), the minio query response time is very long. , I allocated a lot of CPU and memory to this minio pod, but only less than half of it was actually used. The fio test showed that the bandwidth and iops of network file storage are acceptable, and the iops is 13w. I don't know what the bottleneck of minio is at this time. where? How to optimize it? Thanks!

You are perfect case to sign-up to our subscription https://min.io/pricing

**Comment by sunwuyan** [comment]
> > Hi, since there is no storage class in the kubernetes cluster, but the same network file storage service is mounted on all nodes in the cluster, minio is deployed in the kubernetes cluster in single-node mode. The minio version is RELEASE.2023-07 -11T21-29-34, this minio service has only one bucket, and this bucket contains 200T data. When there are a large number of readers and writers (large files are read and written, and a large number of small files are written), the minio query response time is very long. , I allocated a lot of CPU and memory to this minio pod, but only less than half of it was actually used. The fio test showed that the bandwidth and iops of network file storage are acceptable, and the iops is 13w. I don't know what the bottleneck of minio is at this time. where? How to optimize it? Thanks!
> 
> You are perfect case to sign-up to our subscription https://min.io/pricing

Why closed my issue?

**Comment by klauspost** [comment]
We do not perform community performance analysis.

**Comment by sunwuyan** [comment]
> We do not perform community performance analysis.

ok，tks!
