### ISSUE TITLE
minio admin UI doesn't show all objects: foo/bar is invisible when foo exists

### ISSUE THREAD

**Issue by pcarrier** [minio/minio#19754]
## Expected Behavior

If foo and foo/bar, show both the object and the "directory".

## Current Behavior

Only the file appears, there's no way to tell that foo/bar exists from the object browser.

## Possible Solution

Show an object and a directory, or show that's both.

## Steps to Reproduce (for bugs)

1. Create a bucket demo
2. Upload files foo and foo/bar
3. Open the object broser
4. See only a `foo` object

## Regression

No.

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2024-05-01T01-11-10Z (commit-id=7926401cbd5cceaacd9509f2e50e1f7d636c2eb8)`
* Server setup and configuration: nothing interesting
* Operating System and version (`uname -a`): `Linux x0.xmit.dev 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 23:43:36 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by harshavardhana** [comment]
Overlapping object names are undefined and not allowed.

If you use them UI will only display the parent object only.

**Comment by klauspost** [comment]
https://min.io/docs/minio/linux/operations/concepts/thresholds.html#conflicting-objects

**Comment by pcarrier** [comment]
OK, so "that's expected, EWONTFIX"? It might be undefined but it certainly is allowed.

**Comment by klauspost** [comment]
Just don't do it. We can't check without a very considerable cost.
