### ISSUE TITLE
http: Graceful shutdown of the web service.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1976]

**Comment by vadmeste** [comment]
How to define the graceful shutdown: it is alerting all go routines that a shutdown is occurring and wait all of them to finish before the total exit.
However, this means four things:
- a go routine which is performing a long continuous task (we can imagine a golang API which is taking a too long time), in this case, we will need to wait for that goroutine to finish to guarantee that we are not prematurely killing it
- a go routine which is blocked and waiting for an event should always listen to the shutdown alert and behaves accordingly.
- a code rewrite is needed when a golang API implicitly create a goroutine
- All goroutines calls will be performed like this:
  `GO(func() {  ... your code .. } )`, the reason is that we need to track all goroutines.

Any thoughts?

**Comment by vadmeste** [comment]
oups, I've just noticed that the title was changed from graceful shutdown of webservice/io to graceful shutdown of webservice

**Comment by harshavardhana** [comment]
Earlier we used this - https://github.com/facebookgo/httpdown , but this has a weird API style and oddly logs with in the http.Server() instance.  Without much control.

**Comment by harshavardhana** [comment]
We should explore if there are any available.. better alternatives.

**Comment by vadmeste** [comment]
How about implementing this by hand ? It is possible to add a new handler which tracks all the connected clients. When graceful shutdown starts, new connections will be forbidden and at the same time we will wait other clients to finish

**Comment by krishnasrinivas** [comment]
how about a global `shutdown chan struct{}` which the go-routines need to watch out for in `select { }`

**Comment by vadmeste** [comment]
yes @krishnasrinivas, we need that if we want goroutines exit as fast as possible

**Comment by jesselucas** [comment]
With it being added to the standard lib in 1.7, would adopting the use of the context package and using it's done chan be a solution? This could help with integrating with external packages/apis in the future. https://blog.golang.org/context

**Comment by nl5887** [comment]
And maybe this is worth looking at as well: https://github.com/facebookgo/grace. Allows graceful restarts (upgrades), without dropping connections.

**Comment by harshavardhana** [comment]
https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/graceful.go - this is the simplest i found.  

> And maybe this is worth looking at as well: https://github.com/facebookgo/grace. Allows graceful restarts (upgrades), without dropping connections.

We have used this before we in-fact had our own version based on this, it was just way too complex and had bugs we removed this in favor of standard HTTP package.

**Comment by nl5887** [comment]
won't the simplest solution will be to stop listening for new requests (return a error here https://github.com/minio/minio/blob/b0b919a1d6622ea6a956c5428fb6a3e4b70e592b/server-mux.go#L143) and waiting for goroutines to wait using a waitgroup (https://github.com/minio/minio/blob/b0b919a1d6622ea6a956c5428fb6a3e4b70e592b/server-mux.go#L174) ? That could be an easy and quick start, while implementing the shutdown chan. First SIGTERM will stop listening, and wait for running goroutines to finish, second SIGTERM will terminate immediately.

**Comment by vadmeste** [comment]
@nl5887, yes that's a simple solution.. we can even add a handler which does that.. However I prefer that we remember in the first place why we need this graceful shutdown.

**Comment by nl5887** [comment]
I think we just don't want to abort running up- and downloads directly. This will play nicer as well in loadbalancing situations where the minio instance will be removed from the cluster, but will finish the current transfers for the exiting node.

**Comment by xiaofan8421** [comment]
Graceful upgrade has been solved now?

**Comment by klauspost** [comment]
@xiaofan8421 No. As mentioned it is not trivial since you all of a sudden have 2 running servers touching the same data.

This is no a feature we are likely to revisit.
