### ISSUE TITLE
spring boot streaming big file to minio failure.

### ISSUE THREAD

**Issue by sendreams** [minio/minio#19772]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

use spring boot receiving big file and stream to minio.

## Current Behavior

show error:
23:15:21.475 [http-nio-8076-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
23:15:27.942 [http-nio-8076-exec-1] INFO  c.w.t.o.m.controller.FileController - upload started! content size: **1244315823**
23:15:27.979 [http-nio-8076-exec-1] ERROR c.w.t.o.m.controller.FileController - unexpected EOF

## Steps to Reproduce (for bugs)

test code:
```java
package com.ware4u.test.obj.minio.controller;
import io.minio.MinioClient;
import io.minio.PutObjectArgs;
import io.swagger.v3.oas.annotations.Operation;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import javax.annotation.PostConstruct;
import javax.servlet.http.HttpServletRequest;
import java.io.InputStream;

@RestController
@io.swagger.v3.oas.annotations.tags.Tag(name = "文件上传", description = "")
@RequestMapping(value = "/api/file")
@Slf4j
public class FileController {
    private MinioClient minioClient;

    @PostConstruct
    public void init() {
        minioClient =
                MinioClient.builder()
                        .endpoint("http://localhost:9000")
                        .credentials("minioadmin", "minioadmin")
                        .build();
    }

    @Operation(summary = "上传文件", description = "")
    @PostMapping(value = "/upload")
    public ResponseEntity<?> upload(HttpServletRequest request) {
        log.info("upload started! content size: " + request.getContentLengthLong());
        try (InputStream inputStream = request.getInputStream()) {
            copyStreamToMinio(inputStream, request.getContentLengthLong());
            return ResponseEntity.ok().build();
        } catch (Exception e) {
            log.error(e.getMessage());
            return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
        }
    }

    @Operation(summary = "上传文件", description = "")
    @PostMapping(value = "/upload2")
    public ResponseEntity<?> upload2(@RequestParam MultipartFile file) {
        log.info("upload2 started!");
        try {
            InputStream inputStream = file.getInputStream();
            copyStreamToMinio(inputStream, file.getSize());
            return ResponseEntity.ok().build();
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    private void copyStreamToMinio(InputStream is, long size) throws Exception {
        // 使用分块上传
        minioClient.putObject(
                PutObjectArgs.builder()
                        .bucket("3ddata")
                        .object("BIM/test")
                        .stream(is, size, 104857600)    // 每个分块大小设置为100MB
                        .build()
        );
    }
}
```
1. upload will be failure.
2. upload2 can be succeed.
3. upload a file bigger then 1GB
4. application.properties config
   `spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB
server.tomcat.max-swallow-size=10GB
server.tomcat.connection-timeout=60000
server.tomcat.max-http-form-post-size=-1`
6. spring boot version: 2.6.13
7. use insomnia to post file `> POST /api/file/upload HTTP/1.1
> Host: localhost:8076
> User-Agent: insomnia/9.2.0
> Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> Accept: */*
> Content-Length: **1244315823**`

## Your Environment

* Version used (`minio --version`): RELEASE.2024-05-10T01-41-38Z (go1.22.3 windows/amd64)
* Server setup and configuration: minio.exe server d:\minio --console-address ":9001"
* Operating System and version (`uname -a`): windows 10

**Comment by balamurugana** [comment]
@sendreams Check whether you are getting a complete stream and uploading the stream with correct content length.  Enable `MinioAsyncClient.traceOn()` and look into what exactly going on from the client.

I am closing this issue as incomplete information like no error message/stacktrace/trace logs.
