### ISSUE TITLE
Slack Web Hooks Not Working 

### ISSUE THREAD

**Issue by A7MAD-ALMLA** [minio/minio#19776]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Go To MinIO Console =====> Events ======> Add a webhook event destination with the details

1. Identifier: Test
2. Endpoint: https://hooks.slack.com/services/XXXX9PCY/B073UXXXF5M/DzMqj0rCXXXXXXXXX

save and restart the server
then configure the bucket with the event you just created with Any Operation e.g.. PUT
then Upload something to the bucket 

 **Expected Behavior: should receive a notification on the slack channel you selected when you created the webhook**

## Current Behavior
Nothing received on slack channel 

## Steps to Reproduce (for bugs)

1. Go To MinIO Console ==> Events ===> Add a webhook event destination with the details
2. Save and restart the server
3. Configure the bucket with the event you just created with Any Operation e.g.. PUT
4. Upload something to the bucket 
5. Check Status of the MinIO Service using "systemctl status minio.service" You will see a 400 Status Bad Request When the webhook reqest triggered 

![image](https://github.com/minio/minio/assets/44104530/cbbfe4a0-4196-4e84-9e62-c97750d6d99a)

REASON: Slack webhooks require a "text" key in the POST body data in order to accept the request 

you can reference this [thread](https://minio.slack.com/archives/C3NDUB8UA/p1716225065961639?thread_ts=1716225065.961639&cid=C3NDUB8UA) on the community slack of MinIO

## Possible Solution

since i don't have control over the slack API and how it process the request
My solution was to create a python script that listen to webhooks and run it locally on the server and make the script edit the JSON Body Data and include another "text" field to the body of the request with any a value of anything (random data)

## Your Environment

* Version used (`minio --version`):  minio version RELEASE.2024-05-10T01-41-38Z 
* Server setup and configuration: New Setup (one machine multiple drives)
* Operating System and version (`uname -a`): ubuntu server 22.04

**Comment by harshavardhana** [comment]
> REASON: Slack webhooks require a "text" key in the POST body data in order to accept the request

We cannot randomly change that, the incoming format is JSON they shouldn't be hard-coding it to "text". 

This cannot be supported without breaking our other endpoints.

**Comment by A7MAD-ALMLA** [comment]
I Just thought since Slack is so popular and used by many people, that's why i opened an issue

for future, in case someone else faced the same, 
![image](https://github.com/minio/minio/assets/44104530/281df9e5-edfa-47f7-bead-1efe00f68280)


![image](https://github.com/minio/minio/assets/44104530/0b12b2ab-3100-4d0b-b3e9-eda2cde15cdd)

**Comment by harshavardhana** [comment]
YeH but we cannot add custom data structures for them. They are clearly not generic webhook they expect specific format.
