### ISSUE TITLE
Avoid 524 when using cloudflare, send keepalive every 45s when it takes long time

### ISSUE THREAD

**Issue by magictomagic** [minio/minio#19777]
**Is your feature request related to a problem? Please describe.**
When I upload small files and it does not take long time, it works well, but when the file is too big and takes long time, it occurs 524 because the 100s limit in cloudflare.

**Describe the solution you'd like**
Send keepalive every 45s to avoid long time no request.

**Describe alternatives you've considered**
Send keepalive every 45s from gateway, not from minio, but it cause low coupling. Or, just add script in docker-compose.

**Additional context**
I use minio as my homelab, which is ipv6 only. So the cloudflare proxy is used to enable my ipv6 only network to ipv4. 

My route is `cloudflare -> nginx -> minio`,  I use docker-compose.yml to deploy. The nginx is used as reverse proxy and https end, that is to say the communication between cloudflare and nginx is https while the communication between nginx and minio is http.

**Comment by harshavardhana** [comment]
Ask them to fix it, what is this has to do with MinIO?

**Comment by klauspost** [comment]
Furthermore there exists no "Send keepalive every 45s to avoid long time no request".

**Comment by harshavardhana** [comment]
> Furthermore there exists no "Send keepalive every 45s to avoid long time no request".

Yeah it is expected from a client to write some kind of a lookup and ping @klauspost . Poor man's keep alive.
