### ISSUE TITLE
CopyObject() are slow to modify metadata

### ISSUE THREAD

**Issue by DaiYuanchuan** [minio/minio#19778]
## Expected Behavior
not affected by file size，return in a short time

## Current Behavior
I want to modify the ContentType value of an object after the upload operation is completed.

I only want to modify the ContentType value, so I used the same object as both the source and target objects in CopyObject().

However, I found that it seems to be affected by file size.    For one object with a size of 23.7GB (xx.2024.HDR.2160P.120FPS.mp4), it took around 6000ms, while another object with a size of 1.7GB took only about 300ms.    At the same time, CPU usage increases when performing this operation.

```
Map<String, String> headers = Maps.newHashMapWithExpectedSize(5);
headers.put("Content-Type", "video/mp4");
ObjectWriteResponse future = minioClient.copyObject(
        CopyObjectArgs. builder()
                .bucket(BUCKET_NAME)
                .object("xx.2024.HDR.2160P.120FPS.mp4")
                .source(
                        CopySource. builder()
                                .bucket(BUCKET_NAME)
                                .object("xx.2024.HDR.2160P.120FPS.mp4")
                                .build())
                .metadataDirective(Directive.REPLACE)
                .userMetadata(headers)
                .build());
```

## Your Environment
Using latest docker image from minio/minio

bash-5.1# minio --version
minio version RELEASE.2024-05-10T01-41-38Z (commit-id=b5984027386ec1e55c504d27f42ef40a189cdb55)
Runtime: go1.22.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

bash-5.1# uname -a
Linux minio 5.10.134-13.an8.x86_64 #1 SMP Mon Jan 9 10:39:46 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
bash-5.1#

**Comment by harshavardhana** [comment]
> Map<String, String> headers = Maps.newHashMapWithExpectedSize(5);
> headers.put("Content-Type", "video/mp4");
> ObjectWriteResponse future = minioClient.copyObject(
>         CopyObjectArgs. builder()
>                 .bucket(BUCKET_NAME)
>                 .object("xx.2024.HDR.2160P.120FPS.mp4")
>                 .source(
>                         CopySource. builder()
>                                 .bucket(BUCKET_NAME)
>                                 .object("xx.2024.HDR.2160P.120FPS.mp4")
>                                 .build())
>                 .metadataDirective(Directive.REPLACE)
>                 .userMetadata(headers)
>                 .build());

This is not just updating metadata it is rewriting the entire object

**Comment by DaiYuanchuan** [comment]
is there a way to only update the metadata?  or is there a plan for the future?

**Comment by klauspost** [comment]
You can use tagging: https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html

**Comment by DaiYuanchuan** [comment]
not tags, what I want to change is Content-Type, which will affect the browser's download behavior。

I am implementing the function of shard upload. If Content-Type is not specified during upload, I will read some bytes from the first shard to identify the correct Content-Type and modify it after uploading.

**Comment by klauspost** [comment]
That is not possible without copying.

Set the correct content type on upload.

**Comment by DaiYuanchuan** [comment]
even if the source object is the same as the target object？😰

**Comment by klauspost** [comment]
With versioning you are creating unique versions, since existing versions are immutable.

**Comment by klauspost** [comment]
I don't see us implementing special cases for this.
