### ISSUE TITLE
minio stuck on May 22 01:11:42 idk systemd[1]: Starting MinIO... May 22 01:11:42 idk systemd[1]: Started MinIO.

### ISSUE THREAD

**Issue by japlic** [minio/minio#19784]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

The minio is stuck on May 22 01:11:42 idk systemd[1]: Starting MinIO...
May 22 01:11:42 idk systemd[1]: Started MinIO.

## Expected Behavior
run the minio client

## Current Behavior
May 22 01:11:42 idk systemd[1]: Starting MinIO...
May 22 01:11:42 idk systemd[1]: Started MinIO.

## Steps to Reproduce (for bugs)
idk
1.
2.
 Set the hosts and volumes MinIO uses at startup

 The command uses MinIO expansion notation {x...y} to denote a

 sequential series.

 The following example covers four MinIO hosts

 with 4 drives each at the specified hostname and drive locations.

 The command includes the port that each MinIO server listens on

 (default 9000)
CI=true

MINIO_CI_CD=true

MINIO_VOLUMES="http://localhost/mnt/data/disk{1...4}/minio"

 Set all MinIO server options

# The following explicitly sets the MinIO Console listen address to

 port 9001 on all network interfaces. The default behavior is dynamic

 port selection.

MINIO_OPTS="--console-address :9001"

 Set the root username. This user has unrestricted permissions to

 perform S3 and administrative API operations on any resource in the

 deployment.

 Defer to your organizations requirements for superadmin user name.

MINIO_ROOT_USER=minioadmin

 Set the root password

 Use a long, random, unique string that meets your organizations

 requirements for passwords.

MINIO_ROOT_PASSWORD=minioadmin

 Set to the URL of the load balancer for the MinIO deployment

 This value *must* match across all MinIO servers. If you do

not have a load balancer, set this value to to any *one* of the

 MinIO hosts in the deployment as a temporary measure.

MINIO_SERVER_URL="http://localhost"

root@idk:~# cat  /etc/systemd/system/minio.service
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local
ProtectProc=invisible

StartLimitBurst=0

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

 Let systemd restart this service always
Restart=always

 Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

 Specifies the maximum number of threads this process can create
TasksMax=infinity

Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})
3.
4.

## Context
i just want the minio website

## Your Environment

* Version used (`minio --version`):
* 
* Server setup and configuration:
* Operating System and version (`uname -a`):
* Linux idk 5.4.0-176-generic #196-Ubuntu SMP Fri Mar 22 16:46:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
If you only have one host just do `minio server /mnt/disks
