### ISSUE TITLE
Restore the file path in minio bucket to private access, but it does not take effect.

### ISSUE THREAD

**Issue by jjtenger** [minio/minio#19794]
Initially, I set the anonymous access permission of the 'bbb' folder in the testabc bucket to be publicly downloadable using the following mc command. This setting was normally effective.

```
$ ./mc anonymous set download myminio/testabc/bbb
Access permission for `myminio/testabc/bbb` is set to `download`

$ curl -O http://feiniu-oss.idc1.fn:9000/testabc/bbb/test.txt
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    23  100    23    0     0   1765      0 --:--:-- --:--:-- --:--:--  1916
```

Then, I restored the folder back to private access. However, this operation does not take effect, and the files in the folder can still be downloaded normally.

```
$ ./mc anonymous set private myminio/testabc/bbb
Access permission for `myminio/testabc/bbb` is set to `private`

$ curl -O http://feiniu-oss.idc1.fn:9000/testabc/bbb/test.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   329  100   329    0     0  28905      0 --:--:-- --:--:-- --:--:-- 29909
```

Why is the operation to restore private access ineffective? I have tried the above operations repeatedly on the console web page and got the same result.

The version of minio I am using is: RELEASE.2023-10-25T06-33-25Z

```
$ minio --version
minio version RELEASE.2023-10-25T06-33-25Z (commit-id=c60f54e5be7302d82d0d8fc404c056fea4e2bf4e)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

The operating system is: Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-144-generic x86_64)

I hope to get an answer, thanks very much!

**Comment by jjtenger** [comment]
I installed the latest Docker version of the minio locally, tested it, and it's still the same. Restarting the service didn't work either. I don't know what the reason is.

**Comment by jjtenger** [comment]
Update the problem description:
After I restored the anonymous access back to private, I uploaded a new file in the folder. The new file cannot be downloaded, but the old files in the folder can still be downloaded. How can I disable the download permissions for the old files?

**Comment by harshavardhana** [comment]
you can you do `mc anonymous get-json` to see the current policy

**Comment by jjtenger** [comment]
> you can you do `mc anonymous get-json` to see the current policy

the current policy is empty

```
$ ./mc anonymous get-json  myminio/testabc/bbb
{}
```

**Comment by harshavardhana** [comment]
```

**Comment by harshavardhana** [comment]
```
$ ./mc anonymous get-json  myminio/testabc
```

**Comment by jjtenger** [comment]
> ```
> $ ./mc anonymous get-json  myminio/testabc
> ```

It's also empty

```
./mc anonymous get-json  myminio/testabc
{}
```

**Comment by harshavardhana** [comment]
and you said you can download even with empty policy - can you show me how you download?

**Comment by jjtenger** [comment]
> and you said you can download even with empty policy - can you show me how you download?

curl -O http://127.0.0.1:9000/testabc/bbb/test.txt
or
Access this url directly through the browser

**Comment by jjtenger** [comment]
> and you said you can download even with empty policy - can you show me how you download?

curl -O http://127.0.0.1:9000/testabc/bbb/test.txt
or
Access this url directly through the browser

**Comment by jjtenger** [comment]
This question should be easily reproducible, I have replicated it multiple times on different machines

**Comment by harshavardhana** [comment]
can you share after `mc anonymous private alias/testabc/bbb/` 

```
curl http://127.0.0.1:9000/testabc/bbb/test.txt
```

Here is what I tested it looks like you are not testing things properly

```
~ minio server ~/test &
```

```
~ mc mb myminio/public/
Bucket created successfully `myminio/public/`.
```

```
~ mc cp /etc/hosts myminio/public/bbb/test.txt
/etc/hosts:                           228 B / 228 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 12.56 KiB/s 0s
```

```
~ mc anonymous set download myminio/public/bbb
Access permission for `myminio/public/bbb` is set to `download`
```

```
~ curl http://localhost:9000/public/bbb/test.txt
127.0.0.1	localhost
127.0.1.1	nano
127.0.1.2       nano

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

```
~ mc anonymous set private myminio/public/bbb
Access permission for `myminio/public/bbb` is set to `private`
```

```
~ curl http://localhost:9000/public/bbb/test.txt
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>bbb/test.txt</Key><BucketName>public</BucketName><Resource>/public/bbb/test.txt</Resource><RequestId>17D2091C350D5A7E</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
```

**Comment by jjtenger** [comment]
> can you share after `mc anonymous private alias/testabc/bbb/`
> 
> ```
> curl http://127.0.0.1:9000/testabc/bbb/test.txt
> ```
> 
> Here is what I tested it looks like you are not testing things properly
> 
> ```
> ~ minio server ~/test &
> ```
> 
> ```
> ~ mc mb myminio/public/
> Bucket created successfully `myminio/public/`.
> ```
> 
> ```
> ~ mc cp /etc/hosts myminio/public/bbb/test.txt
> /etc/hosts:                           228 B / 228 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 12.56 KiB/s 0s
> ```
> 
> ```
> ~ mc anonymous set download myminio/public/bbb
> Access permission for `myminio/public/bbb` is set to `download`
> ```
> 
> ```
> ~ curl http://localhost:9000/public/bbb/test.txt
> 127.0.0.1	localhost
> 127.0.1.1	nano
> 127.0.1.2       nano
> 
> ::1     ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
> ```
> 
> ```
> ~ mc anonymous set private myminio/public/bbb
> Access permission for `myminio/public/bbb` is set to `private`
> ```
> 
> ```
> ~ curl http://localhost:9000/public/bbb/test.txt
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>bbb/test.txt</Key><BucketName>public</BucketName><Resource>/public/bbb/test.txt</Resource><RequestId>17D2091C350D5A7E</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
> ```

No, no, you must use `curl -O` to download the file, not just `curl`. With `curl -O`, you will download successfully without any AccessDenied messages.
@harshavardhana

**Comment by harshavardhana** [comment]
curl and curl -O has no real difference.

**Comment by harshavardhana** [comment]
the -O for the access denied as `XML` access denied messages in the file. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>bbb/test.txt</Key><BucketName>public</BucketName><Resource>/public/bbb/test.txt</Resource><RequestId>17D20F59AAD6E076</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
```

> $ curl -O http://feiniu-oss.idc1.fn:9000/testabc/bbb/test.txt
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    23  100    23    0     0   1765      0 --:--:-- --:--:-- --:--:--  1916



> $ curl -O http://feiniu-oss.idc1.fn:9000/testabc/bbb/test.txt
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   329  100   329    0     0  28905      0 --:--:-- --:--:-- --:--:-- 29909

Its clearly visible that second attempt to save lot more which is the XML error.

**Comment by jjtenger** [comment]
> the -O for the access denied as `XML` access denied messages in the file.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>bbb/test.txt</Key><BucketName>public</BucketName><Resource>/public/bbb/test.txt</Resource><RequestId>17D20F59AAD6E076</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
> ```
> 
> > $ curl -O http://feiniu-oss.idc1.fn:9000/testabc/bbb/test.txt
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 100    23  100    23    0     0   1765      0 --:--:-- --:--:-- --:--:--  1916
> 
> > $ curl -O http://feiniu-oss.idc1.fn:9000/testabc/bbb/test.txt
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 100   329  100   329    0     0  28905      0 --:--:-- --:--:-- --:--:-- 29909
> 
> Its clearly visible that second attempt to save lot more which is the XML error.

Thank you for your answer. You are correct. Moreover, I have found the root cause of the issue that I initially encountered. Our online minio service has a gateway in front of it, and the gateway has caching. If you download through the gateway URL, it goes directly through the cache and does not go through minio.
