### ISSUE TITLE
About Minio deployment and the AGPLv3 license.

### ISSUE THREAD

**Issue by brkcnbz** [minio/minio#19808]
Can we use Minio in a production environment? Can we set it up on internal servers without making any changes to the Minio code and use it as an S3 service for our CRM infrastructure?

**Comment by harshavardhana** [comment]
We have designed MinIO as open-source software for the Open-Source software community. This requires applications to consider whether their usage of MinIO is in compliance with the GNU AGPLv3 license.

MinIO cannot determine whether your application's use of MinIO is in compliance with the AGPLv3 license requirements. You should instead rely on your own legal counsel or licensing specialists for open-source projects with which your application integrates or interacts.

We understand that AGPLv3 licensing is complex and nuanced. For that reason, we strongly encourage using experts.

**Comment by klauspost** [comment]
https://min.io/compliance
