### ISSUE TITLE
FTP/SFTP unable to upload properly

### ISSUE THREAD

**Issue by beck-8** [minio/minio#19802]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Upload large or small files at normal speed
## Current Behavior

> FTP is the same situation

When transferring large files (G), the speed will drop from 100MB/S to 0 and cannot be uploaded normally.
It also often gets stuck when transferring small files.
```bash
root@node3:~# sftp -P60021 vcr@10.126.80.5
The authenticity of host '[10.126.80.5]:60021 ([10.126.80.5]:60021)' can't be established.
RSA key fingerprint is SHA256:eA4jRHfNnOCIrdhn4RhNakdzLmw14J/rBMKt0uCGi7o.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[10.126.80.5]:60021' (RSA) to the list of known hosts.
vcr@10.126.80.5's password: 
Connected to 10.126.80.5.
sftp> ls
vcr     vcr1    vcr123  vcr2    
sftp> cd vcr123
sftp> ls
sftp> put /media/nvme/subspace-farm3h/piece_cache.bin
Uploading /media/nvme/subspace-farm3h/piece_cache.bin to /vcr123/piece_cache.bin
piece_cache.bin                                                                                                                                             3%  528MB   0.0KB/s - stalled -
```
## Steps to Reproduce (for bugs)

1. minio server --console-address :9001 --address :9000 --sftp=address=:60021 --sftp=ssh-private-key=/opt/id_rsa http://node{1...4}.net:9000/mnt/disk{1...4}
2. test sftp put (Files larger than G)
3.
4.

## Your Environment

* Version used (`minio --version`):
```bash
root@node2:~# minio -v
minio version RELEASE.2024-05-10T01-41-38Z (commit-id=b5984027386ec1e55c504d27f42ef40a189cdb55)
Runtime: go1.22.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration:
```bash
minio server --console-address :9001 --address :9000 --sftp=address=:60021 --sftp=ssh-private-key=/opt/id_rsa http://node{1...4}.net:9000/mnt/disk{1...4}
```
* Operating System and version (`uname -a`):
```bash
root@node2:~# uname -a
Linux node2 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by klauspost** [comment]
```
λ sftp -P60021 minio@127.0.0.1
The authenticity of host '[127.0.0.1]:60021 ([127.0.0.1]:60021)' can't be established.
ECDSA key fingerprint is SHA256:M6s8so0GzowK77OBdK2SYmKEbwOQlyoNyTKMx4F5jNQ.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Warning: Permanently added '[127.0.0.1]:60021' (ECDSA) to the list of known hosts.
minio@127.0.0.1's password:
Connected to 127.0.0.1.
sftp> cd testbucket
sftp> put enwik10
Uploading enwik10 to /testbucket/enwik10
enwik10                                                                                          100% 9537MB 124.3MB/s   01:16
sftp>
```

You may have packet loss leading to hanging TCP connections. Either way without a clean reproducer there isn't much more we can do.

**Comment by beck-8** [comment]
Are you testing multiple instances?
This question is really confusing and I can't find the direction to doubt it at the moment.

**Comment by klauspost** [comment]
On a distributed setup:

```
λ sftp -P60021 minio@127.0.0.1
minio@127.0.0.1's password:
Connected to 127.0.0.1.
sftp> cd testbucket
sftp> put enwik10
Uploading enwik10 to /testbucket/enwik10
enwik10                                                                                          100% 9537MB 116.1MB/s   01:22
sftp>
```

> This question is really confusing and I can't find the direction to doubt it at the moment.

I can't really help you either. My guess is you have issues with your network.

**Comment by beck-8** [comment]
I'm checking it myself. The network I'm using is the local IP, so there shouldn't be any problem.Thank you so much

**Comment by beck-8** [comment]
I think I may already know how to reproduce this issue. @klauspost 
> Tested with 17G files, write in a same bucket

In your cluster, how many machines have you enabled SFTP on?
My test steps:
1. Only start sftp on node1. At this time, the speed of reading and writing data is normal.
2. Also start sftp on node2. At this time, node1 can read and write data normally, but node2 cannot write. (node1 node2 writes data at the same time)
3. Close the sftp of node1, and the sftp of node2 cannot be written normally.
4. node1 is always in a normal state, node2 node3 node4 is in an abnormal state.

Summary: The first sftp that is started for the first time is normal, and other machines are in an abnormal state.

**Comment by klauspost** [comment]
I tried adding sftp on more servers. No difference AFAICT.

**Comment by beck-8** [comment]
Additional Information:
- Using mc cp download speed is normal(100MB/S)
- Abnormal download speed using sftp get(1M/S)

![image](https://github.com/minio/minio/assets/34204218/34d73be5-3beb-4ca0-9bc2-422166409190)

**Comment by klauspost** [comment]
sftp speed has not been a priority. This is mainly due to how the [sftp server](github.com/pkg/sftp) is implemented. For whatever reason they decided that reading at non-sequential offsets was a good idea leading to a crazy amount of seeking.

**Comment by beck-8** [comment]
Got it. I'm not sure if this could be the reason for the slow writes.

**Comment by klauspost** [comment]
No. We buffer out of order writes.
