### ISSUE TITLE
Add HostAliases parameter to values.yaml

### ISSUE THREAD

**Issue by nleeuskadi** [minio/minio#19803]
**Is your feature request related to a problem? Please describe.**
Adding entries to a Pod's /etc/hosts file provides Pod-level override of hostname resolution when DNS and other options are not applicable. 

But modifying directly the /etc/hosts file is not recommended wince it is managed by the kubelet and can be overwritten on during Pod creation/restart.

Hopefully, Kubernetes provided a means to add these custom entries with the HostAliases field in PodSpec.

But, currently, in the minio values.yaml file there is no entries for HostAliases (as we can have in other helm charts of others software).

**Describe the solution you'd like**
Add in the minio values.yaml the HostAliases entry allowing us to add specific hostname resolution.
Something like this for example:
``` yaml
## @param hostAliases pod host aliases
## https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
##
hostAliases: []

``` 
And enrich the statefulset yaml template with some bunch of lines to add HostAliases in the minio POD spec:
``` yaml
spec:
    ......
    {{- if .Values.hostAliases }}
     hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
    {{- end }}
```

**Describe alternatives you've considered**
No alternative

**Additional context**
N/A

**Comment by harshavardhana** [comment]
Vanilla helm chart-related feature requests, please send PRs. The MinIO team does not consider new features for it.
