### ISSUE TITLE
Random and Unpredictable Upload spikes when uploading data to minio bucket from Spring Boot Application

### ISSUE THREAD

**Issue by titos999** [minio/minio#19827]
## Current Behavior
Hello, recently I started working with minio and integrating it in my Java Spring Boot application. My application's main thread is constantly consuming messages from RabbitMQ, creates files (1B up to 3 MiB) out of those messages and then push these files to a minio bucket using `io.minio.MinioClient#uploadObject`. Also periodically, I am uploading some big files into the same bucket (95 MiB up to 150 MiB). My setup includes 4 minio nodes and an HAProxy Load Balancer on top of these nodes. For HAProxy I have tried both least connection and round robin balancing. 

The issue with my current setup is that randomly I get some upload spikes and they are very unpredictable. Rarely in the day, messages that are small (~2.5 KiB) take about 720ms to 1.5s to upload (sometimes even more), while in average they take take around 10ms - 250ms which is acceptable. Also, 105 MiB files are getting uploaded in about 2.5s - 4s which is pretty fine in my case. I have noticed that I can get these spikes even when no other operation (GET, DELETE etc.) takes place in the minio cluster. I really can't explain what happens during these spikes. I know that my setup is not 100% aligned with the recommended one on the docs but still reaching out for some assistance.

This issue is affecting my application because ideally I want to upload these small files as fast as possible (ideally less than 200ms) and this unpredictable spikes could cause serious issues later in the flow. Could it be that my current setup (e.g. OS/Kernel Version) be responsible for these spikes?

## Your Environment
* Version used (`minio --version`): **minio-RELEASE.2024-05-10T01-41-38Z**
* Java Library Version used: **8.5.10**
* Server setup and configuration: Each node has **2 xfs drives** configured with a total of **14GB SSD storage**, **3.8 GiB** Memory
* Operating System: **CentOS Linux release 7.9.2009**
* Linux Kernel Version: **3.10.0-1160.66.1.el7.x86_64**

**Comment by klauspost** [comment]
Debugging performance issues like this is pretty time consuming and only something we offer for our [subscribers](https://min.io/pricing).

You can try looking at `mc admin trace -a --response-duration=100ms` to see if you can identify the slowdown.
