### ISSUE TITLE
Minio FTP service failed to upload large files starting from RELEASE.2024-04-28T17-53-50Z version

### ISSUE THREAD

**Issue by jiajingshan** [minio/minio#19830]
My task is to optimize ftp/sftp upload() implementations to avoid CPU load caused by @ harshavardhana in # 19552 in RELEASE.2024-04-28T17-53-50Z version optimization
After testing, the response speed of the backend S3 for uploading files exceeding 2M through FTP is about 2 seconds. Uploading files of around 1GB is slow and sometimes fails. Uploading data of around 10GB also fails. I hope to restore the modifications to FTP on April 28th. Before April 28th, the FTP function was normal and the CPU usage was not high. I tested that there was no problem writing 300GB of data continuously every day (data ranging from 1k to 1GB). I have now returned RELEASE.2024-04-18T
RELEASE.2024-04-28T17-53-50Z and later versions have this issue.

**Comment by jiajingshan** [comment]
Operating system version RockyLinux9.3

**Comment by zveinn** [comment]
Will look into this

**Comment by klauspost** [comment]
Filezilla:

```
19:08:46	Status:	Connecting to 127.0.0.1:8021...
19:08:46	Status:	Connection established, waiting for welcome message...
19:08:46	Status:	Insecure server, it does not support FTP over TLS.
19:08:46	Status:	Logged in
19:08:46	Status:	Starting upload of 10gb.tar
19:09:13	Status:	File transfer successful, transferred 10.065.157.632 bytes in 26 seconds
```

```
λ ftp
ftp> o 127.0.0.1 8021
Connected to 127.0.0.1.
220 Welcome to 'MinIO' FTP Server Version='GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html' License='DEVELOPMENT.GOGET'
200 UTF8 mode enabled
User (127.0.0.1:(none)): minio
331 User name ok, password required
Password:
230 Password ok, continue
ftp> cd /testbucket
250 Directory changed to /testbucket
ftp> put 10gb.tar
200 Connection established (53152)
150 Data transfer starting
226 OK, received 10065157632 bytes
ftp: 10065157632 bytes sent in 28.39Seconds 354531.79Kbytes/sec.
```

Seems to work fine here.

**Comment by jiajingshan** [comment]
&nbsp;
I'm sorry, I didn't test the latest version at that time, only tested versions 2024428 to 20240510. I saw that there were no updates to FTP related functions, and I think the problem hasn't been fixed. I will pay attention next time and raise the issue after strict testing.











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月3日(星期一) 凌晨1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio] Minio FTP service failed to upload large files starting from RELEASE.2024-04-28T17-53-50Z version (Issue #19830)





 
Filezilla:
 19:08:46	Status:	Connecting to 127.0.0.1:8021... 19:08:46	Status:	Connection established, waiting for welcome message... 19:08:46	Status:	Insecure server, it does not support FTP over TLS. 19:08:46	Status:	Logged in 19:08:46	Status:	Starting upload of 10gb.tar 19:09:13	Status:	File transfer successful, transferred 10.065.157.632 bytes in 26 seconds  λ ftp ftp&gt; o 127.0.0.1 8021 Connected to 127.0.0.1. 220 Welcome to 'MinIO' FTP Server Version='GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html' License='DEVELOPMENT.GOGET' 200 UTF8 mode enabled User (127.0.0.1:(none)): minio 331 User name ok, password required Password: 230 Password ok, continue ftp&gt; cd /testbucket 250 Directory changed to /testbucket ftp&gt; put 10gb.tar 200 Connection established (53152) 150 Data transfer starting 226 OK, received 10065157632 bytes ftp: 10065157632 bytes sent in 28.39Seconds 354531.79Kbytes/sec.  
Seems to work fine here.

**Comment by harshavardhana** [comment]
Please redo your tests with the latest release.

**Comment by harshavardhana** [comment]
Closing this as mostly fixed via the latest release.
