### ISSUE TITLE
Console and mc admin info  drivers count is error

### ISSUE THREAD

**Issue by myrust-go** [minio/minio#19847]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
If i umount a driver in a node, the cluster's driver's total number is right.

## Current Behavior
Umount a driver in a node, the  cluster driver's total number is not right

## Possible Solution
fix   https://github.com/minio/minio/edit/master/cmd/erasure.go
`
if state != madmin.DriveStateOk && state != madmin.DriveStateUnformatted {
		if state != madmin.DriveStateOk {
`

## Steps to Reproduce (for bugs)

1. umount  /data/minio1
2. visit MinIO web console metrics 
3. mc admin info local/

## Your Environment

* Version used (`minio --version`):  20240528
* Server setup and configuration:  ubuntu 22.02 
* Operating System and version (`uname -a`): Linux iZf8zax9l9auh7ujtwnqd1Z 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

![1](https://github.com/minio/minio/assets/2740529/3426b659-2f53-460f-98c7-1547a5fe4ce5)
![2](https://github.com/minio/minio/assets/2740529/576482fc-26c0-4bee-9e2d-7c02c8a8654c)

**Comment by loverustfs** [comment]
I think:
Web console & MinIO client admin info not fixed: madmin.DriveStateUnformatted

The backend changed, but the frontend did not change. So this bug occurred

**Comment by myrust-go** [comment]
I think:
Web console & MinIO client admin info not fixed: madmin.DriveStateUnformatted

The backend changed, but the frontend did not change. So this bug occurred

**Comment by harshavardhana** [comment]
Console UI value is cached upto 10/30sec - mc admin info doesn't cache.

An unformatted drive is a valid drive so it is never shown as offline.
