### ISSUE TITLE
Feat: Differentiate Between Access Keys and User Accounts in IAM Policies

### ISSUE THREAD

**Issue by flpydsk** [minio/minio#19844]
**Is your feature request related to a problem? Please describe.**
We need to prevent administrative user accounts from logging in via the S3 API, FTP/S, and SFTP. Currently, it's not possible to differentiate between service accounts and user accounts in IAM policies to enforce this restriction. Specifically, we have several users who administer a MinIO deployment with its S3 API exposed to the internet and want to ensure that these administrative user accounts cannot log in via the API, but only through the (much stronger) access keys.

**Describe the solution you'd like**
We would like a method to differentiate between user accounts and access keys in IAM policies. For example, the aws:userid could return either the username or the access key ID depending on which was used for the request. Alternatively, ldap:username could only have a value if the LDAP user was used to log in. A simpler solution and one that would reduce and possible regression might involve using aws:PrincipalType that returns a value based on the login type.

**Describe alternatives you've considered**
Instead of using access keys, we considered using only user accounts and applying an IAM policy with an IP restriction. However, the documentation indicates that this approach is insecure. [Source](https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#id6).

**Additional context**
This feature would be very useful for controlling access for administrative and data users, ensuring their access is restricted to the minimum necessary.

**Comment by donatello** [comment]
> Specifically, we have several users who administer a MinIO deployment with its S3 API exposed to the internet and want to ensure that these administrative user accounts cannot log in via the API, but only through the (much stronger) access keys.

@flpydsk Could you clarify what you mean here? All API access to MinIO requires an access key pair. An API access (via a REST API call) involves both authentication (login) and authorization (based on policies attached to the user entity that the access key pair belongs to). Are you trying to prevent access to the MinIO browser console, for example? Or perhaps prevent access via FTP/S or SFTP? In our view all these methods of access have the same level of security compared to a regular API access - why do you consider one method less secure? 

Currently MinIO does not support such restrictions. An IAM policy is attached to a "user entity" and is applied to all access keys (aka service accounts) they create and also to each temporary access key created via AssumeRole-style APIs (which is used by the web console). We would like to better understand the requirement here.

**Comment by flpydsk** [comment]
Hi @donatello,
What I mean is using an external IDP users credentials to access the minio SFTP/FTP should be disallowed, I am thinking that only the access keys created by that user should be used for access via the API's and allowing only the users to login to the dashboard for admin functions.

In my test minio depo loyment I have been seeing that you can use user credential to authenticate via SFTP/FTP(S) though not by S3, this is a problem for us I would like a method to prevent

**Comment by olljanat** [comment]
Not exactly what you are asking but related.
It is possible to prevent SFTP/FTP access with policies. I shared some examples in #19698

It is a bit dirty solution but works. #19744 also tried improve situation but will need rewrite it differently when I have some spare time.

Additionally #19833 added support to completely disable username/paasword authentication to SFTP.

**Comment by harshavardhana** [comment]
There is something called as principaltype

All service accounts and STS credentials have `principaltype` of AssumeRole, the rest have `User`, and the root credential says "Account." for all anonymous requests, it is called `Anonymous`.

You specify this via `aws:principaltype`

**Comment by flpydsk** [comment]
@olljanat, for now denying user credentials by sftp will be sufficient for my needs but impl of principle type as @harshavardhana and myself suggested

**Comment by olljanat** [comment]
> impl of principle type as @harshavardhana and myself suggested

@flpydsk I understand @harshavardhana comment in way that this already exist.
That is how it looks for me in code too:
https://github.com/minio/minio/blob/70078eab1052fe101d9ab4b8e25981d27c829a05/cmd/bucket-policy.go#L91-L100

**Comment by harshavardhana** [comment]
yeah this has been around since years like 5-6yrs ago, this should already help IMO.

**Comment by flpydsk** [comment]
Yes, Turns out I am just blind (and/or stupid) thanks though
