### ISSUE TITLE
s3.PutObject on single transaction failed for large file 

### ISSUE THREAD

**Issue by ahuiko** [minio/minio#19853]
## NOTE
Version 2024-05-28 18:49 fail if upload large file with one transaction (not multipart)
## Expected Behavior
If via WEB GUI upload large object, process will finish OK

## Current Behavior
when I upload a larger object using the website, "Resource request is unwritable, please reduce your request rate" appears after a while. If I use trace --debugg from mc I get the information "503 Service Unavailable" for s3.PutObject.

MultiPart upload of the same object is OK.

If I use the older version 2023-11-01T18:37:25Z everything is OK.

## Possible Solution
downgrade - but it is forbidden

## Steps to Reproduce (for bugs)
use Web UI and make upload large file (more then 700MB)
 
## Your Environment
4 servers (every 12 disk (11TB)
erasure-coding
OL8

**Comment by ahuiko** [comment]
upload large object (single transaction) failed via aws protocol too (not only web ui)

**Comment by harshavardhana** [comment]
It looks like it takes longer than 30 seconds can you do `mc admin trace -v alias/` and share the output here ?

**Comment by ahuiko** [comment]
yes, here is 
[result.txt](https://github.com/user-attachments/files/15515917/result.txt)

**Comment by harshavardhana** [comment]
how about you upload a smaller object like 100MiB?

**Comment by ahuiko** [comment]
small object is OK. Minio_release was uploaded OK

**Comment by klauspost** [comment]
What file system are you using?

**Comment by harshavardhana** [comment]
this is related to the aggressive deadlines we added to handle hung node scenarios @klauspost

**Comment by harshavardhana** [comment]
Yeah its the 30sec READ deadline on the client side conn for REST CreateFile() for some reason this connection is getting closed.

**Comment by ahuiko** [comment]
> What file system are you using?

xfs
