### ISSUE TITLE
A bug after hot-unplugging a hard disk

### ISSUE THREAD

**Issue by myrust-go** [minio/minio#19856]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavio

After hot-plugging and unplugging hard disks on the server. mc client and console client correctly display the number of offline hard disks.

## Current Behavior

1. Current server cluster is 4 nodes, 8 hard disks, EC: 8
2. Unplug the 8 hard disks on a server on a server
3. mc admin info host, still shows 8 hard disks online.

## Possible Solution

fix https://github.com/minio/minio/edit/master/cmd/erasure.go
~~~
if state != madmin.DriveStateOk && state != madmin.DriveStateUnformatted {
if state != madmin.DriveStateOk {
~~~

## Steps to Reproduce (for bugs)

1.  Unplug all hard disks from the physical machine or delete all hard disks in the virtual machine management interface
2.  check :  `mc admin info TARGET`

## Your Environment

* Version used (`minio --version`):  20240528
* Server setup and configuration:  ubuntu 22.02
* Operating System and version (`uname -a`):    Linux iZf8zax9l9auh7ujtwnqd4Z 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

![1](https://github.com/minio/minio/assets/2740529/66352909-b1e8-493b-a9e1-cc684caab2ae)
![2](https://github.com/minio/minio/assets/2740529/4a19af33-a64f-4163-bd61-aca9e454cef6)
![3](https://github.com/minio/minio/assets/2740529/91d9f1df-6dde-4c6f-824e-1cfaf8b37fca)

**Comment by harshavardhana** [comment]
What is the user ID of the MinIO is running as ? 

Also is your disks part of root disks or separate drives?

**Comment by harshavardhana** [comment]
Again as I mentioned before closing the previous issue an unformatted drive is a valid drive. We do not show them as offline.

**Comment by myrust-go** [comment]
> What is the user ID of the MinIO is running as ?
> 
> Also is your disks part of root disks or separate drives?

it's minio-user.
minio binaries, systemctl and disk users are same.
And ownership is given.

**Comment by myrust-go** [comment]
> Again as I mentioned before closing the previous issue an unformatted drive is a valid drive. We do not show them as offline.

Okay, thank you. I don't quite understand unformatted . I have a feeling that it is the mc front end code, the prometheus status and the back end code that is not aligned with the status code.
So, unplugging the hard disk mc 8/8 still shows online status.

When you need to monitor the alarm, unplugging the hard disk prometheus also can not accept the message of hard disk damage.

Thank you harsh.

**Comment by harshavardhana** [comment]
Please share the server logs @kaiwenli from the node where you hot-plugged the drives.

**Comment by loverustfs** [comment]
> Please share the server logs @kaiwenli from the node where you hot-plugged the drives.

Thank you Harsh.

Okay, I exported both logs:

1. mc admin logs target host > minio_cluster.log; (this log doesn't show the logs for the hot swapped disks)

2. dmesg > hot-plugged.log (this one has hot-plugging information for the disks).

3. minio_cluster.log has information about wrong permissions at startup, the screenshot shows that the permissions are correct;


My suggestions:

1. the web console API needs to handle the unformatted state; 2. the mc admin info loop is not working.
2. mc admin info needs to handle unformatted once when cycling through disk info;
3. prometheus needs to adjust the amount of minio_cluster_offline_total when the unformatted state changes.


[hot-plugged.log](https://github.com/user-attachments/files/15520963/hot-plugged.log)
[minio_cluster.log](https://github.com/user-attachments/files/15520964/minio_cluster.log)


[
![4](https://github.com/minio/minio/assets/155562731/013a1d3f-9b57-4bb6-b637-b2271cd1544b)
](url)

![5](https://github.com/minio/minio/assets/155562731/da7a5d87-46f9-4544-aa59-04f848914589)

**Comment by myrust-go** [comment]
> Please share the server logs @kaiwenli from the node where you hot-plugged the drives.

Thank you Harsh.

Okay, I exported both logs:

1. mc admin logs target host > minio_cluster.log; (this log doesn't show the logs for the hot swapped disks)

2. dmesg > hot-plugged.log (this one has hot-plugging information for the disks).

3. minio_cluster.log has information about wrong permissions at startup, the screenshot shows that the permissions are correct;


My suggestions:

1. the web console API needs to handle the unformatted state; 2. the mc admin info loop is not working.
2. mc admin info needs to handle unformatted once when cycling through disk info;
3. prometheus needs to adjust the amount of minio_cluster_offline_total when the unformatted state changes.


[hot-plugged.log](https://github.com/user-attachments/files/15520963/hot-plugged.log)
[minio_cluster.log](https://github.com/user-attachments/files/15520964/minio_cluster.log)


[
![4](https://github.com/minio/minio/assets/155562731/013a1d3f-9b57-4bb6-b637-b2271cd1544b)
](url)

![5](https://github.com/minio/minio/assets/155562731/da7a5d87-46f9-4544-aa59-04f848914589)

**Comment by myrust-go** [comment]
I have fixed this bug in the web console.
However, the bug in minio client (mc) has not been fixed yet.



![1717249058220](https://github.com/minio/minio/assets/2740529/c6d4a32c-4c6e-4ac8-ad0b-26a9512f9c5a)

![8888](https://github.com/minio/minio/assets/2740529/718efd0a-0d4c-4bcf-9ab5-d3a8a37db14d)

Please confirm:

The unformatted status of hot swap is not processed in web console, prometheus, and mc admin info.

The status codes of the frontend and backend are inconsistent.

Thank you!

**Comment by harshavardhana** [comment]
No this is normal, by the time you see unformatted the disk is online for use while it is being healed and new data can come in.

The WebUI caches the server responses until 10-30sec so it's never instantaneous.

mc admin info is doing exactly what we want it to do. To see which drives are healing you need to use `mc admin heal` 

To see an offline drive just make the drive read-only.

Remember MinIO has no idea that you have given MinIO a drive or a folder. It simply doesn't know it for real.

If there is write access and the path is already not a root drive MinIO will consider that as a drive and use it.

MinIO by design keeps this for predictable behavior.
