### ISSUE TITLE
It appears that Minio deviates from the way AWS S3 signs range requests: SignatureDoesNotMatch if a range header is included in the signature

### ISSUE THREAD

**Issue by apps4uco** [minio/minio#19857]
It appears that Minio deviates from the way AWS S3 signs range requests.

I do not have access to the minio server and so do not know the version used, so apologies if this has already been fixed.

When a range request header is sent 
eg. Range=bytes=0-4
and then the request is signed the client library sends
SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, ...

and the server responds with a SignatureDoesNotMatch

## Expected Behavior

The range request header should be included in the signature, according to the AWS documentation I have seen. 

The range should be returned.

## Current Behavior

Adding the Range request and then signing generates a SignatureDoesNotMatch error

This breaks every client library I have tested. 

## Possible Solution

A workaround is to add the Range request header after signing.

SignedHeaders=host;x-amz-content-sha256;x-amz-date,
Range=bytes=0-4

This correctly returns the range.

However, I believe that this should not work, and that doing this should generate an error, as a Range header that should have been included in the SignedHeaders was not present.

## Steps to Reproduce (for bugs)

I could provide some Rust code that shows the problem and the workaround

## Context

This breaks all the s3 client libraries that I tested.

## Regression

Doesnt appear to be so

## Your Environment

* Version used (`minio --version`): Dont have access to the server
* Server setup and configuration: Via nginx
* Operating System and version (`uname -a`): Linux? - Dont have access to the server

**Comment by harshavardhana** [comment]
Please share a reproducer @apps4uco

**Comment by apps4uco** [comment]
I tried to reproduce the problem on play.min.io and range requests work as expected, so it looks like its either an old version of minio that the hosting provider is using or that the hosting provider is modifying the range request header somehow. Closing the report, as its not an issue with minio, sorry for the noise.
