### ISSUE TITLE
Do you guys read the content before closing an issue?

### ISSUE THREAD

**Issue by ibigbug** [minio/minio#19859]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I'm sorry being a bit rude. 

But why this issue got locked?

https://github.com/minio/minio/issues/19858

I don't understand the comment - what's working as expected? And the question didn't get answered. 

Why was the issue just locked ?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by kannappanr** [comment]
@ibigbug Hope you understood the comment in issue https://github.com/minio/minio/issues/19858
