### ISSUE TITLE
deleting bucket

### ISSUE THREAD

**Issue by ibigbug** [minio/minio#19858]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I deleted a bucket with cmd

```
mc rm -r --force --bypass --versions --dangerous dsm/files.social.yba.dev
```

## Expected Behavior

the bucket should be empty and can be deleted with 

```
mc rb --dangerous --force dsm/files.social.yba.dev
```

## Current Behavior

```
mc: <ERROR> Failed to remove `dsm/files.social.yba.dev`. The specified method is not allowed against this resource.
```

I see there are still empty folders in the bucket, that I just can't delete - all command line/UI delete operations were success but those empty folder just won't get removed.

Mean while I see trace logs below

<img width="1734" alt="image" src="https://github.com/minio/minio/assets/543405/e3f3d5ca-75da-4784-8dca-6339f20e7a8f">

And this has been the case for 2 weeks or more since I ran the 1st command.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This bucket used to be my Mastodon storage and could have a lot of small objects.

How should I delete the bucket and discard everthing under the bucket?

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
You have versioning enabled on the bucket without --versions you can't delete the objects.

You also seem to have governance object locking enabled which will also refuse to delete objects that's why 

--bypass --versions works 

This is working as expected.

**Comment by harshavardhana** [comment]
The issue is locked to avoid more bikeshedding on known topics. Please read the documentation regarding versioning and what needs to be done if you enable unnecessary features you don't need.
