### ISSUE TITLE
Grafana Minio node dashboard not working out of the box

### ISSUE THREAD

**Issue by staedter** [minio/minio#19867]
We are trying to use the official Minio Grafana dashboards for gathering relevant Metrics via the /minio/v2/metrics/node enpoints for each of the Minio nodes, but the node dashboard is not working correctly out of the box without manually tweaking it afterwards.

## Expected Behavior
We should be able to just import the node dashboards and set the correct prometheus datasource and everything should work and be usable by our developers without needing to fiddle with panel or board settings.
 
The only available scrape_jobs in the dropdown menu should be the ones that actually scrape the /minio/v2/metrics/node enpoints and not all available scrape_jobs to make it easier to use by regular developers that need to just consume the dashboards.
Also for the node dashboard there should be no overrides active for stuff like play.minio.io that disables the visibility of panel graphs like "Free Inodes".

## Current Behavior
When opening the dashboard after importing it into a grafana that has a prometheus datasource setup that scrapes the node enpoints, that board is not working out of the box and we had to manually fix it, to get everything running correctly.
![image](https://github.com/minio/minio/assets/46670623/37e4920a-2a6c-4fe8-94f1-38a09acadf82)

We first need to select the correct scrap_job name, which I, as the cluster administrator, might know, but my developers do not.
![image](https://github.com/minio/minio/assets/46670623/40f26df2-ed18-47ec-9c20-0626770259ed)

Afterwards the dashboards shows some metrics, but some panels like "Free Inodes" are not working (this is even visible in the docs btw).
![image](https://github.com/minio/minio/assets/46670623/40ee80c3-3084-46e7-8e69-442bdf881d03)

But this was the one metric that we really needed to track in our use case. 
Unfortunately the graphs are not visible in the panel out of the box and apparently it is related to an override set for play.minio.io.

![image](https://github.com/minio/minio/assets/46670623/17799bd5-6807-4370-82c6-902c7dd7c7ac)

When we remove this override or disable the "viz" setting, the graphs are starting to show. But why is this override there in the first place?
![image](https://github.com/minio/minio/assets/46670623/cec08624-09ff-44bd-b3e8-e656f7a3cd3a)
![image](https://github.com/minio/minio/assets/46670623/364ff1bb-1357-45dd-b4e6-582bc3a91f2f)

## Possible Solution
Make it easier to use this board by setting the dashboards scrape_jobs dropdown menu only to those jobs that actually include the  minio_node_* metrics and not all available job_scrapes.

Make sure that all available panels are actually visible and not disabled by visibility settings or override.

## Steps to Reproduce (for bugs)
1. Import the dashboard with ID or JSON
2. Set the Prometheus that scrapes the minio node metrics as the datasource
3. Display the Minio Node Dashboard
5. The Free Inode panel is not showing any graphs

## Your Environment
* Version used (`minio --version`): 2024-03-30T09:41:56Z
* Server setup and configuration: Virtualised 5 Node Minio Cluster behind a HAProxy-LB
* Operating System and version (`uname -a`): Linux minio01-node01 6.5.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 26 11:23:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shtripat** [comment]
This seems some copy paste issue. Will check and send a fix.

**Comment by shtripat** [comment]
Regarding `scrape_jobs` dont think we can restrict to names starting with `minio_node_*` as users can name the scrape jobs their own way. Selecting a proper node scrape job would be needed for the dashboard to work.

**Comment by staedter** [comment]
Ah sorry I was not clear about what I meant. My proposol was to restrict the dropdown menu to scrape_jobs that have metrics that start with minio_node_* like minio_node_drive_free_inodes via this setting
![image](https://github.com/minio/minio/assets/46670623/82adc83f-6736-4609-8e43-4bcfbed9883d)


We had this issue in two grafana instances and in one we could fix it like this:

![image](https://github.com/minio/minio/assets/46670623/b39da22c-c064-47b7-9847-213f67b2f54a)
this is version 
![image](https://github.com/minio/minio/assets/46670623/6985061e-251a-45d9-877c-f04110141077)

on the older version this is apparently not yet possible, but with the regex it should work an both right?

![image](https://github.com/minio/minio/assets/46670623/e38647b7-26b0-4256-8e7d-79ea47068a20)
![image](https://github.com/minio/minio/assets/46670623/354b1631-d680-4b74-af75-a7cf80812ee6)

**Comment by staedter** [comment]
For older versions this seems to work:

Query: query_result(minio_node_drive_free_inodes)
Regex: /job="(.*?)"/
![image](https://github.com/minio/minio/assets/46670623/cad76cb8-3505-4357-89b1-1560d5745bba)

**Comment by shtripat** [comment]
As these dashboards are provided as an example and need basis they should be customized, feel free to add the above changes for your use-case. Not all users would have scrape jobs named like `minio-job.*`
Regarding `restrict the dropdown menu to scrape_jobs that have metrics that start with minio_node_*` we would evaluate and send PR.

**Comment by staedter** [comment]
I think you were missing my point. Everyone that uses this board, would necessarily have to scrape the /minio/v2/metrics/node enpoint and therefore have some scrape_job (whatever the job is called) that would have all the metrics for that endpoint

like in my case the minio_node_drive_free_inodes metric or other metrics that only can be scrape from the /minio/v2/metrics/node endpoint and therefore extending the base dashboard to restrict the dropdown menu to only those scrape_jobs that include at least one of the minio_node_* metrics like minio_node_drive_free_inodes. the scrape_jobs themselves can be named however the users like but only those that will have the data to fill the panels will be selectable

But you are also correct if I want to extend that to the dashboard I can do that myself in the future if I can find the time.

Best regards and thanks for the quick support anyways :)
