### ISSUE TITLE
[QUESTION] Deployment strategy & post-install job

### ISSUE THREAD

**Issue by Subetov** [minio/minio#19874]
Having the "deploymentUpdate.type.RollingUpdate" strategy in deployment, when updating the helm chart (for example, changing the Docker image), we will have a new pod running and a “post-job” created.
The “post-job” connects to the old (still running) pod and starts executing commands, then when the new pod becomes ready, the old one dies.

Could this create/lead to problems?
For example, part of the “post-job” will not be executed or some of the commands will not apply due to the fact that during the execution one of the pods will terminate?

Thanks.

**Comment by harshavardhana** [comment]
helm charts are not official way to deploy MinIO. Please use the documentation here for k8s native installation - https://min.io/docs/minio/kubernetes/upstream/index.html?ref=docs-redirect

the helm chart you are referencing in this repo is not our official way to deploy, so we do not really work or address any issues arising from it.
