### ISSUE TITLE
Issue with mutual TLS in minio kubernetes

### ISSUE THREAD

**Issue by haylch** [minio/minio#19871]
## Expected Behavior
Minio server running on kubernetes should request connecting client to send client certs when mutual TLS is enabled. 

## Current Behavior
Set the following settings in minio operator UI console
- TLS enabled
- AutoCert enabled
- Custom Certificates enabled 

I have added CA, Server and Client certs in custom certs section of the operator console UI.

The one-way TLS works as the server did send server certs for the client to verify in the TLS handshake process. But the client TLS is not happening as the server does not seem to request the connecting client to send certs for the server to verify.

Connecting client application is already configured with truststore and client cert keystore.

## Context
Trying to enable mutual TLS in minio

## Your Environment

* Version used (`minio --version`): 5.0.14
* Server setup and configuration: minio running on kubernetes rke2
* Operating System and version (`uname -a`): ubuntu 22.04

**Comment by harshavardhana** [comment]
@haylch mTLS requires that client to use AssumeRoleWithCertificate() STS to get credentials base on certificates.

There is no S3 API protocol level requirement for mTLS available.
