### ISSUE TITLE
Can the time shared by Minio be set to permanent ！！！

### ISSUE THREAD

**Issue by ldy521314** [minio/minio#19880]
The following URL lets you share this object without requiring a login.
The URL expires automatically at the earlier of your configured time (12 hours) or the expiration of your current web session. 

The default is 12 hours, which is very unfriendly to users and I want to set it to permanent！！！！

**Comment by klauspost** [comment]
Assuming you are talking about pre-signed URLs, they have a max lifetime of 7 days as per S3 spec. These are stateless, so there must be an expiration.
