### ISSUE TITLE
Avoid force-pushing Docker images

### ISSUE THREAD

**Issue by sathieu** [minio/minio#19889]
## Expected Behavior

Docker tags to be immutable.

## Current Behavior

`RELEASE.2024-05-28T17-19-04Z` has been force-pushed from `sha256:7cb3f11447d1ac7c4b73420dd8f3601afa16ea0cd7e929ecb00be1a8af1eac05` to `sha256:391d1d45fdbe79944cb6de9337b073864bb9ee38c4c24280bfb39572e925af08` .

![image](https://github.com/minio/minio/assets/741106/23682331-9aae-4434-af04-52e5b6e6480f)

Ref: https://quay.io/repository/minio/minio?tab=history&tag=latest (`RELEASE.2024-05-28T17-19-04Z` in search field).

## Possible Solution

Add a check to avoid pushing when the tag already exists.

## Steps to Reproduce (for bugs)

1. `docker pull quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z@sha256:7cb3f11447d1ac7c4b73420dd8f3601afa16ea0cd7e929ecb00be1a8af1eac05` -> 404 Not found

## Regression

Yes: something was working and is not anymore.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by donatello** [comment]
@sathieu This happened to due an automation bug - the image was re-generated and pushed to the registry - however, the minio binary inside the image is the same as before. I'll be sending a fix to prevent this from happening again.

**Comment by Pumba98** [comment]
> @sathieu This happened to due an automation bug - the image was re-generated and pushed to the registry - however, the minio binary inside the image is the same as before. I'll be sending a fix to prevent this from happening again.

This happened again with RELEASE.2024-08-29T01-40-52Z

**Comment by harshavardhana** [comment]
Yes it was on purpose.
