### ISSUE TITLE
UseSignatureVersion4 does not work for us for upload

### ISSUE THREAD

**Issue by sagar-shah-uipath** [minio/minio#19887]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

When we are explicitly specifying configuration
`AWSConfigsS3.UseSignatureVersion4 = true;`
before creating aws s3 object using aws sdk, minio upload request is failing with error  `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256` . same code works with AWS s3 without any issue
Following code shows how we construct aws s3 client using aws sdk
```
        var accessKey = storageOptions.AccessKey;
        var secretKey = storageOptions.SecretKey;
        AWSConfigsS3.UseSignatureVersion4 = true;
        var awsConfig = new AmazonS3Config
        {
            AuthenticationRegion = "us-east-1"
            ServiceURL = "MINIO_URL",
            ForcePathStyle = true
            SignatureVersion = "v4",
        };
        return new AmazonS3Client(accessKey, secretKey, awsConfig);
    }
```

If we remove AWSConfigS3.UseSignatureVersion4 = true, it works with minio. can someone please explain is there any limitation on minio side?

## Expected Behavior

- Providing `AWSConfigS3.UseSignatureVersion4 = true` should not break upload to minio

## Current Behavior

- `AWSConfigS3.UseSignatureVersion4 = true` configuration is causing failure during upload to minio, if we remove that statement and perform upload it works fine

**Comment by harshavardhana** [comment]
Please provide the entire working reproducer.

**Comment by sidharthkalra** [comment]
// this is the full repro code using dotnet SDK


```
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;

namespace Reproducer
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            Console.WriteLine(await GetPresignedUrl());
        }

        private static AmazonS3Client GetClient()
        {
            AWSConfigsS3.UseSignatureVersion4 = true;
            var awsConfig = new AmazonS3Config
            {
                AuthenticationRegion = "us-east-1",
                ServiceURL = "<serviceUrl>",
                ForcePathStyle = true,
                SignatureVersion = "v4",
            };
            return new AmazonS3Client("<accessKey>", "<secretKey>", awsConfig);
        }

        public static async Task<Uri> GetPresignedUrl()
        {
            using var client = GetClient();
            var bucket = "<my-bucket>";
            var key = "<my-key>";
            var request = new InitiateMultipartUploadRequest
            {
                BucketName = bucket,
                Key = key,
            };
            var response = await client.InitiateMultipartUploadAsync(request, CancellationToken.None);
            var partUploadRequest = new GetPreSignedUrlRequest
            {
                BucketName = bucket,
                Key = key,
                Expires = DateTime.UtcNow + TimeSpan.FromHours(8),
                Verb = HttpVerb.PUT,
                Protocol = Protocol.HTTPS,
                ContentType = "text/csv",
                UploadId = response.UploadId,
                PartNumber = 1,
            };
            return new Uri(client.GetPreSignedURL(partUploadRequest));
        }
    }
}

```

Using the generated presigned url, tried uploading the file with curl. As mentioned by Sagar, this throws an error.

**Comment by ramondeklein** [comment]
**NOTE:** This is not a problem with the Minio SDK, but with the AWS SDK.

The documentation of `AWSConfigsS3.UseSignatureVersion4` states the following:

> Configures if the S3 client should use Signature Version 4 signing with requests.
> By default, this setting is set to `true` which will use Signature Version 4 for all requests **_except presigned URL requests when the region is set to `us-east-1`_**. When `UseSignatureVersion4` is explicitly set to `true` by directly setting this property or directly setting this property through configuration, Signature Version 4 will be used for all requests when able to do so.
When this setting is false, Signature Version 2 will be used. Note that when the setting is false, Signature Version 4 may still be used by default in some cases or with some regions.
> Setting `AWSConfigsS3.UseSignatureVersion4 = true` will use signature version 4, unless you are creating presigned URLs for the `us-east-1` region. For that to work, you'll have to set `AmazonS3Config.SignatureVersion` explicitly.

It's quite unusual behavior that you need to set a property that was already the correct value, but we can't control this behavior (it's not our SDK). When setting this property explicitly to `true`, then I don't need to set the `AmazonS3Config.SignatureVersion` anymore. If you do set it, then set it to `4` (not `v4`) as can be seen here in the [AWS SDK code](https://github.com/aws/aws-sdk-net/blob/8bc4eddb2c1827fd306c3ccb76f26d4f77dd800f/sdk/src/Core/Amazon.Runtime/Internal/Auth/AbstractAWSSigner.cs#L142-L149). I couldn't find any documentation about the correct value (except for source-code). But determining the signature version is quite complex and can be found in the [`AmazonS3Client.DetermineSignatureVersionToUse()`](https://github.com/aws/aws-sdk-net/blob/8bc4eddb2c1827fd306c3ccb76f26d4f77dd800f/sdk/src/Services/S3/Custom/AmazonS3Client.Extensions.cs#L285) function.

It looks like it depends on:
1. Global setting.
2. If bucket is an S3 outpost (on-premise S3), then v4 is enforced.
3. If region only supports v4, then always use v4.
4. Use v2 signature if v4 is not set explicitly (only for `us-east-1` region).
5. If expiration is longer than v4 allows, then fallback to v2 (if the region supports v2).

So the actual signature that is used depends on a lot of factors and even the expiration date of your pre-signed URL may impact the used signature version.

During my testing, setting `AWSConfigsS3.UseSignatureVersion4 = true` explicitly is all that is need. When I run your code (without setting `AmazonS3Config.SignatureVersion`), then I get a pre-signed URL that uses `X-Amz-Algorithm=AWS4-HMAC-SHA256`.

FYI: I used [AWSSDK.S3 v3.7.309](https://www.nuget.org/packages/AWSSDK.S3) using .NET Core 8.0.

**Comment by prakashsvmx** [comment]
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/csharp_s3_code_examples.html

Thank you @ramondeklein , i could build and verified with the below code with local minio.


```
using System;
    using System.IO;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Amazon;
    using Amazon.S3;
    using Amazon.S3.Model;

    /// <summary>
    /// This example shows how to upload an object to an Amazon Simple Storage
    /// Service (Amazon S3) bucket using a presigned URL. The code first
    /// creates a presigned URL and then uses it to upload an object to an
    /// Amazon S3 bucket using that URL.
    /// </summary>

    
    public class UploadUsingPresignedURL
    {

         private static AmazonS3Client GetClient()
        {
            AWSConfigsS3.UseSignatureVersion4 = true;
            var awsConfig = new AmazonS3Config
            {
                AuthenticationRegion = "us-east-1",
                ServiceURL = "http://localhost:22000/",
                ForcePathStyle = true,
                SignatureVersion = "4",
            };
            return new AmazonS3Client("minio", "minio123", awsConfig);
        }

        private static HttpClient httpClient = new HttpClient();

        public static async Task Main()
        {
            string bucketName = "test-bucket";
            string keyName = "1.txt";
            string filePath = "/home/prakash/tmpwork/1.txt";

            // Specify how long the signed URL will be valid in hours.
            double timeoutDuration = 12;

            // Specify the AWS Region of your Amazon S3 bucket. If it is
            // different from the Region defined for the default user,
            // pass the Region to the constructor for the client. For
            // example: new AmazonS3Client(RegionEndpoint.USEast1);

            // If using the Region us-east-1, and server-side encryption with AWS KMS, you must specify Signature Version 4.
            // Region us-east-1 defaults to Signature Version 2 unless explicitly set to Version 4 as shown below.
            // For more details, see https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingAWSSDK.html#specify-signature-version
            // and https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Amazon/TAWSConfigsS3.html
            AWSConfigsS3.UseSignatureVersion4 = true;
            IAmazonS3 client = GetClient();

            var url = GeneratePreSignedURL(client, bucketName, keyName, timeoutDuration);
            var success = await UploadObject(filePath, url);

            if (success)
            {
                Console.WriteLine("Upload succeeded.");
            }
            else
            {
                Console.WriteLine("Upload failed.");
            }
        }

        /// <summary>
        /// Uploads an object to an Amazon S3 bucket using the presigned URL passed in
        /// the url parameter.
        /// </summary>
        /// <param name="filePath">The path (including file name) to the local
        /// file you want to upload.</param>
        /// <param name="url">The presigned URL that will be used to upload the
        /// file to the Amazon S3 bucket.</param>
        /// <returns>A Boolean value indicating the success or failure of the
        /// operation, based on the HttpWebResponse.</returns>
        public static async Task<bool> UploadObject(string filePath, string url)
        {
            using var streamContent = new StreamContent(
                new FileStream(filePath, FileMode.Open, FileAccess.Read));


            var response = await httpClient.PutAsync(url, streamContent);
            return response.IsSuccessStatusCode;
        }

        /// <summary>
        /// Generates a presigned URL which will be used to upload an object to
        /// an Amazon S3 bucket.
        /// </summary>
        /// <param name="client">The initialized Amazon S3 client object used to call
        /// GetPreSignedURL.</param>
        /// <param name="bucketName">The name of the Amazon S3 bucket to which the
        /// presigned URL will point.</param>
        /// <param name="objectKey">The name of the file that will be uploaded.</param>
        /// <param name="duration">How long (in hours) the presigned URL will
        /// be valid.</param>
        /// <returns>The generated URL.</returns>
        public static string GeneratePreSignedURL(
            IAmazonS3 client,
            string bucketName,
            string objectKey,
            double duration)
        {
            var request = new GetPreSignedUrlRequest
            {
                BucketName = bucketName,
                Key = objectKey,
                Verb = HttpVerb.PUT,
                Expires = DateTime.UtcNow.AddHours(duration),
                Protocol=Protocol.HTTP
            };

            string url = client.GetPreSignedURL(request);
            return url;
        }
    }
    ```

**Comment by emanueldejanu** [comment]
@ramondeklein @prakashsvmx the issue is that MinIO is not parsing correctly the SAS URL when you add more headers that needs to be authorize like `Content-Type`, so if you change your `GeneratePreSignedURL` to include the content type header it will give you the error.

```
var request = new GetPreSignedUrlRequest
            {
                BucketName = bucketName,
                Key = objectKey,
                Verb = HttpVerb.PUT,
                Expires = DateTime.UtcNow.AddHours(duration),
                Protocol=Protocol.HTTP,
                ContentType = "application/octet-stream",
            };
```            
The error from MinIO console is the following:
```
minio-1  | API: SYSTEM.authN
minio-1  | Time: 11:39:05 UTC 06/30/2024
minio-1  | DeploymentID: d6cae75c-b869-49e0-aa4b-f875dd11de6a
minio-1  | Error: invalid semicolon separator in query (*errors.errorString)
minio-1  |        5: internal/logger/logger.go:268:logger.LogIf()
minio-1  |        4: cmd/logging.go:50:cmd.authNLogIf()
minio-1  |        3: cmd/auth-handler.go:129:cmd.getRequestAuthType()
minio-1  |        2: cmd/auth-handler.go:618:cmd.setAuthMiddleware.func1()
minio-1  |        1: net/http/server.go:2166:http.HandlerFunc.ServeHTTP()
```

Check the URL generated
```
http://localhost:9000/uipath-as-orchestrator/test/f18556990976347f7a201394d6b5dd9d3.txt?X-Amz-Expires=3600&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin/20240630/us-east-1/s3/aws4_request&X-Amz-Date=20240630T122400Z&X-Amz-SignedHeaders=content-type;host&X-Amz-Signature=79f7cea173c419b274931903db7b817a2f64ff29d963deb77961c627c7aac5b0
````

The parameter that is causing the issue is `X-Amz-SignedHeaders=content-type;host` contains a `;`.

According to https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html is a valid request URI.

Given the new information I hope that you will reopen this issue.

**Comment by emanueldejanu** [comment]
Looking in MinIO code it seems that the issue is caused by  https://github.com/minio/minio/blob/master/cmd/auth-handler.go#L127C17-L127C31 calling `https://pkg.go.dev/net/url#ParseQuery` that don't accept unencoded ';' characters in query string.

**Comment by harshavardhana** [comment]
Not a priority item. Supporting `;` is unsafe in URLs that's why Go is strict about it.

They need to be encoded `value1;value2` as `value1%3Bvalue2`

This is an SDK bug they are not a good HTTP client. Also in this scenario we really don't want to be relaxed due to security concerns around it.

So not reopening, please ask them to fix their sdks.

**Comment by emanueldejanu** [comment]
@harshavardhana thanks for your response, indeed after reviewing MinIO code and reading the specification this must be fixed on AWS S3 SDK.
