### ISSUE TITLE
no logs when running minio server in Linux

### ISSUE THREAD

**Issue by HowHsu** [minio/minio#19908]
How to output logs in terminal? I simply start my minio server with: 
```bash
sudo MINIO_ROOT_USER=xxx MINIO_ROOT_PASSWORD=xxx \
        minio server \
        /path/to/dir \
        --console-address ":9001"

```
no logs printed when I use mc to cat a object in minio storage, why?

**Comment by klauspost** [comment]
MinIO doesn't print access logs.

See docs:

https://min.io/docs/minio/linux/administration/console/managing-deployment.html#audit
https://min.io/docs/minio/linux/administration/monitoring.html
