### ISSUE TITLE
Error: could not read "/proc": stat /proc: no such file or directory (*fmt.wrapError) on the MacOS

### ISSUE THREAD

**Issue by DongZhaoXiong** [minio/minio#19901]
### Description

When I deploy the Minio on my mac, it work fine. However, I config the prometheus server to collect metrics, raise the error message:

Error: could not read "/proc": stat /proc: no such file or directory (*fmt.wrapError) on the MacOS

1. brew install prometheus
2. mc admin prometheus generate kraftminio
3. add the config to prometheus.yml and restart server
4. minio config.yaml as below:
version: v2
address: ":9000"
rootUser: "kraft"
rootPassword: "kraftadmin"
console-address: ":9001"
pools: # Specify the nodes and drives with pools
  - args:
      - "/Users/Kraft/data"

options:
  prometheus: # settings for MinIO to act as an prometheus server
    url: "127.0.0.1:9090"

Please help to confirm what cause this issue

**Comment by DongZhaoXiong** [comment]
Hi, any update?

**Comment by anjalshireesh** [comment]
> Hi, any update?

We're looking into it; will comment here when there is an update.

**Comment by harshavardhana** [comment]
Fixed via #19965
