### ISSUE TITLE
Issue With AssumeRoleWithCerificate

### ISSUE THREAD

**Issue by haylch** [minio/minio#19910]
## Expected Behavior

Should return a temp credential when client connects with the following command:
curl --insecure -X POST --key $KEY --cert $CERT $ENDPOINT
e.g curl --insecure -X POST --key private.key --cert public.crt "https://minio:30000?Action=AssumeRoleWithCertificate&Version=2011-06-15&DurationSeconds=3600"

## Current Behavior

Have already enabled TLS and STS as follows:
  - Enable TLS
  mc admin config set myminio identity_tls skip_verify=off

  - Restart endpoint for alias myminio
  mc admin service restart myminio

  - Enable STS for minio-operator
  kubectl set env deployment/minio-operator -n minio-operator OPERATOR_STS_ENABLED=on

  - Add a policy with name which is the SAME as the CN in the client cert
   
  - Generated client cert contains the Extended Key Usage: 
	TLS Web Client Authentication

But still received response saying STS API AssumeRoleWithCerificate is disabled. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Not able to connect with AssumeRoleWithCerificate

## Your Environment

* Version used (`minio --version`): 5.0.14
* Server setup and configuration: MinIO running on RKE2
* Operating System and version (`uname -a`): Ubuntu 22.04

**Comment by harshavardhana** [comment]
> * Enable STS for minio-operator
>   kubectl set env deployment/minio-operator -n minio-operator OPERATOR_STS_ENABLED=on

Operator STS enabled has nothing to do with MinIO supporting AssumeRoleWithCertificate 


> * mc admin config set myminio identity_tls skip_verify=off
> *

https://github.com/minio/minio/blob/master/docs/sts/tls.md read the docs
