### ISSUE TITLE
with mincache enabled `HEAD` request returns different `Content-Length` then matching `GET` on a KMS setup

### ISSUE THREAD

**Issue by ramondeklein** [minio/minio#19925]
I have enabled server-side encryption on my bucket and uploaded `Audi cabriolet 01.jpg` of 2,971,514 bytes to the `test` bucket. When I try to copy the file using `mc`, then I got the following error: `Input reader closed pre-maturely. Expected '2972986' bytes, but only received '2971514' bytes.`

I ran the `mc` command using the `--debug` flag and noticed that the `HEAD` request returns a different length then the `GET` request. This is the `HEAD` request:
```
HEAD /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 __debug_bin2996553503/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240612T160723Z
```
`HEAD` response:
```
HTTP/1.1 200 OK
Content-Length: 2972986
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Wed, 12 Jun 2024 16:07:23 GMT
Etag: "efd738945e94f4dbb8588b788b2ea7c1"
Last-Modified: Wed, 12 Jun 2024 15:21:24 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D84D79C009F04A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```
Then it performs the actual `GET` and that request looks like:
```
GET /test/audi/Audi%20cabriolet%2001.jpg HTTP/1.1
Host: tenant-rdk-hl.tenant-rdk:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.70 __debug_bin2996553503/DEVELOPMENT.GOGET
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=l5m7mQiwUi2GCSH3/20240612/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240612T160904Z
```
And the response is:
```
HTTP/1.1 200 OK
Content-Length: 2971514
Accept-Ranges: bytes
Content-Type: image/jpeg
Date: Wed, 12 Jun 2024 16:09:04 GMT
Etag: "efd738945e94f4dbb8588b788b2ea7c1"
Last-Modified: Wed, 12 Jun 2024 15:21:24 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: d5a265f7265c149d31b79b2568737f9e0d97aab546838b9090d7403265887733
X-Amz-Request-Id: 17D84D916E7CC820
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:tenant-rdk-key
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```
This seems to be a bug in Minio, because both the `HEAD` and `GET` requests should return the same content length. I never have seen this issue without encryption.

**Comment by ramondeklein** [comment]
There is a cache in-between `mc` and Minio. Disabling the cache fixes the issue and Minio does return the proper content-size and encryption headers.

**Comment by jiuker** [comment]
You have uploaded different size at the same object. 
```
root@DESKTOP-QPDA04R:/mnt/c/workspace/go/src/minkms/dist# mc cp minio9000/mytest/dlv.exe dlv.exe 
mc: <ERROR> Failed to copy `http://192.168.2.6:9000/mytest/dlv.exe`. Input reader closed pre-maturely. Expected `19311104` bytes, but only received `10248344` bytes.
root@DESKTOP-QPDA04R:/mnt/c/workspace/go/src/minkms/dist# 
```

**Comment by harshavardhana** [comment]
No @jiuker you are not understanding the issue. Please DM me.

**Comment by jiuker** [comment]
Restarting mincache will fix the problem? @ramondeklein

**Comment by ramondeklein** [comment]
@jiuker I will try to create a Docker image using this PR and check if the problem still exists.

**Comment by jiuker** [comment]
> @jiuker I will try to create a Docker image using this PR and check if the problem still exists.

Yesh. Please sync the result. Maybe you have another case here. @ramondeklein

**Comment by harshavardhana** [comment]
this is still not fully fixed yet.

**Comment by harshavardhana** [comment]
Please try latest master and also https://github.com/miniohq/mincache/pull/35 @ramondeklein and let us know if it works for you. 

Thanks

**Comment by harshavardhana** [comment]
@shtripat can we open an issue to track testing of mincache with MinIO deployment and that mint tests pass?

**Comment by shtripat** [comment]
> @shtripat can we open an issue to track testing of mincache with MinIO deployment and that mint tests pass?

Sure @harshavardhana , will do needful.
