### ISSUE TITLE
I am trying to configure 2 minio nodes to write to 4 drive mouts on an nfs server, but i when I start the service in both nodes, I get error below: 

### ISSUE THREAD

**Issue by HoangMinhThuyet** [minio/minio#19924]
Jun 12 15:49:12 minio01 minio[9571]: Time: 15:49:12 UTC 06/12/2024
Jun 12 15:49:12 minio01 minio[9571]: DeploymentID: af1a632e-2386-4b75-b7bb-b8b3ed63022b
Jun 12 15:49:12 minio01 minio[9571]: Error: Unable to initialize backend: failed to load rebalance data: Storage resources are insufficient for the read operation .minio.sys/rebalance.bin, retrying in 4.16>
Jun 12 15:49:12 minio01 minio[9571]:        7: internal/logger/logger.go:268:logger.LogIf()
Jun 12 15:49:12 minio01 minio[9571]:        6: cmd/logging.go:152:cmd.storageLogIf()
Jun 12 15:49:12 minio01 minio[9571]:        5: cmd/erasure-server-pool.go:218:cmd.newErasureServerPools()
Jun 12 15:49:12 minio01 minio[9571]:        4: cmd/server-main.go:1156:cmd.newObjectLayer()
Jun 12 15:49:12 minio01 minio[9571]:        3: cmd/server-main.go:908:cmd.serverMain.func10()
Jun 12 15:49:12 minio01 minio[9571]:        2: cmd/server-main.go:560:cmd.bootstrapTrace()
Jun 12 15:49:12 minio01 minio[9571]:        1: cmd/server-main.go:906:cmd.serverMain()

# # config minio
MINIO_VOLUMES="http://minio0{1...2}.labtest.com:9000/data{1...4}"

## config mount nfs server: /etc/exports

/data/minio_01 10.80.4.0/24(rw,sync,no_subtree_check)
/data/minio_02 10.80.4.0/24(rw,sync,no_subtree_check)
/data/minio_03 10.80.4.0/24(rw,sync,no_subtree_check)
/data/minio_04 10.80.4.0/24(rw,sync,no_subtree_check)
~

**Comment by harshavardhana** [comment]
Do not use NFS, we recommend that you bring in real disks with XFS on them.

**Comment by HoangMinhThuyet** [comment]
Yes, yes, I just want to test whether minio supports multiple nodes writing to the same drive
It is could not be? @harshavardhana

**Comment by harshavardhana** [comment]
The issue is use of NFS.

**Comment by HoangMinhThuyet** [comment]
Yes, which kind of storage can use?  for multiple node write same drive.
Please tell me know! Thanks

**Comment by bpedersen2** [comment]
> Yes, which kind of storage can use? for multiple node write same drive. Please tell me know! Thanks

minio can not  have multiple nodes that  write to the same files ( it does not make any sense...)
