### ISSUE TITLE
tests: XL metadata and multipart internal operations lack good coverage

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1992]
Address the lack of coverage in tests on

xl-v1-metadata.go: 63.2% 
xl-v1-multipart-common.go: 54.4%

**Comment by GarimaKapoor** [comment]
please update the timeline for the fix.

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
timeline - 20th

**Comment by krishnasrinivas** [comment]
remaining code coverage will be taken care by https://github.com/minio/minio/issues/2284
@harshavardhana this issue can be closed
