### ISSUE TITLE
Free space not detected with mergerfs storage backend

### ISSUE THREAD

**Issue by presto8** [minio/minio#19938]
I have a Minio endpoint with a storage backend on a mergerfs filesystem comprising 8 independent disks. The mergerfs filesytem is mounted on /backups and the minio data is stored in /backups/minio.

The filesystem reports that the /backups mountpoint has 526 GB free space.

    Filesystem       Size  Used Avail Use% Mounted on
    1:2:3:4:5:6:7:8   57T   56T  526G 100% /backups

However, minio is not detecting this free space correctly and reports that the storage backend is full (this message is from a backup program using the S3 API to the minio endpoint):

   ! Error when processing "...clip....": Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.

Similarly, the minio web console, under the menu Administrator: Monitoring: Metrics: Info, does not list the free space correctly.

## Expected Behavior

Minio should detect the free space correctly on a mergerfs filesystem.

## Current Behavior

Minio detects the freespace on the underlying filesystem that the mergerfs is mounted on (or perhaps it is picking one of the component drives of the mergerfs).

## Steps to Reproduce (for bugs)

1. Set up mergerfs with at least two drives and lots of free disk space
2. Mount mergerfs and configure minio to use the mounted path
3. From web console, Administrator: Monitoring: Metrics: Info, see that the free space reported is not correct.

## Context

I use mergerfs to manage my drives into a JBOD. I would like to use minio to provide an S3 service on this JBOD, however I can't because it doesn't identify the free space and thinks the volume is full.

## Regression

Not sure, I don't think so.

## Your Environment
    * Version used (`minio --version`): minio version RELEASE.2024-06-06T09-36-42Z (commit-id=RELEASE.2024-06-06T09-36-42Z)
    * Server setup and configuration: Basic minio set up, issue can be replicated without setting up buckets
    * Operating System and version (`uname -a`): Linux tank 6.1.91 #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 09:56:25 UTC 2024 x86_64 GNU/Linux

**Comment by ravindk89** [comment]
MergerFS is not a supported backend/filesystem. Unless we see some sort of OS-level trace or log indicating an issue with MinIO, we're unlikely to investigate further.

More likely than not, MergerFS needs better handling on how they respond to standard OS calls around storage resources. You can try to open an issue on their end.

**Comment by presto8** [comment]
Thanks for your comments. But when I use "df" or get disk statistics from Python using the standard calls, on the mergerfs mountpoint, it does return the correct values. Doesn't that point to it being a minio issue?

If mergerfs is not a supported backend, of course that's understandable. But I don't see that it is a mergerfs issue here.

I'll try to get some trace calls and further debug info when I have time.

**Comment by harshavardhana** [comment]
MinIO recommends directly using XFS with JBODs, with no other frill layers in between. Any other artisanal FS is unsupported.

Follow our documentation on the recommended setup. If you think that MinIO has a bug and MergerFS will work even if we don't officially support it - fix it and send a PR, we will happily review it. 

If it's decent, we will merge it.

**Comment by presto8** [comment]
Understood and will do! Thanks very much. Minio is an incredible piece of software. I look forward to getting it working on my setup. I love that phrase "artisanal FS" :-).
