### ISSUE TITLE
MinIO Client bundled with docker container is not auto configured to use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD

### ISSUE THREAD

**Issue by zumm** [minio/minio#19937]
## Expected Behavior
Would be nice if MinIO Client works inside docker container without extra configuration.

## Current Behavior
MinIO Client required extra configuration.

## Possible Solution
`mc alias set local http://127.0.0.1:9000 {MINIO_ROOT_USER} {MINIO_ROOT_PASSWORD}`

## Steps to Reproduce (for bugs)
```
docker run -d \
  -p 9000:9000 \
  -p 9001:9001 \
  --name minio \
  -v minio:/data \
  -e "MINIO_ROOT_USER=user" \
  -e "MINIO_ROOT_PASSWORD=password" \
  quay.io/minio/minio server /data --console-address ":9001"

docker exec -it minio sh

mc ls local
```

`mc: <ERROR> Unable to list folder. Access Denied.`

## Your Environment

* Version used (`minio --version`):
* minio version RELEASE.2024-06-13T22-53-53Z (commit-id=20960b6a2ddb9594ee418035b3c7c7fe92ae6a12)
Runtime: go1.22.4 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Yes it is not and it is done so on purpose to avoid exposing credentials without user consent.

If you need it configure it and it's kept ephemeral on purpose.

**Comment by harshavardhana** [comment]
And no we are not changing it.
