### ISSUE TITLE
tests: Address lack of coverage on signature-v4 utility functions

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1993]
signature-v4-parser.go: 51% 
signature-v4-utils.go: 41%
signature-v4.go: 47%

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
cc @harshavardhana 

@krisis if we can refactor signature calculation api to:

```
func getSginatureV4(method string, url http.URL, headers http.Header, accessKey string, secretKey string, region string) (signature string)
```

the same function can be used on server and minio-go. And also the signature test cases you had found on amazon can be reused by us (if license permits, else we can our own test cases) to write the unit test cases which will help in coverage.

**Comment by hackintoshrao** [comment]
[30th July].

**Comment by hackintoshrao** [comment]
Part -1 fix - Tests for signature utils and their associated functions -  https://github.com/minio/minio/pull/2342 .

**Comment by hackintoshrao** [comment]
Part - 2 fix - Test for signature parser https://github.com/minio/minio/pull/2362 .

**Comment by hackintoshrao** [comment]
Part -3 fix: https://github.com/minio/minio/pull/2375
