### ISSUE TITLE
profile: Analyze memory profiling.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1994]
Implement 'go test -bench' to get the allocation list.

**Comment by GarimaKapoor** [comment]
Please update the timeline.

**Comment by harshavardhana** [comment]
Memory profiling is finished.. No significant changes needed on the server,  memory usage is well with in the ballpark and server doesn't crash for large amount of requests as well. 

```
Running 500 routines GET i.e with aws cli becomes 5000 requests,  uses around 30GB gets used.
```

```
Running 200 routines PUT i.e with aws cli becomes 2000 requests, uses around 6GB gets used.
```

Subsequently GC de-allocates them as well.

Closing the bug this activity led to fixing of around 4 different issues.  Next tasks to be done are block profiling and cpu profiling for wrong inputs. 

Going to close the bug and focus on other profiling for now. Please re-open if this is seen again.
