### ISSUE TITLE
Minio Nginx Reverse Proxy is not working

### ISSUE THREAD

**Issue by amankumarchagti** [minio/minio#19944]
My Minio Server is running on 127.0.0.1 (UI - 9001, API - 9000). and i am trying to expose the API only to /api/minio for my domain test.testing.co

Following is nginx configuration:
```
server {
    listen 80;
    server_name test.testing.co;

    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;

    # No need for Docker DNS resolver since Minio is on localhost
    set $upstream "127.0.0.1";
    location /api/filemanager2 {
        proxy_pass http://$upstream:9000;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        proxy_connect_timeout 300;

        # To support websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        chunked_transfer_encoding off;
    }
}
    
```

when i reach to test.testing.co/api/filemanager2, it is showing this:

<img width="321" alt="image" src="https://github.com/minio/minio/assets/73024810/7532e2ee-a872-4b77-a706-7b4d4e695d31">

and when i try to upload object to minio using java client using following code.

```
 MinioClient minioClient =
                    MinioClient.builder()
                            .endpoint("httos://test.testing.co/api/filemanager2)
                            .credentials("minioadmin", "minioadmin")
                            .build();
```
I am getting following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: no path allowed in endpoint https://test.testing..co/api/filemanager2/
	at io.minio.http.HttpUtils.validateUrl(HttpUtils.java:114)
	at io.minio.http.HttpUtils.getBaseUrl(HttpUtils.java:125)
	at io.minio.MinioAsyncClient$Builder.endpoint(MinioAsyncClient.java:3281)
	at io.minio.MinioClient$Builder.endpoint(MinioClient.java:2473)
	at org.example.minioUpload.main(minioUpload.java:22)

```

**Comment by harshavardhana** [comment]
S3 API cannot be hosted at a custom path, resources are real entities on drives.  Follow what we have documented, don't experiment with things that are not supported or documented.

**Comment by tschuehly** [comment]
@harshavardhana 
Why is this arbitrary restriction there? Even S3 allows for paths: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
Is there any part in the S3 specification that disallows this? Otherwise the minio-client is not S3 compatible?

I cannot control the path that it is hosted on with Supabase for example.

**Comment by marktheunissen** [comment]
@tschuehly S3 supports path and domain style, e.g. from the docs page you posted, the following are equivalent:

- https://s3.region-code.amazonaws.com/bucket-name/key-name
- https://bucket-name.s3.region-code.amazonaws.com/key-name

MinIO supports the same functionality.

The config you posted above, attempts to change the URL scheme to include `/api/filemanager2` in the path, which is not supported.
