### ISSUE TITLE
profile: Analyze CPU profiling. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1995]
Analyze the amount of CPU used by the call path.

**Comment by GarimaKapoor** [comment]
please update the timeline.

**Comment by krisis** [comment]
Jul 6th

**Comment by krisis** [comment]
CPU profiling was done at various snapshots of the development branches and master. The aim of the exercise was to identify any deviation from expected performance characteristic and to investiage if it warranted a backend format change. No such conclusions were made. Here are a few cpu profile graphs referred below.

Summary:
[Run on commit id 8ddf520](https://github.com/minio/minio/files/361120/8ddf520-cpu.pdf) - sha256 and blake-2b consuming 42% and 24% of cpu time respectively
[Run on master + PR #2066, before it was merged](https://github.com/minio/minio/files/361121/2066-cpuprof.pdf) - sha256 and blake-2b consuming 85% and 42% of cpu time respectively
[Run on PR #2191, before it was merged](https://github.com/minio/minio/files/361122/nslocking-cksuminfo-fix-cpu.pdf) - sha256 and blake-2b consuming 52% and 16% of cpu time respectively

**Comment by hackintoshrao** [comment]
On a different note @krisis  you can use the script here https://github.com/minio/minio/blob/master/dist/benchmark/benchcmp.sh to do benchmark compare between  2 commits, this might be useful in future.

**Comment by fwessels** [comment]
Can we re-analyze CPU profiling with minio/sha256-simd ?
