### ISSUE TITLE
profile: Analyze block profiling 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1998]
Analyze blocking code paths.

**Comment by GarimaKapoor** [comment]
Please update the timeline.

**Comment by krisis** [comment]
This issue is being currently worked on. Initial block profile analysis must be complete by EOD. Issues found while running the profile setup will be tracked separately.

**Comment by krisis** [comment]
Block profile when 200 concurrent uploads/downloads on a bucket
[2066-blockprof.pdf](https://github.com/minio/minio/files/344375/2066-blockprof.pdf)

**Comment by krisis** [comment]
[ ] - Need to perform block profiling for list objects.

**Comment by GarimaKapoor** [comment]
@krisis please update the status and the results of the block profiling.

**Comment by krisis** [comment]
Block profile when 200 concurrent uploads/downloads on a bucket with master as of Jul 5th.
[8ddf520-jul5-block.pdf](https://github.com/minio/minio/files/351480/8ddf520-jul5-block.pdf)

**Comment by krisis** [comment]
Block profile for listing a million objects in a bucket.
[f55093c-jul7-blockprof.pdf](https://github.com/minio/minio/files/353148/f55093c-jul7-blockprof.pdf)

**Comment by harshavardhana** [comment]
Closing now being tracked at #2082
