### ISSUE TITLE
Objects still available after delete request completes successfully with replication

### ISSUE THREAD

**Issue by Foxcapades** [minio/minio#19983]
Ref #19981  Issue still present in `RELEASE.2024-03-15T01-07-19Z`

## Expected Behavior

Target object is no longer 'deleted' after delete request returns success.

## Current Behavior

Target object is still available for a short period of time after the delete request returns successfully.

## Possible Solution

Poll and wait for a 404 after deleting an object to ensure the delete is actually done?

## Steps to Reproduce (for bugs)

**MAY REQUIRE REPLICATION**  I was not able to reproduce with a local stack, only using our live stack which has site replication enabled.

```kotlin
import io.minio.*
import java.util.UUID

fun main() {
  val client = MinioClient.builder()
    .endpoint(System.getenv("MINIO_ENDPOINT"), 443, true)
    .credentials(System.getenv("MINIO_USER"), System.getenv("MINIO_PASS"))
    .build()

  val obj = UUID.randomUUID().toString()
  val bucket = System.getenv("MINIO_BUCKET")

  print("put object - ")
  println(client.putObject(PutObjectArgs.builder()
    .bucket(bucket)
    .`object`(obj)
    .stream(ByteArray(0).inputStream(), 0, 0)
    .contentType("text/plain")
    .build())
    .versionId())

  println("delete object")
  client.removeObject(RemoveObjectArgs.builder().bucket(bucket).`object`(obj).build())

  while (true) {
    print("stat object - ")
    println(client.statObject(StatObjectArgs.builder().bucket(bucket).`object`(obj).build()).versionId())
  }
}
```

The result varies from getting the expected 404 immediately to being able to make multiple successful stat requests against the object before it is gone.  The expectation of the test script is that if MinIO was behaving as expected, then the script would throw an exception the first time it attempts to stat the object.

Example result:
```
put object - 29929f6f-4304-486c-88e9-39409f6dacda
delete object
stat object - 29929f6f-4304-486c-88e9-39409f6dacda
stat object - 29929f6f-4304-486c-88e9-39409f6dacda
stat object - Exception in thread "main" error occurred
```

## Context

Intermittent/occasional system hiccups due to unexpected bucket content state.  In the system we detected this issue we are running queued jobs.  By chance, sequential jobs may attempt to operate on the same key/path.

* Job 1 completed by performing a delete on object `foo/bar`
* Job 2 started intending to create object `foo/bar`
    * As a pre-check Job 2 attempted to verify that `foo/bar` does not already exist by using stat
    * MinIO reported that `foo/bar` still exists
* Job 2 aborted due to the unexpected state
* MinIO finally 'deleted' the object

## Regression

Unknown.

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-03-15T01-07-19Z`
* Server setup and configuration: Standard/default setup with site replication.
* Operating System and version (`uname -a`): Linux *** 3.10.0-1160.49.1.el7.x86_64 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please upgrade to latest MinIO release https://github.com/minio/minio/releases/tag/RELEASE.2024-06-22T05-26-45Z

**Comment by harshavardhana** [comment]
Also next time when you report an issue please share the server logs, on all servers on all sites.
