### ISSUE TITLE
MinIO Server throws a 503 Error for Uploading PDF-File

### ISSUE THREAD

**Issue by Zipunrar** [minio/minio#19992]
Hello MinIO-Team,

I got an error code 503 trying to upload a PDF-file. The error occurs in my development environment. I run a docker container of
your official image on my Windows host system.

I can provide you the PDF file. However, the content is not our property and I am not allowed to share this in public.
Is it possible to send you the file via mail for debugging?

## Expected Behavior
The file will upload as normal, without the error.

## Current Behavior
Uploading a PDF file, either via CLI oder web UI or via Java interface library (group: 'io.minio', name: 'minio', version: '8.5.7') will throw the error mentioned above.
![image](https://github.com/minio/minio/assets/5785373/90302171-8e30-4f12-aa4a-137819bf58f6)

## Possible Solution
I have no idea. I tried other PDF files from the same source, but they work without error. Other PDFs work also, independent of size, source or content. I also upgraded or downgraded with several minio server images from 2024.

I tried this file multiple times via different APIs as well as removing the file extension with no luck. However, opening the file with a text editor and manipulating the raw content (I know this breaks the PDF) but this works if I remove the first line, which contains:

```
%PDF-1.7  <--- remove this line
%Çì¢
%%Invocation: path/gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/printer -sDEVICE=pdfwrite -sOutputFile=? ? ? ? ? ? ? ? -f ?
```
After removing the line, the file can be uploaded without errors. So it seems, that the issue is related to the content of the file.
Is it possible that MinIO tries to read or interpret the content somehow and fails?

## Steps to Reproduce (for bugs)
1. Create a docker container using the following command:
```shell
docker run --rm -it -p 9000:9000 -p 9001:9001 -v %cd%/tmp/minio:/data -v %cd%/tmp/secrets:/secrets -e MINIO_ROOT_USER_FILE=/secrets/user -e MINIO_ROOT_PASSWORD_FILE=/secrets/pass minio/minio:RELEASE.2024-03-30T09-41-56Z server /data --console-address :9001 --address :9000
```
Username: admin
Password: 12345678

2. Login into the web UI at http://localhost:9001
3. Create a bucket
4. Try to upload the file via UI oder CLI into this bucket

## Context
We are currently upgrading our internal backend service (Java based) on the minio release 2024 from 2022 releases (I know, very large gap :)) The effect is currently development only, but we want to bring this in production as soon as possible.

## Regression
Its a new issue for me. I don't find other issues with the same source or scenario, except:
https://github.com/minio/minio/issues/10496
But my error occurs independent of thread count or the interface used.

## Environment
* MinIO Server Image Version: RELEASE.2024-03-30T09-41-56Z and RELEASE.2024-06-22T05-26-45Z
* OS: Windows 10
* Web-Browser: Chrome v126+
* Docker Desktop: 4.27.1

I would be grateful for any help, as unfortunately I don't know what to do next.

**Comment by klauspost** [comment]
So you are running MinIO server on Windows? 

Disable your AV software.

**Comment by Zipunrar** [comment]
What? Excuse me? Are you kidding me?
I wrote a complete issue, to bring up as many details as possible and all you return is "disable your anti-virus software"?
Like why. What does it has to do with the issue. I can upload and work with the docker container as normal, but only a specific file is not possible to be uploaded. Why would my AV have influence on that?

At least give me a reason.

**Comment by klauspost** [comment]
Everything you write points to something messing with the files written to disk (locking/removing them). On Windows that is pretty much always AV software. Not much more explain.

**Comment by Zipunrar** [comment]
Ok, just to make this clear: Sorry, if I sound rude in my last comment, but working on this *** the hole day makes me mad. 

However, for everybody that will came across this too: @klauspost was correct. At least it seems that some process, not sure if it really is the AV, interfers with the files.

It works after creating a explicit mount volume for the container using
```shell
docker volume create minio
docker run --rm -it -p 9000:9000 -p 9001:9001 -v minio:/data -v %cd%/tmp/secrets:/secrets -e MINIO_ROOT_USER_FILE=/secrets/user -e MINIO_ROOT_PASSWORD_FILE=/secrets/pass minio/minio:RELEASE.2024-03-30T09-41-56Z server /data --console-address :9001 --address :9000
```

With this, the files will be written into a "simulated" volume, so no changes are made except by minio itself.
