### ISSUE TITLE
MinIO get wrong ip address location it show as [ or 127.0.0.1

### ISSUE THREAD

**Issue by hoanbc** [minio/minio#19990]
I have issues with ip location on MinIO version 2024-06-13T22:53:53Z
It show ip address location as [ or 127.0.0.1 -> i can't set a policy for deny/allow specific ip address for my bucket.
My topology as: Client -> Nginx Reverse Proxy -> MinIO
![image](https://github.com/minio/minio/assets/26288807/79f1282d-ea94-467c-be34-9ec4d8928a1e)
![image](https://github.com/minio/minio/assets/26288807/c81c2e73-036c-4461-a05e-2f8f9349b704)

**Comment by jiuker** [comment]
So, could you share the nginx config?

**Comment by klauspost** [comment]
Traces show the "Host" as received and does not do any parsing.

Don't use upstream IP filtering. It is trivial to bypass.

**Comment by hoanbc** [comment]
> So, could you share the nginx config?

Hi @jiuker  
My nginx as below, that is config have recommend from minio document.
Link: https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

```yml
upstream minio_s3 {
   least_conn;
   server minio:9000;
}

upstream minio_console {
   least_conn;
   server minio:9001;
}
server {
   listen       443;
   server_name  s3.devops.id.vn;
   ssl on;
   ssl_certificate          /etc/nginx/ssl/devops-crt.pem;
   ssl_certificate_key      /etc/nginx/ssl/devops-key.pem;
   # Allow special characters in headers
   ignore_invalid_headers off;
   # Allow any size file to be uploaded.
   # Set to a value such as 1000m; to restrict file size to a specific value
   client_max_body_size 0;
   # Disable buffering
   proxy_buffering off;
   proxy_request_buffering off;
   location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_connect_timeout 300;
      # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      chunked_transfer_encoding off;
      proxy_pass https://minio_s3; # This uses the upstream directive definition to load balance
   }
}

server {
   listen       443;
   server_name  s3-console.devops.id.vn;
   ssl on;
   ssl_certificate          /etc/nginx/ssl/devops-crt.pem;
   ssl_certificate_key      /etc/nginx/ssl/devops-key.pem;

   # Allow special characters in headers
   ignore_invalid_headers off;
   # Allow any size file to be uploaded.
   # Set to a value such as 1000m; to restrict file size to a specific value
   client_max_body_size 0;
   # Disable buffering
   proxy_buffering off;
   proxy_request_buffering off;

   location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-NginX-Proxy true;
      # This is necessary to pass the correct IP to be hashed
      real_ip_header X-Real-IP;
      proxy_connect_timeout 300;
      # To support websocket
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      chunked_transfer_encoding off;
      proxy_pass https://minio_console; # This uses the upstream directive definition to load balance and assumes a static Console port of 9001
   }
}
```

**Comment by hoanbc** [comment]
> Traces show the "Host" as received and does not do any parsing.
> 
> Don't use upstream IP filtering. It is trivial to bypass.

Sorry, that mean i can't use condition ip address for allow/deny action? or it have limitation?

**Comment by klauspost** [comment]
You can. But anyone can add to `X-Forwarded-For`, so it it not safe.

**Comment by hoanbc** [comment]
> You can. But anyone can add to `X-Forwarded-For`, so it it not safe.

Yes, i did config X-Forwarded-For on nginx. i think that it should have same ip address for request. But it use ip of minio (nginx) for send 
![image](https://github.com/minio/minio/assets/26288807/b1949b93-1161-4522-84f0-41affd1371b9)

**Comment by harshavardhana** [comment]
There is nothing here for MinIO. Host header is a LB layer value the real source IP exists in x-forwarded-for or x-real-ip
