### ISSUE TITLE
benchmarks:  Add benchmarks for `PutObjectPart`.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2000]

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by hackintoshrao** [comment]
Timeline 2nd July.

**Comment by hackintoshrao** [comment]
Working on more critical bugs. Will be getting back to this after fixing. Meanwhile @vadmeste  or @awwalker or @balamurugana can pick this up. I have ideas on the implementation, will be really useful if we get benchmarks for `PutObjectPart` 

[9th July]

**Comment by GarimaKapoor** [comment]
@vadmeste can you co ordinate with Karthic and work on this fix.

**Comment by balamurugana** [comment]
I am working on this.

**Comment by harshavardhana** [comment]
This already fixed in master, closing.
