### ISSUE TITLE
Unable to add sites for replication. Invalid site-replication request (duplicate sites provided for site-replication)

### ISSUE THREAD

**Issue by aaaleeexTLC** [minio/minio#20000]
Hi all

This is my situation:
VM1: freebsd14. Minio installed, up & running just fine.
VM exported and imported with a different name, ip address, same domain. All this with the objective of making of it a second node for a minio cluster

VM2: started, assigned a new servername, new ip, copied certificates. Minio up & running just fine (even with certificates so I can connect using https)

Aliases registered for the 2 sytems, "source" and "target" just fine (both of them using the exactly very same AccessKey and SecretKey

I can do a mc alias list on both systems for the remote one

Problem:

When I try 
/usr/local/bin/minio-client admin replicate add source target --debug

I'm getting the following error message:

minio-client: <ERROR> Unable to add sites for replication. Invalid site-replication request (duplicate sites provided for site-replication)

Of course I'm suspecting that somewhere there's some HostID that was duplicated along with all the information of the VM and it's causing minio to think both VMs are the same one

Is there a way to fix this?
BTW I tried this also using GUI and got the same error messages (duplicated sites provided)

I've already tried reinstalling minio (sudo pkg install -Rf minio) with no success, or well, same behavior.

I was able to set up bucket replication, so it looks both minio servers are working fine, but I have this issue when trying to replicate them with mc admin replicate add ALIAS1 ALIAS2

RELEASE.2024-01-31T08-59-40Z | Commit:62b12a277082 | OS:freebsd | Arch:amd64 | Lang:go1.20.14 | Mem:67 MiB/139 MiB | Heap:67 MiB/128 MiB.

Thanks a lot
Alex

**Comment by harshavardhana** [comment]
Just exporting and reusing same backend drives won't work. We persist information that would become invalid.

You need to wipe things clean on your secondary site.

**Comment by aaaleeexTLC** [comment]
Thanks Hashavardhana for the answer... when you said "wipe things clean" what do you mean?, uninstall minio and install it again? or the whole OS?

**Comment by harshavardhana** [comment]
> Thanks Hashavardhana for the answer... when you said "wipe things clean" what do you mean?, uninstall minio and install it again? or the whole OS?

The data drive on your site2 must be clean.
