### ISSUE TITLE
Can support separation of metadata and data?

### ISSUE THREAD

**Issue by iabetor** [minio/minio#20026]
Now both metadata and data are in the same directory without separation. Does MinIO have plans to support separation of metadata and data? This way, we can store metadata on higher-performance disks and data on disks with larger capacity.

**Comment by klauspost** [comment]
You can use [tiering](https://min.io/docs/minio/kubernetes/upstream/administration/object-management/object-lifecycle-management.html#object-transition-tiering) to separate data and metadata.

We do not have any further plans in this direction.
