### ISSUE TITLE
After disabling encryption and enabling it back it is not able to login to console and not able to list polices

### ISSUE THREAD

**Issue by mohantnr** [minio/minio#20041]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1. Disable minio encryption in operator
2. Delete secrete key tenant1-secret-kes-configuration from name space
3. Restart minio
4. Then enable encryption
5. error 
API: SYSTEM()
Time: 07:47:48 UTC 07/05/2024
DeploymentID: dc0a7820-fd06-41fa-8ce8-02d349949c50
Error: Failure in periodic refresh for IAM (took 0.17s): decryption failed: ciphertext is not authentic (*errors.errorString)
       2: internal/logger/logger.go:270:logger.LogIf()
       1: cmd/iam.go:444:cmd.(*IAMSys).watch()

API: SYSTEM()
Time: 07:57:48 UTC 07/05/2024
DeploymentID: dc0a7820-fd06-41fa-8ce8-02d349949c50
Error: Failure in periodic refresh for IAM (took 0.18s): decryption failed: ciphertext is not authentic (*errors.errorString)
       2: internal/logger/logger.go:270:logger.LogIf()
       1: cmd/iam.go:444:cmd.(*IAMSys).watch()

API: SYSTEM()
Time: 08:07:48 UTC 07/05/2024
DeploymentID: dc0a7820-fd06-41fa-8ce8-02d349949c50
Error: Failure in periodic refresh for IAM (took 0.18s): decryption failed: ciphertext is not authentic (*errors.errorString)
       2: internal/logger/logger.go:270:logger.LogIf()
       1: cmd/iam.go:444:cmd.(*IAMSys).watch()

## Context

Not able to login to console and not able to list admin polices

## Your Environment

* Version used (`minio --version`): RELEASE.2022-07-13T23-29-44Z
* Server setup and configuration: 16 servers 
* Operating System and version (`uname -a`):4.18.0-513.24.1.el8_9.x86_64

**Comment by mohantnr** [comment]
I have not deleted existing key in Azure Keyvault. I am using same old key for encryption.

**Comment by harshavardhana** [comment]
Enabling, disabling and enabling is not supported.

You must never disable encryption once enabled.

**Comment by mohantnr** [comment]
Hi Harsha,

How to recover it now? We have not enabled encryption for any bucket. But only problem is console and policy listing.

Regards
Mohan

**Comment by mohantnr** [comment]
> Enabling, disabling and enabling is not supported.
> 
> You must never disable encryption once enabled.

is it possible to recover only console and listing polices?. We have not enabled encryption for any buckets?

**Comment by harshavardhana** [comment]
> is it possible to recover only console and listing polices?. We have not enabled encryption for any buckets?

No, it is not possible. When you enable encryption, all IAM assets get encrypted. You cannot disable encryption.

If you want to re-enable encryption you have to provide the same master key on the kes deployment otherwise the existing data is gone if your master key has changed.

**Comment by mohantnr** [comment]
> > is it possible to recover only console and listing polices?. We have not enabled encryption for any buckets?
> 
> No, it is not possible. When you enable encryption, all IAM assets get encrypted. You cannot disable encryption.
> 
> If you want to re-enable encryption you have to provide the same master key on the kes deployment otherwise the existing data is gone if your master key has changed.

I am providing same Master key which is stored in Azure Keyvault.  I have not deleted key. We have kept that same key.

**Comment by mohantnr** [comment]
> > > is it possible to recover only console and listing polices?. We have not enabled encryption for any buckets?
> > 
> > 
> > No, it is not possible. When you enable encryption, all IAM assets get encrypted. You cannot disable encryption.
> > If you want to re-enable encryption you have to provide the same master key on the kes deployment otherwise the existing data is gone if your master key has changed.
> 
> I am providing same Master key which is stored in Azure Keyvault. I have not deleted key. We have kept that same key.

Key name is : my-minio-key Created 7/27/2022, 5:00:13 PM Updated 7/27/2022, 5:00:13 PM . Kindly find the created and updated keys

**Comment by klauspost** [comment]
We are not going to argue what you did and didn't do. The key you provide doesn't decrypt the data - it is as simple as that. We cannot magically "unencrypt" your data. If you cannot provide the correct key, that data is lost.

If you've deleted the secret key as you claim above I don't see how we can help you.

**Comment by mohankumar-h** [comment]
> We are not going to argue what you did and didn't do. The key you provide doesn't decrypt the data - it is as simple as that. We cannot magically "unencrypt" your data. If you cannot provide the correct key, that data is lost.
> 
> If you've deleted the secret key as you claim above I don't see how we can help you.

I have not deleted key which is stored in keyvault . I have to deleted secret key to reenable else it was not allowing me to re-enable it.  it was saying secretkey is already present.  also also I took backup of secret key before deleting and compared after operated created secret key. Both key data looks same. 

If it is not recoverable., is it way possible to re-create/reset IAM polices and re-attach to buckets? I can access data as root Access keys.

**Comment by mohantnr** [comment]
> We are not going to argue what you did and didn't do. The key you provide doesn't decrypt the data - it is as simple as that. We cannot magically "unencrypt" your data. If you cannot provide the correct key, that data is lost.
> 
> If you've deleted the secret key as you claim above I don't see how we can help you.

I have not deleted key, it is still present in AZ keyvault.  

I have to delete and secret "tenant1-secret-kes-configuration", because operator was not allowing me to create new secret with same configuration which earlier it was present. 

I have backed up tenant1-secret-kes-configuration key before deleting it.   

secret key got created with same secrete key name and with same information. I have compared with old secret key after enabling encryption. 

Still if not possible, is their way to reset IAM polices/re-create it?

**Comment by mohantnr** [comment]
> > We are not going to argue what you did and didn't do. The key you provide doesn't decrypt the data - it is as simple as that. We cannot magically "unencrypt" your data. If you cannot provide the correct key, that data is lost.
> > If you've deleted the secret key as you claim above I don't see how we can help you.
> 
> I have not deleted key, it is still present in AZ keyvault.
> 
> I have to delete and secret "tenant1-secret-kes-configuration", because operator was not allowing me to create new secret with same configuration which earlier it was present.
> 
> I have backed up tenant1-secret-kes-configuration key before deleting it.
> 
> secret key got created with same secrete key name and with same information. I have compared with old secret key after enabling encryption.
> 
> Still if not possible, is their way to reset IAM polices/re-create it?

miniomc admin kms key status lbfm1pobs --json
{
    "keyId": "my-minio-key",
    "encryption": true,
    "decryption": true,
    "status": "success"
}

**Comment by mohantnr** [comment]
is their way to check master key got changed? I do see master key (my-minio-key) creation time stamp remain unchanged in azureKV.

This is my secret tenant1-secret-kes-configuration. before and after re-creation. it is exactly same. 

address: 0.0.0.0:7373
root: disabled
tls:
  key: /tmp/kes/server.key
  cert: /tmp/kes/server.crt
policy:
  default-policy:
    paths:
    - /v1/key/create/my-minio-key
    - /v1/key/generate/my-minio-key
    - /v1/key/decrypt/my-minio-key
    identities:
    - ${MINIO_KES_IDENTITY}
cache:
  expiry:
    any: 5m0s
    unused: 20s
log:
  error: "on"
  audit: "off"
keys:
  azure:
    keyvault:
      endpoint: https://azurekvxxxx
      credentials:
        tenant_id: xx
        client_id: xx
        client_secret: xx

**Comment by harshavardhana** [comment]
Messing around with KMS will lead to lots of complex behaviors.

Note: you cannot do

- I went with KMS created a bunch of things
- Now I reverted but my disks are same
- Now I again went back because I am confused what I want.

No the above process is not supported.
