### ISSUE TITLE
Copy data from crashed minio server to new one

### ISSUE THREAD

**Issue by manju-rn** [minio/minio#20050]
I had a minio server (say m1) with some data. It crashed and not recoverable. I do have the  full contents where the m1 stored the data.
So I have setup a new minio server (say m2).  In the directory location where m2 creates the contents, I have now placed the contents from m1.  What changes needs to be done to make those visible in m2?

## Expected Behavior
By copying the contents as a whole, I was expecting m2 will just recognize the file and will work just like m1 did earlier

## Current Behavior
The buckets in M2 are empty - which the folder where it stores the data has been copied from m1

## Possible Solution
Need solution

## Steps to Reproduce (for bugs)
1. Create a Minio server using operator in k8s. create a PV by mapping to a localhost folder location
2. Upload some files from Minio UI
3. remove Minio - but keep the data
4. Create another minio and point to new location. Copy all the contents from previous minio to new
5. The expectation was that the minio would just show up the data as earlier since the entire data from earlier minio was copied over

## Context
In case of Minio server failure (however, the data is intact).  Should be able just create a new minio server and copy over the contents. Since the format of the storage is not altered with, the expectation was that the data will just be restored in the new Minio UI

## Regression
NA

## Your Environment
* Version used (`minio --version`): 
* Server setup and configuration:  minio on minikuibe using operator
* Operating System and version (`uname -a`): AMD64

**Comment by harshavardhana** [comment]
> In case of Minio server failure (however, the data is intact). Should be able just create a new minio server and copy over the contents. Since the format of the storage is not altered with, the expectation was that the data will just be restored in the new Minio UI

can you show me how those contents are stored? also `cat /path/to/mount/.minio.sys/format.json` ?

**Comment by manju-rn** [comment]
Here is the structure. 
1.  The dir ending with `a0778b4a7ca4`  is the old storage for which the minio crashed
2. The dir ending with `aa8650677f9d`  is the new minio path in which i copied the complete contents from `a0778b4a7ca4`
3. And here is the cat from format.json
```
manju@minipc:~/zfs-pool/nextcloud-bucket-1/minio-minipc-ns-data0-minio-pool-0-0-pvc-14faa777-b710-4c9d-8c10-a0778b4a7ca4/.minio.sys$ cat format.json
{"version":"1","format":"xl-single","id":"b5a4d864-5ba3-42f8-bb95-f53ac734b4ab","xl":{"version":"3","this":"0428da68-4822-4422-9674-d5979a98d4d8","sets":[["0428da68-4822-4422-9674-d5979a98d4d8"]],"distributionAlgo":"SIPMOD+PARITY"}}
```

![image](https://github.com/minio/minio/assets/26291847/05839da8-d79b-427f-9dd2-fa88de87bdcc)

**Comment by harshavardhana** [comment]
are you sure you specified the right path for MinIO? are permissions the same?

**Comment by manju-rn** [comment]
Yes all permissions are the same (infact used the same exact user and passwd as earlier) - I will try to recreate
So there is nothing to be changed after copying? it should just automatically pick up?

**Comment by manju-rn** [comment]
Looks like restart of minio instance fixed the issue. Didn't have to make any changes
