### ISSUE TITLE
Unable to disable individual bucket notifications

### ISSUE THREAD

**Issue by allanrogerr** [minio/minio#20055]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Bucket notification cannot be individually disabled

## Current Behavior
```
ubuntu@ilm:~$ mc event ls ilm/test
arn:minio:sqs::TEST:webhook   s3:ObjectRestore:*,s3:ObjectTransition:*   Filter: 
ubuntu@ilm:~$ mc event rm ilm/test arn:minio:sqs::TEST:webhook
mc: <ERROR> Unable to disable notification on the specified bucket. no notification configuration matched.
ubuntu@ilm:~$ mc event rm ilm/test --force
Successfully removed 
ubuntu@ilm:~$ mc event ls ilm/test
ubuntu@ilm:~$ 
```

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Create a bucket e.g. `mc mb ilm/test`
Add an event e.g. `mc event add ilm/test arn:minio:sqs::TEST:webhook --event "ilm"`
Attempt to disable the event e.g. `mc event add ilm/test arn:minio:sqs::TEST:webhook --event "ilm"`
Observe the error

## Context
Test of documented MinIO server functionality `https://min.io/docs/minio/linux/reference/minio-mc/mc-event-remove.html` 

## Regression
Unknown

## Your Environment
* Version used (`minio --version`):
mc --version
mc version RELEASE.2024-07-03T20-17-25Z (commit-id=d6ff97012549bfd91396447249297411ccfc79a7)
Runtime: go1.22.5 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

* Server setup and configuration:
* Operating System and version (`uname -a`):
uname -a
Linux ilm 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
It is required that you specify all parameters that was specified in `add` to `mc event rm` 

For example in this case you have `ilm,transition` configured not `put,get,delete` so `mc event rm` which defaults to `put,get,delete` without explicit `--event` flag it is rejecting this as a valid ARN that is matching.

So if you want to match it with your `add` you need to reuse the same `--event` flag with `mc event rm` as well. 

So this is working as intended, but might need a documentation update to clarify why `--event` must be used.

@djwfyi @ravindk89 @feorlen
