### ISSUE TITLE
[docs/] Unable to create removal of delete markers ILM rule

### ISSUE THREAD

**Issue by allanrogerr** [minio/minio#20054]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
Using minio latest version, I should be able to implement the ILM rule documented here: https://github.com/minio/minio/blob/master/docs/bucket/lifecycle/README.md#33-automatic-removal-of-delete-markers-with-no-other-versions

## Current Behavior
```
mc ilm import play/testbucket <<EOF
{
    "Rules": [
        {
            "ID": "Removing all delete markers",
            "Expiration": {
                "DeleteMarker": true
            },
            "Status": "Enabled"
        }
    ]
}
EOF

mc: <ERROR> Unable to set new lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.
```

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Using a system with `mc` installed, run the above command `mc ilm import play/testbucket`.

## Context
Test of documented MinIO server functionality `3.3 Automatic removal of delete markers with no other versions`

## Regression
Unknown

## Your Environment
* Version used (`minio --version`):
mc --version
mc version RELEASE.2024-07-03T20-17-25Z (commit-id=d6ff97012549bfd91396447249297411ccfc79a7)
Runtime: go1.22.5 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

* Server setup and configuration:
* Operating System and version (`uname -a`):
uname -a
Linux ilm 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
The markdown must be updated to use `ExpiredDeleteMarker` 

```json
{
 "Rules": [
  {
   "Expiration": {
    "ExpiredObjectDeleteMarker": true
   },
   "ID": "cq682uscno5ug7pcgvug",
   "Status": "Enabled"
  }
 ]
}
```

**Comment by allanrogerr** [comment]
Fixing this in the docs.
