### ISSUE TITLE
Minio custom metadata not preserved during minio client mirror

### ISSUE THREAD

**Issue by Vasile27** [minio/minio#20068]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I have a Minio pod in Kubernetes.
I have tar objects stored in Minio. The objects have custom metadata: 
```
  X-Amz-Meta-Family      : A
  X-Amz-Meta-Image-Type  : B
  X-Amz-Meta-Release-Type: [{"C":"D","E":"F"}}]
```
 I mirror them to a local drive (is has Ubuntui installed).
I then mirror the tar objects back to Minio. The objects do not have the custom metadata anymore.

## Expected Behavior

I would expect the mc mirror to preserve the custom metadata.

## Current Behavior

The custom metadata is not preserved during mirror.

## Steps to Reproduce (for bugs)

1. Have a tar object stored in Minio with custom metadata information
2. Use mc mirror to mirror the tar object to a local path.
3. Remove the tar object from Minio
4. Use mc mirror to mirror back the tar object to Minio

## Context

I am storing tar objects in Minio. This tar objects have custom metadata. I am trying to migrate Minio from Gateway.
I am mirroring the tar objects to a local drive. I am upgrading Minio and then I want to mirror back the tar objects to the new upgraded Minio. At the moment I am trying the mc mirror backup and restore with the new Minio version that does not use the old Gateway or Filesystem mode.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-04-18T19-09-19Z (commit-id=98f7821eb3f60a6ece3125348a121a1238d02159)
* Server setup and configuration: Kubernetes
* Operating System and version (`uname -a`): Linux 5.15.0-107-generic #117~20.04.1-Ubuntu
* MC version: RELEASE.2024-03-30T15-29-52Z (commit-id=9f8147bf0e037730077a1b3baef25e53181099b0)

**Comment by klauspost** [comment]
Mirroring to local drives loses all metadata. At that point it is just files on a disk.

Do the mirror S3 -> S3.
