### ISSUE TITLE
Recommended client for Windows with GUI?

### ISSUE THREAD

**Issue by arjitc** [minio/minio#2006]
Hello,
Just wondering if there was any recommended client for Windows with a GUI. CyberDuck seems to not allow changing the port from 443 for their S3 profile :(

Thanks!

**Comment by krishnasrinivas** [comment]
@arjitc web-browser interface is not ok for you? https://localhost:9000/minio

**Comment by arjitc** [comment]
Drag and drop support would be nice to have :+1:

**Comment by harshavardhana** [comment]
> Drag and drop support would be nice to have

https://github.com/minio/minio/issues/2049 - closing this.

**Comment by dkocher** [comment]
Please install the [generic S3 profile](https://trac.cyberduck.io/wiki/help/en/howto/s3#HTTPS) for Cyberduck.
