### ISSUE TITLE
MinIO console access restriction

### ISSUE THREAD

**Issue by AntonKun** [minio/minio#20060]
I have deployed MinIO on my server and configured two URLs for access:

1. `minio.example.com` - MinIO API
2. `minio-admin.example.com` - MinIO Console (UI)

I have set policies for my buckets (readonly policy for `/` path ):
![image](https://github.com/minio/minio/assets/59668952/adb258e3-a7f5-43a0-9b3c-d1958e1a0f4b)
...and everything works as expected for the MinIO API URL. However, when accessing the MinIO Console URL, I can see the entire structure of my buckets and all files without any authentication.

When accessing `minio.example.com/browser/my-bucket`, I get the following error message (what I want to achieve for the second URL as well):

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>test</Key>
<BucketName>browser</BucketName>
<Resource>/browser/my-bucket</Resource>
<RequestId>17E051413F91E8A2</RequestId>
<HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId>
</Error>
```

However, when accessing `minio-admin.example.com/browser/my-bucket`, I can see the complete list of all files and directories in my bucket without any authentication:
![image](https://github.com/minio/minio/assets/59668952/e45887dd-7d66-4110-b4d0-4617850a8dff)

Is there any way to achieve the same result for the second URL (`minio-admin.example.com` - MinIO Console (UI)) as for the first (`minio.example.com` - MinIO API)? That is, I want users to have anonymous access only to those files to which they have a **full link** (e.g. `minio-admin.example.com/browser/my-bucket/my-file`)

I can set basic auth for second URL in my proxy, but I don't really like this option. Maybe there are other ways?

**Comment by harshavardhana** [comment]
> I can set basic auth for second URL in my proxy, but I don't really like this option. Maybe there are other ways?

No you cannot, no there is no other way. the way its behaving is correct. You cannot add `/browser` to your API endpoint and expect a UI to show up. That UI will be only visible at `minio-admin.example.com`

**Comment by AntonKun** [comment]
@harshavardhana you don't get the point of my issue. I don't want to see UI at `minio.example.com`.

I want to close unauthorised access to bucket structure at `minio-admin.example.com`. Only files should be accessible by full link (with file name in it).

**Comment by harshavardhana** [comment]
> @harshavardhana you don't get the point of my issue. I don't want to see UI at `minio.example.com`.
> 
> I want to close unauthorised access to bucket structure at `minio-admin.example.com`. Only files should be accessible by full link (with file name in it).

For that you have to do it outside of MinIO we cannot restrict someone visiting the domain via policies.

**Comment by harshavardhana** [comment]
anonymous read-only provides "list" access by default, you should come up with a policy for anonymous users where they directly download via link you need to write your own policy `mc anonymous set-json`

**Comment by AntonKun** [comment]
@harshavardhana yes, that's it! `mc anonymous set-json` works well. Thanks.
