### ISSUE TITLE
Bucket Replicate: support breakpoint resume

### ISSUE THREAD

**Issue by mymeatball** [minio/minio#20071]
**Is your feature request related to a problem? Please describe.**
    Between my two MinIO clusters apply Bucket Replication usually failed when MinIO replicating large objects.
    The part of reason , because of the two clusters deployment in difference IDC. You can think that one cluster is deployed on AWS and  other cluster deployed on GCP. So, i cant guarantee the bandwidth is sufficient between the two IDC. The bandwidth about 100~200Mb/s.
    1.when enable mutipart upload feature. the timeout is 3600s.
    2.when disable multipart upload feature. the timeout is 600s.
    Due to above two reasons. Bucket Replication will occur problem when replicate large object (abuot large than 20GB).
    Sometimes, the network quality is not good, will occur response 400 when Bucket Replicate.

    Although Minio attempts to replicate failed objects, but each copy starts from scratch. 

    So , need to breakpoint resume feature when Bucket Replicate. Even without sufficient bandwidth and good network quality, synchronization can still be successful

**Describe the solution you'd like**
   Support breakpoint resume when Bucket Replicate.

**Describe alternatives you've considered**
   Can modify the timeout config when disable or enable multipart upload feature. Large object have sufficient long time to replicate.
   Currently, these configurations should be hard coded. I cant modify these timout's  config.

**Additional context**
The dedicated line bandwidth about 10000$/month, so I think i cant infinitely expand the bandwidth for replicate large object (like 1TB even large than 1TB).

**Comment by harshavardhana** [comment]
This will be fixed to some extent by #20077

**Comment by mymeatball** [comment]
> This will be fixed to some extent by #20077


Thats greate. Thank you.

Can i get more details about this PR? 
1. Whats problem will been resolved in this PR? Is it about response code 400?
2. This PR whether resolve timeout problem? Can i exceed 3600s limit for Bucket Replication? For example, the timeout is 3600s when enable mutipart upload feature and the timeout is 600s when disable multipart upload feature. 
3. Whats version of Minio will released this feature? Do I need to configure the number of workers in use for Bucket Replication？

If this PR fixed in one of MinIO's version, please let me know. I will upgrade MinIO‘s version as soon as possible. Thank you very much.

**Comment by harshavardhana** [comment]
> Can i get more details about this PR?
> 
> 1. Whats problem will been resolved in this PR? Is it about response code 400?
> 2. This PR whether resolve timeout problem? Can i exceed 3600s limit for Bucket Replication? For example, the timeout is 3600s when enable mutipart upload feature and the timeout is 600s when disable multipart upload feature.
> 3. Whats version of Minio will released this feature? Do I need to configure the number of workers in use for Bucket Replication？

The problem resolved in the PR is to support shoddy networks.

**Comment by harshavardhana** [comment]
Resuming is impossible in AWS S3 API on individual objects, replication doesn't replicate already replicated content anyway. 

The PR https://github.com/minio/minio/pull/20077 makes the connection handling and throttling a bit more robust that all changes to expectations and slows itself down appropriately.
