### ISSUE TITLE
PID file for minio server

### ISSUE THREAD

**Issue by AndreC10002** [minio/minio#20085]
Hi,
This was discussed on #4605 but after so many years, I'd like to bring it back for consideration.

Every daemon I can think of creates a pid file upon execution. This standard behavior is specially important for monitoring purposes. A script can be built to monitor based on ps output, but that isn't as reliable as monitoring a pid file and verifying the process id written to it is running.

**Describe the solution you'd like**
Create a pid file on execution and delete it on shutdown. Make the pid file path configurable via command line.

**Comment by harshavardhana** [comment]
@AndreC10002 no we are not considering that kind of a design sorry.

**Comment by AndreC10002** [comment]
May I please get an explanation of why you are not considering it?
It seems contrary to good system administration practices and *nix tradition. In production environments, we need a way to monitor that Minio is running.
Would appreciate if you could please elaborate.
Thank you for your attention with this matter and prompt response.

**Comment by harshavardhana** [comment]
> May I please get an explanation of why you are not considering it? It seems contrary to good system administration practices and *nix tradition. In production environments, we need a way to monitor that Minio is running. Would appreciate if you could please elaborate. Thank you for your attention with this matter and prompt response.

To monitor if MinIO is running or not you have healthcheck endpoints use them.

Use `mc ready` to look for readiness of the system deployed.

PID approach on the other hand is nothing but a duplicate data saved elsewhere with no other purpose to it, adding to that it's a headache for us to manage it.

If you insist on PID for some weird reason, go write a script around MinIO - we are not going to implement it.
