### ISSUE TITLE
Bucket size updating

### ISSUE THREAD

**Issue by ampminfo** [minio/minio#20096]
When visualizing the buckets sizes, I could see the fist bucket size increasing almost in real time but the second one always stayed at the same size. Could not get it updated after multiple days after uploading almost 5 TB of data to the second one.

## Expected Behavior
See all buckets size being updated like the first one that was almost instantly. 

Fist bucket is versionned and lock is active
Second is by default with no lock

## Current Behavior
![image](https://github.com/user-attachments/assets/49e52ffc-ca3f-4ecf-9365-9b79f6209435)

## Your Environment
Windows server 2019
Minio for Windows latest built available at that time (2024-06-xx)
Veeam backup and replication 12

**Comment by harshavardhana** [comment]
> When visualizing the buckets sizes, I could see the fist bucket size increasing almost in real time but the second one always stayed at the same size. Could not get it updated after multiple days after uploading almost 5 TB of data to the second one.

It is never going to be real-time, it feels because that's the bucket it picked while you were writing to the other. 

The behavior is normal, next cycle it uses a different bucket to scan.

**Comment by ampminfo** [comment]
the first one is close to real when monitoring.  One week later I do not see any update on the second one

**Comment by harshavardhana** [comment]
> the first one is close to real when monitoring. One week later I do not see any update on the second one

It means that the first one that got started is not complete observe these two to see what it is doing to get more insights. 

```
mc admin trace --call scanner alias/
```

```
mc admin scanner status alias/
```

**Comment by harshavardhana** [comment]
> Minio for Windows latest built available at that time (2024-06-xx)

Also, Windows is experimental; if you deploy and see issues, expect issues. Always upgrade before you report issues 
RELEASE.2024-07-13T01-46-15Z is latest.

**Comment by ampminfo** [comment]
I know but can't stop to update it right now
