### ISSUE TITLE
health checks, multipart uploads, and retries, when Minio node cycles

### ISSUE THREAD

**Issue by justinfx** [minio/minio#20091]
## Description
I've observed an issue when performing a rolling update to my production Minio cluster, where client uploads ended up seeing request failures, while I had assumed the update would be transparent and fault tolerant. So I then reduced my test case to a smaller configuration.

I have the following simplified setup:

1. 3 node minio cluster
2. Minio sidekick loadbalancer pointing at minio cluster, using `/minio/healthy/ready` check
3. `mc` client performing an `mc cp` command, in a loop, pointing at sidekick instance

With the `mc` performing a copy of a 30MB file in a loop, I cycle one of the minio nodes to simulate a rolling update. The goal is to have uninterrupted copy operations on the client, as sidekick detects and removes a down node, and adds it back later when healthy. 

## Expected Behavior
I would expect to see sidekick respond to the minio node going down. But I would not expect to see any failed requests occurring on the client side during object uploads. I would expect the client retries to handle any temporary failure before becoming fatal to the caller.
I expect to be able to slowly roll nodes in a minio cluster without causing fatal errors to clients.

I would hope to not have to write special error and retry handling in each of our clients, to deal with transient request failures.

## Current Behavior
Sidekick logs "502 Bad Gateway" when minio node goes down. This might be considered expected. 

After bringing the minio node back up, I will see request errors on the Minio node, using `mc admin trace`:

```
[REQUEST s3.CompleteMultipartUpload] [2024-07-12T17:27:49.900] [Client IP: X.X.X.X]
POST /path/key?uploadId=M2Y4MGY3MzMtZWRjMS00YTQ1LWFkZmItNWIxNjY3ZmQwZWVhLjU1NzM3MjA0LTI1YzAtNGVhYy04ZGZiLWI1MWM3MTM1ODljOQ
Proto: HTTP/1.1
Host: <host>:9010
X-Real-Ip: X.X.X.X
Authorization: <...>
Content-Length: 267
Content-Type: application/octet-stream
X-Forwarded-For: X.X.X.X, X.X.X.X
X-Forwarded-Host: <host>:9010
Accept-Encoding: zstd,gzip
User-Agent: MinIO (linux; amd64) minio-go/v7.0.73 mc/DEVELOPMENT.GOGET
X-Amz-Content-Sha256: 7315c823224b844add1645658a85fc4b5a832930a7ef58a19e6f2531f3604785
X-Amz-Date: 20240712T052749Z
<CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Part><PartNumber>1</PartNumber><ETag>e637d8911e1566418c2d050952051467</ETag></Part><Part><PartNumber>2</PartNumber><ETag>0e27318879caf674aab5c2e35b979b85</ETag></Part></CompleteMultipartUpload>

[RESPONSE] [2024-07-12T17:27:49.902] [ Duration 1.699ms TTFB 1.688781ms ↑ 416 B  ↓ 465 B ]
400 Bad Request
Content-Type: application/xml
Server: MinIO
Vary: Origin,Accept-Encoding
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Content-Length: 465
X-Amz-Request-Id: 17E15FFC4F62F55B
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Amz-Id-2: 2de226a8c93748c02709a9643005ddcbb6b35f079c2973a359b7d7309028e074
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part&#39;s entity tag.</Message><Key>key</Key><BucketName>path</BucketName><Resource>/path/key</Resource><RequestId>17E15FFC4F62F55B</RequestId><HostId>2de226a8c93748c02709a9643005ddcbb6b35f079c2973a359b7d7309028e074</HostId></Error>
```

On the client, I get the same fatal failure propagated back. There does not seem to be any form of a retry for the temporary failure. And I can't tell if the failure is caused by the upload being inflight when the server goes down, or the health check on sidekick green-lighting too soon and causing a bad request to start on the node after it is immediately back online.

## Possible Solution
I've done further investigations via the Go SDK and narrowed it down to multipart uploads. The client switches to multipart upload when the object size is greater than 16MB. When I disable multipart, to seems to mitigate the failure when cycling the minio node.  I am not sure if multipart transfers have proper transient failure handling in the clients. The retry logic in `minio/minio-go` suggest a 400 is not something that is retried automatically.

I've also added more extensive error handling on the client to check for codes like 400 InvalidPart, 404 NoSuchUpload, and 503 SlowDownRead, and a set of retries for those errors that can happen when retrying multipart requests. I'm not sure if end users should have to be doing this or if it should be part of the client, or if it should not happen at all in the first place. 

## Steps to Reproduce (for bugs)
Here is a link to the Go SDK code I have used to test workarounds: https://pastebin.com/L6azFF4P

You will see there are controls for whether multipart should be disabled, and the request size.

1. Start 3 minio nodes
2. Start sidekick
3. Use either:
   1. my test code: `go run test_code.go`
   2. mc cp <30mb.file> minio bucket
5. Alternate between killing one of the minio nodes, and bringing it back up again, and observe client-side errors

## Context
We are releasing a new production stack that uses Minio as a backend storage. it is important for me to be confident that cycling any one Minio node will not cause request failures at the frontend of the application. I want to achieve proper redundancy and I am not sure if I have to implement more custom error and retry handling in each client (we use Go, Python, and C++).

## Regression
No

## Your Environment
* Minio server: docker minio/minio Version: RELEASE.2024-02-26T09-33-48Z (go1.21.7 linux/amd64) with host networking
* Minio sidekick: docker quay.io/minio/sidekick:v7.0.0
* `mc` latest version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
* Go SDK: github.com/minio/minio-go/v7 v7.0.73

**Comment by justinfx** [comment]
I've also tested with `minio/minio:RELEASE.2024-07-13T01-46-15Z` and am able to reproduce the "400 InvalidPart" error when multipart is enabled.

**Comment by harshavardhana** [comment]
@justinfx you need to add sidekick to use /minio/health/cluster for health-path can you use that and try?

We will look at the reproducer

**Comment by justinfx** [comment]
> @justinfx you need to add sidekick to use /minio/health/cluster for health-path can you use that and try?
> 

Oh really? I didn't think to try that because I figured it was a single health value for the entire cluster and not specific to each node. Wouldn't that continue to try routing to a down minio node since the cluster still has write quorum with the other 2?

**Comment by harshavardhana** [comment]
> Oh really? I didn't think to try that because I figured it was a single health value for the entire cluster and not specific to each node. Wouldn't that continue to try routing to a down minio node since the cluster still has write quorum with the other 2?

No, it is the health of the cluster from every node's point of view because there is always a possibility of network partitions, etc.

**Comment by justinfx** [comment]
I've tested sidekick using the /minio/health/cluster endpoint, and it seems to work at least as well as the ready endpoint, in that it doesn't prevent the client failures from happening when multipart is enabled. My best solution for the meantime does seem to be to disable multipart entirely. I'll do that for now, and hope some new information comes out of your attempts to repro the situation. Thanks!

**Comment by harshavardhana** [comment]
> I've tested sidekick using the /minio/health/cluster endpoint, and it seems to work at least as well as the ready endpoint, in that it doesn't prevent the client failures from happening when multipart is enabled. My best solution for the meantime does seem to be to disable multipart entirely. I'll do that for now, and hope some new information comes out of your attempts to repro the situation. Thanks!

yeah this looks like `minio-go` is not able to understand that the remote site is going down

**Comment by harshavardhana** [comment]
ping @allanrogerr

**Comment by allanrogerr** [comment]
Reviewing

**Comment by allanrogerr** [comment]
I used your reproducer and observed logs similar to:
```
400 InvalidPart: (5: try #0): One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
```

Im still reviewing; with the team now.

**Comment by allanrogerr** [comment]
This does not seem supported. See related code to https://github.com/minio/minio-go/blob/master/api-put-object.go#L282

**Comment by justinfx** [comment]
Thanks for reviewing this, @allanrogerr. Do you have an opinion on whether this situation is clear enough when it comes to being able to reliably cycle minio nodes without breaking clients? There is internal retry logic, but that doesn't seem to handle a broken multipart upload, so the client will directly see the failure. In my case, it was a bit obscure to understand the behaviour until I worked around it by entirely disabling multipart. Since I did that, the clients no longer fail during restarts of minio nodes, as the retry happens transparently.

**Comment by allanrogerr** [comment]
It is clear. We are reviewing how to handle this case. Im glad that, for now, disabling multipart works for you.

**Comment by allanrogerr** [comment]
@justinfx When you say 
> Alternate between killing one of the minio nodes, and bringing it back up again, and observe client-side errors

Could you provide a sample of the code please? Do you ensure that minio has quorum before attempting to begin a new upload?

**Comment by justinfx** [comment]
I can provide a code sample, but honestly it is just a bash for loop calling "mc cp" over and over. There is no smarts. The expectation is that we are going through minio sidekick as a single endpoint, with the cluster health check, which is meant to load balance to healthy minio nodes. So it would be ideal to not see the mc command fail at any point from the multipart error, if it were being retried from the start.

**Comment by allanrogerr** [comment]
Load balancing will happen if the cluster is healthy enough to load balance to. If there are enough nodes down, then the cluster will lose write quorum and become unhealthy and inaccessible. Try running `mc ready <alias>` which will block until the cluster achieves write quorum.

We're still looking into the issue. I was able to reproduce your observation.

**Comment by justinfx** [comment]
I appreciate the suggestion. But I don't think I will investigate that
approach, because it suggests that every single copy operation should first
do a ready check first to see if the cluster has write quorum. I wouldn't
want to put any time into making every client aware of these checks, and to
have extra retry handling, until we confirm whether the minio client should
be able to do it transparently.
Thanks for looking at this! Really appreciate your time so far.

**Comment by harshavardhana** [comment]
I found a comprehensive change to handle this.

**Comment by justinfx** [comment]
Fantastic! @harshavardhana thanks so much for putting the time into a fix. If I understand the changes, it both handles the cleanup of failed parts as well as making multipart failures automatically retriable, right?

Looking forward to the next tag.
