### ISSUE TITLE
Add Apache Arrow output format to S3 Select

### ISSUE THREAD

**Issue by danepitkin** [minio/minio#20103]
S3 Select currently supports CSV and JSON output. For large analytical data sets stored as parquet files, the serialization/deserialization cost is high. Apache Arrow as an output format can provide much better performance for this use case.

**Comment by harshavardhana** [comment]
We implement whatever AWS S3 implements, S3Select is a complex piece with relatively small adoption. We have no interest in expanding its scope unless we see a good opportunity to make it more widely usable.

Right now the incentives are not aligned, so this is not going to be worked on. Thanks for your interest.
