### ISSUE TITLE
tests: unit tests for erasure-readfile.go

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2010]
add unit tests for:

isSuccessDecodeBlocks()
isSuccessDataBlocks()
getOrderedDisks()
getReadDisks()
parallelRead()
erasureReadFile()

**Comment by GarimaKapoor** [comment]
Please update the timeline to fix this issue.

**Comment by krishnasrinivas** [comment]
timeline 4-july.

**Comment by GarimaKapoor** [comment]
please update the revised timeline.

**Comment by harshavardhana** [comment]
Fixed by #2229
