### ISSUE TITLE
Add possibility to deploy initContainers via the values.yaml

### ISSUE THREAD

**Issue by cgiangreco** [minio/minio#20107]
The helm chart currently only allows to deploy sidecar containers using the "extraContainers" array. Adding initContainers using it is not possible.
Currently, the only way to add initContainers to the deployment would be to use a custom, extended deployment.yaml file.
It would be nice if, instead, this functionality would already come out of the box from the MinIO Helm Chart, as having the possibility to add initContainers to a deployment can be useful for a number of tasks.

**Comment by harshavardhana** [comment]
Please use our operator deployment, the current helm chart is done from our end. 

If you want extended functionality feel free to work on it yourself and send PR.
