### ISSUE TITLE
[iam/ldap] User AccessKeys stop works after short period of time for special character UserDNs

### ISSUE THREAD

**Issue by redtex** [minio/minio#20112]
## Environment
Minio version - 2024-07-15T19:02:30Z
Clean minio install
MinIO for Authentication using Active Directory / LDAP (Win2012) configured

## Expected Behavior
User accesskey grant access to S3 bucket until it expires or user has been disabled

## Current Behavior
After accesskey creation in minio console UI, accesskey works as expected a short period of time - approximately in 30 minutes, accesskey stop working - when user try to connect with it, got 'Access disabled'

Problem persists only with CN, in which present national (non-ASCII) characters.

## Steps to Reproduce (for bugs)
I have two LDAP users:
* test.m
* tešt.r

Both create accesskeys. User test.m has no problems, user tešt.r exactly what I have described.

Output of `mc idp ldap accesskey ls ALIAS`:
<pre>
mc: <ERROR> Unable to retrieve access keys for user 'cn=te\c5\a1t.r,cn=Users,dc=sdsys,dc=local'. The specified user does not exist. (Specified user does not exist)
DN cn=test.m,cn=Users,dc=sdsys,dc=local
  STS Access Keys:
    PXTU6U3DK5LJS2L4PGIZ
  Service Account Access Keys:
    LGXtt3qDErbyLBUxQPsZ
</pre>

## Regression
Is this issue a regression? - Yes. Older versions of minio - I have `2024-02-04T22:36:13Z` - not suffer from such user names.

**Comment by redtex** [comment]
when I try to make `ldapsearch -b 'cn=te\c5\a1t.r,cn=Users,dc=sdsys,dc=local'`  have same result:

<pre>
# extended LDIF
#
# LDAPv3
# base <cn=te\c5\a1t.r,cn=Users,dc=sdsys,dc=local> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# search result
search: 2
result: 32 No such object
matchedDN: CN=Users,DC=sdsys,DC=local
text: 0000208D: NameErr: DSID-03100217, problem 2001 (NO_OBJECT), data 0, bes
 t match of:
	'CN=Users,DC=sdsys,DC=local'
</pre>


but with `ldapsearch -b "cn=Users,dc=sdsys,dc=local" "(&(objectClass=user)(cn=te\c5\a1t.r))"` it's ok:
<pre>
# extended LDIF
#
# LDAPv3
# base <CN=Users,DC=sdsys,DC=local> with scope subtree
# filter: (&(objectClass=user)(cn=te\c5\a1t.r))
# requesting: ALL
#

# te\C5\A1t.r, Users, sdsys.local
dn:: Q049dGXFoXQucixDTj1Vc2VycyxEQz1zZHN5cyxEQz1sb2NhbA==
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn:: dGXFoXQucg==
givenName:: dGXFoXQucg==
distinguishedName:: Q049dGXFoXQucixDTj1Vc2VycyxEQz1zZHN5cyxEQz1sb2NhbA==
....
....
</pre>

**Comment by harshavardhana** [comment]
Looks like we brought back regression with decodedn changes @taran-p @donatello

**Comment by harshavardhana** [comment]
@redtex can you test with `RELEASE.2024-07-10T18-41-49Z` ?

**Comment by harshavardhana** [comment]
and is MinIO running on Windows or Linux?

**Comment by redtex** [comment]
> @redtex can you test with `RELEASE.2024-07-10T18-41-49Z` ?

Yes. Done:
- deleted all accesskeys
- deployed RELEASE.2024-07-10T18-41-49Z
- created new accesskeys for test.m and tešt.r
- same errors, absolutely

It's Linux. Official k8s helm - operator+tenant 5.0.15 with mentioned images.

**Comment by taran-p** [comment]
@redtex A few more things:

- Could you check the output for `mc idp ldap accesskey ls ALIAS 'cn=tešt.r,cn=Users,dc=sdsys,dc=local'`
- What is `user_dn_search_filter` in your LDAP config
- What is the output when trying `mc alias` with the non-functional access key?
- How many nodes/drives in your setup?

**Comment by redtex** [comment]
Updated to RELEASE.2024-07-16T23-46-41Z

> * Could you check the output for `mc idp ldap accesskey ls ALIAS 'cn=tešt.r,cn=Users,dc=sdsys,dc=local'`. 

No error:
<pre>
DN cn=tešt.r,cn=Users,dc=sdsys,dc=local
  Service Account Access Keys:
    h7WTFZe1eSp20qTaxQi6
</pre>

> * What is `user_dn_search_filter` in your LDAP config

`MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER='(&(objectCategory=user)(sAMAccountName=%s))'`

> * What is the output when trying `mc alias` with the non-functional access key?

<pre>
mc alias set test-r https://s3.... h7WTFZe1eSp20qTaxQi6 'd.....5'
mc ls test-r
mc: <ERROR> Unable to list folder. Access Denied.
</pre>

> * How many nodes/drives in your setup?

3 nodes, 2 drives on each node

**Comment by harshavardhana** [comment]
can you tar up your backend drives on each node both drives at `/backend_mount/.minio.sys/config/iam` and attach it here? 

Does re-attaching policy work? or does it never work?

**Comment by redtex** [comment]
sorry for long answer. I've re-create my minio tenant with identical settings, as before. Only access keys changed.
@harshavardhana 
[exp0-0.tar.gz](https://github.com/user-attachments/files/16349429/exp0-0.tar.gz)
[exp0-1.tar.gz](https://github.com/user-attachments/files/16349430/exp0-1.tar.gz)
[exp1-0.tar.gz](https://github.com/user-attachments/files/16349431/exp1-0.tar.gz)
[exp1-1.tar.gz](https://github.com/user-attachments/files/16349432/exp1-1.tar.gz)
[exp2-0.tar.gz](https://github.com/user-attachments/files/16349433/exp2-0.tar.gz)
[exp2-1.tar.gz](https://github.com/user-attachments/files/16349434/exp2-1.tar.gz)
attached required files
Policies work as expected, even for both users - with and without special characters

**Comment by harshavardhana** [comment]
So only access keys created for these users stop working? @redtex

**Comment by redtex** [comment]
> So only access keys created for these users stop working? @redtex

Correct. Only access key for user ```tešt.r``` stops working. Anything else - ok.

**Comment by harshavardhana** [comment]
@donatello @taran-p can we look at this again - it looks like the policy lookup issue again that was considered fixed and we have CI tests on these as well.

@redtex to confirm you enable policy directly on the user not it's group right? And these generated credentials have no other inline policy?

**Comment by harshavardhana** [comment]
And how long does it take for it to move from working to non working? Or does it never work?

**Comment by taran-p** [comment]
I've reproduced the issue. We're searching using the internal normalized DN when periodically updating LDAP group memberships. Working on a fix.
@harshavardhana

**Comment by redtex** [comment]
@harshavardhana formally, for this issue - it's ok, problem resolved - access key works. But command ```mc idp ldap accesskey ls <ALIAS>``` still complains: ```The specified user does not exist.```
Should I open new issue, or re-open this ?

**Comment by harshavardhana** [comment]
> @harshavardhana formally, for this issue - it's ok, problem resolved - access key works. But command `mc idp ldap accesskey ls <ALIAS>` still complains: `The specified user does not exist.` Should I open new issue, or re-open this ?

A new one please.
