### ISSUE TITLE
Instead of DirectPV, why not develop a CSI Driver that can connect to minio storage like the s3 CSI Driver?

### ISSUE THREAD

**Issue by Bokki-Ryu** [minio/minio#20111]
**Is your feature request related to a problem? Please describe.**

`to connect a minio to a k8s and use it as storage, the only way to do it is with directPV.`

**Describe the solution you'd like**

`The goal is to create a CSI driver that can connect K8S and MINIO storage.`

**Describe alternatives you've considered**

**Additional context**

**Comment by balamurugana** [comment]
DirectPV is storage space provider to MinIO server or any software requires direct access to local drives. If you want to access MinIO server through some CSI driver, you are free to do

**Comment by Bokki-Ryu** [comment]
@balamurugana 

> DirectPV is storage space provider to MinIO server or any software requires direct access to local drives. If you want to access MinIO server through some CSI driver, you are free to do

I understand what you're saying. If I were to install Minio Operator and Minio Tenant using Helm, how about making it possible to connect Minio Tenant's Bucket through the CSI Driver and StorageClass provided by Minio, similar to how JuiceFS works?

**Comment by balamurugana** [comment]
There is no such CSI driver we provide

**Comment by harshavardhana** [comment]
> I understand what you're saying. If I were to install Minio Operator and Minio Tenant using Helm, how about making it possible to connect Minio Tenant's Bucket through the CSI Driver and StorageClass provided by Minio, similar to how JuiceFS works?

We do not provide such things, you can use https://github.com/awslabs/mountpoint-s3-csi-driver

**Comment by Bokki-Ryu** [comment]
@harshavardhana 

> We do not provide such things, you can use https://github.com/awslabs/mountpoint-s3-csi-driver

are there any plans to add it?

**Comment by harshavardhana** [comment]
> are there any plans to add it?

No @bkkoli

**Comment by Bokki-Ryu** [comment]
@harshavardhana 

thank you for kindness👍
