### ISSUE TITLE
The folder has turned into a file with Content-Type application/octet-stream.

### ISSUE THREAD

**Issue by ndy2** [minio/minio#20116]
## Expected Behavior
A folder should be a folder.

## Current Behavior
The folder has turned into a file with Content-Type application/octet-stream.

<img src="https://github.com/user-attachments/assets/62fc5149-10e1-46c0-b2b7-7004a1b624e6" width="300">
<img src="https://github.com/user-attachments/assets/98dd9a33-babb-4339-9b8b-2c3d4e0f3fb1" width="300">

As shown in above image the folder in bucket `fr-data` named `official` is treated as a file when search the bucket `/fr-data`.
But it was a folder and still is a folder, since i can `ls` inside the folder wint `mc ls fr-data/official/` command.

Fortunately, the data inside of the `fr-data/official` path are not removed 

## Possible Solution
`mc admin heal` does not helped.

## Steps to Reproduce (for bugs)
I didn't do special job. at the time of `last modified at` of that file.  (Thu, Jul 18 2024:09:46)
I don't know how to reproduce it...

## Regression
No

## Your Environment
deployed in kubernetes 1.26.15
minio-operater: 5.0.11
minio-tenant: 5.0.11
minio:  `RELEASE.2023-11-15T20-43-25Z`

**Comment by harshavardhana** [comment]
yeah that is because you are wrongly creating conflicting objects 

https://min.io/docs/minio/linux/operations/concepts/thresholds.html

```
PUT data/invoices/2024/january/vendors.csv
PUT data/invoices/2024/january <- collides with an existing object prefix
```

```
PUT data/invoices/2024/january
PUT data/invoices/2024/january/vendors.csv <- collides with an existing object
```

you need to fix your application to not do that.

**Comment by ndy2** [comment]
@harshavardhana.
Thank you for quick response!
