### ISSUE TITLE
feat: Reconnect OpenID configuration at startup, if fails

### ISSUE THREAD

**Issue by septatrix** [minio/minio#20118]
## Expected Behavior
Minio should fetch the OpenID configuration and (in case of an error) should occasionally refetch such configuration

## Current Behavior
When Minio in unable to initialize OpenID upon startup it just gives up and never makes an attempt to fetch the config at a later time.

## Possible Solution
Minio should attempt to fetch the OpenID config at a later time, e.g. every 5 minutes, until it gets a valid response.

## Steps to Reproduce (for bugs)
1. Set up an OpenID provider, e.g. Keycloak, Authentik, or oidc-server-mock
2. Configure Minio to use the OpenID provider with environment variables (i.e. `MINIO_IDENTITY_OPENID_CONFIG_URL` et al)
3. Stop the OpenID provider (to simulate a temporary connectivity error)
4. Start Minio
5. Open the Minio console and confirm that OpenID login is not available
6. Restart the OpenID provider
7. Wait a bit
8. Refresh the Minio console
9. OpenID login is still not available

## Context
This has mostly occurred when both, Minio and our OpenID provider, were restarted at the same time due to updates of the underlying host, containerd, or rolling out several container updates at the same time. In this case Minio starts up before our OpenID provider and fails to obtain the OpenID config.

## Regression
Not that I know of. We have observed this multiple times now since setting up OpenID login.

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2024-06-13T22-53-53Z (commit-id=20960b6a2ddb9594ee418035b3c7c7fe92ae6a12)`
* Server setup and configuration: Docker compose
* Operating System and version (`uname -a`): `Linux aa2e5237-c6de-466c-aff0-a3923e0af7a2 6.1.0-21-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
We cannot do that because we have no way to reestablish things and keep it safe.

It needs to be initialized atleast once during the startup.

IDP is a fundamental entity like KMS we cannot hope for it to come back online in the future.

We reconnect fine once it's properly initialized at startup.

You have to make sure that the IDP is reachable during server startup.

We can make a change where if IDP is configured it keeps retrying for sometime, somehow and makes it work but this will affect your overall startup time and service availability.

We prefer that you have service order where in MinIO must be restarted or updates only after IDP is updated and available.

**Comment by septatrix** [comment]
> We cannot do that because we have no way to reestablish things and keep it safe.

Where lies the safety problem with performing retries until a configuration has been successfully fetched?

> IDP is a fundamental entity like KMS we cannot hope for it to come back online in the future.

I understand that this should not be blocking as Minio first and foremost needs to continue starting but it should be fine to do this in the background?

> You have to make sure that the IDP is reachable during server startup.
> We prefer that you have service order where in MinIO must be restarted or updates only after IDP is updated and available.

We too would prefer to have 100% uptime on our IDP but that is simply not realistic. And with Minio and our IDP on different hosts there is no way we can declare any dependency

**Comment by harshavardhana** [comment]
> Where lies the safety problem with performing retries until a configuration has been successfully fetched?
> 
> >

Safety is that when should the service be up? how long should we wait? and who tells us that? should we just wait forever? 

> I understand that this should not be blocking as Minio first and foremost needs to continue starting but it should be fine to do this in the background?
> 
> >

how would I serve requests when IDP is unreachable? - how do I authenticate and authorize requests for its validity?

**Comment by harshavardhana** [comment]
We have to write software to handle various use cases - we simply have to expect some cadence here. Everyone thinks that their use-case is the right one. 

IDP is a fundamental piece, just like KMS (encryption). If you don't have it available, we can't authenticate/authorize. Its as simple as that.

If we make the service available and serve requests incorrectly, it's a bigger disaster than quite simply having a cadence of services managed properly.

If they happen, IDP updates must also not be done in parallel with MinIO updates. MinIO updates can wait until IDP updates are complete. Then you proceed to update MinIO - this is not hard at all.

**Comment by septatrix** [comment]
> > Where lies the safety problem with performing retries until a configuration has been successfully fetched?
> 
> Safety is that when should the service be up? how long should we wait? and who tells us that? should we just wait forever?

As I said it can just be fetched in the background without delaying startup.

> > I understand that this should not be blocking as Minio first and foremost needs to continue starting but it should be fine to do this in the background?
> > >
> 
> how would I serve requests when IDP is unreachable? - how do I authenticate and authorize requests for its validity?

The same way it is currently handled? At the moment Minio just ignores the OpenID login (forever) and still allows logging in with username+password as well as API access via access tokens. The change I would like to see is that after a while the OpenID login would become available instead of never being retried.

> IDP is a fundamental piece, just like KMS (encryption). If you don't have it available, we can't authenticate/authorize. Its as simple as that.

But that is not what currently happens. Without OpenID Minio still allows logging in via other means. What I propose would only change that after a few minutes OpenID too would become available. This does not reduce the security or impact the available compared to the current state.

> If we make the service available and serve requests incorrectly, it's a bigger disaster than quite simply having a cadence of services managed properly.

How would this cause Minio to serve requests incorrectly?

**Comment by harshavardhana** [comment]
Great suggestions, lets see a PR @septatrix

**Comment by mircea-pavel-anton** [comment]
I will chime in here for a second to say that I am also interested in this functionality.

It is not clear in the docs either that the IDP needs to be up at server startup and orchestrating such an order can be cumbersome. I would have expected a behavior similar to the proposed one, where MinIO would periodically check the IDP again to see if it becomes available.

**Comment by kashalls** [comment]
Maintainer says they won't implement it in non-enterprise branch. Another lost to the SSO Tax. 😕

See https://github.com/minio/minio/pull/20333#issuecomment-2365403444

**Comment by harshavardhana** [comment]
> It is not clear in the docs either that the IDP needs to be up at server startup and orchestrating such an order can be cumbersome. I would have expected a behavior similar to the proposed one, where MinIO would periodically check the IDP again to see if it becomes available.

@ravindk89 @djwfyi we might have to make this clear in the docs.

**Comment by septatrix** [comment]
> > It is not clear in the docs either that the IDP needs to be up at server startup and orchestrating such an order can be cumbersome. I would have expected a behavior similar to the proposed one, where MinIO would periodically check the IDP again to see if it becomes available.
> 
> @ravindk89 @djwfyi we might have to make this clear in the docs.

Or fix this obvious bug in the community version for which a patch was already provided. OIDC is already in the community version so it should be bug free...

**Comment by mircea-pavel-anton** [comment]
> > > It is not clear in the docs either that the IDP needs to be up at server startup and orchestrating such an order can be cumbersome. I would have expected a behavior similar to the proposed one, where MinIO would periodically check the IDP again to see if it becomes available.
> > 
> > @ravindk89 @djwfyi we might have to make this clear in the docs.
> 
> Or fix this obvious bug in the community version for which a patch was already provided. OIDC is already in the community version so it should be bug free...

+1 on this. It's baffling to me to leave bugs in the community version intentionally 
This makes me question if we should really use this tool at work given the attitude

**Comment by harshavardhana** [comment]
Locking the conversation here since its not getting productive.

**Comment by harshavardhana** [comment]
OpenID must be online before MinIO service, doing this safely is complicated - the order of services must be established here.  An IDP is considered available just like a KMS service or any other external service that is important enough to apply authentication and authorization during the service startup.

If it's unavailable, operating a service is not generally safe. This is a deployment problem, you shouldn't be deploying stuff in this manner when you have dependent services. 

Observe how our operator does it https://github.com/minio/operator - manages to deploy a KMS service properly - before it starts a MinIO service. IDP needs to be done in the same manner. 

**As a courtesy, we are adding support for reconnecting automatically when it is safe to do so during the startup sequence. It is an advanced feature request and enhancement in behavior to make provisions for a safer way to operate under poor deployment conditions.**

How we are making this feature available is entirely up to us.
