### ISSUE TITLE
Several KES commands not working anymore

### ISSUE THREAD

**Issue by ramondeklein** [minio/minio#20125]
The MinioAdmin client implements a lot of KMS commands (source). It looks like all KES/KMS commands are routed through MinIO. Although I was able to create keys using this client, deleting the keys results in an error. After some investigation it looks like the KMS router in MinIO (source) only forwards some commands. It looks like https://github.com/minio/minio/pull/19368 removed this functionality a few months ago. This is the most important part:
![image](https://github.com/user-attachments/assets/d8bd1ab1-0810-4c52-b715-e8ba67a371b2)

It's not possible to list policies, identities and to import/delete keys anymore. I ran a local console (non-Enterprise version) and it also fails to delete keys:
![image](https://github.com/user-attachments/assets/b88d5d5e-0e41-4aad-94fd-12cc67a12ad8)

**Comment by aead** [comment]
In general, MinIO should only expose as few KMS APIs as possible. Proper KMS management should be done separately.

In particular, various policy and identity APIs make no sense. KES is intentionally static in the sense that policies and identities are provided by the KES config file and cannot be changed.
The MinIO UI is not the right place to manage the KMS beyond the small subset of tasks MinIO as an S3 storage needs to accomplish.

**Comment by ramondeklein** [comment]
I think it's dangerous to delete keys via MinIO too. Vaults can be shared by multiple clusters, so it's hard to determine if a key is still in use. But we should remove that functionality from the MinIO console. I'll create an issue for that.

**Comment by ramondeklein** [comment]
See https://github.com/minio/console/issues/3412.
