### ISSUE TITLE
Minio failed to delete empty folder and metadata.json

### ISSUE THREAD

**Issue by streamvsriver** [minio/minio#20138]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Minio left the empty prefix undeleted with metadata.json folder. 

Tried to manually delete the directory vi mc client, it got successful response but from the trace, it indicated the file not found.

```
[user@testvm ~]$ mc stat minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11
Name      : 2021-01-11/
Date      : 2024-07-24 09:12:42 JST
Type      : folder

[user@testvm ~]$ mc ls  minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11
[2023-07-17 14:03:30 JST]   655B STANDARD metadata.json

[user@testvm ~]$ mc rm --versions --force --recursive  minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11
Removed `minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11/metadata.json` (versionId=null).

[user@testvm ~]$ mc admin trace minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11 | grep kreq_minute_last_done_count
2024-07-23T16:01:23.734 [404 Not Found] s3.HeadObject minio-research-ss-2-5.minio-test-hl.minio.svc.test.ks:9000/shenron-shared/kreq_minute_last_done_count/2021-01-11 10.73.12.21      6.304ms      ⇣  0s         ↑ 77 B ↓ 0 B
2024-07-23T16:01:23.796 [200 OK] s3.ListObjectsV2 minio-research-ss-2-5.minio-test-hl.minio.svc.test.ks:9000/shenron-shared/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&max-keys=1&prefix=kreq_minute_last_done_count%2F2021-01-11%2F  10.73.12.21      3.122ms      ⇣  3.108288ms  ↑ 77 B ↓ 702 B
2024-07-23T16:01:23.855 [200 OK] s3.ListObjectVersions minio-research-ss-2-5.minio-test-hl.minio.svc.test.ks:9000/shenron-shared/?delimiter=&encoding-type=url&prefix=kreq_minute_last_done_count%2F2021-01-11&versions=  10.73.12.21      3.214ms      ⇣  3.197721ms  ↑ 77 B ↓ 813 B
```

## Expected Behavior

The prefix should be automatically deleted by minio, if the prefix does not have any object.

## Current Behavior

The empty prefix persist in the cluster, s3 query via boto3 client and mc client both still can discover the folder via listObjectV1/V2 api or mc client, even though tried to delete the profix via mc client

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

Unable to recreate the issue. Just some of the prefixes exhibit the problme.

## Context

We check if the object existed in the prefix, to determine whether we  can used the folder for our training workload. But, as the emtpy directory in the path with other prefix actually containing the data. It constant caused 404 not found error for our end user workload, when they scan the directory for available data. 

## Regression
 No

## Your Environment

* Version used (`minio --version`): 2024-02-24T17:11:14Z
* Server setup and configuration: 6 test host with 6 x 7TB nvme each hosts running in kubernete cluster. The minio cluster is spinning up with minio operator 5.0.12
* Operating System and version (`uname -a`): Linux 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> [user@testvm ~]$ mc rm --versions --force --recursive  minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11

just use 

```
mc rm --force --purge minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11
```

**Comment by streamvsriver** [comment]
Hi @harshavardhana , 

Thanks for the quick response. 

Tried the purge option, but the problematic prefix persisted. 

```
[user@testvm ~]$ mc rm --force --purge minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11
Removed `minio-research/shenron-shared/kreq_minute_last_done_count/2021-01-11`.
[user@testvm ~]$ mc ls minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11
[2023-07-17 14:03:30 JST]   655B STANDARD metadata.json
```

**Comment by harshavardhana** [comment]
Check if you have .trash folder present on all the nodes on all the drives at .minio.sys/tmp/.trash 

If it's not present create it manually using mkdir -p and the run the purge command again this time with / at the end.

```
[user@testvm ~]$ mc rm --force --purge minio-test/shenron-shared/kreq_minute_last_done_count/2021-01-11/
Removed `minio-research/shenron-shared/kreq_minute_last_done_count/2021-01-11/`.
```

**Comment by streamvsriver** [comment]
hi @harshavardhana , 

Thanks a lot for the tips. Indeed couples of the disk missing .minio.sys/tmp/.trash. I added the directory back to the drive and redelete the folder. 

Now the empty prefix is gone now.

Thanks again for your help.

**Comment by harshavardhana** [comment]
> hi @harshavardhana ,
> 
> Thanks a lot for the tips. Indeed couples of the disk missing .minio.sys/tmp/.trash. I added the directory back to the drive and redelete the folder.
> 
> Now the empty prefix is gone now.
> 
> Thanks again for your help.

Yeah so please upgrade your setup.
