### ISSUE TITLE
MINIO_STS_DURATION, MINIO_BROWSER_SESSION_DURATION ignored in environment variables for share links

### ISSUE THREAD

**Issue by teward** [minio/minio#20146]
When attempting to use temporary share links (STS), the system says it allows sharing durations of 12 hours, the default for the web session.

It says we can override the maximum by setting `MINIO_STS_DURATION`.  Additionally, because it also has the web session restriction, we have to set the web session timeout equally high.

Accordingly, we would expect setting `MINIO_STS_DURATION` and `MINIO_BROWSER_SESSION_DURATION` to the same value to allow the UI to change the max share time to 30 days if both are set to it (`30d`) would work to allow a larger share time to be set.

## Expected Behavior
Share UI lets us enter a value up to the set value in MINIO_STS_DURATION and MINIO_BROWSER_SESSION_DURATION.

## Current Behavior
Neither MINIO_STS_DURATION or MINIO_BROWSER_SESSION_DURATION changes actually change the UI share time setting.

## Steps to Reproduce (for bugs)

1. Create bucket and upload a file into it.
2. Observe the "Share" function and it locks by default to 12 hours.
3. Log out of MinIO.
4. Set the environment variables as stated in description for the nodes to 30 days.
5. Relogin to MinIO.
6. Attempt to change share time to > 12 hours (30d or such).

## Context

We are using MinIO with cases where single files should be able to be shared without login credentials in order to permit certain external individuals to have easy access to the file for a temporary period of time.  The "Share" function meets this criterion, however it is not possible to get long enough *duration* on links because of these observed issues.

(Note I opened a [discussion](https://github.com/minio/minio/discussions/20109) on this but got zero replies and can still replicate this)

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-07-10T18-41-49Z (commit-id=6c6f0987dc04c942c33a2a90ffbe7075c0e2e5eb)`
* Server setup and configuration: Ubuntu 24.04 virtual machine, SystemD and .deb package installed from the .deb downloads. SNMD deployment.
* Operating System and version (`uname -a`): `Linux ubuntu 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC ...`

**Comment by taran-p** [comment]
For environment variables, days are not parsed. Does setting `MINIO_STS_DURATION` to `720h` (30d) fix your problem?

**Comment by teward** [comment]
@taran-p Yep that worked.

However, this means that there are one of two cases that need to happen:

(1) Documentation for both MINIO_STS_DURATION and MINIO_BROWSER_SESSION_DURATION should be updated to indicate acceptable time designation formats (indicate that `d` for days is not parsed and such time has to be set in hours `h` or specify the complete list of time specification formats that're accepted).

(2) The environment variable parsing should be updated to accept days.  It's annoying to have to manually do this conversion first yourself into hours (or smaller time segments) if the length should be in days (it's easier to define it *in* days).

**Comment by taran-p** [comment]
The duration parsing is done with Go's standard library ParseDuration, which intentionally does not parse days ([here](https://github.com/golang/go/issues/11473) for more info). Closing this issue, I'll look into the documentation.
