### ISSUE TITLE
MinIO pod memory consumption keeps increasing

### ISSUE THREAD

**Issue by vigneshvmohan** [minio/minio#20156]
We've deployed the mimir-distributed helm-chart version 5.4.0. We noticed that the memory usage of the MinIO pod running as dependency for mimir has been increasing steadily until it reaches it's limit.
Only an OOM kill or restart brings down the memory usage.
![image](https://github.com/user-attachments/assets/3db6c352-fb40-481a-b06f-df9ebc51eb41)

## Expected Behavior
stable memory usage for MinIO pod

## Current Behavior
Currently the memory usage of MinIO pod continues to increase until it reaches the limit

## Steps to Reproduce (for bugs)
deploy mimir-distributed using helm chart 5.4.0
observe the memory usage increasing for the MinIO pod in Mimir namespace

## Your Environment
AKS version : 1.28.9
Mimir helm-chart : 5.4.0
Mimir version : 2.12.0
MinIO version : 5.0.14

**Comment by harshavardhana** [comment]
set `--memlimit <pod_limit>` for memory, such tiny memory is not what we optimize for.

**Comment by vigneshvmohan** [comment]
@harshavardhana 

The current limit for the pod is 512Mi. It seems if we keep increasing the limit the memory usage will continue to rise till it reaches the limit and get's itself OOMkilled.

Is this expected and whether this will have any impact ?

**Comment by harshavardhana** [comment]
> The current limit for the pod is 512Mi. It seems if we keep increasing the limit the memory usage will continue to rise till it reaches the limit and get's itself OOMkilled.
> 
> Is this expected and whether this will have any impact ?

minio server --memlimit 500MiB is your option
