### ISSUE TITLE
Object with path that prefixes another file shadows that second file

### ISSUE THREAD

**Issue by jjnesbitt** [minio/minio#20167]
When uploading a pair of files that share a path delimited prefix, the file with the "nested" path (e.g. `foo/bar`) is shadowed entirely by the "parent" file (e.g. `foo`), until all versions of that "parent" file are deleted. What's more is that if the "parent" object is deleted normally (using a delete marker), it _fully_ shadows the second object, and minio will report no objects in the bucket at all (except the delete marker on the parent object).

## Expected Behavior
When uploading the second object, they are both visible. This is how S3 behaves, with `foo` and `foo/bar` both visible at the same time.

## Current Behavior
When uploading the second object, only the first object is visible.

## Steps to Reproduce
<details>

<summary>MVCE with the Python Client</summary>

```python
import io

from minio import Minio
from minio.commonconfig import ENABLED
from minio.versioningconfig import VersioningConfig

BUCKET_NAME = "my-bucket"
client = Minio(
    "localhost:9000",
    secure=False,
    access_key="minioAccessKey",
    secret_key="minioSecretKey",
)
client.make_bucket(bucket_name=BUCKET_NAME)
client.set_bucket_versioning(bucket_name=BUCKET_NAME, config=VersioningConfig(ENABLED))

# Create file one
FILE_ONE = "foo"
res = client.put_object(
    bucket_name=BUCKET_NAME, object_name=FILE_ONE, data=io.BytesIO(b"hello"), length=5
)
FILE_ONE_VERSION_ID = res.version_id
objects = [
    (obj.object_name, obj.version_id, obj.size)
    for obj in client.list_objects(
        bucket_name=BUCKET_NAME, recursive=True, include_version=True
    )
]

print(f"Bucket objects: {objects}")
print(f"File {FILE_ONE} exists: {FILE_ONE in [x[0] for x in objects]}")

# Create file with a path prefix that contains the recently deleted file
FILE_TWO = "foo/bar"
res = client.put_object(
    bucket_name=BUCKET_NAME,
    object_name=FILE_TWO,
    data=io.BytesIO(b"hello2"),
    length=6,
)
FILE_TWO_VERSION_ID = res.version_id
objects = [
    (obj.object_name, obj.version_id, obj.size)
    for obj in client.list_objects(
        bucket_name=BUCKET_NAME, recursive=True, include_version=True
    )
]
print(f"Bucket objects: {objects}")
print(f"File {FILE_TWO} exists: {FILE_TWO in [x[0] for x in objects]}")


# Delete first file, which will completely obscure the second one
print("Removing first object")
res = client.remove_object(bucket_name=BUCKET_NAME, object_name=FILE_ONE)
BUCKET_FILES_LIST = [
    (obj.object_name, obj.version_id, obj.size)
    for obj in client.list_objects(
        bucket_name=BUCKET_NAME, recursive=True, include_version=True
    )
]
print(f"Bucket objects: {objects}")
print(f"File {FILE_TWO} exists: {FILE_TWO in [x[0] for x in BUCKET_FILES_LIST]}")


print("Removing all versions of first object")
for name, version, _ in BUCKET_FILES_LIST:
    client.remove_object(bucket_name=BUCKET_NAME, object_name=name, version_id=version)

objects = [
    (obj.object_name, obj.version_id, obj.size)
    for obj in client.list_objects(
        bucket_name=BUCKET_NAME, recursive=True, include_version=True
    )
]
print(f"Bucket objects: {objects}")
print(f"File {FILE_TWO} exists: {FILE_TWO in [x[0] for x in objects]}")


# Cleanup
client.remove_object(
    bucket_name=BUCKET_NAME, object_name="foo/bar", version_id=FILE_TWO_VERSION_ID
)
client.remove_bucket(bucket_name=BUCKET_NAME)

```
</details>

1. Create a version enabled bucket
2. Upload an object (e.g. `foo`)
3. Upload a second object that fully contains the first object in it's path, as if that first object is a "folder" (e.g. 'foo/bar')
4. Observe that only the first object is visible

## Context
We're trying to run local tests for our application that makes use of versioned S3 buckets.

## Your Environment
Docker image `minio/minio:latest` as of 2024-07-24
```
bash-5.1# minio -v
minio version RELEASE.2024-07-16T23-46-41Z (commit-id=3535197f993dea840dcb96302ba4d883dc619097)
Runtime: go1.22.5 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```

**Comment by harshavardhana** [comment]
Yes that is expected https://min.io/docs/minio/kubernetes/upstream/operations/concepts/thresholds.html#id6

**Comment by klauspost** [comment]
Yes. That is documented here: https://min.io/docs/minio/linux/operations/concepts/thresholds.html#conflicting-objects

**Comment by jwodder** [comment]
But the problem happens even if a key is deleted before uploading a conflicting key and is afterwards only kept around due to versioning.  Surely that isn't intended?

**Comment by harshavardhana** [comment]
> But the problem happens even if a key is deleted before uploading a conflicting key and is afterwards only kept around due to versioning. Surely that isn't intended?

Versioning by default is soft delete, nothing is deleted yet.

**Comment by harshavardhana** [comment]
The point is you should never have conflicting names in that manner; it is simply something we have no plans to support. You may have a use-case but that is beyond the scope of this project at the moment.
