### ISSUE TITLE
mc anonymous set download Why can I view the bucket file list

### ISSUE THREAD

**Issue by liuxin638507** [minio/minio#20186]
mc anonymous set download Permission after s3/mybucket is set:
~~~bash
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}
~~~
This will show you a bucket list of files, and it's very full, why not permissions:
~~~bash
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}
~~~
* Version used (`minio --version`): 2024.7.29
* Operating System and version (`uname -a`): Linux node-y1 5.11.16-1.el7.elrepo.x86_64

**Comment by marktheunissen** [comment]
> This will show you a bucket list of files, and it's very full, why not permissions:

Hi, could you explain what you mean? I don't understand "very full" and "why not permissions". 

Please paste the output that you saw and what you expect to see?


- `"arn:aws:s3:::fusion"`
- `"arn:aws:s3:::mybucket/*"`

These are different resources, what do you intend here?

**Comment by liuxin638507** [comment]
> > This will show you a bucket list of files, and it's very full, why not permissions:
> 
> Hi, could you explain what you mean? I don't understand "very full" and "why not permissions".
> 
> Please paste the output that you saw and what you expect to see?
> 
> * `"arn:aws:s3:::fusion"`
> * `"arn:aws:s3:::mybucket/*"`
> 
> These are different resources, what do you intend here?
Sorry, it's the same bucket name: mybucket

When there are a large number of files in it, accessing the root path of mybucket will display a list of all files, which is very slow to load and feels unsafe. The mc anonymous set download strategy currently includes

Action ": [" s3: ListBucket "," s3: GetBucketLocation "]policy, I think it only needs to be able to access the file, why not just include it

Action ": [" s3: GetObject "], this strategy


> > This will show you a bucket list of files, and it's very full, why not permissions:
> 
> Hi, could you explain what you mean? I don't understand "very full" and "why not permissions".
> 
> Please paste the output that you saw and what you expect to see?
> 
> * `"arn:aws:s3:::fusion"`
> * `"arn:aws:s3:::mybucket/*"`
> 
> These are different resources, what do you intend here?

Sorry, it's the same bucket name: mybucket

When there are a large number of files in it, accessing the root path of mybucket will display a list of all files, which is very slow to load and feels unsafe. The mc anonymous set download strategy currently includes

Action ": [" s3: ListBucket "," s3: GetBucketLocation "], policy, I think it only needs to be able to access the file, why not just include it

Action ": [" s3: GetObject "], this strategy

**Comment by harshavardhana** [comment]
mc anonymous set download is meant for exploring what objects are present to download. 

Think of this like ISO downloads, public rpm or deb archives etc.

If you want special policies write your own via set-json
