### ISSUE TITLE
Site Replication dosn't sync policy attachments

### ISSUE THREAD

**Issue by zhilyaev** [minio/minio#20197]
## NOTE
I have finished the site replication process.

## Expected Behavior
Policy attachments are syncing well.

## Current Behavior
I have the policy with the name `my-policy` and the user `my-user`.
The user and policy have synced successfully. But `my-user` doesn't have `my-policy`.
Therefore my application has the error Access Denied.

## Possible Solution
Add Attachment relations to the sync procedure.

## Steps to Reproduce (for bugs)

1. create minio-a and minio-b
2. create my-app1,my-app2  user and policy with name my-policy1, my-policy2 . Attach my-policy1 to my-user1. And my-policy2 to my-user2 
3. Setup Site replication: `mc admin replicate add minio-a minio-b`
4. Open minio-b. Inspect my-user.

## Your Environment
* Version used 2024.6.13
* Server setup and configuration: K8s, bitnami chart minio-14.6.11

**Comment by harshavardhana** [comment]
If we haven't mentioned this a dozen times already, report issues with latest release or a release before that. 

Please upgrade first, test and report issue if still exists
