### ISSUE TITLE
minio read-after-write feature is not guaranteed

### ISSUE THREAD

**Issue by xiaozhukuaipaoba** [minio/minio#20200]
## Expected Behavior

Minio needs to ensure strict read-write features both in distributed and standalone modes.
https://github.com/minio/minio/blob/master/docs/distributed/README.md#consistency-guarantees

## Current Behavior

In the scenario of concurrent writing on the same object, minio cannot read the newly written object，and return 404.

## Possible Solution

Minio should follows strict read-after-write consistency model，and fix this issue.

## Steps to Reproduce (for bugs)

1. Start a minio(standalone mode) and use HDD(SATA) drive as the storage backend，**filesystem is xfs**.
3. Using a client, start the pressure to fully utilize Minio's disk usage(95%+).
4. Using another client(10 threads), each thread put an object, and immediately read the object upon successful writing. **The object name is the same of all threads(concurrent overwrite).**
5. After a period of time, possibly several hours, it was found that there were 404 returns.

My minio configuration：

> MINIO_VOLUMES="/data/{0...1}"  // /data/0 and /data/1 are two SATA HDD drive and format as xfs.
> MINIO_OPTS="--console-address :9001"
> MINIO_ROOT_USER=*********
> MINIO_ROOT_PASSWORD=*********
> MINIO_STORAGE_CLASS_STANDARD="EC:0"
> MINIO_PROMETHEUS_AUTH_TYPE='public'
> 
> systemctl start minio

Reproduce client pseudocode：

```
void main() 
{
  while (1) {
    std::vector<std::thread> threads;
    for (int i = 0; i < num_threads; ++i) {
      char file_path[1024] = {0};
      // generate file path，for example, using the current time as a suffix
      threads.push_back(std::thread(write_to_minio, file_path));
      for (auto& t : threads)  {   
        t.join();     
      }
    }
  }
}

void write_to_minio(const char *file_path) {
  // use s3 client put this object
  s3_client.put_object(file_path);
  // if put success, then read the same object
  if (put_succ) {
    s3_client.get_object(file_path);
    // expected to be able to read the data, it will definitely not return a 404
  }
}
```

minio audit log

> for one thread:
> 
> put_object succ:
> 
> {"version":"1","deploymentid":"fc635b24-6802-46ee-a416-8975cca777d8","time":"2024-07-31T07:21:56.454597984Z","event":"","trigger":"incoming","api":{"name":"PutObject","bucket":"oushen","object":"io_adapter_unittest_dir/test_io_manager_rw_1722410508561073","status":"OK","statusCode":200,"rx":4096,"tx":0,"txHeaders":408,"timeToResponse":"7892548598ns","timeToResponseInNS":"7892548598"},"remotehost":"xxx.xxx.xxx.xxx","requestID":"17E73B3B583DB8E1","userAgent":"aws-sdk-cpp/1.11.156 Linux/3.10.0-327.ali2019.alios7.x86_64 x86_64 GCC/9.3.0","requestPath":"/oushen/io_adapter_unittest_dir/test_io_manager_rw_1722410508561073","requestHost":"xxx.xxx.xxx.xxx:9000","requestHeader":{"Accept":"*/*","Amz-Sdk-Invocation-Id":"B274EF3E-9D51-4FAA-BADB-692C8C7F7FC9","Amz-Sdk-Request":"attempt=1","Authorization":"AWS4-HMAC-SHA256 Credential=xxxxxxx/20240731/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=d89d2d0d307562f42236f20d4d547a0e403a074db39afa6b7f53312d8bab875e","Content-Length":"4096","Content-Md5":"K808TeIMkY4Z+rXDYknHDQ==","Content-Type":"binary/octet-stream","Expect":"100-continue","User-Agent":"aws-sdk-cpp/1.11.156 Linux/3.10.0-327.ali2019.alios7.x86_64 x86_64 GCC/9.3.0","X-Amz-Content-Sha256":"c8f5d0341d54d951a71b136e6e2afcb14d11ed8489a7ae126a8fee0df6ecf193","X-Amz-Date":"20240731T072148Z"},"responseHeader":{"Accept-Ranges":"bytes","Content-Length":"0","ETag":"2bcd3c4de20c918e19fab5c36249c70d","Server":"MinIO","Strict-Transport-Security":"max-age=31536000; includeSubDomains","Vary":"Origin,Accept-Encoding","X-Amz-Id-2":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","X-Amz-Request-Id":"17E73B3B583DB8E1","X-Content-Type-Options":"nosniff","X-Xss-Protection":"1; mode=block","x-amz-version-id":"e5069a52-2e04-4e88-b60e-36f4e2e8451e"},"tags":{"objectLocation":{"name":"io_adapter_unittest_dir/test_io_manager_rw_1722410508561073","poolId":1,"setId":1,"drives":["/data/0","/data/1"]}},"accessKey":"*********"}
>           
>              
> get_object return 404:
>     
> {"version":"1","deploymentid":"fc635b24-6802-46ee-a416-8975cca777d8","time":"2024-07-31T07:22:06.268202915Z","event":"","trigger":"incoming","api":{"name":"GetObject","bucket":"oushen","object":"io_adapter_unittest_dir/test_io_manager_rw_1722410508561073","status":"Not Found","statusCode":404,"rx":0,"tx":437,"txHeaders":351,"timeToFirstByte":"9806393741ns","timeToFirstByteInNS":"9806393741","timeToResponse":"9806401290ns","timeToResponseInNS":"9806401290"},"remotehost":"xxx.xxx.xxx.xxx","requestID":"17E73B3D2F1A5E61","userAgent":"aws-sdk-cpp/1.11.156 Linux/3.10.0-327.ali2019.alios7.x86_64 x86_64 GCC/9.3.0","requestPath":"/oushen/io_adapter_unittest_dir/test_io_manager_rw_1722410508561073","requestHost":"xx.xxx.xxx.xxx:9000","requestHeader":{"Accept":"*/*","Amz-Sdk-Invocation-Id":"6E5AE8F0-EEBD-45FB-9029-8C8D6C658E18","Amz-Sdk-Request":"attempt=1","Authorization":"AWS4-HMAC-SHA256 Credential=xxxxxxx/20240731/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-type;host;range;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=2df4b8bc66920f11a37cd367bdc23968a629b4f32a5b419e2ae8f5f6e47d288c","Content-Type":"application/xml","Range":"bytes=0-4095","User-Agent":"aws-sdk-cpp/1.11.156 Linux/3.10.0-327.ali2019.alios7.x86_64 x86_64 GCC/9.3.0","X-Amz-Api-Version":"2006-03-01","X-Amz-Content-Sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","X-Amz-Date":"20240731T072156Z"},"responseHeader":{"Accept-Ranges":"bytes","Content-Length":"437","Content-Type":"application/xml","Server":"MinIO","Strict-Transport-Security":"max-age=31536000; includeSubDomains","Vary":"Origin,Accept-Encoding","X-Amz-Id-2":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","X-Amz-Request-Id":"17E73B3D2F1A5E61","X-Content-Type-Options":"nosniff","X-Xss-Protection":"1; mode=block"},"tags":{"objectLocation":{"name":"io_adapter_unittest_dir/test_io_manager_rw_1722410508561073","poolId":1,"setId":1,"drives":["/data/0","/data/1"]}},"accessKey":"*******"}

## Your Environment

uname -a
Linux obvos-dev-u5 3.10.0-327.ali2019.alios7.x86_64 #1 SMP Sun Jan 19 18:21:42 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

minio --version
minio version RELEASE.2024-06-13T22-53-53Z (commit-id=20960b6a2ddb9594ee418035b3c7c7fe92ae6a12)
Runtime: go1.22.4 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             1
NUMA node(s):          1

**Comment by harshavardhana** [comment]
@xiaozhukuaipaoba please report issues with latest releases.

Next time also talk what is your backend disk filesystem and also output of `dmesg -T`
