### ISSUE TITLE
posix: All posix operations need unit tests 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2021]
Currently only ReadAll and readDir are implemented.

**Comment by harshavardhana** [comment]
Need to implement tests for 
- MakeVol
- DeleteVol
- StatVol
- ListVols
- DeleteFile
- AppendFile
- RenameFile
- StatFile

**Comment by GarimaKapoor** [comment]
@balamurugana please update the timeline to fix this issue.
