### ISSUE TITLE
REST API is documented here https://github.com/minio/minio/tree/master/pkg/madmin , for now, we are not planning to implement different language libraries for Admin REST API.  Our SDKs are only meant for S3 APIs only.

### ISSUE THREAD

**Issue by awezmapr** [minio/minio#20217]
Link is not available.

              REST API is documented here https://github.com/minio/minio/tree/master/pkg/madmin , for now, we are not planning to implement different language libraries for Admin REST API.  Our SDKs are only meant for S3 APIs only. 

The suggested way is to use `mc` tool or use the Go API directly or write your own wrapper for your language choice.

_Originally posted by @harshavardhana in https://github.com/minio/minio/issues/7539#issuecomment-482898917_

**Comment by klauspost** [comment]
https://github.com/minio/madmin-go
