### ISSUE TITLE
Permissions Issue upgrading MinIO version

### ISSUE THREAD

**Issue by Teachh** [minio/minio#20245]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Allow the normally usage of MinIO GUI console.
## Current Behavior

Having **invalid Login.** error and this error logs executing `journalctl -u minio.service`:
```
....
Aug 12 09:58:50 minio minio[19417]: Error: Prefix access is denied: .minio.sys/buckets/.background-heal.json (cmd.PrefixAccessDenied)
Aug 12 09:58:50 minio minio[19417]:        5: internal/logger/logger.go:268:logger.LogIf()
Aug 12 09:58:50 minio minio[19417]:        4: cmd/logging.go:112:cmd.internalLogIf()
Aug 12 09:58:50 minio minio[19417]:        3: cmd/data-scanner.go:152:cmd.saveBackgroundHealInfo()
Aug 12 09:58:50 minio minio[19417]:        2: cmd/data-scanner.go:203:cmd.runDataScanner()
Aug 12 09:58:50 minio minio[19417]:        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()
Aug 12 09:58:50 minio minio[19417]: API: SYSTEM.scanner
Aug 12 09:58:50 minio minio[19417]: Time: 09:58:50 UTC 08/12/2024
Aug 12 09:58:50 minio minio[19417]: DeploymentID: 0a23bce0-b447-47c4-a4d7-f47ec87119c8
Aug 12 09:58:50 minio minio[19417]: Error: Prefix access is denied: .minio.sys/buckets/.usage-cache.bin (cmd.PrefixAccessDenied)
Aug 12 09:58:50 minio minio[19417]:        3: internal/logger/logger.go:268:logger.LogIf()
Aug 12 09:58:50 minio minio[19417]:        2: cmd/logging.go:136:cmd.scannerLogIf()
Aug 12 09:58:50 minio minio[19417]:        1: cmd/erasure-server-pool.go:760:cmd.(*erasureServerPools).NSScanner.func1()
Aug 12 09:58:50 minio minio[19417]: API: SYSTEM.scanner
Aug 12 09:58:50 minio minio[19417]: Time: 09:58:50 UTC 08/12/2024
Aug 12 09:58:50 minio minio[19417]: DeploymentID: 0a23bce0-b447-47c4-a4d7-f47ec87119c8
Aug 12 09:58:50 minio minio[19417]: Error: Prefix access is denied: .minio.sys/buckets/.usage-cache.bin (cmd.PrefixAccessDenied)
Aug 12 09:58:50 minio minio[19417]:        4: internal/logger/logger.go:268:logger.LogIf()
Aug 12 09:58:50 minio minio[19417]:        3: cmd/logging.go:136:cmd.scannerLogIf()
Aug 12 09:58:50 minio minio[19417]:        2: cmd/data-scanner.go:210:cmd.runDataScanner()
Aug 12 09:58:50 minio minio[19417]:        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()
Aug 12 09:59:36 minio minio[19417]: INFO: Exiting on signal: TERMINATED

```
## Possible Solution

In my case, the fix was changing the service configuration in ` /lib/systemd/system/minio.service` commenting the User and Group
```yaml
[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
Type=notify

WorkingDirectory=/usr/local

#User=minio-user <----- THIS
#Group=minio-user <----- THIS
ProtectProc=invisible

EnvironmentFile=-/etc/default/minio
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

Restart=always

LimitNOFILE=1048576

MemoryAccounting=no

TasksMax=infinity

TimeoutSec=infinity

SendSIGKILL=no

[Install]
WantedBy=multi-user.target

```
## Steps to Reproduce (for bugs)

1. Upgrade the version of MinIO following [this documentation](https://min.io/docs/minio/linux/operations/install-deploy-manage/upgrade-minio-deployment.html).

## Context

When upgrading to **RELEASE.2024-08-03T04-33-23Z (commit-id=6efb56851c40da88d1ca15112e2d686a4ecec6b3)**, there were permissions issues that did not allow the access  because of the error **invalid Login.** in the landing page.

## Your Environment

* Version used (`minio --version`):  RELEASE.2024-08-03T04-33-23Z (commit-id=6efb56851c40da88d1ca15112e2d686a4ecec6b3)
* Server setup and configuration: [Folder permissions](https://github.com/minio/minio-service/blob/master/linux-upstart/README.md) and the service configuration provided in **Possible Solution**
* Operating System and version (`uname -a`): Ubuntu 22.04.4 Server

**Comment by harshavardhana** [comment]
> In my case, the fix was changing the service configuration in ` /lib/systemd/system/minio.service` commenting the User and Group

It would help if you used what user you wish to run MinIO as and what your backend drive permissions are.  When you upgrade via RPM or DEB the service file is updated, if you have chosen in the past to not use `minio-user` you should make those changes. 

Or fix the permissions.
