### ISSUE TITLE
aws-java-sdk is not working properly with Minio over https

### ISSUE THREAD

**Issue by fryzhykau** [minio/minio#2024]
## Expected behaviour

Upload executes correctly
## Actual behaviour

`com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3L137), S3 Extended Request ID: 3L137
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1370)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:917)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:695)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:447)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:409)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:358)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3821)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1415)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`
## Minio version

```
Version: 2016-06-03T19:32:05Z
Release-Tag: RELEASE.2016-06-03T19-32-05Z
Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074
```
## System information

and our nginx configuration

```
server {
    listen       443;
    server_name  example.com;

    ssl                  on;
    ssl_certificate      /etc/nginx/cert.pem;
    ssl_certificate_key  /etc/nginx/cert.key;

    gzip off;
    add_header Strict-Transport-Security "max-age=31536000;";
     location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://s3;
   }
}
```

Nginx version:
`nginx/1.10.0`

aws-java-sdk version : 
`
<dependency>
         <groupId>com.amazonaws</groupId>
         <artifactId>aws-java-sdk-s3</artifactId>
         <version>1.11.9</version>
     </dependency>
`

Code example:
`
public String uploadOutputDataToS3WithBuffer(String bucketName, String key, InputStream is, ObjectMetadata objectMetadata)  throws S3UploadException {
        TransferManager tm = new TransferManager(createS3Client());
        File tmpFile = null;
        try {
            tmpFile = stream2file(is);
            Upload upload = tm.upload(bucketName, key, new FileInputStream(tmpFile), objectMetadata);
            logger.info(upload.getDescription());
            upload.waitForCompletion();
            return String.format(s3Config.getEndpointUrl() + "/%s/%s", bucketName, key);
        } catch (InterruptedException e) {
            throw new S3UploadException();
        } catch (IOException e) {
            logger.error("Failed to create temporary file", e);
            throw new S3UploadException();
        } finally {
            if (tmpFile != null && tmpFile.exists()) {
                tmpFile.delete();
            }
            tm.shutdownNow();
        }
    }
`

`
 public AmazonS3 createS3Client() {

```
    AWSCredentials credentials = s3Config.getCredentials();
    AmazonS3Client amazonS3Client;

    if (!s3Config.isDefaultS3Used()) { // Support of S3 emulator

        String s3EndpointUrl = s3Config.getEndpointUrl();
        String s3SignatureType = s3Config.getSignatureType();

        ClientConfiguration clientConfiguration = new ClientConfiguration();
        String signatureVersion = S3_SIGNER;
        if (S3Configuration.S3_SIGNATURE_TYPE_V4.equalsIgnoreCase(s3SignatureType)) {
            signatureVersion = S3_V4_SIGNER;
        }
        clientConfiguration.setSignerOverride(signatureVersion);

        amazonS3Client = new AmazonS3Client(credentials, clientConfiguration);
        Region usEast1 = Region.getRegion(Regions.US_EAST_1);
        amazonS3Client.setRegion(usEast1);

        logger.info("Overriding default Amazon S3 endpoint URL by '{}' and signature version '{}'", s3EndpointUrl, signatureVersion);
        final S3ClientOptions clientOptions = S3ClientOptions.builder().setPathStyleAccess(true).disableChunkedEncoding().build();
        // S3ClientOptions clientOptions = new S3ClientOptions();
        // clientOptions.setPathStyleAccess(true);

        amazonS3Client.setS3ClientOptions(clientOptions);
        amazonS3Client.setEndpoint(s3EndpointUrl);
    } else {
        amazonS3Client = new AmazonS3Client(credentials);
    }

    return amazonS3Client;
}
```

`

**Comment by krishnasrinivas** [comment]
@balamurugana I think minio-java uses "host: example.com:443" for signature calculation, i.e it is using port numbers for signature calculation even when the port numbers are 80 and 443 which it should not.

Can you check if that's what is happening?

**Comment by krishnasrinivas** [comment]
Ah, this is `aws-java-sdk` not `minio-java`

**Comment by krishnasrinivas** [comment]
@ironmanby do this in your java file (i.e enable payload signing):

```
final S3ClientOptions clientOptions = S3ClientOptions.builder().setPathStyleAccess(true).disableChunkedEncoding().setPayloadSigningEnabled(true).build();
```

and add this to your nginx config: (disables the PUT body content size limit)

```
client_max_body_size 0;
```

This should fix the problem you are seeing.

**Comment by fryzhykau** [comment]
@krishnasrinivas , @harshavardhana  Thanks a lot, works like a charm! :)
