### ISSUE TITLE
parseObjectAttributes needs to account for the possibility of repeating headers

### ISSUE THREAD

**Issue by jimrobinson** [minio/minio#20267]
## NOTE

The RFC 2616 (HTTP/1.1) specification defines a section [4.2 Message Headers](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) that allows for multiple message-header fields with the same field-name if the field-value for the header is defined as a comma-separated list, as is the case for `X-Amz-Object-Attributes`:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded. 

In minio the [parseObjectAttributes](https://github.com/minio/minio/blob/743ddb196ac071db1f6929c62765ad136112b11f/cmd/object-api-options.go#L226-L235) function has a bug on [line 228](https://github.com/minio/minio/blob/743ddb196ac071db1f6929c62765ad136112b11f/cmd/object-api-options.go#L228) where [http#Header.Get](https://pkg.go.dev/net/http#Header.Get), which can only return a single value, is used instead of [http#Header.Values](https://pkg.go.dev/net/http#Header.Values) which can return multiple values.

If a client's request splits the `X-Amz-Object-Attributes` header across multiple values, as happens in [Go AWS SDK v2](https://github.com/aws/aws-sdk-go-v2)'s [GetObjectAttributes](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#Client.GetObjectAttributes) method, minio will only recognize the first header.

## Expected Behavior

If a `/<bucket>/<key>?attributes` request arrives which splits `X-Amz-Object-Attributes` across multiple headers:

```
X-Amz-Object-Attributes: ETag
X-Amz-Object-Attributes: Checksum
X-Amz-Object-Attributes: ObjectParts
X-Amz-Object-Attributes: StorageClass
X-Amz-Object-Attributes: ObjectSize
```

I expect minio to treat this the same way it treats a single comma-separated list:

```
X-Amz-Object-Attributes: ETag,Checksum,ObjectParts,StorageClass,ObjectSize
```

and for minio to return all the metadata fields:

```
<getObjectAttributesResponse><ETag>5d24b9bdd2228c106cc450b149250736-5</ETag><Checksum></Checksum><ObjectParts><IsTruncated>false</IsTruncated><MaxParts>10000</MaxParts><NextPartNumberMarker>5</NextPartNumberMarker><PartNumberMarker>0</PartNumberMarker><PartsCount>5</PartsCount><Part><PartNumber>1</PartNumber><Size>5242880</Size><ChecksumSHA256>WJNgeAfdBqOk8hkGI71dyjbjSY1bj4kyPVAJCEmeESI=</ChecksumSHA256></Part><Part><PartNumber>2</PartNumber><Size>5242880</Size><ChecksumSHA256>nt5kyXy51JbcuusmseVCnEpe07yb9a8xdI/UbDMRsoA=</ChecksumSHA256></Part><Part><PartNumber>3</PartNumber><Size>5242880</Size><ChecksumSHA256>w+u9sWAglt/RADOcVBfU12rLPZt6HFsM+TgE4cagjw0=</ChecksumSHA256></Part><Part><PartNumber>4</PartNumber><Size>5242880</Size><ChecksumSHA256>JFGyhk9OXG+HRl5SjUhDU3+hVUh4y/BxtimqAcGOpPc=</ChecksumSHA256></Part><Part><PartNumber>5</PartNumber><Size>5242880</Size><ChecksumSHA256>ClT0+i7WJfPCkAjQ+N0QKyyPGXeLihMcbTD8E3WX4OM=</ChecksumSHA256></Part></ObjectParts><StorageClass>STANDARD</StorageClass><ObjectSize>26214400</ObjectSize></getObjectAttributesResponse>
```

## Current Behavior

If a `/<bucket>/<key>?attributes` request arrives which splits `X-Amz-Object-Attributes` across multiple headers:

```
X-Amz-Object-Attributes: ETag
X-Amz-Object-Attributes: Checksum
X-Amz-Object-Attributes: ObjectParts
X-Amz-Object-Attributes: StorageClass
X-Amz-Object-Attributes: ObjectSize
```

Then only the first object attribute, `ETag` in this example, will be returned:

```
<getObjectAttributesResponse><ETag>5d24b9bdd2228c106cc450b149250736-5</ETag></getObjectAttributesResponse>
```

## Possible Solution

`parseObjectAttributes` should be revised to fetch the http header values using [http#Header.Values](https://pkg.go.dev/net/http#Header.Values) instead of the single value returned by [http#Header.Get](https://pkg.go.dev/net/http#Header.Get).

For folks using aws-sdk-go-v2 there's a workaround available client-side, which is to inject some middleware to force the client to merge the headers into a single value, see https://github.com/aws/aws-sdk-go-v2/issues/1620#issuecomment-1069535332

## Steps to Reproduce (for bugs)

Build the following [Go](https://go.dev/) program:
```
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

func main() {
	var profile string
	flag.StringVar(&profile, "profile", "",
		"aws profile")

	var bucket string
	flag.StringVar(&bucket, "bucket", "",
		"s3 object bucket")

	var key string
	flag.StringVar(&key, "key", "",
		"s3 object key")

	var use_path_style bool
	flag.BoolVar(&use_path_style, "use-path-style", false,
		"use old path-style instead of virtual-hosted style s3 requests")

	flag.Parse()

	if bucket == "" {
		log.Fatal("missing required --bucket argument")
	}

	if key == "" {
		log.Fatal("missing required --key argument")
	}

	ctx := context.Background()

	s3cfg, err := config.LoadDefaultConfig(ctx,
		config.WithSharedConfigProfile(profile),
	)
	if err != nil {
		log.Fatal(err)
	}

	s3client := s3.NewFromConfig(s3cfg, func(o *s3.Options) {
		o.UsePathStyle = use_path_style
	})

	attr, err := s3client.GetObjectAttributes(
		ctx,
		&s3.GetObjectAttributesInput{
			Bucket: aws.String(bucket),
			Key:    aws.String(key),
			ObjectAttributes: []types.ObjectAttributes{
				types.ObjectAttributesEtag,
				types.ObjectAttributesChecksum,
				types.ObjectAttributesObjectParts,
				types.ObjectAttributesObjectSize,
			},
		},
	)

	if err != nil {
		log.Fatal(err)
	}

	buf, err := json.MarshalIndent(attr, "", "  ")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(buf))
}
```

and use it to fetch the metadata for an object you uploaded:

```
$ ./get_object_attributes --profile test-elm --use-path-style --bucket test-jrobinso --key x/x.5
{
  "Checksum": null,
  "DeleteMarker": null,
  "ETag": "5d24b9bdd2228c106cc450b149250736-5",
  "LastModified": "2024-08-14T22:34:35Z",
  "ObjectParts": null,
  "ObjectSize": null,
  "RequestCharged": "",
  "StorageClass": "",
  "VersionId": null,
  "ResultMetadata": {}
}
```

Compare this to aws-cli, which uses python's boto3 and which sends everything on a single header:

```
$ aws --profile test-elm s3api get-object-attributes --bucket test-jrobinso --key x/x.5 --object-attributes ETag Checksum ObjectParts StorageClass ObjectSize
{
    "LastModified": "2024-08-14T22:34:35+00:00",
    "ETag": "5d24b9bdd2228c106cc450b149250736-5",
    "Checksum": {},
    "ObjectParts": {
        "TotalPartsCount": 5,
        "PartNumberMarker": 0,
        "NextPartNumberMarker": 5,
        "MaxParts": 10000,
        "IsTruncated": false,
        "Parts": [
            {
                "PartNumber": 1,
                "Size": 5242880,
                "ChecksumSHA256": "WJNgeAfdBqOk8hkGI71dyjbjSY1bj4kyPVAJCEmeESI="
            },
            {
                "PartNumber": 2,
                "Size": 5242880,
                "ChecksumSHA256": "nt5kyXy51JbcuusmseVCnEpe07yb9a8xdI/UbDMRsoA="
            },
            {
                "PartNumber": 3,
                "Size": 5242880,
                "ChecksumSHA256": "w+u9sWAglt/RADOcVBfU12rLPZt6HFsM+TgE4cagjw0="
            },
            {
                "PartNumber": 4,
                "Size": 5242880,
                "ChecksumSHA256": "JFGyhk9OXG+HRl5SjUhDU3+hVUh4y/BxtimqAcGOpPc="
            },
            {
                "PartNumber": 5,
                "Size": 5242880,
                "ChecksumSHA256": "ClT0+i7WJfPCkAjQ+N0QKyyPGXeLihMcbTD8E3WX4OM="
            }
        ]
    },
    "StorageClass": "STANDARD",
    "ObjectSize": 26214400
}
```

## Context

I'm writing some tools that require using the various checksums S3 supports, and I want to be able to fetch all of the current object attribute values using the golang SDK.

## Regression

No

**Comment by marktheunissen** [comment]
Thanks for the detailed bug report @jimrobinson I've got a PR up for this now
