### ISSUE TITLE
Minio has been using 127.0.0.1:9000. I need to change it to 0.0.0.0:9000. What should I do?

### ISSUE THREAD

**Issue by karsapeng** [minio/minio#20275]
minio:
    restart: always
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: minio
    volumes:
      - ./data:/data
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: 'aDdF_37D7OuH'
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    command: server  --address :9000 /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
Why is the local address always 127.0.0.1:9000? I need to change it to 0.0.0.0:9000. How can I change it?

**Comment by karsapeng** [comment]
minio:
    restart: always
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: minio
    volumes:
      - ./data:/data
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: 'aDdF_37D7OuH'
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    command: server --address 0.0.0.0:9000  /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
I changed command to 0.0.0.0:9000 to start the container. netstat -tulnp check is still 127.0.0.1:9000

**Comment by harshavardhana** [comment]
We always need to listen on 127.0.0.1:9000 that is a design requirement.
