### ISSUE TITLE
what's the command to sync and bring back deleted files on target server ?

### ISSUE THREAD

**Issue by sadathknorket** [minio/minio#20276]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I tried running ```mc mirror --remove --watch  myminio/restic-demo myaws/myminio```  if i make changes to source server it syncs it to destination but if I delete a file in destination I'm expecting it to bring it up

## Expected Behavior
It does not bring up the deleted files in aws s3 but it does if I stop the server and rerun the command 

## Current Behavior
without re-running the command it should be able to bring back the deleted files in aws s3

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
We cannot add --watch functionality to AWS S3 since it isn't a standard S3 API.

MC will never know what you did on AWS S3. As you saw it's behaving as expected.

This is out of the scope of mc.
