### ISSUE TITLE
Different certificates directory for differents '-config-dir' are not working.

### ISSUE THREAD

**Issue by dnp1** [minio/minio#2028]
## Expected behaviour

I set -config-dir=${APP_CONFIG_DIR}, then I suppose that ${APP_CONFIG_DIR}/certs should be the certificates directory of Minio.
## Actual behaviour

But It Always point to ${HOME_DIR}/.minio/certs
## Steps to reproduce the behaviour

Set your certificates in ~/.minio/certs (private.key and public.crt)
Put two minio servers working at same time passing a different config-dir to one of them.

Both of them will use the certificates in ~/.minio/certs
## System information

Windows 10 64-bit. Go 1.6.2

**Comment by harshavardhana** [comment]
Thanks @daniloanp - this is a bug. We will fix it.
