### ISSUE TITLE
Can not download file through Web UI

### ISSUE THREAD

**Issue by cataglyphis** [minio/minio#20284]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1. download file through web ui, but failed
![CleanShot 2024-08-18 at 20 54 56@2x](https://github.com/user-attachments/assets/14587936-def5-40ff-94f8-e8791431cc03)

## Your Environment

* Version used (`minio --version`): 2024-08-03
* Server setup and configuration:
* Operating System and version (`uname -a`): linux

```
❯ mc admin info minio
●  minio-0.minio-headless.minio.svc.cluster.local:9000
   Uptime: 18 minutes
   Version: 2024-08-03T04:33:23Z
   Network: 4/4 OK
   Drives: 1/1 OK
   Pool: 1

●  minio-1.minio-headless.minio.svc.cluster.local:9000
   Uptime: 18 minutes
   Version: 2024-08-03T04:33:23Z
   Network: 4/4 OK
   Drives: 1/1 OK
   Pool: 1

●  minio-2.minio-headless.minio.svc.cluster.local:9000
   Uptime: 19 minutes
   Version: 2024-08-03T04:33:23Z
   Network: 4/4 OK
   Drives: 1/1 OK
   Pool: 1

●  minio-3.minio-headless.minio.svc.cluster.local:9000
   Uptime: 19 minutes
   Version: 2024-08-03T04:33:23Z
   Network: 4/4 OK
   Drives: 1/1 OK
   Pool: 1

┌──────┬──────────────────────┬─────────────────────┬──────────────┐
│ Pool │ Drives Usage         │ Erasure stripe size │ Erasure sets │
│ 1st  │ 0.0% (total: 20 PiB) │ 4                   │ 1            │
└──────┴──────────────────────┴─────────────────────┴──────────────┘

60 GiB Used, 1 Bucket, 531 Objects
4 drives online, 0 drives offline, EC:2
```

**Comment by cataglyphis** [comment]
`mc admin trace` logs:
![CleanShot 2024-08-18 at 21 01 12@2x](https://github.com/user-attachments/assets/300ee478-1b22-450a-8f05-d7fc0baa589f)

**Comment by cataglyphis** [comment]
And use `mc cp` command to download file failed too.
```
❯ mc cp minio/forest/app/release/xxxxxx.exe ./
mc: <ERROR> Failed to copy `https://minio-api.xxx.com/forest/app/release/xxx.exe`. unexpected EOF
```

**Comment by harshavardhana** [comment]
there is some on-disk issue on the data, without much detailed debugging we can't possibly to see what might be wrong. 

what are your backend drives here? are they regular drives or some NFS volume?

**Comment by cataglyphis** [comment]
> there is some on-disk issue on the data, without much detailed debugging we can't possibly to see what might be wrong.
> 
> what are your backend drives here? are they regular drives or some NFS volume?

Backend driver is NFS volume.

**Comment by klauspost** [comment]
> Backend driver is NFS volume.

There is your problem. NFS is not a reliable storage backend, and usually presents problems when put under load. It could seem like your object is lost if you cannot read it back with mc.

**Comment by harshavardhana** [comment]
Yeah, distributed setup must not use NFS; NFS is not a persistent layer and should not be used. 

https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#storage-requirements read the recommendations for production setup.
