### ISSUE TITLE
MultipartUpload does not complete the upload

### ISSUE THREAD

**Issue by alexbran8** [minio/minio#20292]
## Expected Behavior
I am trying to create a multipartUpload, on MINIO (as storage), but using the `aws-sdk/client-s3`.
My current flow is:
- update start
- generate signed urls for each chunk
- update chunks
- finish update - complete multipart upload
Should see a file in the bucket.

## Current Behavior
Bucket shows file, not assembled.
![image](https://github.com/user-attachments/assets/44097f15-4960-4331-8b60-c7e3a489efcb)

## Steps to Reproduce (for bugs)
could be reproduced wusing the `aws-sdk-client/s3` and trying to upload multipart on MINIO

## Your Environment
```  
const command = new CompleteMultipartUploadCommand(params2);
const response = await s3Client.send(command);
```

Response from MultipartUploadCommand:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '17ED564D5A62B1F6',
    extendedRequestId: 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Bucket: 'bucket',
  ETag: '"147965304e4476e9e7ecdd7928736848-13"',
  Key: '18500568-uhd_3840_2160_30fps.mp4',
  Location: 'http://localhost:9000/bucket/18500568-uhd_3840_2160_30fps.mp4'
}
```

## QUESTIONS
- Is MIMIO compatible with `MultipartUpload`?
- Does MIMIO have this feature if trying to use `mimio client` and not `aws-sdk`?
- am I missing something in my code?

**Comment by marktheunissen** [comment]
@alexbran8 Your testing method is flawed, you cannot look at the contents of the file system on a MinIO server, those parts are for erasure coding and unrelated to multipart uploads.

The test you should do is whether you can download the file you just uploaded, and whether it's checksum matches what you uploaded.

Use the `mc` command line client as a helper in achieving the above.

**Comment by harshavardhana** [comment]
Let's close it @marktheunissen
