### ISSUE TITLE
The "Last Modified" attribute of an object does not change when modifying object tags.

### ISSUE THREAD

**Issue by daniel-leicht** [minio/minio#20299]
While scanning objects, I'm trying to see if there are any changes since my last scan and am using the "Last Modified" attribute to do so.

I added and removed some tags of several objects (via the server UI), and the "Last Modified" attribute did not change and kept its previous value.

This causes me to add another "get tags" query for each file to see if the tags have changed, when going over thousands of files this is a very big hit on the performance of the process.

Using the official docker version: RELEASE.2023-12-23T07-19-11Z (go1.21.5 linux/amd64)

**Comment by klauspost** [comment]
It is not my impression that [PutObjectTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html) will update "Last Modified". But I will confirm on AWS.

**Comment by klauspost** [comment]
```
λ mc stat mys3/klauspost/test.json
Name      : test.json
Date      : 2019-09-30 23:47:52 CEST
Size      : 369 B
ETag      : da31cf57c87a5c06abebc5a1f9722c7f
VersionID : null
Type      : file
Metadata  :
  Content-Type: application/json
  
λ mc tag set mys3/klauspost/test.json "abc=def"
Tags set for https://s3.amazonaws.com/klauspost/test.json

λ mc stat mys3/klauspost/test.json
Name      : test.json
Date      : 2019-09-30 23:47:52 CEST
Size      : 369 B
ETag      : da31cf57c87a5c06abebc5a1f9722c7f
VersionID : null
Type      : file
Metadata  :
  X-Amz-Tagging-Count: 1
  Content-Type       : application/json
```
