### ISSUE TITLE
Performance when uploading with object locking

### ISSUE THREAD

**Issue by azgms** [minio/minio#20300]
## NOTE
Degradation of performance when uploading to bucket with object locking. 

## Expected Behavior
Not sure if this should be filed as a bug as it is more an information request. 
Expected higher speeds on object locked bucket uploads.

## Current Behavior
root@ubuntu-pod:/mnt/storage# mc cp test internal/unlockbucket
/mnt/storage/test:                       4.92 GiB / 100.00 GiB ┃▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃ 1.09 GiB/s
root@ubuntu-pod:/mnt/storage# mc cp test internal/fullnodes   
/mnt/storage/test:                       542.81 MiB / 100.00 GiB ┃█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃ 205.25 MiB/s

## Possible Solution
Looking for any parameters or documentation to improve performance in this case

## Steps to Reproduce (for bugs)

1. Create standalone minio deployment. 1 server, 1 disk.
2. Create random file for testing - heaad -c 100G /dev/urandom > test
3. Configure mc alias 
4. Create bucket with object locking  - mc mb --with-lock lockedbucket
5. Create bucket with object locking  - mc mb unlockedbucket
6. Copy files to both buckets

## Context
Trying to achieve faster active-active replication between servers on different datacenters.

## Your Environment
Kubernetes environment.
Using minio helm chart version 5.2.0
10G native networking
Nvme storage
Tests were done with workloads running on the same kubernetes host

**Comment by klauspost** [comment]
For performance related questions, look into our [subscriptions](https://min.io/pricing).
