### ISSUE TITLE
How to set TLS cert path on kafka events

### ISSUE THREAD

**Issue by EKrol2** [minio/minio#20306]
### Discussed in https://github.com/minio/minio/discussions/20261

<div type='discussions-op-text'>

<sup>Originally posted by **EKrol2** August 14, 2024</sup>
Hi, Im trying to setup up a replication event to kafka from minio using TLS. However when I use the command, (or web interface) i get an error saying that the file cannot be found.

> mc: <ERROR> Unable to set 'notify_kafka:NAME brokers=BROKER_LIST topic=TOPIC_NAME tls=on client_tls_cert=PATH_TO_P12 client_tls_key=KEY' to server: error (NAME:kafka): open PATH_TO_P12: no such file or directory.

Im using the following command:
`mc admin config set az1/ notify_kafka:NAME brokers="BROKER_LIST" topic="TOPIC_NAME" tls="on" client_tls_cert="PATH_TO_P12" client_tls_key="KEY"`

I've tried with a path to the p12 file on my local machine, and have tried putting the cert in a bucket and providing that path, however both result in the same error.

I am using the minio cli from my local machine, so not the machine that minio runs on, should the certificates be added to the filesystem minio itself uses? And if so can i do this from the outside using the minio cli?

Thanks!</div>

**Comment by EKrol2** [comment]
Some additional info about the UI, see the attached image:
![screenshot-MinIO-interace](https://github.com/user-attachments/assets/4beeba55-0d80-4889-b232-d2787fa20215)

I would expect a button where I can upload a certificate in the interface for the client TLS cert field. However I can only fill in a path, resulting in the error above.



p.s. I have been told the MinIO deployment is kubernetes based.

**Comment by harshavardhana** [comment]
Closing the issue as this is not an issue but to be discussed at https://github.com/minio/minio/discussions/20261

**Comment by EKrol2** [comment]
Hi @harshavardhana , thanks for the response.

We do not have access to the kubernetes cluster / namespace where MinIO is deployed since we are merely a tenant and we are adding our own certificates all our kafka topics. So we cannot add a configmap that the MinIO deployment itself can use.

**Comment by harshavardhana** [comment]
> We do not have access to the kubernetes cluster / namespace where MinIO is deployed since we are merely a tenant and we are adding our own certificates all our kafka topics. So we cannot add a configmap that the MinIO deployment itself can use.

Then unfortunately it's not possible. You need access to add config maps to your tenants; if you don't even have that, we can do nothing.

**Comment by EKrol2** [comment]
Alright, thats unfortunate indeed. We will probably switch to SASL for the Minio - Kafka topics then.

Thank you for the follow up.
