### ISSUE TITLE
 when using the composeObject() method to merge files, show: "The specified key does not exist."

### ISSUE THREAD

**Issue by duchengying** [minio/minio#20307]
I uploaded a 10GB file to MinIO by splitting it into 5MB chunks. When attempting to merge the chunks, I receive the error message "The specified key does not exist." However, the file appears to have been uploaded successfully when checking the MinIO console. I'm not sure where the issue is.

**Comment by duchengying** [comment]
Language：JAVA
pom：
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>8.2.2</version>
        </dependency>
docker:
minio/minio:RELEASE.2022-01-04T07-41-07Z

**Comment by klauspost** [comment]
Upgrade. If that doesn't help, provide call traces for operations `mc admin trace -v ALIAS`.
