### ISSUE TITLE
Browser file download rename

### ISSUE THREAD

**Issue by Gordon-Gan-Jiang** [minio/minio#20303]
**Is your feature request related to a problem? Please describe.**

Download pre-signing of files renames the name of the downloaded file when accessed via a browser

**Describe the solution you'd like**

In the sdk, it is allowed to pass in parameters to set the response header, Content-Disposition, attachment; filename*=UTF-8''xxx.xx

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/998eb58a-6946-46c9-bbf3-e9c4fd079d72)

**Comment by harshavardhana** [comment]
You can override the content-disposition via `response-content-disposition` override, you can do that via any SDK or presigned URLs.
