### ISSUE TITLE
`Content-MD5` field/header seems to have no effect with a presigned POST url

### ISSUE THREAD

**Issue by MrCreosote** [minio/minio#20319]
When POSTing with a presigned URL to Minio, I am unable to cause the upload to fail via specifying a known bad `Content-MD5` field and header.

## Expected Behavior
When uploading a file to Minio with a presigned URL and specifying a known bad `Content-MD5`, the upload should fail.

## Current Behavior
The upload succeeds.

## Possible Solution
Possibly I'm doing something wrong - if so, if you could point it out that'd be great, as I'm a bit stumped.
Otherwise presumably Minio needs to check the MD5 of the file against the header / field.

## Steps to Reproduce (for bugs)
* Start Minio, with or without the `--compat` flag
```
MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ~/minio/RELEASE/2024-08-17T01-24-54Z/minio server ~/minio/data2 --compat
```
* Use the method of your choice to create a bucket called `test`
* Execute the following Python code, which follows [these directions](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html#generating-a-presigned-url-to-upload-a-file):
```python
$ ipython
Python 3.11.3 (main, Apr  5 2023, 14:14:40) [GCC 7.5.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from aiobotocore.session import get_session

In [2]: import requests

In [3]: sess = get_session()

In [4]: async with sess.create_client("s3", endpoint_url="http://localhost:9000"
   ...: , aws_access_key_id="admin", aws_secret_access_key="password") as client
   ...: :
   ...:     url = await client.generate_presigned_post(Bucket="test", Key="somef
   ...: ile", Fields={"Content-MD5": "garbage"}, Conditions=[{"Content-MD5": "ga
   ...: rbage"}])
   ...: 

In [5]: headers = {"Content-MD5": "garbage"}

In [6]: url
Out[6]: 
{'url': 'http://localhost:9000/test',
 'fields': {'Content-MD5': 'garbage',
  'key': 'somefile',
  'AWSAccessKeyId': 'admin',
  'policy': 'eyJleHBpcmF0aW9uIjogIjIwMjQtMDgtMjVUMDI6MTQ6MzZaIiwgImNvbmRpdGlvbnMiOiBbeyJDb250ZW50LU1ENSI6ICJnYXJiYWdlIn0sIHsiYnVja2V0IjogInRlc3QifSwgeyJrZXkiOiAic29tZWZpbGUifV19',
  'signature': '3/IO033FDA3TyAytqTUA+M5FcWM='}}

In [7]: with open("Dockerfile") as f:
   ...:     files = {"file": ("somefile", f)}
   ...:     res = requests.post(url["url"], headers=headers, data=url["fields"],
   ...:  files=files)
   ...: 

In [8]: res.text
Out[8]: ''

In [9]: res.status_code
Out[9]: 204
```
* Using the method of your choice, check that the file has been uploaded successfully.

## Context
I'm trying to upload files to Minio with a presigned URL and ensure file integrity as part of the upload via the `Content-MD5` header.

## Regression
I originally found this problem on a 2022 release of Minio so it seems not.

## Your Environment
* Version used (`minio --version`):
```
$ RELEASE/2024-08-17T01-24-54Z/minio --version
minio version RELEASE.2024-08-17T01-24-54Z (commit-id=72cff79c8a7cc59bccb591995e3c3ed6aa2f4cd5)
Runtime: go1.22.6 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration:
Just my laptop
* Operating System and version (`uname -a`):
Ubuntu 18.04 (yeah, I need to upgrade)
```
$ uname -a
Linux andbusinessisgood 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@MrCreosote please send `mc admin trace -v alias/` output when you make the API call.

**Comment by MrCreosote** [comment]
```
$ ~/minio/mc/RELEASE/2024-08-17T11-33-50Z/mc admin trace -v myminio/
localhost:9000 [REQUEST s3.PostPolicyBucket] [2024-08-25T07:21:04.641] [Client IP: 127.0.0.1]
localhost:9000 POST /test
localhost:9000 Proto: HTTP/1.1
localhost:9000 Host: localhost:9000
localhost:9000 Content-Length: 1891
localhost:9000 Content-Md5: garbage
localhost:9000 Content-Type: multipart/form-data; boundary=1c171a563a4b9fe6d3015f7d871ac779
localhost:9000 User-Agent: python-requests/2.32.3
localhost:9000 Accept: */*
localhost:9000 Accept-Encoding: gzip, deflate
localhost:9000 Connection: keep-alive
localhost:9000 <BLOB>
localhost:9000 [RESPONSE] [2024-08-25T07:21:04.666] [ Duration 24.597ms TTFB 0s ↑ 1.9 KiB  ↓ 0 B ]
localhost:9000 204 No Content
localhost:9000 Server: MinIO
localhost:9000 X-Amz-Request-Id: 17EEFE9EA4298C4C
localhost:9000 X-Content-Type-Options: nosniff
localhost:9000 X-Ratelimit-Remaining: 4853
localhost:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:9000 X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
localhost:9000 X-Ratelimit-Limit: 4853
localhost:9000 Content-Length: 0
localhost:9000 Content-Type: text/plain; charset=utf-8
localhost:9000 ETag: "40964dedca312a0b91d6aae5b3618a9e"
localhost:9000 Location: http://localhost:9000/test/somefile
localhost:9000 Vary: Origin,Accept-Encoding
localhost:9000 Accept-Ranges: bytes
localhost:9000 X-Xss-Protection: 1; mode=block
localhost:9000 <BLOB>
localhost:9000 
```

**Comment by harshavardhana** [comment]
@MrCreosote okay so in post form uploads you need to specify content-md5 as part of the form upload not as part of the http header.

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

**Comment by MrCreosote** [comment]
I am specifying it as part of the form upload:
```
In [6]: url
Out[6]: 
{'url': 'http://localhost:9000/test',
 'fields': {'Content-MD5': 'garbage',
```

```
 res = requests.post(url["url"], headers=headers, data=url["fields"],
   ...:  files=files)
```

**Comment by harshavardhana** [comment]
> localhost:9000 Content-Md5: garbage

no you are not.

**Comment by MrCreosote** [comment]
I don't quite understand how that shows I'm not sending `Content-MD5` in a form entry. Assuming I'm interpreting the trace correctly it does show I'm sending it as a header, which I am, but I'm *also* sending it as a field in the ipython code above.

Anyway, to hopefully alleviate all confusion, here's the `curl` equivalent to the python command above, with and without the `Content-MD5` header, but always with a `Content-MD5` form field. In both cases the file upload succeeds.

Maybe I'm sending the form field incorrectly (although I don't see how, I'm sending it the same way as the policy and signature), but I'm definitely sending the `Content-MD5` form field unless I'm very confused indeed.

With header:
```
$ cat curltest
#!/bin/sh

curl -v \
-H "Content-MD5: garbage" \
-F "Content-MD5=garbage" \
-F "key=somefile" \
-F "AWSAccessKeyid=admin" \
-F "policy=eyJleHBpcmF0aW9uIjogIjIwMjQtMDgtMjVUMjM6MDM6NDRaIiwgImNvbmRpdGlvbnMiOiBbeyJDb250ZW50LU1ENSI6ICJnYXJiYWdlIn0sIHsiYnVja2V0IjogInRlc3QifSwgeyJrZXkiOiAic29tZWZpbGUifV19" \
-F "signature=96sGtEVza91wF1dAGYN/Jv+oa9E=" \
-F file=@somefile \
http://localhost:9000/test

$ ./curltest 2>&1 | grep 204
< HTTP/1.1 204 No Content
```

Without header
```
~$ cat curltestnoheader 
#!/bin/sh

curl -v \
-F "Content-MD5=garbage" \
-F "key=somefile" \
-F "AWSAccessKeyid=admin" \
-F "policy=eyJleHBpcmF0aW9uIjogIjIwMjQtMDgtMjVUMjM6MDM6NDRaIiwgImNvbmRpdGlvbnMiOiBbeyJDb250ZW50LU1ENSI6ICJnYXJiYWdlIn0sIHsiYnVja2V0IjogInRlc3QifSwgeyJrZXkiOiAic29tZWZpbGUifV19" \
-F "signature=96sGtEVza91wF1dAGYN/Jv+oa9E=" \
-F file=@somefile \
http://localhost:9000/test

$ ./curltestnoheader 2>&1 | grep 204
< HTTP/1.1 204 No Content
```

**Comment by MrCreosote** [comment]
Here's the trace from the no header case:
```
$ ~/minio/mc/RELEASE/2024-08-17T11-33-Z/mc admin trace -v myminio/
localhost:9000 [REQUEST s3.PostPolicyBucket] [2024-08-25T15:36:39.955] [Client IP: 127.0.0.1]
localhost:9000 POST /test
localhost:9000 Proto: HTTP/1.1
localhost:9000 Host: localhost:9000
localhost:9000 Expect: 100-continue
localhost:9000 User-Agent: curl/7.58.0
localhost:9000 Accept: */*
localhost:9000 Content-Length: 1052
localhost:9000 Content-Type: multipart/form-data; boundary=------------------------948d075df8fe1678
localhost:9000 <BLOB>
localhost:9000 [RESPONSE] [2024-08-25T15:36:39.985] [ Duration 29.875ms TTFB 0s ↑ 1.1 KiB  ↓ 0 B ]
localhost:9000 204 No Content
localhost:9000 Accept-Ranges: bytes
localhost:9000 Content-Length: 0
localhost:9000 Location: http://localhost:9000/test/somefile
localhost:9000 X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
localhost:9000 X-Content-Type-Options: nosniff
localhost:9000 X-Ratelimit-Limit: 5250
localhost:9000 X-Ratelimit-Remaining: 5250
localhost:9000 ETag: "fea24acb1cbb3731146b06d0c6707cd4"
localhost:9000 Server: MinIO
localhost:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:9000 Vary: Origin,Accept-Encoding
localhost:9000 X-Amz-Request-Id: 17EF19A9EEF2DA2F
localhost:9000 X-Xss-Protection: 1; mode=block
localhost:9000 <BLOB>
localhost:9000 
```

**Comment by harshavardhana** [comment]
Will verify this one more time and paste the right way to do this.

**Comment by harshavardhana** [comment]
> -F "Content-MD5=garbage" \

Found that we do not validate this instead, we validate `x-amz-checksum-crc32` which is a better alternative here. 

But we should be able to support it // cc @marktheunissen

**Comment by MrCreosote** [comment]
Forgive my ignorance, but why is crc32 a better alternative here (other than it's already implemented, obviously)? I naively assumed md5s would come for free server side since they're already calculated for the e-tag (since the unsigned post isn't multipart). 

I'm aware that md5s are cryptographically insecure but AFAIK are still reasonable for file integrity checks.

**Comment by harshavardhana** [comment]
> Forgive my ignorance, but why is crc32 a better alternative here (other than it's already implemented, obviously)? I naively assumed md5s would come for free server side since they're already calculated for the e-tag (since the unsigned post isn't multipart).

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html for your knowledge why these are better alternatives.

**Comment by MrCreosote** [comment]
Yes, I'm aware of that page but AFAICT it just lists the 5 checksum options (including md5) but doesn't provide any rationale as to preferring one over another.

Edit: The only reason I chose MD5 was, given the above, it presumably didn't incur any extra computation costs server side

**Comment by harshavardhana** [comment]
> Edit: The only reason I chose MD5 was, given the above, it presumably didn't incur any extra computation costs server side

Of course it does, we have to recompute what you sent in the payload. md5sum is CPU heavy and terrible in performance.

**Comment by MrCreosote** [comment]
But you already have to compute it for the e-tag surely?

Edit: Oh, that only applies in `--compat` mode.

**Comment by harshavardhana** [comment]
> But you already have to compute it for the e-tag surely?
> 
> Edit: Oh, that only applies in `--compat` mode.

No --compat is default and Content-Md5 it is not needed when you have TLS enabled on the transport layer.

**Comment by harshavardhana** [comment]
ETag is not always md5sum https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html read about the ETag behavior

**Comment by marktheunissen** [comment]
@harshavardhana I'm a little bit lost now... should I work on implementing support for the Content-MD5 header, even though it generates extra server load?

**Comment by harshavardhana** [comment]
> @harshavardhana I'm a little bit lost now... should I work on implementing support for the Content-MD5 header, even though it generates extra server load?

in this case for completeness its okay to add, this is a hardly used API as such @marktheunissen
