### ISSUE TITLE
Bug: If-Match and If-Unmodified-Since together in the HeadObjectRequest

### ISSUE THREAD

**Issue by T-TRz879** [minio/minio#20321]
**HeadObject** supports carrying If Match and If Unmodified Sense in requests. If these two parameters are used together, there may be issues in Minio
I upload a object, below is object info
```
{
  AcceptRanges: "bytes",
  ContentLength: 100,
  ContentType: "binary/octet-stream",
  ETag: "\"62ca1808bf6dd0fb37fe0f461f04939e\"",
  LastModified: 2024-08-24 02:34:39 +0000 UTC
}
```
below is my code
```go
func TestHeadObjectMinio(t *testing.T) {
	timeSince1 := time.Date(2024, 8, 24, 10, 34, 38, 0, time.Local)
	timeSince2 := time.Date(2024, 8, 24, 10, 34, 39, 0, time.Local)
	timeSince3 := time.Date(2024, 8, 24, 10, 34, 40, 0, time.Local)
	fmt.Println(timeSince1)
	fmt.Println(timeSince2)
	fmt.Println(timeSince3)
	if res, err := v1Cli.HeadObject(
		&s3.HeadObjectInput{
			Bucket:            aws.String(bucket),
			Key:               aws.String(key),
			IfMatch:           aws.String(`62ca1808bf6dd0fb37fe0f461f04939e`),
			IfUnmodifiedSince: aws.Time(timeSince1),
		}); err != nil {
		assert.Fail(t, err.Error())
	} else {
		fmt.Println(res)
	}
}
```

## Expected Behavior

minio should return 200 to me.

## Current Behavior

minio should return 412 to me.

## Possible Solution

I searched for the usage of this HTTP header in [RFC-9110](https://www.rfc-editor.org/rfc/rfc9110.html#field.if-match). 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/5e9ac4dc-1e3c-4239-837e-0be416155ca3">

## Steps to Reproduce (for bugs)

1. PutObject to minio
2. HeadObject from minio with request If-Match and If-Unmodified-Since, set If-Match=object.ETag, set If-Unmodified-Since=the time before object.LastModified

## Context

If it's a real bug, I can deal with problem, Can you leave this issue to me to handle?

## Regression

No

## Your Environment

* Version used (`minio --version`): RELEASE.2023-11-15T20-43-25Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): `Linux pc 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> I searched for the usage of this HTTP header in [RFC-9110](https://www.rfc-editor.org/rfc/rfc9110.html#field.if-match).

Absolutely this must be fixed.

**Comment by harshavardhana** [comment]
We should implement and follow this

```
       --if-match (string)
          Return  the  object only if its entity tag (ETag) is the same as the
          one specified; otherwise, return a 412 (precondition failed) error.

          If both of the If-Match and If-Unmodified-Since headers are  present
          in the request as follows:

          o If-Match condition evaluates to true , and;

          o If-Unmodified-Since condition evaluates to false ;

          Then Amazon S3 returns 200 OK and the data requested.

          For more information about conditional requests, see RFC 7232 .

       --if-modified-since (timestamp)
          Return  the  object only if it has been modified since the specified
          time; otherwise, return a 304 (not modified) error.

          If both of  the  If-None-Match  and  If-Modified-Since  headers  are
          present in the request as follows:

          o If-None-Match condition evaluates to false , and;

          o If-Modified-Since condition evaluates to true ;

          Then Amazon S3 returns the 304 Not Modified response code.

          For more information about conditional requests, see RFC 7232 .

       --if-none-match (string)
          Return  the  object  only if its entity tag (ETag) is different from
          the one specified; otherwise, return a 304 (not modified) error.

          If both of  the  If-None-Match  and  If-Modified-Since  headers  are
          present in the request as follows:

          o If-None-Match condition evaluates to false , and;

          o If-Modified-Since condition evaluates to true ;

          Then Amazon S3 returns the 304 Not Modified response code.

          For more information about conditional requests, see RFC 7232 .

       --if-unmodified-since (timestamp)
          Return  the object only if it has not been modified since the speci-
          fied time; otherwise, return a 412 (precondition failed) error.

          If both of the If-Match and If-Unmodified-Since headers are  present
          in the request as follows:

          o If-Match condition evaluates to true , and;

          o If-Unmodified-Since condition evaluates to false ;

          Then Amazon S3 returns 200 OK and the data requested.

          For more information about conditional requests, see RFC 7232 .
```

**Comment by T-TRz879** [comment]
if `if-unmodified-since` and `if-match` use together, `if-unmodified-since` should be ignored. Is my understanding correct?
(The above content is from the S3 document, but I didn't understand its meaning, so I went to see the definition of RFC)
```
 --if-unmodified-since (timestamp)
          If both of the If-Match and If-Unmodified-Since headers are  present
          in the request as follows:
          o If-Match condition evaluates to true , and;
          o If-Unmodified-Since condition evaluates to false ;
          Then Amazon S3 returns 200 OK and the data requested.
```

**Comment by harshavardhana** [comment]
> (The above content is from the S3 document, but I didn't understand its meaning, so I went to see the definition of RFC)

We must follow AWS S3 documentation not HTTP RFC, some times they diverge.

**Comment by T-TRz879** [comment]
okay.

**Comment by T-TRz879** [comment]
I have some questions
1. The current code complies with the specifications in the S3 documentation.
2. I tried using AWS S3 and found that if both `If-Match` and `If-Unmodified` are specified, then regardless of `If-Unmodified` and object The relationship between LastModified is only related to the results of `If-Match`

You can try AWS S3 (I'm a bit confused at the moment)

**Comment by harshavardhana** [comment]
> * The current code complies with the specifications in the S3 documentation.

@T-TRz879 so we just comply with the AWS S3 behavior.

**Comment by T-TRz879** [comment]
Hi, it's high time to close this issue.
