### ISSUE TITLE
Prometheus on single node minio is not collecting any data

### ISSUE THREAD

**Issue by hsafe** [minio/minio#20328]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
I have a single instance of minio along the prometheus. both services are running fine and in service. However following instructions in adding the minio and configuring prometheus to use the metrics api is not working. 

## Current Behavior
As said earlier I have both working services live. I tried to run:
$ mc admin prometheus generate local node
Then copied and pasted the scrape block in prometheus and started the service. Trying to see what happens I run:
$ mc admin trace -v -a TARGET

It prints out some errors like:

localhost:9000 [REQUEST handler.MetricsAuth] [2024-08-26T14:59:10.714] [Client IP: 127.0.0.1]
localhost:9000 GET /minio/v2/metrics/node
localhost:9000 Proto: HTTP/1.1
localhost:9000 Host: localhost:9000
localhost:9000 X-Prometheus-Scrape-Timeout-Seconds: 10
localhost:9000 Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
localhost:9000 Accept-Encoding: gzip
localhost:9000 Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDg3ODI3MTAzNn0.Ben4JSNBMo3wwJPgQmO26g_qt1-HUZckUxkmY-7Nb9MilNbi0YxWMgdZ0PKcXRWBm6wCZF3ErO65Pe-uPTPaCQ
localhost:9000 Content-Length: 0
localhost:9000 User-Agent: Prometheus/2.31.2+ds1
localhost:9000 <BLOB>
localhost:9000 [RESPONSE] [2024-08-26T14:59:10.714] [ Duration 250µs TTFB 246.508µs ↑ 104 B  ↓ 249 B ]
localhost:9000 403 Forbidden
localhost:9000 Vary: Origin
localhost:9000 X-Amz-Request-Id: 17EF43D1CF7B26EF
localhost:9000 X-Content-Type-Options: nosniff
localhost:9000 Accept-Ranges: bytes
localhost:9000 Content-Length: 249
localhost:9000 Content-Type: application/json
localhost:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:9000 Server: MinIO
localhost:9000 X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
localhost:9000 X-Xss-Protection: 1; mode=block
localhost:9000 {"Code":"AccessDenied","Message":"Access Denied. (Authentication failed, check your access credentials)","Resource":"/minio/v2/metrics/node","RequestId":"17EF43D1CF7B26EF","HostId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8"}

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-05-28T17-19-04Z (commit-id=f79a4ef4d0dc3e6562cad0d1d1db674bc8c75531)
Runtime: go1.22.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

* Server setup and configuration: 
* Operating System and version (`uname -a`):ubuntu22. Linux 5.15.0-118-generic

Appreciate to help me fix this. Note please I have had success in a prod cluster before adding to the same prometheus and yet this single node seems really a pain ... I did not know what could be the cause until found the mc admin trace that printed the error regarding access is denied....All the other specific setting in minio is generic and out of the box ...nothing fancy or complex

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): minio version RELEASE.2024-05-28T17-19-04Z (commit-id=f79a4ef4d0dc3e6562cad0d1d1db674bc8c75531)

Please upgrade the setup first and then report issues.

**Comment by hsafe** [comment]
Hello again it is upgraded to :
minio version RELEASE.2024-08-26T15-33-07Z (commit-id=1c4d28d7af0373cde810703839a179739dbe6f34)
Runtime: go1.22.6 linux/amd64
But still I get the error:

> localhost:9000 GET /minio/v2/metrics/node
> localhost:9000 Proto: HTTP/1.1
> localhost:9000 Host: localhost:9000
> localhost:9000 Accept-Encoding: gzip
> localhost:9000 Authorization: Bearer <TOKEN>
> localhost:9000 Content-Length: 0
> localhost:9000 User-Agent: Prometheus/2.31.2+ds1
> localhost:9000 X-Prometheus-Scrape-Timeout-Seconds: 10
> localhost:9000 Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
> localhost:9000 <BLOB>
> localhost:9000 [RESPONSE] [2024-08-27T09:30:00.714] [ Duration 212µs TTFB 209.055µs ↑ 104 B  ↓ 249 B ]
> localhost:9000 403 Forbidden
> localhost:9000 Accept-Ranges: bytes
> localhost:9000 Vary: Origin
> localhost:9000 X-Amz-Request-Id: 17EF806FF90FF093
> localhost:9000 X-Xss-Protection: 1; mode=block
> localhost:9000 X-Content-Type-Options: nosniff
> localhost:9000 Content-Length: 249
> localhost:9000 Content-Type: application/json
> localhost:9000 Server: MinIO
> localhost:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
> localhost:9000 X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
> localhost:9000 {"Code":"AccessDenied","Message":"Access Denied. (Authentication failed, check your access credentials)","Resource":"/minio/v2/metrics/node","RequestId":"17EF806FF90FF093","HostId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8"}
> 
>

**Comment by harshavardhana** [comment]
> localhost:9000 Authorization: Bearer

where is your token?

**Comment by harshavardhana** [comment]
Works perfectly fine for me 

```
~ minio server ~/test
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: DEVELOPMENT.2024-08-28T15-32-18Z (go1.22.6 linux/amd64)

API: http://10.0.0.185:9000  http://172.17.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000 
   RootUser: minioadmin 
   RootPass: minioadmin 

WebUI: http://10.0.0.185:41539 http://172.17.0.1:41539 http://172.19.0.1:41539 http://127.0.0.1:41539    
   RootUser: minioadmin 
   RootPass: minioadmin 

CLI: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
   $ mc alias set 'myminio' 'http://10.0.0.185:9000' 'minioadmin' 'minioadmin'

```

```
mc admin prometheus generate myminio node
scrape_configs:
- job_name: minio-job-node
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDg3ODQ2ODk4N30.3seBnUyUdmvq2qjs7wjzXD0t40lcL1DEjamVgYsHdTg1gyWt9ygjx3oJm72YUfxjt2enb-BjZkQ697ZMxh1KeA
  metrics_path: /minio/v2/metrics/node
  scheme: http
  static_configs:
  - targets: ['10.0.0.185:9000']
```

```
~ curl -I -s -H "Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDg3ODQ2ODk4N30.3seBnUyUdmvq2qjs7wjzXD0t40lcL1DEjamVgYsHdTg1gyWt9ygjx3oJm72YUfxjt2enb-BjZkQ697ZMxh1KeA" http://localhost:9000/minio/v2/metrics/node
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8; escaping=values
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
X-Amz-Request-Id: 17EFF7385B33FA4A
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Wed, 28 Aug 2024 18:16:43 GMT
```
