### ISSUE TITLE
Distributed minio Error Logs

### ISSUE THREAD

**Issue by Gordon-Gan-Jiang** [minio/minio#20332]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Current Behavior

Using the MC tool, the execution command is "mc cp -r xx alias/xxx", and an error is reported. The log is as follows,

{
  "error": {
    "cause": {
      "message": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
      "error": {
        "Message": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
        "RequestID": "17ED19999B3324C7",
        "Server": "nginx",
        "Resource": "/wpspackage/f72b00c1b11b9e8ae65c136b1c23f01f/eFPz1821140357195366400/SRWr1825445435637104640/uBDg1825475480103550976/wnBP1825475480103550977/myCI1825475480103550978/WBRK1825475480103550979/libwpsapi.so",
        "HostID": "8b972e2b44c13fa81f2b77b7dfd60988e5b1de1563db518b150fe16aa431fcfd",
        "Code": "NoSuchUpload",
        "BucketName": "wpspackage",
        "Region": "",
        "Key": "f72b00c1b11b9e8ae65c136b1c23f01f/eFPz1821140357195366400/SRWr1825445435637104640/uBDg1825475480103550976/wnBP1825475480103550977/myCI1825475480103550978/WBRK1825475480103550979/libwpsapi.so"
      }
    },
    "message": "Failed to copy `/build/data/func_master_pc_v12_personal_AI_240807_branch/x64_N/Build/Release/WPSOffice/office6/libwpsapi.so`.",
    "type": "error"
  },
  "status": "error"
}

## Steps to Reproduce (for bugs)

Verbose logs

Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: Host: wcos.minio7.kingsoft.com:9000
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: Error: ws write: write tcp 10.23.21.19:9000->10.23.21.20:50220: i/o timeout (*fmt.wrapError)
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        6: internal/logger/logger.go:268:logger.LogIf()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        5: internal/grid/connection.go:51:grid.gridLogIf()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        4: internal/grid/connection.go:1133:grid.(*Connection).handleMessages()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        3: internal/grid/connection.go:831:grid.(*Connection).handleIncoming()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        2: internal/grid/manager.go:225:cmd.registerDistErasureRouters.(*Manager).Handler.func1()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        1: net/http/server.go:2166:http.HandlerFunc.ServeHTTP()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: API: github.com/minio/minio/cmd.registerDistErasureRouters.(*Manager).Handler.func1
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: Time: 05:03:11 UTC 08/14/2024
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: DeploymentID: fdc28805-87f9-4340-8ffb-3153941c4b87
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: RequestID: 17EB2694B44BA3F3
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: RemoteHost: 10.23.21.20
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: Host: wcos.minio7.kingsoft.com:9000
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]: Error: ws write: write tcp 10.23.21.19:9000->10.23.21.20:50220: i/o timeout (*fmt.wrapError)
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        6: internal/logger/logger.go:268:logger.LogIf()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        5: internal/grid/connection.go:51:grid.gridLogIf()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        4: internal/grid/connection.go:1133:grid.(*Connection).handleMessages()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        3: internal/grid/connection.go:831:grid.(*Connection).handleIncoming()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        2: internal/grid/manager.go:225:cmd.registerDistErasureRouters.(*Manager).Handler.func1()
Aug 14 13:03:11 wcos.minio7.kingsoft.com minio[3033]:        1: net/http/server.go:2166:http.HandlerFunc.ServeHTTP()
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]: API: SYSTEM.grid
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]: Time: 02:48:07 UTC 08/19/2024
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]: DeploymentID: fdc28805-87f9-4340-8ffb-3153941c4b87
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]: Error: host http://wcos.minio5.kingsoft.com:9000 last pong too old (44.462s); disconnecting (*errors.errorString)
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]:        5: internal/logger/logger.go:268:logger.LogIf()
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]:        4: internal/grid/connection.go:51:grid.gridLogIf()
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]:        3: internal/grid/connection.go:1073:grid.(*Connection).handleMessages()
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]:        2: internal/grid/connection.go:731:grid.(*Connection).connect()
Aug 19 10:48:07 wcos.minio7.kingsoft.com minio[3033]:        1: internal/grid/connection.go:260:grid.newConnection.func1()

## Context

mc tool error and minIo service error log, are they related?

## Your Environment

* Version used (`minio --version`): Version: 2024-05-10T01:41:38Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by dormanze** [comment]
You can try
```
mc cp -r xx alias/xxx --disable-multipart
```

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): Version: 2024-05-10T01:41:38Z

Please upgrade and report issues @Gordon-Gan-Jiang

**Comment by Gordon-Gan-Jiang** [comment]
> > * 所用版本 ( `minio --version`)：版本：2024-05-10T01:41:38Z
> 
> 请升级并报告问题@Gordon-Gan-Jiang

OK

**Comment by Gordon-Gan-Jiang** [comment]
> 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3ag3jpquii3of 密码：changeme 当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。



> 要解决您的问题，请尝试下载这个修复程序，我在另一个问题中看到它， [https://app.mediafire.com/3ag3jpquii3](https://app.mediafire.com/3ag3jpquii3of) 的密码：changeme 当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。

Which issue solves this problem? Could you please send me a link?

**Comment by klauspost** [comment]
@Gordon-Gan-Jiang That is not for us to figure out. But we don't want to go hunting for bugs we already fixed. Therefore community only receives support on latest version.
