### ISSUE TITLE
Unable to Configure LDAP Authentication on MINIO

### ISSUE THREAD

**Issue by mgamarra** [minio/minio#20340]
I am unable to configure LDAP authentication on MINIO. Despite setting up the LDAP parameters through both environment variables and the Console UI, the user search functionality does not work as expected. The configuration seems to be correctly set, but the LDAP integration fails silently without providing any error messages in the logs. This issue prevents the integration of MINIO with our existing LDAP directory for user authentication.

## Expected Behavior

MINIO should successfully authenticate users via LDAP.

## Current Behavior

Even after configuring LDAP settings through environment variables or the Console UI, the user search against LDAP does not work, and no errors are logged.

## Steps to Reproduce

1. Configure LDAP authentication using either environment variables or the Console UI:

MINIO_IDENTITY_LDAP_SERVER_ADDR="<<host>>:389"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="CN=xxx,OU=xxx,OU=xxx,OU=xxx,DC=xxx,DC=xxx,DC=xxx"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="XXXXXXx"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="DC=xxx,DC=xxx,DC=xxx"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(&(objectCategory=user)(sAMAccountName=%s))"
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY="on"
MINIO_IDENTITY_LDAP_SERVER_INSECURE="on"
MINIO_IDENTITY_LDAP_SERVER_STARTTLS="off"

3. Restart the MINIO instance and attempt to search for a valid user registered in LDAP.
4. In the “Identity/LDAP” section, go to the “Entities” tab and try searching for users. 
## Context

I need to configure LDAP authentication in MINIO to integrate it with our existing user directory.
## Your Environment

* Version used (`minio --version`): inio version RELEASE.2024-08-03T04-33-23Z (commit-id=6efb56851c40da88d1ca15112e2d686a4ecec6b3)
* Server setup and configuration:
* Operating System and version (`uname -a`): Rocky Linux 5.14.0-427.28.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 31 15:28:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
We test with LDAP daily @mgamarra this is mostly a configuration issue.

So to start with provide output for `ldapsearch` using the base_dn credentials and user-dn lookups for us.

**Comment by mgamarra** [comment]
Thank you for your response.
Below is a screenshot of the query executed with ldapsearch.
I have hidden some information, but the command executed was the one below with the same information tested on MINIO.

ldapsearch -x -H ldap://xxx:389  -D "CN=xxxx" -w "xxx"  -b "DC=xxx" "(&(objectCategory=user)(sAMAccountName=vinicius.santos))" userPrincipalName cn objectGUID, sAMAccountName
![image](https://github.com/user-attachments/assets/e4281a42-2157-4873-a170-7cfc59fb8ddd)

**Comment by harshavardhana** [comment]
why is the DN base64 encoded in the response? and also cn: ? and is your LDAP clearly on TLS? you are not using ldaps here and yet you have told MinIO to use TLS based for your LDAP endpoint.

**Comment by harshavardhana** [comment]
> 6\. In the “Identity/LDAP” section, go to the “Entities” tab and try searching for users.

We do not allow searching to external entity, once you have LDAP configured you need to add relevant policy mappings for users that you want access on MinIO. 

Our UI is not an arbitrary search UI for your LDAP. 

https://min.io/docs/minio/linux/reference/minio-mc/mc-idp-ldap-policy-attach.html#command-mc.idp.ldap.policy.attach

You need to attach relevant users to MinIO to register their access.

**Comment by vinibodruch** [comment]
Thank you for the clarification. We now understand how the LDAP assignment works and successfully managed to assign users to the LDAP group.

However, we found the process of searching for entities a bit confusing, which might have led us to believe that the integration wasn't working initially.

To help others who might face similar issues, we discovered that the LDAP was correctly connected by using the following command:

```
# mc idp ldap policy attach minio01/ consoleAdmin --group='cn=GRPXXXXXXXXX' --debug 
Attached Policies: [consoleAdmin]
To Group: cn=GRPXXXXXXXXX
#
# mc idp ldap policy entities --group='GRPXXXXXXXXX' minio01
Query time: 2024-08-29T15:21:50Z
Group -> Policy Mappings:
  Group: cn=GRPXXXXXXXXX
    Policies:
      consoleAdmin
```

This command confirmed that the group and its policies were correctly mapped. Hopefully, this will assist others in verifying their LDAP configurations more confidently.

**Comment by harshavardhana** [comment]
> To help others who might face similar issues, we discovered that the LDAP was correctly connected by using the following command:

That's not the correct command to use 

```
mc idp ldp info minio01/
```

Shows if the IDP is configured and if its online

**Comment by harshavardhana** [comment]
Like this

```
~ mc idp ldap info myminio/
╭─────────────────────────────────────────────────────────────────╮
│                enable: on                                       │
│  group_search_base_dn: ou=swengg,dc=min,dc=io                   │
│   group_search_filter: (&(objectclass=groupOfNames)(member=%d)) │
│        lookup_bind_dn: cn=admin,dc=min,dc=io                    │
│           server_addr: localhost:1389                           │
│       server_insecure: on                                       │
│user_dn_search_base_dn: dc=min,dc=io                             │
│ user_dn_search_filter: (uid=%s)                                 │
╰─────────────────────────────────────────────────────────────────╯
```

```
~ mc idp ldap ls myminio/
╭─────────────────────────╮
│ On?    Name     RoleARN │
│ 🟢   (default)          │
╰─────────────────────────╯
```
