### ISSUE TITLE
Remove all references to x-minio-date

### ISSUE THREAD

**Issue by awwalker** [minio/minio#2034]
There is no good reason to have a different date format from x-amz-date or Date.

**Comment by harshavardhana** [comment]
> There is no good reason to have a different date format from x-amz-date or Date.

x-minio-date is a date header used by the web jsonrpc it has a clear purpose, generic handlers validate this date header to look for valid json rpc/web browser requests.

**Comment by awwalker** [comment]
My misunderstanding, thanks for explaining.
