### ISSUE TITLE
server returns "volume not found" when user doesn't have write permissions on the disk(s)

### ISSUE THREAD

**Issue by krisis** [minio/minio#2035]
## Expected behaviour

When minio server doesn't have permission on disks it is run with it should return "Permission denied" as opposed to "volume not found".
## Actual behaviour

When minio server is run for the first time on disks, the user it is run as, doesn't have permissions for, it returns "volume not found" error. 
## Steps to reproduce the behaviour
- Create enough disks for using with minio as root (say).
- Run minio server with those disks as a different user.
## Minio version
- commit id - 57bc08c
## System information

`Linux 4.4.0-24-generic #43-Ubuntu SMP`

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by harshavardhana** [comment]
> Please update the timeline for the fix.

Patch sent already.

**Comment by harshavardhana** [comment]
July 1st.
