### ISSUE TITLE
Minio node status is OK  just after umount. hard disk is not replaced yet.

### ISSUE THREAD

**Issue by ufo2243** [minio/minio#20362]
## NOTE
Minio node status is OK  just after umount. hard disk is not replaced yet.

```
   Uptime: 1 month
   Version: 2023-11-20T22:40:07Z
   Network: 10/10 OK
   Drives: 36/36 OK
   Pool: 1
```
minio create a minio folder in the mountpoint path  just after the umounting.

## Expected Behavior
Drives status should stay offline. after the hard disk is replaced. 

## Current Behavior
Drives is online. before the hard disk is replaced

## Steps to Reproduce (for bugs)
1.  Drivers is offline
2.  umount the disk

## Context
check if any more data is writing to the minio folder. i want to make sure no more data is writing to the system disk after umount and before the hard disk is replaced.

## Regression
It's probably not a regression

## Your Environment
minio version RELEASE.2023-11-20T22-40-07Z (commit-id=f56a182b719cb262e0628ef3f544371ea8842551)
Runtime: go1.21.4 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

Pools:
   1st, Erasure sets: 12, Drives per erasure set: 15
   2nd, Erasure sets: 12, Drives per erasure set: 15

linux 5.10.0-7.el8.x86_64

**Comment by jiuker** [comment]
Please upgrade your setup

**Comment by harshavardhana** [comment]
This has been fixed already
