### ISSUE TITLE
The number of files seen on the Minio web interface does not match the number of files uploaded, and the interface calculates whether there is a delay

### ISSUE THREAD

**Issue by smallemployees** [minio/minio#20378]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

I am currently able to download the files I uploaded normally, but the statistical data on the page is inaccurate
## Current Behavior

I uploaded 500 files using MC, but the number of bucket objects displayed on the web interface is 200
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): 2023-03-22T06-36-24Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): 2023-03-22T06-36-24Z

Upgrade first.
