### ISSUE TITLE
Broken error log message: "*errors.errorString"

### ISSUE THREAD

**Issue by tmohme** [minio/minio#20371]
The usefulness of the log message suffers from incorrect argument replacement.

## Expected Behavior
The error log message should inform humans (and machines) clear and succinct about important conditions that need action.

## Current Behavior
Currently, the log messages _hides_ the condition and makes it really hard to find it out:
You have to examine the whole line, extract the "source" array and guess, which line in the source-code produced the error, what the actual condition is and what to do about it.

## Possible Solution
Fix the message preparation.

## Steps to Reproduce (for bugs)
1. Given a running tenant in K8s - in this particular case with two pools
2. do a restart on the StatefulSet of one pool

The full error message is:
```
  {
    "deploymentid": "fc964bf6-a0df-4bc8-b7f7-ddb4e117deec",
    "level": "ERROR",
    "time": "2024-09-03T07:53:04.229015945Z",
    "api": {
      "name": "SYSTEM.storage",
      "args": {
        "bucket": "5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5",
        "object": "5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"
      }
    },
    "remotehost": "5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5",
    "error": {
      "message": "*errors.errorString",
      "source": [
        "internal/logger/logger.go:268:logger.LogIf()",
        "cmd/logging.go:156:cmd.storageLogIf()",
        "cmd/erasure-server-pool-decom.go:474:cmd.poolMeta.save()",
        "cmd/erasure-server-pool-decom.go:518:cmd.(*erasureServerPools).Init()",
        "cmd/erasure-server-pool.go:204:cmd.newErasureServerPools.func5()",
        "cmd/server-main.go:561:cmd.bootstrapTrace()",
        "cmd/erasure-server-pool.go:203:cmd.newErasureServerPools()",
        "cmd/server-main.go:1166:cmd.newObjectLayer()",
        "cmd/server-main.go:915:cmd.serverMain.func11()",
        "cmd/server-main.go:561:cmd.bootstrapTrace()",
        "cmd/server-main.go:913:cmd.serverMain()"
      ]
    }
  }
  ```

## Context
We are going to manage multiple clusters and strive for complete automation.
Therefore we need direct, succinct information in the log messages and can't effort to manually dig up the source-code, look what it does and what might have cause the error message in question.
Having unclear error messages in the logs massively hinders automation.

## Regression
No

## Your Environment
* Version used (`minio --version`): RELEASE.2024-08-26T15-33-07Z
* Server setup and configuration: K8s
* Operating System and version (`uname -a`): Linux minio-tenant-minio01-0 6.6.43-talos #1 SMP Mon Aug  5 13:28:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@tmohme you have anonymous flag enabled, this will hide the error text and print only minimal information. You can disable anonymous to have more details about the error
