### ISSUE TITLE
minio 怎么修改不了服务的时区呢

### ISSUE THREAD

**Issue by taosehngyijiushi** [minio/minio#20370]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by marktheunissen** [comment]
Please fill in the form properly, include your operating system, MinIO version, and please explain where you would like the timezone to be changed and what you expect to see. What is the use case? 

We set everything to UTC on the server

// All MinIO operations must be under UTC.
os.Setenv("TZ", "UTC")

The client can change the timezone e.g. with mc:

```
export TZ="America/New_York"
 ❯ mc ls play
[2024-08-28 21:14:37 EDT]     0B 00atest/
```


Notice: EDT timezone in the above output
