### ISSUE TITLE
There was a problem in production

### ISSUE THREAD

**Issue by xzlinux** [minio/minio#20385]
There is a problem in production:
   Version: RELEASE.2024-03-26T22-10-45Z (go1.21.8 linux/amd64)
Expanded Security Maintenance for Applications is not enabled.

67 updates can be applied immediately.
1 of these updates is a standard security update.
To see these additional updates run: apt list --upgradable

4 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm

github.com/minio/minio/cmd.newMetacacheBlockWriter.func1.2()
        github.com/minio/minio/cmd/metacache-stream.go:793 +0xbe
github.com/minio/minio/cmd.newMetacacheBlockWriter.func1()
        github.com/minio/minio/cmd/metacache-stream.go:809 +0x34e
created by github.com/minio/minio/cmd.newMetacacheBlockWriter in goroutine 416520929
        github.com/minio/minio/cmd/metacache-stream.go:774 +0xbb

**Comment by harshavardhana** [comment]
Production systems require subscriptions https://min.io/pricing - please sign-up.
