### ISSUE TITLE
Failed to load rebalance data

### ISSUE THREAD

**Issue by deathalt** [minio/minio#20391]
### Expected Behavior
The mc admin rebalance start minio_prod command should start the rebalance operation without errors.

### Current Behavior
The rebalance operation fails with the following error:

```
Error: Unable to initialize backend: failed to load rebalance data: Storage resources are insufficient for the read operation .minio.sys/rebalance.bin, retrying in 2.618628637s (*fmt.wrapError)
        7: internal/logger/logger.go:268:logger.LogIf()
        6: cmd/logging.go:156:cmd.storageLogIf()
        5: cmd/erasure-server-pool.go:211:cmd.newErasureServerPools()
        4: cmd/server-main.go:1166:cmd.newObjectLayer()
        3: cmd/server-main.go:915:cmd.serverMain.func11()
        2: cmd/server-main.go:561:cmd.bootstrapTrace()
        1: cmd/server-main.go:913:cmd.serverMain()
 API: SYSTEM.rebalance()
 Time: 09:22:39 UTC 09/06/2024
 DeploymentID: 01b2524d-8d6c-4cad-ab4d-0958ae577e13
```

and no rebalance.bin file exists

```
❯ ansible prod -m shell -a '
  for i in $(seq 1 16); do  
    if [ -f /opt/minio/disk$i/.minio.sys/rebalance.bin ]; then 
      echo "/opt/minio/disk$i/.minio.sys/rebalance.bin exists"; 
    fi 
  done' -b

prod-minio-2 | CHANGED | rc=0 >>

prod-minio-4 | CHANGED | rc=0 >>

prod-minio-3 | CHANGED | rc=0 >>

prod-minio-1 | CHANGED | rc=0 >>

prod-minio-5 | CHANGED | rc=0 >>

prod-minio-6 | CHANGED | rc=0 >>

prod-minio-9 | CHANGED | rc=0 >>

prod-minio-8 | CHANGED | rc=0 >>

prod-minio-10 | CHANGED | rc=0 >>

prod-minio-7 | CHANGED | rc=0 >>

prod-minio-11 | CHANGED | rc=0 >>

prod-minio-13 | CHANGED | rc=0 >>

prod-minio-12 | CHANGED | rc=0 >>

prod-minio-14 | CHANGED | rc=0 >>

prod-minio-15 | CHANGED | rc=0 >>

prod-minio-17 | CHANGED | rc=0 >>

prod-minio-18 | CHANGED | rc=0 >>

prod-minio-19 | CHANGED | rc=0 >>

prod-minio-16 | CHANGED | rc=0 >>

prod-minio-20 | CHANGED | rc=0 >>
```

### Steps to Reproduce (for bugs)
Run the command mc admin rebalance start minio_prod.
Observe the error message in the logs.

### Context
The rebalance operation is necessary to distribute data evenly across the storage pool. The failure of this operation affects data distribution and potentially impacts performance and reliability.

### Regression
No

### Your Environment
Version used (minio --version): minio version RELEASE.2024-08-29T01-40-52Z (commit-id=504e52b45e8350d0b64ae52f4b4307fd5d6b23d1)
Server setup and configuration: 20 servers, 16 nvme per server, 2 pools 10 servers each
<details>
  <summary>mc admin info</summary>

❯ mc admin info minio_prod
●  prod-minio-10:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-11:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-12:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-13:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-14:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-15:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-16:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-17:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-18:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-19:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-1:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-20:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 2

●  prod-minio-2:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-3:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-4:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-5:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-6:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-7:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-8:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

●  prod-minio-9:9000
   Uptime: 8 minutes
   Version: 2024-08-29T01:40:52Z
   Network: 20/20 OK
   Drives: 16/16 OK
   Pool: 1

┌──────┬────────────────────────┬─────────────────────┬──────────────┐
│ Pool │ Drives Usage           │ Erasure stripe size │ Erasure sets │
│ 1st  │ 13.3% (total: 1.3 PiB) │ 10                  │ 16           │
│ 2nd  │ 7.7% (total: 1.1 PiB)  │ 10                  │ 16           │
└──────┴────────────────────────┴─────────────────────┴──────────────┘

1.1 PiB Used, 35 Buckets, 7,497,963 Objects, 7,713,485 Versions, 831,745 Delete Markers
320 drives online, 0 drives offline, EC:4
</details>

Operating System and version (uname -a): Linux prod-minio-6 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> The rebalance operation is necessary to distribute data evenly across the storage pool. The failure of this operation affects data distribution and potentially impacts performance and reliability.

There is no such requirement, these are all wrong assumptions about rebalance. Rebalance exists to avoid unnecessary FUD from the competitors. 

You should never use rebalance in the first place. 

> Server setup and configuration: 20 servers, 16 nvme per server, 2 pools 10 servers each

Also for such high end setups please avail a subscription so we can help you. 

> Run the command mc admin rebalance start minio_prod.
> Observe the error message in the logs.

This error will never happen when you run `mc admin rebalance start`, this is happening when you are restarting the servers the error log indicates that. 

it also indicates that there is some quorum issue on the rebalance metadata 

- Either your rebalance.bin is truncated, unreadable
- You have many drives or nodes offline

**Comment by deathalt** [comment]
> Either your rebalance.bin is truncated, unreadable
> You have many drives or nodes offline

as you can see in mc admin info output there is no offline disks or nodes, you can find it under spoiler
also there is no rebalance.bin in any of .minio.sys/ directory, you can find it under spoiler also

> it also indicates that there is some quorum issue on the rebalance metadata

how can I find quorum issue?

mc admin service restart said that quorum is established

```
❯ mc admin service restart minio_prod
Restart command successfully acknowledged by `minio_prod` in 521 milliseconds. Type Ctrl-C to quit or wait to follow the status of the restart process.
┌─────────────────────────────────┬────────┐
│ HOST                            │ STATUS │
├─────────────────────────────────┼────────┤
│                   minio-18:9000 │ ✔      │
│                   minio-10:9000 │ ✔      │
│                   minio-11:9000 │ ✔      │
│                   minio-12:9000 │ ✔      │
│                   minio-13:9000 │ ✔      │
│                   minio-14:9000 │ ✔      │
│                   minio-15:9000 │ ✔      │
│                   minio-16:9000 │ ✔      │
│                   minio-17:9000 │ ✔      │
│                   minio-19:9000 │ ✔      │
│                   minio-1:9000  │ ✔      │
│                   minio-20:9000 │ ✔      │
│                   minio-2:9000  │ ✔      │
│                   minio-3:9000  │ ✔      │
│                   minio-4:9000  │ ✔      │
│                   minio-5:9000  │ ✔      │
│                   minio-6:9000  │ ✔      │
│                   minio-7:9000  │ ✔      │
│                   minio-8:9000  │ ✔      │
│                   minio-9:9000  │ ✔      │
└─────────────────────────────────┴────────┘

....!!!!!
Established quorum on `minio_prod` successfully in 4 seconds
```

> Also for such high end setups please avail a subscription so we can help you.

we should think about it
we got issue right now because of minio undefined behavior


also I found that not all disks are loaded evenly within the pool.

**Comment by harshavardhana** [comment]
@deathalt it looks like your requirement is production grade, we do not support via community for such production grade setups. https://min.io/pricing - please consider a subscription.

It will require deeper investigation here.

**Comment by deathalt** [comment]
@harshavardhana 

So you honestly think that after you close an issue with an obvious bug in your product that says “Github Issue Support” in the PRICING we'll run to pay you 500 thousand dollars?
lol
first learn how to behave with people who can potentially bring you money, instead of *** them up and just walking away.
that's just nonsense.

**Comment by harshavardhana** [comment]
> So you honestly think that after you close an issue with an obvious bug in your product that says “Github Issue Support” in the PRICING we'll run to pay you 500 thousand dollars?
> lol
> first learn how to behave with people who can potentially bring you money, instead of *** them up and just walking away.
> that's just nonsense.

@deathalt, the tooling needed to help you will only work on registered clusters. If there are ways that I could have helped you, I would. 

This requires deeper investigation and goes beyond the scope of free community support. Please don't hesitate to send the fixes if you happen to have a problem. There is a source available.

I sent a change to not hold the server startup #20392 for rebalance metadata since it's just a hint, not a hard requirement. You can cherry-pick the patch and deploy it in your environment.

Thank you for using MinIO.
