### ISSUE TITLE
How to change 9000 port for the container

### ISSUE THREAD

**Issue by quantissimo** [minio/minio#20398]
I'm trying to run MinIO on Synology Container Manager (docker) but it seems that the 9000 port conflicts with another container (Portainer). It seems that the 9000 is preconfigured for the MinIO docker container.

Do you know which port will work?

![Screenshot 2024-09-07 at 10 37 06](https://github.com/user-attachments/assets/3a92a94e-a140-467b-b5d5-d6a748ddbf01)

![Screenshot 2024-09-07 at 10 40 30](https://github.com/user-attachments/assets/685ec4a3-00df-4031-8739-e3d7952d0598)

**Comment by harshavardhana** [comment]
@quantissimo synology is not our product please ask them how they expose changing ports for MinIO, however with minio server you can change the port via `--address :myport`

**Comment by quantissimo** [comment]
Thank you for your idea.

I tried to change the container port by command --address :9310 and stopped Portainer but still not working

![Screenshot 2024-09-07 at 11 21 24](https://github.com/user-attachments/assets/6008225c-9308-40c1-97b1-b40655a5180d)

**Comment by klauspost** [comment]
Check your mapping is correct. Minio will print which port it uses in the standard output when starting.

**Comment by harshavardhana** [comment]
> I tried to change the container port by command --address :9310 and stopped Portainer but still not working

That seems correct, but as I said, we do not support these appliances and can't tell you their behavior and shortcomings. You'll need to contact the vendor. 

How it behaves is shown below; we expect Synology to honor this.
```
~ minio server ~/test --address ":9310"
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: DEVELOPMENT.2024-09-07T10-38-36Z (go1.22.6 linux/amd64)

API: http://10.0.0.185:9310  http://10.0.3.1:9310  http://172.17.0.1:9310  http://172.19.0.1:9310  http://127.0.0.1:9310 
   RootUser: minioadmin 
   RootPass: minioadmin 

WebUI: http://10.0.0.185:35247 http://10.0.3.1:35247 http://172.17.0.1:35247 http://172.19.0.1:35247 http://127.0.0.1:35247    
   RootUser: minioadmin 
   RootPass: minioadmin 

CLI: https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
   $ mc alias set 'myminio' 'http://10.0.0.185:9310' 'minioadmin' 'minioadmin'

Docs: https://docs.min.io
WARN: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
```
