### ISSUE TITLE
windows arm64 release

### ISSUE THREAD

**Issue by gedw99** [minio/minio#20425]
https://dl.min.io/server/minio/release/ does not have windows arm64

I know it seems a little silly,  but there are a ton of Windows arm64 devices coming out with the partnership with Qualcomm.  

I actually run Windows 11 ARM64 on a surface.

Its easier for devs to debug using just the binaries, instead of docker.

It should, I expect be a matter of just turning it in on goreleaser.

**Comment by harshavardhana** [comment]
go install -v github.com/minio/minio@latest
