### ISSUE TITLE
SignatureDoesNotMatch Error with MinIO Behind NGINX Ingress in Kubernetes

### ISSUE THREAD

**Issue by parsa-nw** [minio/minio#20429]
Hello Minio team
In my setup, I have [Spring Cloud Gateway](https://github.com/spring-cloud/spring-cloud-gateway) behind an [NGINX Ingress](https://github.com/kubernetes/ingress-nginx) in Kubernetes, with MinIO positioned behind the Spring Cloud Gateway. I consistently encountered a SignatureDoesNotMatch error when interacting with MinIO. After extensive research, no solution seemed to address my specific case.

To troubleshoot, I performed several packet captures using tcpdump and discovered that certain headers, generated by the ingress, were being forwarded to MinIO and causing the SignatureDoesNotMatch error. The problematic headers were:

    X-Forwarded-For
    X-Forwarded-Host
    X-Forwarded-Port
    X-Forwarded-Proto
    X-Forwarded-Scheme
    Forwarded
    traceparent

Unfortunately, removing these headers at the ingress level wasn't an option, as it would disrupt the ingress functionality.
As a workaround, I resolved the issue by removing these headers within Spring Cloud Gateway before forwarding the request to MinIO. This approach successfully eliminated the error.

I believe it would be beneficial if MinIO provided an option or argument to handle such scenarios when deployed behind a reverse proxy, to prevent similar issues in the future.

**Comment by harshavardhana** [comment]
Make sure spring cloud gateways preserves the host header.
