### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by GiedriusS** [minio/minio#20435]
Trying to update `minio` to make it work on Go 1.23 and getting this error:

```
get: minio.mod: getting github.com/minio/minio@latest: install: list: go: github.com/minio/minio@v0.0.0-20240912204405-e47d787adb48 requires
        github.com/minio/dperf@v0.5.3 requires
        github.com/intel-go/cpuid@v0.0.0-20220614022739-219e067757cb: invalid version: unknown revision 219e067757cb
```

https://github.com/minio/dperf/blob/master/go.mod#L23 seems like this was moved to https://github.com/aregm/cpuid. 

Trying a fix here: https://github.com/minio/dperf/pull/12

**Comment by harshavardhana** [comment]
Being fixed in PR #20436

**Comment by GiedriusS** [comment]
@harshavardhana your PR got closed for some reason? :sweat_smile:

**Comment by harshavardhana** [comment]
> @harshavardhana your PR got closed for some reason? 😅

yeah due to other issues will resubmit it later.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/20467 fixes this.
