### ISSUE TITLE
ERROR Unable to prepare the list of endpoints: strconv.ParseFloat: parsing "": invalid syntax

### ISSUE THREAD

**Issue by pasztorl** [minio/minio#20437]
Hi,

I got this message when upgrading from RELEASE.2024-05-28T17-19-04Z to RELEASE.2024-06-04T19-20-08Z
I've tried latest release too with the same result.
I've searched the source code and can't find this error message. How can I debug it?

**Comment by harshavardhana** [comment]
Share the server configuration..
