### ISSUE TITLE
Rename fails with resource deadlock avoided error (*os.LinkError)

### ISSUE THREAD

**Issue by AjeelAhmed1998** [minio/minio#20448]
## Expected Behavior
A successful PUT call is made to Minio for a file. The file gets saved in the Minio bucket. 

## Current Behavior
A PUT call is made to Minio for a file and it appends one of the tmp cache files it already has to the file that was sent in the PUT call for some reason that is beyond my understanding and knowledge of Minio.

## Possible Solution
Deleting the tmp folder it already had but that didn't help, it just recreated it again. 

## Steps to Reproduce (for bugs)

1. Create a PUT call to Minio with .jpg file. 

Logs from the minio side: 

```
prefect-minio-1   | Time: 15:08:27 UTC 09/17/2024
prefect-minio-1   | DeploymentID: 1b2bc937-97ed-4ef2-8fa0-b4a7997113a9
prefect-minio-1   | RequestID: 17F6108D8768346A
prefect-minio-1   | RemoteHost: 172.21.0.5
prefect-minio-1   | Host: prefect-minio:9000
prefect-minio-1   | UserAgent: Botocore/1.27.59 Python/3.10.14 Linux/6.6.22-linuxkit
prefect-minio-1   | Error: rename /data/.minio.sys/tmp/bcef508d-bb63-4441-a1b4-3ea0ff2e78ee/eecfe2d3-f70a-4c4c-b1c7-9638df694555/ /data/flow-storage/daily_report/opt/prefect/flows/documentation/images/database.jpg/eecfe2d3-f70a-4c4c-b1c7-9638df694555: resource deadlock avoided (*os.LinkError)
prefect-minio-1   |        7: internal/logger/logger.go:258:logger.LogIf()
prefect-minio-1   |        6: cmd/erasure-object.go:1256:cmd.erasureObjects.putObject()
prefect-minio-1   |        5: cmd/erasure-object.go:936:cmd.erasureObjects.PutObject()
prefect-minio-1   |        4: cmd/erasure-sets.go:923:cmd.(*erasureSets).PutObject()
prefect-minio-1   |        3: cmd/erasure-server-pool.go:957:cmd.(*erasureServerPools).PutObject()
prefect-minio-1   |        2: cmd/object-handlers.go:1916:cmd.objectAPIHandlers.PutObjectHandler()
prefect-minio-1   |        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP() 
```

## Context
I am using Minio as part of running a Prefect script, Prefect makes a call to the Minio as shown above and tries to store the codebase there. 

## Your Environment

* Version used (`minio --version 7.1.12`):

**Comment by harshavardhana** [comment]
> prefect-minio-1   | Error: rename /data/.minio.sys/tmp/bcef508d-bb63-4441-a1b4-3ea0ff2e78ee/eecfe2d3-f70a-4c4c-b1c7-9638df694555/ /data/flow-storage/daily_report/opt/prefect/flows/documentation/images/database.jpg/eecfe2d3-f70a-4c4c-b1c7-9638df694555: resource deadlock avoided (*os.LinkError)

what is your backend filesystem? @AjeelAhmed1998

**Comment by AjeelAhmed1998** [comment]
hi @harshavardhana it's S3 if that's what you mean

**Comment by klauspost** [comment]
@AjeelAhmed1998 No. What is the file system of the ` /data/` mount you've installed on.

**Comment by AjeelAhmed1998** [comment]
hi @klauspost it's ext4, thanks for all the help. I'm running all this on docker, I have a separate container running the minio image `minio/minio:RELEASE.2023-01-02T09-40-09Z.fips`. I ran the same setup on another machine(both m1 macbooks in this case) and on that one it worked without any issues. I have never had this issue before so I have no idea what changed.

**Comment by AjeelAhmed1998** [comment]
another log if it helps


```
prefect-minio-1   | API: PutObject(bucket=flow-storage, object=daily_report/documentation/images/database.jpg)
prefect-minio-1   | Time: 14:47:41 UTC 09/18/2024
prefect-minio-1   | DeploymentID: 00305852-319c-4b53-b115-3cdf3a9c4491
prefect-minio-1   | RequestID: 17F65E00263E3B97
prefect-minio-1   | RemoteHost: 172.24.0.4
prefect-minio-1   | Host: prefect-minio:9000
prefect-minio-1   | UserAgent: Botocore/1.27.59 Python/3.10.14 Linux/6.6.22-linuxkit
prefect-minio-1   | Error: drive:/data, srcVolume: .minio.sys/tmp, srcPath: 50405995-dd9f-44dd-9504-605f64b4d137, dstVolume: flow-storage:, dstPath: daily_report/documentation/images/database.jpg - error resource deadlock avoided (*errors.errorString)
prefect-minio-1   |        7: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
prefect-minio-1   |        6: internal/logger/logonce.go:149:logger.LogOnceIf()
prefect-minio-1   |        5: cmd/logging.go:164:cmd.storageLogOnceIf()
prefect-minio-1   |        4: cmd/xl-storage.go:2576:cmd.(*xlStorage).RenameData.func1()
prefect-minio-1   |        3: cmd/xl-storage.go:2875:cmd.(*xlStorage).RenameData()
prefect-minio-1   |        2: cmd/xl-storage-disk-id-check.go:501:cmd.(*xlStorageDiskIDCheck).RenameData.func2()
prefect-minio-1   |        1: internal/ioutil/ioutil.go:116:ioutil.WithDeadline[...].func1()
```

**Comment by AjeelAhmed1998** [comment]
what I don't understand why does Minio need to rename this in the first place, why can't it just add new files as is? Why the appending?

**Comment by klauspost** [comment]
I guess there is another item on the list to why we don't recommend ext4.

Object writes have to be atomic, so data is written and then renamed to its final destination.

**Comment by harshavardhana** [comment]
Yeah this is a bug in your platform, or the kernel version. This is buggy implementation at the kernel level.

This is not ext4, there are no such errors returned in Linux this is some kind of emulation issue on macOS.

This is out of the scope for us to fix, please use a supported environment such as backend drives with xfs.
