### ISSUE TITLE
clarification for the AGPL license

### ISSUE THREAD

**Issue by Gottox** [minio/minio#20459]
In this comment from a minio contributor it was mentioned that all software that connects to minio must be open source: https://github.com/minio/minio/issues/13308#issuecomment-929254690

This is a pretty strange interpretation of the AGPL license. I'd like to ask if this represents the official opinion of the minio project or if I can use minio on the actual Internet where clients like Microsoft Edge, Opera or other non-open source clients can call the Webinterface of minio or files in minio buckets.

**Comment by harshavardhana** [comment]
> This is a pretty strange interpretation of the AGPL license. I'd like to ask if this represents the official opinion of the minio project or if I can use minio on the actual Internet where clients like Microsoft Edge, Opera or other non-open source clients can call the Webinterface of minio or files in minio buckets.

Please read https://min.io/compliance and seek legal advice. If you want an AGPL exception for using MinIO, please contact us at sales@minio.io.
