### ISSUE TITLE
Checksum not retrievable when provided as a trailing checksum via the AWS S3 SDK

### ISSUE THREAD

**Issue by ozzytc** [minio/minio#20455]
## Expected Behavior
When putting an object via PutObject using the AWS S3 .NET SDK and requesting a trailing checksum by setting ChecksumAlgorithm (X-Amz-Sdk-Checksum-Algorithm) to "SHA256", I expect to be able to retrieve the checksum at a later point from either:

- GetObjectAttributes (by setting X-Amz-Object-Attributes: Checksum) - the checksum value should be included in the GetObjectAttributesResponse response body
- GetObject (by setting X-Amz-Checksum-Mode: ENABLED) - the checksum value should be included in the X-Amz-Checksum-SHA256 response header

The ChecksumAlgorithm should also be included in the ListObjectsV2 result but it too is missing.

Note: when providing a precalculated checksum to PutObject, the checksum value is able to be retrieved later via GetObject and GetObjectAttributes, however ChecksumAlgoritm is still missing from the ListObjectsV2 result.

## Current Behavior
When I upload a file via PutObject using a trailing checksum, I can see the X-Amz-Trailer request header correctly provided and I also see the trailing checksum correctly appended to the end of the upload request.  The PutObject response includes the X-Amz-Checksum-Sha256 response header as expected.

However, subsequent calls to ListObjectsV2, GetObjectAttributes and GetObject fail to include the checksum value (or the checksum algorithm in the case of ListObjectsV2) in their respective responses.

Running the same SDK code against an AWS S3 endpoint yields expected behaviour, that is:
- ListObjectsV2 includes 'ChecksumAlgorithm' in its xml response body
- GetObjectAttributes includes 'Checksum/ChecksumSHA256' in its xml response body
- GetObject includes the 'X-Amz-Checksum-Sha256' response header

## Environment
Version: RELEASE.2024-09-13T20-26-02Z (go1.22.7 linux/amd64)
Server setup and configuration: Docker on Ubuntu 20.04.5

**Comment by klauspost** [comment]
Got a PutObject repro.

ListObjectsV2 must have been added recently. Do not see it in [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html). Do you have an example of this working?

**Comment by klauspost** [comment]
#20456 Fixes the issue. Verified with PutObject (trailing headers) + GetObject, HeadObject & GetObjectAttributes.

**Comment by klauspost** [comment]
Tests in https://github.com/minio/minio-go/pull/2002

**Comment by ozzytc** [comment]
> ListObjectsV2 must have been added recently. Do not see it in [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html). Do you have an example of this working?

@klauspost ChecksumAlgorithm is documented [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html) in the API docs.  Here is an example from AWS:

`<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>my-test-bucket</Name><Prefix></Prefix><KeyCount>1</KeyCount><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>test.txt</Key><LastModified>2024-09-19T00:27:16.000Z</LastModified><ETag>&quot;bdc70a6c91dbb9b87a3bde0436bfd3f0&quot;</ETag><ChecksumAlgorithm>SHA256</ChecksumAlgorithm><Size>19</Size><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>`

**Comment by klauspost** [comment]
@ozzytc OK, seems like they underdocumented it a bit. I will add it - should be pretty trivial.

**Comment by ozzytc** [comment]
Yes, it's not very obvious, thank you!

**Comment by klauspost** [comment]
@ozzytc Are you sending a `X-Amz-Checksum-Mode: ENABLED` header to get this field in the listing, or just a regular listing?

**Comment by ozzytc** [comment]
@klauspost No, just a regular listing, looking at the AWS docs and in their SDK for ListObjectsV2 (and ListObjects for that matter) this header isn't an option.  From my testing, ChecksumAlgorithm will be included in the response whenever there is an additional checksum for the object.

**Comment by klauspost** [comment]
@ozzytc Great. I was hoping that was the case. Testing an implementation now.

**Comment by klauspost** [comment]
Encryption is making this a bit more complicated, so it may take a bit to land.

**Comment by ozzytc** [comment]
No dramas, thanks for the update!
