### ISSUE TITLE
Weird Behavior when looking at `Uint8Array`

### ISSUE THREAD

**Issue by newtondotcom** [minio/minio#20453]
## Expected Behavior
When I upload an 1500066 long Uint8Array and then download back, I would like to have an 1500066 long Uint8Array and not a 5300707 or 5300703 long Uint8Array.

## Current Behavior
The Uint8Array has almost tripled in size during the operation. 

## Steps to Reproduce (for bugs)
[Demo code](https://github.com/newtondotcom/CoffreTonDoc/blob/main/pages/test4.vue)

## Context
I am trying to make a personal cloud with client side encryption so I need to be able to manipulate file etc .

## Regression
I don't think so !

## Your Environment
* Docker version : `Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`
* Version used (`minio --version`): `minio version RELEASE.2024-06-06T09-36-42Z (commit-id=5aaef9790ff4d693202ff55bc46b40a1ff67f69e)`
* Server setup and configuration: `1Gb ram` / `1 vCPU`
* Operating System and version (`uname -a`): `Linux d21f8e71d595 6.5.0-1018-oracle #18~22.04.1-Ubuntu SMP Sat Feb 17 22:00:50 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by klauspost** [comment]
You need to use an S3 API SDK. You can't just PUT/GET.

**Comment by newtondotcom** [comment]
Yeah I would love to but when I import Minio Client in client-side, I get the following error : `✘ [ERROR] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json`.
So I am obliged to use `PUT`/`GET`

**Comment by klauspost** [comment]
@newtondotcom I am not a JS dev, so maybe find a community that get you further.
