### ISSUE TITLE
Doesn't work events of REPLICA and PUT

### ISSUE THREAD

**Issue by slovak12345** [minio/minio#20464]
## NOTE
Doesn't work events of replica

Hello everyone I have two minio containers raised based on the following images quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z ,
one on one physical server, in the future we will call it (source_minio) and on another physical server (target_minio). 
Files are uploaded to the downloads folder on source_minio, data replication is configured from this folder to the downloads folder at target_minio using the following commands: 

mc alias set myminio http://127.0.0.1:9000 minio_admin_do_not_use_in_production minio_admin_do_not_use_in_production
mc replicate add myminio/downloads --remote-bucket 'http://minio_admin_do_not_use_in_production:minio_admin_do_not_use_in_production@<target_minio_ip>:9000/downloads' --replicate "delete,delete-marker,existing-objects"

Events are configured on target_mini using AMQP rabbit_mq(mini and rabbit_mq are raised as two containers on the same network), we tried to configure it with postgresql as well: 

mc alias set myminio http://127.0.0.1:9000 minio_admin_do_not_use_in_production minio_admin_do_not_use_in_production
mc admin config set myminio notify_amqp:1 url="amqp://simpleuser:simplepassword@<target_rabbit_mq_ip>:5672" exchange="bucketevents" routingKey="bucketlogs" exchangeType="fanout" enable="on" mandatory="off" immediate="off" durable="off" internal="off" noWait="off" autoDeleted="off"

After that, events in the downloads folder are configured via the web interface for all types of events (PUT, REPLICA, DELETE, etc.).

Finally:

## Expected Behavior
I will see a PUT or REPLICA event in the queue when replication from source_mini to target_minio occurs. 

## Current Behavior
Nothing happens 

## Context
We tried checking through mc watch, complete silence, no messages (at the same time, I see messages about deleting, highlighting and uploading files immediately on target_minio). However, if we set up the audit_log, we see the put event 
Received POST data: 
{
                        "version":"1",
                        "deploymentid":"4d04ad7b-9257-46ec-80b7-2967a68ed081",
                        "time":"2024-09-19T17:55:51.157627902Z",
                        "event":"",
                        "trigger":"incoming",
                        "api":
                            {
                                "name":"PutObject",
                                "bucket":"downloads",
                                "object":"file.txt",
                                "status":"OK",
                                "statusCode":200,
                                "rx":88205010,
                                "tx":0,
                                "txHeaders":460,
                                "timeToResponse":"29751570499ns",
                                "timeToResponseInNS":"29751570499"
                            },
                            "remotehost":"172.25.0.1",
                            "requestID":"17F6B6D247BC11E7",
                            "userAgent":"MinIO (linux; amd64) minio-go/v7.0.75 minio-replication-target/RELEASE.2024-08-17T01-24-54Z arn:minio:replication::d7119613-083e-4b95-af87-f6d629f10843:downloads",
                            "requestPath":"/downloads/file.txt",
                            "requestHost":"<target_minio_ip>:9000",
                            "requestQuery":
                            {
                                "versionId":"958e7ee2-0967-48fc-b5f4-e6f09f427d56"
                            },
                            "requestHeader":
                            {
                                "Authorization":"AWS4-HMAC-SHA256 Credential=minio_admin_do_not_use_in_production/20240919/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-object-lock-mode;x-amz-object-lock-retain-until-date;x-amz-replication-status;x-amz-storage-class;x-minio-source-etag;x-minio-source-mtime;x-minio-source-replication-request;x-minio-source-replication-retention-timestamp,Signature=083c53ea1cc1d9d7719da804da0b54f706aae1881c8f018abf6a6d6f5ac630b9",
                                "Content-Length":"88205010",
                                "Content-Type":"video/mp4",
                                "User-Agent":"MinIO (linux; amd64) minio-go/v7.0.75 minio-replication-target/RELEASE.2024-08-17T01-24-54Z arn:minio:replication::d7119613-083e-4b95-af87-f6d629f10843:downloads",
                                "X-Amz-Content-Sha256":"STREAMING-AWS4-HMAC-SHA256-PAYLOAD",
                                "X-Amz-Date":"20240919T175726Z",
                                "X-Amz-Decoded-Content-Length":"88083876",
                                "X-Amz-Object-Lock-Mode":"COMPLIANCE",
                                "X-Amz-Object-Lock-Retain-Until-Date":"2025-03-18T17:56:38Z",
                                "X-Amz-Replication-Status":"REPLICA",
                                "X-Amz-Storage-Class":"STANDARD",
                                "X-Minio-Source-Etag":"48b2d49e052f789566cec900dd71c7f3",
                                "X-Minio-Source-Mtime":"2024-09-19T17:57:26.164682213Z",
                                "X-Minio-Source-Replication-Request":"true",
                                "X-Minio-Source-Replication-Retention-Timestamp":
                                "2024-09-19T17:57:26.164682213Z"
                            },
                            "responseHeader":
                                    {
                                        "Accept-Ranges":"bytes",
                                        "Content-Length":"0",
                                        "ETag":"48b2d49e052f789566cec900dd71c7f3",
                                        "Server":"MinIO",
                                        "Strict-Transport-Security":"max-age=31536000; includeSubDomains",
                                        "Vary":"Origin,Accept-Encoding",
                                        "X-Amz-Id-2":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8",
                                        "X-Amz-Request-Id":"17F6B6D247BC11E7",
                                        "X-Content-Type-Options":"nosniff",
                                        "X-Ratelimit-Limit":"8545",
                                        "X-Ratelimit-Remaining":"8545",
                                        "X-Xss-Protection":"1; mode=block",
                                        "x-amz-version-id":"958e7ee2-0967-48fc-b5f4-e6f09f427d56"
                                    },
                                "tags":
                                    {
                                        "GetObject":"name=buckets/.usage.json,pool=1,set=1",
                                        "PutObject":"name=file.txt,pool=1,set=1"
                                    },
                                "accessKey":"minio_admin_do_not_use_in_production"
                            }

**Comment by harshavardhana** [comment]
yes this is on purpose to avoid double events. It is behaving as per design.

**Comment by slovak12345** [comment]
@harshavardhana  And then why do I see the HEAD, PUT (when uploading a file directly to target_minio) and DELETE events both in the audit log and in the rabbit queue, in which case do replica events appear in the queue at all? because even with the audiologue turned off, they don't appear there.
