### ISSUE TITLE
Allow disabling shared urls properly via bucket policy (not IAM policy)

### ISSUE THREAD

**Issue by myrust-go** [minio/minio#20469]
## Expected Behavior

MinIO Said is 100% compatible with the S3 API.
I found that my attempt to disable MinIO's sharing feature failed.
“s3:signatureAge": 600000
https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html
```

{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Sid": "Deny a presigned URL request if the signature is more than 10 min old",
         "Effect": "Deny",
         "Principal": "*",
         "Action": "s3:*",
         "Resource": "arn:aws:s3:::examplebucket3/*",
         "Condition": {
            "NumericGreaterThan": {
               "s3:signatureAge": 600000
            }
         }
      }
   ]
}
```

## Current Behavior

Add s3:signatureversion and s3:authType hint parameters are not supported.
Add support parameters bucket can't  invisible.

The S3 permission policy is set, and all buckets are invisible
After the setting is successful, all buckets cannot be displayed and the permissions are not effective.

The IAM permissions are set as follows:

```

{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Sid": "Deny a presigned URL request if the signature is more than 10 min old",
         "Effect": "Deny",
         "Principal": "*",
         "Action": "s3:*",
         "Resource": "arn:aws:s3:::examplebucket3/*",
         "Condition": {
            "NumericGreaterThan": {
               "s3:signatureAge": 600000
            }
         }
      }
   ]
}
```

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Allow only requests that use Authorization header for request authentication. Deny POST or presigned URL requests.",
            "Effect": "Deny",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mytest/*",
                "arn:aws:s3:::test/*",
                "arn:aws:s3:::abctest/*"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-content-sha256": [
                        "AWS4-HMAC-SHA256"
                    ]
                }
            }
        }
    ]
}
```

```
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Sid": "Deny a presigned URL request if the signature is more than 10 min old",
         "Effect": "Deny",
         "Principal": "*",
         "Action": "s3:*",
         "Resource": "arn:aws:s3:::examplebucket3/*",
         "Condition": {
            "NumericGreaterThan": {
               "s3:signatureAge": 60
            }
         }
      }
   ]
}
```

## Steps to Reproduce (for bugs)

Add the same policy as S3.

1.  s3:signatureAge
2.s3:authType
3.s3:signatureversion 

## Your Environment

* Version used (`minio --version`): 2024-09-13T20:26:02Z
* Server setup and configuration: SNSD stanard config
* Operating System and version (`uname -a`): Linux iZ2ze5kj5mk9w05wdmmsscZ 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Edited the nonsensical title and made it more concise and meaningful.

We will take a look at see if we can address this properly.

**Comment by myrust-go** [comment]
> Edited the nonsensical title and made it more concise and meaningful.
> 
> We will take a look at see if we can address this properly.

My statement is not accurate. It is necessary to prohibit the share URL, just like the S3 policy.

The title you modified is accurate.

Great!

**Comment by harshavardhana** [comment]
You need to set these policies as IAM policies, not as a public policy @mynameisdasagua we only support "anonymous" bucket policies there is no concept of a principal in them. 

You need to add the policy here directly to a user or a group as part of an IAM policy where there is no Principal. 

```
        // S3SignatureVersion - identifies the version of AWS Signature that you want to support for authenticated requests.
        S3SignatureVersion KeyName = "s3:signatureversion"

        // S3SignatureAge - identifies the maximum age of presigned URL allowed
        S3SignatureAge KeyName = "s3:signatureAge"

        // S3AuthType - optionally use this condition key to restrict incoming requests to use a specific authentication method.
        S3AuthType KeyName = "s3:authType"
```

Adding Principal: "*" is mostly meaningless on MinIO as we do not wish to support such an extend bucket policy requirement which is only meant for anonymous access.

**Comment by myrust-go** [comment]
## 1. Set bucket custom policy :

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Deny a presigned URL request if the signature is more than 10 min old",
            "Effect": "Deny",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mytarget/*"
            ],
            "Condition": {
                "NumericGreaterThan": {
                    "s3:signatureAge": [
                        10
                    ]
                }
            }
        }
    ]
}
```

## 2.  generate the share object.  The command is 

` mc share download  demo/mytarget/ztypes_linux.go  
`

## 3. Visit the url ，Able to access. 
http://xxxx:9000/mytarget/ztypes_linux.go?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20240926%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240926T125334Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=571c80746a02a0f457b61b3f382726466507abc092b8796b2b27e4b65a7fb08e


## 4. Set User IAM Policy:
```

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mytest/*"
            ],
            "Condition": {
                "NumericGreaterThan": {
                    "s3:signatureAge": [
                        10
                    ]
                }
            }
        }
    ]
}

```

Unable to share, all operations are unavailable.


## 5. Expected

Objects older than 10 seconds cannot be accessed. Expectations not met.

**Comment by myrust-go** [comment]
@harshavardhana   Above are our test results.

**Comment by harshavardhana** [comment]
You cannot set bucket policy as I mentioned above. Which enables anonymous access.

But will try to perhaps try to see if we can error out properly as it's unsupported for bucket policies.

**Comment by myrust-go** [comment]
> You cannot set bucket policy as I mentioned above. Which enables anonymous access.
> 
> But will try to perhaps try to see if we can error out properly as it's unsupported for bucket policies.

Ok , I set up the user Policy  or Bucket Policy , it didn't work..

Haven't been able to find a way for MinIO to implement the same functionality as s3, how to disable the preSignedUrl?

My test concluded that MinIO User Policy ‘s3:signatureAge’ is not working.

Harsh, thanks very much

**Comment by jiuker** [comment]
> ## 1. Set bucket custom policy :
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "Deny a presigned URL request if the signature is more than 10 min old",
>             "Effect": "Deny",
>             "Principal": {
>                 "AWS": [
>                     "*"
>                 ]
>             },
>             "Action": [
>                 "s3:*"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::mytarget/*"
>             ],
>             "Condition": {
>                 "NumericGreaterThan": {
>                     "s3:signatureAge": [
>                         10
>                     ]
>                 }
>             }
>         }
>     ]
> }
> ```
> 
> ## 2. generate the share object. The command is
> `mc share download demo/mytarget/ztypes_linux.go `
> 
> ## 3. Visit the url ，Able to access.
> http://xxxx:9000/mytarget/ztypes_linux.go?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20240926%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240926T125334Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=571c80746a02a0f457b61b3f382726466507abc092b8796b2b27e4b65a7fb08e
> 
> ## 4. Set User IAM Policy:
> ```
> 
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Deny",
>             "Action": [
>                 "s3:*"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::mytest/*"
>             ],
>             "Condition": {
>                 "NumericGreaterThan": {
>                     "s3:signatureAge": [
>                         10
>                     ]
>                 }
>             }
>         }
>     ]
> }
> ```
> 
> Unable to share, all operations are unavailable.
> 
> ## 5. Expected
> Objects older than 10 seconds cannot be accessed. Expectations not met.

Your policy is limit `mytest` bucket but your shared url are `mytarget`....So that's why not worked as expected. Please try again. Close it for I test it worked as expected. If you still have this issue, please write down here.
