### ISSUE TITLE
scanner on one node in cluster work all the time

### ISSUE THREAD

**Issue by yotles** [minio/minio#20477]
* minio version: RELEASE.2024-06-22T05-26-45Z
* deployment: 9 identical HW servers with 3 disks(SSD) in each.
* 1 bucket ~ 55.6 Mil objects

Hi there! Faced with such strange behavior when on one node in cluster scanner works almost all the time. Due this only on this node permanent high memory consumption. Scanner status show load on all disks on this particular node:
```go
Overall Statistics

Last full scan time:   10d4h25m; Estimated 2.95/month
Current cycle:         77045; Started: 2024-09-23 08:21:38.937773676 +0000 UTC
Active drives:         3

Last Minute Statistics

Objects Scanned:       43921 objects; Avg: 284.91µs; Rate: 63246240/day
Versions Scanned:      43921 versions; Avg: 7.085µs; Rate: 63246240/day
Versions Heal Checked: 0 versions; Avg: 0ms
Read Metadata:         43921 objects; Avg: 245.489µs, Size: 403 bytes/obj
ILM checks:            43921 versions; Avg: 5.233µs
Check Replication:     43921 versions; Avg: 1.151µs
Verify Deleted:        0 folders; Avg: 0ms
Yield:                 1m53.7s total; Avg: 2.59ms/obj
``` 

Metrics `minio_node_scanner_objects_scanned` looks like:

```go
minio-c1-p1-1.node:9000       403854679
minio-c1-p1-2.node:9000       305524103
minio-c1-p1-3.node:9000       194536605
minio-c1-p1-4.node:9000       54615650
minio-c1-p1-5.node:9000       3872299
minio-c1-p1-6.node:9000       839338
minio-c1-p1-7.node:9000       9349
minio-c1-p1-8.node:9000       0
minio-c1-p1-9.node:9000       2203489494
``` 
So I'm talking about minio-c1-p1-9 where metrics so different.
Scanner config default:

`scanner speed=default alert_excess_versions=100 alert_excess_folders=50000`

Is this proper scanner functioning, or I'm missing something in the configuration?

**Comment by klauspost** [comment]
That is expected. Drives are chosen randomly on each cycle. Not all drives are needed, so some nodes/disks will see more activity than others.
