### ISSUE TITLE
cannot read logs on docker

### ISSUE THREAD

**Issue by rtmvc** [minio/minio#20481]
## Expected Behavior

Getting Minio logs from Docker API.

## Current Behavior
No logs are provided through the (golang in my case) Docker API. This seems to be the same issue as this one https://github.com/minio/minio/issues/19693.
However, running the docker image by hand, in a terminal, using `docker run`, works correctly and show logs in the terminal.

## Possible Solution
It is explained in the 19693 issue, which was a bit abruptly closed, that we shouldn't rely on logs to check minio startup. I'm ok with that.
However logs are important to debug issues, e.g. when Minio is used for integration tests. So this workaround is not satisfying at all.

## Steps to Reproduce (for bugs)
Same as https://github.com/minio/minio/issues/19693 . I did it using dockertest golang api

## Context
Trying to get logs to inspect what's happening on Minio, if files get correctly uploaded, etc.

## Regression
Yes.
- This tag "RELEASE.2024-05-01T01-11-10Z" doesn't have the issue.
- This has the issue "RELEASE.2024-05-07T06-41-25Z",
My guess is that this is related to this release that seems to perform few changes to Minio logging (https://github.com/minio/minio/releases/tag/RELEASE.2024-04-06T05-26-02Z).

## Your Environment
- Linux / golang dockertest
- Docker tag RELEASE.2024-05-07T06-41-25Z
- Docker daemon Server: Engine Version: 27.2.1, API version: 1.47

Let me know if I can help more.
Thanks in advance.

**Comment by harshavardhana** [comment]
Can you share a reproducer?

**Comment by rtmvc** [comment]
Here it is (using `github.com/ory/dockertest/v3 v3.9.1`):
```golang
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/ory/dockertest/v3"
	"github.com/ory/dockertest/v3/docker"
)

func main() {
	pool, err := dockertest.NewPool("")
	if err != nil {
		println(err)
		os.Exit(1)
	}
	container, err := pool.RunWithOptions(&dockertest.RunOptions{
		Cmd:          []string{"server", "/data", "--console-address", ":9001"},
		Env:          []string{"MINIO_ROOT_USER=admin", "MINIO_ROOT_PASSWORD=password"},
		ExposedPorts: []string{fmt.Sprintf("%d/tcp", 9000)},
		Repository:   "minio/minio",
		//Tag:          "RELEASE.2024-05-01T01-11-10Z", // With this tag, logs are outputted properly
		Tag: "RELEASE.2024-05-07T06-41-25Z", // With this tag, logs are not outputted anymore
	})
	if err != nil {
		println(err)
		os.Exit(1)
	}

	cmdBuffer := new(bytes.Buffer)
	res, err := container.Exec([]string{"mc", "ready", "play"}, dockertest.ExecOptions{
		StdOut: cmdBuffer,
		StdErr: cmdBuffer,
		TTY:    false,
	})
	println(cmdBuffer.String())
	if err != nil {
		println(err)
		os.Exit(1)
	}
	if res > 0 {
		println("mc ready failed:")
		println(res)
		os.Exit(1)
	}

	buffer := new(bytes.Buffer)
	err = pool.Client.Logs(docker.LogsOptions{
		Container:    container.Container.ID,
		OutputStream: buffer,
		RawTerminal:  false,
		Stdout:       true,
		Stderr:       true,
	})
	if err != nil {
		println(err)
		os.Exit(1)
	}
	println("Something should be printed below:")
	println(buffer.String())
}
```

**Comment by marktheunissen** [comment]
@rtmvc There is no bug here in MinIO, the only change that happened between the two versions you linked was that the log output was changed from stdout to stderr. 

Your reproducer can be modified, to show the stderr output (notice `ErrorStream`):

```
        buffer := new(bytes.Buffer)
	errBuff := new(bytes.Buffer)
	err = pool.Client.Logs(docker.LogsOptions{
		Container:    container.Container.ID,
		OutputStream: buffer,
		ErrorStream:  errBuff,
		RawTerminal:  false,
		Stdout:       true,
		Stderr:       true,
	})
	if err != nil {
		println(err)
		os.Exit(1)
	}
	println("Something will be printed below on stderr:")
	println(errBuff.String())
```

Another option is to set `RawTerminal:  true`. This is all documented here in dockertest: https://github.com/ory/dockertest/blob/f845de5f3bbd65d746dbbf36046283813b21dc25/docker/container.go#L1493-L1499

This is also clearly demonstrated by doing `docker logs xyz` on the container that is started by the original code reproducer, you will see the logs, as `docker logs` multiplexes stderr and stdout together.
