### ISSUE TITLE
Add SSO support for SAML2?

### ISSUE THREAD

**Issue by kerlion** [minio/minio#20485]
**Is your feature request related to a problem? Please describe.**
Most web applications support SAML2 SSO integration.  It would be better if MinIO can support it.

**Describe the solution you'd like**
MinIO supports SAML2.  Lets SSO do authentication work only, map the username to local user. Authorization is still same as local user.
That is. privileges are managed by MinIO side, not the IdP/ side. In most companies, MinIO and SSO/AD accounts are managed by different teams. It can simplify the IT management.

**Describe alternatives you've considered**
I have configured OIDC in MinIO, but get difficult in claims. The IdP do not support add claims for a specific application. 

**Additional context**
May be we can use java-saml under https://github.com/SAML-Toolkits.

**Comment by harshavardhana** [comment]
SAML2 may come as part of our EOS offering in future, currently we do not have any real customer requirements as most of them use OpenID.

If you do have a production requirement please reach out to us at https://min.io/pricing 

There won't be any further IDP extensions  done here for the time being.
