### ISSUE TITLE
Minio crash in docker container, ten thousand of threads, load average over hundred of thousands (ZFS, 3-node cluster)

### ISSUE THREAD

**Issue by marcj** [minio/minio#20498]
## NOTE

We have a MinIO cluster running on 3 servers (nautilus1, nautilus2, nautilus3), each server has a docker container with `minio/minio:RELEASE.2024-06-22T05-26-45Z` running. Only nautilus1 receives the file ops/http calls from our application. Everything runs on ZFS, Ubuntu 24.10 and Docker 27.0.1, AMD EPYC 7502 32-Core. All 3 machines are almost identical, living in the same rack using a VLAN with 10G link. This setup was initially load testet and then was running for weeks in production super stable, then suddenly we experience strange behaviour only on one particular node at a time. We had the issue so far on nautilus1 and nautilus2.

First more information about the setup:

```
Linux nautilus3 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

<img width="1595" alt="Screenshot 2024-09-30 at 18 05 38" src="https://github.com/user-attachments/assets/4e4749bc-c4a2-49ab-b96c-aaefbd42bb4b">

<img width="1647" alt="Screenshot 2024-09-30 at 18 02 34" src="https://github.com/user-attachments/assets/a695189e-e3d0-4041-88e6-cb1c29880717">

```sh
# docker ps
ec5d0e838a33   minio/minio:RELEASE.2024-06-22T05-26-45Z   "/usr/bin/docker-ent…"   3 weeks ago   Up 3 days (healthy)                        minio
```

docker-compose.yml:

```yml
services:
  minio:
    image: minio/minio:RELEASE.2024-06-22T05-26-45Z
    container_name: minio
    network_mode: host
    restart: unless-stopped
    ports:
      - 192.168.100.61:9000:9000
      - 192.168.100.61:9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: abc
    volumes:
      - /data_pool/minio:/data
    command: server http://nautilus1:9000/data http://nautilus2:9000/data http://nautilus3:9000/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.100.61:9001"]
      interval: 30s
      timeout: 20s
      retries: 3
```

`/data_pool/minio` is a ZFS filesystem

```sh
# zfs list
data_pool/minio                   3.56T   136T  1.14T  /data_pool/minio
```

of a pool like this

```sh
# zpool status
  pool: data_pool
 state: ONLINE
  scan: scrub repaired 0B in 04:07:30 with 0 errors on Sun Sep  8 04:31:31 2024
config:

	NAME                        STATE     READ WRITE CKSUM
	data_pool                   ONLINE       0     0     0
	  mirror-0                  ONLINE       0     0     0
	    wwn-0x5000cca400c04d9d  ONLINE       0     0     0
	    wwn-0x5000cca400c049b1  ONLINE       0     0     0
	  mirror-1                  ONLINE       0     0     0
	    wwn-0x5000cca2fecf67a3  ONLINE       0     0     0
	    wwn-0x5000cca2f6c22c09  ONLINE       0     0     0
	  mirror-2                  ONLINE       0     0     0
	    wwn-0x5000cca400c052f9  ONLINE       0     0     0
	    wwn-0x5000cca400c044c4  ONLINE       0     0     0
	  mirror-3                  ONLINE       0     0     0
	    wwn-0x5000cca400c04f01  ONLINE       0     0     0
	    wwn-0x5000cca400c05256  ONLINE       0     0     0
	  mirror-4                  ONLINE       0     0     0
	    wwn-0x5000cca2fecf7d95  ONLINE       0     0     0
	    wwn-0x5000cca2fecf7e2e  ONLINE       0     0     0
	  mirror-5                  ONLINE       0     0     0
	    wwn-0x5000cca400c05353  ONLINE       0     0     0
	    wwn-0x5000cca2fecf7aeb  ONLINE       0     0     0
	  mirror-6                  ONLINE       0     0     0
	    wwn-0x5000cca400c05316  ONLINE       0     0     0
	    wwn-0x5000cca400c04ea3  ONLINE       0     0     0
```

One of our server connects to one of the MinIO cluster nodes (nautilus1) and has a daily traffic of roughly 3TB.

<img width="1588" alt="Screenshot 2024-09-30 at 17 49 44" src="https://github.com/user-attachments/assets/8310d26d-517f-4f30-8318-31fa5684900d">

## Expected Behavior

We expect that a cluster of 3 nodes to operate stable.

## Current Behavior

Every few days if traffic/utilisation goes up, after some delay, let's say 1 day, one of the nodes goes wild and creates ten thousand of threads, increasing load average of the whole system to over 300,000, and eventually crashes. Upon restarts everything works as usual. 

Last crash was on nautilus2 and it seems it was busy communicating with the main minio server. Please note that our application only ever talks to nautilus1 at the moment. Here are some graphs showing a load average of a few hundred thousand (normal operation is around 5-15), spiked disk latency after a while. It seems to have all started with a spike in network traffic (which can only come from another minio server) and then slowly eating CPU/Memory up until crash.

<img width="1590" alt="Screenshot 2024-09-30 at 17 54 22" src="https://github.com/user-attachments/assets/f71ab5d0-3fe0-4a6a-8ea4-3f8ba88dd9ff">

Looking at process monitors revealed that minio process created ten thousands of threads. The operating system is responsive, disk io is normal, ZFS healthy, no interesting kernel or sys log entries. Just minio not responsive anymore and going crazy until collapse. It appears it goes into a loop creating endless threads until it crashes.

Normal thread count for secondaries (nautilis2 and nautilisu3) is around 2000-3000, .e.g:

<img width="1516" alt="Screenshot 2024-09-30 at 18 16 30" src="https://github.com/user-attachments/assets/3897b286-6f06-41ce-ac1e-1fa02cc2170f">

That being said, we have currently on nautilus1 (which receives the HTTP traffic) a thread count of over 15k.

<img width="1530" alt="Screenshot 2024-09-30 at 18 01 30" src="https://github.com/user-attachments/assets/7a02ba99-0b50-4a42-9fcc-ee50449a2d8b">

Looking at docker logs shows a few errors, and it seems it is related to filesystem issues, but it's unclear whether this is the cause or a result.

```
.....


goroutine 6295360982 gp=0xc5b6af4a80 m=nil [runnable]:
syscall.Syscall(0x102, 0xffffffffffffff9c, 0xc690277b80, 0x1ff)
	syscall/syscall_linux.go:69 +0x25 fp=0xc99aabc938 sp=0xc99aabc8d8 pc=0x492645
syscall.Mkdirat(0xffffffffffffff9c, {0xc672b4b040?, 0x412225?}, 0x1ff)
	syscall/zsyscall_linux_amd64.go:665 +0x73 fp=0xc99aabc980 sp=0xc99aabc938 pc=0x4902b3
syscall.Mkdir(...)
	syscall/syscall_linux.go:272
os.Mkdir.func1()
	os/file.go:304 +0x65 fp=0xc99aabc9b0 sp=0xc99aabc980 pc=0x4c9605
os.ignoringEINTR(...)
	os/file_posix.go:251
os.Mkdir({0xc672b4b040, 0x39}, 0x1?)
	os/file.go:303 +0x59 fp=0xc99aabca08 sp=0xc99aabc9b0 pc=0x4c94b9
github.com/minio/minio/cmd.Mkdir({0xc672b4b040, 0x39}, 0x1ff)
	github.com/minio/minio/cmd/os-instrumented.go:131 +0xdb fp=0xc99aabca78 sp=0xc99aabca08 pc=0x246bbbb
github.com/minio/minio/cmd.osMkdirAll({0xc672b4b040, 0x39}, 0x1ff, {0xc610edea68?, 0x100008551e8?})
	github.com/minio/minio/cmd/os_unix.go:93 +0xe5 fp=0xc99aabcac0 sp=0xc99aabca78 pc=0x246e6c5
github.com/minio/minio/cmd.reliableMkdirAll({0xc672b4b040, 0x39}, 0x1ff, {0xc610edea68?, 0x39?})
	github.com/minio/minio/cmd/os-reliable.go:107 +0x56 fp=0xc99aabcb20 sp=0xc99aabcac0 pc=0x246d7f6
github.com/minio/minio/cmd.mkdirAll({0xc672b4b040, 0x39}, 0x1ff, {0xc610edea68, 0x14})
	github.com/minio/minio/cmd/os-reliable.go:85 +0x175 fp=0xc99aabcb78 sp=0xc99aabcb20 pc=0x246d655
github.com/minio/minio/cmd.(*xlStorage).writeAllDirect(0xc0022ea120, {0x4e43fa8, 0xc6804b0af0}, {0xc672b4b040, 0x41}, 0x2039, {0x4e22120, 0xc638352b40}, 0x241, {0xc610edea68, ...})
	github.com/minio/minio/cmd/xl-storage.go:2125 +0xf0 fp=0xc99aabcca8 sp=0xc99aabcb78 pc=0x25aeed0
github.com/minio/minio/cmd.(*xlStorage).writeAll(0xc0022ea120, {0x4e43fa8, 0xc6804b0af0}, {0xc5fdbfd380, 0xe}, {0xc63316da40, 0x2c}, {0xc99aabe000, 0x2039, 0x2a80}, ...)
	github.com/minio/minio/cmd/xl-storage.go:2213 +0x2fd fp=0xc99aabcd60 sp=0xc99aabcca8 pc=0x25af8fd
github.com/minio/minio/cmd.(*xlStorage).WriteAll(0xc0022ea120, {0x4e43fa8, 0xc6804b0af0}, {0xc5fdbfd380, 0xe}, {0xc63316da40, 0x2c}, {0xc99aabe000, 0x2039, 0x2a80})
	github.com/minio/minio/cmd/xl-storage.go:2259 +0x1d4 fp=0xc99aabcde0 sp=0xc99aabcd60 pc=0x25afc94
github.com/minio/minio/cmd.(*xlStorage).RenameData(_, {_, _}, {_, _}, {_, _}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
	github.com/minio/minio/cmd/xl-storage.go:2741 +0x2492 fp=0xc99aabdbd8 sp=0xc99aabcde0 pc=0x25b3632
github.com/minio/minio/cmd.(*xlStorageDiskIDCheck).RenameData.func2({0x4e43fa8?, 0xc6804b0af0?})
	github.com/minio/minio/cmd/xl-storage-disk-id-check.go:486 +0x1b7 fp=0xc99aabdf30 sp=0xc99aabdbd8 pc=0x2570ed7
github.com/minio/minio/internal/ioutil.WithDeadline[...].func1()
	github.com/minio/minio/internal/ioutil/ioutil.go:109 +0x34 fp=0xc99aabdfe0 sp=0xc99aabdf30 pc=0x25bbd74
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc99aabdfe8 sp=0xc99aabdfe0 pc=0x4795e1
created by github.com/minio/minio/internal/ioutil.WithDeadline[...] in goroutine 6295360981
	github.com/minio/minio/internal/ioutil/ioutil.go:108 +0x14c

runtime stack:
runtime.throw({0x2e19c6e?, 0xc000063da8?})
	runtime/panic.go:1023 +0x5c fp=0xc000063d80 sp=0xc000063d50 pc=0x43e1fc
runtime.newosproc(0xc5b86b8008)
	runtime/os_linux.go:195 +0x176 fp=0xc000063df0 sp=0xc000063d80 pc=0x43af36
runtime.newm1(0xc5b86b8008)
	runtime/proc.go:2701 +0xbf fp=0xc000063e30 sp=0xc000063df0 pc=0x44545f
runtime.newm(0x100000001?, 0xc000096508, 0x0?)
	runtime/proc.go:2676 +0x125 fp=0xc000063e60 sp=0xc000063e30 pc=0x445325
runtime.startm(0xc000096508?, 0x0, 0x0)
	runtime/proc.go:2870 +0x158 fp=0xc000063eb0 sp=0xc000063e60 pc=0x445918
runtime.handoffp(0xc0ffffffff?)
	runtime/proc.go:2911 +0x336 fp=0xc000063ed8 sp=0xc000063eb0 pc=0x445dd6
runtime.retake(0x1cdf92f969049f)
	runtime/proc.go:6165 +0x23d fp=0xc000063f38 sp=0xc000063ed8 pc=0x44dbfd
runtime.sysmon()
	runtime/proc.go:6071 +0x345 fp=0xc000063fa0 sp=0xc000063f38 pc=0x44d8a5
runtime.mstart1()
	runtime/proc.go:1729 +0x93 fp=0xc000063fc8 sp=0xc000063fa0 pc=0x443eb3
runtime.mstart0()
	runtime/proc.go:1686 +0x76 fp=0xc000063ff8 sp=0xc000063fc8 pc=0x443df6
runtime.mstart()
	runtime/asm_amd64.s:394 +0x5 fp=0xc000064000 sp=0xc000063ff8 pc=0x4776a5
....
```

More logs here https://gist.github.com/marcj/62e728099dbb2ff1368e30a4a3966c57
Unfortunately the logs outputted by minio inside docker does not have a timestamp.

## Possible Solution

No known solution. Any idea what we can do to get more information? Is the issue known, or are we using it incorrectly?

## Steps to Reproduce (for bugs)

No way to reproduce it easily, if at all.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Can you use our recommended setup with XFS?

**Comment by marcj** [comment]
Unfortunately not, no. Is ZFS not supported?

**Comment by harshavardhana** [comment]
> Unfortunately not, no. Is ZFS not supported?

No we never test with ZFS anymore. So we have no idea what this might be.

Mostly an upgrade here would fix the problem as we have fixed a whole bunch of problems since then.

But I would recommend that you should migrate to XFS from ZFS

**Comment by marcj** [comment]
May I ask why? ZFS is in my opinion superior in many ways. ZFS is one of our cornerstones in our infrastructure and we can not replace it for a single service to a FS like XFS that we have no tools or experience with. The risk would be unreasonable.

I understand that you want to minimise maintainability and reduce the usage to a very small set of potential FS, but for us this would mean to switch to something else.

While the error logs indicate an issue in ZFS, I think the likelihood of that being the case on two separate machines at around the same time for a simple very common syscall like `mkdir` is exceedingly low. Given the thread count, the load average, and the panics in MinIO it indicates to me that this is an issue with MinIO not handling mkdir failures correctly, or maybe mkdir failure is the result of spinning up ten thousand of threads all calling mkdir, cause vs effect. We will update to newest MinIO version soon and report back.

**Comment by klauspost** [comment]
> May I ask why? ZFS is in my opinion superior in many ways. 

MinIO will stress the file system beyond much other software. ZFS provides layers of abstractions and features that provide no benefits, but act as potential barrier to performance with non-deterministic behavior. Therefore we want the simplest; XFS with JBOD.  ZFS is a feature trap, where the complexity makes the system unpredictable.

We do standard file system calls. There is nothing magic. I am not sure how you can "[be] handling mkdir failures correctly". mkdir shouldn't fail in the first place - but in your case it more looks like mkdir calls are never returning, or extremely slow to return and not failing. That should never happen, but you may be hitting a ZFS bug or limitation. If ZFS breaks underneath there isn't really much we can do.

We can't really offer more debugging as a community service. Feel free to reach reach out if you want to engage in a commercial manner (though it will not change that you should move away from ZFS and add one or more nodes for production-quality setup).

**Comment by marcj** [comment]
> We do standard file system calls. There is nothing magic. I am not sure how you can "[be] handling mkdir failures correctly". mkdir shouldn't fail in the first place - but in your case it more looks like mkdir calls are never returning, or extremely slow to return and not failing. That should never happen, but you may be hitting a ZFS bug or limitation. If ZFS breaks underneath there isn't really much we can do.

There are two ways to look at this: 

1. Either ZFS has a fundamental issue with timeouts and thus MinIO goes into a unstable branch bringing down its whole system by creating absurd amount of threads
2. or MinIO has an issue spinning up excessive threads creating absurd amount of syscalls, which eventually leads to a timeout of the FS. 

It's unclear whether the ZFS timeout is the cause or an effect. It seems to me the latter is the case since I debugged live the system during the outage pointed out above while MinIO was hogging resources. ZFS did not have any failures or higher latencies up until the point MinIO produced ten thousand of threads and created a load average of several hundred thousand, overloading the whole system. 
We also see in the graphs above that the FS latency spiked only after MinIO consumed excessive resources.

Therefore it is for me reasonable to assume that MinIO entered a path or deadly loop where it created more and more threads, all creating syscalls so that eventually the FS has to timeout due to the sheer volume of calls. A switch to a different FS will not fix this issue. The problem appears to lie with MinIO’s resource management, particularly in its unbounded creation of threads.

While ZFS might have experienced timeouts or higher latencies, it was likely a consequence of MinIO’s excessive resource consumption. The filesystem didn’t exhibit issues until MinIO overwhelmed the system with load, which suggests that the root cause is MinIO’s behavior rather than a fundamental issue with ZFS.

> I am not sure how you can "[be] handling mkdir failures correctly"

A normal way to handle timeouts of syscalls (or any function call) is to back off and report accordingly if out of expected distribution of timeouts. Linux in default configuration is not a real-time kernel so is fundamentally non-deterministic, which needs to be handled correctly. Like with any resource handling it's reasonable to implement some way to back off and apply limits if the resources is overloaded in one way or another, to avoid a crash. But I don't think a timing out or slow FS is the issue here. If this is the case MinIO should just get slow, not crash. Instead what we see is that MinIO creates an absurd amount of load.

 > If ZFS breaks underneath there isn't really much we can do.

I'm not sure I'd call a timeout a "break". There can be many situations where a FS timeout can happen. 

1. System temporarily overloaded
2. (self-healing) Hardware issue
3. Userland code produced to many calls due to a bug

In any case, the fundamental issue here is unlikely the FS, but the fact that MinIO created ten thousand of threads creating a load average of hundreds of thousands overloading everything. This should never happen. No matter what underlying system is timing out. It's fine to get slow if the underlying resources are slow, but it's not fine to me to keep creating threads and syscalls with the assumption that they return in an fixed time window without back off. 

I think the underlying issue here is that an excessive amount of threads are created for unknown reason. Maybe the initial reason was a FS timeout, maybe something else, who knows. It shouldn't really matter what exactly caused it, since not this cause brought down the system, but the fact that MinIO created an excessive amount of threads and overloaded everything.


```
runtime stack:
runtime.throw({0x2e19c6e?, 0xc000063da8?})
	runtime/panic.go:1023 +0x5c fp=0xc000063d80 sp=0xc000063d50 pc=0x43e1fc
runtime.newosproc(0xc5b86b8008)
	runtime/os_linux.go:195 +0x176 fp=0xc000063df0 sp=0xc000063d80 pc=0x43af36
runtime.newm1(0xc5b86b8008)
	runtime/proc.go:2701 +0xbf fp=0xc000063e30 sp=0xc000063df0 pc=0x44545f
```

So, maybe reasonable and straightforward fix is to limit the number of threads MinIO can spawn. Proper handling of timeouts, back-off strategies, and resource limits would prevent MinIO from escalating the issue to the point of system overload. 

In essence, the system should degrade gracefully (e.g., slower performance) rather than fail completely due to runaway thread creation. Even if the filesystem or some other resource temporarily slows down, MinIO should be able to handle that without spinning out of control. Limiting threads and implementing more robust back-off mechanisms is essential for stability.

**Comment by klauspost** [comment]
@marcj Feel free to reach out on `sales@min.io`, if you want to discuss this further.

**Comment by harshavardhana** [comment]
Upgrade first, we had a bug where a runaway number of goroutines would get created stuck on an unresponsive drive.

Rest we can argue at length, we recommend XFS, jbod in that pattern. 

Anything outside is not supported, we really don't have the cycles to test every single artisanal filesystems out there. 

We want backend filesystems to do exactly what XFS does and leave it at that. ZFS does way too many things, this applies to btrfs, cephfs, lustre and every other other such filesystems.
