### ISSUE TITLE
Not enough online disks to calculate the available space

### ISSUE THREAD

**Issue by Hintic** [minio/minio#20491]
## NOTE
1. MinIO Deployment Architecture: We have deployed a MinIO setup in the Kubernetes cluster with four MinIO pods, and each pod has four drives. That’s a total of 16 drives across the MinIO pods.
2. Not Enough Online Disks Error: One of our MinIO pods intermittently encounters the error message: “Not enough online disks to calculate the available space, expected (9)/(4).” The number after “expected” varies between 4, 6, or other values.
3. Log Disappearance and Pod Recreation: The error logs sometimes disappear automatically, but at other times, we need to recreate the pod to clear the error. However, after some time, the issue reappears.
4. Diskinfo and Health Status: Upon inspecting the source code, we found that the error occurs when the healthy diskinfo doesn’t meet the minimum requirement (half of the expected disks). However, when we use `mc admin info`, it reports healthy status, and monitoring alerts show no anomalies.
5. Inode Expansion: We attempted to address the issue by expanding the inodes on relevant disks, but this didn’t resolve the problem.
6. DNS Resolution and Network Issues: There was a past issue with DNS domain resolution between nodes, leading to network packet loss. Although we have resolved this, the sporadic MinIO error persists.
7. Version Upgrade Constraints: Unfortunately, due to certain reasons, we are unable to perform a version upgrade at the moment.
8. Impact on Upper Layer Services: This error directly affects upper-layer services, causing uploads to fail with the message: “Resource requested is unreadable, please reduce your request rate.”

source code：
![1727404809083](https://github.com/user-attachments/assets/71f0f6a1-c44e-4bac-92a3-c630dd030d81)

error info：
![error](https://github.com/user-attachments/assets/0e367076-e948-44fb-ab08-d3860ff368fe)

## Expected Behavior
Abnormal disappearance, CLI uploads normally

## Current Behavior
Intermittent errors occur when the upper-level service is uploaded.

## Possible Solution
1. Domain name resolution failure and other network problems.
2. Caused by insufficient inodes, but the disk inodes have been checked and expanded

## Your Environment
* Version used (`minio --version`): [RELEASE.2023-03-24T21-41-23Z]

**Comment by harshavardhana** [comment]
Please upgrade to latest release.
