### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by jamesla** [minio/minio#20502]
I'm deploying Minio using the helm chart in this repository.

It works fine but when I try and upload files to it I get the error "Payload Too Large"

I have read through the helm chart in this repos values file and can't seem to see where to set the maximum file size.

How can I modify the maximum file size for minio objects?

**Comment by harshavardhana** [comment]
@jamesla there is a reason we have the issue template, please explain yourself. This issue is non-actionable for us. 

"Payload Too Large" looks like your load balancer limit.

**Comment by hanisntsolo** [comment]
Just modify the client-max-body-size property in your reverse proxy if not accessing directly 


	gzip                          on;
	proxy_ignore_client_abort     off;
	client_max_body_size          200000m; # 200GB. You can just change this property. by default its just 2 GB so anything greater than 2GB will give payload too large.
	server_names_hash_bucket_size 1024;
