### ISSUE TITLE
High memory consumption during scanner works

### ISSUE THREAD

**Issue by yotles** [minio/minio#20505]
* minio version: RELEASE.2024-06-22T05-26-45Z
* deployment: 9 identical HW servers with 3 disks(SSD) in each.
* 1 bucket ~ 55.6 Mil objects

We started to log OOM with minio process, during scanner cycle applying on node. In cluster each node have 12GB RAM and works properly with usual load(consumption about 1-2GB). And after start scanner memory consumption run fast.
<img width="726" alt="Screenshot 2024-10-01 at 17 11 57" src="https://github.com/user-attachments/assets/8a86d240-4042-45e3-b2f7-4a88becbf984">

Want to note that scanner often choose 3 disks on the same node in my installation, as I understand there is no way to affect on it. 
So in documentation present recommendations for RAM in context concurrent requests on a nodes, that not my case. Also I can see general recommendations: 8GiB RAM - for Up to 1 Tebibyte (Ti) which executed by me. How I should calculate proper RAM size for our nodes in cluster to not OOM during scanner run?  Is there some specifications about it? Changing MINIO_SCANNER_SPEED will change something? Thanks.

**Comment by klauspost** [comment]
Use prefixes and don't dump all objects in the root of the bucket as per https://min.io/docs/minio/linux/administration/object-management.html#object-organization-and-planning
