### ISSUE TITLE
Support search objects by ETag or Hash

### ISSUE THREAD

**Issue by amone-bit** [minio/minio#20503]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I hope I can also ensure the existence of object by ETag or Hash rather than only by the object name.

**Describe alternatives you've considered**
use database out of MinIO to complete it.

**Additional context**

**Comment by klauspost** [comment]
Unfortunately the S3 API does not have such functionality.

**Comment by amone-bit** [comment]
Can we only add the feature in MinIO without breaking compatibility with s3? I don't understand why we need S3 API has such functionality.

**Comment by klauspost** [comment]
@amone-bit No. We are not interested in such a feature.

**Comment by harshavardhana** [comment]
@amone-bit this is exactly the reason we built mincat product, you should consider an enterprise license to try this product.
