### ISSUE TITLE
MySQL couldn't receive delete events

### ISSUE THREAD

**Issue by GX-Wang** [minio/minio#20515]
## Expected Behavior
Delete events should push to mysql

## Current Behavior
I just encounter a  issue that mysql couldn't receive delete event from minio and it is normal for put&get event ,  mysql version 5.7.44 , minio version RELEASE.2024-09-22T00-33-43Z (commit-id=03e996320ebb887112fb2a15c6f27936e5f124a0)

## Steps to Reproduce (for bugs)
1. delete a file from the minio console

## Your Environment

 mysql version 5.7.44 , 
minio version RELEASE.2024-09-22T00-33-43Z (commit-id=03e996320ebb887112fb2a15c6f27936e5f124a0)

**Comment by harshavardhana** [comment]
what is your event configuration look like `mc event list alias/bucket` ?

**Comment by GX-Wang** [comment]
![image](https://github.com/user-attachments/assets/00395ca5-9333-4059-92c2-04cf98d77dd3)
I cofigured it directly  from console

**Comment by harshavardhana** [comment]
By default mysql gets configured as `namespace` events what is your MySQL target configured as?

**Comment by GX-Wang** [comment]
it is configured as 'namespace'

**Comment by GX-Wang** [comment]
MySQL logs the event with the event name 's3:ObjectAccessed:Head'  ()  when I perform the delete operation. I assume that is a record of double check operation not a record of delete event. pls correct me if  I am wrong.

**Example**
{
    "Records": [
        {
            "eventVersion": "2.0",
            "eventSource": "minio:s3",
            "awsRegion": "",
            "eventTime": "2025-10-03T01:17:44.309Z",
            "eventName": "s3:ObjectAccessed:Head",
            "userIdentity": {
                "principalId": "myminioadmin"
            },
            "requestParameters": {
                "principalId": "myminioadmin",
                "region": "",
                "sourceIPAddress": "192.168.224.1"
            },
            "responseElements": {
                "content-length": "106434",
                "x-amz-id-2": "dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8",
                "x-amz-request-id": "186AD654D6B408B5",
                "x-minio-deployment-id": "abfd0391-cde2-4b32-8441-f026a33f8270",
                "x-minio-origin-endpoint": "http://192.168.224.128:9000"
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "Config",
                "bucket": {
                    "name": "test",
                    "ownerIdentity": {
                        "principalId": "myminioadmin"
                    },
                    "arn": "arn:aws:s3:::test"
                },
                "object": {
                    "key": "%E5%8F%8B%E6%83%85%E6%8D%90%E8%B5%A0.jpg",
                    "size": 106434,
                    "eTag": "ef2ba8540921a449b8648b60052925cc",
                    "contentType": "image/jpeg",
                    "userMetadata": {
                        "content-type": "image/jpeg"
                    },
                    "sequencer": "186AD6537E9305B7"
                }
            },
            "source": {
                "host": "192.168.224.1",
                "port": "",
                "userAgent": "MinIO (linux; amd64) minio-go/v7.0.76 MinIO Console/(dev)"
            }
        }
    ]
}

**Comment by GX-Wang** [comment]
MySQL logs the event with the event name 's3:ObjectAccessed:Head'  when I perform the delete operation. I assume that is a record of double check operation not a record of delete event. pls correct me if I am wrong.

Example
{
"Records": [
{
"eventVersion": "2.0",
"eventSource": "minio:s3",
"awsRegion": "",
"eventTime": "2025-10-03T01:17:44.309Z",
"eventName": "s3:ObjectAccessed:Head",
"userIdentity": {
"principalId": "myminioadmin"
},
"requestParameters": {
"principalId": "myminioadmin",
"region": "",
"sourceIPAddress": "192.168.224.1"
},
"responseElements": {
"content-length": "106434",
"x-amz-id-2": "dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8",
"x-amz-request-id": "186AD654D6B408B5",
"x-minio-deployment-id": "abfd0391-cde2-4b32-8441-f026a33f8270",
"x-minio-origin-endpoint": "http://192.168.224.128:9000"
},
"s3": {
"s3SchemaVersion": "1.0",
"configurationId": "Config",
"bucket": {
"name": "test",
"ownerIdentity": {
"principalId": "myminioadmin"
},
"arn": "arn:aws:s3:::test"
},
"object": {
"key": "%E5%8F%8B%E6%83%85%E6%8D%90%E8%B5%A0.jpg",
"size": 106434,
"eTag": "ef2ba8540921a449b8648b60052925cc",
"contentType": "image/jpeg",
"userMetadata": {
"content-type": "image/jpeg"
},
"sequencer": "186AD6537E9305B7"
}
},
"source": {
"host": "192.168.224.1",
"port": "",
"userAgent": "MinIO (linux; amd64) minio-go/v7.0.76 MinIO Console/(dev)"
}
}
]
}

**Comment by harshavardhana** [comment]
Then you need to set it as audit, if you want to see all entries otherwise the mysql target is a namespace entry map.

There is nothing to record since it's not an audit target it is a key in and key removed (put and delete equivalent)
