### ISSUE TITLE
Batch replication documentation mentions prefix as optional parameter, but doesn't work if omitted

### ISSUE THREAD

**Issue by ssidorenko** [minio/minio#20511]
## Expected Behavior
Batch replication documentation mentions prefix as optional parameter, replicates everything if omitted

## Current Behavior
Batch replication documentation mentions prefix as optional parameter, but replicates nothing.

## Steps to Reproduce (for bugs)
```replicate:
  apiVersion: v1
  source:
    type: s3 # valid values are "s3" or "minio"
    bucket: abc
    endpoint: https://s3.eu-central-1.amazonaws.com/
    path: off
    # endpoint: https://s3.eu-central-1.amazonaws.com/
    credentials:
      accessKey: xx
      secretKey: xx
  target:
    type: minio # valid values are "s3" or "minio"
    bucket: zyx
```

Version:  2024-08-29T01:40:52Z

**Comment by jiuker** [comment]
Upgrade to latest and to see what happened

**Comment by harshavardhana** [comment]
This is fixed in latest release.
