### ISSUE TITLE
Audit log with unable to heal 0 corrupted blocks

### ISSUE THREAD

**Issue by Solvik** [minio/minio#20513]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I was trying to understand a high `minio_heal_objects_heal_total` metric and looking at the audit logs I have hundreds of thousands of lines `unable to heal 0 missing blocks on drives` and `unable to heal 0 corrupted blocks on drive`

I have the case on bucket objects but also on "systems" objects such as the `.minio.sys` bucket and `buckets/mypersonalbucket/.usage-cache.bin` objects

## Expected Behavior

I'm not sure it should log it couldn't heal 0 blocks, it means there's nothing to heal ?

## Current Behavior

N/A

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

N/A

## Context

I'm trying to understand an elevated heal metrics

## Regression

I think it's a regression [introduced here](https://github.com/minio/minio/commit/e7a56f35b9bc8e782a4b0864c92627dfab2b3853) which is included in the version I'm running

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-08-26T15-33-07Z (commit-id=1c4d28d7af0373cde810703839a179739dbe6f34)
* Server setup and configuration: 4x 24
* Operating System and version (`uname -a`): `Ubuntu 22.04` / `Linux minio1-node2.pr.par5.numberly.net 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is not a regression as such; it was created to reduce the number of audit logs. Audit log has sufficient information to understand the final location of the object. 

You have some production issues on the setup that require immediate attention https://min.io/pricing is the right way to go, all the tooling that helps debug your problem requires an active subscription with us.

**Comment by harshavardhana** [comment]
`0 corrupted` blocks looks like a wrong indication, will fix it.
