### ISSUE TITLE
when I choose CRC32C to use PutObject API, the ETag still return MD5

### ISSUE THREAD

**Issue by amone-bit** [minio/minio#20520]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

when I choose CRC32C to use PutObject API, the ETag still return MD5

## Expected Behavior
I think the ETag will be CRC32C rather than MD5

## Current Behavior
ETag is MD5

## Possible Solution
Modify some relative codes

## Steps to Reproduce (for bugs)
Use PutObject API and print the result

## Regression
No

## Your Environment

* Version used (`minio --version`): RELEASE.2024-10-02T17-50-41Z (commit-id=ded0b19d97bb9f73f4d78382eb131ff80003e272)
* Server setup and configuration: default
* Operating System and version (`uname -a`): windows 11 pro

**Comment by klauspost** [comment]
We must calculate etag to be S3 compliant, but for example encryption disables it - and then it is just a random value.

> I think the ETag will be CRC32C rather than MD5

That is not how S3 works.

Adding `--no-compat` to the server parameters will also cause it to be a random value.
