### ISSUE TITLE
Auto-extraction always extracts files relative to the root of the bucket

### ISSUE THREAD

**Issue by Ocarthon** [minio/minio#20527]
Hey everyone,

we want to use the auto-extract feature for our workflow. After reading the [minio announcement](https://blog.min.io/minio-optimizes-small-objects/), the initial PR of this feature (https://github.com/minio/minio/pull/11849) and the AWS reference (https://docs.aws.amazon.com/snowball/latest/developer-guide/batching-small-files.html), it seems to not correctly handle the directory where the archive is put into.

While i understand that this feature only took inspiration from the aws feature, IMO it makes sense to also replicate this behavior regarding sub directories

## Expected Behavior

When an archived is uploaded and the auto-extract feature enabled, the archive should be extracted relative to where the archive would have been placed:

```bash
mc mb minio/extract-test
mc cp archive.tar.gz minio/extract-test/subdir/archive.tar.gz --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true"
mc ls -r minio/extract-test
> [2024-10-06 14:51:04 CEST]     0B STANDARD subdir/
> [2024-10-06 14:51:04 CEST]     4B STANDARD subdir/a.txt
> [2024-10-06 14:51:04 CEST]     0B STANDARD subdir/dir/
> [2024-10-06 14:51:04 CEST]     4B STANDARD subdir/dir/b.txt
```

## Current Behavior

The extract archive files are placed relative to the bucket root. When you upload your archive into subdirectory, the files get extracted in the root of the bucket:

```bash
mc mb minio/extract-test
mc cp archive.tar.gz minio/extract-test/subdir/archive.tar.gz --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true"
mc ls -r minio/extract-test                                                                                                     
> [2024-10-06 14:50:57 CEST]     4B STANDARD a.txt
> [2024-10-06 14:51:04 CEST]     0B STANDARD dir/
> [2024-10-06 14:51:04 CEST]     4B STANDARD dir/b.txt
```

## Possible Solution

Replicate the aws behavior and extract the files relative to where the archive has been uploaded to.

Quote from https://docs.aws.amazon.com/snowball/latest/developer-guide/batching-small-files.html
> The archive file will be extracted in the same directory it is stored in and the folder structures will be built out accordingly.

## Steps to Reproduce (for bugs)

Content of `archive.tar.gz`:
```bash
tar ztf archive.tar.gz
> ./
> ./a.txt
> ./dir/
> ./dir/b.txt
```

```bash
mc mb minio/extract-test
mc cp archive.tar.gz minio/extract-test/subdir/archive.tar.gz --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true"
mc ls -r minio/extract-test                                                                                                     
```

## Your Environment
``` bash
bash-5.1# minio --version
minio version RELEASE.2024-10-02T17-50-41Z (commit-id=ded0b19d97bb9f73f4d78382eb131ff80003e272)
Runtime: go1.22.8 linux/arm64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```

**Comment by klauspost** [comment]
The path you provide on your object is ignored. You can add a `X-Amz-Meta-Minio-Snowball-Prefix=prefix/` header to your call, if you'd like to have a specific prefix.  (And `X-Amz-Meta-Minio-Snowball-Ignore-Dirs=true` is also recommended).

We cannot change this, as it would break existing use.
