### ISSUE TITLE
Debian backport kernel + zfs filesystem performance issues

### ISSUE THREAD

**Issue by sidboy55555** [minio/minio#20526]
## Expected Behavior
Uploading a 1GB file or backup to Minio should take only a few seconds, as observed when using the default Debian kernel with ZFS.

## Current Behavior
When uploading a 1GB file to the Minio server on the **linux-image-6.9.7+bpo-amd64** kernel, the upload performance drops significantly. The same upload, which usually takes a few seconds, now takes up to **3 minutes**—an increase of over **400%**.

Additionally, uploads of 40GB or more are failing because the operation takes too long.

- Disk performance has been tested separately with no issues.
- The network between servers is functioning correctly.
- The performance degradation is noticeable specifically in the `.minio.sys/tmp` directory, where writing the 5GB backup block is significantly slower on this kernel version.

## Steps to Reproduce
1. Install Debian 12 from scratch.
2. Follow the [OpenZFS install guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/index.html).
3. Create a ZFS array with two disks and configure two ZIL logs on other disks, and the options mentioned below.
4. Install Minio and configure its data directory to use the ZFS disk.
5. Install the backport kernel using:
   ```bash
   apt-get install linux-image-6.9.7+bpo-amd64 linux-headers-6.9.7+bpo-amd64
   ```
6. Restart into the newly installed kernel and notice the performance drop during file uploads to Minio.

## Context
I am using the newer kernel for better compatibility with new hardware and additional features. However, this performance issue significantly impacts my workflow when uploading backups to Minio.

## Regression
- **Minio Version**: RELEASE.2024-09-09T16-59-28Z
- I'm unsure if it qualifies as a regression.

## Your Environment
- **Minio Version**: RELEASE.2024-09-09T16-59-28Z
- **Server Setup and Configuration**:
  - ZFS pool with 2x16TB disks (entire disks)
  - ZFS settings: `ashift=12`, `relatime=on`, `atime=off`, `compression=zstd-19`, `secondarycache=none`, `dedup=on`, `sync=always`
  - ZIL stored on mirrored NVMe partitions (2x8GB)
- **Operating System and Kernel**: Debian 12
  - **With Issue**: `linux-image-6.9.7+bpo-amd64`
  - **Without Issue**: `linux-image-6.1.0-26-amd64`

**Comment by klauspost** [comment]
We don't do Linux Kernel or ZFS support. Ask in the appropriate forums. We don't use any particular magic to file files, just write with odirect and fdatasync.

We recommend XFS as file system.

**Comment by sidboy55555** [comment]
The only reason I created this issue is that someone directed me here from the Minio slack chats. For me, it works on linux-image-6.1.0-26-amd64, as my backup system runs on older hardware, so I'm all set. Just trying to help out the community here.
![image](https://github.com/user-attachments/assets/8f11ebdd-4496-4619-aab4-95451738f1c9)

**Comment by klauspost** [comment]
Sure. I don't think @ravindk89 is that much into system details.
