### ISSUE TITLE
false positive healthcheck during service outage

### ISSUE THREAD

**Issue by yotles** [minio/minio#20535]
In my minio cluster 1 node was updated by accident from `20240622052645.0.0-1` to `20240622052645.0.0-1`. After service restart node not joined cluster with errors, as it expected as I understand, because binaries on all nodes should be updated and simultaneously restarted with `mc admin service restart`. 
Internal healthcheck `minio/health/live` used by consul to announce service to clients, and in this case I'm trying to find correct way detect such service drift.

Errors:
`1: internal/grid/connection.go:275:grid.newConnection.func3()
API: SYSTEM.grid
Error: grid: http://minio-c1-p1-1:9000 re-connecting to http://minio-1-c1-p1-1>
6: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
5: internal/logger/logonce.go:149:logger.LogOnceIf()
4: internal/grid/connection.go:59:grid.gridLogOnceIf()
3: internal/grid/connection.go:672:grid.(*Connection).connect.func1()
2: internal/grid/connection.go:678:grid.(*Connection).connect()
1: internal/grid/connection.go:275:grid.newConnection.func3()`

```go 
  mcli admin info local:

  minio-c1-p1-1:9000
   Uptime: offline

  minio-c1-p1-2:9000
   Uptime: offline

  minio-c1-p1-3:9000
   Uptime: initializing
```

service minio not in status running:

```go
   Loaded: loaded (/usr/lib/systemd/system/minio.service; enabled; vendor preset: disabled)
   Active: activating (start) since Tue 2024-10-08 08:40:09 UTC; 36s ago
```

But at the same time internal healthcheck return 200:

```go 
curl -I http://localhost:9000/minio/health/live
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Id-2: 2d373614bb7f80d7aa0c904a0d3df47372d8e60a84cee8ef1cb0b7c7906a1265
X-Amz-Request-Id: 17FC70CC3C395389
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Tue, 08 Oct 2024 09:39:39 GMT
```

## Expected Behavior
If node not joined cluster correctly should be unhealthy respond.

## Current Behavior
Node restarted and not ready to accept requests from clients but respond with healthy answer.

**Comment by harshavardhana** [comment]
liveness is not the health of the system, it is only returns 200 OK if the port is reachable, to know if the cluster itself has quorum you need to use `/minio/health/cluster`

This is documented already at length https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html#id2

**Comment by harshavardhana** [comment]
or use `mc admin service restart --wait` to wait for all services (cluster health to report 200 OK)

**Comment by yotles** [comment]
@harshavardhana Thank you for answer. This issue happened not during upgrade process. I want to prevent such cases in future and trying to understand is there any solution to check without tcp check port that local node healthy, not cluster in general?

**Comment by harshavardhana** [comment]
> @harshavardhana Thank you for answer. This issue happened not during upgrade process. I want to prevent such cases in future and trying to understand is there any solution to check without tcp check port that local node healthy, not cluster in general?

The cluster health check is per node basis - the returned information is provided from that nodes perspective.

https://github.com/minio/minio/blob/master/.github/workflows/mint/minio-erasure.yaml#L16

Observe how this is used in docker environments.

```

97cb050cbfac   y4m4/minio:eos        "/usr/bin/docker-ent…"   2 days ago   Up 2 days (healthy)   9000-9001/tcp      eos-minio4-1
...

```
