### ISSUE TITLE
Azure Tier broken after Minio upgrade

### ISSUE THREAD

**Issue by bjornuppeke** [minio/minio#20531]
After upgrading from `RELEASE.2023-03-24T21-41-23Z` to `RELEASE.2024-07-16T23-46-41Z` existing Azure Tiers are broken. Transition rules are timing out and CRUD operations fail due to an unresolvable hostname. 

## Expected Behavior
After upgrading, existing Azure Tiers should work just like they did prior to the upgrade. There is no information in any release notes that say otherwise.

## Current Behavior
All Azure Tier communication is failing. We have a Lifecycle Transition Rule on a bucket that is configured to use the Azure Tier. The transitions are failing with following error:

```
    1: cmd/bucket-lifecycle.go:495:cmd.(*transitionState).worker()
    2: cmd/logging.go:120:cmd.transitionLogIf()
    3: internal/logger/logger.go:268:logger.LogIf()
Error: Transition to AZURECOLD failed for container/bucketname/prefix/object. version: with Operation timed out (*fmt.wrapError)
  DeploymentID: 99afcd37-0f83-421b-a10d-cb66c652bdd1
  Time: 19:45:23 UTC 10/07/2024
  API: SYSTEM.transition
```

When trying to download an object located in the Azure Tier the request times out.

When trying to delete objects located in the Azure Tier with `mc rm` the following error is found in the logs:

```
    1: cmd/bucket-lifecycle.go:345:cmd.(*expiryState).Worker()
    2: cmd/logging.go:120:cmd.transitionLogIf()
    3: internal/logger/logger.go:268:logger.LogIf()
  (*pipeline.pcError)
Delete "http://blob.core.windows.net/accountname/prefix/...?timeout=61": dial tcp: lookup blob.core.windows.net on 10.0.0.10:53: no such host

HTTP request failed
Error: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, github.com/Azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
DeploymentID: 79a29093-0787-4e64-90c2-64edc87bffc0
Time: 09:34:04 UTC 10/07/2024
API: SYSTEM.transition
```

Requests are sent to `blob.core.windows.net` which is an unresolvable hostname. Azure storage accounts hosts are prefixed with the accountname.

I assume that the older version of Minio we had, prefixed the hostname automatically with the accountname on Azure Tiers. With this new version that is not happening. Can this have something to to with https://github.com/minio/minio/pull/19188?

## Possible Solution
- Make sure Azure Tier requests are sent with a correctly formatted hostname. 
- Make it possible to change the `endpoint` of an existing Azure Tier.

## Steps to Reproduce (for bugs)
1. Create an Azure Tier with Minio `RELEASE.2023-03-24T21-41-23Z`.
2. Update Minio to `RELEASE.2024-07-16T23-46-41Z`

## Context
This is a pretty big problem for us because we've basically lost all Tiered data. Sure, the data is still there in Azure. But it can't be accessed by our applications that use Minio as storage interface.

We can't create a new Tier pointing to the same Blob Storage Container because Minio doesn't allow it. Which is understandable due to the potential conflicts that would cause.

## Regression
Yes
`RELEASE.2023-03-24T21-41-23Z` to `RELEASE.2024-07-16T23-46-41Z`
Potentially https://github.com/minio/minio/pull/19188

## Your Environment
Kubernetes v1.30.3 on Azure AKS
Minio Operator v6.0.3

**Comment by harshavardhana** [comment]
fixed in #20247 please upgrade to latest release
