### ISSUE TITLE
MinIO keeps reading/write to disk

### ISSUE THREAD

**Issue by francoism90** [minio/minio#20534]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

When MinIO (Podman container) is not in use/accessed, it keeps reading/writing to disk.

I don't mind the reading, but it's every 1-3 seconds writing something to disk.

## Current Behavior

![image](https://github.com/user-attachments/assets/86e46d9f-a803-409a-9011-aaf36d7045f2)

The disk write total is only from ~12 hours being active (without restarting the service - and not accessing MinIO).

## Possible Solution

Please explain why this is happening, I don't think it's desired when using a SSD/NVMe (consumer in this case). This would mean MinIO would write ~2GB each day to disk (in my case). The buckets are around ~150GB in usage.

It seems to create an additional volume:

```bash
$ podman volume inspect fff5c64ed88721dca42f9c2a4d31093461fdd15f185bb0fbd140d1037ca7c1d2
[
     {
          "Name": "fff5c..",
          "Driver": "local",
          "Mountpoint": "/var/home/user/.local/share/containers/storage/volumes/fff5c../_data",
          "CreatedAt": "2024-10-07T19:55:30.348110749+02:00",
          "Labels": {},
          "Scope": "local",
          "Options": {},
          "Anonymous": true,
          "MountCount": 0,
          "NeedsCopyUp": true,
          "NeedsChown": true,
          "LockNumber": 14
     }
]
```

Is this is what being called/used as cache or temp location?
Could this be mounted on /tmp?

## Steps to Reproduce (for bugs)

This is a systemd service (Podman Quadlet + SELinux):

```bash
[Unit]
Description=Minio container

[Service]
TimeoutStartSec=300
Restart=always

[Container]
Image=docker.io/minio/minio:latest
AutoUpdate=registry
Exec=minio server /data/minio --console-address ":8900"
Volume=my-minio:/data/minio:rw,Z,U
LogDriver=none
Network=traefik.network
ExposeHostPort=8900
ExposeHostPort=9000

[Install]
WantedBy=multi-user.target
```

## Context

I'm using MinIO with Podman Quadlet.

## Regression

I don't know, sorry.

## Your Environment

```$ minio --version
minio version RELEASE.2024-10-02T17-50-41Z (commit-id=ded0b19d97bb9f73f4d78382eb131ff80003e272)
Runtime: go1.22.8 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.```

```$ uname -a
Linux desktop 6.11.2-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  4 16:44:08 UTC 2024 x86_64 GNU/Linux
```

This on Fedora Silverblue 41 (beta) with Podman 5.2.3.

**Comment by harshavardhana** [comment]
yes that is normal, it is part of the health check, you don't want that 

```
_MINIO_DRIVE_ACTIVE_MONITORING=off
```

set this, of course you open yourself to drive failures and we not being 
able to detect such failures. 

The choice is yours.

**Comment by francoism90** [comment]
@harshavardhana Thanks for your reply. :)

Is the `_` prefix required?

It seems related to this https://github.com/minio/minio/discussions/15705, but you cannot lower the frequency, instead of disabling it completely?

And what does the second volume do? Why is this being created?

**Comment by harshavardhana** [comment]
> Is the `_` prefix required?

yes it is required, we do not want our customers to disable this. It is meant for cases such as yours that do not care much about this anyway.

> It seems related to this #15705, but you cannot lower the frequency, instead of disabling it completely?

No

> And what does the second volume do? Why is this being created?

We do not create any second volume automatically, and it must be because of Dockerfile.release

```
VOLUME ["/data"]
```

**Comment by francoism90** [comment]
@harshavardhana Thanks again, I'll change the volume mount point. :)
