### ISSUE TITLE
PutObject snowball Response Etag is always different

### ISSUE THREAD

**Issue by xiangjs6** [minio/minio#20537]
## Expected Behavior

When I use PutObject with x-amz-meta-snowball-auto-extract: true for the same tar file, I hope to return ETag consistency

## Current Behavior
I use PutObject with x-amz-meta-snowball-auto-extract: true for the same tar file, Every time the ETag is inconsistent

## Steps to Reproduce (for bugs)

1. mkdir test-snowball
2. echo hello > test-snowball/myobject-1
3. tar -cf batch01.tar test-snowball
4. aws s3 cp batch01.tar s3://pool/batch01.tar --metadata snowball-auto-extract=true --endpoint http://0.0.0.0:9000 --debug 2>&1 | grep ETag
5. repeat 4 step

```
# aws s3 cp batch01.tar s3://pool/batch01.tar --metadata snowball-auto-extract=true --endpoint http://192.168.5.109:9001 --debug 2>&1 | grep ETag                                        ✔ 
2024-10-09 11:46:48,042 - ThreadPoolExecutor-0_0 - botocore.parsers - DEBUG - Response headers: {'Accept-Ranges': 'bytes', 'Content-Length': '0', 'ETag': '"ba8b82b458a963077ed9b6f8b88468a3"', 'Server': 'MinIO', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Origin, Accept-Encoding', 'X-Amz-Id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8', 'X-Amz-Request-Id': '17FCAB9F96359CDD', 'X-Content-Type-Options': 'nosniff', 'X-Ratelimit-Limit': '3329', 'X-Ratelimit-Remaining': '3329', 'X-Xss-Protection': '1; mode=block', 'Date': 'Wed, 09 Oct 2024 03:37:38 GMT', 'Connection': 'close'}
# aws s3 cp batch01.tar s3://pool/batch01.tar --metadata snowball-auto-extract=true --endpoint http://192.168.5.109:9001 --debug 2>&1 | grep ETag                                        ✔ 
2024-10-09 11:46:50,720 - ThreadPoolExecutor-0_0 - botocore.parsers - DEBUG - Response headers: {'Accept-Ranges': 'bytes', 'Content-Length': '0', 'ETag': '"9deed711fceb069c7aafb04602ac1286"', 'Server': 'MinIO', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Vary': 'Origin, Accept-Encoding', 'X-Amz-Id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8', 'X-Amz-Request-Id': '17FCABA035CF528A', 'X-Content-Type-Options': 'nosniff', 'X-Ratelimit-Limit': '3329', 'X-Ratelimit-Remaining': '3329', 'X-Xss-Protection': '1; mode=block', 'Date': 'Wed, 09 Oct 2024 03:37:41 GMT', 'Connection': 'close'}
```

## Context

I want to know how Snowball's etag is calculated？

## Your Environment

- minio
minio version RELEASE.2024-10-02T17-50-41Z (commit-id=ded0b19d97bb9f73f4d78382eb131ff80003e272)
Runtime: go1.22.8 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

- awscli:
aws-cli/1.34.7 Python/3.12.5 Linux/6.1.111-1-MANJARO botocore/1.34.131

**Comment by harshavardhana** [comment]
A snowball extract is a server side extraction, there is no final ETag here its just bunch of objects untarred on the namespace. 

Not sure what you are looking for.

**Comment by xiangjs6** [comment]
> A snowball extract is a server side extraction, there is no final ETag here its just bunch of objects untarred on the namespace.
> 
> Not sure what you are looking for.

Can you tell me snowball etag calculation algorithm

**Comment by balamurugana** [comment]
> > A snowball extract is a server side extraction, there is no final ETag here its just bunch of objects untarred on the namespace.
> > Not sure what you are looking for.
> 
> Can you tell me snowball etag calculation algorithm

@xiangjs6 Why does it matter?

**Comment by harshavardhana** [comment]
> Can you tell me snowball etag calculation algorithm

that's a wrong question, snowball is meant for extraction of tar server side, returned ETag is of no consequence here.

**Comment by xiangjs6** [comment]
Due to Minio not hashing all the contents of the Snowball PutObject's body and only reading the content that needs to be retrieved, and the network not sending all packets to Minio at once, the ETag has changed.
![Screenshot_20241009_153314](https://github.com/user-attachments/assets/07c21f20-fed4-4621-8616-7e61967d78cf)

![Screenshot_20241009_153250](https://github.com/user-attachments/assets/5113e94a-9e4f-44c3-807b-59d5c21e79db)

**Comment by xiangjs6** [comment]
> > > A snowball extract is a server side extraction, there is no final ETag here its just bunch of objects untarred on the namespace.
> > > Not sure what you are looking for.
> > 
> > 
> > Can you tell me snowball etag calculation algorithm
> 
> @xiangjs6 Why does it matter?

I want to check md5, but I didn't know about md5 before PutObject

**Comment by balamurugana** [comment]
> > > > A snowball extract is a server side extraction, there is no final ETag here its just bunch of objects untarred on the namespace.
> > > > Not sure what you are looking for.
> > > 
> > > 
> > > Can you tell me snowball etag calculation algorithm
> > 
> > 
> > @xiangjs6 Why does it matter?
> 
> I want to check md5, but I didn't know about md5 before PutObject

Why do you want to check hash of md5 of snowball tar file? You should check individual file's hash after snowball upload by Head Object.

**Comment by klauspost** [comment]
@xiangjs6 We do not calculate MD5.
