### ISSUE TITLE
mc mirror command upload and download speed limits do not take effect

### ISSUE THREAD

**Issue by Alexios-cd** [minio/minio#20548]
When using the mc mirror command, add the -- limit-download and -- limit-upload commands, the upload and download speeds are not limited.
![demo](https://github.com/user-attachments/assets/20a1f40e-210f-4ad4-b523-61565a2d479e)

According to the official document, the transmission speed should be 100KiB/s.

**Comment by harshavardhana** [comment]
Server side copy has not bandwidth limits, you need to do either server to local or local to server or server to another server.

To limit bandwidth mc needs to be involved in the data transfer.

What you are doing is server side copy, where we can't do any bandwidth limits.

**Comment by Alexios-cd** [comment]
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/75012269-8724-4e5e-a9d8-89c1bbe8a145">
In the actual test, from the server to the local, the speed limit was made, but it still did not take effect.
