### ISSUE TITLE
Using a metadata field on objects as Object creation/reference date for Object lifecycle management

### ISSUE THREAD

**Issue by sangalao** [minio/minio#20540]
**Is your feature request related to a problem? Please describe.**

I am trying to manage data replication of buckets content from One Minio instance (named "blue") to another Minio instance (named "green").
I need to manage one-time replications from "blue" to" green", with specific folders/files to copy, so I am using "rclone" with "--metadata" to manage this replication.

I encounter an issue for files stored in buckets with specific "Object lifecycle management" configuration, for example with 7 days expiration, as the creation date / modification date of files in Blue Minio are "reset" and changed to upload time when copied on green instance. So, after replication, some objects in Green Minio might not be expired when expected, but much later, and causing storage issues.

**Describe the solution you'd like**

I saw that "rclone --metadata" is storing the metadata information in files in "Green" Minio (creation date in "X-Amz-Meta-Btime" , modification date in "X-Amz-Meta-Mtime").

The solution I would like is to able to configure buckets with a specific metadata entry name for creation date, so that :
- If this metadata entry exists, Minio uses this entry value as "creation date" to manage its "Lifecycle management"
- If this metadata entry does not exist, Minio uses its basic mechanism for "Lifecycle management"

So, in my use-case, I would like to configure buckets with "X-Amz-Meta-Btime" as "alternate creation date field".

**Describe alternatives you've considered**

I have considered all options referenced in this issue : https://github.com/minio/minio/discussions/20296
So I just copy the content of this issue with description of alternatives : 

- mc replicate - not really suitable for one-time replications from "blue" to" green", with specific folders/files to copy
- mc mirror/mc cp (both from S3 API-S3 API, Filesystem-S3 API): data was indeed transfered to new cluster, but all of the objects has lastModified timestamp set to the time of the upload
- rsync/scp - as in my understanding, this option is not possible due to MinIO Gateway depreciation, objects needs to be uploaded using S3 API
- rclone sync/copy - it was the closest to my goal, but still not what I needed. I run this command with --metadata flag, it added X-Amz-Meta-Btime and X-Amz-Meta-Mtime to metadata section for the objects, however the lastModified timestamp on MinIO is set to the upload date.

**Additional context**

No specific addition context

**Comment by harshavardhana** [comment]
Unsupported in AWS S3 API.
