### ISSUE TITLE
minio does not heal metadata on transitionned object (ilm tiering)

### ISSUE THREAD

**Issue by julienlau** [minio/minio#20559]
When using tiering the hot/front tier hold the metadata for all objects accross all tiers.
The metadata also holds data of inlined objects (size < 128K)

## Expected Behavior

- When I heal a drive on the hot tier cluster, I should not have minio log errors for objects that have already transitionned to the backend tier.
Right now, I have error like this one below for all transitionned objects:
`Error: unable to heal object thanos/index: Storage resources are insufficient for the read operation thanos/index (*fmt.wrapError)`
The object can be listed or stat: 
`sudo mc ls myminio-local/thanos/index 
[2024-10-03 11:17:11 CEST] 512MiB COLD-THANOS index`

- When I heal a drive on the hot tier cluster, minio must be able to re-generate the missing xl.meta files for metadata of transitionned objects. If this is not possible, then minio will progressively loose data at each disk replacement.

## Current Behavior

minio tries to heal all objects from a tiered setup, even if the object is not stored on the current cluster.
OK, but the healing on the hot tier should work without error even if the object already transitionned to the backend tier.
Otherwise, it means that healing is not supported once tiering is setup.

## Your Environment

* Version used (`minio --version`): 2024-09-22T00:33:43Z
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by julienlau** [comment]
The healing is now terminated on the node that I completely rebuild.

All objects that were transitionned have no metadata on this new node.
In the disk the files .meta.xl does not exist for transitionned object. Thus the metadata are corrupted on the new node.

This is a HUGE bug to us, since it basically means Tiering looses data.

**Comment by julienlau** [comment]
Hello,

Guys, I don't get it.
To my view minio tiering is loosing data and should not be considered prod ready.
From what I see, when you use parity=2 once you completely rebuilt 1 node from the hot tier then any incident on the transitionned objects that were part of the first rebuilt will cause a data loss.

It bites me in production but it can be easily reproduced.

I have a setup with 4 VM in EC4:2 (hot tier) and 1 single VM as cold tier. 
I generated data with warp that transitionned to the cold tier.

using the commands below to simulate an outage on a given object I can observe that the healing engine of minio cannot heal metadata of transitionned objects:

```
f='85.zvG4d0a7a)Y1t)GZ.rnd'
mc ls hot/buc/tnxXHrgA/$f
find /data/1/buc -type f | grep $f
mc ls hot/buc/tnxXHrgA/$f; date; sudo systemctl stop minio; date ; sudo rm $(find /data/1/buc -type f | grep $f); sudo systemctl start minio ; date ; mc ls hot/buc/tnxXHrgA/$f
find /data/1/buc -type f | grep $f
mc admin heal -r --scan=deep hot/buc/tnxXHrgA/
find /data/1/buc -type f | grep $f
mc ls hot/buc/tnxXHrgA/$f
mc cp hot/buc/tnxXHrgA/$f /tmp/
mc stat hot/buc/tnxXHrgA/$f
```

Please see the screenshots below where I applied this iteratively on 3 VMs from the hot tier to observe data loss

1/ Every host from the hot tier hold the metadata from the cold tier
![Screenshot from 2024-10-28 15-44-51](https://github.com/user-attachments/assets/cfca1b06-4c26-4483-b59a-85c4eb689625)

2/ Simulate hardware-replacement / incident on VM u20-1 : the data can still be accessed after the outage. Given we are using EC4:2 here and 1 erasure shard was wiped, the quorum is maintained (1 out of 4).
![Screenshot from 2024-10-28 15-49-40](https://github.com/user-attachments/assets/2f8ff820-d559-4fc8-a4da-51a4c4b0900b)

3/ Simulate hardware-replacement / incident on VM u20-3 : the data cannot be accessed anymore
![Screenshot from 2024-10-28 15-57-11](https://github.com/user-attachments/assets/00cbd210-bcbc-4e6b-a732-283f63c29d33)
In addition the heal still sees 50 objects in this directory despite the fact that one of the objects cannot be listed consistently.
Given we are using EC4:2 here and 2 erasure shard were wiped, the quorum is not maintained (2 out of 4) which explained inconsistent lists.

4/ Simulate hardware-replacement / incident on VM u20-4 : the data cannot be accessed anymore
![Screenshot from 2024-10-28 16-09-30](https://github.com/user-attachments/assets/e9e101fb-24f4-4d0f-938a-8bb105c3ef81)
In addition the heal still sees 50 objects in this directory despite the fact that one of the objects cannot be listed consistently.

5/ As can be seen the data is still there on the cold tier : I have 63 objects in this bucket. However in the front tier I see that all objects have transitionned to minio-cold and I can only list 62 objects.
![Screenshot from 2024-10-28 17-21-33](https://github.com/user-attachments/assets/337238c4-901b-46d9-bb3d-63d052f9df4a)



I understand that unit tests in tiering is probably challenging since transition use its own schedule and cannot be force at delays below 1 day, but I am very astonished to find this bug in a production ready solution.

**Comment by julienlau** [comment]
FTR : auto heal of non transitioned objects works fine on this setup.
![minio-normal-healing](https://github.com/user-attachments/assets/75fa53f8-d949-489a-888f-4e43ce815cb4)

**Comment by julienlau** [comment]
please note that these tests were done with bucket versioning disabled and config api `object_max_versions=1`

**Comment by klauspost** [comment]
When @krisis is back (next week AFAIK) he should be able to look at it. Could you collect the directories of an unhealing object from all disks and attach it here as a zip?

**Comment by julienlau** [comment]
I will do the same experiment with the latest version of minio and attach the archive here tomorrow.
I did not find an easy way to trick the clock in order to speed up transition in less than 1 day.
I tried to run minio with `faketime -f "+1d"` but it fails.

**Comment by julienlau** [comment]
Hello,
No surprises but I can confirm that the bug is still there on the latest version of minio.
I redid the same experiment : 
```
mc admin trace -a local | grep -i -e testfile_241028_idx20 -e  heal

rm testfile_*idx*
for i in {11..20}; do dd if=/dev/urandom bs=1K count=$i of=testfile_$(date '+%y%m%d')_idx$i; done
mc cp testfile_*idx* local/buc/adir/
mc ls -r local/buc/

mc admin info local | tail -12
date
f='testfile_241028_idx20'
mc ls local/buc/adir/$f
find /data/1/buc -type f | grep $f
ll /data/1/buc/adir/$f/xl.meta
mc admin heal -r --scan=deep -a --force local/buc
for i in range {1..10}; do printf "$(mc ls -r local/buc/ | wc -l) "; done; echo ""
mc ls local/buc/adir/$f; date; sudo systemctl stop minio; date ; sudo rm -f $(find /data/1/buc -type f | grep $f); ll /data/1/buc/adir/$f/xl.meta; sudo systemctl start minio ; date ; ll /data/1/buc/adir/$f/xl.meta; mc ls local/buc/adir/$f;
for i in range {1..10}; do printf "$(mc ls -r local/buc/ | wc -l) "; done; echo ""
mc admin info local | tail -2
ll /data/1/buc/adir/$f/xl.meta
mc stat local/buc/adir/$f
mc admin heal -r --scan=deep -a --force local/buc
ll /data/1/buc/adir/$f/xl.meta
mc ls local/buc/adir/$f
mc cp local/buc/adir/$f /tmp/
mc stat local/buc/adir/$f
```

and same results : simulated drive replacement causes data loss since xl.meta of transitionned object is never repaired on hot tier.

Screenshots of the tests : 
- Setup
![1-minio-setup-version](https://github.com/user-attachments/assets/d1935c59-b4b3-4aff-a61d-9b0fc4805c0c)
- Setup
![2-minio-tiering-files](https://github.com/user-attachments/assets/b962bf81-a3bf-4506-91b0-618b4501566c)
- simulated incident on vm1 (hot)
![3-vm1-incident-lost-file1](https://github.com/user-attachments/assets/7c45ed15-ea34-47fa-9421-ad1f165df2ea)
- simulated incident on vm2 (hot)
![4-vm2-incident-lost-file1](https://github.com/user-attachments/assets/0d7e9a0c-1c64-4a04-8b7b-ba1bae2e3403)
- simulated incident on vm3 (hot)
![5-vm3-incident-lost-file1](https://github.com/user-attachments/assets/28d12403-2dee-4a14-a6cf-7fb671469ca4)

Archive of the whole minio drives from the 4 vm of the hot tier :  
[minio-tiering-data-loss.zip](https://github.com/user-attachments/files/17571995/minio-tiering-data-loss.zip)

**Comment by klauspost** [comment]
@julienlau Thanks for your files & scripts. Yes. It does seem like there is a healing glitch on tiered objects.

Also, you can remove your sensationalist "LOOSE DATA", since your data isn't lost. It is just inaccessible. I know you just do this and your blog post for attention.

While we appreciate your situation, we have to prioritize our paying customers for non-trivial issues. Thank you for your understanding.

**Comment by julienlau** [comment]
I've edited the title, even though in my view the data is lost once the metadata is lost.

I am sure you guys are doing the best you can, and I thank you for that. However, I am sorry to say that this is not the kind of bug I find acceptable in a production-grade storage solution, even if it is open source. I know this is not the Enterprise Edition I use, but data durability is the core of any storage solution. You may also understand that on my side, the cluster using Minio + tiering is just a bleeding edge pain, with every hardware fault causing a lot of inconsistency issues and manual repairs.

I agree that it may be possible to rebuild the data, but I foresee a lot of pain here (I have no expertise in Minio source code). From my perspective, it would require taking snapshots or stopping writes to the hot+cold clusters (ouch!), performing a full scan of all metadata in the hot+cold cluster (ouch!), and rebuilding the missing metadata file in the front tier using the metadata from the cold tier.

**Comment by klauspost** [comment]
@julienlau 👍🏼 I will see what I can do.

**Comment by julienlau** [comment]
more facts : the data on the cold tier looks like that

EDIT : re-upload the same image due to 404
![Screenshot from 2024-10-31 12-00-50](https://github.com/user-attachments/assets/de40635e-f27b-43df-b0c6-7100b03f208e)

**Comment by klauspost** [comment]
Yeah, we should be fine with data.

What seems to happen is that when data is tiered the part data obviously isn't there, and this condition isn't ignored all the way through the healing process.

**Comment by klauspost** [comment]
With the data you sent, I can heal `dira` with one shard missing on master. With transitioned data, it requires [N/2+1](https://github.com/minio/minio/blob/b6b7cddc9c419d2e047063c30a92d14e264c5eca/cmd/erasure-metadata.go#L518) (=3) shards, and disallows for the split brain scenario, so this makes it not heal in 2+2 setups.

I can't see your images above. For whatever reason opening the full image gives 404.

**Comment by julienlau** [comment]
I redid the upload the same image.

Nice to here that you manage to heal it the 1 shard missing scenario and thank you for your help. 
I did no try to manually copy the xl.meta of a transitioned object from one node to another, is it what you've done ?

**Comment by klauspost** [comment]
@julienlau I will send a PR that allows for healing 2 shards, but it will need some thorough review, since it is a sensitive system and I don't know all the details of it.
