### ISSUE TITLE
minio error due to inconsistent data with list_quorum=strict and tiering

### ISSUE THREAD

**Issue by julienlau** [minio/minio#20558]
## NOTE

I have a cluster using the setting : api list_quorum=strict because the jobs of my clients crash when they have inconsitent list data.
Due to hardware failure I replaced a node with a new one on this cluster and followed your guide : 
https://min.io/docs/minio/linux/operations/data-recovery/recover-after-node-failure.html#minio-restore-hardware-failure-node

Once I started minio on the new node with empty drives it was immediately marked as healthy in `mc admin info myminio-local` and it begans to serve client requests.

However client jobs failed due to inconsistent metadata. In their delta table.
I was thniking that strict consistencies means some kind of quorum read, but it seems not.

```
sudo mc admin config export myminio | grep -v "^#"
subnet license= api_key= proxy= 
drive max_timeout= 
site name= region= 
api requests_max=0 cluster_deadline=10s cors_allow_origin=* remote_transport_deadline=2h list_quorum=strict replication_priority=auto replication_max_workers=500 transition_workers=100 stale_uploads_cleanup_interval=6h stale_uploads_expiry=24h delete_cleanup_interval=5m odirect=on gzip_objects=off root_access=on sync_events=off object_max_versions=1 replication_max_lrg_workers=10 
scanner speed=default alert_excess_versions=100 alert_excess_folders=50000 
batch replication_workers_wait=0ms keyrotation_workers_wait=0ms expiration_workers_wait=0ms 
browser csp_policy="default-src 'self' 'unsafe-eval' 'unsafe-inline';" hsts_seconds=0 hsts_include_subdomains=off hsts_preload=off referrer_policy=strict-origin-when-cross-origin 
ilm transition_workers=100 expiration_workers=100 
storage_class standard=EC:2 rrs=EC:1 optimize=availability 
heal bitrotscan=off max_sleep=250ms max_io=100 drive_workers=
```

## Expected Behavior

There should be a setting to achieve read consistency with minio.

## Current Behavior

When minio is doing a healing, consistency is lost.
On the image attached, I used the mc client with the alias "myminio-local" pointing to localhost (no load-balancer).
If I run `mc ls` on a legacy node, I get the expected response : see the terminal on the left of the image.
If I run `mc ls` on the new node at ~50% healing, I get an error.
`mc: <ERROR> Unable to list folder. Requested file XXX not found`

![Capture](https://github.com/user-attachments/assets/a3c7acf9-5fd4-4873-8017-6990ca73538c)

## Steps to Reproduce (for bugs)

1. populate data in a multi-node cluster
2. stop minio on one node and delete on data on the hard drives
3. start minio on this node
4. try to read data from this node using mc client during the healing operation

## Your Environment

* Version used (`minio --version`): 
Version: 2024-09-22T00:33:43Z
* Server setup and configuration: on premise, HPE servers, 8 nodes, 7 drives.
* Operating System and version (`uname -a`): Ubuntu

**Comment by klauspost** [comment]
It sounds more like your new node is having troubles. Listing quorum isn't really affected by which node is called, except if it has connectivity issues.

I don't really see anything actionable here. If you would like to go into a deeper dive, look into our [subscriptions](https://min.io/pricing).

**Comment by julienlau** [comment]
won't it log errors in minio logs if it has connectivity issues ?

**Comment by julienlau** [comment]
I have no connectivity issues, but I'll try to reproduce it by myself... but if the error is due to tiering I won't be able to reproduce it. To my view this error is specific to Tiering, because my users have crashes only on transitionned objects.

Could you please confirm that LIST is not affected by tiering ?

Could you please confirm that this behavior is not expected ?

It's too bad that nothing describes in depth how minio operates during healing. If a GET request arrives on a node that has corrupted data what is happening exactly ? Failure and the client is expected to retry ? Response with data from another nodes ? Heal and then response ?

**Comment by julienlau** [comment]
In addition if i pick random objects in the error seen in the logs from :
`mc admin trace --call healing myminio-local`

I observe that they all are transitionned objects.

**Comment by julienlau** [comment]
I have a transition delay of 3 days.
Most of my files are parquet or delta tables with datehour in one of the partition.

I can say that I did no catch non transitionned objects using this command : 
`mc admin trace --call healing myminio-local | grep -e 2024101[3-5] `
however most of my objects are transitionned objects

**Comment by julienlau** [comment]
The healing of the new node is now completed.
I had "objects failed" on all transitionned objects as mentionned in this other issue : https://github.com/minio/minio/issues/20559

The new node still have incomplete metadata which cause havoc on the whole cluster.
As mentionned in https://github.com/minio/minio/issues/11254 I cleaned the whole metadata cache in the whole cluster and perform a minio restart without success.

Basically what I observed after rebuilding:
- The rebuild node does not hold any metadata for rebuild of transitionned objects : meta.xl files are missing on the disks.
There is also a large difference in disk usage, but it may be due to the meta.xl files since there are tens of millions of objects on this cluster.
If I check a single table on a not-rebuild-node I count ~1000 xl.meta files and ~5 "real" objects whereas on the rebuild node I have only 8 xl.meta files.

The node on the left ("67") was not rebuild and the node on the right ("81") was rebuild yersterday.
![disk-usage](https://github.com/user-attachments/assets/d73db1f4-e7b3-4669-8758-7725032586de)
![no-metadata-after-rebuild](https://github.com/user-attachments/assets/3abf66ea-7d23-4954-998c-a3c2af6c57d9)


- even with list_quorum=strict, I have inconsistent listing when this node is up. The inconsistent listing appears on ALL nodes and is not restricted to queries on localhost that was rebuild ("b81")
```
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
44
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
34
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
45
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
50
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
41
```
whereas if I turn off minio on the new node that was freshly rebuild, the listing operations are then consistent:
```
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
50
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
50
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
50
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
50
[jlaurenc@b67]> sudo mc ls myminio-local/_delta_log | wc -l
50
```
![ls](https://github.com/user-attachments/assets/15af15f4-c81c-4978-8008-5012f339a918)
![api-settings](https://github.com/user-attachments/assets/b9b013ca-105e-4580-874f-dfd01c8dbcf4)


This makes me think that there is a bug on how minio handles quorum in the list_quorum code.

**Comment by julienlau** [comment]
This is still happening every time we have a single outage.

![list-consistency-after-outage](https://github.com/user-attachments/assets/0d72d998-9d26-4df1-8587-5f03a5f53644)

I did not find any way to heal that with minio API or CLI.
The only way to fix it : 
- shutdown minio on the node that suffered an outage. 
- backup the data `mc cp -r minio/buc/dir /tmp/` 
- on the bad node : perform a brute force wipe of these data: `rm -rf /data/*/buc/dir`
- start minio on the bad node
- copy (overwrite) the data from the backup `mc cp -r /tmp/dir minio/buc/ `

**Comment by julienlau** [comment]
Looking at the latest release, it seems to me that it may be caused by this bug that was recently fixed : 
https://github.com/minio/minio/pull/20522
![image](https://github.com/user-attachments/assets/413edcc1-17d9-4ab2-808c-009f3dce5b71)

**Comment by julienlau** [comment]
I updated to this latest version RELEASE.2024-10-13T13-34-11Z and unfortunately I did not see any effect on the heal behavior.

The existing inconsistencies are still not heal by running `mc admin heal -r`

**Comment by harshavardhana** [comment]
This is also fixed via #20601

**Comment by julienlau** [comment]
Could you please reopen this issue.
I run the version RELEASE.2024-11-07T00-52-20Z that should implement the fix and I still have inconsistent LIST results.

**Comment by julienlau** [comment]
Manual healing seems to help
![image](https://github.com/user-attachments/assets/38aa2098-8c47-474f-9157-d94c31815e57)

The scan results are odds: 9162 objects scanned and the LIST queries retrieve only 1384 objects... I hope this is not lost objects.

I'll wait a bit before applying manual healing to solve the other erros on this cluster in order to see if automatic healing manage to solve this after more time.

**Comment by julienlau** [comment]
maybe the automatic healing is too lazy with the default settings. I'll try to increment the settings to FAST. 
![image](https://github.com/user-attachments/assets/f9cd6f5f-e2ae-4b3e-8c18-1ada7cf0ba49)
![image](https://github.com/user-attachments/assets/f54a5e15-52a0-44fc-bea7-0d233e4bf4ad)

**Comment by julienlau** [comment]
more embarrassing, I still have LIST inconsistencies on some directories even after a manual healing
![image](https://github.com/user-attachments/assets/67e56917-c7ef-4e4d-b316-877958a59ed7)

**Comment by julienlau** [comment]
and I'm sure that it is not due to some transient files of a running processing because users have inconsistencies after every issue or reboot of a node.
On another delta table the difference in the number of files is huge :
![image](https://github.com/user-attachments/assets/106b6928-be70-486b-993a-12a47f2429f7)
