### ISSUE TITLE
Metrics dupe for `minio_cluster_usage_total`

### ISSUE THREAD

**Issue by ravindk89** [minio/minio#20564]
Duplicated Console UI usage for `minio_cluster_usage_total_bytes` due to a potential server label mismatch.

Given a load balancer routing to two different servers, the `server` label changes - this much is expected. Customer has a prometheus config w/ redundant servers, each scraping from MinIO.

So:

```sh
minio_cluster_usage_total_bytes{instance="s3.prod.example.com:443",job="minio-prod",server="minio-01.example.net:9000"}
minio_cluster_usage_total_bytes{instance="s3.prod.example.com:443",job="minio-prod",server="minio-02.example.net:9000"}
```

are returned by Prometheus. This seems to result in a double count for the Console UI, assuming the graph does a `SUM` on the returned values.

If the above is true, the console UI query could be adjusted to take the `max` of this count such that any duplicate entries due to changing servers is resolved appropriately.

**Comment by ramondeklein** [comment]
Metrics are collected in MinIO itself (not the console), so moving this to the MinIO repository.

**Comment by harshavardhana** [comment]
This looks like a double scraping issue at the customer environment. MinIO itself won't publish duplicates, you shouldn't scrape cluster metrics from two endpoints. 

It must be only scraped via an LB - custom seems to be scraping this via two endpoints.

**Comment by ravindk89** [comment]
@harshavardhana we can add that to the docs and advise the customer, but it does leave open their scenario of using multiple prom nodes for metrics HA. Is that a nonstandard pattern or something we would want to report?

@ramondeklein I _think_ the issue is related to a Console graph + report, the SUBNET issue made reference to prom queries which MinIO does not itself do.

**Comment by ramondeklein** [comment]
The customer also added the following context:

> We scrape the metrics from two prom servers for redundancy. The `server` label is probably dependent on where the load balancer sends the request.
>
> I would guess the console UI is returning a value from a query like: `sum(minio_cluster_usage_total_bytes{instance="s3.prod.chaska.optumserve.com:443"}) by (instance)` returns 314194856699950
>
> It probably should do something like:
> Whereas, `max(minio_cluster_usage_total_bytes{instance="s3.prod.chaska.optumserve.com:443"}) by (instance)` returns 157097428349975

Seems to be a problem that shows up in the console. I'm not a Prometheus specialist, so don't really know if this is a setup failure or a bug in our console.

**Comment by harshavardhana** [comment]
> @harshavardhana we can add that to the docs and advise the customer, but it does leave open their scenario of using multiple prom nodes for metrics HA. Is that a nonstandard pattern or something we would want to report?

cluster metrics must be scraped from one endpoint, and all other metrics are scraped per node.

**Comment by ravindk89** [comment]
cc @cesnietor on the console note via Ramon.

I think @harshavardhana issue here is that they have two Prom nodes behind LB, so Console cannot pin to a single prom node. Thus it gets the 'double' count since the underlying Prom nodes don't have any knowledge of each other. If I understand the issue.

So they could solve this by just bypassing LB and pointing Console at only one Prom instance. Or perhaps if the LB supports sticky sessions it could route Console to the same Prom server consistently or something.

Still if we can solve this at the Console layer it would be _nice_.

**Comment by harshavardhana** [comment]
Not sure if this anything actionable, closing this since there is nothing new we are doing regarding this in community Console UI.
