### ISSUE TITLE
DNs containing special characters fail login attempts with LDAP

### ISSUE THREAD

**Issue by luckypawn** [minio/minio#20565]
We were trying to configure MinIO tenant to use Active Directory as IDP. Unfortunately, we have Cyrillic in DN, which breaks user login. 
## Expected Behavior
Users with Cyrillic in DN are able to login to MinIO console

## Current Behavior
MiniO Console throws an error "invalid Login", logs contain this message: 

```
API: AssumeRoleWithLDAPIdentity
Time: 07:42:32 UTC 10/16/2024
DeploymentID: f6b5f3af-bb4f-bb42-bbe4-ebb14e70136
RequestID: 17DEADBEEF806CE1
RemoteHost: x.x.x.x
UserAgent: Go-http-client/1.1Error: Object name invalid: .minio.sys/config/iam/policydb/users/cn=johndoe,ou=\d0\9f\d0\be\d0\bb\d1\8c\d0\b7\d0\be\d0\b2\d0\b0\d1\82\d0\b5\d0\bb\d0\b8
,ou=TEST OU,dc=example,dc=local.json (cmd.ObjectNameInvalid)Backtrace: 
0: internal/logger/logger.go:269:logger.LogIf()
1: cmd/logging.go:204:cmd.stsLogIf()
2: cmd/sts-errors.go:43:cmd.writeSTSErrorResponse()
3: cmd/sts-handlers.go:670:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
4: cmd/sts-handlers.go:384:cmd(*stsAPIHandlers).AssumeRoleWithSSO()
5: net/http/server.go:2171:http.HandlerFunc.ServeHTTP()
```

## Possible Solution
We assume the reason is "\\" characters breaking path to JSON.

## Steps to Reproduce (for bugs)
1. Configure MinIO to use LDAP
2. Add user with Cyrillic in DN to AD
3. Login with username
4. Get an error

## Context
The bug makes login impossible and creation of local users in console is forbidden due to security policies.

## Regression
No

## Your Environment
* Version used (`minio-operator`): 6.0.3
* Environment name and version (e.g. kubernetes v1.17.2): v1.29.5
* Operating System and version (`uname -a`): Linux 5.15.0-209.161.7.2.el9uek.x86_64 GNU/Linux
* LDAP Settings: 
  * Lookup Bind DN: cn=service-account,ou=Пользователи,OU=TEST OU,DC=example,DC=local
  * User DN Search Base: DC=EXAMPLE,DC=LOCAL
  * User DN Search Filter: (sAMAccountName=%s)

**Comment by ramondeklein** [comment]
Most likely a duplicate of https://github.com/minio/minio/issues/19757. Please upgrade to the latest MinIO version and try again.

**Comment by luckypawn** [comment]
We used the latest available version, no luck with RELEASE.2024-10-02T17-50-41Z

**Comment by luckypawn** [comment]
We are also able to use this exact credentials and search filters in another service without any errors

**Comment by luckypawn** [comment]
Tried also version RELEASE.2024-10-13T13-34-11Z, same result

**Comment by ramondeklein** [comment]
Can you also post the logs of the latest release?

**Comment by luckypawn** [comment]
Also, there is an error when trying to apply policies:

 ` Error: drive:/export1/data, srcVolume: .minio.sys/tmp, srcPath: d5efc049-676a-4cef-b3cc-1e023e4544a6, dstVolume: .minio.sys:, dstPath: config/iam/policydb/sts-users/cn=username,....,ou=\d0\9f\d0\be\d0\bb\d1\8c\d0\b7\d0\be\d0\b2\d0\b0\d1\82\d0\b5\d0\bb\d0\b8,dc=example,dc=com.json - error file name too long. `
  Backtrace: 
  0: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
  1: internal/logger/logonce.go:149:logger.LogOnceIf()
  2: cmd/logging.go:164:cmd.storageLogOnceIf()
  3: cmd/xl-storage.go:2576:cmd.(*xlStorage).RenameData.func1()
  4: cmd/xl-storage.go:2632:cmd.(*xlStorage).RenameData()
  5: cmd/xl-storage-disk-id-check.go:501:cmd.(*xlStorageDiskIDCheck).RenameData.func2()
  6: internal/ioutil/ioutil.go:116:ioutil.WithDeadline[...].func1()

We are unable to change the length of the DN. Due to normalization of DN it uses three times as many symbols. 

Apart from that, the previous error remains the same, example is in the issue.

**Comment by ramondeklein** [comment]
Can you post the full `dstPath` (or else tell me the length of that path)?

**Comment by luckypawn** [comment]
Filename without extension and parent folders takes 364 characters. Which is more than the limit for most of filesystems by itself

**Comment by luckypawn** [comment]
As a suggestion, maybe it's better to use a hash of DN for a filename instead?

**Comment by ramondeklein** [comment]
Most Linux filesystems only allow 255 characters for the filename (without path). That will most likely cause this issue. Can you share the full path?

**Comment by harshavardhana** [comment]
Yeah this we can't support unfortunately as of now. In future we may, but Cyrillic  names are not a priority right now.

For now just change the OU name to something simpler if possible.

Normalization of these names further into to fit into 255 characters is going to be a lot of work.

Will close this as it's not a priority right now but will make a note of it internally to get back to when time permits.

**Comment by s5unty** [comment]
The unique field used for Minio user authentication in LDAP (such as distinguishedName) is read by Minio and then represented as hexadecimal UTF-8 encoding.

This raw encoded form (e.g., \e5\9f\ba\...) is subsequently used by Minio to name a configuration file.

When this encoded string exceeds 256 characters, it causes the configuration file creation to fail, leading to authentication problems.
