### ISSUE TITLE
latest images on docker hub doesn't have s390x architecture

### ISSUE THREAD

**Issue by apupier** [minio/minio#20560]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Have s390x architecture for same images than before

![image](https://github.com/user-attachments/assets/47638e15-4a98-4755-b10a-0fb16da2c863)

## Current Behavior

missing s390x architecture with latest image pushed
![image](https://github.com/user-attachments/assets/0d7393b3-e461-40a6-af1d-9f5ca4c1938c)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
s390x is deprecated as we have no takers anymore, we won't be build s390x based binaries anymore.
