### ISSUE TITLE
Support for UNSIGNED-PAYLOAD on minio server

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2056]
All object-handlers which have body should support UNSIGNED-PAYLOAD for sha256.

**Comment by krishnasrinivas** [comment]
https://github.com/minio/minio/pull/2038 fixes this as well

**Comment by harshavardhana** [comment]
Is this valid? @krishnasrinivas ?

**Comment by krishnasrinivas** [comment]
closing as this is already fixed.
