### ISSUE TITLE
[XL] Validate CRC64 for collision consistency.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2057]

**Comment by fwessels** [comment]
Info on CDC T10 DIF
http://www.ibm.com/developerworks/aix/library/au-T10E2E/

**Comment by harshavardhana** [comment]
We never discussed about this after this was opened up since blake2b is working great do not know how much value this adds, closing this unless anyone has any concern keeping this open. We can re-open when we really need it.
