### ISSUE TITLE
Why can't text be previewed??

### ISSUE THREAD

**Issue by yhwei89** [minio/minio#20570]
[RELEASE.2024-10-02T17-50-41Z] 
 
![image](https://github.com/user-attachments/assets/5b826dc2-6ca4-49c3-b553-4d759fa032fa)

**Comment by ravindk89** [comment]
https://github.com/minio/console/issues/2021#issuecomment-1132942518

There were security concerns raised for previewing certain filetypes, and that includes text files. Therefore we are not going to be re-implementing this feature.

**Comment by carlosaya** [comment]
I really wonder what the security implication is here.  If I have already successfully logged into minio and have rights to download the file, then what is the security concern with just making it easy for me to preview the file in my browser instead of having to download it?  🤔
