### ISSUE TITLE
IAM refresh took lead to AccessDenied.

### ISSUE THREAD

**Issue by yotles** [minio/minio#20571]
* minio version: RELEASE.2024-06-22T05-26-45Z
* deployment: 9 identical HW servers with 3 disks(SSD) in each.

Hi! In some random moment during ~1-2 minutes clients started to get `S3 operation failed; code: AccessDenied, message: Access Denied., resource: /` and then became to normal. In the exact time on one of nodes I've found such log `IAM refresh took 28.49s`. So looks like this is the reason that some clients communicate with this node at this point of time. As I understand IAM synced each 15 minutes. Is there any steps to avoid it, tune something in configuration?

Thanks.

**Comment by harshavardhana** [comment]
Please upgrade to latest version.
