### ISSUE TITLE
Authelia OIDC & InvalidBucketName

### ISSUE THREAD

**Issue by vasyakrg** [minio/minio#20582]
Authelia OIDC Settings:

Config URL https://auth.mydomain.com/.well-known/openid-configuration
Client ID s3-minio
Claim Name groups
Display Name Authelia
Claim Prefix  ""
Scopes openid,profile,email,groups
Redirect URI https://minio.mydomain.com/oauth_callback
Role Policy ""
Claim User Info ""
Redirect URI Dynamic Disable

after transferring to oidc, I successfully log in Authelia and get back redirect to minio
i get an error: 
```
Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Resource>/oauth_callback</Resource><Region>nsk-1</Region><RequestId>1801527C96070D34</RequestId><HostId>...id_redacted_bbb7caf88b9b950d6c40028253...</HostId></Error>
```

if you log in using a regular login and password - there are no problems, all the bickets are in place.
there are no problems in the Authelia logs, authorization is successful, then redirect.

setting get from https://www.authelia.com/integration/openid-connect/minio/

policy redacted:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*"
            ],
            "Condition": {
                "StringEquals": {
                    "jwt:groups": [
                        "admins"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Condition": {
                "StringEquals": {
                    "jwt:groups": [
                        "admins"
                    ]
                }
            }
        }
    ]
}
```

## Your Environment
Authelia: 4.37.5
Minio: 2024-08-03

**Comment by harshavardhana** [comment]
> Redirect URI https://minio.mydomain.com/oauth_callback

you can't have your own random oauth callback, you need to keep your callbacks under `/minio/<myname>` 

This is deprecated a long time ago you must use 

```
MINIO_BROWSER_REDIRECT_URL
```

For your redirect URI to work your ingress must handle and direct this properly which it is not doing right now.

**Comment by vasyakrg** [comment]
i set redirect "/minio/ui" in config Authelia and setting oidc in minio, but:

```
"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."
```
