### ISSUE TITLE
A low-privileged user can download files from a restricted bucket using tools like `postman`

### ISSUE THREAD

**Issue by wugeer** [minio/minio#20589]
## Expected Behavior

When a low-privileged user tries to download files from a restricted bucket using tools like `postman`, an "Access Denied" error (or similar) is returned.

## Current Behavior

A low-privileged user can download files from a restricted bucket using tools like `postman`

## Steps to Reproduce (for bugs)

1. Create a user with a read-only policy using the MinIO Console.
2. Create a test bucket and upload a test file.
3. Log in to the MinIO Console with the read-only account and click on the newly created bucket; an "Access Denied" message appears.
4. Execute the API endpoint and cookie from the previously denied action in the MinIO Console using Postman.
[录屏 2024-10-29 17-07-34.webm](https://github.com/user-attachments/assets/3b886885-42b7-44ab-bc85-36c00f80f622)
[录屏 2024-10-29 17-08-11.webm](https://github.com/user-attachments/assets/a91a794e-41db-48a1-b025-ccd3b4943140)

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-10-13T13-34-11Z`
* Server setup and configuration: default
* Operating System and version (`uname -a`): host machine `Linux wugeer 6.6.58-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 23 Oct 2024 17:28:15 +0000 x86_64 GNU/Linux` docker container
![image](https://github.com/user-attachments/assets/988943d3-65f5-439e-9e85-705b9f84d872)

**Comment by harshavardhana** [comment]
You have GetObject permissions, but the UI is returning "access denied" because you have disallowed ListObjects() - however, the user has GetObject() permissions, which means they can download objects. 

Which is what you are demonstrating. This is not a security issue just what is expected from your policy.

**Comment by wugeer** [comment]
@harshavardhana Thank you for help. :)
