### ISSUE TITLE
slow http attack 

### ISSUE THREAD

**Issue by lunxian8** [minio/minio#20588]
"When using MinIO directly without an NGINX proxy, it was detected to be vulnerable to HTTP slow connection attacks. Is there a configuration to prevent this, similar to the connectionTimeout setting in Tomcat?"

**Comment by lunxian8** [comment]
Using <env name="MINIO_READ_HEADER_TIMEOUT" value="6s"/> and <env name="MINIO_IDLE_TIMEOUT" value="6s"/> doesn't seem to work."

**Comment by lunxian8** [comment]
Using MINIO_READ_HEADER_TIMEOUT and MINIO_IDLE_TIMEOUT  doesn't seem to work.

**Comment by klauspost** [comment]
@lunxian8 S3 operations can be very slow by nature. As such, there is no 100% Slowloris mitigation, unless you are willing to accept false positives. If you are considering these attacks as a threat you must mitigate them upstream.

**Comment by lunxian8** [comment]
Yes, Nginx is configured. However, we have a relevant department that conducts inspections, similar to logging directly into your Linux system to inspect each program. This makes it impossible to avoid detection of this issue. If the scan was conducted externally, I could simply open port 80 on Nginx for them, ensuring that this issue wouldn’t be exposed. Unfortunately, I just wanted to ask if MinIO has any plans to support connection timeout information for clients. I reviewed the code and found configurations like IdleTimeout, but it doesn't seem to be effective.

**Comment by klauspost** [comment]
Slowloris mitigation is unlikely to be added directly. We - or rather @harshavardhana - have looked into non-progressing HTTP connections that have stopped sending/receiving data. We have not made a final decision on this.

**Comment by lunxian8** [comment]
tks
