### ISSUE TITLE
When making requests to the MinIO using tools like `Postman`, setting the Host header incorrectly still result in normal responses which could indicate a risk of HTTP header attacks

### ISSUE THREAD

**Issue by wugeer** [minio/minio#20590]
## Expected Behavior

When making requests to the MinIO using tools like` Postman`, setting the Host header incorrectly is expected to result in an http error.

## Current Behavior

When making requests to the MinIO using tools like `Postman`,  setting the Host header incorrectly still result in normal responses.

## Steps to Reproduce (for bugs)

1. Log in to the MinIO console using an account that can list the `test-bucket`, and retrieve the cookie from the browser's developer tools.
2.  Execute the API endpoint and cookie from the previously action in the MinIO Console using Postman with setting the Host header incorrectly 
[录屏 2024-10-30 10-13-48.webm](https://github.com/user-attachments/assets/e6648399-f33f-49b4-9ade-4e6cfbea1a3a)

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-10-13T13-34-11Z`
* Server setup and configuration: default
* Operating System and version (`uname -a`): host machine `Linux wugeer 6.6.58-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 23 Oct 2024 17:28:15 +0000 x86_64 GNU/Linux` docker container
![image](https://github.com/user-attachments/assets/988943d3-65f5-439e-9e85-705b9f84d872)

**Comment by harshavardhana** [comment]
Host header is allowed to be anything other than the actual host, because MinIO can run behind proxies.

The point is as long as you have credentials there is nothing you can't do. If you don't have credentials rest are meaningless.

Closing since this issue is not technically applicable to us.
