### ISSUE TITLE
After enabling TLS, the MinIO console's login interface still transmits passwords in plain text.

### ISSUE THREAD

**Issue by wugeer** [minio/minio#20592]
## Expected Behavior

After enabling TLS, the MinIO console's login interface still transmits passwords in encrypted form.

## Current Behavior

After enabling TLS, the MinIO console's login interface still transmits passwords in plain text.

## Steps to Reproduce (for bugs)

1. Log in to the MinIO console using an account 
2. Check the password in the payload of the login interface.
![image](https://github.com/user-attachments/assets/a3abf499-658f-4a8a-aed3-62ec9654d8cd)
![image](https://github.com/user-attachments/assets/84f86678-0175-4890-a1b0-10a08f09e250)
![image](https://github.com/user-attachments/assets/2c8b8b5c-a5f0-474c-862d-37b09c3323ff)

## Your Environment

* Version used (`minio --version`): `RELEASE.2024-10-13T13-34-11Z`
* Server setup and configuration: default
* Operating System and version (`uname -a`): host machine `Linux wugeer 6.6.58-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 23 Oct 2024 17:28:15 +0000 x86_64 GNU/Linux` docker container
![image](https://github.com/user-attachments/assets/988943d3-65f5-439e-9e85-705b9f84d872)

**Comment by marktheunissen** [comment]
That is not how TLS and the browser devtools work. The devtools are able to show you the payload of the request _before_ it gets encrypted for transmission over the TLS connection to MinIO.

If you repeat your test on any other website that uses TLS, it will be the same result.

**Comment by wugeer** [comment]
@marktheunissen Thank you for your reply to this issue. I am wondering now is the login interface payload transmission is the plaintext password, is there any way to let it transmit ciphertext password? I looked at the minio documentation and did not find the relevant configuration or function, is the current community does not support this?

**Comment by marktheunissen** [comment]
@wugeer No, it's not supported because it makes no sense. The connection is TLS so the password is encrypted, along with all other communication, between the browser and the backend. Why do you need it to be encrypted twice?

**Comment by wugeer** [comment]
@marktheunissen Thanks for you replay. It's true that secondary encryption doesn't make sense. Thank you for your guidance.
