### ISSUE TITLE
Enable s390x support

### ISSUE THREAD

**Issue by vivkong** [minio/minio#20595]
We kindly request the re-enabling of support for s390x by publishing the corresponding image and binary. The discontinuation of s390x support would be a significant loss, as evidenced in https://github.com/minio/minio/issues/20560 where minio is referenced and utilized by several other open-source projects, including Apache Camel and Prow. We can offer our assistance and resources to maintain support for s390x.

Thank you for considering our request.

**Comment by harshavardhana** [comment]
We have decided to not publish s390x support anymore, please use source compilation.

**Comment by harshavardhana** [comment]
With the time we have, we can't test and support all kinds of architectures, let alone build binaries and keep them on our dl.minio.io website for public consumption.
