### ISSUE TITLE
Error: Connection Refused using Webhook with docker container.

### ISSUE THREAD

**Issue by RootInit** [minio/minio#20602]
## NOTE

**Error:** 

(eventhook:webhook): dial tcp 127.0.0.1:6969: connect: connection refused

## Expected Behavior

When MinIO sends a notification to the configured webhook endpoint, the example Flask app should successfully receive the event data and return a 200 response which MinIO should receive.

## Current Behavior

MinIO is unable to connect to the webhook server resulting in a "connection refused" error.

## Possible Solution
No clue

## Steps to Reproduce (for bugs)
1. Set up a Flask application as shown in https://blog.min.io/minio-webhook-event-notifications/
```python
from flask import  Flask, jsonify, request

app = Flask(__name__)

@app.route('/', methods=['POST'])
def handle_minio_event():
    event_data = request.json
    app.logger.info(f"Received MinIO event: {event_data}")
    return jsonify(event_data), 200

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=6969)
```

2. Deploy docker container with port bindings.
```
podman run -p 9000:9000 -p 9001:9001 -p 6969:6969 -e "MINIO_NOTIFY_WEBHOOK_ENABLE=on" -e "MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://127.0.0.1:6969" \
  quay.io/minio/minio:latest server /data --console-address ":9001"
```
4. Configure MinIO event listener either via env variables (shows disconnected) or via Events UI (gives error)

## Context
I am trying to set up MinIO notifications.

## Regression
Don't know.

## Your Environment
RELEASE.2024-10-13T13-34-11Z
Fedora Silverblue

**Comment by harshavardhana** [comment]
> podman run -p 9000:9000 -p 9001:9001 -p 6969:6969 -e "MINIO_NOTIFY_WEBHOOK_ENABLE=on" -e "MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://127.0.0.1:6969" \
>   quay.io/minio/minio:latest server /data --console-address ":9001"

in this you are expecting to have flask service be running on the same container as minio, which is not the case, please provide the right endpoint where the webhook is accessible.

**Comment by RootInit** [comment]
> > podman run -p 9000:9000 -p 9001:9001 -p 6969:6969 -e "MINIO_NOTIFY_WEBHOOK_ENABLE=on" -e "MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://127.0.0.1:6969" 
> > quay.io/minio/minio:latest server /data --console-address ":9001"
> 
> in this you are expecting to have flask service be running on the same container as minio, which is not the case, please provide the right endpoint where the webhook is accessible.

:facepalm: Yep I forgot to add `--network host` Thanks.
