### ISSUE TITLE
Intermittent disconnection when download file

### ISSUE THREAD

**Issue by Hieu-github** [minio/minio#20604]
When I download a file about 2Gb, the intermittent disconnection happen. I download through Haproxy and backend is 4 nodes Minio.
After debugging, I was captured some packet as image bellow.
I realized that there are signs of congestion in Haproxy. But "tcp keepalive" packet and "tcp rst packet" were sent very fast. It's so weird.
from the "tcp window full" packet was sent to the "tcp rst" packet was sent just about 2 seconds. It seem like the "TCP keepalive" parameter in linux kernel has not effect.

![image](https://github.com/user-attachments/assets/5a546b37-8e44-47f4-af45-cd7419e98a18)
note: 172.16.38.121 IP address is a Minio node
172.21.80.69 IP address is a Haproxy
## Expected Behavior
"TCP keepalive" Linux parameter should be effect

## Current Behavior
"TCP keepalive" is sent very fast
"TCP RST" in sent within 2 seconds

## Your Environment
* Minio version: minio version RELEASE.2024-03-15T01-07-19Z
* Server setup and configuration:
MINIO_VOLUMES="http://myminio{1...4}.local:9000/mnt/data{1...4}"  
MINIO_OPTS="--console-address :9001"
MINIO_ROOT_USER=<>
MINIO_ROOT_PASSWORD=<>
MINIO_SERVER_URL="https://<mypuclic_domain_name>"
MINIO_PROMETHEUS_URL="http://<my_prometheus_server>"
MINIO_PROMETHEUS_JOB_ID=<my_prometheus_job>
* Operating System and version (`uname -a`):
5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

4 nodes Minio, each node 16 CPU, 40G memory
1 VM Haproxy, 8 CPU, 16G memory

**Comment by harshavardhana** [comment]
Avoid haproxy, use something like https://github.com/minio/sidekick more simpler

**Comment by Hieu-github** [comment]
I don't think that when the congestion happening, the Sidekick or any LB can keep connection if Minio sent to LB a TCP RST packet.
