### ISSUE TITLE
Simple command error could easily lead to a corrupted backend format msg

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2060]
It is easy to corrupt the disks (from the user's point of view):
1.  $ mkdir -p /tmp/fs1/export{1..16}
2.  $ minio server /tmp/fs1/export{1..16}
3. In a new terminal: 
$ mc mb myminio/bucket/ && mc cp file myminio/bucket/
4. Now, you run mistakenly this command and you correct it later 
$ minio server /tmp/fs1/export1
CTRL-C 
$ minio server /tmp/fs1/export{1..16}

FATA[0000] Unable to intialize object layer.             cause=corrupted backend format sysInfo=map[host.arch:amd64 host.name:xps-u host.cpus:4 mem.used:3.2MB mem.total:6.5MB mem.heap.used:3.2MB mem.heap.total:4.7MB host.os:linux host.lang:go1.6.2] type=*errors.errorString

**Comment by harshavardhana** [comment]
> It is easy to corrupt the disks (from the user's point of view):
> 1. $ mkdir -p /tmp/fs1/export{1..16}
> 2. $ minio server /tmp/fs1/export{1..16}
> 3. In a new terminal: 
> $ mc mb myminio/bucket/ && mc cp file myminio/bucket/
> 4. Now, you run mistakenly this command and you correct it later 
> $ minio server /tmp/fs1/export1
> CTRL-C 
> $ minio server /tmp/fs1/export{1..16}
> 
> FATA[0000] Unable to intialize object layer. cause=corrupted backend format sysInfo=map[host.arch:amd64 host.name:xps-u host.cpus:4 mem.used:3.2MB mem.total:6.5MB mem.heap.used:3.2MB mem.heap.total:4.7MB host.os:linux host.lang:go1.6.2] type=*errors.errorString

Yes FS needs to validate if the disk is part of an initialized group // cc @hackintoshrao

**Comment by harshavardhana** [comment]
Assigned this to @balamurugana .
