### ISSUE TITLE
allow a queue for multiple-file uploads via UI

### ISSUE THREAD

**Issue by esarakaitis** [minio/minio#2061]
## Expected behavior

uploading multiple files should happen in serial
## Actual behavior

you can only upload one at a time
## Steps to reproduce the behavior

upload a file, while its uploading, try to upload another
## Minio version

Version: 2016-06-03T19:32:05Z
Release-Tag: RELEASE.2016-06-03T19-32-05Z
Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074

**Comment by brendanashworth** [comment]
This should be fixed by https://github.com/minio/miniobrowser/pull/174 once it lands.

edit: also https://github.com/minio/miniobrowser/commit/a5d0f7e6d2ff67b4ec353ea999bbd57c952e8491 added partial multiple file support before this.
