### ISSUE TITLE
LDAP integration - "Invalid DN Syntax": invalid DN"

### ISSUE THREAD

**Issue by weakcamel** [minio/minio#20616]
I'm trying to configure LDAP (OpenLDAP) per [documentation links](https://min.io/docs/minio/linux/reference/minio-server/settings/iam/ldap.html#comment) and having some difficulties with setting up groups lookup.

## Expected Behavior

LDAP group operations should succeed, e.g.
```
root@minio1:~# mc idp ldap policy attach minio consoleAdmin --group engineers
```

## Current Behavior

User lookup works fine however any attempt to operate groups fail with the following:

```
root@minio1:~# mc idp ldap policy attach minio consoleAdmin --group engineers
mc: <ERROR> Unable to make LDAP policy association. We encountered an internal error, please try again. (Error looking up DN engineers: LDAP client: LDAP Result Code 34 "Invalid DN Syntax": invalid DN).
```

My LDAP config (populated with environment variables or via UI, both react the same) is:

```
root@minio1:~# mc idp  ldap info minio
╭─────────────────────────────────────────────────────────────────────────────╮
│                enable: on                                                   │
│  group_search_base_dn: ou=Groups,dc=mycompany,dc=io  (environment)       │
│   group_search_filter: (cn=%s)  (environment)                               │
│        lookup_bind_dn: cn=admin,dc=mycompany,dc=io  (environment)        │
│           server_addr: ldap1.mycompany.io:389  (environment)             │
│       server_insecure: on  (environment)                                    │
│user_dn_search_base_dn: ou=Users,dc=mycompany,dc=io  (environment)        │
│ user_dn_search_filter: (&(objectClass=inetOrgPerson)(uid=%s))  (environment)│
╰─────────────────────────────────────────────────────────────────────────────╯
```

To troubleshoot, I switched it to unencrypted LDAP and used tshark to capture LDAP traffic and this is what I noticed:

```
# tshark  -i any -s10000 -f "port 389" -V -O ldap

...
Lightweight Directory Access Protocol
    LDAPMessage bindRequest(1) "cn=admin,dc=mycompany,dc=io" simple
        messageID: 1
        protocolOp: bindRequest (0)
            bindRequest
                version: 3
                name: cn=admin,dc=mycompany,dc=io
                authentication: simple (0)
                    simple: REDACTED

Lightweight Directory Access Protocol
    LDAPMessage bindResponse(1) success
        messageID: 1
        protocolOp: bindResponse (1)
            bindResponse
                resultCode: success (0)
                matchedDN:
                errorMessage:
        [Response To: 116]
        [Time: 0.000485515 seconds]

Lightweight Directory Access Protocol
    LDAPMessage searchRequest(2) "engineers" baseObject
        messageID: 2
        protocolOp: searchRequest (3)
            searchRequest
                baseObject: engineers
                scope: baseObject (0)
                derefAliases: neverDerefAliases (0)
                sizeLimit: 0
                timeLimit: 0
                typesOnly: False
                Filter: (objectClass=*)
                    filter: present (7)
                        present: objectClass
                attributes: 1 item
                    AttributeDescription: 1.1

Lightweight Directory Access Protocol
    LDAPMessage searchResDone(2) invalidDNSyntax (invalid DN) [0 results]
        messageID: 2
        protocolOp: searchResDone (5)
            searchResDone
                resultCode: invalidDNSyntax (34)
                matchedDN:
                errorMessage: invalid DN
        [Response To: 120]
        [Time: 0.000284696 seconds]
```

Note that the search request issued doesn't contain the Group DN at all, it just sends the expected group name as the whole baseObject which obviously fails.

I'm seeing the same behaviour on
https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20241013133411.0.0_amd64.deb
as well as `minio_20240715190230.0.0_amd64.deb` or `minio_20241029160148.0.0_amd64.deb`

## Possible Solution
n/a

## Steps to Reproduce (for bugs)

1. Set up MinIO with LDAP in `/etc/default/minio`

```
MINIO_IDENTITY_LDAP_SERVER_ADDR='ldap1.mycompany.io:389'
MINIO_IDENTITY_LDAP_SERVER_INSECURE="on"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN='cn=admin,dc=mycompany,dc=io'
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD='REDACTED'
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN='ou=Users,dc=mycompany,dc=io'
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER='(&(objectClass=inetOrgPerson)(uid=%s))'
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN='ou=Groups,dc=mycompany,dc=io'
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(cn=%s)"
```
2. Run any operation involving groups, e.g. `mc idp ldap policy attach minio consoleAdmin --group engineers`

## Context

This is a blocker for MinIO deployment.

## Your Environment

* Version used (`minio --version`):
```
minio --version
minio version RELEASE.2024-10-29T16-01-48Z (commit-id=c4239ced225b9fead5f6b44e3665c5ccd7eacc89)
Runtime: go1.22.8 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration:
A set of 2 vSphere VMs with 1 base disk + 4 data disks for MinIO (trying out [MultiNode](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html) setup)

* Operating System and version (`uname -a`):
Linux minio1 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by weakcamel** [comment]
Ouch. I just found the reason (documentation ambiguity) while trying to hack around the problem. See here:

https://min.io/docs/minio/linux/reference/minio-mc/mc-idp-ldap-policy-attach.html#description

![image](https://github.com/user-attachments/assets/9ec6584b-e34c-4248-83d5-49cf4329868f)

Syntax description says `--group=GROUP` and doesn't mention that this needs to be Group DN.

To make it worse, 


```
mc idp ldap policy attach myminio  userpolicy --user='bobfisher'
```

works just fine but that doesn't apply to `--group`

Note also that the above syntax description is suggesting both `--user` and `--group` parameters are fully optional (so it's fine to skip either or both of them) whereas in reality at least one of them is required, see below. What is should say to match the current state of things is `< --use='USER DN or USERNAME' | --group 'GROUP DN' >`


The builtin help is more precise and had I used it, I'd have been better off :)

```
root@minio1:~# mc idp ldap policy attach --help
NAME:
  mc idp ldap policy attach - attach a policy to an entity

USAGE:
  mc idp ldap policy attach [FLAGS] TARGET POLICY [POLICY...] [ --user=USER | --group=GROUP ]

  Exactly one "--user" or "--group" flag is required.

POLICY:
  Name of a policy on the MinIO server.

FLAGS:
  --user value, -u value        attach policy to user by DN or by login name
  --group value, -g value       attach policy to LDAP Group DN

... SNIP ...

EXAMPLES:
  1. Attach policy "mypolicy" to a user
     $ mc idp ldap policy attach play/ mypolicy --user='uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io'
  2. Attach policies "policy1" and "policy2" to a group
     $ mc idp ldap policy attach play/ policy1 policy2 --group='cn=projectb,ou=groups,ou=swengg,dc=min,dc=io'
root@minio1:~# mc idp ldap policy attach minio consoleAdmin --group "cn=engineers,ou=Groups,dc=speechmatics,dc=io"
```

Personally, I believe that `--group` should also accept just group name. I mean, what's the point of providing base Group DN in the configuration if user has to refer to groups by full DN anyway?

**Comment by harshavardhana** [comment]
Yes, group DNs are necessary since they can come from multiple hierarchies, and we cannot assume one way or the other. 

You are expected to provide the correct DN.

**Comment by weakcamel** [comment]
> Yes, group DNs are necessary since they can come from multiple hierarchies, and we cannot assume one way or the other.

@harshavardhana How is that different from users? They could also be under multiple hierarches because LDAP is just flexible enough to do so - and yet, MinIO accepts username too, matching it against the preconfigured User Base DN.

> You are expected to provide the correct DN.

Even if so, can we have the [documentation](https://min.io/docs/minio/linux/reference/minio-mc/mc-idp-ldap-policy-attach.html#description) fixed? It currently says `[--user=USER] [--group=GROUP]`, not "GROUP DN" in the syntax description and there's no example for a group either.
