### ISSUE TITLE
Hard quota exceed

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#20629]
I have bucket with hard quota of 1 TB. I've tried to upload few data into this bucket - 4 TB total. Just run script which copy file-by-file into this bucket. After process was completed I've checked the space used in this bucket. MinIO show me only 500 GB. Then day-by-day I see that total used space increases and now the reported usage is 2.7 TB (see screenshot below) and continue increasing. My question how it's possible to write 4 TB of data into bucket with 1 TB hard quota. Is this normal behavior?

![image](https://github.com/user-attachments/assets/e1b8afa5-63f8-4087-a0cc-eb885d0422f6)

## Expected Behavior
Stop receiving new objects when bucket size reaches the limit. 

## Current Behavior
Seems that bucket size calculating is very late what making possible to upload 3-4 times more objects than set in quota.

## Steps to Reproduce (for bugs)
Just upload objects with total size more than bucket quota.

## Your Environment

* Version used (`minio --version`): 2024-09-13T20:26:02Z
* Server setup and configuration: 4 nodes with 4 disks on each
* Operating System and version (`uname -a`): Linux minio-1 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Quota's rely on scanner usage updates, you can always exceed tiny quotas like 1TiB easily by simply uploading large objects.

We have already deprecated quota https://min.io/docs/minio/linux/reference/deprecated/mc-quota.html

> Bucket quotas are not intended to enforce a strict hard limit on a bucket’s size. If a bucket exceeds its quota between scanner passes, MinIO continues to accept PUT requests for that bucket until _after_ the next scanner pass identifies the quota violation.

**Comment by AlexZIX** [comment]
@harshavardhana Does that means that quota feature will be removed or will be replaced with another implementation?

**Comment by klauspost** [comment]
@AlexZIX It is removed. It may be rewritten at some point in a different context, but it has not been decided yet.
