### ISSUE TITLE
Support for GRPC clients

### ISSUE THREAD

**Issue by fpetkovski** [minio/minio#20626]
**Is your feature request related to a problem? Please describe.**

The Google Cloud Storage team recently added support for GRPC: https://cloud.google.com/storage/docs/enable-grpc-api.

I am wondering if MinIO has plans to implement a similar feature to help reduce cpu and memory usage for both the client and server.

**Comment by klauspost** [comment]
We don't really find the API to be any serious limitation on server performance. 

It may be different in thin clients, but either way, though most is just an HTTP stream of data. While XML is clunky, we are not looking to invent our own API. So no; we are not.
