### ISSUE TITLE
AzureChina Gateway Support

### ISSUE THREAD

**Issue by 2dukes** [minio/minio#20622]
Hi,

I'm currently facing an error while using MinIO Gateway (release from 2019-08-01) for an Azure China environment in the China North 3 region.

## Current Behavior

The Minio Gateway logs that support this claim are the following:

```
 ./minio-gateway.stdout.log:28386:Error: Get https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/?comp=list&prefix=internal-logs-container-v2<PARAMETER_SUFFIX>: dial tcp: lookup <STORAGE_ACCOUNT_NAME>.blob.core.windows.net on X.Y.W.Z:53: no such host
```
 
<br>

While looking for the correct Blob Service endpoint in Azure China, I can see that it should be `https://<STORAGE_ACCOUNT_NAME>.blob.core.chinacloudapi.cn/`. However, it seems that this domain is not targeted by Minio Gateway as instead of looking for the `blob.core.chinacloudapi.cn` domain, it's trying to reach `blob.core.windows.net`, most likely due to [this line of code](https://github.com/minio/minio/blob/cefc43e4daa4cbb490ef6726ea374e26a93eb85e/cmd/warm-backend-azure.go#L155).

Would it be possible have support for Azure China as well? If this is not the case, then is there a way to configure this domain?

Thank you in advance.

**Comment by kannappanr** [comment]
I don't think you can overwrite the endpoint

**Comment by 2dukes** [comment]
Overwriting the endpoint probably wouldn't work, but some sort of conditional check, maybe it would be possible from your side 🙂

**Comment by harshavardhana** [comment]
Gateway is deprecated and removed from our codebase.
