### ISSUE TITLE
PutBucketLifecycle(deprecated) vs PutBucketLifecycleConfiguration

### ISSUE THREAD

**Issue by vlvicente** [minio/minio#20632]
### Discussed in https://github.com/minio/minio/discussions/20580

<div type='discussions-op-text'>

<sup>Originally posted by **vlvicente** October 23, 2024</sup>
Can anyone confirm that the new version of LifecycleConfiguration is not yet supported by MinIO?
Context: I've been trying to programmatically add a lifecycle configuration to a bucket, which is rejected with a bad request saying the XML is not wellformed. I'm using [rust-s3](https://docs.rs/rust-s3/latest/s3/index.html) which only implements the new version and the xml does seem well formed and within the specs defined by AWS.
Taking a look at the MinIO implementation I noticed that one of the validations made is this one:
```go
func (r Rule) validatePrefixAndFilter() error {
 if !r.Prefix.set && r.Filter.IsEmpty() || r.Prefix.set && !r.Filter.IsEmpty() {
   return errXMLNotWellFormed
 }
 if !r.Prefix.set {
   return r.Filter.Validate()
 }
 return nil
}
```
which seems to consider the [deprecated version](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycle.html) of the request (in which the Prefix field is in the same level as Filter and marked as required) instead of [new version](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html) (Prefix is moved inside the Filter field)</div>

**Comment by dhananjaykrutika** [comment]
This issue has been fixed at https://github.com/minio/minio/pull/20684
Closing it for now. Feel free to reopen it if the issue persists.
