### ISSUE TITLE
Error: Specified user does not exist

### ISSUE THREAD

**Issue by bakin199** [minio/minio#20652]
Good afternoon! Please tell me how to get rid of this error.
I have a cluster of two nodes, ssl is used. Minio is installed as a binary file. I'm using the latest version.

minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU Gplv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

When starting the mini, everything is fine, there are no errors, two users have been added and policies have been configured for them (1 added independently). Initially, the user and policies were created via the web console.
Even after this error appears, I can create an alias for the mc for the created users and can also log in through them in the web console.

This error does not appear immediately after startup, but after a while. The error goes away after restarting minio, either through systemctl restart minioor through mc admin service restart. But after a while it comes back again.

I also tried to recreate users and policies through the mc, but it didn't give any results. Similarly, an error appears after a while.

What is the reason, what causes it and how can it be fixed?

nov 11 13:37:29 vplin0011 minio[271716]: API: SYSTEM.iam
nov 11 13:37:29 vplin0011 minio[271716]: Time: 10:37:29 UTC 11/11/2024
nov 11 13:37:29 vplin0011 minio[271716]: DeploymentID: 5d721a0e-71a8-418d-b3ac-df90241a1560
nov 11 13:37:29 vplin0011 minio[271716]: Error: Specified user does not exist (*errors.errorString)
nov 11 13:37:29 vplin0011 minio[271716]: 6: internal/logger/logger.go:268:logger.LogIf()
nov 11 13:37:29 vplin0011 minio[271716]: 5: cmd/logging.go:29:cmd.iamLogIf()
nov 11 13:37:29 vplin0011 minio[271716]: 4: cmd/iam-object-store.go:784:cmd.(*IAMObjectStore).loadAllFromObjStore()
nov 11 13:37:29 vplin0011 minio[271716]: 3: cmd/iam-store.go:592:cmd.(*IAMStoreSys).LoadIAMCache()
nov 11 13:37:29 vplin0011 minio[271716]: 2: cmd/iam.go:207:cmd.(*IAMSys).Load()
nov 11 13:37:29 vplin0011 minio[271716]: 1: cmd/iam.go:414:cmd.(*IAMSys).periodicRoutines()

**Comment by harshavardhana** [comment]
This is a false error, can be ignored.

**Comment by bakin199** [comment]
@harshavardhana 
Does this have an impact on the performance of processes? 
Which users are we talking about and is it possible to get rid of this error completely?
