### ISSUE TITLE
Ability to configure MinioStoreName in runtime

### ISSUE THREAD

**Issue by mhkarimi1383** [minio/minio#20663]
**Is your feature request related to a problem? Please describe.**
I want to change server header in MinIO sometimes and I don't want to use reverse proxy

**Describe the solution you'd like**
Being able to change MinioStoreName via env

**Describe alternatives you've considered**
Using a reverse proxy

**Additional context**

**Comment by harshavardhana** [comment]
No you cannot change what the product name is, feel free to made code changes yourself.

We don't want make this configurable, we are not an nginx server.
