### ISSUE TITLE
Unclear how to specify bucket name(s) for v3 bucket metrics

### ISSUE THREAD

**Issue by dhedberg** [minio/minio#20660]
Trying to migrate from v2 metrics to v3 metrics. Some v3-metrics require one or more bucket names to be specified, and I was unable to easily figure out how to do that (or indeed even that it's required at all).

The documentation at https://min.io/docs/minio/kubernetes/upstream/operations/monitoring/metrics-and-alerts.html lists endpoints like `/bucket/replication`, but unless I'm missing it I cannot see that it anywhere says that you need to specify a bucket name.

The documentation at https://github.com/minio/minio/blob/master/docs/metrics/v3.md says that you can add `?buckets=bucket1,bucket2` to the query, but this does not work. (The example paths in this document also seems inverted, with `/api/bucket` instead of `/bucket/api`.)

The relevant code in `cmd/metrics-v3-handler.go` seems to be:

```
        if strings.HasPrefix(pathComponents, "/bucket/") {
                // bucket specific metrics, extract the bucket name from the path.
                // it's the last part of the path. e.g. /bucket/api/<bucket-name>
                bucketIdx := strings.LastIndex(pathComponents, "/")
                buckets = append(buckets, pathComponents[bucketIdx+1:])
```

.. and specifying a single bucket name as the final path component indeed appears to work. But specifying a comma separated list of buckets here does not work, and I see no evidence of any obvious comma splitting magic.

It would be nice if:

1. The documentation is updated to make it a bit more clear how to specify the bucket names, and
2. .. if there was a working way to specify multiple bucket names (preferably with wildcard support if possible)

**Comment by marktheunissen** [comment]
We are actually "undeprecating" v2 metrics for now, as they are still in high demand. Recommend you stick with v2, for more info, follow this: https://github.com/minio/docs/pull/1375
