### ISSUE TITLE
Deleted service account resurrection

### ISSUE THREAD

**Issue by marktheunissen** [minio/minio#20667]
After deleting a user by its service account, with `mc admin user rm ALIAS SERVICE_ACCOUNT`, the service account can be resurrected under certain conditions, and reappears as a valid account.

The API call is `/minio/admin/v3/delete-service-account?accessKey=....`

## Expected Behavior

Deleted service accounts should not reappear.

## Current Behavior

Service accounts can be brought back.

## Steps to Reproduce (for bugs)

I'm restarting the MinIO service to trigger the issue, however both community member and myself have reproduced by simply waiting +-5 mins. 

## Context

Reported in the community Slack channel here: https://minio.slack.com/archives/C3NDUB8UA/p1731866729991619

## Regression

Yes, possibly STS caching work? Just a guess.

## Your Environment

Running MinIO locally, SNSD just on my mac.

**Comment by donatello** [comment]
Oops didn't see you were assigned @taran-p !

This is fixed by the linked PR, now mc will report an error when attempting to delete a service account with `mc admin user rm `
