### ISSUE TITLE
Editing Non current Versioned life cycle

### ISSUE THREAD

**Issue by Mendomutz** [minio/minio#20664]
Upon editing a non current and versioned life cycle, the minio throws the error

>`Unable to generate new lifecycle rule: expiration days cannot be set to zero`

But i cannot change the `expiration days` amount.

#### Steps to Reproduce (for bugs)

1. Create a new life cycle
2. Set to `Non Current`, after n `Versions`, `Expiry` type, filters and advanced don't matter.
3. After creation, edit the new life cycle.

**Comment by dhananjaykrutika** [comment]
Hi @Mendomutz , I'm unable to recreate this issue. Can you list the exact commands you used?

**Comment by harshavardhana** [comment]
Closing as lack of steps to reproduce, please re-open the issue with steps to reproduce. State your version number environment and everything about it. 

Please do not skip the issue template.
