### ISSUE TITLE
A reference to the problem Error: Specified user does not exist #20652

### ISSUE THREAD

**Issue by bakin199** [minio/minio#20670]
Returning to the problem https://github.com/minio/minio/issues/20652

Does this have an impact on the performance of processes?
Which users are we talking about and is it possible to get rid of this error completely?

And how can I find out a more detailed explanation of this error, for example, is it possible to change the log level in minio to debug

**Comment by harshavardhana** [comment]
This error is benign as I explained, for now ignore it.
