### ISSUE TITLE
Fixing the error in a future update

### ISSUE THREAD

**Issue by bakin199** [minio/minio#20675]
Good afternoon!
Returning to the issue of the error described in https://github.com/minio/minio/issues/20652

This error could be reproduced again.

The minio is installed as a binary file in /usr/local/bin/

Minio config:
```
MINIO_VOLUMES="http://minio-{1...2}.mydomain:9000/var/lib/minio/data1/minio"
MINIO_OPTS="--console-address :9001"
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=qwerty123
MINIO_SERVER_URL="http://minio-4.mydomain:8081"
MINIO_BROWSER_REDIRECT_URL="http://minio-4.mydomain:8080/minio/ui"
```

Systemd config:
`curl -O https://raw.githubusercontent.com/minio/minioservice/master/linux-systemd/minio.service`

Users and policies were created through mc:
json has been added:
read-only.json

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

Next, a new policy has been added to minio: 
`mc admin policy create test read-only read-only.json`

Buckets have been created:
```
mc mb test/inbound
mc mb test/outbound
```

Users have been created:
```
mc admin user add test writer testpass123
mc admin user add test reader testpass123
```

They have been assigned policies:
```
mc admin policy attach test readwrite --user=writer
mc admin policy attach test read-only --user=reader
```

Command output: mc admin user ls test
```
enabled    reader                read-only
enabled    writer                readwrite
```
Suddenly, an error appeared in `journalctl-u minio.service ` in a similar way

```
Nov 20 20:33:29 minio-1 minio[2354]: Error: Specified user does not exist (*errors.errorString)
Nov 20 20:33:29 minio-1 minio[2354]:        6: internal/logger/logger.go:268:logger.LogIf()
Nov 20 20:33:29 minio-1 minio[2354]:        5: cmd/logging.go:29:cmd.iamLogIf()
Nov 20 20:33:29 minio-1 minio[2354]:        4: cmd/iam-object-store.go:796:cmd.(*IAMObjectStore).loadAllFromObjStore()
Nov 20 20:33:29 minio-1 minio[2354]:        3: cmd/iam-store.go:592:cmd.(*IAMStoreSys).LoadIAMCache()
Nov 20 20:33:29 minio-1 minio[2354]:        2: cmd/iam.go:207:cmd.(*IAMSys).Load()
Nov 20 20:33:29 minio-1 minio[2354]:        1: cmd/iam.go:415:cmd.(*IAMSys).periodicRoutines()
```

Minio-version:
```
mini version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU Gplv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```

version mc:
```
mc version RELEASE.2024-11-17T19-35-25Z (commit-id=bb4ff4951a3e54bbee6ac75cfaf387c521e98709)
Runtime: go1.23.3 linux/amd64
Copyright (c) 2015-2024 MinIO, Inc.
License GNU Gplv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

System:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

if you need additional information, I can add it without any problems.

Are you planning to fix this error in the next update?

**Comment by marktheunissen** [comment]
Is this not fixed by https://github.com/minio/minio/pull/20691 potentially?

**Comment by bakin199** [comment]
> Разве это не исправлено в #20691 ?

Good afternoon @marktheunissen! 
And how can I test this fix?
If I understood correctly, the new version has not been added yet.

At the moment I am using: 

minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU Gplv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

The file was received in this way:
`wget https://dl.min.io/server/minio/release/linux-amd64/minio`

**Comment by klauspost** [comment]
The version you are running is from before the PR you reference was merged.

This will be in next release.
