### ISSUE TITLE
Minio Binary building is failing on fips enabled

### ISSUE THREAD

**Issue by Repana-Chowdappa** [minio/minio#20676]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Minio Binary building is failing on fips enabled

## Expected Behavior
Should able to build the minio binary

## Current Behavior
Build is failing with below error
```
Building minio binary to './minio'
# github.com/minio/minio/internal/fips
internal/fips/api.go:47:17: undefined: enabled
make: *** [Makefile:179: build] Error 1
```

## Possible Solution
Need to change the Enabled varibale in internal/fips/api.go file to true instread of enabled.
change internal/fips/api.go line 47 to **true**
`const Enabled = true`

## Steps to Reproduce (for bugs)
1. git clone https://github.com/minio/minio.git
2. cd minio
3. sed -i 's/go build -tags kqueue/go build -tags kqueue,fips/g' Makefile
4. make all

## Context
unable to build minio binary from source code

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go build -tags fips -trimpath -o ./minio.fips
