### ISSUE TITLE
aws s3 cp fails with xml parse error during AbortMultipartUpload operation

### ISSUE THREAD

**Issue by krisis** [minio/minio#2067]
## Expected behaviour

`aws s3 cp` must not fail to parse xml response for AbortMultipartUpload operation. i.e, minio server's xml response is incorrect. See sample response below,
## Actual behaviour

`aws s3 cp` fails with the following error message.

```
Unable to parse response (XML or text declaration not at start of entity: line 2, column 0), invalid XML received:
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/my-bucket/87</Resource><RequestId$
3L137</RequestId><HostId>3L137</HostId></Error>

A client error (NoSuchUpload) occurred when calling the AbortMultipartUpload operation: The specified multipart upload does not exist.

```
## Steps to reproduce the behaviour
- Perform many concurrent multipart uploads
## Minio version
- commit id `eb5f782` + #2066 
## System information
- `Linux 4.4.0-24-generic #43-Ubuntu SMP`

**Comment by harshavardhana** [comment]
To be fixed by July 4th

**Comment by harshavardhana** [comment]
@krisis are you still seeing this issue?

**Comment by harshavardhana** [comment]
Moving this out of Standalone Release.

**Comment by GarimaKapoor** [comment]
@krisis can you reproduce this bug.

**Comment by krisis** [comment]
@GarimaKapoor I shall reproduce the issue and update the steps to reproduce.

**Comment by krisis** [comment]
I should be sending a proposed fix by EOD Jul 24.

**Comment by krisis** [comment]
I was unable to recreate this issue with the recent master.  We can close this issue and open a new issue if we observe this later.
