### ISSUE TITLE
Grafana Dashboard for V3 Metrics

### ISSUE THREAD

**Issue by dharmil** [minio/minio#20678]
According to the [website](https://min.io/docs/minio/container/operations/monitoring/metrics-and-alerts.html) the v2 metrics API is deprecated in the newest minio versions. 

The provided [Grafana Dashboard](https://github.com/minio/minio/tree/master/docs/metrics/prometheus/grafana) still relies on metrics from the v2 API like for example [`minio_s3_traffic_sent_bytes`](https://min.io/docs/minio/container/operations/monitoring/metrics-v2-deprecated.html#minio-metrics-v2). I guess the new equivalent for that would be `minio_api_requests_traffic_received_bytes` but I am not sure.

V3 Metrics List: https://min.io/docs/minio/container/operations/monitoring/metrics-and-alerts.html
V2 Metrics List: https://min.io/docs/minio/container/operations/monitoring/metrics-v2-deprecated.html#minio-metrics-v2

Is there already a Dashboard JSON Model available that uses the new API?

**Comment by harshavardhana** [comment]
v3 metrics is not going to get any dashboard, v3 metrics is directly integrated in our observability product as part of AiStor https://min.io/download?view=aistor

**Comment by olljanat** [comment]
> v3 metrics is not going to get any dashboard

@harshavardhana On that case, what is plan with v2 metrics deprecation? It just do not get updates anymore or is plan also to remove it someday?

**Comment by klauspost** [comment]
We don't have any current plans to removing it. The only thing I can say for sure is that there will be no more updates for it.

**Comment by chobostar** [comment]
Would anyone be willing to share their Grafana dashboards based on v3 metrics? It would be very helpful to the community."

**Comment by ElanHasson** [comment]
@chobostar did you get any dashboards? 
I'd like them too.

**Comment by FedericoAntoniazzi** [comment]
@ElanHasson @chobostar 
I created this repository for the Grafana Dashboard that uses v3 metrics. I currently use it for my homeserver in which I have a single minio instance running and I haven't tested it on a MinIO cluster yet.

https://github.com/FedericoAntoniazzi/minio-grafana-dashboard-metrics-v3
