### ISSUE TITLE
Memory leak RELEASE.2024-11-07T00-52-20Z

### ISSUE THREAD

**Issue by codedoga** [minio/minio#20681]
## NOTE
I have single node deployed with official docker container RELEASE.2024-11-07T00-52-20Z. 

There are 5 buckets, with very little traffic. I also have storage tiering to s3 compatible storage (new object storage/ceph from Hetzner). Lifecycle rule is set for transition in 1 day. There is also expiry rule on different bucket also after 1 day.  

Everything works alright expect for occasional error message in log:
```
Error: Specified user does not exist (*errors.errorString)
6: internal/logger/logger.go:268:logger.LogIf()
5: cmd/logging.go:29:cmd.iamLogIf()
4: cmd/iam-object-store.go:796:cmd.(*IAMObjectStore).loadAllFromObjStore()
3: cmd/iam-store.go:592:cmd.(*IAMStoreSys).LoadIAMCache()
2: cmd/iam.go:207:cmd.(*IAMSys).Load()
1: cmd/iam.go:415:cmd.(*IAMSys).periodicRoutines()
```

## Expected Behavior
I guess there should be GC which should take care of occasional memory leaks but it looks like it's not kicking in.

## Current Behavior
But memory usage keeps steadily increasing: 185.5MB on 17-11-2024T17:10 to 275.08MB on 24-11-2024T17:10 without any increase in usage (usage is actually way lower then 7 days ago).

Red is minio container
<img width="675" alt="Slika zaslona 2024-11-24 u 18 53 13" src="https://github.com/user-attachments/assets/01591298-daa4-4515-bc8b-755f036b3d60">

## Steps to Reproduce (for bugs)
I guess deploy single node container from minio/minio:RELEASE.2024-11-07T00-52-20Z image; 
create two buckets one with lifecycle rule to s3 and other one with expiry rule (both 1 day);
Watch for container memory usage

## Context
I would like to have container memory usage affected only by traffic/tiering instead of just by existing.

## Regression
Could be: 
https://github.com/minio/minio/discussions/17871
https://github.com/minio/minio/issues/19219

## Your Environment
Neoverse-N1 (8c/8t)

Ubuntu 22.04.3 LTS
Docker 25.0.3
Minio RELEASE.2024-11-07T00-52-20Z

Single instance in container with only root user, and two buckets configured as stated above.

**Comment by marktheunissen** [comment]
@codedoga The term "memory leak" indicates a bug, if you have evidence of an actual memory leak which the garbage collector cannot cleanup, then please post those steps to reproduce. You can post memory profiles too, to support the bug report.

However, I think what you're seeing is just normal behavior. Please see https://min.io/docs/minio/linux/operations/checklists/hardware.html#memory our guidance on this.

> Starting with [RELEASE.2024-01-28T22-35-53Z](https://github.com/minio/minio/releases/tag/RELEASE.2024-01-28T22-35-53Z), MinIO preallocates 2GiB of memory per node in distributed setups and 1GiB of memory for a single-node setup.

You're basically asking why MinIO memory use increases by 80M over time. This is totally within normal operating parameters. For example we collect stats in the background, there are various caches that begin to fill, etc.

**Comment by codedoga** [comment]
@marktheunissen thank you for quick response.

It was just curios to me to see constant increase in memory usage because I have different server with RELEASE.2024-10-13T13-34-11Z where it doesn't happen at all.

**Comment by harshavardhana** [comment]
Minor increases in MiBs are mostly just noise. 

Please provide more evidences of an OOM etc, if none of that happens a minor increase in 80mib is business as usual we do not do such micro optimizations.
