### ISSUE TITLE
FATAL Unable to use the drive /minio_vol: drive not found: Invalid arguments specified

### ISSUE THREAD

**Issue by gitnatarajan** [minio/minio#20686]
FATAL Unable to use the drive /minio_vol: drive not found: Invalid arguments specified

I am currently using the minio version RELEASE.2022-04-09T15-09-52Z  in ubuntu 22, I have tried to update to the latest version .
After updating the latest version , the minio service is getting failed while starting.

Getting error in syslogs as FATAL Unable to use the drive /minio_vol: drive not found: Invalid arguments specified.

* Version used : RELEASE.2022-04-09T15-09-52Z
* Server setup and configuration: "Ubuntu 22.04.4 LTS
* Operating System and version (`uname -a`): "Ubuntu 22.04.4 LTS

**Comment by klauspost** [comment]
Since it says `Invalid arguments specified`, try providing the arguments your are specifying.

**Comment by gitnatarajan** [comment]
HI @klauspost ,

After upgrade i am unable to start the service , below is the syslog error and my service file of minio.
I have tried by adding the arguments like  (which are already included in service file)
MINIO_VOLUMES="/minio_vol"
MINIO_OPTS="--console-address :9001"
the above vars are already declarec in /etc/default/minio


### Old version details:

minio --version
minio version RELEASE.2022-04-09T15-09-52Z

### After update
### syslog output:

minio[121393]: FATAL Unable to use the drive /minio_vol: drive not found: Invalid arguments specified
systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: minio.service: Failed with result 'exit-code'.
systemd[1]: Failed to start MinIO.
systemd[1]: minio.service: Scheduled restart job, restart counter is at 5.
systemd[1]: Stopped MinIO.
systemd[1]: minio.service: Start request repeated too quickly.
systemd[1]: minio.service: Failed with result 'exit-code'.
systemd[1]: Failed to start MinIO.

### journalctl -xeu minio.service


Nov 25 19:01:22 systemd[1]: minio.service: Start request repeated too quickly.
Nov 25 19:01:22 systemd[1]: minio.service: Failed with result 'exit-code'.
Subject: Unit failed
Defined-By: systemd
 Support: http://www.ubuntu.com/support
The unit minio.service has entered the 'failed' state with result 'exit-code'.
Nov 25 19:01:22 gccvedl2011933 systemd[1]: Failed to start MinIO.
Subject: A start job for unit minio.service has failed

### cat /lib/systemd/system/minio.service : 

[Unit]
Description=MinIO
Documentation=https://docs.min.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
Type=notify
WorkingDirectory=/usr/local
User=minio-user
Group=minio-user
ProtectProc=invisible
Environment="MINIO_LOG_LEVEL=debug"
EnvironmentFile=-/etc/default/minio
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

Restart=always
LimitNOFILE=1048576
MemoryAccounting=no
TasksMax=infinity
TimeoutSec=infinity
SendSIGKILL=no

[Install]
WantedBy=multi-user.target


Even i have tried directly to start the service via binary
_/usr/local/bin/minio server --console-address :9001  /minio_vol_
Error: FATAL Unable to use the drive /minio_vol: drive not found: Invalid arguments specified

but the dir /minio_vol contains the bucket and .minio.sys which is generated at older version

/minio_vol# ls -la
total 16
drwxr-xr-x  4 minio-user minio-user 4096 Nov 25 19:23 .
drwxr-xr-x 23 root       root       4096 Nov 25 19:23 ..
drwxr-xr-x  7 minio-user minio-user 4096 Nov 25 19:20 .minio.sys
drwxr-xr-x  2 minio-user minio-user 4096 Nov 25 18:15 mytestbucket

### Updated minio version
minio --version
minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

Kindly assist me further

Thanks,
Natarajan.P

**Comment by harshavardhana** [comment]
is your `/minio_vol` a mounted partition or part of root drive?

**Comment by gitnatarajan** [comment]
@harshavardhana : Its part of root drive .

**Comment by harshavardhana** [comment]
Then you need to set CI=true

**Comment by gitnatarajan** [comment]
hi @harshavardhana,
I have set the env var as CI=true.
i have checked in both scenario where the /minio_vol as from / dir as well as dedicated lvm mounted on /minio_vol.

but even after that also , minio service is not getting started , 
getting the below error in syslog

minio[125589]: FATAL Unable to use the drive /minio_vol: drive not found: Invalid arguments specified
systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: minio.service: Failed with result 'exit-code'.
systemd[1]: Failed to start MinIO.
systemd[1]: minio.service: Scheduled restart job, restart counter is at 2.
systemd[1]: Stopped MinIO.
systemd[1]: Starting MinIO...

**Comment by gitnatarajan** [comment]
Hi @harshavardhana,

I have made the service up and running , But I am unable to see the objects inside the buckets.
buckets are available with 0 objects

Regards,
Natarajan.P

**Comment by Lon-Liang** [comment]
HI @harshavardhana 
I have the same problem,/data is an NFS mounted directory, and when I start it, I encounter the error 'FATAL Unable to use the drive /data/miniodata: drive not found: Invalid arguments specified'
![微信截图_20241206162555](https://github.com/user-attachments/assets/7af175a4-ea0b-43a1-b423-e53b346aa68e)

**Comment by marktheunissen** [comment]
@Lon-Liang Hi, what else have you tried? Did you set `CI=true`? Does it work when you run on a different directory that isn't NFS mounted? We don't recommend NFS ever.

**Comment by klauspost** [comment]
@Lon-Liang Don't use NFS. It is not stable. This fails because of ODIRECT, but it generally just presents unstable behavior.

**Comment by gitnatarajan** [comment]
Hi All,
I hope the issue with data format . I have deployed the latest version in another server and moved the data using mc client utility.
