### ISSUE TITLE
Audit-logs UI 

### ISSUE THREAD

**Issue by dpaceoffice** [minio/minio#20687]
The UI reports audit logs are not available despite docs referred to [here](https://min.io/docs/minio/windows/operations/monitoring/minio-logging.html?ref=con) setting environment variables.

![image](https://github.com/user-attachments/assets/ead4c68e-3937-430f-91c1-e9478c63d568)

My config..

![image](https://github.com/user-attachments/assets/679c5030-83df-4d0d-add4-c9561e0f1677)

My webhook is receiving the logs and is storing them locally... Occasionally, I will see this error:

```
API: SYSTEM.config
Time: 03:09:32 UTC 11/26/2024
DeploymentID: d7775b0f-5fc5-436e-92f7-387382365c1d
RequestID: 
RemoteHost: 
UserAgent: 
Error: unable to send audit/log entry(s) to 'minio-http-audit-local' err 'http://webhook-service:5000/audit returned 'Post "http://webhook-service:5000/audit": EOF', please check your endpoint configuration': 1 (*fmt.wrapError)

Backtrace: 
0: internal/logger/logonce.go:64:logger.(*logOnceType).logOnceConsoleIf()
1: internal/logger/logonce.go:157:logger.LogOnceConsoleIf()
2: cmd/logging.go:132:cmd.configLogOnceConsoleIf()
3: internal/logger/target/http/http.go:442:http.(*Target).startQueueProcessor()
```

Is the UI not expected to show anything despite there being a configuration in place for Audit Logs? 

Thanks..

**Comment by harshavardhana** [comment]
This UI has moved to our AiStor observability product, please purchase that.
