### ISSUE TITLE
Error: Marking core-minio-1.core-minio-svc.dr-app.svc.cluster.local:9000 offline temporarily; caused by Post "http://core-minio-1.core-minio-svc.dr-app.svc.cluster.local:9000/minio/lock/v7/rlock": lookup core-minio-1.core-minio-svc.dr-app.svc.cluster.local on 172.30.0.10:53: no such host (*fmt.wrapError)

### ISSUE THREAD

**Issue by rvamir** [minio/minio#20694]
## Expected Behavior
MinIO server pods should seamlessly communicate with each other in a multi-node setup using a StatefulSet and ClusterIP service. DNS should resolve correctly, and all nodes should remain online to serve requests.

## Current Behavior
The MinIO cluster intermittently fails DNS resolution between nodes, causing errors like:
Unable to resolve DNS for Unable to resolve DNS for http://core-minio-0.core-minio-svc.dr-app.svc/export: lookup core-minio-0.core-minio-svc.dr-app.svc on 10.0.0.10:53: no such host (*fmt.wrapError)
This leads to failures in internal communication between MinIO pods, with one node being reported as Offline for brief periods.
also in mc admin info command all drive l network showing online and able to curl  their svc from inside container each other pods . 200.
also i update to latest version 
but still getting 
API: SYSTEM.bootstrap
Time: 03:48:52 UTC 11/27/2024
Error: Unable to resolve DNS for http://core-minio-0.core-minio-svc.dr-app.svc/export: lookup core-minio-0.core-minio-svc.dr-app.svc on 10.0.0.10:53: no such host (*fmt.wrapError)
       host="core-minio-0.core-minio-svc.dr-app.svc", elapsedTime="1 second elapsed"
      10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       9: internal/logger/logonce.go:149:logger.LogOnceIf()
       8: cmd/logging.go:82:cmd.bootLogOnceIf()
       7: cmd/endpoint.go:869:cmd.PoolEndpointList.UpdateIsLocal()
       6: cmd/endpoint.go:1007:cmd.CreatePoolEndpoints()
       5: cmd/endpoint-ellipses.go:508:cmd.createServerEndpoints()
       4: cmd/server-main.go:344:cmd.serverHandleCmdArgs()
       3: cmd/server-main.go:687:cmd.serverMain.func2()
       2: cmd/server-main.go:512:cmd.bootstrapTrace()
       1: cmd/server-main.go:683:cmd.serverMain()

API: SYSTEM.bootstrap
Time: 03:48:52 UTC 11/27/2024
Error: Unable to resolve DNS for http://core-minio-1.core-minio-svc.dr-app.svc/export: lookup core-minio-1.core-minio-svc.dr-app.svc on 10.0.0.10:53: no such host (*fmt.wrapError)
       host="core-minio-1.core-minio-svc.dr-app.svc", elapsedTime="1 second elapsed"
      10: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       9: internal/logger/logonce.go:149:logger.LogOnceIf()
       8: cmd/logging.go:82:cmd.bootLogOnceIf()
       7: cmd/endpoint.go:869:cmd.PoolEndpointList.UpdateIsLocal()
       6: cmd/endpoint.go:1007:cmd.CreatePoolEndpoints()
       5: cmd/endpoint-ellipses.go:508:cmd.createServerEndpoints()
       4: cmd/server-main.go:344:cmd.serverHandleCmdArgs()
       3: cmd/server-main.go:687:cmd.serverMain.func2()
       2: cmd/server-main.go:512:cmd.bootstrapTrace()
       1: cmd/server-main.go:683:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialize...
Automatically configured API requests per node based on available memory on the system: 3922
All MinIO sub-systems initialized successfully in 27.686062ms

## Steps to Reproduce (for bugs)
Deploy MinIO in Kubernetes using a StatefulSet with 2 replicas and a ClusterIP service.

This issue disrupts internal MinIO cluster communication, impacting availability and operations such as bucket creation and data replication. It is critical to resolve this for maintaining a reliable distributed storage system in a production environment.

## Your Environment
Version used: MinIO RELEASE.2024-04-18T19-09-19Z
Server setup and configuration:
Kubernetes StatefulSet with 2 replicas
Service: Headless, ClusterIP: None, publishNotReadyAddresses: true
openshift(ARO) on Azure with minio as storage

**Comment by rvamir** [comment]
checked dns logs in kube-system but no error also restarted

**Comment by rvamir** [comment]
minio is deployed via helm -  which was working fine been an year and have out of 10TB , 6TB is only filled . 
enabled: true
fullnameOverride: core-minio
replicas: 2
existingSecret: minioroot-credentials
configPathmc: /app
persistence:
  size: 10T
environment:
  MINIO_DOMAIN: core-minio
  MINIO_REGION: us-east-1
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
makeBucketJob:
  annotations:
    helm.sh/hook-weight: "-5"
  extraVolumes:
    - name: app
      emptyDir: {}
  extraVolumeMounts:
    - name: app
      mountPath: /app
      readOnly: false
makeUserJob:
  annotations:
    helm.sh/hook-weight: "-5"
  extraVolumes:
    - name: app
      emptyDir: {}
  extraVolumeMounts:
    - name: app
      mountPath: /app
      readOnly: false
buckets:
  - name: drdata
    policy: none
    purge: false
  - name: drlogs
    policy: none
    purge: false
users:
  - accessKey: xx
    existingSecret: xx
    existingSecretKey: secretKey
    policy: readwrite
securityContext:
  enabled: false
resources:
  requests:
    memory: "1Gi"
    cpu: "250m"

**Comment by marktheunissen** [comment]
Hi @rvamir this is not a bug in MinIO, it's something to do with your Kubernetes environment. The steps you have provided to reproduce are the same steps we use internally, and with our customers, successfully all the time.

DNS resolution is a complicated issue especially in Kubernetes. You'll have to dig deep into your environment specifics.

Please note we only support issues in Github community on the latest version, please update RELEASE.2024-04-18T19-09-19Z to the latest version before opening issues
