### ISSUE TITLE
Audit-logs not reporting correct object-location

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/minio#20692]
Fields under "tags" in audit-logs are not reporting the same or correct object-location anymore.

## Expected Behavior
Fields under "tags" in audit-logs like "GetObject" and "GetObjectInfo" should report the same correct object-location
Fields under "tags" in audit-logs like "PutObject" and "GetObjectInfo" should report the same correct object-location

## Current Behavior
Fields under "tags" in audit-logs report a different object-location.
Example: 
audit-log of one PutObject-call gives:
 - tags.GetObjectInfo : "name=testfile,pool=2,set=3"
 - tags.PutObject: "name=testfile,pool=3,set=1"

## Possible Solution
A different field for object-location which is always correct... "GetObjectInfo" doesn't seem like the correct naming either.

## Regression
These are "new" fields under "tags". It used to be objectLocation.poolId and objectLocation.setId. That changed apparently.

## Your Environment
* Version used (`minio --version`): RELEASE.2024-10-02T17-50-41Z (commit-id=ded0b19d97bb9f73f4d78382eb131ff80003e272)
* Server setup and configuration: 3 pools of 4 nodes each
* Operating System and version (`uname -a`): Linux 6.1.0-0.deb11.21-amd64

**Comment by marktheunissen** [comment]
Hi @hamalchristiaan, what do you expect to see?

```
tags.GetObjectInfo : "name=testfile,pool=2,set=3"
tags.PutObject: "name=testfile,pool=3,set=1"
```

When running multiple pools, for many operations MinIO needs to check whether the object is present in every pool first, as it doesn't know exactly which pool holds the object. 

Please provide much more detailed info to reproduce and what you expect to see, but first update to the latest version `RELEASE.2024-10-02T17-50-41Z` is not the latest
