### ISSUE TITLE
Content type from webhook event return wrong

### ISSUE THREAD

**Issue by lechuhuuha** [minio/minio#20699]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

I had setup a event destinations in /settings/event-destinations
the event will push to /api/v1/minio-events in my nodejs backend

in my nodejs backend i receive the event and parse its
when event s3:ObjectCreated:Copy come
i will get the content-type from event and add to database

expected
the s3.object.contentType should be "application/pdf"
```
{
  eventVersion: '2.0',
  eventSource: 'minio:s3',
  awsRegion: '',
  eventTime: '2024-11-28T05:08:56.708Z',
  eventName: 's3:ObjectCreated:Copy',
  userIdentity: { principalId: 'myminioadmin' },
  requestParameters: {
    principalId: 'myminioadmin',
    region: '',
    sourceIPAddress: '172.18.0.1'
  },
  responseElements: {
    'content-length': '232',
    'x-amz-id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
    'x-amz-request-id': '180C099F5B00DCCC',
    'x-minio-deployment-id': '4e728b44-72eb-4641-864d-bf440c34983f',
    'x-minio-origin-endpoint': 'http://172.18.0.3:9000'
  },
  s3: {
    s3SchemaVersion: '1.0',
    configurationId: 'Config',
    bucket: {
      name: '6747d5b0fa113eced44f7f9e',
      ownerIdentity: [Object],
      arn: 'arn:aws:s3:::6747d5b0fa113eced44f7f9e'
    },
    object: {
      key: 'Tika-in-Action.pdf',
      size: 18055875,
      eTag: 'f45e9298d7e64a7645c0ab0fef0a092b',
      contentType: 'binary/octet-stream',
      userMetadata: [Object],
      sequencer: '180C099F5DA0EC11'
    }
  },
  source: {
    host: '172.18.0.1',
    port: '',
    userAgent: 'MinIO (linux; x64) minio-js/8.0.2'
  }
}
```

## Current Behavior
the current the s3.object.contentType is "binary/octet-stream" making is irrelivant.

## Possible Solution
return correct content type for event type

## Steps to Reproduce (for bugs)
1. Setup new instance minio in docker
2. docker pull minio/minio
3. create file `/etc/default/minio`
4. paste content: in https://min.io/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#create-the-environment-variable-file
5. ![ảnh](https://github.com/user-attachments/assets/10c0a391-69e8-4904-9bf5-9dd6c012729f)
6. docker run -dt -p 9000:9000 -p 9001:9001 -v PATH:/mnt/data -v /etc/default/minio:/etc/config.env -e "MINIO_CONFIG_ENV_FILE=/etc/config.env" --name "minio_local" minio/minio:latest server --console-address ":9001"
7. Create new event webhook in [settings/event-destinations](http://localhost:9001/settings/event-destinations) with these info
8. ![ảnh](https://github.com/user-attachments/assets/36ffa985-36ca-4b04-a905-5fcd8ba1bc53)
9. Setup new expressjs server to receive webhook event
```typescript
import express, { Request, Response } from 'express';

// Initialize Express app
const app = express();

// Middleware to parse JSON request bodies
app.use(express.json());

// Route to handle MinIO events
app.post('/api/v1/minio-events', (req: Request, res: Response) => {
  try {
    // Log the event from the request body
    console.log('Received MinIO event:', req.body);

    // Respond with 200 OK
    res.status(200).send('OK');
  } catch (error) {
    console.error('Error processing event:', error.message);
    res.status(500).send('Internal Server Error');
  }
});

// Start the server
const PORT = 3000; // Adjust as needed
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
```

## Context
i try to send file content from minio to apache tika to get text from pdf, word,...

## Regression
No

## Your Environment

* Version used (`minio --version`): 
minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

* Server setup and configuration: wsl2 in windows 11
* Operating System and version (`uname -a`): Linux db8574d56236 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marktheunissen** [comment]
Hi @lechuhuuha you left out the most important part, which is: how are you triggering the object copy? 

I cannot reproduce this, when using `mc` our CLI client.

`mc cp --disable-multipart local/marktest/big-ol.pdf local/marktest/another.pdf`

I copy the pdf using the above command, then run `mc admin trace ALIAS` and see:

`2024-11-29T16:11:30.176 [200 OK] s3.CopyObject 127.0.0.1:9000/marktest/another.pdf 127.0.0.1        48.983ms     ⇣  48.934ms   ↑ 149 B ↓ 232 B`

And then in the audit logs, I see:

`EventName:s3:ObjectCreated:Copy .... ContentType:application/pdf`

So it is working, there is just something wrong with whatever you're doing to execute the copy of the object. 

You can read the SDK code for our language samples (e.g. minio-go, minio-js) and see how we do it, in there.

**Comment by lechuhuuha** [comment]
Hi @marktheunissen 

in my application
when user upload file
in front end i divide each part of the file into chunks using File api https://developer.mozilla.org/en-US/docs/Web/API/File

then upload each chunk into backend nodejs
in backend nodejs i use putObject https://min.io/docs/minio/linux/developers/javascript/API.html#putobject-bucketname-objectname-stream-size-metadata-callback

after all the chunk finish post to server
i use  composeObject https://min.io/docs/minio/linux/developers/javascript/API.html#composeobject-destobjconfig-sourceobjectlist

to compose all chunk file into single file

when use this composeObject func
minio will send me 2 event
 s3:ObjectCreated:Copy - the object will represent the final file after all chunk file merge into that final file
 s3:ObjectRemoved:Delete - chunk file get deleted which i ignore this events

thanks
