### ISSUE TITLE
MINIO_BROWSER_REDIRECT_URL URL contains unexpected resources

### ISSUE THREAD

**Issue by domme1908** [minio/minio#20704]
## Minio refuses to accept http://minio._mydomain.com_/**admin** as MINIO_BROWSER_REDIRECT_URL

I would like to expose the minio UI behind nginx on the subpath /admin. I'd expect minio to serve the static resources such as root-styles.css under the path http://minio._mydomain.com_/**admin**/styles/root-styles.css. As per the official [documentation](https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#envvar.MINIO_BROWSER_REDIRECT_URL) I set MINIO_BROWSER_REDIRECT_URL variable to http://minio._mydomain.com_/**admin**. 

## Expected Behavior
Minio accepts the variable and serves static files under the given path
## Current Behavior

Minio does not even start. This is the error message:
ERROR Invalid MINIO_BROWSER_REDIRECT_URL value is environment variable: URL contains unexpected resources, expected URL to be of http(s)://minio.example.com format: http://minio.******.com/admin

## Steps to Reproduce (for bugs)
Set MINIO_BROWSER_REDIRECT_URL to a domain that includes a path like /admin

## Your Environment
* minio/minio:RELEASE.2022-03-17T06-34-49Z
* microk8s k8s cluster
* 5.15.0-107-generic 117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
S3 APIs cannot be served on a subpath.
