### ISSUE TITLE
Minio S3 Cluster Each folder can only write one object now

### ISSUE THREAD

**Issue by williamsun-hha** [minio/minio#20705]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

The Minio S3 cluster was setup on AKS.  It has been working normally until now.  

Debug error message below:      remove the URL info.   "mc: <ERROR> Failed to copy ... net/http: HTTP/1.x transport connection broken: http: ContentLength=11681 with Body length 0
 (3) mirror-main.go:586 cmd.(*mirrorJob).monitorMirrorStatus(..) Tags:   ... 2024-06-06/2024-06-06 16_03_28.108208-25cb.json
 (2) common-methods.go:510 cmd.uploadSourceToTargetURL(..)  ..  2024-06-06/2024-06-06 16_03_28.108208-25cb.json
 (1) common-methods.go:212 cmd.putTargetStream(..)  .. . 2024-06-06/2024-06-06 16_03_28.108208-25cb.json
 (0) client-s3.go:1161 cmd.(*S3Client).Put(..)
 Release-Tag:RELEASE.2024-10-08T09-37-26Z | Commit:cf128de2cf42 | Host:chipdrop-wus2-bastion01 | OS:linux | Arch:amd64 | Lang:go1.22.8 | Mem:7.8 MiB/17 MiB | Heap:7.8 MiB/11 MiB
"

Bucket quota: 
Bucket `nextgen-xxx` has  quota of 0 B
Bucket `nextgen-xxx-2` has  quota of 0 B

From Minio Console reported usage

Bucket: nextgen-xxx
Usage
1.3TiB
Objects
130,326,292

Bucket: nextgen-xxx-2
Usage
0.0 B
Objects
0

Both buckets have the same issue.

nextgen-xxx-2 is created today. 

CLuster info. 

●  myminio-minionpd8s-0.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-1.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-2.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-3.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-4.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-5.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-6.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

●  myminio-minionpd8s-7.myminio-hl.tenant-ns.svc.cluster.local:9000
   Uptime: 5 days 
   Version: 2024-10-02T17:50:41Z
   Network: 8/8 OK 
   Drives: 8/8 OK 
   Pool: 1

┌──────┬───────────────────────┬─────────────────────┬──────────────┐
│ Pool │ Drives Usage          │ Erasure stripe size │ Erasure sets │
│ 1st  │ 25.6% (total: 46 TiB) │ 16                  │ 4            │
└──────┴───────────────────────┴─────────────────────┴──────────────┘

1.3 TiB Used, 1 Bucket, 130,247,552 Objects
64 drives online, 0 drives offline, EC:4

Backend type: Erasure
Standard storage class parity:   4
Reduced redundancy storage class parity: 1

## Expected Behavior

mirror command should replicate the s3 objects from source to destination normally.   Currently it can only copy one object, then stop working.

Not sure what the issue.  There are plenty disk space.  and Minio console reported cluster healthy

## Current Behavior

Tested copy objects from the source to local disk.  working fine.
test copy objects from local disck to minio S3.  only 1st local object copied to minio S3 successfully 
...15_54_20.787889-0dbf.json: 16.53 KiB / 16.53 KiB 

Second file failed with message below
'2024-06-06 15_57_47.640422-ba81.json`. Resource requested is unwritable, please reduce your request rate
repeat copying failed with the same error

Third file  failed with message below
'2024-06-06 16_03_28.108208-25cb.json`. Resource requested is unwritable, please reduce your request rate

## Possible Solution

Not sure. Thank you very much for your help!

## Steps to Reproduce (for bugs)

Steps are listed above
1.
2.
3.
4.

## Context

Currently S3 cluster can not be used for production operations 

## Regression

The issue is persistent now.

## Your Environment

* Version used (`minio --version`):      Version: 2024-10-02T17:50:41Z
* Server setup and configuration: Azure AKS: 8 nodes with 8 x 1TiB drives.  Info is above. 
* Operating System and version (`uname -a`):   AKS 1.30.3
* helm list -n tenant-ns
NAME  	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART       	APP VERSION
tenant	tenant-ns	8       	2024-11-11 16:54:30.78810769 +0000 UTC	deployed	tenant-6.0.4	v6.0.4  

Thank you very much for your help!

**Comment by harshavardhana** [comment]
Quotas rely on usage, setting tiny quotas is not recommended. Read the docs..

**Comment by williamsun-hha** [comment]
Just checked the document  https://min.io/docs/minio/container/operations/checklists/thresholds.html.  I do not see any limit was broken.  One bucket has 130.3M objects.   The quota is disabled from the Minio Console.

**Comment by williamsun-hha** [comment]
@harshavardhana ,  there are no quota set on the bucket.   Where  did you see where (setting tiny quotas) is set.  I think the command returned quota 0 meant to be no quota on the bucket.   Please do not close this.
