### ISSUE TITLE
Error: IAM sub-system is partially initialized, unable to write the IAM format: etcd is unreachable, please check your endpoints

### ISSUE THREAD

**Issue by CalmVibes** [minio/minio#20708]
Hello!

Minio authorization and healthcheck stopped working. The logs say: `Error: IAM sub-system is partially initialized, unable to write the IAM format: etcd is unreachable, please check your endpoints [https://<minio-console-domain-name>:9000]`. At the same time, the docker container does not have etcd settings initially. There were never any etcd processes on the server, as well as its ports. Perhaps, users added an etcd endpoint in the tenant settings. Please tell how to fix it now? I tried to write MINIO_ETCD_ENDPOINTS: "" in the environment of the docker-compose.yml file, recreate the container, it did not help.

image: minio/minio:RELEASE.2023-11-11T08-14-41Z

Logs:
![container logs](https://github.com/user-attachments/assets/a39cadce-ae67-4ea8-a4fe-0df542eebb91)

Healthcheck:
![healthcheck](https://github.com/user-attachments/assets/cab1ceff-f95c-419a-95ce-ab074e713876)

Console login:
![console](https://github.com/user-attachments/assets/bb5fe5ed-217d-485f-b6bb-1beb7f9ea2ac)

**Comment by harshavardhana** [comment]
Just make etcd available, also before reporting issues make sure to upgrade your setup.

**Comment by CalmVibes** [comment]
> Just make etcd available, also before reporting issues make sure to upgrade your setup.

Please tell to which etcd does Minio connect in the container by default? We did not set any environment related to etcd in the container. And we did not set up any etcd for Minio. Here are all the variables in the container:
      MINIO_DOMAIN: 
      MINIO_SERVER_URL:
      MINIO_ROOT_USER: 
      MINIO_ROOT_PASSWORD: v
      MINIO_BROWSER_REDIRECT_URL: 
      MINIO_PROMETHEUS_AUTH_TYPE: 
      MINIO_KMS_SECRET_KEY: 
      MINIO_CACHE: 
      MINIO_API_REQUESTS_MAX:

**Comment by CalmVibes** [comment]
It worked to remove the `/.minio.sys/config/` directory from the tenant's data copy, start Minio container, wait fo init, shut it down, and return the `/iam/` directory back.
