### ISSUE TITLE
Minio S3 Cluster Each folder can only write one object now related issue (harshavardhana accidentally closed ) #20705.  Please help!

### ISSUE THREAD

**Issue by williamsun-hha** [minio/minio#20706]
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

The Minio S3 cluster was setup on AKS. It has been working normally until now.

Debug error message below: remove the URL info. "mc: Failed to copy ... net/http: HTTP/1.x transport connection broken: http: ContentLength=11681 with Body length 0
(3) mirror-main.go:586 cmd.(*mirrorJob).monitorMirrorStatus(..) Tags: ... 2024-06-06/2024-06-06 16_03_28.108208-25cb.json
(2) common-methods.go:510 cmd.uploadSourceToTargetURL(..) .. 2024-06-06/2024-06-06 16_03_28.108208-25cb.json
(1) common-methods.go:212 cmd.putTargetStream(..) .. . 2024-06-06/2024-06-06 16_03_28.108208-25cb.json
(0) client-s3.go:1161 cmd.(*S3Client).Put(..)
Release-Tag:RELEASE.2024-10-08T09-37-26Z | Commit:cf128de2cf42 | Host:chipdrop-wus2-bastion01 | OS:linux | Arch:amd64 | Lang:go1.22.8 | Mem:7.8 MiB/17 MiB | Heap:7.8 MiB/11 MiB
"

Bucket quota:
Bucket nextgen-xxx has quota of 0 B
Bucket nextgen-xxx-2 has quota of 0 B

From Minio Console reported usage

Bucket: nextgen-xxx
Usage
1.3TiB
Objects
130,326,292

Bucket: nextgen-xxx-2
Usage
0.0 B
Objects
0

Both buckets have the same issue.

nextgen-xxx-2 is created today.

CLuster info.

● myminio-minionpd8s-0.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-1.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-2.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-3.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-4.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-5.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-6.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

● myminio-minionpd8s-7.myminio-hl.tenant-ns.svc.cluster.local:9000
Uptime: 5 days
Version: 2024-10-02T17:50:41Z
Network: 8/8 OK
Drives: 8/8 OK
Pool: 1

┌──────┬───────────────────────┬─────────────────────┬──────────────┐
│ Pool │ Drives Usage │ Erasure stripe size │ Erasure sets │
│ 1st │ 25.6% (total: 46 TiB) │ 16 │ 4 │
└──────┴───────────────────────┴─────────────────────┴──────────────┘

1.3 TiB Used, 1 Bucket, 130,247,552 Objects
64 drives online, 0 drives offline, EC:4

Backend type: Erasure
Standard storage class parity: 4
Reduced redundancy storage class parity: 1

Expected Behavior

mirror command should replicate the s3 objects from source to destination normally. Currently it can only copy one object, then stop working.

Not sure what the issue. There are plenty disk space. and Minio console reported cluster healthy

Current Behavior

Tested copy objects from the source to local disk. working fine.
test copy objects from local disck to minio S3. only 1st local object copied to minio S3 successfully
...15_54_20.787889-0dbf.json: 16.53 KiB / 16.53 KiB

Second file failed with message below
'2024-06-06 15_57_47.640422-ba81.json`. Resource requested is unwritable, please reduce your request rate
repeat copying failed with the same error

Third file failed with message below
'2024-06-06 16_03_28.108208-25cb.json`. Resource requested is unwritable, please reduce your request rate

Possible Solution

Not sure. Thank you very much for your help!

Steps to Reproduce (for bugs)

Steps are listed above
1.
2.
3.
4.

Context

Currently S3 cluster can not be used for production operations

Regression

The issue is persistent now.

Your Environment

Version used (minio --version): Version: 2024-10-02T17:50:41Z
Server setup and configuration: Azure AKS: 8 nodes with 8 x 1TiB drives. Info is above.
Operating System and version (uname -a): AKS 1.30.3
helm list -n tenant-ns
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
tenant tenant-ns 8 2024-11-11 16:54:30.78810769 +0000 UTC deployed tenant-6.0.4 v6.0.4
Thank you very much for your help!

**Comment by williamsun-hha** [comment]
@harshavardhana, please do not close this.   There is no quota on any of the bucket from Minio console.  Quota status is Disabled.   I created a new bucket with quota disabled as well.  Same issue.

**Comment by harshavardhana** [comment]
> @harshavardhana, please do not close this. There is no quota on any of the bucket from Minio console. Quota status is Disabled. I created a new bucket with quota disabled as well. Same issue.

This is because there is some issue with how the writes happened on the drive etc, there seems to be some setup issue as well, this requires a lot more investigation that we do not provide over community support.

Please upgrade to latest release and let us know if its the same.

**Comment by williamsun-hha** [comment]
@harshavardhana,  I did further test on the cluster.   The cluster does not have any issues.  I can uploaded as many objects as I want from the Minio Console.  This has proved that Minio S3 cluster is function well.    It is appears that S3 service minio has issue.    Can I use the minio console port 9090 as a S3 api port since I am able to upload the S3 objects from the console.   If you can provide a quick fix for this,   Please let provide a document on the upgrade.   we would greatly appreciate it.  
What would be the best route to resolve this issue. Thank you very much!

**Comment by williamsun-hha** [comment]
After further analysis.  On all of the Minios pods (Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)
Filesystem      Size  Used Avail Use% Mounted on
overlay         248G   24G  225G  10% /
tmpfs            64M     0   64M   0% /dev
/dev/sdg        984G  252G  732G  26% /export0
/dev/sdh        984G  252G  732G  26% /export1
/dev/sdf        984G  252G  732G  26% /export2
/dev/sdi        984G  252G  732G  26% /export3
/dev/sdc        984G  252G  732G  26% /export4
/dev/sde        984G  252G  732G  26% /export5
/dev/sdd        984G  252G  732G  26% /export6
/dev/sdb        984G  252G  732G  26% /export7
/dev/root       248G   24G  225G  10% /data
shm              64M     0   64M   0% /dev/shm
tmpfs            27G   12K   27G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
) ( 	1.	Disk Space:
	•	All drives in the cluster (/exportX) have sufficient free space (~732 GiB each).
	•	The reported issue drive path full may be a false alarm or related to metadata or temporary files.
	2.	Error Specificity:
	•	The error mentions .minio.sys/tmp and .minio.sys/buckets/.usage-cache.bin.bkp.
	•	These are internal MinIO files related to bucket metadata or cache.
	3.	Cluster and Pods:
	•	All pods are running and healthy (READY: 2/2, STATUS: Running).) But the issue is Minio-S3 internal drive full (API: SYSTEM.storage(bucket=.minio.sys, object=buckets/.usage-cache.bin.bkp)
Time: 22:29:20 UTC 11/28/2024
DeploymentID: 02401f33-06f7-48ed-badb-bbb2fa8c26f3
Error: drive:/export6/data, srcVolume: .minio.sys/tmp, srcPath: 63523b2a-68dd-412c-b98c-6edb2dd73cc3, dstVolume: .minio.sys:, dstPath: buckets/.usage-cache.bin.bkp - error drive path full (*errors.errorString)
       7: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       6: internal/logger/logonce.go:149:logger.LogOnceIf()
       5: cmd/logging.go:164:cmd.storageLogOnceIf()
       4: cmd/xl-storage.go:2576:cmd.(*xlStorage).RenameData.func1()
       3: cmd/xl-storage.go:2846:cmd.(*xlStorage).RenameData()
       2: cmd/xl-storage-disk-id-check.go:501:cmd.(*xlStorageDiskIDCheck).RenameData.func2()
       1: internal/ioutil/ioutil.go:116:ioutil.WithDeadline[...].func1()
).
