### ISSUE TITLE
mc mv sends delete event notification before file deletion is completed

### ISSUE THREAD

**Issue by xueyu-xxxx** [minio/minio#20701]
#### **Expected Behavior**:  
Delete event notifications should only be sent after the source file has been completely deleted by the `mc mv` operation.

---

#### **Current Behavior**:  
When using the `mc mv` command with delete event notifications enabled on a MinIO bucket, the delete event notification is sent **before** the file deletion process is completed. This causes inconsistencies, especially when workflows rely on accurate delete event timing.

---

#### **Steps to Reproduce (for bugs)**:  

1. Enable delete event notifications on a MinIO bucket.  
   Example configuration:  
   ```json
   {
    "EventName": "s3:ObjectRemoved:Delete",
    "Key": "test/storage_life_14/7CDDE9011FD221732775851_1/54dcef68af8a4bcdb83a663713cdc94a.jpg",
    "Records": [
        {
            "eventVersion": "2.0",
            "eventSource": "minio:s3",
            "awsRegion": "",
            "eventTime": "2024-11-28T06:41:59.682Z",
            "eventName": "s3:ObjectRemoved:Delete",
            "userIdentity": {
                "principalId": "4mX5VIdxRBZqOTRgA5y1"
            },
            "requestParameters": {
                "principalId": "4mX5VIdxRBZqOTRgA5y1",
                "region": "",
                "sourceIPAddress": "172.16.30.105"
            },
            "responseElements": {
                "x-amz-id-2": "dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8",
                "x-amz-request-id": "180C0EB33ECF1806",
                "x-minio-deployment-id": "09c6a6dd-7844-4c40-bdfc-60e4d8ea6960",
                "x-minio-origin-endpoint": "https://172.16.30.105:9000/"
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "Config",
                "bucket": {
                    "name": "test",
                    "ownerIdentity": {
                        "principalId": "4mX5VIdxRBZqOTRgA5y1"
                    },
                    "arn": "arn:aws:s3:::test"
                },
                "object": {
                    "key": "storage_life_14%2F7CDDE9011FD221732775851_1%2F54dcef68af8a4bcdb83a663713cdc94a.jpg",
                    "sequencer": "180C0EB340F03A58"
                }
            },
            "source": {
                "host": "172.16.30.105",
                "port": "",
                "userAgent": "MinIO (linux; arm64) minio-go/v7.0.75 mc/RELEASE.2024-08-17T11-33-50Z"
            }
        }
    ]
}
   ```  

2. Use the `mc mv` command to move a large file from one location to another within the bucket:  
   ```bash
   mc mv minio1/test/source_file.jpg minio2/test/destination_file.jpg
   ```

3. Monitor delete event notifications using the configured notification service (e.g., webhook, SQS).

4. Compare the timestamps of the delete event notification and the completion time of the `mc mv` operation.  

---

#### **Logs & Evidence**:  

**`mc mv` Log**:  
```text
Nov 28 06:41:59 minio-cluster-01 mc-mv.sh[2885436]: `minio1/test/storage_life_14/7CDDE9011FD221732775851_1/54dcef68af8a4bcdb83a663713cdc94a.jpg` -> `minio2/test/storage_life_14/7CDDE9011FD221732775851_1/54dcef68af8a4bcdb83a663713cdc94a.jpg`
```

**Delete Event Notification Log**:  
```json
{
  "EventName": "s3:ObjectRemoved:Delete",
  "Key": "test/storage_life_14/7CDDE9011FD221732775851_1/54dcef68af8a4bcdb83a663713cdc94a.jpg",
  "eventTime": "2024-11-28T06:39:56.711Z"
}
```

**Comparison**:  
- `mc mv` completion time: **06:41:59**  
- Delete event notification time: **06:39:56**  

The delete notification is triggered approximately 2 minutes **before** the `mc mv` operation completes.

---

#### **Possible Solution**:  
Adjust the implementation of `mc mv` or the notification mechanism to ensure that delete event notifications are sent **only after** the source file is fully deleted.

---

#### **Context**:  
This issue impacts workflows that rely on delete event notifications to trigger downstream actions. Notifications sent prematurely can result in invalid or inconsistent states.

---

#### **Regression**:  
- **Yes/No**: Unknown  
- If regression, please specify the affected version or commit:  

---

#### **Your Environment**:  

- **MinIO Version**:  
  ```text
  MinIO (linux; arm64) minio-go/v7.0.75 mc/RELEASE.2024-08-17T11-33-50Z
  ```  

- **mc Version**:  
  ```text
  mc version RELEASE.2024-08-17T11-33-50Z (commit-id=2c94b8d03979ed96a6379ecabc3435b271398efc)
  Runtime: go1.22.6 linux/arm64
  Copyright (c) 2015-2024 MinIO, Inc.
  ```

- **Server setup and configuration**:  
  MinIO Cluster (distributed)  

- **Operating System and version (`uname -a`)**:  
  ```text
  uname -a
  Linux minio-cluster-01 6.5.0-1026-oracle #26~22.04.1-Ubuntu SMP Mon Jun 24 14:22:18 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
  ```

---

#### **Additional Notes**:  
This issue is more likely to occur in scenarios with slow network conditions or large files, where the time between initiating and completing a deletion is significant.

**Comment by marktheunissen** [comment]
Hi @xueyu-xxxx, please repeat your test while running `mc admin trace ALIAS`. This will show you exactly when the call to `s3.DeleteMultipleObjects` happens. For example:

```
2024-11-29T15:51:05.624 [200 OK] s3.CopyObjectPart 127.0.0.1:9000/marktest/district-5.mkv?partNumber=16&uploadId=MTY5OGFhYjctN2ViYS00NWE5LWFjNjQtNmRkZDU1MGMyZmYwLjBmMmJlNTI4LTgyMDgtNDNjNy1iZDdlLWJmMDIwNTQwZWFjMXgxNzMyODU1ODU1NjczODY0MDAw  127.0.0.1        665.154ms    ⇣  665.145ms  ↑ 135 B ↓ 228 B
2024-11-29T15:51:06.290 [200 OK] s3.CopyObjectPart 127.0.0.1:9000/marktest/district-5.mkv?partNumber=17&uploadId=MTY5OGFhYjctN2ViYS00NWE5LWFjNjQtNmRkZDU1MGMyZmYwLjBmMmJlNTI4LTgyMDgtNDNjNy1iZDdlLWJmMDIwNTQwZWFjMXgxNzMyODU1ODU1NjczODY0MDAw  127.0.0.1        663.94ms     ⇣  663.928ms  ↑ 135 B ↓ 228 B
2024-11-29T15:51:06.954 [200 OK] s3.CopyObjectPart 127.0.0.1:9000/marktest/district-5.mkv?partNumber=18&uploadId=MTY5OGFhYjctN2ViYS00NWE5LWFjNjQtNmRkZDU1MGMyZmYwLjBmMmJlNTI4LTgyMDgtNDNjNy1iZDdlLWJmMDIwNTQwZWFjMXgxNzMyODU1ODU1NjczODY0MDAw  127.0.0.1        663.361ms    ⇣  663.349ms  ↑ 135 B ↓ 228 B
2024-11-29T15:51:07.618 [200 OK] s3.CompleteMultipartUpload 127.0.0.1:9000/marktest/district-5.mkv?uploadId=MTY5OGFhYjctN2ViYS00NWE5LWFjNjQtNmRkZDU1MGMyZmYwLjBmMmJlNTI4LTgyMDgtNDNjNy1iZDdlLWJmMDIwNTQwZWFjMXgxNzMyODU1ODU1NjczODY0MDAw  127.0.0.1        5.423ms      ⇣  5.385ms    ↑ 1.9 KiB ↓ 324 B
2024-11-29T15:51:07.624 [200 OK] s3.DeleteMultipleObjects 127.0.0.1:9000/marktest/?delete=  127.0.0.1        550µs       ⇣  499µs     ↑ 184 B ↓ 160 B
```

You can see in the above log output, it has copied the parts, then finally s3.DeleteMultipleObjects is called at `2024-11-29T15:51:07.624` which on my machine, triggers an event with eventTime `2024-11-29T15:51:07.625` so this seems to be exactly correct.

If you see something different, please paste the logs from `mc admin trace` and the full corresponding event that you see. Describe in detail any processing happening on the event. 

Some things to consider:
- Is the clock on your local machine, or the machine running `mc` synchronized to the same time as the clock on the server? 
- You say you're copying from one bucket to another, but also you say `mc mv minio1/test/source_file.jpg minio2/test/destination_file.jpg` which indicates two different minio instances (minio1 and minio2). It can't be the same bucket if it's different clusters, so there is an error here in the command. Clarify please.

Update to the latest versions of MinIO and mc and repeat the test, we don't support anything older than the latest version in Github issues.
