### ISSUE TITLE
The more LDAP groups a user has - the slower the console and mc client are

### ISSUE THREAD

**Issue by mg-aik** [minio/minio#20717]
The more LDAP groups a user has, the longer time it takes to login and browse buckets using the Console. Mc client is also slower to list buckets.

We see the performance is clearly degraded when a user has more than 20 groups and it gets even worse for every single group we add.

## Expected Behavior
We expect it to be fast to use Minio console or client (mc) even with many groups.

## Current Behavior
Users with less 20 groups everything works as expected. If the user has 60 groups it takes ~30 seconds. If a user has more than 100 groups, it takes more than two minutes or the request times out. When removing groups from the user things are speeding up again.

## Possible Solution
No.

## Steps to Reproduce (for bugs)
1. Configure MinIO for Authentication using Active Directory / LDAP
2. Create 100 buckets
3. Create 100 LDAP groups
4. Create 100 policies binding each bucket to a LDAP group
5. Create LDAP user
6. Add LDAP user to these 100 LDAP groups
7. Login to MinIO Console

## Context
Our security framework is built around LDAP so each user must have the correct LDAP group to be able to access a bucket.

## Regression

Yes. This worked fine with RELEASE.2023-09-04T19-57-37Z, but not after upgrading to RELEASE.2024-11-07T00-52-20Z. During the upgrade we followed this procedure: https://github.com/minio/minio/releases/tag/RELEASE.2024-04-18T19-09-19Z

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration:
```
# minIO volumes
MINIO_VOLUMES="http://a{0001...0004}.xxx.net/data/disk{1...8}/minio/data http://a{0005...0008}.xxx.net/data/disk{1...8}/minio/data http://a{0009...0012}.xxx.net/data/disk{1...8}/minio/data http://a{0013...0016}.xxx.net/data/disk{1...8}/minio/data"

# minIO CLI options
MINIO_OPTS="--address :9000 --console-address :9090"

# Access and secret key
MINIO_ROOT_USER=xxx
MINIO_ROOT_PASSWORD=xxx

# LDAP config 
MINIO_IDENTITY_LDAP_SERVER_ADDR=xxx.se:636
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=xxx@xxx
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=xxx
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=dc=xxx,dc=xxx,dc=xx
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(sAMAccountName=%s)
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectClass=group)(member=%d))
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN=ou=xxx,dc=xxx,dc=xxx,dc=xx

MINIO_AUDIT_WEBHOOK_ENABLE_RANGER=on
MINIO_AUDIT_WEBHOOK_ENDPOINT_RANGER=https://minio-audit.xxx.net/webhook
MINIO_AUDIT_WEBHOOK_AUTH_TOKEN_RANGER=xxx
MINIO_AUDIT_WEBHOOK_QUEUE_DIR_RANGER=/data/shared/minio-audit-queue
MINIO_AUDIT_WEBHOOK_BATCH_SIZE_RANGER=400
```
* Operating System and version (`uname -a`): `Linux xxx.net 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

* Operating System and version (`cat /etc/os-release `):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Comment by harshavardhana** [comment]
@mg-aik how is your group policy mapping handled? and how are your credentials generated? can you provide some test programs that we can reproduce this with?

**Comment by mg-aik** [comment]
**how is your group policy mapping handled?**
Each bucket has two polices (r/w + r). We assign each policy to an LDAP group.

**and how are your credentials generated?**
Users login with their LDAP credentials in the console. Once logged in they can generate access/secret key and use mc client.

**can you provide some test programs that we can reproduce this with?**
No. We experience this problem in environments with large number of users, groups and buckets.

**Comment by harshavardhana** [comment]
> Each bucket has two polices (r/w + r). We assign each policy to an LDAP group.

what if the policy is directly attached to the user-dn? @mg-aik does that change anything?

**Comment by harshavardhana** [comment]
I am unable to reproduce this with 100 groups @mg-aik

**Comment by harshavardhana** [comment]
spoke too early, its reproducible

**Comment by mg-aik** [comment]
> what if the policy is directly attached to the user-dn

In addition to the policies attached to group-dns, each user has one policy attached to the user-dn for its "home-bucket".

**Comment by mg-aik** [comment]
Hi, and thanks for your fix. However, it does not solve our problem. It still takes very long time to login to the console or list buckets, `mc ls myminio`, after upgrading to latest version.

**Comment by harshavardhana** [comment]
> Hi, and thanks for your fix. However, it does not solve our problem. It still takes very long time to login to the console or list buckets, `mc ls myminio`, after upgrading to latest version.

It's only fixed in AiStor, it is not supported yet in OSS version.
