### ISSUE TITLE
Accessing Object Size During Delete Request

### ISSUE THREAD

**Issue by mrjavadseydi** [minio/minio#20716]
Sometimes objects or folders need to be deleted, and knowing the size of an object (or multiple objects) is important to calculate whether in the audit or track usage of data. At this time, there is no way of getting the object size at the time of delete request, which would facilitate better management of storage as well as resource tracking.

For instance, large numbers of files being deleted mean that understanding the size of the objects helps make more informed decisions for storage optimization, backup strategies and billing considerations.

I would like to be able to send a delete request and be able to get the size for that object (or folder). Ideally, this would be done via reply headers or part of the metadata associated with the object so that i can find it out before the object deletion process is initiated.

One of the things that can be done is include a header like `X-Object-Size` in the delete response, which would return the size of the object in bytes. That way, the user will be able to capture size pre-deletion without having first to fetch it separately.

This is in contrast to querying the object metadata or a separate HEAD request prior to delete command. It all just throws everything into getting that extra step added into the process. Ideally, if it were sized with delete, it would smooth out efficiency and workflow.

To be able to provide an object size before deletion will dramatically help in managing storage usage and optimizing workflows. This new feature will give the benifit

**Comment by harshavardhana** [comment]
Random features like this that extend AWS S3 are not going to be entertained unfortunately.

You manage the storage usage separately via Prometheus and set alerts for cleanup .
