### ISSUE TITLE
Certificates used for Kafka notifications not reloaded after rotation

### ISSUE THREAD

**Issue by RyyzQ** [minio/minio#20722]
We have MinIO running from a Helm chart (not the operator) in a K8s cluster. We have setup Kafka notifications using mTLS; TLS is enabled and both the "MINIO_NOTIFY_KAFKA_CLIENT_TLS_CERT_<SERVICE>" and "MINIO_NOTIFY_KAFKA_CLIENT_TLS_KEY_<SERVICE>" variables are provided and work correctly. We also have "MINIO_NOTIFY_KAFKA_TLS_CLIENT_AUTH" set to 4. 
These variables point to a K8s secret mounted in a volumeMount. The volumeMount points to a specific location, something similar to "/etc/minio/certs/<SERVICE>/private.key", but also other locations seem to result in the same behavior. It does not seem to matter whether we point the env. variables to the location mentioned, or to the path they symlink to.

As long as the certificates are valid, everything is fine and notifications are sent correctly. When certificates are rotated and the old ones expire, certificate errors start to arise.

## Expected Behavior
When certificates are rotated and the new certificates are mounted, they should be loaded in and used to send event notifications to Kafka.

## Current Behavior
When these certificates are rotated (and therefore the certs that are loaded in memory expire), we eventually start seeing "remote error: tls: unknown certificate" errors and the notifications stop working.

Running `mc admin service restart <alias>` fixes it, however this seems undesirable to do for every rotation for every cert. We've also tried sending SIGHUP to MinIO, but this doesn't seem to do anything, or maybe more specifically: the Kafka event destination stays marked as "offline" and notifications aren't sent. Whether certs are reloaded I don't know.

## Possible Solution
-

## Steps to Reproduce (for bugs)

1. Setup Kafka event notifications using mTLS.
2. Wait for certificates to expire.
3. Put a file into a bucket that should send event notifications.
4. Observe errors.

## Context
We want to act upon files being uploaded to certain buckets, for which Kafka notifications make the most sense in our usecase. For security reasons we use shortlived certificates, so proper rotations are an important part of our setup.

## Regression
-

## Your Environment
* Version used (`minio --version`): RELEASE.2024-10-02T17-50-41Z
* Server setup and configuration: Kubernetes, helm chart (not the operator)
* Operating System and version (`uname -a`): 22.04.1-Ubuntu

**Comment by harshavardhana** [comment]
mc admin service restart is the correct way for now, it is similar in nature to sighup a soft restart.

**Comment by RyyzQ** [comment]
Should anyone find this in the future: our solution was to implement an application that watches the Kubernetes events for certificate renewals/rotations and based on that triggers a rolling restart for minio by applying a "restartedAt" annotation.

Restarting through mc admin also works, but that was more difficult to automate in our setup.
