### ISSUE TITLE
Follow `.` characters in the bucket names as allowed in Amazon's spec

### ISSUE THREAD

**Issue by JonasDoe** [minio/minio#20720]
**Is your feature request related to a problem? Please describe.**
I'ld like to utilize `.` characters in my bucket names, b/c only hyphens lead to confusion in my use case. Amazon's S3 [spec](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) allows them:
> - Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).

**Describe the solution you'd like**
I'ld like dot characters to be allowed.

**Describe alternatives you've considered**
Right now, I'm using hyphens to seperate pieces of information.

**Additional context**
I'm using the `minio-go v7.0.81` library, so it's possible dots are only forbidden there.

**Comment by harshavardhana** [comment]
This has been supported since day 1

```
mc mb play/test.bucket
Bucket created successfully `play/test.bucket`.
```

You must be specifying unsupported scenarios such as `.` in the beginning and `.` at the end those are not supported. 

```
mc mb play/.test.bucket
mc: <ERROR> Unable to make bucket `play/.test.bucket`. Bucket name contains invalid characters
```

```
mc mb play/test.bucket.
mc: <ERROR> Unable to make bucket `play/test.bucket.`. Bucket name contains invalid characters
```

**Comment by JonasDoe** [comment]
Oh, my bad. Actually, my mistake was another one: a upper case letter had sneaked in. Sorry for the hassle!
