### ISSUE TITLE
Minio restricts filtering the storage of multiple MIME objects

### ISSUE THREAD

**Issue by juvenrui** [minio/minio#20726]
For example, .txt, .jpg and .pdf, the policy rules are as follows:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::*/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:content-type": ["text/plain", "image/jpeg", "application/pdf"]
                }
            }
        }
    ]
}
```

But hint: invalid condition key 's3:content-type'

Please tell me, how to solve the Minio restriction to filter the storage of multiple MIME objects? 

Version used (minio --version):  RELEASE.2024-11-07T00-52-20Z

Thanks!

**Comment by harshavardhana** [comment]
> ```json
>                     "s3:content-type": ["text/plain", "image/jpeg", "application/pdf"]
> ```

there is no AWS S3 condition key called `s3:content-type` - you can use tags instead

**Comment by juvenrui** [comment]
> > ```json
> >                     "s3:content-type": ["text/plain", "image/jpeg", "application/pdf"]
> > ```
> 
> there is no AWS S3 condition key called `s3:content-type` - you can use tags instead

OK, thank you.
