### ISSUE TITLE
Please add a setting to block the upload function on port 9000 for the admin account.

### ISSUE THREAD

**Issue by BBUBBA** [minio/minio#20737]
- web port = 9000
- console port = 9001 ( blocked Firewall )

I don't want to use the upload function, but if the admin account is hacked, I won't be able to block uploads on port 9000

Even if I set a policy for the admin account, I cannot block uploads for the admin account.

I want to use only the access key and secret key for each bucket, but if the admin account is hacked, I won't be able to block uploads for all buckets.

In Ceph and S3, it is possible to block uploads from the admin account.

I would prefer that the admin account does not have the role of uploading via access key and secret key, but only has the ability to upload through the web console. Also, I would like each bucket to be able to use only newly generated access key and secret key.

Thank you !!

**Comment by marktheunissen** [comment]
Hi @BBUBBA, set MINIO_API_ROOT_ACCESS=off to disable root user entirely.

https://min.io/docs/minio/linux/reference/minio-server/settings/root-credentials.html#envvar.MINIO_API_ROOT_ACCESS

We will not make a feature that disables root user access for the API but then somehow allows it for the console, just create the users you need after blocking root as above.

> S3, it is possible to block uploads from the admin account.

If you can provide links to documented behavior in AWS S3, as well as steps that show that MinIO and S3 behave differently, please open an issue with exact steps to reproduce and conclusive evidence that MinIO does not correctly implement the functionality.
