### ISSUE TITLE
Local users are unable to authenticate if LDAP is enabled

### ISSUE THREAD

**Issue by MonolithProjects** [minio/minio#20746]
## NOTE

I am using both Local and LDAP user in the Minio Cluster. Local users can login to the Console, but can not access the data in the buckets (even using `mc` cli). Once LDAP is disabled, Local Local users can access the data again.

## Expected Behavior

Both Local and LDAP users can access the data based on their policies.

## Current Behavior

Local users can not access the data when LDAP is enabled

## Steps to Reproduce (for bugs)

1. Have both Local and LDAP users
2. Update to RELEASE.2024-11-07T00-52-20Z
3. Try to access the data with Local user

## Context

Minio Cluster was updated from RELEASE.2024-06-29T01-20-47Z to RELEASE.2024-11-07T00-52-20Z.

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
Runtime: go1.23.3 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.

* Server setup and configuration: 8 node cluster
* Operating System and version (`uname -a`): 
```Linux ops-object03.embl.de 4.18.0-513.24.1.el8_9.x86_64 #1 SMP Mon Apr 8 11:23:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by harshavardhana** [comment]
This feature is available in our AiStor releases https://min.io/download?view=aistor-custom

**Comment by MonolithProjects** [comment]
@harshavardhana so the feature was removed from Minio Server? I did not have this problem with older Minio release
