### ISSUE TITLE
Option to allow insecure connection to KES/KMS (self-signed CA)

### ISSUE THREAD

**Issue by avoidik** [minio/minio#20752]
**Is your feature request related to a problem? Please describe.**

I am trying to connect to a KES server HTTPS endpoint which has TLS configured with self-signed CA.

- https://min.io/docs/kes/tutorials/getting-started/
- https://min.io/docs/kes/tutorials/filesystem-keystore/

**Describe the solution you'd like**

I would like to be able to connect to a secure-by-default KES over the insecure connection with self-signed CA.

**Describe alternatives you've considered**

- extract CA cert, supply it over `MINIO_KMS_KES_CAPATH`
- sslip.io

**Additional context**

The kes cli app has `--insecure` flag to set `tls.Config{InsecureSkipVerify: true}` here:

https://github.com/minio/kes/blob/v0.23.0/cmd/kes/main.go#L158

However, there is no similar option on the minio side. Neither of TLS structs allows you to set that.

https://github.com/minio/minio/blob/RELEASE.2024-11-07T00-52-20Z/internal/kms/config.go#L127

https://github.com/minio/minio/blob/RELEASE.2024-11-07T00-52-20Z/internal/kms/config.go#L158

**Comment by avoidik** [comment]
```
kes-1            | time=2024-12-11T14:39:14.848Z level=INFO msg="http: TLS handshake error from 172.18.0.3:35252: remote error: tls: bad certificate"
minio-1          | FATAL Failed to connect to KMS: failed to generate data key with KMS key: Post "https://kes:7373/v1/key/generate/minio-sse-s3-key": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**Comment by klauspost** [comment]
Allowing unverified certs just seems like a security foot-gun. But leaving to Andreas.

**Comment by avoidik** [comment]
@klauspost begging for a feature parity here

**Comment by marktheunissen** [comment]
> extract CA cert, supply it over MINIO_KMS_KES_CAPATH

Is there a reason that this doesn't work for you? 

A self-signed cert is its own CA, so just provide the cert.

**Comment by avoidik** [comment]
I can confirm this works fine in normal situations, like when I supply a CA certificate through an environment variable. However, when using kes's self-signed CA (created using the command `kes identity new --ip "127.0.0.1" localhost`), there's no actual certificate file available. That's why I need to first get the CA certificate by running `openssl s_connect 127.0.0.1:7373`. This becomes particularly challenging in a containerized environment.

While I understand I could create my own self-signed CA beforehand, I think there should be a simpler option for less critical uses or testing purposes, especially when kes is only being used as a KMS backend for minio. This would be a reasonable trade-off instead of having to maintain a CA.

**Comment by marktheunissen** [comment]
> when using kes's self-signed CA (created using the command kes identity new --ip "127.0.0.1" localhost), there's no actual certificate file available. 

In the docs you linked to above https://min.io/docs/kes/tutorials/getting-started/, the command provided is `kes identity new --ip "127.0.0.1" --key "private.key" --cert "public.crt" localhost` which generates a cert and then makes the file `public.crt` available for use.

I think you've maybe just missed that?

**Comment by avoidik** [comment]
thank you @marktheunissen, you are absolutely right 👍

```bash
kes identity new --ip '127.0.0.1' --key private.key --cert public.crt localhost
export MINIO_KMS_KES_CAPATH="public.crt"
```
