### ISSUE TITLE
Check for available inodes in addition of free space disk

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2075]
```
$ df -h /dev/nvme0n1p8
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p8   24G   17G  6.3G  73% /mnt/p8
$ df -i /dev/nvme0n1p8                                                             
Filesystem      Inodes   IUsed IFree IUse% Mounted on
/dev/nvme0n1p8 1572864 1572864     0  100% /mnt/p8
```

This partition is formatted by mkfs with default parameters, minio returns error 500 in this case.

**Comment by harshavardhana** [comment]
> This partition is formatted by mkfs with default parameters, minio returns error 500 in this case.

:+1:

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/issues/2076 - this will be fixed..  once this issue is fixed.
