### ISSUE TITLE
XL: cannot remove some dirs

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2076]
```
$ mc rm --force --recursive myminio/testbucket/
Removed ‘myminio/testbucket/1003’.
Removed ‘myminio/testbucket/1004’.
Removed ‘myminio/testbucket/1005’.
Removed ‘myminio/testbucket/1006’.
Removed ‘myminio/testbucket/1007’.
Removed ‘myminio/testbucket/1008’.
Removed ‘myminio/testbucket/1009’.
Removed ‘myminio/testbucket/1010’.
Removed ‘myminio/testbucket/1011’.
$ mc ls myminio/testbucket/
[2016-07-03 17:48:48 CET]     0B 1003/
[2016-07-03 17:48:48 CET]     0B 1004/
[2016-07-03 17:48:48 CET]     0B 1005/
[2016-07-03 17:48:48 CET]     0B 1006/
[2016-07-03 17:48:48 CET]     0B 1007/
[2016-07-03 17:48:48 CET]     0B 1008/
[2016-07-03 17:48:48 CET]     0B 1009/
[2016-07-03 17:48:48 CET]     0B 1010/
[2016-07-03 17:48:48 CET]     0B 1011/
```

The attached file is the archive of the exported dirs
[fs.cannot.remove.tar.gz](https://github.com/minio/minio/files/345180/fs.cannot.remove.tar.gz)

**Comment by harshavardhana** [comment]
Was this inconsistency created? by deleting files from backend ?

**Comment by vadmeste** [comment]
I copied a dir to myminio/testbucket/1, myminio/testbucket/2 and so on until the disk became full, minio returned 500, then I deleted some files, copied again.. Finally I decided to remove all files. All of this using mc, so no I didn't touch the backend manually.

**Comment by harshavardhana** [comment]
> Was this inconsistency created? by deleting files from backend ?

Can you post following details 
- Approach/script with which the files were created, parallel etc. Average size of the file.
- Were any disks deleted during this copy?

**Comment by harshavardhana** [comment]
> I copied a dir to myminio/testbucket/1, myminio/testbucket/2 and so on until the disk became full, minio returned 500, then I deleted some files, copied again.. Finally I decided to remove all files. All of this using mc, so no I didn't touch the backend manually.

Looks like some became inconsistent after the disk was full, is this related to the inode problem? - that we ran out of inode before we ran out of disk space?

**Comment by vadmeste** [comment]
> Looks like some became inconsistent after the disk was full, is this related to the inode problem? - that we ran out of inode before we ran out of disk space?

yes, I encountered this when the disk ran out of inodes.

**Comment by harshavardhana** [comment]
> yes, I encountered this when the disk ran out of inodes.

Yeah we need to fix that, no wonder you are not able to delete.  REF #2075

**Comment by harshavardhana** [comment]
This should be fixed already in master to handle a case where we run out of inodes, since we wouldn't be reaching a situation as the i/o would have stopped at the 5% threshold.
