### ISSUE TITLE
Lifecycle not work 

### ISSUE THREAD

**Issue by chenpei2** [minio/minio#20779]
## NOTE
I added a lifecycle transition rule to a bucket to migrate data to a remote tier adter one day, but the data has still not been migrated after 2 days.The remote tier is another minio.

## Expected Behavior

The data in the bucket should be moved to the remote tier.

## Current Behavior

The data is still in the current minio bucket.

## Your Environment

* Version used (`minio --version`):
docker image version: 2024.5.10-debian-12-r2, running in k8s.

**Comment by harshavardhana** [comment]
>   docker image version: 2024.5.10-debian-12-r2, running in k8s.

Report issues with latest release
