### ISSUE TITLE
Writing to disk every 10 seconds whilst idle

### ISSUE THREAD

**Issue by Bilge** [minio/minio#20777]
I have minio installed on a home NAS, which used to put disks into hibernation for most of the day. Since installing minio, it writes to disk every 10 seconds all day long.

## Expected Behavior
When not in use, there should be no disk access.

## Current Behavior
minio writes to disk compulsively even when there is nothing to do.

## Steps to Reproduce (for bugs)

1. Install minio via Docker.
2. Listen to hard drive ticking every 10 seconds and observe disk access via `htop`.

## Context
Burning power and disk longevity.

## Regression
Never used any other version.

## Your Environment

* Version: RELEASE.2024-10-29T16-01-48Z (c4239ced225b9fead5f6b44e3665c5ccd7eacc89)
* Server setup and configuration: ???
* Operating System and version (`uname -a`): Linux NAS 4.4.302+ #72806 SMP Thu Sep 5 13:44:44 CST 2024 x86_64 GNU/Linux synology_geminilake_423+

**Comment by klauspost** [comment]
Yes, MinIO will keep working even when idle. This is by design.

**Comment by Bilge** [comment]
What design is that, exactly? What could it possibly need to keep writing for?

**Comment by harshavardhana** [comment]
Using the following ENV, you can disable health checks for your drives.

```export _MINIO_DRIVE_ACTIVE_MONITORING=off ```

MinIO performs health checks on the drives by default to proactively identify issues like hung drives and I/O problems. This is by design.

Since your use case is specialized and not typically required, you can use the environment mentioned above.

**Comment by Bilge** [comment]
> Using the following ENV, you can disable health checks for your drives.
> 
> `export _MINIO_DRIVE_ACTIVE_MONITORING=off `
> 
Thanks. Whilst that does appear to have quieted usage a bit, it is still non-zero.
