### ISSUE TITLE
Menu "Site Replication" and "Tiering" are absent in WEB console RELEASE.2024-12-13T22-19-12Z

### ISSUE THREAD

**Issue by almorr** [minio/minio#20773]
Console menu "Site Replication" (console_UTL/settings/site-replication) and "Tiering" (console_UTL/settings/tiers) are  absent in release RELEASE.2024-12-13T22-19-12Z

# Expected Behavior
Cann't access this menu from WEB console

## Current Behavior
Menu not shown, trying to modify URL to /settings/site-replication redirect to /browser

## Steps to Reproduce (for bugs)

Upgrade to release RELEASE.2024-12-13T22-19-12Z from RELEASE.2024-09-13T20-26-02Z

## Regression
 Is this issue a regression?
 Yes

Release https://github.com/minio/minio/releases/tag/RELEASE.2024-12-13T22-19-12Z

## Your Environment

* Version used (`minio --version`):
*minio version RELEASE.2024-12-13T22-19-12Z (commit-id=68b004a48f418ed9c4363b9faaf61a90d2f6f502)
Runtime: go1.23.4 linux/amd64

* Server setup and configuration:
* Operating System and version (`uname -a`):
* Linux 4.18.0-553.32.1.el8_10.x86_64 #1 SMP Mon Dec 2 06:32:20 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marktheunissen** [comment]
These are deprecated, here is the PR in console: https://github.com/minio/console/pull/3470

You can use `mc` CLI tool to access this functionality.
