### ISSUE TITLE
No lifecycle option in web bucket admin menu

### ISSUE THREAD

**Issue by Iceberry-qdd** [minio/minio#20780]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
![image](https://github.com/user-attachments/assets/d6a95697-7c06-4950-b6bd-23486e5dd793)

## Current Behavior

![image](https://github.com/user-attachments/assets/c8b6a9b8-1167-4a1f-baa3-7dd50b46bf68)

## Possible Solution

Rollback to version `2023.7.11`

## Steps to Reproduce (for bugs)

1. `docker pull minio/minio:RELEASE.2024-12-18T13-15-44Z`
2. `docker run -p 9000:9000 -p 9001:9001  minio/minio server /data --console-address ":9001"`
3. Open chrome.

## Your Environment

* Version used (`minio --version`):
```bash
sh-5.1# minio -version
minio version RELEASE.2024-12-18T13-15-44Z (commit-id=16f8cf1c52f0a77eeb8f7565aaf7f7df12454583)
Runtime: go1.23.4 linux/amd64
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Copyright: 2015-2024 MinIO, Inc.
```
* Server setup and configuration:
```bash
docker run -p 9000:9000 -p 9001:9001  minio/minio server /data --console-address ":9001"
```
* Operating System and version (`uname -a`):
```bash
sh-5.1# uname -a
Linux 4226dfd34940 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@ramondeklein @cesnietor did we remove lifecycle rules via UI?

**Comment by ramondeklein** [comment]
@harshavardhana See https://github.com/minio/console/pull/3469 and https://github.com/minio/console/pull/3470.

**Comment by harshavardhana** [comment]
Okay, this is expected. @Iceberry-qdd, we have deprecated replication and lifecycle UI. Please use our AiStor products, which provide these UI elements in a consolidated manner.

https://min.io/download?view=aistor-custom

Or use `mc ilm`

**Comment by Iceberry-qdd** [comment]
Thank you, i'll check this change.
