### ISSUE TITLE
Let user configure `diskFillFraction` value

### ISSUE THREAD

**Issue by Neurone** [minio/minio#20790]
**Is your feature request related to a problem? Please describe.**

I just ran into the infamous "_Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed._" error when I've still got 38 GB of free space.

For my use case, I don't care about performance degradation and I know what I'm doing, so having Minio block me just because I'm formally at 99% disk usage is very annoying.

I've seen this issue recurring for a few years now, and many users probably just want to configure the limit themselves.

https://github.com/minio/minio/issues/16185
https://github.com/minio/minio/issues/16534
https://github.com/minio/minio/issues/17596
https://github.com/minio/minio/issues/18639

A simple warning in the log at the beginning about the suggestion to keep `diskFillFraction = 0.99` is enough to educate the users about the suggested value.

**Describe the solution you'd like**

Add a setting (environment variable?) to change the `diskFillFraction` value.

**Describe alternatives you've considered**

Add a setting (environment variable?) to completely disable the minimum free drive threshold check.

**Additional context**

I'm running minio with home and dev environments, I want to be able to tinker with the system as much as I want.

**Comment by harshavardhana** [comment]
You can recompile the source as you see fit @Neurone - we don't want to make this configurable -- we can't have cockpit options on these things. 

> For my use case, I don't care about performance degradation and I know what I'm doing, so having Minio block me just because I'm formally at 99% disk usage is very annoying.

when you have a specific use-case, we don't want to provide options where things willfully become slow or problematic pointing this to be our problem.

**Comment by Neurone** [comment]
> You can recompile the source as you see fit @Neurone

As open source software I can always change and recompile, thanks for the suggestions, I understand that.

The problem is that these are small changes, but if I do it in my own repo, I'll have to do it again every time there's a new release

> we don't want to make this configurable -- we can't have cockpit options on these things.

Why not? It's very easy to externalize parameters, especially in this case where it's just hard coded. There is no downside to having highly configurable software.

And I'm only asking about this parameter, not others.

And not for the sake of it, or just to expose a random parameter, but because this parameter clearly more than others is causing someone problems instead of being useful (which is the reason I assume you put it there in the first place, to be useful to users).

> when you have a specific use-case, we don't want to provide options where things willfully become slow or problematic pointing this to be our problem.

How can that be the case? By making this an option, no one will complain if something goes wrong because of what they changed. Again, the default would be 0.99 anyway, and you just need to provide a warning about changing that parameter, like you do for others.

**Comment by harshavardhana** [comment]
It is a design choice, we are not planning to make it configurable. Thank you for asking for the feature request but we have no plans to make this configurable for the moment.

**Comment by klauspost** [comment]
>  There is no downside to having highly configurable software.

@Neurone That is a big fallacy in software. Options are a liability and not only creates one more thing users must understand, but also something that we must support every time a user decides to make a foot-gun from an option, despite what is documented.

Every option is added with the best reasons and intention, but honestly most aren't solving any real issues. 

I don't know what your motivations are, but this "issue" is solved by setting up proper drive space monitoring and reacting in due time to space limitation. This limit should never, ever be reached by an ops team that does their due diligence. This is a backstop, so at least the server doesn't kill itself, but it doesn't replace proper monitoring.
