### ISSUE TITLE
MINIO_BROWSER_REDIRECT_URL

### ISSUE THREAD

**Issue by zero-wsh** [minio/minio#20794]
**Is your feature request related to a problem? Please describe.**

An error occurs upon starting the docker-compose deployment after setting MINIO-BROWSER-REDIRECT-URL.

ERROR Invalid MINIO_BROWSER_REDIRECT_URL value is environment variable: URL contains unexpected resources, expected URL to be of http(s)://minio.example.com format: https://minio.zdddh.top/minio/ui

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/1f3664e9-9140-4062-9884-8a305ca3685e)
![image](https://github.com/user-attachments/assets/071c86c7-8e56-4ee5-bb98-4b01fa027532)

nginx document config:
https://minio.org.cn/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
![image](https://github.com/user-attachments/assets/d6becc22-5838-4c09-9267-8bd3d3e28c64)

**Comment by harshavardhana** [comment]
What is your MinIO version?

**Comment by zero-wsh** [comment]
> What is your MinIO version?

![image](https://github.com/user-attachments/assets/21f89ec1-4bcd-4c01-927a-7d615f867bc2)

**Comment by harshavardhana** [comment]
Please upgrade. We can't be working on issues from 2yr old releases.
