### ISSUE TITLE
ftp protocol cost too much memory

### ISSUE THREAD

**Issue by alexz0000** [minio/minio#20800]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
I hope that the FTP protocol, like the MinIO console, will not consume too much additional memory.

## Current Behavior

I am using MinIO and have enabled support for the FTP protocol. However, when I upload files through an FTP client, I notice that it consumes a lot of memory. For instance, uploading a 1KB file can consume up to several GB of memory. But when uploading the same file using the MinIO console, there is basically no significant change in memory usage. This phenomenon is particularly noticeable when MinIO is deployed in Kubernetes.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
OS: Centos 7.9
Minio：RELEASE.2024-03-10T02-53-48Z (go1.21.8 X:boringcrypto linux/amd64)

**Comment by alexz0000** [comment]
I monitor the minio via prometheus, you can see the memory cost is 1.75G when uploading serveral files from ftp client. Howerver,      it looks doesn't cost any memory when I upload files from minio console
![image](https://github.com/user-attachments/assets/85947cac-dc7e-4665-ae5c-5f6cc4570de7)

**Comment by harshavardhana** [comment]
what kind of deployment do you have? we expect that you deploy a minimum of 32GiB per node. 1.75GiB is nothing. 

ftp uploads require that they allocate 512MiB * 4 - worth of memory per transfer is that a bit too much to ask?

**Comment by alexz0000** [comment]
Hi, Harshavardhana, thank you for your reply. Below is a graph showing the memory consumption when I uploaded dozens of files using the MinIO Java client. My question is, why is the memory consumption so low when uploading through the MinIO Java client using the S3 protocol, but the memory consumption is so high when uploading through the FTP protocol? My expectation is that the memory consumption when uploading files through the FTP protocol can be as low as that of the S3 protocol.

Due to limited server resources, I hope to achieve our goals with minimal resources.

By the way, you mentioned that "FTP uploads require allocating 512MiB (Megabits) * 4 of memory per transfer". Where can I find this deployment requirement?

Looking forward to your reply. Thanks。

**Comment by alexz0000** [comment]
![img_v3_02i3_e090f707-63e3-4527-9db3-5748d338fa7g](https://github.com/user-attachments/assets/afd207ac-6a05-4905-802c-52fbe6995bd5)

**Comment by harshavardhana** [comment]
This is normal because in S3 API the client knows the file size. 

Ftp protocol never shares the actual file size of the blob being uploaded, so we have to end up assuming big enough memory.

This is expected behavior if you use ftp, if you have provisions to use S3 API then use that which is what we want our users to use. Ftp is legacy and it is meant to be used seldomly.

Do not perpetually use a legacy protocol if you can move to well performant S3 API.

The memory is expected to be a bit higher with ftp, so be mindful of that.
