### ISSUE TITLE
XL: Cache add auto-expiry of entries.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2080]

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix.

**Comment by harshavardhana** [comment]
> Please update timeline for the fix.

Should by done by July 8th

**Comment by harshavardhana** [comment]
https://github.com/harshavardhana/minio/commit/3a263c762467f294aecf02b9ef0e40c13fe3502d - a relevant patch has been submitted
