### ISSUE TITLE
Golang/ioutil: ioutil.ReadAll(req.Body) panic. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2085]
## Expected behaviour

Atleast expected not to panic in this context. 
## Actual behaviour

Panics during  ioutil.ReadAll(req.Body)
## Steps to reproduce the behaviour

Follow the comments here https://github.com/minio/minio/pull/2074
## Minio version

Commit 7747a085a97ee4a700ec4d2fd0c7bfb3c91dd065
## System information

OSX ElCaption.

**Comment by GarimaKapoor** [comment]
Closing it as it is not reproducible. If it comes again we will look at this issue again.
