### ISSUE TITLE
ssl: make sure to properly handle non-SSL requests

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2096]
This requires us to write custom http.Server{} avoiding the Golang default http server TLS handshake message. 

The problem that we have right now is as shown below

```
$ curl -v http://play.minio.io:9000
* Rebuilt URL to: http://play.minio.io:9000/
*   Trying 12.226.201.63...
* Connected to play.minio.io (12.226.201.63) port 9000 (#0)
> GET / HTTP/1.1
> Host: play.minio.io:9000
> User-Agent: curl/7.47.0
> Accept: */*
> 

* Connection #0 to host play.minio.io left intact
```

**Comment by vadmeste** [comment]
@harshavardhana, you mean serving http and https on the same port?

**Comment by harshavardhana** [comment]
> @harshavardhana, you mean serving http and https on the same port?

yes

**Comment by vadmeste** [comment]
First of all, there is a way to do this with nginx, so I wonder if we should keep minio minimal and avoid such things,

But if we want to incorporate this feature:
1. curl http://play.minio.io:9000 still expects a http connection, so first, we need to reply by http redirect to https://play.minio.io:9000 (I am not sure if s3 clients are permitted to follow redirection)
2. There is a solution with a little overhead which can do all of this. The overhead here is an additional function call for each Read() operation on the input socket (we'll add a wrapper to the original Read())

**Comment by harshavardhana** [comment]
> First of all, there is a way to do this with nginx, so I wonder if we should keep minio minimal and avoid such things,
> 
> But if we want to incorporate this feature:
> 
> curl http://play.minio.io:9000 still expects a http connection, so first, we need to reply by http redirect to https://play.minio.io:9000 (I am not sure if s3 clients are permitted to follow redirection)
> 
> There is a solution with a little overhead which can do all of this. The overhead here is an additional function call for each Read() operation on the input socket (we'll add a wrapper to the original Read())

Running a proxy is front is will not be an acceptable solution, the factual problem here is that "http://s3.amazonaws.com" and "https://s3.amazonaws.com" work the same way and we don't. 

In general it shouldn't be forced upon user, even if it is a better message should sent back on the request itself. Currently Golang standard http just returs back a TLS message which is no expected. 

We can explore the possibilities and see how it can be achieved, something similar has been implemented nicely in Caddy project.

**Comment by GarimaKapoor** [comment]
@vadmeste please update the timeline for the fix.

**Comment by vadmeste** [comment]
This is under review. Could be merged today, 24 July

**Comment by harshavardhana** [comment]
Closing already merged..

**Comment by GarimaKapoor** [comment]
@vadmeste what is the status of this issue?
