### ISSUE TITLE
tests: Implement unit tests for tree-walk.go

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2100]
Right now there is exhaustive testcases for listObjects and listMultipartuploads and test case for tree-walk.go is very minimal.

test cases for tree-walk.go should be exhaustive as well.
for ex:
- recursive/nonrecursive
- check for EOF
- check if listing is correctly sorted

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix.
