### ISSUE TITLE
tests: Add unit tests for object cache. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2109]
Currently no tests have been written.

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix.

**Comment by hackintoshrao** [comment]
Its in progress. 8th July.

**Comment by harshavardhana** [comment]
> Its in progress. 8th July.

This is address in a patch already #2115 - please review.

**Comment by harshavardhana** [comment]
Unit tests have been added for object cache.
