### ISSUE TITLE
tests: Need Cleaner and exhaustive tests for functions in xl-v1-object.go

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2110]

**Comment by hackintoshrao** [comment]
- GetObject() test is in progress rest of the existing tests has to be made cleaner and exhaustive.

**Comment by hackintoshrao** [comment]
`TestRepeatPutObjectPart` from `xl-v1-object_test.go` has to be removed from there and made part of [object suite test](https://github.com/minio/minio/blob/master/object_api_suite_test.go) and detailed array of valid/invalid cases for other functions required.

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix.

**Comment by krisis** [comment]
@hackintoshrao could you explain what you mean when you say cleaner test?

**Comment by hackintoshrao** [comment]
- The tests doesn't have comments. 
- One of the test has to be made part of the suite test for object layer, it looks more of a functional test, its good to there. 
- Unit test need to have an array of success and failure cases and validate. 
- other functions from `xl-v1-object.go` (leaving out GetObject) needs test.

**Comment by krisis** [comment]
@hackintoshrao, there is only one test, namely TestRepeatPutObjectPart. IIUC, you think this should be moved into our object-api test suite. Additionally, all functions (and methods) defined in xl-v1-object.go need to be tested with varied set of inputs. Does that make sense?

**Comment by harshavardhana** [comment]
> @hackintoshrao, there is only one test, namely TestRepeatPutObjectPart. IIUC, you think this should be moved into our object-api test suite. Additionally, all functions (and methods) defined in xl-v1-object.go need to be tested with varied set of inputs. Does that make sense?

:+1: we need basically varying inputs and some of these functions would crash, so they should be fixed as well with input validation.

**Comment by krisis** [comment]
This issue, in spirit, aims at improving coverage of code present in `xl-v1-object.go`. Currently, we have tests in files matching `object-api-*.go`. These tests apply to both XL and FS backends. There are functions in `xl-v1-object.go` which are specific to XL. The corresponding unit-tests will be added in `xl-v1-object_test.go`. Following are functions that need to be covered,
- [x] - DeleteObject
- [x] - PutObject (error path)
- [x] - GetObject (error path)

**Comment by GarimaKapoor** [comment]
Please update the timeline for the fix.

**Comment by krisis** [comment]
#2222 is sent for review. I expect it to be merged by today.

**Comment by krisis** [comment]
@harshavardhana this issue was fixed by #2222. Could you close this issue?

**Comment by harshavardhana** [comment]
> @harshavardhana this issue was fixed by #2222. Could you close this issue?

Fixed by #2222
