### ISSUE TITLE
tests: Need unit test and exhasutive coverage for ObjectLayer.GetObject()

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2116]
- Need cases to cover every possible erroneous output. 
- Data integrity has be tested too. 
- Need a separate concurrent test to concurrently fetch and test for data integrity and races.

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix.

**Comment by hackintoshrao** [comment]
This is ready once https://github.com/minio/minio/pull/2133 is merged.
