### ISSUE TITLE
XL/FS: ObjectLayer.GetObject() incorrect behaviour while trying to fetch from an non-existent bucket.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2117]
## Expected behaviour

To error out with `Bucket not exist`
## Actual behaviour
-  FS strangely passes the test while its expected to error, here is the log.  Not sure how does it pass the test on an non-existent bucket. 
  `object-api-getobject_test.go:118: Test 1: SingleNode: Expected to fail with <ERROR> "Bucket not found: abc", but passed instead`
-  XL fails with the following error.
  `object-api-getobject_test.go:123: Test 1: XL: Expected to fail with error "Bucket not found: abc", but instead failed with error "The requested range is not satisfiable" instead`
## Steps to reproduce the behaviour

run the test here https://github.com/hackintoshrao/minio/commit/6ff382bc018177433846a090b4d7675f61716a52
## Minio version

Latest master at this point 169c72cdab14ac0f993161f6ed97e8462eccfb97 . 
- (paste output of `minio version`)
## System information

OSX ElCaptain.

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix.

**Comment by hackintoshrao** [comment]
@krishnasrinivas : Uncomment test  case 6 here https://github.com/minio/minio/blob/master/object-api-getobject_test.go with your patch. That test is validation for the fix.
