### ISSUE TITLE
FS: GetObject: Incorrect behaviour with invalid offset.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2118]
## Expected behaviour

To Fail with `InvalidRange`. XL behaves as expected for this case. 
## Actual behaviour

Test passing. 
## Steps to reproduce the behaviour

Run the test here https://github.com/hackintoshrao/minio/blob/65a80044e4b6e551d903c1e91c9ad2d659c9e475/object-api-getobject_test.go 
## Minio version

Latest master at this point in time 169c72cdab14ac0f993161f6ed97e8462eccfb97 
## System information

OSX ElCaptain.

**Comment by GarimaKapoor** [comment]
Please update timeline for the fix

**Comment by balamurugana** [comment]
To be closed: 07-Jul-2016.
