### ISSUE TITLE
Break the single test function in object_api_suite_test.go into separate unit-tests

### ISSUE THREAD

**Issue by krisis** [minio/minio#2120]

**Comment by krisis** [comment]
In it's current form it is very difficult to understand each test individually. Also, if one of them fails, there isn't an easy way to run the failing test(s) alone.

**Comment by harshavardhana** [comment]
> In it's current form it is very difficult to understand each test individually. Also, if one of them fails, there isn't an easy way to run the failing test(s) alone.

Thanks for opening this @krisis

**Comment by hackintoshrao** [comment]
Yeah, that helps. It just runs as 2 tests now.
