### ISSUE TITLE
ETag does not return in HeadObject response headers

### ISSUE THREAD

**Issue by amelkikh** [minio/minio#2125]
Expected standard http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html

Step by step, I have studied the code.
I do not know the language well enough to write a fix, however, I understand that the metadata is not preserved. In particular, the hash sum, which is necessary for the response header
ETag is present only in PutObject request

https://github.com/minio/minio/blob/master/object-handlers.go#L296
https://github.com/minio/minio/blob/master/api-headers.go#L71

```
...
if objInfo.MD5Sum != "" {
        w.Header().Set("ETag", "\""+objInfo.MD5Sum+"\"")
}
...
```
## Expected behaviour

Sample Request

```
HEAD /my-bucket/my-image.jpg HTTP/1.1
Host: s3.my-local-storage.docker
Date: Wed, 28 Oct 2009 22:32:00 GMT
Authorization: comeAuthCode
```

Expected response

```
HTTP/1.1 200 OK
x-amz-request-id: 318BC8BC143432E5
Date: Wed, 28 Oct 2009 22:32:00 GMT
Last-Modified: Sun, 1 Jan 2006 12:00:00 GMT
ETag: "fba9dede5f27731c9771645a39863328"
Content-Length: 434234
Content-Type: text/plain
Connection: close
Server: my-server
Something: Else
```
## Actual behaviour

Actual Response

```
HTTP/1.1 200 OK
x-amz-request-id: 318BC8BC143432E5
Date: Wed, 28 Oct 2009 22:32:00 GMT
Last-Modified: Sun, 1 Jan 2006 12:00:00 GMT
ETag:
Content-Length: 434234
Content-Type: text/plain
Connection: close
Server: my-server
Something: Else
```
## Steps to reproduce the behaviour

In docker according to instructions https://hub.docker.com/r/minio/minio/
Php 5.6, Yii2 and official aws-sdk-php
https://packagist.org/packages/aws/aws-sdk-php
## Minio version

"DEVELOPMENT.GOGET"
## System information

Platform 
OS: linux | Arch: amd64
Runtime
Version: go1.6.2 | CPUs: 4

**Comment by krishnasrinivas** [comment]
@amelkikh we do not store the ETAG of the object so that we can keep the backend filesystem like a regular browsable directory tree of regular files and directories without any etag related metadata files.

However for the XL erasure coded backend, we store the ETAG in the backend.
You can start minio XL as `minio server /disk1 /disk2 ..../disk16` in which all the objects will be erasure coded, there will be 8 data and 8 parity disks.

**Comment by amelkikh** [comment]
Thank you for the quick response.
Is there any documentation that points to these differences?

**Comment by krishnasrinivas** [comment]
The erasure coded XL documentation is not available in http://docs.minio.io yet
But you can compile minio on the master branch and type `minio server --help`

**Comment by amelkikh** [comment]
Thank you, the question is solved.
