### ISSUE TITLE
I'd like to contribute a recipe for rclone

### ISSUE THREAD

**Issue by ncw** [minio/minio#2126]
I'd like to contribute a recipe for [rclone](http://rclone.org) but I can't figure out which repo to send a pull requst to!  Something like [this one](https://docs.minio.io/docs/s3cmd-with-minio-server).

If it isn't a public repo then I can send instructions!

rclone works reasonably well with minio.  You need to use the `--size-only` flag to avoid using MD5 sums and date stored in the metadata neither of which minio seems to support at the moment.

The config file needs to look something like this...  Setting the region to `us-east-1` is necessary - leaving it blank doesn't work.

```
[minio]
type = s3
env_auth = false
access_key_id = 2W...79
secret_access_key = eq...z3
region = us-east-1
endpoint = http://127.0.0.1:9000
location_constraint = 
server_side_encryption = 
```

Thanks

Nick

**Comment by krishnasrinivas** [comment]
@ncw docs.minio.io is not available on github yet, soon it will be. Can you post the recipe for `rclone` here? we could update our docs site. Thanks.

**Comment by harshavardhana** [comment]
@ncw you can send a PR to https://github.com/minio/cookbook which will be incorporated seamlessly when our https://github.com/minio/doctor project is out. Thanks a lot.

**Comment by koolhead17** [comment]
Welcome @ncw 
We would love to see http://rclone.org/ listed on  https://github.com/minio/awesome-minio as well. 😄

**Comment by ncw** [comment]
Thanks guys - will do!  I'm planning to put a section in rclone docs on working with minio too.

**Comment by koolhead17** [comment]
@ncw that will be fantastic. Thanks again 😄

**Comment by koolhead17** [comment]
hello @ncw let me know if I can be of any help in getting this PR done, would love to get the contents soon. 😄

**Comment by ncw** [comment]
I've sent out a couple of PRs so I'm going to close this issue now :-)

Thanks for a great project - is there a roadmap for adding either Etag support or metadata support? That is something I could help with.

**Comment by harshavardhana** [comment]
> Thanks for a great project - is there a roadmap for adding either Etag support or metadata support? That is something I could help with.

We already do support that with XL backend we are also going to fix it for FS as well - https://github.com/minio/minio/pull/2184 has preliminary work in this regard.
