### ISSUE TITLE
XL: detect if a disk has been unmounted

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2128]
If minio is started as:
`minio server /mnt/disk1 /mnt/disk2 /mnt/disk3...`

`/mnt/disk1 /mnt/disk2 /mnt/disk3...` are mount points for the disks. Now if user does `umount /mnt/disk` we have no way to tell that the disk is not available, we will just see empty `/mnt/disk` and try to initialize it.

**Comment by harshavardhana** [comment]
We can validate by looking at missing format.json

**Comment by krishnasrinivas** [comment]
> We can validate by looking at missing format.json

In that case minio should not init newly mounted disks, because it wont know if it's a new disk or an umounted directory.

**Comment by harshavardhana** [comment]
Init will happen if all of them are fresh. It doesnt have to heal missing format.json which is the problem here. We will just have to see which is acceptable.

**Comment by krishnasrinivas** [comment]
in the meeting we decided to do this:

`minio server /mnt/disk1 /mnt/disk2 /mnt/disk3... --ignore-disks /mnt/disk2:/mnt/disk7`

**Comment by krishnasrinivas** [comment]
> in the meeting we decided to do this:
> 
> minio server /mnt/disk1 /mnt/disk2 /mnt/disk3... --ignore-disks /mnt/disk2:/mnt/disk7

is it possible that across reboots drives can change it's mount point and that's why we have UUIDs?

**Comment by harshavardhana** [comment]
> is it possible that across reboots drives can change it's mount point and that's why we have UUIDs?

Yes that is why we have UUIDs.
