### ISSUE TITLE
Cannot change policy under Minio ?

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2148]
With the upstream mc, pretty sure this was working before.

```
$ mc access readonly myminio/bucket/
mc: <ERROR> Unable to set access permission ‘readonly’ for ‘myminio/bucket/’. Policy nesting conflict has occurred.
```

**Comment by harshavardhana** [comment]
We need to see why this is happening @mkash32 @hackintoshrao did some changes can fill in here.

**Comment by harshavardhana** [comment]
Assigned to you so you can take a look.

**Comment by hackintoshrao** [comment]
@vadmeste : Whats was the previous policy on the bucket.

**Comment by vadmeste** [comment]
@hackintoshrao, this happens even with fresh disks

**Comment by vadmeste** [comment]
The bug disappeared when I removed ~/.mc directory. I have the backup, will investigate further

**Comment by harshavardhana** [comment]
> The bug disappeared when I removed ~/.mc directory. I have the backup, will investigate further

Are you sure you deleted `~/.mc` not `~/.minio` ?

**Comment by vadmeste** [comment]
> Are you sure you delete ~/.mc not ~/.minio ?

I thought that the bug disappeared when I removed ~/.mc directory while mc was just setting the access of myminio/bucket/ in the local fs, so you are right..

Now, it seems that I was confused because I thought that removing disks will also remove policies, however it seems policies are stored under ~/.minio/, also I wasn't really able to understand the meaning of Policy nesting error. Now, I guess it is normal to have this error when running these commands:

```
$ mc access readonly myminio/bucket/test
$ mc access readonly myminio/bucket/

```

Right?

**Comment by mkash32** [comment]
@vadmeste Yup that is the expected behavior :smile:

**Comment by vadmeste** [comment]
@mkash32, I thought there were multiple bugs but all seems to be fine now.. there are only some legitimate confusions for the newcomers

**Comment by harshavardhana** [comment]
> @mkash32, I thought there were multiple bugs but all seems to be fine now.. there are only some legitimate confusions for the newcomers

Closing..
