### ISSUE TITLE
XL/FS: GetObject: Object Layer Load test for 500 concurrent reads. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2151]
Need a mechanism to easily validate data integrity and detect races during highly concurrent reads. 
- Object layer tests. 
- Tests over socket using Test server. 

need to use a test flag `stresstest` or `loadtest` so that these tests have to invoked using the flags.

**Comment by GarimaKapoor** [comment]
We should add this functionality to s3verify or start a new project as s3bench.

**Comment by hackintoshrao** [comment]
There is a need for internal stress test (not of scale 500, but on a smaller) on the object layer API's for easier detection of races with the help of -race flag while running tests.  Will start to work on this week.  But More exhaustive stress tests can be a new project where the load can be easily controlled.

**Comment by harshavardhana** [comment]
> There is a need for internal stress test (not of scale 500, but on a smaller) on the object layer API's for easier detection of races with the help of -race flag while running tests. Will start to work on this week. But More exhaustive stress tests can be a new project where the load can be easily controlled.

How about doing in s3verify which would run an instance of minio which is built with '-race' flag?  why would there be a need for internal stress test and how often are we going to run it?

**Comment by hackintoshrao** [comment]
I want more specific load test than just bombarding the handler of the test server. Like I want to load just the object layer at times for some specific reasons. And the concurrency of 15-20 at times could catch these bugs ( In the past had done that with MakeBucket) , it doesn't need a complicated setup like build the server with -race flag and run one more project, it can be as easy as `go test -loadtest`.

**Comment by harshavardhana** [comment]
ping @hackintoshrao is this still valid?

**Comment by hackintoshrao** [comment]
Getting the unit tests first is the priority, we could close this for now.
