### ISSUE TITLE
fs+xl returns 501 Not Implemented instead of correct responses

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2156]
```
$ mc cp session.go  myminio/test1/passwd/session.go
$ mc ls myminio/test1/passwd/
mc: <ERROR> Unable to initialize target ‘myminio/test1/passwd/’. 501 Not Implemented
$  mc ls myminio/test1/passwd/session.go/
mc: <ERROR> Unable to stat ‘myminio/test1/passwd/session.go/’. 501 Not Implemented
```

The second command is supposed to return a list of objects
The third command doesn't return Requested file not found, also it takes some unusual seconds to perform.

I tested the same cases with mc+s3 and it is working fine.

**Comment by harshavardhana** [comment]
> $ mc ls myminio/test1/passwd/
> mc: <ERROR> Unable to initialize target ‘myminio/test1/passwd/’. 501 Not Implemented
> $  mc ls myminio/test1/passwd/session.go/
> mc: <ERROR> Unable to stat ‘myminio/test1/passwd/session.go/’. 501 Not Implemented

Because we do not support '/' at the end , it must be we are sending this back for some unnecessary errors can you print the whole file structure doing 'mc ls -r ' from bucket level?. The usually long seconds is perhaps because of retry from the client side.

**Comment by harshavardhana** [comment]
Also there is a fix for this here - https://github.com/minio/minio/pull/2144

**Comment by vadmeste** [comment]
$ mc ls -r myminio/test1/
[2016-07-09 20:49:32 CET] 3.4KiB passwd/session.go

**Comment by vadmeste** [comment]
@harshavardhana, please notice that the same commands are tested with the s3 account and they worked without reporting any errors. This lead me to think that probably Minio is not complying to s3 protocol for this specific point.
