### ISSUE TITLE
XL: cleaning files/dirs under ./minio/tmp/ doesn't work as expected

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2171]
1. Upload many incomplete files.  You can use this command:

```
while true; do timeout 1 mc cp 5gb.bin myminio/testbucket/3/${RANDOM}; done
```
1. Ctlr-C after some minutes
2. `mc rm -r --force --incomplete mnyminio/testbucket/`

Now you can find some files still under tmp/. Restarting minio won't remove directories directly stored under .minio/tmp/

**Comment by harshavardhana** [comment]
This issue is closed by #2187
