### ISSUE TITLE
cache: removing objects doesn't free the associated memory from the system memory.

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2174]

**Comment by harshavardhana** [comment]
what you are seeing is the GC reference which cleans itself up,  try setting GOGC=10. 

Additionally are you saying that right after delete the object is still served from cache?

**Comment by harshavardhana** [comment]
You should be able to validate this behavior also programatically inside the pkg/objcache/ itself https://golang.org/pkg/runtime/debug/#SetGCPercent

**Comment by harshavardhana** [comment]
Another thing to validate is - https://golang.org/pkg/runtime/debug/#FreeOSMemory as well.

**Comment by vadmeste** [comment]
> are you saying that right after delete the object is still served from cache?

No, it works as expected.

I was only looking at the memory usage of minio using top, interestingly, memory consumption dropped to the usual values only after many minutes, I imagined gc has shorter periodic cycles

**Comment by harshavardhana** [comment]
> I was only looking at the memory usage of minio using top, interestingly, memory consumption dropped to the usual values only after many minutes, I imagined gc has shorter periodic cycles

GC is the issue here by default its not aggressive enough to our liking, try setting GCPercent during objcache.New() and you can see the aggressive behavior.  Downside of setting GCPercent is that there will be frequent pauses.

**Comment by vadmeste** [comment]
@harshavardhana, this is not a problem by itself.. the garbage collector will do its job when needed.. however I feel that there are already some lags when I run minio and mc in the same machine. minio clearly lags each 200mb approximately  of upload though part size is 5mb and that's for XL and FS. Probably we could use some memory cache like kmem_cache for linux kernel to decrease memory allocs, but we need to make sure of the cause of that lag first

**Comment by krishnasrinivas** [comment]
@vadmeste what do you mean by lag? do you mean the minio process stalls? how did you detect it?

**Comment by vadmeste** [comment]
@krishnasrinivas, https://asciinema.org/a/4cs11wuyfwg16r0wbtstue3o3

btw, it seems it is not gc, I executed minio with these parameters, `GOGC=4000 GODEBUG=gctrace=1 minio server /mnt/p8/fs/export`, gc wasn't consuming resources..

**Comment by vadmeste** [comment]
I really don't know this is a lag or not (it could be just normal).. but at least, as a simple user, I can see that the bandwidth speed calculated by mc decreased greatly over time

**Comment by krishnasrinivas** [comment]
@vadmeste I saw that upload speed decreased from 54 MBps to 47MBps right? I think it's acceptable.
What would be not acceptable is if it continues to go down for larger files. For ex. if it reaches 20MBps when uploading a 100G file then we can check what's going on.

**Comment by harshavardhana** [comment]
> @vadmeste I saw that upload speed decreased from 54 MBps to 47MBps right? I think it's acceptable.
> What would be not acceptable is if it continues to go down for larger files. For ex. if it reaches 20MBps when uploading a 100G file then we can check what's going on.

:+1:

**Comment by GarimaKapoor** [comment]
Until we face the issue, we should leave it to GC to do the job using defaults. Also GOGC can be set by environment variable.
