### ISSUE TITLE
XL/format: Some disks are corrupt i.e missing `format.json` but has bucket/objects

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2182]
Currently we return failure, we need to handle this case by re-populating `format.json` by inspecting the objects.

**Comment by harshavardhana** [comment]
Same case should be handled for a situation where some disks are offline/unavailable but we have quorum.

**Comment by GarimaKapoor** [comment]
@vadmeste please update the timeline for the fix.

**Comment by vadmeste** [comment]
@GarimaKapoor, still discussing..

Question: Creating format.json could fail too.. what would happen in that case?

My opinion: 
I really recommand that we simplify the process, so we will have:
1. a code that reads as much as possible despite errors that it will encounter
2. a code that fix (fsck).

Here, I suggest to load all format.json and compare them.. and try to find the quorum disks that have the same format.json. If successful, minio will continue working normally, the other disks will be marked as damaged and need fix by fsck

**Comment by harshavardhana** [comment]
> Question: Creating format.json could fail too.. what would happen in that case?

You could use `--ignore-disks` to start the server.

**Comment by vadmeste** [comment]
By the way, here sometimes, a disk contains only buckets without objects, so inspection will fail here. I will start to write code then discuss if needed

**Comment by harshavardhana** [comment]
> By the way, here sometimes, a disk contains only buckets without objects, so inspection will fail here. I will start to write code then discuss if needed

When only a bucket is present you can look into '.minio.sys' as well for any entries.
