### ISSUE TITLE
Logging middleware

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2202]
Support logging middleware that dumps the HTTP headers and responses. Useful for debugging.

**Comment by harshavardhana** [comment]
There is accesslog-handlers.go which can be enhanced to suppport this.

**Comment by GarimaKapoor** [comment]
Duplicate with event notification. Event Notification will now support full access logs, which can be enabled pragmatically by CLI or SDK. Dumping HTTP header will overwhelm the logs. For debugging you may just manually add print statement to write to the console.

**Comment by krishnasrinivas** [comment]
@vadmeste has sent a PR https://github.com/minio/minio/pull/4804, re-opening this issue.

> Duplicate with event notification. Event Notification will now support full access logs, which can be enabled pragmatically by CLI or SDK.

Events do not print headers which is crucial for debugging

> For debugging you may just manually add print statement to write to the console.

This decreases the efficiency of dev process, recently we had to give a custom binary to a customer which had HTTP logging enabled. We can fix bugs faster if logging/debugging infra is built into minio by default.

> Dumping HTTP header will overwhelm the logs

HTTP logging should be off by default

**Comment by kannappanr** [comment]
Closing this issue as this feature has been implemented.
