### ISSUE TITLE
XL: GetObject fails when all data disks are available

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2203]
`mc cp /etc/passwd myminio/testbucket/`

remove parity disks:

```
krishna@escape:~$ rm -rf xl-exports/disk{1..6}
krishna@escape:~$ rm -rf xl-exports/disk15
krishna@escape:~$ rm -rf xl-exports/disk16
```

`mc --debug cat myminio/testbucket/passwd` fails with:

```
mc: <DEBUG> HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Wed, 13 Jul 2016 15:35:48 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: CIFO9EDKYY8Q0LJB

116
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/passwd</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

**Comment by vadmeste** [comment]
@krishnasrinivas, I guess this is normal.. you removed 8 disks which is greater than N/2-1.
Also, I guess it doesn't make sense if you remove all parity data because you can't be sure that the read data are intact.

**Comment by krishnasrinivas** [comment]
@vadmeste if you have all the data blocks it is possible to reconstruct. We don't depend on parity for data intact-ness, we use checksum (blake2b right now) that is stored for each part.

for reedsolomon erasure code, read can be done if (for m data and n parity):
1) we have m blocks (all blocks should be data)
or
2) we have m+1 blocks (each block can be data or parity) if even one data block is missing.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
@GarimaKapoor this needs discussion if it should be fixed

**Comment by harshavardhana** [comment]
> for reedsolomon erasure code, read can be done if (for m data and n parity):
> 1) we have m blocks (all blocks should be data)
> or
> 2) we have m+1 blocks (each block can be data or parity) if even one data block is missing.

It is a right thing to be able to still read - the logic which we agreed some time ago when we implemented erasureReadFile() was if we have 'm data blocks' - all are data and it is equal to n/2.  It should be read. If bitrotVerify fails then we return errXLReadQuorum error.

**Comment by hackintoshrao** [comment]
When cache is disabled and tests are run, it fails with following we error, 

```
OK: 102 passed
--- FAIL: TestGetObjectDiskNotFound (0.03s)
        object-api-getobject_test.go:318: Test 6: XL: Expected to fail with error "EOF", but instead failed with error "Storage resources are insufficient for the read operation." instead.
        object-api-getobject_test.go:310: Test 7: XL:  Expected to pass, but failed with: <ERROR> Storage resources are insufficient for the read operation.
        object-api-getobject_test.go:310: Test 8: XL:  Expected to pass, but failed with: <ERROR> Storage resources are insufficient for the read operation.
        object-api-getobject_test.go:310: Test 9: XL:  Expected to pass, but failed with: <ERROR> Storage resources are insufficient for the read operation.
FAIL
```

The test had 8 out 16 disks down.

**Comment by harshavardhana** [comment]
This is fixed.
