### ISSUE TITLE
Move bucket-policy as part of the special namespace itself.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2214]
- policy.json 
- notification.json 

Should go into XL backend itself and be protected, treat this like user set data.

**Comment by krisis** [comment]
Will be sending a PR by EOD Jul 19th.

**Comment by krisis** [comment]
I was working on other issues and this had to wait. I should be sending a fix by EOD Jul 25th.

**Comment by GarimaKapoor** [comment]
@krisis please update the status of this issue?
