### ISSUE TITLE
Validate RAFT and provide prototype implementation of multiple nodes

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2215]
Use RAFT and implement a prototype service to hold consensus and validate the reliability of master election process.

**Comment by harshavardhana** [comment]
It was decided that RAFT in not going to provide us what we need. Closing this.

**Comment by krishnasrinivas** [comment]
@harshavardhana can you post a gist of to solve what problem RAFT was being explored?

**Comment by harshavardhana** [comment]
> @harshavardhana can you post a gist of to solve what problem RAFT was being explored?

RAFT, ETCD and Consul were being explored with the idea to achieve consensus without using the Controller to make the overall setup simpler for the end user.  

It was dropped due to necessity of using a key value database as the backend (historically we knew but forgot during the discussion). 

Now the consensus will be achieved based on the transaction locks itself. With transactions locks there is also no need to have a controller instance, at any given point in time one of the minio server itself becomes the authority.

There will be a controller cli though to replay, heal as it was agreed earlier.  The work towards this has not been started yet, it is assigned to @fwessels
