### ISSUE TITLE
Tests: Tree Walk pool leak after tests finished running. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2231]
## Expected behaviour

No pending go routines after make test. 
## Actual behaviour

The go routine pending everytime tests run. 
gopath/src/github.com/minio/minio/tree-walk-pool.go:122 +0x7ac
created by github.com/minio/minio.treeWalkPool.Set
## Steps to reproduce the behaviour

Adding a defer print in the above functional and run the test, or just run `ListObject` test. 
## Minio version

Latest master at 5cc9e4e214583eeebe6d4f62ac134f750a6decfc
## System information

OSX El Caption.

**Comment by GarimaKapoor** [comment]
KP, please update the timeline for the fix!

**Comment by krisis** [comment]
I will be sending a PR for this by Jul 23rd.
