### ISSUE TITLE
XL: dynamic allocation of reedsolomon.New() 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2236]
Be able to dynamically shrink the data and parity blocks and also allocate necessary Vandermonde matrix during XL inititalization.

**Comment by ubergarm** [comment]
Not sure if it is related, but I'd like to be able to specify the number or ratio of dataBlocks to parityBlocks through configuration if that makes sense. (Dynamically through UI would be even cooler if that's even possible.)

Currently it is hard coded to split Data and Parity evenly across the number total number of disks:

https://github.com/minio/minio/blob/cef26fd6eac29cbaa436eabb91178a679429068c/xl-v1.go#L177

The change seems simple to make, but unsure if it would have other unintended effects.

Thanks,
-John

**Comment by GarimaKapoor** [comment]
It is hard coded deliberately to enforce best practice. Even at N/2 parity it only takes 2X the capacity compared to replication where it takes 3X capacity and far less reliable. It is more expensive to send experts to data center to replace failed drives, sometimes wrong cables are pulled or other mistakes happen. With N/2 parity you deploy Minio once and by the time half of the drives fail it is time to replace your whole setup. However Minio is designed to enable custom parity setting at object level. Where each object can have different parity even.Nothing would break, you can go ahead and add an option and leave the default to N/2.

**Comment by harshavardhana** [comment]
Adding for the lack of gist.  This bug is to be able to erasure code with different parity blocks as the disks fail.  It is an algorithmic-ally handled scenario well with in the Minio's internal code base.

In this proposed idea we pre-allocate all the known matrices when server gets initialized i.e 

2x2
3x3
4x4
...
8x8 

From this pool of known matrices, we figure out the right matrices to be used based on the available disks and pick the right value.  Say if you have 12 disks i.e 4 disks are down you do now 6x6 for new incoming objects rather than the default 8x8. 

This would work transparently for existing GetObject() code as well. 

Hitherto N/2 is not broken, just that with different N's being available such an N/2 is chosen automatically.

**Comment by harshavardhana** [comment]
This was decided to be not implemented for now, will re-open if the requirement comes up.
