### ISSUE TITLE
api - content-encoding missing

### ISSUE THREAD

**Issue by brackxm** [minio/minio#2244]
## Expected behaviour

getObject returns the Content-Encoding
## Actual behaviour

getObject does not return the Content-Encoding
## Steps to reproduce the behaviour

putObject with Content-Encoding
then getObject
## Minio version

Version: 2016-07-13T21:46:05Z
Release-Tag: RELEASE.2016-07-13T21-46-05Z
Commit-ID: 3f27734c22212f224037a223439a425e6d2b653a
## System information

aws java sdk 1.11.5

**Comment by krishnasrinivas** [comment]
@brackxm are you using minio FS or XL? FS does not store content-type or content-encoding in the backend.

**Comment by brackxm** [comment]
The server was started like in the readme/quickstart, with a directory argument.
Assuming this is FS, how do i start an XL server?

**Comment by brackxm** [comment]
same behaviour with the erasure coded backend (starting the server with 6 dirs).
Maybe that is XL, as there are xl.json files now.

**Comment by krishnasrinivas** [comment]
> same behaviour with the erasure coded backend (starting the server with 6 dirs).
> Maybe that is XL, as there are xl.json files now.

That is right

**Comment by harshavardhana** [comment]
Fixed by #2245
