### ISSUE TITLE
Tests: Review the project for completeness and exhaustiveness of tests.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2256]
- Review the completeness and exhaustiveness of the tests. 
- Fix them wherever its necessary. 
- Use locks debugging (https://github.com/minio/minio/pull/2223 has to be merged) and leak-detect (https://github.com/minio/minio/pull/2254) in the tests wherever necessary. 
- Fix the found bugs in the process.

**Comment by harshavardhana** [comment]
Closing the bug, open issues which are not meta. Open individual issues.

**Comment by hackintoshrao** [comment]
OK 👍
