### ISSUE TITLE
api - default content-type

### ISSUE THREAD

**Issue by brackxm** [minio/minio#2267]
## Expected behaviour

default content-type is binary/octet-stream
## Actual behaviour

default content-type is text/plain
## Steps to reproduce the behaviour

putObject without specifying content-type
headObject
## Minio version

Version: 2016-07-22T06:19:39Z
Release-Tag: DEVELOPMENT.2016-07-22T06-19-39Z
Commit-ID: 5d118141cd3d92f7d501b7045992df9e9f312b8d
## System information

aws-cli/1.10.48

**Comment by harshavardhana** [comment]
Default content-type is automatically detected by doing a ContentType detection by Golang HTTP server based on the file type, is there a reason it should be 'binary/octet-stream' when it isn't? @brackxm

**Comment by brackxm** [comment]
'binary/octet-stream' is the default on aws s3

**Comment by brackxm** [comment]
this is not an issue for me, just reporting a difference i noticed with aws s3 (as you claim compatibility)
your impl seems better here, but still a difference, so it might be an issue for some

**Comment by harshavardhana** [comment]
> this is not an issue for me, just reporting a difference i noticed with aws s3 (as you claim compatibility)
> your impl seems better here, but still a difference, so it might be an issue for some

Once you set it the value is persisted in XL backend,  we could set it to 'binary/octet-stream' but it was our intention that current behavior would be more useful.

**Comment by harshavardhana** [comment]
> this is not an issue for me, just reporting a difference i noticed with aws s3 (as you claim compatibility)
> your impl seems better here, but still a difference, so it might be an issue for some
> Once you set it the value is persisted in XL backend, we could set it to 'binary/octet-stream' but it was our intention that current behavior would be more useful.

Let us know how this would be preferred here @brackxm ?
