### ISSUE TITLE
XL: Alert on a disk failure

### ISSUE THREAD

**Issue by flibustenet** [minio/minio#2275]
On disk failure the content is still available thanks to erasure code. Then it's not possible to see that a disk is broken and should be repaired.
Linked to the possibility to repopulate the new disk #1745

**Comment by harshavardhana** [comment]
> On disk failure the content is still available thanks to erasure code. Then it's not possible to see that a disk is broken and should be repaired.
> Linked to the possibility to repopulate the new disk #1745

The disk failure will be reported in a different way.
