### ISSUE TITLE
signature: putObject XAmzContentSHA256Mismatch

### ISSUE THREAD

**Issue by brackxm** [minio/minio#2283]
With recent versions of the java aws sdk, putObject gives a XAmzContentSHA256Mismatch error.
This happens with version 1.11.16 and 1.11.20 (latest).
With version 1.11.15 it works.

**Comment by brackxm** [comment]
This seems to be due to a changed default chunkedEncodingDisabled s3ClientOption.
So a putObject with chunked encoding is giving a XAmzContentSHA256Mismatch error.

**Comment by harshavardhana** [comment]
> This seems to be due to a changed default chunkedEncodingDisabled s3ClientOption.
> So a putObject with chunked encoding is giving a XAmzContentSHA256Mismatch error.

Yes you need to disable chunkedEncoding what we also need is - https://github.com/minio/minio/issues/1008 which aws-sdk does by default. We are going to work on it and finish it to support the default aws-sdk behavior.

**Comment by harshavardhana** [comment]
Closing this as duplicate of #2326
