### ISSUE TITLE
presigned POST behavior

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2294]
`rp` is the request-promise module.
this failed:

```
return rp({
    method: s3info.method,
    uri: s3info.url,
    formData: _.extend({}, s3info.formData, {
      file: {
        value: asset.content,
        options: {
          contentType: 'application/octet-stream',
        }
      }
    })
  })
```

this worked:

```
return rp({
    method: s3info.method,
    uri: s3info.url,
    formData: _.extend({}, s3info.formData, {
      file: {
        value: asset.content,
        options: {
          contentType: 'application/octet-stream',
          filename: asset.assetId
        }
      }
    })
  })
```

i.e it succeeded when filename was provided.
Need to check the behavior of aws s3 and standards and behave accordingly.

**Comment by harshavardhana** [comment]
> return rp({
>     method: s3info.method,
>     uri: s3info.url,
>     formData: _.extend({}, s3info.formData, {
>       file: {
>         value: asset.content,
>         options: {
>           contentType: 'application/octet-stream',
>         }
>       }
>     })

This perhaps didn't work because of an existing issue here https://github.com/minio/minio/issues/2290

**Comment by vadmeste** [comment]
I tested with request-promise and aws s3, uploading works correctly without that filename attribute

**Comment by vadmeste** [comment]
I also checked with tcpdump, filename attribute is not sent
