### ISSUE TITLE
server: Implement support for 'crossdomain.xml' flash requirement

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2301]
https://aws.amazon.com/articles/2011 

S3 implemented this to handle flash requests and their cross domain policy requirements from an endpoint.  This is needed to support many exiting legacy apps.

**Comment by flaviocarmo** [comment]
A sample crossdomain.xml file can be found on the root of https://s3.amazonaws.com/crossdomain.xml

```
<?xml version="1.0"?><!DOCTYPE cross-domain-policy SYSTEM "http://www.adobe.com/xml/dtds/cross-domain-policy.dtd"><cross-domain-policy><allow-access-from domain="*" secure="false" /></cross-domain-policy>
```
