### ISSUE TITLE
POST Policy: Replace ${filename} in Key form field with filename attribute passed in multipart 

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2303]

**Comment by harshavardhana** [comment]
what is the gist of the issue here? the title is not clean enough can you elaborate @vadmeste ?

**Comment by harshavardhana** [comment]
The patch is merged - still fix this and update the title here @vadmeste

**Comment by vadmeste** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html mentions the use of ${filename} feature in Key
