### ISSUE TITLE
Docs: XL usage

### ISSUE THREAD

**Issue by AnatolyRugalev** [minio/minio#2313]
Can anyone explain why and when I need to use XL storage and how to enable it on my minio instance?

**Comment by harshavardhana** [comment]
You can find more details here @AnatolyRugalev - https://docs.minio.io/docs/minio-erasure-code-quickstart-guide

**Comment by AnatolyRugalev** [comment]
Thank you!

I already saw this page but I haven't found any XL storage mention there. This confused me a bit
