### ISSUE TITLE
Use semver compatible release versioning

### ISSUE THREAD

**Issue by jehiah** [minio/minio#2318]
Can you consider adopting [semver](http://semver.org) compatible version strings? This will help set expectations for types of changes between releases when upgrading, and will help when integrating minio into other deployment systems (for example I'm making an RPM to snapshot this dependency for deployment in an environment, and i have to make up a "version number").
## Expected behaviour

I expect to see version strings like `v1.0.0` or `v0.1.1`
## Actual behaviour

The release tag is set to `RELEASE.2016-07-13T21-46-05Z`

thanks!

**Comment by harshavardhana** [comment]
> Can you consider adopting semver compatible version strings? This will help set expectations for types of changes between releases when upgrading, and will help when integrating minio into other deployment systems (for example I'm making an RPM to snapshot this dependency for deployment in an environment, and i have to make up a "version number").

@jehiah Minio is designed for continuous deployment model and we consciously moved away to make binary version simpler.   So we choose the release date as the server version.

What we have is `config version` and `backend format version`.  Minio server also handles auto migration from one version of config to the other and also be able to handle format changes in its backend transparently.  Minio server also provides update notification automatically.

**Comment by jehiah** [comment]
++ all good things. feel free to close this request if you feel that's appropriate =) 

I just wanted to give the request/feedback that I'd find more typical version strings helpful. For my use, I explicitly version and manage state for everything that runs in my environment.

**Comment by koolhead17** [comment]
@jehiah  Are you using Minio at bitly, kind of curious? 😄

**Comment by harshavardhana** [comment]
> ++ all good things. feel free to close this request if you feel that's appropriate =)

:+1:

**Comment by jehiah** [comment]
@koolhead17 yes! Just starting out to use it as a development double for S3. We have a lot of objects in S3 =)

**Comment by koolhead17** [comment]
@jehiah 😄 
It will be great if you can add your use case to https://github.com/minio/awesome-minio. It is a curated list of projects using Minio.

**Comment by 030** [comment]
What if there a breaking changes?
