### ISSUE TITLE
Bug: Server config directory should have certs directory created by default

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2324]
In current Minio server our `.minio` directory looks like 

```
$ ls -l ~/.minio/
total 16
drwx------  3 koolhead17  staff  102 Jul 11 10:19 buckets
-rw-------  1 koolhead17  staff  847 Jul 28 13:11 config.json
-rw-------  1 koolhead17  staff  847 Jul 28 13:11 config.json.old
```

For someone who wants to run Minio with `HTTPS` has to manually create `certs` directory before providing keys, we should handle this from our end. We should not let our configuration altered manually.

**Comment by jesselucas** [comment]
@koolhead17 The ~/.minio/certs directory was created for me:

```
$  ls -Glah ~/.minio/
total 16
drwx------   5 jesse  staff   170B Jul 29 18:09 .
drwxr-xr-x@ 71 jesse  staff   2.4K Jul 29 18:22 ..
drwx------   2 jesse  staff    68B Jul 28 20:31 certs
-rw-------   1 jesse  staff   837B Jul 29 18:09 config.json
-rw-------   1 jesse  staff   837B Jul 29 18:09 config.json.old
```

**Comment by harshavardhana** [comment]
> @koolhead17 The ~/.minio/certs directory was created for me:
> 
> $  ls -Glah ~/.minio/
> total 16
> drwx------   5 jesse  staff   170B Jul 29 18:09 .
> drwxr-xr-x@ 71 jesse  staff   2.4K Jul 29 18:22 ..
> drwx------   2 jesse  staff    68B Jul 28 20:31 certs
> -rw-------   1 jesse  staff   837B Jul 29 18:09 config.json
> -rw-------   1 jesse  staff   837B Jul 29 18:09 config.json.old

I just checked it is created as well

```
                // Create certs path.
                err = createCertsPath()
                if err != nil {
                        return err
                }
```

The problem is that 'certs' is created inside a conditional where config was not created.  So it would mean that if someone deleted 'certs' directory manually it wouldn't be created later.

We can debate that we should create this directory always regardless of if config exists or not.
