### ISSUE TITLE
signature: Implement support for STREAMING-AWS4-HMAC-SHA256-PAYLOAD

### ISSUE THREAD

**Issue by marclennox** [minio/minio#2326]
I'm using the Docker version of minio and connecting with the Ruby AWS-SDK 2.x (through a third-party library called Carrierwave).

With the aws-cli tool, I can upload files without issue, but with the ruby SDK I'm getting the following error:

```
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message><Key></Key><BucketName></BucketName><Resource>/bucket/uploads/pictures/8ac516fd-e046-4367-a4eb-fb94e7fe95ee/image/output_1469823101.png</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

Just wondering how best to debug this.

**Comment by harshavardhana** [comment]
> I'm using the Docker version of minio and connecting with the Ruby AWS-SDK 2.x (through a third-party library called Carrierwave).
> 
> With the aws-cli tool, I can upload files without issue, but with the ruby SDK I'm getting the following error:
> 
> <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message><Key></Key><BucketName></BucketName><Resource>/bucket/uploads/pictures/8ac516fd-e046-4367-a4eb-fb94e7fe95ee/image/output_1469823101.png</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
> Just wondering how best to debug this.

This we have seen before, most probably related to - https://github.com/minio/minio/issues/2283 working on fixing this right now.  This is most probably related to a type of signature functionality which we do not support yet i.e http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html 

Just so we know do you know the relevant portion of the code which does this?

**Comment by marclennox** [comment]
Thanks for the quick response.  I wonder if I can somehow bypass this with configuration in the ruby SDK.

http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Core/Configuration.html#s3_multipart_max_parts-instance_method

**Comment by harshavardhana** [comment]
> Thanks for the quick response. I wonder if I can somehow bypass this with configuration in the ruby SDK.
> 
> http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Core/Configuration.html#s3_multipart_max_parts-instance_method

Yes it would be possibly by not using chunked encoded based signature. Upstream aws-sdk-java we sent earlier a patch to disable this by using a flag. 

But not sure if ruby SDK has it.

**Comment by harshavardhana** [comment]
> Thanks for the quick response. I wonder if I can somehow bypass this with configuration in the ruby SDK.
> 
> http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Core/Configuration.html#s3_multipart_max_parts-instance_method

Actually this looks like a different issue,  ruby doesn't support STREAMING-PAYLOAD which i just mentioned before. This must be something different. 

Can you paste the code or the software on how this can be reproduced? - let us try to have a look at it.

**Comment by marclennox** [comment]
Yeah, I’ve actually been able to perform operations successfully with the ruby sdk directly.  It fails when I use Papertrail or Fog on top of the Ruby SDK, so I’ll have to debug this further.

I was previously using Fake S3 successfully.

**Comment by harshavardhana** [comment]
> Yeah, I’ve actually been able to perform operations successfully with the ruby sdk directly.  It fails when I use Papertrail or Fog on top of the Ruby SDK, so I’ll have to debug this further.
> 
> I was previously using Fake S3 successfully.

Would love to see the code, must be related to signature calculation in this case.

**Comment by marclennox** [comment]
I'm using this library

https://github.com/carrierwaveuploader/carrierwave

in conjunction with the Fog library, so my initialization looks like this.

``` ruby
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider:              'AWS',
    aws_access_key_id:     ENV.fetch('AWS_ACCESS_KEY'),
    aws_secret_access_key: ENV.fetch('AWS_SECRET_KEY'),
    region:                ENV.fetch('AWS_REGION') { 'us-east-1' },
    endpoint:              ENV.key?('AWS_S3_HOST'),
    path_style:            true
  }.compact
  config.asset_host = "#{ENV.fetch('FOG_ASSET_HOST')}/#{ENV.fetch('AWS_S3_BUCKET')
  config.fog_directory = "#{ENV.fetch('AWS_S3_BUCKET')"
end
```

**Comment by marclennox** [comment]
fog-aws library is here

https://github.com/fog/fog-aws

**Comment by harshavardhana** [comment]
> fog-aws library is here
> 
> https://github.com/fog/fog-aws

Checking.

**Comment by harshavardhana** [comment]
The library seems to be working fine, do not know about carrierwave how it can be tested.  Looks like requires rails etc.

**Comment by marclennox** [comment]
I'm able to replicate the error by using the Fog AWS wrapper library, as follows.

``` ruby
s3 = Fog::Storage::AWS.new(aws_access_key_id: '<KEY>', aws_secret_access_key: '<SECRET>', endpoint: 'http://minio:9000', aws_signature_version: 4)
s3.put_object('test', 'test.png','/path/to/image.png')
```

**Comment by marclennox** [comment]
I think I've gotten closer to the root cause.  It seems that it works if I run the ruby client outside of Docker and connect through an nginx proxy running in Docker in front of minio.

However if I try to run ruby from inside Docker using a container link, I get the failure.

So something about docker network linking is triggering this.

**Comment by harshavardhana** [comment]
> I think I've gotten closer to the root cause. It seems that it works if I run the ruby client outside of Docker and connect through an nginx proxy running in Docker in front of minio.
> 
> However if I try to run ruby from inside Docker using a container link, I get the failure.
> 
> So something about docker network linking is triggering this.

Thanks for the input will check.

**Comment by marclennox** [comment]
Did some more tests.  The combination of using Fog inside of the docker VM is causing failure.  Using the ruby SDK directly works fine.  I'm using Docker for Mac FYI.

**Comment by marclennox** [comment]
I tried running minio on a separate machine, separate network and still the same issue.  So it seems the issue is something to do with Fog, which is a commonly used Ruby library for S3 access.  Here's the stack trace showing which classes and methods are being invoked, perhaps if you have time to look at Fog's source you'll see something that stands out.

```
"Expected(200) <=> Actual(400 Bad Request)\nexcon.error.response\n  :body          => \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message><Key></Key><BucketName></BucketName><Resource>/gtcloud-attachments-development/beacon_scan_sets/42507e6c-1a7a-4ebf-aabb-4e995a561884/data.csv</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>\"\n  :cookies       => [\n  ]\n  :headers       => {\n    \"Accept-Ranges\"    => \"bytes\"\n    \"Content-Type\"     => \"text/xml; charset=utf-8\"\n    \"Date\"             => \"Mon, 01 Aug 2016 15:54:30 GMT\"\n    \"Server\"           => \"Minio/DEVELOPMENT.2016-08-01T15-52-47Z (darwin; amd64)\"\n    \"Vary\"             => \"Origin\"\n    \"X-Amz-Request-Id\" => \"B75NEB6JAUBXWD1F\"\n  }\n  :host          => \"192.168.86.100\"\n  :local_address => \"172.18.0.10\"\n  :local_port    => 60708\n  :path          => \"/gtcloud-attachments-development/beacon_scan_sets/42507e6c-1a7a-4ebf-aabb-4e995a561884/data.csv\"\n  :port          => 9000\n  :reason_phrase => \"Bad Request\"\n  :remote_ip     => \"192.168.86.100\"\n  :status        => 400\n  :status_line   => \"HTTP/1.1 400 Bad Request\\r\\n\"\n",
[  1] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/expects.rb:6:in `response_call'",
[  2] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'",
[  3] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:389:in `response'",
[  4] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:253:in `request'",
[  5] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'",
[  6] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/base.rb:10:in `error_call'",
[  7] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/base.rb:10:in `error_call'",
[  8] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:273:in `rescue in request'",
[  9] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:221:in `request'",
[ 10] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'",
[ 11] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/base.rb:10:in `error_call'",
[ 12] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/base.rb:10:in `error_call'",
[ 13] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:273:in `rescue in request'",
[ 14] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:221:in `request'",
[ 15] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'",
[ 16] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/base.rb:10:in `error_call'",
[ 17] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/base.rb:10:in `error_call'",
[ 18] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:273:in `rescue in request'",
[ 19] "/data/bundle/ruby/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:221:in `request'",
[ 20] "/data/bundle/ruby/2.3.0/gems/fog-core-1.42.0/lib/fog/core/connection.rb:81:in `request'",
[ 21] "/data/bundle/ruby/2.3.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'",
[ 22] "/data/bundle/ruby/2.3.0/gems/fog-aws-0.10.0/lib/fog/aws/storage.rb:611:in `_request'",
[ 23] "/data/bundle/ruby/2.3.0/gems/fog-aws-0.10.0/lib/fog/aws/storage.rb:606:in `request'",
[ 24] "/data/bundle/ruby/2.3.0/gems/fog-aws-0.10.0/lib/fog/aws/requests/storage/put_object.rb:47:in `put_object'",
[ 25] "/data/bundle/ruby/2.3.0/gems/fog-aws-0.10.0/lib/fog/aws/models/storage/file.rb:212:in `save'",
[ 26] "/data/bundle/ruby/2.3.0/gems/fog-core-1.42.0/lib/fog/core/collection.rb:51:in `create'",
[ 27] "/data/bundle/ruby/2.3.0/gems/paperclip-5.0.0/lib/paperclip/storage/fog.rb:112:in `block in flush_writes'",
[ 28] "/data/bundle/ruby/2.3.0/gems/paperclip-5.0.0/lib/paperclip/storage/fog.rb:101:in `each'",
[ 29] "/data/bundle/ruby/2.3.0/gems/paperclip-5.0.0/lib/paperclip/storage/fog.rb:101:in `flush_writes'",
[ 30] "/data/bundle/ruby/2.3.0/gems/paperclip-5.0.0/lib/paperclip/attachment.rb:241:in `save'",
[ 31] "/data/bundle/ruby/2.3.0/gems/paperclip-5.0.0/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'",
...
```

**Comment by marclennox** [comment]
I did some stepping through the code, and I noticed something suspicious around the `x-amz-content-sha256` header, which seems to be the complaint in the error message.

Notice the header data being sent below.

```
:headers=>
  {"Content-Type"=>"text/plain",
   "x-amz-acl"=>"public-read",
   "Host"=>"192.168.86.100",
   "x-amz-date"=>"20160801T163417Z",
   "x-amz-content-sha256"=>"STREAMING-AWS4-HMAC-SHA256-PAYLOAD",
   "x-amz-decoded-content-length"=>1000633,
   "Authorization"=>
    "AWS4-HMAC-SHA256 Credential=WK4Y6IRX20UG7W3QZFCM/20160801/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=cafe223149eda9a8d926138e77fc82a8dea55dc73d3359cba7a0270b6bdfde8d"},
 :idempotent=>true,
 :method=>"PUT",
 :path=>"/gtcloud-attachments-development/beacon_scan_sets/499d5dc3-cc67-4cb2-91a4-a334d18302a7/data.csv"
```

**Comment by harshavardhana** [comment]
> "x-amz-content-sha256"=>"STREAMING-AWS4-HMAC-SHA256-PAYLOAD",

This looks like the same bug i mentioned earlier i am fixing right now.

**Comment by marclennox** [comment]
OK cool, let me know when you have something I can test.  I’m eager to get this resolved on my end.

**Comment by harshavardhana** [comment]
> OK cool, let me know when you have something I can test.  I’m eager to get this resolved on my end.
> …

Sure will let you know. Thanks for your patience.

**Comment by darkhelmet** [comment]
I'm hitting this too, using attache, which uses fog.

The problem in fog comes from this: https://github.com/fog/fog-aws/blob/f8e795d6d35c4f3fac4f92a507410c1cdfae6d7d/lib/fog/aws/storage.rb#L579

If you do something like `...files.create(key: 'foo', File.read('foo'))` then it works fine, but if you pass a file handle `...files.create(key: 'foo', File.open('foo'))` then it fails.

I tried setting the signature version to 2, but minio doesn't support that. Ima hack some things in my local env to make it work for now, but I'll be watching this space for updates. Excited to deploy this 😄

**Comment by marclennox** [comment]
Hey @darkhelmet, I posted my temporary monkey patch over at the fog-aws project if you're interested.

https://github.com/fog/fog-aws/issues/285

Basically I read the file into memory and upload it in one shot, which is exactly what you've suggested also.  It's not great, but it works for now until this issues is resolved.

**Comment by harshavardhana** [comment]
Here is a working patch that is available - https://github.com/minio/minio/pull/2370 

@marclennox @darkhelmet would you mind testing this?

**Comment by marclennox** [comment]
I’d love to test this out.  I’m running minio with Docker, would you mind pushing a Docker testing tag for this patch build, or is there a script to build the docker image myself locally using this patch?

**Comment by harshavardhana** [comment]
Let me see if we can get a docker image.

**Comment by marclennox** [comment]
@harshavardhana I was able to use your PR to patch minio:master and build a Docker image.  On running my test suite, it appears that everything works with streaming signature v4

**Comment by harshavardhana** [comment]
> @harshavardhana I was able to use your PR to patch minio:master and build a Docker image. On running my test suite, it appears that everything works with streaming signature v4

Very cool.

**Comment by marclennox** [comment]
Thanks @harshavardhana.  When do you plan to merge this and do an official Docker build?

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana. When do you plan to merge this and do an official Docker build?

Just a few things, some test cases pending.
