### ISSUE TITLE
Don't concatenate multi-part upload during completion

### ISSUE THREAD

**Issue by ramondeklein** [minio/minio#2334]
The FS version concatenates all the parts of a multi-part upload when the multi-upload is completed. Multi-part uploads are often used for huge files, so this takes a lot of time and also spikes the IOPS for a while. In some situations (like ours), it would be much better to use the XL method to keep the parts separate and combine them during download.

Of course, the parts cannot be accessed the regular way (via the filesystem) anymore. But most systems that use S3 only use S3 to access them (you can't do otherwise in AWS), so this wouldn't be a big problem.

Concatenating files might be the sensible default option, but when performance and I/O is critical, then keeping the files separate might be the better option. Now, we reverted using the XL method, solely for this feature, but this costs us a lot of additional disk space.

**Comment by krishnasrinivas** [comment]
@ramondeklein 

> Of course, the parts cannot be accessed the regular way (via the filesystem) anymore.

This was the intention to do the concatenation so that the backend is kept simple.

> Multi-part uploads are often used for huge files, so this takes a lot of time and also spikes the IOPS for a while.

What is the file size you are uploading? what client library are you using to do the multipart upload?

**Comment by ramondeklein** [comment]
We are rolling our own HTTP requests from the webbrowser to have maximum flexibility. Depending on the uploader's bandwidth, we alter the chunk-size dynamically and also tune the amount of parallel parts that are being uploaded. Our files range from several megabytes up to 50GB. The part-size is between 5-50MB.

**Comment by krishnasrinivas** [comment]
@ramondeklein are you using aws-jdk-js http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-intro.html in the web browser for multipart uploads?

**Comment by ramondeklein** [comment]
No, we use the AWS-SDK on the backend (Javascript). It initiates the multi-part upload and returns the tokens to the client. The client uploads all the parts using handcrafted XHRs. We don't use an AWS library on the client, so we do our own authorization, SHA calculation, etc... Once the client has uploaded all parts directly to S3 (without passing our server), we signal our backend that the multi-part upload has completed. The back-end then initiates the finalization command, which will complete the upload.

Because the upload token has an expiration date and only allows to upload to a specific bucket, with a fixed prefix for the filename it's pretty secure.

**Comment by krishnasrinivas** [comment]
It will be a little tricky, we will get back on this.

**Comment by harshavardhana** [comment]
Saving the parts information makes backend format change which we don't want to carry in FS. The reason to keep FS the way it is as @krishnasrinivas pointed out is for users to serve existing content. We cannot break the assumption and it is this simplicity which is important for FS backend.  

Rather than introducing a new backend one could use 'XL' with 4 disks which would work the same way.  Additionally we will discuss internally with @abperiasamy if at all we would want to introduce a new backend which is like FS but for special cases alone. 

> .. Once the client has uploaded all parts directly to S3 (without passing our server), we signal our backend that the multi-part upload has completed. The back-end then initiates the finalization command, which will complete the upload.

Question here does the user uploading the file wait here due to completion of multipart upload?

**Comment by ramondeklein** [comment]
> Question here does the user uploading the file wait here due to completion of multipart upload?

Well... They do now, but in S3 this operation is completed pretty fast. There is no need for our end-users to wait for this operation. One of our benefits is that we send out the emails right after the upload has completed. There is no processing step necessary, which is better for I/O distribution (no spikes) and without post-processing, the recipient can download the files faster.

We currently use Minio in XL mode to avoid the multi-part concatenation. We currently use six volumes, but this requires quite some additional disk-space. I would favor disk-space over reliability, because we only have one disk and six volumes on a single disk doesn't really add much protection (maybe recovery from bitrot). Do I understand that I could reconfigure Minio into a 4-volume array, so we don't have redundancy but prevent the concatenation step?

PS: Big thumbs up :+1: :+1: :+1:  for the prompt response. It's really appreciated.

**Comment by krishnasrinivas** [comment]
@ramondeklein we are planning to do the concatenation in background, so your users will not have to wait, will that work for you?

**Comment by ramondeklein** [comment]
I think that solution would be a violation of the S3 API. Amazon also states that the completion of this call can take several minutes ([link](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html)):

> Processing of a Complete Multipart Upload request could take several minutes to complete. After Amazon S3 begins processing the request, it sends an HTTP response header that specifies a 200 OK response. While processing is in progress, Amazon S3 periodically sends whitespace characters to keep the connection from timing out. Because a request could fail after the initial 200 OK response has been sent, it is important that you check the response body to determine whether the request succeeded.

We have never seen that the completion takes minutes (on S3 itself). Even large files (40GB) complete only in a few seconds.

If you process the parts in the background, then you should be able to serve the file as if it was already completed. After a success response, client code assumes that the file can be accessed.

For us, it's quite easy to use background processing. It would only add a delay between uploading and downloading the file. Another bad side-effect is the sudden spike in I/O on the system. Uploads are often limited by bandwidth (network bound). Concatenating the files would be I/O bound on the storage array. This will probably impact download and upload performance. I/O spikes make a system scale less, so I would rather avoid it.

**Comment by ramondeklein** [comment]
PS: Is it possible to use XL mode without the additional parity volumes? If we don't have additional overhead for the parity information, then the XL way is fine with us.

**Comment by harshavardhana** [comment]
> I think that solution would be a violation of the S3 API. Amazon also states that the completion of this call can take several minutes (link):
> 
> Processing of a Complete Multipart Upload request could take several minutes to complete. After Amazon S3 begins processing the request, it sends an HTTP response header that specifies a 200 OK response. While processing is in progress, Amazon S3 periodically sends whitespace characters to keep the connection from timing out. Because a request could fail after the initial 200 OK response has been sent, it is important that you check the response body to determine whether the request succeeded.

This was the entire reason we could concatenate :-)

**Comment by harshavardhana** [comment]
@ramondeklein we have merged a change in master which preempts the concatenation for FS backend. 
Which would in-turn avoid the larger delay at the end of a complete multipart upload.  

Would you validate 'github.com/minio/minio/' 'master' ?

**Comment by ramondeklein** [comment]
Could you explain what's the current behavior. Does it concatenate the files in the background and already return? Or is it similar to XL mode where the separate parts will be kept?

**Comment by krishnasrinivas** [comment]
@ramondeklein here's what we do: start appending parts as soon as possible and keep the order of the parts in the appended file correct.

so by the time complete-multipart-upload is called we have the appended file ready.

The append process will happen as and when the parts arrive.

**Comment by ramondeklein** [comment]
Okay, that seems pretty cool. I'll try to fetch a copy this week. I always use the minio/latest image, but I guess I now need to fetch minio/edge to do some testing...

**Comment by harshavardhana** [comment]
> Okay, that seems pretty cool. I'll try to fetch a copy this week. I always use the minio/latest image, but I guess I now need to fetch minio/edge to do some testing...

Yes you would need to get 'minio/edge'

**Comment by harshavardhana** [comment]
> Okay, that seems pretty cool. I'll try to fetch a copy this week. I always use the minio/latest image, but I guess I now need to fetch minio/edge to do some testing...

@ramondeklein have you been able to validate the new changes?

**Comment by harshavardhana** [comment]
> @ramondeklein have you been able to validate the new changes?

We made a new release, closing this bug.
