### ISSUE TITLE
"minio control heal" cli in minio binary

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2343]
Implement minimal framework to implement commands:
minio control heal
minio control shutdown

Ideally should be implemented as a package.

**Comment by harshavardhana** [comment]
> Ideally should be implemented as a package.

There is no reason to, keep it as the overall structure. Control package is not useful outside unless you call it 'Control client SDK'

**Comment by krishnasrinivas** [comment]
The assumption that you should not create package if it's not useful outside appears wrong.

I checked few of the well known golang projects I could think of, all of them have been structured using packages.
for example, bradfitz's project: https://github.com/camlistore/camlistore
you can see that packages are specific to camlistore and not usable outside:
https://github.com/camlistore/camlistore/tree/master/pkg/camlegal
https://github.com/camlistore/camlistore/tree/master/pkg/schema
https://github.com/camlistore/camlistore/blob/master/pkg/publish/types.go

Also check  https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit

comment by Russ Cox:

> Go encourages structuring a program as a collection of packages interacting using exported APIs. 

So packages are not just used to share reusable code but also structure your project.

If exposing APIs by packages is our reason of not using packages then we can always use `internal` packages But still `internal` packages will be restrictive i.e one package cant import another package. We could just use regular golang (`non-internal`) packages as exposing an API is not harmful for our project.

**Comment by harshavardhana** [comment]
> I checked few of the well known golang projects I could think of, all of them have been structured using packages.
> for example, bradfitz's project: https://github.com/camlistore/camlistore
> you can see that packages are specific to camlistore and not usable outside:
> https://github.com/camlistore/camlistore/tree/master/pkg/camlegal
> https://github.com/camlistore/camlistore/tree/master/pkg/schema
> https://github.com/camlistore/camlistore/blob/master/pkg/publish/types.go
> 
> Also check https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit
> 
> comment by Russ Cox:
> 
> Go encourages structuring a program as a collection of packages interacting using exported APIs.
> So packages are not just used to share reusable code but also structure your project.
> 
> If exposing APIs by packages is our reason of not using packages then we can always use internal packages But still internal packages will be restrictive i.e one package cant import another package. We could just use regular golang (non-internal) packages as exposing an API is not harmful for our project.

There is no such consensus and brings in complexity, Let's not do it right now. We have other important things to address.

**Comment by harshavardhana** [comment]
> There is no such consensus and brings in complexity, Let's not do it right now. We have other important things to address.

Adding to that we will do this activity on case by case basis in a clean way deciding on what should become a package or not. For the time being we have to address the distributed server version timeline.

**Comment by harshavardhana** [comment]
Fixed .
