### ISSUE TITLE
minio complains over UNSIGNED-PAYLOAD on secure server

### ISSUE THREAD

**Issue by brendanashworth** [minio/minio#2355]
## Expected behaviour

I might be wrong :) but I'd expect that `presignedGetObject` requests receive the same response from minio when properly authenticated.
## Actual behavior

Minio returns a `ErrContentSHA256Mismatch` ("The provided 'x-amz-content-sha256' header does not match what was computed.") when minio-js makes a request to do `presignedGetObject` on a secure server. In this case, sha256 summing should be disabled and the node client sends `UNSIGNED-PAYLOAD` as the header.

Minio works correctly on a server that isn't secure, which triggers the sha256 sum to take place.
## Steps to reproduce the behavior

This can be tested between `play.minio.io` (secure) and a local, out-of-the-box minio install. Run this code to see the difference between the two, adjusting authentication parameters as needed.

``` javascript
const Minio = require('minio');

/*var client = new Minio({
    endPoint: 'play.minio.io',
    port: 9000,
    secure: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});*/

/*var client = new Minio({
    endPoint: 'localhost',
    port: 9000,
    secure: false,
    ...
});*/

client.presignedGetObject('pictures', 'house.png', 100, function(err, url) {
    if (err) throw err;
    console.log(url);
});

```
## Minio version
- `play.minio.io` = `2016-07-28T03:19:46Z`
- `localhost` = `2016-08-03T07:43:43Z`
## System information

Unsure about the minio server, but locally it's a Macbook running OSX 
10.11.6.

**Comment by krishnasrinivas** [comment]
@brendanashworth i am able to reproduce this, checking.

**Comment by harshavardhana** [comment]
> Minio returns a ErrContentSHA256Mismatch ("The provided 'x-amz-content-sha256' header does not match what was computed.") when minio-js makes a request to do presignedGetObject on a secure server. In this case, sha256 summing should be disabled and the node client sends UNSIGNED-PAYLOAD as the header.
> 
> Minio works correctly on a server that isn't secure, which triggers the sha256 sum to take place.

Can you try the same behavior with 'minio-go' ?

**Comment by brendanashworth** [comment]
@harshavardhana hmph, it doesn't behave the same — this must be an issue with minio-js, I'll move it to there. Sorry for the run around.

**Comment by krishnasrinivas** [comment]
@brendanashworth you can fix this in minio:

basically handler for getbucketlocation was not handling UNSIGNED-PAYLOAD properly.
minio-go was not doing UNSINGED-PAYLOAD for getbucketlocation

```
krishna@escape:~/gocode/src/github.com/minio/minio$ git diff
diff --git a/bucket-handlers.go b/bucket-handlers.go
index 878b5fb..4eab391 100644
--- a/bucket-handlers.go
+++ b/bucket-handlers.go
@@ -17,12 +17,8 @@
 package main

 import (
-       "bytes"
-       "encoding/base64"
-       "encoding/hex"
        "encoding/xml"
        "io"
-       "io/ioutil"
        "net/http"
        "net/url"
        "path"
@@ -89,28 +85,7 @@ func (api objectAPIHandlers) GetBucketLocationHandler(w http.ResponseWriter, r *
                        return
                }
        case authTypeSigned, authTypePresigned:
-               payload, err := ioutil.ReadAll(r.Body)
-               if err != nil {
-                       writeErrorResponse(w, r, ErrInternalError, r.URL.Path)
-                       return
-               }
-               // Verify Content-Md5, if payload is set.
-               if r.Header.Get("Content-Md5") != "" {
-                       if r.Header.Get("Content-Md5") != base64.StdEncoding.EncodeToString(sumMD5(payload)) {
-                               writeErrorResponse(w, r, ErrBadDigest, r.URL.Path)
-                               return
-                       }
-               }
-               // Populate back the payload.
-               r.Body = ioutil.NopCloser(bytes.NewReader(payload))
-               var s3Error APIErrorCode // API error code.
-               validateRegion := false  // Validate region.
-               if isRequestSignatureV4(r) {
-                       s3Error = doesSignatureMatch(hex.EncodeToString(sum256(payload)), r, validateRegion)
-               } else if isRequestPresignedSignatureV4(r) {
-                       s3Error = doesPresignedSignatureMatch(hex.EncodeToString(sum256(payload)), r, validateRegion)
-               }
-               if s3Error != ErrNone {
+               if s3Error := isReqAuthenticated(r); s3Error != ErrNone {
                        writeErrorResponse(w, r, s3Error, r.URL.Path)
                        return
                }
krishna@escape:~/gocode/src/github.com/minio/minio$ 
```

**Comment by harshavardhana** [comment]
@krishnasrinivas - can you send a PR?

**Comment by harshavardhana** [comment]
Also minio-go should be fixed as well.

**Comment by krishnasrinivas** [comment]
> Also minio-go should be fixed as well.

let me fix

**Comment by brendanashworth** [comment]
Oh! How sneaky. Thanks for the fix!
