### ISSUE TITLE
Load Image in browser by direct url pointing

### ISSUE THREAD

**Issue by ajarbehari** [minio/minio#2360]
## Expected behaviour

Ability to access an image with public-read access using <img ng-src={{ImageUrl}} > and load in browser
## Actual behaviour

Access Denied error .
## Steps to reproduce the behaviour
1. Uploaded image to bucket with public-read permission. File is uploaded but not sure if ACL: 'public-read' and content-type: 'file.type' is set in aws.s3.upload call . We cannot read back acl permissions using getObjectAcl as we get error 501 .
2. Acccess image using <img ng-src={{ImageUrl}} where url is http://192.168.40.10000/bucket-name/folder-name/image
3. Access Denied error
4. Able to fetch the image file if I use the getObject call but it returns as uint8array and has to be converted to base64 format before displaying in browser
## Minio version
- (paste output of `minio version`)
  Version: 2016-08-02T12:10:19Z
  Release-Tag: DEVELOPMENT.2016-08-02T12-10-19Z
  Commit-ID: 1494af485e7828c848cd6a2903ace27676c99986
## System information

uname -a
Linux apj 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Uploaded image to bucket with public-read permission. File is uploaded but not sure if ACL: 'public-read' and content-type: 'file.type' is set in aws.s3.upload call . We cannot read back acl permissions using getObjectAcl as we get error 501 .
> Acccess image using <img ng-src={{ImageUrl}} where url is http://192.168.40.100/bucket-name/folder-name/image
> Access Denied error
> Able to fetch the image file if I use the getObject call but it returns as uint8array and has to be converted to base64 format before displaying in browser

On Minio we do not support ACL's on objects we support Bucket policy - https://docs.minio.io/docs/minio-client-complete-guide#policy . Using bucket policy you can make objects to be accessed anonymously.

**Comment by ajarbehari** [comment]
I tried to set the 
mc policy both bucket 
mc policy both bucket\subfolder
and this was set correctly from mc .

Can we also do this from aws js sdk using putBucketPolicy by passing policy as json object ?

And, I still get access denied 403 when I access the image resource in the subfolder .

**Comment by harshavardhana** [comment]
> I tried to set the 
> mc policy both bucket 
> mc policy both bucket\subfolder
> and this was set correctly from mc .

Can you provide exact behavior basically some more details about the setup? 
- OS
- minio version
- Backend being used 'fs' or 'erasure coded'? 

> Can we also do this from aws js sdk using putBucketPolicy by passing policy as json object ?

Yes it is definitely possible you have to construct your own policy json, some examples here 
https://gist.github.com/harshavardhana/23b19e20409248189eb3dbbc74a1c42c

**Comment by ajarbehari** [comment]
OS (Ubuntu 14.04 LTS)
uname -a
Linux apj 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Minio Version
Version - 2016-08-02T12:10:19Z
Release-Tag-  DEVELOPMENT.2016-08-02T12-10-19Z
Commit-ID-  1494af485e7828c848cd6a2903ace27676c99986

I am using the default backend when installed from source , I think 'filesystem' .

**Comment by harshavardhana** [comment]
> OS (Ubuntu 14.04 LTS)
> uname -a
> Linux apj 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> 
> Minio Version
> Version - 2016-08-02T12:10:19Z
> Release-Tag- DEVELOPMENT.2016-08-02T12-10-19Z
> Commit-ID- 1494af4
> 
> I am using the default backend when installed from source , I think 'filesystem' .

Oh you are running the master, let me check what is the problem.

**Comment by ajarbehari** [comment]
I am getting some unexplained behavior with mc look at sequence of commands on terminal.

./mc policy wyzbee-52a3e1ee/
Access permission for ‘wyzbee-52a3e1ee/’ is ‘none’

./mc policy both wyzbee-52a3e1ee/
Access permission for ‘wyzbee-52a3e1ee/’ is set to ‘both’

./mc policy wyzbee-52a3e1ee/
Access permission for ‘wyzbee-52a3e1ee/’ is ‘none’

Can these issue be caused by migration . I had first installed mc from Release and then upgraded to Master .

Migration from version ‘4’ to ‘5’ completed successfully.
Version: 2016-08-02T12:10:19Z
Release-Tag: DEVELOPMENT.2016-08-02T12-10-19Z
Commit-ID: 1494af485e7828c848cd6a2903ace27676c99986

**Comment by harshavardhana** [comment]
> I am getting some unexplained behavior with mc look at sequence of commands on terminal.
> 
> ./mc policy wyzbee-52a3e1ee/
> Access permission for ‘wyzbee-52a3e1ee/’ is ‘none’
> 
> ./mc policy both wyzbee-52a3e1ee/
> Access permission for ‘wyzbee-52a3e1ee/’ is set to ‘both’
> 
> ./mc policy wyzbee-52a3e1ee/
> Access permission for ‘wyzbee-52a3e1ee/’ is ‘none’
> 
> Can these issue be caused by migration . I had first installed mc from Release and then upgraded to Master .
> 
> Migration from version ‘4’ to ‘5’ completed successfully.
> Version: 2016-08-02T12:10:19Z
> Release-Tag: DEVELOPMENT.2016-08-02T12-10-19Z
> Commit-ID: 1494af4

There has been some changes recently, need to validate what is going on.

// cc @hackintoshrao

**Comment by hackintoshrao** [comment]
@ajarbehari :  Created a new issue for policy issue, you can follow it up here https://github.com/minio/minio/issues/2361 .
