### ISSUE TITLE
bucket policy: Unexpected behaviour. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2361]
As reported by @ajarbehari here https://github.com/minio/minio/issues/2360 , 

> I am getting some unexplained behavior with mc look at sequence of commands on terminal.

./mc policy wyzbee-52a3e1ee/
Access permission for ‘wyzbee-52a3e1ee/’ is ‘none’

./mc policy both wyzbee-52a3e1ee/
Access permission for ‘wyzbee-52a3e1ee/’ is set to ‘both’

./mc policy wyzbee-52a3e1ee/
Access permission for ‘wyzbee-52a3e1ee/’ is ‘none’

**Comment by hackintoshrao** [comment]
@ajarbehari : Not able to reproduce with latest master of both 'mc' and 'minio' server at https://github.com/minio/minio/commit/1494af485e7828c848cd6a2903ace27676c99986. Can you upgrade to latest master and validate it on any newly created bucket?

**Comment by ajarbehari** [comment]
I was getting the above error with the below mc version (which was Release version) :

./mc --version 

2016-07-13T22:00:39Z

I installed latest version from src 
./mc --version

VERSION:
DEVELOPMENT.GOGET

After this the permissions were set correctly and I could access the images in the folder anonymously from browser.

**Comment by hackintoshrao** [comment]
@ajarbehari : Thanks for confirming. We consistently keep fixing bugs, there were lot of policy related bugs which were fixed in last couple of weeks, will soon plan for a new release.
