### ISSUE TITLE
Unable to upload files while in a browser on windows 32 bit

### ISSUE THREAD

**Issue by ozonesn** [minio/minio#2374]
## Expected behaviour

files to be uploaded (.png, .js, .txt) via minio browser
## Actual behaviour

![error](https://cloud.githubusercontent.com/assets/9211383/17457881/e13469d2-5c23-11e6-9a59-5ac922e2f461.png)
## Steps to reproduce the behaviour
1. install minio server on 32 bit windows
2. create a data directory
3. start mino server
4. create a bucket via browser
5. files will error upload
## Minio version
- 2016-07-13T21:46:05Z
## System information

Windows 7 ultimate 32 bit
Browser : Firefox ver 48

**Comment by vadmeste** [comment]
@ozonesn, thanks for reporting. I tried to be similar as much as possible to your testing case but I failed to reproduce the bug, could we schedule to test together ?

**Comment by ozonesn** [comment]
@vadmeste, sure, shall we sometimes have teamviewer session?

**Comment by vadmeste** [comment]
@ozonesn, yes.. join us here https://gitter.im/minio/minio

**Comment by vadmeste** [comment]
A proxy (not standard one) was used between Firefox and Minio server.. Most likely that proxy is buggy or needs user pre-configuration, but I guess a proxy should be always transparent, any thoughts?

**Comment by ozonesn** [comment]
@vadmeste The particular proxy has a role providing access; mainly, managing download and clipboard to third party Download Manager. Thus it was added automatically without user convention. Why is minio unable to handshake?

**Comment by krishnasrinivas** [comment]
@vadmeste What's the proxy's name? can we reproduce this to check what's really happening? were there any clues in the JS console?

**Comment by ozonesn** [comment]
@vadmeste , @koolhead17 , @krishnasrinivas http://127.0.0.1:9614/proxy.pac is used as proxy.

**Comment by vadmeste** [comment]
@krishnasrinivas, this is the XDM proxy (download manager).. I suggest to test against known proxy tools and that would be enough,

**Comment by krishnasrinivas** [comment]
@vadmeste I think the XDM proxy is changing the `Host` header causing signature mismatch. was it returning 401/403 error?
Host header won't affect json/rpc as auth is webtoken based and hence it should be affecting only upload/download of objects.

**Comment by krishnasrinivas** [comment]
Ah but, we don't do presigned urls anymore for upload/download.

**Comment by vadmeste** [comment]
> was it returning 401/403 error?

We didn't get any web service error as I recall which was strange, we can test again tocheck. By the way, json/rpc doesn't return any error (so 200 success) when you send a request without `content-type:application/json`, so it could be something changed in the request that didn't please json/rpc

**Comment by harshavardhana** [comment]
> We didn't get any web service error as I recall which was strange, we can test again to test. By the way, json/rpc doesn't return any error (so 200 success) when you send a request without content-type:application/json, so it could be something changed in the request that didn't please json/rpc

@koolhead17 will work with @ozonesn

**Comment by ozonesn** [comment]
@harshavardhana, I am ready to assist.

**Comment by harshavardhana** [comment]
has this been resolved @krishnasrinivas ?

**Comment by ozonesn** [comment]
@krishnasrinivas as of End User, it is solved. What developers are up to?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas as of End User, it is solved. What developers are up to?

is upload working for you now then?

**Comment by ozonesn** [comment]
@krishnasrinivas yes, upload is working fine after disabling proxy.

**Comment by harshavardhana** [comment]
> @krishnasrinivas yes, upload is working fine after disabling proxy.

Closing this as working for now.
