### ISSUE TITLE
tests: TestCheckPortAvailability fails when port 9000 busy.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2376]
## Expected behaviour

Tests to pass irrespective whether port 9000 is busy. 
## Actual behaviour

Fails when 9000 is busy.
--- FAIL: TestCheckPortAvailability (0.00s)
        checkport_test.go:37: checkPortAvailability test failed for port: 9000. Error: listen tcp :9000: bind: address already in use
## Steps to reproduce the behaviour

Run any server on 9000 and do `go test` on Minio repo root. 
## Minio version

Master at b23605a2b5397b0303f4ab1ebe3111c93c6796eb
## System information

Able to produce on both Mac and Linux.

**Comment by vadmeste** [comment]
If this doesn't fail, it means that other functional tests that run a server on the same port will fail too.. I think this is an overkill to change this behavior

**Comment by harshavardhana** [comment]
> If this doesn't fail, it means that other functional tests that run a server on the same port will fail too.. I think this is an overkill to change this behavior

It can be changed to pick an free port to run the tests.

**Comment by vadmeste** [comment]
> It can be changed to pick an free port to run the tests.

I think we need to avoid adding more details to our minds for a little gain.

**Comment by harshavardhana** [comment]
Not really we have this code already AFAIK.
