### ISSUE TITLE
GetObject (Presigned): Incorrect error response message

### ISSUE THREAD

**Issue by awwalker** [minio/minio#2380]
## Expected behaviour

wanted to get "Request has expired"
## Actual behaviour

got "Request has expired."
## Steps to reproduce the behaviour

run s3verify tests
## Minio version
- (paste output of `minio version`)
  play.minio.io:9000
  ## System information

**Comment by hackintoshrao** [comment]
@awwalker : The expected and the actual behavior you have mentioned in the same.  Are you talking about error response for expired presign URL?

**Comment by awwalker** [comment]
@hackintoshrao one has a period and one doesn't that's the difference. We include it in the error response and s3 doesn't.

**Comment by hackintoshrao** [comment]
@awwalker : Got it, so have to just introduce a `.`, thats it right ?

**Comment by hackintoshrao** [comment]
Oops, need to remove the period.

**Comment by hackintoshrao** [comment]
Will fix it in https://github.com/minio/minio/pull/2375
