### ISSUE TITLE
Can not create bucket with Unicode Character file name

### ISSUE THREAD

**Issue by ozonesn** [minio/minio#2384]
## Expected behaviour

bucket to be created with unicode file name (Nepali Unicode नेपाली युनिकोड)
## Actual behaviour

![error](https://cloud.githubusercontent.com/assets/9211383/17479122/43969fe2-5d90-11e6-9b1f-de6b6cb61968.png)
## Steps to reproduce the behaviour

 install minio server on 32 bit windows 7
    create a data directory
    start minio server
    create a bucket via browser where file name is a Unicode characters बकेट for example
    fail create Bucket name invalid: बकेट
## Minio version
- 2016-07-13T21:46:05Z
## System information

Host: Windows-Machine | OS: windows | Arch: 386
Browser: Firefox

**Comment by krishnasrinivas** [comment]
@ozonesn 
Bucket name must be 3-63 characters long, can contain dashes and periods, but must begin and end with a lowercase letter or a number. Unicode is not allowed
