### ISSUE TITLE
s3-api: Need cleaner way to construct variable error messages. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2386]
In cases like mentioned in [here](https://github.com/minio/minio/issues/2385) , Need cleaner way to construct runtime error messages.

**Comment by krishnasrinivas** [comment]
@harshavardhana if you or @vadmeste have not yet started working on this, i would like to work on this

**Comment by harshavardhana** [comment]
> @harshavardhana if you or @vadmeste have not yet started working on this, i would like to work on this

I already have a patch for this but lets discuss if you have better ideas.

**Comment by krishnasrinivas** [comment]
> I already have a patch for this but lets discuss if you have better ideas.

I had some vague ideas, will get back on this.

**Comment by GarimaKapoor** [comment]
@harshavardhana is it ready to be reviewed by @abperiasamy

**Comment by harshavardhana** [comment]
> @harshavardhana is it ready to be reviewed by @abperiasamy

Not yet will be ready by tomorrow.

**Comment by harshavardhana** [comment]
@GarimaKapoor - This change is not finished yet, the change itself is larger with lot of changes across the code base. Since we are closing in on the release i am okay to put this into next one as there is too little time for this level of change to bring in.

The work on this patch is going on in parallel, don't want distributed release to hold off.

**Comment by harshavardhana** [comment]
Moving this out of distributed release will address this in another release after distributed.

**Comment by deekoder** [comment]
This can be addressed later when we do a full overhaul and have the ability to dynamically generate the error messages struct to be exactly compatible with S3 error messages. For now we will close and revisit this after we complete error message fixes happening right now from @kannappanr
