### ISSUE TITLE
tests: Need unit tests for bucket-handlers.go

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2412]
- Need to register only the necessary endpoints required for each test so the the unit test for the given handler is performed under isolated and minimal environment, here is an [example](https://github.com/minio/minio/blob/master/bucket-policy-handlers_test.go#L241) . 
- Once coverage for all handlers is finished any issues can be mapped to these handlers and can be added as cases.

**Comment by harshavardhana** [comment]
Overall coverage increased to 1.5% with the changes here, closing this bug. We will need to add 'ErrServerNotIntialized' cases as well.  Which will be addressed in a separate test bug opening it right now. Closing this.
