### ISSUE TITLE
tests: Need better coverage for  streaming-signature-v4.go . 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2421]

**Comment by harshavardhana** [comment]
ping @brendanashworth - will you be able to work on this?

**Comment by brendanashworth** [comment]
@harshavardhana I probably won't have time to work on this one — sorry!

**Comment by harshavardhana** [comment]
> @harshavardhana I probably won't have time to work on this one — sorry!

Thanks @brendanashworth // cc @vadmeste
