### ISSUE TITLE
tests: Need better coverage for  web-handlers.go 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2422]
Need to register the necessary handlers in isolation using something like [this](https://github.com/minio/minio/blob/master/test-utils_test.go#L793) and test them in isolation.

**Comment by vadmeste** [comment]
@hackintoshrao, could you explain why we need to test handlers in isolation?

**Comment by hackintoshrao** [comment]
Yes, 
- Firstly we need unit tests for the handlers, ( It could be a different question now that why we need unit tests for handlers), while unit testing it is important the system is setup with least functionalities so that there are no interference or influence from any other part of the software. 
- Thats why for other bucket handlers tests too register only necessary end points using this function during tests https://github.com/minio/minio/blob/master/test-utils_test.go#L793 .

**Comment by vadmeste** [comment]
This patch https://github.com/minio/minio/pull/2429 did this (increase 1.17%), well see if I can do better
