### ISSUE TITLE
web handlers: Upload API should support multipart upload

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2434]

**Comment by harshavardhana** [comment]
This is not needed, we decided this conciously. Browser is not meant for uploading files bigger than 5GB. It is better left to intelligent tooling like mc which can provide resumable uploads.

**Comment by vadmeste** [comment]
@harshavardhana, I was talking about http mime multipart.. but still r.Body is not buffered in golang and it is passed directly to storage.PutObject()

You can close this issue.

**Comment by harshavardhana** [comment]
> @harshavardhana, I was talking about http mime multipart.. but still r.Body is not buffered in golang and it is passed directly to storage.PutObject()

We don't need that either mime multipart is only when there is a form input - we don't have a form input and do not foresee when we might have.
