### ISSUE TITLE
validate new go1.7 release for block/cpu/mem profiling

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2445]
https://blog.golang.org/go1.7

**Comment by hackintoshrao** [comment]
Size of binary with Go 1.6 build - 18098887 bytes. 
Size of binary with Go 1.7 build - 18089595 bytes.

**Comment by hackintoshrao** [comment]
There's  a consistent 15 second gain with 500 serial get object on 1Gb file with 1.7 build.

**Comment by harshavardhana** [comment]
> There's a consistent 15 second gain with 500 serial get object on 1Gb file with 1.7 build.

Is there a memory consumption decrease in the overall run?

**Comment by hackintoshrao** [comment]
>  Is there a memory consumption decrease in the overall run? 

Will do a concurrenet load test to verify it.

**Comment by hackintoshrao** [comment]
Need https://github.com/minio/minio/issues/2594 and issues with load test to solved to moved ahead (https://github.com/minio/minio/issues/2591) .

**Comment by hackintoshrao** [comment]
`Memory profiles for Minio build with Go 1.6 and Go 1.7 under 200 parallel reads of 1GB object from aws-cli.`
- With Go 1.7 
  [s3200get-go-new.pdf](https://github.com/minio/minio/files/466676/s3200get-go-new.pdf)
- With Go 1.6
  [s3200get-go-old.pdf](https://github.com/minio/minio/files/466677/s3200get-go-old.pdf)
- Its very clear that GC has become super efficient in Go 1.7 compared to Go 1.6. 
- In Go 1.6 build GC is the highest consumer, wherein its not in the picture at all with 1.7 build.

**Comment by hackintoshrao** [comment]
I think this test is good enough to understand the difference, this can be closed now. The primary focus was to understand difference in GC behavior, its clear from the above test.
