### ISSUE TITLE
[distributed] Tests: Validate mc operations when minio server instances go offline

### ISSUE THREAD

**Issue by krisis** [minio/minio#2452]
## Expected behaviour

When there is quorum (N/2+1) number of nodes available, all `mc` operations should work seamlessly. When more than quorum number of nodes fail, `mc` operations should fail with appropriate error message.
## Actual behaviour

To be tested

**Comment by harshavardhana** [comment]
Will test this tomorrow - re-assigned /me

**Comment by harshavardhana** [comment]
We have been testing this and there are bugs reported by @balamurugana and @krishnasrinivas  already. 

Is there anything that needs to be done with this bug? should we close this. Since this looks like a meta bug.

**Comment by harshavardhana** [comment]
> Is there anything that needs to be done with this bug? should we close this. Since this looks like a meta bug.

Closing this ESTALE.
