### ISSUE TITLE
[distributed] Perform CPU profiling on multi-node minio setup 

### ISSUE THREAD

**Issue by krisis** [minio/minio#2453]
## Expected behaviour
- [ ] Run operations on objects and buckets on a multi-node minio setup with CPU profiling enabled using `export MINIO_PROFILER=cpu`. 
- [ ] Run the same operations with block profiling enabled for better understanding of performance characteristics. `export MINIO_PROFILER=block`.

**Comment by krisis** [comment]
I expect to have run tests with CPU profiling enabled by 25th Aug.

**Comment by harshavardhana** [comment]
Going to run this tomorrow - re-assigned /me

**Comment by hackintoshrao** [comment]
Here is the result of the stress test with its memory profiling, 
- Setup Details 
  - 2 node setup with 4 drives. 
  - Minio 2 and Minio3 are the nodes with the server running. 
  - 200 parallel Get Object of 1GB is generated from Minio1 for each Minio2 and Minio3 ( 400 requests in total)
- Results 
  - Load test on both Minio2 and Minio3 finished in approximately 20 minutes. 
  - Memory usage peaked to 20GB 

CPU profile, 
- On Minio2 
  
  [410cpu2.pdf](https://github.com/minio/minio/files/508139/410cpu2.pdf)
- On Minio3
  
  [410cpu.pdf](https://github.com/minio/minio/files/508142/410cpu.pdf)

In both the CPU profiles the function `blake2b-simd.compressAVX2Loop` consumes over 55% CPU. 

Here is the listing of CPU time consumed by  `blake2b-simd.compressAVX2Loop`  , 

[out.txt](https://github.com/minio/minio/files/508143/out.txt)

**Comment by harshavardhana** [comment]
> Here is the listing of CPU time consumed by blake2b-simd.compressAVX2Loop ,
> 
> out.txt

// cc @fwessels - looks like G1 and G2 macros are using some good amount of time - while this was known that it would cause slowness a tiny bit.  Do you see anything special going on here? 

```
$ grep G1 out.txt 
     6.81s      6.81s    160:    G1
    16.47s     16.47s    172:    G1
    13.23s     13.23s    196:    G1
    13.31s     13.31s    216:    G1
    10.57s     10.57s    241:    G1
    10.84s     10.84s    262:    G1
    14.05s     14.05s    284:    G1
    14.48s     14.48s    303:    G1
    13.51s     13.51s    326:    G1
    10.88s     10.88s    349:    G1
    13.93s     13.93s    370:    G1
    13.42s     13.42s    390:    G1
    12.69s     12.69s    417:    G1
    13.87s     13.87s    437:    G1
    10.96s     10.96s    462:    G1
    13.65s     13.65s    481:    G1
    13.65s     13.65s    506:    G1
    13.28s     13.28s    525:    G1
    13.36s     13.36s    550:    G1
    10.30s     10.30s    571:    G1
    15.75s     15.75s    587:    G1
    16.20s     16.20s    599:    G1
    13.96s     13.96s    623:    G1
    12.88s     12.88s    643:    G1

```

```
$ grep G2 out.txt 
    27.33s     27.33s    161:    G2
    30.32s     30.32s    173:    G2
    28.62s     28.62s    197:    G2
    27.32s     27.32s    217:    G2
    29.05s     29.05s    242:    G2
    27.17s     27.17s    263:    G2
    26.74s     26.74s    285:    G2
    26.91s     26.91s    304:    G2
    26.55s     26.55s    327:    G2
    28.34s     28.34s    350:    G2
    27.61s     27.61s    371:    G2
    27.81s     27.81s    391:    G2
    27.82s     27.82s    418:    G2
    26.36s     26.36s    438:    G2
    27.90s     27.90s    463:    G2
    27.37s     27.37s    482:    G2
    26.47s     26.47s    507:    G2
    30.51s     30.51s    526:    G2
    26.03s     26.03s    551:    G2
    25.56s     25.56s    572:    G2
    28.86s     28.86s    588:    G2
    30.11s     30.11s    600:    G2
    25.03s     25.03s    624:    G2
    25.53s     25.53s    644:    G2
```

**Comment by harshavardhana** [comment]
Can we use new instructions that are added to Go with 1.7? 

### Assembler

For 64-bit ARM systems, the vector register names have been corrected to V0 through V31; previous releases incorrectly referred to them as V32 through V63.

For 64-bit x86 systems, the following instructions have been added: PCMPESTRI, RORXL, RORXQ, VINSERTI128, VPADDD, VPADDQ, VPALIGNR, VPBLENDD, VPERM2F128, VPERM2I128, VPOR, VPSHUFB, VPSHUFD, VPSLLD, VPSLLDQ, VPSLLQ, VPSRLD, VPSRLDQ, and VPSRLQ.

**Comment by fwessels** [comment]
@harshavardhana it is expected that G1 and G2 take the vast majority of time for BLAKE2b, there is no further way to optimize this, because these are the minimally essential computations that we need to do for BLAKE2b.

Regarding the new instructions for Go 1.7, I saw that these have been added indeed. They should help with BLAKE2b / lessen the need for arm2plan9s (although I am not quite sure that Golang 1.7 addresses all instructions that we need for BLAKE2b).

**Comment by harshavardhana** [comment]
> Regarding the new instructions for Go 1.7, I saw that these have been added indeed. They should help with BLAKE2b / lessen the need for arm2plan9s (although I am not quite sure that Golang 1.7 addresses all instructions that we need for BLAKE2b).

Yeah you are right they are not doing everything.

**Comment by harshavardhana** [comment]
This activity was finished by @balamurugana . Closing.
