### ISSUE TITLE
[distributed] Perform memory profiling on multi-node minio setup

### ISSUE THREAD

**Issue by krisis** [minio/minio#2455]
## Expected behaviour
- [x] Run operations on objects and buckets on a multi-node minio setup with memory profiling enabled using `export MINIO_PROFILER=mem`

**Comment by harshavardhana** [comment]
Running 60 parallel GetObjects() on 1G

```
real    11m53.784s
user    3m50.160s
sys     1m33.600s
```

**Comment by harshavardhana** [comment]
Running 70 parallel GetObject() on 1G

```
real    13m51.577s
user    4m28.168s
sys     1m49.616s
```

**Comment by balamurugana** [comment]
Uploaded same 4 MiB file created 1000 times on `minio2`.

minio1:
![minio1](https://cloud.githubusercontent.com/assets/629407/18653526/50d5c244-7e8f-11e6-83b4-31b9deb48b45.png)

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18653532/5d650ace-7e8f-11e6-918f-7caa476eab54.png)

**Comment by harshavardhana** [comment]
@balamurugana can you create larger files like in terms of 500MB to 10G ?

**Comment by balamurugana** [comment]
Uploaded same 77MiB file created 1000 times on `minio2`

minio1:
![minio1](https://cloud.githubusercontent.com/assets/629407/18654818/e789775e-7e98-11e6-906e-0825fb4095df.png)

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18654824/ef2ce5e0-7e98-11e6-93bb-93df1e7b510f.png)

**Comment by balamurugana** [comment]
Uploaded same 735.48MiB file created 1000 times on minio2
minio1:
![minio1](https://cloud.githubusercontent.com/assets/629407/18673275/0e376b2e-7f00-11e6-8073-3319f186c303.png)

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18673302/293c3c06-7f00-11e6-84ce-627aa676e851.png)

**Comment by balamurugana** [comment]
Upload of 77MiB file in parallel for 500 times with disabled cache.

minio1:
![minio1](https://cloud.githubusercontent.com/assets/629407/18685376/979c1a96-7f2c-11e6-8c41-cb5c75da1c39.png)

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18685377/9b297b18-7f2c-11e6-895e-453b25b6626c.png)

**Comment by balamurugana** [comment]
Upload of 736MiB file in parallel for 100 times with disabled cache.

minio1:
![minio1](https://cloud.githubusercontent.com/assets/629407/18690733/81ba343e-7f44-11e6-8a37-6aeea64c73bc.png)

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18690736/87a99fe2-7f44-11e6-8875-30396aae5308.png)

**Comment by balamurugana** [comment]
Download of 736MiB file in parallel for 100 times with disabled cache.

minio1:
![minio1](https://cloud.githubusercontent.com/assets/629407/18691368/0d9dc58a-7f48-11e6-9bac-ea3f09b36d68.png)

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18691376/18358708-7f48-11e6-871b-d7bdb1c20651.png)

**Comment by balamurugana** [comment]
10 Parallel list objects on minio2

minio1:
None

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18693075/d1ac3f3c-7f53-11e6-8918-240bd0fb8048.png)

**Comment by balamurugana** [comment]
Two Parallel copy of linux kernel source using `mc cp -r`
minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18735137/69eb2254-8030-11e6-93ea-071b661bc44f.png)

minio3:
![minio3](https://cloud.githubusercontent.com/assets/629407/18735138/6dc7627a-8030-11e6-9f71-aa4d611e28d1.png)

**Comment by balamurugana** [comment]
Parallel 300 `mc cp` command ran with 88MiB file copied to different unique object on both minio2 and minio3 (600 `mc cp` in total).

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18762497/d9283b56-80bd-11e6-9d4d-42bb14a8a063.png)

minio3:
![minio3](https://cloud.githubusercontent.com/assets/629407/18762503/dd9cf4d8-80bd-11e6-9412-fd2d2386c84f.png)

**Comment by balamurugana** [comment]
Two parallel 300 download of objects using `mc cat`

minio2:
![minio2](https://cloud.githubusercontent.com/assets/629407/18771246/2cc7b122-80f2-11e6-9fbe-9c08c58ea1cb.png)

minio3:
![minio3](https://cloud.githubusercontent.com/assets/629407/18771248/33015e1c-80f2-11e6-8bad-8c7531145575.png)

**Comment by hackintoshrao** [comment]
Here is the result of the stress test with its memory profiling, 
- Setup Details 
  - 2 node setup with 4 drives. 
  - Minio 2 and Minio3 are the nodes with the server running. 
  - 200 parallel Get Object of 1GB is generated from Minio1 for each Minio2 and Minio3 ( 400 requests in total)
- Results 
  - Load test on both Minio2 and Minio3 finished in approximately 20 minutes. 
  - Memory usage peaked to 20GB 

Memory profile, 

[391-mem.pdf](https://github.com/minio/minio/files/505541/391-mem.pdf)

**Comment by harshavardhana** [comment]
This is a great test @hackintoshrao and nice to really know the performance of the system.

**Comment by harshavardhana** [comment]
Was caching disabled? @hackintoshrao

**Comment by hackintoshrao** [comment]
@harshavardhana : Yes, caching was disabled.

**Comment by hackintoshrao** [comment]
Here are the mem profiles taken on both nodes under the same load as mentioned above, 
- Profile on Minio2 node 
  
  [4-10-mem2.pdf](https://github.com/minio/minio/files/507591/4-10-mem2.pdf)
- Profile on Minio3 node 
  
  [4-10-mem1.pdf](https://github.com/minio/minio/files/507593/4-10-mem1.pdf)

**Comment by harshavardhana** [comment]
This activity was finished by @balamurugana and @hackintoshrao
