### ISSUE TITLE
Please PGP sign Minio binary and source releases

### ISSUE THREAD

**Issue by bwerthmann** [minio/minio#2457]
## Expected behaviour

Minio Binary and Source Releases should be signed with a  PGP key in the strong set. 
## Actual behaviour

Binary releases are currently signed with a key which has no signatures. Source releases are not signed.

He's a nice guide for signing releases on GitHub: https://wiki.debian.org/Creating%20signed%20GitHub%20releases
## Minio version

`RELEASE.2016-07-13T21-46-05Z`
## System information

N/A

**Comment by harshavardhana** [comment]
> Actual behaviour
> 
> Binary releases are currently signed with a key which has no signatures. Source releases are not signed.
> 
> He's a nice guide for signing releases on GitHub: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

We don't release binaries on github, in-fact we do it through a private infrastructure where we do provide GPG signatures for validation - https://dl.minio.io/server/minio/release/linux-amd64/ 

Tagging on github is only for convenience and being able to track history.

**Comment by bwerthmann** [comment]
The source releases are at https://github.com/minio/minio/releases. We're asking that these source releases be signed.

The binary releases on the download site are indeed signed, the issue is that there is not a published public key to check the package signature against and the signing key has no signatures other than a self-signature.  Usually, the public key of the signing key is published in locations other than the download repo. Ideally, the package signing key should have signatures from other PGP users.

**Comment by harshavardhana** [comment]
> The binary releases on the download site are indeed signed, the issue is that there is not a published public key to check the package signature against and the signing key has no signatures other than a self-signature. Usually, the public key of the signing key is published in locations other than the download repo. Ideally, the package signing key should have signatures from other PGP users.

The published key is available at pgp.mit.edu - http://pgp.mit.edu/pks/lookup?op=vindex&search=0x12C74390F9AAC728

> The source releases are at https://github.com/minio/minio/releases. We're asking that these source releases be signed.

We are not planning to sign source releases, we will explore perhaps it in time.

**Comment by harshavardhana** [comment]
I see that since github already takes 'asc' file we can attach them to each releases as well.

**Comment by harshavardhana** [comment]
This has been done and we will follow this for all releases from now on. Thanks @bwerthmann.

**Comment by bwerthmann** [comment]
Thanks!  It would be nice if the public key of the signing key is published in a location controlled by Minio. Anyone can claim the `trusted@minio.io` identity and upload public key with a self signature.  Ideally, the package signing key should have signatures from other PGP users. This is sort of like running a public website with a self-signed certificate. What we have now is the ability to verify what a release was signed by a key, but we don't have a way to verify that key for `trusted@minio.io` is indeed owned by minio.

Here's a great article on signing / verifying: http://www.apache.org/info/verification.html

**Comment by harshavardhana** [comment]
> Thanks! It would be nice if the public key of the signing key is published in a location controlled by Minio. Anyone can claim the trusted@minio.io identity and upload public key with a self signature. Ideally, the package signing key should have signatures from other PGP users. This is sort of like running a public website with a self-signed certificate. What we have now is the ability to verify what a release was signed by a key, but we don't have a way to verify that key for trusted@minio.io is indeed owned by minio.

Good to know thanks for the tip.  Also i do see that we lack documentation regarding this so we will add it as well.

**Comment by jvoisin** [comment]
Any updates on the documentation front?

**Comment by harshavardhana** [comment]
We already sign the releases https://dl.minio.io/server/minio/release/linux-amd64/minio.asc  and source tags. Are you referring to anything else ? And what documentation are you looking for ? https://github.com/minio/cookbook/blob/master/docs/verifying-minio-binaries.md

**Comment by jvoisin** [comment]
The [download page]( https://minio.io/downloads.html#download-server-linux-x64 ) on minio's website doesn't mention cryptographic signatures at all.

It would be nice to have instructions like this instead:

```
wget https://dl.minio.io/server/minio/release/linux-amd64/minio{,.asc}
gpg --interactive --with-fingerprint --keyserver pgp.mit.edu --recv-keys 12C74390F9AAC728
gpg --verify minio.asc minio
chmod +x minio
./minio server /mnt/data
```

**Comment by harshavardhana** [comment]
> The download page on minio's website doesn't mention cryptographic signatures at all.

@jvoisin download page is minimal it is geared towards simpler instructions - for users who wish to validate it more, it is written as a separate doc.

**Comment by jvoisin** [comment]
Security shouldn't be optional :/

You can't reasonably expect people to guess that the project is indeed signing releases if it's not documented on the download page.

**Comment by harshavardhana** [comment]
> Security shouldn't be optional :/

Unfortunately, it is with PGP you can totally ignore to do those step anyways. 

> You can't reasonably expect people to guess that the project is indeed signing releases if it's not documented on the download page.

Most users who use this currently do this in an automated fashion by using ansible etc, downloading binary is just kept simple. So they follow the doc to automate it.

**Comment by jvoisin** [comment]
You can automate GPG verification too ♥
