### ISSUE TITLE
[distributed] `minio control locks` command to list and remove distributed locks

### ISSUE THREAD

**Issue by krisis** [minio/minio#2460]
## Expected behaviour
- [ ] Implement a command that allows administrator to list locks that are held in the cluster.
- [ ] Implement a command that allows administrator to remove locks (user discretion required).

**Comment by harshavardhana** [comment]
This fix would have a pending patch - https://github.com/minio/minio/pull/2223

**Comment by hackintoshrao** [comment]
adding tests to #2223 .

**Comment by harshavardhana** [comment]
@hackintoshrao - already has a rebased patch for distributed branch re-assigned.

**Comment by hackintoshrao** [comment]
https://github.com/minio/minio/pull/2584 fixes it.
