### ISSUE TITLE
[distributed] tests: Check if multi-node minio setup work in a docker environment

### ISSUE THREAD

**Issue by krisis** [minio/minio#2465]
## Expected behaviour

e.g, when all ports except 80 or 443 are closed. Multi-node version must continue to work.

**Comment by vadmeste** [comment]
I ran multiple minio servers, each minio in a different docker instance and it works as expected.

A simple idea of @krishnasrinivas about how to do that:
- Run multiple docker instances using this command: 
  `sudo docker run -it -v /home/vadmeste/:/root minio/distributed /bin/bash`, the docker will have access to the local system then to your minio binary.
- Check the ip address of these instances (`ifconfig`) to construct minio args
- Run several minio instances with the constructed arguments

**Comment by harshavardhana** [comment]
> I ran multiple minio servers, each minio in a different docker instance and it works as expected.
> 
> A simple idea of @krishnasrinivas about how to do that:
> 
> Run multiple docker instances using this command: sudo docker run -it -v /home/vadmeste/:/root minio/distributed /bin/bash, the docker will have access to the local system then to your minio binary.
> Check the ip address of these instances (ifconfig) to construct minio args
> Run several minio instances with the constructed arguments

ping @vadmeste - can you send an updated doc patch for Docker.md with the instructions on docker?

**Comment by vadmeste** [comment]
@harshavardhana, I've prepared a script but we need to publish a docker image first in Hub, can we do that ? will be minio-distributed-unstable for example

**Comment by harshavardhana** [comment]
@vadmeste patch wouls be for distributed branch

**Comment by harshavardhana** [comment]
> @harshavardhana, I've prepared a script but we need to publish a docker image first in Hub, can we do that ? will be minio-distributed-unstable for example

@vadmeste  you need to just send updated instructions in Docker.md we will validate this again after the merge into 'master' from distributed branch. 

We don't need to build docker image for unstable branches on our public hub.
