### ISSUE TITLE
provide example using aws-sdk for ruby

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2471]
Provide example code for ruby along the lines of https://docs.minio.io/docs/how-to-use-aws-sdk-for-php-with-minio-server for upload and download of files.

so that we can just provide the link to it when someone asks on gitter on how to use aws-sdk ruby with minio.

The RoR full blown example is not as minimal and to the point as our PHP example.

**Comment by GarimaKapoor** [comment]
done!

**Comment by pungoyal** [comment]
in case someone is looking for this: https://docs.minio.io/docs/how-to-use-aws-sdk-for-ruby-with-minio-server
