### ISSUE TITLE
bucket notification: setting the same configuration twice shouldn't work

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2472]

**Comment by harshavardhana** [comment]
Do you know the appropriate error message send by S3 in this situation?

**Comment by vadmeste** [comment]
```
<Error><Code>InvalidArgument</Code><Message>Configurations overlap. Configurations on the same bucket cannot share a common event type.</Message><ArgumentName>Event</ArgumentName><ArgumentValue>s3:ObjectRemoved:*, s3:ObjectRemoved:*</ArgumentValue><RequestId>FEB49A624F28D7B5</RequestId><HostId>3NgGx9BEOREo+KRBJKJ72VEh8wAfZSLNLYxwcB7YwG8b1M3X7ZmtqHXE1d2LfIMWcRSXidmHyts=</HostId></Error>
```

**Comment by vadmeste** [comment]
Are we willing to check overlapping rules here? because this issue could be treated with the same process.

**Comment by harshavardhana** [comment]
> Are we willing to check overlapping rules here? because this issue could be treated with the same process.

Yes we need to check for overlapping rules and reject them.

**Comment by harshavardhana** [comment]
@vadmeste are you working on this?

**Comment by vadmeste** [comment]
@harshavardhana, I didn't start on this yet

**Comment by harshavardhana** [comment]
Okay, will send a PR right now. @vadmeste
