### ISSUE TITLE
api: HealList() should return only objects that need healing.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2476]
returns all the objects, I think we can return only objects that needs healing as there is no use of returning all the objects. HealList will again have the random-io problem because of stat of xl.json, need to see how it can be fixed. -- @krishnasrinivas

**Comment by vadmeste** [comment]
To know if an object needs healing, we probably need to :
- heal all xl.json if possible (?)
- check the existence of all parts of the given object and check their checksums too

By the way, this operation could take some time. Also, we need to protect healing from uploading a new object with the same key name.

What do you think?

**Comment by krishnasrinivas** [comment]
@vadmeste you can use this to check if the object needs healing:
(taken from HealObject)

```
233         partsMetadata, errs := readAllXLMetadata(xl.storageDisks, bucket, object)  
234         if err := reduceErrs(errs, nil); err != nil {                              
235                 return toObjectErr(err, bucket, object)                            
236         }                                                                          
237                                                                                    
238         if !xlShouldHeal(partsMetadata, errs) {                                    
239                 // There is nothing to heal.                                       
240                 return nil                                                         
241         }
```

**Comment by krishnasrinivas** [comment]
it should be done under lock:

```
29         // Lock the object before healing.                                         
230         nsMutex.RLock(bucket, object)                                              
231         defer nsMutex.RUnlock(bucket, object)  
```
