### ISSUE TITLE
[distributed] isLocalStorage() should return true only if it matches what is given at --address

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2498]
@krishnasrinivas:

> @harshavardhana on m1 m2 m3, if we have two minio servers per machine (3:3 XL), that means for each minio servers isLocalStorage() returns true twice

@harshavardhana: 
Yes currently each network path is validated separately. We can fix that @krishnasrinivas - can you open a bug?

**Comment by krisis** [comment]
`IsLocalStorage()` returns true if the `ip` of `ip:/path/to/disk` is one of the network interfaces local to the node on which minio server is running.

e.g, `minio server --address ":9000" node1:/disk1 node2:/disk2 node1:/disk3 node2:/disk4`
For the minio server running on node1, `IsLocalStorage` would return true for `node1/disk1` and `node1/disk3`.
Similiarly for minio server running on node2, it would return true for `node2:/disk2` and `node/disk4`.
Are you seeing behaviour different than above?

**Comment by krisis** [comment]
Further, in the distributed version, `--address` flag is used to pass the common port on which minio server instance would be running on all the nodes participating in the cluster. It doesn't hold any IP address or hostname that is local to any of the nodes.

**Comment by krishnasrinivas** [comment]
@krisis sorry the bug is not clear, the underlying point of the bug is to provide a way to test distributed XL on the same machine (like for example creating lo:1 lo:2 ... interfaces with different IP addres)

**Comment by harshavardhana** [comment]
@krishnasrinivas  - i would think docker compose is a much nicer and better way to test distributed setup.  We can close this bug. 

```
$ cat ~/docker-compose/docker-compose.yml 
version: '2'
services:
  minio1:
    image: minio/minio:dist
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9001:9000"
    volumes:
      - /tmp/1:/export
    command: minio1:/export minio2:/export minio3:/export minio4:/export

  minio2:
    image: minio/minio:dist
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9002:9000"
    volumes:
      - /tmp/2:/export      
    command: minio1:/export minio2:/export minio3:/export minio4:/export

  minio3:
    image: minio/minio:dist
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9003:9000"
    volumes:
      - /tmp/3:/export      
    command: minio1:/export minio2:/export minio3:/export minio4:/export

  minio4:
    image: minio/minio:dist
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9004:9000"
    volumes:
      - /tmp/4:/export      
    command: minio1:/export minio2:/export minio3:/export minio4:/export    
```
