### ISSUE TITLE
[distributed] upload 1gb file twice stuck at 100%

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2500]
minio@minio1:~/vadmeste$ mc cp work/bigfiles/1024mb.bin myvadmeste/testbucket/
work/bigfiles/1024mb.bin:      1024.00 MB / 1024.00 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 12.88 MB/s 0

where mc and minio are idle

**Comment by vadmeste** [comment]
Actually, this is systematic if we upload a file twice

**Comment by vadmeste** [comment]
in this case, `mc rm myvadmeste/testbucket/1024mb.bin` doesn't work too.. it seems it is some locking issue

**Comment by harshavardhana** [comment]
> in this case, mc rm myvadmeste/testbucket/1024mb.bin doesn't work too.. it seems it is some locking issue

Yes over-write of a file has a locking issue during GetObject() initiated to populate the cache.

**Comment by harshavardhana** [comment]
Closing this as duplicate of - https://github.com/minio/minio/issues/2518
