### ISSUE TITLE
[dsitributed] : mc mb fails.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2505]
## Expected behaviour

`mc mb` to create buckt . 
## Actual behaviour

`mc: <ERROR> Unable to make bucket ‘rdis1/rao’. Server not initialized, please try again.`
## Steps to reproduce the behaviour
- First pulled the latest from distributed branch and build the binary.
- On Minio1:  `./minio server --address ":9999" minio1:/tmp/rao1 minio2:/tmp/rao1 minio1:/tmp/rao2 minio2:/tmp/rao2/`
- On Mino2:  `./minio server --address ":9999" minio1:/tmp/rao1 minio2:/tmp/rao1 minio1:/tmp/rao2 minio2:/tmp/rao2/`
- on Minio1: `mc config host add rdis1 http://65.19.167.91:9999 <AK> <SK>`  (From the output of the server start on the console)
## Minio version
- 38386510a41eca468e0bb05af8f092f94a6c97ad on distributed (latest at this point)
## System information

Minio Servers.

**Comment by krisis** [comment]
> mc: <ERROR> Unable to make bucket ‘rdis1/rao’. Server not initialized, please try again.

@hackintoshrao API requests wouldn't be served until the time quorum number of nodes have established connections between each other. This is expected behaviour. Was `mc mb` run after all the minio server instances were running?

**Comment by hackintoshrao** [comment]
There are 2 server instances as mentioned above, and both are running.

**Comment by harshavardhana** [comment]
Keys were missing on minio2
