### ISSUE TITLE
Server fails to start when checkPortAvailability can't open port #### (9000) on tcp6 when IPv6 is unavailable

### ISSUE THREAD

**Issue by text-editor** [minio/minio#2510]
## Expected behaviour

Minio launches, disregarding IPv6 if unavailable
## Actual behaviour

minio server --address127.0.0.1:9000 ~/minio  
FATA[0000] Port unavailable 9000                         cause=listen tcp6 :9000: socket: address family not supported by protocol
## Steps to reproduce the behaviour

**Launch minio on host without IPv6**
## Minio version

**Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2**
## System information

**Debian 8 Jessie
Kernel 2.6.32-042stab116.2
OpenVZ guest
IPv6 (and modules) unavailable**

**Comment by text-editor** [comment]
Thanks, that fixed it

**Comment by dreampuf** [comment]
still get that issue.

``` bash
root@cm1:/opt/minio · 06:26 AM Wed Aug 31 ·
!1020 # docker run -p 9000:9000 minio/minio /opt/minio/storage
Unable to find image 'minio/minio:latest' locally
latest: Pulling from minio/minio
357ea8c3d80b: Pull complete
52befadefd24: Pull complete
3c0732d5313c: Pull complete
fee55c622298: Pull complete
85155ee2fbc2: Pull complete
c51febe84798: Pull complete
52609aaab90b: Pull complete
2b794529dfa9: Pull complete
63182f445359: Pull complete
0041f5e0f9c7: Pull complete
166e914ae120: Pull complete
5d533c36fdb3: Pull complete
Digest: sha256:5d9b4321680c86875ac56472ca1c54ef9c685a6fba531c802b7adf6b2bae41be
Status: Downloaded newer image for minio/minio:latest
+ exec app server /opt/minio/storage
time="2016-08-31T06:34:33Z" level=fatal msg="Port unavailable 9000" cause="listen tcp6 :9000: socket: address family not supported by protocol"

root@cm1:/opt/minio · 06:34 AM Wed Aug 31 ·
!1021 # ll
total 22M
drwxr-xr-x   3 root root 4.0K Aug 31 06:14 ./
drwxr-xr-x. 10 root root 4.0K Aug 31 05:56 ../
-rwxr-xr-x   1 root root  22M Aug 21 02:47 minio*
drwxr-xr-x   2 root root 4.0K Aug 31 06:14 storage/

root@cm1:/opt/minio · 06:45 AM Wed Aug 31 ·
!1022 # cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)

```

**Comment by harshavardhana** [comment]
> 166e914ae120: Pull complete
> 5d533c36fdb3: Pull complete
> Digest: sha256:5d9b4321680c86875ac56472ca1c54ef9c685a6fba531c802b7adf6b2bae41be
> Status: Downloaded newer image for minio/minio:latest
> - exec app server /opt/minio/storage
>   time="2016-08-31T06:34:33Z" level=fatal msg="Port unavailable 9000" cause="listen tcp6 :9000: socket: address family not supported by protocol"
> 
> root@cm1:/opt/minio · 06:34 AM Wed Aug 31 ·
> !1021 # ll
> total 22M
> drwxr-xr-x   3 root root 4.0K Aug 31 06:14 ./
> drwxr-xr-x. 10 root root 4.0K Aug 31 05:56 ../
> -rwxr-xr-x   1 root root  22M Aug 21 02:47 minio*
> drwxr-xr-x   2 root root 4.0K Aug 31 06:14 storage/
> 
> root@cm1:/opt/minio · 06:45 AM Wed Aug 31 ·
> !1022 # cat /etc/redhat-release

Latest doesn't have this fix yet you should try "docker pull minio/minio:edge"
