### ISSUE TITLE
[distributed] mc ls hangs when one only minio is running

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2514]
In two server and four disks setup, if one only server is running, `mc ls myminio/` hangs.

Minio version:

```
Version: 2016-08-22T08:12:57Z
Release-Tag: DEVELOPMENT.2016-08-22T08-12-57Z
Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31
```

Command ran on m2.minio.io:

``` bash
minio server --address=:60000 m2.minio.io:/mnt/sdk1/bala/mydisk m2.minio.io:/mnt/sdi1/bala/mydisk   m3.minio.io:/mnt/sdk1/bala/mydisk  m3.minio.io:/mnt/sdi1/bala/mydisk
```

Test command:

```
mc ls  --debug myminio/
```

**Comment by harshavardhana** [comment]
> In two server and four disks setup, if one only server is running, mc ls myminio/ hangs.
> 
> Minio version:
> 
> Version: 2016-08-22T08:12:57Z
> Release-Tag: DEVELOPMENT.2016-08-22T08-12-57Z
> Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31
> Command ran on m2.minio.io:
> 
> minio server --address=:60000 m2.minio.io:/mnt/sdk1/bala/mydisk m2.minio.io:/mnt/sdi1/bala/mydisk   m3.minio.io:/mnt/sdk1/bala/mydisk  m3.minio.io:/mnt/sdi1/bala/mydisk
> Test command:
> 
> mc ls  --debug myminio/

Write locking quorum requires 'N+1' to be running i.e 3 disks out of 4.  During XL init a write lock is held before initializing 'format.json'  so you will see that the server to be not running.

**Comment by GarimaKapoor** [comment]
Closing it, discussed and mc will throw an appropriate error message.
