### ISSUE TITLE
[distributed] two different version of minio running together

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2515]
Its possible to run two different version of minio distributed version together.

minio version on `m2.minio.io`:

```
Version: 2016-08-22T08:12:57Z
Release-Tag: DEVELOPMENT.2016-08-22T08-12-57Z
Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31

```

minio version on `m3.minio.io`:

```
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```

**Comment by harshavardhana** [comment]
> minio version on m2.minio.io:
> 
> Version: 2016-08-22T08:12:57Z
> Release-Tag: DEVELOPMENT.2016-08-22T08-12-57Z
> Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31
> 
> minio version on m3.minio.io:
> 
> Version: DEVELOPMENT.GOGET
> Release-Tag: DEVELOPMENT.GOGET
> Commit-ID: DEVELOPMENT.GOGET

This is expected.. @balamurugana

**Comment by balamurugana** [comment]
Why is it expected behaviour if two different version behaves differently?

**Comment by harshavardhana** [comment]
Authentication happens with credentials to be same so the validation is proper at RPC layer. 

> Why is it expected behaviour if two different version behaves differently?

They won't behave differently `xl.json` is the sacrosanct entity in XL and we intend to carry forward all `xl.json` including current one and future versions forward supporting full backward compatibility.  There is no reason for it to error out if server versions are different. 

Each object has enough knowledge to handle the discrepancies between versions, if there is a bug it is not a bug here but somewhere else. 

In a production scenario some servers might not be upgraded at the same time during an upgrade session, we are not supposed to error out and take a downtime. It is a purposeful design.

**Comment by harshavardhana** [comment]
> They won't behave differently xl.json is the sacrosanct entity in XL and we intend to carry forward all xl.json including current one and future versions forward supporting full backward compatibility. There is no reason for it to error out if server versions are different.

If at all there is a breakage in backward compatibility then 'format.json' is the indicative authority.  if 'format.json' indicates that if at all the backward compatibility is broken - we won't run anyways.
