### ISSUE TITLE
[distributed]: mc cat hangs when any one of the minio servers is down

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2519]
```
minio server 169.254.0.1:/root/xl-exports/disk1 169.254.0.2:/rooxl-exports/disk2 169.254.0.3:/root/xl-exports/disk3 169.254.0.4:/root/xl-exports/disk4 169.254.0.5:/root/xl-exports/disk5 169.254.0.6:/root/xl-exports/disk6
```

this is a 3:3 setup

`mc cat myminio/testbucket/passwd` works fine when all 6 servers are up.

Ctrl-C any one of the server then do:
`mc cat myminio/testbucket/passwd` now hangs, but returns data as soon as the down server is up

**Comment by harshavardhana** [comment]
can you validate this again @krishnasrinivas ?

**Comment by krishnasrinivas** [comment]
Same issue as the one here https://github.com/minio/minio/issues/2569

**Comment by harshavardhana** [comment]
> Same issue as the one here #2569

can you validate this again @krishnasrinivas ?

**Comment by krishnasrinivas** [comment]
@harshavardhana still has issues, debugging.

**Comment by krishnasrinivas** [comment]
works now
