### ISSUE TITLE
[distributed] Error in disk path in arguments not detected

### ISSUE THREAD

**Issue by fwessels** [minio/minio#2540]
An opening slash was missing for the first server (10.193.15.145:**/**home/ec2-user/minio1/), server started fine but would not write any data (wheres the other servers just ran fine).

$ minio server --address ":12345" 10.193.15.145:home/ec2-user/minio1/ 10.195.139.19:/home/ec2-user/minio2/ 10.75.139.172:/home/ec2-user/minio3/ 10.194.130.45:/home/ec2-user/minio4/

Suggest to detect error, report back to user and not start server.

**Comment by harshavardhana** [comment]
Fixed by #2554
