### ISSUE TITLE
[distributed] http panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fwessels** [minio/minio#2541]
Below occured on server 3 (actually in inactive state)

[ec2-user@ip-10-75-139-172 ~]$ minio server --address ":12345" 10.193.15.145:/home/ec2-user/minio1/ 10.195.139.19:/home/ec2-user/minio2/ 10.75.139.172:/home/ec2-user/minio3/ 10.194.130.45:/home/ec2-user/minio4/

Endpoint:  http://10.75.139.172:12345  http://127.0.0.1:12345
AccessKey: 12W2ED3NBNJFDSR4KQ9I 
SecretKey: lXgvFuOnyWbuvQwadQNA9sTf7nlAm7sP5Msv1Ssa 
Region:    us-east-1

2016/08/23 14:59:17 http: panic serving 42.49.107.173:59327: runtime error: invalid memory address or nil pointer dereference
goroutine 133542 [running]:
net/http.(_conn).serve.func1(0xc820148000)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xbfd0e0, 0xc8200100d0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
crypto/tls.(_Conn).serverHandshake(0xc8203fa000, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/handshake_server.go:43 +0x4d6
crypto/tls.(_Conn).Handshake(0xc8203fa000, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:1035 +0x169
net/http.(_conn).serve(0xc820148000)
    /usr/local/go/src/net/http/server.go:1405 +0x382
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by vadmeste** [comment]
This is already fixed by @harshavardhana (https://github.com/minio/minio/commit/c39d3db7a036cdcce44ed020e10574edb2a466a7)

**Comment by fwessels** [comment]
Great, so closing this.

**Comment by mvanveen** [comment]
Hi I downloaded version `2016-08-21T02:44:47Z` today from the website and am running into this issue.  Is the workaround to just build from `master`?

Here's a trace:

```
2016/09/07 03:43:15 http: panic serving 127.0.0.1:57687: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc820350000)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/server.go:1389 +0xc1
panic(0xbee660, 0xc8200160d0)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:443 +0x4e9
crypto/tls.(*Conn).serverHandshake(0xc820452300, 0x0, 0x0)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/tls/handshake_server.go:43 +0x4d6
crypto/tls.(*Conn).Handshake(0xc820452300, 0x0, 0x0)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/tls/conn.go:1035 +0x169
net/http.(*conn).serve(0xc820350000)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/server.go:1405 +0x382
created by net/http.(*Server).Serve
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/server.go:2137 +0x44e
2016/09/07 03:43:18 http: panic serving 127.0.0.1:57688: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc820350100)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/server.go:1389 +0xc1
panic(0xbee660, 0xc8200160d0)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:443 +0x4e9
crypto/tls.(*Conn).serverHandshake(0xc820452600, 0x0, 0x0)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/tls/handshake_server.go:43 +0x4d6
crypto/tls.(*Conn).Handshake(0xc820452600, 0x0, 0x0)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/tls/conn.go:1035 +0x169
net/http.(*conn).serve(0xc820350100)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/server.go:1405 +0x382
created by net/http.(*Server).Serve
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/server.go:2137 +0x44e
```

**Comment by krishnasrinivas** [comment]
@mvanveen yes, till the next release is made you can build from master

**Comment by sebastiaanluca** [comment]
I'm getting this error using the latest version, fresh Ubuntu VM. Anything I can provide to help debug this issue?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4b6d8c]
```

**Comment by harshavardhana** [comment]
Please open a new issue @sebastiaanluca .  Just provide the entire stack trace in the github issue and also your current minio version.
