### ISSUE TITLE
Bug: Minio server fails to start if notification service configuration are added incorrectly.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2547]
## Expected behaviour

Minio server should start giving error log about wrong/in-correct configuration of notification service source.
## Actual behaviour

Currently it says about notification service configured being unable to connect and Minio server does not start. 
## Steps to reproduce the behaviour

I have enabled notify option and RabbitMQ URL was added, which was not running. 

```
 "notify": {
        "amqp": {
            "1": {
                "enable": true,
                "url": "amqp://minio:minio@192.168.1.11:5672/",
                "exchange": "minio",
                "routingKey": "minio",
                "exchangeType": "direct",
                "mandatory": false,
                "immediate": false,
                "durable": false,
                "internal": false,
                "noWait": false,
                "autoDeleted": false
            }
        },
```
## Minio version

  2016-08-21T02:44:47Z
## System information

OSX El Capitan

**Comment by harshavardhana** [comment]
This is fixed in distributed repo, closing.
