### ISSUE TITLE
How can I set Port - including for Docker container

### ISSUE THREAD

**Issue by jonniedarko** [minio/minio#2550]
I'm looking to run the docker container specifically on another port. I see in the `how-to` for multiple servers you can set the address, is their away to just set just the port? maybe an environment variable already exists like `MINIO_PORT`

**Comment by krishnasrinivas** [comment]
@jonniedarko 
- do you want minio to listen on a different port? if so there is no env var to set it
  or
- do you want to map a different port port on the host?
  that can be done by `docker run -p 80:9000 minio/minio`

**Comment by jonniedarko** [comment]
@krishnasrinivas I want to set it to a different port - I currently have it mapped to a different port but I still need to use 9000 within other containers when using links in composer file

**Comment by krishnasrinivas** [comment]
@jonniedarko can you explain the situation more?
because if minio is running at 9000 inside its own container it will not affect processes of other containers.

**Comment by jonniedarko** [comment]
We are trying to match our test/rc/live servers as much as possible and
they all run on a different port. I guess it's not the biggest deal except I would of expected setting the port to be included as an option, it is usually included in basic config options. A lot of other services run on that port (9000) by default including xdebug and we are just looking to keep our config as clear as possible. We also usually try to map ports to the same ports where possible with docker

**Comment by krishnasrinivas** [comment]
if i understand correctly you have the same test container running many processes (including xdebug running on 9000) and hence you want the port to be configurable?

**Comment by jonniedarko** [comment]
yes, while Mino is it its own container and I can access the Minio UI
though whatever port I map, our application (in another container) still
needs to reference port 9000 (which I'm surprised about, I would of thought
other docker containers would use the mapped port, but they don't seem to)

**Comment by krishnasrinivas** [comment]
Can you try if this works for you:
`docker run minio/minio --address :80 /export`

**Comment by jonniedarko** [comment]
That works 👍

**Comment by harshavardhana** [comment]
> That works

@jonniedarko are there any other issues that you see with docker minio?

**Comment by krishnasrinivas** [comment]
> that works

you can close this issue then.
