### ISSUE TITLE
Cannot create Folder inside bucket using Mino web UI or Cyber Duck

### ISSUE THREAD

**Issue by jonniedarko** [minio/minio#2551]
## Expected behaviour

Should have the ability to create a folder using the Web UI Or a s3 compatiable program like Cyber Duck to repersent keys with `/` e.g. `s3://my-bucket/namespace1/subnamespace1/myfile
## Actual behaviour

When I try to create or upload a folder with cyberduck I get the error:

```
Object name contains unsupported characters. Unsupported characters 
are `^*|\". Please contact your web hosting service provider for assistance.
```

So I tried to rename `myfile`  `namespace1/subnamespace1/myfile` but it uploaded it as `namespace1:subnamespace1:myfile`. This also occures with the Web UI and I can see no ability to create a folder using the Web UI

It does however work as expected when using the AWS SDK (php in my case)
## Minio version

using the latest Minio Docker image

**Comment by harshavardhana** [comment]
> Should have the ability to create a folder using the Web UI Or a s3 compatiable program like Cyber Duck to repersent keys with / e.g. `s3://my-bucket/namespace1/subnamespace1/myfile

You are not allowed to create an empty directory on Minio, you can upload an object on a prefix.

**Comment by jonniedarko** [comment]
@hackintoshrao I understand you can't create an empty directory but how does one upload a object on a prefix using the web UI or a tool like cyber duck

**Comment by harshavardhana** [comment]
> @hackintoshrao I understand you can't create an empty directory but how does one upload a object on a prefix using the web UI or a tool like cyber duck

Cyberduck and Mountainduck made some fixes recently to be inter-operable with Minio - can you paste your version? 

AFAIK you just have to select a bucket and upload a file and aforementioned prefixes are already created by Cyberduck or no?

**Comment by jonniedarko** [comment]
@harshavardhana the version of cyber duck I have is `Version 5.1.0 (20872)` which should be the most recent. Sorry if this seems like a stupid question but what do you mean exactly by a prefix? Is this an option on Cyber Duck that I am just not seeing? And is it an option on the Minio Web UI? Or do you mean in the actual file name? As I mentioned Originally I did try renaming my file with `/`'s contained in the name, and this was replaced with `:`

**Comment by harshavardhana** [comment]
> the version of cyber duck I have is Version 5.1.0 (20872) which should be the most recent. Sorry if this seems like a stupid question but what do you mean exactly by a prefix? Is this an option on Cyber Duck that I am just not seeing? And is it an option on the Minio Web UI? Or do you mean in the actual file name? As I mentioned Originally I did try renaming my file with /'s contained in the name, and this was replaced with :

In the WebUI you are talking about is Minio Browser here?

**Comment by harshavardhana** [comment]
I think i understand the problem now you could use - https://docs.minio.io/docs/minio-client-quickstart-guide to upload these files for the time being.

**Comment by jonniedarko** [comment]
@hackintoshrao Thank you :+1: but I'm actually just using a php script at present until a better solution is available, We would would like the UI to support if possible at some stage, would make it easier for our non-technical QA's to test it

**Comment by dkocher** [comment]
Cyberduck will attempt to create placeholder files that denote directories ending with `/` to allow having a 'directory' in the browser without any keys 'inside'.

```
PUT /cd-4nvli/placeholder/ HTTP/1.1
Date: Thu, 25 Aug 2016 20:14:51 GMT
Expect: 100-continue
Content-Type: application/x-directory
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Host: play.minio.io
x-amz-date: 20160825T201451Z
Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20160825/us-east-1/s3/aws4_request,SignedHeaders=content-type;date;expect;host;x-amz-content-sha256;x-amz-date,Signature=7e8aa03d8eb269ad7adab5fd2db63791859c81a9d04b2885776f8bfb404ee82b
Content-Length: 0
Connection: Keep-Alive
User-Agent: Cyberduck/5.1.0.20872 (Mac OS X/10.12) (x86_64)

```

**Comment by harshavardhana** [comment]
> Cyberduck will attempt to create placeholder files that denote directories ending with / to allow having a 'directory' in the browser without any keys 'inside'.
> 
> PUT /cd-4nvli/placeholder/ HTTP/1.1
> Date: Thu, 25 Aug 2016 20:14:51 GMT
> Expect: 100-continue
> Content-Type: application/x-directory
> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> Host: play.minio.io
> x-amz-date: 20160825T201451Z
> Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20160825/us-east-1/s3/aws4_request,SignedHeaders=content-type;date;expect;host;x-amz-content-sha256;x-amz-date,Signature=7e8aa03d8eb269ad7adab5fd2db63791859c81a9d04b2885776f8bfb404ee82b
> Content-Length: 0
> Connection: Keep-Alive
> User-Agent: Cyberduck/5.1.0.20872 (Mac OS X/10.12) (x86_64)

Yes we don't support than in Minio, empty directories or objects ending with '/' are not allowed.

**Comment by dkocher** [comment]
You will need to support this if you want your implementation to be S3 compatible. Refer to [Object Keys](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys).

**Comment by harshavardhana** [comment]
> You will need to support this if you want your implementation to be S3 compatible. Refer to Object Keys.

You are right @dkocher.  

We considered this as bad practice since empty directories are nothing but 0 byte objects with '/' at the end. For example when an object is uploaded at '/bucket/prefix/object' the 'prefix/' is automatically associated with the said 'object'. Since the keys are flat the sense of a common prefix among objects is just at the API level be it '/' or otherwise.  One more reasoning is to avoid a separate PUT operation of 0 byte object when indeed the attempt is to upload real objects with larger sizes. 

The choice helped us keep things simple and predictable. 

But technical issues aside we also agree this is supported by large number of tools/applications out there,  which are already using this feature of S3 and it would be harder to change the behavior now.

We will see how this issue can be solved.

**Comment by krishnasrinivas** [comment]
one workaround is if we get a PUT on an object with trailing "/" for ex
bucket = testbucket, object = "a/b/c/" we can create a 0-byte object "a/b/c/d/placeholder" though not an elegant solution it will fix the UX problem of creating a directory.

**Comment by harshavardhana** [comment]
Closing this as known issue but won't be fixed.  We will send an upstream patch for Cyberduck to make it cleanly work by handling prefixes properly just like how https://github.com/minio/mc does.

**Comment by Andrey198** [comment]
Good day.

> We will send an upstream patch for Cyberduck

When?

Thanx!

**Comment by harshavardhana** [comment]
This should be fixed in current master @jonniedarko @Andrey198 @dkocher

**Comment by jonniedarko** [comment]
:+1:

**Comment by keithballdotnet** [comment]
You mean with the latest it is now possible to create empty folders again?

**Comment by harshavardhana** [comment]
It is allowed in a manner where cyberduck won't complain. It doesn't really create a folder yet but it doesn't return any error if the object has a / at the end.

**Comment by jonniedarko** [comment]
What about the Minio UI, How can I upload files there to a particular
folder path? is that supported

**Comment by harshavardhana** [comment]
Not on Minio UI @jonniedarko

**Comment by u007** [comment]
realize cant start object name with /
example /xxx/file.jpg fails, xxx/file.jpg works

**Comment by harshavardhana** [comment]
> realize cant start object name with /
> example /xxx/file.jpg fails, xxx/file.jpg works

Yes you cannot the path resource is already `<bucket_name>/<object_name>`  - '/' is a delimiter.

**Comment by u007** [comment]
would be nice if the error shows more friendlier on the possible issue in the object name.
Unsupported characters are `^*|\" isnt indicating it

**Comment by harshavardhana** [comment]
> would be nice if the error shows more friendlier on the possible issue in the object name.
> Unsupported characters are `^*|" isnt indicating it

What would be a friendlier message? @u007 - happy to incorporate if you have something in mind.

**Comment by u007** [comment]
Object name may not start with prefix /
maybe we add this validation before checking on other validations

**Comment by harshavardhana** [comment]
> Object name may not start with prefix /

Well that is not the only requirement @u007 in-fact unsupported characters are indeed "^*|" as well.  We could potentially differentiate these errors.. 

Will open a bug and see how this can be fixed properly.

**Comment by u007** [comment]
alright, its up to you, maybe you can check both condition at one validation and comes out an error that prompt a generic error for both condition
