### ISSUE TITLE
docker documentation on hub.docker.com

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2552]
The documentation see here: https://hub.docker.com/r/minio/minio/ should have minio-docker related instructions. It currently has taken the default README.md file of minio.

i.e it should display the content that we have at https://docs.minio.io/docs/minio-docker-quickstart-guide

**Comment by harshavardhana** [comment]
> The documentation see here: https://hub.docker.com/r/minio/minio/ should have minio-docker related instructions. It currently has taken the default README.md file of minio.

Let me check how to edit and add a custom README.md

**Comment by harshavardhana** [comment]
Updated the docker.md on hub page, will see if hub updates the README.md again upon a new commit.
