### ISSUE TITLE
[distributed] mc command hangs if one of the node is down

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2569]
Minio Version:

```
Version: 2016-08-29T11:37:19Z
Release-Tag: DEVELOPMENT.2016-08-29T11-37-19Z
Commit-ID: 5b5938cd94f6124eaef8abc48fb1f1eef76315bb
```

Reproducer:
1. start minio in all nodes like `MINIO_CACHE_SIZE=0 ./minio server m1:/mnt m2:/mnt m3:/mnt m4:/mnt`
2. stop one of the minio by `Ctrl-C`
3. run `mc ls myminio` . This hangs.

**Comment by balamurugana** [comment]
This bug appears when start minio expect in one node like `./minio server m1:/mnt m2:/mnt m3:/mnt m4:/mnt` where no minio is running on `m4`.

Once minio is started in `m4`, things are started working.

**Comment by fwessels** [comment]
I am looking at this one, found the issue and correcting it
