### ISSUE TITLE
XL: Stress test: `exec-concurrent "TestListPartiallyUploaded"` hangs.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2570]
## Expected behaviour

To pass.
## Actual behaviour

Hangs.
## Steps to reproduce the behaviour

`./exec-concurrent "TestListPartiallyUploaded"`
## Minio version

Latest master at 8484d1c0ca3b1a0a0d2b832fd2ae12fd5aeeaba6 . 
## System information

Minio2 server.

**Comment by harshavardhana** [comment]
> System information
> 
> Minio2 server.

Is this a single node XL?

**Comment by hackintoshrao** [comment]
Its a single node XL.

**Comment by harshavardhana** [comment]
> Its a single node XL.

Can you test this again with latest master HEAD?

**Comment by hackintoshrao** [comment]
Will test.

**Comment by hackintoshrao** [comment]
Fails on current master. Ran the test without any concurrency.

**Comment by hackintoshrao** [comment]
Running the test just once close to 20 seconds to finish.

**Comment by harshavardhana** [comment]
> Running the test just once close to 20 seconds to finish.

cannot understand what this means?

**Comment by hackintoshrao** [comment]
Previously was running the test at a concurrency level of 100, now run it without any concurrency, it took around 20 seconds to finish . When I increased the concurrency level to 10, it tool  `1m50.045s` for the test to finish. Will profile and investigate why this operation is painfully slow.

**Comment by harshavardhana** [comment]
> Previously was running the test at a concurrency level of 100, now run it without any concurrency, it took around 20 seconds to finish . When I increased the concurrency level to 10, it tool 1m50.045s for the test to finish. Will profile and investigate why this operation is painfully slow.

Is the hang reproducible?  - if it's really about being slow and no hang then open a new bug for optimization of ListMultipartUploads().

**Comment by hackintoshrao** [comment]
> Is the hang reproducible? - if it's really about being slow and no hang then open a new bug for optimization of ListMultipartUploads(). 

Yes, I'm able to consistently reproduce. When the concurrency of the load goes it gets slower and slower, so slow that it looks like its inactive. 

Yes, I'll open a new bug on optimization of ListMultipartUploads .

**Comment by hackintoshrao** [comment]
Opened a new issue https://github.com/minio/minio/issues/2591 on `ListMultipartUpload` optimization.
