### ISSUE TITLE
[distributed] list+upload in parallel, an uploaded file becomes a directory 

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2573]
Run this in a terminal:
`while true; do mc ls myminio1/testbucket/; done | grep "/$"`

And this in another terminal:
`while true; do mc cp -r file myminio2/testbucket/; done`

After a while, `testbucket/file/` (as a directory) will show up in the terminal that is doing the continuous listing.

**Comment by harshavardhana** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel
- A process writes a new object to Amazon S3 and immediately lists keys within its bucket. Until the change is fully propagated, the object might not appear in the list.
- A process replaces an existing object and immediately attempts to read it. Until the change is fully propagated, Amazon S3 might return the prior data.
- A process deletes an existing object and immediately attempts to read it. Until the deletion is fully propagated, Amazon S3 might return the deleted data.
- A process deletes an existing object and immediately lists keys within its bucket. Until the deletion is fully propagated, Amazon S3 might list the deleted object.

**Comment by harshavardhana** [comment]
// cc @vadmeste - for more investigation.

**Comment by vadmeste** [comment]
Looks like the reason is clear. ListObjects doesn't hold any mutex. Putting an object (actually replacing) will remove first the directory associated to the object in the backend (e.g export1/testbucket/object/) and create new one. I didn't read the code actually, I just observed the backend.

**Comment by harshavardhana** [comment]
> Looks like the reason is clear. ListObjects doesn't hold any mutex. Putting an object (actually replacing) will remove first the directory associated to the object in the backend (e.g export1/testbucket/object/) and create new one. I didn't read the code actually, I just observed the backend.

We need to investigate this further on why the Rename() of a directory is not deemed as atomic.

**Comment by vadmeste** [comment]
First, this bug is easily reproducible if we test with a code from minio-go examples instead of mc. 

Now the result of my findings:
- I noticed that listing can miss an object if we are uploading another object of the same name in parallel. The reason is that we are making a backup of the old object by renaming it before moving the new uploaded one from tmp to its new location. Listing objects is not using any synchronization primitives.
- For the bug of the current issue, the reason is similar. ListDir detects the object but isLeaf can miss it later. isLeaf relies on xl.isObject() which returns false even if the object directory is not found (most likely because we are doing a backup as described in the first point).

What do you think?

**Comment by harshavardhana** [comment]
> I noticed that listing can miss an object if we are uploading another object of the same name in parallel. The reason is that we are making a backup of the old object by renaming it before moving the new uploaded one from tmp to its new location. Listing objects is not using any synchronization primitives.

This a correct behavior object storage only provides certain levels of consistency, this is the same as doing Stat() within a Readdir() call on POSIX.  An file/object can get deleted but the Dirent cache might have the entry and upon a "ENOENT" you can choose to ignore such errors.

> For the bug of the current issue, the reason is similar. ListDir detects the object but isLeaf can miss it later. isLeaf relies on xl.isObject() which returns false even if the object directory is not found (most likely because we are doing a backup as described in the first point).

To fix this issue we have to do 2 Stat() operations one to tell if `xl.json` doesn't exist and another to tell if the parent directory for `xl.json` doesn't exist.  This can be written like a fallback in case if the first attempt fails with `xl.json` .

**Comment by vadmeste** [comment]
> To fix this issue we have to do 2 Stat() operations one to tell if xl.json doesn't exist and another to tell if the parent directory for xl.json doesn't exist. This can be written like a fallback in case if the first attempt fails with xl.json .

yes, but this is not enough.. things could change between the two Stat() calls. To avoid this, can't we just prepare the new object in tmp, and do one rename() call in the final stage if everthing is successful?

**Comment by harshavardhana** [comment]
> yes, but this is not enough.. things could change between the two Stat() calls. To avoid this, can't we just prepare the new object in tmp, and do one rename() call in the final stage if everthing is successful?

New object is already prepared in tmp if not its a bug.   There is only so much you can do without holding lock.

**Comment by GarimaKapoor** [comment]
@vadmeste what is the status of this issue?

**Comment by harshavardhana** [comment]
Closing this to be an expected behavior in the current code,  will re-open if at all this issue becomes important.
