### ISSUE TITLE
[distributed] doc: write distributed quickstart/complete guide

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2574]

**Comment by zet4** [comment]
Any update on this? Really want to try out the distributed mode but no idea how to use it.

**Comment by harshavardhana** [comment]
> Any update on this? Really want to try out the distributed mode but no idea how to use it.

It is currently in a separate branch, we will be merging it soon.

**Comment by nitisht** [comment]
Documentation merged with #3342

**Comment by harshavardhana** [comment]
Closing .. merged in #3342
