### ISSUE TITLE
[distributed]  `The specified bucket does not exist` shows up sometimes (rare)

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2579]
```
vadmeste@xps-u:~/work/gospace/src/github.com/minio/minio (distributed) 
$ mc rm --recursive --force myminio4/testbucket/ 
mc: <ERROR> Unable to list ‘http://172.17.0.5:9000/testbucket/’. The specified bucket does not exist 
vadmeste@xps-u:~/work/gospace/src/github.com/minio/minio (distributed)
$ mc rm --recursive --force myminio4/testbucket/
Removed ‘myminio4/testbucket/0’. 
Removed ‘myminio4/testbucket/1’.
...
```

This is a rare bug, I play with 8 nodes + small files

**Comment by vadmeste** [comment]
This happened for me with ls, cp commands, but I guess with all other commands too

**Comment by harshavardhana** [comment]
> This happened for me with ls, cp commands, but I guess with all other commands too

This issue is related to the problem of server disconnection, this will be fixed once #2561 is fixed.

**Comment by harshavardhana** [comment]
> This happened for me with ls, cp commands, but I guess with all other commands too

In situations like this you should also see what is server is reporting as it would have printed "connection is shutdown"

**Comment by harshavardhana** [comment]
can you validate this again with latest distributed HEAD @vadmeste ?

**Comment by vadmeste** [comment]
@harshavardhana, I tested the script again for about an hour and I didn't have any error. Should be fixed.
