### ISSUE TITLE
XL: ListMultipartUpload optimzation.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2591]
During stress tests `ListMultipartUpload` is found to be unusually slow. More details on the bug and info on reproducing can be found here https://github.com/minio/minio/issues/2570 . 

Profiling and investigating the cause for it.

**Comment by vadmeste** [comment]
@hackintoshrao, tests are consuming too much resources (most likely in generating random data), probably that's why minio was looking like idle

**Comment by vadmeste** [comment]
@hackintoshrao, I replaced random buffer generation (crand.Reader) with a buffer of 1Mb, 1000 parallel TestListPartiallyUploaded takes 18 seconds to finish in my laptop.

**Comment by harshavardhana** [comment]
Ah this problem we have seen this before crand.Reader

**Comment by harshavardhana** [comment]
@hackintoshrao - moved this as non bug out of milestone, please confirm @vadmeste findings.

**Comment by hackintoshrao** [comment]
Fixing the `crand.Reader` to `bytes.Repeat` and running the tests again. Thanks @vadmeste .
