### ISSUE TITLE
cli: Add distributed server example `minio server` example template

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2602]
```
  5. Start minio server on 12 disks while ignoring two disks for initialization.
      $ minio server --ignore-disks=/mnt/export1/backend,/mnt/export2/backend /mnt/export1/backend \
          /mnt/export2/backend /mnt/export3/backend /mnt/export4/backend /mnt/export5/backend /mnt/export6/backend \
          /mnt/export7/backend /mnt/export8/backend /mnt/export9/backend /mnt/export10/backend /mnt/export11/backend \
          /mnt/export12/backend
```

**Comment by vadmeste** [comment]
Looks like it is already existing in the distributed branch

`
6. Start minio server with 4 remote disks on all remote nodes. You need to execute the same command on all nodes
     192.168.1.11, 192.168.1.12, 192.168.1.13 and 192.168.1.14.
      $ export MINIO_ACCESS_KEY=minio
      $ export MINIO_SECRET_KEY=miniostorage
      $ minio server 192.168.1.11:/mnt/export1/backend 192.168.1.12:/mnt/export1/backend \
          192.168.1.13:/mnt/export1/backend 192.168.1.14:/mnt/export1/backend
`

**Comment by harshavardhana** [comment]
> Looks like it is already existing in the distributed branch
> 1. Start minio server with 4 remote disks on all remote nodes. You need to execute the same command on all nodes 192.168.1.11, 192.168.1.12, 192.168.1.13 and 192.168.1.14. $ export MINIO_ACCESS_KEY=minio $ export MINIO_SECRET_KEY=miniostorage $ minio server 192.168.1.11:/mnt/export1/backend 192.168.1.12:/mnt/export1/backend \ 192.168.1.13:/mnt/export1/backend 192.168.1.14:/mnt/export1/backend

oh nice. Closing
