### ISSUE TITLE
Unable to use signed URL

### ISSUE THREAD

**Issue by iscy** [minio/minio#2613]
## Expected behaviour

Signed URLs, like these:
https://s3.amazonaws.com/bucket/the_file.jpg?AWSAccessKeyId=ACCESSKEY&Expires=1472832666&Signature=mXeDQhvsZlXw7DGUmagmlJazdyY%3D

Should be able to work until the "Expires" time is out. Right now, this returns 'access denied' as 'bucket' is private and the signed URL doesn't seem to work with minio.
## Actual behaviour

The file should be accessible until the signed url expires.
## Steps to reproduce the behaviour
1. Setup minio
2. Create a bucket (do not assign any policy to it)
3. Upload a file
4. Use the AWS SDK (or JETS3T) to generate the signed URL
5. Access the URL using curl or your browser
## Minio version

Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2

**Comment by harshavardhana** [comment]
@iscy you are using signature v2 style signed URLs. Minio only supports signature v4.

**Comment by harshavardhana** [comment]
@iscy you can use - https://docs.minio.io/docs/minio-client-complete-guide#share and also please do share your code we can help you get the signature v4 working as well. 

Thanks

**Comment by iscy** [comment]
Thanks for the pointer. The SDK was definitely using v2 requests instead of v4. Once switched to v4, the requests made it and worked properly.

**Comment by harshavardhana** [comment]
> Thanks for the pointer. The SDK was definitely using v2 requests instead of v4. Once switched to v4, the requests made it and worked properly.

Thanks for confirming @iscy
