### ISSUE TITLE
[distributed] Re-uploading an interrupted upload with a different object, causes mc to fail

### ISSUE THREAD

**Issue by donatello** [minio/minio#2615]
## Expected behaviour

mc fails to upload to an object, if a previous attempt (with a different object) was interrupted.
## Actual behaviour

mc should upload the new object successfully.
## Steps to reproduce the behaviour
1. Upload a large file using `mc cp`, and hit `Ctrl+C` to interrupt it - (1.5 GB file in my test).
2. Upload a different file (100MB in my test) to the same object using `mc cp`, you get something similar to:

```
mc: <ERROR> Failed to copy ‘/tmp/test’. Unexpected number of parts found Want 3, Got 15
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume cwQZMpRF’
```
## Minio version

```
Version: 2016-09-03T02:22:11Z
Release-Tag: DEVELOPMENT.2016-09-03T02-22-11Z
Commit-ID: 0098879c6acc743f5d247352701993563f327634
```
## System information

Linux.

**Comment by harshavardhana** [comment]
@donatello  This is not a server issue. 

This is returned by 'mc' when total parts previously uploaded is not same as the one being uploaded. This needs to be relaxed on the minio-go.  Can you open a bug against minio-go instead?

**Comment by donatello** [comment]
Ok, closing this as it is not a server issue.
