### ISSUE TITLE
docs: Discouraging usage of X-Amz-Meta

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2616]
We need to document & educate our users not to use `X-Amz-Meta`  API request.

**Comment by harshavardhana** [comment]
what is the status of this @koolhead17 ?

**Comment by koolhead17** [comment]
It is in list of items for this week. 😄

**Comment by koolhead17** [comment]
I have added it to our FAQ, this can be closed.

**Comment by harshavardhana** [comment]
> I have added it to our FAQ, this can be closed.

s this FAQ public?

**Comment by koolhead17** [comment]
Not yet, working on same with @GarimaKapoor

**Comment by harshavardhana** [comment]
> Not yet, working on same with @GarimaKapoor

Closing..
