### ISSUE TITLE
Presigned url generated from amazon AWS SDK for .net does not work

### ISSUE THREAD

**Issue by Vidarls** [minio/minio#2620]
## Expected behaviour

When using amazons official .net SDK to generate a presigned url for minio, I expect that presigned url to work.
## Actual behaviour

Getting access denied, (and the generated URL is quite different from what the minio `mc.exe` tool generates.
## Steps to reproduce the behaviour

Code for simple repro:

https://gist.github.com/Vidarls/206fe2efb3b2ef93dfc33c9a891ecaf8

(Included the output from the dotnet lib minio has published on github (also not working, but might be unrelated, and the official `mc.exe` tool that works as expected.
## Minio version

```
Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2
```
## System information

Minio server running on windows 10, using amazon AWS sdk for S3 version 3.1.9

**Comment by Vidarls** [comment]
Update: Tested with official amazon CLI tool on windows. Also works as expected.

**Comment by hackintoshrao** [comment]
Update: @Vidarls validated that the it works fine with Minio .NET library, should validate with AWS .NET library.

**Comment by harshavardhana** [comment]
@Vidarls if would be easier if you could paste a sample program that was used to generate the presigned URL and also 'presignedURL' itself to look for differences. 

Another thing to validate at your end is if you are using Signature V4 ? because Minio only supports Signature V4.

**Comment by harshavardhana** [comment]
> @Vidarls if would be easier if you could paste a sample program that was used to generate the presigned URL and also 'presignedURL' itself to look for differences.

My bad @Vidarls just saw the code.

**Comment by harshavardhana** [comment]
I am able to use the latest master here and not able to reproduce the problem 

```
$ wget "http://localhost:9000/testbucket/1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=USWUXHGYZQYFYFFIT3RE%2F20160905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160905T160956Z&X-Amz-Expires=1000&X-Amz-SignedHeaders=host&X-Amz-Signature=388c111773b459f33a479fca38a1f5086a6bd0fdcc9f4647da23e4284c6ae204"
The name is too long, 268 chars total.
Trying to shorten...
New name is 1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=USWUXHGYZQYFYFFIT3RE%2F20160905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160905T160956Z&X-Amz-Expires=1000&X-Amz-SignedHeaders=host&X-Amz-Signature=388c111773b459f33a479fca38a1f508.
--2016-09-05 09:10:08--  http://localhost:9000/testbucket/1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=USWUXHGYZQYFYFFIT3RE%2F20160905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160905T160956Z&X-Amz-Expires=1000&X-Amz-SignedHeaders=host&X-Amz-Signature=388c111773b459f33a479fca38a1f5086a6bd0fdcc9f4647da23e4284c6ae204
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:9000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2436591110 (2.3G) [application/zip]
Saving to: ‘1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=USWUXHGYZQYFYFFIT3RE%2F20160905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160905T160956Z&X-Amz-Expires=1000&X-Amz-SignedHeaders=host&X-Amz-Signature=388c111773b459f33a479fca38a1f508’

             1?X-Amz-Algorithm=AWS4-  18%[===========>                                                         ] 433.76M   411MB/s               ^C
$ rm 1\?X-Amz-Algorithm\=AWS4-HMAC-SHA256\&X-Amz-Credential\=USWUXHGYZQYFYFFIT3RE%2F20160905%2Fus-east-1%2Fs3%2Faws4_request\&X-Amz-Date\=20160905T160956Z\&X-Amz-Expires\=1000\&X-Amz-SignedHeaders\=host\&X-Amz-Signature\=388c111773b459f33a479fca38a1f508 
```

We fixed a problem related to signature issues recently and it is not part of the previously released nuget library

```
commit 8fb951775d14d59da84265ff88d9912adf1077cc
Author: Harshavardhana <harsha@minio.io>
Date:   Tue Jul 26 16:34:34 2016 -0700

    signature: Make sure to keep the port along in canonical request. (#104)

    Fixes #102
```

**Comment by harshavardhana** [comment]
Also surprisingly aws-sdk .net generates a an incompatible query string for Signature V4. 

```
http://127.0.0.1:9000/mybucket/mytest.txt?AWSAccessKeyId=3218PIU4AP41PX12BW5S&Expires=1473938248&Signature=AWS4-HMAC-SHA256%20Credential%3D3218PIU4AP41PX12BW5S%2F20160905%2Fus-east-1%2Fs3%2Faws4_request%2C%20SignedHeaders%3Dhost%3Bx-amz-content-sha256%3Bx-amz-date%2C%20Signature%3D63770424a643cc54b3566b3e894a1d6cddaa8e12d30a59630c477881cbe24e31
```

Adds two query params as 'Signature' set to AWS4-HMAC-SHA256 and another set to the actual signature value. The first two query params are related to Signature V2 based presigned request. Not sure what is really happening here though looks like a wrong presigned url generated by aws-sdk .net

There is one slight change i did in the code - https://gist.github.com/harshavardhana/e5865389e7e1adb166d89df320a00f61

Added 

```
SignatureMethod: Hmac256, 
```

Can you try this again @Vidarls ?

**Comment by vadmeste** [comment]
@Vidarls, I put this `AWSConfigsS3.UseSignatureVersion4 = true;` before any S3 initialization in the code and it worked fine (@harshavardhana suggestion didn't work for me but not sure why)

**Comment by harshavardhana** [comment]
Looks like the signature selection does not appropriately choose the signature type. 

Can you paste the url generated after your change @vadmeste ?

**Comment by vadmeste** [comment]
@harshavardhana, `http://172.17.0.2:9000/testbucket/mytest2.txt?X-Amz-Expires=86400&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=VB4BHCH5QPGTZPDTOEYE/20160905/us-east-1/s3/aws4_request&X-Amz-Date=20160905T202359Z&X-Amz-SignedHeaders=host&X-Amz-Signature=bc4d33dbeaa4f0a9e54ef637c0e52d5b56a32f0bf887394c3d3f8fed25d488c0`

**Comment by Vidarls** [comment]
I can confirm that adding the `UseSignatureVersion4 = true` from @vadmeste fixed the problem. Awesome and thanx. 

(@vadmeste: How did you figure this out, any links I should look at?)

//cc @harshavardhana

**Comment by harshavardhana** [comment]
This is still a bug though in their implementation sign v2 shouldnt be mixed with sign v4 and generated even as a valid url.

**Comment by vadmeste** [comment]
> This is still a bug though in their implementation sign v2 shouldnt be mixed with sign v4 and generated even as a valid url.

@harshavardhana, also, I wonder why it is not v4 by default

@Vidarls, I found this link, http://stackoverflow.com/questions/31081153/generating-a-pre-signed-url-for-s3-object-with-kms-encryption-what-am-i-doing but the solution was outdated.
