### ISSUE TITLE
streaming-v4: need better compliance to S3

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2621]
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

*) we need to require to have a last signed chunk with 0 bytes
*) check if the length of the received data is not shorter or longer than specified by headers, return the appropriate errors otherwise
*) play with standard aws libraries code to check the behavior of s3 with more edge cases

**Comment by krisis** [comment]
With #2804 still open, this issue has taken backseat. I shall provide a timeline once the sporadic streaming signature issue is root-caused.

**Comment by harshavardhana** [comment]
Fixed by #2862
