### ISSUE TITLE
docs: Need documentation/recipie for Minio with Cloud berry client.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2623]
We've got this request several times in the channel, so it'll be good have docs for Running Cloud Berry clients with Minio using v2->v4 proxy.

**Comment by koolhead17** [comment]
Moved it to Cookbook https://github.com/minio/cookbook/issues/83 , we can close it here.

**Comment by harshavardhana** [comment]
> Moved it to Cookbook minio/cookbook#83 , we can close it here.

Closing..
