### ISSUE TITLE
[distributed] Writer starvation when readers are always present

### ISSUE THREAD

**Issue by donatello** [minio/minio#2629]
## Expected behaviour

An attempt to PutObject when others are executing GetObject on the same object should succeed in a reasonable amount of time.
## Actual behaviour

A PutObject in the presence of multiple GetObject on the same object, stalls indefinitely.
## Steps to reproduce the behaviour

Run minio in distributed mode (used creds as accessKey = "abcd1" and secretKey = "abcd1234") and upload an object:

``` shell
$ mc mb myminio/dummy
$ dd if=/dev/zero of=dummy-50M bs=1048576 count=50
$ mc cp dummy-50M myminio/dummy/
# create the file to upload to the server in the program that follows
$ echo "abcdef" > /tmp/dummy-test
```

Build and run the following go program:

``` go
package main

import (
    "fmt"
    "io"
    "os"
    "time"

    mgo "github.com/minio/minio-go"
)

var (
    endpoint        = "localhost:9000"
    accessKeyID     = "abcd1"
    secretAccessKey = "abcd1234"
    useSSL          = false

    bucket = "dummy"
    path   = "dummy-50M"

    writeFilePath = "/tmp/dummy-test"
)

func readObject(resp chan bool) {
    // Initialize minio client object.
    minioClient, err := mgo.New(endpoint, accessKeyID, secretAccessKey, useSSL)
    if err != nil {
        fmt.Println(err)
        resp <- false
        return
    }

    object, err := minioClient.GetObject(bucket, path)
    if err != nil {
        fmt.Println(err)
        resp <- false
        return
    }

    fp, err := os.Create("/dev/null")
    if err != nil {
        fmt.Println(err)
        resp <- false
        return
    }
    defer fp.Close()

    bcount, err := io.Copy(fp, object)
    if err != nil {
        fmt.Println(err)
        resp <- false
        return
    }

    fmt.Printf("Success read and wrote %d bytes from %s/%s to /dev/null\n", bcount, bucket, path)
    resp <- true
    return
}

//starts 5 readers with 100ms delay. Then as each reader finishes,
//starts another one. This tries to make sure that a read is always in
//progress.
func keepReading() {
    respChan := make(chan bool)
    for i := 0; i < 5; i++ {
        go readObject(respChan)
        time.Sleep(100 * time.Millisecond)
    }
    for {
        select {
        case val := <-respChan:
            if val {
                go readObject(respChan)
            } else {
                fmt.Printf("Got error from a reader - exiting!")
                return
            }
        }
    }
}

func writeObject() {
    // Initialize minio client object.
    minioClient, err := mgo.New(endpoint, accessKeyID, secretAccessKey, useSSL)
    if err != nil {
        fmt.Println(err)
        return
    }

    file, err := os.Open(writeFilePath)
    if err != nil {
        fmt.Println(err)
        return
    }
    defer file.Close()

    n, err := minioClient.PutObject(bucket, path, file, "application/octet-stream")
    if err != nil {
        fmt.Println(err)
        return
    }

    fmt.Printf("Wrote %d bytes from %s to %s/%s\n", n, writeFilePath, bucket, path)
    return
}

func main() {
    go keepReading()

    //sleep to allow readers to start
    time.Sleep(200 * time.Millisecond)

    writeObject()
}
```

In the output we see that only the readers complete, but the writer does not - wait for a few minutes - if the writer completes, the program will exit:

```
Success read and wrote 52428800 bytes from dummy/dummy-50M to /dev/null
Success read and wrote 52428800 bytes from dummy/dummy-50M to /dev/null
Success read and wrote 52428800 bytes from dummy/dummy-50M to /dev/null
Success read and wrote 52428800 bytes from dummy/dummy-50M to /dev/null
...
```

When the same program is run against minio in fs mode, the writer is not starved - output looks like this:

```
Success read and wrote 52428800 bytes from dummy/dummy-50M to /dev/null
Success read and wrote 52428800 bytes from dummy/dummy-50M to /dev/null
Success read and wrote 7 bytes from dummy/dummy-50M to /dev/null
Wrote 7 bytes from /tmp/dummy-test to dummy/dummy-50M
```
## Minio version

```
Version: 2016-09-06T19:05:36Z
Release-Tag: DEVELOPMENT.2016-09-06T19-05-36Z
Commit-ID: b18af7a925322cd1a9af36109971b03daa96bafa
```
## System information

Linux. Minio server running locally.

**Comment by donatello** [comment]
In fs mode, the lock library - sync.RWMutex's Lock() call semantics is that, when a Lock() call (for write) is blocked, waiting for other readers to finish, it disallows new readers from acquiring the lock - https://golang.org/pkg/sync/#RWMutex - however this does not appear to be the case in the distributed version. Thus, the starvation bug I believe.

**Comment by fwessels** [comment]
The assumption is correct, the initial version of DRWMutex that worked on the client side favored Write behaviour over Read behaviour (like RWMutex).

However now that the logic has moved to the server side this is no longer the case and all locks have the same chance of success.

With DRWMutex (as implemented on the server) itself you cannot solve this, you can probably solve it on the client side by "wrapping" it with another (exclusive and distributed) mutex to mimic the sync.RWMutex behaviour. That is before you either do a Lock() or RLock(), get a Lock() on the "wrapping" mutex. But this is not cheap to do so I guess it is up to the client (code) to decide whether it is worth this or not.

**Comment by fwessels** [comment]
It is possible to use a simple wrapper around DRWMutex (that effectively uses two DRWMutexes) like so:

```
type DRWMutexNoWriterStarvation struct {
    excl *dsync.DRWMutex
    rw   *dsync.DRWMutex
}

func NewDRWMutexNoWriterStarvation(name string) *DRWMutexNoWriterStarvation {
    return &DRWMutexNoWriterStarvation{
        excl: dsync.NewDRWMutex(name + "-excl-no-writer-starvation"),
        rw: dsync.NewDRWMutex(name),
    }
}

func (d *DRWMutexNoWriterStarvation) Lock() {
    d.excl.Lock()
    defer d.excl.Unlock()

    d.rw.Lock()
}

func (d *DRWMutexNoWriterStarvation) Unlock() {
    d.rw.Unlock()
}

func (d *DRWMutexNoWriterStarvation) RLock() {
    d.excl.Lock()
    defer d.excl.Unlock()

    d.rw.RLock()
}

func (d *DRWMutexNoWriterStarvation) RUnlock() {
    d.rw.RUnlock()
}
```

(see https://github.com/minio/dsync/pull/22/commits/0d8e5988abb53b7daadb256bda6d7625dbb22834 for full details and https://github.com/minio/dsync/pull/22/commits/b272b3d3534149cfa3a65121e7129c8468c8a055 for a corresponding test case)

Only downside of this approach is that it obviously uses 2 DRWMutex objects so it is effectively twice as expensive compared to the normal usage. But it is up to the client/user to decide whether it is worth the expense or not.

**Comment by harshavardhana** [comment]
After discussion this has been deferred to future work.

**Comment by harshavardhana** [comment]
> After discussion this has been deferred to future work.

This was decided to be closed, we can open this discussion back if it becomes a priority.
