### ISSUE TITLE
Minio returns an error code when deleting a non-existent object through DeleteMultiObjects API

### ISSUE THREAD

**Issue by danielboros** [minio/minio#2630]
Hello, we use Minio as a replacement for S3 during development. This behavior cropped up when we ran an existing unit test against Minio. When deleting an object that doesn't exist, we normally expect to receive no error code. It seems as though Minio's response provides an error code (`NoSuchKey`) which causes an exception in the Java SDK.

As an aside... I took a look at the code and it doesn't seem like the error gets propagated...

``` Go
/// http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETE.html
/// Ignore delete object errors, since we are suppposed to reply
/// only 204.
if err := api.ObjectAPI.DeleteObject(bucket, object); err != nil {
    writeSuccessNoContent(w)
    return
}
```

So this might be a side effect of how the SDK is interpreting the response from Minio.
## Expected behaviour

When running against Amazon AWS with Java SDK version 1.11.8, the response is populated with the deleted objects and no errors are put into the response list. See the response object populated from Amazon AWS' response below:

![Amazon AWS Response](http://i.imgbox.com/jnOQIfW6.png)
## Actual behaviour

The SDK generates a `MultiObjectDeleteException` after receiving `NoSuchKey` in errors list... so it seems like Minio does the opposite. See the response object populated from Minio's response below:

![Minio Response](http://i.imgbox.com/lEOuoXIM.png)
## Steps to reproduce the behaviour
1. Try to delete a non-existent object.
## Minio version

Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2
## System information
- Windows 7
- AWS Java SDK 1.11.8

**Comment by harshavardhana** [comment]
> Hello, we use Minio as a replacement for S3 during development. This behavior cropped up when we ran an existing unit test against Minio. When deleting an object that doesn't exist, we normally expect to receive no error code. It seems as though Minio's response provides an error code (NoSuchKey) which causes an exception in the Java SDK.
> 
> As an aside... I took a look at the code and it doesn't seem like the error gets propagated...
> 
> /// http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETE.html
> /// Ignore delete object errors, since we are suppposed to reply
> /// only 204.
> if err := api.ObjectAPI.DeleteObject(bucket, object); err != nil {
>     writeSuccessNoContent(w)
>     return
> }

@danielboros for that minio server implements DeleteMultipleObjects - http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html

The code you are looking at is DeleteObject() which does only single object delete. Can you show us an example code?

**Comment by danielboros** [comment]
@harshavardhana 
Hello, here's some Java code that will fail every time:

``` Java
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.DeleteObjectsRequest;
import java.security.SecureRandom;

public class Delete
{
  private AmazonS3 s3Client;

  private final String ACCESS_KEY = "access";
  private final String SECRET_KEY = "secret";

  public Delete() {
    AWSCredentials credentials = new BasicAWSCredentials( ACCESS_KEY, SECRET_KEY );

    s3Client = new AmazonS3Client( credentials );
    s3Client.setEndpoint("http://127.0.0.1:9000");
  }

  public void deleteANonExistingObject() {
    String aBucket  = "bucket." + getRandomString( 10, false );
    String anObject = "object." + getRandomString( 10, false );

    s3Client.createBucket( aBucket );
    s3Client.deleteObjects( new DeleteObjectsRequest( aBucket ).withKeys( anObject ) );
  }

  private static String getRandomString( int size, boolean includeUppercase )
  {
    String symbols = "0123456789abcdefghijklmnopqrstuvwxyz";

    if ( includeUppercase )
      symbols += "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

    SecureRandom random = new SecureRandom();
    StringBuilder builder = new StringBuilder( size );

    for ( int i = 0; i < size; i++ )
      builder.append( symbols.charAt( random.nextInt( symbols.length() ) ) );

    return builder.toString();
  }
}
```

... and the corresponding JUnit test:

``` Java
@Test
public void testDeletingANonExistentObjectCausesException()
{
  try
  {
    new Delete().deleteANonExistingObject();
  }
  catch ( MultiObjectDeleteException e )
  {
    e.printStackTrace();
    fail("Should not generate an exception for an object that DNE.");
  }
}
```

**Comment by krishnasrinivas** [comment]
@danielboros 
http://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingMultipleObjectsUsingJava.html
says:

```
In the event of an exception, you can review the MultiObjectDeleteException to determine which objects failed to delete and why as shown in the following Java example.
```

Hence the exception is raised.

If you use `s3Client.deleteObject()` instead of `s3Client.deleteObjects()` you will not see the exception even if the object did not exist

**Comment by danielboros** [comment]
@krishnasrinivas 
`s3Client.deleteObjects(...)` will not raise an exception when deleting objects that DNE on AWS S3. Just wondering what your thoughts are on that? Our code can account for both cases but my understanding is that Minio is supposed to be in parity with the canonical implementation.

**Comment by krishnasrinivas** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html says:
`Note that, if the object specified in the request is not found, Amazon S3 returns the result as deleted.`

So indeed it is not an error. We will fix this, thanks for reporting @danielboros

**Comment by danielboros** [comment]
@krishnasrinivas 
No problem! Thanks. :bow:

**Comment by krishnasrinivas** [comment]
@danielboros :bow: :pray:

**Comment by danielboros** [comment]
Built and tested locally. Looks good. :+1:

**Comment by harshavardhana** [comment]
> Built and tested locally. Looks good.

Thanks @danielboros

**Comment by smith-daniels** [comment]
I am curious where the code added in https://github.com/minio/minio/commit/a4afb312d44f431e856ab83e5884bb21d38ac29b is no longer in the source. I have an issue where the DeleteMultipleObjects request is reporting a failure to delete the object because they no longer exist.
