### ISSUE TITLE
tests: Validate minio server with skewed times on different machines.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2634]
We need to test and find if Minio distributed release is dependent on NTP server for time synchronization among all the nodes.

**Comment by harshavardhana** [comment]
@hackintoshrao - we need to test various conditions here basically setting system time 
- forward
- backward
  
  After setting these values and access the server using 'mc' from a node which has proper time, see how many operations fail or what kind of operations fail. Just to see if we do indeed fail with required error messages.

**Comment by hackintoshrao** [comment]
Ok, got it now.

**Comment by GarimaKapoor** [comment]
@hackintoshrao what is the status of this issue?

**Comment by hackintoshrao** [comment]
Need to validate this for more operations.  Will finish it today.

**Comment by GarimaKapoor** [comment]
What is the status of the fix?

**Comment by hackintoshrao** [comment]
was setting the date using `date --set="17 Sep 2016 10:00:00"` from root ( cannot set without being a root), but once I log back to normal user the date used to reset (seen using `date` command), never noticed this, so my results are not reliable. Will run minio with `root` privilages and run these small tests again.

**Comment by hackintoshrao** [comment]
<img width="862" alt="screen shot 2016-09-16 at 8 19 43 pm" src="https://cloud.githubusercontent.com/assets/2609511/18591123/f7393014-7c4e-11e6-9fc6-aacc42307af8.png">

Even with root the date set is not retained, didnt notice till now. What would be good way to change system time.

**Comment by harshavardhana** [comment]
> Even with root the date set is not retained, didnt notice till now. What would be good way to change system time.

It is not retained perhaps is because of ntp - turn it off and run this again it should work.

**Comment by harshavardhana** [comment]
> Even with root the date set is not retained, didnt notice till now. What would be good way to change system time.
> It is not retained perhaps is because of ntp - turn it off and run this again it should work.

Were you able to validate this?

**Comment by hackintoshrao** [comment]
The NTP service doesn't seem to be running, here is the output when I tried to stop  the NTP service, 

`$sudo service ntp stop`

 Failed to stop ntp.service: Unit ntp.service not loaded.

**Comment by hackintoshrao** [comment]
I made several other attemps, but able to change the system time  minio2 server. Can @krishnasrinivas  help ?

**Comment by krishnasrinivas** [comment]
@hackintoshrao 
changed it on minio2 like this:
timedatectl set-ntp 0
root@minio2:~# timedatectl set-time 2002-10-02
root@minio2:~# date
Wed Oct  2 00:00:01 PDT 2002

**Comment by hackintoshrao** [comment]
Thanks @krishnasrinivas , will try with this.

**Comment by hackintoshrao** [comment]
Here my observations,
- After the time is skewed the operations run well with `mc` when it pings the same node in which its running.  That is Lets the time is skewed on node2 (Its a 2 node setup), and mc is running on node2 and pings to node2 itself, all the operations run smoothly, the vice versa holds good too. 
- But when `mc` is configured to ping `node1` from `node2` or vice versa the operations fail with `The difference between the request time and the server's time is too large.` . 
- Linking https://github.com/minio/minio/issues/2753 to this issue.

**Comment by harshavardhana** [comment]
> Here my observations,
> 
> After the time is skewed the operations run well with mc when it pings the same node in which its running. That is Lets the time is skewed on node2 (Its a 2 node setup), and mc is running on node2 and pings to node2 itself, all the operations run smoothly, the vice versa holds good too.
> 
> But when mc is configured to ping node1 from node2 or vice versa the operations fail with The difference between the request time and the server's time is too large. .

The error is appropriate we have another bug open which needs to be addressed at a distributed scale. #2753 -  closing this issue.
