### ISSUE TITLE
[distributed] If a minio instance serving a PUT request goes down, in certain cases the same PUT request cannot be retried later

### ISSUE THREAD

**Issue by donatello** [minio/minio#2636]
## Expected behaviour

If a Minio server goes down when it is serving a PUT request, the request should be retry-able on another Minio server in the cluster.
## Actual behaviour

As in title.
## Steps to reproduce the behaviour

**Not reproduced currently**, but I am trying to do it. As per my understanding, if the Minio server goes down while holding a lock on the object being PUT, the lock cannot be recovered. Since the window during which the lock is held is small, so far I have not succeeded in reproducing this bug.
## Minio version
- latest distributed branch (at time of writing)
## System information
- all systems

**Comment by fwessels** [comment]
I guess not easy to reproduce indeed...

Situations like these should be fixed when we have a "stale lock" detection/clearing mechanism in dsync. Work is on going to come up with a good strategy.

**Comment by fwessels** [comment]
See https://github.com/minio/dsync/pull/22 for the Stale Lock detection algorithm that should address this.

Once we update (the vendorized) dsync, we also need to add the maintenance code to the lock-rpc-server.

**Comment by harshavardhana** [comment]
> See minio/dsync#22 for the Stale Lock detection algorithm that should address this.
> 
> Once we update (the vendorized) dsync, we also need to add the maintenance code to the lock-rpc-server.

New dsync changes are already in master, closing this.
