### ISSUE TITLE
Large files fail to upload: malformed HTTP status code "html>"

### ISSUE THREAD

**Issue by matthanley** [minio/minio#2639]
Large files fail to upload - below is the error from a ~17GB upload via `mc copy`. The upload reaches 100% but then exits with an error.
## Expected behaviour

File uploads correctly.
## Actual behaviour

```
mc: <ERROR> Failed to copy ‘*************.pst’. Post https://s3.eu-west-1.********/tmp/*********.pst?uploadId=********-2807-47e8-bd2d-d475ec0b1b3a: malformed HTTP status code "html>"
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume KrwL****’
```
## Steps to reproduce the behaviour
- Create a large file (~20GB)
- `mc copy file dest/bucket/`
## Minio version

docker minio/minio:latest
## System information

Docker + HAProxy SSL termination

**Comment by krishnasrinivas** [comment]
@matthanley does it work for smaller files? like 100MB?

**Comment by matthanley** [comment]
It does - I can successfully copy `debian-8.1.0-amd64-netinst.iso` at 247MB with no problems. I am having issues pushing a 212MB docker image into minio via Gitlab's docker registry but that may be an unrelated issue.

**Comment by harshavardhana** [comment]
> mc: <ERROR> Failed to copy ‘************_.pst’. Post https://s3.eu-west-1.**_****_/tmp/**_*****_.pst?uploadId=**_****_-2807-47e8-bd2d-d475ec0b1b3a: malformed HTTP status code "html>"
> mc: <ERROR> Session safely terminated. To resume session ‘mc session resume KrwL**_*’

The problem related to large file uploads FS waits for a longer period of time since it does concatenation in background. 

Another important issue we recently fixed is related to timeouts so here completemultipart upload perhaps has timedout after 10mins. 

Can you try 'docker minio/minio:edge'  and confirm? - thanks

**Comment by matthanley** [comment]
This may also be related to #2640 if the client is using multipart uploads. I have also been having issues with timeouts after 10 mins for downloads so have switched to `:edge` and retesting now. I'll retest the upload via `mc` again tomorrow on `:edge` and with #2640 fixed.

**Comment by harshavardhana** [comment]
> This may also be related to #2640 if the client is using multipart uploads. I have also been having issues with timeouts after 10 mins for downloads so have switched to :edge and retesting now. I'll retest the upload via mc again tomorrow on :edge and with #2640 fixed.

Cool thanks @matthanley

**Comment by harshavardhana** [comment]
Is this still a problem @matthanley ?

**Comment by harshavardhana** [comment]
> Is this still a problem @matthanley ?

@matthanley will close this for now, please re-open if the issue persists.
