### ISSUE TITLE
Multipart uploads failing with 404 errors

### ISSUE THREAD

**Issue by matthanley** [minio/minio#2640]
## Expected behaviour

Multipart uploads accepted and stored.
## Actual behaviour

Uploads are failing with `404` response codes.

From HAProxy logs, the server is accepting multipart uploads to a point (not always the same point) and then failing with a `404` response part way through. This is the log file from doing `docker push` via Gitlab's docker registry using a Minio backend:

```
Sep  8 19:04:13 two haproxy[6086]: 185.***.***.***:55379 [08/Sep/2016:19:04:13.209] S3-EU-WEST-1~ S3-EU-WEST-1_backend/two-s3-eu-west-1 123/0/0/586/709 200 297 - - ---- 2/2/1/2/0 0/0 "PUT https://s3.eu-west-1.*******/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/*******/_uploads/5c44ee32-68e9-4535-9d83-*********/data?partNumber=4&uploadId=594dae27-f9fa-4242-a4ea-******* HTTP/1.1"
Sep  8 19:04:14 two haproxy[6086]: 185.***.***.***:55379 [08/Sep/2016:19:04:13.918] S3-EU-WEST-1~ S3-EU-WEST-1_backend/one-s3-eu-west-1 124/0/1/13/138 404 746 - - SD-- 1/1/1/0/0 0/0 "PUT https://s3.eu-west-1.*******/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/*******/_uploads/5c44ee32-68e9-4535-9d83-*********/data?partNumber=5&uploadId=594dae27-f9fa-4242-a4ea-******* HTTP/1.1"
Sep  8 19:04:14 two haproxy[6086]: 185.***.***.***:55470 [08/Sep/2016:19:04:14.068] S3-EU-WEST-1~ S3-EU-WEST-1_backend/two-s3-eu-west-1 5/0/0/28/33 200 297 - - ---- 2/2/1/2/0 0/0 "PUT https://s3.eu-west-1.*******/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/*******/_uploads/5c44ee32-68e9-4535-9d83-*********/hashstates/sha256/62884005 HTTP/1.1"
Sep  8 19:04:14 two haproxy[6086]: 185.***.***.***:55470 [08/Sep/2016:19:04:14.101] S3-EU-WEST-1~ S3-EU-WEST-1_backend/one-s3-eu-west-1 50/0/1/5/56 404 746 - - SD-- 1/1/1/0/0 0/0 "PUT https://s3.eu-west-1.*******/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/*******/_uploads/5c44ee32-68e9-4535-9d83-*********/data?partNumber=5&uploadId=594dae27-f9fa-4242-a4ea-******* HTTP/1.1"
```

`partNumber=4` is accepted with a `200` response code, but `partNumber=5` fails with a `404`.

`SD--` termination code indicates the server (minio) severed the connection during the data phase.
## Steps to reproduce the behaviour

`docker push` on an image ~200MB via Gitlab's docker registry.
## Minio version

docker minio/minio:edge
docker minio/minio:latest
## System information

Docker with HAProxy SSL termination

**Comment by harshavardhana** [comment]
> Sep  8 19:04:13 two haproxy[6086]: 185.**_.**_.**_:55379 [08/Sep/2016:19:04:13.209] S3-EU-WEST-1~ S3-EU-WEST-1_backend/two-s3-eu-west-1 123/0/0/586/709 200 297 - - ---- 2/2/1/2/0 0/0 "PUT https://s3.eu-west-1.**_***_/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/**_***_/_uploads/5c44ee32-68e9-4535-9d83-**_*****_/data?partNumber=4&uploadId=594dae27-f9fa-4242-a4ea-**_***\* HTTP/1.1"
> Sep  8 19:04:14 two haproxy[6086]: 185.**_.**_.**_:55379 [08/Sep/2016:19:04:13.918] S3-EU-WEST-1~ S3-EU-WEST-1_backend/one-s3-eu-west-1 124/0/1/13/138 404 746 - - SD-- 1/1/1/0/0 0/0 "PUT https://s3.eu-west-1.**_***_/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/**_***_/_uploads/5c44ee32-68e9-4535-9d83-**_*****_/data?partNumber=5&uploadId=594dae27-f9fa-4242-a4ea-**_***\* HTTP/1.1"
> Sep  8 19:04:14 two haproxy[6086]: 185.**_.**_.**_:55470 [08/Sep/2016:19:04:14.068] S3-EU-WEST-1~ S3-EU-WEST-1_backend/two-s3-eu-west-1 5/0/0/28/33 200 297 - - ---- 2/2/1/2/0 0/0 "PUT https://s3.eu-west-1.**_***_/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/**_***_/_uploads/5c44ee32-68e9-4535-9d83-**_*****_/hashstates/sha256/62884005 HTTP/1.1"
> Sep  8 19:04:14 two haproxy[6086]: 185.**_.**_.**_:55470 [08/Sep/2016:19:04:14.101] S3-EU-WEST-1~ S3-EU-WEST-1_backend/one-s3-eu-west-1 50/0/1/5/56 404 746 - - SD-- 1/1/1/0/0 0/0 "PUT https://s3.eu-west-1.*******/gitlab-docker-registry/docker/registry/v2/repositories/matt.hanley/*******/_uploads/5c44ee32-68e9-4535-9d83-*********/data?partNumber=5&uploadId=594dae27-f9fa-4242-a4ea-******* HTTP/1.1"
> partNumber=4 is accepted with a 200 response code, but partNumber=5 fails with a 404.
> 
> SD-- termination code indicates the server (minio) severed the connection during the data phase.

Do you have detailed instructions on how we can reproduce this ourselves? @matthanley

**Comment by matthanley** [comment]
I've actually just realised this was me being stupid; I'm running minio on two hosts on top of glusterfs with haproxy doing SSL and load balancing. The issue was having `balance roundrobin` in haproxy - as far as I can see the next request is being sent to a different server faster than the gluster replication latency, so the previous part doesn't actually exist on the server that receives the next part.

I've changed to `balance source` and the issue is resolved.

**Comment by harshavardhana** [comment]
> I've actually just realised this was me being stupid; I'm running minio on two hosts on top of glusterfs with haproxy doing SSL and load balancing. The issue was having balance roundrobin in haproxy - as far as I can see the next request is being sent to a different server faster than the gluster replication latency, so the previous part doesn't actually exist on the server that receives the next part.
> 
> I've changed to balance source and the issue is resolved.

Ah nice, btw if you have time to document this setup and submit a PR  - https://github.com/minio/cookbook - Happy Hacking :-)

**Comment by krishnasrinivas** [comment]
> I've actually just realised this was me being stupid; I'm running minio on two hosts on top of glusterfs with haproxy doing SSL and load balancing.

@matthanley note that two minio servers should not share the same backend unless the access is readonly. Minio-FS (exporting single export) uses in memory locks, hence if two minio instances share the same backend there can be race conditions.

**Comment by matthanley** [comment]
Thanks, I'll have to look into whether I can split the requests from HAProxy based on the HTTP verb of the request to deal with read/write. Otherwise I can just run them in active/passive instead of balanced.

For my purposes at the moment having `balance source` should provide enough of a split to prevent client collisions.

**Comment by krishnasrinivas** [comment]
> Thanks, I'll have to look into whether I can split the requests from HAProxy based on the HTTP verb of the request to deal with read/write.

Even in this case read and write can race which can cause unintended consequences. For example one minio server over-writes to a file which is read by the other minio server - the minio server that is reading can get contents from two versions of the file.

**Comment by matthanley** [comment]
A valid point; my primary use case is storing docker images so I'm not likely to hit that condition but something to keep in mind. It would be interesting to see how the gluster layer would help mitigate this (if at all) as I'm not accessing the _same_ backend, rather different backends which are replicated. Unfortunately I don't know enough about the specifics of gluster replication, but I do know it has a layer designed to prevent exactly the issue you mentioned under "normal" usage.

**Comment by harshavardhana** [comment]
> A valid point; my primary use case is storing docker images so I'm not likely to hit that condition but something to keep in mind. It would be interesting to see how the gluster layer would help mitigate this (if at all) as I'm not accessing the same backend, rather different backends which are replicated. Unfortunately I don't know enough about the specifics of gluster replication, but I do know it has a layer designed to prevent exactly the issue you mentioned under "normal" usage.

It would be easier to see the setup here @matthanley so that we can make valid recommendations.
