### ISSUE TITLE
s3 list objects v2 owner

### ISSUE THREAD

**Issue by brackxm** [minio/minio#2647]
## Expected behaviour

AWS S3 does not return the object owner with list objects v2
## Actual behaviour

minio returns the object owner with list objects v2
## Minio version

Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2

**Comment by vadmeste** [comment]
Thanks @brackxm.

@harshavardhana, we can set `fetch-owner` query to true in ListObjectV2 to retrieve owner information by default when calling our API.

**Comment by vadmeste** [comment]
> @harshavardhana, we can set fetch-owner query to true in ListObjectV2 to retrieve owner information by default when calling our API.

oups, this is minio and not minio-go. Anyway, there is a new option fetch-owner in list-object-v2 which, only when set to true, returns owner information

**Comment by harshavardhana** [comment]
> oups, this is minio and not minio-go. Anyway, there is a new option fetch-owner in list-object-v2 which, only when set to true, returns owner information

I think i remember reading that - lets fix it. :+1:
