### ISSUE TITLE
Minio should provide Informative error output for better debugging.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2651]
Minio should provide more informative error output, it will make debugging easier.

```
$ mc --debug  events add  myminio/amonak arn:minio:sqs:us-east-1:1:redis --suffix .jpg
mc: <ERROR> The provided url doesn't point to a S3 server. 
```

An example above. I am using Minio, but error mentions S3.

**Comment by harshavardhana** [comment]
> Minio should provide more informative error output, it will make debugging easier.
> 
> $ mc --debug  events add  myminio/amonak arn:minio:sqs:us-east-1:1:redis --suffix .jpg
> mc: <ERROR> The provided url doesn't point to a S3 server. 
> An example above. I am using Minio, but error mentions S3.

This is not 'minio' bug can you open this on 'mc' ?? @koolhead17
