### ISSUE TITLE
[distributed] tests: Implement tests for ratelimit handler.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2661]
https://codecov.io/gh/minio/minio/src/8acf4d112a01f3071d008ae3bc559e2ec40a6dee/cmd/rate-limit-handler.go  - for more awareness.

**Comment by donatello** [comment]
Waiting for resolution of https://github.com/minio/minio/issues/2678

**Comment by harshavardhana** [comment]
> Waiting for resolution of #2678

Can you send a PR with the fix you mentioned.. #2678

**Comment by donatello** [comment]
This can be closed now.
