### ISSUE TITLE
[distributed] tests: Implement tests for server-main.go

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2663]
https://codecov.io/gh/minio/minio/src/8acf4d112a01f3071d008ae3bc559e2ec40a6dee/cmd/server-main.go - for more awareness.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas what is the timeline for the fix.

**Comment by krisis** [comment]
@GarimaKapoor I am working on https://github.com/minio/minio/issues/2760 at the moment. I will pick this up after adding some more tests for https://github.com/minio/minio/issues/2710.
