### ISSUE TITLE
ServeHTTP Rate-limit bug in acquire()

### ISSUE THREAD

**Issue by donatello** [minio/minio#2678]
In [rate-limit-handler.go](https://github.com/minio/minio/blob/master/cmd/rate-limit-handler.go) (at this time of writing), there is a function `acquire()`, intended to allow at most `globalMaxConn` connections to be processed simultaneously, and to limit the number of waiting connections to `globalMaxConn*4`:

``` go
// acquire and release implement a way to send and receive from the
// channel this is in-turn used to rate limit incoming connections in
// ServeHTTP() http.Handler method.
func (c *rateLimit) acquire() error {
    // Kick out clients when it is really crowded
    if len(c.waitQueue) == cap(c.waitQueue) {
        return errTooManyRequests
    }

    // Add new element in waitQueue to keep track of clients
    // wanting to process their requests
    c.waitQueue <- struct{}{}

    // Moving from wait to work queue is protected by a mutex
    // to avoid draining waitQueue with multiple simultaneous clients.
    c.lock.Lock()
    c.workQueue <- <-c.waitQueue
    c.lock.Unlock()
    return nil
}
```

Consider the scenario, that `globalMaxConn = 1`, and `len(c.waitQueue) == 3`. Now assume, 2 connections simultaneously enter the `acquire()` method - both may pass the `if` block (`len(c.waitQueue) == 3 and cap(c.waitQueue) == 4`), then, one will enter wait queue, and the other will block waiting on the same queue.

This a bug because the intended semantics appears to be that no more than `globalConn * 4` connections should be waiting, but in this case there will be 5 waiting. With only one spot available in the queue, if 10 connections come in simultaneously, all 10 could be waiting instead of 9 of them getting rate-limit exceeded errors back.

Proposed fix:

``` go
func (c *rateLimit) acquire() error {
    c.lock.Lock()
    // Kick out clients when it is really crowded
    if len(c.waitQueue) == cap(c.waitQueue) {
        defer c.lock.Unlock() //don't forget to unlock
        return errTooManyRequests
    }

    // Add new element in waitQueue to keep track of clients
    // wanting to process their requests
    c.waitQueue <- struct{}{}
    c.lock.Unlock()

    c.workQueue <- <-c.waitQueue
    return nil
}
```

We prevent two go-routines from simultaneously checking for a spot in the queue and entering it.

No synchronization for moving an item from the `waitQueue` to `workQueue` is needed, as it is thread safe already.

**Comment by donatello** [comment]
PR to resolve this - https://github.com/minio/minio/pull/2679

**Comment by vadmeste** [comment]
Thanks @donatello
