### ISSUE TITLE
[feature] Support server side encryption of objects

### ISSUE THREAD

**Issue by theonewolf** [minio/minio#2692]
This is a feature request.

For enterprise environments, it is crucial that storage systems have encrypted storage capabilities.

Minimally you will want to use something like AES with 256-bit keys and key rotation.

I **highly** suggest adding support for encrypting with Vault (https://www.vaultproject.io, https://github.com/hashicorp/vault also written in Go) which has started seeing use within enterprise environments already.

Vault would provide all of the cryptography, parameters, and key management.  It is critical that these things are managed centrally as well for enterprise users.  If every subsystem manages users and credentials independently, things quickly become an operational nightmare.

Minio is unusable for us and others until we have strong cryptography both in flight (I think this is in progress for you guys) and at rest.

However, Minio is one of the best storage projects I've seen in a long time.  Keep up the good work :+1:.

Also, in case you need any help, @jefferai and team are very responsive some of the best developers in industry (IMHO).

**Comment by jefferai** [comment]
Gosh @theonewolf , thanks :-)

I'm not sure if this is related to a similar feature request made by @theonewolf to Vault, although I suspect it may be, but as of 0.6.2 (due in a week or two) Vault will support convergent encryption. This allows the same plaintext + context to map to the same ciphertext while providing good defaults/safeguards against doing such a thing insecurely.

This allows encrypted blocks to be deduplicated, which also means that they can be well-supported by things like erasure coding systems.

Happy to help if you have any questions, but I do think that Vault can be well suited for this kind of use-case!

**Comment by krishnasrinivas** [comment]
> However, Minio is one of the best storage projects I've seen in a long time. Keep up the good work

@theonewolf thank you!

Regarding encryption, it could be done in two ways:
1) Minio encrypts objects on the server side before saving it to the disk.
    We want to keep minio features minimal and focus on stability and reliability. Hence we did not implement this.
2) Client encrypts the object and uploads it to minio.
    Users already do this with minio by using clients such as restic(https://github.com/restic/restic) rclone (http://rclone.org/) which encrypt data before uploading it to minio.

Isn't option-2 viable for you?

**Comment by harshavardhana** [comment]
> 2) Client encrypts the object and uploads it to minio.
> Users already do this with minio by using clients such as restic(https://github.com/restic/restic) rclone (http://rclone.org/) which encrypt data before uploading it to minio.

:+1:

**Comment by krishnasrinivas** [comment]
@theonewolf isn't option-2 viable for your use case?

**Comment by theonewolf** [comment]
It does work, in the way of punting it to users (who will inevitably mess it up, misconfigure it, etc.).  I was hoping to get a principled "module" in place that works well with Minio.

Also, I am a **huge** fan of minimalism, and huge supporter of the "do one thing and do it well" mantra.  I'm happy to see your devotion to it :-)  A strong vision for Minio will take it very far in my opinion.

Do you think you will have support for things like "filters" similar to how the Linux kernel introduced devmapper (https://en.wikipedia.org/wiki/Device_mapper), or how QEMU has block filters (not sure on a great link, but an example implementation: http://events.linuxfoundation.org/sites/events/files/slides/kvm16.pdf)?

If you guys had a filter / plugin framework, then users could have a well defined API to program against such that we could better ensure correctness for anything we wish to layer on top of Minio.

Alternatively, I was wondering if you had plans instead to fit encryption into one of your other projects.  For example, your FUSE project (https://github.com/minio/minfs) could layer encryption on top of Minio.

**Comment by theonewolf** [comment]
Ah, it is on the TODO list for FUSE:

> TODO
> 
> There is a long list of todos:
> 
> Allow stats to be printed using a signal.
> Use Minio notifications to actively update metadata.
> One mountpoint per bucket.
> Each mountpoint will have its own cache folders and can be mounted to one bucket
> Implement encryption support, (a)symmetric

**Comment by theonewolf** [comment]
I can't quite quantify this, but having encryption built into the storage directly is just so nice (such as SSDs having encryption built into the hardware these days http://www.samsung.com/semiconductor/minisite/ssd/downloads/document/Samsung_SSD_White_Paper.pdf).

Without built in encryption in the storage layer, the Minio cookbook examples aren't as simple as they first appear.  For example, you can't just use the `mc` tool to mirror your database backups into Minio.  You'll need at least one extra step or tool to encrypt the data before mirroring.

**Comment by krishnasrinivas** [comment]
> Also, I am a huge fan of minimalism, and huge supporter of the "do one thing and do it well" mantra. I'm happy to see your devotion to it :-) A strong vision for Minio will take it very far in my opinion.

:+1: 

> If you guys had a filter / plugin framework, then users could have a well defined API to program against such that we could better ensure correctness for anything we wish to layer on top of Minio.

We don't have a plugin support. But what you can do is write a proxy on top minio which encrypts/decrypts data. This is not very straight forward as proxy needs to speak s3 protocol.

looks like aws-sdks have built-in support to encrypt files http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryptionUpload.html

> Without built in encryption in the storage layer, the Minio cookbook examples aren't as simple as they first appear. For example, you can't just use the mc tool to mirror your database backups into Minio. You'll need at least one extra step or tool to encrypt the data before mirroring.

having `mc` support encryption is a good idea, if we don't implement it you can use rclone :D

But I get that you really prefer minio handle encryption on the server side transparently. Will wait for @harshavardhana to add if anything can be done about it.

**Comment by theonewolf** [comment]
Yeah, @krishnasrinivas you're right S3 has built-in support for encryption (as does EBS and other storage services).

It's a bit philosophical, but I'm proposing that all modern storage systems should consider cryptography as a fundamental feature.  Similar to how any serious web server project must include support for HTTPS these days.

However, I'd be willing to concede that the layer Minio is placing itself in the stack should not do cryptography.  For example, we could require the host system to implement cryptography either in the native file system (such as ZFS), or in the block layer of the host (a la dm-crypt).

I wouldn't mind that, except sometimes you don't get to control the parameters of your host file system or block layer (although that could be a minority of Minio deployments).  There's still something "nice" about the objects being encrypted, especially if the keys are controlled by some centralized service or node such as Vault.

If Minio objects are encrypted, that means even if a Minio server is broken into, it doesn't necessarily compromise the objects on the host file system.

Also, placing the burden of cryptography into a lower-level system such as ZFS or dm-crypt does not solve the Minio multi-tenant (although I think Minio is largely single tenant right now?) case where multiple users of Minio want their objects encrypted with different keys.

I suppose that's why you suggest using a proxy into Minio that encrypts objects passing through it.

**Comment by harshavardhana** [comment]
Features like encrytion, compression, dedup should be outside of object storage as a layer above object storage, ideally implemented at the client side. 

Please take a look at tools like 

 - https://restic.readthedocs.io/en/stable/Manual/ - Restic
 - http://rclone.org/ - Rclone.

**Comment by frntn** [comment]
@theonewolf not yet documented but SSE-C is available now thanks to PR #4894
I have successfully tested it with this version
```
$ minio version
Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48
```

**Comment by frntn** [comment]
Nevermind... here is the "doc" : https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-server-side-encryption-with-aws-cli.md

**Comment by theonewolf** [comment]
Oh wow!  Thanks for the update @frntn!
