### ISSUE TITLE
api: Signature should be validated first and payload later

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2697]
SignatureDoesNotMatch should be returned early, currently we read all the data and return the error in the end.

**Comment by harshavardhana** [comment]
> SignatureDoesNotMatch should be returned early, currently we read all the data and return the error in the end.

Cannot understand what you mean here, are you saying that we shouldn't validate payload?

**Comment by krishnasrinivas** [comment]
> Cannot understand what you mean here, are you saying that we shouldn't validate payload?

payload should be validated, but that will be sha256-mismatch error if the validation fails. But there is no stopping us from validating the signature early unless it is a streaming upload.

**Comment by harshavardhana** [comment]
> payload should be validated, but that will be sha256-mismatch error if the validation fails. But there is no stopping us from validating the signature early unless it is a streaming upload.

But how would you calculate signature without knowing the sha256? are you saying that we use the same  sha256 what comes over the wire? 

What is the S3 behavior?

**Comment by krishnasrinivas** [comment]
> But how would you calculate signature without knowing the sha256? are you saying that we use the same sha256 what comes over the wire?

Yes since sha256 is sent in the header we can just use it for signature verification

> What is the S3 behavior?

S3 should be doing the signature verification early too before reading in all the data, let me check.

**Comment by harshavardhana** [comment]
> S3 should be doing the signature verification early too before reading in all the data, let me check.

Sure please validate.

**Comment by krishnasrinivas** [comment]
S3 returns signature error early.

hard coded a wrong signature:

```
+++ b/src/main/signing.js
@@ -216,6 +216,7 @@ export function signV4(request, accessKey, secretKey, region) {
   var signingKey = getSigningKey(requestDate, region, secretKey)
   var credential = getCredential(accessKey, region, requestDate)
   var signature = Crypto.createHmac('sha256', signingKey).update(stringToSign).digest('hex').toLowerCase()
+  if (request.method === 'PUT') signature = 'b806149a17ffe66e75a0cc1d18ead4579e5a8a21d4e952059adc4f4279504e1b'

   return `${signV4Algorithm} Credential=${credential}, SignedHeaders=${signedHeaders.join(';').toLowerCase()}, Signature=${signature}`
 }
```

/tmp/go.tgz is 1.2G file:

```
s3Client.fPutObject('miniocloud', 'go.tgz', '/tmp/go.tgz', '', function(e, etag) {
  console.log(e, etag)
})
```

`time node fput-object-s3.js` with secure=false took 18secs (includes sha256 calculation) to return signature error. So S3 is returning early as well without reading in the whole data.

`time sha256sum /tmp/go.tgz` took 8 secs. So definitely the script could not have uploaded 1.2G in 10 secs.

**Comment by harshavardhana** [comment]
> hard coded a wrong signature:
> 
> +++ b/src/main/signing.js
> @@ -216,6 +216,7 @@ export function signV4(request, accessKey, secretKey, region) {
>    var signingKey = getSigningKey(requestDate, region, secretKey)
>    var credential = getCredential(accessKey, region, requestDate)
>    var signature = Crypto.createHmac('sha256', signingKey).update(stringToSign).digest('hex').toLowerCase()
> -  if (request.method === 'PUT') signature = 'b806149a17ffe66e75a0cc1d18ead4579e5a8a21d4e952059adc4f4279504e1b'
>   
>   return `${signV4Algorithm} Credential=${credential}, SignedHeaders=${signedHeaders.join(';').toLowerCase()}, Signature=${signature}`
>   }
>   /tmp/go.tgz is 1.2G file:
> 
> s3Client.fPutObject('miniocloud', 'go.tgz', '/tmp/go.tgz', '', function(e, etag) {
>   console.log(e, etag)
> })
> time node fput-object-s3.js with secure=false took 18secs (includes sha256 calculation) to return signature error. So S3 is returning early as well without reading in the whole data.
> 
> time sha256sum /tmp/go.tgz took 8 secs. So definitely the script could not have uploaded 1.2G in 10 secs.

I see lets make this change, it makes things easy as well.

**Comment by harshavardhana** [comment]
Assigned this to you @krishnasrinivas - can you fix it?

**Comment by krishnasrinivas** [comment]
> Assigned this to you @krishnasrinivas - can you fix it?

yes!

**Comment by GarimaKapoor** [comment]
@krishnasrinivas, What is the timeline for the fix?

**Comment by harshavardhana** [comment]
> @krishnasrinivas, What is the timeline for the fix?

ping @krishnasrinivas

**Comment by harshavardhana** [comment]
> ping @krishnasrinivas

ping @krishnasrinivas are you working on this? - can take over if you are busy with other things.

**Comment by krishnasrinivas** [comment]
@harshavardhana working on this now

**Comment by harshavardhana** [comment]
> @harshavardhana working on this now

Okay.

**Comment by krishnasrinivas** [comment]
closed by https://github.com/minio/minio/pull/2813
