### ISSUE TITLE
browser: Browser bug found in docker edge image

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2702]
http://env-5085296.pb-de.jelastic.com/minio/docker/

![screenshot from 2016-09-14 17-27-22](https://cloud.githubusercontent.com/assets/622699/18534508/b7cf854a-7aa0-11e6-8f03-8cc148921fb7.png)
![screenshot from 2016-09-14 17-27-44](https://cloud.githubusercontent.com/assets/622699/18534509/b7cfc03c-7aa0-11e6-91c5-13986f338f37.png)

**Comment by harshavardhana** [comment]
Can upload files and see them through 'minio client' - @sych74 but looking into the bug. Did a quick local setup not able to reproduce.

**Comment by harshavardhana** [comment]
> Can upload files and see them through 'minio client' - @sych74 but looking into the bug. Did a quick local setup not able to reproduce.

Just now was able to reproduce looking into the issue.

**Comment by harshavardhana** [comment]
> Just now was able to reproduce looking into the issue.

Looks like false alarm, using 'docker-compose up' with the following profile seems to be working fine can you validate this on your end locally? 

```
$ cat docker-compose.yml 
version: '2'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio:edge
    ports:
      - "9001:9000"
    volumes:
      - /mnt/export/minio1:/export
    environment:
      MINIO_ACCESS_KEY: abcd1
      MINIO_SECRET_KEY: abcd1234
    command: minio1:/export minio2:/export minio3:/export minio4:/export
  minio2:
    image: minio/minio:edge
    ports:
      - "9002:9000"
    volumes:
      - /mnt/export/minio2:/export
    environment:
      MINIO_ACCESS_KEY: abcd1
      MINIO_SECRET_KEY: abcd1234
    command: minio1:/export minio2:/export minio3:/export minio4:/export
  minio3:
    image: minio/minio:edge
    ports:
      - "9003:9000"
    volumes:
      - /mnt/export/minio3:/export
    environment:
      MINIO_ACCESS_KEY: abcd1
      MINIO_SECRET_KEY: abcd1234
    command: minio1:/export minio2:/export minio3:/export minio4:/export
  minio4:
    image: minio/minio:edge
    ports:
      - "9004:9000"
    volumes:
      - /mnt/export/minio4:/export
    environment:
      MINIO_ACCESS_KEY: abcd1
      MINIO_SECRET_KEY: abcd1234
    command: minio1:/export minio2:/export minio3:/export minio4:/export
```

Sill need to see why there is an error on jelastic cluster though. Will be debugging this further today by rebuild minio with some additional logs on the jelastic cloud if that is fine with you? @sych74

**Comment by sych74** [comment]
I checked it with a fresh setup and seems like everything is fine 
http://docker90216-server104.demo.jelastic.com/minio/test2/ (use the same keys), not sure why that initially broken setup does not show the disk space...

**Comment by harshavardhana** [comment]
> http://docker90216-server104.demo.jelastic.com/minio/test2/ (use the same keys), not sure why that initially broken setup does not show the disk space...

Oh no idea will keep this bug here if you happen to see it again need to figure out why it could happen.

**Comment by harshavardhana** [comment]
Thanks for looking though @sych74

**Comment by harshavardhana** [comment]
Just checking back to see how are things going @sych74 ?  were you able to test minio distributed properly?

**Comment by sych74** [comment]
Seems like it works now as expected, at least initial setup and configuration. I was not able to test it under a high load as well as emulate a hardware failure, but I believe we can show it now to some of our users / partners and get their feedback.

**Comment by harshavardhana** [comment]
> Seems like it works now as expected, at least initial setup and configuration. I was not able to test it under a high load as well as emulate a hardware failure, but I believe we can show it now to some of our users / partners and get their feedback.

Closing this bug as i am not able to reproduce this anymore. Please re-open @sych74 if the problem persists.
