### ISSUE TITLE
SSL/TLS issue?

### ISSUE THREAD

**Issue by k0nsl** [minio/minio#2728]
## Minio version

```
root@relay01:~/go/bin# minio version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```
## System information

KVM running Debian (Sid).
## The issue

I have a problem connecting to my Minio instance through the various command line tools (i.e `s3cmd`, `mc`, `aws` and even GUI based tools, both for *nix and MS Windows.
When I try to use one application called `S3 Browser` it doesn't get further than this:
![https://k0nsl.img-cdn.ru/s3browser-win32_2016-09-17_20-16-58.png](https://k0nsl.img-cdn.ru/s3browser-win32_2016-09-17_20-16-58.png)

The directory `/root/.minio/certs` is empty. As per:

```
root@relay01:~/go/bin# ls -lah /root/.minio/certs
total 8.0K
drwx------ 2 root root 4.0K Sep 17 04:30 .
drwx------ 3 root root 4.0K Sep 17 14:20 ..
```

Is that intended?

When I run the CLI tool `aws` with the following parameters:

```
root@relay01:~# aws --endpoint-url https://s3.subdomain.domain.tld:443 --region us-east-1 s3 ls
```

And that produces the following:

> An error occurred (InvalidRequest) when calling the ListBuckets operation: You are attempting to operate on a bucket in a region that requires Signature Version 4.  You can fix this issue by explicitly providing the correct region location using the --region argument, the AWS_DEFAULT_REGION environment variable, or the region variable in the AWS CLI configuration file.  You can get the bucket's location by running "aws s3api get-bucket-location --bucket BUCKET".

That is it for now. I am probably terribly unclear and that is due to extreme lack of sleep. I just had to at least scribble down the gist of my problem with the hope that somebody has a solution to it.

Thanks in advance!

PS:
SSL is configured on the `domain.tld` 100% correctly. I can access Minio just fine through the reverse proxy (nginx in this case). I can upload files through the WebUI. But interacting with any of the available S3 compatible tools is a "no-no"; it just doesn't work for some reason.

**Comment by krishnasrinivas** [comment]
> When I try to use one application called S3 Browser it doesn't get further than this:

S3-browser is using older signature-v2 based auth hence it fails. Minio uses more recent signature-v4 algorithm for auth. http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

Can you check if the instructions here https://docs.minio.io/docs/aws-cli-with-minio helps?

**Comment by k0nsl** [comment]
@krishnasrinivas: Yes! Thank you. The documentation for aws-cli with Minio helped to solve my issue :D

I just ran:

```
aws configure set default.s3.signature_version s3v4
```

...and wham-bam, it works just fine now! Perfect.
