### ISSUE TITLE
minio hangs with two nodes with four disks

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2736]
With below command, I couldn't able to start minio.

on `minio1`:

```
minio server --address=:60000 minio2:/home/bala/sd{m..n}1/bala/mydisk minio1:/home/bala/sd{m..n}1/bala/mydisk
```

on `minio2`:

```
/tmp/minio server --address=:60000 minio2:/home/bala/sd{m..n}1/bala/mydisk minio1:/home/bala/sd{m..n}1/bala/mydisk
```

_/tmp/minio is copy of minio executable from `minio1`_

minio version:

``` bash
$ minio version
Version: 2016-09-19T17:33:27Z
Release-Tag: DEVELOPMENT.2016-09-19T17-33-27Z
Commit-ID: a955676986338d7b925ce61d06aa53e66c79f758
```

**Comment by harshavardhana** [comment]
Looks like the access key is not set, can you validate with access keys being set @balamurugana ?

**Comment by balamurugana** [comment]
Yep. Keys are not same in `minio1` and `minio2`.  Its working after having same config.json on both the machines.
