### ISSUE TITLE
NoSuchUpload: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.

### ISSUE THREAD

**Issue by olalonde** [minio/minio#2737]
## Expected behaviour

When trying to complete a multipart upload, I get an error message. However, if I use the minio web UI, I can see that the multipart upload did in fact complete. There is 2 parts to the upload, one of size 5MB and the other of just 1 byte.

Example params object I'm passing to s3.completeMultipartUpload:

```javascript
{ Key: 'foo',
  Bucket: 's3-tus-store',
  MultipartUpload:
   { Parts:
      [ { ETag: '"572a86744a2aff29e7c75405df4a4685"', PartNumber: 1 },
        { ETag: '"9033e0e305f247c0c3c80d0c7848c8b3"', PartNumber: 2 } ] },
  UploadId: 'ce1aac6b-3046-4dbb-9f9d-d8b3a7e18741' }
```

I tried "unquoting" the ETag values and that doesn't seem to help:

```
InternalError: We encountered an internal error, please try again.] message: 'We encountered an internal error, please try again.
```

When listing multipart uploads before completing, I am getting the following:

```javascript
{ Bucket: 's3-tus-store',
  KeyMarker: '',
  UploadIdMarker: '',
  NextKeyMarker: '',
  Prefix: '',
  Delimiter: '',
  NextUploadIdMarker: '',
  MaxUploads: 1000,
  IsTruncated: false,
  Uploads:
   [ { UploadId: 'ce1aac6b-3046-4dbb-9f9d-d8b3a7e18741',
       Key: 'foo',
       Initiated: 2016-09-19T19:30:10.215Z,
       StorageClass: '',
       Owner: { DisplayName: '', ID: '' },
       Initiator: { ID: '', DisplayName: '' } } ],
  CommonPrefixes: [],
  EncodingType: '' }
```

## Actual behaviour

Getting this error message with `aws-sdk-js`:

```
NoSuchUpload: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.] message: 'The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
```

## Steps to reproduce the behaviour

1. Create new multipart upload
2. Upload part
3. Upload other part
4. Complete multipart upload

Repo:

```sh
git checkout https://github.com/blockai/s3-tus-store.git
cd s3-tus-store
npm install
docker-compose up -d minio
npm run test:fast
```

## Minio version

Docker minio/minio image

```
# ./go/bin/app version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```

**Comment by olalonde** [comment]
Oh damn, it. That error was thrown somewhere else, because I was listing parts after the upload had completed. Sorry.

**Comment by krishnasrinivas** [comment]
@olalonde no problem, let us know if you face issues :)

**Comment by prasanna3000** [comment]
I am facing a similar issue. When I listed all the uploads, I can see my file in the uploads list but the completeMultiPart is giving 
`The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed` response.

I am not listing the uploads immediately after uploading. 

Here is the code I am running
`
        const bucketName = nconf.get('AWS_BUCKET_NAME_FOR_FILE_UPLOAD');

        // configure S3 to use
        const s3 = new AWS.S3({
            accessKeyId: 'string',
            secretAccessKey: 'string,
            signatureVersion: 'v4',
        });

        const params = {
            Bucket: bucketName,
            Key: fileName,
            MultipartUpload: {
                Parts: parts,
            },
            UploadId: uploadId,
        };
        return new Promise(
            (resolve, reject) => s3.completeMultipartUpload(params, (err, data) => {
                if (err) {
                    reject(false);
                } else {
                    resolve(true);
                }
            }));`

Any help would be really appreciated.

**Comment by namdiemefo** [comment]
did you find an answer @prasanna3000 ?
