### ISSUE TITLE
[distributed] events: Notifications should be fetched from all the nodes - Listen

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2741]

**Comment by GarimaKapoor** [comment]
@donatello please update the timeline for the fix!

**Comment by donatello** [comment]
@GarimaKapoor I believe it may take a week.

**Comment by GarimaKapoor** [comment]
@donatello if you need more help let @harshavardhana and @abperiasamy know. We should try to get it done sooner.

**Comment by harshavardhana** [comment]
Closing in favor of #2772
