### ISSUE TITLE
doc: Does Minio support multitenant environments?

### ISSUE THREAD

**Issue by k0nsl** [minio/minio#2751]
I couldn't find anything in the documentation when I glanced it over earlier this morning, about the possibility of having multiple users for one Minio instance. Does such a option exist?

**Comment by harshavardhana** [comment]
> I couldn't find anything in the documentation when I glanced it over earlier this morning, about the possibility of having multiple users for one Minio instance. Does such a option exist?

We don't support multiple users per Minio server we in-fact have it documented how to build multi tenancy  here https://github.com/krishnasrinivas/cookbook/blob/68b6dab51f557ed437449104970abcf3bacf4b7b/docs/multi-tenancy-in-minio.md

**Comment by harshavardhana** [comment]
Closing this. Captured in FAQs.
