### ISSUE TITLE
[distributed] Purge cached objects when disk has more recent copy

### ISSUE THREAD

**Issue by krisis** [minio/minio#2760]
## Expected behaviour
- Object layer cache could return stale copy of an object if the node receiving the GET request doesn't  receive the latest PUT request on the same object.
## Actual behaviour
- Object layer cache should purge its old copy of an object when discovered.
## Steps to reproduce the behaviour
- Setup:
  - 8 nodes each hosting a disk
- Issue a PUT object on node1
- Issue a PUT object with different data on node2
- Issue a GET object on node1
## System information

All platforms

**Comment by harshavardhana** [comment]
Fixed by #2770
