### ISSUE TITLE
[docs] Minio MS Windows + SSL

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2769]
Good day.
Cant start minio on Windows system with SSL - cant find any documents on it or help in minio --help
Found this topic https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio 
but no instruction for MS Windows

Please, help.
Does minio can start and works through SSL?

Thanx!

[REF] - https://github.com/minio/minio/pull/2768

**Comment by harshavardhana** [comment]
> Does minio can start and works through SSL?

Same instructions work for Windows as well @Andrey198

**Comment by Andrey198** [comment]
Good day, harshavardhana!
Thanx.
Questions for now:
 1.Can I use Self Signed certificate (private.key+public.crt) to start minio?

2.Following this https://github.com/minio/mc/issues/1220, trying to start minio 

_C:\minio>minio server c:\minio\home --cert public.cert --key private.key
**Unknown flags. 'c:\minio\home, --cert, public.cert, --key, private.key'**_

but minio cant resolve flags like --cert & --key (windows-amd64). What I missed?

3.According to this https://www.veritas.com/support/en_US/article.000081253, Symantec BE can backup cloud data from Amazon S3. Can I (somebody ever try it?) backup my data through minio?

Thanx for support!

**Comment by harshavardhana** [comment]
> 1.Can I use Self Signed certificate (private.key+public.crt) to start minio?

Yes you can - all you have to do is just copy `private.key` and `public.crt`  into your '.minio' directory it is located at 

```
C:\Users\<Username>\.minio\certs
```

> 2.Following this minio/mc#1220, trying to start minio
> 
> C:\minio>minio server c:\minio\home --cert public.cert --key private.key
> Unknown flags. 'c:\minio\home, --cert, public.cert, --key, private.key'
> 
> but minio cant resolve flags like --cert & --key (windows-amd64). What I missed?

These flags are not available since long time, all you need to do is just copy the certs. 

> 3.According to this https://www.veritas.com/support/en_US/article.000081253, Symantec BE can backup cloud data from Amazon S3. Can I (somebody ever try it?) backup my data through minio?

Yes it should work if Symantec BE supports AWS latest signature API.

**Comment by Andrey198** [comment]
Great! It works fine via SSL. Tanx again.

And the last questions I think:
1.How can I count PUT, COPY, POST, LIST and GET requests for minio?
2.Does minio server logging his work (log files or something else?)

Thanx, harshavardhana! Nice product!

**Comment by koolhead17** [comment]
Hello @Andrey198 
you can enable logging via .minio/config.json

```
 "logger": {
        "console": {
            "enable": true,
            "level": "error"
        },
        "file": {
            "enable": false,
            "fileName": "",
            "level": "error"
        },
        "syslog": {
            "enable": false,
            "address": "",
            "level": "debug"
        }
    },
```

You can publish Minio events to [AMQP](https://blog.minio.io/part-1-3-publish-minio-events-via-rabbitmq-8dd747632623#.4e3hg2ily), Redis or [elasticsearch](https://blog.minio.io/part-2-3-publish-minio-events-via-elasticsearch-ce7a080fa89f#.oiz9k5dl8)   

Let me know if this helps.

**Comment by Andrey198** [comment]
My config.json:

 "logger": {
        "console": {
            "enable": false,
            "level": "debug"
        },
        "file": {
            "enable": true,
            "fileName": "2log2.txt",
            "level": "debug"
        },
        "syslog": {
            "enable": false,
            "address": "",
            "level": "debug"
        }
    },

File 2log2.txt has been created, but always empty. If minio started, i cant delete this file - it already in use by minio. But no data in file. 
What i missed?

**Comment by koolhead17** [comment]
@Andrey198 Let me test it on my end and get back you.

**Comment by Andrey198** [comment]
Thanx, koolhead17 
- does logging system has retension policy. I mean log rotation in Mbytes, time (for example, 1 file for 1 wekk)?

**Comment by koolhead17** [comment]
@Andrey198 So this is how I was able to get log file read inside the file.

My config.json

```
{
    "version": "7",
    "credential": {
        "accessKey": "secret",
        "secretKey": "secret"
    },
    "region": "us-east-1",
    "logger": {
        "console": {
            "enable": false,
            "level": "error"
        },
        "file": {
            "enable": true,
            "fileName": "mylog1",
            "level": "error"
        },
        "syslog": {
            "enable": false,
            "address": "",
            "level": "debug"
        }
    },
```

Started minio server 

```
$ minio server a
$ mc ls myminio
$ mc mb myminio/atul
$ mc cp test.py  myminio/atul
```

This creates a logfile name `mylog1` in directory from where `minio` server is running.
 After this i deleted my data directory.

```
$ rm -rf a
$ mc ls myminio
```

I was able to see the logs

```
$ cat mylog1

{"cause":"disk not found","level":"error","msg":"Unable to fetch bucket info.","time":"2016-09-26T07:34:54-07:00"}

{"cause":"disk not found","level":"error","msg":"Unable to fetch bucket info.","time":"2016-09-26T07:34:56-07:00"}

{"cause":"disk not found","level":"error","msg":"Unable to list buckets.","time":"2016-09-26T07:35:03-07:00"}

{"cause":"disk not found","level":"error","msg":"Unable to list buckets.","time":"2016-09-26T07:35:04-07:00"}

{"cause":"disk not found","level":"error","msg":"Unable to list buckets.","time":"2016-09-26T07:35:05-07:00"}

{"cause":"disk not found","level":"error","msg":"Unable to list buckets.","time":"2016-09-26T07:35:05-07:00"}

{"cause":"disk not found","level":"error","msg":"Unable to list buckets.","time":"2016-09-26T07:35:09-07:00"}
```

RE: does logging system has retension policy:  This can be done outside minio,  some third party logging server.

Let me know if this helps.

**Comment by Andrey198** [comment]
koolhead17,

i have windows minio
changed my config.json like yours, start minio with homefolder. File was created and still zero bytes in it.

Then I delete home folder and refresh web-browser. Log file has got an error message about unavailable directrory and then was terminated unexpected.

Only one message I can see in log-file: error about missed folder.

I've delete directory that maped like bucket manually - Shift+Delete in Windows

Is it a bug? Am I have to delete data directory every time before minio is starting?
_After this i deleted my data directory._

**Comment by koolhead17** [comment]
@Andrey198 so now error is getting saved to the logfile as desired, please paste the error output you got here. It will help me in debugging.

**Comment by Andrey198** [comment]
Ok.
My envoriment (repo steps):
1. config.json

_{
    "version": "7",
    "credential": {
        "accessKey": "access",
        "secretKey": "secret"
    },
    "region": "us-east-1",
  "logger": {
        "console": {
            "enable": false,
            "level": "error"
        },
        "file": {
            "enable": true,
            "fileName": "mylog1",
            "level": "debug"
        },
        "syslog": {
            "enable": false,
            "address": "",
            "level": "debug"
        }
    },
    "notify": {
        "amqp": {
            "1": {
                "enable": false,
                "url": "",
                "exchange": "",
                "routingKey": "",
                "exchangeType": "",
                "mandatory": false,
                "immediate": false,
                "durable": false,
                "internal": false,
                "noWait": false,
                "autoDeleted": false
            }
        },
        "elasticsearch": {
            "1": {
                "enable": false,
                "url": "",
                "index": ""
            }
        },
        "redis": {
            "1": {
                "enable": false,
                "address": "",
                "password": "",
                "key": ""
            }
        }
    }
}_
1. using SSL (CERT folder inside .minio)
2. Folder with windows minio.exe is empty
3. Starting minio:
   _C:\minio>minio server c:\minio\home_
4. Successfully started and log it in console:
   _Endpoint:  https://ip:9000  https://127.0.
   AccessKey: access
   SecretKey: secret
   Region:    us-east-1
   SqsARNs:

Browser Access:
   https://ip:9000  https://127.0.0.1:9000_
1. See in minio directory 1 file and 1 folder:
- home
- mylog1
1. Manually delete folder "home"
2. Access for minio via web-browser
   9 Minio terminated, log file got a one message:
   _{"cause":"GetFileAttributesEx c:\minio\home: The system cannot find the file specified.","level":"fatal","msg":"Unable to get disk info c:\minio\home","time":"2016-09-26T18:25:28+03:00"}_

Please, help :-) Thanx

**Comment by koolhead17** [comment]
@Andrey198 That is exactly what I got, what did we miss?

**Comment by Andrey198** [comment]
Is it a question for me? )))
I cant tell U smth about this use-case, I just want to configure logging sub-system. 
Delete datafolder is not normal.

I set debug mode to file log

_"file": {
"enable": true,
"fileName": "mylog1",
"level": "debug"
},_

Before I've delete datafolder, log-file was empty. Originally, the task was following: count PUT and GET requests during working with minio cloud storage.

Can anybody help to correctly setup logging?

**Comment by koolhead17** [comment]
@Andrey198 As you understand Minio is an Object Storage and not a normal file server. To achieve your requirement simply enable/use Minio server bucket notification method. Please go through the blog links i have referred above, this will provide you info for every upload and object delete to bucket where or on which you have applied bucket policy. 

For logging the downloads @harshavardhana can answer, this looks like a new feature requirement. 😄

**Comment by koolhead17** [comment]
Can you alternatively open a new bug and close this one since this is not related to SSL anymore. IT will help us and community to search in better way. thanks again.

**Comment by harshavardhana** [comment]
> And the last questions I think:
> 1.How can I count PUT, COPY, POST, LIST and GET requests for minio?

You have to enable bucket notifications easiest way to achieve this is using 'mc watch' - https://docs.minio.io/docs/minio-client-complete-guide#watch

> 2.Does minio server logging his work (log files or something else?)

Server can log to console, file and syslog (not on windows)

**Comment by Andrey198** [comment]
Thax. SSL work perfect, other discussion in another issue.

Please, close issue. I cant do that

**Comment by harshavardhana** [comment]
> Thax. SSL work perfect, other discussion in another issue.
> 
> Please, close issue. I cant do that

Thanks. @Andrey198
