### ISSUE TITLE
Distributed: Minio server should notify about adding rest nodes to the cluster

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2771]
During 8 node cluster setup, when I executed below command on  one first node, it gave me no message. 

 it will be good idea to have a notification msg like please add other nodes in cluster or a msg like `node 192.168.1.1` added, please add rest nodes to the cluster.

```
./minio server --address=:9000 192.168.1.1:/home/minio/data 192.168.1.2:/home/minio/data 192.168.1.3:/home/minio/data 192.168.1.4:/home/minio/data 192.168.1.5:/home/minio/data 192.168.1.6:/home/minio/data 192.168.1.7:/home/minio/data 192.168.1.8:/home/minio/data 
```

**Comment by harshavardhana** [comment]
This will be fixed as part of #2652
