### ISSUE TITLE
[distributed] notifications and policy config in distributed XL

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2772]
notifications and policy config should be applied to all the minio servers in a cluster.

**Comment by harshavardhana** [comment]
> if notification is applied to only one minio server in d-XL, objects uploaded to other minio servers will not send notification event.

Glad you opened it, was working on a fix for this.

**Comment by harshavardhana** [comment]
> notifications and policy config should be applied to all the minio servers in a cluster.

Notifications are written to the backend so the notification.xml is erasure coded and cached as well. So all nodes do indeed see the same configuration. 

There is another problem of double caching at object-handler layer which i am removing as its not needed.  On the other hand there is one more bug which Aditya is fixing which is ListenBucketNotification() in a distributed mode.

**Comment by harshavardhana** [comment]
Fixed by #2891 and #2877
