### ISSUE TITLE
[document] MINIO_* environmental variables

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2773]
document all MINIO_\* env vars like MINIO_CACHE_SIZE MINIO_FSMETA etc

**Comment by harshavardhana** [comment]
This not only needs to be fixed with our docs.minio.io, we also need to update 'minio server' cli docs. We should also look at removing unnecessary env vars if not needed.

**Comment by koolhead17** [comment]
@GarimaKapoor will need your advice on where to get this added in docs.minio.io also @harshavardhana what part of code will get me all these infos so that i can get it documented.

**Comment by krishnasrinivas** [comment]
list:

MINIO_ENABLE_FSMETA
MINIO_TRACE
MINIO_PROFILER
MINIO_BROWSER
MINIO_ACCESS_KEY
MINIO_SECRET_KEY
MINIO_CACHE_SIZE
MINIO_CACHE_EXPIRY
MINIO_MAXCONN
MINIO_PROFILE_DIR

**Comment by koolhead17** [comment]
Thanks @krishnasrinivas

**Comment by krishnasrinivas** [comment]
@koolhead17 i have sent a PR as it needs a little code knowledge to write document

**Comment by koolhead17** [comment]
👍
