### ISSUE TITLE
docs: Deployment automation button for jelastic cloud

### ISSUE THREAD

**Issue by sych74** [minio/minio#2777]
Is there any interest to add a button that simplifies deployment and configuration of Minio XL in Jelastic cloud? There are many Jelastic cloud providers that offer free resources, so it should be useful for end users as they can try Minio and get an instant experience easily. There is an example of similar buttons (scroll down to Deployment section)  https://github.com/PokemonGoMap/PokemonGo-Map. Please let me know if so then I will add to Readme.md.

**Comment by harshavardhana** [comment]
> Is there any interest to add a button that simplifies deployment and configuration of Minio XL in Jelastic cloud? There are many Jelastic cloud providers that offer free resources, so it should be useful for end users as they can try Minio and get an instant experience easily. There is an example of similar buttons (scroll down to Deployment section) https://github.com/PokemonGoMap/PokemonGo-Map. Please let me know if so then I will add to Readme.md.

This is a great idea indeed @sych74 - right we do have a publicly accessible server at https://play.minio.io:9000 which runs with erasure coded backend. 

We are also bringing up another 8 set pine64 cluster to run Minio distributed mode.  

Please let us know if there is anything needed from our end @sych74 ?

**Comment by GarimaKapoor** [comment]
@sych74 Thats a great idea. We should have deployment button for different cloud providers like Digital Ocean, Jelastic , Packet etc. Let me discuss internally and get back to you.

**Comment by sych74** [comment]
@GarimaKapoor any feedback on this? Jelastic deployment automation button is ready. Please let me know if any additional information is needed from our side. Thanks

**Comment by deekoder** [comment]
Let's discuss and finalize on this task.

**Comment by sych74** [comment]
@deekoder the button is ready and placed in our repo https://github.com/jelastic-jps/minio. The following code can be used for adding the button to the current repo readme

`[![Deploy](https://github.com/jelastic-jps/git-push-deploy/raw/master/images/deploy-to-jelastic.png)](https://jelastic.com/install-application/?manifest=https://raw.githubusercontent.com/jelastic-jps/minio/master/manifest.jps&min-version=4.6) `  

Or we can provide you an interactive widget for a webpage http://www.smartfoxserver.com/cloud/jelastic

Let us know that works better.

**Comment by deekoder** [comment]
@sych74  - Thanks for making the button available! We are working on a mechanism where our partners like you can place their one click buttons. Please stay tuned.

**Comment by deekoder** [comment]
We dont have plans for partner level button integrations at this time. We will revisit this ask again when we plan to do partner level integration as buttons in the future.
