### ISSUE TITLE
[fs] : Relax 5% disk usage to a more cumulative number based on the total disk capacity.

### ISSUE THREAD

**Issue by JaCoB1123** [minio/minio#2780]
## Expected behaviour

Successful start of object-storage browser
## Actual behaviour

Error: Minimum '4' disks are required to enable erasure code
## Steps to reproduce the behaviour

Start server on non-root HDD/non-home? 
i.e. `minio server ~/test` works. `minio server /files/test` does not. Both are newly created, empty directories. /files is a mount-point to my big hdds
## Minio version

Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET

Commit-ID according to git: cfbab22237cb29d06b3df7d684ab208d8bc661e7
## System information

Ubuntu 14.04 x64
Go Version 1.7.1

**Comment by koolhead17** [comment]
@JaCoB1123 What would you like to achieve with this? You can run Minio as a standalone FS as well as distributed. 

To run it as a standalone FS, all you need to do is to run `minio server datadir`

To run it as a distributed store with Erasure code backend, at-east  4 disc or node will be needed. In your case  the command will be like  `$ minio server /mnt/export1/backend /mnt/export2/backend /mnt/export3/backend /mnt/export4/backend`  Our Erasure code guide has explained it in detail [here](https://docs.minio.io/docs/minio-erasure-code-quickstart-guide) 

Let me know if this helps.

**Comment by harshavardhana** [comment]
> Version: DEVELOPMENT.GOGET
> Release-Tag: DEVELOPMENT.GOGET
> Commit-ID: DEVELOPMENT.GOGET
> 
> Commit-ID according to git: cfbab22

Was able to run with latest `minio server ~/test`  - are you sure you were not running the same path for XL?

**Comment by JaCoB1123** [comment]
@koolhead17 @harshavardhana 
As written above it works as "standalone FS" when I use a path in my home-directory (e.g. `~/test`). As soon as I specify a single path on my other filesystem (`/files/test`) I get the error I mentioned above. I can't use a path in my homedir, since the filesystem is too small.

Is there a special flag to force the standalone FS?

Here's a full log of my tries:

```
~ jacob@nas
❯ minio server ~/test

Endpoint:  http://10.0.0.10:9000  http://127.0.0.1:9000
AccessKey: <censored>
SecretKey: <censored>
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://10.0.0.10:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.10:9000 <censored> <censored>

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
^C%                                                                                                                                  
~ jacob@nas
❯ minio server /files/test
ERRO[0000] intializing object layer failed               cause=Storage reached its minimum free disk threshold.

~ jacob@nas
❯ minio server min-free-disk 100M /files/test
FATA[0000] Invalid disk arguments for server.            cause=Minimum '4' disks are required to enable erasure code
```

**Comment by harshavardhana** [comment]
> minio server min-free-disk 100M /files/test
> FATA[0000] Invalid disk arguments for server.            cause=Minimum '4' disks are required to enable erasure code

This is not supported anymore you cannot change the 'min-free-disk' value that is why `minio server` treating them as disk arguments and reporting that you need minimum of 4 disks. 

> ❯ minio server /files/test
> ERRO[0000] intializing object layer failed               cause=Storage reached its minimum free disk threshold.

Here the total storage usage has reached minimum allowed i.e 5%  you might want to delete a few files. Can you do 'df -h' and see ?

**Comment by JaCoB1123** [comment]
```
/dev/sdb1       8,2T  7,8T  478G  95% /files
```

The 5% Threshold is really unfortunate. I still have 478G free which is more than enough for my needs.

**Comment by harshavardhana** [comment]
> The 5% Threshold is really unfortunate. I still have 478G free which is more than enough for my needs.

I see we can fix this by doing a dynamic allocation based on the disk size and have a algorithm percentile which proportionately scales.  Will fix it thanks for reporting the requirements @JaCoB1123

**Comment by JaCoB1123** [comment]
Thanks, sounds good.
I worked around this now by setting the `fsMinSpacePercent` to 1.
