### ISSUE TITLE
docs: Configure Minio using distributed filesystem backend load balancing with traefik?

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2781]
Document using distributed filesystem backend with multiple minio servers. With single writers and many readers.

**Comment by koolhead17** [comment]
@krishnasrinivas will need some help with you on this to understand scenario clearly. 😄

**Comment by krishnasrinivas** [comment]
@harshavardhana even single writer and multiple readers can be potentially risky. Because reader's read lock and writer's write lock would both succeed.

Taking one particular example:
reader does rlock() on an object and starts streaming it.
inbetween, the writer overwrites this object (because lock() would succeed as it is a different process)
now the reader will stream contents from the new object.

**Comment by krishnasrinivas** [comment]
only multiple readers with no writers at all is safe.

**Comment by harshavardhana** [comment]
> Taking one particular example:
> reader does rlock() on an object and starts streaming it.
> inbetween, the writer overwrites this object (because lock() would succeed as it is a different process)
> now the reader will stream contents from the new object.

This is upto the application to decide an object that is being written should never be read, our documentation here is about how to use traefik to channel writers to one server and all reads to other servers. We are not solving the conflicts problem here application still needs to hold a lock and synchronize.

**Comment by harshavardhana** [comment]
This can now be documented after shared backend code is merged.

**Comment by harshavardhana** [comment]
Closing this as not needed anymore.

**Comment by finid** [comment]
@harshavardhana, sorry to reopen this, but could you explain why this is not needed anymore?

**Comment by harshavardhana** [comment]
> @harshavardhana, sorry to reopen this, but could you explain why this is not needed anymore?

This is already documented.. @finid
