### ISSUE TITLE
Logging events on all buckets

### ISSUE THREAD

**Issue by Andrey198** [minio/minio#2785]
Good day, fox!
I need to log every event, or just PUT for example, on all home folder that ships all buckets in there.

For now, i'm started minio in Win64

_minio server c:\minio\home_

Then I've installed elasticsearch and add watch on current bucket.

_mc events add  myminio/asd24 arn:minio:sqs:us-east-1:1:elasticsearch --events put_

 I've see indexes, like wrote here https://blog.minio.io/part-2-3-publish-minio-events-via-elasticsearch-ce7a080fa89f#.ook2nf5mq:

 _"hits" : {
    "total" : 5,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "bucketevents",
      "_type" : "event",
      "_id" : "AVdqxqsp14HaY2oX3LPQ",
      "_score" : 1.0,
      "_source" : {
        "Records" : [ {
          "eventVersion" : "2.0",
          "eventSource" : "aws:s3",
          "awsRegion" : "us-east-1",
          "eventTime" : "2016-09-27T08:33:07.366Z",
          "eventName" : "s3:ObjectCreated:Put",
          "userIdentity" : {
            "principalId" : "minio"
          },
          "requestParameters" : {
            "sourceIPAddress" : "XXX.XXX.XXX.XXX:50268"
          },
          "responseElements" : { },
          "s3" : {
            "s3SchemaVersion" : "1.0",
            "configurationId" : "Config",
            "bucket" : {
              "name" : "asd24",
              "ownerIdentity" : {
                "principalId" : "minio"
              },
              "arn" : "arn:aws:s3:::asd24"
            },
            "object" : {
              "key" : "file.log",
              "size" : 32242,
              "sequencer" : "14782105F1108FE8"
            }
          }
        } ]
      }_

**The question №1 is**: how can i monitor and get data about all events like "s3:ObjectCreated:Put" about all buckets and objects in home folder c:\minio\home

I have to watch on all buckets.

**The question №2 is**: How can I to monitor events like BucketCreation? Is it possible?

**The question №3 is**: How can count PUT and GET queries, that client side initiates? In notification.xml I see only ObjectCreated and ObjectRemoved. I need to count uploading and downloading counts from minio server.

Thanx!

**Comment by harshavardhana** [comment]
If you want to log events on all buckets you need to enable notification for all buckets individually. @Andrey198 . This is similar to S3 specification.

**Comment by harshavardhana** [comment]
> The question №2 is: How can I to monitor events like BucketCreation? Is it possible?

You can't monitor events of bucket creation.

**Comment by harshavardhana** [comment]
> The question №3 is: How can count PUT and GET queries, that client side initiates? In notification.xml I see only ObjectCreated and ObjectRemoved. I need to count uploading and downloading counts from minio server.

This can be achieved through the application making the request itself rather than asking the server.  In anycase Put and Delete are only supported for more information you can read here - http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html

**Comment by Andrey198** [comment]
Thanx!
