### ISSUE TITLE
s3 browser and minio

### ISSUE THREAD

**Issue by Andrey198** [minio/minio#2786]
Good day again.

Somebody friends S3 browser (http://s3browser.com/) and minio?

When I try to do it, I've had a response from browser:

Server response: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

I've used minio over SelfSigned SSL and just over HTTP

Can anybody share with the way to get connect to minio via this broweser?
Thanx

**Comment by hackintoshrao** [comment]
Hello @Andrey198 : `Server response: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256` , 

From the above error response it looks like the `S3 Browser` client is using V2 signature version, Minio only supports V4 signature version. 
- You can use [v2->v4 proxy](https://github.com/minio/s3v2tov4-proxy) to get Minio to work with any V2 signature clients 

OR 
- You can check out the browser interface which comes bundled with Minio, check out this [simple guide](https://docs.minio.io/) on using Minio browser from the quick start guide page.

**Comment by Andrey198** [comment]
Thanx.
