### ISSUE TITLE
signature: Streaming signature sporadic issue not reproducible always. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2804]
--- FAIL: TestAPIPutObjectStreamSigV4Handler (0.03s)
    object-handlers_test.go:281: Test 2: Expected the response status to be `200`, but instead found `500`
    object-handlers_test.go:291: Test 2: FS: Object content differs from expected value.: <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/w1ts1q3judciakgiarh00nc69cgpmpvqedpozzugncu6hrhjsypwvxtdrhb3/test-object</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
FAIL

**Comment by harshavardhana** [comment]
// cc @krisis

**Comment by GarimaKapoor** [comment]
@krisis were you able to dig deeper on this issue. What are your thoughts?

**Comment by harshavardhana** [comment]
> @krisis were you able to dig deeper on this issue. What are your thoughts?

There is a possible fix already - https://github.com/minio/minio/pull/2862 . It requires some more test coverage once done we can merge and close this issue.

**Comment by krisis** [comment]
The fix doesn't completely eradicate the problem. This needs further investigation. I will be looking further into it.

**Comment by harshavardhana** [comment]
With new changes in #2621 @krisis - is the elusive issue gone now?

**Comment by krisis** [comment]
No. The sporadic failure is still present. Still investigating the issue. I have checked that the state transitions appear valid even in the presence of failure. The chunked data read also appears to be right. I am now investigating if our unit test utility function constructing streaming signature request is working as expected.

**Comment by harshavardhana** [comment]
> No. The sporadic failure is still present. Still investigating the issue. I have checked that the state transitions appear valid even in the presence of failure. The chunked data read also appears to be right. I am now investigating if our unit test utility function constructing streaming signature request is working as expected.

Perhaps that can be validated as well i suspect something is wrong in how the chunk signature itself is constructed.
