### ISSUE TITLE
May I use the method "presignedGetObject" to get a permanent url?

### ISSUE THREAD

**Issue by zhanjiejun** [minio/minio#2808]
I want a url to get Object without a expired time, what should I do?

**Comment by harshavardhana** [comment]
> I want a url to get Object without a expired time, what should I do?

You should use 'mc policy' to set bucket policies on your bucket.  @zhanjiejun

**Comment by harshavardhana** [comment]
Relevant documentation https://docs.minio.io/docs/minio-client-complete-guide#policy @zhanjiejun

**Comment by zhanjiejun** [comment]
Does the method "presignedPostPolicy" in Java Client API provide the same functionality?

**Comment by harshavardhana** [comment]
No it should be https://docs.minio.io/docs/javascript-client-api-reference#setBucketPolicy

**Comment by zhanjiejun** [comment]
Thx :)
But it's a javascript client api, what I want is **java client api**

**Comment by harshavardhana** [comment]
Sorry read it wrong here you go https://docs.minio.io/docs/java-client-api-reference#setBucketPolicy

**Comment by zhanjiejun** [comment]
Thank you very much ^^
I used to use version 2.0.1 and didn't see the method

**Comment by zhanjiejun** [comment]
Sorry to say that T_T
I see the method "setBucketPolicy" and "getBucketPolicy".
The method "getBucketPolicy" return a object of enum BucketPolicy, it doesn't provide any useful method.
Is there any sample can be used as reference?

**Comment by harshavardhana** [comment]
- https://github.com/minio/minio-java/blob/master/examples/GetBucketPolicy.java 
- https://github.com/minio/minio-java/blob/master/examples/SetBucketPolicy.java 

GetBucketPolicy is to fetch and display type of policy configured on the server.  That is the only purpose of that API. 

You can look at how to build proper Photo app
- https://github.com/minio/minio-java-rest-example

**Comment by harshavardhana** [comment]
Once you have set bucket policy as 'read-only' for a prefix or a bucket then you can access the URL publicly without using Presigned operations

``` java
minioClient.setBucketPolicy("my-bucketname", "downloads", BucketPolicy.ReadOnly);
```

Now say your endpoint is 'http://10.1.10.1:9000" then you can access any objects uploaded inside the "prefix" downloads as 

```
wget http://10.1.10.1:9000/my-bucketname/downloads/backups.tar.gz
```

**Comment by zhanjiejun** [comment]
appreciate you providing me these informations.
i'll try it right now.
Thank you again ^^
