### ISSUE TITLE
doc: document that watch is supported only for minio storage and not aws-s3

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2809]
Update the doc mentioning that  `mc mirror -w` does not work for aws-s3 and works only for minio.

**Comment by koolhead17** [comment]
@krishnasrinivas assign this to me for the docs, I will add a note mentioning only supported for Minio server not AWS S3. 😄

**Comment by krishnasrinivas** [comment]
@koolhead17 reopened the bug on mc, updated this issue to be a doc bug

**Comment by koolhead17** [comment]
👍

**Comment by koolhead17** [comment]
can be closed via https://github.com/minio/mc/pull/1842
