### ISSUE TITLE
Relax object name restrictions and fail at lower levels based on capabilities of backend

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2812]
An issue was reported where object name with ^ was not being created, check if it should be allowed.

**Comment by koolhead17** [comment]
@krishnasrinivas http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html  AWS is suggesting not to use Caret ("^")

`You should avoid the following characters in a key name because of significant special handling for consistency across all applications`

**Comment by krishnasrinivas** [comment]
@koolhead17 thanks

**Comment by gowithplanb** [comment]
The actual error (sensitive data has been replaced by XXX):

Sep 30 10:32:36 scp01 minio[1208]: {"cause":"Object name invalid: BUCKETNAME#XXX/XXX/XXX/XXX/XXX/XXX/XXX/XXX/XXX/XXX/XXX/b674e8220cfbee7d2d3dc6dfd2be8354^ff99f41357b1590715662e995b7c823f9704103c.XXX.XXX;XXX.XXX:/20160914090540/b674e8220cfbee7d2d3dc6dfd2be8354^ff99f41357b1590715662e995b7c823f9704103c.XXX.XXX;XXX.XXX","level":"error","msg":"Unable to create an object.","time":"2016-09-30T10:32:36+02:00"}

**Comment by gowithplanb** [comment]
@koolhead17 Thanks for pointing out the AWS document. I'm not sure if AWS S3 means to actually refuse objects that contain a carret symbol rather than to -avoid- (which has a different meaning to it) because it may interfere cross application. Minio just refuses it.

**Comment by krishnasrinivas** [comment]
file system can accomodate `^` though @harshavardhana what do you think

`mc cp /etc/passwd s3/kline/a^b` works fine

**Comment by harshavardhana** [comment]
> @koolhead17 Thanks for pointing out the AWS document. I'm not sure if AWS S3 means to actually refuse objects that contain a carret symbol rather than to -avoid- (which has a different meaning to it) because it may interfere cross application. Minio just refuses it.

We are reading the document as not just a warning but just avoid in general these special characters which do not add much value in the object name.

> file system can accomodate ^ though @harshavardhana what do you think

We need to verify if caret works for windows as directories and files, we can still relax this at object layer. Lower levels might fail if they don't support it independently.
