### ISSUE TITLE
[distributed] review all logging messages across codebase.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2815]

**Comment by solsson** [comment]
Confirmed that `minio/minio:edge@sha256:fe31cf94d1f5c1a74a92c0a9c001d1cb0fbf2d6ec9ec377ffa568b3bf16379e9` gives me explanation of the 403. Nice JSON log format. Great!

Edit: with `"console": { "enable": true, "level": "debug" }` in config.json that is.

**Comment by harshavardhana** [comment]
This is fixed by #3340
