### ISSUE TITLE
browser: Multi selection of objects should download all of them as a zipped file.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2817]

**Comment by GarimaKapoor** [comment]
@krishnasrinivas are you working on this? Do we have a timeline

**Comment by krishnasrinivas** [comment]
@rushenn can you do the UI changes needed? It will be same as the multi-delete, in addition to delete we need to provide a "download as zip" button.

**Comment by harshavardhana** [comment]
Added @rushenn here as well.

**Comment by krishnasrinivas** [comment]
This got auto closed, @harshavardhana this can be reopened as it was a partial server side fix. Browser fix still needed.

**Comment by GarimaKapoor** [comment]
@rushenn what the update on this issue?

**Comment by krishnasrinivas** [comment]
Can be closed. Fixed by 52d6678bf0d1442d0ab9b7bc63b47ceda69d0e4a
