### ISSUE TITLE
docs: document distributed Minio deployment using kubernetes (k8s)

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2825]

**Comment by koolhead17** [comment]
I am working on  kubernetes, would love to take this task. 😄 
cc: @GarimaKapoor @harshavardhana

**Comment by JackTiger** [comment]
How progress about deploying in k8s with multi-node? @koolhead17 @harshavardhana @NitishT  Ths  very much!

**Comment by nitisht** [comment]
Hey  @JackTiger I will send you a yaml file tonight.

**Comment by nitisht** [comment]
Hi @JackTiger you can use this yaml to create a 4 node distributed Minio on k8s. https://gist.github.com/NitishT/ded3bd58e1269c6490c07547cb3ab066

This is still WIP, but will help you get started.

**Comment by JackTiger** [comment]
Ths very much!

**Comment by GarimaKapoor** [comment]
@NitishT you can close this issue one the post is published on 26th Jan.

**Comment by nitisht** [comment]
@GarimaKapoor I need to add docs on docs.minio.io also

**Comment by GarimaKapoor** [comment]
Yes! forgot on that. We will need to officially document in our docs as well.

**Comment by JackTiger** [comment]
Great Job!!

**Comment by john-bakker** [comment]
is this ever added to the minio documentation ?  on docs.minio.io ?

**Comment by nitisht** [comment]
@john-bakker https://docs.minio.io/docs/deploy-minio-on-kubernetes
