### ISSUE TITLE
validate SSL on CentOS

### ISSUE THREAD

**Issue by Andrey198** [minio/minio#2827]
Good day to all!

Now I cant start minio with SSL

Here instruction https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio 

after

 ./minio server directory/

Minio started on HTTP

How can I troubleshoot it?

p.s. enabled logging in config like:

"console":{
"enable":true,
"level": ""debug
}

but no messages about cert error

What I missed

Thanx

**Comment by krishnasrinivas** [comment]
@Andrey198 can you paste the output of `ls ~/.minio/certs/`

**Comment by Andrey198** [comment]
Here ls command:

_private.key public.crt_

**Comment by Andrey198** [comment]
p.s. This key I buy with SSL certificate

**Comment by harshavardhana** [comment]
@Andrey198 are you sure 'certs' are in the right directory and have right permissions for 'minio server' to access?  -  We have a running server at https://play.minio.io:9000 with SSL so it shouldn't be a problem.

**Comment by Andrey198** [comment]
My minio is inside /etc/minio

folder with certs - ".minio" in /root/.minio/certs

Is it correct?

**Comment by harshavardhana** [comment]
> My minio is inside /etc/minio
> 
> folder with certs - ".minio" in /root/.minio/certs
> 
> Is it correct?

No you need to have 'certs' inside '/etc/minio'

**Comment by cherbunin** [comment]
> Hi! Folder 'certs' already exist. How we can set 'certs' path manually?

**Comment by Andrey198** [comment]
What I ve did wrong?

http://s020.radikal.ru/i707/1610/8f/d62adc4349d8.png

**Comment by Andrey198** [comment]
U've wrote that 'certs' have to be in .minio config folder

_https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio

$ cp my-certs/private.key /home/supernova/.minio/certs/
$ cp my-certs/public.crt /home/supernova/.minio/certs/_

Is it wrong?

**Comment by harshavardhana** [comment]
Certs folder is referenced from the config folder for example like this here is the local configuration of HTTPS how it looks like.

```
./mygo/bin/minio server /mnt/data
```

```
ubuntu@minio-play:~$ mc ls .minio/
[2016-03-26 09:44:39 UTC] 4.0KiB certs/
[2016-10-03 01:23:27 UTC] 1.1KiB config.json
[2016-10-03 01:23:27 UTC] 1.1KiB config.json.old
ubuntu@minio-play:~$ mc ls .minio/certs/
[2016-03-26 09:44:31 UTC] 1.7KiB private.key
[2016-03-26 09:44:14 UTC] 3.4KiB public.crt
```

Now you are keeping configs in a separate folder for example '/etc/minio' then you should do 

```
./minio server --config-dir /etc/minio 
```

In this case minio server is looking for `certs` inside '/etc/minio' -  make sure to keep 'certs' inside '/etc/minio'

**Comment by Andrey198** [comment]
./minio server --config-dir /etc/minio

Answer: Unknown flags. '--config-dir, /etc/minio/'

Am I have to run it in utility "mc"? Or I have to set config-dir via ./minio start server?

Thanx

**Comment by harshavardhana** [comment]
> ./minio server --config-dir /etc/minio

@Andrey198 './minio --config-dir /etc/minio server <testdir>'

**Comment by harshavardhana** [comment]
> ./minio server --config-dir /etc/minio
> @Andrey198 './minio --config-dir /etc/minio server <testdir>'

@Andrey198 were you able to use './minio --config-dir' ?

**Comment by Andrey198** [comment]
Config-dir is worked for me, but still cant start minio over SSL :-(
No SSL on CentOS?

http://s017.radikal.ru/i440/1610/ad/b5b6ecd37ebf.png

**Comment by harshavardhana** [comment]
> Config-dir is worked for me, but still cant start minio over SSL :-(
> No SSL on CentOS?
> 
> http://s017.radikal.ru/i440/1610/ad/b5b6ecd37ebf.png

We will investigate further can you provide more details on the setup?

**Comment by Andrey198** [comment]
Harshavardhana, I've started minio over HTTPS on CentOS. Thank U!

What i've done:
- aim to new config-dir
- delete folder "certs"
- create new "certs" folder and copy once againt private.key and public.crt

What I had find out:
- version of minio was 6. Upgraded it to 7,
- in folder certs after many manipulations, i found that private.key and public.crt are the folders too (not files). In each one i found 2 files: json and part1 (not exactly like this, but similar). How it happens - cant understand. I've delete them and copy again. Then change owner (**sudo chown username:username**) and start minio

Voila! Minio started over https with valid certificate.

I dont think that is a bug, but no understandings how it happens.

p.s. pair of keys previously i uploaded to minio server via web-inerface. Maybe it changed them..?

Thanx for first-line support!

**Comment by harshavardhana** [comment]
> I dont think that is a bug, but no understandings how it happens.

This happened perhaps as you said you uploaded certs through the browser and perhaps previously data directory was '/etc/' 

> p.s. pair of keys previously i uploaded to minio server via web-inerface. Maybe it changed them..?
> 
> Thanx for first-line support!

No thanks for your patience.
