### ISSUE TITLE
docs: Questions on load testing tool and other resources Minio server uses

### ISSUE THREAD

**Issue by sych74** [minio/minio#2829]
We are going to publish an article about minio xl at our blog soon, but we are missing some information about resource usage under the load. In other words we want to figure out how much resources minio server consumes at different level of the load. Do you have any preconfigured load testing tool? If you use something for internal load testing then I believe we can set it on an environment inside Jelastic and check the resource consumption. Please advise.

**Comment by harshavardhana** [comment]
> We are going to publish an article about minio xl at our blog soon, but we are missing some information about resource usage under the load. In other words we want to figure out how much resources minio server consumes at different level of the load. Do you have any preconfigured load testing tool? If you use something for internal load testing then I believe we can set it on an environment inside Jelastic and check the resource consumption. Please advise.

The things to know about minio server in default configuration 
- MINIO_CACHE_SIZE defaults to 8GB if RAM size is smaller than 8GB  -  80% of the RAM size is used instead. 
- MINIO_CACHE_EXPIRY defaults to 72hrs.
- MINIO_MAXCONN to limit number of concurrent requests to be served by default it is unlimited.

These values can be configured to any value depending on the load and can be configured based on the application itself.  These have direct impact on the server behavior and how much resources server does consume. 

Server usually has minimal footprint on the resources but to increase and test the load we use tools like `aws cli` to upload in parallel.  

Recent result from Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

Setup Details
-  2 node setup with 4 drives.
- Minio 2 and Minio3 are the nodes with the server running.
- 200 parallel Get Object of 1GB is generated from Minio1 for each Minio2 and Minio3 (4000 requests in total aws cli does parallel GET requests)

Results
- Load test on both Minio2 and Minio3 finished in approximately 20 minutes.
- Memory usage peaked to 20GB`

**Comment by harshavardhana** [comment]
efau

**Comment by harshavardhana** [comment]
Now if you wish to generate profiles and understand the overall system behavior we use Go's standard profiling mechanism. 

Set  `MINIO_PROFILER=mem|cpu|block`  memory, cpu and block profiling when running load tests to help generate profiler details. TO generate these profiles in a custom directory use `MINIO_PROFILE_DIR`. These graphs and values provide better indication of bottlenecks and load.

**Comment by sych74** [comment]
Thanks for the prompt reply. The details are helpful. So, how much resources you recommend to allocate for an instance by default - 20GB RAM? I understand that it depends on the load, but default configs are always present usually. 

Also if you have any "ready-to-use" testing solution then it will be easier to change url link to the remote minio server and run set of the tests on the env hosted in Jelastic.

**Comment by harshavardhana** [comment]
> Thanks for the prompt reply. The details are helpful. So, how much resources you recommend to allocate for an instance by default - 20GB RAM? I understand that it depends on the load, but default configs are always present usually.

20GB is plenty but this depends on the load. 

> Also if you have any "ready-to-use" testing solution then it will be easier to change url link to the remote minio server and run set of the tests on the env hosted in Jelastic.

We don't have any testing solution we just use 'aws cli' and 'mc' , but we have plans to implement and we haven't prioritized it yet.

**Comment by GarimaKapoor** [comment]
@sych74 let us know if you need anything else from us for your blog post.

**Comment by sych74** [comment]
@GarimaKapoor does the **latest** docker image tag include MinioXL? We are waiting for a stable release, related to this issue https://github.com/minio/minio/issues/2850.
Thanks

**Comment by koolhead17** [comment]
@sych74 We have made distributed release and installation details are available on [https://docs.minio.io/docs/minio-docker-quickstart-guide](https://docs.minio.io/docs/minio-docker-quickstart-guide)

**Comment by sych74** [comment]
Passed to QA department today, expecting to get results the next week, will keep you informed.

**Comment by harshavardhana** [comment]
@sych74 all the load testing tools are being collated here - https://github.com/minio/perftest

**Comment by deekoder** [comment]
@sych74 closing this. Please let us know if we have not addressed your question. We will reopen this issue.
