### ISSUE TITLE
Minio does not recognize directories with " "'s as buckets... 

### ISSUE THREAD

**Issue by badscooter23** [minio/minio#2830]
## Expected behaviour

I am not 100% sure what the expected behavior should be... see below
## Actual behaviour

Start minio server ... 
minio*\* server ~/foo

Suppose the datasets dir contained the following sub-directories... 

sub dir 1
sub-dir-2

sub-dir-2 (with the dashes) will show up as a bucket in Minio (client or cli)... 
"sub dir 1" (with blanks instead of dashes) will not show up in Minio 

Is this a Bug? Or a "feature" of AWS Compatibility?  (see below) 
I suspect that this may be related to the legal syntax for a AWS bucket (and Mino following strict compatibility).

If "blanks" are illegal in bucket names, then:

a) should ./minio server warn users that certain sub-directories will not show up as buckets due to "illegal" names? 
b) should minio somehow map these dir names to legal bucket names? 
c) Is it working the way it should? 

??? 
## Steps to reproduce the behaviour

See above
## Minio version
- (paste output of `minio version`)
  New update: https://dl.minio.io/server/minio/release/darwin-amd64/minio?update=yes 

Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2
## System information

I am sure it does not matter, but... 
MacBook Pro, El Capitan V 10.11.5
2.8 GHz Intel Core i7
16GB mem

**Comment by harshavardhana** [comment]
> a) should ./minio server warn users that certain sub-directories will not show up as buckets due to "illegal" names? 

http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html - the bucket restrictions.  We can warn but we avoided any form of logging unless it is really useful in this case we can warn. 

> b) should minio somehow map these dir names to legal bucket names? 

No this we won't do. 

> c) Is it working the way it should?

Yes it is correct. 

Buckets have limitations in terms of how it is named but you can have prefixes or objects which can carry spaces. 

```
$ mc cp CONTRIBUTING.md 'play/harsha/I am here as a contributor.md'
$ mc ls play/harsha/
[2016-10-03 10:37:53 PDT] 740KiB Anderson_Terry_Kal_Toh.pdf
[2016-10-03 11:02:10 PDT] 2.7KiB I am here as a contributor.md
$ 
```

**Comment by harshavardhana** [comment]
Closing this added a new bug - https://github.com/minio/minio/issues/2832
