### ISSUE TITLE
browser: Appears to timeout on bucket with large number of files (intermittent)

### ISSUE THREAD

**Issue by badscooter23** [minio/minio#2831]
## Expected behaviour

It would be better if the client did not time out ... :(

For directories / buckets with LARGE numbers of files there is probably a more user friendly behavior (perhaps warning the user that it will take a long time to render, rendering the list a "page" at a time, allowing the user some control over the behavior, etc). 
## Actual behaviour

On a test minio system (small/laptop installation) - Minio client times out (intermittently) on a bucked that contains many image files... 

I _suspect_ the problem is the large number of files, but it could be something else... 
## Steps to reproduce the behaviour

I downloaded the "State Farm Distracted Driver" dataset from Kaggle... 
https://www.kaggle.com/c/state-farm-distracted-driver-detection/data

I started Minio server on my datasets directory... 

Scotts-MacBook-Pro-2:datasets scott$ pwd
/Users/scott/datasets
Scotts-MacBook-Pro-2:datasets scott$ ls -l
total 0
drwxr-xr-x  5 scott  staff  170 Sep 21 14:28 airlines
drwxr-xr-x  5 scott  staff  170 Sep 24 12:21 digit-reconition
drwxr-xr-x  7 scott  staff  238 Sep 21 12:50 redhat-kaggle
drwxr-xr-x  6 scott  staff  204 Oct  3 10:10 sf-distracted-driver
drwx------@ 7 scott  staff  238 Sep 21 14:29 thecounted-data
drwx------@ 6 scott  staff  204 Sep 21 14:28 thecounted-data-old

The "sf-distracted-driver" bucket contains sub-buckets (directories)

Scotts-MacBook-Pro-2:datasets scott$ find sf-distracted-driver -type d
sf-distracted-driver
sf-distracted-driver/imgs
sf-distracted-driver/imgs/test
sf-distracted-driver/imgs/train
sf-distracted-driver/imgs/train/c0
sf-distracted-driver/imgs/train/c1
sf-distracted-driver/imgs/train/c2
sf-distracted-driver/imgs/train/c3
sf-distracted-driver/imgs/train/c4
sf-distracted-driver/imgs/train/c5
sf-distracted-driver/imgs/train/c6
sf-distracted-driver/imgs/train/c7
sf-distracted-driver/imgs/train/c8
sf-distracted-driver/imgs/train/c9

The sf-distracted-driver/images/test directory contains 79727 files:

Scotts-MacBook-Pro-2:datasets scott$ ls -l sf-distracted-driver/imgs/test | wc -l
   79727

When you click on "test" under sf-distracted-driver, imgs in Minio Client you will get a 
"spinning wheel" for quite some time (30seconds +/-) then a message that Minio Client 
is non-responsive. 

NOTE: It does appear to be somewhat intermittent - on a subsequent attempt it did "complete" and listed all the "objects" (images) in the bucket. 
## Minio version
- (paste output of `minio version`)

Scotts-MacBook-Pro-2:Downloads scott$ ./minio version 

  New update: https://dl.minio.io/server/minio/release/darwin-amd64/minio?update=yes 

Version: 2016-08-21T02:44:47Z
Release-Tag: RELEASE.2016-08-21T02-44-47Z
Commit-ID: 975eb319730c8db093b4744bf9e012356d61eef2
## System information

MacBook Pro
OS X El Capitan v 10.11.5
Processor: 2.8 GHZ Intel Core i7
Mem 16GB

**Comment by vadmeste** [comment]
> When you click on "test" under sf-distracted-driver, imgs in Minio Client you will get a 
> "spinning wheel" for quite some time (30seconds +/-) then a message that Minio Client 
> is non-responsive.

Did you mean Minio Browser ? Minio Client has another meaning (https://docs.minio.io/docs/minio-client-quickstart-guide)

> Scotts-MacBook-Pro-2:Downloads scott$ ./minio version
> 
> New update: https://dl.minio.io/server/minio/release/darwin-amd64/minio?update=yes

You are running an outdated version of Minio, can you download the last version and test again? ( https://www.minio.io/downloads/ )

**Comment by badscooter23** [comment]
Yes... sorry for the confusion.. I meant Minio Browser (not Minio Client); I'll try a newer version when  I get a chance and update the results here...

**Comment by harshavardhana** [comment]
> Yes... sorry for the confusion.. I meant Minio Browser (not Minio Client); I'll try a newer version when I get a chance and update the results here...

The error listing might be because browser listing is not efficient yet since it waits for the entire list, we are fixing that  - https://github.com/minio/miniobrowser/issues/189

**Comment by badscooter23** [comment]
I retested with the latest version 

./minio version
Version: 2016-09-11T17:42:18Z
Release-Tag: RELEASE.2016-09-11T17-42-18Z
Commit-ID: 85e2d886bcb005d49f3876d6849a2b5a55e03cd3

The behavior is the same... 
I agree that, based on the symptom, it is likely that the timeout is caused by waiting for the entire list  ... so the new version will likely address the problem...

**Comment by GarimaKapoor** [comment]
@krishnasrinivas do we have a timeline for the fix?
