### ISSUE TITLE
Endpoint gets redirected when server started with browser disabled

### ISSUE THREAD

**Issue by muminoff** [minio/minio#2837]
## Expected behaviour

Endpoint shouldn't be redirected to `/minio`
## Actual behaviour

Started minio server with browser disabled, but default endpoint URL is getting redirected to `/minio`
## Steps to reproduce the behaviour

```
$ MINIO_BROWSER=off minio server ~/storage/

Endpoint:  http://192.168.0.67:9000  http://127.0.0.1:9000  http://192.168.99.1:9000
AccessKey: floppyfloppy
SecretKey: floppyfloppy
Region:    us-east-1
SqsARNs:

Browser Access:
   http://192.168.0.67:9000  http://127.0.0.1:9000  http://192.168.99.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.0.67:9000 floppyfloppy floppyfloppy

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide


$ curl -i -X GET http://127.0.0.1:9000

HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Server: Minio/RELEASE.2016-09-11T17-42-18Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: XG1DQ5BWMJUD3FFQ
Date: Tue, 04 Oct 2016 07:11:39 GMT
Content-Type: text/xml; charset=utf-8
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

⬆️  `curl` seems to be acting good, but browsers (Chrome, Safari, Firefox) are getting redirected.

See screenshots below:

![chrome](https://cloud.githubusercontent.com/assets/1235454/19065352/047a1fba-8a4e-11e6-8daf-125255923621.jpg)
![firefox](https://cloud.githubusercontent.com/assets/1235454/19065353/047ba4ac-8a4e-11e6-8ca5-d485656858dc.jpg)
![safari](https://cloud.githubusercontent.com/assets/1235454/19065354/0481b66c-8a4e-11e6-8b8a-69f268f92037.jpg)
## Minio version
- (paste output of `minio version`)

```
$ minio version
Version: 2016-09-11T17:42:18Z
Release-Tag: RELEASE.2016-09-11T17-42-18Z
Commit-ID: 85e2d886bcb005d49f3876d6849a2b5a55e03cd3
```
## System information

OSX El Capitan (10.11.6)

EDIT: Markdown format

**Comment by muminoff** [comment]
Please, note browsers are started with private/incognito mode to prevent using cache.

**Comment by krishnasrinivas** [comment]
timeline - 5th
