### ISSUE TITLE
tests: Need better coverage for control-heal-main.go

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2840]

**Comment by GarimaKapoor** [comment]
@krisis pease update the timeline for the fix.

**Comment by hackintoshrao** [comment]
Timeline - 10th october.

**Comment by harshavardhana** [comment]
> Timeline - 10th october.

are you working on this issue? ping @krisis

**Comment by hackintoshrao** [comment]
I've put timeline on the wrong issue, sorry.

**Comment by krisis** [comment]
I expect to fix this issue by the 10th Oct.

**Comment by GarimaKapoor** [comment]
@krisis please update the status of this issue.

**Comment by krisis** [comment]
I have not looked into this issue. I am investigating the root cause for sporadic failure of streaming signature putobject API request.

**Comment by harshavardhana** [comment]
> I have not looked into this issue. I am investigating the root cause for sporadic failure of streaming signature putobject API request.

Will be fixed in the control-heal refactor, taking this issue and closing #2491
