### ISSUE TITLE
tests: Need better coverage for bucket-policy-handler.go.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2841]

**Comment by GarimaKapoor** [comment]
@hackintoshrao what is the timeline for the fix.

**Comment by hackintoshrao** [comment]
Timeline - 6th October.

**Comment by hackintoshrao** [comment]
bucket-handler.go contains a large collection of API's, opening a new issue to address it.

**Comment by hackintoshrao** [comment]
Current coverage for `bucket-policy-handlers.go` is 93.5 % , Closing the issue.

**Comment by harshavardhana** [comment]
> Current coverage for bucket-policy-handlers.go is 93.5 % , Closing the issue.

You the man!
