### ISSUE TITLE
can't push docker image with 5G+ layer

### ISSUE THREAD

**Issue by swimablefish** [minio/minio#2843]
## Expected behaviour

when use docker registry, can push docker  image with 5G+ layer
## Actual behaviour

time="2016-10-04T05:11:31Z" level=error msg="response completed with error" err.code=unknown err.detail="s3aws: EntityTooLarge: Your proposed upload exceeds the maximum allowed object size.\n\tstatus code: 400, request id: 5TRXC53B06CA64R3" err.message="unknown error" go.version=go1.
## Steps to reproduce the behaviour

docker push an image with 5G+ layer
## Minio version
- (paste output of `minio version`)
  VERSION
  2016-04-17T22:42:41Z
## System information

MEMORY
Used: 9.2GB | Allocated: 126GB | Used-Heap: 9.2GB | Allocated-Heap: 9.2GB
PLATFORM
Host: b4c745c82655 | OS: linux | Arch: amd64
RUNTIME
Version: go1.6 | CPUs: 32

**Comment by harshavardhana** [comment]
> (paste output of minio version) VERSION 2016-04-17T22:42:41Z

This seems like you are using really old version of Minio can you try the latest? https://minio.io/downloads ?

**Comment by harshavardhana** [comment]
> This seems like you are using really old version of Minio can you try the latest? https://minio.io/downloads ?

Were you able to try the recent version of Minio? @swimablefish

**Comment by harshavardhana** [comment]
> Were you able to try the recent version of Minio? @swimablefish

Closing this as working @swimablefish - please re-open if you see the problem again.
