### ISSUE TITLE
tests/bench: move to table driven benchmarks.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2844]
The table driven benchmarking facility which comes with Go 1.7 makes the setup for similar benchmarks ( BenchmarkGetOjbect\* , BenchmarkPutObject*) easier, also maintainance and readability of table driven benchmarks is higher, should make changes to Benchmark to use those facilities/style.

**Comment by harshavardhana** [comment]
Not part of distributed release, moving this to future.

**Comment by GarimaKapoor** [comment]
@hackintoshrao what is the status of this issue?

**Comment by hackintoshrao** [comment]
Missed out on this after it was labelled future. Taking it up.

**Comment by harshavardhana** [comment]
> Missed out on this after it was labelled future. Taking it up.

Not in future anymore.

**Comment by deekoder** [comment]
Need to discuss and understand how we are proceeding here.

**Comment by deekoder** [comment]
We need to add these as part of mint suite at a later time. Closing as won't fix in minio server repo here.
