### ISSUE TITLE
Can I disable authentication for GET requests to particular bucket?

### ISSUE THREAD

**Issue by kuatro** [minio/minio#2845]
Is there any way to disable authentication for direct browser request if I don't want to trigger my web app on every `GET /some_file.jpg` request? I think it's going to be a good approach to store and deliver static content as precompiled images, CSS, JS etc.

**Comment by vadmeste** [comment]
@kuatro, this can be done by setting download policy to your bucket using mc or any minio library

`$ mc policy download myminio/yourbucket/`

**Comment by kuatro** [comment]
@vadmeste Thank you! Don't know how I missed it in the documentation.

**Comment by koolhead17** [comment]
hello @kuatro https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#policy should help. 😄
