### ISSUE TITLE
Set default URL for presignedUrl

### ISSUE THREAD

**Issue by tspoke** [minio/minio#2848]
In a docker-compose file I build : 
- minio => minio:9000
- api => api:3000
- nginx => 0.0.0.0:80

The nginx redirections : 
- 0.0.0.0/  => minio:9000
- 0.0.0.0/api  => api:3000
## Expected behaviour

When requesting the API for a resource, the API should return a public URL to access to it not the container's address.
## Actual behaviour

The API returns a presigned url built with the docker address and not the public address. If I edit the returned host with the public host the key mismatch and I can't access to the resource.
## Steps to reproduce the behaviour

Run a docker with these containers :
1. A minio container on minio:9000
2. A server API container on api:3000
3. Instantiate minio and set the endpoint/port to minio's container.
4. A nginx server on 80 redirecting / to minio and /api to the API
## How I fixed it

To fix this issue I setup my nginx to modify the host : 

```
location / {
    proxy_set_header Host minio:9000;
    proxy_pass        http://minio:9000;
  }
```

And on the API side I rewrite the host before sending the presignedUrl : 

``` js
MinioStorage.prototype.getURL = function(bucketName, filename, cb, expiry) {
    expiry = expiry || 3600*24*2; // 2 days
    var self = this;
    this.minioClient.presignedGetObject(bucketName, filename, expiry, function(err, presignedUrl) {
        if(cb) {
            cb(err, {
                container: bucketName,
                filename: filename,
                url: presignedUrl.replace(self.internalURL, self.publicURL)
            });
        }
    });
};
```
## Minio version

RELEASE.2016-09-11T17-42-18Z
### Minio client configuration

I think it could be nice to customize the public url that minio should use to generate presignedUrl directly when a client instantiate the minioClient.

Something like : 

``` js
this.minioClient = new Minio({
        endPoint: ...,
        port: ...,
        secure: ...,
        accessKey: ...,
        secretKey: ...,
        publicUrl: 0.0.0.0 /* Here the URL I want to use in presigned url */
});
```
### Docker configuration

Or, add a Environment variable to allow docker to inject to it : PUBLIC_URL

Thank you.

**Comment by harshavardhana** [comment]
Presigned URL is generated by client and cannot be modified to have custom endpoints after the fact of generation. 

```
this.minioClient = new Minio({
        endPoint: ...,
        port: ...,
        secure: ...,
        accessKey: ...,
        secretKey: ...,
        publicUrl: 0.0.0.0 /* Here the URL I want to use in presigned url */
});
``` 

^^^ This is an application responsibility you can create a new 'this.minioClient' which points to a different endpoint.  You can have a collection of endpoints this would solve your problem. 

In-fact using a proxy is a correct approach as welll here.
