### ISSUE TITLE
Incompatibility with AWS java SDK

### ISSUE THREAD

**Issue by jlebloas** [minio/minio#2849]
Hello,

I face an compatibility while using the last java SDK with your last minio server. The issue is the order in the xml in response, the `<Name>` stands after the `<Contents>` thus creating a bug with the SDK.
## Expected behaviour

Having the `<Contents>`  after the name.
## Actual behaviour

```
GET /my-bucket-name/?prefix=aPrefix%2F&delimiter=%2F&encoding-type=url HTTP/1.1
[HEADERS]

HTTP/1.1 200 OK
Accept-Ranges: bytes
Server: Minio/RELEASE.2016-09-11T17-42-18Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 9YRQE2TWVBNME28M
Date: Tue, 04 Oct 2016 14:08:00 GMT
Content-Type: text/xml; charset=utf-8
Transfer-Encoding: chunked

387
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Contents>
        <ETag></ETag>
        <Key>aPrefix/aKey</Key>
        <LastModified>2016-10-04T08:35:26.691Z</LastModified>
        <Size>103761</Size>
        <Owner>
            <ID>minio</ID>
            <DisplayName>minio</DisplayName>
        </Owner>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
    <Delimiter>/</Delimiter>
    <EncodingType></EncodingType>
    <IsTruncated>false</IsTruncated>
    <Marker></Marker>
    <MaxKeys>1000</MaxKeys>
    <Name>my-bucket-name</Name>
    <NextMarker>aPrefix/newtKey</NextMarker>
    <Prefix>aPrefix/</Prefix>
</ListBucketResult>
```
## Steps to reproduce the behaviour

GET Bucket (List Objects) Version 1
## Minio version

Version: 2016-09-11T17:42:18Z
Release-Tag: RELEASE.2016-09-11T17-42-18Z
Commit-ID: 85e2d886bcb005d49f3876d6849a2b5a55e03cd3
## AWS SDK For Java version

1.11.39

**Comment by harshavardhana** [comment]
> I face an compatibility while using the last java SDK with your last minio server. The issue is the order in the xml in response, the <Name> stands after the <Contents> thus creating a bug with the SDK.

S3 publishes http://doc.s3.amazonaws.com/2006-03-01/AmazonS3.xsd the returned XML should enforce positional fields.  Thanks for opening the bug @jlebloas
