### ISSUE TITLE
[distributed] DistXL release in Docker 

### ISSUE THREAD

**Issue by sych74** [minio/minio#2850]
Previously I used minio:**edge** tag for XL setup and it worked fine. I tried to install it one more time and get a new error "Server is not initialized". So I tried to use :**latest** tag but it throws the following error 
`time="2016-10-04T14:32:27Z" level=fatal msg="Unable to intialize object layer." cause="dial tcp: missing port in address 172.18.2.113"`
Which Docker image tag can be used for a stable XL setup?

**Comment by harshavardhana** [comment]
Are you talking about distributed XL setup

**Comment by sych74** [comment]
seems like yes
`+ exec app server 192.168.8.254:/export 192.168.8.158:/export 192.168.4.244:/export 192.168.8.255:/export --address :80`

**Comment by harshavardhana** [comment]
> seems like yes
> - exec app server 192.168.8.254:/export 192.168.8.158:/export 192.168.4.244:/export 192.168.8.255:/export --address :80

Checking just ran a 'docker-compose up' seems to be running fine. Are you looking for starting server on a non 9000 port?

**Comment by harshavardhana** [comment]
Just ran 

```
Attaching to minio_minio3_1, minio_minio2_1, minio_minio1_1, minio_minio4_1
minio3_1  | + exec app server --address :80 minio1:/export minio2:/export minio3:/export minio4:/export
minio2_1  | + exec app server --address :80 minio1:/export minio2:/export minio3:/export minio4:/export
minio1_1  | + exec app server --address :80 minio1:/export minio2:/export minio3:/export minio4:/export
minio4_1  | + exec app server --address :80 minio1:/export minio2:/export minio3:/export minio4:/export
```

Seems to be running fine.. with 'minio/minio:edge' -  'minio/minio:latest' doesn't have distributed XL yet.

**Comment by sych74** [comment]
> Are you looking for starting server on a non 9000 port?

yes, I would prefer to run in on 80 by default 

Here is a fresh installation (example of the issue), the cluster has 4 servers and this one works fine 
http://docker91725-minio-env.demo.jelastic.com/ 
but the rest are down 
http://docker91724-minio-env.demo.jelastic.com/
http://docker91727-minio-env.demo.jelastic.com/
http://docker91726-minio-env.demo.jelastic.com/

the last message in the logs is the same  at each instance
`+ exec app server 192.168.7.99:/export 192.168.7.116:/export 192.168.7.132:/export 192.168.7.69:/export --address :80`

**Comment by harshavardhana** [comment]
> yes, I would prefer to run in on 80 by default
> 
> Here is a fresh installation (example of the issue), the cluster has 4 servers and this one works fine 
> http://docker91725-minio-env.demo.jelastic.com/ 
> but the rest are down 
> http://docker91724-minio-env.demo.jelastic.com/
> http://docker91727-minio-env.demo.jelastic.com/
> http://docker91726-minio-env.demo.jelastic.com/
> 
> the last message in the logs is the same at each instance
> - exec app server 192.168.7.99:/export 192.168.7.116:/export 192.168.7.132:/export 192.168.7.69:/export --address :80

can you provide "--address" in the beginning? does that change any behavior?

**Comment by sych74** [comment]
Just a simple restart of non working containers helped and all minio instances are up and running now. So I believe --address is not the root. I did a fresh install and it's working now. Is it possible to make a tag release for docker XL? Then we could push this release to Jelastic users. The latest updates will stay at edge tag and every user will be able to switch if needed.

**Comment by harshavardhana** [comment]
> Just a simple restart of non working containers helped and all minio instances are up and running now. So I believe --address is not the root. I did a fresh install and it's working now. Is it possible to make a tag release for docker XL? Then we could push this release to Jelastic users. The latest updates will stay at edge tag and every user will be able to switch if needed.

We are not ready to release the distributed code just yet we are in process of fixing and testing.  How soon do you need this?

**Comment by sych74** [comment]
Actually the article about Minio XL in Jelastic is almost ready and we published the automation package at some Jelastic providers. When do you think you will be ready to release?

**Comment by harshavardhana** [comment]
> Actually the article about Minio XL in Jelastic is almost ready and we published the automation package at some Jelastic providers. When do you think you will be ready to release?

Right now we are in testing and hardening phase.. We will be releasing in about 2-3weeks. Let me discuss internally and see if we can do something quicker here. Thanks for your patience @sych74

**Comment by harshavardhana** [comment]
> Actually the article about Minio XL in Jelastic is almost ready and we published the automation package at some Jelastic providers. When do you think you will be ready to release?
> Right now we are in testing and hardening phase. We will be releasing in about 2-3weeks. Let me discuss internally and see if we can do something quicker here. Thanks for your patience @sych74

@sych74 We discussed internally and we think that you should wait until we call our distributed code stable and make a release. This is beneficial in terms our ongoing integration effort and also for your end users as well.

**Comment by sych74** [comment]
Hi guys, hope you are fine. I noticed some progress on the release. Is the distributed XL included in the release RELEASE.2016-10-07T01-16-39Z or the latest? 
Thanks

**Comment by krishnasrinivas** [comment]
@sych74  distributed XL is not included in the release RELEASE.2016-10-07T01-16-39Z, available on master though.

**Comment by harshavardhana** [comment]
@sych74 - distributed XL version has been released.. - https://github.com/minio/minio/releases/tag/RELEASE.2016-11-24T02-09-08Z

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/tree/master/docs/distributed for distributed quick start guide.

**Comment by sych74** [comment]
@harshavardhana thank you for letting me know, but I can't find a related docker tag https://hub.docker.com/r/minio/minio/tags/. 

Btw, I passed the update to our marketing department, so they are going to publish a blog post about minio in Jelastic the next week or week after the next.

**Comment by harshavardhana** [comment]
> @harshavardhana thank you for letting me know, but I can't find a related docker tag https://hub.docker.com/r/minio/minio/tags/.

@sych74 "docker pull minio/minio" has distributed support.

**Comment by sych74** [comment]
Ok, got it, it means tag is the :latest. Thanks for clarification.

**Comment by harshavardhana** [comment]
> Ok, got it, it means tag is the :latest. Thanks for clarification.

Yes @sych74 , please do let us know how it goes.

**Comment by sych74** [comment]
Hi guys, can you advice how to configure https? getting the error `Certificates not provided for https`
Thanks

**Comment by harshavardhana** [comment]
@sych74 do you have a SSL terminator or just accessing minio server directly ?

**Comment by sych74** [comment]
yes, you are right, there is a load balancer terminator.

**Comment by harshavardhana** [comment]
Where do you see the above error ? On Minio console logs ?

**Comment by sych74** [comment]
yes, in the console logs

**Comment by harshavardhana** [comment]
It means that the client is trying SSL but it's not configured. Can you try without SSL?

**Comment by sych74** [comment]
w/o ssl it works fine

**Comment by harshavardhana** [comment]
> w/o ssl it works fine

To configure SSL you have to put certs into the "~/.minio/certs/" folder as mentioned here https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio

Otherwise you can configure the load balancer to have SSL and it just talks to minio internally without SSL.  Something like how an nginx proxy would do - https://docs.minio.io/docs/setup-nginx-proxy-with-minio

**Comment by sych74** [comment]
Ok, thanks for the clarification, will check it out.

**Comment by harshavardhana** [comment]
> Ok, thanks for the clarification, will check it out.

Let us know if you see further issues.

**Comment by sych74** [comment]
btw, why the SSL certificates are required for commutation across the nodes if I can upload files from browser w/o them. Does the communication work not over https?

**Comment by harshavardhana** [comment]
> btw, why the SSL certificates are required for commutation across the nodes if I can upload files from browser w/o them. Does the communication work not over https?

It is never required unless you already have certs it will automatically configure itself with SSL transport.  In a distributed setup if one node is SSL then all nodes need to be SSL .  It could be a configuration mistake, let's open a new github issue so we can start a fresh discussion.

Original intention of this github issue is complete - https://docs.minio.io/docs/distributed-minio-quickstart-guide
