### ISSUE TITLE
browser: Implement delete with multi select and confirmation dialog

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2854]
Single object delete works. Need to implement multi-object delete.

**Comment by krishnasrinivas** [comment]
timeline 9-oct

**Comment by GarimaKapoor** [comment]
@krishnasrinivas can we not do this earlier. The release is on 10th. We will need to test it as well.

**Comment by harshavardhana** [comment]
Moved out of milestone.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas do you have a timeline for the fix?

**Comment by krishnasrinivas** [comment]
@rushenn are the UI changes done?

**Comment by rushenn** [comment]
@krishnasrinivas UI is ready and converting the style naming conventions. Will push the changes shortly.

**Comment by harshavardhana** [comment]
Fixed by #3730

**Comment by krishnasrinivas** [comment]
@rushenn can you take care of the UI changes after https://github.com/minio/minio/pull/3810 is merged?

**Comment by rushenn** [comment]
@krishnasrinivas sure

**Comment by harshavardhana** [comment]
This is fixed finally by #3859
