### ISSUE TITLE
[distributed] Validate setup and instructions on windows for distributed minio server. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2860]
Following syntax 'minio server <ip>:/path' might be confusing on windows. We need to finalize on what needs to be done.

**Comment by GarimaKapoor** [comment]
@krisis can you update the timeline of the fix.

**Comment by krisis** [comment]
@GarimaKapoor I am currently testing if Minio multi-disk(XL) setup works on Windows, with the changes that were introduced to support Minio distributed setup. I expect to be finished with my tests by EOD 15th.

**Comment by krisis** [comment]
Tests run so far,
- Basic GET/PUT of objects on a single node XL setup, using `aws` cli and `mc`
  -  https://github.com/minio/minio/issues/2934
  -  https://github.com/minio/minio/issues/2926
- Replace disks with fresh ones (i.e, no data or `format.json`) and repair using `minio control heal`
- Delete bucket directories from one of the disks and use `minio control heal` to repair
- Recursive copying of objects between buckets
  -  https://github.com/minio/minio/issues/2936

**Comment by GarimaKapoor** [comment]
@krisis what is the update in this issue.

**Comment by krisis** [comment]
#2936 turned out to be an issue with `mc` on Windows (ref: https://github.com/minio/mc/issues/1857).
#2934 was fixed by @krishnasrinivas 
#2926 is yet to be fixed.
Further tests (to be done),
- s3verify on single node XL on windows.

Timeline: Oct 22nd

**Comment by krisis** [comment]
- Ran s3verify on single-node XL setup
- Will be running [minio-py based script](https://gist.github.com/krisis/031ef243a1033156a7671d2b76872f01) on a single-node XL setup

**Comment by krisis** [comment]
- Ran minio-py based script on a single-node XL setup successfully.

@harshavardhana I have tested that single-node XL setup with the tests mentioned in the above comments. All tests pass after we fixed the issues that were found in the process. This issue can be closed.
