### ISSUE TITLE
Question: What happens when I manually remove the file from filesystem?

### ISSUE THREAD

**Issue by matylla** [minio/minio#2861]
Since Minio does not offer object lifecycle (yet?) I'm in the need of removing files from storage machines after 24hrs myself. What happens when I remove the file/directory manually `rm -rdf` which has been previously uploaded via Minio API? Will that action break anything in Minio internally? Will that interfere with erasure code algorithm?

Thanks in advance.

**Comment by krishnasrinivas** [comment]
@matylla if you are using the minio-FS  then you can remove the file from the backend. But if you are using XL (erasure backend) then you should not modify the backend directly. You can delete the object using the delete api. you can use `mc rm` to script deletion too. https://github.com/minio/mc

**Comment by matylla** [comment]
Thank you, that answers my question. Does minio-FS provide any fault-tolerance when we loose any hard drive from the storage machine?

**Comment by krishnasrinivas** [comment]
@matylla for minio-FS you can run `mc mirror -w` for continuous replication https://docs.minio.io/docs/minio-client-complete-guide#mirror
