### ISSUE TITLE
[handlers] Allow redirect to custom URL when using MINIO_BROWSER=off instead of plain error

### ISSUE THREAD

**Issue by gowithplanb** [minio/minio#2866]
## Expected behaviour

Ability to redirect visitors to public URL to a custom URL when MINIO_BROWSER=off
## Actual behaviour

A plain-text error:

`<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<Key />
<BucketName />
<Resource>/minio/</Resource>
<RequestId>3L137</RequestId>
<HostId>3L137</HostId>
</Error>
`
## Steps to reproduce the behaviour

Visit the URL Minio is active on, while MINIO_BROWSER=off.
## Minio version

Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
## System information

not relevant

This small feature is useful for Minio users that do not require the Minio browser enabled and have Minio running on a well-known public port (i.e. 80 or 443).

**Comment by harshavardhana** [comment]
> Ability to redirect visitors to public URL to a custom URL when MINIO_BROWSER=off

What is the overall purpose of this @gowithplanb can you explain with some examples? - like how this is beneficial in real world scenarios.

**Comment by gowithplanb** [comment]
We'll have Minio available on well-known public ports which will be (ab)used by scanners and robots. To disencourage any attempts to see beyond the redirect, we'd like to hide the fact that there's an S3 server/Minio behind it, without, for this feature alone, going through installing additional software.

**Comment by harshavardhana** [comment]
This is not needed anymore, we have removed the env variable browser is on by default.  Re-directing to a custom URL should be implemented outside of Minio using a proxy etc.
