### ISSUE TITLE
[notifications] Add kafka support for bucket notifications.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2869]

**Comment by GarimaKapoor** [comment]
@donatello do we have a timeline for this?

**Comment by donatello** [comment]
Timeline 8th-9th.

**Comment by GarimaKapoor** [comment]
@donatello any updates on the revised timelines?

**Comment by donatello** [comment]
@GarimaKapoor The PR to add Kafka support is ready for review now. I think it should be merged within a day or two at most.
