### ISSUE TITLE
tests: Anonymous HTTP request cases for API handlers. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2873]
Need to add cases to validate success and failure of anonymous HTTP requests for API handlers. Currently in Progress.

**Comment by harshavardhana** [comment]
ping @hackintoshrao - is this fixed already?

**Comment by hackintoshrao** [comment]
@harshavardhana : bucket-handlers.go need the same fix. Doing it.

**Comment by hackintoshrao** [comment]
@harshavardhana : This is fixed. Closing the issue.
