### ISSUE TITLE
Error in methods "SetBucketPolicy" and "GetBucketPolicy" of Java client api

### ISSUE THREAD

**Issue by zhanjiejun** [minio/minio#2886]
Hi, I meet some problems, my test codes are below:

```
minioClient.makeBucket("test");
BucketPolicy policy1 = minioClient.getBucketPolicy("test", "");
System.out.println(policy1);  // It's "none".
minioClient.setBucketPolicy("test", "", BucketPolicy.ReadOnly);
BucketPolicy policy2 = minioClient.getBucketPolicy("test", ""); // Where error happens.
System.out.println(policy2);
minioClient.removeBucket("test");
```

When I set a policy to a bucket, error happened if i call the method "getBucketPolicy" to the bucket.
The phenomenon is same if i call the method "setBucketPolicy" to the bucket again.

The exception messages is below: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: **Expected a string but was BEGIN_ARRAY at line 1 column 242 path $.Statement[1].Condition..**

```
HttpResponse response = executeGet(bucketName, null, null, queryParamMap);
BucketAccessPolicy policy = gson.fromJson(response.body().charStream(), BucketAccessPolicy.class);
response.body().close();
```

**Comment by harshavardhana** [comment]
Opened under relevant library closing this https://github.com/minio/minio-java/issues/470
