### ISSUE TITLE
[distributed] XL: Should heal buckets

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2900]
Support healing of buckets.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas can you update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
time: oct-12th

**Comment by GarimaKapoor** [comment]
@krishnasrinivas any updates on the fix?

**Comment by krishnasrinivas** [comment]
@GarimaKapoor i will push this today.

**Comment by krishnasrinivas** [comment]
@harshavardhana https://github.com/minio/minio/pull/2924 creates missing buckets.

But it does not delete buckets which got deleted when the disk was down. Deleting buckets and its contents recursively looked very risky and dangerous. What do you think.

**Comment by harshavardhana** [comment]
Fixed by #2924

**Comment by harshavardhana** [comment]
> But it does not delete buckets which got deleted when the disk was down. Deleting buckets and its contents recursively looked very risky and dangerous. What do you think.

This is fine really.
