### ISSUE TITLE
[lock] Possible race between GetObject and GetObjectInfo.

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2912]
In get object we do:
objectAPI.GetObjectInfo()

// some checks

objectAPI.GetObject()

when `// some checks` are performed, if the object is replaced it will cause race condition.

**Comment by hackintoshrao** [comment]
> when // some checks are performed, if the object is replaced it will cause race condition.

 Can you elaborate on this @krishnasrinivas ?

**Comment by krishnasrinivas** [comment]
> Can you elaborate on this @krishnasrinivas ?

for example:
- etag might be returned of the old object but the contents would be from the new object.
- content-length might be the size of the old object and the contents might be from the new object.

there might be problems with `rangeHeader` check too.

**Comment by hackintoshrao** [comment]
@krishnasrinivas : How to reproduce this ?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas : How to reproduce this ?

it will be difficult to reproduce this because the time between getObjectInfo and getObject will be a very small window during which you have to replace that particular object. You have to be lucky (rather unlucky) to hit it.

**Comment by harshavardhana** [comment]
It was decided to expose Lock(), Unlock() at object layer to hold a lock on entire namespace.  Other than the locks held inside. 

This would introduce locking at object handler layer which would facilitate a way to avoid races like this, while rare provides consistency on we not returning corrupted data in the middle of an operation.
