### ISSUE TITLE
docs: minio docker image under Windows

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2920]
Someone from the community reported that he managed to run Minio docker image under Windows, we need to test by ourselves too.

Starting link: https://docs.docker.com/docker-for-windows/

**Comment by vadmeste** [comment]
Community is invited to test docker image of Minio under Windows. Here is how to run minio docker image:
1. Install Docker Toolbox for Windows (http://www.docker.com/products/docker-toolbox)
2. Open Docker Quickstart Terminal, this will give you the ip address of the docker terminal (not the docker containers themselves)
3. Run 
- `docker pull minio/minio`
- `curl https://raw.githubusercontent.com/minio/minio/master/docker-compose.yml > docker-compose.yml`
- `docker-compose.exe up`

Minio browser will be simply accessible at one of the port 9001-9004, in my case the IP address is 192.168.99.100 and not the one you can see in the minio output.

Two things that we need to check:
- After upload via Minio Browser, the list of files is not automatically refreshed
- mc download policy doesn't always work..

**Comment by harshavardhana** [comment]
> After upload via Minio Browser, the list of files is not automatically refreshed

This is already fixed in the miniobrowser branch we haven't vendorized the new changes yet. 

> mc download policy doesn't always work..

Things changed in this regard recently with distributed setup  can you fill in @donatello about the issues?

**Comment by harshavardhana** [comment]
> Community is invited to test docker image of Minio under Windows. Here is how to run minio docker image:
> 1. Install Docker Toolbox for Windows (http://www.docker.com/products/docker-toolbox)
> 2. Open Docker Quickstart Terminal, this will give you the ip address of the docker terminal (not the docker containers themselves)
> 3. Run
> 
> docker pull minio/minio
> curl https://raw.githubusercontent.com/minio/minio/master/docker-compose.yml > docker-compose.yml
> docker-compose.exe up
> Minio browser will be simply accessible at one of the port 9001-9004, in my case the IP address is 192.168.99.100 and not the one you can see in the minio output.

Can you put this into Markdown and send a PR to https://github.com/minio/cookbook  or 'github.com/minio/minio/docs'

**Comment by zllovesuki** [comment]
<img width="794" alt="minio" src="https://cloud.githubusercontent.com/assets/298453/19408587/ffa4c276-9275-11e6-80d6-28984c351a2e.PNG">

How can we help? :D

**Comment by koolhead17** [comment]
Hello @zllovesuki thanks for your kind offer to contribute to Minio. 😄 

Would you like to add a cookbook for `Running Minio docker image under Windows` following style guidelines https://github.com/minio/cookbook ?

**Comment by harshavardhana** [comment]
Is this already done @koolhead17 @vadmeste ? - we can close this if docs are captured already.

**Comment by koolhead17** [comment]
@harshavardhana I need to test, will close the task this week.

**Comment by vadmeste** [comment]
> @harshavardhana I need to test, will close the task this week.

@koolhead17, I already did a quick documentation, you can see it above and test again

**Comment by koolhead17** [comment]
This works well just we need only one modification. The path for docker-compose.yml is now [https://raw.githubusercontent.com/minio/minio/master/docs/docker/docker-compose.yml](https://raw.githubusercontent.com/minio/minio/master/docs/docker/docker-compose.yml)

we can close this.

**Comment by harshavardhana** [comment]
> This works well just we need only one modification. The path for docker-compose.yml is now https://raw.githubusercontent.com/minio/minio/master/docs/docker/docker-compose.yml
> 
> we can close this.

Can you submit the PR for review? @koolhead17

**Comment by koolhead17** [comment]
sure @harshavardhana I documented it here https://github.com/koolhead17/test/blob/master/docs/minio-docker-windows.md, will send it minio/docker/docs

**Comment by harshavardhana** [comment]
Closing as fixed by #3507
