### ISSUE TITLE
[distributed] Minio server prints "Failed to delete lock info entry" during copy of a large object 

### ISSUE THREAD

**Issue by krisis** [minio/minio#2926]
## Expected behaviour

Copy of a large object leads to `Failed to delete lock info entry` message on console.
## Actual behaviour

No error message should be seen.
## Steps to reproduce the behaviour
- Make a bucket
- Copy a file > 64MB (using `mc`) into the bucket
- We can see `Failed to delete lock info entry` on the console
## Minio version

`5e86352`
## System information

MS Windows

**Comment by vadmeste** [comment]
This is also reproducible under Linux + FS backend

**Comment by GarimaKapoor** [comment]
@krisis please update the status of this issue?

**Comment by krisis** [comment]
I haven't yet determined the root cause of the issue. I will resume work on this issue on Oct 22. @vadmeste tested if this was reproducible on Linux yesterday, with some of the fixes that were merged and couldn't reproduce it. I will verify if it is true with Windows and update.

**Comment by krisis** [comment]
This issue is reproducible with objects of size < 64MB as well.

**Comment by harshavardhana** [comment]
> This issue is reproducible with objects of size < 64MB as well 

Is there a pattern to it?

**Comment by harshavardhana** [comment]
Was able to reproduce this problem with current master

```
ERRO[0034] Failed to set the lock state to running.      cause=No entry in lock info for <Operation ID> XQTK9QVZ467T4P9X, <volume> .minio.sys, <path> multipart/testbucket/test/b816f0aa-7c24-465e-b124-8721a52820ee. location=[namespace-lock.go:149:(*nsLockMap).lock()]
ERRO[0034] Failed to delete lock info entry.             cause=No entry in lock info for <Operation ID> XQTK9QVZ467T4P9X, <volume> .minio.sys, <path> multipart/testbucket/test/b816f0aa-7c24-465e-b124-8721a52820ee. location=[namespace-lock.go:177:(*nsLockMap).unlock()]
```

**Comment by vadmeste** [comment]
> Was able to reproduce this problem with current master

Were you able to see this under Linux @harshavardhana  ?

**Comment by harshavardhana** [comment]
> Were you able to see this under Linux @harshavardhana ?

Yes it is Ubuntu 16.04

**Comment by vadmeste** [comment]
I found this bug only in FS. Something related to the fact that appendParts() is running in a goroutine but failed to reproduce with XL, @harshavardhana do you remember if you saw this in FS too ?

**Comment by harshavardhana** [comment]
> I found this bug only in FS. Something related to the fact that appendParts() is running in a goroutine but failed to reproduce with XL, @harshavardhana do you remember if you saw this in FS too ?

yes it is FS @vadmeste

**Comment by harshavardhana** [comment]
Reassigned to @balamurugana

**Comment by harshavardhana** [comment]
Closing the bug this bug is not reproducible anymore // cc @balamurugana

**Comment by balamurugana** [comment]
Unable to reproduce in HEAD 5741a53d4650249ced86af190141f0a8417d403e.
Reopen if appears again.
