### ISSUE TITLE
Connecting to minio s3 via CloudBerry S3 Explorer fails ?

### ISSUE THREAD

**Issue by StefH** [minio/minio#2928]
## Expected behaviour

Connection ok
## Actual behaviour

Error : **The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.**
## Steps to reproduce the behaviour

Run minio on windows machine.
## Minio version

Version: 2016-10-14T04:00:39Z
Release-Tag: RELEASE.2016-10-14T04-00-39Z
Commit-ID: 8c59a4166865e65192e91986e8bee329851bbf7c
## System information

Windows 2008 R2

**Comment by harshavardhana** [comment]
@StefH we don't support Signature V2 just yet in our release. Currently signature v2 is available only in our master branch. 

So this is expected.

**Comment by krishnasrinivas** [comment]
@StefH you can compile minio from source using the command:
`$ go get -u github.com/minio/minio`

(note: you can install Go from here https://golang.org/)

if you test it, can you let us know how it goes?

**Comment by koolhead17** [comment]
hello @StefH for time being can you try https://blog.erudinsky.com/2016/08/30/minimal-object-storage-s3-compatible, it should work in current setup of yours. @harshavardhana we can close this 😄

**Comment by StefH** [comment]
For this moment, I just will use this solution : https://github.com/jubos/fake-s3

**Comment by koolhead17** [comment]
thanks @StefH

**Comment by harshavardhana** [comment]
> For this moment, I just will use this solution : https://github.com/jubos/fake-s3

Thanks @StefH we will be making a distributed release in couple of weeks which will have Signature V2 capabilities. Closing this issue for now.
