### ISSUE TITLE
Copying a multipart-uploaded object to another bucket fails

### ISSUE THREAD

**Issue by krisis** [minio/minio#2934]
## Expected behaviour

`mc cp myminio/test/go1.6.2.linux-amd64.tar.gz myminio/test1`
should pass
## Actual behaviour

The above copy command fails with, 
`mc: <ERROR> Failed to copy ‘http://192.168.1.104:9000/tst/go1.6.2.linux-amd64.tar.gz’. The Content-Md5 you specified did not match what we received.
`
## Steps to reproduce the behaviour

`mc cp myminio/test/go1.6.2.linux-amd64.tar.gz myminio/test1`
## Minio version

`17eeec6`

**Comment by krishnasrinivas** [comment]
I am working on the fix which preserves the ETag from the source.

**Comment by krishnasrinivas** [comment]
Observation on aws-S3 is - the ETag from the source is not preserved. So if the source ETag is a7d414b9133d6483d9a1c4e04e856e3b-2 but after copy object the ETag is f1c9645dbc14efddc7d8a322685f26eb which is the md5sum. So the fix will be simple.
