### ISSUE TITLE
miniobrowser: upload a file when no a bucket created yet shows an unclear error

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2946]
I think the browser should test this situation by itself and shows the appropriate error message.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the timeline of the fix.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas any updates on this issue?

**Comment by harshavardhana** [comment]
> @krishnasrinivas any updates on this issue?

This is fixed https://github.com/minio/miniobrowser/pull/223
