### ISSUE TITLE
[distributed] mc commands hang. 

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2963]
After the sequence of steps in https://github.com/minio/minio/issues/2961

I did:
`mc policy both minio2/kris`

This hung.
Ctrl-C and
`mc ls minio2/kris`
also hung.

Probably locking issue.

**Comment by harshavardhana** [comment]
Can this be reproduced again? @krishnasrinivas

**Comment by GarimaKapoor** [comment]
@donatello were you able to reproduce this issue?

**Comment by donatello** [comment]
No, not been trying. But I am working on this one https://github.com/minio/minio/issues/2979 - it is probably related to this one. However, there have been some other fixes in the meanwhile, and it would be good if @krishnasrinivas can have a whack at reproducing it (he may already have the necessary code) - so we can be sure this one is not already fixed.

**Comment by GarimaKapoor** [comment]
cc @krishnasrinivas

**Comment by krishnasrinivas** [comment]
I will try to reproduce this issue and fix it if seen again.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas were you able to reproduce the issue.

**Comment by harshavardhana** [comment]
> @krishnasrinivas were you able to reproduce the issue.

Server have been updated to latest we should validate this again.

**Comment by krishnasrinivas** [comment]
This is not reproducible anymore, maybe it was side effect of something else.
