### ISSUE TITLE
[distributed] make bucket command hangs.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2966]
## Expected behaviour

`mc mb` should create a bucket.
## Actual behaviour

It gives no output & for a normal user the behaviour appears as if process is stuck. 
## Steps to reproduce the behaviour

`mc mb myminio/mybucket`  The screen will be stuck, CTRL+C and do `mc ls myminio`
bucket will be created.

**Comment by harshavardhana** [comment]
Can you try again

```
root@minio-client1:~# mc mb minio2/obiwan
mc: <ERROR> Unable to make bucket ‘minio2/obiwan’. Your previous request to create the named bucket succeeded and you already own it.
root@minio-client1:~# 
```

**Comment by koolhead17** [comment]
yup, closing it works now.
