### ISSUE TITLE
[distributed] listing objects on a non-existent bucket hangs

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2967]
## Expected behaviour

`mc ls` should error out saying bucket does not exist.
## Actual behaviour

It stays on the terminal without any output
## Steps to reproduce the behaviour

`mc ls myminio/fubarwesgs`
- bucket `fubarwesgs` does not exist but terminal stays without giving any output.

**Comment by harshavardhana** [comment]
Can you try again seems to be working fine?

**Comment by koolhead17** [comment]
Yup, closing it. works now.
