### ISSUE TITLE
[distributed] remove bucket command hangs.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#2968]
## Expected behaviour

`mc rm myminio/mybucket` should remove empty bucket
## Actual behaviour

The terminal stays without giving any output after CTRL+C running `mc ls myminio` concludes bucket is deleted.
## Steps to reproduce the behaviour

`$ mc rm myminio/atul1` It will stay on terminal, after CTRL+C running `mc ls myminio` concludes bucket is deleted.

**Comment by harshavardhana** [comment]
This seems to be working fine now. 

```
# mc rm myminio/atul1
mc: <ERROR> Unable to remove ‘myminio/atul1’. The specified bucket does not exist
```

Can you validate again?

**Comment by koolhead17** [comment]
yup, closing it works now.
