### ISSUE TITLE
[distributed]  Taking down first server while the other servers are in startup sequence can hang

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2973]
```
minio2: [10/16] minio5:/mnt/export2/minio - 218 GiB online
minio2: [11/16] minio6:/mnt/export1/minio - 218 GiB online
minio2: [12/16] minio6:/mnt/export2/minio - 218 GiB online
minio2: [13/16] minio7:/mnt/export1/minio - 218 GiB online
minio2: [14/16] minio7:/mnt/export2/minio - 218 GiB online
minio2: [15/16] minio8:/mnt/export1/minio - 218 GiB online
minio2: [16/16] minio8:/mnt/export2/minio - 218 GiB online
minio5: Initializing data volume.
minio5: [01/16] minio1:/mnt/export1/minio - 218 GiB online
minio5: [02/16] minio1:/mnt/export2/minio - 218 GiB online
minio5: [03/16] minio2:/mnt/export1/minio - 218 GiB online
minio5: [04/16] minio2:/mnt/export2/minio - 218 GiB online
minio5: [05/16] minio3:/mnt/export1/minio - 0 B offline
minio5: [06/16] minio3:/mnt/export2/minio - 0 B offline
minio5: [07/16] minio4:/mnt/export1/minio - 218 GiB online
minio5: [08/16] minio4:/mnt/export2/minio - 218 GiB online
minio5: [09/16] minio5:/mnt/export1/minio - 218 GiB online
minio5: [10/16] minio5:/mnt/export2/minio - 218 GiB online
minio5: [11/16] minio6:/mnt/export1/minio - 218 GiB online
minio5: [12/16] minio6:/mnt/export2/minio - 218 GiB online
minio5: [13/16] minio7:/mnt/export1/minio - 218 GiB online
minio5: [14/16] minio7:/mnt/export2/minio - 218 GiB online
minio5: [15/16] minio8:/mnt/export1/minio - 218 GiB online
minio5: [16/16] minio8:/mnt/export2/minio - 218 GiB online
```

Servers should proceed forward with disconnected server and initialize with in quorum.

**Comment by harshavardhana** [comment]
This is not a hang but a race in cleanupDir() function which would kill the servers..

**Comment by harshavardhana** [comment]
// cc - assigned to @vadmeste

**Comment by harshavardhana** [comment]
Ping @vadmeste - have you validated this?

**Comment by vadmeste** [comment]
@harshavardhana, I can easily have this behavior when disks are unformatted but not when disks are already formatted.. but this is weird since the first node calls Storage.TryInitHandler on all other nodes, am I missing something ?

**Comment by harshavardhana** [comment]
It must be that the notification is lost and it happens. So any error is never retried.

**Comment by vadmeste** [comment]
> It must be that the notification is lost and it happens. So any error is never retried.

Currently, the first node orchestrates the init phase, if the first node is killed in the very early stage, the system won't be initialized.

**Comment by harshavardhana** [comment]
Its a correct behavior if first node is not available. But init should still proceed one of the other nodes other than the first disk are down.

**Comment by vadmeste** [comment]
> Its a correct behavior if first node is not available. But init should still proceed one of the other nodes other than the first disk are down.

So this issue doesn't make sense anymore?

**Comment by harshavardhana** [comment]
Yes but the issue was that during startup sequence first server goes down the other peers dont reach inconsistent state or print odd messages. But if there was a window where they all proceed and then first server goes down in middle of format.json being written. We need to validate these scenarios.

**Comment by harshavardhana** [comment]
> Yes but the issue was that during startup sequence first server goes down the other peers dont reach inconsistent state or print odd messages. But if there was a window where they all proceed and then first server goes down in middle of format.json being written. We need to validate these scenarios.

This is not reproducible anymore. Closing.
