### ISSUE TITLE
[distributed]: Enable quick heal for  'policy.json', 'notification.xml' , 'listeners.json' 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2980]
Basically all bucket metadata files as well.

**Comment by krishnasrinivas** [comment]
maybe we can do this every time after a server comes back up, since it's just 3 files it will be quick.

**Comment by harshavardhana** [comment]
> maybe we can do this every time after a server comes back up, since it's just 3 files it will be quick.

We decided to do both do it during startup and also allow it to be done during 'minio control heal'

**Comment by harshavardhana** [comment]
Healing through command is deferred post distributed release, we will still be doing startup healing.

**Comment by GarimaKapoor** [comment]
@harshavardhana what is the timeline for the fix.

**Comment by harshavardhana** [comment]
> @harshavardhana what is the timeline for the fix.

Should be merged today.
