### ISSUE TITLE
[distributed] minio-fs on windows serves from a different path

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2987]
Gave @delimix a custom windows build.
He tried `minio.exe server d:\minioroot` it did not serve from d:\minioroot.
Must be a recent bug.

**Comment by krishnasrinivas** [comment]
Tested on my windows machine, it worked fine. Doing a remote desktop session with @delimex

**Comment by krishnasrinivas** [comment]
`minio server d:\minioroot` behaves as `minio server c:\minioroot`

Also the performance on SATA drive was very poor but it was fine on SSD.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the status of this issue?

**Comment by krishnasrinivas** [comment]
There were two issues, one related to export path and other performace on windows.

Performance on windows needs debugging. Will fix it by 22nd.

**Comment by krishnasrinivas** [comment]
performance issue on windows was caused by open/close in every AppendFile.
Plus diskFree() check also had some impact.

as proof https://github.com/krishnasrinivas/minio/commit/b72e77b1bb2bd929c93912adc76c911010ef8ca4 fixes the performance problem. But implementing fdcache for windows sake will be bad for our code flow.

**Comment by GarimaKapoor** [comment]
@harshavardhana does it make sense to move it out of distributed then?

**Comment by harshavardhana** [comment]
> @harshavardhana does it make sense to move it out of distributed then?

Yes @GarimaKapoor moving it out.

**Comment by harshavardhana** [comment]
This issue is already fixed in master.
