### ISSUE TITLE
erasure/distributed: Sync in-memory bucket metadata automatically

### ISSUE THREAD

**Issue by donatello** [minio/minio#2991]
In some cases, in-memory bucket metadata such as policy configuration, notifications configuration or listener configuration can go stale due to dropped/missed messages. We need a simple framework that automatically heals/fixes this.

**Comment by deekoder** [comment]
needs to be discussed.

**Comment by donatello** [comment]
On discussion with @abperiasamy it was decided to write a periodic checker that lists all buckets and syncs the bucket configurations by reading from object layer.

**Comment by harshavardhana** [comment]
> On discussion with @abperiasamy it was decided to write a periodic checker that lists all buckets and syncs the bucket configurations by reading from object layer.

Are you still doing this @donatello ?

**Comment by harshavardhana** [comment]
Notification subsystem and policy subsystem has been fully refactored, this situation is handled more cleanly now.
