### ISSUE TITLE
access key invalid - need to print details

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3010]
`time="2016-10-20T11:57:18Z" level=fatal msg="Invalid access key." cause="Invalid arguments specified"`

should say why access key is invalid.

**Comment by tspoke** [comment]
Same for secret key : 

```
time="2016-10-20T12:57:33Z" level=fatal msg="Invalid secret key." cause="Invalid arguments specified"
```

**Comment by vadmeste** [comment]
Generally speaking, what about printing links to some specific sections in a documentation page which explains the possible reasons of the error ?

**Comment by harshavardhana** [comment]
> Generally speaking, what about printing links to some specific sections in a documentation page which explains the possible reasons of the error ?

There is no such documentation but we can talk about the expected length of small and high which we do inside the error itself. 

Currently the message doesn't indicate why it is an "Invalid access key"

**Comment by harshavardhana** [comment]
For example 

```
minio server
....
 ACCESS:
     MINIO_ACCESS_KEY: Access key string of 5 to 20 characters in length.
     MINIO_SECRET_KEY: Secret key string of 8 to 40 characters in length.
```

**Comment by vadmeste** [comment]
I was able to run minio after setting access/secret keys to "m", "m" directly in config.json

Is this normal?

**Comment by harshavardhana** [comment]
> I was able to run minio after setting access/secret keys to "m", "m" directly in config.json
> 
> Is this normal?

I don't think so @vadmeste - it is a bug.
