### ISSUE TITLE
[distributed] Concurrent multipart PUTs sometimes make an object unavailable for PUT

### ISSUE THREAD

**Issue by donatello** [minio/minio#3014]
## Expected behaviour

Concurrent PUTs should always be possible.
## Actual behaviour

Get an error like:

```
ResponseError: code: NoSuchKey, message: The specified key does not exist., bucket_name: None, object_name: None, request_id: X6UG12PWOTCNK6AS, host_id: 3L137, region:
```

This happens even no other concurrent uploads are happening.
## Steps to reproduce the behaviour

The script at https://gist.github.com/donatello/037377ad0a204b3309e6334483e0d3c3 creates 65MB files using multipart uploads.
1. Run it in parallel:

```
$ # Run 16 instances of the script in parallel, and in total run the script 100 times. 
$ # The argument 10 says to create/upload 10 files.
$ seq 100 | xargs -I{} -n 1 -P 16 -t python small-obj-load-test.py 10
...
...
^C
$ # Hit Ctrl+C about 5 minutes later. Make sure all instances of the script have exited.
$ # Run the script sequentially now. Some files will fail to upload:
$ for i in $(seq 10) ; do python small-obj-load-test.py 10 ; done
DEBUG: donatello-7 my-boring-object-0
minio6:9000:donatello-7/my-boring-object-0: upload success - took 0:00:03.443936
DEBUG: donatello-7 my-boring-object-1
minio6:9000:donatello-7/my-boring-object-1: upload failure - got error: ResponseError: code: NoSuchUpload, message: The specified multipart upload does not
 exist. The upload ID may be invalid, or the upload may have been aborted or completed., bucket_name: None, object_name: None, request_id: 0XM3W44QXOH5L0JX
, host_id: 3L137, region: 
DEBUG: donatello-7 my-boring-object-2
minio7:9000:donatello-7/my-boring-object-2: upload failure - got error: ResponseError: code: NoSuchUpload, message: The specified multipart upload does not
 exist. The upload ID may be invalid, or the upload may have been aborted or completed., bucket_name: None, object_name: None, request_id: 2KFD35HTPW26VW5M
, host_id: 3L137, region: 
DEBUG: donatello-7 my-boring-object-3
minio1:9000:donatello-7/my-boring-object-3: upload success - took 0:00:03.409935
DEBUG: donatello-7 my-boring-object-4
minio7:9000:donatello-7/my-boring-object-4: upload failure - got error: ResponseError: code: NoSuchKey, message: The specified key does not exist., bucket$name: None, object_name: None, request_id: UA2DNOKY4RZHDZNJ, host_id: 3L137, region: 
DEBUG: donatello-7 my-boring-object-5
minio8:9000:donatello-7/my-boring-object-5: upload success - took 0:00:03.498258
DEBUG: donatello-7 my-boring-object-6
minio2:9000:donatello-7/my-boring-object-6: upload success - took 0:00:03.413123
DEBUG: donatello-7 my-boring-object-7
minio5:9000:donatello-7/my-boring-object-7: upload success - took 0:00:03.494773
DEBUG: donatello-7 my-boring-object-8
minio7:9000:donatello-7/my-boring-object-8: upload success - took 0:00:03.493213
DEBUG: donatello-7 my-boring-object-9
minio2:9000:donatello-7/my-boring-object-9: upload failure - got error: ResponseError: code: NoSuchUpload, message: The specified multipart upload does no$ exist. The upload ID may be invalid, or the upload may have been aborted or completed., bucket_name: None, object_name: None, request_id: DVVHI3NZ4NSZCT0$, host_id: 3L137, region: 
DEBUG: donatello-7 my-boring-object-0
minio6:9000:donatello-7/my-boring-object-0: upload success - took 0:00:03.416122
DEBUG: donatello-7 my-boring-object-1
minio4:9000:donatello-7/my-boring-object-1: upload failure - got error: ResponseError: code: NoSuchUpload, message: The specified multipart upload does no$ exist. The upload ID may be invalid, or the upload may have been aborted or completed., bucket_name: None, object_name: None, request_id: BL1N1EBNLY0JXXR$, host_id: 3L137, region: 
...
```
## Minio version
- Latest version of master (as of now) running on packet.
## System information

Linux.

**Comment by donatello** [comment]
This happens on new buckets too, so it seems unlikely that it is related to healing - I think https://github.com/minio/minio/issues/3006 may be closed for now @harshavardhana ?

**Comment by donatello** [comment]
Potential cause 1:

(thanks to @balamurugana)

Consider `newMultipartUpload()` function:
https://github.com/minio/minio/blob/5782ec3ada1c98b20402d271b66baeb10fa0f243/cmd/xl-v1-multipart.go#L265-L306 (on latest master at time of writing).

`uploads.json` is written on line 291, but `writeSameXLMetadata` and `renameObject` on lines 297 and 300  can fail, leaving a stale `uploads.json` - i.e. json file with entry, but no uploads directory.

The fix seems to be to remove the entry from uploads.json on failure, but it appears to be complicated to do this.

On discussion with @balamurugana - it appears that we may not actually need uploads.json at all if we just send the update time for the uploadid instead of the initiated time. This needs some discussion.

**Comment by harshavardhana** [comment]
> On discussion with @balamurugana - it appears that we may not actually need uploads.json at all if we just send the update time for the uploadid instead of the initiated time.

We cannot do that this will break S3 compatibility.  This fix of `uploads.json` to be removed incase of failure should happen and it shouldn't be that complicated to fix as well.

**Comment by krishnasrinivas** [comment]
> > On discussion with @balamurugana - it appears that we may not actually need uploads.json at all if we just send the update time for the uploadid instead of the initiated time.
> 
> We cannot do that this will break S3 compatibility. This fix of uploads.json to be removed incase of failure should happen and it shouldn't be that complicated to fix as well.

Also we use uploads.json to detect if it's the leaf directory

You can move the following lines to line 305, i.e do writeUploadJSON() only after writeSameXLMetadata and renameObject

```
    // Create 'uploads.json'
    if err = xl.writeUploadJSON(bucket, object, uploadID, initiated); err != nil {
        return "", err
    }
```
