### ISSUE TITLE
[distributed] Enable SSL based tests as well for all handler/controller/rpc/api communication

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3020]
We should use a self-signed certificate and validate it.

**Comment by harshavardhana** [comment]
// cc @krisis

**Comment by krisis** [comment]
@harshavardhana I shall start with adding TLS based tests in `server_test.go`. The following is how I plan to do it.
-  Have a self-signed ceritficate, `.pem` and `.key` files, under `test-data/`.
-  Add a test utility function that starts a http server with TLS configured.
-  Add a subset of tests from `server_test.go` to execute on the http server with TLS configured.

Is this along the lines of what is expected in this issue?

**Comment by harshavardhana** [comment]
Yes :+1: looks good.
