### ISSUE TITLE
dist: systemd script for running distributed Minio.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3026]
- The current systemd script is configured to run Minio distributed. Need modifications to get Minio distributed running/stop/restart using systemd script.
- Also need a guide on setting to systemd along with the environment configurations  to run Minio distributed.

**Comment by gebi** [comment]
Hi,

I'm not sure i understand the part about "distributed" minio correct, but i needed a systemd service unit for minio. Feel free to use it. You may remove the dependency to remote-fs.target which is a speciality of our setup.

As for the others, `MINIO_SECURE_CONSOLE=0` does not work with current minio stable, i will open an issue about it.

```
[Unit]
Description=minio s3 server
Documentation=https://minio.io
Requires=remote-fs.target
After=remote-fs.target

[Service]
User=minio
Group=minio
WorkingDirectory=/srv/minio
Environment=MINIO_SECURE_CONSOLE=0
ExecStart=/opt/minio/minio server --address ":9001" /srv/minio/data

PrivateTmp=true
PrivateDevices=true
ProtectSystem=full
ProtectHome=true
CapabilityBoundingSet=~CAP_SYS_ADMIN CAP_DAC_OVERRIDE CAP_SYS_PTRACE
NoNewPrivileges=true

Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```

**Comment by gebi** [comment]
Never mind about MINIO_SECURE_CONSOLE, it's just not included in the current stable and hidden inside a big code re-organization.

**Comment by harshavardhana** [comment]
> As for the others, MINIO_SECURE_CONSOLE=0 does not work with current minio stable, i will open an issue about it.

This will be available the distributed release @gebi
