### ISSUE TITLE
[cli] Arguments parsing failure when sent as one string.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3028]
- This was witnessed while getting systemd to run Minio distributed.
- When the arguments to run `minio` binary is sent as one string (all flags + drives/nodes), the cli fails to parse the arguments, leads to `Invalid arguments error`.

**Comment by krishnasrinivas** [comment]
systemd should have a way to provide multiple arguments right?

**Comment by harshavardhana** [comment]
> systemd should have a way to provide multiple arguments right?

Its not systemd issue its our CLI flag parsing problem.

**Comment by harshavardhana** [comment]
ping @hackintoshrao is this an issue still - you said it works fine now?

**Comment by hackintoshrao** [comment]
This works good now. The issue was due to a typo in the systemd script.
