### ISSUE TITLE
[distributed] Minio not able to initialize with these disks

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3044]
## Expected behaviour

Minio distributed initialized and ready for use
## Actual behaviour

Minio distributed not able to start
## Steps to reproduce the behaviour

Not sure, but you can find the disks attached to this issue
[export_16disks_init_bug.tar.gz](https://github.com/minio/minio/files/545846/export_16disks_init_bug.tar.gz)
## Minio version

4b5b363c6c6da32e7703390e25556f48e3f41690
## System information

Docker

**Comment by vadmeste** [comment]
[export_16disks_init_bug_second.tar.gz](https://github.com/minio/minio/files/548005/export_16disks_init_bug_second.tar.gz)

Another case, not sure if it is the same bug or not.

**Comment by harshavardhana** [comment]
ping @vadmeste is this reproducible with latest master?

**Comment by vadmeste** [comment]
Well, the latest master doesn't work with both export directories attached to this issue:

All instances quit with the first export directories:
`minio3_1   | time="2016-10-28T08:54:55Z" level=fatal msg="Unable to load all bucket policies." cause="Storage resources are insufficient for the read operation." location="newObjectLayer [routers.go:70]` 

Instances work with the second export directories, however all of them show this strange status message:
`minio7_1   | Status:         1 Online, 15 Offline.`
and mc cp doesn't really work.

Shall I restart from scratch? It could be some inconsistent information in the backend due to a previous bug.

**Comment by harshavardhana** [comment]
> Shall I restart from scratch? It could be some inconsistent information in the backend due to a previous bug.

Yes please try from scratch @vadmeste - did you do anything to the cluster set to reach this stage?

**Comment by harshavardhana** [comment]
Any particular operation that you performed?

**Comment by harshavardhana** [comment]
> Any particular operation that you performed?

Were you able to reproduce this @vadmeste ?

**Comment by vadmeste** [comment]
This is hard to reproduce or fixed, I think it is safe to close it for now.

**Comment by harshavardhana** [comment]
> This is hard to reproduce or fixed, I think it is safe to close it for now.

Closing..will re-open as new bug if seen again. Thanks @vadmeste
