### ISSUE TITLE
[distributed] Fails to start server when `listener.json` is incompatible with previous configuration

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3052]
Starting server fails if listener.json is incompatible with the previously saved configuration. 

```
$ cat ~/test/.minio.sys/buckets/testbucket/listener.json 
[{"TopicConfiguration":{"Event":["s3:ObjectCreated:*","s3:ObjectRemoved:*"],"Filter":{"S3Key":{"FilterRules":[{"Name":"prefix","Value":""},{"Name":"suffix","Value":""}]}},"Id":"sns-1476947682612223331","Topic":"arn:minio:sqs:us-east-1:1476947682612223331:listen-:9000"},"TargetServer":":9000"}]
```

```
$ minio server --address "10.0.0.13:9000" ~/test
ERRO[0000] Unable to initialize listener target logger.  cause=Peer :9000 was not initialized - bug! location=initEventNotifier [event-notifier.go:664]
FATA[0000] Unable to initialize event notification.      cause=Error initializing listner target logger - Peer :9000 was not initialized - bug! location=newObjectLayer [routers.go:74]
```
## Expected Behavior

Server should continue to function properly. This bug is related to https://github.com/minio/minio/issues/3022
## Current Behavior

Server cannot start and doesn't describe the issue further either. 
## Possible Solution

Fixing this https://github.com/minio/minio/issues/3022 would fix this. 
## Your Environment

- Version used: latest master
- Server type and version: regular backend filesystem.

**Comment by GarimaKapoor** [comment]
@donatello please update the timeline for the fix.

**Comment by donatello** [comment]
@GarimaKapoor I am going to take up this one (and #3022 which is related) after #3073 (which I am going to take up today) and #3044 (which is a newish bug). So it looks like it may take up to 28th Oct.
