### ISSUE TITLE
Persistent download URLs

### ISSUE THREAD

**Issue by Shark** [minio/minio#3056]
It would be really helpful if the URLs for the minio binaries stayed the same after a new release is published. We download Minio as part of our image build scripts. Currently those scripts break whenever a new version is released. This also affects mc.

For example: https://dl.minio.io/server/minio/release/linux-amd64/minio.RELEASE.2016-10-22T00-50-41Z is the latest version, but the file is moved to the archives/ subdirectory after a version bump.

**Comment by harshavardhana** [comment]
@Shark persistent downloads link is directly https://dl.minio.io/server/minio/release/linux-amd64/minio not https://dl.minio.io/server/minio/release/linux-amd64/minio.RELEASE.2016-10-22T00-50-41Z  

We are in the process of making continuous releases and each release is backward compatible. Unless there is a good reason i don't see a reason why your image builds should be using a specific .RELEASE binary. 

If there is a important requirement it is better to mirror them if you wish to stick to a particular version. This is how http://deis.io/ achieves. https://github.com/deis/minio

**Comment by Shark** [comment]
@harshavardhana sticking to the latest version should be ok for most people, but we're versioning the images ourselves and want repeatable builds. If the latest build is available as /minio, then the /minio.RELEASE.2016-10-22T00-50-41Z could be put into /archives/minio.RELEASE.2016-10-22T00-50-41Z right away, or am I wrong? This would allow us to stick to a specific version while others could always get the latest one.

**Comment by harshavardhana** [comment]
@Shark can you give more details on how the images are built can help you point to a cleaner solution here?  for example you can see how - https://github.com/Homebrew/homebrew-core/blob/06e9168deab3809363a53ada1617f61e137e3a18/Formula/minio.rb is achieved in the same context.  A pld-linux version for RPM spec is here https://github.com/pld-linux/minio/blob/master/minio.spec

**Comment by Shark** [comment]
@harshavardhana ok, as far as I understand it, Homebrew builds Minio from source and then host the resulting bottle on their own. And I think that's okay, because they have to maintain a hosting service for the binaries anyway.

We're using [Packer](https://www.packer.io/) to build our images. During the build we download the Minio binary. Our images use a semver-like versioning scheme. For example, let's say we built v0.1.0 today. 6 months from now, we already have v0.2.0 with a newer Minio version. We then find a bug in our image and release v0.2.1, but we also need to update v0.1.0. We do not want to use an updated Minio server since we don't want to test it against the downstream code (are all the projects using the Minio server as their storage backend still compatible?).

Besides, I don't think that the approach I'm proposing is unusual (e.g. https://releases.hashicorp.com/consul). And it it should be an easy fix. :)

**Comment by harshavardhana** [comment]
> then the /minio.RELEASE.2016-10-22T00-50-41Z could be put into /archives/minio.RELEASE.2016-10-22T00-50-41Z right away, or am I wrong?

This is a better suggestion. Just did this and every release will have a similar style. Please confirm if it working for you.

**Comment by Shark** [comment]
@harshavardhana thanks, that's perfect. Would love to see the same for `mc`. Keep up the great work!

**Comment by harshavardhana** [comment]
> @harshavardhana thanks, that's perfect. Would love to see the same for mc. Keep up the great work!

@Shark even mc is going to do the same.
