### ISSUE TITLE
[tests] Need better test coverage for `PostPolicyBucketHandler` .

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3059]
Need better test coverage for `PostPolicyBucketHandler` from object-handlers.

**Comment by krishnasrinivas** [comment]
Added few testcases in https://github.com/minio/minio/pull/3104.

More will be added after fixing https://github.com/minio/minio/issues/3103

**Comment by krishnasrinivas** [comment]
timeline 12-11

**Comment by vadmeste** [comment]
I am taking this
