### ISSUE TITLE
[tests] Need better test coverage for `updateUploadsJSON`.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3060]
Need better test coverage for `updateUploadsJSON` from `xl-v1-multipart-common.go`.

**Comment by GarimaKapoor** [comment]
@donatello please update the timeline for the fix.

**Comment by donatello** [comment]
@GarimaKapoor After #3052, I'll take up the 3 unit test issues. So perhaps 1-2 Nov for these 3 (i.e. this one and #3061 and #3067) issues.

**Comment by donatello** [comment]
This can be closed - the function has moved to `object-multipart-common.go` and is covered fully except for some rare error cases. https://codecov.io/gh/minio/minio/src/master/cmd/object-multipart-common.go#L117

**Comment by harshavardhana** [comment]
> This can be closed - the function has moved to object-multipart-common.go and is covered fully except for some rare error cases. https://codecov.io/gh/minio/minio/src/master/cmd/object-multipart-common.go#L117

Closing.

**Comment by donatello** [comment]
> This can be closed - the function has moved to object-multipart-common.go and is covered fully except for some rare error cases. https://codecov.io/gh/minio/minio/src/master/cmd/object-multipart-common.go#L117

This was a wrong message. I am working on a test to improve its coverage.
