### ISSUE TITLE
[tests] Need better test coverage for `writeUploadJSON`.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3061]
Need better test coverage for `writeUploadJSON` from `xl-v1-multipart-common.go`.

**Comment by GarimaKapoor** [comment]
@donatello please update the timeline for the fix.

**Comment by donatello** [comment]
This function is covered (ignoring rare error cases). https://codecov.io/gh/minio/minio/src/master/cmd/object-multipart-common.go#L107

Can be closed.

**Comment by harshavardhana** [comment]
> This function is covered (ignoring rare error cases). https://codecov.io/gh/minio/minio/src/master/cmd/object-multipart-common.go#L107
> 
> Can be closed.

Closing.. 80% covered.
