### ISSUE TITLE
[tests] Need better test coverage for StorageServer RPC handlers.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3064]
Need better coverage for RPC handlers in `storage-rpc-server.go`.

**Comment by GarimaKapoor** [comment]
@krisis will you be able to finish it before leaving?

**Comment by krisis** [comment]
I don't think it will be possible. I will be working on #3020 next. Let me know if this is of higher priority.

**Comment by harshavardhana** [comment]
> I don't think it will be possible. I will be working on #3020 next. Let me know if this is of higher priority.

@hackintoshrao stole it.

**Comment by harshavardhana** [comment]
ping @hackintoshrao

**Comment by hackintoshrao** [comment]
yes @harshavardhana . Will fix this by 12th november.

**Comment by krisis** [comment]
@harshavardhana I spoke to @hackintoshrao, he is looking into other issues now. I will work on this issue.

**Comment by harshavardhana** [comment]
> @harshavardhana I spoke to @hackintoshrao, he is looking into other issues now. I will work on this issue.

Thanks @krisis

**Comment by GarimaKapoor** [comment]
@krisis what is the timeline of the fix.

**Comment by krisis** [comment]
I expect to send out a PR by EOD Nov 16th.

**Comment by krisis** [comment]
@harshavardhana I forgot to add "Closes <#issue> in the PR description. Could you close this issue?

**Comment by harshavardhana** [comment]
> @harshavardhana I forgot to add "Closes <#issue> in the PR description. Could you close this issue?

Closing.. @krisis
