### ISSUE TITLE
[tests] Need better coverage for `checkPostPolicy`.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3066]
Need better test coverage for `checkPostPolicy` from `signature-v4-postpolicyform.go`.

**Comment by krishnasrinivas** [comment]
@harshavardhana can you keep this open till https://github.com/minio/minio/issues/3103 is fixed, will send in more testcases after that is fixed.

**Comment by harshavardhana** [comment]
> @harshavardhana can you keep this open till #3103 is fixed, will send in more testcases after that is fixed.

Only mention the github issue next time in the PR,  if you say "fixes" then it would auto close the github issue.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas please update the timeline for the fix.

**Comment by krishnasrinivas** [comment]
timeline 12-11

**Comment by vadmeste** [comment]
Taking this.

**Comment by vadmeste** [comment]
You can close this @harshavardhana, checkPostPolicy is all green https://codecov.io/gh/minio/minio/src/4daa0d2cee9cf4b0ec7a443416a4c453779eec98/cmd/postpolicyform.go

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/commit/372da5eaf51a25159a7396d5f114e181135ef91c

**Comment by harshavardhana** [comment]
Closing @vadmeste
