### ISSUE TITLE
FS:  HeadObject (If-None-Match) incorrect response status.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3072]
- When S3Verify is run using 
  $ `./s3verify -a  <A-Key>  -s <Secret-Key> --extended -u http://localhost:9000` 
             [FAIL] Unexpected Status Received: wanted 304, got 200.
  
  HeadObject (If-None-Match) fails with incorrect response status. The test sets the `ETag==ObjectMD5Sum`, In this case the server is supposed to response with status 304.

**Comment by harshavardhana** [comment]
If you enable `MINIO_ENABLE_FSMETA` this problem is not there. We choose to return back object regardless of the said concerns here. So FS this test is not valid and it is done on purpose.
