### ISSUE TITLE
[distributed] Add generation id to uploads.json

### ISSUE THREAD

**Issue by donatello** [minio/minio#3073]
## Expected Behavior

The uploads.json file used for multipart uploads needs to have a generation id, that helps identify the latest version of the file that was written "quorum" successfully.
## Current Behavior

Currently we are using the version from the first disk on which we successfully read the file. This can lead to stale information.
## Possible Solution

Add generation id to uploads.json.
## Context

Stale information in uploads.json is a source of bugs. This was discovered while reading source code in relation to chasing down bug #3014

**Comment by harshavardhana** [comment]
This is not valid anymore closing. @donatello open a relevant bug which doesn't talk about generation id.
