### ISSUE TITLE
Server unable to start on Mac

### ISSUE THREAD

**Issue by suprnova32** [minio/minio#3075]
## Expected Behavior

The server should start and I should be able to use the browser app.

## Current Behavior

The server is not starting and is eating up all my CPU and RAM.

<img width="799" alt="screen shot 2016-10-24 at 2 38 19 pm" src="https://cloud.githubusercontent.com/assets/723365/19660983/8f14b064-99f7-11e6-8206-af325d87e9e8.png">

## Steps to Reproduce (for bugs)

1. Install minio via `brew` on macOS Sierra 10.12.1
2. Start on a non-empty folder, e.g. `minio server uploads/`
3. Watch it go on forever, without really starting.
## Context

I am unable to try minio.
## Your Environment

- Version used: 2016-10-22T00:50:41Z
- Environment name and version (e.g. nginx 1.9.1): go 1.7.3
- Server type and version: Haven't gotten this far.
- Operating System and version: macOS 10.12.1

**Comment by harshavardhana** [comment]
A new release binary has been updated https://dl.minio.io/server/minio/release/ , fixed in current release branch. Closing.
