### ISSUE TITLE
[build/release] Signing OSX binary releases. 

### ISSUE THREAD

**Issue by justinclift** [minio/minio#3077]
Thankfully, the native security mechanism on OSX - Gatekeeper - doesn't seem to have issues with the unsigned Minio binary (for OSX 10.11.6 anyway).

If at some point that changes, and you need to sign things, the steps are super simple. :smile:

This is the before step, the signing command, and the verification step.

``` bash
$ codesign --verify --verbose --deep minio 
minio: code object is not signed at all
In architecture: x86_64
```

```
$ DEV_ID="Developer ID Application: Joe Bloggs (C12AB34CDE)"
$ codesign --sign "DEV_ID" --verbose --deep minio 
minio: signed Mach-O thin (x86_64) [minio]
```

```
$ codesign --verify --verbose --deep minio 
minio: valid on disk
minio: satisfies its Designated Requirement
```

Likely worth filing this away for later use. :wink:

**Comment by harshavardhana** [comment]
We decided to ship minio now always with ``brew`` does brew provide anything special for this?

**Comment by justinclift** [comment]
From memory, Homebrew doesn't sign third party binaries during the process (that'd probably be way too open to abuse).  Homebrew formulas themselves include a sha256 for each download (eg tarball, whatever), to verify the downloaded file is what's expected.  That doesn't help with OSX Gatekeeper stuff though.

From my perspective, having Homebrew compile and install Minio (unsigned) is probably "good enough".  That's how the other source builds work, and (as far as I know) it doesn't create issues.

@ilovezfs That's correct isn't it?

**Comment by ilovezfs** [comment]
Yes. But if you do need us to distribute signed binaries, then this applies:
https://github.com/caskroom/homebrew-cask/issues/25423

**Comment by justinclift** [comment]
Awesome @ilovezfs, thanks. :smile:

**Comment by harshavardhana** [comment]
Great thanks @ilovezfs @justinclift

**Comment by harshavardhana** [comment]
> From my perspective, having Homebrew compile and install Minio (unsigned) is probably "good enough". That's how the other source builds work, and (as far as I know) it doesn't create issues.

Closing it for now, we can re-open it in future for now we want to automate releases securely from one single build machine. This process would require manual intervention. 

We gpg sign the binaries which should be fine for now. Until we find a way to automate this we will follow current mechanism based on gpg.

**Comment by justinclift** [comment]
Sure.  As a data point, that codesign command can be used for automation.

We sign the DB4S automatic nightly builds on OSX [using it](https://gist.github.com/justinclift/59e2c975100c5cd647d773bc797312f0#file-build_sqlitebrowser_nightly-sh-L87-L88). :wink:

**Comment by harshavardhana** [comment]
> Sure. As a data point, that codesign command is can be used for automation.
> 
> We sign the DB4S automatic nightly builds on OSX

Is this on Linux or macOS system? - we are doing our automation on digital ocean.

**Comment by justinclift** [comment]
On OSX. We have an older Mac Mini here on a shelf dedicated to building the nightlies. :wink:

Most of every day it's in sleep mode, but at ~4am (scheduled) it wakes up, pulls down the latest source, builds and signs the binaries from that, and uploads them to our nightlies server:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/osx/

(having the historical ones there has turned out useful occasionally.  People can use them to figure out when a bug/behaviour first started)

**Comment by harshavardhana** [comment]
For now it won't be possible for us just do this specifically for macOS alone.  Once the automation is done we might revisit this, there are other methods perhaps `docker` and brew which are good enough. 

Thanks for the tips @justinclift

**Comment by justinclift** [comment]
Sure, no worries at all. :smile:
