### ISSUE TITLE
[distributed] Controller should take URI friendly format with env in URI as well

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3091]
## Expected Behavior

The expected behavior is that 

```
minio control heal http://<access>:<secret>@ip:9000/bucket
```

Should be allowed to make it consistent with server command line syntax #3090 

## Current Behavior

Current behavior asks for explicit ENVs before running controller command.

**Comment by vadmeste** [comment]
> minio control heal http://<access>:<secret>@ip:9000/bucket

Can we fetch access/secret keys in URL, then in ENV then in config file ?

**Comment by harshavardhana** [comment]
> Can we fetch access/secret keys in URL, then in ENV then in config file ?

Yes preference is URL, ENV and then config file.

**Comment by harshavardhana** [comment]
@vadmeste in your patch documentation is missing regarding the aforementioned change. Can you add that ? Once done we can close this bug.

**Comment by harshavardhana** [comment]
Fixed by #3115
