### ISSUE TITLE
Performance: Slow Download speed of object from Minio browser on Windows.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3094]
As reported by @zorenleolumosbog  on Gitter, 

> I have the download limit of 10mb network speed on my pc and the download speed from Minio was more less 5-50kb per second, for object size 50mb-1gb and above.

Need to investigate and validate  this on windows.

**Comment by krishnasrinivas** [comment]
Download is very slow, reason not known yet. Would not be surprised if it is because of open/close in append file.

Upload slowness behavior: https://github.com/minio/minio/issues/2987

**Comment by harshavardhana** [comment]
> Download is very slow, reason not known yet. Would not be surprised if it is because of open/close in append file.
> 
> Upload slowness behavior: #2987

How does AppendFile affect while downloading?

**Comment by vadmeste** [comment]
Just a reminder, Antivirus in Windows is a real performance killer when operations are related to writing/reading, you have to disable it if there is one.

**Comment by harshavardhana** [comment]
> Just a reminder, Antivirus in Windows is a real performance killer when operations are related to writing/reading, you have to disable it if there is one.

Oh?

**Comment by krishnasrinivas** [comment]
> Just a reminder, Antivirus in Windows is a real performance killer when operations are related to writing/reading, you have to disable it if there is one.

I remember your experience with antivirus and renames ... i had tested with anti-virus disabled

**Comment by harshavardhana** [comment]
There is a bug here while trying to download from server, i am just downloading 60MB file.

![windows-issue](https://cloud.githubusercontent.com/assets/622699/19739788/2e88c9b2-9b71-11e6-96b2-e18c9e4c1d91.png)

**Comment by harshavardhana** [comment]
Did some testing on Windows 10 locally both master and release branch.  Results are correct the error on AWS instance seems like some serious problems with the instance itself.

![os details](https://cloud.githubusercontent.com/assets/622699/19747445/86c5af18-9b90-11e6-949e-3b4e766bbc7e.png)
![uploading-1 4gb](https://cloud.githubusercontent.com/assets/622699/19747443/86c0ad56-9b90-11e6-9bda-6717c252ef18.png)
![upload-mc](https://cloud.githubusercontent.com/assets/622699/19747444/86c14158-9b90-11e6-9a72-875e429ff50a.png)
![download](https://cloud.githubusercontent.com/assets/622699/19747446/86c68fd2-9b90-11e6-87da-5a31303299fa.png)

**Comment by harshavardhana** [comment]
Surprisingly even the upload problem is not visible reported by @krishnasrinivas - we should validate further. Note that anti-virus (file-system shield) was completely disabled on my setup. 

Takes around a 1minute 10secs to upload 1.4GB of ubuntu 16.04 image.

**Comment by krishnasrinivas** [comment]
@harshavardhana did the local win-10 have SSD or HDD?

**Comment by harshavardhana** [comment]
It is an SSD but it shouldnt make a difference so drastic.  Talking about downloads here. Not uploads.

**Comment by krishnasrinivas** [comment]
just verified on HDD win-10, download was fast.

**Comment by harshavardhana** [comment]
This is not reproducible even on a new aws instance anymore. Closing if reproducible again we will re-open.
