### ISSUE TITLE
feature: Add support for custom REST HTTP(S) endpoint notifications

### ISSUE THREAD

**Issue by donatello** [minio/minio#3095]
## Expected Behavior

Minio could send bucket event notifications to a custom user-defined REST web-server endpoint. The endpoint would get requests from Minio in a fixed format (say a particular JSON-encoded structure) whenever events occur in the bucket. This let's a user define a custom service for receiving bucket notifications.
## Current Behavior

It is currently not possible to do this, but would be a useful enhancement.
## Possible Solution

Can be implemented similar to existing external notifications support. For this feature some configurable parameters could be:
- Endpoint information (like `http://example.com:9100/minioevents/`)
- HTTP(s) authentication information
- The definition of a success response from the custom server (like say HTTP status code 200 or 2xx).
- A max retry count in case of failure responses.
## Context

It is an additional user convenience to have the option of defining their own web-service to receive bucket notification events.

**Comment by harshavardhana** [comment]
Kafka support takes priority over some custom REST endpoint, moving this future and low priority for now.

**Comment by alexellis** [comment]
I could see this as being very useful. A HTTP(s) post seems like one of the easier cases to support and you now have quite extensive support for other event types. What do you think?

Is there a plugin model? Do you have any code you could point me at?

**Comment by harshavardhana** [comment]
> Is there a plugin model? Do you have any code you could point me at?

Go doesn't have a nice plugin model there are lot of boiler code needs to be added, we are planning to explore plugin model in go1.8 which has plugin model standardized.

One such example here is - https://github.com/minio/minio/blob/master/cmd/notify-kafka.go

**Comment by alexellis** [comment]
I'm starting to make the changes with this, probably 70-85% there.

https://github.com/alexellis/minio/pull/1/files

I'll clean up the commits and then send over when reviewed by @harshavardhana .

**Comment by harshavardhana** [comment]
Fixed by #3566 - Thanks a lot @alexellis
