### ISSUE TITLE
docs: document using s3fs, drupal with Minio

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3097]
@illmatix reported problem with uploading files to Minio using drupal + s3fs

**Comment by vadmeste** [comment]
I was unable to make it work for the moment.

s3fs: 7.x-2.6  supports custom endpoint but without activating path style
s3fs: 7.x-3.0-alpha  and 7.x-3.0-dev have bugs in custom endpoints, also no indication for path style flag

**Comment by illmatix** [comment]
Anis,

Thanks for the review. that seems to be the position i was able to get to.
I didn't realize there was some sort of path style flag though.

**Comment by GarimaKapoor** [comment]
@koolhead17 were you able to test?

**Comment by koolhead17** [comment]
@GarimaKapoor was working on Ruby related projects, will test it coming week and update?

**Comment by GarimaKapoor** [comment]
@koolhead17 any update on this?

**Comment by koolhead17** [comment]
@GarimaKapoor will need some more time for this. Will update it soon I have the test done on drupal8.

**Comment by harshavardhana** [comment]
> @GarimaKapoor will need some more time for this. Will update it soon I have the test done on drupal8.

ping @koolhead17 was there any issue with drupal testing with Minio?

**Comment by koolhead17** [comment]
@harshavardhana I get back on this today and update it.

**Comment by GarimaKapoor** [comment]
@koolhead17 any updates?

**Comment by koolhead17** [comment]
@GarimaKapoor Timeline this week for it.

**Comment by GarimaKapoor** [comment]
@koolhead17 any updates on this?

**Comment by harshavardhana** [comment]
ping @koolhead17

**Comment by harshavardhana** [comment]
ping @koolhead17 - any updates on this?

**Comment by koolhead17** [comment]
@harshavardhana got involved with other task, will get back to it soon.

**Comment by GarimaKapoor** [comment]
@koolhead17 please update the status. and the timeline for the fix

**Comment by koolhead17** [comment]
@GarimaKapoor I will work on this tomorrow 20th feb and come up with my findings.

**Comment by koolhead17** [comment]
This can be closed because the module on drupal8 is still in development and on Drupal 7, it uses older version of AWS-S3 PHP.

**Comment by worthwhileindustries** [comment]
Anyone here get this working on drupal 8 with https://www.drupal.org/project/s3fs 8.x-3.0-alpha7 ... it's using the latest sdk aws/aws-sdk-php (3.36.7).

**Comment by harshavardhana** [comment]
> Anyone here get this working on drupal 8 with https://www.drupal.org/project/s3fs 8.x-3.0-alpha7 ... it's using the latest sdk aws/aws-sdk-php (3.36.7).

Very cool thanks @worthwhileindustries we will evaluate, can you open a new issue ?

**Comment by worthwhileindustries** [comment]
@harshavardhana https://github.com/minio/minio/issues/4914

**Comment by harshavardhana** [comment]
> @harshavardhana #4914

Thanks @worthwhileindustries
