### ISSUE TITLE
How to use paperclip with Minio?

### ISSUE THREAD

**Issue by sadysnaat** [minio/minio#3117]
When used with paperclip, getting this error

Aws::S3::Errors::InvalidAccessKeyId in BooksController#create
The AWS Access Key Id you provided does not exist in our records.
# Environment

Code with which we can reproduce the error
[Rails Project link](https://github.com/sadysnaat/estuk/tree/minio-paperclip)

I am using dotenv-rails gem for env variables.

I am running a minio server from docker image as following

``` bash
docker run -p 9000:9000 --name minio1 \
-e "MINIO_ACCESS_KEY=ACCESS_KEY" \
  -e "MINIO_SECRET_KEY=SECRET_KEY" \
minio/minio server /export
```

**Comment by harshavardhana** [comment]
After some good amount of testing finally arrived at a right configuration which works in your situation.

Purposefully hard-coded the value but you can pick them up from dotenv style as well. 

```
 config.paperclip_defaults = {
    storage: :s3,
    s3_protocol: ':https',
    s3_permissions: 'private',
    s3_region: 'us-east-1', #ENV.fetch("AWS_REGION"),    
    s3_credentials: {
      bucket: 'testbucket', #ENV.fetch("AWS_BUCKET"),
      access_key_id: 'Q3AM3UQ867SPQQA43P2F',#ENV.fetch("AWS_ACCESS_KEY_ID"),
      secret_access_key: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG', #ENV.fetch("AWS_SECRET_ACCESS_KEY"),
    },
    s3_host_name: 'play.minio.io:9000',    
    s3_options: {
      endpoint: "https://play.minio.io:9000", # for aws-sdk
      force_path_style: true # for aws-sdk (required for minio)
    },
    url: ':s3_path_url',
    path: "/:class/:id.:style.:extension"    
  }  
```

I just used play our public server.  You can change the IPs and protocol depending on your needs.

**Comment by harshavardhana** [comment]
Fixed via - https://github.com/minio/cookbook/pull/107
