### ISSUE TITLE
[distributed] Cannot list incomplete uploads or reupload an object

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3129]
## Expected Behavior

To be able to list incomplete uploads and re-upload an object 
## Current Behavior

Not able to list incomplete uploads and reupload an object

```
$ mc cp /tmp/myobj0 myminiold1/kp-test-minio-py/my-boring-object-0/
mc: <ERROR> Failed to copy ‘/tmp/myobj0’. Object key is missing, object key cannot be empty
```

```
$ mc ls -I myminiold1/kp-test-minio-py/my-boring-object-0                          
mc: <ERROR> Unable to initialize target ‘myminiold1/kp-test-minio-py/my-boring-object-0’. The specified key does not exist. 
```
## Steps to Reproduce (for bugs)

Shutdown one minio instance in the middle of parallel object uploads of 128 mb (not sure concretely how to reproduce this)

I've attached the export directories to this issue, you can notice that part.1 is missing in minio4/.minio.sys/multipart/kp-test-minio-py/my-boring-object-0/bbd32d06-a1c3-48a0-a150-3954303a5d3e/

[upload_not_possible.tar.gz](https://github.com/minio/minio/files/560429/upload_not_possible.tar.gz)

Minio log:
`time="2016-10-30T11:47:28Z" level=error msg="Unable to list uploaded parts." cause="Object not found: .minio.sys#bbd32d06-a1c3-48a0-a150-3954303a5d3e/part.1" location="[object-handlers.go:798:objectAPIHandlers.ListObjectPartsHandler()]" stack="xl-v1-multipart-common.go:253:xlObjects.statPart xl-v1-multipart.go:577:xlObjects.listObjectParts xl-v1-multipart.go:633:xlObjects.ListObjectParts <autogenerated>:843:(*xlObjects).ListObjectParts object-handlers.go:796:objectAPIHandlers.ListObjectPartsHandler api-router.go:49:(objectAPIHandlers).ListObjectPartsHandler-fm"`
## Your Environment

Docker with master minio

**Comment by harshavardhana** [comment]
Merged a patch #3124 on a related note can you validate this scenario again? @vadmeste

**Comment by harshavardhana** [comment]
Do you see this behavior anymore. If there is a different symptom can you open another bug @vadmeste ?

**Comment by vadmeste** [comment]
> Do you see this behavior anymore. If there is a different symptom can you open another bug @vadmeste ?

This one seems to be fixed but there is another one, I am opening a new bug.
