### ISSUE TITLE
[Distributed] Data directory strange behaviour

### ISSUE THREAD

**Issue by shinji62** [minio/minio#3144]
I want to place the data inside /var/vcap/store/minio-server
It's common to mount the volume the directory to the same mounting point for all instance.
As it's easier to automate deployment.

So it seems the directory is create from the script running the command line, in my case from monit script.

```bash
STORE_DIR=/var/vcap/store/minio-server
exec minio server --address :9000 \
      10.244.187.61:${STORE_DIR}/ 10.244.187.62:${STORE_DIR}/ 10.244.187.63:${STORE_DIR}/ 10.244.187.64:${STORE_DIR}/
      >>  ${LOG_DIR}/minio_server.stdout.log \
      2>> ${LOG_DIR}/minio_server.stderr.log
```

## Expected Behavior
Expected the directory to be the one I give during the start command.

```
10.244.187.62:/var/vcap/store/minio-server 
```
I was expected that's mean on 10.244.187.62 the data directory is `/var/vcap/store/minio-server `
```
Initializing data volume for the first time.
[01/04] 10.244.187.62:/var/vcap/store/minio-server - 77 GiB online
[02/04] 10.244.187.61:/var/vcap/store/minio-server - 77 GiB online
[03/04] 10.244.187.63:/var/vcap/store/minio-server - 77 GiB online
[04/04]  10.244.187.64:/var/vcap/store/minio-server - 77 GiB online
```

## Current Behavior
I use monit to start my server and it seems it took the monit directory as home
```
Initializing data volume for the first time.
[01/04] /etc/sv/monit/10.244.187.61:/var/vcap/store/minio-server - 77 GiB online
[02/04] /etc/sv/monit/10.244.187.62:/var/vcap/store/minio-server - 77 GiB online
[03/04] /etc/sv/monit/10.244.187.63:/var/vcap/store/minio-server - 77 GiB online
[04/04] /etc/sv/monit/10.244.187.64:/var/vcap/store/minio-server - 77 GiB online>
```

## Possible Solution
But data inside the directory as given into the command line.

## Steps to Reproduce (for bugs)
Just run with 4 nodes 

## Context
Try to automate distributed deployment.

## Your Environment
Last master commit as 11/1/2016

**Comment by harshavardhana** [comment]
> STORE_DIR=/var/vcap/store/minio-server
> exec minio server --address :9000 \
>       10.244.187.61:${STORE_DIR}/ 10.244.187.62:${STORE_DIR}/ 10.244.187.63:${STORE_DIR}/ 10.244.187.64:${STORE_DIR}/
>       >>  ${LOG_DIR}/minio_server.stdout.log \
>       2>> ${LOG_DIR}/minio_server.stderr.log

This syntax is not supported anymore that is why it create a directory with that style instead.  Take a look at the `minio server -h`

```
  6. Start minio server for a 4 node distributed setup. Type the following command on all the 4 nodes exactly.
      $ export MINIO_ACCESS_KEY=minio
      $ export MINIO_SECRET_KEY=miniostorage
      $ minio server http://192.168.1.11/mnt/export/ http://192.168.1.12/mnt/export/ \
          http://192.168.1.13/mnt/export/ http://192.168.1.14/mnt/export/

  7. Start minio server on a 4 node distributed setup. Type the following command on all the 4 nodes exactly.
      $ minio server http://minio:miniostorage@192.168.1.11/mnt/export/ \
          http://minio:miniostorage@192.168.1.12/mnt/export/ \
          http://minio:miniostorage@192.168.1.13/mnt/export/ \
          http://minio:miniostorage@192.168.1.14/mnt/export/
```

**Comment by shinji62** [comment]
@harshavardhana Thanks for the info, I will try it.
Btw where to you put the port ? using `--address 9000` or just normal `http://192.168.1.11:900/mnt/export/`

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for the info, I will try it.
> Btw where to you put the port ? using --address 9000 or just normal http://192.168.1.11:900/mnt/export/

Port will be common across all so you can just set it as shown below. 

```
minio server --address ":10000" http://192.168.1.11/mnt/export/ http://192.168.1.12/mnt/export/ \
          http://192.168.1.13/mnt/export/ http://192.168.1.14/mnt/export/
```

Same command line to run on all the nodes.

**Comment by shinji62** [comment]
Ok I try that 

```
exec minio server --address ":9000" \
       http://10.244.187.61/var/vcap/store/minio-server/  http://10.244.187.62/var/vcap/store/minio-server/  http://10.244.187.63/var/vcap/store/minio-server/  http://10.244.187.64/var/vcap/store/minio-server/  \
      >>  ${LOG_DIR}/minio_server.stdout.log \
      2>> ${LOG_DIR}/minio_server.stderr.log
```

Now I get 

```
time="2016-11-01T08:05:07Z" level=fatal msg="Storage endpoint error." cause="Total number of disks should be multiples of '2'" location="[server-main.go:325:checkServerSyntax()]"
```

**Comment by harshavardhana** [comment]
@shinji62 looks like something else clobbering up the CLI args. do you have a sample script which i can use it locally and see what is the issue?

**Comment by shinji62** [comment]
Thanks, it works !
I will give you my project links soon.
Any pages will all options ?

**Comment by harshavardhana** [comment]
> Thanks, it works !
> I will give you my project links soon.
> Any pages will all options ?

Largely `minio server -h` for master has the most comprehensive docs, for distributed we are in the process of updating docs.minio.io

**Comment by harshavardhana** [comment]
Thanks @shinji62
