### ISSUE TITLE
[Distributed] minio server does not respond/quit on SIGINT/SIGQUIT/SIGTERM signals.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#3154]
When minio server is waiting for quorum at startup like below, it does not respond to SIGINT/SIGQUIT/SIGTERM signals.  This causes node waiting too long to reboot/shutdown.

Below is the relevant log.
```
Initializing data volume. Waiting for minimum 5 servers to come online.
[minio-arm1:]:9000:/export/xl/mydisk still unreachable.
[minio-arm2:]:9000:/export/xl/mydisk still unreachable.
[minio-arm3:]:9000:/export/xl/mydisk still unreachable.
[minio-arm4:]:9000:/export/xl/mydisk still unreachable.
[minio-arm5:]:9000:/export/xl/mydisk still unreachable.
[minio-arm6:]:9000:/export/xl/mydisk still unreachable.
[minio-arm7:]:9000:/export/xl/mydisk still unreachable.
[minio-arm8:]:9000:/export/xl/mydisk still unreachable.
Initializing data volume. Waiting for minimum 5 servers to come online.
```

Minio version:
Commit ID: 9db2205db38c1c9f404c8d819007671af84c09e8

**Comment by vadmeste** [comment]
Currently SIGTERM twice will shutdown Minio permaturaly.

For a graceful shutdown, we probably need to broadcast shutdown signal to different modules, (channel with one writer and different readers), we had a generic graceful shutdown mechanism also, we can consider bringing it back again, what do you think?

**Comment by harshavardhana** [comment]
Will ping you about this.
