### ISSUE TITLE
[distributed] If disks are down we are leaving tmp files behind

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3168]
```
$ ls -ltr /mnt/export1/minio/.minio.sys/tmp/ | wc -l
26337
```

## Expected Behavior
No tmp files should be left behind

## Current Behavior
tmp files are left behind 100s of them.

**Comment by GarimaKapoor** [comment]
@vadmeste please update the timeline for the fix.

**Comment by harshavardhana** [comment]
Closing as duplicate of #3199
