### ISSUE TITLE
[feature]: minio event notification in plain text backend

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#3174]
We have a community request via @JackTiger for providing minio event notification in plain text backend. 

We are currently providing event notification to backends Redis, elasticsearch, nats, postgresql.

**Comment by harshavardhana** [comment]
There is already ListenBucketNotification which does the same thing, wouldnt that work ?

**Comment by harshavardhana** [comment]
> There is already ListenBucketNotification which does the same thing, wouldnt that work ?

This feature request is similar to this issue - https://github.com/minio/minio/issues/3095 . But this feature itself  is already implemented can be solved by just using `mc watch` or ListenBucketNotification API. 

Closing.
