### ISSUE TITLE
[distributed]: Chaos test failure with `mc rm`.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3178]
- Chaos test fails to delete the object with `mc rm`. It displays that the object was deleted successfully, but `mc ls` still lists the object.
- Even though `mc ls` lists the object `mc cp` fails to get the object.
## Expected Behavior

- Successful deletion of object using `mc rm`.
- `mc ls` shouldn't list the object after `mc rm`.
-   `If` it lists  `then` it  should be able to possible the fetch back the object using `mc cp`. 
## Current Behavior

- `mc rm` fails to remove the object from `mc ls` entry.
- `$ mc ls` lists the same object.
- But `$ mc cp` fails to fetch the object.

Here is the output of list operations performed when the 8 nodes were under round robin chaos test .
```sh
$ mc rm chaos1/rao1/1gb
Removed ‘chaos1/rao1/1gb’.

$ mc ls chaos1/rao1/
[2016-11-04 14:53:50 UTC] 1.0GiB 1gb

$ mc cp  chaos1/rao1/1gb .
mc: <ERROR> Unable to stat 'chaos1/rao1/1gb'. Object key is missing, object key cannot be empty

```
## Possible Solution

Not sure. 
## Steps to Reproduce (for bugs)

1. Run the Chaos test. 
```sh
  ./master --endpoints="minio2:9997,minio3:9997,minio4:9997,minio5:9997,minio6:9997,minio7:9997,minio8:9997" -recover=3  -rounds=30 -end-point=9199
```

2. run `$ mc rm chaos1/rao1/1gb` when chaos round robin test is going on.

3. run `mc ls chaos1/rao1`

4. run `$ mc cp  chaos1/rao1/1gb .`

## Context

Chaos test. Click [here](https://github.com/minio/chaos) for info on running chaos test.
## Your Environment

* Version used: Master at e6965ca066973861c923e477cc7df8fce89431dd .
* Environment name and version (e.g. nginx 1.9.1): Packet linux server.

**Comment by harshavardhana** [comment]
You need to heal the object here were the servers going up and down when this happened? did you have quorum to successfully complete the operation? 

Any server errors etc.?

**Comment by hackintoshrao** [comment]
> were the servers going up and down when this happened? 

  Yes. 

> did you have quorum to successfully complete the operation? 

  Yes. Any given point in time only one of the node was down.

> Any server errors ? 

   Will log them and test again.

**Comment by harshavardhana** [comment]
Without having some sort of transaction support it is not possible to ignore this object since `mc ls` will still list the object since it lists from only one disks not quorum number of disks. 

`mc ls` output shouldn't be considered as the sanctimonious output it is the 'mc cp's behavior which would indicate that object really exists on not. 

Now in case of healing can purge dangling entries like this safely even for this we need transaction support. 

https://github.com/minio/minio/issues/1366

**Comment by harshavardhana** [comment]
This case will be handled properly in object healing where inconsistent objects will be purged safely.
