### ISSUE TITLE
[browser] Removing object throws "Object not found" for previously deleted object.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#3181]
## Expected Behavior
It should not throw an error

## Current Behavior
"Object not found" error is shown and "Are you sure want to delete?" modal doesn't disappear.

## Possible Solution
It could be easy to fix at web handler side to not throw this error.

## Steps to Reproduce (for bugs)
1. Open minio browser for a bucket.
2. Remove an existing object using `mc rm`
3. Now try to remove the same object in the browser.

## Minio version:
`Commit-ID: bf3c93a8cc264a2add6d3074b78d3a7d8954a523`

**Comment by GarimaKapoor** [comment]
@balamurugana please update the timeline of the fix.

**Comment by GarimaKapoor** [comment]
@balamurugana can you please update the timeline for this fix.
