### ISSUE TITLE
[distributed] Document distributed XL - TLS based setup

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3182]
```
 if rpcClient.secureConn {
                hostname, _, splitErr := net.SplitHostPort(rpcClient.node)
                if splitErr != nil {
                        return nil, errors.New("Unable to parse RPC address <" + rpcClient.node + "> : " + splitErr.Error())
                }
                // ServerName in tls.Config needs to be specified to support SNI certificates
                conn, err = tls.Dial("tcp", rpcClient.node, &tls.Config{ServerName: hostname})
        } else {
                // Have a dial timeout with 3 secs.
                conn, err = net.DialTimeout("tcp", rpcClient.node, 3*time.Second)
        }
        if err != nil {

``` 

Following code can lead to bugs, `tls.Config` should be passed in the initializer from the top level.  Here the strict reliance on `hostname` is wrong for the most part a successfully running HTTPS server might not provide a proper 'hostname' in the first place. 

So in case of TLS this always fails.

## Expected Behavior
Works transparently with TLS.

## Current Behavior
Restrictive usage fails most of the time.

## Possible Solution
Fix the behavior and handle the TLS connections regardless of SNI requirements.

## Steps to Reproduce (for bugs)
Quite easy run `minio server` with HTTPS without hostname configured.

**Comment by vadmeste** [comment]
> Quite easy run minio server with HTTPS without hostname configured.

Can you elaborate on this? AFAIK, TLS doesn't properly work when host name is not specified.

**Comment by harshavardhana** [comment]
> Can you elaborate on this? AFAIK, TLS doesn't properly work when host name is not specified.

NO it does work properly i don't think anyone has to specify --address specifically to run https properly.  We need to re-do the behavior in this code path to handle both self-signed and regular SNI certs.

**Comment by vadmeste** [comment]
> i don't think anyone has to specify --address specifically to run https properly.

I must be misunderstanding you, can you tell how can we produce a bug ?

**Comment by harshavardhana** [comment]
> I must be misunderstanding you, can you tell how can we produce a bug ?

For example look at `https://churchofminio.com:9000/minio/login` i tried setting bucket policy from UI and saw this message 

```
ERRO[0019] Error sending peer update bucket policy to :9000 - tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config  cause=tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config location=[s3-peer-client.go:222:S3PeersUpdateBucketPolicy()]
ERRO[0019] Error sending peer update bucket policy to  - Unable to parse RPC address <> : missing port in address  cause=Unable to parse RPC address <> : missing port in address location=[s3-peer-client.go:222:S3PeersUpdateBucketPolicy()]
```

**Comment by harshavardhana** [comment]
Now while removing policy

```
 ERRO[0080] Error sending peer update bucket policy to  - Unable to parse RPC address <> : missing port in address  cause=Unable to parse RPC address <> : missing port in address location=[s3-peer-client.go:222:S3PeersUpdateBucketPolicy()]
ERRO[0080] Error sending peer update bucket policy to :9000 - tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config  cause=tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config location=[s3-peer-client.go:222:S3PeersUpdateBucketPolicy()]
```

**Comment by vadmeste** [comment]
Here is my findings:
- Specifying DNS is really needed to make TLS works perfectly.
- We can extract DNS name from the certificate found under certs/ directory. However, we could also find more than one DNS name (in case of SNI certificates), even if there is only one, it could be useless for the machine configuration (like ping minio1.user.com could be unsolvable in the machine where Minio lives)
- I tried to configure an intranet which uses TLS + custom CA but DNS names (or fixed ip addresses) are still needed.
- After all, if we are targetting a **local** ip address, can't we just bypass certificate validation?
- Looks like it is more natural to avoid rpc loopback call.

**Comment by harshavardhana** [comment]
> Specifying DNS is really needed to make TLS works perfectly.

This would mean that we need to take domain special flag other than TLS to make distributed setup work properly. We will need some discussion on this. Can you put more details on the flow here? for example if we have a wildcard DNS for a domain `*.domain.com` 

And distributed servers are `m1.domain.com, m2.domain.com` are you saying that each need to specify domain? 

> We can extract DNS name from the certificate found under certs/ directory. However, we could also find more than one DNS name (in case of SNI certificates), even if there is only one, it could be useless for the machine configuration (like ping minio1.user.com could be unsolvable in the machine where Minio lives)

We could pick the first one that the SNI points to?. Also in what situation `minio1.user.com` is unresolvable? 

> I tried to configure an intranet which uses TLS + custom CA but DNS names (or fixed ip addresses) are still needed.
> After all, if we are targetting a local ip address, can't we just bypass certificate validation?

For a loopback call yes we can. But fundamentally we won't make a call in this situation.

> Looks like it is more natural to avoid rpc loopback call.

This is being fixed by @donatello - there is a patch already. We have to validate after that is merged.

**Comment by harshavardhana** [comment]
@vadmeste confirmed usage of letsencypt based certs with distributed setup, he will be sending a documented way to achieve it. Moving this as not a bug but documenting the behavior.

**Comment by vadmeste** [comment]
@harshavardhana, I think we have missed the self signed certificates part (with custom CA), shall we do it ?

**Comment by harshavardhana** [comment]
> @harshavardhana, I think we have missed the self signed certificates part (with custom CA), shall we do it ?

Yes that is also needed.

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/commit/6512d9978ec8fe6c30bca6bfec1d3211be77f105

**Comment by harshavardhana** [comment]
Closing as fixed by https://github.com/minio/minio/commit/6512d9978ec8fe6c30bca6bfec1d3211be77f105
