### ISSUE TITLE
[distributed] PutObject hangs when n/2 disks are down

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3184]
## Expected Behavior
PutObject should get 503 when n/2 disks are down

## Current Behavior
PutObject hangs.

## Steps to Reproduce (for bugs)
1. have 4 out of 6 servers up.
2. run the client program (source pasted below)
3. Ctrl-C a server.
4. Client program waits without any timeout

client:
```
package main

import (
	"fmt"
	"log"
	"os"
	"strings"
	"sync"

	minio "github.com/minio/minio-go"
)

func main() {
	accessKey := os.Getenv("MINIO_ACCESS_KEY")
	secretKey := os.Getenv("MINIO_SECRET_KEY")

	testCases := []struct {
		host string
		data string
	}{
		{"localhost:9001", "one"},
		{"localhost:9002", "two"},
		{"localhost:9003", "three"},
		{"localhost:9004", "four"},
		{"localhost:9005", "five"},
		{"localhost:9006", "six"},
	}

	i := 0
	for {
		i++
		fmt.Println(i)
		wg := &sync.WaitGroup{}
		for _, test := range testCases {
			wg.Add(1)
			go func(host string, data string) {
				defer wg.Done()
				client, err := minio.New(host, accessKey, secretKey, false)
				if err != nil {
					log.Fatalln(err)
				}
				_, err = client.PutObject("test", "testobject", strings.NewReader(data), "")
				if err != nil {
					log.Println(err)
				}
			}(test.host, test.data)
		}
		wg.Wait()
	}
}
```

**Comment by harshavardhana** [comment]
This is the same scenario as #3185 writeLock is waiting for N/2+1 servers.

A 503 service unavailable only happens during the startup, once the object layer has initialized it never occurs in its lifetime.

**Comment by harshavardhana** [comment]
Actually Lock cannot timeout, if it does it would proceed forward. There needs to be a way to actively cancel the ObjectLayer operation and return error when the quorum is not available. We don't even attempt to lock but this functionality would make additional calls to make sure if we have enough quorum even to begin with.

**Comment by harshavardhana** [comment]
Closing this and merging with #3185
