### ISSUE TITLE
erasure: Without read or write quorum object layer hangs with no errors to client.

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3185]
## Expected Behavior
`mc cat` should return error when quorum is not available.
`mc cp` should return error when quorum is not available.

## Current Behavior
`mc cat` hangs.
`mc cp` hangs 

## Steps to Reproduce (for bugs)

``mc cat`` hangs 
1. Create a 3:3 distributed-XL setup
2. mc cp /etc/passwd myminio/testbucket
3. bringdown 4 servers
4. `mc cat myminio/testbucket/passwd` hangs

``mc cp`` hangs
1. Create a 3:3 distributed-XL setup
2. bring down 3 servers
3. mc cp /etc/passwd myminio/testbucket hangs

**Comment by harshavardhana** [comment]
> I think Get http://localhost:9001/test/?location= request hangs when trying to get lock.

I think it is expected in distributed Lock right now, may be we can have a canceler timeout once it has attempted enough.  // cc @fwessels

**Comment by harshavardhana** [comment]
Actually Lock cannot timeout, if it does it would proceed forward. There needs to be a way to actively cancel the ObjectLayer operation and return error when the quorum is not available.  We don't even attempt to lock with this functionality - note it would need to make additional calls to make sure if we have enough quorum even to begin with.

**Comment by harshavardhana** [comment]
Merged #3184 with this bug and changed the overall description.

**Comment by abperiasamy** [comment]
With N/2 redundancy, it is a likely condition only in a desperate situation. Ideally the handlers should time out at the higher level and return appropriate response. Locks with deadlines are dangerous. `context` package is meant for this purpose, however context adds more complexity to minio for a tiny little benefit. It is not all that hard to implement deadline for top level handler go routines alone. This is not a blocker for this release.

**Comment by harshavardhana** [comment]
> This is not a blocker for this release.

Moving it out.

**Comment by fwessels** [comment]
If you would want to cancel/error out, to Go way of doing it is with an additional go routine that has a timeout and in that way abort the blocking operation.

We can decide on a case-by-case basis when we want to do this. Or come up with some sort of 'template' that adds this functionality.

**Comment by deekoder** [comment]
Discuss and finalize where we stand on these class of bugs.

**Comment by deekoder** [comment]
Duplicate #3234

**Comment by donatello** [comment]
#3234 is about letting the Minio cluster come up and serve reads when only a "readQuorum" number of servers is up (i.e. `n/2` of `n` servers are up) - that can be resolved independently of this one.

Write-requests hanging when write-quorum is not present and read-requests hanging when read-quorum is not present is related to the locking behavior - it currently does not have a provision to return an error or timeout.

In my view, this issue should be re-opened.

**Comment by deekoder** [comment]
@fwessels  is investigating. We need to discuss again after investigating Relevant thread we were looking at https://github.com/golang/go/issues/6123

**Comment by fwessels** [comment]
The thread put me in the direction as per https://github.com/fwessels/lsync (as opposed to using multiple go-routines, channels, select timeouts etc. but that has many corner cases).

After review we can integrate this (and implement the same API for dsync). 

Can also help in tackling #4337

**Comment by harshavardhana** [comment]
PR #4377 addresses this @balamurugana , unblocking this issue PR has been sent @deekoder

**Comment by balamurugana** [comment]
@harshavardhana It would be helpful how `lsync` is solving the problem.

**Comment by harshavardhana** [comment]
> @harshavardhana It would be helpful how lsync is solving the problem.

Lsync is solving by adding a timeout for sync and returning error if it should timeout with in the defined interval. This basically is to solve long running Locks to not stay there long and also be able to send back a proper error to the client in case of quorum failure where as in current code in dsync it retries infinitely. A relevant PR for https://github.com/minio/dsync/pull/49 has also been submitted please review that as well. 

Also an independent repo here https://github.com/minio/lsync explains in README.md 

// cc @fwessels can provide more deeper explanation if you have more questions @balamurugana

**Comment by balamurugana** [comment]
@harshavardhana I believe lock is created and sent within the `timeout` ie after timeout there is no lock created at all for this request.

@fwessels It would be great to get info of the design and implementation of `lsync` before reading the PR.

**Comment by fwessels** [comment]
@balamurugana that is correct, if a lock can be obtained before the timeout it is granted as normal and it is signaled back to the user that a lock was obtained (and the client needs to unlock it at a later stage). 
When more time has elapsed than the timeout duration (and no lock has been obtained), then it will return and signal back that no lock was acquired. In this case the client should not proceed with the operation for which it seeked to get the lock but exit out instead . Also no unlock should be done since no lock was granted.

**Comment by balamurugana** [comment]
@fwessels thanks.  Do we have `lsync` design/implementation doc?

**Comment by fwessels** [comment]
@balamurugana we went over the design last week with PA team. Note that the (eventual) implementation is rather straightforward (and loosely based on dsync lock loop).
It essentially comes down to trying to get the (single) write lock or acquire a read lock.
The test suite is analogous to sync and dsync.

**Comment by harshavardhana** [comment]
This can be closed I think . Since we already have lsync implemented and released.

@deekoder @fwessels ??

**Comment by fwessels** [comment]
Yes, correct, can be closed.
