### ISSUE TITLE
[distributed]: Round Robin Chaos test failure with `exec-concurrent TestMakeBucketError`.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3191]
Chaos test fails for `exec-concurrent TestMakeBucketError` load at a CONCURRENCY level of 100.
## Expected Behavior

Choas test to pass with `exec-concurrent TestMakeBucketError`
## Current Behavior

AT`CONCURRENCY` of 100, 99 of them pass, only one fails with following error. 
```sh
Goroutine: 91
--- FAIL: TestMakeBucketError (17.71s)
        api_functional_v4_test.go:92: Error: Multiple disks failures, unable to write data. io5qoqbe9ohfp5ri064te2enmaep3i
```
Its a 8 node setup, quorum is satisfied at any point in time since only one node is down at a given point in time in Round Robin chaos test.

The test worked fine when a node was permanently down. But the issue occurred when nodes were going up and down.
## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Run [Chaos test](https://github.com/minio/chaos). 
  ```sh
   ./master --endpoints="minio2:9997,minio3:9997,minio4:9997,minio5:9997,minio6:9997,minio7:9997,minio8:9997" -recover=1  -rounds=10 -minio-port=9199
   ```
2. Run [exec-concurrent TestMakeBucketError](https://github.com/minio/perftest/tree/master/exec-concurrent) on the node1 (other 7 nodes are under round robin chaos test) at a CONCURRENCY of 100.
    
3. check  output.log . 

## Context

- Chaos test with exec-concurrent load.
## Your Environment

* Version used: Master at e6965ca066973861c923e477cc7df8fce89431dd
* Server type and version: packet linux nodes.

**Comment by harshavardhana** [comment]
Do you still have the setup handy @hackintoshrao ?

**Comment by hackintoshrao** [comment]
Sorry missed out, just saw this, Yes, I have the setup ready the issues I've opened.

**Comment by harshavardhana** [comment]
> Sorry missed out, just saw this, Yes, I have the setup ready the issues I've opened.

Thanks will ping you @hackintoshrao

**Comment by hackintoshrao** [comment]
Closing this. Will run the tests again on the latest master.
