### ISSUE TITLE
[distributed]:  Nodes fails to restart during a failed chaos test.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3196]
Chaos test fails for `exec-concurrent TestMakeBucketError` load at a CONCURRENCY level of 100 (Different from the test used in https://github.com/minio/minio/issues/3191).
But All nodes fails to restart with error, more description will be provided below.
## Expected Behavior

- Test to pass.
- Nodes to restart gracefully in Chaos test.
## Current Behavior

- Firstly the Chaos test under `exec-concurrent TestMakeBucketRegions`(with Concurrency level of 100) load fails. 99 of them pass and only one of them fail.
 
   ```sh
   Goroutine: 51
  FAIL: TestMakeBucketRegions (19.42s)
        api_functional_v4_test.go:138: Error: Multiple disks failures, unable to write data.   6kcyuyx4gjfuki34byeybgh2vimvg0
  FAIL
    ```
- Then multiple nodes fail to restart. 7 out of 8 nodes were subjected to chaos test. All 7 failed to start again. Here are the errors with which the nodes failed to restart.

| Node Number | The error with which the node failed to restart                                                                                         |
|-------------|-----------------------------------------------------------------------------------------------------------------------------------------|
| Node2       | time="2016-11-07T05:24:03Z" level=fatal msg="Unable to load all bucket policies." cause="Bucket not found: lszh0yri6lxneyb2tbaypmmlcw4  |
| Node3       | time="2016-11-07T05:24:03Z" level=fatal msg="Unable to initialize event notification." cause="disk not found" location="[routers.go:74: |
| Node4       | time="2016-11-07T05:24:03Z" level=fatal msg="Unable to load all bucket policies." cause="Bucket not found: lszh0yri6lxneyb2tbaypmmlcw4  |
| Node5       | time="2016-11-07T05:24:03Z" level=fatal msg="Unable to initialize event notification." cause="disk not found" location="[routers.go:74  |
| Node 6      | time="2016-11-07T06:44:24Z" level=fatal msg="Unable to load all bucket policies." cause="Bucket not found: 03rxe6qus9tsmqym1wryg9s09yy  |
| Node8       | time="2016-11-07T05:26:09Z" level=fatal msg="Unable to load all bucket policies." cause="Bucket not found: e31buocts6ti69ixyoid20atlfh  |
| Node 7      | Couldn't find the error in the service status.                                                                                          |
## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Run [Chaos test](https://github.com/minio/chaos). 
  ```sh
   ./master --endpoints="minio2:9997,minio3:9997,minio4:9997,minio5:9997,minio6:9997,minio7:9997,minio8:9997" -recover=1  -rounds=10 -minio-port=9199
   ```
2. Run [exec-concurrent TestMakeBucketError](https://github.com/minio/perftest/tree/master/exec-concurrent) on the node1 (other 7 nodes are under round robin chaos test) at a CONCURRENCY of 100.
    
3. check  output.log . 

4. Go to each node and check `service minio status`

## Context

- Chaos test with `exec-concurrent TestMakeBucketError` load at a concurrency of 100.
## Your Environment

* Version used: Latest master at 9161016962afc92cf42a2dd3cbdbc05aca8ae375 . 
* Server type and version: Packet linux nodes.

**Comment by harshavardhana** [comment]
We need to test this with latest master as well @hackintoshrao

**Comment by hackintoshrao** [comment]
I'll test again.

**Comment by harshavardhana** [comment]
> I'll test again.

Can we do this together? @hackintoshrao

**Comment by hackintoshrao** [comment]
@harshavardhana : Yes, That'll be the best way to do it !

**Comment by hackintoshrao** [comment]
The test is holding after the changes in https://github.com/minio/minio/pull/3221. Will again run the other tests and validate them.

**Comment by hackintoshrao** [comment]
- Last time when the issue was witnessed all the node failed to restart. 
- But with the latest master at only 1 node (`node2`) failed with the error below, 
  
  ``` sh
  time="2016-11-14T07:40:09Z" level=fatal msg="Unable to load all bucket policies." cause="Bucket not found: whexylf6qlhh40nmpn5maloykagm . 
  ```
- It has become difficult to reproduce this, had to run the `exec-concurrent TestMakeBucketError` at a concurrency of 50, tens of times (while chaos test is going on) to reproduce. 
- Around like 10th run of the test of one one of the `exec-concurrent` test failed (50 was the concurrency level, so only 1 out of 50 failed)  with following error, 
  
  ``` sh
  
  Goroutine: 21
  --- FAIL: TestMakeBucketError (0.01s)
      api_functional_v4_test.go:92: Error: Your previous request to create the named bucket succeeded and you already own it. ud5tjjk61152vdx1tsn1bs33yggzz9
  FAIL
  ```
- After this happened 1 of the 7 nodes under chaos test failed to restart.

**Comment by harshavardhana** [comment]
> time="2016-11-14T07:40:09Z" level=fatal msg="Unable to load all bucket policies." cause="Bucket not found: whexylf6qlhh40nmpn5maloykagm .

Do you still have the setup handy - want to look at the node where "Unable to load all bucket policies" happen?

**Comment by hackintoshrao** [comment]
Yes. When I ran at a concurrency of 100, node4 failed failed. Its still down and you could see the log.
