### ISSUE TITLE
tests: add a hook for tests to restore global variables to defaults

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3198]
Currently the test cases modify the global variables. There is a good chance that test cases modify the global variables and affect other test cases. So far we have fixed this behavior by restoring the global variable  at the beginning of the test cases which gets affected. Easier way is to see if testing framework provides a hook that gets called before every test, so we can set global variables to their defaults when the hook is run.

**Comment by hackintoshrao** [comment]
timeline - 10th November.

**Comment by hackintoshrao** [comment]
In progress.

**Comment by GarimaKapoor** [comment]
@hackintoshrao can you update on the status of this fix.

**Comment by hackintoshrao** [comment]
Will be fixed today.

**Comment by hackintoshrao** [comment]
Couldn't proceed, finishing the tests and reporting the issues. Will finish this weekend.

**Comment by harshavardhana** [comment]
> Couldn't proceed, finishing the tests and reporting the issues. Will finish this weekend.

ping @hackintoshrao are you still working on this?

**Comment by hackintoshrao** [comment]
Yes, will continue on this in couple of days.

**Comment by GarimaKapoor** [comment]
@hackintoshrao any updates on this?

**Comment by hackintoshrao** [comment]
Working on this currently ....

**Comment by krishnasrinivas** [comment]
@hackintoshrao is there a way to trigger resetTestGlobals before each test automatically? like a pre-hook?

**Comment by hackintoshrao** [comment]
@krishnasrinivas : There's no facility to trigger this as a hook before every hook, may be we could have a wrapper and use it for calling the actual tests. Collecting all the globals and resetting them in this PR. Should finish it in couple of days.

**Comment by harshavardhana** [comment]
ping @hackintoshrao - any progress on this?

**Comment by hackintoshrao** [comment]
The function to reset globals variables is added, need to add reset few more variables in it. Will add them by 5th Jan.

**Comment by hackintoshrao** [comment]
Working on it currently.

**Comment by hackintoshrao** [comment]
@krisis  @harshavardhana : Since the mutex to be held on the `globalNsLock` is one of the fileds of the struct, I don't find a way to set `globalNSLock` to `nil` atomically. That would be possible if the mutex lock lives outside the struct, and that would complicate the usage of entire lock usage.

```go
// reset global NSLock.
func resetGlobalNSLock() {
        if globalNSMutex != nil {
        // this is not possible. But Lock is essential for safe implementation.
              globalNSMutex.Lock()
              defer globalNSMutex.Unlock()
              globalNSMutex = nil
        }
}       
```

Is it ok to go ahead with `unsafe` modification of the globalNsMutex considering that tests are not parallel for now?

**Comment by krisis** [comment]
@hackintoshrao you could use [atomic.CompareAndSwapPointer](https://golang.org/pkg/sync/atomic/#CompareAndSwapPointer) to atomically reset ``globalNSMutex``.

**Comment by hackintoshrao** [comment]
Thanks @krisis .

**Comment by krishnasrinivas** [comment]
But you don't need to hold any locks while resetting the global variables because no one else will be accessing these variables during this phase

**Comment by hackintoshrao** [comment]
Just to avoid a racy usage of the function in future.

**Comment by krishnasrinivas** [comment]
btw you can't use  atomic.CompareAndSwapPointer as it will be bypassing garbage collector.

> Just to avoid a racy usage of the function in future.

Can you give an example of such use? because if something is accessing the global vars when resetTestGlobals() is called then such a situation should be considered as a bug and fixed such that it does not happen.

**Comment by hackintoshrao** [comment]
> But you don't need to hold any locks while resetting the global variables because no one else will be accessing these variables during this phase

@krishnasrinivas , I agree with the above thought, because of the way its used, there's no need for a lock.
