### ISSUE TITLE
[distributed] Canceling an on-going upload doesn't clean tmp file during multipart upload

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3199]
In https://github.com/minio/minio/blob/master/cmd/xl-v1-multipart.go#L425, `xl.deleteObjects()` wants to clean .minio.sys/tmp/tmp-object/*, however currently tmp-objet is a file and not a directory.

**Comment by harshavardhana** [comment]
This is the same bug as before, do we need to duplicate this?

**Comment by vadmeste** [comment]
you mean this https://github.com/minio/minio/issues/3168 ?

**Comment by harshavardhana** [comment]
> you mean this #3168 ?

Yes seems its not just about disks going down.

**Comment by GarimaKapoor** [comment]
@vadmeste can you update the status of the fix. PR mentions rebase, what else is pending on this.
