### ISSUE TITLE
[browser] Event notification is not triggered for object deleted from UI

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3201]
## Expected Behavior
Event notification should be triggered. 

## Current Behavior
Event notification for RemoveObject is not triggered. 

## Possible Solution
Implement `eventNotifiy()` function in web-handlers.go

## Steps to Reproduce (for bugs)

1. mc watch play/testbucket
2. delete an object from UI
3. no notification objects
4. copy an object - a new notification is seen on console.

## Your Environment
Latest master.

**Comment by GarimaKapoor** [comment]
@balamurugana please update the status of this issue
