### ISSUE TITLE
[distributed] replace disk, bucket heal does not happen in one situation

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3206]
## Steps to Reproduce (for bugs)
* start 2:2 dXL
* bring down 4th server
* replace disk of 4th server (rm -rf and mkdir)
* bring up 4th server
* heal the disk:
```
krishna@escape:~$ minio control heal http://localhost:9004/
krishna@escape:~$ ls /export/disk4/ -a
.  ..  .minio.sys
krishna@escape:~$ 
```
* heal the bucket:
```
krishna@escape:~$ minio control heal http://localhost:9004/test

krishna@escape:~$ ls /export/disk4/ -a
.  ..  .minio.sys
krishna@escape:~$
```

Bucket is not healed. But it heals if healing is pointed towards localhost:9001/9002/9003

**Comment by harshavardhana** [comment]
This is the same as other two bugs not reproducible. @krishnasrinivas

**Comment by harshavardhana** [comment]
> This is the same as other two bugs not reproducible. @krishnasrinivas

This is reproducible.
