### ISSUE TITLE
No response and not quit when use mc policy download ly/test2 in linux ?

### ISSUE THREAD

**Issue by JackTiger** [minio/minio#3210]
I have find a problem in the latest mc command client, When I use mc policy command to change the policy, like this : mc policy download ly/test2, the console has nothing output and can not be quit. But the policy has been set in bucket, In last version, I have not find this problem, maybe it is related to my local agent, I use the internal proxy server in linux.

My command is like this 

```
root@SZV1000050161:/tmp/compose# mc --debug policy download ly/test2 
mc: <DEBUG> GET /test2/?location= HTTP/1.1
Host: 10.120.200.176:9000
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/2016-10-07T01:56:22Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20161109/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161109T003626Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: text/xml; charset=utf-8
Date: Wed, 09 Nov 2016 00:36:26 GMT
Proxy-Connection: keep-alive
Server: Minio/DEVELOPMENT.2016-11-08T00-03-00Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: FMNVKDB50LDERH3E

mc: <DEBUG> Response Time:  73.346695ms

mc: <DEBUG> GET /test2/?policy= HTTP/1.1
Host: 10.120.200.176:9000
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/2016-10-07T01:56:22Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20161109/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161109T003626Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 292
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Wed, 09 Nov 2016 00:36:26 GMT
Proxy-Connection: keep-alive
Vary: Origin

mc: <DEBUG> Response Time:  2.286525ms
```

By the way, in latest mc version, I find the progress bar is not updated when I upload the file to the mirror, and the command can not quite, but the file has been upload successfully.

**Comment by vadmeste** [comment]
@JackTiger, can you tell us how did you configure your internal proxy ? Also did you set the proxy url in your environment ? you need to set this variable in your shell before running mc

`export HTTP_PROXY="http://username:password@proxyIp:proxyPort"`

**Comment by harshavardhana** [comment]
> @JackTiger, can you tell us how did you configure your internal proxy ? Also did you set the proxy url in your environment ? you need to set this variable in your shell before running mc
> 
> export HTTP_PROXY="http://username:password@proxyIp:proxyPort"

@vadmeste @JackTiger is using - http://cntlm.sourceforge.net/ proxy.

**Comment by harshavardhana** [comment]
Under our testing nginx, caddy and traefik proxy works fine - @JackTiger closing this issue.
