### ISSUE TITLE
Single-part upload using pre-signed url failed with response status 400

### ISSUE THREAD

**Issue by henryzzhang** [minio/minio#3217]
Attempt to upload a small file to a pre-signed failed with http response status 400.

## Expected Behavior

Uploading a small file (<5 MB, so no multi-part upload was used) to a bucket using a pre-signed url should succeed.  Because it works with aws S3.

## Current Behavior

It doesn't work with minio server.

## Possible Solution

For single-part upload, there is no upload ID.  So minio server should just save the file into the specified bucket. 

## Steps to Reproduce (for bugs)

1. Generate a request using s3 api S3.PutObjectRequest
2. Get a pre-signed url using s3 api Request.Presign
3. Send the file to the pre-signed url using http PUT
4. Now you will get http response with status 400

## Context

For small files, we don't use multi-part upload, which is intended for big files.

## Your Environment

* Version used:
We build minio server from source code downloaded on 11/09/2016 using go get -u github.com/minio/minio

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
minio server, no SSL, 

* Operating System and version:
Ubuntu 16.04

* Link to your project:

**Comment by harshavardhana** [comment]
> Environment name and version (e.g. nginx 1.9.1):

Can you try without using nginx @henryzzhang ?  also can you also paste your nginx configuration?

**Comment by henryzzhang** [comment]
I was not using nginx.  The 400 error even happens when my client code and
the minio server run in the same box.

**Comment by harshavardhana** [comment]
> I was not using nginx.  The 400 error even happens when my client code and
> the minio server run in the same box.

Okay cool. Can you paste the same code that you have?

**Comment by harshavardhana** [comment]
Just used the latest master with the following code seems to be working fine .. 

### Generate presign URL.

``` go
package main

import (
    "fmt"
    "time"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/credentials"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
)

func main() {
    creds := credentials.NewStaticCredentials("USWUXHGYZQYFYFFIT3RE", "MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03", "")
    newSession := session.New()
    s3Config := &aws.Config{
        Credentials:      creds,
        Endpoint:         aws.String("http://localhost:9000"),
        Region:           aws.String("us-east-1"),
        DisableSSL:       aws.Bool(true),
        S3ForcePathStyle: aws.Bool(true),
    }
    // Create an S3 service object in the default region.
    s3Client := s3.New(newSession, s3Config)
    params := &s3.PutObjectInput{
        Bucket: aws.String("testbucket"),
        Key:    aws.String("object"),
    }
    req, _ := s3Client.PutObjectRequest(params)
    url, err := req.Presign(10 * time.Minute)
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println(url)
}
```

```
$ go run put-object-presign.go
http://localhost:9000/testbucket/object?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=USWUXHGYZQYFYFFIT3RE%2F20161109%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20161109T220321Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=7c7ab5971613209e6cab814f2045c8201f93698e14ed3b139af28e808b12b37e
```

### Upload file and verify.

```
$ curl -X PUT -T /etc/passwd "http://localhost:9000/testbucket/object?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=USWUXHGYZQYFYFFIT3RE%2F20161109%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20161109T220321Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=7c7ab5971613209e6cab814f2045c8201f93698e14ed3b139af28e808b12b37e" 
```

```
$ mc ls myminio/
[2016-11-09 06:03:41 PST]     0B testbucket/
$ mc ls myminio/testbucket/
[2016-11-07 20:22:40 PST] 8.8KiB examples.desktop
[2016-11-09 14:03:41 PST] 2.7KiB object
```

**Comment by henryzzhang** [comment]
My code is scattered in multiple places, so I don't have one that you can
use to test with.
My code to generate pre-signed url is similar to yours.  Do you see any
problem in my code to upload the data?  The error message returned from
minio is "There were headers present in the request which were not
signed".

Below are my code fragments and trace:

```
req, _ := s3.PutObjectRequest(&s3.PutObjectInput{
```

  Bucket: aws.String(bucket),
  Key:    aws.String(path),
 })

```
url := req.Presign(24 * time.Hour)
```

 req, err = http.NewRequest("PUT", url, bytes.NewReader(buffer))
 req.Header.Add("Content-Type", "application/octet-stream")
 log.Println("REQUEST PUT ", url)
 for k, v := range req.Header {
  log.Printf("%v: %v", k, v)
 }

 resp, err = http.DefaultClient.Do(req)
 if err != nil {
  panic(err)
 }
 body, err = ioutil.ReadAll(resp.Body)
 resp.Body.Close()
 if err != nil {
  panic(err)
 }
 log.Println("AMZ RESPONSE")
 for k, v := range resp.Header {
  log.Printf("%v: %v", k, v)
 }
 log.Printf("\n%v", string(body))

14:10:41.227647 main.go:177: REQUEST PUT
http://localhost:9000/telemetry-dev-attachment/e185d07a-0e34-4c5e-a22f-a97239a84df2/2016/11/09/2016110922-local-oy9LeJqt02Ma3XKBRxDHCX8nqlqjujUi.attach?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=9336Q56R1IQDIO97G9XY%2F20161109%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20161109T221041Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=1df0502f97acbb165a2c788553196f8bc494cfaa6117561d1ac030d3d69e90af
14:10:41.227686 main.go:179: Content-Type: [application/octet-stream]
14:10:41.241943 main.go:186: RESPONSE status  400 Bad Request
14:10:41.242073 main.go:192: AMZ RESPONSE
14:10:41.242111 main.go:194: Vary: [Origin]
14:10:41.242122 main.go:194: X-Amz-Request-Id: [1EI32LK9CY8GFY8B]
14:10:41.242132 main.go:194: Date: [Wed, 09 Nov 2016 22:10:41 GMT]
14:10:41.242141 main.go:194: Content-Type: [text/xml; charset=utf-8]
14:10:41.242151 main.go:194: Accept-Ranges: [bytes]
14:10:41.242160 main.go:194: Server: [Minio/DEVELOPMENT.GOGET (linux;
amd64)]
14:10:41.242170 main.go:196:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>There were headers present in the
request which were not
signed</Message><Key></Key><BucketName></BucketName><Resource>/telemetry-dev-attachment/e185d07a-0e34-4c5e-a22f-a97239a84df2/2016/11/09/2016110922-local-oy9LeJqt02Ma3XKBRxDHCX8nqlqjujUi.attach</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>

**Comment by harshavardhana** [comment]
> req.Header.Add("Content-Type", "application/octet-stream")

You cannot set this outside of the request itself. you have to make sure to pass this information during PutObjectInput{} then it will work.

**Comment by harshavardhana** [comment]
Let me give you a working version.

**Comment by henryzzhang** [comment]
But my code works fine with aws s3.  minio and s3 should be compatible,
right?

I did try to remove it, but still got the same error.  Can you try to use
go code client to do the upload to see if you get the same error on your
side?

**Comment by henryzzhang** [comment]
BTW, for multi-part upload, I don't get such error with the added custom
headers when I upload chunks to the pre-signed urls.

**Comment by harshavardhana** [comment]
> But my code works fine with aws s3.  minio and s3 should be compatible,
> right?
> 
> I did try to remove it, but still got the same error.  Can you try to use
> go code client to do the upload to see if you get the same error on your
> side?

You are right looks like the current code trying to look for only a single header i.e "host" . In this case it can have multiple signed headers.

Sent a fix already. at #3222

**Comment by henryzzhang** [comment]
After your fix, am I allowed to add new headers that were not in the
pre-signed url?
When can I get the fix using go get -u github.com/minio/minio?

**Comment by harshavardhana** [comment]
> After your fix, am I allowed to add new headers that were not in the
> pre-signed url?
> When can I get the fix using go get -u github.com/minio/minio?

Yes you can @henryzzhang
