### ISSUE TITLE
Multi-part upload completion ETag in response not enclosed by ""

### ISSUE THREAD

**Issue by henryzzhang** [minio/minio#3224]
As they did in aws s3, the returned ETag is always enclosed by double quotes.  In minio, the ETag from individual chunk upload is enclosed by "", but the ETag from the multi-part completion is NOT.  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by henryzzhang** [comment]
I just tested with the latest minio (built from source code).  The CompleteMultipartUpload ETag value is still not enclosed by "".  It should look like "\"c636647010481c1deeba83b353625946\""

**Comment by harshavardhana** [comment]
> I just tested with the latest minio (built from source code). The CompleteMultipartUpload ETag value is still not enclosed by "". It should look like ""c636647010481c1deeba83b353625946""

That is incorrect S3 replies with double quotes only, there are no double double quotes. 

```
mc: <DEBUG> PUT /issue HTTP/1.1
Host: andoria.s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/2.0.2 mc/DEVELOPMENT.GOGET
Content-Length: 26
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161202/us-east-1/s3/aws4_request, SignedHeaders=content-md5;expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: HnZyy8L3bD6dqtDikOcRuQ==
Content-Type: application/octet-stream
Expect: 100-continue
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20161202T222319Z
Accept-Encoding: gzip

mc: <DEBUG> Content-Length: 0
Date: Fri, 02 Dec 2016 22:23:21 GMT
Etag: "1e7672cbc2f76c3e9daad0e290e711b9"
Server: AmazonS3
X-Amz-Id-2: maXgq+cBddjDQlxcFvLeCP4+IkWbWVu7CgtBSTLDUgWrdolCwd9aDeWm5GpB72d4jdrMoiPsGQg=
X-Amz-Request-Id: 7A2178F0460B72AE
```

**Comment by henryzzhang** [comment]
I meant double quotes.  The Etag from CompleteMultipartUpload returns no
quote at all.  The issue is with CompleteMultipartUpload only.

**Comment by harshavardhana** [comment]
> I meant double quotes.  The Etag from CompleteMultipartUpload returns no
> quote at all.  The issue is with CompleteMultipartUpload only.

It does 

```
mc: <DEBUG> POST /testbucket/test1?uploadId=0bf6eab2-68d8-4349-9574-1da74352f9a0 HTTP/1.1
Host: 10.1.10.162:9000
User-Agent: Minio (linux; amd64) minio-go/2.0.2 mc/2016-12-03T00:47:48Z
Content-Length: 363
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161203/us-west-2/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: 26e535dbc37b162980325de1f5c2ee4f98b901f09a14b6cc06d57edad5102da6
X-Amz-Date: 20161203T015505Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8
Date: Sat, 03 Dec 2016 01:55:05 GMT
Etag: "f11858b474861d13a78f394c9f2e4d66-2"
Vary: Origin

mc: <DEBUG> Response Time:  201.571462ms

bigfile:                   100.00 MB / 100.00 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 83.93 MB/s 1s
```

which version of minio are you using @henryzzhang ?

**Comment by henryzzhang** [comment]
I pull the latest source code and built it only a couple of days ago.

**Comment by harshavardhana** [comment]
> I pull the latest source code and built it only a couple of days ago.

Can you paste the debug output or http trace? - also provide a sample program if you can?
