### ISSUE TITLE
erasure: To read we need n/2, for server to come up we need n/2 + 1

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3233]
For GetObject to succeed we need just n/2 disks online. But for server init to succeed it needs n/2 + 1.

i.e let's say n/2 servers are running and the cluster is operational for reads. At this point if a server is restarted then it will never come back up and prints:
`Initializing data volume. Waiting for minimum 3 servers to come online.` when n is 4.

**Comment by harshavardhana** [comment]
This is not needed anymore we only need n/2 for servers to come up after volume has initialized.

**Comment by krishnasrinivas** [comment]
@harshavardhana this situation is rare, i.e when n/2 disks are totally gone, we had moved a similar issue from distributed release last week.

**Comment by harshavardhana** [comment]
> @harshavardhana this situation is rare, i.e when n/2 disks are totally gone, we had moved a similar issue from distributed release last week.

Meaning we don't need to do this for this release?

**Comment by krishnasrinivas** [comment]
> Meaning we don't need to do this for this release?

yes

**Comment by GarimaKapoor** [comment]
cc @abperiasamy

**Comment by deekoder** [comment]
We need to discuss and finalize where we stand on these.

**Comment by deekoder** [comment]
Duplicate of #3234

**Comment by krishnasrinivas** [comment]
Duplicate of #3234. Closing.
