### ISSUE TITLE
erasure: Replace n/2 disks, new servers do not come up

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3234]
## Steps to Reproduce (for bugs)
1. run 2:2 DXL
2. bring down minio3 and minio4 (i.e 3rd and 4th server)
3. rm -rf /export/disk{3..4} (i.e remove the down servers disks)
4. mkdir /export/disk{3..4}
5. start minio3 and minio4

minio 3 and 4 does not come up and prints eternally:
`Initializing data volume. Waiting for minimum 3 servers to come online.`

**Comment by harshavardhana** [comment]
The bug here #3233 - both are related if we fix one fixes the other.

**Comment by deekoder** [comment]
Need to finalize on where we stand on this. Let's discuss.

**Comment by deekoder** [comment]
Minio Server should start in read-only mode.
