### ISSUE TITLE
[distribute] high CPU usage during server boot

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3235]
This issue might be related to https://github.com/minio/minio/issues/3232

1. start 3:3 DXL
i.e 6 x `minio server --address localhost:9001 http://localhost:9001/export/disk1 http://localhost:9002/export/disk2 http://localhost:9003/export/disk3 http://localhost:9004/export/disk4 http://localhos
t:9005/export/disk5 http://localhost:9006/export/disk6`

2. Create a bucket

3. Ctrl-C all the minio servers

4. Bring all the minio servers back up at the same time. If using tmux use `synchronize-panes` feature to start the minio servers at the same time. (starting the servers at the same time is important, if it is started one after another then issue is not seen very often)

5. All minio processes goes into high CPU usage 70-90% and it takes around 2 minutes for the CPU usage to go down and for the cluster to be operational

Few servers are stuck at :
```
krishna@escape:~$ minio server --address localhost:9001 http://localhost:9001/export/disk1 http://localhost:9002/export/disk2 http://localhost:9003/export/disk3 http://localhost:9004/export/disk4 http://localhost:9005/export/disk5 http://localhost:9006/export/disk6

```

few servers are stuck at -
```
krishna@escape:~$ minio server --address localhost:9002 http://localhost:9001/export/disk1 http://localhost:9002/export/disk2 http://localhost:9003/export/disk3 http://localhost:9004/export/disk4 http://localhost:9005/export/disk5 http://localhost:9006/export/disk6

Initializing data volume.
[01/06] http://localhost:9001/export/disk1 - 38 GiB online
[02/06] http://localhost:9002/export/disk2 - 38 GiB online
[03/06] http://localhost:9003/export/disk3 - 38 GiB online
[04/06] http://localhost:9004/export/disk4 - 38 GiB online
[05/06] http://localhost:9005/export/disk5 - 38 GiB online
[06/06] http://localhost:9006/export/disk6 - 38 GiB online
```

**Comment by donatello** [comment]
This is reproducible with our 4-node docker-compose file as well. My laptop has all cores burning for about 20 seconds till it settles down and is working. It appears that a lot of messages are being exchanged at start up.

**Comment by harshavardhana** [comment]
> This is reproducible with our 4-node docker-compose file as well. My laptop has all cores burning for about 20 seconds till it settles down and is working. It appears that a lot of messages are being exchanged at start up.

Is this reproducible with latest master? @donatello - can you also try with the patch - https://github.com/minio/minio/pull/3238

**Comment by donatello** [comment]
Yes, on master, on my laptop, with 4 node docker-compose, it takes around ~14-18 seconds for all 4 servers to finish printing their start-up messages. 50-100% cpu usage on all cores on my laptop during this time. 

Will try with #3238 (but see my comment on it - it is not exactly preventing a race to login).

**Comment by donatello** [comment]
It seems a bit better but not too significantly - it takes about ~12-14 seconds with the change (in each of about 10 manual tests), but there was one test that took about 30s. 

The test I am doing is to note the start time, start the docker-compose cluster, wait for all start-up messages from each server, and then note the time and see the time taken.

**Comment by donatello** [comment]
With the latest version of #3238 (where allow only one login attempt at a time is allowed via locking), cpu usage is significantly lesser and the cluster is ready in about 6-12s.

Request @krishnasrinivas and @hackintoshrao to independently confirm.

**Comment by hackintoshrao** [comment]
The CPU usage is still high, Here are some of the screenshots of CPU usage over a course of time when only 3 out of 8 node were started.

The CPU usage gradually builds up. 
- At 40% 
  <img width="1204" alt="screen shot 2016-11-11 at 2 53 57 pm" src="https://cloud.githubusercontent.com/assets/2609511/20210783/3f5b2dcc-a821-11e6-96af-e940104c1506.png">
- At 73%
  <img width="1277" alt="screen shot 2016-11-11 at 3 01 11 pm" src="https://cloud.githubusercontent.com/assets/2609511/20210820/693fb8c4-a821-11e6-92ff-db40d1142726.png">
- At over 280%
  <img width="1135" alt="screen shot 2016-11-11 at 3 04 37 pm" src="https://cloud.githubusercontent.com/assets/2609511/20210836/74f9cbc8-a821-11e6-8ef3-16457b96109e.png">
- It grows beyond 300%.

**Comment by harshavardhana** [comment]
@hackintoshrao did you have a lot of temporary files?  - servers might be cleaning them up.  You should test the patch itself on a cleaner backend with only involving startup sequences. 

There will be some amount of CPU usage we just have to see if the usage is sustained and unwarranted.

**Comment by hackintoshrao** [comment]
Ok. Will test with a clean setup.

**Comment by krishnasrinivas** [comment]
For my setup CPU usage problem is fixed, it hardly takes any time now for peer discovery and the cluster to be operational.

**Comment by harshavardhana** [comment]
> For my setup CPU usage problem is fixed, it hardly takes any time now for peer discovery and the cluster to be operational.

Closing based on new testing. Will re-open again if seen.
