### ISSUE TITLE
[distributed] HealObject() tries to heal when one of the servers is down

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3237]
## Expected Behavior
HealObject() should return immediately as there is nothing to heal.

## Current Behavior
ListHealObject() tries to heal the object thinking that the object in the down server is outdated.

## Steps to Reproduce (for bugs)
1. start 3:3 dxl
3. Upload a `bucket/object`
2. Bring down 6th server
3. Exec heal command on the bucket: (this takes up CPU healing the object)

```
krishna@escape:~$ MINIO_ACCESS_KEY=SXO8VW2OFKKP2OG7AC85 MINIO_SECRET_KEY=CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 minio control heal http://localhost:9005/testbucket
[0] ◐ SUCCESS  5g                                                                                                    
krishna@escape:~$ 
```

It actually tried to heal the object and said success.

Fix:
ListObjectsHeal() should not have returned the object
HealObject() should not try to heal the object (xlShouldHeal should return false)

**Comment by harshavardhana** [comment]
@krishnasrinivas does this actually try to do any i/o ? or is it that it proceeds forward?

**Comment by harshavardhana** [comment]
> @krishnasrinivas does this actually try to do any i/o ? or is it that it proceeds forward?

@krishnasrinivas does this try to create the part of the object?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas does this actually try to do any i/o ? or is it that it proceeds forward?
> @krishnasrinivas does this try to create the part of the object?

@harshavardhana I noticed high CPU usage for quite sometime, I am sure it is reading from disk reconstructing the missing data and tries to write to the server which is down.

**Comment by harshavardhana** [comment]
> @harshavardhana I noticed high CPU usage for quite sometime, I am sure it is reading from disk reconstructing the missing data and tries to write to the server which is down.

Okay ..cool

**Comment by harshavardhana** [comment]
This feature will be worked on post distributed release when we bring in `mc admin heal` command
