### ISSUE TITLE
[security] minio browser login involves sending unencrypted credentials over the wire

### ISSUE THREAD

**Issue by donatello** [minio/minio#3259]
This is insecure without https and needs to be fixed using a signature v4 style payload generated for initial handshake.

**Comment by harshavardhana** [comment]
Taking this.

**Comment by krishnasrinivas** [comment]
JWT can be generated on the client side itself and this JWT can be verified in the "Login" step.

But "change secretkey" process will still happen unencrypted.

**Comment by vadmeste** [comment]
> JWT can be generated on the client side itself and this JWT can be verified in the "Login" step.
> 
> But "change secretkey" process will still happen unencrypted.

Looks like JWT supports payload encryption too:
https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-encryption

However, we added TLS to help the user to secure his data + username/password. I don't think this is high priority.

**Comment by krishnasrinivas** [comment]
> Looks like JWT supports payload encryption too:
> https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-encryption

Oh, right, JWT already does encryption.

**Comment by harshavardhana** [comment]
You are right changing secret key has the same problem where in server cannot validate it.  Removing this as part of milestone.

> Looks like JWT supports payload encryption too:
> https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-encryption

Payload like this would require public/privatekey our UI doesn't cater for this, in-fact TLS would do something similar.
