### ISSUE TITLE
[distributed] Too many go routines running even at less load.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3260]
- This was witnessed when the binary was build with `-race` flag.
- When the binary was built with `-race` flag the server stops after the number of go routines running exceeds 8192, thats a hard limit.
- The hard limit was reached when the server was bomabarded with load which was as small as 5 concurrent make buckets. 
- Will evaluate this deeper during the currently running tests.

**Comment by hackintoshrao** [comment]
Will be using the snippet [here](https://play.golang.org/p/MRAsYRoWUk) to first evaluate the count of go routines increased after each operation.

**Comment by hackintoshrao** [comment]
- Have set up an endpoint inside the server which returns the number of Go routines running in the system.
- Will call that end point ( `/minio/debug/goroutines` ) from the my load tests before the load is bombarded and then after the test and will observe the increase in the number of go routines running, that should help us know if there are many go routines left behind.

**Comment by donatello** [comment]
> When the binary was built with -race flag the server stops after the number of go routines running exceeds 8192, thats a hard limit.

What kind of crash is this? If there are 8192+ go routines the program panics when built with `-race` flag?

**Comment by hackintoshrao** [comment]
The program doesn't panic. It just halts execution with a msg that 8192 limit reached. All connections will be reset .

**Comment by harshavardhana** [comment]
> The program doesn't panic. It just halts execution with a msg that 8192 limit reached. All connections will be reset .

This is an internal Go limit i think in 1.7.x series. Can you paste the code and concurrency level here?

**Comment by hackintoshrao** [comment]
The first 2 tests of exec-concurrrent tests with the concurrency of 10 on the binary built with `-race` produces it. Will have more details on whether there are significant leaks today.

**Comment by hackintoshrao** [comment]
Here's an interesting result. 
- When load test run without chaos test ,`time ./exec-concurrent TestMakeBucketError` at a Concurrency of 300 the number of go routines in the node remains constant before and after the load test. Remains at 29. 
- This holds good consistently. 
- But when the node are under chaos test the number of go routines in the system before and after the test steadily increase for each run of the load test.  the number of go routines in the system increase over 100.
- And with more repetition of the load test (while nodes are subjected to chaos test) the numbers keep climbing.
- the number remains high even after the nodes stabilize. 
- But clearly not able to understand why the binary build with `-race` reached the limit 8192 so fast, the system doesn't seem to have those many go routines running.

**Comment by harshavardhana** [comment]
> When load test run without chaos test ,time ./exec-concurrent TestMakeBucketError at a Concurrency of 300 the number of go routines in the node remains constant before and after the load test. Remains at 29.
> This holds good consistently.
> But when the node are under chaos test the number of go routines in the system before and after the test steadily increase for each run of the load test. the number of go routines in the system increase over 100.
> And with more repetition of the load test (while nodes are subjected to chaos test) the numbers keep climbing.
> the number remains high even after the nodes stabilize.
> 
> But clearly not able to understand why the binary build with -race reached the limit 8192 so fast, the system doesn't seem to have those many go routines running.

We should capture stack-trace like we did with #3274 - to confirm the go-routine leak is same. If yes then we can close this as duplicate bug of #3274

**Comment by hackintoshrao** [comment]
Opening issues for specific tests. closing this.
