### ISSUE TITLE
tests: Make API handler tests concurrent for race detection.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3261]
- Currently when the binary is built with `-race` flag to catch potential races during load test, the hard limit of 8192 is reached too soon (see https://github.com/minio/minio/issues/3260). 
- Due to this currently not able to detect potential races with concurrent load. 
- Need to introduce concurrent calling of handler inside `API Handler tests` to detect potential races inside the handlers during concurrent calls.
- Since tests can run with `-race` flag this would introduce a layer of detection and safety against possible races.
- Will test this.

**Comment by harshavardhana** [comment]
This is not a blocked for Distributed, moving this out.

**Comment by harshavardhana** [comment]
ping @hackintoshrao

**Comment by hackintoshrao** [comment]
I believe it'll still be useful to implement this. Let me know if I could proceed.

**Comment by deekoder** [comment]
needs to be discussed and prioritized further.

**Comment by deekoder** [comment]
Keeping it high pri since APIs do need to be tested for race conditions. All API maintainers need to chime in.

**Comment by deekoder** [comment]
ETA Apr 12th

**Comment by hackintoshrao** [comment]
This will be a overhead on the CI to run lot of concurrent tests on the API handler for race detection. Race detection test will introduced in Mint, wherein the binary has to be built with `-race` flag and run the test to catch potential races in the binary. This can be tracked here https://github.com/minio/mint/issues/11 .
