### ISSUE TITLE
tests: Improve tests to avoid using repeated setup and teardown code.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#3270]
Currently test functions use repeated setup and tear down code.

For example,
* testAPIHeadObjectHandler() and testAPIGetObjectHandler() do put object setup to run the actual tests.
* Repeated below code at the end.
```
	// HTTP request for testing when `objectLayer` is set to `nil`.
	// There is no need to use an existing bucket and valid input for creating the request
	// since the `objectLayer==nil`  check is performed before any other checks inside the handlers.
	// The only aim is to generate an HTTP request in a way that the relevant/registered end point is evoked/called.

	nilBucket := "dummy-bucket"
	nilObject := "dummy-object"
	nilReq, err := newTestSignedRequestV4("GET", getGetObjectURL("", nilBucket, nilObject),
		0, nil, "", "")

	if err != nil {
		t.Errorf("Minio %s: Failed to create HTTP request for testing the response when object Layer is set to `nil`.", instanceType)
	}
	// execute the object layer set to `nil` test.
	// `ExecObjectLayerAPINilTest` manages the operation.
	ExecObjectLayerAPINilTest(t, nilBucket, nilObject, instanceType, apiRouter, nilReq)
```

This style of implementation can be improved by having separate reusable setup and teardown code wherever applicable.

**Comment by harshavardhana** [comment]
> This style of implementation can be improved by having separate reusable setup and teardown code wherever applicable.

Agreed this needs to be done @hackintoshrao pointed it out earlier and is aware of it.

**Comment by hackintoshrao** [comment]
There are few things to be considered here and should evaluate this further, 
- The primary reason to not have a shared initial setup is to make sure that the unit tests truly run in isolation, its good to create new backend for every unit test since we know that the unit test is not influenced by any possible changes to the backend by other unit tests.
- About the repeated code here,
  
  > nilBucket := "dummy-bucket"
  > nilObject := "dummy-object"
  > nilReq, err := newTestSignedRequestV4("GET", getGetObjectURL("", nilBucket, nilObject),
  >     0, nil, "", "")

The signed HTTP request is usually different for different functionalities, that's the reason why HTTP requests are hand crafted everytime. 
- Will evaluate further on what are the other ways with it could be simplified.

**Comment by balamurugana** [comment]
@hackintoshrao 

> The signed HTTP request is usually different for different functionalities, that's the reason why HTTP requests are hand crafted everytime.

Yes.  That is helper snippet if anything repeating in tail of the function code.

**Comment by GarimaKapoor** [comment]
@harshavardhana these tests were done before the release, is this still relevant?

**Comment by harshavardhana** [comment]
> The primary reason to not have a shared initial setup is to make sure that the unit tests truly run in isolation, its good to create new backend for every unit test since we know that the unit test is not influenced by any possible changes to the backend by other unit tests.

The current style tests to be run across specific directories for each is good enough and correct to varied use cases
