### ISSUE TITLE
[distributed]  `exec-concurrent TestPutObjectReadAt` test hangs with leaked go routines.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3274]
- `exec-concurrent TestPutObjectReadAt` test hangs on the distributed setup.
- Witnessed a severe Go routine leakage (Closely related to https://github.com/minio/minio/issues/3260)
## Expected Behavior

- Test to pass.
- Not to leave behind too many Go routines in the system.
## Current Behavior

- Everytime the test is executed the test hangs.
- Test is ran at Concurrency of 1 (just one) . 
- The test hangs and if its stopped and re run the number of running Go routines in the system increases by close to 1000. 
- After several failed attempts of the tests the number of go routines in the system has increased to 73798  ! 
## Possible Solution

- Need to figure the reason for failure and such a big bump in number of go routines alive in the system.
- Not sure about the origin of the problem.
## Steps to Reproduce (for bugs)

1. Set up 8 node distributed Minio.
2. Run `exec-concurrent TestPutObjectReadAt` test. [Click here](https://github.com/minio/perftest/tree/master/exec-concurrent) for more info on exec-concurrent tests.

## Context

- exec-concurrent tests without chaos test running.
## Your Environment

* Version used: Master at 05dc52a206a47abd71aa1d81e5eb3053285f034a .

**Comment by hackintoshrao** [comment]
After 16 minutes of leaving the test ( which was hung) , the number of go routines alive in the system increased to 127031 .  More the time the hanged test is left as it is, higher the increase in number of go routines alive.

**Comment by harshavardhana** [comment]
How did you test the number of go-routines?

**Comment by harshavardhana** [comment]
We can also get runtime.Stack() output by setting the StackTraceback("all") to capture the leaking go-routines, this would help track down these issues quickly.

**Comment by hackintoshrao** [comment]
Using the snippet below to obtain the number of go routines in the system.

``` go
// Get the count of number of go routines alive in the system.
func CountGoRoutines() int {
        return runtime.NumGoroutine()
}

// Respond with the number of currently running GoRoutines in the system.
func  GetGoroutinesCountHandler(w http.ResponseWriter, r *http.Request) {
       // Get the count of number of go routines running.
        count := CountGoRoutines()
        setCommonHeaders(w)
        w.Write([]byte(strconv.Itoa(count)))
}
```

Calling the HTTP handler from the load test program (exec-concurrent) before and after bombarding the load.

**Comment by harshavardhana** [comment]
For now primarily go-routine leaks look like coming from dsync. 

```
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc426403c80, 0xc42641ad20, 0xc4204c4500, 0x8, 0x8, 0xc42f5ec280, 0x3d, 0xc42669907b, 0xc4266990a0, 0xc420457400)
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:247 +0x25f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:253 +0x200
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc42f642540, 0xc4203aa4c0, 0xc4204c4500, 0x8, 0x8, 0xc42001ba80, 0x3d, 0xc42f6496ea, 0xc42f649720, 0xc420457400)
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:247 +0x25f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:253 +0x200
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc42041d680, 0xc420372d20, 0xc4204c4500, 0x8, 0x8, 0xc42f64ac80, 0x3d, 0xc420275fde, 0xc426676060, 0xc420457400)
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:247 +0x25f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:253 +0x200
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc42f5fd0e0, 0xc4206d6e00, 0xc4204c4500, 0x8, 0x8, 0xc4204c1ec0, 0x3d, 0xc42027464a, 0xc420274980, 0xc420457400)
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:247 +0x25f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:253 +0x200
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc42041d920, 0xc420373280, 0xc4204c4500, 0x8, 0x8, 0xc4204c1ec0, 0x3d, 0xc4266760fa, 0xc426676110, 0xc420457400)
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:247 +0x25f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:253 +0x200
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc42658e420, 0xc426419320, 0xc4204c4500, 0x8, 0x8, 0xc42f5ec280, 0x3d, 0xc42663e81a, 0xc42663e830, 0xc420457400)
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:247 +0x25f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /root/work/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:253 +0x200
```

This generally coincides with what we are seeing through go-routine results.

```
$ grep dsync.lock /tmp/final-stack-trace.log  |grep 'created by' | wc -l
509
```

```
$ grep dsync.lock /tmp/1109-final-stack-trace.log  | grep 'created by' | wc -l
1081
```

**Comment by harshavardhana** [comment]
ping @krisis @fwessels - would love to get some inputs here..

**Comment by krisis** [comment]
@harshavardhana I shall look into it.

**Comment by fwessels** [comment]
Also on FS I have seen some weird drops in performance after a while, maybe go-routine/garbage collection related too, we need to look into this.

Perhaps we can use some "pools" of go-routines in a few place in the code in order to promote re-use of go-routines rather than continuously creating new routines.

**Comment by krisis** [comment]
I am unable to recreate the issue with `4a926d1` on master branch using the steps to reproduce provided in the issue description. I am using a 8 node distributed setup using docker-compose.

**Comment by hackintoshrao** [comment]
I have a 8node packet setup, will help you replicate.

**Comment by hackintoshrao** [comment]
Same issue is seen while running `exec-concurrent TestResumablePutObject` at an concurrency of 5, but the leakage is more explosive  here.

**Comment by hackintoshrao** [comment]
Similar issue originating originating from the same source during `time ./exec-concurrent TestResumableFPutObject` at a concurrency of 3.

**Comment by hackintoshrao** [comment]
- Again, Same issue originating from same source during `time ./exec-concurrent TestFPutObjectMultipart` at a concurrency of 3. 
- Looks like the problem is occurring during any `PutObject` related operations.

**Comment by hackintoshrao** [comment]
- Same issue but reproduced in a very different way. 
- Bring 4 out of 8 nodes down permanently.
- run `time ./exec-concurrent TestGetObjectReadSeekFunctional`.
- It hangs.
- Bring one node up in like 2 minutes.
- The number of go routines in the system grew from 28 to 1548 just in 2 minutes and all of the originating from the same source as above.

**Comment by harshavardhana** [comment]
Fixed by #3308

**Comment by harshavardhana** [comment]
Reverted the fix for this change, re-opening the bug.

**Comment by krisis** [comment]
This issue was not reproducible with a fix (https://github.com/minio/dsync/pull/34) to dsync. @harshavardhana if the dsync fix is fine, we could vendor-in the changes.

**Comment by harshavardhana** [comment]
Send the vendor update patch.

**Comment by krisis** [comment]
@harshavardhana the vendor update patch would include reducing dsync requirements for node count to 2, which is still under discussion w.r.t minio server? How should we go about it?

**Comment by harshavardhana** [comment]
> @harshavardhana the vendor update patch would include reducing dsync requirements for node count to 2, which is still under discussion w.r.t minio server? How should we go about it?

Oh that patch should be reverted `dsync`.

**Comment by harshavardhana** [comment]
> @harshavardhana the vendor update patch would include reducing dsync requirements for node count to 2, which is still under discussion w.r.t minio server? How should we go about it?

Dsync is updated can you send a vendorized change for dsync?
