### ISSUE TITLE
As buckets increase there is a increasing delay in initialization.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3276]
- With growing number of buckets in the backend, the initialization time of the server increases.
## Expected Behavior

- Not to have too much delay in initialization when there are large number of buckets in the backend.
## Current Behavior

- The initialization time grows with number of buckets in the system.
- Witnessed it with @harshavardhana  during chaos tests. 

## Steps to Reproduce (for bugs)

1. Have the backend to demonstrate this. have large number of buckets.
2. Just use chaos test to restart all nodes in round robin fashion.

## Context

- Chaos tests.
## Your Environment

* Version used: latest master at 05dc52a206a47abd71aa1d81e5eb3053285f034a

**Comment by harshavardhana** [comment]
ping @hackintoshrao can we test this again? if you have the setup handy let me know. Otherwise whenever you are free ping me. 

We can see where does this slow down at what point by rapidly creating 1000's of buckets.

**Comment by hackintoshrao** [comment]
I still have the backend for this. Will test it, gimme couple of days, wrapping up with other tasks.

**Comment by GarimaKapoor** [comment]
@hackintoshrao any updates on this?

**Comment by hackintoshrao** [comment]
Should test with @harshavardhana . Will be doing it today.

**Comment by harshavardhana** [comment]
> Should test with @harshavardhana . Will be doing it today.

let me know when you are available.

**Comment by harshavardhana** [comment]
@hackintoshrao were you able to reproduce this again?

**Comment by hackintoshrao** [comment]
Not able to reproduce this, closing this.
