### ISSUE TITLE
[distributed] corrupted data when disk becomes full

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3278]
## Expected Behavior
Data are always sane

## Current Behavior
I can download a corrupted file without having mc returning an error

## Steps to Reproduce (for bugs)
1. Start from fresh disks.. but we need to have 2.3Gb remaining space
2. mc mb myminio/testbucket
3. mc cp 1gb.file myminio/testbucket/
4. mc cp 1gb.file myminio/testbucket/ (again)

It is normal if the second cp fails.. however mc cp didn't indicate any problem.. In addition, mc cat myminio/testbucket/1gb.file | md5sum will give an incorrect hash.

Minio prints some errors:
```
time="2016-11-18T14:09:15Z" level=error msg="Unable to create object part." cause="mkdir /export/minio3/.minio.sys/tmp/8994253a-3756-40c9-9d1f-1698680fe5a3: no space left on device" location="[object-handlers.go:691:objectAPIHandlers.PutObjectPartHandler()]" stack="xl-v1-utils.go:52:reduceErrs xl-v1-metadata.go:343:writeUniqueXLMetadata xl-v1-multipart.go:521:xlObjects.PutObjectPart <autogenerated>:854:(*xlObjects).PutObjectPart object-handlers.go:688:objectAPIHandlers.PutObjectPartHandler api-router.go:44:(objectAPIHandlers).PutObjectPartHandler-fm" 
time="2016-11-18T14:09:15Z" level=error msg="Unable to create object part." cause="mkdir /export/minio4/.minio.sys/tmp/3ef3aba5-d4d0-4137-919b-e6bdbad457b9: no space left on device" location="[object-handlers.go:691:objectAPIHandlers.PutObjectPartHandler()]" stack="xl-v1-utils.go:52:reduceErrs xl-v1-metadata.go:343:writeUniqueXLMetadata xl-v1-multipart.go:521:xlObjects.PutObjectPart <autogenerated>:854:(*xlObjects).PutObjectPart object-handlers.go:688:objectAPIHandlers.PutObjectPartHandler api-router.go:44:(objectAPIHandlers).PutObjectPartHandler-fm" 
time="2016-11-18T14:09:22Z" level=error msg="Unable to read part.14 of the object `testbucket/1gb.bin`." cause="Read failed. Insufficient number of disks online" location="[xl-v1-object.go:201:xlObjects.GetObject()]" stack="erasure-readfile.go:251:erasureReadFile xl-v1-object.go:199:xlObjects.GetObject /home/vadmeste/work/go/src/runtime/asm_amd64.s:2086:runtime.goexit" 
```

## Context
Testing

## Your Environment
All, commit-id 05dc52a206a47abd71aa1d81e5eb3053285f034a

**Comment by harshavardhana** [comment]
This requires healing. To return an error we have to validate if what we read from xl.json also is correct   i.e on disk. Currently the object would proceed to read and fail. But the client would receive a 200 OK.

**Comment by harshavardhana** [comment]
Taking this.

**Comment by krisis** [comment]
I am working on this. @harshavardhana, could you assign this to me.

**Comment by krisis** [comment]
This issue is not reproducible in commit-id ``5197649``. I confirmed this with @vadmeste, you may close the issue. We can reopen this if it is seen again.
