### ISSUE TITLE
[distributed] parallel multipart uploads of two different files makes the first file not able to reupload anymore

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3279]
## Expected Behavior
Re-uploading the same file again shouldn't fail

## Current Behavior
Cannot upload a file anymore with the same name

## Steps to Reproduce (for bugs)
1. 4 fresh disks
2. `mc mb myminio/testbucket/`
3. Two loops which upload the same file to different target names
`while true; do mc cp 70mb.bin myminio/testbucket/70mb.bin.1 ; done`
and
`while true; do mc cp 70mb.bin myminio/testbucket/70mb.bin.2 ; done`

## Context
Testing

## Your Environment
Ubuntu, commit id 05dc52a206a47abd71aa1d81e5eb3053285f034a

**Comment by vadmeste** [comment]
I am taking this

**Comment by vadmeste** [comment]
`posix: Rename err = rename /tmp/standalone-xl/minio4/.minio.sys/multipart/testbucket/70mb.bin.1/uploads.json /tmp/standalone-xl/minio4/.minio.sys/tmp/3a7f88dc-7107-47c3-
9201-e666c1152f12: no such file or directory`

This happens because tmp directory is removed after checking if it exists in posix.RenameFile() and before populating the tmp dir

I added a hacky code which forbids the remove tmp dir and the bug disappeared.

Fixing this bug https://github.com/minio/minio/issues/3281 will fix this one too.

**Comment by harshavardhana** [comment]
Is this fixed already? @vadmeste

**Comment by vadmeste** [comment]
> Is this fixed already? @vadmeste

yes, this is fixed with https://github.com/minio/minio/pull/3294

**Comment by harshavardhana** [comment]
> yes, this is fixed with #3294

Closing.
