### ISSUE TITLE
UI not encoding url resources

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3280]
- create a folder named "%s"
- clic on the ui
- you stay on the same folder and the url is /%s/

The url shoudl be /%25/ and the folder should change

**Comment by szepeviktor** [comment]
The URL should be `/%25s/`

**Comment by vadmeste** [comment]
I am taking this

**Comment by vadmeste** [comment]
This is fixed with https://github.com/minio/miniobrowser/pull/250

**Comment by harshavardhana** [comment]
> This is fixed with minio/miniobrowser#250

Closing..
