### ISSUE TITLE
reduceErrs should return maximally occurring error and its count

### ISSUE THREAD

**Issue by krisis** [minio/minio#3298]
[reduceErrs](https://github.com/minio/minio/blob/master/cmd/xl-v1-utils.go#L35) returns the error which occurs the most, filtering out ``ignoredErrs``. This is insufficient to know if the corresponding operation had the same result in quorum or more number of nodes.

## Expected Behavior

``reduceErrs`` should return maximally occurring error and its count
## Current Behavior

``reduceErrs`` returns the maximally occurring error. e.g, ``reduceErrs([]error{errFileNotFound, errFileNotFound, nil, nil}, nil}`` will return ``nil`` or ``errFileNotFound`` depending on the order in which the keys where inserted into the underlying map, which is used to count the number of occurrences of an error.

## Possible Solution

``reduceErrs`` should return the number of occurrences of the maximally occurring error.

## Steps to Reproduce (for bugs)

N/A

## Context

With ``reduceErrs`` returning an error (incl. ``nil``) which may not have quorum may cause data to diverge among disks in a erasure code backend.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment]
why should it return count? we are not using reduceErrs in case of quorum for that we have isDiskQuorum?

Also is this a blocker for the release @krisis ?

**Comment by krisis** [comment]
@harshavardhana isDiskQuorum only checks if quorum number of disks are operational. It doesn't indicate whether quorum or more number of disks/nodes are in agreement with the backend state. This is a blocker for the release.

**Comment by harshavardhana** [comment]
> @harshavardhana isDiskQuorum only checks if quorum number of disks are operational. It doesn't indicate whether quorum or more number of disks/nodes are in agreement with the backend state. This is a blocker for the release.

This is not a blocker - Can you provide a reproducible case for this? a sample program would be better or some scenario using chaos test.
