### ISSUE TITLE
urlib3 ssl error

### ISSUE THREAD

**Issue by elcolie** [minio/minio#3305]
urllib3 throws an error

## Expected Behavior
Not throw an 
```
urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)
```

## Current Behavior
It throws 
```
urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)
```

## Possible Solution
No found yet

## Steps to Reproduce (for bugs)

1. Install `django-storages`, `django-minio-storage`
1. Add 'storages' in the `INSTALLED_APPS`
1. Add variables as follows in Django config.py
```python
DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = "localhost:9000"
MINIO_STORAGE_ACCESS_KEY = "KBP6WXGPS387090EZMG8"
MINIO_STORAGE_SECRET_KEY = "DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A"
MINIO_STORAGE_USE_HTTPS = True
MINIO_STORAGE_MEDIA_BUCKET_NAME= "uihportal-media"
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET= True
MINIO_STORAGE_STATIC_BUCKET_NAME= "uihportal-static"
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET= True
```

## Context
Unable to run Django

## Your Environment
OSX 10.11.6
Django 1.9
django-storages==1.5.1
django-minio-storage==0.1.0
minio==2.0.2              # via django-minio-storage
python 3.5.1

Do we have workaround to fix this?
I had read the similar thread, but my knowledge is limited https://github.com/kennethreitz/requests/issues/3006
Then I could not understand it.

**Comment by krishnasrinivas** [comment]
> MINIO_STORAGE_USE_HTTPS = True

are you running minio on https? if not you have to make this value `False`

**Comment by elcolie** [comment]
@krishnasrinivas Good morning.
Yes. I want to run it on `https`
I had tried `concert`, but no luck
```
Sarits-MacBook-Air-2:Downloads el$ ./concert_darwin_amd64 gen --dir my-certs sarit.r@codium.co www.codium.co
2016/11/22 09:12:37 Failed to obtain certificates for Domains: [www.codium.co], with following errors [[www.codium.co] error presenting token: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied] respectively.
Sarits-MacBook-Air-2:Downloads el$ ./concert_darwin_amd64 gen --dir my-certs sarit.r@codium.co portal.uih.co.th
2016/11/22 09:13:07 Failed to obtain certificates for Domains: [portal.uih.co.th], with following errors [[portal.uih.co.th] error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied] respectively.
```

First one is my company website it has no `https` and later is customer website it has `https`

**Comment by harshavardhana** [comment]
> Sarits-MacBook-Air-2:Downloads el$ ./concert_darwin_amd64 gen --dir my-certs sarit.r@codium.co www.codium.co
> 2016/11/22 09:12:37 Failed to obtain certificates for Domains: [www.codium.co], with following errors [[www.codium.co] error presenting token: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied] respectively.
> Sarits-MacBook-Air-2:Downloads el$ ./concert_darwin_amd64 gen --dir my-certs sarit.r@codium.co portal.uih.co.th
> 2016/11/22 09:13:07 Failed to obtain certificates for Domains: [portal.uih.co.th], with following errors [[portal.uih.co.th] error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied] respectively.

You have to run 'concert' as root

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio - please follow this document use sudo as mentioned.

**Comment by elcolie** [comment]
```
Sarits-MacBook-Air-2:Downloads el$ sudo ./concert_darwin_amd64 gen --sub-domains www,ftp,mail sarit.r@codium.co codium.co
Password:
2016/11/22 09:57:30 Failed to obtain certificates for Domains: [mail.codium.co], with following errors [acme: Error 400 - urn:acme:error:badNonce - JWS has invalid anti-replay nonce 8utX6t6KjQFa4Kk-0bK-y_Z7p2qZQFKIbZOFZACKzkQ] respectively.
```

```
$ sudo ./concert_darwin_amd64 gen --dir my-certs sarit.r@codium.co codium.co
2016/11/22 09:58:19 Failed to obtain certificates for Domains: [codium.co], with following errors [acme: Error 400 - urn:acme:error:connection - Failed to connect to 184.168.221.13:443 for TLS-SNI-01 challenge
Error Detail:
	Validation for codium.co:443
	Resolved to:
		184.168.221.13
	Used: 184.168.221.13

] respectively.
```

```
$ sudo ./concert_darwin_amd64 gen --dir my-certs sarit.r@codium.co portal.uih.co.th
2016/11/22 09:59:40 Failed to obtain certificates for Domains: [portal.uih.co.th], with following errors [acme: Error 403 - urn:acme:error:unauthorized - Incorrect validation certificate for TLS-SNI-01 challenge. Requested 544da13b2f64cb0f53e9a8b1f41b2145.4c7ff415d899350ce89038a4afaf9e1f.acme.invalid from 43.249.68.9:443. Received certificate containing 'portal.uih.co.th'
Error Detail:
	Validation for portal.uih.co.th:443
	Resolved to:
		43.249.68.9
	Used: 43.249.68.9

] respectively.
```

Oh I miss `sudo`. Now new problem. Seems like my customer never use a `ssl` certificate.

**Comment by harshavardhana** [comment]
Looks the like there is a domain configuration issue, you need to be on the server itself to generate certs. i.e you should login to codium.co to generate certs. 

You cannot generate otherwise.

**Comment by elcolie** [comment]
New knowledge for me thank you very much

**Comment by harshavardhana** [comment]
> New knowledge for me thank you very much

You need to use tools like `certbot` but you need access to your DNS provider which allows for handshaking to happen to validate the domain names. 

You can alternatively just use self signed certs - https://github.com/minio/minio/blob/master/docs/configure-minio-with-tls.md#with-generate_certgo-self-signed-certificate
