### ISSUE TITLE
TestObjectAPIMultipartPutObjectStaleFiles fails under Windows

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3310]
## Expected Behavior
No stale files in put multipart objects

## Current Behavior
TestObjectAPIMultipartPutObjectStaleFiles fails under Windows

## Possible Solution
No solution

## Steps to Reproduce (for bugs)
go test -run=TestObjectAPIMultipartPutObjectStaleFiles

## Context
Need to check why TestObjectAPIMultipartPutObjectStaleFiles fails under Windows

## Your Environment
Windows amd64

**Comment by krisis** [comment]
@vadmeste are you working on this? If not, I could take this up.

**Comment by vadmeste** [comment]
hey @krisis, sorry the title was misleading.. I am not working on it.. You can take it if you want.
