### ISSUE TITLE
docs: Document docker-machine usage on OS X properly

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3319]
https://docs.docker.com/machine/get-started/ - Requires special handling of network etc.

**Comment by koolhead17** [comment]
@harshavardhana need more clarity here. 

I have run Minio FS with Docker Toolbox using Virtualbox out of the box. The network should have a DHCP server running to the instance acquires the IP. What is the specific steps we are talking about?

**Comment by harshavardhana** [comment]
> I have run Minio FS with Docker Toolbox using Virtualbox out of the box. The network should have a DHCP server running to the instance acquires the IP. What is the specific steps we are talking about?

This is using docker-machine not docker toolbox, seems like one of the user from cloud foundry had lot of trouble.

**Comment by koolhead17** [comment]
@harshavardhana recommended way of running docker machine is via docker toolbox.

https://docs.docker.com/machine/install-machine/ 
On macOS and Windows, Machine is installed along with other Docker products when you install the Docker Toolbox.

Installing Docker anyways is pre-requisite for running  Minio on Docker.  Installing Docker is beyond scope of us.

**Comment by harshavardhana** [comment]
> @harshavardhana recommended way of running docker machine is via docker toolbox.
> 
> https://docs.docker.com/machine/install-machine/
> On macOS and Windows, Machine is installed along with other Docker products when you install the Docker Toolbox.
> 
> Installing Docker anyways is pre-requisite for running Minio on Docker. Installing Docker is beyond scope of us.

Agreed @koolhead17 - closing.
