### ISSUE TITLE
log: do not print common error messages for known good cases

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3328]
## Expected Behavior
Currently we print log messages even for all the good cases, we should remove them and do not print them. 

## Current Behavior
Printing logs even for "bucket not found". 

## Possible Solution
Remove `bucket not found` error logging.  Errors like common messages shouldn't be printed.

**Comment by vadmeste** [comment]
I think we need to add Debug loglevel error, what do you think ?

**Comment by harshavardhana** [comment]
We don't need to we decided not to print such messages for now.

**Comment by balamurugana** [comment]
A good question would be whether such logs are useful for debugging or not.  Most of the cases debug logs won't be that useful (learned from Gluster)

**Comment by harshavardhana** [comment]
Patch sent #3340
