### ISSUE TITLE
log: enhance error logging like printk messages.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3329]
## Expected Behavior
 Do not repeat printing  repeated log messages. 

## Current Behavior
We print lot of log messages which are common, we should avoid them. 

## Possible Solution
We need to bring in a framework to address this.

**Comment by GarimaKapoor** [comment]
@harshavardhana is this still relevant?

**Comment by harshavardhana** [comment]
This is not relevant for now and we need to get back to it later as needed.
