### ISSUE TITLE
Minio client API calls fail with unknown errors if data directory access permission is incorrect

### ISSUE THREAD

**Issue by ghost** [minio/minio#3349]
This issue is noted when "data" directory access permission is incorrect and API call is trying to add an object with name as "prefix1/prefix2/filename"

## Expected Behavior
Appropriate directories should be created as well as file must be created in the directory.

## Current Behavior

The issue has been tested with NodeJS API as well as AWS NodeJs SDK. Both are failing. Minio JS API issue is noted in minio-js issue: https://github.com/minio/minio-js/issues/520

## Steps to Reproduce (for bugs)

1. Setup minio with data directory as /opt/myapp/minio/data. Following the instruction from here:
https://github.com/minio/minio-systemd
2. In linux /opt folder is typically owned by root 
3. Using nodejs try to upload an object with name as "prefix1/prefix2/filename"
4. Error will be thrown as mentioned in the https://github.com/minio/minio-js/issues/520
5. Temporary workaround is to manually go to bucket and give the permission to "minio" user such as 
cd opt/myapp/minio/data/<bucket-name>
chown -R minio:minio *

## Context

Trying to add object with certain parent path hierarchy.

## Your Environment

* Version used: RELEASE.2016-10-22T00-50-41Z
* Environment name and version (e.g. nginx 1.9.1): Minio JS API was used for uploading
* Server type and version: Client machine was MacOSX Sierra.
* Operating System and version: Ubuntu 16.04
* Link to your project:

**Comment by krisis** [comment]
@sachinwalia2k8 I get the following error when I attempt to start minio server on a root owned data directory.
```
➜  minio git:(master) ✗ minio server /opt/myapp/minio/data
FATA[0000] formatting storage disks failed               cause=Unable to initialize '.minio.sys' meta volume, disk access denied source=[server-main.go:458:serverMain()]
```
I have built minio server from source. See version below.
```
➜  minio git:(master) ✗ minio version 
Version: 2016-11-27T16:09:57Z
Release-Tag: DEVELOPMENT.2016-11-27T16-09-57Z
Commit-ID: 46a6fde813545cbb512b143ceb97fc91969def06
```
Could you confirm that with the above (or later) version you don't see minio server starting up and failing only on uploading of objects with slash separated prefixes, as you observed with an earlier version?

**Comment by ghost** [comment]
@krisis - the issue in my case was that /opt - was owned by root.
/opt/myapp/minio/data - was owned by minio user.
I think you may be able to reproduce this without running minio.
Without giving permission via "chown" try creating a folder inside /opt/myapp/minio/data/bucket and it should generate an error.

**Comment by krisis** [comment]
@sachinwalia2k8 This is what I observe when I tried the above,
1. /opt/myapp/minio/data is initially owned by root
```sh
➜  minio git:(master) ✗ sudo mkdir -p /opt/myapp/minio/data
➜  minio git:(master) ✗ ls -l /opt/myapp/minio/data
total 0
➜  minio git:(master) ✗ ls -l /opt/myapp/minio/    
total 4
drwxr-xr-x 2 root root 4096 Nov 28 23:51 data
```
2. We change owner to kp
 ```sh
➜  minio git:(master) ✗ sudo chown kp /opt/myapp/minio/data
➜  minio git:(master) ✗ ls -l /opt/myapp/minio/            
total 4
drwxr-xr-x 2 kp root 4096 Nov 28 23:51 data
```

3. Was able to create a directory bucket under /opt/myapp/minio/data as user kp.
 ```sh
➜  minio git:(master) ✗ mkdir /opt/myapp/minio/data/bucket  
➜  minio git:(master) ✗ echo $?
0
```
IIUC, you weren't able to create a directory like bucket above. Could you paste your output for this experiment in the backend filesystem you are using for minio server?

**Comment by GarimaKapoor** [comment]
@harshavardhana the same issue is opened in https://github.com/minio/minio-js/issues/520 we can close one.

**Comment by harshavardhana** [comment]
@GarimaKapoor minio-js is closed, this is for us to validate on server to not start in cases when we don't have permissions.

**Comment by ghost** [comment]
@krisis I'll try to replicate this behavior and will update with findings.

**Comment by harshavardhana** [comment]
> @krisis I'll try to replicate this behavior and will update with findings.

Thank you @sachinwalia2k8

**Comment by krisis** [comment]
@sachinwalia2k8 did you get a chance to replicate the behaviour?

**Comment by harshavardhana** [comment]
Closing this for now @sachinwalia2k8 - please let us know if you can reproduce it again.
