### ISSUE TITLE
unable to do cloudberry backup because of "pathing" error?

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3357]
Could very well be user but here is the information. Any assistance will be helpful.

error code:
time="2016-11-25T21:41:05-06:00" level=error msg="Unable to create an object." cause="mkdir \\?\c:\backups\backups\testing\MBS-eb2917ef-a3bc-4e8e-8652-3a1cb2fdb7e8\CBB_HUNTING_WABBIT\C:: The filename, directory name, or volume label syntax is incorrect." source="[object-handlers.go:447:objectAPIHandlers.PutObjectHandler()]" stack="/home/harsha/mygo/src/github.com/minio/minio/cmd/fs-v1.go:465:fsObjects.PutObject :195:(*fsObjects).PutObject /home/harsha/mygo/src/github.com/minio/minio/cmd/object-handlers.go:433:objectAPIHandlers.PutObjectHandler /home/harsha/mygo/src/github.com/minio/minio/cmd/api-router.go:58:(objectAPIHandlers).PutObjectHandler-fm"

## Expected Behavior
Works properly as documented.

## Current Behavior
Does not work with a particular set of files.

## Possible Solution
No solution yet.

## Your Environment

* Version used: latest minio release
* Environment name and version CloudBerry Explorer
* Operating System and version: Windows 10.

**Comment by harshavardhana** [comment]
// cc @BilliumG @erudinsky @koolhead17

**Comment by harshavardhana** [comment]
From @koolhead17  - https://github.com/minio/awesome-minio/issues/22

Hello @BilliumG Is your bucket name correct because the error ``The filename, directory name, or volume label syntax is incorrect."`` ? 
Also please follow [https://github.com/minio/cookbook/blob/master/docs/how-to-use-cloudberry-drive-with-minio.md](https://github.com/minio/cookbook/blob/master/docs/how-to-use-cloudberry-drive-with-minio.md)

Also adding @erudinsky to the thread. 😄

**Comment by harshavardhana** [comment]
From @erudinsky - https://github.com/minio/awesome-minio/issues/22

@BilliumG where do you run Minio? Windows? What backup type (file level etc) / what settings applied?

**Comment by BilliumG** [comment]
@harshavardhana  - not wanting to use cloudberry drive.  Just backup to bucket.  the bucket name is "testing" and should not be an issues

@erudinsky - Windows Server 2016 with command minio.exe sever c:\backups\backups.  backup fails with both image and file level backups

**Comment by harshavardhana** [comment]
Thanks @BilliumG

**Comment by BilliumG** [comment]
[dir list.txt](https://github.com/minio/minio/files/615382/dir.list.txt) - directory list from request in chat.

**Comment by BilliumG** [comment]
[minio.log.txt](https://github.com/minio/minio/files/615493/minio.log.txt)

**Comment by erudinsky** [comment]
@BilliumG we released v2.3.2.15 of drive. Can you check please?

**Comment by BilliumG** [comment]
Is this for CBB client or minio?

Thank You,
Bill Gerth
Vice President – Cloud Services Infrastructure and Support
BGerth@INGTS.com<mailto:BGerth@INGTS.com>
Office: 407-641-4211 x0110
Cell: 321 331 2698
[iNETWORKS Group]

**Comment by erudinsky** [comment]
Disregard that comment. We are trying to reproduce this issue.
Can you help us with logs like written [here](http://kb.cloudberrylab.com/kb1026/) please? Leave support as reference.

**Comment by BilliumG** [comment]
[rmservice.log.txt](https://github.com/minio/minio/files/617176/rmservice.log.txt)
[Task Scheduler.log.txt](https://github.com/minio/minio/files/617177/Task.Scheduler.log.txt)
[ef658ddf-f1d6-495b-989b-515d17fd0372.log.txt](https://github.com/minio/minio/files/617178/ef658ddf-f1d6-495b-989b-515d17fd0372.log.txt)
[Inetworks Online Backup.log.txt](https://github.com/minio/minio/files/617179/Inetworks.Online.Backup.log.txt)


I have also uploaded here incase they get "lost".

**Comment by krishnasrinivas** [comment]
minio.log.txt:
```
{"cause":"mkdir \\\\?\\c:\\backups\\backups\\testing\\MBS-eb2917ef-a3bc-4e8e-8652-3a1cb2fdb7e8\\CBB_HUNTING_WABBIT\\CBB_Configuration\\enginesettings.list:: The filename, directory name, or volume label syntax is incorrect.","level":"error","msg":"Unable to create an object.","source":"[object-handlers.go:447:objectAPIHandlers.PutObjectHandler()]","stack":"/home/harsha/mygo/src/github.com/minio/minio/cmd/fs-v1.go:465:fsObjects.PutObject \u003cautogenerated\u003e:195:(*fsObjects).PutObject /home/harsha/mygo/src/github.com/minio/minio/cmd/object-handlers.go:433:objectAPIHandlers.PutObjectHandler /home/harsha/mygo/src/github.com/minio/minio/cmd/api-router.go:58:(objectAPIHandlers).PutObjectHandler-fm","time":"2016-11-27T23:18:05-06:00"}
```

`mkdir \\\\?\\c:\\backups\\backups\\testing\\MBS-eb2917ef-a3bc-4e8e-8652-3a1cb2fdb7e8\\CBB_HUNTING_WABBIT\\CBB_Configuration\\enginesettings.list:`

is failing, need to check about the initial `\\\\?` string in the path is causing any issue.

**Comment by BilliumG** [comment]
Is this an adjustment I can make?

**Comment by krisis** [comment]
@erudinsky I found the following line in ``ef658ddf-f1d6-495b-989b-515d17fd0372.log.txt``.
```

2016-11-28 00:18:03,335 [CL] [9] ERROR - Command::Run failed:
Copy; Source:C:\ProgramData\Inetworks Services LLC\settings.list; Destination:/testing/MBS-eb2917ef-a3bc-4e8e-8652-3a1cb2fdb7e8/CBB_HUNTING_WABBIT/CBB_Configuration/settings.list:/20161127044747/
```
In this Destination has a `:` in its path. Does CBB add that to the destination path? Minio server uses UNC path in windows and `:` is a reserved character. (ref: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)

**Comment by BilliumG** [comment]
Per CBB tech i spoke with on chat when minio was suggested.  CBB had this setup in house.  What version of the software was that at least so i can finish my testing and move foward.
@erudinsky

**Comment by erudinsky** [comment]
@BilliumG CBB uses S3 compatible interface and has the same as for AWS S3 data structure for backups (e.g. in advanced/simple mode you have colon in folders names). Colon is reserved by Windows (not allowed) as @krisis mentioned. So your options for Windows use custom path mode (you should be able to store your content in S3 «as is», without CBB structure, thus without colon symbol). Another option - mount Minio server to other FS (e.g. ZFS) that allows colons in your files / folder names.

**Comment by BilliumG** [comment]
(e.g. in advanced/simple mode you have colon in folders names) - where is the set.

we are backing up to S3 now with no issues.

**Comment by erudinsky** [comment]
@BilliumG you can backup to Minio also as it is compatible with S3 interface with some constrains (like above). We (CBB) can't really change this strategy as it breaks other providers (S3 compatible interface). Workarounds explained above ^

**Comment by BilliumG** [comment]
@erudinsky so what do you have running in your office.  windows or linux flavor.  and i do not choose how to backup cbb is placing the files that way

**Comment by erudinsky** [comment]
@BilliumG not sure if I understood your question.

**Comment by BilliumG** [comment]
@harshavardhana @krishnasrinivas @krisis 
is this there a way to use minio is simple mode - see notes above.

@erudinsky so minio is no go with cbb on windows server.

**Comment by harshavardhana** [comment]
> is this there a way to use minio is simple mode - see notes above.

Minio doesn't have any simple mode i think the suggestion by @erudinsky 

- So your options for Windows use custom path mode (you should be able to store your content in S3 «as is», without CBB structure, thus without colon symbol).  You can use this with minio server on windows as well right now. 

- Another option - mount Minio server to other FS (e.g. ZFS) that allows colons in your files / folder names. This would require you to use Linux which allows storing files with colons. 

It would seem to me that former option is easier but if you wish to keep CBB structure then latter option is the only viable way to do it.

**Comment by BilliumG** [comment]
@harshavardhana 
Windows use custom path mode - how do you do you do this?  Google turned nothing up

**Comment by harshavardhana** [comment]
> Windows use custom path mode - how do you do you do this? Google turned nothing up

I think its a CBB feature @erudinsky ??

**Comment by erudinsky** [comment]
@harshavardhana @BilliumG Details are below. Yes, this is CBB feature, correct. 

I was talking about "custom path" in CBB product. Check screenshots below.

![screen shot 2016-11-29 at 14 18 59](https://cloud.githubusercontent.com/assets/9085802/20731416/31044548-b63f-11e6-89c4-4829299734fa.png)
Picture 1: your file level backup configuration with custom path.


![screen shot 2016-11-29 at 14 19 13](https://cloud.githubusercontent.com/assets/9085802/20731414/30f461a0-b63f-11e6-93af-ddbd2641c7e1.png)
Picture 2: your data is saved "as is", not CBB structure (apart level up with CBB configuration folder and files, but it does not contain colon or other constraints).


Using this mode your data is being saved "as is" without CBB structure. Data source was entire data folder, which resides in C:\Users\Administrator\Desktop\

**Comment by BilliumG** [comment]
@erudinsky i do not have this option on my CBB backup.  What version is this?  I am using 5.2.0.361. I do not have these options.

**Comment by BilliumG** [comment]
@erudinsky .....bump

**Comment by BilliumG** [comment]
Support Team 1
Neither version for Managed Backup supports other modes than Advanced Mode

**Comment by kmarquardt** [comment]
I am going to try installing it on Ubuntu server and see if that works.

**Comment by harshavardhana** [comment]
Closing this .
