### ISSUE TITLE
server: Support ipv6 with minio server

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3359]
## Expected Behavior
Minio server should support ipv6 and should be accessible through them.

## Current Behavior
Minio server does not support ipv6. 

## Possible Solution
We need to see if we are handling the ipv6 ip's properly.

**Comment by harshavardhana** [comment]
// cc @justinclift - who originally asked for this feature.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by gowithplanb** [comment]
As far as I can tell, Minio operates just fine on IPv6.

I have a native IPv6 connection to Minio over the internet and it works exactly the same as with IPv4.

Minio however doesn't tell you it's IPv6 reachable address when it starts.

**Comment by deekoder** [comment]
Let's discuss this further.

**Comment by justinclift** [comment]
Sounds like it might be mostly a matter of adding some IPv6 address detection so the IPv6 address can be displayed in the right places + some appropriate unit tests.  Hopefully it's that easy. :smile:

**Comment by vielmetti** [comment]
Any word on this one?

I ask because I have been debugging a confusing setup.

Server: Raspberry Pi on a LAN running `avahi`, addressed as "idaeus.local"

When I try to connect to it with `mc ls`, it hangs. Further debugging with `curl` results in this error:

```
curl -v https://idaeus.local:9000/photos/
*   Trying fe80::ba27:ebff:fe4e:8167...
* TCP_NODELAY set
* Connected to idaeus.local (fe80::ba27:ebff:fe4e:8167) port 9000 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

However when I force the connection to use IPv4, by pasting in the IPv4 address to the configuration, it appears to work just fine. I am a little confused by this behavior and don't know why it appears that `mc` is defaulting to IPv6 on its connection but that might be a red herring.

**Comment by harshavardhana** [comment]
> However when I force the connection to use IPv4, by pasting in the IPv4 address to the configuration, it appears to work just fine. I am a little confused by this behavior and don't know why it appears that mc is defaulting to IPv6 on its connection but that might be a red herring.

It is not `mc` which is defaulting but instead the kernel resolver is resolving to IPv6 by default if present @vielmetti , our listener might not be listening on the IPv6 address in this situation. 

We haven't prioritized this issue yet. Since using IP directly works fine.

**Comment by harshavardhana** [comment]
Closing this will be revisited in future as per discussion with @abperiasamy

**Comment by trygvis** [comment]
Is this something that will be supported? Is there a new issue to track it I can subscribe to?

**Comment by harshavardhana** [comment]
> Is this something that will be supported? Is there a new issue to track it I can subscribe to?

This is the issue we might re-open this in future.

**Comment by Subito** [comment]
I upgraded from 2018.07.13.00.09.07 to 2018.10.25.01.27.03 and "IPv6 stopped working" I don't know why, but it only listens on IPv4 and I can't influence that in any way. Any progress on this would be greatly appreciated :)

**Comment by harshavardhana** [comment]
This is on purpose we don't currently fully support ipv6 yet, it wasn't fully working either in older releases.
