### ISSUE TITLE
Older go versions

### ISSUE THREAD

**Issue by szepeviktor** [minio/minio#3363]
Hello!

First I've tried installing with go 1.6 and I've got an error message x509.somethinpool... is missing

After some time I've realized minio needs go 1.7

Could it be that there warning message is not appearing on go 1.6?
https://github.com/minio/minio/blob/ca3022d5450cee5e6b39bcfe6126231ff9302262/cmd/runtime-checks.go#L28

**Comment by harshavardhana** [comment]
We don't support older Go versions.   Go 1.7 and newer is supported.

**Comment by harshavardhana** [comment]
'checkGoVersion()' is executed at runtime and also 'make' validates the go version. Using 'go get' we couldn't restrict which version it should use.

**Comment by szepeviktor** [comment]
Thank you.

So `go get` has no mechanism to check runtime version (like composer does).
