### ISSUE TITLE
Safe file uploading

### ISSUE THREAD

**Issue by diffnull** [minio/minio#3370]
When I use `mc cp` to upload file and the other process is simultaneously downloading object with same name using `mc cp` too, eventually downloading breaks down due to file size changing. How can I safely upload file to minio bucket?

**Comment by harshavardhana** [comment]
> When I use mc cp to upload file and the other process is simultaneously downloading object with same name using mc cp too, eventually downloading breaks down due to file size changing. How can I safely upload file to minio bucket?

Can you provide a reproducer for this when this happens? @elyzov - a sample script etc.

**Comment by diffnull** [comment]
There are two files in my play bucket:
```
$ mc ls play/elyzov
[2016-11-30 11:51:28 KRAT] 108MiB VirtualBox-5.0.22-108108-Win.exe
[2016-11-30 11:48:46 KRAT] 115MiB VirtualBox-5.1.0-108711-Win.exe
```
If you download one of this files
```
$ mc cp play/elyzov/VirtualBox-5.0.22-108108-Win.exe .
```
And trying to upload downloaded file with another name (to simulate content file changing)
```
$ mc cp  VirtualBox-5.0.22-108108-Win.exe play/elyzov/VirtualBox-5.1.0-108711-Win.exe
```
And in another console trying to download this file
```
$ mc cp play/elyzov/VirtualBox-5.1.0-108711-Win.exe .
```
You'll get the following error
```
mc: <ERROR> Failed to copy ‘https://play.minio.io:9000/elyzov/VirtualBox-5.1.0-108711-Win.exe’. Input reader closed pre-maturely. Expected ‘120192480’ bytes, but only received ‘113385952’ bytes.
```

**Comment by harshavardhana** [comment]
Checking.. @elyzov

**Comment by krishnasrinivas** [comment]
@harshavardhana https://github.com/minio/minio/issues/2912 might be causing it

**Comment by krishnasrinivas** [comment]
shucks, looks like we are also not holding lock in `func (fs fsObjects) CompleteMultipartUpload()`

**Comment by harshavardhana** [comment]
> shucks, looks like we are also not holding lock in func (fs fsObjects) CompleteMultipartUpload()

Yes but 'play' is not using FS it is XL.

**Comment by harshavardhana** [comment]
i am not able to simulate it @elyzov - can you keep the same files on play for us to download and test?

**Comment by diffnull** [comment]
@harshavardhana sorry, I've recovered files in play as describe in example:
```
mc ls play/elyzov
[2016-11-30 14:50:37 KRAT] 108MiB VirtualBox-5.0.22-108108-Win.exe
[2016-11-30 14:51:40 KRAT] 115MiB VirtualBox-5.1.0-108711-Win.exe
```

Also, you may wait awhile before start downloading in the another console (in this case file will be overrided before download has finished).

**Comment by harshavardhana** [comment]
> @harshavardhana sorry, I've recovered files in play as describe in example:
> 
> mc ls play/elyzov
> [2016-11-30 14:50:37 KRAT] 108MiB VirtualBox-5.0.22-108108-Win.exe
> [2016-11-30 14:51:40 KRAT] 115MiB VirtualBox-5.1.0-108711-Win.exe
> Also, you may wait awhile before start downloading in the another console (in this case file will be overrided before download has finished).

Understood thanks @elyzov
