### ISSUE TITLE
inconsistent StorageInfo on cluster

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3372]
4 physical servers running the edge version of minio with docker.
It's a staging environment and the minio are restarted frequently in //
Sometimes the StorageInfo call does not return the same info for all servers, restarting the "failing" server fix the problem, the data are **not changed** between the restarts, we do **not** remove the exported folder.

It would be better to consistently restart successfully but way more important, all StorageInfo should report strictly the same information about Connected and failing disks.

```
{
     "host": "http://node0.st2.------tech.org:9000",
     "data": {
       "storageInfo": {
         "Total": 15872866181120,
         "Free": 14900683038720,
         "Backend": {
           "Type": 2,
           "OnlineDisks": 4,
           "OfflineDisks": 0,
           "ReadQuorum": 2,
           "WriteQuorum": 3
         }
       },
       "uiVersion": "2016-11-24T00:39:02Z"
     }
   },
   {
     "host": "http://node1.st2.------tech.org:9000",
     "data": {
       "storageInfo": {
         "Total": 11904649635840,
         "Free": 11174937053184,
         "Backend": {
           "Type": 2,
           "OnlineDisks": 3,
           "OfflineDisks": 1,
           "ReadQuorum": 2,
           "WriteQuorum": 3
         }
       },
       "uiVersion": "2016-11-24T00:39:02Z"
     }
   },
   {
     "host": "http://node2.st2.------tech.org:9000",
     "data": {
       "storageInfo": {
         "Total": 15872866181120,
         "Free": 14900683038720,
         "Backend": {
           "Type": 2,
           "OnlineDisks": 4,
           "OfflineDisks": 0,
           "ReadQuorum": 2,
           "WriteQuorum": 3
         }
       },
       "uiVersion": "2016-11-24T00:39:02Z"
     }
   },
   {
     "host": "http://node3.st2.------tech.org:9000",
     "data": {
       "storageInfo": {
         "Total": 15872866181120,
         "Free": 14900683038720,
         "Backend": {
           "Type": 2,
           "OnlineDisks": 4,
           "OfflineDisks": 0,
           "ReadQuorum": 2,
           "WriteQuorum": 3
         }
       },
       "uiVersion": "2016-11-24T00:39:02Z"
     }
   }
```

**Comment by harshavardhana** [comment]
Thanks @dcharbonnier

**Comment by vadmeste** [comment]
> Thanks @dcharbonnier

@dcharbonnier also reported that sometimes, one node is not able to reach another node (3 onlines, 1 offline) after restarting servers though he is sure that connections between servers are excellent.

**Comment by harshavardhana** [comment]
@dcharbonnier - is the "/export" ephemeral here or persistent?  also is the backend export deleted during these runs?

**Comment by dcharbonnier** [comment]
@harshavardhana this morning it was after destroying the storage but after that it happened twice keeping the storage unchanged with simply a restart of all servers at the same time

**Comment by harshavardhana** [comment]
I have tried reproducing this @dcharbonnier - but not able to reproduce it.  I see that StorageInfo is returning properly each time it reboots the container,  is there any logs that you have ? can you enable "error" in your `~/.minio/config.json`  if not already set? 


```
{
     "host": "http://node1.st2.------tech.org:9000",
     "data": {
       "storageInfo": {
         "Total": 11904649635840,
         "Free": 11174937053184,
         "Backend": {
           "Type": 2,
           "OnlineDisks": 3,
           "OfflineDisks": 1,
           "ReadQuorum": 2,
           "WriteQuorum": 3
         }
       },
       "uiVersion": "2016-11-24T00:39:02Z"
     }
```

Also is the offline disk reported by the node that was restarted or some other nodes in the cluster?

**Comment by dcharbonnier** [comment]
They all restart, i don't get the question. Did you automated the restart and do you have 4 mschines and not 4 containers on the same machine ?

**Comment by harshavardhana** [comment]
> They all restart, i don't get the question. Did you automated the restart and do you have 4 mschines and not 4 containers on the same machine ?

I have 4 machines on hyper.sh i am thinking that these are on individual instances. from what i gathered i thought it was only one node that was restarted. Let me re-test by restarting all nodes.

**Comment by dcharbonnier** [comment]
Yes and do it in // not in a sequence

**Comment by GarimaKapoor** [comment]
@harshavardhana is there an update on this issue?

**Comment by harshavardhana** [comment]
> @harshavardhana is there an update on this issue?

Unable to reproduce till now, so setting a scaleway instance.

**Comment by dcharbonnier** [comment]
again :

```
Version: 2016-12-07T11:26:45Z
Release-Tag: DEVELOPMENT.2016-12-07T11-26-45Z
Commit-ID: 71f0b35d1e15f3fc41dd07620ec205a1bb486739
```
```

  "Cluster return inconsistent data",
  [
    {
      "host": "http://node0.xxxx.org:9000",
      "data": {
        "storageInfo": {
          "Total": 15872866181120,
          "Free": 14815561392128,
          "Backend": {
            "Type": 2,
            "OnlineDisks": 4,
            "OfflineDisks": 0,
            "ReadQuorum": 2,
            "WriteQuorum": 3
          }
        },
        "uiVersion": "2016-11-24T00:39:02Z"
      }
    },
    {
      "host": "http://node1.xxxx.org:9000",
      "data": {
        "storageInfo": {
          "Total": 11904649635840,
          "Free": 11111671044096,
          "Backend": {
            "Type": 2,
            "OnlineDisks": 3,
            "OfflineDisks": 1,
            "ReadQuorum": 2,
            "WriteQuorum": 3
          }
        },
        "uiVersion": "2016-11-24T00:39:02Z"
      }
    },
    {
      "host": "http://node2.xxxx.org:9000",
      "data": {
        "storageInfo": {
          "Total": 15872866181120,
          "Free": 14815561392128,
          "Backend": {
            "Type": 2,
            "OnlineDisks": 4,
            "OfflineDisks": 0,
            "ReadQuorum": 2,
            "WriteQuorum": 3
          }
        },
        "uiVersion": "2016-11-24T00:39:02Z"
      }
    },
    {
      "host": "http://node3.xxxx.org:9000",
      "data": {
        "storageInfo": {
          "Total": 15872866181120,
          "Free": 14815561392128,
          "Backend": {
            "Type": 2,
            "OnlineDisks": 4,
            "OfflineDisks": 0,
            "ReadQuorum": 2,
            "WriteQuorum": 3
          }
        },
        "uiVersion": "2016-11-24T00:39:02Z"
      }
    }
  ]
]
```

**Comment by harshavardhana** [comment]
@dcharbonnier is this observed again?

**Comment by dcharbonnier** [comment]
no but I didn't restarted minio so much those days

**Comment by harshavardhana** [comment]
> no but I didn't restarted minio so much those days

Okay understood. Thanks

**Comment by dcharbonnier** [comment]
I confirm @harshavardhana still the same, 3 hosts reporting the same information (all ok), one host reporting an error...

**Comment by harshavardhana** [comment]
> I confirm @harshavardhana still the same, 3 hosts reporting the same information (all ok), one host reporting an error...

I see will try to reproduce it , are you using scaleway? can you post your scaleway instance config - will try to replicate them.

**Comment by harshavardhana** [comment]
https://gist.github.com/dcharbonnier/1fc0d2aa01fbbcf75ff095d2387730b9 shared by @dcharbonnier to validate this issue. 

Any takers here @krisis @vadmeste @krishnasrinivas @hackintoshrao @balamurugana ?

**Comment by harshavardhana** [comment]
https://hub.docker.com/r/y4m4/minio/ @dcharbonnier this is fixed here..

**Comment by harshavardhana** [comment]
Can you validate this on your end by changing the cluster to use "y4m4/minio" docker image instead. @dcharbonnier ?
