### ISSUE TITLE
php aws sdk version 1 with minio

### ISSUE THREAD

**Issue by sudha53633** [minio/minio#3378]
Hi there,

Really i love to use minio.

Currently i'm using php aws sdk for s3(version 1), I would like to use minio with php aws sdk version 1. I could able to work with php aws sdk version 3, everything working fine. but coming php aws sdk version 1 i don't find anything to configure minio access_key,secret & endpoint. Could you please help me out to work with version 1

Thanks
Sudhakar

**Comment by koolhead17** [comment]
Hello @sudha53633 
Thanks for your kind words.

AWS PHP1 is deprecated and not recommended by [AWS S3](https://github.com/amazonwebservices/aws-sdk-for-php), Since Minio compatible with AWS S3 API, we follow its latest API specification so we would recommend using version3.

Hope it helps!!

Atul

**Comment by sudha53633** [comment]
Hmm, Thank you for quick response. Using latest version is best choice.

**Comment by koolhead17** [comment]
yes @sudha53633.
Also if it is okey please close this issue. Feel free to reach out to us on our developer chat channel on [Gitter](https://gitter.im/minio/minio) for further help.

Thanks again, Welcome to Minio Community 😄 

Atul
