### ISSUE TITLE
presigned get: cannot share a prefix which contains unicode characters

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3379]
## Expected Behavior
Presigning objects with unicode characters work

## Current Behavior
URL like this doesn't work : http://127.0.0.1:9000/testbucket/%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9/index.html?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20161201%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20161201T201642Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=c8dbaaa282f5e2eee021ebc1257c708e165d0f4ceeda500ef2258c5b580bb3c9

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
Open the provided URL above

## Context
New found bug

## Your Environment
All env

**Comment by harshavardhana** [comment]
how is the presigned URL obtained? @vadmeste

**Comment by vadmeste** [comment]
> how is the presigned URL obtained? @vadmeste

Minio Browser.

**Comment by harshavardhana** [comment]
> how is the presigned URL obtained? @vadmeste
> Minio Browser.

Can you try with `mc share download` ? can you paste the difference?

**Comment by vadmeste** [comment]
This is a false bug.
