### ISSUE TITLE
tls: Certificates not provided for https error 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3382]
@sych74 - wrote : 

Hi guys, can you advice how to configure https? getting the error Certificates not provided for https
Thanks

@harshavardhana wrote : 

To configure SSL you have to put certs into the "~/.minio/certs/" folder as mentioned here https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio

Otherwise you can configure the load balancer to have SSL and it just talks to minio internally without SSL. Something like how an nginx proxy would do - https://docs.minio.io/docs/setup-nginx-proxy-with-minio

@sych74 wrote : 

btw, why the SSL certificates are required for commutation across the nodes if I can upload files from browser w/o them. Does the communication work not over https?

## Your Environment

* Version used: docker latest image.

**Comment by harshavardhana** [comment]
ping @sych74 - opened a new bug here to discuss about the TLS problems. Please let me know does this occur without configuring TLS? or is it the client that was requesting it?  etc.

**Comment by sych74** [comment]
let me check couple more things, will follow-up

**Comment by harshavardhana** [comment]
> let me check couple more things, will follow-up

Thanks @sych74 let us know.

**Comment by sych74** [comment]
@harshavardhana, I suggest to close this issue for now, I implemented http for communication inside internal network and https via load balancer if requests are coming outside. Seems working fine so far.

**Comment by harshavardhana** [comment]
> @harshavardhana, I suggest to close this issue for now, I implemented http for communication inside internal network and https via load balancer if requests are coming outside. Seems working fine so far.

Great to know thanks @sych74
