### ISSUE TITLE
postform: uploading an empty file is not successful

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3385]
## Expected Behavior
Uploading an empty object via post form works

## Current Behavior
Uploading an empty object via post form doesn't work

## Possible Solution
Don't know

## Context
Normal testing

## Your Environment
All

I'll fix this after finishing the check post form

**Comment by harshavardhana** [comment]
Why should it not work ? Only if content length range is specified it makes sense to return error.

**Comment by vadmeste** [comment]
> Why should it not work ?

I meant it should work but it doesn't work actually

**Comment by vadmeste** [comment]
it works with XL but not with FS

```
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```
