### ISSUE TITLE
api/mgmt: Implement a new admin package as a client for management APIs.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3396]
## Expected Behavior
We need a library just like `minio-go` to be implemented for management APIs which will be imported by `mc` to implement `mc admin` command.

## Current Behavior
There are no management APIs to manage minio server. 

## Possible Solution
Resolve issues present here 

- https://github.com/minio/minio/issues/3395
- https://github.com/minio/minio/issues/3394
- https://github.com/minio/minio/issues/3393

## Context
This package will reside on the server inside `pkg/` directory and will be imported by `mc` to implement `mc admin` command.

**Comment by GarimaKapoor** [comment]
@harshavardhana can we close this?

**Comment by harshavardhana** [comment]
@GarimaKapoor there are two more issues that needs to be resolved.

**Comment by harshavardhana** [comment]
One more healing API is pending on this bug.

**Comment by harshavardhana** [comment]
Closing since the madmin package itself has been added and vendorized / used by mc.  Healing API has its own bug.
