### ISSUE TITLE
Aliyun OSS Support

### ISSUE THREAD

**Issue by bscott** [minio/minio#3401]
Requesting support for Alibaba Aliyun Cloud Object Storage.

https://intl.aliyun.com/product/oss

**Comment by harshavardhana** [comment]
@bscott can you explain a bit on what is the requirement here? - Minio is S3 compatible are you thinking that we should expose Aliyun OSS compatible API as well?

**Comment by bscott** [comment]
@harshavardhana Yes, I don't think Aliyun is S3 compatible as I've tried S3 clients and they fail.

**Comment by harshavardhana** [comment]
> @harshavardhana Yes, I don't think Aliyun is S3 compatible as I've tried S3 clients and they fail.

We are S3 API compatible @bscott - do we need to keep this open?

**Comment by GarimaKapoor** [comment]
closing this for now!

**Comment by bscott** [comment]
@GarimaKapoor We need to reopen this as thier API is not exact same as S3

**Comment by harshavardhana** [comment]
> @GarimaKapoor We need to reopen this as thier API is not exact same as S3

Minio is meant to be only S3 compatible, we are not planning to implement support for Aliyun OSS API.

**Comment by bscott** [comment]
From what I can see Aliyun is S3 Compatible but I'm seeing errors like this

```
Input reader closed pre-maturely. Expected ‘4226’ bytes, but only received ‘0’ bytes.
```

**Comment by harshavardhana** [comment]
> From what I can see Aliyun is S3 Compatible

Then the apps running on Aliyun would work fine on Minio as well.

**Comment by bscott** [comment]
@harshavardhana Any idea if that error is because of Minio?

**Comment by harshavardhana** [comment]
> @harshavardhana Any idea if that error is because of Minio?

Can you please open a bug on https://github.com/minio/mc/issues with "mc version" and "mc --debug" output.

**Comment by bscott** [comment]
Will do @harshavardhana Thanks
