### ISSUE TITLE
minio/mc: [feature] mc mirror for entire instance

### ISSUE THREAD

**Issue by jmthackett** [minio/minio#3418]
Erasure coding as currently implemented has some limitations around migration. The idea that migration between clusters should be necessary (rather than rebuilding them or dynamically increasing their size) leaves an opening for a tool to migrate. I'd suggest `mc mirror` as the right candidate.

I'd like to be able to do something like this:

`mc mirror --watch --force --remove myminio1/* myminio2/*`

This would give the ability to keep two clusters in sync until the old one is retired. It would also be useful for mirroring to other services like S3.

At the moment, this doesn't work: mc expects a bucket. If it accepted a glob or regex, or just the otherwise unqualified bucket alias, that'd be very helpful for anyone doing migrations or eventually-consistent mirrors.

**Comment by GarimaKapoor** [comment]
@abperiasamy can you take a look at this?

**Comment by harshavardhana** [comment]
This we agreed to implement @GarimaKapoor

**Comment by vadmeste** [comment]
Taking this

**Comment by vadmeste** [comment]
Ongoing development and finding: we will need --region flag to correctly create buckets in the second instance.

**Comment by harshavardhana** [comment]
> Ongoing development and finding: we will need --region flag to correctly create buckets in the second instance.

You can use 'GetBucketLocation()' API from minio-go @vadmeste

**Comment by vadmeste** [comment]
> You can use 'GetBucketLocation()' API from minio-go @vadmeste

Well, the bucket doesn't exist yet to fetch its location

**Comment by vadmeste** [comment]
Also I guess --force will allow overriding policy rules in the second instance if they ever exist

**Comment by harshavardhana** [comment]
This is fixed in mc master branch. Closing.
