### ISSUE TITLE
api: ListenBucketNotification sporadically fails to send events sometimes

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3424]
## Expected Behavior
Events are not lost or should have a possible reason why it was lost.

## Current Behavior
Sporadically events may get lost this behavior was reproduced with `mc watch`. 

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)

1. `mc watch` 
2. Take the network down (mc watch reconnects if network is available)
3. Network is back up `copy` files now on the watch bucket. 
4. Once in a while events might get lost.

## Context
Events shouldn't be lost after re-connection.

**Comment by harshavardhana** [comment]
Any takers here? @donatello ?

**Comment by donatello** [comment]
Yes, I will take this.

**Comment by donatello** [comment]
@harshavardhana I've been unable to reproduce this so far. Here's the script I'm using to simulate this situation - https://gist.github.com/donatello/cfa09d78e9db6bd945b8ce5b8974db21 - with iptables.

With REJECT in iptables, no events are lost. With DROP, the events appear after some time.

Testing was done on FS-mode.

Can you provide more info about how network is going down in your situation?

**Comment by harshavardhana** [comment]
I think a possible bug might exist in minio-go but not sure.

**Comment by harshavardhana** [comment]
> @harshavardhana I've been unable to reproduce this so far. Here's the script I'm using to simulate this situation - https://gist.github.com/donatello/cfa09d78e9db6bd945b8ce5b8974db21 - with iptables.
> 
> With REJECT in iptables, no events are lost. With DROP, the events appear after some time.
> 
> Testing was done on FS-mode.
> 
> Can you provide more info about how network is going down in your situation?

@donatello can you check if minio-go code has any races?

**Comment by donatello** [comment]
@harshavardhana ok will do. You can assign this to me.

**Comment by harshavardhana** [comment]
Not able to reproduce this anymore.. closing this. Will re-open if seen again.
