### ISSUE TITLE
undefined: x509.SystemCertPool

### ISSUE THREAD

**Issue by huytn** [minio/minio#3429]
Hi all,
I Got error while installing from source
```
go get -u github.com/minio/minio
# github.com/minio/minio/cmd
src/github.com/minio/minio/cmd/certs.go:81: undefined: x509.SystemCertPool
```
I'm using
OS: debian 8 
Golang: 1.7.4.linux-amd64

**Comment by koolhead17** [comment]
hello @huytn how did you install golang? I have installed golang 1.7.4 from source [https://golang.org/dl/](https://golang.org/dl/)

Minio is working perfectly fine for me on debian8.

```
debian@debian:~$ go version
go version go1.7.4 linux/amd64
debian@debian:~$ cat /etc/debian_version
8.6
debian@debian:~$ go get -u github.com/minio/minio
debian@debian:~$ minio server myroot
Created minio configuration file at /home/debian/.minio

Endpoint:  http://192.168.1.110:9000  http://127.0.0.1:9000
AccessKey: PSXNO82WE651TY6VXOG3 
SecretKey: D7XdwiSQzltyFcs/gzYy9i8xtfF5dpq3Q9XMpwQY 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://192.168.1.110:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.110:9000 PSXNO82WE651TY6VXOG3 D7XdwiSQzltyFcs/gzYy9i8xtfF5dpq3Q9XMpwQY

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 5.4 GiB Free, 7.4 GiB Total
```
In my case I have installed golang from source. This is how installed it on a fresh debian8 machine followed by installing Minio.

```
$ sudo apt-get install git 
$ wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
$ tar -C ${HOME} -xzf go1.7.4.linux-amd64.tar.gz
```
update ``~/.bashrc`` file by adding,
```
export GOROOT=${HOME}/go
export GOPATH=${HOME}/work
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```
source the enviornment 
$ source ~/.bashrc
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/debian/work"
GORACE=""
GOROOT="/home/debian/go"
GOTOOLDIR="/home/debian/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
$ go version
go version go1.7.4 linux/amd64

Installing Minio after this should work.

**Comment by huytn** [comment]
I reinstalled go1.7.4 and the installation is ok :(
