### ISSUE TITLE
Is it possible to specify bucket policy on server start?

### ISSUE THREAD

**Issue by astafev** [minio/minio#3430]
It's possible to specify a path to storage, but is there a way to make some directory publicly accessible on start (not with `mc policy` command)?

I'm running minio in Docker. Didn't find anything in documentation.

**Comment by vadmeste** [comment]
> It's possible to specify a path to storage, but is there a way to make some directory publicly accessible on start (not with mc policy command)?
> 
> I'm running minio in Docker. Didn't find anything in documentation.

After creating a bucket, you'll need to configure it to be public only one time.

We are following S3 specification, there is no other way.

**Comment by astafev** [comment]
@vadmeste hi, thanks for quick response. Just to make sure: there's no good way to specify bucket policy other than on already running server, right? Where does minio saves policy information if it's not in `/export` folder and not in `~/.minio`, it should be somewhere, right?

Maybe I'm missing something, but what is the problem with S3 specification? Usually we don't start S3 servers, so Minio and S3 are different in this part.

**Comment by astafev** [comment]
seems like I've found what I was looking for - a bucket `.minio.sys`, it's possible to put there resource `buckets/<bucketName>/policy.json` and specify there all necessary rules.

**Comment by vadmeste** [comment]
@astafev, can you explain a little more your use case?

By the way, when using docker, you need to bind /export directory to somewhere persistent so you won't lose all information when you restart your docker instance. Look at -v flag in docker documentation (man docker-run)

**Comment by astafev** [comment]
@vadmeste we're using minio as shared storage for multiple applications in docker-compose environment. Minio server for it needs to contain few resources already on start, some of those resources needs to be public.
So, what I'm doing is creating a custom docker image, copying all necessary resources to `export` folder in the created image. 

At the moment we don't need to retain any information besides those predefined resources between launches.
