### ISSUE TITLE
Minio does not work if installed on different Drive then C: on windows

### ISSUE THREAD

**Issue by tjachmann** [minio/minio#3433]
On windows 7 64bit, I always get the error <level=fatal msg="formatting storage disks failed" cause="corrupted backend format"> when the minio.exe is started on a different drive then C:

On another note, my Firefox only shows the loading icon, when browing to "http://127.0.0.1:9000/". Though Chrome works.

**Comment by harshavardhana** [comment]
> On windows 7 64bit, I always get the error <level=fatal msg="formatting storage disks failed" cause="corrupted backend format"> when the minio.exe is started on a different drive then C:
> 
> On another note, my Firefox only shows the loading icon, when browing to "http://127.0.0.1:9000/". Though Chrome works.

@tjachmann which version of minio binary are you using?

**Comment by tjachmann** [comment]
I downloaded the 32 and 64 bit windows binaries a few moments ago from here:

https://docs.minio.io/docs/minio-quickstart-guide

The version commands shows:

Version: 2016-12-12T18:35:43Z
Release-Tag: RELEASE.2016-12-12T18-35-43Z
Commit-ID: 6b4e6bcebf1127f7b1444790580bb5b64f31c6e7

**Comment by harshavardhana** [comment]
> I downloaded the 32 and 64 bit windows binaries a few moments ago from here:
> 
> https://docs.minio.io/docs/minio-quickstart-guide
> 
> The version commands shows:
> 
> Version: 2016-12-12T18:35:43Z
> Release-Tag: RELEASE.2016-12-12T18-35-43Z
> Commit-ID: 6b4e6bc
>  
>   
>             
>   
> Write

Checking @tjachmann

**Comment by harshavardhana** [comment]
Looks like there is a regression fixing it.

**Comment by tjachmann** [comment]
In the meantime I was trying to access the local minio server http://127.0.0.1:9000/ via amazonaws .net sdk. The list bucket command worked as expected. But create,read or write commands just hang and do nothing.

**Comment by harshavardhana** [comment]
> In the meantime I was trying to access the local minio server http://127.0.0.1:9000/ via amazonaws .net sdk. The list bucket command worked as expected. But create,read or write commands just hang and do nothing.

Server is on windows? @tjachmann

**Comment by harshavardhana** [comment]
> Server is on windows? @tjachmann

I just tried and uploaded a file through the web browser. Can you paste your sample program? @tjachmann - Also have you tried with https://github.com/minio/mc ?

**Comment by harshavardhana** [comment]
> I just tried and uploaded a file through the web browser. Can you paste your sample program? @tjachmann - Also have you tried with https://github.com/minio/mc ?

Also please open a new github issue and also let us know if the AWS SDK version including perhaps "trace" output of the network traffic and error that server sent etc.
