### ISSUE TITLE
k8s integration: create official helm chart for standalone Minio server installation on Kubernetes

### ISSUE THREAD

**Issue by nitisht** [minio/minio#3443]
## Expected Behavior
Helm is a package manager for Kubernetes. Need to create an official Helm Chart that enables users to install standalone Minio on their Kubernetes cluster via Helm commands.

## Current Behavior

No Helm installer available currently. 

## Possible Solution
Follow the guide to create new [Helm Charts](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md) and add the chart to [Kubernetes/charts/stable repo](https://github.com/kubernetes/charts/tree/master/stable).

## Context
Minio should be easy to get started with on a Kubernetes cluster. Having a Helm installer will simplify the process.

**Comment by nitisht** [comment]
Helm chart created by community member. Can be accessed here: https://github.com/kubernetes/charts/tree/master/stable/minio

Will review and update the chart repo. We can then close this issue.

**Comment by harshavardhana** [comment]
This is done right @NitishT ?

**Comment by nitisht** [comment]
Yes @harshavardhana , fixed with https://github.com/kubernetes/charts/pull/348 

Minio Helm Chart is now available at https://github.com/kubernetes/charts/tree/master/stable/minio
