### ISSUE TITLE
docs: Add note section in minio distributed guide.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#3453]
Add note section in minio distributed guide.

## Context
* We should add note in our Minio distributed docs that order of command execution should be uniform in all the nodes.
* All the disk used for Minio distributed should be fresh i.e without any other existing data.

**Comment by koolhead17** [comment]
cc: @deekoder

**Comment by harshavardhana** [comment]
what is this waiting on @koolhead17 ?

**Comment by koolhead17** [comment]
@harshavardhana  was waiting for feedback.

**Comment by GarimaKapoor** [comment]
@koolhead17 what feedback are you waiting on? Is the PR already sent.

**Comment by harshavardhana** [comment]
> We should add note in our Minio distributed docs that order of command execution should be uniform in all the nodes.
> All the disk used for Minio distributed should be fresh i.e without any other existing data.

We will update the distributed docs to explicitly mention this.
