### ISSUE TITLE
erasure/distributed:  Throughput inconsistent with standalone single backend

### ISSUE THREAD

**Issue by aidabeorn** [minio/minio#3468]
After getting distributed to work, I was underwhelmed by the performance, using siege we see 71 transactions per second average over 1 minute. Switching to a non-distributed minio server we see 188 transactions per second.

## Expected Behavior
Higher throughput or at least minimally impacted throughput when using minio in distributed settings

## Current Behavior
when Minio is distributed throughput seems to take a significant hit

## Steps to Reproduce (for bugs)
1. set up 4 minio nodes
2. set up a loadbalancer of sorts (I've used træfik for these tests, also tested with haproxy) w/ round robin (non sticky)
3. execute `siege -c 250 -b -t 1m http://minio/test/test.txt`

## Context
70 transactions per second is far too low for the use-case we're targeting (distributing static images, css, js, json and updates)

## Your Environment
* Version used: 2016-12-13T17:19:42Z
* Environment name and version (e.g. nginx 1.9.1): træfik 1.1.2 on docker/haproxy 1.6.3 from Ubuntu repo
* Server type and version: 4x virtual machines with 2 vcpu 2GB ram
* Operating System and version: Ubuntu 16.04.1 LTS
* Link to your project:

_ps:_ we will be trying to scale the machines and see if the issue persists on higher-end hardware

**Comment by krishnasrinivas** [comment]
@thorerik the VMs you use for testing, are they on same machine? or are they VMs on digital ocean or any other cloud provider?

**Comment by aidabeorn** [comment]
They are at scaleway

**Comment by harshavardhana** [comment]
Distributed does erasure coded and bitrot comparing that with a non erasure coded wouldn't yield right results.

To understand the behavior more here are some questions

- network speed (provide output from iperf tool output)
- backend disk speed ( dd if=/dev/zero of=bigfile bs=1m count=1024 oflag=direct ) - this would tell us raw disk performance 
-  can you also provide us the average file size used in these tests ?
- was the client on the same machine or separate ? Network speed between client and server ?

**Comment by aidabeorn** [comment]
* iperf:
```
between LB and minio01:
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.1 sec  1018 MBytes   842 Mbits/sec
between minio01 and minio03:
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.2 sec  1.00 GBytes   841 Mbits/sec
```
* disk speed:
```
% dd if=/dev/zero of=bigfile bs=1M count=1024 oflag=direct
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 10.5329 s, 102 MB/s
```
(the other 3 hosts matched about this speed, all doing it simultaneously;
* average file size
tested using a single file that is 131K (representative of the majority of files we'll be serving)
* Client was in norway, but testing with clients on same network yield similar result

**Comment by harshavardhana** [comment]
Thanks for the results @thorerik - we will get back to you.

**Comment by harshavardhana** [comment]
@thorerik we did some testing and don't see the performance to be consistent with our tests. We performed our tests on hyper.sh L3 instances 

https://gist.github.com/harshavardhana/415e6e73bc2cde0535ba6a435ef453d1

We see around 400 obj/sec - here is the test script we are using https://github.com/donatello/minio-perftest/blob/master/uploadsperftest.go

Our configuration was a 4 storage server with 50GB disks providing around 100MB/sec uncached disk performance. 

Can you please run `uploadsperftest.go` on your end and let us know the performance on your cluster?

**Comment by harshavardhana** [comment]
Also does the siege utility use S3 protocol ? - https://github.com/JoeDog/siege

**Comment by harshavardhana** [comment]
Also what is the RAM size on these nodes @thorerik ?

**Comment by pascalandy** [comment]
@thorerik I'm testing minio in distributed mode and I can't get them to sync.
I'm using 4 nodes on scaleway. Of course, on each nodes I update $CTN_name. Can you help me find what's wrong. 

Looking at the docs, https://docs.minio.io/docs/distributed-minio-quickstart-guide it is not clear yet for me.

```
CTN_name=minioN01
#
export MINIO_ACCESS_KEY=ncaksnc09ashcaknsc9
export MINIO_SECRET_KEY=98h24g982h4g089h2
#
mkdir -p /mnt/minio/export/$CTN_name
mkdir -p /mnt/minio/config/$CTN_name
#
docker run -d \
-p 9000:9000 --name $CTN_name \
-e "MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY" \
-e "MINIO_SECRET_KEY=$MINIO_SECRET_KEY" \
-v /mnt/minio/export/$CTN_name:/export \
-v /mnt/minio/config/$CTN_name:/root/.minio \
minio/minio server \
http://10.4.999.155/dev/vda \
http://10.4.999.207/dev/vda \
http://10.4.999.139/dev/vda \
http://10.4.999.15/dev/vda
```

Thank you!

**Comment by harshavardhana** [comment]
@pascalandy Please visit us on https://gitter.im/minio/minio for these questions.  This bug is related to some performance problems.

Also for docker you need to use swarm or kubernetes networking to get distributed working properly or use `--net="host"`   (not recommended since this can make your container run in privileged mode)

**Comment by pascalandy** [comment]
You are right @harshavardhana, I should have went to gitter. See you there :)

**Comment by aidabeorn** [comment]
Sorry for the late reply @harshavardhana, haven't had time to poke at this again before now.

Some quick tests I didn't think to do prior:
at a concurrency of 50, I see expected performance;
```
** SIEGE 3.0.8
** Preparing 50 concurrent users for battle.
The server is now under siege...
Lifting the server siege...      done.

Transactions:                  81359 hits
Availability:                 100.00 %
Elapsed time:                  59.23 secs
Data transferred:             293.60 MB
Response time:                  0.04 secs
Transaction rate:            1373.61 trans/sec
Throughput:                     4.96 MB/sec
Concurrency:                   49.78
Successful transactions:       81359
Failed transactions:               0
Longest transaction:            1.04
Shortest transaction:           0.00
```

but once I crank it closer to our expected peak (200-250 concurrent), things fall appart:
```
** SIEGE 3.0.8
** Preparing 250 concurrent users for battle.
The server is now under siege...
Lifting the server siege...      done.

Transactions:                  14835 hits
Availability:                 100.00 %
Elapsed time:                  60.01 secs
Data transferred:              53.54 MB
Response time:                  0.98 secs
Transaction rate:             247.21 trans/sec
Throughput:                     0.89 MB/sec
Concurrency:                  241.10
Successful transactions:       14835
Failed transactions:               0
Longest transaction:           15.93
Shortest transaction:           0.00
```

edit:
just as a (shoddy)comparison, nginx serving it's default page through the same LB (mostly to clear the LB of fault):
```
** SIEGE 3.0.8
** Preparing 250 concurrent users for battle.
The server is now under siege...
Lifting the server siege...      done.

Transactions:                 203703 hits
Availability:                 100.00 %
Elapsed time:                  59.32 secs
Data transferred:              74.60 MB
Response time:                  0.07 secs
Transaction rate:            3433.97 trans/sec
Throughput:                     1.26 MB/sec
Concurrency:                  244.47
Successful transactions:      203705
Failed transactions:               0
Longest transaction:            1.19
Shortest transaction:           0.00
```

**Comment by deekoder** [comment]
@hackintoshrao  ask for remote access.

**Comment by hackintoshrao** [comment]
@thorerik : Will it be possible to get access to the machine to investigate this further?

**Comment by deekoder** [comment]
@thorerik  - please reactivate this issue if you think its not addressed by us. Since we are unable to reproduce this on our end, we would love to see this issue on your end.
