### ISSUE TITLE
Post policy-based upload disrespects Content-Encoding header 

### ISSUE THREAD

**Issue by bsideup** [minio/minio#3473]
## Expected Behavior
File uploaded thru the form with `Content-Encoding: gzip` should store the file with `Content-Encoding: gzip` header. 

## Current Behavior
`Content-Encoding: gzip` is ignored.

## Possible Solution
Store it :)

## Steps to Reproduce (for bugs)
1. Use Form-based upload with POST policy and "Content-Encoding: gzip" form field
2. Upload the file
3. Check returned `Content-Encoding` header, it will be missing

## Context
We store our data compressed to reduce the cost of the storage and bandwidth, so we force gzip compression.

## Your Environment
Latest Minio Docker image (edge)

**Comment by vadmeste** [comment]
I am taking this

**Comment by bsideup** [comment]
@vadmeste :+1: thanks!
