### ISSUE TITLE
server: Start time sanity check across all servers

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3475]
Create a new ServerInfo() RPC call to query all its neighbors to check for sane environment. 

- Architecture (OS and ARCH has to match)
- cmdline (CLI Args)

## Expected Behavior
We need to verify if all servers in a distributed setup are sane. 

## Current Behavior
No verification done can lead to corrupted state.

## Possible Solution
Explained above.

## Steps to Reproduce (for bugs)
Bringing any servers with any of the above environments can cause issues.

## Context
Sane environment check is needed and is an important check before we proceed to initialize object layer.

## Your Environment
Current master.

**Comment by GarimaKapoor** [comment]
@vadmeste is this issue still work in progress

**Comment by harshavardhana** [comment]
Actually @balamurugana is working on a related issue.

**Comment by harshavardhana** [comment]
ping @balamurugana

**Comment by deekoder** [comment]
Moving this to next milestone since this involves several moving parts that need to be changed eg #3970

**Comment by harshavardhana** [comment]
This change is necessary starting with change https://github.com/minio/minio/pull/5420 @donatello @nitisht

**Comment by harshavardhana** [comment]
config has moved to backend so all servers are always going to be same, closing this as not needed anymore.
