### ISSUE TITLE
multi hosts Distributed docker-compose.yml

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3485]
How to write for each docker-compose.yml for multi hosts(four hosts)?
Is the following right ? {2,3,4} is for other three docker-compose.yml
version: '2'

# starts one docker container running minio server instances on each host. 1{2,3,4}

services:
  minio1{2,3,4}:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio1{1,2,3,4}:/export
      
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address 192.168.0.11:9000/export 192.168.0.12:9000/export 192.168.0.13:9000/export 192.168.0.14:9000/export

volumes:
  minio1{2,3,4}:
    external:
      name: minio1{2,3,4}

**Comment by harshavardhana** [comment]
Docker compose doesn't support multi host,  here is a sample kubernetes config - https://gist.github.com/NitishT/ded3bd58e1269c6490c07547cb3ab066

**Comment by harshavardhana** [comment]
> Docker compose doesn't support multi host, here is a sample kubernetes config - https://gist.github.com/NitishT/ded3bd58e1269c6490c07547cb3ab066

Closing as answered.
