### ISSUE TITLE
Is datadir useful ?

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3490]
Is datadir usefull in mirror example ?

#!/bin/bash
datadir="/home/minio/minio1-data/"
minio2="minio2/mbucket"
MC_PATH="/home/minio/mc"
$MC_PATH --quiet  mirror --force $minio1 $minio2

**Comment by koolhead17** [comment]
@goodforever what is ``$minio1``, did you miss defining it? Also what are you trying to achieve?

**Comment by harshavardhana** [comment]
> datadir="/home/minio/minio1-data/"

are you trying to configure this one? - https://github.com/minio/minio/blob/master/docs/setup-replication-between-two-sites-running-minio.md @goodforever

**Comment by harshavardhana** [comment]
I think the doc is buggy.. /cc @koolhead17

**Comment by koolhead17** [comment]
ooh. let me quickly test and fix it.

**Comment by goodforever** [comment]
@harshavardhana Yes, waiting  @koolhead17 fix

**Comment by koolhead17** [comment]
@goodforever 

It should be
```
datadir="/home/ubuntu/minio1-data/"
minio2="minio2/mbucket"
MC_PATH="/home/ubuntu/work/bin/mc"
$MC_PATH --quiet  mirror --force $datadir $minio2
```
The example takes minio data directory and mirrors it to remote minio server bucket name ``mbucket``. I will fix it in the doc, thanks again.  Also ``MC_PATH`` will depend on local setup.

Also we have introduced ``mc mirror -w`` command, It will continuously watch for changes on a local directory and mirror the changes https://docs.minio.io/docs/minio-client-complete-guide#mirror

**Comment by goodforever** [comment]
@koolhead17 
if I mirror minio1/mbucket to minion/mbucket ,  Do I setup in following ?
minio1=minio1/mbucket
minio2=minio2/mbucket
MC_PATH="/home/ubuntu/work/bin/mc"
$MC_PATH --quiet  mirror --force $minio1  $minio2

**Comment by goodforever** [comment]
@koolhead17 mc mirror -w is better than --force for me  , thanks !

**Comment by harshavardhana** [comment]
> @koolhead17 mc mirror -w is better than --force for me , thanks !

Closing.. @koolhead17 can you remove these stale docs?

**Comment by koolhead17** [comment]
sure @harshavardhana
