### ISSUE TITLE
Stops uploading "Error occurred uploading"

### ISSUE THREAD

**Issue by zorenleolumosbog** [minio/minio#3497]
Stops uploading error pop up says "Error occurred uploading".

**Comment by harshavardhana** [comment]
Can you share more details like server version, operating system ? Were you using browser ?  Also can you use the GitHub issue template to describe the issue that occurred. It is easier for us for quick turn around to not ask repeated questions.

**Comment by zorenleolumosbog** [comment]
Okay sorry for that Sir, these are the following:
**For Server Side**
VERSION
2016-12-13T17:19:42Z
MEMORY
i3 Processor 4GB RAM
Used: 18 MB | Allocated: 1.2 GB | Used-Heap: 18 MB | Allocated-Heap: 38 MB
PLATFORM
OS: Windows 10 32bit
RUNTIME
Version: go1.7.3 | CPUs: 4
INTERNET SPEED
100 Mbps

**For Client Side**
Browser: Any Kind
OS: Windows XP and later
Internet Upload Speed 1 Mbps only

Its stops uploading and after I've an error that pop up says "Error occurred uploading". I've tried other internet connection with upload speed of 1 Mbps and it can upload successfully. I can't say the problem was the ISP because I've tried to upload on 4shared and it can upload successfully.

**Comment by harshavardhana** [comment]
> Its stops uploading and after I've an error that pop up says "Error occurred uploading". I've tried other internet connection with upload speed of 1 Mbps and it can upload successfully. I can't say the problem was the ISP because I've tried to upload on 4shared and it can upload successfully.

Do you see any errors on the server logs?

**Comment by harshavardhana** [comment]
@zorenleo were you able to see any error on the server logs?

**Comment by zorenleolumosbog** [comment]
There is no any error on the server logs. I think it is the internet connections fault since the current connection on the client side is not stable at all. It will get an error when the connection stops but when it comes backup it can't continue uploading since the connection gets interrupted.

**Comment by harshavardhana** [comment]
Yeah that is expected from browser uploads you should  look at https://github.com/minio/mc for resumable uploads. Upon network disconnection mc will write session for resuming in future.

**Comment by zorenleolumosbog** [comment]
Alright I should have to use it. Thank you.
