### ISSUE TITLE
[shared-fs] - Multipart upload fails with internal error

### ISSUE THREAD

**Issue by krisis** [minio/minio#3500]
Shared backend test binary was used. A single instance of minio server was started listening on port ``9001``. A multipart upload was performed using minio-py SDK.

## Expected Behavior

Multipart upload should complete successfully.

## Current Behavior

Multipart upload failed with internal error.

Server log:
```
ERRO[1008] Unable to complete multipart upload.          cause=EOF source=[object-handlers.go:767:objectAPIHandlers.CompleteMultipartUploadHandler()]
```

## Possible Solution

Not known

## Steps to Reproduce (for bugs)

1. Perform a multipart upload
2. Fails with internal error

## Context

This issue prevents a multipart upload of a large object.
## Your Environment

* Version used: 
```
Version: 2016-12-27T00:13:46Z
Release-Tag: RELEASE.2016-12-27T00-13-46Z
Commit-ID: fb607946840505d95beea4ebcba26c73793278b1
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: - 
* Operating System and version: Ubuntu Xenial
* Link to your project: -

**Comment by harshavardhana** [comment]
Fixed in latest push, building a new binary..

**Comment by harshavardhana** [comment]
Uploaded new binary..

**Comment by harshavardhana** [comment]
@krisis did you test this ?

**Comment by harshavardhana** [comment]
Closing this as fixed @krisis - please re-open if seen again.
