### ISSUE TITLE
fs locking issue

### ISSUE THREAD

**Issue by bweston92** [minio/minio#3503]
## Context
Frequently I'm hitting an issue with my Docker registry using Minio as a back end. I don't know if to many things are accessing this data at once or what but even the Minio UI doesn't respond.

## Your Environment

* Version used: 2016-10-24T21:23:47Z (048af5e5cdc1344e83231c09079828a3d289e6df)
* Environment name and version (e.g. nginx 1.9.1): nginx 1.6.2
* Server type and version: Standalone.
* Operating System and version: Debian 8
* Link to your project:

```
strace -p 775
Process 775 attached
futex(0xee8890, FUTEX_WAIT, 0, NULL
```

```
 time strace -p 775
Process 775 attached
futex(0xee8890, FUTEX_WAIT, 0, NULL^CProcess 775 detached
 <detached ...>

real    0m32.808s
user    0m0.000s
sys    0m0.000s
```

**Comment by harshavardhana** [comment]
> ersion used: 2016-10-24T21:23:47Z (048af5e)
> Environment name and version (e.g. nginx 1.9.1): nginx 1.6.2
> Server type and version: Standalone.
> Operating System and version: Debian 8

@bweston92 can you try the latest version and see if it has the same issue? we have fixed quite a few issues after the release you are using.

**Comment by harshavardhana** [comment]
@bweston92 were you able to validate with latest version?

**Comment by bweston92** [comment]
@harshavardhana I've upgraded and will get back to you if it locks up any time soon.

**Comment by harshavardhana** [comment]
> @harshavardhana I've upgraded and will get back to you if it locks up any time soon.

Thanks please keep us updated.

**Comment by harshavardhana** [comment]
@bweston92 is there anything that you observed after upgrading?

**Comment by bweston92** [comment]
The system is not under the same stress as one holiday at the minute :p will get back to you

**Comment by harshavardhana** [comment]
> The system is not under the same stress as one holiday at the minute :p will get back to you

Thanks @bweston92

**Comment by harshavardhana** [comment]
Hey @bweston92 just checking back to see if things are going well. Let us know.

**Comment by bweston92** [comment]
Seems to be fixed, thanks.
