### ISSUE TITLE
mc mirror -w is valid for add file   ,but invalid for mc rm file

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3505]
mc mirror -w minio2/mybucket minio1/mybucket
mc cp test.txt minio2/mybucket  , you can see minio1/mybucket/test.txt
mc rm minio2/mybucket/test.txt , but the   minio1/mybucket/test.txt is not removed

**Comment by vadmeste** [comment]
@goodforever, hello. You need to use --delete parameter in mc mirror command. That will remove files when needed in mirroring.

**Comment by harshavardhana** [comment]
> @goodforever, hello. You need to use --delete parameter in mc mirror command. That will remove files when needed in mirroring.

Closing as answered.
