### ISSUE TITLE
bucket-policy: read policy on prefix should allow listing

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3513]
Enable READ policy on a prefix
```
krishna@escape:~$ mc policy download myminio/test/a/b
Access permission for ‘myminio/test/a/b’ is set to ‘download’
krishna@escape:~$
```

Try unauthenticated listing:
```
krishna@escape:~$ curl localhost:9000/test/a/b
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/test/a/b</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
krishna@escape:~$
```

This should work. (works fine on the bucket root)

## Expected Behavior

Listing on READ enabled prefix should work.

## Current Behavior

Listing on READ enabled prefix fails.

**Comment by harshavardhana** [comment]
This is a bug in the client i think, look at the `policy.json` file if it has a '/' in it. Server will only interpret the exact `policy.json`.

**Comment by harshavardhana** [comment]
were you able to verify `policy.json` does it have "/" or not @krishnasrinivas ?

**Comment by harshavardhana** [comment]
> krishna@escape:~$ curl localhost:9000/test/a/b
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/test/a/b</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
> krishna@escape:~$

This works fine actually what you are doing is wrong - you can't list on a bucket as resources, you list with a query param. 

```
$ curl localhost:9000/testbucket?prefix=a%2Fb
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>testbucket</Name><Prefix>a/b</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>
```

```
$ curl localhost:9000/testbucket/a/b/issue
Ubuntu 16.04.1 LTS \n \l
```
