### ISSUE TITLE
[shared-fs] 10 parallel `mc cp` of same file fails with `500 Internal Server Error`

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#3523]
## Steps to Reproduce (for bugs)

1. run `for (( i = 0; i < 10; i++ )); do mc cp sample-Elysium.2013.2160p.mkv m1testbin/mybucket/1.mkv& done`
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment]
Uploaded new binaries fixing this issue, closing.

```
for (( i = 0; i < 100; i++ )); do mc cp --debug ~/Downloads/bigfile myminio/testbucket/2 & done
```

@balamurugana please proceed with further testing.
