### ISSUE TITLE
Tag RELEASE.2016-10-07T01-16-39Z not found in repository docker.io/minio/minio

### ISSUE THREAD

**Issue by HaraldNordgren** [minio/minio#3524]
I started getting this behavior today when pulling the Minio docker image. We have been using this locked version for a while:

```
Pulling minio (minio/minio:RELEASE.2016-10-07T01-16-39Z)...
Pulling repository docker.io/minio/minio
ERROR: Tag RELEASE.2016-10-07T01-16-39Z not found in repository docker.io/minio/minio
```

**Comment by harshavardhana** [comment]
@HaraldNordgren those releases were built wrongly so we had to purge them, please upgrade to the latest release.

**Comment by HaraldNordgren** [comment]
Are there detailed changelogs available?

**Comment by harshavardhana** [comment]
> Are there detailed changelogs available?

The changelogs are available here - https://github.com/minio/minio/releases/tag/RELEASE.2016-12-12T18-35-43Z

**Comment by harshavardhana** [comment]
Closing.. as stated.
