### ISSUE TITLE
[shared-fs] Setting download policy doesn't work

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3525]
## Expected Behavior
`mc policy download myminio/testbucket` should make the bucket accessible via browser (http://localhost:9000/testbucket/)

## Current Behavior
http://localhost:9000/testbucket gives Access denied

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
1. Start shared minio from fresh export directory
2. mc mb myminio/testbucket/
3. mc policy download myminio/testbucket/
4. curl http://localhost:9000/testbucket => Access denied

## Context
Testing the shared backend

## Your Environment
All

**Comment by harshavardhana** [comment]
Can you access curl with http://localhost:9000/test bucket/

**Comment by vadmeste** [comment]
> Can you access curl with http://localhost:9000/test bucket/

No. It gives me Access denied. But I've just noticed that I can access after restarting the Minio server.

**Comment by harshavardhana** [comment]
Ah I think I know the problem.

**Comment by harshavardhana** [comment]
Fixed in the PR. @vadmeste

**Comment by vadmeste** [comment]
> Fixed in the PR. @vadmeste

:+1:, it works now.
