### ISSUE TITLE
[shared-fs] Uploading a 10Gb object fails.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3528]
With Shared FS servers on top of GlusterFS, with 2 servers each on 2 nodes,
Uploading a 10GB object using aws-cli fails.

## Expected Behavior

For copy to succeed.
## Current Behavior

The copy fails with the following error, 

```
upload failed: ../10gb to s3://test/10gbe(s) remaining
A server error (InternalError) occurred when calling the UploadPart operation: We encountered an internal error, please try again.
```
## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Run GlusterFS across 2 nodes.
2. Run 2 shared backend on each node using the Gluster FS common backend.
3. Use HAProxy to load balance across 4 servers.
4. use aws-cli (pointing to proxy) to upload a 10GB object.

## Context

Testing the shared FS backend.
## Your Environment

* Version used: 
```
Version: 2017-01-04T07:22:10Z
Release-Tag: RELEASE.2017-01-04T07-22-10Z
Commit-ID: cefb3d4952c34dc78d1423e386469fcb06045ce7
```
* Environment name and version (e.g. nginx 1.9.1): Minio M2 and M3 servers (Linux 4..4.-31)

**Comment by krisis** [comment]
@hackintoshrao did you find any logs of interest in glusterfs servers?

**Comment by hackintoshrao** [comment]
Here is the log from Minio server when the error occurred, 

```
Handler api-router.go:44:(objectAPIHandlers).PutObjectPartHandler-fm
ERRO[0185] Unable to create object part.                 cause=unexpected end of JSON input source=[object-handlers.go:641:objectAPIHandlers.PutObjectPartHandler()] stack=fs-v1-metadata.go:160:(*fsMetaV1).ReadFrom fs-v1-multipart.go:456:fsObjects.PutObjectPart <autogenerated>:228:(*fsObjects).PutObjectPart object-handlers.go:638:objectAPIHandlers.PutObjectPartHandler api-router.go:44:(objectAPIHandlers).PutObjectPartHandler-fm
ERRO[0199] Unable to create object part.                 cause=unexpected end of JSON input source=[object-handlers.go:641:objectAPIHandlers.PutObjectPartHandler()] stack=fs-v1-metadata.go:160:(*fsMetaV1).ReadFrom fs-v1-multipart.go:456:fsObjects.PutObjectPart <autogenerated>:228:(*fsObjects).PutObjectPart object-handlers.go:638:objectAPIHandlers.PutObjectPartHandler api-router.go:44:(objectAPIHandlers).PutObjectPartHandler-fm
ERRO[0199] Unable to create object part.  
```

**Comment by harshavardhana** [comment]
Looks like the issue is sync operation related. Data is not persisted and there is a garbage data on backend.

**Comment by hackintoshrao** [comment]
Basically unmarshalling of `fs.json` failed. Not sure why.

**Comment by harshavardhana** [comment]
> Basically unmarshalling of fs.json failed. Not sure why.

Is the data on disk? @hackintoshrao i.e `fs.json`

**Comment by hackintoshrao** [comment]
Yes, it is there. @krisis  was able to unmarshal from a separate program and it was intact.

**Comment by harshavardhana** [comment]
> Yes, it is there. @krisis was able to unmarshal from a separate program and it was intact.

Hmm looks interesting can this be consistently reproduced?

**Comment by hackintoshrao** [comment]
Yes, able to produce consistently.

**Comment by harshavardhana** [comment]
Will take a look its on m2 @hackintoshrao ?

**Comment by hackintoshrao** [comment]
Yes, You can join the session and ping me on gitter.

**Comment by harshavardhana** [comment]
This is fixed with the latest PR. @hackintoshrao 

```
$ aws --endpoint-url http://minio2 s3 cp ~/10gb  s3://test3/1                                                               
upload: ../10gb to s3://test3/1    
```
