### ISSUE TITLE
[shared-fs] `PutObjectReadAt` from exec-concurrent tests fails. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3529]
`PutObjectReadAt` from exec-concurrent tests fails on shared backend test. 
The setup same as used in https://github.com/minio/minio/issues/3528.

## Expected Behavior

- Expected the test to pass.
## Current Behavior

Fails with the following error, 

```
Goroutine: 1
--- FAIL: TestPutObjectReadAt (2.94s)
        api_functional_v4_test.go:214: Error: Put http://127.0.0.1/minio-go-test4cbyi3pjnuso3dib2/dec0y3yj2mohiz3aqv63lqgtputukg?partNumber=2&uploadId=8aed0c50-52d3-4b4b-a6d4-6b29eb49927f: http: ContentLength=67108864 with Body length 0 minio-go-test4cbyi3pjnuso3dib2 dec0y3yj2mohiz3aqv63lqgtputukg
--- FAIL: TestPutObjectWithMetadata (2.91s)
        api_functional_v4_test.go:300: Error: Put http://127.0.0.1/minio-go-test1z9l9mrazowhajkc2/qnau0i4riifyqa291o9qkvn19rtq6c?partNumber=2&uploadId=5d9b9767-9353-447c-a143-3e4a7b05ccbd: http: ContentLength=67108864 with Body length 0 minio-go-test1z9l9mrazowhajkc2 qnau0i4riifyqa291o9qkvn19rtq6c
FAIL
```

## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Get the setup as mentioned in https://github.com/minio/minio/issues/3528.
2. Run the [exec-concurrent](https://github.com/minio/perftest/tree/master/exec-concurrent) test.

## Context

Testing the shared backend.
## Your Environment

* Version used:
```
Version: 2017-01-04T07:22:10Z
Release-Tag: RELEASE.2017-01-04T07-22-10Z
Commit-ID: cefb3d4952c34dc78d1423e386469fcb06045ce7
```

**Comment by harshavardhana** [comment]
Can you validate if this is true still @hackintoshrao ?

**Comment by hackintoshrao** [comment]
Will validate this.

**Comment by harshavardhana** [comment]
Is this reproducible @hackintoshrao ?

**Comment by hackintoshrao** [comment]
Not able to reproduce this.

**Comment by harshavardhana** [comment]
> Not able to reproduce this.

Cool @hackintoshrao
