### ISSUE TITLE
[fs]: Unexpected result when the request contains double slash.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3530]
HTTP requests with double results in unexpected result.

For example request with invalid bucket name, but with an extra slash results in `ListAllBucket` operation. `http://127.0.0.1:9000//getobjecterrors-./test-non-exitent-object`

## Expected Behavior

- To detect the double slash and behave accordingly or throw an error.
## Current Behavior

Results in `ListBucket` operation.
## Possible Solution

Have to checked while parsing the URL.
## Steps to Reproduce (for bugs)

1. wget https://gist.githubusercontent.com/hackintoshrao/ee970e53f7d45956f6e655b12dfa38c2/raw/7e66797dd28cac1f84e7ab8c53e192c34047cff7/dist_func_test.go
2. Run Minio FS locally.
3. export S3_ENDPOINT=http://127.0.0.1
    export ACCESS_KEY=<ACCESS_KEY>
    export SECRET_KEY=<SECRET_KEY>
4. go test -run=TestGetObjectErrors . 

`TestGetObjectErrors` send an additional slash in the request, which fails the test.

## Your Environment

* Version used: Minio latest master @  c8f57133a4384ea98206560b691f50e7520007b9
* Environment name and version (e.g. nginx 1.9.1):OSX ElCapitan

**Comment by harshavardhana** [comment]
Gorilla mux strips all the extraneous slash so minio server never received the slash which is sent by the client

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/issues/3256 @hackintoshrao here is the fix related.

**Comment by harshavardhana** [comment]
Actually it was agreed that we will strip the extraneous slashes, so this is expected since it causes problems with signature etc.

**Comment by hackintoshrao** [comment]
Closing the issue since this is expected.
