### ISSUE TITLE
[shared-fs] fcntl + delete causes problems

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3531]
fcntl based synchronization relies on the fact that underlying inode number of a name space entry never changes. But since we do delete of fs.json/uploads.json fcntl locking is not reliable.

For ex consider a race between DeleteObject on minio1 and PutObject on minio2:
minio1 opens fs.json and does lock(fd) and gets lock
minio2 opens the same fs.json and blocks on lock(fd)
minio1 deletes deletes fs.json and unlock(fd)
minio2 now gets the lock and writes to the fd whose fs.json which was deleted in the namespace.

i.e PutObject's fs.json is lost.

If a 3rd minio server (minio3) PutObject races in addition, then we can have a situation such that metadata is from minio3 but the object content is from minio2.

**Comment by harshavardhana** [comment]
Closing this since its a documented behavior in the patch.
