### ISSUE TITLE
Create a basic health/status endpoint for monitoring/probing

### ISSUE THREAD

**Issue by counterbeing** [minio/minio#3532]
## Expected Behavior
I'd like to see an endpoint that could be fetched as `GET /minio/health` that would simply return a status code of `200` or an error code. 

## Current Behavior
I'm currently using the path to the svg icon for health checks. It doesn't tell me about wether or not it's ready to accept requests. 

## Context
A lot of my assets are additive, just meaning, I don't remove them often, just add more. As such, a varnish cache seems to provide a great deal better performance. Varnish wants to probe the back end every few seconds, and my current method doesn't actually tell me wether or not the service is truly up. Also, given the frequency of probes, I'd like those requests to go through with as little overhead as possible.

## Your Environment
I'm using docker containers with Kontena. I'm using a varnish container in front of my minio instances.

**Comment by harshavardhana** [comment]
You can simply probe /minio/index.html

**Comment by counterbeing** [comment]
Works for me. I'm not that sure how varnish works, but I bet it doesn't bother checking anything other than the status code. 

Cheers!

**Comment by prein** [comment]
/minio/index.html returns `HTTP/1.1 403 Forbidden`. I don't see how that would be useful for a healthcheck. I would prefer not to make healthcheck configuration come with credentials.

**Comment by roffe** [comment]
@prein I do the healthcheck on exactly that. 
If it returns 403 that means minio is up and running
