### ISSUE TITLE
api: Unable to set user metadata and content-type when uploading with POST policy

### ISSUE THREAD

**Issue by kallqvist** [minio/minio#3534]
I'm trying to send a file using minio python and presigned post policy.
I'm also trying to add a custom metadata value at the time of post policy generation by modifying the object before signing it.

The file upload and validation of the policy during upload goes through fine without error and the file is available in minio browser.

My problem is that the metadata and content-type **doesn't seem to be saved**.

Upload is done using a preflight request to backend for presigned policy and in the browser I have ajax requests in custom code (no access keys are available to browser).

For the sake of reproducing my issue I'm sending the file with curl in this example since that is giving me the exact same results.

The signed policy looks like this:
```
[
  "http://minio:9000/video/", 
  {
    "x-amz-algorithm": "AWS4-HMAC-SHA256", 
    "key": "filename.txt", 
    "x-amz-date": "20170105T154246Z", 
    "bucket": "video", 
    "x-amz-signature": "96e0a7017da6c13e7e44b287e852ee81935ff0c1c3ac70354c5616edf5acf40c", 
    "x-amz-meta-testing": "this-is-the-test-value", 
    "policy": "eyJjb25kaXRpb25zIjogW1siZXEiLCAiJGJ1Y2tldCIsICJ2aWRlbyJdLCBbImVxIiwgIiRrZXkiLCAiZmlsZW5hbWUudHh0Il0sIFsiZXEiLCAiJENvbnRlbnQtVHlwZSIsICJ0ZXh0L3BsYWluIl0sIFsiZXEiLCAiJHgtYW16LW1ldGEtdGVzdGluZyIsICJ0aGlzLWlzLXRoZS10ZXN0LXZhbHVlIl0sIFsiZXEiLCAiJHgtYW16LWRhdGUiLCAiMjAxNzAxMDVUMTU0MjQ2WiJdLCBbImVxIiwgIiR4LWFtei1hbGdvcml0aG0iLCAiQVdTNC1ITUFDLVNIQTI1NiJdLCBbImVxIiwgIiR4LWFtei1jcmVkZW50aWFsIiwgImFhYWFhLzIwMTcwMTA1L3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QiXV0sICJleHBpcmF0aW9uIjogIjIwMTctMDEtMDZUMTU6NDI6NDYuMDAwWiJ9", 
    "x-amz-credential": "aaaaa/20170105/us-east-1/s3/aws4_request", 
    "Content-Type": "text/plain"
  }
]
```

The curl request generated from this data (using the example code in minio docs) like this:
```
curl -X POST http://minio:9000/video/ -F x-amz-algorithm=AWS4-HMAC-SHA256 -F key=filename.txt -F x-amz-date=20170105T154246Z -F bucket=video -F x-amz-signature=96e0a7017da6c13e7e44b287e852ee81935ff0c1c3ac70354c5616edf5acf40c -F x-amz-meta-testing=this-is-the-test-value -F policy=eyJjb25kaXRpb25zIjogW1siZXEiLCAiJGJ1Y2tldCIsICJ2aWRlbyJdLCBbImVxIiwgIiRrZXkiLCAiZmlsZW5hbWUudHh0Il0sIFsiZXEiLCAiJENvbnRlbnQtVHlwZSIsICJ0ZXh0L3BsYWluIl0sIFsiZXEiLCAiJHgtYW16LW1ldGEtdGVzdGluZyIsICJ0aGlzLWlzLXRoZS10ZXN0LXZhbHVlIl0sIFsiZXEiLCAiJHgtYW16LWRhdGUiLCAiMjAxNzAxMDVUMTU0MjQ2WiJdLCBbImVxIiwgIiR4LWFtei1hbGdvcml0aG0iLCAiQVdTNC1ITUFDLVNIQTI1NiJdLCBbImVxIiwgIiR4LWFtei1jcmVkZW50aWFsIiwgImFhYWFhLzIwMTcwMTA1L3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QiXV0sICJleHBpcmF0aW9uIjogIjIwMTctMDEtMDZUMTU6NDI6NDYuMDAwWiJ9 -F x-amz-credential=aaaaa/20170105/us-east-1/s3/aws4_request -F Content-Type=text/plain -F file=@filename.txt
```

Decoding the generated policy value from base64 gives this result:
```
{
  "conditions": [
    [
      "eq",
      "$bucket",
      "video"
    ],
    [
      "eq",
      "$key",
      "filename.txt"
    ],
    [
      "eq",
      "$Content-Type",
      "text/plain"
    ],
    [
      "eq",
      "$x-amz-meta-testing",
      "this-is-the-test-value"
    ],
    [
      "eq",
      "$x-amz-date",
      "20170105T154246Z"
    ],
    [
      "eq",
      "$x-amz-algorithm",
      "AWS4-HMAC-SHA256"
    ],
    [
      "eq",
      "$x-amz-credential",
      "aaaaa/20170105/us-east-1/s3/aws4_request"
    ]
  ],
  "expiration": "2017-01-06T15:42:46.000Z"
}
```

So far all is good; executing the curl goes through without any errors and the uploaded file appears in minio browser.
Changing any of the values (including my custom x-amz-meta-testing) return 403 as expected.
This leads me to believe that issue isn't in minio-py or the way my policy is generated.

When checking the generated filename.txt/fs.json there is no metadata other than md5Sum.

```
{"version":"1.0.0","format":"fs","minio":{"release":"RELEASE.2016-12-13T17-19-42Z"},"meta":{"md5Sum":"14799e99d840a4ce60fe6fa9d7d0551a"}}
```

## Expected Behavior
Content-type and x-amz-meta-testing should have values set in fs.json

## Current Behavior
Only md5Sum is set. (However; files uploaded in minio browser have both md5Sum and content-type)

## Possible Solution
-

## Steps to Reproduce (for bugs)
I'm attaching a simplified python-script for generating the presigned policy and curl command I've explained in this post.
minio-py is latest released version.

[presigned.py.txt](https://github.com/minio/minio/files/687672/presigned.py.txt)
```
pip install minio==2.0.5
mv presigned.py.txt presigned.py
python presigned.py
# execute the curl command from python output and check generated fs.json
```

## Context
I'm trying to let users that have an API-key and/or active session to my backend generate presigned minio credentials for uploading files directly from browser to minio.

## Your Environment
Single node minio in docker using the minio:latest tag.

**Comment by kallqvist** [comment]
An interresting find is that if I also add the content-type as a header in the curl request (-H "Content-Type:text/plain" appended to curl command) will return 403 from minio.

Don't know why that is or if it's related to this in any way.

**Comment by harshavardhana** [comment]
> An interresting find is that if I also add the content-type as a header in the curl request (-H "Content-Type:text/plain" appended to curl command) will return 403 from minio.
> 
> Don't know why that is or if it's related to this in any way.

It will return 403 because the signature mismatches if you set additional headers which are not expected. Will check why POST policy is not saving metadata. 

Thanks for the bug @kallqvist

**Comment by krishnasrinivas** [comment]
@kallqvist you can use presigned PUT : https://docs.minio.io/docs/javascript-client-api-reference#presignedPutObject

and:
```
curl -X PUT "http://localhost:9000/test/passwd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=SXO8VW2OFKKP2OG7AC85%2F20170105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170105T192234Z&X-Amz-Expires=100000&X-Amz-SignedHeaders=host&X-Amz-Signature=f37303d6e78c98236e4505fc4e5cb8b72011dc36696dce21e176b47e8cebcdc5" -H "X-Minio-Meta-Test:123" --upload-file /etc/passwd
```

@harshavardhana for POST policy it expects the metadata to be in formData: bucket-handlers.go

```
449         // Extract metadata to be saved from received Form.                                                                                                                 
450         metadata := extractMetadataFromForm(formValues)     
```

**Comment by kallqvist** [comment]
@krishnasrinivas python-pi only implements presigned_post_policy.
https://github.com/minio/minio-py#api-reference--presigned-operations

I could create the api request from python for presign put myself but would prefer to use the minio python lib?

thanks for all the help and a great project btw, loving minio so far :)

**Comment by harshavardhana** [comment]
// cc @vadmeste - have you seen this before?

**Comment by krishnasrinivas** [comment]
@kallqvist presigned PUT is implemented as well here is the api doc:
https://docs.minio.io/docs/python-client-api-reference#presigned_put_object

**Comment by kallqvist** [comment]
@krishnasrinivas Yes, but I also want to add and require that my custom meta fields are set in the signature generated.

I'm currently doing it like this with the post policy:
```
post_policy.__dict__["form_data"]["x-amz-meta-userid"] = str(uploaded_by_user_id)
post_policy.__dict__["policies"].append(("eq", "$x-amz-meta-userid", str(uploaded_by_user_id)))
```

I don't think I can add my custom meta fields or headers to presigned_put_object before the policy is signed?

**Comment by krishnasrinivas** [comment]
@kallqvist for the presigned PUT generated by our API only host header needs to be signed. For example you can notice that the following commands succeeds:

```
krishna@escape:~$ curl -X PUT "http://localhost:9000/test/passwd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=SXO8VW2OFKKP2OG7AC85%2F20170105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170105T192234Z&X-Amz-Expires=100000&X-Amz-SignedHeaders=host&X-Amz-Signature=f37303d6e78c98236e4505fc4e5cb8b72011dc36696dce21e176b47e8cebcdc5" -H "X-Minio-Meta-Test:123" --upload-file /etc/passwd
krishna@escape:~$ jq . export/.minio.sys/buckets/test/passwd/fs.json
{
  "version": "1.0.0",
  "format": "fs",
  "minio": {
    "release": "DEVELOPMENT.GOGET"
  },
  "meta": {
    "X-Minio-Meta-Test": "123",
    "md5Sum": "73c2ee0acb590362c0ac3740f8c39523"
  }
}
krishna@escape:~$
```

here you can notice that metadata is saved even though it is not signed.

**Comment by kallqvist** [comment]
But the thing here is that I want it to be signed, I'm using it to store the user ID that owns the file in the meta and don't wan't the user to be able to change it from the browser upload request.

Or is it possible somehow to create a put signature that also includes the header using the minio library?

**Comment by krishnasrinivas** [comment]
for presigned-PUT and presigned-POST APIs we don't support metadata, you will have to use AWS client SDKs to generate it.

**Comment by kallqvist** [comment]
Got it, thanks!

But there is also a bug in the minio server here right?
I think it should be possible to add metadata also with a presigned-POST in the s3 specification?

**Comment by krishnasrinivas** [comment]
Minio server should already work fine, if it doesn't work let us know.

**Comment by harshavardhana** [comment]
Works fine on the current master 

```
$ curl -X POST http://localhost:9000/testbucket/ -F x-amz-algorithm=AWS4-HMAC-SHA256 -F key=filename.txt -F x-amz-date=20170106T181319Z -F bucket=testbucket -F x-amz-signature=d6f71bd6f11f9828e3b077aee15a79f0e094e7d257e76d0c75ce9b7625f1f82c -F x-amz-meta-testing=this-is-the-test-value -F policy=eyJleHBpcmF0aW9uIjoiMjAxNy0wMS0wN1QxODoxMzoxOS4wMDBaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwidGVzdGJ1Y2tldCJdLFsiZXEiLCIka2V5IiwiZmlsZW5hbWUudHh0Il0sWyJlcSIsIiRDb250ZW50LVR5cGUiLCJ0ZXh0L3BsYWluIl0sWyJlcSIsIiR4LWFtei1tZXRhLXRlc3RpbmciLCJ0aGlzLWlzLXRoZS10ZXN0LXZhbHVlIl0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAxNzAxMDZUMTgxMzE5WiJdLFsiZXEiLCIkeC1hbXotYWxnb3JpdGhtIiwiQVdTNC1ITUFDLVNIQTI1NiJdLFsiZXEiLCIkeC1hbXotY3JlZGVudGlhbCIsIlVTV1VYSEdZWlFZRllGRklUM1JFLzIwMTcwMTA2L3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QiXV19 -F x-amz-credential=USWUXHGYZQYFYFFIT3RE/20170106/us-east-1/s3/aws4_request -F Content-Type=text/plain -F file=@/etc/issue
```

```
 jq . ~/test/.minio.sys/buckets/testbucket/filename.txt/fs.json 
{
  "version": "1.0.0",
  "format": "fs",
  "minio": {
    "release": "DEVELOPMENT.2017-01-06T18-10-40Z"
  },
  "meta": {
    "X-Amz-Meta-Testing": "this-is-the-test-value",
    "content-type": "text/plain",
    "md5Sum": "1e7672cbc2f76c3e9daad0e290e711b9"
  }
}
```

```
$ mc cat --debug myminio/testbucket/filename.txt > /dev/null
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 26
Accept-Ranges: bytes
Content-Type: text/plain
Date: Fri, 06 Jan 2017 18:15:21 GMT
Etag: "1e7672cbc2f76c3e9daad0e290e711b9"
Last-Modified: Fri, 06 Jan 2017 18:13:34 GMT
Server: Minio/DEVELOPMENT.2017-01-06T18-10-40Z (linux; amd64)
Vary: Origin
X-Amz-Meta-Testing: this-is-the-test-value
X-Amz-Request-Id: QF7T062Z9V7CD5F2
```

**Comment by kallqvist** [comment]
I just tried the exact same code from my original issue but running minio from the image minio:edge in dockerhub and it works exactly as expected with no changes!

The problem still remain in minio:latest in dockerhub but that version is also 24 days older than minio:edge.

How often do you guys build and push the minio:latest tag? It looks to be about once a month?
I assume this would be resolved with the next stable release and I can use minio:edge in my dev environment instead for now so to me this issue is resolved.

I'll close the issue, big thanks for all your help! :)

**Comment by harshavardhana** [comment]
> How often do you guys build and push the minio:latest tag? It looks to be about once a month?
> I assume this would be resolved with the next stable release and I can use minio:edge in my dev environment instead for now so to me this issue is resolved.

We usually do quickly, for now we have an important feature that needs to be merged. @kallqvist  we will soon get it stable.
