### ISSUE TITLE
Previously working code stopped working... Put object fails: client.putObject(bucket, key, file).....

### ISSUE THREAD

**Issue by puneetpandey37** [minio/minio#3535]
## Expected Behavior

Upload the file....

## Current Behavior

I use AWS Java SDK and try to put an object to a Bucket as below
client.putObject(bucket, key, file)..... This worked before and suddenly stopped working.
Throws exception while uploading a file... but it still uploads that file...

I throws below exception:
"com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 7xPDVN7q6CL2eAl9aoZ9Xw== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3."

Below is Minio version:

Version: 2016-12-13T17:19:42Z
Release-Tag: RELEASE.2016-12-13T17-19-42Z
Commit-ID: 29d72b84c07f9555f83a6485fe8291e18d23811b

**Comment by harshavardhana** [comment]
> I throws below exception:
> "com.amazonaws.AmazonClientException: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: 7xPDVN7q6CL2eAl9aoZ9Xw== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3."

What is the aws-sdk-java version under use @puneetpandey37 ?

**Comment by puneetpandey37** [comment]
Hey it was indeed a version issue. My project used an older version of AWS SDK, I had updated the SDK and brought that to work... I pulled the code again and updated the SDK jar.... but the project was still referring to the older SDK... deleted all other versions and built it... And it works now! Thank!

**Comment by harshavardhana** [comment]
Thanks @puneetpandey10_twitter the issue was AWS Java SDK introduced a regression in one of the versions expecting case sensitive names in the response headers in your case it was "Etag" v/s "ETag" - which was in violation of HTTP RFC (client implementation) which was subsequently fixed. Response headers names are case insensitive in accordance with HTTP RFC.

**Comment by thasija** [comment]
@puneetpandey37  we are seeing this error when running hive insert statement , what version of sdk fixed the issue ?
