### ISSUE TITLE
Operation consistency model

### ISSUE THREAD

**Issue by uroni** [minio/minio#3536]
When I write to a minio bucket, what are the guarantees I have once the operation is finished?

I did sift a bit through the source code and found no calls to either fsync or fssync.

This is also something that should be added prominently to the documentation. E.g. "Minio is a distributed object storage server with eventual consistency". I may also have missed that bit.

**Comment by harshavardhana** [comment]
Sync and fsync only makes regular i/o synchronous and slow.  Minio writes data to the disk using regular read/write calls and is as durable as the underlying filesystem.  Minio guarantees strict read after write consistency model using [dsync](https://github.com/minio/dsync) locking and synchronization in distributed mode and regular RW mutex in standalone mode. 

Thanks for bringing this to our notice.  We will add this to distributed server documentation.

**Comment by uroni** [comment]
Ok, so no guarantee the data is durable. I need this for the use case (and it is something all other S3 implementations have btw.). Thanks for the answer!

**Comment by archenroot** [comment]
@harshavardhana - can there be something like check implemented that the written data has been written, so we can consider this durable, or there are no plans about it ... aka by design ?

**Comment by harshavardhana** [comment]
We have long implemented durability guarantees in Minio @archenroot @uroni 

- `xl.json` file is always written in the synchronous mode by default.
- individual shards are written in the synchronous mode when `MINIO_DRIVE_SYNC=on`  environment is set.

**Comment by archenroot** [comment]
@harshavardhana  - thx, just red some review (maybe 1 year old somewhere on reddit) where guys stated, don't use minio in favour of CEPH and others...:
https://news.ycombinator.com/item?id=16626993

So just wanted to double check as I am going to utilize Minio on my new project as RAW storage from which we can replay.

**Comment by uroni** [comment]
Thanks for `MINIO_DRIVE_SYNC`. I mounted the whole partition with `-o sync` when I used it, that should work as well.

It would be great, if the sync behaviour would be the default, because that is what people expect coming from AWS S3 etc.

**Comment by harshavardhana** [comment]
Even without sync, those guarantees are already there.  Minio writes erasure coding as the stream is written to disk without staging unlike other vendors. AWS S3 is eventually consistent for rewrites, Minio is strictly consistent for all PUTs. The durability guarantee is as close as your XFS behavior.

Sync is useful mainly when lots of small block I/O is being performed on XFS, Minio writes in large blocks for most objects.

This is one of the reason why we write `xl.json` the source of truth in our backend in sync mode, due to erasure coding logic we do have enough parities to reconstruct the data in case of any further failure.

If you are further paranoid when your files are smaller in the range of few KBs or your parity is smaller (on smaller setups) it is better to enable MINIO_DRIVE_SYNC additionally as well.

**Comment by uroni** [comment]
Sorry, there are a lot of conceptual issues with your post. Maybe I also misunderstood you?

I did not look into the erasure coding storage. Maybe minio is doing something different there? I'd guess most people use it with a single file system, but you probably have more data there.

Despite the title, this issue is mainly about durability. I.e., what happens if I upload some data, I get an OK back, and then the server crashes. Will I be able to retrieve the data? (without fsync/sync usually no)

The consistency is merely something other object storage servers differentiate on. AWS S3 has eventual consistency. Ceph radosgw has strong consistency. They all are durable.

You say "The durability guarantee is as close as your XFS behavior" (Is there a reason you are focusing on XFS?), but XFS has no durability unless you call fsync() or syncfs(). In fact, XFS often won't even allocate blocks (delayed allocation) and Linux will keep it in its buffer cache unless such a function is called (or a configurable amount of time expires).

XFS can afford to have no durability per default, because there are specific functions a programmer can call that make data durable (O_SYNC/fsync/syncfs). There is no such function in the S3 API because there every operation is durable.

> Sync is useful mainly when lots of small block I/O is being performed on XFS, Minio writes in large blocks for most objects.

Usually you want to call fsync() as rarely as possible, because Linux has to flush its buffer cache, the file system has to do some journaling, the disk has to flush its write buffer and this takes a lot of time (and on hard disks a lot of seeking). So it should be faster with larger blocks?
