### ISSUE TITLE
[shared-fs]: Mint test fails.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3539]
- [Mint](https://github.com/minio/mint) fails when run on shared backend with 2 servers on top of GlusterFS.
## Expected Behavior

- Test to pass.
## Current Behavior

- The test fails with the following error.

```
--- FAIL: TestPutObjectLongName (0.12s)
        server_test.go:304: Expected response code to be XMinioInvalidObjectName, got InternalError.
        server_test.go:307: Expected response Message to be Object name contains unsupported characters. Unsupported characters are `^*|\", got We encountered an internal error, ple
ase try again..
        server_test.go:310: Expected response status code to be 400, got 500.

--- FAIL: TestObjectMultipart (0.48s)
        server_test.go:4225: Put http://65.19.167.92/mhp45u2fpunxfvb5nx409vrcs9ampg4xi9ql06se0vfnx9pxxgray0xybnvk/: EOF
FAIL
 ```

## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1.Run 2 FS servers with shared on top of GlusterFS.
2. Setup HA Proxy for load balancing between them.
3. Build [Mint](github.com/minio/mint)
4. Run Mint `docker run -e S3_ADDRESS=65.xxx.xxx.92  -e ACCESS_KEY=xxxx  -e SECRET_KEY=xxxx  minio/mint:alpha `

## Context

- Testing the shared backend.
## Your Environment

* Version used: 
```
Version: 2017-01-06T20:28:08Z
Release-Tag: RELEASE.2017-01-06T20-28-08Z
Commit-ID: 4225a15281558149d7377640c9bf2aeae245b314
```
* Operating System and version: Minio m2 server.

**Comment by harshavardhana** [comment]
@hackintoshrao anything relevant on the server logs?

**Comment by harshavardhana** [comment]
Looks like something we can add as a test case on the server tests as well..

**Comment by harshavardhana** [comment]
Strange there is a Minio server test which seems to pass appropriately 

```
func (s *TestSuiteCommon) TestPutObjectLongName(c *C) {
         // generate a random bucket name.                                                                                                        
         bucketName := getRandomBucketName()
         // HTTP request to create the bucket.                                                                                                    
         request, err := newTestSignedRequest("PUT", getMakeBucketURL(s.endPoint, bucketName),
                 0, nil, s.accessKey, s.secretKey, s.signer)
         c.Assert(err, IsNil)

         client := http.Client{Transport: s.transport}
         // Execute the HTTP request to create bucket.                                                                                            
         response, err := client.Do(request)
         c.Assert(err, IsNil)
         c.Assert(response.StatusCode, Equals, http.StatusOK)
         // Content for the object to be uploaded.                                                                                                
         buffer := bytes.NewReader([]byte("hello world"))
         // make long object name.                                                                                                                
         longObjName := fmt.Sprintf("%0255d/%0255d/%0255d", 1, 1, 1)
         // create new HTTP request to insert the object.                                  
...
...
...
````

**Comment by harshavardhana** [comment]
> --- FAIL: TestPutObjectLongName (0.12s)
>         server_test.go:304: Expected response code to be XMinioInvalidObjectName, got InternalError.
>         server_test.go:307: Expected response Message to be Object name contains unsupported characters. Unsupported characters are `^*|\", got We encountered an internal error, ple
> ase try again..
>         server_test.go:310: Expected response status code to be 400, got 500.

Fixed these two in the PR.  Looking at the other issue , looks like a network disconnection. Can you reproduce this without using shared proxy? just direct?

**Comment by hackintoshrao** [comment]
When the test was run separately it passes. The issue is not with the shared backend. Closing the issue.
