### ISSUE TITLE
Restricting Access to a Bucket and/or File to HTTP Referrer

### ISSUE THREAD

**Issue by ZiiX** [minio/minio#3540]
## Expected Behavior
S3 buckets allow you to restrict what sites can show files as [outlined on their site](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-4).

## Current Behavior
Minio's difference only allows for a few [policy features](http://docs.minio.io/docs/minio-client-complete-guide#policy) and [share options](https://docs.minio.io/docs/minio-client-complete-guide#share).

## Possible Solution
It would be great to incorporate this feature on an individual file 'share' level as well as on a per-bucket 'policy' level for one, many or *.domains.  Also, adding to the browser-based create bucket button with the option to limit to referring domain(s) as well as an individual new "copy link" feature-set to the online minio browser with http referrer limit, time limit, etc options would be great.

Other solutions I'm not aware of to increase privacy and security would be welcome too!
## Context
I want to: 
- save bandwidth from folks posting my media links to their sites & sharing them from my minio server
-  limit hotlinking and protect files better that are currently served behind a password & force that file to stay behind a password protected site. 

## Your Environment
My environment is NGINX + Minio + Lets Encrypt

thank you for your time & my awesome minio!

**Comment by harshavardhana** [comment]
Ping @krisis are planning to look into this ?

**Comment by krisis** [comment]
Yes, I will be working on it.
