### ISSUE TITLE
[shared-fs] Multipart upload leaves behind empty directory

### ISSUE THREAD

**Issue by krisis** [minio/minio#3545]
Multipart upload leaves behind an empty object directory under ``.minio.sys/multipart/bucket/object``.

## Expected Behavior

There should be no empty directories left behind.

## Current Behavior

If an object was uploaded using the multipart upload API to bucket/object, on completion we find the following empty directory left behind.
``.minio.sys/multipart/bucket/object``

## Possible Solution

Not known.

## Steps to Reproduce (for bugs)

1. ``mc cp 65mb shared-backend/test/``
2. Look for ``shared-backed/.minio.sys/multipart/test/65mb``

## Context

Multipart upload (i.e, upload of "large" objects)

## Your Environment

* Version used: 2017-01-09
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version: Windows 8.1
* Link to your project:

**Comment by krisis** [comment]
This issue is _not_ present on GNU/Linux.

**Comment by harshavardhana** [comment]
Found a way to address this problem - https://boostgsoc13.github.io/boost.afio/doc/html/afio/FAQ/deleting_open_files.html 

Happens because of how windows operating system behaves, let me add this code for windows only helper function and provide a new binary.

**Comment by harshavardhana** [comment]
Uploaded new binaries, this issue is fixed for windows based on the logic from the last link.
