### ISSUE TITLE
Passing Response-Content-Disposition results in SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by JaTochNietDan** [minio/minio#3547]
When trying to use [this fork](https://github.com/AdRoll/goamz) of the goamz library for Go and using the function [SignedURLWithArgs](https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L800), we get an error `SignatureDoesNotMatch` when attempting to load the signed URL in the browser. The API seems to return the signed URL just fine but when loading it in the browser it doesn't work.

An example of a signed URL that is returned that doesn't work: `http://develop.local:9500/bucket/1.20170109113658351.1.20170109113658351pcfNk.png?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1483971588&Signature=z19KhQHjJM98VNjetdBU0j5IZDw%3D&response-content-disposition=inline%3B+filename%3D%22Screen+Shot+2017-01-08+at+18.58.10.png%22`

## Expected Behavior
Should load the file from the Minio server with the set `Content-Disposition` header.

## Current Behavior
Returns a `SignatureDoesNotMatch` error for the signed URL. The full message is: `The request signature we calculated does not match the signature you provided. Check your key and signing method.`

## Possible Solution
I suspect it is something to do with URL encoding but I'm not entirely sure.

## Steps to Reproduce (for bugs)
Using this library https://github.com/AdRoll/goamz.

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/url"
	"time"

	"github.com/AdRoll/goamz/aws"
	"github.com/AdRoll/goamz/s3"
)

func main() {
	auth, err := aws.GetAuth(
		"AKIAIOSFODNN7EXAMPLE",
		"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
		"",
		time.Now().AddDate(1, 0, 0),
	)

	if err != nil {
		log.Fatalln(err)
	}

	client := s3.New(auth, aws.Region{
		Name:                 "dev",
		S3Endpoint:           "http://dev.local:9500",
		S3LocationConstraint: false,
		S3LowercaseBucket:    false,
	})

	bucket := client.Bucket("desk")

	vals := url.Values{}

	// Works fine without this line
	vals.Set("response-content-disposition", "inline; filename=\"test.png\"")

	fmt.Println("URL:", bucket.SignedURLWithArgs("i/1/attachment/1.20170109113658351.1.20170109113658351pcfNk.png", time.Now().Add(time.Minute*10), vals, http.Header{}))
}
```

This also doesn't work with V2 on the minio-go library:

```go
func TestMinio() {
	s3Client, err := minio.NewV2("development.dev:9500","AKIAIOSFODNN7EXAMPLE","wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY", false)
	if err != nil {
		log.Fatalln(err)
	}

	reqParams := make(url.Values)
	reqParams.Set("response-content-disposition", "inline; filename=\"test.png\"")

	// Gernerate presigned get object url.
	presignedURL, err := s3Client.PresignedGetObject("desk", "i/1/attachment/1.20170109113658351.1.20170109113658351pcfNk.png", time.Minute*10, reqParams)
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println("Minio URL:", presignedURL)
}
```

The returned URL produces the same error when attempting to use it in the browser.

**Comment by harshavardhana** [comment]
We will take a look thanks @JaTochNietDan

**Comment by vadmeste** [comment]
Taking this.
