### ISSUE TITLE
[standalone-xl] Cannot list an object when we manually remove its data in the first xl disk

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3548]
## Expected Behavior
Manually removing an object data from the first disk should not lead to a listing problem.

## Current Behavior
mc ls myminio/testbucket/ doesn't show the "corrupted" object

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
1. Start Minio with fresh 4 local xl disks
`minio server /tmp/xl{1..4}`
2. Create a bucket: `mc mb myminio/testbucket`
3. Upload a file (128 mb): `mc cp 128mb.file myminio/testbucket/`
4. Delete object data in the first disk: `rm -r /tmp/xl1/testbucket/128mb.file`
5. `mc ls myminio/testbucket/`

## Context
Manual testing

## Your Environment
All, commit-id: 2f4a7483eac98e29a708d170d114ed0160b94421

**Comment by harshavardhana** [comment]
Listing is not meant to honor quorum. @vadmeste - you have to read the file.  Listing happens only from one of the disks chosen at random. So might list and might not list.

**Comment by harshavardhana** [comment]
> Listing is not meant to honor quorum. @vadmeste - you have to read the file. Listing happens only from one of the disks chosen at random. So might list and might not list.

Going to close this since this a known behavior, to list corrupted objects one should be using ListObjectsHeal()
