### ISSUE TITLE
Notification message (amqp) doesn't contain correct source minio IP

### ISSUE THREAD

**Issue by kallqvist** [minio/minio#3556]
There is no good way to connect back to the minio server that created a notification message.

Note also how my IP in this example is affected by the docker setup and docker links I'm using between minio and rabbitmq and therefore not usable at all.

```
      ...
      "userIdentity": {
        "principalId": "minio"
      },
      "requestParameters": {
        "sourceIPAddress": "172.17.0.1:48212"
      },
      "responseElements": {},
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "Config",
        "bucket": {
          "name": "video",
          "ownerIdentity": {
            "principalId": "minio"
          },
          "arn": "arn:aws:s3:::video"
        },
        "object": {
          "key": "d%2Fd7%2Fd7b3b561fe44f31e.mp4",
          "size": 15540066,
          "eTag": "087d63de0bcacc7aa787adf18277463c",
          "sequencer": "149804955F81CCFF"
        }
        ...
```

## Expected Behavior
There should be some way of connecting back to Minio from any value in the notification message JSON.

## Current Behavior
There is no such information in the messages and I haven't found any way of forwarding additional values or object/bucket metadata as part of the message data.

## Possible Solution
- the sourceIPAddress? (if it would be the actual IP of the upload request to minio)
or
- principalId? (if I could lead principalId back to an access key instead of the (hardcoded?) value of minio)
- s3['arn'] containing a hostname or minio instance name?
- something else?

## Steps to Reproduce (for bugs)
1. Configure AMQP and s3:ObjectCreated:* event
2. Upload file
3. Try to connect back to Minio using nothing but message content

## Context
I have multiple minio instances publishing events to the same exchange in rabbitmq and need a way to connect back to the minio instance that created an event.
There are no values in the message that I can use to connect back to the correct minio instance.

## Your Environment
docker setup using minio:edge (more than one container) and rabbitmq using docker links for network.

**Comment by harshavardhana** [comment]
SourceIPAddress is the source of the client not the server. We are following S3 spec here http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

```
 "requestParameters":{  
            "sourceIPAddress":"ip-address-where-request-came-from"
         },
``` 

Adding new fields just invalidates S3 compliance. 

Can you explain more on why are you connecting back to server? are you trying to invoke a callback upon an event? - if yes

Then it is better to use - [ListenBucketNotification API](https://github.com/minio/minio-js/blob/master/examples/minio/listen-bucket-notification.js)

**Comment by vadmeste** [comment]
@harshavardhana, according to the discussion in Gitter, @kallqvist have many Minio servers (not a cluster) and he wanted to know which Minio server fired the notification.

**Comment by kallqvist** [comment]
@vadmeste Exactly!

There are several minio instances in my stack.
They are all separate (no clustering) and I don't know beforehand where or how many they are.

They are also writing their events to the same exchange (each one have an upload bucket) and a worker is waiting for amqp-messages to process the uploaded file and then send it back to the _same_ minio instance the event came from.

**Comment by harshavardhana** [comment]
We can add a new responseElements key which signifies the server hostname or server ip -  but it is a new field which needs to be added..

**Comment by kallqvist** [comment]
what about the principal ID?
maybe that could contain a reference to the access key that generated the message?

I don't mind doing a DB lookup and/or regex on my end to connect any gap between a value in the amqp-messages and something I can use for later connections (public hostname etc)

**Comment by harshavardhana** [comment]
> maybe that could contain a reference to the access key that generated the message?

Principal ID needs to be fixed properly @kallqvist which i am doing right now.

**Comment by kallqvist** [comment]
Hmm, I see.

Can you think of any other way I can connect back to the origin minio using the message content?
Is it maybe possible to forward custom x-amz-meta or request parameters from the upload to the message?

I'm doing this to reduce the amount of config-files for workers and other places I need to have access and secret keys to minio stored when most services waiting for AMQP are only supposed to have temporary read access anyway, I think what I'm trying to build could be a pretty common use-case?

**Comment by harshavardhana** [comment]
> Can you think of any other way I can connect back to the origin minio using the message content?
> Is it maybe possible to forward custom x-amz-meta or request parameters from the upload to the message?
> 
> I'm doing this to reduce the amount of config-files for workers and other places I need to have access and secret keys to minio stored when most services waiting for AMQP are only supposed to have temporary read access anyway, I think what I'm trying to build could be a pretty common use-case?

Yes you can we will had a new entry in ResponseElements{}  i.e basically add 

`x-minio-api-endpoint: http://<ip>:9000`

**Comment by harshavardhana** [comment]
how does this look @kallqvist 

```
	"Records": [
		{
			"eventVersion": "2.0",
			"eventSource": "aws:s3",
			"awsRegion": "us-east-1",
			"eventTime": "2017-01-10T20:28:36Z",
			"eventName": "s3:ObjectCreated:Put",
			"userIdentity": {
				"principalId": "USWUXHGYZQYFYFFIT3RE"
			},
			"requestParameters": {
				"sourceIPAddress": "127.0.0.1:46250"
			},
			"responseElements": {
				"x-amz-request-id": "2K9Z6ZOKX5EY22U0",
				"x-minio-origin-server": "http://192.168.1.106:9000"
			},
			"s3": {
				"s3SchemaVersion": "1.0",
				"configurationId": "Config",
				"bucket": {
					"name": "testbucket",
					"ownerIdentity": {
						"principalId": "USWUXHGYZQYFYFFIT3RE"
					},
					"arn": "arn:aws:s3:::testbucket"
				},
				"object": {
					"key": "issue",
					"size": 26,
					"eTag": "1e7672cbc2f76c3e9daad0e290e711b9",
					"sequencer": "14988300BA5F8C65"
				}
			}
		}
	],
```

**Comment by kallqvist** [comment]
yes, that is perfect! :)

**Comment by harshavardhana** [comment]
@kallqvist final name is `x-minio-origin-endpoint`

**Comment by kallqvist** [comment]
@harshavardhana Just tried the minio:edge and it all works fine!
The origin endpoint is still affected by docker somehow in my setup and didn't end up being very useful in my case.
In this example I would have needed it to be 192.168.99.100:9000 (The one I used when sending the POST with the file) to be able to reach it over my network.

```
      ---
      "userIdentity": {
        "principalId": "aaaaa"
      },
      "requestParameters": {
        "sourceIPAddress": "192.168.99.1:51203"
      },
      "responseElements": {
        "x-amz-request-id": "1498A64E3A474260",
        "x-minio-origin-endpoint": "http://172.17.0.5:9000"
      },
      ...
```

Not really a problem for me and even a little bit expected to be ruined by docker networking somehow when docker link is used...

I instead ended up saving the principalId in a database together with a public dns name to minio I can use for file downloads in the workers and that works perfectly!
I think the principalId is probably the better choice for what I'm trying to achieve anyway when there's also loadbalancers and proxies on the network between all these services that might affect the returned IP even more...

Thanks for all the quick help and fixes!
