### ISSUE TITLE
api: GetObject() transfer rate observed to have TTFB (Time To First Byte) ~5s delay

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3559]
Downloading a file is slow

## Expected Behavior
When I download a file the TTFB should be few milliseconds

## Current Behavior
Downloading a 500Mo file take about 5s before the first bit
```
time curl -o /dev/null -s -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" XXXXXXXX
Connect: 0.042 TTFB: 3.966 Total time: 31.460
```

## Your Environment
Cluster of 4 machines running on docker.

```
docker exec -ti 886727bc922e minio version
Version: 2017-01-09T23:49:09Z
Release-Tag: DEVELOPMENT.2017-01-09T23-49-09Z
Commit-ID: eb6d53d2f5d66e16a621141df111bd78bb843ecb
```
Bandwidth between the servers 1Gbit, the machines are on the same datacenter, no connectivity problem, when the download start we can observe up to 800Mbits/s between the machines, the BW is not the issue.
The problem can also be observed remotely and locally, 5s can't be explained by the latency between the client and the server anyway.
The rest of the transfert seems also quite slow compared to the network performances but this need more investigation on my side to confirm this part.

**Comment by harshavardhana** [comment]
what is the object size here @dcharbonnier ?

**Comment by harshavardhana** [comment]
Also can you paste "cat /proc/cpuinfo" ?

**Comment by dcharbonnier** [comment]
```
454.97 MB Connect: 0.560 TTFB: 0.602 Total time: 41.616
931.98 MB Connect: 0.552 TTFB: 11.515 Total time: 95.418
 49.85 MB Connect: 0.114 TTFB: 1.195 Total time: 5.834
```

The behavior is not consistent, I repeated the second one a second time and it took 0.604 instead of 11 seconds, caching ?

**Comment by dcharbonnier** [comment]
More than enough @harshavardhana and those machines are only running minio (also 32Go of ram, >30Go free)

```
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
stepping	: 9
microcode	: 0x19
cpu MHz		: 1946.097
cache size	: 8192 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 6185.85
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
stepping	: 9
microcode	: 0x19
cpu MHz		: 1601.464
cache size	: 8192 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 6185.85
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
stepping	: 9
microcode	: 0x19
cpu MHz		: 1613.210
cache size	: 8192 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 6185.85
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
stepping	: 9
microcode	: 0x19
cpu MHz		: 1600.011
cache size	: 8192 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 6185.85
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by harshavardhana** [comment]
> The behavior is not consistent, I repeated the second one a second time and it took 0.604 instead of 11 seconds, caching ?

This is caching @dcharbonnier

**Comment by harshavardhana** [comment]
@dcharbonnier can you run "go test -benchmark ."  - golang.org/x/crypto/blake2b on this project ?  We have been working on fix with upstream Go regarding blake2b performance issue.  Bit-rot checksum uses blake2b. 

https://github.com/golang/go/issues/18563

There is some XEON instruction bug which is being fixed upstream. I am thinking this is your issue. If you confirm the perf numbers then it might tell us more about your hardware. 

https://go-review.googlesource.com/#/c/34993/ here is patch which we are pushing upstream.

**Comment by dcharbonnier** [comment]
so minio 11s is the time to transfert ~1To of data with a 1Gbit link, does it means that minio need to do that before starting ? :-(

**Comment by dcharbonnier** [comment]
no I can't run it sorry, this machine only run docker and I can't run anything else than a docker container

**Comment by harshavardhana** [comment]
> so minio 11s is the time to transfert ~1To of data with a 1Gbit link, does it means that minio need to do that before starting ? :-(

Blake2b verification happens for data blocks to verify they are all in-tact i.e there is no on-disk corruption before erasure decoding, this is done for all I/O.  Caching is implemented to augment this behavior.

Blake2b performance problem happened because of a recent change in upstream code which introduced a wrong instruction providing lower perf on AVX/AVX2 based Intel hardware. 

Blake2b should be ideally negligible but due to this bug it can slow the decoding down.

> no I can't run, this machine only run docker and I can't run anything else than a docker container

Would a binary with the benchmark work ? it can be run on the host as well -  since it would be the same CPU.

**Comment by harshavardhana** [comment]
Looks like my assumption was incorrect blake2b performance is at expected value 

```
 ./blake2b.test -test.bench .
BenchmarkWrite128-4   	 5000000	       209 ns/op	 610.33 MB/s
BenchmarkWrite1K-4    	 1000000	      1484 ns/op	 689.59 MB/s
BenchmarkSum128-4     	10000000	       234 ns/op	 546.91 MB/s
BenchmarkSum1K-4      	 1000000	      1506 ns/op	 679.83 MB/s
PASS
``` 

Since this processor is also AVX, SSE4.1 only - the performance issue only affects AVX2 based intel processors. 

So looks like we are looking at something else here..

**Comment by krisis** [comment]
- Download statistics of 2GB object using a single PUT object via ``mc share`` URL.
```sh
➜  lab curl -o /dev/null -s -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" -L http://172.20.0.4:9000/test/2gb
Connect: 0.000 TTFB: 4.149 Total time: 8.033 
```

- Download statistics of a 2GB object uploaded via multipart upload using ``mc cp``.
```sh
➜  lab curl -o /dev/null -s -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" -L http://172.20.0.4:9000/test/2gb-mpart
Connect: 0.000 TTFB: 0.310 Total time: 15.246 
```

@dcharbonnier could you check if uploading an object via multipart upload, using ``mc`` for instance, reduces TTFB? In my setup, the improvement in TTFB is significant if I upload the object via multipart upload. ``0.310s`` in comparison to ``4.419s`` for a single PUT object.

**Comment by vadmeste** [comment]
Taking this.
