### ISSUE TITLE
x-amz-metadata-directive: REPLACE support

### ISSUE THREAD

**Issue by mpetrazzo** [minio/minio#3560]
I'm trying minio with s3ql (bitbucket.org/nikratio/s3ql), a fuse FS, "that stores all its data online using storage services like Amazon S3" and there is a problem with minio.
I opened a issue with s3ql and after them debug, it seems that minio is not supporting the "x-amz-metadata-directive: REPLACE" header

Here you can find the issue: https://bitbucket.org/nikratio/s3ql/issues/246/s3ql-and-minio-s3-server there the developer says:
"Sounds as if minio is not supporting the x-amz-metadata-directive: REPLACE header, but instead of reporting in error it is silently ignored."

## Possible Solution
S3ql guys suggest to open a bug for ask the implementation

## Steps to Reproduce (for bugs)
1. Install s3ql
2. mkfs.s3ql s3c://serveroip:9000/s3ql --backend-options no-ssl
3. mount.s3ql --fg --compress zlib-1 --backend-options no-ssl s3c://serverip:9000/s3ql /mnt/point/
in other shell:
4. touch /mnt/point/test
5. umount /mnt/point

And s3ql crash, like you can see on the s3ql issue

## Your Environment
* Version used: 2016-12-13T17:19:42Z
* Operating System and version: ubuntu 14 LTS
* Link to your project: bitbucket.org/nikratio/s3ql

**Comment by harshavardhana** [comment]
We already support this in master branch , fixed by https://github.com/minio/minio/pull/3487
