### ISSUE TITLE
Proposal - `touch` API

### ISSUE THREAD

**Issue by marcinwyszynski** [minio/minio#3562]
I would like to propose adding a `touch` operation to the API, which would set the value of the `lastModified` to the current timestamp. This operation is not supported on S3, but my particular use case is cache expiration for which I could use `lastModified`.

I understand that this needs careful consideration and - if the idea is accepted - careful design. Still, I'd be happy to try implementing this feature if you consider it useful.

**Comment by harshavardhana** [comment]
Thanks for the proposal API @marcinwyszynski 

Minio is designed with a mindset to reduce the number of APIs to interact with storage and keep it to bare minimum. Addressing only 90% of the use case 100% of the time. 

Every new API we add adds the burden of testing and maintaining it.  If its not part of S3 it would be seldom used by majority users we would like to avoid such situations. 

This type of functionality should be implemented outside of Minio perhaps at a caching layer using varnish etc.

**Comment by marcinwyszynski** [comment]
Makes sense, thanks!
