### ISSUE TITLE
server: Support minio server to bind to list of specific ip address and interface. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3567]
## Expected Behavior
Currently there is no way to specific interface and ip-address for Minio server to bind to. 

## Current Behavior
We have no way to provide this multiple ips. 

## Possible Solution
There is no possible solution yet in Go - https://github.com/golang/go/issues/9334 

## Steps to Reproduce (for bugs)
Quite easy its not possible.

## Context
Under certain deployments this is quite useful. 

## Your Environment
Current master

**Comment by harshavardhana** [comment]
Our current server mux actually handles this and provides a way to have multiple listeners. We can look at enhancing it to support binding to specific set of comma separated IP's only.

**Comment by vadmeste** [comment]
Taking this

**Comment by harshavardhana** [comment]
Deferred for future for now..

**Comment by harshavardhana** [comment]
This functionality already works we can bind to a specific IP.  Upstream go lacks features to bind to a specific set of IPs - https://github.com/golang/go/issues/9334

Closing until then.

**Comment by finid** [comment]
@harshavardhana, but by default, Minio already binds to all available IP address on a server. Or is that different from what you're referring to?

**Comment by harshavardhana** [comment]
Binding to all interfaces is not the issue. It is to selectively listening on only few of them .  Currently it's either bind to one or to all. Go lacks API level support for this.

**Comment by finid** [comment]
OK, thanks for the clarification.

**Comment by plinss** [comment]
Understood about the upstream go API limitation, but in the meanwhile it would be useful to at least have to option to bind to a single IP address. Specifically localhost so when running behind a proxy, such as Nginx for TLS termination/caching etc., we can prevent access that bypasses the proxy.

**Comment by harshavardhana** [comment]
The option to bind to single address is `minio server --address "localhost:9000"` . Does this not work for you @plinss?

**Comment by plinss** [comment]
That works for me, I actually just found it by digging through the code, didn't see that option in the docs anywhere.

(It would be nice to have in the config file as well.)

**Comment by harshavardhana** [comment]
> That works for me, I actually just found it by digging through the code, didn't see that option in the docs anywhere.

FWIW our approach usually is a TLDR style, each command is self documented.  simply doing `minio server -h` gives you examples as well. 

```
$ minio server -h
NAME:
  minio server - Start object storage server.

USAGE:
  minio server [FLAGS] PATH [PATH...]

FLAGS:
  --address value               Bind to a specific ADDRESS:PORT, ADDRESS can be an IP or hostname. (default: ":9000")
  --config-dir value, -C value  Path to configuration directory. (default: "/home/harsha/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  
ENVIRONMENT VARIABLES:
  ACCESS:
     MINIO_ACCESS_KEY: Custom username or access key of minimum 5 characters in length.
     MINIO_SECRET_KEY: Custom password or secret key of minimum 8 characters in length.

  BROWSER:
     MINIO_BROWSER: To disable web browser access, set this value to "off".

  REGION:
     MINIO_REGION: To set custom region. By default it is "us-east-1".

EXAMPLES:
  1. Start minio server on "/home/shared" directory.
      $ minio server /home/shared

  2. Start minio server bound to a specific ADDRESS:PORT.
      $ minio server --address 192.168.1.101:9000 /home/shared

  3. Start erasure coded minio server on a 12 disks server.
      $ minio server /mnt/export1/ /mnt/export2/ /mnt/export3/ /mnt/export4/ \
          /mnt/export5/ /mnt/export6/ /mnt/export7/ /mnt/export8/ /mnt/export9/ \
          /mnt/export10/ /mnt/export11/ /mnt/export12/

  4. Start erasure coded distributed minio server on a 4 node setup with 1 drive each. Run following commands on all the 4 nodes.
      $ export MINIO_ACCESS_KEY=minio
      $ export MINIO_SECRET_KEY=miniostorage
      $ minio server http://192.168.1.11/mnt/export/ http://192.168.1.12/mnt/export/ \
          http://192.168.1.13/mnt/export/ http://192.168.1.14/mnt/export/
```

> (It would be nice to have in the config file as well.)

This is not done on purpose `--address` is a mutating entity and doesn't need a place in `config.json` where entries are largely static.

**Comment by plinss** [comment]
> FWIW our approach usually is a TLDR style, each command is self documented. simply doing minio server -h gives you examples as well.

Understood, though the `minio <command> -h` option doesn't seem to be documented anywhere either... (and doesn't show for `minio -h` or `minio -h server`).

I do appreciate the TLDR style to get started quickly, but I'm finding the docs quite sparse when looking for details... (but that's getting off topic, will file separate issues for missing info).

> This is not done on purpose --address is a mutating entity and doesn't need a place in config.json where entries are largely static.

I disagree, IP addresses don't change often on production servers (actually just about never on my servers), particularly 'localhost'. But that's just my opinion. Seems better to me to control the listening address in the server's config file rather that the service file (or other script that starts the server). Spreading configuration options out in multiple places (config files, command-line options, and environment variables) is generally asking for something to get out of sync.

I do get that you're probably considering the cluster use-case and are trying to enable simply copying config files between all the nodes in a cluster, but you already have the instance vs cluster config issue with region and domain. You can always add an environment variable override for the address too... another common pattern is to support multiple config files that layer on top of each other (one for cluster-wide options, another for instance options).

(and for that matter, having the rest of the command-line options, like storage paths and cluster addresses in the config file would be nice too)

**Comment by davidgubler** [comment]
> This is not done on purpose --address is a mutating entity and doesn't need a place in config.json where entries are largely static.

I'm sorry, but that does not make any sense at all.

A configuration file is just one way to configure a service. Another one is command line parameters, and a third one is environment variables. Ideally, all three support the exact same set of configuration options. 

It is up to the user/system administrator to decide which is best for which situation. In our case, we start multiple instances of minio via systemd, and the multi-instance handling of systemd doesn't support command line parameters that well. As a result of this issue, we need a wrapper script to start every instance with the proper port number argument just because it can't be set in the configuration file.

In other situations, the twelve-factor app methodology mandates that apps can be *completely* configured via environment variables. Or a user who just wants to quickly test a tool probably prefers configuration via command line parameters. 

Please do not arbitrarily limit the configuration options of your software. It just causes a lot of headaches, use of foul language and a lot of wasted time.
