### ISSUE TITLE
ssl: Add support of Windows PFX certificates

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3572]
## Expected Behavior
To be able to detect and load pfx file inside .minio/certs/ directory 

## Current Behavior
PFX file is not recognizable

## Possible Solution
Use golang pfx API support

## Context
Adding new feature

## Your Environment
All

**Comment by harshavardhana** [comment]
http://stackoverflow.com/questions/15413646/converting-pfx-to-pem-using-openssl - one workaround here to be documented.

**Comment by deekoder** [comment]
Document the steps to extract pfx file into its components such as `private.key, public.crt`

**Comment by nitisht** [comment]
closing this for now, as the steps are available [here](http://stackoverflow.com/questions/15413646/converting-pfx-to-pem-using-openssl). We can revisit if required later.
