### ISSUE TITLE
package: Create ubuntu/debian package for Minio

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3575]
## Expected Behavior
Create a ubuntu package which works for both debian and ubuntu. 

## Current Behavior
No packages are available.

## Possible Solution
Work on creating a skeletal debian package. 

## Steps to Reproduce (for bugs)
No package available right now.

## Context
Building packages for across ecosystems.

## Your Environment
Current releases.

**Comment by shantanugadgil** [comment]
Same as: https://github.com/minio/minio/issues/3576#issuecomment-277564260

**Comment by jmdh** [comment]
Hi,

I'm a Debian developer and am involved in a project that would benefit from minio packaging. Would packaging minio for the official Debian repositories (which would ultimately filter down to ubuntu)  be of interest?

**Comment by harshavardhana** [comment]
> I'm a Debian developer and am involved in a project that would benefit from minio packaging. Would packaging minio for the official Debian repositories (which would ultimately filter down to ubuntu) be of interest?

Yes definitely and thank you @jmdh

**Comment by hentismith** [comment]
Hi @harshavardhana 

I'm busy working on the Debian package for minio and minio/cli is listed as a dependency. minio/cli is a fork of  urfave/cli. Will minio always depend on minio/cli without the changed being merged back to urfave/cli ? If so how do I log an issue ?

**Comment by harshavardhana** [comment]
We have a PR pending upstream and do not know when it might get merged. But as a Debian package maintainer you don't need to package all the deps. All the relevant deps are already present .. in a vendorized directory. So in future if we migrate to a newer CLI debian package doesn't have to do anything.

**Comment by jmdh** [comment]
Hello,

A Debian package uploaded to Debian will need to have all its deps
packaged separately - embedding code copies in Debian is a both a
security nightmare and against policy:

https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

https://pkg-go.alioth.debian.org/packaging.html (dependencies)

**Comment by harshavardhana** [comment]
> A Debian package uploaded to Debian will need to have all its deps
> packaged separately - embedding code copies in Debian is a both a
> security nightmare and against policy:

These are not embedded files in-fact are part of the project itself. We decided which is the right version of each of the packages along with how go tooling works.  It would be a bad experience for users to install a simple static binary via this kind of mechanism. All it should be is a simple static binary packaged in a `.deb` file nothing more.

**Comment by hentismith** [comment]
Good morning. 

Debian packaging doesn't work that way. From https://wiki.debian.org/Packaging:

> A Debian package consists of one source package component and one or more binary package components. Debian Policy requires that these package files are built with a particular structure and format but there are many methods of arriving at these files.

> Only packages that are compliant with Debian policy will be accepted into the archive. Manually constructed binary packages (.deb) that are not built from a source package will never be accepted.

As you can see Debian policy requires a source package that can build the binary package and binary only packages will not be accepted. 

I'll keep working on packaging minio if I can and update here.

**Comment by hentismith** [comment]
Hi @harshavardhana 

Can you please assist. When trying to build minio/cli I get the following 

```
github.com/minio/cli
   dh_auto_test -O--buildsystem=golang
	go test -v -p 8 github.com/minio/cli
# github.com/minio/cli_test
src/github.com/minio/cli/app_test.go:343: cannot use func literal (type func(string, interface {})) as type cli.helpPrinter in assignment
src/github.com/minio/cli/command_test.go:15: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/command_test.go:35: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:15: cannot use globalSet (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:25: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:32: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:39: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:46: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:53: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:63: cannot use set (type *flag.FlagSet) as type *cli.Context in argument to cli.NewContext
src/github.com/minio/cli/context_test.go:63: too many errors
FAIL	github.com/minio/cli [build failed]
```

I've ci'ed the v1.2.0 tag on releases.

**Comment by harshavardhana** [comment]
> go test -v -p 8 github.com/minio/cli

Checking.. @henti

**Comment by harshavardhana** [comment]
Published v1.3.0 let me know if that works for you.. @henti - https://github.com/minio/cli/releases

**Comment by hentismith** [comment]
@harshavardhana 

Perfect, thank you.

**Comment by hentismith** [comment]
@hackintoshrao Sorry for slow progress. 

Need to get all dependencies packaged and accepted into Debian first before I can start work on minio. 
On a related note, can you please tag/release dsync ?

**Comment by henti** [comment]
Just an update. 

golang-github-fatih-structs
golang-github-gorilla-rpc
golang-github-minio-cli
golang-github-minio-dsync

Has been accepted into Debian, however I'm no longer able to work on the remainder of the dependencies or packaging minio for Debian as the packaging component for our internal project has been moved out of my team.  

I'm reaching out to the new team and will point them at this ticket in case they will be doing Debian packaging of minio. 

Regards
Henti

**Comment by harshavardhana** [comment]
We have a snap package already for Ubuntu https://github.com/minio/minio#snap closing
