### ISSUE TITLE
feature request: hashicorp vault integration for bucket level ACLs + encryption

### ISSUE THREAD

**Issue by blacktop** [minio/minio#3581]
You could integrate with vault to add policies that were able to read/write to certain buckets that way you could carve up (revokable) access that way and have something very similar to S3 + IAM.

**Comment by blacktop** [comment]
I have also created a feature request with vault here - https://github.com/hashicorp/vault/issues/2274

**Comment by harshavardhana** [comment]
@blacktop we can work with them. Thanks for opening the bug.

**Comment by harshavardhana** [comment]
Now circling back on this we see that you are requesting bucket ACLs and IAM.  We are not planning to implement ACLs and IAM in Minio.  Minio is intentionally designed to solve all the needs of a single tenant only.

Closing this as not applicable.
