### ISSUE TITLE
Error on file upload through web UI >5GB

### ISSUE THREAD

**Issue by emanuelstanciu** [minio/minio#3582]
ERRO[0309] Failed to create object <path>  cause=http: request body too large source=[fs-v1.go:410:fsObjects.PutObject()] stack=fs-createfile.go:27:fsCreateFile fs-v1.go:407:fsObjects.PutObject <autogenerated>:195:(*fsObjects).PutObject web-handlers.go:494:(*webAPIHandlers).Upload web-router.go:85:(*webAPIHandlers).Upload-fm
ERRO[0309] Unexpected error, please report this issue at https://github.com/minio/minio/issues  cause=http: request body too large source=[web-handlers.go:877:toWebAPIError()]

**Comment by harshavardhana** [comment]
This is expected @emanuelstanciu  - https://github.com/minio/minio/blob/master/docs/minio-limitations.md#browser-access
 
For larger files than 5GB please use command line tools which allow for richer functionality.

**Comment by harshavardhana** [comment]
Closing as answered..
