### ISSUE TITLE
docker-machine getting "Unable to initialize storage - disk path full"

### ISSUE THREAD

**Issue by jeffutter** [minio/minio#3592]
## Expected Behavior
I am expecting the server to start

## Current Behavior
When starting minio:

```
docker run --rm -v $(pwd)/data:/export minio/minio server /export
Created minio configuration file at /root/.minio
time="2017-01-19T05:03:51Z" level=fatal msg="Unable to initialize storage disk(s)." cause="disk path full" source="[server-main.go:405:serverMain()]"
```

## Possible Solution
I'm not terribly sure, I think it has something to do with the way that docker-machine mounts the volumes as network shares. Inside the minio container the volumes have the permission 1000:50. I have gone as far as creating a new docker image that adds a minio user with those IDs.

## Steps to Reproduce (for bugs)
1. Use docker-machine on OSX
2. Create a local folder `data`
3. run `docker run --rm -v $(pwd)/data:/export minio/minio server /export`

## Context
I am trying to use minio as a replacement for fake_s3 for local development. However I can't persist the data, as I get the above error when starting up

## Your Environment
* Version used: 2016-12-13T17:19:42Z
* OSX 10.12.2
* Docker version 1.13.0-rc7, build 48a9e53
* docker-machine version 0.9.0-rc2, build 7b19591

**Comment by harshavardhana** [comment]
> time="2017-01-19T05:03:51Z" level=fatal msg="Unable to initialize storage disk(s)." cause="disk path full" source="[server-main.go:405:serverMain()]"

Your disks are full.. @jeffutter min required is atleast 1GB.

**Comment by jeffutter** [comment]
I should have specified. On my docker host I have plenty of space:

```
~/ ❯❯❯ df -h /
Filesystem   Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1  373Gi  309Gi   64Gi    83% 4100549 4290866730    0%   /
```

On the vm from docker-machine:

```
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     7.0G    179.8M      6.8G   3% /
/dev/sda1                55.7G     19.7G     33.1G  37% /mnt/sda1
cgroup                    3.9G         0      3.9G   0% /sys/fs/cgroup
Users                   372.5G    309.0G     63.5G  83% /Users
/dev/sda1                55.7G     19.7G     33.1G  37% /mnt/sda1/var/lib/docker/aufs
```

The space minio sees:

```
go/src/app $ df -h
Filesystem                Size      Used Available Use% Mounted on
none                     55.7G     19.7G     33.1G  37% /
Users                   372.5G    309.0G     63.6G  83% /export
Users                   372.5G    309.0G     63.6G  83% /config
```

**Comment by harshavardhana** [comment]
Looks strange @jeffutter can you do this 

Start server but mount it at a separate location choose `/export1`
```
docker run --rm -v $(pwd)/data:/export1 minio/minio server /export

docker exec -it <container_id> /bin/sh
df -h /export1 
```

**Comment by harshavardhana** [comment]
Also 'df -i' to check for inodes.

**Comment by jeffutter** [comment]
```
docker exec -it angry_bose /bin/sh
/go/src/app # df -h /export1
Filesystem                Size      Used Available Use% Mounted on
Users                   372.5G    309.0G     63.5G  83% /export1
/go/src/app # df -i /export1
Filesystem              Inodes      Used Available Use% Mounted on
Users                     1000         0      1000   0% /export1
```

Size looks fine. I don't know how many inodes it expects, but none are used.

**Comment by harshavardhana** [comment]
> Size looks fine. I don't know how many inodes it expects, but none are used.

Ah i see @jeffutter this looks like a bug on the mount bind..

**Comment by jeffutter** [comment]
I was thinking it was something like that. Perhaps it couldn't read the correct stats off it or something. I'm not really sure how to debug further. I see many places where that error message gets logged, but I'm not sure which one is actually raising here.

**Comment by harshavardhana** [comment]
Let me give you a code to run 

```go
package main

import (
	"fmt"
	"os"

	"github.com/minio/minio/pkg/disk"
)

func main() {
	fmt.Printf("%#v\n", disk.GetInfo(os.Args[1]))
}
```

**Comment by harshavardhana** [comment]
you might have to a static binary built locally using ``CGO_ENABLED=0 go build disk.go``

**Comment by jeffutter** [comment]
certainly, It might take me a minute. I haven't done any go in a while.

Thanks for being so helpful and quick to respond.

**Comment by jeffutter** [comment]
disk.Info{Total:400000000000, Free:68179484672, Files:1000, Ffree:1000, FSType:"NFS"}

**Comment by harshavardhana** [comment]
> disk.Info{Total:400000000000, Free:68179484672, Files:1000, Ffree:1000, FSType:"NFS"}

Looks like indeed it is returning a wrong information.  Can you try using docker released version it could be a bug in the `rc2` version as well, also are you sure you are using NFS mount here? 

Our internal code validates atleast 10,000 inodes need to be available.

**Comment by jeffutter** [comment]
```
❯❯❯ docker-machine version
docker-machine version 0.8.2, build e18a919
❯❯❯ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
❯❯❯ docker run --rm -v $(pwd)/data:/export minio/minio server /export 
Created minio configuration file at /root/.minio
time="2017-01-19T14:49:06Z" level=fatal msg="Unable to initialize storage disk(s)." cause="disk path full" source="[server-main.go:405:serverMain()]"
```

@harshavardhana I downgraded to 1.12.6 (although 1.13 was released last night!). Anyhow, it has the same issue.

With docker-machine, docker creates a nfs share from the OSX host to the virtualbox VM running docker for volumes. It then bind mounts that share into the container. Thus it's showing NFS.

**Comment by jeffutter** [comment]
It appears that this number of `1000` is hardcoded in virtualbox: http://superuser.com/a/999847

Maybe we could skip this check on NFS ... or more specifically skip it on NFS if the count is 1000? I realize that probably opens up a some potential issues if someone is using minio on Virtualbox over NFS and doesn't actually have enough inodes. But I'm guessing most people wouldn't be doing that in production and more like would be using it in dev environments where it wouldn't cause them problems?

**Comment by harshavardhana** [comment]
Yes will skip it for NFS. @jeffutter

**Comment by jeffutter** [comment]
@harshavardhana I opened a PR that fixes this for me. You may have a better way to handle it, but the PR is available if you would like.

**Comment by harshavardhana** [comment]
> @harshavardhana I opened a PR that fixes this for me. You may have a better way to handle it, but the PR is available if you would like.

The PR looks good @jeffutter - will be merged.
