### ISSUE TITLE
[fs] Regression in bucket listening in master

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3594]
## Expected Behavior
`mc watch myminio/testbucket` shows new uploaded objects

## Current Behavior
`mc watch` is not able to detect uploaded objects

## Possible Solution
Not yet

## Steps to Reproduce (for bugs)
Terminal 1:
`$ minio server /tmp/fs`
Terminal 2:
`$ mc mb myminio/testbucket`
`$ mc watch myminio/testbucket`
Terminal 3:
`$ mc cp file myminio/testbucket`

## Context
Manual test

## Your Environment
All, with last minio master.

**Comment by harshavardhana** [comment]
This is the bug 

```
ERRO[0015] Error sending update bucket listener to  - Peer :9000 was not initialized, unexpected error  cause=Peer :9000 was not initialized, unexpected error source=[s3-peer-client.go:178:S3PeersUpdateBucketListener()]
``` 

First we need to stop sending RPC for localhosts.
