### ISSUE TITLE
clicking on the logo shows incorrect error message

### ISSUE THREAD

**Issue by shantanugadgil** [minio/minio#3601]
When I start the minio server and I click on the logo on the left top which says "Minio Browser",
an error message pops up (in the top middle) which says "Bucket name invalid: "

## Expected Behavior
nothing should happen

## Current Behavior
shows an error message

## Possible Solution
don't show error message

## Steps to Reproduce (for bugs)
(description should be self-explanatory)

## Your Environment
* Version used: 2016-12-13T17:19:42Z
* Environment name and version (e.g. nginx 1.9.1): standalone browser
* Server type and version: Linux x86_64
* Operating System and version: Debian 8

**Comment by harshavardhana** [comment]
> When I start the minio server and I click on the logo on the left top which says "Minio Browser",
> an error message pops up (in the top middle) which says "Bucket name invalid: "

Do you have a screenshot to help us @shantanugadgil ? - Thanks

**Comment by harshavardhana** [comment]
// cc @krishnasrinivas

**Comment by shantanugadgil** [comment]
![minio_empty_data_dir](https://cloud.githubusercontent.com/assets/2508915/22122353/9c6f5f84-dead-11e6-9d99-9942a9a69f63.png)

**Comment by harshavardhana** [comment]
Thanks @shantanugadgil

**Comment by krishnasrinivas** [comment]
@shantanugadgil what browser (and version) are you using? because I am not able to see the error that you get (checked with minio 2016-12-13T17:19:42Z)

**Comment by shantanugadgil** [comment]
My setup: Firefox 50 (now 51.0.1) 32-bit on Win7 x64
It happens when the storage directory is empty.

I also checked with the following browsers; same result:
Opera 42.0.2393.517 
Seamonkey (User agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0 SeaMonkey/2.46)
Vivaldi 1.6.689.40 (Stable channel) (64-bit)

**Comment by krishnasrinivas** [comment]
> It happens when the storage directory is empty.

ah, yes, i see that it happens when there are no buckets.
