### ISSUE TITLE
browser: Change colors of the upload buttons in the minio browser

### ISSUE THREAD

**Issue by shantanugadgil** [minio/minio#3602]
When using the minio browser ...

The "white-on-pink" icons are fine to see (the rotating + and X symbol)
One has to squint to try and make out the "white-on-ochre-yellow" logos. (upload file and create bucket)

## Expected Behavior
Easier to identify color combination for the icons.

## Current Behavior
![minio_different_colors](https://cloud.githubusercontent.com/assets/2508915/22122439/fe6dfc86-dead-11e6-8c59-3f5a09264095.png)

## Possible Solution
Probably different colors for 'upload file' and 'create bucket' ?

## Steps to Reproduce (for bugs)
Start the minio server.
Go to the URL in the web browser

## Context

Start the minio server.
Go to the URL in the web browser

## Your Environment
* Version used: 2016-12-13T17:19:42Z
* Environment name and version (e.g. nginx 1.9.1): Linux (server).  Windows (Firefox) browser
* Server type and version: Linux, Debian 8
* Operating System and version: Windows Desktop

**Comment by harshavardhana** [comment]
There is a work on this under progress in `miniobrowser` project.

**Comment by harshavardhana** [comment]
Thanks for the github issue @shantanugadgil

**Comment by harshavardhana** [comment]
@shantanugadgil do you happen to have a particular color set in mind which you would like to share it with us would make it easier for us.  Thanks

**Comment by deekoder** [comment]
Discuss what to do between now and the upcoming refresh.

**Comment by deekoder** [comment]
proceed with current colors.
