### ISSUE TITLE
browser: Misleading error message during secretKey missing in UI

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3614]
## Expected Behavior

When a user enters an access key, but neglects to provide a secret key, then the Minio frontend should report an error about the missing secret key form field.

## Current Behavior

The minio frontend displays an error message, but mistakenly reports a missing Access Key, when in fact the Access Key is provided, it's the Secret Key field that is missing.

## Steps to Reproduce (for bugs)

1. `docker pull minio/minio`
2. `docker run -p 9000:9000 minio/minio server /export`
3. `go get github.com/mcandre/karp/...`
3. `karp 127.0.0.1:9000`
4. Attempt to authenticate by supplying an Access Key from the Docker logs, but omit the Secret Key.

## Your Environment

* minio:latest
* Safari 10
* Docker for Mac 1.12
* macOS Sierra

**Comment by harshavardhana** [comment]
Does karp provide S3 support - more instructions on what was the environment variable used? and how to run karp would be useful.

**Comment by mcandre** [comment]
Apologies, `karp` is simply a cross-platform substitute for the equivalent `open`, `xdg-open`, `start`, etc. platform-specific commands for launching graphical programs such as web browsers. You could just do `open 127.0.0.1:9000` on macOS, for example.

**Comment by harshavardhana** [comment]
Current the error message for wrong secret key is 

`Authentication failed, check your access credentials`

If access key is wrong 

`The access key ID you provided does not exist in our records`

This is correct in terms of how S3 behaves wrong access key results in `The access key ID you provided does not exist in our records`  where as wrong secret key results in `Signature` failure. 

Closing this bug as working as expected in the recent release. Please re-open if you disagree we can discuss further. Thanks
