### ISSUE TITLE
Docs: Offer Cookbook for connecting to Minio servers via AWS S3 API

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3615]
In the Minio documentation, please provide more details for users interested in connecting to Minio-provided object storage servers via the main AWS S3 API, including configuration details like how to specify the Minio server endpoint.

https://docs.aws.amazon.com/sdk-for-go/api/

**Comment by harshavardhana** [comment]
@mcandre have you looked at this - https://docs.minio.io/docs/how-to-use-aws-sdk-for-go-with-minio-server#main ?

**Comment by harshavardhana** [comment]
Closing as answered..
