### ISSUE TITLE
How to cleanly shutdown minio clients?

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3623]
Are minio clients automatically shutdown per gc, or are users expected to call some kind of shutdown function when no further REST calls will be submitted?

**Comment by harshavardhana** [comment]
Do not understand what it means by clients are you talking about SDK or mc or anything that you are using.

Server automatically cleans idle connections and properly gives back resources to kernel even if you didn't close the connection on the client side.

**Comment by harshavardhana** [comment]
Closing this as answered @mcandre
