### ISSUE TITLE
How to quickly delete a non-empty bucket?

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3624]
Minio provides `RemoveBucket` for deleting an empty bucket, but what's the fastest way to delete a non-empty bucket? For example, it would be nice to quickly clean up after integration tests.

**Comment by harshavardhana** [comment]
You can use `mc rm -r --force` which basically does RemoveObjects and then RemoveBucket

**Comment by mcandre** [comment]
`mc` is fine for CLI, but what about from the SDK?

**Comment by krishnasrinivas** [comment]
@mcandre you can do listObjects and use the results to remove the objects and finally remove the empty bucket

**Comment by sonemaro** [comment]
As @krishnasrinivas said you can get Iterator and remove them one by one or all with `deleteObjects` method 
```
try {
    $iterator = $s3->getIterator('ListObjects', [
        'Bucket' => $bucketName
    ]);

    foreach ($iterator as $object) {
        $s3->deleteObject([
            'Bucket'  =>  $bucketName,
            'Key'     =>  $object['Key']
        ]);
    }
} catch (\Exception $e) {
    return $this->response->errorBadRequest();
}
```
