### ISSUE TITLE
[heal] Fails to heal an object when xl.json is deleted in one disk

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3631]
## Expected Behavior
Recover when xl.json is removed in only one disk

## Current Behavior
mc admin heal returns 500 error

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
1. Start from four fresh disk : 
`minio server /tmp/xl{1..4}`
2. Create a bucket and upload an object
`mc mb myminio/testbucket; mc cp file myminio/testbucket`
3. Remove xl.json in disk 1
` rm /tmp/xl1/testbucket/file/xl.json`
4. `mc admin heal myminio/testbucket/file`

## Context
Manual test of healing

## Your Environment
All

**Comment by harshavardhana** [comment]
Possible solution is fix the `xl.json` from the other nodes in quorum.. this is part of the deep healing which needs to be addressed.

**Comment by harshavardhana** [comment]
Also you can test this with 6 disks and see what the result is? @vadmeste

**Comment by vadmeste** [comment]
> Also you can test this with 6 disks and see what the result is? @vadmeste

The same behavior with 6 disks

**Comment by vadmeste** [comment]
> Possible solution is fix the xl.json from the other nodes in quorum.. this is part of the deep healing which needs to be addressed.

I see, however, how it comes that it works when I remove the whole object in one disk, like `rm /tmp/xl1/testbucket/file/*` ?

**Comment by harshavardhana** [comment]
> I see, however, how it comes that it works when I remove the whole object in one disk, like rm /tmp/xl1/testbucket/file/* ?

It is because `xl.json` is used to validate if the object exists to see that if its an object but it should be the quorum that should be counted here in case of healing. There is a bug in how it is handled right now apparently.

**Comment by krisis** [comment]
@harshavardhana I can take this up.

**Comment by krisis** [comment]
@harshavardhana can we close this issue? https://github.com/minio/minio/pull/3649 fixes this.
