### ISSUE TITLE
[proposal] Add exported functions to simplify testing from external test scripts

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3637]
Currently, a go test code can import github.com/minio/minio/cmd package and run the server Minio. 

However libraries like minio-go or madmin have the difficulty to perform real tests since they need:
*) An already configured Minio server
*) An established situation that is usually difficult to have.

For example: Let's consider that madmin want to test its lock management code. It is already difficult to write a scenario that finds a hold lock since this latter will appear and disappear in a very short time. So adding some exported functions in cmd package like: cmd.TestUtilsAddLock(bucket, object, ..) could simplify our test code.

What do you think ?

**Comment by harshavardhana** [comment]
> For example: Let's consider that madmin want to test its lock management code. It is already difficult to write a scenario that finds a hold lock since this latter will appear and disappear in a very short time. So adding some exported functions in cmd package like: cmd.TestUtilsAddLock(bucket, object, ..) could simplify our test code.

Can you elaborate more on this @vadmeste ?

**Comment by vadmeste** [comment]
> Can you elaborate more on this @vadmeste ?

The goal is to **really** test some Minio web services by external librairies like madmin and minio-go. For example, I do not see how we can prepare a test case where madmin is able to find some hold locks when it calls lock list management API.

So, the proposal is:
* madmin's test imports github.com/minio/minio/cmd package and runs the server
* madmin's test calls some APIs that we will implement to prepare difficult scenarios, like creating 1000 permanent locks so they can be discover-able when madmin test fetches them.

**Comment by harshavardhana** [comment]
A functional test for this scenario was decided to be done on mint package using directly `mc admin` tool.

**Comment by harshavardhana** [comment]
> A functional test for this scenario was decided to be done on mint package using directly mc admin tool.

Closing..
