### ISSUE TITLE
Store multiple versions of the same file

### ISSUE THREAD

**Issue by radutopala** [minio/minio#3640]
Is Minio already capable of storing multiple versions of the same file? Like s3 is.

**Comment by koolhead17** [comment]
Hello @radutopala 
Minio does not support object versioning.

**Comment by radutopala** [comment]
@koolhead17 would be awesome to have this feature, compete on it with Dropbox and s3.

**Comment by koolhead17** [comment]
@radutopala we have discussed about same https://github.com/minio/minio/issues/1309

**Comment by harshavardhana** [comment]
> @koolhead17 would be awesome to have this feature, compete on it with Dropbox and s3.

We will not be implementing this in Minio to create multiple object versions our recommended tool is - https://github.com/s3git/s3git

**Comment by EugenMayer** [comment]
Is there no chance to see this happening? This is one of my most missing features actually ;/

**Comment by nitisht** [comment]
@EugenMayer https://github.com/minio/minio/pull/6494 this is WIP
