### ISSUE TITLE
Can't put a file to a bucket with AWS SDK locally

### ISSUE THREAD

**Issue by liamdawson** [minio/minio#3642]
## Expected Behavior
When the Ruby AWS SDK is set up with the Minio endpoint, creating an object in a bucket should work.

## Current Behavior
If I do not set up hosts file mapping to Minio, and instead use localhost, it attempts to connect to `bucket-name.localhost:9000`, which fails hosts mapping.

If I set up hosts mapping to map `bucket-name.localhost` to `127.0.0.1`, I get an error about unformed XML (as it is putting the file to a "bucket creation" url, and minio is trying to read the file as XML).

## Possible Solution
* Provide instructions on how to override the default bucket name -> hostname mapping for the AWS sdks (or a general place to look)
* Allow/document the ability to bind to a hostname, and then recognise subdomains of that hostname as bucket names

## Steps to Reproduce (for bugs)

1.Can add later if necessary. Suspect this is a known "issue" that I couldn't find the relevant documentation to solve.

## Context
I'm unable to test the official AWS api locally with minio due to this issue.

## Your Environment

* Version used: 2017-01-25T03:14:52Z
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: N/A
* Operating System and version: Debian 8.6 Jesse
* Link to your project: N/A

**Comment by vadmeste** [comment]
@liamdawson, you probably need to activate force_path_style flag in your code. Did you follow this documentation https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-ruby-with-minio.md ?

**Comment by liamdawson** [comment]
Thanks @vadmeste - I could only find the docs for the CLI. Hopefully this issue will help someone else in future. :)

**Comment by vadmeste** [comment]
You welcome. By the way, the same information is hosted here https://docs.minio.io/docs/how-to-use-aws-sdk-for-ruby-with-minio-server, take a look in http://docs.minio.io for more information
