### ISSUE TITLE
how to modify local fs system to minio ? 

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3653]
for exmaple I can get image(object) from:
	s3Client, err := minio.New(url, accessKey, secretKey, false)
	if err != nil {
		log.Fatalln(err)
	}

	object, err := s3Client.GetObject(mybucket, fn)

	if err != nil {
		log.Fatalln(err)
	}

How can I modify old local fs system to minio ? like following codes :

// 输出image
// 权限判断
func (c File) OutputImage(noteId, fileId string) revel.Result {
	path := fileService.GetFile(c.GetUserId(), fileId) // 得到路径
	if path == "" {
		return c.RenderText("")
	}
	fn := revel.BasePath + "/" + strings.TrimLeft(path, "/")
	file, _ := os.Open(fn)
	return c.RenderFile(file, revel.Inline) // revel.Attachment
}

// RenderFile returns a file, either displayed inline or downloaded
// as an attachment. The name and size are taken from the file info.
func (c *Controller) RenderFile(file *os.File, delivery ContentDisposition) Result {
	c.setStatusIfNil(http.StatusOK)

	var (
		modtime       = time.Now()
		fileInfo, err = file.Stat()
	)
	if err != nil {
		WARN.Println("RenderFile error:", err)
	}
	if fileInfo != nil {
		modtime = fileInfo.ModTime()
	}
	return c.RenderBinary(file, filepath.Base(file.Name()), delivery, modtime)
}

// RenderBinary is like RenderFile() except that it instead of a file on disk,
// it renders data from memory (which could be a file that has not been written,
// the output from some function, or bytes streamed from somewhere else, as long
// it implements io.Reader).  When called directly on something generated or
// streamed, modtime should mostly likely be time.Now().
func (c *Controller) RenderBinary(memfile io.Reader, filename string, delivery ContentDisposition, modtime time.Time) Result {
	c.setStatusIfNil(http.StatusOK)

	return &BinaryResult{
		Reader:   memfile,
		Name:     filename,
		Delivery: delivery,
		Length:   -1, // http.ServeContent gets the length itself unless memfile is a stream.
		ModTime:  modtime,
	}
}

**Comment by harshavardhana** [comment]
Are you asking how you can modify backend for FS and make it reflect on the S3 API ? @goodforever

**Comment by goodforever** [comment]
@harshavardhana yes ,Can you help me ?

**Comment by harshavardhana** [comment]
> @harshavardhana yes ,Can you help me ?

This shouldn't be done - modifying backend while also modifying the object from S3 API can have bad consequences - you might loose data. It is not recommended that you modify objects in this manner. 

Either you should modify the file directly on the backend and not use S3 API.. Or only use S3 API for all i/o operations.

**Comment by harshavardhana** [comment]
Closing as answered
