### ISSUE TITLE
Upload of policies having conditionKeys with incompatible actions should fail

### ISSUE THREAD

**Issue by krisis** [minio/minio#3657]
All conditionKeys don't apply for all actions. See http://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html#object-keys-in-amazon-s3-policies and http://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html#bucket-keys-in-amazon-s3-policies for more information.

## Expected Behavior

ConditionKeys like "s3:prefix" and "s3:max-keys" are applicable to "s3:ListBucket" action while not applicable to say "s3:GetObject".

## Current Behavior

As it stands now, minio server applies conditions to all actions. This is incorrect. 

## Possible Solution

We must disallow setting of bucket policies when the actions and conditionKeys are incompatible.

## Steps to Reproduce (for bugs)

1. Set a bucket policy with "s3:GetObject" action and "s3:prefix" conditonKey
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by krisis** [comment]
@harshavardhana I can take this up.

**Comment by harshavardhana** [comment]
Closed by #3659
