### ISSUE TITLE
How to  switch *minio.Object type  to *os.File or io.Reader type ?

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3658]
I have a function with *os.File parameter .
How to  switch *minio.Object type  to *os.File or io.Reader type ?

**Comment by harshavardhana** [comment]
> I have a function with *os.File parameter .
> How to switch *minio.Object type to *os.File or io.Reader type ?

I do not understand what you are trying to achieve here. Can you describe in detail with specific code examples? 

The best way is for a function to use `io.Reader` as the basic interface type which both `*minio.Object` and `*os.File` satisfy - for further reading https://dave.cheney.net/2016/08/20/solid-go-design

**Comment by harshavardhana** [comment]
Closing as answered.

**Comment by goodforever** [comment]
@harshavardhana 
I have old function:
// 输出image
// [OK]
func (c ApiFile) GetImage(fileId string) revel.Result {
	path := fileService.GetFile(c.getUserId(), fileId) // 得到路径
	if path == "" {
		return c.RenderText("")
	}
	fn := revel.BasePath + "/" + strings.TrimLeft(path, "/")
	file, _ := os.Open(fn)
	return c.RenderFile(file, revel.Inline) // revel.Attachment
}

image file is *os.File ,that is saved local fs dir,
Now I get the  image  from minio , it's *minio.Object

I want to modify old code ,like 
fn = strings.TrimLeft(path, "/")
object = ninioClient.GetObject("mybucket", fn)
file := switch object to io.reader 
return c.RenderFile(file, revel.Inline) // revel.Attachment


about ReaderFile , in following:

// RenderFile returns a file, either displayed inline or downloaded
// as an attachment. The name and size are taken from the file info.
func (c *Controller) RenderFile(file *os.File, delivery ContentDisposition) Result {
	c.setStatusIfNil(http.StatusOK)

	var (
		modtime       = time.Now()
		fileInfo, err = file.Stat()
	)
	if err != nil {
		WARN.Println("RenderFile error:", err)
	}
	if fileInfo != nil {
		modtime = fileInfo.ModTime()
	}
	return c.RenderBinary(file, filepath.Base(file.Name()), delivery, modtime)
}

// RenderBinary is like RenderFile() except that it instead of a file on disk,
// it renders data from memory (which could be a file that has not been written,
// the output from some function, or bytes streamed from somewhere else, as long
// it implements io.Reader).  When called directly on something generated or
// streamed, modtime should mostly likely be time.Now().
func (c *Controller) RenderBinary(memfile io.Reader, filename string, delivery ContentDisposition, modtime time.Time) Result {
	c.setStatusIfNil(http.StatusOK)

	return &BinaryResult{
		Reader:   memfile,
		Name:     filename,
		Delivery: delivery,
		Length:   -1, // http.ServeContent gets the length itself unless memfile is a stream.
		ModTime:  modtime,
	}
}

**Comment by harshavardhana** [comment]
What methods does `RenderFile()` needs access to `Read(), Seek(), ReaderAt()`  ? if its just `Read()` then the function signature should be just for `io.Reader` 

Old function signature
```
func (c *Controller) RenderFile(file *os.File, delivery ContentDisposition) Result {
```

New function signature
```
func (c *Controller) RenderFile(file io.Reader delivery ContentDisposition) Result {
```

**Comment by goodforever** [comment]
can I pass *minio.Object to New function signature parameter file io.Reader,for example
c. ReaderFile(object,...) ?

func (c *Controller) RenderFile(file io.Reader delivery ContentDisposition) Result {

**Comment by harshavardhana** [comment]
> can I pass *minio.Object to New function signature parameter file io.Reader,for example
> c. ReaderFile(object,...) ?
> 
> func (c *Controller) RenderFile(file io.Reader delivery ContentDisposition) Result {

Yes absolutely `*minio.Object` implements 

- io.Reader
- io.Seeker
- io.ReaderAt
- io.Closer

Interfaces..

**Comment by goodforever** [comment]
Thanks ,all
