### ISSUE TITLE
Can't get valid PresignedUrl with aws-sdk: Signature does not match

### ISSUE THREAD

**Issue by paride** [minio/minio#3672]
My Java code (based on `aws-sdk`, not on `minio-java`) goes like this:

```java
  public URL getPreSignedUrl(long attachmentId, HttpMethod method) {
    ClientConfiguration clientConfiguration = new ClientConfiguration();
    clientConfiguration.setSignerOverride("AWSS3V4SignerType");

    AmazonS3 client = new AmazonS3Client(credentials, clientConfiguration);

    Region usEast1 = Region.getRegion(Regions.US_EAST_1);
    client.setRegion(usEast1);
    client.setEndpoint("https://s3.myserver.org/");

    final S3ClientOptions clientOptions = S3ClientOptions.builder().setPathStyleAccess(true).build();
    client.setS3ClientOptions(clientOptions);

    GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(bucket, String.valueOf(attachmentId), method);

    request.setExpiration(new Date(System.currentTimeMillis() + DURATION));
    request.setContentType("application/octet-stream");

    return client.generatePresignedUrl(request);
  }
```

The URL is generated, but then it's not accepted by Minio with this error:

> ERRO[0967] {"method":"PUT","path":"/mybucket/2751378068674537391","query":"X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Date=20170201T184235Z\u0026X-Amz-SignedHeaders=content-type%!B(MISSING)host\u0026X-Amz-Expires=3599\u0026X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%!F(MISSING)20170201%!F(MISSING)cable%!F(MISSING)s3%!F(MISSING)aws4_request\u0026X-Amz-Signature=91ab6a1f3638d23898f9f2073127f1f01a0993be30eb0bf6433ed48ad71c0cf6","header":{"Accept-Encoding":["gzip"],"Connection":["Keep-Alive"],"Content-Length":["24976"],"Content-Type":["application/octet-stream"],"Host":["s3.cable.im"],"User-Agent":["Dalvik/2.1.0 (Linux; U; Android 7.1; Android SDK built for x86_64 Build/NPF26K)"],"Via":["1.1 s3.cable.im"],"X-Forwarded-For":["1.2.3.4"],"X-Forwarded-Host":["s3.myserver.org"],"X-Forwarded-Server":["s3.myserver.org"]}}  cause=Signature does not match source=[object-handlers.go:468:objectAPIHandlers.PutObjectHandler()]

This happens on Minio
```
Version: 2017-01-25T03:14:52Z
Release-Tag: RELEASE.2017-01-25T03-14-52Z
Commit-ID: f8e4700a11065967242b8857045ce7dee607722d
```
using `aws-sdk` 1.11.22. If I use the `minio-java` libraries on the same Minio server everything works fine. The other tools like `mc` have no problems in accessing the server. The code I'm using is taken from:

https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-java-with-minio.md

so it should be a tested recipe. There is nothing special in my setup I guess.

Is this a known issue?
Any hint?

**Comment by vadmeste** [comment]
@paride, to open the presigned URL, you need to use the same server's host name that you passed when generating the presigned url.

You set this in your code `client.setEndpoint("https://s3.myserver.org/");`, so you have to use https://s3.myserver.org/mybucket/2751378068674537391?xx=xx&xx=xx&xx=xx

Can you check and keep us updated ?

**Comment by harshavardhana** [comment]
Can you paste the generated URL ?

**Comment by harshavardhana** [comment]
Also looks there is a proxy used here . Can you paste your proxy version and config ?

**Comment by paride** [comment]
The URL is:

`https://s3.myserver.org//secchio/2515018938636541835?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20170201T192142Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=3600&X-Amz-Credential=XXXXXXX%2F20170201%2Fcable%2Fs3%2Faws4_request&X-Amz-Signature=6cda4ae30ae474c636f005b879560321c08415e3aa7f8111707095db5b357015`

where `secchio` is the name of the bucket. The proxy is an Apache reverse proxy, I'll do a test without it to rule out the possibility it's interfering.

**Comment by paride** [comment]
OK, trying without proxy is not straightforward, but it's an Apache reverse proxy.

The code works fine if I use the official Amazon service. Well, I didn't try with `setSignerOverride()`, `setRegion()` and `setPathStyleAccess()`, but otherwise it works. I do use the same hostname both when generating the presignedUrl and with accessing it.

**Comment by harshavardhana** [comment]
> https://s3.myserver.org//secchio/2515018938636541835?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20170201T192142Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=3600&X-Amz-Credential=XXXXXXX%2F20170201%2Fcable%2Fs3%2Faws4_request&X-Amz-Signature=6cda4ae30ae474c636f005b879560321c08415e3aa7f8111707095db5b357015

Can you provide the apache reverse proxy config ?

**Comment by paride** [comment]
I got rid of the double `/` in the URL, just in case. Nothing changed. The proxy is configured like this:

```apache
<VirtualHost *:443>
        ServerName s3.myserver.org
        SSLEngine On

        SSLCertificateFile /etc/letsencrypt/live/s3.myserver.org/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/s3.myserver.org/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateChainFile /etc/letsencrypt/live/s3.myserver.org/chain.pem

        ProxyVia On
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:9000/
        ProxyPassReverse / http://127.0.0.1:9000/
</VirtualHost>
```

**Comment by paride** [comment]
I just changed `ProxyVia On` to `ProxyVia Block`, like suggested here:

https://github.com/minio/cookbook/blob/master/docs/setup-apache-http-proxy-with-minio.md

but with no success.

**Comment by harshavardhana** [comment]
> ERRO[0967] {"method":"PUT","path":"/mybucket/2751378068674537391","query":"X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Date=20170201T184235Z\u0026X-Amz-SignedHeaders=content-type%!B(MISSING)host\u0026X-Amz-Expires=3599\u0026X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%!F(MISSING)20170201%!F(MISSING)cable%!F(MISSING)s3%!F(MISSING)aws4_request\u0026X-Amz-Signature=91ab6a1f3638d23898f9f2073127f1f01a0993be30eb0bf6433ed48ad71c0cf6","header":{"Accept-Encoding":["gzip"],"Connection":["Keep-Alive"],"Content-Length":["24976"],"Content-Type":["application/octet-stream"],"Host":["s3.cable.im"],"User-Agent":["Dalvik/2.1.0 (Linux; U; Android 7.1; Android SDK built for x86_64 Build/NPF26K)"],"Via":["1.1 s3.cable.im"],"X-Forwarded-For":["1.2.3.4"],"X-Forwarded-Host":["s3.myserver.org"],"X-Forwarded-Server":["s3.myserver.org"]}} cause=Signature does not match source=[object-handlers.go:468:objectAPIHandlers.PutObjectHandler()]

The error here indicates that the `Host` header is wrong where it should have been "s3.myserver.org"

**Comment by paride** [comment]
@harshavardhana if you're referring to the fact that sometimes it's `s3.cable.im` and sometimes `s3.myserver.org`, it's my fault. I didn't want to publish the actual domain, but it's not so important. It's actually `s3.cable.im`, everywhere. So:

`ERRO[0101] {"method":"PUT","path":"/secchio/4956633102154884414","query":"X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Date=20170201T194311Z\u0026X-Amz-SignedHeaders=content-type%!B(MISSING)host\u0026X-Amz-Expires=3599\u0026X-Amz-Credential=XXXXXXXXXXX%!F(MISSING)20170201%!F(MISSING)cable%!F(MISSING)s3%!F(MISSING)aws4_request\u0026X-Amz-Signature=cefd3ed4f9f1eee3f53b3afeada4f323f08e4d0a6a3dff7254c02539fd03125e","header":{"Accept-Encoding":["gzip"],"Connection":["Keep-Alive"],"Content-Length":["24976"],"Content-Type":["application/octet-stream"],"Host":["s3.cable.im"],"User-Agent":["Dalvik/2.1.0 (Linux; U; Android 7.1; Android SDK built for x86_64 Build/NPF26K)"],"Via":["1.1 s3.cable.im"],"X-Forwarded-For":["2.234.35.49"],"X-Forwarded-Host":["s3.cable.im"],"X-Forwarded-Server":["s3.cable.im"]}}  cause=Signature does not match source=[object-handlers.go:468:objectAPIHandlers.PutObjectHandler()]`

The same goes for the `VirtualHost`:

```apache
<VirtualHost *:443>
        ServerName s3.cable.im
        SSLEngine On

        SSLCertificateFile /etc/letsencrypt/live/s3.cable.im/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/s3.cable.im/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateChainFile /etc/letsencrypt/live/s3.cable.im/chain.pem

        ProxyVia Block
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:9000/
        ProxyPassReverse / http://127.0.0.1:9000/
</VirtualHost>
```

Sorry for the confusion.

**Comment by harshavardhana** [comment]
> @harshavardhana if you're referring to the fact that sometimes it's s3.cable.im and sometimes i3.myserver.org, it's my fault. I didn't want to publish the actual domain, but it's not so important. It's actually s3.cable.im, everywhere. So:
> 
> ERRO[0101] {"method":"PUT","path":"/secchio/4956633102154884414","query":"X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Date=20170201T194311Z\u0026X-Amz-SignedHeaders=content-type%!B(MISSING)host\u0026X-Amz-Expires=3599\u0026X-Amz-Credential=XXXXXXXXXXX%!F(MISSING)20170201%!F(MISSING)cable%!F(MISSING)s3%!F(MISSING)aws4_request\u0026X-Amz-Signature=cefd3ed4f9f1eee3f53b3afeada4f323f08e4d0a6a3dff7254c02539fd03125e","header":{"Accept-Encoding":["gzip"],"Connection":["Keep-Alive"],"Content-Length":["24976"],"Content-Type":["application/octet-stream"],"Host":["s3.cable.im"],"User-Agent":["Dalvik/2.1.0 (Linux; U; Android 7.1; Android SDK built for x86_64 Build/NPF26K)"],"Via":["1.1 s3.cable.im"],"X-Forwarded-For":["2.234.35.49"],"X-Forwarded-Host":["s3.cable.im"],"X-Forwarded-Server":["s3.cable.im"]}} cause=Signature does not match source=[object-handlers.go:468:objectAPIHandlers.PutObjectHandler()]

Ok i see now we will evaluate this on our end..

**Comment by paride** [comment]
@hackintoshrao Thank you.

**Comment by paride** [comment]
@harshavardhana if you can't figure what the problem is I can let you have the credentials to try on the server. Let me know.

**Comment by vadmeste** [comment]
@paride, the client which is opening the presigned url should send this header "Content-Type: application/octet-stream", you can't do that with a browser but you can with curl.

Another option is to remove ` request.setContentType("application/octet-stream");` from your code.

**Comment by paride** [comment]
@vadmeste Thank you. I removed the `setContentType()` line but it didn't fix it. The error is still

`ERRO[5552] {"method":"PUT","path":"/secchio/1951076555824126305","query":"X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Date=20170201T225308Z\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Expires=3600\u0026X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%!F(MISSING)20170201%!F(MISSING)cable%!F(MISSING)s3%!F(MISSING)aws4_request\u0026X-Amz-Signature=9b203643bb2e626d7aece0075626d015aa9bb67e2202dd5825edf608be84f533","header":{"Accept-Encoding":["gzip"],"Connection":["Keep-Alive"],"Content-Length":["24976"],"Content-Type":["application/octet-stream"],"Host":["s3.cable.im"],"User-Agent":["Dalvik/2.1.0 (Linux; U; Android 7.1; Android SDK built for x86_64 Build/NPF26K)"],"Via":["1.1 s3.cable.im"],"X-Forwarded-For":["1.2.3.4"],"X-Forwarded-Host":["s3.cable.im"],"X-Forwarded-Server":["s3.cable.im"]}}  cause=Signature does not match source=[object-handlers.go:468:objectAPIHandlers.PutObjectHandler()]`

The content type is actually an octect-stream (binary data).

With this change the generated URL is now:

`https://s3.cable.im/secchio/1150191823978977622?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20170201T225305Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20170201%2Fcable%2Fs3%2Faws4_request&X-Amz-Signature=54072b3fb595dff2b4d0368b877a6cfa360525b9f6a9f30347e907b7a7130712`

where indeed I don't see `X-Amz-SignedHeaders=content-type` anymore.

**Comment by vadmeste** [comment]
@paride, well, it seems that you were sending the content-type header from the beginning so it must be another issue. Will continue my investigation. By the way, can you tell me what is the value that you set to 'method' variable ?

**Comment by paride** [comment]
@vadmeste It's `HttpMethod.PUT`, from `com.amazonaws.HttpMethod`.

**Comment by vadmeste** [comment]
@paride, I tested locally and it works. Not able to guess what's the problem with your configuration, can you join us here  https://slack.minio.io to discuss further ?

**Comment by paride** [comment]
OK, I somehow fixed it, and it wasn't minio's fault. Unfortunately I changed too many things to be able to pinpoint the problem. What I did basically is:

- Use the new `AmazonS3ClientBuilder` stuff instead of the deprecated `setEndpoint()`, especially `setEndpointConfiguration()`. I found out that I call it after `setRegion()`, so the tricky part was probably there.
- Updated `aws-java-sdk-s3` to 1.11.86.

Something like this does work (cleaned up from my application's stuff, may contain errors):

```java
  public URL getPreSignedUrl(long attachmentId, HttpMethod method) {
    AmazonS3ClientBuilder clientBuilder = AmazonS3ClientBuilder.standard();

    clientBuilder.setPathStyleAccessEnabled(true);

    clientBuilder.setCredentials(new AWSStaticCredentialsProvider(credentials));

    AwsClientBuilder.EndpointConfiguration endpointConfiguration = new AwsClientBuilder.EndpointConfiguration("https://my-endpoint/", "us-east-1");
    clientBuilder.setEndpointConfiguration(endpointConfiguration);

    AmazonS3 client = clientBuilder.build();

    GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(bucket, String.valueOf(attachmentId), method);

    return client.generatePresignedUrl(request);
  }
```

Thanks for the great support!

**Comment by harshavardhana** [comment]
Thanks @paride. Closing this bug.

**Comment by krishnaksharma** [comment]
I had the same issue, but removing content-type works fine. Hereby sharing the complete code.

public class GeneratePresignedUrlAndUploadObject {
	private static final String BUCKET_NAME = "<YOUR_AWS_BUCKET_NAME>"; 
	private static final String OBJECT_KEY  = "<YOUR_AWS_KEY>";
	private static final String AWS_ACCESS_KEY = "<YOUR_AWS_ACCESS_KEY>";
	private static final String AWS_SECRET_KEY = "<YOUR_AWS_SECRET_KEY>";

	public static void main(String[] args) throws IOException {
		BasicAWSCredentials awsCreds = new BasicAWSCredentials(AWS_ACCESS_KEY, AWS_SECRET_KEY);

		AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withRegion(Regions.US_EAST_1)
				.withCredentials(new AWSStaticCredentialsProvider(awsCreds)).build();

		try {
			System.out.println("Generating pre-signed URL.");
			java.util.Date expiration = new java.util.Date();
			long milliSeconds = expiration.getTime();
			milliSeconds += 1000 * 60 * 60;
			expiration.setTime(milliSeconds);

			GeneratePresignedUrlRequest generatePresignedUrlRequest = 
				    new GeneratePresignedUrlRequest(BUCKET_NAME, OBJECT_KEY);
			generatePresignedUrlRequest.setMethod(HttpMethod.PUT); 
			generatePresignedUrlRequest.setExpiration(expiration);
			URL url = s3Client.generatePresignedUrl(generatePresignedUrlRequest); 

			UploadObject(url);

			System.out.println("Pre-Signed URL = " + url.toString());
		} catch (AmazonServiceException exception) {
			System.out.println("Caught an AmazonServiceException, " +
					"which means your request made it " +
					"to Amazon S3, but was rejected with an error response " +
			"for some reason.");
			System.out.println("Error Message: " + exception.getMessage());
			System.out.println("HTTP  Code: "    + exception.getStatusCode());
			System.out.println("AWS Error Code:" + exception.getErrorCode());
			System.out.println("Error Type:    " + exception.getErrorType());
			System.out.println("Request ID:    " + exception.getRequestId());
		} catch (AmazonClientException ace) {
			System.out.println("Caught an AmazonClientException, " +
					"which means the client encountered " +
					"an internal error while trying to communicate" +
					" with S3, " +
			"such as not being able to access the network.");
			System.out.println("Error Message: " + ace.getMessage());
		}
	}

	public static void UploadObject(URL url) throws IOException
	{
		HttpURLConnection connection=(HttpURLConnection) url.openConnection();
		connection.setDoOutput(true);
		connection.setRequestMethod("PUT");
		OutputStreamWriter out = new OutputStreamWriter(
				connection.getOutputStream());
		out.write("This text uploaded as object.");
		out.close();
		int responseCode = connection.getResponseCode();
		System.out.println("Service returned response code " + responseCode);

	}
}
