### ISSUE TITLE
How to call Go client API CopyObject ?

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3677]
Is right that I call  CopyObject like following ? 
err := minioClient.CopyObject("mybucket", "files/user001/xxx.jpg,   "/" + "mybucket" + "/" + files +"/" + "user002" + "/"  + "xxx.jpg", CopyConditions)

I have no CopyConditions, how to setup CopyConditions ?

**Comment by krisis** [comment]
@goodforever what you wish to achieve in the above snippet? ``CopyObject`` is meant for copying objects within the same object store. E.g, copying an object ``myobject`` that is already available in minio (or AWS S3) under ``mybucket`` onto a new object say ``anotherbucket/newobject`. If you wish to copy a file to minio (or AWS S3) you could use [PutObject](http://docs.minio.io/docs/golang-client-api-reference#PutObject) instead.

**Comment by goodforever** [comment]
I need copy a object to other object name under the same mybucket .

**Comment by krisis** [comment]
I tested the following program on play.minio.io, to copy an object into the same bucket with no copy conditions. It worked. If you don't expect source object to satisfy any conditions like ETag value or Modified-Since etc, passing an 'empty' ``minio.CopyConditions`` works. Hope that helps.
```go
package main

import (
	"fmt"

	minio "github.com/minio/minio-go"
)

func main() {
	srcObject := "srcBucket/srcObject"
	dstBucket := "dstBucket"
	dstObject := "dstObject"

	ssl := true
	// Initialize minio client object.
	minioClient, err := minio.New("play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", ssl)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Assuming you don't wish to match any property of the src
	// object before copying it over, we can keep copy conditions
	// 'empty'.
	copyConds := minio.NewCopyConditions()
	err = minioClient.CopyObject(dstBucket, dstObject, srcObject, copyConds)
	if err != nil {
		fmt.Println(err)
		return
	}
}

```

**Comment by harshavardhana** [comment]
Closing this as answered by @krisis

**Comment by goodforever** [comment]
@krisis Thanks!

**Comment by krisis** [comment]
@goodforever could you review this [PR](https://github.com/minio/minio-go/pull/601), which tries to improve the CopyObject API example?

**Comment by goodforever** [comment]
@krisis The example srcObject := "srcBucket/srcObject"  that you give me above and PR example (+err := minioClient.CopyObject("mybucket", "myobject", "/my-sourcebucketname/my-sourceobjectname", copyConds) is different . PR example has  "/" before my-sourcebucketname .
and other When I compile 	copyConds := minioClient.NewCopyConditions(), I got minioClient.NewCopyConditions undefined (type *minio.Client has no field or method NewCopyConditions)

**Comment by harshavardhana** [comment]
> copyConds := minioClient.NewCopyConditions(), I got minioClient.NewCopyConditions undefined (type *minio.Client has no field or method NewCopyConditions)

It should be `copyConds := minio.NewCopyConditions()`

**Comment by goodforever** [comment]
@harshavardhana Thanks!

**Comment by krisis** [comment]
@goodforever I have removed the leading '/' from the source object name in the examples. I don't see minioClient.CopyConditions in the example in the PR. If you find this change useful we can merge it to our docs.

**Comment by goodforever** [comment]
@krisis minioClient.CopyConditions is my code error , not in your example code . Your example is very useful , Thanks!

**Comment by krisis** [comment]
@goodforever OK. Thank you for reviewing the examples.
