### ISSUE TITLE
admin: Introduce a new API ServerInfo()

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3679]
Provides following output, new command.

```
$ mc admin info play --json | jq .
{
  "status": "success",
  "storage": {
    "total": 675875831808,
    "free": 602565951488,
    "backend": {
      "type": "XL",
      "onlineDisks": 8,
      "offlineDisks": 0
    }
  },
  "server": {
    "uptime": 0000,  
    "version": "2017-02-02T20:07:53Z",
    "commitID": "aacfb8654ee399922ca70a6f2d86e23e84ce39e5",
    "sqsARN": [ "arn:minio:sqs:us-east-2:1:webhook", ...],
    "region": "us-east-2"
  },
  "network": {
    "transferred": 0000,
    "received": 00000,
    "thoughput": 0000,
  }
}
```

```
$ mc admin info play
Region:    us-east-2
SQS ARNs:  arn:minio:sqs:us-east-2:1:webhook
Total: 630GiB, Free: 561GiB. Online Disks: 8, Offline Disks: 0
Received: NNGiB, Transferred: NNGiB since <human-duration>
```

## Expected Behavior
Expected to have `ServerInfo`

## Current Behavior
Currently serverInfo is part of status Info but we need to introduce network transfer rates as well.

## Possible Solution
Implement network monitors at handler layer. 

## Context
Enhancement to existing functionality. 

## Your Environment
Current `mc master` and `minio master`

**Comment by gowithplanb** [comment]
Please include the number of requests handled as well, that will make for nice graphing too.

**Comment by harshavardhana** [comment]
> Please include the number of requests handled as well, that will make for nice graphing too.

Thanks @gowithplanb looks like a good idea :+1:

**Comment by krisis** [comment]
@harshavardhana I can take this up.

**Comment by krisis** [comment]
@harshavardhana how do we represent ``server`` key in the case of a distributed setup? e.g, ``version`` and ``uptime`` could be different for nodes in a distributed setup. One way to handle this is make ``server`` key an json array with one element per node. The same question applies to ``network`` key as well. Thoughts?

**Comment by vadmeste** [comment]
by the way @krisis, I forgot to mention here that I already started to write a handler to count transferred bytes and requests count etc.. I mean all network related information. I'll commit it today and you can take the rest of the task if you want.

**Comment by vadmeste** [comment]
Storage Info (free/total storage) is removed in a previous commit, can you confirm that we don't need it anymore or it will be just moved somewhere?

**Comment by harshavardhana** [comment]
> Storage Info (free/total storage) is removed in a previous commit, can you confirm that we don't need it anymore or it will be just moved somewhere?

It is removed from "service status" - it should be added here.. @vadmeste
