### ISSUE TITLE
Incorect file sizes

### ISSUE THREAD

**Issue by billyprice1old** [minio/minio#3683]
Incorrect files size when useing mounts points /mnt/storage  i have multiples points and i dont want to invidaly need them on diffrent ports

**Comment by harshavardhana** [comment]
Can you also add screenshots and the software that you are using ?

**Comment by billyprice1old** [comment]
im useing Ubuntu 14.04 hubicfuse this branch https://github.com/nikokio/hubicfuse

mnt point /mnt/hubmic/pxl and /mnt/hubmic/ibillys3 works if i do it dirrect but i got 2 diffrent accounts so thats not possible https://vgy.me/YetKvU.png both 

1 mount https://vgy.me/QO2Ft5.png

if you need anything else just ask thanks

**Comment by harshavardhana** [comment]
We cannot technically support this behavior we used `.minio.sys` which is a directory for example at a top level "/mnt/storage" - where we create temporary files and eventually they are renamed to their actual namespace inside "/mnt/storage/bucket" if - the bucket for example is a different mount point - renames are not allowed across different mount boundaries so ultimately it will fail. 

You can follow a new bug here where are going to bring in unified namespace.

https://github.com/minio/minio/issues/3689
