### ISSUE TITLE
How to get the size of  object (object := mini.Client.GetObject(...)) ?

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3685]
I cannot find file of *minio.Object defined. How to get the size of  object (object := minioClient.GetObject(...)) ?

**Comment by harshavardhana** [comment]
> I cannot find file of *minio.Object defined. How to get the size of object (object := minioClient.GetObject(...)) ?

You can by just doing 

```go
        object, err := s3Client.GetObject("my-bucketname", "my-objectname")
	if err != nil {
		log.Fatalln(err)
	}
        st, err := object.Stat()
        if err != nil {
                log.Fatalln(err)
        }
        log.Println("Size: %d", st.Size)
````

**Comment by goodforever** [comment]
@harshavardhana Thanks!
