### ISSUE TITLE
Object deduplication

### ISSUE THREAD

**Issue by Gargron** [minio/minio#3687]
Are there any plans to implement deduplication? If the same file is uploaded more than once, to keep only one copy in the store, but reference it from two objects?

**Comment by krishnasrinivas** [comment]
@Gargron we don't have any plans of implementing de-dup in minio as we would like to keep the software simple to do one thing well - which is not lose the data (plus ease of operation).

**Comment by harshavardhana** [comment]
> Are there any plans to implement deduplication? If the same file is uploaded more than once, to keep only one copy in the store, but reference it from two objects?

As @krishnasrinivas suggested we are not planning to implement this feature.

**Comment by morph027** [comment]
If one really needs this, just have a look at http://opendedup.org/odd/ which could run in front of minio (loosing some features of course)

**Comment by qiuwei** [comment]
https://github.com/s3git/s3git can provide deduplication when integrated with minio.
