### ISSUE TITLE
Implement minio federation gateway to combine namespace

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3689]
The proxy should:
* be S3 compatible
* forward request based on bucket
* should provide regex based routing preference
* should implement ListBuckets by listing across minio instances

We should explore the best way to implement the proxy - 
* caddy plugin
* nginx module
* our own Go implementation

**Comment by krishnasrinivas** [comment]
the proxy should:
(1) route to the right minio instance based on the bucket name
    - job of reverse proxy

(2) handle ListBuckets and MakeBucket calls
    - job of our plugin

Another way to implement this requirement is:
Write a micro-service to handle (2) and use traefik for (1) This fits well in micro services environment.

traefik will redirect ListBuckets and MakeBucket calls to our microservice. For MakeBucket call, this microservice creates a bucket on one of the minio cluster and makes necessary changes to the traefik backend config to so that trakefk picks up routing changes for the new bucket created.

**Comment by krishnasrinivas** [comment]
what we decided on:

First version
----------------
ming (minio gateway) works like a content addressable gateway. This gateway is aware of all the S3 servers using a config file. The gateway gives an aggregated view of all these servers. The gateway supports only upload/download of objects. Nothing else (ex no list objects).

Users upload objects to the gateway like:
curl -X PUT http://demo.io/ming/etc/passwd --data "content"
Return data: curl http://demo.io/ming/HASH/etc/passwd

The HASH encodes the hostname of the S3 server which ming uses to route the request.

Download objects using GET like:
curl http://demo.io/ming/HASH/etc/passwd

For security, we'll have query string parameter `auth=AUTHSTRING`

Subsequent version
--------------------------
bucket based routing will be subsequent versions. But ming works only for public buckets.

curl -X PUT http://demo.io/photos/etc/passwd
http://demo.io/photos/etc/passwd

curl http://demo.io/photos/etc/passwd

**Comment by krishnasrinivas** [comment]
Project on hold as of now.

**Comment by harshavardhana** [comment]
This has moved to MSF

**Comment by nitisht** [comment]
closing this as we already have issues related to MSF #5314
