### ISSUE TITLE
admin: Add GetConfig API to get the entire `config.json` 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3698]
This is to be implemented for `mc admin config get`

```
mc admin config get <filename-to-save.json> if not prints to 'stdout' (returns the server entire `config.json`)
```

## Expected Behavior
Expected to get entire `config.json` from server to be edited on the client side and uploaded.

## Current Behavior
No way to set the configuration params for other options like logger, notification etc.

## Possible Solution
Implement a new admin API.

**Comment by GarimaKapoor** [comment]
@krisis any update on this issue?

**Comment by GarimaKapoor** [comment]
@harshavardhana if the get config code is merged, can we close this issue?

**Comment by harshavardhana** [comment]
Yes we can. Closing
