### ISSUE TITLE
config: Add a new `config.json` option to disable browser

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3701]
Bring a new config option to disable browser through `config.json` , requires bumping of the config version to '14'. 

## Expected Behavior
```json
"browser": "disable",
....
```

In `config.json`

## Current Behavior
No way to disable minio browser without just ENV variable.

## Possible Solution
Implement support for `config.json` to dictate if browser should be turned off.

**Comment by vadmeste** [comment]
What will happen for MINIO_BROWSER env variable ?

**Comment by harshavardhana** [comment]
Just like access and secret overrides the config entry.

**Comment by harshavardhana** [comment]
For a fresh config if ENV is set then it is saved to config.json if it's not a fresh config then ENV only overrides the config value upon server start.

This is how access and secret keys behave.

**Comment by vadmeste** [comment]
> For a fresh config if ENV is set then it is saved to config.json if it's not a fresh config then ENV only overrides the config value upon server start.
> 
> This is how access and secret keys behave.

+1

**Comment by balamurugana** [comment]
@harshavardhana previously we decided that `MINIO_BROWSER` env variable is to have ability to disable browser for some specific cases and we don't want to add an option into config or cli ie to keep it minimal config/cli.

Why would we add that option in `config.json` now?

**Comment by harshavardhana** [comment]
> @harshavardhana previously we decided that MINIO_BROWSER env variable is to have ability to disable browser for some specific cases and we don't want to add an option into config or cli ie to keep it minimal config/cli.
> 
> Why would we add that option in config.json now?

Actually to solve two different problems 

 - First problem is that MINIO_BROWSER is a dangling environment variable, if you look at MINIO_ACCESS_KEY it is inconsistent. So it should have been in the `config.json` in the first place.

- Second problem is it solves a situation of being able to turn off browser remotely through an administrative API.   With the implementation of SetConfig admin API we will be able to turn off features for a minio server or a set of servers (cluster) by simply uploading a new `config.json` from `mc admin config set` . We cannot achieve this cleanly with environment variables.  This is the most important reason to implement it.

**Comment by balamurugana** [comment]
> First problem is that MINIO_BROWSER is a dangling environment variable, if you look at MINIO_ACCESS_KEY it is inconsistent. So it should have been in the config.json in the first place.

As per our previous discussion, we want minio browser to be running but some users want it to be disabled hence `MINIO_BROWSER` env variable as a fall back.  Whereas `MINIO_ACCESS_KEY` is entirely different purpose where user is able to override previous key or start with new key

> Second problem is it solves a situation of being able to turn off browser remotely through an administrative API. With the implementation of SetConfig admin API we will be able to turn off features for a minio server or a set of servers (cluster) by simply uploading a new config.json from mc admin config set . We cannot achieve this cleanly with environment variables. This is the most important reason to implement it.

As `MINIO_BROWSER` is a special case, I don't know whether this option is required or not.

**Comment by harshavardhana** [comment]
> As MINIO_BROWSER is a special case, I don't know whether this option is required or not.

It just provides completeness to whatever is available for the `minio server` - just like `mc admin password` can change credentials - this just allows for turning off the browser remotely. 

Similarly we will even do turning profiler on and off (not decided yet) too for varius sub-systems - just the way how we have with _MINIO_PROFILE env.

**Comment by balamurugana** [comment]
> It just provides completeness to whatever is available for the minio server - just like mc admin password can change credentials - this just allows for turning off the browser remotely.
>
> Similarly we will even do turning profiler on and off (not decided yet) too for varius sub-systems - just the way how we have with _MINIO_PROFILE env.


I am good If its already approved by @abperiasamy.  If its possible to enable/disable browser using config file and environment variable, Its not a good idea ie two ways to do the same thing.

**Comment by harshavardhana** [comment]
> I am good If its already approved by @abperiasamy. If its possible to enable/disable browser using config file and environment variable, Its not a good idea ie two ways to do the same thing.

On the same train of thought Credentials can be changed through 4 different ways :-)
