### ISSUE TITLE
browser: Bucket policy modal should have more clues on public access using browser

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3702]
As of now after adding a bucket policy the user does not know how to access it publicly (without auth) using browser.

Add one more "copy url" button at the arrow shown in the picture below, when the user clicks the button we copy "https://host/minio/bucket/prefix" to clipboard.

![copyurl](https://cloud.githubusercontent.com/assets/634494/22677185/9fb19cc4-eca5-11e6-85cc-e8fdf675500c.png)

**Comment by deekoder** [comment]
Discussion needed since it affect usability of the product. @abperiasamy

**Comment by deekoder** [comment]
This is part of the new UX. We will decide on this after seeing the new UX.
