### ISSUE TITLE
bucket-policy: condition keys should be specific to actions

### ISSUE THREAD

**Issue by krisis** [minio/minio#3705]
In minio server, bucket policies implementation doesn't check if the specified condition keys are valid for the actions in the statement. ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html#bucket-keys-in-amazon-s3-policies
## Expected Behavior

e.g, "s3:prefix" applies only to "s3:ListBucket" and not for "s3:PutBucket" (say).
## Current Behavior

We don't check if condition keys apply to actions included in policy statements.

## Possible Solution

Not known yet.

## Steps to Reproduce (for bugs)

1. Set a policy with "s3:PutBucket" and condition key "s3:prefix"
2. PutBucketPolicy should fail when we upload a policy as above.

## Context

Deviates from AWS S3 spec.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment]
Isn't this fixed already?  What is this patch supposed to do 2665aba55525f47faf8a362d21b2aa1da10e09fa?

**Comment by harshavardhana** [comment]
> Set a policy with "s3:PutBucket" and condition key "s3:prefix"

There is no "s3:PutBucket" btw.  Perhaps you meant "s3:PutObject"

**Comment by harshavardhana** [comment]
Here is the previous github issue - https://github.com/minio/minio/issues/3657

**Comment by krisis** [comment]
Oops. I forgot that the issue was opened previously and fixed. Sorry for the confusion.
