### ISSUE TITLE
faq: How to use presignedURL ?

### ISSUE THREAD

**Issue by goodforever** [minio/minio#3707]
How to use presignedURL in html template  ?

div
	img src={{display image of presignedURL at here }} id="avatar"
div

presignedURL, _ := storage.MinioClient.PresignedGetObject(mybucket, "logo.jpg", time.Second * 24 * 60 * 60, nil)

**Comment by harshavardhana** [comment]
Please provide us more definite code with proper description of what you are trying to do. @goodforever

**Comment by harshavardhana** [comment]
Also for these type of questions please visit our slack channel https://slack.minio.io

**Comment by rakesh-eltropy** [comment]
You need to use an API which generates signed url and redirect e.g src="/api/image/render/logo.jpg".

**Comment by harshavardhana** [comment]
> You need to use an API which generates signed url and redirect e.g src="/api/image/render/logo.jpg".

Closing this as answered.  Please visit us at https://slack.minio.io for more questions @goodforever
