### ISSUE TITLE
faq: Can minio server be run on other path other than root?

### ISSUE THREAD

**Issue by Daxten** [minio/minio#3710]
Is it possible to run minio on, for example www.example.com/s3? I couldn't find this in the documentation and I think it would be a very helpfull feature. Atm if I route /s3 to minio I will get "s3 bucket could not be found" error

**Comment by harshavardhana** [comment]
// cc @krishnasrinivas can help.

**Comment by krishnasrinivas** [comment]
@Daxten 

You can use nginx like proxies to achieve this like this:

```
http {
    server {
        listen       9001;
	location /s3bucket {
		 proxy_set_header Host $http_host;
		 proxy_pass http://localhost:9000;
        }
    }
}
```

But note that `s3bucket` is actually a bucket on minio. If you want to expose more buckets you will need to add routes for those buckets as well in the nginx config.
