### ISSUE TITLE
faq: Paths containing colons do not work on Windows

### ISSUE THREAD

**Issue by tibbes** [minio/minio#3711]
The set of characters supported in object names is not the same as the real S3. In particular, paths containing colons fail when `minio` is running on Windows.

## Expected Behavior
It is possible to create objects that contain colons in the name.

## Current Behavior
When uploading an object with a colon in the name (in this case, the directory part of the name), the upload fails and the `minio` log contains the following:

```
level=error msg="Unable to create an object." cause="mkdir \\\\?\\
p\\TEST\\data\\minio\\.minio.sys\\buckets\\test-job-results\\jobs\\build-export\\1000001:32976
ory name is invalid."
```

## Possible Solution
Do not directly use object names as paths on the local filesystem (at least, not on Windows).

## Steps to Reproduce (for bugs)

1. Run `minio` on Windows.
2. Try to create the object `a/1:2/b.txt`

## Context
We're experimenting with Windows compatibility of a system that we have developed on Linux, that uses `minio` as a component.

## Your Environment
* Windows 7
* Client: AWS Java SDK
* Minio version: sorry, don't have the exact version string - latest stable as of 2017-02-03 I think.

**Comment by harshavardhana** [comment]
This is expected. Windows has limited capabilities in terms of what file if can create on the backend. S3 uses a database we don't use database we rely on backend disk abilities.

Uses Linux which will allow creation of such files happily.
