### ISSUE TITLE
api/client: [minio-java] Ability to add a region manually while generating the signed url..

### ISSUE THREAD

**Issue by rakesh-eltropy** [minio/minio#3716]
## Expected Behaviour
We don't have access to network while generating the signed url. In case network is not available, we should have a way to pass the region in the API. It would be great if this enhancement can be added.

## Current Behaviour
Currently it is falling back to default region us-east-1 in Java API.

**Comment by vadmeste** [comment]
This can be closed @harshavardhana

**Comment by harshavardhana** [comment]
minio-java now has a way to specify custom regions in the constructor. Closing this as fixed.
