### ISSUE TITLE
package: Package minio as a (virtual) storage appliance using bosh / Cloud Foundry. 

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#3718]
We got request from our community on Slack for:
Package and maintain minio as a (virtual) storage appliance using bosh / Cloud Foundry.

**Comment by beddari** [comment]
There are already several bosh releases, both for a single CF tenant and a distributed one, random google search:

https://github.com/dpb587/minio-bosh-release
https://github.com/shinji62/minio-dist-boshrelease
https://libraries.io/github/cloudfoundry-community/minio-boshrelease

It might be interesting to adopt/help maintain something like this as part of the minio project effort

**Comment by shinji62** [comment]
Already list in awesome minio.

I think @shinji62 is the only one supporting distributed version.

**Comment by harshavardhana** [comment]
Closing as duplicate of #3850
