### ISSUE TITLE
docs: fix docs to describe different minio setups

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3722]
Related: https://github.com/minio/minio/issues/3239

```
The issue is closed as I mentioned what are the agreed terminologies and our documentation is using these terminologies already. It is how we usually use it needs to be changed. We confused the community with XL etc our docs don't talk about it.

Also there are no abbrev .. list of type of setups possible with Minio

Standalone FS
Standalone Erasure
Distributed FS (shared)
Distributed Erasure
```

> The issue is closed as I mentioned what are the agreed terminologies and our documentation is using these terminologies already.

Our docs don't use these terminologies already. They should be fixed.

**Comment by harshavardhana** [comment]
> Our docs don't use these terminologies already. They should be fixed.

@krishnasrinivas  Can you list all the docs which do not follow this in consistent manner? It would help @NitishT

**Comment by GarimaKapoor** [comment]
@koolhead17 please review all the docs for this inconsistency and work with @NitishT to close this issue.

**Comment by deekoder** [comment]
Need a thorough pass on this during the USS Akira release.

**Comment by krishnasrinivas** [comment]
For example:
https://docs.minio.io/docs/minio-quickstart-guide This does not use the term `Standalone FS`

https://docs.minio.io/docs/minio-erasure-code-quickstart-guide does not use the term `Standalone Erasure`

https://docs.minio.io/docs/distributed-minio-quickstart-guide does not use the term `Distributed Erasure`

**Comment by nitisht** [comment]
Can be closed in favor of https://github.com/minio/minio/issues/4529

**Comment by harshavardhana** [comment]
Closing this is not a valid issue anymore. #4529
