### ISSUE TITLE
tests: Test suite for distributed setup.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3727]
Currently the test suites for XL and FS backend exists. Its necessary to have test suite for Minio distributed so that any undesirable changes doesn't break the distributed functionality.

**Comment by harshavardhana** [comment]
Are you going to take this ?

**Comment by hackintoshrao** [comment]
Yes, Working on it. In progress.

**Comment by GarimaKapoor** [comment]
@hackintoshrao How much more work is pending on this issue?

**Comment by hackintoshrao** [comment]
It needs refactoring of the tests too. Will continue with this once the Minio-Mesos distributed integration is finished.

**Comment by deekoder** [comment]
Need to hook up to CI.  Need to dedicated machines to test every commit. ETA: pending meeting.

**Comment by deekoder** [comment]
@hackintoshrao  can this be closed?

**Comment by hackintoshrao** [comment]
AB will be suggesting a different approach for this, this can be closed.
