### ISSUE TITLE
browser: use BEM CSS naming convention 

### ISSUE THREAD

**Issue by rushenn** [minio/minio#3731]
With BEM(Block, Element, Modifier) methodology,  classes in HTML and CSS are named with a unique approach in order to help code maintainers better understand the relationship between HTML and CSS.

http://getbem.com/naming/

**Comment by deekoder** [comment]
Needs further discussion.

**Comment by deekoder** [comment]
dependent on new UI. Track new UX as an issue.

**Comment by nitisht** [comment]
closing as duplicate of https://github.com/minio/minio/issues/5397
