### ISSUE TITLE
Reconnect to RabbitMQ after network timeouts?

### ISSUE THREAD

**Issue by kallqvist** [minio/minio#3732]
Hi, I'm currently testing minio together with lambda events over AMQP.
I have experienced some missing events that (I think) happen from the time there's been a network timeout between minio and rabbitmq and lasts until the next time minio is restarted.

## Expected Behavior
All file events should generate messages, even if the network is (temporarilly) down.

## Current Behavior
There seems to be cases where minio doesn't reconnect and messages are lost.
These are the logs from minio:
```
2/10/2017 10:28:23 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:30:51 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:35:27 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:52:47 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:53:11 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:53:24 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:53:25 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:53:26 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:54:24 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:54:27 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:54:34 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 10:54:45 AMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 12:03:03 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 12:34:18 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 1:01:02 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 1:34:13 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 2:02:34 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 2:36:41 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 2:47:10 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
2/10/2017 3:40:45 PMFailed to fire hook: write tcp 10.42.153.50:50974->10.42.157.156:5672: use of closed network connection
```

## Possible Solution
- Maybe I should configure my RabbitMQ server differently?
- More reconnect attempts in minio maybe?
- Perhaps some type of disk-based solution where failed events are stored on harddrive until message backend is available again?
- I'm using hostname to reach RabbitMQ and the IP changes everytime it reconnects, is Minio maybe caching the IP somewhere?

## Steps to Reproduce (for bugs)
1. Setup minio and bucket events to RabbiqMQ
2. Restart RabbitMQ (or pull the cable a while before reconnecting it again)
3. Minio will now fail sending all messages until restarted

## Context
I'm trying to index all files added to minio in a database to make them searchable.
I've found this line in minio source that I assume should deal with what I'm talking about:
https://github.com/minio/minio/blob/1b4bb94ac4fd328e49af2d5e0fe23c912335ed9b/cmd/notify-amqp.go#L95

However; it doesn't seem to do that for me in this scenario.

## Your Environment
Minio docker image, I sadly don't know exact version.
I'm running minio:edge from dockerhub but it's been running for a few weeks so I know it's not the latest at least.

**Comment by kallqvist** [comment]
Btw; I just read about the new webhook support in minio, I will try that out instead of AMQP.

I guess that would be a new network connection opened for every event message?
In that case I think that would be a better fit for the (not so stable) network I'm running minio on.

**Comment by harshavardhana** [comment]
ON a network disconnect there should code already to reconnect back. 

> I guess that would be a new network connection opened for every event message?

It is not a new connection opened but upon a network failure there should be a transparent reconnect.

**Comment by harshavardhana** [comment]
Will validate and update here @kallqvist

**Comment by harshavardhana** [comment]
ping @donatello

**Comment by donatello** [comment]
I am able to reproduce this, so bug is confirmed. Working on finding a fix.
