### ISSUE TITLE
faq: Is Minio production ready?

### ISSUE THREAD

**Issue by peacemakr** [minio/minio#3737]
is there a doc explaining use cases? 
is it production ready for large scale applications?

where and how are objects stored? is storage distributed?

**Comment by harshavardhana** [comment]
> is there a doc explaining use cases?

Here are some curated non exhaustive list of use cases - https://github.com/minio/awesome-minio

> is it production ready for large scale applications?

Yes it is production ready, how large is your requirement? can you explain more about the "large scale" application here?  - with this information we can provide better assessment. 

> where and how are objects stored? is storage distributed?

There are two primary modes of operation Minio server provides i.e 

|    Minio    | FS | Erasure | Stability |
|:-----------:|:----:|:----:|:---:|
| Standalone  | x  | x  | Stable |
| Distributed | x  | x  | Stable |

Objects in FS(filesystem) mode are kept as is on the backend disk just like files and folders,  Objects in erasure mode are stored as erasure coded chunks across all backend disks.

**Comment by peacemakr** [comment]
I'm developing a social media app, so files, photos, etc need to be stored somewhere.

Is performance better than NFS, CephFS etc?

Which mode is better (performance wise)?

How easy/difficult it is to switch from standalone to distributed mode?

**Comment by harshavardhana** [comment]
> I'm developing a social media app, so files, photos, etc need to be stored somewhere.

Great.

> Is performance better than NFS, CephFS etc?

We don't have any comparison benchmarks - Minio differentiates itself with simplicity and reliability. performance if its better is a plus but our goal is to keep the data reliable. 

> Which mode is better (performance wise)?

Depends on the use case and reliability requirements.  Using Filesystem is easier but its as reliable as your backend disk. Erasure code provides data protection and reliability.

> How easy/difficult it is to switch from standalone to distributed mode?

Quite easy you can setup a new cluster `mc mirror` your data from standalone to distributed.

**Comment by harshavardhana** [comment]
Please join us on https://slack.minio.io for further questions. Closing this issue as answered.
