### ISSUE TITLE
Settings do not work

### ISSUE THREAD

**Issue by dswd** [minio/minio#3738]
In the latest version (2017-01-25) clicking the "Settings" menu item just reloads the page but does not show the settings. That worked in the previous version.

I reported this bug before and I think it has been fixed but the whole subproject `minio-browser` does not exist anymore and no bugfix release has been issued. Please note that this bug is a complete show-stopper for me.

## Expected Behavior
Clicking on "Settings" should open the settings panel

## Current Behavior
Clicking on "Settings" just reloads the page

## Steps to Reproduce (for bugs)
1. Click on "Settings"

## Context
I can't open the settings, duh!

## Your Environment
* Version used: 2017-01-25T03-14-52Z

**Comment by harshavardhana** [comment]
Fixed by #3656

**Comment by harshavardhana** [comment]
> I reported this bug before and I think it has been fixed but the whole subproject minio-browser does not exist anymore and no bugfix release has been issued. Please note that this bug is a complete show-stopper for me.

Until we make a release you could use minio master using 'go get' or use `docker pull minio/minio:edge` as a workaround for now.
