### ISSUE TITLE
ENJOYING_THIS_PROJECT="SayThankYou"

### ISSUE THREAD

**Issue by pascalandy** [minio/minio#3746]
Here is the place to say thank you to folks who are working hard on this project.

« One of the greatest ways to show your appreciation to open source projects you enjoy is to open an issue that let people say thank you »

_Disclaimer: I don't have any kind of connexion or personal interest with maintainers(s) of this project. Pure gratitude here._

**Comment by pascalandy** [comment]
Thank you thank you!! Love Minio
_\m| 💯

**Comment by krishnasrinivas** [comment]
@pascalandy thanks for your support!!

**Comment by harshavardhana** [comment]
Thanks @pascalandy
