### ISSUE TITLE
How can we Docker Exec in MC container?

### ISSUE THREAD

**Issue by pascalandy** [minio/minio#3747]
Hey folks,
Now that I have a [solid setup](http://blog.pascalandy.com/the-complete-guide-to-attach-a-docker-volume-with-minio-on-your-docker-swarm-cluster/) with Minio and Docker Volumes, I need to use the Minio CLI via Docker.

I cannot find how to enter the container via Docker Exec. From the [docs](https://docs.minio.io/docs/minio-client-quickstart-guide), I can't find any help.

### Launch container

```
docker run -d \
--name minio-client \
--restart always \
minio/mc
```

### Docker exec

```
docker exec -it minio-client sh ls my-bucket
```

This is not working. I guess I need to define the entrypoint or something. 
Thanks for your help!

Cheers!

**Comment by harshavardhana** [comment]
You cannot do that @pascalandy - `mc` is a command tool which just runs and exits.  You can just do 

```
docker run --rm -v /etc/mc:/root/.mc minio/mc config host add myserver <minio_endpoint> <access_key> <secret_key>
```

```
docker run --rm -v /etc/mc:/root/.mc minio/mc ls myserver/my-bucket
```

**Comment by pascalandy** [comment]
Got it! Will test this :)

**Comment by harshavardhana** [comment]
> Got it! Will test this :)

Closing as answered.
