### ISSUE TITLE
Minio app on Cloudron

### ISSUE THREAD

**Issue by gramakri** [minio/minio#3757]
Hi Guys, thanks for minio! The Cloudron community (@dswd) has contributed a minio app for Cloudron. You can try it out here - https://my-demo.cloudron.me (install minio from the App Store).

The code for the app itself is at https://git.cloudron.io/dswd/minio-app and also has selenium based tests at https://git.cloudron.io/dswd/minio-app/tree/master/test.

Would you be OK in adding a "Install on Cloudron" section to the project's README? Alternately, a page in the docs at http://docs.minio.io/docs/minio-quickstart-guide ? If so, I can submit a PR for either or both.

**Comment by harshavardhana** [comment]
Thanks @gramakri for opening the bug and supporting Minio - we will get back to you.

**Comment by koolhead17** [comment]
@gramakri thanks for all your hard work.

Please add the document contribution to cookbook to https://github.com/minio/cookbook, follow the same style guide like others which are added.

Also please add the use case to awesome-minio https://github.com/minio/awesome-minio, this will let others in the community to know more about the projects.

Hope it helps.

**Comment by GarimaKapoor** [comment]
@gramakri we are planing to introduce a section of one click deploys which be the ideal case for listing Cloudron. Till then like @koolhead17 suggested please add your use case under https://github.com/minio/awesome-minio.

**Comment by gramakri** [comment]
@GarimaKapoor @koolhead17 thanks. I made https://github.com/minio/awesome-minio/pull/43 for awesome-minio.

**Comment by harshavardhana** [comment]
> @GarimaKapoor @koolhead17 thanks. I made minio/awesome-minio#43 for awesome-minio.

Thanks @gramakri merged. Closing this.

**Comment by gramakri** [comment]
@harshavardhana https://github.com/minio/cookbook/pull/137 has the cookbook PR
