### ISSUE TITLE
Deleting files while a node is offline doesn't actually delete

### ISSUE THREAD

**Issue by jhixson74** [minio/minio#3768]
If you delete a file when a node is offline in a distributed configuration, the file is not actually deleted.

## Expected Behavior

\

Expected behavior is that files that are deleted are actually deleted.

## Current Behavior

After file is deleted and offline node comes online again, the file is in some sort of limbo state where it is there sometimes and not there sometimes. 

## Steps to Reproduce (for bugs)

1. Create a test bucket
2. Copy files to test bucket
3. Offline a node
4. Delete file(s)
5. Online the node that was offline
6. List contents of bucket (For full effect, do this multiple times to see file flip flop between being there and not being there). 

## Context

This issue concerns me since I expect deleted files to be removed. 

## Your Environment

* Version used:

RELEASE.2017-02-16T01-47-30Z

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:

FreeBSD minio1.divinix.org 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

* Link to your project:

http://www.freebsd.org
http://www.freenas.org

**Comment by kmoore134** [comment]
I've also duplicated this here as well. It also happens if you upload a file while a node is offline, refreshing sometimes shows the new file, other times not.

**Comment by harshavardhana** [comment]
This is actually on purpose.  Listing always lists objects from one of the disks which are basically changed every time a list request comes to the server. Until you heal the object the listing will have inconsistent output. The reason we did that is to avoid hitting all the disks. Listing is can be an expensive operation - it was a design decision.

**Comment by jhixson74** [comment]
How does one go about healing ?

**Comment by harshavardhana** [comment]
> How does one go about healing ?

It is a REST API currently available only in master and under testing.  When its done you would use `mc admin heal` to heal the disks, buckets and objects.

**Comment by harshavardhana** [comment]
Alternatively you can use the SDK  - https://github.com/minio/minio/tree/master/pkg/madmin directly - https://github.com/minio/minio/blob/master/pkg/madmin/examples/heal-object.go

**Comment by harshavardhana** [comment]
Closing this as answered. Please reopen if you have more questions.
