### ISSUE TITLE
Suggest `mc config host remove` alias

### ISSUE THREAD

**Issue by alexellis** [minio/minio#3770]
## Expected Behavior

With most UNIX command-line tools `rm` is acceptable in the place of `remove`:

```
docker rm
git rm
git remote rm upstream
rm -rf ./test.file
mc rm play/bucket1/test_file.txt
```

It felt jarring as a UX that I could not type in `mc config host rm <host_config>` and I would like to suggest the change.

@harshavardhana if you're OK with the suggestion I don't mind looking into the code and making the change.

Alex

**Comment by harshavardhana** [comment]
This is neat idea - i will let @abperiasamy provide his inputs as well.

**Comment by harshavardhana** [comment]
Closing this in favor of mc issue - https://github.com/minio/mc/issues/2027
