### ISSUE TITLE
Access to files denied

### ISSUE THREAD

**Issue by iamso** [minio/minio#3774]
Hi

In your minio shopping app demo you create a public link to the image. I have copied this line of code and tried this with my minio installation and I get an access denied error.

```javascript
var publicUrl = minioClient.protocol + '//' + minioClient.host + ':' + minioClient.port + '/' + minioBucket + '/' + obj.name
```

## Expected Behavior
I would expect to see the image in the browser when accessing the url.

## Current Behavior
I get the following error:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied.</Message>
    <Key></Key>
    <BucketName></BucketName>
    <Resource>/testbucket/IMG_0278.JPG</Resource>
    <RequestId>3L137</RequestId>
    <HostId>3L137</HostId>
</Error>
```

## Steps to Reproduce (for bugs)
1. install minio with homebrew `brew install minio`
2. start the service `brew services start minio` ([fix the .plist file](https://github.com/minio/minio/issues/3564) before ;))
3. log in to the web interface
4. create a bucket
5. upload a file
6. use the node.js minio client, initialize client with server credentials
7. and add the following code:
```javascript
var stream = minioClient.listObjects(minioBucket,'', true)
stream.on('data', function(obj) {
  // Lets construct the URL with our object name.
  var publicUrl = minioClient.protocol + '//' + minioClient.host + ':' + minioClient.port + '/' + minioBucket + '/' + obj.name
  console.log(publicUrl);
});
```
8. copy the generated url and paste it into the browser

## Context
I was trying to load a file through the browser, like you do in the shopping app demo.

## Your Environment
* Version used: 2017-02-16T01:47:30Z
* Environment name and version (e.g. nginx 1.9.1): with and without MAMP PRO 4 as proxy
* Server type and version: MAMP PRO 4.1
* Operating System and version: macOS Sierra

What could this be? Do I have to change something?

Thanks

**Comment by iamso** [comment]
Never mind, I found it. 😊

For those having the same issue, either use the command line client to set the policy for the bucket to public, more [here](https://docs.minio.io/docs/minio-client-complete-guide#policy), or use the web interface, where you click on the three dots next to the bucket name and add a row with the prefix `*` and `Read and Write` permissions.

**Comment by Sherriluneau** [comment]
It was a sad day once i got threw access denied

**Comment by thienly** [comment]
i got the same issue even though i set public permission for the bucket

**Comment by rcermeno** [comment]
> Never mind, I found it. 
> 
> For those having the same issue, either use the command line client to set the policy for the bucket to public, more [here](https://docs.minio.io/docs/minio-client-complete-guide#policy), or use the web interface, where you click on the three dots next to the bucket name and add a row with the prefix `*` and `Read and Write` permissions.

@iamso how to do this same but from mc cli?

**Comment by cniackz** [comment]
Hello @rcermeno 

In order to do that, you can do this: `mc policy set public myminio/bucket` where `myminio` is the `alias`

Example:
```
$ mc policy get myminio/bucket
Access permission for `myminio/bucket` is `private`
$ mc policy set public myminio/bucket
Access permission for `myminio/bucket` is set to `public`
$ mc policy get myminio/bucket       
Access permission for `myminio/bucket` is `public`
```
