### ISSUE TITLE
PUT with no size (enhancement)

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3777]
## Expected Behavior
A PUT with no size should work and the size should be limited to 5Gbits (the optimization should still work on this configuration) there is case where producing the data is slow, streaming the file has a benefit and we know (or accept) that the limit for this style of 'single' PUT it 5Gbits

## Current Behavior
HTTP 411

## Possible Solution
a default value ;-)

_Non blocking for me I can add the size_

**Comment by harshavardhana** [comment]
Allowing this breaks S3 compatibility, S3 requires us to use Content-Length precisely for an incoming PUT request. It is requirement for how the payload signature is calculated even on the client side so if you are using signature v4 then Content-Length is what you need to send anyways. 

This enhancement might not work because of these reasons.

**Comment by dcharbonnier** [comment]
Correct me if im wrong but s3 is a subset of minio and for example you can't upload a 20go file with s3 but you can with minio. Anyway, just a nice to have and easy to implement but nothing very important for now.

**Comment by harshavardhana** [comment]
> Correct me if im wrong but s3 is a subset of minio and for example you can't upload a 20go file with s3 but you can with minio. Anyway, just a nice to have and easy to implement but nothing very important for now.

You can upload 20G with S3 using multipart API what minio libraries do just to abstract those details and make them look like a single upload operation transparently upto 5TB object which is the maximum S3 protocol mandates. 

So a putObject() as a client library call is not always a single PUT operation, depending on the file size it can transparently do multi-part upload which are basically collection of calls splitting the incoming data. 

Even there a single chunk that is uploaded with content-length.

**Comment by harshavardhana** [comment]
@dcharbonnier closing this github issue, If AWS S3 ends up supporting `Transfer-Encoding: chunked`  i.e when Content-Length is not set for PUT and POST operations until then we won't be supporting this scenario.
