### ISSUE TITLE
docker registry 2.6 doesn't work with minio:edge

### ISSUE THREAD

**Issue by gouthamve** [minio/minio#3779]
I am running the docker registry `registry:2.5` with `minio:edge`. The uploads are not happening and are failing with `err=blob unknown`.
When I revert to `registry:2.5` the uploads proceed fine.

## Expected Behavior

`registry:latest` should work with `minio:edge`

## Current Behavior

Uploads fail.

## Steps to Reproduce (for bugs)

1. Run `minio:edge` and `registry:latest`
2. Connect the two
3. Upload an image

## Your Environment

* Version used: `minio:edge`
* Server type and version: i7
* Operating System and version: Archlinux Kernel 4.9.8-1-ARCH

**Comment by harshavardhana** [comment]
@Gouthamve this looks like a setup issue on your end here is a following config that works fine with latest release and minio edge branch 

```
docker push  localhost:5000/newtag
The push refers to a repository [localhost:5000/newtag]
47e7b2b2995a: Pushed 
ef5e49ab7833: Pushed 
d99b55828607: Pushed 
ea7dfbea9728: Mounted from minio2 
7c6aae281ebc: Mounted from minio2 
626236f77c64: Mounted from minio2 
35dcfec0d419: Mounted from minio2 
19ff851c0a5f: Mounted from minio2 
2c8604a15a0d: Mounted from minio2 
d0b5d4ff1582: Mounted from minio2 
7cbcbac42c44: Mounted from minio2 
latest: digest: sha256:f60ffb15201400ee6209526bdbf4150796e090b5c350c4161a6fa6c62c1097ed size: 2616
```

https://gist.github.com/harshavardhana/149509d34dca14e23a195e30a8be8f0b

**Comment by gouthamve** [comment]
Hi,

Here are the logs: http://pastebin.com/BxLmuigb, also attached
[registry.txt](https://github.com/minio/minio/files/789149/registry.txt)

I am running it behind a reverse proxy (fabio) that proxies to a docker forwarded port on the host.
Given how its working for you, I am pretty sure its a setup issue on my end, will get back and thanks a ton for looking into it!

**Comment by harshavardhana** [comment]
> Hi,
> 
> Here are the logs: http://pastebin.com/BxLmuigb, also attached
> registry.txt

@Gouthamve what is the error that you see when you do `docker push` ? does it wait and timeout?

**Comment by gouthamve** [comment]
@harshavardhana It starts with: https://i.imgur.com/Udi9KMu.png and ends with: https://i.imgur.com/DrhamqO.png

**Comment by harshavardhana** [comment]
> @harshavardhana It starts with: https://i.imgur.com/Udi9KMu.png and ends with: https://i.imgur.com/DrhamqO.png

Can you use to 'registry:2.6' rather than using 'registry:latest' ?

**Comment by harshavardhana** [comment]
> Can you use to 'registry:2.6' rather than using 'registry:latest' ?

Ah looks like that doesn't make any difference..

**Comment by gouthamve** [comment]
Nope. I tried with that already!

**Comment by harshavardhana** [comment]
@Gouthamve - i would suggest you try minio latest release instead of 'edge'  and let us know? 

```
docker pull minio/minio:RELEASE.2017-02-16T01-47-30Z
```

**Comment by gouthamve** [comment]
Hmm, makes no difference.

Also found something that made it clear that its definitely an issue with registry and not minio. So I now try to do: `docker push 172.17.0.4:5000/gouthamve/ubuntu` and it works but `docker push registry.beast.geekon.tech/gouthamve/ubuntu` fails!

This might be something to do with my reverse proxy I guess. I will stick to registry:2.5 for now. This can be closed, but leaving it open in-case you think its an issue with minio.

Thanks and sorry for the trouble!

**Comment by harshavardhana** [comment]
> Also found something that made it clear that its definitely an issue with registry and not minio. So I now try to do: docker push 172.17.0.4:5000/gouthamve/ubuntu and it works but docker push registry.beast.geekon.tech/gouthamve/ubuntu fails!

We will verify this on our end why this might happen, it could also be potentially something odd interaction issue as well. 2.6 has changed a lot of things from 2.5.x so it could be a bug. 

Please loop us in if you are reporting this upstream, if at all it potentially points to our problem.

> This might be something to do with my reverse proxy I guess. I will stick to registry:2.5 for now. This can be closed, but leaving it open in-case you think its an issue with minio.
> 
> Thanks and sorry for the trouble!

No not all happy to help anytime.

**Comment by harshavardhana** [comment]
Closing this in favor of upstream bug - https://github.com/docker/distribution/issues/2177

**Comment by zllovesuki** [comment]
See my issue: docker/distribution#2205

`registry:2.6` changed its behavior on multipart upload.
