### ISSUE TITLE
docs: AWS S3 credentials URL needs to be fixed.

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#3781]
The URL for AWS S3 credentials on https://docs.minio.io/docs/minio-client-quickstart-guide pointing to wrong location. We can replace it with http://docs.aws.amazon.com/AmazonS3/latest/gsg/SigningUpforS3.html

**Comment by harshavardhana** [comment]
Perhaps http://docs.aws.amazon.com/general/latest/gr/aws-security-credentials.html
