### ISSUE TITLE
Swagger doc minio server endpoints

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3788]
Could we get some frontend-friendly docs for the HTTP request and response details, so that curl users have an easier time manipulating the minio REST API?

**Comment by harshavardhana** [comment]
Minio supports AWS S3 exactly - we reply in compatible way similar to S3 - AWS S3 documents these in details which we ourselves use and write libraries http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketDELETE.html 

This is one of the reason why we didn't see the need to document these. So what you do with AWS S3 just do that with Minio.

**Comment by harshavardhana** [comment]
You could also use - https://github.com/asciimoo/wuzz for HTTP inspection.
