### ISSUE TITLE
Clarify health status, readiness endpoint usage

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3789]
For the ultimate ops experience, could minio document which endpoints provide health checks, readiness, that sort of thing, and what a curl user can expect about how to make the call and how to interpret the results?

**Comment by harshavardhana** [comment]
There is a work in progress API which is currently available only in master 

https://github.com/minio/minio/tree/master/docs/admin-api
https://github.com/minio/minio/tree/master/pkg/madmin

Once a server is released with these support we will be publishing them.

**Comment by deekoder** [comment]
We have #3800 to address health status usage. Closed as duplicate.
