### ISSUE TITLE
Can not connect to minio [ERROR: SSL certificate verification failure]

### ISSUE THREAD

**Issue by vijayrawatsan** [minio/minio#3794]
I have updated the .s3cfg file as per the docs @ https://docs.minio.io/docs/s3cmd-with-minio

## Expected Behavior
Demo at https://docs.minio.io/docs/s3cmd-with-minio should work. 
And I should be able to create and list buckets.

## Current Behavior
$ s3cmd ls
ERROR: SSL certificate verification failure: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

$ s3cmd mb s3://mybucket
ERROR: SSL certificate verification failure: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

## Context
I was trying to setup minio server for my integration tests. Could not get it working.

## Your Environment
Versions:
s3cmd-1.6.0
MacOS Sierra, v10.12.3 (16D32)

**Comment by harshavardhana** [comment]
Looks like an upstream issue which was fixed - https://github.com/s3tools/s3cmd/commit/a6ffd5b5d31021e27a76f1f8255448c36a453c93 

There has been no release yet.

**Comment by harshavardhana** [comment]
You can alternatively use 

 - [mc](https://github.com/minio/mc)
 - [aws cli](http://docs.minio.io/docs/aws-cli-with-minio)

**Comment by harshavardhana** [comment]
FWIW updating to new `s3cmd` works fine from github works, closing this bug as upstream issue. 

```
s3cmd ls s3://
2017-02-23 21:27  s3://5555555
2017-02-23 21:26  s3://555555555
2017-02-23 22:06  s3://deg
2017-02-23 20:36  s3://devendra
2017-02-23 20:45  s3://iwashere
2017-02-23 23:40  s3://mikef
2017-02-23 21:10  s3://test
2017-02-23 22:09  s3://thejoj
```
