### ISSUE TITLE
S3 API compatibility documentation

### ISSUE THREAD

**Issue by emil-nasso** [minio/minio#3797]
Hi guys! This looks like a great project. Great job so far. :)

I did some experiments today with directus ( https://getdirectus.com/ ) and minio as a backend for files (directus has support for s3). I ran into and problem. It doesn't seem like a minio supports acl. In this application, that means that minio is not compatible with the s3 api.

Is there documentation anywhere that states what features are lacking in minio or how "complete" the api is?

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/minio-server-limits-per-tenant has a list of APIs not supported.

**Comment by harshavardhana** [comment]
This is already documented, closing this bug as answered.
