### ISSUE TITLE
Allow binding to a hostname

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3799]
The minio server provides a `--address` flag for binding to an IP, but it would be more convenient to be able to bind to a hostname. Could we add this ability to `--address`?

**Comment by harshavardhana** [comment]
It should already work you can bind to a resolvable hostname. If your hostname doesn't resolve add a `/etc/hosts` entry.

**Comment by mcandre** [comment]
Excellent! In that case, could the flag description be updated to say "... can be bound to an address" rather than just an IP, for clarity?
