### ISSUE TITLE
Serve on 0.0.0.0:9000 by default

### ISSUE THREAD

**Issue by mcandre** [minio/minio#3801]
If minio used `--address 0.0.0.0:9000` by default, then the service would automatically integrate better in environments with multiple, complex network interfaces, such as different Kubernetes hostnames. The user experience is more likely to be "just works".

Security-minded folks might balk at this, but they probably want to customize `--address` anyway, so nothing wrong with a helpful default.

What do you think of adopting this default?

**Comment by harshavardhana** [comment]
Currently minio does bind to '0.0.0.0:9000' automatically by default. what is the issue right now?

**Comment by harshavardhana** [comment]
Closing this as how minio server binds right now. Minio server by default binds to all interfaces and all ips. Including ipv6.

**Comment by ruben-herold** [comment]
[root@store01 conf.d]# /opt/minio/bin/minio version
Version: 2018-12-06T01:27:43Z
Release-Tag: RELEASE.2018-12-06T01-27-43Z
Commit-ID: 40852801ea63d0e10f220c0d7d2a8d6a8efa5688

does not listen on ipv6 :

telnet localhost 9000
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
