### ISSUE TITLE
307 Temporary Redirect issue with nginx

### ISSUE THREAD

**Issue by marcosterland** [minio/minio#3802]
## Expected Behavior
Accessing minio via nginx in the browser should show the webUI.

## Current Behavior
minio answers with `307 Temporary Redirect` to `/minio/`.
The browser then tries to load `example.com/minio`, which is obviously not working (404).

## Context
I want to have multiple minios running on one server behind a nginx proxy. I'm not sure, whether this is a bug or just a configuration problem.
This is my nginx config:
```
server {
    listen 80;
    server_name example.com;
    location /foo/ {
        proxy_pass         http://localhost:9100/;
        proxy_set_header   Host $host;
    }
    location /bar/ {
        proxy_pass         http://localhost:9200/;
        proxy_set_header   Host $host;
    }
}
```

## Steps to Reproduce (for bugs)
1. start a minio, e.g. `minio server --address :9100 /mnt/foo`
2. setup nginx with config above
3. open example.com/foo in browser

## Your Environment
* Version used: RELEASE.2017-02-16T01-47-30Z
* Environment name and version: nginx 1.10.0
* Server type and version: Ubuntu 16.04.1

**Comment by krishnasrinivas** [comment]
```
server {
    listen 80;
    server_name example.com;
    location /foo/ {
        proxy_pass         http://localhost:9100/;
        proxy_set_header   Host $host;
    }
    location /bar/ {
        proxy_pass         http://localhost:9200/;
        proxy_set_header   Host $host;
    }
}
```

You can add one more entry:
```
    location /minio/ {
        proxy_pass         http://localhost:9100/;
        proxy_set_header   Host $host;
    }
```

but with this you can get UI only for one minio server.

what you can do is something like this:
```
    location /minio1 {
       rewrite ^/minio1(.*)$ /minio$1 permanent;
        proxy_pass         http://localhost:9100/;
        proxy_set_header   Host $host;
    }
    location /minio2 {
       rewrite ^/minio2(.*)$ /minio$1 permanent;
        proxy_pass         http://localhost:9200/;
        proxy_set_header   Host $host;
    }
    location /minio3 {
       rewrite ^/minio3(.*)$ /minio$1 permanent;
        proxy_pass         http://localhost:9300/;
        proxy_set_header   Host $host;
    }
```

with this the UI has to be accessed as example.com/minio1/ example.com/minio2/ example.com/minio3/

**Comment by marcosterland** [comment]
No, sorry. `rewrite ^/minio2(.*)$ /minio$1 permanent;` makes it again looking for example.com/minio.

**Comment by krishnasrinivas** [comment]
> No, sorry. rewrite ^/minio2(.*)$ /minio$1 permanent; makes it again looking for example.com/minio.

I see, maybe you can remove permanent and it works? But you get the idea ... you will have to redirect to the appropriate minio instance but with path `/minio/....` You can see how to configure nginx with that. If you figure it out you can reply here so that it helps others, if not we'll try to figure it out and let you know.

**Comment by marcosterland** [comment]
Thanks @krishnasrinivas for your help so far! I'll let you know, if I find the solution.
The reason, why I think it's something in minio is the following. When I enter the URL `example.com/foo` in Chrome with developer console, I can see the following requests & responses:
```
Request:
Request URL:http://example.com/foo
Request Method:GET
Status Code:301 Moved Permanently
Remote Address: <removed>
```
```
Response:
Connection:keep-alive
Content-Length:194
Content-Type:text/html
Date:Fri, 24 Feb 2017 21:23:03 GMT
Location:http://example.com/foo/
Server:nginx/1.10.0 (Ubuntu)
```
```
Request:
Request URL:http://example.com/foo/
Request Method:GET
Status Code:307 Temporary Redirect
Remote Address:<removed>
```
```
Response:
Connection:keep-alive
Content-Length:43
Content-Type:text/html; charset=utf-8
Date:Fri, 24 Feb 2017 21:23:03 GMT
Location:/minio/
Server:nginx/1.10.0 (Ubuntu)
Vary:Origin
```
```
Request:
Request URL:http://example.com/minio/
Request Method:GET
Status Code:404 Not Found
Remote Address:<removed>
```
Notice the _Location_ attributes in the responses. The first response comes from nginx and basically redirects me to the same URL but with a slash appended. The second response is from minio. It wants to redirect me, but chops off the host. I would expect to be redirected to `http://example.com/foo/minio/`.

When I access `http://example.com/foo/minio/` manually, it succeeds. But all its resources can't be accessed, since they're addressed with e.g.  `http://example.com/minio/logo.svg` (missing foo).

Is there a way to tell minio its base URL?

**Comment by harshavardhana** [comment]
This happens because all incoming web requests - which are not signed with any AWS signatures are redirected to `/minio` assuming the request is from Web browser.

**Comment by krishnasrinivas** [comment]
@marcosterland my earlier suggestion is incorrect. We use the URL path `/minio/` in the client side for logic.

What you can do is make nginx listen on different ports, and redirect each port to a minio instance.

**Comment by marcosterland** [comment]
For my specific problem, I've found a solution, where I don't need the webUI.
But in case someone has a similar problem and googles to this issue, this might be a solution:
```
server {
    listen 80;
    server_name example.com;
    location ~ foo\/(?!.*minio).* {
        proxy_pass         http://localhost:9100/;
        proxy_set_header   Host $host;
    }
    location /foo/minio/ {
        proxy_pass         http://localhost:9100/minio/;
        proxy_set_header   Host $host;
    }
}
```
This RegExp magic seems to do the job! :smiley: 
On `example.com/foo` you should get your usual S3 service, whereas `example.com/foo/minio` should proxy you to the webUI.
Nevertheless, thanks @krishnasrinivas and @harshavardhana for your time & help!
