### ISSUE TITLE
browser: duplicate file entries after sort by name/size/last modified

### ISSUE THREAD

**Issue by minamitsubame** [minio/minio#3809]
Each currently listed files will have another entry clone after a click on Name/Size/Last Modified, and only the newly added entries are sorted.

## Expected Behavior
Once trigger sort by Name/size/last modified, all existing file entries reordered by the specified field, no entry should be added in browser.

## Current Behavior
Each time you click Name/Size/Last Modified, entries in the list are doubled. And only newly added entries are sorted. If you have 2 files in a bucket, and you click any of Name/Size/Last Modified for 3 times, you will see 16 entries. However, only the last 8 entries are guaranteed sorted.
Once you refresh the page, all duplicates are gone, but you also loss the sorting order.

## Steps to Reproduce (for bugs)
(Pretty clear in current behavior)

## Context
Look for the last modified file.

## Your Environment
* Version used: 2017-02-16T01:47:30Z
* Environment name and version (e.g. nginx 1.9.1): minio/minio docker image
* Server type and version: Verified the issue on various platforms
* Operating System and version: Ubuntu 16.04 / Cent OS 7
* Browser: Chrome  56.0.2924.87

**Comment by harshavardhana** [comment]
Can you provide some screenshots for us as well @minamitsubame  - Thanks

**Comment by rushenn** [comment]
@harshavardhana Look like there is an issue in the sorting
![1](https://cloud.githubusercontent.com/assets/13393018/23374639/1cec980a-fd4b-11e6-8626-005e395370f7.gif)

**Comment by minamitsubame** [comment]
Screenshot above reveals the issue pretty well. Thank you @harshavardhana

**Comment by harshavardhana** [comment]
Fixed by #3813
