### ISSUE TITLE
Duplicated notify entries doesn't throw errors

### ISSUE THREAD

**Issue by bchevallereau** [minio/minio#3812]
By mistake, I created 2 `kafka` objects in the `notifiy` objects in `config.json` and I was confused why it was not working.

## Expected Behavior
An error should be thrown at the server startup if there are duplicated notification definition.

## Current Behavior
Not sure

**Comment by harshavardhana** [comment]
To be fixed as part of - https://github.com/minio/minio/issues/3697

**Comment by vadmeste** [comment]
I don't see a way to do this without rewriting json unmarsheler. This is also the same thing for all other fields in the config file (like entering access key twice).

**Comment by harshavardhana** [comment]
> I don't see a way to do this without rewriting json unmarsheler. This is also the same thing for all other fields in the config file (like entering access key twice).

We don't need to rewrite we need to validate if there are multiple entries we just fail.

**Comment by vadmeste** [comment]
> We don't need to rewrite we need to validate if there are multiple entries we just fail.

We can't detect if there are multiple entries. Once the json is loaded into the structure, each field will contain the last duplicated entry. Aren't we going to see if we can migrate to yml here too ?

**Comment by harshavardhana** [comment]
> We can't detect if there are multiple entries. Once the json is loaded into the structure, each field will contain the last duplicated entry. Aren't we going to see if we can migrate to yml here too ?

Yes we are that is why `mc` takes the bait first :-) @vadmeste

**Comment by donatello** [comment]
One approach is suggested here: https://stackoverflow.com/questions/27927035/golang-detecting-duplicate-keys-in-json-input
