### ISSUE TITLE
Add support for mysql in event notifications

### ISSUE THREAD

**Issue by stephenreay** [minio/minio#3818]
MySQL is generally regarded as the most popular open source database in the world.

Since v5.7.8, mysql (and the downstream forks) has supported a JSON column type. Documentation is available here: https://dev.mysql.com/doc/refman/5.7/en/json.html

The idea of supporting mysql was raised in #2739, and squashed with a comment of "mysql is going proprietary". I believe that is a too-simplistic view of the MySQL ecosystem.

In recent years a number of open source forks have emerged, notably MariaDB and Percona Server/ Cluster. These two retain protocol compatibility (i.e. they're drop in replacements for oracle mysql), while implementing features either not available at all in oracle mysql, or only available in enterprise editions.

For the purposes of this discussion, the term `mysql` might refer to oracle mysql or any of the compatible forks.

## Expected Behaviour
I would expect this should work in essentially the same manner as the postgres target already works.

## Current Behaviour
Currently postgres is the only relational DB supported natively as a notification event target

## Possible Solution
In other languages, SQL databases are often accessible via a high-level API (e.g. PHP's PDO). As I understand it, Go's `database/sql` package. This could allow for additional SQL db's being supported with (presumably) final work.

## Context
In an environment with several applications already using a mysql server or cluster, it is much more efficient to re-use existing services (the mysql server(s)) than requiring a postgres server (or cluster if you want HA) just to get SQL-based access to notifications from minio.

**Comment by harshavardhana** [comment]
ping @donatello
