### ISSUE TITLE
Reverse proxy (nginx) configuration?

### ISSUE THREAD

**Issue by k0nsl** [minio/minio#3823]
I am having some issues with my reverse proxy configuration for minio. All of my attempts results in `ERR_TOO_MANY_REDIRECTS`.

My nginx configuration looks like this:

```
proxy_cache_path /var/nginx/cache_s3 levels=1:2 keys_zone=STATIC_S3:30m inactive=24h max_size=1024m;

server {
  listen 216.126.198.36:80;
  server_name redacted.k0nsl.org;
  return 301 https://redacted.k0nsl.org$request_uri;
}

server {
        root /usr/share/nginx/ragnarok;
        listen 127.0.0.1:443 ssl http2;
        server_name redacted.k0nsl.org;
        index index.html index.htm;
        error_log /dev/null error;
        access_log /dev/null combined;

        large_client_header_buffers 8 32k;

        ssl_certificate /root/.acme.sh/s3/fullchain.cer;
        ssl_certificate_key /root/.acme.sh/s3/s3.key;

ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_dhparam /etc/ssl/certs/dhparam.pem;
ssl_session_cache shared:SSL:10m;
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
ssl_session_tickets off; # Requires nginx >= 1.5.9
ssl_stapling on; # Requires nginx >= 1.3.7
ssl_stapling_verify on; # Requires nginx => 1.3.7
ssl_trusted_certificate /root/.acme.sh/s3/fullchain.cer;
resolver 95.215.44.59 8.8.4.4 valid=300s;
resolver_timeout 5s;

location / {
        proxy_cache STATIC_S3;
        proxy_cache_valid 200 120m;
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        add_header X-Proxy-Cache $upstream_cache_status;

        recursive_error_pages on;

        error_page 500 502 503 504 403 /custom_50x.html;
        location = /custom_50x.html {
                root /usr/share/nginx/ragnarok;
                internal;
        }

        proxy_intercept_errors on;
        proxy_pass http://127.0.0.1:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
}
}
```

I updated minio today (so should be latest version):
```
root@relay01:~/go/bin# minio version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```

Excuse me if I am low on details but I am posting this in a rush and I can compliment this issue with further details, if needed.

Thanks in advance for any help or suggestions.

**Comment by harshavardhana** [comment]
// cc @krishnasrinivas

**Comment by krishnasrinivas** [comment]
@k0nsl did you check this doc: https://docs.minio.io/docs/setup-nginx-proxy-with-minio

**Comment by k0nsl** [comment]
@krishnasrinivas: I can't see what that document has which I might be missing. I've got minio and nginx installed and I'm using the above configuration, but for making absolutely sure nothing in my configuration was wrong, I tried that vanilla nginx reverse proxy configuration listed in the document you've linked and the results are still the same.

Thanks for your time.

**Comment by harshavardhana** [comment]
> @krishnasrinivas: I can't see what that document has which I might be missing. I've got minio and nginx installed and I'm using the above configuration, but for making absolutely sure nothing in my configuration was wrong, I tried that vanilla nginx reverse proxy configuration listed in the document you've linked and the results are still the same.

@k0nsl can you paste your simplified configuration?

**Comment by krishnasrinivas** [comment]
@k0nsl just verified that it works:
```
root@escape:~# cat /home/krishna/nginx.conf
events {
    worker_connections  1024;
    
}

http {
     server {
    	   listen       80;
	   location / {
   	   	    proxy_set_header Host $http_host;
		    proxy_pass http://localhost:9000;
           }
     }
}

root@escape:~# nginx -c /home/krishna/nginx.conf
root@escape:~# nginx -v
nginx version: nginx/1.9.3 (Ubuntu)
root@escape:~# 
```

and verified with mc:
```
krishna@escape:~$ mc ls myminio80/test-1
[2017-03-01 16:42:03 PST] 2.2KiB passwd
krishna@escape:~$ 
```

There must be something else in your environment that is causing problem for you.

**Comment by k0nsl** [comment]
@krishnasrinivas: Well, it worked many months ago but when I finally decided to upgrade it now gives error about "too many redirects". I ran an older version when you still maintained `minio-browser` as a separate repository.
Did you run that nginx configuration on a VPS or dedicated server and with a "live" domain, outside of your own network? That's what I do.

When I access it all simply by going to the IP, it works. Well, I'll give this some more testing and report back if I find anything new.

More details which I had forgot to add in my initial issue due to time constraints:
```
root@relay01:/etc/nginx/sites-enabled# cat /etc/os*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@relay01:/etc/nginx/sites-enabled# nginx -v
nginx version: nginx/1.10.3
root@relay01:/etc/nginx/sites-enabled# uname -a
Linux relay01 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux
root@relay01:/etc/nginx/sites-enabled# uptime
 02:34:52 up 130 days, 17:46,  2 users,  load average: 0.33, 0.23, 0.22
```

**Comment by k0nsl** [comment]
I found out what the issue is. Jeez, something so innocuous as this had me running around on a wild goose chase -- wasting several hours! 😂

The issue? Change the protocol from `HTTP` to `HTTPs`, i.e:
```
proxy_pass http://127.0.0.1:9000;
```
To:
```
proxy_pass https://127.0.0.1:9000;
```

Now it works beautifully with the original nginx configuration I have been using all along (the one shown in the first comment).

Thanks for the help.
