### ISSUE TITLE
make maxObjectSize a config option

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3825]
maxObjectSize should be a setting

The maxObjectSize is an arbitrary value based on a strict equality with the s3 limits, in my case this limit is really annoying and force to bring to the last level of services the complexity of the authentification and the s3 API instead of having very simple PUT/GET on shared url.
To bypass this I have a proxy that take the PUT with a simple custom signature and send it to the storage with the S3 API.
This is useful 1 time every 100 000 PUT, one object is between 5Go and 10Go every 100 000, the rest are 99% < 100Mo et 1% is between 100Mo and 5Go.
I have no intention to switch to S3, even if the minio compatibility is interesting it's only on one side, most of the software that can use S3 as a backend can use minio or require minimal changes but I personally don't care about the opposite.
Having a warning saying that if you change that for a <5Go limit you break the possibility to switch from s3 to minio and if  > 5Go from minio to S3 is enough IMO.

**Comment by harshavardhana** [comment]
Arch reviewed and accepted @dcharbonnier - PR sent increasing to 16GiB.

**Comment by dcharbonnier** [comment]
Thx a lot i will test it Monday
