### ISSUE TITLE
browser: Add support to enable image previews.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#3835]
We stream image files to minio server. However since the browser does not have a preview, we have to download files one by one and verify if our images are saved correctly.

## Expected Behavior
On clicking ... or hovering show image preview.

## Current Behavior
On clicking a file downloads to the local computer.
A preview of the file on hover or click is needed.  Display file's metadata like any file explorer.

## Possible Solution
Ideally, image preview should only be available for image file types (jpg/png/gif..etc). In the future we must also be able to easily extend and add video previews and text, markdown, previews. Finally, have a fall back mechanism to show when previews are not available. Possibly with reason why its not available may also be shown.

## Steps to Reproduce (for bugs)
1. Open Minio Browser
2.  Find any bucket and select an image file
3. On hover nothing happens.
4. On clicking the .... there is no view option
5. on click the file it simply download the file.

## Context
Xray server streams images to the minio server whenever a face is detected. It becomes really cumbersome to verify if all the files have a face in them without downloading every one of them.

## Your Environment
Play

**Comment by deekoder** [comment]
New UI demo tomorrow.

**Comment by deekoder** [comment]
Need to review again with @abperiasamy

**Comment by deekoder** [comment]
@donatello  please give a placeholder API with default image preview.

**Comment by deekoder** [comment]
is a dependent blocking  bug https://github.com/minio/minio/issues/2991

**Comment by donatello** [comment]
> is a dependent blocking bug #2991

@deekoder #2991 is not related to this one.

**Comment by deekoder** [comment]
#4141 is the blocking bug.

**Comment by deekoder** [comment]
Since #4141 is owned by @brendanashworth  assigning this also to @brendanashworth

**Comment by mattn** [comment]
any update on this?

**Comment by deekoder** [comment]
We will work on this in the future.

**Comment by AnthonyDevTS** [comment]
Is this feature still being worked on?

**Comment by harshavardhana** [comment]
This is on hold @AnthonyDevTS at this point in time.

**Comment by FlowsenAusMonotown** [comment]
@harshavardhana This feature would be very nice and helpful since I'm using minio as picture and file store for my own platform. Please set a higher priority to it.

**Comment by harshavardhana** [comment]
@FlowsenAusMonotown for near future we have no cycles to work on this.

**Comment by ihostage** [comment]
@harshavardhana Why closed? 😞 
Maybe someone from the community can implement this while maintainers are busy.
@pkwenda maybe you? 😄

**Comment by harshavardhana** [comment]
This change requires server side support for optimal behavior, unless there is a clean approach which we can ratify. 

Browser UI may even become slower with this feature, so it is not worth the time for now.

**Comment by tweigel-dev** [comment]
ahh nice that there is a need of the feature :smile:
