### ISSUE TITLE
browser: Object deletion is not immediately shown in the browser when its deeper than one bucket level

### ISSUE THREAD

**Issue by deekoder** [minio/minio#3836]
Create a bucket. When you organize content inside the bucket with more prefixes, and try to delete the object, browser does not update. See gif.

## Expected Behavior
On delete browser should immediately show deletion of the object (it must disappear). If browser is refreshed the browser removes the deleted object.

## Current Behavior
 See gif below. Open dashboard -> car_photos-> delete any object (no refresh).
This is different from the behavior when you delete an object inside dashboard.
![browser_ui_bug](https://cloud.githubusercontent.com/assets/1700901/23538137/da76415a-ff85-11e6-9857-5bca3dfc52d3.gif)

## Possible Solution
None.

## Steps to Reproduce (for bugs)
See gif 

## Context
Refreshing screen after deletes is too cumbersome.
 
## Your Environment
play

**Comment by harshavardhana** [comment]
Fixed in master 0bae3330e8c8910c69e8229a3f0268e6127b6982
