### ISSUE TITLE
docs: can I limit the space for a bucket

### ISSUE THREAD

**Issue by cocodrino** [minio/minio#3846]
Hi..I'm curious about if it's possible set a specific limit size for a bucket, I'm interested in running on a server but I can't use the whole space...if it's not do you know what can I do for solve this situation?..thank you!!!

**Comment by harshavardhana** [comment]
It is not possible you should use backend fs quotas to achieve this. @cocodrino

**Comment by harshavardhana** [comment]
Closing as answered..
