### ISSUE TITLE
Refresh button in the bucket and accessing image in the browser

### ISSUE THREAD

**Issue by scratchoo** [minio/minio#3847]
1- I uploaded a file to an empty bucket, and it's surprising to not have any button to refresh the bucket content, I had to go back and come again to the backet to see the file. (This is a suggestion to add a refresh button in the buckets)

2 - after uploading the image I cannot see how I can see it in the browser ? Is it possible to access an url that show the image directly in the browser ?

Thanks

**Comment by krishnasrinivas** [comment]
> 1- I uploaded a file to an empty bucket, and it's surprising to not have any button to refresh the bucket content, I had to go back and come again to the backet to see the file. (This is a suggestion to add a refresh button in the buckets)

this is a bug, which minio version are you using?



> 2 - after uploading the image I cannot see how I can see it in the browser ? Is it possible to access an url that show the image directly in the brows

This is not supported.

**Comment by scratchoo** [comment]
@krishnasrinivas I used `docker pull minio/minio` to install minio so I think I used the old version that was available on digitalocean. I will upgrade..

How I can show an image in my site if it's not supported to show an image in the browser ?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas I used docker pull minio/minio to install minio so I think I used the old version that was available on digitalocean. I will upgrade..

I see the bug, we'll fix it.



> How I can show an image in my site if it's not supported to show an image in the browser ?

Minio-Browser (like AWS console browser) is a minimal file browser, not intended to have preview of files. Even AWS S3 console just allows you to browse/upload/download objects. You would have to implement separate application so that it shows the images in the browser.

**Comment by scratchoo** [comment]
@krishnasrinivas yes I have already a rails app, is there any helper to show the image in the browser ?

**Comment by krishnasrinivas** [comment]
@medBouzid check this sample app: https://docs.minio.io/docs/javascript-shopping-app

it shows the images stored on minio in the browser.

**Comment by krishnasrinivas** [comment]
>> @krishnasrinivas I used docker pull minio/minio to install minio so I think I used the old version that was available on digitalocean. I will upgrade..

> I see the bug, we'll fix it.

Sorry, I did not check properly, I am unable to see the bug. Can you let us know the version? you can click Settings->About

**Comment by scratchoo** [comment]
```
    Version
    2017-02-16T01:47:30Z
    Memory
    Used: 4.4 MB | Allocated: 8.2 MB | Used-Heap: 4.4 MB | Allocated-Heap: 9.0 MB
    Platform
    Host: 8bb2e992d091 | OS: linux | Arch: amd64
    Runtime
    Version: go1.7.5 | CPUs: 1
```

For the link you provided  for the sample app, I am not sure how I can apply this to my Rails view, and the documentation is lucking a lot of info, I felt confused today while I was reading through it !

**Comment by krishnasrinivas** [comment]
> 1- I uploaded a file to an empty bucket, and it's surprising to not have any button to refresh the bucket content, I had to go back and come again to the backet to see the file. (This is a suggestion to add a refresh button in the buckets)

@medBouzid I am not able to reproduce this problem (tried docker as well) Minio browser shows the content as soon as the file is uploaded into the empty bucket.
Can you check if there are any errors in the JS console?

> For the link you provided for the sample app, I am not sure how I can apply this to my Rails view, and the documentation is lucking a lot of info, I felt confused today while I was reading through it !

Think about how you would implement an app such that the images you show in the app is hosted on AWS S3, you will have to use minio exactly the same way to host the images. Your users should never use Minio browser to see the images as you would not share the access/secret keys with your users.

**Comment by scratchoo** [comment]
> I am not able to reproduce this problem (tried docker as well) Minio browser shows the content as soon as the file is uploaded into the empty bucket.
> Can you check if there are any errors in the JS console?

@krishnasrinivas  

I forget to tell you that this issue happens because I was uploading directly from the browser, so I thought it would be useful that the uploaded image appears directly or there is a refresh button. No there are no errors in the console, the upload is done correctly.
----------------------------------

Yesterday I asked you if there is a way to show the uploaded image in the browser, or how to show it in the view of my app, strangely today I made the bucket as "read and write" and I was able to access my image via the url : http://138.197.117.239:9000/docker/uploads/f9b2cef3-9384-4ecf-97c8-be1da4a2d928/schema1.png (I just show you the url format here, so I am not sure it will work for you after I log out because every time I quit the server from my terminal all the uploaded images are deleted)

if you need me to provide you with more info, feel free to ask. 

thanks

**Comment by krishnasrinivas** [comment]
To make storage persistent check this doc: https://docs.minio.io/docs/minio-docker-quickstart-guide

> I forget to tell you that this issue happens because I was uploading directly from the browser, so I thought it would be useful that the uploaded image appears directly or there is a refresh button. No there are no errors in the console, the upload is done correctly.

It works for me, can you check at https://play.minio.io:9000 if it works as expected for you?


> Yesterday I asked you if there is a way to show the uploaded image in the browser, or how to show it in the view of my app, strangely today I made the bucket as "read and write" and I was able to access my image via the url : http://138.197.117.239:9000/docker/uploads/f9b2cef3-9384-4ecf-97c8-be1da4a2d928/schema1.png (I just show you the url format here, so I am not sure it will work for you after I log out because every time I quit the server from my terminal all the uploaded images are deleted)

Yes, but better make it read-only by this command:
mc policy download myminio/docker

so that there is no anonymous write permission.

You can also use presigned URLs for private buckets: http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html

**Comment by scratchoo** [comment]
> To make storage persistent check this doc: https://docs.minio.io/docs/minio-docker-quickstart-guide
Thank you for the link, I run this code : 
```
docker run -p 9000:9000 --name minio1 \
  -v /mnt/export/minio1:/export \
  -v /mnt/config/minio1:/root/.minio \
  minio/minio server /export
```
and after that I have no idea how to run the minio server?? I am not sure why I can't find help when I search in google, and the doc is really not clear :( minio looks awesome but there is a luck of info and the doc is not much friendly, also the youtube short video of minio are no-sense maybe those points make minio less used by people, so I hope you guys focus more about clear documentation :) 

> It works for me, can you check at https://play.minio.io:9000 if it works as expected for you?

It still not working for me, I am not sure you are uploading from a web app to minio ? I am using direct upload and after the file is uploaded it doesn't show directly in the bucket, I always have to refresh the bucket via the browser's refresh button to see the new file!!

**Comment by harshavardhana** [comment]
> It still not working for me, I am not sure you are uploading from a web app to minio ? I am using direct upload and after the file is uploaded it doesn't show directly in the bucket, I always have to refresh the bucket via the browser's refresh button to see the new file!!

Yes you have to refresh the UI if you upload using cli because there is no active refresh implemented on the browser and we are not going to implement that to keep it simple.  This is is expected as of now.  We will explore adding a refresh button to make it easier for now just use browser refresh.

> and after that I have no idea how to run the minio server?? I am not sure why I can't find help when I search in google, and the doc is really not clear :( minio looks awesome but there is a luck of info and the doc is not much friendly, also the youtube short video of minio are no-sense maybe those points make minio less used by people, so I hope you guys focus more about clear documentation :)

May be i am not able to understand, are you not able to run minio server by typing below command?

> docker run -p 9000:9000 --name minio1 \
>   -v /mnt/export/minio1:/export \
>   -v /mnt/config/minio1:/root/.minio \
>   minio/minio server /export

Here is the output that you would get, given that you typed them appropriately. 

```
$ docker run -p 9000:9000 --name minio1  \
  -v /mnt/export/minio:/export \
  -v /mnt/config/minio:/root/.minio \
  minio/minio server /export

Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
AccessKey: 123456789 
SecretKey: 123456789 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://172.17.0.2:9000 123456789 123456789

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 12 GiB Free, 55 GiB Total
```

Also can you elaborate what info is missing? - we can definitely address them.

**Comment by scratchoo** [comment]
@harshavardhana ok thank you I will wait to see the refresh button, it will make things easier..

This is the error I get when I try to run the server : 

```
root@docker-512mb-nyc3-01:~# docker run -p 9000:9000 --name minio1 \
>   -v /mnt/export/minio1:/export \
>   -v /mnt/config/minio1:/root/.minio \
>   minio/minio server /export
docker: Error response from daemon: Conflict. The container name "/minio1" is already in use by container a2f19c89df57f701e8a9c3a6d81dae7a21b453146f871839e94a1288473af872. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
```
When I run the above command the very first time, it worked but after I exit the server and come back then try to run it again, I get that error now every time!

> Also can you elaborate what info is missing? - we can definitely address them.

I meant a lot of things aren't clear and sometimes luck of details written in a simple way... can I contribute by writing a dummy/beginner guide to run minio from A to Z, I will write everything my mind wants to do to create a ready to use minio server, the deal is that I will use that for me, and write a follow steps for other developers who maybe are like me, so it's win win, the only thing I need is your answers, I will ask you "how to do that" when I don't find an answer, you tell me and I write it down in an easy to use guide.. If that arranges you then let me know, I will be happy to help :)

**Comment by harshavardhana** [comment]
> I meant a lot of things aren't clear and sometimes luck of details written in a simple way... can I contribute by writing a dummy/beginner guide to run minio from A to Z, I will write everything my mind wants to do to create a ready to use minio server, the deal is that I will use that for me, and write a follow steps for other developers who maybe are like me, so it's win win, the only thing I need is your answers, I will ask you "how to do that" when I don't find an answer, you tell me and I write it down in an easy to use guide.. If that arranges you then let me know, I will be happy to help :)

The problem is awareness of `docker` like tools, We cannot possibly document other tools as well.  So the document is kept minimal so that you can start running `minio server` without further distraction. 

Thanks for the feedback we will see how these can be improved. // cc @NitishT 

> This is the error I get when I try to run the server :
> 
> root@docker-512mb-nyc3-01:~# docker run -p 9000:9000 --name minio1 \
> >   -v /mnt/export/minio1:/export \
> >   -v /mnt/config/minio1:/root/.minio \
> >   minio/minio server /export
> docker: Error response from daemon: Conflict. The container name "/minio1" is already in use by container a2f19c89df57f701e8a9c3a6d81dae7a21b453146f871839e94a1288473af872. You have to remove (or rename) that container to be able to reuse that name..
> See 'docker run --help'.
> When I run the above command the very first time, it worked but after I exit the server and come back then try to run it again, I get that error now every time!

So here the situation is the default behavior of docker.  docker attaches a volume to a container, even if you exit the reference is not deleted. It is expected that you pass `--rm` along with the previous CLI so that when you exit the references are deleted as well. 

If the reference is valid for example now you need to do is `docker start minio1`  to restart the previously stopped container if not you need to just do is 

```
docker rm minio1
```

To delete the unneeded containers.  Then type the above command again. 

If you wish to not have any dangling references then please follow the below CLI. 

```
root@docker-512mb-nyc3-01:~# docker run -p 9000:9000 --rm --name minio1 \
>   -v /mnt/export/minio1:/export \
>   -v /mnt/config/minio1:/root/.minio \
>   minio/minio server /export
```

**Comment by scratchoo** [comment]
@harshavardhana 

> The problem is awareness of docker like tools, We cannot possibly document other tools as well. So the document is kept minimal so that you can start running minio server without further distraction.

I moved away from docker and now my minio is installed in a linux machine directly which is fine :) 
I also set up a domain name to the ip address of my droplet (DO) and it's working fine. 

Is there a way to hide the login page under a  dummy sub-domain or sub-folder ? I mean when someone visit my domain name domain.com he shouldn't see the login page to my minio, instead I want the login page to be under something like domain.com/Esx3sr31fze  (obscure it) so only me know it's url ??

**Comment by harshavardhana** [comment]
> Is there a way to hide the login page under a dummy sub-domain or sub-folder ? I mean when someone visit my domain name domain.com he shouldn't see the login page to my minio, instead I want the login page to be under something like domain.com/Esx3sr31fze (obscure it) so only me know it's url ??

You should do this using nginx proxy in front of Minio, this is out of scope for Minio.

**Comment by krishnasrinivas** [comment]
@medBouzid you can turn off the browser using `export MINIO_BROWSER=off`

> Is there a way to hide the login page under a dummy sub-domain or sub-folder ? I mean when someone visit my domain name domain.com he shouldn't see the login page to my minio, instead I want the login page to be under something like domain.com/Esx3sr31fze (obscure it) so only me know it's url ??

This won't be possible. Because the path `/minio` is hardcoded in minio to allow access to non-storage resources ... like UI/management. Hence browser side JS also depends on this path for working.

Regarding the original questions:
> 1- I uploaded a file to an empty bucket, and it's surprising to not have any button to refresh the bucket content, I had to go back and come again to the backet to see the file. (This is a suggestion to add a refresh button in the buckets)

If you don't upload file through the UI, the UI will not auto refresh. You will have to refresh the browser manually.

I think we can close this issue?

**Comment by harshavardhana** [comment]
Yes we can close this.. issue.
