### ISSUE TITLE
Cannot remove files when out of disk

### ISSUE THREAD

**Issue by sheerun** [minio/minio#3856]
I get "Storage backend has reached its minimum free disk threshold. Please delete few objects to proceed." message from minio. Unfortunately when trying to remove while folder using `mc` tool, I get the same message..

## Expected Behavior
Minio should allow removing files, even if over disk usage threshold

## Current Behavior
Minio doesn't allow even removing of files if over disk threshold

## Steps to Reproduce (for bugs)

1. Make minio to produce "Storage backend has reached its minimum free disk threshold. Please delete few objects to proceed."
2. Try to remove some files like so: 

mc rm --recursive --force kube/git/
mc: <ERROR> Failed to remove ‘kube/git/’ recursively. Storage backend has reached its minimum free disk threshold. Please delete few objects to proceed.

## Your Environment

mc 

Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 3fe080982e5e7da59dfcca9ad63ccdd64f04e053

minio

VERSION
2016-06-03T19:32:05Z
MEMORY
Used: 4.4MB | Allocated: 11TB | Used-Heap: 4.4MB | Allocated-Heap: 676MB
PLATFORM
Host: deis-minio-676004970-mw5f3 | OS: linux | Arch: amd64
RUNTIME
Version: go1.6 | CPUs: 2

**Comment by vadmeste** [comment]
@sheerun, thanks for reporting. One question: about the disk which holds Minio data (backend storage), was it also used for other purposes? (like operating system data, user data etc..)

**Comment by sheerun** [comment]
Indeed, Minio wasn't the only one using this disk (I think there were some build performed there and logging. Another probably related issue: I wasn't able to traverse directory structures in minio web ui.

**Comment by vadmeste** [comment]
@sheerun by the way, your Minio version is quite old now, can you manage to update your server and test again?

**Comment by sheerun** [comment]
Not really, I use up-to-date deis build

**Comment by harshavardhana** [comment]
> Not really, I use up-to-date deis build

Dies is using a really really old version from like 8months ago it should be updated to latest. @sheerun `2016-06-03T19:32:05Z` should be `2017-02-16T01-47-30Z`

**Comment by sheerun** [comment]
So it's not the issue with the newest minio?

**Comment by harshavardhana** [comment]
> So it's not the issue with the newest minio?

Nope @sheerun we relaxed this requirement some time ago.

**Comment by harshavardhana** [comment]
Fixed in the latest master as well with new requirements.
