### ISSUE TITLE
docker: Add multiarch docker support for minio 

### ISSUE THREAD

**Issue by vielmetti** [minio/minio#3864]
## Expected Behavior

`docker run minio/minio` results in a working system on all supported platforms, using `multiarch` support in the Docker manifest to pull in each of the supported minio versions for various hardware.

## Current Behavior

An error message like`panic: standard_init_linux.go:178: exec user process caused "exec format error"` happens when you run the amd64 Docker image on an arm64 system.

## Possible Solution

The system that's done the best at implementing this is `portainer`, as described in https://github.com/portainer/portainer/issues/285 using the manifest-tool https://github.com/estesp/manifest-tool to build. 

Note that this depends also on having a CI pipeline that supports automated Docker builds for multiple architectures, and there's a start of work on that at https://github.com/minio/minio/pull/3574 for armhf (Raspberry Pi).

## Context

Trying to get `minio` running under Docker on as many system types as possible with minimum friction and hunting around for working images. The `portainer` setup is very simple to describe and works well.

## Your Environment

* Server type and version: Various, including Raspberry Pi and Packet 2A
* Operating System and version: Various, including Raspbian and Ubuntu and CentOS

**Comment by harshavardhana** [comment]
> The system that's done the best at implementing this is portainer, as described in portainer/portainer#285 using the manifest-tool https://github.com/estesp/manifest-tool to build.
> 
> Note that this depends also on having a CI pipeline that supports automated Docker builds for multiple architectures, and there's a start of work on that at #3574 for armhf (Raspberry Pi).

We have found a much simpler solution by using qemu multiarch - currently we have both Dockerfiles maintained `aarch64, armhf` 

Is the manifest-tool endorsed by docker? @vielmetti

**Comment by harshavardhana** [comment]
We already have this now.. from this release onward. 

https://hub.docker.com/r/minio/minio/tags/

```
RELEASE-2017-06-13T19-01-01Z-aarch64

RELEASE-2017-06-13T19-01-01Z-armhf

RELEASE.2017-06-13T19-01-01Z
```

Closing this for now. Please re-open @vielmetti if anything we missed.
