### ISSUE TITLE
Minio web interface: buckets with longer name 

### ISSUE THREAD

**Issue by danyaljj** [minio/minio#3866]
Here is what I have: 

<img width="768" alt="screen shot 2017-03-07 at 1 55 46 pm" src="https://cloud.githubusercontent.com/assets/2441454/23675156/062c7b6e-033e-11e7-973e-1a6c78175c2b.png">

As you can see the bucket names are long and are cut. So I have to go through them one by one to find the one I'm looking for. Would be great if you can move the margin between the bucket list and the content browser on the right, so that the user can browse the list of buckets easier.

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio/pull/3877
