### ISSUE TITLE
Default Minio Access/Secret Keys on Rancher Install.

### ISSUE THREAD

**Issue by thoughtpalette** [minio/minio#3871]
On initial Rancher container install of minio using the default `server /export` command to start it on port `9000`. I get to a login page where it asks to provide credentials for access/secret keys.

I've been unable to find any documentation around default install keys or how to generate them through the command line. 

Can anyone point me in the right direction?

**Comment by thoughtpalette** [comment]
Solved by viewing the Logs in the container.

**Comment by harshavardhana** [comment]
You can also set them using envs with custom values 

Envs 

- MINIO_ACCESS_KEY
- MINIO_SECRET_KEY
