### ISSUE TITLE
Use Minio without keys

### ISSUE THREAD

**Issue by JarrodAMcEvers** [minio/minio#3878]
Is there a way I can use Minio server without an access key and a secret key?

**Comment by krishnasrinivas** [comment]
@JarrodAMcEvers you can start start minio with access/secret keys and create public buckets:

`mc policy public myminio/bucketname`

Starting with access/secret keys is not allowed.

**Comment by harshavardhana** [comment]
> @JarrodAMcEvers you can start start minio with access/secret keys and create public buckets:
> 
> mc policy public myminio/bucketname
> 
> Starting without access/secret keys is not allowed.

Closing this as answered.

**Comment by JarrodAMcEvers** [comment]
Okay thanks for the quick reply
