### ISSUE TITLE
Minio can be started with access/secret keys empty in config.json

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3880]
## Expected Behavior
Minio shows an error when empty string are set to access and secret keys

## Current Behavior
Minio starts normally

## Possible Solution
Add validation to access and secret keys, possibly in config extensive validation

## Steps to Reproduce (for bugs)
1. Start fresh Minio
2. Edit config.json and set empty string to access and secret key fields
3. Start Minio again

## Context
A bug found and needs to be fixed.

## Your Environment
All

**Comment by harshavardhana** [comment]
Is this still a bug @vadmeste ?

**Comment by harshavardhana** [comment]
Perhaps this PR fixes this problem https://github.com/minio/minio/pull/3893

**Comment by vadmeste** [comment]
> Perhaps this PR fixes this problem #3893

Extensive config validation also does this.

**Comment by harshavardhana** [comment]
Fixed by #3872
