### ISSUE TITLE
browser: Chaning ordering will duplicate object entries in the table

### ISSUE THREAD

**Issue by Atlantic777** [minio/minio#3881]
## Expected Behavior

When I click on the header of a column, I expect ordering to be changed but number of entries should be the same as before and entries should not be duplicated.

## Current Behavior

Each time I click on a column header, new rows are appended at the end of the table. They are indeed ordered properly.

## Possible Solution

Remove old rows from the table before new ones are appended.

## Steps to Reproduce (for bugs)

1. Given that there are some objects in a bucket
2. When you click on a column header to change ordering
3. Then the list of objects will not be just reordered but it will grow.

## Context

Just monitoring some objects on my dev minio instance.

## Your Environment

* Version used: 
```
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697
```

* Environment name and version (e.g. nginx 1.9.1): the docker container
* Server type and version: 
* Operating System and version: Linux
* Link to your project: n/a

**Comment by harshavardhana** [comment]
Fixed by

commit fcad4a44fd01279955921a8c4054820d396021da
Author: Rushan <rushenn123@gmail.com>
Date:   Wed Mar 1 02:41:34 2017 +0530

    Browser: Remove duplicate object entries while sorting (#3813)
