### ISSUE TITLE
Error when starting in distributed mode

### ISSUE THREAD

**Issue by atifghaffar** [minio/minio#3891]
Hi,

When starting in distributed mode i-e using url scheme we get an error. Please point us where we are doing something wrong.
thanks

here is the setup

wget https://dl.minio.io/server/minio/release/linux-amd64/minio
chmod +x minio
sudo cp minio /usr/local/bin/

sudo /usr/local/bin/minio  server http://10.0.236.111/s3-storage
FATA[0001] http://10.1.236.111:9000/s3-storage, FS setup expects a filesystem path  cause=Invalid arguments specified source=[server-main.go:274:checkServerSyntax()]

$ df -h /s3-storage/
Filesystem                                 Size  Used Avail Use% Mounted on
/dev/lxc/wscwbs-storage01-prod_s3-storage  493G   70M  467G   1% /s3-storage

$ ifconfig front
front     Link encap:Ethernet  HWaddr 00:16:5f:40:31:9b
          inet addr:10.0.236.111  Bcast:10.0.236.255  Mask:255.255.255.0

$ sudo /usr/local/bin/minio  -v
Minio version 0.0.0

**Comment by atifghaffar** [comment]
$ minio version
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697

**Comment by atifghaffar** [comment]
The same was reproducable on my mac .

 ~   minio server http://192.168.33.139/var/tmp
FATA[0001] http://192.168.33.139:9000/var/tmp, FS setup expects a filesystem path  cause=Invalid arguments specified source=[server-main.go:274:checkServerSyntax()]

**Comment by nitisht** [comment]
@atifghaffar Minio distributed mode needs at least four servers. If there are less than four arguements passed to the `server` command, Minio takes it as standalone mode. 

In standalone mode Minio server doesn't allow remote paths i.e. `http://` style paths is not allowed, hence the error.

**Comment by atifghaffar** [comment]
Thanks @NitishT, Will it start even if the other servers are not yet started?

**Comment by nitisht** [comment]
yes, you can use distributed Minio when all the servers are up and each of them can talk to others, before that they just wait for other instances to come online.

**Comment by atifghaffar** [comment]
@NitishT  it workes. I just realize that I cannot use a cluster with 5 nodes.. With 4 nodes it works.

So with 4 node cluster I need to have 3 hosts up for read/write to work. correct?

**Comment by nitisht** [comment]
>  I cannot use a cluster with 5 nodes.

You can use a cluster with 5 nodes as well. Max nodes = 16. 

> So with 4 node cluster I need to have 3 hosts up for read/write to work. correct?

Yes (n (number of nodes) / 2) + 1 nodes

**Comment by atifghaffar** [comment]
@NitishT With 5 node, I get the following

$ sudo /usr/local/bin/minio  server http://10.1.236.111/s3-storage http://10.1.236.112/s3-storage http://10.1.236.113/s3-storage http://10.1.236.114/s3-storage http://10.1.236.115/s3-storage

FATA[0001] Insufficient number of disks.                 cause=Total number of disks should be multiples of '2' source=[server-main.go:270:checkServerSyntax()]

**Comment by nitisht** [comment]
@atifghaffar apologies, looks like only even number of disks are supported. 

so you can have - 4, 6, 8, 10, 12, 14, 16 disks. 

I am sorry for giving wrong information!

**Comment by atifghaffar** [comment]
@NitishT  its ok. I will increase the size to 6 nodes.

**Comment by atifghaffar** [comment]
Thanks for your help. All works now.
