### ISSUE TITLE
docs: Please help me to integrate minio.io to Laravel 4

### ISSUE THREAD

**Issue by macray125** [minio/minio#3892]
Hi Ma'am/Sir

Please help me to integrate minio.io to Laravel 4.

CONFIGURATION
'credentials' => [
        'key'    => 'KEY'
        'secret' => 'SECRET', // Your AWS Secret Access Key
    ],
'endpoint' => 'http://steveharvey.db.weplay.media',

 $result = $s3->putObject(array(
                        'Bucket' => 'asksteveharvey',
                        'Key'    => 'testkey',
                        'Body'   => 'Hello from Minio!!'
                    ));

## Current Behavior

ERROR JSON RETURN
{
  "error": "Something went wrong.[curl] 6: Could not resolve host: asksteveharvey.steveharvey.db.weplay.media [url] http://asksteveharvey.steveharvey.db.weplay.media/testkey"
}

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by jerome-vai** [comment]
i have a same problem with an other app to integrate minio try with param    'path_style' => true in your client configuration :)

More info here :
https://gist.github.com/viccherubini/e3107493f078516555f3
https://github.com/aws/aws-sdk-php/issues/347

**Comment by harshavardhana** [comment]
Can you confirm if @jeje-50 suggestion works @macray125 ?

**Comment by macray125** [comment]
didn't work

**Comment by harshavardhana** [comment]
> didn't work

What is the error? any log file ? code snippet ? that you care to share?

**Comment by macray125** [comment]
still the same

ERROR JSON RETURN
{
  "error": "Something went wrong.[curl] 6: Could not resolve host: asksteveharvey.steveharvey.db.weplay.media [url] http://asksteveharvey.steveharvey.db.weplay.media/questions/images/632/question_img_f6e5525f4eee77e3b33c09f8d9385c4f.jpg"
}

**Comment by macray125** [comment]
Im using aws-sdk-php and aws-sdk-php-laravel

**Comment by koolhead17** [comment]
@macray125 what exactly are you trying to achieve and @harshavardhana asked for code snippet so we would know what and how you are running minio. Please provide us the same.

**Comment by macray125** [comment]
may bucket name is "asksteveharvey" and my endpoint is 'endpoint' => 'http://steveharvey.db.weplay.media',

apparently the bucketname is concatenating   to endpoint that's why I'm getting http://asksteveharvey.steveharvey.db.weplay.media and it causing error.
 below is may code snippet
`
config/aws.php
return array(
    'key'    => 'key here', // Your AWS Access Key ID
    'secret' => 'secret here', // Your AWS Secret Access Key
    'endpoint' => 'http://steveharvey.db.weplay.media',
    'path_style' => true,
    'region' => 'us-east-1',
    'config_file' => null,
);

$s3 = App::make('aws')->get('s3');

                try {
                    // Upload a file.
                    $result = $s3->putObject(array(
                        'Bucket'       => 'asksteveharvey',
                        'Key'          => 'questions/images/'.$question_created->id.'/' .$keyname,
                        'Body'   => fopen($destination.'/'.$keyname, 'r'),
                        'ACL' => 'public-read',
                    ));

                    //echo $result['ObjectURL'];
                    $question_update_with_image = 1;                   
                    //return true;

                    if(file_exists($destination.'/'.$keyname)){
                      File::delete($destination.'/'.$keyname);
                    }
                } catch (S3Exception $e) {
                    //echo "There was an error uploading the file.\n";
                    return Response::json(['error' => 'Something went wrong Image.']);
                }
`

**Comment by koolhead17** [comment]
@macray125 

You are using older version or aws-php-laravel which uses ([aws/aws-sdk-php:~2.4](https://github.com/aws/aws-sdk-php-laravel)). aws-sdk-php:~2.4 is a older AWS client library which uses virtual path style.

Can you try latest Laravel 5.1 which uses aws-sdk-php:~3.X. 

References:
1. https://github.com/aws/aws-sdk-php/issues/1129  
2. https://github.com/aws/aws-sdk-php-laravel

**Comment by macray125** [comment]
I'm using laravel 4. Is still compatible if I change the version of aws-sdk-php and aws-sdk-php-laravel for laravel 4?

**Comment by koolhead17** [comment]
@macray125  

Will it be possible to test your code on:

aws-sdk-php-laravel 3.x - For laravel/framework:~5.1 and aws/aws-sdk-php:~3.0  for the reason i stated previously.

**Comment by pinepain** [comment]
With AWS PHP SDK v3 adding `'use_path_style_endpoint' => true` to client args should help


E.g.:

```php
    $s3 = new \Aws\S3\S3Client([
        'version'                 => 'latest',
        'region'                  => 'us-east-1',
        'endpoint'                => 'http://play.minio.io:9000',
        'use_path_style_endpoint' => true,
        'credentials'             => [
            'key'    => 'Q3AM3UQ867SPQQA43P2F',
            'secret' => 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
        ],
    ]);
    $bucket = 'testbucket-' . microtime(true);
    $result = $s3->createBucket([
        'Bucket' => $bucket,
    ]);

```

Source:  http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct

**Comment by pinepain** [comment]
@harshavardhana Thanks for the best tool! Could we add a brief how-to about PHP AWS SDK configuration with minio  to Cookboks docs section please? The example above should help a lot to newcomers and will help spreading mino idea.

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/how-to-use-aws-sdk-for-php-with-minio-server the AWS PHP docs have been updated.

**Comment by pinepain** [comment]
Thanks!

**Comment by coraxster** [comment]
if forked @taisph version of flysystem-aws-s3-v3 and published to composers packagist.
check this out 
https://packagist.org/packages/coraxster/flysystem-aws-s3-v3-minio

**Comment by harshavardhana** [comment]
Thanks looks great :cake: @coraxster perhaps you might want to update the following doc whenever you have time - https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-as-laravel-file-storage.md

This issue can be closed as well since we have this documented under cookbook // cc @deekoder
