### ISSUE TITLE
Use minio instead amazon S3

### ISSUE THREAD

**Issue by ZennouRachid** [minio/minio#3894]
#Im trying to use minio as i want to use minio for self-host instead amazon S3 in my custom Signal whisper system application(https://github.com/lucaconte/BeatTheMeddler) as it's described in this link (https://github.com/WhisperSystems/Signal-Server/pull/77), so my yml file configuration look like this :
s3:
accessKey: 1PAVK1425juiUAH
accessSecret: inhoKJSHDUIIrichskiY7Fpc9
attachmentsBucket: bucket
endpoint: http://127.0.0.1:9000
region: us-east-1
pathStyleAccess: true
signerAlgorithm: AWSS3V4SignerType
but it doesn't work, when i try to send an attachment the signal application give my this error "signal has stoped" .
any one have an idea?

**Comment by vadmeste** [comment]
@ZennouRachid, as I understood, WhisperSystems/Signal-Server still doesn't support S3 servers other than Amazon S3, https://github.com/WhisperSystems/Signal-Server/pull/77 is an open pull request which is not merged yet.

**Comment by ZennouRachid** [comment]
@vadmeste Thank you, as an expert on minio service, is there a posibility to do this ?

**Comment by harshavardhana** [comment]
Closing this as not a bug for Minio but an upstream issue..
