### ISSUE TITLE
browser: Persistent ``Loading...``` message 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3901]
## Expected Behavior
No such message if there are no buckets available

## Current Behavior
Without any bucket browser shows "Loading..." message

![no-bucket](https://cloud.githubusercontent.com/assets/622699/23924875/cb878da0-08c9-11e7-9053-5cced3a0983c.png)

Observed while watching this demo https://vimeo.com/208089836

## Possible Solution
No sure.

## Steps to Reproduce (for bugs)

1. Start on a fresh directory.
2. Login to the browser and you should see it.

## Context
Inconsistent UI.

## Your Environment
Current master

**Comment by krishnasrinivas** [comment]
I observed it as well :D
