### ISSUE TITLE
docs: How to use Minio with Apache Drill 

### ISSUE THREAD

**Issue by waynekoepcke** [minio/minio#3908]
Has anyone used minio as an Amazon S3 server for Apache Drill?
I'm wondering if it is possible.  I tried but couldn't get a working configuration.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment]
Can you take some time to fill out the following which have been left empty from the issue template?

- minio version
- apache drill version
- apache drill configuration

Also if possible steps to reproduce.

**Comment by harshavardhana** [comment]
Other relevant params to use Minio with Apache Drill. 

```xml

<property>
  <name>fs.s3a.connection.ssl.enabled</name>
  <value>true</value>
  <description>Enables or disables SSL connections to S3.</description>
</property>

<property>
  <name>fs.s3a.endpoint</name>
  <description>AWS S3 endpoint to connect to. An up-to-date list is
    provided in the AWS Documentation: regions and endpoints. Without this
    property, the standard region (s3.amazonaws.com) is assumed.
  </description>
</property>

<property>
  <name>fs.s3a.path.style.access</name>
  <value>false</value>
  <description>Enable S3 path style access ie disabling the default virtual hosting behaviour.
    Useful for S3A-compliant storage providers as it removes the need to set up DNS for virtual hosting.
  </description>
</property>
```

**Comment by waynekoepcke** [comment]
Hi Harsha

This is great!  I'll give it a try and get back to you.

Thanks
Wayne

**Comment by waynekoepcke** [comment]
Hi,

Using these properties allowed my local drill server was able to communicate with my local minio server using the drill s3 connector.  However queries are failing.  I think the best way to show this is to include an image of the drill explorer.  I'll add the error from the minio log below as well as my Apache Drill configuration.

Thanks for all your help!

## Drill explorer with query and error
<img width="1058" alt="drillexplorer" src="https://cloud.githubusercontent.com/assets/13474649/24017159/22c2c1e2-0a4c-11e7-9a55-d6757a62368b.png">

## Apache drill server configuration 
<configuration>

    <property>
       <name>fs.s3a.connection.ssl.enabled</name>
       <value>false</value>
       <description>Enables or disables SSL connections to S3.</description>
    </property>

    <property>
      <name>fs.s3a.endpoint</name>
      <value>http://127.0.0.1:9000</value>
    </property>

    <property>
      <name>fs.s3a.path.style.access</name>
      <value>true</value>
    </property>

</configuration>

I have tried both true and false for fs.s3a.path.style.access

## Apache Drill S3 storage config settings
`{
  "type": "file",
  "enabled": true,
  "connection": "s3a://bucket1",
  "config": {
    "fs.s3a.access.key": "BMWHDEYX01H0PQP7WNMF",
    "fs.s3a.secret.key": "CEZV+albFAC7wqyTAJ062FI9HWpgN6JJJn6ighxY"
  },
  "workspaces": {
    "root": {
      "location": "/",
      "writable": true,
      "defaultInputFormat": null
    }
  },
  "formats": {
    "psv": {
      "type": "text",
      "extensions": [
        "tbl"
      ],
      "delimiter": "|"
    },
    "csv": {
      "type": "text",
      "extensions": [
        "csv"
      ],
      "delimiter": ","
    },
    "tsv": {
      "type": "text",
      "extensions": [
        "tsv"
      ],
      "delimiter": "\t"
    },
    "parquet": {
      "type": "parquet"
    },
    "json": {
      "type": "json",
      "extensions": [
        "json"
      ]
    },
    "avro": {
      "type": "avro"
    },
    "sequencefile": {
      "type": "sequencefile",
      "extensions": [
        "seq"
      ]
    },
    "csvh": {
      "type": "text",
      "extensions": [
        "csvh"
      ],
      "extractHeader": true,
      "delimiter": ","
    }
  }
}`

## Minio webconsole
<img width="1627" alt="miniowebconsole" src="https://cloud.githubusercontent.com/assets/13474649/24017434/455a9616-0a4d-11e7-9c43-29688f7d3cd4.png">

## Minio log
`ERRO[4142] Unable to fetch object info.                  cause=Object name invalid: bucket1#data/ source=[object-handlers.go:206:objectAPIHandlers.HeadObjectHandler()] stack=object-api-input-checks.go:39:checkBucketAndObjectNames object-api-input-checks.go:23:checkGetObjArgs fs-v1.go:534:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:204:objectAPIHandlers.HeadObjectHandler api-router.go:42:(objectAPIHandlers).HeadObjectHandler-fm`

**Comment by waynekoepcke** [comment]
The version information
## Minio
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697

## Apache Drill version
apache drill 1.8.0

## OS
Apple
Darwin 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
@waynekoepcke this is expected we don't support object names which have "/" at the end.

**Comment by waynekoepcke** [comment]
'/' at the end or anywhere in the path?  Is there a drill query that would work.
For example if the full path on the minio server is
bucket1/data/account/20161229/0_0_0.parquet

Would a drill query to the root folder like this work
DESCRIBE s3.root`./data/account/20161229/0_0_0.parquet`;

Or are you saying queries on objects at the top of the bucket are supported.
Queries on objects in subdirectories are not supported?

**Comment by harshavardhana** [comment]
> '/' at the end or anywhere in the path? Is there a drill query that would work.
> For example if the full path on the minio server is
> bucket1/data/account/20161229/0_0_0.parquet
> 
> Would a drill query to the root folder like this work
> DESCRIBE s3.root./data/account/20161229/0_0_0.parquet;
> 
> Or are you saying queries on objects at the top of the bucket are supported.
> Queries on objects in subdirectories are not supported?

It is HEAD on "data/"

**Comment by waynekoepcke** [comment]
Thanks for the explanation.

**Comment by harshavardhana** [comment]
> Thanks for the explanation.

Can you test with the latest release? we made a different set of change to not return object name invalid where as just to return 404. Can you try ? @waynekoepcke 

Thanks

**Comment by deekoder** [comment]
Needs to be a recipe on cookbook.

**Comment by waynekoepcke** [comment]
Hi @harshavardhana - Yes sure I can try it using the latest release.
I'll let you know how it goes.

Thanks

**Comment by harshavardhana** [comment]
> Hi @harshavardhana - Yes sure I can try it using the latest release.
> I'll let you know how it goes.
> 
> Thanks

Thanks @waynekoepcke

**Comment by harshavardhana** [comment]
Here is a rough doc captured for Apache Drill querying data stored on Minio - https://gist.github.com/harshavardhana/a8424dcf247fb68ad72b803cefb1b561

**Comment by nitisht** [comment]
@waynekoepcke we added a blog post for this here https://blog.minio.io/query-minio-datastore-with-apache-drill-dcaf71d0cee5

Closing this as fixed.
