### ISSUE TITLE
minio log:"Unable to fetch object info." cause="../myobjects78/fs.json: bad file descriptor" 

### ISSUE THREAD

**Issue by JYang1986** [minio/minio#3911]
When I use the COSBench test the following configuration file , use Amazon S3 , with 3 drivers

`<workload name="get-200Workers-256KB" description="sample benchmark for s3"> 
 <storage type="s3" config="accesskey=test;secretkey=test;endpoint=http://192.168.222.76:9000" />
<workflow>
 <workstage name="init">
      <work type="init" workers="200" config="cprefix=s3testqwer;containers=r(1,2)" />
    </workstage>
<workstage name="prepare">
      <work type="prepare" workers="200" config="cprefix=s3testqwer;containers=r(1,2);objects=r(1,500);sizes=c(256)KB" />
    </workstage>
<workstage name="get 256KB data with 200 workers">
<work name="Put256KBData1" workers="200"  runtime="60">
  <operation type="read" ratio="100" config="cprefix=s3testqwer;containers=u(1,2);objects=s(1,500);sizes=c(256)KB" /> 
  </work>
  </workstage>
  </workflow> 
</workload>`

the read success is very low

and log messages lot of these errors:
`
Mar 16 13:36:32 node76 minio: time="2017-03-16T13:36:32+08:00" level=error msg="Unable to fetch object info." cause="read /opt/minio/lminio/.minio.sys/buckets/s3testqwer2/myobjects78/fs.json: bad file descriptor" source="[object-handlers.go:104:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1-metadata.go:156:(*fsMetaV1).ReadFrom fs-v1.go:508:fsObjects.getObjectInfo fs-v1.go:542:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:102:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
Mar 16 13:36:32 node76 minio: time="2017-03-16T13:36:32+08:00" level=error msg="Unable to fetch object info." cause="stat /opt/minio/lminio/.minio.sys/buckets/s3testqwer1/myobjects104/fs.json: bad file descriptor" source="[object-handlers.go:104:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1-metadata.go:151:(*fsMetaV1).ReadFrom fs-v1.go:508:fsObjects.getObjectInfo fs-v1.go:542:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:102:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
Mar 16 13:40:47 node76 minio: time="2017-03-16T13:40:47+08:00" level=error msg="Unable to fetch object info." cause="read /opt/minio/lminio/.minio.sys/buckets/s3testqwer1/myobjects14/fs.json: bad file descriptor" source="[object-handlers.go:104:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1-metadata.go:156:(*fsMetaV1).ReadFrom fs-v1.go:508:fsObjects.getObjectInfo fs-v1.go:542:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:102:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
Mar 16 13:40:47 node76 minio: time="2017-03-16T13:40:47+08:00" level=error msg="Unable to fetch object info." cause="read /opt/minio/lminio/.minio.sys/buckets/s3testqwer1/myobjects120/fs.json: bad file descriptor" source="[object-handlers.go:104:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1-metadata.go:156:(*fsMetaV1).ReadFrom fs-v1.go:508:fsObjects.getObjectInfo fs-v1.go:542:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:102:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
Mar 16 13:40:47 node76 minio: time="2017-03-16T13:40:47+08:00" level=error msg="Unable to fetch object info." cause="read /opt/minio/lminio/.minio.sys/buckets/s3testqwer2/myobjects214/fs.json: bad file descriptor" source="[object-handlers.go:104:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1-metadata.go:156:(*fsMetaV1).ReadFrom fs-v1.go:508:fsObjects.getObjectInfo fs-v1.go:542:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:102:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
Mar 16 13:40:47 node76 minio: time="2017-03-16T13:40:47+08:00" level=error msg="Unable to fetch object info." cause="read /opt/minio/lminio/.minio.sys/buckets/s3testqwer1/myobjects269/fs.json: bad file descriptor" source="[object-handlers.go:104:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1-metadata.go:156:(*fsMetaV1).ReadFrom fs-v1.go:508:fsObjects.getObjectInfo fs-v1.go:542:fsObjects.GetObjectInfo <autogenerated>:274:(*fsObjects).GetObjectInfo object-handlers.go:102:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"`

when I cat /opt/minio/lminio/.minio.sys/buckets/s3testqwer2/myobjects78/fs.json, I can see the content。

how this happened?

when the workers<=drivers (only test 2,3 drivers), the read success is 100%
if the  workers>drivers the read success is very low, sometimes <40%

## Your Environment
[root@node76 ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@node76 ~]# uname -a
Linux node76 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@node76 ~]#

minio 02.16.2017 release

cosbench 0.4.2.c4

**Comment by harshavardhana** [comment]
> when I cat /opt/minio/lminio/.minio.sys/buckets/s3testqwer2/myobjects78/fs.json, I can see the content。
> 
> how this happened?
> 
> when the workers<=drivers (only test 2,3 drivers), the read success is 100%
> if the workers>drivers the read success is very low, sometimes <40%

We fixed this bug possibly related in the master branch since 2b0ed21f083e3333bc4508b8c1d0266d7385eca6 . If you can give master branch a try that would be immensely helpful.. @Saber-Yang 

Thanks for doing this btw, we will also run these tests on our end as well - do you have any special cosbench profile or the CLI params that you can share with us for us to replicate?

**Comment by JYang1986** [comment]
Thank you for answer my issue. I will test the master branch, if also have problem , then I also comment a issue.

**Comment by harshavardhana** [comment]
> Thank you for answer my issue. I will test the master branch, if also have problem , then I also comment a issue.

We made a new release you can try that as well..

**Comment by JYang1986** [comment]
@harshavardhana I make the master  branch yesterday 

[root@test02 minio]# git log
commit 21d73a3eefc6ade7e65e761bcb0a789bda3ecb78
Author: Bala FA <bala.gluster@gmail.com>
Date:   Thu Mar 16 12:46:06 2017 +0530

    Simplify credential usage. (#3893)


and then test, this issue does not appear thank you for fix bug.

[root@node76 lminio]# cat /var/log/messages | grep minio
......
Mar 17 08:56:24 node76 systemd: Started minio.
Mar 17 08:56:24 node76 systemd: Starting minio...
Mar 17 08:56:24 node76 minio: Migration from version ‘13’ to ‘14’ completed successfully.

 Log information does not have this problem, I will continue to use your release version to test through consbench。

may I have your email? 
this issues can be closed. my email is: **dahaimydream@126.com**

**Comment by harshavardhana** [comment]
Thanks @Saber-Yang you can email me at harsha@minio.io
