### ISSUE TITLE
Notify object access in event notification APIs

### ISSUE THREAD

**Issue by deekoder** [minio/minio#3916]
Currently DELETE and PUT are supported. Add support for GET & HEAD as well. 
s3:ObjectAccessed:Get
s3:ObjectAccessed:Head
s3:ObjectAccessed:*

**Comment by GarimaKapoor** [comment]
@krisis can you take a look at this issue?

**Comment by donatello** [comment]
Perhaps `s3:ObjectAccessed:Copy` should also be added for an object being copied via server side copy-object request?

**Comment by harshavardhana** [comment]
@donatello `s3:ObjectCreate:Copy` is already there borrowed from S3 spec.

**Comment by donatello** [comment]
> @donatello `s3:ObjectCreate:Copy` is already there borrowed from S3 spec.

@harshavardhana Ah. I meant that maybe it should be an event on the **source object** in the copy object operation - implying that the source object was accessed to make a copy. It is for completeness of the events system. Perhaps it is not needed if the `s3:ObjectCreate:Copy` event already includes the source object.
