### ISSUE TITLE
listenBucket notification  and event notifications APIs need to be extended and modified

### ISSUE THREAD

**Issue by deekoder** [minio/minio#3917]
modify :  events -> source string needs to be "minio:s3" instead of aws:s3
add: sourceUserAgent : "User Agent"
add: sourcePort:"Port"

https://github.com/minio/mc/issues/2073 depends on this.

Links
* http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html
* https://aws.amazon.com/blogs/aws/s3-event-notification/

**Comment by GarimaKapoor** [comment]
@krisis please take over this issue. It is priority feature.

**Comment by krisis** [comment]
@deekoder I have couple of clarifications.
- From the links in description, it appears that `sourceUserAgent` and `sourcePort` are specific to minio. Is this right?
-  Does the event message structure change apply to notification targets like Redis, Postgres, etc as well?

**Comment by krisis** [comment]
@deekoder @harshavardhana Does `sourcePort`  and `sourceUserAgent` refer to the client making API requests like `PutObject` to Minio server?

**Comment by harshavardhana** [comment]
> @deekoder @harshavardhana Does sourcePort and sourceUserAgent refer to the client making API requests like PutObject to Minio server?

Yes any client be it presigned based curl upload, browser upload etc. 

sourcePort is an additional field 
sourceUserAgent is just the userAgent obtained from request header.
