### ISSUE TITLE
benchmark: fsCreateFile throws unexpected EOF while running cosbench

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3926]
## Expected Behavior
No such message

## Current Behavior
```
ERRO[0380] Failed to create object mycontainers2/myobjects20  cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Unable to create an object. /mycontainers2/myobjects20  cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Failed to create object mycontainers1/myobjects12  cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Unable to create an object. /mycontainers1/myobjects12  cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Failed to create object mycontainers1/myobjects45  cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Unable to create an object. /mycontainers1/myobjects45  cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Failed to create object mycontainers2/myobjects33  cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Unable to create an object. /mycontainers2/myobjects33  cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0380] Failed to create object mycontainers1/myobjects21  cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
``` 

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Run cosbench with attached 
[controller.zip](https://github.com/minio/minio/files/852215/controller.zip)

## Context
Running benchmarking tools successfully..

## Your Environment
FusionIO NAS backend, latest minio.

**Comment by JYang1986** [comment]
minio server environment
[root@node77 minio_test]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   50G   16G   35G  31% /
devtmpfs                 126G     0  126G   0% /dev
tmpfs                    126G   36K  126G   1% /dev/shm
tmpfs                    126G  1.8G  125G   2% /run
tmpfs                    126G     0  126G   0% /sys/fs/cgroup
/dev/sdc                 3.6T  689G  2.8T  20% /opt/fusionnas/cds/1
/dev/sdd                 3.6T  772G  2.7T  23% /opt/fusionnas/cds/2
/dev/sdh                 3.6T  578G  2.9T  17% /opt/fusionnas/cds/7
/dev/mapper/centos-home   57G   11G   47G  18% /home
/dev/sdi                 3.6T  696G  2.8T  20% /opt/fusionnas/cds/5
/dev/sdg                 3.6T  686G  2.8T  20% /opt/fusionnas/cds/6
/dev/sde                 3.6T  730G  2.7T  21% /opt/fusionnas/cds/3
/dev/sdb                 3.6T  775G  2.7T  23% /opt/fusionnas/cds/0
/dev/sdf                 3.6T  699G  2.8T  21% /opt/fusionnas/cds/4
/dev/sdj1                497M  194M  304M  39% /boot
tmpfs                     26G     0   26G   0% /run/user/0
tmpfs                     26G     0   26G   0% /run/user/993
127.0.0.1:/nfs_minio      83T   13T   67T  16% /opt/minio/nfs_minio
[root@node77 minio_test]# pwd
/opt/fusionnas/cds/0/minio_test
[root@node77 minio_test]# uname -a
Linux node77 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@node77 minio_test]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@node77 minio_test]#

[root@node77 0]# ./minio version
Version: 2017-03-16T07:26:24Z
Release-Tag: DEVELOPMENT.2017-03-16T07-26-24Z
Commit-ID: 21d73a3eefc6ade7e65e761bcb0a789bda3ecb78
[root@node77 0]# ./minio server minio_test/ -C .

Endpoint:  http://192.168.1.77:9000  http://192.168.110.77:9000  http://192.168.222.77:9000  http://192.168.223.77:9000  http://127.0.0.1:9000
AccessKey: FusionNAS
SecretKey: FusionNAS
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://192.168.1.77:9000  http://192.168.110.77:9000  http://192.168.222.77:9000  http://192.168.223.77:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.77:9000 FusionNAS FusionNAS

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 2.6 TiB Free, 3.6 TiB Total

[root@node77 minio_test]# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=131918088k,nr_inodes=32979522,mode=755)
......
/dev/sdb on /opt/fusionnas/cds/0 type ext4 (rw,noatime,data=ordered)

[root@node77 minio_test]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
stepping        : 2
microcode       : 0x37
cpu MHz         : 2300.976
cache size      : 30720 KB
physical id     : 0
siblings        : 24
core id         : 0
cpu cores       : 12
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 15
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc
bogomips        : 3599.93
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:


test xml:
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="write1GB" description="sample benchmark for s3">

  <storage type="s3" config="accesskey=FusionNAS;secretkey=FusionNAS;endpoint=http://192.168.223.77:9000/" />

  <workflow>

    <workstage name="init">
      <work type="init" workers="1" config="containers=r(1,2)" />
    </workstage>

    <workstage name="write1GB">
      <work name="write1GB" workers="30" runtime="180" division="object">
        <operation type="write" ratio="100" config="containers=u(1,2);objects=u(1,30);content=zero;sizes=c(1024)MB" />
      </work>
    </workstage>
    
    <workstage name="cleanup">
      <work type="cleanup" workers="20" config="containers=r(1,2);objects=r(1,500)" />
    </workstage>

    <workstage name="dispose">
      <work type="dispose" workers="1" config="containers=r(1,2)" />
    </workstage>

  </workflow>

</workload>

30workers write is OK

iostat info
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.32    0.00    6.51    7.60    0.00   78.57

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00    59.60    0.00  668.20     0.00   166.25   509.54   127.60  189.85    0.00  189.85   1.50  99.98
sde               0.00     2.40    0.00   15.20     0.00     2.63   354.11     0.09    6.08    0.00    6.08   1.41   2.14
sdc               0.00     4.20    0.00   20.00     0.00     3.84   392.72     0.06    3.11    0.00    3.11   1.07   2.14
sdd               0.00     1.80    0.00   15.40     0.00     2.82   375.48     0.08    4.92    0.00    4.92   1.47   2.26
sdf               0.00     3.00    0.00   36.00     0.00     3.11   176.67     0.43   12.04    0.00   12.04   0.59   2.12
sdg               0.00     5.20    0.00   22.20     0.00     4.83   445.77     0.06    2.62    0.00    2.62   1.05   2.34
sdh               0.00     0.00    0.00   18.80     0.00     3.62   394.04     0.05    2.46    0.00    2.46   0.90   1.70
sdi               0.00    23.60    0.00   18.00     0.00     3.31   376.89     0.06    3.41    0.00    3.41   1.03   1.86
sdj               0.00     0.20    0.00    2.60     0.00     0.02    14.00     0.00    0.08    0.00    0.08   0.08   0.02
dm-0              0.00     0.00    0.00    2.80     0.00     0.02    13.00     0.00    0.07    0.00    0.07   0.07   0.02
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-3              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
drbd0             0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.56    0.00    6.39    3.68    0.00   82.38

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00    38.60    0.00  698.00     0.00   174.01   510.57   137.14  196.66    0.00  196.66   1.43 100.00
sde               0.00     4.40    0.00   19.60     0.00     4.23   441.80     0.05    2.71    0.00    2.71   0.98   1.92
sdc               0.00     5.00    0.00   26.80     0.00     5.64   430.75     0.07    2.73    0.00    2.73   0.99   2.64
sdd               0.00     5.20    0.00   18.20     0.00     4.03   453.36     0.05    2.55    0.00    2.55   1.02   1.86
sdf               0.00     5.00    0.00   24.20     0.00     5.23   442.84     0.06    2.58    0.00    2.58   1.04   2.52
sdg               0.00     0.00    0.00   22.40     0.00     5.01   458.00     0.11    3.52    0.00    3.52   1.15   2.58
sdh               0.00     4.00    0.00   25.20     0.00     5.23   425.27     0.06    2.21    0.00    2.21   0.86   2.16
sdi               0.00     4.40    0.00   45.80     0.00     5.51   246.46     0.49   10.79    0.00   10.79   0.68   3.10
sdj               0.00     0.00    0.00    1.60     0.00     0.01     9.50     0.00    0.12    0.00    0.12   0.12   0.02
dm-0              0.00     0.00    0.00    1.60     0.00     0.01     9.50     0.00    0.12    0.00    0.12   0.12   0.02
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-3              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
drbd0             0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.41    0.00    8.15    7.67    0.00   76.77

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   171.80    0.00  438.80     0.00   105.13   490.67     6.03   13.75    0.00   13.75   0.57  24.98
sdb               0.00   329.20    0.00  806.20     0.00   166.81   423.74   119.67  149.12    0.00  149.12   1.24  99.88
sde               0.00    24.00    0.00   20.20     0.00     3.91   396.75     0.05    2.56    0.00    2.56   0.89   1.80
sdc               0.00     6.20    0.00   21.40     0.00     4.05   387.14     0.07    3.26    0.00    3.26   0.93   1.98
sdd               0.00     3.20    0.00   20.60     0.00     3.83   381.13     0.06    2.82    0.00    2.82   0.88   1.82
sdf               0.00     0.00    0.00   27.40     0.00     5.62   420.03     0.07    2.62    0.00    2.62   0.89   2.44
sdg               0.00     5.00    0.00   25.00     0.00     5.43   445.06     0.07    3.86    0.00    3.86   0.97   2.42
sdh               0.00     5.00    0.00   16.40     0.00     4.02   502.15     0.04    2.32    0.00    2.32   0.98   1.60
sdi               0.00     4.40    0.00   17.60     0.00     3.24   376.55     0.05    2.89    0.00    2.89   1.01   1.78
sdj               0.00     0.00    0.00    2.80     0.00     0.02    13.79     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    2.80     0.00     0.02    13.79     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-3              0.00     0.00    0.00  610.60     0.00   105.13   352.62     6.99   11.45    0.00   11.45   0.41  24.98
drbd0             0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00


top info
top - 09:28:06 up 12 days, 23:37,  6 users,  load average: 10.30, 5.50, 2.79
Tasks: 556 total,   1 running, 555 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.8 us,  4.9 sy,  0.0 ni, 83.6 id,  2.5 wa,  0.0 hi,  1.1 si,  0.0 st
KiB Mem : 26385841+total, 13485929+free,  8604208 used, 12039492+buff/cache
KiB Swap:  4194300 total,  4194300 free,        0 used. 25202441+avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 11045 root      20   0 1609316  78908   7060 S 582.7  0.0  13:42.97 minio
 14009 root      20   0  380384  14400   4216 S  11.0  0.0   0:00.39 python2.7


50workers write 100G file
the problem has appeare maybe one node 50 drivers 50 workers has the problem
ERRO[2458] Failed to create object mycontainers2/myobjects21  cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[2458] Unable to create an object. /mycontainers2/myobjects21  cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:469:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm

cosbench workload.log
---------------------------------- mission: MDE9745B6A2, driver: driver21 ----------------------------------
2017-03-20 10:03:21,011 [INFO] [Log4jLogManager] - will append log to file /root/0.4.2.c4/log/mission/MDE9745B6A2.log
2017-03-20 10:03:25,153 [INFO] [NoneStorage] - performing PUT at /mycontainers2/myobjects21
2017-03-20 10:04:47,863 [INFO] [NoneStorage] - performing PUT at /mycontainers2/myobjects21
2017-03-20 10:05:21,212 [INFO] [NoneStorage] - performing PUT at /mycontainers2/myobjects21
2017-03-20 10:06:25,164 [WARN] [S3Storage] - below exception encountered when creating object myobjects21 at mycontainers2:

**Comment by JYang1986** [comment]
Now I have understand. This log info is appear when I cancelled the put operation。When I put file by s3cmd， then I cancelled， this log info has appeared。

```
[root@node2 s3cmd]# ./s3cmd put 1G.txt s3://test/1G_2.txt --disable-multipart
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: '1G.txt' -> 's3://test/**1G_2.txt**'  [1 of 1]
  726007808 of 1073741824    67% in   77s     8.88 MB/s^CSee ya!
[root@node2 s3cmd]# 

ERRO[0289] Failed to create object test/**1G_2.txt**         cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:480:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0289] Unable to create an object. /test/**1G_2.txt**    cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:480:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm

```

In this issue, I have canclled the COSBench test,  so the minio have send these log info . please close this issue.

**Comment by harshavardhana** [comment]
Thanks for the update @Saber-Yang . Closing as per your comment.
