### ISSUE TITLE
config: deprecate logger log levels

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3927]
- remove 'log-level' for loggers.
- rename `fileName` for file logger as `filename`.

migrate the config to version 16.

## Expected Behavior
Currently log-levels are kind of pretty much useless because we do not have any extensive logging. 

## Current Behavior
log-levels are supported and parsed which do not provide much value to the end user and ends up confusing them.

## Possible Solution
Fix `config.json` 

## Steps to Reproduce (for bugs)
Open `config.json`

## Context
Cleanup and simplification.

## Your Environment
Latest minio release and master branch.

**Comment by balamurugana** [comment]
> Currently log-levels are kind of pretty much useless because we do not have any extensive logging.

What if I want to save <= fatal log level in a separate file target?

**Comment by harshavardhana** [comment]
> What if I want to save <= fatal log level in a separate file target?

Most deployments do not even touch these values + they are not adding value anymore since we don't have egregious log-levels in our codebase.  Just one less thing to document and explain.  

We can easily ignore that case..

**Comment by balamurugana** [comment]
Ignoring will lead to bloated log file in a long run.  Another case is, if we support other log targets, user may like to save certain log levels to different target.

**Comment by harshavardhana** [comment]
> Ignoring will lead to bloated log file in a long run. Another case is, if we support other log targets, user may like to save certain log levels to different target.

When it happens we will bring whatever is necessary at that point in time. There are not open requirements for now.

**Comment by vadmeste** [comment]
@harshavardhana what will be the default log value internally in the code ?

**Comment by harshavardhana** [comment]
> @harshavardhana what will be the default log value internally in the code ?

there is no log-level all log-levels are enabled.. @vadmeste
