### ISSUE TITLE
browser: Add button to create directory in web interface

### ISSUE THREAD

**Issue by pgaskin** [minio/minio#3933]
There should be an button to create a directory in the web interface. Currently, to create a directory, I either have to do it from the command line or append it to the url.

**Comment by harshavardhana** [comment]
> There should be an button to create a directory in the web interface. Currently, to create a directory, I either have to do it from the command line or append it to the url.

We don't allow creating directories on Minio and have no plans on supporting it. But we can explore providing a way to upload a file to a specific path rather than top level. 

Thanks for opening the bug @geek1011

**Comment by pgaskin** [comment]
@harshavardhana Directories work perfectly fine for some reason if I just append it to the URL.

**Comment by harshavardhana** [comment]
> @harshavardhana Directories work perfectly fine for some reason if I just append it to the URL.

Yes prefixes are created if there is an object referenced but plain empty directories are not allowed.

**Comment by pgaskin** [comment]
@harshavardhana So is this meant to happen?

**Comment by harshavardhana** [comment]
> @harshavardhana So is this meant to happen?

Prefixes are supposed to be created since its a flat namespace ,, but empty prefixes with no object are not allowed. We don't send an error but its a no operation i.e nothing is created on the backend.

**Comment by pgaskin** [comment]
@harshavardhana OK, thanks for the clarification.

**Comment by krishnasrinivas** [comment]
> @harshavardhana Directories work perfectly fine for some reason if I just append it to the URL.

yes, if you want to upload a file to a non-existent directory, you can directly enter the directory path in the address-bar and upload the file.
