### ISSUE TITLE
"Delete selected files" doesn't work in sub-path via Web-UI

### ISSUE THREAD

**Issue by stephenreay** [minio/minio#3936]
Selecting one more files in a sub-path (i.e. /foo/bar/baz.file) of a bucket and then clicking the "Delete selected" button does not work correctly. 

## Expected Behaviour
The selected file(s) should be deleted.

## Current Behaviour
The selected files are removed from the current view, but return on refresh.

## Possible Solution
Maybe related to #3839  ?

## Steps to Reproduce (for bugs)

1. Go to https://play.minio.io:9000/minio/test-bucket-stephenr/foo/
2. Select the file "bar.png" by clicking the check on its icon
3. Click the "Delete Selected files"
4. Refresh/Reload browser view

## Context
Files can't be deleted from the web UI in bulk.

## Your Environment
Play environment and RELEASE.2017-03-16T21-50-32Z on Debian Jessie

**Comment by harshavardhana** [comment]
Do you have a giffy or screenshot - i can't seem to reproduce this. @stephenreay .. Thanks

**Comment by stephenreay** [comment]
I have a screen recording of it, but it gets pretty crapped out as a gif. I can't UL the m4v to GH directly, so its using the bucket from the recording to store the screen rec: https://play.minio.io:9000/test-bucket-stephenr/no-worky.m4v

**Comment by harshavardhana** [comment]
> I have a screen recording of it, but it gets pretty crapped out as a gif. I can't UL the m4v to GH directly, so its using the bucket from the recording to store the screen rec: https://play.minio.io:9000/test-bucket-stephenr/no-worky.m4v

Does individual delete works ? i.e clicking on the one right next to generating shareable URL?

**Comment by stephenreay** [comment]
Yes, that works correctly.

**Comment by harshavardhana** [comment]
ping @rushenn @krishnasrinivas
