### ISSUE TITLE
build: Reduce release binary sizes for minio releases

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3939]
## Expected Behavior
Binary sizes can be made as small as 5.6MB from 24MB current release using upx.

## Current Behavior
Currently no binary size reduction is attempted. 

## Possible Solution
Use - https://upx.github.io/ and also along with `go build --ldflags "-s -w"`

## Steps to Reproduce (for bugs)
Just `make` and check the resulting binary size.

## Context
This is for faster to download and deploy times overall user experience etc.

## Your Environment
Current master.

**Comment by harshavardhana** [comment]
// cc @hackintoshrao once this change is done - need your help in validating the sanctity of the binary so that we don't expect any unexpected issues.

**Comment by matrixik** [comment]
UPX on Go binaries is not working now: https://github.com/golang/go/issues/16706

**Comment by harshavardhana** [comment]
Looks like something happened between 1.7 and 1.8 it's regression. It works with our current release btw which is built with 1.7.5
