### ISSUE TITLE
browser: Download all as Zip doesn't work correctly

### ISSUE THREAD

**Issue by stephenreay** [minio/minio#3943]
The "download all as zip" button is non-functional.

## Expected Behaviour
Select one or more files, click download button, ZIP file downloads

## Current Behaviour
When logged out (i.e. using a bucket with public read policy), the console shows a 403 error.

When logged in using Safari (v10) the console shows an error about frame interrupted:
[Error] Failed to load resource: Frame load interrupted (blob:https://play.minio.io:9000/a7e6c5f0-2636-44bc-9856-b0251e291873, line 0)

## Steps to Reproduce (for bugs)
1. Use safari.
2. Select multiple files
3. Click download all as zip

## Your Environment

* Version used: 2017-03-16T21:50:32Z
* Environment name and version (e.g. nginx 1.9.1): local via vagrant & play
* Operating System and version: Debian Jessie & Play

**Comment by harshavardhana** [comment]
Thanks for the issue, we will take a look.

**Comment by harshavardhana** [comment]
ping @krishnasrinivas @rushenn

**Comment by krishnasrinivas** [comment]
Does not work on Safari. @rushenn is exploring solution.

`window.location = url` does not trigger download of the file on Safari.

**Comment by poornas** [comment]
This is a known issue with Safari Browser. The latest version of Safari Technology Preview (Release 29 (Safari 10.2, WebKit 12604.1.19.0.1)) has fixed this issue, and the next version of Safari will catch up.

**Comment by harshavardhana** [comment]
> This is a known issue with Safari Browser. The latest version of Safari Technology Preview (Release 29 (Safari 10.2, WebKit 12604.1.19.0.1)) has fixed this issue, and the next version of Safari will catch up.

Can you explain what the known issue is? @poornas

**Comment by deekoder** [comment]
Fix fails on my safari. zip extension was not added and the downloaded file (unknown) on double click does not unzip automatically. The workaround was to rename "unknown" to "unknown.zip" then resolves this issue.

**Comment by rushenn** [comment]
@deekoder What is the version of your Safari?

**Comment by harshavardhana** [comment]
Fixed by #4357
