### ISSUE TITLE
bit-rot: Use faster hash functions for bit-rot detection

### ISSUE THREAD

**Issue by aead** [minio/minio#3946]
Minio's erasure coding / bit-rot detection currently relies on BLAKE2b (and SHA-256 on arm).
It's not necessary to use a cryptographic secure general purpose hash function - weaker hash function properties are sufficient for minio's purposes.  

## Expected Behavior
The bit-rot detection requires following properties:
 - The hash must be collision resistant. (see: what means collision resistant)
 - The hash must be long enough - this is also related to collision resistance

### What means collision resistant
In this context collision resistant does not mean collision resistant from a cryptographers perspective.
The hash should not collide for special structured messages - e.g. zero blocks. For example a hash function consisting of modulo multiplication - like `hash(i) = (hash(i-1) * message) mod poly` produces always the zero value if a zero-block occurs, regardless what data comes after the zero-block.     

### Some math
A "good" decision requires some math:  
The birthday paradox tells us: 
 - the probability of a collision is >= 50 % if you hash `2^(hashsize / 2) different messages.
 
Or in oder words: you have to expect a collision after hashing 2^(hashsize / 2) different messages. 
But this only applies for an ideal hash function. If you use a hash function, that relies on simple mathematical operations (like addition or multiplication), a collision can occur because of some structure within the message. On way to be "sure", that a bit flip in the message results in a different hash value, is to relay on hash functions using the [avalanche effect](https://en.wikipedia.org/wiki/Avalanche_effect).

So if we rely on a hash function with the "avalanche property", we can be confident, that the hash function will give us a different values for slightly different messages  - otherwise we found a collision of the hash function. Further it should be very unlikely to get two different messages, which results in the same hash value - this is pretty similar to a cryptographic hash function.

Now let us assume, that we have found such a good hash function - how long should the hash value be?
The computation for minio is a bit different because of:
 - for minio a pure collision is not a problem
 - only a collision of a message and its bit-rot version is problem
 - minio is limited to 16 storage disks  

```
min_msg_size := minimal size of uploaded / stored files (e.g. 4KB)
bitrot rate br:= probability of a disk failure - depends on disks / mode of operation etc. 
collision rate cr := ~ 1 /  2 ^ (hashsize / 2) 

We can now compute the number of bytes - a collision statistically appears after:     
(br ^ -1) * (cr ^ -1) * min_msg_size = (br ^ -1) * (2 ^ (hashsize / 2)) * min_msg_size bytes
in the worst case - only min_msg_size long messages are stored
```
But notice, that this number of bytes refers to ***all minio instances over the world together - not just a single instances***
Let use some concrete numbers:
```
hash_size = 128 bit
min_msg_size = 1K
br = 0.01% (I've no clue whether this is realistic - probably not, realistic values are much lower e.g. < 0.00001%)

=> (br ^ -1) * (cr ^ -1) * min_msg_size = 1,717 * 10^14 TB =~ 163834 EB (exabyte)
if we assume we have 1 billion Minio instances out there, we get following bytes / instance: 
( (br ^ -1) * (cr ^ -1) * min_msg_size ) / 10000000000  =~ 171798,69 TB / instance
```
This is far beyond current store capabilities. 

## Possible Solution
On hash function candidate is [SipHash](https://131002.net/siphash/siphash.pdf) - It's fast on amd64, 386 and ARM - see [implementation](https://github.com/aead/siphash).

**Comment by harshavardhana** [comment]
// cc @fwessels to take a look at the implementation, before we decide.

**Comment by aead** [comment]
@fwessels [https://go-review.googlesource.com/c/38362/](https://go-review.googlesource.com/c/38362/)

**Comment by aead** [comment]
The current plan is to migrate to [GHASH](https://en.wikipedia.org/wiki/Galois/Counter_Mode) so I close this.
