### ISSUE TITLE
Server links down

### ISSUE THREAD

**Issue by doron-goldstein** [minio/minio#3947]
All server download links in the readme are dead

**Comment by koolhead17** [comment]
Thanks for reporting @BlackSynder We will fix it quickly.

**Comment by doron-goldstein** [comment]
As a side note, I also noticed the same thing with the docs. I assume youve switched the location, thus disabling all other links.

**Comment by harshavardhana** [comment]
@BlackSynder looks like github changed their UI and broke the table rendering. Because we remember this to be working fine yesterday. 

Anyways the bug has been fixed in #3948 and thanks for reporting.
