### ISSUE TITLE
Removing the content of some disks shows a wrong behavior in the next server restart.

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3949]
## Expected Behavior
Reformat disks and start normally.

## Current Behavior
Showing `Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 0s)`

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1.  `minio server /path/disk{1..4}/ # start with fresh disks`
2. Kill Minio
3. `rm -r /path/disk{1..2}/.minio.sys # two disks will become empty`
4. `minio server /path/disk{1..4}/  # start Minio again`

## Context
Testing healing

## Your Environment
All

**Comment by harshavardhana** [comment]
You can't start the server without minimum of N/2+1 - see other bugs which are open in this regard.

**Comment by harshavardhana** [comment]
- [arch: replace n/2 disks, new servers does not come up](https://github.com/minio/minio/issues/3234)
- [arch: To read we need n/2, for server to come up we need n/2 + 1](https://github.com/minio/minio/issues/3233)

**Comment by vadmeste** [comment]
> You can't start the server without minimum of N/2+1 - see other bugs which are open in this regard.

Okay, thanks!
