### ISSUE TITLE
[regression]: "invalid credential" when loading (migrated) configuration without credentials

### ISSUE THREAD

**Issue by ankon** [minio/minio#3954]
## Expected Behavior

/config/config.json:
```json
{"version":"10","region":"local"}
```

environment contains suitable MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables.

Expected behavior is that `minio --config-dir /config server /data` starts up, migrating the configuration if so needed.

This works with minio/minio:RELEASE.2017-02-16T01-47-30Z, and produces these messages:
```
Migration from version ‘10’ to ‘11’ completed successfully.
Migration from version ‘11’ to ‘12’ completed successfully.
Migration from version ‘12’ to ‘13’ completed successfully.

Endpoint:  http://172.17.0.11:9000  http://127.0.0.1:9000
...
```

## Current Behavior

With :latest (RELEASE.2017-03-16T21-50-32Z) minio fails to start, and just reports:
```
minio: <ERROR> Cannot validate configuration file. Error: invalid credential
```

## Context
I need to be able to specify the region for minio, and using the configuration file is the only way to accomplish that (AFAICS). I'd love if I could avoid the configuration file and just use an environment variable.
I also need to be able to set the credentials from the outside, which works using environment variables -- and so I'm doing that. I could change my environment to create the configuration programmatically, but that would be quite a PITA :) 

## Your Environment
* Environment name and version (e.g. nginx 1.9.1): minio/minio:latest via docker hub
* Operating System and version: Linux VM with linux 4.7.2 inside Virtualbox

**Comment by vadmeste** [comment]
@ankon, thanks for reporting.

It seems we need to disable validation of access & secret keys inside config, since they can be overridden from the environment.
