### ISSUE TITLE
browser: Fix missing space between colon and number in Minio Browser

### ISSUE THREAD

**Issue by belvid** [minio/minio#3962]
On Minio Browser (play.minio.io) on the top bar were the "**Used:**88.88GB" title is, there is no space between colon and the number. There should be one. I provide screenshot for better visualization of the issue.

![minio browser](https://cloud.githubusercontent.com/assets/20955366/24270032/c964c534-0fd0-11e7-944f-1d7a9a8f4137.png)

**Comment by harshavardhana** [comment]
Thanks @belvid // cc @rushenn
