### ISSUE TITLE
ecosystem: Support minio distributed on Mesosphere 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3966]
- There complications involved in getting the IP's of the containers before hand to send as arguments to run Minio binary on distributed mode.
- DCOS engineers suggested work around by using the shell script and work around docker container which can be found in /https://github.com/tobilg/minio-dcos. 
- Taking this approach means we need to publish docker container which will be dedicated to only run Minio distributed on Mesosphere.
- This calls for a arch review on steps further.

**Comment by harshavardhana** [comment]
Pending discussion with upstream folks.

**Comment by deekoder** [comment]
Now blocked pending discussion -  @abperiasamy

**Comment by deekoder** [comment]
@abperiasamy  approved @fwessels proposal.

**Comment by fwessels** [comment]
Which means that we will not be adding a 'hack' to` mc admin` for delayed starting of minio (instead just start `minio server` directly at the time that all IP addresses are known).

**Comment by deekoder** [comment]
External script should discover IP address and launch minio server with appropriate CLI args.

**Comment by deekoder** [comment]
Post the scripts(solution) in this bug.

**Comment by deekoder** [comment]
Please add a documentation on how to use the script.

**Comment by hackintoshrao** [comment]
Here is the [link](https://github.com/tobilg/minio-dcos/blob/master/minio-wrapper.sh) to the script, but there's lot more work that has to be done around it. The script can't be used as it is, it'll be just part of a new Minio container which will then be used to deploy Minio distributed on Mesosphere using the standard deployment method. Once the development is done, the documentation will be done similar to the docs for standalone Minio on Mesosphere, [here's the link](https://github.com/dcos/examples/tree/master/minio/1.8).

**Comment by deekoder** [comment]
Could we close this issue since it seems resolved?

**Comment by hackintoshrao** [comment]
We can keep this open as a issue tracker till the PR to Mesosphere repo is sent and its merged.

**Comment by deekoder** [comment]
Use env variables do pass to the docker file.

**Comment by hackintoshrao** [comment]
Testing on packet clusters, ETA - 27th April 2017.

**Comment by deekoder** [comment]
@hackintoshrao  can this be closed? Is it merged upstream?

**Comment by harshavardhana** [comment]
> @hackintoshrao can this be closed? Is it merged upstream?

This is not done yet.. AFAIK @deekoder

**Comment by deekoder** [comment]
Can this be closed now?

**Comment by harshavardhana** [comment]
> Can this be closed now?

Its not finished yet. @deekoder

**Comment by hackintoshrao** [comment]
@krisis has sent a proposal, waiting response from Mesosphere team.

**Comment by krisis** [comment]
@deekoder I can take this up. Please assign this to me.
