### ISSUE TITLE
[Windows] mc cp fails with "Failed to copy ‘filename’. Insufficient permissions to access this file"

### ISSUE THREAD

**Issue by krisis** [minio/minio#3968]
## Expected Behavior

`mc cp` should work.

## Current Behavior

`mc cp` fails with "Failed to copy ‘filename’. Insufficient permissions to access this file"

## Possible Solution

NA 
## Steps to Reproduce (for bugs)

1. mc cp \path\to\file myminio/bucket/obj
2. 
3.
4.

Stack trace on server
```
time="2017-03-24T14:23:33+02:00" level=error msg="Unable to create an object." cause="Prefix access is denied: bucketname/filename" source="[object-handlers.go:479:objectAPIHandlers.PutObjectHandler()]" stack="/home/builder/mygo/src/github.com/minio/minio/cmd/fs-v1.go:577:fsObjects.PutObject <autogenerated>:275:(*fsObjects).PutObject /home/builder/mygo/src/github.com/minio/minio/cmd/object-handlers.go:476:objectAPIHandlers.PutObjectHandler /home/builder/mygo/src/github.com/minio/minio/cmd/api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm"
```

Minio Version
```
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697
```

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by rawmaze** [comment]
If this helps, I am able to delete the file with Minio client (mc) but not to overwrite it.

I am also able to delete (with del) and overwrite (with copy) the file in a Windows command line console. Before overwriting it, the copy command prompts for confirmation first.

**Comment by vadmeste** [comment]
I was able to reproduce this bug with the last releaseof minio & mc but it looks like the bug is fixed in master, not sure what's the commit that fixed it.

**Comment by harshavardhana** [comment]
> I was able to reproduce this bug with the last releaseof minio & mc but it looks like the bug is fixed in master, not sure what's the commit that fixed it.

can you git bisect? @vadmeste

**Comment by vadmeste** [comment]
> can you git bisect? @vadmeste

I was able to reproduce this problem with master, it occurs when the target object of the copy operation already exists.

```
c:\work\bin>mc.exe -q cp obj myminio\testbucket\obj
`obj` -> `myminio/testbucket/obj`
Total: 2.36 KB, Transferred: 2.36 KB, Speed: 32.16 KB/s

c:\work\bin>mc.exe -q cp obj myminio\testbucket\obj
`obj` -> `myminio/testbucket/obj`
mc.exe: <ERROR> Failed to copy `obj`. Insufficient permissions to access this file `http://localhost:9000/testbucket/obj`
Total: 2.36 KB, Transferred: 0 B, Speed: 0 B/s
```

**Comment by harshavardhana** [comment]
> I was able to reproduce this problem with master, it occurs when the target object of the copy operation already exists.
> 
> c:\work\bin>mc.exe -q cp obj myminio\testbucket\obj
> `obj` -> `myminio/testbucket/obj`
> Total: 2.36 KB, Transferred: 2.36 KB, Speed: 32.16 KB/s
> 
> c:\work\bin>mc.exe -q cp obj myminio\testbucket\obj
> `obj` -> `myminio/testbucket/obj`
> mc.exe: <ERROR> Failed to copy `obj`. Insufficient permissions to access this file `http://localhost:9000/testbucket/obj`
> Total: 2.36 KB, Transferred: 0 B, Speed: 0 B/s

Thanks @vadmeste

**Comment by harshavardhana** [comment]
Tried with multiple runs on Windows 2012 and not able to reproduce this. 

```
PS C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 87.62 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 88.34 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 89.81 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/4/
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 89.08 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/4/
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 88.34 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 90.57 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 88.34 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/mc.exe
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 88.34 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/mc.exe
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 87.61 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/mc.exe
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 88.34 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/mc.exe
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 87.62 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/mc.exe
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 90.57 MB/s 0s
S C:\Users\Admin\go\bin> .\mc.exe cp .\mc.exe windows/testbucket/1/2/3/mc.exe
.\mc.exe:             10.81 MB / 10.81 MB [=====================================================] 100.00% 89.81 MB/s 0s
``` 

With various combinations of prefix and full path, with latest master and also the released binary.

**Comment by harshavardhana** [comment]
Can we get more system information basically which windows version etc. ?

**Comment by rawmaze** [comment]
@harshavardhana The Windows version is 10 Pro, build 10.0.14393.
Minio server is started with the default settings. Its version is in the initial post by @krisis

**Comment by rawmaze** [comment]
I downloaded the new Minio's version and I still get the same error with it under Windows.
Could it be related to something not configured at all or configured wrong on my machine / OS?

**Comment by vadmeste** [comment]
> Can we get more system information basically which windows version etc. ?

I can reduce the code so we can have a better understanding about what's going on.
