### ISSUE TITLE
rpc: Move format.json validation into object layer.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#3970]
Currently the check is happening at RPC layer which is incorrect as the knowledge of `format.json` is at object layer.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by balamurugana** [comment]
Related Issues: https://github.com/minio/minio/issues/3475

Related PRs https://github.com/minio/minio/pull/3517 https://github.com/minio/minio/pull/3643

**Comment by deekoder** [comment]
@balamurugana can you refresh us about this issue.  We have lost the context on it.

**Comment by balamurugana** [comment]
As described in the first comment
```
Currently the check is happening at RPC layer which is incorrect as the knowledge of format.json is at object layer.
```
`format.json` should be validated at object layer as per the design

**Comment by harshavardhana** [comment]
This has been moved already to object layer with large bucket PR. Closing.
