### ISSUE TITLE
Install via FreeBSD ports now fails

### ISSUE THREAD

**Issue by kulraj-gurm** [minio/minio#3976]
## Current Behavior
 make install
===>  Building for minio-2017.03.16.21.50.32_1
gmake[1]: Entering directory '/usr/ports/www/minio/work/minio-RELEASE.2017-03-16T21-50-32Z'
syscall
/usr/local/go/src/syscall/exec_unix.go:188: undefined: forkExecPipe
Installing minio:
syscall
/usr/local/go/src/syscall/exec_unix.go:188: undefined: forkExecPipe
gmake[1]: *** [Makefile:118: gomake-all] Error 2
gmake[1]: Leaving directory '/usr/ports/www/minio/work/minio-RELEASE.2017-03-16T21-50-32Z'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make: stopped in /usr/ports/www/minio

## Steps to Reproduce (for bugs)
1. Installing with latest new install of FreeBSD from iso
2. portsnap fetch extract update
3. cd /usr/ports/www/minio
4. make install clean

This worked flawlessly until recently

## Your Environment

* OS Version used: FreeBSD11p1

**Comment by kulraj-gurm** [comment]
Found workaround!!
Will post txt doc with step by step for anyone who also has an issue installing via ports

**Comment by harshavardhana** [comment]
> /usr/local/go/src/syscall/exec_unix.go:188: undefined: forkExecPipe

This looks like a FreeBSD packaging bug - @kulraj-gurm have you reported this upstream?

**Comment by kulraj-gurm** [comment]
[minio_install.txt](https://github.com/minio/minio/files/871106/minio_install.txt)
[minio.txt](https://github.com/minio/minio/files/871107/minio.txt)

**Comment by kulraj-gurm** [comment]
@harshavardhana not reported upstream, more concerned with getting it running at the moment.

**Comment by kulraj-gurm** [comment]
[minio_install.txt](https://github.com/minio/minio/files/871111/minio_install.txt)
[minio.txt](https://github.com/minio/minio/files/871112/minio.txt)

**Comment by harshavardhana** [comment]
@swills looks like there is a FreeBSD installation issue looks like `go` port is not compiling properly?

**Comment by harshavardhana** [comment]
Going to close this as a non issue and an upstream problem.
