### ISSUE TITLE
tests: Mint failure when one of the node is down.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3979]
`TestRemoveMultipleObjects` hangs when Mint is run against Minio distributed with one of the node permanently down.
## Expected Behavior

[Mint](https://github.com/minio/mint) tests to pass.
## Current Behavior

`TestRemoveMultipleObjects` hangs and the test eventually timeout.

## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

1. Use Chaos test revamped version for easier replication.
2. ` git clone https://github.com/hackintoshrao/chaos.git && cd chaos`
3. `docker-compose up`
4. Stop Node 1. `docker-compose exec minio1 supervisorctl stop minio`
5. Run [Mint](https://github.com/minio/mint) on node2 (will be exposed on port 9011 on host). 
6. find logs of minio2 at `./logs/minio2/`.
## Context

Minio fault tolerant test.
## Your Environment

* Version used: Chaos builds Minio from latest master everytime.

**Comment by krisis** [comment]
@hackintoshrao could you paste the commit id of master branch the Minio server is based on?

**Comment by hackintoshrao** [comment]
Here is the commit ID 6e63904048e9d7318c5454268b418b92317ba871 .

**Comment by krisis** [comment]
@hackintoshrao I couldn't recreate the issue following the steps provided above. Could you share the minio logs from all the servers when you see this issue?
```
-- PASS: TestListenBucketNotificationHandler (8.46s)
=== RUN   TestDeleteMultipleObjects
--- PASS: TestDeleteMultipleObjects (33.89s)
=== RUN   TestDeleteObject
--- PASS: TestDeleteObject (0.22s)
=== RUN   TestNonExistentBucket
--- PASS: TestNonExistentBucket (0.03s)
=== RUN   TestEmptyObject
--- PASS: TestEmptyObject (0.11s)
=== RUN   TestBucket
```

**Comment by krisis** [comment]
@hackintoshrao Ignore the above comment, it is the output of `functional-tests` run. `TestRemoveMultipleObjects` doesn't hang in my setup, but it takes ~58s. Do you have the minio server logs when this issue was observed?

**Comment by hackintoshrao** [comment]
Its the test from `minio-go sdk-tests`.

**Comment by hackintoshrao** [comment]
Had a test timeout of 60 sec which was less. Tests run well once the timeout is set to default.
