### ISSUE TITLE
CORS 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by IsNull** [minio/minio#3985]
Minio does not include the CORS header `Access-Control-Allow-Origin` - at least not when it serves a resource with a presigned AWS URL.

## Current Behaviour

Sample Request URL
```
$ curl http://mydomain:9000/media/Videos/Movies/2015/test.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=V9SGTU4WHLJLP0A6UKJG%2F20170327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170327T202940Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=b2282bdf4cb08b0bbf9b00fb026890763f40fde08a48d14c385abfdde489a59a
```

**The current response header is**
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2138051800
Content-Type: video/mp4
Last-Modified: Sun, 17 Jan 2016 22:32:24 GMT
Server: Minio/RELEASE.2017-03-16T21-50-32Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14AFD72D6E7EA419
Date: Mon, 27 Mar 2017 20:29:51 GMT
```

## Possible Solution

Ability to add the `Access-Control-Allow-Origin: *` header.
If Minio does not support this, the only workaround is to proxy the whole traffic and injecting the required headers - which is obviously not nice for performance.

Or did I miss something?

## Context
Im trying to stream a video from Minio to a Chromecast Device. Chromecast works with receiver apps which are HTML5 apps themselves and thus require `Access-Control-Allow-Origin: *` since the receiver app is usually hosted somewhere else than the minio server.

## Environment

* Docker Container `minio/minio latest` 
* Version `Minio/RELEASE.2017-03-16T21-50-32Z (linux; amd64)`

**Comment by krishnasrinivas** [comment]
`Vary: Origin` would be the CORS setting, did your HTML5 app complain?

**Comment by krishnasrinivas** [comment]
@IsNull, try this:
```
curl http://mydomain:9000/media/Videos/Movies/2015/test.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=V9SGTU4WHLJLP0A6UKJG%2F20170327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170327T202940Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=b2282bdf4cb08b0bbf9b00fb026890763f40fde08a48d14c385abfdde489a59a `-H "Origin: randomhost"` -v
```

i.e with `-H "Origin: randomhost"`

you will see in the response:
`Access-Control-Allow-Origin: randomhost`

**Comment by harshavardhana** [comment]
Your application has a bug @IsNull we support CORS by default on all requests. On the browser or your client you need to set the valid `Origin:` HTTP header[1] as indicated by @krishnasrinivas .   You can also use XMLHTTPRequest() which supports OPTIONS to populate Origin header automatically for any PUT or GET request. 

[1] - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

**Comment by IsNull** [comment]
Thanks for the fast response. I have to recheck what the Chromecast receiver app actually sends with the initial request.

Closing this now.
