### ISSUE TITLE
locks: Possible stale lock observed on play.minio.io:9000 server

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3988]
```s3contents-test/this/is/the/prefix/Untitled Folder/.s3keep (LocksOnObject: 0, locksAcquiredOnObject: 0, totalBlockLocks:0):   {OperationID:Z01I5LMX3YAXKELL LockSource:[web-handlers.go:284:(*webAPIHandlers).RemoveObject.func1()] LockType:WLock Status:Blocked Since:2017-03-22 04:40:37.031610943 +0000 UTC Duration:63h58m31.901491283s}  {OperationID:PNRTMKHOHHQJL4QP LockSource:[bucket-handlers.go:277:objectAPIHandlers.DeleteMultipleObjectsHandler.func1()] LockType:WLock Status:Blocked Since:2017-03-22 04:41:31.770140598 +0000 UTC Duration:63h57m37.162961628s}  {OperationID:9DOZ9VCI7CFPINY5 LockSource:[object-handlers.go:305:objectAPIHandlers.CopyObjectHandler()] LockType:RLock Status:Blocked Since:2017-03-22 04:25:43.415475148 +0000 UTC Duration:64h13m25.517627078s}  {OperationID:PU55E8TLD3LCYJVA LockSource:[object-handlers.go:201:objectAPIHandlers.HeadObjectHandler()] LockType:RLock Status:Blocked Since:2017-03-22 04:28:50.075365272 +0000 UTC Duration:64h10m18.857736954s}  {OperationID:WULYEQYUCPETTH1B LockSource:[web-handlers.go:284:(*webAPIHandlers).RemoveObject.func1()] LockType:WLock Status:Blocked Since:2017-03-22 04:31:03.418564809 +0000 UTC Duration:64h8m5.514537417s}  {OperationID:F43YMK2BPGZ1YBOS LockSource:[web-handlers.go:284:(*webAPIHandlers).RemoveObject.func1()] LockType:WLock Status:Blocked Since:2017-03-22 04:40:36.306823435 +0000 UTC Duration:63h58m32.626278791s}  {OperationID:RTA2DNEVDUZRILQB LockSource:[object-handlers.go:295:objectAPIHandlers.CopyObjectHandler()] LockType:WLock Status:Blocked Since:2017-03-22 04:26:44.612630219 +0000 UTC Duration:64h12m24.320472007s}  {OperationID:73FY9K6RRS4ASF9R LockSource:[object-handlers.go:201:objectAPIHandlers.HeadObjectHandler()] LockType:RLock Status:Blocked Since:2017-03-22 04:27:24.352789467 +0000 UTC Duration:64h11m44.580312759s}  {OperationID:CB51HSVFFIK0LPCJ LockSource:[web-handlers.go:284:(*webAPIHandlers).RemoveObject.func1()] LockType:WLock Status:Blocked Since:2017-03-22 04:40:34.712479666 +0000 UTC Duration:63h58m34.22062256s}  {OperationID:YGVKLW8MFCYP3B18 LockSource:[web-handlers.go:284:(*webAPIHandlers).RemoveObject.func1()] LockType:WLock Status:Blocked Since:2017-03-22 04:30:53.177420694 +0000 UTC Duration:64h8m15.755681532s}```

## Expected Behavior
No stale locks

## Current Behavior
Unknown stale locks found on play.minio.io server, from the call trace it looks like CopyObject()

## Possible Solution
Not sure. 

## Steps to Reproduce (for bugs)
Not sure, we have to inspect the code.

## Context
Important issue can lead to bucket access being denied. 

## Your Environment
Current master code.

**Comment by vadmeste** [comment]
~~https://github.com/minio/minio/blob/master/cmd/web-handlers.go#L285:~~

~~This is quite dangerous, if the browser mistakenly sends an object twice, we can have a deadlock.~~

**Comment by vadmeste** [comment]
Looks like I found the bug, it is in CopyObjectHandler(), you can notice it is the oldest lock in the log. And it is easy to reproduce with minio-go:

```
 package main
  
 import (
     "log"
 
     "github.com/minio/minio-go"
 )
 
 func main() {
     s3Client, err := minio.New("localhost:9000", "minio", "minio123", false)
     if err != nil {
         log.Fatalln(err)
     }   
     err = s3Client.CopyObject("testbucket", "file", "testbucket/file", minio.CopyConditions{})
     if err != nil {
         log.Fatalln(err)
     }   
     log.Println("Copied source object.")
 }
```

Source path without a leading '/' in the third argument of CopyObject will systematically lock indefinitely the lock.

The reason is that CopyObjectHandler() is not properly checking if src is equal to dest.
