### ISSUE TITLE
windows: "minio -C ./some_dir server ./dir" leads to error in initializing minio server

### ISSUE THREAD

**Issue by rawmaze** [minio/minio#3991]
## Expected Behavior
`minio -C ./some_dir server ./dir` should work even if there is not directory `./some_dir`

## Current Behavior
`minio -C ./some_dir server ./dir`

leads to the following error:

`minio: <ERROR> Unable to initialize minio config for the first time. Error: mkdir \\?\some_dir\certs: The system cannot find the path specified..`

## Possible Solution
NA

## Steps to Reproduce (for bugs)
1. `minio -C ./some_dir server ./dir`
2.
3.
4.

## Your Environment
* Version used:
```
Version: 2017-03-16T21:50:32Z
Release-Tag: RELEASE.2017-03-16T21-50-32Z
Commit-ID: 5311eb22fd681a8cd4a46e2a872d46c2352c64e8
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
`Windows 10`
* Link to your project:

**Comment by rawmaze** [comment]
Note: It works with the previous Minio version.

**Comment by balamurugana** [comment]
Exact bug is at https://github.com/minio/minio/blob/master/cmd/posix-prepare-path.go#L38 which doesn't work for relative path by doing `filepath.Clean()` ie `filepath.Clean("./some_dir") == "some_dir"` then `\\?\` is added hence `\\?\some_dir`

However using windows path separator `\` would work ie `minio -C .\some_dir server .\dir`

**Comment by rawmaze** [comment]
Yes, I expect the directory to be created. It is created if I use the previous Minio version and it is created even with the current version if it's not run on Windows.

**Comment by balamurugana** [comment]
@imosk Yep. That's the expected behavior and found a bug in another place.

**Comment by rawmaze** [comment]
The bug is also present if Minio is run from the master sources as of this moment.

**Comment by harshavardhana** [comment]
> The bug is also present if Minio is run from the master sources as of this moment.

is `./<dir>` commonly used notation on windows? - as @balamurugana suggested the proper path specification on windows is to use `.\<dir>` . 

If it worked before it must have been a mistake because the path on windows for a `./<dir>` is meant to default to an 'absolute' UNC path.

```
minio -C .\some_dir server .\dir
``` 

Is the correct style.  I do not see this as a bug IMHO.

**Comment by rawmaze** [comment]
It does not work with `.\<dir>` either. The slashes do not make any difference.

**Comment by harshavardhana** [comment]
> It does not work with .\<dir> either. The slashes do not make any difference.

How about not using any slashes

```
minio -C some_dir server dir
```

**Comment by rawmaze** [comment]
It's the same even without slashes. It only works with the full path under Windows right now.
But the previous release version worked with relative paths under Windows and the current version works with relative paths on other OSes.

**Comment by harshavardhana** [comment]
> It's the same even without slashes. It only works with the full path under Windows right now.
> But the previous release version worked with relative paths under Windows and the current version works with relative paths on other OSes.

Looks like i tried various combinations on Windows 2012 R2.

Not working
```
minio -C some_dir server dir
```

All of them are working below without using a custom config dir.
```
minio server dir
minio server ./dir
minio server .\dir 
```

Looks like the config directory path handling has some changes which has resulted in some regression the previously comment prepare-path.go // cc @balamurugana is not the problem here.

The bug is lack of usage of absolute path.

```
         var err error
         // Disallow relative paths, figure out absolute paths.                                                                                   
         fsPath, err = filepath.Abs(fsPath)
         if err != nil {
                 return nil, err
         }
```
