### ISSUE TITLE
docs: How to use jgit with Minio?

### ISSUE THREAD

**Issue by lavvy** [minio/minio#3993]
I can push my repo to minio with s3git but i am finding it hard to do the same with jgit. 
S3git is well described by minio but i can't see any documentation or clue about jgit . 
The problem is only just how to add minio url as remote instead of amazon-s3

**Comment by krishnasrinivas** [comment]
@lavvy does not look like http://www.eclipse.org/jgit/ JGit works with S3 storages. JGit is just a Java libary for git repos.

**Comment by lavvy** [comment]
Oh my God, it works like charm with Amazon.
http://www.fancybeans.com/blog/2012/08/24/how-to-use-s3-as-a-private-git-repository/

I tried it yesterday.
I strongly believe it will work with minio if we get the right url

**Comment by deekoder** [comment]
This issue has to move to cookbook.

**Comment by lavvy** [comment]
Any progress

**Comment by harshavardhana** [comment]
> Any progress

does jgit document anything other than supporting AWS S3? - If they don't we can't do much here @lavvy

**Comment by deekoder** [comment]
Moved to minio/cookbook repo.
