### ISSUE TITLE
package: Redis notifications cannot be configured anymore

### ISSUE THREAD

**Issue by mantoni** [minio/minio#3997]
I have upgrade minio with brew yesterday and now my redis notification config is considered invalid. I get this error message:

```
minio: <ERROR> Cannot validate configuration file. Error: Redis [1] configuration invalid: `127.0.0.1:8200` invalid: parse 127.0.0.1:8200: first path segment in URL cannot contain colon
```

## Possible Solution

The cause seems to be rooted here: https://github.com/golang/go/commit/c5ccbdd22bdbdc43d541b7e7d4ed66ceb559030e#comments

However, the solution suggested in the comment to use `//127.0.0.1:8200` yields this error:

```
FATA[0001] Initializing object layer failed              cause=Unable to initialize event notification. Connecting to arn:minio:sqs:us-east-1:1:redis tcp: dial tcp: lookup //127.0.0.1: no such host source=[server-main.go:587:serverMain()]
```

## Steps to Reproduce (for bugs)

My configuration looks like this:

```
		"redis": {
			"1": {
				"enable": true,
				"address": "127.0.0.1:8200",
				"password": "...",
				"key": "bucketevents"
			}
		},
```

As the documentation still states under "Publish Minio events via Redis" this notation should be valid.

## Your Environment

Latest Minio from brew on Mac OS X (10.12.3).

**Comment by mantoni** [comment]
In case others come here, I worked around the issue for now by downgrading to the previous version I had installed with `brew switch minio 20170216014730`.

**Comment by vadmeste** [comment]
@mantoni, thanks for reporting.

We did not move to go 1.8 yet. I guess another solution to this issue is to downgrade to golang 1.7.5

**Comment by mantoni** [comment]
Hmm. I don't have golang installed. Isn't golang compiling the code into a binary?

**Comment by harshavardhana** [comment]
I think the problem is brew must have built it with go1.8 we  will fix the brew package.

**Comment by harshavardhana** [comment]
@mantoni Go broke a lot of things in go1.8 that is why we haven't moved to upstream version yet until the all the above issues get sorted out. 

https://github.com/Homebrew/homebrew-core/pull/11815

**Comment by mantoni** [comment]
Thanks for looking into it and preparing a fix. Fantastic support 👍

**Comment by harshavardhana** [comment]
https://github.com/Homebrew/homebrew-core/pull/11815 any help chiming would be appreciated @mantoni

**Comment by harshavardhana** [comment]
> Homebrew/homebrew-core#11815 any help chiming would be appreciated @mantoni

In-case brew is not resolved we do have minio builds https://dl.minio.io/server/minio/release/darwin-amd64/  which shouldn't have the issue since they are built with go1.7.5

**Comment by harshavardhana** [comment]
It was decided that we will move the homebrew tap to our own repositories 

```
$ brew install minio/minio
```

This would get the Formula from - https://github.com/minio/homebrew-minio

**Comment by mantoni** [comment]
Makes sense. I was surprised and disappointed by the response from the brew team. It's a dangerous and irresponsible decision, in my opinion. Please update here once `brew install minio/minio` works. Thank you.

**Comment by harshavardhana** [comment]
> Makes sense. I was surprised and disappointed by the response from the brew team. It's a dangerous and irresponsible decision, in my opinion. Please update here once brew install minio/minio works. Thank you.

Thanks will do soon!

**Comment by harshavardhana** [comment]
@mantoni - so we added homebrew repo to our main minio repo as well 

Here is how you can test it out. 
```
brew tap minio/release && brew tap-pin minio/release
brew install minio
``` 

Can you let us know if this works properly on your end? 

Thanks

**Comment by mantoni** [comment]
@harshavardhana Thanks. Apparently it worked:

```
master❯ brew install minio
Warning: minio is provided by core, but is now shadowed by minio/release/minio.
To refer to the core formula, use Homebrew/core/minio instead.
==> Installing minio from minio/release
Error: minio-20170216014730 already installed
To install this version, first `brew unlink minio`
master❯ brew unlink minio
Unlinking /usr/local/Cellar/minio/20170216014730... 1 symlinks removed
master❯ brew install minio
Warning: minio is provided by core, but is now shadowed by minio/release/minio.
To refer to the core formula, use Homebrew/core/minio instead.
==> Installing minio from minio/release
==> Downloading https://dl.minio.io/server/minio/release/darwin-amd64/minio
######################################################################## 100,0%
==> Caveats
To have launchd start minio/release/minio now and restart at login:
  brew services start minio/release/minio
Or, if you don't want/need a background service you can just run:
  minio server
==> Summary
🍺  /usr/local/Cellar/minio/20170316215032_1: 4 files, 25.1MB, built in 10 seconds
```

~~However, I'm now getting another error when starting minio, which I don't have the time to trace down right now:~~

```
Unable to get home directory.
```

~~I'm having a little trouble reverting to the previous working version now. Maybe you have some pointers for me?~~

**Comment by vadmeste** [comment]
> However, I'm now getting another error when starting minio, which I don't have the time to trace down right now:
> 
> Unable to get home directory.

@mantoni, you don't have HOME variable set in your terminal ?

`$ echo $HOME`

**Comment by mantoni** [comment]
Scratch it. I wasn't exposing the `HOME` environment variable to minio. It works as it should now. Thanks a lot!
