### ISSUE TITLE
build: Use semantic versioning for stable releases

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#4005]
http://semver.org/

This system is now adopted by all modern software (and this also mean automated with a ci/cd that produce the version)  

example of useful versioning 
 - https://hub.docker.com/r/gitlab/gitlab-ce/tags/
 - https://hub.docker.com/r/library/mongo/tags/
 - https://hub.docker.com/r/library/node/tags/
 - https://hub.docker.com/r/library/golang/tags/
 - https://hub.docker.com/r/library/python/tags/

In production we can't use edge or latest but we could use "4" or "4.2" and get all fixes automatically, you could also maintain a master branch and provide patches. When a bug is fixed we need to wait a release with 90% of commits that are nor urgent for the us.
The production environments pull the images, if we point to a generic tag like nightly or latest, we don't know what we run and a any moment something really bad can happen, this is not a descent option.

**Comment by harshavardhana** [comment]
We don't use semver instead rely on date. If you want to stick to a release just look at the tags 

https://hub.docker.com/r/minio/minio/tags

So it would be `docker pull minio/minio:RELEASE.2017-03-16T21-50-32Z`

**Comment by dcharbonnier** [comment]
PS : no need for documentation or faq, we all got what you do, we just don't think it's a good idea and would like to see an other development cycle.
