### ISSUE TITLE
Support Certificate chain while configuring SSL

### ISSUE THREAD

**Issue by stephenchinnadorai** [minio/minio#4010]
## Expected Behavior
A certificate chain file named public.crt should be recognised and HTTPS on Minio server should work. 

## Current Behavior
Minio server returns an error about a mismatch between private and public keys.
`time="2017-03-30T17:36:41Z" level=fatal msg="Failed to start minio server." cause="tls: private key does not match public key" source="[server-main.go:580:serverMain.func1()]"
`
## Steps to Reproduce (for bugs)

1. Add private.key and public.crt file 
2. public.crt file should contain multiple `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` stanzas. I tested with 4.
3. restart minio docker container so that the new certificates are recognised
4. `docker logs -f minio`

## Your Environment

* Version used: 2017-03-16T21:50:32Z
* Environment name and version (e.g. nginx 1.9.1): Docker version 1.12.6 
* Server type and version: VMware virtual machine
* Operating System and version: CentOS Linux release 7.3.1611 (Core)
* Link to your project:

**Comment by deekoder** [comment]
@vadmeste is this issue addressed and fixed?

**Comment by deekoder** [comment]
@harshavardhana closed as fixed?
