### ISSUE TITLE
Not able to mount multiple volumes using the docker driver minfs

### ISSUE THREAD

**Issue by bearmoo-cloud-net** [minio/minio#4015]
Tring to mount two buckets in the same cantainer, but getting an error:
Error response from daemon: containerd: container did not start before the specified timeout.

## Expected Behavior

I should see in the runnung container:
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  31.2G     13.2G     16.3G  45% /
tmpfs                   919.8M         0    919.8M   0% /dev
tmpfs                   919.8M         0    919.8M   0% /sys/fs/cgroup
MinFS                    64.0T         0     64.0T   0% /mnt/websites
MinFS                    64.0T         0     64.0T   0% /mnt/data
/dev/sda2                31.2G     13.2G     16.3G  45% /etc/resolv.conf
/dev/sda2                31.2G     13.2G     16.3G  45% /etc/hostname
/dev/sda2                31.2G     13.2G     16.3G  45% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   919.8M         0    919.8M   0% /proc/kcore
tmpfs                   919.8M         0    919.8M   0% /proc/timer_list
tmpfs                   919.8M         0    919.8M   0% /proc/timer_stats
tmpfs                   919.8M         0    919.8M   0% /proc/sched_debug
tmpfs                   919.8M         0    919.8M   0% /sys/firmware

I should be able to mount multple volumes into a container from the minfs driver.

## Steps to Reproduce (for bugs)

1. docker volume create -d minio/minfs --name data -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=data
2. docker volume create -d minio/minfs --name websites -o endpoint=https://example.com:9000 -o access-key=yyyy -o secret-key=xxxx -o bucket=websites
3.docker run -it -v data:/mnt/data -v websites:/mnt/websites busybox /bin/sh

## Context

I am trying create an environment where data is not limited to a specific area. Moreover have docker mount the needed resources for the container without the need for me to configure the host so that the containers can use the resources.

For example:
Instead of having to configure the host to mount nfs share, I can use minfs driver for docker make that data availble weather its local or on the cloud.

## Your Environment

* Version used: lastest
* Docker version: 1.13.1
* Environment name and version (e.g. nginx 1.9.1): busybox
* Server type and version: virtual machine(Cloud services)
* Operating System and version: Centos 7.2
* Link to your project:

**Comment by harshavardhana** [comment]
Thanks for opening the issue.

Can you open this issue on https://github.com/minio/minfs instead for relevancy and avoids confusion.

Thanks

**Comment by bearmoo-cloud-net** [comment]
Sure

**Comment by harshavardhana** [comment]
Closing issue moved to minfs https://github.com/minio/minfs/issues/24
