### ISSUE TITLE
How to set up bucket policy with AWS SDK for PHP

### ISSUE THREAD

**Issue by jGielen** [minio/minio#4016]
## Expected Behavior
I want to create a bucket with 2 folders (Private and Public). Standard all folders are private, but I can't configure the public folder. I'm using AWS SDK for PHP.

## Current Behavior
My public folder isn't public.

## Possible Solution
/ 

## Steps to Reproduce (for bugs)
/

## Context
Create a public folder with read only policy.

## Your Environment
* Version used: 2017-02-06T20:16:19Z

**Comment by harshavardhana** [comment]
You just have to follow this code and modify for your local needs should work https://gist.github.com/harshavardhana/00c3ade4e61a640bde44afebb38baeb7
