### ISSUE TITLE
cloudberry mbs not working with minio past version minio.RELEASE.2016-12-13T17-19-42Z

### ISSUE THREAD

**Issue by SSBN506** [minio/minio#4017]
Minio running on a Linux server running any version beyond minio.RELEASE.2016-12-13T17-19-42Z will not work with cloudberry mbs. When you add the storage location you get the following error from minio. ERRO[0012] TLS handshake failed                          cause=tls: no cipher suite supported by both client and server source=[server-mux.go:240:newListenerMux.func1.1()]

This happens with both a signed and self signed ssl. 

## ## Your Environment

* Version used: Any version after minio.RELEASE.2016-12-13T17-19-42Z 
* Operating System and version:Centos 7.1

**Comment by obrienmd** [comment]
At least before version 5.5 for Windows, Cloudberry backup didn't support TLS 1.2. I have used a Caddy proxy in front of minio to allow TLS 1.1 minimum, which seems to work fine with pre-5.5 Windows clients.

Not ideal, but a resolution at least. I'm not sure what the MBS control panel uses when you're setting up a storage location.

**Comment by SSBN506** [comment]
![image](https://cloud.githubusercontent.com/assets/26817913/24560937/2531d640-161b-11e7-97f2-46f548c5ff80.png)

Here is a picture of the error just after hitting ok in the mbs.cloudberrylab.com portal after adding a storage location. the Secret Key was in the field but blanks out after the error just so you don't think i didn't entre it.

**Comment by SSBN506** [comment]
Here is the error on the minio end. 
![image](https://cloud.githubusercontent.com/assets/26817913/24561033/9c8e0786-161b-11e7-9fb7-00338b91d2e3.png)

**Comment by dcwilliams29id** [comment]
I also confirmed this fix works as of the latest stable branch 05/04/2017 at 9:01pm using Cloudberry Backup Agents to Minio.

**Comment by dflasse** [comment]
I know it is supposed to be closed but I do have the very same issue from CloudBerry MBS:

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/listener.go:177:http.(*httpListener).start.func2()
[2018-03-08T11:45:59.272944256Z] [ERROR] TLS handshake failed with new connection x.x.x.x:59971 at server yy.yy.yy.yy:8000 (tls: no cipher suite supported by both client and server)

And I have the lastest version of minio running on Ubuntu 16.04

Version: 2018-02-09T22:40:05Z
Release-Tag: RELEASE.2018-02-09T22-40-05Z
Commit-ID: 289457568c2c812604484ae9b4efeca0f33aac2c

**Comment by gowithplanb** [comment]
This is an issue with CloudBerry MBS clients since Minio dropped support for certain ciphers. CloudBerry is aware of the issue and looking into it. MBS clients running Windows 7 are affected, but i.e. Windows 10 is not.
