### ISSUE TITLE
Object name invalid error

### ISSUE THREAD

**Issue by obrienmd** [minio/minio#4018]
I'm using Cloudberry backup against minio, with the encrypted filename option on CBB enabled. On a significant share of files, minio is erroring out with 'Object name invalid'.

## Expected Behavior
Minio accepts requests and creates objects.

## Current Behavior
Errors per gist:
https://gist.github.com/obrienmd/d15b9fb8642926a57c22959ec246cb0f

## Possible Solution
Looking at https://github.com/minio/minio/blob/6df7bc42b8c082b8e6033eff283a0f4aa66ed41c/cmd/object-api-utils.go, IsValidObjectName and IsValidObjectPrefix seem like they should both be satisfied by this incoming request, but I'm wildly unqualified to say this with any certainty.

## Steps to Reproduce (for bugs)
1. Start minio.
2. Configure Cloudberry Backup 5.5 with S3-compatible endpoint (minio).
3. Configure a file-based backup plan, enable "Encrypt Filenames".
4. Run backup set.
5. Review minio console output.

## Context
Trying to get backup working with encrypted data and file names.

## Your Environment
* Version used: minio RELEASE.2017-03-16T21-50-32Z
* Environment name and version (e.g. nginx 1.9.1): Caddy 0.95 as reverse proxy in front of minio
* Server type and version: Hyper-V virtual machine, 4 CPU, 16GB RAM
* Operating System and version: Ubuntu 16.04.2 LTS

**Comment by harshavardhana** [comment]
Encrypted backend is not supported yet. Since the paths generated by CBB exceed the filesystem capacities on Linux. .I.e each path component is greater than 255 characters.  

CBB is fixing by working on a Minio only backend support .

**Comment by harshavardhana** [comment]
This feature is scheduled to be released soon by CBB by supporting Minio specific backend configuration. Closing here.
