### ISSUE TITLE
[Feature-Request] Server Side Encryption Support

### ISSUE THREAD

**Issue by AbrohamLincoln-zz** [minio/minio#4020]
I know its been discussed before in #2692 but I would like to request SSE again anyway.
It would be super useful to me to use [SSE-C](http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html) in my particular project.

Thanks!

**Comment by harshavardhana** [comment]
We won't be implementing server side encryption @AbrohamLincoln - it is expected for clients to use client side encryption as proposed and documented by AWS here 

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryptionUpload.html
and you can use minio client APIs in inter-operable way as well http://docs.minio.io/docs/golang-client-api-reference#PutEncryptedObject

Closing this issue.
