### ISSUE TITLE
gateway: Add gateway support for s3 compatible object storage systems in minio.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4022]
gateway mode already supports azure blob store, add support to run minio in gateway mode for any s3 compatible object storage.

**Comment by dennismulder** [comment]
Hey, I work in Azure Storage and noticed this Gateway. Tried playing with it. Unfortunately I keep on getting issues with an invalid access key error. "mc: <ERROR> Invalid access key ‘dmulder.blob.core.windows.net’. Invalid arguments provided, cannot proceed". I am giving it the valid access key for the account. Am I missing something. Also on the server side I see issues:

time="2017-04-01T14:24:33Z" level=error msg="Unable to list objects." cause="Get https://dmulder.blob.core.windows.net.blob.core.windows.net/backup/?comp=list&maxresults=1000&restype=container: dial tcp: lookup d                                                                                                                                                                                                                       mulder.blob.core.windows.net.blob.core.windows.net on 168.63.129.16:53: no such host" source="[gateway-handlers.go:584:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="go/src/github.com/minio/minio/cmd/azure-an                                                                                                                                                                                                                       onymous.go:151:AzureObjects.AnonListObjects <autogenerated>:212:(*AzureObjects).AnonListObjects go/src/github.com/minio/minio/cmd/gateway-handlers.go:577:(GatewayLayer).AnonListObjects-fm go/src/github.com/minio/                                                                                                                                                                                                                       minio/cmd/gateway-handlers.go:582:gatewayAPIHandlers.ListObjectsV1Handler go/src/github.com/minio/minio/cmd/gateway-router.go:100:(gatewayAPIHandlers).ListObjectsV1Handler-fm"

Does the gateway support private blobs?

**Comment by krishnasrinivas** [comment]
@dennismulder can you open a new issue? Also can you copy paste the `mc` command you ran and also the output? note that you have to do `export MINIO_ACCESS_KEY=dmulder` not `export MINIO_ACCESS_KEY=dmulder.blob.core.windows.net`

**Comment by harshavardhana** [comment]
Fixed by #3940
