### ISSUE TITLE
Add caching support for gateway mode. 

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4026]
Add support for caching when starting minio server in gateway mode.
Also : Doc Impact is below :
Deliver a document or enhance an existing document to :
- clearly state what users can do with the gateway enhancements in minio server.
 - comprehensive documentation on how to use and run minio and gateway mode.

**Comment by krishnasrinivas** [comment]
We'll be able to write a good documentation once the caching implementation is complete.
