### ISSUE TITLE
api: AWS JDK objectSummary does not display the key's md5

### ISSUE THREAD

**Issue by rusher81572** [minio/minio#4028]
## Expected Behavior

Return the md5 hash of the file. It works with AWS S3 and s3-compatible solutions.

## Current Behavior

The md5 returned is null

## Steps to Reproduce (for bugs)

Use the AWS JDK to try and view the object summary and extract the MD5
```
  for (S3ObjectSummary objectSummary : objectListing.getObjectSummaries()) {
                    if (process.contains("checkmd5")) {
                        if (objectSummary.getKey().contains(key)) {
                            objectlist = objectSummary.getETag();
                            break;
                        }
                    }
```

## Context

Important for backup and restore applications to verify if the data has changed

## Your Environment

./minio version
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697

**Comment by rusher81572** [comment]
Here is the complete object summary for a key:

S3ObjectSummary{bucketName='snapshot', key='Snapshot-two-2017-03-31/performance_test_data_0_0', eTag='', size=1024, lastModified=Fri Mar 31 18:03:19 PDT

No etag info is there

**Comment by harshavardhana** [comment]
> Here is the complete object summary for a key:
> 
> S3ObjectSummary{bucketName='snapshot', key='Snapshot-two-2017-03-31/performance_test_data_0_0', eTag='', size=1024, lastModified=Fri Mar 31 18:03:19 PDT
> 
> No etag info is there

@rusher81572 - ETag info is deliberately not sent to improve on listing performance on regular filesystem mode, avoids metadata lookup. GET or HEAD on the object would return the ETag as expected. 

Is ETag necessary for you @rusher81572 in LIstObjects()?

**Comment by rusher81572** [comment]
@harshavardhana Thanks for the update. Yes. It is necessary for backup applications to verify if data has changed or not to reduce extra data transfers. Not having it also reduced S3 compatibility with AWS SDK's.

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for the update. Yes. It is necessary for backup applications to verify if data has changed or not to reduce extra data transfers. Not having it also reduced S3 compatibility with AWS SDK's.

It can be added but there is a added performance implication for it we will discuss this internally to bring it back in.

**Comment by rusher81572** [comment]
Thank you

**Comment by alexellis** [comment]
Server-side flag?

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for the update. Yes. It is necessary for backup applications to verify if data has changed or not to reduce extra data transfers.

One question is if the backup is initiated you will be performing a GET operation you can use `If-Match` HTTP -  instead of relying on ListObjects() to give you ETag.  Might as well improve performance of the application. How is the ETag used in the flow can you explain further in detail? 

We are still discussing on bringing it back.

**Comment by harshavardhana** [comment]
Okay so we will enable it @rusher81572 back again.  No server flag @alexellis will do some tests to see the drawbacks, if its terrible we can still stick to what we have.

**Comment by deekoder** [comment]
Pending testing. ETA: Apr 5th.
