### ISSUE TITLE
gateway: Invalid secret key error when using Azure Gateway

### ISSUE THREAD

**Issue by dennismulder** [minio/minio#4033]
I have started the minio Azure Gateway with the following command:
docker run -p 9000:9000 --name azure-s3 -e "MINIO_ACCESS_KEY=dmulder" -e "MINIO_SECRET_KEY=<key>" minio/minio gateway azure

The service starts succesfully:

Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
AccessKey: dmulder
SecretKey: <key>

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myazure http://172.17.0.2:9000 dmulder <key>

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Then when I try and call the Service using the MC command with: 
mc config host add myazure http://<publicip>:9000 dmulder <key>

I get the following error:
mc: <ERROR> Invalid secret key ‘<key>’. Invalid arguments provided, cannot proceed

I tried multiple times and copy/pasted the actual key.

## Expected Behavior
I don't expect the error to show.

## Current Behavior
I get the error above. 
mc: <ERROR> Invalid secret key ‘<key>’. Invalid arguments provided, cannot proceed

## Your Environment
I am running the minio azure gateway on an Ubuntu 16.04 machine in an Azure Virtual Machine. 
I am running MC.exe on Windows.

**Comment by krishnasrinivas** [comment]
> docker run -p 9000:9000 --name azure-s3 -e "MINIO_ACCESS_KEY=dmulder" -e "MINIO_SECRET_KEY=" minio/minio gateway azure

secret key cannot be empty. Did you try to give it empty secret key on purpose?

**Comment by dennismulder** [comment]
No I removed it to not share credentials here (and replaced with <key>) of course I pasted my Primary Azure Storage key there.

**Comment by dennismulder** [comment]
argh angle brackets are replaced here on the github forum (I replaced my keys with [key], but then with angle brackets)

**Comment by vadmeste** [comment]
`mc` only checks the length of the secret key, which should be between 8 and 100 characters.

**Comment by krishnasrinivas** [comment]
(cc @harshavardhana)
The released `mc` does not have the change yet to accommodate longer keys. You will have to compile it from source till the next release is made.

**Comment by dennismulder** [comment]
OK I will do this later this week. BTW. Why is the ACCESS Key not a FQDN? It should be. Azure Storage runs on a few different domain names for the various sovereign clouds provided (eg. USGov, USDoD, Germany, China etc).

**Comment by krishnasrinivas** [comment]
@dennismulder I see. But:
https://github.com/Azure/azure-storage-go/blob/7c36d244fc8bf27bcf9785b0b37d6beef2949296/client.go#L131

It takes account-name and account-key and hence we assumed account-name is like access-key.

Also, https://docs.microsoft.com/en-us/azure/storage/storage-azure-cli : 
```
export AZURE_STORAGE_ACCOUNT=<account_name>
export AZURE_STORAGE_ACCESS_KEY=<key>
```

What do you think?

**Comment by krishnasrinivas** [comment]
>  Azure Storage runs on a few different domain names for the various sovereign clouds provided (eg. USGov, USDoD, Germany, China etc).

then this would be an option for `--endpoint FQDN`

`minio server gateway --endpoing azure.usdod.gov azure`

access-key can still be account-name.

What do you think?

**Comment by dennismulder** [comment]
Makes sense @krishnasrinivas. Is that option already there and does the gateway use it?

**Comment by dennismulder** [comment]
Do you have alternative ways to test the gateway (outside of MC)? Eg. Should the AWS CLI work? (I have playing with that as well, but got errors also). Will do some more testing later this week.

**Comment by harshavardhana** [comment]
> Do you have alternative ways to test the gateway (outside of MC)? Eg. Should the AWS CLI work? (I have playing with that as well, but got errors also). Will do some more testing later this week.

Using aws cli, or s3cmd will work as well.

**Comment by krishnasrinivas** [comment]
> Makes sense @krishnasrinivas. Is that option already there and does the gateway use it?

Not yet, but we can bring it in future.

**Comment by dennismulder** [comment]
With the AWS CLI it seems to work now. I can list Blob Container and upload files. Great work guys.

**Comment by dennismulder** [comment]
BTW. With S3 Browser and Cyberduck I do get errors server side: time="2017-04-03T08:37:23Z" level=error msg="{\"method\":\"GET\",\"path\":\"/\",\"query\":\"\",\"header\":{\"Authorization\":[\"AWS PKE9IBCQMXLVTNN925A7:IEFu0gngHnoN9dvIK6qanDktI+8=\"],\"Host\":[\"52.174.233.10:9000\"],\"User-Agent\":[\"S3 Browser 6-5-9 http://s3browser.com\"],\"X-Amz-Date\":[\"Mon, 03 Apr 2017 08:37:22 GMT\"]}}" cause="Signature does not match" source="[auth-handler.go:117:checkRequestAuthType()]"

time="2017-04-03T08:42:22Z" level=error msg="TLS handshake failed" cause="tls: no certificates configured" source="[server-mux.go:256:newListenerMux.func1.1()]"

I suspect Cyberduck tries to enforce SSL and S3 Browser isn't fully compatible?

**Comment by harshavardhana** [comment]
> I suspect Cyberduck tries to enforce SSL and S3 Browser isn't fully compatible?

They should be you can configure the server with TLS to avoid this error as well -  http://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls

**Comment by deekoder** [comment]
ETA: Apr 3 EOD release will take care of this issue.

**Comment by deekoder** [comment]
Upgrading this to a severe issue.

**Comment by harshavardhana** [comment]
A release has been made and binaries uploaded for `mc`  fixes the issue of secret key limits - https://github.com/minio/mc/releases/tag/RELEASE.2017-04-03T18-35-01Z 

Can you upgrade to latest and validate this  for us @dennismulder with azure gateway - Thanks.

**Comment by harshavardhana** [comment]
@dennismulder will close this as fixed, please re-open if you see an issue with `mc`.

**Comment by dennismulder** [comment]
@harshavardhana now mc config works, but when listing I get the following error:
mc: <ERROR> Unable to list folder. The access key ID you provided does not exist in our records.

the AWS CLI does work.

**Comment by harshavardhana** [comment]
> @harshavardhana now mc config works, but when listing I get the following error:
> mc: Unable to list folder. The access key ID you provided does not exist in our records.

how did you add @dennismulder `mc config` did you add the config param access key and aws cli match? 

// cc @krishnasrinivas

**Comment by dennismulder** [comment]
Never mind. My bad. I had a typo in my accountname. It works.

**Comment by harshavardhana** [comment]
> Never mind. My bad. I had a typo in my accountname. It works.

Okay closing thanks.. @dennismulder
