### ISSUE TITLE
mc mirror --watch --force --remove ignores changes after some days

### ISSUE THREAD

**Issue by ghost** [minio/minio#4036]
mc mirror --watch --force --remove ignores changes after some days

## Expected Behavior
it should mirror local content to minio server even after days without desynch of local and remote location

## Current Behavior
restarting the "mc mirror --watch --force --remove" cmd after some 10+days revealed that it missed out on a couple 150+ delete operations and also on some uploads

## Steps to Reproduce (for bugs)

1. have a directory wich is constantly updated 24/7 (we have advertisements coming in every few minutes and some vanish after they're expired)
2. have mc mirror --watch --force --remove ./local minio/remotebucket running
3. after some days restart the process and see mc delete a lot and upload some files

## Context
constantly mirror local to central distribution server.
have a near realtime updated playlist / content on the playout systems.

## Your Environment
Debian jessie
mc from 2 weeks ago i think. (version flag says 0.0.0)
caddyserver in front of minio (timeouts set to 30 minutes)

**Comment by vadmeste** [comment]
@xstillwill, can you move this issue to https://github.com/minio/mc ?
