### ISSUE TITLE
CORS missing Access-Control-Allow-Credentials header

### ISSUE THREAD

**Issue by MikaelWahlberg** [minio/minio#4044]
When doing a Preflight request with the Javascript FileAPI ( https://github.com/mailru/FileAPI ) 
(For a presigned POST) Minio does not respond with a Access-Control-Allow-Credentials: true header. 

When doing the same request to Amazon S3 we do get the header (After CORS is configured correctly on the bucket of course)

## Expected Behavior
I would like Access-Control-Allow-Credentials: true to be set

## Current Behavior
When doing the request (OPTIONS) Chrome responds with the following message in the Console:

> XMLHttpRequest cannot load http://minio.cantemo.com:9000/xx. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://xx.dev' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute

## Possible Solution
I tested adding:
```
diff --git a/cmd/generic-handlers.go b/cmd/generic-handlers.go
index 83cf031..aba3764 100644
--- a/cmd/generic-handlers.go
+++ b/cmd/generic-handlers.go
@@ -278,6 +278,7 @@ func setCorsHandler(h http.Handler) http.Handler {
                AllowedMethods: defaultAllowableHTTPMethods,
                AllowedHeaders: []string{"*"},
                ExposedHeaders: []string{"ETag"},
+               AllowCredentials: true,
        })
        return c.Handler(h)
 }


```
And that solved the problem.  Is there a specific reason this is not there?  Or am I missing something obvious here? 

## Your Environment
* Version used: latest master
* Environment name and version (e.g. nginx 1.9.1): Direct access
* Server type and version: Linux
* Operating System and version: Centos7
* Link to your project: N/A

**Comment by harshavardhana** [comment]
> And that solved the problem. Is there a specific reason this is not there? Or am I missing something obvious here?

No specific reason we can certainly add it. Thanks for the bug report @MikaelWahlberg

**Comment by vadmeste** [comment]
I think CORS parameters should be part of the config, we can't generalize it otherwise it will be a security risk.

`Allowed-Origins: *` means if a user opens any malicious web page from any location in his browser, the javascript inside that web page can do harmful things to his Minio session (like removing buckets, objects, etc..)

**Comment by MikaelWahlberg** [comment]
While I agree with that, it is a separate issue to the one I reported. I just want credentials to be allowed as well when other CORS are allowed. 

Making it the whole CORS-thing a config is of course a good idea in general.

**Comment by krishnasrinivas** [comment]
As long as we don't use Cookie header for auth/session management (of browser login by admin), we should be fine. Else Minio will be exposed for cross site scripting.

Let me check more if this is safe for us.
