### ISSUE TITLE
ecosystem: Support Minio to be an external persistent storage solution for k8s

### ISSUE THREAD

**Issue by abaumann0204** [minio/minio#4048]
Kubernetes is really a very important open source cloud technology project.
For many cloud projects storage is also very important. Normal docker based solutions are not always the best way. In the case of multi node clusters kubernetes introduced the concept of Persistent Volumes. Today there are a bunch of solution available. Some of this are commercial solutions and some are open source. 
From my point of view most of this solutions are complex.
Minio is a very intersting distributed storage solution which is powerful and is easy to manage ( a smarter solution ==> relation between functionallity and complexity ).

The write way to implement minio as provider of Persistent Volumes is the concept of external storage, which was introduced in the kubernetes project some month ago.

The is a project which shows examples of external storage implementations:

https://github.com/kubernetes-incubator/external-storage

**Comment by nitisht** [comment]
Thank you @abaumann0204 
We will explore this.

**Comment by deekoder** [comment]
Please go through this link : https://mesosphere.com/blog/2017/03/30/csi-towards-universal-storage-interface-for-containers/ 
Multiple vendors are working together to standardize a container storage interface. At the moment, we don't mind working with each one of them to tightly integrate Minio.  Similar to OpenStack's Swift Object, Cinder Block and Manila File storage interface, it will be nice to see Object Storage interface included in these systems natively.  Object Storage is good for container images as well as application blob data. File and Block are good for persistent data volumes.  

We can explore MinFS as a file interface compatible with existing providers.
