### ISSUE TITLE
Startup fails if webhook endpoint is offline.

### ISSUE THREAD

**Issue by AbrohamLincoln-zz** [minio/minio#4050]
In my development environment my webhook endpoint was offline.  During this time startup of a Minio node would fail.

## Expected Behavior
I'm not entirely sure if this is operating as intended or a bug, but it seems to me having Minio up and running is preferable to stopping due to a down webhook endpoint.

Minio should log the error and continue with initialization.

## Current Behavior
Minio logs the following error and stops:

` time="2017-04-03T11:14:01Z" level=fatal msg="Unable to initialize event notification." cause="dial tcp 192.168.1.5:443: getsockopt: no route to host" source="[xl-v1.go:91:newXLObjectLayer()]"`

## Possible Solution
Maybe make this a non-fatal error by adding some handling somewhere around here:
https://github.com/minio/minio/blob/master/cmd/xl-v1.go#L87

## Steps to Reproduce (for bugs)
1. Add an invalid webhook endpoint to the server config.
2. Restart minio.

## Your Environment
* Version used: 2017-03-16T21:50:32Z

**Comment by harshavardhana** [comment]
It is operating as intended. We deliberately fail because it indicates a configuration mistake, if you have your endpoint offline you should turn the config for webhook from `true` to `false`

**Comment by AbrohamLincoln-zz** [comment]
Consider this scenario:

You have a webhook configured to notify a third party endpoint.
The third party endpoint fails temporarily for (insert some reason here).
During that temporary outage your Minio nodes restart for (insert some other reason here).
Your distributed Minio will fail to start despite having a valid config.

It seems to me that having a functional Minio instance is preferable to throwing a critical error because it can't notify an external system.

**Comment by deekoder** [comment]
Webhook is async unlike elastic search, NATs targets. So @AbrohamLincoln is right in that we should not exit for offline webhook events.

**Comment by harshavardhana** [comment]
ETA - another 2 hrs.

**Comment by deekoder** [comment]
Not fixed. Reopening.
