### ISSUE TITLE
Windows Based Minio Cluster Setup

### ISSUE THREAD

**Issue by ChiefArchitect** [minio/minio#4055]
I have a well working standalone minio server on a windows machine. at this point i would like to scale it out and started looking at the distributed minio documentations

minio server http://10.165.241.122/c:\dev\store1  http://10.165.241.123/c:\dev\store2  - doesnt work
minio server http://10.165.241.122:c:\dev\store1  - doesnt work
minio server http://10.165.241.122/c:/dev/store1  - doesnt work

the difference between linux mounts and windows folders are not well documented and had failed to start a cluster

## Your Environment

* Version used: github version
* Environment : have 2 windows machines and one Mac that i would like to setup a cluster on
* Server type and version: Windows 2012R2 , MacOS Sierra 10.12.3

**Comment by ChiefArchitect** [comment]
C:\dev\ObjectStorage>minio server http://10.165.241.122/C:\dev\store1 http://10.165.241.122/C:\dev\store2 http://10.165.241.122/C:\dev\store3 http://10.165.241.122/C:\dev\store4
time="2017-04-06T18:12:07+03:00" level=fatal msg="Initializing object layer failed" cause="Unsupported backend format [fs] found" source="[server-main.go:587:serverMain()]"

**Comment by krishnasrinivas** [comment]
on slack:

> chief: ok now its working after deletion of the data of store 1 - many thanks

@ChiefArchitect @deekoder  can you close this?

**Comment by deekoder** [comment]
Closing this. Since this issue is resolved for @ChiefArchitect. But I am also opening a doc issue so that we clearly document the nuances for Windows.
