### ISSUE TITLE
Variable to point to a new directory for config file

### ISSUE THREAD

**Issue by finid** [minio/minio#4058]
## Expected Behavior

Just a question:

If I move the config directory from `~/.minio` to `/etc/minio`, for example, how can I inform Minio of the change in `/etc/default/minio`?

**Comment by vadmeste** [comment]
@finid, Hello,

`minio -C /etc/default/minio/` will do.

**Comment by harshavardhana** [comment]
> If I move the config directory from ~/.minio to /etc/minio, for example, how can I inform Minio of the change in /etc/default/minio?

You need to edit the 

```
cat <<EOT >> /etc/default/minio
# Use if you want to run Minio on a custom port.
MINIO_OPTS="-C /etc/minio --address :9199"

EOT
```

**Comment by finid** [comment]
Thank you.
