### ISSUE TITLE
docs: Document what's the recommended user and group to run Minio. 

### ISSUE THREAD

**Issue by finid** [minio/minio#4061]
## Expected Behavior

I have Minio running fine, but just need to get a better understanding of some of the configurations options.

In the systemd service descriptor file, one has to specify the user and group that Minio should run as. For my installation, I created a new system user with no login access for Minio, but I've seen other configurations where `root` was specified for the user and group.

So my question is, what's the recommended and most secure approach? Running as root or as a new system user?

**Comment by koolhead17** [comment]
hello @finid It is not required to run minio as root. If you check https://github.com/minio/minio-service/tree/master/linux-systemd  and the minio-service file, it has ``service`` section
```
[Service]
User=minio-user
Group=minio-user
```

Feel free to use the user you would like Minio to run.

hope. it helps.

**Comment by harshavardhana** [comment]
@finid you can use any normal user or create a special user which has no shell access. Perhaps you can use `nobody:nobody` given the user has proper access perms to the /etc/minio directory which systemctl service uses by default. 

The general guide line is to avoid `root` and run it as a normal user, now what kind of restrictions based on cgroups, permissions this user needs to have is based on case to case basis.

**Comment by harshavardhana** [comment]
Please do let us know if you need us to describe these details further. @finid

**Comment by finid** [comment]
Thanks, @koolhead17, @harshavardhana. 

This question came up for me, because I'm setting Minio up with TLS support on a system that already has a Let's Encrypt certificate set up for domains on the server. Being that LE doesn't issue certs to an IP address, Minio was configured to use one of the domain's certs by symlinking to `/etc/minio/certs` to that domain's certs.

It looked good, but Minio fails to start with this error:
```
level=fatal msg="Unable to load a CA files" cause="open /etc/minio/certs/fullchain.pem: permission denied"
```
So this is a case of the Minio user attempting to open a file owned by user/group root. Does it make sense to work around this by making the Minio user a member of `sudo`? A different angle?

**Comment by koolhead17** [comment]
@finid Please check https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio . After generating the cert we have changed it ownership and permission.

### Step 5: Change ownership of certificates.

```
$ sudo chown supernova:supernova /home/supernova/.minio/certs/private.key
$ sudo chown supernova:supernova /home/supernova/.minio/certs/public.crt
```

Hope this helps.

**Comment by harshavardhana** [comment]
Removed `fixed` @koolhead17 is sending a fix for the document and cleaning it up.

**Comment by harshavardhana** [comment]
Is this fixed already @koolhead17 @NitishT ?
