### ISSUE TITLE
tests: TestPostPolicyBucketHandler unit test fails

### ISSUE THREAD

**Issue by krisis** [minio/minio#4067]
## Expected Behavior

TestPostPolicyBucketHandler unit test should pass.
## Current Behavior

```
--- FAIL: TestPostPolicyBucketHandler (4.21s)  	<autogenerated>:10: Test 4: FS: Expected the response status to be `400`, but instead found `403`
```
## Possible Solution

Not known
## Steps to Reproduce (for bugs)

1. `make test`
2.
3.
4.

## Context

CI failure - https://travis-ci.org/minio/minio/jobs/219567604
## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by nitisht** [comment]
Looks like this passed on latest CI jobs - https://travis-ci.org/minio/minio/jobs/232330173
Also passed locally.

**Comment by harshavardhana** [comment]
> Looks like this passed on latest CI jobs - https://travis-ci.org/minio/minio/jobs/232330173
> Also passed locally.

Its a very rare issue you need to reproduce it properly with probably with `go test -run TestPostPolicyBucketHandler -count 10000`

**Comment by nitisht** [comment]
```
Nitishs-MacBook:minio nitish$ go test -run TestPostPolicyBucketHandler -count 10000
PASS
ok  	github.com/minio/minio	0.255s
Nitishs-MacBook:minio nitish$ go test -run TestPostPolicyBucketHandler -count 20000
PASS
ok  	github.com/minio/minio	0.323s
Nitishs-MacBook:minio nitish$ go test -run TestPostPolicyBucketHandler -count 30000
PASS
ok  	github.com/minio/minio	0.286s
Nitishs-MacBook:minio nitish$ go test -run TestPostPolicyBucketHandler -count 40000
PASS
ok  	github.com/minio/minio	0.424s
Nitishs-MacBook:minio nitish$ 
```
Still passed..I'll try with some other values as well.
