### ISSUE TITLE
copy condition unmodified fails in minio

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4080]
Below minio-java functional test fails in play.minio.io whereas it succeeds in amazon s3.

```java
    CopyConditions copyConditions = new CopyConditions();
    DateTime dateRepresentation = new DateTime(2015, Calendar.MAY, 3, 10, 10);
    copyConditions.setUnmodified(dateRepresentation);
    client.copyObject(bucketName, filename, destBucketName, copyConditions);
```
Failure message:
```
ErrorResponse(code=PreconditionFailed, message=At least one of the pre-conditions you specified did not hold, bucketName=null, objectName=null, resource=/minio-java-test-2ffm6th/minio-java-test-g9dvi7, requestId=3L137, hostId=3L137)
request={method=PUT, url=https://play.minio.io:9000/minio-java-test-2ffm6th/minio-java-test-g9dvi7, headers=x-amz-copy-source-if-unmodified-since: Fri, 03 Apr 2015 17:10:00 +00:00
x-amz-copy-source: minio-java-test-3n2cg3a%2Fminio-java-test-g9dvi7
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
Host: play.minio.io:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20170409T131324Z
Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20170409/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-unmodified-since;x-amz-date, Signature=4e5b1404d533fcafbe9468abdbb11b310184ddbcf1abb1c5fb281b061f3549e8
Content-Type: application/octet-stream
Content-Length: 0
}
response={code=412, headers=Accept-Ranges: bytes
Content-Type: application/xml
Etag: "f7f14b0dc4fc67f17f7590be179ad2de"
Last-Modified: Sun, 09 Apr 2017 13:13:24 GMT
Server: Minio/DEVELOPMENT.2017-04-06T07-23-25Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14B3BCE78F6F4807
Date: Sun, 09 Apr 2017 13:13:24 GMT
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1491743604320
OkHttp-Received-Millis: 1491743604327
```

## Expected Behavior

Should work as like amazon s3

## Steps to Reproduce (for bugs)

1. Use the above code snippet.
2.
3.
4.

## Your Environment

* Version used: play.minio.io
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by vadmeste** [comment]
@balamurugana, 

`copyConditions.setUnmodified(new DateTime(2015, Calendar.MAY, 3, 10, 10))` means copy the source only if it is not modified since 3 May 2015, so this is intended to fail as Minio did.

However, if I test CopyObject of minio-go, it fails with AWS S3:

```
s3Client, err := minio.New("s3.amazonaws.com", "xxx", "xxx", true)
if err != nil {
    log.Fatalln(err)
}

var copyConds = minio.CopyConditions{}
copyConds.SetUnmodified(time.Date(2014, time.April, 0, 0, 0, 0, 0, time.UTC))
err = s3Client.CopyObject("vadmeste-dst", "my-objectname-copy", "/vadmeste/my-objectname", copyConds)
if err != nil {
    log.Fatalln(err)
}
```
**=>** 
```
2017/04/09 22:05:50 At least one of the pre-conditions you specified did not hold
```


So, it looks more like a minio-java bug, what do you think ?

**Comment by harshavardhana** [comment]
BTW `minio-java` function test runs fine with play. 

```
Test: copyObject(String bucketName, String objectName, String destBucketName)
Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions) with Matching ETag (Negative Case)
Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions) with Matching ETag (Positive Case)
Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions) with not matching ETag (Positive Case)
Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions) with not matching ETag (Negative Case)
Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions) with modified after condition (Positive Case)
Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions) with modified after condition (Negative Case)
Test: threadedPutObject
```

**Comment by vadmeste** [comment]
Yes, this problem only occurs with AWS S3

**Comment by harshavardhana** [comment]
> Yes, this problem only occurs with AWS S3

From what i can remember with `s3verify` we have seen that some times S3 behaves in a wrong manner i.e not following the spec and then it starts working fine. Frequent with buckets which are created newly and it starts working in accordance with spec after some time.  This is a sporadic problem so minio server behavior is correct here.

**Comment by harshavardhana** [comment]
Looks like it is working fine i created bucket in `us-west-1`

```diff
diff --git a/functional/FunctionalTest.java b/functional/FunctionalTest.java
index 214b119..f49c19f 100644
--- a/functional/FunctionalTest.java
+++ b/functional/FunctionalTest.java
@@ -1065,8 +1065,8 @@ public class FunctionalTest {
 
     String fileName = createFile(3 * MB);
 
-    client.makeBucket(bucketName);
-    client.makeBucket(secondBucketName);
+    client.makeBucket(bucketName, "us-west-1");
+    client.makeBucket(secondBucketName, "us-west-1");
     client.putObject(bucketName, fileName, fileName);
 
     CopyConditions copyConditions = new CopyConditions();
```

```
Test: copyObject(String bucketName, String objectName, String destBucketName,String destObjectName)
Test: copyObject(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions) with Matching ETag (Negative Case)
Test: copyObject(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions) with Matching ETag (Positive Case)
Test: copyObject(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions) with not matching ETag (Positive Case)
Test: copyObject(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions) with not matching ETag (Negative Case)
Test: copyObject(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions) with modified after condition (Positive Case)
Test: copyObject(String bucketName, String objectName, String destBucketName, String destObjectName, CopyConditions copyConditions) with modified after condition (Negative Case)
Test: threadedPutObject
```

**Comment by vadmeste** [comment]
> From what i can remember with s3verify we have seen that some times S3 behaves in a wrong manner i.e not following the spec and then it starts working fine. Frequent with buckets which are created newly and it starts working in accordance with spec after some time. This is a sporadic problem so minio server behavior is correct here.

That's true, 

However, with the same source bucket & object that I've created, minio-go shows the correct behavior but minio-java doesn't, most likely this is a weird bug in minio-java.

@harshavardhana does your test cover unmodified use case ?

**Comment by harshavardhana** [comment]
> That's true,
> 
> However, with the same source bucket & object that I've created, minio-go shows the correct behavior but minio-java doesn't, most likely this is a weird bug in minio-java.
> 
> @harshavardhana does your test cover unmodified use case ?

I am running minio-java functional test . that's all. @vadmeste

**Comment by harshavardhana** [comment]
Closing this as bug in minio-java instead - https://github.com/minio/minio-java/issues/546

**Comment by balamurugana** [comment]
What is the conclusion?  `minio-java` expects a failure which is got in minio server but not amazon S3.   If `minio-java` is buggy, why isn't minio server working? Don't both servers behave similar in this case irrespective of `minio-java` is buggy?

**Comment by harshavardhana** [comment]
> What is the conclusion? minio-java expects a failure which is got in minio server but not amazon S3. If minio-java is buggy, why isn't minio server working?

There are two things here 

- Incorrect time sent by minio-java - AWS S3 just ignores the time if its not in the right format. Setting correct time format generates the same error as generated by Minio server.

```
x-amz-copy-source-if-unmodified-since: Fri, 03 Apr 2015 17:10:00 +00:00
```

This is not the `http.TimeFormat`

```
0001-01-01 00:00:00 +0000 UTC parsing time "Fri, 03 Apr 2015 17:10:00 +00:00" as "Mon, 02 Jan 2006 15:04:05 GMT": cannot parse "+00:00" as " GMT"
```

- Minio server treats it as failure instead of proceeding with the call i.e incorrect time was sent by the client. 

```go
        // x-amz-copy-source-if-unmodified-since : Return the object only if it has not been
        // modified since the specified time, otherwise return a 412 (precondition failed).
        ifUnmodifiedSinceHeader := r.Header.Get("x-amz-copy-source-if-unmodified-since")
        if ifUnmodifiedSinceHeader != "" {
                if ifModifiedSince(objInfo.ModTime, ifUnmodifiedSinceHeader) {
                        // If the object is modified since the specified time.
                        writeHeaders()
                        writeErrorResponse(w, ErrPreconditionFailed, r.URL)
                        return true
                }
        }
```

`ifModifiedSince` returns `true` if failed to parse the time sent, where as AWS S3 just ignores the incorrect time sent.  It is preferred to not proceed when a client is buggy, so Minio server behavior would be preferred. If one proceeds it might mean that an I/O should be attempted which might be undesirable.

**Comment by balamurugana** [comment]
> Incorrect time sent by minio-java - AWS S3 just ignores the time if its not in the right format. Setting correct time format generates the same error as generated by Minio server.

If amazon S3 works by ignoring the date with a buggy client, the expected behavior should be same as in minio server.  minio-java is one of such kind of buggy client.

This issue needs to be fixed at the server.

**Comment by harshavardhana** [comment]
> If amazon S3 works by ignoring the date with a buggy client, the expected behavior should be same as in minio server. minio-java is one of such kind of buggy client.

No we should not @balamurugana at times we have to do the right thing, it would have been fine if its some other sort of call like GET etc - relaxing this causes an unexpected write on the server side i.e a file is copied.  

It could be possible that AWS S3 would fix this in future which means that we will be at a disadvantage. It is not correct mimic bad behavior, it is better for the client to fix itself and perform the proper request.

**Comment by balamurugana** [comment]
If Amazon S3 ignores wrong date format and continue the operation, minio server should do the same.  Currently the server treats as some specific timezone and continues which is wrong.

**Comment by balamurugana** [comment]
> It could be possible that AWS S3 would fix this in future which means that we will be at a disadvantage. It is not correct mimic bad behavior, it is better for the client to fix itself and perform the proper request.

If so, amazon s3 would return different error code  for this case.  that leads for the fix in minio server as well.  In both the cases we should fix it.

**Comment by harshavardhana** [comment]
> If Amazon S3 ignores wrong date format and continue the operation, minio server should do the same. Currently the server treats as some specific timezone and continues which is wrong.

Actually there is a better reason to do so.  According to https://tools.ietf.org/html/rfc7232#section-3.4
```  
A recipient MUST ignore the If-Unmodified-Since header field if the
received field-value is not a valid HTTP-date.
```

So it would seem that AWS S3 is behaving in accordance with HTTP spec.

**Comment by harshavardhana** [comment]
Actually will close this an open a separate issue, it is for GetObject, HeadObject, CopyObject.

**Comment by balamurugana** [comment]
> Actually will close this an open a separate issue, it is for GetObject, HeadObject, CopyObject.

There is no good reason to close this and refer in another new issue.  The issue title/description could have been modified to address the decided.

**Comment by harshavardhana** [comment]
> There is no good reason to close this and refer in another new issue. The issue title/description could have been modified to address the decided.

There is a reason, this issue only talks about CopyObject - the issue exists even for Head() and Get().

**Comment by balamurugana** [comment]
> There is a reason, this issue only talks about CopyObject - the issue exists even for Head() and Get().

You are free to modify the issue title/description though.
