### ISSUE TITLE
notifications: Simplify generating and adding new notifications

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4081]
## Expected Behavior
Currently adding and removing notification is hard - explore ways to make it simpler. 

## Current Behavior
Cryptically modifying config files and not being able to edit config to be syntax error free. 

## Possible Solution
No solution yet.

## Steps to Reproduce (for bugs)
Architectural issue.

## Context
Simplification for overall usage of Minio.

## Your Environment
Current master

**Comment by harshavardhana** [comment]
TO be discussed.. no ETA

**Comment by deekoder** [comment]
@balamurugana  since you are looking at these.

**Comment by balamurugana** [comment]
@deekoder Yep
