### ISSUE TITLE
browser: Firefox does not save AccessKey

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4084]
Firefox does not save "AccessKey" after login in "Do you want to save password?" dialog box.

**Comment by krishnasrinivas** [comment]
![ss](https://cloud.githubusercontent.com/assets/634494/24886542/2ebe3fa4-1e0a-11e7-86f9-9ac24279b708.jpg)

**Comment by deekoder** [comment]
PR is pending.

**Comment by harshavardhana** [comment]
Fixed by #4091
