### ISSUE TITLE
docs: [faq] Can attaching multiple block devices to a server be used to satisfy the distributed setup drive minimum? 

### ISSUE THREAD

**Issue by finid** [minio/minio#4085]
> As with Minio in stand-alone mode, distributed Minio has a per tenant limit of minimum 4 and maximum 16 drives (imposed by erasure code).

The above quote is from the [official doc on distributed Minio setup](https://docs.minio.io/docs/distributed-minio-quickstart-guide). My question on that is, can that drive minimum be met using two servers and attaching an extra block device to each?

**Comment by harshavardhana** [comment]
> The above quote is from the official doc on distributed Minio setup. My question on that is, can that drive minimum be met using two servers and attaching an extra block device to each?

Yes it can be @finid

**Comment by finid** [comment]
I guess I should have read most of that page before asking, as the answer is right on there.

Thank you.
