### ISSUE TITLE
ecosystem: Add support to BOSH system to use Minio as blobstore

### ISSUE THREAD

**Issue by donatello** [minio/minio#4089]
This is part of enhancing the ecosystem around both Minio and BOSH.

## Expected Behavior

BOSH should be able to download blobs from a blobstore hosted using a Minio deployment.

## Current Behavior

BOSH does not support working with blobstores other than S3 and Atmos.

## Possible Solution

Add support to BOSH components to use Minio as a blobstore. 

## Context

This was initially opened here https://github.com/minio/minio-boshrelease/issues/2

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by donatello** [comment]
The newer [bosh-cli v2](https://bosh.io/docs/cli-v2.html) supports using Minio as a blobstore - settings for minio can be specified via extra options in the blobstore related configuration files like `config/final.yml` and `config/private.yml`. The list of available options is present here - https://github.com/pivotal-golang/s3cli/blob/master/config/config.go#L17

Currently, using Minio with the older bosh cli does not appear to work - because there is no facility to specify a port in the options [supported by it](https://github.com/cloudfoundry/bosh/blob/631179db59d4a38ce596d491f692be3c96938186/src/bosh-director/spec/functional/s3_spec.rb#L180). Also blobstore options supported by the older bosh cli and the newer bosh cli appear to be incompatible.

**Comment by deekoder** [comment]
Needs to be tested and documented.
