### ISSUE TITLE
When put file to minio server, some reason put have been cancelled, minio not delete extra fs.json in .minio.sys/buckets directory

### ISSUE THREAD

**Issue by JYang1986** [minio/minio#4090]
When I put file by s3cmd， then I cancelled， this log info has appeared。

[root@node2 s3cmd]# ./s3cmd put 1G.txt s3://test/1G_2.txt --disable-multipart
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: '1G.txt' -> 's3://test/**1G_2.txt**'  [1 of 1]
  726007808 of 1073741824    67% in   77s     8.88 MB/s^CSee ya!
[root@node2 s3cmd]# 

ERRO[0289] Failed to create object test/**1G_2.txt**         cause=unexpected EOF source=[fs-v1.go:566:fsObjects.PutObject()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:480:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0289] Unable to create an object. /test/**1G_2.txt**    cause=#has incomplete body source=[object-handlers.go:483:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:267:fsCreateFile fs-v1.go:563:fsObjects.PutObject <autogenerated>:298:(*fsObjects).PutObject object-handlers.go:480:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm

In this test, minio will delete tmp file for 1G_2.txt, but the buckets not delete **1G_2.txt**.
[root@node1 test]# pwd
/home/minio/test/.minio.sys/buckets/test
[root@node1 test]# ls -l
total 0
drwxr-xr-x 2 root root 20 Apr 11 14:10 **1G_2.txt**
drwxr-xr-x 2 root root 20 Apr 11 14:17 1G_3.txt
drwxr-xr-x 2 root root 20 Apr 11 09:46 1G.txt
[root@node1 test]# ls 1G_2.txt/fs.json -l
-rw-r--r-- 1 root root 329 Apr 11 15:18 **1G_2.txt/fs.json**
[root@node1 test]#

**Comment by vadmeste** [comment]
@Saber-Yang, thanks for reporting,

We don't have the same behavior with `mc`, not sure what s3cmd is doing to trigger this, but it looks like a serious bug, we'll investigate further.

**Comment by vadmeste** [comment]
ETA 12 Apr.

**Comment by deekoder** [comment]
@vadmeste  can this be closed?

**Comment by vadmeste** [comment]
A PR was sent and got one approval.
