### ISSUE TITLE
gateway: Support for GetBucketLocation

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4092]
Currently we return minio's region us-east-1 at GetBucketLocationHandler instead of forwarding the request to backend. This is relevant more for S3 backend. GatewayInterface would need one more call GetBucketLocation.

**Comment by harshavardhana** [comment]
Is this fixed? @krishnasrinivas

**Comment by krishnasrinivas** [comment]
@harshavardhana not yet

**Comment by krishnasrinivas** [comment]
ETA May-2

**Comment by deekoder** [comment]
Blocks #4241

**Comment by deekoder** [comment]
Not a showstopper for today's release. May 4.

**Comment by deekoder** [comment]
ETA 5/8/2017

**Comment by krishnasrinivas** [comment]
blocked on @abperiasamy for discussion

**Comment by krishnasrinivas** [comment]
At gateway during signature verification we need the bucket region. We can use the region sent by the client itself for this. But gateway's S3 layer shares code with server's S3 layer for all the multipart/policy related handlers. This code uses `serverConfig.GetRegion()` to get the region.

Hence we have 4 choices:
* duplicate the shared code so that it does not do `serverConfig.GetRegion()` (but a lot of code gets duplicated just for this)
* make GetBucketLocation part of ObjectLayer interface so that XL and FS implementations return whatever that has been configured (`serverConfig.GetRegion()`) and gateway implementation can return appropirate values from the azure/aws backend.
* Restrict gateway to only one region just like minio-server
* make the server code also use whatever region the client sends i.e disable region configuration completely

**Comment by deekoder** [comment]
- if server is configured with region, then we use that region in signature verification.
- if not, we simply trust the region set by the client.
- if no region is set by the client, use region from the request.
This behavior is common for server & gateway.

**Comment by deekoder** [comment]
![region](https://cloud.githubusercontent.com/assets/1700901/25926773/fbbad7e4-35a5-11e7-8a7a-a77142684693.png)

**Comment by deekoder** [comment]
Other related  changes for minio server startup message: 
- Remove SQS ARNS do not print "none".
- If region is not set,  do not print "none".

**Comment by krishnasrinivas** [comment]
https://github.com/minio/minio/pull/4329 will fix this issue.
