### ISSUE TITLE
Can not set object as public

### ISSUE THREAD

**Issue by rusher81572** [minio/minio#4093]
Hello, I am using aws-java-sdk-1.11.111.jar with the following code to set an objects permission to public on minio.RELEASE.2017-02-15T22-55-24Z

```
            s3Client.setObjectAcl(bucket, object, CannedAccessControlList.PublicRead);
```
Full code located here: 
https://github.com/rusher81572/cloudExplorer/blob/master/src/cloudExplorer/Acl.java

When I try to access the object I get the following error:
 
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key/>
<BucketName/>
<Resource>/test/test</Resource>
<RequestId>3L137</RequestId>
<HostId>3L137</HostId>
</Error>
```

It works fine on AWS and other S3 compatible servers.

Here is the dump:

```
-----
RESPONSE STATUS: 501 Not Implemented
Date: Tue, 11 Apr 2017 16:43:15 GMT
Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-02-16T01-47-30Z (linux; arm)
X-Amz-Request-Id: 14B46584617F4E30

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Key></Key><BucketName></BucketName><Resource>/test/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
--------------------------
```

If I use GeneratePresignedUrlRequest, it works fine with the account identifies appended to the string:

```
http://127.0.0.1:8000/test/test?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20170411T164549Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60000&X-Amz-Credential=EB90BT8N1SADGX1T36N4%2F20170411%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7bf374832ee6ead8d5ffc7c1d7207e683b7c782ac1961bdc75d6edc70166f1c5
```

**Comment by harshavardhana** [comment]
@rusher81572 we don't support ACLs and have no plans on supporting it in the future - https://github.com/minio/minio/blob/master/docs/minio-limitations.md#list-of-amazon-s3-bucket-apis-not-supported-on-minio

**Comment by rusher81572** [comment]
Thanks.

**Comment by harshavardhana** [comment]
We did upstream work for example alluxio had similar problems - if you need to look @rusher81572 - https://github.com/Alluxio/alluxio/pull/4217
