### ISSUE TITLE
Not able to run minio server bound to specific ip address

### ISSUE THREAD

**Issue by akb2017** [minio/minio#4094]
I am not able to run minio server bound to specific ip addresss.
If I do like  ./minio server --address 192.168.1.14:9000 /home/shared/  iam not able to run the server
 Minio is downloaded and kept in another server ,If i run this command from there iam not able to run the server

## Expected Behavior
Iam expecting the server to run and the data should be stored in server 2. i.e Iam running the command from server 1 and refering the data to be stored in server2
## Current Behavior
Getting error as --> 
**FATA[0001] Failed to start minio server.  cause=listen tcp 192.168.1.14:9000: bind: cannot assign requested address source=[server-main.go:580:serverMain.func1()]**

**Comment by harshavardhana** [comment]
> Getting error as -->
> FATA[0001] Failed to start minio server. cause=listen tcp 192.168.1.14:9000: bind: cannot assign requested address source=[server-main.go:580:serverMain.func1()]

You already have another service running on port 9000 @akb2017 you choose another port 

```
./minio server --address 192.168.1.14:9001 /home/shared/ 
```

Check if there is another service running 

```
netstat -ntlp | grep 9000
```

**Comment by akb2017** [comment]
I tried this ./minio server --address 192.168.1.14:9001 /home/shared/ but getting the same error..
Even i tried in other servers but same problems..

**Comment by koolhead17** [comment]
Hello @akb2017 

This is what how got it working.

```
$ minio server fu

Endpoint:  http://10.0.0.4:9000  http://127.0.0.1:9000
AccessKey: BKIKJAA5BMMU2RHO6IBB 
SecretKey: V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://10.0.0.4:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.4:9000 BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 223 GiB Free, 465 GiB Total
```

Now to run it on a particular IP address, this is what I did.

```
$ minio server --address 127.0.0.1:9000 fu

Endpoint:  http://127.0.0.1:9000
AccessKey: BKIKJAA5BMMU2RHO6IBB 
SecretKey: V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:9000 BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 223 GiB Free, 465 GiB Total
```
As @harshavardhana suggested, can you check if the ports are not used by any other service?

**Comment by akb2017** [comment]
Checked this port is not used any other service

**Comment by koolhead17** [comment]
Can you share Operating System over all deployment environment?  We can try to re-produce.

**Comment by harshavardhana** [comment]
> I tried this ./minio server --address 192.168.1.14:9001 /home/shared/ but getting the same error..
> Even i tried in other servers but same problems..

Are you sure this IP is local to the server? perhaps `ip addr` ?

**Comment by akb2017** [comment]
Both are connected using ssh connection
server1 ip is :192.168.1.24 and server  :192.168.1.25 
iam running the minio server from server1 and it is supposed  to run and create storage on server2

**Comment by harshavardhana** [comment]
> Both are connected using ssh connection
> server1 ip is :192.168.1.24 and server :192.168.1.25
> iam running the minio server from server1 and it is supposed to run and create storage on server2

But you are trying to set "192.168.1.14" is there a typo?

**Comment by harshavardhana** [comment]
you should set 

```
./minio server --address "192.168.1.24:9000" /home/shared
```

**Comment by akb2017** [comment]
Actually iam trying store my data in server2 buy running it in server1, i.e from 192.168.1.14

**Comment by akb2017** [comment]
*by

**Comment by harshavardhana** [comment]
> Actually iam trying store my data in server2 buy running it in server1, i.e from 192.168.1.14

you have to listen on your local IPs but you just said your server1 ip is 192.168.1.24 ?? - I think i am lost so lets backtrack and get some answers.

- Where exactly you are running the minio server? is it on server1 or server2 ?
- What are the local IPs on the server1 and what are the local IPs on server2? - please paste the output of `ip addr`

**Comment by akb2017** [comment]
Sorry by mistake i gave that ip , 
server 1 ip-192.168.1.24
server 2 ip-192.168.1.25

**Comment by akb2017** [comment]
Iam running the server on server1 i.e on 192.168.1.24 
Now i want it to store the data on 192.168.1.25 
the command is ./minio server --address 192.168.1.25:9004 /home/shared/

**Comment by krishnasrinivas** [comment]
@akb2017 I think you have misunderstood on how minio works.

Minio server basically exposes local storage using S3 protocol if you run:
`minio server /mnt/export`

Now you can access this storage from another client machine using `mc` or any S3 compatible clients.

Coming to your usecase, when you do:
On Server-1: ./minio server --address 192.168.1.24:9001 /home/shared/
(I am assuming that Server-1's IP is 192.168.1.24)

Now you can access Server-1's /home/shared from any other machine using S3 clients (like `mc`)

If you run minio server on Server-1 it has no connection/relation to Server-2's disks at all.

**Comment by akb2017** [comment]
Then if i want to store on server2 how to do that ? 
@krishnasrinivas

**Comment by harshavardhana** [comment]
> the command is ./minio server --address 192.168.1.25:9004 /home/shared/

Your bind IP should be local to the server `minio server` should be bound to local IP.  To access data from 192.168.1.25 you need to use tools like [mc](https://github.com/minio/mc)

First you need to decide where you are storing data and run minio server there.  If you want to store on server2 you need to run minio server on server2.

**Comment by akb2017** [comment]
Oh ok got it ..

**Comment by deekoder** [comment]
I'll go ahead and close this issue then. @akb2017 please reopen if you think its not solved your issue.
