### ISSUE TITLE
server: [startup] Startup message endpoints list is not sorted properly.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4099]
## Expected Behavior
Endpoints listed in the startup banner should be properly sorted based on last octet.

```
http://192.168.1.106:9000  http://127.0.0.1:9000  http://172.23.0.1:9000  http://172.19.0.1:9000  http://172.24.0.1:9000  http://172.20.0.1:9000  http://172.17.0.1:9000  http://172.21.0.1:9000  http://172.25.0.1:9000  http://172.22.0.1:9000  http://172.18.0.1:9000  http://172.26.0.1:9000  http://172.27.0.1:9000
```

## Current Behavior
Last octet based sorting is lost.

```
Endpoint:  http://127.0.0.1:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://172.21.0.1:9000  http://172.22.0.1:9000  http://172.23.0.1:9000  http://172.24.0.1:9000  http://172.25.0.1:9000  http://172.26.0.1:9000  http://172.27.0.1:9000  http://192.168.1.106:9000
```

## Possible Solution
Fix `net.go` 

## Steps to Reproduce (for bugs)

```
Endpoint:  http://127.0.0.1:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://172.21.0.1:9000  http://172.22.0.1:9000  http://172.23.0.1:9000  http://172.24.0.1:9000  http://172.25.0.1:9000  http://172.26.0.1:9000  http://172.27.0.1:9000  http://192.168.1.106:9000
```

127.0.0.1:9000 is a wrong ip to be preferred as the first entry.

## Context
Startup banners need to be consistent , this is a regression. 

## Your Environment
master branch de204a0a52e6b13fec2d25b73102239891e6de35

**Comment by deekoder** [comment]
how should the right order be?

**Comment by balamurugana** [comment]
> 127.0.0.1:9000 is a wrong ip to be preferred as the first entry.

Why is it wrong?

**Comment by harshavardhana** [comment]
> Why is it wrong?

First its a regression broke a functionality which was added previously with a specific reason and it was also a UI change which happened which we missed during the patch review.

There as cleaner comment in `interface-ips.go`  before the change which explains this. 
```
// [The logic to sort by last octet is implemented to
// prefer CIDRs with higher octects, this in-turn skips the
// localhost/loopback address to be not preferred as the
// first ip on the list. Subsequently this list helps us print
// a user friendly message with appropriate values].
```

When a user looks at the startup banner with values pre-filled for example in current master.

```
$ minio server ~/test/

Endpoint:  http://127.0.0.1:9000  http://192.168.1.106:9000
....
....
Browser Access:
   http://127.0.0.1:9000  http://192.168.1.106:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:9000 USWUXHGYZQYFYFFIT3RE MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03
```

A user generally just copy pastes these commands and expects it to work, since the CLI itself is longer and cryptic - we want to make it easy for the user to be able to just copy paste it across many systems and with localhost being there it doesn't work on remote machines. 

At the time i wanted to do full CIDR based sorting, but @abperiasamy suggested just looking at last octet is enough for the most use cases. 

Now look at the same output with the patch. 

```
$ minio server ~/test/

Endpoint:  http://192.168.1.106:9000  http://127.0.0.1:9000 
....
....
Browser Access:
   http://192.168.1.106:9000  http://127.0.0.1:9000 

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.106:9000 USWUXHGYZQYFYFFIT3RE MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03
```

Latter is the requirement.
