### ISSUE TITLE
Unable to run distributed minio

### ISSUE THREAD

**Issue by akb2017** [minio/minio#4104]
Here iam using 4 servers or nodes to run distributed minio ,Not able to run due to Unsupported backend format [fs] error ,I executed the command in all the nodes
The command is as follows -->
 ./minio server http://192.168.1.25/home/node1 http://192.168.1.24/home/node2 http://192.168.1.20/home/node3 http://192.168.1.22/home/node4

## Current Behavior
Getting error in all the nodes as follows -->
FATA[0021] Initializing object layer failed  cause=Unsupported backend format [fs] found source=[server-main.go:587:serverMain()]
## Your Environment
Here iam using 4 ubuntu machine as servers,All are locally connected
ports are opened in all the  servers

**Comment by harshavardhana** [comment]
> Here iam using 4 servers or nodes to run distributed minio ,Not able to run due to Unsupported backend format [fs] error ,I executed the command in all the nodes
> The command is as follows -->
> ./minio server http://192.168.1.25/home/node1 http://192.168.1.24/home/node2 http://192.168.1.20/home/node3 http://192.168.1.22/home/node4

You have to remove any files which are present from previous run. The error message indicates that you already ran "[fs]" server on this. 

Can you delete the files on "/home/node1/.minio.sys" and try again? @akb2017

**Comment by akb2017** [comment]
Ok i will try now

**Comment by akb2017** [comment]
I can run server now ..
Thank you so much @harshavardhana
