### ISSUE TITLE
lock instrumentation shouldn't return duration which can be computed from time of lock

### ISSUE THREAD

**Issue by krisis** [minio/minio#4110]
## Expected Behavior

Ref #4108 
>Lock APIs

  >  In the list api do we need options since and duration? Need more info.
    older-than : Specify time format with an example.

Lock instrumentation should return time since when the namespace lock is held alone. The time elapsed since can be derived.

## Current Behavior

We return both time since when the lock is held and the duration computed at the time of `List Locks` admin API call.

## Possible Solution

Return only the time since when the lock is held on Minio server.

## Steps to Reproduce (for bugs)

1. `mc admin lock list alias/bucket`
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment]
Fixed by #4111
