### ISSUE TITLE
ecosystem: Create Minio service broker for Cloud Foundry

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4112]
As per user `abhilash07` on [Slack Channel](https://minio.slackarchive.io/-/search-service%20broker/page-1), 

`as we know if we have to bind minio to cf apps bosh release is the first step, second is we have to bind minio to cf application by using service broker`

We need to explore and if required, implement the Cloud Foundry service broker API. 

## Expected Behavior
Create a Service Broker for Minio. We can try to follow the [Open Service Broker API](https://www.openservicebrokerapi.org/) which is compatible with Cloud Foundry, Kubernetes and more.  

Further documentation on Cloud Foundry deployment is available [here](https://docs.cloudfoundry.org/services/overview.html)

MySql broker example is available [here](https://github.com/cloudfoundry/cf-mysql-release)

## Current Behavior
Cloud Foundry service broker for Minio not available. 

## Context
This will allow users to deploy Minio seamlessly on Cloud Foundry

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by koolhead17** [comment]
This might be helpful https://github.com/deis/minio-broker

**Comment by deekoder** [comment]
need to discuss further with @abperiasamy

**Comment by deekoder** [comment]
Wait for input from them.

**Comment by sentientmonkey** [comment]
Any update on the status? Would love to see this happen.

**Comment by deekoder** [comment]
Closing as items are moved to minio/minio-boshrelease

**Comment by deekoder** [comment]
@sentientmonkey  we are doing it. But all cloudfoundry related issues are going to move to a separate repo. You will be able to see them there.

**Comment by sentientmonkey** [comment]
Thanks! 🤘

**Comment by deekoder** [comment]
@sentientmonkey  - We'd love it if you join us on our slack channel. We would love to ping you when we have the service broker available for testing.  https://slack.minio.io/
