### ISSUE TITLE
erasure: Create fuzz test for erasure coding library

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#4118]
The erasure coding library is the core of Minio's data distribution logic, The library https://github.com/klauspost/reedsolomon is being currently used for the purpose. Its critical that erasure coding library doesn't have parsing limitations for certain combination of data input. 

A upstream contribution with fuzz testing using https://github.com/dvyukov/go-fuzz is necessary to increase the confidence about the lib's parsing capability.

**Comment by harshavardhana** [comment]
// cc @fwessels - here for any comments on this.

**Comment by fwessels** [comment]
Nice tool, had not heard about it before.

However in our case, we are not "parsing" the incoming data in any way, but literally just treating it as an arbitrary array of bytes. Only border case that I could potentially see go wrong is that `len(input) != len(output)` (and then for a particular combination of data & parity size) but for that we could better test it in a large `for` loop...
