### ISSUE TITLE
nginx proxy cache seems to mess up headers

### ISSUE THREAD

**Issue by morph027** [minio/minio#4120]
I was just googling around and found this blog post: https://www.nginx.com/blog/enterprise-grade-cloud-storage-nginx-plus-minio/

Besides simple load balancing and TLS termination, I was trying to test/implement the caching feature. But when accessing the bucket with mc, an error appears: ```mc: <ERROR> Unable to initialize target `test/test`. Access Denied.```

Removing the ```proxy_cache minio_s3;``` makes it usable again. Will provide more output from minio server and nginx logs as soon as i'am back at work.

* **nginx config**

```
upstream minio_servers {
    server minio-server-1:9000;
    server minio-server-2:9000;
    server minio-server-3:9000;
    server minio-server-4:9000;
}

proxy_cache_path /var/cache/nginx/minio levels=1:2 keys_zone=minio_s3:10m max_size=10g inactive=60m use_temp_path=off;

server {
    listen 80 default_server;
    location / {
       proxy_cache minio_s3;
       proxy_pass http://minio_servers;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forward-Proto http;
    }
}
```

**Comment by deekoder** [comment]
@harshavardhana : Will this have to move to minio/mc issues

**Comment by harshavardhana** [comment]
> @harshavardhana : Will this have to move to minio/mc issues

No @deekoder this is server only issue, more so an interaction issue with nginx + minio -   We need to see what nginx does when headers are cached.

**Comment by morph027** [comment]
## List minio (works)

### mc command

```
$ mc ls minio/
[2017-04-14 09:53:17 CEST]     0B runners/
```

### nginx log

```
"GET / HTTP/1.1" 200 343 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET / HTTP/1.1" 200 343 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
```

## List bucket (fails)

### mc command

```
$ mc ls minio/runners
mc: <ERROR> Unable to initialize target `minio/runners`. Access Denied.
```

### nginx log

```
"GET /runners/?location= HTTP/1.1" 200 139 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"HEAD /runners/ HTTP/1.1" 403 25 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET / HTTP/1.1" 200 343 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"HEAD /runners/ HTTP/1.1" 403 25 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
```

### minio log

```
ERRO[0807] {"method":"GET","path":"/runners/","query":"","header":{"Authorization":["AWS4-HMAC-SHA256 Credential=xxx/20170414/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=808b1f80183f7fe3084f6ce4634361e16a107c705b24e7609f8e6fcef8afee8c"],"Connection":["close"],"Host":["minio-proxy:8080"],"User-Agent":["Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],"X-Amz-Date":["20170414T184835Z"],"X-Forward-Proto":["http"],"X-Real-Ip":["192.168.1.100"]}}  cause=Signature does not match source=[auth-handler.go:123:checkRequestAuthType()]
ERRO[0807] {"method":"GET","path":"/runners/","query":"","header":{"Authorization":["AWS4-HMAC-SHA256 Credential=xxx/20170414/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=808b1f80183f7fe3084f6ce4634361e16a107c705b24e7609f8e6fcef8afee8c"],"Connection":["close"],"Host":["minio-proxy:8080"],"User-Agent":["Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],"X-Amz-Date":["20170414T184835Z"],"X-Forward-Proto":["http"],"X-Real-Ip":["192.168.1.100"]}}  cause=Signature does not match source=[auth-handler.go:123:checkRequestAuthType()]
```

## List file inside bucket (works)

### mc command

```
$ mc ls minio/runners/IMG_20170312_125207.jpg
[2017-04-14 20:55:55 CEST] 5.2MiB IMG_20170312_125207.jpg
```

### nginx log

```
"GET /runners/?location= HTTP/1.1" 200 139 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
```

## Copy file from bucket (fails)

### mc command

```
$ mc cp minio/runners/IMG_20170312_125207.jpg .
mc: <ERROR> Failed to copy `http://minio-proxy:8080/runners/IMG_20170312_125207.jpg`. Insufficient permissions to access this file `http://minio-proxy:8080/runners/IMG_20170312_125207.jpg`
```

### nginx log

```
"GET /runners/?location= HTTP/1.1" 200 139 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"GET /runners/?delimiter=%2F&max-keys=1000&prefix=IMG_20170312_125207.jpg HTTP/1.1" 200 604 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
"HEAD /runners/IMG_20170312_125207.jpg HTTP/1.1" 403 25 "-" "Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z" "-"
```

### minio log

```
ERRO[1537] {"method":"GET","path":"/runners/IMG_20170312_125207.jpg","query":"","header":{"Authorization":["AWS4-HMAC-SHA256 Credential=xxx/20170414/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=878dc780f6099f36d6875c67eab4e71d3851058eadca45fcd7c95728a90a1d21"],"Connection":["close"],"Host":["minio-proxy:8080"],"User-Agent":["Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-03T18:35:01Z"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],"X-Amz-Date":["20170414T190045Z"],"X-Forward-Proto":["http"],"X-Real-Ip":["192.168.1.100"]}}  cause=Signature does not match source=[auth-handler.go:123:checkRequestAuthType()]
```

**Comment by harshavardhana** [comment]
Thanks @morph027 we will take a look.

**Comment by morph027** [comment]
Thanks! If you need more debug info, just let me know.

Meantime, i guess it's not really high priority...the nginx config from the docs does work :smile:

**Comment by morph027** [comment]
By the way, browser access itself works fine for all operations!

**Comment by krishnasrinivas** [comment]
nginx is removing the `Expect` header causing this problem.

**Comment by harshavardhana** [comment]
I guess using `mc` master would fix this problem we don't have Expect header anymore. But this will happen if other clients which use Expect header eg. boto3

**Comment by harshavardhana** [comment]
Actually the issue is deeper than that with proxy caching enabled there is an odd situation. With proxy

```
---------------------------
REQUEST : GET path:/testbucket/
Host: localhost
X-Amz-Date: 20170415T002022Z
X-Real-Ip: 127.0.0.1
X-Forward-Proto: http
Connection: close
User-Agent: Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-11T03:36:40Z
Authorization: AWS4-HMAC-SHA256 Credential=USWUXHGYZQYFYFFIT3RE/20170415/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=4f5ddce12b194f2ba900e90b089ba027ecbc146e19049b26f0362df659ea9794
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

INFO[0131] Round trip: http://localhost:8000/testbucket/, code: 403, duration: 754.146µs 

-----
RESPONSE STATUS: 403 Forbidden
Vary: Origin
X-Amz-Bucket-Region: us-east-1
Date: Sat, 15 Apr 2017 00:20:22 GMT
Server: Minio/DEVELOPMENT.2017-04-15T00-14-39Z (linux; amd64)
X-Amz-Request-Id: 14B56A33D46147B0
Accept-Ranges: bytes
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
--------------------------
``` 

Without proxy

```
---------------------------
REQUEST : GET path:/testbucket/?delimiter=%2F&max-keys=1000
Host: 192.168.1.106:9000
Accept-Encoding: gzip
User-Agent: Minio (linux; amd64) minio-go/2.0.4 mc/2017-04-11T03:36:40Z
Authorization: AWS4-HMAC-SHA256 Credential=USWUXHGYZQYFYFFIT3RE/20170415/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1d4f8d8d3e6cb06e5500a9f62424e322515dcfcf71da638d2c20d9d7cb67de66
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170415T002218Z

INFO[0247] Round trip: http://localhost:8000/testbucket/?delimiter=%2F&max-keys=1000, code: 200, duration: 1.051896ms 

-----
RESPONSE STATUS: 200 OK
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14B56A4ECE9B3640
Date: Sat, 15 Apr 2017 00:22:18 GMT
Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-04-15T00-14-39Z (linux; amd64)
Vary: Origin

--------------------------
```

The problem here if you can observe happens because the URL query params are filtered out and not sent to the server. Basically client used these query params to calculate signature so the signature error. 

Now it exposes a deeper problem not just that query params are lost, lets say we fixed signature mismatch somehow but we can't even list properly using ListObjects() API because the request has missing params like the prefix, marker etc. 

Investigating more if we can address it with nginx configuration.

**Comment by harshavardhana** [comment]
After exploring this for last two days, I am afraid to say that nginx seems to filter out query params no matter what which leads to issues with signature. Since all of S3 APIs usually have a query param in one way or the other and query params are much part of the signature calculation along with HTTP headers. Which makes it impossible for the nginx `proxy_cache` to work with Minio with all APIs which have query params. 

Unless there is a way to bypass query params somehow in their proxy_cache implementation, for which i don't see any documentation exists after various techniques.  It would seem that it is not possible.

**Comment by morph027** [comment]
Thanks for your effort anyway! As written above, this was just out of curiosity ;)

nginx without cache works flawlessly.

**Comment by iahmad-khan** [comment]
Hi,

Why is this closed? does mean we can't have caching for minio?

**Comment by harshavardhana** [comment]
@iahmad-khan it is closed because it's not MinIO issue

**Comment by PaulMatencio** [comment]
By default, Nginx is converting HEAD into GET. All you need is to disable this converion by setting proxy_cache_convert_head off

**Comment by kislik** [comment]
@PaulMatencio Can you please show the full working example stack. I mean your Nginx configuration with Minio. I'll be really appreciated! =)

**Comment by PaulMatencio** [comment]
Here is the s3 server configuration

server {
    listen 80 backlog=4096;
    server_name s3_test;
    status_zone s3_test;
    access_log  /var/log/nginx/upstream.log upstream ;
    location / {
       status_zone  s3_test  ;
       # make sure to pass the  Host to S3
       proxy_set_header Host $http_host;
       proxy_set_header  Range $slice_range;
       # Configure out caches
       proxy_cache S3-cache;
       # need to set proxy_buffering on in order to cache
       proxy_buffering on ;
       proxy_buffers 8 16k;
       proxy_buffer_size 16k;
       proxy_busy_buffers_size 32k;

       # Do not convert HEAD into GET
       proxy_cache_convert_head off;       

       # Pass along Authorization credentials to upstream S3
       proxy_set_header Authorization $http_authorization;

      # proxy_cache_purge $purge_method;

       proxy_cache_bypass $http_cachepurge;

       # Since head conversion is disabled, the request_method is included in the proxy_cache_key
       proxy_cache_key  "$scheme$proxy_host$request_method$request_uri$is_args$args";

      # GET and HEAD are cached by default
       proxy_cache_methods GET HEAD;

      # Cache all 200 OK's for 24 hours
       proxy_cache_valid  200 24h;

      # Use stale cache file in all errors from upstream if we can
       proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;

      # Lock the cache so that only one request can populate it at a time
       proxy_cache_lock    on;
       proxy_cache_revalidate on;

       add_header             Cache-Control max-age=31536000;
      # add_header             Request "$request_method $uri $is_args $args";

      # Set back a nice HTTP Header to indicate what the cache status was
       add_header             X-Cache-Status $upstream_cache_status;

       proxy_pass http://S3-test;

    }
}
