### ISSUE TITLE
docs.minio.io logo is pixelated 

### ISSUE THREAD

**Issue by rushenn** [minio/minio#4121]
Current resized PNG logo is pixelated in low PPI displays.

![logo-png](https://cloud.githubusercontent.com/assets/13393018/25045935/4d253480-214c-11e7-9bd4-e537252b5a38.png)

## Possible Solution
Use SVG instead of PNG or any other image formats.

## Steps to Reproduce (for bugs)
Image attached.

## Your Environment
* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment]
@deekoder is this relevant for `minio/minio` ?  I see these images are not served from minio server repo.

**Comment by deekoder** [comment]
Closing this. And will open in the docs repo.
