### ISSUE TITLE
Minio server cant read Windows 2016 deduplicated files 

### ISSUE THREAD

**Issue by JamshaidF** [minio/minio#4122]
After uploading a file to minio server running on Windows 2016, Everything seems fine and  file is accessible fine using mc client. But as soon as scheduled deduplication runs on the server and  the file's "size on disk" changes to Zero in file properties, minio client cant retrive/list the file. And with every attempt to retrive/list file using mc client, i get below error on  minio server console 

time="2017-04-14T08:38:44-07:00" level=error msg="Unable to stat path d:\\data2/xxxxxx/c4/bb/c4bbf66cbdd866476f0247059f220667/c4bbf66cbdd866476f0247059f220667.ntfsclone.1492098076" cause="readlink \\\\?\\d:\\data2\\xxxxxx\\c4\\bb\\c4bbf66cbdd866476f0247059f220667\\c4bbf66cbdd866476f0247059f220667.ntfsclone.1492098076: The system cannot find the file specified." source="[posix-list-dir-others.go:60:readDir()]"

## Expected Behavior

Since deduplicated file(s) are present in data folders so they must be accessible as any other file(s) 

## Current Behavior

mc client dont list the deduplicated file(s) and server console print above mentioned error

## Steps to Reproduce (for bugs)

1. Setup a windows 2016 server with deduplicated volume d:\\
2.  Start minio on windows 2016 server as "minio.exe server d:\\data2
3.  From a linux server using linux mc client create a bucket
4. Upload a large file to minio server
(NOTE: several copies of same file must be present on the server with different names so that windows deduplication can really deduplicate it)
5. Varify... the file is accessable using mc client
6. Wait untill windows run and finish its scheduled deduplication process or start the deduplication manually and wait for it to finish
7. Try to access same file using mc client and file wont list. And on server you will see above mentioned error on minio console

## Context

Trying to setup minio server on a windows 2016 deduplicated volume

## Your Environment

* Version used:
2017-03-16T21:50:32Z

* Environment name and version (e.g. nginx 1.9.1):
minio.exe for windows 64 bit
* Server type and version:
Windows 64 bit
* Operating System and version:
Windows Server 2016  (Build 14393)
* Link to your project:

**Comment by vadmeste** [comment]
Looks like it is a golang "bug" which is not fixed yet https://github.com/golang/go/issues/10935.

**Comment by deekoder** [comment]
@vadmeste is this golang bug in minio or outside of minio?

**Comment by JamshaidF** [comment]
Incase if you need a test server, i can provide access to a windows 2016 server with deduplication setup. Just let me know how can i send you ip and login information.

**Comment by vadmeste** [comment]
@deekoder, this is outside of Minio.

@JamshaidF, can you join us in https://minio.slack.com ?

**Comment by deekoder** [comment]
@vadmeste if there is data loss even if its not related to minio, let us document this.

**Comment by harshavardhana** [comment]
> @vadmeste if there is data loss even if its not related to minio, let us document this.

There is no data loss, just that they are not accessible. But we can fix this bug without using Go and not wait for it. Since we already use `sys/unix` package dependency it is possible to write a higher level function for this and fix it properly.

**Comment by JamshaidF** [comment]
@vadmeste it need a minio.io email address to join https://minio.slack.com ? how can i join it ?
you can mail at jam***@serverpoint.com

and yes there is no data loss, just it is not accessable through minio server

**Comment by harshavardhana** [comment]
> @vadmeste it need a minio.io email address to join https://minio.slack.com ? how can i join it ?
> you can mail at jamshaid@serverpoint.com

You don't need minio email you should just click this https://slack.minio.io and get yourself signed up.

**Comment by JamshaidF** [comment]
thanks @harshavardhana . Joined

**Comment by deekoder** [comment]
lowering pri since the issue is caused by something outside of minio.

**Comment by harshavardhana** [comment]
https://go-review.googlesource.com/#/c/41504/ here is the PR.

**Comment by harshavardhana** [comment]
> https://go-review.googlesource.com/#/c/41504/ here is the PR.

The following PR was abandoned after talking upstream, and is being fixed comprehensively here - https://go-review.googlesource.com/#/c/41834/

**Comment by harshavardhana** [comment]
@JamshaidF would it be possible for you to test this PR? https://github.com/harshavardhana/minio/commit/3ba2326a7c0b66a475318e8000d802a176158177

**Comment by JamshaidF** [comment]
Thanks @harshavardhana , i will test it today*

**Comment by JamshaidF** [comment]
I can confirm, the PR #4203 does fix the issue.

Steps for testing
1. First tested with latest Windows binary (minio.exe 2017-04-29 00:46). And issue was there.
2. Setup GoLang environment, Fetched minio  and the PR #4203 and started minio under GoLang
3. All deduplicated files in the bucket are accessible by mc client. No error on the server console.

Great job @harshavardhana 

PS:  Not much important but just in case , cant start upstream minio.exe with same data directories now, it says configuration is upgraded to version 15 and this version of minio needed version 14

**Comment by harshavardhana** [comment]
You can change the version number in the config.json present under `.minio/config.json` under your home dir. I should have suggested that you run ` --config-dir`  to avoid migrating the current config.

**Comment by harshavardhana** [comment]
Thanks for confirming that it fixes the issue.
