### ISSUE TITLE
Explore support for minio gateway to HDFS backend

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4124]
* We need to find the right go library to do this.
 * CLI : ` minio gateway hdfs ENDPOINT` 
 * access and secret key passed as env variables

Please put together a proposal doc for review.

**Comment by vadmeste** [comment]
This following link contains my exploration result:

https://docs.google.com/document/d/19A8oZnUJcysBBowZ3ioOUKZgI2Ka_KlSh6SV5MElj7s/edit

Please, review especially the multipart support, not native but there is a way to achieve it.

**Comment by deekoder** [comment]
will do @vadmeste

**Comment by deekoder** [comment]
We will explore this if there is clear need for this feature. Please reactivate if you think this support needs to be there. Closing now.

**Comment by ckesselh** [comment]
@deekoder my company's interested in funding the development of this gateway. Who's the right person to talk to about this, then?

**Comment by harshavardhana** [comment]
> @deekoder my company's interested in funding the development of this gateway. Who's the right person to talk to about this, then?

hadoop already has s3a plugin, can you explain a bit more about how `minio gateway` will help?

**Comment by ckesselh** [comment]
My client already has a Hortonworks/Hadoop stack which they currently host on-premise. Now they want an object storage to use for uploading files from/downloading files to some of their Angular front-ends and for exchanging them with outside parties (which don't have access to the environment running Hadoop). 

They prefer to go with Minio instead of WebHFDS because the former provides them with an S3 compatible API.

**Comment by harshavardhana** [comment]
> My client already has a Hortonworks/Hadoop stack which they currently host on-premise. Now they want an object storage to use for uploading files from/downloading files to some of their Angular front-ends and for exchanging them with outside parties (which don't have access to the environment running Hadoop).
> 

We will get back to you on this topic @ckesselh - thanks for providing us the details.

**Comment by devrimbaris** [comment]
> hadoop already has s3a plugin, can you explain a bit more about how `minio gateway` will help?

@harshavardhana I guess that is for accessing s3 compatible storages , but not for providing a S3a compatible storage interface to HDFS.

**Comment by harshavardhana** [comment]
> @harshavardhana I guess that is for accessing s3 compatible storages , but not for providing a S3a compatible storage interface to HDFS.

@devrimbaris we are not planning to do this, this has been dropped since some time.

**Comment by xor007** [comment]
Given HDFS's presence (and inertia) in datacenters around the world, I struggle to understand why this feature request was dropped. It is near impossible in some environment to initiate changes in storage technology but people will not need to approve an "S3 Gateway to HDFS". Note: I foresee this to be widly popular.

**Comment by adiospeds** [comment]
Even Quobyte supports this

**Comment by harshavardhana** [comment]
Fixed and released #7440
