### ISSUE TITLE
gateway: [s3] Listing has inconsistent output

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4125]
## Expected Behavior
Listing output should be consistent with gateway server.

## Current Behavior
```
$ mc ls play/testbucket2 
[2017-04-14 15:58:19 PDT]     0B apt/
[2017-04-14 15:58:19 PDT]     0B fsck/
$ mc ls mys3/testbucket2
[0000-12-31 16:07:02 LMT]     0B 
```

Prefix based listing is not working. 

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
Just use `mc ls` on any buckets use `mc ls play/<bucketname>`  and `mc ls mys3/<buckename>` outputs are different. 

## Context
S3 compatibility errors.

## Your Environment
Download binary: http://minio-download.s3.amazonaws.com/minio
and use the latest `mc` master.

**Comment by nl5887** [comment]
Duplicate #4129, fixed in latest PR.

**Comment by koolhead17** [comment]
Just tested, can confirm this is fixed. 😄

**Comment by harshavardhana** [comment]
Fixed in latest update to gateway PR.
