### ISSUE TITLE
gateway: [s3] Conflicting policy should result in consistent errors

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4127]
## Expected Behavior
```
mc policy download play/testbucket
mc: <ERROR> Unable to set policy `download` for `play/testbucket`. New bucket policy conflicts with an existing policy. Please try again with new prefix.
```

## Current Behavior
```
mc policy download mys3/testbucket
mc: <ERROR> Unable to set policy `download` for `mys3/testbucket`. 
```

## Possible Solution
Policy conflicts error is not consistent with what Minio server would have sent.

## Steps to Reproduce (for bugs)
Use the latest `mc` master, attempt to cause a policy conflict.

## Context
S3 compatibility errors.

## Your Environment
Download binary: http://minio-download.s3.amazonaws.com/minio and use the latest mc master.

**Comment by harshavardhana** [comment]
Can reproduce this issue with the latest PR update.

```
$ mc policy download gateway/testbucket
Access permission for `gateway/testbucket` is set to `download`
$ mc policy download gateway/testbucket/test
mc: <ERROR> Unable to set policy `download` for `gateway/testbucket/test`. 
$ 
```

**Comment by krishnasrinivas** [comment]
Can this issue be closed? because on AWS-S3:
```
krishna@escape:~$ mc policy download s3/krisbuck/a/
Access permission for `s3/krisbuck/a/` is set to `download`
krishna@escape:~$ mc policy download s3/krisbuck/
Access permission for `s3/krisbuck/` is set to `download`
krishna@escape:~$ 
```

this is allowed, since gateway will just pass the client supplied policy JSON to the backend it is up to the backend to validate it. i.e AWS S3 will not complain but minio server will. Hence the "Expected Behavior" will depend on the gateway's backend.

**Comment by harshavardhana** [comment]
The error passed back to the client should be consistent. Gateway should be a passthrough for the errors coming in from the server.

**Comment by harshavardhana** [comment]
This is fixed properly in https://github.com/dutchcoders/minio/commit/4cec11959b8f5c490bf91bb2285a3581882b37ee latest. Closing.
