### ISSUE TITLE
Trying to heal a disk with distributed Erasure Code

### ISSUE THREAD

**Issue by rusher81572** [minio/minio#4132]
Hello, I wanted to help out and test the heal command on my production setup. I have a 6 node Raspberry Pi Cluster. Minio is running in a docker container on each host with 1 disk per node. 

I compiled the latest MC and MINIO server today from Git.

I started with 6 nodes then took two nodes offline and copied a lot of data to the nodes.  The cluster is working fine with 4/6 disks. Today. I added one of the downed nodes back to the cluster with a larger disk and tried to heal the disk and it fails

```
/mc admin heal myminio --json --debug

mc: <DEBUG> POST /?heal= HTTP/1.1
Host: 169.254.206.217:8001
User-Agent: Minio (linux; arm) madmin-go/0.0.1 mc/DEVELOPMENT.GOGET
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170415/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-operation, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170415T032758Z
X-Minio-Operation: format
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Sat, 15 Apr 2017 03:28:01 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; arm)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14B574713B72F657

102
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  3.007484862s

{"status":"error","error":{"message":"Cannot heal the disks.","cause":{"message":"We encountered an internal error, please try again.","error":{"Code":"InternalError","Message":"We encountered an internal error, please try again.","BucketName":"","Key":"","RequestID":"3L137","HostID":"3L137","Region":""}},"type":"fatal","trace":[{"line":408,"file":"admin-heal.go","func":"cmd.mainAdminHeal"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"2.7MB","mem.heap.used":"1.0MB","mem.total":"23MB","mem.used":"1.0MB"}}}
```

After adding the node back to the cluster, I still see the following on the nodes:
```
Drive Capacity: 26 GiB Free, 58 GiB Total
Status:         4 Online, 2 Offline. We can withstand [1] more drive failure(s).
```

Since I added the node back, it should say 5 online right? Does a heal have to happen first? Problem is that I can not heal =( I can access my files and write data when connecting to the web console on the added host.

**Comment by krisis** [comment]
@rusher81572, this is a known limitation. To heal the format of any unformatted disks in a XL (distributed or single node) setup, we require all the nodes to be up. Let me investigate further to see if this restriction can be removed.

@harshavardhana Do you have context on why we have this restriction in `healFormatXL`?

**Comment by rusher81572** [comment]
I added all 6 nodes back and I get the following error:
```
time="2017-04-15T07:59:19Z" level=fatal msg="Initializing object layer failed" cause="Inconsistent JBOD found" source="[server-main.go:2Migration from version ‘17’ to ‘18’ completed successfully.

time="2017-04-15T08:00:33Z" level=fatal msg="Initializing object layer failed" cause="Inconsistent JBOD found" source="[server-main.go:2
time="2017-04-15T08:01:03Z" level=fatal msg="Initializing object layer failed" cause="Inconsistent JBOD found" source="[server-main.go:2root@rpi-1:/mnt/.minio#
```

**Comment by rusher81572** [comment]
I managed to get all the nodes online by deleting .minio.sys and restarting minio

```
Version : DEVELOPMENT.GOGET
   Uptime : 19 minutes 19 seconds
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 226KiB, Outgoing 61KiB
  Storage : Total 88GiB, Free 43GiB, Online Disks: 6, Offline Disks: 0
```

I now did a heal on the two new nodes and I do not see any data after heal is run:
````
4.0K    /miniodata/mysql
4.0K    /miniodata/.minio.sys/tmp
4.0K    /miniodata/.minio.sys/multipart
16K     /miniodata/.minio.sys
4.0K    /miniodata/nextcloud
4.0K    /miniodata/cloudexplorer
4.0K    /miniodata/testbucket
4.0K    /miniodata/music
4.0K    /miniodata/picluster
4.0K    /miniodata/html
48K     /miniodata/
```

**Comment by harshavardhana** [comment]
did you just run `mc admin heal myminio --json --debug` ?  perhaps you might have to do `mc admin heal --recursive --json --debug myminio/<bucketname>` 

@krisis can confirm if the syntax is correct. or you can take a look at the `mc admin heal` help examples.

**Comment by rusher81572** [comment]
That is what I was thinking. I did:

```
root@rpi-2:/minio# ./mc admin heal --recursive myminio/html
mc: <ERROR> minio cannot be healed until quorum is available.
```

All disks are online though:
```
 Storage : Total 88GiB, Free 43GiB, Online Disks: 6, Offline Disks: 0
```

**Comment by rusher81572** [comment]
Some data did get copied I noticed with --recursive --json --debug. Without it, nothing got copied and you get the "mc: <ERROR> minio cannot be healed until quorum is available." error

```
52K     /miniodata/mysql/ResumeofPhillipTribble.pdf
56K     /miniodata/mysql
47M     /miniodata/.minio.sys/tmp/d60f98bb-c4bf-4fbd-b0da-9053a27d3f42
47M     /miniodata/.minio.sys/tmp
4.0K    /miniodata/.minio.sys/multipart
47M     /miniodata/.minio.sys
4.0K    /miniodata/nextcloud
4.0K    /miniodata/cloudexplorer
4.0K    /miniodata/testbucket
4.0K    /miniodata/music
4.0K    /miniodata/picluster
56M     /miniodata/html/www-04-05-17.tar.gz
56M     /miniodata/html
102M    /miniodata/
```

**Comment by rusher81572** [comment]
Long story short, something is likely wrong with MC that causes it to error out when  --json --debug is not used

**Comment by rusher81572** [comment]
Some errors noticed during heal:
```
c: <DEBUG> POST /?bucket=music&heal=&object=Music%2FAmazon%20Music%2FBABYMETAL%2FBABYMETAL%2F01-01-%20Babymetal%20Death.mp3 HTTP/1.1
Host: linux-toys.com:8000
User-Agent: Minio (linux; arm) madmin-go/0.0.1 mc/DEVELOPMENT.GOGET
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170415/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-operation, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170415T084503Z
X-Minio-Operation: object
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Sat, 15 Apr 2017 08:45:15 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; arm)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14B585C0ED0F290A

dc
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  11.215237957s

{"status":"error","error":{"message":"Cannot repair object: `Music/Amazon Music/BABYMETAL/BABYMETAL/01-01- Babymetal Death.mp3`","cause":{"message":"Access Denied.","error":{"Code":"AccessDenied","Message":"Access Denied.","BucketName":"","Key":"","RequestID":"3L137","HostID":"3L137","Region":""}},"type":"error","trace":[{"line":240,"file":"admin-heal.go","func":"cmd.healObjects"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"5.7MB","mem.heap.used":"3.2MB","mem.total":"26MB","mem.used":"3.2MB"}}}
```
Lot's of files have access denied.

**Comment by vadmeste** [comment]
>  Do you have context on why we have this restriction in healFormatXL?

@krisis, If we want to format one fresh disk, and there is another disk offline, the JBOD list of the offline disk will not get updated, and that disk will be "unusable" when it will come back.

**Comment by rusher81572** [comment]
I can not heal this bucket due to the following error that always happens:

```
{"status":"error","error":{"message":"Cannot heal bucket.","cause":{"message":"Post http://192.168.0.101:8001/?bucket=nextcloud\u0026heal=: net/http: timeout awaiting response headers","error":{"Op":"Post","URL":"http://192.168.0.101:8001/?bucket=nextcloud\u0026heal=","Err":{}}},"type":"fatal","trace":[{"line":414,"file":"admin-heal.go","func":"cmd.mainAdminHeal"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"1.6MB","mem.heap.used":"888kB","mem.total":"20MB","mem.used":"888kB"}}}
```

```
{"status":"error","error":{"message":"Cannot heal bucket.","cause":{"message":"Post http://linux-toys.com:8000/?bucket=nextcloud\u0026heal=: read tcp 192.168.0.101:37736-\u003e71.202.156.167:8000: read: connection reset by peer","error":{"Op":"Post","URL":"http://linux-toys.com:8000/?bucket=nextcloud\u0026heal=","Err":{"Op":"read","Net":"tcp","Source":{"IP":"192.168.0.101","Port":37736,"Zone":""},"Addr":{"IP":"71.202.156.167","Port":8000,"Zone":""},"Err":{"Syscall":"read","Err":104}}}},"type":"fatal","trace":[{"line":414,"file":"admin-heal.go","func":"cmd.mainAdminHeal"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"1.6MB","mem.heap.used":"913kB","mem.total":"21MB","mem.used":"913kB"}}}
```

**Comment by vadmeste** [comment]
> I can not heal this bucket due to the following error that always happens:
> 
> {"status":"error","error":{"message":"Cannot heal bucket.","cause":{"message":"Post http://192.168.0.101:8001/?bucket=nextcloud\u0026heal=: net/http: timeout awaiting response headers","error":{"Op":"Post","URL":"http://192.168.0.101:8001/?bucket=nextcloud\u0026heal=","Err":{}}},"type":"fatal","trace":[{"line":414,"file":"admin-heal.go","func":"cmd.mainAdminHeal"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"1.6MB","mem.heap.used":"888kB","mem.total":"20MB","mem.used":"888kB"}}}
> {"status":"error","error":{"message":"Cannot heal bucket.","cause":{"message":"Post http://linux-toys.com:8000/?bucket=nextcloud\u0026heal=: read tcp 192.168.0.101:37736-\u003e71.202.156.167:8000: read: connection reset by peer","error":{"Op":"Post","URL":"http://linux-toys.com:8000/?bucket=nextcloud\u0026heal=","Err":{"Op":"read","Net":"tcp","Source":{"IP":"192.168.0.101","Port":37736,"Zone":""},"Addr":{"IP":"71.202.156.167","Port":8000,"Zone":""},"Err":{"Syscall":"read","Err":104}}}},"type":"fatal","trace":[{"line":414,"file":"admin-heal.go","func":"cmd.mainAdminHeal"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"1.6MB","mem.heap.used":"913kB","mem.total":"21MB","mem.used":"913kB"}}}

@rusher81572, this simply indicates network timeout error

**Comment by vadmeste** [comment]
@rusher81572 Access denied issue is weird, do you still have this bug? are you using a reverse proxy ?

**Comment by rusher81572** [comment]
@vadmeste Should I be doing the heal directly to the node with mc  or through the reverse proxy with Nginx? I am having issues with both methods per the outputs above

**Comment by rusher81572** [comment]
Connecting directly
```
{"status":"error","error":{"message":"Cannot list objects to be healed.","cause":{"message":"Get http://192.168.0.101:8001/?bucket=nextcloud\u0026delimiter=\u0026heal=\u0026marker=\u0026max-key=1000\u0026prefix=: net/http: timeout awaiting response headers","error":{"Op":"Get","URL":"http://192.168.0.101:8001/?bucket=nextcloud\u0026delimiter=\u0026heal=\u0026marker=\u0026max-key=1000\u0026prefix=","Err":{}}},"type":"error","trace":[{"line":222,"file":"admin-heal.go","func":"cmd.healObjects"}],"sysinfo":{"host.arch":"arm","host.cpus":"4","host.lang":"go1.7.5","host.name":"rpi-1","host.os":"linux","mem.heap.total":"2.7MB","mem.heap.used":"1.0MB","mem.total":"22MB","mem.used":"1.0MB"}}}
```

**Comment by vadmeste** [comment]
Looks like the reason is that healing naturally taking time (probably because it is RPI + ARM is slow), and mc client doesn't wait that long. We need to consider this case.

**Comment by harshavardhana** [comment]
> Looks like the reason is that healing naturally taking time (probably because it is RPI + ARM is slow), and mc client doesn't wait that long. We need to consider this case.

We should bring in the concept of sessions for `mc admin heal` just like `mc cp` - will confirm with @abperiasamy as well .  But i think doing this will help to resume healing from where it left off etc.

**Comment by rusher81572** [comment]
This workaround is now copying data to the two nodes. This will help me for now to protect my data

```
mc ls -r myminio/ | awk '{ for(i=5;i<=NF;++i) printf("%s ",  $i) ; print "" }' | sed 's# $##g' | sed 's# #\\ #g' | xargs -I{} mc --debug admin heal myminio/{}
```

Thanks @vadmeste

**Comment by rusher81572** [comment]
@vadmeste  I ru  the command twice and here is the number of files in the /miniodata directory on each node: 

find /miniodata -type f | wc -l
```
Node:rpi-1

4390

Node:rpi-2

4392

Node:rpi-4

14613

Node:rpi-6

14624

Node:rpi-3

14601

```

Shouldn't  the number of files be the same or more closer together on all the nodes after a repair?

**Comment by vadmeste** [comment]
@rusher81572, `find /miniodata -type f | grep -v .minio.sys | wc -l` is more accurate.

**Comment by vadmeste** [comment]
I was thinking about sending whitespaces as S3 sometimes does for long operations. However, this means that we have to send headers first. 

As a solution, we can let fast checks (like arguments validation) returning error headers, but when real work starts (like listing heal objects or healing them), we should return http 200. We can always add Error field to the result. So the returned xml tree structure  will be the same for all cases.

What do you think @harshavardhana, @krisis ?

**Comment by harshavardhana** [comment]
Yes that is how it should be done to keep the connection active like how listen bucket notification works.

**Comment by rusher81572** [comment]
Is heal working correctly since there is a large disparity in number of files on each node?

**Comment by vadmeste** [comment]
> Is heal working correctly since there is a large disparity in number of files on each node?

We have a bug when healing takes too much time (Looks like RPI + ARM is slow in your case). I need to discuss the issue with the team first before sending a PR.

**Comment by vadmeste** [comment]
ETA: 16 Apr

**Comment by harshavardhana** [comment]
Moving this issue as blocked pending discussion on the final design to fix healing API.

**Comment by miketonks** [comment]
What's the status on this?  Is healing API now stable?

**Comment by donatello** [comment]
@miketonks The new API is a work in progress: https://github.com/minio/minio/pull/4826 and https://github.com/minio/mc/pull/2239 - however, please let us know if you are running into any issues with the existing APIs.

**Comment by kannappanr** [comment]
https://github.com/minio/minio/pull/5160 handles this issue. Closing this issue, Please follow that PR for progress.
