### ISSUE TITLE
heal: mc healing standalone erasure returns wrong message

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4134]
## Expected Behavior
mc returns object healed

## Current Behavior
mc returns object is healed on 1 disks while 1 disks were offline

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. `minio server /tmp/xl{1..4}`
2.  `mc mb myminio/testbucket`
3.  `mc cp file myminio/testbucket`
4.  `rm -r /tmp/xl1/testbucket/file`
5. `mc admin heal myminio/testbuckett/file`

## Context
Testing

## Your Environment
All

last master (3032f0f505437c2f631e304cd64a7c1ed7a3479a)

**Comment by krisis** [comment]
The issue isn't reproducible. @vadmeste, could you close this issue if you don't see it occur with some of the recent changes in `mc`?

**Comment by vadmeste** [comment]
> The issue isn't reproducible. @vadmeste, could you close this issue if you don't see it occur with some of the recent changes in mc?

I also don't see the bug anymore. I am going to close this issue.
