### ISSUE TITLE
How to backup minio - data files?

### ISSUE THREAD

**Issue by akb2017** [minio/minio#4135]
My question is how to backup minio data?
In the worst scenario if i lost all the data in all the servers how do i recover it?
Should i take backup manually or is there any other solution for that ?

**Comment by harshavardhana** [comment]
There some tools which we recommend such as

- Restic https://docs.minio.io/docs/restic-with-minio
- Rclone https://docs.minio.io/docs/rclone-with-minio-server
- Cloudberry Backup “Setup an automated data backup system with Minio and CloudBerry” @tiwari_nitish https://blog.minio.io/setup-an-automated-data-backup-system-with-minio-and-cloudberry-cc8dc7f178b9 and https://www.cloudberrylab.com/solutions/minio

**Comment by akb2017** [comment]
What about distributed minio how can i take backup ?In the same way or is there any different approach?

**Comment by harshavardhana** [comment]
Distributed Minio is no different those articles apply to distributed Minio as well.

**Comment by akb2017** [comment]
but for backup purpose it needs to create one more minio server right?

**Comment by harshavardhana** [comment]
> but for backup purpose it needs to create one more minio server right?

It is upto you it could be another NAS device, Minio Server or even Amazon S3.

**Comment by krishnasrinivas** [comment]
@akb2017 you can use `mc mirror` as well and do continuous backup:

https://docs.minio.io/docs/minio-client-complete-guide#mirror

```
mc mirror -w src dst
```

**Comment by akb2017** [comment]
But in order to backup the distributed minio it requires to backup the data from all the servers right? Is there any easy way to do it?

**Comment by krishnasrinivas** [comment]
`mc` works on top of S3, so you should not try to backup from the backend. `mc` uses S3 protocol for upload/download from minio server.

**Comment by akb2017** [comment]
OK thank you

**Comment by zqkou** [comment]
@harshavardhana 
One of your recommendation is Restic, which I took a look is great backup/restore tool. But I only see articles talk about how to backup data TO minio. I didn't see how to backup data FROM minio. Could you please share some thoughts on this?

**Comment by GabrielDumbrava** [comment]
[Handybackup](https://www.handybackup.net/minio-backup.shtml) can also backup from minio, but also [rclone](https://docs.min.io/docs/rclone-with-minio-server.html) might do the trick.

You may still want to run minio in [distributed mode](https://docs.min.io/docs/distributed-minio-quickstart-guide.html) so that your data is being written in more than one node at the same time.

**Comment by ckt114** [comment]
I’m a little confused on all these tools if someone can please explain. I have a minio cluster that I want to backup its volumes into an NFS. All these tools documentation is about syncing a directory to a bucket instead of a bucket out into a directory. Am I missing something? Thanks.

**Comment by ZVilusinsky** [comment]
> I’m a little confused on all these tools if someone can please explain. I have a minio cluster that I want to backup its volumes into an NFS. All these tools documentation is about syncing a directory to a bucket instead of a bucket out into a directory. Am I missing something? Thanks.

Just backup the drive/folder where you store minio data. At least that is our current solution as I did not find any info on dedicated minio backup and replacing the current version with a backup works.

**Comment by l0nax** [comment]
> Just backup the drive/folder where you store minio data. At least that is our current solution as I did not find any info on dedicated minio backup and replacing the current version with a backup works.

But does MinIO _lock_ the repository to prevent data loss.
I mean what is if currently a backup is created and at the same time some data changes on our MinIO-Server?
Does this destroy the data? @harshavardhana @krishnasrinivas

**Comment by krishnasrinivas** [comment]
@l0nax `mc mirror src dst` computes a diff of files between `src` and `dst` and starts copying files one by one. If you try to overwrite a file in `src` that is being copied, the overwrite gets blocked till the file is copied as we hold a lock.

**Comment by phucduong86** [comment]
> I have a minio cluster that I want to backup its volumes into an NFS. All these tools documentation is about syncing a directory to a bucket instead of a bucket out into a directory. Am I missing something? Thanks.

I agree that they are lacking in example.
When you reverse the order of your arguments it would copy the files from the bucket to local.
Here's an example of the command I use:
```
mc mirror --remove --preserve $MINIO_ENV/<bucket> $BACKUPS_DIR/$BACKUP_NAME
```
Where:
- **$MINIO_ENV** is your Min.IO remote host (eg. 'myminio')
- **$BACKUPS_DIR/$BACKUP_NAME** is the absolute path to your local folder

**Comment by satyamuralidhar** [comment]
ERROR: 2020/07/10 16:15:05.924450 Finish LSN of backup base_000000010000000000000005 greater than current LSN
