### ISSUE TITLE
No way to access uploaded metadata in fput_object from python api.

### ISSUE THREAD

**Issue by funnydevnull** [minio/minio#4136]
The python API allows you to upload metadata as a dict using the fput_object call but there doesn't seem to be a way to access it afterwards.

## Expected Behavior
I discussed this with @harshavardhana on slack and his suggestion was including it in the response object to a stat call and also fget_object.

## Current Behavior
Currently there does not seem to be a way to access this metadata via the python API once its been uploaded.

**Comment by harshavardhana** [comment]
This PR in minio-py should fix the problem - https://github.com/minio/minio-py/pull/505

**Comment by tarunmudgal** [comment]
when this fix will be available as I can't see this fix on minio==3.0.3
