### ISSUE TITLE
Create a thumbnailing service on minio server

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4141]
- We need this for the Minio Browser. 
- Can start with providing this for img & video files.

**Comment by cfehring** [comment]
Check out https://github.com/h2non/imaginary

**Comment by deekoder** [comment]
On demand or store thumbnails somewhere.  Start with images. Also explore nginx modules that can do that.

**Comment by deekoder** [comment]
marking this unblocked since we have clarity for first iteration.

**Comment by donatello** [comment]
@deekoder This should be in the UX and Admin API milestone.

**Comment by deekoder** [comment]
We will work on this in the future and build on what @brendanashworth  completed.

**Comment by kannappanr** [comment]
Do not have the bandwidth to work on this right now. Will close this now and re-open it when we get some bandwidth to do this.
