### ISSUE TITLE
gateway: bucket notification related test fail. 

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#4149]
## Expected Behavior

Bucket notifications to work.

## Current Behavior
bucket notification related test fail.

## Possible Solution
not sure.

## Steps to Reproduce (for bugs)

1. Run gateway using [instructions](https://gist.github.com/koolhead17/75290e448a2487477c7de8bf1ce06d11) 
2. Run mint using [instructions](https://github.com/minio/mint/blob/master/README.md)

## Context
Testing gateway.

## Your Environment

* Environment name and version : Minio m2 server

**Comment by krishnasrinivas** [comment]
same as https://github.com/minio/minio/issues/4165

**Comment by harshavardhana** [comment]
Closing this we have decided to not do bucket notifications on gateway.
