### ISSUE TITLE
How to run minio as Daemon process?

### ISSUE THREAD

**Issue by akb2017** [minio/minio#4155]
I want to run minio as Daemon process or to run in background ..How to run minio as Daemon process in ubuntu without root access?

**Comment by harshavardhana** [comment]
Please read this https://github.com/minio/minio-service/tree/master/linux-systemd @akb2017 and let us know how it goes.

**Comment by akb2017** [comment]
But that one requires root access right? I want to run this without root access

**Comment by harshavardhana** [comment]
> But that one requires root access right? I want to run this without root access

It doesn't require root access.. you can configure the system daemon to run as a normal user.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-service/tree/master/linux-systemd#note - read the Note here. First you need to configure the service as root and then subsequently make a proper user without shell to run the service.

**Comment by akb2017** [comment]
Ok i will try it now

**Comment by akb2017** [comment]
This one working fine for running single instance minio ..But getting error when i tried as cluster
Error -->

Starting Minio...
Started Minio.
minio.service: Main process exited, code=exited, status=1/FAILURE
 minio.service: Unit entered failed state.
minio.service: Failed with result 'exit-code'.

**Comment by harshavardhana** [comment]
// cc @hackintoshrao can you check?

**Comment by hackintoshrao** [comment]
Will validate the script for distributed Minio.

**Comment by akb2017** [comment]
ok

**Comment by akb2017** [comment]
Iam getting the error like this -->
Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Sat 2017-04-22 08:35:48 IST; 44s ago
Docs: https://docs.minio.io
Process: 8886 ExecStart=/opt/minio/minio server $MINIO_OPTS $MINIO_VOLUMES (code=exited, status=1/FAILURE)
Process: 8883 ExecStartPre=/bin/bash -c [ -n "${MINIO_VOLUMES}" ] || echo "Variable MINIO_VOLUMES not set in /etc/default/minio" (code=exited, status=0/SUCCESS)
Main PID: 8886 (code=exited, status=1/FAILURE)
Apr 22 08:35:48 deds14 systemd[1]: Starting Minio...
Apr 22 08:35:48 deds14 systemd[1]: Started Minio.
Apr 22 08:35:48 deds14 systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 08:35:48 deds14 systemd[1]: minio.service: Unit entered failed state.
Apr 22 08:35:48 deds14 systemd[1]: minio.service: Failed with result 'exit-code'.

Iam running this on 4 ubuntu machines
My configuration file is as follows
# Local export path.
MINIO_VOLUMES=http://192.168.1.22/home/minio/data http://192.168.1.23/home/minio/data http://192.168.1.24/home/minio/data http://192.168.1.25/home/minio/data # Minio data storage directory   
# Access Key of the server.
MINIO_OPTS="--address :9000"
MINIO_ACCESS_KEY=minio2015
# Secret key of the server.
MINIO_SECRET_KEY=minio2015


minio.service file -->
[Unit]
Description=Minio
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/opt/minio/minio

[Service]
WorkingDirectory=/home/minio/work

User=minio
Group=minio

PermissionsStartOnly=true

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "[ -n \"${MINIO_VOLUMES}\" ] || echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\""

ExecStart=/opt/minio/minio server $MINIO_OPTS $MINIO_VOLUMES

StandardOutput=journal
StandardError=inherit

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=0

# SIGTERM signal is used to stop Minio
KillSignal=SIGTERM

SendSIGKILL=no

SuccessExitStatus=0

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})

**Comment by hackintoshrao** [comment]
@akb2017 : Can you also send the logs of Minio using the command `journalctl -u minio.service` and also the version of Minio you are running using the `/opt/minio/minio --version` command.

**Comment by akb2017** [comment]
version: 2017-03-16T21:50:32Z


root@deds13:/var/minio# journalctl -u minio.service
-- Logs begin at Fri 2017-04-21 23:21:52 IST, end at Sat 2017-04-22 13:11:12 IST
Apr 21 23:22:11 deds13 systemd[1]: Starting Minio...
Apr 21 23:22:11 deds13 systemd[1]: minio.service: Control process exited, code=e
Apr 21 23:22:11 deds13 systemd[1]: Failed to start Minio.
Apr 21 23:22:11 deds13 systemd[1]: minio.service: Unit entered failed state.
Apr 21 23:22:11 deds13 systemd[1]: minio.service: Failed with result 'exit-code'
Apr 22 08:19:17 deds13 systemd[1]: Starting Minio...
Apr 22 08:19:17 deds13 systemd[1]: minio.service: Control process exited, code=e
Apr 22 08:19:17 deds13 systemd[1]: Failed to start Minio.
Apr 22 08:19:17 deds13 systemd[1]: minio.service: Unit entered failed state.
Apr 22 08:19:17 deds13 systemd[1]: minio.service: Failed with result 'exit-code'
Apr 22 08:22:41 deds13 systemd[1]: Starting Minio...
Apr 22 08:22:41 deds13 systemd[1]: minio.service: Control process exited, code=e
Apr 22 08:22:41 deds13 systemd[1]: Failed to start Minio.
Apr 22 08:22:41 deds13 systemd[1]: minio.service: Unit entered failed state.
Apr 22 08:22:41 deds13 systemd[1]: minio.service: Failed with result 'exit-code'
Apr 22 08:33:15 deds13 systemd[1]: Starting Minio...
Apr 22 08:33:15 deds13 systemd[1]: minio.service: Control process exited, code=e
Apr 22 08:33:15 deds13 systemd[1]: Failed to start Minio.
Apr 22 08:33:15 deds13 systemd[1]: minio.service: Unit entered failed state.
Apr 22 08:33:15 deds13 systemd[1]: minio.service: Failed with result 'exit-code'
Apr 22 10:40:48 deds13 systemd[1]: Starting Minio...
Apr 22 10:40:48 deds13 systemd[1]: minio.service: Control process exited, code=e
lines 1-23...skipping...
-- Logs begin at Fri 2017-04-21 23:21:52 IST, end at Sat 2017-04-22 13:11:12 IST. --
Apr 21 23:22:11 deds13 systemd[1]: Starting Minio...
Apr 21 23:22:11 deds13 systemd[1]: minio.service: Control process exited, code=exited status=1
Apr 21 23:22:11 deds13 systemd[1]: Failed to start Minio.

**Comment by gowithplanb** [comment]
If I specify my MINIO_VOLUMES with a comment in the line, minio won't start either. Try removing the comment in your config file.

**Comment by akb2017** [comment]
Yeh its working fine now ..
Thanks a lot....

**Comment by Dharshan2004** [comment]
I have a problem  and getting a job assertion failed error

**Comment by Dharshan2004** [comment]
Assertion failed on job for minio.service.

**Comment by pchiend** [comment]
> Yeh its working fine now ..
> Thanks a lot....

how?
