### ISSUE TITLE
bucket listening: Regression with standalone FS

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4158]
## Expected Behavior
`mc watch` against a Minio server in standalone FS mode should succeed

## Current Behavior
`mc watch` against a Minio server in standalone FS mode fails

`ERRO[0129] Error sending update bucket listener to localhost:9000 - Peer :9000 was not initialized, unexpected error  cause=Peer :9000 was not initialized, unexpected error source=[s3-peer-client.go:171:S3PeersUpdateBucketListener()]`

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Terminal 1:
1. `minio server /tmp/fs`

Terminal 2:
1. `mc mb myminio/testbucket`
2. `mc watch myminio/testbucket`

## Context
Normal testing

## Your Environment
All
Version: f1d77801678b1e2f8d9b237d313b069d1c5e04bc

**Comment by harshavardhana** [comment]
> mc server /tmp/fs

mc server? :-p

**Comment by vadmeste** [comment]
> mc server? :-p

corrected :)
