### ISSUE TITLE
File with spaces in his name fail signature checks 

### ISSUE THREAD

**Issue by jfcalvo** [minio/minio#4162]
I'm trying to init a multipart upload with a file that has a space in his name `video 1.mp4`.

The response of the request is a 403 error indicating that `Signature does not match`.

The same exact request is working as expected when the filename doesn't have any space in the name (tested with `video_1.mp4` and working fine) so maybe it's a bug.

Minio log error is the following:

```
ERRO[16163] {"method":"POST","path":"/resumable-uploads/user-2ecf6b69-b13e-45b6-b097-a3fd2e50620d/upload-65f57c0e-2f39-43ed-b9f5-1c6930f57842/video+1.mp4","query":"uploads=1","header":{"Authorization":["AWS4-HMAC-SHA256 Credential=YWB4WI45OW89F47IENY1/20170421/eu-central-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=b5fbc5fd8a3f20dda02cc38e7d3092754021a261084a77358e1283a2ee380aaa"],"Content-Length":["0"],"Content-Type":["application/octet-stream"],"Host":["minio-1.myfuturedomain.com:9000"],"User-Agent":["hackney/1.6.5"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],"X-Amz-Date":["20170421T142338Z"]}}  cause=Signature does not match source=[auth-handler.go:123:checkRequestAuthType()]
```

Elixir/Phoenix error is:

```elixir
{:error, {:http_error, 403, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key></Key><BucketName></BucketName><Resource>/resumable-uploads/user-2ecf6b69-b13e-45b6-b097-a3fd2e50620d/upload-65f57c0e-2f39-43ed-b9f5-1c6930f57842/video+1.mp4</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>", headers: [{"Accept-Ranges", "bytes"}, {"Content-Type", "application/xml"}, {"Server", "Minio/RELEASE.2017-03-16T21-50-32Z (darwin; amd64)"}, {"Vary", "Origin"}, {"X-Amz-Request-Id", "14B76FB382E172AB"}, {"Date", "Fri, 21 Apr 2017 14:23:38 GMT"}, {"Transfer-Encoding", "chunked"}], status_code: 403}}}
```
## Environment
* macOS Sierra `10.12.4`
* Elixir/Phoenix using ex_aws `1.1.2`.
* Minio `2017-03-16T21-50-32Z`

Related and very similar issue https://github.com/minio/minio/issues/3251#issuecomment-296160367

**Comment by harshavardhana** [comment]
Would you mind posting a sample code? . It would help in our functional tests

**Comment by jfcalvo** [comment]
It's ok for you an small Elixir app using ex_aws to do that request?

**Comment by harshavardhana** [comment]
> It's ok for you an small Elixir app using ex_aws to do that request?

Sure @jfcalvo - thanks.

**Comment by jfcalvo** [comment]
I have created two functions the first one without spaces (working) and the last one with spaces that is returning an error from minio.

Take a look to the README file in order to make it run: https://github.com/jfcalvo/minio_spaces_test

Please tell me if you have problems executing it.

**Comment by krishnasrinivas** [comment]
Checking this.

**Comment by krishnasrinivas** [comment]
ex_aws encodes space as `+` instead of `%20`

Refer to the docs on the rules for signature-v4 http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html :

`The space character is a reserved character and must be encoded as "%20" (and not as "+").`

I will check if it's easy to fix and send a PR to ex_aws, if not I will create an issue there.

**Comment by krishnasrinivas** [comment]
Actually, signature is calculated fine, here is ex_aws canonical header:
```
POST
/minio-download/video%201.mp4
uploads=1
content-length:0
host:localhost:9000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20170421T190045Z

content-length;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

i.e space is encoded as %20 while calculating the signature.

But the request is sent as `+`, here is `nc -l` output 
```
krishna@escape:~$ nc -l 9000
POST /minio-download/video+1.mp4?uploads=1 HTTP/1.1
Authorization: AWS4-HMAC-SHA256 Credential=SXO8VW2OFKKP2OG7AC85/20170421/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=5793763588c168a19833e03ab4423e0bfc2741fe17d1a6f043cfbedd59f5948d
host: localhost:9000
x-amz-date: 20170421T191151Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
User-Agent: hackney/1.7.1
Content-Type: application/octet-stream
Content-Length: 0

```

Because of this minio constructs signature after encoding `+` to `%2B`, here's minio's canonical request:
```
POST
/minio-download/video%2B1.mp4
uploads=1
content-length:0
host:localhost:9000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20170421T190045Z

content-length;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by krishnasrinivas** [comment]
opened https://github.com/CargoSense/ex_aws/issues/396

**Comment by krishnasrinivas** [comment]
Fixed https://github.com/CargoSense/ex_aws/issues/396
Can be closed

**Comment by harshavardhana** [comment]
Closing as fixed here https://github.com/CargoSense/ex_aws/commit/17d1702f78d4dcf1a1ca3f5c9a2fc620c75613b5

**Comment by jfcalvo** [comment]
Thanks!
