### ISSUE TITLE
Minio Signed URL download by client

### ISSUE THREAD

**Issue by akb2017** [minio/minio#4164]
Does minio signed-url supports downloading of file as stream at minio client Java API or any other API?

**Comment by harshavardhana** [comment]
> Does minio signed-url supports downloading of file as stream at minio client Java API or any other API?

Do not understand the question? are you asking that signed URL downloads as stream?

**Comment by akb2017** [comment]
yes

**Comment by harshavardhana** [comment]
> yes

Yes it is a stream. if you have a signed URL. All you have to do is just do http GET on it.

**Comment by akb2017** [comment]
OK thank you

**Comment by akb2017** [comment]
I have one more question related to this. Will signed URL downloading support reactive streaming ?
If that supports, if you can give pointer to any reference, code or documentation will be helpful for us. Appreciate your help ,Thank you

**Comment by deekoder** [comment]
Can you elaborate on what you mean by reactive streaming? I am not sure i understand the question.

**Comment by akb2017** [comment]
Reactive streaming means downloading as stream with back pressure..

**Comment by harshavardhana** [comment]
> Reactive streaming means downloading as stream with back pressure..

There is nothing special that Minio server does other than reply back with a proper HTTP stream, now if HTTP stream does support reactive streams with back pressure then it should work fine with any libraries that do support this. 

Is this something that you looking at client side or server side?

**Comment by akb2017** [comment]
Some what cleared... Thanks you
