### ISSUE TITLE
remove a bucket from gui? 

### ISSUE THREAD

**Issue by danyaljj** [minio/minio#4166]
In the minio webapp, why there is no way to delete a bucket from the graphical interface?

**Comment by harshavardhana** [comment]
Not possible yet @danyaljj - we are re-doing the UI right now.  For now you have to use `mc rm -r`

**Comment by deekoder** [comment]
It's on our roadmap. I am filing this under future milestone for now.

**Comment by marbetschar** [comment]
Run into the same issue. Any ETA?

**Comment by harshavardhana** [comment]
> Run into the same issue. Any ETA?

No ETA yet @marbetschar we are revamping our UI and it should be available in future releases.

**Comment by nodesocket** [comment]
👍 look forward to having a way to delete a bucket in the web ui *(if empty of course)*.

**Comment by copernico** [comment]
+1

**Comment by spommerening** [comment]
+1
