### ISSUE TITLE
Policy regarding submitting security issues

### ISSUE THREAD

**Issue by slapers** [minio/minio#4168]
Hi,

Im experiencing unexpected behaviour which which might be a bit sensitive to just report in an issue. Is there a policy regarding submitting security issues ?

**Comment by harshavardhana** [comment]
> Im experiencing unexpected behaviour which which might be a bit sensitive to just report in an issue. Is there a policy regarding submitting security issues ?

@slapers why do you think it is a security issue is there a specific reason? - if you have logs which indicate some org details you should just redact them before sharing here. 

For security related issues you can email us as security@minio.io

**Comment by slapers** [comment]
I will send an email with the steps to reproduce..

**Comment by harshavardhana** [comment]
A release has been made as well.
