### ISSUE TITLE
Encrypt new password using HMAC

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4193]

**Comment by harshavardhana** [comment]
is there any more detail/description to this issue other than the issue title?

**Comment by kannappanr** [comment]
Resolution: Password change setting disabled in HTTP mode. A tooltip can be shown to the user that 'This option requires TLS configuration'

**Comment by kannappanr** [comment]
@kmkanagaraj Please assign it to appropriate person.

**Comment by kannappanr** [comment]
closing this issue as we will not be allowing password change in the new UI.
