### ISSUE TITLE
Obscure message when starting minio server

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4199]
Error message printed was not comprehensible. 

## Expected Behavior
It would just start and print the usual access key/secret key info

## Current Behavior
Migration from 11 to 18 was a series of messages seen on startup. These numbers looked different from minio server's version information leading me to wonder what was actually being migrated. If it was anything internal, does the user even need to know about it?

## Possible Solution
Evaluate if there is a valid need to show config file migration messages to the user.  

## Steps to Reproduce (for bugs)
Install an older version of minio first. Then install a much newer version of the binary. You should be able to see these messages. 

## Context
 It's a cosmetic issue. 

## Your Environment

* Version used (`minio version`):  2017-04-28T19:24:01Z
* Environment name and version (e.g. nginx 1.9.1): none
* Server type and version: fs
* Operating System and version (`uname -a`): 
* Link to your project: 16.3.0 Darwin Kernel Version 16.3.0

Actual message :
```
minio server ~/Downloads/miniodata/
Migration from version ‘10’ to ‘11’ completed successfully.
Migration from version ‘11’ to ‘12’ completed successfully.
Migration from version ‘12’ to ‘13’ completed successfully.
Migration from version ‘13’ to ‘14’ completed successfully.
Migration from version ‘14’ to ‘15’ completed successfully.
Migration from version ‘15’ to ‘16’ completed successfully.
Migration from version ‘16’ to ‘17’ completed successfully.
Migration from version ‘17’ to ‘18’ completed successfully.

Endpoint:  http://192.168.1.9:9000  http://127.0.0.1:9000
AccessKey:  <redacted>
SecretKey:   <redacted>
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://192.168.1.9:9000  http://127.0.0.1:9000

```

**Comment by deekoder** [comment]
The version numbers are not recognizable. Also why is it printing 2 ip addresses for me?

**Comment by harshavardhana** [comment]
> Migration from version ‘10’ to ‘11’ completed successfully.
> Migration from version ‘11’ to ‘12’ completed successfully.
> Migration from version ‘12’ to ‘13’ completed successfully.
> Migration from version ‘13’ to ‘14’ completed successfully.
> Migration from version ‘14’ to ‘15’ completed successfully.
> Migration from version ‘15’ to ‘16’ completed successfully.
> Migration from version ‘16’ to ‘17’ completed successfully.
> Migration from version ‘17’ to ‘18’ completed successfully.

```
Migrating minio configuration version 'N' to 'M' completed successfully.  
```

Is more readable.
