### ISSUE TITLE
TLS handshake error message

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4200]
See output below

## Expected Behavior
Not print TLS handshake error when https is not used in the URL.

## Current Behavior
I have a browser with HTTPS everywhere ad on. Trying to open the minio browser gave correct errors on the browser. And a TLS handshake error on the terminal. After pasting the URL in another browser without https everywhere plugin, still gave TLS error even though it opened the minio browser login page successfully.
 
## Possible Solution
Suppress the extra error message if possible.  

## Steps to Reproduce (for bugs)
1. Start Minio Server
2. Refresh Minio Browser on a browser with the plugin https everywhere
3. Check terminal for TLS error
4. Now open the Minio Browser url on a browser using http
4. More TLS error printed on the terminal.

## Context

Surprised at the additional error message.

 
## Your Environment

* Version used (`minio version`):  Test candidate
* Environment name and version (e.g. nginx 1.9.1): macOS 10.12.2
* Server type and version: Test candidate from Apr 28
* Operating System and version (`uname -a`): 16.3.0 Darwin Kernel Version 16.3.0
* Link to your project:  N/A

 

Actual error output :
 
```
ERRO[0107] TLS handshake failed                          cause=tls: no certificates configured source=[server-mux.go:271:newListenerMux.func1.1()]
ERRO[0107] TLS handshake failed                          cause=tls: no certificates configured source=[server-mux.go:271:newListenerMux.func1.1()]
ERRO[0240] Unable to peek into incoming protocol         cause=read tcp 192.168.1.9:9000->192.168.1.9:57588: i/o timeout source=[server-mux.go:259:newListenerMux.func1.1()]
ERRO[0240] Unable to peek into incoming protocol         cause=read tcp 192.168.1.9:9000->192.168.1.9:57586: i/o timeout source=[server-mux.go:259:newListenerMux.func1.1()]
ERRO[0240] Unable to peek into incoming protocol         cause=read tcp 192.168.1.9:9000->192.168.1.9:57587: i/o timeout source=[server-mux.go:259:newListenerMux.func1.1()]
ERRO[0240] Unable to peek into incoming protocol         cause=read tcp 192.168.1.9:9000->192.168.1.9:57585: i/o timeout source=[server-mux.go:259:newListenerMux.func1.1()]

```

**Comment by harshavardhana** [comment]
This is expected @deekoder if you are trying to access minio server with TLS, without having TLS configured.

**Comment by balamurugana** [comment]
The issue is addressed properly in https://github.com/minio/minio/pull/4217
