### ISSUE TITLE
Minio server does not seem to start for the current directory as shown

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4222]
`minio server .` does not start

## Expected Behavior

minio server should simply start use the current directory.
 
## Current Behavior
 Invalid command line arguments server=‘:9000’, args=[.]  cause=empty or root endpoint is not supported source=[server-main.go:143:serverHandleCmdArgs()]

## Possible Solution
 None

## Steps to Reproduce (for bugs)
 Simply start minio server with the .  path

## Context
 Adhoc Testing

## Your Environment
 
* Version used (`minio version`): 2017-04-28T19:24:01Z
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: FS
* Operating System and version (`uname -a`):  16.3.0 Darwin Kernel Version 16.3.0
* Link to your project: N/A

**Comment by harshavardhana** [comment]
> minio server . does not start

This was done on purpose to avoid ROOT paths. @deekoder since they do not have a path component, but they can be relaxed..

**Comment by harshavardhana** [comment]
> This was done on purpose to avoid ROOT paths. @deekoder since they do not have a path component, but they can be relaxed.

Such as "/", "." do not work.  You can make it work by doing `minio server ./`

**Comment by deekoder** [comment]
ok but its good for me to know why we avoid ROOT paths. Is it a security issue?

**Comment by harshavardhana** [comment]
Perhaps only for "/" root path. We can allow this to work for "." Since this signifies present directory.

It should also not work if your current directory is / and then you started with "."

**Comment by deekoder** [comment]
Let's check with @abperiasamy

**Comment by deekoder** [comment]
ETA: 2017-06-08 17:55

**Comment by harshavardhana** [comment]
Fixed by #4513

**Comment by harshavardhana** [comment]
Re-opening since its partially fixed.. in #4513 @krishnasrinivas is sending another fix.

**Comment by harshavardhana** [comment]
It is indeed fixed and validated by @krishnasrinivas - closing.
