### ISSUE TITLE
Access Key change on minio browser should behave similar to password change

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4223]
Seems like access key change has no effect immediately.

## Expected Behavior
 
If access key is changed from inside minio browser, log the user out just like a password change.

 

## Current Behavior
Change access key from Settings. Close the browser tab. Minio browser loads without any issues. 

## Steps to Reproduce (for bugs)
 
1. Login to Minio Browser
2. Change the access key from the settings menu
3. Close browser tab
4. Reopen Minio Browser (no auth is required again). Since they are a pair (access/secret) it should not allow user to see the buckets without re-authenticating.

## Context
Adhoc testing
 
## Your Environment

* Version used (`minio version`): 2017-04-28T19:24:01Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: FS
* Operating System and version (`uname -a`): macOS
* Link to your project:

**Comment by krishnasrinivas** [comment]
> If access key is changed from inside minio browser, log the user out just like a password change.

@deekoder currently we don't log the user out if secret key is changed. Is this needed because even gmail does not logout after password change (I just checked). Though gmail asks for current password before changing the password (which we are handling in this issue https://github.com/minio/minio/issues/4182)

**Comment by krishnasrinivas** [comment]
@deekoder this issue can be closed, we will not log out the user if he changes the access/secret key.
