### ISSUE TITLE
Minio Server in RELEASE.2017-04-25T01-27-49Z and above, doesn't start in a distributed mode in Kubernetes

### ISSUE THREAD

**Issue by mzygmunt** [minio/minio#4225]
## Expected Behavior
Minio RELEASE.2017-04-25T01-27-49Z and above will start in a distributed mode in Kubernetes 1.6.2.

## Current Behavior
If I configure Minio in distributed mode, I get an error:
`time="2017-05-03T08:24:04Z" level=fatal msg="Invalid command line arguments server=‘:9000’, args=[http://minio-0.minio.default.svc.cluster.local/export http://minio-1.minio.default.svc.cluster.local/export http://minio-2.minio.default.svc.cluster.local/export http://minio-3.minio.default.svc.cluster.local/export]" cause="'http://minio-1.minio.default.svc.cluster.local/export': lookup minio-1.minio.default.svc.cluster.local on 10.96.0.10:53: no such host" source="[server-main.go:143:serverHandleCmdArgs()]"`

## Steps to Reproduce (for bugs)
My configuration is the same as here (distributed mode section): https://github.com/kubernetes/kubernetes/tree/master/examples/storage/minio

I noticed that, in version RELEASE.2017-03-16T21-50-32Z and under, all works fine with the same config.

## Your Environment
* Version used (`minio version`): RELEASE.2017-04-25T01-27-49Z and above
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Kubernetes 1.6.2
* Operating System and version (`uname -a`): Linux kube-master1 4.4.0-75-generic
* Link to your project:

**Comment by harshavardhana** [comment]
> lookup minio-1.minio.default.svc.cluster.local on 10.96.0.10:53: no such host" source="[server-main.go:143:serverHandleCmdArgs()]"

This error looks like a DNS server issue are you able to run with the previous release from `RELEASE.2017-04-25T01-27-49Z` ?

**Comment by mzygmunt** [comment]
I tried to run RELEASE.2017-03-16T21-50-32Z and everything works fine. DNS also works fine (tested with other services). In addition this error appears on minio-0 and stops scheduling the rest of the pods - maybe this is the cause?

**Comment by nitisht** [comment]
@mzygmunt we have fixed the issue. It is available in the master. 

Can you please try the image `minio/minio:edge` for you Kubernetes cluster, and let us know how this goes?

**Comment by mzygmunt** [comment]
@NitishT @harshavardhana  I pulled minio/minio:edge, but I have the same error on first pod:
`
time="2017-05-04T19:11:35Z" level=fatal msg="Invalid command line arguments server=‘:9000’, args=[http://minio-0.minio-headless.minio.svc.cluster.local/export http://minio-1.minio-headless.minio.svc.cluster.local/export http://minio-2.minio-headless.minio.svc.cluster.local/export http://minio-3.minio-headless.minio.svc.cluster.local/export]" cause="'http://minio-1.minio-headless.minio.svc.cluster.local/export': lookup minio-1.minio-headless.minio.svc.cluster.local on 10.96.0.10:53: no such host" source="[server-main.go:143:serverHandleCmdArgs()]"
`
When I pulled back version minio/minio:RELEASE.2017-03-16T21-50-32Z, then Minio works fine.

**Comment by harshavardhana** [comment]
Are you sure @mzygumnt that you have pulled the latest . In our tests we used Google cloud with Kubernetes.  We can validate again.

But I would suggest if you can try again on a fresh cluster.

**Comment by nitisht** [comment]
@mzygmunt how are you deploying Minio on Kubernetes? Using the helm pack or custom yaml file. If it is a yaml file can you put it here? 

The reason is, with recent changes you'll need to remove the `command` field in the yaml file, it should look like:

```
image: minio/minio:edge
args:
- server
- http://minio-0.minio.default.svc.cluster.local/data
- http://minio-1.minio.default.svc.cluster.local/data
- http://minio-2.minio.default.svc.cluster.local/data
- http://minio-3.minio.default.svc.cluster.local/data
```

**Comment by mzygmunt** [comment]
@NitishT When I removed `command`, Minio works fine. This solved the issue.

**Comment by nitisht** [comment]
Great! Thanks @mzygmunt we'll update the documents on Minio and Kubernetes examples.

**Comment by harshavardhana** [comment]
> @NitishT When I removed command, Minio works fine. That solved the issue.

Thanks @mzygmunt we are updating the docs with this change. Entry point is overridden and our script never gets the control. 

Thanks for spending time and testing this.

**Comment by kmcrawford** [comment]
I see this is resolved, but I'm having the same issues. 

  image: minio/minio:edge
        args:
        - server
        - http://minio-0.minio.default.svc.cluster.local/data
        - http://minio-1.minio.default.svc.cluster.local/data
        - http://minio-2.minio.default.svc.cluster.local/data
        - http://minio-3.minio.default.svc.cluster.local/data

time="2017-09-24T16:36:46Z" level=error msg="Unable to resolve host minio-1.minio.default.svc.cluster.local (7 minutes elapsed)" cause="lookup minio-1.minio.default.svc.cluster.local on 10.51.240.10:53: no such host" source="[net.go:102:getHostIP4()]"

**Comment by harshavardhana** [comment]
Have you followed our deployment guide here https://docs.minio.io/docs/deploy-minio-on-kubernetes

**Comment by hokiegeek2** [comment]
@kmcrawford Not sure if this is still an issue, but I just ran into this on my home cluster. I added two new mini-computers and forgot to set the hosts file, so my machine name had an IP of 127.0.0.1. Once I updated the hosts file and reloaded the daemon set, all nodes came up correctly.

**Comment by harshavardhana** [comment]
> @kmcrawford Not sure if this is still an issue, but I just ran into this on my home cluster. I added two new mini-computers and forgot to set the hosts file, so my machine name had an IP of 127.0.0.1. Once I updated the hosts file and reloaded the daemon set, all nodes came up correctly.

Please open a new GitHub issue @hokiegeek2 if you think you have an issue.

**Comment by hokiegeek2** [comment]
@harshavardhana Cool, yeah, it looks like Minio is working fine. Just added my comment to document that I was seeing the same error and I fixed it by fixing my /etc/hosts configuration. BTW, Minio is a really cool product working well for me thus far.
