### ISSUE TITLE
Sporadic test failure in TestPostPolicyBucketHandler

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4226]
```
=== RUN   TestPostPolicyBucketHandler
--- FAIL: TestPostPolicyBucketHandler (3.95s)
	<autogenerated>:10: Test 3: XL: Expected the response status to be `400`, but instead found `403`
```

## Expected Behavior
TestPostPolicyBucketHandler never fails. 

## Current Behavior
TestPostPolicyBucketHandler can fail unknowingly. 

## Possible Solution
Not sure. 

## Steps to Reproduce (for bugs)
Hard to reproduce have to use `go test -race -run=TestPostPolicyBucketHandler` with many runs.

## Context
Tests should be idempotent. 

## Your Environment
Current master.

**Comment by vadmeste** [comment]
I can take this.

**Comment by hackintoshrao** [comment]
I'm interested too. Will use some concurrency and do some race tests.

**Comment by deekoder** [comment]
Can't reproduce anymore.
