### ISSUE TITLE
Need a way to specify logging on command line

### ISSUE THREAD

**Issue by swills** [minio/minio#4228]
For rc scripts, we need a way to specify logging config on command line.

## Expected Behavior
Would be nice if I could specify logging config on command line, so that rc scripts can rely on that instead of redirecting stdout/stderr with default config.

## Current Behavior
Right now, when you start minio without config, it creates a default config file which logs to stdout/stderr. For the rc script, this means that in order to avoid output showing up after the process is daemonized, I have to redirect stdout/stderr somewhere. Currently this goes to /dev/null, but this can cause issues for users, so I'm looking at changing it to redirect them to a log file. See:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218957

for background. This redirect does however run the risk that the user would edit the log file and setup logging to the same file, causing double logging.

## Possible Solution
It would be ideal if the script could specify a log file on command line and have minio log to that. Or even better, specify a log file and possibly other settings and have minio write the default config with those settings and then exit.

(While I'm asking for unicorns, would also be nice if minio had a flag to daemonize itself.)

One possible solution was to include a default config file, but that would have to include credentials, unless minio was changed to generate credentials and add them if they were missing.

## Steps to Reproduce (for bugs)
See above

## Context
See above

## Your Environment
I'm using 2017-04-29T00:40:27Z on FreeBSD

**Comment by vadmeste** [comment]
Specifying a log parameter shouldn't be done in rc script since it will be overridden with the value set by the user if the latter decides to change it. I think you want to specify it post package install instead.

**Comment by swills** [comment]
Not sure what you mean by "post package install"? That is, do you mean, by the user, by the rc script or perhaps in some sort of post install script run by the package manager after the package is installed? We try to avoid post install scripts, but running something in the rc script if the config doesn't exist might work.

**Comment by vadmeste** [comment]
> in some sort of post install script run by the package manager after the package is installed?

I meant this one.

> running something in the rc script if the config doesn't exist might work.

Yes. I guess.

**Comment by vadmeste** [comment]
It does make sense for me if --quiet will be able to disable console log, not only to resolve this issue but it seems it is a natural thing to do.

**Comment by kannappanr** [comment]
@swills We are simplifying the config.json and are no longer supporting logging to a file. As part of daemonizing minio executable, the user has to redirect the output to a file.

As far as the ability to change the config value via command line. We have a task in pipeline that will allow you do that via `mc admin` command. 

As far as daemonizing minio with a commmand line option, we will talk over it and see if we can support it in the future.

Please open a new issue if you have further questions.
