### ISSUE TITLE
Browser: Object download is not working in guest mode

### ISSUE THREAD

**Issue by rushenn** [minio/minio#4230]
Object download is not working in guest mode

## Expected Behavior
Objects should be downloadable in guest mode 

## Current Behavior
When trying to download one or multiple objects from the browser, it fires an error message in the console 
```
Failed to load resource: the server responded with a status of 403 (Forbidden)  ..../minio/zip?token=undefined 
```

## Steps to Reproduce (for bugs)

1. Open Browser in guest mode.
2. Select one or more objects.
3. Click 'Download all as zip' from the top action header.

## Your Environment
* Version used: 2017-03-15T17:49:51Z
* Operating System and version: macOS Sierra 10.12.4

**Comment by deekoder** [comment]
Can you repro this in the latest release?

**Comment by deekoder** [comment]
Linux : Downloads if logged in.
Win : Downloads but does not open because downloadable is not a .zip extension. Manually renaming it to a .zip then opened it successfully.

**Comment by deekoder** [comment]
Server should check if the operation is allowed and proceed accordingly.
