### ISSUE TITLE
Message : You are running an older version of Minio released 5 hours from now

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4232]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 5 hours from now ┃
┃ Update: https://dl.minio.io/server/minio/release/darwin-amd64/minio ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
## Expected Behavior

No such message since I am running the test binaries. 

## Current Behavior
The above sentence does not sound intuitive.
 
## Possible Solution
 Don't know.

## Steps to Reproduce (for bugs)
 
1. Type `minio gateway azure` with keys
 
## Context
It's ambiguous now for me because I think i need to update to the latest released version of minio. However since i am already using a release candidate, why does it ask me update. Perhaps it should know that the current version is > than the released versions and not show me this message.

## Your Environment
 
* Version used (`minio version`):  2017-04-28T19:24:01Z
* Environment name and version (e.g. nginx 1.9.1): macOS
* Server type and version: Test Build, Gateway
* Operating System and version (`uname -a`): 16.5.0 Darwin Kernel Version 16.5.0
* Link to your project:

**Comment by harshavardhana** [comment]
Actually you are running older @deekoder our latest release is - 2017-04-29T00-40-27Z

**Comment by harshavardhana** [comment]
Which is precisely 5 hours.. but agreed the message is '5 hours from now' is confusing since its isn't now.

**Comment by deekoder** [comment]
Oh we updated data.minio.io build? I haven't downloaded it since i did it on APR 28.

**Comment by harshavardhana** [comment]
> Oh we updated data.minio.io build? I haven't downloaded it since i did it on APR 28.

I don't think we have updated data.minio.io after April 28th.

**Comment by deekoder** [comment]
Ok great. So now i am clear about the build numbers. But this bug is still valid due to "now" word.

**Comment by harshavardhana** [comment]
> Ok great. So now i am clear about the build numbers. But this bug is still valid due to "now" word.

Yes it is "now" is not correct.

**Comment by balamurugana** [comment]
@deekoder how about fixing the description of the issue WRT `now`? current description is incorrect and clear description wouldn't confuse someone in future than going through all comments.

**Comment by deekoder** [comment]
Current:  You are running an older version of Minio released 5 hours from now

Proposed : A new version of Minio has been released < humanized time > ago. 
except no ago when the string has "now" in it.

Test : 

A new version of Minio has been released now
A new version of Minio has been released 2 hours ago
A new version of Minio has been released 3 months ago
A new version of Minio has been released 1 minute ago
A new version of Minio has been released 13 days ago

**Comment by deekoder** [comment]
@abperiasamy  :
Never print any message if minio is the latest version. Now string can never be printed. 
Eg : 
You are running an older version of Minio released 5 hours ago is fine. Don't compute the newerThan time string in the colorize function.  UTC.now() should be looked at.
