### ISSUE TITLE
[bug] Cryptic error message due to bad value in config file

### ISSUE THREAD

**Issue by donatello** [minio/minio#4233]
When there is a bad value in the configuration file, the server appears to report an error unrelated to the bad configuration value.

When setting the kafka configuration value `notify.kafka.brokers` whose value has type list, a simple string was given `"localhost:9092"`, but the error was cryptic:

```
$ minio server /tmp/newd
FATA[0000] Config migration failed.                      cause=Unable to load config version ‘6’. json: cannot unmarshal string into Go value of type []string source=[server-main.go:109:initConfig()]
```

While the type error makes sense (since we know the problem already), it does not say where the error happened. Also the error message says it is related to configuration migration - however the configuration was already at version 18 (latest afaik).

## Expected Behavior

Error message should not say configuration migration at the very least. It would be good if it says which item in the configuration file had a parsing error.

## Current Behavior

As described above.

## Possible Solution

Unknown.

## Steps to Reproduce (for bugs)

1. Enable kafka in the configuration and set the `brokers` value as described above.
2. Start the server.

## Context

Happened during testing of something unrelated to this.

## Your Environment

* Version used (`minio version`):
```
Version: 2017-05-03T19:23:01Z
Release-Tag: DEVELOPMENT.2017-05-03T19-23-01Z
Commit-ID: f0b5c0ec7cbd6604d4a43ed0869318741823a40a
```
* Environment name and version (e.g. nginx 1.9.1): Linux

**Comment by deekoder** [comment]
Putting this in edge cache since its  2017-05-03T19:23:01Z and not the test build.  Will move if @donatello repros in test build as well.

**Comment by donatello** [comment]
It happens on the test build too:

```
$ minio-release server /tmp/newd
FATA[0000] Config migration failed.                      cause=Unable to load config version ‘6’. json: cannot unmarshal string into Go value of type []string source=[server-main.go:109:initConfig()]
$ minio-release version
Version: 2017-04-28T19:24:01Z
Release-Tag: RELEASE.2017-04-28T19-24-01Z
Commit-ID: d36dd80a8a8ec959af008b35453fa5126ab1acdf
```

**Comment by harshavardhana** [comment]
> While the type error makes sense (since we know the problem already), it does not say where the error happened. Also the error message says it is related to configuration migration - however the configuration was already at version 18 (latest afaik).

Config migration requires reading of config file from earliest known to latest, first attempt is always to read and migrate.. So the error is appropriate from code point of view that it failed properly without corrupting the config file. 

Nevertheless messaging should be improved here ..
