### ISSUE TITLE
Browser: Does not autofill saved access/secret keys on windows

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4235]
Chrome/Explorer should allow autofilling passwords if saved on the browser.

## Expected Behavior
Save access key & secret key should be autofilled when opening the minio browser again.
## Current Behavior
Does not autofill access/secret key on browser.

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
 
1. Install minio on windows
2. Login and allow chrome password manager to save the credentials.
3. Logout
4. Go back to login page. Chrome does not autofill the saved credentials.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Fixed by #4091
