### ISSUE TITLE
Request an object by ranges of 5MB traffic between minio rose to +/- 600/5*600MB

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4236]
Hi, I have a file of 600Mo, I request this file by ranges of 5Mo and it looks like the traffic between the minio is +/- 600/5*600Mo ....

```
{"version":"1.0.0","format":"xl","stat":{"size":610184874,"modTime":"2017-05-03T13:20:24.810639588Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":4,"distribution":[3,4,1,2],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"c0e27462affda2512fbc7ed2edf3f3466e79dbb2391cd8f778ca6930e6af7b405d191f85e1c701bacada042f3529f65196166d4e9ff8351c62adbfa7340c2d33"},{"name":"part.2","algorithm":"blake2b","hash":"68a37018c5b379d50c5ce428b2256a32bb7cb222d279ed4751e8da4645076ee590f431dc6f1fc03a91fab0e797b93842ed39faefce50459834a238239c6bb35d"},{"name":"part.3","algorithm":"blake2b","hash":"38f6570629a3f645da83d742950078e4e386a2be1f2dbda5e818a5ec291288498acea7339869b11a818f046d84abc6c901b4d2814f91d30167f647bfd57adbe5"},{"name":"part.4","algorithm":"blake2b","hash":"2859055291d3104b6310c7436536a742ce5e5bea208c401fae544b73ebdcb1714e658e7591fbe769e2d4954eb605b3bf4919d11768e5ef134c42b493bd78dc02"},{"name":"part.5","algorithm":"blake2b","hash":"292c2f4cf4a0034f7998ca9f39ddc6247e58f7fd67da972bf347233bb593e4e21e3957297ac21101c9af279555b901756dd1d89d5deb621821fcaeefdd25bb41"},{"name":"part.6","algorithm":"blake2b","hash":"bc2174bf07052abf51766d10048215cc0fcfbfbb9a264ad1a9613e8b55aa8e4f75da48e412562728e0aacb833062df4b8e87f5ec9bacfdef7da3021b6b3a6e5c"},{"name":"part.7","algorithm":"blake2b","hash":"c818d362cbbbaf6c3238aaf26b98aad5843afe4ea87aa974417fa44acd84f7de2e8a6b5e7260d5c2506fec2d4832d1e383fa136d8143a4a4a2002e8b577c670e"},{"name":"part.8","algorithm":"blake2b","hash":"c52345ea710fbe005c5462a8d0e248e7c54e1a404630f4955bd7d84861dfa03bc336753c81d4a9adceba8c0a5273f3e817cba03f9a1b75acc16f13e3b7d0b308"},{"name":"part.9","algorithm":"blake2b","hash":"efde022268693378b89bbb856c4cf59725177ad21a2e4d07e533a4a3a4bed59da6659e8075533ef8db4f284621e4c004a45f7fe8a26bce0e8387b75107854df8"},{"name":"part.10","algorithm":"blake2b","hash":"0a7b323d618bd0f079cde5ecb82b3b73a901f9bc46791bc4742e5f81b38c57b9160dbec7cbfa458c5953d47b536d4929618ef28dfee61074729f07b9898e93a8"}]},"minio":{"release":"DEVELOPMENT.2017-04-27T19-43-28Z"},"meta":{"md5Sum":"e2508ace73dbf331c3cb3e3e95227cc5"},"parts":[{"number":1,"name":"part.1","etag":"","size":67108864},{"number":2,"name":"part.2","etag":"","size":67108864},{"number":3,"name":"part.3","etag":"","size":67108864},{"number":4,"name":"part.4","etag":"","size":67108864},{"number":5,"name":"part.5","etag":"","size":67108864},{"number":6,"name":"part.6","etag":"","size":67108864},{"number":7,"name":"part.7","etag":"","size":67108864},{"number":8,"name":"part.8","etag":"","size":67108864},{"number":9,"name":"part.9","etag":"","size":67108864},{"number":10,"name":"part.10","etag":"","size":6205098}]}
```

Using https://nginx.org/en/docs/http/ngx_http_slice_module.html with size 5M and it's a sequence from the begining to the end of the file. It should be fast and should not generate a traffic of an average of 700Mbits during more than a minute

## Expected Behavior
Expected to not transfer large amounts of data for only 5Mb worth of range reads.

## Current Behavior
Data transfer is large even for smaller range request.

## Possible Solution
investigate the GetObject() method. 

## Steps to Reproduce (for bug)
Reproduced by user @dcharbonnier 

## Context
Performance improvements.. 

## Your Environment
Current release.

**Comment by dcharbonnier** [comment]
Difference between ranges of 1Go, 100Mo, 10Mo, 1Mo and 64M (the part size)

```
cat test.sh
FILE="st0/5909862adf21c60010e75a90-exports/5909ce8915de6f000f07d503";
PART_SIZE=67108864;
START=0;
rm file.minio;
URL=`mc share --json download $FILE |jq -r '.share'`;
FILE_SIZE=`mc ls --json $FILE|jq -r '.size'`

START=0
while [ $START -lt $FILE_SIZE ]
do
  END=`expr $START + $PART_SIZE`
  echo "RANGE $START-$END";
  curl -H "range: bytes=$START-$END" $URL >> file.minio
  echo "";
  START=$END;
done
curl -H "range: bytes=$START-" $URL >> file.minio
```
### 1Go
![screen shot 2017-05-04 at 9 17 44 am](https://cloud.githubusercontent.com/assets/6220422/25693909/172ced72-30ac-11e7-80ea-6c484a9658a9.png)
### 100Mo
![screen shot 2017-05-04 at 9 14 32 am](https://cloud.githubusercontent.com/assets/6220422/25693911/173388bc-30ac-11e7-9645-cd0e33c5d763.png)
### 10 Mo
![screen shot 2017-05-04 at 9 09 52 am](https://cloud.githubusercontent.com/assets/6220422/25693910/172e6990-30ac-11e7-9bdc-eb68ee275010.png)
### 64 Mo
![screen shot 2017-05-04 at 10 01 08 am](https://cloud.githubusercontent.com/assets/6220422/25694812/b5a105de-30b0-11e7-9dca-f6945a7be7f8.png)
### 1 Mo
![screen shot 2017-05-04 at 9 46 54 am](https://cloud.githubusercontent.com/assets/6220422/25694813/b5b770bc-30b0-11e7-80ba-f810613e1a1c.png)

**Comment by harshavardhana** [comment]
Thanks @dcharbonnier

**Comment by dcharbonnier** [comment]
Total of traffic in the cluster for different ranges
```
1 Go    rx 1277  MiB tx 1833  MiB
100 Mo  rx 2632  MiB tx 1981  MiB
64 Mo   rx 2905 MiB  tx 3415  MiB
10 Mo   rx 11710 MiB tx 12280 MiB
1 Mo    rx 72230 MiB tx 72760 MiB
```

**Comment by dcharbonnier** [comment]
any ETA for this ?

**Comment by harshavardhana** [comment]
> any ETA for this ?

Would like to discuss this with you over on slack @dcharbonnier

**Comment by harshavardhana** [comment]
It was discussed and agreed that we will implement a hashing verifier as a POSIX interface level primitive. 

```go
func Verify(volume string, path string, offset int64, length int64, algo string, expectedHash []byte) (ok bool, err error) 
``` 

This would offload the checksum calculation to POSIX while not spilling over the format details. i.e this primitive is generic enough to be implemented at POSIX layer but is implemented like a generic checksum verifier at POSIX which has offset and length variation as well.  Caller is supposed to provide what is being matched against. 

This would in-turn allow for not having to do data transfer across for each small offset reads, after this PR is merged we are also removing the object in memory caching.

**Comment by krishnasrinivas** [comment]
should `algo` be a string? because it needs to be transmitted over network.
expectedHash should be []byte? because []byte is canonical representation of hash value. If it is a string then it could be hex-encoded or base64 encoded. This is why we changed the API at minio-go putobject API to:
func (c Core) PutObject(bucket, object string, size int64, data io.Reader, md5Sum, sha256Sum []byte, metadata map[string][]string) (ObjectInfo, error) {

i.e if md5Sum was a string we would not know if it is base64 encoded or md5sum encoded.

also this would be a better API?:
```
getHash(volume string, path string, offset int64, length int64, algo string) (hashVal []byte, err error)
```

**Comment by harshavardhana** [comment]
> should algo be a string? because it needs to be transmitted over network.

Algo should be a string. My mistake.

> expectedHash should be []byte? because []byte is canonical representation of hash value. If it is a string then it could be hex-encoded or base64 encoded. This is why we changed the API at minio-go putobject 

Yes expected hash should be []byte. 

> getHash(volume string, path string, offset int64, length int64, algo string) (hashVal []byte, err error)

This variant was also discussed but its not adding any value unless we need to use this for computing checksums while returning to client which we don't do. 

Currently there is no need to transmit the data just to verify at the top level, we can avoid that as well just by returning boolean. Its a further reduction by passing in the hash itself to be verified. Any allocations memory etc is all confined at the remote server rather than coming over the network.

**Comment by harshavardhana** [comment]
```go
func Verify(volume string, path string, offset int64, length int64, algo string, expectedHash []byte) (ok bool, err error) 
```
Here is the updated one.  

Additionally we can bring a proper type for `algo string` as well providing some more safety to the data transferred over the network.

```go
type HashAlgo string

const (
       HashBlake2b HashAlgo = "blake2b"
       HashSha256 HashAlgo = "sha256"
)
```

So it would be 

```go
func Verify(volume string, path string, offset int64, length int64, algo HashAlgo, expectedHash []byte) (ok bool, err error) 
```

**Comment by donatello** [comment]
Would it be better to eliminate the `bool` from the return value? We could just have ErrHashMismatch in case the hash value does not match. This way we could avoid a new return type for RPC calls.
