### ISSUE TITLE
S3 gateway does not support accessing multiple regions

### ISSUE THREAD

**Issue by donatello** [minio/minio#4241]
After starting the gateway in us-east-1 region, if we try to create a bucket in a different region, we get an error from mc.

## Expected Behavior

Region should pass through the gateway to the backend and the request should work

## Current Behavior

We get error.

## Possible Solution

Unknown.

## Steps to Reproduce (for bugs)

1. Start gateway like:
```
MINIO_ACCESS_KEY="<redacted>" MINIO_SECRET_KEY="<redacted>" minio gateway s3 https://s3.amazonaws.com
```
2. Add alias s3gw for the gateway into `mc`. I used S3V2.
3. Run:
```
$ mc mb --region us-west-2 s3gw/miniostestbucket
mc: <ERROR> Unable to make bucket `s3gw/miniostestbucket`. Region does not match.
```

## Context

Testing

## Your Environment

* Version used (`minio version`): Latest master.
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by donatello** [comment]
Also, I get the same behaviour when using the env vars `_MINIO_REGION` or `MINIO_REGION`.

**Comment by deekoder** [comment]
I tried it on azure gateway. The region in the config file was us-east-1

$ mc mb --region us-west-2 myazure/testbucket
mc: <ERROR> Unable to make bucket `myazure/testbucket`. Region does not match.

$ mc mb --region us-east-1 myazure/testbucket
Bucket created successfully `myazure/testbucket`.

**Comment by krishnasrinivas** [comment]
This is dup of https://github.com/minio/minio/issues/4092

**Comment by deekoder** [comment]
Not a showstopper for today's release.

**Comment by krishnasrinivas** [comment]
Apologies this is not dup of  #4092, sent a PR https://github.com/minio/minio/issues/4335 to fix it

**Comment by deekoder** [comment]
@deekoder check if this needs to be closed.

**Comment by deekoder** [comment]
FIxed.
