### ISSUE TITLE
Update Kubernetes examples/helm/mesos packages with new interface

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4245]
## Expected Behavior
Distributed Minio should launch on Kubernetes

## Current Behavior
We changed the waiting mechanism for distributed Minio on Kubernetes. All the Minio - Kubernetes 
examples should be updated. 

## Possible Solution
Update the example docs 
- https://github.com/kubernetes/kubernetes/tree/master/examples/storage/minio
- https://github.com/kubernetes/charts/tree/master/stable/minio
- https://github.com/minio/minio/tree/master/docs/orchestration/kubernetes

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Kubernetes helm charts PR: https://github.com/kubernetes/charts/pull/1015

Helm PR merged.

**Comment by nitisht** [comment]
Minio Docker composes file update PR: https://github.com/minio/minio/pull/4271

**Comment by nitisht** [comment]
Kubernetes example PR: https://github.com/kubernetes/kubernetes/pull/45444

**Comment by nitisht** [comment]
Mesos universe package PR: https://github.com/mesosphere/universe/pull/1159

**Comment by nitisht** [comment]
Sent the PRs, the priority can be reduced now. One the PRs are merged, we can close this.

**Comment by deekoder** [comment]
Still waiting upstream for the merge to happen.

**Comment by nitisht** [comment]
https://github.com/mesosphere/universe/pull/1159 closed in favour of https://github.com/mesosphere/universe/pull/1160

**Comment by nitisht** [comment]
@deekoder all the PRs are merged. This can be closed now.

**Comment by harshavardhana** [comment]
> @deekoder all the PRs are merged. This can be closed now.

Closing.. as fixed upstream.
