### ISSUE TITLE
[notify] webhook: Unable to start Minio when endpoint is unreachable

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4254]
## Expected Behavior
To be able to run Minio and work normally when webhook endpoint is unreachable.

## Current Behavior
*Not* able to run Minio when webhook endpoint is unreachable.

## Possible Solution
Do not know.

## Steps to Reproduce (for bugs)
1. Enable web hook notify and set endpoint as `http://localhost:random_port`
2. Start Minio

## Context
Testing for release

## Your Environment
All
master (972a527b66f2ac05d52dc475baaf995e660f456d)

**Comment by deekoder** [comment]
Ok we have to reactivate the bug that said this was fixed.

**Comment by deekoder** [comment]
So no way to start minio just because web hook is not reachable?

**Comment by vadmeste** [comment]
> So no way to start minio just because web hook is not reachable?

Yes

**Comment by vadmeste** [comment]
> Ok we have to reactivate the bug that said this was fixed.

yes right.. better than writing a new one.

**Comment by vadmeste** [comment]
Duplicate of this https://github.com/minio/minio/issues/4050

**Comment by deekoder** [comment]
Will close.
