### ISSUE TITLE
[browser] Previous error message not cleared in browser

### ISSUE THREAD

**Issue by poornas** [minio/minio#4258]
After attempting to create a  bucket with invalid characters in bucket name, error message is displayed. This message is not cleared from the browser even after another Add bucket is attempted and it succeeds
## Expected Behavior

Error message should pertain to current user action
## Current Behavior

Error message not cleared out after user initiates new action
## Steps to Reproduce (for bugs)

1.  On minio browser, add a new bucket name with invalid characters.
2. Error message continues to be displayed even after user clicks create bucket button to create a different valid bucket.

## Your Environment

* Version used (`minio version`):  latest master
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
@poornas  is a screenshot possible?

**Comment by harshavardhana** [comment]
The error is never meant to be cleared..  you have to manually close it. @poornas

**Comment by poornas** [comment]
In that case, error message should be displayed as a modal so that user closes it before further UI interaction.

**Comment by harshavardhana** [comment]
> In that case, error message should be displayed as a modal so that user closes it before further UI interaction.

It is displayed as a modal there is a "close" button on the right hand side. @poornas - does it not display?

**Comment by poornas** [comment]
You will notice that the error message for foo/bar continues to be displayed even after "anotherbucket" was added and appears on the list of buckets. This is misleading.  A similar problem occurs when an object is selected  by a user for delete/download - the blue alert is displayed but when user changes his mind and instead goes to a different bucket, the UI continues to show the delete/display on the previously selected object. Attempting to click the Download all as zip  gives an operation not permitted error. While this is good, the better approach would be to clear the alert when user clicks away from the bucket

![screen shot 2017-05-04 at 2 38 26 pm](https://cloud.githubusercontent.com/assets/791968/25726171/c606aa9c-30d7-11e7-827b-1ffd8f957a81.png)

![screen shot 2017-05-04 at 2 45 53 pm](https://cloud.githubusercontent.com/assets/791968/25726467/27ae91c8-30d9-11e7-9135-027a25aac476.png)
![screen shot 2017-05-04 at 2 47 33 pm](https://cloud.githubusercontent.com/assets/791968/25726472/2ab271fa-30d9-11e7-90d4-897b6166db18.png)

**Comment by harshavardhana** [comment]
> You will notice that the error message for foo/bar continues to be displayed even after "anotherbucket" was added and appears on the list of buckets. This is misleading. A similar problem occurs when an object is selected by a user for delete/download - the blue alert is displayed but when user changes his mind and instead goes to a different bucket, the UI continues to show the delete/display on the previously selected object. Attempting to click the Download all as zip gives an operation not permitted error. While this is good, the better approach would be to clear the alert when user clicks away from the bucket

It is implemented in the present form as accepted behavior.  Because we would want to show the error until user acts on it. We shouldn't hide it because for the most part showing this error is important. 

Now if you didn't click the close button it is expected to see what you saw, it won't close automatically.

**Comment by deekoder** [comment]
- let us fix this in the new UX. No further action is needed.
