### ISSUE TITLE
[browser] Duplicate bucket policy rows  on double click

### ISSUE THREAD

**Issue by poornas** [minio/minio#4267]
## Expected Behavior

Double clicking on Bucket policy Add button creates duplicate rows with prefix * and ReadOnly action. Upon refreshing, only one row is retained with */ ReadOnly  [ Not sure if this is also a bug or fallback default]
## Current Behavior

1. Double clicking on Add button creates rows with * as prefix and ReadOnly as action. Adding one row with * /ReadOnly is ok, but this seems to be a bug -see screenshot.
2.  The cursor should be set to focus on the prefix input text element as well
## Possible Solution

Validate if policy and prefix were set to non-null values on submit of Add button.
## Steps to Reproduce (for bugs)

1.  Click on the ... (More) button on a bucket.
2. Double click on the Add button - this adds duplicate rows for prefix/action. This also is triggered sporadically by double clicking on the ... button to the right side of bucket name. 
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
![screen shot 2017-05-05 at 2 24 24 pm](https://cloud.githubusercontent.com/assets/791968/25764967/5243899a-319f-11e7-836e-711179d2492e.png)

**Comment by harshavardhana** [comment]
> Double clicking on Bucket policy Add button creates duplicate rows with prefix * and ReadOnly action. Upon refreshing, only one row is retained with */ ReadOnly [ Not sure if this is also a bug or fallback default]

This is a bug on browser side, server only applies one policy per prefix. So the redux is appending to the policy list without checking if the prefix was previously applied to.
