### ISSUE TITLE
Erasure codes with cloud providers

### ISSUE THREAD

**Issue by rc979** [minio/minio#4268]
Hi,

Can you please provide details on how to configure Minio's erasure codes mode with cloud storage backends? You have some information here https://docs.minio.io/docs/minio-erasure-code-quickstart-guide but just shows you how to do this with physical disks and not with cloud storage backends.

Thanks!

**Comment by harshavardhana** [comment]
> Can you please provide details on how to configure Minio's erasure codes mode with cloud storage backends? You have some information here https://docs.minio.io/docs/minio-erasure-code-quickstart-guide  but just shows you how to do this with physical disks and not with cloud storage backends.

What do you mean cloud storage backends? are you talking about gateway?

**Comment by rc979** [comment]
Yes. From that url that I pasted before it seems you can combine erasure codes with cloud storage, is that not the case?

**Comment by harshavardhana** [comment]
> Yes. From that url that I pasted before it seems you can combine erasure codes with cloud storage, is that not the case?

`minio server` is different than `minio gateway` . Minio server is only meant for physical disks. You can't use cloud storage backends.  `minio gateway` supports many different cloud storage backends. But it doesn't implement any erasure coding it is just a S3 proxy and writes to your remote cloud storage backend.

**Comment by rc979** [comment]
ok, thanks for clarifying.

**Comment by harshavardhana** [comment]
> ok, thanks for clarifying.

Closing this as answered.. feel free to open new issues @rc979 if you have more questions.
