### ISSUE TITLE
[browser] Share object validation error

### ISSUE THREAD

**Issue by poornas** [minio/minio#4269]
Share Object link should have validation to prevent entering invalid expiry date. See screenshot.
## Current Behavior

Allows select/enter - no validation to ensure valid max range for hours/mins/days
## Possible Solution

Validate max range
## Steps to Reproduce (for bugs)

1. On share object menu, manually enter invalid hours/mins/days then toggle up/down arrow.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
![screen shot 2017-05-05 at 2 55 58 pm](https://cloud.githubusercontent.com/assets/791968/25765801/b94ffaf2-31a3-11e7-957c-7a89ddf5fce4.png)

**Comment by deekoder** [comment]
Check if this can be closed?

**Comment by krishnasrinivas** [comment]
@deekoder you can lower the priority of the bug. Currently the fix committed is to make the fields read-only and allow changes only by clicking up/down buttons which allows the values to be in the configured range.

A better fix for the bug is form validation as pointed out by @poornas

**Comment by rushenn** [comment]
@krishnasrinivas I think it's better to close this issue and open a new one specifically for form validation (if required). Currently there is no need for any validation features as we don't have any forms other than 'share' to validate. May be we can address this in the new UI.

**Comment by krishnasrinivas** [comment]
@rushenn ok sure let's close this then. This is for the case when the user wants to set minutes to "30" he/she will have to click the up button 30 times. So you can take care of this in the new UI.

**Comment by harshavardhana** [comment]
> @rushenn ok sure let's close this then. This is for the case when the user wants to set minutes to "30" he/she will have to click the up button 30 times. So you can take care of this in the new UI.

@rushenn can you open a bug.. referencing this issue? Once its open we can close this issue.

**Comment by rushenn** [comment]
@harshavardhana done https://github.com/minio/minio/issues/4305

**Comment by harshavardhana** [comment]
Closing this issue..moved to #4305

**Comment by deekoder** [comment]
Reopening this issue. Since in testing release candidate user can still enter values in presigned URL invalid hours. We decided to disable user input and allow using the arrows. But this should not be confused with adding form validation. As an intermediate we decided to disable user input till the new ux addresses this comprehensively.
