### ISSUE TITLE
[gateway-gcs]: md5sum verification not being done

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4285]
In `func (l *gcsGateway) PutObject` does not do MD5 verification:

```
delete(metadata, "md5Sum")
```

client sent md5sum is being lost.

**Comment by nl5887** [comment]
Linked to issue minio/minio#4289.

**Comment by nl5887** [comment]
I thought we decided to removed checks of both md5 and sha256, but will add md5 check.

**Comment by krishnasrinivas** [comment]
@nl5887 aws-sdk will still send md5 which we need to verify

**Comment by hackintoshrao** [comment]
Does this particular case/test exist in Mint ?
