### ISSUE TITLE
[gateway-gcs]: Support for MakeBucketWithLocation

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4287]
```
        if err := bkt.Create(l.ctx, l.projectID, &storage.BucketAttrs{                                                                                                                   
                Location: "US",                                                                                                                                                          
        });
```

Currently location is hardcoded.

**Comment by deekoder** [comment]
related to #4241

**Comment by nl5887** [comment]
As discussed we're going to use the default server region as defined by MINIO_REGION.

**Comment by deekoder** [comment]
reverting the revert.

**Comment by hackintoshrao** [comment]
Does this particular case/test exist in Mint ?

**Comment by krishnasrinivas** [comment]
@hackintoshrao gateway and server behave differently with and without region config.

server/gateway with region configured: clients should create buckets in that region only
server/gateway with empty region: clients can create buckets in any region
