### ISSUE TITLE
performance: Analyze Memory allocations and consumption of Minio server.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#4291]
Analyze Memory allocations and consumption of Minio server in FS/XL/Distributed Modes. 

Building a simple plugin tool ( https://github.com/hackintoshrao/go-debug ) which works with Gorilla mux and sets up endpoints for getting lot of useful metrics from within the server.

Need to revisit the memory consumption patterns with various scenarios, 
- With and Without Cache 
- Analyze Distributed with a one/more nodes down.
- Observe the Mem profile for hotposts in both number of allocations and  total memory allocated.
- Observe the memory consumption patterns with [Chaos](https://github.com/minio/chaos/) test.
## Context

Analyzing memory consumption.

**Comment by hackintoshrao** [comment]
Rough working snippet https://gist.github.com/hackintoshrao/1c502d09075b87fc92fefef026dbf88a which can be plugged to return profiles, number of goroutines, stack trace, etc. Starting to test using this.  Will be working on identifying functions with more allocations, and writing tests and benchmarks for those functions and works towards reducing the number of allocations.

**Comment by hackintoshrao** [comment]
[test.pdf](https://github.com/minio/minio/files/1024224/test.pdf)
FS memory and allocation consuming pattern has been straight forward, nothing unusual, pretty simple.

**Comment by deekoder** [comment]
Will be addressed via new test framework.
