### ISSUE TITLE
[gateway-azure] Metadata is not passed to Azure

### ISSUE THREAD

**Issue by dennismulder** [minio/minio#4292]
when I execute the following command to put an object in Azure through the S3 api the metadata isn't set accordingly.

aws --endpoint-url http://<endpoint> s3api put-object --bucket test --key smallfile.txt --metadata firstname=dennis,lastname=mulder --body smallfile.txt

I also tried JSON:
aws --endpoint-url http://<endpoint> s3api put-object --bucket test --key smallfile.txt --metadata "{\"lastname\": \"mulder\"}" --body smallfile.txt

And when I put invalid JSON, it does throw an error:
Error parsing parameter '--metadata': Invalid JSON: Expecting object: line 1 column 21 (char 20)
JSON received: {"lastname": "mulder"

**Comment by krishnasrinivas** [comment]
Thanks @dennismulder we'll check.

**Comment by krishnasrinivas** [comment]
we need to convert:
```
X-Amz-Meta-Firstname: dennis
X-Amz-Meta-Lastname: mulder
```

to

```
X-Ms-Meta-Firstname: dennis
X-Ms-Meta-Lastname: mulder
```

and in the response headers perform similar conversion.
