### ISSUE TITLE
[gateway-s3] List Parts returns parts with ETag having doubled double quotes

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4294]
## Expected Behavior
ListParts returns 
```
...<Part><PartNumber>1</PartNumber
><LastModified>2017-05-08T18:53:09.031Z</LastModified><ETag>&#34;&#34;d9340f5267685ca716e86c33e570c12e&#34;&#34;</ETag><Size>67108864</Size></Part><Part>...
```

## Current Behavior
ListParts returns 
```
...<Part><PartNumber>1</PartNumber
><LastModified>2017-05-08T18:53:09.031Z</LastModified><ETag>&#34;d9340f5267685ca716e86c33e570c12e&#34;</ETag><Size>67108864</Size></Part><Part>...
```
## Steps to Reproduce (for bugs)
1. Setup a Minio gateway instance pointing to an S3 server
2. Setup a multipart upload and upload a part
3. List parts

(I did this with mc after tweaking some codes to the the gateway xml response)

## Context
Testing

## Your Environment
All, master

**Comment by vadmeste** [comment]
Taking this.

**Comment by vadmeste** [comment]
We should add a test in mint for this case

**Comment by harshavardhana** [comment]
> We should add a test in mint for this case

Perhaps open a bug over at mint so that we don't forget @vadmeste
