### ISSUE TITLE
s3verify repository missing

### ISSUE THREAD

**Issue by gaul** [minio/minio#4296]
Sorry to cross-post this, but the s3verify repository no longer exists:

https://github.com/minio/s3verify

Is this intentional?

**Comment by harshavardhana** [comment]
Yes it's deprecated.  We moved it to https://github.com/minio/attic

**Comment by gaul** [comment]
I am curious -- does minio still use s3verify or do you use another tool like s3-tests?

**Comment by harshavardhana** [comment]
> I am curious -- does minio still use s3verify or do you use another tool like s3-tests?

We started a new project as https://github.com/minio/mint which would perform s3verify style operations as a subset of tests which is still a work in progress.  We are not using s3verify anymore.
