### ISSUE TITLE
gateway: Validate object name

### ISSUE THREAD

**Issue by nl5887** [minio/minio#4300]
We need to pick a strategy here:

* do we want the backend to validate the object name and fail if it is invalid, possibly being incompatible with S3
* do we want to be compatible with S3 and validate object name following S3 standards, failing when it not complies

**Comment by krishnasrinivas** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

> The name for a key is a sequence of Unicode characters whose UTF-8 encoding is at most 1024 bytes long.

Since S3 does not impose any restrictions on the object name, the backend can decide if it allows it. For example our XL/FS layer does not allow object with name "/" whereas aws-s3 allows it.

**Comment by nl5887** [comment]
Oh yeah, I now see in the code this is a custom XMinioInvalidObjectName error that has been thrown by Mint. Will ignore this error.
