### ISSUE TITLE
Browser: Add form validation

### ISSUE THREAD

**Issue by rushenn** [minio/minio#4305]
Currently browser doesn't have any form validation features to validate any kind of form data such texts, numbers etc. 

## Expected Behavior
On form submit or form field key press, a proper feedback message should be given with a nice presentation UI. 

## Current Behavior
Form validation is ignored and handled alternative methods to overcome. 
e.g Read only fields in object share modal

## Possible Solution
https://github.com/0rangeT1ger/React-form-validator

## Context
https://github.com/minio/minio/issues/4269

**Comment by deekoder** [comment]
Related to #4313
