### ISSUE TITLE
Provide per release download URLs and SHA256 sums

### ISSUE THREAD

**Issue by danielsreichenbach** [minio/minio#4306]
## Expected Behavior
* for each release there should be a canonical download URL to allow for a managed installation, such as e.g <https://dl.minio.io/server/minio/release/TAG/linux-amd64/minio> where `TAG` would be the git tag for the release.
* provide a SHA256sum file for each release, e.g. e.g <https://dl.minio.io/server/minio/release/TAG/linux-amd64/minio.sha256sum> where `TAG` would be the git tag for the release.

## Current Behavior
* releases are available from generic URLs such as <https://dl.minio.io/server/minio/release/linux-amd64/minio>

## Context
Having just released a Puppet module for managing Minio (see https://github.com/kogitoapp/puppet-minio) I noticed that it is kind of hard to produce a stable installation state, as without a pairing of released version and checksum, you can never be sure that your Puppet managed installation is working.

Updated versions of Minio would be available from identical URLs with different checksums, thus rendering installs invalid and producing a Puppet error. Instead of this in Puppet context you want to be able to have a defined state as in tagged version with defined checksum.

**Comment by harshavardhana** [comment]
> releases are available from generic URLs such as https://dl.minio.io/server/minio/release/linux-amd64/minio

This is the current expected behavior and we are not planning to change that. Minio is designed with continuous deployment in mind. So there are are no releases or version numbers / migration downtimes etc. Each releases are just signified by a build id that is the date at which Minio was built. 

What you need is https://dl.minio.io/server/minio/release/linux-amd64/archive/ where each release is kept as 

```minio.<tagname>``` and its corresponding signature file ```minio.<tagname>.asc``` which can be used to validate the binary using gpg --armor. 

Each new release also gets itself copied into archive so that third-party tools such as yours work fine, can keep/generate a separate `minio.<tagname.sha256sum` if that helps.

**Comment by danielsreichenbach** [comment]
@harshavardhana I did not see the archive URL. Thanks for mentioning that. I will adapt the Puppet module to use this then.

**Comment by harshavardhana** [comment]
> @harshavardhana I did not see the archive URL. Thanks for mentioning that. I will adapt the Puppet module to use this then.

@danielsreichenbach let me know if you need `sha256sum` as well. Will add them tomorrow.. and shall incorporate them into the release process as well. 

Thanks for writing puppet-minio, feel free to mention it on https://github.com/minio/awesome-minio .

**Comment by danielsreichenbach** [comment]
`sha256sum` would be great as it's working out of the box for most use cases!

**Comment by danielsreichenbach** [comment]
Pushed the update in https://github.com/kogitoapp/puppet-minio/commit/6315ed5b92b439e4cebf81face643568e1b1f3aa, ping me when sha256sums are available.

Thanks for your help!

**Comment by harshavardhana** [comment]
> ping me when sha256sums are available.

sha256sums generated for all new and older releases. here is one sample https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2017-05-05T01-14-51Z.sha256sum

Please let us know if this is acceptable.

**Comment by danielsreichenbach** [comment]
Awesome, that's exactly what is needed. Will add support for grabbing these to the puppet module within the next days.
