### ISSUE TITLE
Dockerfile for Nano server

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4308]
## Expected Behavior
Having a dockerfile which downloads minio code from github and builds and ship it in a windows nano server image.

## Current Behavior
No such dockerfile

## Possible Solution
Writing a new dockerfile for that purpose.

## Steps to Reproduce (for bugs)
NA

## Context
Add docker support for Windows

## Your Environment
All

**Comment by deekoder** [comment]
who is asking for this? Is it a community ask?

**Comment by vadmeste** [comment]
> who is asking for this? Is it a community ask?

Yes. Someone from the community wanted to play with Minio Docker under Windows but we don't have an automatic way to build the image.

**Comment by vadmeste** [comment]
I can take this @deekoder, I already played with docker under Windows before.

**Comment by vadmeste** [comment]
Not really necessary.
