### ISSUE TITLE
Changing number input values in Expiry dialog does not get used

### ISSUE THREAD

**Issue by francoishill** [minio/minio#4313]
## Expected Behavior

When you open die "Share Object" dialog of a file in Minio Web UI the values in the number textboxes should be used to generate the "expiry link".

## Current Behavior

If you change the values by editing the input values (of Days, Hours or Minutes) "manually" it does not work at all. Whether using the mouse wheel to increase/decrease or by entering with a keyboard. On the flip side, the up/down arrows work as expected.

## Possible Solution

The numeric input values should also trigger same events as the up/down arrows.

## Steps to Reproduce (for bugs)

1. Browse to a running Minio web UI with an existing file
2. Click on the ellipsis menu on the right hand of a file and choose the "copy" icon to open the "Shared Object" dialog
3. Modify with keyboard or mouse wheel the value of any of the input boxed (Days, Hours, Minutes)
4. Click on "Copy Link" and inspect the `X-Amz-Expires` value in the URL, it still remains `432000` which was the initial value of 5 Days

## Context

This is an extreme security risk when copying Expiry links of objects/files. The link only expires after 5 days even though the user **thought** it would only expire after the duration he chose.

## Your Environment

* Version used (`minio version`): Installed golang version on commit `fa3f6d75b672059d52c4e676ec305c8d64c5f7ac`
* Environment name and version (e.g. nginx 1.9.1): Windows command-line with a raw directory
* Server type and version: Windows 10 Pro 64bit
* Operating System and version (`uname -a`): Windows 10 Pro 64bit
* Web browser: Chrome version `57.0.2987.133` 64bit

**Comment by harshavardhana** [comment]
The input UI has been disabled in the current master due to the fact that we don't have a proper form validation in place. @francoishill - we will bringing a new UI change which would address these concerns.

**Comment by poornas** [comment]
@deekoder, #4305 will address this issue.

**Comment by francoishill** [comment]
@harshavardhana, disabling the inputs should definitely reduce the risk **a lot**.

**Comment by deekoder** [comment]
Form validation is slated to come with the new UX.

**Comment by deekoder** [comment]
@deekoder check repro steps and see if this is still an issue.

**Comment by kannappanr** [comment]
@kaankabalak Can you please verify if this is fixed in the new ux. If not, we need to fix this issue.

**Comment by kaankabalak** [comment]
After testing, I was not able to reproduce this issue, as #4273, which makes input numbers read-only and only allows inputs through the up/down arrows, already solves this.

**Comment by kannappanr** [comment]
Closing this as fixed.
