### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by emresaracoglu** [minio/minio#4316]
Hi, 
Demo not working

Error:
`
TLS Not found - MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING
`

**Comment by vadmeste** [comment]
Thanks for reporting @emresaracoglu,

Yeah, I don't have this with Chrome but I was able to reproduce with Firefox. I'll investigate further.

**Comment by harshavardhana** [comment]
@emresaracoglu this seems like is a bug in Firefox to work with letsencrypt. We will see if we can generate a new set of certs with OCSP stapling disabled and test.

**Comment by emresaracoglu** [comment]
@harshavardhana Yes, the new certificate will solve this problem. This problem is not seen with any browser except Firefox. I can close the issue because you are aware of this problem.

**Comment by harshavardhana** [comment]
Fixed it by generating a new `certbot certonly --standalone --preferred-challenges tls-sni -d play.minio.io --staple-ocsp -m sysadmin@minio.io --agree-tos`  - ocsp stapled cert.  Firefox should work fine now.

**Comment by vadmeste** [comment]
Yes it works @harshavardhana, do we need to add staple ocsp feature to concert ?

**Comment by harshavardhana** [comment]
> Yes it works @harshavardhana, do we need to add staple ocsp feature to concert ?

Yes we need to .. currently the lego/acme library has no easier way to do it but we need to figure it. We can open a bug on minio/concert.

**Comment by emresaracoglu** [comment]
It's working right now 👍

**Comment by vadmeste** [comment]
Can we open this issue again? There is an opened PR being reviewed which fixes this.

**Comment by harshavardhana** [comment]
> Can we open this issue again? There is an opened PR being reviewed which fixes this.

Thanks @emresaracoglu @vadmeste
