### ISSUE TITLE
Bucket not showed due to use of some letters

### ISSUE THREAD

**Issue by tredoe** [minio/minio#4325]
The bucket is not showed when there is a directory with a letter in upper case or it has character '_' wich is valid for an URL.

## Steps to Reproduce (for bugs)
Under actual directory, create a directory like 'Test' and 'test_foo', and run `minio server .`

## Your Environment

* Version used (`minio version`): DEVELOPMENT.GOGET
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Linux 4.10.0-20-generic x86_64
* Link to your project:

**Comment by harshavardhana** [comment]
This is expected behavior .. bucket naming conventions are closer to AwS S3 behavior and we are not planning to change that in near future.

**Comment by deekoder** [comment]
Closing this. Please reopen if you think we have not addressed the issue.
