### ISSUE TITLE
Benchmark Minio with cosbench tool

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4326]
https://github.com/intel-cloud/cosbench - benchmark Minio using cosbench tool

- Read throughput
- Write throughput 
- Mixed workload.

**Comment by deekoder** [comment]
@NitishT can you write down the instructions on how to run this. @hackintoshrao is looking for the instructions.

**Comment by nitisht** [comment]
yes @deekoder will update the details on specific cases to @hackintoshrao

**Comment by deekoder** [comment]
Related to #4345

**Comment by harshavardhana** [comment]
https://github.com/minio/benchmarks repo is created with the final results, We can close this bug.
