### ISSUE TITLE
List bucket not listing gcs buckets on windows.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4331]
## Expected Behavior
mc ls gcs should show output but it does not

## Current Behavior
See Image
![mc_gcs_win](https://cloud.githubusercontent.com/assets/1700901/25976766/8f41a2b2-36a6-11e7-8a23-600744e7c91f.PNG)

## Steps to Reproduce (for bugs)
 Do this on windows server 2016 to see this error.

## Context
Unable to use gcs on windows platform. Actually i can't do anything without mc working with minio gateway on windows.
 
## Your Environment

* Version used (`minio version`): 
```
minio.exe version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: built from source
* Operating System and version (`uname -a`):  This may not help for windows 2016 server platform but here's what i get on git bash MINGW64_NT-10.0 EC2AMAZ-OH9HN9F 2.8.0(0.310/5/3) 2017-04-02 13:38 x86_64 Msys

* Link to your project:

**Comment by deekoder** [comment]
not a bug.

**Comment by harshavardhana** [comment]
> not a bug.

#notabug
