### ISSUE TITLE
Set the Cache-Control header based on the object metadata

### ISSUE THREAD

**Issue by laktek** [minio/minio#4341]
From a Slack conversation with Minio developers, I learnt currently Cache-Control metadata isn't set as an header when Minio is serving an object.

## Expected Behavior
Minio server should set the Cache-Control header based on the metadata provided.

**Comment by krishnasrinivas** [comment]
@laktek code for `cache-control` was available and should already work fine, can you let us know if it does not work?

**Comment by laktek** [comment]
Thanks! Will check.

**Comment by krishnasrinivas** [comment]
@deekoder do you want to close this? @laktek can re-open it if it does not work as expected.

**Comment by deekoder** [comment]
Please reopen if you think this issue has not been addressed.
