### ISSUE TITLE
Investigate a possible use of readahead library

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4342]
Check if https://github.com/klauspost/readahead can bring a performance enhancement

**Comment by deekoder** [comment]
Since this is an exploratory task moving this to prototype milestone.

**Comment by vadmeste** [comment]
- Using readahead inside posix doesn't have any effect (obviously) 
- Next step is to use it in object API handlers.

The problem with readahead is that it is creating a new goroutine with each read and we already trying to avoid that to support more concurrent connections.

**Comment by kannappanr** [comment]
Not required anymore.
