### ISSUE TITLE
Ctrl-C gives contradicting messages

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4348]
```
krishna@escape:~$ minio server export

Endpoint:  http://169.254.11.153:9000  http://10.0.0.115:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
AccessKey: SXO8VW2OFKKP2OG7AC85 
SecretKey: CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://169.254.11.153:9000  http://10.0.0.115:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://169.254.11.153:9000 SXO8VW2OFKKP2OG7AC85 CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 37 GiB Free, 92 GiB Total
^CGracefully stopping... (press Ctrl+C again to force)
krishna@escape:~$ 

```

Sending ctrl-C says `Gracefully stopping...` and then says `(press Ctrl+C again to force)` which are contradicting messages. It exits after just one ctrl-C.

**Comment by harshavardhana** [comment]
What is contradictory about this message? .

"Gracefully stopping..." indicates that server initiated a graceful stop and handled Ctrl-C

The next optional inside the () indicates that if pressed again server will stop by force.

This message was added to differentiate first Ctrl-C vs second Ctrl-C 

Can you also propose a newer string?

**Comment by krishnasrinivas** [comment]
Now I get it.

This is how the thought process went:
OK, Let me force a shutdown by doing Ctrl-C
`Gracefully stopping...` - OK, now minio is going to stop
`press Ctrl+C again to force` -  looks like minio is not going to stop and I have to press ctrl-C again

So, `press Ctrl+C again to force shutdown` would sound better

or even better just `Gracefully stopping...` or `Cleaning up...` is less confusing. User would try Ctrl-C again if he wants to interrupt it.

**Comment by donatello** [comment]
The first C-c should not be thought of as "force a shutdown" - this is not the usual use-case. The _first_ time C-c is pressed, the user is indicating an intent to shutdown the program - it is just "ok minio server - please stop now"; the user only wants to force shutdown in case it seems unresponsive - and often users attempt to do this by repeatedly pressing C-c. By printing the message we are giving feedback to the user that the program did pick up the C-c. Current behaviour is good.

(C-c = Ctrl + C in above, like in emacs notation).

**Comment by deekoder** [comment]
I press ctrl+c usually for getting my prompt back.  Usually servers just say "Exiting" and give me back the terminal prompt. This message shows after i got back my prompt. So  no need to tell me anything more please go ahead and shutdown gracefully.  If the prompt is not released then you can tell user please do Ctrl+C again.  Thats how i am used to server behaviors on macOS.

**Comment by krishnasrinivas** [comment]
If you are getting the message after the prompt then it's a bug.

**Comment by vadmeste** [comment]
@deekoder, I guess you tested `mc admin service restart` command before pressing Control-C. In that case, minio becomes unattached from the terminal input. I'll see what I can do.

**Comment by deekoder** [comment]
@vadmeste i sent PR for this, can you help verify it?

**Comment by krishnasrinivas** [comment]
https://github.com/minio/minio/pull/4428 PR addressing this issue

**Comment by rugved9713** [comment]
@krishnasrinivas : Could you please share any link or document where you have capture the ctrl C or any other kill signal ? I have to test my minio for graceful shutdown on dcos

**Comment by krishnasrinivas** [comment]
@rugved9713 you can refer to the code here: https://github.com/minio/minio/blob/master/cmd/signals.go#L72

We haven't documented signal handling. Minio stops accepting new connections and waits for 5 seconds for existing connections to finish up and exits.
