### ISSUE TITLE
Unable to list objects.

### ISSUE THREAD

**Issue by bearmoo-cloud-net** [minio/minio#4354]
On the console I am seeing this error:
5/12/2017 8:30:49 AMERRO[0592] Unable to list objects.                       cause=parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006" source=[bucket-handlers-listobjects.go:98:objectAPIHandlers.ListObjectsV2Handler()] stack=xl-v1-utils.go:262:readXLMetaStat xl-v1-metadata.go:285:xlObjects.readXLMetaStat xl-v1-object.go:337:xlObjects.getObjectInfo xl-v1-list-objects.go:89:xlObjects.listObjects xl-v1-list-objects.go:149:xlObjects.ListObjects <autogenerated>:1004:(*xlObjects).ListObjects bucket-handlers-listobjects.go:96:objectAPIHandlers.ListObjectsV2Handler api-router.go:77:(objectAPIHandlers).ListObjectsV2Handler-fm
5/12/2017 8:30:49 AMERRO[0593] Unable to list objects.                       cause=parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006" source=[bucket-handlers-listobjects.go:98:objectAPIHandlers.ListObjectsV2Handler()] stack=xl-v1-utils.go:262:readXLMetaStat xl-v1-metadata.go:285:xlObjects.readXLMetaStat xl-v1-object.go:337:xlObjects.getObjectInfo xl-v1-list-objects.go:89:xlObjects.listObjects xl-v1-list-objects.go:149:xlObjects.ListObjects <autogenerated>:1004:(*xlObjects).ListObjects bucket-handlers-listobjects.go:96:objectAPIHandlers.ListObjectsV2Handler api-router.go:77:(objectAPIHandlers).ListObjectsV2Handler-fm

## Expected Behavior

Not sure. Is it normal?

n/a
## Current Behavior

That is something I would like to know. Is there a way to debug it or enable logs?

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Version used (`minio version`): 
VERSION:
  2017-05-12T00:37:05Z
* Environment name and version (e.g. nginx 1.9.1):
Apache/2.4, minfs: 47a5474f28bc6a4291e4d2707f3c7c05594dd168db20cb1d052cc9417e4ba1be

* Server type and version:
vm:  CPU: 2.3 GHz,RAM: 1.66 GiB
* Operating System and version (`uname -a`): Centos 7.2 Core
* Link to your project:

**Comment by harshavardhana** [comment]
The error originates from this function where `stat.modTime` is being obtained.. 

```
func parseXLStat(xlMetaBuf []byte) (statInfo, error) {
         // obtain stat info.                                                                                                                     
         stat := statInfo{}
         // fetching modTime.                                                                                                                     
         modTime, err := time.Parse(time.RFC3339, gjson.GetBytes(xlMetaBuf, "stat.modTime").String())
         if err != nil {
                 return statInfo{}, err
         }
         stat.ModTime = modTime
         // obtain Stat.Size .                                                                                                                    
         stat.Size = gjson.GetBytes(xlMetaBuf, "stat.size").Int()
         return stat, nil
 }
```

Do you know exactly which file is giving this problem? how did you try to list? can you do `mc ls` on the prefix or object to see the same results?

**Comment by vadmeste** [comment]
Unable to decipher the origin of the problem yet, but I'll paste my findings:

* Listing objects does not check `format` and `version` fields of xl.json file
* xl.json should be already there, otherwise another error would be shown up (file not found)
* The following is the behavior of parseXLStat() function:
```
parseXLStat([]byte(`{"version":"1.0.0","format":"xl","stat":{"size":7,"modTime":"2017-05-19T12:55:12.663138264Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":8,"parity":8,"blockSize":10485760,"index":13,"distribution":[13,14,15,16,1,2,3,4,5,6,7,8,9,10,11,12],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"e8847244814d9bbd82d7b941679292c55153d5512fd12c0584f0599b11835c92bc91dafbd7a4413bfb4ed6cbeba54a74ea82142f24026eabadc54d4fedcb9381"}]},"minio":{"release":"DEVELOPMENT.GOGET"},"meta":{"content-type":"application/octet-stream","md5Sum":"9a0364b9e99bb480dd25e1f0284c8555"},"parts":[{"number":1,"name":"part.1","etag":"","size":7}]}`)) = _, <nil>
parseXLStat([]byte(`{"version":"1.0.0","format":"xl","stat":{"size":7}, "erasure":{}}`)) = _, parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
parseXLStat([]byte(`{"version":"1.0.0","format":"xl", "erasure":{}}`)) = _, parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
parseXLStat([]byte(`{"version":"1.0.0","format":"xl"}`)) = _, parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
parseXLStat([]byte(`{}`)) = _, parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
parseXLStat([]byte(``)) = _, parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
```
This shows that the error message, pasted by the author of this issue, can even happen if xl.json is empty.


So, can we imagine that there is a case where xl.json contains some json fields except `modTime` ? Personally, I can't. xlMetaV1 has Stat and ModTime fields, which both are static structs and not pointers. Marshelling an uninitialized (null) time.Time variable gives `0001-01-01T00:00:00Z`.

But on the other side, I can't see how we can have an empty xl.json, we are always marshelling a static xlMetaV1 struct, and not a pointer. Marsheling an initialized xlMetaV1 gives this `{"version":"","format":"","stat":{"size":0,"modTime":"0001-01-01T00:00:00Z"}, ......`

Any suggestions for more investigation ?

**Comment by deekoder** [comment]
@bearmoo-repo  could you help us reproduce the issue. We are not able to do root cause analysis.

**Comment by harshavardhana** [comment]
There is also a possibility that backend disk itself is corrupt in this scenario, getting kernel logs such as /var/log/kern.log or dmesg will help.

**Comment by krishnasrinivas** [comment]
@bearmoo-repo Do you know for what object this happens? if you know the object, then you can go to the backend directly and check the object's xl.json and paste the contents here.

(Along with kernel logs)

**Comment by fwessels** [comment]
We need some more info to be able to figure out what is going on -- waiting for further info...

**Comment by bearmoo-cloud-net** [comment]
Hi,

Unfortunately I am un able to reproduce the error. I will close this ticket.

**Comment by harshavardhana** [comment]
```
$ ansible -i hosts.d/zboxapp minio-servers -m command -a "ls /mnt/minioA/archiving-01/s3ql_data_23999/ -l" -f4
minio-03 | SUCCESS | rc=0 >>
total 16
-rw-r--r-- 1 minio minio 0 may 25 09:09 part.1
-rw-r--r-- 1 minio minio 0 may 25 09:09 xl.json

minio-04 | SUCCESS | rc=0 >>
total 16
-rw-r--r-- 1 minio minio 0 may 25 09:09 part.1
-rw-r--r-- 1 minio minio 0 may 25 09:09 xl.json

minio-02 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 May 25 09:09 part.1
-rw-r--r-- 1 minio minio   888 May 25 09:09 xl.json

minio-01 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 may 25 09:09 part.1
-rw-r--r-- 1 minio minio   887 may 25 09:09 xl.json
```

vadmeste [12:49 PM] 
minioA is disk 1 @pbruna? what about the two other disks ?

pbruna [12:50 PM] 
second disk

[12:50] 
 ```$ ansible -i hosts.d/zboxapp minio-servers -m command -a "ls /mnt/minioB/archiving-01/s3ql_data_23999/ -l" -f4
minio-03 | SUCCESS | rc=0 >>
total 16
-rw-r--r-- 1 minio minio 0 may 25 09:09 part.1
-rw-r--r-- 1 minio minio 0 may 25 09:09 xl.json

minio-04 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 may 25 09:09 part.1
-rw-r--r-- 1 minio minio   887 may 25 09:09 xl.json

minio-02 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 May 25 09:09 part.1
-rw-r--r-- 1 minio minio   887 May 25 09:09 xl.json

minio-01 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 may 25 09:09 part.1
-rw-r--r-- 1 minio minio   888 may 25 09:09 xl.json
```

[12:51] 
third disk
``` ansible -i hosts.d/zboxapp minio-servers -m command -a "ls /mnt/minioC/archiving-01/s3ql_data_23999/ -l" -f4
minio-04 | SUCCESS | rc=0 >>
total 16
-rw-r--r-- 1 minio minio 0 may 25 09:09 part.1
-rw-r--r-- 1 minio minio 0 may 25 09:09 xl.json

minio-03 | SUCCESS | rc=0 >>
total 16
-rw-r--r-- 1 minio minio 0 may 25 09:09 part.1
-rw-r--r-- 1 minio minio 0 may 25 09:09 xl.json

minio-01 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 may 25 09:09 part.1
-rw-r--r-- 1 minio minio   888 may 25 09:09 xl.json

minio-02 | SUCCESS | rc=0 >>
total 20
-rw-r--r-- 1 minio minio 15880 May 25 09:09 part.1
-rw-r--r-- 1 minio minio   887 May 25 09:09 xl.json```
```

```
pbruna [11:59 AM] 
Power when off
```

Copying from the #general discussion.

**Comment by deekoder** [comment]
This may be a different bug from the original one. Because xl.json and parts are empty. Need additional info from @harshavardhana on if they are the same issue.

**Comment by harshavardhana** [comment]
> This may be a different bug from the original one. Because xl.json and parts are empty. Need additional info from @harshavardhana on if they are the same issue.

Actually its the same issue @deekoder even with `xl.json` being empty the listObjects() only tries to read StatInfo of the xl.json without validating the version part of the `xl.json`.
