### ISSUE TITLE
How I can install on my VM without Docker

### ISSUE THREAD

**Issue by emresaracoglu** [minio/minio#4356]
Hi again,

How I can install on my VM without Docker?

CentOS 7

**Comment by harshavardhana** [comment]
> How I can install on my VM without Docker?

You can download the relevant binary from https://dl.minio.io/server/minio/release/

**Comment by emresaracoglu** [comment]
I think this question is simple for you;
I already installed it with the Docker but I'm curious about this installation method - This is not image file or `rpm`.. 

```
$ wget https://dl.minio.io/server/minio/release/linux-amd64/minio.RELEASE.2017-05-05T01-14-51Z
$ ... ?
```
How does such a file install into existence?
#
Also, I getting this error: 

`Minio server is unreachable`

Colsole:
```
[root@server5 ~]# docker run -p 9000:9000 minio/minio server /export
Created minio configuration file successfully at /root/.minio

Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
AccessKey: UIFS6X5NQQY5ZZAC401Q
SecretKey: F0e/4mWc/lv5Lu9R4ReY+QeCB3RvP7MRp1bzhaoF
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://172.17.0.2:9000 UIFS6X5NQQY5ZZAC401Q F0e/                                                                                                                                                             4mWc/lv5Lu9R4ReY+QeCB3RvP7MRp1bzhaoF

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 42 GiB Free, 50 GiB Total
time="2017-05-17T21:26:21Z" level=error msg="Unable to login request from 192.16                                                                                                                                                             8.1.1:64618" cause="Invalid access key, access key should be 5 to 20 characters                                                                                                                                                              in length" source="[web-handlers.go:346:(*webAPIHandlers).Login()]"
```
_PS: http://172.17.0.2:9000 it's not my public IP_
Where's the error?

#Update
When I close Putty Shell, then the connection is disconnected with Minio. I see

**Comment by harshavardhana** [comment]
First you need to do these things

- If you are running docker you don't need to download minio binary again. 
- if you are running docker you should run with `docker run -d` to deamonize it so that when you kill your terminal it stays there. 
- To download the binary the right link is https://dl.minio.io/server/minio/release/linux-amd64/minio - this is referenced already at multiple places in our README.md, docs.minio.io and also our website https://minio.io . There is no need to download the binary with the tagged filename.

**Comment by emresaracoglu** [comment]
I see now, **thank you** for your time @harshavardhana !
