### ISSUE TITLE
How to list Objects in a Bucket ?

### ISSUE THREAD

**Issue by kiranshashiny** [minio/minio#4358]
I was able to successfully make a bucket and put an object i.e a zip file, using the makeBucket API.

But when I try to listObjects () and get that from the bucket   I get nothing back !

## Expected Behavior

I was hoping to see the 'name', 'size', 'lastModified' and so on, when I called the 'listObjects".

## Current Behavior
Nothing is returned back , when I use the API in your documentation.

## Steps to Reproduce (for bugs)

1.  Two pieces of code are attached , one is where I upload the object ( i.e the zip file) and next is where I m trying to list it .

Code where I am in

fileUploader.js

    var Minio = require('minio')

    // Instantiate the minio client with the endpoint
    // and access keys as shown below.
    var minioClient = new Minio.Client({
    endPoint: 'play.minio.io',
    port: 9000,
    secure: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
    });

    // File that needs to be uploaded.
    var file = 'sat-practice-test-7.zip'

    // Make a bucket called europetrip.
    minioClient.makeBucket('asiatrip', 'us-east-1', function(err) {
    if (err) return console.log(err)

    console.log('Bucket created successfully in "us-east-1".')

    // Using fPutObject API upload your file to the bucket europetrip.
    minioClient.fPutObject('europetrip', 'sat-practice-test-7.zip', file, 'application/octet-stream',         function(err, etag) {
      if (err) return console.log(err)
      console.log('File uploaded successfully.')
        });
    });

Code to list the objects in the bucket:

     var Minio = require('minio')

    // Instantiate the minio client with the endpoint
    // and access keys as shown below.
    var minioClient = new Minio.Client({
        endPoint: 'play.minio.io',
        port: 9000,
        secure: true,
        accessKey: 'Q3AM3UQ867SPQQA43P2F',
        secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
    });

    // List buckets - shows my bucket.  [ My note: the bucket 'asiatrip' shows up ]

    minioClient.listBuckets(function(err, buckets) { 
      if (err) return console.log(err)
      console.log('buckets :', buckets)
    })

    console.log ("list objects in the bucket, this is where I dont see any output like name,size, modified etc " );

    var stream = minioClient.listObjects('asiatrip','', true)
    stream.on('data', function(obj) { console.log(obj) } )
    stream.on('error', function(err) { console.log(err) } )

Results from running the script: ( note the first line 'asiatrip' is in buckets list. )

    $ node listbuckets.js 
    buckets : [ { name: 'asiatrip',
        creationDate: Wed May 17 2017 15:10:19 GMT+0530 (IST) },
      { name: 'bkp',
        creationDate: Wed May 17 2017 08:08:28 GMT+0530 (IST) },
      { name: 'europetrip',
        creationDate: Wed May 17 2017 15:10:34 GMT+0530 (IST) },
      { name: 'hdhd',
    creationDate: Wed May 17 2017 08:38:46 GMT+0530 (IST) },
      { name: 'sbiger',
    creationDate: Wed May 17 2017 11:56:41 GMT+0530 (IST) },
      { name: 'test',
    creationDate: Wed May 17 2017 08:08:34 GMT+0530 (IST) },
      { name: 'testbucket',
    creationDate: Wed May 17 2017 16:16:57 GMT+0530 (IST) } ]

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by krisis** [comment]
@kiranshashiny Could you provide the snippet of code you use to perform `listObjects` on the bucket where you uploaded your object? The above snippet uploads an object but doesn't perform `listObjects`.

**Comment by kiranshashiny** [comment]
@krisis  - done - Sorry was in the middle of edits when your note came in.

I tried listObjectV2 as well.
BTW : I am on Mac OS - Sierra.

    node -v  
    v4.8.2

    $ npm list |grep minio
    ├─┬ minio@3.1.3

**Comment by krisis** [comment]
@kiranshashiny You have uploaded file into `europetrip` bucket. See below the relevant section from your snippet.

```javascript
// Using fPutObject API upload your file to the bucket europetrip.
minioClient.fPutObject('europetrip', 'sat-practice-test-7.zip', file, 'application/octet-stream',         function(err, etag) {
  if (err) return console.log(err)
  console.log('File uploaded successfully.')
    });
});
```

**Comment by krisis** [comment]
You can see your uploaded file in `play.minio.io` using `mc ls play/europetrip`.

**Comment by kiranshashiny** [comment]
@krisis  - thanks - I think I got it.

yes, it was initially set to europetrip, when I uploaded it -and then I think I created the 'asiatrip' as well. 
My Typo !   Sorry 
and Thanks.

**Comment by kiranshashiny** [comment]
Now, is there no REST APIs to PUT , GET, DELETE and so on  ?

**Comment by krisis** [comment]
@kiranshashiny Could you close this issue? You can join us on https://slack.minio.io/ to know more about minio and its SDKs.

**Comment by kiranshashiny** [comment]
Thanks  @krisis  - Closing it.
