### ISSUE TITLE
Disable expiry date for file shares

### ISSUE THREAD

**Issue by emanuelstanciu** [minio/minio#4365]
I can see a lot of use cases where having a forced expiry date is useful, however, I am using it for local dev work and I would like to share files permanently.
How can I disable this altogether?

Thanks,
Emanuel

**Comment by krishnasrinivas** [comment]
@emanuelstanciu Use bucket policies for this: https://docs.minio.io/docs/minio-client-complete-guide#policy

`mc policy download myminio/mybucket` will make the entire bucket read-only for anonymous access.

`mc policy download myminio/mybucket/prefix/` will make files in `prefix/` read-only for anonymous access.

**Comment by krishnasrinivas** [comment]
@emanuelstanciu let us know if you have more questions, you can also join our slack channel https://slack.minio.io

**Comment by deekoder** [comment]
Please reopen this issue if you think the above question is not resolved.

**Comment by happybydefault** [comment]
What if I have `domain.com/data/diagnosis/alice.pdf` and `domain.com/data/diagnosis/bob.pdf`, and I need to email them their diagnosis link but I don't want to allow Bob to try to download Alice's diagnosis?

It would be awesome to have the flexibility to set whatever expiration time that's needed, even infinite.

Is there something you can do about this issue?

**Comment by harshavardhana** [comment]
> What if I have `domain.com/data/diagnosis/alice.pdf` and `domain.com/data/diagnosis/bob.pdf`, and I need to email them their diagnosis link but I don't want to allow Bob to try to download Alice's diagnosis?
> 

We don't have multi-user concept to provide this behavior. 

> It would be awesome to have the flexibility to set whatever expiration time that's needed, even infinite.
> 
> Is there something you can do about this issue?

It is not possible @amulecregg, unfortunately, we are following AWS S3 specification here and we are compatible.

**Comment by happybydefault** [comment]
@harshavardhana OK, I understand. Thank you, anyway!
