### ISSUE TITLE
Need for a document explaining scaling of minio

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4366]
https://github.com/minio/minio/issues/4364

`How can I extend the storage size after deployment?` is a common question on #channel and GH issues, it will be good to have a document providing explanation.

**Comment by donatello** [comment]
@krishnasrinivas Remove extraneous `explaining` in title?

**Comment by deekoder** [comment]
Please refer to
https://docs.minio.io/docs/minio-deployment-quickstart-guide

**Comment by abessifi** [comment]
From https://docs.minio.io/docs/minio-deployment-quickstart-guide:
>MinIO is built ground up on the cloud-native premise. With features like erasure-coding, distributed and 
>shared setup, it focuses only on storage and does it very well. While, it can be scaled by just replicating 
>MinIO instances per tenant via an orchestration platform.

@deekoder please correct me if I'm wrong, does the above mean that to increase an existing cluster storage capacity we just have to scale minio horizontally by adding new instances (an instance in this case is a minio service running on a new host with new disks) ?

I'm sorry if I ask about this, but I'm a bit confused especially after reading [this](https://github.com/minio/minio/issues/5901#issuecomment-387380087).

**Comment by krishnasrinivas** [comment]
@abessifi we updated our scaling document, please refer to: https://docs.min.io/docs/minio-federation-quickstart-guide.html

Here are some points to note:
* minio uses coredns/etcd to federate multiple minio clusters into a single large namespace
* a bucket is always restricted to just one cluster. i.e a bucket can not grow beyond a cluster
