### ISSUE TITLE
Query on User creation for buckets

### ISSUE THREAD

**Issue by wingZero21** [minio/minio#4372]
Hi,

Do you know if its currently possible to create buckets that are also assigned to a specific user? 

I am struggling to find anything that shows the ability to create users for minio.

**Comment by harshavardhana** [comment]
There is no concept of users on Minio .  There is one access and secret per server.  If you need to isolate multiple tenants you should look at https://docs.minio.io/docs/multi-tenant-minio-deployment-guide

**Comment by deekoder** [comment]
We are working on integrating with systems which have user management (ldap/AD/kerberos). It's in our roadmap. Closing this issue.

**Comment by maxozerov** [comment]
Hm, I am writing in a closed Issue, but I did not find any more info about User Management (ldap/AD/kerberos) and Minio. Please, Could you remind or maybe already have open Issue about LDAP? it (User Management) will be in future releases?

**Comment by harshavardhana** [comment]
> Hm, I am writing in a closed Issue, but I did not find any more info about User Management (ldap/AD/kerberos) and Minio. Please, Could you remind or maybe already have open Issue about LDAP? it (User Management) will be in future releases?

Currently, there is no user management it's going to arrive in its first form in https://github.com/minio/minio/pull/6168
