### ISSUE TITLE
Upload via web hangs at completion

### ISSUE THREAD

**Issue by jcoetzee** [minio/minio#4375]
When uploading to a bucket via the web interface the upload hangs just before completion.

## Expected Behavior
File uploaded to bucket

## Current Behavior
1. Upload hangs at ~100%
2. Upon refreshing the page the file is not present in the bucket

![screen shot 2017-05-19 at 10 19 03 pm](https://cloud.githubusercontent.com/assets/1784961/26265468/850ca6c0-3ce1-11e7-91c4-8f070a910572.png)

## Steps to Reproduce (for bugs)
1. Upload file to bucket via web interface.

## Your Environment
* Version used (`minio version`): 2017-05-05T01:14:51Z
* Environment name and version (e.g. nginx 1.9.1): Docker 17.05.0-ce.
* Operating System and version (`uname -a`): Ubuntu 16.04.2 LTS. Linux 4.4.0-78

**Comment by deekoder** [comment]
Can you tell us the file size? Can you share `mc ls` output on the bucket where you uploaded the object.

**Comment by krishnasrinivas** [comment]
@jcoetzee it works fine for me (docker 2017-05-05T01:14:51Z) with Chrome browser. What browser are you using?

**Comment by deekoder** [comment]
I will close this @jcoetzee  since we are not able to proceed with the repro. Please reopen if you think this issue is still happening for you.

**Comment by jcoetzee** [comment]
Apologies, this fell off my radar and I forgot to reply.

I did some investigation. This bug isn't present when hitting minio directly but rather when using nginx as a reverse proxy. Running nginx 1.13.1.

My nginx config (which as I understand is similar to the minio docs):

    server {
        listen 8443 ssl http2;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256'; 
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security max-age=15768000;

        ssl_client_certificate /etc/ssl/root_ca.pem;
        ssl_verify_client on;
        ssl_verify_depth 2;
        
        server_name minio.domain.tld;
        ssl_certificate /etc/ssl/minio/minio.domain.tld.pem;
        ssl_certificate_key /etc/ssl/minio/minio.domain.tld.key;

        location / {
                proxy_buffering off;
                proxy_pass http://minio:9000;
                proxy_redirect http://minio:9000 https://minio.domain.tld/;
                proxy_cache proxy_cache;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-for $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_read_timeout 600;
                port_in_redirect off;
        }
    }

I have tried turning both http2 and proxy_cache off and still experience the problem.

As for file sizes, it works with very small files (order of 80 kb) but a 1.7MB pptx fails.

I've upgraded to latest minio (2017-06-13T19:01:01Z) btw.

**Comment by jcoetzee** [comment]
Should I open a new issue for this?

**Comment by harshavardhana** [comment]
Sure @jcoetzee

**Comment by Lewiscowles1986** [comment]
Just in-case this helps anyone else

```
# minio.localhost
server {
	server_name minio.localhost;
	listen 80;

    ignore_invalid_headers off;
    client_max_body_size 0;
    proxy_buffering off;

	access_log /var/log/nginx/access.log vhost;
	location / {
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_read_timeout 15m; # Default value is 60s which is not sufficient for MinIO.
        proxy_send_timeout 15m; # Default value is 60s which is not sufficient for MinIO.
        proxy_request_buffering off; # Disable any internal request bufferring.
		proxy_pass http://minio:9000;
	}
}
```

works for me to proxy `minio` (in a docker container) via nginx as `minio.localhost`

This is in the docs at https://docs.min.io/docs/setup-nginx-proxy-with-minio.html
