### ISSUE TITLE
[gateway-gcs] Prefix in listing incomplete uploads doesn't have effect

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4380]
## Expected Behavior
To be able to list all incomplete uploads having some prefix.

## Current Behavior
Listing incomplete uploads always list all uploads.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1.
```
 package main
 
 import (
         "fmt"
         "log"
 
        "github.com/minio/minio-go"
 )

 
 func main() {
         s3Client, err := minio.New("localhost:9000", "minio", "minio123", false)
         if err != nil {
                 log.Fatalln(err)
         }
 
         doneCh := make(chan struct{})
         defer close(doneCh)
 
         for multipartObject := range s3Client.ListIncompleteUploads("vadmeste", "randomprefix",
                 false, doneCh) {
                 if multipartObject.Err != nil {
                         fmt.Println(multipartObject.Err)
                         return
                 }
                 fmt.Println(multipartObject)
         }
         return
 }
````

The above code always shows all incomplete uploads disregarding any provided prefix.

## Context
Testing GCS.

## Your Environment
All

**Comment by hackintoshrao** [comment]
We need to add this to functional test cases.

**Comment by harshavardhana** [comment]
> We need to add this to functional test cases.

Gateway has no functional tests on minio server side, this needs to go into mint
