### ISSUE TITLE
Drop root user in Docker image

### ISSUE THREAD

**Issue by andrewklau** [minio/minio#4381]
I would like to be able to drop the root user in the Minio docker image

## Expected Behavior
```
FROM minio/minio
adduser -u 1000 -G root default
USER default
```

## Current Behavior
Permission denied on the volume /export

It is not possible to change the permissions on an existing volume except in the base image and at run time.

## Possible Solution

There are a few solutions:

- Add a minio user and chown the volume:
https://github.com/docker-library/redis/blob/master/3.2/alpine/Dockerfile#L4
https://github.com/docker-library/redis/blob/master/3.2/alpine/Dockerfile#L47

- Simply chmod 777 /export

## Context

Docker recommends running containers without root. On some platforms like openshift, the ability to run containers as root are heavily restricted.

**Comment by nitisht** [comment]
Discussed with @abperiasamy . We'll continue to support existing deployments by running as root. For new deployments we'll drop the root privileges and start as user `minio:minio`. 

`chown` on startup is not a good option due to sheer amount of data in existing deployments. 

Changes need to be done accordingly in our Dockerfile.

**Comment by andrewklau** [comment]
How will we detect if it is a new deployment or existing deployment?

**Comment by nitisht** [comment]
@andrewklau please take a look at #4877

**Comment by gjonespf** [comment]
Any chance the UID/GID can be set via env var or similar, with a default like you are already using (190)?  Would be good for instances where minio needs to be run on an already owned volume that can't be changed.  Currently have an image to do just this.

**Comment by deekoder** [comment]
@nitisht  can you bring the WIP PR to review for this?

**Comment by kannappanr** [comment]
Will not be implementing this now, so closing it for now.
