### ISSUE TITLE
Can't explicitly tell minio to serve on 0.0.0.0

### ISSUE THREAD

**Issue by stephenreay** [minio/minio#4382]
Passing `--address 0.0.0.0:9000` to the `serve` command causes Minio to exit with an error:

## Expected Behaviour
Minio should bind on all local addresses, as it does when no `--address` is specified or `--address :port` is specified.

## Current Behaviour
Minio refuses to start with an `--address` flag using `0.0.0.0` for the IP portion. It will error with:

> FATA[0000] Invalid address ‘0.0.0.0:9000’ in command line argument.  cause=host in server address should be this server source=[server-main.go:138:serverHandleCmdArgs()]

## Steps to Reproduce (for bugs)

Run `minio server --address "0.0.0.0:9000" /path/to/storage`

## Context
Configuring minio as a dependency in a project means identifying the address to listen on in each environment (e.g. dev might be 0.0.0.0 for debugging purposes, prod might be 127.0.0.1). The current situation requires special-casing the 0.0.0.0 address when populating a configuration file for the minio system service

## Your Environment
* Version used (`minio version`): 2017-05-05T01:14:51Z
* Operating System and version (`name -a`): Linux gunstrader 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Thanks for opening the bug - surely looks like a newly introduced bug, its a regression @stephenreay

**Comment by balamurugana** [comment]
@stephenreay I am sure the case `--address=0.0.0.0:9000` is missed out in the validation? However `--address=:9000` should work with the same behavior.  Does it work for you?

**Comment by stephenreay** [comment]
Yes, omitting the ip has the correct behaviour.
