### ISSUE TITLE
recursive remove objects expects Content-MD5 with valid SHA256 hash sent.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4383]
`Content-MD5` might not be sent when a valid SHA-256 hash is sent on requests.  recursive remove objects returns `MissingContentMD5` which is wrong in this case.

## Expected Behavior

It should work

## Current Behavior

returns error `MissingContentMD5`

## Steps to Reproduce (for bugs)
1. Run minio-java functional test

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Refer: https://github.com/minio/minio-java/issues/579

**Comment by harshavardhana** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html

According to the spec its required 

```Finally, the Content-MD5 header is required for all Multi-Object Delete requests. Amazon S3 uses the header value to ensure that your request body has not be altered in transit.```

http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html#multiobjectdeleteapi-requests

**Comment by harshavardhana** [comment]
There is a bug in minio-java with HTTPS POST request is setting the Content-Md5 properly 

```
---------START-HTTP---------
POST /?delete= HTTP/1.1
Content-MD5: kxNeXSd3f6lJscy4ILj3jg==
Host: minio-java-test-o00itb.s3.amazonaws.com
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20170522T014803Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170522/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
x-amz-id-2: gRGDZJ0N74ugJWnOCZpTuwGbH8qq8diWnculGi6jIvWmvuCwn2VQxhsqACSA1UCmYSY0U5Mwkqk=
x-amz-request-id: 8AC9B7B3E19AD14B
Date: Mon, 22 May 2017 01:48:04 GMT
Connection: close
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3
```

This is why it works with S3 and play.minio.io as @vadmeste mentioned. Whereas with HTTP request doesn't set the value at all. 

```
---------START-HTTP---------
POST /minio-java-test-2e53q7m?delete= HTTP/1.1
Host: 10.0.0.13:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: f7e76c307f009af5ea42ad52b148ae953c6e1bb300e51b548501d986b68b50b0
x-amz-date: 20170522T015115Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170522/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 400
Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-05-18T23-58-35Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14C0CAA2710661DF
Date: Mon, 22 May 2017 01:51:15 GMT
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MissingContentMD5</Code><Message>Missing required header for this request: Content-Md5.</Message><Key></Key><BucketName></BucketName><Resource>/minio-java-test-2e53q7m</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
----------END-HTTP----------
```

Now if i remove setting Content-Md5 for AWS S3, S3 is returning a proper error here. 

```
---------START-HTTP---------
POST /?delete= HTTP/1.1
Host: minio-java-test-3kk0m0a.s3.amazonaws.com
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20170522T015312Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170522/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 400
x-amz-request-id: 172CCBF65C769B34
x-amz-id-2: W+M6kEcSKinAiTJEG5KCbvIks150zO6Gn4kic43b53MzbWYICWCl0Br0o+wS9/e3xKgpCicWWak=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 22 May 2017 01:53:12 GMT
Connection: close
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: Content-MD5</Message><RequestId>172CCBF65C769B34</RequestId><HostId>W+M6kEcSKinAiTJEG5KCbvIks150zO6Gn4kic43b53MzbWYICWCl0Br0o+wS9/e3xKgpCicWWak=</HostId></Error>
----------END-HTTP----------
```

So it is a bug in minio-java, please close this bug and re-open the bug in minio-java.

**Comment by balamurugana** [comment]
Irrespective of spec mandates `Content-MD5`, the test passes with Amazon AWS S3 ie without `Content-MD5` header

**Comment by harshavardhana** [comment]
> Irrespective of spec mandates Content-MD5, the test passes with Amazon AWS S3 ie without Content-MD5 header

How does the test pass? i just showed you it doesn't. @balamurugana

**Comment by harshavardhana** [comment]
It works with AWS S3 because we are setting Content-Md5 see the trace output. @balamurugana

**Comment by balamurugana** [comment]
I see below case is hit for Amazon AWS S3 and play.minio.io
```
     - For HTTPS (secure) request, SHA-256 hash is set to "UNSIGNED-PAYLOAD" and
       MD5 hash is calculated.
```

The logic I was told below is wrong in some cases like multiobject delete
```
     - For HTTPS (secure) request, SHA-256 hash is set to "UNSIGNED-PAYLOAD" and
       MD5 hash is calculated.
```

This is not minio server issue.
