### ISSUE TITLE
minio gateway help instead of error

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4390]
```
minio gateway gcs
FATA[0000] Access and secret keys are mandatory to run Minio gateway server.  cause=Missing credentials source=[gateway-main.go:113:mustGetGatewayConfigFromEnv()]
```

**Comment by deekoder** [comment]
Same thing for this : 
```
MINIO_ACCESS_KEY=<> MINIO_SECRET_KEY=<> minio gateway gcs 
FATA[0000] Unable to initialize gateway layer            cause=ProjectID expected source=[gateway-main.go:209:gatewayMain()]
```
shows the above error. Instead say project id is expected in a better way.   FATA[0000] etc should go.

**Comment by deekoder** [comment]
@vadmeste  you were going to verify this to help close.

**Comment by vadmeste** [comment]
yes @deekoder,

> Show help instead of log message. Log messages are shown only after server starts. For input validation pretty print message & do not show log messaging.

@deekoder, shall we print help or pretty message for input validation? little confused.

**Comment by deekoder** [comment]
We should do the latter here. This is what i see 
```
 MINIO_ACCESS_KEY=<> MINIO_SECRET_KEY=<> ./minio gateway gcs asfasffd

               *** Warning: Not Ready for Production ***
FATA[0000] Unable to initialize gateway layer            cause=unknown project id source=[gateway-main.go:323:gatewayMain()]
```
I think unknown project id is more apt. We can fix presentation of this error when we fix all log/error messages.

**Comment by deekoder** [comment]
If i do ```minio gateway gcs ``` without project id it does show help. So I will close this.
