### ISSUE TITLE
No indication to user that they need to login to gcs

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4391]
There is no way to know for the user that they have to do 
```
gcloud beta auth application-default login
```
## Expected Behavior
 Error message should have above command to reauth or gcloud init if the administrator is setting minio with gcs for the first time.

## Current Behavior
fails without accurate error message

## Possible Solution
Have custom error messages for GCS or the usability is significantly harder to figure out.

## Steps to Reproduce (for bugs)
1. Don't login to gcs and try to do any bucket/object operations. 

## Context
 Testing

## Your Environment

* Version used (`minio version`): minio gateway gcs branch
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: 
* Operating System and version (`uname -a`): Darwin macOS
* Link to your project:

**Comment by krishnasrinivas** [comment]
There is a better way to authenticate for an application like minio.

When users want to deploy minio gateway on VMs or using docker containers we can't expect them to do "gloud init" the deployment would have to be automated/scriptable.

https://cloud.google.com/storage/docs/authentication the section `Other Environments` points to https://developers.google.com/identity/protocols/application-default-credentials#howtheywork which has instructions on how to use `GOOGLE_APPLICATION_CREDENTIALS` This is most suitable for applications like minio.

I have edited the help message accordingly. We can use the same way for our testing as well, i.e the admin will have to generate and give us credentials.json for testing.

and:
```
export GOOGLE_APPLICATION_CREDENTIALS=/home/krishna/Downloads/miniotest-d4530e7be663.json
minio gateway gcs miniotesting
```

```

**Comment by nitisht** [comment]
This is an example: https://gist.github.com/NitishT/ae31e00695788f55f498c5534b35c29f#run-gcs-gateway-on-docker

**Comment by krishnasrinivas** [comment]
@NitishT ah cool, you had figured it out. For the GCS document for community we can write the document not requiring them to install google cloud sdk and generate using `gcloud beta auth application-default login` instead we can provide instructions on how to generate credentials.json from the google cloud console UI. It will be easier.

**Comment by nitisht** [comment]
Yes, just the `projectid` is required and user should login using `gcloud beta auth application-default login` and set the `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by krishnasrinivas** [comment]
@NitishT I meant it's better to provide instructions to generate credentials.json from GCS web console, not `gcloud login` as users don't have to install gcloud to generate credentials.json

**Comment by nitisht** [comment]
ahh I see @krishnasrinivas agreed. We can probably have both the ways mentioned in the doc.

**Comment by donatello** [comment]
The gcs gateway works even when `GOOGLE_APPLICATION_CREDENTIALS` is not set - by looking up some local configuration files. These files are created via `gcloud` commands. Since this also is a way to get it to work, we need to document both.

**Comment by krishnasrinivas** [comment]
@donatello yes, I thought about it but it will be too confusing to give multiple options. Hence chose the most suitable option from minio's perspective. Typically users will deploy gateway in either VM or docker and not on their laptop/dekstops. Hence `GOOGLE_APPLICATION_CREDENTIALS` based approach is suitable to deploy minio gateway.

But we can improve it when we fix https://github.com/minio/minio/issues/4457
