### ISSUE TITLE
docs support

### ISSUE THREAD

**Issue by timchenxiaoyu** [minio/minio#4394]
I don‘t know how minio work，how to storage data，the  arch of minio ,the component how to communicate ,and so on .some detail about the design.

**Comment by timchenxiaoyu** [comment]
maybe need developer docs ,make more people to join this

**Comment by timchenxiaoyu** [comment]
how to storage metadata? detail about Erasure Code

**Comment by deekoder** [comment]
hi tim all these details are available at https://docs.minio.io

**Comment by timchenxiaoyu** [comment]
I know the  https://docs.minio.io,but it is not incomplete ,we need more detail about minio ,not how to use it

**Comment by deekoder** [comment]
hi tim can you help describe what topics you would like to see in the docs and is details are missing.

**Comment by deekoder** [comment]
Tim i am closing this issue. Please feel free to join us at https://minio.slack.com/ where we will be able to chat about any specific questions on how to use minio further (not already published on our docs). You will have to put your email address and invite yourself to join our channel.
