### ISSUE TITLE
[gateway-gcs] Empty ETag returned during  a Put object call 

### ISSUE THREAD

**Issue by poornas** [minio/minio#4397]
## Expected Behavior

Running a gcs server locally  and uploading a  78.23Mb file to a bucket using python SDK. Expect script to complete successfully.
## Current Behavior

python script crashes because ETag returned by gcs gateway is empty. minio-python sdk expects a nonempty ETag in CompleteMultipartUpload method. Note that the file upload works ok with mc command line.
## Possible Solution

No idea. However server log doesn't show any errors.

## Steps to Reproduce (for bugs)

1. Start minio gateway gcs server locally
2. Run a fput_object call with gcs credentials from minio-py sdk for a large object
3. The SDK crashes because of missing Etag

$ python3 make_bucket.py
received data b'<?xml version="1.0" encoding="UTF-8"?>\n<CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>/aquaduck1/object2</Location><Bucket>aquaduck1</Bucket><Key>object2</Key><ETag></ETag> </CompleteMultipartUploadResult>'   <=== xml returned by gateway GCS
None
Traceback (most recent call last):
  File "make_bucket.py", line 37, in <module>
    '/Users/krispy/Downloads/opencv-3.2.0.zip', content_type='application/zip')
  File "/Users/krispy/GMinio/minio-py/minio/api.py", line 687, in fput_object
    uploaded_parts)
  File "/Users/krispy/GMinio/minio-py/minio/api.py", line 1753, in _complete_multipart_upload
    return parse_multipart_upload_result(response.data)
  File "/Users/krispy/GMinio/minio-py/minio/parsers.py", line 162, in parse_multipart_upload_result
    root.get_etag_elem()
  File "/Users/krispy/GMinio/minio-py/minio/parsers.py", line 127, in get_etag_elem
    return self.get_child_text('ETag', strict).replace('"', '')
AttributeError: 'NoneType' object has no attribute 'replace'

==same upload from mc ==
$ mc cp ~/Downloads/opencv-3.2.0.zip gcs2/aquaduck1 
...opencv-3.2.0.zip:  78.23 MB / 78.23 MB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 2.27 MB/s 34s

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
Version: 2017-05-23T00:51:58Z
Release-Tag: DEVELOPMENT.2017-05-23T00-51-58Z
Commit-ID: 2659ff77b65e30224f73e805e1f49c11f5ba17a5

minio-py sdk from master commit a60bf9336aa3d20308c563356ffbed94fed95cd0

**Comment by harshavardhana** [comment]
> Running a gcs server locally and uploading a 78.23Mb file to a bucket using python SDK. Expect script to complete successfully.

This should be fixed in the latest `feature-gcs`
