### ISSUE TITLE
Taking Backups of MinIO

### ISSUE THREAD

**Issue by seafoodbuffet** [minio/minio#4398]
I want to acknowledge that this already closed issue (https://github.com/minio/minio/issues/4135) asked the same question, but I wanted to expand on this topic and go more in-depth.

All of the documentation links that @harshavardhana suggested seem to be about backing up data INTO minio. While I understand the general point that you could use those tools to backup minio's data directory into another s3-type store, I wanted to ask some specific questions about this.

Mirroring solutions do a good job of providing a literal copy of the current state of the object store. However, that doesn't protect against accidental deletion, overwrite, and doesn't allow you to go backwards in time. I'm wondering how to achieve those things as well.

Let's say I have a MinIO server or perhaps distributed servers using Erasure Coding. 

Starting with the simple case, can I safely use file-system backup tools to backup MinIO's storage directory while MinIO is running? Are all writes by MinIO atomic and consistent? What happens if the backup happens while a bucket is being updated? Will the backup still be usable?

Expanding further, what happens if I now have three servers setup using erasure coding? Can backups on the servers happen while they are all running? How would you ensure consistency? For example, if the server clocks are slightly off and backups begin at minutely different times, will the backup still be usable?

**Comment by deekoder** [comment]
@seafoodbuffet would you be able to come to our slack channel? You can invite yourself  at slack.minio.io

**Comment by krishnasrinivas** [comment]
> While I understand the general point that you could use those tools to backup minio's data directory into another s3-type store

You can take backup from S3 (minio) to local-disk too.

It is advised not to touch the backend Filesystem when minio is doing IO.

**Comment by seafoodbuffet** [comment]
To update this issue, I exchanged messages with @krishnasrinivas and here's some conclusions.

1. In general it is NOT safe to access the backend file system when minio could be doing I/O
2. This is doubly true for setups using distributed / erasure coding since consistency across nodes/disks is a huge issue.
3. What we'll likely end up doing for backup is using `mc `mirror` to put a copy of the objectstore into the local filesystem and then backup/snapshot that filesystem using our tools of choice (SAN/EBS/LVM snapshot and/or bacula, etc)

The exception to the above would be using minfs, the FUSE driver. Presumably, it would be possible to expose the objectstore via minfs and use filesystem-based backup solutions on that as well.

**Comment by benyanke** [comment]
I'd also put in a plug for something like ZFS - this would allow transparent backups using snapshots. Also provides transparent checksums for bitrot protection, as well as transparent compression.

**Comment by ieugen** [comment]
Any changes for this? We plan to use minio for storing some app data in lots of buckets  and we would like to backup those buckets individually ( one per tenant). 

We might end up wirh thousands of buckets that we need to backup. What strategy would be applied in rgis case since I imagine mirroring is not a very good solution ?!

**Comment by harshavardhana** [comment]
There are no changes , there is already a solution use `mc mirror`  mirror can mirror many buckets.

**Comment by harshavardhana** [comment]
Feel free to join our slack at https://slack.minio.io for further discussion on this topic..

**Comment by seafoodbuffet** [comment]
We eventually ended up with an mc mirror solution. The issue is that mirror isn't the same as a backup. mirror doesn't protect against accidental deletion or data corruption.

We didn't do this but I could imagine a solution in which you mirror your primary copy to a secondary, and then take cold backups off of the secondary.

**Comment by ieugen** [comment]
Thank you. It seems pretty reasonable considering the capabilities.
