### ISSUE TITLE
[gateway-gcs] PutObjectPart returns zero modified timestamp

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4400]
PutObjectPart returns:

```
{
  "PartNumber": 2,
  "LastModified": "0001-01-01T00:00:00Z",
  "ETag": "73c2ee0acb590362c0ac3740f8c39523",
  "Size": 2284
}
```

  "LastModified": "0001-01-01T00:00:00Z", <---- zero

**Comment by krisis** [comment]
@krishnasrinivas did you use minio-go to reproduce this issue? It looks like minio-go's Core type doesn't extract lastModified time of an object from PutObjectPart response. The server is returning lastModifiedTime as expected. This issue can be closed.

**Comment by harshavardhana** [comment]
> "LastModified": "0001-01-01T00:00:00Z", <---- zero

LastModified is never returned by any PUT or POST operations in AWS S3.  In-fact its a bug in minio-go which is keeping a frivolous field in the struct and which has always been empty.

**Comment by krisis** [comment]
@harshavardhana Makes sense. Then we can remove the following snippet of code in `gcsGateway.PutObject`, right?

```go
	attrs, err := object.Attrs(l.ctx)
	if err != nil {
		return ObjectInfo{}, gcsToObjectError(traceError(err), bucket, key)
	}
```

**Comment by krishnasrinivas** [comment]
@krisis this code snippet is used for returning etag (md5sum)

**Comment by harshavardhana** [comment]
> @harshavardhana Makes sense. Then we can remove the following snippet of code in gcsGateway.PutObject, right?
> 
> 	attrs, err := object.Attrs(l.ctx)
> 	if err != nil {
> 		return ObjectInfo{}, gcsToObjectError(traceError(err), bucket, key)
> 	}

No we need to just get rid of LastModified from ObjectPart struct in minio-go. @krisis

**Comment by krishnasrinivas** [comment]
Closing this then
