### ISSUE TITLE
Minio browser and mc should accept kerberos provisioned usernames and work with GCS backend

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4407]
User must be able to user their provisioned kerberos provisioned username/passwords into minio browser and mc. The backend would be GCS in this scenario.

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/tree/sts initial work which should work with GCS as well.

**Comment by harshavardhana** [comment]
With the new design `Federator` is a separate project. We can close this bug.

**Comment by harshavardhana** [comment]
Work has moved to https://github.com/minio/federator closing this bug.
