### ISSUE TITLE
[gateway] Implement ListObjectsV2 anonymous support

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4413]
As of now object-handlers.go's ListV2 handler handles the V2 request, hence anonymous requests are not served for ListV2 in gateway mode.

Also we can add ListObjectsV2 to GatewayLayer interface.

**Comment by nitisht** [comment]
Don't close it yet. Need to send another PR for the GCS branch.

**Comment by deekoder** [comment]
Can this be closed now @NitishT

**Comment by harshavardhana** [comment]
> Can this be closed now @NitishT

GCS branch is not yet merged i think.

**Comment by nitisht** [comment]
Can be closed now.

**Comment by harshavardhana** [comment]
Fixed in master
