### ISSUE TITLE
Can't create a subfolder in a bucket using the web interface.

### ISSUE THREAD

**Issue by SaimonL** [minio/minio#4423]
Can't create a subfolder in a bucket using the web interface.

**Comment by harshavardhana** [comment]
Please follow the issue template @SaimonL - we cannot understand what is needed and what is not working if you don't provide us basic information.

It helps us triage internally.

**Comment by deekoder** [comment]
I think this is by design @SaimonL

**Comment by deekoder** [comment]
Closing this as this behavior is Minio compatible. Please reopen if you think this needs to be addressed.
