### ISSUE TITLE
Head request on existing folder  in a bucket returns 404

### ISSUE THREAD

**Issue by Yurmusp** [minio/minio#4434]
Head request on existing folder  in root of a bucket returns 404.
While it shall return 200 or may be other code that confirms existence of a folder.
Bucket rights are rw/public.

I use django-minio-storage with Django 
and try to subsitute S3 for local testing.
Our existing code fails with issue caused by above.
I debugged an digged and found that minio returns 404 error code
where it shall return OK code.

Internally it tries to do "stat" on folder 
static.bucket/admin

My debug dump from inside of _url_open method
looks like this.

Response NOT success. Status = 404 target url = http://localhost:9000/static.bucket/admin. Headers: {'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'host': u'localhost:9000', 'authorization': 'AWS4-HMAC-SHA256 Credential=username/20170526/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=80cd2514bb98232cbcd13ae2cd5f70ada296e16b2ddd1ad894c587a5db80245a', 'x-amz-date': '20170526T003958Z', 'user-agent': 'Minio (Linux; x86_64) minio-py/2.2.2'}
Raising exception with method HEAD

## Expected Behavior

It shall return 200 code

## Current Behavior

It returns 404 status code

## Possible Solution

I think Head request for folder is not properly implemented and there is no proper test case for it.
I'm not absolutely sure, but that's what I think.

## Steps to Reproduce (for bugs)

Create bucket
Create folder with subfolders and files
Send head request for a folder as in example above.
it shall fail with returning 404 like folder does not exist.
However, folder exists and return code shall be different.

I think what I described above is easier than replicating my setup with 
Django and django-minio-storage
1.
2.
3.
4.

## Context

Replace S3 with Minio for local testing with Django project.
Probably, one of popular uses for Minio if it would work.

## Your Environment

* Version used (`minio version`):
Latest downloaded at minio site link few days ago.
Version: 2017-05-05T01:14:51Z
Release-Tag: RELEASE.2017-05-05T01-14-51Z
Commit-ID: 40985cc4e3eec06b7ea82dc34c8d907fd2e7aa12

* Environment name and version (e.g. nginx 1.9.1):
Ubuntu 14.04 x86_64

* Server type and version:
Vagrant VM

* Operating System and version (`uname -a`):
Linux localdev 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
This is expected @Yurmusp and as per design, there is no directory concept on Minio. You should not perform a HeadObject() without specifying a right object name.

**Comment by Yurmusp** [comment]
So, if somebody needs  to check if folder exists, how he shall do it?

**Comment by harshavardhana** [comment]
> So, if somebody needs to check if folder exists, how he shall do it?

You don't need to there is no such concept as directories, they are just prefix. They don't exist independently of objects.  You can just upload with the path directly.  Minio is a flat namespace and not a POSIX filesystem - conceptually there are no directories, only prefixes exist - which only exist because they have an object associated with it. 

A good way to avoid these things and be optimal is look at how `mc cp` does this https://github.com/minio/mc constructs properly the filesystem paths to be replicated to remote object storage. `mc` makes file-system look like object storage not the other way around.

**Comment by Yurmusp** [comment]
Hmm, I see.

**Comment by harshavardhana** [comment]
@Yurmusp btw have you looked at https://github.com/maddevsio/django_minio ?

**Comment by Yurmusp** [comment]
Yes. It is much less functional than the one I use. It only saves it. I already checked it. Thank you for suggestion.

**Comment by deekoder** [comment]
Thank @Yurmusp  we will close this issue then.

**Comment by cgarciaarellano** [comment]
Just hit the same issue trying to use minio to replace s3. We also do the same, explicitly create directories (ie key name terminated with "/") and then later on we do a head request on the object. 

In the trace this looks like this:

```
172.19.0.2 [REQUEST s3.PutObject] 04:07:27.920
172.19.0.2 PUT /testbucket/testdir/
172.19.0.2 Host: 172.19.0.2
172.19.0.2 User-Agent: aws-sdk-cpp/......
172.19.0.2 X-Amz-Content-Sha256: ...
172.19.0.2 X-Amz-Date: 20191126T040727Z
172.19.0.2 Accept: */*
172.19.0.2 Authorization: AWS4-HMAC-SHA256 Credential=.../20191126/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=...
172.19.0.2 Content-Length: 0
172.19.0.2 Content-Type: binary/octet-stream
172.19.0.2 <BODY>
172.19.0.2 [RESPONSE] [04:07:27.925] [ Duration 5.567ms  <U+1F809> 97 B  <U+1F80B> 259 B ]
172.19.0.2 200 OK
172.19.0.2 X-Amz-Request-Id: 15DA9AD2576694B2
172.19.0.2 X-Xss-Protection: 1; mode=block
172.19.0.2 Accept-Ranges: bytes
172.19.0.2 Content-Length: 0
172.19.0.2 Content-Security-Policy: block-all-mixed-content
172.19.0.2 ETag: "d41d8cd98f00b204e9800998ecf8427e"
172.19.0.2 Server: MinIO/RELEASE.2019-10-12T01-39-57Z
172.19.0.2 Vary: Origin
172.19.0.2 <BODY>
```

and then when we do the head request we see this

```
172.19.0.2 [REQUEST s3.HeadObject] 04:14:52.632
172.19.0.2 HEAD /testbucket/testdir/
172.19.0.2 Host: 172.19.0.2:9000
172.19.0.2 User-Agent: aws-cli/...
172.19.0.2 X-Amz-Content-Sha256: ...
172.19.0.2 X-Amz-Date: 20191126T041452Z
172.19.0.2 Accept-Encoding: identity
172.19.0.2 Authorization: AWS4-HMAC-SHA256 Credential=.../20191126/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=...
172.19.0.2 Content-Length: 0
172.19.0.2
172.19.0.2 [RESPONSE] [04:14:52.633] [ Duration 1.309ms  <U+1F809> 93 B  <U+1F80B> 225 B ]
172.19.0.2 404 Not Found
172.19.0.2 Content-Security-Policy: block-all-mixed-content
172.19.0.2 Server: MinIO/RELEASE.2019-10-12T01-39-57Z
172.19.0.2 Vary: Origin
172.19.0.2 X-Amz-Request-Id: 15DA9B39E2532518
172.19.0.2 X-Xss-Protection: 1; mode=block
172.19.0.2 Accept-Ranges: bytes
172.19.0.2 Content-Length: 0
```
