### ISSUE TITLE
Fix helm/universe Minio icons

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4439]
## Expected Behavior
Minio logo should be rendered properly. 

## Current Behavior
- Minio logo in DC/OS universe package is good quality. Needs to be reviewed and fixed.
-- https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/M/minio/5/resource.json#L3-L5
- Minio logo in K8S helm package is not rendered 
-- https://kubeapps.com/charts/stable/minio
-- https://github.com/kubernetes/charts/blob/master/stable/minio/Chart.yaml#L10

## Possible Solution
Review and fix image logos. 

## Context
Minio logos should be rendered properly in orchestration system packages.

**Comment by nitisht** [comment]
Sent PR for Kubernetes logo: https://github.com/kubernetes/charts/pull/1233

**Comment by belvid** [comment]
[minio icons universe.zip](https://github.com/minio/minio/files/1075793/minio.icons.universe.zip)
[Updated set]

Minio icons retina set for mesosphere.

@harshavardhana Can you upload them to https://minio.io/img/icons/minio/

**Comment by harshavardhana** [comment]
> minio icons universe.zip
> [Updated set]
> 
> Minio icons retina set for mesosphere.
> 
> @harshavardhana Can you upload them to https://minio.io/img/icons/minio/

Its done! - closing.
