### ISSUE TITLE
Fix StorageClass in Kubernetes examples and Helm package

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4440]
## Expected Behavior
Kubernetes examples `.yaml` files and Helm package should work on local clusters (non cloud-provider setup)

## Current Behavior
Minio not launching on local k8s clusters

## Possible Solution
Helm package and `.yaml` file examples should work seamlessly on local k8s clusters. Fix `StorageClass`.

## Context
Minio on Kubernetes

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kesavkolla** [comment]
I'm using Kuberentes 1.6.4 local cluster with a Persistent Volume created.  The Persistent Volume is configured to use hostPath for local mounts.  The helm installation get's stcuk with exception of 
`
 SchedulerPredicates failed due to PersistentVolumeClaim is not bound
`

I'm using minio chart version of `0.1.1`

**Comment by nitisht** [comment]
@kesavkolla how is your Kubernetes cluster configured - how many nodes, which OS?

**Comment by kesavkolla** [comment]
My kuberentes cluster is configured with two nodes.  One node runs master and another node is a worker node.  The master node is tainted so it can also provision pods.

Host OS is Ubuntu

**Comment by nitisht** [comment]
Thanks @kesavkolla

**Comment by nitisht** [comment]
Minio Helm chart and Kubernetes examples use `default` storage class by not specifying a `storageClass` section. Read more [here](http://blog.kubernetes.io/2017/03/dynamic-provisioning-and-storage-classes-kubernetes.html). 

Quoting above post 

> To reduce the burden of setting up default StorageClasses in a cluster, beginning with 1.6, Kubernetes installs (via the add-on manager) default storage classes for several cloud providers. To use these default StorageClasses, users do not need refer to them by name – that is, storageClassName need not be specified in the PVC.

To the end user this means 

- If you have you K8s cluster on a cloud provider (eg  AWS/GCE/Azure), and you install Minio using [Helm chart](github.com/kubernetes/charts/tree/master/stable/minio) or [Minio-K8S deployment docs](https://docs.minio.io/docs/deploy-minio-on-kubernetes), dynamic provisioning will kick in and create persistent volumes matching Minio's persistent volume claims (if there is no matching persistent volume available). 

- If you have k8s cluster on other infrastructure, and you install Minio using [Helm chart](github.com/kubernetes/charts/tree/master/stable/minio) or [Minio-K8S deployment docs](https://docs.minio.io/docs/deploy-minio-on-kubernetes), dynamic provisioning of persistent volumes may not happen, leaving you with errors like `failed to bind`. In this case, you as the cluster-administrator should provision persistent volumes required for Minio deployment. 

Bundling only PVCs with an application configuration is in inline with [best practices](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration) recommended by Kubernetes project. Read more on persistent volumes here - https://kubernetes.io/docs/concepts/storage/persistent-volumes

To conclude, there is nothing to be changed from Minio configuration side. So, the issue can be closed.

**Comment by harshavardhana** [comment]
Closing this based https://github.com/minio/minio/issues/4440#issuecomment-308593718
