### ISSUE TITLE
[gateway-gcs] Not validating given project id at start up leads to weird client error

### ISSUE THREAD

**Issue by donatello** [minio/minio#4449]
When given an invalid project id, minio gcs gateway just starts up without any validation.

When a client makes a request, errors are returned by server that do not reflect the problem.

Bug surfaced while debugging https://github.com/minio/mc/issues/2162

## Expected Behavior

Options below:

1. Gateway at startup should do some request to check that the backend is reachable, valid and working fine, (this behaviour makes sure that the environment/backend is sane).
2. Return errors about backend being unavailable when client requests are received. (This behaviour probably breaks s3 protocol - but it may be needed as the backend can go down at any time).

## Current Behavior

No validation is done at startup.

Vague errors are returned on client requests.

## Possible Solution

No Idea

## Steps to Reproduce (for bugs)

1. Start minio gateway like so:
```
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway gcs invalidprojid

Endpoint:  http://192.168.1.121:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add mygcs http://192.168.1.121:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

2. With mc try to list with command and you get error:

```
$ mc ls myminio
mc: <ERROR> Unable to list folder. The specified bucket is not valid.
```

3. On server you get error like:
```
ERRO[0002] Unable to list buckets.                       cause=Bucket name invalid:  source=[bucket-handlers.go:213:objectAPIHandlers.ListBucketsHandler()] stack=home/aditya/Code/goenv-1.7.5/workspace/src/github.com/minio/minio/cmd/gateway-gcs.go:268:(*gcsGateway).ListBuckets home/aditya/Code/goenv-1.7.5/workspace/src/github.com/minio/minio/cmd/bucket-handlers.go:211:objectAPIHandlers.ListBucketsHandler home/aditya/Code/goenv-1.7.5/workspace/src/github.com/minio/minio/cmd/api-router.go:100:(objectAPIHandlers).ListBucketsHandler-fm
ERRO[0002] Unable to list buckets.                       cause=Bucket name invalid:  source=[bucket-handlers.go:213:objectAPIHandlers.ListBucketsHandler()] stack=home/aditya/Code/goenv-1.7.5/workspace/src/github.com/minio/minio/cmd/gateway-gcs.go:268:(*gcsGateway).ListBuckets home/aditya/Code/goenv-1.7.5/workspace/src/github.com/minio/minio/cmd/bucket-handlers.go:211:objectAPIHandlers.ListBucketsHandler home/aditya/Code/goenv-1.7.5/workspace/src/github.com/minio/minio/cmd/api-router.go:100:(objectAPIHandlers).ListBucketsHandler-fm

```

4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
> Gateway at startup should do some request to check that the backend is reachable, valid and working fine, (this behaviour makes sure that the environment/backend is sane).

This we need to anycase @donatello - we are not doing this right now.

**Comment by deekoder** [comment]
@vadmeste  did you already not fix this ?

**Comment by vadmeste** [comment]
> @vadmeste did you already not fix this ?

I sent a PR that only validates the project id format but not if the project id does really exist. I'll do that now.
