### ISSUE TITLE
Unable to create a bucket with two Minio instances (4 disks) + self-signed certificates

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4451]
It is a weird behavior and I could be missing something but I was not able to create a bucket in my two Minio instances when https is enabled. It works if I disable https. I saw that the code is blocked in bucket  namespace lock (https://github.com/minio/minio/blob/master/cmd/bucket-handlers.go#L388)

It is important to test first and see if you can reproduce it.  

## Expected Behavior
To be able to create a bucket in a cluster of two Minio instances

## Current Behavior
mc mb doesn't respond. Code blocks in https://github.com/minio/minio/blob/master/cmd/bucket-handlers.go#L388

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Prepare two self signed certificates
2. Run two instances of Minio servers, each instance contains two disks, both are configured with tls certificates. Do not forget to copy public certificates in CAs directory of both instances.
3. mc mb myminio/testbucket

## Context
Testing

## Your Environment
- master
- Ubuntu 16.04
- Bare metal

**Comment by harshavardhana** [comment]
> Prepare two self signed certificates

How did you generate self signed certificates?

**Comment by harshavardhana** [comment]
I am able to run this successfully 

```
mc mb --insecure --debug local/testbucket2
mc: <DEBUG> PUT /testbucket2/ HTTP/1.1
Host: localhost:9004
User-Agent: Minio (linux; amd64) minio-go/2.0.4 mc/2017-05-30T21:02:34Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170530T235037Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Tue, 30 May 2017 23:50:37 GMT
Location: /testbucket2
Server: Minio/DEVELOPMENT.2017-05-30T23-47-19Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14C3874644BF0252

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: organization
mc: <DEBUG>  >> Expires: 2027-05-28 23:48:48 +0000 UTC
mc: <DEBUG> Response Time:  32.830523ms

Bucket created successfully `local/testbucket2`.
```

```
$(minio server --address localhost:9001 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4)&
$(minio server --address localhost:9002 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4)&
$(minio server --address localhost:9003 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4)&
minio server --address localhost:9004 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4
```

```
openssl genrsa -out private.key 2048
openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=localhost"
```

**Comment by harshavardhana** [comment]
Changed the `http://` for remote disks to `https://` 

```
#!/bin/bash

$(minio server --address localhost:9001 https://localhost:9001/tmp/1 https://localhost:9002/tmp/2 https://localhost:9003/tmp/3 https://localhost:9004/tmp/4)&
$(minio server --address localhost:9002 https://localhost:9001/tmp/1 https://localhost:9002/tmp/2 https://localhost:9003/tmp/3 https://localhost:9004/tmp/4)&
$(minio server --address localhost:9003 https://localhost:9001/tmp/1 https://localhost:9002/tmp/2 https://localhost:9003/tmp/3 https://localhost:9004/tmp/4)&
minio server --address localhost:9004 https://localhost:9001/tmp/1 https://localhost:9002/tmp/2 https://localhost:9003/tmp/3 https://localhost:9004/tmp/4
```

This also works @vadmeste .  what is the running port @vadmeste for you?

**Comment by vadmeste** [comment]
I am testing with m{1..3} servers and not with localhost. I am really seeing this issue. So after cluster initialization, I am not to able to create a bucket. I added some log in the code and as I said, the server is blocking in one lock call. I was not able to reproduce with docker.

**Comment by vadmeste** [comment]
OKay, I've finally understood it.

I enabled DSYNC_LOG (export DSYNC_LOG=1), dsync client was calling rpc of the same local server. The following is the dysnc log:
```
2017/05/31 04:52:46 Unable to call RLock dial-http minio2:9002/minio/lock/tmp/vadmeste/d2: x509: certificate signed by unknown authority
```

I wasn't putting the public certificate of the local server under ~/.minio/certs/CAs/ which is quite unusual to do.

I think it is better if we make the server loads server's public certificate for client connections.

**Comment by harshavardhana** [comment]
How did you create certs ? Is your domain part of your cert generation ?

**Comment by vadmeste** [comment]
> How did you create certs ? Is your domain part of your cert generation ?

```
openssl genrsa -out private.key 2048
openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=minio2"
```

**Comment by vadmeste** [comment]
I generated several certs with the following domain names: minio2, minio3 and I tested using m2 and m3 servers.

**Comment by harshavardhana** [comment]
Yeah if you didn't put the public.crt in the CAs then you need to have insecureSkipVerify on @vadmeste . So I would say it's a setup issue. 

But we should fail early on in this scenario do know how the initial connection worked / got established .

**Comment by vadmeste** [comment]
> But we should fail early on in this scenario do know how the initial connection worked / got established .

Let me repeat my point.

To correctly have this setup working (especially for dsync to work), we need to put public certificates of *all* nodes in CAs/ directory, the thing that wasn't obvious even for me. When I tested, I put public certificates of all *other* nodes in .minio/certs/CAs and I excluded the public certificate of the current node because it already exists in ~/.minio/certs/

Does this make sense ?

**Comment by harshavardhana** [comment]
Yes it doesn't because that would make it an inconsistent setup. When there is n-n connection we shouldn't think like that.

In any case we need to error out early on.

**Comment by deekoder** [comment]
If this is a user error please advise.

**Comment by harshavardhana** [comment]
> If this is a user error please advise.

It is a user error, but we are not validating the environment properly - in-fact we end up starting the server but fail later.

**Comment by donatello** [comment]
In #4465, an attempt to fix this issue is present - we eliminate the problem of making the CA cert of the server as a trusted root certificate on that server. The lock RPC is refactored in this change so that when making local requests it skips using the network.

@vadmeste - could you help test that change?
