### ISSUE TITLE
Update useragent string to indicate where minio was installed on

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4456]
This would be very helpful for debugging and supportability.

**Comment by balamurugana** [comment]
@deekoder does this mean you want below as user agent for all ReST replies?
```
Minio (<OS>; <ARCH>[; docker][; source])  Minio/<VERSION> Minio/<RELEASE-TAG> Minio/<COMMIT-ID>
```

If so, you could update the description properly.

**Comment by deekoder** [comment]
ETA: 2017-06-08 EOD

**Comment by harshavardhana** [comment]
Helm support added by #4592

**Comment by nitisht** [comment]
Corresponding Helm package changes done by https://github.com/kubernetes/charts/pull/1304
