### ISSUE TITLE
Policies are not shared between all instances of minio

### ISSUE THREAD

**Issue by dreh23** [minio/minio#4458]
Problem:
Bucket policy is just set to one instance

Expected:
Shared state of policy.

Environment:
We are running a nomad/consul cluster with 3 docker instances of minio:latest and a fabio load balancer. All minio instances mount the same storage endpoint into the container. The load balancers are using round robin to route to minio and are set as a TLS endpoint.

If I change bucket policy to public:

```
mc policy s3/conf
Access permission for ‘s3/conf’ is ‘public
```

I can download files approx. every 3rd reload. 

```
curl https://s3.ourdomain.inc/conf/index.html

<!DOCTYPE html>
<html>
....
```

```
curl https://s3.ourdomain.inc/conf/index.html

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/conf/index.html</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>

```

Is this expected and minio is not capable of using a shared storage space?

**Comment by deekoder** [comment]
Yes this seems to be a bug. Could you restart the instances for now as a workaround till we fix this issue.

**Comment by deekoder** [comment]
Need to discuss design with @abperiasamy

**Comment by vadmeste** [comment]
A simple solution is to watch policy.json file using some file watch libraries (like what we do with mc mirror -w), so if policy.json is updated, all Minio instances in the shared configuration will detect the change and will be able to reload the configuration. The only problem is that watching could be not possible in some cases, like with NFS. I'll investigate further.

**Comment by harshavardhana** [comment]
> A simple solution is to watch policy.json file using some file watch libraries (like what we do with mc mirror -w), so if policy.json is updated, all Minio instances in the shared configuration will detect the change and will be able to reload the configuration. The only problem is that watching could be not possible in some cases, like with NFS. I'll investigate further.

The plan is to bring a peer framework which basically combines 

- shared mode backend servers
- gateway servers

Into a peer mode where shared backend and gateway provide the peers associated while starting up. This way using the peers we update each other. This is sort of a distributed behavior but with replicated updates across all nodes. 

This solves the problem of 

 - mc watch, mc policy and mc events on shared backend.
 - mc watch, mc policy and mc events on gateway mode.

**Comment by dominicporteous** [comment]
Just wondering if anyone has found / implemented a workaround to this - I'm planning on using an NFS based fs for minio so dont think the suggested `mc watch` will be a possibility.

**Comment by dominicporteous** [comment]
@dreh23

**Comment by dreh23** [comment]
@dominicporteous we implemented no workaround. We just adapted our work flow to the given situation and it's a non-critical installation.

**Comment by kannappanr** [comment]
@vadmeste For all anonymous calls always read from the disk.

**Comment by vadmeste** [comment]
> @vadmeste For all anonymous calls always read from the disk.

A more efficient solution is to stat() policy.json and get the modified time, then reload policy only if mtime is more recent than the time of the last update.

**Comment by vadmeste** [comment]
inotify can be not supported in all underlying file systems.. but I guess file last modification time is always present in majority of cases.
