### ISSUE TITLE
error "Unable to list objects." in minio gateway mode using azure s3 blob storage

### ISSUE THREAD

**Issue by flo82** [minio/minio#4464]
I started using minio in gateway mode as described [here](https://github.com/minio/minio/tree/master/docs/gateway) 

it starts correctly, but i can't access the frontend because an error ist displayed.

## Expected Behavior

no error - expecting a login screen

## Current Behavior

frontend error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key/>
<BucketName/>
<Resource>/</Resource>
<RequestId>3L137</RequestId>
<HostId>3L137</HostId>
</Error>
```
backend error:
```
time="2017-06-02T09:31:01Z" level=error msg="Unable to list objects." cause="expected element type <EnumerationResults> but have <Error>" source="[gateway-handlers.go:615:gatewayAPIHandlers.ListObjectsV1Handler()]" stack="go/src/github.com/minio/minio/cmd/gateway-azure-anonymous.go:163:AzureObjects.AnonListObjects <autogenerated>:362:(*AzureObjects).AnonListObjects go/src/github.com/minio/minio/cmd/gateway-handlers.go:608:(GatewayLayer).AnonListObjects-fm go/src/github.com/minio/minio/cmd/gateway-handlers.go:613:gatewayAPIHandlers.ListObjectsV1Handler go/src/github.com/minio/minio/cmd/gateway-router.go:104:(gatewayAPIHandlers).ListObjectsV1Handler-fm"
```
## Possible Solution

no idea

## Steps to Reproduce (for bugs)
```
docker run -p 9000:9000 --name azure-s3  -e "MINIO_ACCESS_KEY=AAA"  -e "MINIO_SECRET_KEY=BBB"  minio/minio gateway azure
```
Note: YYY, AAA and BBB has been replaced with correct values.

Endpoint:  YYY
AccessKey: AAA
SecretKey: BBB
Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myazure YYY AAA BBB
Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

If i try to access the minio http interface now i get the error described above.

## Context

created an azure blob account and verified access using microsoft azure storage explorer.
account is empty. no blob containers exist.

## Your Environment
```
docker image ls -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
minio/minio         latest              a5c634ee8199        4 weeks ago         37.6MB
```
This should be: minio.RELEASE.2017-05-05T01-14-51Z

**Comment by vadmeste** [comment]
@flo82, browser support for gateways is only supported in master. You can use 'minio/minio:edge' docker image. Also, you need to set MINIO_BROWSER to `on`.

So you have to run this command for now:
`docker run -p 9000:9000 --name azure-s3  -e "MINIO_BROWSER=on" -e "MINIO_ACCESS_KEY=AAA"  -e "MINIO_SECRET_KEY=BBB"  minio/minio:edge gateway azure`

**Comment by flo82** [comment]
works perfectly @vadmeste 
it would be helpful to see these configuration requirements documented [here](https://github.com/minio/minio/tree/master/docs/gateway)
for me the issue is resolved - i'm leaving it open so that you can decide how to deal with it.
thank you for the fast help :-)

**Comment by deekoder** [comment]
Since we will merge all of this eventually in one branch, this is a short term pain point.

**Comment by vadmeste** [comment]
@deekoder, there is no indication in the documentation that the user needs to set MINIO_BROWSER to 'on' if he wants to enable Minio Browser, shall we add it or it will change in the near feature ?

**Comment by harshavardhana** [comment]
> @deekoder, there is no indication in the documentation that the user needs to set MINIO_BROWSER to 'on' if he wants to enable Minio Browser, shall we add it or it will change in the near feature ?

Minio browser works without setting MINIO_BROWSEr=on .. @vadmeste

**Comment by vadmeste** [comment]
Not when I tested. Let me check again.

**Comment by harshavardhana** [comment]
> Not when I tested. Let me check again.

That's what i assumed too but it works without doing anything special. Just tested with Azure and S3 backend. GCS is also working fine in the feature-gcs branch.

**Comment by vadmeste** [comment]
Yes, you are right. I guess it is some browser caching issue when I tested.
