### ISSUE TITLE
Secret key is really long.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4470]
On starting minio server. Secret key in latest master branch is extremely long making it very hard to use.

## Expected Behavior
Not have 100 char secret key.
 
## Current Behavior
 eg: D2/a3Bs5HApwmzvntgMbKtZyOauiaT1I+gK2ch1IIvz1g6bZ7DdzrMvlkf6rtu/MSUQihSLevB0XhX9K3OijIWDQdVx0/4/HU8tf

## Possible Solution
 Trim length

## Steps to Reproduce (for bugs)
1. Start Minio Server.
 
## Context
On windows it was too hard to cut copy and paste. Had to use notepad to manage browser login. So usability is affected.
 
## Your Environment
 
* Version used (`minio version`): RC candidate
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by rushenn** [comment]
ETA: 2017-06-06 12:00
