### ISSUE TITLE
Creating docker swarm works sporadically

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4477]
Running docker in swarm works sporadically and is not consistent. 

## Expected Behavior
Should work properly and initialize quickly - waits too long to get the server running. 

## Current Behavior
```
root@server1:~# docker logs 3db5c743c411
Waiting for all hosts to resolve.....Failed to lookup minio2
.Failed to lookup minio3
.Failed to lookup minio4
Failed to resolve hosts.. retrying after 1 second.
...Failed to lookup minio3
.Failed to lookup minio4
Failed to resolve hosts.. retrying after 1 second.
....Failed to lookup minio4
Failed to resolve hosts.. retrying after 1 second.
....All hosts are resolving proceeding to initialize Minio.
Created minio configuration file successfully at /root/.minio
Initializing data volume for first time. Waiting for other servers to come online (elapsed 19s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 28s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 28s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 30s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 32s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 36s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 40s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 45s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 54s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 1m6s)
```

## Possible Solution
No solution yet, writing `format.json` is slow. 

## Steps to Reproduce (for bugs)
Create docker swarm network locally. 

1. docker run --rm swarm create
2. docker run -d -p 2376:2375 swarm manage token://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Use the value printed in step 1.
3. docker swarm init --advertise-addr <MANAGER_HOST_IP>
4. Docker create secrets
echo "AKIAIOSFODNN7EXAMPLE" | docker secret create access_key -
echo "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" | docker secret create secret_key -

Download https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-swarm/docker-compose-secrets.yaml
5. docker stack deploy --compose-file=docker-compose-secrets.yaml minio_stack

## Context
Deployment simplicity and feasibility.

## Your Environment
Minio docker release version, docker edge etc.

**Comment by harshavardhana** [comment]
Works some times

```
....All hosts are resolving proceeding to initialize Minio.
Created minio configuration file successfully at /root/.minio

Initializing data volume.
[01/04] http://minio1:9000/export - 218 GiB online
[02/04] http://minio2:9000/export - 218 GiB online
[03/04] http://minio3:9000/export - 218 GiB online
[04/04] http://minio4:9000/export - 218 GiB online

Endpoint:  http://10.255.0.8:9000  http://10.255.0.7:9000  http://10.0.0.3:9000  http://172.18.0.3:9000  http://10.0.0.2:9000  http://127.0.0.1:9000
AccessKey: AKIAIOSFODNN7EXAMPLE 
SecretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY 

Browser Access:
   http://10.255.0.8:9000  http://10.255.0.7:9000  http://10.0.0.3:9000  http://172.18.0.3:9000  http://10.0.0.2:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.255.0.8:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 410 GiB Free, 436 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).
```

**Comment by nitisht** [comment]
Explored this yesterday with @harshavardhana . Looks like this happens when a `minio_stack` is deleted and started again. 

Since `docker stack rm` doesn't remove the volumes created by the stack, these volumes interfere with the writing of `format.json` in a new stack (when new Minio servers come up). Kubernetes handles it in a way that a specific volume (PV) is always mapped to a specific claim (PVC) no matter how many times the pods are restarted. Swarm doesn't guarantee such a mapping yet. 

One way to avoid this is to cleanup the volumes created in the stack manually, before starting up a new stack. This can be done via `docker volume rm` command. Sent a PR https://github.com/minio/minio/pull/4536 to Minio docs to list these steps in our Swarm guide. 

This can be closed now.

**Comment by harshavardhana** [comment]
Closing as reproduced and proposed work around.
