### ISSUE TITLE
Unable to load all bucket policies

### ISSUE THREAD

**Issue by fwessels** [minio/minio#4478]
Trying to set a policy after creating an object called policy.json causes minio server to not want to restart.
(and after upgrading format.json to V2 a different error message is shown.)

## Possible Solution
See further analysis below.

## Steps to Reproduce (for bugs)
```
$mkdir fstest2
$ ./minio-05-05 server fstest2
...................................
Drive Capacity: 46 GiB Free, 373 GiB Total
^Z
[1]+  Stopped                 ./minio-05-05 server fstest2
$ bg
[1]+ ./minio-05-05 server fstest2 &
$ mc mb myminio/test
Bucket created successfully `myminio/test`.
$ mc cp /etc/passwd myminio/test/policy.json
/etc/passwd:                         5.13 KB / 5.13 KB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 469.50 KB/s 0s
$ mc policy public myminio/test
mc: <ERROR> Unable to set policy `public` for `myminio/test`. We encountered an internal error, please try again.
$ fg
./minio-05-05 server fstest2
^C
$ ./minio-05-05 server fstest2/
FATA[0000] Initializing object layer failed              cause=Unable to load all bucket policies. Object exists on : .minio.sys as directory buckets/test/policy.json source=[server-main.go:276:serverMain()]
```

If we are to upgrade to the newer version the migration itself is successful but then a corrupted backend (understandably) is also reported.

```
$ ./minio-06-02 server fstest2/
Please do not stop the server.
Migrating bucket metadata format from "1" to newer format "2"... completed successfully.FATA[0000] Initializing object layer failed              cause=corrupted backend format, please join https://slack.minio.io for assistance source=[server-main.go:276:serverMain()]
$ ./minio-06-02 server fstest2/
FATA[0000] Initializing object layer failed              cause=corrupted backend format, please join https://slack.minio.io for assistance source=[server-main.go:276:serverMain()]
$
 ```

## Analysis

Further analysis shows that (in `checkFormatSanityFSV2`) the following check fails: 
```
		// Look for the difference between entries and the
		// expected config set, resulting entries if they
		// intersect with original entries set we know
		// that the backend has unexpected files.
		if !entriesSet.Difference(expectedConfigsSet).IsEmpty() {
			fmt.Println(entriesSet)
			fmt.Println(expectedConfigsSet)
			return errCorruptedFormat
		}
```
which gives this output
```
[objects/ policy.json/]
[listener.json notification.xml objects/ policy.json]
```

**Comment by harshavardhana** [comment]
> [1]+  Stopped                 ./minio-05-05 server fstest2
> $ bg
> [1]+ ./minio-05-05 server fstest2 &
> $ mc mb myminio/test
> Bucket created successfully `myminio/test`.
> $ mc cp /etc/passwd myminio/test/policy.json
> /etc/passwd:                         5.13 KB / 5.13 KB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 469.50 KB/s 0s
> $ mc policy public myminio/test
> mc: <ERROR> Unable to set policy `public` for `myminio/test`. We encountered an internal error, please try again.
> $ fg

Yes @fwessels migration won't fix this issue automatically.  But i see that we should handle it.

**Comment by fwessels** [comment]
Correct, was not expecting migration to automatically fix this.
(Initially I though that the error happened due to migration of the format.json file but it already happened before it.)

**Comment by harshavardhana** [comment]
Sending a fix. @fwessels
