### ISSUE TITLE
Enhance storage/metadata version handling: prevent older minio versions from corrupting a newer minio's on-disk format

### ISSUE THREAD

**Issue by donatello** [minio/minio#4486]
This is to improve error messages when an older version of Minio server is run with a disk which has data in a newer format created by a newer version of Minio.

Currently, when running the release candidate binary in a data-disk on which:

1. `.minio.sys/format.json`-> `fs.version` is bumped up from 2 (current supported) to 3 (unknown future version), then we get start-up error:
```
FATA[0000] Initializing object layer failed              cause=Unable to validate 'format.json', corrupted backend format, please join https://slack.minio.io for assistance source=[server-main.go:276:serverMain()] stack=fs-v1-metadata.go:414:initFormatFS fs-v1.go:229:newFSObjectLayer server-main.go:299:newObjectLayer server-main.go:275:serverMain /home/builder/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:github.com/minio/minio/vendor/github.com/minio/cli.HandleAction /home/builder/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:github.com/minio/minio/vendor/github.com/minio/cli.Command.Run /home/builder/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run main.go:143:Main /home/builder/mygo/src/github.com/minio/minio/main.go:68:main.main /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:183:runtime.main /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/asm_amd64.s:2086:runtime.goexit
```
2. `.minio.sys/format.json`-> `version` is bumped up from 1 (current) to 2 (future), then no error is returned - this is a **bug**, as it allows an older version minio to corrupt a newer minio's data disk.

## Expected Behavior

1. When seeing an unknown version (i.e. version number greater than what is known to the current version), server needs to display a message like "Future on-disk format detected" and error out, so as to not corrupt the disk.
2. When seeing an older version, it should be migrated to the current/latest version (this is the current behaviour - nothing to implement here).

## Current Behavior

As described in near the beginning here.

## Context

Testing for release candidate of FS policy/notifications related migrations.

**Comment by deekoder** [comment]
Since #4523 now in. We don't need this anymore.
