### ISSUE TITLE
Missing support for S3 GovCloud endpoints

### ISSUE THREAD

**Issue by jwilander** [minio/minio#4489]
## Expected Behavior
Minio recognizes S3 GovCloud region and endpoints as Amazon S3.

## Current Behavior
Minio does not recognize S3 GovCloud region and endpoints as Amazon S3.

## Possible Solution
Update this https://github.com/minio/minio-go/blob/master/pkg/s3utils/utils.go#L83

To something like this:
```
// IsAmazonEndpoint - Match if it is exactly Amazon S3 endpoint.
func IsAmazonEndpoint(endpointURL url.URL) bool {
    if IsAmazonChinaEndpoint(endpointURL) {
        return true
    }

    if IsAmazonGovCloudEndpoint(endpointURL) {
        return true
    }

    return endpointURL.Host == "s3.amazonaws.com"
}

// IsAmazonGovCloudEndpoint - Match if it is exactly Amazon S3 GovCloud endpoint.
func IsAmazonGovCloudEndpoint(endpointURL url.URL) bool {
    if endpointURL == sentinelURL {
        return false
    }
    return endpointURL.Host == "s3-us-gov-west-1.amazonaws.com"
}
```

## Context
Prevents our customers from using GovCloud region/endpoints.

**Comment by deekoder** [comment]
Thanks for reporting this issue @jwilander. Will take a look and update here.

**Comment by harshavardhana** [comment]
@jwilander https://github.com/minio/minio-go/pull/701 is it possible to validate on your end with mattermost?

**Comment by harshavardhana** [comment]
@jwilander just checking back were you able to validate the PR upstream?

**Comment by jwilander** [comment]
Unfortunately I don't actually have an S3 account with access to the GovCloud region so it's difficult for me to verify

**Comment by jwilander** [comment]
Alright what I can do is create a custom Mattemost build to give to the customer to try out to make sure this fixes the issue. I'll report back here with the results

**Comment by harshavardhana** [comment]
> Alright what I can do is create a custom Mattemost build to give to the customer to try out to make sure this fixes the issue. I'll report back here with the results

Thanks @jwilander

**Comment by jwilander** [comment]
Customer came back saying they're getting an error from [here](https://github.com/harshavardhana/minio-go/blob/bd170838e265666d52b1d9661712275edccdf513/utils.go#L126) since this [function](https://github.com/harshavardhana/minio-go/blob/bd170838e265666d52b1d9661712275edccdf513/pkg/s3utils/utils.go#L83) is missing the GovCloud check

**Comment by harshavardhana** [comment]
> Customer came back saying they're getting an error from here since this function is missing the GovCloud check

Can the actual error be pasted here? @jwilander

**Comment by jwilander** [comment]
In Mattermost error logs:
```
[2017/06/13 19:15:54 EDT] [EROR] /api/v3/teams/<teamid>/files/upload:WriteFile code=500 rid=<requestid> uid=<userid> ip=<ipaddress> Encountered an error writing to S3 [details: Amazon S3 endpoint should be 's3.amazonaws.com'.]
```

So the error from the driver is
```
Amazon S3 endpoint should be 's3.amazonaws.com'.
```

**Comment by harshavardhana** [comment]
My bad @jwilander just updated the PR with the said change. It should work fine now. Please let me know. If helps you can also loop me in to the issue/email thread `harsha ( a ) minio.io`

**Comment by jwilander** [comment]
No worries, thanks for the updates! We appreciate the quick turn around on this. I'll get it tested out and let you know.

We don't actually have an email thread, the correspondence is in a private channel on our Mattermost instance

**Comment by harshavardhana** [comment]
> No worries, thanks for the updates! We appreciate the quick turn around on this. I'll get it tested out and let you know.
> 

:+1: 

> We don't actually have an email thread, the correspondence is in a private channel on our Mattermost instance

Understood.

**Comment by jwilander** [comment]
Making some progress, now they're getting this error:

`[details: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-gov-west-1']`

We're thinking it might be from here: https://github.com/harshavardhana/minio-go/blob/gov/api-put-bucket.go#L193

**Comment by harshavardhana** [comment]
> Making some progress, now they're getting this error:
> 
> [details: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-gov-west-1']

Yes most probably, are you trying to create a bucket as well? @jwilander

**Comment by harshavardhana** [comment]
> Yes most probably, are you trying to create a bucket as well? @jwilander

Updated the PR again this time with some more simplification in MakeBucket behavior. Tested with us-west-1.  Let me know if you find further issues.

**Comment by jwilander** [comment]
That seems to have fixed it, thanks @harshavardhana!

**Comment by harshavardhana** [comment]
@jwilander Thanks - can you confirm on the PR as well? There some tests that have to be changed which I will do and we will get this merged.
