### ISSUE TITLE
browser: share file expiration not changeable on IE

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4493]
The UP DOWN buttons are not clickable on Internet Explorer

![share-windows](https://user-images.githubusercontent.com/634494/26856652-e4ff884e-4ad9-11e7-85ea-1d2185e91014.png)

**Comment by rushenn** [comment]
@krishnasrinivas What is the IE version?

**Comment by krishnasrinivas** [comment]
@rushenn it was actually Edge browser on windows.

**Comment by kannappanr** [comment]
@kaankabalak Can you verify if the new ux has the same bug, if yes, we can keep it open until it is fixed?

**Comment by rushenn** [comment]
@kannappanr I've tested this on both Microsoft Edge and IE 11 on Windows 10 and It seems working. This issue was already addressed here https://github.com/minio/minio/pull/4524

**Comment by kannappanr** [comment]
Issue marked fixed.
