### ISSUE TITLE
TestInitListeners unit test failed on travis-ci

### ISSUE THREAD

**Issue by krisis** [minio/minio#4505]
Travis CI output
```
--- FAIL: TestInitListeners (0.00s)

	server-mux_test.go:143: Test 2: Unable to initialize listeners listen tcp :38416: bind: address already in use
```
## Expected Behavior

Unit tests should pass
## Current Behavior

`TestInitListeners` unit test failed.

## Possible Solution

Not known yet
## Steps to Reproduce (for bugs)

1. Seen once on Travis CI - https://travis-ci.org/minio/minio/jobs/240720887
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Fixed by #4508
