### ISSUE TITLE
GET ObjectAcl fails with "Not Implemented" on minio server

### ISSUE THREAD

**Issue by taisph** [minio/minio#4507]
I am using Laravel 5.3 Framework Filesystem with the AWS S3 driver and when I try to move or copy files, I get the error below from the minio server.
```
GET http://localhost:9000/temp/somefile.txt?acl resulted in a '501 Not Implemented' response
```

## Expected Behavior
I expect the file operation to be completed without errors as the Amazon S3 service would have.

## Current Behavior
Fails to move or copy the file or directory with error 500 Not Implemented.

## Steps to Reproduce (for bugs)

1. Grab a laravel skeleton application.
2. Configure S3 disk to use minio server.
3. Use `artisan tinker` and run
```php
\Storage::disk('s3')->put('somefile.txt'); \Storage::disk('s3')->move('somefile.txt', 'someotherfile.txt');
```
4. Curse at the error while waving your fist at the screen.

## Context
I need to generate and store arbitrary number of PDF files in a temporary directory and move them to the final directory when all files have been stored.

## Your Environment

* Version used (`minio version`): 2017-05-05T01:14:51Z
* Environment name and version (e.g. nginx 1.9.1): latest docker image
* Server type and version: latest docker image
* Operating System and version (`uname -a`): latest docker image

**Comment by deekoder** [comment]
We recommend using bucket policies over Object ACLs. We will send a patch upstream to Laravel project to do the same.

**Comment by deekoder** [comment]
Also Dup of #3892

**Comment by taisph** [comment]
FWIW, I opted for a quick-and-dirty solution by overriding the visibility fetch in the copy method of the `flysystem-aws-s3-v3` adapter that Laravel 5+ uses: https://github.com/Casalogic/flysystem-aws-s3-v3/blob/feature/override-visibility-on-copy/src/AwsS3Adapter.php#L402

They basically fetch the ACL of the object they want to copy in order to apply the same visibility on the destination object.

I haven't worked with S3 before but if you can point me to an explanation of what you are suggesting as a replacement, then I'll set off some time to make a proper PR for `thephpleague/flysystem-aws-s3-v3`.

**Comment by deekoder** [comment]
https://docs.minio.io/docs/how-to-use-aws-sdk-for-php-with-minio-server @taisph  please see if this helps.

**Comment by coraxster** [comment]
@taisph thank you! I forked your version and published to composer. Hope sometime thephpleague will fix this
https://packagist.org/packages/coraxster/flysystem-aws-s3-v3-minio

**Comment by deekoder** [comment]
Since we support bucket policies, we don't plan to add ACL support. Even AWS strongly discourages using ACLs with S3.
