### ISSUE TITLE
Cache coherency when using shared backend

### ISSUE THREAD

**Issue by tsmgeek** [minio/minio#4510]
When running minio with a shared backend will the internal cache still check if the backend has a newer file that currently in the cache?

**Comment by harshavardhana** [comment]
> When running minio with a shared backend will the internal cache still check if the backend has a newer file that currently in the cache?

There are no caches in shared backend @tsmgeek each i/o hits the backend.

**Comment by deekoder** [comment]
@tsmgeek - Caching is only enabled for erasure coded backended and it does validate cache for each getObject request. For al FS backends, including shared backends, there is no caching. Hope this helps. Closing this bug as won't fix. We are about to introduce persistent cache support and we may remove the in memory caching completely later.
