### ISSUE TITLE
In shared-fs mode upgrade may hang during migration

### ISSUE THREAD

**Issue by krisis** [minio/minio#4511]
## Expected Behavior
In share-fs mode upgrade may hang during migration, we need to provide a user actionable message.

## Current Behavior
In shared-fs mode upgrade may hang during migration - if other instances are running older version, we don't show user any actionable message.

## Possible Solution
Add a log message to indicate user that he needs to restart the other servers. If the `format.json` write lock is blocked.

## Context
UI enhancements.. 

## Your Environment
Current master.

**Comment by krishnasrinivas** [comment]
We are not doing migration for this release

**Comment by deekoder** [comment]
#4523 fix makes this a won't fix as its no longer relevant.
