### ISSUE TITLE
Minio hangs when run in shared-fs mode

### ISSUE THREAD

**Issue by krisis** [minio/minio#4517]
When Minio server is run in shared-fs mode like,
```
minio server --address ":9000" ~/dir
minio server --address ":9001" ~/dir
```
One of the above server instances hangs.

## Expected Behavior

Minio server instances when run in shared-fs mode shouldn't hang.

## Current Behavior

The second (or later) launched Minio server instances hangs indefinitely.

## Possible Solution

Not known yet.
## Steps to Reproduce (for bugs)

1. minio server --address ":9000" ~/dir
2. minio server --address ":9001" ~/dir
3.
4.

## Context

Shared-fs mode testing
## Your Environment

* Version used (`minio version`): commit id `3dfe254a1112384c336d14734f2cb23366d92ab3`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by krisis** [comment]
## Root cause analysis
The second (or subsequent) Minio server instances block trying to acquire a write lock (flock(3)) on format.json, since the running instance is holding a read lock for its lifetime. This read lock is to avoid future migrations (from format version 2 to 3 or later) while older Minio version is still operating on the shared filesystem. So, this read lock can't be simply removed.

## Solution 
N B The following solution requires https://github.com/minio/minio/pull/4512 for it to work.

One way to fix this is to hold a non-blocking write lock (i.e, LOCK_EX | LOCK_NB). If the lock isn't granted (i.e, we get EWOULDBLOCK) we should exit with the message - `There may be older version of the server still running. Stop all the older instances and upgrade them before migrating to new format version`. If the lock is granted migration can happen and server starts without blocking indefinitely.

**Comment by deekoder** [comment]
#4523  fixes.
