### ISSUE TITLE
format.json migration assumes current version is always lower

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4519]
Migration validates current `format.json` is not equal to version 2.  It will break if higher version is available.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by donatello** [comment]
This change is addressing this: https://github.com/minio/minio/pull/4491 - the validation is done in `checkFormatFS` - specifically checking if the version on disk is a "known version" and then if it is not the latest version, it returns `errFSFormatOld`.

This can be closed after #4491 is merged.
