### ISSUE TITLE
[proposal] Possibility of migrating to grpc with Gob codec.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4526]
https://godoc.org/google.golang.org/grpc , since the net/rpc has been deprecated we should explore the possibility of moving to grpc.

Since we need to bring in support for certain types of functionality which we cannot implement right now with Go net/rpc

- Adding deadlines for on-going RPC operations without sufficiently refactoring/re-implementing `net/rpc`
- Native authentication mechanism, we have built a layer on top to address this by default `net/rpc` is unauthenticated. 
- Native TLS support, we have built the functionality of top to address this by default `net/rpc` is plain-text only. 
- All the current bugs in `net/rpc` has been frozen and no more updates will be available this is problem for us from a long term perspective to stick with legacy code.

This is a proposal change and should be done carefully with detailed exploration, benchmarks and validate if indeed the grpc will be better for us.

**Comment by fwessels** [comment]
As per https://github.com/golang/go/issues/16844#issuecomment-245261755, back in September GRPC was overall 4x slower (2x more CPU intensive, 2x slower). Would be good to reinvestigate if GRPC performance has improved since then.

**Comment by harshavardhana** [comment]
My proposal is to bring in this with Gob

- https://godoc.org/google.golang.org/grpc#Codec
- https://godoc.org/google.golang.org/grpc#CustomCodec
- https://godoc.org/google.golang.org/grpc#WithCodec

Also authentication mechanism to built around 

- https://godoc.org/google.golang.org/grpc/credentials#TransportCredentials
- https://godoc.org/google.golang.org/grpc/credentials#AuthInfo
- https://godoc.org/google.golang.org/grpc/credentials/oauth#NewJWTAccessFromKey (For JWT)

**Comment by harshavardhana** [comment]
https://github.com/google/go-microservice-helpers

**Comment by fwessels** [comment]
This may be something to investigate as a serialization protocol: https://github.com/capnproto/go-capnproto2

**Comment by harshavardhana** [comment]
Tested using Gob it seems to work fine.. 

```go
type gobCodec struct{}

func (c *gobCodec) Marshal(v interface{}) ([]byte, error) {
        var b bytes.Buffer
        enc := gob.NewEncoder(&b)
        err := enc.Encode(v)
        if err != nil {
                return nil, err
        }
        fmt.Println("Marshal: I am here", v)
        return b.Bytes(), nil
}

func (c *gobCodec) Unmarshal(b []byte, v interface{}) error {
        fmt.Println("Unmarshal: I am here", v, string(b))
        r := bytes.NewReader(b)
        dec := gob.NewDecoder(r)
        return dec.Decode(v)
}

func (c *gobCodec) String() string {
        return "gob"
}
``` 

A sample Gob codec compatible with grpc.Codec interface, so we might just leverage this and use for now.

**Comment by harshavardhana** [comment]
https://github.com/harshavardhana/grpc-gob-hello one such example on how to proceed forward.

**Comment by h12w** [comment]
I happen to see this code. It is is a wrong or at least inefficient way of using gob.

Gob encodes a type declaration when a type is transferred for the first time in a stream. So the client and the server must have the same understanding what a stream is in order to use gob correctly and efficiently.

By creating gob.Decoder each time of marshaling, either a request sent from a client that assumes it has already sent out the type declaration will fail to be decoded, or it will become extremely inefficient for both the client and the server to recreate the encoder and decoder in each request-response loop.

**Comment by harshavardhana** [comment]
> Gob encodes a type declaration when a type is transferred for the first time in a stream. So the client and the server must have the same understanding what a stream is in order to use gob correctly and efficiently.
> 
> By creating gob.Decoder each time of marshaling, either a request sent from a client that assumes it has already sent out the type declaration will fail to be decoded, or it will become extremely inefficient for both the client and the server to recreate the encoder and decoder in each request-response loop.

Thanks for pointing it out, the code was meant to be an example @h12w .  For efficient usage you should create a gob.NewEncoder, Decoder using the net.Conn itself and use it for all the requests subsequently.

**Comment by 13o6** [comment]
Hi @harshavardhana 
I also noticed what @h12w did, was trying to fix it in the following ways:
1 - move out the declaration of `NewEncoder` and only do the initialization/assignment inside `Marshal`. By 'move out' I mean declared as a _global_ package variable or inside the `Codec` struct.
2 - add them in the client delcaration along with a `ClientConn`.

Option 1 did not result in any (significant) speedup. Option 2 didn't work at all. 

I was inspired by:
- https://appliedgo.net/networking/
- https://www.safaribooksonline.com/library/view/network-programming-with/9781484226919/A436770_1_En_4_Chapter.html
- https://github.com/grpc/grpc-go/blob/f4b523765c542aa30ca9cdb657419b2ed4c89872/call_test.go

In my benchmarks grpc + pb is typically 4 - 4.5x faster than using with Gob...

**Comment by harshavardhana** [comment]
What was test like were you transferring structs or lots of binary data ?

**Comment by 13o6** [comment]
Yes, structs but only with a handful of fields of primitive types. Results are below:
```Clients: 10
Requests/client 100000
Total time: 236667 ms for 1000000 requests
Requests sent: 1000000
Verified responses: 998045
Throughput (TPS): 4225
Mean: 2359630 ns, median: 1810145 ns```

**Comment by kannappanr** [comment]
Will not be implementing this feature. There is more latency if the case of grpc compared to netrpc.
