### ISSUE TITLE
format.json FD gets closed

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4530]
Start minio server in the usual manner and check that the format.json is kept open:

krishna@escape:~$ ls -l /proc/13134/fd
total 0
lrwx------ 1 krishna krishna 64 Jun 13 00:52 0 -> /dev/pts/0
lrwx------ 1 krishna krishna 64 Jun 13 00:52 1 -> /dev/pts/0
lrwx------ 1 krishna krishna 64 Jun 13 00:52 2 -> /dev/pts/0
lr-x------ 1 krishna krishna 64 Jun 13 00:52 3 -> /dev/tty
lrwx------ 1 krishna krishna 64 Jun 13 00:52 4 -> socket:[270135]
lrwx------ 1 krishna krishna 64 Jun 13 00:52 5 -> anon_inode:[eventpoll]
lr-x------ 1 krishna krishna 64 Jun 13 00:52 6 -> /home/krishna/export/.minio.sys/format.json

But after sometime (5-10 mins) the FD gets closed automatically:
krishna@escape:~$ ls -l /proc/13134/fd
total 0
lrwx------ 1 krishna krishna 64 Jun 13 00:52 0 -> /dev/pts/0
lrwx------ 1 krishna krishna 64 Jun 13 00:52 1 -> /dev/pts/0
lrwx------ 1 krishna krishna 64 Jun 13 00:52 2 -> /dev/pts/0
lr-x------ 1 krishna krishna 64 Jun 13 00:52 3 -> /dev/tty
lrwx------ 1 krishna krishna 64 Jun 13 00:52 4 -> socket:[270135]
lrwx------ 1 krishna krishna 64 Jun 13 00:52 5 -> anon_inode:[eventpoll]
krishna@escape:~$ 

Need to figure out how the FD is getting closed.

**Comment by krisis** [comment]
@krishnasrinivas what operations were being performed on the object store?

**Comment by harshavardhana** [comment]
> krishna@escape:~$ ls -l /proc/13134/fd
> total 0
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 0 -> /dev/pts/0
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 1 -> /dev/pts/0
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 2 -> /dev/pts/0
> lr-x------ 1 krishna krishna 64 Jun 13 00:52 3 -> /dev/tty
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 4 -> socket:[270135]
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 5 -> anon_inode:[eventpoll]
> lr-x------ 1 krishna krishna 64 Jun 13 00:52 6 -> /home/krishna/export/.minio.sys/format.json
> 
> But after sometime (5-10 mins) the FD gets closed automatically:
> krishna@escape:$ ls -l /proc/13134/fd
> total 0
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 0 -> /dev/pts/0
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 1 -> /dev/pts/0
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 2 -> /dev/pts/0
> lr-x------ 1 krishna krishna 64 Jun 13 00:52 3 -> /dev/tty
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 4 -> socket:[270135]
> lrwx------ 1 krishna krishna 64 Jun 13 00:52 5 -> anon_inode:[eventpoll]
> krishna@escape:$
> 
> Need to figure out how the FD is getting closed.

It could be possible that it is being garbage collected due to `_  = rlk`

**Comment by krisis** [comment]
>It could be possible that it is being garbage collected due to _ = rlk

How will the garbage collector know that the Close() method should be called? Further, I added `debug.PrintStack()` in `RLockedFile`'s `Close` and it is not being called. 

```
diff --git a/pkg/lock/lock.go b/pkg/lock/lock.go
index 1672ef7..2b43021 100644
--- a/pkg/lock/lock.go
+++ b/pkg/lock/lock.go
@@ -20,7 +20,9 @@ package lock
 
 import (
        "errors"
+       "fmt"
        "os"
+       "runtime/debug"
        "sync"
 )
 
@@ -59,12 +61,14 @@ func (r *RLockedFile) Close() (err error) {
        r.mutex.Lock()
        defer r.mutex.Unlock()
 
+       fmt.Println(r)
        if r.refs == 0 {
                return os.ErrInvalid
        }
 
        r.refs--
        if r.refs == 0 {
+               debug.PrintStack()
                err = r.File.Close()
        }
 
```

**Comment by harshavardhana** [comment]
> diff --git a/pkg/lock/lock.go b/pkg/lock/lock.go
> index 1672ef7..2b43021 100644
> --- a/pkg/lock/lock.go
> +++ b/pkg/lock/lock.go
> @@ -20,7 +20,9 @@ package lock
>  
>  import (
>         "errors"
> +       "fmt"
>         "os"
> +       "runtime/debug"
>         "sync"
>  )
>  
> @@ -59,12 +61,14 @@ func (r *RLockedFile) Close() (err error) {
>         r.mutex.Lock()
>         defer r.mutex.Unlock()
>  
> +       fmt.Println(r)
>         if r.refs == 0 {
>                 return os.ErrInvalid
>         }
>  
>         r.refs--
>         if r.refs == 0 {
> +               debug.PrintStack()
>                 err = r.File.Close()
>         }

There are finalizer's set inside os.File() - It is purely a speculation not suggesting that this will happen. So in-fact top level Close() wouldn't reveal much in this case. 

But i am wondering if the scope is lost it might cause a problem? 
```
// NewFile returns a new File with the given file descriptor and name.
  func NewFile(fd uintptr, name string) *File {
  	fdi := int(fd)
  	if fdi < 0 {
  		return nil
  	}
  	f := &File{&file{fd: fdi, name: name}}
  	runtime.SetFinalizer(f.file, (*file).close)
  	return f
  }
```

**Comment by krisis** [comment]
@harshavardhana,
> There are finalizer's set inside os.File() ...

This makes sense. We need to find an idiomatic way to retain the read-lock overriding the finalizer set by `os` package.

**Comment by harshavardhana** [comment]
Here is a simple reproducer. 

```
package main

import (
        "fmt"
        "os"
        "runtime"
        "time"
)

func closed() {
        x, _ := os.Open("/tmp/closed.txt")
        _ = x
        return
}

func open() *os.File {
        o, _ := os.Open("/tmp/open.txt")
        return o
}

func main() {
        closed()
        o := open()
        time.Sleep(20 * time.Second)
        runtime.GC()
        // Make sure to reference it here                                                                                                         
        // to avoid GC.                                                                                                                           
        fmt.Println(o.Name())
        time.Sleep(20 * time.Second)
}
```

You will be able to observe that `closed()` when listing `ls -l /proc/<pid>/fd` would suddenly vanish after 20secs, where as `open()` lives on after the GC has been called.
