### ISSUE TITLE
Query on Minio Browser Public Bucket access

### ISSUE THREAD

**Issue by wingZero21** [minio/minio#4531]
Hi,

Can you advise on if we are able to access a bucket without the key when its been made public?

I have added the command below but I cant see anyway to view this without logging into the UI?

Cheers

Details:
```mc policy public myminio/publicbucket```

**Comment by harshavardhana** [comment]
> Can you advise on if we are able to access a bucket without the key when its been made public?
> 
> I have added the command below but I cant see anyway to view this without logging into the UI?
> 
> Cheers
> 
> Details:
> mc policy public myminio/publicbucket

@wingZero21 all you have to do is just navigate to the publicbucket say for example your server is running at ip 10.0.0.1 

Then you would visit UI without logging in at http://10.0.0.1:9000/minio/publicbucket/ 

This will list all buckets without logging into your browser.  Let me know if you have further questions, feel free to join our slack channel as well.

If this is sufficiently answered feel free to the close this issue as well.

**Comment by wingZero21** [comment]
Hi,

I have tried that however it just redirects me to the login screen.

**Comment by harshavardhana** [comment]
Can write down what you did step by step ?

**Comment by wingZero21** [comment]
Hi,

I just went to the URL that you advised in the previous post. 

I also tried adding the specific bucket name which has been assigned to be public, however again it just takes me to the login screen.

**Comment by harshavardhana** [comment]
> Hi,
> 
> I just went to the URL that you advised in the previous post.
> 
> I also tried adding the specific bucket name which has been assigned to be public, however again it just takes me to the login screen.

All i did was the following and i am able to publicly access. 

```
$ mc policy download play/harsha
Access permission for `play/harsha` is set to `download`
```

Now click on the link https://play.minio.io:9000/minio/harsha

**Comment by wingZero21** [comment]
Hi,

I have tried doing this with the download command however just takes me back to the login screen as it did previously.

**Comment by wingZero21** [comment]
Ok, so what I have done now which seems to work is add /publicbucket to the end of the URL and this does seem to work.

However after uploading a file it does not seem to appear on the publicbucket list? You then have to click back a directory which seems a bit odd. Anyway it does seem to allow access but I am not sure how this would work if you were wanting to access the file via command line without the key? 

I have just accessed the file with direct url once knowing the filename, so it must just be the bucket part that you if you want to view the entire bucket, you need to go back a directory.

EG: 
```
https://play.minio.io/minio/testbucket1/publicbucket
```

Cheers

**Comment by harshavardhana** [comment]
Feel free to close this bug, if you have no more questions.
