### ISSUE TITLE
minio looks hung when format.json is opened with write lock.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4533]
When `format.json` is opened by another process and holding write lock, starting minio looks hung ie nothing printed.

## Expected Behavior

We would need to show some message on retries to get the lock.

## Current Behavior

Nothing printed.

## Steps to Reproduce (for bugs)

1. run below code before starting minio
```go
	wlockedFile, err := lock.TryLockedOpenFile("d1/.minio.sys/format.json", os.O_RDWR|os.O_CREATE, 0600)
	if err != nil {
		fmt.Println("unable to open wlocked file", err)
		return
	}

	fmt.Println("got wlockedFile", wlockedFile)
	time.Sleep(1 * time.Minute)
```

2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
This messaging will come when we will migrate from format.json v1 to v2. Also next release we are going to review each message being printed so this will be addressed then.

It is not really a big of a problem right now and can be moved out RC milestone.

**Comment by balamurugana** [comment]
v1 binary (ie this release) will not print any message if v2 would hold lock for more time because of migration.  IMO we should fix for completeness in this release.

**Comment by harshavardhana** [comment]
> v1 binary (ie this release) will not print any message if v2 would hold lock for more time because of migration. IMO we should fix for completeness in this release.

That is not a problem @balamurugana it is a rare scenario when v1 is being started while v2 is being migrated. Usually it would be v1 is already running and v2 is just starting and waiting.

There is no reason to introduce cosmetic non actionable messages at this point in time.  Before migration release we can do one more with HTTP changes where we can bring this in hopefully in another 2 weeks.

**Comment by balamurugana** [comment]
The best case is always wished to happen.  I would like to see how things should work for error situations.


> There is no reason to introduce cosmetic non actionable messages at this point in time. Before migration release we can do one more with HTTP changes where we can bring this in hopefully in another 2 weeks.

Does this mean we support v2 migration from the next release only?

**Comment by harshavardhana** [comment]
> The best case is always wished to happen. I would like to see how things should work for error situations.

What error are you talking about here? @balamurugana you are putting an arbitrary code and showing that its useful with arbitrary wait time, why would you think current code waits for long and what makes you think user will think its hung?.  Show me if there is a problem in current binary with significant wait times then we can think about this where a server is seen to be hung. 

> Does this mean we support v2 migration from the next release only?

We might not do v2 migration in next release also, at that point we can come up with a common messaging for all these situations with proper discussion. We don't need to hurry and add this since this might not even occur in most deployments and the window itself is too small since writing `format.json` is in millisecond range so entirety of a write lock is perhaps really small..

**Comment by balamurugana** [comment]
> What error are you talking about here? @balamurugana you are putting an arbitrary code and showing that its useful with arbitrary wait time, why would you think current code waits for long and what makes you think user will think its hung?. Show me if there is a problem in current binary with significant wait times then we can think about this where a server is seen to be hung.

The code is a simulation of write lock held in a situations like migration in v2.  No one is interested to  fix for arbitrary code.  What do you think starting server binary like minio not showing any message for few more seconds?

> We might not do v2 migration in next release also, at that point we can come up with a common messaging for all these situations with proper discussion. We don't need to hurry and add this since this might not even occur in most deployments

makes sense.

> and the window itself is too small since writing format.json is in millisecond range so entirety of a write lock is perhaps really small..

Yes in all the cases.  Buggy network filesystem for backend might respond beyond this time, however the response time won't be beyond TCP timeout.

The above argument doesn't mean to take this issue for RC.  Its up to the team decision.

**Comment by harshavardhana** [comment]
Is this bug still needed? there are other bugs which are superseding this related to `.minio.sys` deprecation and removing fcntl locks // cc @krisis @krishnasrinivas

**Comment by harshavardhana** [comment]
> Is this bug still needed? there are other bugs which are superseding this related to .minio.sys deprecation and removing fcntl locks // cc @krisis @krishnasrinivas

Shall we close this? @krisis @krishnasrinivas

**Comment by harshavardhana** [comment]
This is not an issue anymore, since we have decided to remove fcntl locks and change the backend quite entirely. Will re-open this again if we decide otherwise and have to do migration.
