### ISSUE TITLE
Any plans for a iOS Swift SDK?

### ISSUE THREAD

**Issue by gperdomor** [minio/minio#4535]
Do you have plans or can provide a ETA for a Swift SDK?

**Comment by harshavardhana** [comment]
> Do you have plans or can provide a ETA for a Swift SDK

We don't have any set timelines right now.  We will keep you posted @gperdomor

**Comment by krishnasrinivas** [comment]
@gperdomor you can use AWS Swift SDK to talk to minio as well.

**Comment by harshavardhana** [comment]
> @gperdomor you can use AWS Swift SDK to talk to minio as well.

https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-iOS-with-minio.md agreed @krishnasrinivas here is the relevant doc as well.

**Comment by gperdomor** [comment]
thank you guys :D
