### ISSUE TITLE
[gateway-azure] In responses, convert MD5 from Base64 to Hex

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio#4537]
Azure Blob Storage stores and returns MD5 checksums in base64 format. AWS S3 uses the hex encoding, however, and this causes applications to think that files are corrupted.

Example: create a minio gateway to Azure, then upload a file using "s3cmd put"

## Expected Behavior
Minio should return MD5 hashes encoded as hex. As such, s3cmd should work

## Current Behavior
"s3cmd put" fails with:
```
asegala@wsl:~/s3cmd-1.6.1$ ./s3cmd put photos/1.jpg s3://testbucket
upload: 'photos/1.jpg' -> 's3://testbucket/1.jpg'  [1 of 1]
 4318654 of 4318654   100% in    1s     3.33 MB/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of photos/1.jpg
upload: 'photos/1.jpg' -> 's3://testbucket/1.jpg'  [1 of 1]
 4318654 of 4318654   100% in    0s     4.86 MB/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of photos/1.jpg
upload: 'photos/1.jpg' -> 's3://testbucket/1.jpg'  [1 of 1]
 4318654 of 4318654   100% in    0s     5.58 MB/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of photos/1.jpg
upload: 'photos/1.jpg' -> 's3://testbucket/1.jpg'  [1 of 1]
 4318654 of 4318654   100% in    0s     6.13 MB/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of photos/1.jpg
upload: 'photos/1.jpg' -> 's3://testbucket/1.jpg'  [1 of 1]
 4318654 of 4318654   100% in    0s     6.34 MB/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of photos/1.jpg
upload: 'photos/1.jpg' -> 's3://testbucket/1.jpg'  [1 of 1]
 4318654 of 4318654   100% in    0s     6.24 MB/s  done
WARNING: MD5 Sums don't match!
WARNING: Too many failures. Giving up on 'photos/1.jpg'
ERROR: Upload of 'photos/1.jpg' failed too many times (Last reason: )
```

## Possible Solution
Minio should convert base64-encoded checksums to hex when using Azure

## Steps to Reproduce (for bugs)
1. Create a Minio gateway to Azure
2. Use s3cmd to upload any object

## Your Environment
* Version used (`minio version`): RELEASE.2017-05-05T01-14-51Z
* Operating System and version (`uname -a`): Docker (minio/minio)

**Comment by krishnasrinivas** [comment]
@EgoAleSum --debug options says:

```
DEBUG: MD5 sums: computed=73c2ee0acb590362c0ac3740f8c39523, received="0x8D4B2AE97754E88"
```

What we do in azure gateway is return whatever ETag Azure returns us. i.e Azure returns ETag as `"0x8D4B2AE97754E88"` and hence we return the same ETag to the S3 client.

`mc` and `aws-cli` works fine with azure gateway though.

**Comment by ItalyPaleAle** [comment]
Yes, I tried mc and that was successful. However, s3cmd was the main reason why I wanted to implement the gateway :) (and I'm expecting that others would want the same) Any way we could fix this?

**Comment by harshavardhana** [comment]
> Yes, I tried mc and that was successful. However, s3cmd was the main reason why I wanted to implement the gateway :) (and I'm expecting that others would want the same) Any way we could fix this?

There a reason we avoid computing md5sum to avoid overhead and introducing custom metadata on your blobs at your backend.  

While for the most part ETag looks like hex md5sum,  AWS S3 discourages users to treat ETag as md5sum in a generalized manner, i don't see how it will work in all scenarios. 

So i took the liberty of testing s3cmd with 20MB objects,  i can see they never match md5sum for such objects. So i see that this double checking is frivolous activity for files smaller than < 20MB for which multipart API is not used.  So the default behavior behavior here is not meaningful and consistent.

It would be `aws cli` behavior which is more consistent with the documented behavior IMHO.

**Comment by EgoAleSum** [comment]
Thanks for explaining @harshavardhana . I have filed an issue with s3cmd too: https://github.com/s3tools/s3cmd/issues/880

I understand your rationale and it makes full sense.

Is there any chance you could alter the response from Azure to convert the MD5 hash in hex format and include it in the ETag header? This would improve compatibility.

**Comment by ItalyPaleAle** [comment]
Thanks for explaining @harshavardhana . I have filed an issue with s3cmd too: https://github.com/s3tools/s3cmd/issues/880

I understand your rationale and it makes full sense.

Is there any chance you could alter the response from Azure to convert the MD5 hash in hex format and include it in the ETag header? This would improve compatibility. I'm not asking to compute MD5 on the client, but to take the Azure-compiled MD5 and expose it in the way apps like s3cmd expect.

Like I said before, I do believe that s3cmd is among the most valuable tools for S3 and I've seen it used everywhere (and I've been dreaming of having s3cmd for Azure for a while - saying this as an Azure user and MS employee :) )

**Comment by harshavardhana** [comment]
> Is there any chance you could alter the response from Azure to convert the MD5 hash in hex format and include it in the ETag header? This would improve compatibility. I'm not asking to compute MD5 on the client, but to take the Azure-compiled MD5 and expose it in the way apps like s3cmd expect.
> 

We will get back to you on this. 

> Like I said before, I do believe that s3cmd is among the most valuable tools for S3 and I've seen it used everywhere (and I've been dreaming of having s3cmd for Azure for a while - saying this as an Azure user and MS employee :) )

For now as a work-around i would recommend you to take a look at - https://github.com/minio/mc while we figure out what is the right thing to do here. 

Thanks for your patience.

**Comment by ItalyPaleAle** [comment]
Thanks @harshavardhana -  no rush here! (Although I have a really nice blog post to publish as soon as this is resolved :) )

I am familiar with mc and it does work pretty well. It's missing some key features of s3cmd, however, most notably encryption (although I guess that could possibly be done via a unix pipe).

**Comment by harshavardhana** [comment]
> I am familiar with mc and it does work pretty well. It's missing some key features of s3cmd, however, most notably encryption (although I guess that could possibly be done via a unix pipe).

Our client library already has support for this (https://github.com/minio/minio-go#api-reference-encrypted-object-operations) 

`mc` is just waiting on https://github.com/minio/mc/pull/2140 -  while s3cmd implements only server side encryption support. `mc` will do both server and fully client side.

**Comment by ItalyPaleAle** [comment]
s3cmd implements encryption on the client-side (e2e) with OpenPGP

**Comment by harshavardhana** [comment]
> s3cmd implements encryption on the client-side (e2e) with OpenPGP

Oh yes my bad,  this is incompatible with the approach I am mentioning perhaps this feature in s3cmd might predate the newer style for client side encryption standardized by AWS S3 -
 http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryptionUpload.html 

I see that it uses gpg_encrypt to create a temporary output file and then upload.

**Comment by krishnasrinivas** [comment]
@EgoAleSum can you verify that it works for you fine with this  https://github.com/krishnasrinivas/minio/tree/append-dash-one-etag

**Comment by krishnasrinivas** [comment]
@EgoAleSum just verified, still getting:
```
DEBUG: MD5 sums: computed=73c2ee0acb590362c0ac3740f8c39523, received="0x8D4C4CCE4CF5281-1"
```
I have updated https://github.com/s3tools/s3cmd/issues/880

**Comment by ItalyPaleAle** [comment]
Thanks for checking, I haven't had time to try it myself yet. Sad it didn't work :(

**Comment by ItalyPaleAle** [comment]
@krishnasrinivas do you know when this will be included into a stable release? Thanks

**Comment by krishnasrinivas** [comment]
appending `-1` is already included in the stable release of minio @EgoAleSum :
```
Content-Length: 2461
Accept-Ranges: bytes
Content-Md5: QdZKnimeZ7Xjc5AcnVLfjw==
Content-Type: application/octet-stream
Date: Mon, 23 Oct 2017 22:22:57 GMT
Etag: "0x8D5079EF8D94F0D-1"
Last-Modified: Sat, 30 Sep 2017 01:02:50 GMT
Server: Minio/RELEASE.2017-09-29T19-16-56Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14F053389B0FABFB

```

**Comment by ItalyPaleAle** [comment]
It's still missing this commit: https://github.com/harshavardhana/minio/commit/74c051d33a20d6ca0d02664e7dc05ca51d586527

Do you know when it will be included into a release?

**Comment by harshavardhana** [comment]
That is not released yet @EgoAleSum

**Comment by deathname** [comment]
Is the above-mentioned issue is fixed now?
I am getting **"ETag from S3 did not match the compute MD5"** error when I tried to connect my boto client to Azure storage.

**Comment by harshavardhana** [comment]
Etag is never meant to be md5 all the time, which tool are you using ?

**Comment by deathname** [comment]
Actually, I was receiving a warning whenever I tried to use PUT/ POST command using s3cmd which is hitting **minio azure gateway**  and that's warning is because of **MD5 sum don't match**. What will be possible resolution

**Comment by harshavardhana** [comment]
> Actually, I was receiving a warning whenever I tried to use PUT/ POST command using s3cmd which is hitting **minio azure gateway** and that's warning is because of **MD5 sum don't match**. What will be possible resolution

which version of s3cmd?

**Comment by deathname** [comment]
It is **s3cmd version 1.6.0** and warning for MD5 sum don't match occur during PUT/POST commands

**Comment by harshavardhana** [comment]
> It is **s3cmd version 1.6.0** and warning for MD5 sum don't match occur during PUT/POST commands

you need to use v2.0.1 https://github.com/s3tools/s3cmd/issues/880
 to have the right fixes for s3cmd to ignore certain etags, upgrade your s3cmd version

```
commit 9dd2586b6d447d156122cde4d44139a059aae623 (origin/pr/923, harsha/fix-etag)
Author: Harshavardhana <harsha@minio.io>
Date:   Sat Oct 7 17:48:38 2017 -0700

    Don't need to compute ETag md5sum match if it is not a real md5sum
    
    Fixes https://github.com/s3tools/s3cmd/issues/880
```

**Comment by deathname** [comment]
Thank you @harshavardhana for the reply. I need to ask one more thing I am facing same warning issue using **boto2** when uploading data in multipart, should I need to upgrade to boto3 or there is some solution in boto2

**Comment by harshavardhana** [comment]
You should turn off checking md5 in boto @deathname

**Comment by deathname** [comment]
Hi, @harshavardhana I just want to know whether Minio can support connection with multiple Azure accounts at runtime or not. Because in my case I need connections to different Azure accounts based on runtime status.

**Comment by harshavardhana** [comment]
@deathname our idea is you run one instance per account

**Comment by deathname** [comment]
> @deathname our idea is you run one instance per account

Okay

**Comment by deathname** [comment]
Out of curiosity, I want to know whether Minio supports Azure Client-site encryption or not when Minio's gateway is azure.

**Comment by harshavardhana** [comment]
> Out of curiosity, I want to know whether Minio supports Azure Client-site encryption or not when Minio's gateway is azure.

We do not feel free to open a github issue we will evaluate.

**Comment by deathname** [comment]
It means right now Minio itself does encryption/decryption of data based upon algorithm provided by the customer and transfer that data to cloud storage.

**Comment by deathname** [comment]
For our use-case, we want to modify client's request before minio process it and do some operations on the response. Please suggest us the best way to do it.
It would be great if we can have pre-request and post-response handlers to include our custom code.

**Comment by deathname** [comment]
Hi @harshavardhana,
One more query in addition to above, we'd like to raise two feature requests - 
1. Support for multiple azure accounts
2. Support for pre-request and post-response handlers.

Kindly let us know, what is the process to raise a feature request?

**Comment by harshavardhana** [comment]
> Kindly let us know, what is the process to raise a feature request?

Open a new GitHub issue stating feature request for Azure gateway

**Comment by deathname** [comment]
Hi, @harshavardhana 
In our case, we store our data in azure, which is encrypted by azure-client. And, we want to download the data using Minio. Since the data is encrypted, we would need to decrypt it using any azure Go sdk.

So, is there a way in minio to decrypt the data, or if there is any Azure Go sdk which support this decryption?
