### ISSUE TITLE
Support for Azure blob storage REST API

### ISSUE THREAD

**Issue by daigok** [minio/minio#4540]
Add support for Azure blob storage too.

**Comment by harshavardhana** [comment]
> Add support for Azure blob storage too.

We already have gateway feature with azure `minio gateway azure` are you talking about this @daigok ?

**Comment by daigok** [comment]
@harshavardhana No. I'm talking about a Blob Storage SDK. We want to use a Azure Blob Storage SDK to our service. Because our serivce supports both Azure and on-premise. Azure SDK/tools are better than S3 SDK/tools for us. So if minio is compatible with a Azure Blob Stroage, it really helpful for us. 

We could'nt find any  Azure Blob Storage copatible object storage other than a Microsoft's storage emulator and Azure Stack. Minio's architecture is simply and easy to extend compare to other object storage products. Hence, I've posted this enhancement request.

**Comment by deekoder** [comment]
@daigok  I don't think we plan to support a drop in replacement for Azure SDK/tools at this time :(   We are committed however to providing an s3 compatible interface to Azure blob storage. I will close this issue as a won't fix for now. Please reopen if you still think otherwise.
