### ISSUE TITLE
about the  performance 

### ISSUE THREAD

**Issue by luomaofu** [minio/minio#4544]
1. there are two backends : fs and xl . 
What is the difference between them? What's short for xl?

2.   in fs backend, A bucket is equivalent to a directory . and Bucket of object, is a file in the directory.
  so ,   Stored in a bucket of hundreds of millions of objects, means :  Stored in a directory  of hundreds of millions of files,  and the performance will be very slow.

fs-v1.go , line  392
```sh
	// Read the object, doesn't exist returns an s3 compatible error.
	fsObjPath := pathJoin(fs.fsPath, bucket, object)
	reader, size, err := fsOpenFile(fsObjPath, offset)
	if err != nil {
		return toObjectErr(err, bucket, object)
	}
	defer reader.Close()
```

**Comment by krisis** [comment]
@merlin-cn,
> there are two backends : fs and xl .
What is the difference between them? What's short for xl?

https://github.com/minio/minio/pull/4538 answers the above questions. XL is used to refer to the erasure code backend.

>in fs backend, A bucket is equivalent to a directory . and Bucket of object, is a file in the directory.
so , Stored in a bucket of hundreds of millions of objects, means : Stored in a directory of hundreds of millions of files, and the performance will be very slow.

The performance may degrade if millions of objects are uploaded in to a single bucket. One way to alleviate this problem is to use prefixes along with object names to reduce the number of files in a directory.

E.g `store/dept/obj1`

where `store` is the bucket name, `dept` is a prefix and `obj1` is the object name.

This translates to the following directory structure in the backend.
```
└── store
    └── dept
        └── obj1

```

**Comment by harshavardhana** [comment]
> in fs backend, A bucket is equivalent to a directory . and Bucket of object, is a file in the directory.
> so , Stored in a bucket of hundreds of millions of objects, means : Stored in a directory of hundreds of millions of files, and the performance will be very slow.
> 

This is not a problem of object storage as such, any given filesystem is generally slower if you create lots of files in a single directory - but with proper directory structure employed it can be easily avoided.

http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html  - Amazon wrote a nice article about this which also applies in this case as well on how to work towards scaling your app with storage.

**Comment by luomaofu** [comment]
some performace test:

upload one object,  cost 8 ms at least ,it is very  slow. 



client

```python
# Import Minio library.
from minio import Minio
from minio.error import (ResponseError, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)
import time
# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('192.168.60.16:9000',
                    access_key='TIU991MT3O0VD5G7WMOI',
                    secret_key='rWyAvMzTSAvTeD8N6zRVPX8Dabpo2Zh/9rKYCSwG',
                    secure=False)

try:
    a= time.time()
    print "upload file " + str(a)
    minioClient.fput_object('abc', str(a), '/tmp/test.log')
    b = time.time()
    print b-a
    """
    c= time.time()
    print "download  file " + str(a)
    data = minioClient.get_object('abc', str(a))
    with open('my-testfile', 'wb') as file_data:
        for d in data.stream(32*1024):
            file_data.write(d)
    b = time.time()
    print b-c
    """
except ResponseError as err:
    print(err)


```

```sh
[root@localhost ~]# python f.py 
upload file 1497587559.88
0.0116341114044
[root@localhost ~]# 

```

the trace:

```sh
[pid 14699] 1497587559.885628 stat("/export/abc", {st_mode=S_IFDIR|0755, st_size=153, ...}) = 0
[pid 14699] 1497587559.888792 stat("/export/abc", {st_mode=S_IFDIR|0755, st_size=153, ...}) = 0
[pid 14699] 1497587559.888988 stat("/export/abc", {st_mode=S_IFDIR|0755, st_size=153, ...}) = 0
[pid 14699] 1497587559.889135 stat("/export/.minio.sys/buckets/abc/1497587559.88", 0xc42028eac8) = -1 ENOENT (No such file or directory)
[pid 14699] 1497587559.889379 stat("/export/.minio.sys/buckets/abc", {st_mode=S_IFDIR|0755, st_size=153, ...}) = 0
[pid 14699] 1497587559.889516 mkdirat(AT_FDCWD, "/export/.minio.sys/buckets/abc/1497587559.88", 0777) = 0
[pid 14699] 1497587559.889778 openat(AT_FDCWD, "/export/.minio.sys/buckets/abc/1497587559.88/fs.json", O_RDWR|O_CREAT|O_SYNC|O_CLOEXEC, 0666) = 8
[pid 14699] 1497587559.890021 stat("/export/.minio.sys/buckets/abc/1497587559.88/fs.json", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid 14699] 1497587559.890197 stat("/export/.minio.sys/tmp/d089c64a-53ee-4ba4-8400-ce25e904b180", {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
[pid 14699] 1497587559.890309 statfs("/export/.minio.sys/tmp/d089c64a-53ee-4ba4-8400-ce25e904b180", {f_type=0x58465342, f_bsize=4096, f_blocks=13100800, f_bfree=11799334, f_bavail=11799334, f_files=26214400, f_ffree=25860206, f_fsid={64768, 0}, f_namelen=255, f_frsize=4096}) = 0
[pid 14699] 1497587559.890471 openat(AT_FDCWD, "/export/.minio.sys/tmp/d089c64a-53ee-4ba4-8400-ce25e904b180/75e152c5-af4a-4977-a7c6-7265440769cd", O_WRONLY|O_CREAT|O_CLOEXEC, 0666) = 9
[pid 14699] 1497587559.891190 stat("/export/abc", {st_mode=S_IFDIR|0755, st_size=153, ...}) = 0
[pid 14699] 1497587559.891292 renameat(AT_FDCWD, "/export/.minio.sys/tmp/d089c64a-53ee-4ba4-8400-ce25e904b180/75e152c5-af4a-4977-a7c6-7265440769cd", AT_FDCWD, "/export/abc/1497587559.88") = 0
[pid 14699] 1497587559.892929 stat("/export/abc/1497587559.88", {st_mode=S_IFREG|0644, st_size=1263, ...}) = 0
[pid 14699] 1497587559.893041 unlinkat(AT_FDCWD, "/export/.minio.sys/tmp/d089c64a-53ee-4ba4-8400-ce25e904b180/75e152c5-af4a-4977-a7c6-7265440769cd", 0) = -1 ENOENT (No such file or directory)
[pid 14699] 1497587559.893134 unlinkat(AT_FDCWD, "/export/.minio.sys/tmp/d089c64a-53ee-4ba4-8400-ce25e904b180/75e152c5-af4a-4977-a7c6-7265440769cd", AT_REMOVEDIR) = -1 ENOENT (No such file or directory)



```

```sh
0.893134 -0.885628 = 0.007506000000000013  // minio cost

0.0116341114044 -  0.007506000000000013  = 0.004128111404399988   //other coat (network io , etc ...)
```


 I think it needs to be improved

**Comment by fwessels** [comment]
> some performace test:
>
> upload one object, cost 8 ms at least ,it is very slow.

Object storage is designed for (very) large objects, starting at 100KB at the minimum up to 10s of GBs or even larger. Likewise it is designed to be used in parallel, i.e. you can upload 10s or 100s of objects in parallel without any problems.

So your duration for measuring a single PUT is more or less what we would expect, but to really get an idea of the performance you need to test in parallel. Also I think you will find that if you increase the size of your objects (32KB now which is quite small for object storage) tenfold, you will just see a small increase in the overall duration for a single PUT operation.

In our performance tests we typically saturate the (incoming) network bandwidth first before hitting CPU, memory or disk limits (given decent server hardware). So you can easily upload 1000s of objects/sec generating Gbit/s of incoming network traffic.

Lastly, note that object storage is not designed as a "generic" key/value store where you can go to 100K  operations/second such as for instance a redis store (where typically the objects or values are in the kilobyte size). Also minio will commit to disk before signalling success back to the client whereas for example redis will initially keep state in memory before flushing it out to disk. Both approaches have pros and cons and serve a different purpose/use case.

**Comment by deekoder** [comment]
@merlin-cn  closing this issue. Please reopen if you think we have not addressed your concern here.
