### ISSUE TITLE
docs: More information about the webhook server are needed

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4545]
What's missing:
1. Brief information about the content and format of the data that webhook server will receive
2. Say what the webhook server should return as information to Minio server

**Comment by harshavardhana** [comment]
Webhook doesn't need to send anything to Minio server..it's only a receiving end.

What is sent on the wire can be easily seen by using request.bin

**Comment by vadmeste** [comment]
yes, I am just saying we need to update this documentation https://docs.minio.io/docs/minio-bucket-notification-guide#webhooks so users can easily understand what this is about.

**Comment by deekoder** [comment]
Needs a link to this doc http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

**Comment by MontyGvMC** [comment]
May the documentation could also contain examples on how to consume webhooks in various libraries/languages.

It seems to be impossible to consume the webhook via .NET Core 1 & 2 without implementing an exact model class (or more precise exact model classes) of [http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html](http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html).

**Comment by harshavardhana** [comment]
> It seems to be impossible to consume the webhook via .NET Core 1 & 2 without implementing an exact model class (or more precise exact model classes) of http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html.
>  

Are you saying that with .NET Core you cannot parse the notified event structure in json?

**Comment by MontyGvMC** [comment]
Well, the explanation for the problem would be longer and mainly .NET Core related (and less Minio related).

So I allowed myself to open a [dedicated issue](https://github.com/minio/minio/issues/5204) for consuming the webhook in .NET Core.
