### ISSUE TITLE
OwnerID too short; does not match AWS spec

### ISSUE THREAD

**Issue by TJC** [minio/minio#4553]
Minio reports the OwnerID as just "minio", but this causes at least one S3 library to fail, as they expect a 64 character string.

The AWS specifications say:
> The canonical user ID is the Amazon S3–only concept. It is s
> 64-character obfuscated version of the account ID.

That quote taken from: http://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example4.html

Failing S3 client: https://github.com/rustyconover/net-amazon-s3/issues/18
My patch for it: https://github.com/strategicdata/net-amazon-s3/commit/1b9b52d3aece937cb853b1f9f25bb3bab2713310

I'm not sure this really needs to be fixed in Minio, but I thought I would alert you to the issue.

**Comment by harshavardhana** [comment]
There is no concept of OwnerID in Minio it just kept as a placeholder value which defaults to "minio" . We can generate something of the 64-bit obfuscated version just for compatibility sake - it doesn't add much value honestly and there is no value for the client to interpret this if they are using Minio.

**Comment by harshavardhana** [comment]
> There is no concept of OwnerID in Minio it just kept as a placeholder value which defaults to "minio" . We can generate something of the 64-bit obfuscated version just for compatibility sake - it doesn't add much value honestly and there is no value for the client to interpret this if they are using Minio

But it makes sense to just keep it similar in meaning. Thanks for opening the bug @TJC .
