### ISSUE TITLE
specify minio server region using environment variable

### ISSUE THREAD

**Issue by shantanugadgil** [minio/minio#4555]
Is there a way to specify the region using an environment variable, rather than the config.json?

I went through the docs, but found the method to set region by modifying the config.json.
That works fine, but was wondering if there is any `MINIO_REGION` type of variable that can be used?

My use case is that modifying the config.json at runtime may not be possible, but setting environment variables would be during the start of `minio`.

Thanks and Regards,
Shantanu

**Comment by krisis** [comment]
@shantanugadgil Yes, `MINIO_REGION` is the environment variable you are looking for.
E.g, you could run,
 ```sh
export MINIO_REGION="my_region"
minio server /path/to/dir
```

**Comment by shantanugadgil** [comment]
@krisis thanks, this works for me!
