### ISSUE TITLE
[stale] High level architecture document

### ISSUE THREAD

**Issue by fwessels** [minio/minio#4557]
Create a high level architecture document describing the key components of minio's design in terms of objectapihandlers, object handlers (fs/xl/distributed), erasure coding, bitrot, server vs gateway, etc.

Initial version will contain the high level structure without all the details, once the structure is in place, we can fill in the details to the level that we want.

**Comment by fwessels** [comment]
First version available under https://github.com/fwessels/minio/blob/feature/design-doc/DESIGN.md

**Comment by harshavardhana** [comment]
@fwessels is this waiting on code re-org ?

**Comment by fwessels** [comment]
Re-org would definitely help I think, but timing may be to far out. Let's discuss, we can "finish" an interim version.

**Comment by TennyZhuang** [comment]
Is there any latest version of the doc?

**Comment by fwessels** [comment]
No, this is still the latest version

**Comment by congweitao** [comment]
please what is the sitution now ?

**Comment by harshavardhana** [comment]
Closing this as we will get to this in future.. no current cycles available.

**Comment by Junaiid-Ahmad** [comment]
Just checking if there is some update on this document?
I only know about the first version here https://github.com/fwessels/minio/blob/feature/design-doc/DESIGN.md

**Comment by fwessels** [comment]
No, there's no update (and the document is getting more out of sync, so we should probably retire it).
