### ISSUE TITLE
Propose or enhance new feature template

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4559]
This will help PR reviewing and testing.

**Comment by krisis** [comment]
The existing PR and issue template capture relevant information. We need to ensure that all contributors follow them. @deekoder this issue can be closed.

**Comment by krisis** [comment]
The existing PR and issue template capture relevant information. We need to ensure that all contributors follow them. @deekoder this issue can be closed.

**Comment by krisis** [comment]
@deekoder this issue can be closed as discussed.
