### ISSUE TITLE
Submit Dockerfile to official Docker library

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4565]
## Expected Behavior
Docker has a public repo: https://github.com/docker-library/official-images that hosts the _official images_. They also have detailed documentation on how to contribute to the repo: https://github.com/docker-library/official-images#contributing-to-the-standard-library

We can take a look at the process and add Minio Dockerfile to the standard library

## Current Behavior
Minio Docker image is not on the standard library

## Possible Solution
https://github.com/docker-library/official-images#contributing-to-the-standard-library

## Context
Minio Docker image should be among Official Docker Images

**Comment by harshavardhana** [comment]
To do this first we need to figure out who actually maintains official images. Does the maintainer pushes the changes? if so does he do manually? can this be auto built like how we build our image after a release. what is the difference between docker official images v/s minio built official images? does docker promise some sort of higher availability? 

Also this would require a disruptive change basically we will have to remove our organization or some-how rename it i.e `hub.docker.com/r/minio`  we tried to do this previously and this was one of the reason we discarded the idea.

**Comment by nitisht** [comment]
> To do this first we need to figure out who actually maintains official images. Does the maintainer pushes the changes? if so does he do manually? can this be auto built like how we build our image after a release. 

Whoever sends the PR for the official repo is supposed to maintain it. Details: https://github.com/docker-library/official-images#maintainership. Looks like Maintainer has to do this manually. It can be built automatically but Maintainer has to push changes to the Dockerfile first.  

> what is the difference between docker official images v/s minio built official images? does docker promise some sort of higher availability?

I don't think so, but there are a few advantages. Quoting their docs here: 

> The Docker Official Repositories are a curated set of Docker repositories that are promoted on Docker Hub. They are designed to:
> - Provide essential base OS repositories (for example, ubuntu, centos) that serve as the starting point for the majority of users.
> - Provide drop-in solutions for popular programming language runtimes, data stores, and other services, similar to what a Platform-as-a-Service (PAAS) would offer.

More info here: https://docs.docker.com/docker-hub/official_repos/

**Comment by harshavardhana** [comment]
We can definitely do this. 

What we need to figure out is if automated build is possible across platforms - Basically doing manual approach for docker build is a bad idea and can lead to unforseen security issues.. building on docker cloud is the safest approach that is why we use automated build and download over SSL. We need to see how this is allowed.

**Comment by nitisht** [comment]
Since we're not going ahead with https://github.com/minio/minio/pull/4877 closing this as won't fix for now. We can revisit later if required.
