### ISSUE TITLE
Disable color in the text output

### ISSUE THREAD

**Issue by shantanugadgil** [minio/minio#4568]
Minio version: 2017-06-13T19:01:01Z

Would it be possible for a `--no-color` (or some such) parameter to disable the color output?
I run **minio server** as an upstart service on Ubuntu 14.04 and the output in the upstart logs at `/var/log/upstart/minio.log` is full of ANSI color escape sequences.
It would be great if there were an option to disable color in the output.

## Current Behavior
Log files contain ANSI color sequences.

## Possible Solution
Possibly a parameter like '--no-color` to disable output.

## Your Environment

* Version used (`minio version`): 2017-06-13T19:01:01Z
* Operating System and version (`uname -a`): Ubuntu 14.04

**Comment by harshavardhana** [comment]
> Would it be possible for a --no-color (or some such) parameter to disable the color output?
> I run minio server as an upstart service on Ubuntu 14.04 and the output in the upstart logs at /var/log/upstart/minio.log is full of ANSI color escape sequences.
> It would be great if there were an option to disable color in the output.

You can simply do `--quiet` if you don't need any output banner. NOTE this will still print error logs..

**Comment by shantanugadgil** [comment]
Using quiet doesn't work. This makes it completely silent (with error logs as you mentioned)
I _do_ want the startup banner, just without coloring!

**Comment by harshavardhana** [comment]
> Using quiet doesn't work. This makes it completely silent (with error logs as you mentioned)
> I do want the startup banner, just without coloring!

Another simpler way is just doing pipe the output so that the console printer thinks that its a dumb terminal. 

```
script
        exec /usr/local/bin/minio --config-dir $MINIOCONFIGPATH server $MINIOVOLUMES | tee
end script
```

**Comment by harshavardhana** [comment]
You can even do this 

```
env TERM=dumb
script
        exec /usr/local/bin/minio --config-dir $MINIOCONFIGPATH server $MINIOVOLUMES
end script
```

**Comment by shantanugadgil** [comment]
perfect, this does the trick:
`env TERM=dumb`
