### ISSUE TITLE
Minio can be used in the production environment?

### ISSUE THREAD

**Issue by luomaofu** [minio/minio#4571]
Minio can be used in the production environment?
is there  some successful case?
thank you

**Comment by harshavardhana** [comment]
> Minio can be used in the production environment?

Yes you can. 

> is there some successful case?

https://blog.minio.io/scalable-genomics-data-processing-pipeline-with-alluxio-mesos-and-minio-a8360e54b11a

https://blog.minio.io/toolslib-switches-to-minio-for-scale-and-performance-7510eb1f866f

You can take a look at all the use cases listed here - https://github.com/minio/awesome-minio

**Comment by deekoder** [comment]
@merlin-cn  closing this issue. Let us know if you have any further questions.
