### ISSUE TITLE
Shared link doesn't encode spaces, breaks url up

### ISSUE THREAD

**Issue by jcoetzee** [minio/minio#4573]
## Expected Behavior
I expect that when sharing a link (via web browser) to a file with someone they should be able to click it directly to download regardless of if the filename has spaces in it or not.

## Current Behavior
If the filename has spaces in it it breaks the url so it cannot be clicked. The URL will need to be manually copied and pasted into a browser

## Possible Solution
When sharing, spaces should be encoded as '+' in accordance with S3 schematics.

## Steps to Reproduce (for bugs)
1. Upload file with spaces in the name.
2. Share file (via web interface) and copy link.
3. Paste link.
4. Try click resulting link.

## Your Environment
* Version used (`minio version`): Release-Tag: RELEASE.2017-06-13T19-01-01Z
* Server type and version: Docker
* Operating System and version (`uname -a`): Ubuntu 16.04

**Comment by vadmeste** [comment]
Browsers (at least Chrome & Firefox) naturally convert a space to %20 when pasted in the url bar and opened but curl doesn't. I think we should encode the object prefix after signature calculation.

**Comment by jcoetzee** [comment]
Yes, however that still would require you to manually highlight, copy and paste into the URL bar instead of just clicking on the link. This would also cause confusion for those not technically minded.
