### ISSUE TITLE
Authentication information is added to shared URL even if prefix is set to public readable

### ISSUE THREAD

**Issue by jcoetzee** [minio/minio#4574]
This is something minor but when sharing a file in a prefix that is public readable authentication information is added even though it isn't needed.

## Expected Behavior
If the bucket policy allows anonymous download anyway then I would expect a simpler URL to share.

## Current Behavior
The authentication information (`?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...`) is added to the shared URL 

## Possible Solution
Don't append authentication information for a file that can be downloaded without it.

## Steps to Reproduce (for bugs)
1. Set read policy on bucket
2. Share file
3. Notice that authentication information is included even though the policy allows for anonymous download.

## Your Environment
* Version used (`minio version`): 2017-06-13T19:01:01Z

**Comment by harshavardhana** [comment]
If you access the object without logging in then you don't see this problem. To login to a publicly readable bucket you just have to logout and visit the http://endpoint:9000/minio/bucket 

Looks like currently the check is only making sure to avoid signature generation only for anonymous requests.

**Comment by deekoder** [comment]
@jcoetzee closing this issue. Please reopen if you think we have not addressed this issue.
