### ISSUE TITLE
Upload via web hangs at completion when using nginx as reverse proxy

### ISSUE THREAD

**Issue by jcoetzee** [minio/minio#4579]
When uploading to a bucket via the web interface using nginx as reverse proxy the upload hangs just before completion.

## Expected Behavior
File uploaded to bucket

## Current Behavior
1. If file sizes are small enough (order of 80KB) the upload succeeds however for larger files the upload hangs (smallest file I've found to do this is 1.7Mb)
2. Upload doesn't hang at the same percentage every time but it tends to be near completion (i.e. for larger files it's pretty consistently 99-100%)
2. Upon refreshing the page the file is not present in the bucket
3. The file doesn't show when using `mc ls` either

![screen shot 2017-05-19 at 10 19 03 pm](https://cloud.githubusercontent.com/assets/1784961/26265468/850ca6c0-3ce1-11e7-91c4-8f070a910572.png)

## Steps to Reproduce (for bugs)
1. Use nginx as a reverse proxy to minio
1. Upload file to bucket via web interface

## Your Environment
* Version used (`minio version`): 2017-06-13T19:01:01Z
* Environment name and version (e.g. nginx 1.9.1): nginx 1.13.1
* Operating System and version (`uname -a`): Ubuntu 16.04.2 LTS. Linux 4.4.0-79

### nginx config
    server {
        listen 8443 ssl http2;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256'; 
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security max-age=15768000;

        ssl_client_certificate /etc/ssl/root_ca.pem;
        ssl_verify_client on;
        ssl_verify_depth 2;
        
        server_name minio.domain.tld;
        ssl_certificate /etc/ssl/minio/minio.domain.tld.pem;
        ssl_certificate_key /etc/ssl/minio/minio.domain.tld.key;

        location / {
                proxy_buffering off;
                proxy_pass http://minio:9000;
                proxy_redirect http://minio:9000 https://minio.domain.tld/;
                proxy_cache proxy_cache;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-for $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_read_timeout 600;
                port_in_redirect off;
        }
    }

**Comment by deekoder** [comment]
@krishnasrinivas  - i feel like this was a bug we had seen before and was closed as a "works for me".

**Comment by jcoetzee** [comment]
@deekoder Yes, that was #4375 but that was closed before I realised that this is only experienced when using nginx as reverse proxy.

**Comment by harshavardhana** [comment]
> @deekoder Yes, that was #4375 but that was closed before I realised that this is only experienced when using nginx as reverse proxy.

@jcoetzee have you tried using the simplest nginx config mentioned in our docs - https://docs.minio.io/docs/setup-nginx-proxy-with-minio  and see if that actually works? 

This would help us narrow down the variables.

**Comment by jcoetzee** [comment]
The bug is still present with the following config

    server {
        listen 8443 ssl;
        
        server_name minio.domain.tld;
        ssl_certificate /etc/ssl/minio/minio.domain.tld.pem;
        ssl_certificate_key /etc/ssl/minio/minio.domain.tld.key;

        location / {
                proxy_buffering off;
                proxy_pass http://minio:9000;
                proxy_set_header Host $host;
        }
    }

**Comment by jcoetzee** [comment]
This is my fault. I forgot to add the `client_max_body_size` directive as indicated in the notes below the example config.

For reference that directive doesn't need to be in the `http` context, it can be in the `server` or `location` directives as well. May be an idea to just put it in the example config?
