### ISSUE TITLE
server follows symlinks

### ISSUE THREAD

**Issue by walterdejong** [minio/minio#4588]
It is possible to make a symbolic link to a directory that points outside the `minio` server "root". The server will happily serve this as a bucket, potentially giving access to unexpected places.

## Expected Behavior

I expected the server would not allow access outside the server "root".

## Current Behavior

Current: The server follows symbolic links. This allows remote users to access files outside the served up tree.
Difference: Do not allow this to happen.

## Possible Solution

Maybe the server could check it by doing something like `abspath` or `realpath`.

A simple fix could be having an option like `"followsymlinks": "no"`.

## Steps to Reproduce (for bugs)

1. mkdir s3test
2. cd s3test
3. ln -s root /
4. minio server ~/s3test
5. mc cat mys3/root/etc/passwd

## Context

The company where I work hosts interactive servers where remote users login with ssh.
Therefore they can create symbolic links whenever and wherever they want to.
We would like to allow them to use `minio` to give them S3 access to their files.
This poses too much of a security risk at the moment.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

```
Version: 2017-06-23T08:28:12Z
Release-Tag: DEVELOPMENT.2017-06-23T08-28-12Z
Commit-ID: 9d3d64df2de89518345ce01d52d8c10def874699

SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
```

**Comment by harshavardhana** [comment]
I have a question @walterdejong are you asking if Minio server should run in a chrooted env ? if yes then we can add that support to be default always. 

You can still achieve this today by doing `chroot /path /path/minio server export` , this would disallow minio to access outside namespace and provides proper isolation.

**Comment by walterdejong** [comment]
`chroot` could certainly be a solution. Note that only the `root` user may start a chrooted environment; a regular user gets `Operation not permitted`. I can probably cook up a sudo-wrapper for this.

I think it would still be nice if the symlink behavior were configurable via a (command-line) option.
I can imagine some people would actually want to use "followsymlink" as a feature--while others don't.

**Comment by harshavardhana** [comment]
If Minio server needs to chroot that would put the same restriction on Minio server as well.

Minio server is statically compiled it is ideal to run it in `chroot` environment. While the chroot has to be run as root the resulting process can easily run as a regular user using chroot command line options.

**Comment by walterdejong** [comment]
Unfortunately `chroot` is not a very good solution for us.

I can get it to work but it requires a minimal "root" filesystem like:
```
$HOME/
  dev/urandom
  bin/minio
  lib64/ld-linux-x86-64.so.2
  lib64/libc.so.6
  lib64/libpthread.so.0
  home/walter/.minio/config.json
  home/walter/.minio/certs/private.key
  home/walter/.minio/certs/public.crt
  serverroot/

# chroot --userspec 501:501 /home/walter /bin/minio server serverroot/
```

It's too convoluted for our users.

Additionally, I had a look at `syscall.Chroot()` but it looks like golang no longer supports it (because of portability issues). This means that `chroot` can't be built in.

The easy fix would be to optionally disallow symlinks.
The less easy fix would be to use a `realpath()`-like construction to check all paths against the "serverroot".


----

It's not important to me, but as a side note: when you create symlinks that point outside the chroot, the program won't start:
```
~/s3test # chroot --userspec 501:501 /home/walter/s3test /bin/minio server /serverroot
ERRO[0000] Unable to list buckets.                       cause=disk not found source=[bucket-policy.go:85:loadAllBucketPolicies()] stack=fs-v1.go:239:fsObjects.ListBuckets <autogenerated>:360:(*fsObjects).ListBuckets bucket-policy.go:84:loadAllBucketPolicies bucket-policy.go:127:initBucketPolicies fs-v1.go:141:newFSObjectLayer server-main.go:304:newObjectLayer server-main.go:280:serverMain /home/walter/src/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:github.com/minio/minio/vendor/github.com/minio/cli.HandleAction /home/walter/src/go/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:github.com/minio/minio/vendor/github.com/minio/cli.Command.Run /home/walter/src/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run main.go:145:Main /home/walter/src/go/src/github.com/minio/minio/main.go:68:main.main /usr/lib64/go/1.8/src/runtime/proc.go:185:runtime.main /usr/lib64/go/1.8/src/runtime/asm_amd64.s:2197:runtime.goexit
FATA[0000] Initializing object layer failed              cause=Unable to load all bucket policies. disk not found source=[server-main.go:281:serverMain()]
```

**Comment by harshavardhana** [comment]
> Unfortunately chroot is not a very good solution for us.
> 
> I can get it to work but it requires a minimal "root" filesystem like:
> 
> $HOME/
>   dev/urandom
>   bin/minio
>   lib64/ld-linux-x86-64.so.2
>   lib64/libc.so.6
>   lib64/libpthread.so.0
>   home/walter/.minio/config.json
>   home/walter/.minio/certs/private.key
>   home/walter/.minio/certs/public.crt
>   serverroot/
> 
> $ chroot --userspec 501:501 /home/walter /bin/minio server serverroot/

Actually this is not correct you must be using an older release of Minio. Latest release doesn't need these files - here are the steps. 

```
$ mkdir /mnt/sdd1/harsha/bin
$ wget https://dl.minio.io/server/minio/release/linux-amd64/minio -O /mnt/sdd1/harsha/bin/minio
$ chmod +x /mnt/sdd1/harsha/bin/minio
```

```
$ chroot --userspec harsha:harsha /mnt/sdd1/harsha /bin/minio --config-dir=/.minio server root

Endpoint:  http://192.168.1.92:9000  http://65.19.167.92:9000 
AccessKey: MVPSPBW4NP2CMV1W3TXD 
SecretKey: X3RKxEeFOI8InuNWoPsbG+XEVoaJVCqbvxe+PTOa 

Browser Access:
   http://192.168.1.92:9000  http://65.19.167.92:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.92:9000 MVPSPBW4NP2CMV1W3TXD X3RKxEeFOI8InuNWoPsbG+XEVoaJVCqbvxe+PTOa

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 3.0 TiB Free, 3.6 TiB Total
```

You can have a skeletal structure for this which provisions minio on all servers. 

> The easy fix would be to optionally disallow symlinks.
> The less easy fix would be to use a realpath()-like construction to check all paths against the "serverroot".

This is actually not a good fix/solution, the reasoning from our end goes like this. Creation of symlinks effects almost all tools not just minio server.  A new user who has been given ssh access to a server can indeed create a symlink and even copy data out by simply running a netcat service.  So the idea that just because minio server would disallow this makes it secure is actually wrong way to look at the problem (users should be disallowed to create root symlinks). Regardless of minio server supporting something like this - Its a problem not solved completely on your end.

Our suggestion here either use chroot or docker - these tools are meant to provide namespace isolation.

**Comment by walterdejong** [comment]
True, and I was afraid you might mention that.
Currently minio is a very single-user-at-home experience. Ideally, I wish minio server was more akin to a webserver: a service on a well-known port, able to serve up files for multiple users from their respective homedirs. Have PAM support for authentication. Use the server host certificate for TLS/SSL. Have a way to mark buckets as public and read-only for sharing/publication.
I hope you can do something with these ideas.

On topic: It seems (to me) sane to have at least the _option_ of not following symlinks in a file server.
If you disagree, feel free to close this issue.

**Comment by harshavardhana** [comment]
> True, and I was afraid you might mention that.
> Currently minio is a very single-user-at-home experience. Ideally, I wish minio server was more akin to a webserver: a service on a well-known port, able to serve up files for multiple users from their respective homedirs. Have PAM support for authentication. Use the server host certificate for TLS/SSL. Have a way to mark buckets as public and read-only for sharing/publication.
> I hope you can do something with these ideas.

We actually are working on STS (Token Service) based on SAML identity provider which should provide multi user support with in your organization. Given that your kerberos or ldap is part of a SAML identity federation. 

> On topic: It seems (to me) sane to have at least the option of not following symlinks in a file server.
> If you disagree, feel free to close this issue.

We will close this issue since chroot or docker (cgroups) solve this problem sufficiently.
