### ISSUE TITLE
Minio is not reusing or closing old/existing connections to Rabbit

### ISSUE THREAD

**Issue by TuiTeamSearch** [minio/minio#4597]
After setting up AMQP for bucket events, we are receiving events, but the RabbitMQ connection pool fills up quite quickly.

## Expected Behavior
One connection per bucket to RabbitMQ, or one Minio connection all together to multiple exchanges.

## Current Behavior
Roughly one connection per event, not quite sure but a lot of connections are created filling up the RabbitMQ connection pool

## Steps to Reproduce (for bugs)
1. Set up Rabbit
2. Set up Minio with AMQP with the following config:
      "my-bucket-events": {
	"enable": true,
        "url": "amqp://user:pass@host",
        "exchange": "myExchange",
        "routingKey": "",
        "exchangeType": "fanout",
        "deliveryMode": 2,
        "mandatory": false,
        "immediate": false,
        "durable": true,
        "internal": false,
        "noWait": false,
        "autoDeleted": false
      },
      "my-other-bucket-events": {
	"enable": true,
        "url": "amqp://user:pass@host",
        "exchange": "mySecondExchange",
        "routingKey": "",
        "exchangeType": "fanout",
        "deliveryMode": 2,
        "mandatory": false,
        "immediate": false,
        "durable": true,
        "internal": false,
        "noWait": false,
        "autoDeleted": false
      },
3. Upload files to buckets
4. Check connection pool in RabbitMQ -> should have a lot of connections
5. Try restarting Minio -> only new connections should be added, none closed

## Context
Since we are using CloudAMQP the number of connections are limited in various scenarios, and the connection quota is filled or at least an abnormal number of connections are present

## Your Environment
* Version used (`minio version`): 2017-05-05T01:14:51Z   (18?)
* Operating System and version (`uname -a`): Ubuntu 16.10

![client_props](https://user-images.githubusercontent.com/23450296/27531517-2d0c526a-5a5d-11e7-87fb-bce3a6591e0b.jpg)
![connectionlist](https://user-images.githubusercontent.com/23450296/27531516-2d0900f6-5a5d-11e7-9b64-1b4c234104c3.jpg)

**Comment by krisis** [comment]
@deekoder I can take this up.

**Comment by krisis** [comment]
@TuiTeamSearch Here is how I tried recreate the issue.

1. Ran RabbitMQ server in a docker container
```shell
docker run -d --hostname my-rabbit --name some-rabbit -p 5672:5672 -p 8080:15672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3-management
```
2. Used the configuration provided in the issue description.

**Comment by TuiTeamSearch** [comment]
Seems to be a network/firewall issue

**Comment by TuiTeamSearch** [comment]
We're still experiencing the same issue. This morning we had roughly 4500 connections to Rabbit

Currently running Minio version: 2017-08-05T00:00:53Z
We switched to a self-hosted RabbitMQ on a separate Machine.
Config above is still valid.

Today I set up the test locally on my Mac with Docker:
With remote rabbit it works as described above, tested both hosted on cloudamqp.com service as described above as well as a self-hosted Rabbit on another machine. We switched to this self-hosted Rabbit in our production environment.
However, with a Rabbit on local machine (docker container) it does not create new connections.

Worth noting is that all above cases are working as expected with our dockerized nodejs apps.

**Comment by TuiTeamSearch** [comment]
This is the result of `lsof` from our production environment, it's roughly 22k+ connections. This explains alot to us, since we see that Minio gets slow after awhile as well as not accepting new connections. We have not had any connectivity issues.

Please note also that when we kill all connections in Rabbit, Minio still holds them until the Minio service is restarted.

As stated in the Slack channel, each new file generates a new connection to Rabbit. It is not reproducable with a local container running RabbitMQ, it reproduces when RabbitMQ is on a remote machine.

[minio_lsof.txt](https://github.com/minio/minio/files/1259405/minio_lsof.txt)

**Comment by harshavardhana** [comment]
Thanks for letting us know @TuiTeamSearch do you have any minio console logs to share with us as well? - if you do have please share with us.
