### ISSUE TITLE
Distribution Minio with docker 

### ISSUE THREAD

**Issue by robben766** [minio/minio#4602]
I can run distributiion minio with linux follow this [Doc](https://docs.minio.io/docs/distributed-minio-quickstart-guide)
    However, I don't know how to work in docker .
    Try executing the command
   
 `  docker run -p 9000:9000 --rm --name minio \
  -e "MINIO_ACCESS_KEY=test" \
  -e "MINIO_SECRET_KEY=test" \
  -v /home/minio/export:/export \
  -v /home/minio/config/minio:/root/.minio \
  minio/minio server  \
http://192.168.2.1/home/minio/minio-export1 http://192.168.2.1/home/minio/minio-export2 http://192.168.2.1/home/minio/minio-export3 http://192.168.2.1/home/minio/minio-export4 \
http://192.168.2.2/home/minio/minio-export1 http://192.168.2.2/home/minio/minio-export2 http://192.168.2.2/home/minio/minio-export3 http://192.168.2.2/home/minio/minio-export4
`
   I got error
  `Waiting for all hosts to resolve...........All hosts are resolving proceeding to initialize Minio.
time="2017-06-26T12:55:55Z" level=fatal msg="Invalid command line arguments server=‘:9000’, args=[http://192.168.2.1/home/minio/minio-export1 http://192.168.2.1/home/minio/minio-export2 http://192.168.2.1/home/minio/minio-export3 http://192.168.2.1/home/minio/minio-export4 http://192.168.2.2/home/minio/minio-export1 http://192.168.2.2/home/minio/minio-export2 http://192.168.2.2/home/minio/minio-export3 http://192.168.2.2/home/minio/minio-export4]" cause="no endpoint found for this host" source="[server-main.go:144:serverHandleCmdArgs()]" `

**Comment by harshavardhana** [comment]
@robben766 for docker you should use swarm. https://docs.minio.io/docs/deploy-minio-on-docker-swarm

**Comment by robben766** [comment]
@harshavardhana Thanks for your quick response。why minio distribution with docker must use swarm. Can run in multi machine ?

**Comment by harshavardhana** [comment]
You can but you need to expose host networking use --net=host . Swarm is the most recommended if you are using only docker.

**Comment by robben766** [comment]
@harshavardhana it works now , Thanks.

**Comment by harshavardhana** [comment]
Feel free to close @robben766 if you have no more questions.

**Comment by tangkhaiphuong** [comment]
@harshavardhana today, I test again on Docker and got error

```
 sudo docker rm minio --force && sudo docker run -i -t -p 9090:9000 --name minio  -e "MINIO_ACCESS_KEY=demo"  -e "MINIO_SECRET_KEY=demo" -v /data/minio/data:/data -v /data/minio/config:/root/.minio minio/minio server  http://172.16.3.187/data http://172.16.3.188/data http://172.16.3.189/data http://172.16.3.215/data
minio
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
```
