### ISSUE TITLE
Ability for minio to create pid file

### ISSUE THREAD

**Issue by tsmgeek** [minio/minio#4605]
Would it be possable for minio to create a PID file for itself either a default one or path if supplied by user on startup.

**Comment by harshavardhana** [comment]
You can create it yourself inside a script why is this useful?

**Comment by tsmgeek** [comment]
true and its what I currently do in my OCF resource agent, just thought most services can do it natively and also tidy the pid on a tidy shutdown

**Comment by harshavardhana** [comment]
> true and its what I currently do in my OCF resource agent, just thought most services can do it natively and also tidy the pid on a tidy shutdown

Problem with daemon is that daemonizing is not standardized approach in Go and all other external libraries have some sort of implementation and portability problems. 

Including usage of daemon() from the stdlib.h involving cgo etc which causes more bloat.

**Comment by deekoder** [comment]
@tsmgeek  closing this issue as won't fix. Please don't hesitate to reopen it if you still want to discuss it further and think minio should address this.
