### ISSUE TITLE
Enhance the ACL authorization with Casbin

### ISSUE THREAD

**Issue by hsluoyz** [minio/minio#4614]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix ACL, RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can enhance the current ACL authorization by providing more features and flexibility. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by harshavardhana** [comment]
Thanks for opening the bug. @hsluoyz - we will get back to you on this.

**Comment by deekoder** [comment]
Marking blocked to discuss with @abperiasamy

**Comment by hsluoyz** [comment]
Hi, is there any progress on this issue?

**Comment by deekoder** [comment]
@hsluoyz  I will move this item to future. We have not had a chance to discuss this yet since we are busy in shipping the next version of minio right now. Will bring this back for discussion after we complete the next release in Jul.

**Comment by deekoder** [comment]
@hsluoyz  we discussed casbin support. Casbin is really cool.  In the case of Minio, we use policies rather than ACLs / RBAs to set policy on buckets. These policies are set programmatically via APIs and these APIs have to be S3 compatible for Minio.
