### ISSUE TITLE
Slack link on website is broken

### ISSUE THREAD

**Issue by SteveFaultless** [minio/minio#4615]
I'm sure this is the wrong place, but I don't use twitter.
The "join us on slack" button leads to a broken link, as do all of the other slack buttons scattered around.
I wanted to join you!  I still will if you can fix it :)

**Comment by deekoder** [comment]
@steveBetl  looking into this right away.

**Comment by harshavardhana** [comment]
Should be fixed.. now

**Comment by deekoder** [comment]
Closing. It's fixed.
