### ISSUE TITLE
giving 4 backing storage devices with differing free space results in wrong capacity

### ISSUE THREAD

**Issue by niv** [minio/minio#4617]
Provide 4 backing disk images/directories with differing sizes:
* 1GB
* 2GB
* +2GB (any)
* +2GB (any)

Example setup:
```
Initializing data volume for the first time.
[01/04] /Volumes/minio - 954 MiB online
[02/04] /Volumes/miniobig - 1.7 GiB online
[03/04] a - 465 GiB online
[04/04] b - 465 GiB online

Endpoint:  http://10.47.1.113:9000  http://10.2.1.107:9000  http://127.0.0.1:9000
AccessKey: access
SecretKey: secretsecret

Browser Access:
   http://10.47.1.113:9000  http://10.2.1.107:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.47.1.113:9000 access secretsecret

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 1.8 GiB Free, 1.9 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).
```

## Expected Behavior

* Capacity should say 1GB, as that is the smallest "disk" available to minio.
* Uploading a >1GB file should fail immediately.

## Current Behavior

* Capacity says 2GB.
* Uploading a file litters the file system with part.XX files. No UI feedback. File does not show up in the web interface. No error on stdout.

## Your Environment
  
* Version used (`minio version`): 
Version: 2017-06-13T19:01:01Z
Release-Tag: RELEASE.2017-06-13T19-01-01Z
Commit-ID: b9f622824ac17d3e0577d8a9b81a707666cc8cf1

Test setup on OSX Sierra, installed via homebrew.

**Comment by harshavardhana** [comment]
Erasure behaves in this manner N disks are divided into N/2 data and N/2 parity lets take an example homogeneous disk sizes, each disk is 1TB on a 4 disk setup would effectively result to 2TB.  So the algorithm of calculating the effective disk size is simply 

```
total-cluster-size = min-disk-size * (total-online-disks / 2)
```

Another limit to remember is also that each disk requires a limit of 1GB per disk free space. So your disk size say is 954MB then free space is lesser than this value. Then the i/o will fail as disk full which is what you experienced. 

So in your case 
```
[01/04] /Volumes/minio - 954 MiB online
[02/04] /Volumes/miniobig - 1.7 GiB online
[03/04] a - 465 GiB online
[04/04] b - 465 GiB online
```

The maximum disk size here is lesser than the allowed minimum.  But there are some apparent bugs in this area i am able to reproduce 

 - First bug is we shouldn't start the server if one of the disk doesn't meet the actual requirements of erasure or posix. 
- Second is that we are allowing the i/o to happen even if one of the disks failed and it proceeds to copy data to rest of the disks.  When an actual commit happens it fails with parts missing which is an odd error .  Total disk limit should be applied even for the disks which are bigger. 

> Uploading a file litters the file system with part.XX files. No UI feedback. File does not show up in the web interface. No error on stdout.

This is expected, this is part of the backend disk format for erasure coding. Unlike FS the files are split in chunks and stored. An object is always represented in its parts and `xl.json` describes each such part.
