### ISSUE TITLE
Get benchmark numbers for minio

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4619]
Perform benchmarks for FS and erasure backend for parallel PUT and GET with different file sizes.

**Comment by harshavardhana** [comment]
Erasure coded we already have .. why do we need it again ?

**Comment by krishnasrinivas** [comment]
@harshavardhana FS numbers weren't there. You are right that we already have it for erasure.

Closing this issue as we now have numbers for FS also.
