### ISSUE TITLE
JSON parsing for xl.json gjson lags behind jsoninter

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4620]
Comparing standard library v/s jsoniter 
```
$ benchcmp /tmp/std.txt /tmp/jsoniter.txt 
benchmark                          old ns/op     new ns/op     delta
BenchmarkParseUnmarshal10-4        74356         16404         -77.94%
BenchmarkParseUnmarshal100-4       572028        113695        -80.12%
BenchmarkParseUnmarshal500-4       2760211       500776        -81.86%
BenchmarkParseUnmarshal1000-4      5532915       985919        -82.18%
BenchmarkParseUnmarshal5000-4      27897519      7296728       -73.84%
BenchmarkParseUnmarshal10000-4     55900504      14337416      -74.35%
```

Comparing gjson v/s jsoniter 
```
benchcmp /tmp/gjson.txt /tmp/jsoniter.txt 
benchmark                          old ns/op     new ns/op     delta
BenchmarkParseUnmarshal10-4        57561         16404         -71.50%
BenchmarkParseUnmarshal100-4       458900        113695        -75.22%
BenchmarkParseUnmarshal500-4       2159754       500776        -76.81%
BenchmarkParseUnmarshal1000-4      4335041       985919        -77.26%
BenchmarkParseUnmarshal5000-4      21955116      7296728       -66.77%
BenchmarkParseUnmarshal10000-4     43759317      14337416      -67.24%
```

## Expected Behavior
Use a high performant json parser. This is needed because we are json heavy and we need to only use the best parser available to avoid any form of latencies that can incur due to json parsing. 

## Current Behavior
Current usage of gjson is performing lower in benchmarks compared to https://github.com/json-iterator/go which is 100% compatible with the go standard library. 

## Steps to Reproduce (for bugs)
Download https://gist.github.com/harshavardhana/51126d9df806c5fcf64c5cbd01e77129
```
PARSER=gjson go test -run=NONE -bench .
```

## Context
Performance improvements, look for better things on a timely basis. 

## Your Environment
Current master code.

**Comment by deekoder** [comment]
Won't fix for now. Will revisit later in a more comprehensive manner.
