### ISSUE TITLE
Migrate minio codebase to support go1.8.x releases

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4624]
## Expected Behavior
go1.8.x compilation, unit tests all should work fine.

## Current Behavior
Currently we only use go1.7.x and do not work properly on go1.8.x releases. 

## Context
Fully go1.8 migration is needed.  We need to remove some code here 

- posix-prepare-path.go is no longer needed, Go supports long UNC paths by default now. 
- we don't need to use `pkg/x/os/stat_windows.go` this is fixed upstream in go1.8.3
- test-utils_test.go needs to be fixed to compensate for http.Body interpretation changes and use http.NoBody when we are going to provide `nil` to the body.
- server-mux.go - majority of the code can be purged, and use only which is needed. 
- other tests changes.. 

This is needed to be done before the next release. 

## Your Environment
- go1.8
- minio master branch

**Comment by GarimaKapoor** [comment]
this is resolved, can we close?

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/pull/4759

**Comment by deekoder** [comment]
:+1:
