### ISSUE TITLE
Disable admin api in minio server.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4629]
Let's disable this in minio server till we have the fully comprehensive new admin api support rolls in the next release.

**Comment by krishnasrinivas** [comment]
@deekoder no response yet on https://github.com/minio/minio/issues/4626

My suggestion is, considering that `mc admin heal` has saved the day for a few of our users and also the fact that it has not been well tested, what we can do till the new API is ready is:
* disable admin handlers by default
* enable admin handlers if `_MINIO_ADMIN_HANDLERS` env var is set to "on"

This way, in the worst case scenario we will have some way out of it. Note that `_MINIO_ADMIN_HANDLERS` would be temporary solution till the new API is declared stable.

**Comment by harshavardhana** [comment]
@deekoder the relevant PR was closed since we decided to only change client side. This issue can be closed.
