### ISSUE TITLE
Chrome 59 on OSX does not autofill accessKey on login page

### ISSUE THREAD

**Issue by niv** [minio/minio#4630]
Chrome 59 on OSX does not autofill the username part of correctly saved credentials.

Related:  #4235 #4091 

## Expected Behavior
Both accessKey and secretKey are autofilled.

## Current Behavior
Only secretKey is autofilled, even after liberal clicking/explicit selecting. Logging in requires typing the accessKey manually.

Safari can be made to autofill both if selecting explicitly, but does not do so by default.

## Steps to Reproduce (for bugs)

1. Save creds in chrome by clicking Yes when asked to do so.  UI will show both username and password.
2. Logout.
3. Try to log in again and dispair as your accessKey taunts you from the dropdown, but does not fill in.

## Your Environment

* Version used: minio/minio:latest (96c93972853d) on docker

**Comment by ebozduman** [comment]
This looks like a Chrome bug. See [this](https://stackoverflow.com/questions/35049555/chrome-autofill-autocomplete-no-value-for-password)
The **workaround** is either to click on the Minio logo at the right bottom corner or to refresh the page. Then the `Secret Key` will be available.
By the way, this Chrome issue is not specific to OS X. I've also reproduced it on Windows, and Ubuntu OSs.
Here is the table that shows OSs and browsers with autofill password feature works/fails

|           | Chrome | Safari  | FireFox | IE  |
|:----------|:------:|:-------:|:-------:|:---:|
|**Windows**|Fails   |   N/A   | Works   |Works|
|**OS X**   |Fails   |   Works | Works   |N/A  |
|**Ubuntu** |Fails   |   N/A   | Works   |N/A  |

Chrome Canary also behaved the same way on OS X.
I suggest to close the issue.

**Comment by niv** [comment]
Thanks for looking into this.

However, this issue is not about the secret key, it's the associated username/access key that is not auto filled. I verified this in the builtin password manager (it's stored properly), and it happens both in Chrome and Safari.

Clicking the password entry pops up the selector and allows autofilling as expected; however, it only autofills secret, not access.

Reloading the page doesn't help in this case.

**Comment by ebozduman** [comment]
I see some difference in the behavior in my case. 
Could you give us some more information about your setup (although some may sound irrelevant):
1. How do you start your Minio server? Does it run on your localhost?
2. What is your OS X, and Safari version? 

I can reproduce the issue with Chrome on Ubuntu and localhost, but I don't see it with Safari. When the little key icon next to the Secret Key is clicked in Safari and the key is selected from the pull down menu, Access Key is auto filled right away.

**Comment by niv** [comment]
Hey,

* minio is hosted via docker (96c93972853d); reverse-proxied with https in place.
* Chrome: Version 59.0.3071.115 (Official Build) (64-bit)
* OSX: Sierra (10.12.5), Safari (10.1.1 (12603.2.4))

And you're right, Safari seems to be okay.  I must have mis-remembered/taken the automatically generated password as a partial autofill.  Chrome still doesn't work though.

**Comment by ebozduman** [comment]
Hi Niv,

When I start my local server like `http://localhost:9000/minio/login`, I see the  issue.
If I go to `https://play.minio.io:9000/minio/login` server publicly available, I don't see it and everything works as expected.

No matter what, it is the same code running in both cases, so we are  being the culprit like setting `autoComplete = "off"` is close to impossible (I also checked the code and did not see it). 
Password management and auto-fill are browser's responsibility anyways.

I spent quite some time to look into similar Chrome auto-fill related posts and responses on the internet, but could not find anything helpful or useful. 
I've posted my own question hoping to have someone to shed some light on it. I'll update it here if something helpful comes up.

**Comment by niv** [comment]
Thanks again for looking into this, @ebozduman!

I checked out the DOM and all the associated fields and from what I see, it *should* work. However, it does not.  I had to change the access key to something human-typable/rememberable just so I can log in.

If I find anything, I'll update here as well.

**Comment by ebozduman** [comment]
Sounds great!
Thanks.

**Comment by atomi** [comment]
Upgrading to Version 60 has fixed the issue for me on Ubuntu.

**Comment by ebozduman** [comment]
@niv,
Could you try with beta version 60?
With version 60, access key is auto filled when the secret key is selected. 

Although, the opposite and auto fill for both when login page is visited don't work, this is still quite a big progress.

**Comment by niv** [comment]
Yep, can confirm this is as described in Chrome 60. Not really fixed as one would expect it to behave, but at least usable.

**Comment by ebozduman** [comment]
@niv,
I agree. But, as you put it, at least it satisfies the bare min requirement.
As far as this issue goes, I suggest closing it.
Would you be ok to close it (with reservations)?

**Comment by niv** [comment]
Sure. :)
