### ISSUE TITLE
mc: share download endpoint/bucket/ w/o -r does not produce share links

### ISSUE THREAD

**Issue by niv** [minio/minio#4631]
Trying to share `bucket/path` without `--recursive` does not produce presigned URL(s).

The documentation promises:
```
   3. Share all objects under this folder with 5 days expiry.
      $ mc share download --expire=120h s3/backup/
```

## Expected Behavior

Have bucket/test/data.txt existing.

    $ mc share download minio/bucket/test/

Should produce a shareable link to test/data.txt

## Current Behavior

Above command does nothing.

## Your Environment
mc:  2017-06-15T03:38:43Z
minio: minio/minio:latest (96c93972853d)

**Comment by harshavardhana** [comment]
You should use mc share download --recursive

**Comment by niv** [comment]
--recursive will generate one URL for each object in the "directory" and all subdirs. Is exposing a whole prefix this way not supported?  If so, the documentation should be updated. :)

**Comment by harshavardhana** [comment]
Can you point me to the doc where we say that its supported by `mc share` command? Presigned URLs with expiry generated here as per S3 spec is generated for only objects.

If you wish to expose the prefix you have to use `mc policy download myminio/mybucket/test/` this would allow anonymous access to all objects inside `test/` prefix.

Then to list all the resultant URLs just do `mc policy links myminio/mybucket/test/`

**Comment by niv** [comment]
````
~ → mc share download
NAME:
   mc share download - Generate URLs for download access.

USAGE:
   mc share download [FLAGS] TARGET [TARGET...]

OPTIONS:
  --recursive, -r                  Share all objects recursively.
  --expire value, -E value         Set expiry in NN[h|m|s]. (default: "168h")
  --config-folder value, -C value  Path to configuration folder. (default: "/Users/niv/.mc")
  --quiet, -q                      Suppress chatty console output.
  --no-color                       Disable color theme.
  --json                           Enable JSON formatted output.
  --debug                          Enable debug output.
  --insecure                       Disable SSL certificate verification.
  --help, -h                       Show help.

EXAMPLES:
   1. Share this object with 7 days default expiry.
      $ mc share download s3/backup/2006-Mar-1/backup.tar.gz

   2. Share this object with 10 minutes expiry.
      $ mc share download --expire=10m s3/backup/2006-Mar-1/backup.tar.gz

   3. Share all objects under this folder with 5 days expiry.
      $ mc share download --expire=120h s3/backup/

   4. Share all objects under this folder and all its sub-folders with 5 days expiry.
      $ mc share download --recursive --expire=120h s3/backup/

[1]    31812 exit 1     mc share download
````

See point 3.

Edit: Thank you, policy & links does what I need. I can then also browse them on the web interface anonymously.

**Comment by harshavardhana** [comment]
> 3. Share all objects under this folder with 5 days expiry.
>       $ mc share download --expire=120h s3/backup/

This means all objects under backup/ at the top-level , if none found it doesn't do anything. 

> 4. Share all objects under this folder and all its sub-folders with 5 days expiry.
>       $ mc share download --recursive --expire=120h s3/backup/

This means all objects inside backup and all subsequent objects recursively. 

Feel free to close this issue @niv if there is nothing else that needs to be done.

**Comment by niv** [comment]
Right! Thanks for responding so quickly and diligently.

However, according to the docs (and your explanation), this still is broken for me:

````
~ → mc ls ic/code/
[2017-07-05 22:16:05 CEST]   365B timestamp.nim
[2017-07-05 23:09:13 CEST]     0B nimcache/

~ → mc share download ic/code/

~ →
````

Shouldn't this spit out a single link in my case (for timestamp.nim)?

**Comment by harshavardhana** [comment]
> Right! Thanks for responding so quickly and diligently.
> 
> However, according to the docs (and your explanation), this still is broken for me:
> 
> ~ → mc ls ic/code/
> [2017-07-05 22:16:05 CEST]   365B timestamp.nim
> [2017-07-05 23:09:13 CEST]     0B nimcache/
> 
> ~ → mc share download ic/code/
> 
> ~ →
> Shouldn't this spit out a single link in my case (for timestamp.nim)?

Yes it should - its a bug.. @niv

**Comment by niv** [comment]
Updated the top comment! Thanks for following this up. I'll leave the ticket open so it can be tracked.

**Comment by harshavardhana** [comment]
> Updated the top comment! Thanks for following this up. I'll leave the ticket open so it can be tracked.

It would be better to close this one out and open here https://github.com/minio/mc/issues a more relevant place for this bug to be.

**Comment by niv** [comment]
Moved - https://github.com/minio/mc/issues/2204.

**Comment by harshavardhana** [comment]
> Moved - minio/mc#2204.

Thank you @niv
