### ISSUE TITLE
How can I get URL to latest release binary with fixed version?

### ISSUE THREAD

**Issue by Yurmusp** [minio/minio#4632]
The way you guys publish your releases, I do not see how I can get fixed version URL to latest release binary, that will not change in the future.

Is there way to get it (if I missed it)?
Can you change how you publish releases, so that fixed version URLs would not change with next release?

I talk about  linux-amd64 release.

**Comment by harshavardhana** [comment]
You can just use https://dl.minio.io/server/minio/release/linux-amd64/minio.RELEASE.2017-06-13T19-01-01Z

**Comment by harshavardhana** [comment]
eventually it will become part of archive as https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2017-06-13T19-01-01Z

**Comment by Yurmusp** [comment]
That's the problem, it will change and download will fail at some point.

**Comment by harshavardhana** [comment]
Why not try both @Yurmusp what is the problem?

**Comment by Yurmusp** [comment]
I think it shall go to archive right away, where I would do every delivery as a folder and
your release folder to be symlink to most recent versioned folder.
This way fixed version URLs will always be correct.
Production environments need fixed version URLs that will not expire for a long time. 
If you guys do not do it this way, it discourages your component use, 
as typically intention to use versioned URLs is to never change it.
Because if you change it, then build of my component will fail without any change  
on my side, which shall not be the case.
If I have to change URL to fix the build, then your versioned URLs do not serve the purpose.
I think I'm not the only one who going to have this issue.
I think best option would be if you change how you publish releases in a way that
versioned URLs never change.

**Comment by Yurmusp** [comment]
I can try both, but that's workaround. Issue on your side remains and I think best is to fix it.

**Comment by harshavardhana** [comment]
> I think it shall go to archive right away, where I would do every delivery as a folder and
> your release folder to be symlink to most recent versioned folder.
> This way fixed version URLs will always be correct.
> Production environments need fixed version URLs that will not expire for a long time.
> If you guys do not do it this way, it discourages your component use,
> as typically intention to use versioned URLs is to never change it.
> Because if you change it, then build of my component will fail without any change
> on my side, which shall not be the case.
> If I have to change URL to fix the build, then your versioned URLs do not serve the purpose.
> I think I'm not the only one who going to have this issue.
> I think best option would be if you change how you publish releases in a way that
> versioned URLs never change.

Its as simple as doing 5 lines in a bash script, i don't know what could be a complex situation in this. There are only two places to check. 

```
release_tag=$(curl -s https://api.github.com/repos/minio/minio/releases/latest | jq -r .tag_name)

dl_minio="https://dl.minio.io/server/minio/release/linux-amd64/minio"
dl_archive_minio="https://dl.minio.io/server/minio/release/linux-amd64/archive/minio"

curl --head "${dl_minio}.${release_tag}"
curl --head "${dl_archive_minio}.${release_tag}"
```

> Production environments need fixed version URLs that will not expire for a long time.

Current design to for continuous delivery minio in practice has no real versions only commit ids and build dates are used to know what release build a user is running, each new version is designed to be compatible with previous version. 

To make it even easier we can pro-actively copy  new release to archive folder just so that you only have to look at one place.

**Comment by harshavardhana** [comment]
> To make it even easier we can pro-actively copy new release to archive folder just so that you only have to look at one place.

Would this be acceptable if done as practice and as part of release process? @Yurmusp

**Comment by Yurmusp** [comment]
I think yes.

**Comment by Yurmusp** [comment]
That's probably much simpler for you guys and will do the job.

**Comment by harshavardhana** [comment]
> That's probably much simpler for you guys and will do the job.

We will stick to that as part of release process.. so that you have a consistent URL to reference.

**Comment by Yurmusp** [comment]
Please, let me know when you will have persistent URL for the most recent
version.
Thank you.

**Comment by harshavardhana** [comment]
> Please, let me know when you will have persistent URL for the most recent
> version.
> Thank you.

@Yurmusp it should be already done..

**Comment by Yurmusp** [comment]
I need same thing with client mc.

**Comment by harshavardhana** [comment]
> I need same thing with client mc.

Please open a bug on mc. Feel free to close this.
