### ISSUE TITLE
Performances downloading as zip with big sized files

### ISSUE THREAD

**Issue by b4nst** [minio/minio#4638]
## Environment

* Version used (`minio version`): 2017-06-13T19:01:01Z
* Environment name and version (e.g. nginx 1.9.1): docker single node

The feature **download all as zip** is very long when the file(s) selected are large (>=~500Mo). Would it be possible to set no compression on zip algorithm to speed it up, and maybe even stream it (by chunk) to be able to start the download before the zip process ends ? At least a display should inform the user that the task is running and the download will be available soon (maybe a progress bar ?) Currently it's pretty confusing to understand that you have to wait for the zip process to finish.

Btw, where are the zip files stored (.minio.sys/tmp ?) and what is the remove policy ?

**Comment by krishnasrinivas** [comment]
@BastienAr the zip file is not stored on the disk, it is created as a stream and that stream is downloaded by the client. We will check what can be done to give a better UX.

**Comment by k0nsl** [comment]
I must be practically blind as I cannot even locate **_“Download as ZIP”_** anywhere in the Minio Browser (ver. `2017-06-13T19:01:01Z`) 😔

**Comment by krishnasrinivas** [comment]
@k0nsl once you select a file it will show up at the top :smile:

**Comment by b4nst** [comment]
@krishnasrinivas Oh ok I thought it was not because the download take a while to start, is the stream flushed while processed ?

**Comment by deekoder** [comment]
@BastienAr is this resolved in your opinion. Hope you were able to locate the download widget and get the zip files.

**Comment by b4nst** [comment]
@deekoder I was already able to get the zip files, the problem is that when large files are selected the download process take a while to start, as it wait zip completion before starting.

**Comment by deekoder** [comment]
ok great. Closing this as working as intended. If the download process is unacceptable amount of waiting time, please let us know.

**Comment by beniwtv** [comment]
I have the exact same issue: I uploaded a 14 GB video file to minio (3 node cluster), and set the policy to 'download'. When I now request the file, it will take ages to even start downloading.

(wget just reports "HTTP request sent, waiting for response..."). 

I guess minio processes the entire file before starting to send the response? Any solution to this?

**Comment by harshavardhana** [comment]
We will take a look @beniwtv . Thanks for reporting.

**Comment by nitisht** [comment]
closing this for now as we have not been able to work on it. we can revisit later once we have development cycles to fix this.

**Comment by kaankabalak** [comment]
This was also reported recently on the community Slack channel. We might want to investigate if there is an alternative way to fix this issue.
