### ISSUE TITLE
[GCS] part names of upload id need to be manual data recovery friendly

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4639]
Current part names are just ETags like `.../UPLOADID/PARTETAG`. In case of manual data recovery, its not possible to know part numbers.  Its required change part names recovery friendly.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
Will review backend as part of #4637  and also take care of the usability of the part id for manual operations.
