### ISSUE TITLE
Eval whether there are any better http muxer (better than gorilla) available

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4643]
Evaluate from the following list. 

https://github.com/avelino/awesome-go#routers

**Comment by ebozduman** [comment]
Deepa,
This task is done and the gist doc is at:
https://gist.github.com/ebozduman/98e258acea7a9e255010e0b9d45a6fb7

ab and I discussed it and went over the doc and information and decided `bone` to be the mux we will be replacing `gorilla` mux with.
