### ISSUE TITLE
Investigate plug-in mechanism for gateway mode

### ISSUE THREAD

**Issue by fwessels** [minio/minio#4644]
Investigate how to be able to load external plug-ins into minio to be more flexible to load (for gateway) connectors to other back-ends without bloating minio itself too much.

A multi-language approach would be best although to start with a Go-only solution would be fine.

Multi-OS support would also be nice but not a necessity.

**Comment by harshavardhana** [comment]
This would require a migration to go1.8 first i believe @fwessels ?

**Comment by fwessels** [comment]
Yes, correct.

**Comment by harshavardhana** [comment]
We are not doing the plugin style due to cross platform limitations, the scope and requirement has moved https://github.com/minio/minio/projects/13 and there is a pending PR under review. 

Closing this.
