### ISSUE TITLE
Implement server-side-encryption for all backend formats (FS, XL, ...)

### ISSUE THREAD

**Issue by aead** [minio/minio#4650]
Server-side-encryption can be implemented in the Object-Layer. This will lead to some overhead for XLs bitrot protection but simplifies encryption support for FS and other backends.

See aslo #4416 ,  #4020 , #4616 ,  #4649 

### Possible Solution
Server-side-encryption can be "easily" implemented in the Object-Layer. It only requires small changes to the backend formats and is transparent for erasure-coding / bitrot protection.P
Proposal:
 - use ChaCha20Poly1305 and/or AES-GCM as cipher.
 - store encrypted objects in slices/parts which are smaller than `N` and use an unique/random nonce per slice/nonce

@harshavardhana, @abperiasamy
We must think about the Impacts on other backends (RPC, GCS, Azure)...

**Comment by harshavardhana** [comment]
GCS, Azure and AWS S3 backends can be a pass through utilizing the relevant server side encryption APIs from all these relevant providers.

**Comment by aead** [comment]
Current progress:
#4894 Add basic support for:
  - GET (without ranges)
  - PUT
  - HEAD

The following operations are still missing:
 - GET with ranges - requires: part size and number of parts for multipart objects
 - InitMultipart
 - PUT Multipart - requires: XL / FS must save part size and number of parts in meta data
 - EndMultipart - requires: check that all uploaded parts have the same size - fail otherwise
 - Copy - Explore exact AWS behavior

**Comment by aead** [comment]
basic work is done - I will open a separate issue for each feature
