### ISSUE TITLE
Configurable erasure coding

### ISSUE THREAD

**Issue by bobobo1618** [minio/minio#4654]
Per the docs:

> Minio uses Reed-Solomon code to shard objects into N/2 data and N/2 parity blocks. 

I have 8 drives with above average MTBF and I'd much rather have a say 3/1 data/parity allocation than 4/4, as this would give me failure tolerance (albeit a single disk), reduce my overhead (75% efficient vs. 50%) and increase IOPS (0.25x vs. 0.125x).

I had a look around for a similar issue but couldn't find one.

**Comment by fwessels** [comment]
> albeit a single disk

With just a single disk of parity, losing another disk means that users will lose data.

Thanks for the suggestion, and you are correct that you couldn’t find an issue as we made a conscious decision to not make it configurable. The reason for this is that we believe that for the vast majority of users it is better to put priority on prevention of data loss over maximizing effective storage capacity. 

It also stems from operational experience where, generally speaking, you see that it is cheaper to spend a bit more on hardware/hard disks as compared to spending more on manpower to fix/replace harddisks. In fact we advocate, especially on larger configurations with eg. 8 or more disks, a “deploy and forget” philosophy whereby faulty disks don’t even need to be replaced. But rather, once the economical life of a server is over, to migrate and decommission a server in whole. 

(Having said that, with minio being open source, you are of course free to change it yourself and the underlying erasure coding technique will work just fine.)

**Comment by bobobo1618** [comment]
> The reason for this is that we believe that for the vast majority of users it is better to put priority on prevention of data loss over maximizing effective storage capacity.

> (Having said that, with minio being open source, you are of course free to change it yourself and the underlying erasure coding technique will work just fine.)

So would a PR to implement this be unwelcome?

I agree that minimizing data loss is a good thing but I think you've taken it too far to one extreme for it to be the only option. For my disks, the current configuration would allow me to lose 4 disks before any data loss occurred but it would _also_ require that I sacrifice a full 88% of available IOPS and 50% of storage to get it.

I just can't really imagine a situation where I'd want this configuration. How often am I going to lose 4 entire disks before I can replace one (unless I go for your "deploy and forget" idea, which is out for me)? I can't imagine that will justify the other costs (like IOPS).

**Comment by fwessels** [comment]
We normally always love PRs but in this special case it is unlikely to get accepted.

We have gone to considerable length to keep the deployment and installation of minio as simple as possible (single binary for FS / XL / Distributed mode), purely deciding mode of operation based on arguments passed in (and you may have noticed there is not even a user config file).

It is not so much the technical difficulty of adding it, but rather forcing everyone to think about it and perhaps some people (not fully comprehending all the details) making the wrong tradeoff and suffering data loss as a consequence down the line.

With respect to performance, we normally find that we first saturate the networking bandwidth, so although N/2 data and N/2 parity is more expensive in terms of IOPS it is not the limiting factor in practice.

It sounds like you are understanding the tradeoffs and know what you are doing, so again, you are free to tweak/optimize minio for your particular situation.
