### ISSUE TITLE
Problems uploading files to minio "The system cannot move the file to a different disk drive"

### ISSUE THREAD

**Issue by robertodocampo** [minio/minio#4655]
## Expected Behavior

I have minio on Windows sociated to folder "d:\minio". On this folder i've a link to fileserver 

d:\minio\
          -- test (maped to \\myfileserver\\test) 

I expected than minio uploads the file to te folder on the fileserver

## Current Behavior

'''
{"cause":"rename \\\\?\\D:\\minio\\.minio.sys\\tmp\\2aff9963-d062-49a1-b175-975224ce18d6\\39f89004-c63c-435f-be1d-f1e73aad9acc \\\\?\\D:\\minio\\test\\Microservices.pdf: The system cannot move the file to a different disk drive.","level":"error","msg":"Unexpected error, please report this issue at https://github.com/minio/minio/issues","source":"[web-handlers.go:1055:toWebAPIError()]","time":"2017-07-10T08:59:29+02:00"

'''
## Possible Solution

It Seems to be related to "https://github.com/golang/go/issues/13766"

## Environment
Windows 2012 SR2
Minio Version 2017-06-13T19:01:01Z

Best Regards

**Comment by krishnasrinivas** [comment]
@robertodocampo when you upload file to minio, it first stages it to a temp directory before renaming. Minio requires that the export directory and all the sub-directories belong to the same FS. Rename will not work across different FSes.

**Comment by robertodocampo** [comment]
I suggest change it to move and rename. It make it compatible to a minio with backend on fileserver cluster

**Comment by harshavardhana** [comment]
That is an unexpected reasoning. It puts an unexpected onus on the backend and can lead to bugs. We use rename for it's atomic nature. It is unlikely that we will support this scenario.

**Comment by krishnasrinivas** [comment]
@robertodocampo minio is designed with the assumption that the backend FS supports rename syscall. Minio works on top of NFS and cluster FSes like GlusterFS which support rename syscall.

Hence the export directory should be one FS (it can be clusterFS like glusterFS or disk FS like XFS)

@deekoder can this be closed?
