### ISSUE TITLE
Explore the possibility of using golang.org/x/sync/errgroup

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4667]
https://godoc.org/golang.org/x/sync/errgroup

```
Package errgroup provides synchronization, error propagation, and 
Context cancellation for groups of goroutines working on subtasks 
of a common task.
```

There many naked go-routines where we use a combination of things like 

```
var wg sync.WaitGroup

wg.Add(1)
go func()  { defer wg.Done()  ..... }
wg.Wait()
``` 

Using this package has advantages in terms of task management, error handling and active cancellation/timeouts.

**Comment by deekoder** [comment]
This is an exploration we have to do in future. Moving it there.

**Comment by kannappanr** [comment]
Will not be implementing this.
