### ISSUE TITLE
Allow inter-server HTTP resources only to minio servers.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4676]
## Expected Behavior
We shouldn't allow this to happen and return appropriate error.

## Current Behavior
Currently inter-server resources like `Admin`, `BrowserPeer` etc are accessible any clients.  This could be fixed by allowing only peer minio nodes to access such resources and return HTTP response code `405` at gorilla muxer level.

## Possible Solution
Use grpc, or use a gorilla muxer style restriction. 

## Context
Security

## Your Environment
master branch

**Comment by krishnasrinivas** [comment]
Admin will need to be accessed by mc. But yes internode-only services can be restricted to the specified IPs of peers.

**Comment by deekoder** [comment]
Part of cleanup. We will do this. @balamurugana  can you take this on as part of your cleanup task.

**Comment by balamurugana** [comment]
@deekoder it is not a cleanup, it is a bug fix.

**Comment by deekoder** [comment]
@balamurugana can we close this as fixed?

**Comment by harshavardhana** [comment]
This can be perhaps fixed after the new HTTP RPC refactor.

**Comment by balamurugana** [comment]
This issue is not related to HTTP RPC and is not addressed in HTTP RPC PR

**Comment by nitisht** [comment]
@harshavardhana @krishnasrinivas is this fixed as a part of HTTP REST approach?

**Comment by harshavardhana** [comment]
In a way yes.. but it is perhaps not there yet. We basically have to disallow requests from IPs trying to connect to Minio.

**Comment by harshavardhana** [comment]
This is already fixed as part of instance id support and also disks with inode differences are rejected as well. Closing as fixed.

**Comment by krishnasrinivas** [comment]
@harshavardhana note that the issue is not fixed by instance-id or inode support, it can be fixed by your earlier comment `We basically have to disallow requests from IPs trying to connect to Minio.` the only problem is if the network is NATed peers connection's source IP might be different than what is specified at the command line

**Comment by harshavardhana** [comment]
instance-id and inode sufficiently fix it already so we don't have to do a anything else anymore.
