### ISSUE TITLE
SignatureDoesNotMatch error when putting object via aws-java-sdk-s3

### ISSUE THREAD

**Issue by longtimeago** [minio/minio#4687]
Unable to put an object via `aws-java-sdk-s3`

`com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3L137)`

Retrieving objects is OK, the problem is only with put
Tried to put the same object to a real AWS bucket - works without issues

SDK client logs:
```java
16:55:48.930 [http-nio-8080-exec-4] [username=AnyKey] DEBUG com.amazonaws.request - Sending Request: PUT http://172.19.0.10:9000 /b1/theme Headers: (User-Agent: aws-sdk-java/1.11.163 Linux/4.4.0-83-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121, amz-sdk-invocation-id: 62795af7-8caa-f391-8b48-c75a05959035, Content-Length: 2, Content-Type: text/plain, ) 
16:55:48.930 [http-nio-8080-exec-4] [username=AnyKey] DEBUG com.amazonaws.auth.AWS4Signer - AWS4 Canonical Request: '"PUT
/b1/theme

amz-sdk-invocation-id:62795af7-8caa-f391-8b48-c75a05959035
amz-sdk-retry:0/0/470
content-length:174
content-type:text/plain
host:172.19.0.10:9000
user-agent:aws-sdk-java/1.11.163 Linux/4.4.0-83-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121
x-amz-content-sha256:STREAMING-AWS4-HMAC-SHA256-PAYLOAD
x-amz-date:20170718T165548Z
x-amz-decoded-content-length:2

amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length
STREAMING-AWS4-HMAC-SHA256-PAYLOAD"
16:55:48.930 [http-nio-8080-exec-4] [username=AnyKey] DEBUG com.amazonaws.auth.AWS4Signer - AWS4 String to Sign: '"AWS4-HMAC-SHA256
20170718T165548Z
20170718/us-east-1/s3/aws4_request
dc968f0b7f6234b84ad3b9c2184de71339a5cd98bec612ddd47a959ecaf1a5c8"
16:55:51.936 [http-nio-8080-exec-4] [username=AnyKey] DEBUG com.amazonaws.request - Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3L137), S3 Extended Request ID: 3L137
16:55:51.936 [http-nio-8080-exec-4] [username=AnyKey] DEBUG com.amazonaws.request - Retrying Request: PUT http://172.19.0.10:9000 /b1/theme Headers: (User-Agent: aws-sdk-java/1.11.163 Linux/4.4.0-83-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121, amz-sdk-invocation-id: 62795af7-8caa-f391-8b48-c75a05959035, Content-Length: 2, Content-Type: text/plain, ) 
```

Minio log:
`
time="2017-07-18T16:55:48Z" level=error msg="{\"method\":\"PUT\",\"reqURI\":\"/b1/theme\",\"header\":{\"Amz-Sdk-Invocation-Id\":[\"62795af7-8caa-f391-8b48-c75a05959035\"],\"Amz-Sdk-Retry\":[\"0/0/470\"],\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=minio/20170718/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=3030a3bde0c515c0d0ce624cdf52f9b0064110e3a7d03f1e017654eef3051341\"],\"Connection\":[\"Keep-Alive\"],\"Content-Length\":[\"174\"],\"Content-Type\":[\"text/plain\"],\"Expect\":[\"100-continue\"],\"Host\":[\"172.19.0.10:9000\"],\"User-Agent\":[\"aws-sdk-java/1.11.163 Linux/4.4.0-83-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.121-b13/1.8.0_121\"],\"X-Amz-Content-Sha256\":[\"STREAMING-AWS4-HMAC-SHA256-PAYLOAD\"],\"X-Amz-Date\":[\"20170718T165548Z\"],\"X-Amz-Decoded-Content-Length\":[\"2\"]}}" cause="Signature does not match" source="[object-handlers.go:510:objectAPIHandlers.PutObjectHandler()]" 
`

Aws client is obtained like this
```java
AmazonS3ClientBuilder.standard()
            .withPathStyleAccessEnabled(true)
            .withEndpointConfiguration(
                new AwsClientBuilder.EndpointConfiguration(this.url, null)
            ).withCredentials(
                new AWSStaticCredentialsProvider(
                    new BasicAWSCredentials(this.accesskey, this.secretkey)
                )
            ).build()
```

Environment:
- minio/minio:RELEASE.2017-06-13T19-01-01Z
- aws-java-sdk-s3:1.11.163

I would really appreciate any hint :)

**Comment by krishnasrinivas** [comment]
@longtimeago can you check it this way if it works? https://gist.github.com/krishnasrinivas/edc62873bcef5396493f31f8d582fc2c

In the meanwhile we will investigate why your program is not working

**Comment by vadmeste** [comment]
@longtimeago @krishnasrinivas, AWS Java SDK uses streaming signature v4 by default. This issue is known and fixed in master but not released yet. Using Minio master will fix the problem but if you don't want to use it, you can explicitly set a region (like "us-east-1") in ~/.minio/config.json and the issue will disappear.

**Comment by longtimeago** [comment]
Thanks for the fast response!
@vadmeste We use minio inside a docker container, so the solution with `~/.minio/config.json` is not very suitable ... of course, we could build our own image based on minio/minio as a temporaty solution :)
@krishnasrinivas Nice! The example works like a charm :) Gonna try to rewrite it with new sdk `builder` style ...
Thanks ones again!
Probably, we don't need this issue, closing

**Comment by longtimeago** [comment]
@krishnasrinivas by the way, in your example critical thing is `disableChunkedEncoding()`
On the other hand, it works without `clientConfiguration.setSignerOverride("AWSS3V4SignerType")`

**Comment by harshavardhana** [comment]
You could also override the region by using MINIO_REGION env for docker instances. Also you don't need to disable chunkedEncoding with Minio. We support streaming signature mechanism which is the default ehavior of aws-sdk-java

**Comment by Chandra4Aws** [comment]
My observations on this issue.
Environment: Api gateway -> Lambda function (Java) -> S3.
There are 2 observations
1. When there is a space in the Custom metadata key, it doesn't create it.
     Eg: "Account Number" -> Not creating
           "Account-Number" -> It creates

2. When there is a : (Colon) in the key, it throws "There were headers present in the request which were not signed (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID:XXXXX".

First issue doesn't happen in console, but second issue consistent. S3 can throw a better exception rather not signed.

Thanks

**Comment by krishnasrinivas** [comment]
> 1. When there is a space in the Custom metadata key, it doesn't create it.
>    Eg: "Account Number" -> Not creating
>    "Account-Number" -> It creates

Are you saying AWS-S3 allows space in key? Cursory look at their documentation does not provide that info, if you can provide a test program showing that they allow we can check if we can allow as well.

> 2\. When there is a : (Colon) in the key, it throws "There were headers present in the request which were not signed (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID:XXXXX".

Are you using minio-java or aws-java-sdk?
