### ISSUE TITLE
Official Signed Windows Binary?

### ISSUE THREAD

**Issue by tyler-johnson** [minio/minio#4688]
I have an enterprise customer wanting to install Minio on-premise as a replacement for S3. They are running Windows Server 2012 and due to their security policies, they cannot download or run unsigned exe files.

Is there any plan for Minio to distribute a signed Windows binary?

**Comment by krishnasrinivas** [comment]
@tyler-johnson the signature is provided along with the binaries which you can verify:
https://dl.minio.io/server/minio/release/windows-amd64/

```
krishna@escape:/tmp$ wget https://dl.minio.io/server/minio/release/windows-amd64/minio.exe
--2017-07-18 15:51:27--  https://dl.minio.io/server/minio/release/windows-amd64/minio.exe
Resolving dl.minio.io (dl.minio.io)... 162.243.132.171
Connecting to dl.minio.io (dl.minio.io)|162.243.132.171|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18001920 (17M) [application/x-msdos-program]
Saving to: ‘minio.exe’

minio.exe                                   100%[=============================================================================================>]  17.17M  16.8MB/s   in 1.0s   

2017-07-18 15:51:29 (16.8 MB/s) - ‘minio.exe’ saved [18001920/18001920]

krishna@escape:/tmp$ wget https://dl.minio.io/server/minio/release/windows-amd64/minio.exe.asc
--2017-07-18 15:51:33--  https://dl.minio.io/server/minio/release/windows-amd64/minio.exe.asc
Resolving dl.minio.io (dl.minio.io)... 162.243.132.171
Connecting to dl.minio.io (dl.minio.io)|162.243.132.171|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 819 [text/plain]
Saving to: ‘minio.exe.asc’

minio.exe.asc                               100%[=============================================================================================>]     819  --.-KB/s   in 0s     

2017-07-18 15:51:34 (93.0 MB/s) - ‘minio.exe.asc’ saved [819/819]

krishna@escape:/tmp$ gpg --verify minio.exe.asc minio.exe
gpg: Signature made Wednesday 14 June 2017 11:57:38 AM PDT using RSA key ID F9AAC728
gpg: Good signature from "Minio Trusted <trusted@minio.io>"
gpg: Note: This key has expired!
Primary key fingerprint: 4405 F3F0 DDBA 1B9E 68A3  1D25 12C7 4390 F9AA C728
krishna@escape:/tmp$ 
```

**Comment by tyler-johnson** [comment]
Thanks for the quick response! 

When I run the gpg command this is what I see. Am I missing something?

```
gpg: Signature made Wed Jun 14 12:57:38 2017 MDT
gpg:                using RSA key 12C74390F9AAC728
gpg: Can't check signature: No public key
```

Also I don't know much about Windows Server and how it determines which .exe files are allowed to be downloaded/run. Should Internet Explorer automatically detect the .asc file? Or does the system admin need to do something to tell Windows that this executable can be trusted?

To be clear, I am looking for the Windows Server equivalent of UAC:

![](http://www.windowscentral.com/sites/wpcentral.com/files/styles/larger/public/field/image/2016/05/windows-10-uac-dialog.jpg?itok=herxc9ZJ)

**Comment by aead** [comment]
@tyler-johnson 
You have to import the public key from the keyserver: `gpg --keyserver pgp.mit.edu --recv F9AAC728`

But I think you are looking for a way to run minio as a verified binary on windows servers. You want to run minio and windows will pop up UAC and say: "Do you want to allow this app to make changes to your PC" and "Verified publisher": Miniio Inc. right?!

To do this, we have to get a certificate from a trusted entity which is trusted by windows - like Comodo, VeriSign etc. Then we can sign minio with the public key of this certificate and then it will be a "trusted app". (See Verified publisher)

**Comment by aead** [comment]
@tyler-johnson 
We have applied for a code signing certificate to create signed windows binaries. As soon we receive the certificate we will build a signed windows release. Then windows UAC should show minio server as verified application. Will keep you updated.

**Comment by aead** [comment]
@tyler-johnson 
We have build a signed windows release. You can find it [here](https://data.minio.io:10000/windows/minioSignedRelease.exe?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=miniocorp%2F20170719%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170719T183106Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8c7a390c319c8ca7e3e6d52cec0106e44326a9a9e6a8062e8063ff20c87825ff).
You can download and test whether it works on your environment. Once you did that, please let us know - then we will exchange our official windows release. Thank you.

**Comment by tyler-johnson** [comment]
Wow you guys rock! I will try it out on this Windows Server and see how it goes. Thank you for doing this.

**Comment by deekoder** [comment]
@tyler-johnson did it work out well without any issues for you? We plan to make a new release and if everything looks good we plan to sign all windows build in future.

**Comment by tyler-johnson** [comment]
Yes, I can confirm that my client is able to download and run Minio on their Windows Servers now. It worked beautifully. Thank you so much!

**Comment by aead** [comment]
Okay, glad to hear - thank you very much @tyler-johnson
