### ISSUE TITLE
Investigate reconstruct on the fly for Distributed mode

### ISSUE THREAD

**Issue by fwessels** [minio/minio#4696]
Once the ReconstructData is accepted in klauspost/reedsolomon, we should investigate, for distributed mode, whether it is worthwhile to always load the local block (irrespective of whether it is a data or parity block) and reconstruct on the fly. (And thus load one less block over the network).

The reason for this is that, given the reconstruction speed that we are now seeing, we are easily getting reconstruction speeds in excess of 10 GB/sec (or 80Gbit/sec):

```
benchmark                            all MB/s     data MB/s    speedup
BenchmarkReconstruct10x2x10000-8     2011.67      10530.10     5.23x
BenchmarkReconstruct50x5x50000-8     4585.41      14301.60     3.12x
BenchmarkReconstruct10x2x1M-8        8081.15      28216.41     3.49x
BenchmarkReconstruct5x2x1M-8         5780.07      28015.37     4.85x
BenchmarkReconstruct10x4x1M-8        4352.56      14367.61     3.30x
BenchmarkReconstruct50x20x1M-8       1364.35      4189.79      3.07x
BenchmarkReconstruct10x4x16M-8       1484.35      5779.53      3.89x
```

**Comment by harshavardhana** [comment]
This is a neat thing to do.
