### ISSUE TITLE
Question: Maximum installation (size) + HA setup

### ISSUE THREAD

**Issue by malejpavouk** [minio/minio#4698]
Hi,

I hope this is a correct channel to ask questions, if not, please direct me to the correct one.

I have two questions:

1. 16 disks seems to me a bit limiting on the first sight. Do I understand it correctly, that If I have 16 disks with 8TB each, I have 128TB capacity, but with 50% used on parity. Hence practically I can use at max 64TB. As I do not want to have the disks completely full, the upper limit of Minio as a system is lets say 50TB of data? Or is there any other way (except of sharding)?
2. We also consider to use many servers. The Java Minio client does not seem to support passing multiple IPs. So what is the recommended approach? Use HA Proxy and do Round Robin balancing? Or some client side balancing with multiple clients (should I prefer one node, or round robin)? 

Thanks in advance!

**Comment by krishnasrinivas** [comment]
> 16 disks seems to me a bit limiting on the first sight. Do I understand it correctly, that If I have 16 disks with 8TB each, I have 128TB capacity, but with 50% used on parity. Hence practically I can use at max 64TB. As I do not want to have the disks completely full, the upper limit of Minio as a system is lets say 50TB of data? Or is there any other way (except of sharding)?

That is correct since half the drives is for parity, 64 TB will be usable. Minio took this approach to build for very large scale. design philosophy is to build many small manageable units rather than one giant monolithic distributed unit. This way, you may even run many minio instances of different versions cohosted on the same hardware infrastructure. Failure is self contained within each unit. take a look at this use case: https://blog.minio.io/scalable-genomics-data-processing-pipeline-with-alluxio-mesos-and-minio-a8360e54b11a 

However we are planning to relax the 16 drive limit per tenant to 288 drives per tenant. @frank is working on it. But we recommend the use the large drive count model for legacy deployments

Cloud native applications should not require large distributed single name space storage cassandra, gluster, ceph are all older approaches.

> We also consider to use many servers. The Java Minio client does not seem to support passing multiple IPs

Client will take just one endpoint

> So what is the recommended approach? Use HA Proxy and do Round Robin balancing? Or some client side balancing with multiple clients (should I prefer one node, or round robin)?

That is up to you, i.e what ever is convenient to your application/setup.

**Comment by malejpavouk** [comment]
Thanks for the quick answer. 

Is threre any time-frame in which you plan to have the disks limits increased in the stable version? We are currently doing evaluations of multiple technologies and while we like Minio, this may cause us some troubles.

Use case: we are storing _a lot_ of media files of the same type per customer. We do not want to shard this database, as this would require some rebalancing code (when some media files are deleted). And rebalancing again if customer adds more shards or wants remove any existing...

Two more questions (hopefully the last ones): 

1. It just occurred to me that if we use VMWare or some other virtualizer, we can create virtual disk with up to 64TB. Would it be possible to have lets say 10x64TB=640TB storage attached to Minio, or will we hit some other limitation?
2. Is it possible to disable the redundancy? I completely agree that the way Minio does it is superior to RAID, but unfortunatly we need to handle also customers with their own storage boxes, which are HA by default (and they expect that we'll not duplicate the data, as they already have it duplicated on HW level...)

**Comment by krishnasrinivas** [comment]
> Is threre any time-frame in which you plan to have the disks limits increased in the stable version? We are currently doing evaluations of multiple technologies and while we like Minio, this may cause us some troubles.

There is no time frame right now, it is in very early/design stage.

> It just occurred to me that if we use VMWare or some other virtualizer, we can create virtual disk with up to 64TB. Would it be possible to have lets say 10x64TB=640TB storage attached to Minio, or will we hit some other limitation?

It is possible to make it work but would advise against it. But note that there will be multiple layers of abstraction. Minio on top of XFS on top of VMDK on top of VMFS(?) on top of RAID on top of Disks.

> Is it possible to disable the redundancy? I completely agree that the way Minio does it is superior to RAID, but unfortunatly we need to handle also customers with their own storage boxes, which are HA by default (and they expect that we'll not duplicate the data, as they already have it duplicated on HW level...)

Yes you can use Minio without erasure. You can use minio like `minio server /mnt/export` and /mnt/export can have highly available storage.

**Comment by malejpavouk** [comment]
I have probably asked too vaguely, because according to docs the erasure will kick in automatically for distributed minio (your answer addresses single node setup).

So better wording of the question is: _Is it possible to run distributed Minio (HA mode) and have erasure disabled?_

**Comment by krishnasrinivas** [comment]
> I have probably asked too vaguely, because according to docs the erasure will kick in automatically for distributed minio (your answer addresses single node setup).

Distributed minio comes with erasure, yes.

> So better wording of the question is: Is it possible to run distributed Minio (HA mode) and have erasure disabled?

No. What might probably interest you is https://github.com/minio/mnm It is a small program and hence it can be customized to your needs.

**Comment by malejpavouk** [comment]
Thanks for your answers!
