### ISSUE TITLE
Propose a multipart upload backend without fcntl(3)-based coordination.

### ISSUE THREAD

**Issue by krisis** [minio/minio#4704]
Requirements
- Crash-consistent, concurrency-safe multipart upload
- Support user meta-data _iff_ EA support is present

**Comment by krisis** [comment]
The proposal and discussions surrounding it can be followed here - https://gist.github.com/krisis/761ff87ee0a7368681351239dca5733a

**Comment by GarimaKapoor** [comment]
@krisis did we reach any conclusion on this?

**Comment by krisis** [comment]
@garima, we decided that we will work on this after we finish ongoing projects.

**Comment by deekoder** [comment]
Moving this to future.

**Comment by deekoder** [comment]
Duplicate of #5063
