### ISSUE TITLE
Suggestion: Make OkHttpClient in MinioClient protected/provide extentension point

### ISSUE THREAD

**Issue by malejpavouk** [minio/minio#4707]
## Expected Behavior
The OkHttpClient should have **protected** modifier, a setter or an extension method (void customizeHttpClient(OkHttpClient client){}) in MinioClient class. This would follow the logic of _open to extension, close to modification_. 

The httpClient is statically typed (we are in Java), so the programmer does not have any way to modify the core behavior, but may decide to provide improved version of the http client itself. 

This can be for example used to introduce client load-side load balancing (one Minio client will be able to connect to any Minio node, do retry policy etc.).

## Current Behavior
Currently it is not possible to set custom OkHttpClient instance to minio client (it has **private** modifier), or to modify the HttpClient in any other way than is prescribed in MinioClient class.

---
Other possibility would be to at least allow to pass interceptor to the current OkHttpClient instance

Thanks!

**Comment by deekoder** [comment]
@malejpavouk  are you using minio's java sdk? https://github.com/minio/minio-java

**Comment by malejpavouk** [comment]
yes, the Java SDK

**Comment by balamurugana** [comment]
@malejpavouk refer https://github.com/minio/minio-java/issues/589
