### ISSUE TITLE
Explore alternatives for browser ux

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4710]
What could we use instead of react (in case license issue with react does not resolve).

**Comment by brendanashworth** [comment]
There's [no shortage of options](http://stateofjs.com/2016/frontend/) for [JS frontend frameworks](https://github.com/showcases/front-end-javascript-frameworks): [ember.js](https://emberjs.com/), [backbone.js](http://backbonejs.org/#), [vue.js](http://vuejs.org/), [Polymer](https://www.polymer-project.org/) and [angular.js](https://angularjs.org/) to name some of the most popular besides react. Selecting a framework can be very dependent on the team and intended use case, as well as opinionated. It's a deep hole that one can spend a lot of time in.

However our situation is that, should the license situation be an issue, we'd need to port the current browser over to a new framework. Similarities between react.js and the new framework would be what we want the most, and one option thats promising would be Google's [Polymer](https://www.polymer-project.org/) ([on github](https://github.com/Polymer/polymer)). Polymer is licensed under the BSD license.

I'd say the browser's three core parts are Redux, HTML extending components, and RPC.

- HTML extending components is also [Polymer's mojo](https://www.polymer-project.org/2.0/start/quick-tour). We should be able to keep all of our [components](https://github.com/minio/minio/tree/4785555d34a6a481ed9247e25e560585216b73fe/browser/app/js/components) without a major refactor, just slight ports in the actual code. This is a major plus, and I'm not sure if another library does it as similar as react does it.
- Redux is how the app manages [state and dispatching actions](https://github.com/minio/minio/blob/4785555d34a6a481ed9247e25e560585216b73fe/browser/app/js/actions.js). Polymer has a [Redux library](https://github.com/tur-nr/polymer-redux) that should allow us to keep some code the same, without reworking the entire state integration with the rest of the app.
- We have our own RPC implementation.

Of course, the best case scenario would be we keep React as is and don't have to change anything. The [PATENTS](https://www.elcaminolegal.com/single-post/2016/10/04/Facebook-Reactjs-License) situation needs to be discussed, and if it's deemed to be an issue we can look further into a new alternative.

**Comment by brendanashworth** [comment]
After the discussion, we've decided to move to Vuejs. This can be closed.

**Comment by harshavardhana** [comment]
We can move a new issue for migration instead @brendanashworth ? and then we can close this.

**Comment by GarimaKapoor** [comment]
@deekoder since we have already discussed on this issue. We should close it.

**Comment by deekoder** [comment]
Alternatives explored as presented by Brendan.
