### ISSUE TITLE
Disk formatting continues regardless of conflicting situation of starting Minio server 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4713]
## Expected Behavior
Should be only this 

```
ERRO[0002] http server exited abnormally                 cause=listen tcp :9000: bind: address already in use source=[signals.go:55:handleSignals()]
```

## Current Behavior
```
Endpoint:  http://192.168.43.246:9000  http://172.23.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://172.21.0.1:9000  http://172.22.0.1:9000  http://172.17.0.1:9000  http://172.24.0.1:9000  http://172.25.0.1:9000  http://172.26.0.1:9000  http://172.27.0.1:9000  http://172.28.0.1:9000  http://172.29.0.1:9000  http://127.0.0.1:9000
AccessKey: USWUXHGYZQYFYFFIT3RE 
SecretKey: MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03 
Region:    us-east-1
SQS ARNs:  arn:minio:sqs:us-east-1:1:redis arn:minio:sqs:us-east-1:2:redis

Browser Access:
   http://192.168.43.246:9000  http://172.23.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://172.20.0.1:9000  http://172.21.0.1:9000  http://172.22.0.1:9000  http://172.17.0.1:9000  http://172.24.0.1:9000  http://172.25.0.1:9000  http://172.26.0.1:9000  http://172.27.0.1:9000  http://172.28.0.1:9000  http://172.29.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.43.246:9000 USWUXHGYZQYFYFFIT3RE MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 74 GiB Free, 165 GiB Total
ERRO[0002] http server exited abnormally                 cause=listen tcp :9000: bind: address already in use source=[signals.go:55:handleSignals()]
```

## Possible Solution
We shouldn't be performing any action whatsoever on the backend, currently from what it looks like we are attempting to initialize object layer and failing later this can lead to serious bugs. 

We also wrote `format.json` even when we cannot start the server.  It is misleading to state that endpoint is ready when we can't start HTTP server. 

```
ls /tmp/2/.minio.sys/
[2017-07-23 06:25:11 PDT]    50B format.json
[2017-07-23 06:25:11 PDT] 4.0KiB multipart/
[2017-07-23 06:25:11 PDT] 4.0KiB tmp/
```

## Steps to Reproduce (for bugs)
Start `minio server /tmp/1` on terminal 1 and attempt to start another server on the same server on directory `/tmp/2` 

## Context
Testing for this release.. 

## Your Environment
master branch.

**Comment by harshavardhana** [comment]
I do not yet know how serious it is but it is important to investigate this before release in my opinion.

**Comment by krisis** [comment]
Minio server may format the disk on the first run before successfully listening on a given port. This doesn't affect correctness. On restart, when the port becomes available, minio server would function as expected with no loss of functionality or data. So, this is not an issue. @harshavardhana you could close the issue if you agree with the reasoning.

**Comment by harshavardhana** [comment]
> Minio server may format the disk on the first run before successfully listening on a given port. This doesn't affect correctness. On restart, when the port becomes available, minio server would function as expected with no loss of functionality or data. So, this is not an issue. @harshavardhana you could close the issue if you agree with the reasoning.

Agreed closing this. @krisis
