### ISSUE TITLE
Bucket remembers old policy

### ISSUE THREAD

**Issue by pablopla** [minio/minio#4714]
When deleting a bucket with read policy and recreating it, it remembers the read policy.

## Expected Behavior
New bucket should be private.

## Current Behavior
The new bucket has public read permission.

## Steps to Reproduce (for bugs)
1. Run minio server
2. Create a file with name 'test' in the current path with content 'hello'
3. Install python-boto3 (on ubuntu: sudo apt-get install python-boto3)
4. start python (python2)
5. Paste the following code in the terminal to create a bucket and upload the test file. Use your minio key and secret.
```python
import boto3
import json

minio_key = '<enter-minio-key>'
minio_secret = '<enter-minio-secret'
endpoint_url = 'http://127.0.0.1:9000'
bucket_name = 'docs'

client = boto3.client(
    's3',
    aws_access_key_id=minio_key,
    aws_secret_access_key=minio_secret,
    endpoint_url=endpoint_url
)

client.create_bucket(Bucket=bucket_name)
client.upload_file('test', bucket_name, 'test')
```
6. Try to load the object in a browser. You should see access denied error.
http://127.0.0.1:9000/docs/test
7. Paste the following code in the console to put a bucket policy:
```python
bucket_policy = {
    'Version': '2012-10-17',
    'Statement': [{
        'Sid': 'AllowPublicRead',
		'Action': ['s3:GetObject'],
        'Effect': 'Allow',
        'Principal': '*',
        'Resource': "arn:aws:s3:::%s/*" % bucket_name
    }]
}
bucket_policy = json.dumps(bucket_policy)
client.put_bucket_policy(Bucket=bucket_name, Policy=bucket_policy)
```
8. Verify that the bucket has a policy:
```python
client.get_bucket_policy(Bucket=bucket_name)
```
9. Try to load the object in the browser. Now it should succeed.
10. Paste the following code in the console to delete the object and the bucket:
```python
client.delete_object(Bucket=bucket_name, Key='test')
client.delete_bucket(Bucket=bucket_name)
```
11. Create the bucket and the object again:
```python
client.create_bucket(Bucket=bucket_name)
client.upload_file('test', bucket_name, 'test')
```
12. Try to load the object in the browser. It should fail but it succeeds.
http://127.0.0.1:9000/docs/test
13.  Verify that the bucket doesn't have a policy:
```python
client.get_bucket_policy(Bucket=bucket_name)
```

## Your Environment
* Version used (`minio version`):
Version: 2017-06-13T19:01:01Z
Release-Tag: RELEASE.2017-06-13T19-01-01Z
Commit-ID: 353f2d3a6e30f595a721abcd9cf1b108b041ee21
* Operating System and version (`uname -a`):
Linux miniotest 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pablopla** [comment]
After restarting the minio server, the object isn't accessible and the permissions are back to normal.
minio probably keep the bucket policy in memory and doesn't delete it when removing the bucket.

**Comment by harshavardhana** [comment]
I can't reproduce this using `mc policy` command 

```
$ mc mb home/testbucket2
Bucket created successfully `home/testbucket2`.
$ mc policy download home/testbucket2
Access permission for `home/testbucket2` is set to `download`
$ mc rm -r --force home/testbucket2
Removing `home/testbucket2`.
$ mc mb home/testbucket2
Bucket created successfully `home/testbucket2`.
$ mc policy list home/testbucket2
$ mc policy home/testbucket2
Access permission for `home/testbucket2` is `none`
```

But i was able to reproduce this.. the issue is inside removeBucketPolicy. In-fact this effects event notifications and listen bucket notification APIs as well.
