### ISSUE TITLE
Increase access key to 24 chars for compatibility with Azure

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio#4717]
When using Minio in Gateway mode to Azure, Access Keys are limited to 20 characters. Because the Access Key is the Azure Blob Storage Account name, which can be `[a-z0-9]{3,24}`, certain storage accounts cannot be used with Minio.

## Expected Behavior
When using Minio in Gateway mode to Azure, Access Keys are limited to 20 characters, so storage account with names of 21-24 characters aren't accepted.

## Current Behavior
Minio gives an auth error saying that the Access Key can only be up to 20 characters.

## Possible Solution
Increase Access Keys to 24 characters

**Comment by deekoder** [comment]
Can we remove the check on max limit check?

**Comment by harshavardhana** [comment]
Fixed by 

>commit 0f401b67ad37a22abdf213eec9d706c8030ae290
>Author: ebozduman <ersan.bozduman@gmail.com>
>Date:   Thu Aug 3 20:03:37 2017 -0700
>
>    Removes max limit requirement on accessKey and secretKey length (#4730)
