### ISSUE TITLE
Update Mesos & Kubernetes with latest release tag

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4721]
Since we have a new release. We need to send PRs to Mesos & Kubernetes . @krisis  could we also add these steps to the release doc.

**Comment by deekoder** [comment]
https://github.com/kubernetes/charts/pull/1304/files
https://github.com/mesosphere/universe/pull/1169/files

**Comment by nitisht** [comment]
@deekoder I can sent the PR for k8s/helm

**Comment by nitisht** [comment]
https://github.com/kubernetes/charts/pull/1546

**Comment by ebozduman** [comment]
I created a PR for required mesosphere/universe changes.
https://github.com/mesosphere/universe/pull/1290
Waiting for its approval and merge.
I also updated the [release doc](https://docs.google.com/document/d/1yRrWmAa2yjNNjmfnlL7oQfuskZZk5Vy2BjvZR3fZ2qo/edit#heading=h.r2p5sjd4d9jf) about what changes need to be done at kubernetes and mesosphere repos when there is a new minio release.
