### ISSUE TITLE
Change to semantic versioning

### ISSUE THREAD

**Issue by fzumstein** [minio/minio#4722]
minio's datetime version strings are very unusual. Semantic versioning (http://semver.org/) would be a huge improvement in user experience.

**Comment by harshavardhana** [comment]
Relevant previous issue and why we won't be doing it  https://github.com/minio/minio/issues/2318#issuecomment-235992350

**Comment by fzumstein** [comment]
thanks, sorry for the duplicate, will add further comments there.
