### ISSUE TITLE
minio distribute error

### ISSUE THREAD

**Issue by liujia88** [minio/minio#4723]
`nohup ./minio server --address :9004   http://192.168.48.105/home/work/miniofilepath http://192.168.48.94/home/work/miniofilepath http://192.168.48.98/home/work/miniofilepath http://192.168.48.99/home/work/miniofilepath &`

i use this command in test environment, it can work. but i use this command online environment,it goes wrong, error message:
`FATA[0000]` Invalid command line arguments server=‘:9004’, args=[http://192.168.48.105/home/work/miniofilepath http://192.168.48.94/home/work/miniofilepath http://192.168.48.98/home/work/miniofilepath http://192.168.48.99/home/work/miniofilepath]  cause=no endpoint found for this host `source=[server-main.go:95:serverHandleCmdArgs()]`

**Comment by vadmeste** [comment]
@liujia88, the machine which is running your command should have one of the ip addresses that you passed as arguments to Minio server, otherwise it won't work.

So your machine IP should be 192.168.48.105 or 192.168.48.94 or 192.168.48.98 or 192.168.48.99

**Comment by liujia88** [comment]
@vadmeste Could you give me some more details ,i did not find the doc about this,thks
