### ISSUE TITLE
Setting reverse proxy with IIS web server does not work

### ISSUE THREAD

**Issue by pintookhara** [minio/minio#4732]
Setting up minio with IIS reverse proxy does not work. 

## Expected Behavior
Client requests should be redirected to minio with URL rewrite setup in IIS  

## Current Behavior
IIS is expecting minio to be under inetpub/wwwroot folder causing 404 error 

## Steps to Reproduce (for bugs)
Setup reverse proxy in IIS using steps in the link below
[https://weblogs.asp.net/owscott/creating-a-reverse-proxy-with-url-rewrite-for-iis](url)

## Your Environment

* Version used (`minio version`):
* Environment name and version (IIS 8.5):
* Server type and version: Windows server 2012 R2 64 bit
* Operating System and version (Windows server 2012 R2):
* Link to your project:

**Comment by krisis** [comment]
> IIS is expecting minio to be under inetpub/wwwroot folder causing 404 error

@pintookhara is IIS expecting the minio binary to be present under inetpub/wwwroot folder?
Have you considered using nginx on Windows for the same purpose? You can find more information on setting up a reverse-proxy using nginx here - https://docs.minio.io/docs/setup-nginx-proxy-with-minio

**Comment by krisis** [comment]
@pintookhara did you get a chance to try nginx for reverse-proxy?

**Comment by pintookhara** [comment]
Cannot use nginx due to company IT policy, only IIS can be used. We have to drop the use of Minio if reverse-proxy does not work with IIS.

**Comment by krisis** [comment]
@pintookhara 
> IIS is expecting minio to be under inetpub/wwwroot folder causing 404 error

Is IIS expecting the minio binary to be under inetpub/wwwroot folder? If so, does simply copying it over solves the issue for you?

**Comment by krisis** [comment]
@pintookhara Could you paste the rewrite rule(s) you tried to proxy object storage requests to a Minio server?

**Comment by pintookhara** [comment]
Followed these steps to setup reverse proxy in IIS [https://blogs.msdn.microsoft.com/friis/2016/08/25/setup-iis-with-url-rewrite-as-a-reverse-proxy-for-real-world-apps/](url)

**Comment by krisis** [comment]
@pintookhara Could you join us on https://slack.minio.io/?  We could go over your rewrite rules and see why it is not working with Minio.

**Comment by deekoder** [comment]
We do plan to do this @pintookhara  in future.

**Comment by ghost** [comment]
Is there a reason for using Reverse Proxy? Are you trying to achieve load balancing with IIS?

**Comment by deekoder** [comment]
Addressed via slack. If not please reopen.

**Comment by harshavardhana** [comment]
Just to reference - You have to run this 
```
%windir%\system32\inetsrv\appcmd.exe set config -section:system.webServer/proxy -preserveHostHeader:true /commit:apphost
```
Other information -https://stackoverflow.com/questions/14841986/iis-aar-url-rewrite-for-reverse-proxy-how-to-send-http-host
