### ISSUE TITLE
File expiration support

### ISSUE THREAD

**Issue by zivgabel** [minio/minio#4734]
Hi,
Is it possible to set an expiration date to a file/bucket.
I mean that if I set the expiration for a file to a specific date, the file will be removed from the server at that time.

**Comment by vadmeste** [comment]
@zivgabel hey, Minio doesn't support that feature.

You can join us here https://slack.minio.io if you have any additional questions.

**Comment by deekoder** [comment]
@zivgabel closing this issue. Please let me know if we can address this further. Feel free to reopen if you think Minio must address this.
