### ISSUE TITLE
Healthcheck TLS error

### ISSUE THREAD

**Issue by Darkknight33** [minio/minio#4737]
When accessing Minio docker instance configured for TLS directly via IP of the host, healthcheck fails with following error message:

time="2017-07-31T06:34:53Z" level=error msg="Error in reading from new TLS connection 192.168.0.199:60697 at server 172.17.0.3:9000" cause=EOF source="[listener.go:170:github.com/minio/minio/pkg/h                             ttp.(*httpListener).start.func2()]"

## Expected Behavior
Accessing it directly via IP should not generate a healthcheck error in the container. Client side browser warning is enough.

## Current Behavior
Everytime a page is accessed via the browser using the IP directly a TLS error message is logged.

## Possible Solution
Silently fail TLS error. 

## Steps to Reproduce (for bugs)
Create docker instance of Minio
Configure for TLS to external domain
Access Minio via internal IP:port

## Context
Healthchecks are unreliable

## Your Environment
* Version used (`minio version`): minio/minio:latest
* Server type and version: ESXi 6
* Operating System and version (`uname -a`): Debian Stretch

**Comment by nitisht** [comment]
Fixed by https://github.com/minio/minio/pull/4740
