### ISSUE TITLE
Int overflow in TestListObjects on 32-bit systems

### ISSUE THREAD

**Issue by ws141** [minio/minio#4738]
When running the tests on a 32-bit system I end up with a int overflow.

## Expected Behavior
Test shouldn't fail even if ran on a 32-bit systems.

## Current Behavior
Currently I end up with the following behaviour when running the TestListObjects test.

```
$ go test -run TestListObjects
# github.com/minio/minio/cmd
./object-api-listobjects_test.go:449: constant 1111000000000000 overflows int
./object-api-listobjects_test.go:455: constant 1234567891011 overflows int
FAIL	github.com/minio/minio/cmd [build failed]
```

This occurs due to the fact that the maxKeys property is defined as an int and the values that are being sent in are bigger then a 32-bit int.

According to the [go tour](https://tour.golang.org/basics/11) : `The int, uint, and uintptr types are usually 32 bits wide on 32-bit systems and 64 bits wide on 64-bit systems.` which means that the type will vary between the systems.

## Possible Solution
There are 2 possible solutions as I see it.

1. Change the maxValue data type to int64.
2. Use smaller values then [2147483647](https://en.wikipedia.org/wiki/2,147,483,647#In_computing) in the tests cases.

## Steps to Reproduce (for bugs)
1. Use a 32-bit machine like Raspberry Pi 2 Model B v1.1
2. Clone repository `go get github.com/minio/minio`
3. Change directory to cmd `cd $GOPATH/src/github.com/minio/minio/cmd`
3. Run ListObjects test `go test -run TestListObjects`

## Context
I was trying to run the tests in order to see if they work as expected on 32-bit arm architecture.

## Your Environment
* Version used (`minio version`):
Latest checkout of master branch currently at commit: `ec5293ce29ef03726c7174d9e3304bc156259c4e`
* Server type and version:
`go version go1.7.6 linux/arm`
Raspberry Pi 2 Model B v1.1
* Operating System and version (`uname -a`):
Debian 8 Jessie
`Linux rpi 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux`

**Comment by donatello** [comment]
Thank you for the bug report!

We will fix the tests to not overflow the int type. The max-keys parameter of the API cannot exceed 1000 according to the spec. So such large numbers should not be used in tests too.
