### ISSUE TITLE
unexpected directory layout when running from source code

### ISSUE THREAD

**Issue by liuxuan30** [minio/minio#4745]
I want to run it from the source,

I create my directory like:
```
~/Downloads/minio-RELEASE.2017-06-13T19-01-01Z
|
 src
   |
    all minio directories, including vendor, like the image below
```
![golang](https://user-images.githubusercontent.com/4375169/28810945-ec42164c-76be-11e7-98cc-2c1b8236b790.png)

but it throws errors:
```
GOROOT=/usr/local/Cellar/go/1.8.3/libexec
GOPATH=/Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z:/Users/xl/go
/usr/local/Cellar/go/1.8.3/libexec/bin/go build -i -o /private/var/folders/8v/6dg7d6mx2850sv1gp8ts9thm0000gn/T/go_run_main_gogo /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src/main.go
unexpected directory layout:
    import path: github.com/Azure/azure-sdk-for-go/storage
    root: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src
    dir: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src/vendor/github.com/Azure/azure-sdk-for-go/storage
    expand root: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src
    expand dir: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src/vendor/github.com/Azure/azure-sdk-for-go/storage
    separator: /
```
when launching.

## Expected Behavior
minio should start correctly

## Current Behavior
```
GOROOT=/usr/local/Cellar/go/1.8.3/libexec
GOPATH=/Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z:/Users/xl/go
/usr/local/Cellar/go/1.8.3/libexec/bin/go build -i -o /private/var/folders/8v/6dg7d6mx2850sv1gp8ts9thm0000gn/T/go_run_main_gogo /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src/main.go
unexpected directory layout:
    import path: github.com/Azure/azure-sdk-for-go/storage
    root: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src
    dir: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src/vendor/github.com/Azure/azure-sdk-for-go/storage
    expand root: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src
    expand dir: /Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z/src/vendor/github.com/Azure/azure-sdk-for-go/storage
    separator: /
```
## Possible Solution
No idea

## Steps to Reproduce (for bugs)
same as above

## Context
GOROOT=/usr/local/Cellar/go/1.8.3/libexec
GOPATH=/Users/xl/Downloads/minio-RELEASE.2017-06-13T19-01-01Z:/Users/xl/go

## Your Environment

* Version used (`minio version`):minio-RELEASE.2017-06-13T19-01-01Z
* Environment name and version (e.g. nginx 1.9.1):None
* Server type and version: macOS

**Comment by harshavardhana** [comment]
@liuxuan30 go tooling doesn't allow the code to built in this manner - release tarballs are just for placeholder only either use the binary directly or if you wish to build it from source please follow following  instructions, it is expected that GOPATH is set and you have Go installed properly by now. 

```
$ go get -d github.com/minio/minio
$ cd $GOPATH/src/github.com/minio/minio
$ git checkout RELEASE.2017-06-13T19-01-01Z
$ make
```

Also curious why do you wish to run it from source @liuxuan30 ? what purpose does it solve ? and what are you trying to achieve?  I don't see any explanation on what you are trying to achieve by doing something like this. 

if you are trying to contribute code please use the master branch directly by forking the git repository and sending pull requests.

**Comment by liuxuan30** [comment]
I just want to use Gogland to debug minio :) e.g. add break points 
And it turned out Gogland debugger might have issue even I run from source.. the break point does not works well

Feel free to close this, thanks!

**Comment by harshavardhana** [comment]
> Feel free to close this, thanks!

Thanks @liuxuan30
