### ISSUE TITLE
s3ql implementation with minio

### ISSUE THREAD

**Issue by Notespeak** [minio/minio#4750]
Hello. I am trying to mount a minio bucket via s3ql. Unfortunately I am stuck at "Mounting filesystem....." . This (possibly bug) is easily reproducible and I got the same error 5 times in a row, both on google cloud and home lab. 
The steps are
-  `sudo apt-get install s3ql`
- `mkfs.s3ql --backend-options no-ssl s3c://ip:9000/bucket`
- `mount.s3ql  --backend-options no-ssl s3c://ip:9000/bucket /var/clstrg/`

After these steps, the s3ql will freeze at "Mouting filesystem"
System: Ubuntu 16.04 lts
Minio version: current master.
Minio server doesn't seem to give out any errors during the process. All s3ql files are always created inside the bucket.
I tried to lower the default cache size, and adding --allow-other, using ssl but none seem to work.
I also found a confirmed case, when a similar setup was said to be in working condition https://bitbucket.org/nikratio/s3ql/issues/246/s3ql-and-minio-s3-server .
It seems very strange, that it doesn't seem to work at all in my case. Or maybe I am just a noob).

**Comment by harshavardhana** [comment]
Sorry for the delay @Notespeak in reaching out. 

- Can you provide us the s3ql version under use? 
- Can you try again with the latest Minio server and see if the issue persists?

**Comment by vadmeste** [comment]
@harshavardhana, I tested with the latest Minio (2017-08-05T00:00:53Z ) and the latest s3ql (2.22).  Uploading files is working and s3ql was even able to create empty directories.

**Comment by GarimaKapoor** [comment]
If you have validated it can we close it @vadmeste

**Comment by vadmeste** [comment]
yes, we can close it
