### ISSUE TITLE
Exit during boot-up in case of cross device buckets

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4764]
The issue is explained better in free form rather than issue template.

Currently if a bucket is a mount point, rename from `.minio.sys/tmp` to the bucket will fail with error EXDEV (Invalid cross-device link) Hence PutObject will fail during runtime.

Hence during bootup we should check if any of the bucket's `st_dev` obtained from the stat() syscall is different from the export directory. If any such bucket is found we should fail during the boot itself.

**Comment by harshavardhana** [comment]
we shouldn't exit, we can perhaps ignore such buckets and continue with the rest? . This is almost like how we ignore `capitalized` bucket names?

**Comment by krishnasrinivas** [comment]
@harshavardhana AB wanted the process to exit with error. we can check with him.

**Comment by harshavardhana** [comment]
> @harshavardhana AB wanted the process to exit with error. we can check with him.

I think we can ignore and keep running we do ignore non-conforming buckets anyways..
