### ISSUE TITLE
Bucket URI conflicts with login page's URI when named 'login'

### ISSUE THREAD

**Issue by samluthebrave** [minio/minio#4766]
URI of bucket named 'login' and URI of login page are identical, making the bucket unaccessible.

## Expected Behavior
Any successfully created bucket can be accessed.

## Current Behavior
You can successfully create a bucket named 'login', and it does appear on the sidebar, but click on it won't jump into it.

## Possible Solution
Change login URI or reserve name 'login' from bucket creating.

## Steps to Reproduce (for bugs)
1. create a bucket named 'login'
2. find it on the sidebar and click it

**Comment by nitisht** [comment]
@samluthebrave thank you for finding the issue. We are taking a fresh look at how to handle such scenarios. Here are the details https://github.com/minio/minio/issues/4809

**Comment by ckuetbach** [comment]
Regarding [Amazon documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) bucket names must be at least 3 chars long.

If all UI is accessable wothin /ui/* all valid bucket names are accessable.

**Comment by deekoder** [comment]
Refactoring as per https://github.com/minio/minio/issues/4809 will take care of this.

**Comment by deekoder** [comment]
Whenever we refactor for newux pod we have to do so such that /login is not used in the URL.
