### ISSUE TITLE
newux: pending bugs

### ISSUE THREAD

**Issue by brendanashworth** [minio/minio#4772]
This is a list of current bugs in the `newux` branch that should be resolved before it is merged into `master`.

- [ ] dropdown toggle incorrectly centers on Firefox (https://github.com/minio/minio/pull/4725#discussion_r129454604)
- [ ] dragging a file onto the dropbox and dragging it back without dropping it doesn't cancel dropzone (https://github.com/minio/minio/pull/4725#discussion_r129456188)
- [ ] close icon centering isn't good across browsers (https://github.com/minio/minio/pull/4725#discussion_r129456909)
- [ ] sort icons should more clearly identify which category they're sorting (https://github.com/minio/minio/pull/4725#discussion_r130493278)
- [ ] settings panel leads to change password panel (https://github.com/minio/minio/pull/4725#discussion_r130493654)
- [ ] dropzone with multiple files duplicates entire bucket listing (https://github.com/minio/minio/pull/4725#issuecomment-319233915)
- [ ] grid view needs to be implemented
- [ ] should warn user if they close tab while uploading file (https://github.com/minio/minio/issues/4748#issuecomment-320428847)

**Comment by rushenn** [comment]
@deekoder Can you please re-check the dropdown toggle issue ([#4725 (comment)](https://github.com/minio/minio/pull/4725#discussion_r129454604)). It looks fine on my end, running MacOS 10.12.5, Chrome 60.0.3112.90, Firefox 54.0.1 (64-bit) and Safari 10.1.1 (12603.2.4).
