### ISSUE TITLE
TestHTTPListenerAddrs fails sporadically on travis-ci

### ISSUE THREAD

**Issue by krisis** [minio/minio#4774]
## Expected Behavior

Unit test must pass deterministically on all travis-ci runs.

## Current Behavior

It fails intermittently on travis-ci builds.

## Possible Solution

Not known yet

## Steps to Reproduce (for bugs)

1. Travis-CI build
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
One more such occurrence  - 
[log.txt](https://github.com/minio/minio/files/1205977/log.txt)


```
--- FAIL: TestNewHTTPListener (0.01s)
	listener_test.go:228: error: expected = <nil>, got = listen tcp 127.0.0.1:60002: bind: address already in use
--- FAIL: TestHTTPListenerStartClose (0.00s)
	listener_test.go:282: Test 3: error: expected = <nil>, got = listen tcp 127.0.0.1:60006: bind: address already in use
```
