### ISSUE TITLE
Update Mesos and Kubernetes with latest release tags

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4776]

**Comment by nitisht** [comment]
@deekoder @krisis I have a PR pending to universe package, I will just update the version there. https://github.com/mesosphere/universe/pull/1330

**Comment by nitisht** [comment]
sent a PR for helm chart as well https://github.com/kubernetes/charts/pull/1638

The helm chart was at older config version of minio server, so had to sent this to avoid any config mismatch issues.

**Comment by GarimaKapoor** [comment]
Is this issue still relevant?
