### ISSUE TITLE
https not work for my local minio server

### ISSUE THREAD

**Issue by billschen** [minio/minio#4789]
Hi,I user minio in windows 7 64bit,I download minio.exe to my folder and run cmd
minio.exe server D:\miniofiles

then I open the url [http://192.168.1.149:9000/minio](http://192.168.1.149:9000/minio) and login.
then I create a bucket, I work find like:
![del_48](https://user-images.githubusercontent.com/19528399/29059970-6c08541e-7c4a-11e7-9470-2b8c0b0cdc23.png)
Next I want to switch http to https like the online sample [https://play.minio.io:9000/minio/login](https://play.minio.io:9000/minio/login)  .BUT at last fail like:
![del_49](https://user-images.githubusercontent.com/19528399/29060109-f6a0c584-7c4a-11e7-8ad6-eb825ed32539.png)

Any suggestions would be appreciated

**Comment by harshavardhana** [comment]
@billschen have you looked at https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls ?

**Comment by billschen** [comment]
@harshavardhana :+1: thank you very much! I  try right now

**Comment by billschen** [comment]
@harshavardhana . I follow the instructions :
1: create private.key
certtool.exe --generate-privkey --outfile private.key 

2: edit cert.cnf 
`# X.509 Certificate options
#
# DN options

# The organization of the subject.
organization = "GDGW Inc."

# The organizational unit of the subject.
#unit = "sleeping dept."

# The state of the certificate owner.
state = "GDGD"

# The country of the subject. Two letter code.
country = "ZH"

# The common name of the certificate owner.
cn = "gd_gdgw_cn"

# In how many days, counting from today, this certificate will expire.
expiration_days = 3650

# X.509 v3 extensions

# DNS name(s) of the server
dns_name = "localhost"

# (Optional) Server IP address
ip_address = "127.0.0.1"

# Whether this certificate will be used for a TLS server
tls_www_server

# Whether this certificate will be used to encrypt data (needed
# in TLS RSA ciphersuites). Note that it is preferred to use different
# keys for encryption and signing.
plegotoolforgeneratingself-signedcertificatesbutworksforthe
`

3:run command:
certtool.exe --generate-self-signed --load-privkey private.key --template cert.cnf --outfile public.crt 

4:copy private.key  public.crt to C:\Users\BJB70\.minio\certs\CAs   BJB70 is user name
![del_50](https://user-images.githubusercontent.com/19528399/29062654-14710542-7c55-11e7-849a-aa5c91b40a6c.png)


5:install  certificate  
![del_51](https://user-images.githubusercontent.com/19528399/29063183-59a2e8ae-7c57-11e7-960f-fcf588c8b220.png)
![del_52](https://user-images.githubusercontent.com/19528399/29063187-5dc29b8c-7c57-11e7-950f-8338d6b33d00.png)



BUT  also fail at last
![del_53](https://user-images.githubusercontent.com/19528399/29063189-60326abe-7c57-11e7-9cd0-30a16391c6d2.png)

my host name is BJB-70

**Comment by vadmeste** [comment]
@billschen, you should copy private.key and public.crt in .minio\certs\ and not .minio\certs\CAs

**Comment by billschen** [comment]
@harshavardhana  :  @vadmeste :+1: is the right way,the Solved my problem， I can use https now like:

![del_55](https://user-images.githubusercontent.com/19528399/29072658-26fc8850-7c7b-11e7-93f4-f4512e6dbf84.png)


so the instruction in the page [How to secure access to Minio server with TLS](https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls) my be have some mistake:
![del_54](https://user-images.githubusercontent.com/19528399/29072669-300dffb4-7c7b-11e7-923b-8935dc049d71.png)

**Comment by vadmeste** [comment]
@billschen, "Install third-party CAs" describes how to make Minio able to connect to *other* servers and trust their self signed certificates.

**Comment by billschen** [comment]
@vadmeste :+1:  ,OK, I make a mistake thank you for your help!
