### ISSUE TITLE
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by AlViKo** [minio/minio#4791]
Our customer uses Cloudberry Backup tool and trying to upload the data to the local storage, configured with Minio. 
## Expected Behavior

The expected behavior is successfully uploaded data. It's Image Based Backup.
## Current Behavior

Backup interrupts on 33-36% with an error "Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host."
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 2017-08-05T00-00-53Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: Single server, no load balancing, loading 4 inststances of minio server with different ports.  Virtualzied machine in vmware environment.
* Operating System and version (`uname -a`): Linux Ubuntu1a 4.8.0-58-generic #63-16.04.1-Ubuntu SMP Mon Jun26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 CNU/Linux
* Link to your project:

**Comment by vadmeste** [comment]
@AlViKo, sorry for the delay, did you see any output in Minio server ?

**Comment by deekoder** [comment]
@AlViKo closing this as we don't have enough information to further look into this issue. Please reopen if you have more information.
