### ISSUE TITLE
listParts does not return all parts that have been uploaded

### ISSUE THREAD

**Issue by kyleburnett** [minio/minio#4792]
## Expected Behavior
After a part has been uploaded, a subsequent call to listParts should provide that part in the response.

## Current Behavior
No parts are found.

```
Set up test bucket
Setup: Create multipart for file0
Setup: Upload multipart for file0
Test: List parts for file0
Tear down test bucket
AssertionError: 0 == 1
    at /Users/kyle/Documents/scripts/minio-test/test2.js:41:16
    at tryCatcher (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/promise.js:638:18)
    at Response.<anonymous> (/Users/kyle/Documents/scripts/minio-test/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.<anonymous> (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kyle/Documents/scripts/minio-test/node_modules/aws-sdk/lib/request.js:38:9)
```

## Possible Solution
This was working before the most [recent release](https://github.com/minio/minio/releases/tag/RELEASE.2017-08-05T00-00-53Z). Perhaps one of those "fixes" is the culprit.

## Steps to Reproduce (for bugs)
Here is a gist: https://gist.github.com/kyleburnett/bb85c386162e2a32c6d092f7898ea6a4

1. Run `npm install` to install dependencies.
2. Run `node setup.js` to generate random data.
Replace "your accessKeyId here", "your secretAccessKey here", and "your endpoint here" in `test2.js`
Run `test2.js`.

## Context
I had originally reported #4727. When I ran my test case again after RELEASE.2017-08-05T00-00-53Z was made available, I encountered a MalformedXML error because `completeMultipartUpload` was being called with no parts. I then created the simplified test2.js to isolate the issue in `listParts`.

## Your Environment
- On a Vagrant VM:
  - Minio: 2017-08-05T00:00:53Z
  - Docker: v1.11.1
  - OS: Ubuntu 14.04.4
- Host
  - Node.js: v4.4.7
  - OS: macOS Sierra v10.12.5

**Comment by harshavardhana** [comment]
This is intentional @kyleburnett // cc @krisis

**Comment by krisis** [comment]
@kyleburnett With Minio server (2017-08-05T00:00:53Z) in single disk mode ListParts always returns empty response. This is the first step towards making Minio's [multipart backend representation](https://gist.github.com/krisis/761ff87ee0a7368681351239dca5733a) crash-consistent without requiring lock-based synchronization.
Further, we anticipate most applications to hold information about parts uploaded in an ongoing multipart upload and not to rely on ListParts to take the upload to completion.

**Comment by kyleburnett** [comment]
Ah, so if I specify more than one drive like in Example 2 [here](https://docs.minio.io/docs/multi-tenant-minio-deployment-guide), ListParts will return parts as I expect?

**Comment by krisis** [comment]
@kyleburnett you could do that. How do you intend to use ListParts in your application? Why do you prefer using it over remembering parts uploaded so far?

**Comment by kyleburnett** [comment]
I have a client that is uploading parts of a file concurrently to a set of API servers behind a load balancer. After each part completes, I obviously have to check if I have all the parts in order to know whether I can complete the upload. Currently, we are using ListParts to make that determination as opposed to storing the status of each chunk in our relational database. As such, the behavior of ListParts is currently critical to our upload workflow.

We could rewrite our upload logic to maintain the list of uploaded parts. However, for our cloud-based deployments, we use s3, which supports this workflow (We use minio for local development/testing and on-premise installations.).

**Comment by krishnasrinivas** [comment]
@kyleburnett does your client make use of this call also? http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListMPUpload.html

**Comment by kyleburnett** [comment]
The client does not make any calls to s3. The client makes calls to our API, which in turn makes calls to s3 or minio (depending on whether type of the deployment is cloud-based or on-premise) using the AWS SDK.

The API server doesn't list multipart uploads either. The client uses another API route to create a multipart upload (which we **do** store in our database) before initiating the individual part uploads. Each part upload references the created multipart upload. In other words, we are maintaining a list of active uploads, we just don’t maintain a list of completed upload parts.

**Comment by krisis** [comment]
@kyleburnett, what happens when upload of a part (say part 9) fails during upload of an object (made of 10 parts)? If you rely on information returned by ListParts you would leave out part 9 from your object right?

AWS S3 document discourages using ListParts as source of truth for complete multipart upload request, possibly due to situations like above. (Ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html). To quote,
> Only use the returned listing for verification. You should not use the result of this listing when sending a complete multipart upload request. Instead, maintain your own list of the part numbers you specified when uploading parts and the corresponding ETag values that Amazon S3 returns. 

While it is (still) possible for Minio to list parts of an upload, we return empty response to stop applications from relying on ListParts for the 'wrong' reason. The client is better positioned to know if all parts of an object have been uploaded. In your case, I understand it requires you to change the application code. But this change ensures that your upload logic is resilient to upload part failures on S3 too.

**Comment by kyleburnett** [comment]
Okay, thanks for the reference - I didn't know about that aspect of multipart uploads. I will refactor my application code accordingly.

**Comment by harshavardhana** [comment]
> Okay, thanks for the reference - I didn't know about that aspect of multipart uploads. I will refactor my application code accordingly.

Feel free to close this issue @kyleburnett
