### ISSUE TITLE
Minio instances(services) cannot share the same volume when deploying with docker-compose

### ISSUE THREAD

**Issue by IustinaN** [minio/minio#4801]
I have a docker-compose.yml which defines 4 Minio instances: the first 2 share a volume and the other ones another volume.

## Expected Behavior
I'd expect to have a working setup (minio instances to be up and running and accessible from browser).

## Current Behavior
Every node is exiting with the following stacktrace:

minio2_1  | time="2017-08-09T13:28:26Z" level=fatal msg="Unable to initialize XL object layer." cause="Unable to recognize backend format, invalid character '{' after top-level value" source="[xl-v1.go:74:newXLObjectLayer()]" 
minio_minio2_1 exited with code 1
minio1_1  | time="2017-08-09T13:28:28Z" level=error msg="Unable to shutdown http server" cause="timed out. some connections are still active. doing abnormal shutdown" source="[server-main.go:208:serverMain()]" 
minio_minio1_1 exited with code 1
minio3_1  | time="2017-08-09T13:28:36Z" level=error msg="Initializing object layer failed" cause="\n[01/04] http://minio1:9000/myexport1 : disk not found\n[02/04] http://minio2:9000/myexport1 : unformatted disk found\n[03/04] /myexport2 : unformatted disk found\n[04/04] http://minio4:9000/myexport2 : invalid character '{' after top-level value" source="[server-main.go:206:serverMain()]" 
minio3_1  | time="2017-08-09T13:28:41Z" level=error msg="Unable to shutdown http server" cause="timed out. some connections are still active. doing abnormal shutdown" source="[server-main.go:208:serverMain()]" 
minio_minio3_1 exited with code 1
minio4_1  | time="2017-08-09T13:28:54Z" level=error msg="Initializing object layer failed" cause="\n[01/04] http://minio1:9000/myexport1 : disk not found\n[02/04] http://minio2:9000/myexport1 : disk not found\n[03/04] http://minio3:9000/myexport2 : invalid character '{' after top-level value\n[04/04] /myexport2 : invalid character '{' after top-level value" source="[server-main.go:206:serverMain()]" 

## Steps to Reproduce (for bugs)
Run **docker-compose up** for the following configuration:

version: '3.1'
services:
  minio1:
    image: minio/minio
    ports:
      - 9001:9000
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - minio1:/myexport1
    command: server http://minio1/myexport1 http://minio2/myexport1 http://minio3/myexport2  http://minio4/myexport2
  minio2:
    image: minio/minio
    ports:
      - 9002:9000
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - minio1:/myexport1
    command: server http://minio1/myexport1 http://minio2/myexport1 http://minio3/myexport2  http://minio4/myexport2
  minio3:
    image: minio/minio
    ports:
      - 9003:9000
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - minio2:/myexport2 
    command: server http://minio1/myexport1 http://minio2/myexport1 http://minio3/myexport2  http://minio4/myexport2
  minio4:
    image: minio/minio
    ports:
      - 9004:9000
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - minio2:/myexport2 
    command: server http://minio1/myexport1 http://minio2/myexport1 http://minio3/myexport2  http://minio4/myexport2
volumes:
  minio1:
    driver: local
  minio2:
    driver: local

I also tried with the following volumes: _minio1:/myexport_  and  _minio2:/myexport_

then running command _server http://minio1/myexport http://minio2/myexport http://minio3/myexport  http://minio4/myexport_ on each node and I'm still seeing them exiting.

## Context
The ultimate scenario would be to have 2 different machines, each with 2 Minio instances. The first machine would have 2 Minio instances sharing volume1, the other one another 2 instances sharing volume2. Over them an overlay network would be created within a docker swarm setup.

**However, with the provided configuration I'm firstly trying to find out if sharing one volume between 2 Minio instances is possible (locally, on a single machine).** 

## Your Environment

* Version used (`minio version`): latest
* Operating System and version (`uname -a`): Ubuntu 16.04 Xenial

**Comment by vadmeste** [comment]
@IustinaN, this configuration setup won't work with Minio, but I am not sure what you want to do exactly. You want to run four instances, will these four instances be belonging to the same cluster or two different clusters ?

**Comment by IustinaN** [comment]
In order to see if 2 Minio instances can share the same volume, I've provided above a setup with 4 instances (Minio services) deployed on the same machine, same host but with different ports: the first 2 are sharing _minio1:/myexport1_ volume, the next 2 are sharing _minio2:/myexport2_ volume.

Given the mentioned volumes, honestly I'm not sure about the 'command' that is executed on each instance: _server http://minio1/myexport1 http://minio2/myexport1 http://minio3/myexport2 http://minio4/myexport2_ . Maybe there is smth wrong with my setup...

Or, asking more explicitly: what is the correct way of defining a shared volume between 2 different  Minio instances using docker-compose? I've tried the approach with different volume per instance and is working, but taking into account the storage perspective I would like to make use of shared volumes if possible...

**Comment by vadmeste** [comment]
@IustinaN, having two pair of nodes, where each pair shares the same volume, means you are going to have two small clusters, each cluster will have its own buckets and objects. Is that what you want to do ?

**Comment by IustinaN** [comment]
Yes, with the condition that buckets and objects to be replicated between clusters.

But at the moment the most important is to have 2 minio instances sharing the same volume in each cluster. How can I achieve this functionality from configuration perspective?

**Comment by vadmeste** [comment]
@IustinaN, can you join us here ? https://slack.minio.io, we can have a richer conversation there.

**Comment by vadmeste** [comment]
We cannot have shared disks + data protection (erasure) at the same time.

Closing this after having a private conversation
