### ISSUE TITLE
Can S3 buckets be azure accounts instead of containers

### ISSUE THREAD

**Issue by krisis** [minio/minio#4818]
Explore if S3 buckets must be mapped to Azure accounts instead of containers

**Comment by krisis** [comment]
Following is how Minio gateway can work with S3 buckets and
leverage data isolation of Azure storage accounts.

Azure Blob Storage (ABS) uses accounts for multi-region availability
much like buckets in AWS S3. In addition, it provides data isolation
with each account having its own credentials. On the other hand, AWS
S3 allows applications to create many buckets with the same
credentials. There are many ways to bridge this difference between
Azure accounts and S3 buckets including the one below.

Minio Gateway for Azure manages _one_ Azure storage account per
instance. For each new account a new Minio Gateway instance can be
started with its own Azure account credentials. This provides data
isolation like ABS. Application(s) using a Minio Gateway instance can create
as many 'buckets' (i.e, blob containers) as required using the same credential
like AWS S3.

Illustration:

Instance 1 on VM1 serving account1

$ export MINIO_ACCESS_KEY=azureAccount1
$ export MINIO_SECRET_KEY=account1Key
$ minio gateway --address ":9000" azure

Instance 2 VM1 (same VM) serving account2

$ export MINIO_ACCESS_KEY=azureAccount2
$ export MINIO_SECRET_KEY=account2Key
$ minio gateway --address ":9001" azure

and so on. This provides process-level isolation across different
accounts while using fewer VMs.

Solution:
This can be packaged into a single VM image for usability as below,

- An agent process periodically scans for new storage accounts and
  launches one Minio Gateway instance per account.

- Create a Service Principal for the agent to access storage accounts.

Note: The admin/operator is required to create storage accounts as required.

**Comment by krisis** [comment]
In the same breath we should document the above solution in Minio Gateway for Azure docs.

**Comment by deekoder** [comment]
@krisis  can we close this issue in this repo?

**Comment by krisis** [comment]
@deekoder yes we can close this issue.
