### ISSUE TITLE
Add docs for S3 gateway

### ISSUE THREAD

**Issue by krisis** [minio/minio#4830]
## Expected Behavior

Documentation for Minio gateway for S3 
## Current Behavior

No documentation available
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
We will do this after @poornas  completes the caching feature.
