### ISSUE TITLE
minio cluster startup with a error message showing unformatted disk found

### ISSUE THREAD

**Issue by dingjs** [minio/minio#4831]
Hi!
I have a 4 nodes minio cluster, one node is 10 seconds apart from the other 3 nodes(I know it shouldn't be bigger than 3 seconds apart).When I start the minio server,the console print some error message: 'unformatted disk found'.When I use ntp to make the time right,the error message is gone and the cluster runs perferctly.So maybe the error message can change a little bit.

**Comment by harshavardhana** [comment]
This should only happen if it was a fresh disk and there is no conclusive way to know this.

Otherwise it might be a bug on our end.

**Comment by vadmeste** [comment]
When all disks are initialized with time skew between nodes, I can see the following output
```
Detected configuration inconsistencies in the cluster. Please fix following servers.
[01/04] http://147.75.81.25:9000/root/backend/m1 : Server times are too far apart
[02/04] http://147.75.81.25:9000/root/backend/m2 : Server times are too far apart
```

But when disks are not initialized, with time skew:

```
Detected configuration inconsistencies in the cluster. Please fix following servers.
[01/04] /root/backend/m1 : unformatted disk found
[02/04] /root/backend/m2 : unformatted disk found
[03/04] http://147.75.83.39:9000/root/backend/m3 : Server times are too far apart
[04/04] http://147.75.83.39:9000/root/backend/m4 : Server times are too far apart
```

Shall we modify this and print a more sophisticated error message? I think we can do that: the code which decides that there is a configuration inconsistencies can also create the appropriate error message to show to the user.

**Comment by harshavardhana** [comment]
> Shall we modify this and print a more sophisticated error message? I think we can do that: the code which decides that there is a configuration inconsistencies can also create the appropriate error message to show to the user.

We can do that @vadmeste . But do not yet know what else we can say in this.

**Comment by deekoder** [comment]
@kannappanr  please take a look at the error message printed in this case.
