### ISSUE TITLE
[Proposal] Allow setting optional per bucket ttls

### ISSUE THREAD

**Issue by DrRibosome** [minio/minio#4836]
I think it would be fairly useful if minio allowed per bucket time to live (ttl) to enable the use case where minio acts as a disk backed cache. Unless I missed it in the documentation, there doesnt seem to be an easy way to do this currently.

## Expected Behavior

Allow setting per bucket ttls (like s3)

## Context

Currently my company uses s3 for this, but we are investigating alternatives. Minio seems great, but lacks this feature.

## Your Environment

* aws

**Comment by harshavardhana** [comment]
This is being implemented here https://github.com/minio/minio/pull/4156 . Feel free to test and let us know.

**Comment by deekoder** [comment]
@DrRibosome please follow https://github.com/minio/minio/pull/4156. Closing this as duplicate.
