### ISSUE TITLE
Add lru expire objects over time

### ISSUE THREAD

**Issue by fkautz** [minio/minio#484]

**Comment by buffcode** [comment]
@fkautz Did you find a workaround/solution? I'm also looking for this feature as we are using minio as cache backend for GitLab.

**Comment by krishnasrinivas** [comment]
@buffcode you can use `mc` in cron to do this:
` mc rm --recursive --older-than=90 s3/jazz-songs/louis/`

**Comment by buffcode** [comment]
Thanks a lot!
