### ISSUE TITLE
Unknown "Object name invalid" error

### ISSUE THREAD

**Issue by alonewithyou** [minio/minio#4840]
When I'm trying to upload .dng files to a minio server on my computer with the following code
`func uploadFileToMinio(bucketName: String,
                        remoteName: String,
                        fileURL: URL){
        
        let accessKey = "xxxxxxxx"
        let secretKey = "xxxxxxxx"
        
        let credentialsProvider = AWSStaticCredentialsProvider(accessKey: accessKey, secretKey: secretKey)
        let configuration = AWSServiceConfiguration(region: .USEast1, endpoint: AWSEndpoint(region: .USEast1, service: .S3, url: URL(string:"http://xxx.xxx.xxx.xxx:9000")),credentialsProvider: credentialsProvider)
        
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        let uploadRequest = AWSS3TransferManagerUploadRequest()!
        uploadRequest.body = fileURL
        uploadRequest.key = remoteName
        uploadRequest.bucket = bucketName
        
        let transferManager = AWSS3TransferManager.default()
        transferManager.upload(uploadRequest)
        transferManager.upload(uploadRequest).continueWith { (task: AWSTask<AnyObject>) -> Any? in
            
            if let error = task.error {
                print("Upload failed with error: (\(error.localizedDescription))")
            }
            
            if task.result != nil {
                let url = AWSS3.default().configuration.endpoint.url
                let publicURL = url?.appendingPathComponent(uploadRequest.bucket!).appendingPathComponent(uploadRequest.key!)
                print("Uploaded to:\(String(describing: publicURL!))")
            }
            
            return nil
        }
    }`

The upload failed with 

> Upload failed with error: (The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 0.))

 while the error log from the server says 

> ERRO[0510] Unable to initiate new multipart upload id.   cause=Object name invalid: rawphoto#/1503389301.18356.dng source=[object-handlers.go:600:objectAPIHandlers.NewMultipartUploadHandler()] stack=object-api-input-checks.go:146:checkPutObjectArgs object-api-input-checks.go:108:checkNewMultipartArgs fs-v1-multipart.go:403:fsObjects.NewMultipartUpload <autogenerated>:381:(*fsObjects).NewMultipartUpload object-handlers.go:598:objectAPIHandlers.NewMultipartUploadHandler api-router.go:52:(objectAPIHandlers).NewMultipartUploadHandler-fm

However, when I tried to upload a jpg file with same code or upload the same file to Amazon S3 storage, both of them succeeded. Is there anything wrong with my usage of the API? Thanks in advance!

## Your Environment
Xcode 8, swift 3

**Comment by harshavardhana** [comment]
> uploadRequest.key = remoteName

Can you paste your object name here ? @alonewithyou

**Comment by alonewithyou** [comment]
@harshavardhana 
The remote name is 1503389301.18356.dng and bucket name is rawphoto, as are shown in the error log

> ERRO[0510] Unable to initiate new multipart upload id. cause=Object name invalid: rawphoto#/1503389301.18356.dng

**Comment by balamurugana** [comment]
@alonewithyou 
> ERRO[0510] Unable to initiate new multipart upload id. cause=Object name invalid: rawphoto#/1503389301.18356.dng 

I did below which worked fine.
```bash
$ mc mb local/rawphoto
Bucket created successfully `local/rawphoto`.

$ mc cp README.md local/rawphoto/1503389301.18356.dng
README.md:                      6.46 KB / 6.46 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 604.32 KB/s 0s

$ mc ls local/rawphoto
[2017-08-22 11:37:48 PDT] 6.5KiB 1503389301.18356.dng
```

I see one difference with the object name is `/1503389301.18356.dng` i.e. `/` is prefixed.  Could you trim `/` and try again?

**Comment by alonewithyou** [comment]
@balamurugana 
I've tried use some different filename before, when I do so, the server reports

> ERRO[0158] {"method":"POST","reqURI":"/rawphoto/1503489436.37158.dng?uploadId=c08e7a48-7634-41e4-81fd-6a8564c15b17","header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-cn"],"Authorization":["AWS4-HMAC-SHA256 Credential=shining/20170823/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-date, Signature=8dbc2a7d6901e479833539e14968ffd637f5ef4b640975f69c73569a4d67e338"],"Connection":["keep-alive"],"Content-Length":["313"],"Content-Type":["application/x-www-form-urlencoded"],"Host":["10.106.165.250"],"User-Agent":["aws-sdk-iOS/2.5.9 iOS/10.3.3 zh_CN transfer-manager"],"X-Amz-Date":["20170823T115730Z"]}}  cause=Signature does not match source=[auth-handler.go:122:checkRequestAuthType()]

(this log generated when I removed the '/' prefixed in the filename)
I'm sure I used correct access key and secret key, what could have caused this error?

**Comment by harshavardhana** [comment]
You used the right access and secret key did you apply the fix mentioned here https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-iOS-with-minio.md . I am assuming you are using iOS AWS SDK.

**Comment by alonewithyou** [comment]
@harshavardhana I didn't remove the line "transfer-encoding" at the beginning, and I just tried to remove it, "pod install" and rebuild, but the same error came to me again.

**Comment by harshavardhana** [comment]
Referencing a previous bug which was closed here and what we found to be AWS iOS SDK bug https://github.com/minio/minio/issues/4731 where AWS iOS SDK fails to follow AWS S3 spec. 

We have sent a previous PR for the `Transfer-Encoding` fix here https://github.com/aws/aws-sdk-ios/pull/638 and sadly its not accepted yet.

**Comment by alonewithyou** [comment]
@harshavardhana Oh this reference really helped. Luckily, files I need to upload are usually not larger than 15MB, adjusting AWSS3TransferManagerMinimumPartSize could work here for me. Thank you very much for helping, and hope this problem fixed soon!

**Comment by balamurugana** [comment]
@alonewithyou I think you could close this issue.

**Comment by harshavardhana** [comment]
@alonewithyou can you update your findings in our doc here https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-iOS-with-minio.md ? for large files.

It would be immensely helpful if you can provide your feedback.
