### ISSUE TITLE
Api and mc return 0 objects / output when downloading from the same dir at the sametime

### ISSUE THREAD

**Issue by rob-killingsworth** [minio/minio#4842]
## Expected Behavior
I would expect the api and mc to beable to do and ls at the same time as a download from a bucket and if they are unable to access not silently fail i.e. the api returning an empty list and mc to none 0.

## Current Behavior
While downloading a 100Mb file on one client if a second does a ls in the same bucket and path it will randomly give no results but does not give an error either

## Steps to Reproduce (for bugs)
1. start to down load a larger file from minio
2. in a loop run mc ls on the files containing path

## Context
I'm trying to use minio in a CI system which needs to check that all the needed files have been uploaded before it can start testing. The files follow a naming convention but i need to beable to use regex when looking for them so need the ls step before trying to download.

## Your Environment
Standalone docker minio container running under docker-ce on centos7

@vadmeste was able to quickly reproduce while I was talking to him in the slack channel

**Comment by vadmeste** [comment]
Concurrent listing showed this problem for me, like if we run the following code concurrently

```
package main

import (
	"fmt"

	"github.com/minio/minio-go"
)

func main() {
	s3Client, err := minio.New("localhost:9000", "minio", "minio123", false)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	countObjects := 0

	// List all objects from a bucket-name with a matching prefix.
	for object := range s3Client.ListObjects("testbucket", "", true, doneCh) {
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		countObjects++
	}

	if countObjects == 0 {
		fmt.Printf("WARN: no objects found\n")
	}

	return
}
```
