### ISSUE TITLE
do not compare credentials using bcrypt 

### ISSUE THREAD

**Issue by aead** [minio/minio#4844]
Currently bcrypt is used to generate a hash from the secret key. This hash is used to compare the secret key send by clients during login. The whole bcrypt code is not necessary and uses the wrong primitive for this use case. A simple constant-time-compare is sufficient.

   
## Expected Behavior
Use constant time compare of secret key

## Current Behavior
Compute bcrypt value of secret key and use the equal function of bcrypt to compare the hash values.

## Possible Solution
Use subtle.ConstantTimeCompare

**Comment by harshavardhana** [comment]
> The whole bcrypt code is not necessary and uses the wrong primitive for this use case.

Can you clarify why bcrypt is using a wrong primitive? isn't CompareHashPassword internally doing subtle.ConstantTimeCompare anyways? .  Only such that it does it on a Hash of the SecretKey?

**Comment by aead** [comment]
That's correct, but bcrypt itself is actually the "wrong" primitive for this use case.
Bcrypt is a PBKDF - it should be used (actually should not be used any more -> scrypt, Argon2) to derive a key from a password. The secret key is not really a password because it already contains a reasonable amount of entropy (secret key is long enough and generated by the system PRNG).

**Comment by balamurugana** [comment]
To extend secret key generation, admin can use free-formed text like `minio123` without generating using randomness.

**Comment by harshavardhana** [comment]
> To extend secret key generation, admin can use free-formed text like minio123 without generating using randomness.

Thanks @balamurugana - either we use bcrypt, scrypt, argon2 we wanted to have generic password hash style protection (we could also add salt here) and not depending on the randomness of the user passed string itself. 

 Not sure of the security implications but since secret key is indeed a password - i don't see how constant time compare would be sufficient. Secret key is a password used in two situations 

 - Web browser
 - Inter-node communication (RPC)

**Comment by aead** [comment]
But the current code does not protect the secret key using a PBKDF. This must be done in a different style. 
Just one simple example:
Webbrowser sends access key & secretkey (or bcrypt hash) as login. If connection is TLS everything is fine. If not it does not matter whether we send the secret key or the bcrypt hash - someone recording the credentials can always login...

If we want to support different types of secret keys (e.g. a "real" password) we must change the current code...

**Comment by harshavardhana** [comment]
> If we want to support different types of secret keys (e.g. a "real" password) we must change the current code...

Propose the change @aead which you think is more secure in this scenario. Which can be discussed further. PR #4845 referencing this fix is not warranted until we decide AFAICS we should close it.

**Comment by aead** [comment]
Okay, sure - any resources about the requirements?

**Comment by aead** [comment]
@harshavardhana Reopened PR - should fix it and fulfill the requirements, can discuss again if any concerns...

**Comment by harshavardhana** [comment]
> @harshavardhana Reopened PR - should fix it and fulfill the requirements, can discuss again if any concerns...

Are we not planning to secure support as password?  and instead rely on just constant time comparison?

**Comment by aead** [comment]
It does not improve security if we send the password as hash / hmac /bcrypt-value. If we would do this, somebody who can read the network traffic cannot compute the secret key from the hash - but it is not necessary to compute the secret key. If we send the hash / hmac / bcrypt-value during login, this hash / hamc / bcrypt-value IS the login and anyone who knows the hash can login.

Bcrypt, scrypt, Argon2 are only usefull (in minio's scenario) if the secret key is not stored on the disk - similar to a `/etc/shadow` approach.

What I'm trying to say - The current behavior would be:
 If the secret key is sent over an insecure network connection anybody who records the secret key can login.  
If the bcrypt(secret key) is sent over an insecure network connection anybody who records the bcrypt(secret key) can login.  
There is currently nothing like a challenge-response approach...
