### ISSUE TITLE
can not create share url

### ISSUE THREAD

**Issue by drahnr** [minio/minio#4847]
mc share download host/bucket

## Expected Behavior
if return 0, print a sharing url

## Current Behavior
no sharing url is created

## Steps to Reproduce (for bugs)
1. try to create a bucket with a pdf file
2. share that

## Your Environment
* minio/minio:edge
* setup nginx according to the howto guide

**Comment by harshavardhana** [comment]
You can't create a share URL for a bucket @drahnr - shared URL works only for an object if you wish to share all the objects under a bucket  - you should use `mc share -r`.  NOTE: This command will create URL which will expire in 7 days max. 

If you are looking for making your buckets public entirely - you should just set `mc policy download host/bucket`  instead, this would make your bucket publicly readable without any URL expiry. 

@drahnr for more FAQs and quick responses - feel free to join our https://slack.minio.io one of us is always around and we are more than happy to help.

**Comment by drahnr** [comment]
ok, I was just suspecting something is wrong since vaguely remember the return code being 0 - will double check

**Comment by harshavardhana** [comment]
> ok, I was just suspecting something is wrong since vaguely remember the return code being 0 - will double check

It is not doing anything because `mc share home/bucket` supports listing of objects at the top level.  If you don't have any objects at top level then it will still be successful since Listing succeeded just that it couldn't find any objects.

**Comment by drahnr** [comment]
I see, thanks for clarification.
