### ISSUE TITLE
Do minio server provide some restful api to operate data?

### ISSUE THREAD

**Issue by hegphegp** [minio/minio#4851]
I see the minio websites only uses the 'http:ip:port/webrpc' api. Do minio server provide some restful api to operate data? Our team don't want to use mino sdk to develop.

**Comment by harshavardhana** [comment]
> I see the minio websites only uses the 'http:ip:port/webrpc' api. Do minio server provide some restful api to operate data? Our team don't want to use mino sdk to develop.

Minio implements and supports http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html - you can use either Minio SDKs or AWS S3 SDKs to talk to Minio or write your own. 

Minio browser UI uses a different set of API based on JSON-RPC and bearer token auth - it is not a public API and can change at will. It shouldn't be used to build applications. 

Feel free to join our https://slack.minio.io for more real time help on these FAQs.

**Comment by harshavardhana** [comment]
Please close the issue if you have no further questions @hegphegp
