### ISSUE TITLE
Complete CreateFile as soon as write quorum is obtained

### ISSUE THREAD

**Issue by fwessels** [minio/minio#4854]
In CreateFile (for erasure coding), when writing out the parts to the individual disks or nodes, we can optimize the behaviour to return successful completion as soon as the write quorum is in. 

That is, once we have received a number of successul responses that is equal to the write quorum, we can complete the function and return success. We should let the other operations complete normally but their responses do no longer matter (since we already got write quorum).

This will protect us against the slowest operation which makes the overall system performance vulnerable to (bad) outliers.

**Comment by fwessels** [comment]
After giving it more thought, this issue has a bit more impact. Exiting out early would mean releasing the write lock before all write operations are necessarily completed.

Thus a subsequent (blocking) read lock could be released before all underlying write operations are finished. Since we do not know which write operations may have been slow/incomplete, we run the risk of reading potentially incomplete parts resulting in errors.

Ideally the write lock would not be released until all underlying write operations are complete, but this is not so easy to implement, and has quite a bit more implications.

Maybe there is another way of tackling this.

**Comment by harshavardhana** [comment]
We should close this @fwessels ?

**Comment by fwessels** [comment]
Yes, we can close it

**Comment by harshavardhana** [comment]
> Yes, we can close it

Thanks @fwessels
