### ISSUE TITLE
[enhancement] erasure/posix: Explore ways if possible to offload json un-marshalling to backend. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4860]
This issue is not a general bug but an enhancement affecting our master branch using free from submission here.

Currently we have `posix.go: ReadAll()` API - primary purpose of the API is to read a file in its entirety and returned back to the caller.  We used this call extensively in reading `xl.json`.   Once we get the response from the remote servers JSON unmarshalling is attempted. 

This has some problems 

- JSON unmarshalling is taxing especially doing it on the receiving end, slowly our ability to serve data. 
- JSON is not strictly typed, we are bound with reflection overhead when parsing large JSON lists can happen with large files (Currently we avoid this by using gjson and lazy unmarshalling. This has problems since gjson will not validate corrupted JSON properly).

Basic requirements:
- Avoid spilling over `xl.json` details to the backend.
- Generalized for any metadata.

**Comment by fwessels** [comment]
We could also looking into accelerating JSON unmarshalling by writing some custom code (specific to the exact format that we use). 

Do we know what the total performance (in MB/sec) is that we can parse?

**Comment by fwessels** [comment]
Quick test (in gjson):

```
func BenchmarkJSON(b *testing.B) {
	b.SetBytes(int64(len(complicatedJSON)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var s ComplicatedType
		if err := Unmarshal([]byte(complicatedJSON), &s); err != nil {
			b.Fatal(err)
		}
	}
}
````

reports

```
$ go test -v -run=SKIP -bench=.
BenchmarkJSON-8   	  100000	     13230 ns/op	  78.45 MB/s
PASS
ok  	github.com/tidwall/gjson	1.487s
```

I guess we should be able to get at the very minimal 10x the performance.

**Comment by harshavardhana** [comment]
> We could also looking into accelerating JSON unmarshalling by writing some custom code (specific to the exact format that we use).

This is also possible if we can avoid reflection.

**Comment by fwessels** [comment]
With recent performance measurements that we did, it did not show up to be a bottleneck.

I would suggest postponing the issue for now and revisit it later if it becomes performance critical again (knowing that we can improve significantly here).

**Comment by harshavardhana** [comment]
Yes we can do that agreed. Will close this for now as a non issue.
