### ISSUE TITLE
Write a template UI to deploy a Minio Azure with parameters specified by users

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4862]
Write a createUiDefinition.json which is a UI (or number of steps) to configure Minio deployment in Azure

**Comment by vadmeste** [comment]
Done

**Comment by vadmeste** [comment]
We can close this as completed.

**Comment by harshavardhana** [comment]
Why is this re-opened? @vadmeste

**Comment by vadmeste** [comment]
I wanted to check with @krisis first.
