### ISSUE TITLE
Add support of LetsEncrypt in Minio Azure

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4863]
We need first decide if we should use Letsencrypt, for example, does Letsencrypt support all recent browsers, then implement it.

**Comment by vadmeste** [comment]
One important point that we need to be aware, is the automatic renewal here. Minio doesn't support renewal of certificates only if we restart it.

**Comment by harshavardhana** [comment]
We can convert our `concert` tool into a library here and then hot replace the TLS.  Caddy does this without downtime we should be able to leverage such a thing ourselves.

**Comment by vadmeste** [comment]
> We can convert our concert tool into a library here and then hot replace the TLS. Caddy does this without downtime we should be able to leverage such a thing ourselves.

This won't probably work since we have many Minio instances, I guess when one instance will have to renew the certificate, other certificates in other instances will be invalidated, or not ?

**Comment by harshavardhana** [comment]
They will be invalidated as well this renewal should happen in a distributed manner as well. But it is highly unlikely that we would need to support such a situation.

It is easier to support FS and Standalone Erasure for now.

**Comment by krisis** [comment]
> They will be invalidated as well this renewal should happen in a distributed manner as well. But it is highly unlikely that we would need to support such a situation.

> It is easier to support FS and Standalone Erasure for now.

@harshavardhan how would we support minio gateway?

**Comment by harshavardhana** [comment]
> @harshavardhan how would we support minio gateway

One problem with lets encrypt is is that they don't support wild cards yet.  But apart from that Gateway and FS use case won't be different i believe.

**Comment by vadmeste** [comment]
Closing this we are moving issues to a new location
