### ISSUE TITLE
The Maxlength of boejct key?

### ISSUE THREAD

**Issue by billschen** [minio/minio#4875]
Is Some one can tell me the max length of object key?
I Put a file which is the filename is very long but fail like:

![ltc41](https://user-images.githubusercontent.com/19528399/29906203-fcb6c178-8e45-11e7-8a44-de5afe052357.png)

**Comment by harshavardhana** [comment]
Max length of object key is UTF-8 characters of 1024 bytes long - http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html. 
>When you create an object, you specify the key name, which uniquely identifies the object in the bucket. For example, in the Amazon S3 console (see AWS Management Console), when you highlight a bucket, a list of objects in your bucket appears. These names are the object keys. The name for a key is a sequence of Unicode characters whose UTF-8 encoding is at most 1024 bytes long.

Please visit us at https://slack.minio.io for quick answers @billschen

**Comment by billschen** [comment]
@harshavardhana :+1:  thank you! I will try use slack.
