### ISSUE TITLE
Calling minio via IP Vs Hostname

### ISSUE THREAD

**Issue by N1v0k** [minio/minio#4880]
I'm using the Java AWS SDK.
Everything is working fine if I provide the minio host via ip+port.

## Expected Behavior
When calling
`PutObjectRequest putObjectRequest = new PutObjectRequest(dstBucket,dstKey,localFile);`
The file is uploaded to http://miniohost:1234/dstBucket

## Current Behavior
It tries to upload the file to:
http://dstBucket.miniohost:1234

If I provide the ip it uploads to:
http://ip:1234/dstBucket

## Your Environment
Minio Docker - Latest

**Comment by N1v0k** [comment]
I didn't see this:
https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-java-with-minio.md

This solved the issue of course:

```
        final S3ClientOptions clientOptions = S3ClientOptions.builder().setPathStyleAccess(true).build();
        s3Client.setS3ClientOptions(clientOptions);
```

This way you don't need any subdomains . (which was the keyword I was searching for)

Many thanks for this great project.

**Comment by harshavardhana** [comment]
Feel free to close this issue @Gmentsik
