### ISSUE TITLE
FS: return error if part size differ

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4881]
For multipart, currently we do background append. This is inefficient, better approach is to use `pwrite()` and write the part to the right offset. When the client sends complete multipart upload call we should have the full file ready to be renamed to the main namespace.

There are limitations with this approach, i.e clients can't send variable part sizes. Hence the change can break clients if they send variable part sizes. Before we commit to this way of doing things we can test waters by sending error if client send variable sized parts and see if users report any error (just like how we send empty response for listparts and listincompleteuploads now)

If we don't hear of any critical client breakages we can go ahead and implement pwrite() style multipart operation.

**Comment by vadmeste** [comment]
Linux (and probably Windows) supports adding a data in the middle of a file in a non-costly manner, does it help to resolve variable part sizes problem?

> If we don't hear of any critical client breakages we can go ahead and implement pwrite() style multipart operation.

Though this is better to have a simpler code.

**Comment by krishnasrinivas** [comment]
Had a chat with @vadmeste about using FALLOC_FL_INSERT_RANGE but it is not flexible as it expects offsets and length to be at 4K boundary

**Comment by harshavardhana** [comment]
are we still exploring this @krishnasrinivas @vadmeste ? - if not should we close this bug?

**Comment by krishnasrinivas** [comment]
> are we still exploring this @krishnasrinivas @vadmeste

yes @harshavardhana this bug needs to be worked on

**Comment by sgamzn** [comment]
@krishnasrinivas @harshavardhana this change definitely breaks compatibility with clients. There is a use case when products upload files increasing part size. There are all sorts of workflows which could be facilitated by parts being different size. I think there has to be a switch or configuration option to disable this error. In my organization, we had to fallback to pre-October client to enable our workflows

**Comment by krishnasrinivas** [comment]
@sgamzn thanks for your inputs. We will get back on this.

**Comment by harshavardhana** [comment]
> @krishnasrinivas @harshavardhana this change definitely breaks compatibility with clients. There is a use case when products upload files increasing part size. There are all sorts of workflows which could be facilitated by parts being different size. I think there has to be a switch or configuration option to disable this error. In my organization, we had to fallback to pre-October client to enable our workflows

@sgamzn what is the exact workflow here? and what is the reason behind not having a consistent part size?

**Comment by sgamzn** [comment]
@harshavardhana in our organization there are multiple reasons:

1. if upload happens in parallel with file processing, it is beneficial to gradually increase fragment size - e.g.: starting with small chunks to be more responsive, and continue with larger ones to be able to upload up to maximum size.

2. some workflows involve writing first fragment of file after all other fragments are written (e.g.: header). In this case, header fragment is typically smaller than others, as we don't want to hold on to a large file when it's not necessary

**Comment by krishnasrinivas** [comment]
@sgamzn can't your application first write to local FS first to compose the file first and in the end upload it to S3? What would be the downside of this approach for your application?

**Comment by sgamzn** [comment]
@krishnasrinivas no, our app is designed to write files larger than drive space available locally.

Please consider following: we design our application to work with Amazon S3. Third party S3 providers will be supported as long as they are compatible. So, as you would imagine, it does not make sense for us to be implementing workarounds, even if we theoretically could.

**Comment by sniegu** [comment]
@krishnasrinivas @harshavardhana I have just hit this issue. Currently I need to fallback to pre-October release of Minio. I understand and accept the need of optimizations that this change would introduce, but it stands in contradiction with Minio's claim that it is "Amazon S3 compatible object storage server", since nor original S3 does impose such a restriction, neither other implementation do (like RGW - Rados Gateway above CEPH).

A configuration to switch to enable or disable this behaviour (as @sgamzn have already suggested) would be definitely desirable.

**Comment by krishnasrinivas** [comment]
> A configuration to switch to enable or disable this behaviour (as @sgamzn have already suggested) would be definitely desirable.

We tend to avoid adding config options, but will check with the team if it can be an exception in this case.

**Comment by krishnasrinivas** [comment]
@sgamzn @sniegu isn't erasure backend an option for you?

`minio server /export1 /export2 /export3 /export4`

It supports differing parts sizes.

**Comment by sgamzn** [comment]
@krishnasrinivas erasure as in https://docs.minio.io/docs/minio-erasure-code-quickstart-guide ? I am not certain how it would possibly affect the problem. Our workflow is: file being generated and uploaded. Part size starts small, then gradually increases. I am not sure how you propose to use erasure here

**Comment by harshavardhana** [comment]
> @krishnasrinivas erasure as in https://docs.minio.io/docs/minio-erasure-code-quickstart-guide ? I am not certain how it would possibly affect the problem. Our workflow is: file being generated and uploaded. Part size starts small, then gradually increases. I am not sure how you propose to use erasure here

Minio provides two different primary modes of operation 

- FS mode where you saw the error
- Erasure coded (distributed or standalone multiple disks)  where you won't see the error

We wish to keep the FS mode as it is and simple. We purposefully reduced the scope of FS mode in this scenario to reduce code complexity and higher performance. We do not support many other S3 APIs as well simply because they are seldom used and there are easier alternatives for such APIs.  So our decision here is purely practical and in this scenario tradeoff is valid.

For use cases such as yours can use erasure coded mode which doesn't have such restrictions.

**Comment by sniegu** [comment]
I can confirm that changing mode to erasure coded storage solved my problem. Thanks!

Up until now I have used Minio only in development and testing scenarios, with a single Minio instance - I was just not aware, that the other mode might be different in such a way.

I agree that introduction of configuration switches should be avoided, especially with software such easy to run as Minio. Maybe just a single configuration switch named like "strict" would suffice - it might switch between full compatibility with S3 and the other mode using some not S3 compatible optimizations.

Still I think that documentation regarding XMinioPartsSizeUnequal should be improved - I had seen string XMinioPartsSizeUnequal in Minio log, then tried to google it and found literally a single hit: a file on github where it is defined, which was obviously not very helpful. Then I have greped around only to find a comment in cmd/fs-v1-multipart.go regaring optimizations using pwrite(), however it said nothing about FS vs. Erasure coded differences.

**Comment by sgamzn** [comment]
Is there a way to enter erasure mode with just a single export?

**Comment by krishnasrinivas** [comment]
@sniegu no
you can do `minio server /single-export/export{1...4}` but I guess that is not what you are looking for.

**Comment by sgamzn** [comment]
@krishnasrinivas perhaps you want this to be configurable... I get it that erasure backend is an option, but you have:

a) incompatibility with Amazon S3. Whichever way you slice it, you made your product incompatible. I get it that you had reasons, but reasons are irrelevant if product falls short of specs. The right way to approach such experiments is to enable it in non-default mode with a note that some applications might be broken by enabling that mode.

b) two unrelated features are coupled. It's absolutely unintuitive, why would one need to have a very specialized backend enabled when all they want is compatibility. How will even get this documented? I don't think  this was well thought through

**Comment by dwsteele** [comment]
This behavior causes problems for pgBackRest: https://github.com/pgbackrest/pgbackrest/issues/556.  pgBackRest is currently running on a number of S3 gateways (ScalityS3, IBM Cloud, Ceph, Swift, etc.) with no problem but fails on minio because of this limitation.  

The workaround does not seem to be very intuitive.  It seems like this should be an option that defaults to `off` and can be enabled by those who want the extra performance.

**Comment by harshavardhana** [comment]
FS mode is simplest with no multiple codepaths with different behaviours. We would like to keep less knobs or avoid them if possible. In this definitely no knobs. For most applications it has not been a problem and there is no reason to provide a non performant version in the FS codebase.

The workaround is simply use erasure coded backend which still supports this ..

**Comment by sgamzn** [comment]
I think this is a mistake. This product is a generic tool, so performance here is secondary to compatibility. When you get Ferrari, you want to squeeze every possible drop of performance out of it and that's OK if it is not comfortable to drive; but this is rather Camry, where you want all minutiae to work - windshield wipers, brake signals, and it's unfathomable to be swapping all wheels while on the road trip. I agree that knobs should be avoided, but it's compatibility that should be default, not performance

**Comment by harshavardhana** [comment]
> I think this is a mistake. This product is a generic tool, so performance here is secondary to compatibility. When you get Ferrari, you want to squeeze every possible drop of performance out of it and that's OK if it is not comfortable to drive; but this is rather Camry, where you want all minutiae to work - windshield wipers, brake signals, and it's unfathomable to be swapping all wheels while on the road trip. I agree that knobs should be avoided, but it's compatibility that should be default, not performance

For now it is here to stay and the workaround is to use erasure coding if you have such an application. The performance was not the real reason perhaps it was miscommunicated before in-fact it was the simplicity of the codebase which is of utmost importance for our maintenance. The trade-off was we lose compatibility which is okay for stability.
