### ISSUE TITLE
ContentMD5 header, when set with putting an object, is not being returned when getting an object

### ISSUE THREAD

**Issue by damianh** [minio/minio#4889]
Using the AWSSDK for .NET I am specifying the ContentMD5 of an object being PUT. When getting the objects, the ContentMD5 on the response headers is missing.

## Expected Behavior

`ContentMD5` on the response should be the same value as define when putting the object.

## Current Behavior

`ContentMD5` is on the response should be specified.

## Steps to Reproduce (for bugs)

    using System;
    using System.IO;
    using System.Text;
    using System.Threading.Tasks;
    using Amazon;
    using Amazon.S3;
    using Shouldly;
    using Xunit;

    public class MinioMD5
    {
        [Fact]
        public async Task Get_MD5()
        {
            var accessKey = "accesskey";
            var secretKey = "secretkey";
            var bucketName = $"mino-{Guid.NewGuid()}";
            var s3Client = new AmazonS3Client(accessKey, secretKey,
                new AmazonS3Config
                {
                    RegionEndpoint = RegionEndpoint.USEast1,
                    ServiceURL = "http://localhost:9000",
                    ForcePathStyle = true
                });
            await s3Client.PutBucketAsync(bucketName);

            var putObjectRequest = new Amazon.S3.Model.PutObjectRequest
            {
                Key = "key",
                BucketName = bucketName,
                ContentType = "text/plain",
                InputStream = new MemoryStream(Encoding.UTF8.GetBytes("foo")),
                MD5Digest = "rL0Y20zC+Fzt72VPzMSk2A=="
            };

            await s3Client.PutObjectAsync(putObjectRequest);

            var getObjectResponse = await s3Client.GetObjectAsync(bucketName, "key");

            // This fails
            getObjectResponse.Headers.ContentMD5.ShouldBe(putObjectRequest.MD5Digest);
        }
    }

## Your Environment

* Version used (`minio version`): 
```
Version: 2017-08-05T00:00:53Z
Release-Tag: RELEASE.2017-08-05T00-00-53Z
Commit-ID: aeafe668d8b6d25caac671d59e2b0f0473ce35d0
```
* Environment name and version (e.g. nginx 1.9.1):  AWSSDK .NET 3.3.10.2
* Server type and version:
* Operating System and version (`uname -a`): Windows 10,
* Link to your project:

**Comment by damianh** [comment]
PutObject request:

![image](https://user-images.githubusercontent.com/57436/30068507-4d582fce-925e-11e7-9dfb-8888aa51ceeb.png)

GetObject response has no Content-MD5 response header:

![image](https://user-images.githubusercontent.com/57436/30068555-6f3970ee-925e-11e7-97e1-e25fb6ef5733.png)

**Comment by harshavardhana** [comment]
Etag is returned for Content-MD5 .

**Comment by poornas** [comment]
@damianh, do you have further questions? As @harshavardhana mentioned, we return Etag but not Content-MD5 header

**Comment by damianh** [comment]
Thanks for fast response.

I am away from computer until tomorrow. Then I will verify that S3 behaves this way (I thought it set the ContentMD5 header, but will check).

From the screenshots above, one can see that the Etag value is different to the Content-MD5. Should they be the same? Am I missing something here? Encoding?

Also, if the object was multipart uploaded, is the Etag and Content-MD5 still going be the same? I though they would be different.. I'll check the S3 docs.

**Comment by harshavardhana** [comment]
> From the screenshots above, one can see that the Etag value is different to the Content-MD5. Should they be the same? Am I missing something here? Encoding?

ETag is hex encoded - Content-Md5 is sent as base64.  ETag is not always md5sum of the object uploaded - For more information read S3 docs - http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

**Comment by damianh** [comment]
It appears that S3 doesn't respond with an object's Content-MD5 thus not enabling client side integrity checking.

I was led to believe that due to the presence of such a property in the response type in the SDK. :| 

Sorry for wasting your time.

**Comment by damianh** [comment]
This is deceptive:

![image](https://user-images.githubusercontent.com/57436/30108260-ee4268fc-9301-11e7-8c4c-bb1df53d68f9.png)
