### ISSUE TITLE
[gateway] handle backend service timeout properly

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4896]
Gateway would need to translate timeout or socket timeout errors from backend service as `RequestTimeout` S3 error.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
@balamurugana  do we still have to address this issue?

**Comment by balamurugana** [comment]
@deekoder yes

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
