### ISSUE TITLE
Fail to put zero bytes object with go sdk

### ISSUE THREAD

**Issue by trusch** [minio/minio#4899]
## Expected Behavior
go minio sdk put zero-byte file should succeed

## Current Behavior

go minio sdk put zero-byte file doesnt succeed:
Error: The XML you provided was not well-formed or did not validate against our published schema.

## Possible Solution
No idea, I think its a bug in the go-sdk because there are closes issues which are related to this.

## Steps to Reproduce (for bugs)
upload zero-byte file with go sdk

## Your Environment
* Version used (`minio version`):
latest docker image
* Operating System and version (`uname -a`):
Linux carbon 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
* Link to your project:

**Comment by poornas** [comment]
@trusch, could you provide a snippet of the code that fails, go version and version of go sdk used?

**Comment by trusch** [comment]
@poornas I'll put something together this evening.

**Comment by trusch** [comment]
go version: `go version go1.8.3 linux/amd64` (yes, I need to update ;))
minio-go version: `ab4751ef607ceca97e30a3e8c0f890e2c19c1ff0` (one commit after v3.0.2)

```go
package main

import (
	"io"
	"log"
	"os/exec"

	"github.com/minio/minio-go"
)

func main() {
	var (
		accessKey = "YV4ZWPZ3HEUN4P21GUH0"
		secretKey = "TU8KRW8dqstLv8t6tQHbAoOPqhPZWpyGzue46IK"
	)

	// start minio
	args := []string{
		"run",
		"--name", "minio",
		"-p", "9000:9000",
		"-d",
		"-e", "MINIO_ACCESS_KEY=" + accessKey,
		"-e", "MINIO_SECRET_KEY=" + secretKey,
		"--rm",
		"minio/minio:RELEASE.2017-08-05T00-00-53Z",
		"server", "/data",
	}
	exec.Command("docker", args...).Run()
	exec.Command("bash", "-c", "while ! curl localhost:9000; do echo sleep; sleep 0.2; done").Run()
	defer exec.Command("docker", "kill", "minio").Run()

	// create client
	s3Client, err := minio.New("localhost:9000", accessKey, secretKey, false)
	if err != nil {
		log.Print(err)
		return
	}

	// prepare bucket
	err = s3Client.MakeBucket("my-bucketname", "")
	if err != nil {
		log.Print(err)
		return
	}

	// This is my usecase:
	// I have to fullfill an interface which requires me to return a WriteCloser.
	// Therefore I create a pipe to pass the reader end to the PutObject() function
	// and use the writer to write stuff to the object.
	r, w := io.Pipe()
	done := make(chan struct{})
	go func() {
		defer close(done)
		_, err := s3Client.PutObject("my-bucketname", "my-objectname", r, "application/octet-stream")
		if err != nil {
			log.Print("This is the error: ", err)
			return
		}
	}()

	// if I would do a w.Write([]byte("foobar")) here, everything would be fine
	// but no, I'm closing immediatly because the file I want to write (for example) has exactly zero bytes.
	w.Close()
	<-done
}
```

**Comment by trusch** [comment]
I know I could do some special handling for this case and simply don't upload empty files, but I expected it to work, so I leave this issue here!

**Comment by poornas** [comment]
@trusch, you could use PutObjectWithSize call instead of PutObject. For optimal memory usage, it is best that size be provided when it is known. In the event that size is unknown,you could leave it to the sdk to figure it out.
`		_, err := s3Client.PutObjectWithSize("my-bucketname", "my-objectname", r, 0, nil, nil)
`

**Comment by poornas** [comment]
@trusch, did the suggestion above resolve your issue? If so, can we close this?

**Comment by krishnasrinivas** [comment]
@poornas we can fix this as it is a bug in the PutObject API implementation even though you can use the workaround of using PutObjectWithSize.

**Comment by poornas** [comment]
Correct @krishnasrinivas , I have a fix in the PutObject refactor PR.

**Comment by trusch** [comment]
@poornas yes it helped,  but it's very contra-intuitive to use PutObjectWithSize when I don't know the size ;) in my original use case I'm fine with simply not writing objects with size zero. from my point of view you could add a testcase for this in your refactor PR and close this issue.

**Comment by poornas** [comment]
sounds good @trusch.

**Comment by ebozduman** [comment]
Closing this since we have the tests @trusch is asking for already as part of our functional tests.
