### ISSUE TITLE
how to cancel the shared URL

### ISSUE THREAD

**Issue by kybom** [minio/minio#4902]
## Expected Behavior

In browser,I  share a object.Now I wan to cancel the  shared link,keep the object private.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
There is no way to do that in AWS S3 Specification @kybom
