### ISSUE TITLE
Healing takes long / requires restart

### ISSUE THREAD

**Issue by matti** [minio/minio#4909]
Minio is running on 4 servers in google cloud platform: 3 of the servers are standard and 1 is ephemeral.

Once the ephemeral node gets deleted and recreated, the mc admin health says that all nodes are healthy, but larger file uploads keep failing with 502.

When I manually restarted all servers, the cluster eventually healed itself:
https://gist.github.com/matti/39f06d2aecb53a8d3912135115f3123c

Running with kontena.io + docker + coreos

**Comment by fwessels** [comment]
@matti could you elaborate on what you mean by "larger file uploads" keep failing. Does this mean that small files are uploaded fine (and thus maybe a PUT vs MULTIPART PUT issue)? Do GETs work normally after the ephemeral nodes has been deleted and recreated?

**Comment by matti** [comment]
All file uploads fail, small ones looked like they would complete

**Comment by fwessels** [comment]
And what about GETs, where they working?

**Comment by deekoder** [comment]
Ping @matti I will go ahead and close this issue. Please reactivate and reopen if you want to continue the discussion.
