### ISSUE TITLE
s3cmd put with --acl-public parameter returns an error Public URL 

### ISSUE THREAD

**Issue by mohaijiang** [minio/minio#4912]
s3cmd put with --acl-public returns an error Public URL 

## Expected Behavior

When  upload file with s3cmd put --acl-public to the minio server ,the returned URL such as `http://127.0.0.1:9000/mohaijiang/test/aa.txt`. And the URL should be able to be downloaded.

## Current Behavior

The URL `http://127.0.0.1:9000/minio/mohaijiang/test/aa.txt` can be downloaded,but `http://127.0.0.1:9000/mohaijiang/test/aa.txt` can't.

## Steps to Reproduce (for bugs)

1.  create a test file
```
$ touch aa.txt
```
2. upload to minio
```
$ s3cmd put --acl-public ./aa.txt s3://mohaijiang/test/aa.txt
upload: './aa.txt' -> 's3://mohaijiang/test/aa.txt'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  done
Public URL of the object is: http://127.0.0.1:9000/mohaijiang/test/aa.txt
```
3. try to download with the URL which be returned in Step 2
```
$ wget http://127.0.0.1:9000/mohaijiang/test/aa.txt
--2017-09-13 15:06:29--  http://127.0.0.1:9000/mohaijiang/test/aa.txt
Connecting to 127.0.0.1:9000... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-09-13 15:06:29 ERROR 403: Forbidden.
```
4. try to add http context path 
```
$ wget http://127.0.0.1:9000/minio/mohaijiang/test/aa.txt
--2017-09-13 15:31:29--  http://127.0.0.1:9000/minio/mohaijiang/test/aa.txt
Connecting to 127.0.0.1:9000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2021 (2.0K) [text/html]
Saving to: ‘aa.txt.1’

aa.txt.1            100%[===================>]   1.97K  --.-KB/s    in 0s      

2017-09-13 15:31:29 (85.6 MB/s) - ‘aa.txt.1’ saved [2021/2021]

```

## Context

Can Minio remove the http context path or retrun current URL with s3cmd ?

## Your Environment

* Version used (`minio version`):
```
Version: 2017-08-05T00:00:53Z
Release-Tag: RELEASE.2017-08-05T00-00-53Z
Commit-ID: aeafe668d8b6d25caac671d59e2b0f0473ce35d0
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
`Ubuntu 17.04`
* Operating System and version (`uname -a`):
```
Linux mohaijiang-ThinkPad-L450 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your project:

**Comment by harshavardhana** [comment]
@mohaijiang minio doesn't support ACLs we only support Bucket policies https://docs.minio.io/docs/minio-server-limits-per-tenant  and we have no plans on supporting ACLs yet.

**Comment by mohaijiang** [comment]
@harshavardhana  thanks.
