### ISSUE TITLE
Azure Limitations should be in the same guide, not separate.

### ISSUE THREAD

**Issue by belvid** [minio/minio#4930]
## Expected Behavior

- Keep limitations of Azure gateway with its doc
- Update limitations like 100MB per upload part

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by krisis** [comment]
Fixed by https://github.com/minio/minio/pull/5072
