### ISSUE TITLE
Paper to cite?

### ISSUE THREAD

**Issue by danyaljj** [minio/minio#4932]
Want to cite your system in an academic paper. Do you have a paper on minio that we can cite?

**Comment by aead** [comment]
Depends on what you want/need to cite. We have documentation at [/docs](https://github.com/minio/minio/tree/master/docs). As far as I know there a no academic papers... Can you provide further information about what your paper is about?

**Comment by danyaljj** [comment]
I use minio to store model files of a machine learning system paper. I feel like if you have a white paper on minio and let people in academia cite you, it could be a good source of advertisment.

**Comment by aead** [comment]
cc @harshavardhana @fwessels

**Comment by aead** [comment]
@danyaljj We don't have any academic white papers about minio. Feel free to use any type of documentation or talks we provide if it fulfills your academic requirements.
