### ISSUE TITLE
[build] make test does not clean up server processes reliably

### ISSUE THREAD

**Issue by donatello** [minio/minio#4950]
## Expected Behavior

No minio server processes launched by make test should remain running after it completes.

## Current Behavior

Sometimes, the minio server processes do not exit.

## Possible Solution

Not sure of the reason.

## Steps to Reproduce (for bugs)

1. Run make test a few times and check if minio server is still running.

## Context

make test fails if run consecutively with errors about ports being in use.

**Comment by harshavardhana** [comment]
Along with this i also see that some times `mc-test` buckets are not cleaned up.

**Comment by balamurugana** [comment]
Reopen with steps to reproduce the issue
