### ISSUE TITLE
Ability to completely remove the front end

### ISSUE THREAD

**Issue by dominicporteous** [minio/minio#4955]
## Expected Behavior

Ability to deploy on docker, exposing only the back-end (for use with command-line or language specific clients.)

## Current Behavior

As is

## Steps to Reproduce (for bugs)
N/a

## Context

Ability to deploy without front end UI, to fit in with existing S3 like workflow.

## Your Environment
N/a

**Comment by nitisht** [comment]
@dominicporteous you can use the `MINIO_BROWSER` flag to deny browser access. For Docker you can use

```sh
sudo docker run -p 9000:9000 -e "MINIO_BROWSER=off" <minio_image> server <data_dir>
```

**Comment by dominicporteous** [comment]
@nitisht Thanks! Is there a place where all of these options are listed? 

Thanks again!
