### ISSUE TITLE
Unable to heal objects

### ISSUE THREAD

**Issue by curantes** [minio/minio#4956]
Unable to heal objects in distributed minio. even if the cluster have always ben running except for the upgrade i did before the heal command to latest version.

I am not able to send the sosreport since its time consuming to clear sensitive data. But I am willing to send you reports of specific parts if you require it. Just let me know what you need.

## Expected Behavior
Running `mc admin heal` should heal objects.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
ls -l for the different minio instances

minio01:
```
drwxr-xr-x 2 minio minio 35 24 apr 09.07 3546c1e2-b191-4b61-bdde-2411225c0625.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.26 83b17557-edea-4662-9d79-f54faeb4259c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 b85be709-aa98-4e73-9b19-4a04b4861a1c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 c8885a40-d5df-4f90-9872-0af7c46026c0.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.58 d8ab0052-3057-4baa-aa9a-e082271a2cc8.jpg
```

minio02: 
```
drwxr-xr-x 2 minio minio 35 24 apr 13.26 00ad64d8-b767-4f6e-b7f6-5282d0e9f058.png
drwxr-xr-x 2 minio minio 35 24 apr 13.28 05dce802-9eee-446b-8c1a-39fe80bf2e92.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 2086f4a1-e06e-40c0-9d95-9046cb04a80e.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 2c88345a-1218-49ea-8be9-92e572fab683.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.26 3234d90e-be31-44f8-9ba1-cb3a3a97d51e.zip
drwxr-xr-x 2 minio minio 35 24 apr 09.07 3546c1e2-b191-4b61-bdde-2411225c0625.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.28 361594f7-d42d-4e6e-92a8-957799697c36.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.27 41ef03e5-e7f1-48fd-aa2f-a86f232fc9ca.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 455a68bf-10b1-4092-b3f6-170fdac06d18.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 48f2b7c6-3325-41ad-959b-1f45881bbd8e.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.26 550e4bb7-b0f0-4aac-862b-679db72058ca.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.26 5587c75b-b0a6-4479-b810-a705c1015c45.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 58a3afd6-8f6c-4460-837b-0b182b6e6435.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 5de5ca3e-443f-4305-8010-95a1cf6994ee.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.26 7586fba1-142d-4833-b3b6-f8a30f94c23b.jpg
drwxr-xr-x 2 minio minio 35 22 sep 07.25 83b17557-edea-4662-9d79-f54faeb4259c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 881df61c-933b-42ca-9a7a-6701665b735a.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 88d450ef-50e7-4d58-bbbc-978631ac08dc.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.27 925a3bdc-5c93-4e27-955a-038a22f57185.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 9b2c5946-ccfb-4763-af36-1ccf2683baff.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 a05d07d6-3e35-4771-90f0-84801e4a9654.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.26 a905a220-07c1-4979-9452-1462c590b96a.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.26 b6cc1d50-d215-477c-b7b6-0a63c3358fd1.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 b85be709-aa98-4e73-9b19-4a04b4861a1c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 c241949c-8b76-448e-826d-75453d62e6fe.pdf
drwxr-xr-x 2 minio minio 35 22 sep 07.25 c8885a40-d5df-4f90-9872-0af7c46026c0.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.58 d8ab0052-3057-4baa-aa9a-e082271a2cc8.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 dde3c849-7891-48a5-8c60-e547c48b8201.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.26 e1ea8118-f8ee-495f-8d8a-435139907993.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.26 e2c8ded6-524e-485f-997c-33d19e1d762b.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 e452af3e-9a91-4fce-b028-fba91144a521.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.28 f619c4d9-b185-4e79-a88d-f2957aec8a30.jpg
drwxr-xr-x 2 minio minio 35 24 apr 13.26 ff3921d4-6531-4dd6-ac0e-fd00296ca690.pdf
```

minio03:
```
drwxr-xr-x 2 minio minio 35 24 apr 09.07 3546c1e2-b191-4b61-bdde-2411225c0625.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.26 83b17557-edea-4662-9d79-f54faeb4259c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 b85be709-aa98-4e73-9b19-4a04b4861a1c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 c8885a40-d5df-4f90-9872-0af7c46026c0.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.58 d8ab0052-3057-4baa-aa9a-e082271a2cc8.jpg
```

minio04:
```
drwxr-xr-x 2 minio minio 35 24 apr 09.07 3546c1e2-b191-4b61-bdde-2411225c0625.pdf
drwxr-xr-x 2 minio minio 35 24 apr 13.26 83b17557-edea-4662-9d79-f54faeb4259c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 b85be709-aa98-4e73-9b19-4a04b4861a1c.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.57 c8885a40-d5df-4f90-9872-0af7c46026c0.jpg
drwxr-xr-x 2 minio minio 35 24 apr 12.58 d8ab0052-3057-4baa-aa9a-e082271a2cc8.jpg
```

## Your Environment
* minio disk/node count: 4
* Version used (`minio version`): 2017-08-05T00:00:53Z
* Environment name and version (e.g. nginx 1.9.1): HAproxy 1.5
* Server type and version: VMware VSphere 6.5
* Operating System and version (`uname -a`): CentOS 7, Linux 3.10.0-514.10.2.el7.x86_64 
* Storage: SSD SAN connected with fibrechannel
* Link to your project:

**Comment by fwessels** [comment]
@curantes I notice that almost all dates are '24 apr' except for some '22 sep' on minio02. Did anything specifically happen on 24 april as far as you can recall?

For starters let's begin examining one directory -- can you list the contents of the directory '3546c1e2-b191-4b61-bdde-2411225c0625.pdf' on all four machines?

As well if you can provide the contents of the xl.json files in these directories that would be great (note that these do not contain any confidential information, as the contents of the files are included in the part.1 etc. files).

**Comment by curantes** [comment]
> @curantes I notice that almost all dates are '24 apr' except for some '22 sep' on minio02. Did anything specifically happen on 24 april as far as you can recall?

I have looked through some logs and the calendar but I can't recall any issues that day.

> For starters let's begin examining one directory -- can you list the contents of the directory '3546c1e2-b191-4b61-bdde-2411225c0625.pdf' on all four machines?

all 4 servers have same content:
- part.1
- xl.json

> As well if you can provide the contents of the xl.json files in these directories that would be great (note that these do not contain any confidential information, as the contents of the files are included in the part.1 etc. files).

I have attached the 4 different xl.json files.
[xl.zip](https://github.com/minio/minio/files/1343723/xl.zip)

**Comment by harshavardhana** [comment]
@curantes is this still an issue at your end or should we close this?

**Comment by curantes** [comment]
@harshavardhana you can close this. I think this was a issue due to having traffic while doing upgrade. I will create a new issue if this happens again.

**Comment by harshavardhana** [comment]
Thanks @curantes
