### ISSUE TITLE
Document how to use minio with TLS using IP address

### ISSUE THREAD

**Issue by ryanwalls** [minio/minio#4959]
Even after following the TLS setup guide, I can't get TLS to work with a local minio server and hitting `127.0.0.1`.  

This is the error I get:
```
ERRO[0006] Error in reading from new TLS connection 127.0.0.1:61985 at server 127.0.0.1:9001  cause=EOF source=[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]
```

I would rather not run DNS for this local app.  Is there a way to configure TLS using a static IP address?

## Your Environment

* Version used (`minio version`):
```
Version: 2017-08-05T00:00:53Z
Release-Tag: RELEASE.2017-08-05T00-00-53Z
Commit-ID: aeafe668d8b6d25caac671d59e2b0f0473ce35d0
```
* Environment name and version (e.g. nginx 1.9.1): running locally on a mac
* Server type and version: localhost
* Operating System and version (`uname -a`): 
`Darwin Ryans-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
* Link to your project:

**Comment by vadmeste** [comment]
> I would rather not run DNS for this local app. Is there a way to configure TLS using a static IP address?

@ryanwalls, there are many ways to do that. In case of OSX, I think this is the easiet way:

You create a file called openssl.cnf and put inside it the following text:

```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = VA
L = Somewhere
O = MyOrg
OU = MyOU
CN = MyServerName

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = 127.0.0.1
```

Then, you run the following command where you put the correct path of openssl.cnf.

```
openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout private.key -out public.crt -config openssl.cnf
```

That command will generate the needed public.crt and private.crt, you need to put them in ~/.minio/certs/

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls following document helps you configure TLS with either ip or dns. Just replace with desired ip wherever dns is indicated

**Comment by vadmeste** [comment]
> https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls following document helps you configure TLS with either ip or dns.

That works with curl but doesn't work with mc. Golang will say the https url contains an IP address but the certificate doesn't contain any IP information. That's why I suggested the openssl.cnf solution.

**Comment by harshavardhana** [comment]
We need to then fix our TLS documentation.

**Comment by deekoder** [comment]
@ryanwalls We will add this documentation in the next milestone.

**Comment by deekoder** [comment]
We need to rewrite this doc. @nitisht could you PTAL

**Comment by nitisht** [comment]
@deekoder sent #5231
