### ISSUE TITLE
UI should tell why changing password is disabled

### ISSUE THREAD

**Issue by mlowicki** [minio/minio#4963]
Currently it doesn't say anything - just fields are disabled for editing and there is not "Update" button visible.

**Comment by harshavardhana** [comment]
Thanks @mlowicki for opening an issue. It would be nice if  you used the issue template while reporting the issue, avoids some back and forth on detail gathering.

**Comment by harshavardhana** [comment]
> Currently it doesn't say anything - just fields are disabled for editing and there is not "Update" button visible.

The disabled is meant to be indicative of not being able to do change it. We will be fixing the UI enhancements in `newux` branch.

**Comment by deekoder** [comment]
moving to newux milestone.

**Comment by ghost** [comment]
What are the actual reasons password changing is disabled ? And how to enable it for multi-user ?

**Comment by harshavardhana** [comment]
If your keys are set through env then you can't change the password, there is a PR to allow changing passwords of regular users #7683

**Comment by ghost** [comment]
Thanks @harshavardhana , it was for regular users indeed, I'll subscribe to the PR then.

**Comment by kannappanr** [comment]
This can be closed once #7683 is merged.

**Comment by harshavardhana** [comment]
Closing this issue #7683 is merged, fixed, released.
