### ISSUE TITLE
Download using a Presigned URL for getObject generated via awscli results in signature mismatch error

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#4966]
## Expected Behavior
The object when it exists, should be downloaded to the local machine.

## Current Behavior
Getting a Signature mismatch error.  Here is the exact response from the server

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key></Key><BucketName></BucketName><Resource>/awscli-mint-test-bucket-410/datafile-1-MB</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>

## Steps to Reproduce (for bugs)
1. Build Minio by cloning from https://github.com/minio/minio
2. Start Minio and create a bucket called test-bucket and upload an object called datafile-1-MB
2. Issue the following command
aws --endpoint-url http://192.168.1.200:9000 s3 presign s3://test-bucket/datafile-1-MB
3. Copy the resulting URL
4. issue the following command
curl "http://192.168.1.200:9000/awscli-mint-test-bucket-410/datafile-1-MB?Expires=1506386542&Signature=MnGC76n6py1bPD0lef%2BSqCaKhCI%3D&AWSAccessKeyId=0HLMIQOIZP73MAQRP0F7"

## Your Environment

* Version used (`minio version`):
* Environment name and version (Standalone server version):
* Server type and version:
* Operating System and version (`uname -a`):
Linux ubuntu-ltp 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Fixed by #4965
