### ISSUE TITLE
"Unable to create object part" after /export/.minio.sys/multipart accumulated 10k files on one node

### ISSUE THREAD

**Issue by hagmonk** [minio/minio#4968]
Writes into my distributed minio cluster were consistently failing - after debugging with @harshavardhana we found the count of files in /export looked very different on each node:

```
     505 minio-0
   13171 minio-1
     505 minio-2
     505 minio-3
```

The extra 12666 files were all underneath /export/.minio.sys/multipart.

The server environment is a Kubernetes cluster presently running the y4m4/minio-staging:debug image.

**Comment by krisis** [comment]
@hagmonk Do you have a listing of some (if not all) of the files under `.minio.sys/multipart/` directory?

Did you bring down any of the minio servers while uploading objects?

**Comment by deekoder** [comment]
ping @hagmonk  would you be able to help us troubleshoot further?

**Comment by hagmonk** [comment]
Sorry for the delay here ... here's an example of some of the file paths under .minio.sys:

```
/export/.minio.sys
/export/.minio.sys/multipart
/export/.minio.sys/multipart/torchwood-staging
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.22
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.21
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.13
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.1
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.4
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/xl.json
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.20
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.11
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.12
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.8
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.18
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.2
/export/.minio.sys/multipart/torchwood-staging/attribute-bitmaps/component/b381d8d1-d87a-4980-a55d-c4857c6cc227/part.6
...
```

**Comment by hagmonk** [comment]
It's possible that servers went down while objects were being uploaded – I had some processes hitting the minio service every minute or so. The servers could have gone down for a variety of reasons. Unfortunately I don't have access to logs from around this time.

**Comment by krisis** [comment]
@hagmonk for temporary relief you could run `mc rm -I myminio/<bucket>/object`. Note: `-I` flag is important, it deletes only incomplete multipart uploads. If you miss it you **will delete** your object.

It is not unusual to see the multipart upload directories with different number of files/directories when servers go offline during the upload of a large object. You could use the above command for relief.

**Comment by krisis** [comment]
@hagmonk closing this issue since we haven't heard back for some time now. Feel free to reopen this issue if you face this again with the latest release (or a more recent one).
