### ISSUE TITLE
Converge gateway interface with object interface

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4978]
Todo Item for NAS Gateway

**Comment by deekoder** [comment]
upcoming.

**Comment by harshavardhana** [comment]
Giving this to @poornas since she already sent a PR for this.

**Comment by harshavardhana** [comment]
This is already done should we close this @poornas ?

**Comment by poornas** [comment]
left this open because notification/listener config has not yet been moved to object layer @harshavardhana

**Comment by harshavardhana** [comment]
> left this open because notification/listener config has not yet been moved to object layer @harshavardhana

This has been fixed already with multiple refactors closing.
