### ISSUE TITLE
Azure: ListObjects with negative maxKeys incorrectly fails with InvalidBucketName 

### ISSUE THREAD

**Issue by krisis** [minio/minio#4982]
## Expected Behavior

ListObjects with negative maxKeys on Minio Gateway for Azure should fail with InvalidArgument. 
## Current Behavior

ListObjects with negative maxKeys on Minio Gateway for Azure fails with InvalidBucketName.

## Possible Solution

N/A
## Steps to Reproduce (for bugs)

1. Run mint on Minio gateway for Azure.
2. 
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by balamurugana** [comment]
@krisis How do I reproduce this issue?

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio/pull/4999
