### ISSUE TITLE
Disk http://minio1:9000/export is still unreachable - Physical & Overlay Networks Confict

### ISSUE THREAD

**Issue by painslie** [minio/minio#4987]
## Expected Behavior
I setup a Docker Swarm network with 4 hosts.  Then I deployed a 4 server Mini docker compose file (auto-generated from the minio.io website).  It should have a swarm setup within a minute or two.

## Current Behavior
Containers on each of the 4 hosts were logging similar messages and were not able to connect to the other containers, except for their own (http://minioX:9000/export).
```
time="2017-09-25T01:12:35Z" level=error msg="Disk http://minio1:9000/export is still unreachable" cause="disk not found" source="[prepare-storage.go:197:printRetryMsg()]" 
time="2017-09-25T01:12:35Z" level=error msg="Disk http://minio2:9000/export is still unreachable" cause="disk not found" source="[prepare-storage.go:197:printRetryMsg()]" 
time="2017-09-25T01:12:35Z" level=error msg="Disk http://minio4:9000/export is still unreachable" cause="disk not found" source="[prepare-storage.go:197:printRetryMsg()]" 
Initializing data volume. Waiting for minimum 3 servers to come online. (elapsed 1h5m41s)
```

@nitisht was helping out and created a special minio build to log specific errors...
```time="2017-09-25T13:19:54Z" level=error msg="Unable to establish connection to minio1:9000" cause="dial tcp 10.0.0.2:9000: getsockopt: no route to host" source="[net-rpc-client.go:93:(*RPCClient).dial()]" 
time="2017-09-25T13:19:54Z" level=error msg="Unable to establish connection to minio3:9000" cause="dial tcp 10.0.0.6:9000: getsockopt: no route to host" source="[net-rpc-client.go:93:(*RPCClient).dial()]" 
time="2017-09-25T13:19:54Z" level=error msg="Retrying failed with unexpected error cmd.authConfig{accessKey:\"minio\", secretKey:\"minio123\", serverAddr:\"minio1:9000\", serviceEndpoint:\"/minio/storage/export\", secureConn:false, serviceName:\"Storage\", disableReconnect:true, retryUnit:1000000000, retryCap:30000000000, retryAttemptThreshold:1}" cause="dial-http minio1:9000/minio/storage/export: dial tcp 10.0.0.2:9000: getsockopt: no route to host" source="[auth-rpc-client.go:164:(*AuthRPCClient).Call()]" 
time="2017-09-25T13:19:54Z" level=error msg="Retrying failed with unexpected error cmd.authConfig{accessKey:\"minio\", secretKey:\"minio123\", serverAddr:\"minio3:9000\", serviceEndpoint:\"/minio/storage/export\", secureConn:false, serviceName:\"Storage\", disableReconnect:true, retryUnit:1000000000, retryCap:30000000000, retryAttemptThreshold:1}" cause="dial-http minio3:9000/minio/storage/export: dial tcp 10.0.0.6:9000: getsockopt: no route to host" source="[auth-rpc-client.go:164:(*AuthRPCClient).Call()]" 
```
Basically, `no route to host`.

A `docker network inspect minio_minio_distributed` showed the following.
```
[
    {
        "Name": "minio_minio_distributed",
        "Id": "58yw21frh2e7675vqg5qyu3y0",
        "Created": "2017-09-25T11:49:17.864586262Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "c48418fdd13bc10ffb13b9bb4bdb4162313ea1782e266f4a8c9d404331984549": {
                "Name": "minio_minio2.1.rdps8k7s7pmbdzyg7ep0ux6s9",
                "EndpointID": "8741d38421abda613235b57ba99320b319b71fdfaa5ba3ba01df5d04c43c807a",
                "MacAddress": "02:42:0a:00:00:05",
                "IPv4Address": "10.0.0.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {
            "com.docker.stack.namespace": "minio"
        },
        "Peers": [
            {
                "Name": "s-ams-013-c92aca374326",
                "IP": "10.6.1.51"
            },
            {
                "Name": "s-ams-011-1ecea6358d49",
                "IP": "10.6.5.39"
            },
            {
                "Name": "s-ams-012-83a8c6d7c42f",
                "IP": "10.6.1.27"
            },
            {
                "Name": "s-ams-014-4f0693fcba8e",
                "IP": "10.6.37.143"
            }
        ]
    }
]
```
So internal IP address (on eth0) on each of the 4 hosts is as follows.
host1 = 10.6.5.39/31
host2 = 10.6.5.39/31
host3 = 10.6.1.51/31
host4 = 10.6.37.143/31

Then ran `docker exec -it <container-id> /bin/sh` to check IP address inside one of the containers.
```/go/src/github.com/minio # ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
234: eth2@if235: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:00:05 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.5/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet 10.0.0.4/32 scope global eth2
       valid_lft forever preferred_lft forever
236: eth1@if237: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.3/16 scope global eth1
       valid_lft forever preferred_lft forever
238: eth0@if239: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:ff:00:09 brd ff:ff:ff:ff:ff:ff
    inet 10.255.0.9/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.255.0.8/32 scope global eth0
       valid_lft forever preferred_lft forever
```

I created 3 different clusters on Scalway servers, 2 Debian 8 and one Ubuntu 16.04.  All had the same problem.

## Possible Solution
@nitisht suspects there's some type of conflict between the overlay network and the physical network.  Docker's team has also noticed issues https://github.com/moby/moby/issues/34841#issuecomment-329484088

@nitisht tried to create a customized overlay network, without any success.  This should, in theory, have worked. https://docs.docker.com/engine/swarm/networking/#customize-an-overlay-network

I ended up changing providers!

## Steps to Reproduce (for bugs)
1. Launch 4 Scaleway hosts (bare metal or VM's) - or any IP network in the 10.6.x.x space.
2. Create docker swarm network of 4 nodes.
3. Deploy 4 node minio cluster

## Your Environment
* Minio Version used (`Version: 2017-09-25T07:46:55Z`):
* Docker version: 17.06.2-ce
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: baremetal servers hosted with Scaleway
* Operating System and version (`uname -a`): Ubuntu 16.04.3 LTS;  Was also a problem on Debian 8

**Comment by vadmeste** [comment]
I've also tested with packet.net and it works fine for me.

@painslie:
*) Can you check first if your VMs are pingable between each other? 
*) Can you also test if containers can ping each other ?

```sh
   docker ps # to get container id
   docker run exec -it container_id /bin/sh 
   ping other_container_ip_address
```
you can find the virtual IP of any container using this `docker network inspect minio_minio_distributed`

*) Can you test with VMs while having the same OS distro ? (who knows..)

**Comment by harshavardhana** [comment]
> I've also tested with packet.net and it works fine for me.

@vadmeste @painslie was using scaleway.

**Comment by painslie** [comment]
@vadmeste Our VM's are all singable between each other.  I also used went into the containers on each host (as you mentioned above) and successfully pinged the other hosts on their eth0 IP address.

I've tried this several times with Debian 8 (Jessie) and Ubuntu 16.04.3 LTS.

I guess this is unique to Scaleway because of the address space they use.  I've got a dev Scaleway cluster you're welcome to try.  I'll be turning it down next week though.

**Comment by vadmeste** [comment]
> I've got a dev Scaleway cluster you're welcome to try.

Great, can you send me in private IPs and credentials of your VMs ? I am in Slack: https://slack.minio.io

**Comment by vadmeste** [comment]
Well, it seems that internal DNS of swarm is wrong. If I login to container 1, ping minio2 resolves to an IP that doesn't actually exist (you can check by logging in other containers and then run 'ifconfig').

Now, I am not sure yet why this happens, there are some issues reporting similar problem in Docker project.

By the way @painslie, I found the following paragraph in Swarm documentation:

```
Firewall considerations
Docker daemons participating in a swarm need the ability to communicate with each other over the following ports:

Port 7946 TCP/UDP for container network discovery.
Port 4789 UDP for the container overlay network.
```

I've been told that Scaleway has a different networking system, do you think we need to allow some ports or whatever ?

**Comment by painslie** [comment]
@vadmeste everything should be wide open on those Scaleway servers; but I've tried exactly opening those ports now everything up on the default firewall.  Try again.

**Comment by vadmeste** [comment]
That didn't help @painslie, I'll investigate further,

One example of a similar issue:
https://github.com/moby/moby/issues/30134

**Comment by vadmeste** [comment]
@painslie, I guess that Scaleway doesn't support all Docker features by default. You need to provide the appropriate bootscript which loads the appropriate kernel version and built-in features which support Docker + Swarm very well. So I guess if you redeploy your VMs with bootscript docker, this issue will disappear.

This is the issue from where I found the information above:
https://github.com/scaleway/image-ubuntu/issues/78

**Comment by painslie** [comment]
I switched the boot image to the latest mainline, `x86_64 mainline 4.12.12 rev1`, rebooted the cluster and it worked!  Thanks @vadmeste for all your help!

**Comment by harshavardhana** [comment]
@painslie feel free to close this bug if its resolved.
