### ISSUE TITLE
[refactor] erasure read needs complexity refactoring 

### ISSUE THREAD

**Issue by aead** [minio/minio#4988]
The erasure read code is quite complex with functions taking long parameter lists. We should refactor the code to reduce complexity and take recent code-quality discussions into account.

## Expected Behavior
The code should be readable even tough the overall topic is complex.

## Current Behavior
The current code takes too long argument lists and does too much in too few functions.

## Possible Solution
Refactoring :smile: 

## Context
Overall code quality 

## Your Environment
git master

**Comment by harshavardhana** [comment]
@aead @krishnasrinivas already refactored erasure enough - should we keep this issue open?

**Comment by aead** [comment]
I think we can close and reopen/reference whenever we do something about this...

**Comment by nitisht** [comment]
okay closing this then
