### ISSUE TITLE
fatal error: thread exhaustion

### ISSUE THREAD

**Issue by Panxing4game** [minio/minio#4990]
## Expected Behavior

nothing

## Current Behavior

server down，print "runtime: program exceeds 10000-thread limit fatal error: thread exhaustion"

## Steps to Reproduce (for bugs)

1. start 4 Java process ,each process init a singleton MinioClient
2. create 32 threads each process, to upload images to minio server
3. upload speed is about 10,000 pic/min 
4. api used was minioClient.putObject(bucketName,key,localFilePath);
5. after about 3 hours ,minio server went down,and loged "fatal error: thread exhaustion"

## Your Environment

* Version used (`minio version`):RELEASE.2017-08-05T00-00-53Z
* java sdk version : 3.0.7
* Operating System and version :centOS 7
* client and server are not on the same machine

**Comment by Panxing4game** [comment]
[minio.log.zip](https://github.com/minio/minio/files/1339360/minio.log.zip)

**Comment by Panxing4game** [comment]
package com.imagedt.lemon.cli;

import com.imagedt.common.object.storage.common.ObjectStorageConst;
import com.imagedt.commons.es.doc.BatchEsDocScanner;
import com.imagedt.commons.es.doc.EsDoc;
import com.imagedt.commons.util.common.IDTConfiguration;
import com.imagedt.commons.util.common.IDTHostLocation;
import com.imagedt.commons.util.file.FileUtil;
import com.imagedt.commons.util.redis.ImageDtRedis;
import io.minio.MinioClient;
import io.minio.errors.InvalidEndpointException;
import io.minio.errors.InvalidPortException;
import io.minio.errors.MinioException;
import org.xmlpull.v1.XmlPullParserException;
import redis.clients.jedis.JedisCommands;

import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import static com.imagedt.common.object.storage.common.IdtFileBucket.IMAGE;

/**
 * Created by panxing on 17/9/11
 */
public class ImageUploadClient {

    private static IdtImageDao imageDao;

    static {
        try {
            imageDao = new IdtImageDao();
        } catch (InvalidPortException | InvalidEndpointException | IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        new ImageUploadClient().execute();
    }

    private static class LimitedQueue<E> extends LinkedBlockingQueue<E> {
        LimitedQueue(int maxSize) {
            super(maxSize);
        }

        @Override
        public boolean offer(E e) {
            try {
                put(e);
                return true;
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
            }
            return false;
        }
    }

    private static class UploadRunner implements Runnable {

        private final EsDoc esDoc;

        UploadRunner(EsDoc esDoc) {
            this.esDoc = esDoc;
        }

        @Override
        public void run() {
            try {
                String imagePath = getPath(esDoc);
                String md5 = imageDao.upload(imagePath);
            } catch (Exception e) {
            }
        }
    }


    protected void execute() {

        // I hava 32 processors here
        int workerNum = Runtime.getRuntime().availableProcessors();
        ExecutorService threadPool = new ThreadPoolExecutor(workerNum, workerNum, 0L, TimeUnit.MILLISECONDS, new LimitedQueue<>(workerNum * 2));

        searcher.search((BatchEsDocScanner) list -> list.forEach(doc -> {
                    threadPool.execute(new UploadRunner(doc));
                })
        );
    }


    private static class IdtImageDao {
        private MinioClient minioClient;
        private JedisCommands redis;

        public IdtImageDao() throws InvalidPortException, InvalidEndpointException, IOException {
            IDTConfiguration configuration = IDTConfiguration.getInstance();

            String osUrl;
            String redisConfig;
            if (configuration.hostLocation == IDTHostLocation.ALI_YUN) {
                osUrl = IDTConfiguration.OBJECT_STORAGE_URL_TUNNEL;
                redisConfig = configuration.get(IDTConfiguration.FILE_REDIS_CONFIG_TUNNEL);
            } else {
                osUrl = IDTConfiguration.OBJECT_STORAGE_URL;
                redisConfig = configuration.get(IDTConfiguration.FILE_REDIS_CONFIG);
            }

            minioClient = new MinioClient(
                    configuration.get(osUrl),
                    configuration.get(IDTConfiguration.OBJECT_STORAGE_ACCESS_KEY),
                    configuration.get(IDTConfiguration.OBJECT_STORAGE_SECRET_KEY));
            redis = ImageDtRedis.getInstance(new String[]{redisConfig}).getJedisCommands();
        }

        public String upload(String filePath) throws IOException, InvalidKeyException, NoSuchAlgorithmException, MinioException, XmlPullParserException {
            String md5 = FileUtil.md5(filePath);
            if (redis.sadd(ObjectStorageConst.MD5_REDIS_KEY, md5) == 1) {
                try {
                    minioClient.putObject(IMAGE.name, md5, filePath);
                } catch (InvalidKeyException | NoSuchAlgorithmException | MinioException | XmlPullParserException e) {
                    redis.srem(ObjectStorageConst.MD5_REDIS_KEY, md5);
                    throw e;
                }
            }
            return md5;
        }
    }
}

**Comment by harshavardhana** [comment]
Thanks for the sharing the code and reproducing it.

**Comment by deekoder** [comment]
we are still looking into this. Please stay tuned.

**Comment by harshavardhana** [comment]
Pasting some more details here about this bug, from the logs we can obtain that there are around 9990 active i/o calls in progress.

```
grep 'os.(\*File).Write' minio.log | wc -l
9990
```

>They're called goroutines because the existing terms—threads, coroutines, processes, and so on—convey inaccurate connotations. A goroutine has a simple model: it is a function executing concurrently with other goroutines in the same address space. It is lightweight, costing little more than the allocation of stack space. And the stacks start small, so they are cheap, and grow by allocating (and freeing) heap storage as required.

>Goroutines are multiplexed onto multiple OS threads so if one should block, such as while waiting for I/O, others continue to run. Their design hides many of the complexities of thread creation and management.

Each thread is given to a Go process if it is actively blocked on a syscall, in the `minio.log` we can see that is the case here.

Relevant fixes done in other projects such as docker https://github.com/moby/moby/pull/18362

Fixes the issue reported here 
- https://github.com/moby/moby/issues/15258
- https://github.com/moby/moby/issues/15256
- https://github.com/moby/moby/pull/12159#issuecomment-125739702
