### ISSUE TITLE
[gateway/gcs] validate whether gateway sends Content-MD5 or checksum to server

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4995]
Currently Content-MD5 or other checksum is not sent to GCS server for `PUT`, `POST` methods. Its required to send at least one checksum header to server to verify transferred body.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
We need to do this in the next release. Not critical for release.

**Comment by Praveenrajmani** [comment]
The same block as discussed in [https://github.com/minio/minio/issues/4994#issuecomment-434682933](url)

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
