### ISSUE TITLE
Implement support for x-amz-storage-class for configurable erasure coding

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4997]
Avoiding issue template on purpose.

```
x-amz-storage-class 

Valid Values: STANDARD | STANDARD_IA | REDUCED_REDUNDANCY
```

If you don't specify, Standard is the default storage class. Amazon S3 supports other storage classes. We can re-purpose these values or come up with new valid values. These values when set with minio SDKs during PutObject() would set the right value, each objects would be able to choose the right data and parity.

**Comment by deekoder** [comment]
@nitisht any updates on this.

**Comment by nitisht** [comment]
Just started @deekoder . I will propose a solution in few days.

**Comment by nitisht** [comment]
Based on discussion with @abperiasamy this is the initial approach for implementation of storage classes https://gist.github.com/nitisht/ba07d65626f4848b338513fff1d075c5

**Comment by nitisht** [comment]
Bumping priority due to client requirements.
