### ISSUE TITLE
S3-gateway returns InternalServerError instead of EntityTooSmall in CompleteMultipartUpload 

### ISSUE THREAD

**Issue by krisis** [minio/minio#5005]
## Expected Behavior

S3 gateway should return EntityTooSmall error response code when upload of a part is smaller than 5MB. 

## Current Behavior

S3 gateway instead returns InternalServerError.
## Possible Solution

N/A
## Steps to Reproduce (for bugs)

1. Refer https://github.com/minio/mint/issues/168
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by krisis** [comment]
This issue is fixed by https://github.com/minio/minio/pull/5006. @deekoder can we close this?

**Comment by harshavardhana** [comment]
This is fixed by #5006
