### ISSUE TITLE
Incompatibility with git-annex: RFC1139 format too strict.

### ISSUE THREAD

**Issue by hverr** [minio/minio#5007]
[Git annex](https://git-annex.branchable.com/) is a popular tool for managing large files with git. It is able to use S3-compatible storage backends to store the actual data.

Unfortunately, the HTTP `Date` request header value produced by git annex is incompatible with parser for the RFC1123 time format in the Go standard library, used by minio. This leads to incompatibility issues between the two tools in the first 9 days of each month.

E.g.: git annex sends the following request header:

```
Date: Tue,  3 Oct 2017 18:53:01 GMT
```

But minio only accepts

```
Date: Tue, 03 Oct 2017 18:53:01 GMT
```

## Expected Behavior
Minio accepts `Date`-header values that contain single-digit days of the month.

## Current Behavior
Minio does not accept `Date`-header values that contain single-digit days of the month. It requires double-digit days of the month.

## Possible Solution
PR #5008 

## Steps to Reproduce (for bugs)
1. Deploy a minio instance on localhost
2. Set the clock of the host to 3 Oct 2017
3. Try to add minio as an S3 remote using git-annex
4. Minio will return a 400 Bad Request with message: `Invalid date format header, expected ISO601, RFC1123 or RFC1123Z  time format.`

## Context

See short description at the top.

## Your Environment
* Version used: 89d528a4

**Comment by balamurugana** [comment]
According to [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) the date must be in RFC 1123 defined in https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1.

It seems bug in `Git annex`

**Comment by hverr** [comment]
Although **I think** (don't shoot me if I'm incorect) the RFC1123 date format technically allows for single-digit and double-digit days of the month, the RFC2616 is clear in the fact that it does not.

Yet, I'm still advocating to loosen up the header parsing in minio, as a fix in git annex would require a fix in a library dependency and would be far more complex and would take a lot more time than a patch to minio.

Furthermore, the proposed patch does not add to the complexity of the minio code base, yet adds compatibility with possibly many misbehaving clients.

**Comment by harshavardhana** [comment]
> Furthermore, the proposed patch does not add to the complexity of the minio code base, yet adds compatibility with possibly many misbehaving clients.

We shouldn't make Minio compatible with misbehaving clients, clients should be fixed.

**Comment by hverr** [comment]
Understood, thanks for considerating
