### ISSUE TITLE
Docker Healthcheck fails on latest Minio release Docker image

### ISSUE THREAD

**Issue by nitisht** [minio/minio#5010]
## Expected Behavior
Docker should report the status of Minio container as healthy

## Current Behavior
Docker reports the status as unhealthy

```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                      PORTS               NAMES
e8ce5a03d72a        minio/minio:RELEASE.2017-09-29T19-16-56Z   "/usr/bin/docker-e..."   11 minutes ago      Up 11 minutes (unhealthy)                       zen_turing

```

## Possible Solution
Fix `healthcheck.sh`  

## Steps to Reproduce (for bugs)
1. Launch latest release Docker Minio image
```
sudo docker run -p 9000:9000 --net=host minio/minio:RELEASE.2017-09-29T19-16-56Z server /tmp/test
```
2. After sometime, check the status using `docker ps`. 

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by dswd** [comment]
Same problem here. However the "fix" will not work for me as the health check is performed by an external tool. I guess this will hit a lot of people using external tools like Nagios.

**Comment by harshavardhana** [comment]
Do not understand what you are talking about here @dswd

**Comment by harshavardhana** [comment]
> Same problem here. However the "fix" will not work for me as the health check is performed by an external tool. I guess this will hit a lot of people using external tools like Nagios.

This fix has nothing to do with nagios, for nagios monitoring you should write your own plugin using admin REST API.  In this fix healthcheck is a concept of docker containers which happily accepts external tools, one such example scripts used https://github.com/docker-library/healthcheck

**Comment by dswd** [comment]
Ok to clarify: I need a simple unauthorized URL that can be used for a health check by an external tool. 
Before the current release I used `/minio/login` for this but the current release changed the behavior so that now it depends on the user agent. If this functionality is possible using the REST API, I am fine with that (please tell me the path to use).

**Comment by harshavardhana** [comment]
> Ok to clarify: I need a simple unauthorized URL that can be used for a health check by an external tool.
> Before the current release I used /minio/login for this but the current release changed the behavior so that now it depends on the user agent. If this functionality is possible using the REST API, I am fine with that (please tell me the path to use).

If you require unauthorized, then you can add a User-Agent since you are already using an external tool. There are no unauthorized endpoints on Minio other than browser.

**Comment by dswd** [comment]
Exactly that is my problem. The external tool has no support for adding a fake user-agent to the request. Could you consider restoring the original behavior of minio?

**Comment by harshavardhana** [comment]
> Exactly that is my problem. The external tool has no support for adding a fake user-agent to the request. Could you consider restoring the original behavior of minio?

Original behavior was wrong its the same reason why our docker healthscript stopped working. @dswd  what is the external tool that is being used which cannot take a user-agent?

**Comment by dswd** [comment]
The external tool I am talking about is the integrated health check of Cloudron.io. I am maintaining the Minio app on that platform.

**Comment by harshavardhana** [comment]
> The external tool I am talking about is the integrated health check of Cloudron.io. I am maintaining the Minio app on that platform.

Do you have the code for this App that we can take a look? @dswd

**Comment by dswd** [comment]
Ich already sent a PR to that project but that will take some weeks. Until then  the current minio will not be available.

**Comment by dreh23** [comment]
Same Problem here. Hashicorp's nomad health check needs an unauthorized http request with a 2xx ranged reply. See here: [https://www.nomadproject.io/docs/job-specification/service.html#check-parameters](https://www.nomadproject.io/docs/job-specification/service.html#check-parameters). I believe an unauthorized dedicated /health endpoint would be useful.

**Comment by N1v0k** [comment]
We are using minio on Rancher, which also needs any kind of 2xx response from an unauthorized endpoint.

**Comment by metametadata** [comment]
+1 for simple /health endpoint. Would make writing [Kubernetes readiness/live probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) much easier.

**Comment by yebo29** [comment]
The docker state still shows unhealthy, however. Should I just manually change healthcheck.sh until it gets fixed? No rush in my case, it's just aesthetic for me as I'm not monitoring (it's for a personal project). Many thanks.

**Comment by yebo29** [comment]
Nevermind. I see it's being handled in https://github.com/minio/minio/issues/6365

**Comment by fergbrain** [comment]
@yebo29 The issue has been fixed in RELEASE.2018-09-01T00-38-25Z: https://github.com/minio/minio/tree/RELEASE.2018-09-01T00-38-25Z
