### ISSUE TITLE
Files do not sync to an offline node once it comes back online

### ISSUE THREAD

**Issue by lauragiles** [minio/minio#5016]
## Expected Behavior
If a minio docker container is stopped for maintenance and files are uploaded to minio during this time, i would expect the files to be copied to the offline node once it comes back online.

## Current Behavior
Checked the docker volumes folder size and the offline nodes files are less than the other node volume sizes.

## Steps to Reproduce (for bugs)

1. stop one of the nodes docker containers
2. upload a large file
3. start docker container
4 check docker volume sizes of all nodes in the cluster

## Context
Are we missing something? do we need to run a command to resync files across all nodes?

## Your Environment

* Version used - latest
* Ubuntu 16
* Virtual

**Comment by harshavardhana** [comment]
> Are we missing something? do we need to run a command to resync files across all nodes?

You need to run `mc admin heal` to sync them back up, there is no auto-heal.

**Comment by lauragiles** [comment]
I thought the mc admin heal command is used to reinitialise a disk only. Its possible we would stop the docker container and run maintenance on the base OS and up the container again after. The disks and the data on the disks would remain the same. Do i still need to run mc admin heal?

**Comment by harshavardhana** [comment]
mc admin heal is to heal disk, bucket and objects. If you have taken the server down and uploaded objects. Then you need to heal those objects..once the server joins back the cluster.

Healing is driven through a REST API which can be called by external application either it's `mc admin heal` or your app.

**Comment by lauragiles** [comment]
ok. So i run _mc admin heal devops-1_ using minio client. The data volume size still doesn't change. 
Is there a log file i can check? We are concerned that when we take nodes offline for maintenance we will have data inconsistencies across all nodes if we can't resync them.

Please see files attached 
![screen shot 2017-10-05 at 09 05 30](https://user-images.githubusercontent.com/28596314/31216677-68021cbc-a9ac-11e7-9e9e-133fb2496d95.png)
![screen shot 2017-10-05 at 08 56 55](https://user-images.githubusercontent.com/28596314/31216678-6838820c-a9ac-11e7-8653-7177ed5574b6.png)

**Comment by harshavardhana** [comment]
> ok. So i run mc admin heal devops-1 using minio client. The data volume size still doesn't change.
> Is there a log file i can check? We are concerned that when we take nodes offline for maintenance we will have data inconsistencies across all nodes if we can't resync them.

@lauragiles current command is changing and you won't be performing the same instructions as i am about to give you. 

But this is what it works currently in the available mc build. 

```
mc admin heal devops-1  -- Only heals the `format.json`, i.e attaches the disk to the cluster to be usable. (This is only necessary if the disk was replaced, unlike in your case this won't do anything)
```

```
mc admin heal --recursive devops-1/<bucketname> -- Heals bucket and all its objects. 
mc admin heal --incomplete --recursive devops-1/<bucketname> -- Heals bucket and all the (multipart) uploads.
```

**Comment by lauragiles** [comment]
Ok that makes sense. I was hoping we wouldn't have to specify each bucket name individually.

Thanks for the reply. Look forward to the updated version.

**Comment by harshavardhana** [comment]
> Ok that makes sense. I was hoping we wouldn't have to specify each bucket name individually.
> 
> Thanks for the reply. Look forward to the updated version.

Closing this as answered and resolved.
