### ISSUE TITLE
feature request: Provide a tool for reassembling EC file parts outside of minio

### ISSUE THREAD

**Issue by rhaig** [minio/minio#5026]
For debug, learning, and pacification of managers, a tool that would reassemble the parts of erasure coded files would be handy to have. This tool could also provide a method for partial reconstruction of files.

## Expected Behavior

I'm envisioning a tool that would essentially un-EC files after a sufficient number of parts of the files (and their included config) were collected from the various drives/servers that may have survived a failure. 

## Current Behavior

currently, there is no documented method to reassemble EC file parts outside of minio

## Possible Solution

clearly minio contains this functionality, but instead of the output being a network socket, the app would open a file and write the contents.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I have product component owners that are hesitant to use EC as they would like to be able to read the files direct from disk.  Having a tool like this could aid in acceptance as well as provide a learning tool and partial recovery tool (sometimes the first 12.5% of a file is enough).

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by fwessels** [comment]
Thank you for submitting the feature request, this is an interesting idea.

While it would be possible to "rip" some code out of the minio repo in order to accomplish this, a more structural approach requires considerably more thought and probably some reorganization of our source code base.

At the moment it is not a priority but we will keep it in the back of our minds and maybe some time in the future we will have enough bandwidth to work on something along these lines.

**Comment by harshavardhana** [comment]
This is re-opened to open discussion, about if we need to provide this tool.

**Comment by ebozduman** [comment]
Scheduled as candidate for future work.

**Comment by kannappanr** [comment]
@krisis to discuss about this with @abperiasamy

**Comment by harshavardhana** [comment]
> This is re-opened to open discussion, about if we need to provide this tool.

Closing this issue as not a priority at the moment, due to how the erasure coding was changed with streaming bitrot the effort to do a simple assemblage of erasured parts is not possible anymore.
