### ISSUE TITLE
[gateway] stale objects may be found in main namespace

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5030]
In Azure/GCS, when single put object is called, the client may send checksum of the object stream as Content-MD5 or SHA-256.  The stream is forwarded to backend service and in parallel the checksum is validated.  If checksum failed at gateway, gateway calls remove object of uploaded object.

The above approach would lead by other clients could access wrongly uploaded object because it is available in main namespace.

The solution to this problem could be use multipart upload of given object eleminates this problem.

**Comment by harshavardhana** [comment]
@balamurugana @krishnasrinivas suggested an easier suggestion to fail with a wrapped reader which does `data.Verify()` on io.EOF , this would ensure that object is not written to the backend we do not need to add multipart code. 

This is how it is currently implemented on backblaze-b2.

**Comment by krishnasrinivas** [comment]
what we can do for azure/gcs is stream everything to the backend except the last byte, do `data.Verify()` (after reading the last byte) and depending on the result send the last byte to the backend.

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
