### ISSUE TITLE
md5sum not available for objects where more than one part is stored

### ISSUE THREAD

**Issue by sebschlue** [minio/minio#5037]
```
$ dd if=/dev/urandom of=one_mb bs=1M count=1
$ rclone copy one_mb minio:bucket/
$ rclone md5sum minio:bucket/one_mb

$ dd if=/dev/urandom of=ten_mb bs=1M count=10
$ rclone copy ten_mb minio:bucket/
$ rclone md5sum minio:bucket/ten_mb

```

Using minio version 2017-09-29T19:16:56Z

**Comment by harshavardhana** [comment]
This is expected. Multipart files don't have md5sum stored after complemultipart.. this should be true with AWS S3 as well refer http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

**Comment by harshavardhana** [comment]
@sebschlue feel free to close this issue.
