### ISSUE TITLE
No HA API for checking if minio could create new object (a.k.a in read-only mode or not)

### ISSUE THREAD

**Issue by harry75369** [minio/minio#5044]
As the doc says, minio can withstand at most N/2 disks failure but it requires at least (N/2 + 1) disks to create new object.

When N/2 disks fails and you want to upload file, the request will be pending all the time, until at least one more disks come back, and then will the request be finished.

However, if the recovery time is too long, user will be kept waiting too long. The user cannot get an immediate feedback that the minio is in read-only mode due to N/2 disks failure, since there is no High-Availibity related API for checking if minio could new object or not.

**Comment by harshavardhana** [comment]
Which version of Minio are you running ? `minio version`

**Comment by harry75369** [comment]
```
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
```

In my test, the pending timeout is about 15 minutes, which means user has to wait 15 mins before he get a timeout error.

And I am using minio-js (3.1.3) API to upload file.

By using `mc admin info ...`, I could see which nodes are down, but cannot determine if minio is in read-only mode or not. And also `mc admin info` has no API version for developer to use.

**Comment by harshavardhana** [comment]
> Version: 2017-09-29T19:16:56Z
> Release-Tag: RELEASE.2017-09-29T19-16-56Z
> Commit-ID: 60cc6184d253efee4a3120683517028342229e21
> In my test, the pending timeout is about 15 minutes, which means user has to wait 15 mins before he get a timeout error.

Yes this is expected @harry75369 we need Locks to timeout for the client to see an error. We introduced timeout for this reason alone so that we avoid a fully blocking operation forever.  There is no way we can return an error hastily since there is no difference between a temporary network disconnection v/s a permanent one. These timeout values are chosen based on practical conditions and can be changed as well in future releases based on most common timeout value.  

A read only situation can be ascertained by simply initiating a call on a previously created object, where as your upload should fail with a timeout.   There is no S3 API level feature for these things, so if you did get an error you can understand that we do not have quorum to complete the transaction.

**Comment by harry75369** [comment]
> Yes this is expected @harry75369 we need Locks to timeout for the client to see an error. We introduced timeout for this reason alone so that we avoid a fully blocking operation forever. There is no way we can return an error hastily since there is no difference between a temporary network disconnection v/s a permanent one. These timeout values are chosen based on practical conditions and can be changed as well in future releases based on most common timeout value.

I see. Is it able to customize the timeout as a parameter in the upload API so that smaller timeout will give quicker response?

> A read only situation can be ascertained by simply initiating a call on a previously created object, where as your upload should fail with a timeout. There is no S3 API level feature for these things, so if you did get an error you can understand that we do not have quorum to complete the transaction.

So the only way to get upload failure due to read-only situation is by (possibly customizable) timeout which is 15 mins for now. But timeout is hacky, what if a file needs more than 15 mins to upload due to big size or slow network speed? In this case, user will never upload file successfully unless there are better strategies, for example:
1. upload file, fail with 15 mins timeout, error says "maybe minio is in read-only situation, try again"
2. upload the same file again, fail with  30 mins timeout, error says "maybe minio is in read-only situation, try again"
3. upload the same file again, fail with 60 mins timeout, error says "you will never upload this file successfully", stop trying.

One possible way to get upload failure due to read-only situation is to check if current available quorum is equal to N/2, and gives the error message immediately and more surely that minio is in read-only situation. But current APIs don't support this.

**Comment by harshavardhana** [comment]
> So the only way to get upload failure due to read-only situation is by (possibly customizable) timeout which is 15 mins for now. But timeout is hacky, what if a file needs more than 15 mins to upload due to big size or slow network speed? In this case, user will never upload file successfully unless there are better strategies, for example:

Timeout is only for acquiring once the Lock is acquired you can upload object until Content-Length.  You cannot tune this parameter, this parameter dynamically changes the value as the time progresses too. 

> One possible way to get upload failure due to read-only situation is to check if current available quorum is equal to N/2, and gives the error message immediately and more surely that minio is in read-only situation. But current APIs don't support this.

We do understand that but it is not architecturally correct to assume that.  There are always situations where in a distributed system  nodes are temporarily offline, in middle of a startup or some other sort of situation etc.  A timeout based nature is provided, such that in a situation like temporary offline, network errors - your calls are not necessarily pro-actively cancelled atomically - ample time is given such that your nodes come back online and such a call might succeed. 

Another judicious assumption is that if your nodes are dying all the time, if they do you have an entirely different set of problem. Once N/2 disks are lost you have little room to do anything in a quorum based system, we just wait in such a situation. If nothing is around until 15 minutes we just give up.  

So current APIs are behaving as expected.

**Comment by harry75369** [comment]
I see. From minio's developer's view, current APIs have no problem.

But from minio's user's view, the upload API's behavior is not friendly enough due to the long wait time in the case of read-only situation.

Anyway, thanks for the reply. You can close this issue.

**Comment by harshavardhana** [comment]
> Anyway, thanks for the reply. You can close this issue.

Closing as answered.
