### ISSUE TITLE
Does minio work on a FUSE (Filesystem in user space)

### ISSUE THREAD

**Issue by venchen** [minio/minio#5046]
Tried to run minio against a FUSE mounted folder /tmp/foo
ran the command
./minio server /tmp/foo/

Got the following message:
ERRO[0000] Initializing object layer failed              cause=disk path full source=[server-main.go:209:serverMain()]

The FUSE mount has plenty of space - its a custom FUSE driver that Ive built that might not be returning something that minio needs (for example I have not implemented XATTRS)

## Expected Behavior

The FUSE mount should be used by minio as its data directory

## Steps to Reproduce (for bugs)

1. Setup a FUSE mount point - (for e.g. https://peterodding.com/code/python/dedupfs )
2. Run minio server against the FUSE mount point

## Context

I have a custom FUSE that is backed by a key value store (like Redis). My FUSE exposes the Key Value store as a POSIX file system.  Standalone my FUSE works fine and I can do all file operations - touch, cat, ls, dd, rm, ln, mkdir/rmdir etc. 

## Your Environment

* Version used (`minio version`):
version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Ubuntu 16.0.4 LTS
* Operating System and version (`uname -a`):Linux alpha-2 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
You need a fully POSIX compatible filesystem or a Windows Win32 API compliant disk FS such as NTFS.

It is not advisable to run on any other backend fs. If you happen to use you are on your own.

**Comment by venchen** [comment]
Thanks, @harshavardhana - that's what I suspected. Will hack away at the FUSE till its compatible.
Cheers!

**Comment by harshavardhana** [comment]
Feel free to close this issue @venchen.

**Comment by venchen** [comment]
FWIW and if it helps any other FUSE writers trying to put minio on their FUSE - implementing the StatFS function fixes this particular problem I ran into and allows minio to server a FUSE mounted directory as the data folder (minio server /<path to FUSE mount>)
