### ISSUE TITLE
Azure gateway - Etag not changed for multipart upload

### ISSUE THREAD

**Issue by jmaitrehenry** [minio/minio#5052]
On Azure Gateway, we add "-1" to the etag header when we put a new file, but, when we use a multipart upload, it doesn't overwrite the etag header

## Expected Behavior
Append "-1" to multipart etag header

## Current Behavior
Don't append "-1" to multipart etag header

## Context
```
DEBUG: format_uri(): /files/multipart.pdf?partNumber=1&uploadId=f92d518b71f26947

{'data': '',
 'headers': {'accept-ranges': 'bytes',
             'content-length': '0',
             'content-type': 'text/plain; charset=utf-8',
             'date': 'Tue, 10 Oct 2017 17:58:45 GMT',
             'etag': '"fc7d1cde16acc6a9ea43534fe9c47667"',
             'server': 'Minio/DEVELOPMENT.GOGET (linux; amd64)',
             'vary': 'Origin',
             'x-amz-request-id': '14EC474256C4529B'},
 'reason': 'OK',
 'size': 15728640,
 'status': 200}
 15728640 of 15728640   100% in    0s    29.20 MB/s  done
DEBUG: MD5 sums: computed=aefacbcda00c1a546a161ad01d64c7f1, received=fc7d1cde16acc6a9ea43534fe9c47667
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of files/multipart.pdf
```

## Your Environment

* Version used (`minio version`): master + metadata fixes

**Comment by jmaitrehenry** [comment]
I will create a PR soon with a fix, I do just a little more test/debugging for now

**Comment by balamurugana** [comment]
@jmaitrehenry Do you say ETag of parts need to be suffixed with `-1`?

**Comment by jmaitrehenry** [comment]
@balamurugana Yes, without it, the md5 check failed.
