### ISSUE TITLE
How do I use https with minio?

### ISSUE THREAD

**Issue by kineticz** [minio/minio#5058]
After starting the server (`minio server miniodata/`),  I got this: 

```
Browser Access:
   http://192.168.8.40:9000  http://127.0.0.1:9000
```

## Expected Behavior

I was expecting https://127.0.0.1:9000 would work as well. 

## Current Behavior

When I visit `https://127.0.0.1:9000` in the browser I got this:

```
Secure Connection Failed
```

And in the terminal there is this message: 

```
ERRO[0085] Received non-HTTP message from new connection 127.0.0.1:51618 at server 127.0.0.1:9000  cause=junk message source=[listener.go:205:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]
```

## Your Environment

* Version:

```
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
```

* Operating System and version (`uname -a`):

```
Darwin kaiyins-mbp 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
```

**Comment by harshavardhana** [comment]
have you read our TLS docs ? https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls

**Comment by harshavardhana** [comment]
@kindlychung were you able to follow the docs? - feel free to close this issue if you have no further questions.

**Comment by kineticz** [comment]
Yes, the docs are good. Thanks.

**Comment by sceptic30** [comment]
Not sure where to ask, so im gonna ask here since i have a similar question.
First, can minio work in distributed mode with SSL enabled in docker swarm? 

**The docs are missing info about this specific matter.**

My NOT WORKING compose file is this: 

  minio1:
    image: minio/minio:latest
    hostname: minio1
    volumes:
      - minio1-data:/export
      - ./minio/certs:/home/certs
    ports:
      - "7081:7443"
    networks:
      - app-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server --config-dir /home --certs-dir /home/certs https://minio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "https://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
   
     minio2:
      ....(same config for the other containers)

Thanks

**Comment by harshavardhana** [comment]
come over ask us at https://slack.min.io please don't post on old issues @sceptic30
