### ISSUE TITLE
Building a Dockerfile from a tag in git just builds the latest master

### ISSUE THREAD

**Issue by fbartels** [minio/minio#5064]
Doing a checkout of a specific tag and then running `docker build .` will create a minio binary based on the current status of the master branch and not the checkout tag.

## Expected Behavior
- building the dockerfile should produce a minio binary from the currently checked out code

## Current Behavior
- uses go get to build based on the latest master

## Possible Solution
- use add or copy to copy the checked out code into the docker environment before building

## Steps to Reproduce (for bugs)
1. `git checkout RELEASE.2017-09-29T19-16-56Z`
2. `sudo docker build .`

## Context
I want to rebuild a tagged Minio release for inclusion into the app store of a Linux business distribution.

**Comment by harshavardhana** [comment]
@fbartels just build 

- `docker build -f Dockerfile.dev -t minio/minio:dev` for your local copy
- `docker build -f Dockerfile  -t minio/minio:edge` for master copy
- `docker build -f Dockerfile.release -t  minio/minio:latest` for release binary

**Comment by fbartels** [comment]
Ah, ok the Dockerfile.release did not yet exist when the last tag was created. This file indeed does what I want.
