### ISSUE TITLE
Anonymous downloads not working via web ui on bucket with read-only policy

### ISSUE THREAD

**Issue by chotaire** [minio/minio#5076]
## Expected Behavior
When using minio.RELEASE.2017-09-29T19-16-56Z (amd64) and setting a bucket to read-only within the web ui (with no prefix or prefix set as *), anonymous users should be able to view the bucket and also download all objects that are in the root of the bucket (using the web ui).

## Current Behavior
Anonymous users can view the bucket using the web ui, but when they attempt to click an object  they get to see a warning ""Authentication failed, check your access credentials". When downgrading to minio.RELEASE.2017-08-05T00-00-53Z (amd64) however, it works as intended.

## Possible Solution
For users, the current solution is to downgrade to minio.RELEASE.2017-08-05T00-00-53Z.

## Steps to Reproduce (for bugs)
1. Create bucket using web ui
2. Upload file into bucket using web ui
3. Create * read-only policy using web ui
4. Copy URL from browser and open in another incognito window
5. Attempt to download one of the files using web ui

## Context
Without this broken feature it is not possible to allow anonymous users to access objects from a read-only bucket using the web ui.

## Your Environment
* minio.RELEASE.2017-09-29T19-16-56Z
* golang 1.8.3
* Kernel 4.13.5-200.fc26.x86_64

**Comment by harshavardhana** [comment]
can you tell us how you tested this? @chotaire

**Comment by harshavardhana** [comment]
> Anonymous users can view the bucket, but when they attempt to download an object they get to see a dialog warning them that credentials are missing. When downgrading to minio.RELEASE.2017-08-05T00-00-53Z (amd64) however, it works as intended.

Are you talking about web browser UI? @chotaire - looks like a regression.

**Comment by vadmeste** [comment]
With Browser UI, I am not able to list a bucket in download mode, but I was able to download any file.

It looks like bucket policy sent for UI is different to mc's one.

**Comment by harshavardhana** [comment]
> With Browser UI, I am not able to list a bucket in download mode, but I was able to download any file.
> 
> It looks like bucket policy sent for UI is different to mc's one.

Looks like a small regression - sending a fix.

**Comment by chotaire** [comment]
Yes I am talking about the Web UI. You can easily reproduce as explained in my original post.

> With Browser UI, I am not able to list a bucket in download mode, but I was able to download any file.

This may be related, but is a different issue. In this case policies were probably defined using mc. In my case, bucket policies were defined using the Web UI.

**Comment by harshavardhana** [comment]
> Yes I am talking about the Web UI. You can easily reproduce as explained in my original post.
> 
> With Browser UI, I am not able to list a bucket in download mode, but I was able to download any file.
> This may be related, but is a different issue. In this case policies were probably defined using mc. In my case, bucket policies were defined using the Web UI.

@chotaire i just tested the master branch, i cannot reproduce the problem.  what type of minio setup is this are you using basic single disk FS mode? or multiple disk distributed mode?

**Comment by harshavardhana** [comment]
Also if possible can you provide the output of `policy.json`  locate ad `.minio.sys/buckets/<bucketname>/policy.json` 

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::<bucketname>"
      ],
      "Sid": ""
    },
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::<bucketname>/*"
      ],
      "Sid": ""
    }
  ]
}
```

**Comment by vadmeste** [comment]
@harshavardhana, I was able to reproduce this.. actually @chotaire was talking about downloading a file from the browser without credentials and not curl.

**Comment by vadmeste** [comment]
Clicking on the object in Minio Browser in anonymous mode will send this request:
```
{"id":1,"jsonrpc":"2.0","params":{},"method":"Web.CreateURLToken"}
```

the response is:
```
{"jsonrpc":"2.0","error":{"code":0,"message":"Authentication failed, check your access credentials","data":null},"id":1}
```

**Comment by chotaire** [comment]
I have updated the issue description to reflect that this is all about the web ui. creating the bucket, setting the policy, uploading the file and accessing the objects: all web ui. Sorry I did not make myself clear enough. 

> Also if possible can you provide the output of policy.json

`
{"Version":"2012-10-17","Statement":[{"Action":["s3:GetBucketLocation","s3:ListBucket"],"Effect":"Allow","Principal":{"AWS":["*"]},"Resource":["arn:aws:s3:::whatever"],"Sid":""},{"Action":["s3:GetObject"],"Effect":"Allow","Principal":{"AWS":["*"]},"Resource":["arn:aws:s3:::whatever/*"],"Sid":""}]}
`

**Comment by chotaire** [comment]
> @chotaire i just tested the master branch, i cannot reproduce the problem. what type of minio setup is this are you using basic single disk FS mode? or multiple disk distributed mode?

That's basic single disk FS mode. Nothing fancy except that I use TLS with a real certificate chain.

`
{
        "version": "19",
        "credential": {
                "accessKey": "<censored>",
                "secretKey": "<censored>"
        },
        "region": "eu-central-1",
        "browser": "on",
        "logger": {
                "console": {
                        "enable": false
                },
                "file": {
                        "enable": false,
                        "filename": "/var/log/minio.log"
                }
        },
        "notify": {
                "amqp": {
                        "1": {
                                "enable": false,
                                "url": "",
                                "exchange": "",
                                "routingKey": "",
                                "exchangeType": "",
                                "deliveryMode": 0,
                                "mandatory": false,
                                "immediate": false,
                                "durable": false,
                                "internal": false,
                                "noWait": false,
                                "autoDeleted": false
                        }
                },
                "nats": {
                        "1": {
                                "enable": false,
                                "address": "",
                                "subject": "",
                                "username": "",
                                "password": "",
                                "token": "",
                                "secure": false,
                                "pingInterval": 0,
                                "streaming": {
                                        "enable": false,
                                        "clusterID": "",
                                        "clientID": "",
                                        "async": false,
                                        "maxPubAcksInflight": 0
                                }
                        }
                },
                "elasticsearch": {
                        "1": {
                                "enable": false,
                                "format": "",
                                "url": "",
                                "index": ""
                        }
                },
                "redis": {
                        "1": {
                                "enable": false,
                                "format": "",
                                "address": "",
                                "password": "",
                                "key": ""
                        }
                },
                "postgresql": {
                        "1": {
                                "enable": false,
                                "format": "",
                                "connectionString": "",
                                "table": "",
                                "host": "",
                                "port": "",
                                "user": "",
                                "password": "",
                                "database": ""
                        }
                },
                "kafka": {
                        "1": {
                                "enable": false,
                                "brokers": null,
                                "topic": ""
                        }
                },
                "webhook": {
                        "1": {
                                "enable": false,
                                "endpoint": ""
                        }
                },
                "mysql": {
                        "1": {
                                "enable": false,
                                "format": "",
                                "dsnString": "",
                                "table": "",
                                "host": "",
                                "port": "",
                                "user": "",
                                "password": "",
                                "database": ""
                        }
                },
                "mqtt": {
                        "1": {
                                "enable": false,
                                "broker": "",
                                "topic": "",
                                "qos": 0,
                                "clientId": "",
                                "username": "",
                                "password": ""
                        }
                }
}
`

**Comment by harshavardhana** [comment]
> Clicking on the object in Minio Browser in anonymous mode will send this request:
> 
> {"id":1,"jsonrpc":"2.0","params":{},"method":"Web.CreateURLToken"}

Yes `CreateURLToken` has an implementation bug @vadmeste
