### ISSUE TITLE
Improve tests for fs-v1-multipart.go

### ISSUE THREAD

**Issue by nitisht** [minio/minio#5082]
## Expected Behavior
Tests in [fs-v1-multipart_test.go](https://github.com/minio/minio/blob/master/cmd/fs-v1-multipart_test.go) need to be improved to check for multiple scenarios. 

## Current Behavior
Currently, majority of tests (5/7) check for `faultyDisk` by this logic

```go
	fs.fsPath = filepath.Join(globalTestTmpDir, "minio-"+nextSuffix())
	_, err = obj.NewMultipartUpload(bucketName, objectName, nil)
	if err != nil {
		if _, ok := errorCause(err).(BucketNotFound); !ok {
			t.Fatal("Unexpected err: ", err)
		}
	}
```
The test changes underlying `fsPath` and then `NewMultipartUpload` or other method under test fails with `BucketNotFound`. 

## Possible Solution
Not sure, but either we can improve unit testing to cover other scenarios as well, or extend functional testing in mint to cover several positive/negative scenarios related to multipart uploads.

**Comment by deekoder** [comment]
Unit test can be extended as part of the next mint pod.

**Comment by nitisht** [comment]
we can take this up in future. closing this for now
