### ISSUE TITLE
Minio Server fails to start with a cryptic error message when set up for lambda notification

### ISSUE THREAD

**Issue by deekoder** [minio/minio#5085]
minio server gives a cryptic message while trying to start a minio server set up for lambda notification (config.json). Machine had to be hard powered down and restarted which caused notification.xml to be empty.

```
 ./minio server ~/data
ERRO[0000] Error loading bucket notifications - EOF      cause=EOF source=[event-notifier.go:776:initEventNotifier()]
ERRO[0000] Initializing object layer failed              cause=Unable to initialize event notification. EOF source=[server-main.go:209:serverMain()]
deekoder@deepad:~/work/src/github.com/minio/minio$ ./minio server ~/data
ERRO[0000] Error loading bucket notifications - EOF      cause=EOF source=[event-notifier.go:776:initEventNotifier()]
ERRO[0000] Initializing object layer failed              cause=Unable to initialize event notification. EOF source=[server-main.go:209:serverMain()]
deekoder@deepad:~/work/src/github.com/minio/minio$ go build
deekoder@deepad:~/work/src/github.com/minio/minio$ ./minio server ~/data
ERRO[0000] Error loading bucket notifications - EOF      cause=EOF source=[event-notifier.go:776:initEventNotifier()]
ERRO[0000] Initializing object layer failed              cause=Unable to initialize event notification. EOF source=[server-main.go:209:serverMain()]
deekoder@deepad:~/work/src/github.com/minio/minio$ ./minio server ~/data
ERRO[0000] Error loading bucket notifications - EOF      cause=EOF source=[event-notifier.go:776:initEventNotifier()]
ERRO[0000] Initializing object layer failed              cause=Unable to initialize event notification. EOF source=[server-main.go:209:serverMain()]
deekoder@deepad:~/work/src/github.com/minio/minio$ ./minio server ~/data
ERRO[0000] Error loading bucket notifications - EOF      cause=EOF source=[event-notifier.go:776:initEventNotifier()]
ERRO[0000] Initializing object layer failed              cause=Unable to initialize event notification. EOF source=[server-main.go:209:serverMain()]
```

## Expected Behavior
 Error message should be actionable. Eg. Instruct user to delete the notification.xml and then restart. Infact if notification.xml is empty delete and restart yourself.

## Current Behavior
 See error message

## Possible Solution
  Good would be : show user what to do. An instructive error message to fix and start server.
 Best would be : Do it for the user. Delete notification.xml at server start if notification.xml is empty?

## Steps to Reproduce (for bugs)
1. Set up Minio server for lambda notification
2. go to .minio.sys/bucket remove contents of notification.xml (to simulate)
3. Try starting minio server (see cryptic error  message and server refuses to start)
4.

## Context
 machine crashed and minio server was not restartable after that crash

## Your Environment

* Version used (`minio version`):  

Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET

* Environment name and version (e.g. nginx 1.9.1):  none
* Server type and version: none
* Operating System and version (`uname -a`): Linux deepad 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project: none

**Comment by harshavardhana** [comment]
Actually at io.EOF we can simply ignore the file, we don't need to fail.
