### ISSUE TITLE
Upload using HTTP POST

### ISSUE THREAD

**Issue by tgivslife** [minio/minio#5091]
Hi,

I've been trying to integrate minio server with the Signal application (server/android app).
I managed to make the attachments transmission functional using presigned urls generated by the signal server and the android app uses the PUT method to upload the file.

I've been having problems with the account avatar image functionality. The android app is using POST multipart/form-data to upload the new image with the following body:

AWS S3 Doc http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

```
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="acl"

private
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

profiles/n_Zk5FoVPXsXSgx0pw4JHA
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="policy"

eyAiZXhwaXJhdGlvbiI6ICIyMDE3LTEwLTIwVDA3OjUwOjMxLjU5MFoiLAogICJjb25kaXRpb25zIjogWwogICAgeyJidWNrZXQiOiAic2lnbmFsLXByb2ZpbGVzIn0sCiAgICB7ImtleSI6ICJwcm9maWxlcy9uX1prNUZvVlBYc1hTZ3gwcHc0SkhBIn0sCiAgICB7ImFjbCI6ICJwcml2YXRlIn0sCiAgICBbInN0YXJ0cy13aXRoIiwgIiRDb250ZW50LVR5cGUiLCAiIl0sCgogICAgeyJ4LWFtei1jcmVkZW50aWFsIjogIlM5VDNISjBONVFDSzJUTU9VM0ZQLzIwMTcxMDIwL3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QifSwKICAgIHsieC1hbXotYWxnb3JpdGhtIjogIkFXUzQtSE1BQy1TSEEyNTYifSwKICAgIHsieC1hbXotZGF0ZSI6ICIyMDE3MTAyMFQwNzIwMzFaIiB9CiAgXQp9
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Content-Type"

image/jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-algorithm"

AWS4-HMAC-SHA256
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-credential"

S9T3HJ0N5QCK2TMOU3FP/20171020/us-east-1/s3/aws4_request
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-date"

20171020T072031Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-signature"

85b655a4cccd2aab2b77be1202a6b2b3c7b01bb6c7da6774efed988535d0373a
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="signal-app-ic-launcher.png"
Content-Type: image/png


------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

On the minio server I don't get anything because the the android request gets 403 forbidden

```
10-20 15:52:00.977 30520-4031/org.thoughtcrime.securesms W/CreateProfileActivity: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://host:9000/signal-profiles}
                                                                                      at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:653)
                                                                                      at org.whispersystems.signalservice.internal.push.PushServiceSocket.setProfileAvatar(PushServiceSocket.java:400)
                                                                                      at org.whispersystems.signalservice.api.SignalServiceAccountManager.setProfileAvatar(SignalServiceAccountManager.java:301)
                                                                                      at org.thoughtcrime.securesms.CreateProfileActivity$6.doInBackground(CreateProfileActivity.java:377)
                                                                                      at org.thoughtcrime.securesms.CreateProfileActivity$6.doInBackground(CreateProfileActivity.java:362)
                                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                      at java.lang.Thread.run(Thread.java:764)
```

Can you tell me if upload using http post is supported?

**Comment by nitisht** [comment]
> Can you tell me if upload using http post is supported?

This should work.

@NamingException can you provide Minio server logs, it is available in console where server is running.

**Comment by tgivslife** [comment]
Hi @nitisht ,  

I got it to work.

First I was posting to host:9000 in no particular bucket (my bad), afterwards I mistype the bucket name (no bucket).
After fixing this the request goes through and the file is uploaded in the bucket.

I do get following log while browsing the bucket with the web dashboard, (during my post upload the server does not log anything, working as you said): 

```
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56911 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56910 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56913 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
time="2017-10-21T11:26:33Z" level=error msg="Error in reading from new TLS connection 84.232.207.221:56912 at server 172.17.0.2:9000" cause=EOF source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"

```  

Any idea why the previous log lines are thrown? Not related to upload request just using web dashboard.

**Comment by nitisht** [comment]
> I got it to work.

:+1: 

> Any idea why the previous log lines are thrown?

Have you setup TLS with Minio?

**Comment by tgivslife** [comment]
Yes with certificate from letsencrypt. The browsers says its trusted.

**Comment by vadmeste** [comment]
Thanks for reporting @NamingException, I opened a new issue (https://github.com/minio/minio/issues/5096) to address the new problem. Please close this if you don't have any more questions with your original issue.

**Comment by bunt72** [comment]
Hi @NamingException, could you tell me how to specify bücket name for POST updoad form.
http://<ServerName>:9000/minio/<BucketName> don't work for me. 
Greetings

**Comment by harshavardhana** [comment]
Your URL should look like http://IP:9000/bucketname - IP here is your local address.

Dont use /minio it is a reserved bucket. 

Feel free to join our slack for real time answers https://slack.minio.io

**Comment by bunt72** [comment]
Thank you @harshavardhana, I thought so too. Another question:
We have the same requirements as @NamingException, and want Signal Server software connect to the local Minio Server. Attachments / Presigned-Url work fine, but we have problem using Post  (PostPolicy)

Here is an except of Trace.log (HTTP tracing enabled);

[REQUEST (objectAPIHandlers).PostPolicyBucketHandler-fm] [153280699.567063] [2018-07-28 21:43:15 +0200]
POST /global-securetalk-profiles/
Host: 192.168.2.110:9000
Accept: */*
User-Agent: SecureTalk/1.0 (iPhone; iOS 11.4; Scale/2.00)
Accept-Language: ru-US;q=1, en;q=0.9, de-AT;q=0.8, ru-RU;q=0.7
Content-Length: 100182
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=Boundary+6C9E5C40C6BD7F2D
Connection: keep-alive

--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="bucket"

global-securetalk-profiles
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="key"

profiles/ZLI-B4vuyiXIJmIqZJ0S0A
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="acl"

private
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="x-amz-algorithm"

AWS4-HMAC-SHA256
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="x-amz-credential"

<SECRETKEY>/20180728/us-east-1/s3/aws4_request
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="x-amz-date"

20180728T194315Z
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="policy"

<POLICYDATA>

--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="x-amz-signature"

<SIGNATURE>
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="Content-Type"

application/octet-stream
--Boundary+6C9E5C40C6BD7F2D
Content-Disposition: form-data; name="file"

<FILECONTENT>
--Boundary+6C9E5C40C6BD7F2D--



[RESPONSE] [153280699.567063] [2018-07-28 21:43:15 +0200]
400 Bad Request
Vary: Origin
X-Xss-Protection: "1; mode=block"
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15459FD769EFCC30
Server: Minio/RELEASE.2018-05-04T23-13-12Z (windows; amd64)
Accept-Ranges: bytes
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>POST requires exactly one file upload per request.</Message><Key></Key><BucketName></BucketName><Resource>/global-securetalk-profiles/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>

How can we troubleshot this issue?
Could you help me, please?

**Comment by harshavardhana** [comment]
Please open a new GitHub issue @bunt72
