### ISSUE TITLE
'memory leak' when using multiple minio processes

### ISSUE THREAD

**Issue by fangyuxiangGL** [minio/minio#5110]
1. run two or three minio processes on a server, and put nginx in front of them, which behave as a load balancer
2. start multipart upload objects workload
3. use 'top' to observe memory usage of minio
4. stop the workload after sometime
5. wait golang memory gc for sometime

## Expected Behavior
after 5, memory usage of minio should decrease a lot

## Current Behavior
after 5, memory usage of minio doesn't decrease

## Possible Solution
In this circumstance, parts of object may be delivered to different minio. Provided that, minio PID1 got PART1 and triggered background append goroutine for the object, and minio PID2 got PART2 meantime and also triggered background append goroutine  for the object, but only one goroutine will end, and left the other blocked until timeout(now it is 24 * 60 * 60).

## Steps to Reproduce (for bugs)

1. run two or three minio processes, and put nginx in front of them, which behave as a load balancer
2. start multipart upload objects workload
3. use 'top' to observe memory usage of minio
4. stop the workload after sometime

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Thanks for taking the time on opening the bug @fangyuxiangGL - As per our conversation this issue is persistent and quite reproducible.

FS background append is scheduled for a change, we will be fixing this issue along the lines of this explanation https://github.com/minio/minio/issues/4881 // cc @krishnasrinivas

**Comment by deekoder** [comment]
increased priority

**Comment by krishnasrinivas** [comment]
@fangyuxiangGL 

you can use this in nginx config:
```
upstream backend {
    hash $uri consistent;

    server backend1.example.com;
    server backend2.example.com;
}
```

i.e nginx will load balance based on hash(objectName) hence for a given object, all the requests will go to the same minio server fixing your issue.

**Comment by fangyuxiangGL** [comment]
@krishnasrinivas 

but what is the content of $uri? Does it contain any args of http request, since that args is different even for a given object for multipart upload.

**Comment by fangyuxiangGL** [comment]
@krishnasrinivas 

thanks, i already know the difference between $uri and $request_uri, and will test it.

**Comment by krishnasrinivas** [comment]
@fangyuxiangGL did you try it? did it fix the problem?

**Comment by fangyuxiangGL** [comment]
@krishnasrinivas 

thanks, it fix the problem
