### ISSUE TITLE
ContentType match fails

### ISSUE THREAD

**Issue by nitisht** [minio/minio#5123]
## Expected Behavior
`minio-go` tests pass against s3 gateway mode

## Current Behavior
Test fails on S3 gateway

```json
{"alert":"","args":{"bucketName":"minio-go-testuiu6c5hkc46306qvq","fileName":"","objectName":"minio-go-testuiu6c5hkc46306qvqFPutObject","opts":{"UserMetadata":null,"Progress":null,"ContentType":"application/octet-stream","ContentEncoding":"","ContentDisposition":"","CacheControl":"","EncryptMaterials":null,"NumThreads":0}},"duration":65478,"function":"FPutObject(bucketName, objectName, fileName, opts)","message":"ContentType does not match, expected application/x-gtar, got application/octet-stream","name":"minio-go","status":"fail"}
```

## Possible Solution
--

## Steps to Reproduce (for bugs)
1. Run latest minio master in S3 gateway mode
2. Test `minio-go` functional tests against S3 gateway

**Comment by harshavardhana** [comment]
Just tested everything seems to be working fine? @nitisht

**Comment by kannappanr** [comment]
In the arguments, "ContentType":"application/octet-stream". Why would the error be "ContentType does not match, expected application/x-gtar, got application/octet-stream"?

**Comment by nitisht** [comment]
> In the arguments, "ContentType":"application/octet-stream". Why would the error be "ContentType does not match, expected application/x-gtar, got application/octet-stream"?

This is because args is not updated, that needs fixing as well.

**Comment by nitisht** [comment]
> Just tested everything seems to be working fine? @nitisht

I can consistently reproduce this with minio-go master. Initially I was running a branch, but with `minio-go` latest master, failing test is `testPutObjectReadAt` with same `Content types don't match` error. 

To test, run all the tests from beginning, (you need to comment out ComposeObject tests to avoid https://github.com/minio/mint/issues/194)

		//testComposeObjectErrorCasesV2()
		//testCompose10KSourcesV2()
		//testEncryptedCopyObjectV2()
		//testUserMetadataCopyingV2()

```
{"alert":"","args":{"bucketName":"minio-go-testj1pl2c5e9nvusbxq3","objectContentType":"binary/octet-stream","objectName":"5d6ag9vl0m5yfrm09pap1gg1qjazxr","opts":"objectContentType"},"duration":30454,"function":"PutObject(bucketName, objectName, reader, opts)","message":"Content types don't match","name":"minio-go","status":"fail"}
exit status 1
```

**Comment by nitisht** [comment]
Update: tested with freshly launched S3 gateway, the issue was not reproducible anymore.. `testPutObjectReadAt` passed.

**Comment by harshavardhana** [comment]
We should close if it's not reproducible.
