### ISSUE TITLE
Honor updated Presigned Post Policy

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5133]
Existing post policy is deprecated and new way of setting condition is updated in http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
This is a bug in minio-java and minio server @kannappanr  opened relevant bug https://github.com/minio/minio/issues/5141 , we should close this bug since presigned post policy has not received any new updates and the previous style of using `$eq` to match buckets still work.
