### ISSUE TITLE
Minio behind nginx

### ISSUE THREAD

**Issue by retorquere** [minio/minio#5134]
I have set up minio using [these instructions](https://github.com/minio/minio-service/tree/master/linux-systemd) and have proxied it behind nginx as per [this guide](https://github.com/minio/cookbook/blob/master/docs/setup-nginx-proxy-with-minio.md#non-root-configuration) using this block:

```
  location ~^/ix35-s3 {
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:9199;
  }
```

but when I access `https://<external hostname>/ix35-s3` I get a `NoSuchBucket` error.

What dd I do wrong, and/or where can I find the logs that will help me find out what I did wrong? The logile I pointed minio to from the config.json is created but remains empty, and `journalctl` just shows

```
okt 31 09:32:07 37-97-179-209.colo.transip.net minio[16439]: Created minio configuration file successfully at <home>/.minio
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: Endpoint:  http://127.0.0.1:9199
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: AccessKey: <key>
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: SecretKey: <secret>
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: Browser Access:
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: http://127.0.0.1:9199
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
okt 31 09:32:08 37-97-179-209.colo.transip.net minio[16439]: $ mc config host add myminio http://127.0.0.1:9199 <key> <secret>
```

I'm running CentOS Linux release 7.3.1611 (Core)

**Comment by balamurugana** [comment]
@retorquere I am setting up the env for reproduce the issue mentioned.

**Comment by john-bakker** [comment]
@retorquere when adding /ix35-s3 to your external hostname , are you trying to get to the root of your minio storage, or are you trying to go to the ix35-s3 bucket on your minio storage ? as you configured it above to go to the ix35-s3 bucket in your minio storage running on your http://127.0.0.1:9199

can you try using 

```
  location ~^/ix35-s3 {
    rewrite /ix35-s3(.*) /$1  break;
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:9199;
  }
```

**Comment by krishnasrinivas** [comment]
@retorquere can you set env var MINIO_HTTP_TRACE=1 and run minio. Then try to access the bucket and paste the minio logs?

**Comment by retorquere** [comment]
I'm going to try those both when I'm back in the office -- sorry for the delayed response.

**Comment by retorquere** [comment]
Sorry guys -- super thanks for the help, but it turns out MatLab cannot access S3-compatible buckets, just S3 buckets -- the domain name is hard-coded into matlab 🙄.

**Comment by harshavardhana** [comment]
> Sorry guys -- super thanks for the help, but it turns out MatLab cannot access S3-compatible buckets, just S3 buckets -- the domain name is hard-coded into matlab .

We will have domain based bucket support in the upcoming release, where you configure virtual buckets similar to AWS S3.

**Comment by retorquere** [comment]
I'll give that a go when it drops, but it'd mean I'd have to fiddle with the hosts file to get it to work - mathworks has really hard-coded the domains, and the code is closed-source, so I can't change it.

**Comment by harshavardhana** [comment]
We have made a release with virtual bucket support @retorquere - feel free to close this issue? if nothing is needed from our end.

**Comment by retorquere** [comment]
Nothing needed on my end (blasted mathworks) - I generally only close issues at dev request (I ask my users to do the same),which is why I hadn't already.
