### ISSUE TITLE
Run distributed Minio - Windows

### ISSUE THREAD

**Issue by ghost** [minio/minio#5136]
The command in the document seem to have issues.

minio.exe server http://192.168.1.11/C:/data http://192.168.1.12/C:/data ^
                  http://192.168.1.13/C:/data http://192.168.1.14/C:/data ^
                  http://192.168.1.15/C:/data http://192.168.1.16/C:/data ^
                  http://192.168.1.17/C:/data http://192.168.1.18/C:/data

Not sure if there is an issue with escaping. Minio service never start with the above command. Replaced the IP address with my ip address.

**Comment by harshavardhana** [comment]
Did you directly copy paste? you will have to change the paths appropriately @varun7447

**Comment by harshavardhana** [comment]
Also you need to run exact commands on all nodes exactly,  you also need to make sure that access and secret keys are set properly.

**Comment by ghost** [comment]
Yeah i changed the path 
MinioServiceStart.cmd "http://10.1.1.10/MinioRepository1 http://10.1.1.10/MinioRepository2 http://10.1.1.11/MinioRepository1 http://10.1.1.11/MinioRepository2" XXXXXXXXX XXXXXXXXXXXXX ran it on all nodes. 

I also ran this

MinioServiceStart.cmd "http://10.1.1.10/C:/MinioRepository1 http://10.1.1.10/C:/MinioRepository2 http://10.1.1.11/C:/MinioRepository1 http://10.1.1.11/C:/MinioRepository2" XXXXXXXXXXXX XXXXXXXXXXXXX

both did not work.

**Comment by ebozduman** [comment]
Did it work?

**Comment by harshavardhana** [comment]
> Yeah i changed the path
> MinioServiceStart.cmd "http://10.1.1.10/MinioRepository1 http://10.1.1.10/MinioRepository2 http://10.1.1.11/MinioRepository1 http://10.1.1.11/MinioRepository2" XXXXXXXXX XXXXXXXXXXXXX ran it on all nodes.
> 
> I also ran this
> 
> MinioServiceStart.cmd "http://10.1.1.10/C:/MinioRepository1 http://10.1.1.10/C:/MinioRepository2 http://10.1.1.11/C:/MinioRepository1 http://10.1.1.11/C:/MinioRepository2" XXXXXXXXXXXX XXXXXXXXXXXXX

Can you share MinioServiceStart.cmd ?

**Comment by ghost** [comment]
nssm.exe install minio minio.exe server http://10.1.1.10/C:/MinioRepository1 http://10.1.1.10/C:/MinioRepository2 http://10.1.1.11/C:/MinioRepository1 http://10.1.1.11/C:/MinioRepository2 XXXXXXXXXXXX XXXXXXXXXXXXX
I had to use nssm because i want to run windows service.

**Comment by ghost** [comment]
Even i run the command manually

minio.exe server http://10.1.1.10/C:/MinioRepository1 http://10.1.1.10/C:/MinioRepository2 http://10.1.1.11/C:/MinioRepository3 http://10.1.1.11/C:/MinioRepository4

+--------------------------------------------------------------------------+
| You are running an older version of Minio released 2 months ago          |
| Update: https://dl.minio.io/server/minio/release/windows-amd64/minio.exe |
+--------------------------------------------------------------------------+

time="2017-10-31T22:28:07Z" level=error msg="Initializing object layer failed" cause="CreateFile \\\\?\\C:\\C:\\MinioRepository3: The filename, directory name, or volume label syntax is incorrect." source="[server-main.go:206:serverMain()]"

**Comment by harshavardhana** [comment]
> time="2017-10-31T22:28:07Z" level=error msg="Initializing object layer failed" cause="CreateFile \\?\C:\C:\MinioRepository3: The filename, directory name, or volume label syntax is incorrect." source="[server-main.go:206:serverMain()]"

Looks like a bug and regression @varun7447 we will check and let you know.

**Comment by ghost** [comment]
I also tried with the latest minio.exe. One thing i noticed is without C:/ it is creating the folder. But the Minio is not starting.

**Comment by ghost** [comment]
Ok i guess i got this working. Minio documentation has to be updated. We don't have to specify C:/ in the command prompt in Windows. The command is exactly the same as Linux and Windows.

set MINIO_ACCESS_KEY=<ACCESS_KEY>
set MINIO_SECRET_KEY=<SECRET_KEY>
minio server http://10.1.X.XX/MinioRepository1 http://10.1.X.XX/MinioRepository2 http://10.1.X.XX/MinioRepository3 http://10.1.X.XX/MinioRepository4 http://10.1.Y.YY/MinioRepository1 http://10.1.Y.YY/MinioRepository2 http://10.1.Y.YY/MinioRepository3 http://10.1.Y.YY/MinioRepository4

Note: Initially i had only 4 drives, 2 on each node. Looks like we need 4 drives on each node.

**Comment by ghost** [comment]
Is there a reason why we are not providing Windows service out of the box with Minio Windows exe?

**Comment by harshavardhana** [comment]
> Is there a reason  why we are not providing Windows service out of the box with Minio Windows exe?

nssm serves the purpose @varun7447  and we didn't want to enforce a mechanism in this area.  Most orchestration platforms like docker already provide this for windows as well.

**Comment by harshavardhana** [comment]
> Ok i guess i got this working. Minio documentation has to be updated. We don't have to specify C:/ in the command prompt in Windows. The command is exactly the same as Linux.

Oh this is great to know @varun7447 - thanks.

**Comment by ghost** [comment]
Can we confirm if it is ok to use without C:/ in the server command?

**Comment by harshavardhana** [comment]
> Can we confirm if it is ok to use without C:/ in the server command?

For non C:\ we need to see how this behaves, there is still a bug and we should honor `C:\`

**Comment by ghost** [comment]
But the issue is with C:/ I am unable to start Minio itself..

**Comment by harshavardhana** [comment]
> But the issue is with C:/ I am unable to start Minio itself..

I agree we need to fix it @varun7447 its a regression.

**Comment by harshavardhana** [comment]
The culprit was in `endpoint.go` where we need to make sure that on windows we need to trim the paths properly.

**Comment by ghost** [comment]
We still need to run the command as C:/ ?

**Comment by harshavardhana** [comment]
Do not understand your question to clarify following styles will be supported

- http://192.168.1.2/C:/test1 (common style)
- http://192.168.1.2/C:\test1 (common canonical style)
- http://192.168.1.2/\\net\share\vol (network share as backend)
- http://192.168.1.2/test1 (relative path to C:\ or whatever is current working directory)

**Comment by ghost** [comment]
Last week when I tested with C:/test the minio was not starting up. 

The only style that worked was http://localhost/test.

**Comment by harshavardhana** [comment]
> Last week when I tested with C:/test the minio was not starting up.
> 
> The only style that worked was http://localhost/test.

@varun7447 PR #5152 fixes your issue. We know it didn't work for you last week, but it is expected to support the above mentioned styles.

**Comment by ghost** [comment]
Will test and let you know the results..
