### ISSUE TITLE
Android system version is less than 5, not by Minio upload and download the APK package

### ISSUE THREAD

**Issue by yunyunchen** [minio/minio#5140]
Android system version is less than 5, not by Minio upload and download the APK package，

Try to download again

**Comment by nitisht** [comment]
@yunyunchen can you please rephrase? It is not clear what is the question here.

**Comment by yunyunchen** [comment]
@nitisht 
Using golang to compile directly, found the following problems：

`[root@i-tp6apg01 mnt]# curl -v https://***.***.com:9000/health/2.0.0%20beta7.apk
* About to connect() to  ***.***.com port 9000 (#0)
*   Trying 139.***.***.***...
* Connected to mops-oss-dev.lianluo.com (139.***.***.***) port 9000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12190 (SSL_ERROR_PROTOCOL_VERSION_ALERT)
* Peer reports incompatible or unsupported protocol version.
* Error in TLS handshake, trying SSLv3...
> GET /health/2.0.0%20beta7.apk HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ***.***.com:9000
> Accept: */*
> 
* Connection died, retrying a fresh connect
* Closing connection 0
* Issue another request to this URL: 'https://***.***.com:9000/health/2.0.0%20beta7.apk'
* About to connect() to ***.***.com port 9000 (#1)
*   Trying 139.***.***.***...
* Connected to ***.***.com (139.***.***.***) port 9000 (#1)
* TLS disabled due to previous handshake failure
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12190 (SSL_ERROR_PROTOCOL_VERSION_ALERT)
* Peer reports incompatible or unsupported protocol version.
* Closing connection 1
curl: (35) Peer reports incompatible or unsupported protocol version.
`

minio service logs:

ERRO[0049] TLS handshake failed with new connection 139.198.9.***:34677 at server 192.168.0.94:9000  cause=tls: client offered an unsupported, maximum protocol version of 301 source=[listener.go:170:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]
ERRO[0049] TLS handshake failed with new connection 139.198.9.***:34678 at server 192.168.0.94:9000  cause=tls: client offered an unsupported, maximum protocol version of 300 source=[listener.go:170:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]

ps: tls1.0 false
tls1.2 true

**Comment by nitisht** [comment]
Thanks @yunyunchen can you please let us know

- Minio version you are using
- How did you set up TLS (have you seen https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls)

**Comment by yunyunchen** [comment]
@nitisht 

- I didn't find how to look at its version.Is it this?

`
#minio update
You are already running the most recent version of ‘minio’.

#minio version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET

`

- TLS is configured according to this document. It is configured correctly. I confirm it

**Comment by nitisht** [comment]
Looks like you are running from master. Can you please try the latest release instead, it is available here https://minio.io/downloads.html#download-server-linux-x64

**Comment by yunyunchen** [comment]
@nitisht I want Install from Source or docker，can you give me link？

**Comment by harshavardhana** [comment]
> ERRO[0049] TLS handshake failed with new connection 139.198.9.***:34677 at server 192.168.0.94:9000 cause=tls: client offered an unsupported, maximum protocol version of 301 source=[listener.go:170:github.com/minio/minio/pkg/http.(httpListener).start.func2()]

@yunyunchen we only support TLS 1.2 and above if your android client is using TLS 1.1 we won't work.   here are things we need from your end

  - curl --version
  - uname -a (your system information) (kernel version)

You can try accessing from curl using `curl --tlsv1.2` if you wish to force TLS 1.2

**Comment by yunyunchen** [comment]
@harshavardhana 
you‘re right.

```
#curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.15.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz 

#uname -a
Linux i-97vd9q5e 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

curl --tlsv1.2 is true,but I'd like to know how to support tls1.2 below

**Comment by harshavardhana** [comment]
You cannot know @yunyunchen more recent versions of curl use TLS 1.2 as default. 

```
curl --version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) librtmp/2.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy PSL 
```

**Comment by nitisht** [comment]
If there is nothing else to be addressed, feel free to close the issue @yunyunchen
