### ISSUE TITLE
Add new flag --force-remove to mirror command

### ISSUE THREAD

**Issue by mati865** [minio/minio#5144]
## Expected Behavior

I have no idea why `Delete is not allowed ...` appears but it doesn't matter.

It should have option to force remove but don't overwrite files.

## Current Behavior

When running `mirror --remove` there are warnings `{Delete,Overwide} not allowed for <filename>. Use `--force` to override this behavior.`

Using `--force` will allow to delete files as expected but it will also overwrite all files.

## Possible Solution

Flag `--force-remove` would leave existing files would not overwrite existing files and remove extraneous files.

## Context

Mirror files from local directory to the bucket.

## Your Environment

* Version used (`minio version`): 2017-09-29T19:16:56Z
* Environment name and version (e.g. nginx 1.9.1): go1.8.3
* Server type and version:
* Operating System and version (`uname -a`): Linux (don't have access to the server)
* Link to your project:

**Comment by vadmeste** [comment]
I don't think --force here has another meaning other than override (we need to check it anyway), but in the case, I think it would be better to rename --force to --override instead. That way we can also keep --remove flag.

**Comment by vadmeste** [comment]
We should discuss if we are okay with this change.

**Comment by mati865** [comment]
I don't mind as long as I can force deletion without overwriting.

**Comment by harshavardhana** [comment]
We should close this issue here and open on github.com/minio/mc

**Comment by mati865** [comment]
Sorry, my bad.
