### ISSUE TITLE
'The specified bucket is not valid' when creating bucket in web browser

### ISSUE THREAD

**Issue by kaizenlabs** [minio/minio#5145]
Trying to just create a bucket running a Minio server locally on my Mac, I can create a bucket via the command line (MC), but when I try to do it through the browser UI, I keep getting 'The specified bucket is not valid'...can someone help?

**Comment by nitisht** [comment]
@JohnAntonusMaximus can you please tell us 

- Minio version you are using
- Bucket name you are trying to create

**Comment by kaizenlabs** [comment]
Hi @nitisht, I can't tell what version of minio because there is no -v or --version flag to pass, but I'm assuming latest since I pulled it only yesterday. Name of the bucket is just 'Test' or 'Vision', but also 'Vision1234' doesn't work either.

**Comment by nitisht** [comment]
>  I can't tell what version of minio because there is no -v or --version flag to pass,

You can find version using `$ minio version`

> Name of the bucket is just 'Test' or 'Vision', but also 'Vision1234' doesn't work either.

Minio adheres to AWS S3 standards and as per S3 API, _"Bucket names can contain lowercase letters, numbers, and hyphens"_ (ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) Can you please try `test`, `vision`, `vision1234`

**Comment by kaizenlabs** [comment]
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET

**Comment by nitisht** [comment]
Thanks @JohnAntonusMaximus . Can you please try bucket names without capital letters, and let us know?

**Comment by kaizenlabs** [comment]
@nitisht, yes that worked, thank you for the reminder on that. I have another question for you since you seem to be very knowledgeable on this...is there a way that I can create multiple users on minio and restrict their bucket access according to user permissions (like AWS bucket policies)?

**Comment by nitisht** [comment]
> is there a way that I can create multiple users on minio and restrict their bucket access according to user permissions (like AWS bucket policies)

Minio allows one user per instance, so multiple users are not possible. Minio does support bucket policies for anonymous requests - here is a [brief primer](https://gist.github.com/harshavardhana/400558963e4dfe3709623203222ed30c).

**Comment by kaizenlabs** [comment]
@nitisht, ok, then can I launch multiple minio server instances across the same mounted hard drives to achieve this effect? Or would I need to implement this user login in front of minio as a custom solution using the one minio access key and secret key?

**Comment by nitisht** [comment]
In general we recommend adding multiple minio instances, one for each tenant (a tenant is loosely defined, here it may be a user, an application or other entity that needs to store its data - based on your needs).

However, if you need to share data across multiple users you can also take a look at [presigned URLs](https://docs.minio.io/docs/golang-client-api-reference#PresignedGetObject). 

> I launch multiple minio server instances across the same mounted hard drives to achieve this effect

you can do that as well, but this may not scale very well as the higher the number of Minio instances performing I/O on a single drive, the slower it will be. 

> I need to implement this user login in front of minio as a custom solution using the one minio access key and secret key

This is probably a better approach than sharing drives.

**Comment by nitisht** [comment]
@JohnAntonusMaximus if there is nothing else to address, feel free to close the issue

**Comment by ddzialak** [comment]
> Minio adheres to AWS S3 standards and as per S3 API, "Bucket names can contain lowercase letters, numbers, and hyphens" (ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) Can you please try test, vision, vision1234

Is `minio` supporting `US East` region? According to referenced page:
> These conventions are enforced in all Regions except for the US East (N. Virginia) Region.

My point is about underscore in bucket name.

**Comment by krisis** [comment]
@ddzialak `minio` uses region in the context of authenticating requests. Beyond this region doesn't mean anything to `minio`. So, minio doesn't support region-specific restrictions like AWS S3. AWS S3 does it for backward compatibility reasons and encourages use of DNS compliant bucket names.

An important reason to support bucket naming restrictions that apply to newer regions (and not us-east-1) is to avoid any surprises for users when they backup objects from minio to AWS S3 in any region including us-east-1.

**Comment by krisis** [comment]
Closing this since it is a non-issue. Feel free to open if you feel otherwise.

**Comment by YasminBZ** [comment]
Hello, 

please i'm having this error when trying to create a bucket:
./mc config host add myminio http://172.16.51.3:9000 YBSAVEJ8KK16B42SESRR iDIERFMSaGkDeGK+YASXywMslZLJjB0dREDqEemC foobar
Added `myminio` successfully.
 and then i get this error:
mc: <ERROR> Unable to make bucket `myminio/foobar`. The specified bucket does not exist.
what this error means please , i'm stuck in this error since two days, don't know how to resolve it 
Any suggestions please.

Thank you.

**Comment by harshavardhana** [comment]
@white-cloud `mc config host add` doesn't create a bucket it is simply to register a new alias in `mc` config.json, additionally please open a separate GitHub issue this issue is closed and archived.
