### ISSUE TITLE
Feature: Go API for starting embedded Minio server

### ISSUE THREAD

**Issue by jawnsy** [minio/minio#5146]
## Background

Minio is currently designed to be started exclusively directly as an application, and the command-line interface is considered to be the user-facing interface for starting a server. It also focuses on production applications, and as such, expects to be provided a path on the filesystem to store files.

There does not currently appear to be any public Go API for starting a Minio server.

## Requirement

Programs that utilize Minio for storage currently have a few options:

1. Require Minio to be available and started when running integration tests. This means that machines must be preconfigured (in the case of continuous integration servers) and developers must manually set up Minio.

1. Tests can be configured to point to a test server, either an internal one set up for this purpose, or the Minio playground. Since the server is shared, this is likely to lead to flaky tests, results in a single point of failure, and doesn't work if the developer is offline.

1. Another library like [GoFakeS3](https://github.com/johannesboyne/gofakes3) can be used. This has the disadvantage that behavior may not be completely compatible with Minio. Test results are therefore only advisory: bugs in GoFakeS3 may not affect Minio, and vice versa, so tests always need to be re-executed on a real Minio server prior to release.

1. Code can be written to start `minio` as part of the test suite, as [restic does](https://github.com/restic/restic/blob/faadbd734b23ba60d6b8cae2e6347b6dabee8c47/internal/backend/s3/s3_test.go#L32). However, this boilerplate code then has to be maintained across all the projects that use Minio. Additionally, since it executes any `minio` binary in the system PATH, special care has to be taken to arrange for the correct binary to be available beforehand.

1. Code using Minio can be extracted into another interface, and then mocked out entirely. This would work well for unit tests, but integration tests would benefit from the greater assurance of talking to a "real" Minio server.

## Proposal

I propose some sort of public Go API that can be used to start a Minio server, possibly in a special "test mode" that can preconfigure a Minio server and client instance and return it. This seems like it would effectively entail extracting some of the code in https://github.com/minio/minio/blob/master/cmd/server-main.go and moving it to an importable package, possibly `github.com/minio/minio/pkg/http`. It looks like this package already includes some useful utilities, particularly `http.NewServer` in `server.go`, but it's unclear to me whether this would actually be enough to start an embedded server.

[ginkgo](https://github.com/onsi/ginkgo) has facilities to ensure setup/teardown code is called before and after the test suite runs (BeforeSuite/AfterSuite) and starting the server in this way means that multiple fully-isolated servers could even be started in parallel. Even when only starting a single server, the variants SynchronizedBeforeSuite and SynchronizedAfterSuite can be used instead.

## Benefits

By providing a documented, public Go API for starting and stopping an embedded Minio server, new developers can be onboarded more quickly (as the test will be self-contained.) As the `minio` server code can be vendored, this enables greater reproducibility for integration tests as well.

## Prior Art

* Kubernetes provides an [E2E Testing Framework](https://github.com/kubernetes/kubernetes/blob/cc49b34d290b90a45177755092b126e331cfa86a/test/e2e/framework/framework.go#L125) which hooks into ginkgo and provides a preconfigured Kubernetes go client (`k8s.io/client-go/kubernetes`) instance. There are similar utilities in related projects; for example: [kubernetes/apiextensions-apiserver](https://github.com/kubernetes/apiextensions-apiserver/blob/51a1910459f074162eb4e25233e461fe91e99405/test/integration/testserver/start.go#L37)
* OpenShift provides a [StartTestMaster](https://github.com/openshift/origin/blob/c21a4709fd612345e6a732874a3ccd2cbaf1eaa6/test/integration/extension_apiserver_test.go#L17) utility function

The Kubernetes tests start an embedded etcd server and selectively stub out infrastructure depending on the system under test. For example, `hollowmark` is a benchmark that tests performance of the API server only rather than benchmarking a container engine's ability to create and destroy containers. This speeds up performance test runs, reduces variability, and allows them to be more targeted, since the API server and container engine can be benchmarked in isolation.

**Comment by harshavardhana** [comment]
@jawnsy Thanks for the detailed github issue. 

Before going into the details i would like to say that it is quite common to use Minio server to test S3 compatibility for your application needs which eventually uses AWS S3.  But it is also true that Minio server is not just a Fake S3 like application instead its a full storage system to manage large quantities of your data. 

With that in mind providing an API which allows minio server to look like sort of a pkg/http/httputil sort of a package (comparing parallels here with httpTestServer implementation by Go) is not really the intention  of Minio, also we haven't designed / written the code to facilitate this. 

Even with lack of such an API popular projects like restic (https://github.com/restic/restic/blob/master/run_integration_tests.go), s3cmd (https://github.com/s3tools/s3cmd/blob/master/run-tests-minio.py)
already employ a much simpler technique i.e by simply running minio server while running integration tests.

With Minio server being small and simple to run it is perfectly designed to be part of your application stack. You don't need a special API to do this for you, neither does Minio needs to over compensate by implementing itself like a package. 

We will certainly discuss this internally since its an important use case for you, with the detailed finer points of requirement what you have stated in this issue. Will let you know

**Comment by nitisht** [comment]
Blocked till further discussion

**Comment by harshavardhana** [comment]
So what we decided was you can simply do the following for a static compilation into your code base.

```go 
package main                                                                    
                                                                                
import minio "github.com/minio/minio/cmd"                                       
                                                                                
// StartMinio -                                                                 
func StartMinio() {                                                             
        minio.Main([]string{                                                    
                "--address :9001",                                              
                "server",                                                       
                "/tmp/server",                                                  
        })                                                                      
}                                                                               
                                                                                
func main() {                                                                   
        go StartMinio()           
       ---> do your thing <---                                                 
}
```

**Comment by jawnsy** [comment]
@harshavardhana That approach is better than nothing, but still has some limitations:

1. The configuration file needs to be available somewhere beforehand, meaning additional code to write one somewhere and refer to it from the minio.Main invocation. This applies for the configuration of both the server and client (which access key & secret key to use)

1. There doesn't seem to be an easy way to signal Minio to stop

1. It requires files to be written to disk (e.g. if Minio used an abstraction layer like https://github.com/spf13/afero, then it could run embedded in-memory only)

How does Minio manage its integration tests today?

**Comment by harshavardhana** [comment]
> The configuration file needs to be available somewhere beforehand, meaning additional code to write one somewhere and refer to it from the minio.Main invocation. This applies for the configuration of both the server and client (which access key & secret key to use)

Not really you can simply set the ENVs 

> There doesn't seem to be an easy way to signal Minio to stop

You can simply stop it by using pkg/madmin API after this refactor gets merged https://github.com/minio/minio/pull/4826/files#diff-457830409c3192b41ef7843a4f3ebda1R82 

> It requires files to be written to disk (e.g. if Minio used an abstraction layer like https://github.com/spf13/afero, then it could run embedded in-memory only)

This is hardly a problem really you can simply mount `ramfs`  and then point minio to use that. 

> How does Minio manage its integration tests today?

https://github.com/minio/mint

**Comment by vtolstov** [comment]
Does things changed after this? I think about embeding too.
