### ISSUE TITLE
http: request body too large

### ISSUE THREAD

**Issue by wekay102200** [minio/minio#5147]
when upload object which file size exceed 10GB，occur upload problem below:
/opt/env/falcon/src/github.com/Genetalks/gtxstorage/1111/.gtxstorage.sys/tmp/8549454d-920b-40c1-a85a-dc24c684b98a/f27cc1a3-4e04-40cc-aa90-2d850c182f91
ERRO[5970] Failed to create object rrrr/00-All.vcf       cause=http: request body too large source=[fs-v1.go:640:fsObjects.PutObject()] stack=fs-v1-helpers.go:306:fsCreateFile fs-v1.go:637:fsObjects.PutObject <autogenerated>:1:(*fsObjects).PutObject web-handlers.go:581:(*webAPIHandlers).Upload web-router.go:85:(*webAPIHandlers).Upload-fm
ERRO[5970] Unexpected error, please report this issue at https://github.com/minio/minio/issues  cause=http: request body too large source=[web-handlers.go:1137:toWebAPIError()]

How to upload huge file object to web server?

**Comment by krishnasrinivas** [comment]
Uploading 10G from web-ui works fine for me. Can you fill up the issue template that you see here?: https://github.com/minio/minio/issues/new
