### ISSUE TITLE
http: request body too large

### ISSUE THREAD

**Issue by wekay102200** [minio/minio#5148]
## Expected Behavior

upload file successful

## Current Behavior

my upload file size is 26G,but when upload exceed 15G size,it occurs problem below:
ERRO[5970] Failed to create object rrrr/00-All.vcf cause=http: request body too large source=[fs-v1.go:640:fsObjects.PutObject()] 
![default](https://user-images.githubusercontent.com/18589915/32433929-981b984a-c317-11e7-9b85-995f3561b10b.png)

## Possible Solution

multipart uploads

## Steps to Reproduce (for bugs)

1.upload 20G file to web server via web client.
2.
3.
4.

## Context

when upload object which file size exceed 15GB，occur upload problem below:
/opt/env/falcon/src/github.com/Genetalks/gtxstorage/1111/.gtxstorage.sys/tmp/8549454d-920b-40c1-a85a-dc24c684b98a/f27cc1a3-4e04-40cc-aa90-2d850c182f91
ERRO[5970] Failed to create object rrrr/00-All.vcf cause=http: request body too large source=[fs-v1.go:640:fsObjects.PutObject()] stack=fs-v1-helpers.go:306:fsCreateFile fs-v1.go:637:fsObjects.PutObject :1:(*fsObjects).PutObject web-handlers.go:581:(*webAPIHandlers).Upload web-router.go:85:(*webAPIHandlers).Upload-fm
ERRO[5970] Unexpected error, please report this issue at https://github.com/minio/minio/issues cause=http: request body too large source=[web-handlers.go:1137:toWebAPIError()]

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by krishnasrinivas** [comment]
we have this limit
```
        globalMaxObjectSize = 16 * humanize.GiByte                                                      
```

It is convenient for web-UI to not honour this limit as web-UI does not do multipart. What do you think @harshavardhana

**Comment by harshavardhana** [comment]
> It is convenient for web-UI to not honour this limit as web-UI does not do multipart. What do you think @harshavardhana

@krishnasrinivas was thinking about this too, we can bump the size limit here to 5TiB, but it is not an ideal way to upload such large files using browser.   Personally i think `mc cp` is a better choice here for file sizes beyond 16GiB.

**Comment by harshavardhana** [comment]
This is waiting on discussion with @abperiasamy to bump incoming request side to 5TiB

**Comment by wekay102200** [comment]
@krishnasrinivas @harshavardhana thanks very much.I also think the 16GB limit size is too small,We can let the limit size higher.

**Comment by harshavardhana** [comment]
> @krishnasrinivas @harshavardhana thanks very much.I also think the 16GB limit size is too small,We can let the limit size higher.

AWS S3 has a limit of 5GiB per PutObject() what we have right now is bigger.  You can use client side `mc cp` to do multipart transfer which can upload till 5TiB.  Browser code was left to be simpler because, browser is hardly a good tool to upload large files.

**Comment by wekay102200** [comment]
@krishnasrinivas @harshavardhana I use your tool in inner net environment, the net speed is very fast.so upload large files is feasible.
