### ISSUE TITLE
Folder within a bucket and associated ops support using JAVA SDK

### ISSUE THREAD

**Issue by vrock28** [minio/minio#5151]
Hi,

The Minio JAVA SDK documentation doesn't clearly articulate how to create a folder inside a bucket. Can somebody help me on this request ? I am mainly trying to implement ops to create & delete folder and also trying to figure out the AWS equivalent for ListObjectsV2Request() and ListObjectsV2() API support in minio.

Thanks in Advance!

**Comment by nitisht** [comment]
@vrock28 you can simply pass the directory structure as a part of `objectName` and Minio will create the directories. For example

```java
MinioClient minioClient = new MinioClient("http://localhost:9000", "minio", "minio123");
String bucketName = "my-bucket";
String objectName = "make/directory/and/store/object.txt";
minioClient.putObject(bucketName,objectName, "/path/to/file/object.txt");
```

Minio equivalent of ListObjectsV2() API is `listObjects` (Ref: https://docs.minio.io/docs/java-client-api-reference#listObjects)

**Comment by nitisht** [comment]
For further issues related to Java SDK, please file issues here : https://github.com/minio/minio-java/issues/new

**Comment by vrock28** [comment]
@nitisht : Thanks for the quick response. Would this also work ?

`minioClient.putObject(bucketName, "dir1/");`

**Comment by nitisht** [comment]
> Would this also work ? `minioClient.putObject(bucketName, "dir1/");`

No, that is not a valid putObject call. You can see the available putObject method here: http://minio.github.io/minio-java/io/minio/MinioClient.html

**Comment by vrock28** [comment]
OK so i understand that we have the facility to implicitly create a directory structure as you showed earlier but it looks like i cannot create an empty folder under a bucket right ?

Would this work for me ?
`MinioClient minioClient = new MinioClient("http://localhost:9000", "minio", "minio123");
String bucketName = "my-bucket";
String objectName = "dir1/object.txt";
minioClient.putObject(bucketName,objectName);`

Whats the "/path/to/file/object.txt" when we intend to create the object under a path within the bucket itself ?

**Comment by vrock28** [comment]
AFter a bit of doc study, i get it.  The "/path/to/file/object.txt" is the location of the file in our local filesystem which we want to do a PUT of to minio.

**Comment by nitisht** [comment]
> Whats the "/path/to/file/object.txt" when we intend to create the object under a path within the bucket itself ?

` "/path/to/file/object.txt"` this is the path to the file to be uploaded. 

While `"dir1/object.txt"` is the path where object will be kept inside the bucket (in Minio server)

**Comment by nitisht** [comment]
Feel free to close the issue if there is nothing else to be addressed. You can also talk to us on Slack
https://slack.minio.io

**Comment by vrock28** [comment]
Sure. Let me use the slack to discuss more on what i need. Thanks for the help. Closing this thread.
