### ISSUE TITLE
`Authorization` header that comes from another application on same domain causes GET to fail

### ISSUE THREAD

**Issue by pszabop** [minio/minio#5155]
When testing on localhost, my application issues a redirect to minio but my application is already using the `Authorization` HTTP header that thus gets sent to minio by the client following the redirect (to a different port).  Even though I have not configured any Authorization for minio, minio rejects what it thinks is an invalid `Authorization` HTTP header.  Is there a way to disable this check?  Removing the `authorization` header will be difficult because my client (modified superagent/supertest)  automatically inserts the header based on cookie domain.. (aka the host, which is of course `localhost` when testing.  

TL;DR:  If using minio alongside another application on the same domain, a client that inserts an `Authorization` header for a domain and receives a redirect from the application to minio will cause minio to receive an authorization header it doesn't like, and the redirect fails with a 401.

TL:DR - TL:DR:  The `Authorization` header has namespace collision issues because everyone is using the same header for their apps, breaking redirects between apps on the same host.

## Expected Behavior
If minio isn't expecting an `Authorization` header, it shouldn't be checking for one.

## Current Behavior
* this fails: 

`curl -H "Authorization: foo"  http://cdn_ut:9000/cdn/db663ffb-fe83-4fe8-b1e0-6f1e400b57a2.jpeg `

* this succeeds:  

`curl  http://cdn_ut:9000/cdn/db663ffb-fe83-4fe8-b1e0-6f1e400b57a2.jpeg`

But I have not configured any authorization features for minio.  I've configured global readability for the `cdn` bucket

## Possible Solution
1.  Make authorization checks configurable
1.  Make authorization header name configurable.  It seems unhealthy for all applications to be using the `Authorization` header.  Perhaps the header name should be `Authorization-<application_identifier>`

## Steps to Reproduce (for bugs)
See Current Behavior above for a direct reproduction.

superagent debug output from my redirecting application (far to complicated to reproduce entirely)

```
  superagent GET http://127.0.0.1:41107/pictures/66580aff-ec28-4ec2-84aa-bc4a67087e93.jpeg -> 302 +7ms
  superagent redirect http://127.0.0.1:41107/pictures/66580aff-ec28-4ec2-84aa-bc4a67087e93.jpeg -> http://cdn_ut:9000/cdn/db663ffb-fe83-4fe8-b1e0-6f1e400b57a2.jpeg +0ms
  superagent GET http://cdn_ut:9000/cdn/db663ffb-fe83-4fe8-b1e0-6f1e400b57a2.jpeg +2ms
  superagent GET http://cdn_ut:9000/cdn/db663ffb-fe83-4fe8-b1e0-6f1e400b57a2.jpeg -> 401 +2ms
```

## Context
I have a client (supertest/superagent) that automatically inserts an `Authorization` header for an application when given an `Authorization` cookie, to prevent CSRF attacks.   When this client gets an HTTP redirect to Minio, Minio receives an `Authorization` header it doesn't recognize.

It seems to me there's a serious namespace issue with `Authorization` headers being used by multiple apps on the same domain...

## Your Environment

```
VERSION:
Version: 2017-01-25T03:14:52Z
Release-Tag: RELEASE.2017-01-25T03-14-52Z
Commit-ID: f8e4700a11065967242b8857045ce7dee607722d
```

Running on Docker on OSX.  (all latest)

**Comment by harshavardhana** [comment]
It is an incorrect implementation to keep the Authorization header from a different request after redirect, if Authorization is needed then redirect call back should re-authorize the request to the new destination with proper AWS S3 signature. If you wish to do anonymous request then please remove the authorization header in your redirect callback code. 

Here is how AWS S3 also behaves 

```
curl -H "Authorization: foo" https://s3.amazonaws.com/vadmeste
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Authorization header is invalid -- one and only one ' ' (space) required</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>foo</ArgumentValue><RequestId>ADFEE7ECC3FF2688</RequestId><HostId>1ZBqaBQWJxXwPPbhCAe8xKVBAsVXcPXUBDIxthvqVe8EfDMKgHtCSu6kZrG+yLPk4GMP/jlMTsc=</HostId></Error>
```

Minio responds with following
```
 curl -H "Authorization: foo" https://play.minio.io:9000/testbucket
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

AFAICS this is not a minio issue,  this is a client implementation bug.

**Comment by harshavardhana** [comment]
> VERSION:
> Version: 2017-01-25T03:14:52Z
> Release-Tag: RELEASE.2017-01-25T03-14-52Z
> Commit-ID: f8e4700a11065967242b8857045ce7dee607722d

Also please upgrade to latest looks like your minio version is like almost a 1yr old.

**Comment by pszabop** [comment]
Agreed this is a [client bug](https://github.com/visionmedia/superagent/issues/1309),  but I would appreciate a formal reference (e.g. RFC) on this requirement, because other than some vulnerabilities posts, it's hard to find a formal reference (e.g. RFC) on what headers should be stripped on redirects.

**Comment by krishnasrinivas** [comment]
Could not find any formal reference on this. We are behaving in a similar manner as AWS-S3. Also you agree that this is a client bug.

**Comment by pszabop** [comment]
I can't argue with "behaving in a similar manner as AWS-S3".

**Comment by harshavardhana** [comment]
> Agreed this is a client bug, but I would appreciate a formal reference (e.g. RFC) on this requirement, because other than some vulnerabilities posts, it's hard to find a formal reference (e.g. RFC) on what headers should be stripped on redirects.

The general rule is this https://golang.org/src/net/http/client.go?s=16518:16570#L830  - only send Authorization, Cookie to only if the redirection is to sub-domains, assumption is that the domain and sub-domains would be pointing to same service.

**Comment by pszabop** [comment]
Golang's http client is hardly a formal reference, but thanks.  I note the superagent nodejs client doesn't handle subdomains correctly, just exact matches the host...  (good enough for me for now).

**Comment by harshavardhana** [comment]
> Golang's http client is hardly a formal reference, but thanks. I note the superagent nodejs client doesn't handle subdomains correctly, just exact matches the host... (good enough for me for now).

Yes its not a formal reference but can be seen what other HTTP clients are doing, perhaps this can be suggested on the issue on superagent @pszabop
