### ISSUE TITLE
From single node deployment to cluster

### ISSUE THREAD

**Issue by mhemrg** [minio/minio#5159]
Is it possible to migrate from single node deployment to cluster mode without loosing previous data?

**Comment by harshavardhana** [comment]
yes you can using `mc mirror` from single node to cluster mode.

**Comment by ebozduman** [comment]
@mhemrg ,
Thank your for your interest and question.
It looks like you can close this issue since @harshavardhana's comment answered your question. 

Please also feel free to use Slack to ask questions and clarifications instantly.
