### ISSUE TITLE
Restriction for object name consistent with documentation

### ISSUE THREAD

**Issue by ddzialak** [minio/minio#5161]
## Expected Behavior
Description of `XMinioInvalidObjectName` in doc should correspond to `minio` behavior. It would be wonderful if restrictions are the same as in AWS S3 service.

## Current Behavior
According to doc at minio/docs/admin-api/README.md:
```
<Error>
    <Code>XMinioInvalidObjectName</Code>
    <Message>Object name contains unsupported characters. Unsupported characters are `^*|\&#34;</Message>
... 
```
but it looks like `XMinioInvalidObjectName` is returned if there is `\` in object name
and `PutObject` also fail with `BucketAlreadyOwnedByYou` if name contains `\n` (new line).

## Possible Solution
- Update doc to be consistent with minio behavior.
- Allow for backslash and new line character in object names (as it is in S3)

## Steps to Reproduce (for bugs)
1. Try to create object `foo\bar` or `foo\nbar` (both will fail with different errors)
2. Try to create object `^*|\"` (it will succeed)

## Context
Want to copy filesystem with paths where all characters are allowed (except `\0`) into S3 object store.

## Your Environment
I'm running minio from docker:
root@ubuntu:~# docker run minio/minio minio version
Version: 2017-10-27T18:59:02Z
Release-Tag: RELEASE.2017-10-27T18-59-02Z
Commit-ID: 03df692ae2f911943d5ef98b0ee2f9461605fb8c

with command `minio server /srv` where `/srv` is mapped to host `/var/lib/s3minio` that is normal ext3 directory.

**Comment by kannappanr** [comment]
@ddzialak Sorry for getting back late on this. I tried all three steps you had suggested to reproduce the issue. I was unable to reproduce using any of them.
`foo/bar` created the object successfully. I believe that this is a typo and tried `foo\bar` and that failed with the `XMinioInvalidObjectName` error.

Then I tried `foo\nbar` and `^*|\&#34;` , both of them failed with `XMinioInvalidObjectName` error.

Here is the sample Python code that I used to test.

```import os

from minio import Minio
from minio.error import ResponseError

client = Minio('localhost:9000',
               access_key='minio',
               secret_key='minio123',
               secure=False)

# Put a file with default content-type.
try:
    file_stat = os.stat('/home/admin/minio_test')
    file_data = open('/home/admin/minio_test', 'rb')
    client.put_object('test', "foo\\nbar", file_data, file_stat.st_size)
except ResponseError as err:
    print(err)
```
Note that in Python, you have to escape to make sure that the `\` shows up.

**Comment by kannappanr** [comment]
@ddzialak Can you please let us know, if you are fine with the explanation? If not, can you elaborate more on the steps you used to reproduce the issue?

**Comment by ddzialak** [comment]
@kannappanr  is `XMinioInvalidObjectName` raised by Minio client? I've reproduced the same with boto library and successfully created object named: `object[^*|"]` (so none of these chars is forbidden by server)
```
(sf2) dzialak@tad-38 ~/PycharmProjects/minio $ python  ../_extras_/custom-s3-req.py  s3cfg.minio 
Connection: S3Connection:beta92
DEBUG:boto:path=/dd-test/object%5B%5E%2A%7C%22%5D
DEBUG:boto:auth_path=/dd-test/object%5B%5E%2A%7C%22%5D
DEBUG:boto:Method: PUT
DEBUG:boto:Path: /dd-test/object%5B%5E%2A%7C%22%5D
DEBUG:boto:Data: new file
DEBUG:boto:Headers: {}
DEBUG:boto:Host: beta92:9000
DEBUG:boto:Port: 9000
DEBUG:boto:Params: {}
DEBUG:boto:establishing HTTP connection: kwargs={'port': 9000, 'timeout': 70}
DEBUG:boto:Token: None
DEBUG:boto:StringToSign:
PUT


Wed, 10 Jan 2018 08:32:39 GMT
/dd-test/object%5B%5E%2A%7C%22%5D
DEBUG:boto:Signature:
AWS AKIAIOSFODNN7EXAMPLE:izr4BgiWjtnP35XMfmCDYqmRGrU=
DEBUG:boto:Final headers: {'Date': 'Wed, 10 Jan 2018 08:32:39 GMT', 'Content-Length': '8', 'Authorization': u'AWS AKIAIOSFODNN7EXAMPLE:izr4BgiWjtnP35XMfmCDYqmRGrU=', 'User-Agent': 'Boto/2.48.0 Python/2.7.12 Linux/4.4.0-53-generic'}
DEBUG:boto:Response headers: [('content-length', '0'), ('accept-ranges', 'bytes'), ('vary', 'Origin'), ('server', 'Minio/RELEASE.2017-10-27T18-59-02Z (linux; amd64)'), ('etag', '"7b07c717c8f3187221c4ec0ebf53a874"'), ('x-amz-request-id', '150865B9D2E14C38'), ('date', 'Wed, 10 Jan 2018 08:32:03 GMT'), ('content-type', 'text/plain; charset=utf-8')]

(sf2) dzialak@tad-38 ~/PycharmProjects/minio $ s3cmd -c s3cfg.minio ls s3://dd-test
                       DIR   s3://dd-test/files/
                       DIR   s3://dd-test/manifests/
2018-01-10 08:26         8   s3://dd-test/_new
2018-01-10 08:32         8   s3://dd-test/object[^*|"]
2018-01-10 08:28         8   s3://dd-test/object[^*|&#34;]
```

**Comment by ddzialak** [comment]
@kannappanr the main issue is about documentation inconsistency, please don't propagate client restriction to server side ;) rather change message `Unsupported characters are ...` and possible allow these chars in client as it's supported by server.
An extra option for this issue is to allow new lines and backslashes but it sounds like a feature/improvement.

**Comment by ddzialak** [comment]
so backslash `\` is forbidden:
```
$ python  ../_extras_/custom-s3-req.py  s3cfg.minio 
Connection: S3Connection:beta92
DEBUG:boto:path=/dd-test/foo%5Cbar
DEBUG:boto:auth_path=/dd-test/foo%5Cbar
DEBUG:boto:Method: PUT
DEBUG:boto:Path: /dd-test/foo%5Cbar
DEBUG:boto:Data: new file
DEBUG:boto:Headers: {}
DEBUG:boto:Host: beta92:9000
DEBUG:boto:Port: 9000
DEBUG:boto:Params: {}
DEBUG:boto:establishing HTTP connection: kwargs={'port': 9000, 'timeout': 70}
DEBUG:boto:Token: None
DEBUG:boto:StringToSign:
PUT


Wed, 10 Jan 2018 08:48:55 GMT
/dd-test/foo%5Cbar
DEBUG:boto:Signature:
AWS AKIAIOSFODNN7EXAMPLE:Mr29Cc0R7k8niSSp7W6jWrhi5dc=
DEBUG:boto:Final headers: {'Date': 'Wed, 10 Jan 2018 08:48:55 GMT', 'Content-Length': '8', 'Authorization': u'AWS AKIAIOSFODNN7EXAMPLE:Mr29Cc0R7k8niSSp7W6jWrhi5dc=', 'User-Agent': 'Boto/2.48.0 Python/2.7.12 Linux/4.4.0-53-generic'}
DEBUG:boto:Response headers: [('transfer-encoding', 'chunked'), ('accept-ranges', 'bytes'), ('vary', 'Origin'), ('server', 'Minio/RELEASE.2017-10-27T18-59-02Z (linux; amd64)'), ('x-amz-request-id', '1508669D2A4926D6'), ('date', 'Wed, 10 Jan 2018 08:48:19 GMT'), ('content-type', 'application/xml')]
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioInvalidObjectName</Code><Message>Object name contains unsupported characters.</Message><Key></Key><BucketName></BucketName><Resource>/dd-test/foo\bar</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

**Comment by ddzialak** [comment]
and new line `\n` is also forbidden but other error is returned:
```
$ python  ../_extras_/custom-s3-req.py  s3cfg.minio 
Connection: S3Connection:beta92
DEBUG:boto:path=/dd-test/foo%0Abar
DEBUG:boto:auth_path=/dd-test/foo%0Abar
DEBUG:boto:Method: PUT
DEBUG:boto:Path: /dd-test/foo%0Abar
DEBUG:boto:Data: new file
DEBUG:boto:Headers: {}
DEBUG:boto:Host: beta92:9000
DEBUG:boto:Port: 9000
DEBUG:boto:Params: {}
DEBUG:boto:establishing HTTP connection: kwargs={'port': 9000, 'timeout': 70}
DEBUG:boto:Token: None
DEBUG:boto:StringToSign:
PUT


Wed, 10 Jan 2018 08:51:08 GMT
/dd-test/foo%0Abar
DEBUG:boto:Signature:
AWS AKIAIOSFODNN7EXAMPLE:G7nC6pkn+qvteubVn50alQNdaGM=
DEBUG:boto:Final headers: {'Date': 'Wed, 10 Jan 2018 08:51:08 GMT', 'Content-Length': '8', 'Authorization': u'AWS AKIAIOSFODNN7EXAMPLE:G7nC6pkn+qvteubVn50alQNdaGM=', 'User-Agent': 'Boto/2.48.0 Python/2.7.12 Linux/4.4.0-53-generic'}
DEBUG:boto:Response headers: [('transfer-encoding', 'chunked'), ('accept-ranges', 'bytes'), ('vary', 'Origin'), ('server', 'Minio/RELEASE.2017-10-27T18-59-02Z (linux; amd64)'), ('x-amz-request-id', '150866BC0C5AAD17'), ('date', 'Wed, 10 Jan 2018 08:50:32 GMT'), ('content-type', 'application/xml')]
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><Key></Key><BucketName></BucketName><Resource>/dd-test/foo&#xA;bar</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

**Comment by ddzialak** [comment]
sorry for late response, please let me know if you still need any explanation...

**Comment by harshavardhana** [comment]
Since Windows and Linux are supported by windows object name restrictions vary according to the backend. So what is allowed on Linux is not what is allowed on Windows.

> An extra option for this issue is to allow new lines and backslashes but it sounds like a feature/improvement.

There is no reason to allow these characters, do you have applications which create these characters? is it possible to not use them?

**Comment by ddzialak** [comment]
> There is no reason to allow these characters, do you have applications which create these characters? is it possible to not use them?

The reason to support it is that these chars are allowed for names of files and directories for many filestems.
I have application that parallelize backup of whole filesystem to object store. Please believe that any huge filesystem will have directories or files with strange characters like backslash or new line.

 `minio` was selected for testing purpose (instead of amazon) but Amazon S3 allow to store object names with backslash `\` and new line `\n`. Anyway, it's not a big deal for me because I have option `forbidden_chars` that is configurable for each type of object store and urlencode these characters so each object store must only allow for chars `%0-9a-f`.

**Comment by harshavardhana** [comment]
> minio was selected for testing purpose (instead of amazon) but Amazon S3 allow to store object names with backslash \ and new line \n. Anyway, it's not a big deal for me because I have option forbidden_chars that is configurable for each type of object store and urlencode these characters so each object store must only allow for chars %0-9a-f.

II do believe you, but Unfortunately that cannot be supported due to windows dependency. So on windows there is no character such as `\` since its a delimiter it won't work.  It would lead to an inconsistent situation such as  `a\b` where `a\` would become the top level prefix.

> The reason to support it is that these chars are allowed for names of files and directories for many filestems.
> I have application that parallelize backup of whole filesystem to object store. Please believe that any huge filesystem will have directories or files with strange characters like backslash or new line.

```go
// IsValidObjectPrefix verifies whether the prefix is a valid object name.
// Its valid to have a empty prefix.
func IsValidObjectPrefix(object string) bool {
        if hasBadPathComponent(object) {
                return false
        }
        if len(object) > 1024 {
                return false
        }
        if !utf8.ValidString(object) {
                return false
        }
        // Reject unsupported characters in object name.
        if strings.ContainsAny(object, "\\") {
                return false
        }
        return true
}
```

It is nothing but all UTF8 characters,  avoids `..`, avoiding `\` was the only way for us to avoid inconsistent situation. For all other characters backend limitations apply.

**Comment by ddzialak** [comment]
As for me it's fine, the only reason I was surprised is that minio serwer says some characters are unsupported but in fact set of unsupported chars is different. This character set should also contain new line and in case of someone try to store object with new line in name valid error code should be reported.

**Comment by harshavardhana** [comment]
> As for me it's fine, the only reason I was surprised is that minio serwer says some characters are unsupported but in fact set of unsupported chars is different. This character set should also contain new line and in case of someone try to store object with new line in name valid error code should be reported.

Newline is supported but the problem is perhaps encoding and handling it by our muxer on server side.

Especially this message `<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><Key></Key><BucketName></BucketName><Resource>/dd-test/foo&#xA;bar</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>`

This seems like wrong since the the resource has the right path, it would be perhaps ignored by our muxer.
