### ISSUE TITLE
[feature] Support bucket notifications eventInfo return user defined metadata headers

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#5165]
## Expected Behavior
User defined metadata headers should be part of the eventInfo structure sent to the targets

## Current Behavior
Currently we do not send all the necessary details of an object in the eventinfo structure. 

## Possible Solution
Using objInfo copy the necessary values before sending the notification event to relevant targets.

## Steps to Reproduce (for bugs)
Design change, no systemic bug here. 

## Context
We are expanding the scope bucket notification event structure to include object content-type, content-encoding, user set metadata as well.  With this change in scope applications can now use and understand more information about the objects and the events.

## Your Environment
Current master

**Comment by krishnasrinivas** [comment]
@harshavardhana notification receivers can do HEAD on the object to get the metadata?

**Comment by harshavardhana** [comment]
> @harshavardhana notification receivers can do HEAD on the object to get the metadata?

Yes they can @krishnasrinivas since we do set the metadata headers anyways in the response back to the client.

**Comment by krishnasrinivas** [comment]
> Yes they can @krishnasrinivas since we do set the metadata headers anyways in the response back to the client.

I mean, why implement #5165 when notification receivers can do HEAD to get the metadata?

**Comment by harshavardhana** [comment]
> I mean, why implement #5165 when notification receivers can do HEAD to get the metadata?

The metadata is meant for fast querying based on metadata which is not possible today @krishnasrinivas . So a copy of this information in database allows for full namespace replication. 

Additionally this came in as customer requirement
