### ISSUE TITLE
ERRO[0043]ERRO[0042]

### ISSUE THREAD

**Issue by neveziss** [minio/minio#5171]
Getting an error. I can upload files on their own but cannot when it requires folders to be uploaded.
Unable to initiate new multipart upload id.   cause=mkdir /mnt/DriveA/.minio.sys/multipart/ad1server1backup/CBB_SERVER/CBB_DiskImage/Disk_00000000-0000-0000-0000-000000000001/Volume_NTFS_00000000-0000-0000-0000-000000000000:: invalid argument source=[object-handlers.go:600:objectAPIHandlers.NewMultipartUploadHandler()] stack=fs-v1-multipart.go:371:fsObjects.newMultipartUpload fs-v1-multipart.go:417:fsObjects.NewMultipartUpload <autogenerated>:381:(*fsObjects).NewMultipartUpload object-handlers.go:598:objectAPIHandlers.NewMultipartUploadHandler api-router.go:52:(objectAPIHandlers).NewMultipartUploadHandler-fm

PutObject object-handlers.go:542:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm

Unable to create image backups.
## Expected Behavior

Upload successfull
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
You are trying to upload files which has `::` it's unsupported on certain filesystems . 

Can you provide more details 

- System information such as OS, backend FS etc
- minio version

Also can you please edit the bug title to reflect the issue instead?

**Comment by deekoder** [comment]
@neveziss  I hope we have answered your question. Please let us know if theres anything else we can address. Closing this issue. Please feel free to reopen if any further questions. We are also available on slack where you can get answers to questions instantly https://slack.minio.io/
