### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by tillkruss** [minio/minio#5172]
## Expected Behavior
I'm doing a multipart upload using [EvaporateJS](https://github.com/TTLabs/EvaporateJS), but it fails with this:

```
Uncaught (in promise) TypeError: Cannot read property '1' of null
```

## Current Behavior

The POST request trailing with `?uploads` returns 200 and some Minio HTML, however it should return something like:

```
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Bucket>...</Bucket>
    <Key>...</Key>
    <UploadId>...</UploadId>
</InitiateMultipartUploadResult>
```

Are multipart uploads even supported by Minio?

Thanks!

**Comment by harshavardhana** [comment]
Are you uploading from browser ? Would you share a sample code which we can use to reproduce the issue ?

**Comment by tillkruss** [comment]
Yes, I'm uploading from Chrome. I'm not sure if I could provide a code sample, it's tightly baked into a Vue component and our app.

Is there any other way I can help debug this?

Here is the tweaked sample code from [EvaporateJS](https://github.com/TTLabs/EvaporateJS):


```js
var config = {
     signerUrl: <SIGNER_URL>,
     aws_url: 'http://127.0.0.1:9001/minio',
     aws_key: <AWS_KEY>,
     bucket: <AWS_BUCKET>,
     computeContentMd5: false,
};

return Evaporate.create(config)
    .then(function (evaporate) {

      var file = new File([""], "file_object_to_upload"),
          addConfig = {
            name: file.name,
            file: file,
            progress: function (progressValue) { console.log('Progress', progressValue); },
            complete: function (_xhr, awsKey) { console.log('Complete!'); },
          };
      evaporate.add(addConfig)
          .then(function (awsObjectKey) {
                console.log('File successfully uploaded to:', awsObjectKey);
              },
              function (reason) {
                console.log('File did not upload sucessfully:', reason);
              });
    });
```

There are "signer" examples in several languages [here](https://github.com/TTLabs/EvaporateJS/tree/master/example).

**Comment by krishnasrinivas** [comment]
```
var config = {
     signerUrl: <SIGNER_URL>,
     aws_url: 'http://127.0.0.1:9001/minio',
     aws_key: <AWS_KEY>,
     bucket: <AWS_BUCKET>,
     computeContentMd5: false,
};
```
this should have:
```
     aws_url: 'http://127.0.0.1:9001',
```

**Comment by krishnasrinivas** [comment]
Let us know if you still face any problems, we'll close this issue.

**Comment by tillkruss** [comment]
@krishnasrinivas: Thanks a lot, that worked and thanks for the great tool!
