### ISSUE TITLE
OmniOS: minio server fails to start "Initializing object layer failed cause=disk path full"

### ISSUE THREAD

**Issue by ghost** [minio/minio#5173]
## Expected Behavior
Minio server should start and use the ZFS filesystem for it's storage location.

## Current Behavior
On OmniOS (SunOS) version omnios-r151022, with a newly created ZFS filesystem, minio server fails to start with:
`minio server /minio
ERRO[0000] Initializing object layer failed              cause=disk path full source=[server-main.go:209:serverMain()]

There's plenty of space available:
Filesystem             Size   Used  Available Capacity  Mounted on
rpool/minio            899G    88K       446G     1%    /minio

Trussing the process, the last call I see before the error is thrown:
  stat("/minio", 0xC42042FB38)                    = 0

## Possible Solution
Searching on the error message, I found https://github.com/minio/minio/issues/3592. I suspect that the issue here is the same, because ZFS does not preallocate inodes -- so long as there is space, metadata can be written. For example, df -oi (equivalent of df -i on Linux) returns "df: operation not applicable for FSType zfs".

## Steps to Reproduce (for bugs)
1. Compile from source on OmniOSCE omnios-r151022-eb9d5cb557, using go ver 1.9.2
2. Create new ZFS filesystem called minio
3. Attempt to start minio server, using default configuration and no command-line options: `minio server /minio`

## Context
I'm trying to run minio on my OmniOS file server to serve as a backup target for Duplicati.

## Your Environment
* `minio version` doesn't appear to be functioning correctly:
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
From minio.spec:
RELEASE.2017-04-25T01-27-49Z
83abb310b4ce3a0dfc6d7faf78e33cb6f9132cfe
* System OS: OmniOS omnios-r151022-eb9d5cb557

**Comment by harshavardhana** [comment]
We do not return error based on inodes anymore,  this must be related to the `f_frsize` v/s `f_bsize` issue in statfs usage.

**Comment by ghost** [comment]
Perhaps it's similar to this Ansible issue? https://github.com/ansible/ansible/pull/17493

I'm not a developer, just working on this from a Solaris/OmniOS systems administration background.

**Comment by harshavardhana** [comment]
> Perhaps it's similar to this Ansible issue? ansible/ansible#17493

Yes that is the issue @nnmiller

**Comment by harshavardhana** [comment]
Also we do not support Solaris in our implementation of disk.GetInfo(), currently returns dummy zero values which would basically disable running minio on Solaris.  Sending a fix @nnmiller would you help me validate it?

**Comment by ghost** [comment]
@harshavardhana Yes, I will assist with testing.

Rebuilt with the latest commits. Working fine with some basic tests using `mc`. I'll try to get Duplicati set up this weekend and stress test it a bit.

I appreciate your responsiveness to fixing this issue.

**Comment by peterquirk** [comment]
This problem also occurs with Minio 18.02.0-ce on Docker for Windows (Windows 17101 and prior builds.)

![image](https://user-images.githubusercontent.com/4087812/36331743-12f698f6-133d-11e8-991f-7973c532bc72.png)

**Comment by harshavardhana** [comment]
Please provide `df -h` output from your docker instance @peterquirk . Minio needs a minimum of 1gig free disk space available.

**Comment by zamrih** [comment]
Good day to you,

Same issue as @peterquirk here but with Docker Toolbox on a windows server 2008 r2 :

> docker@default:~$ docker run -p 9000:9000 -v /c/opt/host/opt/app/minio/data:/data -v /c/opt/host/opt/app/minio/config:/root/.minio minio/minio server /data
> Created minio configuration file successfully at /root/.minio
> 
> 
> Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:224:cmd.serverMain()
>        2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
>        3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
>        4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
>        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
>        6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
> [2018-02-18T18:42:10.99862071Z] [ERROR] Initializing object layer failed (disk path full)

> docker@default:~$ sudo df -h
> Filesystem                Size      Used Available Use% Mounted on
> tmpfs                   896.3M    421.6M    474.7M  47% /
> tmpfs                   497.9M         0    497.9M   0% /dev/shm
> /dev/sda1                17.9G      1.9G     15.1G  11% /mnt/sda1
> cgroup                  497.9M         0    497.9M   0% /sys/fs/cgroup
> /opt/app                 99.9G     26.3G     73.6G  26% /opt/app
> c/Users                  99.9G     26.3G     73.6G  26% /c/Users
> /dev/sda1                17.9G      1.9G     15.1G  11% /mnt/sda1/var/lib/docker/plugins
> /dev/sda1                17.9G      1.9G     15.1G  11% /mnt/sda1/var/lib/docker/aufs

> docker@default:~$ docker version
> Client:
>  Version:	18.02.0-ce
>  API version:	1.36
>  Go version:	go1.9.3
>  Git commit:	fc4de44
>  Built:	Wed Feb  7 21:12:37 2018
>  OS/Arch:	linux/amd64
>  Experimental:	false
>  Orchestrator:	swarm
> 
> Server:
>  Engine:
>   Version:	18.02.0-ce
>   API version:	1.36 (minimum version 1.12)
>   Go version:	go1.9.3
>   Git commit:	fc4de44
>   Built:	Wed Feb  7 21:20:09 2018
>   OS/Arch:	linux/amd64
>   Experimental:	false

> docker@default:~$ docker image ls
> REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
> minio/mc                      latest              0edbe11b68e4        8 days ago          12.9MB
> minio/minio                   latest              ce3439e5a5b7        8 days ago          28.9MB

> docker@default:~$ docker info
> Containers: 5
>  Running: 0
>  Paused: 0
>  Stopped: 5
> Images: 23
> Server Version: 18.02.0-ce
> Storage Driver: aufs
>  Root Dir: /mnt/sda1/var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 93
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
> runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.4.115-boot2docker
> Operating System: Boot2Docker 18.02.0-ce (TCL 8.2.1); HEAD : 99245f4 - Thu Feb  8 17:43:39 UTC 2018
> OSType: linux
> Architecture: x86_64
> CPUs: 1
> Total Memory: 995.9MiB
> Name: default
> ID: Q56C:TM52:ERBD:6JCO:VHCF:VKZD:FFJ7:ITPL:5D4U:6VJA:SPOL:5NC6
> Docker Root Dir: /mnt/sda1/var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
>  provider=virtualbox
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

This is the output right from the docker vm.
Same error is returned from windows terminal.
The docker machine driver used is virtualbox and the volume used is a shared virtualbox folder.

It may be related to the "vboxsf" filesystem used by the virtualbox shared folder.

As the image starts normally when trying an ext4 partition instead ( see the previous df command )  :

> docker@default:~$ docker run -p 9000:9000 -v /mnt/sda1/tmp/minio/data:/data -v /mnt/sda1/tmp/minio/config:/root/.minio minio/minio server /data
> 
> Drive Capacity: 15 GiB Free, 17 GiB Total
> 
> Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
> AccessKey: ....
> SecretKey: ....
> 
> Browser Access:
>    http://172.17.0.2:9000  http://127.0.0.1:9000
> 
> Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
>    $ mc config host add myminio http://172.17.0.2:9000 .... ....
> 
> Object API (Amazon S3 compatible):
>    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
>    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

tmpfs is also yielding the same error message as with vboxsf :

> docker@default:~$ docker run  -p 9000:9000 -v /minio/data:/data -v /minio/config:/root/.minio minio/minio server /data
> Created minio configuration file successfully at /root/.minio
> 
> 
> Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:224:cmd.serverMain()
>        2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
>        3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
>        4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
>        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
>        6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
> [2018-02-18T18:49:16.671854508Z] [ERROR] Initializing object layer failed (disk path full)
>

**Comment by harshavardhana** [comment]
we will try to validate this using docker toolbox @nnmiller - please open a new issue with new detailed information about the windows server so that we can start this as a new discussion.
