### ISSUE TITLE
How to upload files by mulitiparts with mc tool?

### ISSUE THREAD

**Issue by wekay102200** [minio/minio#5175]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@wekay102200 Multipart upload is handled automatically by mc. If the object size is greater than 64 MB, the tool does a multi-part upload.

**Comment by wekay102200** [comment]
@kannappanr Does Multipart upload is handled automatically by web upload?
![image](https://user-images.githubusercontent.com/18589915/32758549-e5c959d4-c91f-11e7-81d1-bc487e0b9249.png)

**Comment by kannappanr** [comment]
@wekay102200 There is no multipart upload support in Minio browser. The maximum size of object that can be uploaded via browser is 16 Giga Bytes.
