### ISSUE TITLE
mc multipart upload file occur error when complete upload parts.

### ISSUE THREAD

**Issue by wekay102200** [minio/minio#5178]
## Expected Behavior

when  complete upload parts it wil occur upload success or no error occur. 

## Current Behavior

when complete upload parts it occur one error,but the file is already upload success.

perhaps the sequence of delete mutlipart object dir is confused

## Possible Solution

change the sequence of delete mutlipart object dir.

## Steps to Reproduce (for bugs)

1. ./minio server 1111/ 
2. ./mc cp /opt/env/gesq_3.tar.bz myminio/ggg
3.
4.

## Context

![image](https://user-images.githubusercontent.com/18589915/32774515-7f2f24d6-c967-11e7-8fa0-fc06a4e6a8e1.png)
![image](https://user-images.githubusercontent.com/18589915/32774520-835598ce-c967-11e7-90ff-d51e105b3617.png)

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by poornas** [comment]
@wekay102200, The log you posted is for the minio server. Does mc console show an error status for the multi-part upload as well?  Can you paste the version of mc you are using - the version can be found by typing ``` mc version``` on the command line.

**Comment by poornas** [comment]
@wekay102200, the bug on the server side has already been fixed - you could download latest version of minio server from https://dl.minio.io/server/minio/release/

**Comment by wekay102200** [comment]
@poornas the mc console show no error anyway. thanks very much for the bug fix.
