### ISSUE TITLE
how to generate share url permanent?

### ISSUE THREAD

**Issue by timchenxiaoyu** [minio/minio#5180]
now ,the  url only 7 minute valid，how to change this?

**Comment by nitisht** [comment]
@timchenxiaoyu Presigned URLs are valid only for a maximum of 7 days. This is mandated by S3 Spec (Ref: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html).

For permanent sharing you can consider buckets policies - https://docs.minio.io/docs/minio-client-complete-guide#policy

**Comment by deekoder** [comment]
Please lets us know if you have any other questions.

**Comment by timchenxiaoyu** [comment]
even I set  buckets policies, I cannot still get permanent url,how to solve this?

**Comment by nitisht** [comment]
Once you set the policy on a bucket like

```
mc policy public myminio/bucketname
```

You can use the URL: `miniohost:9000/bucketname/object` to access the object

**Comment by timchenxiaoyu** [comment]
#mc policy public minio/test

Access permission for `minio/test` is set to `public`

#wget http://10.39.0.45:9000/test/types-of-mounts.png

it's ok now .ths.
I send url wget http://10.39.0.45:9000/minio/test/types-of-mounts.png before,so i'm wrong

**Comment by nitisht** [comment]
You need to remove `minio`, so the URL should be

`http://10.39.0.45:9000/test/types-of-mounts.png`

**Comment by timchenxiaoyu** [comment]
yes, you are right ,ths

**Comment by JLiscom** [comment]
@nitisht 
I don't know if this is a counter example or a different method. If I use the [s3.getSignedUrl](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.htIml#getSignedUrl-property) I can generate urls that are longer than 7 days.
JS Code
```
var urlParams= {"Bucket":"opennote","Key":"ovoay3yj5uky.png","Expires":77760000}
s3.getSignedUrl("getObject",urlParams,function(err,data){console.dir(err);console.dir(data)})
```

This gives a signature of `?AWSAccessKeyId=tests&Expires=1595816882&Signature=HQbjEiQUrqW87ShZSjVVOeHnz0o%3D`
Which is valid for 900 days from now.

S3 and Minio accepts this signature and display the object

Why does it work?

**Comment by harshavardhana** [comment]
> S3 and Minio accepts this.
> Why does it work?

This is a presigned URL but it is not permanent @FoxUSA

**Comment by JLiscom** [comment]
@harshavardhana 
Its way over 7 days. I could set it to 90,000 days or 999,999,999 days. So it essentially is permanent.

Signature
```
?AWSAccessKeyId=tests&Expires=86401517971856&Signature=OcP7k9X%2FSa4ZS6Ql65p0FOsyNfs%3D
```
[Epoch time sets that signature to expire in the year 2739925.](https://www.wolframalpha.com/input/?i=86401517971856+epoch)

**Comment by harshavardhana** [comment]
> Its way over 7 days. I could set it to 90,000 days or 999,999,999 days. So it essentially is permanent.
> 
> Signature
> 
> ?AWSAccessKeyId=tests&Expires=86401517971856&Signature=OcP7k9X%2FSa4ZS6Ql65p0FOsyNfs%3D
> Epoch time sets that signature to expire in the year 2739925.

Yes only in AWS Signature v2 (legacy),  AWS Signature v4 has limited it to maximum of 7 days.

**Comment by Arkemlar** [comment]
It would be good if somebody point out in docs that polycy prefix should not start with slash / when you type it in via web intrerface, got fooled by that slash hard before checked policies via mc.

**Comment by harshavardhana** [comment]
> It would be good if somebody point out in docs that polycy prefix should not start with slash / when you type it in via web intrerface, got fooled by that slash hard before checked policies via mc.

UI is being revamped you won't be allowed to type incorrect values.

**Comment by woodgear** [comment]
how should i do this via sdk(js)?
```
mc policy public myminio/bucketname
```

**Comment by kannappanr** [comment]
@woodgear Here is the policy

```
 {
  "Statement": [
   {
    "Action": [
     "s3:GetBucketLocation",
     "s3:ListBucket",
     "s3:ListBucketMultipartUploads"
    ],
    "Effect": "Allow",
    "Principal": {
     "AWS": "*"
    },
    "Resource": "arn:aws:s3:::mybucketname",
    "Sid": ""
   },
   {
    "Action": [
     "s3:AbortMultipartUpload",
     "s3:DeleteObject",
     "s3:GetObject",
     "s3:ListMultipartUploadParts",
     "s3:PutObject"
    ],
    "Effect": "Allow",
    "Principal": {
     "AWS": "*"
    },
    "Resource": "arn:aws:s3:::mybucketname/*",
    "Sid": ""
   }
  ],
  "Version": "2012-10-17"
 }
```

Replace `mybucketname` with the appropriate bucket name

**Comment by modbender** [comment]
All I did create a new location in nginx something like /bucketname and in the block add root to the local path for the bucket folder.
