### ISSUE TITLE
Minio cluster becomes unresponsive after killing 1 of 3 instances (2 out of 6 disks) - Docker

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/minio#5189]
I created a Minio cluster using docker-compose file: [docker-compose.txt](https://github.com/minio/minio/files/1473988/docker-compose.txt). Everything works as expected and I can do uploads (using [MinioClientUploader.txt](https://github.com/minio/minio/files/1473984/MinioClientUploader.txt)). When I kill a docker node (minio3 for example), the uploads fails with `Socket timeout` exceptions. Also the UI and `mc commands` are working very slow (few seconds for each request). 

## Expected Behavior
If a minority number of disks are down, the cluster should still be able to process the requests without timeouts (from the Java client).

## Your Environment
* Version used (`minio version`): latest
* Operating System and version (`uname -a`): Ubuntu 16.04 LTS

**Comment by harshavardhana** [comment]
why two issues ? are you saying #5190 different than this? - IMO both seems same we should close one and keep only one?

**Comment by davidgeorgealex** [comment]
Indeed, both are very similar. The differences consist of the way how we build the Docker image (custom one vs Minio one) and the result - sometimes in the custom one get errors as well. If you feel the need, please close this one and keep only https://github.com/minio/minio/issues/5190 because it covers this ticket as well. Thanks for the fast feedback @harshavardhana !

**Comment by nitisht** [comment]
closing as discussed.
