### ISSUE TITLE
Minio Client not mirroring files unless touched

### ISSUE THREAD

**Issue by john-bakker** [minio/minio#5191]
I'm running 4 instances of the minio client simultaneously on 1 server. All of them are running in mirror mode  : 

```
root     17097     1  0 10:01 pts/0    00:00:04 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/upload_mm/ minio/upload-mm --watch --exclude *.html --force --remove
root     17098     1  0 10:01 pts/0    00:00:10 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/static/ minio/static --watch --exclude *.html --force --remove
root     17099     1  0 10:01 pts/0    00:00:02 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/public/ minio/public --watch --exclude *.html --force --remove
root     21099 19433  0 10:24 pts/1    00:00:17 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/upload/ minio/upload --watch --exclude *.html --force --remove

```
These 4 instances should monitor 4 different folders and should put the content of these folders in 4 different buckets.

The files are being placed in the folder by a CMS system.

## Expected Behavior
The expected behavior is that when a file is uploaded through the CMS system , it is placed in the folders that the minio clients are watching . And once a file is placed / updated / removed , it should be synchronized with the minio buckets.

## Current Behavior
The current behavior is the synchronization works perfectly fine when I place a file manually in the folder. It automatically gets pushed in the minio buckets.

Although , when a file is being uploaded through the CMS, the file gets placed in the file system. But the minio client doesn't seem to pick it up. 
If I do a touch on that file , it does get synched.

```
[root@myserver public]# ls -ltra web-docs/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg
-rw-r--r-- 1 gx apache 77123 Nov 15 11:52 web-docs/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg

[root@myserver public]# ./mc ls minio/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg
mc: <ERROR> Unable to stat `minio/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg`. Object does not exist

[root@myserver public]# touch web-docs/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg

[root@myserver public]# ls -ltra web-docs/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg
-rw-r--r-- 1 gx apache 77123 Nov 15 12:49 web-docs/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg

[root@myserver public]# ./mc ls minio/upload/42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg
[2017-11-15 12:49:51 CET]  75KiB 42dcad35-472e-4d09-9fd2-3df3021fa2db_cdn-upload-test-3.jpg
```

When I try directly on the filesystem , it does work properly

```
[root@myserver public]# ls -ltra web-docs/upload/testdoc.txt
ls: cannot access web-docs/upload/testdoc.txt: No such file or directory

[root@myserver public]# ./mc ls minio/upload/testdoc.txt
mc: <ERROR> Unable to stat `minio/upload/testdoc.txt`. Object does not exist

[root@myserver public]# echo "test file" >> web-docs/upload/testdoc.txt

[root@myserver public]# ls -ltra web-docs/upload/testdoc.txt
-rw-r----- 1 root root 10 Nov 15 12:58 web-docs/upload/testdoc.txt

[root@myserver public]# ./mc ls minio/upload/testdoc.txt
[2017-11-15 12:58:42 CET]    10B testdoc.txt
```

## Context
I'm trying to have an almost real-time synchronization between my local filesystem and my minio storage.

## Your Environment

I'm running the version : RELEASE.2017-10-14T00-51-16Z on a RHEL 6.5 OS
```
[root@myserver public]# ./mc version
Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195
```

**Comment by john-bakker** [comment]
@kannappanr do you have a possible update on this already ?

**Comment by kannappanr** [comment]
@john-bakker , It looks like that the modified time is not getting updated on the file being placed by the CMS. Can you please let us know what CMS you are using and give us detailed instructions on how this can be reproduced?

**Comment by john-bakker** [comment]
The CMS is gx experience central. I can't reproduce it without uploading a
file from gx itself. I was hoping you guys had an idea.

Op 20 nov. 2017 21:33 schreef "kannappanr" <notifications@github.com>:

**Comment by john-bakker** [comment]
sorry for the late response, i've got some extra information.

The path where the files are being uploaded is a shared filesystem where multiple servers connect to.
The application that is uploading the files is located on the ins059 , where also the mc is running in mirror mode.

If i do a lookup on the file from another server , and look for the file information i get the following : 

```
[root@ela1ins059 upload]# stat f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg
  File: `f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg'
  Size: 62697           Blocks: 124        IO Block: 131072 regular file
Device: 18h/24d Inode: 265657      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1555/      gx)   Gid: (   48/  apache)
Access: 2017-11-27 12:42:00.752253382 +0100
Modify: 2017-11-27 12:40:25.734000000 +0100
Change: 2017-11-27 12:40:58.923804495 +0100
```

I see a recent timestamp, but somehow the uploaded file was not synched to the s3 bucket.

If I do a touch from the remote server the file properties get updated, but still the file is not synced.

```
root@ela1ins059 upload]# touch f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg

[root@ela1ins059 upload]# stat f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg
  File: `f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg'
  Size: 62697           Blocks: 124        IO Block: 131072 regular file
Device: 18h/24d Inode: 265657      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1555/      gx)   Gid: (   48/  apache)
Access: 2017-11-27 12:46:46.418811707 +0100
Modify: 2017-11-27 12:46:46.418811766 +0100
Change: 2017-11-27 12:46:46.418826123 +0100
```

If I now login to the server where the mc is running in mirror mode with the watch option , and do a stat on the file i do see the same info as on the remote server : 
```
[root@ela1ins056 upload]# stat f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg
  File: `f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg'
  Size: 62697           Blocks: 124        IO Block: 131072 regular file
Device: 18h/24d Inode: 265657      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1555/      gx)   Gid: (   48/  apache)
Access: 2017-11-27 12:46:46.418811707 +0100
Modify: 2017-11-27 12:46:46.418811766 +0100
Change: 2017-11-27 12:46:46.418826123 +0100
```
however, when i do a touch now on the file, the properties again get updated, and now the file is shown in the object storage:
```
[root@ela1ins056 upload]# touch f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg

[root@ela1ins056 upload]# stat f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg
  File: `f23c341e-2e4a-4e29-8a5f-4fc85fe5f592_dave-test.jpg'
  Size: 62697           Blocks: 124        IO Block: 131072 regular file
Device: 18h/24d Inode: 265657      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1555/      gx)   Gid: (   48/  apache)
Access: 2017-11-27 12:51:43.804656752 +0100
Modify: 2017-11-27 12:51:43.786669297 +0100
Change: 2017-11-27 12:51:43.786679048 +0100
```

So it seems the timestamps get properly updated once being uploaded through the application , it only doesnt get picked up by the minio client.

The minio client runs as : 
```
[root@ela1ins056 upload]# ps -ef | grep mirror
root      1754  8529  0 13:05 pts/1    00:00:00 grep mirror
root      4828     1  0 Nov15 ?        00:07:19 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/upload_mm/ minio/upload-mm --watch --exclude *.html --force --remove
root      4829     1  0 Nov15 ?        00:08:24 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/static/ minio/static --watch --exclude *.html --force --remove
root      4830     1  0 Nov15 ?        00:06:47 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/public/ minio/public --watch --exclude *.html --force --remove
root      4831     1  0 Nov15 ?        00:07:19 /u01/nas/gx/mc mirror /u01/nas/gx/web-docs/upload/ minio/upload --watch --exclude *.html --force --remove
```

**Comment by harshavardhana** [comment]
What is the shared filesystem under use ?. This is perhaps due to not supporting inotify semantics properly. `mc mirror --watch` relies on proper working of filesystem notifications (fsnotify in short).

If the notifications are not propagated on a shared FS properly then it cannot sync the data properly.

**Comment by john-bakker** [comment]
the underlying filesystem is ZFS. But if that would be the problem , the mc would not pick up the file if it was touched / edited or deleted right ?

**Comment by harshavardhana** [comment]
how is the same ZFS mounted on two different hosts ? Are you not using a network FS here?AFAIK ZFS is not a network filesystem.

However in this setup the fsnotify is not fully propagated unless the fsnotify probes are local i.e under 056 they are local so a touch works. Filesystem changes do get applied but from 059 but it never propagates.

So if you happen to run ` mc mirror` from 059 then it would work fine. FWIW this is not a mc bug but a limitation of the setup in which you are running (filesystem limits)

**Comment by john-bakker** [comment]
the issue was in the GX CMS system. Apparently the application server that we were talking to , was not the server that was in fact placing the file in the filesystem. Some other server in the cluster was doing the actual upload. 

We now have the mc running in mirror mode on all servers in the cluster, so if any of them writes a file in the shared folder , it gets synched immediatelly.

the item can be closed
