### ISSUE TITLE
Unable to execute commands with s3cmd 

### ISSUE THREAD

**Issue by shruthied** [minio/minio#5196]
In spite of configuring the s3cmd configuration file ~/.s3cfg from the cookbook docs I am unable to execute the commands in s3cmd. Unable to use s3cmd to manage data with minio server.

**Comment by deekoder** [comment]
can you paste the output @shruthied

**Comment by shruthied** [comment]
![s3cmd](https://user-images.githubusercontent.com/32338806/32922180-a39e24ee-caf6-11e7-842e-23c87f404dc0.JPG)

**Comment by harshavardhana** [comment]
You need to update s3cmd - s3cmd fixed a bug upstream in latest 2.0.1 @shruthied

**Comment by shruthied** [comment]
thanku
