### ISSUE TITLE
What's the point of multiple buckets without multiple access keys?

### ISSUE THREAD

**Issue by lflare** [minio/minio#5199]
As I have mentioned in the title, what is the point of allowing for multiple buckets when we are not able to use multiple access/secret keys for each different bucket? Most services/projects I have seen tend towards using only one bucket for all purposes, yet to use the same access/secret keys for multiple projects is also a security disaster waiting to happen.

Before anyone tells me to spin up multiple minio instances to handle multi-identities, I know that is a solution but it is also a shoddy solution. If Minio is modeled after the S3 API, at the very least, maybe allow for multiple secret keys with the same access keys? I should not be needed to spin up multiple instances of Minio to handle multi-identity, when the overhead of doing so is greater than simply allowing for multiple secret keys to access different buckets.

Back to the title, what's the point of multiple buckets without multiple access keys?

**Comment by krishnasrinivas** [comment]
> Back to the title, what's the point of multiple buckets without multiple access keys?

Data organisation. Almost all of Minio's users have multiple buckets. Most of software that use AWS-S3 (for example cloudberry backup client) make ListBucket/MakeBucket calls and we need to support it.

Coming to supporting multiple access/secret keys, we have not had many requests for this. We have had discussions on this, however we can not commit anything at this point.

**Comment by lflare** [comment]
Hello,

Thanks for replying fast. I have some further questions regarding this issue,

> Almost all of Minio's users have multiple buckets.

How does the average user go about segregating access controls to prevent one compromised access key from completely killing their Minio's security? I assume that each bucket is for each different service, how do people sleep at night knowing that if a single service is compromised, all their buckets are equally as compromised?

> Coming to supporting multiple access/secret keys, we have not had many requests for this. We have had discussions on this, however we can not commit anything at this point.

I would've thought this would be quite an important issue that security people would be flocking about but perhaps I'm wrong?

**Comment by krishnasrinivas** [comment]
> How does the average user go about segregating access controls to prevent one compromised access key from completely killing their Minio's security? I assume that each bucket is for each different service, how do people sleep at night knowing that if a single service is compromised, all their buckets are equally as compromised?

We advise one minio instance per tenant. Different tenants can have different access/secret keys. Minio integrates well with micro-service/container architecture. Hence spinning up new instances is easy.

Some documents:
https://docs.minio.io/docs/multi-tenant-minio-deployment-guide
https://github.com/krishnasrinivas/cookbook/blob/multi-tenancy/docs/multi-tenancy-in-minio.md

**Comment by lflare** [comment]
> We advise one minio instance per tenant.

That brings about my first point, why even allow multiple buckets?

I believe Minio can and should be able to be instanced as a central server, rather than as a micro-service. Your documents describes of using multiple Minio instances hosted on different address spaces, or using an additional frontend proxy to host on the same namespace, which I personally think of that as a very sloppy manner of introducing multi-identities.

Rather than rely on an external source, there should at least be a capability of at least allowing for separate **secret** keys for different buckets such that we can separate different service permissions.

**Comment by krishnasrinivas** [comment]
> That brings about my first point, why even allow multiple buckets?

copy/pasting previous reply:

> Data organisation. Almost all of Minio's users have multiple buckets. Most of software that use AWS-S3 (for example cloudberry backup client) make ListBucket/MakeBucket calls and we need to support it.

> I believe Minio can and should be able to be instanced as a central server, rather than as a micro-service.

Thanks for your feedback. We will discuss about it in our product roadmap meeting. But we can't commit anything at this point. I will close this issue for now.

**Comment by mvrhov** [comment]
He's another request from one that would require the same functionality as OP

**Comment by reptillicus** [comment]
Seconded! I work at an academic high performance computing center and we have multiple projects that would like to use minio. Dealing with the overhead of multiple minio instances is a hard sell. If there was a single centralized installation with multiple client access keys it would be perfect for our use cases.

**Comment by mvrhov** [comment]
They are working on that Take a look at https://github.com/minio/mfs

**Comment by jbroq** [comment]
Hi all,

My concern is about having the same data accessed from 

1. a frontend : read only
2. a backend : read/write

Although using policies could make it, I don't think having the same credentials for both my frontend and backend is a good idea.

MFS was promising, but it seems stuck if not dead.

Best
BTW: thanks for the work done so far

**Comment by dgoujard** [comment]
I also need separate access key by buckets to host website assets, it's not great to have the same key for different clients.

**Comment by DoCode** [comment]
👍

**Comment by benyanke** [comment]
Also agree - multiple access keys would be ideal for my use case as well.

**Comment by deependhulla** [comment]
Also agree - multiple access keys would be ideal for my use case as well. I can have single server and a web interface to my project guy to allocate the access.
Possible ot have a our own cloud service like aws s3  for commercial use.

**Comment by hijak** [comment]
plus 1 this or ill have to go with ceph as an object storage provider

**Comment by teroz** [comment]
plus one this too. In a typical logging scenario, a compromised host would allow an attacker to delete all logs on minio. Obviously, multiple minio instances would be impractical in such a use case.

**Comment by davleb** [comment]
Minio is a great piece of software, solid, well documented. But sorry, the lack of this feature makes me think of hijak solution. Cannot handle hundreds of docker/lxc Minio containers for just the sake of it.
Would you seriously consider a multiple access keys contribution / pull request if provided ?

**Comment by harshavardhana** [comment]
Multiple keys is already being implemented 

- https://github.com/minio/minio/pull/6168
- https://github.com/minio/minio/pull/6176

**Comment by alexellis** [comment]
I came here via Google - a key per bucket would be really useful, I also would like this feature. If I can help with testing let me know.

Thanks,

Alex

**Comment by hadifarnoud** [comment]
I didn't realise there is no multi key access until I needed it.

**Comment by vadmeste** [comment]
> I didn't realise there is no multi key access until I needed it.

This feature is recently added, please take a look here https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html
