### ISSUE TITLE
Recommendation consuming the minio webhook in .NET Core

### ISSUE THREAD

**Issue by MontyGvMC** [minio/minio#5204]
In short, minio behaves correctly. This is just a question for a recommendation how to consume the webhook in .NET Core. There is a great chance I am completly wrong and just miss something.

Anyone ever consumed a webhook in .NET Core (REST API) and could please give me some guidance?

## Expected Behavior

The webhook is expected to be consumed in a .NET Core (2.0) REST API controller either receiving the sent JSON as string or as a model class.

## Current Behavior

Currently there seems to be a problem consuming the webhook. The controller method is called but .NET Core struggles to receive the json. (So far this is a .NET Core issue, not a minio issue).

The problem seems to be the way .NET Core handles and binds the data. Binding complex model classes is easy and supported out of the box. Receiving a simple string/json data seems to be a nightmare.

I implemented a controller which should receive the minio webhook and it looks like this:

  ```
public class MinioWebhookReceiverController : ControllerBase 
  {
  
    [HttpPost("MinioWebHook1")]
    public IActionResult MinioWebHook([FromBody]string message)
    {
      Logger.LogInformation("minio web hook 1 called: " + message);
      return Ok();
    }
  
    [HttpPost("MinioWebHook2")]
    public IActionResult MinioWebHook2([FromBody]MinioResponse message)
    {
      Logger.LogInformation("minio web hook 2 called: " + message);
      return Ok();
    }
    
    [HttpPost("MinioWebHook3")]
    public IActionResult MinioWebHook4([FromBody]JObject message)
    {
      Logger.LogInformation("minio web hook 3 called: " + message);
      return Ok();
    }
  
  }
```

So far I understood it like

- minio calls the webhook method using POST
-  it sends [this structure](http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html) as json in the body
- I haven't figured out which content type is used for that (form-data, x-www-form-urlencoded,...)

The results are:

- web hook 1 (consuming the body as string): mesage is always null, not supported by .NET Core?
- web hook 2 (would require an implemented model class of the structure recevied): does the minio SDK (for .NET) already holds such a model class?
- web hook 3 (consuming as Newtonsoft JObject): messagestill is null

## Possible Solution

There are several possible solutions that come up to my mind.

- don't use webhooks and use alternatives like RabbitMQ instead

- implement a correct model class (or correct model classes) of the [received structure](http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html). This enables consuming the json binded to the model class. So far it is unclear for me, how likely this class will change in the future.

- find a workaround to receive the pure json in the controller method (e.g. using a [custom modelbinder](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding) )

## Steps to Reproduce (for bugs)

1. create a .NET Core REST API consuming the webhook from minio
2. configure Minio to send notifications to the rest api
3. try to use (or just log) the received data in the controller method

## Context

I am currently trying to implement a webhook receiver in a .NET Core 2.0 REST API. But I am got stuck at the point how .NET Core could/would pass the webhook data (the JSON) to the controller method.

## Your Environment

* .NET Core 2.0

**Comment by poornas** [comment]
@MontyGvMC , aspnet has a generic webhooks package - not sure if you came across [this](https://github.com/aspnet/WebHooks/blob/dev/samples/CustomReceiver/WebHooks/CustomWebHookHandler.cs) example yet.  You could get the data as a JObject and parse contents if you did not want to implement a custom model class.

**Comment by deekoder** [comment]
@MontyGvMC  closing this for now. Please reactivate if you'd like to discuss this further with us.

**Comment by MontyGvMC** [comment]
Well, still trying to implement a webhook receiver in .NET Core 2.0

So far I configured the web hook in the minio config
But when it starts I receive the following error mesage:

> level=error
> msg="Initializing object layer failed"
> cause="Unable to initialize event notification. Unable to lookup webhook endpoint http://localhost:50100/MinioWebHook response(415 Unsupported Media Type)"
> source="[server-main.go:209:serverMain()]"

The webhook receiver is started and working (tested with postman).
MinioWebHookController holds a POST method receiving the Json as JObject from the POST body.
It is defined to produce and consume "application/json".

What does minio lookup at start?

Any idea or any docs why that would be?

**Comment by harshavardhana** [comment]
At first minio tries to connect to the server @MontyGvMC that would be without application/json - performing a POST without any body. 

```
  req, err := http.NewRequest("POST", urlStr, bytes.NewReader([]byte("")))
        if err != nil {
                return err
        }
```

**Comment by MontyGvMC** [comment]
@harshavardhana Thank you. That helped me. Need some time to figure out how to do the routing configuration in .NET Core and report back when I got it solved. I am close :-)

**Comment by MontyGvMC** [comment]
@harshavardhana The expected media type that should be received and returned is "application/json", right?

**Comment by harshavardhana** [comment]
Yes notification data is in json. There is no requirement on the media type. You shouldn't have handlers specifically for contentType as application/json it's not necessary.

**Comment by MontyGvMC** [comment]
Currently trying my luck with the routing problem over there on StackOverflow.com [.NET Core 2.0 Web API Controller routing (POST with optional [FromBody] Parameter) for receiving web hooks](https://stackoverflow.com/questions/47830126/net-core-2-0-web-api-controller-routing-post-with-optional-frombody-paramete)

**Comment by MontyGvMC** [comment]
@harshavardhana 
In the mean time I recognized I have to [configure in minio which events](https://blog.minio.io/introducing-webhooks-for-minio-e2c3ad26deb2) are sent to the endpoint.

My current setup involes

- a Windows 7 PC
- running the minio.exe on port 9000 directly (for easier config changes and since it didn't run on docker for windows, never was able to get the browser interface)
- Visual Studio 2017 with the endpoint running on local IIS Express

Where in this setup would I configure the events that are sent? As mentioned in point 4 in the link above

I am trying to receive file uploaded events.

> $ mc events add myminio/images arn:minio:sqs:us-east-1:1:webhook — events put — suffix .jpg

**Comment by harshavardhana** [comment]
> Where in this setup would I configure the events that are sent? As mentioned in point 4 in the link above

```
mc config host add myminio <endpoint> access_key secret_key
```

This should be configured pointing to your endpoint on port 9000 and then you can perform `mc events` on a bucket where you would be generally interested in events, suffixes/prefixes of the object.

**Comment by MontyGvMC** [comment]
Well, thank you so far. I will have to wait for monday until I can further try to get things running. Have a nice weekend.

**Comment by MontyGvMC** [comment]
@harshavardhana I wish you a good snowy monday morning.

With the help of [stackoverflow](https://stackoverflow.com/questions/47830126/net-core-2-0-web-api-controller-routing-post-with-optional-frombody-paramete/47830270#47830270) I managed to find a working routing configuration (and .NET Core 2.0 implementation) of the receving endpoint (code below). At least when I test it with postman.

If I use in postman all the information given so far for the requests I get valid results. Unfortunatly when I test it with the minio server I still get 415 unsupported media type when Minio server starts up.

I could not find the code making the requests in the in the git repo. If it is there would you mind pointing me to it so I can take a closer look on it and figure out what is different, please?

```
[Route("api/Hook")]
[Produces("application/json")]
[Consumes("application/json")]
public class HookController : Controller
{
  private ILogger<HookController> Logger { get; set; }

  public HookController(ILogger<HookController> logger)
  {
    Logger = logger ?? throw new ArgumentNullException(nameof(logger));
  }

  [HttpPost("HookReceiver")]
  public IActionResult HookReceiver([FromBody] JObject res)
  {
    return res == null ? HookReceiverLookUp() : HookReceiverEvent(res);
  }

  private IActionResult HookReceiverLookUp()
  {
    Logger.LogInformation("Hook Receiver POST lookup called");
    return Ok();
  }

  private IActionResult HookReceiverEvent(JObject res)
  {
    Logger.LogInformation("Hook Receiver event");
    return Ok();
  }
  
}
```

**Comment by MontyGvMC** [comment]
I was able to pin down the issue.

Can it be that the POST request at start up sends a different or no content type?

**Comment by harshavardhana** [comment]
> Can it be that the POST request at start up sends a different or no content type?

Yes that is correct I indicated that here https://github.com/minio/minio/issues/5204#issuecomment-351938793

**Comment by MontyGvMC** [comment]
Sure, you are right. Seems I forgot it since you mentioned it.

So far this seems to be a problem for .NET Core routing. But I will keep trying to find a solution on the .NET Core side.

Any chances this will be configurable or change so both requests send the same content-type some point in the future?

**Comment by harshavardhana** [comment]
> Any chances this will be configurable or change so both requests send the same content-type some point in the future?

We used to have verification request as JSON but we changed it and perhaps we forgot the reason why we had JSON before and incorrectly fixed it. We should fix it perhaps and keep it as JSON to make application routing much simpler/stricter

Relevant commit ad53c5d8594dd4f6dad7c56824910b6dda1f47af

BTW in your situation here @MontyGvMC you don't need to route based on `content-type` instead your router should be based on the HTTP method `POST` .  `Content-Type` can be a another invariant for the router but doesn't need to be a primary one.  Otherwise your router can be faked by sending naked `CURL` messages for all other HTTP methods.

Anycase we will fix the lookup behavior // @nitisht

**Comment by MontyGvMC** [comment]
I understand that I should not route based on content-type. But this part of the routing is handled somewhere deeper inside .NET Core. My controller method do not even get called when the framework returns 415 Unsupported Media Type. It is a mixture between the .net core routing and the .net core (automated) model bindig.

With my knowledge (so far) I think the only way to get this to work would be a custom routing middleware for the Web API or some configuration. I currently try to get into those topis. So far I was able to avoid this. :-)

It will take me some time to figure out how this could be solved.
Thank you for your time and effort so far.

**Comment by MontyGvMC** [comment]
With the help of Lennart over there on stackoverflow I f(actually he) figured out how to implement a webhook receiver and how to get it working with the default model binder. The trick is to avoid the default model binder at all.

I was able to test it and receive both: the initial lookup event as well as other notifications (objects created,....).

The working implementation:

```
public class HookController : Controller
{
  protected ILogger<HookController> Logger { get; set; }

  public HookController(ILogger<HookController> logger)
  {
    Logger = logger ?? throw new ArgumentNullException(nameof(logger));
  }

  //configuration url: http://localhost:[port]/api/Hook/endpoint
  [HttpPost("Endpoint")]
  public IActionResult HookReceiver([FromHeader(Name = "Content-Type")] string type)  //do not bind JObject here
  {

    if (type == null) return HookReceiverLookUp();   //check if it is the initial look up call / ignore body

    //avoiding built in / default model binder and read the body yourself if necessary
    string body;

    using (var reader = new System.IO.StreamReader(Request.Body, System.Text.Encoding.UTF8, true, 1024, true))
    {
      body = reader.ReadToEnd();
    }

    //optionally convert it to Json if you want to work with json
    JObject obj = Newtonsoft.Json.JsonConvert.DeserializeObject<JObject>(body);

    if (obj == null) return Ok(); //what else??

    return HookReceiverEvent(obj);
  }

  private IActionResult HookReceiverLookUp()
  {
    Logger.LogInformation("Hook Receiver POST lookup called");
    return Ok();
  }

  private IActionResult HookReceiverEvent(JObject res)
  {
    Logger.LogInformation("Hook Receiver POST lookup called\r\n" + res.ToString());
    return Ok();
  }

}
```
It is not final and production ready but at least it is a working starting point in .NET core.

Thank you for your patience, effort and time.
