### ISSUE TITLE
gcs gateway project id check (checkGCSProjectID api) takes  long time 

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#5209]
## Summary
After re-activating the gcs project, I started minio gateway service with the provided credentials.json file.After trying for more than 30 minutes, I still get the following error message on the console:
```
$ ./minio.RELEASE.2017-11-20T23-41-09Z gateway gcs 

               *** Warning: Not Ready for Production ***
FATA[0000] Unable to initialize gateway layer            cause=Error getting projects list: googleapi: Error 403: Google Cloud Resource Manager API has not been used in project peak-essence-171622 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=peak-essence-171622 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured source=[gateway-main.go:175:startGateway()]
```
When the following function call, which checks the validity of the project id, is commented out, the problem goes away and the minio gateway service can be started without any problem.
```
func newGCSGatewayLayer(projectID string) (GatewayLayer, error) {
:
:
                }
        }
 
-       err = checkGCSProjectID(ctx, projectID)
-       if err != nil {
-               return nil, err
-       }
+       // err = checkGCSProjectID(ctx, projectID)
+       // if err != nil {
+       //      return nil, err
+       // }
 
        // Initialize a GCS client.
        // Send user-agent in this format for Google to obtain usage insights while participating in the
:
:
```
Whatever the reason for the project validity check failure is, when the check api call is commented out and the gcs gateway service is started, `mc ls` command lists the buckets and objects without any problem.
```
$ mc config host add mygcs http://localhost:9000 <access_key> <secret_key>
Added `mygcs` successfully.
$ mc ls mygcs
```
## Expected Behavior
Minio gcs gateway service is supposed to be kicked off and if this due to a delay on the gcs side, it should not be more than a few minutes as the error message says, `If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`.

## Current Behavior
Fails to start minio gcs gateway service.

## Possible Solution
Workaround: Comment out the call that checks/validates user provided project's validity.

## Steps to Reproduce (for bugs)
1. Go through the steps of setting up gcs gateway as explained at `https://docs.minio.io/docs/minio-gateway-for-gcs`
2. Start the service, `./minio.RELEASE.2017-11-20T23-41-09Z gateway gcs`

## Context
Minio gcs gateway service is down.

## Your Environment
* Version used (`minio version`): minio.RELEASE.2017-11-20T23-41-09Z

**Comment by deekoder** [comment]
we added this check so that we dont take invalid project ids. But 30 mins sounds too high.
