### ISSUE TITLE
Docker healthcheck script wrong

### ISSUE THREAD

**Issue by tomcsi** [minio/minio#5211]
I running the docker container with healcheck, and I try to get http://127.0.0.1:9000/minio/index.html url from container, then I get 403, because I get this error: Bucket not found: index.html

The container is always unhealthy, because the healthcheck script can check 200 or 404 status code.

**Comment by harshavardhana** [comment]
Please follow the issue template, while also clearly stating the minio/docker container version you are running as well.

- Also explain what you are trying to achieve, 
- are you modifying the healthcheck script? 
- what are the environment variables being used? 
- have you turned off browser?

**Comment by tomcsi** [comment]
I used the following environment variables:
```
MINIO_BROWSER="on"
MINIO_ACCESS_KEY="vahv9phae...........iCeidohQuok1i"
MINIO_SECRET_KEY="ohth1poh3i...........eexaiLohph2ungau"
MINIO_REGION="mmm"
MINIO_CACHE_SIZE="60GB"
```

The docker command:
```
docker run -d -v \
/data/minio-front:/minio-front  -v /data/minio-rear:/minio-rear \
-e MINIO_BROWSER="on"  -e MINIO_ACCESS_KEY="vahv9phae...........iCeidohQuok1i"  \
-e MINIO_SECRET_KEY="ohth1poh3i...........eexaiLohph2ungau"  -e MINIO_REGION="mmm"  \
-e MINIO_CACHE_SIZE="60GB" \
minio/minio server http://1.1.1.1/minio-front http://1.1.1.1/minio-rear \
http://2.2.2.2/minio-front http://2.2.2.2/minio-rear
```

The healthcheck script is unmodified.

**Comment by tomcsi** [comment]
Sorry, I used old image version, and healthcheck script doesn't contains user-agent parameter.
