### ISSUE TITLE
Support Additional Levels of logging

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#5219]
The plan is to have three Levels of logging:
  - Error
  - Fatal
  - Debug

Debug level logs are logged only if the --debug flag is set on the server cli.
Things to do to implement this feature are

1. Add ``` --debug ``` flag
2. Add a function similar to errorIf and fatalIf, can be called debugIf, to log debug logs.

**Comment by pdaures** [comment]
Maybe I could help with this?

**Comment by kannappanr** [comment]
We are not doing this feature as of now, so closing this issue.
