### ISSUE TITLE
Remove logrus dependency in logging

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#5220]
The plan is to remove use of logrus
As part of that, logger functions should not use logrus and they should be removed.

**Comment by pdaures** [comment]
What do you plan to use instead? Use directly the logger package?

**Comment by ebozduman** [comment]
@pdaures ,
We simply planned to have regular formatted messages printed on the console without any logger library/package help. 
If end-user would like to store the console messages in a log file, then s/he can redirect or `tee` the console messages to a file.
