### ISSUE TITLE
Question: large .minio.system/tmp

### ISSUE THREAD

**Issue by AndrewSav** [minio/minio#5222]
Hello,

I have a huge .minio.system/tmp I think it's leftover from failed uploads.

1) how to clean it up?
2) is it possible to do it automatically?

**Comment by harshavardhana** [comment]
Which version of minio are you running? @AndrewSav if you use the latest it shouldn't leave any left overs in this manner. 

Also if you restart the server `.minio.sys/tmp` is cleaned up automatically.  You can also manually purge `.minio.sys/tmp` if there is no active I/O going on.

**Comment by AndrewSav** [comment]
> You are running an older version of Minio released 2 months ago
> Update: docker pull minio/minio:RELEASE.2017-10-27T18-59-02Z

Is it too old?

What happened is that I had about 20GB free space and wanted to upload a 20 GB file. It failed because of free space threshold. I added 20GB more space it's failed again because old tmp left behind. I added 30 more and then it uploaded. When I decided to re-upload the file it failed again of course which left me with no space and /tmp full of these failed attempts.

Does this scenario make sense?

**Comment by harshavardhana** [comment]
> Is it too old?

Yes it is @AndrewSav 

> What happened is that I had about 20GB free space and wanted to upload a 20 GB file. It failed because of free space threshold. I added 20GB more space it's failed again because old tmp left behind. I added 30 more and then it uploaded. When I decided to re-upload the file it failed again of course which left me with no space and /tmp full of these failed attempts.

Even this shouldn't happen really, with ENOSPC error we should still delete the file. Perhaps this scenario can be tested but `.minio.sys/tmp` can be purged safely if you don't have any active I/O or simply restart the server which would clean it up.

**Comment by AndrewSav** [comment]
After I removed the contents of /tmp, pulled latest docker image and restarted I'm getting:

>mc.exe: <ERROR> Failed to copy `box\vmware\api-base.box`. We encountered an internal error, please try again.

And again, there is a left-over large file in /tmp after this error.
The error happens after 100% upload. I think what errors is deleting the old file and moving the new file in it's place, the file is big, and there is not enough space for *three* copies of this file just for two. 

Restart of minio after that does clear the /tmp

**Comment by harshavardhana** [comment]
> And again, there is a left-over large file in /tmp after this error.
> The error happens after 100% upload. I think what errors is deleting the old file and moving the new file in it's place, the file is big, and there is not enough space for three copies of this file just for two.

Ah i see why that is happening, the rename would have failed and we didn't delete the tmp copy. We can fix it.

**Comment by AndrewSav** [comment]
Can you also tell me when /multipart is going to be freeed? it has 9GB file in there for some reason...
That does NOT clear upon restart
Thank you for your support!

**Comment by harshavardhana** [comment]
> Can you also tell me when /multipart is going to be freeed? it has 9GB file in there for some reason...
> That does NOT clear upon restart
> Thank you for your support!

@AndrewSav that can be cleaned in two ways

- Using AbortMultipartUpload API on the client side, listing what is pending you can see using ListMultipartUploads API
- Will be cleaned up automatically after a week.

**Comment by AndrewSav** [comment]
Is ListMultipartUploads / AbortMultipartUpload  available via mc.exe?

**Comment by harshavardhana** [comment]
Yes @AndrewSav `mc ls --incomplete`  shows you incomplete uploads and `mc rm --incomplete` would remove them.

**Comment by AndrewSav** [comment]
Thank you very much. Last (hopefully) question. I keep experimenting and I can see that right after upload the /tmp of the upload that just happened is not deleted, even after the upload succeeded. When those are supposed to be deleted? They disappear on restart but I can't restart the server after every upload.

**Comment by harshavardhana** [comment]
> Thank you very much. Last (hopefully) question. I keep experimenting and I can see that right after upload the /tmp of the upload that just happened is not deleted, even after the upload succeeded. When those are supposed to be deleted? They disappear on restart but I can't restart the server after every upload.

They should be deleted, this must be a recent bug. which version of minio are you running?

**Comment by AndrewSav** [comment]
It's the latest pull from docker hub. How do I find out the version? It does not seem to be printed in the docker log on container start.

**Comment by AndrewSav** [comment]
Aplogies, somehow when I pulled the latest container earlier today something went wrong. I'll just updated again:

```
$ docker exec -it minio minio version
Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48
```

I'll re-test.

**Comment by harshavardhana** [comment]
> $ docker exec -it minio minio version
> Version: 2017-11-22T19:55:46Z
> Release-Tag: RELEASE.2017-11-22T19-55-46Z
> Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48
> I'll re-test.

Thanks @AndrewSav

**Comment by AndrewSav** [comment]
@harshavardhana after the upgrade I cannot use mc.exe at all

>mc.EXE: <ERROR> Failed to copy `box\vmware\api-base.box`. The request signature we calculated does not match the signature you provided. Check your key and signing method.

I triple checked the keys in the config.json on the client. The keys are correct and work in the WebUI but not in mc.exe

**Comment by harshavardhana** [comment]
> I triple checked the keys in the config.json on the client. The keys are correct and work in the WebUI but not in mc.exe

That is not possible most probably you have an extra character. Nothing changes really after an upgrade. @AndrewSav also my id is @harshavardhana not @hackintoshrao :smile:

**Comment by AndrewSav** [comment]
Apologies. How do I troubleshot? I regenerated the keys by removing the config on the server and adding the new ones on the client. mc.exe still returns the same error. WebUI access works.

Also tested mc client on linux - same error.

**Comment by harshavardhana** [comment]
> Apologies. How do I troubleshot? I regenerated the keys by removing the config on the server and adding the new ones on the client. mc.exe still returns the same error. WebUI access works.

what error does `mc.exe` return?

**Comment by AndrewSav** [comment]
You mean apart from:

>mc.EXE: Failed to copy box\vmware\api-base.box. The request signature we calculated does not match the signature you provided. Check your key and signing method.

?

**Comment by harshavardhana** [comment]
Can you provide the `--debug` output and also any output on the server logs? @AndrewSav

**Comment by harshavardhana** [comment]
Also is minio running behind a proxy? @AndrewSav

**Comment by AndrewSav** [comment]
Yes, minio is running behind nginx proxy. The logs will be here in the next few minutes

**Comment by harshavardhana** [comment]
> Yes, minio is running behind nginx proxy. The logs will be here in the next few minutes

Can you paste your nginx config? the issue is perhaps you are not setting Host header. https://docs.minio.io/docs/setup-nginx-proxy-with-minio ?

**Comment by AndrewSav** [comment]
Logs: https://gist.github.com/AndrewSav/d206bd26b529a749f382b9104c83ed71

**Comment by AndrewSav** [comment]
Nginx config:

```
  server {
	listen 443;
	server_name <domain redacted>;
 
        ssl_certificate           /etc/nginx/<cert redacted>.crt;
        ssl_certificate_key       /etc/nginx/<cert redacted>.key;

        ssl on;
        ssl_session_cache  builtin:1000  shared:SSL:10m;
        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

        location / {
            resolver 127.0.0.11 valid=30s;
            set $upstream_minio minio;
            proxy_pass         http://$upstream_minio:9000;
            proxy_http_version  1.1;
            proxy_set_header    Host $server_name:$server_port;
            proxy_set_header    X-Forwarded-Host $http_host;    # necessary for proper absolute redirects and TeamCity CSRF check
            proxy_set_header    X-Forwarded-Proto $scheme;
            proxy_set_header    X-Forwarded-For $remote_addr;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection $connection_upgrade;        
        }
    }    
```

**Comment by harshavardhana** [comment]
> proxy_set_header    Host $server_name:$server_port;

I think there is a bug in using $server_port signature is not generated with port, remove the port it should work fine. @AndrewSav

**Comment by harshavardhana** [comment]
> proxy_set_header    Host $server_name:$server_port;

Just call it `   proxy_set_header Host $http_host;`

**Comment by AndrewSav** [comment]
Yep, that did the trick, sorry for wasting your time. Interesting that it used to work like that before the upgrade. I have not change the ngnix configuration since I first set it up months ago.

Now back to upload and tmp testing!

Thank you!

**Comment by harshavardhana** [comment]
> Yep, that did the trick, sorry for wasting your time. Interesting that it used to work like that before the upgrade. I have not change the ngnix configuration since I first set it up months ago.

It was a bug on Minio server side which allowed it @AndrewSav

**Comment by AndrewSav** [comment]
@harshavardhana seems to work fine now. I'll open new issues if I experience any more abnormalities.
