### ISSUE TITLE
Curl user-agent is giving an HTTP 403 on all endpoints

### ISSUE THREAD

**Issue by boeboe** [minio/minio#5225]
For some reason, curl is giving a HTTP 403 on all endpoints...

    # curl http://127.0.0.1:9000/minio/login -v
    *   Trying 127.0.0.1...
    * Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
    > GET /minio/login HTTP/1.1
    > Host: 127.0.0.1:9000
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 403 Forbidden
    < Accept-Ranges: bytes
    < Content-Type: application/xml
    < Server: Minio/RELEASE.2017-11-22T19-55-46Z (linux; amd64)
    < Vary: Origin
    < X-Amz-Request-Id: 14F9874FB9E5F8B1
    < Date: Wed, 22 Nov 2017 21:58:46 GMT
    < Transfer-Encoding: chunked
    <
    <?xml version="1.0" encoding="UTF-8"?>
    * Connection #0 to host 127.0.0.1 left intact
    <Error><Code>AllAccessDisabled</Code><Message>All access to this bucket has been disabled.</Message><Key></Key><BucketName></BucketName><Resource>/minio/login</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>%                                                                                                                                                                                                    ➜  gitlab-runner git:(master) ✗ 

... unless you force it to use a browser like user-agent:

    # curl http://127.0.0.1:9000/minio/login -v -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
    *   Trying 127.0.0.1...
    * Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
    > GET /minio/login HTTP/1.1
    > Host: 127.0.0.1:9000
    > Accept: */*
    > User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
    >
    < HTTP/1.1 200 OK
    < Accept-Ranges: bytes
    < Cache-Control: no-store
    < Content-Length: 1979
    < Content-Type: text/html; charset=utf-8
    < Last-Modified: Wed, 15 Nov 2017 00:09:52 GMT
    < Vary: Origin
    < Date: Wed, 22 Nov 2017 21:58:46 GMT
    <
    <!DOCTYPE html>
    <html>

        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Minio Browser</title>
            <link rel="stylesheet" href="loader.css" type="text/css">
        </head>

        <body>
            <div class="page-load">
                <div class="pl-inner">
                    <img src="logo.svg" alt="">
                </div>
            </div>
            <div id="root"></div>

            

            <script>currentUiVersion = '2017-11-15T00:09:34Z'</script>
            <script src="index_bundle-2017-11-15T00-09-34Z.js"></script>
        </body>
    </html>
    * Connection #0 to host 127.0.0.1 left intact

This is a problem when one is using minio in a kubernetes/openshift environment with health checks enabled like for example:

          livenessProbe:
            httpGet:
              path: /minio/login
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 10

**Comment by harshavardhana** [comment]
Does healthcheck take scripts @boeboe ?

**Comment by harshavardhana** [comment]
Simply do this 

```
...
livenessProbe:
  exec:
    command:
    - /tmp/healthcheck.sh
  initialDelaySeconds: 15
  timeoutSeconds: 1
...
```

https://github.com/minio/minio/blob/master/dockerscripts/healthcheck.sh download this.

**Comment by boeboe** [comment]
Workaround:

          livenessProbe:
            httpGet:
              path: /minio/login
              port: 9000
              httpHeaders:
              - name: User-Agent
                value: Mozilla
            initialDelaySeconds: 15
            timeoutSeconds: 10

**Comment by boeboe** [comment]
@harshavardhana why do you do this filtering on user agent? Is there a functional/security related requirement behind it?

**Comment by harshavardhana** [comment]
> @harshavardhana why do you do this filtering on user agent? Is there a functional/security related requirement behind it?

this is only a temporary hack, once we have `mc admin service status` implemented and merged we will migrate to that instead.

**Comment by pszabop** [comment]
BTW this broke a bunch of Ansible health checks I had.

Once you publish a URL that works, then changing the behavior breaks the API

/gripe off

**Comment by harshavardhana** [comment]
> BTW this broke a bunch of Ansible health checks I had.
> 
> Once you publish a URL that works, then changing the behavior breaks the API
> 
> /gripe off

@pszabop it is unfortunate that it happened, but what we have now is going to be the right endpoint for future needs.

**Comment by AlaskaJoslin** [comment]
This is broken in the [documentation]( https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes-yaml/minio-standalone-deployment.yaml). By the way really awesome product.

**Comment by nitisht** [comment]
> This is broken in the documentation.

Why do you say it is broken @AlaskaJoslin it is as per https://docs.minio.io/docs/minio-monitoring-guide.html

**Comment by AlaskaJoslin** [comment]
@nitisht without using the hacks discussed above, Kubernetes keeps bouncing the service when using HTTPS. I'm using the latest version and have also tried visiting via Firefox. If the user agent filtering will be continued in later versions it would be good to mention this point in the documentation.

**Comment by loekalive** [comment]
This functionality breaks public buckets for automated clients using the static download URL. Will this be fixed?

**Comment by lf1029698952** [comment]
I have the same issue, when I set minio/bucket policy public, I can get bucket object but cat't get bucket object by curl or wget because the server return 403 
```
All access to this bucket has been disabled.
```

**Comment by harshavardhana** [comment]
You cannot use /minio it's meant for webui access only, refer to buckets as http://endpoint/bucketName instead
