### ISSUE TITLE
Accessing Minio using HTTPS with s3a:// protocol from Apache Spark throwing error

### ISSUE THREAD

**Issue by ramkumarkb** [minio/minio#5232]
## Context
Previously reported Issue - #2965 for which a PR was created - #5179 . The fix was released as part of the 22-Nov-2017 release of MINIO..

However, upon further testing, it turns out that whilst using `s3a://` with `HTTP` protocol seems ok, the same code with `HTTPS` throws error. Details of the test are also added as comment in - #5179 

Upon some further testing, writes to S3 store using HTTP, throwing some errors related to MD5 checks. Possibly caused by the AWS libs that is being used in the calls to `s3a://`

## Expected Behavior
Both read and writes using HTTP and HTTPS protocol with s3a:// should work

## Current Behavior

1. Read over HTTP with s3a://  => OK
2. Write over HTTP with s3a:// => Error (Some errors related to MD5 checks in AWS lib?)
3. Read over HTTPS => Error (Requests are not reaching MINIO, AWS lib issue?)
4. Write over HTTPS => Error (Requests are not reaching MINIO, AWS lib issue?)

Read Works for:
spark._jsc.hadoopConfiguration().set("fs.s3a.endpoint", "http://<minio_server_host>:25252")
spark._jsc.hadoopConfiguration().set("fs.s3a.connection.ssl.enabled", "false")

Read does not work for:
spark._jsc.hadoopConfiguration().set("fs.s3a.endpoint", "https://<minio_server_host>:25252")
spark._jsc.hadoopConfiguration().set("fs.s3a.connection.ssl.enabled", "true")

**Error (with HTTPS)**
`java.nio.file.AccessDeniedException: s3a://spark22/TechCrunchcontinentalUSA_new.csv: getFileStatus on s3a://spark22/TechCrunchcontinentalUSA_new.csv: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null), S3 Extended Request ID: null`

`Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null), S3 Extended Request ID: null`

## Possible Solution
Not sure where the problem is as the chain involves many libs:
`Apache Spark => Hadoop libs => Hadoop-AWS libs => MINIO version`
Suggest that some tests are added for both HTTP & HTTPS protocol usage within s3a://, so that future changes in underlying libs are regressed

## Environment
MINIO Version: `2017-11-22T19:55:46Z` - Single Node
Spark Version: `spark-2.2.0-bin-without-hadoop`
Hadoop Version: `hadoop-2.8.2`
Tested using Zeppelin: `0.7.3` (the version that is compatible with `Spark 2.2`)

Addtional libs that I needed to install (manually!) under `/jars` folder of Spark are:
1. `hadoop-aws-2.8.2.jar`  (NOTE: This version has to be matching with the Hadoop version)
2. aws-java-sdk-kms-1.10.6.jar
3. aws-java-sdk-core-1.10.6.jar
4. aws-java-sdk-s3-1.10.6.jar
5. joda-time-2.9.9.jar
6. httpclient-4.5.3.jar

## Steps to Reproduce (for bugs)
1. Set up MINIO (22-Nov-2017 version), Single Node, with HTTP
2. Write a simple PySpark script in Zeppelin that connects to MINIO in `s3a://` with HTTP mode
3. The scripts works and the data is read from MINIO using the `s3a://` protocol
4. Restart MINIO with HTTPS enabled
5. Restart Zeppelin (not needed but just in case!)
6. Test the same PySpark script in Zeppelin with HTTPS connection 

Works for:
spark._jsc.hadoopConfiguration().set("fs.s3a.endpoint", "http://<minio_server_host>:25252")
spark._jsc.hadoopConfiguration().set("fs.s3a.connection.ssl.enabled", "false")

Does not work for:
spark._jsc.hadoopConfiguration().set("fs.s3a.endpoint", "**https**://<minio_server_host>:25252")
spark._jsc.hadoopConfiguration().set("fs.s3a.connection.ssl.enabled", "**true**")

**References:**
https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html#S3A

**Comment by nitisht** [comment]
Thanks @ramkumarkb . Couple of questions

- How was the HTTPS certificate generated - self signed or via CA?
- Are there any logs on Minio server console? Can you pls paste them here?

**Comment by ramkumarkb** [comment]
@nitisht 
* HTTPS Certificate is self-signed.

Logs from the Minio Server:

* HTTPS => Nothing. I suspect that the request does not even reach the Minio Server. May be some issues with the AWS S3a libs that is causing this?

* HTTP => Reading CSV files from Mino gives the following logs. But the reads themselves seems successful as am able to get the data in the Zeppelin.
 
`time="2017-11-26T19:30:18+08:00" level=error msg="Unable to fetch object info." cause="Prefix access is denied: spark22/TechCrunchcontinentalUSA.csv/_spark_metadata" source="[object-handlers.go:247:objectAPIHandlers.HeadObjectHandler()]" stack="fs-v1-helpers.go:198:osErrToFSFileErr fs-v1-helpers.go:222:fsStatFile fs-v1.go:492:fsObjects.getObjectInfo fs-v1.go:526:fsObjects.GetObjectInfo <autogenerated>:1:(*fsObjects).GetObjectInfo object-handlers.go:245:objectAPIHandlers.HeadObjectHandler api-router.go:45:(objectAPIHandlers).HeadObjectHandler-fm"`

`time="2017-11-26T19:30:18+08:00" level=error msg="Unable to fetch object info." cause="Prefix access is denied: spark22/TechCrunchcontinentalUSA.csv/_spark_metadata" source="[object-handlers.go:247:objectAPIHandlers.HeadObjectHandler()]" stack="fs-v1-helpers.go:198:osErrToFSFileErr fs-v1-helpers.go:222:fsStatFile fs-v1.go:492:fsObjects.getObjectInfo fs-v1.go:526:fsObjects.GetObjectInfo <autogenerated>:1:(*fsObjects).GetObjectInfo object-handlers.go:245:objectAPIHandlers.HeadObjectHandler api-router.go:45:(objectAPIHandlers).HeadObjectHandler-fm"`

`time="2017-11-26T19:30:18+08:00" level=error msg="Unable to write to client." cause="write tcp 10.165.195.24:25252->10.165.192.80:55169: write: connection reset by peer" source="[object-handlers.go:186:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1.go:449:fsObjects.GetObject <autogenerated>:1:(*fsObjects).GetObject object-handlers.go:185:objectAPIHandlers.GetObjectHandler api-router.go:59:(objectAPIHandlers).GetObjectHandler-fm"`

`time="2017-11-26T19:30:18+08:00" level=error msg="Unable to write to client." cause="write tcp 10.165.195.24:25252->10.165.192.80:55170: write: connection reset by peer" source="[object-handlers.go:186:objectAPIHandlers.GetObjectHandler()]" stack="fs-v1.go:449:fsObjects.GetObject <autogenerated>:1:(*fsObjects).GetObject object-handlers.go:185:objectAPIHandlers.GetObjectHandler api-router.go:59:(objectAPIHandlers).GetObjectHandler-fm"`

**Comment by nitisht** [comment]
Thanks @ramkumarkb I'll try to replicate the setup and see what goes wrong

**Comment by ramkumarkb** [comment]
@nitisht 
Thank you for your attention on this rather tricky subject. 

Further tests this morning on `write` using HTTP over `s3a://` also was not very successful, unfortunately. Should I update the title of this issue also to expand the scope to write errors?

## High-level steps ##
* Read a CSV file (as DataFrame) using HTTP over s3a:// => OK
* Set the property to disable MD5Checks
* Use the same DataFrame and try to write back as a new CSV file => Error

## Sample Code (to write back to S3) ##
Disable the MD5 Check
`spark._jsc.hadoopConfiguration().set("com.amazonaws.services.s3.disableGetObjectMD5Validation", "true")`

Other configurations (just in case)
* spark._jsc.hadoopConfiguration().set("fs.s3a.path.style.access", "true")
* spark._jsc.hadoopConfiguration().set("fs.s3a.attempts.maximum", "5")
* spark._jsc.hadoopConfiguration().set("fs.s3a.connection.establish.timeout", "5000")
* spark._jsc.hadoopConfiguration().set("fs.s3a.connection.timeout", "10000")

One can use either of the below Spark DataFrame APIs to write back to S3:
* `df.write.mode('overwrite').format('csv').option("header", "true").save('s3a://spark22/write2s3')`
* `df.write.csv('s3a://spark22/writecsvtos3', mode='overwrite', header='true')`

## MINIO State - 4 temp files written in a temp folder ##
* Looks like a temporary folder gets created and Spark tries to write about 4 times. One can see that 4 temp files are created in MINIO and each one has the data

## Error in Zeppelin Console ##
`Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 86.0 failed 4 times, most recent failure: Lost task 0.3 in stage 86.0 (TID 107, 10.165.192.80, executor 0): org.apache.spark.SparkException: Task failed while writing rows`

`Caused by: org.apache.hadoop.fs.s3a.AWSClientIOException: saving output on writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: eGCnq6QoBbkB+sQWsaO8HQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: eGCnq6QoBbkB+sQWsaO8HQ==, md5DigestStream: null, bucketName: spark22, key: writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv): Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: eGCnq6QoBbkB+sQWsaO8HQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: eGCnq6QoBbkB+sQWsaO8HQ==, md5DigestStream: null, bucketName: spark22, key: writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv)`

`Caused by: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: eGCnq6QoBbkB+sQWsaO8HQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: eGCnq6QoBbkB+sQWsaO8HQ==, md5DigestStream: null, bucketName: spark22, key: writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv)`

**Comment by harshavardhana** [comment]
> Caused by: org.apache.hadoop.fs.s3a.AWSClientIOException: saving output on writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: eGCnq6QoBbkB+sQWsaO8HQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: eGCnq6QoBbkB+sQWsaO8HQ==, md5DigestStream: null, bucketName: spark22, key: writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv): Unable to verify integrity of data upload. Client calculated content hash (contentMD5: eGCnq6QoBbkB+sQWsaO8HQ== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3. You may need to delete the data stored in Amazon S3. (metadata.contentMD5: eGCnq6QoBbkB+sQWsaO8HQ==, md5DigestStream: null, bucketName: spark22, key: writecsvtos3/_temporary/0/_temporary/attempt_20171127110418_0086_m_000000_3/part-00000-a253d555-6b06-4bfd-96cb-702224160767-c000.csv)

this is a aws-sdk-java bug which tries to pro-actively validate the checksum but Etag was wrongly interpreted. Unfortunately it was packaged by hadoop and seems to be still lingering on. Would it be possible to use aws-sdk-java latest jar?  This is the bug which was fixed https://github.com/aws/aws-sdk-java/pull/590

Unfortunately `disableGetObjectMD5Validation` option only disables it for Get not for Put()  you need to set `disablePutObjectMD5Validation` instead.

**Comment by ramkumarkb** [comment]
@harshavardhana @nitisht 
Thanks for the reply.  So I did the following steps. The results are better (able to read / write to S3 Store using HTTP with `s3a://`).

## Removed the following libs from `/jars` folder of Spark ##
1. aws-java-sdk-kms-1.10.6.jar
2. aws-java-sdk-core-1.10.6.jar
3. aws-java-sdk-s3-1.10.6.jar
 
## Added the latest version of the AWS SDK lib ##
* `aws-java-sdk-1.11.234` - This version has only 1 jar as opposed to the older version consisting of 3 jars
* `Restarted` Spark-Master, Spark-Slave and Zeppelin

## Zeppelin ##
* The pySpark script seems to have executed successfully - no errors in the console!

## Minio State ##
* The path (or namespace) got created under the specified bucket
* `_SUCCESS` file was created
* `part-00000-82f8705c-c25e-4b00-84e4-1f341264d7e8-c000.csv` was created
* `_temporary/` got created and under this the following got created
** `0/`
*** `temporary/`
*** `task_20171127141714_0019_m_000000/`

What is this and who is doing all the above? AWS S3 lib or Spark or Minio or a combination of them?

## Documentation ##
Btw, I would really like to document all these steps somewhere so that others can get started more easily and you folks will have one less question to answer in Slack! Do you have a suggestion - Minio Cookbook?

**Comment by harshavardhana** [comment]
> The path (or namespace) got created under the specified bucket
> _SUCCESS file was created
> part-00000-82f8705c-c25e-4b00-84e4-1f341264d7e8-c000.csv was created
> _temporary/ got created and under this the following got created
> ** 0/
> *** temporary/
> *** task_20171127141714_0019_m_000000/

This perhaps i am expecting is created by spark here, not sure if this can be controlled.

**Comment by nitisht** [comment]
> Btw, I would really like to document all these steps somewhere so that others can get started more easily and you folks will have one less question to answer in Slack! Do you have a suggestion - Minio Cookbook?

yes, Cookbook will be a good place for the documents.

**Comment by ramkumarkb** [comment]
@nitisht @harshavardhana 
Update on the read with HTTPS using the new AWS-SDK lib - `aws-java-sdk-1.11.234`. Looks like I need to provide TrustStore - to Spark or AWS-SDK - would you know?

Things are certainly lot brighter with this lib - `aws-java-sdk-1.11.234`!

## Steps ##
Restart MINIO with SSL enabled mode using self-signed Certificate

## Error in MINIO console ## 
`time="2017-11-27T18:42:33+08:00" level=error msg="TLS handshake failed with new connection 10.165.192.80:44799 at server 10.165.195.24:25252" cause="remote error: tls: unknown certificate" source="[listener.go:170:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"` 

## Error in Zeppelin console ##
`org.apache.hadoop.fs.s3a.AWSClientIOException: doesBucketExist on spark22: com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by nitisht** [comment]
@ramkumarkb I found this while Googling, may be this will help https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find

**Comment by nitisht** [comment]
Hey @ramkumarkb I spent some time trying to get this working. I used the same libraries as you did (`aws-java-sdk-1.11.234.jar`) and was able to get the similar errors.

Then I added my self signed certificate to Java `cacerts` on the machine where Spark was deployed. Writes to Minio server with HTTPS enabled worked. I added the certs using `keytool`

```sh
keytool -import -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt -alias mycert -file /path/to/cert/used/by/minio/public.crt
```

Note that certificate was generated like this

```
$ openssl genrsa -out private.key 204
$ openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=127.0.0.1"
```

Can you please try this and let us know how this goes?

**Comment by ramkumarkb** [comment]
@nitisht  Thank you very much for the suggestion.

Unfortunately, Java is installed and runs under root (as per company policy) and we are unable to edit the `cacerts` as an application user. Therefore, we cannot run the command that you have suggested.

We tried to start Spark-Master and Spark-Slave(s) using the following JVM property but no luck:
`-Djavax.net.ssl.trustStore=<MyCaCert> -Djavax.net.ssl.trustStorePassword=<MyPassword>`

But looks like AWS libs does not honour these properties :-( 
https://github.com/aws/aws-sdk-java/issues/1294

Also Cloudera's documentation also confirms the same: 
https://www.cloudera.com/documentation/enterprise/5-9-x/topics/sg_aws_security.html => described under the section - `hadoop-aws Connector`

I guess for now we can close this issue but mark this for Documentation in the MINIO Cookbook (with all the gotchas that we have learnt here).

Thanks again for your patient support!

**Comment by nitisht** [comment]
> Thanks again for your patient support!

No problem @ramkumarkb . Feel free to let us know if there is something else we can help you with. 

> mark this for Documentation in the MINIO Cookbook

Yes, we'll do that. 

Closing this issue as discussed.
