### ISSUE TITLE
Consolidate "Quickstart Guide" links on Minio server console

### ISSUE THREAD

**Issue by ugurtigli** [minio/minio#5238]
An effort to simplify and provide clear details on the console output of Minio server (a la TLDR). 
## Current Behavior
There are 5 separate lines for each link pointing to Go, Java, Python, JavaScript and .NET separately. 

## Possible Solution
Consolidate all links to a landing document link and still keep the supported languages APIs 

## Steps to Reproduce (for bugs)

1. start minio server

## Context
Current View:
```
Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```
Possible View:
```
Object API (Amazon S3 compatible):
   Go, Java, Python, JavaScript & .NET: https://docs.minio.io/docs/quickstart-guides
```

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
After internal discussions, we have decided not to consolidate the links. Hence closing the issue.
