### ISSUE TITLE
io.minio.errors.ErrorResponseException: We encountered an internal error, please try again.

### ISSUE THREAD

**Issue by dingjs** [minio/minio#5254]
When I call minioClient.puObject,I got this exception a few times.
> io.minio.errors.ErrorResponseException: We encountered an internal error, please try again.
        at io.minio.MinioClient.execute(MinioClient.java:1200) ~[minio-3.0.8.jar:3.0.8]
        at io.minio.MinioClient.executePost(MinioClient.java:1347) ~[minio-3.0.8.jar:3.0.8]
        at io.minio.MinioClient.initMultipartUpload(MinioClient.java:4276) ~[minio-3.0.8.jar:3.0.8]
        at io.minio.MinioClient.putObject(MinioClient.java:3751) ~[minio-3.0.8.jar:3.0.8]
        at io.minio.MinioClient.putObject(MinioClient.java:3380) ~[minio-3.0.8.jar:3.0.8]

This is the minio server logs
> time="2017-12-01T09:38:53Z" level=error msg="Unable to initiate new multipart upload id." cause="mkdir /data/.minio.sys/multipart/writkeeper/2017/12/01: no such file or directory" source="[object-handlers.go:677:objectAPIHandlers.NewMultipartUploadHandler()]" stack="fs-v1-multipart.go:375:fsObjects.newMultipartUpload fs-v1-multipart.go:423:fsObjects.NewMultipartUpload <autogenerated>:1:(*fsObjects).NewMultipartUpload object-handlers.go:675:objectAPIHandlers.NewMultipartUploadHandler api-router.go:55:(objectAPIHandlers).NewMultipartUploadHandler-fm"
time="2017-12-01T09:40:44Z" level=error msg="Unable to initiate new multipart upload id." cause="mkdir /data/.minio.sys/multipart/writkeeper/2017/12/01/tpl/basetpl: no such file or directory" source="[object-handlers.go:677:objectAPIHandlers.NewMultipartUploadHandler()]" stack="fs-v1-multipart.go:375:fsObjects.newMultipartUpload fs-v1-multipart.go:423:fsObjects.NewMultipartUpload <autogenerated>:1:(*fsObjects).NewMultipartUpload object-handlers.go:675:objectAPIHandlers.NewMultipartUploadHandler api-router.go:55:(objectAPIHandlers).NewMultipartUploadHandler-fm"
time="2017-12-01T09:41:32Z" level=error msg="Unable to initiate new multipart upload id." cause="mkdir /data/.minio.sys/multipart/writkeeper/2017/12: no such file or directory" source="[object-handlers.go:677:objectAPIHandlers.NewMultipartUploadHandler()]" stack="fs-v1-multipart.go:375:fsObjects.newMultipartUpload fs-v1-multipart.go:423:fsObjects.NewMultipartUpload <autogenerated>:1:(*fsObjects).NewMultipartUpload object-handlers.go:675:objectAPIHandlers.NewMultipartUploadHandler api-router.go:55:(objectAPIHandlers).NewMultipartUploadHandler-fm"

### Minio Server
1.  Linux version 4.12.8-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Aug 17 09:11:11 EDT 2017
2. Minio Server docker version 2017-11-22T19:55:46Z

### Minio Client 
1. Minio Java Client 3.0.8

**Comment by harshavardhana** [comment]
What is you backend filesystem?

**Comment by harshavardhana** [comment]
Also is it reproducible consistently?

**Comment by harshavardhana** [comment]
Navigation through the code i can observe that the only line that generates this error is `os.MkdirAll` 

```
 // Create - creates a new write locked file instance.                                                                                                                        
 // - if the file doesn't exist. We create the file and hold lock.                                                                                                            
 func (fsi *fsIOPool) Create(path string) (wlk *lock.LockedFile, err error) {                                                                                                 
         if err = checkPathLength(path); err != nil {                                                                                                                         
                 return nil, err                                                                                                                                              
         }                                                                                                                                                                    
                                                                                                                                                                              
         // Creates parent if missing.                                                                                                                                        
         if err = os.MkdirAll(pathutil.Dir(path), 0777); err != nil {                                                                                                         
                 if os.IsPermission(err) {                                                                                                                                    
                         return nil, errFileAccessDenied                                                                                                                      
                 } else if isSysErrNotDir(err) {                                                                                                                              
                         return nil, errFileAccessDenied                                                                                                                      
                 }                                                                                                                                                            
                 return nil, err                                                                                                                                              
         }                                       
```

And Go can generate this error only here inside `os.MkdirAll`

```
	// Parent now exists; invoke Mkdir and use its result.
  	err = Mkdir(path, perm) --------> Here
  	if err != nil {
  		// Handle arguments like "foo/." by
  		// double-checking that directory doesn't exist.
  		dir, err1 := Lstat(path)
  		if err1 == nil && dir.IsDir() {
  			return nil
  		}
  		return err
  	}
  	return nil
```

its almost like the parent was deleted while the `MkdirAll` was being attempted.  

Here are few questions for you to answer

 - What is the backend filesystem under use?
 - Are you using shared backend mode where multiple multiple servers are sharing the same backend?

**Comment by dingjs** [comment]
@harshavardhana 
Thank you for your reply.
>  What is you backend filesystem?  

The backend filesystem is xfs.

> Also is it reproducible consistently?

No, is not reproducible consistently.I call putObject tens of thousands of times,and only got a few times of this exception.

> Are you using shared backend mode where multiple multiple servers are sharing the same backend?

No,I'm not.

I'm noticing in the .minio.sys/multipart/ folder,bucketName sub folder being created and deleted automatically.If it is the normal thing, could it be two multipart upload in the same bucket,one upload is finished and delete the bucketName folder ,the other could not create the folders in the bucketName,so throw the exception.This is my humble opinion.
I use files smaller than 5MB in most of my test cases, which won't do the multiple parts upload.I shall test files larger than  5MB more often.

**Comment by harshavardhana** [comment]
> I'm noticing in the .minio.sys/multipart/ folder,bucketName sub folder being created and deleted automatically.If it is the normal thing, could it be two multipart upload in the same bucket,one upload is finished and delete the bucketName folder ,the other could not create the folders in the bucketName,so throw the exception.This is my humble opinion.

yes that is expected, but we do not rely on the parent directories to be created, but MkdirAll has a race basically since it recursively creates directories one by one it is quite possible that one of the parent is deleted due to completion of multipart upload and the subsequent `os.Mkdir` doesn't see it and fails with ENOENT

There must be a race here @dingjs as i stated above,  let me think about a few scenarios where this can occur. 

how are your object names organized? can you provide a list of object names which are > 5MiB which you uploaded failed with the above error?

**Comment by dingjs** [comment]
> how are your object names organized? can you provide a list of object names which are > 5MiB which you uploaded failed with the above error?

Yes,We use 6 threads constantly call putObject in the same bucket (writkeeper) with the same prefix (year/month/day),the object name is a uuid string with a business name.
The object names which failed maybe with the names like uuid-null.

**Comment by harshavardhana** [comment]
> Yes,We use 6 threads constantly call putObject in the same bucket (writkeeper) with the same prefix (year/month/day),the object name is a uuid string with a business name.
> The object names which failed maybe with the names like uuid-null.

I see @dingjs thanks will try to reproduce this.

**Comment by harshavardhana** [comment]
@dingjs sorry for responding late, haven't had time to reproduce this. Will be looking at this soon.

**Comment by dingjs** [comment]
@harshavardhana Thanks.

**Comment by harshavardhana** [comment]
I tried to reproduce this but it isn't seem to be easy, @dingjs do you have a sample code for this that i can use locally to reproduce?

**Comment by harshavardhana** [comment]
> I tried to reproduce this but it isn't seem to be easy, @dingjs do you have a sample code for this that i can use locally to reproduce?

If not for sample code, can you provide a skeletal directory structure? that i can use to reproduce this? @dingjs  - Thanks

**Comment by dingjs** [comment]
> If not for sample code, can you provide a skeletal directory structure? that i can use to reproduce this? @dingjs - Thanks

Sorry for the late response.As far as I know,my collegue only called
``` java 
minioClient.putObject(bucket, objectName, new ByteArrayInputStream(data), "application/msword");
```
The directory structure is 
```
/writkeeper/yyyy/MM/dd/tpl/basetpl/word/
```

There are two things which I think it had something to to with the minio server error.
1. My collegue use 6 threads to migrate the data in mongodb to minio.
2. After  my collegue called putObject or getObject,she did not close the stream.I know it would cause a resource leak,not sure is the minio server error had anything to do with it. 

After the magor release of my own project,I will looking into this problem.
Thanks for you errort.It means a lot to me.

**Comment by harshavardhana** [comment]
Thanks @dingjs

**Comment by harshavardhana** [comment]
> The directory structure is
> 
> /writkeeper/yyyy/MM/dd/tpl/basetpl/word/
> There are two things which I think it had something to to with the minio server error.
> 
> My collegue use 6 threads to migrate the data in mongodb to minio.
> After my collegue called putObject or getObject,she did not close the stream.I know it would cause a resource leak,not sure is the minio server error had anything to do with it.

Is the delete being called? @dingjs the delete called on the object directly or its being deleted recursively?

**Comment by dingjs** [comment]
no,i,don't see delete

**Comment by dingjs** [comment]
no,i,don't see delete

**Comment by dingjs** [comment]
no,i,don't see delete

**Comment by dingjs** [comment]
no,i,don't see delete

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/5376 @dingjs is a possible fix in this scenario would you mind giving it a test run?

**Comment by dingjs** [comment]
Sure,How do I test?

**Comment by dingjs** [comment]
>  is a possible fix in this scenario would you mind giving it a test run?

@harshavardhana  Hi,I did thousands of multipart upload,but can't reproduce the error.
If there is a new release,I'll update to the new version and see how it is going.
Thanks!

**Comment by harshavardhana** [comment]
> @harshavardhana Hi,I did thousands of multipart upload,but can't reproduce the error.
> If there is a new release,I'll update to the new version and see how it is going.
> Thanks

@dingjs we will make a release soon.

**Comment by brauliobo** [comment]
I'm seeing this when doing a lot of IO, are there any logs to check what the error was exactly? is ulimit configured properly on the docker image?

**Comment by harshavardhana** [comment]
Can you elaborate more on lot of IO ? Do you have any server logs ? . Also please open a new GitHub issue.
