### ISSUE TITLE
Inconsistency in data when some servers stopped working

### ISSUE THREAD

**Issue by ifelsenayeem** [minio/minio#5260]
1. Started minio cluster,
./minio server http://192.168.35.11/data http://192.168.35.12/data http://192.168.35.13/data http://192.168.35.14/data

2. Uploaded an image Test_01.jpg

3. Stopped server four (i.e, 192.168.35.14)

4. Uploaded another image Test_02.jpg

5. Started server four (i.e, 192.168.35.14)

## Expected Behavior
Server four should be having the image Test_02.jpg

## Current Behavior
Only server one, two and three are having both Test_01.jpg & Test_02.jpg

## Context
I need same data in all the servers.

## Your Environment
* Version used (`minio version`): 2017-11-22T19:55:46Z
* Environment name and version (e.g. nginx 1.9.1): nginx 1.7.7
* Operating System and version (`uname -a`): GNU/Linux (Ubuntu x86_64)

**Comment by ifelsenayeem** [comment]
I'm closing this task, because I got the solution #5016

**Comment by vadmeste** [comment]
Thanks @nayeemnayyu, you can join us here https://slack.minio.com if you have further questions.
