### ISSUE TITLE
Invalid bucket name, Google Cloud Storage gateway

### ISSUE THREAD

**Issue by ruslan-polutsygan** [minio/minio#5261]
Hello.
Original discussion is there https://github.com/minio/minio-js/issues/652#issuecomment-348980484
Briefly: I can't create new bucket using minio-js library, but it goes fine when I do this from gateway web interface (`127.0.0.1:9000`). 

Deeply inside js-library, I received such xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidBucketName</Code>
    <Message>The specified bucket is not valid.</Message>
    <Key></Key>
    <BucketName></BucketName>
    <Resource>/tabbacacaabbacacaabbacaca</Resource>
    <RequestId>3L137</RequestId>
    <HostId>3L137</HostId>
</Error>
```
Can you advice anything?

## Expected Behavior
Bucket is created successfully.

## Current Behavior
Bucket is not created.

## Context
I'm trying to use gcs-gateway to store files in google cloud storage
 
## Your Environment
* Version used (`minio version`):
```
Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48
```
* Server type and version: Local, binary (I mean, not via docker)
* Operating System and version (`uname -a`): Ubuntu 14.04

Thanks in advance

**Comment by ruslan-polutsygan** [comment]
I've found what was the problem. 
I tried to create bucket in `eu-west-3`, which was OK for minio-server, but not good for GCS. GCS has region `europe-west3`. When changed region - it started working. 

Shouldn't minio server map regions? Or at least say something more sensible, not just "The specified bucket is not valid"? Or it receives above XML from google?

Thanks

**Comment by krishnasrinivas** [comment]
> Shouldn't minio server map regions?

We can't map regions as it is not one-to-one mapping for many regions.

> Or at least say something more sensible, not just "The specified bucket is not valid"?

Was there no log by minio server?

**Comment by ruslan-polutsygan** [comment]
There is following message in terminal where minio is running:
```
ERRO[0146] Unable to create a bucket.                    cause=Bucket name invalid: s-t-abbacacaabbacacaabbacaca source=[gateway-handlers.go:626:gatewayAPIHandlers.PutBucketHandler()] stack=gateway-gcs.go:427:(*gcsGateway).MakeBucketWithLocation gateway-handlers.go:624:gatewayAPIHandlers.PutBucketHandler gateway-router.go:120:(gatewayAPIHandlers).PutBucketHandler-fm
```
Or you mean some other logs? Where are they located?

**Comment by krishnasrinivas** [comment]
Previously it would return misleading invalid-bucket:
```
krishna@escape:~$ mc mb myminio/kris1980 --region=eu-west-3
mc: <ERROR> Unable to make bucket `myminio/kris1980`. The specified bucket is not valid.
krishna@escape:~$
```

after the fix it returns a generic invalid-request:
```
krishna@escape:~$ mc mb myminio/kris1980 --region=eu-west-3
mc: <ERROR> Unable to make bucket `myminio/kris1980`. Invalid Request
krishna@escape:~$
```

**Comment by krishnasrinivas** [comment]
There is a problem in the above fix. For make bucket of `aws-sdk-php-bucket-24013--` it fails with `InvalidRequest` instead of `InvalidBucket` which is not desirable. Google replies with a generic `invalid` requiest, i.e we will not know if GCS is talking about invali bucket name or some other invalid request. Hence we can leave the current behaviour as it is.

**Comment by krishnasrinivas** [comment]
@ruslan-polutsygan we will close the issue because of the lack of distinct error responses from GCS. If this becomes an issue, we can relook at this in future.

**Comment by ruslan-polutsygan** [comment]
thanks
