### ISSUE TITLE
[question] What is not ready for production in gcs-gateway

### ISSUE THREAD

**Issue by ruslan-polutsygan** [minio/minio#5269]
Hello

When I start minio in `gcs-gateway` it says it is not production ready.
Can you please explain what doesn't work or works unstable yet? What cases in integration are not covered?

Thanks

**Comment by harshavardhana** [comment]
The limitations are mentioned in [docs.md](https://github.com/minio/minio/blob/master/docs/gateway/gcs.md). We kept it beta until now for the gateway to stabilize. We will be removing it in upcoming releases.

**Comment by glensc** [comment]
@harshavardhana `docs.md` link 404 in your last post.

**Comment by harshavardhana** [comment]
> @harshavardhana docs.md link 404 in your last post.

what i meant was this https://github.com/minio/minio/blob/master/docs/gateway/gcs.md

**Comment by nitisht** [comment]
closing as resolved

**Comment by ruslan-polutsygan** [comment]
Thanks

**Comment by solsson** [comment]
Is there architectural reasons for GCS gateway not supporting notifications, or is it - understandably - just lower priority than a lot of things?

**Comment by harshavardhana** [comment]
> Is there architectural reasons for GCS gateway not supporting notifications, or is it - understandably - just lower priority than a lot of things?

It is architectural - implementing notifications would undermine the requirement of shared nothing architecture of gateways.
