### ISSUE TITLE
S3 v2 signature support

### ISSUE THREAD

**Issue by jonandernovella** [minio/minio#5270]
Currently the S3 client for Pachyderm uses minio-go, which signs using S3 v4 by default. An option should be added to support S2 signatures in [minio-go](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/obj/minio_client.go#L17) and in the [Pachyderm deployment manifesto]( https://github.com/pachyderm/pachyderm/tree/master/src/server/pkg/deploy). This would enable the S3 client to talk with servers using S3 v2.

**Comment by nitisht** [comment]
Thanks @jonandernovella we'll send a fix.

**Comment by nitisht** [comment]
@jonandernovella can you please take a look at this https://github.com/pachyderm/pachyderm/pull/2564

**Comment by harshavardhana** [comment]
This issue should be opened on pachyderm not here, this has nothing to do with minio server. @jonandernovella
