### ISSUE TITLE
Bring back minimum free inodes check?

### ISSUE THREAD

**Issue by donatello** [minio/minio#5277]
## Expected Behavior

Disks with no free inodes should be considered offline or at least produce an error message at server start up - as writes will fail, but reads will work.

## Current Behavior

The server does not check for free inodes, but does check for minimum free disk space (of 1GB) at start up. So if a disk has free space but no free inodes, it will have errors during writing.

## Possible Solution

Have platform specific checks?

## Context

https://github.com/minio/minio/issues/5271

**Comment by harshavardhana** [comment]
Not sure if we can bring this back in a more platform friendly way, perhaps only for Linux we could do this.

**Comment by harshavardhana** [comment]
> Not sure if we can bring this back in a more platform friendly way, perhaps only for Linux we could do this.

@donatello we do not need to do this due to portability issues. Should we close this?
