### ISSUE TITLE
Bucket policies disable object listing

### ISSUE THREAD

**Issue by reshadman** [minio/minio#5279]
How to disable object listing when bucket policy is public/download?

Is it possible to set policies other than (public, download, upload) abstractions? are they fully supported?

**Comment by vadmeste** [comment]
@reshadman, Minio server supports it, but mc and Minio SDKs don't.

You need to use other tools for that purpose. aws cli or aws SDKs can do that.

**Comment by harshavardhana** [comment]
https://gist.github.com/harshavardhana/400558963e4dfe3709623203222ed30c here is a doc about explanation on bucket policies @reshadman

**Comment by reshadman** [comment]
@harshavardhana thanks
I use the following to allow GetObject and disable BucketList but I can not access the file publicly when I deny the bucket list:
```json
{
  "Version": "2012-10-17",
  "Statement": [
      {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Deny",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::%s/*"
      ],
      "Sid": ""
    },
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::%s/*"
      ],
      "Sid": ""
    }
  ]
}
```

**Comment by harshavardhana** [comment]
> @harshavardhana thanks
> I use the following to allow GetObject and disable BucketList but I can not access the file publicly when I deny the bucket list:

The policy is incorrect @reshadman  you need to replace `arn:aws:s3:::%s` where `%s` should be replaced with actual bucket name.  Also in case of `s3:ListBucket` you don't need to explicitly mention it to be `Deny` You can simply remove it here is the simplest policy you need. 

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::testbucket/*"
      ],
      "Sid": ""
    }
  ]
}
```

**Comment by reshadman** [comment]
@harshavardhana Yeah they were being replace with `sprintf` I used your snippet, but still When I goto minio web interface anonymously I see the list of all objects.

Here is my procedure: 
1. Create the bucket
```./aws --endpoint-url https://jobinja-minio-1.jjcloudservices.com s3api create-bucket --bucket aaaa```

2. Put bucket policy from your snippet (which only allows GetObject)
```./aws --endpoint-url https://jobinja-minio-1.jjcloudservices.com s3api put-bucket-policy --bucket testbucket --policy pol.json
```

3. Uploading multiple files to test

When I upload the multiple files I am able to view the entire list, which I should not.

**Comment by reshadman** [comment]
@harshavardhana  Still , I can see the object listing in minio web GUI, I used your snippet on my newly created bucket, and then uploaded multiple files, I can see the full list in my minio web GUI without entering my secrets.

**Comment by harshavardhana** [comment]
> @harshavardhana Still , I can see the object listing in minio web GUI, I used your snippet on my newly created bucket, and then uploaded multiple files, I can see the full list in my minio web GUI without entering my secrets.

I see now this is a behavior in our browser implementation which honors `s3:GetObject` just like `s3:ListBucket` since in UI is not useful if we cannot List the objects users have read-only access.  So if `s3:GetObject` is provided we simply just list anyways.

In a scenario that you have its best to turn off the browser since you won't have much use for it by starting minio server with `MINIO_BROWSER=off`

**Comment by reshadman** [comment]
I see, thanks, this solves my problem, anyway is this logically accepted? the web rpc endpoint will generate unexpected behaviours. as this is not mentioned anywhere in the docs,  is it not better for web endpoint to be a gateway around the internal s3 api gateway?

**Comment by harshavardhana** [comment]
> I see, thanks, this solves my problem, anyway is this logically accepted? the web rpc endpoint will generate unexpected behaviours. as this is not mentioned anywhere in the docs, is it not better for web endpoint to be a gateway around the internal s3 api gateway?

webRPC implements a completely different implementation altogether other than S3 API. WebRPC is not implementing or complying with S3 API implementation and behavior,  The reason its not published is also because since this an expected behavior for primarily browser users.  WebRPC is an internal API and not meant for external consumption. 

What we can additionally do is avoid listing if `s3:ListBucket`  is not part of the Action map.  This way the users do get an expected behavior IMO to comply with S3.

**Comment by justjanne** [comment]
> What we can additionally do is avoid listing if s3:ListBucket is not part of the Action map. This way the users do get an expected behavior IMO to comply with S3.

Could you implement that? It doesn’t seem to actually be implemented yet.

**Comment by pehbehbeh** [comment]
We also need to set the bucket policy to `download` but would like to disable the anonymous listing of files inside the bucket via the Minio Browser GUI.  Because of this issue we need to set `MINIO_BROWSER=off`. Any chance to get an update on this?

**Comment by harshavardhana** [comment]
Sure this can be definitely fixed..

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/6970 fixed in master @justjanne @pehbehbeh

**Comment by pehbehbeh** [comment]
@harshavardhana Thanks a lot! 👍

**Comment by n0guest** [comment]
> #6970 fixed in master @justjanne @pehbehbeh

@harshavardhana, are these changes included in the release 2018-12-19? 

If yes, then how about corresponding changes in mc (minio client)? As I understand for now mc can't assign custom policy to a bucket. And it's possible only via 3rd party tools (like aws cli, etc). It's kind of strange when "native" minio client doesn't support all minio server features. 

What do you think?

**Comment by harshavardhana** [comment]
We won't do it in `mc` - custom policies are part your responsibility to use the SDK and turn off appropriate actions. Server will honor it. 

`mc` appropriately implements the canned policies bringing in right set of abstractions, for most common use cases - it's not meant to entertain all wordly combinations. It is also not meant to mimic an SDK for that we have minio-go which can be used for further customizations.

Browser is already fixed as per last release.

**Comment by n0guest** [comment]
> We won't do it in `mc` - custom policies are part your responsibility to use the SDK and turn off appropriate actions. Server will honor it.

Sorry, maybe I used wrong words. I meant, that from user's point of view mc is "native" tool for administration purposes of minio server. Including setting of pre-existing policies on buckets, managing canned policies and users. Again maybe it's just my impressions, but then such expectations should be "cleared" in early stages - in the docs. I.e.:

> ... you can and should use mc for administration purposes, but keep in mind, that mc provides only basic functionality. And any other stuff you might want you should do via SDK or 3rd party tools such as aws cli, etc".

Or maybe such "plain" explanations already in minio/mc docs and I just missed it? I'm not trying to get some new features, just trying to understand "the right way to work with minio and related tools".

> `mc` appropriately implements the canned policies bringing in right set of abstractions, for most common use cases - it's not meant to entertain all wordly combinations. It is also not meant to mimic an SDK for that we have minio-go which can be used for further customizations.

I understand, that attempt to cover "all possible use cases" - it's somewhere near impossible and surely meaningless. But even if this "usage case" isn't covered by mc features, we're still discussing this matter. I.e. real world scenario where people are using your product in such way. So, should this case at least be placed somewhere in FAQ section (or somewhere similar)?

> Browser is already fixed as per last release.

Thanks for the info and for the great project!

**Comment by ewolfman** [comment]
Update: I created a new issue here: https://github.com/minio/minio/issues/8121
Hi,

Not sure if this is the same issue or not but here goes:
Using a local minio server I am able to set the policy to allow only GetObject and not the http listing.

`{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Principal": {
				"AWS": [
					"*"
				]
			},
			"Action": [
				"s3:GetObject"
			],
			"Resource": [
				"arn:aws:s3:::tmp1/*"
			]
		}
	]
}`

But on Azure, using the latest release (RELEASE.2019-08-14T20-37-41Z), I get this:
"A header you provided implies functionality that is not implemented."

Any idea?

Thanks.

**Comment by bttger** [comment]
If you want to set a policy via SDK, you can pass a stringified JSON instead of the minio policy name. Also, a good resource is the S3 policy generator: https://awspolicygen.s3.amazonaws.com/policygen.html

**Comment by ghost** [comment]
Went through the above solutions mentioned but did not find the use-case solution we need. Please help.

Q. How do I Hide folders which users do not have permission to?
Have configured a policy for restricting a specific user/group to a specific folder in a bucket (code block below)- but we do not want to list other folders/files other than the folders/files which have permission to.
Note: If I remove this s3:ListBucket policy i.e. 2nd and 3rd Sid then the bucket itself is not displayed.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserToSeeBucketListInTheConsole",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets"               
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket"
            ]
        },
        {
            "Sid": "AllowUserListingOfBucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:delimiter": [
                        "/"
                    ],
                    "s3:prefix": [
                        "",
                        "dir1/",
                        "${aws:username}/"                       
                    ]
                }
            }
        },
        {
            "Sid": "AllowListingofUserFolders",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "dir1/${aws:username}/*"
                    ]
                }
            }
        },
        {
            "Sid": "AllowAllS3ActionsInUserFolder",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::tod/dir1/${aws:username}/*"
            ]
        }
    ]
}
```
