### ISSUE TITLE
Break format.json into two smaller json files

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5283]
As of now migrating format.json to a higher version is confusing as it contains fs and xl related information in the same struct. This problem was encountered when trying to migrate the format.json to indicate the change in backend structure for multipart (where we dont support directory hierarchy). Had a discussion here and the following solution was decided:

Break `format.json`:
```
{
  "version": "1",
  "format": "fs",
  "fs": {
    "version": "1"
  }
}
```

into:
format.json:
```
{
  "version": "1",
  "format": "fs",
}
```
and
fs.json:
```
{
    "version": "1"
}
```

Similar change is needed for erasure backend.
I am working on this issue.

**Comment by harshavardhana** [comment]
@krishnasrinivas since we are not doing this approach i think this can be closed.
