### ISSUE TITLE
Multiple HTTP ranges are not supported

### ISSUE THREAD

**Issue by develar** [minio/minio#5285]
## Expected Behavior

`Range: bytes=200-1000, 2000-6576` must be supported.

## Current Behavior

```
ERRO[10530] Invalid request range                         cause='bytes=90192-101170, 51133486-51193973, 51340765-51865167, 52717655-52751805, 52833099-52848311' does not have a valid last byte position value source=[object-handlers.go:145:objectAPIHandlers.GetObjectHandler()]
```

## Possible Solution

Quite strange for me, because yes, — there are no NodeJS libraries for correctly handle Range headers and in my tests I use Go app `ran`. But `minio` is also written in Go, so, not clear why you have own incomplete Range parser (https://github.com/minio/minio/blob/master/cmd/httprange.go).

## Steps to Reproduce (for bugs)

Just send request with multiple ranges, e.g. `Range: bytes=200-1000, 2000-6576`

## Context

I am developer of electron-builder and some of my users reported that Minio is awesome alternative to S3. As part of my integration tests, I have tested Differential Updater and discovered, that actually Minio usage leads to broken differential updates because multiple ranges are not supported.

The main goal of multiple ranges — avoid HTTP request limit (e.g. on GitHub), it allows to download all changed blocks in one HTTP request instead of hundreds.

## Your Environment

* Version used (`minio version`):

Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:14:16 PST 2017; root:xnu-4570.31.3~2/RELEASE_X86_64 x86_64
* Link to your project:

**Comment by harshavardhana** [comment]
Yes this is expected AWS S3 doesn't support multiple ranges and Minio tries to be S3 compatible. 

> Amazon S3 doesn't support retrieving multiple ranges of data per GET request.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html

**Comment by develar** [comment]
Thanks for quick answer, that's interesting, I haven't yet tested S3 because was sure that it works :(

Do you plan to support or want to be compatible even in context of restrictions?

**Comment by develar** [comment]
It seems S3 restricted because you pay for request number :)

**Comment by harshavardhana** [comment]
We want to be compatible as much as possible, and not introduce things around existing spec. When AWS S3 implements multiple ranges we will comply.

**Comment by develar** [comment]
@harshavardhana Ok. I have disabled multiple ranges for S3 and Minio. It leads to a lot of GET requests, but it is ok in general. Thanks for a quick communication.

**Comment by sihunqu123** [comment]
Is it supported now?

**Comment by harshavardhana** [comment]
> Is it supported now?

Once AWS S3 supports this we shall as well

**Comment by harshavardhana** [comment]
This issue is resolved and locked @sihunqu123 please open new issues and do not discuss on old ones.
