### ISSUE TITLE
[admin API] admin config set can kill server

### ISSUE THREAD

**Issue by aead** [minio/minio#5286]
The `mc admin config set` command can kill the server.
The problem is that a client can get the JSON config from the server and duplicate some entries.
If the client uploads the new config the server will unmarshal the JSON config and do some checks.
However the unmarshal ignores duplicate entries. The problem is that the whole client-provided config
is stored which may lead to duplicate entries in the server config. During restart the server than fails because of dup. entries.
See:
 1. https://github.com/minio/minio/blob/master/cmd/admin-handlers.go#L989
 2. https://github.com/minio/minio/blob/master/cmd/admin-handlers.go#L1009

@donatello 

## Expected Behavior
The server should reject duplicate entries.

## Current Behavior
The server stores duplicate entries.

## Possible Solution
Check whether the JSON config contains dup. entries (like during server start) and fail if so.
Insert [here](https://github.com/minio/minio/blob/master/cmd/admin-handlers.go#L996):
```
        // Check that the client does not try to store duplicate JSON entries.
	// Duplicate JSON entries will lead to restart failure -> DoS
	if err = checkDupJSONKeys(string(configBytes)); err != nil {
		errorIf(err, "config contains duplicate JSON entries.")
		writeErrorResponse(w, toAPIErrorCode(err), r.URL)
		return
	}
```

## Steps to Reproduce (for bugs)
1. `minio server [some dir]`
2. `mc admin config get [server name] > config.json`
3.  Now duplicate an entry (like credentials - you can even change the later access/secret key)
4. `cat config.json > mc admin config set [server name]`
5. `mc admin info [server name]` will show offline because the server cannot restart...

play.minio.io will not work since admin API is disabled after this.

## Your Environment
current master

**Comment by abperiasamy** [comment]
Can we also add a check to test if the JSON is loadable?. If the server fails to load, we can simulate it in a check.

**Comment by aead** [comment]
@abperiasamy IIRC the solution provided in the issue is exactly what the server does during start up to check whether the config is valid. But I don't know whether we want to fix at all because of new admin API?! My last info was that we probably wontfix because of new API...

**Comment by donatello** [comment]
I am sending a PR to address this issue in the existing version as the new API will include the existing functionality too.
