### ISSUE TITLE
How to change the bucket length 

### ISSUE THREAD

**Issue by sbala69gmail** [minio/minio#5297]
Hi, 
I want to change the bucket name in 2 digit.  Is it any possible?

**Comment by nitisht** [comment]
@sbala69gmail Minio is S3 compatible and S3 Bucket names should be at least 3 characters long. Ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by nitisht** [comment]
Closing this as working as intended, for further questions please join us on Slack: https://slack.minio.io
