### ISSUE TITLE
SignatureDoesNotMatch on browser-generated public links without port

### ISSUE THREAD

**Issue by dexafree** [minio/minio#5298]
I just installed minio on a computer I have exposed to internet for my personal projects.

I installed it using a `docker-compose.yml` with the following contents:

```yaml
minio:
  image: minio/minio:latest
  restart: always
  environment:
    - MINIO_DOMAIN=minio.my.domain.com
    - MINIO_REGION=eu-west-1
  volumes:
    - '/mnt/docker/minio/data:/data'
    - '/mnt/docker/minio/config:/root/.minio'
  ports:
    - "9898:9000"
  command: "server /data"
```

For the record, I have it exposed behind an NGINX reverse proxy and a self-signed HTTPS cert. I've already tried with other servers, such as Caddy.

The NGINX config is the following:

```nginx
upstream minio {
  server 127.0.0.1:9898;
}

server {
    listen 80;
    server_name minio.my.domain.com;
    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name minio.my.domain.com;
    include snippets/self-signed.conf;
    include snippets/ssl-params.conf;
    location / {
        proxy_pass http://minio;
    }
}
```

Everything worked as a charm, I could access with my access/secret keys, create buckets, upload files... but when it came to generating download links, I have problems, but only in certain conditions.

As the machine is on my local network too, I can access it via ip:port.

When I access the online browser **via minio.my.domain.com** and generate a public download link for a file (with a read-only policy for the bucket), it gives me a link that, when accessed, returns a ** SignatureDoesNotMatch** error. 
However, if I access the online browser via ip:port and generate a public download link for the same exact file, it lets me access it without problems.

I have also set the domain in the `config.json` file (I tried with and without specifying the scheme, same result).

## Expected Behavior

When I generate a public link, no matter how I access the public browser, it should let me access the resource.

## Current Behavior

Browser-generated links don't work when generated and accessed via a custom domain, only when accessed via ip:port.

## Steps to Reproduce (for bugs)
1. Deploy a minio with docker under a subdomain
2. Access the minio browser via subdomain
3. Create a bucket
4. Upload a file to the bucket
5. Set the bucket policy to *: readonly
6. Create a public link for the file you just uploaded
7. Access that link. You should see a **SignatureDoesNotMatch** error.
8. Access the minio browser via ip:port
9. Access the same bucket
10. Generate a public link for the same object
11. Access that second link, and you will be able to see/download the file

## Context

I just want to use it for simple file storage, and add/retrieve files to it via other applications I may develop.

## Your Environment

* Version used (`minio version`): 2017-11-22T19:55:46Z
* Environment name and version (e.g. nginx 1.9.1): nginx/1.12.2
* Server type and version:
  * macOS Sierra 
  * Ubuntu 16.04.3 LTS
* Operating System and version (`uname -a`): 
  * macOS: 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 i386 MacBookPro8,1 Darwin
  * Ubuntu: Linux 4.5.7-std-3 #1 SMP Tue Jul 12 09:56:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

EDIT: Is also worth saying that if I just click the file in the web browser I can download it without any problem (but that does not solve the problem of generating public links).

**Comment by dexafree** [comment]
I close this issue myself, as I've just found why it wasn't working.
After hours of research, I realized that I missed the Host directive on both reverse proxy configurations I had set.

For completeness, I missed those ones:

**Nginx**

```nginx
location / {
	proxy_set_header Host            $host;
	proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://minio;
}
```

**Caddyfile**

```
proxy / localhost:9898 {
      transparent
}
```

Closing as it's not a minio bug.

**Comment by harshavardhana** [comment]
FWIW @dexafree its clearly mentioned in https://docs.minio.io/docs/setup-nginx-proxy-with-minio

**Comment by dexafree** [comment]
Yes, after spending some hours researching I found that section on the docs (I must have missed it while looking on the docs).
When I found it I compared the configs, and realized I was missing the Host header.

Sorry!
