### ISSUE TITLE
Accessing minio server via boto api

### ISSUE THREAD

**Issue by Vjust** [minio/minio#5301]
An existing django app uses S3 via boto2 .  Now we want to port it to use minio, with (hopefully) minimal code changes . (i.e. our media is currently on AWS / s3 storage,  we want to move it out to our own minio server 192.168.x.x - hopefully  the existing boto code/calls will be able to manage the media under minio).

## What works
1) _AWS cli works fine_ : "aws --end-point 192.168.x.x:9000  s3 ls <bucketname> " works fine, and "aws s3 cp" also works fine with the endpoint url (192.168.x.x is where minio is installed)
2) created an mc (minioclient) config and : "mc ls myminio " also works
3) Browsing the endpoint above in (1), also works fine. i.e. the browser access to http://192.168.x.x/minio" works.

## Desired behavior (What does not work)
What does not work is these steps inside ipython.  Basically any kind of boto-api access , I'm unable to make it work. It times out.  I am using the same access keys as used in the tests above. No error messages appear in ipython, and none on the minio console.

> import boto
> conn = boto.connect_s3(<keys>..)
> conn.get_bucket("buckname")

Have tried to use boto config file .. In other articles I saw I need to set the SIGV4 variable.  So that is also set in .bashrc.  

> Boto config 👍 
> [default]  (I've replicated this section under [s3], [boto] within the same "~/.boto" file.
> is_secure = False
> host = 192.168.x.x
> port = 9000
> endpoints_path = ...  

At this point I am wondering if minio supports a boto interface at all.  (This would be a deal breaker.)  If this support isn't there, do you have an equivalent API that replaces the boto library.

**Comment by harshavardhana** [comment]
Have you looked at https://docs.minio.io/docs/how-to-use-aws-sdk-for-python-with-minio-server ?

**Comment by Vjust** [comment]
Thanks. Will try this out.

**Comment by Vjust** [comment]
This works.

By any chance, is there a  boto2 solution? - the current app is using boto2, and I 'd ideally minimize code changes.

**Comment by harshavardhana** [comment]
Since boto2 is legacy we never documented it. But can give you a simple snippet ..

**Comment by harshavardhana** [comment]
@Vjust here is a sample, sorry for the delay. 

```py
import boto                                                                                                                                                                   
import boto.s3.connection                                                                                                                                                     
                                                                                                                                                                              
conn = boto.connect_s3(                                                                                                                                                       
    aws_access_key_id = 'minio',                                                                                                                                              
    aws_secret_access_key = 'minio123',                                                                                                                                       
    host = 'localhost',                                                                                                                                                       
    port = 9000,                                                                                                                                                              
    is_secure = False,                                                                                                                                                        
)                                                                                                                                                                             
                                                                                                                                                                              
for bucket in conn.get_all_buckets():                                                                                                                                         
    print "{name}".format(                                                                                                                                                    
        name = bucket.name,                                                                                                                                                   
    )  
```

**Comment by harshavardhana** [comment]
Going to close this as answered @Vjust , feel free to open new issues if you have more questions.

**Comment by Vjust** [comment]
Hi @harshavardhana : Thanks for this sample.  Your code works, but I am hitting an error.  In your example (with boto2) ,  when I try it , the "get_all_buckets" call works fine (i.e returns the name of each of the buckets I have , 2 buckets).. but the subsequent "get_bucket" call fails.  (It times out)..  Now it *could* be my local private network - but that's unlikely (I use mysql, and other services between the two exact same machines - and they work fully)..

So why would conn.get_all_buckets() work fine, but not get_bucket("bucket_name").

I have used /etc/boto.cfg to specify "is_secure = False".. How would you set the config settings.

**Comment by zgoda-mobica** [comment]
It fails even if minio is running locally in docker container with `gaierror: [Errno 8] nodename nor servname provided, or not known`

**Comment by naveenmahadevuni** [comment]
Hi, This issue exists when using AWS C++ SDK too. I have tried s3v4 signature by passing"Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always" to S3Client constructor, but it didn't work too. Is minio tested with C++ SDK?

**Comment by naveenmahadevuni** [comment]
Hi, This issue exists when using AWS C++ SDK too. I have tried s3v4 signature by passing"Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always" to S3Client constructor, but it didn't work too. Does minio support AWS C++ SDK?

**Comment by harshavardhana** [comment]
Please open a new GitHub issue @naveenmahadevuni
