### ISSUE TITLE
Different signatures calculated from client and server

### ISSUE THREAD

**Issue by reshadman** [minio/minio#5303]
I use aws php sdk in my Laravel app to interact with minio. When I upload a file and then immediately access it I get a 403 error, which tells me the client's provided signature is wrong 
## Expected Behavior
When I upload a file I should be able to immediately view it. but currently I can not.

## Current Behavior
After I upload a file with aws-php-sdk I can not access it for exactly one minute. (I got a 403)

## Possible Solution
It seems something related to date time, I have checked the date time on both servers and they are correct.

## Steps to Reproduce (for bugs)
1. [Using this how-to for working with minio in Laravel](https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-as-laravel-file-storage.md)
2. Create a sample bucket in minio
3. Upload a file to that bucket with the Laravel driver mentioned above.
4. Get the file with the same driver (403 Access Forbidden)
5. Get the file again after exactly 60 seconds (200 Successful)

## Your Environment

* Version used (`minio version`): 2017-11-22T19:55:46Z
* Operating System and version (`uname -a`): Linux Ubuntu 16.04

**Comment by harshavardhana** [comment]
What is the exact error that you see, i.e the response body other than http status 403 ? Can you enable env MINIO_HTTP_TRACE=1 for Minio server and provide us the console logs?

**Comment by reshadman** [comment]
@harshavardhana It seems the problem is because of putting cloudflare in front of minio, I also have checked that the request is logged in the console from the server, Do you have any suggestions on this?

**Comment by harshavardhana** [comment]
If cloudflare modifies the request in any manner by adding and removing headers then it is quite possible to see these errors.  You might have to check if cloudflare has an option to turn off mangling with request headers.
