### ISSUE TITLE
Error when using gateway for OCI(Oracle cluster infrastructure) S3 storage

### ISSUE THREAD

**Issue by akaFalsh** [minio/minio#5304]
I am trying to use minio as a gateway to OCI(Oracle cluster infrastructure) S3 storage.

## Expected Behavior
I had configured minio as gateway to OCI(Oracle cluster infrastructure) S3 storage as it is described in manual. Filled in all needed:
1) Exported needed keys:
export MINIO_ACCESS_KEY=ocid1.credential.oc1.xxxxx
export MINIO_SECRET_KEY=xxxxxxxxxxx
export MINIO_REGION="eu-frankfurt-1"
2) Started gateway:
./minio gateway s3 https://xxx.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
3) After trying loging in to minio web interface I recieve an error.

## Current Behavior
minio returned an error:
ERRO[0058] Unexpected error, please report this issue at https://github.com/minio/minio/issues  cause=com.oracle.pic.casper.integration.auth.dataplane.exceptions.NotAuthenticatedException: Authentication region name'us-east-1' is incorrect. source=[web-handlers.go:1098:toWebAPIError()]

## Your Environment

* Version used (`minio version`):
```
./minio version
Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48
```
* Server type and version:
```
Ubuntu 16.04.3 LTS
```
* Operating System and version (`uname -a`):
```
Linux test-s3 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
What happens when you do not set MINIO_REGION ?

**Comment by akaFalsh** [comment]
The same error still occurs even when MINIO_REGION is not set.

**Comment by harshavardhana** [comment]
> The same error still occurs even when MINIO_REGION is not set.

In S3 gateway we use minio-go SDK to make a GetBucketLocation() call to ensure that we get the right location of the bucket that you are trying to access, also ListBuckets() is called as well which uses `us-east-1` as the region. 

The code works fine with AWS S3 and Minio - does OCI work differently? are there any docs which provide details on what are the default region requirements? also does OCI support signature v4?

**Comment by harshavardhana** [comment]
Found it https://docs.us-phoenix-1.oraclecloud.com/Content/Object/Tasks/s3compatibleapi.htm#notableDifferences there are quite a few notable differences and it is not fully S3 compatible.  `minio gateway s3` will not work with OCI, Minio S3 gateway implementation expects the remote server to be fully S3 compatible. 

We need to implement a newer gateway which supports OCI natively in this scenario.

**Comment by akaFalsh** [comment]
It would be nice to have this feature.

**Comment by harshavardhana** [comment]
> We need to implement a newer gateway which supports OCI natively in this scenario.

Moving this to blocked for further discussion and closure if we are not prioritizing this now.

**Comment by harshavardhana** [comment]
@deekoder we can close this since OCI (Oracle Cluster Infrastructure) we might not work on this feature in near future.

**Comment by akaFalsh** [comment]
Can I take this issue? I had started some development.

**Comment by harshavardhana** [comment]
> Can I take this issue? I had started some development.

Feel free to send a PR @akaFalsh , once you have finished please validate with https://github.com/minio/mint

**Comment by akaFalsh** [comment]
Thanks

**Comment by harshavardhana** [comment]
Going to close this issue and perhaps open in future, when we plan on implementing it.
