### ISSUE TITLE
Multiple access and secret key pairs

### ISSUE THREAD

**Issue by mvrhov** [minio/minio#5305]
## Expected Behavior
Have the ability to specif multiple Access/secret key pairs.

## Current Behavior
Only one access and secret key available.

## Context
We would like to give the access to the bucket to multiple 3rd parties. Each of them should have it's own pair that we can disable if he starts to abuse the storage access

**Comment by nitisht** [comment]
@mvrhov We are going to implement https://github.com/minio/mfs can you please take a look there

**Comment by harshavardhana** [comment]
MSF is a minio federation project currently under progress, which would implement support for multi access keys as one of the feature.

**Comment by mvrhov** [comment]
Thanks for letting me know. Any chance this remains open until this is implemented. So I can automatically get a notification.

**Comment by nitisht** [comment]
@mvrhov you can just _watch_ https://github.com/minio/mfs for notifications on that project. IMO we can close this issue.

**Comment by mvrhov** [comment]
Yeah, but watching the project pollutes my inbox

**Comment by nitisht** [comment]
> Yeah, but watching the project pollutes my inbox

@mvrhov then creating an issue here https://github.com/minio/mfs will be better.

**Comment by nogweii** [comment]
Since msf is marked as deprecated and it's ideas incorporated into minio itself (rather than existing separately) should this issue be re-opened? minio/msf#2 hasn't been marked resolved yet.

**Comment by harshavardhana** [comment]
Yes good thinking @evaryont

**Comment by erma07** [comment]
When will this feature be implemented? Any chance credential pair permissions could also be defined per bucket?

**Comment by tnatanael** [comment]
Any news?

**Comment by harshavardhana** [comment]
> Any news?

This is in future @thiagonatanael @erkimarks currently we are working on other priorities.

**Comment by tnatanael** [comment]
Sure, really thx! The software is awesone!

**Comment by craSH** [comment]
Hello, this is a feature that I would like / need before I can roll out Minio for some internal uses (which are all inherently multi-user) at my company, please consider this an additional request to prioritize the feature. Thanks!

**Comment by diogojesus95** [comment]
+1 We also need this to implement private buckets over different co-workers for internal use

**Comment by devinmartin** [comment]
I can certainly appreciate keeping Minio a "single responsibility" micro-service. Minio is responsible in my mind for storage durability and availability.

Seems to me, a good approach would be to create a second gateway that implements the S3 api's as well, but does nothing more (I realized this is complicated) than emulate multi-tennant IAM style policies. It has the single root keys to Minio stored securely inside which it only uses for carrying out storage operations that are authorized. It add a layer of policy evaluation against the more granular credentials that it can issue out and relies on Minio for the actual storage on the backend.

Then companies can choose whether to deploy Minio by itself, or deploy minio along with the IAM emulator that sits in front of it. All without modifying Minio at all. Let Minio manage storage durability and availability which it already does so well, and move ACL into a service that sits in front of it. 

I didn't quite understand the federator architecture, but it appeared that Minio was going to interact with it in some way. If that ever materialized I'm interested, but this could be an alternate approach that emulates IAM fairly well without bloating Minio.

Minio proper has the job of battling the forces of entropy to keep your data in tact. MinIAM (or whatever) has the quite separate job of managing access policies. And is an add on for those who need it.

**Comment by harshavardhana** [comment]
We are already implementing IAM style OpenID connect with client grants as part of Minio, which would provide a way to associate rotating keys with your resources such as bucket and object.  Perhaps even apply policies on each call as well. @devinmartin

**Comment by kallisti5** [comment]
At minimum, it would be nice to have an optional "per bucket" access key in addition to the global one..  This is the one major stumble I found deploying minio. (otherwise it is *AWESOME* and just what we were looking for)

**Comment by alshabib** [comment]
This would be a great feature. Any news or ETD?

**Comment by nogweii** [comment]
@alshabib @edingroot Watch https://github.com/minio/minio/pull/6176 for progress on this.

**Comment by nitisht** [comment]
Moving to @harshavardhana as he is working on this

**Comment by harshavardhana** [comment]
This is fixed and released - closing.

**Comment by erdii** [comment]
Is there a way to "pre-seed" minio with multiple key-pairs with different IAM policies?
We'd like to use minio in a kubernetes/docker like environment, where it would not be feasible, to configure minio after it started, but instead would like to use a declarative approach where key-pairs are created outside of minio and injected via envvars.

**Comment by harshavardhana** [comment]
Please open a new issue with a feature request, let's avoid discussion on older issues @erdii

**Comment by erdii** [comment]
@harshavardhana Sorry! I just wanted to know if my scenario is possible with a current minio release. Guess that's a no from you, though. :(

Thanks for your fast answer, anyways!

Edit: I think there is a possiblity to achieve what I wanted. Posting this here, because it is tied to the feature requested and implemented in this issue. `data/.minio.sys/config/iam/users` contains a folder for each user, named as the access key (eg `iam/users/my_access_key`), which, in turn, contains two files:
* `identity.json`: `{"secretKey":"my_secret_key","status":"enabled"}` user secret and enable/disable toggle
* `policy.json`: `"readwrite"` name of the attached ACL policy

Created policies are stored in `data/.minio.sys/config/iam/policies`. Each policy has it's own folder, named as the policy (eg `iam/policies/mytestpolicy`), which in turn, contains a file called `policy.json` with the policy json.
