### ISSUE TITLE
SVG format not support?

### ISSUE THREAD

**Issue by nakamuraagatha** [minio/minio#5307]
I was upload svg format but not show on my website

## Expected Behavior

Please add / support svg

## Your Environment
* Version used (`minio version`): Latest
* Environment name and version : nginx 1.9.1
* Server type and version: Digitalocean Ubuntu 16.04
* Operating System and version : Ubuntu
* Link to your project:

**Comment by kannappanr** [comment]
@nakamuraagatha I do not see any reason, why this would fail. Just as a sanity check, I did test it on the latest released version of minio (RELEASE.2017-11-22T19-55-46Z). All formats are supported. Can you add more information? Are you using the released version of minio, if so, the version used. Do you have an existing bucket that you want to upload the SVG file to?. How are you doing this test? Are you using the browser that comes along with the minio installation or are you using mc to do this test?

**Comment by kannappanr** [comment]
Closing the issue for now. Please re-open the issue if you have more information or you see the problem again with the information requested.

**Comment by nakamuraagatha** [comment]
I'm sorry this error from my wordpress. thanks

**Comment by kannappanr** [comment]
@nakamuraagatha We do not have enough information to help you here. Can you contact us on slack, so that we can help you with your issue?
