### ISSUE TITLE
Managing free disk space

### ISSUE THREAD

**Issue by glensc** [minio/minio#5309]
really hard to find any documentation about the disk space requirement. 
- [min-free-disk 100M](https://github.com/minio/minio/issues/2780#issuecomment-249679435) no longer exists
- [fsMinSpacePercent](https://github.com/minio/minio/issues/2780#issuecomment-249695660) seems to be present in source code only

so it's still hardcoded `5%`? can i configure free-blocks `3GiB` instead?

## Context

I find current percentage based disk space requirement unacceptable, 5% of disk size does not match the impact of upload sizes.

## Your Environment

* Version used (`minio version`): 
  - docker image: `RELEASE.2017-11-22T19-55-46Z`
  - docker image: `RELEASE.2016-10-24T21-23-47Z`

**Comment by harshavardhana** [comment]
No it is not possible to be configure this value @glensc minimum disk space required is 1GiB 

```
const (
        diskMinFreeSpace  = 1 * humanize.GiByte // Min 1GiB free space.
        diskMinTotalSpace = diskMinFreeSpace    // Min 1GiB total space.
```

**Comment by glensc** [comment]
@harshavardhana to be precisely clear: it's always 1GiB free  space required? trying to figure out how to set monitoring to alert.

**Comment by glensc** [comment]
future me, the source that @harshavardhana linked is here:
https://github.com/minio/minio/blob/3d0dced23c45abd8a511831891e2166209766fc4/cmd/posix.go#L35-L37

**Comment by harshavardhana** [comment]
> @harshavardhana to be precisely clear: it's always 1GiB free space required? trying to figure out how to set monitoring to alert.

Yes its always 1GiB @glensc
