### ISSUE TITLE
CoreDNS integration for Minio server

### ISSUE THREAD

**Issue by nitisht** [minio/minio#5314]
Ignoring the template on purpose.

With https://github.com/minio/minio/pull/5095 , Minio server added support for virtual style requests where requests to `bucketname.minio.domain` would be honoured by the Minio server. Here `bucketname` is a bucket created on the Minio server and `minio.domain` is the domain name Minio server is running on. Note that this needs Minio server to be configured with environment variable `MINIO_DOMAIN`. 

However, this still needs the user to 

- either make DNS entries manually as new buckets are being made on Minio server
- create a wildcard entry like `*.minio.domain`

With CoreDNS integration, Minio server can make DNS entries and maintain it (i.e. remove the entries in case a server goes down or a bucket is deleted). Note that CoreDNS would still need to be run as a separate server and _not_ bundled with Minio server in any way. 

Here are the potential steps involved:

- CoreDNS server details are provided in Minio config file, `MINIO_DOMAIN` is set, and DNS Zone in CoreDNS is set accordingly.

- Whenever a new bucket is created, Minio server makes A record entries to CoreDNS server under the given Zone.

- Whenever a bucket is deleted, Minio server removes the corresponding A record entries from CoreDNS server under the given Zone.

- In case if any Minio server instances down (in Distributed Minio setup), corresponding entries should be removed from CoreDNS server.

**Comment by nitisht** [comment]
moved to @harshavardhana as he has already sent the PR #5501

**Comment by harshavardhana** [comment]
Fixed #5501
