### ISSUE TITLE
File's URL button should change with bucket policy

### ISSUE THREAD

**Issue by krzepah** [minio/minio#5318]
I've been struggling to deduce my file's URL. I haven't been playing with minio for a few weeks and when i came back to it I forgot what were the file's URL.

My instinct was to copy paste the URL browser bar (which was on minio) and append it with the file's name.

It turned out as something like this 

[HOST]/minio/media/2-mon_1092-300x234.jpg

The error there was that I left out the /minio/ in the URL. It was a late night and ended-up asking on slack. Without help I'd be going trough the API calls and authenticate the file retrieves EVEN TOUGH I had putted the bucket policy to * Read Only.

So this was my mistake but I'm happy sir KP (on slack) caught me up and gave me the few hints needed. 

Please add a direct link to each files to avoid the confusion :)

**Comment by harshavardhana** [comment]
Browser is meant for browser only and those URLs are valid for browser.. figuring out URL on the client is simply

Just a combination of endpoint+bucket+object

**Comment by krzepah** [comment]
Simple is simple. But confusion comes from it. Avoiding confusion allows greater user experience.

It's true that the thing is pretty well done. However KS suggested the question arises frequently. 

There is simply no UI direct way to get the file's URL. Which is the end problem and the odd thing. Authenticated get_object is not the issue neither the API. It's just the UI that is lacking the end URL which forces us to guess it.

Users shouldn't have to guess stuff. Even tough it's simple.

cheers

**Comment by harshavardhana** [comment]
The proposal to fix it by removing the /minio routing requirement thats the only way to cleanly fix it.

**Comment by krzepah** [comment]
I've so much trouble expressing my self ^^ ; 

It was my mistake on the first place hitting /minio/ ; I did it without notice l8 night copy pasting the URL of Minio's admin which I was on. I tough that appending the file name would head me to the file.

It opened up minio's admin as expected.

The suggestion was to create a direct-link button on each file which would href to [host]/[bucket]/[filename] as if we were properly accessing them.

There isn't any much behaviour to add to it I think.

Tough I'm very well not experienced with Minio neither it's developpement so please take this suggestion as you wish. I hope i've been able to retrace most of my story.

Thanks for your time and dedication :)

**Comment by harshavardhana** [comment]
Moving this to the future requirements if needed to be addressed, for now, we will stay with the current behavior.
