### ISSUE TITLE
Enable notifications by default

### ISSUE THREAD

**Issue by ildar-ceo** [minio/minio#5325]
How to receive all notifications by default without execute command for each bucket:
`./mc events add myminio/images arn:minio:sqs::1:mysql`
?

If I add notification to minio server like this:
`./mc events add myminio arn:minio:sqs::1:mysql`

I get the error:
`mc: <ERROR> Cannot enable notification on the specified bucket. Bucket name cannot be empty`

And how to autoenable notifications for just created bucket?

**Comment by harshavardhana** [comment]
You cannot auto enable notifications upon bucket create in this manner, when we implement MSF federator we would like to bring in policies along these lines.. 

For now you need to do `mc mb` and then `mc events add`

**Comment by ildar-ceo** [comment]
If I create the bucket from web interface. How to enable notifications without console command or autoenable notifications for this bucket?

**Comment by harshavardhana** [comment]
Currently it's not possible to from WebUI.. as I stated above there is no way to auto enable for now.

As an application you can follow this sequence

- you can create a bucket
- you can enable notifications 

If you are not an application then you can use `mc`

**Comment by kannappanr** [comment]
@vistoyn Currently this issue is marked as closed. Please feel free to re-open to issue if you need further clarification.
