### ISSUE TITLE
Notifications for just created bucket.

### ISSUE THREAD

**Issue by ildar-ceo** [minio/minio#5326]
How to receive notification bucket has been just created?

**Comment by harshavardhana** [comment]
There is no S3 API, so we haven't implemented.

**Comment by balamurugana** [comment]
@vistoyn Supported event types are http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html#notification-how-to-event-types-and-destinations

**Comment by kannappanr** [comment]
@vistoyn Closing this issue. Please feel free to re-open the issue, if you feel you need more clarification on this.
