### ISSUE TITLE
How to set password for elasticsearch

### ISSUE THREAD

**Issue by PiaWhoLoveSia** [minio/minio#5329]
I'm trying to publish minio events via Elasticsearch. And the x-pack was installed, so the username and password were needed. I don't see password or username parameter in the `elasticsearch` key in the `~/.minio/config.json`. What's the proper way to set these parameters?

Thank you

**Comment by donatello** [comment]
@PiaWhoLoveSia Apologies for the late response on this. The username and password can be provided as part of the url in the elasticsearch configuration - the format is `http://USERNAME:PASSWORD@elastic.example.com:9200`.

Here is an excerpt from an example server configuration that illustrates the same:

```json
                "elasticsearch": {
                        "1": {
                                "enable": true,
                                "format": "namespace",
                                "url": "http://elastic:MagicWord@localhost:9200",
                                "index": "minio_events"
                        }
                },
```

Thank you for reporting the issue, we will update documentation to highlight authentication.
