### ISSUE TITLE
gateway/manta: Add support for RBAC

### ISSUE THREAD

**Issue by stack72** [minio/minio#5330]
Currently, we are adding support for RBAC in triton-go. This means the same ability will be available to minio when this [PR](https://github.com/joyent/triton-go/pull/82) is merged

This will allow us to run minio as a user other than the main triton account holder

**Comment by kannappanr** [comment]
Referencing the corresponding PR https://github.com/minio/minio/pull/5332

**Comment by harshavardhana** [comment]
RBAC support added on commit a1a98617ca9d681a59082fca0d8bda34818af3ac closing
