### ISSUE TITLE
how to customize the access port

### ISSUE THREAD

**Issue by hikerlook** [minio/minio#5333]
Excuse me, how to customize the access port, rather than the default 9000. 
Thanks.

## Your Environment
* Operating System and version (`uname -a`):
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
you can provide --address have you looked at `minio server -h` ?

**Comment by kannappanr** [comment]
@hikerlook Closing this issue as answered. Please open a new issue if you have further questions.
