### ISSUE TITLE
In what folder/directory does Minio store its objects/files on local disk?

### ISSUE THREAD

**Issue by billmei** [minio/minio#5341]
I'm running a Minio instance on my local machine, on http://localhost:9000. I created a bucket called `foo`, and uploaded a single file `test.txt` to it.

Since this Minio instance is running on my local machine, where is the "uploaded" binary `test.txt` file actually stored in my local filesystem? That is, is it possible to locate this `test.txt` file in a folder somewhere using the GUI filesystem browser? For example, `/Users/myusername/some/hidden/folder/minio/buckets/foo/test.txt`

I looked through [the docs](https://docs.minio.io/docs/minio-client-complete-guide) and it only has information about using the `mc` command via `mc ls` to view the files in the "remote" Minio machine via the command line. This is not what I'm looking for, I want to see under what folder the `test.txt` file actually resides on my local machine. Is this possible, or am I forced to only view an abstraction of the `test.txt` through the `mc` command?

(Cross-post of the StackOverflow question: https://stackoverflow.com/questions/47973268/in-what-folder-directory-does-minio-store-its-objects-files-on-local-disk)

**Comment by nitisht** [comment]
@billmei the file is stored in the mount you pass to start `minio` server. For example if you started `minio` by `minio server /tmp`, create a bucket `foo`, and upload object `bar.txt`. The file will be present at `/tmp/foo/bar.txt`

**Comment by billmei** [comment]
I see it now, thanks @nitisht! I went ahead and added this to the documentation: https://github.com/minio/minio/pull/5342

**Comment by nitisht** [comment]
Closing this as answered, @billmei feel free to join us on [Slack](https://minio.slack.com) for further questions..
