### ISSUE TITLE
SSL error with posting to a minio server.

### ISSUE THREAD

**Issue by mlinsky** [minio/minio#5343]
Hi, i am trying to upload a png file into my minio server that requires ssl, i am following along with what code you have on this page https://docs.minio.io/docs/how-to-use-aws-sdk-for-python-with-minio-server . I have also tried to write code that uses python requests but i keep getting the same error. I have tried my combination of adding certs, auth, and params that included the access key an secret key of minio along with the cert file for the specific project im working on. this is what i currently have in my code. url is the url of the minio server "home" page not the login. here is the path to the image and name is the name of the image. The expected oucome should be a new item in my minio server. It currently is giving me `botocore.vendored.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)`

```
s3 = boto3.resource('s3',
                                    endpoint_url=url,
                                    aws_access_key_id=key_id,
                                    aws_secret_access_key=access_key,
                                    config=Config(signature_version='s3v4'),
                                    region_name='us-east-1')
                s3.Bucket('screenshots').upload_file(here+'/'+name+'.png', name+'.png')

                print('Uploaded ' + name + '.png to the screenshots bucket.')
```

**Comment by mlinsky** [comment]
I did get it to work on a localhost but it still gives that error with my other minio server. I just need a way to properly pass the ssl certs along with the post so it doesnt complain. Everywhere i have looked so far usually just says to set verify to false, but i want/need it to be verified.

**Comment by aead** [comment]
@mlinsky Can you provide some information about your TLS certificate?
Is it a self-signed cert, or a cert you got from a CA like, Let's Encrypt, Comodo etc.?
Further is `certifi` installed on your client?

**Comment by mlinsky** [comment]
@aead The certs i am using are assigned from a CA though i have just been informed that the CA.pem is currently in the project though i wouldnt think thats the problem. This is apparentl a different error someone else found thats working on the same issue. I do not have `Certifi` installed on my client.
```
time="2018-01-02T20:35:37Z" level=error msg="TLS handshake failed with new connection 10.255.0.4:41284 at server 10.255.0.5:9000" cause="remote error: tls: unknown certificate authority" source="[listener.go:177:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
```

**Comment by vadmeste** [comment]
@mlinsky, Minio server prints that message when the client doesn't like the certificate that it receives from the server. 

*) What happens when you open Minio Browser ?
*) What OS are you using ?

**Comment by mlinsky** [comment]
I'm currently looking into the presigned_post_policy. Im not sure how to properlly implement it with what i currently have and changing it to a curl command.

**Comment by mlinsky** [comment]
@vadmeste When i open the browser it opens to the login in, I enter the access key and secret key and it takes me to the "home" page. Im currently on a linux VM called Centos7.

**Comment by vadmeste** [comment]
> @vadmeste When i open the browser it opens to the login in, I enter the access key and secret key and it takes me to the "home" page. Im currently on a linux VM called Centos7.

Great, what about curl command ? you can run this one

`$ curl https://minio_address:9000/`

**Comment by mlinsky** [comment]
i get this, Do i just have my key/certs in the wrong place or am i not properly calling them?
```
curl https://www.minio_address:30000/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by vadmeste** [comment]
@mlinsky, okay.. That means public.crt is missing some intermediate certificates. You need to have a full chain in public.crt

**Comment by mlinsky** [comment]
@vadmeste So this is a server side not a client side issue?

**Comment by vadmeste** [comment]
> @vadmeste So this is a server side not a client side issue?

Yes. You need to properly generate public.crt which needs to contain all intermediate certificates. I can tell you how to do that if you tell me who is your SSL provider. Most likely we can find a documentation in their website about how to create a fullchain certificate.

**Comment by vadmeste** [comment]
Closing as this issue becomes idle. Feel free to reopen it @mlinsky when needed.
