### ISSUE TITLE
Integration with FineUploader

### ISSUE THREAD

**Issue by dels07** [minio/minio#5344]
Currently I'm having trouble with setting up FineUploader to work with Minio, since all the documentation available only applied to S3. Currently I use controller example from this repo:
https://github.com/FineUploader/php-laravel-s3-server

The error I'm receiving:
```
...
[Fine Uploader 5.15.5] Sending simple upload request for 0
[Fine Uploader 5.15.5] Submitting S3 signature request for 0
[Fine Uploader 5.15.5] Sending POST request for 0
s3/endpoint Failed to load resource: the server responded with a status of 419 (unknown status)
[Fine Uploader 5.15.5] POST request for 0 has failed - response code 419
[Fine Uploader 5.15.5] Response does not include the base64 encoded policy!
[Fine Uploader 5.15.5] Policy signing failed.  Response does not include the base64 encoded policy!
```

Likely trouble with policy signing as the code returning error on **line 73** on this file:
https://github.com/FineUploader/php-laravel-s3-server/blob/master/ExampleController.php

Can anyone give me an example of working Minio integration with FineUploader?

Thanks

**Comment by harshavardhana** [comment]
have you looked at https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-as-laravel-file-storage.md?

**Comment by dels07** [comment]
@harshavardhana
Yes, previously I use resumable.js and upload to application server first then to Minio using Storage::cloud()->put or Storage::disk('minio)->put, currently I try to upload file directly to Minio without having to store it in application server

**Comment by kannappanr** [comment]
@dels07 Were you able to reproduce the issue with AWS? Also, what are the changes you made to test the code in repo https://github.com/FineUploader/php-laravel-s3-server? If you can be as detailed as possible, it will be easier for me to reproduce the issue.

**Comment by kannappanr** [comment]
@dels07 Can you please respond to my questions?

**Comment by kannappanr** [comment]
Closing the issue as stale. Please feel free to re-open the issue, if you have more information.
