### ISSUE TITLE
Changed behaviour of 'minio update --quiet' breaks usage for monitoring solutions

### ISSUE THREAD

**Issue by hauke-altmann-as** [minio/minio#5347]
## Expected Behavior
Before PR https://github.com/minio/minio/pull/4961 we were able to check for minio updates with our monitoring calling 'minio update --quiet' and expecting exitcode '1' when a new version is available.

## Current Behavior
Now exitcode '0' is returned without the distinction if running the most recent version or an update is available.

## Possible Solution
Reimplementation of the old behaviour, introduction of an additional exitcode for 'update has been applied'.

## Steps to Reproduce (for bugs)
1. On the command line call 'minio update --quiet' with RELEASE.2017-12-28T01-21-00Z of minio installed. 
2. Call echo $?
3. Exit code wil be '0'

## Context
We are using a command line check with our monitoring to see, if a new version of minio is available. As we are testing software updates on staging environments before releasing it on our production systems and use automated deployment for our infrastructures, updating minio right away when calling 'minio update' is not an option for us.

## Your Environment
* Version used (`minio version`): RELEASE.2017-12-28T01-21-00Z

**Comment by harshavardhana** [comment]
> Before PR #4961 we were able to check for minio updates with our monitoring calling 'minio update --quiet' and expecting exitcode '1' when a new version is available.

About to send a fix for this issue., have a few questions. With the new changes `minio update` would update the binary in-place are you expecting this to happen when `--quiet` is specified? 

To disable this you need to set MINIO_UPDATE=off before running `minio` command.
