### ISSUE TITLE
Fix a faulty format.json recovery when .minio.sys is removed

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5348]
## Expected Behavior
When .minio.sys is removed, Minio regenerates format.json with a correct disk order.

## Current Behavior
When .minio.sys is removed, Minio regenerates format.json with a wrong disk order. Erasure won't be able to correctly construct data.

## Possible Solution
Do not know.

## Steps to Reproduce (for bugs)
I have a sample backend disks which reproduce the error but I am not sharing it because it has sensitive data. So, contact me.

## Context
Fixing bug.

## Your Environment
Recent Minio version

**Comment by vadmeste** [comment]
@nitisht I'll take this PR since I already started on it.

**Comment by harshavardhana** [comment]
This issue will be fixed as part of the format migration and change in PR #5160

**Comment by harshavardhana** [comment]
> This issue will be fixed as part of the format migration and change in PR #5160

@vadmeste can you spin this up and test? with PR #5160 and see if fixes the issue.

**Comment by vadmeste** [comment]
@harshavardhana, currently if I manually remove one .minio.sys in any disk, Minio won't run anymore and says the backend is corrupted.

**Comment by harshavardhana** [comment]
> @harshavardhana, currently if I manually remove one .minio.sys in any disk, Minio won't run anymore and says the backend is corrupted.

Are you talking about the PR #5160 ?

**Comment by vadmeste** [comment]
> Are you talking about the PR #5160 ?

yeah

**Comment by harshavardhana** [comment]
> yeah

yes that is expected we are not going to heal corrupted backends anymore.

**Comment by harshavardhana** [comment]
> yes that is expected we are not going to heal corrupted backends anymore.

Meaning corrupted `format.json`

**Comment by harshavardhana** [comment]
Going through this issue again, i see that we are not going to need to fix this. Closing this issue.
