### ISSUE TITLE
Refactor to remove NS locking from S3 layer

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5350]
Currently we have globalNSMutex.NewNSLock() usage in S3 layer, it should be moved to the object layer such that S3 layer is free of any NS locking.
 

```
krishna@escape:~/go/src/github.com/minio/minio/cmd$ grep globalNSMutex.NewNSLock object-handlers.go  bucket-handlers.go gateway-handlers.go 
object-handlers.go:	objectLock := globalNSMutex.NewNSLock(bucket, object)
object-handlers.go:	objectLock := globalNSMutex.NewNSLock(bucket, object)
object-handlers.go:	objectDWLock := globalNSMutex.NewNSLock(dstBucket, dstObject)
object-handlers.go:		objectSRLock := globalNSMutex.NewNSLock(srcBucket, srcObject)
object-handlers.go:	objectLock := globalNSMutex.NewNSLock(bucket, object)
object-handlers.go:	objectSRLock := globalNSMutex.NewNSLock(srcBucket, srcObject)
object-handlers.go:	destLock := globalNSMutex.NewNSLock(bucket, object)
bucket-handlers.go:			objectLock := globalNSMutex.NewNSLock(bucket, obj.ObjectName)
bucket-handlers.go:	bucketLock := globalNSMutex.NewNSLock(bucket, "")
bucket-handlers.go:	objectLock := globalNSMutex.NewNSLock(bucket, object)
bucket-handlers.go:	bucketLock := globalNSMutex.NewNSLock(bucket, "")
bucket-handlers.go:	bucketLock := globalNSMutex.NewNSLock(bucket, "")
gateway-handlers.go:	objectLock := globalNSMutex.NewNSLock(bucket, object)
gateway-handlers.go:	bucketLock := globalNSMutex.NewNSLock(bucket, "")
krishna@escape:~/go/src/github.com/minio/minio/cmd$ 

```

**Comment by harshavardhana** [comment]
Why did we decide this ?

**Comment by krishnasrinivas** [comment]
Poorna is using array of fsObjects for caching, and locking was conflicting with each other. It will also bring clarity, because currently we are holding locks on same namespace from two layers.

`globalNSMutex` can be `fsObjects.NSMutex`

**Comment by harshavardhana** [comment]
Why would it conflict ? There is an implementation problem I suspect in caching.  I am perfectly fine using it in   large bucket support.

**Comment by harshavardhana** [comment]
I think all you need is a list of locking primitives and the use a hashing function to pick the relevant one based on bucket/object name ..you don't need to move the code into fsObjects at all. 

Are we planning on dynamically expanding the caching to multiple disks as needed ?

**Comment by krishnasrinivas** [comment]
Sorry, my earlier statement was not correct. Cache's fsObjects was conflicting with backend fsObjects. i.e when cache was being used on top of fsObjects. Example scenario is when you want NVME cache for spinnging-disk in a simple FS setup.
