### ISSUE TITLE
minio browser file list icon ('xls' / 'xlsx') is not display

### ISSUE THREAD

**Issue by hikerlook** [minio/minio#5352]
If it is excel file, name column does not display the corresponding file icon, but other file types are displayed, such as word、ppt、pdf、png and so on. 
Is it a browser version of the problem? who knows,  thanks

## Your Environment
Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Chrome 60.0.3112.113

Firefox ESR 45.4.0

**Comment by nitisht** [comment]
@hikerlook PR https://github.com/minio/minio/pull/5361 was merged to fix this issue. Could you please try the latest master.

**Comment by hikerlook** [comment]
ok, thanks. I'll give it a try when I'm done
