### ISSUE TITLE
Standard healthcheck endpoint for Minio Server/Gateway

### ISSUE THREAD

**Issue by nitisht** [minio/minio#5357]
Ignoring template on purpose. 

Currently Minio [healthcheck](https://github.com/minio/minio/blob/master/dockerscripts/healthcheck.sh) script makes a curl request to browser endpoint to check for Minio service health. Due to several combinations of browser enabled/disabled and server/gateway setup, it is complex to handle various HTTP responses. 

Better approach is to create an unauthenticated endpoint that responds with status 200 if the server is healthy. This needs to be explored and implemented and Docker healthcheck script updated accordingly.

**Comment by seboudry** [comment]
Hi!
This feature will be good endpoint for k8s probes. Especially combined with GCE Ingress that only accept status 200 (so issue [3532](https://github.com/minio/minio/issues/3532) is not eligible) and without authentication.
Do you plan to make it as readiness or liveness probe (if distinction can be made) ?

**Comment by nitisht** [comment]
hey @Secathor yes, this will be an unauthorized endpoint and will return 200 for success case. There will be no distinction, it can serve as both readiness and liveness probe.

**Comment by Subito** [comment]
Will this output some information about the cluster-state in a distributed setup? I'm struggling to properly monitor if a cluster will be able to receive writes and deletes. Something like a smaller version of the `mc admin info` output maybe?

**Comment by nitisht** [comment]
@Subito sorry to have missed your comment earlier. 

> Will this output some information about the cluster-state in a distributed setup? I'm struggling to properly monitor if a cluster will be able to receive writes and deletes. Something like a smaller version of the mc admin info output maybe?

The idea for `healthcheck` is to add an endpoint that responds with relevant status. This is in accordance with expectations in Kubernetes / Swarm type environments. For something like what you're looking for, you can use the [madmin](https://github.com/minio/minio/tree/master/pkg/madmin) API.

**Comment by gstorme** [comment]
The endpoints (/minio/health/live & /minio/health/ready) from #5543 still return a 403 forbidden.  
Is it possible to let those return a 200 when the healthcheck is ok?

**Comment by nitisht** [comment]
@gstorme are you running Minio in a container? There was another issue fixed by https://github.com/minio/minio/pull/5647 , can you pls try the `edge` image?
