### ISSUE TITLE
[feature]: add HighwayHash256 support

### ISSUE THREAD

**Issue by aead** [minio/minio#5358]
This is a feature request for adding [HighwayHash256](https://github.com/minio/highwayhash) as bitrot protection / detection algorithm.
The authors have published the [final version](https://github.com/google/highwayhash#versioning-and-stability) of HighwayHash (64, 128, 256).

## Context
@fwessels has already [implemented](https://github.com/minio/highwayhash/commit/fd0b0262e003e6c7b39399f2e6e98f5a1df38d1f) the changes for the final HH versions.

## Your Environment
master

**Comment by fwessels** [comment]
Before we do this, we need to decide on the size of the key. I will follow up with more details.

**Comment by fwessels** [comment]
Based on the freeze of HighwayHash, I have completed the earlier work on comparing hashes (see https://github.com/fwessels/hashcompare), let's review and discuss.
