### ISSUE TITLE
Minio can be configured as https access way?

### ISSUE THREAD

**Issue by supermanlinux** [minio/minio#5360]
Minio can be configured as https access way? Thanks

**Comment by harshavardhana** [comment]
Have you looked at https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls ?

**Comment by supermanlinux** [comment]
@harshavardhana  Thanks,I'll see it right away.

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks,I'll see it right away.

Feel free to join https://slack.minio.io for further questions, going to close this issue now @ziqingshi
