### ISSUE TITLE
ERROR: SSL certificate verification failure: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by supermanlinux** [minio/minio#5362]
ERROR: SSL certificate verification failure: EOF occurred in violation of protocol (_ssl.c:590)
How to solve it?I hava no ideas.

## Expected Behavior
s3cmd mb s3://mybucket
Bucket 's3://mybucket/' created

## Current Behavior
s3cmd mb s3://mybucket
ERROR: SSL certificate verification failure: EOF occurred in violation of protocol (_ssl.c:590)

## Your Environment
ubuntu16.04
s3cmd version 1.6.1

.s3cfg configured:
# Setup endpoint
host_base = 172.xx.xx.xx:9000
host_bucket = 172.xx.xx.xx:9000
bucket_location = us-east-1
use_https = True

# Setup access keys
access_key =  VBKL3KYdfO1A818EU790
secret_key = JA0/It/MFKZReZ6OqdfnTLVQj5ghZ33+cRUDHF

# Enable S3 v4 signature APIs
signature_v2 = False

**Comment by harshavardhana** [comment]
Make sure you have, your minio server is not configured with TLS

```
use_https = False
```

**Comment by supermanlinux** [comment]
@harshavardhana Thank you very much,than I don't configured with TLS, use_https = False,I can use s3cmd mb s3://mybucket and so on.But today I configured with TLS,using self-signed,than I use s3cmd mb s3://xxx, ERROR: SSL certificate verification failure: EOF occurred in violation of protocol (_ssl.c:590),what happened, why?I think it does not matter with self-signatures.

**Comment by harshavardhana** [comment]
This issue has moved here now https://github.com/minio/minio/issues/5369 closing this as addressed.
