### ISSUE TITLE
ERRO[0007] Initializing object layer failed

### ISSUE THREAD

**Issue by hikerlook** [minio/minio#5363]
It is normal to start the minio service on a single node. Multi-node failure

Is my configuration is wrong? environment or command. who knowns, please tell me.

Thanks.

## single node
`minio server /home/minio/data`

show :

```
Drive Capacity: 12 GiB Free, 17 GiB Total

Endpoint:  http://192.168.111.138:9000  http://192.168.122.1:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: miniostorage 

Browser Access:
   http://192.168.111.138:9000  http://192.168.122.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.111.138:9000 minio miniostorage

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

## multi-node
`minio server http://192.168.111.138/home/minio/data http://192.168.111.140/home/minio/data http://192.168.111.141/home/minio/data http://192.168.111.142/home/minio/data`

show :
```
ERRO[0007] Initializing object layer failed              cause=Unsupported backend format [fs] found source=[server-main.go:214:serverMain()]
```

## Your Environment

* Version used (`minio version`):
https://dl.minio.io/server/minio/release/linux-amd64/minio

* Operating System and version (`uname -a`):
four nodes have the same environment
```
uname -a
Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nitisht** [comment]
@hikerlook yes, this is an expected error. You'll need to delete the `.minio.sys` directory inside `/home/minio/data` and try again with multi-node setup

**Comment by hikerlook** [comment]
Yes, after the deletion can be started normally.
Thanks @nitisht

**Comment by nitisht** [comment]
Thanks, closing this issue as answered. Feel free to join us on [slack](https://minio.slack.com) for further questions
