### ISSUE TITLE
[TLS]use:s3cmd ls s3://  error:ERROR: SSL certificate verification failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:59

### ISSUE THREAD

**Issue by supermanlinux** [minio/minio#5369]
I used self-signatures.
a. openssl ecparam -genkey -name prime256v1 -out private.key
b. openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=domain"
...
![image](https://user-images.githubusercontent.com/34739130/34661542-62a51340-f485-11e7-9d3f-5e6b590df2f3.png)
![image](https://user-images.githubusercontent.com/34739130/34661546-69cc5bc4-f485-11e7-9671-ed0d4c85c818.png)
![image](https://user-images.githubusercontent.com/34739130/34661588-9f24f510-f485-11e7-80c3-73d0bd0b1ecf.png)
thanks.
## Expected Behavior
s3cmd mb s3://mybucket
Bucket 's3://mybucket/' created

## Current Behavior
s3cmd mb s3://mybucket
ERROR: SSL certificate verification failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

## Possible Solution
I think it does not matter with self-signatures.

## Your Environment
Ubuntu 16.04.2 LTS
s3cmd version 2.0.1+
OpenSSL 1.0.2g  1 Mar 2016

**Comment by supermanlinux** [comment]
The second picture is openssl.conf,the third picture is .s3cfg.

**Comment by harshavardhana** [comment]
Use `--no-check-certificate`  like `s3cmd mb --no-check-certificate ` - if you wish the certs to be checked which is the default behavior then you need to additionally trust your self signed signatures to system trust directory - follow [this](https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line)

**Comment by supermanlinux** [comment]
@harshavardhana Thank you very much,I try it right now.

**Comment by supermanlinux** [comment]
@harshavardhana I try this,but not success.The same error occured.
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
I added the certificates,but the same error occured.Why?

**Comment by harshavardhana** [comment]
You can provide location to the certs file

```
  --ca-certs=CA_CERTS_FILE
                        Path to SSL CA certificate FILE (instead of system
                        default)
```

```
s3cmd --ca-certs /etc/ssl/certs/ca-certificates.crt mb s3://mybucket
```

**Comment by vadmeste** [comment]
@ziqingshi I tested a self signed certificate generated by your openssl certificates, it just works.

```
11:19 $ s3cmd mb s3://mybucket/
ERROR: SSL certificate verification failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
11:21 $ s3cmd mb --no-check-certificate s3://mybucket/
Bucket 's3://mybucket/' created
11:21 $ s3cmd mb --ca-certs ~/.minio/certs/public.crt s3://anotherbucket/
Bucket 's3://anotherbucket/' created
```

**Comment by vadmeste** [comment]
@ziqingshi can you say why --no-check-certificate didn't work for you? do you see any error ?

**Comment by supermanlinux** [comment]
@vadmeste @harshavardhana  Thank you very much,I have just solved my problem.I based on the server's error, solved problems;I change two locations all in .s3cfg.When the error is certificateError: hostname 'xxx.16.x.15:443' doesn't match u'xxx.16.x.15',I remove the :443 in the .s3cfg,when the error is the request signature we calculated does not match the signature you provided. Check your key and signing method,I changed signature_v2 = True,previoud is False.I like studying,I should try my best to learn from you.

**Comment by phdeniel** [comment]
Hi, I meet the same error on Fedora 28. 
I am using s3cmd in front of a minio S3 Server (running on localhost). I did my best to disable SSL checking, but it fails anyway:

# s3cmd mb --no-check-certificate -d  s3://bucky
(... many debug message as .s3cfg is parsed ...)
DEBUG: Command: mb
DEBUG: bucket_location: <CreateBucketConfiguration><LocationConstraint>fr</LocationConstraint></CreateBucketConfiguration>
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'PUT\n\n\n\nx-amz-date:Fri, 01 Mar 2019 09:56:53 +0000\n/bucky/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(bucky): 127.0.0.1:9000
DEBUG: ConnMan.get(): creating new connection: https://127.0.0.1:9000
DEBUG: Using ca_certs_file None
**DEBUG: Disabling SSL certificate checking**
DEBUG: httplib.HTTPSConnection() has both context and check_hostname
DEBUG: non-proxied HTTPSConnection(127.0.0.1, 9000)
**ERROR: SSL certificate verification failure: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:858)**

That sounds quite illogic : why do I get a SSL certificate error as I explicitely said this should be turned off (and apparently s3cmd knows it should turn this off). Any idea ?

**Comment by harshavardhana** [comment]
Perhaps your s3cmd version is old or config is incorrect.
