### ISSUE TITLE
BUG: HEAD request on root returns 405 should be 200

### ISSUE THREAD

**Issue by zhnu** [minio/minio#5372]
## Expected Behavior
Hi, when I try to do an HEAD on minio on the root object I get an status code 405 while the expected is  an 200 (atleast on s3).

When I try to HEAD another location on minio I get a status code 400, it should respond with the status of the file (200, 404, etc).

## Steps to Reproduce (for bugs)
`curl -X HEAD \
  http://localhost:9000 \
  -H 'authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN12341234/20180108/us-west-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=SOMETHING' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'x-amz-content-sha256: SOMETHING' \
  -H 'x-amz-date: 20180108T144726Z'`

## Your Environment
* Minio running on docker (RELEASE.2018-01-02T23-07-00Z).
* Ubuntu 16.04.3 LTS running 4.4.0-97-generic
* Docker version 17.09.0-ce, build afdb6d4

**Comment by krishnasrinivas** [comment]
Head on `/` is an unusual request with out purpose @zhnu 
does any of your application break because of this?
Can you paste code on how you tried to do HEAD on S3's `/`?

**Comment by harshavardhana** [comment]
I see that AWS S3 returns 405 as well 

```
curl --head https://s3.amazonaws.com/
HTTP/1.1 405 Method Not Allowed
x-amz-request-id: 7D98BF1103B40FEC
x-amz-id-2: jVLJ2XhEhqskMBB8obxdeT0FRg6e1y0MbXodnohHehzMXRn8RkLDrr1KW7Iw66MdQS1gdtJxh5Q=
Allow: GET
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Wed, 17 Jan 2018 02:23:44 GMT
Server: AmazonS3
```

**Comment by zhnu** [comment]
Hi, sorry for the late response:
On aws:
 `curl -X HEAD \
  http://bucketname.s3-region.amazonaws.com \
  -H 'authorization: AWS4-HMAC-SHA256 Credential=AKIAblablabla/20180117/region/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=something' \
  -H 'cache-control: no-cache' \
  -H 'x-amz-content-sha256: something' \
  -H 'x-amz-date: 20180117T184930Z'`
you get an 200 response from the root of the bucket.
On minio when I try to curl the root of the bucket I get a 405. I have minio running behind a reverse-proxy (traefik) with rules to replicate the s3 domains. The library that gets broken by this is the s3 datastore for Apache Jackrabbit.
If necessary I can post the rules I'm using for the reverse proxy.

**Comment by harshavardhana** [comment]
> Hi, sorry for the late response:
> On aws:
> curl -X HEAD \ http://bucketname.s3-region.amazonaws.com \ -H 'authorization: AWS4-HMAC-SHA256 Credential=AKIAblablabla/20180117/region/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=something' \ -H 'cache-control: no-cache' \ -H 'x-amz-content-sha256: something' \ -H 'x-amz-date: 20180117T184930Z'
> you get an 200 response from the root of the bucket.
> On minio when I try to curl the root of the bucket I get a 405. I have minio running behind a reverse-proxy (traefik) with rules to replicate the s3 domains. The library that gets broken by this is the s3 datastore for Apache Jackrabbit.
> If necessary I can post the rules I'm using for the reverse proxy.

You would get the same if you configure minio with `--domain` to get the resolver to work. Without providing the bucketname either path or virtual style wouldn't work with Minio. Since you don't have `--domain` set you should simply do `http://ip:port/bucketname`  @zhnu

**Comment by zhnu** [comment]
Will try asap, I need to modify my ansiable templates thank you very much.

**Comment by harshavardhana** [comment]
Correction you need to set MINIO_DOMAIN not `--domain`

**Comment by zhnu** [comment]
Hi, I can confirm that it works as expected with the domain defined. Thank you for your help
