### ISSUE TITLE
java-client:minio-3.0.7 support remove objects but it does not work in my code

### ISSUE THREAD

**Issue by belugaliu** [minio/minio#5377]
## Expected Behavior
my scenes is that want to remove batch objects only in one http's request.not for-loop remove one by one.
## Current Behavior
i found in java-client(minio-3.0.7.jar) support remove batch objects.
```java
//MinioClient
 public Iterable<Result<DeleteError>> removeObject(final String bucketName, final Iterable<String> objectNames) {
//....
}
```
but it does not work.<br>
so i want confirm is it a bug?

## Steps to Reproduce (for bugs)
1.my code like this:
```java
 Iterable<Result<DeleteError>> deleteResultes = client.removeObject(bucketName, objectNames);
   Iterator<Result<DeleteError>> deleteResultIter = deleteResultes.iterator();
   List<String> errorMsgs =  new ArrayList<String>();
    while(deleteResultIter.hasNext()){
        Result<DeleteError> deleteResult = deleteResultIter.next();
        DeleteError deleteError;
        try {
            deleteError = deleteResult.get();
            if(deleteError != null) {
                errorMsgs.add(String.format("%s---%s", deleteError.getString(), deleteError.toString()));
            }
        }   catch (ErrorResponseException e) {
            errorMsgs.add(String.format("%s---%s", e.errorResponse().getString(), e.toString()));
        }  catch (Exception e) {
            errorMsgs.add(buildRmBatchExpMsg(e));
        }
        if(CollectionUtils.isNotEmpty(errorMsgs)){
            throw new  StorageException(StringUtils.join(errorMsgs, "\n"));
        }
    }
```
2. then no exception throw and no work in minio-server

## Your Environment
* Version used (`minio version`):minio-3.0.7.jar
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: 
VERSION
2017-10-27T18:59:02Z
MEMORY
Used: 50 MB | Allocated: 27 GB | Used-Heap: 50 MB | Allocated-Heap: 114 MB
PLATFORM
Host: localhost | OS: linux | Arch: amd64
RUNTIME
Version: go1.9.2 | CPUs: 4

* Operating System and version (`uname -a`):
* Link to your project:

**Comment by balamurugana** [comment]
@liuliliGithub Could you share what error/stacktrace you get in minio-java and minio server?

**Comment by nitisht** [comment]
closing due to no response @liuliliGithub . Please reopen if required.
