### ISSUE TITLE
Incorrect information from madmin client

### ISSUE THREAD

**Issue by nitisht** [minio/minio#5378]
## Expected Behavior
`mdmClnt.ServerInfo()` gives correct information about read and write quorum.

## Current Behavior
`mdmClnt.ServerInfo()` gives incorrect information about read and write quorum.

## Steps to Reproduce (for bugs)
As reported by user stefanbo on Slack channel . Deploy latest Minio server and use the below snippet

```go
package main

import (
	"fmt"

	"github.com/minio/minio/pkg/madmin"
)

func main() {
	// Use a secure connection.
	ssl := false

	// Initialize minio client object.
	mdmClnt, err := madmin.New("10.1.61.168:9000", "aaaaa", "bbbbbbbbb", ssl)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Fetch service status.
	st, err := mdmClnt.ServiceStatus()
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("%#v\n", st)

	serversInfo, err := mdmClnt.ServerInfo()
	if err != nil {
		fmt.Println(err)
	}

	for _, peerInfo := range serversInfo {
		fmt.Printf("Node: %s, ReadQuorum: %v, WriteQuorum: %v\n", peerInfo.Addr, peerInfo.Data.StorageInfo.Backend.ReadQuorum, peerInfo.Data.StorageInfo.Backend.WriteQuorum)
	}
}
```

## Context
StorageClass implementation

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@nitisht Till release minio.RELEASE.2017-11-22T19-55-46Z , the results are fine. I see that this is broken from release minio.RELEASE.2017-12-28T01-21-00Z onwards
