### ISSUE TITLE
Offline node make cluster ListObjects inconsistent when it's back online

### ISSUE THREAD

**Issue by Vesnica** [minio/minio#5380]
## Steps to Reproduce (for bugs)
1. Create 4 node cluster, 1 disk per node, wait for it all ready
2. mc cp 10000 small(10M) files to the cluster
3. On all 4 nodes, use mc ls local | wc -l to check files count, all return 10000 consistently
4. Bring down 1 node, then cp another 5000 files to the cluster
5. On the running 3 nodes, use mc ls local | wc -l to check files count, all return 15000 consistently
6. Bring the offline node back online, and execute mc admin heal on it (with and without --recursive)
7. On all 4 nodes, use mc ls local | wc -l to check files count

## Expected Behavior

All nodes should report 15000 consistently

## Current Behavior

All nodes report 10000 ~ 15000 randomly

## Possible Solution

None

## Context

This inconsistent behaviour is unaccpetable for production uses, especially for docker registry garbage collect procedure which will fail when any file is inaccessible, the inconsistent file list makes gc impossible to finish successfully.

## Your Environment

* Version used (`minio version`): RELEASE.2018-01-02T23-07-00Z
* Server type and version: Linux
* Operating System and version (`uname -a`): Linux controller 3.10.0-514.26.2.el7.x86_64 #1 SMP Mon Dec 4 15:49:59 CST 2017 x86_64 x86_64 GNU/Linux

**Comment by Vesnica** [comment]
After some extended tests, I found that cluster can reach final consistent if you perform the complete recursive heal on the specified bucket. But I still think there is something wrong with it:

1. Why a single re-joined node can makes the entire cluster inconsistent？I think other 3 nodes should have enough quorum information
2. Why user must perform heal manually to sync the re-joined node with others? This should be an automated process, for a HA system

**Comment by harshavardhana** [comment]
This is an expected behavior we do not hold quorum on Listing instead quorum is held on GetObject().   Listing always happens randomly from one of the disks that is available. So if you have disks going up and down in this fashion you are correct you need to heal to make the Listing consistent. 

And yes healing is manual since you are more aware of when you need to heal the cluster `mc admin heal`, providing more visibility and control.

**Comment by Vesnica** [comment]
The inconsistent listing will make many user scenarios to fail(registry gc, for example), and it's not feasible to ensure all disks or nodes never fail in practice(or forbid user traffic during the failing or healing).

Currently I have to abandon the minio's native distributed setup, and switch to a customized one(some standalone minio nodes + mc mirror), to make my system can continue to run in the actual environment.

**Comment by harshavardhana** [comment]
> The inconsistent listing will make many user scenarios to fail(registry gc, for example), and it's not feasible to ensure all disks or nodes never fail in practice(or forbid user traffic during the failing or healing).
> 
> Currently I have to abandon the minio's native distributed setup, and switch to a customized one(some standalone minio nodes + mc mirror), to make my system can continue to run in the actual environment.

We will have to discuss this, in the past we have decided because GetObject() is the ideal operation to check for consistency. There can be an added drawback here that Listing would become slower due to Stat() operations that need to be performed to know the quorum.

**Comment by Vesnica** [comment]
Thank you for willingness to reconsider current design!

Actually, I had considered several options before, one of them is:
1. Get the complete object list when booting(or restarting), and store it in memory
2. Use the notification or event mechanism to update the object changes to memory list
3. All nodes's memory list should reach identical eventually if any abnormal happened (use Raft?)

This design will prolong the system startup(or restart) time, but listing performance should not be a concern anymore.

I'm not an expert, of course. just think there must be a way to improve the current situation。

**Comment by miketonks** [comment]
We are also using minio in distributed mode with a similar setup, and having same issues.

The lack of automated healing is a big problem for using minio in production.  Without this minio is not really a reliable system.

A node can go offline for any reason, either planned maintenance or network outage.  We may not know the node was offline as it does not report this, so we have no way to know if the node requires healing unless we monitor constantly.

As list reading is unreliable, all backups are also unreliable.  So we cannot safely back up our data

We have had to implement our own monitoring and automated healing system on top of minio, but this is hacky and not ideal.  When a node is detected as offline we must mark it bad and not read from it again until it comes back online and is fully healed. 

We hope minio will improve this feature soon.

**Comment by Vesnica** [comment]
mc admin heal is very slow, it's not practical to use in production environment.

I wrote a script to manually sync the missing files between nodes(3 nodes setup). very hacky, but it works well:
```
#!/bin/bash

A_IP=$1
B_IP=$2
C_IP=$3

A_NAME=a_host
B_NAME=b_host
C_NAME=c_host

: ${ACCESS_KEY:=ACCESS_KEY}
: ${SECRET_KEY:=SECRET_KEY}

if [[ -z $A_IP ]] || [[ -z $B_IP ]] || [[ -z $C_IP ]]; then
    echo "A_IP B_IP C_IP must exist, exit"
    exit 255
fi

mc config host add $A_NAME http://$A_IP:9000 $ACCESS_KEY $SECRET_KEY
if [ ! $? -eq 0 ]; then
    echo "mc config host add $A_IP failed"
    exit 255
fi
mc config host add $B_NAME http://$B_IP:9000 $ACCESS_KEY $SECRET_KEY
if [ ! $? -eq 0 ]; then
    echo "mc config host add $B_IP failed"
    exit 255
fi
mc config host add $C_NAME http://$C_IP:9000 $ACCESS_KEY $SECRET_KEY
if [ ! $? -eq 0 ]; then
    echo "mc config host add $C_IP failed"
    exit 255
fi

REPO="/export/"

echo "Get $A_IP file list"
sshpass -p cloud ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$A_IP REPO=$REPO sudo -E find $REPO -type d | sort > a.log
if [ ! $? -eq 0 ]; then
    echo "ssh $A_IP failed"
    exit 255
fi
echo "Get $B_IP file list"
sshpass -p cloud ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$B_IP REPO=$REPO sudo -E find $REPO -type d | sort > b.log
if [ ! $? -eq 0 ]; then
    echo "ssh $B_IP failed"
    exit 255
fi
echo "Get $C_IP file list"
sshpass -p cloud ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$C_IP REPO=$REPO sudo -E find $REPO -type d | sort > c.log
if [ ! $? -eq 0 ]; then
    echo "ssh $C_IP failed"
    exit 255
fi

echo "Generate all.log"
sort -u a.log b.log c.log > all.log

echo "Generate missing logs"
comm -23 all.log a.log | sort > a_missing.log
comm -23 all.log b.log | sort > b_missing.log
comm -23 all.log c.log | sort > c_missing.log

echo "Process a_missing files"
while read f; do
    if (( $(grep $f a_missing.log -c) > 1 )); then
        continue
    fi
    if echo $f | grep -q ".minio.sys"; then
        continue
    fi
    SRC=""
    if grep -Fxq "$f" b.log; then
        SRC=$B_NAME
    fi
    if grep -Fxq "$f" c.log; then
        SRC=$C_NAME
    fi
    if [[ -z $SRC ]]; then
        echo "couldn't find $f in b.log and c.log, skipping"
        continue
    fi
    OBJ_NAME=${f##*/}
    OBJ_PATH=${f#$REPO}
    echo "get $OBJ_PATH from $SRC and put to $A_NAME";
    mc cp $SRC/$OBJ_PATH .
    mc cp $OBJ_NAME $A_NAME/$OBJ_PATH
    rm $OBJ_NAME
done <a_missing.log

echo "Process b_missing files"
while read f; do
    if (( $(grep $f b_missing.log -c) > 1 )); then
        continue
    fi
    if echo $f | grep -q ".minio.sys"; then
        continue
    fi
    SRC=""
    if grep -Fxq "$f" a.log; then
        SRC=$A_NAME
    fi
    if grep -Fxq "$f" c.log; then
        SRC=$C_NAME
    fi
    if [[ -z $SRC ]]; then
        echo "couldn't find $f in a.log and c.log, skipping"
        continue
    fi
    OBJ_NAME=${f##*/}
    OBJ_PATH=${f#$REPO}
    echo "get $OBJ_PATH from $SRC and put to $B_NAME";
    mc cp $SRC/$OBJ_PATH .
    mc cp $OBJ_NAME $B_NAME/$OBJ_PATH
    rm $OBJ_NAME
done <b_missing.log

echo "Process c_missing files"
while read f; do
    if (( $(grep $f c_missing.log -c) > 1 )); then
        continue
    fi
    if echo $f | grep -q ".minio.sys"; then
        continue
    fi
    SRC=""
    if grep -Fxq "$f" a.log; then
        SRC=$A_NAME
    fi
    if grep -Fxq "$f" b.log; then
        SRC=$B_NAME
    fi
    if [[ -z $SRC ]]; then
        echo "couldn't find $f in a.log and b.log, skipping"
        continue
    fi
    OBJ_NAME=${f##*/}
    OBJ_PATH=${f#$REPO}
    echo "get $OBJ_PATH from $SRC and put to $C_NAME";
    mc cp $SRC/$OBJ_PATH .
    mc cp $OBJ_NAME $C_NAME/$OBJ_PATH
    rm $OBJ_NAME
done <c_missing.log

echo "All Done"
```
Still, I hope minio can fix this issue eventually so we don't need these black sorceries.

**Comment by krishnasrinivas** [comment]
@Vesnica @miketonks we are going to implement quorum listing, which will make listing consistent and correct but it will be slower. Need to see how slow it will be.
