### ISSUE TITLE
Distributed minio fail to start after upgrade using ansible

### ISSUE THREAD

**Issue by curantes** [minio/minio#5402]
I had some issues with an distributed minio upgrade using provided minio ansible playbook and roles. Thanks for the assistance from @harshavardhana. This issue is created as a referens how minio could be upgrade with the help with ansible.

This have have worked flawlessly on all our environments except one.

ansible files attached as referens.

[ansible-minio.tar.gz](https://github.com/minio/minio/files/1632041/ansible-minio.tar.gz)

## Expected Behavior

When upgrading minio cluster there should not be any issues

## Current Behavior

With the environment we had problem with we had some old bucket_listeners with old version which missmatched the new upgraded version and causing our erros. Also I think ansible did not forcefully kill minio so some nodes never got restart on new version 

## Steps to Reproduce (for bugs)

1. install ansible
2. run the ansible playbook to upgrade
3. make sure that there are old bucket listerens file located in each buckets
4.

## Your Environment

* Version used (minio version): prior upgrade: 2017-09-29T19:16:56Z after upgrade: RELEASE.2018-01-02T23-07-00Z
* Environment name and version (e.g. nginx 1.9.1): CentOS 7
* Server type and version: VMware VSphere 6.5 VM, 1 Core, 4 GB of memory
* Operating System and version (uname -a): Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Nodes count: 16
* Storage size in minio: 10 TB
* Number of buckets: 1000

**Comment by harshavardhana** [comment]
We support rolling upgrades since last couple of releases so this issue would be fixed @curantes . Should we close this issue ?

**Comment by curantes** [comment]
@harshavardhana yes I can close. Thanks
