### ISSUE TITLE
Issue starting minio server on MacOS (not using docker or home-brew)

### ISSUE THREAD

**Issue by jsrockets** [minio/minio#5403]
When you try to launch minio via launchd (launchctl) on boot it does not work because it cannot find a home directory. A home directory seems to be a requirement even if --config-dir is used on the command line.

## Expected Behavior
Home directory should not be required if --config-dir is passed.

## Current Behavior
Code exits with an error.

## Possible Solution
I believe the problem is in this code from config-dir.go   : 
func mustGetDefaultConfigDir() string {
	homeDir, err := homedir.Dir()
	fatalIf(err, "Unable to get home directory.")

	return filepath.Join(homeDir, defaultMinioConfigDir)
}

Either this function should not be called if the config-dir is passed in, or this function should be modified to return the value from config-dir instead of failing.

## Steps to Reproduce (for bugs)
Try to start on macOS at root without homer

## Your Environment
I was able to work around this by adding the following to my plist file :
   <key>EnvironmentVariables</key>
   <dict>
     <key>HOME</key>
     <string> ---insert valid home dir here--- </string>
   </dict>

**Comment by harshavardhana** [comment]
Thanks @jsrockets we will take a look.

**Comment by harshavardhana** [comment]
> func mustGetDefaultConfigDir() string {
> homeDir, err := homedir.Dir()
> fatalIf(err, "Unable to get home directory.")

Do you have the error message from this output? @jsrockets

**Comment by jsrockets** [comment]
Error messages match the code exactly : 
Unable to get home directory.

I don't remember if there were any additional messages.

**Comment by harshavardhana** [comment]
> Error messages match the code exactly :
> Unable to get home directory.
> 
> I don't remember if there were any additional messages.
> 
>  
There should be "err" component associated with the "message" that is being printed. Do you not see that?

**Comment by jsrockets** [comment]
Yes there was more there but I don't have the exact error saved.
Give me a few minutes and I'll try to recreate.

**Comment by jsrockets** [comment]
Exact error : 

time="2018-01-15T13:50:40-06:00" level=fatal msg="Unable to get home directory." cause="exit status 1" source="[config-dir.go:100:mustGetDefaultConfigDir()]"

**Comment by jsrockets** [comment]
> time="2018-01-15T13:50:40-06:00" level=fatal msg="Unable to get home directory." cause="exit status 1" source="[config-dir.go:100:mustGetDefaultConfigDir()]"

**Comment by jsrockets** [comment]
`time="2018-01-15T13:50:40-06:00" level=fatal msg="Unable to get home directory." cause="exit status 1" source="[config-dir.go:100:mustGetDefaultConfigDir()]" 
`

**Comment by jsrockets** [comment]
Don't know where that weird red 100 thing is from. Last one is the exact line.

**Comment by harshavardhana** [comment]
> Don't know where that weird red 100 thing is from. Last one is the exact line.

Well that must be because of `:100:` is a emoji on github :100:

**Comment by harshavardhana** [comment]
> cause="exit status 1"

This message is weird let me take a look at the code.

**Comment by jsrockets** [comment]
Code that works:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>KeepAlive</key>
   <true/>
   <key>Label</key>
   <string>com.minio.engine</string>
   <key>ProgramArguments</key>
   <array>
     <string>/Users/Jeff/Minio/bin/minio</string>
     <string>server</string>
     <string>--config-dir=/Users/Jeff/Minio/etc</string>
     <string>--address=:9000</string>
     <string>/NAS/Backups/Minio_data</string>
   </array>
   <key>RunAtLoad</key>
   <true/>
   <key>KeepAlive</key>
   <true/>
   <key>WorkingDirectory</key>
   <string>/Users/Jeff/Minio</string>
   <key>UserName</key>
   <string>root</string>
   <key>StandardErrorPath</key>
   <string>/Users/Jeff/Minio/Logs/engine_error.log</string>
   <key>StandardOutPath</key>
   <string>/Users/Jeff/Minio/Logs/engine_output.log</string>
   <key>EnvironmentVariables</key>
   <dict>
     <key>HOME</key>
     <string>/Users/Jeff</string>
   </dict>
   <key>RunAtLoad</key>
   <true/>
</dict>
</plist>
`

To get the fail you just need to remove the whole EnvironentVariables section.

**Comment by jsrockets** [comment]
Lets try it a different way.


[com.minio.engine.plist.txt](https://github.com/minio/minio/files/1632868/com.minio.engine.plist.txt)

**Comment by jsrockets** [comment]
That worked. Just remove the .txt obviously.
Jeff
