### ISSUE TITLE
kubernetes service broker for minio

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5406]
Similar to how Minio has service broker for CF, Minio needs a service broker for k8s too.

https://kubernetes.io/docs/concepts/service-catalog/

**Comment by solsson** [comment]
@krishnasrinivas Can you elaborate a bit on the scope of this? Have you found any example of a blob store service broker?

**Comment by nitisht** [comment]
we decided to implement minio-operator for Kubernetes (ref: https://github.com/minio/minio-operator) so closing this for now. We can revisit later if there is a pressing need

**Comment by abessifi** [comment]
From a developer/user perspective, how to request for a S3 bucket using the `minio-operator` as a replacement of the Service Broker. I know that this feature is not yet implemented but just wondering about what the `minio-operator` will be used for apart of the idea to make easy the installation, management and upgrade of a Minio Cluster.
On the other hand, in the long term, do the [rook-minio](https://rook.io/docs/rook/v1.0/minio-object-store.html) project be the official operator for Minio ?
