### ISSUE TITLE
Upgrade of distributed minio failed due old version listener.json files blocked the start

### ISSUE THREAD

**Issue by curantes** [minio/minio#5408]
I did a upgrade of the distributed minio using ansible according to #5402 this failed. I got assistance from @harshavardhana who assisted to get the cluster up and running. Looks like there were old listener.json for each bucket since an old `mc mirror -w` that still had the old version which caused the new version of cluster to fail to start.

Attachment of the listener.json files for all buckets in cluster:
[listener.json.old-files.tar.gz](https://github.com/minio/minio/files/1634277/listener.json.old-files.tar.gz)

journal log for one of the minio instances:
```
jan 13 07:58:30 minio[11409]: [4B blob data]
jan 13 07:58:36 minio[11409]: [410B blob data]
jan 13 07:58:40 minio[11409]: time="2018-01-13T07:58:40+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d508), maxRetry
jan 13 07:58:40 minio[11409]: time="2018-01-13T07:58:40+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d510), maxRetry
jan 13 07:58:41 minio[11409]: time="2018-01-13T07:58:41+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d518), maxRetry
jan 13 07:58:44 minio[11409]: time="2018-01-13T07:58:44+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d520), maxRetry
jan 13 07:58:46 minio[11409]: time="2018-01-13T07:58:46+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d528), maxRetry
jan 13 07:58:51 minio[11409]: time="2018-01-13T07:58:51+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d548), maxRetry
jan 13 07:58:54 minio[11409]: time="2018-01-13T07:58:54+01:00" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc42000d550), maxRetry
jan 13 07:58:54 minio[11409]: Initializing data volume.
jan 13 07:58:54 minio[11409]: [01/16] http://10.98.92.114:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [02/16] http://10.98.92.115:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [03/16] http://10.98.92.116:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [04/16] http://10.98.92.117:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [05/16] http://10.98.92.118:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [06/16] http://10.98.92.119:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [07/16] http://10.98.92.120:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [08/16] http://10.98.92.121:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [09/16] http://10.98.92.122:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [10/16] http://10.98.92.123:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [11/16] http://10.98.92.124:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [12/16] http://10.98.92.125:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [13/16] http://10.98.92.126:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [14/16] http://10.98.92.127:9091/minio/data - 1.7 TiB online
jan 13 07:58:54 minio[11409]: [15/16] http://10.98.92.128:9091/minio/data - 0 B offline
jan 13 07:58:54 minio[11409]: [16/16] http://10.98.92.129:9091/minio/data - 0 B offline
jan 13 07:59:11 minio[11409]: time="2018-01-13T07:59:11+01:00" level=error msg="Unable to load bucket-listeners for bucket 168" cause="Storage resources are insufficient for the read oper
```

## Expected Behavior

Should be able to do an upgrade without issues to start the clsuter aftwards.

## Current Behavior

In this case the cluster did not come up until @harshavardhana helped me to move the old/faulty listener.json files

## Possible Solution

An ideá would be that the old listener.json files get clearer during upgrade or is part of the version migration to these files can be used with new version.

## Steps to Reproduce (for bugs)

1. Upgrade cluster with old listener.json files in /minio/data/.minio.sys/buckets/*/
2. Try to launch cluster on new version
3.
4.

## Context

This issue caused longer downtime for the minio cluster than we planned for in our production. I did this upgrade without issues on our other environments without any issues. And again many thanks for the quick assistance from @harshavardhana that helped in shortening this downtime.

## Your Environment

* Version used (minio version): prior upgrade: 2017-09-29T19:16:56Z after upgrade: RELEASE.2018-01-02T23-07-00Z
* Environment name and version (e.g. nginx 1.9.1): CentOS 7
* Server type and version: VMware VSphere 6.5 VM, 1 Core, 4 GB of memory
* Operating System and version (uname -a): Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Nodes count: 16
* Storage size in minio: 10 TB
* Number of buckets: 1000

**Comment by harshavardhana** [comment]
This should be fixed already in the latest release already. Since the startup sequences have changed . Is it okay to close this issue @curantes ?

**Comment by curantes** [comment]
@harshavardhana yes I will close this.
