### ISSUE TITLE
ListObjects with prefix and non existing marker causes an NotImplemented error

### ISSUE THREAD

**Issue by auvn** [minio/minio#5421]
I am trying to list objects using *github.com/aws/aws-sdk-go/service/s3* package

Pseudo code example:
```
        s3session, err := session.NewSession(&aws.Config{
		Endpoint:         aws.String("http://localhost:9000"),
		Credentials:      credentials.NewStaticCredentials("...", "...", ""),
		Region:           aws.String("us-east-1"),
		DisableSSL:       aws.Bool(true),
		S3ForcePathStyle: aws.Bool(true),
	})
	if err != nil {
		panic(err)
	}

	s3Api := s3.New(s3session)
	resp, err := s3Api.ListObjects(&s3.ListObjectsInput{
		Bucket: aws.String("bucket"),
		Prefix: aws.String("some_prefix"),
		Marker: aws.String("some_marker"),
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(resp)
```

## Expected Behavior
Response is:
```
{
  IsTruncated: false,
  Marker: "some_marker",
  MaxKeys: 1000,
  Name: "bucket",
  Prefix: "some_prefix"
}
```

## Current Behavior
```
panic: NotImplemented: A header you provided implies functionality that is not implemented
	status code: 501, request id: 150A9DB07BBBEB40, host id: 
```

## Steps to Reproduce (for bugs)

1. Run the docker image *docker minio container: docker run --name=s3_server -p 9000:9000 -d minio/minio server /expor*;
2. Create a new bucket via minio web page. Bucket name is "bucket";
3. Execute the code above.

## Context
We use minio for testing, to avoid using real aws s3 service. We are building something like s3 discovery logic, due to the issue our QA were unable to write test cases for a similar situation as I provided above. Using real aws s3 service I was able to perform this request and didn't get any errors.

## Your Environment
* Version used (`minio version`):

```
/ # minio version
Version: 2018-01-02T23:07:00Z
Release-Tag: RELEASE.2018-01-02T23-07-00Z
Commit-ID: a6318dbdaf0a33d80e52bb762e153e4d7ca396f7
```

* Environment name and version (e.g. nginx 1.9.1):

```
❯ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by poornas** [comment]
@auvn, was able to reproduce this issue. Agree that it would be better to return an empty response rather than throw a NotImplemented error.

**Comment by auvn** [comment]
good news :) thank you

**Comment by auvn** [comment]
btw, just in case: the issue happens only if I specify the prefix params, without the prefix I am getting an empty response as expected
