### ISSUE TITLE
Remove all the "remove" functionality for authorized access

### ISSUE THREAD

**Issue by bitatomcat** [minio/minio#5431]
I have a requirement to disable three remove interfaces
remove_bucket
remove_object
remove_objects

Is it configurable?  If not would have to modify the source.

**Comment by harshavardhana** [comment]
We do not have a way to disable individual APIs for authorized access. You can setup a proxy and reject all DELETE http requests without modifying minio code.

**Comment by kannappanr** [comment]
Marking this issue as answered. Please feel free to open an issue if you have further questions.
