### ISSUE TITLE
AdminAPI accepts Signature-V4 requests without signed X-Minio-Operation header 

### ISSUE THREAD

**Issue by aead** [minio/minio#5436]
The AdminAPI accepts Signature V4 requests without signed `X-Minio-Operation` header.
A V4 request contains a list of signed headers. By default `mc` signs all headers except:
- Authorization
- Content-Type
- Content-Length
- User-Agent

Luckily because of this fact this is not a security issue. However the server accepts V4 requests even if `X-Minio-Operation` is not part of the signed headers. Such a request (without signed `X-Minio-Operation` header) could be abused to set server credentials and thereby take over the server.

## Expected Behavior
The server should reject requests without signed `X-Minio-Operation` header.
This means: If the `X-Minio-Operation` header is present it must be a signed header.

## Current Behavior
Server accepts requests without signed `X-Minio-Operation` header.

## Possible Solution
Check whether the signed headers contain `X-Minio-Operation` if the header is present.

## Steps to Reproduce (for bugs)

1. Add `"X-Minio-Operation"` [here](https://github.com/minio/mc/blob/master/vendor/github.com/minio/minio-go/pkg/s3signer/request-signature-v4.go#L78)
2. Rebuild `mc` (`go install github.com/minio/mc`
3. `mc admin service status YOUR_SERVER`
4. Server will accept request

The request could be used to trigger `ServiceCredentialsHandler` and set the server credentials to a custom value. 

## Context
Admin-API security audit

Is it worth to fix @donatello or should we wait for new Admin-API?

## Your Environment
master

**Comment by donatello** [comment]
@aead I expect that the new admin API will be merged in a day or so and will be present in the next release. The new API does not use x-minio-operation header and all operations have paths in the URL and would be used in the signature.

**Comment by aead** [comment]
Okay, than we don't need to fix and can wait for new API. Closing because of #5351
