### ISSUE TITLE
Investigate compression of objects in minio

### ISSUE THREAD

**Issue by deekoder** [minio/minio#5446]
As per discussion, investigate compression for IOT data usecases.

**Comment by aead** [comment]
Just some hints: 
 - [https://en.wikipedia.org/wiki/Brotli](https://en.wikipedia.org/wiki/Brotli) 
 - [https://en.wikipedia.org/wiki/Zstandard](https://en.wikipedia.org/wiki/Zstandard)

**Comment by harshavardhana** [comment]
Fixed by #6292
