### ISSUE TITLE
Browser incorrectly selects bucket as active when URL to invalid/nonexistent bucket is entered

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#5452]
## Expected Behavior

When the user enters a URL leading to an invalid/nonexistent bucket for the Minio Browser, that bucket should not be set as the current bucket.

## Current Behavior

When the user enters a URL leading to an invalid/nonexistent bucket in the Minio Browser, that bucket is being set as the current bucket even though the characters are invalid or the bucket does not exist. This leads to the user to see a loading message in place of where the files are normally listed. The user also has the option to upload a file to this bucket, but the upload does not complete and a 404 Not Found error on the browser console is displayed. Please refer to the screenshots for further reference.

<img width="1280" alt="screen shot 2018-01-26 at 12 08 09 pm" src="https://user-images.githubusercontent.com/27314853/35458686-27087938-0292-11e8-90ae-d6a7f2329955.png">

<img width="1280" alt="screen shot 2018-01-26 at 12 11 54 pm" src="https://user-images.githubusercontent.com/27314853/35458695-2f4591a8-0292-11e8-9fe9-81b8ab7a6772.png">

## Possible Solution

Before setting the bucket specified in the URL as the current bucket, we need to check if it exists or if it is valid in the way that we are generating the error messages, which still appear as popups when a path to an invalid/nonexistent bucket is entered in the URL

## Steps to Reproduce (for bugs)

1. Open Minio Browser
2. Create a few buckets
3. Enter a URL that leads to a bucket that is invalid or doesn't exist in the current list of buckets, like `localhost:9000/minio/INVALID` or `localhost:9000/minio/nonexistent` assuming that the Minio Browser is running on `localhost:9000`

## Context

This issue would cause confusion for users as they might think that the invalid/nonexistent bucket they entered in the URL is existing/active, and the "Loading..." message implies that the contents of that bucket are still loading.

## Your Environment

* Version used (`minio version`): latest (This rarely happens on play.minio.io, however the "Loading..." message is not visible there)
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): macOS High Sierra 10.13.2
* Link to your project:

**Comment by kanagarajkm** [comment]
This issue is fixed after the browser re-write. Opening `https://play.minio.io:9000/minio/nonexistent/` will take the user to the first available bucket.

**Comment by harshavardhana** [comment]
You mean the issue is fixed in master branch?

**Comment by kanagarajkm** [comment]
@harshavardhana yes

**Comment by nitisht** [comment]
closing this based on previous comments
