### ISSUE TITLE
[PR#5160] Error out if wrong ellipsis syntax used

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5458]
When wrongly formed ellipsis used like `mydisk{1..64}`, we would need to error out than creating an endpoint as `mydisk{1..64}`

Step to reproduce the bahavior:
$ minio server 'mydisk{1..64}'

**Comment by harshavardhana** [comment]
> When wrongly formed ellipsis used like mydisk{1..64}, we would need to error out than creating an endpoint as mydisk{1..64}
> 
> Step to reproduce the bahavior:
> $ minio server 'mydisk{1..64}'

We cannot detect this @balamurugana - bash already expands the `..` style. By the time the control reaches the CLI the expansion is complete.

**Comment by balamurugana** [comment]
@harshavardhana I haven't used bash to produce this error.  BTW its possible in bash not to expand it.

**Comment by harshavardhana** [comment]
> @harshavardhana I haven't used bash to produce this error. BTW its possible in bash not to expand it.

yeah i saw the quotes specifically being used, lets see how to handle this specifically.
