### ISSUE TITLE
[PR#5160] Wrong ellipsis format leads to wrong setup

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5461]
Running with command `minio server n{1...10}.m{1...8}` makes wrong endpoints
```
n{1...10}.m1 n{1...10}.m2 n{1...10}.m3 n{1...10}.m4 n{1...10}.m5 n{1...10}.m6 n{1...10}.m7 n{1...10}.m8
```

**Comment by harshavardhana** [comment]
The ellipses syntax for double is only supported for HTTP endpoints, i guess we need to error out.
