### ISSUE TITLE
Issue running shared Minio on GlusterFS backend

### ISSUE THREAD

**Issue by jonandernovella** [minio/minio#5467]
## Expected Behavior
Concurrently writing files to a PV volume should result in a successful upload.

## Current Behavior
When pushing data using Pachyderm via `pachctl put-file`, using a parallelism of 10, the logs from pachd show the following:

`2018-02-14T19:24:32Z ERROR pfs.BlockAPI.Obj.PutObjectSplit {"duration":27.47588571,"error":"unexpected EOF","request":null} 
2018-02-14T19:24:32Z ERROR pfs.API.PutFile {"duration":27.478187142,"error":"unexpected EOF","request":{"file":{"commit":{"repo":{"name":"mrpo"},"id":"b5282c46545848c08f6604fb482776c6"},"path":"0011.mzML"}}} 
2018-02-14T19:24:42Z ERROR pfs.BlockAPI.Obj.PutObjectSplit {"duration":36.856480149,"error":"The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.","request":null} 
2018-02-14T19:24:42Z ERROR pfs.API.PutFile {"duration":36.883879766,"error":"The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.","request":{"file":{"commit":{"repo":{"name":"mrpo"},"id":"b5282c46545848c08f6604fb482776c6"},"path":"0018.mzML"}}}  `

## Steps to Reproduce (for bugs)
1. Deploy shared Minio on Kubernetes backed by GlusterFS and deploy Pachyderm on Kubernetes 
2. Create a repository and put several big files with a parallelism of 35  (I tested it with 200 files of approximately 200Mb each)
`pachctl put-file -r -c -p 35 myrepo master -f .`

## My setup and code
* Version used: Pachyderm 1.6.6, Kubernetes 1.9.2
* Environment: Pachyderm + Minio running on Kubernetes
* Pachyderm deployment using Helm chart: https://github.com/kubernetes/charts/tree/master/stable/pachyderm
* Shared Minio deployment in Kubernetes with 50 replicas writing to a PV provided by heketi (GlusterFS version  `gluster/gluster-centos:gluster3u9_centos7`, Minio version `RELEASE.2017-12-28T01-21-00Z`)
* StorageClass settings: https://github.com/kubenow/KubeNow/blob/k8s-1.9.2/playbooks/roles/heketi-gluster/templates/object-store-sc.yml

**Comment by jonandernovella** [comment]
Issue semi-solved. Changed volume options as recommended here and it works with certain settings. https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3/html/configuring_red_hat_openstack_with_red_hat_storage/sect-setting_up_red_hat_storage_trusted_storage_pool

**Comment by jonandernovella** [comment]
Updated the issue with tests under new settings and logs from gluster.

**Comment by harshavardhana** [comment]
Thanks @jonandernovella we will take a look

**Comment by jonandernovella** [comment]
The issue seems to have been solved by changing some advanced GlusterFS volume options. I stressed the storage backend with different loads and it seemed to work fine. These include the listed in the following tutorial: https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.2/html/configuring_red_hat_virtualization_with_red_hat_gluster_storage/chap-hosting_virtual_machine_images_on_red_hat_storage_volumes

@harshavardhana commented that it might be related to the way Gluster was dealing with lock acquisitions in our setting. Can you add to this/suggest why this new settings might do the trick?

**Comment by harshavardhana** [comment]
Can you provide the output of `gluster volume info `. For our reference ?

**Comment by harshavardhana** [comment]
> Can you provide the output of gluster volume info. For our reference ?

Can you provide us the output of `gluster volume info` @jonandernovella

**Comment by jonandernovella** [comment]
@harshavardhana 

``` Volume Name: vol_ef774d043198bc6bcc395902cb419978
Type: Replicate
Volume ID: a4a6de4a-b149-49fc-881d-4025e2888758
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: 10.0.169.121:/var/lib/heketi/mounts/vg_1b9dcd3ef45eb3b821a3a5d815458026/brick_139f15390a44b578b515c205ff6f67a5/brick
Brick2: 10.0.128.143:/var/lib/heketi/mounts/vg_7df4bf19473dbb378af42b8c405dcd0a/brick_ac4b94e761b2bbaf8fe3b2381bd302b0/brick
Brick3: 10.0.30.101:/var/lib/heketi/mounts/vg_9111f4f5fc1165cd31dcc57a1f4d31f4/brick_9a61432e33f6418c1b5bfb6c1c56856d/brick
Options Reconfigured:
user.cifs: off
features.shard: on
cluster.shd-wait-qlength: 10000
cluster.shd-max-threads: 8
cluster.locking-scheme: granular
cluster.data-self-heal-algorithm: full
cluster.server-quorum-type: server
cluster.quorum-type: auto
disperse.eager-lock: enable
cluster.eager-lock: enable
network.remote-dio: enable
performance.low-prio-threads: 32
performance.stat-prefetch: off
performance.io-cache: off
performance.read-ahead: off
performance.quick-read: off
transport.address-family: inet
nfs.disable: on ```

Please note that the issues were also present with `replicated` and `single` volume types.

**Comment by harshavardhana** [comment]
`cluster.locking-scheme: granular` I think this is the volume option that is needed.

**Comment by harshavardhana** [comment]
@jonandernovella can you confirm if this is fixed ?

**Comment by harshavardhana** [comment]
@jonandernovella closing this as working . Feel free to open a new issue if you have further problems.
