### ISSUE TITLE
InvalidStorageClass when calling the PutObject for storage-class STANDARD_IA

### ISSUE THREAD

**Issue by hungntit** [minio/minio#5469]
I use the docker image minio/minio:RELEASE.2018-01-18T20-33-21Z or latest, when I execute the command: 
`aws --endpoint-url http://localhost:9555 --profile localdev s3 cp --storage-class STANDARD_IA README.md s3://tettet/README.md`
I got the result  _upload failed: ./README.md to s3://tettet/README.md An error occurred (InvalidStorageClass) when calling the PutObject operation: Invalid storage class._

But it run successfully when I use the old image minio/minio:RELEASE.2017-11-22T19-55-46Z

**Comment by nitisht** [comment]
@hungntit storage classes were not supported as of version `minio/minio:RELEASE.2017-11-22T19-55-46Z` and the input was ignored. 

We recently added support for storage classes with `STANDARD` and `REDUCED_REDUNDANCY` classes. As `STANDARD_IA` is not supported you get the error. Refer to storage class documentation [here](https://github.com/minio/minio/tree/master/docs/erasure/storage-class).

**Comment by hungntit** [comment]
@nitisht Will we support for `STANDARD_IA` storage class?

**Comment by nitisht** [comment]
it is not planned as of now @hungntit .

**Comment by harshavardhana** [comment]
> @nitisht Will we support for STANDARD_IA storage class?

There is no meaning for STANDARD_IA in Minio while it can be implemented, it is quite redundant with STANDARD.

**Comment by nitisht** [comment]
Closing this as answered @hungntit feel free to reopen/reachout on [Slack](https://slack.minio.io) for further questions.

**Comment by hungntit** [comment]
Currently I use minio on dev environment instead of S3. Could we support STANDARD_IA like STANDARD storage class?

**Comment by harshavardhana** [comment]
> Currently I use minio on dev environment instead of S3. Could we support STANDARD_IA like STANDARD storage class?

STANDARD_IA is not meaningful in context of Minio, STANDARD_IA is STANDARD in Minio so you can simply use STANDARD. We can also make STANDARD_IA behave like STANDARD but we didn't want to confuse users so we error out.

**Comment by hungntit** [comment]
Thanks @harshavardhana  @nitisht
