### ISSUE TITLE
allows rrs == standard redundancy for 4 disks, but bans it for 6 disks.

### ISSUE THREAD

**Issue by thorsteinssonh** [minio/minio#5474]
## Expected Behavior
User expects consistent behavior from minio in case of which rrs and standard redundancies are allowed.  Expect 4 and 6 disks startups to follow same rules.

## Current Behavior
Currently minio allows rrs == reduced for 4 disks, but refuses to accept 6 disks with same settings.
This is unintuitive. Harshavardhana explained that there has been contention about allowing 4 disk erasures.

## Possible Solution
Possibly...:
- allow rrs == reduced throughout, 
- or reduce minimum rrs to EC:1
- or set 6 as minimum disk number for erasure codes.
- or remove defuault rrs and allow any user defined storage class

## Steps to Reproduce (for bugs)
Start a new minio instance with 4 disks default settings
Also try to start instance with 6 disks, but asking for standard EC:2 and rrs EC:2,
and observe error message from minio.

## Context
Have been mixing and matching disk types that are available on my server, but attempting
to replicate "similar" redundancy throughout.  I.e. attempting to configure an N/3 redundancy instead of N/2 redundancy lead me to try to set 6 disk instance with rrs == standard == 2

**Comment by harshavardhana** [comment]
Fixed by #5470
