### ISSUE TITLE
[PR#5160] unable to use endpoints with ellipsis

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5484]
```
$ minio server sda1 sdb{2...6}

Trace: 1: cmd/server-main.go:121:cmd.serverHandleCmdArgs()
       2: cmd/server-main.go:171:cmd.serverMain()
       3: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       6: cmd/main.go:149:cmd.Main()
       7: main.go:71:main.main()
[2018-02-01T12:47:41.528948549Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[sda1 sda{2...6}] (Unsupported range size 2, minimum range size is 1...4)
```

**Comment by harshavardhana** [comment]
This is not purposefully supported @balamurugana as i explained before the ellipses syntax expands per argument, arguments are not combined in the manner like this. Each ellipses needs to be properly divisible and should be expandable.

This is done on purpose to support situations where users don't want have redundancy to spawn across disks, in such a scenario it is expected that they provide ellipses range properly.

NOTE: These styles are not going to be documented

**Comment by balamurugana** [comment]
@harshavardhana This requires a discussion.  Breaking large set to multiple smaller sets come with lower fault tolerance setup.

**Comment by harshavardhana** [comment]
> @harshavardhana This requires a discussion. Breaking large set to multiple smaller sets come with lower fault tolerance setup.

This was already discussed @balamurugana and is implemented as agreed. The point is users know what they are trying to do here and it is an undocumented behavior as well.  In a scenario like this we are actively going to educate users on the pitfalls if they really don't know what they are doing.

**Comment by balamurugana** [comment]
Reopened wrong issue
