### ISSUE TITLE
[PR#5160] Valid ellipses are not working

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5485]
```
$ minio server sda{1...7} sdb{1...7}

Trace: 1: cmd/server-main.go:121:cmd.serverHandleCmdArgs()
       2: cmd/server-main.go:171:cmd.serverMain()
       3: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       6: cmd/main.go:149:cmd.Main()
       7: main.go:71:main.main()
[2018-02-01T12:57:06.633773087Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[sda{1...7} sdb{1...7}] (Unsupported range size 7, range should be divisible by one of the supported erasure sets [4 6 8 10 12 14 16])
```

**Comment by harshavardhana** [comment]
This is not purposefully supported @balamurugana as i explained before the ellipses syntax expands per argument, arguments are not combined in the manner like this. Each ellipses needs to be properly divisible and should be expandable. 

This is done on purpose to support situations where users don't want have redundancy to spawn across disks, in such a scenario it is expected that they provide ellipses range properly.  

NOTE:  These styles are not going to be documented
