### ISSUE TITLE
implement service discovery

### ISSUE THREAD

**Issue by yajo** [minio/minio#5492]
To get a really resilient storage cloud, service discovery needs to be implemented.

## Expected Behavior

Minio should be able to use some service discovery system, such as etcd or similar, and fetch siblings from there instead of needing to hardcode them in the cli of settings.

## Current Behavior

Minio needs a hardcoded list of siblings: `minio server http://minio1:9000/export http://minio2:9000/export`

## Possible Solution

    minio server --etcd=http://etcd

... And watch for changes there.

## Context

I'm trying to use the full poder of docker swarm, being able to scale up or down a replicated service, and exposing just one port to the network routing mesh.

**Comment by harshavardhana** [comment]
Bucket and config discovery is a work in progress as part of federation work to discover many deployments.

Individual deployment units of Minio are always expected to be proper command line options - it is very much part of the design and this is not going to change.

**Comment by yajo** [comment]
May I ask why? It doesn't seem to be an extremely hard feature and it seems to align well with the project philosophy IMHO. Thanks.

**Comment by harshavardhana** [comment]
> May I ask why? It doesn't seem to be an extremely hard feature and it seems to align well with the project philosophy IMHO. Thanks.

It adds an unneeded dependency, the design philosophy of Minio is to keep the most common deployments simple and predictable. Minio is deployed in static deployment units and each such units are completely isolated from each other. 

etcd is required only when all of these different deployment units need to federate which is why we will be introducing a way to manage multiple creds across many deployments, global bucket awareness etc.

**Comment by yajo** [comment]
But then, adding the node nº 101 to a 100-node cluster means changing CLI on the other 100, isn't it? While just letting nodes be autodiscovered is more a Plug&play approach, while still not having to remove the current feature set, of course.
In a big, dynamic, cloud deployment, this very little piece of the puzzle means a lot of manual work...
Or maybe I didn't understand clearly what you mean with "multiple creds across many deployments, global bucket awareness" 🤔

**Comment by harshavardhana** [comment]
> But then, adding the node nº 101 to a 100-node cluster means changing CLI on the other 100, isn't it? While just letting nodes be autodiscovered is more a Plug&play approach, while still not having to remove the current feature set, of course.

Minio doesn't allow adding 100 to 101 - there is no dynamic expansion.  If you started with 100 it stays 100 forever, you can potentially start a new 100.  This is one of the reason why we never require etcd. 

etcd is only useful when there are dynamic floating entities that is the case for buckets, multiple credentials which will be provided in the federation.

**Comment by yajo** [comment]
> Minio doesn't allow adding 100 to 101 - there is no dynamic expansion. If you started with 100 it stays 100 forever, you can potentially start a new 100. This is one of the reason why we never require etcd.

Oh Ok, I get it now clearly 😉 

However that's a very weird design decision... Scalability is not on the project's roadmap? How can somebody know all the disk space he will need forever? And why pay for that since the start, when you still don't need it?

Certainly Minio's features are great, but this one decision feels like narrowing its purpose for non-serious business, don't you think?... 🤔

**Comment by harshavardhana** [comment]
> However that's a very weird design decision... Scalability is not on the project's roadmap? How can somebody know all the disk space he will need forever? And why pay for that since the start, when you still don't need it?
> 
> Certainly Minio's features are great, but this one decision feels like narrowing its purpose for non-serious business, don't you think?.

Making a single large PB sized volume where the disks and nodes are managed like a blackbox by the filesystem is quite scary. Any crash means we blew up all the tenants at once. 1000s of individual minio tenants means, I know when I add the million'th minio instance, it is not any more complex than the first instance of Minio. Provisioning with k8 or external orchestration tools is better than Minio's own resource management system. When it comes to the applications, objects are just represented as URLs. Some data sitting on Amazon S3 and some on Minio makes no difference to the application.  With this principle in mind Minio is designed for scalability, you scale in smaller scalable units.
