### ISSUE TITLE
Creating a directory fails when SSE-C is enabled

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#5493]
## Expected Behavior
Directories are now supported on both FS and Erasure coded backends but with SSE-C we shouldn't interpret them specially. 

## Current Behavior
SSE-C enabled requests for directory creates are not supported.

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Create a PutObject request with SSE-C headers enabled make sure to have the object name with `/` suffixed. 

## Context
Supporting `s3fs` like clients. 

## Your Environment
Minio master branch.

**Comment by aead** [comment]
A possible solution is to add the following check: `&& size > 0` [here](https://github.com/minio/minio/blob/master/cmd/object-handlers.go#L559).
