### ISSUE TITLE
Update vendored grpc package

### ISSUE THREAD

**Issue by iwanbk** [minio/minio#5498]
Current version of `grpc` is too old (2017-04-28T22:32:14Z) i think it is better to update the `grpc` package, the newer version the better

## Expected Behavior

Should use latest `grpc` or newer version than currently used

## Current Behavior

too old `grpc` version (0eb507a2ca07f13baf499f89d66cc566bf644643 , dated 2017-04-28T22:32:14Z)

## Possible Solution

Update `grpc`, the newer the better

## Steps to Reproduce (for bugs)

check `grpc` version in `vendor/vendor.json` file.

## Context

We (my company) are developing minio gateway for [0-stor](https://github.com/zero-os/0-stor), which use `grpc` API not available in `grpc` version used by minio.

0-stor doesn't use latest version either, but use newer version (v1.5.2, dated at 2017-08-04).

I think the best solution is update to latest grpc, or newer version of it

## Your Environment

* Version used (`minio version`): 48218272cceb2d6cf2d1a59e44e5bf13aee69d9f
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: ubuntu 16.04
* Operating System and version (`uname -a`):
* Link to your project: https://github.com/gigforks/minio

Is there a reason to use old version of `grpc`?

If not, i have managed to update `grpc` up to v1.6.0 and is going to continue my work to update to the version you want.

Just let me know which version we need to update and i will happily send the PR.

**Comment by harshavardhana** [comment]
why is newer grpc better @iwanbk ? - we have no direct dependency on it.

**Comment by iwanbk** [comment]
> why is newer grpc better @iwanbk 

It normally contains fixes and improvements of the older version.
Current version used doesn't even a release version (v1.4.0-dev).

If you worry of regression when we jump to `v.1.9.2` from `v1.4.0-dev`, `v.1.5.2` is enough for our usage, it also easier to check/test if there is regression because the smaller difference than with v1.9.2

**Comment by iwanbk** [comment]
closing this because it is not relevant anymore.
See https://github.com/minio/minio/pull/5500#issuecomment-369371374
