### ISSUE TITLE
minio ignores policy rules?

### ISSUE THREAD

**Issue by kiltum** [minio/minio#5503]
I try to limit bucket to "read-only" or "write-only" state, but without success.

Create bucket "test" at server test and set policy to "upload"

```
/ # mc policy upload test/test
Access permission for `test/test` is set to `upload`
/ # mc policy test/test
Access permission for `test/test` is `upload`
/ # mc policy list test/test
test/* => writeonly
/ #
```

I see the same in web interface.

## Expected Behavior

```
$ cat > testfile
fjnklnlln
$ s3cmd put testfile s3://test/wow
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'testfile' -> 's3://test/wow'  [1 of 1]
 10 of 10   100% in    0s   666.80 B/s  done
[at next commands i should get error like "access denied" or something like this]
$ s3cmd get s3://test/wow
$ mc cat test/test/wow

```

## Current Behavior

```
$ cat > testfile
fjnklnlln
$ s3cmd put testfile s3://test/wow
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'testfile' -> 's3://test/wow'  [1 of 1]
 10 of 10   100% in    0s   666.80 B/s  done
$ s3cmd get s3://test/wow
download: 's3://test/wow' -> './wow'  [1 of 1]
 10 of 10   100% in    0s   619.66 B/s  done
$ mc cat test/test/wow
fjnklnlln
```

## Context

i just try to make "write-only"  bucket, so anyone with keys can only add files, but not download them. 

## Your Environment

* Version used (`minio version`):
$ minio version
Version: 2018-01-18T20:33:21Z
Release-Tag: RELEASE.2018-01-18T20-33-21Z
Commit-ID: e2d5a87b2676e3e01f0f4fa7ebd01205364cfb16
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
```
$ uname -a
Darwin mbook 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

and the same situation in docker

**Comment by poornas** [comment]
``` 
i just try to make "write-only" bucket, so anyone with keys can only add files, but not download them.
```

@kiltum, the bucket policies are meant to restrict anonymous access to a bucket, if anyone has keys they will be able to both download/upload.  
```
$ s3cmd get s3://test/wow
download: 's3://test/wow' -> './wow'  [1 of 1]
 10 of 10   100% in    0s   619.66 B/s  done
$ mc cat test/test/wow
fjnklnlln
```
The above 2 commands were tried in authenticated mode, i.e. with keys - hence the content was served. 

You could do a curl GET request on the test/wow file - it should return access denied because you have set the policy for test bucket to upload only.

**Comment by kiltum** [comment]
Ooops. Looks like this behaviour is a little tricky .... Ok. I got this.
Thank you!
