### ISSUE TITLE
Unable to run on docker for windows.

### ISSUE THREAD

**Issue by niemyjski** [minio/minio#5504]
I have a windows build on appveyor and I wanted to test against a local docker instance (https://ci.appveyor.com/project/Exceptionless/foundatio-minio/build/7.0.3). It's failing with: 

```
docker pull minio/minio
Using default tag: latest
latest: Pulling from minio/minio
docker : image operating system "linux" cannot be used on this platform
```

After some research it appears that a manifest needs to be added to the docker configs: https://github.com/dotnet/dotnet-docker/issues/99

**Comment by vadmeste** [comment]
@niemyjski Minio doesn't have a Windows image AFAIK but the Linux image is supposed to work if Docker under Windows can emulate Linux binaries.

Also, it looks like Appveyor needs to support nested virtualization with Windows 2016, it seems this is not done yet.

See https://help.appveyor.com/discussions/questions/2652-windows-server-2016/page/2 and 
https://github.com/appveyor/ci/issues/1717

**Comment by niemyjski** [comment]
Thanks! Do you know if there are any plans to add a windows image?

**Comment by harshavardhana** [comment]
We do not have any current plans to create one @niemyjski . You could simply download `minio` windows binary and use the following bat script 

https://gist.github.com/harshavardhana/7ee9302375a181eb20f7fb3ff0a041e0#file-minio-server-bat

**Comment by kannappanr** [comment]
@niemyjski Closing this issue as answered. Please feel free to open a new issue if you have further questions.
