### ISSUE TITLE
VirtualHost + Signature V2: Signature mismatch 

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5506]
## Expected Behavior
Listing objects work with virtual host style and V2 signature method 

## Current Behavior
Listing objects doesn't work with virtual host style and V2 signature method 

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Set "localhost" in ~/.minio/config.json
2. Run Minio server
3. Run the following code:
```
package main

import (
	"fmt"
	"log"

	"github.com/minio/minio-go"
	"github.com/minio/minio-go/pkg/credentials"
)

func main() {
	creds := credentials.NewStaticV2("minio", "minio123", "")
	options := minio.Options{
		Creds:        creds,
		Secure:       false,
		Region:       "",
		BucketLookup: minio.BucketLookupDNS,
	}
	s3Client, err := minio.NewWithOptions("localhost:9000", &options)
	if err != nil {
		log.Fatal(err)
	}

	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	// List all objects from a bucket-name with a matching prefix.
	for object := range s3Client.ListObjects("testbucket", "", true, doneCh) {
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		fmt.Println(object)
	}
	return
}
```

## Context
Fixing bugs

## Your Environment
All

**Comment by poornas** [comment]
@vadmeste, minio.BucketLookupDNS will work only when server can handle virtual hosted style requests. So when user specifies BucketLookupDNS the expectation is that server can handle such requests, and they have deliberately chosen DNS style lookup. In the context of running minio server on localhost it will not work.

**Comment by vadmeste** [comment]
@poornas I think it should work and it is already working with V4. The code above works fine if I change V2 to V4.

**Comment by poornas** [comment]
@vadmeste , while it doesn't throw a signature mismatch error, it doesn't list the objects when I use V4

**Comment by vadmeste** [comment]
@poornas it lists objects for me.. it must be something in your config, are you sure you have at least one object under 'testbucket' ?

**Comment by poornas** [comment]
@vadmeste, yes

**Comment by vadmeste** [comment]
This is a minio-go bug, not a Minio server bug. Tested this condition with s3cmd & aws java SDK and it works fine.

**Comment by vadmeste** [comment]
This issue is created instead https://github.com/minio/minio-go/issues/920, closing this.
