### ISSUE TITLE
VirtualHost: Creating a bucket doesn't work

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5509]
## Expected Behavior
When virtual host mode is enabled in Minio server, we can create new buckets

## Current Behavior
When virtual host mode is enabled in Minio server, we can't create new buckets, the error is 
`A header you provided implies functionality that is not implemented`

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
1. Set "localhost" to domain field in ~/.minio/config.json
2. Start Minio server
3. Run the following code minio-go code:
```
package main

import (
	"log"

	"github.com/minio/minio-go"
	"github.com/minio/minio-go/pkg/credentials"
)

func main() {
	creds := credentials.NewStaticV4("minio", "minio123", "")
	options := minio.Options{
		Creds:        creds,
		Secure:       false,
		Region:       "",
		BucketLookup: minio.BucketLookupDNS,
	}
	s3Client, err := minio.NewWithOptions("localhost:9000", &options)
	if err != nil {
		log.Fatal(err)
	}

	err = s3Client.MakeBucket("my-bucketname", "us-east-1")
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Success")
}
```

## Context
Fixing bugs

## Your Environment
Last Minio master

**Comment by harshavardhana** [comment]
this is expected in current master @vadmeste this is being fixed in #5501
