### ISSUE TITLE
SSE-C multipart requires ObjectLayer interface refactoring

### ISSUE THREAD

**Issue by aead** [minio/minio#5510]
The SSE-C multipart PUT operation requires to verify that the user provided key matches the key specified during InitMultipart. Therefore multipart PUT must access the metadata of the temporary multipart object (written to tmp dir during multipart upload). This is not possible because of `ObjectLayer` interface limitations.

## Possible Solution 

Find a clean way to get access to (most) backend functionality. Currently the `ObjectLayer` interface is to close to S3 API.   

## Context
Encryption, SSE-C

## Your Environment
master

**Comment by harshavardhana** [comment]
Why not simply have a similar style like CopyObject since headers will be sent in each case for multipart operations?

I don't see the limitations it's simply adding a metadata argument to PutObjectPart() and validating them internally.

**Comment by aead** [comment]
No,I have to verify that the key sent by client during PutPart is the same as the key sent by the client during InitMultipart. Further I have to check that the key for part2 is the same as for part1.

The context is that client can send wrong keys and we have to error out... 

EDIT: I see what you mean by:
 >validating them internally.

It may work... However it's not a nice design. Some encryption logic in S3-layer, some in Object/Backend-Layer. (mixing layers) So we would workaround the "ObjectLayer interface" issue by duplicating logic in two layers...

**Comment by harshavardhana** [comment]
> It may work... However it's not a nice design. Some encryption logic in S3-layer, some in Object/Backend-Layer. (mixing layers) So we would workaround the "ObjectLayer interface" issue by duplicating logic in two layers...

The encryption logic in s3 layer is to pass the reader - the one in the object layer is simply to validate the incoming headers, this is to avoid even to start reading from the reader.  it would be unclean if we are reading some metadata from `.minio.sys` in S3 layer. I don't see why it would be a problem, since in case of gateway you need to sent the headers all the way to the remote backend anyways. Incidentally introducing the SSE-C feature for S3 gateway as well.

**Comment by aead** [comment]
> it would be unclean if we are reading some metadata from .minio.sys in S3 layer.

We already do that (of course not from .minio.sys). We do HEAD then verify key and then GET for SSE-C GET. I was thinking of something like internal HEAD operation for temp. multipart objects.

>The encryption logic in s3 layer is to pass the reader - the one in the object layer is simply to validate the incoming headers, this is to avoid even to start reading from the reader.

Well it's not that simple. For example we erase the client key from metadata already at the S3-layer to avoid saving the key as part of metadata by accident.

>since in case of gateway you need to sent the headers all the way to the remote backend anyways. Incidentally introducing the SSE-C feature for S3 gateway as well.

That depends upon how we implement SSE-C at gateway. Either we forward - then we don't do anything on the server or we encrypt on the server but then we should not forward headers...

**Comment by harshavardhana** [comment]
> Well it's not that simple. For example we erase the client key from metadata already at the S3-layer to avoid saving the key as part of metadata by accident.

Isn't validating the hmac enough for the secret key? why wouldn't we pass the client key to down layer? since we need to do pass through anyways for gateway why are we stripping it? we should simply send it. It is upto us the implementation to be careful.  We have trusted a DARE specification to be tamper proof i don't see why we not trust our object layer implementations.

**Comment by harshavardhana** [comment]
> We already do that (of course not from .minio.sys). We do HEAD then verify key and then GET for SSE-C GET. I was thinking of something like internal HEAD operation for temp. multipart objects.

We could simply do `ListMultipartUploads()` for the given object and pick the right `upload-id` and corresponding MultipartInfo which should carry metadata as well.

**Comment by aead** [comment]
Okay, that sounds like a good approach - will explore, thanks.

**Comment by harshavardhana** [comment]
> We could simply do ListMultipartUploads() for the given object and pick the right upload-id and corresponding MultipartInfo which should carry metadata as well.

does S3 validate if each part used the same SSE-C keys? or does it validate at CompleteMultipart?

**Comment by aead** [comment]
>Multipart Upload — When uploading large objects using the multipart upload API, you can specify these headers. You specify these headers in the initiate request (see Initiate Multipart Upload) and each subsequent part upload request (Upload Part). For each part upload request, the encryption information must be the same as what you provided in the initiate multipart upload request. 

https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html

IIRC it fails per part but I can check again to be sure...
Verifying at the CompleteMultipart would be surprising since AWS would have to store key which they claim they don't do...

**Comment by harshavardhana** [comment]
This is not necessary it is already addressed without changing much in the backend in @vadmeste branch.  We don't need object interface refactoring at all.

**Comment by harshavardhana** [comment]
This is already fixed in PR #5576
