### ISSUE TITLE
Server should fail if SSE-C headers are provided but backend does not support encryption

### ISSUE THREAD

**Issue by aead** [minio/minio#5511]
## Expected Behavior
The server should fail if the backend does not support encryption *but* SSE-C headers are provided.

## Current Behavior
The server stores the object unencrypted.

## Possible Solution
Add check in object handler layer (S3 -layer)

## Steps to Reproduce (for bugs)
1.  Disable encryption for e.g. FS backend.
2. Build and start server (with TLS) on FS
3.  `aws s3api put-object --no-verify-ssl --endpoint-url https://localhost:9000 --bucket my-bucket --key my-secret-diary --sse-customer-algorithm AES256 --sse-customer-key MzJieXRlc2xvbmdzZWNyZXRrZXltdXN0cHJvdmlkZWQ= --sse-customer-key-md5 7PpPLAK26ONlVUGOWlusfg== --body ~/my-diary.txt`

## Context
Encryption, SSE-C

## Your Environment
master

**Comment by harshavardhana** [comment]
The new Object layer has IsEncryption() for this purpose alone which can be used here.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/blob/4f73fd94878b087b428ccbd309463f956be8dff7/cmd/fs-v1.go#L1141 this should be simply `false`

**Comment by aead** [comment]
Yes exactly, but if it is set to false **and** the client sends SSE-C request we don't fail but store object **unencrypted**. Client may be able recognize that from response headers but we already stored object without encryption.
IMO the server should fail with something like: "Server-Side-Encryption not supported by backend" or so..  

```
if IsSSERequest(r.Header) && !obj.IsEncryptionSupported() {
     // return error
}
```

**Comment by harshavardhana** [comment]
@aead so for this bug to be reproduced you need to modify code, are you trying to say this happens on gateway as well?

**Comment by aead** [comment]
@harshavardhana What I'm saying is that if we add a backend implementation that does not support encryption (currently there is none) we will trigger this issue. The current code relies on the fact that there is no backend which does not support encryption. So I'm suggesting to add a check since the current code contains a (hidden) bug.
On Gateway we don't do SSE-C at the moment as fas as I know... (haven't checked...)

**Comment by harshavardhana** [comment]
> @harshavardhana What I'm saying is that if we add a backend implementation that does not support encryption (currently there is none) we will trigger this issue. The current code relies on the fact that there is no backend which does not support encryption. So I'm suggesting to add a check since the current code contains a (hidden) bug.
> On Gateway we don't do SSE-C at the moment as fas as I know... (haven't checked...)

In-fact you can simply return `ErrNotImplemented` just like how we do for CopyObject and Multipart APIs

**Comment by aead** [comment]
Okay, yes that's basically what I was thinking:
```
if IsSSERequest(r.Header) && !obj.IsEncryptionSupported() {
     // return ErrNotImplemented
}
```

**Comment by kannappanr** [comment]
Should we keep this issue open? Can it be closed?

**Comment by aead** [comment]
I will send a PR to fix this - thanks for the ping @kannappanr

**Comment by harshavardhana** [comment]
Do we already do this?

**Comment by poornas** [comment]
this can be closed - we already do this.

**Comment by kannappanr** [comment]
Closing this issue based on the previous comment
