### ISSUE TITLE
SIA Gateway "Unable to save object"

### ISSUE THREAD

**Issue by chrsch** [minio/minio#5512]
## Expected Behavior
Configure minio sia gateway as s3 storage backend for nextcloud
Nextcloud site is able to store to minio s3 (like it is if using minio without sia)

## Current Behavior
Objects are created in the bucket (1 b size)
No data is uploaded to the objects

## Possible Solution
None known.

## Steps to Reproduce (for bugs)
1. Setup nextcloud with s3 as primary storage (make sure minio s3 works ok without sia before switching over to minio using sia for storage e. g. follow this guide https://github.com/tigerlinux/tigerlinux-extra-recipes/tree/master/recipes/misc/minio-nextcloud-lab )
2. After you did some testing with minio s3 as backend and are sure it works switch to minio s3 sia gateway. Try to access nextcloud site.
3. You will see objects are created in the bucket but all with 1 b size
3. Internal server error is shown after a while, error is raised from minio as posted below (error log)

## Your Environment

* Version used (`minio version`): Version: 2018-01-20T15:47:09Z, Release-Tag: DEVELOPMENT.2018-01-20T15-47-09Z, Commit-ID: 6a769949c43e727b1eae8533f47975ac53729f40
* Run cmd: minio gateway sia --address :443
* Operating System and version (`uname -a`): Linux xxxxx 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## Minio error log
time="2018-02-11T11:35:45Z" level=error msg="Unable to save an object /wssiademo/350" cause="Sia: Object does not exist in bucket." source="[gateway-handlers.go:311:gatewayAPIHandlers.PutObjectHandler()]" 
time="2018-02-11T11:35:45Z" level=error msg="Unable to fetch object info." cause="Sia: Failed to select records in the cache database." source="[gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler()]" 
time="2018-02-11T11:36:11Z" level=error msg="Unable to save an object /wssiademo/358" cause="Sia: Object does not exist in bucket." source="[gateway-handlers.go:311:gatewayAPIHandlers.PutObjectHandler()]" 
time="2018-02-11T11:36:12Z" level=error msg="Unable to save an object /wssiademo/358" cause="Sia: Object does not exist in bucket." source="[gateway-handlers.go:311:gatewayAPIHandlers.PutObjectHandler()]" 
time="2018-02-11T11:36:12Z" level=error msg="Unable to save an object /wssiademo/358" cause="Sia: Object does not exist in bucket." source="[gateway-handlers.go:311:gatewayAPIHandlers.PutObjectHandler()]" 
time="2018-02-11T11:36:12Z" level=error msg="Unable to save an object /wssiademo/358" cause="Sia: Object does not exist in bucket." source="[gateway-handlers.go:311:gatewayAPIHandlers.PutObjectHandler()]"

**Comment by harshavardhana** [comment]
> Sia: Failed to select records in the cache database.

looks like your siad is returning errors @chrsch

**Comment by chrsch** [comment]
Seems like nextcloud tries to read the file directly after doing the first put and siad doesn't yet have the file uploaded completely and therefore not available yet. Shouldn't the s3 gateway handle such situations gracefully? @dvstate  Did you already notice such behavior?

**Comment by harshavardhana** [comment]
> Seems like nextcloud tries to read the file directly after doing the first put and siad doesn't yet have the file uploaded completely and therefore not available yet. Shouldn't the s3 gateway handle such situations gracefully? @dvstate Did you already notice such behavior?

File is only said to be uploaded and ready when the Sia cloud says its available according to the code. it must be that siad is reporting incorrectly and taking more time? 

```go
// deleteTempFileWhenUploadCompletes checks the status of a Sia file upload
// until it reaches 100% upload progress, then deletes the local temp copy from
// the filesystem.
func (s *siaObjects) deleteTempFileWhenUploadCompletes(tempFile string, bucket, object string) {
        var soi siaObjectInfo
        // Wait until 100% upload instead of 1x redundancy because if we delete
        // after 1x redundancy, the user has to pay the cost of other hosts
        // redistributing the file.
        for soi.UploadProgress < 100.0 {
                var err error
                soi, err = s.findSiaObject(bucket, object)
                if err != nil {
                        minio.ErrorIf(err, "Unable to find file uploaded to Sia path %s/%s", bucket, object)
                        break
                }

                // Sleep between each check so that we're not hammering
                // the Sia daemon with requests.
                time.Sleep(15 * time.Second)
        }

        os.Remove(tempFile)
}
```

**Comment by chrsch** [comment]
I also investigated the code and I think the upload request (post() in the code below) is asynchronous. Also see SIA api at https://github.com/NebulousLabs/Sia/blob/master/doc/API.md#renteruploadsiapath-post. The deleteTempFileWhenUploadCompletes is defered and just called to clear up the tmp file needed for the upload by siad. So basically it seems minio returns "upload successful" to the s3 client but the data is not yet available because upload is still ongoing.

Now in a use case where the file (object) is first of created and the s3 client tries to immediately write data to it this will fail and I think this is what we see in above error messages. Sequence goes like this:
Client: Minio put file x.y
Minio: Hey client, file x.y is put (but in fact siad is currently starting the upload)
Client: Ok minio, write data to file x.y (put)
Minio: Siad give me the file (siad is still uploading -> file not available -> error)

Maybe I'm missing something but I think the sia gateway currently completely ignores the fact that uploading to sia will take some moments until file is available.

```go
// PutObject creates a new object with the incoming data,
func (s *siaObjects) PutObject(bucket string, object string, data *hash.Reader, metadata map[string]string) (objInfo minio.ObjectInfo, err error) {
	srcFile := path.Join(s.TempDir, minio.MustGetUUID())
	writer, err := os.Create(srcFile)
	if err != nil {
		return objInfo, err
	}

	wsize, err := io.CopyN(writer, data, data.Size())
	if err != nil {
		os.Remove(srcFile)
		return objInfo, err
	}

	if err = post(s.Address, "/renter/upload/"+path.Join(s.RootDir, bucket, object), "source="+srcFile, s.password); err != nil {
		os.Remove(srcFile)
		return objInfo, err
	}
	defer s.deleteTempFileWhenUploadCompletes(srcFile, bucket, object)

	return minio.ObjectInfo{
		Name:    object,
		Bucket:  bucket,
		ModTime: time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC),
		Size:    wsize,
		ETag:    minio.GenETag(),
	}, nil
}
```

**Comment by harshavardhana** [comment]
Where do you see we return success? We have a function which is executed upon PutObject return i.e to ensure that the file is available on Sia. If siad reported file is available then we exit and return success.

**Comment by harshavardhana** [comment]
NOTE: defer means the function in defer is executed upon the actual function return i.e the function doesn't return until the deferred function has completed successfully.

**Comment by chrsch** [comment]
The point is this code will just start upload process at siad. It will not wait until siad has completed upload.  Will try to make it synchron (wait for upload to completed) and see if this solves the problem.
```go
	if err = post(s.Address, "/renter/upload/"+path.Join(s.RootDir, bucket, object), "source="+srcFile, s.password); err != nil {
		os.Remove(srcFile)
		return objInfo, err
	}
```

**Comment by harshavardhana** [comment]
> The point is this code will just start upload process at siad. It will not wait until siad has completed upload. Will try to make it synchron (wait for upload to completed) and see if this solves the problem.

where do you think it doesn't wait @chrsch ? didn't i show you the code which will wait? 

```
	defer s.deleteTempFileWhenUploadCompletes(srcFile, bucket, object)
```

**Comment by chrsch** [comment]
I understand the defer part. But the PutObject function return successful put operation (though deferred function might still wait for the upload to complete and delete the tmp file). Or do I get this wrong?

**Comment by harshavardhana** [comment]
> I understand the defer part. But the PutObject function return successful put operation (though deferred function might still wait for the upload to complete and delete the tmp file). Or do I get this wrong?

The defer gets executed and waits until the upload completes PutObject will never return until the defer is completed.  This is the reason to have `defer` in the first place to execute different functions on function return and the function return is blocked until the `defers` are completed.

**Comment by chrsch** [comment]
Ah ok I had to educate myself some go... Thanks for pointing out, so this is actually not the problem ;-)

**Comment by deekoder** [comment]
i will close this issue hence. Please lets us know if you have any further questions @chrsch
