### ISSUE TITLE
Docker - Many healthcheck processes in the container as Zombies on Swarm

### ISSUE THREAD

**Issue by OsamaJBR** [minio/minio#5514]
I've notice that there are many zombie process on all swarm hosts, all of them are **/usr/bin/healthcheck.sh**. 

I've entered to one of running container
```
root@node01 ~ # docker exec -it 12cf0485d665 /bin/sh
/ # ps
PID   USER     TIME   COMMAND
    1 root       1:57 minio server /export
  281 root       0:00 [healthcheck.sh]
  295 root       0:00 [healthcheck.sh]
  437 root       0:00 [healthcheck.sh]
  495 root       0:00 [healthcheck.sh]
  749 root       0:00 [healthcheck.sh]
  873 root       0:00 [healthcheck.sh]
  887 root       0:00 [healthcheck.sh]
  915 root       0:00 [healthcheck.sh]
  943 root       0:00 [healthcheck.sh]
  971 root       0:00 [healthcheck.sh]
 1054 root       0:00 [healthcheck.sh]
 1152 root       0:00 [healthcheck.sh]
 1264 root       0:00 [healthcheck.sh]
....
/ # ps aux | grep health | wc -l 
102
```

# My Environment
* Image: **minio:latest**
* OS : Linux node01 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version:  17.09.1-ce, build 19e2cf6

I've checked the health check twice and could not find a real reason of why is this happening. 

I'm not sure, but I guess you should use "CMD set -e &&  /usr/bin/healthcheck.sh".

**Comment by vadmeste** [comment]
@OsamaJBR can you paste the output of `ps -ao pid,state,cmd` ?

**Comment by OsamaJBR** [comment]
There is no cmd option.
But here is pid,stat,args: 
```
/ # ps -ao pid,stat,args
PID   STAT COMMAND
    1 S    minio server /export
  103 Z    [healthcheck.sh]
  201 Z    [healthcheck.sh]
  257 Z    [healthcheck.sh]
  285 Z    [healthcheck.sh]
  312 Z    [healthcheck.sh]
  354 Z    [healthcheck.sh]
  446 S    /bin/sh
  462 S    {healthcheck.sh} /bin/sh /usr/bin/healthcheck.sh
  468 S    curl -H User-Agent: Mozilla -s -k -o /dev/null -I -w %{http_code} http://127.0.0.1:9000/minio/index.html
  469 R    ps -ao pid,stat,args
```

**Comment by harshavardhana** [comment]
This looks like `healthcheck.sh` doesn't exit properly.

**Comment by kannappanr** [comment]
@OsamaJBR Can you let us know the docker version that you are using?

**Comment by OsamaJBR** [comment]
Docker version: 17.09.1-ce, build 19e2cf6

**Comment by kannappanr** [comment]
@OsamaJBR Will try to reproduce with the version of docker that you have and get back to you.

**Comment by nitisht** [comment]
@OsamaJBR we implemented a more straightforward approach for `healthcheck` in #5543 
can you please confirm if this fixes the issue for you

**Comment by OsamaJBR** [comment]
Yes, I don't see the problem again using the latest docker tag. Thanks.
