### ISSUE TITLE
Website hosting support

### ISSUE THREAD

**Issue by vmtocloud** [minio/minio#5515]
## Expected Behavior
Allow me to enable bucket to support website hosting. So when I drop index.html into a bucket I can open website from the bucket URL. example http://minio.corp.local/mysite

## Current Behavior
Buckets only support files 

## Possible Solution
https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html

## Steps to Reproduce (for bugs)
N/A

## Context
Unable to use true S3 compatible service.

**Comment by harshavardhana** [comment]
We have debated in the past but we decided not to do it @vmtocloud  there are alternative ways to do it

- https://gist.github.com/harshavardhana/f05b60fe6f96803743f38bea4b565bbf (using nginx and setting bucket policies to download)
- https://github.com/harshavardhana/s3www (a custom HTTP server based on net/http)

**Comment by kannappanr** [comment]
@vmtocloud We talked about it again and decided that nginx is adequate for this purpose.
