### ISSUE TITLE
Server returns `BucketAlreadyOwnedByYou`

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5533]
* Start `minio` like `minio server http://node1/disk{1...4} http://node2/disk{1...4} http://node3/disk{1...4}`
* After successful some make buckets, stop `minio` in node3, then replace all disks of `node3`
* Bring up `node3`, now `unformatted disk found (unformatted disk found)` error message is shown `node1` and `node3` console.
* Now create non-existent bucket like `mc mb minio/testbucket3` which shows a trace like below
```
$ date; mc --debug mb test/mybucket3; date
Thu Feb 15 15:44:39 IST 2018
mc: <DEBUG> PUT /mybucket3/ HTTP/1.1
Host: node1:9000
User-Agent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-15T07:35:19Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20180215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180215T101439Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 15 Feb 2018 10:24:40 GMT
Retry-After: 120
Server: Minio/DEVELOPMENT.2018-02-15T07-05-04Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 151378C37DE5C3D6

10b
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioWriteQuorum</Code><Message>Multiple disks failures, unable to write data.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket3/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  10m0.620226469s

mc: <DEBUG> PUT /mybucket3/ HTTP/1.1
Host: node1:9000
User-Agent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-15T07:35:19Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20180215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180215T102440Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Thu, 15 Feb 2018 10:24:40 GMT
Server: Minio/DEVELOPMENT.2018-02-15T07-05-04Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 151378C37FE77F43

135
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket3/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  21.82074ms

mc: <ERROR> Unable to make bucket `test/mybucket3`. Your previous request to create the named bucket succeeded and you already own it.
 (1) mb-main.go:131 cmd.mainMakeBucket(..) Tags: [test/mybucket3]
 (0) client-s3.go:768 cmd.(*s3Client).MakeBucket(..)
 Release-Tag:DEVELOPMENT.2018-02-15T07-35-19Z | Commit:335a53ad2911 | Host:bala-ThinkPad-X1-Carbon-4th | OS:linux | Arch:amd64 | Lang:go1.9.4 | Mem:3.1MB/6.6MB | Heap:3.1MB/4.8MB
Thu Feb 15 15:54:40 IST 2018
```

All the requests are sent to `node1`

**Comment by harshavardhana** [comment]
Currently the server code returns error based on the fact that we have enough buckets which are present on all other disks, so i am not sure if you are expecting some other error here? @balamurugana - are you expecting we return quorum error?

**Comment by harshavardhana** [comment]
@abperiasamy suggested that we use quorum across all disks here since buckets exist on all disks, if the quorum confirms that it exists on all disks then we simply return one error instead not the first error.

**Comment by balamurugana** [comment]
@harshavardhana I do not understand your comment.  when `MakeBucket()` is called, it returns `XMinioWriteQuorum` for `503 Service Unavailable`.  Because of this error, if the call is tried again, it returns `BucketAlreadyOwnedByYou` for `409 Conflict`.

In a technical sense, since the bucket is created in quorum number of sets,  why we need to return an error and show another error for the next call.  Note that any other call (put/get object) to the bucket works fine after `XMinioWriteQuorum` error.

**Comment by harshavardhana** [comment]
> @harshavardhana I do not understand your comment. when MakeBucket() is called, it returns XMinioWriteQuorum for 503 Service Unavailable. Because of this error, if the call is tried again, it returns BucketAlreadyOwnedByYou for 409 Conflict.
> 
> In a technical sense, since the bucket is created in quorum number of sets, why we need to return an error and show another error for the next call. Note that any other call (put/get object) to the bucket works fine after XMinioWriteQuorum error.

This is the bug i fixed in the pr #5560, the problem was previously the code returned based on first available error so it be sporadically either 409 or 500.

**Comment by deekoder** [comment]
Can we close this then?

**Comment by harshavardhana** [comment]
> Can we close this then?

Yeah, I think we can, there is no consensus on how to fix this. Perhaps re-open when we have the bandwidth to address this.
