### ISSUE TITLE
Windows server 2008 R2 / Docker Toolbox : minio server fails to start "Initializing object layer failed cause=disk path full"

### ISSUE THREAD

**Issue by zamrih** [minio/minio#5545]
minio container fails to start when using [Docker Toolbox](https://download.docker.com/win/stable/DockerToolbox.exe) ( Docker for Windows not being available ) installed on a [Windows Server 2008 R2 Standard Edition](https://www.microsoft.com/en-us/download/details.aspx?id=2227) machine.
Docker toolbox uses virtualbox as a docker machine driver tather than Hyper-V ( not available on this windows server edition ).

## Expected Behavior
minio container should be able to pickup the available disk space/inodes when using a shared virtualbox as a mounted volume ( -v /shared_folder/minio/data/:/data )
On a side note, It should do the same with a "tmpfs" mounted partition ( -v /tmpfs_partition/minio/data:/data ).

## Current Behavior
minio fails to start with an error message :

> [ERROR] Initializing object layer failed (disk path full)

## Possible Solution
minio does however start when firing the container in the same environment with a volume mounted on an available ext4 partition.

## Steps to Reproduce (for bugs)

1. A fresh install of  [Windows Server 2008 R2 Standard Edition](https://www.microsoft.com/en-us/download/details.aspx?id=2227) as a virtual machine ( kvm, vmware, ... anything supporting nested virtualization ).
2. A fresh install of [Docker Toolbox](https://download.docker.com/win/stable/DockerToolbox.exe) 
3. Add a windows folder as a shared virtualbox folder from the new "default" vm ( docker virtual machine ) on the virtualbox gui. 
4. Start a docker cli from the quick start desktop shortcut, from the Kitematic left bottom shortcut or by connecting through ssh to the docker vm.
5. Fire a minio container on the shared folder : docker run -p 9000:9000 -v /c/shared_folder/minio/data:/data -v /c/shared_folder/minio/config:/root/.minio minio/minio server /data 

## Context
The minio container is part of a web app using S3 compliant file storage.
It's cooked using a docker compose file having two minio containers.
The docker compose file is getting up fine on a native docker install ( linux machine ) but fails to do the same specifically on the two minio containers and the two minio containers alone.
The goal is to make sure to support the web app starting using docker-compose on both native and boot2docker ( windows mainly ) driven docker installs.

## Your Environment
> docker@default:~$ docker run -p 9000:9000 -v /c/opt/host/opt/app/minio/data:/data -v /c/opt/host/opt/app/minio/config:/root/.minio minio/minio server /data
> Created minio configuration file successfully at /root/.minio
> 
> 
> Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:224:cmd.serverMain()
>        2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
>        3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
>        4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
>        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
>        6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
> [2018-02-18T18:42:10.99862071Z] [ERROR] Initializing object layer failed (disk path full)

> docker@default:~$ sudo df -h
> Filesystem                Size      Used Available Use% Mounted on
> tmpfs                   896.3M    421.6M    474.7M  47% /
> tmpfs                   497.9M         0    497.9M   0% /dev/shm
> /dev/sda1                17.9G      1.9G     15.1G  11% /mnt/sda1
> cgroup                  497.9M         0    497.9M   0% /sys/fs/cgroup
> /opt/app                 99.9G     26.3G     73.6G  26% /opt/app
> c/Users                  99.9G     26.3G     73.6G  26% /c/Users
> /dev/sda1                17.9G      1.9G     15.1G  11% /mnt/sda1/var/lib/docker/plugins
> /dev/sda1                17.9G      1.9G     15.1G  11% /mnt/sda1/var/lib/docker/aufs

> docker@default:~$ docker version
> Client:
>  Version:	18.02.0-ce
>  API version:	1.36
>  Go version:	go1.9.3
>  Git commit:	fc4de44
>  Built:	Wed Feb  7 21:12:37 2018
>  OS/Arch:	linux/amd64
>  Experimental:	false
>  Orchestrator:	swarm
> 
> Server:
>  Engine:
>   Version:	18.02.0-ce
>   API version:	1.36 (minimum version 1.12)
>   Go version:	go1.9.3
>   Git commit:	fc4de44
>   Built:	Wed Feb  7 21:20:09 2018
>   OS/Arch:	linux/amd64
>   Experimental:	false

> docker@default:~$ docker image ls
> REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
> minio/mc                      latest              0edbe11b68e4        8 days ago          12.9MB
> minio/minio                   latest              ce3439e5a5b7        8 days ago          28.9MB

> docker@default:~$ docker info
> Containers: 5
>  Running: 0
>  Paused: 0
>  Stopped: 5
> Images: 23
> Server Version: 18.02.0-ce
> Storage Driver: aufs
>  Root Dir: /mnt/sda1/var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 93
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
> runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.4.115-boot2docker
> Operating System: Boot2Docker 18.02.0-ce (TCL 8.2.1); HEAD : 99245f4 - Thu Feb  8 17:43:39 UTC 2018
> OSType: linux
> Architecture: x86_64
> CPUs: 1
> Total Memory: 995.9MiB
> Name: default
> ID: Q56C:TM52:ERBD:6JCO:VHCF:VKZD:FFJ7:ITPL:5D4U:6VJA:SPOL:5NC6
> Docker Root Dir: /mnt/sda1/var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
>  provider=virtualbox
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

This is the output right from the docker vm.
Same error is returned from windows terminal.
The docker machine driver used is virtualbox and the volume used is a shared virtualbox folder.

It may be related to the "vboxsf" filesystem used by the virtualbox shared folder.

As the image starts normally when trying an ext4 partition instead ( see the previous df command )  :

> docker@default:~$ docker run -p 9000:9000 -v /mnt/sda1/tmp/minio/data:/data -v /mnt/sda1/tmp/minio/config:/root/.minio minio/minio server /data
> 
> Drive Capacity: 15 GiB Free, 17 GiB Total
> 
> Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
> AccessKey: ....
> SecretKey: ....
> 
> Browser Access:
>    http://172.17.0.2:9000  http://127.0.0.1:9000
> 
> Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
>    $ mc config host add myminio http://172.17.0.2:9000 .... ....
> 
> Object API (Amazon S3 compatible):
>    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
>    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

tmpfs is also yielding the same error message as with vboxsf :

> docker@default:~$ docker run  -p 9000:9000 -v /minio/data:/data -v /minio/config:/root/.minio minio/minio server /data
> Created minio configuration file successfully at /root/.minio
> 
> 
> Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:224:cmd.serverMain()
>        2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
>        3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
>        4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
>        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
>        6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
> [2018-02-18T18:49:16.671854508Z] [ERROR] Initializing object layer failed (disk path full)
>

**Comment by harshavardhana** [comment]
Thanks @zamrih for opening the issue we will take a look soon.

**Comment by harshavardhana** [comment]
@zamrih would you mind helping us debug this problem further - we do not have the availability of the operating system that you are using - feel free to ping us on slack lets take it from there?

**Comment by zamrih** [comment]
Hi,

Sorry for the late reply...
Sure! Let me know how I can help.
I should still have the underlying environment as a VM.

**Comment by harshavardhana** [comment]
> Hi,
> 
> Sorry for the late reply...
> Sure! Let me know how I can help.
> I should still have the underlying environment as a VM.

@zamrih please reach out on the slack we can do a remote session? at your convenience

**Comment by zamrih** [comment]
I am a bit short on time at the moment but I will certainly do.
See you on slack then.

**Comment by harshavardhana** [comment]
@zamrih going to close this issue for now, feel free to re-open if this issue requires more attention.
