### ISSUE TITLE
xl: Delete & Multi Delete API on a non-empty directory should not remove it and its contents

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5547]
## Expected Behavior
Removing a directory should not have an effect if this latter contains some objects.

## Current Behavior
Removing a directory deletes it and all its contents

## Possible Solution
Change the behavior of delete object in xl.

## Steps to Reproduce (for bugs)
1. `minio server /tmp/xl/backend{1..4}/
2. `mc mb myminio/bucket`
3. `mc cp file myminio/bucket/dir/file`
4. Run the following go code:
```
package main

import (
	"log"
	"github.com/minio/minio-go"
)

func main() {
	s3Client, err := minio.New("127.0.0.1:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatalln(err)
	}
	err = s3Client.RemoveObject("bucket", "dir/")
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Success")
}
```

## Context
Found a bug while doing another thing

## Your Environment
All, latest master

**Comment by harshavardhana** [comment]
fixed by #5548
