### ISSUE TITLE
xl: Putting an empty directory twice should not return 403 Error

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5549]
## Expected Behavior
Putting the same empty directory (empty object with a trailing slash in name) twice is successful

## Current Behavior
Putting the same empty directory the second time returns 403 error code.

## Possible Solution
Do not know yet.

## Steps to Reproduce (for bugs)

1. `$ minio server /tmp/xl/disk-{1..4}`
2. Install aws cli and set Minio server credentials in ~/.aws/credentials
3. `$ aws s3api create-bucket --bucket testbucket --endpoint-url http://localhost:9000`
4.  `$aws s3api put-object --bucket testbucket --key 'emptydir/' --endpoint-url http://localhost:9000`
(successful)
5. `$ aws s3api put-object --bucket testbucket --key 'emptydir/' --endpoint-url http://localhost:9000`
`An error occurred (AccessDenied) when calling the PutObject operation: Access Denied.`

## Context
Fixing a bug.

## Your Environment
All, latest master (1e7e41fada2585ef100f70ffc9773cbb07893158)

**Comment by harshavardhana** [comment]
This is also a good test for mint IMHO @vadmeste
