### ISSUE TITLE
Distributed minio won't start on docker swarm

### ISSUE THREAD

**Issue by tambetliiv** [minio/minio#5557]
## Expected Behavior
When following steps in the docs (https://docs.minio.io/docs/deploy-minio-on-docker-swarm) containers should start on docker swarm hosts.

## Current Behavior
Following steps in the docs (https://docs.minio.io/docs/deploy-minio-on-docker-swarm) containers won't start on any of the nodes.

## Possible Solution

Don't know how to fix.

## Steps to Reproduce (for bugs)

1. Setup docker swarm 3 node cluster. https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/
1.  Follow steps to described in the doc https://docs.minio.io/docs/deploy-minio-on-docker-swarm
1. On 4th instruction when it is time to deploy service to docker swarm nodes. The container won't start on any node and when viewing logs, every failed container has the same error message. Example of one failed container on every node:
```
node0# docker logs f42fb54a70a9

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:100:cmd.serverHandleCmdArgs()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:149:cmd.serverMain()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       7: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-19T13:27:20.868284953Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[http://minio1/export http://minio2/export http://minio3/export http://minio4/export] (no endpoint found for this host)


node1# docker logs c840007f9ba4

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:100:cmd.serverHandleCmdArgs()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:149:cmd.serverMain()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       7: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-20T09:06:51.790782065Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[http://minio1/export http://minio2/export http://minio3/export http://minio4/export] (no endpoint found for this host)

node2# docker logs 909ae4faacc1

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:100:cmd.serverHandleCmdArgs()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:149:cmd.serverMain()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       7: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-19T13:27:06.568956866Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[http://minio1/export http://minio2/export http://minio3/export http://minio4/export] (no endpoint found for this host)

```

## Context
Example config should work out-of-the box or some instructions provided how to fix this problem.

Error message is not informative enough. 

## Your Environment

* Version used (`minio version`): latest docker image (minio/minio:RELEASE.2018-02-09T22-40-05Z)
* Environment name and version (e.g. nginx 1.9.1): `Docker version 17.12.0-ce, build c97c6d6`
* Server type and version: All nodes have the same os
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
```
* Operating System and version (`uname -a`): All have the same version os `Linux node0 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`

**Comment by nitisht** [comment]
Thanks for reporting @tambetliiv let me try to reproduce this and get back to you

**Comment by nitisht** [comment]
@tambetliiv I was able to deploy Minio distributed using the given example documents on a Packet server cluster. 

```
root@minio-swarm-1:~# docker stack ps minio_stack
ID                  NAME                   IMAGE                                      NODE                DESIRED STATE       CURRENT STATE                ERROR               PORTS
0na9k1r3unw8        minio_stack_minio2.1   minio/minio:RELEASE.2018-02-09T22-40-05Z   minio-swarm-1       Running             Running about a minute ago                       
h1uumo9vqjiy        minio_stack_minio1.1   minio/minio:RELEASE.2018-02-09T22-40-05Z   minio-swarm-4       Running             Running about a minute ago                       
yycs8ti0qqun        minio_stack_minio4.1   minio/minio:RELEASE.2018-02-09T22-40-05Z   minio-swarm-1       Running             Running about a minute ago                       
jxpdqp82lk1r        minio_stack_minio3.1   minio/minio:RELEASE.2018-02-09T22-40-05Z   minio-swarm-3       Running             Running about a minute ago  
```

Can you pls confirm if your Swarm cluster is deployed properly and nodes are able to talk to each other..

**Comment by tambetliiv** [comment]
not sure how to check any other way 
```
node0# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
tcgncgywb0no114mz01mf4orh *   node0    Ready               Active              Leader
056bjbgpie9dhmfp6he9v1c58     node1    Ready               Active
a6pd9tbttj3gw9gdwvjedg7xi     node2    Ready               Active

```

Just in case uninstalled docker engine from all nodes, purged installation (removed /var/lib/docker dir) and initiated swarm again. All other services that i tried, are running ok, only minio deployment fails.

Got any other ideas on how to debug this weird situation?

**Comment by nitisht** [comment]
@tambetliiv is it possible to allow remote access to your deployment?

**Comment by nitisht** [comment]
Based on a quick remote sharing session, looks like Minio server thinks of all the four endpoints passed as remote endpoints -- causing the failure during startup with the error `(no endpoint found for this host)`.

**Comment by nitisht** [comment]
@tambetliiv , I discussed with @harshavardhana , this generally happens generally when

- swarm has not updated the DNS correctly
- not assigned the IPs correctly

Can you confirm if the IP of each container reported by Swarm is same as the IP visible from inside the container. Also, the hosts `minio1` .. `minio4` are resolvable to correct IPs (same as the ones reported by Swarm)

**Comment by tambetliiv** [comment]
I set up a new docker swarm (installed new VMs) and used the same versions. Couldn't reproduce this issue. I don't know what was wrong with the old docker-swarm cluster but for me now issue is resolved.

Thanks again for quick response and all your help.

**Comment by tambetliiv** [comment]
I installed all the docker hosts in the same environment and reproduced the issue. This means that this environment is somehow incompatible.

resolv.conf file is populated automatically and found out issue what was causing this behavior. 

minio didn't run on docker swarm hosts that had this example resolv.conf:
```
# cat /etc/resolv.conf
search xxxxx.xxx xxxxx.xxx xxxxx.xxx
nameserver xxx.xxx.xxx.xxx
nameserver xxx.xxx.xxx.xxx
```

When removed search option, minio starts normally.
```
# cat /etc/resolv.conf
nameserver xxx.xxx.xxx.xxx
nameserver xxx.xxx.xxx.xxx
```

Hope this info helps someone wrestling with the same problem.

**Comment by harshavardhana** [comment]
Thanks @tambetliiv

**Comment by glensc** [comment]
knowing your infra @tambetliiv, i think the problem is that your `search` added wildcard resolution.

```
*.domain.tld A 1.2.3.4
```

thus `nslookup foobar` always resulted `A 1.2.3.4` reply while without `search` it would returned `NXENT`

**Comment by tambetliiv** [comment]
https://github.com/minio/minio/issues/5557#issuecomment-371065465

Yes, that was the problem. Was able to reproduce. One of those `search` domains supported wildcard resolution. And when docker creates container `resolv.conf`, It appends `options ndots:0`, which tries to resolv all names with `search` domains, and when one of those domains supports wildcard resolution, then name resolution to container won't work.

Non working container `resolv.conf` example:
```
# cat /var/lib/docker/containers/08b7e616db220bc18d77cc6787b5940b6b0a4779db1bfdcb3d3d9c1f1d51f0a2/resolv.conf
search xxxx.xx xxxx.xx xxxx.xx #last one supports wildcard resolution
nameserver 127.0.0.11
options ndots:0
```

Working container `resolv.conf` example:
```
# cat /var/lib/docker/containers/08b7e616db220bc18d77cc6787b5940b6b0a4779db1bfdcb3d3d9c1f1d51f0a2/resolv.conf
search xxxx.xx xxxx.xx #wildcard resolution removed
nameserver 127.0.0.11
options ndots:0
```
