### ISSUE TITLE
Document the process about how to upgrade to a new go version

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5566]
It is not so easy to know how to support a new go runtime version (we need to remember docker image and probably other stuffs), we need to document it in MAINTAINERS.md probably.

**Comment by harshavardhana** [comment]
> It is not so easy to know how to support a new go runtime version (we need to remember docker image and probably other stuffs), we need to document it in MAINTAINERS.md probably.

Why do we need to do this? i don't see we need to document this.

**Comment by deekoder** [comment]
We have a doc on "how to install go". This is very useful. Can we add a section to how to upgrade go. I think you have to write it generic so that we don't have to keep updating version numbers.

**Comment by vadmeste** [comment]
@deekoder I meant how to upgrade go runtime version in Minio server. It doesn't seem there is any performance enhancement in go 1.10 but it is still good to do.

@harshavardhana, because upgrading go version is prone to errors.. like we can forget to increase go version in Dockerfile. I wrote a PR to migrate to 1.10 but then I decided to not sending it I am not sure what I could be missing.
