### ISSUE TITLE
Question: Empty Etag is returned 

### ISSUE THREAD

**Issue by Alexander198961** [minio/minio#5567]
I got Etag is empty not sure how the best way to debug issue:
I  have started server like this:
./minio server some_dir
and I got this output
++ aws --endpoint=http://127.0.0.1:9000 s3api list-objects --bucket bucket
{
    "Contents": [
        {
            "LastModified": "2018-02-20T16:13:14.158Z", 
            "ETag": "", 
            "StorageClass": "STANDARD", 
            "Key": "ProxyKeyStore", 
            "Owner": {
                "DisplayName": "", 
                "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
            }, 
            "Size": 2140
        }
    ]
}
Can you please advice how can I debug why I got empty Etag ? so this is question 
Can be something wrong with aws client  or this is minio issue ?

**Comment by Alexander198961** [comment]
./mc ls --json s3/bucket/ProxyKeyStore
{"status":"success","type":"file","lastModified":"2018-02-20T16:13:14.158Z","size":2140,"key":"ProxyKeyStore","etag":""}

**Comment by Alexander198961** [comment]
So which file should I check  why I couldt get  Etag  ?

**Comment by vadmeste** [comment]
@Alexander198961, this is expected if you are running Minio FS on some existing data. ETag is returned only for objects that you already uploaded using an S3 client.

**Comment by harshavardhana** [comment]
If you re-upload the same object through our API we would calculate ETag. For existing content we can't calculate ETag.

**Comment by nitisht** [comment]
Closing this as answered @Alexander198961 . Feel free to reopen if there are further issues
