### ISSUE TITLE
Extend API to store objects externally, e.g. tape

### ISSUE THREAD

**Issue by mbo77** [minio/minio#5582]
I am interested if it's possible to extend the functionality, so that objects can be moved to even cheaper storage solutions like tape.

We have a software solution which handles tape media, refreshing the data and migrating to newer tape technology for data which needs to be stored for long term, 10 years and above. We'd like to integrate that with the minio S3 server.

To integrate such a feature, there are different possible approaches:

- Include support for named pipes
Replace the actual object with a named pipe, after data has been moved to a lower tier. Include triggers to indicate that an object has been completely stored (so that it gets stored externally) and trigger read events, so that the object can be streamed back to the primary tier by feeding into the pipe from the external solution.

- Implement on API level
Provide functions to store/retrieve data to an external provider and handle the object virtually in the primary tier.

Both solutions can be made configurable per bucket.

This is just a very rough description, but I hope to have made my idea clear.

**Comment by harshavardhana** [comment]
Thanks @mbo77 for sharing the requirements

**Comment by deekoder** [comment]
@mbo77 this is an ask for HSM (hierarchical storage management). At this time, we don't have plans to do this inside our object storage server implementation. Can you give details on why exactly you want this feature. Perhaps we can discuss possibilities on how you can achieve this outside of the core object storage server code.

**Comment by kannappanr** [comment]
Closing this issue as this has been stale for a while now. Can re-open the issue if there is more information and once we have more bandwidth to fix this feature request.
