### ISSUE TITLE
Credentials displayed in container log when starting up

### ISSUE THREAD

**Issue by chris-vest** [minio/minio#5585]
## Expected Behavior
No credentials displayed in log upon startup

## Current Behavior
Credentials displayed in log upon startup:
```
27/02/2018 17:50:32Endpoint:  http://10.42.142.10:9000  http://127.0.0.1:9000
27/02/2018 17:50:32AccessKey: $myAccessKey
27/02/2018 17:50:32SecretKey: $mySecretKey
```

## Possible Solution
Include a flag in config not to display credentials; or simply hide them altogether.

## Context
Ideally don't want our access and secret keys anywhere in plaintext!

## Your Environment
Rancher 1.6
Minio container: minio/minio:latest
Host is running RHEL

**Comment by harshavardhana** [comment]
just use `--quiet` on command line @chris-vest to disable creds on console

**Comment by kannappanr** [comment]
Closing this as answered. Please feel free to reopen the issue if you feel otherwise.

**Comment by chris-vest** [comment]
Thanks guys.
