### ISSUE TITLE
Cannot initialize distributed nodes with version "2018-02-09T22-40-05Z"

### ISSUE THREAD

**Issue by rCj7t993swwMeDsm** [minio/minio#5589]
Initializing distributed minio with 2 nodes 4 disks from fresh failed.

## Expected Behavior
The initialization shall work as previous version

## Current Behavior
1. fresh setup with following command
`minio server http://host a/disk1 http://host a/disk2 http://host b/disk1 http://host b/disk2`
2. The following error observed after firing up the minio command:
`minio: [2018-02-28T09:18:44.00222728Z] [FATAL] Unable to initialize distributed locking clients (Dsync is not designed for less than 4 nodes)`
3. TCPDUMP was used to observe the network activity and found no network connection was initiated by minio
4. nothing is written in the storage by minio
5. By using the previous version "2018-01-18T20:33:21Z" the above configuration can be started.
6. minio version "2018-02-09T22-40-05Z" could be started successfully with 1 node 4 disks configuration.

## Possible Solution
Might be some libraries are missing or incompatible with OS.

## Steps to Reproduce (for bugs)
1. Setup two virtual machines with disabled firewall and selinux (CentOS 7)
2. create two directories "/disk1" and "/disk2"
3. start the minio command

## Your Environment
CentOS Linux release 7.4.1708 (Core)
No docker, no swarm, just the minio x86 binary.

**Comment by harshavardhana** [comment]
This is currently fixed in master branch 8de6cf41243ae5a53cf16ec43e49d45fdc0a7ea2  we will make a release soon. 

```
commit 8de6cf41243ae5a53cf16ec43e49d45fdc0a7ea2
Author: Harshavardhana <harsha@minio.io>
Date:   Mon Feb 12 01:46:12 2018 -0800

    update dsync implementation to fix a regression (#5513)
    
    Currently minio master requires 4 servers, we
    have decided to run on a minimum of 2 servers
    instead - fixes a regression from previous
    releases where 3 server setups were supported.
```
