### ISSUE TITLE
user-defined metadata key issue

### ISSUE THREAD

**Issue by ChrisWrightMaglabs** [minio/minio#5594]
I'm setting some custom expiry meta data with the key "companyname-expiry" but when I head the object it comes back as "Companyname-Expiry".

## Expected Behavior
Metadata should return all lower case.

From https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata
> User-defined metadata is a set of key-value pairs. **Amazon S3 stores user-defined metadata keys in lowercase**. Each key-value pair must conform to US-ASCII when you are using REST and to UTF-8 when you are using SOAP or browser-based uploads via POST.

## Current Behavior
Metadata keys have uppercase characters.

## Environment
Version: 2018-02-09T22:40:05Z  (docker latest)
Platform: Host: 9ae0dace61f0 | OS: linux | Arch: amd64

**Comment by ebozduman** [comment]
There was a slack message exchange between @ChrisWrightMaglabs and @harshavardhana and it looks like this is not a Minio bug, (if it is a bug).
Basic idea/response was as follows:
```
Http headers are supposed to be case-insensitive, so it should NOT matter for an http
client in which case, upper-case, lower-case or camel-case, user metadata is returned
by the server. 
In other words, if an http client complies with http RFC, then it would NOT be
case-sensitive and would treat lower and upper case field names the same way. 
Since Minio does not control how http header field names are canonicalized, if you
have a client case sensitive about http header field names, then that client is buggy
and it should be fixed on that client's implementation.
```

Reference:
```
The server could emit everything lower case if it wanted to. Clients or servers
that insist on a particular case are in violation of the RFC.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

    Field names are case-insensitive.
```

@ChrisWrightMaglabs : we recommend this issue to be closed with `"working as intended"` label.

**Comment by krishnasrinivas** [comment]
If this is causing an issue with AWS SDK then we should discuss if we should be compatible with AWS SDK (though http rfc does not warrant for us to do so)

**Comment by harshavardhana** [comment]
> If this is causing an issue with AWS SDK then we should discuss if we should be compatible with AWS SDK (though http rfc does not warrant for us to do so)

I don't think so @krishnasrinivas - aws-sdk-go canonicalizes the key, aws-sdk-php doesn't so there is inconsistency even in languages. The problem is perhaps @ChrisWrightMaglabs is simply expecting the headers to be lower case because it was set that way.  I am pretty sure PHP http clients will not fail if keys are canonicalized.

**Comment by ChrisWrightMaglabs** [comment]
Working via the AWS PHP SDK setting the keys in any mix of casing results in an all lowercase result, which I presume is due to Amazon forcing all lowercase in storage and preserving that through to the HTTP headers.

Minio behaviour being different is a minor irritation, was simply of note because it is different and some S3 interaction code that depended on the consistent behaviour out of AWS tripped over when pointed at Minio.

**Comment by harshavardhana** [comment]
> Working via the AWS PHP SDK setting the keys in any mix of casing results in an all lowercase result, which I presume is due to Amazon forcing all lowercase in storage and preserving that through to the HTTP headers.

If you used aws-sdk-go, aws-sdk-java you would see all headers to be canonicalized (camel cased) this is just a http implementation choice, it shouldn't change what these values mean or how they are treated by S3 clients. 

> Minio behaviour being different is a minor irritation, was simply of note because it is different and some S3 interaction code that depended on the consistent behaviour out of AWS tripped over when pointed at Minio.

Any client which depends on this behavior is going to be buggy and not compliant with HTTP RFC,  AWS S3 is a HTTP compliant server implementation which sends in whatever casing it sees fit in accordance with RFC,  HTTP RFC puts the onus on the client to be case insensitive.

**Comment by ebozduman** [comment]
@ChrisWrightMaglabs,
We would like to close this issue if you are OK with it.
Please let us know.

**Comment by ChrisWrightMaglabs** [comment]
I agree that this is basically a AWS SDK consistency issue, both in code and their documentation, makes sense to close this off.
