### ISSUE TITLE
SSL on Synology (via Docker App)

### ISSUE THREAD

**Issue by pharaohman** [minio/minio#5608]
I've got Minio running successfully on my Synology Rackstation via a container in the Docker App, but I can't figure out how to get it to use the SSL cert that is also installed on the Synology (full cert, not the self-assigned one). I'd prefer to use the SSL already installed on the Synology but if I have to get a new one, I'm okay with that too. Any help would be appreciated!

**Comment by kannappanr** [comment]
@pharaohman please take a look at https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls about instructions on how to add certs

**Comment by pharaohman** [comment]
@kannappanr Thanks, that gives me a start however the Synology certs are in .pem format and I'm not sure where the .minio folder is located within the Docker app. I see a .minio.sys folder, would that be the same thing? Can I just rename the .pem files with .crt and .key and copy them to that folder?

**Comment by harshavardhana** [comment]
> @kannappanr Thanks, that gives me a start however the Synology certs are in .pem format and I'm not sure where the .minio folder is located within the Docker app. I see a .minio.sys folder, would that be the same thing? Can I just rename the .pem files with .crt and .key and copy them to that folder?

`.minio` folder defaults to `${HOME}/.minio`

**Comment by pharaohman** [comment]
I saw that but unless I am completely lost that isn't necessarily the case when installed via the Docker app on a Synology NAS. Or, I'm not clear on how to get there.

**Comment by harshavardhana** [comment]
> I saw that but unless I am completely lost that isn't necessarily the case when installed via the Docker app on a Synology NAS. Or, I'm not clear on how to get there.

It is simply `/root/.minio` for a docker container. You can also override by specifying a custom directory `--config-dir /mydir/`

**Comment by pharaohman** [comment]
That doesn't seem to be the case with the Docker app installed in the Synology Diskstation Manager. There is no such directory. I've got a .minio.sys folder with folders for buckets, multipart and tmp with a format.json file. There is also a folder in @docker/containers/<hexidecimal idendifier> with checkpoints and shm folders as well as files called config.v2.json, hostconfig.json hostname, hosts, log.db and resolv.conf.

**Comment by harshavardhana** [comment]
Since I do not have access to Synology and have never used it - I don't have a way to debug your issue. Is there anything you can do to help us get access?

**Comment by pharaohman** [comment]
I'd be happy to setup a screen sharing session if you're open to that.

**Comment by harshavardhana** [comment]
> I'd be happy to setup a screen sharing session if you're open to that.

Let us know when do you want to do this?

**Comment by pharaohman** [comment]
I'm pretty available tomorrow. Can you email me and we can set something up?

**Comment by harshavardhana** [comment]
> I'm pretty available tomorrow. Can you email me and we can set something up?

Can this be closed @pharaohman?

**Comment by pharaohman** [comment]
Let me post the resolution first for others who may come across this. I should be able to do it this afternoon. 

	
Ryan O'Hara
IT Consultant, Sphinx Technology Solutions
p:(313) 482-9930 | m:(313) 920-4622 | e:ryanohara@sphinx.technology | w:http://sphinx.technology

**Comment by pharaohman** [comment]
After working with @harshavardhana the solution was to setup a Mount Path under Volume in the container. Save a copy of your private.key and public.crt into a folder on your Synology and set that folder under File/Folder, set the mount path to /root/.minio/certs. Once that was done HTTPS worked perfectly. Thanks!

**Comment by BrianGilbert** [comment]
Here's how I did it, but you do have to start it from terminal instead of the docker GUI..

Execution command:
```
    docker run -d -p 9000:9000 --name minio1 \
        -e "MINIO_ACCESS_KEY=YOURACCESSKEY" \
        -e "MINIO_SECRET_KEY=YOURSECRETKEY" \
        -v /volume1/docker/minio/data:/data \
        -v /volume1/docker/minio/config:/root/.minio \
        minio/minio server /data
```

Then create a scheduled task (assuming you have let's encrypt certs configured as the default for your Synology), with the following script so that the site will be accesible via https (restart the instance from Docker gui to enable the certs):
```
    cp -f /usr/syno/etc/certificate/_archive/$(cat DEFAULT)/privkey.pem /volume1/docker/minio/config/certs/private.key && cp -f /usr/syno/etc/certificate/_archive/$(cat DEFAULT)/fullchain.pem /volume1/docker/minio/config/certs/public.crt

**Comment by harshavardhana** [comment]
> After working with @harshavardhana the solution was to setup a Mount Path under Volume in the container. Save a copy of your private.key and public.crt into a folder on your Synology and set that folder under File/Folder, set the mount path to /root/.minio/certs. Once that was done HTTPS worked perfectly. Thanks!

@pharaohman would it be possible for you to give us some screenshots of how you did it? or better perhaps would you be interested in submitting a document?

**Comment by BrianGilbert** [comment]
I was able to get it working via the Docker gui by entering the following run command:
```
minio server /data
