### ISSUE TITLE
GPU acceleration for Minio possible?

### ISSUE THREAD

**Issue by gavinmcnair** [minio/minio#5615]
I was wondering if the erasure encoding could be offloaded onto the GPU? I presume any modern GPU would be capable of SSD level parity calculations.

## Context
We currently get 40,50 MB a second off our Minio on hard disks and it makes a noticeable dent on CPU performance (our hardware is a little out of date). I was wondering how serious this dent would become if I was to use an SSD based disk solution. In previous years people have used cards to offload this type of work (both raid and SSL). I was wondering if a modern general purpose GPU which is relatively inexpensive could be used to offload erasure encoding calculations.

## Task

Feature Enhancement (possibility)

**Comment by aead** [comment]
On modern (x86) processors (with SSE4 / AVX / AVX2) the erasure coding (and hashing) is reasonable fast. Here are some resources: 
 - [Cosbench blog-post](https://blog.minio.io/minio-benchmarks-with-cosbench-81704a8f0178?gi=c7517d2cec7a)
 - [HighwayHash](https://github.com/minio/highwayhash)
 -  [Reed-Solomon erasure coding](https://github.com/klauspost/reedsolomon)

While it may be possible to offload erasure-coding to the GPU in general it is not trivial to do so since we have to explore how to support various GPUs using Go and assembly. Further it is not clear whether this provides a significant advantage. On modern processors the (SSD) disks are usually the bottleneck (AFAIK).

Also cc-ing @fwessels

**Comment by gavinmcnair** [comment]
I am currently archiving Kafka topics using Kafka connect S3 directly to our Minio cluster.

It is writing around 20gb per hour across 16 minio hosts (each 16 core machines).

All 16 machines are consuming 66% of a single CPU core with no wait on IO.

The processors are Opteron's from about 4 years ago (which I accept isn't the latest) and has the following CPU feature flags

flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 popcnt hypervisor lahf_lm svm abm sse4a

In addition the logs I am writing seem to be lagging realtime by an hour (which is a worry). GPU acceleration will also not help me in this case (since these machines are probably not ideal for GPU's) but i gave it as a suggestion of a possibility for massive scalability when writing out high volume data streams in realtime.

**Comment by gavinmcnair** [comment]
Let me check there are no network IO issues.

**Comment by aead** [comment]
>It is writing around 20gb per hour across 16 minio hosts (each 16 core machines).

This would be 5-6 MB/s across 16 instances. That should not cause performance problems.
Are you using the latest release of the server?

 >All 16 machines are consuming 66% of a single CPU core with no wait on IO.

Does this mean 66% on a *single* CPU core on each node or 66 % on *every* CPU  core on each node?

The Opteron's are old but they support SSE-4 so they should be able to use SIMD optimized code.
You can try the following simple test:
 1. `go get github.com/klauspost/reedsolomon`
 2. `go test -bench $GOPATH/src/github.com/klauspost/reedsolomon`

>GPU acceleration will also not help me in this case (since these machines are probably not ideal for GPU's) but i gave it as a suggestion of a possibility for massive scalability when writing out high volume data streams in realtime.

I will report this also internally. From our experience on reasonable modern CPUs / machines there are hardly data disks/networks available/used where the CPU work-load is a bottleneck. Will cycle back to you about this.

**Comment by fwessels** [comment]
If you are using the latest Minio release you should benefit from Highwayhash which is 10x faster than Blake2b which we have been using this far for hashing.

**Comment by gavinmcnair** [comment]
Thanks, i'll give it a try.

**Comment by aead** [comment]
Closing the issue as resolved. Please feel free to reopen the issue, if that is not the case.
