### ISSUE TITLE
FS: CopyObject where source and destination are the same fails to preserve ETag

### ISSUE THREAD

**Issue by wd256** [minio/minio#5622]
## Expected Behavior
When copying an object for the purpose of updating its metadata, I expect the ETag to be preserved.

## Current Behavior
The copy operation completes successfully but the ETag is now missing from the object's metadata.

## Your Environment
Version: RELEASE.2018-02-09T22-40-05Z
Platform: Linux amd64

**Comment by harshavardhana** [comment]
Can you test this with master branch and let us know?

**Comment by wd256** [comment]
I've tested with master and can confirm I see the same behaviour.
