### ISSUE TITLE
SSE-C does not validate equal keys during key rotation

### ISSUE THREAD

**Issue by aead** [minio/minio#5625]
This is a SSE-C API compliance bug. It has no security impact.

## Expected Behavior
If the client does a key-rotation where source-key == destination-key the server should check that the source-key is valid. The server should error out if the source-key is not valid.

## Current Behavior
The server accepts invalid source-keys. Since key-rotation with equal keys is implemented as a no-op this has no security impact.

## Possible Solution
Check source-key.

## Steps to Reproduce (for bugs)
1. Setup a minio server with TLS.
2. Create an object using SSE-C and the key: `key1`
3. Execute a `s3Client.CopyObject(dst, src)` where src==dst but the encryption keys does match `key1`
4. Server returns `200 OK` but AWS returns `400 BadRequest: "The provided encryption parameters did not match the ones used originally."`

Notice: This is a new error.
## Context
Encryption, SSE-C

## Your Environment
master

**Comment by harshavardhana** [comment]
> The server accepts invalid source-keys. Since key-rotation with equal keys is implemented as a no-op this has no security impact.

:+1:
