### ISSUE TITLE
Distributed Cluster setup failed

### ISSUE THREAD

**Issue by xofaptech** [minio/minio#5627]
Hi,

I'm currently trying to setup a distributed cluster of minio before using it at production. I have created 4 nodes of minio using xen hypervisor and ubuntu 16.04. They are working well as standalone nodes. Then as an attempt to make a distribution cluster, I run the following command on every nodes : 

 minio server http://192.168.1.221:9000/minio/demo01 http://192.168.1.222:9000/minio/demo02 http://192.168.1.223:9000/minio/demo03 http://192.168.1.224:9000/minio/demo04 

And I got this error message : 

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:224:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-03-09T06:05:51.287931096Z] [ERROR] Initializing object layer failed (
[01/04] /minio/demo01 : unformatted disk found
[02/04] http://192.168.1.222:9000/minio/demo02 : unexpected HTTP response: 200 OK
[03/04] http://192.168.1.223:9000/minio/demo03 : unexpected HTTP response: 200 OK
[04/04] http://192.168.1.224:9000/minio/demo04 : unexpected HTTP response: 200 OK)

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:226:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-03-09T06:05:51.293115494Z] [ERROR] Unable to shutdown http server (server not initialized)

I wonder where is the problem, since each nodes are working fine as standalone.

**Comment by nitisht** [comment]
@xofaptech do you have an existing directory like `lost+found` in your mounts `/minio/demo01`, `/minio/demo02`, `/minio/demo03`, `/minio/demo04`

**Comment by xofaptech** [comment]
no, all of the buckets are empty

**Comment by harshavardhana** [comment]
You cannot use /minio as part of the path IMO, can you change it to something else ? /minio is a reserved prefix..

**Comment by xofaptech** [comment]
the url is defaulted to minio. how can I change it?

**Comment by harshavardhana** [comment]
> the url is defaulted to minio. how can I change it?

it is not you can change it to your actual export directory lets say your directory is /export/data then your command will look like 

```
minio server http://192.168.1.221:9000/export/data http://192.168.1.222:9000/export/data http://192.168.1.223:9000/export/data http://192.168.1.224:9000/export/data
```

there is no `/minio` required.

**Comment by xofaptech** [comment]
Tried, but I got this error instead

[2018-03-09T08:52:21.117047824Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[http://192.168.1.221:9000/data/demo01] (use path style endpoint for FS setup)

**Comment by nitisht** [comment]
> Tried, but I got this error instead
[2018-03-09T08:52:21.117047824Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[http://192.168.1.221:9000/data/demo01] (use path style endpoint for FS setup)

What is the command used @xofaptech ? Looks like whole command wasn't run?

```
minio server http://192.168.1.221:9000/export/data http://192.168.1.222:9000/export/data http://192.168.1.223:9000/export/data http://192.168.1.224:9000/export/data
```

**Comment by xofaptech** [comment]
I was using 
minio server http://192.168.1.221:9000/data/demo01 http://192.168.1.222:9000/data/demo02 http://192.168.1.223:9000/data/demo03 http://192.168.1.224:9000/data/demo04

after another trial, I got : 
[2018-03-09T09:13:38.249941833Z] [ERROR] Initializing object layer failed (
[01/04] /data/demo01 : unformatted disk found
[02/04] http://192.168.1.222:9000/data/demo02 : unexpected HTTP response: 200 OK
[03/04] http://192.168.1.223:9000/data/demo03 : unexpected HTTP response: 200 OK
[04/04] http://192.168.1.224:9000/data/demo04 : unexpected HTTP response: 200 OK)

**Comment by xofaptech** [comment]
FYI, I'm using this documentation as a guide to setup the minio nodes : 
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04

**Comment by nitisht** [comment]
Will it be possible to provide access to your setup @xofaptech

**Comment by xofaptech** [comment]
unfortunately, it's not possible to access the setup from public network.

**Comment by harshavardhana** [comment]
> [02/04] http://192.168.1.222:9000/data/demo02 : unexpected HTTP response: 200 OK
> [03/04] http://192.168.1.223:9000/data/demo03 : unexpected HTTP response: 200 OK
> [04/04] http://192.168.1.224:9000/data/demo04 : unexpected HTTP response: 200 OK)

The unexpected response can only come if you already have something running on port 9000, we are able to run perfectly fine on our local systems both master and released versions.

**Comment by xofaptech** [comment]
Hi all,

Thanks for the pointers. I think I found the source of the error message. looks like the minio service of all nodes must not run at the time the command input. Once I stop the minio service of all nodes, the initialization started on the command input.

**Comment by harshavardhana** [comment]
> Hi all,
> 
> Thanks for the pointers. I think I found the source of the error message. looks like the minio service of all nodes must not run at the time the command input. Once I stop the minio service of all nodes, the initialization started on the command input.

You don't need to start minio servers prior - command line input is the only thing necessary which should be run on all servers. Feel free to close this issue if you think this issue is fixed.
