### ISSUE TITLE
Default docker image needs to include time sync

### ISSUE THREAD

**Issue by koliyo** [minio/minio#5631]
I am running the default minio docker image in a local test environment. It has stopped working due to 

```
The difference between the request time and the server's time is too large
```

Restarting the container does not help.

## Expected Behavior
The provided docker image should contain time sync since the service functionality depends on it.

## Current Behavior
I can not use the default docker image, even for testing.

My local host machine, Mac, is synced against a time server. And the current time here is `Sat Mar 10 14:51:51 CET 2018`. Inside the minio container it says `Sat Mar 10 14:06:59 UTC 2018`

## Possible Solution
Include ntp time sync in the default docker image.

## Steps to Reproduce (for bugs)
Not really sure, it worked at first. But today I'm getting the `The difference between the request time and the server's time is too large` error messages. 

## Context
I can not use the default docker image, even for testing.

## Your Environment

* Version used (`minio version`): 2018-02-09T22:40:05Z
* Environment name and version (e.g. nginx 1.9.1): Docker for mac
* Server type and version: macOS
* Operating System and version (`uname -a`): Darwin elMaco 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
* Link to your project: -

**Comment by koliyo** [comment]
Ok, this may actually be a docker for Mac issue. I found this

https://blog.shameerc.com/2017/03/quick-tip-fixing-time-drift-issue-on-docker-for-mac

And running this command
```
docker run --rm --privileged alpine hwclock -s
```

does sync the time of the docker environment for me.

**Comment by harshavardhana** [comment]
This issue doesn't occur on Linux or Windows due to the native implementation of docker. Docker for Mac uses virtualbox VMs which is perhaps the reason why this issue occurs.

We will check how we can fix this issue.

**Comment by kannappanr** [comment]
@koliyo Looks like this is a known issue on Mac based on [https://blog.shameerc.com/2017/03/quick-tip-fixing-time-drift-issue-on-docker-for-mac](https://blog.shameerc.com/2017/03/quick-tip-fixing-time-drift-issue-on-docker-for-mac) . Can this be closed, as this is not a minio issue?

**Comment by harshavardhana** [comment]
In-fact Docker fixed this in https://github.com/docker/for-mac/issues/17 **17.05.0-ce-mac9**

**Comment by deekoder** [comment]
Please reopen if needed. Closing this.
