### ISSUE TITLE
SSL - Invalid SSL certificate file

### ISSUE THREAD

**Issue by JLiscom** [minio/minio#5632]
Whitespace characters after last pem in the cert chain will cause Minio to not start and display
```
[<Some time> ] [FATAL] Invalid SSL certificate file (Could not read PEM block from file <some path>)
```
## Expected Behavior
Minio should ignore whatespaces anywhere in a `public.crt` chain

## Current Behavior
Freaks out if you accidentally have whitespaces at the end of the file. Most editors insert some.

## Possible Solution

Remove whitespaces before parsing.

## Steps to Reproduce (for bugs)
1. put a couple of newlines at the end of a `public.crt` file

## Your Environment
* Version used (`minio version`):
```
Version: 2018-02-09T22:40:05Z
Release-Tag: RELEASE.2018-02-09T22-40-05Z
Commit-ID: 289457568c2c812604484ae9b4efeca0f33aac2c

```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:  Minio provided docker container
* Operating System and version (`uname -a`): `Linux 2627148c1bd0 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 Linux`
* Link to your project: https://github.com/FoxUSA/OpenNote-Docker

**Comment by aead** [comment]
@krishnasrinivas I guess we can remove trailing white-spaces/returns/... [here](https://github.com/minio/minio/blob/27258b9c54980dcba26ccf041c316b221f0ad392/cmd/certs.go#L44)
