### ISSUE TITLE
Disk tuning script attempts to change max_hw_sectors_kb (RO)

### ISSUE THREAD

**Issue by easkay** [minio/minio#5633]
## Expected Behavior
The tuning script should run without errors, and tune `max_sectors_kb` successfully.

## Current Behavior
The tuning script instead attempts to tune the read-only file `max_hw_sectors_kb` resulting in either a permissions error, or an I/O error:
```
/sys/block/sda/queue/max_hw_sectors_kb: Permission denied
-bash: echo: write error: Input/output error
```

## Possible Solution
Change `max_sectors_kb` instead of `max_hw_sectors_kb`

## Steps to Reproduce (for bugs)
1. Install CentOS 7 or similar variant of RHEL.
2. Copy the tuning script from https://github.com/minio/minio/blob/master/docs/deployment/kernel-tuning/disk-tuning.sh
3. Make the script executable with `chmod`
4. Execute the script and observe the error

## Context
As part of general minio setup, attempting to ensure best practises are followed by implementing the tuning recommendations.

## Your Environment
* Version used (`minio version`): N/A
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: VMware ESX 6.5, HP DL380 G7
* Operating System and version (`uname -a`): Linux <hostname> 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: N/A

I'd be happy to raise a PR if you wish.

**Comment by kannappanr** [comment]
@easkay Please do submit a PR. We welcome community contribution.
Note that you can't `chmod` proc files. The script would need to be executed as a root user.
On some hardware, it cannot be changed and the failure needs to be ignored.

**Comment by easkay** [comment]
Thanks @kannappanr, I'll have a PR ready for you in about 9 hours or so.

**Comment by harshavardhana** [comment]
Thanks @easkay
