### ISSUE TITLE
Docker example causes files to be saved inside of container instead of mapped volume

### ISSUE THREAD

**Issue by OmgImAlexis** [minio/minio#5635]
## Expected Behavior

Dockerfile should be using `/data` as the examples show.

## Current Behavior

Dockerfiles uses `/export` like the example use to show before https://github.com/minio/minio/commit/69555f1224282031651b8b4397fd5e6e8b17e5ea#commitcomment-28040482.

## Possible Solution

Update Dockerfile's export.

**Comment by harshavardhana** [comment]
Well you can bind mount to any directory to specified path from docker ?. How is it different even if we mention `/export ` and you don't have a persistent volume attached?

**Comment by OmgImAlexis** [comment]
The Dockerfile exposes the `/export` since the examples were changed to show using `/data` the exposed volume should be changed too.
