### ISSUE TITLE
Issue compiling minio on Smartos/Illumos

### ISSUE THREAD

**Issue by FilipFrancis** [minio/minio#5642]
Hi all,

I am trying to compile minio on smartos but i am getting the following error when i run following command:
go get -u github.com/minio/minio
then after i while i get following error:
github.com/minio/minio/cmd
root/go/src/github.com/minio/minio/cmd/fs-v1-helpers.go:270:17: undefined: lock.Open

The go language that i am using is:
go version go1.10 solaris/amd64

Anybody any ideas as i have looked on the internet to found i solution but no luck
REgards
Filip

**Comment by harshavardhana** [comment]
@FilipFrancis we do not support Illumos/Solaris out of the box - neither we test and compile on these platforms. Feel free to send a fix.

**Comment by deekoder** [comment]
@FilipFrancis I will go ahead and close as won't fix as we have not the bandwidth to test it on Illumos/Solaris platforms at this moment.

**Comment by jfqd** [comment]
@deekoder would it be possible to include the fix from @ryumei to build on Illumos?

**Comment by harshavardhana** [comment]
> @deekoder would it be possible to include the fix from @ryumei to build on Illumos?

Please send a PR @jfqd

**Comment by jfqd** [comment]
Thx for the offer, I created the PR: https://github.com/minio/minio/pull/6150
