### ISSUE TITLE
[toolchain]: Update go version to latest stable version 1.10

### ISSUE THREAD

**Issue by aead** [minio/minio#5644]
This is a request for updating our CI, docker files and other configuration files to the latest Go version `1.10`. At the moment we require Go `1.9.4`.
Further some of our config files contain out-dated Go versions like: [snap](https://github.com/minio/minio/blob/52e382b697eab615ca114df431ea741e60bb4879/snap/snapcraft.yaml#L31)

## Context
Tooling
Also related: #5566 

## Your Environment
master

**Comment by harshavardhana** [comment]
already fixed this few days ago here https://github.com/harshavardhana/minio/tree/enable-builds didn't submit it yet.
