### ISSUE TITLE
Distributed minio fails to heal drive after complete data loss of 1 of 4 drives

### ISSUE THREAD

**Issue by martinmoerch** [minio/minio#5659]
We're seeing an issue when trying out a test scenario, simulating failure of 1 of 4 drives in distributed minio, where heal never completes successfully.

## Expected Behavior
Verify parity and integrity of all objects in all buckets and recreate parity as needed.

## Current Behavior
Heal command stalls on "disk-format", exits after ~600 seconds with error: `Heal had an error -  Storage resources are insufficient for the write operation.`

JSON Output: https://pastebin.com/raw/n5zGq1J9

Storage info after mkfs and heal command (`df -h`): https://pastebin.com/raw/hXFLqSj5

## Steps to Reproduce
1. Start 4x minio in distributed setup, 4x drives total. Command: https://pastebin.com/raw/Prm624HB
2. Via web UI, create a single bucket and upload X number of files to it.
3. `kill` instance 3 and when stopped, umount, mkfs.ext4 and mount again.
4. Start minio instance 3 again.
5. Perform heal via instance 1: `mc admin heal mmo1 --json`

## Context
We're testing distributed minio and want to prepare for catastrophic data loss, before it happens :)

## Your Environment
* Versions used
minio:
`Version: 2018-03-12T21:25:28Z
Release-Tag: RELEASE.2018-03-12T21-25-28Z
Commit-ID: 4a4d1d1b82046a2af62381434bcbff1d748db477`
mc:
`Version: 2018-03-14T23:16:27Z
Release-tag: RELEASE.2018-03-14T23-16-27Z
Commit-id: fe82b0381c5ccf004515be3bfd9b6fa733890005`
* Server type and version: VirtualBox 5.2.6 r120293
* Operating System and version (`uname -a`): CentOS Linux release 7.4.1708 (3.10.0-693.17.1.el7.x86_64)

**Comment by harshavardhana** [comment]
> Start 4x minio in distributed setup, 4x drives total. Command: https://pastebin.com/raw/Prm624HB
> Via web UI, create a single bucket and upload X number of files to it.
> kill instance 3 and when stopped, umount, mkfs.ext4 and mount again.
> Start minio instance 3 again.
> Perform heal via instance 1: mc admin heal mmo1 --json

Tried to reproduce this @martinmoerch but can't - tested running both distributed and standalone erasure coded mode. 

```

mc: <DEBUG> POST /minio/admin/v1/heal/?clientToken=71a33647-5660-48f6-a88c-e5026015a5f8 HTTP/1.1
Host: localhost:9001
User-Agent: Minio (linux; amd64) madmin-go/0.0.1 mc/2018-03-14T23:16:27Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20180315/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180315T190902Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/json
Date: Thu, 15 Mar 2018 19:09:02 GMT
Server: Minio/DEVELOPMENT.2018-03-14T22-37-17Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 151C2DA0C5A3148D

mc: <DEBUG> Response Time:  35.512277ms

 ◐  ** waiting for status from server **
    0/0 objects; 0 B in 0s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 0 │   0.0%              │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
mc: <DEBUG> POST /minio/admin/v1/heal/?clientToken=71a33647-5660-48f6-a88c-e5026015a5f8 HTTP/1.1
Host: localhost:9001
User-Agent: Minio (linux; amd64) madmin-go/0.0.1 mc/2018-03-14T23:16:27Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minio/20180315/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180315T190903Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
 ◓  [disk-format]
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 1 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

**Comment by harshavardhana** [comment]
@martinmoerch i take that back, was able to reproduce and send a PR fix as well.

**Comment by martinmoerch** [comment]
@harshavardhana Awesome! Will watch closely. Thank you for your prompt reaction 👍
