### ISSUE TITLE
Run distributed minio as service

### ISSUE THREAD

**Issue by xofaptech** [minio/minio#5663]
I have been able to create a distributed minio installation on 4 nodes using the quick-start guide. But the steps on quick-start guide are using manual input to start the minio. I was able to start a single minio node using https://github.com/minio/minio-service/tree/master/linux-systemd . I would like to know if it's possible to use the same service for distributed nodes, probably by changing some of the configurations.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-service/tree/master/linux-systemd/distributed have you seen this ?

**Comment by xofaptech** [comment]
Ah, I missed that one. Thanks for pointing out.
