### ISSUE TITLE
 Add SQS and SNS as possible bucket notification targets

### ISSUE THREAD

**Issue by jondavidjohn** [minio/minio#5670]
## Expected Behavior

I can configure SQS or SNS as a bucket notification target as listed [here](https://docs.minio.io/docs/minio-bucket-notification-guide)

## Current Behavior

Currently, you cannot integrate bucket events with standard S3 event targets (like SQS and SNS), this would further improve the "drop-in compatible replacement for S3" story of minio.

## Context

While this improvement would likely have benefits in a production deployment of minio, I am personally trying to mirror a production deployment of standard AWS (S3 -> SQS) workflow locally, for both development and integration testing.

Ultimately, I am wanting to use Docker to run both an SQS replacement (https://github.com/vsouza/docker-SQS-local) and an S3 replacement (minio), and allow minio to send bucket notifications to the local SQS replacement.

This looks to be the second request in the past few weeks on Slack

https://minio.slack.com/archives/C3NDUB8UA/p1520513017000096

**Comment by nitisht** [comment]
@jondavidjohn does this solve your use case - https://docs.minio.io/docs/minio-bucket-notification-guide?

**Comment by jondavidjohn** [comment]
@nitisht Unfortunately no, I actually linked that above.  The problem here is that Amazon SQS and SNS (which are official s3 bucket notification targets) are not supported by Minio, only the follow are supported:

<img width="922" alt="screen shot 2018-03-19 at 4 21 22 pm" src="https://user-images.githubusercontent.com/401520/37623132-9eba08ac-2b91-11e8-9708-b6babf7992ab.png">

**Comment by harshavardhana** [comment]
> @nitisht Unfortunately no, I actually linked that above. The problem here is that Amazon SQS and SNS (which are official s3 bucket notification targets) are not supported by Minio, only the following are supported

@jondavidjohn how would we support them? are you saying that Amazon SQS accepts arbitrary connections from external services which support the event info structure? can you provide an example?

**Comment by phyrexian** [comment]
Are these not already available via the Webhooks handler? 

SQS: 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

(see the documentation example at the bottom)

**Comment by jondavidjohn** [comment]
> Amazon SQS accepts arbitrary connections from external services which support the event info structure?

Amazon SQS is just a managed queueing service and can be used however the implementor sees fit.  My thinking is that Minio could simply mimic the S3 event behavior and structure, in the same way that it mimics other S3 APIs.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-send-message.html

**Comment by jondavidjohn** [comment]
@phyrexian Ah, That could be a way to accomplish it today.  Though it seems like first class support for these services might be nice.  Thanks for the tip 👍 

I'll need to look into whether or not the webhook payload and structure would match the "native" S3 -> SQS structure and behavior.

**Comment by harshavardhana** [comment]
> Amazon SQS is just a managed queueing service and can be used however the implementor sees fit. My thinking is that Minio could simply mimic the S3 event behavior and structure, in the same way that it mimics other S3 APIs.

Minio already generates that while sending them to currently available targets, each target converts them in how they see fit to their native format.  As @phyrexian suggested webhooks would require your own way of doing this. 

> @phyrexian Ah, That could be a way to accomplish it today. Though it seems like first class support for these services might be nice. Thanks for the tip

First class support would be complicated to setup @jondavidjohn since the logic of ARN which has a region associated with the SQS v/s the Minio deployment would confuse the situation.  It is a bit harder to achieve to avoid confusion.  Webhook is perhaps a way to go here.

**Comment by jondavidjohn** [comment]
@harshavardhana Great, thanks for taking a look

**Comment by djanjic** [comment]
Webhook is not working with SQS. AWS SQS expects url encoded data and Minio uses JSON.

**Comment by harshavardhana** [comment]
> Webhook is not working with SQS. AWS SQS expects url encoded data and Minio uses JSON.

It won't work directly you will have to write a translation layer in your webhook handler @djanjic

**Comment by nitisht** [comment]
Closing this as answered @jondavidjohn , feel free to reopen if you have further questions
