### ISSUE TITLE
download linux-amd64 RELEASE.2018-03-16T22-52-12Z is not in archive 

### ISSUE THREAD

**Issue by mishak87** [minio/minio#5672]
RELEASE.2018-03-16T22-52-12 is missing from [archive](https://dl.minio.io/server/minio/release/linux-amd64/archive/) is only available in [release folder](https://dl.minio.io/server/minio/release/linux-amd64/).

I thought this has been automated already see #4632.

**Comment by harshavardhana** [comment]
> RELEASE.2018-03-16T22-52-12 is missing from archive is only available in release folder.

@mishak87 it only moves thereafter another release.

**Comment by mishak87** [comment]
https://github.com/minio/minio/issues/4632#issuecomment-313271230

**Comment by harshavardhana** [comment]
> #4632 (comment)

This is automated only to an extent that new releases move older release to archive, i don't think we need to change that at anytime now.  is there any specific reason you need it?

**Comment by mishak87** [comment]
I use archive URL in chef recipes for installing minio server.

Having to check two URLs is automation nightmare because last version is a moving target. As soon as you release new version you break scripts for installing now the second to new version.

**Comment by mishak87** [comment]
Current setup is a docker equivalent of tagging previous version with `ARCHIVE.<VERSION>` and deleting  original tag when you release new version.

**Comment by harshavardhana** [comment]
fixed this from next release onwards it is fully automated.
