### ISSUE TITLE
Please re-open #5472 - Snap produces `relocation error`

### ISSUE THREAD

**Issue by dragon2611** [minio/minio#5674]
I've already posted details in #5472 but I believe the issue referenced there occurs in ubuntu 17.10 as well.

**Comment by harshavardhana** [comment]
> I've already posted details in #5472 but I believe the issue referenced there occurs in ubuntu 17.10 as well.

We have no idea why snap produces this error, we are probably going to remove the reference since we never test on snap.

**Comment by dragon2611** [comment]
Fair enough it's not exactly difficult to install minio manually, it's just as I already had a snap on there for nextcloud I figured that was the easiest way to go
