### ISSUE TITLE
Docs: Erasure-code quickstart

### ISSUE THREAD

**Issue by dragon2611** [minio/minio#5675]
Not sure if this is the right project for raising issues with documentation, I'd suggest an edit to the doc directly but I wouldn't want to edit in incorrect info 

https://docs.minio.io/docs/minio-erasure-code-quickstart-guide doesn't make any reference to the minimum or maximum number of drives for erasure code.  (I'm pretty sure it did at one point)

https://docs.minio.io/docs/distributed-minio-quickstart-guide Suggests it's a minimum of 4 and maximum of 16 drives per tenant.

So either the limit's changed and the distributed doc is wrong or the EC doc could really use the info in the limits adding.

**Comment by harshavardhana** [comment]
these docs are correct @dragon2611 there needs to be a reference to new doc describing how to use beyond 16 disks on a regular setup https://docs.minio.io/docs/minio-large-bucket-support-quickstart-guide

**Comment by nitisht** [comment]
PR Sent https://github.com/minio/minio/pull/5677

**Comment by harshavardhana** [comment]
Closing this as fixed by #5677
