### ISSUE TITLE
Scroll doesn't work on the list of buckets in New UX

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#5682]
## Expected Behavior

Scroll functionality should work for the list of buckets.

## Current Behavior

In New UX, the scroll functionality doesn't work for the list of buckets. We can't access the buckets listed beyond the elements seen in the screenshot below:

<img width="1276" alt="screen shot 2018-03-21 at 12 40 57 pm" src="https://user-images.githubusercontent.com/27314853/37733500-7b1ff97c-2d05-11e8-9b68-4380c907ab8c.png">

## Possible Solution

This can be solved by adding back the Scrollbars component to`browser/app/js/buckets/BucketList.js`, and applying the relevant CSS changes.

## Steps to Reproduce (for bugs)

1. Create many buckets
2. Open the new version of the Minio browser
3. Try to scroll down on the list of buckets

## Context

This will affect users who have many buckets as they won't be able to access them via the browser.

## Your Environment

* Version used (`minio version`): Minio New UX
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kmkanagaraj** [comment]
Fixed in #5684
