### ISSUE TITLE
Update New UX favicon with the new logo and make its background transparent

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#5693]
## Expected Behavior

The favicon should have a higher resolution than the current one and its background should be transparent. It should be like the one shown below, but for the new Minio logo:

<img width="132" alt="screen shot 2018-03-22 at 3 50 42 pm" src="https://user-images.githubusercontent.com/27314853/37802706-cf8a76de-2de8-11e8-82f9-b6001478ede6.png">

## Current Behavior

The current favicon looks like the following. Notice that it has low resolution and the background is not transparent.

<img width="161" alt="screen shot 2018-03-22 at 3 45 14 pm" src="https://user-images.githubusercontent.com/27314853/37802744-eac4e876-2de8-11e8-9a59-161c884ccf9f.png">

## Possible Solution

We can replace the favicon that is on the `app/img/favicon.ico` directory

## Steps to Reproduce (for bugs)

1. Open the Minio browser locally
2. Check the favicon

## Context

The favicon with low resolution doesn't look visually appealing.

## Your Environment

* Version used (`minio version`): master
* Environment name and version (e.g. nginx 1.9.1): localhost
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kmkanagaraj** [comment]
Fixed in #5698
