### ISSUE TITLE
When bucket name exceeds sidebar width, it overflows instead of continuing onto the next line

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#5695]
## Expected Behavior

When the bucket name exceeds the width of the sidebar, it should continue onto the next line, like the old version of the UX.

<img width="319" alt="screen shot 2018-03-22 at 8 43 29 pm" src="https://user-images.githubusercontent.com/27314853/37810691-d09b4a2e-2e12-11e8-86d8-923ec9d4b081.png">

## Current Behavior

When the bucket name is long, it overflows and the part that overflows isn't visible. The bucket name also gets in the way of the bucket dropdown, however it is still selectable.

<img width="321" alt="screen shot 2018-03-22 at 8 49 22 pm" src="https://user-images.githubusercontent.com/27314853/37810713-f8cada96-2e12-11e8-907f-e817c1296292.png">

## Possible Solution

We need to add  `word-wrap: break-word;` to the `buckets__item` class in the CSS and adjust the paddings accordingly.

## Steps to Reproduce (for bugs)

1. Create a bucket with a long name on New UX

## Context

This is not visually appealing as the when bucket name is too long, it overlaps with the bucket dropdown. Also, the users cannot see the full name of the bucket when it is too long.

## Your Environment

* Version used (`minio version`): master
* Environment name and version (e.g. nginx 1.9.1): local and play.minio.io
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Fixed by https://github.com/minio/minio/pull/5694
