### ISSUE TITLE
C/C++ bindings

### ISSUE THREAD

**Issue by aaronovz1** [minio/minio#5702]
Is there any roadmap for providing a C or C++ binding for the Minio SDK?

**Comment by harshavardhana** [comment]
@aaronovz1 currently no, our recommendation is AWS SDK https://github.com/aws/aws-sdk-cpp

**Comment by aaronovz1** [comment]
I was actually trying to get away from using the AWS SDK, but are you suggesting that the AWS SDK will work for Minio as well? Basically I am trying to avoid vendor lock-in.

**Comment by harshavardhana** [comment]
> I was actually trying to get away from using the AWS SDK, but are you suggesting that the AWS SDK will work for Minio as well? Basically I am trying to avoid vendor lock-in.

Of course, all AWS SDKs will work with Minio. @aaronovz1

**Comment by aaronovz1** [comment]
Oh ok great!
