### ISSUE TITLE
Redesign Minio demo server(play.minio.io) landing page

### ISSUE THREAD

**Issue by rushenn** [minio/minio#5703]
As we have a new UI for Minio Browser, it is better to redesign the landing page of the demo server (play.minio.io) in order to make it look consistent across. 

## Expected Behavior
New design should match the Browser UI. It should also uses the same design elements such as fonts, colors etc.

## Current Behavior
Currently the landing page uses the design element of previous Browser UI. It also looks outdated compared to the new Browser UI. 

## Possible Solution
Redesigning a new landing page.

## Steps to Reproduce (for bugs)
http://play.minio.io:9000/

**Comment by harshavardhana** [comment]
Are we ever going to do this? @deekoder @rushenn if not shall we close it ?

**Comment by harshavardhana** [comment]
closing this since this issue has been open for long and there is no movement in terms of technical discussion or implementation.
