### ISSUE TITLE
Ignore unsupported object ACL header?

### ISSUE THREAD

**Issue by GeoffreyBooth** [minio/minio#5706]
I’m trying to use Minio to emulate S3 for an application I’m developing. My app uses a library to upload files/put objects into S3, and I don’t have much control over it. Unfortunately it applies an object-level ACL to every file uploaded, which I know Minio doesn’t support (#4496).

My issue is that Minio returns a 501 error, `A header you provided implies functionality that is not implemented`, on such attempted uploads. Would it be possible for Minio to just ignore this unsupported header? Possibly via configuration?

**Comment by harshavardhana** [comment]
We will have to discuss this since ignoring it would mean that we are falsely representing the API and behavior. IMO we should avoid doing such things as it might provide a false representation of API for applications and even cause them to expect a certain type of behavior which will be fake. 

Please do let us know what is the library you are using we can recommend changes, ACL is considered legacy style and is a legacy way to apply policy on a bucket which lacks flexibility.

**Comment by GeoffreyBooth** [comment]
> Please do let us know what is the library you are using we can recommend changes, ACL is considered legacy style and is a legacy way to apply policy on a bucket which lacks flexibility.

I know, I’ve investigated patching it but unfortunately I haven’t been able to. It’s a closed-source proprietary app called [OpenText Media Management](https://www.opentext.com/what-we-do/products/customer-experience-management/digital-asset-management/opentext-media-management). They only just added S3 support a few months ago, and yes, they’re using this deprecated API. That pretty much tells you all you need to know about their software (and no, I can’t stop using it).

Maybe a global configuration setting like “ignore unsupported APIs” or “ignore unsupported headers”? That would be disabled by default, to preserve the current behavior, but cases like mine could set this in order to override Minio’s validation.

**Comment by harshavardhana** [comment]
> Maybe a global configuration setting like “ignore unsupported APIs” or “ignore unsupported headers”? That would be disabled by default, to preserve the current behavior, but cases like mine could set this in order to override Minio’s validation.

Will let you know we can perhaps provide an unsafe mode @GeoffreyBooth

**Comment by harshavardhana** [comment]
This needs to be discussed @deekoder - moving this to blocked for discussion.

**Comment by deekoder** [comment]
@harshavardhana  will be sending PR for this soon.

**Comment by harshavardhana** [comment]
@GeoffreyBooth we will be supporting `GetBucketACL` as a dummy call for now which perhaps should resolve legacy application problems.  Will be sending a PR on this shortly.

**Comment by harshavardhana** [comment]
@GeoffreyBooth we have a PR here would you be able to validate it with your application? https://github.com/minio/minio/pull/5906 ?

**Comment by GeoffreyBooth** [comment]
Not quickly, sorry.

**Comment by harshavardhana** [comment]
> Not quickly, sorry.

@GeoffreyBooth you can try now `docker pull minio/minio:edge`
