### ISSUE TITLE
Distributed minio fails to heal drives after complete data loss of 2 of 4 drives

### ISSUE THREAD

**Issue by martinmoerch** [minio/minio#5708]
Similar to #5659, we're seeing an issue when trying out a test scenario, simulating failure of 2 of 4 drives in distributed minio, where heal never completes successfully.

## Expected Behavior
Verify parity and integrity of all objects in all buckets and recreate parity as needed.

## Current Behavior
-Before heal-
`mc admin info` reports 2 online, 2 offline: https://pastebin.com/raw/vW0MYdyK

-After heal-
On host/drive 2, performing `mc admin heal -r --json` reports "Heal had an error -  Storage resources are insufficient for the write operation.": https://pastebin.com/raw/v4EBTBgX 

Additionally, `mc admin info` now reports only host 2 as 4 online, 0 offline: https://pastebin.com/raw/ZVVvMYf3

Doing `mc admin service restart` and then `mc admin info`, after 5-10 seconds, now shows all online: https://pastebin.com/raw/mDtdbd4s

However, heal still fails: https://pastebin.com/raw/8SCbFvKn

Data is about 90MB and there's plenty of space available: https://pastebin.com/raw/fDqkXHk8

## Steps to Reproduce
1. Create new minio distributed cluster from scratch on 4 drives
2. Create single bucket
3. Upload files to bucket
4. Stop 2 nodes abruptly
5. Delete all disk data from same 2 nodes/drives
6. Start those 2 nodes again and proceed to try and heal

## Context
We're testing distributed minio and want to prepare for catastrophic data loss, before it happens :)

## Your Environment
* Versions used
minio:
`Version: 2018-03-19T19:22:06Z
Release-Tag: RELEASE.2018-03-19T19-22-06Z
Commit-ID: a4d2e2b4283b228c34ca2fe0aa007d792a726c3a`
mc:
`Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4`
* Server type and version: VirtualBox 5.2.6 r120293
* Operating System and version (`uname -a`): CentOS Linux release 7.4.1708 (3.10.0-693.17.1.el7.x86_64)

**Comment by harshavardhana** [comment]
This issue is not fixed correctly yet, re-opening.

**Comment by nitisht** [comment]
@martinmoerch the fix is now merged onto the master, could you give it a try and let us know how it goes

**Comment by martinmoerch** [comment]
@nitisht Oh snap, it worked perfectly! Thanks for the quick fix everyone.

**Comment by nitisht** [comment]
awesome!
