### ISSUE TITLE
df and minio space reports are different

### ISSUE THREAD

**Issue by gmile** [minio/minio#5713]
## Expected Behavior

Minio is reporting the same space stats as `df`.

## Current Behavior

Minio is reporting the space stats different to what is seen from `df`.

## Steps to Reproduce (for bugs)

1. Run `df`, see the output, note the `/minio`,

    ```
    eugene@k8s-monitoring:~$ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    udev             12G     0   12G   0% /dev
    tmpfs           2.4G   11M  2.4G   1% /run
    /dev/sda1        94G   57G   33G  64% /
    tmpfs            12G  1.5M   12G   1% /dev/shm
    tmpfs           5.0M     0  5.0M   0% /run/lock
    tmpfs            12G     0   12G   0% /sys/fs/cgroup
    /dev/sdb1       493G  268G  200G  58% /backups
    tmpfs           2.4G     0  2.4G   0% /run/user/1001
    /dev/sdc1       197G   68G  120G  37% /minio
    tmpfs           2.4G     0  2.4G   0% /run/user/1002
    eugene@k8s-monitoring:~$
    ```

2. Go to minio dashboard, note the free space:

    ![image 4](https://user-images.githubusercontent.com/207112/37916580-de406a78-3124-11e8-9e30-9325cc125960.png)

## Context

FWIW, Minio is writing to a location on disk that is backed by an iSCSI.

## Your Environment

* Version used (`minio version`): 

    ```
    minio/minio:RELEASE.2018-03-12T21-25-28Z
    ```
* Environment name and version (e.g. nginx 1.9.1): -
* Server type and version: -
* Operating System and version (`uname -a`):

    ```
    Linux k8s-monitoring 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    ```
* Link to your project: -

**Comment by gmile** [comment]
I have access to the server minio is running on. What can I do to further diagnose this?

**Comment by harshavardhana** [comment]
The reported numbers are correct `df -h` rounds them up to upper value.

**Comment by gmile** [comment]
@harshavardhana ugh, you're totally right! Thank you!
