### ISSUE TITLE
Object is not decrypted using AmazonS3EncryptionClient

### ISSUE THREAD

**Issue by impathan** [minio/minio#5720]
I am using AmazonS3EncryptionClient to encrypt my object on minio server

Here is my code:
`Aes aesAlgorithm = Aes.Create();
            aesAlgorithm.Key = File.ReadAllBytes(@"d:tempSymmetricKey.txt");

            EncryptionMaterials encryptionMaterials = new EncryptionMaterials(aesAlgorithm);
            AmazonS3CryptoConfiguration config = new AmazonS3CryptoConfiguration()
            {
                StorageMode = CryptoStorageMode.InstructionFile,
                ServiceURL = "https://play.minio.io:9000",
                ForcePathStyle = true,
                SignatureVersion = "2"
            };
            AmazonS3EncryptionClient client = new AmazonS3EncryptionClient("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", config, encryptionMaterials);

            string bucketName = "imran-bucket-1";
            var objectName = "bucket-7.txt";
            PutObjectRequest putObjectRequest = new PutObjectRequest
            {
                BucketName = bucketName,
                Key = objectName,
                ContentBody = "Hello, Testing...."
            };
            client.PutObjectAsync(putObjectRequest).Wait();
            GetObjectRequest getObjectRequest = new GetObjectRequest
            {
                BucketName = bucketName,
                Key = objectName
            };
            GetObjectResponse getObjectResponse = await client.GetObjectAsync(getObjectRequest);
            using (Stream decryptedStream = getObjectResponse.ResponseStream)
            {
                using (StreamReader reader = new StreamReader(decryptedStream))
                {
                    string decryptedContent = reader.ReadToEnd();
                    Console.WriteLine("Decrypted data: {0}", decryptedContent);
                }
            }`
 Console.WriteLine("Decrypted data: {0}", decryptedContent);
Always return encrypted data instead of decrypting content to original content.

**Comment by vadmeste** [comment]
@impathan, can you test with AWS S3 first? Client side encryption doesn't require any special behavior to be done in Minio server

**Comment by impathan** [comment]
Thanks,

> can you test with AWS S3 first?

Obviously, It should work with AWS S3 as its provided by Amazon AWS SDK

[https://aws.amazon.com/blogs/developer/client-side-data-encryption-with-aws-sdk-for-net-and-amazon-s3/](https://aws.amazon.com/blogs/developer/client-side-data-encryption-with-aws-sdk-for-net-and-amazon-s3/)

I will test Minio's server-side-encryption with aws-cli.
[https://docs.minio.io/docs/how-to-use-minio-s-server-side-encryption-with-aws-cli](https://docs.minio.io/docs/how-to-use-minio-s-server-side-encryption-with-aws-cli)

Thanks

**Comment by vadmeste** [comment]
I tested this code and you are right.. There is a bug somewhere.. Investigating..

**Comment by vadmeste** [comment]
@impathan this is most likely a bug in AWS .NET not knowing that header names are case insensitive as HTTP RFC says. In general, a patch is sent & accepted in AWS .NET in similar cases.

**Comment by vadmeste** [comment]
Closing after opening the issue: https://github.com/aws/aws-sdk-net/issues/927
