### ISSUE TITLE
Implement unauthenticated endpoints for server metrics

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#5723]
** not using template style **
Requirements are to implement un-authenticated endpoints which can serve system-level information about the server performance etc. Currently, this requires access/secret keys to be provided to a third-party such software such as `Prometheus` should be avoided.

- Network statistics
- API latency statistics
- Total number of APIs
- Overall memory usage graph

https://github.com/joe-pll/minio-exporter - re-implement this exporter such that it uses these unauthenticated endpoints.

**Comment by aead** [comment]
What about a token-based approach?

**Comment by SuperQ** [comment]
Depending on what kind of authentication minio supports, it should be reasonable to have a metrics-level access for Prometheus.  Prometheus doesn't _need_ to be unauthenticated.

**Comment by harshavardhana** [comment]
Minio re-purposes access/secret key which is used for S3 API as well which is a big security issue, un-authenticated access will only provide read-only access to system information and some metrics which are being actively captured by the server. 

Any new authentication mechanism brings problems of its own where we need to have a server component to validate it, just like how we do un-authenticated endpoints to check the server status and readiness probes. This is similar to that.

**Comment by aead** [comment]
>Minio re-purposes access/secret key which is used for S3 API as well which is a big security issue

Completely agree about that.

> Any new authentication mechanism brings problems of its own where we need to have a server component to validate it, just like how we do un-authenticated endpoints to check the server status and readiness probes. This is similar to that.

I think an un-authneticated metrics endpoint is okay as a mid-term solution as long as we are careful about the exposed API (The Admin-API is crucial security component). On the long run this may be also an item for the Admin-API authentication design (e.g. extra Admin-API credentials) which was mentioned internally before. Also for KMS we may need/want a new/separate authentication mechanism. But all this is beyond the scope of this issue and needs its own design (discussion) round.
