### ISSUE TITLE
Modify --quiet to output a final "server is ready" message _IF_ if output any other messages

### ISSUE THREAD

**Issue by nneul** [minio/minio#5724]
Currently, --quiet will show a few waiting messages during startup if it's waiting for other nodes/disks, but there is no clear indication that it stopped and is fully started. 

I'd like to see --quiet operate in a "if no special messages were output, don't say anything", but if it started showing any status messages like that, it should say something to indicate that it's done/recovered/operational.

Reason this came up is that I used --quiet in order to silence the very verbose and credential-showing interactive startup messages, but would still like to see a little bit more than it does now. 

Alternatively, just have --quiet always show a final 'server is ready on x.x.x.x:yyyy' message.

**Comment by kannappanr** [comment]
@nneul Thanks for filing the issue. We will talk internally and see if and how we can incorporate your request.

**Comment by kannappanr** [comment]
@nneul We will be showing a server is ready sort of output in the case where a `--quiet` flag is set.

**Comment by kannappanr** [comment]
The fix for this PR has been merged and already part of the last two releases.
