### ISSUE TITLE
Server Start-up: Unable to create configuration directories

### ISSUE THREAD

**Issue by magaldima** [minio/minio#5725]
## Expected Behavior
Minio server starts up fine. I recently updated Minikube from v0.25.0 -> v0.25.2. Previously, the minio server started up fine.

## Current Behavior
Ran `helm install stable/minio` and the server logs look like this:
```
Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:155:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-03-28T14:16:27.559344766Z] [FATAL] Unable to create configuration directories. (Mkdir /Root/.Minio/Certs: Read-Only File System)
```

## Steps to Reproduce (for bugs)
1. Install and run Minikube v0.25.2
2. `helm init`
3. `helm install stable/minio`

## Context
Trying to run minio server on local latest minikube.

## Your Environment

* Version used (`minio version`): stable
* Environment name and version (e.g. nginx 1.9.1): minikube v0.25.2

**Comment by nitisht** [comment]
@magaldima this is actually related to https://github.com/kubernetes/charts/pull/4281

The fix is merged now, can you please use Helm chart version `1.0.0` and try again

**Comment by magaldima** [comment]
I updated the helm chart to `1.0.0` using:
1. `helm repo update`
2. `helm install stable/minio`

However, now I see the following error during container creation:
`Error: failed to prepare subPath for volumeMount "minio-server-config" of container "minio"`. The pod has status: `Waiting: CreateContainerConfigError`

I see the following events from the pod:
```
Successfully assigned bold-spaniel-minio-568664fd7d-rkvk2 to minikube
default-scheduler
-
1
2018-03-28T15:06 UTC
2018-03-28T15:06 UTC
MountVolume.SetUp succeeded for volume "minio-server-config"
kubelet minikube
-
1
2018-03-28T15:06 UTC
2018-03-28T15:06 UTC
MountVolume.SetUp succeeded for volume "minio-user"
kubelet minikube
-
1
2018-03-28T15:06 UTC
2018-03-28T15:06 UTC
MountVolume.SetUp succeeded for volume "default-token-db9z9"
kubelet minikube
-
1
2018-03-28T15:06 UTC
2018-03-28T15:06 UTC
MountVolume.SetUp succeeded for volume "podinfo"
kubelet minikube
-
1
2018-03-28T15:06 UTC
2018-03-28T15:06 UTC
MountVolume.SetUp succeeded for volume "pvc-90f891c8-3299-11e8-ba35-080027a36be3"
kubelet minikube
-
1
2018-03-28T15:06 UTC
2018-03-28T15:06 UTC
Container image "minio/minio:RELEASE.2018-03-16T22-52-12Z" already present on machine
kubelet minikube
spec.containers{minio}
10
2018-03-28T15:06 UTC
2018-03-28T15:08 UTC
warning
Error: failed to prepare subPath for volumeMount "minio-server-config" of container "minio"
kubelet minikube
spec.containers{minio}
10
2018-03-28T15:06 UTC
2018-03-28T15:08 UTC
```

**Comment by nitisht** [comment]
Thanks @magaldima let me reproduce this locally and get back to you

**Comment by magaldima** [comment]
After some investigations, I found that the latest `Minikube v0.25.2` installs by default the latest version of `Kubernetes v1.9.4`. The above error of installing the minio helm chart occurred on this version of kubernetes. However, after deleting minikube and starting it up with `Kubernetes v1.9.0`, the helm installation of the minio chart succeeds. 

Steps:
1. Stop & delete minikube instance: `minikube stop | minikube delete`
2. Re-install minikube with previous version of k8: `minikube start --kubernetes-version v1.9.0`
3. Re-install minio: `helm install stable/minio`

Looks like this is due to some change in the `volumeMounts` for containers between kubernetes version `1.9.0` and `1.9.4`.

**Comment by nitisht** [comment]
Thanks for the info @magaldima , I will investigate on `1.9.4`

**Comment by magaldima** [comment]
This may be due to this: https://github.com/kubernetes/kubernetes/issues/60813 or this: https://github.com/kubernetes/kubernetes/issues/60814

Here's the one: https://github.com/kubernetes/kubernetes/issues/61076

**Comment by nitisht** [comment]
In that case, looks like the fix should be available in https://github.com/kubernetes/kubernetes/releases/tag/v1.9.5 

is it possible for you to confirm?

**Comment by magaldima** [comment]
yes, the problem is minikube only supports kubernetes <1.9.4. https://github.com/kubernetes/minikube/issues/2642 

so I can't confirm until I can actually run that version of Kubernetes.

**Comment by whisper-bye** [comment]
+1
I have the same problem as you

**Comment by harshavardhana** [comment]
> yes, the problem is minikube only supports kubernetes <1.9.4. kubernetes/minikube#2642
> 
> so I can't confirm until I can actually run that version of Kubernetes.

isn't using kubernetes 1.9.0 not an option? @magaldima @whisper-bye

**Comment by whisper-bye** [comment]
@harshavardhana 
yes, but another problems occur... [kubernetes/minikube#2570](https://github.com/kubernetes/minikube/issues/2570)

**Comment by harshavardhana** [comment]
Is it not possible to do `minikube config set kubernetes-version v1.8.0` ? @whisper-bye

**Comment by whisper-bye** [comment]
@harshavardhana 
bad news...
```bash
$ minikube config set kubernetes-version v1.9.0
$ minikube start
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
Getting VM IP address...
Kubernetes version downgrade is not supported. Using version: v1.9.4
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by rawkode** [comment]
Suffering this problem too. Is there a solution yet?

**Comment by nitisht** [comment]
what is you Kubernetes version @rawkode ?

**Comment by rawkode** [comment]
@nitisht 1.9.6

**Comment by nitisht** [comment]
Thanks @rawkode let me try to reproduce this and get back to you

**Comment by nitisht** [comment]
@rawkode I have removed the configMap support in the helm chart for now, so that the deployment goes through. Once https://github.com/kubernetes/charts/pull/4277 is merged, the helm chart should work as expected.

**Comment by nitisht** [comment]
@rawkode @magaldima  kubernetes/charts#4277 is merged, can you try out the latest Helm Chart version: `1.2.0`

**Comment by nitisht** [comment]
@rawkode @magaldima @whisper-bye closing this as we have confirmation from users about the Helm Chart version `1.2.0` working. Feel free to reopen if you're facing issues.

**Comment by magaldima** [comment]
I successfully deployed the `1.2.0` chart, however now I'm confused where to set the `minioConfig` for registering bucket notification resources. 

I am using this command, however there is no config map and on startup, the logs indicate no SQS resources.
```
helm install --set service.type=LoadBalancer stable/minio --name artifacts --set minioConfig.nats.enable=true --set minioConfig.nats.address=example-nats-cluster.nats-io:4222 --set minioConfig.nats.subject=bucketevents --set minioConfig.nats.username=user --set minioConfig.nats.password=psswrd
```

Minio server start-up logs:
```
Created minio configuration file successfully at /root/.minio
Drive Capacity: 13 GiB Free, 15 GiB Total
 Endpoint:  http://172.17.0.9:9000  http://127.0.0.1:9000
AccessKey: AKIAIOSFODNN7EXAMPLE 
SecretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY 
 Browser Access:
   http://172.17.0.9:9000  http://127.0.0.1:9000
 Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://172.17.0.9:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
 Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

Any help or updated documentation on registering bucket notifications would be greatly appreciated!

[UPDATED] I've found the config with this command:
`k exec artifacts-minio-6b677b94ff-ttvp5 cat /root/.minio/config.json`

And I am still seeing the `nats` config `"enable": false`

Also, would be good to have the [documentation](https://docs.minio.io/docs/minio-bucket-notification-guide) match latest updates. Especially this line:
```
The default location of Minio server configuration file is ~/.minio/config.json
```

**Comment by nitisht** [comment]
@magaldima we had to remove configMap support due to recent issues with Kubernetes ConfigMap. To enable notifications, you can exec into the Minio pod and update the `/root/.minio/config.json` based on details here https://docs.minio.io/docs/minio-bucket-notification-guide

**Comment by magaldima** [comment]
I am trying to exec in with: 
`k exec artifacts-minio-6b677b94ff-chd6w -it -- bash`

however, I get the following:
```
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
command terminated with exit code 126
```

**Comment by harshavardhana** [comment]
There is no bash in our containers you might need to use `sh`

**Comment by magaldima** [comment]
This still doesn't explain why the `minioConfig` values were not respected on chart install.

**Comment by nitisht** [comment]
> This still doesn't explain why the minioConfig values were not respected on chart install.

@magaldima As I mentioned [above](https://github.com/minio/minio/issues/5725#issuecomment-387452673) we had to remove configMap support due to [issues](https://github.com/kubernetes/kubernetes/issues/62099) in Kubernetes. Hence the chart doesn't honor `minioConfig` values.

**Comment by magaldima** [comment]
I exec'd into the pod and updated the `config.json`. Restarting the server is a bit tricky though since the config file is not on a persistent volume so `k delete pod ...` will not work as it will reset the config.json file contents. 

I had to point my docker daemon to the instance inside the cluster and run `docker ps` to find the container running the minio server and do `docker restart [container id]`.

**Comment by sylus** [comment]
https://github.com/kubernetes/charts/issues/5403

**Comment by magaldima** [comment]
The previous worked on Minikube, but now I'm having an issue with this on a Kubernetes cluster in a pre-production environment. I do not have access to the cluster's docker daemon and as you mentioned the `minioConfig` values are not honored. This means that I cannot configure any bucket notifications. 

Is there anyway for the minio server to pick up the configuration change after startup?

**Comment by magaldima** [comment]
can we reopen this? not being able to configure the minio server seems like an issue worth looking further into a better solution.

**Comment by nitisht** [comment]
sure @magaldima could you explain the problem

**Comment by magaldima** [comment]
See my previous comment:
> The previous worked on Minikube, but now I'm having an issue with this on a Kubernetes cluster in a pre-production environment. I do not have access to the cluster's docker daemon and as you mentioned the minioConfig values are not honored. This means that I cannot configure any bucket notifications.

> Is there anyway for the minio server to pick up the configuration change after startup?

**Comment by nitisht** [comment]
@magaldima We are adding configmap back to the helm chart https://github.com/kubernetes/charts/pull/6152
That should help you set config values

**Comment by nitisht** [comment]
@magaldima the https://github.com/kubernetes/charts/pull/6152 is merged. You should now be able to use configMaps again. Do you mind giving it a try

**Comment by nitisht** [comment]
@magaldima I going to close this as Charts is now updated and works on local testing. Feel free to reopen if there is a problem
