### ISSUE TITLE
Fail to delete Bucket Notifications

### ISSUE THREAD

**Issue by magaldima** [minio/minio#5727]
## Expected Behavior

bucket notifications are removed after using either the `mc` or the `go-client` to remove them.

## Current Behavior

I am experiencing this failure to delete bucket notifications for 2 minio clients: `mc` and `client-go`. Both give the same error response:
```
<ERROR> Cannot enable notification on the specified bucket. The XML you provided was not well-formed or did not validate against our published schema.
```

## Steps to Reproduce (for bugs)

1. Install latest minio helm chart (v1.0.0): `helm install stable/minio`
2. Install mc (see version below)
3. mc config host myminio add ...
4. mc mb myminio/test
5. mc events add myminio/test ...
6. mc events remove myminio/test --force

## Context

I am trying to delete bucket notifications from S3 buckets.

## Your Environment

* Versions used:
`minio helm chart version`: 1.0.0
`minio-server version`: RELEASE.2018-03-16T22-52-12Z
`mc version`: Version: 2018-03-14T23:16:27Z
`minio go-client version`: release-6.0

**Comment by harshavardhana** [comment]
we fixed this in master @magaldima will be making a new release, its a regression. c726145baf121ed4cccef5d4ddf622890e56bf4f

**Comment by kannappanr** [comment]
This has been fixed by https://github.com/minio/minio/pull/5673 . The fix is in the master. We will also be making a release either today or tomorrow.

**Comment by harshavardhana** [comment]
We made a release can you verify if this is fixed for you @magaldima ?

**Comment by magaldima** [comment]
Sure

**Comment by deekoder** [comment]
Fixed in master. Closing. @magaldima please reopen this issue if you find that we have not fixed it.

**Comment by magaldima** [comment]
I am testing this through installing the minio/minio helm chart on minikube. Does either the "latest" or the "edge" image tags from here (https://hub.docker.com/r/minio/minio/tags/) represent the master branch ? 

I am installing minio with this command:
```
helm install --set service.type=LoadBalancer --set image.tag=latest stable/minio --name argo-artifacts
```

and i am seeing the following fatal error in the pod:
```
[FATAL] Config migration failed. (Failed to migrate config from ‘22’ to ‘23’. rename /root/.minio/$tmpfile.config.json.119935690 /root/.minio/config.json: device or resource busy)
```

**Comment by harshavardhana** [comment]
This looks like you binded the config.json as a kubernetes device when we migrate we need to rename the existing config.json . EBUSY is perhaps because of this rename not being allowed.

**Comment by magaldima** [comment]
It looks like kubernetes treats volume mounted configmaps are immutable. If that's the case, attempting to rename them would probably fail as is happening when I try to install the helm minio chart. (https://github.com/kubernetes/kubernetes/pull/58720) 

This is not a problem when I use the current default minio helm chart version `RELEASE.2018-03-16T22-52-12Z`, however then the problem for this ticket in deleting bucket notifications pops up. Every attempt to use a more recent image fails with the above error.

**Comment by harshavardhana** [comment]
It won't pop up since the current helm is using a v22 config version and if you moved to newer image it would attempt to migrate to v23 perhaps @nitisht is perhaps updating the helm chart.

You could also manually add v23 config instead of v22 config in helm? Such that config.json migration doesn't happen.
