### ISSUE TITLE
Migrating configuration should not add additional hosts

### ISSUE THREAD

**Issue by nneul** [minio/minio#5745]
If you provide a v8 config, and run mc against it, in the process of upgrading the config - it populates additional hosts with useless default configuration in the resulting file. That's fine when creating a blank config, but seems like it is inappropriate to do when upgrading.

Would prefer to see the config upgrade JUST upgrade, not otherwise add to or alter the config.

**Comment by harshavardhana** [comment]
It's not useless @nneul they are always there by default - it is intentional, also this issue is related to `mc` could you create this on github.com/minio/mc instead of here??

**Comment by nneul** [comment]
My point is that it's taking a perfectly valid config file (if out of date on version) and _adding_ non-functional content to it. 

Will recreate in mc repo.

**Comment by nneul** [comment]
FYI for any search results hitting this:  

https://github.com/minio/mc/issues/2425

https://github.com/minio/mc/pull/2426
