### ISSUE TITLE
"ECONNRESET" if key contains leading slash "/"

### ISSUE THREAD

**Issue by gjgarryuan** [minio/minio#5751]
Using aws-sdk javascript 2.194.0:

When uploading with key consisting of leading slash "/", the aws-sdk rejects with:

```
s3.putObject({
    Bucket: 'bucket',
    Key: '/path/to/entity',
    Body: fs.readFileSync('/path/to/local/file'),
    ACL: 'bucket-owner-full-control'
}).promise();
```

```
{ Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TCP.onread (net.js:620:25)
  message: 'read ECONNRESET',
  errno: 'ECONNRESET',
  code: 'NetworkingError',
  syscall: 'read',
  region: 'us-east-1',
  hostname: 'xxx',
  retryable: true,
  time: 2018-04-02T15:09:46.769Z }
```

I tried it with the real aws s3 in which case the aws-sdk didn't reject with any error, but the uploaded entity was under a "virtual" folder without a name. I guess that was the effect of the leading slash in the key.

## Expected Behavior
It should put the entity under a virtual folder just like the real aws s3 does.

## Current Behavior
It currently reset the connection which causes the aws-sdk rejects with "ECONNRESET".

## Steps to Reproduce (for bugs)
```
s3.putObject({
    Bucket: 'bucket',
    Key: '/path/to/entity',
    Body: fs.readFileSync('/path/to/local/file'),
    ACL: 'bucket-owner-full-control'
}).promise();
```

## Context
Use minio for local functional testing for the s3 integration of my program.

## Your Environment
Spawn up using docker and below is the info in the "about" of the Minio Browser:

VERSION
2018-03-28T23:45:53Z
MEMORY
Used: 5.1 MB | Allocated: 105 MB | Used-Heap: 5.1 MB | Allocated-Heap: 9.9 MB
PLATFORM
Host: 9c665a69d796 | OS: linux | Arch: amd64
RUNTIME
Version: go1.9.4 | CPUs: 2

**Comment by harshavardhana** [comment]
Minio uses filesystem paths so it cannot really create virtual folders the way aws S3. AWS S3 recommends using proper relative paths to bucket for better management such that in future tools like AWS cli, s3cmd functionalities work properly. Otherwise this can lead to complications when copying data.

Minio server automatically restricts this usage .. simply remove the leading `/` the affect is same.

**Comment by gjgarryuan** [comment]
Thanks for the reply.

If it is expected that Minio does not support key with leading slash, I will close this ticket.
