### ISSUE TITLE
b2 gateway gives misleading error messages for "mc mb" failures

### ISSUE THREAD

**Issue by vielmetti** [minio/minio#5758]
The b2 gateway gives several error messages which are misleading in the face of failures to make buckets (`mc mb`) on b2. None of these are fatal, just cosmetic, but they had me wondering whether I had set up the system incorrectly.

## Expected Behavior

Example 1.

```
Eds-MacBook-Pro:~ ed$ mc mb myb2/mp3
mc: <ERROR> Unable to make bucket `myb2/mp3`. We encountered an internal error, please try again.
```

b2 buckets have a minimum size length of 6 characters, per the Backblaze web site which reads: "Each bucket name must be at least 6 characters long."

Example 2.

```
Eds-MacBook-Pro:~ ed$ mc mb myb2/b2-mp3
mc: <ERROR> Unable to make bucket `myb2/b2-mp3`. The specified bucket does not exist
```

b2 buckets cannot be named with the initial prefix characters "b2-", per the Backblaze web site which reads: "BucketName must not start with 'b2-'. reserved for Backblaze use."

## Current Behavior

Error messages are less informative than they might be, though there is no loss of data, just a little temporary confusion.

## Possible Solution

Perhaps the detailed API responses for these two failures (bucket name too short; bucket name reserved) can be examined to give a better error report.

## Context

After setting up a b2 gateway, I was surprised that my first two tries to use it failed.

## Your Environment
* Version used (`minio version`):

```
$ docker run minio/minio version
Version: 2018-03-30T00:38:44Z
Release-Tag: RELEASE.2018-03-30T00-38-44Z
Commit-ID: 804a4f9c159ecef7093585a5b577e03a382af50e
```

* Operating System and version (`uname -a`):
```
Linux bastion-0 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by deekoder** [comment]
will look into it.

**Comment by deekoder** [comment]
@vielmetti  can you try without the / char in bucket name and tell me if that's failing?

**Comment by vielmetti** [comment]
@deekoder just to be clear the 'myb2' is set up according to the instructions at https://github.com/minio/minio/blob/master/docs/gateway/b2.md with 

`mc config host add myb2 http://gateway-ip:9000 b2_account_id b2_application_key`

Once I correctly name the `b2` buckets all is well.

**Comment by harshavardhana** [comment]
Reproduced it and sending a fix - thanks for opening the bug @vielmetti
