### ISSUE TITLE
Minio fails to initialize object layer (disk path full) with k8s PVC on AWS EBS class gp2

### ISSUE THREAD

**Issue by dferstay** [minio/minio#5761]
## Expected Behavior

I am using the ```minio/minio:RELEASE.2018-03-30T00-38-44Z``` to deploy a standalone minio service using the following k8s StatefulSet:
<pre>apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: minio # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: s3_access_key
        - name: MINIO_SECRET_KEY
          value: s3_secret_key
        image: minio/minio:RELEASE.2018-03-30T00-38-44Z
        args:
        - server
        - /data
        ports:
        - containerPort: 9000
        # Each pod in the PetSet gets a volume mounted at mountPath
        volumeMounts:
        - name: minio-data
          mountPath: /data
        # Liveness probe detects situations where Minio server instance
        # is not working properly and needs restart. Kubernetes automatically
        # restarts the pods if liveness checks fail.
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
</pre>

I expect that a single mino pod will be deployed.

## Current Behavior

I see that the required PVC is created:
<pre>
$ kubectl -n user-dferstay get pvc
NAME                             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
minio-data-minio-0               Bound     pvc-2a1a2cfa-3770-11e8-8eb4-02c838be99c4   1Gi        RWO            gp2            7s
</pre>
<pre>
$ kubectl -n user-dferstay describe pvc minio-data-minio-0 
Name:          minio-data-minio-0
Namespace:     user-dferstay
StorageClass:  gp2
Status:        Bound
Volume:        pvc-2a1a2cfa-3770-11e8-8eb4-02c838be99c4
Labels:        app=minio
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
Finalizers:    []
Capacity:      1Gi
Access Modes:  RWO
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  ProvisioningSucceeded  20m   persistentvolume-controller  Successfully provisioned volume pvc-2a1a2cfa-3770-11e8-8eb4-02c838be99c4 using kubernetes.io/aws-ebs
</pre>
But the minio pod fails to initialize its storage layer:
<pre>
$ kubectl -n user-dferstay logs -f minio-0
Created minio configuration file successfully at /root/.minio

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:267:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:155:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-04-03T18:52:58.385047218Z] [ERROR] Initializing object layer failed (disk path full)
</pre>

Exec'ing into a running container before it crashes I see that ```/dev/xvdbt``` is mounted on ```/data```
<pre>
/ # mount
overlay on / type overlay (rw,context="system_u:object_r:svirt_lxc_file_t:s0:c231,c537",relatime,lowerdir=/var/lib/docker/overlay/7c56cf93c4015481c0ad22a10c0784db992a6482d04924d52204f8e028aa710d/root,upperdir=/var/lib/docker/overlay/abaed83c5f997fab58ba5ada5aacebe7c02d4563a3a6746c054899d573b27ddd/upper,workdir=/var/lib/docker/overlay/abaed83c5f997fab58ba5ada5aacebe7c02d4563a3a6746c054899d573b27ddd/work)
overlay on / type overlay (rw,context="system_u:object_r:svirt_lxc_file_t:s0:c231,c537",relatime,lowerdir=/var/lib/docker/overlay/7c56cf93c4015481c0ad22a10c0784db992a6482d04924d52204f8e028aa710d/root,upperdir=/var/lib/docker/overlay/abaed83c5f997fab58ba5ada5aacebe7c02d4563a3a6746c054899d573b27ddd/upper,workdir=/var/lib/docker/overlay/abaed83c5f997fab58ba5ada5aacebe7c02d4563a3a6746c054899d573b27ddd/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,seclabel,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,seclabel,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
mqueue on /dev/mqueue type mqueue (rw,seclabel,nosuid,nodev,noexec,relatime)
/dev/xvdbt on /data type ext4 (rw,seclabel,relatime,data=ordered)
/dev/mapper/pods on /dev/termination-log type ext4 (rw,seclabel,relatime,stripe=256,data=ordered)
/dev/xvda9 on /etc/resolv.conf type ext4 (rw,seclabel,relatime,data=ordered)
/dev/xvda9 on /etc/hostname type ext4 (rw,seclabel,relatime,data=ordered)
/dev/mapper/pods on /etc/hosts type ext4 (rw,seclabel,relatime,stripe=256,data=ordered)
shm on /dev/shm type tmpfs (rw,context="system_u:object_r:svirt_lxc_file_t:s0:c231,c537",nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /var/run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,seclabel,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/latency_stats type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,seclabel,relatime)
tmpfs on /sys/firmware type tmpfs (ro,seclabel,relatime)
</pre>

I can also see that there is plenty of free space and inodes on ```/dev/xvdbt```
<pre>
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 121.7G     17.1G     99.5G  15% /
overlay                 121.7G     17.1G     99.5G  15% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    60.0G         0     60.0G   0% /sys/fs/cgroup
/dev/xvdbt              975.9M      2.5M    906.2M   0% /data
/dev/mapper/pods          3.4T    211.0M      3.4T   0% /dev/termination-log
/dev/xvda9              121.7G     17.1G     99.5G  15% /etc/resolv.conf
/dev/xvda9              121.7G     17.1G     99.5G  15% /etc/hostname
/dev/mapper/pods          3.4T    211.0M      3.4T   0% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    60.0G     12.0K     60.0G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    60.0G         0     60.0G   0% /proc/scsi
tmpfs                    60.0G         0     60.0G   0% /sys/firmware
/ # df -hi
Filesystem              Inodes      Used Available Use% Mounted on
overlay                  31.3M   1022.5K     30.3M   3% /
overlay                  31.3M   1022.5K     30.3M   3% /
tmpfs                    15.0M        17     15.0M   0% /dev
tmpfs                    15.0M        16     15.0M   0% /sys/fs/cgroup
/dev/xvdbt               64.0K        11     64.0K   0% /data
/dev/mapper/pods        221.2M      1.1K    221.2M   0% /dev/termination-log
/dev/xvda9               31.3M   1022.5K     30.3M   3% /etc/resolv.conf
/dev/xvda9               31.3M   1022.5K     30.3M   3% /etc/hostname
/dev/mapper/pods        221.2M      1.1K    221.2M   0% /etc/hosts
shm                      15.0M         1     15.0M   0% /dev/shm
tmpfs                    15.0M         9     15.0M   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.0M        17     15.0M   0% /proc/kcore
tmpfs                    15.0M        17     15.0M   0% /proc/latency_stats
tmpfs                    15.0M        17     15.0M   0% /proc/timer_list
tmpfs                    15.0M        17     15.0M   0% /proc/sched_debug
tmpfs                    15.0M         1     15.0M   0% /proc/scsi
tmpfs                    15.0M         1     15.0M   0% /sys/firmware
</pre>

## Steps to Reproduce (for bugs)

1. Use the k8s StatefulSet resource above and deploy it on an Kubernetes running on an AWS cluster.

## Context

I am attempting to run a Druid  cluster using S3 as the deep storage layer on k8s in an AWS cluster where I don't have permissions to access S3.

**Comment by nitisht** [comment]
Thanks for reporting @dferstay , let me setup a cluster and try to reproduce this locally. Will get back to you

**Comment by nitisht** [comment]
@dferstay can you please try 

```
 image: minio/minio:RELEASE.2018-04-19T22-54-58Z
        args:
        - server
        - /data/drive
```

and let us know how this goes?

**Comment by dferstay** [comment]
Hi @nitisht; I get the same mode of failure at startup:


Unfortunately, I get the same result:
```
dan@paso:~/src/pike-docker$ kubectl -n user-dferstay logs minio-0
Created minio configuration file successfully at /root/.minio


API: SYSTEM()
Time: 19:49:25 UTC 04/23/2018
Error: disk path full
       1: cmd/server-main.go:262:cmd.serverMain()
```

And a shell into the running container shows that there is plenty of space
```
dan@paso:~/src/pike-docker$ kubectl -n user-dferstay exec -ti minio-0 -- /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 121.7G     38.9G     77.8G  33% /
overlay                 121.7G     38.9G     77.8G  33% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    60.0G         0     60.0G   0% /sys/fs/cgroup
/dev/xvdbu              975.9M      2.5M    906.2M   0% /data
/dev/mapper/pods          3.4T      4.5G      3.4T   0% /dev/termination-log
/dev/xvda9              121.7G     38.9G     77.8G  33% /etc/resolv.conf
/dev/xvda9              121.7G     38.9G     77.8G  33% /etc/hostname
/dev/mapper/pods          3.4T      4.5G      3.4T   0% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    60.0G     12.0K     60.0G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    60.0G         0     60.0G   0% /proc/scsi
tmpfs                    60.0G         0     60.0G   0% /sys/firmware
/ # mount
overlay on / type overlay (rw,context="system_u:object_r:svirt_lxc_file_t:s0:c292,c923",relatime,lowerdir=/var/lib/docker/overlay/0ef5a0ba1e4f07f61b8ea69fe9f5d14509739580445cd709854f734ed263f676/root,upperdir=/var/lib/docker/overlay/e4f7b3d8043b85b1d6475c1138b2b395ff07073319c28cbba5c4c3c9c08324dd/upper,workdir=/var/lib/docker/overlay/e4f7b3d8043b85b1d6475c1138b2b395ff07073319c28cbba5c4c3c9c08324dd/work)
overlay on / type overlay (rw,context="system_u:object_r:svirt_lxc_file_t:s0:c292,c923",relatime,lowerdir=/var/lib/docker/overlay/0ef5a0ba1e4f07f61b8ea69fe9f5d14509739580445cd709854f734ed263f676/root,upperdir=/var/lib/docker/overlay/e4f7b3d8043b85b1d6475c1138b2b395ff07073319c28cbba5c4c3c9c08324dd/upper,workdir=/var/lib/docker/overlay/e4f7b3d8043b85b1d6475c1138b2b395ff07073319c28cbba5c4c3c9c08324dd/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,seclabel,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,seclabel,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
mqueue on /dev/mqueue type mqueue (rw,seclabel,nosuid,nodev,noexec,relatime)
/dev/xvdbu on /data type ext4 (rw,seclabel,relatime,data=ordered)
/dev/mapper/pods on /dev/termination-log type ext4 (rw,seclabel,relatime,stripe=256,data=ordered)
/dev/xvda9 on /etc/resolv.conf type ext4 (rw,seclabel,relatime,data=ordered)
/dev/xvda9 on /etc/hostname type ext4 (rw,seclabel,relatime,data=ordered)
/dev/mapper/pods on /etc/hosts type ext4 (rw,seclabel,relatime,stripe=256,data=ordered)
shm on /dev/shm type tmpfs (rw,context="system_u:object_r:svirt_lxc_file_t:s0:c292,c923",nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,seclabel,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/latency_stats type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,seclabel,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,seclabel,relatime)
tmpfs on /sys/firmware type tmpfs (ro,seclabel,relatime)
/ # df -hi
Filesystem              Inodes      Used Available Use% Mounted on
overlay                  31.3M      2.2M     29.1M   7% /
overlay                  31.3M      2.2M     29.1M   7% /
tmpfs                    15.0M        17     15.0M   0% /dev
tmpfs                    15.0M        16     15.0M   0% /sys/fs/cgroup
/dev/xvdbu               64.0K        11     64.0K   0% /data
/dev/mapper/pods        221.2M      8.4K    221.2M   0% /dev/termination-log
/dev/xvda9               31.3M      2.2M     29.1M   7% /etc/resolv.conf
/dev/xvda9               31.3M      2.2M     29.1M   7% /etc/hostname
/dev/mapper/pods        221.2M      8.4K    221.2M   0% /etc/hosts
shm                      15.0M         1     15.0M   0% /dev/shm
tmpfs                    15.0M         9     15.0M   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.0M        17     15.0M   0% /proc/kcore
tmpfs                    15.0M        17     15.0M   0% /proc/latency_stats
tmpfs                    15.0M        17     15.0M   0% /proc/timer_list
tmpfs                    15.0M        17     15.0M   0% /proc/sched_debug
tmpfs                    15.0M         1     15.0M   0% /proc/scsi
tmpfs                    15.0M         1     15.0M   0% /sys/firmware
```

**Comment by nitisht** [comment]
I just noticed you have the storage set to ` storage: 1Gi` in the yaml file. Could you please change it to `2 Gi` and try?

**Comment by dferstay** [comment]
Thanks @nitisht.  After bumping the size of the persistent volume claim to 2G minio started up and is staying up:
```
dan@paso:~/src/pike-docker$ kubectl -n user-dferstay logs minio-0
Created minio configuration file successfully at /root/.minio

Drive Capacity: 1.8 GiB Free, 1.8 GiB Total

Endpoint:  http://100.121.5.225:9000  http://127.0.0.1:9000
8<snipped>8
```

Was I unwittingly bumping into a minimum volume size?

**Comment by nitisht** [comment]
> After bumping the size of the persistent volume claim to 2G minio started up and is staying up:

Great!

> Was I unwittingly bumping into a minimum volume size?

Yes, 1 Gi is the minimum required storage for Minio instances. Feel free to close the issue @dferstay

**Comment by dferstay** [comment]
> Yes, 1 Gi is the minimum required storage for Minio instances.

Thanks.  Is this documented somewhere?

**Comment by nitisht** [comment]
I don't think so @dferstay , we will add it in the docs. Thanks for the pointer

**Comment by dferstay** [comment]
No problem!
