### ISSUE TITLE
[Error] Unable to write to client on GET request for object

### ISSUE THREAD

**Issue by alexander-daniel** [minio/minio#5762]
I have a docker-compose project using `minio` and I am able to upload and listen to files that I upload. However, for some reason, these errors are pouring out on me.

Thank you so much for checking this out. Much appreciated!

## Expected Behavior
It's odd. Files are still fetch-able and I can make requests for them successfully, this error just throws every time on the backend.

I'm confused about where it wants to pipe that data too, and the upstream port is different everytime.

## Current Behavior

```

s3_1                 |
s3_1                 | Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:185:cmd.objectAPIHandlers.GetObjectHandler()
s3_1                 |        2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:72:cmd.(objectAPIHandlers).GetObjectHandler-fm()
s3_1                 |        3: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
s3_1                 |        4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
s3_1                 |        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:617:cmd.rateLimit.ServeHTTP()
s3_1                 |        6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:575:cmd.pathValidityHandler.ServeHTTP()
s3_1                 |        7: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:514:cmd.httpStatsHandler.ServeHTTP()
s3_1                 |        8: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
s3_1                 |        9: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:90:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
s3_1                 |       10: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
s3_1                 |       11: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
s3_1                 |       12: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
s3_1                 |       13: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
s3_1                 |       14: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
s3_1                 |       15: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
s3_1                 |       16: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
s3_1                 |       17: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:465:cmd.resourceHandler.ServeHTTP()
s3_1                 |       18: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:257:cmd.authHandler.ServeHTTP()
s3_1                 |       19: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:133:cmd.reservedMetadataHandler.ServeHTTP()
s3_1                 |       20: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/server.go:111:http.(*Server).Start.func1()
s3_1                 |       21: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
s3_1                 |       22: /opt/go/src/net/http/server.go:2619:http.serverHandler.ServeHTTP()
s3_1                 |       23: /opt/go/src/net/http/server.go:1801:http.(*conn).serve()
s3_1                 | [2018-04-03T19:48:23.348075706Z] [ERROR] Unable to write to client. (write tcp 172.18.0.3:9003->172.18.0.8:54676: write: broken pipe)
```

## Your Environment

* Version used (`minio version`): docker `minio/minio:latest`
* Environment name and version (e.g. nginx 1.9.1): `docker-compose 1.20.1`
* Server type and version: `nginx`
* Operating System and version (`uname -a`): whatever is packaged with docker image
* Link to your project:

**Comment by harshavardhana** [comment]
> s3_1                 | [2018-04-03T19:48:23.348075706Z] [ERROR] Unable to write to client. (write tcp 172.18.0.3:9003->172.18.0.8:54676: write: broken pipe)

Broken pipe happens when your client reader has not read the entire content that it requested, it is possible that your client is ignoring the last byte. There are few situations where this can happen

- Client abruptly closed the connection (client died) without reading the entire stream.
- A client forgets the last byte and doesn't drain the entire stream 

So you can simply ignore this error for now, we are revamping these logs anyways - since it's not indicative of a server problem - instead of a problem on the client.

**Comment by alexander-daniel** [comment]
@harshavardhana thank you so much for your answer. I was about to update the issue, as I found out it only happens when im using an HTML5 `<audio>` component, with certain settings for preload. 

So yeah -- what you explained makes sense! The client was not buffering the entire file, so there probably lies the issue.

Thank you again and I'll keep my ear to the ground for the coming updates.

**Comment by kannappanr** [comment]
@alexander-daniel Closing the issue as answered. Please feel free to reopen the issue, if that is not the case.
