### ISSUE TITLE
Would like ability to either tell minio to not show free space information/ignore some drives/apply multiplier

### ISSUE THREAD

**Issue by nneul** [minio/minio#5763]
## Expected Behavior

For embedded use and to allow provisioning a 2-node cluster, I've got a minio cluster set up with multiple directories as "disks". Unfortunately, since these are the same backend storage, this results in minio over-reporting total space. 

It would be nice if there were a way to say to minio server to either

A) Don't show free space at all
B) Ignore drive X for space calculations. 
C) Apply a multiplier to free space

This is also applicable for example if you are using minio purely as a means to provide a resilient S3-compatible object store, and don't actually care about the backend erasure code other than to allow for server failover/maintenance/etc. 

## Current Behavior

Two servers, 4 disks each, on same backend filesystem = 4 x actual capacity since each server is counting the same filesystem 4 times. 

## Possible Solution

Allow turning off free space calculation.

Allow telling config to 'ignore disk X', 'ignore disk Y' for disk space calculations

Allow telling config to "apply disk space multiplier" -- i.e. "0.25" for the example above. 

## Your Environment

Version: 2018-03-19T19:22:06Z
Release-Tag: RELEASE.2018-03-19T19-22-06Z
Commit-ID: a4d2e2b4283b228c34ca2fe0aa007d792a726c3a

ub 16.04 x64

**Comment by kannappanr** [comment]
@nneul Thanks for reporting the issue. Will check internally about not displaying the disk free space. One work around is to use the `quiet` flag. This does not display any startup message including the free disk space.

**Comment by nneul** [comment]
Just to be clear - this was primarily referring to free space indicator in center-top of browser UI, not console output.

**Comment by kannappanr** [comment]
@nneul Thanks for the clarification.

**Comment by harshavardhana** [comment]
There is no easier way to do this, can you explain how it useful for your application ?  Since you are using S3 API only does it really matter what is in storage info ?

**Comment by nneul** [comment]
Well, the admin/browse console for minio is exposed in the appliance minio is being put on, and some of the folks tat will go there are guaranteed (already have) to get all freaked out about the size information being completely out of touch with reality.

It's not a problem unique to minio - many monitoring packages have the same sort of not-handling of multiple mounts - think the scenario of you having N different NFS mounts on a box for different users coming off the same NAS - with all of them reporting X GB free of Y GB.

**Comment by harshavardhana** [comment]
you can simply disable browser with MINIO_BROWSER=off

**Comment by nneul** [comment]
They want/need the browser. The point is I'd like the _space_ display in the browser to either be correct or to be able to hide if it is not possible to correct it.

**Comment by kannappanr** [comment]
@nneul It has been decided that we will not be doing this feature. We expect the user to use different disks and not different folders within a single disk.

**Comment by payne8** [comment]
@kannappanr 
What about the multi-tenant usage? Should we have different disks for every new instance we spin up? That seems like overkill. I would prefer to be able to simply show my user the amount of storage they are using in their own instance. I don't care about what space is used by other files being present on the drive and I don't want my user caring about how much space is left on their cluster. 

The browser is a very useful tool and very well built and designed. I would prefer not to have to build my own browser or maintain a fork just to hide one part of the UI that doesn't work for my use-case (and obviously for others as well).

Further more, the multi-tenant instructions indicate we should use different folders on the same drive which is the opposite from what you just suggested. https://github.com/krishnasrinivas/cookbook/blob/68b6dab51f557ed437449104970abcf3bacf4b7b/docs/multi-tenancy-in-minio.md

Maybe I am misunderstanding how the space calculation is working and each instance really does only show the current instance's usage. I am only at the beginning stages of developing my multi-tenant setup.

**Comment by krishnasrinivas** [comment]
For multi-tenant case, it is indeed confusing to show disk space used by other tenants. But this is a hard problem to solve @payne8 we'll discuss again and get back. Do you prefer not showing disk usage than showing it in such a setup?

**Comment by harshavardhana** [comment]
> For multi-tenant case, it is indeed confusing to show disk space used by other tenants. But this is a hard problem to solve @payne8 we'll discuss again and get back. Do you prefer not showing disk usage than showing it in such a setup?

There is no way to restrict tenants from using the entire space so it is correct in the way it is showing right now. Since there is no such policy applied to restrict tenants there is no real value in even showing a lesser disk space. 

If the disks were partitioned correctly let's say if you have a zfs/btrfs like volumes and each of them has quotas on them. Then minio server will report the right size in accordance with the restriction applied by the underneath backend.  Without any of these underlying restrictions providing a fake value in UI is more misleading, in-fact the current UI should be thought of has thin provisioning i.e Each tenant is able to use up to the size of the backend. So it is expected that one may use more over each other.

**Comment by nneul** [comment]
Just adding the option to allow hiding the space listing from the UI would be an easy option that would help both of these cases while you work toward a more suitable multi-tenant solution. (Even if that is just a bit of CSS.)

**Comment by krishnasrinivas** [comment]
@nneul  We avoid adding options unless it is absolutely necessary.

**Comment by nneul** [comment]
Would you consider a generic option - to allow custom CSS/JS insert in the UI? That seems like it would be general purpose hook for customization like this?

**Comment by krishnasrinivas** [comment]
no @nneul ability to customize the UI is not the right solution. It will just add more complexity and variations to the UI.

**Comment by krishnasrinivas** [comment]
I was able to make the storage-info disappear by using the sub_filter nginx config.

First run this script:
```
krishna@escape:/tmp$ cat gen.sh 
#!/bin/sh

echo -n "sub_filter "; echo -n "'";curl -H User-Agent:Mozilla -s localhost:9000/minio/ | sed 's/$/\\n/g' | sed "s/'/\\\'/g" | tr -d '\n'; echo -n "' '";curl -H User-Agent:Mozilla -s localhost:9000/minio/ | sed 's/$/\\n/g' | sed "s/'/\\\'/g" | tr -d '\n' | sed 's#</body>#<script>var hideStorageInfo = function() {var usage = document.getElementsByClassName("feh-usage");if(usage){usage[0].style.display = "none"} else setTimeout(hideStorageInfo, 100)}; setTimeout(hideStorageInfo, 100)</script></body>#g';echo "';"
krishna@escape:/tmp$ 
```

```
krishna@escape:/tmp$ bash gen.sh 
sub_filter '<!DOCTYPE html>\n<html>\n\n    <head>\n        <meta charset="UTF-8">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        <title>Minio Browser</title>\n        <link rel="stylesheet" href="loader.css" type="text/css">\n    </head>\n\n    <body>\n        <div class="page-load">\n            <div class="pl-inner">\n                <img src="logo.svg" alt="">\n            </div>\n        </div>\n        <div id="root"></div>\n\n        <!--[if lt IE 11]>\n            <div class="ie-warning">\n                <div class="iw-inner">\n                    <i class="iwi-icon fa fa-warning"></i>\n\n                    You are using Internet Explorer version 12.0 or lower. Due to security issues and lack of support for Web Standards it is highly recommended that you upgrade to a modern browser\n\n\n                    <ul>\n                        <li>\n                            <a href="http://www.google.com/chrome/">\n                                <img src="chrome.png" alt="">\n                                <div>Chrome</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.mozilla.org/en-US/firefox/new/">\n                                <img src="firefox.png" alt="">\n                                <div>Firefox</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.apple.com/safari/">\n                                <img src="safari.png" alt="">\n                                <div>Safari</div>\n                            </a>\n                        </li>\n                    </ul>\n\n                    <div class="iwi-skip">Skip & Continue</div>\n                </div>\n            </div>\n        <![endif]-->\n\n        <script>currentUiVersion = \'2018-04-16T18:35:51Z\'</script>\n        <script src="index_bundle-2018-04-16T18-35-51Z.js"></script>\n    </body>\n</html>\n' '<!DOCTYPE html>\n<html>\n\n    <head>\n        <meta charset="UTF-8">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        <title>Minio Browser</title>\n        <link rel="stylesheet" href="loader.css" type="text/css">\n    </head>\n\n    <body>\n        <div class="page-load">\n            <div class="pl-inner">\n                <img src="logo.svg" alt="">\n            </div>\n        </div>\n        <div id="root"></div>\n\n        <!--[if lt IE 11]>\n            <div class="ie-warning">\n                <div class="iw-inner">\n                    <i class="iwi-icon fa fa-warning"></i>\n\n                    You are using Internet Explorer version 12.0 or lower. Due to security issues and lack of support for Web Standards it is highly recommended that you upgrade to a modern browser\n\n\n                    <ul>\n                        <li>\n                            <a href="http://www.google.com/chrome/">\n                                <img src="chrome.png" alt="">\n                                <div>Chrome</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.mozilla.org/en-US/firefox/new/">\n                                <img src="firefox.png" alt="">\n                                <div>Firefox</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.apple.com/safari/">\n                                <img src="safari.png" alt="">\n                                <div>Safari</div>\n                            </a>\n                        </li>\n                    </ul>\n\n                    <div class="iwi-skip">Skip & Continue</div>\n                </div>\n            </div>\n        <![endif]-->\n\n        <script>currentUiVersion = \'2018-04-16T18:35:51Z\'</script>\n        <script src="index_bundle-2018-04-16T18-35-51Z.js"></script>\n    <script>var hideStorageInfo = function() {var usage = document.getElementsByClassName("feh-usage");if(usage){usage[0].style.display = "none"} else setTimeout(hideStorageInfo, 100)}; setTimeout(hideStorageInfo, 100)</script></body>\n</html>\n';
krishna@escape:/tmp$ 
```

Now you copy the output and put it in nginx.config:
```
        location ~ ^(/minio/|/minio/.*/)$ {
                 if ($request_method !~ GET ) {
                    return 404;
                 }
                 proxy_set_header Host $http_host;
                 proxy_pass http://localhost:9000;
sub_filter '<!DOCTYPE html>\n<html>\n\n    <head>\n        <meta charset="UTF-8">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        <title>Minio Browser</title>\n        <link rel="stylesheet" href="loader.css" type="text/css">\n    </head>\n\n    <body>\n        <div class="page-load">\n            <div class="pl-inner">\n                <img src="logo.svg" alt="">\n            </div>\n        </div>\n        <div id="root"></div>\n\n        <!--[if lt IE 11]>\n            <div class="ie-warning">\n                <div class="iw-inner">\n                    <i class="iwi-icon fa fa-warning"></i>\n\n                    You are using Internet Explorer version 12.0 or lower. Due to security issues and lack of support for Web Standards it is highly recommended that you upgrade to a modern browser\n\n\n                    <ul>\n                        <li>\n                            <a href="http://www.google.com/chrome/">\n                                <img src="chrome.png" alt="">\n                                <div>Chrome</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.mozilla.org/en-US/firefox/new/">\n                                <img src="firefox.png" alt="">\n                                <div>Firefox</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.apple.com/safari/">\n                                <img src="safari.png" alt="">\n                                <div>Safari</div>\n                            </a>\n                        </li>\n                    </ul>\n\n                    <div class="iwi-skip">Skip & Continue</div>\n                </div>\n            </div>\n        <![endif]-->\n\n        <script>currentUiVersion = \'2018-04-16T18:35:51Z\'</script>\n        <script src="index_bundle-2018-04-16T18-35-51Z.js"></script>\n    </body>\n</html>\n' '<!DOCTYPE html>\n<html>\n\n    <head>\n        <meta charset="UTF-8">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        <title>Minio Browser</title>\n        <link rel="stylesheet" href="loader.css" type="text/css">\n    </head>\n\n    <body>\n        <div class="page-load">\n            <div class="pl-inner">\n                <img src="logo.svg" alt="">\n            </div>\n        </div>\n        <div id="root"></div>\n\n        <!--[if lt IE 11]>\n            <div class="ie-warning">\n                <div class="iw-inner">\n                    <i class="iwi-icon fa fa-warning"></i>\n\n                    You are using Internet Explorer version 12.0 or lower. Due to security issues and lack of support for Web Standards it is highly recommended that you upgrade to a modern browser\n\n\n                    <ul>\n                        <li>\n                            <a href="http://www.google.com/chrome/">\n                                <img src="chrome.png" alt="">\n                                <div>Chrome</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.mozilla.org/en-US/firefox/new/">\n                                <img src="firefox.png" alt="">\n                                <div>Firefox</div>\n                            </a>\n                        </li>\n                        <li>\n                            <a href="https://www.apple.com/safari/">\n                                <img src="safari.png" alt="">\n                                <div>Safari</div>\n                            </a>\n                        </li>\n                    </ul>\n\n                    <div class="iwi-skip">Skip & Continue</div>\n                </div>\n            </div>\n        <![endif]-->\n\n        <script>currentUiVersion = \'2018-04-16T18:35:51Z\'</script>\n        <script src="index_bundle-2018-04-16T18-35-51Z.js"></script>\n    <script>var hideStorageInfo = function() {var usage = document.getElementsByClassName("feh-usage");if(usage){usage[0].style.display = "none"} else setTimeout(hideStorageInfo, 100)}; setTimeout(hideStorageInfo, 100)</script></body>\n</html>\n';

        }
        location / {
                 proxy_set_header Host $http_host;
                 proxy_pass http://localhost:9000;
        }
```

nginx inserts a small JS script into index.html, this script hides the html element which shows the storage disk info.

**Comment by payne8** [comment]
@krishnasrinivas @harshavardhana I think I would prefer not to show it in the UI for multi-tenant. I understand adding extra options, especially for such a small thing, makes things complicated. I started looking into the zfs/btrfs options.

I know this is kind of a tangent but...
If I change a quota on a drive or expand the disk size in anyway does that mess up the cluster? https://github.com/minio/minio/issues/4712
https://github.com/minio/minio/issues/4364

I am under the impression I will need to set and forget the quotas and simply add instances for each tenant as they approach filling their quota. Sadly that makes for some heavier lifting on the part of my users. Plus unpredictability in usage requirements might lead to the risk of over/under provisioning.

**Comment by harshavardhana** [comment]
Extending underneath backends is not a problem .. @payne8 either in cluster or single filesystem mode.  Those bugs talk about that you cannot extend a cluster by adding more disks (disk paths)

**Comment by abperiasamy** [comment]
@krishnasrinivas  I am tempted to add support for JavaScript extensibility.

**Comment by krishnasrinivas** [comment]
@abperiasamy just ability to customize the theme and look? or JS extensibility?

**Comment by payne8** [comment]
> I was able to make the storage-info disappear by using the sub_filter nginx config.

@krishnasrinivas that is a very creative solution.

A custom CSS option would be more than sufficient for my needs (maybe overkill) and might add some really cool customization options for the same amount of work. I am not exactly sure how a user would provide the CSS though. Maybe by specifying a URL or file path on startup?

**Comment by nneul** [comment]
With other apps I've used, config would either just point to a file, or it would be something you place at a particular filename in the config directory. i.e. "user.css" and "user.js" - If the files are present, add handlers for outputting them and add the reference to them in the UI. Wouldn't even have to be a new 'option' in the CLI or configuration.

**Comment by krishnasrinivas** [comment]
What we decided was to bring a change to not show disk-information on the main page, but provide a button "calculate disk-usage" that calculates the `du` command style disk usage.

This will address both your use cases.

**Comment by nneul** [comment]
:+1: :+1: :+1:

**Comment by nneul** [comment]
(one thumb is degraded)

**Comment by kannappanr** [comment]
PRs #5976 and #5969 address this issue. They have been merged into the master, so closing this issue. Please feel free to open a new issue if you find anything wrong.
