### ISSUE TITLE
the new policy is not be supported by java sdk ?

### ISSUE THREAD

**Issue by Jamlee** [minio/minio#5768]
the newset policy is look like below:

https://github.com/minio/mc/blob/18ddd3925b366a730fdce63da303aefa7c25814e/cmd/access-perms.go#L33-L36

## Expected Behavior
i want set the policy download, but sdk not provide.

> Allowed policies are: [none, download, upload, public].

## Current Behavior
currently, the policy is : 

> Policy to apply, available types are [PolicyType.NONE, PolicyType.READ_ONLY, PolicyType.READ_WRITE, PolicyType.WRITE_ONLY].

**Comment by harshavardhana** [comment]
download is READ_ONLY,  upload is WRITE_ONLY and public is READ_WRITE

**Comment by Jamlee** [comment]
@harshavardhana Could i download my file without access key or presigned url ?

**Comment by harshavardhana** [comment]
Yes you can set READ_ONLY

**Comment by kannappanr** [comment]
@Jamlee Closing this issue as answered. Please feel free to re-open the issue, if you feel otherwise.
