### ISSUE TITLE
Minio object storage for application data

### ISSUE THREAD

**Issue by abhilash07** [minio/minio#5773]
Hi everyone deployed Minio on CF Market place using on-Demand-Broker and Service Adapter or
as Cloud Foundry Blobstore.
Thanks in Advance.
Abhilash S

https://github.com/minio/minio-boshrelease.git
https://github.com/minio/minio-boshrelease/issues/50
https://www.minio.io/cloudfoundry.html

**Comment by kannappanr** [comment]
@abhilash07 I see that the questions asked in minio/minio-boshrelease#50 have been answered. Closing the issue for now. Please feel free to re-open the issue if you feel otherwise.
