### ISSUE TITLE
[Feature] Make notifications configurable through the API

### ISSUE THREAD

**Issue by denismakogon** [minio/minio#5781]
Make notifications great (again?)
========================
Here's the thing. At this moment the notifications can be configured through the config file which makes them totally unflexible. So, is there any plans to enable notification configuration through the API?

## Cold start problem

More on the notifications. The way minio triggers webhook is not kind of useful.  Here's why assume you want to use a serverless function as the "reaction" (webhook) to the object event in store, so when minio starts it submits the HTTP request to the endpoint specified in the configuration, so you make the function do a "cold" start which is totally redundant because you minio forces developers to do more code to make safe processing of the cold start.

## Handshake mechanism instead of cold start

So, if the idea that stands behind the cold start is some sort of the handshake, so there has to be another way to do so. The good example would be Azure Event Grid topic subscribers, azure posts a validation event so the webhook subscriber should reply with the corresponding data derived from the validation event data.

## Dead webhook problem

Webhook is dead, how should i fix that on minio side? Again, need to modify the config.

# Key statements

 - Notifications are good, but not.
 - Config file-based definition, no thanks.
 - Object pollsters (continues HTTP GET on bucket/object can die with the rate limits), so there has to be another way to work with "reactions" to object modifications(any of CRUD).

There might be more use cases for the notifications, but it is a real area for improvements.
Thoughts?

**Comment by harshavardhana** [comment]
> Here's the thing. At this moment the notifications can be configured through the config file which makes them totally unflexible. So, is there any plans to enable notification configuration through the API?

First, you configure targets with `config.json` then the server prints ARNs and then you use notification APIs in SDKs to configure these targets to send notifications to.

You can configure the targets in `config.json` also by using https://github.com/minio/minio/blob/master/pkg/madmin/API.md#SetConfig by uploading a new `config.json`

**Comment by harshavardhana** [comment]
> More on the notifications. The way minio triggers webhook is not kind of useful. Here's why assume you want to use a serverless function as the "reaction" (webhook) to the object event in store, so when minio starts it submits the HTTP request to the endpoint specified in the configuration, so you make the function do a "cold" start which is totally redundant because you minio forces developers to do more code to make safe processing of the cold start.

Minio notification implementation is compatible with AWS S3 Bucket notification behavior it is not meant to do anything else beyond that, so any change in behavior means we are not AWS S3 Bucket notification anymore should be considered as a new feature. 

Feel to submit a new notification implementation here `pkg/event/target` if you need it to do some specialized work.

**Comment by denismakogon** [comment]
@harshavardhana thanks for the reply, okay, you say that minio is compliant. But i don't see any equivalent to the notification configurations similar to S3 https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-notification-configuration.html.
The link that you've posted (https://github.com/minio/minio/blob/master/pkg/madmin/API.md#SetConfig) doesn't look similar to API and AWS S3 exposes to configure notifications.

If i am wrong, please tell me how to configure the notifications config with aws-sdk-go?

**Comment by harshavardhana** [comment]
> The link that you've posted (https://github.com/minio/minio/blob/master/pkg/madmin/API.md#SetConfig) doesn't look similar to API and AWS S3 exposes to configure notifications.

This API suggestion was to replace `config.json` in-case you are changing the targets, I did not mention that this is an S3 API what I meant this is for two things let me clarify. In minio just like AWS S3, there are two steps to notifications

- Configure the target i.e by adding credentials, endpoints etc in `config.json` - this is analogous to you creating, for example, an AWS SQS service.
- Once the target is configured you will be able to see ARNs, similar to how you will be able to in AWS as well. 

once these ARNs are available you can use AWS S3 compatible bucket notification API - all our SDKs support this 

- https://docs.minio.io/docs/golang-client-api-reference#SetBucketNotification (minio-go)
- https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutBucketNotification (aws-sdk-go)

To make it simpler we have a comprehensive guide for each of the supported targets https://docs.minio.io/docs/minio-bucket-notification-guide which use a simplified way by using our client-side tool `mc` which makes it easier for many users.

**Comment by harshavardhana** [comment]
This bug can be closed @deekoder @kannappanr

**Comment by kannappanr** [comment]
Closing based on suggestion from @harshavardhana. @denismakogon Please feel free to open an issue if you have any other question.
