### ISSUE TITLE
[Feature Request] Multi-site EC, 3+ DC, no Mirror

### ISSUE THREAD

**Issue by vRobM** [minio/minio#5782]
What's needed for EC across 3 DCs w/o replication with 1 site outage tolerance?

**Comment by deekoder** [comment]
@vRobM - Please can you elaborate what your ask is. It's not super clear to us from the above description.

**Comment by vRobM** [comment]
Which part is confusing?
3 separate datacenters (lets say 50ms apart)
no replication between datacenters (no mirror)
use of appropriate error correcting codes to spread data across the 3 sites, so that any 1 site outage results in recomputed data that is still readable from an available node.

**Comment by deekoder** [comment]
@vRobM you could run minio in distributed mode where you have say 4 nodes in DC#1, 4 nodes in DC #2, 4 nodes in DC#3 and so on. Since we have to keep them in sync, we need to make sure they have low latency (say 20ms), if you dont have that, it's better to use replication/mirroring.

**Comment by deekoder** [comment]
I'll go ahead and close this issue for now. We will ping you again when we do the next set of enhancements.
