### ISSUE TITLE
Docker container cannot seem to talk to Minio internally?

### ISSUE THREAD

**Issue by zGrav** [minio/minio#5789]
Hey folks,

I'm trying to access my Minio container through a Node application running in another container, Docker resolves the IP just fine, but fails to actually connect to Minio with a 503 Service Unavailable.

`/usr/src/app # ping minio_1
PING minio_1 (172.19.0.7): 56 data bytes
64 bytes from 172.19.0.7: seq=0 ttl=64 time=0.116 ms
64 bytes from 172.19.0.7: seq=1 ttl=64 time=0.161 ms
64 bytes from 172.19.0.7: seq=2 ttl=64 time=0.164 ms
^C
--- minio_1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.116/0.147/0.164 ms
/usr/src/app # wget 172.19.0.7:9000/minio/login
Connecting to 172.19.0.7:9000 (172.19.0.7:9000)
wget: server returned error: HTTP/1.1 403 Forbidden`

The following GET below times out.

`"http://172.19.0.7:9000/assets/default/logo.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx%2F20180408%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180408T210924Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=xxx"`

## Expected Behavior
wget should not return forbidden, Node application should fetch data from Minio under Docker as intended and not return CONN_TIME_OUT.

## Current Behavior
HTTP times out on retrieving data from Minio under Docker.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Build docker-compose that runs a small Node app and Minio
2. Try to connect Node app to Minio.

## Context
Trying to simplify asset management using Minio. Minio/Docker runs great when the Node part is not Dockerized :(

## Your Environment
* Version used (`minio version`): `/usr/bin # minio version
Version: 2018-04-04T05:20:54Z
Release-Tag: RELEASE.2018-04-04T05-20-54Z
Commit-ID: 85a57d20210eb867b1c023e024cc4391d5ac5685`
* Environment name and version (e.g. nginx 1.9.1): `Node 8.11.1`
* Server type and version: `Docker 18.03.0`
* Operating System and version (`uname -a`): `macOS High Sierra 10.13.3 17D47 x86_64`
* Link to your project: `N/A`

**Comment by harshavardhana** [comment]
Can you share the docker compose file?

**Comment by zGrav** [comment]
@harshavardhana 

```
ms-console:
    image: xxx
    ports:
      - "8088:8088"
    environment:
      DEBUG: ${DEBUG}
    depends_on:
      - mongo
      - minio

  minio:
    image: minio/minio
    command: ["server", "/export"]
    ports:
      - "9001:9000"
    volumes:
      - ./assets:/export
      - ./data/minio:/root/.minio
    environment:
      - MINIO_DOCKER_NAME=minio
      - MINIO_ACCESS_KEY=Minio
      - MINIO_SECRET_KEY=xxx

**Comment by zGrav** [comment]
Same issue as https://github.com/minio/minio-js/issues/514, closing.
