### ISSUE TITLE
MC heal is not healing files

### ISSUE THREAD

**Issue by masafif** [minio/minio#5799]
After server shutdown not properly...
MC heal is not healing our files. The object size is have same with the original, but not recognize it. The JPG file is not recognize as image file. The txt file have some missing character 
 
root@earth:/home/xxx# mc admin heal -f -r local/newsroom/foto
 â  newsroom/foto/upload/images-47/20140725194232-361.jpg
    3/453,309 objects; 335 GiB in 20h26m22s
    ââââââââââ¬ââââââââââ¬ââââââââââââââââââââââ
    â Green  â 453,312 â 100.0% ââââââââââââ â
    â Yellow â       0 â   0.0%              â
    â Red    â       0 â   0.0%              â
    â Grey   â       0 â   0.0%              â
    ââââââââââ´ââââââââââ´ââââââââââââââââââââââ

 
![20101012184751-553](https://user-images.githubusercontent.com/33485010/38535191-9748d6d0-3cac-11e8-886d-80d15f0beb64.jpg)

![20140721165032-353](https://user-images.githubusercontent.com/33485010/38535523-1532f6c4-3cae-11e8-83a1-11bd10baff47.jpg)

Environment
* MC version : Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4
* Minio version :
Version: 2018-04-04T05:20:54Z
Release-Tag: RELEASE.2018-04-04T05-20-54Z
Commit-ID: 85a57d20210eb867b1c023e024cc4391d5ac5685

* Operating System and version :
Linux mars 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

MINIO_VOLUMES=http://10.10.1.132/home http://10.10.1.132/home2 \
             http://10.10.1.132/home3 http://10.10.1.132/home4 \
             http://10.10.1.133/home http://10.10.1.133/home2 \
             http://10.10.1.133/home3 http://10.10.1.133/home4 \
             http://10.10.1.134/home http://10.10.1.134/home2 \
             http://10.10.1.134/home3 http://10.10.1.134/home4 \
             http://10.10.1.135/home http://10.10.1.135/home2 \
             http://10.10.1.135/home3 http://10.10.1.135/home4

MINIO_OPTS="--address :9000"

/root/config/.json 
 "local": {
                        "url": "http://10.10.1.134:9000",
                        "accessKey": "xxxxxxxxxxx",
                        "secretKey": "xxxxxxxxxxx",
                        "api": "S3v4",
                        "lookup": "auto"
               }

**Comment by harshavardhana** [comment]
@masafif I have tried to reproduce - I cannot seem to reproduce the problem. Do you have any ideas on what led to this situation that we can replicate?

**Comment by masafif** [comment]
@harshavardhana did you reproduce from the file i have uploaded and can open the images?

I try to change config for json like this. @y4m4 said only need one server for heal. Actually I have 4 minio server and using NGINX Proxy. But now, i try to use one server in ip 10.10.1.132    

/root/config/.json
"local": {
"url": "http://10.10.1.132:9000",
"accessKey": "xxxxxxxxxxx",
"secretKey": "xxxxxxxxxxx",
"api": "S3v4",
"lookup": "auto"
}

I have tried using the command : mc admin heal -r local/test/ 
root@earth:/home/afif# mc admin heal -r local/test/
 ◑  test/images/sunset-gedong-lasem.JPG
    0/1 objects; 90 KiB in 2s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘

Seem success to heal but I still can not see the images.......I don't have an idea how to make this situation same with your situation when reproduce the files.

**Comment by harshavardhana** [comment]
@masafif from what I can see the disks were not properly arranged when you deleted the `format.json` and we had to replace them. Locally I have tried multiple times with different images etc I don't see a problem. So it must be that disks were arranged wrong.

**Comment by masafif** [comment]
@harshavardhana, is it still possible to make disks work properly again ?
After recreate format.json actually minio server is normal...but the old data is broken

**Comment by harshavardhana** [comment]
Yes the problem is that order is lost. It is possible to recreate the format.json again but I guess those images are lost.

**Comment by harshavardhana** [comment]
@masafif should we close this issue?

**Comment by harshavardhana** [comment]
Closing this for now... @masafif feel free to re-open.
