### ISSUE TITLE
[gateway/gcs] Content-Type/Content-Encoding lost when updating an objects custom metadata

### ISSUE THREAD

**Issue by wd256** [minio/minio#5800]
## Expected Behavior

When copying an object over itself for the purpose of updating its metadata I expect that the Content-Type/Content-Encoding of the object is preserved.

## Current Behavior
The new user-defined metadata is applied correctly however any Content-Type/Content-Encoding assigned to the object is lost.

## Steps to Reproduce (for bugs)

1. Upload an object
2. Use the AWS CLI to perform a 'head-object' and observe that the object has a Content-Type set
3. Use the AWS CLI to perform a 'copy-object' to update the objects custom metadata (copying it over itself)
4. Use the AWS CLI to perform a 'head-object' and observe that the object's Content-Type has been lost

## Context

I would like to be able to update an objects custom/user-defined metadata without losing other metadata which has been assigned to the object.

## Your Environment
minio version: master (commit ae8e863ff41dbc6ef5a85849a21bc05c1401079d)
OS: Linux amd64

**Comment by wd256** [comment]
I've just tested the other user configurable object metadata which GCS supports (Cache-Control, Content-Disposition and Content-Language) and found that it is cleared after the copy as well.

**Comment by poornas** [comment]
@wd256 , I was able to repro this issue and am sending in a fix to copy the standard metadata you have mentioned above during a copy operation to the destination side. However, it may not help with what you are trying to achieve.

> I would like to be able to update an objects custom/user-defined metadata without losing other metadata which has been assigned to the object.

From above statement, it seems you would like to preserve original metadata as well as add new metadata during the copy-object operation where src and dest objects are the same. As per [s3 spec](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html), if you specify metadata-directive REPLACE, the metadata specified with the --metadata flag will be used and it will not overlay this on the metadata of the original object.  
```
aws --endpoint http://192.168.1.167:9000  s3api copy-object  --copy-source tbucket123/srcObject  --key srcObject --bucket tbucket123 --metadata "{\"mykey\":\"myvalue\"}" --metadata-directive REPLACE
```
For example, after above command , the only metadata on the object will  be mykey:myvalue

**Comment by wd256** [comment]
@poornas, thanks for taking a look at the issue. The core of the problem for me is that I don't see a way using the current GCS ObjectLayer implementation to be able to update the Custom metadata for an object while preserving its other user editable metadata (ContentType, ContentEncoding, ect..).

gcsGateway's CopyObject implementation only sets the object's Metadata attribute which is used to apply Custom metadata. For example, if the UserDefined map contains an entry for 'Content-Type', the objects Content-Type attribute isn't set but instead it receives a 'Content-Type ' custom metadata entry. After copying an object this way, this is how it looks in the GCP Storage Browser:

![image](https://user-images.githubusercontent.com/8491917/38614222-ab67578a-3dcf-11e8-8476-d026c48692dc.png)

**Comment by poornas** [comment]
@wd256, the current GCS gateway implementation follows S3 spec, which does not persist editable metadata from src side in a CopyObject call. You could specify the editable metadata with AWS CLI's copy-object command by specifying the flags like --content-type, in which case you will get the desired outcome. You might want to consider using boto if you want to do it programmatically.

```
import boto3

s3 = boto3.client('s3')
data = open('temp.go','rb')
bucket = 'my-bucket'
key = 'testfile'
s3.put_object(Bucket=bucket,Key=key, Body=data, ContentLanguage='fr', ContentType="application/custom",Metadata={"my-key":"my-value"})
# get original metadata and editable metadata
response = s3.head_object(Bucket=bucket, Key=key)
content_lang = response['ContentLanguage']
content_type = response['ContentType']
meta = response['Metadata']
meta["new-key"] = "new-value"

# Copies object located in mybucket at mykey
# to the location otherbucket at otherkey
s3.copy_object(
    CopySource=bucket + '/' + key,
    Bucket=bucket, 
    Key=key,
    Metadata=meta,
    ContentType=content_type,
    ContentLanguage=content_lang,
    MetadataDirective='REPLACE'
)
response = s3.head_object(Bucket=bucket, Key=key)
print(response)
```

**Comment by wd256** [comment]
@poornas, the issue still occurs when using the AWS CLI with the copy-object comand and specifying --content-type / --content-encoding. The ContentType and ContentEncoding attributes on the object are removed and entries for "content-type" and "content-encoding" are placed into the Custom metadata of the object instead.

This isn't such a problem if you are only accessing the object again through minio as minio sets all the Custom metadata entries as response headers.  So if I use the AWS CLI to perform a head-object after the copy I see:
```
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 12 Apr 2018 06:10:26 GMT",
    "ContentLength": 7,
    "ETag": "\"2302831401-1\"",
    "ContentEncoding": "identity",
    "ContentType": "text/plain",
    "Metadata": {}
}
```

This looks correct, however if I fetch the object info using gsutil, I see the true state of the object:

```
    Creation time:          Thu, 12 Apr 2018 06:10:26 GMT
    Update time:            Thu, 12 Apr 2018 06:10:26 GMT
    Storage class:          STANDARD
    Content-Length:         7
    Content-Type:           None
    Metadata:               
        content-type:       text/plain
        content-encoding:   identity
    Hash (crc32c):          iUJrKQ==
    Hash (md5):             qGhQ3rJ0LsPLQVGOJqotiQ==
    ETag:                   COTM5uSJtNoCEAE=
    Generation:             1523513426552420
    Metageneration:         1
```

Note the Content-Type of the object is None and no Content-Encoding is set. The object has Metadata entries for "content-type" and "content-encoding" instead.

**Comment by poornas** [comment]
@wd256,which version of minio are you using? If you are using the commit from my pull request, I believe now that the PR is not needed at all. If metadata replace directive is specified, the standard metadata in http headers are used during a copy with replace operation. You will have to make sure to get original metadata, update in place and then pass it to aws cli copy-object command as well as ensure that the --content-type / --content-encoding flags are set. I updated the boto script above as well, in case you want to use that.

**Comment by wd256** [comment]
@poornas, I'm able to reproduce the issue when using master and your gcs branch.

The steps to reproduce the issue are as follows:

1) Use gsutil to upload an object and specify the Content-Type, Content-Language.
```
gsutil -h "Content-Type:text/plain" -h "Content-Language:en" cp testfile.txt gs://testbucket/testfile.txt
```
2) Use gsutil to retrieve the object's metadata.
```
gsutil stat gs://testbucket/testfile.txt
```
![image](https://user-images.githubusercontent.com/8491917/38795444-9b8fdce0-419b-11e8-9e47-e8cf192e7531.png)

Observe the Content-Language and Content-Type are defined for the object and gsutil lists them as primary attributes of the object and not beneath a "Metadata" heading which is how gsutil displays items which are part of the objects [Custom metadata](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#custom-metadata).

3) Attempt to add an item of Custom metadata while preserving the Content-Type and Content-Language of the object using the following aws-cli command via the Minio gateway:

```
aws --endpoint-url http://127.0.0.1:9000 s3api copy-object --copy-source testbucket/testfile.txt --bucket testbucket --key testfile.txt --metadata-directive REPLACE --content-type text/plain --content-language en --metadata custom-meta=abc123
```

4) Use gsutil to retrieve the object's metadata.
```
gsutil stat gs://testbucket/testfile.txt
```
![image](https://user-images.githubusercontent.com/8491917/38795468-b592d84a-419b-11e8-96cb-847e53a0a876.png)

Observe that the Content-Type and Content-Language attributes of the object have now been cleared and entries in the Custom metadata of the object for "content-type" and "content-language" have been created instead which is not correct. Content-Type and Content-Language should not be stored as items within the objects Custom metadata attribute.

I've created a branch which uses the metadata provided to the GCS object layer to set the correct object attributes.  When repeating the above steps using this branch, the output for step 4 is as follows:

![image](https://user-images.githubusercontent.com/8491917/38796226-1a282574-419e-11e8-9704-b525152ff9ff.png)
