### ISSUE TITLE
[SSE]: SSE handling for gateway needs decision

### ISSUE THREAD

**Issue by aead** [minio/minio#5801]
The handling of SSE requests for gateway backend needs decision.
Currently the server silently performs SSE requests without encryption whenever a client sends a SSE request. 

## Expected Behavior
Not obvious - needs decision

## Current Behavior
Server handles SSE requests like normal requests

## Possible Solution

There are multiple solutions:
 1. The server could try to convert AWS S3 SSE to gateway-<backend> SSE.
    If this fails - e.g. because the backend does not support SSE - the server would be
   supposed to fail.
 2. The server could work as encryption gateway, terminate SSE and upload only encrypted content to
     the backend. This would create our custom format on the backend and may break interoperability
    between SDKs. 
 3. Disable SSE for gateway completely **and** fail on such requests. 

## Context
SSE, #5511 

## Your Environment
master

@harshavardhana @abperiasamy

**Comment by harshavardhana** [comment]
I prefer the first option.

**Comment by aead** [comment]
@deekoder Resolved by meeting discussion, can be closed.

**Comment by kannappanr** [comment]
Closing this issue as resolved. Refer to #6267 for the decision
