### ISSUE TITLE
cleanup fs.json from .minio.sys/buckets

### ISSUE THREAD

**Issue by glensc** [minio/minio#5803]
Is there way to cleanup `fs.json` files from `.minio.sys/buckets`. those seem to be growing endlessly. my minio storage is backend for private docker registry.

```
$ find data/.minio.sys/buckets/ -type f | wc -l
2874
```

this is only for a week of operation.

## Environment

* minio/minio:RELEASE.2018-04-04T05-20-54Z docker image

**Comment by glensc** [comment]
my previous version for same data running older minio (2017 something):

```
$ du export/.minio.sys/ -s
3,2G    export/.minio.sys/

$ find  export/.minio.sys/ -type f | wc -l
37743
```

didn't report with the old version, because this could be fixed already.

**Comment by krishnasrinivas** [comment]
@glensc each object will have a corresponding fs.json which holds the object's ETag and other metadata.

```
$ find data/.minio.sys/buckets/ -type f | wc -l
2874
```

If you have around 2800 objects, you will have 2800 fs.json

Can you provide the output of
```
du -h export/.minio.sys/buckets
du -h export/.minio.sys/multipart
du -h export/.minio.sys/tmp
```

(Just to make sure that it looks fine)

**Comment by glensc** [comment]
(added `-s` not to leak too much details)

```
$ du -hs data/.minio.sys/buckets
13M     data/.minio.sys/buckets

$ du -hs data/.minio.sys/multipart
144K    data/.minio.sys/multipart

$ du -hs data/.minio.sys/tmp
0       data/.minio.sys/tmp

$ find data/.minio.sys/buckets/ -type f | wc -l
2949
```

but, is it okay (or when it is okay) to remove `.minio.sys`? i migrated `export` -> `data` dir 5 day ago, and did not preserve `.minio.sys` dir, as it seem to contain 3GiB of leftover files. as i looked briefly on the files and seems ok to drop them when no active uploads are in progress.

**Comment by krishnasrinivas** [comment]
Your du output looks reasonable and normal.

data/.minio.sys/buckets -> contains one fs.json per object - fs.json contains etag and user given metadata - you can delete this if you dont care about etag or metadata

data/.minio.sys/multipart -> contains multipart parts, it will be auto cleaned by minio (old files will be purged)

data/.minio.sys/tmp -> tmp files location, cleanedup by minio everytime when it starts

**Comment by harshavardhana** [comment]
@krishnasrinivas we can close this issue?

**Comment by krishnasrinivas** [comment]
@harshavardhana I think so.

@glensc please re-open if you would like to.
