### ISSUE TITLE
minio puppet module and minio server fight about config file

### ISSUE THREAD

**Issue by ZyanKLee** [minio/minio#5804]
## Expected Behavior

minio server should not rewrite its config file.

## Current Behavior

when creating a config file (minified json) using puppet module [kogitoapp/puppet-minio](/kogitoapp/puppet-minio), minio server rewrites its config file to prettyfied json on the subsequent restart.

On the next run of puppet the config file is changed to what this puppet-minio thinks is a valid config file (minified json) and at the subsequent restart of minio server this file is getting reverted to prettyfied json.

This circle never stops.

## Possible Solution

* either let minio NOT touch its file at all
* or provide an option to disable this behaviour at start-time (`--no-config-rewriting` or similar)

## Steps to Reproduce (for bugs)

1. use puppet with [kogitoapp/puppet-minio] to install and manage minio server
2. run puppet multiple times
3. enjoy the spectacle

## Context

There is an issue ticket at kogitoapp/puppet-minio/issues/6 as well

## Your Environment

* Version used (`minio version`): RELEASE.2018-03-12T21-25-28Z
* Server type and version: ubuntu xenial 16.04
* Operating System and version (`uname -a`):ubuntu xenial 16.04
* Puppet: 4.10
* Ruby: ruby 2.1.9p490

**Comment by harshavardhana** [comment]
Minio server auto migrates it's own config file when a new version is available. Puppet shouldn't be managing Minio server config.json neither it should interfere with what Minio wants to do. We have good reasons to migrate the config file to keep it consistent with the new versions. If puppet module sticks to a Minio server config version it should stick to the latest after each releases. NOTE: Minio server doesn't migrate if the config is latest and it knows the version. This is how we do with ansible, helm chart and mesos. I don't see why puppet would be special.

**Comment by deekoder** [comment]
IMO this file need not be minified at all. It's not like a js file that is included and not modified frequently and hence a great candidate for minification. Our users have to edit this file and change settings (eg. set bucket notifications) to let minio server know about their preferences for minio server. Puppet could exclude minifying this file.

**Comment by ZyanKLee** [comment]
I see. 

@danielsreichenbach I suggested to use augeas to modify this config. I think this would be the best way to go, now that I know these facts.

**Comment by nitisht** [comment]
@ZyanKLee closing the issue as answered, feel free to reopen or reach out to us on Slack for further questions.
