### ISSUE TITLE
Error: Invalid command line arguments server=‘:9000’, args=[/mnt/export1/ /mnt/export2/]

### ISSUE THREAD

**Issue by abhilash07** [minio/minio#5808]
hi everyone i am new to minio, 

i want to deploy minio on ubuntu 16.04 on persistent 2 disks (sdb1 & sdc1).
![screen shot 2018-04-11 at 11 07 25 am](https://user-images.githubusercontent.com/10971841/38592752-c2943c90-3d78-11e8-9204-1ceb890844d5.png)

when i am running on single disk everything is fine 
./minio server /mnt/export1
But i want to run minio on distributed (erasure code), unfortunately i encounter below error.
./minio server /mnt/export1/ /mnt/export2/
Error: Invalid command line arguments server=‘:9000’, args=[/mnt/export1/ /mnt/export2/]

./minio server http://10.0.0.5:9000/mnt/export1 http://10.0.0.5:9000/mnt/export2
Error: Invalid command line arguments server=‘:9000’, args=[http://10.0.0.5:9000/mnt/export1 http://10.0.0.5:9000/mnt/export2]

Any suggestions for this error ???

Thanks in Advance

**Comment by nitisht** [comment]
@abhilash07 you need at least 4 disks to start Minio server in erasure coded mode. You can also refer to the docs : https://docs.minio.io/docs/minio-erasure-code-quickstart-guide , https://docs.minio.io/docs/distributed-minio-quickstart-guide

**Comment by abhilash07** [comment]
@nitisht thanks for your quick response, is it my execution is right or should i try anu another execution command ???
Thanks in Advance.

**Comment by nitisht** [comment]
How many servers you have? If you have just one server and all disks are on that server, you should use 
`./minio server /mnt/export1 /mnt/export2 /mnt/export3 /mnt/export4`

You'll need to create mounts `export3` and `export4` if you dont have it already

**Comment by abhilash07** [comment]
@nitisht  thanks for your suggestions. It works.
