### ISSUE TITLE
Gateway: Multipart upload on azure gateway with Minio browser not working

### ISSUE THREAD

**Issue by abhilash07** [minio/minio#5809]
i am trying to deploy minio using Azure Blobstore

export MINIO_ACCESS_KEY=xxxxxx 
export MINIO_SECRET_KEY=xxxxxx

./minio gateway azure

![screen shot 2018-04-11 at 6 59 47 pm](https://user-images.githubusercontent.com/10971841/38609990-8c1070b6-3dba-11e8-9722-0801c62375d4.png)

Second error is how to overcome the object size file uploading to minio azure gateway.

![screen shot 2018-04-11 at 7 04 19 pm](https://user-images.githubusercontent.com/10971841/38610224-2b772992-3dbb-11e8-86fc-4f09c7c9be97.png)

Any suggestions to overcome this error's

Thanks in Advance

**Comment by nitisht** [comment]
@abhilash07 Azure gateway supports only `read-only` policy due to Azure API limitation. Please refer: https://github.com/minio/minio/blob/master/docs/gateway/azure.md#known-limitations

**Comment by nitisht** [comment]
Can you let us know what is the object size being uploaded? Also, SDK and Minio server version in use.

**Comment by abhilash07** [comment]
@nitisht thanks for your information, and the File size i uploaded is  349MB. Please refer below screen short for minio server version and SDK.
![screen shot 2018-04-12 at 8 26 02 am](https://user-images.githubusercontent.com/10971841/38648268-44aec6f2-3e2b-11e8-8b47-1285330df2f4.png)

More Over i can upload 200MB file

Thanks in Advance.

**Comment by nitisht** [comment]
Just to clarify, you use the Minio browser to upload the 349 MB File?

**Comment by abhilash07** [comment]
@nitisht, yes i use minio browser to upload the 349 MB File!!!

**Comment by nitisht** [comment]
okay, thanks let me try to reproduce this locally and get back

**Comment by nitisht** [comment]
I can confirm this issue @abhilash07 . Will have a fix for this soon

**Comment by abhilash07** [comment]
@nitisht thank you so much for quick response and suggestions. Good luck

**Comment by deekoder** [comment]
@kmkanagaraj increasing priority of this issue.

**Comment by kmkanagaraj** [comment]
From azure `Put Blob` documentation https://docs.microsoft.com/en-us/rest/api/storageservices/Put-Blob?redirectedfrom=MSDN#remarks
> If you attempt to upload a block blob that is larger than 256 MB for version 2016-05-31 and later, and 64 MB for older versions, or a page blob larger than 8 TB, the service returns status code 413 (Request Entity Too Large). The Blob service also returns additional information about the error in the response, including the maximum blob size permitted in bytes.

Currently the browser and `web_handlers.go` doesn't have support for multi part upload. 
We need to enhance `web_handlers.go` to use `NewMultipartUpload` instead `PutObject` when the object is bigger than certain size.

**Comment by harshavardhana** [comment]
> Currently the browser and web_handlers.go doesn't have support for multipart upload.
> We need to enhance web_handlers.go to use multipart upload instead PutObject when the object is bigger than a certain size.

https://github.com/minio/minio/blob/master/cmd/gateway/azure/gateway-azure.go#L762 - if our PutObject code supported what we do in PutObjectPart it is possible to do this without using the multipart logic. Since our single PutObject already supports up to 5TiB. 

For now the workaround is simply to use a CLI tool like `mc` or `s3cmd` @abhilash07

**Comment by abhilash07** [comment]
@nitisht, @kmkanagaraj, @harshavardhana thanks for your suggestions.

**Comment by deekoder** [comment]
Closing as a won't fix for now, since its got an acceptable workaround for now.
