### ISSUE TITLE
Browser: Minio Browser not looking so good in Firefox

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5811]
## Expected Behavior
Same rendering as Google Chrome

## Current Behavior
![sc-ff](https://user-images.githubusercontent.com/283197/38647799-ea316a50-3da2-11e8-868c-e35b6ee1a5c2.png)

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
Open http://minio_server_address/ in Firefox 

## Context
Fixing bug

## Your Environment
minio master: 650c6ee8fb9109a664a3305672683caf34c7e631
Firefox version: Mozilla Firefox 52.7.3

**Comment by harshavardhana** [comment]
// cc @kmkanagaraj @rushenn
