### ISSUE TITLE
`UUID on positions 0:0 do not match with`

### ISSUE THREAD

**Issue by zerkms** [minio/minio#5826]
Steps to reproduce

1. Create 4 nodes cluster (m1, m2, m3, m4)
2. Shut down m1
3. From m4 run: `mc admin heal --json -r m4`
4. Start m1

Error observed:

```
format error: UUID on positions 0:0 do not match with, expected ffffffff-ffff-ffff-ffff-ffffffffffff got c2bcd446-5fe4-4498-b262-d1c41445699c
```
Version affected: `RELEASE.2018-04-12T23-41-09Z`

**Comment by harshavardhana** [comment]
Since you are attempting a heal when a disk is offline, that disk is fully ignored on purpose. Once it's ignored you are free to heal all the objects as needed to the available disks.. when the disk is brought back it is rejected because we do not know where this disk came from - it could be a malicious attempt to corrupt the data etc or a misplaced drive from some other cluster.

**Comment by zerkms** [comment]
That's correct, and it means that minio cannot gurantee the erasure code works properly, since https://github.com/minio/minio/issues/5825

Which means - silent data loss. Or broken node. Whichever is more acceptable (while `cluster` term probably means both should be addressed automatically)

**Comment by zerkms** [comment]
After thinking about it for some time, would this be a **safe** way to recover all nodes in cluster for the following scenario:

1. Create 4 nodes cluster (m1-m4)
2. Shut down m1
3. Upload a file
4. Start m1
5. Shut down m2
6. From m1 run `mc admin heal --json -r m1`
7. Start m2 (now it's broken, due to different UUIDs)

So for the step 8 to recover m2, do I have to remove **everything** and heal (it could involve a lot of IO to re-download and recompute everything), or is it safe to just remove `.minio.sys`?

**Comment by harshavardhana** [comment]
@zerkms sorry to get back on this late, what you found here is a bug. healing when only just disks are offline shouldn't edit the `format.json` entries. Healing should invoke itself when at least one unformatted disks are found.
