### ISSUE TITLE
Distributed minio does not start with hostnames when is used inside lxd

### ISSUE THREAD

**Issue by zerkms** [minio/minio#5832]
Steps to reproduce, including configuring lxd:

1. Install lxd (OS-specific, trivial)
2. `lxc launch ubuntu:xenial minio-1` (up to minio-4)
3. setup DNS to resolve your hostnames to IPs of LXD containers
4. `lxc exec minio-1 bash`
5. download minio, edit `config.json` if necessary
6. try to start minio in distributed mode

2 attempts are following, with implicit and explicit server address
```
$ /usr/local/bin/minio server --config-dir=/path/to/config/dir.minio http://minio-1.company.tld/srv/minio http://minio-2.company.tld/srv/minio http://minio-3.company.tld/srv/minio http://minio-4.company.tld/srv/minio
Error: Invalid address ‘minio-4.company.tld:9000’ in command line argument.
```

```
$ /usr/local/bin/minio server --address minio-4.company.tld:9000 --config-dir=/path/to/config/dir.minio http://minio-1.company.tld/srv/minio http://minio-2.company.tld/srv/minio http://minio-3.company.tld/srv/minio http://minio-4.company.tld/srv/minio
Error: Invalid address ‘minio-4.company.tld:9000’ in command line argument.
```

With IP the same configuration starts with no issues. Even more: you only need to specify the current host with IP, remote disks may still use hostnames (but it's a wrong configuration, so it was tried just for test).

**Comment by harshavardhana** [comment]
I followed the steps to run in lxc and I am able to run minio distributed successfully as an lxc container. 

```
 MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio server http://minio1/data1 http://minio2/data1 http://minio1/data2 http://minio2/data2

Drive Capacity: 25 GiB Free, 26 GiB Total
Status:         4 Online, 0 Offline. 

Endpoint:  http://10.96.51.101:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://10.96.51.101:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.96.51.101:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

I am curious to know how were the DNS entries made, were they made directly in the container under `/etc/hosts` or do you have a centralized mechanism for it?

**Comment by zerkms** [comment]
In my case it's a local network DNS server

**Comment by harshavardhana** [comment]
> In my case it's a local network DNS server

I am not sure how the DNS was resolving to, what was your network address subnet for lxc containers?. Here is my local config.  

```
sudo lxc network show minio
config:
  ipv4.address: 10.96.51.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:fde5:ebfc:12f5::1/64
  ipv6.nat: "true"
description: ""
name: minio
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```

**Comment by zerkms** [comment]
I don't have them at the moment, but those containers are network-reachable: my whole infrastructure runs hundreds of lxd containers. The network is not nat'ted, all containers addresses are directly routable.

**Comment by harshavardhana** [comment]
> I don't have them at the moment, but those containers are network-reachable: my whole infrastructure runs hundreds of lxd containers. The network is not nat'ted, all containers addresses are directly routable.

The only way the above message can appear is when one of the DNS address couldn't be resolved, is the DNS nameserver updated in your containers? i.e perhaps /etc/resolv.conf resolves to the right DNS etc.  Let me know if you do a have a setup perhaps we can figure out why it would be a problem.

The error message improvement we are fixing in a separate PR which would explain the cause correctly.

**Comment by harshavardhana** [comment]
I am going to close this for now, if you can reproduce it again do let me know. Perhaps I can replicate the same setup, for now my local setup is working fine with DNS entries.
