### ISSUE TITLE
Getting errors "Error: file access denied" and "Error: stat no such file or directory"

### ISSUE THREAD

**Issue by salsadoom** [minio/minio#5833]
Some files don't appear to be uploading correctly. I haven't been able to figure out why or any pattern to which files don't upload correctly. The files **seem** to actually be there, but I get errors in the logs saying they aren't. Confusing.

## Expected Behavior

I would expect my files to upload correctly, and the logs not output "Error: file access denied" and "Error: stat /storage/minio/mastodon/custom_emojis/images/000/000/017: no such file or directory". But those directories and files ARE there! This is for usage with mastodon.social in the end, but at this point I'm just using mc to mirror files. When I do connect mastodon to the bucket, it fails with a 500 internal server error. I imagine that'll go away when the issue with mc is fixed though.

`Apr 16 16:56:00 media minio[3905]: API: PutBucketPolicy(bucket=mastodon)
Apr 16 16:56:00 media minio[3905]: Time: 16:56:00 CST 04/16/2018
Apr 16 16:56:00 media minio[3905]: RemoteHost: 23.94.27.144:45580
Apr 16 16:56:00 media minio[3905]: UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Apr 16 16:56:00 media minio[3905]: Error: file access denied
Apr 16 16:56:00 media minio[3905]:        1: cmd/fs-v1-helpers.go:235:cmd.fsStatFile()
Apr 16 16:56:00 media minio[3905]:        2: cmd/fs-v1.go:604:cmd.(*FSObjects).parentDirIsObject.func1()
Apr 16 16:56:00 media minio[3905]:        3: cmd/fs-v1.go:612:cmd.(*FSObjects).parentDirIsObject()
Apr 16 16:56:00 media minio[3905]:        4: cmd/fs-v1.go:675:cmd.(*FSObjects).putObject()
Apr 16 16:56:00 media minio[3905]:        5: cmd/fs-v1.go:630:cmd.(*FSObjects).PutObject()
Apr 16 16:56:00 media minio[3905]:        6: cmd/bucket-policy.go:181:cmd.writeBucketPolicy()
Apr 16 16:56:00 media minio[3905]:        7: cmd/bucket-policy.go:200:cmd.persistAndNotifyBucketPolicyChange()
Apr 16 16:56:00 media minio[3905]:        8: cmd/fs-v1.go:1060:cmd.(*FSObjects).SetBucketPolicy()
Apr 16 16:56:00 media minio[3905]:        9: cmd/bucket-policy-handlers.go:278:cmd.objectAPIHandlers.PutBucketPolicyHandler()
Apr 16 16:56:00 media minio[3905]:       10: cmd/api-router.go:97:cmd.(objectAPIHandlers).PutBucketPolicyHandler-fm()
Apr 16 16:56:00 media minio[3905]:       11: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()`

and

`Apr 16 16:38:04 media minio[3905]: API: PutObject(bucket=mastodon, object=custom_emojis/images/000/000/016/static/e82fd12aa619aa97.png)
Apr 16 16:38:04 media minio[3905]: Time: 16:38:04 CST 04/16/2018
Apr 16 16:38:04 media minio[3905]: RemoteHost: 23.94.27.144:45504
Apr 16 16:38:04 media minio[3905]: UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Apr 16 16:38:04 media minio[3905]: Error: stat /storage/minio/mastodon/custom_emojis/images/000/000/016/static: no such file or directory
Apr 16 16:38:04 media minio[3905]:        1: cmd/fs-v1-helpers.go:166:cmd.fsStat()
Apr 16 16:38:04 media minio[3905]:        2: cmd/fs-v1-helpers.go:230:cmd.fsStatFile()
Apr 16 16:38:04 media minio[3905]:        3: cmd/fs-v1.go:604:cmd.(*FSObjects).parentDirIsObject.func1()
Apr 16 16:38:04 media minio[3905]:        4: cmd/fs-v1.go:612:cmd.(*FSObjects).parentDirIsObject()
Apr 16 16:38:04 media minio[3905]:        5: cmd/fs-v1.go:675:cmd.(*FSObjects).putObject()
Apr 16 16:38:04 media minio[3905]:        6: cmd/fs-v1.go:630:cmd.(*FSObjects).PutObject()
Apr 16 16:38:04 media minio[3905]:        7: cmd/object-handlers.go:660:cmd.(ObjectLayer).PutObject-fm()
Apr 16 16:38:04 media minio[3905]:        8: cmd/object-handlers.go:733:cmd.objectAPIHandlers.PutObjectHandler()
Apr 16 16:38:04 media minio[3905]:        9: cmd/api-router.go:77:cmd.(objectAPIHandlers).PutObjectHandler-fm()
Apr 16 16:38:04 media minio[3905]:       10: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Basically a s3 storage bucket to store images and such for a mastodon.social instance. But right now its just mc.

I tried disabling apparmor just in case that was it, but it had no effect. I made sure the directory/file permissions were correct and they look right. The bucket is located on a zfs array but I moved it to a regular single disk ext4 system and it didn't change. The bucket itself and the .minio.sys are on the same filesystem. mc is being ran from a remote system to a local computer that's the minio server, uploading files from the web interface seems to work fine. 

## Your Environment

* Version used (`minio version`): 2018-04-12T23:41:09Z
* Environment name and version (e.g. nginx 1.9.1): mc version 2018-03-25T01:22:22Z
* Server type and version: Ubuntu Server 16.04
* Operating System and version (`uname -a`): Linux media 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: N/A

**Comment by harshavardhana** [comment]
This is an error to be ignored, we have started over logging in a recent release.

**Comment by salsadoom** [comment]
Oh. Well that's actually good news. That means my minio server is working then. Thanks for the quick reply, that explains why everything looked ok. Thanks!!
