### ISSUE TITLE
log erreur copy file in bucket

### ISSUE THREAD

**Issue by gervaiscoquil** [minio/minio#5837]
**Environment** 

OS : Debian 9.4
Minio : minio.RELEASE.2018-04-12T23-41-09Z

`#./mc version`
Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4

**Start server** 

`# ./minio.RELEASE.2018-04-12T23-41-09Z server /mnt/data1 /mnt/data2 /mnt/data3 /mnt/data4`

**Client mc** 

`# ./mc mb myminio/test00`
Bucket created successfully `myminio/test`.
`# ./mc cp README myminio/test`

**Error** 

It's OK for file but log server :

API: PutObject(bucket=test, object=README)
Time: 13:32:43 CEST 04/19/2018
RemoteHost: 192.168.4.15:40624
UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Error: file not found
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: PutObject(bucket=test, object=README)
Time: 13:32:43 CEST 04/19/2018
RemoteHost: 192.168.4.15:40624
UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Error: file not found
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: PutObject(bucket=test, object=README)
Time: 13:32:43 CEST 04/19/2018
RemoteHost: 192.168.4.15:40624
UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Error: file not found
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: PutObject(bucket=test, object=README)
Time: 13:32:43 CEST 04/19/2018
RemoteHost: 192.168.4.15:40624
UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Error: file not found
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: PutObject(bucket=test, object=README)
Time: 13:32:43 CEST 04/19/2018
RemoteHost: 192.168.4.15:40624
UserAgent: Minio (linux; amd64) minio-go/5.0.1 mc/2018-03-25T01:22:22Z
Error: file not found
       1: cmd/xl-v1-utils.go:69:cmd.reduceQuorumErrs()
       2: cmd/xl-v1-utils.go:85:cmd.reduceWriteQuorumErrs()
       3: cmd/xl-v1-object.go:766:cmd.xlObjects.deleteObject()
       4: cmd/xl-v1-object.go:743:cmd.xlObjects.putObject()
       5: cmd/xl-v1-object.go:520:cmd.xlObjects.PutObject()
       6: cmd/xl-sets.go:584:cmd.(*xlSets).PutObject()
       7: cmd/object-handlers.go:660:cmd.(ObjectLayer).PutObject-fm()
       8: cmd/object-handlers.go:733:cmd.objectAPIHandlers.PutObjectHandler()
       9: cmd/api-router.go:77:cmd.(objectAPIHandlers).PutObjectHandler-fm()
      10: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

**Tests**

I tried, it's OK but always error in log server.
`# ./mc admin heal -r myminio/`

**Note** 

No problem with minio.RELEASE.2018-04-04T05-20-54Z build.
There is no errors in log server.

**Comment by nitisht** [comment]
@gervaiscoquil you can safely ignore the error. We are revamping Minio error logging and these errors will be removed soon

**Comment by gervaiscoquil** [comment]
@nitisht ok thanks ;)

**Comment by deekoder** [comment]
closing this as you should not see this in the future once we merge all the error related revamp concludes.

**Comment by kannappanr** [comment]
The logs will get printed on all successful putObject operations in the XL mode. This is because we call `defer xl.deleteObject(ctx, minioMetaTmpBucket, newUniqueID)` in `putObject` function.  It's intention is to remove incomplete object. Since it is called way before knowing whether this is a success or not, we end up calling this all the time. For success scenarios we will be logging as the temporary data would have been erased. The code should be rearranged such that this gets called only in the case of failed incomplete putobject.

**Comment by harshavardhana** [comment]
We have already fixed this @deekoder we can close this bug.
