### ISSUE TITLE
Can i store `/data/.minio.sys` in some db like mysql?

### ISSUE THREAD

**Issue by Jamlee** [minio/minio#5839]
i found the .minio.sys store the struct of stored files. many little files could result to perfermance problem. Could i store the metadata to my mysql db?

![image](https://user-images.githubusercontent.com/5196641/39028679-6d5ff660-448a-11e8-9535-9c6edbe77557.png)

## Possible Solution
metadata adapter to stored in mysql or other db.

**Comment by harshavardhana** [comment]
We designed our backend format to not store in any database. Is there any problem with current format ?

**Comment by Jamlee** [comment]
@harshavardhana I just worry about files amount.  i have 500,000 little files in my EMC Islion( my company enterparise storage).

**Comment by harshavardhana** [comment]
> @harshavardhana I just worry about files amount. i have 500,000 little files in my EMC Islion( my company enterprise storage).

There is nothing to worry about EMC Isilon can handle 500,000 files.
