### ISSUE TITLE
Distributed minio takes long time to upload and download large file locally. 

### ISSUE THREAD

**Issue by msinj** [minio/minio#5846]
## Expected Behavior

- Should show/start uploading immediately
- Should start download immediately.
- The download and upload speed should be faster.

## Current Behavior

We are testing the distributed minio. We have uploaded and download a 177MB video file. It takes about 3 minutes. At the same time, it takes long time to show that it started the download process. It appears after it approximately downloads 64MB. I think it downloads @64Mb or Kb chunks. 

## Possible Solution

Please Help. Desperate for help

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

[Distributed Minio.pdf](https://github.com/minio/minio/files/1939403/Distributed.Minio.pdf)

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by aead** [comment]
@msinj Can you explain your setup:
 - How much nodes are you using?
 - What client (sdk) are you using?
 - Can you provide a minimal example such that we can try to reproduce the issue you're facing?

**Comment by msinj** [comment]
We are using 4 nodes. 2 at California and 2 at New Jersey. Using WebUI to upload and download file to the server. We install the minio as below:
wget https://dl.minio.io/server/minio/release/linux-amd64/minio
chmod +x minio
./minio server /data
Change below field after "accessKey" & "secretKey"
		"accessKey": "AKIAIOSFODNN7EXAMPLE",
                "secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

sudo ./minio server http://192.168.1.158/data http://192.168.1.160/data \
		http://192.168.2.201/data http://192.168.2.202/data
After that, we're testing speed on uploading and downloading a file.

**Comment by aead** [comment]
@msinj Thanks for the details. One more question: What is the exact meaning of:
>At the same time, it takes long time to show that it started the download process.

You said you are using the WebUI. Are you downloading the object as a zip archive? Or are you
starting a "regular" download (just clicking on the object in the UI)?

**Comment by msinj** [comment]
> Are you downloading the object as a zip archive? Or are you
starting a "regular" download (just clicking on the object in the UI)?

We are using regular download option. Normally, when you click an item to download, it supposed to shows immediately that it is downloading. But from the minio, download indication shows after a minute at the bottom of the chrome after it downloads 64MB. File size is 178 MB. Its downloading as if dividing the file into 3 different part.

**Comment by aead** [comment]
Yes this is because erasure mode (in your case distributed erasure mode) splits objects into 64 MB chunks to reduce the time-to-first-byte. So the server is reading 64MB from it's disks before it can write anything to the client. However if all nodes have a fast network connection it should not take that long even in the worst case. I'm investigating...

**Comment by aead** [comment]
@msinj Can you:
1. Try to measure the network performance between the boxes using `iperf -s` and `iperf -c <box>`?
2. Ensure that all servers are available using `mc admin heal <cluster>`

**Comment by msinj** [comment]
can you give an example? I am not very familiar with the task. May be example of exact direction? Also, how to use `mc admin heal <cluster>` ?

**Comment by aead** [comment]
`mc` is our CLI S3 tool -> [here](https://github.com/minio/mc).
If you start your servers/cluster it should show you something like:
`mc config host add myminio https://192.168.188.22:9000 Q3AM3UQ867SPQQA43P2F zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG`

`myminio` would be the name for your cluster - you can change it to anything you want.
Let's assume you called it `myminio`: Than run `mc admin heal myminio`. That should show you status whether all your data is fine or whether some data (a node) is damaged. If the cluster has to repair the data on the fly during GET requests this affects your performance (esp. in distributed erasure since you're doing more network IO)

**Comment by msinj** [comment]
Hi,
I don't see any corruption in the /data directory. 
![image](https://user-images.githubusercontent.com/35358239/39196233-951ee71a-47af-11e8-9d29-660828dce9a0.png)
![image](https://user-images.githubusercontent.com/35358239/39196286-b40fb910-47af-11e8-9fcd-2ddd6038324b.png)

Getting below error when we start the distributed minio:
API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:69:cmd.reduceQuorumErrs()
       2: cmd/xl-v1-utils.go:79:cmd.reduceReadQuorumErrs()
       3: cmd/xl-v1-object.go:216:cmd.xlObjects.getObject()
       4: cmd/xl-v1-object.go:178:cmd.xlObjects.GetObject()
       5: cmd/xl-sets.go:579:cmd.(*xlSets).GetObject()
       6: cmd/bucket-policy.go:123:cmd.readBucketPolicyJSON()
       7: cmd/bucket-policy.go:138:cmd.ReadBucketPolicy()
       8: cmd/xl-sets.go:485:cmd.(*xlSets).GetBucketPolicy()
       9: cmd/bucket-handlers.go:96:cmd.isBucketActionAllowed()
      10: cmd/web-handlers.go:253:cmd.(*webAPIHandlers).ListObjects()
      11: reflect/value.go:447:reflect.Value.call()
      12: reflect/value.go:308:reflect.Value.Call()
      13: vendor/github.com/gorilla/rpc/v2/server.go:137:v2.(*Server).ServeHTTP()
      14: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
      15: cmd/generic-handlers.go:642:cmd.securityHeaderHandler.ServeHTTP()
      16: cmd/generic-handlers.go:626:cmd.rateLimit.ServeHTTP()
      17: :0:()
      18: cmd/generic-handlers.go:584:cmd.pathValidityHandler.ServeHTTP()
      19: :0:()
      20: cmd/generic-handlers.go:523:cmd.httpStatsHandler.ServeHTTP()
      21: :0:()
      22: cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
      23: :0:()
      24: cmd/generic-handlers.go:90:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      25: :0:()
      26: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
      27: :0:()
      28: cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
      29: :0:()
      30: cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
      31: :0:()
      32: cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
      33: :0:()
      34: cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
      35: :0:()
      36: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      37: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
       2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()

API: SYSTEM(bucket=video)
Time: 05:39:30 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:69:cmd.reduceQuorumErrs()
       2: cmd/xl-v1-utils.go:79:cmd.reduceReadQuorumErrs()
       3: cmd/xl-v1-object.go:216:cmd.xlObjects.getObject()
       4: cmd/xl-v1-object.go:178:cmd.xlObjects.GetObject()
       5: cmd/xl-sets.go:579:cmd.(*xlSets).GetObject()
       6: cmd/bucket-policy.go:123:cmd.readBucketPolicyJSON()
       7: cmd/bucket-policy.go:138:cmd.ReadBucketPolicy()
       8: cmd/xl-sets.go:485:cmd.(*xlSets).GetBucketPolicy()
       9: cmd/bucket-handlers.go:96:cmd.isBucketActionAllowed()
      10: cmd/web-handlers.go:254:cmd.(*webAPIHandlers).ListObjects()
      11: reflect/value.go:447:reflect.Value.call()
      12: reflect/value.go:308:reflect.Value.Call()
      13: vendor/github.com/gorilla/rpc/v2/server.go:137:v2.(*Server).ServeHTTP()
      14: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
      15: cmd/generic-handlers.go:642:cmd.securityHeaderHandler.ServeHTTP()
      16: cmd/generic-handlers.go:626:cmd.rateLimit.ServeHTTP()
      17: :0:()
      18: cmd/generic-handlers.go:584:cmd.pathValidityHandler.ServeHTTP()
      19: :0:()
      20: cmd/generic-handlers.go:523:cmd.httpStatsHandler.ServeHTTP()
      21: :0:()
      22: cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
      23: :0:()
      24: cmd/generic-handlers.go:90:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      25: :0:()
      26: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
      27: :0:()
      28: cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
      29: :0:()
      30: cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
      31: :0:()
      32: cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
      33: :0:()
      34: cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
      35: :0:()
      36: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      37: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: SYSTEM()
Time: 05:39:31 PDT 04/24/2018
**Error: file not found**
       1: cmd/xl-v1-utils.go:69:cmd.reduceQuorumErrs()
       2: cmd/xl-v1-utils.go:79:cmd.reduceReadQuorumErrs()
       3: cmd/xl-v1-object.go:345:cmd.xlObjects.getObjectInfoDir()
       4: cmd/xl-sets.go:775:cmd.(*xlSets).ListObjects()
       5: cmd/bucket-handlers-listobjects.go:155:cmd.(ObjectLayer).ListObjects-fm()
       6: cmd/web-handlers.go:272:cmd.(*webAPIHandlers).ListObjects()
       7: reflect/value.go:447:reflect.Value.call()
       8: reflect/value.go:308:reflect.Value.Call()
       9: vendor/github.com/gorilla/rpc/v2/server.go:137:v2.(*Server).ServeHTTP()
      10: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
      11: cmd/generic-handlers.go:642:cmd.securityHeaderHandler.ServeHTTP()
      12: cmd/generic-handlers.go:626:cmd.rateLimit.ServeHTTP()
      13: :0:()
      14: cmd/generic-handlers.go:584:cmd.pathValidityHandler.ServeHTTP()
      15: :0:()
      16: cmd/generic-handlers.go:523:cmd.httpStatsHandler.ServeHTTP()
      17: :0:()
      18: cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
      19: :0:()
      20: cmd/generic-handlers.go:90:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      21: :0:()
      22: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
      23: :0:()
      24: cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
      25: :0:()
      26: cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
      27: :0:()
      28: cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
      29: :0:()
      30: cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
      31: :0:()
      32: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      33: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

**Comment by harshavardhana** [comment]
> We are using 4 nodes. 2 at California and 2 at New Jersey

Minio distributed is not designed to work across data centers and it is not supported. While it may work if you have low-performance requirements, but it is not the recommended setup and can lead to potential issues. Low performance observed here is a result of this style of setup.

**Comment by msinj** [comment]
Thanks for the information. What about the error `file not found`?

**Comment by harshavardhana** [comment]
> Thanks for the information. What about the error file not found?

That error is frivolous and can be ignored, in a recent logging change we are over logging which we don't need to.

**Comment by harshavardhana** [comment]
> Thanks for the information. What about the error file not found?

In a multi-datacenter setup like yours - you should utilize edge caching which can provide you with the expected performance, even with a low performant backend. https://docs.minio.io/docs/minio-disk-cache-guide

**Comment by gongxun0928** [comment]
@harshavardhana i use Minio distributed in LAN, also found low performance when uploading through SDK(both python and golang,upload 23M cost almost 3min) . But when i used mc, it's high performance.
* Environment
6 nodes，disk capacity is differ, 4 nodes is 320GB SSD, the others is 360GB SSD
* OS
centos 7.2
* Version
Version: 2018-04-19T22:54:58Z
Release-Tag: RELEASE.2018-04-19T22-54-58Z
Commit-ID: 5a16671f721f4e8f320bc25f60ce4e601ab544e3

**Comment by harshavardhana** [comment]
> @harshavardhana i use Minio distributed in LAN, also found low performance when uploading through SDK(both python or golang,upload 23M cost almost 3min) . But when i used mc, it's high performance.

@gongxun0928 please create a new issue this issue is closed thanks.

**Comment by gongxun0928** [comment]
@harshavardhana ok.
