### ISSUE TITLE
memory usage regression in erasure setup 

### ISSUE THREAD

**Issue by aead** [minio/minio#5858]
The server consumes a non-constant amount of memory for reading erasure-coded objects.
This a a regression since e.g RELEASE.2017-11-22T19-55-46Z just consumed a constant amount of memory.

## Expected Behavior
```
ErasureRead_12_30MB/_000000|000000_-4       26.4MB ± 0%
ErasureRead_12_30MB/_000000|X00000_-4       26.1MB ± 0%
ErasureRead_12_30MB/_X00000|000000_-4       31.3MB ± 0%
ErasureRead_12_30MB/_X00000|X00000_-4       30.6MB ± 0%
ErasureRead_12_30MB/_000000|XXXXXX_-4       26.3MB ± 0%
ErasureRead_12_30MB/_XXX000|XXX000_-4       26.4MB ± 0%
ErasureRead_12_30MB/_XXXXXX|000000_-4       26.3MB ± 0%
ErasureRead_16_40MB/_00000000|00000000_-4   28.2MB ± 0%
ErasureRead_16_40MB/_00000000|X0000000_-4   27.9MB ± 0%
ErasureRead_16_40MB/_X0000000|00000000_-4   35.0MB ± 0%
ErasureRead_16_40MB/_X0000000|X0000000_-4   33.2MB ± 0%
ErasureRead_16_40MB/_00000000|XXXXXXXX_-4   28.1MB ± 0%
ErasureRead_16_40MB/_XXXX0000|XXXX0000_-4   28.3MB ± 0%
ErasureRead_16_40MB/_XXXXXXXX|00000000_-4   28.7MB ± 0%
```

The code uses a fixed amount of memory. However it is still not optimal since it consumes too much memory for small objects. 

## Current Behavior
```
ErasureRead_12_30MB/_000000|000000_-4        37.3MB ± 0%
ErasureRead_12_30MB/_000000|X00000_-4        37.2MB ± 0%
ErasureRead_12_30MB/_X00000|000000_-4        53.3MB ± 0%
ErasureRead_12_30MB/_X00000|X00000_-4        58.6MB ± 0%
ErasureRead_12_30MB/_000000|XXXXXX_-4        37.3MB ± 0%
ErasureRead_12_30MB/_XXX000|XXX000_-4        79.4MB ± 0%
ErasureRead_12_30MB/_XXXXXX|000000_-4        79.5MB ± 0%
ErasureRead_16_40MB/_00000000|00000000_-4    49.6MB ± 0%
ErasureRead_16_40MB/_00000000|X0000000_-4    49.6MB ± 0%
ErasureRead_16_40MB/_X0000000|00000000_-4    65.6MB ± 0%
ErasureRead_16_40MB/_X0000000|X0000000_-4    71.1MB ± 0%
ErasureRead_16_40MB/_00000000|XXXXXXXX_-4    49.5MB ± 0%
ErasureRead_16_40MB/_XXXX0000|XXXX0000_-4     102MB ± 0%
ErasureRead_16_40MB/_XXXXXXXX|00000000_-4     102MB ± 0%
```

## Possible Solution
The current reading code allocs buffers all over the place. Buffers should only allocated once.  

## Steps to Reproduce (for bugs)
1. Disable logging (therefore you have to edit the `logger` code)
2. `go test -run=None -bench=ErasreRead`
3. `git co RELEASE.2017-11-22T19-55-46Z`
4. `go test -run=None -bench=ErasreRead`

Of course the performance numbers differ, since RELEASE.2017-11-22T19-55-46Z uses BLAKE2b instead of HighwayHash and the constant-memory cod is still not optimal.

## Context
performance

## Your Environment
master

**Comment by harshavardhana** [comment]
I suspect large bucket support could have caused this... @aead

**Comment by harshavardhana** [comment]
> I suspect large bucket support could have caused this... @aead

Oh actually it's not since you are using a lower level call, it is perhaps the bit-rot change that we did to read the entire file in memory and does not return it back.  We need to do a block-level checksum for this to become optimal.

**Comment by aead** [comment]
@harshavardhana I haven't analyzed it with pprof yet, but I suspect that it is caused by code like e.g. [this](https://github.com/minio/minio/blob/master/cmd/erasure-readfile.go#L40) where we simply allocate memory for every call instead of allocating it outside once and reuse it.

**Comment by harshavardhana** [comment]
Is this still a problem @aead if yes can this be closed since there are two more issues opened in this area already ?

- #6338 
- #6363

**Comment by nitisht** [comment]
ping @aead 

> Is this still a problem @aead if yes can this be closed since there are two more issues opened in this area already ?

**Comment by nitisht** [comment]
closing this for now @aead , please reopen if you think this is still an issue
