### ISSUE TITLE
Scaling issues in gateway mode

### ISSUE THREAD

**Issue by cbenien** [minio/minio#5859]
## Expected Behavior
Scale vertically in a predictable way

## Current Behavior
I'm using minio in azure gateway mode, and I see that once I have more than 100 requests running in parallel, the performance drops sharply, with frequent failures at 200 requests. Looking at "netstat -tn" reveals that there are thousands of connections in TIME_WAIT state, indicating that minio doesn't re-use connections to Azure efficiently.

## Possible Solution
Increase number of idle connections per host. Minio statically configures this to 100, and performance problems start once you have more than 100 connections in parallel. I can submit a pull request to increase the static limit, but this is probably not the ideal solution. Maybe it's better to do it dynamically?

## Steps to Reproduce (for bugs)
Use any benchmark tool for S3 and configure number of threads or concurrent connections to 200

## Context
Minio stop responding for a few minutes

## Your Environment
* Version used (`minio version`): DEVELOPMENT.2018-04-25T13-29-15Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Azure DS15v2, 20 CPU and 140 GB memory
* Operating System and version (`uname -a`): Ubuntu 16.04
* Link to your project: -

**Comment by krishnasrinivas** [comment]
Discussion is happening on the PR

**Comment by krishnasrinivas** [comment]
https://github.com/minio/minio/pull/5860 merged. Closing the issue.
