### ISSUE TITLE
make cache limit configurable

### ISSUE THREAD

**Issue by poornas** [minio/minio#5863]
- Add env variable MINIO_CACHE_LIMIT to make % of disk available to cache configurable.
- make MINIO_CACHE_DRIVES take ellipsis style entries.

**Comment by annanay25** [comment]
@poornas `MINIO_CACHE_DRIVES` parsing hasn't been changed.

**Comment by harshavardhana** [comment]
> @poornas MINIO_CACHE_DRIVES parsing hasn't been changed.

Open a new issue @annanay25 @poornas

**Comment by poornas** [comment]
@annanay25, aware of that, will be sending a PR today referencing this issue.
