### ISSUE TITLE
Hide secret key in logs when provided at startup

### ISSUE THREAD

**Issue by blackholegalaxy** [minio/minio#5864]
We use minio docker container. And we send all containers logs to a central elasticsearch cluster. We 

To avoid unwanted people to have direct access to secret key, is there any way to hide it from logs?

## Current Behavior
Even if we user docker secrets to transmit startup access_key and secret_key to minio, minio then logs these value in clear in logs.

## Expected Behavior
Since we use secrets, we expect not to see values in clear in logs.

## Possible Solution
A start option. Or automatic hide of values if using secret. Or hide as soon as access_key and secret_key are not generated by minio.

## Steps to Reproduce (for bugs)
Start minio docker passing keys as secrets or environment variable.

## Your Environment

* Version used (`minio version`): docker image minio/minio:RELEASE.2018-04-19T22-54-58Z

**Comment by harshavardhana** [comment]
minio server --quiet - hides your secret keys.

**Comment by blackholegalaxy** [comment]
But does it also mute any other log statement?

**Comment by harshavardhana** [comment]
> But does it also mute any other log statement?

It will mute the banner, not other logs.

**Comment by blackholegalaxy** [comment]
ok perfect. I missed this command. Thanks for your help.
