### ISSUE TITLE
Minio k8s distributed mode Waiting for a minimum of 2 disks to come online infinately

### ISSUE THREAD

**Issue by Reasno** [minio/minio#5865]
Installed Minio via helm with 4 replicas, each on a different bare metal machine. It seems mimio pods just can't connect with each other. Other pods and services in the cluster ran fine. I also checked dns following the k8s troubleshoot guide, but it is good. 

## Expected Behavior

Minio works out of box.

## Current Behavior

 You are running an older version of Minio released 1 month ago 
 Update: https://docs.minio.io/docs/deploy-minio-on-kubernetes 
Waiting for a minimum of 2 disks to come online (elapsed 0s)
Waiting for a minimum of 2 disks to come online (elapsed 1s)
Waiting for a minimum of 2 disks to come online (elapsed 3s)
Waiting for a minimum of 2 disks to come online (elapsed 10s)
Waiting for a minimum of 2 disks to come online (elapsed 15s)
Waiting for a minimum of 2 disks to come online (elapsed 31s)
Waiting for a minimum of 2 disks to come online (elapsed 54s)
Waiting for a minimum of 2 disks to come online (elapsed 59s)

continue for more than 2 hours.

## Steps to Reproduce (for bugs)

1. bare metal server k8s setup
2. helm install stable/minio

## Your Environment

* Version used (`minio version`): RELEASE.2018-03-12T21-25-28Z
* Environment name and version (e.g. nginx 1.9.1): k8s 1.10.1
* Server type and version: linux
* Operating System and version (`uname -a`): centos 7
* Link to your project:

**Comment by nitisht** [comment]
@Reasno can you pls tell us more about the error 

- Are all the pods up/running?
- Are you able to ping one pod from another?
- Do you have Persistent Volumes available in the cluster and are they bound to Pods?

**Comment by harshavardhana** [comment]
> Version used (minio version): RELEASE.2018-03-12T21-25-28Z

@nitisht this version seems older is the helm chart not updated?

**Comment by nitisht** [comment]
There is a PR that has been in review forever due to recent issues in kubernetes configMap https://github.com/kubernetes/charts/pull/4277 , now that I removed configMap support in minio chart I am hoping it gets in soon

**Comment by Reasno** [comment]
@nitisht Yes to all three questions.

**Comment by nitisht** [comment]
@Reasno it is difficult to say what went wrong, because we have Minio working pretty well on Kubernetes. Will it be possible to provide remote access your deployment?

**Comment by Reasno** [comment]
Hi @nitisht , thanks for your help. I think this could be a duplicate of #5667 . When I manually selected an earlier docker release, everything worked fine. Sadly RELEASE.2018-03-12T21-25-28Z is still the default choice in helm chart.

**Comment by nitisht** [comment]
Thanks for the update @Reasno there is a PR kubernetes/charts#4277 to update Helm chart to latest release, hopefully we'll have it merged soon. 

Also, can you please try the latest release [`RELEASE.2018-04-27T23-33-52Z
`] instead of older release

**Comment by Reasno** [comment]
I hit "Error: Config migration failed." using RELEASE.2018-04-27T23-33-52Z

**Comment by nitisht** [comment]
Helm chart is now updated to latest Minio release, will it possible for you to test once more..

**Comment by Reasno** [comment]
@nitisht I can confirm everything works as intended now in distributed mode with RELEASE.2018-04-27T23-33-52Z and helm chart master

**Comment by nitisht** [comment]
great! Thanks a lot.
