### ISSUE TITLE
XML Parsing Error: no root element found

### ISSUE THREAD

**Issue by matthanley** [minio/minio#5873]
We're seeing the error "XML Parsing Error: no root element found" and a 500 response when requesting files from public buckets with a read only policy on Docker builds after `RELEASE.2018-04-19T22-54-58Z`

## Steps to Reproduce (for bugs)
Setup is:
* Existing data from a previous minio version
* Read only policy on public bucket

Following an update to a build later than `RELEASE.2018-04-19T22-54-58Z` we get a 500 response and the above error message. Build `RELEASE.2018-04-19T22-54-58Z` and earlier work correctly.

## Context
Issue present following update to `latest` or `edge`

## Your Environment
Docker

**Comment by harshavardhana** [comment]
Bucket policies are in JSON the error message seems to be different for XML? can you provide more details?

**Comment by matthanley** [comment]
As an example we have a bucket called `public` with a `*` Read Only policy. Within this bucket, we have a plain text file containing only the characters `OK` that we use for monitoring availability.

We were also having an issue downloading files via `mc` from the same instance, with the error `Unexpected EOF`. I've reverted to the previous working release for now but if I have time over the next few days I'll spin up the `latest` and `edge` builds and try and grab some relevant logs.

**Comment by harshavardhana** [comment]
> As an example we have a bucket called public with a * Read Only policy. Within this bucket, we have a plain text file containing only the characters OK that we use for monitoring availability.

This is not necessary you don't need a complex setup like this to monitor Minio server availability we have moved to a more standardized approach here https://github.com/minio/minio/tree/master/docs/healthcheck - PTAL

> We were also having an issue downloading files via mc from the same instance, with the error Unexpected EOF. I've reverted to the previous working release for now but if I have time over the next few days I'll spin up the latest and edge builds and try and grab some relevant logs.

This would be interesting to see as well can you provide server, `mc --debug` logs as well?

**Comment by matthanley** [comment]
No problem - I've just tested locally and it's working so it might be something related to our infrastructure.

Thanks for the heads-up on the healthcheck endpoint, I'll get our monitoring updated (we use the public bucket anyway)

**Comment by harshavardhana** [comment]
> No problem - I've just tested locally and it's working so it might be something related to our infrastructure.
> 
> Thanks for the heads-up on the healthcheck endpoint, I'll get our monitoring updated (we use the public bucket anyway)

do you still want to keep this issue open @matthanley ?

**Comment by matthanley** [comment]
Will close for now and reopen if I identify any issues in testing
