### ISSUE TITLE
Object name contains unsupported characters when using double forward slash (//)

### ISSUE THREAD

**Issue by raminski2** [minio/minio#5874]
When trying to write an object to a bucket via s3, the following http error 400 is returned by minio:

HTTP operation returned code: 400 request error : "Object name contains unsupported characters", URI: 1.1.1.1:9000/123abcd1234-123abcd1234//test/test_file1

## Expected Behavior
Handle double forward slashes in the URI, i.e. bucket name ending in / is then appended by the object name starting with /

## Steps to Reproduce (for bugs)
Quite easy, just try and create an object in the style mentioned above.

## Context
Unable to use object storage

## Your Environment
* Version used (`minio version`):2018-04-27T23:33:52Z
* Environment name and version (e.g. nginx 1.9.1):Ubuntu  16.04
* Server type and version:Ubuntu 16.04
* Operating System and version (`uname -a`):Linux s3obj 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 14:00 UTC x86_64 GNU/Linux
* Link to your project:n/a

**Comment by harshavardhana** [comment]
> HTTP operation returned code: 400 request error : "Object name contains unsupported characters", URI: 1.1.1.1:9000/123abcd1234-123abcd1234//test/test_file1

This is on purpose why would you want to have a "//" in your prefix is it not possible to simply have `123abcd1234-123abcd1234/test/test_file1` ?

**Comment by deekoder** [comment]
@raminski2 it's not an allowed character.

**Comment by raminski2** [comment]
after further research, it's because the application that i use which wants to use object storage prefixes the object with a forward slash (/) and ends the bucket name with a forward slash (/) which is why there is a double forward slash. This works fine with other s3 object storage providers, such as AWS, Azure, ECS.

**Comment by harshavardhana** [comment]
@raminski2 yes it does because AWS, Azure, and ECS do not use a filesystem backend. In our case these are simply directories on your backend, filesystem doesn't allow us to preserve "/" as a character since its simply a separator. 

The application is buggy here if you try to copy the data out after using this application using tools like s3cmd, aws-cli you will not be able to copy since '/' will not be preserved and it will try to create a directory in your root due to the path being absolute.

**Comment by harshavardhana** [comment]
Additionally, we can simply ignore and trim the "/" but we don't want to mingle with incoming I/O patterns. Ideally, the application should be fixed such that it avoids cryptic file patterns like this. Here is how it will look like in a real world

Lets copy with `//` 
```
$ aws s3 cp /etc/issue s3://harshavardhana//etc/issue
upload: ../../../../etc/issue to s3://harshavardhana//etc/issue
```

Then try to list 
```
$ aws s3 ls s3://harshavardhana
                           PRE /
```

This doesn't tell me what it is so now i add a `/` 
```
$ aws s3 ls s3://harshavardhana/
                           PRE /
```

Still doesn't list anything and now i willfully one more `/`
```
$ aws s3 ls s3://harshavardhana//
                           PRE etc/
```

Now, this is what you need to remember to simply even list the objects, this is a cryptic scenario. Things get interesting when you can do this as well 

```
$ aws s3 cp /etc/issue s3://harshavardhana/etc/issue
upload: ../../../../etc/issue to s3://harshavardhana/etc/issue
```

Now, the list is even more confusing. 
```
$ aws s3 ls s3://harshavardhana/
                           PRE /
                           PRE etc/
```

Now let's try to copy the data out

```
$ aws s3 sync s3://harshavardhana /tmp/1
download: s3://harshavardhana/etc/issue to ../../../../tmp/1/etc/issue
download: s3://harshavardhana//etc/issue to ../../../../tmp/1/etc/issue
```

It ended up overwriting each other and leading to data loss. 

```
 $ ls -ltr /tmp/1/etc/
total 4
-rw-r--r-- 1 harsha harsha 24 May  1 12:30 issue
```

**Comment by raminski2** [comment]
OK thanks. The application doesn't use files, essentially it stores the file name and then converts the actual underlying data for that file by converting the file into a number of objects and stores these objects. Reading/deleting/accessing etc the objects using this exact syntax, i.e. <bucketname></></><objectname> works just fine. I was just trying other object providers and stumbled across minio. If it's not possible with minio, not to worry. I wanted to log it incase it was a bug.

**Comment by nitisht** [comment]
closing this as working as intended @raminski2 . Feel free to reopen/comment if there are further issues.

**Comment by github-wisper** [comment]
please reopen and correct this issue
S3 object key named /   is possible,  a lot of application deal with this, but minio server cannot be use as replacing solution to s3 , or update your website, and delete Full compatible S3 api , it's not the true.
Regards
Nicolas

**Comment by harshavardhana** [comment]
@github-wisper I don't think you are right  `/`  is not supported for good reasons, if your application deals with `/` on object storage then it is incorrectly written, to simulate POSIX on top of object storage.

Supporting `/` is not a cornerstone for all S3 compatibility and not having doesn't make a software suddenly incompatible. We haven't come across any application which is incompatible with this behavior, such as wide range of Hadoop, Splunk etc all use correctly the right style. These applications are correctly written.

If your application tightly sticks to usage of `/` you are better off using some other solution, as we are not interested in supporting POSIX behaviors on object storage.
