### ISSUE TITLE
[distributed] When booting, a node needs to fail early when it has different credentials

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5877]
## Expected Behavior
One node needs to report directly ~and exit~ when it detects that it has unauthenticated RPC call with one of the other nodes (only during initialization)

## Current Behavior
Infinite waiting without clear reason why it is waiting.

```
Waiting for a minimum of 2 disks to come online (elapsed 4m16s)

Waiting for a minimum of 2 disks to come online (elapsed 4m35s)

Waiting for a minimum of 2 disks to come online (elapsed 4m59s)

Waiting for a minimum of 2 disks to come online (elapsed 5m24s)

Waiting for a minimum of 2 disks to come online (elapsed 5m26s)

Waiting for a minimum of 2 disks to come online (elapsed 5m40s)

Waiting for a minimum of 2 disks to come online (elapsed 6m3s)
```

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
```
#!/bin/bash
  
args=()
for i in $(seq 1 4); do
    args+="http://localhost:$[9000+$i]/tmp/xl/d$i "
done
  
for i in $(seq 1 3); do
    MINIO_ACCESS_KEY="minio" MINIO_SECRET_KEY="minio123" minio server --address ":$[9000+$i]" $args >/dev/null &
done

MINIO_ACCESS_KEY="minio" MINIO_SECRET_KEY="minio123xxxxxxx" minio server --address ":$[9000+4]" $args

```

## Context
Testing

## Your Environment
All

**Comment by vadmeste** [comment]
Exiting is not needed to facilitate changing credentials remotely.

**Comment by krishnasrinivas** [comment]
I think failing might be tricky. If we print informative logs it would be good enough.

**Comment by vadmeste** [comment]
> I think failing might be tricky. If we print informative logs it would be good enough.

yeah, it makes sense

**Comment by harshavardhana** [comment]
@vadmeste can this be tested again with latest master?

**Comment by vadmeste** [comment]
> @vadmeste can this be tested again with latest master?

I am still seeing the problem using the script pasted above (btw, I fixed one little bug in it).

Other nodes, which have the correct credentials will work normally together and will ignore the only node that has the wrong credentials. So I guess we need to print more detailed log about the error in the node that has wrong credentials.

```

Waiting for a minimum of 2 disks to come online (elapsed 4m8s)

Waiting for a minimum of 2 disks to come online (elapsed 4m15s)

Waiting for a minimum of 2 disks to come online (elapsed 4m33s)
```

**Comment by harshavardhana** [comment]
> I am still seeing the problem using the script pasted above (btw, I fixed one little bug in it).
> 
> Other nodes, which have the correct credentials will work normally together and will ignore the only node that has the wrong credentials. So I guess we need to print more detailed log about the error in the node that has wrong credentials.
> 
> 
> Waiting for a minimum of 2 disks to come online (elapsed 4m8s)
> 
> Waiting for a minimum of 2 disks to come online (elapsed 4m15s)
> 
> Waiting for a minimum of 2 disks to come online (elapsed 4m33s)

are we going to do this? any proposals? @vadmeste @krishnasrinivas

**Comment by vadmeste** [comment]
> are we going to do this? any proposals? @vadmeste @krishnasrinivas

I think we are good with printing informative logs

**Comment by harshavardhana** [comment]
> I think we are good with printing informative logs

If we are good with informative logs should we close this?

**Comment by vadmeste** [comment]
Yes, with master it is showing
```
Unable to connect to http://minio:9010/mnt/p4/vadmeste/test/dist/10: Authentication failed, check your access credentials

Unable to connect to http://minio:9011/mnt/p4/vadmeste/test/dist/11: Authentication failed, check your access credentials

Unable to connect to http://minio:9012/mnt/p4/vadmeste/test/dist/12: Authentication failed, check your access credentials
```

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/commit/75715820007a8832f4bc86c338d2ce1cb11eff2f
