### ISSUE TITLE
minio mirror error: no such file or directory

### ISSUE THREAD

**Issue by msinj** [minio/minio#5880]
Need help perform mirroring between two minio server
## Expected Behavior
should start mirror file between server

## Current Behavior
after performing below command and configuration on each minio server:
` mc config host add testminio1 http://192.168.200.196 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`
`mc config host add testminio2 http://192.168.200.188 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`
`./mc mirror --watch testminio1 testminio2`

I am getting below error on both servers:
`mc: <ERROR> Failed to start monitoring. lstat /home/itadmin/testminio1: no such file or directory`
`mc:` <ERROR> Failed to start monitoring. lstat /home/itadmin/testminio2: no such file or directory`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
first test server: 192.168.200.196; mounted drive is /media/data
Second test server: 192.168.200.188; mounted drive is /media/data

* Version used (`minio version`): 
![image](https://user-images.githubusercontent.com/35358239/39535423-dc90806a-4e01-11e8-88c4-894ab093aa56.png)
* Server type and version:
Ubuntu server version 16.04.4 LTS
* Operating System and version (`uname -a`):
Linux testminio1 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by deekoder** [comment]
@msinj can you see these two sites when you do `mc config host list`

**Comment by msinj** [comment]
> can you see these two sites when you do mc config host list

Please see below screenshot after typing the command:
![image](https://user-images.githubusercontent.com/35358239/39537146-ac0c3bd2-4e06-11e8-8471-34f4680008fe.png)

**Comment by Praveenrajmani** [comment]
@msinj  For me it works fine .

![screen shot 2018-05-03 at 1 48 31 pm](https://user-images.githubusercontent.com/5410427/39566310-c99dff14-4ed8-11e8-927c-e9be1d8e6da2.png)

Can you get me `mc config host list` and `mc ls` of the buckets that needed to be mirrored ?

**Comment by msinj** [comment]
Hi,
I am not sure if I configured it correctly. Every time I issue those `mc config host list` and `mc ls`, I am getting below screen. Even when issued `mc config host add testminio2 http://192.168.200.188 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`, below screen showed up. Just to make sure, I have a separate ssd which I have mounted @ /media/data.
![](https://user-images.githubusercontent.com/35358239/39537146-ac0c3bd2-4e06-11e8-8471-34f4680008fe.png)

**Comment by Praveenrajmani** [comment]
hey @msinj  ,

how did you install the mc package ?? 

`mc config host list` here looks like 

![screen shot 2018-05-03 at 6 47 13 pm](https://user-images.githubusercontent.com/5410427/39579031-5ea5638e-4f03-11e8-9bb4-fd46208e3311.png)


Follow 

> https://docs.minio.io/docs/minio-client-quickstart-guide

For the installation

check with ./mc binary , should be working

**Comment by msinj** [comment]
Hi @Praveenrajmani 
I was missing the ./mc command. However, new error while configuring the host
`mc: <ERROR> Unable to initialize new config from the provided credentials. Get http://192.168..200.196/probe-bucket-sign/?location=: dial tcp 192.168.200.196:80: connect: connection refused`

**Comment by Praveenrajmani** [comment]
@msinj  

Check the minio server instance whether it is running or not , It seems the server is down and is unreachable for mc.

Try restarting by , `./minio server`

**Comment by msinj** [comment]
Hi @Praveenrajmani 
Both testminio1 and testminio2 are running. Also the access key and secret key are matching

**Comment by Praveenrajmani** [comment]
Hi @msinj 
Can you see them if you do `mc config host list` ?? . can you send me that

**Comment by msinj** [comment]
Hi @Praveenrajmani 
I can only see localhost as below:
![image](https://user-images.githubusercontent.com/35358239/39756455-b412f100-5297-11e8-91a1-a84144bc7ae6.png)

**Comment by vadmeste** [comment]
@msinj there is no testminio1 and testminio2 aliases in your config. Can you try again from scratch and post here the commands you are using with their outputs ?

**Comment by msinj** [comment]
hi @deekoder 
I just removed the minio and re-downloaded. Than configured the access key and secreat key of my choice before issuing below command:
`./mc config host add minio1 http://192.168..200.196 MSISTONEEXAMPLE GetMe/SomeGood/SurfaceFrom/MsistoneUSA2095`

I am still getting below error:
`mc: <ERROR> Unable to initialize new config from the provided credentials. Get http://192.168.200.196/probe-bucket-sign/?location=: dial tcp 192.168.200.196:80: connect: connection refused`

**Comment by vadmeste** [comment]
@msinj by default, Minio server runs on port 9000, so if you did not change the default port number, you will need to pass http://192.168.200.196:9000 in `mc config host add` command.

**Comment by msinj** [comment]
can you please remove the IP address for safty. Thanks

**Comment by msinj** [comment]
Hi,
This time it added the host. So i issued the ` ./mc mirror --watch minio1 minio2` and I got below response
![image](https://user-images.githubusercontent.com/35358239/39780531-8cb98f5e-52da-11e8-8a35-83b57815282e.png)
however, when I checked the the other minio2  /media/data drive, it shows that the drive is empty.

**Comment by vadmeste** [comment]
@msinj  can you show the output of `mc config host list minio1` and `mc config host list minio2` ?

**Comment by msinj** [comment]
Hi @deekoder 
I didn't realize that I have to add all the bucket on all machines. It's working now.
How can we make it to mirror the change as soon as there is change happen on the source?

**Comment by vadmeste** [comment]
> I didn't realize that I have to add all the bucket on all machines. It's working now.
Good.

> How can we make it to mirror the change as soon as there is change happen on the source?
`mc mirror -w` should accomplish this.

Closing this as it seems to be resolved @msinj, please feel free to open it again if needed.
