### ISSUE TITLE
File upload with error Error: file access denied.

### ISSUE THREAD

**Issue by nichochen** [minio/minio#5891]
File upload with error Error: file access denied.

## Expected Behavior

File upload without error.

## Current Behavior

Web console shows file uploaded successfully, but following error shows in the log.

    API: SYSTEM()
    Time: 05:26:44 UTC 05/05/2018
    Error: file access denied
        1: cmd/fs-v1-helpers.go:222:cmd.fsStatDir()
        2: cmd/fs-v1.go:566:cmd.(*FSObjects).getObjectInfo()
        3: cmd/fs-v1.go:1009:cmd.(*FSObjects).ListObjects.func1()
        4: cmd/fs-v1.go:1046:cmd.(*FSObjects).ListObjects()
        5: cmd/bucket-handlers-listobjects.go:156:cmd.(ObjectLayer).ListObjects-fm()
        6: cmd/web-handlers.go:293:cmd.(*webAPIHandlers).ListObjects()
        7: reflect/value.go:447:reflect.Value.call()
        8: reflect/value.go:308:reflect.Value.Call()
        9: vendor/github.com/gorilla/rpc/v2/server.go:137:v2.(*Server).ServeHTTP()
        10: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
        11: cmd/generic-handlers.go:651:cmd.securityHeaderHandler.ServeHTTP()
        12: cmd/generic-handlers.go:636:cmd.rateLimit.ServeHTTP()
        13: :0:()
        14: cmd/generic-handlers.go:596:cmd.pathValidityHandler.ServeHTTP()
        15: :0:()
        16: cmd/generic-handlers.go:535:cmd.httpStatsHandler.ServeHTTP()
        17: :0:()
        18: cmd/generic-handlers.go:66:cmd.requestSizeLimitHandler.ServeHTTP()
        19: :0:()
        20: cmd/generic-handlers.go:91:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
        21: :0:()
        22: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
        23: :0:()
        24: cmd/generic-handlers.go:243:cmd.redirectHandler.ServeHTTP()
        25: :0:()
        26: cmd/generic-handlers.go:301:cmd.minioReservedBucketHandler.ServeHTTP()
        27: :0:()
        28: cmd/generic-handlers.go:270:cmd.cacheControlHandler.ServeHTTP()
        29: :0:()
        30: cmd/generic-handlers.go:371:cmd.timeValidityHandler.ServeHTTP()
        31: :0:()
        32: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
        33: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

## Steps to Reproduce (for bugs)

1. Start Minio with Docker.

    docker run -p 9000:9000 -v /mnt/data:/data -v /mnt/config:/root/.minio minio/minio server /data
2. Login to Minio web console
3. Create a bucket 
4. Upload a file
5. Check the docker log

## Your Environment

* Version used (`minio version`): 2018-05-04T23:13:12Z
* Environment name and version (e.g. nginx 1.9.1): Centos 7.4
* Server type and version: 
* Operating System and version (`uname -a`): Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
@nichochen thanks for opening the bug, this error can be ignored it is a frivolous error. We will fix it in a subsequent release and suppress it.

**Comment by nitisht** [comment]
@nichochen closing this as answered, feel free to get back if you have further questions.

**Comment by thomasknauth** [comment]
Excessive logging behavior creates gigantic log files that fill up the hard disk quickly. I'm seeing this with OpenWhisk which uses minio to some degree. With OpenWhisk this creates about 4MB of logging data every 10s.

**Comment by harshavardhana** [comment]
> Excessive logging behavior creates gigantic log files that fill up the hard disk quickly. I'm seeing this with OpenWhisk which uses minio to some degree. With OpenWhisk this creates about 4MB of logging data every 10s.

@thomasknauth would you mind opening a new bug, this issue is closed.
