### ISSUE TITLE
Unclear error message on Startup "Error: Invalid command line arguments server=‘:9000’, args=[http://example.org/data{1...10}]"

### ISSUE THREAD

**Issue by egofelix** [minio/minio#5892]
Running
docker run --rm minio/minio server http://example.org/data{1...10}
exits with "Error: Invalid command line arguments server=‘:9000’, args=[http://example.org/data{1...10}]"

It is unclear what is the real error here.

## Expected Behavior
Starting of Minio?

## Current Behavior
Abort with non helpful error message

## Possible Solution
Create more clear error message

## Steps to Reproduce (for bugs)
1. docker run --rm minio/minio server http://example.org/data{1...10}

## Context
Unable to start minio

## Your Environment
* Version used (`minio version`):
Version: 2018-05-04T23:13:12Z
Release-Tag: RELEASE.2018-05-04T23-13-12Z
Commit-ID: c5a00e513c44edefd1de7adf68b324bf352740de

* Environment name and version (e.g. nginx 1.9.1):
- Docker version 18.04.0-ce, build 3d479c0af6

* Server type and version:
Arch Linux

* Operating System and version (`uname -a`):
Linux xxxx 4.16.6-1-ARCH #1 SMP PREEMPT Mon Apr 30 12:30:03 UTC 2018

**Comment by JavaCS3** [comment]
The same issue to me

**Comment by vadmeste** [comment]
This PR https://github.com/minio/minio/pull/5878 should fix the error message to the following:

![screenshot from 2018-05-07 10-08-55](https://user-images.githubusercontent.com/283197/39714374-b64ee140-51de-11e8-8154-de40ec6a8d5b.png)

But the PR still needs to get some more reviews before merging it.

**Comment by JavaCS3** [comment]
@vadmeste But it's able to show error message in the previous build.
```
docker run -p 9000:9000 \
  --rm \
  --name minio1 \
  -e "MINIO_ACCESS_KEY=123123123" \
  -e "MINIO_SECRET_KEY=123123123" \
  -v $PWD/data:/data \
  -v $PWD/config:/root/.minio \
  minio/minio:RELEASE.2018-04-04T05-20-54Z server http://192.168.0.1/export/1 http://192.168.0.2/export/2 http://192.168.0.3/export/3 http://192.168.0.4/export/4

Trace: 1: cmd/server-main.go:141:cmd.serverHandleCmdArgs()
       2: cmd/server-main.go:191:cmd.serverMain()
       3: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       6: cmd/main.go:155:cmd.Main()
       7: main.go:71:main.main()
[2018-05-08T03:20:26.82801Z] [FATAL] Invalid command line arguments server=‘:9000’, args=[http://192.168.0.1/export/1 http://192.168.0.2/export/2 http://192.168.0.3/export/3 http://192.168.0.4/export/4] (no endpoint found for this host)
```

**Comment by harshavardhana** [comment]
@JavaCS3 there was logging refactor which ended up removing good messages, we are bringing them back but with a more cleaner approach than what you see with `minio/minio:RELEASE.2018-04-04T05-20-54Z`

**Comment by harshavardhana** [comment]
This is fixed 

```
$ minio server http://example.com/data{1..10}
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
      > Please provide correct combinations of local/remote paths.
      HELP:
        For more information, please refer to the following link: https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
```
