### ISSUE TITLE
PUT Object tagging replaces contents of file with tags rather than updating the tags of the file.

### ISSUE THREAD

**Issue by mjburghoffer** [minio/minio#5896]
## Expected Behavior
When calling PUT tagging endpoint, it is expected that the tags on the object are overwritted.  Here is the [s3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTtagging.html) for the endpoint, and here is the documentation for [consuming it with a java client](https://docs.aws.amazon.com/AmazonS3/latest/dev/tagging-manage-javasdk.html).

## Current Behavior
Currently, minio replaces the contents of the file with the tagging payload, ie:

```xml
<Tagging>
  <TagSet>
     <Tag>
       <Key>Tag Name</Key>
       <Value>Tag Value</Value>
     </Tag>
  </TagSet>
</Tagging>
```

A secondary side-effect is all user metadata is removed, and all server-side metdata is set as though the content of the file is xml.

## Possible Solution
Support PUT tagging.

## Steps to Reproduce (for bugs)
1. Create any file
2. Call PUT tagging request as shown above
3. Call GET tagging request

## Context
Tags are useful so files can be categorized and filtered so applications can decide if and how to consume them.  Additionally with s3, users may do permissioning for certain tags.

## Your Environment
* Version used (`minio version`):
  - RELEASE.2018-05-04T23-13-12Z
* Environment name and version (e.g. nginx 1.9.1):
  - osx Version 10.13.4
  - docker for mac version 18.03.1-ce
* Server type and version:
  - Minio docker RELEASE.2018-05-04T23-13-12Z
* Operating System and version (`uname -a`):
  - 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
We don't support object tagging and have no plans for supporting this in near future. Will send a PR to reject such API operations.

**Comment by Cinerar** [comment]
According to this https://github.com/minio/minio/issues/5139#issuecomment-485520789
there are plans to support object tagging  is it true? any roadmap?

**Comment by harshavardhana** [comment]
> there are plans to support object tagging is it true? any roadmap?

Its not on roadmap @Cinerar
