### ISSUE TITLE
The case of the reappearing file

### ISSUE THREAD

**Issue by tibmeister** [minio/minio#5904]
When trying to clear out the contents of a bucket, I can use either the mc client of the GUI and delete the files and folders without issue, only to have them magically pop-up again.  It's rather annoying when trying to get rid of a bucket.

I am using Minio as an S3FS endpoint for RexRay as a volume-plugin for my Docker systems, at least I want to if I can get the bugs ironed out.

**Comment by harshavardhana** [comment]
@tibmeister are you using distributed minio or standalone?

**Comment by tibmeister** [comment]
Distributed,  I've attached my config.  I have a 3 node swarm currently so one of the hosts is pulling double duty.
[minio-dist-swarm.yml.txt](https://github.com/minio/minio/files/1985643/minio-dist-swarm.yml.txt)

**Comment by harshavardhana** [comment]
> Distributed, I've attached my config. I have a 3 node swarm currently so one of the hosts is pulling double duty.
> minio-dist-swarm.yml.txt

From what I can tell here you don't have enough quorum and deletes are not deleting files.

**Comment by tibmeister** [comment]
So even though I have four containers running minio and all 4 are up I still don't have quorum?  Is there an easy way to check that through mc or something?

**Comment by harshavardhana** [comment]
> So even though I have four containers running minio and all 4 are up I still don't have quorum? Is there an easy way to check that through mc or something?

do you have any logs that you can share?

**Comment by tibmeister** [comment]
Here's from one of the containers, hope this is what you are looking for.
[json.log](https://github.com/minio/minio/files/1985693/json.log)

**Comment by tibmeister** [comment]
Ok, so this one's odd.  I went ahead and just uploaded a bogus txt file to the folder in the bucket, then did a remove using mc and viola, it's gone!  It seems that somehow everything kinda lost the pointer to the metadata, so that's strange to say the least.

Error: Object not found: registry-data#data

**Comment by tibmeister** [comment]
So I was able to replicate this a couple of times and it may be something with the way rexray and minio is interacting. It seems that a data folder is always created by rexray and that data folder isn’t “registered”, for lack of a better term, with the bucket until something is written to the data folder. 
Not sure if it’s an issue with minio or not at this point.

**Comment by harshavardhana** [comment]
Oh yes rexray does that automatically. If you are referring to the /data directory then yes it would be recreated unfortunately.

**Comment by nitisht** [comment]
closing this as it doesn't seem to be related to Minio @tibmeister . Feel free to reopen/comment if there are further issues.
