### ISSUE TITLE
[doc] Minio fails to detect the https protocol, shows http instead.

### ISSUE THREAD

**Issue by twisted1919** [minio/minio#5907]
I can't seem to get minio to work on https following the guide at https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio 

## Expected Behavior 
When i start minio with `sudo minio server --address "mydomain:443" /mnt/volume` i expect to be able to access `https://mydomain.com` and i expect minio to print this address in console 

## Current Behavior
Instead, minio prints: 

> Drive Capacity: 46 GiB Free  
Endpoint:  http://mydomain.com:443  
AccessKey: ...   
SecretKey: ...   
Browser Access:
   http://mydomain.com:443

And accessing  https://mydomain.com does not work and obviously  http://mydomain.com:443 is not ssl.

## Steps to Reproduce (for bugs)

1. Install minio for linux
2. Follow https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio 
3. Try to start minio in https mode as advised in above link

## Context  
I am just playing around with minio to see if it can fit a project of mine 

## Your Environment  

* Version used (`minio version`): Version: 2018-05-04T23:13:12Z
* Environment name and version (e.g. nginx 1.9.1): go version go1.10.2 linux/amd64 
* Server type and version: vps, centos 7
* Operating System and version (`uname -a`): Linux host 4.15.13-x86_64-linode106 #1 SMP Tue Mar 27 14:42:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: ...

**Comment by harshavardhana** [comment]
The doc that you are using is a deprecated doc ..have you tried using the doc here https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls

**Comment by twisted1919** [comment]
@harshavardhana - How is that deprecated? I haven't seen any note which suggest it is...?  
For the link you have sent me, that is a self signed certificate. i was looking to use let's encrypt...

**Comment by vadmeste** [comment]
@harshavardhana actually, the link address  https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio is wrong but the content is correct (certbot, no more concert)

@twisted1919 sudo minio server --address "mydomain:443" /mnt/volume will bind 443 port but it loads the certificate only if you put your public & private certificates (public.crt & private.key) in ~/.minio/certs/

**Comment by twisted1919** [comment]
@vadmeste - yeah, i did that, like i said, i followed that above link which instructed to do so.  
I am giving up and will try to put nginx in front of it and see how that goes.

**Comment by vadmeste** [comment]
@twisted1919 it should be a typo somewhere, you can join https://slack.minio.io and ping me there if you want some help

**Comment by harshavardhana** [comment]
> @harshavardhana actually, the link address https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio is wrong but the content is correct (certbot, no more concert)

@vadmeste this link is deprecated and shouldn't be referenced anywhere in our docs. It is also specifically hidden from the main page. 

> @vadmeste - yeah, I did that, like I said, I followed that above link which instructed to do so.
> I am giving up and will try to put nginx in front of it and see how that goes.

Most probably is that you don't have private.key and public.crt inside `~/.minio/certs/`

**Comment by twisted1919** [comment]
@vadmeste / @harshavardhana - I actually made it work under nginx in a few minutes, so i am good.  
I am pretty sure i have followed the tutorial word by word, i don't think i made a mistake. If anyone is willing to try and share how it worked, would be awesome, otherwise, i'll stick with nginx for the days to come.

**Comment by harshavardhana** [comment]
@twisted1919 here is what I did locally

```
 prtsc : harsha : « » .minio » certs : mv private.key-1 private.key
 prtsc : harsha : « » .minio » certs : mv public.crt-1 public.crt
 prtsc : harsha : « » .minio » certs : pwd
/home/harsha/.minio/certs
 prtsc : harsha : « » .minio » certs : cd
 prtsc : harsha : ~ : minio server ~/test

Drive Capacity: 43 GiB Free, 156 GiB Total

Endpoint:  https://192.168.1.17:9000  https://10.96.51.1:9000  https://172.17.0.1:9000  https://192.168.121.1:9000  https://192.168.122.1:9000  https://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 
SQS ARNs:  arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis arn:minio:sqs::1:webhook

Browser Access:
   https://192.168.1.17:9000  https://10.96.51.1:9000  https://172.17.0.1:9000  https://192.168.121.1:9000  https://192.168.122.1:9000  https://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio https://192.168.1.17:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

So I am not sure what might be a problem on your end.

**Comment by twisted1919** [comment]
@harshavardhana - let me start all from scratch and see how this goes. I'll get back to you soon.

**Comment by twisted1919** [comment]
@harshavardhana - I got it working, the issue is that i was running it with `sudo minio ...` which seem to place the `.minio` under `/root` and then i was copying the certs under `/home/user`, which of course didn't help. I corrected all these and now it works perfectly. 
Thanks a lot for your time with this ;)

**Comment by vadmeste** [comment]
The documentation needs to be fixed though. I am reopening this.

**Comment by harshavardhana** [comment]
> The documentation needs to be fixed though. I am reopening this.

Are you going to fix the documentation @vadmeste?

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/cookbook/pull/221, closing this.
