### ISSUE TITLE
Minio fails to start due to a Postgres notification  without saying the detailed error

### ISSUE THREAD

**Issue by ftalo** [minio/minio#5908]
## Expected Behavior
In the config,json file I setup a notification to a Postgres system. I am sure that the Postgres instance is running and reachable from the machine where Minio is running , the table exists and the credentials are correct. However when I try to start the Minio process it fails to start with the error "Error: Unable to initialize notification system". I would expect somehow to have a more descriptive error when Minio fails to start to troubleshoot the problem

## Current Behavior
There is no way to get a more descriptive and detailed explanation of the error if Minio fails to start for any reason (Postgres notification in this specific case). So it is impossible to troubleshoot the problem

## Possible Solution
Add a more detailed log with error information even when Minio starts to fail

## Steps to Reproduce (for bugs)
1. setup a Postgres notification in the config.json file specifying  not existing host to provoke the error
2. launch minio and check that the only error information available is "Error: Unable to initialize notification system"

## Context

We want Minio to send notification to Postgres in order to process immediately data files submitted from external providers. Those file contain data that we want to store in our internal database.

## Your Environment

* Version used (`minio version`): 23
* Server type and version: Linux Redhat
* Operating System and version (`uname -a`): Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: http://europepmc.org

**Comment by deekoder** [comment]
the fix will be available today. We are fixing the error messages.

**Comment by ftalo** [comment]
Can I run the minio update command to get the latest version with the fix included? Will be the more specific message printed to the console?

**Comment by harshavardhana** [comment]
> Can I run the minio update command to get the latest version with the fix included? Will be the more specific message printed to the console?

@ftalo yes you can run `minio update` to update the binary locally in-place. With new changes, it should be printed and once you have it printed please send it to us here...

**Comment by ftalo** [comment]
I did it and the error was showed : SSL is not enabled on the server. That helped a lot to fix the problem on my side. Thanks
