### ISSUE TITLE
Merge large-bucket & erasure documentations in one link

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5910]
## Expected Behavior
It is easier for users to have one doc page in which they can understand erasure and how many disks (infinite) they can use.

## Current Behavior
They are two separate doc pages for that.

## Possible Solution
A new page for more simple explanation

## Steps to Reproduce (for bugs)
See https://docs.minio.io/docs/minio-large-bucket-support-quickstart-guide and https://docs.minio.io/docs/minio-erasure-code-quickstart-guide

## Your Environment
All

**Comment by deekoder** [comment]
Will take this under consideration for the future. Rob may be working on this aspect.

**Comment by deekoder** [comment]
Rob will address this in future. Closing this for now.
