### ISSUE TITLE
browser : allow to upload a file with drag and drop

### ISSUE THREAD

**Issue by ppawlak** [minio/minio#5915]
A lot of websites support uploading a file with drag & drop nowadays. It would be very convenient.

**Comment by harshavardhana** [comment]
We do support drag and drop only on macOS platforms.

**Comment by ppawlak** [comment]
I made a test before reporting the issue and it didn't work: I was dragging the file too low on the page. By dragging to the top of the page it is working indeed.

Sorry for reporting this false issue. Maybe you can improve the interface to make it clearer drag & drop is supported and where to drop the file. And support other platforms too (I am on macOS right now)

Thank you for the reply.

**Comment by deekoder** [comment]
@ppawlak  the draggable region is on the top only. Typically you are correct, it's in the center of the page (learning from google drive, dropbox etc about this experience). We will revisit this when we plan our next big ux refresh.

**Comment by nitisht** [comment]
Closing now as won't fix and moving it to new ux milestone for activation after we clear our current backlog.
