### ISSUE TITLE
mc admin info does not work when a non default region is set in Minio server

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/minio#5918]
Reported by brauliobo in #general Slack channel.

## Expected Behavior
`mc admin info myminio/` should always work for whatever region.

## Current Behavior
`mc admin info myminio/` doesn't work when Minio server is set with a non default region, like us-west-2

> mc: <ERROR> Cannot get service status. The authorization header is malformed; the region is wrong; expecting 'us-east-1'.

## Steps to Reproduce (for bugs)

1. Set us-west-2 in ~/.minio/config.json
2. Run minio server
3. mc admin info myminio/

**Comment by harshavardhana** [comment]
This is already fixed and released.
