### ISSUE TITLE
preferred-challenges tls-sni

### ISSUE THREAD

**Issue by soloturn** [minio/minio#5922]
the docu here:
https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio

says:
certbot certonly --standalone --preferred-challenges tls-sni -d myminio.com --staple-ocsp -m test@yourdomain.io --agree-tos

i am getting:
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

is this certbot call still correct? the letsencrypt docu here:
https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983

says:
You need to upgrade your Certbot. Let’s Encrypt permanently disabled the TLS-SNI-01 challenge 1.2k due to a security report, as of 2018-01-09.

Certbot 0.21.0 was released on 2018-01-17 2.7k. It adds support for the HTTP-01 challenge to the Apache and Nginx plugins. If you have installed Certbot from your OS package manager (that is, if you use the certbot or letsencrypt commands rather than certbot-auto), version 0.21.0 probably isn’t available yet. You should encourage the Certbot package maintainers for your system to provide a newer version. In the meantime, you can install Certbot through certbot-auto 5.8k which will automatically install the latest version.

**Comment by harshavardhana** [comment]
We will update the doc thanks for letting us know @soloturn

**Comment by deekoder** [comment]
@soloturn will you be able to send us a pr to fix this in our docs?

**Comment by soloturn** [comment]
@deekoder which repo is this in? i did a grep in the minio repo - but either did it wrong or it is somwhere else ..

**Comment by nitisht** [comment]
@soloturn it is in minio/cookbook reop here: https://github.com/minio/cookbook/blob/master/docs/generate-lets-encypt-certificate-using-certbot-for-minio.md
