### ISSUE TITLE
Unable to setup Minio-Kafka on local devopment mode

### ISSUE THREAD

**Issue by abraarsyed** [minio/minio#5924]
## Expected Behavior

I am trying to setup Minio with Kafka on my local machine using the documentation provided [here](https://docs.minio.io/docs/minio-bucket-notification-guide) under `Publish events via Kafka` section.

I have started the minio server, zookeeper and kafka server and then I am using the minio client to add events but it giving error wrt ARN. I am getting the following error:
`mc: <ERROR> Cannot enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN`

Hence not able to add events and complete the steps required for publishing events via Kafka

## Current Behavior

I have successfully created a minio bucket named as `smart-gallery` but everytime I try to add events, I get the following error:
`mc: <ERROR> Cannot enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.`

I am using the following command to add the events:
`mc events add local/smart-gallery arn:minio:sqs::1:kafka`

## Steps to Reproduce (for bugs)

1. Run minio server through Docker:
  a. `docker pull minio/minio`
  b. `docker run -p 9000:9000 --name minio \
      -v /mnt/data:/data \
      -v /mnt/config:/FULL_PATH_TO_HOME/.minio \
      minio/minio server /data`

2. Run zookeeper and Kafka server locally
3. Create a minio bucket: smart-gallery using the browser by going to localhost:9000
4. Add Kafka endpoint to Minio (Mount ~/.minio to docker container)

## Context

I am trying to create a minio-kafka setup such that when I add images to minio bucket it should get notified or published in Kafka so that it can be consumed by other applications through Kafka

## Your Environment

* Version used (`minio version`): 2018-04-27T23:33:52Z
* Version used for Kafka: 1.1.0
* Operating System and version (`uname -a`): Ubuntu 16.04.4 LTS

**Comment by harshavardhana** [comment]
We will try to reproduce this and get back to you..

**Comment by Praveenrajmani** [comment]
Hey @abraarsyed , Its working fine for me here . Can you share me the config ?

**Comment by abraarsyed** [comment]
Hey @Praveenrajmani, can you help me in understanding what could be the possible issue? Here is my config which I am mounting in minio docker container as config.json:

`{
	"version": "23",
	"credential": {
		"accessKey": "27UJU84QOP37MR99M6JZ",
		"secretKey": "8BdKHAwaBrchtDRAjiA+2bhYVhYKiqqo9EgyHrcm"
	},
	"region": "",
	"browser": "on",
	"domain": "",
	"storageclass": {
		"standard": "",
		"rrs": ""
	},
	"cache": {
		"drives": [],
		"expiry": 90,
		"exclude": []
	},
	"notify": {
		"amqp": {
			"1": {
				"enable": false,
				"url": "",
				"exchange": "",
				"routingKey": "",
				"exchangeType": "",
				"deliveryMode": 0,
				"mandatory": false,
				"immediate": false,
				"durable": false,
				"internal": false,
				"noWait": false,
				"autoDeleted": false
			}
		},
		"elasticsearch": {
			"1": {
				"enable": false,
				"format": "",
				"url": "",
				"index": ""
			}
		},
		"kafka": {
			"1": {
				"enable": true,
				"brokers": ["localhost:9092"],
				"topic": "smart-gallery"
			}
		},
		"mqtt": {
			"1": {
				"enable": false,
				"broker": "",
				"topic": "",
				"qos": 0,
				"clientId": "",
				"username": "",
				"password": "",
				"reconnectInterval": 0,
				"keepAliveInterval": 0
			}
		},
		"mysql": {
			"1": {
				"enable": false,
				"format": "",
				"dsnString": "",
				"table": "",
				"host": "",
				"port": "",
				"user": "",
				"password": "",
				"database": ""
			}
		},
		"nats": {
			"1": {
				"enable": false,
				"address": "",
				"subject": "",
				"username": "",
				"password": "",
				"token": "",
				"secure": false,
				"pingInterval": 0,
				"streaming": {
					"enable": false,
					"clusterID": "",
					"clientID": "",
					"async": false,
					"maxPubAcksInflight": 0
				}
			}
		},
		"postgresql": {
			"1": {
				"enable": false,
				"format": "",
				"connectionString": "",
				"table": "",
				"host": "",
				"port": "",
				"user": "",
				"password": "",
				"database": ""
			}
		},
		"redis": {
			"1": {
				"enable": false,
				"format": "",
				"address": "",
				"password": "",
				"key": ""
			}
		},
		"webhook": {
			"1": {
				"enable": false,
				"endpoint": ""
			}
		}
	}
}`

P.S.: Not able to share the json file hence pasted the Javascript object here. Hope it works out in helping you understand the config details. Let me know if there is a better way to share it.

Also, I have mentioned the command as well that I am using to mount the config to docker container. Am I doing something wrong here?

**Comment by Praveenrajmani** [comment]
Hey @abraarsyed , Can you see the `ARN` while running `docker run -p ..` ?? , the config is fine , i suspect the error in docker run . And will be much helpful if you post here the result log for the `docker run`

**Comment by abraarsyed** [comment]
@Praveenrajmani You are right! I think I am not mounting my config properly in the docker container. Can you help me correct it? I deleted the old container and recreated and got the following output:

![image](https://user-images.githubusercontent.com/6316109/40231814-1e0251c6-5aba-11e8-9570-07495f02c4e3.png)

Also, how to I see the `ARN` while running the `docker run` command?

**Comment by abraarsyed** [comment]
I finally got it to work! Thank you for all your help :)

Learnt two things here:
1. The documentation works well for non docker minio setup. If we are using minio docker setup then the config.json cannot have `localhost` for kafka broker since it is inside the docker and not host machine. Planning to update the documentation regarding the same. What do you think?
2. Either cases, mc config needs to be updated as well with access key and secret key for granting permission to add events through mc

**Comment by Praveenrajmani** [comment]
Hi @abraarsyed , 
Yes there should be a classification here in the doc, Feel free to send a PR.
And on the second , there should be a leading `mc config host add` before the `mc events add` in the doc.
Thanks for your inference .

**Comment by YasminBZ** [comment]
Hello @abraarsyed  , please how did you solve that problem cause i'm having the same issue, im using minio in a kubernetes cluster and always it's givin me the same error as you had , any help please.

Thank you

**Comment by abraarsyed** [comment]
Hey @white-cloud, I will try my best to help you out. Can you tell me if you updated your config.json with the actual IP address instead of localhost? Also, you need to update the mc config as well but that is the next step

**Comment by YasminBZ** [comment]
Hello @abraarsyed  Thank you for your answer 
for the config.json of the minio server i modified it this way:
"kafka": {
    "1": {
        "enable": true,
        "brokers": ["localhost:9092"],
        "topic": "bucketevents"
    }
}

I'm using minio in a kubernetes cluster of 4 nodes 1 master and 3 workers.
i installed it using the following commands:
wget https://dl.minio.io/server/minio/release/linux-amd64/minio
chmod +x minio
./minio server /data
Thank you again.

**Comment by abraarsyed** [comment]
I had mounted my config.json when I am running the docker container for minio. So, I had changed the following line: 
"brokers": ["localhost: 9092"]

Change it from localhost to the IP address of the docker container. That worked for me. Can you try the same and let us know if it works?

**Comment by YasminBZ** [comment]
Hello, you mean the adress Ip of the pod running the minio server, is that what you mean ??

**Comment by abraarsyed** [comment]
Yes :)

**Comment by YasminBZ** [comment]
Thank you :) i will try it and let you know :)
