### ISSUE TITLE
Log error if same ip/port/export is not used on all the minio servers

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5925]
// easier to describe this issue without following the template.

It is not an uncommon mistake to provide a different IP or different export on one of the minio servers in a distributed erasure setup. In such a case we should show an error log.

For ex. on 
server1: http://minio1/tmp/export http://minio2/tmp/export http://minio3/tmp/export http://minio4/tmp/export
server2: http://minio1/tmp/export http://minio2/tmp/export http://minio3/tmp/export http://minio4/tmp/export
server3: http://minio1/tmp/export http://minio2/tmp/export http://minio3/tmp/export http://minio4/tmp/export
server4: http://minio1/tmp/export http://minio2/tmp/export http://minio3/tmp/export http://minio4/tmp/exprot

On server4 notice the mistake `exprot` instead of `export` this will cause mino server to print `Waiting for the first server to format the disks.` indefinitely.

on #general:
```
what seems to be the problem ?
I assume 1h is enough to deal with disk formatting
```

This mistake, recently, even cost us a lot of time at a customer site.

Expected behavior: Minio should log an error indicating the mistake.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/issues/3475 there is an older bug on this already which needs to be fixed.

**Comment by harshavardhana** [comment]
Duplicate of https://github.com/minio/minio/issues/3475
