### ISSUE TITLE
Credential is mal-formed error while running in Docker Compose

### ISSUE THREAD

**Issue by Southclaws** [minio/minio#5928]
Hi, I'm in the midst of moving some of my side projects from regular `docker run` scripts to Docker Compose. I've gotten stuck while moving one app that uses Minio, it encounters the error

```
Error parsing the X-Amz-Credential parameter; the Credential is mal-formed; expecting \"<YOUR-AKID>/YYYYMMDD/REGION/SERVICE/aws4_request\".
```

when attempting to check if a bucket exists, so I know it's reaching the server it's just not getting the correct response. This was using the Go client, [I opened an issue there](https://github.com/minio/minio-go/issues/984) but was directed here.

## Expected Behavior

My old, fairly simple deployment method was simple a run command:

```
docker run \
	--name minio \
	--detach \
	--publish 9001:9000 \
	--volume /data/minio:/data \
	minio/minio \
	server /data
docker network connect minio minio
```

There's a network named `minio` which both the Minio and my app container are connected to, the app simply connects to `http://minio:9000` and everything works fine.

## Current Behavior

In compose however, this isn't working as expect and I'm not sure why. I'm fairly certain everything is set up the same, there's a minio network:

```yml
networks:
    minio:
        driver: bridge
        internal: true
```

And the minio service:

```yml
    minio:
        image: minio/minio
        command: server /data
        volumes:
            - '/data/minio:/data'
        networks:
            - minio
```

As far as I can tell, the setup is the same so I'd expect that using `http://minio:9000` with an internal network would work fine in compose.

## Context

My goal was to shift away from flaky scripts to a proper declarative docker-compose deployment (even though they are only small personal projects) and so far, everything else has worked fine (various databases and container communication) It's just minio that brought the whole thing to a halt. Could this be related to the fact that I'm using a domain name to access the container and minio isn't aware of that or something? I have mongodb set up the exact same way (network+domain) and that works fine.

## Your Environment

* Version used (`minio version`): `RELEASE.2018-05-11T00-29-24Z`
* Environment name and version (e.g. nginx 1.9.1): Docker 17.09.0-ce Compose 1.21.2
* Server type and version: bare metal/dedicated
* Operating System and version (`uname -a`): `Linux southclaws 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project: https://github.com/Southclaws/samp-objects-api

**Comment by harshavardhana** [comment]
Would you be able to test with latest release @Southclaws ?

**Comment by Southclaws** [comment]
Just tested with `RELEASE.2018-05-11T00-29-24Z` and the result was the same.

**Comment by sam-jg** [comment]
@Southclaws 
Just had this issue as well. Our problem was that our access key and secret key were randomly generated and would sometimes have a '/' in them. Easy fix to just generate keys with only alphanumeric characters.

Not sure if this is causing your issue though.

**Comment by Southclaws** [comment]
That was the issue, thanks!

It would be very simple but very useful to have the Minio server catch this early on with a helpful error message notifying the user of invalid characters in the key.
