### ISSUE TITLE
Security concern on file sharing

### ISSUE THREAD

**Issue by LissenVos** [minio/minio#5929]
Hi

I am testing the file sharing features on minio. Currently I am using as NAS as backend storage and through minio to provision S3 bucket and storage. I found the the sharing permission can be a security whole to take whatever file you want. 

For example, I have got a bucket and list of files

bucket1/abc.txt
bucket1/cde.txt
bucket1/efg.txt

1. Share a file called abc.txt and it will generate a sharing link for public access for limited of time
2. If I remove abc.txt and change cde.txt to abc.txt, I can still access to cde.txt which are not suppose to be accessed for public 

Would it be possible to check the hash before the file to be accessed in public link?

**Comment by harshavardhana** [comment]
How are you changing abc.txt to cde.txt ?

**Comment by LissenVos** [comment]
>bucket1/abc.txt (I shared this file)
>bucket1/cde.txt

If I swap two filename, meanings that
> bucket1/abc.txt to bucket1/cde.txt (This one cannot be shared. This is right because filename, cde.txt, haven't been shared before) 
> bucket1/cde.txt to bucket1/abc.txt (Original filename cde.txt becomes shared with name abc.txt, which is not suppose to be shared - content of this file still be the original content of cde.txt)

I suggest to check the hash of file before every access from public. Once the hash has been changed for corresponding public link, minio server should revoke the file from public access.

**Comment by harshavardhana** [comment]
Swap meaning are you copying the content of abc.txt from cde.txt ?

**Comment by LissenVos** [comment]
No. Changing its name only without the file content changed

**Comment by aead** [comment]
@LissenVos 

Am I understanding you correctly:
 - You create (at least) 2 objects (e.g. `bucket/abc.txt` and `bucket/def.txt`
 - Than you create a sharing link for the first object `bucket/abc.txt`.
 - After that you remove the object (`bucket/abc.txt`).
 - Now you copy the 2nd object (`bucket/def.txt`) to `bucket/abc.txt` - This is basically a rename. Notice  that S3 does not support a object rename as known from file systems.
 - Now you're saying the previously shared link still works?

**Comment by LissenVos** [comment]
Yes. You are right! Is this possible to be solved on your side?

**Comment by aead** [comment]
>Is this possible to be solved on your side?

No, we cannot fix this. This is "expected" behavior and AWS handles that exactly the same way. A shared link is basically a reference to an object - the access control verification has no knowledge about the content.

Possible work-a-round: Use SSE-C (server-side-encryption) and change the encryption key if you rename/copy the object to a new object-name. That way a GET on the object will fail unless the user/client using the shared link also knows the new SSE-C key.
