### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by mickael-kerjean** [minio/minio#5930]
I've received a feature request to integrate Minio in my [project](https://github.com/mickael-kerjean/nuage). 

That's basically a kindof Filezilla FTP except it's web based and with support for many backend. That's official, we now have full support for Minio `:)` => https://nuage.kerjean.me.

Keep going on the great job!

**Comment by nitisht** [comment]
@mickael-kerjean that is great! Can you please send a PR to https://github.com/minio/awesome-minio to add your project. Closing this issue.
