### ISSUE TITLE
Use session ID to detect minio restarts

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5937]
With the new HTTP POST style RPC we will not be able to detect if a peer is restarted. i.e after a peer is restarted we have to re-evaluate its format.jsons. This is so that we can decide if the disk position has changed.

To fix the problem, we can use a session ID at the RPC layer to know if a peer is restarted. i.e Each minio server will have a global session ID which is initiated at boot time. If a minio process is restarted, new session ID gets generated and hence it will reject all the calls from the peers that use older session ID in the RPC calls. In such a case the remote peer will read format.jsons again to re-evalute it.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/issues/6570 this is another variant of the same issue.

**Comment by harshavardhana** [comment]
Is this fixed @krishnasrinivas @kannappanr?

**Comment by kannappanr** [comment]
Yes @harshavardhana . Fixed by #7227
