### ISSUE TITLE
Minio on Kubernetes returns HTTP Connection Refused on all requests

### ISSUE THREAD

**Issue by hatt** [minio/minio#5938]
When deployed on Kubernetes 1.9.5 on vSphere with either the Helm chart from git HEAD (chart version 1.2.0) or the manifest generator on minio.io, the pods and service come up but have no logs and all connections are refused. When checking the containers with netstat, there are no processes listening.

Storage backend is vSphere VMFS datastore and it successfully attaches storage to the pods. No ingress or load balancers were used.

## Steps to Reproduce (for bugs)
`helm install --set "mode=distributed,image.tag=latest" stable/minio`

## Context
When port-forwarding and connecting via the web UI or the `mc` client, all HTTP requests return Connection Refused, such as in mc:
```mc: <ERROR> Unable to initialize new config from the provided credentials. Get http://localhost:9000/probe-bucket-sign/?location=: Connection closed by foreign host http://localhost:9000/probe-bucket-sign/?location=. Retry again.```

In the port-foward log, I can see a socat error on the socket:
```
Forwarding from 127.0.0.1:9000 -> 9000
Handling connection for 9000
E0516 10:18:27.594594   30912 portforward.go:331] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 8f87af7c76b6512dd3ba1aa89f854555a27b0afd8c52f10adf6dd737629d802c, uid : exit status 1: 2018/05/16 10:18:26 socat[63738] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused

```

## Your Environment
* Version used (`minio version`): Version: 2018-05-11T00:29:24Z
* Server type and version: Kubernetes 1.9.5 on vSphere 5.5
* Operating System and version (`uname -a`): CentOS 7.4.1709 Linux 3.10.0-693.21.1.el7.x86_64

**Comment by nitisht** [comment]
@hatt I checked the `kubectl describe` output you shared, looks fine. Do you mind retrying with couple of changes in the helm startup command

`helm install --set "image.tag=RELEASE.2018-05-11T00-29-24Z" stable/minio` 

This will start current minio release in standalone mode, this to confirm if there are network issues or something else

**Comment by hatt** [comment]
Thanks @nitisht, standalone mode works fine but I think you're onto something with networking. Testing with `kubectl exec`, the pods don't seem to be able to talk to each other either.

**Comment by nitisht** [comment]
> Testing with kubectl exec, the pods don't seem to be able to talk to each other either.

does the Minio container start? are you able to see Minio startup banner or any errors?

**Comment by hatt** [comment]
The container starts but there's no logged output at all in the pod or the container.

**Comment by nitisht** [comment]
this is strange, will it be possible to allow access to your setup remotely?

**Comment by hatt** [comment]
Unfortunately not, the datacentre has no external facing connectivity. We could take this to slack if that's easier though.

**Comment by nitisht** [comment]
@hatt were you able to run the image that I shared

**Comment by nitisht** [comment]
@hatt any progress here?

**Comment by hatt** [comment]
Hi @nitisht, I've been a bit busy with life so apologies for the slow response. I ran the image you sent me and the only log output was a message about trying to connect, could definitely be a network problem:

    Trying to connect to host : minio-qa-0.minio-qa.default.svc.cluster.local and time elapsed 99437619661726

**Comment by nitisht** [comment]
>  I've been a bit busy with life so apologies for the slow response. 

No problem, thanks for the response @hatt . Yes, looks like pods are not able to talk to each other.

**Comment by hatt** [comment]
Great, that's progress then. Any idea how I could get some more details on the actual problem? Normally I'd expect to see a log error like a timeout or DNS failure or similar.

**Comment by nitisht** [comment]
> Normally I'd expect to see a log error like a timeout or DNS failure or similar.

We don't timeout while waiting for the remote pod to respond, this is because there is no uniform/standard timeout number for platforms like Kubernetes - that can run on wide variety of hardware.

Also, DNS failure doesn't seem to be a cause as that would have been logged. 

Can you try pinging one pod from another, and see if that works

**Comment by nitisht** [comment]
any updates on this @hatt

**Comment by simisoz** [comment]
Hi also had the same problem. The pods can't ping each other. The distributed option doesn't work.

**Comment by nitisht** [comment]
> The pods can't ping each other. The distributed option doesn't work.

You need to make sure Pods are able to talk to each other for distributed Minio to work. May be Kubernetes documentation will help 
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#are-the-pods-working

**Comment by nitisht** [comment]
@hatt I am going to close this due to no response. But feel free to reopen/get back if it doesn't work even after pods connectivity is fixed.
