### ISSUE TITLE
SHA256 mismatch installing latest stable via homebrew

### ISSUE THREAD

**Issue by jonathandean** [minio/minio#5944]
I am unable to install the latest stable version via homebrew on a Mac:

```
> brew install minio/stable/minio
==> Installing minio from minio/stable
==> Downloading https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2018-05-16T23-35-33Z
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0f553f6b6c91bd9d98f7f1ce59a40df0e2ff99085a5ab048d5190ec44066086d
Actual: b2be7de3709d4dad3bd0f77384599d2fd4b040541dbc4ccfb8a5a912f7ec5f18
```

Removing the cache version from `/Users/<user>/Library/Caches/Homebrew/` will allow it to re-load the file but it still does not work.

## Expected Behavior

Successful installation

## Current Behavior

Unable to install

## Possible Solution

The file at https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2018-05-16T23-35-33Z is corrupt?

## Steps to Reproduce (for bugs)

1. brew install minio/stable/minio

## Context
Trying to install latest stable on a Mac via homebrew

## Your Environment

* Version used (`minio version`): latest stable
* Environment name and version (e.g. nginx 1.9.1): Homebrew 1.6.3
Homebrew/homebrew-core (git revision 3e6826; last commit 2018-05-16) 
* Operating System and version (`uname -a`): macOS High Sierra 10.13.4 (17E202) -- Darwin Jons-iMac.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

**Comment by harshavardhana** [comment]
Fixed in https://github.com/minio/homebrew-stable/commit/e7506d2cc30840ebf9cf70260fcc817deeda3106

**Comment by jonathandean** [comment]
works now, thanks so much!
