### ISSUE TITLE
Run minio under a subdirectory 

### ISSUE THREAD

**Issue by diogojesus95** [minio/minio#5947]
## Expected Behavior

run minio under cdn.example.com/v2

## Current Behavior

cdn.example.com/v2 access denied (missing token)

## Steps to Reproduce (for bugs)

Since we have a simple and internal cdn in our company we never used minio since we didn't really needed a token. But now we must use it to generate tokens over the client invoices to implement to the actual user interface where the person can download his/her contract, etc, etc...
The problem is that the current cdn (simple nginx setup) is being used by our internal mail system to retrieve the actual contracts (print and send to costumer).
So I added the current config to my nginx
```
  location  /v2  {
        rewrite /v2/(.*) /$1 break;
        proxy_pass http://localhost:9000;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```
While this code should work, it actually doesn't because v2 will be tagged as a bucket and will give access denied (missing token). 

So the question is simple. Can I run minio under my actual config? 
(Nginx simple setup with a web root directory a few folders with invoices etc...) I just want to recreate the actual minio under the /v2 and generate links like https://cdn.example.com/v2/bucket/object.pdf

Thank you,
Diogo Jesus

## Your Environment

* Version used (`minio version`): Version: 2018-05-16T23:35:33Z
* Environment name and version (e.g. nginx 1.9.1): nginx version: nginx/1.10.3
* Server type and version: Debian Stretch
* Operating System and version (`uname -a`): Linux cdn 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 GNU/Linux
* Link to your project: -

**Comment by krishnasrinivas** [comment]
```
        rewrite /v2/(.*) /$1 break;
```

Nginx cannot change the path like this as there will be a signature mismatch. i.e for signature calculation the client will include the path, on the server side when it computes the signature again to verify if the path has changed, the server computed signature will be different.

The signature-v4 standard we use is defined by AWS.

**Comment by diogojesus95** [comment]
if we could run minio under cdn.example.com:9000/v2 then we wouldn't have signature mismatch right?

**Comment by harshavardhana** [comment]
> if we could run minio under cdn.example.com:9000/v2 then we wouldn't have signature mismatch right?

Minio's context root is '/' and this cannot be configured. @diogojesus95 - so changing Paths in the manner you are thinking it's not possible with AWS S3 signature.

**Comment by harshavardhana** [comment]
> Minio's context root is '/' and this cannot be configured. @diogojesus95 - so changing Paths in the manner you are thinking it's not possible with AWS S3 signature.

Closing as this is not possible in accordance with 
- https://github.com/minio/minio/issues/5947#issuecomment-390788999
- https://github.com/minio/minio/issues/5947#issuecomment-415342037

**Comment by delfer** [comment]
@diogojesus95 you do not need to rewrite any urls for your CDN. Just create bucket named `v2` in your Minio))) 🥇

**Comment by ElusiveMind** [comment]
I was able to proxy using apache. I proxied /minio to my minio port and it works.

Working with the API is tricky, but I am only using it for automatically making backups available and all the backups are uploaded from the box where MinIO is - so it just uses localhost:9000 (I am using a docker setup).

Apache:
```
ProxyPass /minio http://minio:9000/minio
ProxyPassReverse /minio http://minio:9000/minio
```

Docker-Compose:
```yaml
  minio:
    image: minio/minio
    container_name: minio-xxxx
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: xxxxxxx
      MINIO_SECRET_KEY: xxxxxx
    networks:
      xxxx-network:
        aliases:
          - minio
    restart: unless-stopped
```

**Comment by wgerlach** [comment]
I ran into the same issue and used this work-around for nginx location `/minio`. It uses the UserAgent field to detect minio traffic. This example works only for the official Minio client. (For curl you would have to add a custom header like this `-H "User-Agent: MinIO"`.) In the server section add this rewrite:
>  if ($http_user_agent ~* "^MinIO") {
>      rewrite ^(.*)$ /minio/$1;
>   }

In the location section remove the `/minio`-prefix
> rewrite ^/minio/(.*)$  $1 break;

I think this is pretty ugly but at least in my tests it worked so far. :-)

**Comment by bpetty-formfast** [comment]
Running into this exact same issue.  It should be possible to make this configurable.
Instead of closing this issue, could we make it a feature request, @harshavardhana ?

**Comment by harshavardhana** [comment]
> Running into this exact same issue. It should be possible to make this configurable.
> Instead of closing this issue, could we make it a feature request, @harshavardhana ?

No we will not be supporting it @bpetty-formfast it's already explained why.

**Comment by AaronJan** [comment]
I bypassed the signature problem.

Let's say your host is `storage.com`, and MinIO is under `storage.com/minio`, therefor, the endpoint should be `http://storage.com/minio`. But if you presigning URLs using this endpoint, you will get a signature mismatched error.

Here comes the high tech stuff.

Just presign URLs using `http://storage.com`, then insert `/minio` in the middle of the presigned URL.
