### ISSUE TITLE
[Request] Generate 1 time only token

### ISSUE THREAD

**Issue by diogojesus95** [minio/minio#5955]
## Possible Solution

When using fGetObject with javascript we would like to generate a token for 1 time read only. Means that everytime that this function is used a new token will be generated. Then if we copy the link the token won't be available and a new one with the function must be generated again.
The main idea is to share only once the link.

## Your Environment

* Version used (`minio version`): Version: 2018-05-16T23:35:33Z
* Environment name and version (e.g. nginx 1.9.1): nginx/1.10.3
* Server type and version: Debian Stretch
* Operating System and version (`uname -a`): Linux cdn 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 GNU/Linux
* Link to your project: -

**Comment by kannappanr** [comment]
@diogojesus95 I am not sure I understand your requirement properly. In the case of Minio, if you are using `fGetObject`, you are assumed to be the owner of the object, so there is no sharing involved. If you want to share and want to have a one time download token, there is no support like that in S3. Please look at `https://stackoverflow.com/questions/19467460/how-can-i-create-a-one-time-download-link-with-amazon-s3` for a similar question.

**Comment by diogojesus95** [comment]
So from what I understand from that link, I can generate the token for a few minutes instead of 1 time only. Is it right? I didn't implement yet the code, since I am first studying all options available for our service. 
Like I said we need something similar to this to store all client invoices. Then the client goes to portal.website.com and after login he/she can download his/her invoice from last month. But data must be encrypted and secured by a token, let's say if I store invoices by name (cdn.website.com/invoices/Diogo_Jesus.pdf) the client sees the PDF link and can change his name to someone else and retrieve someone else invoice.

**Comment by kannappanr** [comment]
You can look at https://docs.minio.io/docs/javascript-client-api-reference#presignedGetObject for more information. The URL that is being generated will not be of the form that you are talking about, so that will not be an issue.

**Comment by kannappanr** [comment]
@diogojesus95 Closing this issue. If you have further questions, please feel free to reach out to us.
