### ISSUE TITLE
Behaviour differs from s3 when a path contains double slash

### ISSUE THREAD

**Issue by rozuur** [minio/minio#5958]
## Expected Behavior

Upload a file to an s3 path with a double slash
```
touch empty
s3cmd put s3://bucket/path//empty
s3cmd ls  s3://bucket/path//empty # File exists at the path shown
```

## Current Behavior

The same behaviour fails with minio  and instead of  
`s3cmd ls s3://bucket/path//empty  # No file`
One should remove the double slash and then proceed
`s3cmd ls s3://bucket/path/empty  # File exists`

## Possible Solution

To be compatible with s3 following location should also work
`s3cmd ls s3://bucket/path//empty `

## Your Environment

* Version used (`minio version`):
Version: 2017-11-22T19:55:46Z
Release-Tag: RELEASE.2017-11-22T19-55-46Z
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Darwin
* Link to your project:

**Comment by harshavardhana** [comment]
Duplicate of https://github.com/minio/minio/issues/5874

**Comment by kannappanr** [comment]
As mentioned in the original issue, AWS does not used filesystem to store the objects, whereas Minio does. But, you also cannot use tools like `s3Cmd` to replicate a bucket in AWS to a local folder, when it contains object names with double slashes. Closing this issue as working as intended.
