### ISSUE TITLE
[faq] [Question] Understand the space capacity

### ISSUE THREAD

**Issue by xp-1000** [minio/minio#5964]
I would like to understand how space capacity is decided depending of the configuration.

## Current Behavior
I read your documentation and it is probably me who don't right understand something. sorry for that.

## Possible Solution
A dedicated documentation for those, as me, who don't understand with the existing documentation

### My situation 

I currently have a personal server where I host some services for me and some friends and family, especially a nextcloud instance to store our files.

I would like to setup high availability on that and the first thing I need to make a distributed storage across my servers (at the moment, only the existing one and a new one I will setup for HA)

I already tested some solutions as glusterfs and drbd. It works but this is not exactly the same scope of minio as it is an object storage (among other things).
I also tested minio as standalone instance and I like very much, thanks for your work !

### What I understand

Reading your documentation I understood multiple things that make clear I will have to change a lot my current installation that is not suited for minio.

For instance, I currenlty have a RAID 5 (hardware) on my server with 7x2TB = 12B usable I thought do something similar on my new one to replicate "2 big disks over wan" as I did for glusterfs/drbd. Nevertheless, with minio I understand according the documentation that distributed instance will automatically enable erasure code which needs 4 disks minimum. So I will probably need to drop my raid setup first because minio already manages parity by itself and also because with 2 servers I will need at least 2 disks by servers to have 4 disks and make it possible distributed minio instance.

I also understand that contrary to the RAID5 where capacity usable = n-1 disks capacity, with minio the storage capacity stays the same but when we put a new object it will take more space than its real size depending of the way it is stored (RR or storage) and the storage class configuration. 

So if I right understood that, with 6x2 TB disks, we have :

* 6 TB usable with RAID1 and files will use a space similar to its size 
* 12 TB usable with minio and files will use a space = 2x its size when they are stored with standard class configured with default configuration (=N/2 similar to RAID1)

### What I don't understand

When I run minio command, it will display the space as following : 

```
Drive Capacity: 20 GiB Free, 20 GiB Total
Status:         4 Online, 0 Offline. 
```

In fact I don't understand how the total space is decided by default, its evolution depending the configuration and also how is handle disks with different spaces in a cluster.

As I explain above, if I right understood, the total space should not change with storage class configuration because it is how file fill space and not how total space is calculated. And I confirm according to my tests that storage class configuration seems to not have incidence on the total space displayed.

I done some tests on my kubernetes testing env with 4 nodes with each one disk : 

* 6+6+6+6 GB = 12 GB => N/2
* 6+8+10+12 GB = 12 GB => 33%
* 14+12+15+10 GB = 20 GB => 39%

Last thing, I think I understand what is the conditions of restoration : it is possible to restore while my disk count offline is less than my parity value. (i.e. 2 servers with 4x2TB each should be able to restore when one server is broken with a N/2=8 parity value).

But What I don't understand it is how minio handle data availability : in my previous example, if a whole server go down for a time, the first one continues to works and its data is available ? (sort of degraded raid)

### My questions

Here are some questions about that I don't understand which should bring all information I need : 

* how total space is decided in a cluster by default ? and is there some configuration which impact this default behavior ?
* how minio handles different disk sizes and what is the impact of mixing different disk sizes ?
* how minio handles data avalability when node is down ? while the parity is respected, data stay usable ?
* how do you advice me for my needs ? 

Imagine I have 8TB on my 2 servers (server1=4x2TB, server2=4x2TB) and I run a distributed minio over my 2 servers for each disk, In my current understanding I will try do answer to these questions : 

* space should be the total space 16 TB / 2 so 8TB no matter the configuration
* there is no different size in this example because I don't understand how is is handled yet
* one node down, the other continues to work and can be used as degradated 
* use a standard class equal to 4 which will allow me to lost 2 drives on each server before lost my data.

I sorry for my misunderstood I hope you will agree to answer to my questions, thanks in advance.

**Comment by nitisht** [comment]
> how total space is decided in a cluster by default ? and is there some configuration which impact this default behavior ?

Total space is simply the number of data disks * space per disk. Minio starts with default configuration of N/2 data and N/2 parity disks. So in default configuration, say you have 8 disks of 1 TiB each, then total usable space is

Number of data disks [4] * Space per disk [1 TiB] = 4 TiB.

If you configure standard storage class with say 5 data, 3 parity and you have 1 TiB per disk, then total storage will be 

Number of data disks [5] * Space per disk [1 TiB] = 5 TiB.

> how minio handles different disk sizes and what is the impact of mixing different disk sizes ?

Minio uses space equal to smallest disk on all the disks. So if you have 4 disks of 1 TiB,  3 disks of 500 GiB and 1 disk of 250 GiB, only 250 GiB will be used per disk. Total available space (in default configuration) will be 

Number of data disks [4] * Space per disk [250 GiB] = 1 TiB

This is not the recommended approach, we recommend using equal sized disks in a distributed deployment. 

> how minio handles data avalability when node is down ? while the parity is respected, data stay usable ?

You need at least [parity + 1] disks online to be able to write data. If you have [parity] disks online, you'll be able to read data but not write to the cluster. If you less than [parity] drives online it is not possible to access data and it will be lost. 

I hope this answers your questions @xp-1000 , feel free to let us know if there is something else you'd like to know

**Comment by xp-1000** [comment]
Hi @nitisht,
Thank you very much for your quick answer, it is crystal clear for me.
One last question : do you know if minio can be used on two nodes over wan and if yes what is the maximum allowed latency between nodes ?
Thanks

**Comment by nitisht** [comment]
> do you know if minio can be used on two nodes over wan and if yes what is the maximum allowed latency between nodes ?

Minio can be used on two nodes, as long as you have at least 4 disks. Maximum time difference allowed across servers is 15 mins

**Comment by nitisht** [comment]
closing this as answered @xp-1000 feel free to join us on https://minio.slack.com if you have further questions.

**Comment by mikepuglisi** [comment]
@nitisht 

> Minio can be used on two nodes, as long as you have at least 4 disks.

Do you mean 4 disks for each node? I read your comment and bought 4 drives, but the documentation suggests to me that a 2 node minio setup might need 4 drives for each node.

"Note that with distributed MinIO you can play around with the number of nodes and drives as long as the limits are adhered to. For example, you can have 2 nodes with 4 drives each..."

https://docs.min.io/docs/distributed-minio-quickstart-guide.html

**Comment by harshavardhana** [comment]
@mikepuglisi please open a new issue or talk to us at https://slack.minio.io

**Comment by Rush** [comment]
I have the same question "Do you mean 4 disks for each node? I read your comment and bought 4 drives, but the documentation suggests to me that a 2 node minio setup might need 4 drives for each node.". What does it mean 15mins between servers? Is it 15 milliseconds by any chance?

**Comment by renatocron** [comment]
> @mikepuglisi please open a new issue or talk to us at https://slack.minio.io

Servers running distributed MinIO instances should be less than 15 minutes apart. You can enable NTP service as a best practice to ensure same times across servers.

**Comment by IIPoliII** [comment]
> > @mikepuglisi please open a new issue or talk to us at https://slack.minio.io
> 
> Servers running distributed MinIO instances should be less than 15 minutes apart. You can enable NTP service as a best practice to ensure same times across servers.

I think the original question is the maximum ping between the nodes for minio

**Comment by Homatp** [comment]
In this post, I read:
"You need at least [parity + 1] disks online to be able to write data. If you have [parity] disks online, you'll be able to read data but not write to the cluster. If you less than [parity] drives online it is not possible to access data and it will be lost."

And this means when we have more parity drives we can lose less drives. Should not be opposite?
