### ISSUE TITLE
Releases missing for Linux ARM, 386, BSD etc

### ISSUE THREAD

**Issue by lyderic** [minio/minio#5965]
The page https://dl.minio.io/server/minio/release/ is missing the latest release for many architectures/OS combinations e.g. Linux ARM, ARM64, 386, BSD, etc.

## Expected Behavior
It would be convenient to have builds for all architectures/OS combinations. For the moment, if you're running e.g. a Linux ARM server, you have to build minio, which might be daunting for some, especially as the README.md specifies that building minio is "only intended for developers and advanced users".

## Current Behavior
At present, only releases dating back to July or August 2017 are available for Linux ARM/ARM64/386 and FreeBSD

## Possible Solution
Please cross-compile minio to provide at least the most common architectures, if not all that are supported by golang (I suppose Linux ARM and ARM64 are pretty common, as well as FreeBSD amd64)

## Steps to Reproduce (for bugs)
N/A

## Context
I have several Linux ARM and ARM64 servers. I can't use minio, unless I build it myself. Why is only amd64 supported? Please also consider the many people using Raspberry Pis and similar, ARM-based devices.

## Your Environment
Linux Debian 9.4
Arch: armv7l
uname -a: Linux balzac 4.3.5-std-1 #1 SMP Fri Feb 19 11:52:18 UTC 2016 armv7l GNU/Linux
My servers are provided by scaleway. Here a link to their ARM offering:
https://www.scaleway.com/pricing/#anchor_arm

**Comment by harshavardhana** [comment]
We used to do in the past, but we decided to not build releases for these platforms simply because we do not have the bandwidth to build, test and validate them to be production worthy.

Source compilation is always possible on all these platforms and should be possible by simply doing ` go get github.com/minio/minio`

**Comment by kannappanr** [comment]
@lyderic As explained above, I will be closing this as won't fix. Please feel free to open a new issue if you have other questions.

**Comment by lyderic** [comment]
Thanks for your time and thanks for minio!!!

**Comment by lyderic** [comment]
Thanks for your time and thanks for minio!!!

**Comment by ulm0** [comment]
@harshavardhana it is possible, yet i've been trying to build it for ARM lately. it all seems to go good until i attempt to run minio (on a Raspberry Pi 3)

```sh
$ docker logs -f minio-arm
Created minio configuration file successfully at /root/.minio

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1156c]

goroutine 1 [running]:
sync/atomic.loadUint64(0x11b58034, 0x11c24440, 0xe)
	/usr/local/go/src/sync/atomic/64bit_arm.go:10 +0x3c
github.com/minio/minio/cmd.(*FSObjects).StorageInfo(0x11b58000, 0xbc8370, 0x11a28970, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/minio/minio/cmd/fs-v1.go:229 +0x30
github.com/minio/minio/cmd.printStartupMessage(0x11eb02c0, 0x2, 0x2)
	/go/src/github.com/minio/minio/cmd/server-startup-msg.go:59 +0x128
github.com/minio/minio/cmd.serverMain(0x11c4e2c0)
	/go/src/github.com/minio/minio/cmd/server-main.go:301 +0x7a0
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0x961530, 0xb1328c, 0x11c4e2c0, 0x11b24400, 0x0)
	/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x64
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xac4d4b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xae02ae, 0x1c, 0x0, ...)
	/go/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0x74c
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0x11b28620, 0x11a22080, 0x3, 0x4, 0x0, 0x0)
	/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x4f4
github.com/minio/minio/cmd.Main(0x11a22080, 0x3, 0x4)
	/go/src/github.com/minio/minio/cmd/main.go:155 +0x6c
main.main()
	/go/src/github.com/minio/minio/main.go:71 +0xe8
```

**Comment by harshavardhana** [comment]
This looks like we are using 64bit atomic load which will panic on 32bit systems like raspberry pi 3, will send a fix.

**Comment by ulm0** [comment]
Great, thank you so much!

May 26, 2018 11:19 PM, "Harshavardhana" <notifications@github.com (mailto:%22Harshavardhana%22%20<notifications@github.com>)> wrote:
	This looks like we are using 64bit atomic load which will panic on 32bit systems like raspberry pi 3, will send a fix.

**Comment by zeysh** [comment]
Hi @harshavardhana,

Same here. I try to compile minio for a Odroid-HC2.

`env GOOS=linux GOARM=7 GOARCH=arm go get -u github.com/minio/minio`

`Linux minio1 4.14.43-1-ARCH #1 SMP PREEMPT Wed May 23 01:02:31 UTC 2018 armv7l GNU/Linux`

But I have the same issue.

```
minio server --address :80 /mnt 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1156c]

goroutine 1 [running]:
sync/atomic.loadUint64(0x118c09e4, 0x6e9bc8, 0x11ad87c0)
	/usr/lib/go-1.10/src/sync/atomic/64bit_arm.go:10 +0x3c
github.com/minio/minio/cmd.(*FSObjects).StorageInfo(0x118c09b0, 0xbddb30, 0x11726828, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/zeysh/go/src/github.com/minio/minio/cmd/fs-v1.go:229 +0x30
github.com/minio/minio/cmd.printStartupMessage(0x11983d60, 0x3, 0x4)
	/home/zeysh/go/src/github.com/minio/minio/cmd/server-startup-msg.go:59 +0x124
github.com/minio/minio/cmd.serverMain(0x119e80b0)
	/home/zeysh/go/src/github.com/minio/minio/cmd/server-main.go:310 +0x7b4
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0x9728d0, 0xb2773c, 0x119e80b0, 0x11826100, 0x0)
	/home/zeysh/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x64
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xad8d80, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf458a, 0x1c, 0x0, ...)
	/home/zeysh/go/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0x74c
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0x11774620, 0x11722030, 0x5, 0x6, 0x0, 0x0)
	/home/zeysh/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x4f4
github.com/minio/minio/cmd.Main(0x11722030, 0x5, 0x6)
	/home/zeysh/go/src/github.com/minio/minio/cmd/main.go:155 +0x6c
main.main()
	/home/zeysh/go/src/github.com/minio/minio/main.go:71 +0xe8
```

Many thanks for your help @harshavardhana

**Comment by harshavardhana** [comment]
> env GOOS=linux GOARM=7 GOARCH=arm go get -u github.com/minio/minio
> 
> Linux minio1 4.14.43-1-ARCH #1 SMP PREEMPT Wed May 23 01:02:31 UTC 2018 armv7l GNU/Linux
> 
> But I have the same issue.
> 
> minio server --address :80 /mnt 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1156c]
> 
> goroutine 1 [running]:
> sync/atomic.loadUint64(0x118c09e4, 0x6e9bc8, 0x11ad87c0)
> 	/usr/lib/go-1.10/src/sync/atomic/64bit_arm.go:10 +0x3c
> github.com/minio/minio/cmd.(*FSObjects).StorageInfo(0x118c09b0, 0xbddb30, 0x11726828, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/home/zeysh/go/src/github.com/minio/minio/cmd/fs-v1.go:229 +0x30
> github.com/minio/minio/cmd.printStartupMessage(0x11983d60, 0x3, 0x4)
> 	/home/zeysh/go/src/github.com/minio/minio/cmd/server-startup-msg.go:59 +0x124
> github.com/minio/minio/cmd.serverMain(0x119e80b0)
> 	/home/zeysh/go/src/github.com/minio/minio/cmd/server-main.go:310 +0x7b4
> github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0x9728d0, 0xb2773c, 0x119e80b0, 0x11826100, 0x0)
> 	/home/zeysh/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x64
> github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xad8d80, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf458a, 0x1c, 0x0, ...)
> 	/home/zeysh/go/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0x74c
> github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0x11774620, 0x11722030, 0x5, 0x6, 0x0, 0x0)
> 	/home/zeysh/go/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x4f4
> github.com/minio/minio/cmd.Main(0x11722030, 0x5, 0x6)
> 	/home/zeysh/go/src/github.com/minio/minio/cmd/main.go:155 +0x6c
> main.main()
> 	/home/zeysh/go/src/github.com/minio/minio/main.go:71 +0xe8

@lyderic this will be fixed by #6006

**Comment by zeysh** [comment]
Hi @harshavardhana,

Works like a charm :+1:  ! 

Thanks you and have a nice day.

**Comment by carlosedp** [comment]
I've been building Minio and mc images for ARM64 in Travis for a while and pushing it into my DockerHub: https://hub.docker.com/r/carlosedp/minio and https://hub.docker.com/r/carlosedp/minio-mc
