### ISSUE TITLE
Cannot upload snapshots to minio from elasticsearch

### ISSUE THREAD

**Issue by iahmad-khan** [minio/minio#5967]
Hi,

I am using the latest stable version of minio. I have created a bucket named: elasticsearch , to which I can upload files using the browser interface.

I want to use the same bucket to stor elasticsearch snapshots. Elastic repo config:

```
PUT _snapshot/backups
{
     "type": "s3",
      "settings": {
         "bucket": "elasticsearch",
         "endpoint": "minio.mydomain:9000",
         "protocol": "http"
      }
}
```

Error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "sdk_client_exception",
        "reason": "sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio.mydomain:9000"
      }
    ],
    "type": "repository_exception",
    "reason": "[backups] failed to create repository",
    "caused_by": {
      "type": "sdk_client_exception",
      "reason": "sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio.mydomain:9000",
      "caused_by": {
        "type": "i_o_exception",
        "reason": "elasticsearch.minio.mydomain:9000"
      }
    }
  },
  "status": 500
}
```

Does it related to the fact that elasticsearch s3 plugin expects s3 kind of url:

`elasticsearch.minio.mydomain:9000`

while the url in minio is:

`minio.mydomain:9000/minio/elasticsearch
`
thanks

**Comment by nitisht** [comment]
@iahmad-khan can you please try setting up your Minio server as explained here https://github.com/minio/minio/tree/master/docs/config#domain

**Comment by iahmad-khan** [comment]
Ok got it. Maybe I need to use s3 style url by passing domain env variable
to container.

**Comment by iahmad-khan** [comment]
Hi , 

Still same erorr.

Here is my docker run , i can see inside the container the those variables are exported:

```
docker run --restart=always -p 9000:9000 --name minio \
  -v /data:/data \
  -v /config:/root/.minio \
  -e MINIO_ACCESS_KEY=NDIzfdsfdsfsdf \
  -e MINIO_SECRET_KEY=zZgoKsdfsdfdsfsd \
  -e MINIO_DOMAIN=myexample.domain \
   mydocker-registery/minio server /data
```

**Comment by iahmad-khan** [comment]
How can I test whether the s3 style url works? If I use curl , it says domain name not found:

elasticsearch.machine_name.mydoamin.com:9000
OR
elasticsearch.machine_name.mydoamin.com

How can I test that I can access my bucket using that url format.

**Comment by iahmad-khan** [comment]
Have you tested that minio works with elasticsearch as snapshot repository? If you test , it will complain about that io-exceptiion

**Comment by iahmad-khan** [comment]
I test by using both:

`MINIO_DOMAIN=myexample.com
`
and

`MINIO_DOMAIN=minioserver.myexample.com
`
still the same error.  Browser uploads works.

**Comment by iahmad-khan** [comment]
This seems strange , it finds the bucket but it complains about the url format.

If I provide the wrong bucket name , it says:

  ```
 "type": "illegal_argument_exception",
      "reason": "The bucket [elastic] does not exist. Please create it before  creating an s3 snapshot repository backed by it."
```

**Comment by nitisht** [comment]
> Have you tested that minio works with elasticsearch as snapshot repository? If you test , it will complain about that io-exception

@iahmad-khan yes, this is well tested and documented on elastic website: https://www.elastic.co/guide/en/cloud-enterprise/current/ece-configuring-minio.html 

When you say 

> Browser uploads works.

how does that work? I mean what are you uploading from browser

**Comment by iahmad-khan** [comment]
From browser interfere I can do file uplods to bucket.

I have also tried --address option with server and configured hosts file
for dns. Still no luck

**Comment by iahmad-khan** [comment]
@nitisht  that documentation is for the cloud version  of elasticsearch , maybe , in there , they are using the path style bucket access , not the dns name style.

In the standard elasticsearch , the s3 plugin tries to access   bucket.minio.domain.com  style that fails.

Did you try using standard elastic-search installation , with s3 plugin.

**Comment by nitisht** [comment]
let me check and get back @iahmad-khan

**Comment by nitisht** [comment]
@iahmad-khan I just tried using Elasticsearch 6.x and was able to create repository and upload snapshots. I have documented the steps here https://github.com/nitisht/cookbook/blob/elastic/docs/elasticsearch-snapshots-on-minio.md can you please take a look

**Comment by iahmad-khan** [comment]
Hi

I have made it worked by using the directory method instead of dns name to
bucket. I used ip address for endpoint in s3 client

Thanks

**Comment by nitisht** [comment]
Closing as working as intended

**Comment by sentient** [comment]
> Hi I have made it worked by using the directory method instead of dns name to bucket. I used ip address for endpoint in s3 client Thanks


What do you have to do to set the "document" or "path" style method. It seems it became the default in elastic 7.0. But I don't understand yet how you can set this on a 6.* version

**Comment by sunilchadha1973** [comment]
> @iahmad-khan I just tried using Elasticsearch 6.x and was able to create repository and upload snapshots. I have documented the steps here https://github.com/nitisht/cookbook/blob/elastic/docs/elasticsearch-snapshots-on-minio.md can you please take a look

@nitisht this document seems to be no more available, can you share it.
I want to know if we can use Elasticsearch open source with S3 plugin with open source minio to take snapshot?

**Comment by nitisht** [comment]
Document is here now: https://github.com/minio/cookbook/blob/master/docs/elasticsearch-snapshots-on-minio.md
