### ISSUE TITLE
Why is the S3 API that Minio is not 100% compatible with Amazon S3?

### ISSUE THREAD

**Issue by pospelov-v** [minio/minio#5970]
Why is the S3 API that Minio is not 100% compatible with Amazon S3?

For example, why is list not supported with prefix and delimeter supported?

Because of this, Error 501 NotImplemented occurs when writing to S3 storage…

**Comment by kannappanr** [comment]
@pospelov-v Not sure I understand you correctly.  Prefix parameter is supported in listObjects API. Can you please provide us with more information and also the corresponding http trace from the server? 

you can use the `MINIO_HTTP_TRACE` environment variable and pass the location where you want to save the log, like
`export MINIO_HTTP_TRACE=/tmp/minio.log`
Restart minio once this env variable is set and once the failure is seen, please stop minio and attach the file to this issue.

**Comment by pospelov-v** [comment]
Tell me more how to use the MINIO_HTTP_TRACE

I'm using this OS:
https://cdimage.debian.org/cdimage/archive/8.10.0/amd64/iso-cd/debian-8.10.0-amd64-netinst.iso

I run the "minio" according to the instructions:

https://docs.minio.io/

`
docker pull minio/minio
`

`
docker run -p 9000:9000 minio/minio server /data
`

`
MINIO_HTTP_TRACE=1
`

`
export MINIO_HTTP_TRACE=/tmp/minio.log
`

reproduce an error

`
cat /tmp/minio.log
`

Tried also:

`
docker run --name minio -e MINIO_HTTP_TRACE=/tmp/minio.log -p 9000:9000 minio/minio:edge server /data
`

But the file `/tmp/minio.log` does not exist.

**Comment by kannappanr** [comment]
Can you please take a look at https://github.com/minio/minio/issues/5710 . 

Here is the sample provided in that issue
```
sudo docker run -p 9000:9000 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -e "MINIO_HTTP_TRACE=/tmp/minio.log"
  -v /mnt/data:/data \
  -v /mnt/config:/root/.minio \
  minio/minio:RELEASE.2018-03-19T19-22-06Z server /data
Here, the logs will be stored in /tmp/minio.log
```

**Comment by pospelov-v** [comment]
![2018-05-27--01-39-53--281](https://user-images.githubusercontent.com/39521751/40580799-9857361c-614f-11e8-8a8d-c931c7292a8d.PNG)

I'm run everything as you told me, I reproduced the problem, but the log file was never created

**Comment by harshavardhana** [comment]
if you close the container the log will be lost @pospelov-v make sure to keep the container running and use `docker cp` to get the log from the container to your host.

**Comment by denisdefreyne** [comment]
I’m running into problems with the `listObjects` API too. Here’s the request/response:

```
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [152802179.706532] [2018-06-03 12:29:57 +0200]
GET /inbox/?prefix=pricing%2F&max-keys=1
Host: localhost:9000
Connection: keep-alive
Date: Sun, 03 Jun 2018 10:29:57 GMT
Accept: */*
User-Agent: Transmit/5.1.4
Authorization: AWS BF89V8A2XZLZT7QRI1VZ:6q21fguu+OMBcNW4PsoBPPtce5E=
Accept-Encoding: gzip, deflate
Accept-Language: en-us


[RESPONSE] [152802179.706532] [2018-06-03 12:29:57 +0200]
200 OK
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15349FBA8734B005
Server: Minio/RELEASE.2018-05-25T19-49-13Z (darwin; amd64)
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: "1; mode=block"

<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>inbox</Name>
  <Prefix>pricing/</Prefix>
  <Marker></Marker>
  <MaxKeys>1</MaxKeys>
  <Delimiter></Delimiter>
  <IsTruncated>false</IsTruncated>
</ListBucketResult>
```

(Slightly reformatted for readability.)

This request is made by [Transmit](https://panic.com/transmit/), which supports Amazon S3. However, Transmit does not like this response (see [this Twitter thread](https://twitter.com/ddfreyne/status/1003220481724559361)), and I don’t know why.

**Comment by denisdefreyne** [comment]
(This might be a separate issue, and perhaps a bug in Transmit.)

**Comment by harshavardhana** [comment]
@ddfreyne the output seems to be correct what is the problem that you are facing??, please open a different GitHub issue for more clarity.

**Comment by denisdefreyne** [comment]
@harshavardhana This indeed appears to be an unrelated problem — and possibly not related to Minio. I’m in touch with Panic to figure out the problem that Transmit is having; if it turns out to be a problem on the Minio side, I’ll open a separate issue.

**Comment by kannappanr** [comment]
@pospelov-v do you have any updates on this issue? Were you able to reproduce the issue and generate the logs?

**Comment by nitisht** [comment]
@pospelov-v closing this due to no response. Feel free to get back / reopen if you think something is not working as expected.
