### ISSUE TITLE
Invalid X-XSS-Protection header format

### ISSUE THREAD

**Issue by willfrew** [minio/minio#5972]
## Expected Behavior
Chrome should be able to parse the X-XSS-Protection header without an error.

## Current Behavior
Chrome is complaining about the quotes wrapping the X-XSS-Protection header:

![2018-05-23-162533_1286x40_scrot](https://user-images.githubusercontent.com/521750/40434277-ed3c0baa-5ea5-11e8-976e-bd1bd1748fc4.png)

[MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) also seems to confirm that there shouldn't be quotes wrapping this header.

## Possible Solution
Remove the quotes [here](https://github.com/minio/minio/blob/5b74f918d4f588927151254af6d6fc8ac7c79eee/cmd/generic-handlers.go#L664).

## Steps to Reproduce (for bugs)
1. Upload an html file to minio.
2. Include it in an another html file as an iframe `src`.
3. Observe the error displayed above.

## Your Environment
* Version used (`minio version`): 
```
Version: 2018-05-16T23:35:33Z
Release-Tag: RELEASE.2018-05-16T23-35-33Z
Commit-ID: 64288d6eb53cc134a1f85851dcaf7dee76fecca6
```
* Environment name and version (e.g. nginx 1.9.1): Docker `18.03.0-ce`?
* Operating System and version (`uname -a`): `Linux wr4ith 4.15.13-1-ARCH #1 SMP PREEMPT Sun Mar 25 11:27:57 UTC 2018 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Thanks @willfrew I saw this too, we will take a look.

**Comment by nitisht** [comment]
Fixed by https://github.com/minio/minio/pull/5992
