### ISSUE TITLE
Minio stops sending events once RabbitMQ has restarted

### ISSUE THREAD

**Issue by bensquire** [minio/minio#5973]
Possible bug (but then my track record hasn’t been good). We are pushing notifications to RabbitMQ on upload. This works fine. 

However if RabbitMQ goes down and then comes back up Minio seemingly stops sending messages to RabbitMQ. If we restart Minio, everything works as expected.

## Expected Behaviour
RabbitMQ goes down and comes back up again, Minio continues to send events

## Current Behaviour
RabbitMQ goes down and comes back up again, Minio stops sending events, until it is restarted

## Possible Solution
Minio should be checking its connection?

## Steps to Reproduce (for bugs)
1. Setup RabbitMQ
2. Setup Minio
3. Add bucket notifications
4. Test notifications being received in exchange/queue by uploading a file
5. Kill RabbitMQ
6. Start RabbitMQ
7. Upload another file, no message appears in RabbotMQ

## Context
We are performing file analysis on successful uploads

## Your Environment
* 2018-05-16T23:35:33Z
* Used: 28 MB | Allocated: 87 MB | Used-Heap: 28 MB | Allocated-Heap: 36 MB
* minio02.local.io | OS: linux | Arch: amd64
* Version: go1.10.1 | CPUs: 1

**Comment by harshavardhana** [comment]
Thanks @bensquire we will fix it.

**Comment by deekoder** [comment]
@bensquire marking as regression, assuming this happens. We will test and if its indeed a regression, fix it and if it's not we will remove regression label and see why it works fine on our end and not for you.

**Comment by Praveenrajmani** [comment]
Hey @bensquire , 
It seems to work fine here , 
Il list down the scenario which succeeded when tested in my machine,

- [ ] Set up RabbitMQ - `.sbin/rabbitmq-server ` 
- [ ] Start Minio server - `./minio server testdir/`
- [ ] Add bucket notifications - `./mc events add  myminio/rabbittemp arn:minio:sqs::1:amqp`
- [ ] Start listening to the events - [I used the python script in the doc](https://docs.minio.io/docs/minio-bucket-notification-guide)
- [ ] exec an event on the bucket - `./mc cp test.js myminio/rabbittemp`

I can see 

> '{"EventName":"s3:ObjectCreated:Put","Key":"rabbittemp/test.js","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2018-05-24T09:43:21Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"25KP291FP03RJUFMO2RV"},"requestParameters":{"sourceIPAddress":"192.168.86.21:56329"},"responseElements":{"x-amz-request-id":"15318B61DB29522F","x-minio-origin-endpoint":"http://127.0.0.1:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"rabbittemp","ownerIdentity":{"principalId":"25KP291FP03RJUFMO2RV"},"arn":"arn:aws:s3:::rabbittemp"},"object":{"key":"test.js","size":1222,"eTag":"a885b2a025a8a773535476aba5b39d73","contentType":"application/javascript","userMetadata":{"content-type":"application/javascript"},"versionId":"1","sequencer":"15318B61DB29522F"}},"source":{"host":"192.168.86.21","port":"56329","userAgent":"Minio (darwin; amd64) minio-go/6.0.1 mc/2018-05-24T06:52:28Z"}}]}'

in the python output console,
and can see the exchanges logged in `sudo .sbin/rabbitmqctl list_exchanges`

Then 

- [ ] Stop the rabbitmq server - `sudo .sbin/rabbitmqctl stop`
- [ ] exec an event on the bucket - `./mc cp example.js myminio/rabbittemp`
- [ ] minio server threw

 ![screen shot 2018-05-24 at 4 01 46 pm](https://user-images.githubusercontent.com/5410427/40480374-e64a45de-5f6b-11e8-8a6b-d5f96aea7789.png)

- [ ] Start the rabbitmq server again - `.sbin/rabbitmq-server`
- [ ] exec an event on the bucket
- [ ] The event got logged in the listener like before (In the python output console)


Will be much helpful if we know what is the event that you're trying to log in the queue ?

**Environment:**

**rabbitmq**: stable 3.7.5
**minio**: 2018-05-19T18:59:53Z
**mc**: 2018-05-24T06:52:28Z


Thanks.

**Comment by deekoder** [comment]
removing regression label @bensquire until you provide further info on why it happens at your end.

**Comment by bensquire** [comment]
@Praveenrajmani  @deekoder I'm going to close this for now, because although I can replicate it locally, I believe something funky is going on with our own setup. If I come up with something definitive, I'll open a new issue with more detail.

Thanks for the help and sorry to waste your time.
