### ISSUE TITLE
Can't implement other gateways using minio as a dependency

### ISSUE THREAD

**Issue by jtolio** [minio/minio#5974]
Summary: github.com/minio/minio vendors github.com/minio/cli and exports types from a vendored cli in the minio gateway interface.

Let's say we want to write a gateway:

`src/github.com/jtolds/mygateway/main.go`
```golang
package main

import (
	"os"

	"github.com/minio/cli"
	"github.com/minio/minio/cmd"
)

func main() {
	cmd.RegisterGatewayCommand(cli.Command{
		Name:   "mygateway",
		Action: func(ctx *cli.Context) { ... },
	})
	cmd.Main(os.Args)
}
```

This won't compile because:

```
./test.go:11:40: cannot use "github.com/minio/cli".Command literal (type 
"github.com/minio/cli".Command) as type 
"github.com/minio/minio/vendor/github.com/minio/cli".Command in argument to 
cmd.RegisterGatewayCommand
```

I can't change the import path of `cli` to `github.com/minio/minio/vendor/github.com/minio/cli` because vendored packages are essentially internal. Code outside of `github.com/minio/minio` can't use it.

See https://github.com/golang/go/issues/15162

The recommendation is that the API of `minio/minio` should not export types that are vendored types and should instead use its own types or define type aliases. cmd.RegisterGatewayCommand should use a type defined by something other than a vendored package.

How do I register a gateway command in my own codebase?

**Comment by jtolio** [comment]
(In the meantime we have to stupidly fix this by `go get github.com/minio/cli && rm -rf $GOPATH/src/github.com/minio/minio/vendor/github.com/minio/cli`)

**Comment by krishnasrinivas** [comment]
"github.com/minio/minio/cmd" is not written to be imported outside minio source @jtolds 

i.e you will have to put your gateway in `src/github.com/minio/minio/cmd/gateway/mygateway`

You can look for other gateway source in `src/github.com/minio/minio/cmd/gateway`
Have a look at `src/github.com/minio/minio/cmd/gateway/azure/gateway-azure.go` for reference.

**Comment by jtolio** [comment]
Why? If I make my own github.com/minio/minio fork with changes, then I don't easily get upstream fixes. It doesn't seem terribly challenging to make github.com/minio/minio/cmd be importable by just using type aliases.

This is really close to working exactly how I want. Could you add type aliases to fix the unexportable vendored types so they're exportable?

**Comment by harshavardhana** [comment]
> Why? If I make my own github.com/minio/minio fork with changes, then I don't easily get upstream fixes. It doesn't seem terribly challenging to make github.com/minio/minio/cmd be importable by just using type aliases.
> 
> This is really close to working exactly how I want. Could you add type aliases to fix the unexportable vendored types so they're exportable?

Well that is not the intention, we can willingly change our cmd/ folder anytime and we need that flexibility. We cannot treat it like a library.   If you want to make changes simply fork and change the import paths.

**Comment by krishnasrinivas** [comment]
> It doesn't seem terribly challenging to make github.com/minio/minio/cmd be importable by just using type aliases.

We will have to pay attention to what symbols are exported and what is not and also maintain it so that packages that import it don't break. It will be burdensome.

you have to treat the `package cmd` like `package main` of minio. Initially we had all the files in cmd in the top folder, but moved it inside cmd so that on the main github page github.com/minio/minio users don't see a long list of files and have to scroll down a long way to see the readme.

**Comment by jtolio** [comment]
bummer. I think minio would be really useful as a library. Consider this issue to be a request for the minio server to be supported as a library!

**Comment by harshavardhana** [comment]
Closing this as won't fix for now.
