### ISSUE TITLE
Test all notifications on Minio Server 

### ISSUE THREAD

**Issue by deekoder** [minio/minio#5975]
Following this doc, please test if the latest minio server still sends notifications for each of the following mentioned integrations in doc below
https://docs.minio.io/docs/minio-bucket-notification-guide

## Expected Behavior
 All notification should work 

## Current Behavior
We are testing if there may be any regressions in notifications
 
## Possible Solution
Test and find if things are broken
 
## Steps to Reproduce (for bugs)
1. Follow documentation and setup each one (MQTT/ Kafka/ Elasticsearch etc) 
2. Check if notifications work
3. If not report behavior on this issue.
4. Else continue 

## Context
N/A
 
## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by Praveenrajmani** [comment]
Removing notifications had a bug in it ( When tested with NATS ), it was probing events even after doing a `mc events remove` .

sent a PR on this. Refer #6082

**Comment by kannappanr** [comment]
@Praveenrajmani Can this issue be closed?

**Comment by Praveenrajmani** [comment]
@nitisht shall we close this ?

**Comment by nitisht** [comment]
closing as we revamped and tested notification code recently.
