### ISSUE TITLE
Spurious failure seen in TestServerTLSCiphers

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#5977]
Very rarely tests in `TestServerTLSCiphers` fails. This has been observed while running Travis builds.

## Expected Behavior
Should not see the test fails sporadically and should always pass.

## Current Behavior
Fails very rarely.
```
--- FAIL: TestServerTLSCiphers (2.54s)
    server_test.go:177: test 2: error: expected: false, got: true
FAIL
FAIL    github.com/minio/minio/cmd/http    10.010s
```

Looks like the second test failed in this scenario
```
testCases := []struct {
		ciphers            []uint16
		resetServerCiphers bool
		expectErr          bool
	}{
		{nil, false, false},
		{defaultCipherSuites, false, false},
		{unsupportedCipherSuites, false, true},
		{nil, true, false},
	}
```
## Possible Solution
Needs to be reproduced consistently and debugged

## Steps to Reproduce (for bugs)

1.Run TestServerTLSCiphers test often
2. Hopefully, the failure can be observed.

## Your Environment
This was seen on Travis build and when the build was restarted, the error went away.

**Comment by aead** [comment]
I think we can actually remove this test. The behavior is tested by mint anyway - See https://github.com/minio/mint/blob/master/run/core/security/tls-tests.go#L92
