### ISSUE TITLE
Can I use minio with both S3 and NFS interfaces at a time?

### ISSUE THREAD

**Issue by darron1217** [minio/minio#5983]
Can I use minio with both S3 and NFS interfaces at a time?

I want to use minio as S3 and also NFS server

**Comment by nitisht** [comment]
you can @darron1217 . Please check this out https://github.com/minio/minio/blob/master/docs/gateway/nas.md

**Comment by darron1217** [comment]
I saw that doc.
I guess minio supports converting NFS -> S3 interface.
But I wanted to know that does minio supports S3 -> NFS conversion

**Comment by nitisht** [comment]
> But I wanted to know that does minio supports S3 -> NFS conversion

No, Minio only provides S3 interface.

**Comment by darron1217** [comment]
Okay now it seems clear for me :)

Thanks
