### ISSUE TITLE
Add to event custom meta info

### ISSUE THREAD

**Issue by fortunto2** [minio/minio#5985]
Hi, thanks for Minio.
But how add custom data (myID)  from Front to events response in RabbitMQ
to there

```
'{"Records":[{"eventVersion":"2.0","eventSource":"aws:s3","awsRegion":"","eventTime":"2016–09–08T22:34:38.226Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"minio"},"requestParameters":{"sourceIPAddress":"10.1.10.150:44576"},"responseElements":{},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"images","ownerIdentity":{"principalId":"minio"},"arn":"arn:aws:s3:::images"},"object":{"key":"myphoto.jpg","size":200436,"sequencer":"147279EAF9F40933"}}}],"level":"info","msg":"","time":"2016–09–08T15:34:38–07:00"}'
```

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
@fortunto2 if I understand correctly, you're adding custom metadata to an object and want the metadata  be accessible in eventData pushed to RabbitMQ?

**Comment by fortunto2** [comment]
yes, it's possible?)

**Comment by nitisht** [comment]
Its not possible to get the metadata directly in RabbitMQ, you'll have to issue a `headObject()` request to Minio server after you get the notification in RabbitMQ. The `headObject()` response will have the custom metadata

**Comment by nitisht** [comment]
@fortunto2 closing this as answered, feel free to comment / join us on [Slack](https://minio.slack.com/) for further questions
