### ISSUE TITLE
`Minio Gateway` should expose `Prometheus` metrics similarly to `Minio Server`

### ISSUE THREAD

**Issue by yskopets** [minio/minio#5986]
## Expected Behavior

`Minio Gateway` should expose `Prometheus` metrics similarly to `Minio Server`.

## Current Behavior

While `Minio Server` exposes `Prometheus` metrics on `/minio/prometheus/metrics`, it happens that `Minio Gateway` doesn't.

## Possible Solution

When configuring `Minio Gateway` on start up, add a `Prometheus` endpoint `/minio/prometheus/metrics` similarly to `Gateway Server`.

## Context

Having `Prometheus` endpoint is important when `Minio Gateway` is deployed on `Kubernetes` (so that it could be monitored consistently with the other infrastructure).

## Your Environment

* Version used (`minio version`): RELEASE.2018-05-25T19-49-13Z

**Comment by yskopets** [comment]
Please see Pull Request https://github.com/minio/minio/pull/5987

**Comment by deekoder** [comment]
What a great idea! Thanks for the PR @yskopets

**Comment by nitisht** [comment]
fixed by #5987
