### ISSUE TITLE
Error when PresignObject on AWS-S3

### ISSUE THREAD

**Issue by reinaldocoelho** [minio/minio#5995]
I have an AWS-S3 bucket on us-west-2 region, but when I request a PresignObject and open the URL, I receive an invalid us-east-1 region error.
This error occours only when running over AWS-S3, local Minio Server don´t present error.

## Expected Behavior
Is expected to when I get an PresignObject url, that this url open the object without error, to show or download.

## Current Behavior
When I call the received PresignObject Url, this show to me an follow error: "Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'us-west-2"

## Steps to Reproduce (for bugs)
1. Download or clone example code from (https://github.com/reinaldocoelho/minio-PresignedGetObjectAsync-Aws-Fail)  (Need DotNet Framework and VisualStudio 2017 installed)
2. Edit file ...src\sample\Controllers\HomeController.cs
  2.1. Change variable objectStorageAccessKey and input your AWS Access Key.
  2.2. Change variable objectStorageSecretKey and input your AWS Secret Key.
3. Press F5 to running code.
4. On the screen, click on buttons to get Image or PDF files
  4.1. The button create an bucket, input the object and get PresignUrl to open and show the error.

## Context
I use this uri to download and show attachments in my software and with this Bug, we can´t use this feature.

## Your Environment
* Windows 10
* AWS S3 on region us-west-2
* Minio .Net SDK version 1.1.0
* Dotnet Framework 4.5.2 (In production using 4.6.1 has the same issue)
* Sample error code: https://github.com/reinaldocoelho/minio-PresignedGetObjectAsync-Aws-Fail

**Comment by poornas** [comment]
@reinaldocoelho , this is a bug with minio  .NET sdk, will be fixing this shortly.
