### ISSUE TITLE
Remove huge number of log messages

### ISSUE THREAD

**Issue by miketonks** [minio/minio#5997]
## Expected Behavior

In distributed mode, when a disk is offline, we see a message in the logs saying disk is offline.

## Current Behavior
In distributed mode, when a disk is offline, we see hundreds or thousands of error messages, often with the same timestamp.

## Possible Solution
Remove duplicate logs messages, or don't log these errors is a disk is known to be offline.

## Steps to Reproduce (for bugs)
1. Start distributed minio with 6 disks (4 should be enough, but I have 6).
2.Take 1 or two disks offline
3. Run a heal command, or do pretty much anything.
4. Check logs

## Context
Minio should be stable in distributed mode.  For standard maintenance or HA, we need to ensure the cluster is stable even if one or two disks offline, as long as quorum is still ok.

When testing this scenario with new Heal API, or sysadmin team noticed huge amounts of errors in the logs, and reported this as a problem.

In production use, this can be a normal scenario, so we should not expect to see large volume of log messages.

In addition, it looks like the heal command can produce one log message for every object in storage, so there may be scaling issues if we scale out to 100,000's of objects (not confirmed).

## Your Environment
* Environment name and version (e.g. nginx 1.9.1): MINIO_VERSION=RELEASE.2018-05-16T23-35-33Z
* Server type and version:  Cloud Virtual Servers
* Operating System and version (`uname -a`):Linux  4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 

Related Issue: https://github.com/minio/minio/issues/5796

**Comment by deekoder** [comment]
In the process of fixing this.

**Comment by kannappanr** [comment]
@miketonks  Thanks for filing this issue. Will try to send a PR to fix this issue by end of this week.
