### ISSUE TITLE
[regression] NAS gateway bucket policy doesn't load from disk anymore

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#6004]
## Expected Behavior
NAS gateway was designed to always load from disk, this changed in the PR 

```
commit 0d521260237ca69a89044f23f10a13b44e1f53c9
Author: Bala FA <bala.gluster@gmail.com>
Date:   Wed Apr 25 04:23:30 2018 +0530

    Enhance policy handling to support SSE and WORM (#5790)
```

## Current Behavior
NAS gateway has regression now related to bucket policies

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Build the master and run the following steps. 

Start two gateway instances on port 9001, 9002
```
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway nas --address ":9001"  ~/test
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway nas --address ":9002"  ~/test
$ mc config host add minio1 http://localhost:9001 minio minio123
$ mc config host add minio2 http://localhost:9002 minio minio123
$ mc mb minio1/testbucket
$ mc cp /etc/issue minio1/testbucket
$ mc policy download minio1/testbucket
$ curl http://localhost:9001/testbucket/issue
... returns data ... 
$ curl http://localhost:9002/testbucket/issue
... returns access denied...
```

Now going back to the commit before the offending commit 21a3c0f482b2e9ed5cf40560cb4c7da320caae0c 

The same step, results are as expected 
```
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway nas --address ":9001"  ~/test
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway nas --address ":9002"  ~/test
$ mc config host add minio1 http://localhost:9001 minio minio123
$ mc config host add minio2 http://localhost:9002 minio minio123
$ mc mb minio1/testbucket
$ mc cp /etc/issue minio1/testbucket
$ mc policy download minio1/testbucket
$ curl http://localhost:9001/testbucket/issue
... returns data ... 
$ curl http://localhost:9002/testbucket/issue
... returns data ... 
```

## Context
Regression

## Your Environment
Minio master and all releases since RELEASE.2018-04-27T23-33-52Z are affected.

**Comment by balamurugana** [comment]
Wondering how it was done previously in a disconnected minio servers.  Do they periodically load the policy of all buckets?

**Comment by harshavardhana** [comment]
> Wondering how it was done previously in a disconnected minio servers. Do they periodically load the policy of all buckets?

This is only for NAS gateway @balamurugana - NAS gateway used to read policies always from the disk

**Comment by balamurugana** [comment]
Do you say previously bucket policy evaluation for a request was done by reading policy from the disk always in FS?

**Comment by harshavardhana** [comment]
> Do you say previously bucket policy evaluation for a request was done by reading policy from the disk always in FS?

yes both in FS and Gateway NAS @balamurugana this functionality was already there and released.

**Comment by deekoder** [comment]
Changing assignees since @krishnasrinivas  sent the PR #6007

**Comment by alvarollmenezes** [comment]
Hello @deekoder, I was waiting for this issue to be closed.

Should it be fixed in todays release (RELEASE.2018-06-07T19-10-07Z)?

**Comment by harshavardhana** [comment]
Yes @alvarollmenezes the fix is to reload the new policy every 5 minutes if needed.

**Comment by alvarollmenezes** [comment]
Thank you all very much. 👍

**Comment by cfmanteiga** [comment]
Hi,

Latest version hits again this regression :-(

Thaks

**Comment by harshavardhana** [comment]
> Hi,
> 
> Latest version hits again this regression :-(
> 
> Thaks

the new issue is different @cfmanteiga lets continue our discussion there.

**Comment by cfmanteiga** [comment]
Hi @harshavardhana, I suppose you're talking about #6223, but this one affects master again.

NAS gateway does not read policy from disk, neither reloading server or waiting +5 minutes. Steps to reproduce in your first post.

Moreover if the server where the policy was updated is restarted, the policy is lost (but its written in .minio.sys metadata.

Maybe it's preferred to open a new issue?

Thank you

**Comment by harshavardhana** [comment]
Yes please let's open a new issue @cfmanteiga
