### ISSUE TITLE
Document specifics of NAS gateway

### ISSUE THREAD

**Issue by straight-shoota** [minio/minio#6009]
From the available documentation it is not clear what is the difference between `minio server /path` and `minio gateway Nas /path`.

I would appreciate if someone could explain this and enhance the docs accordingly.

**Comment by harshavardhana** [comment]
NAS gateway is documented here 

- https://github.com/minio/minio/blob/master/docs/gateway/nas.md 
- https://minio.io/nas.html
- https://docs.minio.io/docs/minio-gateway-for-nas

**Comment by straight-shoota** [comment]
Thanks, but I am aware of these documentation sites. However, I can't find any information there (or in any issues here on Github) how exactly `minio server` and `minio gateway nas` differ. It is my understanding that they behave pretty similar, but not exactly the same. #5569 suggests that for example, but doesn't state specifics.

**Comment by harshavardhana** [comment]
> Thanks, but I am aware of these documentation sites. However, I can't find any information there (or in any issues here on Github) how exactly minio server and minio gateway nas differ. It is my understanding that they behave pretty similar, but not exactly the same. #5569 suggests that for example, but doesn't state specifics.

```
minio server /path 
```

and 

```
minio gateway nas /path
```

Currently, they share the same code base so also behave the same. But NAS gateway if necessary would diverge eventually from `minio server /path`. The reason we are not explaining is also that there is no difference from an application point of view. Both speak S3 APIs and both behave the same for S3 API operations.

**Comment by deekoder** [comment]
@straight-shoota if you want high-level details, architecture etc, you could also go here https://minio.io/nas.html @straight-shoota when you run minio in the server mode, minio is your object storage, which is a full blown server and speaks S3 protocol. 

When you use minio in the gateway mode, you can speak S3 and park your objects on any nas backend. You can also use regular POSIX to access your data apart from S3. It depends on your usecase which path you want to take. Let us know if we can help in any other way.

**Comment by straight-shoota** [comment]
Thanks for clarifying that 👍 

If I understand you both correctly, `server` and `gateway nas` are similar and only differ in the semantics of data ownership: `server` expects that the data path is governed by minio exclusively while `gateway nas` is aware that the data is on a remote storage and may be accessed and changed by different means. However, this semantic difference doesn't matter practically, because both commands are doing exactly the same thing (but might change in the future?).

For my specific use case I'm considering to make selected buckets (or the entire data path of a tenant) available via FTP as legacy support (allowing read and write access).

**Comment by deekoder** [comment]
@straight-shoota  correct. Great. I will close this issue as working as intended. Please feel free to come over to our slack channel https://slack.minio.io/ and come chat with us there. We hang there a lot and can answer questions instantly.

**Comment by zhangyoufu** [comment]
`minio gateway nas` requires `MINIO_ACCESS_KEY` & `MINIO_SECRET_KEY` being specified via environment variable. ~And `minio gateway nas` does not support multiple user.~

**Comment by harshavardhana** [comment]
Minio gateway nas supports multi user with etcd configured.
