### ISSUE TITLE
ListObject API of aws s3 sdk not listing empty folders incase of minio, Working fine for aws s3 object store.

### ISSUE THREAD

**Issue by sdjunaidali** [minio/minio#6010]
ListObjectsRequest API of aws s3 sdk not listing empty directory object for minio, Same working and listing all objects incase of s3 object store.

**Comment by harshavardhana** [comment]
Can you provide more information such as

- which language SDK was used ?
- can you provide a sample program ?

Please use the issue template next time, follow instructions on what information is expected.

**Comment by sdjunaidali** [comment]
I was using aws s3 sdk for C++

Following is the sample program :+1: 
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/ListObjectsRequest.h>
#include <aws/s3/model/Object.h>

/**
 * List objects (keys) within an Amazon S3 bucket.
 */
int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        if (argc < 2)
        {
            std::cout << std::endl <<
                "To run this example, supply the name of a bucket to list!" <<
                std::endl << "Ex: list_objects <bucket-name>" << std::endl
                << std::endl;
            exit(1);
        }

        const Aws::String bucket_name = argv[1];
        std::cout << "Objects in S3 bucket: " << bucket_name << std::endl;

        Aws::Client::ClientConfiguration config;
        config.endpointOverride = "10.1.1.193:9000";
        auto credentials = Aws::Auth::AWSCredentials("BCL8OLKMMVENDQM0DNNU", "6FAbPM+Swg6Nz4xHmeCCtCLB5eQPmCeWDERTsZol");
        Aws::S3::S3Client s3_client = Aws::S3::S3Client(credentials, config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always, false);

        Aws::S3::Model::ListObjectsRequest objects_request;
        objects_request.WithBucket(bucket_name);

        auto list_objects_outcome = s3_client.ListObjects(objects_request);

        if (list_objects_outcome.IsSuccess())
        {
            Aws::Vector<Aws::S3::Model::Object> object_list =
                list_objects_outcome.GetResult().GetContents();

            for (auto const &s3_object : object_list)
            {
                std::cout << "* " << s3_object.GetKey() << std::endl;
            }
        }
        else
        {
            std::cout << "ListObjects error: " <<
                list_objects_outcome.GetError().GetExceptionName() << " " <<
                list_objects_outcome.GetError().GetMessage() << std::endl;
        }
    }

    Aws::ShutdownAPI(options);
}

**Comment by poornas** [comment]
@sdjunaidali , can you try setting ```config.scheme = Aws::Http::Scheme::HTTP;``` in the config?  By default aws-sdk-cpp uses https. I tested this on localhost and lists objects when scheme is set correctly.

**Comment by sdjunaidali** [comment]
Tried with config.scheme = Aws::Http::Scheme::HTTP; 

./list_object <bucket_name> <prefix>

example: ./list_object mybucket dir1/   
*Where dir1/ is list object prefix and empty directory on object store *

I am getting ListObjects error with no proper error message using ,

std::cout << "ListObjects error: " <<
                list_objects_outcome.GetError().GetExceptionName() << " " <<
                list_objects_outcome.GetError().GetMessage() << std::endl;

You can try list object in your environment with prefix option (On empty directory) as defined in above mention program with whatever config scheme of your choice.

**Comment by poornas** [comment]
@sdjunaidali , It lists correctly even with a empty prefix with latest minio from master branch. Which version of minio are you using? 
```
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/s3/model/ListObjectsRequest.h>
#include <aws/s3/model/Object.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
/**
 * List objects (keys) within an Amazon S3 bucket.
 */
int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    Aws::InitAPI(options);
    {
        if (argc < 2)
        {
            std::cout << std::endl <<
                "To run this example, supply the name of a bucket to list!" <<
                std::endl << "Ex: list_objects <bucket-name>" << std::endl
                << std::endl;
            exit(1);
        }

        const Aws::String bucket_name = argv[1];
        std::cout << "Objects in S3 bucket: " << bucket_name << std::endl;
       Aws::Client::ClientConfiguration config;
       config.endpointOverride = "localhost:9000";
       config.scheme = Aws::Http::Scheme::HTTP;
       auto credentials = Aws::Auth::AWSCredentials("minio", "minio123");
       Aws::S3::S3Client s3_client = Aws::S3::S3Client(credentials,      config,Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always, false);
        Aws::S3::Model::ListObjectsRequest objects_request;
        objects_request.WithBucket(bucket_name);

        auto list_objects_outcome = s3_client.ListObjects(objects_request);

        if (list_objects_outcome.IsSuccess())
        {
            Aws::Vector<Aws::S3::Model::Object> object_list =
                list_objects_outcome.GetResult().GetContents();

            for (auto const &s3_object : object_list)
            {
                std::cout << "* " << s3_object.GetKey() << std::endl;
            }
        }
        else
        {
            std::cout << "ListObjects error: " <<
                list_objects_outcome.GetError().GetExceptionName() << " " <<
                list_objects_outcome.GetError().GetMessage() << std::endl;
        }
    }

    Aws::ShutdownAPI(options);
}
➜  s3_build git:(master) ✗ ./list_objects testg em3/
Objects in S3 bucket: testg
* em3/


```

**Comment by sdjunaidali** [comment]
I am using default version from **curl -O https://dl.minio.io/server/minio/release/linux-amd64/minio**
Should I take the source from github and build minio from source?

# minio --help
NAME:
  minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  gateway  Start object storage gateway.
  update   Check for a new software update.
  version  Print version.
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/root/.minio")
  --quiet                       Disable startup information.
  --json                        Output server logs and startup information in json format.
  --help, -h                    Show help.
  
VERSION:
  2018-05-25T19:49:13Z

**Comment by poornas** [comment]
@sdjunaidali, it should list correctly with the minio binary you downloaded. Are you running minio with tls? What's the error message that's displayed when list_objects fails?

**Comment by zetaab** [comment]
I have problems that minio is not listing directories that it does in AWS. It is listing only directories that is empty.

Example (create following dir structure to minio):
```
emptydir/ (this is just empty directory)
dirwithfiles/firstfile (file inside directory)
```

```
/storage/test2 # ls -lR
.:
total 8
drwxr-xr-x    2 root     root          4096 Jun 15 05:44 dirwithfiles
drwxr-xr-x    2 root     root          4096 Jun 15 05:44 emptydir

./dirwithfiles:
total 4
-rw-r--r--    1 root     root             7 Jun 15 05:46 firstfile

./emptydir:
total 0
```
Listing everything
```
        response = self.client.list_objects_v2(
            Bucket=self.bucket,
            Prefix='/',
        )
        for obj in response.get('Contents', []):
            print("%s %d" % (obj['Key'], obj['Size']))
```

The output in minio:
```
% python main.py
dirwithfiles/firstfile 7
emptydir/ 0
```

The output in aws:
```
% python main.py
dirwithfiles/ 0
dirwithfiles/firstfile 7
emptydir/ 0
```

I am using minio/minio:latest docker container

I created own issue for this #6047

**Comment by sdjunaidali** [comment]
@poornas yes i am running minio with tls, everything is working fine, just the list object is giving issue,

ListObjects error with no proper error message ,

I am using following to print error message in case of error scenario,

std::cout << "ListObjects error: " <<
list_objects_outcome.GetError().GetExceptionName() << " " <<
list_objects_outcome.GetError().GetMessage() << std::endl;

**Comment by poornas** [comment]
@sdjunaidali, if you are running minio locally with tls enabled, the ssl certificate verification needs to be turned off with ```config.verifySSL=false``` and ```config.scheme = Aws::Http::Scheme::HTTPS``` (this can be removed since aws cpp sdk uses https by default) If you continue to have listing issues, please post any error logs on the minio server console.

**Comment by sdjunaidali** [comment]
@poornas **just found that ListObject API not working with WithPrefix option only.** 

**It's successfully listing empty directories incase without WithPrefix option in program,**

**Please find the aws sdk logs for ListObject API with WithPrefix option.**

[INFO] 2018-06-27 18:28:52 Aws_Init_Cleanup [140339551385472] Initiate AWS SDK for C++ with Version:1.3.30
[INFO] 2018-06-27 18:28:52 CurlHttpClient [140339551385472] Initializing Curl library
[INFO] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Initializing CurlHandleContainer with size 25
[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Using cached empty string sha256 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 because payload is empty.
[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Canonical Header String: content-type:application/xml
host:10.1.1.193
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20180627T125852Z

[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Signed Headers value:content-type;host;x-amz-content-sha256;x-amz-date
[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Canonical Request String: GET
/ryussi
list-type=2&prefix=New%20folder%2F
content-type:application/xml
host:10.1.1.193
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20180627T125852Z

content-type;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Final String to sign: AWS4-HMAC-SHA256
20180627T125852Z
20180627/us-east-1/s3/aws4_request
0c9714f22a2d79f2e731fdbe37585b227afdb46e65bd1011d664793dd754fe18
[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Final computed signing hash: ef38d56b076b578d3546de24c861aa3f2c129a3b8cd1eaaab9e80109a5b04438
[DEBUG] 2018-06-27 18:28:52 AWSAuthV4Signer [140339551385472] Signing request with: AWS4-HMAC-SHA256 Credential=BCL8OLKMMVENDQM0DNNU/20180627/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=ef38d56b076b578d3546de24c861aa3f2c129a3b8cd1eaaab9e80109a5b04438
[DEBUG] 2018-06-27 18:28:52 AWSClient [140339551385472] Request Successfully signed
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Attempting to acquire curl connection.
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] No current connections available in pool. Attempting to create new connections.
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] attempting to grow pool size by 2
[INFO] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Pool grown by 2
[INFO] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Connection has been released. Continuing.
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Returning connection handle 0xf5f420
[DEBUG] 2018-06-27 18:28:52 CurlHttpClient [140339551385472] Obtained connection handle 0xf5f420
[DEBUG] 2018-06-27 18:28:52 CurlHttpClient [140339551385472] Returned http response code 200
[DEBUG] 2018-06-27 18:28:52 CurlHttpClient [140339551385472] Returned content type application/xml
[DEBUG] 2018-06-27 18:28:52 CurlHttpClient [140339551385472] Releasing curl handle 0xf5f420
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Releasing curl handle 0xf5f420
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Notified waiting threads.
[DEBUG] 2018-06-27 18:28:52 AWSClient [140339551385472] Request returned successful response.
[INFO] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Cleaning up CurlHandleContainer.
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Cleaning up 0xf56180
[DEBUG] 2018-06-27 18:28:52 CurlHandleContainer [140339551385472] Cleaning up 0xf5f420

**Comment by sdjunaidali** [comment]
**Please find the program which I am using to list Object with WithPrefix option,**

#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/s3/model/Bucket.h>
#include <aws/s3/model/Object.h>
#include <aws/s3/model/ListObjectsV2Request.h>


/**
 * List objects (keys) within an Amazon S3 bucket.
 */
int main(int argc, char** argv)
{
    Aws::SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Debug;
    Aws::InitAPI(options);
    {
        if (argc < 3)
        {
            std::cout << std::endl <<
                "To run this example, supply the name of a bucket to list!" <<
                std::endl << "Ex: list_objects <bucket-name>" << std::endl
                << std::endl;
            exit(1);
        }

        const Aws::String bucket_name = argv[1];
        const Aws::String directory_path = argv[2];
        std::cout << "Objects in S3 bucket: " << bucket_name << " directory path " << directory_path << std::endl;

        /*Aws::Client::ClientConfiguration clientConfig;
        clientConfig.region = "ap-south-1";
        Aws::S3::S3Client s3_client(clientConfig);*/

        Aws::Client::ClientConfiguration config;
        config.endpointOverride = "10.1.1.193:9000";
        config.verifySSL=false;
        config.scheme = Aws::Http::Scheme::HTTPS;
        auto credentials = Aws::Auth::AWSCredentials("BCL8OLKMMVENDQM0DNNU", "6FAbPM+Swg6Nz4xHmeCCtCLB5eQPmCeWDERTsZol");
        Aws::S3::S3Client s3_client = Aws::S3::S3Client(credentials, config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always, false);

        Aws::S3::Model::ListObjectsV2Request objects_request;
        objects_request.WithBucket(bucket_name);
        objects_request.WithPrefix(directory_path);

        auto list_objects_outcome = s3_client.ListObjectsV2(objects_request);

        if (list_objects_outcome.IsSuccess())
        {
            Aws::Vector<Aws::S3::Model::Object> object_list =
                list_objects_outcome.GetResult().GetContents();

            if(object_list.size() == 0) {
                std::cout << "*Object List Size* " << object_list.size() << std::endl;
                return 1;
            }

            for (auto const &s3_object : object_list)
            {
                std::cout << "* " << s3_object.GetKey() << std::endl;
            }
        }
        else
        {
            std::cout << "ListObjects error: " <<
                list_objects_outcome.GetError().GetExceptionName() << " " <<
                list_objects_outcome.GetError().GetMessage() << std::endl;
        }
    }

    Aws::ShutdownAPI(options);
}

**Output:**

root@jsubun2:~/ios_s3/junaid/new_approach# ./a.out ryussi junaid/
Objects in S3 bucket: ryussi directory path junaid/
*Object List Size* 0

**Here junaid/ is empty directory on object store.**

**Comment by poornas** [comment]
@sdjunaidali, was able to repro this issue for ListObjects when prefix ends with a slash delimiter - i.e. listing is correct when prefix is junaid but not junaid/  Will be sending a fix for this.

**Comment by sdjunaidali** [comment]
@poornas , Actually it's working without slash delimiter, I am going ahead with this solution as it will work without the slash delimiter.

Thank you so much for looking into the matter. and let me know when fix for this is out, 
Will be happy to give any contribution for this,

**Comment by poornas** [comment]
@sdjunaidali, the reason ListObjects with prefix dir1/ (where dir1/ is empty directory on object store) does not list on minio is because minio is using the file system hierarchy for storing objects whereas s3 uses a flat namespace. On s3, the prefix "dir1/" in entirety is itself just a key to the blob location,so s3 lists it as a result. From minio's perspective, ListObjects with "dir1/" as prefix is listing objects in the filesystem's dir1 directory, hence it returns nothing because the directory is empty.

We could make changes to our implementation to list empty directory as well when you query ListObjects with "dir1/" as prefix, but would like to first understand why it is important to your application to list empty directory in this manner. We discourage creating empty directory as an object, because it would pose issues if you were to sync the data back to filesystem or to an object store other than s3.

Lets say you want to store objects grouped by prefix "dir1" under a bucket, conceptually similar to storing files in a folder. s3 will allow creating object with key "dir1/"(representing empty directory), "dir1" (representing file in filesystem lingo) , and also prefixed by dir1 such as "dir1/a/b" (similar to subdirectories). Look at the example listing below showing the actual object names and the result of aws cli command to sync the data in your bucket back to the file system.

aws cli silently fails to create a dir1/ object or the object named dir2 if dir2/ directory already exists.So storing objects to connote empty directory on s3 can actually pose consistency issues if you were to move the data out of s3. Instead, it is recommended to put objects into the object store with keys in the form "parent_dir/object" would automatically group objects by the prefix "parent_dir" without the overhead of an extra object to represent empty directory, and syncing issues. 

```
➜  minio git:(listobjects) ✗ mc ls --r s3/dir1
[2018-06-28 18:26:52 PDT]    24B dir1/
[2018-06-28 18:27:35 PDT]    24B dir1/issue
[2018-06-28 18:32:44 PDT]     0B dir2
[2018-06-28 18:32:04 PDT]     0B dir2/
[2018-06-28 18:28:09 PDT]    24B dir2/issue

➜  minio git:(listobjects) ✗ aws s3 sync s3://bucket1 /tmp/t
download failed: s3://bucket1/dir1/ to ../../../../../../../tmp/t/dir1/ [Errno 20] Not a directory
download failed: s3://bucket1/dir2 to ../../../../../../../tmp/t/dir2 [Errno 21] Is a directory
download: s3://bucket1/dir2/issue to ../../../../../../../tmp/t/dir2/issue
download: s3://bucket1/dir1/issue to ../../../../../../../tmp/t/dir1/issue

```

If there is a compelling reason for your application to be able to list empty directory despite the issues mentioned above,it would help us reconsider the current implementation.

**Comment by poornas** [comment]
@sdjunaidali, can this issue be closed

**Comment by sdjunaidali** [comment]
@poornas ,

Thank you so much for the detailed answer for that prefix problem, I am fully satisfied with the answer.
and yeah you can close this issue.

**Comment by pitrou** [comment]
I'm having the same problem here. I determined that handling of directories by Minio is fragile and inconsistent:
* an empty directory is visible with [HEAD object](https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/API/RESTObjectHEAD.html) but not with [ListObjects v2](https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/API/v2-RESTBucketGET.html)
* a non-empty directory is visible with [ListObjects v2](https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/API/v2-RESTBucketGET.html) but not with [HEAD object](https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/API/RESTObjectHEAD.html)

This makes it more difficult than necessary to navigate through Minio directories. It also makes Minio [incompatible](https://github.com/PyFilesystem/s3fs/issues/57) with S3 access libraries such as Python [s3fs](https://fs-s3fs.readthedocs.io/en/latest/), even though Minio is advertised for its S3 compatibility.

**Comment by harshavardhana** [comment]
Directory creates are a largely misused operation with implementations like s3fs. The point is s3fs doesn't need to do HEAD and fail for the directory. Because listing will succeed in second case where it is non-empty and that should tell s3fs that prefix indeed exists. Navigating directories purely based on Listing is the expected approach even in S3 API.

We generally do want lesser incompatiblities with S3 applications, but for common sense reasons here we did diverge because we think creating directories on a flat namespace is rather a fruitless operation as a client, every such client which depends on this largely incorrectly implemented. Creating a directory doesn't guarantee anything special for an App. It infact brings lot more complications for the client to be able to delete the heirarchy appropriately, involves now multiple calls to the same path even with flat namespace. This essentially slows down applications, imagine one zero byte object for every directory that you have to additionally delete.

What it does come down to is POSIX like legacy requirements for applications such as s3fs, so for the time being unless s3fs is fixed appropriately to rely on ListObjects non recursive when HEAD fails is correct fix.

**Comment by pitrou** [comment]
Well, many libraries try to provide filesystem-like facility on top of S3, because it makes sense when you want to abstract away from the underlying storage kind (local filesystem, S3, GCS, etc.).

**Comment by harshavardhana** [comment]
@pitrou we have deployed and tested 1000s of such applications such as Hadoop S3A, Spark, Presto and Splunk. Our community has perhaps even tested more.

Every time the directory issue comes is either an incorrect requirement for a client app or strong POSIX like semantics. You can see we have no inclination of encouraging POSIX like behavior and there are clearly ways to address this on the client side.
