### ISSUE TITLE
Presigned URLs don't work if accesskey contains special characters

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio#6011]
## Expected Behavior

Accessing the presigned URL generated for a file downloads or shows the file and shouldn't matter what value the access key is set to.

## Current Behavior

If access key contains for example "(" or "!" minio can create a presigned URL but accessing it shows a _**SignatureDoesNotMatch**_ error.

## Possible Solution

Possibly some issue with urlencode/decode?
If "special chars" are not allowed in access key maybe prevent using them for login aswell?

## Steps to Reproduce (for bugs)

1. Start Minio with access key set to "Test(" or "Test!"
2. Upload a file (or use an existing one) and create a presigned URL for it (for example via browser ui)
3. Copy the Link
4. Try to access it

## Context

Trying to generate presigned URLs automaticly accessing the presigned URL stopped working possibly cause I changed the access key. I'm using minio behind a reverse proxy (traefik) so I at first thought that is the reason why it stopped working but after testing I discovered the above issue.

## Your Environment

* Version used (`minio version`): ```RELEASE.2018-05-25T19-49-13Z```
* Environment name and version (e.g. nginx 1.9.1): ```traefik 1.6.2```
* Operating System and version (`uname -a`): ```Linux 4.13.0-36-generic #40~16.04.1-Ubuntu```
Using docker: ```Docker version 18.03.0-ce, build 0520e24```

**Comment by kannappanr** [comment]
@WolfspiritM Thanks for filing this issue. I was able to reproduce the bug when I used browser UI. `mc` client was able to create a URL that had the special characters escaped when the presigned URL was generated, so I did not observe the error there. On slack you had also mentioned that it failed with SDK, can you let us know which SDK you used? We will send in a fix very soon.

**Comment by WolfspiritM** [comment]
@kaankabalak Thanks! I was using the .NET SDK which failed. Maybe that's the reason why I did think it worked before as I was using the node sdk before and that seemed to work fine.
