### ISSUE TITLE
Kubernetes secret file environment variable ignored at minio start

### ISSUE THREAD

**Issue by blackholegalaxy** [minio/minio#6014]
When running minio on kubernetes and using secrets, we have to define a sub path within `/run/secrets` as kubernetes prevents us to place secrets files at this secrets root path.

We setup our secrets to be placed at:
`/run/secrets/minio/access_key`
`/run/secrets/minio/secret_key`

## Expected Behavior
Defining the environment variable `MINIO_ACCESS_KEY_FILE` and `MINIO_SECRET_KEY_FILE`, minio should use value of these env variables to look for access and secret keys.

## Current Behavior
We defined two environment variables as stated in docker documentation to inform minio our access_key and secret_key are in a different location than default files.

<img width="849" alt="screen shot 2018-06-05 at 7 36 43 am" src="https://user-images.githubusercontent.com/11064123/40973712-3d01c25a-6893-11e8-9c60-af2289d952d7.png">

These env variables are transmitted with success to the pod:

<img width="548" alt="screen shot 2018-06-05 at 7 39 14 am" src="https://user-images.githubusercontent.com/11064123/40973837-a4c49458-6893-11e8-9e70-fb03c3452f41.png">

Our secret also appears correctly on the container at expected path:

<img width="211" alt="screen shot 2018-06-05 at 7 38 21 am" src="https://user-images.githubusercontent.com/11064123/40973782-722d64d4-6893-11e8-8c8b-e216c323b448.png">

The files contains the proper access and secret key.

But at minio start (fresh, without existing config.json), then minio keeps generate its own access key and secret key. Completely ignoring my secrets. 

## Possible Solution
 - Make minio treat `MINIO_ACCESS_KEY_FILE` and `MINIO_SECRET_KEY_FILE` as full path for secret and access keys.

In our case we simply got it work using not full path but `minio/access_key` in the environment variable. But What if we want to place access_key anywhere else than `/run/secrets` directory (for example `/srv/secrets`)?.

These lines in entrypoint prevents us to use other directory.

```
local ACCESS_KEY_FILE="/run/secrets/$MINIO_ACCESS_KEY_FILE"
local SECRET_KEY_FILE="/run/secrets/$MINIO_SECRET_KEY_FILE"
```

## Context
This behavior will allow minio to run seamlessly on kubernetes clusters where we cannot place `access_key` and `secret_key` secrets at `/run/secrets` root due to kubernetes restrictions.

## Your Environment
* Version used (`minio version`): Docker image **RELEASE.2018-05-25T19-49-13Z**
* Server type and version: **Kubernetes v1.10.1**
* Operating System and version: **Ubuntu 16.04**

**Comment by nitisht** [comment]
@blackholegalaxy you can use `MINIO_ACCESS_KEY` & `MINIO_SECRET_KEY` variables and set the values in these variables using this https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by nitisht** [comment]
@blackholegalaxy closing this as answered, feel free to get back if there are further issues.

**Comment by tech-mint** [comment]
> @blackholegalaxy you can use `MINIO_ACCESS_KEY` & `MINIO_SECRET_KEY` variables and set the values in these variables using this https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

this is not working as you expect

**Comment by harshavardhana** [comment]
Feel free open a new issue @tech-mint

**Comment by aculver28** [comment]
Should this have been closed? I can confirm the answer provided doesn't work as minio isn't reading those environment variables when they're set in the k8s containers.

**Comment by harshavardhana** [comment]
Please open a new issue @aculver28 let's not confuse with old issues.

**Comment by cyberious** [comment]
It is the same issue, I am running into this as well. Only if you pass the values in the helm chart which injects them into the config does it work. This old issue should have never been closed though it wasn't fixed.

**Comment by nitisht** [comment]
We’ll check and get back here

**Comment by aculver28** [comment]
Sorry...I resolved my issue. There was a newline character at the end of the value when it was base64 encoded. Fixed that and I was able to use the encrypted values stored as k8s secrets with no problem.

**Comment by cyberious** [comment]
I think I had the same issue, despite being typically diligent about it. 🤦‍♂️ 

That being said I do believe we should be removing the credentials from the config file in the helm template since we are setting them through environment variables as well. It adds confusion to where the values may be coming from and which one overrides which.

**Comment by harshavardhana** [comment]
ENVs always override what is there in the config @cyberious , we are improving the helm chart as well.

**Comment by nitisht** [comment]
Thanks @aculver28 @cyberious closing this issue then. There is a PR to remove configMaps from Helm chart https://github.com/helm/charts/pull/10828 to avoid this confusion. 

Feel free to open a new issue if you see any issues
