### ISSUE TITLE
Very slow response on rendering images from Minio

### ISSUE THREAD

**Issue by alirezastack** [minio/minio#6020]
## Expected Behavior
Very smooth rendering of uploaded objects (images) in the browser

## Current Behavior
I'm using `Minio` python package in `Flask` in order to return images to end users. The code I have used is simple as below:
```
            # Get a full object
            data = self.minio_client.get_object('avatar', file_name)

            app.logger.debug('file {} is retrieved'.format(file_name))

            return Response(data, content_type='image/png')
```

It takes about 1 second to return an image which is about 28 KB! Minio is ran inside of docker image.

## Steps to Reproduce (for bugs)
1. run a simple flask application
2. upload a sample image to a bucket
3. Now try to retrieve the image with the above given code.
4. It will takes a long time to retrieve a small image. A picture with 100 KB in size will take 6 Secs!

## Your Environment
* Version used (`minio version`): DOCKER image with latest version
* Minio Python SDK: 4.0.0

## Minio About section reports that:
* VERSION: 2018-05-25T19:49:13Z
* MEMORY: Used: 5.2 MB | Allocated: 20 MB | Used-Heap: 5.2 MB | Allocated-Heap: 8.7 MB
* PLATFORM Host: cf124cb3e9bb | OS: linux | Arch: amd64
* RUNTIME: Version: go1.10.1 | CPUs: 2

**Comment by harshavardhana** [comment]
@alirezastack what is the network bandwidth on the client to server? are they both hosted on the same network or are you accessing it over a WAN? are you running in distributed mode?

**Comment by alirezastack** [comment]
@harshavardhana  They are both on the same network, my local system. `Flask` application is in swarm mode and `Minio` server is a stand alone docker container. `Minio` container exposes its port  on host machine with port number 9100. No WAN and not in distributed mode.

**Comment by alirezastack** [comment]
@harshavardhana it's good to note that downloading the file directly from the `Minio` dashboard takes no time. Even a 2 MB file will be downloaded within milliseconds. And uploading a file does not take time at all from within flask application. Maybe the `Minio` python SDK has problems or is incompatible with Flask Response.

**Comment by harshavardhana** [comment]
> @harshavardhana it's good to note that downloading the file directly from the Minio dashboard takes no time. Even a 2 MB file will be downloaded within milliseconds. And uploading a file does not take time at all from within flask application. Maybe the Minio python SDK has problems or is incompatible with Flask Response.

@alirezastack this looks like minio-py SDK problem. How are you downloading the stream? did you provide the read buffer size for the stream?

**Comment by harshavardhana** [comment]
Since its a stream you need to make sure to read in large blocks by default it will read in '1' byte at a time. Can you try doing the following in your application? NOTE: here we are using 32K blocks
 
```
# Get a full object
try:
    data = client.get_object('my-bucketname', 'my-objectname')
    with open('my-testfile', 'wb') as file_data:
        for d in data.stream(32*1024):
            file_data.write(d)
except ResponseError as err:
    print(err)
```

**Comment by alirezastack** [comment]
@harshavardhana thank you for your response, but isn't there a way to return the result on the fly without writing every single image request into a file?

I have solved the problem by your code sample and using `direct_passthrough` in `response`:

```
app.logger.debug('[AvatarStorage] writing to a file...')
with open(file_name, 'wb') as file_data:
    for d in data.stream(32 * 1024):
        file_data.write(d)

app.logger.debug('[AvatarStorage] written to {} file...'.format(file_name))

app.logger.debug('[AvatarStorage] make a generator from file path...')
g = file(file_name)  # or any generator
app.logger.debug('[AvatarStorage] return response in stream')
return Response(g, content_type=self.mimetype_map[ext], direct_passthrough=True)
```

**Comment by harshavardhana** [comment]
> @harshavardhana thank you for your response, but isn't there a way to return the result on the fly without writing every single image request into a file?

you don't, of course, need to do that - that was an example of how to read larger stream. Since python doesn't give you the entire stream if you want the full stream simply do `data.read()` which will read the entire content. If you want to stream it directly. It is better to flask not to perform the GET operation instead it should pass the burden to UI to perform the GET operation.
