### ISSUE TITLE
multipartupload invalid byte: U+0057 'W' with rclone

### ISSUE THREAD

**Issue by si458** [minio/minio#6025]
## Expected Behavior

i was expected to be able to copy a file using rclone

## Current Behavior

it doesnt upload this one file correctly, just throws an error

> 
> API: CompleteMultipartUpload(bucket=mybackups, object=HESTOR/sCANS/User_RBSLYN_15_05_2018_15_42_36.txt)
> Time: 15:38:30 UTC 06/07/2018
> RemoteHost: 172.16.46.5:33824
> UserAgent: rclone/v1.41
> Error: encoding/hex: invalid byte: U+0057 'W'
>        1: cmd/object-api-utils.go:183:cmd.getCompleteMultipartMD5()
>        2: cmd/fs-v1-multipart.go:507:cmd.(*FSObjects).CompleteMultipartUpload()
>        3: cmd/object-handlers.go:1400:cmd.(ObjectLayer).CompleteMultipartUpload-fm()
>        4: cmd/object-handlers.go:1404:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
>        5: cmd/api-router.go:67:cmd.(objectAPIHandlers).CompleteMultipartUploadHandler-fm()
>        6: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

## Steps to Reproduce (for bugs)

1. upload file using rclone

## Your Environment

* Version used (`minio version`): latest on docker
* Environment name and version (e.g. nginx 1.9.1): docker
* Server type and version: 
* Operating System and version (`uname -a`): ubuntu 16.04
* Link to your project:

**Comment by kannappanr** [comment]
@si458 Is there a proxy in between rclone and minio? Looking at the error, the etag that is being passed to minio server from one of the parts has an invalid E-Tag, maybe it is a weak E-Tag and it is not supported in S3. Can you create a HTTP trace for minio server when you put this particular file and paste on this issue? 

Turning on HTTP tracing for minio server is explained in https://github.com/minio/minio/issues/5710

**Comment by si458** [comment]
I am indeed using caddy with simple ‘proxy / 127.0.0.1:8000’
So not sure why it would be that but will investigate it in the morning

**Comment by kannappanr** [comment]
@si458 Were you able to investigate this issue, can you please update the issue if you did?

**Comment by si458** [comment]
I have been out the office all day and weekend, so I won’t have change to look at it til Monday, if I get chance before then I will update you :)

**Comment by kannappanr** [comment]
@si458 please let me know if you were able to investigate the issue?

**Comment by giezi** [comment]
Hi @kannappanr @si458 

We encounter exactly the same issue with minio and are also using a Caddyserver as a proxy in front to terminate the https connections on the same machine:

`Time: 05:36:49 CEST 06/19/2018
RemoteHost: 127.0.0.1:54608
UserAgent: Minio (amd64; amd64) minio-java/dev
Error: [31m[1mencoding/hex: invalid byte: U+0057 'W'[0m[0m
       1: cmd\object-api-utils.go:186:cmd.getCompleteMultipartMD5()
       2: cmd\fs-v1-multipart.go:507:cmd.(*FSObjects).CompleteMultipartUpload()
       3: cmd\object-handlers.go:1462:cmd.(ObjectLayer).CompleteMultipartUpload-fm()
       4: cmd\object-handlers.go:1466:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       5: cmd\api-router.go:67:cmd.(objectAPIHandlers).CompleteMultipartUploadHandler-fm()
       6: pkg\handlers\http-tracer.go:149:handlers.TraceReqHandlerFunc.func1()
       7: net\http\server.go:1947:http.HandlerFunc.ServeHTTP()`

Please find attached also the whole trace log of the minio:
[minio_log.txt](https://github.com/minio/minio/files/2114104/minio_log.txt)

Minio version:
Version: 2018-06-09T03:43:35Z
Release-Tag: RELEASE.2018-06-09T03-43-35Z
Commit-ID: 371349787f0e324f072b03ed5a7842229d6b3174

Caddy version:
Caddy 0.11.0

Caddy Config:

<img width="256" alt="screen shot 2018-06-19 at 08 48 23" src="https://user-images.githubusercontent.com/1326203/41581065-8fb65244-739d-11e8-82ee-ce32cba06c3b.png">

Many thanks for any help.

Best regards
Reto

**Comment by kannappanr** [comment]
@giezi We will try to reproduce the issue here. Can you confirm that for the same file, you do not see this issue if you do not use caddy server?

**Comment by giezi** [comment]
Hi @kannappanr 

Many thanks for your answer.
We've tried to upload a file without Caddy and it works perfectly.
The issue exists only in combination with Caddy.

Best regards
Reto

**Comment by giezi** [comment]
Hi @kannappanr 

Do you have any news regarding the issue?
I'm happy to help you with more information or testing :)

Thanks
Reto

**Comment by kannappanr** [comment]
Hi Reto,

 Sorry for the delay in response. Can you remove `gzip` from your caddy config file? Here is the corresponding commit in caddy server's code https://github.com/mholt/caddy/commit/e2544597a1f5fe0842012bbbde29213745844ea7

Looks like in this case, it will always convert it to a weak etag. Please let us know how it goes.

**Comment by giezi** [comment]
Hi @kannappanr 

No problem - it works now flawlessly without the "gzip" option.
Many thanks for your great help!

Best regards
Reto

**Comment by kannappanr** [comment]
@si458 closing the issue as answered based on the response by @giezi . Please feel free to re-open the issue if you feel otherwise.

**Comment by kannappanr** [comment]
@giezi Thanks for verifying the suggestion and getting back to us.
