### ISSUE TITLE
[gateway/s3] list-objects-v2 request with start-after parameter fails

### ISSUE THREAD

**Issue by wd256** [minio/minio#6032]
## Expected Behavior

When making a `list-objects-v2` request with the `start-after` parameter set I expect the server to respond with a list of key names starting after the provided `start-after` value.

## Current Behavior

The current behaviour when a `list-objects-v2` request is made with `start-after` set is for a 500 error response to be returned and a "The continuation token provided is incorrect" error logged in minio.

## Possible Solution

The issue appears to be caused by minio using the `start-after` parameter as a `continuation-token`.

## Steps to Reproduce (for bugs)

1. Use the aws CLI to send a `list-objects-v2` request with the `start-after` parameter set.

`aws --endpoint-url http://127.0.0.1:9000 s3api list-objects-v2 --bucket testbucket --start-after object123`

## Your Environment

minio version: master (commit 12a916091e6ed98fda1ce0c4a00e98a561a1cb2c)
OS: Linux amd64

**Comment by wd256** [comment]
Testing with master (commit: 670b538dde78ce28f09b7be83f787722ccabca59) the issue is still present.  `ListObjectsV2Handler` will also need an update to not use `start-after` as a `continuation-token`.

**Comment by wd256** [comment]
@nitisht can you please re-open this issue?

**Comment by harshavardhana** [comment]
> @nitisht can you please re-open this issue?

@wd256 please open a new issue referencing this issue.
