### ISSUE TITLE
S3 and slash object

### ISSUE THREAD

**Issue by limbo127** [minio/minio#6034]
hello, 
it seems that's minio does not deal with / object of aws s3 key.
When we mirror with mc client from S3 bucket to minio server , our client and sdk java , seems to have problem with the fact that /  ( in directory path)   bucket/test/test1 ) is not considered as object by minio server ? 
regards, 
Nicolas PRochazka

**Comment by harshavardhana** [comment]
Yes, it is not an object @limbo127 "/" is simply a delimiter on a filesystem. It is not just Minio if you simply use aws cli you won't be able to preserve the "/"

**Comment by limbo127** [comment]
I do not understand
Minio server or minio client transpose valid object key names from s3 as a directory structure on file system, by using / as tree structure, how preserve / in object naming

**Comment by harshavardhana** [comment]
@limbo127 please read this explanation https://github.com/minio/minio/issues/5874#issuecomment-385766704

**Comment by harshavardhana** [comment]
@limbo127 and here https://github.com/minio/minio/issues/5874#issuecomment-385764617

**Comment by harshavardhana** [comment]
Closing as won't fix for now.

**Comment by limbo127** [comment]
I believe every single client that supports creating empty directories on s3 uses this pattern.
as for example   goofys – FUSE S3 filesystem

They all create keys that end with a slash, have a ContentLength of 0 bytes and as such all have the ETag "d41d8cd98f00b204e9800998ecf8427e". The ContentType differs between clients, most use either "binary/octet-stream" or "application/octet-stream"

Pretty much all of the commandline tools do not handle these "directories" properly and fail to handle them during sync / copy either with warning or errors:

    s3cmd
    minio client

The official python awscli simply ignores those keys. It never creates empty directories when syncing from local to s3 and never downloads them when syncing or copying from s3 to local. That's not perfect but a lot better than clients that try to compare the key as a regular file with the local directory and error out because of the different types.

From server point of view, s3proxy based on jclouds api, for example, manage attr on linux when object are created.

What can I say it is : 
copy with goofys as client and s3proxy  works well
copy with goofys as client and minio server not works as S3 api standard says
copy with minio client to s3proxy not works 

Regards, 
Nicolas

**Comment by github-wisper** [comment]
need to be fixed, please
