### ISSUE TITLE
Enhancement: gateway to multiple GCS accounts

### ISSUE THREAD

**Issue by msample** [minio/minio#6037]
I successfully used Minio as an S3 gateway to a GCS bucket in one account.  I would like to use it as a gateway to buckets in many different GCS accounts.    Given that bucket names are globally unique, if one provided a pluggable & queryable config storage of bucket name *--> credentials, and modified newObjectLayerFn to take the bucket name (where the operation is scoped to a single bucket or acct), it seems possible to slide in this behavior.    Is this insane?  Would this approach work?  

If this is plausible, one could imagine the gateway bridging different backends (eg. S3 & GCS), where bucket name uniqueness doesn't hold,  e.g. by having Minio clients use a provider prefix on the bucket name.

**Comment by deekoder** [comment]
@msample  I am not sure if your endgoal is to get bucket level dns support. If so, can you look at this https://github.com/minio/minio/tree/master/docs/federation/lookup for reference. If not, then please ignore my note here.

**Comment by msample** [comment]
thanks @deekoder, federation isn't a good fit for my use case - e.g. imagine a set of identically configured Minio gateways behind a load balancer that could proxy to GCS for a dynamically configured set of buckets/accts.  Having one GCS acct per gateway process doesn't offer the type of efficiency I'm seeking.

**Comment by deekoder** [comment]
ok @msample we will consider this for the future. We close this issue in the future milestone and reactivate them as we make enhancements in the future.

**Comment by mamoit** [comment]
I just ran into this use case, where I want to be able to do a gateway, not to all buckets in a specific account, but to a list of buckets that belong to different accounts.

**Comment by harshavardhana** [comment]
> I just ran into this use case, where I want to be able to do a gateway, not to all buckets in a specific account, but to a list of buckets that belong to different accounts.

That is our of scope for our gateway implementation @mamoit - feel free to write your own implementation.
