### ISSUE TITLE
[gateway/gcs] max-keys not enforced for list-objects-v2 requests

### ISSUE THREAD

**Issue by wd256** [minio/minio#6052]
## Expected Behavior
When making a `list-objects-v2` request with the `max-keys` parameter set I expect the server to respond with a list of keys no greater in length than the provided `max-keys` value.

## Current Behavior

The current behaviour is for minio to return all keys in the bucket regardless of the `max-keys` value specified.

## Steps to Reproduce (for bugs)

1. Prepare a bucket on Google Cloud Storage with 10 objects added to it
2. Use the aws CLI to send a `list-objects-v2` request targeting the bucket prepared in step 1 with the `max-keys` parameter set to 5.
`aws --endpoint-url http://127.0.0.1:9000 s3api list-objects-v2 --bucket testbucket --max-keys 5`
3. Observe that all 10 objects in the bucket are included in the response rather than a maximum of 5.

## Your Environment

minio version: master (commit 2575f4198a860e06abded4aa59747730690aa43b)
OS: Linux amd64

**Comment by krisis** [comment]
@wd256 Does your [PR](https://github.com/minio/minio/pull/6078) fix this issue too?

**Comment by wd256** [comment]
@krisis No, this issue will need its own fix

**Comment by wd256** [comment]
@krisis while testing your pull request I saw that when I set the max-keys parameter the results were correctly limited but no NextContinuationToken was provided in the response and IsTruncated is false.

When I looked into the issue further I noticed that using the object iterator provided by the GCS client is problematic given that we skip the minio.sys.tmp/ key when it appears in the results. This is an issue due to the fact that the iterator will fetch 'pages' of results transparently (using he provided maxKeys property to determine page size) and orders all Objects ahead of CommonPrefixes within that fetched 'page'. When we skip the minio.sys.tmp/ key and possibly cause the iterator to fetch the next page of results in the background, we don't know if there are some Prefixes which will be provided at a later point by the iterator that should appear in the results ahead of some of the Objects on that 'page'.

I saw that the iterator returned by the GCS client can be used with the google.golang.org/api/iterator/Pager struct which allows for control over when the next page of results is fetched. I've created a branch which makes use of Pager to address the issues described above. I also noticed that the GCS ListObjectsV1 impl. was not counting prefixes when limiting results to maxKeys and have made a similar update to that function.

**Comment by nitisht** [comment]
Reopening this, as based on @wd256 [comment](https://github.com/minio/minio/issues/6052#issuecomment-404753031) this is not fixed yet

**Comment by krisis** [comment]
@wd256 thank you for looking closely into this issue. Your proposal, to use `Pager` struct to control listing of objects (and prefixes) on GCS so that we return the exact number of objects requested (by the application in front of the gateway) and setting `ContinuationToken` and `IsTruncated` correctly, sounds good to me. Let me know if you need me to review your code before its ready. Thanks again for looking into the issue.

**Comment by wd256** [comment]
thanks @krisis, I've created a PR for the branch and it would be great if you have a chance to check it out
