### ISSUE TITLE
NATS event notifications are not removed

### ISSUE THREAD

**Issue by dmpriso** [minio/minio#6053]
## Expected Behavior
When removing a NATS bucket notification and afterwards performing an appropriate bucket operation, no NATS message should be published

## Current Behavior
Bucket notification is removed successfully, but NATS message is still published.

## Steps to Reproduce (for bugs)

1. Start ```gnatsd --trace``` and watch for messages here
2. Configure & start minio and create a bucket. Add event notificaiton
```
mc mb minio/testbucket
mc events add minio/testbucket arn:minio:sqs::1:nats
```
3. Remove event notification. It doesn't matter if you remove this or all event notifications.
```
mc events remove minio/testbucket --force
```
4. Verify that the list is empty:
```
mc events list minio/testbucket
```
5. Upload a file
```
mc cp mytextfile.txt minio/testbucket
```
6. Look at the gnatsd output, you will see that the notification has been published.

## Context
Just discovered minio and playing around to see if it fits our project.

## Your Environment

* Version used (`minio version`): Version: 2018-06-09T03:43:35Z
* Operating System and version (`uname -a`):  Windows 10 test machine

**Comment by deekoder** [comment]
we'll look into this.

**Comment by Praveenrajmani** [comment]
ping @nitisht
