### ISSUE TITLE
Credentials not picked up by config file for gateway nas

### ISSUE THREAD

**Issue by racorretjer** [minio/minio#6056]
I'm attempting to run minio with the gateway nas command and the -C <config_dir> option. The config dir contains a config file which describes the desired credentials and other settings for my minio server. Running this with the `minio server` command works just fine, however, not for `minio gateway nas`.

## Expected Behavior
Running `minio gateway nas -C /etc/minio /my/nas` should start the minio server with the settings from /etc/minio/config.json **without specifying environment variables**.

## Current Behavior
Running `minio gateway nas -C /etc/minio /my/nas` results in an error stating that credentials are missing, despite them being available in the /etc/minio/config.json file.

## Possible Solution
Read credentials (and other settings) from the config file as opposed to just environment variables.

## Steps to Reproduce (for bugs)
1. Install minio
2. **Do not export MINIO_ACCESS_KEY or MINIO_SECRET_KEY variables**
3. Create an /etc/minio/config.json file with credentials
4. Run `minio gateway nas -C /etc/minio /your/nas`

## Context
I want all my settings to be in one place and compatible with the `minio server` command across all other commands. This way, I don't have to worry about which variables I have to export at any given moment.

## Your Environment

* Version used (`minio version`):
Version: 2018-06-09T03:43:35Z
Release-Tag: RELEASE.2018-06-09T03-43-35Z
Commit-ID: 371349787f0e324f072b03ed5a7842229d6b3174
* Operating System and version (`uname -a`):
Linux xxxxxxxxxxxxxxxxx 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Gateway nas doesn't support config.json on purpose you only need to set access and secret keys for gateway mode.

**Comment by racorretjer** [comment]
So, I take it that the -C option is available to the cli for the certificates and such?

**Comment by harshavardhana** [comment]
> So, I take it that the -C option is available to the cli for the certificates and such?

yeah, i.e true @racorretjer - we will need to revisit this for nas gateway especially. Will get back to you on this.

**Comment by kannappanr** [comment]
@racorretjer Thanks for filing this issue. We do not have cycles to look into this issue now. Will have to take up this task in the future. Closing this issue for now. Will re-open when we have cycles to look into this issue.
