### ISSUE TITLE
Questions: distributed minio and replication

### ISSUE THREAD

**Issue by moonlitSpider** [minio/minio#6058]
Hello,

I'm trying to better understand a few aspects of distributed minio.

1. Do nodes in the cluster replicate data to each other?
2. Does each node contain the same data (a consequence of #1), or is the data partitioned across the nodes?
3. Why the caveat "Servers running distributed Minio instances should be less than 3 seconds apart"?

Thank you.

**Comment by harshavardhana** [comment]
> Do nodes in the cluster replicate data to each other?

Cluster uses erasure coding i.e stream is sharded across all nodes


> Does each node contain the same data (a consequence of #1), or is the data partitioned across the nodes?

Partitioned data

> Why the caveat "Servers running distributed Minio instances should be less than 3 seconds apart"?

This is to ensure that all servers are running on the same UTC time, we prefer homogenous servers.

**Comment by moonlitSpider** [comment]
Thank you, harshavardhana, for the quick response.

Am I right to think that the use of erasure coding is seen as a "replacement" (so to speak) for replicating the data, i.e., as a perhaps simpler form of data redundancy?

**Comment by harshavardhana** [comment]
> Am I right to think that the use of erasure coding is seen as a "replacement" (so to speak) for replicating the data, i.e., as a perhaps simpler form of data redundancy?

Yes, you are correct, erasure coding is a better way to provide data protection than replication, provides higher protection, higher performance with capacity usage equal to 2x replication.

**Comment by moonlitSpider** [comment]
Thanks again; things are getting clearer!

Can you explain what you mean by "capacity usage equal to 2x replication"?

While I see some of the benefits of erasure coding, it is not a DR solution is it? I suppose for that you'd recommend your mirror facility. If so, does that facility mirror at the cluster level or at the node level?

**Comment by harshavardhana** [comment]
> Can you explain what you mean by "capacity usage equal to 2x replication"?

Our default data and parity counts are equal i.e if you have N disks then our data and parity are both N/2 - in erasure coding parlance the effective data usage, for example, a 1Gi would be 2Gi effectively. This is equal to a 2x replication.  But with very very high redundancy i.e you can loose up to half of your disks and still recover data. 

> While I see some of the benefits of erasure coding, it is not a DR solution is it? I suppose for that you'd recommend your mirror facility. If so, does that facility mirror at the cluster level or at the node level?

For DR you will be doing `mc mirror`.  Mirroring happens endpoint to endpoint. https://docs.minio.io/docs/minio-client-complete-guide#mirror

**Comment by moonlitSpider** [comment]
Thank you, harshavardhana. 

I think that your "endpoint to endpoint" means that mirroring happens at the node level, i.e., if I want to mirror the entire minio cluster to a remote site, then I need to do it node by node.

**Comment by harshavardhana** [comment]
No endpoint to endpoint means cluster to cluster. Each endpoint has access to entire namespace.

**Comment by moonlitSpider** [comment]
Very good; thanks.

To me "endpoint" means IP:PORT so I was concerned about the "granularity" of the mirror. 

So I think you're saying that the Minio client mirror facility can replicate the entire cluster to another cluster by means of a single source endpoint and a single destination endpoint.

**Comment by harshavardhana** [comment]
Yes that is correct

**Comment by moonlitSpider** [comment]
Cool. Is there a minimum number of nodes required for a minio cluster?

And if a new node is added, do you balance the data using the new node?

**Comment by moonlitSpider** [comment]
And what happens to the extant erasure codes if new node is added? Must data be re-read and written in order to generate erasure codes that reflect the new number of disks?

**Comment by harshavardhana** [comment]
> Cool. Is there a minimum number of nodes required for a minio cluster?

A minimum number of nodes is 4, maximum allowed is 32. Number of disks allowed is unlimited - https://docs.minio.io/docs/minio-server-limits-per-tenant

> And if a new node is added, do you balance the data using the new node?

A node cannot be added to an existing cluster, so if you start with 4 it will always be 4 in its entirety.

> And what happens to the extant erasure codes if new node is added? Must data be re-read and written in order to generate erasure codes that reflect the new number of disks?

This is not applicable we don't allow adding new disks. 

What you can do is setup new clusters and add them to a single namespace using federation https://docs.minio.io/docs/minio-federation-quickstart-guide

**Comment by moonlitSpider** [comment]
Interesting, so once a cluster is defined, I cannot add a new node (and thus I can't add new disks)?

**Comment by moonlitSpider** [comment]
How well tested is the cluster federation capability. I can't scale out a single minio cluster by adding nodes/disks. So cluster federation is my only choice.

Please advise, and thanks!

**Comment by harshavardhana** [comment]
> How well tested is the cluster federation capability. I can't scale out a single minio cluster by adding nodes/disks. So cluster federation is my only choice.

Cluster federation capability was recently GAed and is ready to be used in production.

**Comment by harshavardhana** [comment]
Closing this issue as answered for questions like these feel free to join our slack https://slack.minio.io for a more real-time response.

**Comment by moonlitSpider** [comment]
Thank you, hashavardhana. But the slack invite page says "this invite link is no longer active".

How can I join slack?

**Comment by harshavardhana** [comment]
> Thank you, hashavardhana. But the slack invite page says "this invite link is no longer active".

https://slack.minio.io is active and as well as https://minio.slack.com/join/shared_invite/enQtMzg2MDg5OTkzODc3LTg0ZTZhZjI2YmM0ZTM2ODY5ZTc5NWI2YjllNDYzY2ZmZDQwMDJjYjkzYjVlZmFlNmY0YjE2ZmFlMjAxMzdjNDU
