### ISSUE TITLE
logger.Critical{If} should not crash the server

### ISSUE THREAD

**Issue by aead** [minio/minio#6064]
## Expected Behavior
AFAIK `logger.CriticalIf` replaces `panic` calls in our server.
Therefore - in my understanding - `logger.CriticalIf` should not crash the entire server. Instead it
should kill only the go-routine calling it - e.g. using `runtime.Goexit()`. On problem for example occurs
if you try to test that a certain non-recoverable code-path is hit. `os.Exit` causes the tests to terminate immediately. Further `os.Exit` will not call any deferred function calls.   

## Current Behavior
Calling `logger.CriticalIf` crashes the entire server.

## Possible Solution
Requires a bit more research but either `runtime.Goexit()` or `panic()` can be used.
Both will terminate the go-routine. 

## Steps to Reproduce (for bugs)
Call `logger.CriticalIf` in a function which is tested.

## Context
logging

## Your Environment
master

**Comment by harshavardhana** [comment]
This was on purpose CriticalIf is not a replacement for panic() - logger functions are formatted output. So wherever it's being used it was considered okay to kill the whole server. 

Go doesn't provide a way for writing formatted logging cleanly by also leveraging panic() like awareness. If we use panic() it would clutter the console output with no control on the actual mechanism.

**Comment by aead** [comment]
@harshavardhana I don't want to change the overall console printing. If you either catch the `panic` in the HTTP handler and drop the call or use `runtime.Goexit()` it does not affect the console at all. This is just about the behavior of killing the entire server...
Meaning call `panic()` or `runtime.Goexit()` instead of the `os.Exit(1)` in `CriticalIf`

**Comment by harshavardhana** [comment]
runtime.GoExit() is better alternative here

**Comment by kannappanr** [comment]
So, replace os.Exit(1) with runtime.GoExit() in CriticalIf ?

**Comment by aead** [comment]
We can do so **if** we never call `logger.CriticalIf` from `main` go-routine - only in handler go-routines.
If I understand `logger` correct for startup we should use `Fatal`.
However we can never detect in a `recover` call that `CriticalIf` was called...

Alternative is to e.g. `panic(CriticalErr)` and add in HTTP top handler:
```
if err := recover(); err == CriticalErr {
     return
}
```
Later one allows use to detect `CriticalIf / panic` - this is useful for unit tests.

**Comment by harshavardhana** [comment]
We only call Fatal only in startup situations in any other situation it should be CriticalIf for unexpected situations. We can do panic and recover by having recover at top level handler approach as well.
