### ISSUE TITLE
Broken reference link to configuration guide in the error message

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#6069]
If Minio server is attempted to be started with invalid configuration information in Minio config.json file, it fails to start as expected with the following error message:
```
ERROR Unable to load the configuration file: scheme appears with empty host.
      > Please ensure a valid value in the configuration file, for more details refer https://docs.minio.io/docs/minio-server-configuration
      -guide.
```
When the provided link to the reference doc, `https://docs.minio.io/docs/minio-server-configuration`, is clicked, `"404: Page not found`  error is shown in the browser. 
That's because `-guide` shows up in the next line instead of being part of the link, `https://docs.minio.io/docs/minio-server-configuration-guide`
## Expected Behavior

The provided link to reference doc works when clicked.
## Current Behavior

404: Page not found
## Possible Solution

It looks like the error handling logic wraps the error message depending on the console/terminal window width size. We should never break the link.
## Steps to Reproduce (for bugs)

See description above

**Comment by harshavardhana** [comment]
> ERROR Unable to load the configuration file: scheme appears with empty host.
>       > Please ensure a valid value in the configuration file, for more details refer https://docs.minio.io/docs/minio-server-configuration
>       -guide.

The link here is not broken the issue here is the link is wrapped due to your terminal size.

**Comment by harshavardhana** [comment]
on my terminal it is 

```
$ minio server ~/test
ERROR Unable to load the configuration file: parse ://guest:guest@localhost:5672/: missing protocol scheme.
      > Please ensure a valid value in the configuration file, for more details refer https://docs.minio.io/docs/minio-server-configuration-guide.
```

**Comment by aead** [comment]
~@harshavardhana - I see a 404 page if following the link. So i think that's what @ebozduman means with broken...~
My fault, copied the final `.` too...

**Comment by ebozduman** [comment]
Yes @harshavardhana, it is because of the wrapping as also explained in the "Possible Solution" section above. But we still should not break the link into 2 when the terminal is not wide enough.

**Comment by harshavardhana** [comment]
> Yes @harshavardhana, it is because of the wrapping as also explained in the "Possible Solution" section above. But we still should not break the link into 2 when the terminal is not wide enough.

The problem is in logger implementation which is actively breaking the line at TerminalSize which shouldn't happen. 

The following change seems to fix the problem

```diff
diff --git a/cmd/logger/logger.go b/cmd/logger/logger.go
index 3b160322..0503d578 100644
--- a/cmd/logger/logger.go
+++ b/cmd/logger/logger.go
@@ -28,7 +28,6 @@ import (
        "time"
 
        c "github.com/minio/mc/pkg/console"
-       "golang.org/x/crypto/ssh/terminal"
 )
 
 // Disable disables all logging, false by default. (used for "go test")
@@ -433,14 +432,6 @@ var (
 func (f fatalMsg) pretty(msg string, args ...interface{}) {
        // Build the passed error message
        errMsg := fmt.Sprintf(msg, args...)
-       // Check terminal width
-       termWidth, _, err := terminal.GetSize(0)
-       if err != nil || termWidth < minimumWidth {
-               termWidth = minimumWidth
-       }
-       // Calculate available widht without the banner
-       width := termWidth - bannerWidth
-
        tagPrinted := false
 
        // Print the error message: the following code takes care
@@ -470,13 +461,8 @@ func (f fatalMsg) pretty(msg string, args ...interface{}) {
                        ansiRestoreAttributes()
                        ansiMoveRight(bannerWidth)
                        // Continue  error message printing
-                       if len(line) > width {
-                               fmt.Println(line[:width])
-                               line = line[width:]
-                       } else {
-                               fmt.Println(line)
-                               break
-                       }
+                       fmt.Println(line)
+                       break
                }
        }
 
```

**Comment by deekoder** [comment]
@vadmeste please can you see why it wraps like this. User clicks on the a href and its not the full url. @harshavardhana  has a proposal for you to consider for the fix in previous comment.

**Comment by harshavardhana** [comment]
> @vadmeste please can you see why it wraps like this. User clicks on the a href and its not the full url. @harshavardhana has a proposal for you to consider for the fix in previous comment.

@vadmeste were you able to look at the change I proposed. We need to fix this due to apparent problem s on smaller terminals our usability is lost.
