### ISSUE TITLE
Read-only Public URL's unfriendly (excess token)

### ISSUE THREAD

**Issue by kallisti5** [minio/minio#6070]
The public https URL's for read-only public / anonymous access are pretty unfriendly:

```
/minio/download/nightly/x86_64/thing.zip?token=%27%27
```

Without the %27%27 token the access doesn't work.  Since no token should be required for public read-only access shouldn't it work without ?token=XXXX ?

**Comment by harshavardhana** [comment]
This is not the public URL for Minio how did you generate it? are you trying to use the json-rpc API?

**Comment by kallisti5** [comment]
just downloaded a file publically (anonymous read-only) via the minio web client on 9000, then looked at the generated URL

**Comment by harshavardhana** [comment]
> just downloaded a file publically (anonymous read-only) via the minio web client on 9000, then looked at the generated URL

This is not correct @kallisti5 you shouldn't use the token in this manner. I am suspecting you have been looking browser network traffic.

**Comment by harshavardhana** [comment]
If you have set the bucket/prefix as publicly readable simply use 

http://endpoint:port/download/nightly/x86_64/thing.zip 

"/minio" is meant for minio browser requests only.

**Comment by kallisti5** [comment]
ah. Is that documented?

**Comment by kallisti5** [comment]
Er. getting access denied without using minio and that token.

https://cdn.haiku-os.org/download/nightly/x86_64/haiku-nightly-hrev52025-x86_64-anyboot.zip

vs 

https://cdn.haiku-os.org/minio/download/nightly/x86_64/haiku-nightly-hrev52025-x86_64-anyboot.zip?token=%27%27

vs

https://cdn.haiku-os.org/minio/download/nightly/x86_64/haiku-nightly-hrev52025-x86_64-anyboot.zip

**Comment by harshavardhana** [comment]
Did you use `mc policy download` to set the bucket policies? @kallisti5

**Comment by kallisti5** [comment]
Bucket Policy: * read only   from minio web client.

**Comment by kallisti5** [comment]
haha. whoops.

https://cdn.haiku-os.org/nightly/x86_64/haiku-nightly-hrev52025-x86_64-anyboot.zip  :-)

**Comment by harshavardhana** [comment]
> Bucket Policy: * read only from minio web client.

Try using mc https://github.com/minio/mc

**Comment by kallisti5** [comment]
The bucket is nightly. Thanks :-)
