### ISSUE TITLE
UnknownEndpoint: Inaccessible host: `screenshots.minio'

### ISSUE THREAD

**Issue by claudiodangelis** [minio/minio#6071]
I'm using Docker Compose to run two containers, minio and a node app, and I get an error when uploading an object from one container to the other.

## Expected Behavior

The object should be uploaded to the minio container.

## Current Behavior

The S3's `putObject` method fails and throws this error:

```
[AWS s3 undefined 0.208s 3 retries] putObject({ Body: <Buffer ... >,
  Bucket: 'screenshots',
  Key: 'screenshots/5b2d7bdac64df900109f4ed9-1529707815.png',
  ServerSideEncryption: 'AES256' })

UnknownEndpoint: Inaccessible host: `screenshots.minio'. This service may not be available in the `us-east-1' region.\n
    at Request.ENOTFOUND_ERROR (/app/node_modules/aws-sdk/lib/event_listeners.js:481:46)\n
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n
    at ClientRequest.error (/app/node_modules/aws-sdk/lib/event_listeners.js:320:22)\n
    at ClientRequest.<anonymous> (/app/node_modules/aws-sdk/lib/http/node.js:89:19)\n
    at emitOne (events.js:96:13)\n
    at ClientRequest.emit (events.js:189:7)\n
    at Socket.socketErrorListener (_http_client.js:358:9)\n
    at emitOne (events.js:96:13)
```

Note: `minio` is the name of the container, and I can successfully run `curl minio:9000` from the node app container.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm using the `aws-sdk` node library, this is my S3 client configuration:

```js
Service {
  config: 
   Config {
     credentials: 
      { accessKeyId: 'xxxxxxx',
        secretAccessKey: 'yyyyyyyyyyyy' },
     credentialProvider: CredentialProviderChain { providers: [Object] },
     region: 'us-east-1',
     logger: { log: [Function: log] },
     apiVersions: {},
     apiVersion: null,
     endpoint: 'http://minio:9000',
     httpOptions: { timeout: 120000 },
     maxRetries: undefined,
     maxRedirects: 10,
     paramValidation: true,
     sslEnabled: true,
     s3ForcePathStyle: false,
     s3BucketEndpoint: false,
     s3DisableBodySigning: true,
     computeChecksums: true,
     convertResponseTypes: true,
     correctClockSkew: false,
     customUserAgent: null,
     dynamoDbCrc32: true,
     systemClockOffset: 0,
     signatureVersion: null,
     signatureCache: true,
     retryDelayOptions: {},
     useAccelerateEndpoint: false },
  endpoint: 
   Endpoint {
     protocol: 'http:',
     host: 'minio:9000',
     port: 9000,
     hostname: 'minio',
     pathname: '/',
     path: '/',
     href: 'http://minio:9000/' },
  _clientId: 1 }
```

Everything works fine if the node app is run on the host and the minio container's 9000 port is mapped to a host port.

## Your Environment

* Version used (`minio version`): latest version as per `docker pull minio/minio`
* Server type and version: AWS instance
* Operating System and version (`uname -a`): `4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Thank you,
Claudio

_(edit: whitespace)_

**Comment by harshavardhana** [comment]
> Note: minio is the name of the container, and I can successfully run curl minio:9000 from the node app container.

You should enable ForcePathStyle @claudiodangelis

**Comment by claudiodangelis** [comment]
Ehy @harshavardhana, setting `s3ForcePathStyle: true` indeed fixed the issue. Thanks for the incredibly fast response. I'm closing this issue.
