### ISSUE TITLE
[gateway/oss] while there hasn't the `listBuckets` permission,  the `oss` gateway cannot  do anything.

### ISSUE THREAD

**Issue by TheNorthMemory** [minio/minio#6075]
## Current Behavior

the console prompt the following msg:

```
API: SYSTEM()
Time: 08:52:39 UTC 06/24/2018
Error: oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage=You are forbidden to list buckets., RequestId=5B2F5BB73A49711B7F837F83
       1: cmd/gateway/oss/gateway-oss.go:393:oss.(*ossObjects).ListBuckets()
       2: cmd/healthcheck-handler.go:55:cmd.LivenessCheckHandler()
       3: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

## Possible Solution

can someone implement an environment setting eg, `MINIO_STICK_TO_BUCKET` to skip `listBuckets` operation, just go to `listObject` directly.

## Your Environment
* image from hub.docker minio/minio:latest
*
* Version: 2018-06-22T23:48:46Z
* Release-Tag: RELEASE.2018-06-22T23-48-46Z
* Commit-ID: 6005dbf01f31a2bffbc3b16d8a8d29885073b2b5
* `Linux 47cce82220fd 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux`

**Comment by harshavardhana** [comment]
Why is ListBuckets() action disabled? @TheNorthMemory

**Comment by TheNorthMemory** [comment]
@harshavardhana for some scenarios, for eg, the storage were support for the multi tenancy, each of them cannot list another buckets.

**Comment by deekoder** [comment]
@TheNorthMemory so if you enable ListBuckets() everything works normally?

**Comment by TheNorthMemory** [comment]
@deekoder yes, I've tested , while the permission as `AliyunOSSFullAccess`, the gateway  working well, such as the `putBucket`, `deleteBucket`, `listBuckets`, `listObjects`, `deleteObject`, `putObject` operations are working great.

it's my cli command:

`docker run --rm -p9000:9000 --name oss -e "MINIO_ACCESS_KEY=$OSS_AccessKeyID" -e "MINIO_SECRET_KEY=$OSS_AccessKeySecret" minio/minio gateway oss https://oss-cn-shanghai.aliyuncs.com`

**Comment by deekoder** [comment]
@TheNorthMemory  We do need ListBuckets() enabled to not have other unintended effects.  Perhaps you could prevent the clients from listing in some other way external to disabling ListBuckets()?

**Comment by TheNorthMemory** [comment]
@deekoder yep, indeed, here's a [tool which is about the oss policy genarator](https://github.com/aliyun/ram-policy-editor/). The policy rules were so clear so do I no reason to "reinvent the wheel".  I think this feature(limited on the special bucket) is not only for the oss gateway but also suitable for the aws, the Minio server also needs  i think.

**Comment by eco-minio** [comment]
@TheNorthMemory The intent is that you should run one gateway per tenant.  In this way, you can enable OSS policy per tenant at the provider level to disallow access to listBuckets for those tenants you don't wish to have access.

**Comment by TheNorthMemory** [comment]
@eco-minio oh, i see and get you point too. The minio server was designed as one AK per tenant. One instance server may need full access on the special bucket. The OSS gateway also need the `listBucket` access limited. I'll try to adjust the aliyun ram to fit for the restricted. Thanks all for the feedbacks. comment the point here for other developers.
