### ISSUE TITLE
Not returning NoSuchBucket when deleting object in non-existent bucket

### ISSUE THREAD

**Issue by tomyl** [minio/minio#6077]
## Expected Behavior

If I try to delete an object in an non-existent bucket against AWS S3 I get:

```bash
$ s3cmd del s3://testbucketxxsdfdsf13ewfewe/newfilessfd
ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist
$
```

## Current Behavior

Same thing against Minio (play.minio.io:9000) doesn't result in any error:

```bash
$ s3cmd del s3://testbucketxxsdfdsf13ewfewe/newfilessfd
delete: 's3://testbucketxxsdfdsf13ewfewe/newfilessfd'
$
```

Verified this behavior with s3cmd and boto3. Interestingly, mc reports error though:

```bash
$ mc rm play/testbucketxxsdfdsf13ewfewe/newfilessfd
mc: <ERROR> Failed to remove `play/testbucketxxsdfdsf13ewfewe/newfilessfd`. The specified bucket does not exist
$
```

**Comment by harshavardhana** [comment]
It would be helpful if you can provide s3cmd --debug output @tomyl

**Comment by tomyl** [comment]
@harshavardhana Of course, here you go:
[delete_object_badbucket_aws.txt](https://github.com/minio/minio/files/2132342/delete_object_badbucket_aws.txt)
[delete_object_badbucket_minio.txt](https://github.com/minio/minio/files/2132344/delete_object_badbucket_minio.txt)

**Comment by tomyl** [comment]
Confirmed that fix works. Thank you!
