### ISSUE TITLE
Can't query parquet file in Minio with Apache Drill

### ISSUE THREAD

**Issue by myaspm** [minio/minio#6080]
## Expected Behavior
Successfuly query a parquet file.

## Current Behavior
When i'm trying to query a parquet file in Drill i get an error saying:

```
Error: SYSTEM ERROR: AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: Forbidden
```

Minio logs give the same error as :

```
API: HeadObject(bucket=fadata, object=RTM_TAS_ALR_34501_2016010100.parquet/.drill.parquet_metadata)
Time: 11:48:10 UTC 06/25/2018
RemoteHost: 172.17.0.1:58746
UserAgent: aws-sdk-java/1.7.4 Linux/4.4.0-128-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.151-b12/1.8.0_151
Error: file access denied
       1: cmd/fs-v1-helpers.go:242:cmd.fsStatFile()
       2: cmd/fs-v1.go:676:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:705:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:710:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:84:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:260:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```
Tried both Docker minio and FreeNas plugin minio. I can connect to minio from Drill and see the files. Can query CSV or Json files with no problem. Parquet file permissions are set to 777 by chmod and the policy is set to 'public' by mc client. I searched extensively but couldn't find any solution so asking here as a last resort.

## Steps to Reproduce (for bugs)
1. Setup a minio server.
2. Set Drill connection configurations.
3. Create a s3 plugin in Drill.
4. Try to query a parquet file.

## Your Environment

* Version used (`minio version`): 2018-06-22T23:48:46Z
* Environment name and version (e.g. nginx 1.9.1): Docker version 17.09.0-ce, build afdb6d4
* Server type and version: Ubuntu 16.04
* Operating System and version (`uname -a`): Linux Ubuntu 16.04

**Comment by nitisht** [comment]
@myaspm how did you start Minio server?

**Comment by myaspm** [comment]
@nitisht :

```
docker run -v /data:/data -p 9000:9000 minio/minio server /data
```

Used the secret/access keys from console output for Drill configs.

and then for mc:

```
docker run -it --entrypoint=/bin/sh minio/mc
```

In mc docker console: 

```
mc config host add minio URL ACCESSKEY SECRETKEY
mc policy public minio/fadata
mc policy public minio/fadata/RTM_TAS_ALR_34501_2016010100.parquet
```

Edit: Uploaded the file by browser, created a bucket named fadata and uploaded the parquet file. Used the docker mount flag for manually chmod'ing the parquet file.

**Comment by nitisht** [comment]
do you mind setting up Minio with erasure code (https://docs.minio.io/docs/minio-erasure-code-quickstart-guide) and give it a try again. 

I think the problem you're facing is a known bug on standalone mode, we are working on a fix here: https://github.com/minio/minio/pull/5966

**Comment by myaspm** [comment]
It works if i use the erasure code setup but i don't understand what this exactly solves. And how to use this setup for FreeNas minio plugin?

**Comment by nitisht** [comment]
>  i don't understand what this exactly solves

Do you mean erasure code? 

> how to use this setup for FreeNas minio plugin?

This should help https://github.com/minio/cookbook/blob/master/docs/running-minio-in-freenas.md

**Comment by myaspm** [comment]
I mean what is the problem with the standalone version?

For the NAS setup yeah that helped i could work it out by starting from FreeNAS console. Just have another question if you dont mind:

How to give minio disks in /<jail_root>/Minio/etc/rc.conf ?

```
minio_disks="</path/to/your/dataset/inside/jail>"
```
I gave a list of comma seperated disks but it fails. If i start the jail from command line with disks given as space seperated arguments it

**Comment by harshavardhana** [comment]
This requires a fix in our code, FS mode has a behavior issue v/s erasure code we will fix it.
