### ISSUE TITLE
Minio reporting bucket as empty while delete operation is in progress

### ISSUE THREAD

**Issue by dmpriso** [minio/minio#6086]
## Expected Behavior
When a object delete operation is in progress, ```ListObjectsV2``` should still report at least the items which are not deleted.

## Current Behavior
While the delete operation is in progress, ```ListObjectsV2``` returns an empty object list. As soon as the delete operation finishes, ```ListObjectsV2``` returns the remaining objects in the bucket.

## Steps to Reproduce (for bugs)
1. Startup minio
2. Execute the following file. You will need AWSSDK S3 nuget package.
https://gist.github.com/dmpriso/ae8fc24b8f7779237428a5cfc08866b8
3. You will see that ```wrongCount != 0``` in line 136

Note that I also tried to create a separate S3 client instance in order to rule out client-side state issues.

## Context
Still investigating.

## Your Environment
* Version: 2018-06-09T03:43:35Z
* Operating System and version (`uname -a`): Windows 10 test machine

**Comment by Praveenrajmani** [comment]
@dmpriso Sorry for the delayed response. The bucket/object will be locked during the process. So it is intentional to not allow access while an object is under action.

**Comment by nitisht** [comment]
closing as working as intended @dmpriso feel free to reopen if there are further problems.
