### ISSUE TITLE
Can't read multiple files in a minio bucket subfolder with spark

### ISSUE THREAD

**Issue by Ftagn92** [minio/minio#6087]
Hello,

I'm trying to read multiple avro files stored in a subfolder of my bucket on a local minio container 

## Expected Behavior
May be i do it wrong, but i'm trying to populate a dataframe with the content of some avro files

It works flawlessly with the instruction : 

`DF_RANDOM = spark.read.format("com.databricks.spark.avro").load("s3a://datalake/random-random_table+0+000000001*.avro")`

the result is OK :

    DF_RANDOM.show()
    +-----+-------------------+---+-------------+
    |index|                  A|  B|    timestamp|
    +-----+-------------------+---+-------------+
    |   12| 0.5680445610939323|  1|1530017325000|
    |   13|  0.925596638292661|  5|1530017325000|
    |   14|0.07103605819788694|  4|1530017325000|
    |   15|0.08712929970154071|  7|1530017325000|
    +-----+-------------------+---+-------------+

When my avro files are in the root folder of my bucket it's OK

## Current Behavior

I'm trying to do the same with the avro files contained in a subfolder : 

`DF_RANDOM = spark.read.format("com.databricks.spark.avro").load("s3a://datalake/random/random-random_table+0+000000001*.avro")`

An error occurs :

`    Py4JJavaError: An error occurred while calling o111.load. : java.nio.file.AccessDeniedException: s3a://datalake/random: getFileStatus on s3a://datalake/random: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null), S3 Extended Request ID: null`

Spark seemes to not access to the subfolders when i use wilcards (access to only one file works even in the subfolder

the problem doesn't appear on real AWS S3. I encounter this only with minio

Have you an idea ?

## Environment

* Version used (`RELEASE.2018-06-22T23-48-46Z`): minio/minio:latest dockerfile 
* Environment name and version (e.g. nginx 1.9.1): Ubuntu 16.04 LTS
* Spark 2.2.1 pyspark --packages com.databricks:spark-avro_2.11:4.0.0,org.apache.hadoop:hadoop-aws:2.8.3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 

* Operating System and version (`uname -a`): Linux ASUS-ROG 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Many thanks

**Comment by nitisht** [comment]
we just merged a fix @Ftagn92 can you try this using `minio/minio:edge` image once?

**Comment by Ftagn92** [comment]
I just finish to test the  :edge (2018-06-26T17:56:31Z)

It works now !!!

Note that the error i had on linux didn't appear on the MacOS of my coworker.

Thanks for your help

**Comment by nitisht** [comment]
great. so shall we close this issue?

**Comment by nitisht** [comment]
fixed by https://github.com/minio/minio/pull/5966

**Comment by Ftagn92** [comment]
Sure :)
