### ISSUE TITLE
Much ioload causing corrupt filesystem

### ISSUE THREAD

**Issue by verymilan** [minio/minio#6092]
I migrated the internal mediafolder of a Mastodon instance to a selfhosted Minio bucket.
The VM is under permanent high ioload (~400K/s, 99% IO).
After some time the ext4 filesystem corrupts reproducable.

I wonder if i could do anything but renting some bucket somewhere / using the internal SSD of the Mastodon server which will run out of space some day soon.. .

* Version used: `2018-06-22T23:48:46Z`
* Environment name and version: `nginx/1.10.3`
* Operating System and version: `4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Can you run fsck on your backend ?

**Comment by verymilan** [comment]
Hi, yes i can, however it turned back to normal, i assume minio scanned the bucket?
Is this a possible reason?

**Comment by harshavardhana** [comment]
> Hi, yes i can, however it turned back to normal, i assume minio scanned the bucket?
> Is this a possible reason?

yes, but we have changed the crawling to be done in a more optimal manner in the latest release. Feel free to test it out.

**Comment by verymilan** [comment]
Alright, will update minio soon, thank you. :+1: 

PS: it would do less confusion if minio ẃould comment on this in the log

**Comment by harshavardhana** [comment]
> Alright, will update minio soon, thank you.

Checking back to see if this is still an issue for you, should we close this issue?

**Comment by verymilan** [comment]
I just had to realize that minio also corrupts the filesystem without the scanning process.

```
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2): ext4_validate_inode_bitmap:134: comm minio: Corrupt inode bitmap - block_group = 6513, inode_bitmap = 213385233
[Sat Jul  7 18:40:41 2018] Aborting journal on device sda2-8.
[Sat Jul  7 18:40:41 2018] EXT4-fs (sda2): Remounting filesystem read-only
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2): ext4_journal_check_start:56: Detected aborted journal
[Sat Jul  7 18:40:41 2018] EXT4-fs (sda2): Remounting filesystem read-only
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in ext4_reserve_inode_write:5448: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in ext4_reserve_inode_write:5448: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in ext4_reserve_inode_write:5448: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in __ext4_new_inode:1133: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in ext4_reserve_inode_write:5448: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in __ext4_new_inode:1133: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in ext4_evict_inode:243: Journal has aborted
[Sat Jul  7 18:40:41 2018] EXT4-fs error (device sda2) in ext4_evict_inode:243: Journal has aborted
```

The only thing i can see from minio in the syslog is that it complains about broken pipes from time to time but this happens like all day.

Edit: weird i was sure i already updated minio but i get `Release-Tag: RELEASE.2018-06-22T23-48-46Z` - i've updated now successfully however this is not a scanning related issue anymore, the ioload is totally fine when this happens.

**Comment by harshavardhana** [comment]
Well Minio cannot corrupt your backend disk in anyway. Your disk has perhaps bad sectors you should run fsck to fix these issues or contact the disk vendor for possible replacement.

Additionally with the new release, we also made improvements to detect if the export path used for Minio is a direct disk mount so we not crawl the filesystem. 

We do crawl if the export path is a sub directory of a mount such as /export/subdir

**Comment by verymilan** [comment]
> Well Minio cannot corrupt your backend disk in anyway.

hmm okey this does not make my troubleshooting easier... :/

> Your disk has perhaps bad sectors you should run fsck to fix these issues or contact the disk vendor for possible replacement.

It is actually a kvm and from the time i got minio on it, i had to recover the filesystem multible times with fsck. I sometimes run fsck once again to ensure everything went well and it never complained about bad sectors.

I think my export path is a sub directory, it is in /var/lib and no additional drive, however with the new release minio seems to cause much less load on rescan which usually happens after this kind of a crash.

**Comment by harshavardhana** [comment]
The reason this cannot happen is because Minio in not doing ext4 journal and inode bitmap management. We simply read and write like any application would do on the path. Now if it does get corrupted by Minio by not any other process is suspicious. Are you sure where ever this kvm resides the underlying storage is resilient ? Please do share how to set this up locally as well along with versions of each component in question we can try reproducing it.

**Comment by verymilan** [comment]
> Now if it does get corrupted by Minio by not any other process is suspicious. 

At least how far i am able to understand the `.. ext4_validate_inode_bitmap:134: comm minio: ..` part of the error.. .

> Are you sure where ever this kvm resides the underlying storage is resilient ?

Well this vm is a rented one, i did not deploy it myself but i can ping their support about it - however it would be an interesting accident since this trouble appears from the day i deployed this specific minio bucket. I however have two other minio instances but only for backups, mainly - this one is dedicated to a Mastodon instances media. 

> Please do share how to set this up locally as well along with versions of each component in question we can try reproducing it.

If i am able to list all the needed components.. .
* `4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1`
* `nginx/1.10.3`
* minio is now at `2018-06-29T02:11:29Z`

...actually i am not sure what else to list? or did you mean like how the kvm itself was deployed?

I'd like to add, i sometimes have stuff like this one when i check dmesg:
```
[Sun Jul  8 00:13:09 2018] INFO: task python2.7:14744 blocked for more than 120 seconds.
[Sun Jul  8 00:13:09 2018]       Not tainted 4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[Sun Jul  8 00:13:09 2018] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```
Followed by a call trace (not about minio itself and nothing like that in the time range of recent corrupt) ... and followed by multible `sh ($id): drop_caches: 3`

```
sd 0:0:0:0: [sda] tag#1 abort
sd 0:0:0:0: [sda] tag#3 abort
```
and `hrtimer: interrupt took 25622164 ns`

But again, except drop_caches a few minutes before recent interrupt, there was nothing like this in the timespan of the recent corrupt.

**Comment by harshavardhana** [comment]
> [Sun Jul  8 00:13:09 2018] INFO: task python2.7:14744 blocked for more than 120 seconds.
> [Sun Jul  8 00:13:09 2018]       Not tainted 4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
> [Sun Jul  8 00:13:09 2018] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.

These things indicate that disk is slow or hung due to previous operation.

> sd 0:0:0:0: [sda] tag#1 abort
> sd 0:0:0:0: [sda] tag#3 abort

This can happen when scsi controller is rejecting or not able to respond in stipulated timeout.

> At least how far i am able to understand the .. ext4_validate_inode_bitmap:134: comm minio: .. part of the error.. .

comm minio means the process that would see this error while the process was trying to write data to that location, it has nothing to do with Minio doing anything special to corrupt the disk.

From what I can see you definitely need to contact the support since it would happen with any application since this server Minio is the most active I/O consumer it is simply incidental that it's visible.

**Comment by verymilan** [comment]
Alright, thank you for reviewing, i just sent them an email.

**Comment by harshavardhana** [comment]
> Alright, thank you for reviewing, i just sent them an email.

Closing this as not an issue with Minio, feel free to re-open if you still think this is a Minio problem.
