### ISSUE TITLE
Insufficient permissions to access path /root/.minio/certs

### ISSUE THREAD

**Issue by v1r** [minio/minio#6095]
Hi there!

I just tried Minio in Mac using Docker and I encountered a permission error when running the following commnad:

`
docker run -p 9000:9000 --name minio1 -v /Volumes/data:/data -v /Volumes/config:/root/.minio minio/minio server /data
`
Error: 
```
ERROR Unable to initialize configuration files: Insufficient permissions to access path, `/root/.minio/certs`.
      > Please ensure the specified path can be accessed.
```

**Docker version:**
Docker version 18.03.1-ce, build 9ee9f40

Any idea what could be the problem?

**Comment by harshavardhana** [comment]
can you avoid using `-u root` ?

**Comment by v1r** [comment]
Hi @harshavardhana !

My bad, I got the error using the following command: 

```
docker run -p 9000:9000 --name minio1 -v /Volumes/data:/data -v /Volumes/config:/root/.minio minio/minio server /data
```
I just copied here the wrong one, starting it using root does not change anything.

**Comment by v1r** [comment]
I think it was an issue with right access for current user on /Volumes. It worked when I changed volumes mount directory to Users/me/.
