### ISSUE TITLE
Brute force auth rate limiting?

### ISSUE THREAD

**Issue by kallisti5** [minio/minio#6098]
Since Minio only leverages a single key  + secret (#5305 ), does it have any auth rate limiting built in?

I know the long random key + long random secret key should be hard to crack, but with only one key + secret, a single minio server could be completely compromised and access to every bucket gained with one successful brute-force attack.

**Comment by harshavardhana** [comment]
Access key and secret key is never transmitted over network.  It is similar in security as AWS Signature V4. 

We are also bringing temporary credentials support as well.

Can you explain how you would crack signature V4 ?

**Comment by kallisti5** [comment]
ok. that covers the concerns I heard.  Thanks!
