### ISSUE TITLE
Would like to have the ability to change the default port

### ISSUE THREAD

**Issue by simongrigorian** [minio/minio#6100]
Is it possible to change the default port from 9000 to, lets say 445? We have services that depend on 9000, and can't be changed.

**Comment by harshavardhana** [comment]
Just run with `minio server --address ":desired-port"` on command line.

**Comment by simongrigorian** [comment]
Hmm.. okay I figured it out, I just did 445:9000. Sorry, I need some coffee for the brain to work in the morning..
