### ISSUE TITLE
fPutObject inconstant parameter requirements

### ISSUE THREAD

**Issue by sergeAMD** [minio/minio#6102]
On windows if I run fPutObject with metaData= {'ContentType' : 'application/octet-stream'}; I get:
(node:17248) UnhandledPromiseRejectionWarning: TypeError: contentType should be of type "string"
    at Client.fPutObject (<PATH>\node_modules\minio\dist\main\minio.js:880:13)
    at Client.<anonymous> (<PATH>\data_storage\node_modules\minio\dist\main\helpers.js:28:51)

When I change that to metaData =  'application/octet-stream' It passes on Windows, but fails on Linux:
UnhandledPromiseRejectionWarning: TypeError: contentType should be of type "object".

## Expected Behavior
It should constantly require either a string, or a JavaScript object.

## Current Behavior
I get different failures on different systems

## Steps to Reproduce (for bugs)
Try to call fPutObject with metaData =  {'ContentType' : 'application/octet-stream'} or metaData = 'application/octet-stream'. And see which case fails, which passes.

## Context
It could be something I am doing wrong when starting the Minio server? Or something else about my environment?

## Your Environment

* Version used (`minio version`):
Version: 2018-06-07T19:10:07Z
Release-Tag: RELEASE.2018-06-07T19-10-07Z
Commit-ID: 94ec6f374e8b7e6d8d79a5248b4b3961ae438756

* Operating System and version (`uname -a`):
Windows 10 Enterprise / Ubuntu 16 LTS

**Comment by nitisht** [comment]
@sergeAMD which SDK you're using to send `fPutObject` requests to Minio server?

**Comment by sergeAMD** [comment]
@nitisht 

        "minio": {
            "version": "5.0.2",
            "resolved": "https://registry.npmjs.org/minio/-/minio-5.0.2.tgz",
            "integrity": "sha1-Wxi1RGSisoI4c5HivcpkL85qp8M=",
            "requires": {
                "async": "1.5.2",
                "block-stream2": "1.1.0",
                "concat-stream": "1.6.2",
                "es6-error": "2.1.1",
                "json-stream": "1.0.0",
                "lodash": "4.17.10",
                "mime-types": "2.1.18",
                "mkdirp": "0.5.1",
                "querystring": "0.2.0",
                "source-map-support": "0.4.18",
                "through2": "0.6.5",
                "uuid": "3.2.1",
                "xml": "1.0.1",
                "xml2js": "0.4.19"
            }
        },

Here is my minio dependency chain. I am using the javascript SDK on Node.JS

**Comment by sergeAMD** [comment]
Is that the info you were looking for @nitisht? Thanks.

**Comment by nitisht** [comment]
Thanks @sergeAMD , yes. we'll take a look

**Comment by sergeAMD** [comment]
Hi, any updates on this?
-Thanks.

**Comment by nitisht** [comment]
hey @sergeAMD - looks like you have two different versions of `minio-js` running, the one on windows is `5.0.2` while on Linux it is `6.0.0`. Can you update the minio-js library on your windows box and try again.

**Comment by nitisht** [comment]
the `6.0.0` release changes the fPutObject API https://github.com/minio/minio-js/compare/5.0.2...master

**Comment by sergeAMD** [comment]
Thank you @nitisht

**Comment by kannappanr** [comment]
@sergeAMD Is your issue resolved? If yes, can you please close the issue?
