### ISSUE TITLE
disk-tuning.sh run error

### ISSUE THREAD

**Issue by ibyte2011** [minio/minio#6103]
## Expected Behavior

run ok

## Current Behavior

-bash: echo: write error:Invalid argument at line 49

## Steps to Reproduce (for bugs)

1when use root .run [disk-tuning.sh](https://github.com/minio/minio/blob/master/docs/deployment/kernel-tuning/disk-tuning.sh)

## Your Environment

* Version used (`minio version`):2018.6.22
* Server type and version:S3
* Operating System and version (`uname -a`):Redhat 7.2

**Comment by harshavardhana** [comment]
> -bash: echo: write error:Invalid argument at line 49

This is expected on certain drivers which do not allow this value to be changed, we can certainly silence this error.
