### ISSUE TITLE
high availability structure

### ISSUE THREAD

**Issue by oghan** [minio/minio#6105]
## Current Behavior
Four servers and 2 disks per server
The scenario we apply is below,This structure can not create high availability
How can we solve this situation

./minio server http://10.10.10.1/d11 http://10.10.10.1/d12 http://10.10.10.2/d21 http://10.10.10.2/d22 http://10.10.10.3/d31 http://10.10.10.3/d32 http://10.10.10.4/d41 http://10.10.10.4/d42

**test.log uploading**				

SERVER		DISK1	DISK2	FILE	UPLOAD
10.10.10.1	UP	UP	test.log	success
10.10.10.2	UP	UP	test.log	success
10.10.10.3	UP	UP	test.log	success
10.10.10.4	DOWN	DOWN	NONE	NONE
				
**the file(test.log) is accessible**			

SERVER		DISK1	DISK2		
10.10.10.1	UP	UP		
10.10.10.2	UP	UP		
10.10.10.3	DOWN	DOWN		
10.10.10.4	DOWN	DOWN		
						
**the file(test.log) is not accessible**				

SERVER		  DISK1	       DISK2		
10.10.10.1	  UP	               UP		
10.10.10.2	  DOWN	       DOWN		
10.10.10.3	  DOWN	       DOWN		
10.10.10.4	  UP	               UP

## Your Environment

* Version used (`minio version`):
Version: 2018-06-09T03:43:35Z
Release-Tag: RELEASE.2018-06-09T03-43-35Z
* Operating System and version (`uname -a`):
   Linux 4.1.12-37.4.1.el6uek.x86_64

**Comment by nitisht** [comment]
@oghan you'll need to heal the setup after the server `10.10.10.4` comes up. [ref: https://github.com/minio/mc/blob/master/docs/minio-admin-complete-guide.md]

**Comment by harshavardhana** [comment]
> ./minio server http://10.10.10.1/d11 http://10.10.10.1/d12 http://10.10.10.2/d21 http://10.10.10.2/d22 http://10.10.10.3/d31 http://10.10.10.3/d32 http://10.10.10.4/d41 http://10.10.10.4/d42

You should simply make sure to disks spread out into neighboring nodes. your existing input is not optimal.

```
./minio server http://10.10.10.1/d11 http://10.10.10.2/d21 http://10.10.10.3/d31 http://10.10.10.4/d41 
http://10.10.10.1/d12 http://10.10.10.2/d22 http://10.10.10.3/d32 http://10.10.10.4/d42
```

**Comment by oghan** [comment]
@nitisht @harshavardhana thanks.
