### ISSUE TITLE
S3 metadata redirection

### ISSUE THREAD

**Issue by kallisti5** [minio/minio#6115]
Amazon S3 allows for x-amz-website-redirect-location to redirect to another location in a bucket (or on a remote server)

This behavior is *extremely* handy since s3 doesn't natively support symlinks.
Our use case is redirecting a "current" directory to another directory within the same bucket.

Example:
```
import boto
import boto.s3.connection

key = "AKEY"
secret = "ASECRET

conn = boto.connect_s3(
	aws_access_key_id = key,
	aws_secret_access_key = secret,
	host = "minio_server",
	port = 443,
	is_secure = True,
	calling_format = boto.s3.connection.OrdinaryCallingFormat(),
)

bucket = conn.get_bucket("haiku-repo")
key = bucket.new_key("x86_64/current")
key.set_metadata('x-amz-website-redirect-location', 'x86_64/r1~alpha4_pm_hrev52058')
key.set_contents_from_string('')
```

While the empty file above gets the correct metadata with minio, it doesn't redirect.
```
$ mc stat haiku/haiku-repo/x86_64/current
Name      : current
Date      : 2018-07-03 08:42:53 CDT 
Size      : 0B     
ETag      : XXX 
Type      : file 
Metadata  :
  Content-Type                              : application/octet-stream 
  X-Amz-Meta-X-Amz-Website-Redirect-Location: x86_64/r1~alpha4_pm_hrev52058 
```

Having metadata redirection (even if limited to a single bucket) would be *really* powerful within minio.

**Comment by kallisti5** [comment]
https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html:
> --website-redirect-location (string) If the bucket is configured as a website, redirects requests for this object to another object in the same bucket or to an external URL. Amazon S3 stores the value of this header in the object metadata.

**Comment by kannappanr** [comment]
@kallisti5 Thanks for filing this issue. I have spent some time to read about website redirection in AWS S3. 

AWS S3 does not just redirect an object in any bucket. The bucket has to be configured for `static website hosting` and the bucket has to be made public as explained here `https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html` .

For the redirection to work, the endpoint cannot be any s3 REST endpoint it has to be a website endpoint with some differences compared to a REST API endpoint as documented here 
`https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html#WebsiteRestEndpointDiff`

In the case of AWS S3, they can probably get away by differentiating based on the endpoint address. The bucket in AWS S3 can be accessed in two ways, one is via regular REST endpoint for regular s3 operations and the other is via its website endpoint for website hosting. currently, minio has only REST APIs implemented.

Additionally, I don't think S3 supports `symlink` support at a directory level as objects here have a flat namespace there is no directory like hierarchy in AWS S3.

**Comment by kannappanr** [comment]
@kallisti5 We are closing this issue as won't fix. please feel free to let us know if you have any questions.
