### ISSUE TITLE
serve s3 from rclone mount error

### ISSUE THREAD

**Issue by Rick7C2** [minio/minio#6118]
## Expected Behavior
The server should start.

## Current Behavior
ERROR Unable to initialize backend: seek /data/.minio.sys/format.json: illegal seek.

## Steps to Reproduce (for bugs)
1. run "docker run -p 9000:9000 --name minio1 -v /mnt/s3:/data -v /etc/docker/minio/config:/root/.minio minio/minio server /data" 

with "/mnt/s3" being an rclone mount

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
We cannot start @Rick7C2 `minio server` requires fcntl locking on the backend.

**Comment by harshavardhana** [comment]
Closing as unexpected usage since `rclone mount` doesn't implement fcntl locking required by Minio filesystem backend.
