### ISSUE TITLE
Migrate sarama/kafka dependent library to segmentio/kafka-go

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#6122]
** not using template on purpose **

- https://github.com/segmentio/kafka-go is a better and better designed/documented API with context support. 
- With stated motivations https://github.com/segmentio/kafka-go#motivations

**Comment by deekoder** [comment]
Moving to future milestone.

**Comment by deekoder** [comment]
Closing this item as something we will look into the future and will reopen when we get to our backlog in the next iteration.
