### ISSUE TITLE
IAM Role for S3 Gateway Access

### ISSUE THREAD

**Issue by dasousa** [minio/minio#6124]
## Expected Behavior
When running minio as an S3 gateway on an EC2 instance, the IAM role assigned to the instance should be used before requiring MINIO_ACCESS_KEY and MINIO_SECRET_KEY.

## Current Behavior
Minio responds with the error "Unable to start gateway: Credentials missing" when the EC2 instance has a role that allows access to S3, but the MINIO_ACCESS_KEY and MINIO_SECRET_KEY variables are not set.

## Steps to Reproduce (for bugs)
1. Launch an EC2 instance with a role that allows access to S3
2. Install minio on the EC2 instance
3. Launch minio with the command, "minio gateway s3" without setting MINIO_ACCESS_KEY or MINIO_SECRET_KEY

## Context
Use S3 for backups without requiring that all application servers in the enterprise have access to S3 on AWS.

## Your Environment
* Version used (`minio version`):  2018-06-29T02:11:29Z
* Server type and version: EC2 instance
* Operating System and version (`uname -a`): CentOS 7.5

**Comment by deekoder** [comment]
@dasousa  we will take a look. I don't think we look at IAM role in the minio server since its agnostic to where it's being run.

**Comment by harshavardhana** [comment]
@deekoder @dasousa we need to use IAM as one of the providers in minio-go which would automatically work.

**Comment by alshabib** [comment]
+1

This would be a great feature.

**Comment by nitisht** [comment]
@dasousa we added a fix https://github.com/minio/minio/pull/6422 for this, can you please try it out on our master. 

Closing the issue as fixed, feel free to reopen if you think something is missing,

**Comment by alshabib** [comment]
Just tested this out using the edge docker tag, it seems to not be working:

```
minio_minio.2.zppw7z8tb7jv@ip-10-253-152-129    | ERROR Unable to start gateway: Credentials missing.
minio_minio.2.zppw7z8tb7jv@ip-10-253-152-129    |       > Please set your credentials in the environment.
minio_minio.2.zppw7z8tb7jv@ip-10-253-152-129    |       HELP:
minio_minio.2.zppw7z8tb7jv@ip-10-253-152-129    |         In Gateway mode, access and secret keys should be specified via environment variables MINIO_ACCESS_KEY and MINIO_SECRET_KEY respectively.
```

Any specific configuration to make this work?

**Comment by harshavardhana** [comment]
We already updated the doc https://github.com/minio/minio/blob/master/docs/gateway/s3.md

**Comment by harshavardhana** [comment]
It is not possible to use IAM creds for Minio credentials because of how the authentication is structured. In this case Minio terminates the authentication and then relies on rotating creds to talk to backend. 

Such that your actual keys to the backend are never shared or saved in any ec2 instance.

**Comment by alshabib** [comment]
ahh I understand, even though I am using IAM creds I still need to specify MINIO_ACCESS_KEY and MINIO_SECRET_KEY for minio auth. 

This should be documented because it is unexpected and not mentioned in the documentation. Happy to do it if you agree that it is necessary.

**Comment by harshavardhana** [comment]
It is documented in the docs I just shared

**Comment by jjsp556** [comment]
I built and tested this fix, and it seems to work as intended. 

- Start EC2 Instance 1 using an IAM role allowing access to S3
- Start EC2 Instance 2 with no IAM role and no AWS credentials
- On EC2 Instance 1, run: MINIO_ACCESS_KEY=fakeaccess MINIO_SECRET_KEY=fakesecret ./minio gateway s3
- On EC2 Instance 2, run AWS_ACCESS_KEY_ID=fakeaccess AWS_SECRET_ACCESS_KEY=fakesecret aws s3 ls --endpoint-url=http://ec2_instance_1:9000
- The aws command on EC2 Instance 2 will return a list of S3 buckets
