### ISSUE TITLE
[feature]: minio should be able to auto-generate TLS certificates 

### ISSUE THREAD

**Issue by aead** [minio/minio#6125]
/* Not using template on purpose */

This is a feature request for adding a CLI / config option to allow the minio server to automatically generate a TLS certificate if there is none. Further if there is one that server should check whether it is expired and if so it should renew it.

Needs decision:
 - How should the CLI / config option look like: `minio server --auto-tls` / `minio server --self-signed`
 - What should happen if there is an expired certificate - either only renew the certificate but keep the private key or completely regenerate the private/public key.
 - What should be part of the certificate (domain, validity, ...)  
 - Should the private key always be generated or also taken as an argument

## Context
Deployment, TLS - #6093

**Comment by ghost** [comment]
> How should the CLI / config option look like: ``minio server --auto-tls`` / ``minio server --self-signed``

I think the certificate generation could and likely should be done by default whenever **SSE** (Server Side Encryption) is enabled. I know it is currently enabled based on ``globalIsSSL bool`` which is ``true`` when the server finds it has the certificates... So I thought, maybe it is worth adding a flag like ``--enable-sse bool`` and once it is ``true`` (which could be true by default), the Minio server would generate the ``public.crt`` / ``private.key`` automatically in case if it does not find them. Then, having this flag (``--enable-sse``) set to ``true`` would mean the Minio server **must** be running in TLS mode, otherwise SSE is not functioning anyway (which resulted in https://github.com/minio/minio/issues/6093 )

> What should happen if there is an expired certificate - either only renew the certificate but keep the private key or completely regenerate the private/public key.

Since the certificate is going to be a self-signed and has no authority (No CA public key to share), I believe it does not make any sense to keep the ``private.key`` and it should be regenerated.

> Should the private key always be generated or also taken as an argument

For better security, I would say yes. Of course if the Minio server sees the ``private.key`` is already present, then no action, except that it should complain and refuse to start if it sees the ``private.key`` without the ``public.crt`` file. So either both public/private were given by the user or nothing (then Minio will automatically generate the certs)

> What should be part of the certificate (domain, validity, ...)

I think that at least it should have these SAN's in x509:

```
DNS.1 = hostname of where the Minio server is running (be it a container or not)
IP.1 = actual IP of the interface where Minio server is running (be it a container or not)
IP.2..N = I believe it should not container all the IP's since it could accidentally expose intranet IP's to the outside world in case if Minio is not running behind a reverse proxy which does TLS termination. Probably DNS.1 also should be configurable.
```

If the reverse proxy is talking to the Minio by the hostname, then it would expect it has a valid DNS SAN, otherwise it would expect it has the valid IP if it is talking by the IP. Otherwise it will throw ``remote error: tls: bad certificate``. Of course, we are having a self-signed certificate, so maybe with ``insecureSkipVerify = true`` it will not care whether the certificate has the valid SAN's or not? I haven't been checking this further.

**Upd: A thought**

I am wondering, would it worth if it could also generate a fake ``ca.crt`` / ``ca.key`` , having the ``public.crt`` signed by it? Because then, one could use the ``ca.crt`` file in order to let reverse proxy trust the certificate without the need of skipping the secure verification. But probably this is pretty uncommon use-case and does not worth bothering with that this far?

**A thought 2**

I am thinking how far this could go in terms of the certificate parameters, should it be RSA or ECDSA key? Should we let a user specify the key size, the EC curve, the certificate signature (SHA1 / SHA256). The default should be the best practice of course.

**Comment by aead** [comment]
> I think the certificate generation could and likely should be done by default whenever SSE (Server Side Encryption) is enabled. I know it is currently enabled based on globalIsSSL bool which is true when the server finds it has the certificates... So I thought, maybe it is worth adding a flag like --enable-sse bool and once it is true (which could be true by default), the Minio server would generate the public.crt / private.key automatically in case if it does not find them. Then, having this flag (--enable-sse) set to true would mean the Minio server must be running in TLS mode, otherwise SSE is not functioning anyway (which resulted in #6093 )

Let me clarify this. SSE-C is not a feature which must be enabled/disabled. It is always available, but S3 specifies (for good reason) that SSE-C requests must be made over TLS. So in theory you could have two clients, one tries SSE-C over TLS (which succeeds) and one tries SSE-C over plain HTTP (which should fail). So the correct approach is not:
 - I want to use SSE-C, so enable it (and as consequence the minio server somehow magically generates a TLS cert)

but should be:
- I want to use SSE-C so I specify how the server should enable TLS.

> Since the certificate is going to be a self-signed and has no authority (No CA public key to share), I believe it does not make any sense to keep the private.key and it should be regenerated.

It's not that simple. For example lets assume we allow the user to specify the private key (and depending on it the server can reconstruct the public key and generate the cert) what should happen if the cert expires:
 - Should the server renew the cert but keep the private key? That may causes the server to overrite
   the user-provided key
 - Or should the server simply regenerate the entire private key/ cert. But if the user can specify the private key than the user can pin the private key and so circumvent the CA verification without a trust issue...

>I am wondering, would it worth if it could also generate a fake ca.crt / ca.key , having the public.crt signed by it? Because then, one could use the ca.crt file in order to let reverse proxy trust the certificate without the need of skipping the secure verification. But probably this is pretty uncommon use-case and does not worth bothering with that this far?

This works quite well as long as the minio server and the other service(s) are running on the same machine. But as soon as they are running on different machines and you would get trust errors again...
So users have to understand that this approach works only in specific scenarios...

>I am thinking how far this could go in terms of the certificate parameters, should it be RSA or ECDSA key? Should we let a user specify the key size, the EC curve, the certificate signature (SHA1 / SHA256). The default should be the best practice of course.

I don't think that should be configurable. Such options are usually used to downgrade security... With every release we can follow the best option available...

**Comment by ghost** [comment]
@aead makes sense, I agree on that SSE must be enabled by default and the users must have the way to specify how the server should enable TLS.

> what should happen if the cert expires:
>
>  - Should the server renew the cert but keep the private key? That may causes the server to overrite
>    the user-provided key
>  - Or should the server simply regenerate the entire private key/ cert. But if the user can specify the private key than the user can pin the private key and so circumvent the CA verification without a trust issue...

About the ``private.key``, please see I above, I actually [specified](https://github.com/minio/minio/issues/6125#issuecomment-402800358) how Minio server could act depending whether it sees the ``private.key`` already present or not. This would probably be the answer.
WDYT?

**Comment by aead** [comment]
@arno01 Actually I meant something slightly different (whether users should be able to specify the private key as CLI arg / ENV). However, I don't think this is a good idea, so your proposal is probably a good solution. So either user specifies private key + cert file or the server generates both. No hybrid solutions...

**Comment by ghost** [comment]
Yes, let's keep it simple. Leave PKI management to the administrator. :-)

This is only to cover "minio has basic TLS out-of-a-box" with the primary use-case - is letting Minio work behind a reverse proxy in the trusted backend network.
As this use-case is highly common and there are very few applications which require TLS for unveiling their full potential. I actually know just Minio that requires TLS (for the SSE to work), hence it needs to spew out the certificate ;-)

**Comment by kallisti5** [comment]
Traefik has built-in ACME certificate renewal via lets-encrypt (we're using it as a front-end for our Minio install).  May want to look at what they did since Traefik is also written in go.

As long as SSL is optional in minio, +1

**Comment by aead** [comment]
The current proposal for an automatic TLS feature is the following:
- There will be CLI flag `--auto-tls dns-name-1,dns-name-2,ip-1,dns-name-3` which accepts a list of comma-separated values - each one is a SAN; either a domain name or an IP address.
- If there is no private key (`private.key`) the server generates a new private key. If the `MINIO_CERT_PASSWD` is present the private key will be encrypted using that password before written to the `private.key` file.
 - The certificate will be **always** regenerated. The certificate's org. unit will be the `user@host` of the machine and it's SANs will be the values passed to `--auto-tls`.
- For now the certificate won't have a CA root. It's just a plain certificate without any trust.
- The minio server will print the certificate hash as well as the HPKP fingerprint of the private key on startup.

**Comment by ghost** [comment]
@aead the proposal looks good. I only had a single concern over the certificate's org. unit value:

> The certificate's org. unit will be the user@host of the machine

Initially, I thought about that as information leak, but quickly realized then that this setup should never be used without a reverse proxy in front of it.

Additionally, this would probably be "a good lift" when debugging multiple backends. (In case if internal DNS borked, etc..).

**Comment by till** [comment]
@aead Saw you started working on this, is there a way to test this?

**Comment by harshavardhana** [comment]
Since we rely on orchestrator to do this for use in minio-operator - closing this as not an issue for MinIO.

**Comment by ghost** [comment]
> Since we rely on orchestrator to do this for use in minio-operator - closing this as not an issue for MinIO

Sad... This means that people won't get SSE-C encryption working out of a box unless they deploy Minio using minio-operator in Kubernetes or unless they generate & maintain the x509 certs for the Minio server by their own means (e.g. https://github.com/minio/minio/issues/6093#issuecomment-401563381 ) in case they do not deploy Minio in Kubernetes.

**Comment by harshavardhana** [comment]
Use k8s or automate this yourself. MinIO can do certain things,  but it can't do everything under the sun.

For things that need to be orchestrator related should be outside. I am closing further discussion on this topic.

**Comment by harshavardhana** [comment]
There is a renewed interest around this topic, lets bring this back into discussion again.

**Comment by harshavardhana** [comment]
With the advent of `--config config.yaml`, this may now be simpler to do automatically.

**Comment by AndreC10002** [comment]
I'd like to suggest taking advantage of certbot (Let's Encrypt) to create / renew trusted instead of self signed certificates.

**Comment by harshavardhana** [comment]
> I'd like to suggest taking advantage of certbot (Let's Encrypt) to create / renew trusted instead of self signed certificates.

certbot requires internet access or some form of complicated DNS settings to work. MinIO is not meant for that its meant for LBs to do this.

**Comment by supriyo-biswas** [comment]
It may be easier to implement https://github.com/caddyserver/certmagic instead; it would allow people to remove yet another component like nginx/haproxy for simpler setups.

**Comment by harshavardhana** [comment]
> It may be easier to implement https://github.com/caddyserver/certmagic instead; it would allow people to remove yet another component like nginx/haproxy for simpler setups.

For distributed setup it is quite challenging to use certmagic, its designed for single node.

**Comment by supriyo-biswas** [comment]
> For distributed setup it is quite challenging to use certmagic, its designed for single node.

Certmagic does have a pluggable storage implementation for this purpose, or it may be sufficient to have the first node of the distributed setup perform this task.

Although, if this has already been deemed low priority or outside current plans, I respect that decision and don't wish to belabor the point.

**Comment by harshavardhana** [comment]
> Certmagic does have a pluggable storage implementation for this purpose, or it may be sufficient to have the first node of the distributed setup perform this task.

That won't work; it requires a distributed setup. For that, you need certificates. Otherwise, you are making a plain-text connection and sending certificates, which is worse than not having them.

It is not a relatively simple task.

**Comment by harshavardhana** [comment]
This is done already as part of our miniohq/eos fork using https://github.com/aead/mtls
