### ISSUE TITLE
Error: No bucket policy found for bucket on Google cloud storage

### ISSUE THREAD

**Issue by blackholegalaxy** [minio/minio#6129]
Using minio as GCS gateway, the error occurs:
> Error: No bucket policy found for bucket

Minio version: `minio/minio:RELEASE.2018-06-29T02-11-29Z`

I start the docker with `gateway gcs my-project`

The credentials are correct and set at project level, as storage admin.

My only bucket on GCS, within `my-project` is empty and doesn't contain any object.

**Comment by harshavardhana** [comment]
Fixed in #6104
