### ISSUE TITLE
Minio TLS Docs

### ISSUE THREAD

**Issue by Colhodm** [minio/minio#6132]
The commands provided in the Minio TLS Docs under option #3 are not complete/clear 
## Expected Behavior

Will provide improved docs PR soon.

## Steps to Reproduce (for bugs)
Try and use ONLY the docs to support TLS.
## Context

Trying to use HTTPS with Minio

**Comment by aead** [comment]
@Colhodm Can you specify which part of `3. Generate self-signed certificates` does not work / is not clear?

**Comment by Colhodm** [comment]
Hey Andreas,
If you do something like this:
go run generate_cert.go -ca --host "10.10.0.3"
openssl ecparam -genkey -name prime256v1 | openssl ec -out private.key
openssl genrsa -out private.key 2048
openssl rsa -in private-pkcs8-key.key -aes256  -out private.key
The last command will result in a private-pkcs-8-key.key not found error.

Also while at the top it says existing certificates can be put into the appropriate certificate directory for minio, it would/could be helpful to just provide a sample script which does this, because the way the docs are written it seems that once you run those commands under subsection 3 you are good to go, and do not need to do more, so could be helpful to add that?

**Comment by aead** [comment]
@Colhodm You are not supposed to run all these commands. For example pick either
 - `openssl ecparam -genkey -name prime256v1 | openssl ec -out private.key`
or
- `openssl genrsa -out private.key 2048`

The current doc provides different options for different scenarios...
Further we are going to give the minio server the capability to (auto) generate certificates (private key + public key/cert). So as long as there is no bug in the documentation I would recommend to follow the auto-tls path before providing a separate script...

**Comment by deekoder** [comment]
@Colhodm  can you send a PR cleaning up the doc so that it's not confusing for the user?

**Comment by aead** [comment]
> can you send a PR cleaning up the doc so that it's not confusing for the user?

Still don't see why docs should be confusing... It just contains different ways to generate a private key / certificate. Either using `generate_cert`, `openssl` or `GnuTLS`. If you follow any of this steps everything works fine AFAIK... Of course users should not use **all** options, but IMO that should be clear - or am I assuming too much?

**Comment by Colhodm** [comment]
@aead my bad I actually did not run the exact set of commands as I said earlier, I ran 
go run generate_cert.go -ca --host "10.10.0.3"
openssl genrsa -out private.key 2048
openssl rsa -in private-pkcs8-key.key -aes256 -out private.key
which gave the error of No such file or directory:bss_file.c:406:fopen('private-pkcs8-key.key','r')
140735787312072:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:408:

I did not actually use both RSA and ECParam. I think that the above 3 commands should be correct, unless I'm still misunderstanding something?

If we are supporting auto-tls soon, then it may be unnecessary to update the docs, as that would provide a much easier solution for the user

**Comment by aead** [comment]
@Colhodm 
Still I don't think this is correct. You should only run **one** of the following commands:
- `go run generate_cert.go -ca --host "10.10.0.3"`
- 1. `openssl genrsa -out private.key 2048`
  2. `openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=<domain.com>"`

- 1. `openssl genrsa -aes256 -out private.key 2048 -passout pass:PASSWORD`
  2. `openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=<domain.com>"`
  3.  `openssl rsa -in private.key -aes256 -passout pass:PASSWORD -out private.key`
- ....

Further notice that you have to specify the correct files. Eg. for
`openssl rsa -in private-pkcs8-key.key -aes256 -passout pass:PASSWORD -out private.key` you have to make sure that you provide the correct PKCS-8 key file. So if your PKCS-8 private key file is `my-private.key` than the command must be `openssl rsa -in my-private.key -aes256 -passout pass:PASSWORD -out private.key` and will create a `private.key` file.

You cannot blindly run the commands, it depends on your setup e.g. whether you already have a private key - but in the wrong format a.s.o.

For example what should always work (regardless of your setup) is: Run either:
 - `openssl ecparam -genkey -name prime256v1 | openssl ec -out private.key`
or 
 - `openssl genrsa -out private.key 2048`

and than: `openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=<domain.com>"`
Both, the `private.key` and the `public.crt` must be put in your `config-dir` - by default at `$HOME/.minio/certs/`

**Comment by eco-minio** [comment]
Tested `go run generate_cert.go -ca --host "10.10.0.3"` on Mac High Sierra and Ubuntu 18.04, in both cases server would not start with https.  

$ go run generate_cert.go -ca --host "192.168.56.101"
2018/07/18 10:04:58 written cert.pem
2018/07/18 10:04:58 written key.pem
$ cp cert.pem key.pem ~/.minio/certs/
$ minio server /home/e/ssltest/data{1...8}
Status:         8 Online, 0 Offline. 
Endpoint:  **http**://192.168.56.101:9000  

$ rm ~/.minio/certs/*pem
$ cd ~/.minio/certs/ 
$ vim openssl.conf
$ openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout private.key -out public.crt -config openssl.conf
Generating a 2048 bit RSA private key
writing new private key to 'private.key'

$ ll -a
...
  253 Jul 18 10:11 openssl.conf
 1704 Jul 18 10:12 private.key
 1229 Jul 18 10:12 public.crt
...
$ minio server /home/e/ssltest/data{1...8}
Status:         8 Online, 0 Offline. 
Endpoint:  **https**://192.168.56.101:9000  https://10.0.2.15:9000  https://127.0.0.1:9000

**Comment by harshavardhana** [comment]
Is this still an issue @eco-minio @kannappanr ?

**Comment by eco-minio** [comment]
@harshavardhana I originally had issues using the go script to generate the certificates, it worked when I tested just now.  Also tested on Windows awhile back, it seems to be working from my side.

**Comment by harshavardhana** [comment]
> @harshavardhana I originally had issues using the go script to generate the certificates, it worked when I tested just now. Also tested on Windows awhile back, it seems to be working from my side.

Then we should close this issue @kannappanr

**Comment by kannappanr** [comment]
closing based on above comments
