### ISSUE TITLE
docker logs doesn't show any log records

### ISSUE THREAD

**Issue by advoretsky** [minio/minio#6138]
Can't find logs of the minio server (running in docker)

## Expected Behavior
`docker logs` shows records related to failed requests

## Current Behavior
no logs records by `docker logs`, only  general info about version, endpoint, how to run command line client etc.

## Possible Solution
make logs displayed out of the box

## Steps to Reproduce (for bugs)
```
docker run -p 9000:9000 minio/minio server /data
docker logs <container_id>
```

## Context
I'm getting some error from s3client and want to check it with the logs from minio. I can't see any logs so far. 

## Your Environment
 You are running an older version of Minio released 1 week ago
 Update: docker pull minio/minio:RELEASE.2018-07-10T01-42-11Z

**Comment by aead** [comment]
Which error is returned by the S3 client? The server does not log every error (esp. not regular S3 errors - like `bucket does not exist`). AFAIK the server log is not for debugging "expected" errors but for detecting server bugs and / or exceptional error conditions...

**Comment by advoretsky** [comment]
I'm getting `com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 3L137; S3 Extended Request ID: 3L137)`

> AFAIK the server log is not for debugging "expected" errors but for detecting server bugs and / or exceptional error conditions...

I don't agree. When I just change config in the system, trying to switch from S3 to minio, I can do it wrong (starting from typo and to confusing bucket with region). Server explanation of the error will help me greatly. Server could say "bucket eu-west-1 not found", so I understand I confused region with bucket.

In my practice mentioning the real cause of error response helps me a lot for solving things like
- Someone can't ssh to server I maintain (I see in log "user `xyz` is unknown" and understand I configured it be just `xy`)
- URL looking legitimate returns 404. It's 100% "expected" error,  I just need help of the nginx to figure out what I configured wrong.

BTW. Nginx helps very much not just saying "requested file not found", but "file /var/www/html/foo.html" not found. I mean message https://github.com/minio/minio/search?q=%22The+specified+bucket+does+not+exist%22&unscoped_q=%22The+specified+bucket+does+not+exist%22 could be more specific.

**Comment by kannappanr** [comment]
@advoretsky We do send an error response based on S3 API as provided here https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

I am not sure which client SDK or tool you are using, but minio server does send an error response in XML format. There is a field in there which specifies what resource in use. In your case you should see the bucket name displayed there.

Here is a sample XML response that will be sent by the server to the client.
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Resource>/someinvalidbucket/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

On the server side, we do have an option where if you set the environment variable `MINIO_HTTP_TRACE` and start the server, it would log all the `HTTP` requests made to the server. You can also see the response that will be sent to the client.

**Comment by advoretsky** [comment]
Thank you. `MINIO_HTTP_TRACE` helped – bucket name was empty. I fixed it by
```
amazonS3ClientBuilder.setPathStyleAccessEnabled(true);
```

**Comment by kannappanr** [comment]
@advoretsky thanks for getting back to us. Glad that you were able to debug your issue. Will close the issue as answered. Please feel free to open an issue if you have any further questions.
