### ISSUE TITLE
Add go runtime metrics to prometheus metrics

### ISSUE THREAD

**Issue by gberche-orange** [minio/minio#6140]
It's great that the [readiness-probe](https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md#readiness-probe) checks the number of goroutines against the 1,000 threshold to report readiness.

It would be useful to be able to get instrumentation for these metrics in the form of additional prometheus metrics, in order to be able to more reliably diagnose capacity problems with a minio cluster.

## Expected Behavior

Prometheus metrics to include new metrics such as numGoRoutines, memoryStats.lastGCPauseTimeNS, memoryStats.numBytesAllocatedHeap

## Current Behavior

[Prometheus metrics](https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md#list-of-minio-metric-exposed) does not provide details about goruntime health or capacity.

## Possible Solution

Potential inspiration in cloudfoundry goruntime metrics such as https://github.com/cloudfoundry/dropsonde/blob/master/runtime_stats/runtime_stats.go#L32-L53

## Context

Troubleshooting minio capacity issues, where readiness probes flap between green and red.

**Comment by nitisht** [comment]
Prometheus exposes some runtime data by default https://play.minio.io:9000/minio/prometheus/metrics

will this not help?

**Comment by gberche-orange** [comment]
thanks @nitisht for the heads up!

 I had overlooked these metrics, along with `go_goroutines` (as they are not prefixed by minio nor did I discover them in the [metrics documentation](https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md#list-of-minio-metric-exposed)).

**Comment by gberche-orange** [comment]
Metrics discoverability would hopefully be addressed by https://github.com/orange-cloudfoundry/cookbook/pull/1

**Comment by nitisht** [comment]
> thanks @nitisht for the heads up!

:+1: 

> as they are not prefixed by minio nor did I discover them in the metrics documentation)

We did not document those metrics as they are standard built-in metrics that prometheus clients expose. Nevertheless, it would be better to mention about these metrics in our docs. I will make the changes.
