### ISSUE TITLE
Bitrot Detection Reads From Page Cache

### ISSUE THREAD

**Issue by keirafadams** [minio/minio#6143]
## Expected Behavior
Bitrot detection runs (healing or healing dry runs) should always read from the device, to ensure that persistently stored data is verified.

## Current Behavior
Instead, if an object has been read, it may be resident in the page cache and the checksum will be calculated based on the page cache data, not what is resident on the device. This opens a vulnerability in that an object may have suffered corruption, but it can be missed due to check summing against the page cache

## Possible Solution
When a file is read for bitrot detection, use O_DIRECT, or other methdology, to bypass the file system page cache. e.g. replace os,Open with os.OpenFile and use O_DIRECT for bitrot detection runs.

## Steps to Reproduce (for bugs)
Steps to Reproduce + Example
1. Start server, upload test data, large enough that a healing/bitrot check run should take a bit. I did 8GB with a slow SSD. Ensure you have enough RAM to fit the entire dataset in memory.

2. Check your buffer/cache size with free

3. After upload, drop the page cache, on linux systems this can be accomplished with 
```
sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"
```

4. As a sanity check, you can run free and make sure the buff/cache is lower than right after the upload.

5. Run heal on your bucket, note time 
'''
 mc admin heal --recursive myminio/downbucket
'''
6. Check buffer cache size with free, should be larger
7. Re-run heal again, likely it will be much faster, suggesting it is reading from the page cache.

As a full example from my runs, note second run is much faster:

```
$ sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           376G        1.8G        374G        114M        432M        373G
Swap:          975M          0B        975M
$ mc admin heal --recursive myminio/downbucket
 ◐  downbucket/test.99
    0/500 objects; 7 GiB in 1m24s
    ┌────────┬─────┬─────────────────────┐
    │ Green  │ 502 │ 100.0% ████████████ │
    │ Yellow │   0 │   0.0%              │
    │ Red    │   0 │   0.0%              │
    │ Grey   │   0 │   0.0%              │
    └────────┴─────┴─────────────────────┘
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           376G        1.9G        358G        114M         16G        373G
Swap:          975M          0B        975M
$ mc admin heal --recursive myminio/downbucket
 ◑  downbucket/test.99
    0/500 objects; 7 GiB in 6s
    ┌────────┬─────┬─────────────────────┐
    │ Green  │ 502 │ 100.0% ████████████ │
    │ Yellow │   0 │   0.0%              │
    │ Red    │   0 │   0.0%              │
    │ Grey   │   0 │   0.0%              │
    └────────┴─────┴─────────────────────┘
$

```

## Context
This issue has not directly impacted me, but in a environment with long-lived data creates some risk that data corruption may not be promptly caught.

## Your Environment

Ubuntu 16.04, client and server on the same machine,
Minio commit 7ac0fccb6eb2f3bb69af3ba670faf6b6a8a6755f

**Comment by krishnasrinivas** [comment]
Thanks for the due diligence @ifadams

**Comment by keirafadams** [comment]
@krishnasrinivas Of course. Let me know if any additional information is helpful.

**Comment by harshavardhana** [comment]
Entire bit-rot now happens upon reads in a streaming fashion i.e the entire stream is always bit-rot read even if its in page-cache.

@krishnasrinivas does this still make sense to keep this issue open?

**Comment by keirafadams** [comment]
If a bitrot read is ever coming from the page-cache, regardless of source, it can potentially miss on-disk corruption. It's certainly not a huge risk as the page-cache usually churns enough over time that a subsequent read will hit the disk, but it is a window of vulnerability.

**Comment by krishnasrinivas** [comment]
@ifadams as you mentioned page-cache usually churns enough over time.

But important fact that needs to be underlined is minio will never serve corrupted data, i.e even if the data is corrupted on the disk and not corrupted in page-cache.

The only downside is ofcourse, during bitrot healing it might go undetected. But it will be eventually caught because of the page-cache purge and re-read from the disk. Hence we can ignore this issue and close it. It is not that we can't handle it, just that adding code for this is not worth it.

**Comment by harshavardhana** [comment]
For the time being, closing this as it's not needed for now and can be implemented in the future.  Using page-cache outweighs the benefits of not using it.
