### ISSUE TITLE
Feature request - Gateway for Azure Data Lake

### ISSUE THREAD

**Issue by Cdaly1970** [minio/minio#6153]
While the direct access to Azure blob storage is a fantastic feature, Azure SME's typically position Azure Data Lake Store as the equivalent S3 storage for Big Data applications.  And since most 3rd Big Data apps incorporate some kind of S3 access model, providing a gateway to ADLS would open a wider option for Minio in the Big Data space.

**Comment by deekoder** [comment]
We will investigate this further.

**Comment by kannappanr** [comment]
@Cdaly1970 Thank you for your suggestion. We had a brief talk about this request. We will definitely be incorporating this into our roadmap. We are doing other important features like identity management. We will take a look into ADLS APIs and get back to you with more information on a timeline when we can implement this feature.

**Comment by deekoder** [comment]
@Cdaly1970  we will consider this for the future. At the present moment, we will wrap up with the current set of features we are working on. I will close for now and put it in our backlog. Reactivate it when we are ready to consider the next set of feature asks.

**Comment by cruizen** [comment]
Any plans to consider this in the near future/ the 'future' milestone?
