### ISSUE TITLE
Website is having issues

### ISSUE THREAD

**Issue by firrae** [minio/minio#6154]
Hey there,

Just notifying you that it seems https://www.minio.io/ is having issues rendering? It just seems to be dumping the template instead of it being parsed into valid HTML.

Wasn't sure how else to inform you. Thanks,

Steve

**Comment by nitisht** [comment]
Thanks for reporting @firrae we will take a look ASAP

**Comment by harshavardhana** [comment]
Closing this as fixed for now. Thanks for letting us know @firrae

**Comment by firrae** [comment]
Awesome, thanks! Keep up the good work with this project!
