### ISSUE TITLE
Detect & warn if minio distributed mode has sub-optimal ordering of disks in distro sets

### ISSUE THREAD

**Issue by robgirard** [minio/minio#6156]
## Expected Behavior
Currently, a user could accidentally run distributed mode in a sub-optimal way that may jeopardize HA (the ability to lose a node).
##### Example:
Minio server configured for EC:4 erasure coding (12 data + 4 parity)
`minio server http://server{1..4}/disk{1..8}`  *wrong way* - 2 ellipse expand in shell
vs
`minio server http://server{1...4}/disk{1...8}` The *right way* - minio server handles distribution of disks

Both examples result in 2 distribution sets of 16 disks each. The first example results is servers 1 & 2 contributing the disks to set1, and servers 3 & 4 contribute to set 4. Lose a server, and you lose 8 out of 16 disks from 1 of the sets, which is higher than the 4 that the EC:4 erasure code allows. All objects in those sets are unavailable.

2nd example will have all 4 servers contributing 4 disks to each distribution set. A failure of 1 node will still allow buckets to be accessible (4 / 16).

## Current Behavior
minio server can't detect when 2 dots {n..m} are used. Or, if the user writes out a fully expanded list of server/disk. Upon cluster creation, the format.json files are created in /.minio.sys folder of each disk. Once these files exist, a user could change from {n..m} to {n...m}, but the damage is already done because the distribution order has already been written into format.json. 

## Possible Solution
Upon starting minio server, run a check to see which disks belong to which hosts (based on host name/IP), and whether or not any distribution set is too heavily populated by disks from the same node which would violate HA, based on storage-class configuration.

If an HA violation occurs, and it is upon first creation of the format.json files, throw a warning that HA may be impacted and exit out, not creating the format.json files. To override, start with a switch (such as --override-HA-warning) to create the format.json files and start the server.
OR
Warn the user, but create anyway. In the warning, there should be some advice and recommendation to remove the format.json files and start again using the correct notation (3 dots: {n...m} )

If an HA violation is detected on an existing cluster, give a warning at startup, similar to the warning given when the minio version is out of date. The warning should state that we've detected a case where "you have too many eggs in one basket" and may violate HA. To correct this, a new cluster needs to be created and buckets/objects would need to be migrated.

Additionally, using `mc admin info SERVER --json` should return an additional element from the servers, which would be ` "is_local":"true" ` to be true/false for each disk local to each node reporting back. This would make it easier to calculate potential violations. 

Here's a sample:
```code
{
  "status": "success",
  "service": "on",
  "address": "minio02:9000",
  "error": "",
  "storage": {
    "used": 13645119488,
    "backend": {
      "backendType": "Erasure",
      "onlineDisks": 16,
      "offlineDisks": 0,
      "standardSCData": 12,
      "standardSCParity": 4,
      "rrSCData": 14,
      "rrSCParity": 2,
      "sets": [
        [
          {
            "uuid": "2841fb40-1eb3-459d-8017-7474ebc0587e",
            "endpoint": "https://minio01:9000/mnt/disk1",
            "state": "ok"
            "is_local":"false"
          },
          {
            "uuid": "e3698947-318e-4347-abe8-3cce6cefd032",
            "endpoint": "https://minio02:9000/mnt/disk1",
            "state": "ok"
'            "is_local":"true"'
          },
          {
            "uuid": "8a3f313d-1ee9-4361-ac3f-c1f105a266ef",
            "endpoint": "https://minio03:9000/mnt/disk1",
            "state": "ok"
            "is_local":"false"
          },
          {
            "uuid": "47a71e88-7069-4d4b-9684-0df418f50700",
            "endpoint": "https://minio04:9000/mnt/disk1",
            "state": "ok"
            "is_local":"false"
          },
```

## Context
It's really easy to get minio server up and running, and once running, it would be nice to know if you're running in a sub-optimal way. In my case, I didn't realize there was a difference between `{n..m}` and `{n...m}` until later. Any clusters I created the wrong way may not have the desired availability I think they should have. A warning to advise me would be very helpful and could have prevented me from choosing a non-optimal distribution of disks in the first place.

**Comment by harshavardhana** [comment]
Working on this already.
