### ISSUE TITLE
using Minio Browser with AWS S3/Ceph RGW

### ISSUE THREAD

**Issue by alfozan** [minio/minio#6157]
The Minio browser is a simple and elegant tool to interact with object storage backends.

It'd be great to add config ( `<YOUR-S3-ENDPOINT> , <YOUR-ACCESS-KEY> , <YOUR-SECRET-KEY> `) so the browser can connect to other services like AWS S3/Ceph RGW

**Comment by harshavardhana** [comment]
> It'd be great to add config ( <YOUR-S3-ENDPOINT> , <YOUR-ACCESS-KEY> , <YOUR-SECRET-KEY>) so the browser can connect to other services like AWS S3/Ceph RGW

you can use `minio gateway s3`

**Comment by kannappanr** [comment]
@alfozan You can use `MINIO_ACCESS_KEY=<AccessKey> MINIO_SECRET_KEY=<SecretKey> minio gateway s3` can be used to connect to AWS S3. `MINIO_ACCESS_KEY=<AccessKey> MINIO_SECRET_KEY=<SecretKey> minio gateway s3 --address http(s)://s3Endpoint:port` can be used to connect to any other AWS S3 compatible endpoint. please feel free to reach out to us if you have any other questions.

**Comment by alfozan** [comment]
Thanks - I just tested the browser client with Ceph v13.2.0 RGW and it's working great!

`docker run -it --rm -p 9000:9000 -e "MINIO_ACCESS_KEY=x" -e "MINIO_SECRET_KEY=y" minio/minio minio gateway s3 http://IP:7480`
