### ISSUE TITLE
Incoming/Outgoing stats are incorrect (mc admin info)

### ISSUE THREAD

**Issue by robgirard** [minio/minio#6158]
The stats reported in `mc admin info` are incorrect. 

## Expected Behavior
I expect the incoming & outgoing bytes to be accurate. Ideally, there would be 4 counters:

__INTERNAL-INCOMING__ (bytes received from other nodes in the cluster/federation. Includes data parts fetched, and internode communications)
__INTERNAL-OUTGOING__ (bytes sent to other nodes in the cluster/federation)
__CLIENT-INCOMING__ (bytes received from clients - typically PUT object requests)
__CLIENT-OUTGOING__ (bytes sent to clients - typically GET object requests)

## Current Behavior
Below is some screenshots (out of many tests!), indicating issues with the stats. These examples are a `GET` & `PUT` tests, using `mc cp` to download\upload an object. The client was copying from Minio01. The erasure coding on this object (250MB) was set to reduced redundancy (EC:2), and the distribution set placed the 2 parity chunks on the first 2 disks of minio01. In the image, the erasure coding was highlighted as "N x Data" for each server.

There are 16 disks in total. Minio server 01 -> 03 each have 4 disks, and servers 04 & 05 have 2 disks each. 
![image](https://user-images.githubusercontent.com/39597178/42719568-8bb45f28-86cc-11e8-8594-4fb665c7cf14.png)

Using this, and several other tests, the summary of findings are as follows:

### GET requests:
![image](https://user-images.githubusercontent.com/39597178/42719553-41b24250-86cc-11e8-918f-80cbcc4cf876.png)
![image](https://user-images.githubusercontent.com/39597178/42718894-d9c1c764-86c2-11e8-81f2-2ffd4815c220.png)

- Data transfer stats are DOUBLE what they should be (in all cases)
- On the node servicing the client (minio01 in this example): __OUTGOING__ is correctly calculated, but shown DOUBLE what it should be (500 MiB instead of 250 MiB). If 4 metrics (internal inc/out | client inc/out ) are used, __CLIENT-OUTGOING__ should be 250 MiB, and the other 3 should have zero incremented data.
- On the node servicing the client (minio01): __INCOMING__ is INCORRECT. This should be the sum of all outgoing data from the other 4 nodes, equal to (object size) - (size of parts local to node servicing client), which is ~216 MiB in this case. IF 4 metrics are used, __INTERNAL-INCOMING__ = 216 MiB. CLIENT-INCOMING = near zero, the small about of data from the HTTP headers/requests received from the client.
- On the other nodes in the cluster with data (minio02 -> minio05) - __OUTGOING_ should equal size of data sent to node servicing the client. Like all other values, this is currently DOUBLE, but otherwise accounted for. For 4 metrics, this should be accounted to __INTERNAL-OUTGOING__. __CLIENT-OUTGOING__ should be ZERO.
- On the other nodes in the cluster with data (minio02 -> minio05) - __INCOMING__ shows the same value as __OUTGOING__ and is incorrect. This should be near-zero, except for http headers/requests from the node servicing the client. For 4 metrics, __INTERNAL-INCOMING__ should be near-zero and __CLIENT-INCOMING__ should be ZERO.

### PUT requests:
![image](https://user-images.githubusercontent.com/39597178/42719575-a2fa19c0-86cc-11e8-9434-f2430fa696ec.png)

![image](https://user-images.githubusercontent.com/39597178/42719563-6744d938-86cc-11e8-826c-54fb290b4f3c.png)
![image](https://user-images.githubusercontent.com/39597178/42719589-2b6dfa24-86cd-11e8-9e91-f058e497987a.png)

- Node servicing client's PUT request (MINIO05) - __INCOMING__ shows double the 250 MiB received from client. Value should be 250 MiB. For 4 metrics, this 250 MiB should be attributed to __CLIENT-INCOMING__. __INTERNAL-INCOMING__ should be near-zero. __OUTGOING__ should show data sent to other nodes, which is usually larger than the object size, depending on storage-class and how much data/parity is written locally to this node's disks. If implementing 4 metrics, __INTERNAL-OUTGOING__ should show data/parity sent to other nodes. __CLIENT-OUTGOING__ should be near-zero (only http responses to client's request).
- Other nodes - __INCOMING__ is double what it should be. Minio04 shows half of what Minio01->03 shows because it has 2 disks, but the others have 4 disks (and get more data/parity blocks). This should be __INTERNAL-INCOMING__. __CLIENT-INCOMING__ should be ZERO on these nodes. __INTERNAL-OUTGOING__ should be near-zero (only http responses to node servicing client). __CLIENT-OUTGOING__ should be ZERO. __OUTGOING__  as-is (2 metrics) should be near-zero (the sum of all data sent to other nodes + client (0 MiB) )

## Possible Solution
Highlighted above

## Steps to Reproduce (for bugs)
Restart minio server. Run `mc admin info` on the cluster and record initial values. PUT and GET some objects (in separate tests), then re-run `mc admin info`. Compare the stats of what they are to what they should be.

__NOTE:__ For GET tests, it is important to know what erasure coding is used, and the distribution order. Refer to xl.json for the object to get this info. Expected results is that ONLY data (which starts at disk #1 in the dist set) blocks are fetched from remote nodes and sent to the node responding to the client request. Nodes/Disks with parity blocks should not increment outgoing counters on those nodes.

## Context
Correct accounting is very important to highlight potential imbalances in the cluster. Breaking out metrics into internal & client provides even more contextual value for troubleshooting. 

Operations like HEAL may generate a lot of internal internode communication. 

Client-only metrics will help provide insight as to how the object storage is used (%read vs %write)

## Your Environment
Node sizing & distribution described in "current behavior" section.
```
$ minio --version
VERSION:
  2018-07-13T00:09:07Z 
```
```
$ mc update
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ mc is 2 days 6 hours 5 minutes old                            ┃
┃ Update: https://dl.minio.io/client/mc/release/darwin-amd64/mc ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by deekoder** [comment]
This is blocked till rob/ab finalize the exact output.

**Comment by deekoder** [comment]
unassigned @balamurugana till @robgirard works out the actual UX with ab for what he thinks ought to be shown instead.

**Comment by robgirard** [comment]
I spoke with AB, and we'll take a phased approach to this. Let's proceed as follows:
1. Using the existing network stat counters, (minio_network_received_bytes_total & minio_network_sent_bytes_total - when viewed from http://server/minio/prometheus/metrics), correct them to make them accurate for EXTERNAL traffic. Communications to/from clients access minio server, NOT internode communications. The output in `mc admin info` will get correctly affected. 

Proceed with this to unblock & resolve this issue, then subsequent improvements will be as follows:

2. Add new counters for INTERNAL traffic (node to node communication). In the prometheus counters, these would be: minio_network_internode_received_bytes_total & minio_network_internode_sent_bytes_total. 

3. With 4 different metrics, then we can make improvements to how `mc admin info` can leverage them in a clean and useful manner, such as: sum of all external traffic to provide total traffic for entire cluster with outside world, break-downs of global cluster info and `--nodes` per node info, etc. Will raise a different issue/spec for these improvements independent of getting these network stats fixed.

Thanks!
Rob
