### ISSUE TITLE
Generate/calculate internal HTTP/RPC & disk metrics

### ISSUE THREAD

**Issue by robgirard** [minio/minio#6159]
If a single node has a single slow disk, or bad network connection (up, but poorly performing), performance of the whole cluster will be impacted. Troubleshooting this may be difficult, especially if the culprit is only ONE of several interswitch links within an LACP bundle between switches. Network conditions could be due to faulty physical hardware, or sporadic cases where one or more links are saturated. In the case of containers, over-subscribed hosts may also contribute to poor performance of one or more nodes.

## Current Behavior
Currently minio only has latency stats for HTTP requests from the client. This is representative of the overall experience, but doesn't indicate whether the latency is due to the connection between client and cluster, or due to connections within the cluster.

## Expected Behavior
We should collect fully-meshed metrics between all nodes, as well as metrics from client. 

At what granularity we capture metrics, what sampling rate, and overall averaging methodology should be discussed. We don't want important outliars to get averaged out, masking a potential issue.

Where we log to is also to be determined. Probably best to leverage Prometheus, or other external logging. 

We should also capture disk latencies independent from HTTP latencies.

## Possible Solution
10 minute averages, with peak/trough values to pick up the 99 percentile cases. Calculate PUT and GET separately, and for each connection (s1 <-> s2, s1 <-> s3, s1 <-> s4, s2 <-> s3, s2 <-> s4, etc).

Latest info should be retrievable with `mc admin info --json`, and historical can be captured with a 3rd party solution (such as prometheus).

Enabling a real-time higher-granularity (shorter sampling periods, raw data without averaging, etc) for short periods would be extremely helpful for performance benchmarking & troubleshooting. 

Disk latencies should capture as much as possible when real-time mode is enabled. 

Breaking down accumulated end-to-end latency to a stacked graph would be a huge plus to solve performance issues at a glance that could otherwise take many hours to diagnose & isolate using other means. 

## Your Environment
All environments would benefit from this. Metrics may be specific to bare-metal/VM deployments vs containerized deployments.

**Comment by harshavardhana** [comment]
isn't this already done @nitisht ?

**Comment by nitisht** [comment]
closing this in favour of https://github.com/minio/mc/issues/2606
