### ISSUE TITLE
After version upgrade, consistent Out of Memory errors and high utilization

### ISSUE THREAD

**Issue by tylerforsythe** [minio/minio#6164]
## Expected Behavior

Minio runs within memory constraints without crashing.

## Current Behavior

Using a version of Minio from mid-October 2017, server had no issues running. After upgrading to the latest version a few weeks ago (skipping many in-between), Minio crashes after a few hours of intense CPU, disk, and memory activity with an out of memory error (see log file attached). Continuing to upgrade to the very latest releases does not fix the issue.

## Possible Solution

More RAM?
Rollback to prior version, if possible? (Currently old versions won't start because of a version # in the config file, and I am afraid to force it by rolling back that #).

## Steps to Reproduce (for bugs)

Unfortunately I don't have specific steps to reproduce and would expect others to be having the same problem I am, as I don't consider myself a big user compared to what I'm sure others are running. However, it happens 100% of the time in my environment within 24 hours of process start. I haven't been measuring precisely, but I would guess within 8 hours of startup the process is no longer running due to crash.

## Context

As mentioned earlier, I first started using Minio in July of 2017, then upgraded in mid-October 2017. I used it for a personal backup destination for many months without issue. I decided to upgrade versions a few weeks ago and noticed that disk, CPU, and memory activity on the machine went up *significantly* due to minio.exe. It is not uncommon for minio to be using 14+ GB of RAM, maxing at least 2 of the 4 drives it has data on, and significant CPU utilization. This utilization happens regardless of whether there is an active backup job hitting the server. On an average day, minio should be idle at least 90% of the time. The old version never had utilization like that.

My initial thought was that this was a bug in the latest release and would be found by many others and fixed, but it appears that is not the case as I have upgraded to the very latest a few times since and my problem persists. I also thought perhaps it was trying to get through some sort of metadata upgrade and would eventually finish and the issue would go away, but it has been weeks of off and on. So I get the feeling it is trying to do something that resets to start every time it crashes. Or, it is simply stuck in a loop until it runs out of memory.

## Your Environment

* Version used (`minio version`):
Version: 2018-07-13T00:09:07Z
Release-Tag: RELEASE.2018-07-13T00-09-07Z
Commit-ID: 2aa18cafc674faf97201a973504cb4caa3a3e67c
* Environment name and version (e.g. nginx 1.9.1): Windows 10 Pro
* Operating System and version (`uname -a`): Windows 10 Pro, patched to latest.
* Link to your project: n/a
* Machine specs: Intel i7-3770K (*no* overclock!), 32 GB RAM, 120 GB C: SSD, two 3.0 TB HDDs, two 6.0 TB HDDs (and a few others that minio does not use), wired gigabit ethernet. Even with a couple VMs running, 16-18 GB of RAM is normally available for minio to use.
Home Office -- not a high-load environment.

I was using minio as a Windows service using the setup described here https://github.com/minio/minio-service/tree/master/windows but have stopped that and been manually starting to find out what was happening and to capture a log. I start minio with this line: 
W:\private\minio\minio.exe --config-dir W:\private\minio\ server V:\MinioDataV W:\MinioDataW\ X:\MinioDataX Y:\MinioDataY\

Each of the disks has ~295 GB of Minio data on them.

I'd be happy to test configuration changes, new versions, etc. Thank you!

[config.txt](https://github.com/minio/minio/files/2199746/config.txt)
[minio_out2.txt](https://github.com/minio/minio/files/2199744/minio_out2.txt)
![minio_drives](https://user-images.githubusercontent.com/1689004/42792713-efae59ca-8933-11e8-8cbc-881627dc3512.png)

**Comment by harshavardhana** [comment]
> As mentioned earlier, I first started using Minio in July of 2017, then upgraded in mid-October 2017. I used it for a personal backup destination for many months without issue. I decided to upgrade versions a few weeks ago and noticed that disk, CPU, and memory activity on the machine went up significantly due to minio.exe. It is not uncommon for minio to be using 14+ GB of RAM, maxing at least 2 of the 4 drives it has data on, and significant CPU utilization. This utilization happens regardless of whether there is an active backup job hitting the server. On an average day, minio should be idle at least 90% of the time. The old version never had utilization like that.

- The CPU usage is due to disk utilization crawling, which would suspend itself if there is an active I/O - if you have a lot of data it will take a while before it computes the utilization. 
- Memory usage is perhaps because we have changed the bit-rot behavior by loading each block in memory around 4-5months ago. The version perhaps which you used in 2017 was not creating smaller blocks for objects to support the bit-rot behavior which it does now. I am assuming you have some files which are large and have been split differently. if you do CopyObject() of these objects then they will be re-striped with smaller blocks such that memory is at a manageable level. 

Thanks for reporting the issue

**Comment by tylerforsythe** [comment]
Thanks for the response, @harshavardhana. Are you implying that if I keep starting the minio process and letting it run that it will eventually finish computing what it needs to do? Or do I need to find those large objects and delete/copy them? (In both cases, assuming a fix does not arrive first.) I generally try to keep large files out of my backups but in this case I do know of a few that sneaked in before I caught it and removed them from the backed-up directory (~5 GB movie files).

**Comment by harshavardhana** [comment]
> Are you implying that if I keep starting the minio process and letting it run that it will eventually finish computing what it needs to do?

Yes, it will finish computing them eventually, now this depends on the disk itself. There will be a spike in CPU if there is no active I/O in progress to use the disk.

> (In both cases, assuming a fix does not arrive first.)

There is no fix actually since we have moved to the model I explained because of an important requirement in bit-rot verification but changed the chunking behavior instead.  But since we had to support backward compatibility we still read older content. 

> I generally try to keep large files out of my backups but in this case I do know of a few that sneaked in before I caught it and removed them from the backed-up directory (~5 GB movie files).

5GiB movie files would have resulted in a big chunk which might have resulted in a memory spike. Assuming these files were uploaded directly using a PutObject API

**Comment by harshavardhana** [comment]
@tylerforsythe are you satisfied with the assessment and remedies?

**Comment by tylerforsythe** [comment]
@harshavardhana my understanding is that you know what's happening based on the log, and the immediate solution for me is to simply let minio run and it will eventually finish what it's trying to do in the background. Hopefully longer-term the out of memory exception is addressed so that future users won't run into this issue.

I'm a little concerned that minio is getting stuck and never going to get through this out of memory error because it's been working on my data for at least 2 weeks now, maybe 3. Seems like it should be done by now.

**Comment by harshavardhana** [comment]
> @harshavardhana my understanding is that you know what's happening based on the log, and the immediate solution for me is to simply let minio run and it will eventually finish what it's trying to do in the background. Hopefully longer-term the out of memory exception is addressed so that future users won't run into this issue.
> 
> I'm a little concerned that minio is getting stuck and never going to get through this out of memory error because it's been working on my data for at least 2 weeks now, maybe 3. Seems like it should be done by now.

are you saying that CPU usage is high even after the last 2weeks? or 3? - the usage routine runs every 12 hours, right after the first usage check gets over?

Memory usage as I explained is mostly due to the fact that you uploaded large files which were chunked differently previously, you can re-chunk by using CopyObject() API by performing a server-side copy of the object.  `mc cp` or directly using CopyObject would work for you.

**Comment by tylerforsythe** [comment]
> are you saying that CPU usage is high even after the last 2weeks? or 3?

Correct. I'm saying that I've been having this sort of CPU/memory/disk utilization from the minio.exe process for at least 2 weeks now, basically constant--not limited to a few times a day. I think running it as a service auto-restarts it when it crashes.

I used the command `mc find local --larger 1GB` a few days ago and, after running a couple hours, it didn't find anything, which surprised me. (I don't know exactly how long it ran because I just checked on it periodically.) Perhaps my backup software automatically split the large files into smaller.

**Comment by harshavardhana** [comment]
> Correct. I'm saying that I've been having this sort of CPU/memory/disk utilization from the minio.exe process for at least 2 weeks now, basically constant--not limited to a few times a day. I think running it as a service auto-restarts it when it crashes.

This is very unusual and unexpected, do you have any more details like memory, CPU profiling? can you enable with `_MINIO_PROFILER=mem` to `_MINIO_PROFILER=cpu`? as an environment variable on windows?

**Comment by tylerforsythe** [comment]
Sure, I'll give it a shot with _MINIO_PROFILER=mem and report back when I've got a useful log. Where should I look for the output file? Once I have one for mem, I'll do it again for _MINIO_PROFILER=cpu. Or can I do both at the same time?

**Comment by harshavardhana** [comment]
> Sure, I'll give it a shot with _MINIO_PROFILER=mem and report back when I've got a useful log. Where should I look for the output file? Once I have one for mem, I'll do it again for _MINIO_PROFILER=cpu. Or can I do both at the same time?

You need to do one at a time otherwise profiler output will be inconsistent. The profile output is generated in your temporary directly. So once you enable it you will see a message at the top of the startup where this file is going to be stored. 

```
_MINIO_PROFILER=mem minio server ~/test
2018-07-20 11:10:03.029112 I | profile: memory profiling enabled (rate 4096), /tmp/profile645473885/mem.pprof
....
....
....
```

**Comment by tylerforsythe** [comment]
Here are CPU and MEM files from different runs yesterday. They are .pprof files renamed to .txt so GitHub will accept them. Peak minio.exe memory usage was at least 20 GB each run.

[cpu.txt](https://github.com/minio/minio/files/2216320/cpu.txt)
[mem.txt](https://github.com/minio/minio/files/2216321/mem.txt)

**Comment by harshavardhana** [comment]
Thanks @tylerforsythe

**Comment by harshavardhana** [comment]
> Here are CPU and MEM files from different runs yesterday. They are .pprof files renamed to .txt so GitHub will accept them. Peak minio.exe memory usage was at least 20 GB each run.
> 
> cpu.txt
> mem.txt

Sorry for late reply @tylerforsythe how many files do you have under a single bucket? do you have all the files in a single directory?

**Comment by tylerforsythe** [comment]
No worries @harshavardhana. The backup software I currently use is [Arq](https://www.arqbackup.com/), which unfortunately places nearly all of its files in a single directory. So while I can't give you an exact number, it will easily be over 10,000, and I wouldn't be surprised if it were more than 100,000.

**Comment by harshavardhana** [comment]
> No worries @harshavardhana. The backup software I currently use is Arq, which unfortunately places nearly all of its files in a single directory. So while I can't give you an exact number, it will easily be over 10,000, and I wouldn't be surprised if it were more than 100,000.

The reason I found is that Go windows implementation of our readdir call is memory intensive with diskUsage crawler it has led to a high memory usage, coupled with all of your files in the same directory/bucket it will cause significant memory usage. 

I have a simpler solution right now will send a fix and should be available in the future releases.

**Comment by tylerforsythe** [comment]
Sounds great! I look forward to trying it out!

**Comment by tylerforsythe** [comment]
I hate to be the bearer of bad news, @harshavardhana , but the fix has not been working for me. I've upgraded to all the most recent Minio.exe builds since the last post in this issue, but with no success. I've delayed responding here in case the fix was in a build later than I thought, and because I found an issue in my environment and wondered if it was related. I've determined it is not but will outline what I've found in the past month.

I noticed as time went on that Minio started reporting read errors on my V: drive, but not any of the others. Separately, I discovered while trying to copy a set of large files from my V: drive (completely unrelated to Minio) that there was at least one corrupted file in the mix. This led me to believe my V drive was experiencing data corruption, and I wondered if it was the culprit of problems all along. I replaced both my V and X drives. Because they're identical and were purchased at the same time, I replaced both just in case the X drive was soon to follow. Two brand-new 6 TB drives are in their place.

This allowed me a chance to test Minio's healing capabilities, which so far are working OK. However, I've not been able to fully test it (I've only healed about half my data set so far) because Minio continues to crash with out of memory errors after 6-7 hours of run time. I brainstormed that if this out of memory error cannot be fixed I could heal in two stages to work-around the bug. First the V and X drives, which should heal their data in this "new" format. Then delete the Minio data on W and Y and heal back to those drives. Thus getting all my data into the new format in a very round-about (and dangerous) fashion.

But like I said, because Minio continues to crash with out of memory exceptions during the heal, I've yet to accomplish this in full. My previous screenshot shows my Minio data at 294 GB, and currently I've only healed about 154 GB. The healed amount tends to change unpredictably. Sometimes it will run for hours and appear to make 0 progress (the V and X data directories are not larger), and other times they will grow by several GB. It's almost as if the process is starting over every single time and it only makes progress if it happens to run longer than last time. I'm not sure, though.

Further, even without the heal running, the W and Y drives continue to be hammered while Minio consumes more and more memory for several hours before crashing. This is puzzling to me, because with the number of times I've run Minio it has to have a total run time of at least 50 hours, maybe much more. Assuming a read/write speed of just 10 MB a second, which is very slow for a SATA drive, even platter-based, it would have been able to read/write 1.8 TB of data from each drive. Even if speed were half that at 5 MB/s, that's still 900 GB. Half that, 2.5 MB/s would be 450 GB in that time period. Given my total data set is ~300 GB, I am extremely puzzled as to why it's not done yet unless it is restarting progress every single time. Which isn't logical given that no software would try to complete 300 GB worth of work before writing out progress. That wouldn't make sense.

Can you shed any light into what's going on here? My last resort is to simply delete everything and restart with no data. That's not the end of the world because my most important backup copy is off-site. Having stuff locally is for a more convenient full-copy.

I've attached CPU and MEM logs that I gathered yesterday, letting it run for a few hours and _not_ healing, just doing it's behind-the-scenes work. Again, it slammed usage of my W and Y drives, as well as the CPU. I stopped it before a crash to get the log output. The CPU log is shorter than the mem one due to my schedule, but it still has a couple hours.

Thank you.

[mem_20180918.txt](https://github.com/minio/minio/files/2397728/mem_20180918.txt)
[cpu_20180918.txt](https://github.com/minio/minio/files/2397729/cpu_20180918.txt)

**Comment by harshavardhana** [comment]
Can you open a new issue to track this ?

**Comment by tylerforsythe** [comment]
Will do.

edit: https://github.com/minio/minio/issues/6490
