### ISSUE TITLE
Recursive rm results in hang

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#6166]
`mc rm --recursive --force <host>/<bucket>` results in hang 
## Expected Behavior

mc rm should be able to remove all files without hanging

## Current Behavior

When running the command against a bucket with many thousands of files, it lists the first 1000 files then hangs
```
...
Removing `<host>/<bucket>/0x0aaaaaaabmj`.
Removing `<host>/<bucket>/0x0aaaaaaabmk`.
Removing `<host>/<bucket>/0x0aaaaaaabml`.
Removing `<host>/<bucket>/0x0aaaaaaabmm`.
Removing `<host>/<bucket>/0x0aaaaaaabmn`.
```

## Possible Solution

Possibly doing a remove of the bucket without verifying all files (although this would result in additional data left on the backend fs
## Steps to Reproduce (for bugs)

1.  Create a bucket with thousands of small files (each file in my env was between 0 - 10 bytes)
2. `mc rm --recursive --force <host>/<bucket>`

## Your Environment

* Version used (`minio version`): `docker exec <container> minio version
Version: 2018-07-13T00:09:07Z
Release-Tag: RELEASE.2018-07-13T00-09-07Z
Commit-ID: 2aa18cafc674faf97201a973504cb4caa3a3e67c
* Environment name and version (e.g. nginx 1.9.1):
Mac OS X High Sierra 10.13.6 running Docker for Mac Version 18.03.1-ce-mac65 (24312), 4 containers with 8 disks each
* Operating System and version (`uname -a`): Linux <hostname> 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux

[env.gz](https://github.com/minio/minio/files/2202823/env.gz)

**Comment by harshavardhana** [comment]
Ping @vadmeste

**Comment by vadmeste** [comment]
@eco-minio I was probably able to reproduce this, but to confirm, I wanted to know if you saw any printed error in Minio output ?

**Comment by eco-minio** [comment]
Eventually saw errors like

`minio1_1  | API: PutObject(bucket=test, object=passwd)
minio1_1  | Time: 20:36:28 UTC 07/17/2018
minio1_1  | RemoteHost: 172.18.0.1
minio1_1  | UserAgent: Minio (darwin; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
minio1_1  | Error: Write failed. Insufficient number of disks online
minio1_1  |        1: cmd/xl-v1-utils.go:74:cmd.reduceQuorumErrs()
minio1_1  |        2: cmd/xl-v1-utils.go:87:cmd.reduceWriteQuorumErrs()
minio1_1  |        3: cmd/xl-v1-object.go:75:cmd.xlObjects.prepareFile()
minio1_1  |        4: cmd/xl-v1-object.go:644:cmd.xlObjects.putObject()
minio1_1  |        5: cmd/xl-v1-object.go:523:cmd.xlObjects.PutObject()
minio1_1  |        6: cmd/xl-sets.go:559:cmd.(*xlSets).PutObject()
minio1_1  |        7: cmd/object-handlers.go:732:cmd.(ObjectLayer).PutObject-fm()
minio1_1  |        8: cmd/object-handlers.go:810:cmd.objectAPIHandlers.PutObjectHandler()
minio1_1  |        9: cmd/api-router.go:79:cmd.(objectAPIHandlers).PutObjectHandler-fm()
minio1_1  |       10: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
minio1_1  | 
minio1_1  | API: PutObject(bucket=test, object=passwd)
minio1_1  | Time: 20:36:30 UTC 07/17/2018
minio1_1  | RemoteHost: 172.18.0.1
minio1_1  | UserAgent: Minio (darwin; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
minio1_1  | Error: Write failed. Insufficient number of disks online
minio1_1  |        1: cmd/xl-v1-utils.go:74:cmd.reduceQuorumErrs()
minio1_1  |        2: cmd/xl-v1-utils.go:87:cmd.reduceWriteQuorumErrs()
minio1_1  |        3: cmd/xl-v1-object.go:75:cmd.xlObjects.prepareFile()
minio1_1  |        4: cmd/xl-v1-object.go:644:cmd.xlObjects.putObject()
minio1_1  |        5: cmd/xl-v1-object.go:523:cmd.xlObjects.PutObject()
minio1_1  |        6: cmd/xl-sets.go:559:cmd.(*xlSets).PutObject()
minio1_1  |        7: cmd/object-handlers.go:732:cmd.(ObjectLayer).PutObject-fm()
minio1_1  |        8: cmd/object-handlers.go:810:cmd.objectAPIHandlers.PutObjectHandler()
minio1_1  |        9: cmd/api-router.go:79:cmd.(objectAPIHandlers).PutObjectHandler-fm()
minio1_1  |       10: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()`

Checking backend of the Docker for Mac VM, noted that we had actually run out of inodes:

`linuxkit-025000000001:/var/lib# df -i /var/lib
Filesystem              Inodes      Used Available Use% Mounted on
/dev/sda1              3907584   3905232      0 100% /var/lib`

So root cause is running out of inodes in the Docker VM that was serving the volumes for the containers.  Currently freeing inodes to see if the operation is allowed to continue.  Is there a way to detect and warn on this condition?

**Comment by vadmeste** [comment]
We had inode checks before but it was removed by this PR https://github.com/minio/minio/pull/4747

By the way, can you check the number of free inodes before starting to test ? It is probably that in your case, free inodes is probably always 0.

Besides, what is the server configuration ? FS ? Distributed XL ?

**Comment by eco-minio** [comment]
Running `mc find <host>/<bucket>/ --exec "mc rm {}"` is slowly freeing up inodes, I'll wait until I have a decent amount before trying again.  Does mc rm of an entire bucket put things over to a temp space before deleting?  Might explain why mc rm --exec works but mc rm <bucket> doesn't?  Server config is distributed - `command: server http://minio{1...4}/lb{1...8}`

**Comment by eco-minio** [comment]
> df -i /var/lib/                                   2018-07-18 17:59:58
> 
> Filesystem              Inodes      Used Available Use% Mounted on
> /dev/sda1              3907584   3686274    221310  94% /var/lib

Even with some inodes freed behaviour still persists.

**Comment by harshavardhana** [comment]
Is this issue still reproducible @eco-minio @vadmeste ?

**Comment by eco-minio** [comment]
No longer have Docker for Mac installed, it is working with mc client on Mac against server running in Ubuntu.  Closing.
