### ISSUE TITLE
Add encryption support in minio gateway

### ISSUE THREAD

**Issue by deekoder** [minio/minio#6167]
A special switch could be turned on when starting minio in gateway mode to enable encryption.

## Expected Behavior
if this switch is not on, gateway should not do any encryption in the gateway mode.  People who use minio gateway to retain the ability to access minio natively will still be able to.
 
## Current Behavior
 There is no gateway encryption support

## Possible Solution
 Start with an option to enable encryption in gateway mode and via config.json

 ## Context
It's useful when users want gateway to encrypt and then store the object in the backend.  Perhaps keys stored externally can be used to decrypt the objects on the native backend.

**Comment by aead** [comment]
See also #5801

**Comment by harshavardhana** [comment]
Can we close this bug? #5801 covers the same situation, we should update new changes required in that bug instead.
