### ISSUE TITLE
Support Kafka authentication and TLS for bucket notifications

### ISSUE THREAD

**Issue by OlivierTarnus** [minio/minio#6170]
## Expected Behavior

We should be able to specify the username and password to use when connecting to Kafka brokers, triggering the SASL/PLAIN mechanism that is supported by Sarama library. Ideally, support for TLS should also be configurable.

## Current Behavior

Contrary to other bucket notification endpoints, there is currently no property available to configure authentication for Kafka. This rules out connecting to secured Kafka brokers.

## Possible Solution

Extending the config file items related to Kafka notifications and passing them to their corresponding Config type in Sarama Library should be sufficient to cover these new features.

## Context

We're running a secured Kafka broker and can't afford to disable security. We think this should be a quite trivial implementation that will enable Kafka notification in real production environments.

## Your Environment

N/A : any environment should be impacted by this missing feature.

**Comment by kannappanr** [comment]
@OlivierTarnus Thanks for filing the issue. We will look into this and get back to you on a timeline for implementing this.

**Comment by OlivierTarnus** [comment]
Thanks @kannappanr !

**Comment by balamurugana** [comment]
@OlivierTarnus Current configuration is in https://github.com/minio/minio/blob/master/pkg/event/target/kafka.go#L31.  Similarly it is used like https://github.com/minio/minio/blob/master/pkg/event/target/kafka.go#L104.

1. Do you say all brokers require same config mentioned in https://godoc.org/gopkg.in/Shopify/sarama.v1#Config ?

2. As https://godoc.org/gopkg.in/Shopify/sarama.v1#Config is huge configuration structure,  it would be great if you provide specific subset of configuration is expected to be.

**Comment by annanay25** [comment]
@balamurugana I have submitted #6172 in reference to this issue. Waiting for exhaustive list of config attributes from @OlivierTarnus.

**Comment by balamurugana** [comment]
@annanay25 What is answer for question `1`?  one configuration for all brokers?

**Comment by OlivierTarnus** [comment]
Hello @balamurugana ,

1. I would say yes. In a properly configured cluster both authentication and encryption parameters should be aligned across all brokers.
2. I think the Net -> SASL structure is the key for configuration for authentication, for ex. by turning on the the Enable flag when a username and password are specified in MinIO config. The Net ->TLS struct is the key for enabling TLS, but it's not clear for me if only enabling the Enable flag is sufficient to initiate a TLS client connection or if a specific Config object needs to be passed.

**Comment by balamurugana** [comment]
> I would say yes. In a properly configured cluster both authentication and encryption parameters should be aligned across all brokers.

OK



> I think the Net -> SASL structure is the key for configuration for authentication, for ex. by turning on the the Enable flag when a username and password are specified in MinIO config. The Net ->TLS struct is the key for enabling TLS, but it's not clear for me if only enabling the Enable flag is sufficient to initiate a TLS client connection or if a specific Config object needs to be passed.

I see `TLS.Enable = true` is sufficient to connect to server securely.  Server should have a valid certificates.

**Comment by annanay25** [comment]
+1 @OlivierTarnus: Kafka broker authentication is aligned across all brokers. 

@kannappanr, for `TLS.Enable`, I think default SSL configuration enables 1-way authentication, in which only client verifies the server certificate. However, for 2-way authentication, each client would need to create a cert-pair and get this verified by the brokers.

Ref: https://github.com/confluentinc/confluent-platform-security-tools/blob/master/single-trust-store-diagram.pdf 
(Sample client broker setup using a CA as a trust store)

**Comment by OlivierTarnus** [comment]
@annanay25 , agree on the 2-way SSL authentication but won't be able to help on testing this. Not sure if this is widely used...

**Comment by OlivierTarnus** [comment]
Hello @kannappanr , @annanay25 ,

I see that code has been pushed and is awaiting merge. Any idea when we could access this code to test on our side?

Cheers

**Comment by kannappanr** [comment]
@OlivierTarnus The PR will hopefully be reviewed and merged in the next few days. Will try to push for it.

**Comment by juv** [comment]
@kannappanr any update on this?

**Comment by kannappanr** [comment]
@juv I think the support is already there as of release (RELEASE.2018-09-11T01-39-21Z) (https://github.com/minio/minio/pull/6291) Will Close this issue as fixed. Please re-open a new issue if you think otherwise.
