### ISSUE TITLE
Minio distributed deployment waiting for disks to come online indefinitely

### ISSUE THREAD

**Issue by sureshpasupathi** [minio/minio#6187]
I ran minio command on 4 servers to start minio in distributed node. I made sure the time is in sync on all servers and port 9000 is open at iptables. But all four servers are waiting for disks to come online for more than hour.

## Steps to Reproduce (for bugs)

1. Have a wrapper script as below on all 4 servers and running the wrapper script. 
export MINIO_ACCESS_KEY=XXXX

export MINIO_SECRET_KEY=XXXXXXXXX

 

/opt/minio/minio server \

        http://server1/mnt/lppbdsvmi0101 http://server1/mnt/lppbdsvmi0102 \

        http://server2/mnt/lppbdsvmi0201 http://server2/mnt/lppbdsvmi0202 \

        http://server3/mnt/lppbdsvmi0301 http://server3/mnt/lppbdsvmi0302 \

        http://server4/mnt/lppbdsvmi0401 http://server4/mnt/lppbdsvmi0402
2.
3.
4.

## Your Environment

* Version used (`minio version`): 
Minio version
Version: 2018-07-13T00:09:07Z
Release-Tag: RELEASE.2018-07-13T00-09-07Z
Commit-ID: 2aa18cafc674faf97201a973504cb4caa3a3e67c

Setup: one OS disk on each server, two disks for Minio on each server mounted on different mount points.
Request Number:
--

* Environment name and version (e.g. nginx 1.9.1): 
Minio version
Version: 2018-07-13T00:09:07Z
Release-Tag: RELEASE.2018-07-13T00-09-07Z
Commit-ID: 2aa18cafc674faf97201a973504cb4caa3a3e67c

 
* Server type and version:
VMware Virtual - 2 vCPU, 8GB RAM, 10gb OS disk

* Operating System and version (`uname -a`):
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Linux lppbdsvmi04.phx.aexp.com 3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by harshavardhana** [comment]
Check if you have 

- ntp setup on all servers
- selinux disabled
- minio servers have write access to your backend
- firewall disabled or enabled to access port 9000
- all servers are running same version

**Comment by sureshpasupathi** [comment]
Thanks for the quick response. All the above were setup as expected except with one exception. Even though I had enabled port 9000, had another rule that was denying all traffic just above it. Disabled iptables for testing and now it started on all 4 servers and I can access the object storage just fine. Thank you.
