### ISSUE TITLE
Unable to initialize backend: Disk .../minio/b: corrupted backend format, please join ...slack.minio.io for assistance

### ISSUE THREAD

**Issue by koreno** [minio/minio#6188]
Configured minio to run on a cluster of d2.2xlarge instances on AWS.
Most of the time it works fine, but occasionally minio refuses to boot, and we get this error message in /var/log/messages

## Expected Behavior
minio should initialize successfully

## Current Behavior
minio fails to initialize, producing an error message
Unable to initialize backend: Disk .../minio/b: corrupted backend format, please join ...slack.minio.io for assistance

This is the content of the minio folder (seems to be missing a `format.json`):
```
# find /usr/local/share/minio/b/.minio.sys/
/usr/local/share/minio/b/.minio.sys/
/usr/local/share/minio/b/.minio.sys/tmp
/usr/local/share/minio/b/.minio.sys/multipart
```

### minio version
* Version: 2018-07-13T00:09:07Z
* Release-Tag: RELEASE.2018-07-13T00-09-07Z
* Commit-ID: 2aa18cafc674faf97201a973504cb4caa3a3e67c

### server
* CentOS Linux release 7.3.1611 (Core)
* Linux ... 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* AWS EC2 d2.2xlarge

**Comment by koreno** [comment]
also, this is the content of our config file:

```
MINIO_OPTS="-C /etc/minio --address 0.0.0.0:80"
MINIO_ACCESS_KEY=admin
MINIO_SECRET_KEY=weka-minio
MINIO_HTTP_TRACE=/tmp/logs/minio-http.log
MINIO_VOLUMES="http://172.31.20.102:80/usr/local/share/minio/b http://172.31.20.102:80/usr/local/share/minio/c http://172.31.20.102:80/usr/local/share/minio/d http://172.31.20.102:80/usr/local/share/minio/e http://172.31.20.102:80/usr/local/share/minio/f http://172.31.20.102:80/usr/local/share/minio/g http://172.31.22.56:80/usr/local/share/minio/b http://172.31.22.56:80/usr/local/share/minio/c http://172.31.22.56:80/usr/local/share/minio/d http://172.31.22.56:80/usr/local/share/minio/e http://172.31.22.56:80/usr/local/share/minio/f http://172.31.22.56:80/usr/local/share/minio/g http://172.31.23.91:80/usr/local/share/minio/b http://172.31.23.91:80/usr/local/share/minio/c http://172.31.23.91:80/usr/local/share/minio/d http://172.31.23.91:80/usr/local/share/minio/e http://172.31.23.91:80/usr/local/share/minio/f http://172.31.23.91:80/usr/local/share/minio/g http://172.31.17.144:80/usr/local/share/minio/b http://172.31.17.144:80/usr/local/share/minio/c http://172.31.17.144:80/usr/local/share/minio/d http://172.31.17.144:80/usr/local/share/minio/e http://172.31.17.144:80/usr/local/share/minio/f http://172.31.17.144:80/usr/local/share/minio/g"
```

**Comment by nitisht** [comment]
I just observed @koreno from the entries you shared, there is the `lost+found` directory in `/minio/b`, this can cause issues. Minio erasure code needs empty directory to start, can you remove these directories or use another data directory for Minio and give it a try..

**Comment by harshavardhana** [comment]
We should have ignored `lost+found` already @nitisht

**Comment by nitisht** [comment]
> We should have ignored lost+found already @nitisht

Ah yes, we do that.

**Comment by harshavardhana** [comment]
Anything we need to do here @nitisht @koreno ?

**Comment by nitisht** [comment]
Need to check with @koreno will do on Slack

**Comment by koreno** [comment]
hi, sorry for not responding. we've worked around this by using xfs instead of ext4 for the minio filesystem, so we're not waiting on this issue anymore.

**Comment by nitisht** [comment]
No problem. Thanks for the update @koreno . I will be closing this as working as expected. Feel free to reopen/get in touch via Slack if this happens again.
