### ISSUE TITLE
Problem in configuring TLS for Minio in Distributed Mode on DC/OS

### ISSUE THREAD

**Issue by ishanchandrajoshi** [minio/minio#6197]
I  want to implement TLS for Minio in distributed mode on DC/OS. DC/OS generates public certificates and private keys and stores them in the sandbox. But, for each task a different pair of public certificate and private key is generated. In this case, one needs to copy public certificate of all the servers into CAs folder of each server. But, it is not possible to access data of other task in a different instance of a Pod in DC/OS. Minio server should be configurable with TLS in this environment by incorporating necessary changes.

## Expected Behavior
Minio server should be configurable with TLS in distributed mode, if different public certificates are copied in _certs_ directory of each Minio server. There should be some way to eliminate the need of copying public certificates of other Minio servers to the _CAs_ of each Minio server.

## Current Behavior
Public Certificate of every Minio server needs to be copied to the _certs_ directory of each Minio server. It is not possible to copy the data of a task in one instance of a Pod to a task in another instance of the same Pod. 

## Context
Trying to implement Minio in distributed mode on DC/OS.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@ishanchandrajoshi Thanks for filing the issue. Have you had a chance to look into importing custom certificates onto DC/OS? https://docs.mesosphere.com/1.11/security/ent/tls-ssl/ca-custom/

**Comment by ishanchandrajoshi** [comment]
@kannappanr This link shows how to import Custom CA certificate in DC/OS. DC/OS can be configured to use either Custom CA certificate (which can be either root or an intermediate certificate) or DC/OS CA root certificate. By default, later is used to generate signed certificates for Admin Router and other components of DC/OS. 
The problem is not with DC/OS CA certificate since it is same across entire DC/OS (for each Pod and each task), but the signed public certificate which is unique for every task. 
Public certificate will be the concatenation of _public certificate_, any intermediates and root CA certificate. _public certificate_ is unique for every task.

**Comment by nitisht** [comment]
AFAIK @ishanchandrajoshi this was discussed on slack the problem was resolved by adding the `public.crt` file under `certs` directory, while certs for other servers under `certs/CAs` directory by adding files `public1.crt`, `public2.crt`, and so on.

**Comment by ishanchandrajoshi** [comment]
The problem was that in DC/OS we cannot copy the certs of other servers under certs/CAs because data transfer between Pods is not facilitated. However, the problem was solved by copying the DC/OS Certificate Authority's root certificate to the CAs folder of all the servers. I am closing this issue with this note.
