### ISSUE TITLE
Missing ETag in GET response

### ISSUE THREAD

**Issue by Self-Perfection** [minio/minio#6198]
I was using minio storage as external FS, filesystem behaviour was emulated by https://github.com/s3ql/s3ql . After recent s3ql upgrade something went wrong and s3ql now can't mount storage.

At first I supposed that the bug is on s3ql side (s3ql/s3ql#35) but further testing revealed, that minio does not provide `ETag` header in response to `GET /<bucketname>/<prefix>s3ql_passphrase`. Just in case: that object was created by s3ql and managed only by s3ql via s3 protocol.

I can create new FS with s3ql, response headers for new stored objects have `ETag`. Something is wrong with that old object. Also it is missing `Content-Type: application/octet-stream` header along with `ETag`.

Minio was updated last week from master, but it has not resolved the issue.

Why this might have happened? Is there any way to force minio to "rehash" existing objects?

**Comment by harshavardhana** [comment]
> I was using minio storage as external FS, filesystem behaviour was emulated by https://github.com/s3ql/s3ql . After recent s3ql upgrade something went wrong and s3ql now can't mount storage.
> 
> At first I supposed that the bug is on s3ql side (s3ql/s3ql#35) but further testing revealed, that minio does not provide ETag header in response to GET /<bucketname>/<prefix>s3ql_passphrase. Just in case: that object was created by s3ql and managed only by s3ql via s3 protocol.

@Self-Perfection how do you know ETag is missing? can you enable `export MINIO_HTTP_TRACE=/dev/stdout` to trace the incoming HTTP requests before starting the server and run s3ql?

**Comment by Self-Perfection** [comment]
@harshavardhana I recorded network traffic on client side with Wireshark and checked packet contents.

I have quite limited access to host which runs minio but I'll try to check from minio side as well.

**Comment by Self-Perfection** [comment]
Network traffic recorded on minio host confirms, that it does not send `ETag` header.

**Comment by harshavardhana** [comment]
> Network traffic recorded on minio host confirms, that it does not send ETag header.

Please paste the entire trace @Self-Perfection

**Comment by harshavardhana** [comment]
So I tried the latest s3ql seems to be working file with the latest Minio release

```
[REQUEST (objectAPIHandlers).GetObjectHandler-fm] [153245427.050060] [2018-07-24 10:44:30 -0700]
GET /testbucket/prefixs3ql_passphrase
Host: 127.0.0.1:9000
Connection: keep-alive
Date: Tue, 24 Jul 2018 17:44:30 GMT
Authorization: AWS minio:pJRo4Eu0wtq1/dTjvNL8hPYuShs=
Content-Length: 0
Accept-Encoding: identity

<BODY>

[RESPONSE] [153245427.050060] [2018-07-24 10:44:30 -0700]
200 OK
X-Amz-Request-Id: 15445F0A2BB64AA2
X-Amz-Meta-005: 'object_id': 's3ql_passphrase',
X-Amz-Meta-000: 'format_version': 2,
Last-Modified: Tue, 24 Jul 2018 17:43:32 GMT
Content-Type: application/octet-stream
X-Amz-Meta-002: 'encryption': 'AES_v2',
X-Amz-Meta-003: 'nonce': b'iYUmUdnV1kFzM3FsX3Bhc3NwaHJhc2U=',
X-Amz-Meta-004: 'data': b'rO3Few==',
Accept-Ranges: bytes
Content-Length: 132
Etag: "58b250326ae8a0c7800978029a212446"
X-Amz-Meta-001: 'compression': 'LZMA',
X-Amz-Meta-006: 'signature': b'YmtgkOd3OTwXZPDr4jcwkCbLjd7w9mrCTge6G3bTRn8=',
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
Server: Minio/DEVELOPMENT.2018-07-24T09-41-27Z (linux; amd64)
X-Amz-Meta-Format: raw2
X-Amz-Meta-Md5: tedZtdtPbzgRmjC3kxxoaw==
```

**Comment by Self-Perfection** [comment]
Here is entire conversation.
```
GET /backup/borg2s3ql_passphrase HTTP/1.1
Host: subgroup.org:9000
Date: Tue, 24 Jul 2018 17:23:06 GMT
Authorization: AWS <LOGIN>:<hash???>
Content-Length: 0
Accept-Encoding: identity
Connection: keep-alive

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 132
Content-Security-Policy: block-all-mixed-content
Last-Modified: Mon, 17 Apr 2017 22:39:58 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Meta-000: 'format_version': 2,
X-Amz-Meta-001: 'compression': 'LZMA',
X-Amz-Meta-002: 'encryption': 'AES_v2',
X-Amz-Meta-003: 'nonce': b'iOq< ... >ZQ==',
X-Amz-Meta-004: 'data': b'pZV6hg==',
X-Amz-Meta-005: 'object_id': 's3ql_passphrase',
X-Amz-Meta-006: 'signature': b'1W+Eu< ... >vWQ=',
X-Amz-Meta-Format: raw2
X-Amz-Meta-Md5: tyw< ... >Mw==
X-Amz-Request-Id: 15445DDF2511A643
X-Xss-Protection: 1; mode=block
Date: Tue, 24 Jul 2018 17:23:06 GMT
Content-Type: application/octet-stream

<binary content>
```

And ( I've mentioned in first post ) creating **new** fs works. But I can't mount **old** fs, that was created a year ago.

**Comment by harshavardhana** [comment]
> Last-Modified: Mon, 17 Apr 2017 22:39:58 GMT

This looks like there was a bug before and new s3ql is expecting ETag - you might have to recreate this file or manually edit `<backend_dir>/.minio.sys/buckets//backup/borg2s3ql_passphrase/fs.json`  for example

```
$ jq .  ~/test/.minio.sys/buckets/testbucket/prefixs3ql_passphrase/fs.json 
{
  "version": "1.0.2",
  "checksum": {
    "algorithm": "",
    "blocksize": 0,
    "hashes": null
  },
  "meta": {
    "X-Amz-Meta-000": "'format_version': 2,",
    "X-Amz-Meta-001": "'compression': 'LZMA',",
    "X-Amz-Meta-002": "'encryption': 'AES_v2',",
    "X-Amz-Meta-003": "'nonce': b'iYUmUdnV1kFzM3FsX3Bhc3NwaHJhc2U=',",
    "X-Amz-Meta-004": "'data': b'rO3Few==',",
    "X-Amz-Meta-005": "'object_id': 's3ql_passphrase',",
    "X-Amz-Meta-006": "'signature': b'YmtgkOd3OTwXZPDr4jcwkCbLjd7w9mrCTge6G3bTRn8=',",
    "X-Amz-Meta-Format": "raw2",
    "X-Amz-Meta-Md5": "tedZtdtPbzgRmjC3kxxoaw==",
    "content-type": "application/octet-stream",
    "etag": "58b250326ae8a0c7800978029a212446"
  }
}
```

**Comment by Self-Perfection** [comment]
It seems to me there is bug _now_ but I don't understand on which side.

Is `ETag` mandatory in response headers? If it is then minio should try to recover incorrectly stored objects and provide `ETag`. If `ETag` is optional, then s3ql should be able to work even if `ETag` is missing.

**Comment by harshavardhana** [comment]
> Is ETag mandatory in response headers? If it is then minio should try to recover incorrectly stored objects and provide ETag. If ETag is optional, then s3ql should be able to work even if ETag is missing.

ETag is not optional but from what it looks like this data is old and we perhaps had a bug at that point, so you can manually set this value and edit the file or re-create it. We still serve the data anyways in standalone mode without having these metadata.

**Comment by Self-Perfection** [comment]
I've updated `fs.json` files with missing 'etag' field with md5 of stored object. It seems that for a long period server runned minio version which does not store etags, and all or most of objects stored during that period missed etag in metadata.

This action resolved my issue! Now s3ql can successfully mount old FS.

Thank you for your advice.

**Comment by harshavardhana** [comment]
@Self-Perfection yes that is perhaps how it was 1.5yrs ago, going to close this issue though since we support generating proper etag's now.
