### ISSUE TITLE
minio heal dry-run does not detect corruption

### ISSUE THREAD

**Issue by tiasarea** [minio/minio#6201]
setup:
4 servers, 4 disks each
minio.RELEASE.2018-07-23T18-34-49Z  running on all of them to form a cluster

created 3 buckets.
uploaded a 1MB test file to cluster into one bucket
edited 1 file "part.1" replaced the first few bytes with '0' -> simulating silent corruption.

## Expected Behavior
running command: 
mc admin heal --dry-run -r myminiocluster
should say 1 object yellow or red or grey 
green 4 objects 80%
yellow or red or grey 1 object 20%

## Current Behavior
mc admin heal --dry-run -r myminiocluster
returns all objects green "green 5 objects 100%"

## Steps to Reproduce (for bugs)
described above

## Context
How has this issue affected you? What are you trying to accomplish?
I want to check my cluster for sanity and run a heal if needed

## Your Environment

* Version used (`minio version`):  minio.RELEASE.2018-07-23T18-34-49Z
* Environment name and version (e.g. nginx 1.9.1): Linux 64 bit Centos
* Server type and version: distributed minio setup
* Operating System and version (`uname -a`): Linux 64 bit Centos and Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

all 4 servers running same version of Centos, same level of patch, same minio version.
each of them have  4 disks of 24GB formatted on ext4.

**Comment by kannappanr** [comment]
@tiasarea Thanks for filing this issue. We will take a look and get back to you.

**Comment by eco-minio** [comment]
Confirmed this issue with 4x4 set up and 4x1 setup.  Issue occurs whether --dry-run flag is placed or not.  Also tried with --recursive which gives slightly different results.

```
 mc admin heal --dry-run -r repro
 ◓  ** unexpected **
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 4 │  80.0% ██████████   │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```
Not sure why we are returning "**unexpected**".  Since I had modified 8 of 16 part files, the calculations seem wrong as well.

**Comment by harshavardhana** [comment]
I ran minio master I am able to see if files are missing properly

```
 mc admin heal --dry-run -r myminio
 ◓  testbucket/issue
    0/1 objects; 24 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 1 │  33.3% ████         │
    │ Yellow │ 1 │  33.3% ████         │
    │ Red    │ 1 │  33.3% ████         │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

**Comment by harshavardhana** [comment]
and after editing a backend `part.1` file 

```
mc admin heal --dry-run -r myminio
 ◓  testbucket/issue
    0/1 objects; 24 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 2 │  66.7% ████████     │
    │ Yellow │ 1 │  33.3% ████         │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

**Comment by harshavardhana** [comment]
```

**Comment by harshavardhana** [comment]
```
--- heal corrupted file --- 
 prtsc : harsha : ~ : mc admin heal -r myminio
 ◓  testbucket/issue
    1/1 objects; 24 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
 --- edit the file again --- 
 prtsc : harsha : ~ : >/tmp/2/testbucket/issue/part.1 

--- now dry run reports it in yellow --- 
 prtsc : harsha : ~ : mc admin heal --dry-run -r myminio
 ◓  testbucket/issue
    0/1 objects; 24 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 2 │  66.7% ████████     │
    │ Yellow │ 1 │  33.3% ████         │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘

--- remove dry-run to heal the object properly --- 
mc admin heal -r myminio
 ◓  testbucket/issue
    1/1 objects; 24 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
 prtsc : harsha : ~ : ls /tmp/2/testbucket/issue/part.1
[2018-07-26 23:56:23 PDT]    12B part.1

```
