### ISSUE TITLE
Minio doesn't throw error message when there is an issue with Cert 

### ISSUE THREAD

**Issue by sureshpasupathi** [minio/minio#6202]
When minio is started in distributed mode with TLS certs, it doesn't throw an error when there is an issue with the way minio was started or if there is a mismatch on cert domain names.

## Expected Behavior

When minio is started with hostnames without fully qualified domain names (if that's what used in the cert), it simply keeps waiting for disks online instead of throwing en error saying it can't talk to peers because the domain name in the cert doesn't match with what's in the command that was invoked.

## Current Behavior

Simply waits for disks to come online infintely

## Possible Solution

1. Throw an error when there is a mismatch or issue with cert, instead of watching for peers to become online. 
2. Documentation needs to be updated to use exact hostnames (FQDN if necessary) when minio is started to match with what was used in the certificate.

## Steps to Reproduce (for bugs)

1. Copy certs to ~/.minio/certs folder (certs were created using FQDN, server.domain.com)

2.  Run minio distributed with the following command 
 export MINIO_ACCESS_KEY=<ACCESS_KEY>
export MINIO_SECRET_KEY=<SECRET_KEY>
minio server https://192.168.1.11/export1 https://192.168.1.12/export2 \
              https://192.168.1.13/export3 https://192.168.1.14/export4 \

Now you will see minio waiting for disks to come online. 
3. "curl https://node_ip:9000/" will provide you an hint about the cert issue.

curl: (51) Unable to communicate securely with peer: required domain name does not match the server's certificate.
4.

## Your Environment
Environment name and version (e.g. nginx 1.9.1):
Minio version
Version: 2018-07-13T00:09:07Z
Release-Tag: RELEASE.2018-07-13T00-09-07Z
Commit-ID: 2aa18ca

Server type and version:
VMware Virtual - 2 vCPU, 8GB RAM, 10gb OS disk

Operating System and version (uname -a):
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Linux lppbdsvmi04.phx.aexp.com 3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@sureshpasupathi Thanks for filing this issue. We will take a look at this and get back on how best we can address it.
