### ISSUE TITLE
There were headers present in the request which were not signed

### ISSUE THREAD

**Issue by atrauzzi** [minio/minio#6219]
_Opening a new ticket based on what I've discovered in #5857._

Generally, I'm getting the error "There were headers present in the request which were not signed" when trying to transfer copy files in minio.  In this case, from one bucket to another.

I'm using the AWS PHP SDK.  So I pass metadata to it and I assume it will handle things correctly, given that it's AWS who publishes the library. 😉 

At no point do I manually add headers, this is effectively what gets passed down to the AWS SDK in its options array:

```
        $options = [
            'Metadata' => array_merge(
                [
                    'organization_id' => $organizationId ?: '0',
                    'uploader_id' => $uploaderId,
                ],
                array_only($upload, [
                    'name',
                    'mime',
                ])
            ),
        ];
```

I think it's worth noting:
- I'm not explicitly creating a pre-signed URL.  I'm simply doing an upload.  So unless a pre-signed URL happens internally as part of this, I'm not sure why I'm getting this message from minio.
- If I comment out the entire metadata key, the requests work, with the obvious disadvantage at that point being that I can't set metadata on my objects.

---

Just to be sure, I pointed the exact same code at a real S3 bucket:

![image](https://user-images.githubusercontent.com/115199/43367875-9c2c263e-9319-11e8-8e15-9ac820534e5e.png)

No error, and my metadata is showing up as intended.

**Comment by harshavardhana** [comment]
Thanks @atrauzzi

**Comment by aarushiarya** [comment]
Hi @atrauzzi 

Can you provide a code snippet so that I can recreate this issue?

**Comment by Praveenrajmani** [comment]
Hey @atrauzzi ,
I tried passing `Metadata` in an UPLOAD request. It seems to work fine for me here

``` <?php

// Include the SDK using the Composer autoloader
date_default_timezone_set('America/Los_Angeles');
//require 'vendor/autoload.php';
require 'aws-autoloader.php';
use GuzzleHttp\Psr7;

$s3Client = new Aws\S3\S3Client([
        'version' => 'latest',
        'region'  => 'us-east-1',
        'endpoint' => 'http://192.168.86.117:9000',
        'use_path_style_endpoint' => true,
        'credentials' => [
                'key'    => 'minio',
                'secret' => 'minio123',
            ],
]);

// Upload with metadata
$insert = $s3Client->upload(
    'testbucket',
    'testkey',
    'Hello from Minio!!',
    'private',
    [ 'params' => [ 'Metadata' =>
                    [
                    'organization_id' => '0',
                    'uploader_id' => '123'
                    ]
    ]
]);

$result = $s3Client->headObject(['Bucket' => 'testbucket',
     'Key'    => 'testkey']);

// Print the metadata
print_r($result['Metadata']);

```
And i cannot see `options` as an attribute to put object request here in aws-sdk doc
[https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_putObject](url)

And i think you have missed the `params` keyword . Can you try with

```
$options = [ 'params' => [ 'Metadata' =>
                array_merge(
                [
                    'organization_id' => $organizationId ?: '0',
                    'uploader_id' => $uploaderId,
                ],
                array_only($upload, [
                    'name',
                    'mime',
                ])
            )
    ],
]
```



Or would be better if you share us the snippet used .

**Comment by aarushiarya** [comment]
This is the code snippet he used @Praveenrajmani - 

```
$this->filesBucket->putStream(
    $this->path($file, 'original'),
    $this->uploadsBucket->readStream($uploadId),
    $this->createStorageOptions($upload, $uploaderId, $organizationId)
);
```
 The storage options is the `options` mentioned in the ticket. He is using minio 2018-07-23T18:34:49Z, as a docker image.

There is no aws sdk php api calls in the snippet @atrauzzi provided.

**Comment by aarushiarya** [comment]
I tried `copyObject` with metadata and it works fine for me.

```

// Include the SDK using the Composer autoloader
date_default_timezone_set('America/Los_Angeles');
require 'vendor/autoload.php';

$s3 = new Aws\S3\S3Client([
        'version' => 'latest',
        'region'  => 'us-east-1',
        'endpoint' => 'http://localhost:9000',
        'use_path_style_endpoint' => true,
        'credentials' => [
                'key'    => 'minio',
                'secret' => 'minio123',
            ],
]);
 $options = array(
        'Bucket'          => 'mybucket',
        'CopySource'      => 'test/asiaPics',
        'Key'             => 'asiaPics',
        'ACL'             => 'public-read',
        'CacheControl'    => "max-age=60, public",
        'ContentType'     => 'text/plain',
        'ContentEncoding' => 'gzip',
        'Expires'         => '0', // 1 Jan 1970, 12:00am GMT
        'Metadata'        => array(
            'updated'        => '1', // x-amz-meta-updated
            'custom-header2' => '2', // x-amz-meta-custom-header2
            'custom-header3' => '3', // x-amz-meta-custom-header3
        ),
        'MetadataDirective' => 'REPLACE',
    );
    $result = $s3->copyObject($options);

    $meta = $s3->headObject(['Bucket' => 'mybucket',
    'Key'    => 'asiaPics']);
    
    // Print the metadata
    print_r($meta['Metadata']);

```

**Comment by atrauzzi** [comment]
Not sure what to say, it's still complaining about headers that were unsigned.

I have an nginx proxy in front of minio that I use to do layer-7 DNS mapping for local development, anything possible there?

**Comment by harshavardhana** [comment]
Could you share your nginx config ?

**Comment by atrauzzi** [comment]
@harshavardhana - Definitely:

```
server {

    listen 80;
    ssl off;

    server_name storage.local.mylocaldevdns;

    client_max_body_size 10M;
    dav_methods PUT;

    location / {

        proxy_pass http://docker.for.mac.host.internal:8078;
        proxy_set_header Host $host;
    }
}
```

Let me know if you want any other pieces of the puzzle, heh.

**Comment by harshavardhana** [comment]
Most probably you need more settings such as 

```
server {
 listen 80;
 server_name example.com;
 # To allow special characters in headers
 ignore_invalid_headers off;
 # Allow any size file to be uploaded.  
 # Set to a value such as 1000m; to restrict file size to a specific value
 client_max_body_size 0;
 # To disable buffering
 proxy_buffering off;
 location / {
   proxy_set_header Host $http_host;
   proxy_pass http://localhost:9000;
   health_check uri=/minio/health/ready;
 }
}
```

Can you apply these missing settings and let us know? especailly ` ignore_invalid_headers off;` should fix your problem.

**Comment by atrauzzi** [comment]
Hey @harshavardhana - It's been a bit, but I definitely will be trying this out shortly.  😄 

Will update with whether it works or not.

**Comment by harshavardhana** [comment]
@atrauzzi we will close this issue as working from our end, feel free to re-open that's not the case.

**Comment by atrauzzi** [comment]
I think we're good, thank you for sniffing this one out for me, greatly appreciated! 😄
