### ISSUE TITLE
403 Forbidden error while doing hadoop ls or distcp

### ISSUE THREAD

**Issue by tharnirav** [minio/minio#6220]
When trying to do haddop fs -ls to list files/folders (or distcp from minio to hdfs), minio server is throwing    403; Error Code: 403 Forbidden.  Its working at  bucket level and file level but fails at folder level.  

## Expected Behavior

Assume we have following folder structure 
bucket-a/folder-1/folder-2/test.txt

The following hadoop command 
       **hadoop fs -ls  s3a://bucket-a/folder-1/**
should result in
      **drwxrwxrwx   - hadoop hadoop          0 2018-07-31 15:01 s3a://bucket-a/folder-1/folder-2/**

## Current Behavior

The following hadoop command 
       **hadoop fs -ls  s3a://bucket-a/folder-1/**
results in
**ls: s3a://bucket-a/folder-1/: getFileStatus on s3a://bucket-a/folder-1/: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 153EDCF7025F0C95; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden**

In Minio server logs,  HEAD request results in 403 Forbidden error.  (Sensitive information is masked as XXXXX) 
v.f.Rb.P**HEAD /bucket-a/folder-1 HTTP/1.1**
Host: XXXXXXXXX:5432
User-Agent: Minio (freebsd; amd64) minio-go/5.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXX/20180712/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=XXXXXXXXXXX
X-Amz-Content-Sha256: XXXXXXXXXXXX
X-Amz-Date: 20180712T200809Z

16:08:09.076657 IP X.X.X.X.postgresql > X.X.X.X.18318: Flags [P.], seq 2698:3011, ack 2607, win 1026, options [nop,nop,TS val 1382202194 ecr 1990420141], length 313
E..m..@.@.4.
...
....8G..Z..ohU~.....Y.....
Rb.Rv.f.**HTTP/1.1 **403 Forbidden****
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2018-05-16T23-35-33Z (freebsd; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1540B7EA072C8177
X-Xss-Protection: "1; mode=block"
Date: Thu, 30 Jul 2018 20:08:09 GMT

## Steps to Reproduce (for bugs)

1.  Create a bucket and folders as follows,  bucket-a/folder-1/folder-2
2.  Update hadoop core-site.xml and setup fs.s3a.endpoint,  fs.s3a.access.key and fs.s3a.secret.key.
3. hadoop fs -ls  s3a://bucket-a/folder-1/

## Context

Trying to distcp data from minio to hdfs and same issues happens there.

## Your Environment

* Version used (`minio version`):  RELEASE.2018-05-16T23-35-33Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): freebsd; amd64
* Link to your project:  Hadoop jars are as follows
                 hadoop-common-3.1.0.jar
                 hadoop-aws-3.1.0.jar
                 aws-java-sdk-bundle-1.11.359.jar

**Comment by harshavardhana** [comment]
> Version used (minio version): RELEASE.2018-05-16T23-35-33Z

please use the latest version and let us know @tharnirav ?

**Comment by nitisht** [comment]
@tharnirav were you able to test this with latest Minio server?

**Comment by tharnirav** [comment]
We did version upgrade to 2018-06-22T23:48:46Z.  It results in same error.  
  
We did interception of requests being sent by hadoop clients as follows
**mkfifo infile
nc -lk 5432 <infile | tee -a testing | nc localhost 9700 | tee -a testing >infile**

When we run 
**hadoop fs -ls s3a://bucket-a/folder-1/**

We see the following logs

**HEAD /bucket-a/** HTTP/1.1
Host: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
x-amz-content-sha256: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-i
d;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
X-Amz-Date: 20180810T181906Z
User-Agent: Hadoop 3.1.0, aws-sdk-java/1.11.359 FreeBSD/11.1-RELEASE-p9 OpenJDK_64-Bit_Server_VM/25.162-b12 java/1.8.0_162
amz-sdk-invocation-id: a6797b26-0c40-94d7-50f9-e60b27a2958d
amz-sdk-retry: 0/0/500
Content-Type: application/octet-stream
Connection: Keep-Alive

**HTTP/1.1 200 OK**
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2018-06-22T23:48:46Z (freebsd; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 15472426BF2CC721
X-Xss-Protection: "1; mode=block"
Date: Thu, 10 Aug 2018 18:19:06 GMT

**HEAD /bucket-a/folder-1** HTTP/1.1
Host: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
x-amz-content-sha256: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXXXX/20180810/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-i
d;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X-Amz-Date: 20180810T181907Z
User-Agent: Hadoop 3.1.0, aws-sdk-java/1.11.359 FreeBSD/11.1-RELEASE-p9 OpenJDK_64-Bit_Server_VM/25.162-b12 java/1.8.0_162
amz-sdk-invocation-id: a8954947-7d40-3d71-beda-3cef9533e55d
amz-sdk-retry: 0/0/500
Content-Type: application/octet-stream
Connection: Keep-Alive

**HTTP/1.1 403 Forbidden**
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2018-06-22T23:48:46Z (freebsd; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 15472426C1FC0E60
X-Xss-Protection: "1; mode=block"
Date: Thu, 10 Aug 2018 18:19:07 GMT

**Comment by tharnirav** [comment]
Any update on the issue?

**Comment by sinhaashish** [comment]
@tharnirav  . Can you share the configuration of core-site.xml. 
I tried with minio version `RELEASE.2018-08-25T01-56-38Z`  and the below configuration in `core-site.xml` and it is working fine for me.

```
<configuration>
  <property>
    <name>fs.s3a.endpoint</name>
    <description>AWS S3 endpoint to connect to. An up-to-date list is
      provided in the AWS Documentation: regions and endpoints. Without this
      property, the standard region (s3.amazonaws.com) is assumed.
    </description>
    <value>http://127.0.0.1:9000</value>
  </property>

  <property>
    <name>fs.s3a.access.key</name>
    <description>AWS access key ID.</description>
    <value>minio</value>
  </property>

  <property>
    <name>fs.s3a.secret.key</name>
    <description>AWS secret key.</description>
    <value>minio123</value>
  </property>

  <property>
    <name>fs.s3a.path.style.access</name>
    <value>true</value>
    <description>Enable S3 path style access ie disabling the default virtual hosting behaviour.
      Useful for S3A-compliant storage providers as it removes the need to set up DNS for virtual hosting.
    </description>
  </property>

  <property>
    <name>fs.s3a.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    <description>The implementation class of the S3A Filesystem</description>
  </property>
</configuration>
```


Attaching the snap shot for the same.
![hadoop-s3](https://user-images.githubusercontent.com/13465383/44835211-1fc2f900-ac51-11e8-89f6-d0e0c5e19ed1.jpg)

**Comment by tharnirav** [comment]
@nitisht ,
Find below core-site.xml  we have.  Have masked confidential details with XXXXX.  We have nginx in front of Minio hence pointing to port 5432.

Also could chat the version of Minio server and hadoop jars you used in you test?

```
  <property>
    <name>fs.s3a.endpoint</name>
    <description>AWS S3 endpoint to connect to. An up-to-date list is
      provided in the AWS Documentation: regions and endpoints. Without this
      property, the standard region (s3.amazonaws.com) is assumed.
    </description>
    <value>http://XXXXXX:5432</value>
  </property>

  <property>
    <name>fs.s3a.access.key</name>
    <description>AWS access key.</description>
    <value>XXXXX</value>
  </property>

  <property>
    <name>fs.s3a.secret.key</name>
    <description>AWS secret key.</description>
    <value>XXXXXXX</value>
  </property>

  <property>
    <name>fs.s3a.path.style.access</name>
    <value>true</value>
    <description>Enable S3 path style access ie disabling the default virtual hosting behaviour.
      Useful for S3A-compliant storage providers as it removes the need to set up DNS for virtual hosting.
    </description>
  </property>

  <property>
    <name>fs.s3a.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    <description>The implementation class of the S3A Filesystem</description>
  </property>
```
 
Thanks
Nirav Thar.

**Comment by sinhaashish** [comment]
@tharnirav   I  have used the below
Minio version : `RELEASE.2018-08-25T01-56-38Z`
Hadoop version : `hadoop-3.1.1`
Can you share the nginx config. We can verify it once; as minio is working fine without nginx

**Comment by nitisht** [comment]
closing due to no response @tharnirav please do let us know when you can verify this

**Comment by mrveera** [comment]
Hey 
I am facing the same issue with the following config
Minio version:`  2018-06-22T23:48:46Z`
Hadoop version: `Hadoop 3.1.0`

**Comment by harshavardhana** [comment]
All later releases of Minio has this fixed please upgrade.

**Comment by mrveera** [comment]
Thanks

**Comment by lmf5103510** [comment]
minio Version: 2019-06-04T01:15:58Z
Hadoop 3.1.2
still get this issue:

Working with:
hadoop fs -ls  s3a://spark-new/

show me :

Found 1 items
-rw-rw-rw-   1 root root          5 2019-06-09 22:48 s3a://spark-new/test.json

while:
hadoop fs -ls  s3a://spark-new/test.json

ls: s3a://spark-new/test.json: getFileStatus on s3a://spark-new/test.json: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden

**Comment by nitisht** [comment]
@lmf5103510 please create a new issue with details
