### ISSUE TITLE
NAS gateway fails to update policy

### ISSUE THREAD

**Issue by cfmanteiga** [minio/minio#6223]
With the latest version, RELEASE.2018-07-31T02-11-47Z, using NAS gateway, minio fails to update any bucket policy.

## Expected Behavior

The bucket policy should change. Old version RELEASE.2018-07-31T02-11-47Z works.

## Current Behavior
mc client hangs trying to modify the policy. Server gives 500

## Steps to Reproduce (for bugs)
1. Set up an NFS server, and export some directory
2. Mount that directory in /export
3. Start minio as a NAS gateway: minio gateway nas /export
4. Create a bucket: mc mb mynas/test
5. Apply download policy to that bucket: mc policy download mynas/test

5th step gives:

Client: 
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/test/</Resource><RequestId>1546C87CF59EF893</RequestId><HostId>3L137</HostId></Error>
```
Server:
```
API: SYSTEM()
Time: 16:18:43 CEST 08/01/2018
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
       2: cmd/fs-v1.go:870:cmd.(*FSObjects).putObject()
       3: cmd/fs-v1.go:780:cmd.(*FSObjects).PutObject()
       4: cmd/notification.go:538:cmd.saveConfig()
       5: cmd/policy.go:216:cmd.savePolicyConfig()
       6: cmd/fs-v1.go:1230:cmd.(*FSObjects).SetBucketPolicy()
       7: cmd/bucket-policy-handlers.go:88:cmd.objectAPIHandlers.PutBucketPolicyHandler()
       8: cmd/api-router.go:103:cmd.(objectAPIHandlers).PutBucketPolicyHandler-fm()
       9: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

## Your Environment

* Version used (`minio version`): 
Version: 2018-07-31T02:11:47Z
Release-Tag: RELEASE.2018-07-31T02-11-47Z
Commit-ID: dbd89bbae33c70175e1f7ca1b7897e8a2fe84f90
* Environment name and version (e.g. nginx 1.9.1): no proxy used
* Server type and version: NAS gateway
* Operating System and version (`uname -a`): 
CentOS Linux release 7.5.1804 (Core)
Linux miniotest 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project: not needed

**Comment by nitisht** [comment]
Thanks for reporting @cfmanteiga we'll take a look soon

**Comment by cfmanteiga** [comment]
master fixes this issue. Thank you!
