### ISSUE TITLE
request: optionally permit all available TLS ciphers

### ISSUE THREAD

**Issue by grumpy42** [minio/minio#6225]
NewServer() in  cmd/http/server.go  has a liimited number of preferred TLS cipher suites.
This prevents some older clients (like Cloudberry or DragonDisk) from negotiating connections.

It would be helpful if there was an option to allow all available TLS ciphers, even the ones which are now considered weak, in order to allow the older clients to connect. in our enclosed networking environment we are not as concerned about the potential vulnerability of the older ciphers as we would normally be if our clients and servers were exposed to the outside world.

As an example, with the attached diffs, if the environment variable "MINIO_SERVER_CIPHERS" is set to "false", then NewServer() will not limit to the cipher suite list contained in cmd/http/server.go, and the older clients are able to connect.

Please excuse code quality - first time working with Go.
Please excuse if this is not the appropriate place for feature requests -- first time using GitHub.
[minio-cipherpref-pch.txt](https://github.com/minio/minio/files/2250513/minio-cipherpref-pch.txt)

**Comment by harshavardhana** [comment]
We will not be doing this or allow @grumpy42 - the ciphers which are disabled has security issues. If you are using software which requires these ciphers they are vulnerable as well.

**Comment by grumpy42** [comment]
okay, no problem.  I had hoped this could be included as an optional feature - for those in secure environments - while waiting for the clients to update their required ciphers. oh well, thanks for your time.
