### ISSUE TITLE
Wrong validation of connectionString in notify.postgreSQL 

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#6226]
## Expected Behavior
Putting connectionString: "sslmode=disable" in notify.postgreSQLshould work

## Current Behavior
Putting connectionString: "sslmode=disable" shows a validation error and prevents Minio from starting

## Possible Solution
Fix validation of connectionString

## Steps to Reproduce (for bugs)
Putting the following json in ~/.minio/config.json

```
 98                 "postgresql": {
 99                     "1": {
100                         "enable": true,
101                         "format": "namespace",
102                         "connectionString": "sslmode=disable",
103                         "table": "bucketevents",
104                         "host": "127.0.0.1",
105                         "port": "5432",
106                         "user": "postgres",
107                         "password": "postgres",
108                         "database": "minio_events"
109                     }
110                 },
```

## Context
Fixing a bug

## Your Environment
All

**Comment by olegbukatchuk** [comment]
+1
