### ISSUE TITLE
Improving Heal performance by allowing parallel heal

### ISSUE THREAD

**Issue by eyalrif** [minio/minio#6241]
When performing Heal on large OBS with a huge amount of small files it can take an extremely long time to complete. 

In our case with have a 60TB OBS with 1MB objects which translate to 60 Million objects. heal manage to process around 10GiB an hour (the setup is with 36 disks). this means that the healing process can take several weeks which isn't reasonable.
This is due to the fact that Minio is processing one object at a time.

in order to allow better performance and give the admin more flexibility, a flag should be added to "mc" which will allow parallelism of the heal operation. Ideally, the parallelism can be changed while the process is running.

This will allow the admin to decide when to give more resources to the "heal" process without affecting the ongoing operation of the cluster 

The way to reproduce the issue is building Minio cluster with a large number of small objects in one bucket and run recursive heal on the entire bucket.

## Your Environment

* Version used (`minio version`): 
Version: 2018-07-23T18:34:49Z
Release-Tag: RELEASE.2018-07-23T18-34-49Z
Commit-ID: 5acc2a6db1fae9923139dfdfab6faa5de48deb73
* Server type and version: 
6 servers with 6 disk of 4TB is on each server
* Operating System and version (`uname -a`): 
3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@eyalrif Thanks for filing this issue. We will talk internally and see how we can best address this issue.
