### ISSUE TITLE
500 Internal Server Error encountered when overloading Minio Cluster

### ISSUE THREAD

**Issue by eyalrif** [minio/minio#6248]
While running high volume activity on Minio Cluster(4 nodes, 48 buckets) we get "Internal Server Error" and not able to write to the OBS

`diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-[RESPONSE] [153305335.825221] [2018-07-31 19:09:33 +0300]
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log:500 Internal Server Error
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-Vary: Origin
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-X-Xss-Protection: 1; mode=block
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-Content-Security-Policy: block-all-mixed-content
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-X-Amz-Request-Id: 15467FE82856F4A8
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-Server: Minio/DEVELOPMENT.2018-07-30T06-57-50Z (linux; amd64)
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-Accept-Ranges: bytes
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-Content-Type: application/xml
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-<?xml version="1.0" encoding="UTF-8"?>
diagnostics//REG-74737-V31MMOBS00-76985-minio-11/minio-http.log-<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/wekabucket-5/16f24144/d/d/83/1/2165/0f6a-4526-ad5b-3bedb27c7b13</Resource><RequestId>15467FE82856F4A8</RequestId><HostId>3L137</HostId></Error>`

`Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: 1: cmd/erasure-readfile.go:43:cmd.ErasureStorage.readConcurrent.func1()
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: API: GetObject(bucket=wekabucket-6, object=16f24144/d/d/97/2/321/0f6a-4526-ad5b-3bedb27c7b13)
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: Time: 19:37:25 IDT 07/31/2018
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: RequestID: 154681706B8E47D4
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: RemoteHost: 172.31.62.246
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: UserAgent: APN/1.0 WEKA/1.0 WEKASCALE/V3.1.0.0
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: Error: disk not found
Jul 31 19:37:25 REG-74737-V31MMOBS00-76985-minio-11 minio: 1: cmd/erasure-readfile.go:43:cmd.ErasureStorage.readConcurrent.func1()`

The issue is reproducible on Lab - environment will be supplied on request

## Context
This is a blocker - we cannot deploy the system in production with this issue

## Your Environment
Minio
4 nodes, 6 disks * 2TB on each node

**Comment by nitisht** [comment]
Thanks for reporting @eyalrif we'll take a look ASAP

**Comment by harshavardhana** [comment]
How many clients were actively connected here @eyalrif? do you have your server `ulimit -n` set to 65535?  - this is total number of open fd's concurrently a server can have.

**Comment by eyalrif** [comment]
we have 8 clients (Weka Nodes) that are connected to Minio Cluster. 
This is the value we set on Minio Hosts:
[root@minio-reprod-xfs-minio-11 ~]# ulimit -n
530000

**Comment by harshavardhana** [comment]
> we have 8 clients (Weka Nodes) that are connected to Minio Cluster.
> This is the value we set on Minio Hosts:
> [root@minio-reprod-xfs-minio-11 ~]# ulimit -n
> 530000

@eyalrif is the backend ext4 here or xfs? any errors in dmesg, kernel logs when running ext4?

**Comment by kannappanr** [comment]
@eyalrif I tried to reproduce the error by setting the `ulimit -n` to a very low number and did some `mc cp` commands and was able to reproduce the `too many open files` error, but was unable to receive any `500` status code. I got `503` status code, which is appropriate.

**Comment by harshavardhana** [comment]
@eyalrif I think after latest release this is not reproducible but we do have issues of running out of sockets on the server. should we open a new issue for that or do we continue to track this?

**Comment by kannappanr** [comment]
@eyalrif Closing this issue as fixed with the recent release. Please feel free to open a new issue if you see any other issue.
