### ISSUE TITLE
Implement support for range get in minio gateway while caching

### ISSUE THREAD

**Issue by deekoder** [minio/minio#6250]
Sometimes customers who use the caching feature in minio gateway want the cache to support a range get request of specific size.

## Expected Behavior
 Instead of caching the full object, have control over how much of the object needs to be cached.

## Current Behavior
 Full objects only caching support.

## Possible Solution
None

## Steps to Reproduce (for bugs)
 N/A this is not a bug. It's an enhancement request.

## Context
Ask from user that's interested in caching feature in minio. Filed here for addressing later.
 
## Your Environment
 N/A

**Comment by harshavardhana** [comment]
Before we do this we need to review #6265 first.

**Comment by harshavardhana** [comment]
Fixed by #7694
