### ISSUE TITLE
Can not upload file larger than 1MB

### ISSUE THREAD

**Issue by huytn** [minio/minio#6255]
After upgrade from "Version: 2016-12-13T17:19:42Z" to "Version: 2018-08-02T23:11:36Z"

![screen shot 2018-08-07 at 2 51 19 pm](https://user-images.githubusercontent.com/5128892/43763201-575ce68c-9a54-11e8-9876-4bf072108ba6.png)

**Comment by vadmeste** [comment]
@huytn if you are using nginx, you should configure it to allow large upload (client_max_body_size) as mentioned here https://docs.minio.io/docs/setup-nginx-proxy-with-minio.html

**Comment by huytn** [comment]
@kmkanagaraj:
+Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
+Nginx: 1.11.8
+Golang: 1.7.4 linux/amd64
+Minio
   - mode: distributed
   - version: 2018-08-02T23:11:36Z

@vadmeste It works now
Thanks you all
