### ISSUE TITLE
EOF on fs.json when listing objects

### ISSUE THREAD

**Issue by byaminov** [minio/minio#6256]
I somehow occasionally get corrupted `fs.json` file in our environment: it has 0 bytes size. As a result the listing of files in that directory fails, including recursive listing from parent directory.

## Expected Behavior
* Metadata files (`fs.json`) should not get corrupted
* If they do it should not prevent a file from being read, although without proper metadata.
* If they do it should not prevent a directory from being listed, although without proper metadata for that corrupted file.
* If they do then the log file should say which file is corrupted.

## Current Behavior
When doing a (recursive) listing of a directory containing the file there are 0 results returned and following error printed on the Minio server logs:
```
API: ListObjectsV2(bucket=some-bucket)
  | Time: 07:57:42 UTC 08/07/2018
  | RemoteHost: 10.128.4.7
  | UserAgent: Minio (x86_64; x86_64) minio-java/dev
  | Error: EOF
  | 1: cmd/fs-v1-metadata.go:252:cmd.(*fsMetaV1).ReadFrom()
  | 2: cmd/fs-v1.go:673:cmd.(*FSObjects).getObjectInfo()
  | 3: cmd/fs-v1.go:1111:cmd.(*FSObjects).ListObjects.func1()
  | 4: cmd/fs-v1.go:1155:cmd.(*FSObjects).ListObjects()
  | 5: cmd/fs-v1.go:1248:cmd.(*FSObjects).ListObjectsV2()
  | 6: cmd/bucket-handlers-listobjects.go:89:cmd.(ObjectLayer).ListObjectsV2-fm()
  | 7: cmd/bucket-handlers-listobjects.go:96:cmd.objectAPIHandlers.ListObjectsV2Handler()
  | 8: cmd/api-router.go:99:cmd.(objectAPIHandlers).ListObjectsV2Handler-fm()
  | 9: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

For me it happens occasionally and can be fixed manually: by tracking down under which path the corrupt file appears, and then removing the corrupt `fs.json` file. It happens once per week on average, but I don't know what is the cause.

## Context
I'm running Minio in Kubernetes (OpenShift), and the `/data` folder is a mounted NFS share.

First I tried running Minio as a server: `server /data` and had these issues. Then I tried running it as a gateway: `gateway nas /data`, but getting the same problems now.

Does maybe Minio not support such a configuration: having filesystem as a mounted NFS share? Obviously NFS is not as reliable as normal disk. I was hoping that when running as a gateway it would not create own system files like `fs.json` and would be more reliable, but it still does. And somehow these metadata files tend to get corrupted from time to time.

## My Environment
* Version used (`minio version`): `RELEASE.2018-07-13T00-09-07Z`
* Running in standalone, `gateway nas` mode
* Environment name and version:
  * OpenShift v3.7.46
  * Kubernetes v1.7.6
  * NFS 4
* NFS server is running on the same network, same data center. Normally network is fast, here's for example time to read a 15 Mb file from Minio container:
```
30076+1 records in
30076+1 records out
real	0m 0.04s
user	0m 0.00s
sys	0m 0.03s
```

**Comment by kannappanr** [comment]
@byaminov Thanks for reporting this issue. We will take a look and get back to you.

**Comment by harshavardhana** [comment]
> I'm running Minio in Kubernetes (OpenShift), and the /data folder is a mounted NFS share.

is the NFS share here using NFSv3 ? or v4? what is the server implementation is it kernel NFS, any proprietary NAS vendors? @byaminov

**Comment by harshavardhana** [comment]
We write `fs.json` in O_SYNC mode such that the file is always synced to disk regardless of the writes/failures. So `0` bytes shouldn't be possible in the first place unless NFS is faking O_SYNC and still caching the files on the client. 

Have you had any server restarts, NFS share disconnections etc while the active I/O is in progress?

**Comment by byaminov** [comment]
@harshavardhana sorry for a late response, was on vacation.
> is the NFS share here using NFSv3 ? or v4?

It is NFSv4
> what is the server implementation is it kernel NFS, any proprietary NAS vendors?
```
NAS solution: openmediavault
Version: 3.0.99 (Erasmus) - https://www.openmediavault.org/?p=2260
OS: Debian.
Kernel: Linux 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.82-1+deb9u3~bpo8+1 (2018-03-22) x86_64
```
> Have you had any server restarts, NFS share disconnections etc while the active I/O is in progress?

Not that I know of, but I cannot say for sure that there was no restart.

In any case thanks a lot for the fix! Now even if a single file gets corrupted it won't break the directory listing anymore.

**Comment by harshavardhana** [comment]
I think the problem is that your NFS server is not honoring O_SYNC mode otherwise we will never get empty `fs.json`

**Comment by byaminov** [comment]
Thanks for the advice, I'll try to add it and see if it helps!
