### ISSUE TITLE
How to protect SecretKey in my js client app?

### ISSUE THREAD

**Issue by lhysrc** [minio/minio#6260]
## Expected Behavior

I want to use **minio js client** in my Angular App, but the AccessKey and SecretKey is not safe neither in code or config asset file. 

## Possible Solution

Is there a way to get a key for a short time to access the minio server (just like jwt)? So I can get the key  by the backend server.

**Comment by harshavardhana** [comment]
Never use secret key on browsers, use presigned URL by generating it on the server https://github.com/minio/minio-js#api-reference--presigned-operations

**Comment by kannappanr** [comment]
@lhysrc Clsoing this issue as answered. Please feel free to reach out to us, if you have further questions.
