### ISSUE TITLE
Enable SSE-{S3, C} encryption at the gateway 

### ISSUE THREAD

**Issue by aead** [minio/minio#6267]
This is a design and tracing issue for enabling SSE at the gateway.

## Expected Behavior

 There will be 3 variants of gateway SSE:
1. **Passthrough Mode**: The gateway passes any SSE-related header to the gateway backend
   without en/decrypting the object itself. (This is current behavior)
2. **Local Mode**: The gateway handles SSE-{S3, C} (maybe SSE-KMS in the future) itself and
    encrypts the object at the gateway server. The backend never sees a plaintext object nor the
    SSE-related headers. The object looks like a plain object for the backend. It's the gateway's
    responsibility to convert internal metadata (`X-Minio-Internal-`) into backend metadata (e.g.
    `X-Amz-Meta-`) and vice versa.
3. **Combined Mode**: Combines 1. and 2. - also referred as "double encryption". The gateway
   handles SSE requests like described in 2. but also passes the SSE headers to the gateway
   backend.
   For SSE-C the gateway **must** derive a new SSE-C client key from the client-provided key.
   using a RO / PRF. Otherwise the backend learns the client key and would be able to decrypt
   the object -> defeats the purpose of **Local Mode**.

## Current Behavior

The gateway passes the any SSE-related headers to the backend and **hopes** that it supports
encryption.

## Possible Solution / TODOs

 - A configuration option / env. variable is required to determine the gateway mode (Passthrough,
Local, Combined)
- The **Local Mode** must be enabled for gateway implementations (See: `IsEncryptionSupported`)
- `ObjectLayer` interface needs refactoring to support passing down the SSE type (and values).
   There must be a way to tell the gateway it should set e.g. SSE-C headers for a `GET`- right now this
   is not possible. A **generic** and **clean** design should be the goal here instead of adding (yet) 
   another parameter.
- `IsEncryptionSupported` should be refactored. All `ObjectLayer` implementations will support 
   encryption - the question is which one.

## Context
SSE, KMS, security

## Your Environment
master

**Comment by poornas** [comment]
@aead, discussed this with @abperiasamy. 
For gateway, the env. variable MINIO_GW_SSE="S3;CLIENT;KMS" will determine how the gateway handles SSE requests. Basically absence of this variable will be a passthru, and presence will indicate double encryption. Since local mode is a subset of combined mode and provides double encryption without any extra work, it makes sense to eliminate the local mode variant.

**Comment by aead** [comment]
@poornas Okay.
Two remarks here:
1. SSE-C terminated on the server and SSE-C applied twice (double encryption) have slightly different
    security implications (in add. to the obvious differences): 
    - In SSE-C (terminated) the backend is not (directly) aware of an encrypted object. It can detect by 
      looking at the headers. But even if it does it cannot tell which client key (and maybe which user if    
      the client key is related to an user) is used to encrypt the object. In SSE-C (double) the SSE-C 
      backend is able to detect which objects are encrypted with the *same* key (consequently which 
      objects are encrypted with different keys). In SSE-C (double) we cannot hide that information from the backend. This property allows the backend to track keys (and maybe users depending on the user-key relation).
     This is a weaker security guarantee depending on the threat-model.
2. If a user first configures the server using e.g. MINIO_GW_SSE="CLIENT", uploads `n` objects and later configures e.g. `MINIO_GW_SSE="S3"` the following will happen:
    - The user will send the client-key to the gateway which forwards it to the backend. Now the  
      backend learns the client key and can decrypt the object.
    - The user will get an error for SSE-C requests since it provides the client key which will be 
      forwarded to the backend. But during uploads the SSE-C key H(client-key) was sent to the 
     backend so the key does not match.

From a security point of view: We should not allow to turn of double-encryption for SSE-C once it's enabled because a) the user "cannot" decrypt the object (without behaving like the gateway) and b)
the user would reveal the client-key to the backend which compromises (at least) that object.
However, I don't see how to enforce that -> We should **explicitly** document that disabling SSE-C double encryption again compromise security.

**Comment by poornas** [comment]
@aead, agree.

**Comment by poornas** [comment]
this issue can be closed @kannappanr

**Comment by kannappanr** [comment]
Closing this issue as double encryption support at S3 Gateway layer has been merged.
