### ISSUE TITLE
Time to prune minio repository

### ISSUE THREAD

**Issue by fwessels** [minio/minio#6268]
Maybe it is time to prune the minio repository?

```
$ git clone https://github.com/minio/minio.git
Cloning into 'minio'...
remote: Counting objects: 38812, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 38812 (delta 14), reused 12 (delta 11), pack-reused 38793
Receiving objects: 100% (38812/38812), 38.59 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (25396/25396), done.
```

**Comment by aead** [comment]
Ref: #4812 - `minio/minio` repo organization is not idomatic w.r.t Go's conventions.

**Comment by harshavardhana** [comment]
#4812 is not relevant here. Most of the data / code in Minio repo is in vendor directory which increases by each new feature. 
 
I don't think this issue is relevant,  we cannot prune the vendor directory and repo size is currently intentional.

**Comment by fwessels** [comment]
I was thinking more of reducing the overall “download” size of the repo, not necessarily reorganizing it.

**Comment by aead** [comment]
@harshavardhana go modules (Go 1.11) at least for "official" packages like `x/net`, `x/crypto`?
Or large projects (vault)...

**Comment by harshavardhana** [comment]
> @harshavardhana go modules (Go 1.11) at least for "official" packages like x/net, x/crypto?
> Or large projects (vault)...

Perhaps in future, yes but for now vendorizing is the primary cause of this.

**Comment by fwessels** [comment]
Ok, let’s leave it as is then. Closing the issue.
