### ISSUE TITLE
minio over caddy reverse proxy dont work

### ISSUE THREAD

**Issue by os-studio** [minio/minio#6269]
Caddyfile:
```
https://upload.domain.de {
  proxy / localhost:9100 {
    transparent
    websocket
  }
}
```
minio server startcommand:
`./minio server --address ":9100" /mnt/data
`

Error-Response from Webbrowser

` SSL required`

i really dont know but i tryed many things it wont work

When i edit the Caddyfile to:
```
http://upload.domain.de {
  proxy / localhost:9100 {
    transparent
    websocket
  }
}
```
i get 

`502 Bad Gateway`

When i start minio with:
`./minio server --address "localhost:9100" /mnt/data`

and edit the caddyfile to:
```
upload.domain.de

proxy / localhost:9100 {
    header_upstream X-Forwarded-Proto {scheme}
    header_upstream X-Forwarded-Host {host}
    header_upstream Host {host}
    health_check /minio/health/ready
}
```
i get
`502 Bad Gateway`

What i'm doing wrong?

## Your Environment

* Version used (`minio version`): latest
* Environment name and version (e.g. nginx 1.9.1): Caddy Reverse Proxy (Port to Domain)
* Server type and version: Testing Server
* Operating System and version (`uname -a`):
3.10.0-123.4.2.el7.x86_64 #1 SMP Mon Jun 30 16:09:14 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:
-

**Comment by nitisht** [comment]
Do you have TLS enabled @Meerbi , also have you seen https://docs.minio.io/docs/setup-caddy-proxy-with-minio.html

**Comment by os-studio** [comment]
Yes. I have tryed it exacly like the Docs and with my own way but it wont work

**Comment by nitisht** [comment]
> I have tryed it exacly like the Docs and with my own way but it wont work

Thanks @Meerbi we'll try to reproduce this locally

**Comment by nitisht** [comment]
@Meerbi can you try 

```
https://upload.domain.de {
  proxy / https://localhost:9100 {
    header_upstream X-Forwarded-Proto {scheme}
    header_upstream X-Forwarded-Host {host}
    header_upstream Host {host}
    health_check /minio/health/ready
  }
}
```

**Comment by harshavardhana** [comment]
We can perhaps close this issue @nitisht

**Comment by nitisht** [comment]
closing this @Meerbi , do let us know if there are problems with the suggested approach.
