### ISSUE TITLE
Browser shows incorrect space "Used", and no info for "Free"

### ISSUE THREAD

**Issue by PerMildner** [minio/minio#6272]
## Expected Behavior

Expect "Used" and "Free" to be present in the Minio Browser, as in the screenshot at https://docs.minio.io/docs/minio-quickstart-guide.html

## Current Behavior

Browser shows only "Used: 808 bytes" (no "Free") and this count is obviously wrong.

![screen shot 2018-08-12 at 17 10 57](https://user-images.githubusercontent.com/1358238/44003591-fb629f20-9e54-11e8-8042-edc25a876f5b.png)

## Steps to Reproduce (for bugs)

1. Started minio from command line pointing at a folder on an external USB disk. Did no configuration except created a bucket in the browser.
2. Started backup with Duplicati pointed at the minio server.
3.
4.

## Your Environment

* Version used (`minio version`):
-bash$ minio_test/minio version
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
macOS X 10.11.6
* Link to your project:

**Comment by kannappanr** [comment]
@PerMildner Thanks for filing this issue. We recently made some changes and have removed Free space display from the browser. We also calculate the used space in the background once every twelve hours. Until it is done calculating, it will display the current calculated number. I will check to see if we can display something like the value is not final and the used space is being calculated. I will also make sure that the image reflects the current behavior.

**Comment by harshavardhana** [comment]
@PerMildner this is as per the design of Minio's multi-tenant deployment scenarios. Once we bring in quota requirements in Minio we will bring back Free/Total values as well. For the time being `Used` is here to stay.

**Comment by PerMildner** [comment]
I understand why "Free" is gone. I was surprised by the incorrect "Used", but that was explained above. Thanks for looking into this.

**Comment by nitisht** [comment]
Closing this as answered @PerMildner . Feel free to reach out on https://minio.slack.com for further questions

**Comment by ahsan2132** [comment]
Hello guys, I have a question.

How can we check the available storage on minio? I have mounted the minio volume behind a gkuster.

**Comment by zhiqihuang** [comment]
I encountered the same issue. Is there a solution now? I'm using the most recent minio

**Comment by harshavardhana** [comment]
This is on purpose to look for free and available space look at the Prometheus metrics, MinIO browser is not for monitoring.

**Comment by muzammel111** [comment]
I am facing the same issue, wrong value of Used space, when the fix will incorporated ?. Its put bad impression on users, i suggest until the fix its remove from the browser.
