### ISSUE TITLE
When trying to push a new docker image to minio server with gcs gateway, docker registry fails to upload

### ISSUE THREAD

**Issue by bearmoo-cloud-net** [minio/minio#6273]
When trying to push a new docker image to minio in gateway mode for gcs. It fails to upload, and docker is stuck retrying again.

## Expected Behavior
It should be able to push the image though gcs with out any issues. Another note, I have minio as regular server setup and it works fine with docker private registry.

## Current Behavior
docker push docker.bearmoo.net:5000:some-image
registry will try to push it, but fails and re-tries.

## Steps to Reproduce (for bugs)

1. setup minio gateway so that it points to gcs storage.
2. setup docker registry so that it points to minio
3. docker push docker.bearmoo.net:5001/some-images
4.

## Context

It's making me having to depend on expensive cost of PD storage in gcs. Trying to achieve a better state of stateless in my environment
.
## Your Environment

* Version used (`minio version`):
/ # minio version
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a

* Environment name and version (e.g. nginx 1.9.1):
docker registry 2.6
* Server type and version:
google cloud instance g1-small

* Operating System and version (`uname -a`):
Linux storage-gcs 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by kannappanr** [comment]
@bearmoo-repo Thanks for filing this issue. We will try to reproduce and will get back to you if we have additional questions.

**Comment by bearmoo-cloud-net** [comment]
Thanks. If you need more info just let me know.

**Comment by harshavardhana** [comment]
have you tried to use https://docs.docker.com/registry/storage-drivers/gcs/ @bearmoo-repo as a work-around?

**Comment by bearmoo-cloud-net** [comment]
No I have not. My goal is too use minio to access any s3 (ie, aws, google, etc...) and be s3 agnostic as possible and not have worry about have different configurations to access storage. Is there a limitation I should be aware of with gcs + docker + minio?

**Comment by krisis** [comment]
@bearmoo-repo could you attach error messages you noticed when the docker image upload failed?

**Comment by bearmoo-cloud-net** [comment]
Here is error logs:
[docker_reg.txt](https://github.com/minio/minio/files/2295528/docker_reg.txt)

output from the cli:
[root@build-node base]# docker push example.com:5001/base
The push refers to a repository [example.com:5001/base]
931dbfa4d6b6: Retrying in 5 seconds 
27b6f0e654f8: Retrying in 5 seconds 
6b9e8fb31b40: Retrying in 5 seconds 
461c302a53fa: Retrying in 5 seconds 
cf411a5cd530: Retrying in 5 seconds 
861d87b3c342: Waiting 
088eda4c3b56: Waiting 
61374c24fd32: Waiting 
1d31b5806ba4: Waiting

**Comment by krisis** [comment]
@bearmoo-repo I am able to recreate the issue locally. minio gcs gateway doesn't return a recently initiated multipart upload's `id` in `ListMultipartUploads` API call. This makes docker-push to retry uploading the docker image unsuccessfully.
The above multipart upload behaviour was brought in GCS gateway by https://github.com/minio/minio/pull/4455. Let me investigate further if `ListMultipartUpload` API can be modified to fix this issue.

**Comment by krisis** [comment]
@krishnasrinivas Is there any reason why we return the list of multipart uploads in `ListMultipartUploads` API call? I see this behaviour was introduced as part of #4455.

**Comment by krishnasrinivas** [comment]
@krisis it was part of the simplification of the backend format for gcs. What we can do for the current issue is, for ListMultipartUploads, we can look if any of the `minio.sys.tmp/multipart/v1/uploadID/gcs.json` matches and return an entry for ListMultipartUploads.

Similarly we can support ListObjectParts too. These two changes should be good enough to support docker registry.

**Comment by bearmoo-cloud-net** [comment]
Hey,

Any update on this?

-Frank

**Comment by krisis** [comment]
@bearmoo-repo, I will be working on this early next week. It is possible to fix this issue as explained in the above comment.

**Comment by bearmoo-cloud-net** [comment]
Any update?

-Frank

**Comment by krisis** [comment]
@bearmoo-repo I have begun working on this. I will submit a pull request once my changes are ready and tested.

**Comment by krisis** [comment]
@bearmoo-repo I have done some initial testing. I still need to do docker registry tests. It would be great if you could test the [PR](https://github.com/minio/minio/pull/6377) and provide comments.

**Comment by krisis** [comment]
@bearmoo-repo I have addressed outstanding review comments on my [PR](https://github.com/minio/minio/pull/6377). docker registry test described in the steps to reproduce works as expected with the PR.
