### ISSUE TITLE
stream with content upload to minio with 0 byte

### ISSUE THREAD

**Issue by chaninafcha** [minio/minio#6274]
hi,

i have stream full with byte,
when i do   : ` minio.PutObjectAsync(bucketName, url, memoryStream, memoryStream.Length);`

**the file upload to minio with 0 byte**

**here the full function code:**

```
`        public byte[] Upload(MemoryStream memoryStream, string fileName, Certificate cert)
        {
                try
                {
                    var found = minio.BucketExistsAsync(bucketName).Result;
                    if (!found)
                    {
                        minio.MakeBucketAsync(bucketName).Wait();
                    }
                     minio.PutObjectAsync(bucketName, url, memoryStream, memoryStream.Length);

                    return memoryStream.ToArray();
                }
                catch (MinioException e)
                {
                    Console.WriteLine("File Upload Error: {0}", e.Message);
                }
            }
            return null;
        }`
```
the way that i call to function

`  byte[] retVal = certUp.Upload( memoryStream, fileName, cert);`

why its happened
Thanks in advance

**Comment by kannappanr** [comment]
@chaninafcha We will take a look at this issue and get back to you. Just to clarify, why are `filename` and `cert` not used within the function? Have you also had a chance to look at https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/PutObject.cs ?

**Comment by poornas** [comment]
@chaninafcha, PutObjectAsync is a task and needs to be awaited. You could either add a Wait() for the Put call or turn  Upload into a task and wait for its completion.

**Comment by chaninafcha** [comment]
hi,
i had memoryStream.position=0 
and its work well

thank
