### ISSUE TITLE
TestCreateEndpoints fails intermittently

### ISSUE THREAD

**Issue by krisis** [minio/minio#6275]
TestCreateEndpoints test fails intermittently during [appveyor-ci](https://ci.appveyor.com/project/Harshavardhana/minio-qxbjq/build/14472) runs.

## Expected Behavior

Unit tests must pass always

## Current Behavior

`TestCreateEndpoints` unit  test fails intermittently
```
--- FAIL: TestCreateEndpoints (0.01s)
	endpoint_test.go:327: error: expected = path '/export' can not be served by different port on same address, got = duplicate endpoints found
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
As we removed appveyor, and use Travis for windows build, closing this for now. we can revisit if seen again
