### ISSUE TITLE
[proposal]: Extend and refactor ObjectLayer to take Options for generic extendability 

### ISSUE THREAD

**Issue by aead** [minio/minio#6279]
## Expected Behavior

It should be possible to pass operation-dependent parameters to the `ObjectLayer` implementation.
This is necessary for certain current features and may be useful for features in the future.
Further it makes the API more convenient: (Only specify what you need).  

## Current Behavior

The API is not extendable. 
For example:
 The current `GetObject` signature is: 
`GetObject(ctx context.Context, bucket string, key string, startOffset int64, length int64, writer io.Writer, etag string)` 

It is not possible to request e.g. SSE-C from the `ObjectLayer` implementation.

## Possible Solution

There is similar approach possible as used by minio-go:
Refactor functions the following way:
Keep the required parameters: For example the bucket, the object and the io.Writer
Add an additional parameter: For example `GetOptions` containing fields for additional parameters - e.g.:
```
GetOptions {
    Offset int64
    Length: int64
    Etag: String,
    ServerSideEncryption: minio.ServerSide,
    ...
}
```  

## Context
SSE, general code structure, design

## Your Environment
master

/cc @poornas

**Comment by harshavardhana** [comment]
Assuming this is already done, closing. Feel free to open if not done yet.
