### ISSUE TITLE
Transfer closed when gzipped content GCS-only

### ISSUE THREAD

**Issue by stevepeak** [minio/minio#6280]
Gzipped files are processing incorrectly resulting in a `curl (18)` error.
Gzipped files *work* when archive and S3 but not GCS.

# Steps to recreate

## Create minio container
```sh
docker run -p 9000:9000 --name minio-gcp \
 -e "MINIO_ACCESS_KEY=key" \
 -e "MINIO_SECRET_KEY=secret" \
 -e GOOGLE_APPLICATION_CREDENTIALS=/credentials.json \
 -v ./credentials.json:/credentials.json  \
 minio/minio:RELEASE.2018-08-02T23-11-36Z gateway gcs ${BUCKET}
```

## Create + upload a zip file
```sh
echo 'foobar' > foobar.txt
gzip foobar.txt
mc cp foobar.txt.gz gcs/${BUCKET}/foobar.txt.gz
```

## Check headers
```sh
curl -I http://localhost:9000/${BUCKET}/foobar.txt.gz
```
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 38
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Etag: "4135543952-1"
Last-Modified: Tue, 14 Aug 2018 10:58:56 GMT
Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 154ABB248F2AF37C
X-Xss-Protection: 1; mode=block
Date: Tue, 14 Aug 2018 10:59:49 GMT
```

**NOTICE** There is no `Content-Encoding` therefore cannot decompress requests.

## Manually change `Content-Encoding`
See here https://cl.ly/3q3V3e2K370V

## Check headers
```sh
curl -I http://localhost:9000/${BUCKET}/foobar.txt.gz
```

```diff
  HTTP/1.1 200 OK
  Accept-Ranges: bytes
+ Content-Encoding: gzip
  Content-Length: 38
  Content-Security-Policy: block-all-mixed-content
  Content-Type: application/octet-stream
  Etag: "4135543952-1"
  Last-Modified: Tue, 14 Aug 2018 11:01:12 GMT
  Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
  Vary: Origin
  X-Amz-Request-Id: 154ABB3C4A13C8A0
  X-Xss-Protection: 1; mode=block
  Date: Tue, 14 Aug 2018 11:01:31 GMT
```

## Curl it
```sh
curl http://localhost:9000/${BUCKET}/foobar.txt.gz
```

```
foobar
curl: (18) transfer closed with 31 bytes remaining to read
```

## Curl it verbose
```sh
curl -v http://localhost:9001/codecov/foobar.txt.gz
```

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9001 (#0)
> GET /codecov/foobar.txt.gz HTTP/1.1
> Host: localhost:9001
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Encoding: gzip
< Content-Length: 38
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/octet-stream
< Etag: "3462412222-1"
< Last-Modified: Tue, 14 Aug 2018 11:06:20 GMT
< Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
< Vary: Origin
< X-Amz-Request-Id: 154ABB83B557B0E4
< X-Xss-Protection: 1; mode=block
< Date: Tue, 14 Aug 2018 11:06:38 GMT
<
foobar
* transfer closed with 31 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 31 bytes remaining to read
```

**Comment by kannappanr** [comment]
@stevepeak Thanks for filing this issue. I am not very clear on the issue. Do you want `mc` to set `content-encoding` header for common file types?

**Comment by harshavardhana** [comment]
This PR https://github.com/minio/minio/pull/6270 might fix this issue.

**Comment by kannappanr** [comment]
@stevepeak Can you please validate the fix?

**Comment by stevepeak** [comment]
@kannappanr I'm not using `mc` to upload. I'm using curl with a temporary link:

```
curl -fiX PUT ${UPLOAD_URL} \
                  --data-binary @foobar.txt.gz \
                  -H 'Content-Encoding: gzip'
```

I've tried so many variations of content-type and encoding... but same issue. The strange thing is that this exact process works for S3 and local-archive just not in GCP.

@harshavardhana I will give this pull request a try. Thank you for suggesting it.

**Comment by stevepeak** [comment]
@kannappanr Even when uploading directly via the GCS console it does not work.

See here: https://cl.ly/3L3n0X2n2I47

Another proof: https://cl.ly/0f1T2a2e3z1B

```diff
+ $ curl https://storage.googleapis.com/codecov/foobar2.txt.gz
+ foobar

- $ curl  http://localhost:9001/codecov/foobar2.txt.gz
- foobar
- curl: (18) transfer closed with 31 bytes remaining to read
```
> `localhost:9001` is a my local minio-gcp

**Comment by stevepeak** [comment]
@harshavardhana Assuming the `edge` tag (as of this comment) in Docker Hub has #6270 included. The change **did not** change the issue I'm presenting.

**Comment by kannappanr** [comment]
@stevepeak I did try `curl -fiX PUT ${UPLOAD_URL}  --data-binary @foobar.txt.gz -H 'Content-Encoding: gzip'` and it worked for me.

Here is what I did 

```
$mc mb mygcs/mytestbucket
Bucket created successfully `mygcs/mytestbucket`.

$ mc policy upload mygcs/mytestbucket
Access permission for `mygcs/mytestbucket` is set to `upload`

$curl -fiX PUT http://192.168.1.68:9001/mytestbucket/ppc.tar.gz --data-binary @/home/user/Desktop/ppc.tar.gz -H 'Content-Encoding: gzip'

HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Etag: "1958397639-1"
Server: Minio/DEVELOPMENT.2018-08-21T23-06-41Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 154D0C0083A05AEE
X-Xss-Protection: 1; mode=block
Date: Wed, 22 Aug 2018 00:04:04 GMT
Content-Length: 0

$ mc stat mygcs/mytestbucket/ppc.tar.gz
Name      : ppc.tar.gz
Date      : 2018-08-21 17:04:04 PDT 
Size      : 2.2KiB 
ETag      : 1958397639-1 
Type      : file 
Metadata  :
  Content-Type    : application/x-www-form-urlencoded 
  Content-Encoding: gzip 
```

**Comment by stevepeak** [comment]
@kannappanr Ok. So I must be missing something here. Can you check this out: https://cl.ly/e8f3c270e9c3

I just don't understand how to get `Content-Encoding: gzip` working...

**Comment by kannappanr** [comment]
@stevepeak We have done various tests on GCS with respect to creating buckets and uploading objects. We have run mc on Linux and Mac. I have even accessed your bucket and object and here is what I see.

```
mc stat mygcs1/codecov/foobar.txt.gz
Name      : foobar.txt.gz
Date      : 2018-08-23 08:10:15 PDT 
Size      : 38B    
ETag      : 3462412222-1 
Type      : file 
Metadata  :
  Content-Type    : application/x-www-form-urlencoded 
  Content-Encoding: gzip 
```

Just to be clear I am using the latest `mc` release

**Comment by stevepeak** [comment]
@kannappanr Thank you again for your help and patience.

I'm simply seeing different results...(hair pulling).

As demonstrated below. The file in GCS has `Content-Encoding: gzip` but `mc stat` ignores.


```
$ brew upgrade  minio/stable/mc
==> Upgrading 1 outdated package, with result:
minio/stable/mc 20180802173944Z_1 -> 20180818021304Z_1
==> Upgrading minio/stable/mc
==> Downloading https://dl.minio.io/client/mc/release/darwin-amd64/mc.RELEASE.2018-08-18T02-13-04Z
######################################################################## 100.0%
🍺  /usr/local/Cellar/mc/20180818021304Z_1: 3 files, 13MB, built in 16 seconds
```

```
$ mc stat gcs/codecov/foobar.txt.gz
Name      : foobar.txt.gz
Date      : 2018-08-14 13:05:06 CEST
Size      : 38B
ETag      : 885ee8e6c901d9fc2cdb87ef1a1c47ad
Type      : file
Metadata  :
  Expires             : Fri, 24 Aug 2018 09:03:06 GMT
  Warning             : 214 UploadServer gunzipped
  Content-Type        : application/x-www-form-urlencoded
  X-Goog-Hash         : crc32c=zmA3vg==
  X-Goog-Storage-Class: MULTI_REGIONAL
  X-Guploader-Uploadid: AEnB2Upw9yHJTN9voDt2_RZIWFvEudr-qSqawBnaqzDQ9UKlY_RsfGBEOZ6hOJqsFsoWkJp880hqmI03597Hj4xkHdyB9jNc0-Ha-WgFCODwUzsY82rIALA
  Alt-Svc             : quic=":443"; ma=2592000; v="44,43,39,35"
  Cache-Control       : private, max-age=0
```

<img width="469" alt="screen shot 2018-08-24 at 11 04 32" src="https://user-images.githubusercontent.com/2041757/44575905-834eb180-a78d-11e8-8b0a-43008ec1e006.png">

**Comment by kannappanr** [comment]
@stevepeak We finally found the issue. See https://cloud.google.com/storage/docs/transcoding#decompressive_transcoding

Google always decompresses and sends the data back by default.

To make this work, we need to set `Accept-Encoding: gzip` as part of the request header. 

 If you try `curl -H "Accept-Encoding: gzip" "https://storage.googleapis.com/codecov/foobar.txt.gz" -o /tmp/file` , you will see that the file is `gzipped`

Will be adding this in the next few days to `minio gateway` code so that this is handled properly.

**Comment by stevepeak** [comment]
Phew! I thought for a moment there I was going crazy....

I greatly appreciate your patience and help. This issue was quite illusive. Very pleased to hear it will be resolved in due time. 👍

**Comment by stevepeak** [comment]
@harshavardhana I ask politely for an update on this issue (it's very important for our production release). Thank you kindly.

**Comment by kannappanr** [comment]
@stevepeak Sorry, we will try to incorporate the changes soon. Vendorizing gcs library took some time and we had to focus on other issues. We will try to make a release with this fix by tomorrow. Once again, sorry it is taking longer.
