### ISSUE TITLE
Crash: Error: Unsupported bitrot algorithm

### ISSUE THREAD

**Issue by jdfalk** [minio/minio#6285]
## Expected Behavior
I should be able to retrieve the object.

## Current Behavior
Attempting to read an object or heal the object crashes minio.

## Logs
<details>
<p>

Aug 15 14:04:58  minio[5506]: API: SYSTEM()
Aug 15 14:04:58  minio[5506]: Time: 14:04:58 UTC 08/15/2018
Aug 15 14:04:58  minio[5506]: Error: Unsupported bitrot algorithm
Aug 15 14:04:58  minio[5506]: 1: cmd/logger/logger.go:326:logger.CriticalIf()
Aug 15 14:04:58  minio[5506]: 2: cmd/xl-v1-metadata.go:77:cmd.BitrotAlgorithm.New()
Aug 15 14:04:58  minio[5506]: 3: cmd/erasure.go:102:cmd.NewBitrotVerifier()
Aug 15 14:04:58  minio[5506]: 4: cmd/xl-v1-healing-common.go:182:cmd.disksWithAllParts()
Aug 15 14:04:58  minio[5506]: 5: cmd/xl-v1-healing.go:308:cmd.healObject()
Aug 15 14:04:58  minio[5506]: 6: cmd/xl-v1-healing.go:627:cmd.xlObjects.HealObject()
Aug 15 14:04:58  minio[5506]: 7: cmd/xl-sets.go:1230:cmd.(*xlSets).HealObject()
Aug 15 14:04:58  minio[5506]: 8: cmd/admin-heal-ops.go:658:cmd.(*healSequence).healObject()
Aug 15 14:04:58  minio[5506]: 9: cmd/admin-heal-ops.go:635:cmd.(*healSequence).healBucket()
Aug 15 14:04:58  minio[5506]: 10: cmd/admin-heal-ops.go:562:cmd.(*healSequence).healBuckets()
Aug 15 14:04:58  minio[5506]: 11: cmd/admin-heal-ops.go:523:cmd.healBuckets)-fm()
Aug 15 14:04:58  minio[5506]: 12: cmd/admin-heal-ops.go:516:cmd.(*healSequence).traverseAndHeal.func1()
Aug 15 14:04:58  minio[5506]: 13: cmd/admin-heal-ops.go:523:cmd.(*healSequence).traverseAndHeal()
Aug 15 14:04:58  minio[5506]: panic: (struct {}) (0x1158e60,0x1eac830)
Aug 15 14:04:58  minio[5506]: goroutine 2077591 [running]:
Aug 15 14:04:58  minio[5506]: github.com/minio/minio/cmd/logger.CriticalIf(0x146cee0, 0xc42003e960, 0x145c4c0, 0xc420e152a0)
Aug 15 14:04:58  minio[5506]: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logger.go:327 +0x74
Aug 15 14:04:58  minio[5506]: github.com/minio/minio/cmd.BitrotAlgorithm.New(0x0, 0x2, 0x2)
Aug 15 14:04:58  minio[5506]: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-metadata.go:77 +0xac
Aug 15 14:04:58  minio[5506]: github.com/minio/minio/cmd.NewBitrotVerifier(0x0, 0x0, 0x0, 0x0, 0xa00000)
Aug 15 14:04:58  minio[5506]: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/erasure.go:102 +0x2f
Aug 15 14:04:58  minio[5506]: github.com/minio/minio/cmd.disksWithAllParts(0x146cf60, 0xc42227ddd0, 0xc422a1f260, 0x6, 0x6, 0xc420305900, 0x6, 0x6, 0xc422a1ef60, 0x6, ...)
Aug 15 14:04:58  minio[5506]: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing-common.go:182 +0x306
Aug 15 14:04:58  minio[5506]: github.com/minio/minio/cmd.healObject(0x146cf60, 0xc42227ddd0, 0xc422a1ef00, 0x6, 0x6, 0xc420d5610a, 0xb, 0xc42111c540, 0x28, 0x3, ...)

</p>
</details>

## Steps to Reproduce (for bugs)
1. We have [thanos](https://github.com/improbable-eng/thanos) backing up data to a minio distributed cluster. 
2. We use [thanos-compact](https://github.com/improbable-eng/thanos/blob/master/docs/design.md) which merges several folders/objects into a consolidated larger one.
3. In the larger folders (80GB+) we suddenly have corruption issues with the error about bitrot. This can cause the daemon to crash.
4. (optional) Attempting to run a heal on the folder crashes the daemon. 

## Context
See above

## Your Environment
* Version used (`minio version`):
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a
* Operating System and version (`uname -a`):
Centos 7, Linux 4.17.14-1.el7.elrepo.x86_64 #1 SMP Thu Aug 9 10:18:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@jdfalk Thanks for filing this issue. We will try to see what could have caused this issue and get back to you.

**Comment by harshavardhana** [comment]
Can you paste the entire error trace ??

**Comment by jdfalk** [comment]
That's all I have in the logs.

**Comment by harshavardhana** [comment]
Can you also provide `xl.json` from your backend disks ? This will be present inside the object folder on your backend.

**Comment by jdfalk** [comment]
xl.json:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":4,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"705bf2bbf4f22defd32ae55fb0e929352601ace319ba1de707d97621319e8449"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

Renamed .txt so github would accept the file
[xl.json.txt](https://github.com/minio/minio/files/2291082/xl.json.txt)

**Comment by kannappanr** [comment]
@jdfalk, can you paste `xl.json` from all the disks for an object, where you are seeing this issue. In your setup, there should be 6 `xl.json` files.

**Comment by jdfalk** [comment]
S1D1:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":4,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"705bf2bbf4f22defd32ae55fb0e929352601ace319ba1de707d97621319e8449"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

S1D2:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":5,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"09f24bbe11ef725c0d9fd55283232952f01f34e55e228989fa02cf4e315297fd"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

S2D1:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":6,"distribution":[4,5,6,1,2,3]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

S2D2:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":1,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"20fec0016bde585214fd9fc47a5627eed28d463499ace754cda9b846afb50707"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

S3D1:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":2,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"fca43bbbf560bac30d5969418b34601c6ea143d2501cea46034d4e9941d0eacd"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

S3D2:
`{"version":"1.0.1","format":"xl","stat":{"size":536869556,"modTime":"2018-08-13T13:38:22.729553244Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":3,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"195d436bf3f5c6349eb7ac8ac44230fdb6ef4a2c7eb6aa59336318ee99fb05dd"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"ade3d414599ba306887780ed3d2ed1df-1"},"parts":[{"number":1,"name":"part.1","etag":"5944957fadfd4acb552b6886f77562e9","size":536869556}]}`

**Comment by jdfalk** [comment]
I noticed S2D1 doesn't have checksum section. To work around this can I delete the folder for the object on the specific disk and run a heal. So effectively:
`rm -rf /mnt/disk1/folder` then `mc admin heal server/object`

**Comment by kannappanr** [comment]
@jdfalk Thanks for this information. Is this particular disk missing checksums on all of its xl.json files?

**Comment by jdfalk** [comment]
Nope. Just that single object.

**Comment by kannappanr** [comment]
@jdfalk On disk S2D1, for this particular object, was the file named `part.1` present?

**Comment by jdfalk** [comment]
Yes sir.

**Comment by jdfalk** [comment]
It happened on another object. I will paste the xl.json from those as well. It looks like it's only happening on S2D1.

S1:
uname -a
`4.17.14-1.el7.elrepo.x86_64 #1 SMP Thu Aug 9 10:18:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`

S2:
uname -a
`4.17.14-1.el7.elrepo.x86_64 #1 SMP Thu Aug 9 10:18:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`


S3:
uname -a
`4.17.13-1.el7.elrepo.x86_64 #1 SMP Mon Aug 6 14:16:00 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`

I'm attempting to pull all the info I would for an ubuntu bug report but centos is.....awful? I think that's the word. 

[lspci-vvnn-server1.log](https://github.com/minio/minio/files/2297726/lspci-vvnn-server1.log)
[lspci-vvnn-server2.log](https://github.com/minio/minio/files/2297727/lspci-vvnn-server2.log)
[lspci-vvnn-server3.log](https://github.com/minio/minio/files/2297728/lspci-vvnn-server3.log)

**Comment by jdfalk** [comment]
S1D1:
`{"version":"1.0.1","format":"xl","stat":{"size":536860899,"modTime":"2018-08-10T08:46:41.266087956Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":4,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"cff7109b055c412e40c07194df8d3e55f630fafc67a383f5c57d2ec7b6464f79"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"d0c49449c1129b72f2ae6d4d36ccf061-1"},"parts":[{"number":1,"name":"part.1","etag":"9ae0b8c2c745d83f7b0602783856af9f","size":536860899}]}`

S1D2:
`{"version":"1.0.1","format":"xl","stat":{"size":536860899,"modTime":"2018-08-10T08:46:41.266087956Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":5,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"dd29f903bb55684712bf7a60f7f136a8da5f14025b21436c452167336dbde49f"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"d0c49449c1129b72f2ae6d4d36ccf061-1"},"parts":[{"number":1,"name":"part.1","etag":"9ae0b8c2c745d83f7b0602783856af9f","size":536860899}]}`

S2D1:
`
{"version":"1.0.1","format":"xl","stat":{"size":536860899,"modTime":"2018-08-10T08:46:41.266087956Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":6,"distribution":[4,5,6,1,2,3]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"d0c49449c1129b72f2ae6d4d36ccf061-1"},"parts":[{"number":1,"name":"part.1","etag":"9ae0b8c2c745d83f7b0602783856af9f","size":536860899}]}
`

S2D2:
`
{"version":"1.0.1","format":"xl","stat":{"size":536860899,"modTime":"2018-08-10T08:46:41.266087956Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":1,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"cecb885a97d71d9430b2626f55244f62fa589103e47085021406642c636c6811"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"d0c49449c1129b72f2ae6d4d36ccf061-1"},"parts":[{"number":1,"name":"part.1","etag":"9ae0b8c2c745d83f7b0602783856af9f","size":536860899}]}
`

S3D1:
`
{"version":"1.0.1","format":"xl","stat":{"size":536860899,"modTime":"2018-08-10T08:46:41.266087956Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":2,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"f58b6897fcefc9516bd8683eba52d03ba1f297a6485145662fc25fad189218b6"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"d0c49449c1129b72f2ae6d4d36ccf061-1"},"parts":[{"number":1,"name":"part.1","etag":"9ae0b8c2c745d83f7b0602783856af9f","size":536860899}]}
`

S3D2:
`
{"version":"1.0.1","format":"xl","stat":{"size":536860899,"modTime":"2018-08-10T08:46:41.266087956Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":3,"parity":3,"blockSize":10485760,"index":3,"distribution":[4,5,6,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"5557e3e0070fb2b473b990efa6a87a172220e48c3e4b1f3b86e9db5c7766e90d"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"application/octet-stream","etag":"d0c49449c1129b72f2ae6d4d36ccf061-1"},"parts":[{"number":1,"name":"part.1","etag":"9ae0b8c2c745d83f7b0602783856af9f","size":536860899}]}
`

**Comment by kannappanr** [comment]
@jdfalk the latest release should have the fix. closing this issue as fixed. Please feel free to re-open if you still have issues.
