### ISSUE TITLE
[API] s3 SELECT implement all the pending items

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#6286]
Implement all the pending features in S3 select.

- [x] JSON documents as supported Objects
- [x] CAST expression, Date functions
- [x] Returning types other than float from aggregation queries.
- [x] Bracket and Reversal Notation with SQL Like operator.
- [x] SUBSTRING currently is not supported and TRIM only works with
      default arguments of trim leading and trailing spaces

**Comment by nitisht** [comment]
ping @sinhaashish can you update what is done and what is not done here

**Comment by harshavardhana** [comment]
Will update all pending features @nitisht soon.

**Comment by harshavardhana** [comment]
This is fixed by #7023 with pending items

- [x] // DateAdd         FuncName = "DATE_ADD"
- [x] // DateDiff        FuncName = "DATE_DIFF"
- [x] // Extract         FuncName = "EXTRACT"
- [x] // ToString        FuncName = "TO_STRING"
- [x] // Cast            FuncName = "CAST" // CAST('2007-04-05T14:30Z' AS TIMESTAMP)

**Comment by harshavardhana** [comment]
Transferring this issue to @balamurugana

**Comment by harshavardhana** [comment]
All pending items have been fixed by @donatello and @balamurugana - closing.
