### ISSUE TITLE
Some directories invisible after upload on EC-based server instance

### ISSUE THREAD

**Issue by jonassvatos** [minio/minio#6293]
I have an EC-based server instance with 32 disks and try to upload this directory strucuture:
```
$ find 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/Arial.ttf
```

## Expected Behavior
When I upload this directory, I expect to be able to list it.

## Current Behavior
The API doesn't return the second level directory, only if i list the bucket recursively.
This affects minio, s3cmd, and s3fs. None of these client implementations is able to list the second level directory withnout recursive list (which is not supported on s3fs, therefore renders the directory invisible).

## Steps to Reproduce (for bugs)
```
$ minio server data/disk{1..32}
..
$ mc mb local/test
[success]
$ mc cp -r 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b local/test
[success]
$ mc ls local/test
**[nothing]**
$ mc ls -r local/test
{"status":"success","type":"file","lastModified":"2018-08-16T15:19:58.618+02:00","size":367112,"key":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/Arial.ttf","etag":"5995c725ca5a13be62d3dc75c2fc59fc"}
{"status":"success","type":"file","lastModified":"2018-08-16T15:19:58.626+02:00","size":2846,"key":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml","etag":"90949995bb143b946f124c5f716a6065"}
```

## Your Environment
```
$ minio version
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a
```
```
$ mc version
Version: 2018-08-02T17:39:44Z
Release-tag: RELEASE.2018-08-02T17-39-44Z
Commit-id: 9998e077dfd70a0c1189f1a9b5d7ab25a6e01b79
```

**Comment by harshavardhana** [comment]
Can you provide the backend files for this directory structure? are `Arial.ttf` and `sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml` files 0-byte files?

**Comment by jonassvatos** [comment]
They are not, but the bug is triggered with files of arbitrary filesize, even 0 bytes..

**Comment by harshavardhana** [comment]
> They are not, but the bug is triggered with files of arbitrary filesize, even 0 bytes..

Can you provide the `xl.json` from the backend disks for these files? at least how do the files look like on the backend?

**Comment by jonassvatos** [comment]
Arial.ttf:
`{"version":"1.0.1","format":"xl","stat":{"size":367112,"modTime":"2018-08-16T16:05:31.603476446Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":8,"parity":8,"blockSize":10485760,"index":3,"distribution":[4,5,6,7,8,9,10,11,12,13,14,15,16,1,2,3],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"3fa98d9104e56160df4bc34c9c8f47c3cd4a0bb71b830e9c2657311bafd0a0e1"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"font/ttf","etag":"5995c725ca5a13be62d3dc75c2fc59fc"},"parts":[{"number":1,"name":"part.1","etag":"","size":367112}]}`

sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml:
`{"version":"1.0.1","format":"xl","stat":{"size":2846,"modTime":"2018-08-16T16:05:31.610223826Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":8,"parity":8,"blockSize":10485760,"index":1,"distribution":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,1],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"2da45ad9e0b55f218b7f4a5821bf0f0d2a41e3fbce502330db67f548f13ecf17"}]},"minio":{"release":"RELEASE.2018-08-02T23-11-36Z"},"meta":{"content-type":"text/xml; charset=utf-8","etag":"90949995bb143b946f124c5f716a6065"},"parts":[{"number":1,"name":"part.1","etag":"","size":2846}]}`

**Comment by jonassvatos** [comment]
But I was able to trigger the bug even on the clean lab environment with only touch-ing the files (e.g. 0-byte filesizes)

**Comment by harshavardhana** [comment]
I just tried with the latest master not able to reproduce it, created same structure. 

```
$ mc ls myminio-local1/testbucket/
[2018-08-16 10:13:07 PDT]     0B 05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/
[2018-08-16 10:13:07 PDT]     0B 1/
[2018-08-16 10:13:07 PDT]     0B 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/
```
```
$ mc ls myminio-local1/testbucket/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/
[2018-08-16 10:13:37 PDT]     0B 05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/
```
```
$ mc ls myminio-local1/testbucket/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/
[2018-08-16 10:12:25 PDT]     0B Arial.ttf
[2018-08-16 10:12:25 PDT]     0B sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml
```

**Comment by jonassvatos** [comment]
I can reproduce it on multiple machines, always from the clean state..
Could you please try to reproduce it with RELEASE.2018-08-02T23-11-36Z ?

Just for the record, I cannot reproduce it when running the server as nas gateway, only with erasure-coding.

Also, the files are invisible in minio browser.

**Comment by harshavardhana** [comment]
> I can reproduce it on multiple machines, always from the clean state..
> Could you please try to reproduce it with RELEASE.2018-08-02T23-11-36Z ?
> 
> Just for the record, I cannot reproduce it when running the server as nas gateway, only with erasure-coding.
> 
> Also, the files are invisible in minio browser.

Can you provide step by step instructions for a clean state? - I am going to try with previous releases and see where we hit this regression.

**Comment by jonassvatos** [comment]
This script starts an empty ec server, uploads the problematic directory structure together with the one which works, and try to list the contents of the bucket. Only the working one will be printed.

```
#!/bin/bash
rm -rf data 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b aa
minio server data/disk{1..32} &
sleep 10
mkdir -p 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30 aa
touch 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/{Arial.ttf,sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml} aa/cc.txt
mc mb --json local/test
mc cp -r --json aa local/test/
mc cp -r --json 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b local/test/
mc ls local/test
```
My output:
```
{"status":"success","bucket":"local/test","region":""}
{"status":"success","source":"aa/cc.txt","target":"local/test/aa/cc.txt","size":0,"totalCount":1,"totalSize":0}
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
{"status":"success","source":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/Arial.ttf","target":"local/test/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/Arial.ttf","size":0,"totalCount":2,"totalSize":0}
{"status":"success","source":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml","target":"local/test/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/05ef545f-8ed7-4ab9-bc0f-5dde7235ef30/sub_05ef545f-8ed7-4ab9-bc0f-5dde7235ef30.xml","size":0,"totalCount":2,"totalSize":0}
Total: 0 B, Transferred: 0 B, Speed: 0 B/s
[2018-08-16 20:17:18 CEST]     0B aa/
```

**Comment by jonassvatos** [comment]
Verified by testing on latest minio/minio:edge container.

BTW, do you have an estimate about timing of the next release ?
Our production runs on baremetal, not containers.
Thanks.

**Comment by harshavardhana** [comment]
> Verified by testing on latest minio/minio:edge container.
> 
> BTW, do you have an estimate about timing of the next release ?
> Our production runs on baremetal, not containers.
> Thanks.

We have made a release..
