### ISSUE TITLE
Crash: Unsupported bitrot algorithm

### ISSUE THREAD

**Issue by erma07** [minio/minio#6295]
unable to heal minio

## Expected Behavior
I should be able to heal minio bucket

## Current Behavior
executing "mc admin heal --recursive --json --debug live-minio-4" ends with minio crashing.

## Logs

<details>
<summary>Logs</summary>
<pre><code>
Aug 16 22:45:51 live-minio-4 minio[11564]: API: SYSTEM()
Aug 16 22:45:51 live-minio-4 minio[11564]: Time: 22:45:51 EEST 08/16/2018
Aug 16 22:45:51 live-minio-4 minio[11564]: Error: Unsupported bitrot algorithm
Aug 16 22:45:51 live-minio-4 minio[11564]:        1: cmd/logger/logger.go:326:logger.CriticalIf()
Aug 16 22:45:51 live-minio-4 minio[11564]:        2: cmd/xl-v1-metadata.go:77:cmd.BitrotAlgorithm.New()
Aug 16 22:45:51 live-minio-4 minio[11564]:        3: cmd/erasure.go:102:cmd.NewBitrotVerifier()
Aug 16 22:45:51 live-minio-4 minio[11564]:        4: cmd/xl-v1-healing-common.go:182:cmd.disksWithAllParts()
Aug 16 22:45:51 live-minio-4 minio[11564]:        5: cmd/xl-v1-healing.go:308:cmd.healObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        6: cmd/xl-v1-healing.go:627:cmd.xlObjects.HealObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        7: cmd/xl-sets.go:1230:cmd.(*xlSets).HealObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        8: cmd/admin-heal-ops.go:658:cmd.(*healSequence).healObject()
Aug 16 22:45:51 live-minio-4 minio[11564]:        9: cmd/admin-heal-ops.go:635:cmd.(*healSequence).healBucket()
Aug 16 22:45:51 live-minio-4 minio[11564]:       10: cmd/admin-heal-ops.go:577:cmd.(*healSequence).healBuckets()
Aug 16 22:45:51 live-minio-4 minio[11564]:       11: cmd/admin-heal-ops.go:523:cmd.healBuckets)-fm()
Aug 16 22:45:51 live-minio-4 minio[11564]:       12: cmd/admin-heal-ops.go:516:cmd.(*healSequence).traverseAndHeal.func1()
Aug 16 22:45:51 live-minio-4 minio[11564]:       13: cmd/admin-heal-ops.go:523:cmd.(*healSequence).traverseAndHeal()
Aug 16 22:45:51 live-minio-4 minio[11564]: panic: (struct {}) (0x1158e60,0x1eac830)
Aug 16 22:45:51 live-minio-4 minio[11564]: goroutine 2130102 [running]:
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd/logger.CriticalIf(0x146cee0, 0xc42003c960, 0x145c4c0, 0xc4233c3860)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logger.go:327 +0x74
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.BitrotAlgorithm.New(0x0, 0x2, 0x2)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-metadata.go:77 +0xac
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.NewBitrotVerifier(0x0, 0x0, 0x0, 0x0, 0xa00000)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/erasure.go:102 +0x2f
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.disksWithAllParts(0x146cf60, 0xc424872360, 0xc422774900, 0x10, 0x10, 0xc420e18000, 0x10, 0x10, 0xc422774300, 0x10, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing-common.go:182 +0x306
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.healObject(0x146cf60, 0xc424872360, 0xc422774200, 0x10, 0x10, 0xc42010a3eb, 0x7, 0xc42984b800, 0x34, 0xb, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing.go:308 +0x28e
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.xlObjects.HealObject(0xc42045f340, 0xc42045f380, 0xc42045f360, 0x0, 0x0, 0x0, 0x0, 0x146cf60, 0xc424872360, 0xc42010a3eb, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1-healing.go:627 +0x38d
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*xlSets).HealObject(0xc420432b40, 0x146cf60, 0xc424872360, 0xc42010a3eb, 0x7, 0xc42984b800, 0x34, 0x0, 0x0, 0x0, ...)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-sets.go:1230 +0x128
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).healObject(0xc420738300, 0xc42010a3eb, 0x7, 0xc42984b800, 0x34, 0x0, 0x0)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:658 +0xf4
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).healBucket(0xc420738300, 0xc42010a3eb, 0x7, 0xc422bb05a0, 0x2)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:635 +0x2ec
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).healBuckets(0xc420738300, 0xc4200a41e0, 0xc42523df00)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:577 +0x157
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).(github.com/minio/minio/cmd.healBuckets)-fm(0xc420738300, 0x0)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:523 +0x2a
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).traverseAndHeal.func1(0xc420566bd0)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:516 +0x8f
Aug 16 22:45:51 live-minio-4 minio[11564]: github.com/minio/minio/cmd.(*healSequence).traverseAndHeal(0xc420738300)
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:523 +0xd9
Aug 16 22:45:51 live-minio-4 minio[11564]: created by github.com/minio/minio/cmd.(*healSequence).healSequenceStart
Aug 16 22:45:51 live-minio-4 minio[11564]: #011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-heal-ops.go:466 +0xf0
Aug 16 22:45:51 live-minio-4 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 16 22:45:51 live-minio-4 systemd[1]: minio.service: Unit entered failed state.
Aug 16 22:45:51 live-minio-4 systemd[1]: minio.service: Failed with result 'exit-code'.
</code></pre>
</details>

## Your Environment
* Version used (`minio version`): 2018-08-02T23:11:36Z
* Operating System and version (`uname -a`): 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Duplicate #6285

**Comment by kannappanr** [comment]
@erkimarks Similar to what was requested in #6285, can you please post the xl.json files from all the disks for an object where you think this error is happening?

**Comment by erma07** [comment]
I have about 90TB of data, this is the only log I have. It is hard for me to identify the object based on this log.

**Comment by erma07** [comment]
Is there a way to roll out a version that has some extended logging.
