### ISSUE TITLE
deleting two minio docker swarm services made it unavailable

### ISSUE THREAD

**Issue by hadifarnoud** [minio/minio#6305]
I followed [this doc](https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html) to deploy minio on a docker swarm. this doc creates four minio instances with four different volumes on the same machine. it was eating up my disk space so I decided to delete two of these 4 docker services.

```
docker service rm minio_stack_minio3
docker service rm minio_stack_minio4
docker volume rm minio_stack_minio3-data
docker volume rm minio_stack_minio4-data
```
minio was showing no file on my buckets even though I was in minio_stack_minio2 which had all the data in its volume folder. then I scaled back the service and scaled it up again to force a restart. 

minio no longer works. I think I messed something up! this service supposed to have four instance and I made it two the wrong way.

can anyone help? what should I do?

PS: that doc is weird by the way. why would I want 4 minio running on the same machine and have four different volumes but the same content? it makes sense if it was on 4 different machines though

**Comment by nitisht** [comment]
> that doc is weird by the way. why would I want 4 minio running on the same machine and have four different volumes but the same content?

@hadifarnoud the doc you're referring to is for Docker Swarm - i.e. a distributed Minio cluster setup. For HA/Data redundancy. Even on a single machine an erasure coded setup with 4 drives will make sure there is enough redundancy to help data survive a 2 drive loss.

As is the Docker behaviour, the same compose file when run on localhost will spin 4 containers to emulate a Swarm/compose setup. 

If you want a single node standalone Minio setup, please refer https://docs.minio.io/docs/minio-docker-quickstart-guide.html

> what should I do?

First of all please back up the remaining Docker volumes at a safe location. Then try to restart Minio server as you did initially, with all the 4 volumes [as two volumes were deleted, please create two new empty docker volumes, and use the two existing volumes]

Once minio server is up, use `mc heal` to regenerate the data (ref: https://docs.minio.io/docs/minio-admin-complete-guide.html#heal).

**Comment by hadifarnoud** [comment]
```
$ mc admin heal --debug -f -r kamva
mc: <ERROR> Failed to start heal sequence. Post http://minio.kamva-files.com:9002/minio/admin/v1/heal/?forceStart=true: dial tcp 159.69.50.108:9002: connect: connection refused
 (0) admin-heal.go:116 cmd.mainAdminHeal(..)
 Release-Tag:RELEASE.2018-07-13T00-53-22Z | Commit:70dcf20d747d | Host:Hadis-Macbook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.10.2 | Mem:1.2MB/5.9MB | Heap:1.2MB/2.6MB
mc: <ERROR> Unable to display follow heal status. Post http://minio.kamva-files.com:9002/minio/admin/v1/heal/?forceStart=true: dial tcp 159.69.50.108:9002: connect: connection refused
 (0) admin-heal.go:130 cmd.mainAdminHeal(..)
 Release-Tag:RELEASE.2018-07-13T00-53-22Z | Commit:70dcf20d747d | Host:Hadis-Macbook-Pro.local | OS:darwin | Arch:amd64 | Lang:go1.10.2 | Mem:1.2MB/5.9MB | Heap:1.2MB/2.5MB
```

**Comment by hadifarnoud** [comment]
for reference, this is what I did to fix this:
`docker stack deploy --compose-file=docker-compose-secrets.yaml minio_stack`
this will create the two missing drivers. and keep the already running ones

`mc admin heal -f -r TARGET`
note: replace `TARGET` with your own minio name which is `.mc/config.json` file.

it seems to be working as it is fixing the buckets. I'll report back if it didn't

**Comment by kannappanr** [comment]
@hadifarnoud Closing this issue for now. Please feel re-open if it doesn't work
