### ISSUE TITLE
Helm ClusterIP is None

### ISSUE THREAD

**Issue by alexellis** [minio/minio#6307]
## Expected Behavior

Minio to come up with a valid and accessible ClusterIP when installed in stand-alone mode with the helm chart with serviceType ClusterIP (default)

## Current Behavior

Unreachable - DNS not found from Kubernetes

## Possible Solution

I may be doing something wrong, @harshavardhana can you advise?

## Steps to Reproduce (for bugs)

Store the secets in Kubernetes

```
kubectl create secret generic -n openfaas-fn \
 s3-secret-key --from-literal s3-secret-key="$SECRET_KEY"
kubectl create secret generic -n openfaas-fn \
 s3-access-key --from-literal s3-access-key="$ACCESS_KEY"
```

Install Minio with helm

```
helm install --name cloud --namespace openfaas \
   --set accessKey=$ACCESS_KEY,secretKey=$SECRET_KEY,replicas=1,persistence.enabled=false,service.port=9000 \
  stable/minio
```

Helm told me that the name value should be `cloud-minio-svc.openfaas.svc.cluster.local`

**Comment by nitisht** [comment]
let me try this and get back to you @alexellis .

**Comment by nitisht** [comment]
I can confirm this is happening @alexellis . I am working on how to fix this

**Comment by nitisht** [comment]
@alexellis I have sent a fix to helm chart repo here https://github.com/helm/charts/pull/7435

**Comment by alexellis** [comment]
Thank you. for the update @nitisht cc @affix

**Comment by nitisht** [comment]
Fixed by https://github.com/helm/charts/pull/7435

**Comment by alexellis** [comment]
Thanks I'll retest to see if the ClusterIP gets assigned properly. :+1:
