### ISSUE TITLE
Update Minio browser screenshots

### ISSUE THREAD

**Issue by nitisht** [minio/minio#6308]
## Expected Behavior
Minio browser screenshots should reflect the current browser look. We have moved away from displaying the total available storage in browser. Accordingly Minio browser screenshots need to be updated in these documents.

- https://docs.minio.io/docs/minio-quickstart-guide.html
- https://docs.minio.io/docs/minio-gateway-for-azure.html
- https://docs.minio.io/docs/minio-gateway-for-gcs.html
- https://docs.minio.io/docs/minio-gateway-for-nas.html

These screenshots need to be updated
https://github.com/minio/minio/blob/master/docs/screenshots/minio-browser.png
https://github.com/minio/minio/blob/master/docs/screenshots/minio-browser-gateway.png

## Current Behavior
These docs have old browser screenshots

## Possible Solution
New screenshots

**Comment by deekoder** [comment]
@belvid  can you give a new screenshot so that @Nitish can do in place replace.

**Comment by belvid** [comment]
Here are the updated screenshots

<img width="704" alt="minio-browser-gateway" src="https://user-images.githubusercontent.com/20955366/44434329-6a60b900-a55f-11e8-9876-237f372a01a0.png">
<img width="704" alt="minio-browser" src="https://user-images.githubusercontent.com/20955366/44434330-6a60b900-a55f-11e8-94a2-1912ce399644.png">

**Comment by nitisht** [comment]
Thanks @belvid I will send the PR
