### ISSUE TITLE
Terraform AWS provider ERROR: NotImplemented: A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by ivan-pacheco** [minio/minio#6310]
## Expected behaviour
We're using terraform with AWS provider (version 1.32) to interact with Minio (aws_s3_bucket_object) 
It works perfectly fine with any version below **RELEASE.2018-05-04T23-13-12Z**

## Actual behaviour
We're using terraform with AWS provider (version 1.32) to interact with Minio (aws_s3_bucket_object) 
It works perfectly fine until version: **RELEASE.2018-05-04T23-13-12Z** where provider reports the below error:

```
aws_s3_bucket_object.ssl-cert[3]: aws_s3_bucket_object.ssl-cert.3: Failed to get object tags (bucket: /my-bucket/certs, key: cert.key): NotImplemented: A header you provided implies functionality that is not implemented
	status code: 501, request id: 154BB73EA25EC680, host id: 
```

## Steps to reproduce the behavior
Use below terraform code to reproduce the issue:

```
provider "aws" {
    skip_requesting_account_id = true
    skip_credentials_validation = true
    skip_get_ec2_platforms = true
    skip_metadata_api_check = true       
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    region     = "us-east-1"
    endpoints {
        s3     = "${var.s3_endpoint}"
  }  
}

resource "aws_s3_bucket_object" "ssl-cert" {
    bucket = "/my-bucket/certs}"
    key    = "${var.ssl-file}"
    source = "generated/${var.ssl-file}"
    content_type = "text/plain"
    etag   = "${md5(file("generated/${var.ssl-files}"))}"
}
```

## mc version
We're not using mc. 

## System information
Terraform 0.11.7
Terraform AWS provider (version 1.32)

**Comment by kannappanr** [comment]
@ivan-pacheco Thanks for filing this issue. Can you please execute `export MINIO_HTTP_TRACE=/dev/stdout` to trace the incoming HTTP requests before starting the minio server and paste the logs here.

**Comment by harshavardhana** [comment]
We should implement a dummy GetObjectTaggingHandler() along the lines of GetBucketACL and GetObjectACL handlers. Check `acl-handlers.go` for more information. 

Once this is done we will be able to use terraform since it is only trying to do GetObjecTagging() not Set..

**Comment by harshavardhana** [comment]
For more information refer https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGETtagging.html

**Comment by deekoder** [comment]
fix is in progress.

**Comment by aeltawela** [comment]
@deekoder @ebozduman May I know how Minio will store the tags? Any plan to have internal DB?

**Comment by ebozduman** [comment]
@ahmedabt,
Our initial thought is to save them in our configuration file. A proposal is ready to be discussed in couple of days. We'll post the outcome here.

**Comment by aeltawela** [comment]
@ebozduman: I am following up on this feature. May I ask you when it will be available? do you have any initial implementation? I can contribute in the development if that can help.

**Comment by harshavardhana** [comment]
@ahmedabt it's already a work in progress. There is no set deadline yet.

Thanks for lending your help, appreciate it.

**Comment by wuzhihui1123** [comment]
my spinnaker use minio to store data, when access the link (http://spinnaker-api/pipelineConfigs/d5c0cbd5-771e-44d7-9356-74800f903e0d/history?count=2) . it always return the below. it has exist many month:

======
`
com.amazonaws.services.s3.model.AmazonS3Exception: A header you provided implies functionality that is not implemented (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: /dev-spinnaker/; S3 Extended Request ID: 3L137)
`

======

**i want to know when it will be fixed ,thanks ：)**

**Comment by harshavardhana** [comment]
Do you have a call trace of the request that is being sent to Minio ?

**Comment by canadiannomad** [comment]
I'm still seeing this in minio/minio:latest from today.
The bucket gets created, but terraform fails with the above error:

`* aws_s3_bucket.bucket: "example": NotImplemented: A header you provided implies functionality that is not implemented
	status code: 501, request id: , host id: `

Removing tags solved it.

**Comment by kannappanr** [comment]
@canadiannomad What `tags` are you talking about?

**Comment by ebozduman** [comment]
@canadiannomad,

Could you please also provide the reproduction steps in detail?

and the versions:
```
 $ terraform -v
 $ minio version
```

**Comment by boxcee** [comment]
@ebozduman I have the same problem. Specs below.

Terraform
```
Terraform v0.12.17
+ provider.aws v2.41.0
```

Minio
```
minio/minio:RELEASE.2019-08-07T01-59-21Z
```

main.tf
```
provider "aws" {
  region                      = "main"
  access_key                  = "minio"
  secret_key                  = "minio"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_region_validation      = true
  s3_force_path_style         = true
  skip_requesting_account_id  = true

  endpoints {
    s3 = "https://minio-instance.com"
  }
}

resource "aws_s3_bucket" "velero_bucket" {
  bucket = "velero-test"
  acl    = "public"
}
```

Error
```
Error: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 15DF5D647612E9D4, host id: 

  on test/main.tf line 16, in resource "aws_s3_bucket" "velero_bucket":
  16: resource "aws_s3_bucket" "velero_bucket" {
```

EDIT: I receive the above error. However, I can confirm the bucket was created correctly.
