### ISSUE TITLE
config.json has to be beautified with proper json indents 

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/minio#6311]
The config.json is not readable and looks clumsy.

I can see config.json not indented properly 

![image](https://user-images.githubusercontent.com/5410427/44302462-bedd1c00-a346-11e8-87ba-ca962a91ba82.png)

And the startup message should be changed. The configDir is pointing to a wrong location ( legacy )

![image](https://user-images.githubusercontent.com/5410427/44302500-8427b380-a347-11e8-9b01-eb5405003a53.png)

The `configDir` path has to be updated.

## Steps to Reproduce (for bugs)

1. Start Minio server
2. Open the config.json which is created in the backend.

## Your Environment

Version: 2018-08-18T18:51:46Z
Release-Tag: DEVELOPMENT.2018-08-18T18-51-46Z
Commit-ID: d531080b7ecd56305df1b79affa8cadf2fb526c4

**Comment by harshavardhana** [comment]
The intent is not to beautify it. But instead to implement an easier way to enable and disable entries in config.json which is being handled in PRs by @ebozduman @vadmeste

There are many tools which prettify JSON.

**Comment by kannappanr** [comment]
@Praveenrajmani Closing this issue as won't fix. We can take it up as part of PRs handled by @ebozduman and @vadmeste if required.

**Comment by vadmeste** [comment]
> @Praveenrajmani Closing this issue as won't fix. We can take it up as part of PRs handled by @ebozduman and @vadmeste if required.

Config PR https://github.com/minio/minio/pull/6113 already fixes this issue.
