### ISSUE TITLE
Error: remove fs.json: device or resource busy

### ISSUE THREAD

**Issue by MarwanElSherif** [minio/minio#6313]
I have minio running in a docker. Minio's data is stored on NFS.

I use this command to start the docker:
docker run -p 9000:9000 -e "MINIO_ACCESS_KEY=access" -e "MINIO_SECRET_KEY=secret" -e "MINIO_HTTP_TRACE=/tmp/minio.log" -v /NFS/minio/data:/data  -v /NFS/minio/config:/root/.minio minio/minio server /data

I can do the following:
create a bucket, 
remove an empty bucket, 
upload a file, 
cat a file. 

But I am getting an error while removing a file.

This is the error i get:
command: 
mc rm local/test1/myfile

Result:
Removing `local/test1/myfile`.
mc: <ERROR> Failed to remove `local/test1/myfile`. We encountered an internal error, please try again.

On the server side, this is what i see:
API: DeleteMultipleObjects(bucket=test1)
Time: 06:20:24 UTC 08/19/2018
RequestID: 154C34CBDC353ACB
RemoteHost: 172.17.42.1
UserAgent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-08-18T02:13:04Z
Error: remove /data/.minio.sys/buckets/test1/myfile/fs.json: device or resource busy
       1: cmd/fs-v1-helpers.go:421:cmd.fsDeleteFile()
       2: cmd/fs-v1.go:946:cmd.(*FSObjects).DeleteObject()
       3: cmd/bucket-handlers.go:307:cmd.(ObjectLayer).DeleteObject-fm()
       4: cmd/bucket-handlers.go:323:cmd.objectAPIHandlers.DeleteMultipleObjectsHandler()
       5: cmd/api-router.go:113:cmd.(objectAPIHandlers).DeleteMultipleObjectsHandler-fm()
       6: pkg/handlers/http-tracer.go:149:handlers.TraceReqHandlerFunc.func1()
       7: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

If I copy the minio data folder from the NFS volume to the local disk and run it using the same docker command above while changing the path, then it works fine. So it seems to be an issue with NFS.

## Expected Behavior

While running minio on an NFS volume, all object related operations should be possible imcluding removing objects.

## Current Behavior

Currently, running minio on an NFS volume, removing objects give an error.

## Steps to Reproduce (for bugs)

1. Run minio while storing the data on NFS mounted volumes.
2. Using any minio compatabile client, try to remove an object
3.
4.

## Your Environment

* Version used (`minio version`):
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: RHEL 7
* Operating System and version (`uname -a`):
Linux es3 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
What type of NFS NAS server do you have? are you using NFSv4 or NFSv3? if you are using NFSv3 do you have NTLM enabled? if not then it won't work. Minio over NFS requires filesystem locks to work properly.

**Comment by MarwanElSherif** [comment]
I running NFSv4.
I have used the flock linux command to check if file locks are supported by the NFS volume and i was able to create locks on files.

Here are the mount options for the NFS volume.

xx.xx.xx.xx:/OIaaS-NFS-01 on /NFS type nfs4 (rw,relatime,vers=4.1,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,port=0,timeo=1200,retrans=2,sec=sys,clientaddr=xx.xx.xx.xx,local_lock=none,addr=xx.xx.xx.xx,_netdev)

**Comment by harshavardhana** [comment]
What is the NFS server here ?

**Comment by MarwanElSherif** [comment]
My university has a EMC VNX storage box. They use the NFS feature of this box to provide storage for projects.

**Comment by MarwanElSherif** [comment]
I have been doing some additional tracing. When I try to delete an object, minio can successfully delete the actual file for NFS. It then tries to rename fs.json to .nfs000000000000493800001450 for example. This fails with error 10046 which i believe is "NFS4ERR_FILE_OPEN"

BTW, i am now running the minio server using "gateway nas" instead of "server" in my docker command

**Comment by harshavardhana** [comment]
> BTW, i am now running the minio server using "gateway nas" instead of "server" in my docker command

The code path is the same so it shouldn't cause problems. 

> I have been doing some additional tracing. When I try to delete an object, minio can successfully delete the actual file for NFS. It then tries to rename fs.json to .nfs000000000000493800001450 for example. This fails with error 10046 which I believe is "NFS4ERR_FILE_OPEN"

Do you have a tcpdump from the NFS client for us to look at? - From what it looks like your NAS server is returning an error. This doesn't happen on local disks so I am not sure why. Should you contact your vendor?

**Comment by MarwanElSherif** [comment]
Issue is fixed. A configuration item had to be changed on the VNX box for the NFS server. It is called the "File Locking Policy" and it is set to "mandatory" by default. This setting had to be changed to "Advisory" after which is issue was resolved.

An explanation of each is provided in the document in the link below:
[https://www.emc.com/collateral/TechnicalDocument/docu48461.pdf](url)

**Comment by nitisht** [comment]
Thanks for the info @MarwanElSherif
