### ISSUE TITLE
Disk Caching in gateway mode for B2 / GCS seem not working

### ISSUE THREAD

**Issue by bennykwok** [minio/minio#6314]
## Expected Behavior
File will be cached in cache disk or cache directory after upload / download.

## Current Behavior
Noting save in the cache disk or cache directory

## Steps to Reproduce (for bugs)

export MINIO_ACCESS_KEY=XXXXXXX
export MINIO_SECRET_KEY=XXXXXXX
export GOOGLE_APPLICATION_CREDENTIALS=/usr/local/minio/XXXXX.json
export MINIO_CACHE_DRIVES="/mnt/minio-cache"
export MINIO_CACHE_EXPIRY=40
export MINIO_CACHE_MAXUSE=80
minio gateway gcs XXXXXX

OR 

Docker version:
docker run -p 9000:9000 -e "MINIO_ACCESS_KEY=XXXXXXX" -e "MINIO_SECRET_KEY=XXXXXXX" -e "GOOGLE_APPLICATION_CREDENTIALS=XXXXXXXX.json" -e "MINIO_CACHE_DRIVES=/mnt/minio-cache" -v /usr/local/minio/XXXXX.json:/usr/local/minio/XXXXX.json -v /mnt/minio-cache:/mnt/minio-cache  minio/minio gateway gcs XXXXXX

## Your Environment
* Version used (`minio version`):
minio version
Version: 2018-08-18T03:49:57Z
Release-Tag: RELEASE.2018-08-18T03-49-57Z
Commit-ID: 9f14433cbd4bde157b00c2afe3228bac0fe1f9d9

OR 
Docker minio/minio version
Version: 2018-08-18T03:49:57Z
Release-Tag: RELEASE.2018-08-18T03-49-57Z
Commit-ID: 9f14433cbd4bde157b00c2afe3228bac0fe1f9d9

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
I could reproduce this fixed in #6312

**Comment by harshavardhana** [comment]
Fixed in #6312
