### ISSUE TITLE
Build errors go1.11rc1 due to vendored rjeczalik/notify lib

### ISSUE THREAD

**Issue by steveoc64** [minio/minio#6315]
## Expected Behavior
`go get -u github.com/minio/minio` should build cleanly with latest go1.11rc1

## Current Behavior
* using go1.11rc1
```
go get -u github.com/minio/minio
# github.com/minio/minio/vendor/github.com/rjeczalik/notify
./watcher_fsevents_cgo.go:51: cannot convert nil to type _Ctype_CFAllocatorRef
./watcher_fsevents_cgo.go:165:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
./watcher_fsevents_cgo.go:166:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
```
Build error in vendored notify library, as found in vendor/github.com/rjeczalik/notify.

* using go1.10.3
```
go get -u github.com/minio/minio
```
builds with no errors.

## Possible Solution
Doing a `go get -u github.com/rjeczalik/notify` builds without errors under go1.11rc1, so it could be a simple matter of updating the vendored repo to the latest version.  Dont know yet how much work that might entail, or what else might need fixing if that lib is updated.

Will investigate later.

## Steps to Reproduce (for bugs)

* setup latest go1.11rc1 release (preferrably in a jail or separate test env)
* `go get -u github.com/minio/minio`
* observe 3 compile errors, as above

## Context
Setting up test environment to validate go1.11rc1 for our codebase.

## Your Environment
```
$ go version
go version go1.11rc1 darwin/amd64
```

minio version - up to date on master, as of commit 7d7e21aebb159d1ab84906b548eee6e9bc54750a

**Comment by steveoc64** [comment]
Note that the latest release of rjeczalik/notify does actually have an extra little bit of code, controlled with build flags to accommodate go1.11rc1

https://github.com/rjeczalik/notify/blob/master/watcher_fsevents_go1.10.go
vs
https://github.com/rjeczalik/notify/blob/master/watcher_fsevents_go1.11.go

the second file defines 
```
// +build darwin,!kqueue,go1.11
package notify
const refZero = 0
```

Which explains it all.  Should be a trivial fix to get minio working under go1.11rc1

(but that's definitely a gotcha for any cgo code to be kept up to date in future .. wasn't aware of that one)

**Comment by kannappanr** [comment]
@steveoc64 Thanks for filing this issue. Will update the code of `github.com/rjeczalik/notify` in the vendor directory to the latest one.

**Comment by steveoc64** [comment]
While you are at it - update `vendor/minio/highwayhash` as well - there is some amd64 asm code in here . https://github.com/minio/minio/blob/master/vendor/github.com/minio/highwayhash/highwayhashAVX2_amd64.s#L253

(its invoking a private function in the Go runtime by hitting it directly with an asm call)

go1.11rc1 has dropped that private function, and they do the AVX2 stuff in a different (private) area now.  Interesting.

Anyway, pulling in the latest minio/highwayhash into the vendored area seems to make it all build.

Nice !
