### ISSUE TITLE
Signaturedoesnotmatch error while routing request through HAProxy

### ISSUE THREAD

**Issue by vishk35** [minio/minio#6319]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Can you provide more details on this issue minio version, haproxy version and configuration. Sample commands or API used to result in this error.

Will close this issue as incomplete. Please reopen the issue when you have these details.
