### ISSUE TITLE
SignatureDoesnotMatch error when routing request through HAProxy

### ISSUE THREAD

**Issue by vishk35** [minio/minio#6320]
When I post request to minio server using hostname:port the request goes through. However if use HAProxy I am getting error SignatureDoesNotMAtch.  
I am using aws-sdk-javascript to access and upload files to minio server. I did print the request received on minio by enabling trace log 
HAProxy version is 1.7
Minio :- RELEASE.2018-08-18T03-49-57Z

Request
GET /bucket/1111117
Host:abc-dv.example.net
User-Agent:aws-sdk-nodejs/2.286.2 win32/V8.9.4 callBack
Authorization: AWS4-HMAC-SHA256 Credential="SOMECREDENTIAL/20180820/us-east-1/s3/aws-request, SignedHeaders=host;x-amz-content-sha256;x-amz-data, Signature=somesignature
X-Amz-Content-Sha256: contentkey
X-Amz-Date: 20180820T161020Z
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@vishk35 Thanks for filing this issue. We will try to reproduce this issue, with HA proxy. Just want to confirm that this is a normal `putobject` call that you are trying using `aws-sdk-js`, if not do you mind sending us a sample code that might be useful in reproducing this issue.

**Comment by vishk35** [comment]
yes this is normal putobject call  using aws-sdk-js

**Comment by kannappanr** [comment]
Do you mind sharing the `HAProxy` config file and also more info about your `minio` setup.

**Comment by vishk35** [comment]
backend service_name
balance roundrobin
cookie service_name insert indirect nocache
option httpchk GET /minio/health/live
option forwardfor
option httplog
request
reqrep ^([^\]*\)/ms/file-store/V1-0-0/bucket_name(.*) \1/bucket_name\2
server service_name_serverhost_9000 host1:9000 cookie service_name_1 check inter 30000
server service_name_serverhost_9000 host2:9000 cookie service_name_2 check inter 30000
rsprep ^([^\]*\)/bucket_name(.*) \1/ms/file-store/V1-0-0/bucket_name\2

**Comment by vishk35** [comment]
Is this because of my endpoint url ? As aws sdk is using enpoint url to generate signature and when it sends request to minio it is stripping off path variables from my endpoint url ?
For example:- my end point passed to aws -sdk is http://loadbalanceurl/ms/servicename/env/v1-0-0

On request received in minio only loadbalanceurl is received in host header

**Comment by kannappanr** [comment]
Yes. Signature mismatch usually happens when the `host` header is modified by the proxy.

**Comment by vishk35** [comment]
does it affect if path in url is modified and host is not?

**Comment by vishk35** [comment]
is there a way i can add context root to minio server?

**Comment by kannappanr** [comment]
@vishk35 The endpoint for `minio` has to be of the form `url:port` . You cannot have endpoints in the form that you have here. 

I don't think we can add context root to minio server.

**Comment by vishk35** [comment]
Thanks for the help We fixed this issue aws-sdk was using path variables to generate signature. And we were stripping those path variables in HAProxy.

**Comment by nitisht** [comment]
Shall we close this issue then @vishk35

**Comment by harshavardhana** [comment]
Closing as working as intended.

**Comment by giezi** [comment]
Hi @vishk35 

How did you fixed the issue with stripping those path variables in HAProxy?

Many thanks!

best regards
Reto
