### ISSUE TITLE
Request: Specify actual bytes sent in getObject notification.

### ISSUE THREAD

**Issue by guanzo** [minio/minio#6321]
I need to record all bytes that minio sends in a getObject response.  Currently, the getObject notification event only has the total size of an object. If the getObject request was for a byte range, the event doesn't reflect that at all. This makes accurate data egress analytics impossible to do at the moment.

## Expected Behavior

The getObject notification event should include the `Content-Range` and/or the `Content-Length` header of the response, if the http request contained a `Range` header. It should report the number of bytes that was actually sent in the response.

## Current Behavior

The getObject notification event only contains the object size.

## Possible Solution

Add the `Content-Range` and/or the `Content-Length` header to the getObject notification event.

## Steps to Reproduce (for bugs)

1. Request a range of bytes from the minio server.
2. Examine the notification event object.

## Context

I'm attempting to record all data egress from the minio server. This will help us charge our customers for the correct amount of bandwidth.

**Comment by kannappanr** [comment]
@guanzo Thanks for filing this issue. It doesn't seem to be part of the actual S3 event structure. Will check internally if we want to add this information as part of the notification event and get back to you.

**Comment by harshavardhana** [comment]
> @guanzo Thanks for filing this issue. It doesn't seem to be part of the actual S3 event structure. Will check internally if we want to add this information as part of the notification event and get back to you.

GET object based notification is Minio extension already @kannappanr we can add this and it is a good idea anyways.
