### ISSUE TITLE
Display warning on Minio Browser when user tries to download object encrypted with SSE-C

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#6322]
## Expected Behavior

The UI should display a warning telling the user that the object they are trying to download is stored using SSE-C and it can't be downloaded using the browser for now.

## Current Behavior

When a single object with SSE-C is downloaded by the user, they are directed to the XML file of the response for the request that was made which has the message `The object was stored using a form of Server Side Encryption. The correct parameters must be provided to retrieve the object.`. When the user tries to download multiple files that contain an SSE-C encrypted object, the files do not download and nothing happens on the UI (such that it acts as if the user hasn't even clicked on the "Download as Zip" button). The user can verify from their browser's developer's console that this is a 400 Bad Request and a similar message is seen on the response for this request.

## Possible Solution

We can use the Alert component that is already there to display the warning when the user tries to download an SSE-C encrypted file.

## Steps to Reproduce (for bugs)

1. Have an SSE-C encrypted object in any of your buckets
2. Try to download the single encrypted object via the browser
3. Verify that the XML message is seen on "Download Object" click
4. Try downloading multiple objects via the browser
5. Observe that nothing happens on the UI side, however a 400 Bad Request is seen on the developer's console.

## Context

This issue would cause confusion for any users that have SSE-C encrypted objects in their buckets when they would like to download that object via the Minio Browser

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1): play.minio.io
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
is this fixed @kaankabalak @kannappanr ?

**Comment by kannappanr** [comment]
Not yet.

**Comment by kaankabalak** [comment]
There is a slight problem extracting the error message for the case where a user tries to download a zip file containing an encrypted file, as the error seems to be written on top of the response. The response looks like the following:

![screen shot 2018-08-31 at 2 47 40 pm](https://user-images.githubusercontent.com/27314853/44937272-48202580-ad2d-11e8-9c48-3931269ae533.png)

Returning the same SSE-C specialized error message for whenever we get a 400 Bad Request didn't seem right, as it is possible that we might get the status code for different errors as well.
