### ISSUE TITLE
SSE encryption in gateway mode for multipart operations

### ISSUE THREAD

**Issue by poornas** [minio/minio#6323]
Need decision on approach to multipart encryption in gateway mode. 

When SSE is specified on multipart upload for minio server encrypted object, we have a mechanism to store the individual part chunk size of the encrypted part via the metadata. 

In the case of gateway, the S3 backend stores the object (parts) and does not have / does not reveal the size of each individual part to the gateway. Since the metadata is specified when the multipart upload is initiated, the part size sent in the subsequent upload part requests cannot be known in advance. For proper decryption at the gateway,gateway needs to know the size of each part

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
@aead / @poornas  we need to discuss this and decide on a design.

**Comment by harshavardhana** [comment]
@poornas can you write down what we decided here?

**Comment by poornas** [comment]
gateway will support encryption for multipart uploads with fixed size

**Comment by aead** [comment]
> gateway will support encryption for multipart uploads with fixed size

@poornas AFAICS this will not work

**Comment by harshavardhana** [comment]
> @poornas AFAICS this will not work

@aead a fixed size is possible we need to do how GCS/Azure gateway implement multipart.

**Comment by deekoder** [comment]
This is now unblocked after our discussion yesterday.
