### ISSUE TITLE
Error: write tcp ... i/o timeout

### ISSUE THREAD

**Issue by ghost** [minio/minio#6328]
We are using a 4 core server as a single instance with 32gb memory on Microsoft Azure, attempting to save 10,000 objects all at average size of ~10mb, when the server has 10,000 objects in it, the write times to save an object of 10mb jump up to 5 minutes, and then eventually we get timeout errors. 

## Expected Behavior
Minio will save an object in a reasonable amount of time.

## Current Behavior
```
Aug 21 18:45:52 grok-minio[12681]: API: GetObject(bucket=default, object=a4447fcf-c51d-48f0-b32d-b6fb1ea9a2f4)
Aug 21 18:45:52 grok-minio[12681]: Time: 18:45:52 UTC 08/21/2018
Aug 21 18:45:52 grok-minio[12681]: RequestID: 154CFA5D644E3D00
Aug 21 18:45:52 grok-minio[12681]: RemoteHost: 10.10.5.10
Aug 21 18:45:52 grok-minio[12681]: UserAgent: Minio (Linux; x86_64) minio-py/4.0.3
Aug 21 18:45:52 grok-minio[12681]: Error: write tcp 10.10.5.12:9000->10.10.5.10:59706: i/o timeout
Aug 21 18:45:52 grok-minio[12681]:        1: cmd/fs-v1.go:599:cmd.(*FSObjects).getObject()
Aug 21 18:45:52 grokminio[12681]:        2: cmd/fs-v1.go:519:cmd.(*FSObjects).GetObject()
Aug 21 18:45:52 grok-minio[12681]:        3: cmd/object-handlers.go:178:cmd.(ObjectLayer).GetObject-fm()
Aug 21 18:45:52 grok-minio[12681]:        4: cmd/object-handlers.go:184:cmd.objectAPIHandlers.GetObjectHandler()
Aug 21 18:45:52 grok-minio[12681]:        5: cmd/api-router.go:75:cmd.(objectAPIHandlers).GetObjectHandler-fm()
Aug 21 18:45:52 grok-minio[12681]:        6: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

## Steps to reproduce
Create a single minio instance on a 4 core server with 32gb memory, fill it with ~100gb of data, attempt to send 100 or more objects of ~10mb size to the minio instance.

## Possible Solution
Add more nodes?

## Your Environment
* Minio Version: ﻿﻿2018-08-21T00:37:20Z
* Operating System: Ubuntu 16

**Comment by kannappanr** [comment]
@kyle-sorensen Thanks for filing this issue. Can you please update the version of `minio` that you are using?

**Comment by ghost** [comment]
@kannappanr updated

**Comment by ghost** [comment]
The following was found in the syslog right around when we had a drop in network performance

> Aug 21 22:43:05 grok-mongo kernel: [3974455.137377] DCCP: Activated CCID 2 (TCP-like)

We are editing some sysctl values and will update our results.

**Comment by ghost** [comment]
```

sudo sysctl vm.overcommit_memory=1
sudo sysctl -w net.core.somaxconn=65535


sudo sed -i '/\ *[eE]nd/i \
 \
# File limits increase \
*         hard    nofile      500000 \
*         soft    nofile      500000 \
root      hard    nofile      500000 \
root      soft    nofile      500000' /etc/security/limits.conf

sudo sed -i '/\ *[eE]nd/i \
 \
# File limits increase requirement \
session required pam_limits.so' /etc/pam.d/common-session

sudo su -c "echo -e '# Increasing file limits\nfs.file-max = 2097152\n' >> /etc/sysctl.conf"
```

These are some changes we made and it looks like the problem has been resolved.

**Comment by harshavardhana** [comment]
> sudo sysctl -w net.dccp.default.seq_window=10000
> sudo sysctl -w net.dccp.default.rx_ccid=2
> sudo sysctl -w net.dccp.default.tx_ccid=2

This looks like you are using dccp protocol?

**Comment by ghost** [comment]
@harshavardhana Yes, this was honestly new to us. They are Azure VM's for load testing...looks like we flooded the kernel?

Actually doesn't seem we are using DCCP, it was just a fluke info log put in the syslog

**Comment by harshavardhana** [comment]
We have never really tested with DCCP enabled @kyle-sorensen so I am curious if these changes can go into https://github.com/minio/minio/tree/master/docs/deployment/kernel-tuning 

If the issue is resolved, feel free to close this issue.

**Comment by ghost** [comment]
@harshavardhana I have confirmed we don't have DCCP enabled, we still get this error. Seems to happen after about 100-200gb of data is in the system.

**Comment by ghost** [comment]
Actually, I see we have not done a lot of that kernel tuning you recommend. We will try those, thanks!

@harshavardhana

**Comment by harshavardhana** [comment]
> Actually, I see we have no done a lot of that kernel doing you recommend. We will try those, thanks!

Well, it's not needed, but thought perhaps it can be added to our docs as well what you did on your deployment. In any case, do you still see this problem?

**Comment by ghost** [comment]
@harshavardhana 

Yes we still see the problem. 

 * 4 core
 * 32G memory
 * Ubuntu 16.04
 * Microsoft Azure

 * 10,000 - 15,000 objects
 * 150G -200G data
 * 8mb average object size 

`/usr/local/bin/minio server --address 0.0.0.0:9000 /mnt/data/data1 /mnt/data/data2 /mnt/data/data3 /mnt/data/data4`

We are using the python SDK. Eventually things just start to timeout like the Golang stack trace above, if we restart the system it goes back to functioning normally, `mc heal` doesn't find anything broken. Difficult to say whats going on here, we implemented all your kernel and disk tuning. The CPU and memory on this server is never under more than 50% load at any given time. Maybe we are being throttled by Microsoft.

**Comment by vadmeste** [comment]
> if we restart the system

Do you mean restart Minio or restart the whole VM ?

Also, can you describe more the operation you are doing ? it looks like you are using minio-py to upload data from another VM in Azure, right ? if so what your minio-py shows ? is it possible that the second machine suffocate ?

**Comment by ghost** [comment]
@vadmeste It's when we restart the minio service with `service minio restart`, all the timeout errors stop and the system behaves normally. 

It's possible that the other VM we are using to pump data into minio is getting suffocated, yes, looking into that now but I doubt it, I will update you.

**Comment by ghost** [comment]
If the server pumping data into minio was at 100% load, its possible this error is coming from the python client and not minio...?

**Comment by vadmeste** [comment]
> If the server pumping data into minio was at 100% load, its possible this error is coming from the python client and not minio...?

What about restarting the server or the tool which is pumping data ?

**Comment by ghost** [comment]
@vadmeste its not that server, this is a real problem, we did the same experiment with mongodb and there were no issues....

**Comment by harshavardhana** [comment]
Minio and mongodb are two different types of software. The comparison is not correct we should look at nginx v/s Minio in your scenario.

**Comment by vadmeste** [comment]
@kyle-sorensen can you share you python code which reproduces the problem ?

**Comment by ghost** [comment]
@vadmeste I cannot share the code because its proprietary, but i can describe it. Its a typical fire and forget docker container architecture. Separating the code in a way that would be okay to post here would be cumbersome. The objects uploaded and downloaded to minio are between 5-11mb.

**Comment by harshavardhana** [comment]
Closing this issue as stale, please reopen if seen again.
