### ISSUE TITLE
Minio does not support SSE-S3 encryption without vault

### ISSUE THREAD

**Issue by gmatev** [minio/minio#6329]
Minio now has support for SSE-KMS and SSE-C which is great but to achieve broader compatibility it is necessary to also support SSE-S3 (server manages the AES256 keys directly without relying on Vault https://github.com/minio/minio/pull/6192). A number of clients are potentially relying on this behavior and are sending server side encryption headers without keys. To be able to easily move these to Minio will require SSE-S3 support

## Expected Behavior
When request containing headers equivalent to SSE-S3 come in Minio should be able to use Minio managed keys to encrypt the objects on disk 

## Current Behavior
When SSE-SE requests come in Minio will return an error unless KMS vault is setup.

**Comment by harshavardhana** [comment]
Vault is an important requirement from security point of view for managing keys.

Are you saying we should re-implement what vault is doing ?

**Comment by aead** [comment]
@gmatev We're already working on SSE-S3 functionality without a external KMS. It will be possible to directly specify a master key as part of the server configuration. However we have to finalize the design. Will keep you posted.

**Comment by gmatev** [comment]
Thanks @aead . Your approach makes sense. Vault configuration is just a bit involved especially in cases where people are doing quick evals and end up hitting a tool that forces SSE-S3 without the option to change (e.g. WAL-E)

**Comment by aead** [comment]
Just for you information @gmatev : Minio server does not support SSE-KMS yet. The reason is that SSE-KMS requires IAM user management polices for the CMK-IDs. Therefore the server should reject SSE-KMS requests with `not implemented`. We may add SSE-KMS in the future but we have to evaluate and make a clean design first.

**Comment by gmatev** [comment]
@aead understood. Thank you for the clarification.
