### ISSUE TITLE
Key rotation is failing when the object is encrypted with SSE-C

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#6330]
## Expected Behavior
Expect key rotation to work and the object be allowed to be downloaded using the new key

## Current Behavior
Statobject is failing when there is Key rotation and SSE-C. is used in both the source and the destination.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
can you paste your command line params @kannappanr ?
