### ISSUE TITLE
minio worm capabilities

### ISSUE THREAD

**Issue by KuladeepK** [minio/minio#6336]
Hi Team,

Please clarify below concerns with worm enabled minio.

1. is there any way we can set up retention policy on object which is created in worm minio.
2. Once we create the file in worm enabled bucket, when we can delete the file?
3. We upload a file into worm minio, and then we disabled worm and restarted minio server. after that also we are not able to delete the file.
4. Please provide a link or document about minio worm capabilities.

thanks
Kuladeep.K

@nitisht @rambg

**Comment by nitisht** [comment]
Hey @KuladeepK thanks for the issue. Let me check and get back to you on this.

**Comment by poornas** [comment]
@nitisht, this is related to config move to backend [https://github.com/minio/minio/pull/6302#pullrequestreview-147413666]. When worm mode is set, it cannot be disabled right now including when the worm mode is being toggled. When @ebozduman/@vadmeste is ready with admin changes to set config by particular key, the admin handler needs to change to allow worm config to be changed when worm key is enabled/disabled.

**Comment by harshavardhana** [comment]
> @nitisht, this is related to config move to backend [https://github.com/minio/minio/pull/6302#pullrequestreview-147413666]. When worm mode is set, it cannot be disabled right now including when the worm mode is being toggled. When @ebozduman/@vadmeste is ready with admin changes to set config by particular key, the admin handler needs to change to allow worm config to be changed when worm key is enabled/disabled.

You can @poornas SetConfig doesn't reject WORM toggling.

**Comment by poornas** [comment]
you are right @harshavardhana , latest release allows it.

**Comment by nitisht** [comment]
Hello @KuladeepK here are the answers - 

> is there any way we can set up retention policy on object which is created in worm minio.

Could you clarify a bit - do you mean a policy to delete the object after a certain time or something else? Is there an AWS S3 equivalent feature that you can point us to. 

> Once we create the file in worm enabled bucket, when we can delete the file?

By default objects in WORM can never be deleted. To delete such files, you'll need to restart the server with WORM disabled.

>  We upload a file into worm minio, and then we disabled worm and restarted minio server. after that also we are not able to delete the file.

This was a bug that was fixed. Can you try with release `RELEASE.2018-08-21T00-37-20Z`. This should be fixed.

> Please provide a link or document about minio worm capabilities.

MInio WORM features are straightforward to avoid any complications. I will list down everything here to give you an idea. 

```
Start Minio server in WORM mode by setting the environment variable `MINIO_WORM=true`. Once Minio server is running in WORM mode, it is not possible to update / delete / modify an object. To delete / modify an object, you can restart the server with WORM mode disabled. 

You can combine WORM with Minio Server Side Encryption (SSE) to build a completely object tamper proof setup.
```
Please do let me know if there are any further questions.

**Comment by deekoder** [comment]
A fix is in progress for this via https://github.com/minio/minio/pull/6168

**Comment by nitisht** [comment]
closing this for now as there are no plans to do this currently.
