### ISSUE TITLE
How to use Oauth2 with Minio

### ISSUE THREAD

**Issue by Jeremytetu** [minio/minio#6337]
I'm trying to use Oauth2 for my stockage minio.

## Expected Behavior

I used https://github.com/bitly/oauth2_proxy in front, with my minio as Upstream serveur.
After authentication, I should be able to get my minio interface. 

## Current Behavior

This is what Minio answers once the authentication done:
```
<Error>
<Code>InvalidRequest</Code>
<Message>
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
</Message>
<Resource>/</Resource>
<RequestId/>
<HostId>3L137</HostId>
</Error>
```

## Possible Solution

It looks like Minio reads token in the header.
How to remove this feature ?

I saw that Minio implement Oauth2 (https://github.com/minio/minio/blob/master/vendor/golang.org/x/oauth2/oauth2.go)
But no documentation about it

So my question is : how to use oauth on Minio ? :)

## My config
config minio : I'm using default config file present in the docker container.
docker run -d -p 9000:9000 minio/minio server /data

config oauth_proxy : 
[config_oauth.txt](https://github.com/minio/minio/files/2310495/config_oauth.txt)

**Comment by harshavardhana** [comment]
Minio implements AWS S3 compatible signature V4 and V2. Oauth is not part of S3 spec.

**Comment by harshavardhana** [comment]
> Minio implements AWS S3 compatible signature V4 and V2. Oauth is not part of S3 spec.

Closing this as answered, once Oauth2 is supported by AWS S3 spec we will follow as well. We are planning to introduce Minio STS API based on ClientGrants PR is available here https://github.com/minio/minio/pull/6168
