### ISSUE TITLE
Parallel uploads made minio to be killed by kernel

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#6338]
## Setup Information:
* 8 servers of [t1.small.x86](https://www.packet.net/bare-metal/servers/t1-small/)
* minio version
```
Version: 2018-08-22T12:25:38Z
Release-Tag: DEVELOPMENT.2018-08-22T12-25-38Z
Commit-ID: 8601f29d95f2ad2055613bedcc917e692ffab5fd
```
* mc version
```
Version: 2018-08-11T04:32:07Z                                                                                                                                            
Release-tag: DEVELOPMENT.2018-08-11T04-32-07Z                                                                                                                            
Commit-id: 22b8ab43bd26c73e3a9037c6d461bfd95307c96d
```

## 10MiB sized objects of 448 parallel uploads
* Below script is run for uploading *448* parallel uploads of 10MiB objects to node1. 

```bash
#!/bin/bash                                                                                                                                                              

mc --quiet --no-color mb node1/mybucket

for (( i = 1; i <= 448; i++ )); do
    mc --quiet --no-color cp 10mb/10mb node1/mybucket/10mb-$i &
done

wait
```

* Below is memory profile of node1.
```
~/run/10mb/448# go tool pprof ~/golang/gopath/bin/minio node1.mem.pprof 
File: minio
Type: inuse_space
Time: Aug 22, 2018 at 2:04pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 4297588.23kB, 99.76% of 4307914.91kB total
Dropped 458 nodes (cum <= 21539.57kB)
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
 2969600kB 68.93% 68.93%  2969600kB 68.93%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
1027209.60kB 23.84% 92.78% 1027209.60kB 23.84%  bytes.makeSlice
  300456kB  6.97% 99.75%   300456kB  6.97%  encoding/gob.encUint8Array
  250.05kB 0.0058% 99.76% 2970366.60kB 68.95%  github.com/minio/minio/cmd.xlObjects.putObject
   32.25kB 0.00075% 99.76% 300496.63kB  6.98%  encoding/gob.(*Encoder).encodeStruct
   20.16kB 0.00047% 99.76% 1328342.44kB 30.83%  github.com/minio/minio/cmd.(*RPCClient).Call
    8.06kB 0.00019% 99.76% 2972331.34kB 69.00%  github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP
    4.06kB 9.4e-05% 99.76%  1328100kB 30.83%  github.com/minio/minio/cmd.(*StorageRPCClient).AppendFile
    4.03kB 9.4e-05% 99.76% 1327749.15kB 30.82%  encoding/gob.(*Encoder).EncodeValue
    4.02kB 9.3e-05% 99.76% 2972323.28kB 69.00%  github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP
(pprof) 
```
* From 484 parallel uploads of 10MiB object made minio on node1 to be killed by the kernel.

## 100MiB sized objects of 80 parallel uploads
* Below script is run for uploading *80* parallel uploads of 10MiB objects to node1. 
```bash
#!/bin/bash                                                                                                                                                              

mc --quiet --no-color mb node1/mybucket

for (( i = 1; i <= 80; i++ )); do
    mc --quiet --no-color cp 100mb/100mb node1/mybucket/100mb-$i &
done

wait
```
* Below is memory profile of node1.
```
~/run/100mb/80# go tool pprof ~/golang/gopath/bin/minio node1.mem.pprof 
File: minio
Type: inuse_space
Time: Aug 22, 2018 at 2:28pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 1439682.92kB, 99.39% of 1448493.43kB total
Dropped 498 nodes (cum <= 7242.47kB)
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
  983040kB 67.87% 67.87%   983040kB 67.87%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
425806.43kB 29.40% 97.26% 425806.43kB 29.40%  bytes.makeSlice
30820.35kB  2.13% 99.39% 30820.35kB  2.13%  encoding/gob.encUint8Array
    4.06kB 0.00028% 99.39% 456748.43kB 31.53%  github.com/minio/minio/cmd.(*StorageRPCClient).AppendFile
    4.03kB 0.00028% 99.39% 456682.97kB 31.53%  encoding/gob.(*Encoder).EncodeValue
    4.03kB 0.00028% 99.39% 983995.74kB 67.93%  github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP
    4.01kB 0.00028% 99.39% 983162.07kB 67.87%  github.com/minio/minio/cmd.xlObjects.PutObjectPart
         0     0% 99.39% 425806.43kB 29.40%  bytes.(*Buffer).Write
         0     0% 99.39% 425806.43kB 29.40%  bytes.(*Buffer).grow
         0     0% 99.39% 456682.97kB 31.53%  encoding/gob.(*Encoder).Encode
(pprof) 
```
* From 88 parallel uploads of 100MiB object made minio on node1 to be killed by the kernel.

**Comment by harshavardhana** [comment]
What is your RAM size ?

**Comment by alexsandro-xpt** [comment]
Are you running it under Docker Containers?

**Comment by balamurugana** [comment]
As specified in the description, machine configuration is [t1.small.x86](https://www.packet.net/bare-metal/servers/t1-small/)

**Comment by harshavardhana** [comment]
Currently there is no way to avoid allocation of 10MiB per request when you have 448 requests in parallel it's 4G allocated. Currently there is no way to know how much RAM the system has too.

So this sort of limits how much of parallel requests can be sent to Minio.

When 100MiB is uploaded too it's the same you have infact two parallel uploads in progress minimum 88 uploads become 176 uploads ..so in parallel around 1.7G of memory active.

On top of this we have Gob based bytes.Buffer allocating more and more memory sending to server. This increases the load until the GC cycle can kick in.

You might try running Minio server with GOGC=20 environment variable from its default 100 value.

**Comment by balamurugana** [comment]
10MiB test > 448 parallel uploads killing the server is completely acceptable as each upload on server takes 20MiB x 448 is ~ 8GiB memory.

Whereas 100MiB test of > 80 parallel uploads killing the server is not completely straight-forward.  As `mc` is used in the test, `mc` is uploading 100MiB in parallel using two threads (100MiB / 64 MiB ~ 2 threads).  With this numbers `2 x 20MiB x 88 ~ 3.5GiB` doesn't use  8GiB RAM fully but minio was killed in the workload.  Due to this killing, there is no memory profile.

**Comment by balamurugana** [comment]
I modified `mc` to use single thread to multipart-uploads.  Now I am able to do 128 parallel uploads of 100MiB objects.  Below is memory profile
```
root@bala-test-pr6206:~/run/100mb/128# go tool pprof ~/golang/gopath/bin/minio node1.mem.pprof 
File: minio
Type: inuse_space
Time: Aug 23, 2018 at 1:13pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 187.11MB, 98.60% of 189.76MB total
Dropped 366 nodes (cum <= 0.95MB)
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
     160MB 84.32% 84.32%      160MB 84.32%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
   18.06MB  9.52% 93.83%    18.06MB  9.52%  bytes.makeSlice
    9.05MB  4.77% 98.60%     9.05MB  4.77%  encoding/gob.encUint8Array
         0     0% 98.60%    18.06MB  9.52%  bytes.(*Buffer).Write
         0     0% 98.60%    18.06MB  9.52%  bytes.(*Buffer).grow
         0     0% 98.60%    27.15MB 14.31%  encoding/gob.(*Encoder).Encode
         0     0% 98.60%    27.15MB 14.31%  encoding/gob.(*Encoder).EncodeValue
         0     0% 98.60%     9.07MB  4.78%  encoding/gob.(*Encoder).encode
         0     0% 98.60%     9.05MB  4.77%  encoding/gob.(*Encoder).encodeStruct
         0     0% 98.60%    18.06MB  9.52%  encoding/gob.(*Encoder).writeMessage
(pprof) 
```
minio is killed for 136 parallel uploads are triggered.  Theoretically it supposes to use `1 x 20MiB x 136 = 2.7GiB` but killed by the kernel.

**Comment by harshavardhana** [comment]
Generate the PDF `top10` is not really fully indicative of the situation, if you see bytes.Buffer is only indicated, you can use these options to get a better understanding of allocated bytes.

```

  -inuse_space      Display in-use memory size
  -inuse_objects    Display in-use object counts
  -alloc_space      Display allocated memory size
  -alloc_objects    Display allocated object counts
```

**Comment by balamurugana** [comment]
Attaching PDF outputs the test.

[alloc_objects.pdf](https://github.com/minio/minio/files/2315587/alloc_objects.pdf)
[alloc_space.pdf](https://github.com/minio/minio/files/2315589/alloc_space.pdf)
[inuse_objects.pdf](https://github.com/minio/minio/files/2315590/inuse_objects.pdf)
[inuse_space.pdf](https://github.com/minio/minio/files/2315591/inuse_space.pdf)

**Comment by harshavardhana** [comment]
If you look at the alloc_space PDF you can see the bytepool is only 5% of the overall allocation. The major allocation that is happening is in Gob and bytes.Buffer

**Comment by harshavardhana** [comment]
And in_use i.e acitve is only 200MiB, most of the memory here which led to the crash is given to GC which didn't clean up quickly in it's default 2x growth logic.

**Comment by balamurugana** [comment]
It looks like 43GiB of memory was allocated (but why 43GiB of memory used) and it should had been freed up as well. Otherwise `top10` could have showed who is holding.
```
encoding/gob
encUint8Array
43512338.75kB (74.07%)
```

**Comment by balamurugana** [comment]
I have also tested `pkg/bpool` which is not really freeing up memory even if `runtime.GC()` is called.  It has very serious bug. By default GC is kicked in 2 minutes to 3 minutes approximately and `runtime.GC()` clears up immediately.

**Comment by harshavardhana** [comment]
bpool Is only to reuse memory it has nothing to do with GC. It keeps buffer active for future operations that is why bpool will not free in GC. Instead it keeps them active. So all future erasure operations simply get it from this pool. That is why actual allocation done by this code is only 5% as clearly indicated in the graph and active use is only 200MiB. Note this is not same as sync.Pool 

The issue is not with active memory when the crash happens. It is with allocations which happen elsewhere which were not GCed,  from a kernel point of view the memory is used since Go has still give it back which it doesn't quickly.

Independently using bpool to show it has active memory is an incorrect test, because that is it's purpose to begin with to avoid future 10MiB allocation. 

We could have a finalizer on them when they are not used with a sufficient period of time but that is not the issue here though.

top10 by default is only showing in use not allocation so always generate a pdf to get a better view.

**Comment by harshavardhana** [comment]
No one is holding the memory other than bpool, it is the problem of when GC kicks in as I suggested earlier you can test with GOGC=30 set as env which will allow for a more aggressive GC and it might not crash at all.

**Comment by harshavardhana** [comment]
From whatever I see here, I think the fundamental problem is using Gob + HTTP and they are ill-suited together. I.e gob is not designed to be allocated again and again for each Call() and Receive() behavior. 

The reason is simple if you look at net/rpc it always uses the same gob.Encoder/Decoder it first allocated when the connection was established under both situations and never creates new gob.Encoder/Decoders per RPC request and never allocates anything new to buffer the incoming stream. 

This is our fundamental challenge I believe since Gob only works on streams we are not fully utilizing the HTTP stream instead we block and buffer to validate the RPC args and then proceed with that information. But this happens for each Call() which is the culminating factor of our troubles.

net/rpc advantage is perhaps having a single connection but with other challenges. http/rpc is great with detecting connection failures but doesn't fit the gob model very well.

**Comment by balamurugana** [comment]
## 448 parallel uploads of 100MiB

```bash
$ go tool pprof minio put-object/100mb/node1.mem.pprof 
File: minio
Type: inuse_space
Time: Sep 12, 2018 at 3:46pm (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 344.75MB, 98.67% of 349.40MB total
Dropped 420 nodes (cum <= 1.75MB)
Showing top 10 nodes out of 52
      flat  flat%   sum%        cum   cum%
     260MB 74.41% 74.41%      260MB 74.41%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
   70.12MB 20.07% 94.48%    70.12MB 20.07%  bytes.makeSlice
   12.12MB  3.47% 97.95%    12.41MB  3.55%  net/http.(*Transport).dialConn
    2.51MB  0.72% 98.67%     2.51MB  0.72%  encoding/gob.encUint8Array
         0     0% 98.67%    70.12MB 20.07%  bytes.(*Buffer).Write
         0     0% 98.67%    70.12MB 20.07%  bytes.(*Buffer).grow
         0     0% 98.67%    72.64MB 20.79%  encoding/gob.(*Encoder).Encode
         0     0% 98.67%    72.64MB 20.79%  encoding/gob.(*Encoder).EncodeValue
         0     0% 98.67%     2.51MB  0.72%  encoding/gob.(*Encoder).encode
         0     0% 98.67%     2.51MB  0.72%  encoding/gob.(*Encoder).encodeStruct
(pprof)
```

## 650 parallel uploads of 10MiB

```bash
$ go tool pprof minio put-object/10mb/node1.mem.pprof 
File: minio
Type: inuse_space
Time: Sep 13, 2018 at 10:21am (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 4378719.13kB, 99.69% of 4392360.88kB total
Dropped 506 nodes (cum <= 21961.80kB)
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
 3358720kB 76.47% 76.47%  3358720kB 76.47%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
896380.05kB 20.41% 96.88% 896380.05kB 20.41%  bytes.makeSlice
  123264kB  2.81% 99.68%   123264kB  2.81%  encoding/gob.encUint8Array
  294.50kB 0.0067% 99.69% 3359727.03kB 76.49%  github.com/minio/minio/cmd.xlObjects.putObject
   20.31kB 0.00046% 99.69% 1020061.64kB 23.22%  github.com/minio/minio/cmd.(*StorageRPCClient).AppendFile
   20.16kB 0.00046% 99.69% 123288.17kB  2.81%  encoding/gob.(*Encoder).encodeStruct
   12.06kB 0.00027% 99.69% 1020451.34kB 23.23%  github.com/minio/minio/cmd.(*RPCClient).Call
    4.03kB 9.2e-05% 99.69% 3362006.56kB 76.54%  github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP
    4.02kB 9.1e-05% 99.69% 3362006.70kB 76.54%  github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP
         0     0% 99.69% 896380.05kB 20.41%  bytes.(*Buffer).Write
(pprof)
```

## 155 parallel uploads of 1GiB

```bash
$ go tool pprof minio put-object/1gb/node1.mem.pprof 
File: minio
Type: inuse_space
Time: Sep 13, 2018 at 9:58am (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 160MB, 98.40% of 162.60MB total
Dropped 371 nodes (cum <= 0.81MB)
Showing top 10 nodes out of 32
      flat  flat%   sum%        cum   cum%
     160MB 98.40% 98.40%      160MB 98.40%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
         0     0% 98.40%   160.63MB 98.79%  github.com/minio/minio/cmd.(*bucketForwardingHandler).ServeHTTP
         0     0% 98.40%   160.04MB 98.43%  github.com/minio/minio/cmd.(*cacheControlHandler).ServeHTTP
         0     0% 98.40%   160.62MB 98.78%  github.com/minio/minio/cmd.(*crossDomainPolicy).ServeHTTP
         0     0% 98.40%   160.62MB 98.78%  github.com/minio/minio/cmd.(*httpStatsHandler).ServeHTTP
         0     0% 98.40%   160.51MB 98.72%  github.com/minio/minio/cmd.(*minioReservedBucketHandler).ServeHTTP
         0     0% 98.40%   160.62MB 98.78%  github.com/minio/minio/cmd.(*pathValidityHandler).ServeHTTP
         0     0% 98.40%   160.63MB 98.79%  github.com/minio/minio/cmd.(*rateLimit).ServeHTTP
         0     0% 98.40%   160.60MB 98.77%  github.com/minio/minio/cmd.(*redirectHandler).ServeHTTP
         0     0% 98.40%   160.62MB 98.78%  github.com/minio/minio/cmd.(*requestHeaderSizeLimitHandler).ServeHTTP
(pprof)
```

## 135 parallel uploads of 2GiB

```bash
$ go tool pprof minio put-object/2gb/node1.mem.pprof 
File: minio
Type: inuse_space
Time: Sep 13, 2018 at 12:26pm (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 338804.03kB, 98.60% of 343610.02kB total
Dropped 401 nodes (cum <= 1718.05kB)
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
  245760kB 71.52% 71.52%   245760kB 71.52%  github.com/minio/minio/pkg/bpool.(*BytePoolCap).Get
   80200kB 23.34% 94.86%    80200kB 23.34%  bytes.makeSlice
   12840kB  3.74% 98.60%    12840kB  3.74%  encoding/gob.encUint8Array
    4.03kB 0.0012% 98.60% 12844.03kB  3.74%  encoding/gob.(*Encoder).encodeStruct
         0     0% 98.60%    80200kB 23.34%  bytes.(*Buffer).Write
         0     0% 98.60%    80200kB 23.34%  bytes.(*Buffer).grow
         0     0% 98.60% 93073.53kB 27.09%  encoding/gob.(*Encoder).Encode
         0     0% 98.60% 93073.53kB 27.09%  encoding/gob.(*Encoder).EncodeValue
         0     0% 98.60% 12860.25kB  3.74%  encoding/gob.(*Encoder).encode
         0     0% 98.60%    80200kB 23.34%  encoding/gob.(*Encoder).writeMessage
(pprof)
```

Memory profiles are available at https://github.com/balamurugana/minio-profile/tree/master/runs/166e998/put-object

**Comment by harshavardhana** [comment]
@balamurugana can you attach your scripts used in generating this workload?

**Comment by balamurugana** [comment]
Please refer https://github.com/balamurugana/minio-profile/tree/master/runs

**Comment by harshavardhana** [comment]
This may not be an issue anymore since we moved to REST based model from RPC

**Comment by harshavardhana** [comment]
> This may not be an issue anymore since we moved to REST based model from RPC

Closing this as fixed for now, can re-open if seen again.
