### ISSUE TITLE
minio/minio:RELEASE.2018-07-13T00-09-07Z has security vulnerabilities

### ISSUE THREAD

**Issue by sanverm2** [minio/minio#6343]
The Minio docker image is using curl 7.60.0-r1 . This version of curl has security  vulnerability. The image need to be updated to pick up the at least version 7.61.0-r0.

![image](https://user-images.githubusercontent.com/28093961/44507706-0fcc7780-a69b-11e8-9f74-0d10b79aaaed.png)

**Comment by harshavardhana** [comment]
The latest release is 2018-08-21 can you verify that as well ?

**Comment by sanverm2** [comment]
Verified that RELEASE.2018-08-21T00-37-20Z has latest version of curl 7.61.0. 

```
 RELEASE.2018-08-21T00-37-20Z
/ # curl --version
curl 7.61.0 (x86_64-alpine-linux-musl) libcurl/7.61.0 LibreSSL/2.6.5 zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-07-11


RELEASE.2018-07-13T00-09-07Z
/ # curl --version
curl 7.60.0 (x86_64-alpine-linux-musl) libcurl/7.60.0 LibreSSL/2.6.3 zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-05-16
``` 

Is it possible to fix RELEASE.2018-07-13T00-09-07Z on dockerhub ?

**Comment by harshavardhana** [comment]
> Is it possible to fix RELEASE.2018-07-13T00-09-07Z on dockerhub ?

No, it is not possible @sanverm2 these are automated builds we cannot edit them, you can upgrade to latest which has the vulnerability fixes.

**Comment by sanverm2** [comment]
Sure. thanks.

**Comment by harshavardhana** [comment]
> Sure. thanks.

Closing this as fixed in latest release.

**Comment by mkumatag** [comment]
actually we don't need curl package in those dockerfiles after the package download, let me create a PR to remove those unwanted packages.

**Comment by harshavardhana** [comment]
> actually we don't need curl package in those dockerfiles after the package download, let me create a PR to remove those unwanted packages.

yep, that can be done simply adding `apk del .build-deps` will work.
