### ISSUE TITLE
minio throw execption:cannot enable TCP_FASTOPEN(qlen=16384): protocol not available

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio#6344]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Issue lacks 

- title
- description of the problem
- minio version
- application requirements etc. 

Feel free to open a new issue with some more details we will take a look @shouldnotappearcalm
