### ISSUE TITLE
minio throw execption:cannot enable TCP_FASTOPEN(qlen=16384): protocol not available 

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio#6345]
When I run the latest minio docker image(RELEASE.2018-08-21T00-37-20Z), the console shows these error message as below
```
API: SYSTEM()
Time: 02:45:45 UTC 08/23/2018
Error: cannot enable TCP_FASTOPEN(qlen=16384): protocol not available
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/signals.go:65:cmd.handleSignals()
       3: cmd/server-main.go:369:cmd.serverMain()`
```
## Steps to Reproduce (for bugs)
1.system：centos6.8 kernel 2.6.32
2.docker pull minio
3.docker run -p 9000:9000 minio/minio server /data

## Your Environment

* minio docker image RELEASE.2018-08-21T00-37-20Z
* Server type and version:centos 6.8 kenerl 2.6.32
* Operating System and version (`uname -a`):Linux iZuf61vmeh3qzws7m9kd45Z 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@shouldnotappearcalm 2.6.32 kernel is pretty old is there a good reason that this is still being used? - not possible to move to CentOS 7.x?
