### ISSUE TITLE
Conflicting bucket policies can be added

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#6349]
## Expected Behavior

We shouldn't be able to add conflicting bucket policies from the browser.

## Current Behavior

We can add conflicting bucket policies from the browser.

## Possible Solution

Not being completely sure, we can make changes to the `web-handlers.go` file to include [this code block](https://github.com/balamurugana/minio/commit/be3d82889a1c590af6570b67d94cd75fae58062c#diff-a332614ad2487d48ea82260329c81b9aL871) that was deleted.

## Steps to Reproduce (for bugs)

1. Start from fresh FS disk
2. Login into Minio Browser
3. Create a bucket
4. Show bucket policy popup
5. Add '*' policy
6. Add 'foo' policy (This step should give an error as this conflicts with the existing '*' policy)

## Context

This will be confusing for users that set policies on their buckets.

## Regression

Yes, this issue is a regression introduced in #5790 

## Your Environment

* Version used (`minio version`): latest
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): macOS High Sierra 10.13.6
* Link to your project:

**Comment by kaankabalak** [comment]
Changed the issue title as I was also able to verify using `mc`.

The following terminal output can also be used to reproduce this issue:
```
$ mc mb myminio/test
Bucket created successfully `myminio/test`.
$ mc policy list myminio/test
$ mc policy upload myminio/test
Access permission for `myminio/test` is set to `upload`
$ mc policy list myminio/test
test/* => writeonly
$ mc policy upload myminio/test/foo
Access permission for `myminio/test/foo` is set to `upload`
$ mc policy list myminio/test
test/* => writeonly
test/foo* => writeonly
```

**Comment by harshavardhana** [comment]
> $ mc mb myminio/test
> Bucket created successfully `myminio/test`.
> $ mc policy list myminio/test
> $ mc policy upload myminio/test
> Access permission for `myminio/test` is set to `upload`
> $ mc policy list myminio/test
> test/* => writeonly
> $ mc policy upload myminio/test/foo
> Access permission for `myminio/test/foo` is set to `upload`
> $ mc policy list myminio/test
> test/* => writeonly
> test/foo* => writeonly

can you add `mc policy download` for `test/foo` ?

**Comment by kaankabalak** [comment]
@harshavardhana Looks like it sets the `test/*` policy to `none` on the `mc` policy list when I do this. However, the browser shows "Read Only" for `*` now. 

Should this policy ever be listed as `none` in the policy list, or should it be completely removed whenever it is set to `none`? If the first option is true, then the browser showing "Read Only" for `*` should be handled in the UI.

```
$ mc policy download myminio/test/foo
Access permission for `myminio/test/foo` is set to `download`
$ mc policy list myminio/test
test/* => none
test/foo* => readonly
```

**Comment by harshavardhana** [comment]
> $ mc policy download myminio/test/foo
> Access permission for `myminio/test/foo` is set to `download`
> $ mc policy list myminio/test
> test/* => none
> test/foo* => readonly

A conflicting policy here is that if you set `mc policy upload myminio/test` and `mc policy download myminio/test/foo`  - is this possible?

**Comment by kaankabalak** [comment]
@harshavardhana, looks like it is possible, I'm attaching the terminal output:
```
$ mc mb myminio/test3
Bucket created successfully `myminio/test3`.
$ mc policy list myminio/test3
$ mc policy upload myminio/test3
Access permission for `myminio/test3` is set to `upload`
$ mc policy list myminio/test3
test3/* => writeonly
$ mc policy download myminio/test3/foo
Access permission for `myminio/test3/foo` is set to `download`
$ mc policy list myminio/test3
test3/* => writeonly
test3/foo* => readonly
```

**Comment by harshavardhana** [comment]
> $ mc mb myminio/test3
> Bucket created successfully `myminio/test3`.
> $ mc policy list myminio/test3
> $ mc policy upload myminio/test3
> Access permission for `myminio/test3` is set to `upload`
> $ mc policy list myminio/test3
> test3/* => writeonly
> $ mc policy download myminio/test3/foo
> Access permission for `myminio/test3/foo` is set to `download`
> $ mc policy list myminio/test3
> test3/* => writeonly
> test3/foo* => readonly

Actually, this change is expected - I think it is not a regression instead its a full feature just like AWS S3. I tested multiple scenarios and we are working in accordance with how AWS S3 works in this scenario.

So I wouldn't consider this as a regression instead we now fully support AWS S3 style behavior including nesting etc.

**Comment by kaankabalak** [comment]
Ok, I guess this is fine then, thanks for clearing it up for me!

**Comment by kannappanr** [comment]
@balamurugana Can you also comment?

**Comment by balamurugana** [comment]
As per @harshavardhana's comment, full policy support was added as like AWS S3 in the refactor.  I won't mark any issue as regression without knowing the feature and/or tests than some assumption.

**Comment by kannappanr** [comment]
@balamurugana Thanks Bala. We wanted you to confirm. Will close this as working as intended.

**Comment by kaankabalak** [comment]
Thanks @balamurugana for confirming, sorry for opening an issue without completely knowing about it.

**Comment by YordanGeorgiev** [comment]
mc policy upload "$MINIO_HOST_ALIAS/$CONFIG_S3_BUCKET_NAME"
mc policy download "$MINIO_HOST_ALIAS/$CONFIG_S3_BUCKET_NAME"
mc policy public "$MINIO_HOST_ALIAS/$CONFIG_S3_BUCKET_NAME"
mc policy list "$MINIO_HOST_ALIAS/$CONFIG_S3_BUCKET_NAME"
