### ISSUE TITLE
Mc mirror --watch should exit if source bucket doesn't exist.

### ISSUE THREAD

**Issue by aarushiarya** [minio/minio#6352]
## Expected Behavior

mc mirror does not exit and continues watching, even if source bucket doesn't exist.

## Current Behavior

mc mirror gives an error if source bucket doesn't exist and continues watch. 

## Steps to Reproduce (for bugs)

1. Add host to mc.
2. Run mc mirror watch, enter bucketname that doesn't exist in the source.
`mc mirror --watch minio/mybucket myminio/mybucket`
3. mc gives out an error
`mc: <ERROR> Unable to perform a mirror action. The specified bucket does not exist`
4. Continues watch.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
mc version
`Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a`

**Comment by nitisht** [comment]
@aarushiarya minio/mc repo is the correct place for this issue.

**Comment by aarushiarya** [comment]
Okay. I will create issue in minio/mc
