### ISSUE TITLE
Error: The specified method (PUT) is not allowed against this resource.

### ISSUE THREAD

**Issue by iiroj** [minio/minio#6355]
After upgrading to minio [`RELEASE.2018-08-21T00-37-20Z`](https://github.com/minio/minio/releases/tag/RELEASE.2018-08-21T00-37-20Z), the [Arq](https://www.arqbackup.com) software is reporting multiple errors in the form:

```
Backup session for /Users/[my-username] started on 23 August 2018 at 12.01.16 EEST
Found completed backup record for /Users/[my-username]
Error: /Users/[my-username]/Library/Metadata/CoreSpotlight/index.spotlightV3/live.2.shadowIndexArrays: PUT https://[minio-url]/[bucket-name]/[arq-uuid]/objects/[object-uuid]: The specified method is not allowed against this resource.
Uploading files that were modified during this session.
Error: PUT https://[minio-url]/[bucket-name]/[arq-uuid]/bucketdata/[some-uuid]/refs/heads/master: The specified method is not allowed against this resource.
Scanned 7.164 GB (103792 files)
Uploaded 183.2 MB
Backup session for /Users/[my-username] ended on 23 August 2018 at 12.03.40 EEST
```

There is no console output in my minio docker, it only shows the startup information.

## Expected Behavior

The backup should just work, I guess.

## Context

Since this happens while backing up my computer, I'm left feeling uncertain if some files are actually being overwritten, or simply left out of the backup. I checked the local file above, since I found in Arq's logs, and it has been modified pretty recently:

```bash
❯ ls -l /Users/[my-username]/Library/Metadata/CoreSpotlight/index.spotlightV3/live.2.shadowIndexArrays
[2018-08-24 09:32:22 EEST] 2.0MiB live.2.shadowIndexArrays
```

In Arq's backups, however, it hasn't been updated after the errors started appearing.

## Regression

This only started yesterday when I updated my docker images. Unfortunately, I didn't check what the previous version was, but it was from around two weeks ago.

## Your Environment

Minio runs in docker:

```
minio:
    container_name: minio
    image: minio/minio
    restart: always
    command: server /data
    logging:
      driver: journald
    volumes:
      - /mnt/data:/data
    env_file: /etc/minio.env
    networks:
      - minio
```

I do not touch the default config, and the `env_file` contains the following:

```bash
MINIO_ACCESS_KEY=[snip]
MINIO_SECRET_KEY=[snip]
MINIO_BROWSER=on
```

Behind caddy 0.11.0 as a transparent proxy.

Docker host OS is `Linux 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

The computer to be backed up is:
- macOS High Sierra 10.13.6
- Arq 5.13.1

**Comment by nitisht** [comment]
@iiroj can you help us with the previous version of Minio that you were using?

**Comment by iiroj** [comment]
@nitisht From looking at the docker hub, it was either `RELEASE.2018-08-18T03-49-57Z` or `RELEASE.2018-08-02T23-11-36Z`. Is that enough? I have pruned the images so it's no longer available.

**Comment by nitisht** [comment]
Okay @iiroj . Can you try these 

- Stop Minio server and confirm if `MINIO_WORM` is set to true in that console.
- If `MINIO_WORM` is not set, can you set env var `export MINIO_HTTP_TRACE=</path/to/log.file>` and then try Arq again. `</path/to/log.file>` will have the tracing information. Can you attach that here

**Comment by iiroj** [comment]
Is this what you are looking for?

```
[REQUEST (objectAPIHandlers).PutObjectHandler-fm] [153509614.654518] [2018-08-24 07:35:46 +0000]
PUT /[arq-bucket]/[arq-id]/bucketdata/[uuid]/refs/heads/master
Host: minio.home.iiro.fi
User-Agent: arqcommitter (unknown version) CFNetwork/902.1 Darwin/17.7.0 (x86_64)
Content-Length: 41
Accept: */*
Accept-Language: en-us
Connection: keep-alive
X-Amz-Content-Sha256: 4f5bb781a2e966724de6a1291a64ee5d59ee627f399e368ee68a5c6991ca4480
Accept-Encoding: br, gzip, deflate
Authorization: AWS4-HMAC-SHA256 Credential=[MINIO_ACCESS_KEY]/20180824/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=50d1c9d5843c9afb485316e67ea8fd492071968627932338aa12bd0182b39dfe
X-Amz-Date: 20180824T073546Z
X-Forwarded-For: 192.168.1.110
X-Forwarded-Proto: https
X-Real-Ip: 192.168.1.110

<BODY>

[RESPONSE] [153509614.654518] [2018-08-24 07:35:46 +0000]
405 Method Not Allowed
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 154DC1CFDEE044FD
Server: Minio/RELEASE.2018-08-21T00-37-20Z (linux; amd64)
Accept-Ranges: bytes
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Resource>/[arq-bucket]/[arq-id]/bucketdata/[uuid]/refs/heads/master</Resource><RequestId>154DC1CFDEE044FD</RequestId><HostId>3L137</HostId></Error>
```

**Comment by nitisht** [comment]
yes this looks good, but can you also confirm if `MINIO_WORM` is set or not

**Comment by iiroj** [comment]
Ah, sorry. It's not set inside the Docker container's ENV.

**Comment by nitisht** [comment]
okay, thanks we'll take a look

**Comment by iiroj** [comment]
For what it's worth, I tagged `RELEASE.2018-08-18T03-49-57Z` in my `docker-compose.yml` and the error then went away.

**Comment by nitisht** [comment]
Marking this as regression as looks like it was working earlier.

**Comment by vadmeste** [comment]
@iiroj can you test minio/minio:edge image? It should have the fix of your issue

**Comment by iiroj** [comment]
@vadmeste Seems to work! I'm not getting any errors anymore using `minio/minio:edge `.

**Comment by harshavardhana** [comment]
> @vadmeste Seems to work! I'm not getting any errors anymore using minio/minio:edge.

We already made the release as well @iiroj so you can use `minio/minio:latest`
