### ISSUE TITLE
I using notify service redis,but i get nothing

### ISSUE THREAD

**Issue by littletow** [minio/minio#6356]
## Expected Behavior

1490686879.650649 [0 172.17.0.1:44710] "PING"
1490686879.651061 [0 172.17.0.1:44710] "HSET" 
## Current Behavior

1490686879.650649 [0 172.17.0.1:44710] "PING"
## Steps to Reproduce (for bugs)

1.docker run minio
2.docker run redis:3.2
3.docker run mc
4.mc config minio
5.mc admin config get myminio/ > /tmp/myconfig
6.vi /tmp/myconfig
7.mc admin config set myminio < /tmp/myconfig
8.docker start minio 
minio log print a line like SQS ARNs: arn:minio:sqs::1:redis
9.mc mb myminio/images
10.mc events add  myminio/images arn:minio:sqs::1:redis --suffix .jpg
## Context

test on redis container
redis-cli -a yoursecret
127.0.0.1:6379> monitor
OK
I get ping and nothing when i upload a picture with suffix jpg

## Your Environment

* Version used (`minio version`):2018-08-21T00:37:20Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:docker 18.06.0-ce
* Operating System and version (`uname -a`):Linux test1 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by Praveenrajmani** [comment]
hey @longfengfirst ,

I tried the same here with an `mc cp` . It seems to work fine 

![image](https://user-images.githubusercontent.com/5410427/44654138-52c97a80-aa0e-11e8-8265-f125657e14b6.png)


![image](https://user-images.githubusercontent.com/5410427/44652276-23643f00-aa09-11e8-84dc-44478ebcf59a.png)

can you do an `mc events list` on the subscribed bucket ?

**Comment by littletow** [comment]
I am very sorry, I found the reason, because the format is not set, An example of Redis configuration is as follows: 
"redis": {
    "1": {
        "enable": true,
        "address": "127.0.0.1:6379",
        "password": "yoursecret",
        "key": "bucketevents"
    }
}

I am not familiar with this parameter, so I have not set this.

**Comment by littletow** [comment]
I suggest modifying the redis configuration example document to add the format field.:slightly_smiling_face:

**Comment by Praveenrajmani** [comment]
@longfengfirst  Yes we need to update the doc. Thanks for reporting !

**Comment by Praveenrajmani** [comment]
@nitisht Shall we close this ?

**Comment by harshavardhana** [comment]
> I suggest modifying the redis configuration example document to add the format field.

In-fact we should validate and throw error if `format` field is not set. Better yet we are supposed to default to 'namespace' format for redis.
