### ISSUE TITLE
[Distributed] Disks are never formatted if instances mixed with binary and docker hosts

### ISSUE THREAD

**Issue by geek-at** [minio/minio#6357]
I have set up 4 minio servers in 4 different physical locations. 3 Are running the native linux binary and one is running in a docker container.

**All instances are using this exact version:**
- Version: 2018-08-21T00:37:20Z
- Release-Tag: RELEASE.2018-08-21T00-37-20Z
- Commit-ID: 2d84b02bc429ad059a060001bccd712491e6e6a3

I am able to ping and curl all instances from all locations and even from inside the container. The answer from CURL is the expected XML with the message "XMinioServerNotInitialized" from all 4 nodes

I have all 4 sites open via my browser so I know they have the same auth info and that they are running correctly.

But it seems they never format the disks.

Here is a video of the servers in action

[Video of all servers waiting for format ![](https://pictshare.net/preview/m4szy91lqp.mp4)](https://pictshare.net/raw/m4szy91lqp.mp4)

However if I replace the docker container with a binary as well, everything works without a problem.

## Expected Behavior
Format should happen and servers should be initialized

## Current Behavior
forever hanging in "Waiting for the first server to format the disks."

## Possible Solution
Replace docker container with linux binary, then it works.

Also it might be noted in the docs that mixing docker and binary will cause problems even at the same version

## Steps to Reproduce (for bugs)
1. Start 3 machines (different networks, exposed port 9000) with `minio server http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data`
2. Start one docker container `docker run -it --rm  -e MINIO_ACCESS_KEY=mykey -e MINIO_SECRET_KEY=mysecret -p 9000:9000 -v /mnt:/data minio/minio server http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data`
3. Watch them never sync

## Context
I tried to set up a distributed system on 4 physical locations with portforwarding and domains enabled. Didn't work unless I let them all run form the linux binary instead of docker

## Your Environment
* Version used (`minio version`): 2018-08-21T00:37:20Z
* Environment name and version: Debian 8 and 9 and one digitalocean docker instance
* Server type and version: mixed native hardare, vhosts and cloud instances

**Comment by kannappanr** [comment]
@chrisiaut Except the first node, all the other nodes will display `Waiting for the first server to format the disks.` during the initial setup. The first node will display, `Waiting for all other servers to be online to format the disks.`, once you have enough number of disks online.

Can you run them by also setting the server address and port while starting the minio instances?


```
MINIO_ACCESS_KEY=mykey MINIO_SECRET_KEY=mysecret minio server --address server1:9000 http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data
```

```
MINIO_ACCESS_KEY=mykey MINIO_SECRET_KEY=mysecret minio server --address server2:9000 http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data
```

```
MINIO_ACCESS_KEY=mykey MINIO_SECRET_KEY=mysecret minio server --address server3:9000 http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data
```

```
docker run -it --rm -p 9000:9000 -v /mnt:/data minio/minio server --address server4:9000 http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data
```

**Comment by geek-at** [comment]
Great idea but what if I'm using NAT?

I assume the `--address` flag is also the listen flag, so I can only set it to an IP or hostname which is directly used by the device running the command, right? What if the device is behind a firewall which will NAT the port to the device. Would `--address` still work if I put in the firewalls hostname?

**Comment by harshavardhana** [comment]
> minio server -e MINIO_ACCESS_KEY=mykey -e MINIO_SECRET_KEY=mysecret http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data

this command line is wrong. `minio server` doesn't have any `-e` option I am pretty sure somehow your servers have same config and it has worked with binary - whereas docker doesn't. So please use envs like by exporting them in your shell. 

```
export MINIO_ACCESS_KEY=mykey
export MINIO_SECRET_KEY=mysecret
minio server http://server1:9000/data http://server2:9000/data http://server3:9000/data http://server4:9000/data
```

With this, your servers will connect fine.  It is recommended also that don't use different ways to run minio either use docker or either use binary based with systemd service.

**Comment by geek-at** [comment]
@harshavardhana I copied it wrong to my original post, of course the key and secret were set via ENV vars.

So the problem still remains. If it's just not supported then it should be mentioned in the documentation but from a software developer standpoint I don't see a reason why it shouldn't work.

I do realize minio needs a rewrite in regards of following routes of supplied URLs so it works in a NAT environment but for now it should be added to the documentation

[edit] and I think the documentation should also mention that the binary doesn't run on linux if  the kernel doesn't support tcp_fastopen (TFO) meaning every kernel below 3.6 I think

**Comment by harshavardhana** [comment]
> [edit] and I think the documentation should also mention that the binary doesn't run on linux if the kernel doesn't support tcp_fastopen (TFO) meaning every kernel below 3.6 I think

We will address this by falling back on older kernels @chrisiaut there is no reason to mention this. 

> So the problem still remains. If it's just not supported then it should be mentioned in the documentation but from a software developer standpoint I don't see a reason why it shouldn't work.
> 
> I do realize minio needs a rewrite in regards of following routes of supplied URLs so it works in a NAT environment but for now it should be added to the documentation

There is no reason to mention this specifically, bit is a recommended practice to use homogenous environments for production deployments. What we are instead going to write this is distributed setup requires homogenous environments.

**Comment by harshavardhana** [comment]
> We will address this by falling back on older kernels @chrisiaut there is no reason to mention this.

This is fixed already. Pending updating distributed docs.

**Comment by harshavardhana** [comment]
Closing this issue, distributed docs have been updated.
