### ISSUE TITLE
Distributed Minio does not run

### ISSUE THREAD

**Issue by viincenb** [minio/minio#6358]
After reproducing steps defined in https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html, I do not have my minio instances ready (connection refused in browser).

## Expected Behavior
Having 4 minio instances on 900{1-4} ports in my Swarm.

## Current Behavior
The associated containers are "healthy" but I got "connection refused" in my browser when connecting to http://[Node_Public_IP_Address]:[Expose_Port_on_Host]. Containers restart after few minutes.

## Possible Solution
?

## Steps to Reproduce (for bugs)
https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html

## Context
Two nodes in a Swarm with the same environment/configuration.

## Regression
I guess it's not and I did something wrong.

## Your Environment
* Version used (`minio version`): Docker images defined in Compose file (minio/minio:RELEASE.2018-08-21T00-37-20Z)
* Server type and version: OVH VPS
* Operating System and version (`uname -a`): Debian 3.16.56-1+deb8u1
* Link to your project: none, im just trying to play with minio

EDIT:
I removed the worker node from the Swarm and everything went as expected. I will investigate to understand what's wrong with my setup.

**Comment by viincenb** [comment]
I tried an other server as a node worker and it works, minio does not want my server :disappointed: I think this issue may be closed unless someone wants to understand what happened.

**Comment by deekoder** [comment]
@devSwoop it could be any number of things outside of minio. We would need to engage back and forth to know why this may have happened. Please come to our slack channel at slack.minio.io and I will close this issue.
