### ISSUE TITLE
Which ports are used for network communication

### ISSUE THREAD

**Issue by evtimokn** [minio/minio#6359]
I need to know which ports are used by minio to communicate to any components of Pivotal PAS. In my configuration PAS is running on a different NSX-Virtual-Wire than Minio. In order to enable the communication between both virtual wires I need to enable NSX-Firewall rules for all the ports that are used by minio to send or receive data to/from PAS. 

## Your Environment
PAS 2.0.20

**Comment by harshavardhana** [comment]
Only one port is used per instance of Minio - default port is 9000

**Comment by deekoder** [comment]
Closing this issue. Let us know if you have any issue.
