### ISSUE TITLE
"Unhealthy" status reported by Docker because curl was removed

### ISSUE THREAD

**Issue by fergbrain** [minio/minio#6365]
#6347 removes curl, however curl is still required by minio/dockerscripts/healthcheck.sh

## Expected Behavior
Docker should report correct heath status of Minio (i.e. running  `/usr/bin/healthcheck.sh` should only raise an error when the healthcheck has failed)

## Current Behavior
Docker reports that Minio is unhealthy.

## Possible Solution
1. Add curl back (using v7.61.0-r0 or greater) (removed by #6347 due to #6343)
2. Use an alternative to curl
3. Remove the heathcheck feature from Docker build

## Steps to Reproduce (for bugs)

1.  Deploy Minio using Docker per instructions at https://docs.minio.io/docs/minio-docker-quickstart-guide.html
2. Wait at least 150 seconds

## Context
Trying to deploy Minio with Docker...just a basic setup. Nothing fancy.

## Regression
Yes: a73b65de08d61e817f6507d3d16b9ba70394c43a 

## Your Environment

* Version used (`minio version`): 2018-08-25T01:56:38Z
* Environment name and version (e.g. nginx 1.9.1): Docker 18.06.1-ce
* Server type and version: N/A
* Operating System and version (`uname -a`): N/A
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Oh yes thanks for reporting this issue.

**Comment by dockerss** [comment]
@harshavardhana  By when can we expect this in the latest build?

**Comment by harshavardhana** [comment]
> @harshavardhana By when can we expect this in the latest build?

The coming week, for now, please disable the health check in the compose as a workaround.

**Comment by douglasmiranda** [comment]
Would you guys be interested in a pull request replacing `curl` with the `wget`?

`wget` is already in Alpine, so no need for adding `curl`.

**Comment by fergbrain** [comment]
> Would you guys be interested in a pull request replacing curl with the wget?

Based on https://github.com/minio/minio/pull/6347#issuecomment-416105622 I believe their plan is to rewrite the script in Go.

**Comment by douglasmiranda** [comment]
That makes sense!! xD Thanks for answering.
