### ISSUE TITLE
Distributed Minio not starting with TLS

### ISSUE THREAD

**Issue by deepak71** [minio/minio#6368]
We're trying to start a distributed cluster of 3-nodes with TLS certificates but minio service is failing to start. With the same configuration, If we start minio service with http its starting without any issue. But if we start Minio service with https by having TLS certificates in place it doesn't start and failing with below errors:
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 58m44s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 58m50s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 59m19s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 59m36s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 59m58s)

## Expected Behavior
We want to start secure distributed minio cluster with TLS certificates

## Current Behavior
But if we start Minio service with https by having TLS certificates in place it doesn't start and failing with below errors:
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 58m44s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 58m50s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 59m19s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 59m36s)
minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 59m58s)

**Comment by vadmeste** [comment]
@deepak71, are you using self signed certificates ? if yes you need to put all certificates of all servers in ~/.minio/certs/CAs/ of all servers.

This needs to be fixed ASAP https://github.com/minio/minio/issues/5877 to print useful information about why nodes are not able to connect (in some cases)

**Comment by deepak71** [comment]
@vadmeste As per minio documentation we should put self signed certificates in ~/.minio/certs.  Also, I tried by putting these certs in ~/.minio/certs/CAs, but its failing with below error message:

`minio[46517]: ERROR Unable to start the server: HTTPS specified in endpoints, but no TLS certificate is found on the local machine.`

**Comment by harshavardhana** [comment]
@deepak71 what @vadmeste meant is you need to copy `public.crt` generated for different servers into `/.minio/certs/CAs` folder. Rest of the `public.crt` and `private.key` should be placed in `/.minio/certs`

**Comment by deepak71** [comment]
@harshavardhana @vadmeste `public.crt `and `private.key` are lying in /.minio/certs directory only, but minio service not starting. Also no exceptions are being reported other then `minio[10724]: Waiting for a minimum of 3 disks to come online (elapsed 58m50s)`.

With the configuration and by using http in place of https and removing these certs from `/.minio/certs/` directory it successfully starting. But as we use https and put these certs it starts failing. Could you please help us in isolating the issue.

**Comment by nitisht** [comment]
@deepak71 here is what you need to do 

- Keep `public.crt` and `private.key` in /.minio/certs
- Additionally copy `public.crt` from each minio instance and put it in `/.minio/certs/CAs` of all other minio instances - while renaming the certs as `public1.crt`, `public2.crt` and so on. 

Currently Minio servers don't trust other peer's cert as it is self signed, by adding all `public.crt` to `/.minio/certs/CAs` you are asking each peer to trust the other peer(s).

**Comment by deepak71** [comment]
@nitisht this way also it didn't help still getting the same exception while starting the minio service.

With this configuration (by placing certificates in designated directories), we're able to start a standalone minio instance, similar config don't work in distributed setup.

**Comment by nitisht** [comment]
Can you paste the commands you used to start Minio server and also the output of `openssl x509 -in ~/.minio/certs/public.crt -text -noout`

**Comment by deepak71** [comment]
@nitisht We're using our own certificates issued by internal Certificate Issuing Authority. Also, I checked certficates authenticity its a valid one. And we're using following config for starting Minio service.

cat minio.conf
```
MINIO_ACCESS_KEY=accesskey
MINIO_SECRET_KEY=secretkey
MINIO_VOLUMES=https://server1/data/minio1/data https://server2/data/minio1/data https://server3/data/minio1/data \
              https://server1/data/minio2/data https://server2/data/minio2/data https://server3/data/minio2/data
MINIO_PORT=:443
```

**Comment by nitisht** [comment]
> We're using our own certificates issued by internal Certificate Issuing Authority. Also, I checked certficates authenticity its a valid one

Okay, I just wanted to confirm certificates are issued for the domain `server1` / `server2`

**Comment by deepak71** [comment]
Yes, certificates are not subjected together with domain or server name like having `*server*`.

**Comment by nitisht** [comment]
@deepak71 can you pls join us on slack https://slack.minio.io . It will help communicate better. [edit: updated link]

**Comment by deepak71** [comment]
@nitisht  Nitish could you invite me to your workspace. Unable to join that.

**Comment by nitisht** [comment]
I'll need your email id for that, but did you try  https://slack.minio.io what is the error you see

**Comment by deepak71** [comment]
its `deepak.sansaniwal@gmail.com`

**Comment by nitisht** [comment]
@deepak71 as discussed on Slack, closing this as a duplicate of #6202
