### ISSUE TITLE
Web interface on Minio Gateway hanging/freezing when rendering/displaying bucket content with custom policies on upstream S3 service

### ISSUE THREAD

**Issue by kalleyne** [minio/minio#6371]
RELEASE.2018-08-21T00-37-20Z
Usually, the web interface on Minio Gateway is responsive and smooth.

However, certain custom S3 policies can negatively affect the ability to view and select buckets within the web browser especially when such policies deny access to certain buckets to the user. This does not seem to be a problem with mc as this appears to work correctly with respect to policies.

**Comment by harshavardhana** [comment]
Thanks @kalleyne

**Comment by kanagarajkm** [comment]
I could reproduce this issue by setting the policy to Deny ListBucket for the first bucket on the list.
