### ISSUE TITLE
Possible issue in default Omnibus install of Gitlab / Minio

### ISSUE THREAD

**Issue by arturgvieira-zz** [minio/minio#6376]
A heads up, to the teams, that the current default install only allocates 10GB of space for Minio.
## Expected Behavior

A docs mention of this specific setting, so that users can choose the size of the bucket ahead of time, or allow for an object lifecycle hook to allow for a rolling setup. Old objects would be deleted and newer ones take their place that would make 10GB not that bad of a choice for that disk size.
## Current Behavior

I set up this sweet setup, CI / CD pipeline in Kubernetes on Google Cloud. Questionably the best setup for a Gitlab system. All of the defaults were maintained. Two weeks later I am running into this error.
<img width="1201" alt="screen shot 2018-08-28 at 7 56 32 pm" src="https://user-images.githubusercontent.com/7041980/44762784-188ad680-aafd-11e8-8598-356a614fa93a.png">
- In the Cloud Pod Logs:
>"s3aws: XMinioStorageFull: Storage backend has reached its minimum free disk threshold. Please >delete a few objects to proceed.\\n\\tstatus code: 507, request id: 154F3B449FE2DB90\"
## Possible Solution

- Not sure, I have updated minio to chart `minio-1.2.0` and the image to RELEASE.2018-08-25T01-56-38Z
- I have also removed all images from my registry.
## Steps to Reproduce (for bugs)

1. Create a Kubernetes Cluster
2. Install Gitlab as per 
https://gitlab.com/charts/gitlab/tree/master
3. Attach the Kubernetes Cluster use Runner DIND service on Kubernetes runner
4. Fill the disk with docker images

## Context

I am unable to push to the registry which deploys my app.
## Regression

Maybe, minio-0.4.3
## Your Environment

* Version used (`minio version`): minio-0.4.3
* Environment name and version (e.g. nginx 1.9.1): Google Cloud
* Server type and version: Kubernetes Engine
* Operating System and version (`uname -a`): Cloud
* Link to your project: Can't share

**Comment by nitisht** [comment]
@arturgvieira we are not the maintainers of the [Gitlab Helm Chart](https://gitlab.com/charts/gitlab/tree/master), accordingly looks like this issue doesn't belong here - instead on the Gitlab Chart repo.  

Do feel free to let us know if there are issues on the Minio server

**Comment by arturgvieira-zz** [comment]
Ok, I'll close it.

**Comment by nitisht** [comment]
Thanks @arturgvieira

**Comment by arturgvieira-zz** [comment]
Thank you. I will leave here as well that I was able to log into the Minio server and trim the registry size.
