### ISSUE TITLE
Allow disabling TCP_FASTOPEN

### ISSUE THREAD

**Issue by dfredell** [minio/minio#6379]
## Expected Behavior
Have minio boot on Joyent's [SmartOS](https://en.wikipedia.org/wiki/SmartOS) (a fork of Solaris and illumos). 

## Current Behavior
When starting docker it won't boot.
```
$ docker --tls run -p 9000 minio/minio:RELEASE.2018-08-18T03-49-57Z server /data
Unable to find image 'minio/minio:RELEASE.2018-08-18T03-49-57Z' locally
RELEASE.2018-08-18T03-49-57Z: Pulling from minio/minio (req fa529453-0588-4cd6-9e97-97df130cf832)
911c6d0c7995: Already exists 
bf8c744d1ab8: Pull complete 
7babccf7bc07: Pull complete 
Digest: sha256:913463a2c86d50f4475b74c30231c28fd06d0cc5f93dcbf8df1f692af9b3d10d
Status: Downloaded newer image for minio/minio:RELEASE.2018-08-18T03-49-57Z
ERRO[0042] error getting events from daemon: Error response from daemon: (NotImplemented) events is not implemented (4a8a82d1-e432-4fed-83a1-1538092f92a0) 

 You are running an older version of Minio released 6 days ago 
 Update: https://dl.minio.io/server/minio/release/linux-amd64/minio 


Created minio configuration file successfully at /root/.minio
Endpoint:  http://10.2.3.240:9000  http://192.168.129.111:9000  http://127.0.0.1:9000
AccessKey: G1N3BKDPSE930CCE5AJZ 
SecretKey: wEsaADbQxthfNFAi/mKYjw6O3bVm1+qIl33hn5i9 

Browser Access:
   http://10.2.3.240:9000  http://192.168.129.111:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.2.3.240:9000 G1N3BKDPSE930CCE5AJZ wEsaADbQxthfNFAi/mKYjw6O3bVm1+qIl33hn5i9

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

API: SYSTEM()
Time: 18:36:17 UTC 08/29/2018
Error: cannot enable TCP_FASTOPEN(qlen=16384): protocol not available
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/signals.go:65:cmd.handleSignals()
       3: cmd/server-main.go:372:cmd.serverMain()
```
When running the same command with `RELEASE.2018-08-02T23-11-36Z` minio boots just fine. 

## Possible Solution

- Add a flag so the user can disable TCP_FASTOPEN / 'enhanced tcp features' from #6289
- Have Minio smart enough to recover from this error and fall back to old behavior.

## Steps to Reproduce (for bugs)
1. Get yourself a [joyent account](https://www.joyent.com/) or start up a [SmartOS](https://wiki.smartos.org/display/DOC/Download+SmartOS)
2. Run the above `docker run` to spin up a minio instance

## Context
I'm running dockers in a [private triton](https://www.joyent.com/pricing/software) environment. That is running a stable released version of the host operating system released in May of 2018.

## Regression
Is this issue a regression? Yes
https://github.com/minio/minio/pull/6289  
Same issue as #6345 but I'm on a more up to date OS. 

## Your Environment

```
[docker] / # uname -a
Linux abceffc25c4b 3.13.0 BrandZ virtual linux x86_64 Linux
[server] / # uname -a
SunOS server 5.11 joyent_20180525T172343Z i86pc i386 i86pc
```

**Comment by harshavardhana** [comment]
> [docker] / # uname -a Linux abceffc25c4b 3.13.0 BrandZ virtual linux x86_64 Linux [server] / # uname -a SunOS server 5.11 joyent_20180525T172343Z i86pc i386 i86pc

TCP_FASTOPEN Is already available since 3.6 kernels - did you joyent remove some features from the kernel here? @dfredell

**Comment by dfredell** [comment]
Possibly, I have raised a ticket with them as well. We will see what they say too. I didn't remove any features from the kernel intentionally.

**Comment by dfredell** [comment]
@harshavardhana Wow, you are wizard level fast. I'm impressed, and thank you. 
And on the version, the OS host is running kernel `5.11`, but the kernel the docker uses/ sees is `3.13.0`. I don't claim to know/ understand the magic that Joyent has made. I can just run `uname -a`.

**Comment by harshavardhana** [comment]
Already sent the PR removing triage.

**Comment by dfredell** [comment]
FYI The reply I got from the Joyent support guy: `You are seeing this error message because our implementation of docker in Triton doesn't support TCP_FASTOPEN yet. I have opened an internal ticket with the engineering team to add support for this feature...`

**Comment by dfredell** [comment]
I can confirm that the TCP_FASTOPEN issue is fixed for me in RELEASE.2018-09-01T00-38-25Z.

**Comment by harshavardhana** [comment]
> I can confirm that the TCP_FASTOPEN issue is fixed for me in RELEASE.2018-09-01T00-38-25Z.

Thanks for your confirmation
