### ISSUE TITLE
Implement AssumeRole API

### ISSUE THREAD

**Issue by challarao** [minio/minio#6381]
## Expected Behavior
Ability to request temporary credentials for a role with constrained policy.
Ability to use this API: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

Client side relevant class: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenService.html#assumeRole-com.amazonaws.services.securitytoken.model.AssumeRoleRequest-

General flow:
1. Use minio/bucket role credentials/credentials with access to assume role
2. Use STS client with any of the above credentials
3. Create an assume role request with a policy json constraining the path under the bucket.
4. Send a request stsClient#assumeRole(AssumeRoleRequest)
5. Get temporary credentials from the AssumeRoleResult
6. Serve to your consuming client.

The temporary credentials returned will only to perform a particular action(PutObject) and to a particular resource like a key under the bucket or a prefix like bucket/some-id/data*. This is specified in policy json.

## Current Behavior
This is unimplemented.

## Context
This is required for the following use cases: 
1. To be able to reliably use S3 multipart APIs feature of the SDKs without re-inventing the wheel of pre-signing the each URL in multipart API. This is very tedious to implement with all the scenarios of fault tolerance that's already implemented by the client SDK. The general client SDKs don't support multipart with presigned URLs.
2. To be able to easily get the temporary credentials to upload to a prefix. Make it possible for a client to upload a whole folder using the session. The server side applications need not create a presigned URL and serve to the client for each file. Since, the client would have the session it can do it by it self.

PS: In some scenarios, the IAM users(with access key, secret) will only have permissions to assume a specific role but not granted any permissions directly on S3.
but

**Comment by bennnjamin** [comment]
+1 I use S3 API this way to provide multi-tenant cloud storage in one bucket and keep every user's data separate. S3 has a 100 bucket limit by default, so securely storing files for thousands of users requires prefix level access control.

**Comment by bennnjamin** [comment]
Whats the status on this? It looks like #6168 only added AssumeRoleWithClientGrants (https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) if I'm not mistaken. It would be very nice to use Minio's root credentials and the AWS AssumeRole API to generate temporary credentials.

**Comment by harshavardhana** [comment]
> Whats the status on this? It looks like #6168 only added AssumeRoleWithClientGrants (https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) if I'm not mistaken. It would be very nice to use Minio's root credentials and the AWS AssumeRole API to generate temporary credentials.

This is a work in progress will be available in future.

**Comment by bennnjamin** [comment]
Thanks for your prompt response. If there's anything I can help with please
let me know.

Benjamin Fitzgerald
LETS Corporation
(925) 566-5600 ext. 25
ben@letscorp.us




*******Confidential Notice:
This message is intended only for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential and exempt from disclosure under applicable law. If the reader
of this message is not the intended recipient, you are hereby notified that
any dissemination, distribution or copying of this communication is
strictly prohibited. If you have received this message in error, please
delete this message from all computers and contact Orion Systems/LETS Corp
immediately by return e-mail and/or telephone at (925) 566-5600

**Comment by Clan-Utility** [comment]
> > Whats the status on this? It looks like #6168 only added AssumeRoleWithClientGrants (https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) if I'm not mistaken. It would be very nice to use Minio's root credentials and the AWS AssumeRole API to generate temporary credentials.
> 
> This is a work in progress will be available in future.

When would AssumeRole() be available roughly? Is it simpler to implement than AssumeRoleWithClientGrants()?
In my case I will have my own API to let user request for temporary credentials for uploading to Minio. Because I want to control the bucket and object name that the user can upload by setting the policy. This API will call AssumeRole() with Minio's root credentials to generate and return the temporary credential to the user.

**Comment by harshavardhana** [comment]
Can't give a hard deadline it will be available soon, will detail out how it will be available soon.

**Comment by bennnjamin** [comment]
Is this still planned to happen soon?

**Comment by harshavardhana** [comment]
No not yet @bennjamin we were finishing WebIdentity first
