### ISSUE TITLE
Update Redis client library

### ISSUE THREAD

**Issue by nitisht** [minio/minio#6392]
**Not using template on purpose as this is not a bug (yet)**

Current Redis client library we use for bucket notifications is https://github.com/garyburd/redigo/ . It has now been archived. 

We should probably move to other Redis client library, preferably more popular libraries like this: https://github.com/go-redis/redis

**Comment by harshavardhana** [comment]
yes we should @nitisht :+1:

**Comment by harshavardhana** [comment]
are we going to update the library ?
