### ISSUE TITLE
Add sse-s3 support for S3 Select Object api

### ISSUE THREAD

**Issue by poornas** [minio/minio#6400]
## Expected Behavior

SSE-S3 support is added in minio server. S3 Select Object Content handler needs to be enhanced to
handle sse-s3 encrypted objects
## Current Behavior

not implemented
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Regression
 No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
This is already fixed in master, closing as fixed.
