### ISSUE TITLE
Issue running Shared backend in Windows

### ISSUE THREAD

**Issue by cwrx777** [minio/minio#6401]
Related to #5649 
I am trying to setup multiple instances of minio in Windows using a shared backend.
Here is the setup:
1. VM1. A Windows Server 2016 VM with a shared folder (SMB), and 'Everyone' has read/write access.
2. VM2. A Windows Server 2016 VM. 
Run minio with gateway nas mode using the shared folder in VM1. 
3. VM3. A Windows Server 2016 VM. 
Run minio with gateway nas mode using the shared folder in VM1. 

## Expected Behavior
All instances of minio using shared backend should be functional.

## Current Behavior
First instance runs fine, subsequent instances fail to start.

## Steps to Reproduce (for bugs)
1. Assume the shared folder has not been initialized before by minio. 
2. Run Minio in VM2. Minio is able to get initialized and the iniatialization message is shown. (e.g EndPoint:, AccessKey: etc). Minio is also accsessible from browser. 
3. Run Minio in VM3. Minio initialization message is not shown.
4. Stop Minio in VM2. Only after this, the initialization message in VM3 is shown.

## Context
Running multiple instances of minio behind a load balancer. The application will connect to load balancer instead of directly connecting to the minio instance. 

## Your Environment

* Version used (`minio version`):2018-09-01 and earlier versions
* Environment name and version (e.g. nginx 1.9.1): NA
* Server type and version: NA
* Operating System and version (`uname -a`):Windows Server 2016, Windows 10 (assume all instances are running using the same OS and version when tested).
* Link to your project: NA

**Comment by nitisht** [comment]
Thanks for creating the issue @cwrx777 we’ll take a look soon

**Comment by harshavardhana** [comment]
Thanks for the issue @cwrx777 a PR is sent fixing this issue.
