### ISSUE TITLE
Select fails with unexpected error on files with special delimiter requirement

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#6403]
***not using template*** 

No failure as observed with S3 
```
python3 /tmp/select.py 
Stats details bytesScanned: 
0
Stats details bytesProcessed: 
0
```

Failure as observed with Minio
```
python3 /tmp/select.py 
Traceback (most recent call last):
  File "/tmp/select.py", line 22, in <module>
    OutputSerialization={'CSV': {}},
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the SelectObjectContent operation (reached max retries: 4): We encountered an internal error, please try again.
```

**Comment by harshavardhana** [comment]
```py
#!/usr/bin/env/env python3
import boto3

s3 = boto3.client('s3',
                  endpoint_url='http://localhost:9000',
                  aws_access_key_id='minio',
                  aws_secret_access_key='minio123',
                  region_name='us-east-1')

r = s3.select_object_content(
    Bucket='mycsvbucket',
    Key='Sacramentorealestatetransactions.csv.gz',
    ExpressionType='SQL',
    Expression="select * from s3object",
    InputSerialization={
        'CSV': {
            "FileHeaderInfo": "USE",
        },
        'CompressionType': 'GZIP',
    },
    OutputSerialization={'CSV': {}},
)

for event in r['Payload']:
    if 'Records' in event:
        records = event['Records']['Payload'].decode('utf-8')
        print(records)
    elif 'Stats' in event:
        statsDetails = event['Stats']['Details']
        print("Stats details bytesScanned: ")
        print(statsDetails['BytesScanned'])
        print("Stats details bytesProcessed: ")
        print(statsDetails['BytesProcessed'])
```

[Sacramentorealestatetransactions.csv.gz](https://github.com/minio/minio/files/2342215/Sacramentorealestatetransactions.csv.gz)

**Comment by harshavardhana** [comment]
The main problem here is that to support custom Record delimiter we need to use our own Reader implementations, currently, other than `\n` is not supported by Minio select API. 

One such reader implementation is https://github.com/ctessum/macreader/blob/master/reader.go

**Comment by Praveenrajmani** [comment]
@harshavardhana, By custom record delimiter ,  do we mean that records can be delimited by any character other than default '\n' , '\r' in our case
If so, For this, AFAIK we can use the `FieldsPerRecord` of `*csv.Reader` which limits the fields read ( Will try this and see if it really works ) (OR) by knowing the record delimiter from the user, In both the cases we would require an addition the in the input options. Will this do good?
OR
let us have `\r` as of now and have a reader designed which will replace '\r' to '\n' and wraps the csv reader inside it .

**Comment by Praveenrajmani** [comment]
Anyhow the csv.Reader converts all the `\r\n` sequences to plain `\n`, but not `\r` to `\n`
https://golang.org/pkg/encoding/csv/#Reader

**Comment by harshavardhana** [comment]
Yes but FieldsPerRecord will not work for us. But we need to specifically support Mac CSV files too which only have `\r`
