### ISSUE TITLE
Private Manta Setup possible?

### ISSUE THREAD

**Issue by neuroserve** [minio/minio#6408]
Would it be possible to make the Manta-Backend configurable in order to be able to choose a local/private Manta setup as a target? As I understand currently the Manta setup of the Joyent Public Cloud is the default.

**Comment by nitisht** [comment]
I think we can do that @neuroserve . 

What are additional requirements for supporting a private Manta setup? I understand an `endpoint` argument is one.

**Comment by neuroserve** [comment]
Currently there's basically these parameters

 -e "MINIO_ACCESS_KEY=joyentaccountname" \
 -e "MINIO_SECRET_KEY=joyentkeyid" \
 -e "MANTA_KEY_MATERIAL=~/.ssh/id_rsa" \
 -e "MANTA_SUBUSER=devuser"

We would need an additional parameter like
      MANTA_URL=https://my.private.manta.dc/

MANTA_URL is also used in the configuration of the Manta-API: https://apidocs.joyent.com/manta/#setting-up-your-environment

**Comment by nitisht** [comment]
Thanks @neuroserve , let me confirm internally as well. If everything is okay, we'll have a PR for this soon

**Comment by nitisht** [comment]
can you try `minio gateway manta <custom-manta-endpoint>`

**Comment by neuroserve** [comment]
I can start minio with that parameter, but I see no buckets and I cannot upload files or create buckets. Error message in the browser is: 
unable to put directory: unable to execute HTTP request: Put /myusername/stor/testm: unsupported protocol scheme ""

**Comment by nitisht** [comment]
can you paste the exact command used

**Comment by neuroserve** [comment]
./minio gateway manta https://manta.mydc.dc
I've used MINIO_SECRET_KEY, MINIO_ACCESS_KEY and MANTA_KEY_MATERIAL as env variables

**Comment by nitisht** [comment]
I see, could you pls also try `./minio gateway manta --address https://manta.mydc.dc`

**Comment by nitisht** [comment]
cc @stack72

**Comment by neuroserve** [comment]
./minio gateway manta --address https://manta.mydc.dc exits immediately. The output says that Endpoint would be http://https://manta.mydc.dc (what obviously does not exist)

**Comment by nitisht** [comment]
@neuroserve could you pls join us on Slack http://slack.minio.io - it will help shorten the discussion loop. I have a few questions.
