### ISSUE TITLE
Internal Error with zero body but defined content-length

### ISSUE THREAD

**Issue by vitpavlenko** [minio/minio#6409]
Send internal error after 300000s timeout while sending request (putObject) with defined Content-Length but zero body.

**Comment by harshavardhana** [comment]
We need more information here, most of the informative structure to opening an issue has been removed with no details regarding the issue. 

We will close this issue as invalid for now, feel free to open Github issue with some more details such as 

- Minio version
- A sample program if you have or any tool that you used to reproduce an issue
- Any other specific libraries that were being used here
