### ISSUE TITLE
Read Only backend fails as Minio can't write to backend

### ISSUE THREAD

**Issue by bitva77** [minio/minio#6413]
## Expected Behavior

Minio should be able to run and provide read access to any backend regardless of whether it can write or not.

## Current Behavior

Minio doesn't start and says:  "Please ensure Minio binary has write permissions for the backend"

## Possible Solution

Add a -ro option to allow read-only backends.

## Steps to Reproduce (for bugs)

1.  Have a backend that's read-only by the server/user/minio
2.  Start minio:  minio gateway nas -C d:\minio\ \\\\netapp\\readonlyshare

## Context

We have processes that write out to shared NAS drives via CIFS/SMB.  I'd like to provide our newer apps that ingest data from these processes with a Minio front-end to download the data.

## Regression

No

## Your Environment

* Version used (`minio version`):  Version: 2018-09-01T00:38:25Z
* Operating System and version (`uname -a`):  Windows 2016

**Comment by harshavardhana** [comment]
Read-only backend is not allowed @bitva77 since we need to write `format.json` to write a specific backend format to handle certain types of I/O

**Comment by bitva77** [comment]
Thanks for the reply.

That can't be moved elsewhere in these cases?  Or even ignored when dealing with a read-only backend?  Since minio won't be writing any way I'd figure it'd be okay...

At some point we'll move the process generating the data to be S3 compatible but until that time I'm trying to get a head of the curve and this kind of feature would go a long ways.

But I understand if that's not in scope for you all here  :)

Thanks!

**Comment by bitva77** [comment]
By the way, in case anyone comes across a similar need/issue:  I've been able to workaround this by symlinking to the backends underneath a writeable directory on the local host.  The backends are read-only still.

I'm doing this in Windows.  I assume Linux would work similarly.

**Comment by markgittins** [comment]
I'd really like to see this implemented in minio. One of my Use Cases requires a RO backend to be made available via S3, the work-around is one thing but it's clunky and I'd much prefer native support from minio, it seems to me that it's a valid Use Case....

**Comment by marks-hbk** [comment]
I agree that this is a desirable enhancement, one which could probably be enabled with an additional startup arg such as "--alt-sys-dir <path>" which allows the .minio.sys dir to be created in a different location, which should then allow the minio server to startup on a readonly-backend. I accept that this option would be less useful in federated configurations and is perhaps for single-node use only.

**Comment by harshavardhana** [comment]
Locking further conversation here. Please open new issues if there are problems in current implementation 

To summarize the resolution - we don't have any bandwidth to support these use cases and also not desirable. Feel free to hack around the software to achieve this yourself.
