### ISSUE TITLE
xl: Removing an empty directory doesn't work

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#6420]
## Expected Behavior
Removing an empty directory should work in distributed mode

## Current Behavior
Removing an empty does not work

## Possible Solution
Fix xl.DeleteObject()

## Steps to Reproduce (for bugs)
1. aws s3api create-bucket --bucket mybucket --endpoint http://localhost:9011
2. aws s3api put-object --bucket mybucket --key key/ --endpoint http://localhost:9011
3 aws s3api delete-object --bucket mybucket --key key/ --endpoint http://localhost:9011
4. aws s3api list-objects --bucket mybucket --endpoint http://localhost:9011

## Context
Fix issue

## Regression
Yes

https://github.com/minio/minio/commit/85117d554febedebaab3392493ef55ea95709411

## Your Environment
master

**Comment by harshavardhana** [comment]
Fixed by #6421
