### ISSUE TITLE
Bucket objects not updating via Web UI

### ISSUE THREAD

**Issue by riazarbi** [minio/minio#6424]
I am using minio via docker, and single server with 10 drives for erasure coding.

## Expected Behavior
For a particular bucket, when accessing minio web UI I expect to see the newest object in the bucket when sorting by Last Modified.

## Current Behavior
When accessing a particular bucket via web UI, the top file listed is -

```
1536054844_P24-106568053.html ... 192.15 KB ... Sep 4, 2018 12:00 PM
```
This is not the newest object in the bucket; the newest object in the bucket is (using python) -  

```
print(max(ob.last_modified for ob in minioClient.list_objects("bucket")).strftime("%Y-%m-%d %H:%M:%S"))

2018-09-05 22:00:06

```
When I look for the corresponding object by name in the webUI, it does not appear anywhere.

It appears that the webUI stopped updating the objects listed at some point in the past (well, at 12:00 PM on Sept 4th).

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)

1. Initialize inio via docker with 10 drives
2. Set up a cron job to sink a timestamped file to a minio bucket every 5 seconds
3. Check in periodically to check whether the webUI listed objects corresponds to the python listed objects

## Context
I'm sinking files to a bucket every 30 minutes. My functionality isn't impacted since I use pthe python client exclusively. But it is unnerving.

## Regression
Not sure

## Your Environment
I am using minio via docker, and single server with 10 drives for erasure coding.

The bucket has 4826 files in it. Not sure how many are listed via webUI; probably in the region of 2000.

**Comment by nitisht** [comment]
Thanks for the issue @riazarbi we'll take a look soon

**Comment by kanagarajkm** [comment]
@riazarbi minio webui doesn't automatically pull newly added objects. When you click a bucket on the left hand side, first set of 1000 objects are pulled from the server and shown. When you click on a column header to sort, the sorting is done locally. Next set of 1000 objects will be loaded when you scroll down to the end of the list and so on. We are intentionally not loading all the objects, it would crash/hang the browser when there are large no.of objects.

**Comment by LordMike** [comment]
Note that S3 UI does the same -- sorting locally.
