### ISSUE TITLE
Gateway fails to start on any port when 9000 (globalMinioPort) is already in use

### ISSUE THREAD

**Issue by ansemjo** [minio/minio#6426]
## Expected Behavior
- start a minio server on port 9000
  - `minio server /tmp`
- afterwards start a minio gateway on a different port, e.g. 9001
  - `minio gateway b2 --address :9001`
- both minio instances should start and not have an "address in use" conflict

## Current Behavior
- the gateway does not start, because it complains of port 9000 being used, even if started with `--address :9001` or any different port
- starting the gateway first on the alternative port and then starting the server on 9000 works

## Possible Solution
Looking at the code, [gateway-main.go#L143](https://github.com/minio/minio/blob/fd1b8491dbe541d780197064e945c451ad733b73/cmd/gateway-main.go#L143) looks wrong to me because it always checks the default `globalMinioPort` instead of the address specified as an argument?

## Steps to Reproduce (for bugs)
See above. Assume that `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` are defined in the environment.

## Context
I'm trying to write a generic systemd service `minio@.service` which uses `.conf` files as EnvironmentFiles, so I can start multiple minio services on different ports quickly.

## Regression
I don't know?

## Your Environment
Tried on Debian 9 with the latest release `2018-09-01T00:38:25Z` and various compilations from source.

**Comment by nitisht** [comment]
Thanks for the details @ansemjo we'll take a look soon
