### ISSUE TITLE
Direct link to public directory doesn't work unless logged in

### ISSUE THREAD

**Issue by pwagland** [minio/minio#6436]
When you have a "directory" that is publicly available, then the link to that directory, that is shown when browsing the site, does not work to get you back to the same location. If you are logged in, the same link will take you to that directory.

For example.

Server: minio.local.lan
Bucket: Public
Policy: Read Only
Files: a/file1.txt a/file2.txt

When you browse to https://minio.local.lan/minio/Public/a then if you are not logged in, you get to see the list of buckets, from where you can choose to go to 'Public' / 'a'. If you are logged, then you get to see immediately the list of files.

## Expected Behavior
You get to see the list of files whether you are logged in or not. That is, both an anonymous user and a logged in user gets to see the same result

## Current Behavior
Anonymous users get dropped to the overview of public buckets. Logged in users get taken directly to the correct location.

## Steps to Reproduce (for bugs)
See summary above.

## Context
This makes sharing of links to public collections of files more complicated than it should be.

## Your Environment
VERSION
2018-07-23T18:34:49Z
MEMORY
Used: 8.1 MB | Allocated: 6.3 GB | Used-Heap: 8.1 MB | Allocated-Heap: 48 MB
PLATFORM
OS: linux | Arch: amd64
RUNTIME
Version: go1.10.2 | CPUs: 4

**Comment by deekoder** [comment]
I think we may have fixed this already in master. @kanagarajkm can you please confirm?

**Comment by kanagarajkm** [comment]
@deekoder i will check this out
