### ISSUE TITLE
domain setting from config/backend ignored

### ISSUE THREAD

**Issue by stefan-as** [minio/minio#6437]
When setting the `domain` parameter in minio config to enable virtual-host-style requests, the setting is ignored since minio.RELEASE.2018-08-21T00-37-20Z or minio.RELEASE.2018-08-18T03-49-57Z (unsure). Setting the `MINIO_DOMAIN` env variable works as expected.

## Expected Behavior

Minio should respect the `domain` setting.

## Current Behavior

The `domain` setting does not enable virtual-host-style requests. The `MINIO_DOMAIN` env variable works as expected.

## Steps to Reproduce (for bugs)

1. `./mc admin config set` some config including `domain` setting
2. `./mc ls` shows path-style requests
3. Set `MINIO_DOMAIN` env var
4. `.mc ls` shows virtual-host-style requests

## Context

virtual-host-style requests not working since mid of August

## Regression

Yes, worked before minio.RELEASE.2018-08-21T00-37-20Z or minio.RELEASE.2018-08-18T03-49-57Z.

## Your Environment

* Version used (`minio version`): RELEASE.2018-09-01T00-38-25Z
* Environment name and version (e.g. nginx 1.9.1): direct access/systemd
* Server type and version: direct access
* Operating System and version (`uname -a`): 4.4.0-134-generic #160-Ubuntu SMP (Ubuntu 16.04.5 LTS)

**Comment by harshavardhana** [comment]
This seems like the problem introduced when config migrated to the backend specifically here

```go
         apiRouter := router.PathPrefix("/").Subrouter()                                                                                                                     
         var routers []*mux.Router                                                                                                                                           
         if globalDomainName != "" {                                                                                                                                         
                 routers = append(routers, apiRouter.Host("{bucket:.+}."+globalDomainName).Subrouter())                                                                      
         }                                                                                                                                                                   
         routers = append(routers, apiRouter.PathPrefix("/{bucket}").Subrouter())
```

Config can't be loaded prior to handlers being registered, but for virtual DNS style since the config.json value should be honored we will not have registered the handlers before we started HTTP server started.

Adding new handlers dynamically on an active HTTP server is generally a bad idea.

**Comment by kannappanr** [comment]
@ebozduman This variable will now be honored only if it is part of the environment variable.

**Comment by deekoder** [comment]
@stefan-as we would need it to be set as an ENV variable moving forward. It's a breaking change. We didn't do a good job of calling it out before the release. So I am modifying the release notes to state this. Sorry for this inconvenience.
