### ISSUE TITLE
PDF upload via JS SDK: "S3 Error: The request signature we calculated does not match"

### ISSUE THREAD

**Issue by incolas** [minio/minio#6438]
Here's the related code. Connection params are stored in a config file

```
let minioClient = new Minio.Client({
    endPoint: config.MINIO_SERVER,
    accessKey: config.MINIO_ACCESS_KEY,
    secretKey: config.MINIO_SECRET_KEY,
    useSSL: true
});

function uploadToMinio(filename, user, cb) {

    setTimeout(() => {

        rStats = fs.statSync(`./${filename}.pdf`);
        rSizeInBytes = rStats.size;
        console.log("the file weighs " + rSizeInBytes + " bytes.")

        // Upload receipt to minio server
        let metaData = {
              'Content-Type':'application/pdf',
              'Content-Length':rSizeInBytes
              };

        minioClient.fPutObject('receipts', `./${filename}.pdf`, `${filename}.pdf`, metaData, (err) => {
            if (err) {
                cb(err);
            } else {
                // If the user want to receive receipts by mail
                if (user.account.send_receipts) {
                    sendReceiptEmail(filename, user, cb);
                } else {
                    removeReceiptfromFs(filename, cb);
                }
            }
        });
    }, 2 * 1000);
}
```

## Expected Behavior
The minio client sdk uploads the pdf file to the minio server bucket.

## Current Behavior
The upload doesn't happen as the server throws this error:

> S3Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.

## Possible Solution
Maybe this has something to do with nginx?

Another lead could be the metadata? Are there any mandatory fields to be used in the metadata?

Maybe it could come from character encoding issues?

## Steps to Reproduce (for bugs)
I'm not sure it's a bug, it could be that I lack some knowledge... I've been looking for a while but I'm a beginner.

1. install minio server
2. install nginx, using certbot to handle https (I let certbot modify nginx conf files automatically)
3. install node server w/ minio js sdk to upload a pdf file using fPutObject
4. use the fPut function to upload the file

## Context
This issue started happening 2 years ago but no one cared until I started digging recently.

Before that, the files uploaded well for a few months and then it stopped working. The last uploaded file dates back to Sept 26 2016. Since late 2016, no one has maintained the service. I started looking 10 days ago and got the "Signature error" from the start. Since then, I've cleaned up a lot of things and updated all servers and packages and what not but I'm still getting the same error.

## Your Environment

**new set up**
ubuntu 16.04
mongo 3.6.5
minio server 2018-08-25T01:56:38Z
minio JS client SDK 7.0.0
nginx 1.14.0
node 8.11.4 (the node app is running in a Docker container)
express 4.14.0
mongoose 5.2.3

**old set up**
debian 8
mongo 3.4.10
minio server 2016-12-13T17:19:42Z
minio JS client SDK 2.0.3
nginx 1.11.4
node 6.9.1 (the node app is running in a Docker container)
express 4.13.0
mongoose 4.5.0

**Comment by nitisht** [comment]
can you please paste the nginx config here

**Comment by incolas** [comment]
Thank you for replying so quick. 

The configuration is split in several files, here's the main one and the one related to the minio server below.

Also I realize I forgot to mention the node app supposed to upload the file is ran on a Docker container. I'll edit my original post now in this regard.

nginx.conf
```
user  nginx;
worker_processes  4;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
    multi_accept        on;
    use                 epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Basic Settings
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # SSL Settings
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    ssl_session_tickets off;
    ssl_stapling on;
        ssl_stapling_verify on;

    # DH
    ssl_dhparam /etc/nginx/dhparam.pem;

    # Logging Settings
    access_log off;

    # Gzip Settings
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1000;

    include /etc/nginx/conf.d/com/*.conf;
}
```


assets.conf (located in conf.d/com)
```
upstream minio_servers {
    least_conn;                 # Use Least Connections strategy
    server xx.xx.xx.xx:9000;
}

server {
    server_name assets.domain.com;

    # Set log files path
    access_log off;
    error_log  /var/log/nginx/assets.domain.com-error.log error;

    # Disbale logging thoses specific files
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    # Return 410 on php page to force search engines to forget the old website version
    location ~ \.php {
        return 410;
    }

    # Redirect request to upstream servers
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://minio_servers/;
        proxy_redirect off;

      # Handle Web Socket connections
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
     }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by harshavardhana** [comment]
```
let minioClient = new Minio.Client({
    endPoint: config.MINIO_SERVER,
    port: 443,
    accessKey: config.MINIO_ACCESS_KEY,
    secretKey: config.MINIO_SECRET_KEY,
    useSSL: true
});
```

Can you try with this ? And make sure you have removed the port from endPoint param ?

**Comment by incolas** [comment]
I just tried adding port 443 but I got the same error.

**Comment by incolas** [comment]
I also tried using a 3rd server but it didn't change the behavior one bit.

**Comment by sinhaashish** [comment]
I am looking into this issue.

**Comment by incolas** [comment]
Hey guys, today I tried to run the node app outside of Docker, which took me quite some time since I'm so noob, but in the end I got just as far as with Docker and collected the same error.

**Comment by incolas** [comment]
Hey guys, I just wanted to let you know I had to take Minio out of the equation here: i'm now using Mongodb instead for the storage, which isn't as convenient but for now it'll do.

Let me know if you ever get to find out what's wrong here. I still plan on using Minio, I think it's an amazing resource.

**Comment by kannappanr** [comment]
@incolas I used the following code 
```
const Minio = require('minio')
const fs = require('fs')

var minioClient = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: false,
  accessKey: 'minio',
  secretKey: 'minio123'
})

function uploadToMinio(filename, cb) {

    setTimeout(() => {

        rStats = fs.statSync(`./${filename}.pdf`);
        rSizeInBytes = rStats.size;
        console.log("the file weighs " + rSizeInBytes + " bytes.")

        // Upload receipt to minio server
        let metaData = {
              'Content-Type':'application/pdf',
              'Content-Length':rSizeInBytes
              };
minioClient.traceOn(process.stdout)
        minioClient.fPutObject('test', `${filename}.pdf`, `./${filename}.pdf`, metaData, (err) => {
            if (err) {
		
                cb(err);
            } else {
               console.log("success")
            }
        });
    }, 2 * 1000);
}

uploadToMinio('test', (err) => {
  console.log(err)
})
```
I did not see any errors when I connected to `minio` directly instead of using an nginx.

Can you also try this to talk to your minio directly instead of using nginx. Also, when you run `minio`, can you enable HTTP Tracing? 

This can be done by 

`MINIO_HTTP_TRACE=/dev/stdout minio server /data`

Once this is done, can you paste the output of both the client side and server side logs that you see on the console, for two scenarios.
1. When you connect directly to minio 
2. When you connect to nginx

Definitely one of the headers is being modified by nginx and hopefully this might help us identify the header(s).

**Comment by harshavardhana** [comment]
Closing this as per comment https://github.com/minio/minio/issues/6438#issuecomment-422858664
