### ISSUE TITLE
mc recursive and force not removing folders

### ISSUE THREAD

**Issue by thbeh** [minio/minio#6440]
I am using minio for Apache Spark and using cookbook https://github.com/minio/cookbook/blob/master/docs/apache-spark-with-minio.md. While it did work but some issues occur with the test-write and I can't remove the folders generated by Spark using mc rm --recursive --force. 

Any help?

**Comment by nitisht** [comment]
@thbeh can you tell us the Minio, mc versions you're using?

btw, please use the issue template while reporting issues.

**Comment by thbeh** [comment]
Firstly, my apologies for not using the template. For the minio server I am using on k8 and it's is using the minio/minio:latest , not exactly sure what's the version but the below is from the web ui.

Minio :-
    Version
    2018-09-01T00:38:25Z
    Memory
    Used: 6.0 MB | Allocated: 30 GB | Used-Heap: 6.0 MB | Allocated-Heap: 28 MB
    Platform
    Host: minio-2 | OS: linux | Arch: amd64
    Runtime
    Version: go1.10.2 | CPUs: 2

MC version: -
Version: 2018-09-06T23:26:56Z
Release-tag: RELEASE.2018-09-06T23-26-56Z
Commit-id: 0d0638b398e69887b5d7c0abcfb32882fd37b1fd

**Comment by harshavardhana** [comment]
This is fixed in master the issue was in deleting empty directories.

**Comment by nitisht** [comment]
@thbeh can you try with master and let us know how it goes

**Comment by harshavardhana** [comment]
Fixed by 

```
commit 1961f2ef54781f07b56faa31f229c8918c1be29e
Author: Anis Elleuch <vadmeste@users.noreply.github.com>
Date:   Thu Sep 6 01:38:03 2018 +0200

    xl: Fix removing an empty directory (#6421)
    
    Removing an empty directory is not working because of xl.DeleteObject()
    was only checking if the passed prefix is an actual object but it
    should also check if it is an empty directory.
```

**Comment by thbeh** [comment]
Do I need to generate a new Docker image to be use by kubernetes from the master branch?

**Comment by harshavardhana** [comment]
> Do I need to generate a new Docker image to be use by kubernetes from the master branch?

you can use `minio/minio:edge`

**Comment by thbeh** [comment]
Will try. Thanks

**Comment by harshavardhana** [comment]
> Will try. Thanks

We also made a release you don't need to try `:edge` no more.

**Comment by deekoder** [comment]
@thbeh  we will close this issue then. Please try it out and let us know if you have any questions.
