### ISSUE TITLE
Migration, docs and mc changes required in dist mode for domain conf setting

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#6450]
Defining and exporting `MINIO_DOMAIN` environment variable became mandatory for Minio distributed mode, after release `minio.RELEASE.2018-08-18T03-49-57Z` (the problem was introduced when config.json file information was migrated to the backend).
We have to make several changes in our code to be able to make migration and mc keep working seamlessly even after declaring to the community/end-users that defining and exporting `MINIO_DOMAIN` environment variable is mandatory when domain information is needed to be set in distributed mode.

## Expected Behavior
Migration:
If domain information is set in the old/removed config.json file with no `MINIO_DOMAIN` environment variable defined in an older release ( < `minio.RELEASE.2018-08-18T03-49-57Z`), as part of the migration process, we have to warn the user during the start up messages that s/he needs to define and export the environment variable, `MINIO_DOMAIN` to preserve the domain setting. Otherwise, it will be lost.
The domain setting is also NOT going to be copied over into the new configuration data location.

MC:
If user runs `mc admin config setkeys domain=xxx` or `mc admin config getkeys domain` command to set/retrieve the domain information,  we should reject the request and fail both commands with an error message.
If user runs `mc admin config set <full_config_info>`, the command should ignore the domain information and inform the user that the domain information is ignored in distributed mode.
If user runs `mc admin config set <full_config_info>`, the command should skim the domain information from the returned configuration information.

Documentation:
Docs need to be changed to reflect the new behavior.

## Regression
Yes, this is  a regression.
`minio.RELEASE.2018-08-18T03-49-57Z`

**Comment by harshavardhana** [comment]
This is fixed already as part of the documentation in #6498,  mc related changes please open an issue in minio/mc
