### ISSUE TITLE
Minio hangs on some HTTP request

### ISSUE THREAD

**Issue by Kanshiroron** [minio/minio#6459]
Hello,
We are facing a very weird bug with Minio: with some requests, it doesn't answer the HTTP request, and the client timeout.

Here a simple way to reproduce:
1 - Run Minio : `docker run -d --name minio -e MINIO_ACCESS_KEY="ACCESS_KEY_ID" -e MINIO_SECRET_KEY="ACCESS_KEY" -p 9000:9000 minio/minio:RELEASE.2018-09-11T01-39-21Z server /home`

2 - Configure Minio:
  - `mc --config-folder $(pwd) config host add s3 http://localhost:9001 ACCESS_KEY_ID ACCESS_KEY S3v4`
  - `mc --config-folder $(pwd) mb s3/cryptobox-bucket`
  - `mc --config-folder $(pwd) policy public s3/cryptobox-bucket`

3 - Try to access a file inside this empty bucket: `echo -en "GET /cryptobox-bucket/12345678 HTTP/1.1\r\nConnection: Keep-Alive\r\nAccept-Encoding: gzip\r\nUser-Agent: Go-http-client/1.1\r\nHost: docker-host.test.cryptobox.com\r\n\r\n" | nc -v 127.0.0.1 9000 -v`. It says the connection succeeded but nothing happen!

The weird thing is that if you remove some header the server may answer, and if you vary the length of the object, it may as well...

We couldn't narrow the scope further...

Best regards,

**Comment by harshavardhana** [comment]
Thanks I think the fix is already being submitted here https://github.com/minio/minio/pull/6453
