### ISSUE TITLE
Drag directory into minio browser

### ISSUE THREAD

**Issue by scher200** [minio/minio#6470]
## Expected Behavior
When I drag a directory, containing files, into the the minio browser I like to see it automatically create the folder and copy the files into it. 

## Current Behavior
It calls out: "Error occurred uploading 'NewFolder'."

## Possible Solution
Autocreate this NewFolder and upload files as normally

## Steps to Reproduce (for bugs)
1. Open minio browser
2. Drag a directory, containing files, into the the minio browser 
3. See the error appear

## Context
As far as I know on every platform with any folder containing any number of files results into this error

## My Environment 
```
    Version
    2018-06-08T03:49:38Z
    Memory
    Used: 5.3 MB | Allocated: 50 MB | Used-Heap: 5.3 MB | Allocated-Heap: 11 MB
    Platform
    Host: a2ad0b825c18 | OS: linux | Arch: amd64
    Runtime
    Version: go1.10.2 | CPUs: 2
```

**Comment by kannappanr** [comment]
@scher200 Thanks for filing this issue. We do not allow for drag and drop of folders. We allow only for drag and drop of files. You can still select multiple files within a folder and upload in one go. Will check internally and see if we plan to support this feature.

**Comment by scher200** [comment]
@kannappanr Would be great because that would also help people create directories easily from within the UI

**Comment by deekoder** [comment]
@scher200 we will finish up our current ongoing enhancements to the browser and get to this request in the next round of enhancements for the browser. Parking it in future milestone until then. Typically we close the issue and then reactivate it when we are ready for the next set of browser enhancements.

**Comment by scher200** [comment]
@deekoder ok!
