### ISSUE TITLE
Measure performance metrics between AWS S3 Select and Minio select implementation

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#6473]
@badscooter23 from our community indicated that he is observing some performance challenges and sporadic changes in performance based on the query input. 

https://github.com/prgxlabs/select-benchmarking use this to benchmark and table the results for understanding, this is a broader issue avoiding our issue template for the moment.

This needs to be validated holistically for the entire Select API functionality, so consider this as an umbrella bug.

**Comment by Praveenrajmani** [comment]
Benchmarks hit for `s3`,`play`,`minio-fs`,`minio-xl` are reported accordingly,

![image](https://user-images.githubusercontent.com/5410427/45682055-d9303280-bb5c-11e8-93a8-c58fc6fc7348.png)

**Comment by deekoder** [comment]
Thanks @Praveenrajmani I think we need to now translate this to see what changes we may need to make to improve perf.

**Comment by nitisht** [comment]
we already have an idea of the perf difference, closing this for now.
