### ISSUE TITLE
How to make folders support Chinese naming

### ISSUE THREAD

**Issue by mclitao** [minio/minio#6481]
How to create a bucket with a Chinese name？
Get the prompt message：“The specified bucket is not valid”

**Comment by harshavardhana** [comment]
Chinese buckets are not supported yet, this limitation is based on AWS S3 bucket restrictions.

**Comment by deekoder** [comment]
@mclitao at the moment, this is working as intended. We will add this support when AWS S3 also supports it.

**Comment by mclitao** [comment]
I see. Thank you.
