### ISSUE TITLE
Unable to create configuration directories." cause="mkdir /root/.minio/certs: permission denied

### ISSUE THREAD

**Issue by leonGravel** [minio/minio#6482]
I get an error when I install it with this command:
```
sudo docker run -p 9000:9000 --name minio1 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=123456" -v /mnt/data:/data -v /mnt/config:/root/.minio minio/minio server /data
```
error msg:
```
time="2018-09-18T09:40:23Z" level=fatal msg="Unable to create configuration directories." cause="mkdir /root/.minio/certs: permission denied" source="[server-main.go:144:serverMain()]" 
```
Is there a problem with my command?
How can I solve it?

**Comment by nitisht** [comment]
Can you paste the output of 

`ls -la /root/.minio/`

Also did you run the Minio server previously with same config directory?

**Comment by leonGravel** [comment]
@nitisht thanks for your reply! 
this is the output:
```
ls: cannot access /root/.minio/: No such file or directory
```
I used to install minio with docker, but I didn't specify the data volume, so I deleted the previous container and reinstalled with this command.

**Comment by dingjs** [comment]
I use `setenfoce 0`,and everything woks fine again.

**Comment by leonGravel** [comment]
@dingjs thanks a lot!
The cause of the problem is indeed because of the security policy of selinux.
