### ISSUE TITLE
Crashing with Out of Memory Errors (refs 6164)

### ISSUE THREAD

**Issue by tylerforsythe** [minio/minio#6490]
I hate to be the bearer of bad news, @harshavardhana , but the fix has not been working for me. I've upgraded to all the most recent Minio.exe builds since the last post in this issue, but with no success. I've delayed responding here in case the fix was in a build later than I thought, and because I found an issue in my environment and wondered if it was related. I've determined it is not but will outline what I've found in the past month.

I noticed as time went on that Minio started reporting read errors on my V: drive, but not any of the others. Separately, I discovered while trying to copy a set of large files from my V: drive (completely unrelated to Minio) that there was at least one corrupted file in the mix. This led me to believe my V drive was experiencing data corruption, and I wondered if it was the culprit of problems all along. I replaced both my V and X drives. Because they're identical and were purchased at the same time, I replaced both just in case the X drive was soon to follow. Two brand-new 6 TB drives are in their place.

This allowed me a chance to test Minio's healing capabilities, which so far are working OK. However, I've not been able to fully test it (I've only healed about half my data set so far) because Minio continues to crash with out of memory errors after 6-7 hours of run time. I brainstormed that if this out of memory error cannot be fixed I could heal in two stages to work-around the bug. First the V and X drives, which should heal their data in this "new" format. Then delete the Minio data on W and Y and heal back to those drives. Thus getting all my data into the new format in a very round-about (and dangerous) fashion.

But like I said, because Minio continues to crash with out of memory exceptions during the heal, I've yet to accomplish this in full. My previous screenshot shows my Minio data at 294 GB, and currently I've only healed about 154 GB. The healed amount tends to change unpredictably. Sometimes it will run for hours and appear to make 0 progress (the V and X data directories are not larger), and other times they will grow by several GB. It's almost as if the process is starting over every single time and it only makes progress if it happens to run longer than last time. I'm not sure, though.

Further, even without the heal running, the W and Y drives continue to be hammered while Minio consumes more and more memory for several hours before crashing. This is puzzling to me, because with the number of times I've run Minio it has to have a total run time of at least 50 hours, maybe much more. Assuming a read/write speed of just 10 MB a second, which is very slow for a SATA drive, even platter-based, it would have been able to read/write 1.8 TB of data from each drive. Even if speed were half that at 5 MB/s, that's still 900 GB. Half that, 2.5 MB/s would be 450 GB in that time period. Given my total data set is ~300 GB, I am extremely puzzled as to why it's not done yet unless it is restarting progress every single time. Which isn't logical given that no software would try to complete 300 GB worth of work before writing out progress. That wouldn't make sense.

Can you shed any light into what's going on here? My last resort is to simply delete everything and restart with no data. That's not the end of the world because my most important backup copy is off-site. Having stuff locally is for a more convenient full-copy.

I've attached CPU and MEM logs that I gathered yesterday, letting it run for a few hours and _not_ healing, just doing it's behind-the-scenes work. Again, it slammed usage of my W and Y drives, as well as the CPU. I stopped it before a crash to get the log output. The CPU log is shorter than the mem one due to my schedule, but it still has a couple hours.

Thank you.

[mem_20180918.txt](https://github.com/minio/minio/files/2397728/mem_20180918.txt)
[cpu_20180918.txt](https://github.com/minio/minio/files/2397729/cpu_20180918.txt)

_Originally posted by @tylerforsythe in https://github.com/minio/minio/issue_comments#issuecomment-422851849_

**Comment by harshavardhana** [comment]
> I hate to be the bearer of bad news, @harshavardhana , but the fix has not been working for me. I've upgraded to all the most recent Minio.exe builds since the last post in this issue, but with no success. I've delayed responding here in case the fix was in a build later than I thought, and because I found an issue in my environment and wondered if it was related. I've determined it is not but will outline what I've found in the past month.

@tylerforsythe what is the minio version?

**Comment by tylerforsythe** [comment]
@harshavardhana 
Version: 2018-09-12T18:49:56Z
Release-Tag: RELEASE.2018-09-12T18-49-56Z
Commit-ID: ce419c98352324caa4c79b159a9f840ca714c3d5

**Comment by harshavardhana** [comment]
From what it looks like windows code path in Go is notorious in its allocations etc

```
ROUTINE ======================== unicode/utf16.Decode in /home/harsha/.gimme/versions/go1.10.2.linux.amd64/src/unicode/utf16/utf16.go
   75.14GB    75.14GB (flat, cum)  4.84% of Total
         .          .     84:}
         .          .     85:
         .          .     86:// Decode returns the Unicode code point sequence represented
         .          .     87:// by the UTF-16 encoding s.
         .          .     88:func Decode(s []uint16) []rune {
   75.14GB    75.14GB     89:   a := make([]rune, len(s))
         .          .     90:   n := 0
         .          .     91:   for i := 0; i < len(s); i++ {
         .          .     92:           switch r := s[i]; {
         .          .     93:           case r < surr1, surr3 <= r:
         .          .     94:                   // normal rune
ROUTINE ======================== unicode/utf16.Encode in /home/harsha/.gimme/versions/go1.10.2.linux.amd64/src/unicode/utf16/utf16.go
  223.73GB   223.73GB (flat, cum) 14.41% of Total
         .          .     59:           if v >= surrSelf {
         .          .     60:                   n++
         .          .     61:           }
         .          .     62:   }
         .          .     63:
  223.73GB   223.73GB     64:   a := make([]uint16, n)
         .          .     65:   n = 0
         .          .     66:   for _, v := range s {
         .          .     67:           switch {
         .          .     68:           case 0 <= v && v < surr1, surr3 <= v && v < surrSelf:
         .          .     69:                   // normal rune
```

List of GB worth allocations
```
         0   449.07GB (flat, cum) 28.93% of Total
         .   449.07GB    375:			fi, err := os.Stat(entry)
         0   119.34GB (flat, cum)  7.69% of Total
         .   119.34GB    251:		return strings.HasSuffix(strings.ToLower(s), strings.ToLower(suffix))
   18.22GB   197.21GB (flat, cum) 12.71% of Total
   18.22GB   197.21GB    167:	return path.Join(elem...) + trailingSlash
         0   786.54GB (flat, cum) 50.67% of Total
         .   786.54GB     30:	return readDirN(dirPath, -1)
   61.68GB   786.54GB (flat, cum) 50.67% of Total
         .   480.25GB     35:	d, err := os.Open(dirPath)
         .      143GB     50:	st, err := d.Stat()
         .     2.55GB     64:		e := syscall.FindNextFile(syscall.Handle(d.Fd()), data)
         .    99.06GB     77:		name := syscall.UTF16ToString(data.FileName[0:])
   53.97GB    53.97GB    101:			entries = append(entries, name+slashSeparator)
    7.71GB     7.71GB    103:			entries = append(entries, name)
         .   449.07GB     33:	if err := usageFn(ctx, path); err != nil {
         .   119.34GB     37:	if !hasSuffix(path, slashSeparator) {
         .   786.54GB     41:	entries, err := readDir(path)
         .   197.21GB     47:		fname := pathJoin(path, entry)
  246.87kB      143GB (flat, cum)  9.21% of Total
         .      143GB     22:		return Stat(file.dirinfo.path)
         0   480.25GB (flat, cum) 30.94% of Total
         .   480.25GB    250:	return OpenFile(name, O_RDONLY, 0)
         0   480.26GB (flat, cum) 30.94% of Total
         .   480.26GB    269:	return openFileNolog(name, flag, perm)
         0   592.07GB (flat, cum) 38.14% of Total
         .   592.07GB     13:	return statNolog(name)
  104.02GB   104.02GB (flat, cum)  6.70% of Total
    1.29GB     1.29GB     46:	f := &File{&file{
  102.74GB   102.74GB     52:		name: name,
  120.97GB   352.55GB (flat, cum) 22.71% of Total
   18.23GB    18.23GB    110:		mask = path + `\*`
         .   127.57GB    112:	maskp, e := syscall.UTF16PtrFromString(mask)
  102.74GB   102.74GB    116:	d := new(dirInfo)
         .   104.02GB    146:	f := newFile(r, name, "dir")
         0   127.70GB (flat, cum)  8.23% of Total
         .   127.70GB     95:	r, e := syscall.Open(fixLongPath(name), flag|syscall.O_CLOEXEC, syscallMode(perm))
   32.19kB   480.26GB (flat, cum) 30.94% of Total
         .   127.70GB    156:	r, errf := openFile(name, flag, perm)
         .   352.55GB    160:	r, errd := openDir(name)
   61.64GB   592.07GB (flat, cum) 38.14% of Total
         .   530.43GB     67:	namep, err := syscall.UTF16PtrFromString(fixLongPath(name))
   61.64GB    61.64GB     75:	var fs fileStat
  119.31GB   119.31GB (flat, cum)  7.69% of Total
   59.66GB    59.66GB     41:		b.buf = make([]byte, len(b.s))
   59.65GB    59.65GB     52:	return string(b.buf[:b.w])
         0   178.99GB (flat, cum) 11.53% of Total
         .   178.99GB    158:			return Clean(strings.Join(elem[i:], "/"))
   59.68GB    59.68GB (flat, cum)  3.84% of Total
   59.68GB    59.68GB    424:		return a[0] + sep + a[1]
  119.34GB   119.34GB (flat, cum)  7.69% of Total
   59.68GB    59.68GB    597:		b := make([]byte, len(s))
   59.66GB    59.66GB    605:		return string(b)
         0     2.55GB (flat, cum)  0.16% of Total
         .     2.55GB    949:	err = findNextFile1(handle, &data1)
         0   127.70GB (flat, cum)  8.23% of Total
         .   127.57GB    251:	pathp, err := UTF16PtrFromString(path)
  561.84GB   785.56GB (flat, cum) 50.61% of Total
  561.84GB   785.56GB     43:	return utf16.Encode([]rune(s + "\x00")), nil
         0   785.56GB (flat, cum) 50.61% of Total
         .   785.56GB     70:	a, err := UTF16FromString(s)
   23.92GB    99.06GB (flat, cum)  6.38% of Total
   23.92GB    99.06GB     55:	return string(utf16.Decode(s))
    2.55GB     2.55GB (flat, cum)  0.16% of Total
    2.55GB     2.55GB     34:	return e
   75.14GB    75.14GB (flat, cum)  4.84% of Total
   75.14GB    75.14GB     89:	a := make([]rune, len(s))
  223.73GB   223.73GB (flat, cum) 14.41% of Total
  223.73GB   223.73GB     64:	a := make([]uint16, n)
```

I can see disk usage crawling cannot be optimized due to various memory hogging code paths for windows, it is better that we turn off usage calculation on windows. which would immediately make your server stable.

**Comment by deekoder** [comment]
thanks for reporting this @tylerforsythe

**Comment by deekoder** [comment]
@harshavardhana is turning the calculations on/off configurable?

**Comment by harshavardhana** [comment]
> @harshavardhana is turning the calculations on/off configurable?

Not yet we need to bring that in some form

**Comment by harshavardhana** [comment]
@tylerforsythe would you be interested in validating a smaller fix on your end?

**Comment by tylerforsythe** [comment]
@harshavardhana sure!

**Comment by harshavardhana** [comment]
Can you set GOGC=10 environment variable for your Minio service ?? Please capture memory profile and let us know how it goes.

**Comment by tylerforsythe** [comment]
I ran it for about 4 hours today. Memory consumption maybe seemed better but was still escalating. I terminated it to get the log. I then started it again and will just let it go this time to see how long it lasts.

Below is the mem log file, as well as a screenshot of: the environment variable to make sure it was done correctly, the PowerShell window I started minio from, and the Task Manager showing activity/usage.

[mem_20180920.pprof.txt](https://github.com/minio/minio/files/2403489/mem_20180920.pprof.txt)
![minio 20180920 screens](https://user-images.githubusercontent.com/1689004/45853526-23531880-bd03-11e8-9352-28268d9f594f.png)

**Comment by tylerforsythe** [comment]
Quick update: it crashed as usual after about ~6 hours.

**Comment by harshavardhana** [comment]
> Quick update: it crashed as usual after about ~6 hours.

Thanks do you have an estimate on how many directories and files do you have on these volumes?

**Comment by harshavardhana** [comment]
```
go tool pprof -alloc_space ./minio.exe /home/harsha/Downloads/mem_20180920.pprof.txt 
File: minio.exe
Type: alloc_space
Time: Sep 20, 2018 at 1:55pm (PDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1900.65GB, 93.96% of 2022.76GB total
Dropped 785 nodes (cum <= 10.11GB)
Showing top 10 nodes out of 29
      flat  flat%   sum%        cum   cum%
  744.48GB 36.81% 36.81%  1040.95GB 51.46%  syscall.UTF16FromString
  296.47GB 14.66% 51.46%   296.47GB 14.66%  unicode/utf16.Encode
  160.37GB  7.93% 59.39%   467.26GB 23.10%  os.openDir
  158.18GB  7.82% 67.21%   158.18GB  7.82%  strings.ToLower
  137.88GB  6.82% 74.03%   137.88GB  6.82%  os.newFile
   84.25GB  4.17% 78.19%    84.25GB  4.17%  unicode/utf16.Decode
   81.72GB  4.04% 82.23%   784.69GB 38.79%  os.statNolog
   79.11GB  3.91% 86.14%    79.11GB  3.91%  path.(*lazybuf).string
   79.09GB  3.91% 90.05%    79.09GB  3.91%  path.(*lazybuf).append
   79.09GB  3.91% 93.96%    79.09GB  3.91%  strings.Join
```

```
(pprof) top10
Showing nodes accounting for 19625.58MB, 98.82% of 19859.05MB total
Dropped 251 nodes (cum <= 99.30MB)
Showing top 10 nodes out of 15
      flat  flat%   sum%        cum   cum%
19180.05MB 96.58% 96.58% 19501.49MB 98.20%  github.com/minio/minio/cmd.readDirN
  256.75MB  1.29% 97.87%   359.71MB  1.81%  syscall.UTF16FromString
  102.96MB  0.52% 98.39%   102.96MB  0.52%  unicode/utf16.Encode
   57.30MB  0.29% 98.68%   164.70MB  0.83%  os.openDir
   28.44MB  0.14% 98.82%   270.56MB  1.36%  os.statNolog
    0.05MB 0.00028% 98.82% 19853.48MB   100%  github.com/minio/minio/cmd.(*posix).diskUsage
    0.04MB 0.00018% 98.82% 19853.04MB   100%  github.com/minio/minio/cmd.getDiskUsage
         0     0% 98.82%   205.61MB  1.04%  github.com/minio/minio/cmd.(*posix).diskUsage.func1
         0     0% 98.82% 19501.49MB 98.20%  github.com/minio/minio/cmd.readDir
         0     0% 98.82% 19853.01MB   100%  github.com/minio/minio/cmd.walk
```

Looks like it didn't help, Go is allocating way more than it can handle in garbage collection. Let me think about a solution.

**Comment by harshavardhana** [comment]
```
grep GB test 
Total: 19.39GB
   56.22kB    19.39GB (flat, cum)   100% of Total
         .    19.39GB    386:	if err := getDiskUsage(context.Background(), s.diskPath, usageFn); err == errWalkAbort {
   36.07kB    19.39GB (flat, cum)   100% of Total
   36.07kB    19.39GB     26:	return walk(ctx, root+slashSeparator, usageFn)
         0    19.04GB (flat, cum) 98.20% of Total
         .    19.04GB     30:	return readDirN(dirPath, -1)
   18.73GB    19.04GB (flat, cum) 98.20% of Total
   18.73GB    18.73GB    101:			entries = append(entries, name+slashSeparator)
         0    38.78GB (flat, cum) 199.94% of Total
         .    19.04GB     41:	entries, err := readDir(path)
         .    19.39GB     48:		if err = walk(ctx, fname, usageFn); err != nil {
```

```
   18.73GB    18.73GB    101:                   entries = append(entries, name+slashSeparator)
```

From what it looks like there are 20 million directories assuming they are each upto 1k string size, also are these directories in the same top level directory? how many nested directories do you have? overall from what it looks like you have many files in the same top level directory without hierarchy?

**Comment by tylerforsythe** [comment]
20 million directories seems really high. It's a backup of my personal files (pictures, music, documents, source code, etc). There's a lot but I just can't imagine 20 million unless my backup software is getting super-crazy (I didn't write backup software, unfortunately). Is there a command I can run to ask minio to count? Whenever I do `mc admin info local` the "Storage" value is different every time, so I don't know if that's useful or not.

I'm not sure if minio stores files on disk like the actual hierarchy, but according to the latest properties window of one of the data directories (see attachment below) it's 722,000 files and 361,000 folders on each drive. But if minio does not store 1 to 1 mapping then that is meaningless.

I'm pretty sure my backup software _does_ store files in a relatively flat hierarchy, meaning it has like 2 directory levels and a particular folder it dumps 99% of its objects into. I think this works fine on an enterprise balanced/distributed service like S3 and Wasabi, but I may be having trouble given that this is a single machine.

![image](https://user-images.githubusercontent.com/1689004/45862136-9e312900-bd2d-11e8-81c7-f7c32ed5092a.png)

**Comment by tylerforsythe** [comment]
Also, I'm **extremely grateful** for the time and effort you're spending on this. If it reaches a point where it's just not worth it for you to pursue further, I understand.

**Comment by harshavardhana** [comment]
> I'm not sure if minio stores files on disk like the actual hierarchy, but according to the latest properties window of one of the data directories (see attachment below) it's 722,000 files and 361,000 folders on each drive. But if minio does not store 1 to 1 mapping then that is meaningless.

Does your backup software also list files on a regular basis? how often does it do that? - I don't think the above value is true because from what i can see readDir() is returning a lot of entries. 

Let me provide a debug binary which might provide a good indication here @tylerforsythe about the number of objects/directories.

**Comment by tylerforsythe** [comment]
Hmm, I'm not sure how often it lists files, but I can completely disable it for a few days/weeks if you think that would help.

Looking forward to the debug build. Thanks again.

**Comment by harshavardhana** [comment]
@tylerforsythe can you download the attached binary? and please provide the output of console attached here?  [minio.zip](https://github.com/minio/minio/files/2407279/minio.zip)

**Comment by tylerforsythe** [comment]
It's running now and logging to a file. How long should I let it run? Until it crashes? It's been running a little over an hour and the out file that the console is logging to is currently 2 GB.

**Comment by harshavardhana** [comment]
2GB is good enough. You can stop and use the released binary for now.

**Comment by tylerforsythe** [comment]
Excellent. Here is a link to download the compressed log file (225 MB). Uncompressed it is 7.5 GB, so watch out. :)
https://s3.amazonaws.com/randomtyler-public/minio_debug_out.7z

**Comment by harshavardhana** [comment]
> Excellent. Here is a link to download the compressed log file (225 MB). Uncompressed it is 7.5 GB, so watch out. :)
> https://s3.amazonaws.com/randomtyler-public/minio_debug_out.7z

I downloaded the file and it seems to have some non-string values how is that possible - since the debug binary only prints numbers? 

```go
 git show
commit 08ba4156e8da3b87b2152aefbdf73d55aa90e4fb (HEAD -> debugging)
Author: Harshavardhana <harsha@minio.io>
Date:   Fri Sep 21 16:11:09 2018 -0700

    Mem debug

diff --git a/cmd/posix-list-dir_windows.go b/cmd/posix-list-dir_windows.go
index 082f9d6eb..6ee285097 100644
--- a/cmd/posix-list-dir_windows.go
+++ b/cmd/posix-list-dir_windows.go
@@ -19,6 +19,7 @@
 package cmd
 
 import (
+       "fmt"
        "os"
        "path"
        "strings"
@@ -32,6 +33,10 @@ func readDir(dirPath string) (entries []string, err error) {
 
 // Return N entries at the directory dirPath. If count is -1, return all entries
 func readDirN(dirPath string, count int) (entries []string, err error) {
+       defer func() {
+               fmt.Println("ReadDirN", len(entries), err)
+       }()
+
        d, err := os.Open(dirPath)
        if err != nil {
                // File is really not found.
@@ -102,6 +107,7 @@ func readDirN(dirPath string, count int) (entries []string, err error) {
                default:
                        entries = append(entries, name)
                }
+               fmt.Println("syscall.NextFile", len(entries), len(name+slashSeparator))
                if remaining > 0 {
                        remaining--
                        done = remaining == 0
```

**Comment by harshavardhana** [comment]
Actually found it the file seems to have UTF-16 characters @tylerforsythe , converting the file to utf-8

**Comment by harshavardhana** [comment]
@tylerforsythe I looked at the logs, I don't see how the memory usage can be this high. It does look like there are a lot of readdir operations and each readdir is happening on around 99k+ entries. 

It would be beneficial to perhaps do a remote session and see this first hand. Right now I don't have much clue on why the memory usage can be this high.

**Comment by tylerforsythe** [comment]
@harshavardhana I am open to a remote session of some kind. What did you have in mind? Are you looking to Remote Desktop in when it's using 15 GB of RAM and use some sort of debugging tool?

**Comment by harshavardhana** [comment]
> @harshavardhana I am open to a remote session of some kind. What did you have in mind? Are you looking to Remote Desktop in when it's using 15 GB of RAM and use some sort of debugging tool?

Yes, ping me 'y4m4' on our slack https://slack.minio.io we can co-ordinate from there.

**Comment by tylerforsythe** [comment]
Ok, I'll pop in when I have a bit of time. Possibly tomorrow afternoon Mountain time. What time zone are you in?

**Comment by harshavardhana** [comment]
> Ok, I'll pop in when I have a bit of time. Possibly tomorrow afternoon Mountain time. What time zone are you in?

@tylerforsythe I am in PST

**Comment by harshavardhana** [comment]
@tylerforsythe shall we close this issue?

**Comment by tylerforsythe** [comment]
Yes, we can close it.

After working with @harshavardhana in Slack, we determined that the primary issue was that I was attempting to use Minio with data directories instead of giving Minio the entire disk. I.e., old command:

C:\home\minio\minio.exe --config-dir C:\home\minio\ server V:\MinioDataV\ W:\MinioDataW\ X:\MinioDataX\ Y:\MinioDataY\

New command:

C:\home\minio\minio.exe --config-dir C:\home\minio\ server V:\ W:\ X:\ Y:\

Notice that I'm giving minio entire drives rather than directories. This change immediately fixed all my CPU, memory, and disk usage problems. I now have over 3 TB stored inside minio with no utilization issues.

Thanks for the help!!

**Comment by dutchhsg** [comment]
There is a similar issue with minio on FreeBSD (FreeNAS):
https://forums.freenas.org/index.php?threads/minio-memory-usage-through-the-roof.73135/

This guy just upgraded his hardware (that's another way to solve it): 
https://github.com/minio/minio/issues/4102

I first tried to share the whole data pool with minio but that takes hours, still is not finished, and will probably screw up my buckets.
May have to revert to the former situation, and add an SSD to create a really big swap space. It is like pushing the accellerator instead of taking the handbrake off... but what else can I do?

See that thread.

**Comment by jcostian** [comment]
Having similar issues with minio on Docker, on ubuntu host. Using data directories instead of entire disk. After having 100k+ folders in minio and 250GB data, the minio memory consumption and CPU usage goes up, after running smoothly about 18-24 hours. And at the end minio just consumes all the memory that is left on the server (in this case it went up to about 16GB) and then stucks. Does not die, but only way to stop it is killing the minio process and then restarting the docker container.

Weren't running the latest version, but updated to the latest release now. Hoping it will help.

Could this be the same issue, or is that something that is related only to windows hosts?
Is using entire disk the only way to go?

**Comment by harshavardhana** [comment]
For the time being using entire disk is the only way to go @jcostian

**Comment by jcostian** [comment]
Ok, thanks for the quick reply.

Is there an issue open for this and a fix coming?

**Comment by dutchhsg** [comment]
I'm quite glad that the issue is not unique to my setup, but there is no real solution as I understand it. Minio should NOT use that much memory under any circumstances.

In my case, I just stopped using Cloudberry File Backup and used Image backup instead. Instead of 6 million files in one directory it creates a couple of files (a few big ones and incrementals every day). That is more of a workaround. I am not sure if the issue will return if one of the systems being backed up hits a certain amount of files in one dir again...

I described in the Freenas topic what happened when I shared a whole "disk" (actually: a data pool, and not a directory in it, with existing data). It took ages and afterwards the contents were in one big bucket after that. I reverted to the previous situation.

https://forums.freenas.org/index.php?threads/minio-memory-usage-through-the-roof.73135/

(Some systems are actually being used, and when the bug appears, it is not always possible to change the way minio is given access.) I tested Freenas and minio for weeks, and concluded I could use it for production data, before the bug appeared. So I cannot change my setup.

**Comment by jcostian** [comment]
Does anyone know if the problem is related to the fact that one single folder contains a huge amount of (100k+) files or folders? Would the same still happen if there was a more reasonable amount of files/folders in a single folder?

**Comment by harshavardhana** [comment]
> Does anyone know if the problem is related to the fact that one single folder contains a huge amount of (100k+) files or folders? Would the same still happen if there was a more reasonable amount of files/folders in a single folder?

It is happening because a single folder has 100k files and folders, reasonable amount files/folders won't have this problem.

**Comment by jcostian** [comment]
So even using data directories instead of entire volume works, if using reasonable amount of folders/files in one folder? Just to make things clear.

Thanks!

**Comment by harshavardhana** [comment]
> So even using data directories instead of entire volume works, if using reasonable amount of folders/files in one folder? Just to make things clear.

yes, absolutely - also fixing the original cause as well in subsequent releases.

**Comment by kaxap** [comment]
Does subfolder hierarchy have same effect as flat folder?

For example, we are having this issue with 1 million files (in 1 folder) in minio with data directories. 2-3 of our 8 servers consume 256 GB of RAM every 6-8 hours until restarted. The question is, will redistribution of files (100 parent dirs/100 child dirs/100 files) help to fight this issue?

**Comment by jcostian** [comment]
This is the solution we used, and didn't see the problem after changing to the deeper structure. So I suggest trying that.

**Comment by dutchhsg** [comment]
With "This is the solution we used" --- do you mean: redistribute files into subfolders?
(I do not have that option as far as Cloudberry goes, it automatically puts ALL files into one dir, even if the files were in separate folders before being backed up.)

That is not a solution but a workaround.

**Comment by jcostian** [comment]
Yes, we distributed the files to deeper folder structure, so that no folder contains too many files or folders. And that did solve the problem, even we are using data folders instead of full volume.
