### ISSUE TITLE
Can't change directory permissions or ownership via s3fs

### ISSUE THREAD

**Issue by djmaze** [minio/minio#6496]
When using s3fs or goofys as a client, chown'ing or chmod'ing directories does not have any effect.

## Expected Behavior
* After changing user / group owner or permissions of the directory, they should show up as changed when listing the parent directory afterwards 

## Current Behavior
* User / group ownership and permissions are shown the same as before

## Steps to Reproduce (for bugs)
1. export `AWSACCESSKEYID` and `AWSSECRETACCESSKEY`
1. Mount a Minio bucket with  `sudo s3fs -o allow_other -o url=http://myminio:9000 bucket /target`
1. `mkdir /target/dir`
1. `ls -nl /target   # dir has owner 1000`
1. `sudo chown 999 /target/dir`
1. `ls -nl /target   # dir still has owner 1000`

## Context
I would like to have the ability to use a bucket for storing data for different users.

## Regression
Is this issue a regression? Probably not

## Your Environment
* Version used (`minio version`): 2018-09-11T01:39:21
* s3fs-fuse version: 1.84
* Environment name and version: running the minio docker container
* Server type and version: Linux amd64
* Operating System and version (`uname -a`): Linux myhost 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@djmaze Thanks for reaching out to us. We will have to see this in context with s3fs. Will reach out to you if we have more questions.

**Comment by nitisht** [comment]
> When using s3fs or goofys as a client, chown'ing or chmod'ing directories does not have any effect.

@djmaze could you please help me with Minio trace for your Minio instance? It will help us understand how goofys / s3fs is translating such calls to S3 calls. 

You need to set the environment variable `MINIO_HTTP_TRACE` to a file path where you want the trace to be written. Then start the Minio server, and finally try the goofys/s3fs chown/chmod operations.

**Comment by djmaze** [comment]
@nitisht  Here is [a paste](https://pastebin.com/G8aSF8aL) of the minio trace when doing the steps outlined above using s3fs. Thanks for your attention!

**Comment by nitisht** [comment]
Thanks @djmaze , sorry for the delay in response, let me check this and get back to you

**Comment by nitisht** [comment]
@djmaze very sorry to have dropped the ball on this, I finally checked the logs and even reproduced it locally. 

This happens because directories (`/target/dir` in this case) are created as 0b objects on Minio backend, Minio server doesn't store any metadata related to these directories - while s3fs depends on the metadata for retrieving UID/GID etc. So, even when s3fs sends `X-Amz-Meta-Uid` to Minio server, it is not returned during a HEAD request, causing s3fs to show owner as the previous owner.

The same operation would work on files because Minio stores and returns relevant metadata set by s3fs.

This Minio behaviour is by design to keep backend simple, so AFAICS, `chown` for directories will not work currently on Minio server.

**Comment by nitisht** [comment]
@djmaze since there are no plans to support this as of now, closing the issue as won't fix. Please do feel free to ask further questions if you have any.

**Comment by merajnouredini** [comment]
so this means that we have to have a flat structure in every bucket and we cannot create/copy directories using s3fs with Minio server?

**Comment by harshavardhana** [comment]
Of course you can @m-nouredini s3fs likes to imitate POSIX semantics on directories, currently we have no plans.

You can create sub-directories or just upload objects to any desired prefix the parents are automatically created either like.

```
mc mb play/testbucket/a/b/my/favorite/prefix/
```

Or

```
mc cp /etc/hosts play/testbucket1/a/b/my/favorite/prefix/a.txt
```

**Comment by harshavardhana** [comment]
This issue resolution is not indicating that you should dump all your objects at bucket level, which is a bad idea to begin with for your backend disk as well as MinIO.

It is better to properly choose heirarchy, MinIO keeps the heirarchy as is on the backend. So making that choice will help you in the long run.

**Comment by merajnouredini** [comment]
Now I got your point, Thanks for the description @harshavardhana.
