### ISSUE TITLE
uploading small file very slow

### ISSUE THREAD

**Issue by ciaoben** [minio/minio#6501]
I am upload a simple 300kb to image to a default minio server through my nodejs app.

The nodejs app and minio are on the same server, and I am using this code:

```
              app.minioClient.putObject(
                "avatars",
                md5_email + "_512.png",
                outputBuffer,
                metaData,
                function(err, etag) {
                  if (err) {
                    return cb(err);
                  }
                  console.log("512x512 file upload", new Date() - start);
                  return cb();
                }
              );
```

The `outputBuffer` contain my image and it weights around 384069 bytes (so 300kb). The code logs:

`512x512 file upload 5651`

So for a 300kb file it takes more than 5 seconds. What kind of bottleneck could be? Is it normal?

**Comment by kannappanr** [comment]
@ciaoben Thanks for reaching out to us. We will get back to you with more information on the setup/ repro info.

**Comment by kanagarajkm** [comment]
@ciaoben Can you provide more information about the setup like, type(distributed), ssl, minio version etc.

**Comment by saviodsouza** [comment]
Hello

I am having similar problems with the latest minio server  on a Ubuntu server and rclone 1.46.

File transfer is close to half of the smb speed even with --s3-cutoff 1G option.

Also can I request if you can tell if  minio has any forms. It would be the best place to put such questions.

**Comment by harshavardhana** [comment]
Join us on https://slack.min.io @saviodsouza

**Comment by AlexNk** [comment]
Same problem with the default configuration, minio version 2019-03-06T22:47:10Z and Boto3 client library. But only when upload a file into a subdirectory. Flat file structure works fast.

Update: It appears that the problem in my case was in the incorrect or incorrectly used client library. Please ignore my comment.

**Comment by saviodsouza** [comment]
What do you mean by flat file structure

**Comment by AlexNk** [comment]
`
client.put_object(Body=b'...', Bucket=bucket_name, Key="file_00001") # these
client.put_object(Body=b'...', Bucket=bucket_name, Key="file_00002") # are 
client.put_object(Body=b'...', Bucket=bucket_name, Key="dir_00003/") # fast
client.put_object(Body=b'...', Bucket=bucket_name, Key="dir_00003/file_0004") # - this is slow
`

**Comment by nitisht** [comment]
Closing this due to no response from OP

**Comment by NeccoNeko** [comment]
I am having a similar problem.

I'm using S3FS-FUSE (s3fs-fuse-1.85-1.el7.x86_64) to access an S3 share running on FreeNAS-11.2-U5 which uses the following version of Minio:

    # /usr/local/bin/minio version
    Version: 2018-04-04T05:20:54Z
    Release-Tag: RELEASE.2018-04-04T05-20-54Z
    Commit-ID: 85a57d20210eb867b1c023e024cc4391d5ac5685

I'm attempting to write millions of 3KB files (as part of a test) using a structure as follows:

    ##/##/##/{uuid}-{aaa..zzz}

For example:

    10/20/30/bdfd79c0-7ffa-4f6e-9a08-f6d6811a1c92-fak

I'm getting an average write speed of ~175KB/sec (~58 files per second).  If I write directly to disk using the same script I get ~40MB/sec (~13k files per second).

I've tried writing to the base path of the bucket and get a similar speed (~180KB/sec)

Is this the kind of performance I should expect with S3FS+Minio?

The script I'm using to generate the data:

```
#!/bin/bash
## Functions
function rand_num {
  shuf -i 0-99 -n 1 | sed 's/^.$/0&/'
}

## Execute
count=0
while [[ ${count} -lt 1000 ]]
do
  count=$(( ${count} + 1 ))
  path=$(rand_num)/$(rand_num)/$(rand_num)
  mkdir -p ${path}
  dd if=<(openssl enc -aes-256-ctr \
                  -pass pass:"$(dd if=/dev/urandom bs=128 count=1 </dev/null | base64)" \
                  -nosalt </dev/zero) 
    bs=2k count=5000 | \
    pv --progress --eta --rate --bytes | \
    split -a 3 -b 3k - ${path}/$(uuidgen)-
done
```

**Comment by harshavardhana** [comment]
s3fs is not something we encourage or recommend. We don't do any performance measurements with s3fs 

Also please avoid positing on older closed issues @NeccoNeko please open a new one.

**Comment by harshavardhana** [comment]
We
