### ISSUE TITLE
Avoid copying or mirroring a folder to itself

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#6519]
## Expected Behavior

mc mirror or cp shouldn't allow copying a folder to itself.

## Current Behavior

Let's suppose we have this structure in a given bucket:

```
$ mc ls -r myminio/testbucket/
[2018-09-25 19:28:17 CET]     8B dir/object
[2018-09-25 19:28:40 CET]     8B object
```

If we do a recursive copy of myminio/testbucket/, you can notice that 'myminio/testbucket/dir/object' is being copied and overwritten at the same time, which creates complicates things

```
$ mc -q cp -r myminio/testbucket/ myminio/testbucket/dir/
`myminio/testbucket/dir/object` -> `myminio/testbucket/dir/dir/object`
`myminio/testbucket/object` -> `myminio/testbucket/dir/object`
Total: 16 B, Transferred: 16 B, Speed: 485 B/s
```

This is especially problematic when copying a large object using copy object part, we will definitely encounter errors indicating that ETag has been changed so copying is aborting.

## Possible Solution
Just compare source & target path

## Steps to Reproduce (for bugs)
NA

## Regression
No

## Your Environment
All

**Comment by harshavardhana** [comment]
@vadmeste first `mc` shouldn't allow this

**Comment by vadmeste** [comment]
> @vadmeste first `mc` shouldn't allow this

Yes I confirm, I update the description

**Comment by harshavardhana** [comment]
Then should this be open on minio/mc instead ?

**Comment by vadmeste** [comment]
> Then should this be open on minio/mc instead ?

Oups, right
