### ISSUE TITLE
minio some node return 403

### ISSUE THREAD

**Issue by anan-lee** [minio/minio#6534]
## Expected Behavior
work better

## Current Behavior
there is a clusters of 4 nodes ，but sometime will return 403 from http response， http header like this:
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2018-09-25T21-34-43Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 1558352F1FFDC4D8
X-Xss-Protection: 1; mode=block
Date: Thu, 27 Sep 2018 08:42:29 GMT

minio error log:
Error: volume not found
       disk=http://ipaddress:9090/app/minio
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:309:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:341:cmd.readAllXLMetadata.func1()

minion start command:
MINIO_ACCESS_KEY=1 MINIO_SECRET_KEY=2 minio server --address ip:9090 http://ip1:9090/app/minio http://ip2:9090/app/minio http://ip3:9090/app/minio http://ip4:9090/app/minio

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
Version: 2018-09-25T21:34:43Z
Release-Tag: RELEASE.2018-09-25T21-34-43Z
Commit-ID: aa4e2b1542b98097e08680f21b790de0b776378c

* Environment name and version (e.g. nginx 1.9.1):

* Server type and version:
Ubuntu 16.04.3 LTS
* Operating System and version (`uname -a`): 
Linux hostname 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
> there is a clusters of 4 nodes ，but sometime will return 403 from http response， http header like this:
> HTTP/1.1 403 Forbidden
> Accept-Ranges: bytes
> Content-Security-Policy: block-all-mixed-content
> Server: Minio/RELEASE.2018-09-25T21-34-43Z (linux; amd64)
> Vary: Origin
> X-Amz-Request-Id: 1558352F1FFDC4D8
> X-Xss-Protection: 1; mode=block
> Date: Thu, 27 Sep 2018 08:42:29 GMT
> 
> minio error log:
> Error: volume not found
> disk=http://ipaddress:9090/app/minio
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:309:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:341:cmd.readAllXLMetadata.func1()
> 
> minion start command:
> MINIO_ACCESS_KEY=1 MINIO_SECRET_KEY=2 minio server --address ip:9090 http://ip1:9090/app/minio http://ip2:9090/app/minio http://ip3:9090/app/minio http://ip4:9090/app/minio

what is the application being used here? @anan-lee

**Comment by anan-lee** [comment]
> what is the application being used here

the bucket is public. and download from browser \wget or curl

**Comment by harshavardhana** [comment]
> the bucket is public. and download from browser \wget or curl

How is the bucket public @anan-lee do you have the policy that you set?

**Comment by anan-lee** [comment]
> > the bucket is public. and download from browser \wget or curl
> 
> How is the bucket public @anan-lee do you have the policy that you set?

Yes, i set the policy * to read-only.

For the same key, The 403 response is from part of the node from the cluster.   and the other node works well.

**Comment by harshavardhana** [comment]
> Yes, i set the policy * to read-only.
> 
> For the same key, The 403 response is from part of the node from the cluster. and the other node works well.

Is this a particular node? have you tried restarting the server on that node?

**Comment by anan-lee** [comment]
> Is this a particular node

**Comment by anan-lee** [comment]
> > Yes, i set the policy * to read-only.
> > For the same key, The 403 response is from part of the node from the cluster. and the other node works well.
> 
> Is this a particular node? have you tried restarting the server on that node?

I am not sure this node it is particular. it's still not work after restarting the bad one. 
![image](https://user-images.githubusercontent.com/7876453/46243368-14a4e980-c406-11e8-81b6-d7d6ca218e08.png)

how to repair this?

**Comment by harshavardhana** [comment]
This is weird @anan-lee can you do `mc policy list` and paste the output from the `.3:9090` server?

**Comment by anan-lee** [comment]
> This is weird @anan-lee can you do `mc policy list` and paste the output from the `.3:9090` server?

mc policy list output:

file/* => readonly

Yesterday I rejoined this node to the cluster and it looks normal now.

**Comment by anan-lee** [comment]
> This is weird @anan-lee can you do `mc policy list` and paste the output from the `.3:9090` server?

i will close this issue. thanks for your reply
