### ISSUE TITLE
Minio using Azure Blob Storage Crashes after more than 1GB it's uploaded

### ISSUE THREAD

**Issue by jonhatanr** [minio/minio#6542]
Hi folks, 

I'm using Kubernetes in Azure AKS running a deployment with latest version of Minio
it connects fine, I'm able to login and no problem ... but when I'm trying to upload files which size is more than 1GB that container gets killed and I'm not able to see any kind of logs. 

After that, I thought it was an issue with Nginx ingress and I created and expose a service to access directly to Minio, instead via Nginx. 
I tried to upload same file and got that same error.

After that, just to be sure, I launched a Docker container with same version (latest one) in my local, export port 9000 and do the same that I mentioned above. 
And same happened. 

As mentioned, I can't get any kind of log and don't know why that container gets killed after almost upload that file. 

## Expected Behavior

Upload more than 1GB files 

## Current Behavior

It crashes after try to upload files more than 1GB

## Steps to Reproduce (for bugs)

1. Locally run minio latest docker image and with `gateway azure` CMD 
```
docker run -tid -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=nameOfyourBlob" \
 -e "MINIO_SECRET_KEY=KEYOFYOURBLOB" \
 -e "MINIO_HTTP_TRACE=/tmp/minio.log" \
  -v ~/data:/data \
 -v ~/data/config:/root/.minio minio/minio gateway azure
```
2. Go to http://127.0.0.1:9000
3. Put your Azure Blob Storage credentials in there
4. Create a bucket
5. Upload a file with more that 1GB size within that bucket 

## Context

AKS Kubernetes
Locally Mac OS X Mojave

## Your Environment

* Version used: Latest docker image
* Environment name and version: No Nginx

**Comment by harshavardhana** [comment]
Does the crash mean server dies is there a stack trace ?

**Comment by jonhatanr** [comment]
@harshavardhana there's no stack trace, I can recreate steps again to double check, but when I tried it did't log anything and not stack trace. 
And yes, that means the server dies cause container gets killed after upload more than 1GB.

**Comment by harshavardhana** [comment]
Just uploaded successfully a 2GiB upload with `minio gateway azure`, 

```
mc cp bigfile myazure/testb/
bigfile:                        1.98 GB / 1.98 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 2.11 MB/s 15m57s
```

So I am assuming something else is going wrong here? 

NOTE: I am using the latest release version

**Comment by jonhatanr** [comment]
@harshavardhana it only fails using Minio UI directly, using Minio client command (mc) it could upload more than 1GB without problem, actually I have done tests with 2GB and it uploads properly. 
But sadly as I mentioned, it only fails using Minio UI. 

Look at this screenshare:
https://drive.google.com/file/d/10M40k0Jaq0OGHSEfCN4u9mv_o4-UvtLT/view?usp=sharing
In that example, I choose a 2GB file. 

Using MC its fine, i got this:
`mc cp data/minio_2gb.tar.gz myazure/test/minio_2gb.tar.gz`
data/minio_2gb.tar.gz:    2.00 GB / 2.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 7.15 MB/s 4m46s

**Comment by harshavardhana** [comment]
yes, now I know the problem @yonhat7n the problem is Azure doesn't support uploading > 256MiB in a single stream, also 1GiB would be buffered by Azure SDK which might have lead to the crash. 

This is the current limitation since Minio UI doesn't use multipart API which is more optimized. I am making some local changes to allow an optimized version.

**Comment by harshavardhana** [comment]
Submitted a PR to fix this issue @yonhat7n

**Comment by jonhatanr** [comment]
@harshavardhana GREAT ! appreciated a lot, anxious to get it in Minio latest verson. 
Thanks for your time to attend this.
