### ISSUE TITLE
Can you limit the overall upper limit of storage?

### ISSUE THREAD

**Issue by mclitao** [minio/minio#6543]
How do you limit the amount of online storage a tenant can store?
For example, the total content cannot exceed 50BG?

**Comment by harshavardhana** [comment]
No it is not possible we need to implement quota support for this. This is something we want to do in future but it's not priority at the moment.

Feel free to close this issue. For general questions like these please join us on slack https://slack.minio.io for more quiker realtime response.

**Comment by mclitao** [comment]
Thank you very much .
