### ISSUE TITLE
How to make a permanent link or a link longer than 7 days

### ISSUE THREAD

**Issue by mclitao** [minio/minio#6547]
How to make a permanent link or a link longer than 7 days
What do you do when you need to make some permanent links in practice?

**Comment by nitisht** [comment]
@mclitao S3 API allows presigned URL validity upto 7 days only, ref: 
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

Accordingly Minio behaves the same way. One way to make permanent URLs is to use bucket policy. ref: 
https://docs.minio.io/docs/minio-client-complete-guide.html#policy

**Comment by mclitao** [comment]
Thank you

**Comment by coderLinJ5945** [comment]
I would like to ask you how to configure the bucket policy to generate permanently valid urls?Can you give me a demo? Thank you

**Comment by kannappanr** [comment]
@coderLinJ5945 As described in the docs

```mc policy download play/mybucket```

You can download objects within the bucket directly.  For e.g, an object named `issue` using the link

`https://play.minio.io:9000/mybucket/issue`

**Comment by coderLinJ5945** [comment]
Could you please tell me why the uploaded object cannot be downloaded directly from the bucket?Will be intercepted login page, http://111.22.15.73:5012/minio/asiatrip/date.png my address file

**Comment by nitisht** [comment]
can you try http://111.22.15.73:5012/asiatrip/date.png

**Comment by coderLinJ5945** [comment]
I'm sorry ,my URL is wrong, but I did the operation as shown in the figure. The new url: http://111.22.15.73:5012/asiatrip/date.png, but I still can't download it.[图片]

**Comment by coderLinJ5945** [comment]
/ # mc policy play/asiatrip
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
Access permission for `play/asiatrip` is `download`
/ # 
Message from syslogd@bogon at Jan 24 17:12:41 ...
 kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
mc policy download play/asiatrip
Access permission for `play/asiatrip` is set to `download`

**Comment by kannappanr** [comment]
@coderLinJ5945 Can you print the output of `mc policy myalias/asiatrip` where `myalias` is the alias to connect to `http://111.22.15.73:5012`

**Comment by coderLinJ5945** [comment]
Is this because my bucket is not an anonymous bucket?

**Comment by kannappanr** [comment]
Yes. You will have to do `mc policy download mylias/asiatrip` where `myalias` is the alias to connect to `http://111.22.15.73:5012`

**Comment by kannappanr** [comment]
Please look at `https://docs.minio.io/docs/minio-client-complete-guide.html#policy` for more information on how to set anonymous access

**Comment by coderLinJ5945** [comment]
I have tried the command you gave me. I have tried both inside and outside the net and reported the following error

**Comment by coderLinJ5945** [comment]
/ # mc policy http://111.22.15.73:5012/asiatrip
mc: <ERROR> Unable to get policy for `http://111.22.15.73:5012/asiatrip`. Use `mc config host add mycloud http://111.22.15.73:5012/asiatrip ...` to add an alias. Use the alias for S3 operations.
/ # mc policy http://172.17.2.122:7480/asiatrip
mc: <ERROR> Unable to get policy for `http://172.17.2.122:7480/asiatrip`. Use `mc config host add mycloud http://172.17.2.122:7480/asiatrip ...` to add an alias. Use the alias for S3 operations.

**Comment by kannappanr** [comment]
before you run `mc policy myalias/asiatrip`, please enter `mc config host add myalias http://111.22.15.73:5012 YOUR_ACCESS_KEY YOUR_SECRET_KEY` Please enter the appropriate values for `YOUR_ACCESS_KEY` and `YOUR_SECRET_KEY`

**Comment by coderLinJ5945** [comment]
/ # mc policy download play/http://111.22.15.73:9000/minio/asiatrip
mc: <ERROR> Unable to set policy `download` for `play/http://111.22.15.73:9000/minio/asiatrip`. All access to this bucket has been disabled.

**Comment by coderLinJ5945** [comment]
/ # mc policy download play/http://111.22.15.73:9000/asiatrip
Access permission for `play/http://111.22.15.73:9000/asiatrip` is set to `download`

**Comment by coderLinJ5945** [comment]
The execution of the order got stuck
：mc config host add myalias http://111.22.15.73:9000 minio minio123456   And there was no mistake.

**Comment by coderLinJ5945** [comment]
/ # mc config host add myalias http://172.17.2.122:9000 minio minio123456
Added `myalias` successfully.

**Comment by coderLinJ5945** [comment]
How do I set the bucket to be anonymous? I follow the document settings: / # mc policy download play/asiatrip
Access permission for `play/asiatrip` is set to `download`  Setup succeeded .But my access will still be blocked to the login page. http://172.17.2.122:9000/asiatrip/date.png

**Comment by coderLinJ5945** [comment]
My thoughts are a bit confused. Let me sort them out first. Thanks very much

**Comment by mickaelmonsieur** [comment]
the correct command is:

```
 mc policy set download myminio/test
```
