### ISSUE TITLE
Package problems while cross-compiling

### ISSUE THREAD

**Issue by adrienyhuel** [minio/minio#6551]
Result package is not correct when I cross-compile for ARM on AMD64

## Expected Behavior
Cross-compiling should work without problem

## Current Behavior
I cross-compile on CentOS7 64bit VM, wirth ARM target.
The minio binary for arm is built, but : 
- version is : DEVELOPMENT.GOGET
- package is not stripped

## Possible Solution
The problem is in the Makefile : LDFLAGS := $(shell go run buildscripts/gen-ldflags.go)
Here a go script is used to get build flags.
If GOARCH is set to arm, this script throw an error "exec format error" because it is run on AMD64 host.
Then flags aren't set, and binary result has no version, and not stripped.
I managed to make it working, with modifying Makefile : 
LDFLAGS := $(shell export GOARCH="$(GOHOSTARCH)"; go run buildscripts/gen-ldflags.go)

## Steps to Reproduce (for bugs)
1. VM CentOS 64bit
2. Install golang
3. export GOARCH=arm; go get -u github.com/minio/minio
4. Copy minion binary on ARM target
5. "minio version" -> Version: DEVELOPMENT.GOGET, Release-Tag: DEVELOPMENT.GOGET, Commit-ID: DEVELOPMENT.GOGET
6. "file minio" -> minio: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, **not stripped**

## Context
I try to build an up to date minio binary to execute on my NAS (ReadyNAS 100, ARM 32bits)
I can't use Docker on the NAS, there is lacks in kernel

## Regression
No

## Your Environment
CentOS 7 VM : 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ReadyNAS : Linux ReadyNAS104 4.4.140.armada.1 #1 SMP Tue Jul 17 15:55:57 UTC 2018 armv7l GNU/Linux

**Comment by harshavardhana** [comment]
> Then flags aren't set, and binary result has no version, and not stripped.

To cross-compile you simply set GOARCH and do source build, Makefile is meant for native compilation.

**Comment by adrienyhuel** [comment]
@harshavardhana you mean I just have to run "export GOARCH=arm; go get -u github.com/minio/minio" ?

And if I want to set a version, I have to manually add flags to command ?

**Comment by harshavardhana** [comment]
> @harshavardhana you mean I just have to run "export GOARCH=arm; go get -u github.com/minio/minio" ?

yes @youlJunior if you want to then you should use `go run buildscripts/gen-ldflags.go` to pass these as flags for `--ldlags` command line.

**Comment by adrienyhuel** [comment]
@harshavardhana thank you very much, here is how I dit it : 

go get -d -u github.com/minio/minio
ldflags=$(cd ~/go/src/github.com/minio/minio && go run buildscripts/gen-ldflags.go)
GOARCH=arm
go install --ldflags "$ldflags" github.com/minio/minio
GOARCH=amd64
