### ISSUE TITLE
no output during startup

### ISSUE THREAD

**Issue by schmurfy** [minio/minio#6554]
When starting the minio docker with invalid parameters minio does not output anything making it very hard to understand what the hell is happenning.
I got to debug that while at the same time setting up our new docker infrastructure and minio does not help much staying quiet on the side...

## Expected Behavior
Before anything else I expect something to be written on the console like "Minio starting up", anything but print something to tell me the process is running, after that in that case telling me the hostname could not be resolved would be appreciated.

## Current Behavior
minio server just sits there, printing nothing, doing nothing.

## Possible Solution
show an actual error, in that case minio2 to minio4 does not exists, pinging them returns a resolve error.

## Steps to Reproduce (for bugs)
I ran this on a rancher v2 host:
docker run --rm -it -p 9000:9000 --name minio1 minio/minio server http://minio{1...4}/data

## Context
I am trying to start a minio cluster.

## Regression
no idea

## Your Environment
* Version used (`minio version`): 2018-09-25T21:34:43Z
* Environment name and version (e.g. nginx 1.9.1): -
* Server type and version: -
* Operating System and version (`uname -a`): -
* Link to your project: -

**Comment by harshavardhana** [comment]
> When starting the minio docker with invalid parameters minio does not output anything making it very hard to understand what the hell is happenning.
> I got to debug that while at the same time setting up our new docker infrastructure and minio does not help much staying quiet on the side...

What are the invalid parameters? @schmurfy like this you mean?

```
minio server http://minio{1...4}/export
ERROR Invalid command line arguments: 'http://minio1/export': lookup minio1 on 1.1.1.1:53: no such host.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
```

**Comment by schmurfy** [comment]
Yes that what I would expect but that's not what I get, not sure why.
I get your error when I try to run locally but not on the docker host but the ping does return en error for minio2 to minio4.

What I called invalid parameters is just a wrong hostname due to the way rancher/kubernetes was configured

**Comment by nitisht** [comment]
@schmurfy looks like we already print the errors as expected, can you confirm if you found something that was preventing this from showing up in Rancher?

**Comment by schmurfy** [comment]
I have not found anything explaining the behavior, I just gave up for now but running the `docker run` command as I did above is not using rancher at all.

I just tested the same command on my macbook and I get the same result: no output at all.
Where did you test this and got something printed on the screen ?

**Comment by dustinaevans** [comment]
I can confirm this. If the etcd endpoints are specified in ENV and etcd is not running, starting minio server in FS mode will hang with no output and cannot be terminated by ^c.

Steps to reproduce:
export MINIO_ETCD_ENDPOINTS=http://1.1.1.1:2379

minio server --address :80 /tmp
<no output>
^C^C^C^C

**Comment by kannappanr** [comment]
@dustinaevans In your case, is `minio` running as  a binary or within a docker container?

**Comment by harshavardhana** [comment]
It shouldn't hang, it has a timeout. We wait for etcd to timeout with a canceller.

Also this issue not related to etcd, let's not piggyback on older issues @dustinaevans please open new issues.

**Comment by harshavardhana** [comment]
This issue is fixed with etcd timeouts closing.
