### ISSUE TITLE
Space used calculation is off

### ISSUE THREAD

**Issue by bootc** [minio/minio#6565]
## Expected Behavior
The `Used:` space in the Minio web interface should broadly match disk space used by Minio, or at least the space used in the filesystem that Minio uses.

## Current Behavior
In my specific configuration the disk space used does not reflect reality:

```
# df -h /tank/minio/
Filesystem      Size  Used Avail Use% Mounted on
tank/minio      5.0G  651M  4.4G  13% /tank/minio
# du -sh /tank/minio/
650M    /tank/minio/
```

The web interface, however, suggests "Used: 2.49 GB".

## Steps to Reproduce (for bugs)
Unsure about steps, sadly.

## Context
I'm using the bare `minio` binary in `gateway nas` mode on a ZFS filesystem. Minio has a dedicated 5GB ZFS dataset for its own use.

## Regression
Unknown. I'm a new user of Minio and this is the first version I've used.

## Your Environment
* Version used (`minio version`): RELEASE.2018-09-25T21-34-43Z
* Environment name and version (e.g. nginx 1.9.1): Apache 2.4.34-1
* Operating System and version (`uname -a`): Debian Buster (testing), Linux 4.18.6-1 (2018-09-06)

Also ZFS from Debian, 0.7.11-1.

See also https://minio.slack.com/archives/C3NDUB8UA/p1538654746000100.

**Comment by bootc** [comment]
I've now tried plain `server` mode rather than `gateway nas`; the space used calculation is the same (and still incorrect).

**Comment by kannappanr** [comment]
@bootc Thanks for filing this issue, we will try to reproduce this issue and get back to you with further questions.

**Comment by harshavardhana** [comment]
This is most probably how ZFS block size is managed can you use `df --block-size` to see the right value or `df -k` here? @bootc

**Comment by harshavardhana** [comment]
>  du -sh /tank/minio/ 650M /tank/minio/

can you also do `du -sh --apparent-size`

**Comment by bootc** [comment]
Huh. Well I'll be. Today my Minio is saying `Used: 2.28 GB` and indeed:
```
# du -sh --apparent-size /tank/minio/
2.2G    /tank/minio/
```

Also:
```
# df -k /tank/minio/
Filesystem     1K-blocks   Used Available Use% Mounted on
tank/minio       5242880 604928   4637952  12% /tank/minio
```

df's `--block-size` requires an argument so isn't much help I don't think.

And now we've gone through this it makes sense to me. I have compression on my filesystems as it's effectively "free" with ZFS, and this bucket contains database dumps which are really compressible. It turns out I do have 2.2GB of data in here but ZFS's compression has worked uncharacteristically well on these dumps with a compression ratio of 4.10x.

```
zfs get logicalused,used,compressratio tank/minio 
NAME        PROPERTY       VALUE  SOURCE
tank/minio  logicalused    2.19G  -
tank/minio  used           591M   -
tank/minio  compressratio  4.10x  -
```

I should have checked that before, I'm sorry.

However this all came about because I had an issue with Minio refusing requests due to no space being available, so I had guessed it was because its size estimate was out; that may not quite be the case, but the filesystem was nowhere near full at the time.

I'll close this ticket now and investigate my original issue a little more before asking for help on that one.

**Comment by bootc** [comment]
I should add, thanks again for your help with this issue!

**Comment by harshavardhana** [comment]
> I should add, thanks again for your help with this issue!

No problem you are welcome, I want to throw this out there alternatively rather than using ZFS compression you can use Minio's own inline compression https://docs.minio.io/docs/minio-compression-guide.html
