### ISSUE TITLE
File backend does not handle equal filename/directory consistently

### ISSUE THREAD

**Issue by aead** [minio/minio#6566]
If you try to create non-zero objects of the following pattern:
1. `bucket/object-prefix`
2. `bucket/object-prefix/object`

the server returns unexpected and inconsistent errors. Further the server behaves differently than AWS. 

## Expected Behavior
Ideally the server should accept both objects - like AWS. At least the server should return a descriptive, custom error.

## Current Behavior
If you upload:
1. `bucket/object-prefix`
2. `bucket/object-prefix/object`
the server responds with `Access Denied`

If you upload:
1. `bucket/object-prefix/object`
2. `bucket/object-prefix`
the server responds with `Internal Error`

## Possible Solution

Not obvious, at least create a custom error. 

## Steps to Reproduce (for bugs)
```
s3Client, err := minio.New("play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
	if err != nil {
		log.Fatalln(err)
	}
	s3Client.SetCustomTransport(&http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}})
	//s3Client.TraceOn(nil)
	data := make([]byte, 1*1024*1024)
	bucketname := "bucket"
	objectName := "object"
	_, err = s3Client.PutObject(bucketname, objectName, bytes.NewReader(data), -1, minio.PutObjectOptions{})
	if err != nil {
		log.Fatalln(err)
	}

	_, err = s3Client.PutObject(bucketname, objectName+"/1", bytes.NewReader(data), -1, minio.PutObjectOptions{})
	if err != nil {
		log.Fatalln(err)
	}
```

## Context
S3 compatibility 

## Regression
no

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
> Ideally the server should accept both objects - like AWS. At least the server should return a descriptive, custom error.

We cannot support AWS style it is simply not possible on a POSIX like hierarchy unless we write of course is some form hashed translation but that would defeat the purpose of Minio to be simpler even to look at the backend. 

The error is inconsistent we should simply return Access Denied in both scenarios, we can make the error more descriptive if needed saying OverlappingPrefixes not allowed 

// cc @aead

**Comment by aead** [comment]
> We cannot support AWS style it is simply not possible on a POSIX like hierarchy unless we write of course is some form hashed translation but that would default the purpose of Minio to be simpler even to look at the backend.

Agree here. We've found this during gateway SSE-C encryption discussion. Gateway with AWS backend allows such object combinations while Gateway with Minio as backend would not allow such objects. Should we make the behavior here consistent or are such small behavioral differences expected (allow what the backend supports)?

 > The error is inconsistent we should simply return Access Denied in both scenarios, we can make the error more descriptive if needed saying OverlappingPrefixes not allowed

Yeah, let's make a custom API error since it's minio-specific behavior...

**Comment by harshavardhana** [comment]
> Agree here. We've found this during gateway SSE-C encryption discussion. Gateway with AWS backend allows such object combinations while Gateway with Minio as backend would not allow such objects. Should we make the behavior here consistent or are such small behavioral differences expected (allow what the backend supports)?
> 

We don't need to comply as it is never an expected scenario to work in the real world, there are no popular applications which actually need this to work.

> Yeah, let's make a custom API error since it's minio-specific behavior...

A custom error here is a better solution.
