### ISSUE TITLE
[Proposal] Enhance disk usage calculation

### ISSUE THREAD

**Issue by donatello** [minio/minio#6576]
Putting in a proposal that came out from discussion with @abperiasamy .

## Expected Behavior

Disk usage calculation should be more incremental - start with a full disk scan and then do it incrementally by accounting in PUT requests.

## Current Behavior

Disk is  scanned periodically to compute usage - this could be an issue on large systems.

## Context

A concern for large systems would be that disk usage computation would be a continuous load on the server, and that the frequency of the scan is arbitrarily set (one scan may take longer than a day, in which case, it will be continuously scanning?). It would be lighter to account from actual writes happening on the server.

**Comment by harshavardhana** [comment]
Assumption that it runs every 12hrs is not correct regardless of any existing thread.  

12hrs is the waiting time after the last successful run. Even if the total run takes more than 12 hrs there are no interleaving usage checks.

**Comment by nitisht** [comment]
based on the discussion the other day, I understand we're not going to take this approach. Okay to close this then? @donatello @harshavardhana

**Comment by harshavardhana** [comment]
Yes we need a different bug with new set of requirements.

**Comment by nitisht** [comment]
Closing this for now.
