### ISSUE TITLE
Bucket stats in minio server

### ISSUE THREAD

**Issue by rhlr** [minio/minio#6577]
Thank you for the awesome project. Is it possible to get bucket statistics like size,count (files and folders) of  a specific bucket ? I checked the python api, although we can get individual object size, it will be very slow to add all the object  size if the number of objects is fairly large. Is there any other way around this ?

**Comment by nitisht** [comment]
@rhlr you can do it with bucket notifications. You can configure notifications for a bucket and track incoming object size in an external target like a database. Ref this doc for more details: https://docs.minio.io/docs/minio-bucket-notification-guide.html

**Comment by nitisht** [comment]
@rhlr closing this as answered, please feel free to reachout to us on Slack : https://slack.minio.io for further questions.

**Comment by mikijov** [comment]
FYI, you can do something like this:
```bash
mc ls -r --json your_bucket_path | awk '{ FS=","; print $4 }' | awk '{ FS=":"; n+=$2 } END{ print n }'
```

**Comment by Nepoxx** [comment]
@mikijov your solution dooes not work for me for buckets with a single item:

```
$ mc ls -r --json myminio/mybucket
{
 "status": "success",
 "type": "file",
 "lastModified": "2019-05-30T09:43:07.763-04:00",
 "size": 44996289,
 "key": "myFile",
 "etag": "bae58dc18zzzzz54c14e233b520e0a"
}
$ mc ls -r --json myminio/mybucket | awk '{ FS=","; print $4 }'
(nothing printed)
$ mc ls -r --json myminio/mybucket | awk '{ FS=","; print $4 }' | awk '{ FS=":"; n+=$2 } END{ print n }'
0
```

---

Here's my alternative solution using [jq](https://stedolan.github.io/jq/)
```bash
mc ls -r --json myminio/mybucket | jq -s 'map(.size) | add'
```

**Comment by RobertHR** [comment]
How about if you have 65 mil objects

**Comment by harshavardhana** [comment]
65 mil objects are quite small for modern workloads @RobertHR  - anyways usage metrics is already merged in master which calculates bucket level usage

```
mc admin info play
●  play.minio.io
   Uptime: 2 hours 
   Version: 2019-12-17T18:21:39Z
   Network: 1/1 OK 
   Drives: 4/4 OK 

10 GiB Used, 374 Buckets, 71,212 Objects
4 drives online, 0 drives offline
```
