### ISSUE TITLE
SSE-S3 PutObject Etag incompatible with AWS S3

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#6580]
## Expected Behavior
AWS S3 behavior, returned ETag is same as the original object 
```
$  s3cmd put /etc/issue --server-side-encryption s3://vadmeste/obj
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s    45.89 B/s  done

$ mc cat s3/vadmeste/obj

mc: <DEBUG> GET /obj HTTP/1.1
Host: vadmeste.s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-10-01T22:37:50Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181007/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181007T080221Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 26
Accept-Ranges: bytes
Content-Type: text/plain
Date: Sun, 07 Oct 2018 08:02:22 GMT
Etag: "38103f9a76bb14e2abbc051b65722cff"
Last-Modified: Sun, 07 Oct 2018 08:01:58 GMT
Server: AmazonS3
X-Amz-Id-2: mok3b6vFSBPQkgXejiWF1eaT2ylgiAcU7130bzVDyQLeLW+mpdeuspOarxl9feMHWdZ4lmgdWGE=
X-Amz-Meta-S3cmd-Attrs: atime:1538875848/ctime:1534869850/gid:0/gname:root/md5:38103f9a76bb14e2abbc051b65722cff/mode:33188/mtime:1534772680/uid:0/uname:root
X-Amz-Request-Id: 36BA302681C145BF
X-Amz-Server-Side-Encryption: AES256
X-Amz-Version-Id: SiVT7t5L.T0KOpV4JPmSz5vJhTimqY0B

$ md5sum /etc/issue
38103f9a76bb14e2abbc051b65722cff  /etc/issue
```

## Current Behavior
Minio,  returned ETag is not same as the original object 
```
s3cmd put /etc/issue --server-side-encryption s3://vadmeste/obj
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s  1743.33 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   476.11 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   440.97 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   510.78 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   464.07 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Retrying upload of /etc/issue
upload: '/etc/issue' -> 's3://vadmeste/obj'  [1 of 1]
 26 of 26   100% in    0s   475.29 B/s  done
WARNING: MD5 Sums don't match!
WARNING: Too many failures. Giving up on '/etc/issue'
ERROR: Upload of '/etc/issue' failed too many times (Last reason: )

$ s3cmd put /etc/issue --server-side-encryption s3://vadmeste/obj --debug  2>&1 |grep MD5
INFO: Running stat() and reading/calculating MD5 values on 1 files, this may take some time...
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=b0669757fc3a19731794200ba9016146
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=ea882d6bcfc05a6605530de9729283a2
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=f84f9ad83fc07f86a3e33919a5ccf2db
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=c7e27b763e6bea7a03ac92b0c7a45934
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=3d473d1d09035128a6fd3a949d1c6d33
WARNING: MD5 Sums don't match!
DEBUG: MD5 sums: computed=38103f9a76bb14e2abbc051b65722cff, received=d000450838ff08cc82835bc473af8682
WARNING: MD5 Sums don't match!

$ mc cat myminio/vadmeste/obj
mc: <DEBUG> GET /vadmeste/obj HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-10-01T22:37:50Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20181007/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181007T080404Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 26
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: text/plain
Date: Sun, 07 Oct 2018 08:04:04 GMT
Etag: "d000450838ff08cc82835bc473af8682"
Last-Modified: Sun, 07 Oct 2018 08:03:42 GMT
Server: Minio/DEVELOPMENT.2018-10-07T08-00-14Z (linux; amd64)
Vary: Origin
X-Amz-Meta-S3cmd-Attrs: atime:1538875848/ctime:1534869850/gid:0/gname:root/md5:38103f9a76bb14e2abbc051b65722cff/mode:33188/mtime:1534772680/uid:0/uname:root
X-Amz-Request-Id: 155B44E42CF428FC
X-Amz-Server-Side-Encryption: AES256
X-Xss-Protection: 1; mode=block
```

## Possible Solution
No solution yet, this would require some implementation change. Current implementation treats SSE-S3 and SSE-KMS as same this is not true on AWS S3. Their behavior is different and should be implemented properly.

## Steps to Reproduce (for bugs)
Already explained in Expected and Current behavior. 

## Context
Compatibility and implementation issues with SSE

## Regression
No, implementation issue. 

## Your Environment
master branch with #6488, I don't think this PR has any effect this seems to be true with vault based implementation.

**Comment by harshavardhana** [comment]
Moving this as high priority since this feature is already out there and creates incompatible situations when using with aws-sdk-java, s3cmd and perhaps other SDKs as well.

**Comment by aead** [comment]
@harshavardhana - #6488 does not add SSE-KMS support. It only allows to specify SSE-S3 master keys as **alternative** to a KMS (like vault).

**Comment by harshavardhana** [comment]
This issue is not related to KMS also not related to #6488 PR - this is currently present in our releases and also in master.

**Comment by aead** [comment]
I see. Can you confirm that the returned etag is the MD5 of the object plaintext? If so, this is a security issue.

**Comment by harshavardhana** [comment]
> I see. Can you confirm that the returned etag is the MD5 of the object plaintext? If so, this is a security issue.

No in AWS S3 returned Etag is of the plain text in our case it's of the encrypted object. s3cmd or aws-sdk-java fails because it's not the Etag of the plain text in Minio.

**Comment by harshavardhana** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html here are the details

**ETag**

The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:
- Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.
- Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-C or SSE-KMS, have ETags that are not an MD5 digest of their object data.
- If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption.

**Comment by aead** [comment]
@poornas The solution to this is:
1. The etag of SSE-S3 PUT (not multipart) objects becomes MD5(object-data).
2. The etag of such objects **MUST NOT** be stored in the metadata directly but **MUST** be encrypted
3. Therefore we derive a separate key: `etag-key := HMAC(object-key, "SSE-S3", "etag")`
4. The etag stored on the backend becomes `etag := sio.Encrypt(etag-key, etag)`
5. On GET we decrypt it back.

EDIT: sorry, pressed ctrl+enter... (slack-method -.-)

**Comment by poornas** [comment]
> 
    The etag of SSE-S3 PUT (not multipart) objects becomes MD5(object-data).
    The etag of such objects MUST NOT be stored in the metadata directly.
Then what would the HEAD call return if Etag is not saved as metadata?

**Comment by harshavardhana** [comment]
> Then what would the HEAD call return if Etag is not saved as metadata?

It is saved but encrypted :-) @poornas
