### ISSUE TITLE
Error when running on Azure Container Instance

### ISSUE THREAD

**Issue by HowardEdidin** [minio/minio#6583]
## Expected Behavior

I am trying to run minio is a Azure Container Instance.

## Current Behavior

Failed to start container with id c664e73ec91e390729b54373651fed4bc6fdb176a4079e4a92a54b1d7a0d6826 with error: rpc error: code 2 desc failed to start container "c664e73ec91e390729b54373651fed4bc6fdb176a4079e4a92a54b1d7a0d6826": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"minio server start --quiet\\\\\\\": executable file not found in $PATH\\\"\\n\""}

![mi-o2](https://user-images.githubusercontent.com/19954905/46584292-4847cb00-ca27-11e8-8347-aac64d75f60a.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 
Properties:
![mi-o1](https://user-images.githubusercontent.com/19954905/46584234-56491c00-ca26-11e8-980e-c55413cc8b72.png)

Documentation: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-group

If you look at the mount path,  I create a file share for logs. Nothing shows up in the share.

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Azure Linuix Container instance 
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
> Failed to start container with id c664e73ec91e390729b54373651fed4bc6fdb176a4079e4a92a54b1d7a0d6826 with error: rpc error: code 2 desc failed to start container "c664e73ec91e390729b54373651fed4bc6fdb176a4079e4a92a54b1d7a0d6826": Error response from daemon: {"message":"invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"minio server start --quiet\\\": executable file not found in $PATH\"\n""}

Looks like your commands settings are wrong. There is no "minio server start" 

Here is the example I just tested successfully, follow the doc in creating your resource groups. 
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-yaml

```
$ az group create --name myResourceGroup --location eastus
{
  "id": "/subscriptions/93fa217a-83eb-4f86-99eb-bc3effe1f797/resourceGroups/myResourceGroup",
  "location": "eastus",
  "managedBy": null,
  "name": "myResourceGroup",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}
```

Create a yaml file 
```yaml
apiVersion: 2018-06-01
location: eastus
name: myContainerGroup
properties:
  containers:
  - name: minio-app
    properties:
      image: minio/minio:latest
      command:
        - "minio"
        - "server"
        - "/data"
      resources:
        requests:
          cpu: 1
          memoryInGb: 2 
      ports:
      - port: 9000
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: '9000'
tags: null
type: Microsoft.ContainerInstance/containerGroups
```

```
az container create --resource-group myResourceGroup --file /tmp/minio.yaml

{
  "id": "/subscriptions/93fa217a-83eb-4f86-99eb-bc3effe1f797/resourceGroups/myResourceGroup/providers/Microsoft.ContainerInstance/containerGroups/myContainerGroup",
  "identity": null,
  "kind": null,
  "location": "eastus",
  "managedBy": null,
  "name": "myContainerGroup",
  "plan": null,
  "properties": {
    "containers": [
      {
        "name": "minio-app",
        "properties": {
          "command": [
            "minio",
            "server",
            "/data"
          ],
          "environmentVariables": [],
          "image": "minio/minio:latest",
          "instanceView": {
            "currentState": {
              "detailStatus": "",
              "startTime": "2018-10-07T18:59:03Z",
              "state": "Running"
            },
            "events": [
              {
                "count": 1,
                "firstTimestamp": "2018-10-07T18:59:02Z",
                "lastTimestamp": "2018-10-07T18:59:02Z",
                "message": "pulling image \"minio/minio:latest\"",
                "name": "Pulling",
                "type": "Normal"
              },
              {
                "count": 1,
                "firstTimestamp": "2018-10-07T18:59:03Z",
                "lastTimestamp": "2018-10-07T18:59:03Z",
                "message": "Successfully pulled image \"minio/minio:latest\"",
                "name": "Pulled",
                "type": "Normal"
              },
              {
                "count": 1,
                "firstTimestamp": "2018-10-07T18:59:03Z",
                "lastTimestamp": "2018-10-07T18:59:03Z",
                "message": "Created container with id 2df41e01ea01a20bc389695868006715b7d5c193c06a8c065d0586f0a40aae4f",
                "name": "Created",
                "type": "Normal"
              },
              {
                "count": 1,
                "firstTimestamp": "2018-10-07T18:59:03Z",
                "lastTimestamp": "2018-10-07T18:59:03Z",
                "message": "Started container with id 2df41e01ea01a20bc389695868006715b7d5c193c06a8c065d0586f0a40aae4f",
                "name": "Started",
                "type": "Normal"
              }
            ],
            "restartCount": 0
          },
          "ports": [
            {
              "port": 9000
            }
          ],
          "resources": {
            "requests": {
              "cpu": 1.0,
              "memoryInGB": 2.0
            }
          }
        }
      }
    ],
    "instanceView": {
      "events": [],
      "state": "Running"
    },
    "ipAddress": {
      "ip": "40.87.89.78",
      "ports": [
        {
          "port": 9000,
          "protocol": "TCP"
        }
      ],
      "type": "Public"
    },
    "osType": "Linux",
    "provisioningState": "Succeeded"
  },
  "resourceGroup": "myResourceGroup",
  "sku": null,
  "tags": null,
  "type": "Microsoft.ContainerInstance/containerGroups"
}
```

```
az container logs --resource-group myResourceGroup --name myContainerGroup --container-name minio-app

Endpoint:  http://10.244.214.11:9000  http://127.0.0.1:9000
AccessKey: N6G2G7VH6NXPHNK7BUML 
SecretKey: aL7vfXzgaubfM/DwJUhveFj6YrCxYfNs1e5zoXmo 

Browser Access:
   http://10.244.214.11:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.244.214.11:9000 N6G2G7VH6NXPHNK7BUML aL7vfXzgaubfM/DwJUhveFj6YrCxYfNs1e5zoXmo

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

**Comment by HowardEdidin** [comment]
Thanks for the quick response.  I was deploying with the Resource template https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups

**Comment by HowardEdidin** [comment]
Can the data folder be mapped to Azure File Storage?  

Also, I am getting the following error when trying to connect by 

rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n"

![image](https://user-images.githubusercontent.com/19954905/46636269-09943c80-cb1d-11e8-8bce-2f676b4367cf.png)

Connection closed. Press Enter to reconnect.
