### ISSUE TITLE
`make` fails with "... recipe for target 'gomake-all' failed"

### ISSUE THREAD

**Issue by krisis** [minio/minio#659]
Tested on commit - cdeadae
Tested on machine -  'Linux trantor 4.0.5-1-ARCH #1 SMP PREEMPT'
## Golang environment

Golang version - go version go1.4.2 linux/amd64
GOROOT=/home/user/go
GOPATH=/home/user/work/go
MINIO_BASE=/home/user/work/go/src/github.com/minio/minio
## Sample backtrace

---

PANIC: api_test.go:957: MySuite.TestXMLNameNotInObjectListJson

... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x470435)

/usr/local/go/src/runtime/panic.go:387
  in gopanic
/usr/local/go/src/runtime/panic.go:42
  in panicmem
/usr/local/go/src/runtime/sigpanic_unix.go:26
  in sigpanic
/home/kp/work/go/src/github.com/minio/minio/pkg/storage/drivers/donut/donut.go:161
  in donutDriver.CreateBucket
<autogenerated>:2
  in donutDriver.CreateBucket
api_test.go:971
  in MySuite.TestXMLNameNotInObjectListJson
/usr/local/go/src/reflect/value.go:296
  in Value.Call
/home/kp/work/go/src/github.com/minio/minio/Godeps/_workspace/src/github.com/minio/check/check.go:763
  in func.003
/home/kp/work/go/src/github.com/minio/minio/Godeps/_workspace/src/github.com/minio/check/check.go:657
  in func.001
/usr/local/go/src/runtime/asm_amd64.s:2232
  in goexit
2015/06/20 11:48:40 Running API Suite: *filesystem.fsDriver
OOPS: 95 passed, 5 FAILED, 12 PANICKED
--- FAIL: Test (1.87s)

**Comment by harshavardhana** [comment]
Thanks @krisis

**Comment by harshavardhana** [comment]
@krisis - i fixed the actual check that was needed inside the code, but i am going to make one more change to Makefile to handle this properly. 

Let us know if you were able to get it fixed by fixing the GOROOT ..

**Comment by krisis** [comment]
@harshavardhana, I will try fixing it via gopath before pulling in your fix
in code/Makefile, whenever that's merged, and update the issue.  I won't be
trying it before Monday though.

**Comment by harshavardhana** [comment]
> @harshavardhana, I will try fixing it via gopath before pulling in your fix

No problem what i would personally suggest is we cleanup the entire environment and start fresh, perhaps following - https://github.com/minio/minio/blob/master/INSTALLGO.md , to avoid installing in /usr/local/go

Lets talk on monday and start a reverse ssh session.

**Comment by krisis** [comment]
`make` works on fbee8f8. Thanks for fixing this.

**Comment by harshavardhana** [comment]
> make works on fbee8f8. Thanks for fixing this.

Your welcome! @krisis
