### ISSUE TITLE
xl: Empty directory found although it is not an empty object with trailing slash

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#6591]
## Expected Behavior
User is not supposed to see an empty directory if he didn't create it

## Current Behavior
User can see an empty directory that he didn't create it

## Possible Solution
A PR ready for that

## Steps to Reproduce (for bugs)
1. Start Minio in local erasure mode, 12 disks with parity set to 4
2. Create a bucket, upload a single file under any directory
3. Remove that file in 5 disks, list the directory using mc, it should be empty

## Context
Sometimes when data become inconsistent between disks, a user can see empty folders although he didn't create them.

## Regression
No

## Your Environment
All

**Comment by kannappanr** [comment]
Here is what was discussed on what needs to be done

1. Object without read quorum will be displayed with a `.CORRUPTED` extension
2. User should be able to delete this object using the `RemoveObject` API
3. There should be a best effort to be able to download a partial object.

**Comment by harshavardhana** [comment]
There is a complete PR available here #6670

**Comment by harshavardhana** [comment]
This is fixed already in master closing.
