### ISSUE TITLE
Error when trying to connect by Bash 

### ISSUE THREAD

**Issue by HowardEdidin** [minio/minio#6595]
I am gettng an error when trying to connect to the container instance. 

![image](https://user-images.githubusercontent.com/19954905/46636416-8e7f5600-cb1d-11e8-91f5-f014e6671899.png)

![image](https://user-images.githubusercontent.com/19954905/46636353-5841d680-cb1d-11e8-9044-6645fc2eac64.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Our container doesn't have /bin/bash, we only have /bin/sh - we are using Alpine Linux @HowardEdidin

**Comment by deekoder** [comment]
@HowardEdidin let us know if any further questions. I will go ahead and close this.
