### ISSUE TITLE
Restarting distributed minio stack in Docker Swarm may fail

### ISSUE THREAD

**Issue by tallandtree** [minio/minio#6606]
I've deployed a distributed minio stack of 4 minio's on 2 nodes in a docker swarm. I've used the example docker-compose.yml (https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-swarm/docker-compose-secrets.yaml), but added "hostname" for each minio servers, as this was needed for Docker 18.06. Else the services cannot resolve each other.

Issue: I cannot restart the minio stack always successfully. 

## Expected Behavior
The minio stack can always be restarted successfully.

## Current Behavior
If I start the minio stack for the first time, it runs ok. If I restart the stack (either through the minio client (mc admin service restart myminiostack) or via Docker, sometimes it starts successfully, sometimes it fails. If they fail to start successfully, the minio services are all waiting for all servers to get online. Finally, they are restarted again. 

The cause: the docker minio services are not running on exactly the same node as before, and a new docker volume is created during the restart which is not in sync with the other already existing volumes. If I remove the minio stack and remove all the minio volumes on all the nodes (which must be done manually on both docker nodes), I can successfully deploy the stack again. 

## Possible Solution
Add a node constraint to services in the docker-compose.yml [docker-compose.yml.txt](https://github.com/minio/minio/files/2465509/docker-compose.yml.txt), to make sure that the services are always started on the same node and add the required labels to the docker nodes.
```
docker node update --label-add minio1=true docker-node1
docker node update --label-add minio2=true docker-node1
docker node update --label-add minio3=true docker-node2
docker node update --label-add minio4=true docker-node2
```

## Steps to Reproduce (for bugs)
1. Setup docker swarm with 2 nodes
2. Deploy distributed minio stack according to documentation
3. Create at least one file or folder in the bucket
4. Restart the minio stack through the minio client: mc admin service restart myminiostack (or use docker to restart the stack). Note, you might have to restart a few times. Sometimes the minio services are started on exactly the same node. Sometimes they are started on the other node.

## Context
I'm using the distributed minio stack for gitlab runner cache. Sometimes the stack needs to be restarted.
My solution seems to work. Other solution is always to remove all volumes. But as "docker stack rm" currently does not have an option to remove all volumes in the stack, this needs to be done manually.

## Regression
No/not sure.

## Your Environment
* Version used (`minio version`): minio/minio:RELEASE.2018-10-06T00-15-16Z
* Environment name and version (e.g. nginx 1.9.1): Docker 18.06.1-ce
* Server type and version: same behavior on ESX VMWare and Oracle VirtualBox
* Operating System and version (`uname -a`): 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project: -

**Comment by kannappanr** [comment]
@tallandtree Thanks for filing this issue. We will try to reproduce this issue and get back to you if we need more information.

**Comment by harshavardhana** [comment]
> Add a node constraint to services in the docker-compose.yml [docker-compose.yml.txt](https://github.com/minio/minio/files/2465509/docker-compose.yml.txt), to make sure that the services are always started on the same node and add the required labels to the docker nodes.
> 
> ```
> docker node update --label-add minio1=true docker-node1
> docker node update --label-add minio2=true docker-node1
> docker node update --label-add minio3=true docker-node2
> docker node update --label-add minio4=true docker-node2
> ```

@tallandtree would you mind sending a fix for docker-compose.yml to run on the same nodes?

**Comment by tallandtree** [comment]
I attached the docker-compose.yml.txt to my issue description above. Can you not open it?

**Comment by harshavardhana** [comment]
> I attached the docker-compose.yml.txt to my issue description above. Can you not open it?

Of course, I can, feel free to send a PR is what I meant.
