### ISSUE TITLE
multi user

### ISSUE THREAD

**Issue by atomotic** [minio/minio#6607]
i see that https://github.com/minio/minio/pull/6168 has been merged, thanks!
i'm following [multi-user/README.md](https://github.com/minio/minio/blob/master/docs/multi-user/README.md), but is not clear to me if minio client has been updated (i've just reinstalled both server and client with go get)

```
mc admin users
mc: <ERROR> `users` is not a mc command. See `mc --help`.
```

**Comment by harshavardhana** [comment]
It's not updated yet. There is a pending PR https://github.com/minio/mc/pull/2554 closing this issue as it's not valid at the moment.

**Comment by andrewnet** [comment]
Hi, is this feature available now? can we use it?

**Comment by harshavardhana** [comment]
> Hi, is this feature available now? can we use it?

yes its done @andrewnet https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html

**Comment by Kiina** [comment]
Just for clarification. Using mc is currently the only way to do this? Will there be a user interface in the future?

**Comment by harshavardhana** [comment]
For now it's just mc - there are no current plans to do UI
