### ISSUE TITLE
Error: tls: no cipher suite supported by both client and server

### ISSUE THREAD

**Issue by alrf** [minio/minio#6611]
I use dockerized Minio https configuration with self-signed certificates. It should work as backend only, so self-signed certificates are ok here. 
I see a lot of error messages in Minio log (by `docker logs minio`):
`Error: tls: no cipher suite supported by both client and server`

Frontend is Amazon Load Balancer (ALB) - https with trusted certificates for my domain.
I can't access to Minio through ALB, i.e. by `https://MY_DOMAIN_LB:9000` (timeout error).
Minio is accessible by IP only, i.e.: `https://MINIO_SERVICE_IP:9000` (but not through domain name and ALB).

All necessary ports (on firewall) are opened. I have a few other services in the same configuration (https, ALB, docker) on that server. Everything ok, exclude Minio. So, it can't be a network/firewall/ports issue.

## Your Environment

* Version used (`minio version`): RELEASE.2018-07-23T18-34-49Z, RELEASE.2018-10-06T00-15-16Z
* Environment name and version: Amazon Load Balancer
* Operating System and version: CentOS 7.4

**Comment by nitisht** [comment]
Thanks for the issue @alrf we'll take a look soon.

**Comment by aead** [comment]
@alrf Which S3 client are you using to access Minio and which public key type is used by your self-signed certificate. Can you also post the TLS configuration of you S3 client, if any? You should see this error if the client and the server cannot agree on a certain cipher suite during TLS handshake. Probably your client does not support any of the following ciphers:
```
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
```

**Comment by alrf** [comment]
@aead I can't access to Minio through Amazon Load Balancer (ALB), i.e. by https://MY_DOMAIN_LB:9000 (timeout error). I see `Error: tls: no cipher suite supported by both client and server` errors during ALB trying to connect to Minio service.
I tried to use ECDSA and RSA self-signed keys: 
https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls

ALB doesn't support
```
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
```
but supports
```
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
```
in default configuration.
Screenshots below:

<img width="592" alt="screenshot_13" src="https://user-images.githubusercontent.com/2919751/46802898-cbdb2200-cd6f-11e8-8c82-1940b9ff50d3.png">

<img width="610" alt="screenshot_6" src="https://user-images.githubusercontent.com/2919751/46802823-920a1b80-cd6f-11e8-87ba-206f8ef37ca7.png">

**Comment by aead** [comment]
@alrf Okay, thank you. So it seems like the ABL supports the at least one required cipher suite as well as TLS1.2. I've looked into Go's standard lib TLS cipher negotiation code... Can you intercept the network traffic between ABL and Minio (e.g. using wireshark) to confirm that ABL really sends the correct protocol version / ciphers / elliptic curves / .... See: https://golang.org/src/crypto/tls/handshake_server.go#L726

**Comment by alrf** [comment]
@aead I analyzed the traffic and I see handshake between ALB and Minio is broken.
ALB sends to Minio only these types of ciphers:
```
Cipher Suites (29 suites)
    Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
    Cipher Suite: TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (0x0084)
    Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
    Cipher Suite: TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (0x0041)
    Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
    Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 (0x00a3)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x006b)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x006a)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x0038)
    Cipher Suite: TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (0x0088)
    Cipher Suite: TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA (0x0087)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 (0x00a2)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x0067)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x0040)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x0032)
    Cipher Suite: TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (0x0045)
    Cipher Suite: TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA (0x0044)
    Cipher Suite: TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (0x0016)
    Cipher Suite: TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x0013)
    Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
```
However it doesn't support by Minio..
This is pre-defined list of ciphers and it can not be changed on ALB.
I asked about it Amazon support and they confirmed it.
So, cipher settings from screenshots above apply to Internet and ALB connections only (but not between ALB and services).

**Comment by aead** [comment]
@alrf This is indeed a problem. Unfortunately we cannot enable any cipher using diffie-hellman key exchange (`DHE`) because the Go TLS library only supports DH based on elliptic curves. Further we cannot enable legacy RSA based ciphers because they do not provide PFS (perfect forward secrecy).

You could run a reverse proxy - like nginx - in-front of Minio which handles the legacy TLS connection.
Additionally you can ask the Amazon support to upgrade their internal ALB TLS configuration. I will also ask internally whether we may introduce a TLS configuration option for such situations but I don't think it's very likely that such a proposal gets accepted...

**Comment by alrf** [comment]
@aead yes, thank you for advice and let's see maybe we can fix it somehow later.

**Comment by harshavardhana** [comment]
> @alrf This is indeed a problem. Unfortunately we cannot enable any cipher using diffie-hellman key exchange (`DHE`) because the Go TLS library only supports DH based on elliptic curves. Further we cannot enable legacy RSA based ciphers because they do not provide PFS (perfect forward secrecy).
> 
> You could run a reverse proxy - like nginx - in-front of Minio which handles the legacy TLS connection.
> Additionally you can ask the Amazon support to upgrade their internal ALB TLS configuration. I will also ask internally whether we may introduce a TLS configuration option for such situations but I don't think it's very likely that such a proposal gets accepted...

@aead @alrf we decided that we will not be supporting older ciphers and make sure to keep the code secure, it looks like a limitation of ALB and should be fixed on Amazon end. 

As @aead suggested using Nginx is a workaround in this scenario.
