### ISSUE TITLE
Too many file descriptors

### ISSUE THREAD

**Issue by pepelisu** [minio/minio#6612]
After stop and restart the daemon in distributed mode (2  nodes/ 4 disk each) the terminal is full of errors like this one:
```
2018-10-11 07:20:52.010224 I | http: Accept error: accept tcp 0.0.0.0:9000: accept4: too many open files; retrying in 10ms
```
When login in Minio Browser only one bucket is listed and when try to access it, it says ```server not initialized please try again.```

## Expected Behavior
Minio should restart without errors. Or if an incompatibility is present throw an error about it, explaining that the two server versions are incompatible. 

## Current Behavior
As mentioned above when stopped and started again, the output in terminal is a list of errors (too many open files) that seems endless, it has not stopped after 12h. 
If minio server is stopped in one of the nodes (server2) a big list with errors is shown all in the form of: 
```
goroutine 115801674 [IO wait]:
internal/poll.runtime_pollWait(0x7f8ee8d739f8, 0x72, 0xc4d9e77960)
	/opt/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc44cc26018, 0x72, 0xffffffffffffff00, 0x15dca60, 0x1d7a618)
	/opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc44cc26018, 0xc42dd07000, 0x1000, 0x1000)
	/opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc44cc26000, 0xc42dd07000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc44cc26000, 0xc42dd07000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc43ce0b878, 0xc42dd07000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:176 +0x6a
github.com/minio/minio/cmd/http.(*TimeoutConn).Read(0xc445a5dbf0, 0xc42dd07000, 0x1000, 0x1000, 0xc47010c840, 0xc4b576d0e0, 0xc4d9e77bfc)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/timeoutconn.go:46 +0x5f
net/http.(*persistConn).Read(0xc42e03ab40, 0xc42dd07000, 0x1000, 0x1000, 0xc4d9e77b98, 0x403355, 0xc47010c840)
	/opt/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc4b4e93860)
	/opt/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc4b4e93860, 0x1, 0x0, 0x0, 0x0, 0xc47010c6c0, 0x0)
	/opt/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc42e03ab40)
	/opt/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
	/opt/go/src/net/http/transport.go:1237 +0x95a

rax    0xca
rbx    0x20c6520
rcx    0x45b6a3
rdx    0x0
rdi    0x20c6668
rsi    0x0
rbp    0x7ffe7ee711d0
rsp    0x7ffe7ee71188
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x433ffce91dce9
r13    0x45290a
r14    0x200
r15    0x4
rip    0x45b6a1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

```
Consequently the other node (server1) stops to throw errors. Stopping minio in server1, after stopping server2, throws no error. 

## Possible Solution
Writing this I realize that server1 and server2 where not running the same minio version. They where working before the issue with server1=```RELEASE.2018-10-06T00-15-16Z```, while server2 was running: ```RELEASE.2018-09-01T00-38-25Z```
I stopped both servers, server2 with errors first, then server1 without. After update server2 to ```RELEASE.2018-10-06T00-15-16Z``` and restart both servers they started without errors and now minio web interface is showing all the buckets. 
So possible solution, always run the same server release in all the distributed systems. 

## Steps to Reproduce (for bugs)
I am not 100% sure that this will work as steps to reproduce, but lets say that:
1. At least two servers in distributed mode, one running updated and the other running old version of the server
2. Copy some data into a bucket.
3. Start and stop the servers.

## Context
I was changing from manual start to a daemon installation with SysVinit. 

## Regression
More than a regression this is a incompatibility. 

## Your Environment

* Version used (`minio version`): RELEASE.2018-10-06T00-15-16Z and RELEASE.2018-09-01T00-38-25Z
* Environment name and version (e.g. nginx 1.9.1): binary minio executable
* Server type and version: NA
* Operating System and version (`uname -a`): Linux 4.14.69-0-vanilla #1-Alpine SMP Mon Sep 10 19:33:23 UTC 2018 x86_64 Linux

**Comment by nitisht** [comment]
@pepelisu what is the client and the file system you're using. 

We made some changes in the way servers interact with each other (RPC calls) in release `RELEASE.2018-10-06T00-15-16Z`

**Comment by pepelisu** [comment]
Hi @nitisht  if you mean the client to connect I am using web client and minio client (mc). The problem described on top was happening without using any client, just by starting the servers.
Initially I formatted all the disks to ext4.

**Comment by nitisht** [comment]
understood @pepelisu . With `RELEASE.2018-10-06T00-15-16Z` we changed the RPC mechanism so it is recommended that users update all the instances to this version. This is a one time change, aimed to bring in huge performance benefits. 

Now that you have upgraded all the instances, it is expected work well. If there are further issues please do let us know..

**Comment by nitisht** [comment]
@pepelisu closing this as working as intended for now, feel free to reopen if you find problems again

**Comment by kannappanr** [comment]
@pepelisu closing this issue based on the previous comment. Please let us know if you have further questions
