### ISSUE TITLE
io.minio.errors.ErrorResponseException exception is being thrown when I'm doing an image migration, and uploading to both aws and gcp from minio api

### ISSUE THREAD

**Issue by nalin-sharma-freshworks** [minio/minio#6615]
Tried running around 360 odd jpeg records, If downloadable(via minio) from aws/gcp(exisitng image is present there for around 10-20 records so for rest of them the download will fail let's call these calls as 1 ). 1+ calls where we are downloading  10-20 images and then 20*7*2=280 uploads to aws and gcp via minio client

These calls are happening very quickly in 1 to 2 seconds
We are currently facing io.minio.errors.ErrorResponseException exception while uploading the images
Is there a scaling issue from minio side or is it something else?

PFA two attachments

<img width="1147" alt="image_upload_faliure" src="https://user-images.githubusercontent.com/42803264/46801511-7c4d2400-cd78-11e8-9d75-96744b5a6054.png">
<img width="1157" alt="image_upload_faliure_exception" src="https://user-images.githubusercontent.com/42803264/46801529-88d17c80-cd78-11e8-89b8-25327d727b52.png">

**Comment by nitisht** [comment]
@nalin-sharma-freshworks please use the issue template to report issues. Right now it is not really clear what are you trying to achieve and what is not working specifically. 

We also need to know the Minio version, your deployment environment and whether you're trying to run Minio as server or gateway.

**Comment by nitisht** [comment]
@nalin-sharma-freshworks closing this for now, feel free to reopen when you can give us above details / a simple reproducer to help us debug/reproduce the issue..
