### ISSUE TITLE
mc goes endless loop when tries to access an unencrypted remote object while SSE-C key provided

### ISSUE THREAD

**Issue by ghost** [minio/minio#6623]
Copy of https://github.com/minio/mc/issues/2567
----

mc goes endless loop when tries to access an unencrypted remote object while SSE-C key provided.

## Expected behaviour

mc should cat/cp/mirror an unencrypted remote object despite the SSE-C key provided.

## Actual behaviour

mc goes endless loop when tries to cat/cp/mirror an unencrypted remote object with SSE-C key provided.

## Context

There could accidentally be unencrypted file in a remote directroy, so one would not want his minio client go endless loop because of that. The client should rather see a warning that the file is unencrypted.

## Possible solution

Probably the client or a server should make the difference between encrypted and unencrypted remote objects.

## Steps to reproduce the behaviour

1. mc mb server/dir
2. mc cp file1.txt server/dir/ --encrypt-key "server/dir=$(echo pwd111 | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)"
3. mc cp file2.txt server/dir/
4. mc mirror server/dir/ localdir --encrypt-key "server/dir=$(echo pwd111 | openssl dgst -sha256 -binary | xxd -p -c 32 -l 16)"

mc will go endless loop:

```
...server/dir/file1.txt:  6 B / 12 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░┃ 47 B/s
```

 ``--debug`` option will show:

```
mc: <DEBUG> HEAD /dir/file2.txt HTTP/1.1
Host: server
User-Agent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-09-26T00:42:43Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181012/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-server-side-encryption-customer-algorithm;x-amz-server-side-encryption-customer-key;x-amz-server-side-encryption-customer-key-md5, Signature=**REDACTED**
X-Amz-Content-Sha256: **REDACTED**
X-Amz-Date: 20181012T074107Z
X-Amz-Server-Side-Encryption-Customer-Algorithm: AES256
X-Amz-Server-Side-Encryption-Customer-Key: **REDACTED**
X-Amz-Server-Side-Encryption-Customer-Key-Md5: **REDACTED**

mc: <DEBUG> HTTP/1.1 500 Internal Server Error
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Fri, 12 Oct 2018 07:41:06 GMT
Server: Minio/DEVELOPMENT.2018-10-11T20-22-03Z (linux; arm)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 155CCC8A12AE83C0
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  4.285215ms
```

## mc version

client ``RELEASE.2018-09-26T00-42-43Z``
server ``2018-10-11T20:22:03Z``

**Comment by harshavardhana** [comment]
This is not an endless loop it retries 8 times with binomial backoff, this retry for all 5xx http errors. 

Looks like the error translation is wrong on server side.

**Comment by ghost** [comment]
Oh, right. It just looked like an endless loop to me, did not had a patience to wait until it stops. :-)
