### ISSUE TITLE
Too many connection mysql,  events ddos server

### ISSUE THREAD

**Issue by fortunto2** [minio/minio#6624]
The server suddenly stopped working. The complaints were on the database. The reason was the events that had recorded minio to the base. After shutdown and reset everything worked. It seems on many times tried to burn one file and why it did not work. Fixated.

```

| 11 | files | localhost:58090 | files | Execute | 0 | update | INSERT INTO files (key_name, value) VALUES ('files/Asaf_Avidan_-_Love_It_Or_Leave_It_[www.jetune.ru] | 0.000 |
| 12 | files | localhost:58094 | files | Execute | 22 | update | INSERT INTO files (key_name, value) VALUES ('files/Asaf_Avidan_-_Love_It_Or_Leave_It_[www.jetune.ru] | 0.000 |
| 13 | files | localhost:58102 | files | Execute | 14 | update | INSERT INTO files (key_name, value) VALUES ('files/Asaf_Avidan_-_Love_It_Or_Leave_It_[www.jetune.ru] | 0.000 |
| 14 | files | localhost:58106 | files | Execute | 12 | update | INSERT INTO files (key_name, value) VALUES ('files/Asaf_Avidan_-_Love_It_Or_Leave_It_[www.jetune.ru] | 0.000 |
| 15 | files | localhost:58114 | files | Execute | 3 | update | INSERT INTO files (key_name, value) VALUES ('files/Asaf_Avidan_-_Love_It_Or_Leave_It_[www.jetune.ru] | 0.000 |

```

```
259 files localhost:48808 files Execute 24 update INSERT INTO files (key_name, value) VALUES ('files/Asaf_Avidan_-_Love_It_Or_Leave_It_[www.jetune.ru].mp3', '{\\"Records\\":[{\\"eventVersion\\":\\"2.0\\",\\"eventSource\\":\\"minio:s3\\",\\"awsRegion\\":\\"\\",\\"eventTime\\":\\"2018-10-12T20:39:40Z\\",\\"eventName\\":\\"s3:ObjectAccessed:Get\\",\\"userIdentity\\":{\\"principalId\\":\\"QHA50Z36SITW4FDEBZXK\\"},\\"requestParameters\\":{\\"sourceIPAddress\\":\\"144.76.141.180\\"},\\"responseElements\\":{\\"content-length\\":\\"10882970\\",\\"x-amz-request-id\\":\\"155CF706A55F4BF6\\",\\"x-minio-origin-endpoint\\":\\"http://10.187.230.1:9000\\"},\\"s3\\":{\\"s3SchemaVersion\\":\\"1.0\\",\\"configurationId\\":\\"Config\\",\\"bucket\\":{\\"name\\":\\"files\\",\\"ownerIdentity\\":{\\"principalId\\":\\"QHA50Z36SITW4FDEBZXK\\"},\\"arn\\":\\"arn:aws:s3:::files\\"},\\"object\\":{\\"key\\":\\"Asaf_Avidan_-_Love_It_Or_Leave_It_%5Bwww.jetune.ru%5D.mp3\\",\\"size\\":10882970,\\"eTag\\":\\"5a3bccb4bede6ec2adb98e0484fd8045\\",\\"contentType\\":\\"audio/mp3\\",\\"userMetadata\\":{\\"content-type\\":\\"audio/mp3\\"},\\"versionId\\":\\"1\\",\\"sequencer\\":\\"155CF706A55F4BF6\\"}},\\"source\\":{\\"host\\":\\"\\",\\"port\\":\\"\\",\\"userAgent\\":\\"Lavf/57.56.101\\"}}]}') ON DUPLICATE KEY UPDATE value=VALUES(value) 0.000

```

## Current Behavior
mysql go down
too many connections

## Possible Solution
restart minio
set mysql connections to 500

## Your Environment
    Version    2018-10-06T00:15:16Z
    Memory    Used: 4.2 MB | Allocated: 60 MB | Used-Heap: 4.2 MB | Allocated-Heap: 14 MB
    Platform   ubuntu 16.04
    Runtime   Version: go1.10.2 | CPUs: 8

![screenshot from 2018-10-13 01-46-17](https://user-images.githubusercontent.com/1236751/46893934-1651c100-ce8c-11e8-99da-c8869614d4f5.png)

**Comment by kannappanr** [comment]
@fortunto2 Thanks for filing this issue. Can you elaborate about the mysql part. Does your `mysql` go down because of too many events being sent to mysql? We will try to reproduce this issue and get back to you with more questions.

**Comment by eco-minio** [comment]
@fortunto2 I was unable to reproduce this issue specifically.  Based on what you are seeing, I would recommend increasing max connections.  By setting max connections to 2 (from default of 151) in mysql, I saw the following (which is expected given than the connection size is so low):
```
Time: 17:10:45 PDT 10/16/2018
Error: Error 1040: Too many connections
       EventName=s3:ObjectCreated:Put, targetID=mysql
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:81:logger.LogOnceIf()
       4: cmd/notification.go:545:cmd.sendEvent.func1()
```

We should add logic to repeat the message in such a way that it does not flood the console.

**Comment by fortunto2** [comment]
OK thanks, I don't know how to do it again right now... I have everything working. If it does write. Thanks

**Comment by kannappanr** [comment]
Closing this issue as stale now. Please re-open the issue if you see the error again.
