### ISSUE TITLE
.minio.sys/multipart is too large

### ISSUE THREAD

**Issue by anan-lee** [minio/minio#6627]
how to repair or clear the folder?
## Current Behavior

one of node in .minio.sys/multipart is too large

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
minio:
Version: 2018-09-25T21:34:43Z
Release-Tag: RELEASE.2018-09-25T21-34-43Z
Commit-ID: aa4e2b1542b98097e08680f21b790de0b776378c

os:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by anan-lee** [comment]
the size of directory in .minio.sys:

56K	buckets
16K	config
4.0K	format.json
96G	multipart
0	tmp

**Comment by kannappanr** [comment]
@anan-lee We should be able to delete the files in the multi-part folder atleast based on the date. We will try certain things and then get back to you on how to delete them.

**Comment by anan-lee** [comment]
@kannappanr  thanks for your reply.
Here is some information that might help you.
Normal node bucket directory space：
241M	file
114M	logs
668K	mobile
2.3G	product
...

bad node bucket directory space:
20M	file
604K	logs
668K	mobile
0	product
...

**Comment by harshavardhana** [comment]
.minio.sys/ multipart is cleaned every 12 hrs content which is 2 weeks older automatically.

**Comment by kannappanr** [comment]
@anan-lee One way you could have seen this is that the `bad node` had some network issues and it was offline during some of the operations. Also, we generally delete old multipart uploads older than 2 weeks are deleted as explained in the above comment.

The files in the `bad` node, are they more than 2 weeks old?

**Comment by belugaliu** [comment]
@harshavardhana Can the cleaning cycle be modified? and What is the role of the multipart folder's sub folders? and what version support the feature that clean multipart floder in every 2 weeks?

**Comment by liuliliGithub** [comment]
@harshavardhana Can the cleaning cycle be modified? and What is the role of the multipart folder's sub folders? and what version support the feature that clean multipart floder in every 2 weeks?

**Comment by kannappanr** [comment]
@liuliliGithub Currently there is no way to modify the cleaning cycle. The multipart's subfolder stores the incomplete parts for all the upload ids for a combination of bucket and object. 

For example

`.minio.sys/multipart/73c76171dcddbf238b23b7b2e0e3caad41bccc5d2ae24c21982f3b433c923759/914dfcf5-630e-4978-b647-a1e6d3dd02fe` 

`73c76171dcddbf238b23b7b2e0e3caad41bccc5d2ae24c21982f3b433c923759` corresponds to a combination of `bucket` and `object` name. It is almost like a hash of `object` and `bucket`

`914dfcf5-630e-4978-b647-a1e6d3dd02fe` is the upload id that was generated during the `InitiateMultipartUplaod` API call.

We have had this clean multipart folder feature for a while now.

**Comment by belugaliu** [comment]
@kannappanr  thanks, i am looking forward.

**Comment by kannappanr** [comment]
@liuliliGithub This auto cleaning feature is already present for the past few months. Are you saying that it is not working?

**Comment by mohanklein** [comment]
can I adjust the cleaning of unfinished multipart uploads (e.g. user closes browser accidentially) by simply running a cron which deletes files older than {X} from `.minio.sys/multipart` or is this a bad idea? I think two weeks is very long regarding huge file uploads which failed towards the end ... This might take up a lot of space and in my case it's pretty unlikely that users will resume uploads older than a single day ...

**Comment by harshavardhana** [comment]
> can I adjust the cleaning of unfinished multipart uploads (e.g. user closes browser accidentially) by simply running a cron which deletes files older than {X} from `.minio.sys/multipart` or is this a bad idea? I think two weeks is very long regarding huge file uploads which failed towards the end ... This might take up a lot of space and in my case it's pretty unlikely that users will resume uploads older than a single day ...

If this is most common we can reduce the 2 weeks to less than 3 days @mohanklein - manually is never a good idea.

**Comment by mohanklein** [comment]
@harshavardhana great! I don't see any practical case where users would upload files that take more than 2 days nor where users would pause a download and then resume after 2 days :-)

**Comment by mohanklein** [comment]
@harshavardhana I think older than 3 days is good `time.Hour * 24 * 3`

**Comment by harshavardhana** [comment]
> @harshavardhana I think older than 3 days is good `time.Hour * 24 * 3`

^^ @deekoder @kannappanr FYI

**Comment by zieg8301** [comment]
Also interested in this, we have a system that does occasional data loads over a less than perfect network connection (not going to improve anytime soon) and causes the multipart uploads to fail on occasion. Having a shorter multipart cleaning interval would be very helpful to us.

**Comment by scorpuva** [comment]
started the minio with >> `minio.exe server c:\storagefolder`

Getting below error for the file of size = 2GB
Using Post Url (PresignedPostPolicyAsync)
```
Error: [31m[1mmultipart: message too large[0m[0m
       4: cmd\bucket-handlers.go:596:cmd.objectAPIHandlers.PostPolicyBucketHandler()
       3: cmd\http-tracer.go:209:cmd.Trace()
       2: cmd\handler-utils.go:346:cmd.httpTraceHdrs.func1()
       1: net\http\server.go:1995:http.HandlerFunc.ServeHTTP()
```

Do i need to modify any config settings of minio?

**Comment by harshavardhana** [comment]
Your issue not related to this issue @scorpuva please open a new GitHub issue.
