### ISSUE TITLE
Unable to run minio in distributed mode 

### ISSUE THREAD

**Issue by CMADHANKUMAR** [minio/minio#6629]
I am uanble to start minio server in distributed mode with 8 nodes.When i start the server it shows something like the below.

[root@centos ~]# ./minio server http://10.81.1.211{1...8}/export
ERROR Invalid command line arguments: 'http://localhost1/export': lookup 10.81.1.2111 on 8.8.8.8:53: no such host.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide

**Comment by nitisht** [comment]
@CMADHANKUMAR what are the IP addresses of the nodes you're trying to run Minio on?

**Comment by CMADHANKUMAR** [comment]
10.81.1.211
10.81.1.170
10.81.1.222
10.81.1.236

**Comment by nitisht** [comment]
Then please try running following command on all the nodes

```
./minio server http://10.81.1.211/export http://10.81.1.170/export http://10.81.1.222/export http://10.81.1.236/export
```

The {...} ellipses notation is only useful when you have contiguous IP addresses.

**Comment by CMADHANKUMAR** [comment]
Worked for me.Thanks a lot !
