### ISSUE TITLE
disk-cache: Put object operations hashes data twice when disk cache is enabled

### ISSUE THREAD

**Issue by leitzler** [minio/minio#6630]
In disk-cache.go, `PutObject(...)` there are two hash readers created: https://github.com/minio/minio/blob/3ef3fefd5483696bd5d38f8cd9e2f37e6feaeed3/cmd/disk-cache.go#L671 
https://github.com/minio/minio/blob/3ef3fefd5483696bd5d38f8cd9e2f37e6feaeed3/cmd/disk-cache.go#L677

They will both perform the quite CPU heavy task of computing hashes for the same data that will harm performance quite a lot.

Note that this also applies to `PutObjectPart` & `PutChunkedObject`.

## Expected Behavior
Turning on cache shouldn't add much more overlay than disk I/O.

## Current Behavior
A lot of unnecessary CPU execution.

## Possible Solution
It would probably be a lot better to use an `io.TeeReader` with a single hash reader.

**Comment by poornas** [comment]
@leitzler, cache and backend are being written to simultaneously, and require hash readers. We can turn off the SHA256Sum and MD5Sum verification by passing in empty strings - however for a small overhead it provides the guarantee that content saved in cache and object store were the original client sent content.

**Comment by leitzler** [comment]
Yes, I noticed that it is written simultaneously and that's good. Both hash readers do however hash the same data twice and will end up with the same result since they read from the same source.

I couldn't see why it would require hash readers, except that it is currently designed that way. It will require some refactoring to change it to io.Readers, but it will provide a more clean code that is easier to maintain.

I did run some load towards PutObject with CPU profiling and hashing is a considerable part of where performance is lost.

**Comment by harshavardhana** [comment]
> I did run some load towards PutObject with CPU profiling and hashing is a considerable part of where performance is lost.

There is no performance gain in PUT for cache @leitzler current code exists for simplicity sake, we don't want to choose the differentiating code for hashing by deciding different situations on when checksum should be computed.

> Yes, I noticed that it is written simultaneously and that's good. Both hash readers do however hash the same data twice and will end up with the same result since they read from the same source.

The reason is also that both ends hash it such that the data that exists has an ETag which is used to validate if the caching is required on a GetObject - we use this ETag to send a request to the backend to check if the object should be reloaded to disk.

We can do as an optimization by moving the hashing to a layer above so that hashing is only done once and both read the hasher content the same.

**Comment by leitzler** [comment]
> We can do as an optimization by moving the hashing to a layer above so that hashing is only done once and both read the hasher content the same.

Yes, this would be my suggestion, great!

**Comment by harshavardhana** [comment]
@poornas are we doing this?

**Comment by nitisht** [comment]
fixed by #7575

**Comment by kannappanr** [comment]
#7575 was reverted, so re-opening this issue
