### ISSUE TITLE
Dockerfile.dev fails to build

### ISSUE THREAD

**Issue by sandyc316** [minio/minio#6631]
## Expected Behavior

Docker image should get built

## Current Behavior

Fails to build docker image

## Steps to Reproduce (for bugs)

1. Downloaded the code to local directory
2. Ran docker build -t minio -f Dockerfile.dev . to build the image
3. Failed with error: 
Step 4/12 : COPY minio /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder617022458/minio: no such file or directory
4.

## Context

Trying to build the docker image

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting @sandyc316 we'll take a look.

**Comment by harshavardhana** [comment]
> * Downloaded the code to local directory
> * Ran docker build -t minio -f Dockerfile.dev . to build the image
> * Failed with error:
>   Step 4/12 : COPY minio /usr/bin/
>   COPY failed: stat /var/lib/docker/tmp/docker-builder617022458/minio: no such file or directory

@sandyc316 you need to do `TAG=tag/release make docker`

**Comment by sandyc316** [comment]
Doing so it asks me to install golang. Do I need to install golang on my machine to build the docker image?
Also, If I use the default docker image: "minio/minio" how do I specify a config file in docker-compose.yml

**Comment by harshavardhana** [comment]
> Doing so it asks me to install golang. Do I need to install golang on my machine to build the docker image?
> Also, If I use the default docker image: "minio/minio" how do I specify a config file in docker-compose.yml

If you want to use default docker image just use `image: minio/minio:latest` tag, if you want to build your own version of Minio yes you need Golang installed.

For docker related documentation please read our published docs https://docs.minio.io/docs/deploy-minio-on-docker-compose.html

**Comment by sandyc316** [comment]
Thanks for the quick reply. However I don't see option to set the config file in docker-compose.yml example given there.

**Comment by nitisht** [comment]
You can mount the existing `config.json` under `/<data-dir>/.minio.sys/config/config.json` like explained here https://docs.docker.com/compose/compose-file/#volumes

**Comment by sandyc316** [comment]
Thanks that helped. I've been searching for the config file!
Can the config file path be mentioned in the docs?

**Comment by nitisht** [comment]
We do explain it here https://github.com/minio/minio/tree/master/docs/config

**Comment by sandyc316** [comment]
I did check it.. But it wasn't entirely clear to me. I had the following questions after reading it:

"Minio server stored all its configuration data in ${HOME}/.minio/config.json file by default.For all releases beyond minio.RELEASE.2017-08-05T00-00-53Z, the configuration data will be migrated to the Minio's backend directory"
**What is Minio's backend directory? Where is it mentioned in the docs?**

The default configuration directory is ${HOME}/.minio
**Is it the same as /data/.minio.sys/?**

**Comment by nitisht** [comment]
> What is Minio's backend directory?

Backend directory is where the data is actually stored, the directory that you pass as the argument to Minio server command.

> Is it the same as /data/.minio.sys/?

No. Configuration directory is where certs and other config items are kept. It is placed at `${HOME}/.minio` by default.

**Comment by sandyc316** [comment]
Thanks for the help. I'll be closing this issue now. However, I feel the documentation can improve a bit.

**Comment by nitisht** [comment]
Thanks for the feedback, @sandyc316 I have sent PR #6634
