### ISSUE TITLE
The architecture diagram of 8 servers for distributed mode shows wrong export drivers.

### ISSUE THREAD

**Issue by andrewnet** [minio/minio#6633]
The architecture diagram of 8 servers for distributed mode shows wrong export drivers in document (https://docs.minio.io/docs/distributed-minio-quickstart-guide). All the drives should be labeled as `EXPORT1` instead of ranging from `EXPORT1`, `EXPORT2`, ... `EXPORT8`

## Expected Behavior
All the drives should be labeled as `EXPORT1` instead of ranging from `EXPORT1`, `EXPORT2`, ... `EXPORT8`; otherwise, the command described in the document won't work.

## Current Behavior
The drives are labeled from `EXPORT1`, `EXPORT2`, ... `EXPORT8`.

## Possible Solution
There are three different versions of this diagram in the GitHub repo, all of them need to be fixed.
https://github.com/minio/minio/blob/master/docs/screenshots/Architecture-diagram_distributed_8.jpg
https://github.com/minio/minio/blob/master/docs/screenshots/Architecture-diagram_distributed_8.png
https://github.com/minio/minio/blob/master/docs/screenshots/Architecture-diagram_distributed_8.svg

## Steps to Reproduce (for bugs)
Go to https://docs.minio.io/docs/distributed-minio-quickstart-guide and search for `Example 1: Start distributed Minio instance on 8 nodes with 1 disk each mounted at /export1 (pictured below), by running this command on all the 8 nodes:`.

## Context
The diagram confuses the readers.

## Regression
N/A

## Your Environment
* Chrome browser

**Comment by nitisht** [comment]
Thanks for the issue @andrewnet , good catch. we'll fix this

**Comment by belvid** [comment]
Hi!

Here's the illustration with the fix. Thanks @andrewnet!

![architecture-diagram_distributed_8](https://user-images.githubusercontent.com/20955366/46968381-f0811380-d067-11e8-8776-c25b8af2889c.jpg)

**Comment by harshavardhana** [comment]
// cc @nitisht can you send a PR to fix this?

**Comment by nitisht** [comment]
yes, waiting for png/svg versions of the image as well cc @belvid

**Comment by deekoder** [comment]
Assigned to @belvid till the format is sent to @nitisht

**Comment by belvid** [comment]
PNG and SVG versions attached in a zip file

Here:

[ArchDiag-Dist8.zip](https://github.com/minio/minio/files/2504184/ArchDiag-Dist8.zip)
