### ISSUE TITLE
Updating metadata made files unavailable due to same erasure hash on all nodes 

### ISSUE THREAD

**Issue by curantes** [minio/minio#6638]
We implemented a virus check that when a file is fetched its scanned and scan status is added to minio metadata.

This caused files to be unavailable that have the new metadata set. After further investigation we noticed that the blake2 hash was the same value for the file on all nodes.

We Fixed this issue by get correct blake2 hash with `b2sum` for each part1.json for each file and if it diff with the info on xl.json we updated it with below bash script which was run using ad-hoc ansible on each node.

```bash
#!/bin/bash
set -e

FILE=$1
CHECKSUM=$(b2sum $FILE/part.1 | awk '{print $1}')

echo Hash on disk is $CHECKSUM

fileHash=$(jq -r '.erasure.checksum[0].hash' $FILE/xl.json)

echo Hash in xl.json is: $fileHash

if [[ $fileHash == $CHECKSUM ]]
then
	echo Hashed as the same. Doing nothing
	exit
fi

sed -i  -e "s/$fileHash/$CHECKSUM/g" $FILE/xl.json
```
We used below code to set metadata.
```go
package main
import (
	"fmt"
	"log"
	minio "github.com/minio/minio-go"
	"github.com/sirupsen/logrus"
)
func main() {
	bucketName := "426"
	filePath := "47426/2017/0927/a529c74d-2034-423c-b173-fda47678bad0.png"
	s3Client, err := minio.New("local:9091", "minio", "minio", false)
	if err != nil {
		log.Panic(err)
	}
	obj, err := s3Client.GetObject(bucketName, filePath, minio.GetObjectOptions{})
	objectStats, err := obj.Stat()
	if err != nil {
		fmt.Printf("s3: Unable to stat object: %s/%s error: %s ", bucketName, filePath, err)
	}
	log.Println("size:", objectStats.Size)
	log.Println(objectStats)
	m := make(map[string]string)
	m["X-Amz-Meta-Virus-Status"] = "CLEAN"
	m["X-Amz-Meta-Virus-Status"] = "2006-01-02T15:04:05.000 MST"
	// "content-type":"application/octet-stream"
	dst, err := minio.NewDestinationInfo(bucketName, filePath, nil, m)
	if err != nil {
		log.Println(err)
	}
	src := minio.NewSourceInfo(bucketName, filePath, nil)
	logrus.Infof("attempting to set metadata %s: %v", filePath, m)
	err = s3Client.CopyObject(dst, src)
	if err != nil {
		log.Println(err)
	}
}
```

## Expected Behavior

Modify metadata should not make files unavailable
## Current Behavior

Modifying metadata makes files unavailable. Data is intakt just the xl.json (metadata) is wrong
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 2018-01-02T23:07:00Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: VMware vSpehere 6.5, VM
* Operating System and version (`uname -a`): CentOS 7, Kernel: 3.10.0-693.2.2.el7.x86_64
* Link to your project:

**Comment by kannappanr** [comment]
@curantes Since you are using quite an older version of `minio`. We believe that we have fixed this issue in the later version of minio. Can you please try the same scenario that you have mentioned in this issue against the latest release of `minio`?

**Comment by curantes** [comment]
@kannappanr We have tried this against a 2018-09-01T00:38:25Z cluster without any issues. So I guess you are right.

**Comment by harshavardhana** [comment]
> @kannappanr We have tried this against a 2018-09-01T00:38:25Z cluster without any issues. So I guess you are right.

Shall we close this issue then @curantes ?

**Comment by curantes** [comment]
Yes we can close this, thanks
