### ISSUE TITLE
Cannot start server after modifying event type in configurations

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#6641]
Testing events in mysql, if you add events notification, then change format without changing the name of the table, minio fails to come up after restart
## Current Behavior

Server fails with the following:
```
Restart command successfully sent to `mysql`.

API: SYSTEM()
Time: 12:17:52 PDT 10/16/2018
Error: Error 1054: Unknown column 'event_time' in 'field list'
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/config-current.go:639:cmd.getNotificationTargets()
       3: cmd/notification.go:446:cmd.NewNotificationSys()
       4: cmd/server-main.go:370:cmd.serverMain()

API: SYSTEM(bucket=images)
Time: 12:17:52 PDT 10/16/2018
Error: ARN 'arn:minio:sqs::1:mysql' not found
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/notification.go:563:cmd.readNotificationConfig()
       3: cmd/notification.go:329:cmd.(*NotificationSys).Init()
       4: cmd/server-main.go:373:cmd.serverMain()
ERROR Unable to initialize notification system: ARN 'arn:minio:sqs::1:mysql' not found.
Failed to restart `mysql`. error: Get http://localhost:9000/minio/admin/v1/service: dial tcp 127.0.0.1:9000: connect: connection refused
```

## Possible Solution

A warning message should be printed, something to the effect that the database table already exists with a different format.  Preferably server should continue to start with a warning that events are not working.  In any case, the major problem is there is no way to recover, since the server will not start you cannot change the config via `mc admin config set` to correct the issue.

## Steps to Reproduce (for bugs)

1.  Set events notification per https://docs.minio.io/docs/minio-bucket-notification-guide.html (in this case I used mysql events)
2. Get config file `$ mc admin config get myminio/ > /tmp/myconfig`
3. Modify config file - pertinent snippet:
```
"mysql": {
                        "1": {
                                "enable": true,
                                "format": "namespace",
                                "dsnString": "",
                                "table": "minio_namespace",
                                "host": "127.0.0.1",
                                "port": "3306",
                                "user": "e",
                                "password": "password",
                                "database": "miniodb"
```
4. Reload config - `mc admin config set myminio < /tmp/myconfig && mc admin service restart mysql`
5. Copy an object into bucket to generate event and verify table got created in mysql database
6. Edit config file and change `format` from `namespace` to `access`
7. Reload config again per step 4
8. Server fails to start 

## Context

Testing events notifications.  Note that the testing I did was specific to mysql notifications but this potentially could affect other notification targets (postgres comes to mind immediately but could be others as well depending on what kind of checks are done before server is started).

## Regression

Not sure
## Your Environment

* Version used (`minio version`):
```
minio version
Version: 2018-10-06T00:15:16Z
Release-Tag: RELEASE.2018-10-06T00-15-16Z
Commit-ID: 66d911653f17b9b180493e3e21c6131170741dcf```

* Environment name and version (e.g. nginx 1.9.1):  MySQL 5.7.23
* Operating System and version (`uname -a`): Ubuntu 18.04

**Comment by harshavardhana** [comment]
We should fix this before release, we have no way to recover the config otherwise @vadmeste @eco-minio
