### ISSUE TITLE
disk size less than minimum threshold on windows 10 with docker 

### ISSUE THREAD

**Issue by monkut** [minio/minio#6647]
On windows 10 with docker Version 18.06.1-ce-win73 (19507) I'm trying to run minio with the docker command from the quickstart:

```
docker run -p 9000:9000 minio/minio server /data
```

## Expected Behavior
Expect *minio* to start with out failing.

> Also would be nice if minio output what the minimum threshold value actually is.

## Current Behavior
When I run the docker command:
```
docker run -p 9000:9000 minio/minio server /data
```
I get the error:

> ERROR Unable to initialize backend: The disk size is less than the minimum threshold.

## Possible Solution
Expand docker volume initial start disk size available to the image?
(Any idea how this might be done?)

## Steps to Reproduce (for bugs)

1. On windows 10 with less than 9 GB of free disk space run the command: 
```
docker run -p 9000:9000 minio/minio server /data
```

## Your Environment

* Minio docker: 

Version: 2018-10-06T00:15:16Z
Release-Tag: RELEASE.2018-10-06T00-15-16Z
Commit-ID: 66d911653f17b9b180493e3e21c6131170741dcf

* docker version:  Version 18.06.1-ce-win73 (19507)
* Operating System and version (`uname -a`): Windows 10 

> NOTE: My main C: drive has *8.48* GB free when this command is run.
> I've tried moving the docker data directory to a larger drive with more space (by updating the `"data-root": "d:\\dockerdata"` value in `C:\ProgramData\Docker\config\daemon.json`, but the error still shows up.

**Comment by harshavardhana** [comment]
```
const (
        diskMinFreeSpace  = 900 * humanize.MiByte // Min 900MiB free space.
        diskMinTotalSpace = diskMinFreeSpace      // Min 900MiB total space.
        maxAllowedIOError = 5
)
```

I think the problem is in the overlay disk filesystem for windows @monkut try with `--net=host` it might work.

**Comment by monkut** [comment]
@harshavardhana Thanks for the quick response!

I tried the following:
```
docker run --net=host -p 9000:9000 minio/minio server /data
```

But I'm getting the following error:
```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: network host not found.
```

Is there something I need to setup before running the `docker run` command?

**Comment by monkut** [comment]
Hmmmm... seems related to this issue:
https://forums.docker.com/t/does-the-run-option-network-host-work-on-docker-for-windows/45773/4

And a post about changing the overlay settings:
https://support.qasymphony.com/hc/en-us/articles/115004011906-Change-Docker-storage-driver-to-avoid-Overlay-issue

but looks like I can't change the storage driver on windows:

> Docker for Mac and Docker for Windows are intended for development, rather than production. Modifying the storage driver on these platforms is not possible.

https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-for-mac-and-docker-for-windows

**Comment by harshavardhana** [comment]
@monkut you are better off simply downloading the minio binary and running locally  https://github.com/minio/minio#microsoft-windows 

Docker on windows is not production ready

**Comment by monkut** [comment]
You're right, I'll give the binary a try.
