### ISSUE TITLE
Document did not have any information about key pair generation.

### ISSUE THREAD

**Issue by leouofl** [minio/minio#6656]
The current Document did not provide any info about how to create the access-key and secure key pair.

## Expected Behavior

The document should give an explanation about how to generate the key pair if needed.

## Current Behavior

Here is what I can find about the key pair. But I have tried to just randomly change the config.json file, but the minio failed to start. So I believe there is a special way to create those key pairs, but it's not documented anywhere I searched.

Field | Type | Description
-- | -- | --
credential |   | Auth credential for object storage and web access.
credential.accessKey | string | Access key of minimum 3 characters in length. You may override this field with MINIO_ACCESS_KEY environment variable.
credential.secretKey | string | Secret key of minimum 8 characters in length. You may override this field with MINIO_SECRET_KEY environment variable.

## Possible Solution

Update document about how to create credential.accessKey and credential.secretKey

## Steps to Reproduce (for bugs)

1. In  a working minio installation. Verify that you cna do service minio restart and it works okey
2. got to /home/.minio/config.json, modify the existing key by random changes. Here I replaced the working key pair with x* and k*.
        "credential": {
                "accessKey": "xxxxxxxxxxx",
                "secretKey": "kkkkkkkkkkkkkkkkkkkkk"
        },

3. service minio restart. The service failed to restart

## Context

We are trying to change the key pair on minio, but can't

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
you can set to whatever value you like @leouofl through ENV, you can also set this using `mc admin credentials` - https://docs.minio.io/docs/minio-admin-complete-guide.html#credentials

**Comment by nitisht** [comment]
@leouofl closing this as answered, please reach out to us on slack https://slack.minio.io for more questions
