### ISSUE TITLE
Why does the gateway-s3 requires MINIO_ACCESS_KEY and SECRET?

### ISSUE THREAD

**Issue by palmerabollo** [minio/minio#6657]
Running the S3 gateway (`minio gateway s3`) requires `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY`, even when the client already uses its own set of credentials (aws key + secret). Is there any reason for this behaviour?

```
s3 client -(key + secret)-> minio -(MINIO_ACCESS_KEY + MINIO_ACCESS_SECRET)-> AWS S3
```

## Expected Behavior
MINIO_ACCESS_KEY and MINIO_SECRET_KEY shouldn't be mandatory. Client access key + secret should be used to connect to AWS in this case.

## Your Environment
* Version used (`minio version`): minio/minio:RELEASE.2018-10-06T00-15-16Z

**Comment by harshavardhana** [comment]
Because Minio does the signature termination of your incoming S3 calls. @palmerabollo
