### ISSUE TITLE
ON windows erasure compiles fine but throws error upon go test -race

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#666]
C:\mygo\src\github.com\minio\minio\pkg\erasure>go test -race
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x609a1d]

runtime stack:
invalid spdelta 0x6099e7 0x609a1d 0xa4551 -1
gf_4vect_dot_prod_avx.next_vect()
        ?:0 +0x36

goroutine 8 [syscall, locked to thread]:
runtime.cgocall_errno(0x605eb0, 0xc082027788, 0x0)
        c:/go/src/runtime/cgocall.go:130 +0xeb fp=0xc082027768 sp=0xc082027740
github.com/minio/minio/pkg/erasure._Cfunc_ec_encode_data(0xa00000040, 0xc000000005, 0x23e880, 0x23f
        github.com/minio/minio/pkg/erasure/_test/_obj_test/_cgo_gotypes.go:32 +0x7a fp=0xc082027788
github.com/minio/minio/pkg/erasure.(_Erasure).Decode(0xc08205e3f0, 0xc08206e180, 0xf, 0xf, 0x23e, 0
        C:/mygo/src/github.com/minio/minio/pkg/erasure/erasure_decode.go:113 +0xcc8 fp=0xc082027998
github.com/minio/minio/pkg/erasure.(_MySuite).TestCauchyEncodeDecodeSuccess(0x119c270, 0xc0820660f0
        C:/mygo/src/github.com/minio/minio/pkg/erasure/cauchy_test.go:65 +0x309 fp=0xc082027aa0 sp=
runtime.call16(0x689928, 0xc082008740, 0x1000000010)
        c:/go/src/runtime/asm_amd64.s:401 +0x4c fp=0xc082027ab8 sp=0xc082027aa0
reflect.Value.call(0x689860, 0x119c270, 0x313, 0x6af7b0, 0x4, 0xc082027f78, 0x1, 0x1, 0x0, 0x0, ...
        c:/go/src/reflect/value.go:419 +0x1339 fp=0xc082027dd0 sp=0xc082027ab8
reflect.Value.Call(0x689860, 0x119c270, 0x313, 0xc082027f78, 0x1, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/reflect/value.go:296 +0xe0 fp=0xc082027e48 sp=0xc082027dd0
github.com/minio/check.func┬╖003(0xc0820660f0)
        C:/mygo/src/github.com/minio/check/check.go:763 +0x569 fp=0xc082027fb0 sp=0xc082027e48
github.com/minio/check.func┬╖001()
        C:/mygo/src/github.com/minio/check/check.go:657 +0xff fp=0xc082027fe0 sp=0xc082027fb0
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc082027fe8 sp=0xc082027fe0
created by github.com/minio/check.(*suiteRunner).forkCall
        C:/mygo/src/github.com/minio/check/check.go:658 +0x687

goroutine 1 [chan receive]:
testing.RunTests(0x71e4b8, 0x118ac70, 0x1, 0x1, 0x1)
        c:/go/src/testing/testing.go:556 +0xdca
testing.(*M).Run(0xc08200c190, 0x119bd00)
        c:/go/src/testing/testing.go:485 +0xe8
main.main()
        github.com/minio/minio/pkg/erasure/_test/_testmain.go:52 +0x294

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/minio/check.(_suiteRunner).runTest(0xc08200e100, 0xc082012150, 0xc082066000)
        C:/mygo/src/github.com/minio/check/check.go:801 +0x86
github.com/minio/check.(_suiteRunner).run(0xc08200e100, 0x119c270)
        C:/mygo/src/github.com/minio/check/check.go:606 +0x4f8
github.com/minio/check.Run(0x689860, 0x119c270, 0xc082002ac0, 0x500000000000000)
        C:/mygo/src/github.com/minio/check/run.go:92 +0x5f
github.com/minio/check.RunAll(0xc082002ac0, 0x0)
        C:/mygo/src/github.com/minio/check/run.go:84 +0x13a
github.com/minio/check.TestingT(0xc082064000)
        C:/mygo/src/github.com/minio/check/run.go:72 +0x4d3
github.com/minio/minio/pkg/erasure.Test(0xc082064000)
        C:/mygo/src/github.com/minio/minio/pkg/erasure/cauchy_test.go:30 +0x3d
testing.tRunner(0xc082064000, 0x118ac70)
        c:/go/src/testing/testing.go:447 +0x13b
created by testing.RunTests
        c:/go/src/testing/testing.go:555 +0xd55

goroutine 6 [select]:
github.com/minio/check.(_resultTracker)._loopRoutine(0xc082064090)
        C:/mygo/src/github.com/minio/check/check.go:452 +0x515
created by github.com/minio/check.(_resultTracker).start
        C:/mygo/src/github.com/minio/check/check.go:432 +0x47
exit status 2
FAIL    github.com/minio/minio/pkg/erasure      0.362s

**Comment by vadmeste** [comment]
I don't have this error in my machine, all erasure unit tests were successful

**Comment by harshavardhana** [comment]
> I don't have this error in my machine, all erasure unit tests were successful

what version of GCC are you using? is it mingw, win-builds - i saw this issue with latest "win-builds"

**Comment by vadmeste** [comment]
I use win-builds-1.5.0 (gcc 4.8.3, target x86_64-w64-mingw32) and yasm 1.2 which is independantly installed

**Comment by harshavardhana** [comment]
> I use win-builds-1.5.0 (gcc 4.8.3, target x86_64-w64-mingw32) and yasm 1.2 which is independantly

must be something in my installation, i will verify this later. Thanks for testing..
