### ISSUE TITLE
How to config event store when minio server startup at the first time but not use mc and restart node

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6663]
Hello, My english is poor, so maybe there is some syntax error in my description. I want to use minio in multi-tenant distribute mode. How to config event notify when minio server startup at the first time but not use mc and restart node. It is not a good way and is too inconvenient. So I want to ask everyone a good solution.

**Comment by harshavardhana** [comment]
> Hello, My english is poor, so maybe there is some syntax error in my description. I want to use minio in multi-tenant distribute mode. How to config event notify when minio server startup at the first time but not use mc and restart node. It is not a good way and is too inconvenient. So I want to ask everyone a good solution.

That is the only way right @kellenchen we are refactoring the approach in upcoming releases, for now you need to edit the `config.json` for the event notifications and update the server.

https://docs.minio.io/docs/minio-bucket-notification-guide.html

**Comment by kellenchen** [comment]
hi, I want to ask how to find the config.json file. Below is my minio version.

 root@localhost ~]# ./minio version
Version: 2018-10-06T00:15:16Z
Release-Tag: RELEASE.2018-10-06T00-15-16Z
Commit-ID: 66d911653f17b9b180493e3e21c6131170741dcf

And below is my startup command. But I can not find the config.json file in config-dir. Only use mc admin config get ?
./minio --config-dir ~/minio_tenant_config/tenant2 server --address .........

@harshavardhana

**Comment by harshavardhana** [comment]
@kellenchen follow the docs here https://docs.minio.io/docs/minio-server-configuration-guide.html

**Comment by deekoder** [comment]
@kellenchen  did the link help?

**Comment by kellenchen** [comment]
em....The link I saw before and can not solve my problem. Maybe it is the point that the minio should optimize in the future.

**Comment by harshavardhana** [comment]
> em....The link I saw before and can not solve my problem. Maybe it is the point that the minio should optimize in the future.

Why did it not solve your problem? what is the issue that you saw @kellenchen?

**Comment by deekoder** [comment]
@kellenchen  thanks for letting us know. We will think about your point of view as we refactor how to interact with the config later. If you follow our guide, i think you can get away with setting it all and doing a single restart once.

**Comment by kellenchen** [comment]
> @kellenchen thanks for letting us know. We will think about your point of view as we refactor how to interact with the config later. If you follow our guide, i think you can get away with setting it all and doing a single restart once.

config once but should restart all nodes to take effect in distributed mode.

**Comment by harshavardhana** [comment]
Yes you can restart nodes by just doing `mc admin restart myminio` you don't need to restart them individually.

**Comment by kellenchen** [comment]
> Yes you can restart nodes by just doing `mc admin restart myminio` you don't need to restart them individually.

Are below steps right ?

1. deploy the distributed minio on serval hosts and start them and use mc add host  command on every host.
2. choose one host and use mc admin config set command to update minio config and use mc admin restart myminio. Is it will restart all nodes if all nodes are called myminio ?
3. choose step 2's host, use mc events add command. Is it will take effect on other nodes ?

**Comment by harshavardhana** [comment]
> Are below steps right ?
> 
> 1. deploy the distributed minio on serval hosts and start them and use mc add host  command on every host.

You only need to only one node using `mc config host` command

> 2. choose one host and use mc admin config set command to update minio config and use mc admin restart myminio. Is it will restart all nodes if all nodes are called myminio ?

You need only do this once `mc admin service restart myminio` - this will restart all of them

> 3. choose step 2's host, use mc events add command. Is it will take effect on other nodes ?

You need to only do this once `mc events add` this will apply to everyone

**Comment by kellenchen** [comment]
In your opinion, below is my mc config host add command. Is it right ? I just add one host and it will not take effect on other nodes. I remember I test before.

[root@localhost ~]# ./mc config host add myminio1 http://xx.xx.xxx.xxx:9001 minio1 minio123 


=====================================================================

em.....I test as you say above. The config updated and the event added will apply to everyone. But the host config is not apply to other. So if I want to see server config and event config take effect on other nodes. I should first use mc config add host on other nodes.

**Comment by kellenchen** [comment]
API: SYSTEM()
Time: 17:26:18 CST 10/28/2018
Error: Server not initialized, please try again
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/admin-rpc-client.go:277:cmd.getPeerUptimes()
       3: cmd/admin-handlers.go:106:cmd.adminAPIHandlers.ServiceStatusHandler()
       4: cmd/admin-router.go:48:cmd.(adminAPIHandlers).ServiceStatusHandler-fm()
       5: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()


**when I use mc admin service restart myminio command to restart the server. It print the above error. But it restart successfully.**



**Another issue:**

API: SYSTEM()
Time: 15:15:08 CST 10/24/2018
Error: client time 2018-10-24 07:15:08 +0000 UTC is too apart with server time 2018-10-24 07:33:38.66263289 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()

API: SYSTEM()
Time: 22:23:53 CST 10/26/2018
Error: client time 2018-10-26 14:23:53 +0000 UTC is too apart with server time 2018-10-26 02:23:37.375204081 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()

API: SYSTEM()
Time: 22:23:53 CST 10/26/2018
Error: client time 2018-10-26 14:23:53 +0000 UTC is too apart with server time 2018-10-26 05:23:38.572195044 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()

API: SYSTEM()
Time: 22:23:53 CST 10/26/2018
Error: client time 2018-10-26 14:23:53 +0000 UTC is too apart with server time 2018-10-26 02:23:37.384828573 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()

API: SYSTEM()
Time: 22:23:53 CST 10/26/2018
Error: Storage resources are insufficient for the read operation.
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/config.go:196:cmd.readConfig()
       3: cmd/policy.go:195:cmd.getPolicyConfig()
       4: cmd/xl-sets.go:507:cmd.(*xlSets).GetBucketPolicy()
       5: cmd/policy.go:102:cmd.(*PolicySys).refresh()
       6: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()

API: SYSTEM()
Time: 13:01:46 CST 10/27/2018
Error: client time 2018-10-27 05:01:46 +0000 UTC is too apart with server time 2018-10-27 05:36:44.875634538 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()

API: SYSTEM()
Time: 13:01:46 CST 10/27/2018
Error: client time 2018-10-27 05:01:46 +0000 UTC is too apart with server time 2018-10-27 05:36:44.88038007 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
       3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()

API: SYSTEM()
Time: 18:03:51 CST 10/27/2018
Error: client time 2018-10-27 10:03:51 +0000 UTC is too apart with server time 2018-10-28 02:06:16.477670013 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-bucket.go:200:cmd.xlObjects.listBuckets()
       3: cmd/xl-v1-bucket.go:212:cmd.xlObjects.ListBuckets()
       4: cmd/xl-sets.go:585:cmd.(*xlSets).ListBuckets()
       5: cmd/policy.go:95:cmd.(*PolicySys).refresh()
       6: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()

API: SYSTEM()
Time: 18:03:51 CST 10/27/2018
Error: client time 2018-10-27 10:03:51 +0000 UTC is too apart with server time 2018-10-28 02:06:16.477670013 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/policy.go:97:cmd.(*PolicySys).refresh()
       3: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()

API: SYSTEM()
Time: 15:43:38 CST 10/28/2018
Error: client time 2018-10-28 07:43:38 +0000 UTC is too apart with server time 2018-10-28 08:21:57.46197192 +0000 UTC
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/xl-v1-bucket.go:200:cmd.xlObjects.listBuckets()
       3: cmd/xl-v1-bucket.go:212:cmd.xlObjects.ListBuckets()
       4: cmd/xl-sets.go:585:cmd.(*xlSets).ListBuckets()
       5: cmd/policy.go:95:cmd.(*PolicySys).refresh()
       6: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()


How does it happen ? I use date command on every host, It print the correct time as my computer.
which is the client and which is the server ?

**Comment by kellenchen** [comment]
./mc events add myminio1/images arn:minio:sqs::1:mysql

this is the add event command. How to add event for all buckets which are not created now ?

**Comment by kellenchen** [comment]
@harshavardhana @deekoder

**Comment by kannappanr** [comment]
@kellenchen  

> How to add event for all buckets which are not created now ?

Event notification is supported only for existing buckets.

**Comment by kannappanr** [comment]
> API: SYSTEM()
> Time: 17:26:18 CST 10/28/2018
> Error: Server not initialized, please try again
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/admin-rpc-client.go:277:cmd.getPeerUptimes()
> 3: cmd/admin-handlers.go:106:cmd.adminAPIHandlers.ServiceStatusHandler()
> 4: cmd/admin-router.go:48:cmd.(adminAPIHandlers).ServiceStatusHandler-fm()
> 5: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
> 
> **when I use mc admin service restart myminio command to restart the server. It print the above error. But it restart successfully.**
> 
> **Another issue:**
> 
> API: SYSTEM()
> Time: 15:15:08 CST 10/24/2018
> Error: client time 2018-10-24 07:15:08 +0000 UTC is too apart with server time 2018-10-24 07:33:38.66263289 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()
> 
> API: SYSTEM()
> Time: 22:23:53 CST 10/26/2018
> Error: client time 2018-10-26 14:23:53 +0000 UTC is too apart with server time 2018-10-26 02:23:37.375204081 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()
> 
> API: SYSTEM()
> Time: 22:23:53 CST 10/26/2018
> Error: client time 2018-10-26 14:23:53 +0000 UTC is too apart with server time 2018-10-26 05:23:38.572195044 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()
> 
> API: SYSTEM()
> Time: 22:23:53 CST 10/26/2018
> Error: client time 2018-10-26 14:23:53 +0000 UTC is too apart with server time 2018-10-26 02:23:37.384828573 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()
> 
> API: SYSTEM()
> Time: 22:23:53 CST 10/26/2018
> Error: Storage resources are insufficient for the read operation.
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/config.go:196:cmd.readConfig()
> 3: cmd/policy.go:195:cmd.getPolicyConfig()
> 4: cmd/xl-sets.go:507:cmd.(*xlSets).GetBucketPolicy()
> 5: cmd/policy.go:102:cmd.(*PolicySys).refresh()
> 6: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()
> 
> API: SYSTEM()
> Time: 13:01:46 CST 10/27/2018
> Error: client time 2018-10-27 05:01:46 +0000 UTC is too apart with server time 2018-10-27 05:36:44.875634538 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()
> 
> API: SYSTEM()
> Time: 13:01:46 CST 10/27/2018
> Error: client time 2018-10-27 05:01:46 +0000 UTC is too apart with server time 2018-10-27 05:36:44.88038007 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-utils.go:310:cmd.readXLMeta()
> 3: cmd/xl-v1-utils.go:342:cmd.readAllXLMetadata.func1()
> 
> API: SYSTEM()
> Time: 18:03:51 CST 10/27/2018
> Error: client time 2018-10-27 10:03:51 +0000 UTC is too apart with server time 2018-10-28 02:06:16.477670013 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-bucket.go:200:cmd.xlObjects.listBuckets()
> 3: cmd/xl-v1-bucket.go:212:cmd.xlObjects.ListBuckets()
> 4: cmd/xl-sets.go:585:cmd.(*xlSets).ListBuckets()
> 5: cmd/policy.go:95:cmd.(*PolicySys).refresh()
> 6: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()
> 
> API: SYSTEM()
> Time: 18:03:51 CST 10/27/2018
> Error: client time 2018-10-27 10:03:51 +0000 UTC is too apart with server time 2018-10-28 02:06:16.477670013 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/policy.go:97:cmd.(*PolicySys).refresh()
> 3: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()
> 
> API: SYSTEM()
> Time: 15:43:38 CST 10/28/2018
> Error: client time 2018-10-28 07:43:38 +0000 UTC is too apart with server time 2018-10-28 08:21:57.46197192 +0000 UTC
> 1: cmd/logger/logger.go:294:logger.LogIf()
> 2: cmd/xl-v1-bucket.go:200:cmd.xlObjects.listBuckets()
> 3: cmd/xl-v1-bucket.go:212:cmd.xlObjects.ListBuckets()
> 4: cmd/xl-sets.go:585:cmd.(*xlSets).ListBuckets()
> 5: cmd/policy.go:95:cmd.(*PolicySys).refresh()
> 6: cmd/policy.go:148:cmd.(*PolicySys).Init.func1()
> 
> How does it happen ? I use date command on every host, It print the correct time as my computer.
> which is the client and which is the server ?

I think you can ignore the initial error. As far as the time difference is concerned, I think that one or more of your nodes have a time difference of 15 seconds and that is causing this issue.
