### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Darkknight33** [minio/minio#6667]
In reference to https://github.com/minio/minio/issues/5874 the documentation page: https://docs.minio.io/docs/minio-server-limits-per-tenant.html

should probably include / in the section: Object name restrictions on Minio

**Comment by eco-minio** [comment]
Tested ",*,:,<,>,?,/, and \ against NTFS, will document these as invalid as well.

**Comment by Darkknight33** [comment]
My Minio instance volumes are IIRC backed in ext4, so I don't think it's just limited to NTFS.

**Comment by eco-minio** [comment]
@Darkknight33 The documentation mentions that it is to cover Windows or other filesystems, the intent is not to cover every possibly permutation, more to make users aware.  In typical scenarios these characters would not be in file names so this is more to call out the behaviour in those cases.
