### ISSUE TITLE
Add a node/disk error in distribute mode 

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6672]
I deploy minio in distributed mode for 4 node and 4 disks. I want to test minio if I add a node and restart all nodes whether the server works well and the config and event notify config works well. So I deploy 6 nodes now which is not allowed to deploy 5 nodes. But when I execute the command on the first node it throw a error as below.

**"ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 6 but the number of disks found in the 1st disk's format.json: 4)."**

what should I do to handle this and fit my expect.

**Comment by harshavardhana** [comment]
This is as per design you cannot add disks to an existing setup @kellenchen you expand by deploying new instances using federation.

**Comment by kellenchen** [comment]
existing setup means even the origin setup has been shutdown ? using federation ? can give more details ?

**Comment by harshavardhana** [comment]
> existing setup means even the origin setup has been shutdown ? using federation ? can give more details ?

here are the details https://docs.minio.io/docs/distributed-minio-quickstart-guide.html
> As with Minio in stand-alone mode, distributed Minio has a per tenant limit of minimum 2 and maximum 32 servers. There are no limits on number of disks shared across these servers. If you need a multiple tenant setup, you can easily spin up multiple Minio instances managed by orchestration tools like Kubernetes.

Existing setup means the disks used for 4 disk setup cannot be used with 6 disk setup, you have to wipe out all the content on the backend and then freshly start with 6 disks. 

Minio doesn't support adding new disks to your existing setup of 4 disks and this is as per design, if you wish to add more storage space you actually expand the cluster by adding federating servers as explained in the following document

https://docs.minio.io/docs/minio-federation-quickstart-guide.html for federation of multiple clusters

**Comment by harshavardhana** [comment]
Closing as answered.

**Comment by harshavardhana** [comment]
This issue has been addressed, locking all future conversations.
