### ISSUE TITLE
Is the length of secret limit and what is the limit of bucket name ?

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6673]
Is the length of key limit and what is the limit of bucket name ?

**Comment by harshavardhana** [comment]
There is not top level limit for secret key length, minimum is 8 characters.

Bucket name is restricted based on AWS S3 bucket name restrictions.

https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

i.e 63 maximum and minimum of 3 characters

Following document provides list if limits for each deployment of Minio http://docs.minio.io/docs/minio-server-limits-per-tenant.html

As a suggestion please join our channel for more real time answers for these type of questions at https://slack.minio.io
