### ISSUE TITLE
Access key and Secret key cannot have "-" as first character

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#6684]
When minio generates a secret key, or if user uses environment variable and has "-" as first character, when you try to add the server it assumes the key is an argument

## Expected Behavior

We should not allow "-" to be the first character of the secret key or access key, and we should never automatically generate keys with "-" in the first position.

## Current Behavior

When trying to add via mc you see the message:
Incorrect Usage: flag provided but not defined: -minio

## Steps to Reproduce (for bugs)

1. Create minio instance with secret key or access key starting with "-" char
```
export MINIO_ACCESS_KEY="-minio"; export MINIO_SECRET_KEY="secretkey123"; minio server /data 
```
2. Try to add host via `mc`
```
mc config host add badkey http://127.0.0.1:9000 -minio secretkey123
Incorrect Usage: flag provided but not defined: -minio
```

## Context

Initially saw this issue with auto generated secret key, so we need to handle the case where user generated or server generated automatically
## Regression

Unknown
## Your Environment

* Version used (`minio version`):
Version: 2018-10-18T00:28:58Z
Release-Tag: RELEASE.2018-10-18T00-28-58Z
Commit-ID: 3b553570459cdf8b10671105252c707ff2cf76f3
* Operating System and version (`uname -a`):
Tested against Minio running in Mac OS High Sierra and Windows 2012 R2

**Comment by harshavardhana** [comment]
```
~ mc config host add --api s3v4 badkey https://127.0.0.1:9000 "-minio" "secretkey123"
```

Should work in this scenario @eco-minio - this is an issue with CLI package since `-` is a separator for flags since we use positional arguments it is possible that '-' will cause confusion which is what is happening.   

This issue is not about access key having `-` or not and has nothing to do with the server not supporting `-`.

**Comment by nitisht** [comment]
closing this based on previous comment

**Comment by harshavardhana** [comment]
Actually a PR was sent to avoid base64 url encoding
