### ISSUE TITLE
when minio server config ssl certificate，internet explorer cannot access,but chrom can why?

### ISSUE THREAD

**Issue by gxwangit** [minio/minio#6686]
## Current Behavior

this is my minio server :  https://minio.mopaas.com/minio/login,chorm access is ok,but  internet explorer cannot access,anybody encounter this problem？how to fix it？

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
We'll check this out @gxwangit

**Comment by deekoder** [comment]
Which version of IE are you using. We can try different IE versions. But it will help to get your IE version.

**Comment by gxwangit** [comment]
> We'll check this out @gxwangit
thanks you

**Comment by gxwangit** [comment]
> Which version of IE are you using. We can try different IE versions. But it will help to get your IE version.
IE 10

**Comment by kaankabalak** [comment]
I was able to reproduce this issue both on IE10 and IE11, we will be investigating the cause and keep you updated @gxwangit

**Comment by harshavardhana** [comment]
Do you see any logs on the server Kaan ?

**Comment by kaankabalak** [comment]
@harshavardhana I just tested it on Play and on the given link on a VM for now, however I can test it on another instance, try to access it from there, and check the server logs.

**Comment by kaankabalak** [comment]
The server log prints the following error when Minio server is configured with TLS and the user tries to access it from IE10:
```
API: SYSTEM()
Time: 19:46:31 UTC 10/31/2018
Error: tls: no cipher suite supported by both client and server
       remoteAddr=73.222.245.195:50811, localAddr=147.75.109.111:9000
       1: cmd/http/listener.go:255:http.(*httpListener).start.func2()
```

**Comment by liezh** [comment]
i have seen issue in C# SDK 



API: SYSTEM()
Time: 02:42:12 UTC 11/01/2018
Error: malformed HTTP request from '172.17.0.2:9000'
       remoteAddr=10.20.0.200:50541, localAddr=172.17.0.2:9000
       1: cmd/logger/logger.go:295:logger.LogIf()
       2: cmd/http/listener.go:274:http.(*httpListener).start.func2()

**Comment by kannappanr** [comment]
@gxwangit From the error, it looks like IE10 does not use recommended cipher suites. Minio does not support older and cryptographically insecure cipher suites.
If you need to have TLS enabled, then one option here is to use a TLS reverse-proxy.

**Comment by harshavardhana** [comment]
// cc @aead - it's not possible for us to support Windows older weaker ciphersuites. Best approach is to upgrade your Windows servers, or use Linux or use nginx like reverse-proxy to enable weaker ciphersuites

> i have seen issue in C# SDK
> 
> API: SYSTEM()
> Time: 02:42:12 UTC 11/01/2018
> Error: malformed HTTP request from '172.17.0.2:9000'
> remoteAddr=10.20.0.200:50541, localAddr=172.17.0.2:9000
> 1: cmd/logger/logger.go:295:logger.LogIf()
> 2: cmd/http/listener.go:274:http.(*httpListener).start.func2()

this is probably you are making a TLS request with server not configured with TLS @liezh

**Comment by aead** [comment]
@liezh If you run Windows 7 / Windows Server 2008/2012 you may have to use a `ECDSA` certificate instead of a `RSA` certificate. The reason is that these windows versions don't support and AEAD cipher + PFS (e.g. AES-GCM + ECDHE) for RSA public/private keys. (I have no clue why...).

@gxwangit You are using a RSA certificate at your minio server. You may should consider using a ECDSA certificate, too. That would allow accessing the server with IE 11 and probably with IE 10 too.
For example I see: `TLS_ECDHE_RSA_*` for your server. Switching to `TLS_ECDHE_ECDSA_*` should fix the IE 11 problem.


Apart from that it's recommended anyway to prefer ECC over "classical" schemes. For example the Go TLS stack does not use a constant-time RSA implementation... (IIRC).

**Comment by nitisht** [comment]
closing this as working as intended
