### ISSUE TITLE
Issues with event notifications for Elasticsearch

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#6691]
`access` format type does not add events to Elasticsearch
## Expected Behavior

Events should be logged for `access` format, and timestamp errors should not be seen for either format
## Current Behavior

When setting up event notifications for Elasticsearch per https://github.com/minio/minio/tree/master/docs/bucket/notifications#Elasticsearch, noted that no events are added to an index when using format type `access`.  Using `access` or `namespace` format, errors (see repro steps for example) are intermittently printed to server on various operations (e.g. delete, put)

## Possible Solution

Unknown, @donatello tested a build with an updated Elasticsearch library but the issue persisted.
## Steps to Reproduce (for bugs)

1. Follow instructions for setting up event notification in Elasticsearch
2. Set format type to `access`, `mc admin config set < myconfig`, restart server
3. Verify events set for bucket - `mc events list myminio/images
arn:minio:sqs::1:elasticsearch   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter:` 
4. Upload files to myminio/images bucket - `mc cp -r . myminio/images`
5. Check Elasticsearch for events:
```
curl  "http://localhost:9200/minio_events/_search?pretty=true" 
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```
Files are uploaded successfully but no events are shown, and server shows error:
```
API: SYSTEM(bucket=images, object=03.file)
Time: 17:26:11 PDT 10/23/2018
Error: elastic: Error 400 (Bad Request): request [/minio_events/event/] contains unrecognized parameter: [timestamp] [type=illegal_argument_exception]
       EventName=s3:ObjectCreated:Put, targetID=elasticsearch
       1: cmd/logger/logger.go:295:logger.LogIf()
       2: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       3: cmd/logger/logonce.go:81:logger.LogOnceIf()
       4: cmd/notification.go:561:cmd.sendEvent.func1()
```
## Context

Testing events notification to Elasticsearch
## Regression

Unknown
## Your Environment

* Version used (`minio version`):
```
minio version
Version: 2018-10-18T00:28:58Z
Release-Tag: RELEASE.2018-10-18T00-28-58Z
Commit-ID: 3b553570459cdf8b10671105252c707ff2cf76f3
```
* Environment name and version (e.g. nginx 1.9.1): 
Elasticsearch version:
```
"version" : {
    "number" : "6.4.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "04711c2",
    "build_date" : "2018-09-26T13:34:09.098244Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
```
* Operating System and version (`uname -a`):
Ubuntu 18.04.1 LTS \n \l

**Comment by nitisht** [comment]
fixed by #6764
