### ISSUE TITLE
Docs: Admin docs for testing setup incomplete

### ISSUE THREAD

**Issue by eode** [minio/minio#6695]
In the [admin docs](https://docs.minio.io/docs/minio-admin-complete-guide.html), under section **4. Test Your Setup**, only example output is given.  It does not show example usage of the command `mc admin info <host alias>`, therefore someone doesn't know what's required to perform the test.

..of course, it becomes rather apparent in the next section, but it's still incorrect.

**Comment by harshavardhana** [comment]
Sent the fix here https://github.com/minio/mc/pull/2578 - thanks for letting us know @eode
