### ISSUE TITLE
Gateway double encryption ETag  compatibility with S3 

### ISSUE THREAD

**Issue by poornas** [minio/minio#6696]
https://github.com/minio/minio/pull/6680 fixes ETag returned by PutObject so that it is compatible with S3 Spec. However the fix is only for minio server and not for the double encryption feature(https://github.com/minio/minio/pull/6423)
## Expected Behavior

For SSE-S3 PUT object requests through minio s3 gateway running in double encryption mode, the ETag returned should be content MD5 Sum of data uploaded. Similarly for UploadPart.
## Current Behavior

Current implementation returns the encrypted content's MD5Sum as ETag
## Possible Solution

s3 gateway needs a similar fix like minio server
## Steps to Reproduce (for bugs)

1.s3cmd put /home/kris/Downloads/smallfile --server-side-encryption s3://tbucket11/obj would fail
2.
3.
4.

## Context

For compatibility with S3
## Regression
 No ( unimplemented feature)

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
Closed as fixed by #6423
