### ISSUE TITLE
Feature request to not display keys on startup

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#6697]
Not using template on purpose.

We should provide a way to suppress secret key and access key being printed to stdout.  For example, if a user uses the --quiet option today, they will not see whether an update is available or any arn they may have configured for notifications.  Should remove access keys from top level and `mc config` command, maybe something like the following:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 3 weeks ago ┃
┃ Update: Run `minio update`                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Endpoint:  http://127.0.0.1:9000
AccessKey: <redacted>
SecretKey: <redacted>
SQS ARNs:  arn:minio:sqs::1:elasticsearch

Browser Access:
http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:9000 <redacted> <redacted>
```

**Comment by harshavardhana** [comment]
`minio server --quiet` @eco-minio

**Comment by harshavardhana** [comment]
Also if `minio` is running inside a non-interactive terminal such as systemd, kubernetes, docker access/secret is not displayed

**Comment by eco-minio** [comment]
@harshavardhana systemd, k8s, docker makes sense, as per above --quiet does not satisfy when you want to see notifications regarding updates or see notification arn's.

**Comment by harshavardhana** [comment]
> @harshavardhana systemd, k8s, docker makes sense, as per above --quiet does not satisfy when you want to see notifications regarding updates or see notification arn's.

So in all situations when its not a terminal its disabled, we don't need to add more envs to disable this IMO

**Comment by kannappanr** [comment]
Closing this as answered and working as intended.
