### ISSUE TITLE
Minio Browser with canned bucket policy shows bucket list

### ISSUE THREAD

**Issue by ihamouda** [minio/minio#6701]
Setup a canned policy per bucket for a user

## Expected Behavior
When logged on as the user, expected to see only the bucket in policy listed

## Current Behavior
All buckets are listed, with the message "Not enough permissions", when clicking on other buckets

## Steps to Reproduce (for bugs)
1. create policy file
`{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"s3:GetObject",
"s3:GetBucketLocation"
],
"Effect": "Allow",
"Resource": [
"arn:aws:s3:::023960535/*",
"arn:aws:s3:::023960535"
],
"Sid": "Public"
}
]
}`

2. create policy
`mc admin policies add minio 023960535 023960535.json`
3. create user
`mc admin users add minio 023960535 UxZTWa3MIQ 023960535`
4. access from minio browser
right bucket, can list files
wrong bucket: Don't have enough permissions to access this resource

## Context
different users should not see the bucket list of other users

## Your Environment
Docker minio, RELEASE.2018-10-25T01-27-03Z
![screen shot 2018-10-25 at 1 27 20 am](https://user-images.githubusercontent.com/169142/47483222-f6a88a00-d7f5-11e8-8713-d414d33a03ee.png)
![screen shot 2018-10-25 at 1 28 34 am](https://user-images.githubusercontent.com/169142/47483223-f6a88a00-d7f5-11e8-842d-05596cc6e77d.png)

**Comment by harshavardhana** [comment]
This is as per design @ihamouda UI still lacks a bunch of things to be fully multi-user ready

**Comment by ihamouda** [comment]
@harshavardhana thank you for the quick reply
Any future plans or timelines?

**Comment by nitisht** [comment]
Closing this for now as this is the intended behaviour

**Comment by harshavardhana** [comment]
Re-opening this for some internal discussions.

**Comment by harshavardhana** [comment]
We are going to fix it, sending a fix.

**Comment by ihamouda** [comment]
thank you

**Comment by ihamouda** [comment]
@harshavardhana Any update on this

**Comment by harshavardhana** [comment]
> @harshavardhana Any update on this

I had to prioritize other work, will get to this soon.

**Comment by ihamouda** [comment]
HI @harshavardhana 
any progress on this?

**Comment by harshavardhana** [comment]
> HI @harshavardhana
> any progress on this?

No further progress yet, we will get to this soon.
