### ISSUE TITLE
Node port not opened when minio is installed using helm

### ISSUE THREAD

**Issue by CMADHANKUMAR** [minio/minio#6702]
I installed minio using helm chart like below .
helm install --set accessKey=myaccesskey,secretKey=mysecretkey stable/minio

It was successfull.

[root@kube-master-0-prodes-1539172764 madhan]# kubectl get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
good-deer-minio-795c9b457d-sbnjg                          1/1     Running   0          25s

[root@kube-master-0-prodes-1539172764 madhan]# kubectl get services
NAME                                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                           AGE
good-deer-minio                        ClusterIP      10.233.26.112   <none>        9000/TCP                                          9m

The pod deployed successfully.But, I am unable to acccess it using node port .Since the node port was not opened.

Port forwarding also not working ..

[root@kube-master-0-prodes-1539172764 madhan]# kubectl port-forward good-deer-minio-795c9b457d-sbnjg 9000:31001
Forwarding from 127.0.0.1:9000 -> 31001

it got struck like the above and i am unable to forward the port.

**Comment by nitisht** [comment]
@CMADHANKUMAR can you try 

```
helm install --set accessKey=myaccesskey,secretKey=mysecretkey,service.type=NodePort,service.nodePort=<port-no> stable/minio
```

**Comment by CMADHANKUMAR** [comment]
The below one works fine.

helm install stable/minio --set service.type=NodePort

**Comment by CMADHANKUMAR** [comment]
> helm install --set accessKey=myaccesskey,secretKey=mysecretkey,service.type=NodePort,service.nodePort=<port-no> stable/minio

This also works fine.

**Comment by CMADHANKUMAR** [comment]
Thankyou for your support !
