### ISSUE TITLE
Heal on distributed cluster not running

### ISSUE THREAD

**Issue by tnatanael** [minio/minio#6703]
I started a minio distributed cluster using this start command:

http://server{1...4}/vol{1...12}

OBS: i am using local dns managemant with Bind9, same network for all servers

Cluster is working pretty fine, im am putting and getting files with no problem!
Erasure coding is also perfectly sharding to disks in sharding groups of 16 disks, as of documentation says! Very good!

When i try to run a heal command, it starts, heal some files, and crashes saying this message:

Heal had an error -  Storage resources are insufficient for the write operation.

But storage usage is only 1% right now, all disks are mounted and working ok, with lot of free space...

Running heal with --json command, gives me strange content in the drives array, aparently its considering 60 drives instead of original 48... and saying 12 drives are offline, but, all servers and disks are online and working... this log file anexed, gives semelhant result as --json output, but is generated via MINIO_HTTP_TRACE file in server configuration...

[miniolog.txt](https://github.com/minio/minio/files/2514714/miniolog.txt)

## Expected Behavior
After and before arrays should contain 48 andpoints no 60 as stated in the log file, so 12 not existing disks offline is consistent with the error message saying the storage resources as insuficient, since sharding algorithm uses 16 disks and the last 12 are offline...

## Possible Solution
Wrong interpretation of disk numbers in some point of code, or wrong array merge or map, in after and before disks arrays...

## Steps to Reproduce (for bugs)
1. Just run heal on a cluster like that

## Context
Heal not works...

## Your Environment
* Version used (`minio version`): Lastest Binary 2018-10-24 minio and mc!!!
* Environment name and version (e.g. nginx 1.9.1): Its just a local network cluster
* Server type and version: Distributed, 4 Servers 12 disk each 10 Tb
* Operating System and version (`uname -a`): Ubuntu 18

**Comment by nitisht** [comment]
@tnatanael did you use 60 disks earlier before going to 48 disks i.e. current setup?

**Comment by tnatanael** [comment]
No! Just started a new fresh cluster as stated...

**Comment by nitisht** [comment]
thanks, let me try this locally and get back to you

**Comment by tnatanael** [comment]
Really thanks man!

**Comment by nitisht** [comment]
@tnatanael could you pls share the `/vol1/.minio.sys/format.json` file

**Comment by tnatanael** [comment]
{"version":"1","format":"xl","id":"e00dea90-f767-4039-954b-36657df12be6","xl":{"version":"3","this":"1816b559-5c53-4953-bc93-893aabbb70be","sets":[["16ce629f-c75f-4be5-817d-2d7aeed288ca","1816b559-5c53-4953-bc93-893aabbb70be","2926219c-5529-49ce-82d3-3f48214a0c50","4135d10b-133f-4d34-88e3-23e657a5e0ac","cc314598-aa17-453e-8c74-0d062b3257d4","f29fe039-dc2b-4a6c-a88a-c54ab7819ec4","2c9f4f8d-9844-4da0-9e5c-a78c412373b5","d0677591-3164-4f4e-826c-2a51e1a49573","5c7aa99b-aa27-431e-acd9-16db028e399c","b9f252e0-46d5-4bc1-9925-3ce94a7eebf0","3d2220cf-37a7-438f-8ca0-f53361f53200","e7ab6b22-7089-43d2-a3fd-999feb0afe90","a65a87c5-866a-494c-a8fe-1252d2caa8f9","9dc1c271-f138-4ef6-94d6-dbc38784dc41","5015af2d-63d6-44ba-8265-75adc6b17999","d65908c8-d71b-44cf-a42d-330fa095d94f"],["436f9e84-0be5-4e5b-a6a6-925925b3ccfb","cadcdc06-012b-4408-a05a-f981573bf1fb","cc7bd567-a54f-4358-b112-ea07f04e41b9","58a6bf21-a007-49d2-9068-d74931d7112f","4f15b590-c1af-43fd-81e6-5fb426179af2","38a55b06-a29b-404e-905c-92b7b46dd428","6ae78f85-46af-40e6-80e8-7f7969850f72","f93f715f-ef4f-4203-959c-71e47c4921b9","316a57d3-a8d8-4635-8de1-11a36ce719be","0b1db9b6-aa3f-41a5-8418-153f72cb3b4f","f1cfca31-92fa-4c67-8c81-49509d592abe","bec66a9c-6ff3-4e3f-9e9e-b54b435a6da1","662e3d95-75d2-424e-a936-01f899272ada","8bb98938-cea8-4df7-9204-90704e78fca2","bedddd73-0cc5-42f8-bdcc-c216fdedd3e2","93ccc2db-460a-4d08-bc45-0cae43b4f429"],["db8fa93b-921a-47b8-b196-9ab0ec7a518a","afdef147-f524-487b-9ec9-5d92961780a4","ff306fc9-ffc8-4121-b803-b8a1773269b9","c9190b1f-a238-408c-9327-5acb6256f95b","49f79123-2365-4039-848d-2a915760eff2","60999594-6e1e-4d1d-8b9e-f3981acca9a7","ba3e0d1f-9b1d-43bf-bcda-5135a470ed27","3d46c350-fa70-46e2-94b9-c865b5f49fe1","65251975-3b0c-48da-8b0c-96d6b3a90528","eeda9212-04b5-4fee-9af3-6af8847ac5e2","8ca0f6cf-f3c2-4284-a827-afa1f0d7862c","8e6a54c9-a589-4d58-8ccb-121dfded0e79","237c8b06-215b-4901-b0a2-f30e00e701f5","74bf7f3e-6766-4e94-b8a6-cbd5bdf30a00","c2bc6953-adb5-44ca-b363-d4375e139e2b","a94471c4-ea7e-43ae-b3ad-7d2e7d62bb08"]],"distributionAlgo":"CRCMOD"}}

**Comment by tnatanael** [comment]
3 Shards 16 each 48 total... appears to be consistent...

**Comment by nitisht** [comment]
> appears to be consistent...

Yeah. do you have any logs on Minio server side?

**Comment by tnatanael** [comment]
Dont know if this helps but my server is also returning this messages for all the 12 vols in log file

[REQUEST (*storageRESTServer).ListDirHandler-fm] [154047827.364679] [2018-10-25 11:37:53 -0300]
POST /minio/storage/v1/vol12/listdir?count=-1&dir-path=config%2Fiam%2Fsts%2F&volume=.minio.sys
Host: server2:9000
Content-Length: 0
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ2OTQwNzgyNzMsInN1YiI6IkxTSk5uM1pOIn0.OW2c0zmgXU7ITPy_5YDCu-UvoRX00D-ZiyO1FMmESUw5jUzeyexbr1ktv5YKIJaLsLVKRw8b9_68RMcCW4jDXQ
X-Minio-Time: 2018-10-25T14:37:53Z
User-Agent: Go-http-client/1.1

since this path does not exists in the cluster it appears to be related...

**Comment by tnatanael** [comment]
This trace with heal --json can also help in understanding...

type: "system" request works fine! with the correct number of disks 48
but 
type: "bucket" gets the wrong number of disks 60 saying /volX is ok but http://server1:9000/vol1 is offline
[Detailed Heal Json.txt](https://github.com/minio/minio/files/2515526/Detailed.Heal.Json.txt)

**Comment by tnatanael** [comment]
> > appears to be consistent...
> 
> Yeah. do you have any logs on Minio server side?

Posted right now all the logs that i have at the moment, i can post a complete HTTP_TRACE, but the only strange logs are those i already posted... anyway you want this complete log?

I could provite team viewer access too... if you want...

**Comment by tnatanael** [comment]
I am also on Minio Slack as `@Thiago Natanael` you can direct talk to me there, i am 100% on this issue, very worried about this...

**Comment by tnatanael** [comment]
Since each of my servers has 12 disks, i found a single bucket that have not done a complete DELETE operation, and remained in the first sharding group, consisting of the primary four disks of each server...

After digging deep into the code i found that implementation in xl-v1-healing.go:

```
// is only used by healBucket().
func checkBucketExistsInQuorum(ctx context.Context, storageDisks []StorageAPI, bucketName string) (err error) {
	var wg = &sync.WaitGroup{}

	errs := make([]error, len(storageDisks))

	// Prepare object creation in a all disks
	for index, disk := range storageDisks {
		if disk == nil {
			continue
		}
		wg.Add(1)
		go func(index int, disk StorageAPI) {
			defer wg.Done()
			_, errs[index] = disk.StatVol(bucketName)
		}(index, disk)
	}
	wg.Wait()

	readQuorum := len(storageDisks) / 2
	return reduceWriteQuorumErrs(ctx, errs, nil, readQuorum)
}

// Heals a bucket if it doesn't exist on one of the disks, additionally
// also heals the missing entries for bucket metadata files
// `policy.json, notification.xml, listeners.json`.
func (xl xlObjects) HealBucket(ctx context.Context, bucket string, dryRun bool) (
	results []madmin.HealResultItem, err error) {

	storageDisks := xl.getDisks()

	// Check if bucket doesn't exist in writeQuorum number of disks, if quorum
	// number of disks returned that bucket does not exist we quickly return
	// and do not proceed to heal.
	if err = checkBucketExistsInQuorum(ctx, storageDisks, bucket); err != nil {
		return results, err
	}

	// get write quorum for an object
	writeQuorum := len(storageDisks)/2 + 1

	// Heal bucket.
	var result madmin.HealResultItem
	result, err = healBucket(ctx, storageDisks, bucket, writeQuorum, dryRun)
	if err != nil {
		return nil, err
	}
	results = append(results, result)

	// Proceed to heal bucket metadata.
	metaResults, err := healBucketMetadata(xl, bucket, dryRun)
	results = append(results, metaResults...)
	return results, err
}
```
Maybe this implementation is checking quorum wrong way?

Read quorun calculated = 9 - Correct since read quorun depends on sharding group in distributed
The problematic Bucket was found only in the first 4 disks of each server

Error raised...

**Comment by harshavardhana** [comment]
Sending a fix @tnatanael

**Comment by tnatanael** [comment]
Hy guys, @harshavardhana  i tested your fix right now, and the problem persists...

![image](https://user-images.githubusercontent.com/11818318/47564472-88e68600-d8fb-11e8-9036-9b68afd7fa31.png)

I found that removing a partially existing bucket manually from the disks, solved the heal problem...

**Comment by tnatanael** [comment]
I realized that the mc admin heal --json output was correct now! The after and before arrays are showing exact the number of disks and all online... So, the fix solved it, but not the heal problem with quorum...

**Comment by harshavardhana** [comment]
> I realized that the mc admin heal --json output was correct now! The after and before arrays are showing exact the number of disks and all online... So, the fix solved it, but not the heal problem with quorum...

Will take a look that's a different problem @tnatanael

**Comment by tnatanael** [comment]
Thanks a lot @harshavardhana ill wait...
