### ISSUE TITLE
HTTP2 support is broken / not implemented

### ISSUE THREAD

**Issue by leitzler** [minio/minio#6704]
## Expected Behavior
Improvement suggestion: minio should support HTTP2.

## Current Behavior
Major browsers as well as curl supports both HTTP/1.1 as well as HTTP2, but due to a bug in `cmd/http/server.go`, minio will never serve HTTP2 if the client support HTTP/1.1.

If a client would only support HTTP2, minio terminate all requests without response while logging `Error: malformed HTTP request from n.n.n.n:nnnn" 

## Possible Solution
Make sure that the server doesn't imply that is supports HTTP2 (as it does right now). I'll submit a PR for this step. This must be done regardless of if HTTP2 support is added.

When (if) HTTP2 support is added, make sure that `tls.Config.NextProtos` is set to `[]string{"h2", "http/1.1"}` instead of `[]string{"http/1.1", "h2"}` since the list is ordered by preference.

## Steps to Reproduce (for bugs)
Create a request using curl with verbose output to see that HTTP2 isn't used:
```bash
$ curl -v https://minio-host/
[...]
* ALPN, offering h2
* ALPN, offering http/1.1
[...]
* ALPN, server accepted to use http/1.1
[...]
GET / HTTP/1.1
[...]
```

You could also try with a minimal H2 client written in Go to reproduce the incorrect handling of H2 requests:
```go
package main

import (
	"crypto/tls"
	"log"
	"net/http"

	"golang.org/x/net/http2"
)

func main() {
	c := &http.Client{
		Transport: &http2.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
				NextProtos:         []string{"h2"},
			},
		},
	}

	_, err := c.Get("https://127.0.0.1:9000")
	if err != nil {
		log.Fatal(err)
	}
}
```
```bash
$ go run main.go
2018/10/25 14:11:00 Get https://127.0.0.1:9000: unexpected EOF
```
```
API: SYSTEM()
Time: 14:11:00 CEST 10/25/2018
Error: malformed HTTP request from 127.0.0.1:9000
       remoteAddr=127.0.0.1:44256, localAddr: 127.0.0.1:9000
```

## Your Environment

* Version used (`minio version`): `latest`
* Environment name and version (e.g. nginx 1.9.1): -
* Server type and version: Linux / macOS
* Operating System and version (`uname -a`): `Linux hostname 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
This is simple to fix to get H2 support - we don't need to remove it @leitzler

**Comment by leitzler** [comment]
Great! I didn't know if it was a prioritized feature. Looking forward to a fix :+1:
