### ISSUE TITLE
Files with a % or + sign fail at certain points using Amazon AWS S3 Java API

### ISSUE THREAD

**Issue by mwiest** [minio/minio#6706]
If some files have % sign in the filename like so: Blabla_50%.jpg. 
Putting them (using Amazon S3 Java API) worked fine, but now I want to s3.listObjects() using Java, I'll get a URLDecoder exception saying `.j` is not a valid hex code. Which it is not, but there must be something wrong with what is expected, etc. I guess it's something that Amazon S3 is handling differently than Minio.

Additionally I found some more issues with + vs. %20 when s3.getObjectMetadata(), also it seems to expect one and receive the other.
In one case, the original file imported had a + sign in the name, the minio web-view shows it the same, and AWS seems to request it with a %20 instead (excerpt from log).

`2018-10-25 14:12:24,754 DEBUG [com.amazonaws.auth.AWS4Signer] AWS4 Canonical Request: '"HEAD
/marketing-upload/es/2016BlackFriday%20CyberMonday-50-SPA-Eblast.png`

## Expected Behavior

I expect that when I write a file with a certain name, and it is accepted, I can act on it (list of retrieve metadata, or whatever) using the same name.

## Current Behavior

In case of a % in the name, an URLDecoder exception is thrown when .listObject() and in case of a + in the name, a 404 not found is produced by HEAD internally inside Amazon S3 library when .getObjectMetadata().

## Steps to Reproduce (for bugs)

1. Upload file with either % or + sign from Linux using Java Amazon AWS S3 library (probably other means, too)
2. Call s3.listObjects() on the bucket (fails in case of % sign in name).
3. Call s3.getObjectMetadata() on the bucket and key name (fails in case of + sign in name)

## Context

I was importing existing files from a file system and so, file names include all kinds of characters.

## Your Environment

* Version used (`minio version`): 2018-10-18T00:28:58Z
* Environment: Standalone installation
* Operating System and version (`uname -a`): Linux xxx 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@mwiest Thanks for filing the issue. We will send in a PR to fix this issue soon.

**Comment by sinhaashish** [comment]
@mwiest  I tried uploading with AWS `Java Amazon AWS S3` with file name as `test_1%.jpg' . Then i used  minio java to list object and its working fine.
```
 Item <?xml version="1.0"?><Contents xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><ETag>"5323fcbec2faa15f4ab987a98288537c"</ETag><Key>test_1%.jpg</Key><LastModified>2018-10-26T09:04:46.000Z</LastModified><Size>302633</Size><StorageClass>STANDARD</StorageClass></Contents>
Fri Oct 26 14:34:46 IST 2018, 5, test_1%.jpg
 Item <?xml version="1.0"?><Contents xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><ETag>"081d4b4b0b6d7570090c24e7fbbb2675"</ETag><Key>test_50%.jpg</Key><LastModified>2018-10-26T06:35:05.000Z</LastModified><Size>371077</Size><StorageClass>STANDARD</StorageClass></Contents>
Fri Oct 26 12:05:05 IST 2018, 5, test_50%.jpg
 Item <?xml version="1.0"?><Contents xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><ETag>"5323fcbec2faa15f4ab987a98288537c"</ETag><Key>wall+paper.jpg</Key><LastModified>2018-10-26T09:03:30.000Z</LastModified><Size>302633</Size><StorageClass>STANDARD</StorageClass></Contents>
Fri Oct 26 14:33:30 IST 2018, 5, wall+paper.jpg
```

 Can you tell which version of minio java client you are using ?

**Comment by kannappanr** [comment]
@sinhaashish If I understand correctly, he does not use `minio-java`. He used `Aws-Java` throughout. He was able to do `putobject`, which worked for you also. then he used `s3.listObjects()`, which failed for him.

He is also explaining another issue with `s3.getObjectMetadata()`. Overall, I think he is using `minio`  version `2018-10-18T00:28:58Z` as the server and `Aws-SDK-Java` as the client SDK.

@mwiest Please feel free to correct if what I have stated is wrong.

**Comment by sinhaashish** [comment]
@kannappanr  @mwiest  I ran the below code against Minio server.
```
AWSCredentials credentials = new BasicAWSCredentials("minio", "minio123");
        ClientConfiguration clientConfiguration = new ClientConfiguration().withProtocol(false ? Protocol.HTTPS : Protocol.HTTP)
                .withUserAgentPrefix("s3browser")
                .withSignerOverride("S3SignerType");
        AmazonS3Client s3Client = new AmazonS3Client(credentials, clientConfiguration);
        s3Client.setS3ClientOptions(S3ClientOptions.builder()
                .setPathStyleAccess(true)
                .disableChunkedEncoding()
                .build());
        s3Client.setEndpoint("http://127.0.0.1:9000");
        try {
            s3Client.putObject("test", "test_1%.jpg", new File("/home/ashish/Downloads/test_1%.jpg"));
        } catch (AmazonServiceException e) {
            System.err.println(e.getErrorMessage());
            System.exit(1);
        }
        System.out.println(" Uploaded ");
        List<Bucket> buckets = s3Client.listBuckets();
        System.out.println("Your Buckets  are:");
        ListObjectsV2Result result = s3Client.listObjectsV2("test");
        List<S3ObjectSummary> objects = result.getObjectSummaries();
        for (S3ObjectSummary os: objects) {
            System.out.println("* " + os.getKey());
        }
```
And i got the below Output
```
 Uploaded 
Your Buckets  are:
* test_1%.jpg
* wall+paper.jpg
```
POM 
```
<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.437</version>
</dependency>
```

Do confirm if i  have missed something because its working for me.

**Comment by kannappanr** [comment]
@sinhaashish Can you please try 
```
Call s3.listObjects() on the bucket (fails in case of % sign in name).
Call s3.getObjectMetadata() on the bucket and key name (fails in case of + sign in name)
```

Maybe only these two calls are failing.

**Comment by john-hanley** [comment]
It is important that the file names (S3 object keys) be correctly encoded before uploading to S3.

Storing "Blabla_50%.jpg" as the "key" name is NOT correct. You must encode all special characters and % is a special character. In the URL world the % character is the start of an encoding.

Consult the AWS S3 documentation for "Characters That Might Require Special Handling" and the section "Characters to Avoid":

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

Some API libraries will do the encoding for you, and this is why they will work with this key name example.

**Comment by sinhaashish** [comment]
@mwiest  : There is no issue on minio side. AWS JAVA SDK has introduced `automatic url decoding` . Refer https://github.com/aws/aws-sdk-java/issues/1797 . You can set `shouldSDKDecodeResponse` to false and you will get the correct output.

**Comment by nitisht** [comment]
@mwiest closing this for now as this looks like related to aws-sdk-java. Feel free to reopen / get back to us if there are any further issues.
