### ISSUE TITLE
`s3select` package needs to use different file segment for parquet

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#6714]
Currently `s3select` uses only one input stream as data source.  However this is not fit to handle parquet file support.  To handle parquet files, its required to read content from many different offset/length sequentially and/or in parallel.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
I am assuming @balamurugana you are working on this, moving the assignment.

**Comment by harshavardhana** [comment]
Fixed by #7023
