### ISSUE TITLE
feature request: Support conditional long poll requests

### ISSUE THREAD

**Issue by vlcinsky** [minio/minio#6722]
## Expected Behavior
To get an object form a bucket, conditional request can be done today using `If-Modified-Since` and `If-None-Match`. This immediately returns the object (in case there is new one) or 304 if no change present.

Adding new parameter `long-poll-timeout` (default 0, maximal acceptable value 20seconds) should result in either returning the new object immediately or waiting up to `long-poll-timeout` time for possible resource update.

## Current Behavior
Currently conditional request is supported but the response is returned immediately and there is no waiting for possible update.

## Possible Solution
If given request condition is not met (no update seen), the service could subscribe to resource update and if it gets updated, return immediately. The waiting shall be limited in time.

Max value of 20 seconds follows value used in AWS SQS long polling (`aws sqs receive-message` with `WaitTimeSeconds` parameter). Many web servers and HTTP clients have timeout set to 30 seconds so 20 seconds is short enough to prevent such timeout.

## Context
This feature would be nice but shall be considered carefully not to cause stability issues. Stability is more important than this feature.

**Comment by harshavardhana** [comment]
We can only implement such features if AWS S3 implemented such features.

**Comment by vlcinsky** [comment]
Thanks @harshavardhana . This is very clear answer (good to keep project scope well defined).
