### ISSUE TITLE
Yet another bug report in Swarm mode

### ISSUE THREAD

**Issue by kyberorg** [minio/minio#6723]
## Expected Behavior

Working Minio, which is accessible from Internet on ports 9001-9004.

## Current Behavior

Stack is deployed, but services are restarting every minute with "Unhealthy container" error

## Possible Solution

Add logs to debug issue

## Steps to Reproduce (for bugs)

1. Install Swarm with 4 nodes 
2. Create secrets within swarm
3. Follow https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html and 
Add labels to nodes `docker node update --label-add minio1=true <DOCKER-NODE1>` and so on...
4. deploy stack with given compose file (https://github.com/minio/minio/blob/master/docs/orchestration/docker-swarm/docker-compose-secrets.yaml?raw=true)

## Context

I followed minio docs for swarm nodes (https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html)

## Regression

I have container setup with docker label: latest.

## Your Environment

* Version used (`minio version`): docker tag: latest
* Environment name and version (e.g. nginx 1.9.1): docker 18.06.1-ce, swarm mode.
* Server type and version:  4 cloud instances
* Operating System and version (`uname -a`): Linux AmEire 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: No link as currently empty swarm

**Comment by nitisht** [comment]
@kyberorg we'll take a look

**Comment by nitisht** [comment]
@kyberorg I tried to replicate this locally, but seems to work with latest release: `RELEASE.2018-11-06T01-01-02Z`, can you try with release tag `RELEASE.2018-11-06T01-01-02Z`

```
$ docker stack ps minio_stack
ID                  NAME                   IMAGE                                      NODE                DESIRED STATE       CURRENT STATE           ERROR
       PORTS
ouxqrs2k4yb8        minio_stack_minio3.1   minio/minio:RELEASE.2018-11-06T01-01-02Z   node3               Running             Running 3 minutes ago

rck5ykqv3unb        minio_stack_minio2.1   minio/minio:RELEASE.2018-11-06T01-01-02Z   node2               Running             Running 3 minutes ago

ffurbe9d626d        minio_stack_minio1.1   minio/minio:RELEASE.2018-11-06T01-01-02Z   node1               Running             Running 3 minutes ago

iqg5efqbogsn        minio_stack_minio4.1   minio/minio:RELEASE.2018-11-06T01-01-02Z   node4               Running             Running 3 minutes ago

```

**Comment by nitisht** [comment]
@kyberorg closing this for now as this seems to be working, feel free to reopen/get back to us if there are further issues
