### ISSUE TITLE
why minio can not see the file which I upload the file into the data dir by hand in distributed mode

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6727]
In standalone mode, I upload the file into the data dir, minio can check auto and see on the browser. But in distributed mode, I upload the file the same, minio can not check auto and can not see on the browser. Why ? We now have the requirement that is We use the standalone mode before but now we want to use distributed mode and want to migrate the data.  How to solve this ?

**Comment by nitisht** [comment]
Please use mc mirror (ref: https://docs.minio.io/docs/minio-client-complete-guide.html#mirror) to move data from one Minio instance to another. 

Minio distributed mode will not detect any files uploaded directly to the drives. Moreover, it is generally not recommended to access / edit files directly on the drives being used by Minio server. It may lead to unintended problems.

**Comment by kellenchen** [comment]
I use mc mirror command and execute success but can not see the file ....

**Comment by nitisht** [comment]
how did you use the command, can you please elaborate

**Comment by kellenchen** [comment]
./mc mirror 111/ minio1/images   

I use ./mc cp -r ~/111 minio1/images the same.

**Comment by kellenchen** [comment]
111 is a dir I create on the host.

**Comment by nitisht** [comment]
you need to use mirror from one Minio instance to another. For example if `minio1` and `minio2` are aliases for two instances (standalone and distributed), use 

`./mc mirror minio1/ minio2/`

**Comment by kellenchen** [comment]
If the minio1 and minio2 are two different hosts. How to write the command ?

**Comment by nitisht** [comment]
add the aliases to mc like `mc config host add minio1 http://IP:Port AccessKey SecretKey` and `mc config host add minio2 http://IP:Port AccessKey SecretKey`

Then use `./mc mirror minio1/ minio2/`

**Comment by kellenchen** [comment]
thanks. I try try

**Comment by kellenchen** [comment]
solved the problem @nitisht
