### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6728]
RROR Invalid command line arguments: mixed style endpoints are not supported.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide

**Comment by kellenchen** [comment]
**All the nodes running distributed Minio need to be in a homogeneous environment, i.e. same operating system, same number of disks and same interconnects.**

I ssh the host and execute the start command. The minio use the sshUser and sshPassword I login in ?

and it requires the sshUser and sshPassword same on every host ?

**Comment by nitisht** [comment]
how did you start the Minio server @kellenchen

**Comment by kellenchen** [comment]
export MINIO_ACCESS_KEY=xxx
export MINIO_SECRET_KEY=xxxx
nohup ./minio --config-dir ~/minio_tenant_config/tenant1 server --address :10620 http://192.168.74.x/app/minio_data/tenant1 192.168.75.x/app/minio_data/tenant1 http://192.168.57.x/app/minio_data/tenant1 http://192.168.59.x/app/minio_data/tenant1 &

**Comment by kellenchen** [comment]
The above four hosts has two kinds of disk as below. One is /dev/xvde and the other is /dev/vdb. But both of them all mounted on /app. Does it matter ? And the user is cloud and the other one is ctgcloud. Does it matter ?

[cloud@aep_cloud_0002 ~]$ df -h
文件系统        容量  已用  可用 已用% 挂载点
/dev/xvda2       36G  5.7G   28G   17% /
devtmpfs         63G     0   63G    0% /dev
tmpfs            63G     0   63G    0% /dev/shm
tmpfs            63G 1009M   62G    2% /run
tmpfs            63G     0   63G    0% /sys/fs/cgroup
**/dev/xvde       900G   16G  884G    2% /app**



[ctgcloud@aep-sz-zk-0001 app]$ df -h
文件系统        容量  已用  可用 已用% 挂载点
/dev/vda2        36G   21G   14G   61% /
devtmpfs         32G     0   32G    0% /dev
tmpfs            32G     0   32G    0% /dev/shm
tmpfs            32G  177M   32G    1% /run
tmpfs            32G     0   32G    0% /sys/fs/cgroup
**/dev/vdb        600G   23G  578G    4% /app**
tmpfs           6.3G     0  6.3G    0% /run/user/10000
tmpfs           6.3G     0  6.3G    0% /run/user/520
tmpfs           6.3G     0  6.3G    0% /run/user/0
tmpfs           6.3G     0  6.3G    0% /run/user/10013

**Comment by kellenchen** [comment]
@nitisht

**Comment by nitisht** [comment]
please use 

```
./minio --config-dir ~/minio_tenant_config/tenant1 server --address :10620 http://192.168.74.x/app/minio_data/tenant1 http://192.168.75.x/app/minio_data/tenant1 http://192.168.57.x/app/minio_data/tenant1 http://192.168.59.x/app/minio_data/tenant1
```

**Comment by kellenchen** [comment]
it is not the reason for remove nohup. When I use the command as you give, it print the same error.

**Comment by harshavardhana** [comment]
You are missing http:// 

```
export MINIO_ACCESS_KEY=xxx
export MINIO_SECRET_KEY=xxxx
nohup ./minio --config-dir ~/minio_tenant_config/tenant1 server --address :10620 http://192.168.74.x/app/minio_data/tenant1 http://192.168.75.x/app/minio_data/tenant1 http://192.168.57.x/app/minio_data/tenant1 http://192.168.59.x/app/minio_data/tenant1
```

**Comment by kellenchen** [comment]
em...I add http:// and two hosts startup success and two another still print below error.

Waiting for a minimum of 2 disks to come online (elapsed 1m0s)

Waiting for a minimum of 2 disks to come online (elapsed 2m0s)

Waiting for a minimum of 2 disks to come online (elapsed 3m0s)

Waiting for a minimum of 2 disks to come online (elapsed 4m0s)

and they can ping success for each other.

**Comment by kellenchen** [comment]
firewall problem . solved.
