### ISSUE TITLE
Access and secret keys not displayed (not generated?) when running in Docker

### ISSUE THREAD

**Issue by dmolesUC** [minio/minio#6730]
Running in bash on macOS mojave, following the [quickstart instructions](https://docs.minio.io/docs/minio-docker-quickstart-guide):

```
$ docker run -p 9000:9000 --name minio1   -v /Users/david/Work/minio-docker/data:/data   -v /Users/david/Work/minio-docker/config:/root/.minio   minio/minio server /data
```

(The `minio-docker` directory exists, the `config` and `data` didn't till they were created by Docker.)

## Expected Behavior

Per #6697, I expected to see 

```
AccessKey: <redacted>
SecretKey: <redacted>
```

## Current Behavior

I just get:

```
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

There's no files in either `config` or `data`, just the following directory tree in `config`:

```
$ tree config
config
└── certs
    └── CAs
```

The service seems to be running, though, as the login page looks fine.

**Comment by harshavardhana** [comment]
yes, this is on purpose @dmolesUC3 you need to run in `docker -it` to see the keys. Docker logs by default are logged and scraped. Displaying keys is a security issue so we went with this approach.

**Comment by dmolesUC** [comment]
@harshavardhana That makes sense. Maybe a note to that effect could be added to the quickstart instructions?

**Comment by kannappanr** [comment]
@dmolesUC3 We will fix the documentation to reflect this change.

**Comment by ctyjrsy** [comment]
If you happen to have an unfortunate experience of not reading how to pass in key and secret when starting minio docker container, here is your quick solution

docker exec -it <CONTAINER ID> sh
data/.minio.sys/config/config.json
