### ISSUE TITLE
How to add event for all bucket ?

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6732]
./mc events add myminio1/images arn:minio:sqs::1:mysql

this is the add event command. How to add event for all buckets which are not created now ?

**Comment by nitisht** [comment]
@kellenchen you can't add events for all buckets in one go. You need to add events one by one, after buckets are created. 

Also, feel free to join us on Slack https://slack.minio.io for further such questions

**Comment by kellenchen** [comment]
sorry..I can not open the url..

**Comment by kellenchen** [comment]
can java api to add event ? or only can use mc command ?

**Comment by nitisht** [comment]
> sorry..I can not open the url..

what is the problem? It works for me..

**Comment by kellenchen** [comment]
em...I don't know. I think it is the network problem for the url's server is not in china. I opened the url and join the minio slack in the afternoon. But sometimes can open and sometimes can not open.

**Comment by nitisht** [comment]
I see, now that you joined, lets continue discussion there. Closing this issue as answered
