### ISSUE TITLE
How to forbid the LIST command in the Minio server settings via the S3 API?

### ISSUE THREAD

**Issue by pospelov-v** [minio/minio#6734]
How to forbid the LIST command in the Minio server settings via the S3 API?

**Comment by harshavardhana** [comment]
Please explain a more use case here, the issue template is not used and the issue not descriptive closing for now.

**Comment by pospelov-v** [comment]
We use minio as an S3 storage of custom images (for example, account avatars).
Our site has two frontend.

Total 3 VPS:
1) frontend of our site
2) frontend of our site
3) "Minio" server that stores pictures and gives them to users of both fronts.

We decided to do it this way - we created one public bucket, all the pictures were put into it.

Now it is necessary that the users of our fronts can only see their pictures and cannot see the pictures of neighboring accounts.

To do this, must be forbid listing of files on the server side minio.

Thus it turns out that it is impossible to get a list of files in the bucket, and if the file name is unknown, it means that the user will not be able to open the file.
