### ISSUE TITLE
HTTP Host header strictly require whitespace

### ISSUE THREAD

**Issue by Dimentium** [minio/minio#6741]
In some latest releases Minio strictly require whitespace in HTTP Host between colon and value.

## Expected Behavior (work in RELEASE.2018-08-02T23-11-36Z)
```
dkuser@dk-ubuntu-18:~$ minio version
Version: 2018-08-02T23:11:36Z
Release-Tag: RELEASE.2018-08-02T23-11-36Z
Commit-ID: a091b1a3eefbaea07499bef9a5462280ec9d2a7a

dkuser@dk-ubuntu-18:~$ curl -i -H "Host: dk-ubuntu-18:9000" http://dk-ubuntu-18:9000
HTTP/1.0 403 Forbidden <- its OK

dkuser@dk-ubuntu-18:~$ curl -i -H "Host:dk-ubuntu-18:9000" http://dk-ubuntu-18:9000
HTTP/1.0 403 Forbidden <- its OK
```

## Current Behavior (broken in some latest releases)
```
dkuser@dk-ubuntu-18:~$ minio version
Version: 2018-10-25T01:27:03Z
Release-Tag: RELEASE.2018-10-25T01-27-03Z
Commit-ID: bf66e9a529fed3d6c460bcdbbd0a60bc167866a4

dkuser@dk-ubuntu-18:~$ curl -i -H "Host: dk-ubuntu-18:9000" http://dk-ubuntu-18:9000
HTTP/1.1 403 Forbidden <- its OK

dkuser@dk-ubuntu-18:~$ curl -i -H "Host:dk-ubuntu-18:9000" http://dk-ubuntu-18:9000
HTTP/1.0 400 Bad Request <- its unexpected
```

## Possible Solution
in RFC there are no strictly requirements for whitespace in header.
other headers except Host correctly accepts both variants (with and without whitespace)

## Context
i bumped with this issue because my script stopped to work after minio update.
some checks lighted this behaviour of minio.
its not a big problem to fix my script, but its an unexpected case for minio users.

**Comment by harshavardhana** [comment]
Thanks we will fix this behavior.
