### ISSUE TITLE
Can't start minio on redhat 5.5 server

### ISSUE THREAD

**Issue by meljai** [minio/minio#6746]
I try to start minio on a "Red Hat Enterprise Linux Server release 5.5 (Tikanga)" server with the flowing command "/opt/minio/bin/minio server /opt/minio/data" but I got this error "runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed
 runtime stack:
runtime.throw(0x159f255, 0x17)
        /opt/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x1562fa909d9df300, 0xc400000000)
        /opt/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /opt/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /opt/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /opt/go/src/runtime/proc.go:1193 +0x76
 goroutine 1 [runnable, locked to thread]:
github.com/minio/minio/vendor/github.com/fatih/structs.init()
        <autogenerated>:1 +0x103
 goroutine 18 [chan receive]:
github.com/minio/minio/cmd/logger.(*logOnceType).cleanupRoutine(0xc420094e90)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logonce.go:60 +0x60
created by github.com/minio/minio/cmd/logger.newLogOnceType
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logonce.go:71 +0x78
 goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /opt/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /opt/go/src/os/signal/signal_unix.go:28 +0x41".

Any suggestions ?

**Comment by vadmeste** [comment]
@meljai your distribution is old, Golang dropped support of RHEL 5.x long time ago. Please update to the most recent RHEL version.
