### ISSUE TITLE
Setup a proxy and reject all DELETE http requests without modifying minio code

### ISSUE THREAD

**Issue by maxozerov** [minio/minio#6758]
_Originally posted by @harshavardhana in https://github.com/minio/minio/issues/5431#issuecomment-359030797_

**Comment by maxozerov** [comment]
You can not setup a proxy and reject all DELETE http requests.
Example for Delete some object in bucket

- Request Method: POST
- Request URL: https://minio.server-name/minio/webrpc
- Authorization: Bearer
- Content-Type: application/json

Request-Payload:
```
{"id":1,"jsonrpc":"2.0","params":{"bucketName":"test-buckets","objects":["kit.ico"]},"method":"Web.RemoveObject"}
```
So, it's not have any DELETE http requests - it's POST Request to *minio/webrpc* and contain json (Request-Payload).

**Comment by maxozerov** [comment]
So, if reject DELETE headers not help...  How 'Deny Delete Selected Objects from Minio Browser'. 
Maybe Change bucket policy - help with it?

Thanks.

**Comment by maxozerov** [comment]
'Deny Delete Selected Objects from Minio Browser' - maybe bucket-policy help with it.
So, i'm closing issue - because not have any info. If  bucket-policy will not take effect - create new Issue.

**Comment by harshavardhana** [comment]
@maxozerov you can disable browser MINIO_BROWSER=off and reject DELETE on the proxy should disable everything that you want.
