### ISSUE TITLE
Use Minio web application as interface for Amazon S3?

### ISSUE THREAD

**Issue by wpuckering** [minio/minio#6759]
Is it somehow supported to use the Minio web application as an interface to Amazon S3? I was thinking that since Minio has API compatibility with S3 that this should be possible? I don't want to use Minio as a storage backend, I would like to use S3, but it would be pretty cool to be able to use the Minio frontend.

**Comment by harshavardhana** [comment]
have you seen? https://github.com/minio/minio/blob/master/docs/gateway/s3.md

**Comment by kannappanr** [comment]
@wpuckering Closing this issue as answered. Please feel free to re-open the issue, if you feel otherwise.
