### ISSUE TITLE
Config.json not generated by itself | How to set minio credentials manually

### ISSUE THREAD

**Issue by mvijayran** [minio/minio#6762]
## Expected Behavior
config.json file should be generated by itself  with auto generated access, secret key and other parameters, when first time minio server is started.

## Current Behavior
config.json file is not getting generated when server is starting and access key and secret key is not getting printed while checking minio status. 

I was trying to setup minio on CentOS Linux release 7.0.1406 (Core) and i have used below link to setup minio server but config.json file was not generated automatically in defined folder when server was started for the first time.
So when i am trying to login to server through browser, at that time i don't have auto generated minio credentials and even if i am trying to set custom credentials through environment variables then those are also not working. Even credentials are not getting printed when we checked for minio server running status.
This issue i have faced with Centos (above version) and Ubuntu 16.04.
Please suggest the way, how can i set minio custom credentials.  

These are the links :
https://www.centosblog.com/install-configure-minio-object-storage-server-centos-linux/
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04

## Your Environment
* Version used  : latest minio version
* Operating System and version (`uname -a`):  CentOS Linux release 7.0.1406 (Core)

**Comment by nitisht** [comment]
@mvijayran 

> config.json file is not getting generated when server is starting and access key and secret key is not getting printed while checking minio status.

Config.json has now moved to another location https://docs.minio.io/docs/minio-server-configuration-guide.html and it is generally not recommended to edit the config file manually. 

Also, if you're running with Docker, Minio will not display the autogenerated keys unless you start the container with the -it(interactive TTY) argument. Generally, as it is not recommended to use autogenerated keys with containers. 

You can set custom credentials using `MINO_ACCESS_KEY` and `MINIO_SECRET_KEY` environment variables.

**Comment by harshavardhana** [comment]
config.json is now not generated as part of users home directory, it is generated only in FS mode as part of the backend it can be generally found at 

```
/mnt/export/.minio.sys/config/config.json
```

But it shouldn't be touched or edited directly through backend but instead follow the following documentation https://docs.minio.io/docs/minio-server-configuration-guide.html 

> The default configuration directory is ${HOME}/.minio. Till the release RELEASE.2018-08-02T23-11-36Z, Minio server configuration file (config.json) was stored in the configuration directory. However for releases beyond RELEASE.2018-08-18T03-49-57Z, the configuration file (only), has been migrated to the storage back-end (storage back-end is the directory passed to Minio server while starting the server).

Addition to this we also disabled printing "access/secret" keys to non-terminal environments i.e either if you are running in systemd service, docker and kubernetes. This is to ensure security, i.e your credentials are not logged into services which capture the logs for active running servers. 

Another reminder is that, please use our documentation at https://docs.minio.io for updated documentation for installation and configuration of Minio. 

Following links are not updated with the latest changes, so should be considered stale at this moment

> https://www.centosblog.com/install-configure-minio-object-storage-server-centos-linux/
> https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04

**Comment by kannappanr** [comment]
@mvijayran Closing this issue as answered. Please feel free to reach out to us if you have other questions.

**Comment by mvijayran** [comment]
Thanks for quick response it solved my issue.

**Comment by jaydenpang** [comment]
Hi there, is there a way to change Minio's access key and secret access key from the command line? I am not using Docker for mine.

**Comment by kannappanr** [comment]
If you are using standalone mode and are not using environment variables `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` then you can use `mc admin config get myminio > /tmp/config.json` to get `config.json` from the server. Then use `cat /tmp/config.json | mc admin config set myminio` to set the credential

**Comment by jaydenpang** [comment]
@kannappanr worked perfectly. Thanks!

**Comment by Comolli** [comment]
thanks god，i love u so much!!!
