### ISSUE TITLE
Notification still be inserted to postgresql after remove events from a bucket.

### ISSUE THREAD

**Issue by huayuanzzb** [minio/minio#6763]
Notification still be inserted to postgresql after remove events from a bucket.

## Expected Behavior
Notification should not be sent to postgresql after remove events from a bucket.

## Current Behavior
When I remove the events, `mc` command tell me it works successfully.
However, the notifications still be inserted into postgresql.

the remove command is 
```
root@localhost:~# mc events remove myminio/test_bucket arn:minio:sqs::1:postgresql
Successfully removed arn:minio:sqs::1:postgresql
root@localhost:~# mc events list myminio/test_bucket
root@localhost:~#
```

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. add notification in config.json on minio server
```
                "postgresql": {
                        "1": {
                                "enable": true,
                                "format": "access",
                                "connectionString": "sslmode=disable",
                                "table": "bucketevents",
                                "host": "192.168.192.77",
                                "port": "5432",
                                "user": "xxxxxx",
                                "password": "xxxxxx",
                                "database": "xxxxx"
                        }
                }
```
2. add events on a bucket
```
root@localhost: ~# mc events add myminio/test_bucket arn:minio:sqs::1:postgresql 
Successfully added arn:minio:sqs::1:postgresql
```

After above step, I can find the notification had been inserted into postgresql. So it woks fine unit now.
When I remove the events, `mc` command tell me it works successfully.
However, the notifications still be inserted into postgresql.

## Context
I want to do a quickly copy for files stored on minio from a datacenter to another. 

I add all events on a bucket at first time, but actually only put and delete event are needed. So I want to remove the events that I added the first time, and then rebuild one that only for put and delete.

## Regression
No

## Your Environment
* minio version: 2018-05-11T00:29:24Z
* mc version: 2018-04-28T00:08:20Z
* OS version: Ubuntu 16.04

**Comment by nitisht** [comment]
> minio version: 2018-05-11T00:29:24Z

@huayuanzzb we have made fixes to the notification system in recent releases. Can you please try the latest release and let us know

**Comment by harshavardhana** [comment]
This was already fixed in our latest release @huayuanzzb

**Comment by harshavardhana** [comment]
PR #6082 fixed an issue #6053

**Comment by harshavardhana** [comment]
Fixed in release RELEASE.2018-08-25T01-56-38Z

**Comment by huayuanzzb** [comment]
Guys, thanks for your help.
@nitisht The latest version works fine.
