### ISSUE TITLE
Not support mc admin policies and mc admin users command 

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6765]
**[root@localhost ~]# ./mc admin -h**
NAME:
  mc admin - Manage Minio servers

USAGE:
  mc admin COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  service      Stop, restart or get status of Minio server
  info         Display Minio server information
  credentials  Change server access and secret keys
  config       Manage configuration file
  heal         Heal disks, buckets and objects on Minio server

**[root@localhost ~]# ./minio version**
Version: 2018-10-06T00:15:16Z
Release-Tag: RELEASE.2018-10-06T00-15-16Z
Commit-ID: 66d911653f17b9b180493e3e21c6131170741dcf

this doc describe policy and user command. why I can not found them on my computer.

https://docs.minio.io/docs/minio-admin-complete-guide.html#policies

**Comment by kannappanr** [comment]
@kellenchen The version of `mc` that you are using does not have the support for that `command`. Can you please try the latest release? https://dl.minio.io/server/minio/release/linux-amd64/minio .

**Comment by kellenchen** [comment]
[root@localhost ~]# ./mc version
Version: 2018-09-26T00:42:43Z
Release-tag: RELEASE.2018-09-26T00-42-43Z
Commit-id: 87f7e65c4c837c8886bf2dd8800c445983b36187


this is my mc version. It is the mc version not support or the minio version not support ? the link you give is for minio download

**Comment by nitisht** [comment]
Please try this https://dl.minio.io/client/mc/release/linux-amd64/mc

**Comment by kellenchen** [comment]
if I use the new mc version, the minio config I use mc before is apply now ? Does it has any influence ?

**Comment by nitisht** [comment]
>  Does it has any influence ?

No, you can try creating policies with this mc version

**Comment by kellenchen** [comment]
OK. I try try

**Comment by kannappanr** [comment]
@kellenchen Sorry, yes I pasted link to `minio` instead of `mc`

**Comment by kellenchen** [comment]
It doesn't  matter. It works now for the new mc version. @kannappanr
