### ISSUE TITLE
mc admin users list not support

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6767]
[root@localhost ~]# ./mc admin users list myminio1
**mc: <ERROR> Cannot list user sio: unsupported version**
[root@localhost ~]# ./mc admin users -h
NAME:
  mc admin users - Manage regular users

USAGE:
  mc admin users COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  add      Add new users
  policy   Set policy for user
  disable  Disable users
  enable   Enable users
  remove   Remove users
  **list     List all users**

FLAGS:
  --config-folder value, -C value  Path to configuration folder. (default: "/root/.mc")

**Comment by kellenchen** [comment]
mc admin users add myminio newuser newuser123 getonly  

After execute the above command successfully, I can not use the newuser/newuser123 to login in the minio browser. why ?

**Comment by kannappanr** [comment]
@kellenchen I tried `$ mc admin users add myminio newuser1 newuser123 readonly
Added used `newuser1` successfully.
`
trying `mc admin users add myminio newuser2 newuser123 getonly
mc: <ERROR> Cannot set user policy for new user The canned policy does not exist.
`

Also, I was able to login to the browser using `newuser1` . Listing of added users also worked for me.

I am using the latest released `minio` and `mc`

**Comment by kellenchen** [comment]
[root@localhost ~]# ./mc version
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

**Comment by kellenchen** [comment]
[root@localhost ~]# ./mc admin policies add myminio1 getonly getonly.json
Added policy `getonly` successfully.
[root@localhost ~]# ./mc admin users add myminio1 newuser newuser123 getonly
Added used `newuser` successfully.

**Comment by kellenchen** [comment]
when i login in, the dialog show The access key ID you provided does not exist in our records

**Comment by kellenchen** [comment]
the minio I setup is in distributed mode , and I use mc command on one minio instance.

**Comment by harshavardhana** [comment]
The users are loaded every 5 mins on rest of the other nodes

**Comment by kellenchen** [comment]
I just login on the node I execute the mc command. It pass not only 5 minutes.

**Comment by kellenchen** [comment]
When i use the latest minio, it works.
