### ISSUE TITLE
Feature Request - Control disks in Minio Disk groups

### ISSUE THREAD

**Issue by eyalrif** [minio/minio#6768]
Feature Request -

Please add the ability to control which mount point will be part of each disk group in minio.
i.e - in case of 4:2 - i would like the /mnt/minio1 on all 6 servers will be disk group1,minio2 on disk group2 etc..

This allows more fine grain control and allow the user to control the device location better (This, for example, can be configured when multiple JBODs are in one setup and you want to allow a situation in which on JBOD is done the system will still be operational)

**Comment by nitisht** [comment]
Thanks @eyalrif we will discuss this internally and get back to you

**Comment by harshavardhana** [comment]
This is already possible using a combination of custom drive count and endpoints without ellipses.

```
MINIO_ERASURE_SET_DRIVE_COUNT=4 MINIO_ENDPOINTS="/tmp/2 /tmp/3 /tmp/4 /tmp/1 /tmp/6 /tmp/5 /tmp/7 /tmp/8" minio server
```

**Comment by kannappanr** [comment]
@eyalrif Closing this issue. Please feel free to reach out to us if you have further questions.
