### ISSUE TITLE
How to upgrade minio in distributed mode 

### ISSUE THREAD

**Issue by kellenchen** [minio/minio#6769]
I use minio of 10.6 version in distributed mode. Now I want to upgrade the minio to 11.6 version since some functions not support by old version. How can I do it

**Comment by kellenchen** [comment]
I don't want to transfer data and config again...

**Comment by harshavardhana** [comment]
@kellenchen please join https://slack.minio.io for answers to these questions - Github issue is not a forum for this type of communication.

**Comment by nitisht** [comment]
closing this as answered on Slack
