### ISSUE TITLE
Ubuntu Server - Unable to start Minio Service

### ISSUE THREAD

**Issue by pchiend** [minio/minio#6771]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by pchiend** [comment]
Linux  4.15.0-38-generic #41-Ubuntu SMP

**Comment by harshavardhana** [comment]
Non descriptive issue with no logs or steps to reproduce. Issue template is empty.

Closing this issue as insufficient information.
