### ISSUE TITLE
Unable to start Minio Service

### ISSUE THREAD

**Issue by pchiend** [minio/minio#6772]
## Expected Behavior

Hello,

i have installed Ubuntu server and Minio.

I follow this procedure:
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04.

## Current Behavior

When i try to start Minio Service i have this:
● minio.service - Minio
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-11-06 16:48:19 CET; 49min ago
     Docs: https://docs.minio.io
  Process: 49302 ExecStartPre=/bin/bash -c [ -z "${MINIO_VOLUMES}" ] && echo "Variable MINIO_VOLUMES not set in /etc/default/minio" (code=exited, status=1/FAILURE)

nov 06 16:48:19 storage.pchiend.it systemd[1]: Starting Minio...
nov 06 16:48:19 storage.pchiend.it systemd[1]: minio.service: Control process exited, code=exited status=1
nov 06 16:48:19 storage.pchiend.it systemd[1]: minio.service: Failed with result 'exit-code'.
nov 06 16:48:19 storage.pchiend.it systemd[1]: Failed to start Minio.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Version used (`minio version`): Latest
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Ubuntu
* Operating System and version (`uname -a`): Linux storage.pchiend.it 4.15.0-38-generic #41-Ubuntu
* Link to your project:

**Comment by harshavardhana** [comment]
Have you created `/etc/default/minio` ? mentioned in https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-16-04

If yes can you please share it with us?

**Comment by pchiend** [comment]
Hello,
yes, sure:

MINIO_VOLUMES="/mnt/md0/"
MINIO_OPTS="-C /etc/minio --address 192.168.40.21:9000"

Regards

**Comment by pchiend** [comment]
Hi, i tryied to reinstall, but the issue is the same, the strange thing is, 1 month ago , same installation procedure but no problem.

Do you know what can i try?

**Comment by vadmeste** [comment]
@pchiend would you mind also pasting /etc/systemd/system/minio.service ? this looks like a typo somewhere

**Comment by pchiend** [comment]
[Unit]
Description=Minio
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/

User=minio-user
Group=minio-user

PermissionsStartOnly=true

EnvironmentFile=-/etc/default/minio
ExecStartPre=/bin/bash -c "[ -z \"${MINIO_VOLUMES}\" ] && echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\""

ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart this service only if it has ended with the clean exit code or signal.
Restart=on-success

StandardOutput=journal
StandardError=inherit

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=0

# SIGTERM signal is used to stop Minio
KillSignal=SIGTERM

SendSIGKILL=no

SuccessExitStatus=0

[Install]
WantedBy=multi-user.target

# Built for ${project.name}-${project.version} (${project.name})
~

**Comment by vadmeste** [comment]
@pchiend can you join https://slack.minio.io and ping me there, it would be easier to debug your issue

**Comment by harshavardhana** [comment]
There was a bug in our systemd after couple of PRs were merged - It's fixed in

https://github.com/minio/minio-service/commit/10e52dfb43677a009b066c9dada17d5166f85ff9

**Comment by pchiend** [comment]
Hello,

so what i need to do?

**Comment by harshavardhana** [comment]
Download the minio.service file again and restart your service ...

**Comment by pchiend** [comment]
Perfect, now it work, but i haven not access and secret key.  Usually i saw that with: 

systemctl status minio.service

**Comment by vadmeste** [comment]
> Perfect, now it work, but i haven not access and secret key. Usually i saw that with:

New Minio version doesn't print access & secret keys in logs anymore, this is intended. You need to set MINIO_ACCESS_KEY and MINIO_SECRET_KEY in /etc/default/minio

e.g.:
MINIO_ACCESS_KEY="minio"
MINIO_SECRET_KEY="minio123"

**Comment by pchiend** [comment]
Very good, it works now.  Thank you all.

**Comment by devburak** [comment]
> /etc/default/minio

when i change anything variable in this file, minio does not start/restart. Do you have any idea why?
