### ISSUE TITLE
Anonymous downloads now working via web UI on bucket with read-only policy

### ISSUE THREAD

**Issue by pwagland** [minio/minio#6778]
This appears to be a regression, similar to the one in #5076.

We are having this issue when running release 2018-11-06T01:01:02Z, this should already be fixed there, correct? I can see that we are not generating the token, as the URL ends with `?token=%27%27`. Prior to upgrading, this same URL did work.

If I change the URL so that instead of `https://host/minio/download/…?token=%27%27` it is `https://host/…`, then the file can be viewed/downloaded. Just removing the `?token=%27%27` also does not work for the download, that just takes me to the login screen.

## Expected Behavior
Clicking download should on a file that I can see should download the file.

## Current Behavior
Clicking download should on a file that I can see results in the error message "Authentication failed, check your access credentials".

## Possible Solution
A work around is presented above, use the direct URL instead of the download URL. This is obviously inconvenient for users.

## Steps to Reproduce (for bugs)
* Create bucket using web ui
* Upload file into bucket using web ui
* Create * read-only policy using web ui
* Copy URL from browser and open in another incognito window
* Attempt to download one of the files using web ui

## Context
Our users are no longer able to download files.

## Regression
Is this issue a regression? *Yes*

This was working before the upgrade, we were running the 2018-10-25 release.

## Your Environment
* Version used (`minio version`): 2018-11-06T01:01:02Z

**Comment by kannappanr** [comment]
@pwagland Thanks for filing this issue. We will try to fix this issue as soon as possible.
