### ISSUE TITLE
Feature Request: Auto heal on reading Object

### ISSUE THREAD

**Issue by eyalrif** [minio/minio#6782]
Please add a feature that heals an object automatically when it is read and identified as not fully healed

**Comment by harshavardhana** [comment]
Thanks @eyalrif we are actually planning to work on it.

**Comment by bratao** [comment]
This is a very important feature. Bit rot at large volume of data is very common and would be a very compelling feature to Minio.

**Comment by cagriersen-omma** [comment]
Absolutely this is a must have  feature especially for large scale deployments. We were planning to deploy such a infrastructure but without auto-heal feature I wouldn't be sure how to handle possible inconsistencies among the nodes.

**Comment by harshavardhana** [comment]
We have auto heal feature in MinIO, which heals namespace every 24hrs. There are further optimizations coming in. So closing this issue as fixed for now.

**Comment by jaceksan** [comment]
@harshavardhana thanks for the feature!
Question - can 24 hours period be configured?

Unfortunately there is a use case, which cannot be solved by this auto-heal feature - 
redeploy of k8s worker nodes (e.g. when upgrading HW).
For each redeployed node related Minio POD starts empty and needs to be healed from the rest of the cluster before redeploying next node.
We can trigger heal "manually" using mc tool.
I am just wondering, if this use case will be any time in the future supported by auto-heal mechanism.
Has already been created a relevant feature request?

**Comment by nullne** [comment]
@harshavardhana   if there are lot's of objects within one MINIO cluster, let's say 1 billion, it's hard to scan all of the objects in 24 hours.

**Comment by harshavardhana** [comment]
We will be doing that @jaceksan - there are further optimizations underway.

There won't be any overlapping scans every 24hrs @nullne - if the previous scan is in progress the healing waits for them to complete. There are some more optimizations being implemented to address a more quicker visits to different directories.
