### ISSUE TITLE
Cannot host behind a proxy path

### ISSUE THREAD

**Issue by ssshake** [minio/minio#6792]
This config produces this error

```

            this.minioClient = new Minio.Client({
                endPoint: 'domain.com/minio',
                port: 9000,
                useSSL: false,
                accessKey: '1234',
                secretKey: '4321'
            });


```

```

InvalidEndpointError {message: "Invalid endPoint : domain.com/minio", name: "InvalidEndpointError", stack: "InvalidEndpointError: Invalid endPoint : domain.co…node_modules/vue/dist/vue.runtime.esm.js:3137:25)"}
message: "Invalid endPoint : domain.com/minio"
name: "InvalidEndpointError"
stack: "InvalidEndpointError: Invalid endPoint : domain.com/minio↵    at new Client (webpack

```

## Expected Behavior
I have this behind an nginx proxy at a particular path. I can access the webui properly so that indicates to me that this should work find.

## Current Behavior
Error above is produced not allowing me to specify a path

## Context
I'm hosing a simple, private webUI and the object store on the same domain and I want a shared SSL cert and dont want to deal with cross origin issues imposed by the browser. The only solution I can think of is to host the front end and object store on the same domain under two different paths.

## Your Environment

* Version used 2018-11-06T01:01:02Z
* Environment name and version nginx/1.4.6 (Ubuntu)
* Server type and version ?
* Operating System and version (`uname -a`) :Linux Linuxbox 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is a expected signature signs the request path, you cannot have a custom path translation.

**Comment by kannappanr** [comment]
@ssshake Will close this as answered. Please feel free to contact us if you have more questions.
