### ISSUE TITLE
Can minio replace nfs storage and write to log files in real time?

### ISSUE THREAD

**Issue by melin** [minio/minio#6797]
An application uses the nfs store log, logback appender to write directly to the nfs directory. Can minio instead of nfs store logback log files?
![image](https://user-images.githubusercontent.com/1145830/48297702-30fa7280-e4ea-11e8-85ba-4b91bb9a403c.png)
![image](https://user-images.githubusercontent.com/1145830/48297711-44a5d900-e4ea-11e8-9e0f-ba58229ffc8d.png)

**Comment by kannappanr** [comment]
@melin Minio can store logs, but cannot append to an existing object. Can you be more clear about what you want?

**Comment by melin** [comment]
> @melin Minio can store logs, but cannot append to an existing object. Can you be more clear about what you want?

each spark job run information is written to a log file, log data is appended, nfs has a single point of failure, and hopes to have a highly available simple solution

**Comment by harshavardhana** [comment]
We still cannot understand what you want Minio to do @melin - what from what I can understand you append to logs, its not possible in S3 API

**Comment by nitisht** [comment]
@melin closing this for now, feel free to reopen if / when you have additional info for us.
