### ISSUE TITLE
Display fingerprint of cert's publickey during startup

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#6801]
*** Not using standard template ***
This is a new feature. In the case of TLS, we will display the sha256 of the publickey in the cert during startup. The expectation is that this value will match the one displayed using `openssl`

`openssl x509 -noout -fingerprint -sha256 -inform pem -in [certificate-file.crt]`

## Context
This is required to support the issues in `mc` https://github.com/minio/mc/issues/2596 and https://github.com/minio/mc/issues/2597

## Regression
No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by aead** [comment]
The fingerprint should be the HPKP (HTTP public key pinning) hash value. Therefore we have to compute the SHA256 of the raw SubjectPublicKeyInfo. To verify using openssl we can use the following command: `openssl x509 -pubkey -in <certificate> | openssl pkey -pubin -outform der | openssl dgst -sha256`

**Comment by harshavardhana** [comment]
There is no plan to do this as of now.
