### ISSUE TITLE
Format issue of the uploaded file

### ISSUE THREAD

**Issue by biplabbh** [minio/minio#6805]
## Expected Behavior
 The uploaded files (image,video etc.) should be downloaded as specified format like jpg/png/jpeg/wmv etc.

## Current Behavior
I have been successful to upload image and videos from android clients. But the uploaded contents I see in the minio client are in a different generalized format. I am providing a screenshot of the minio client.

## Possible Solution
Need to get the exact image/video that I have uploaded in that format only.

May be it is a problem from my end..any help would be appreciated.

![screenshot](https://user-images.githubusercontent.com/31616658/48399268-34d80000-e749-11e8-9977-17bae312604d.png)

**Comment by kannappanr** [comment]
@biplabbh Minio server does not set this information. It is the responsibility of the client to set the objectname and content-type.

**Comment by biplabbh** [comment]
@kannappanr  I have been using minio-3.0.4.jar.

So I have seen from MinioClient.class that this class uses 

headerMap.put("Content-Type", "application/octet-stream");

as contentType.

Still is creates the format issue.

**Comment by biplabbh** [comment]
I am describing the scenario largely, please have a look
1 //#################
MinioClient minioClient = new MinioClient("https://play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");
		try {
			if (!minioClient.bucketExists(bucketname)) {
				minioClient.makeBucket("testbucket","us-east-1");
			} 
			if (method == HttpMethod.PUT) { 
				url = minioClient.presignedPutObject("testbucket", attachemtnId, DURATION); ////Here attachemtnId is the object name like "653253198687911820" but with no extension
			}
			if (method == HttpMethod.GET) {
				url = minioClient.presignedGetObject("testbucket", attachemtnId);
			}
			System.out.println(url);
		} catch (MinioException e) {
                        System.out.println("Error occurred: " + e);
		} catch (java.security.InvalidKeyException e) {
			e.printStackTrace();
		}
//##########################
2. //######################## (From MinioClient.class)

public String presignedPutObject(String bucketName, String objectName, Integer expires)
    throws InvalidBucketNameException, NoSuchAlgorithmException, InsufficientDataException, IOException,
           InvalidKeyException, NoResponseException, XmlPullParserException, ErrorResponseException,
           InternalException, InvalidExpiresRangeException {
    if (expires < 1 || expires > DEFAULT_EXPIRY_TIME) {
      throw new InvalidExpiresRangeException(expires, "expires must be in range of 1 to " + DEFAULT_EXPIRY_TIME);
    }

    String region = getRegion(bucketName);
    Request request = createRequest(Method.PUT, bucketName, objectName, region, null, null, null, "", 0);
    HttpUrl url = Signer.presignV4(request, region, accessKey, secretKey, expires);
    return url.toString();
  }

//########################

Now after all of this call it stores the content as object by that attachemtnId and when we try to download that object file from Minio client browser, it gets downloaded but not as an image/ video, only as an object format.

This is the issue I am facing.

**Comment by nitisht** [comment]
> I have been using minio-3.0.4.jar.

@biplabbh that is pretty old version, can you try with latest release [https://github.com/minio/minio-java/releases/tag/5.0.2] and let us know how it goes

**Comment by kannappanr** [comment]
@biplabbh The solution here is for the application to set the header, when it does the `PUT` operation. Say using curl, if you were to test this, you will do something like
`curl "http://presignedurl" --upload-file /etc/issue -H "Content-Type:application/javascript"`
Assuming that `http://presignedurl` is the URL generated by `minio-java`.

**Comment by biplabbh** [comment]
@nitisht   @kannappanr   Though this is a separate issue..would you please help. The situation is I am trying to upload image/video etc. from a mobile application. The upload call happens in the following way:


mobile app ===> Java client for Minio ===> Minio

(Java client for Minio is deployed in our customized public server ip: **http://219.91.160.XXX** )

So when from this public server **http://219.91.160.XXX** ,  the call goes to Minio like below and upload works:

MinioClient minioClient = new MinioClient("https://play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");


But If I want to use my ip (**http://219.91.160.XXX**) instead of  **"https://play.minio.io:9000"** from the public server itself  ,  the call goes to Minio like below but upload fails:

MinioClient minioClient = new MinioClient("public server's local ip", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");
/**Q: 1::**/ I know that might be the issue is for same domain policy it is not working. Does we need any DNS for calling Customized Minio server (That we have installed at our end) or we can call it by IP? 

/**Q: 2::**/ So I am trying to test by POSTMAN at first. So when I am trying to upload a sample picture through postman to play.minio.io it is not working.. please see the attached screenshot of the postman that I tried. Am I missing something? I hope you guys can surely help..

![111](https://user-images.githubusercontent.com/31616658/48611321-0c9c0b80-e9ac-11e8-85ae-67268bd6f8b0.png)

![222](https://user-images.githubusercontent.com/31616658/48611335-10c82900-e9ac-11e8-8cb4-6975e25448ca.png)

![333](https://user-images.githubusercontent.com/31616658/48611342-13c31980-e9ac-11e8-8da3-2a0764958acd.png)

**Comment by kannappanr** [comment]
@biplabbh instead of the using POSTMAN, can you try with `mc` or some other client. I haven't really worked with `POSTMAN` before. I spent quite a bit of time with it, I am getting <Code>XAmzContentSHA256Mismatch</Code>
    <Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message>


Regarding Q1, can you turn on tracing in `minio` by setting an environment variable `MINIO_HTTP_TRACE=/dev/stdout` and then starting it. Maybe the external IPAddress is not visible. Since you are already on that machine, can you simply try `http://127.0.0.1:XXX` ?

**Comment by biplabbh** [comment]
> Regarding Q1, can you turn on tracing in `minio` by setting an environment variable `MINIO_HTTP_TRACE=/dev/stdout` and then starting it. Maybe the external IPAddress is not visible. Since you are already on that machine, can you simply try `http://127.0.0.1:XXX` ?

I tried with http://127.0.0.1:XXX, but same error. Did not work.

**Comment by kannappanr** [comment]
Can you paste any errors on the server side and also the startup message on the server console?

**Comment by biplabbh** [comment]
@kannappanr 

Below is the server log:

[2018-11-19 19:07:23 +0530]
HEAD /signalbucket123
Host: localhost:9000
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181119T133723Z
Authorization: AWS4-HMAC-SHA256 Credential=A2ETM5IPN6KQ5QWHM8D3/20181119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=645c4fb6e03a6b94b223e0cfaced255a4b9fec414f876bbf64b8b783d3220c8e
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: Minio (amd64; amd64) minio-java/dev


[RESPONSE] [154263464.310257] [2018-11-19 19:07:23 +0530]
200 OK
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15688A08E0564AFE
Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
Accept-Ranges: bytes


[REQUEST (objectAPIHandlers).HeadBucketHandler-fm] [154263464.311855] [2018-11-19 19:07:23 +0530]
HEAD /signalbucket123
Host: localhost:9000
X-Amz-Date: 20181119T133723Z
Authorization: AWS4-HMAC-SHA256 Credential=A2ETM5IPN6KQ5QWHM8D3/20181119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=645c4fb6e03a6b94b223e0cfaced255a4b9fec414f876bbf64b8b783d3220c8e
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: Minio (amd64; amd64) minio-java/dev
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855


[RESPONSE] [154263464.311855] [2018-11-19 19:07:23 +0530]
200 OK
Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
Accept-Ranges: bytes
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15688A08E14A6505


[REQUEST (objectAPIHandlers).PutObjectHandler-fm] [154263464.347937] [2018-11-19 19:07:23 +0530]
PUT /signalbucket123/5938742850589161032?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=A2ETM5IPN6KQ5QWHM8D3%2F20181119%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20181119T133723Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=fc045d8b4c963de61bebcfa8285ec55e854e61f28895eb6c2339ee93064287a6
Host: 219.91.160.182:9000
Content-Length: 78800
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; Redmi Note 4 MIUI/V9.6.3.0.NCFMIFD)
Accept-Encoding: gzip
Content-Type: application/octet- stream
Connection: close

<BODY>

[RESPONSE] [154263464.347937] [2018-11-19 19:07:23 +0530]
403 Forbidden
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15688A08F6CBC905
Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
Accept-Ranges: bytes
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/signalbucket123/5938742850589161032</Resource><RequestId>15688A08F6CBC905</RequestId><HostId>3L137</HostId></Error>



All I am trying to do is, 
a) From Android client I am trying to upload image/videos using an url  (I have received the url by calling Java client by presignedPutObject-- which returns the url)
b) The url gets generated and I am getting it in Android end, Now I am trying to call OkHttpClient to upload image using that url that I received from the JavaClient.

Url pattern:

http://219.91.160.XXX:9000/signalbucket123/6053009523459869212?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=RX5E19CDCZ4GK4KLLZX9%2F20181119%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20181119T115551Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=6cb471c0d4d9ae25829aff08af13e1cab4e693d77a73da97cf46c54319cf5404

Now at the time of upload it return 403 Forbidden.

Help would be appreciated..And also thanks to @kannappanr for replying me so quickly every time.

**Comment by biplabbh** [comment]
@kannappanr 

I tried to run the curl command as well,

from the server (my public server)  itself where Minio is installed: (used **localhost** as well as **127.0.0.1** also)
==================================
curl -v http://localhost:9000/ -H "Authorization: AWS4-HMAC-SHA256 Credential=A2ETM5IPN6KQ5QWHM8D3/20181119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=333ce437e434cdf5af0a556e6a7bd03892ffa7de1f86ef52d7100e81d89cda58" -H "x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" -H "x-amz-date: 20181120T075700Z"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: AWS4-HMAC-SHA256 Credential=A2ETM5IPN6KQ5QWHM8D3/20181119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=333ce437e434cdf5af0a556e6a7bd03892ffa7de1f86ef52d7100e81d89cda58
> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> x-amz-date: 20181120T075700Z
> 
< HTTP/1.1 **403 Forbidden**
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
< Vary: Origin
< X-Amz-Request-Id: 1568C62416BA97E6
< X-Xss-Protection: 1; mode=block
< Date: Tue, 20 Nov 2018 07:58:50 GMT
< Transfer-Encoding: chunked
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/</Resource><RequestId>1568C62416BA97E6</RequestId><HostId>3L137</HostId></Error>


And also tried from out side of the network, same result:
=========================================
curl -v http://219.91.160.XXX:9000/ -H "Authorization: AWS4-HMAC-SHA256 Credential=A2ETM5IPN6KQ5QWHM8D3/20181119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=333ce437e434cdf5af0a556e6a7bd03892ffa7de1f86ef52d7100e81d89cda58" -H "x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" -H "x-amz-date: 20181120T075700Z"
*   Trying 219.91.160.XXX...
* TCP_NODELAY set
* Connected to 219.91.160.XXX (219.91.160.XXX) port 9000 (#0)
> GET / HTTP/1.1
> Host: 219.91.160.XXX:9000
> User-Agent: curl/7.62.0
> Accept: */*
> Authorization: AWS4-HMAC-SHA256 Credential=A2ETM5IPN6KQ5QWHM8D3/20181119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=333ce437e434cdf5af0a556e6a7bd03892ffa7de1f86ef52d7100e81d89cda58
> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> x-amz-date: 20181120T075700Z
>
< HTTP/1.1 403 Forbidden
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: Minio/RELEASE.2018-08-02T23-11-36Z (linux; amd64)
< Vary: Origin
< X-Amz-Request-Id: 1568C62FE3E1E100
< X-Xss-Protection: 1; mode=block
< Date: Tue, 20 Nov 2018 07:59:41 GMT
< Transfer-Encoding: chunked
<
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/</Resource><RequestId>1568C62FE3E1E100</RequestId><HostId>3L137</HostId></Error>* Connection #0 to host 219.91.160.XXX left intact


please help!

**Comment by kannappanr** [comment]
@biplabbh Can we please stick to one issue and try to solve that? Please tell us what you are trying to do. You can also reach us at minio.slack.com, one of us will be there and interacting there might be faster.

**Comment by biplabbh** [comment]
@kannappanr Hey sorry for that. 

But you wanted the logs of Minio. That I have provided you in the last 2 posts. I also provided you the Curl command as well. Just tried to convey that all are giving 403 forbidden response.

**Comment by kannappanr** [comment]
@biplabbh I just meant, it is easier to just focus on one way to reproduce the issue. I have responded to you on slack. We can take it from there.

**Comment by biplabbh** [comment]
Hey @kannappanr .. I have resolved the issue described above in Q1 and Q2. The issue was from our public server itself and that was related to DNS mapping. So this issue is done.

Another is the format of the content being uploaded which I have described at the very first of this thread. Let me try more and more and if I fail to achieve then will communicate with you guys..

So you can close this isssue.

Anyways thanks for being so helpful.

**Comment by kannappanr** [comment]
@biplabbh Glad that you got it to work. I have left you a message on slack. Please feel free to contact me if you need any help.
