### ISSUE TITLE
S3Select: Column position indexing no longer works

### ISSUE THREAD

**Issue by donatello** [minio/minio#6814]
## Expected Behavior

Indexing columns by position e.g. `_1, _2, _3` ought to work. 

## Current Behavior

No results are returned - like as if the column names are being interpreted as strings and not being found in the rows itself.

This used to work, but doesn't now.

## Possible Solution

Need to bring it back.

## Steps to Reproduce (for bugs)

Try query on CSV file like `select s._1 from s3object s` with `FileHeaderInfo` set to `NONE` or `IGNORE`.

## Regression

Yes, this was working prior to c0b4bf0a3e702882008ebaf5f84c32f6fd446f72

**Comment by harshavardhana** [comment]
Fixed in #6815
