### ISSUE TITLE
Azure gateway disk cache by download not storing file in cache folder

### ISSUE THREAD

**Issue by ssuio** [minio/minio#6817]
Setup Azure gateway and disk cache environment attrs. 
Only uploading file will be stored in cache folder. Downloading file won't be stored in cache folder.

## Expected Behavior
Expect doing download on Azure's file will be cached in the cache folder.

## Current Behavior
Upload file will be cached in cache folder.
Download file won't be cached in cache folder.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)

1. Setup Azure gateway, disk cache mode(A cache folder).
2. Start the server.
3. Download a file from Azure server minio browser.
4. The cache file is not store in the cache folder.

## Context
We are comparing Minio file cache versus ours project.

## Regression
 As @poorna said, seems yes. But I don't have the details.

## Your Environment
Minio RELEASE.2018-11-06T01-01-02Z
OS: Windows 7 x64

**Comment by kannappanr** [comment]
@ssuio Thanks for filing this issue. Will try to send a fix soon.
