### ISSUE TITLE
Minio server crash when using mc mirror --watch

### ISSUE THREAD

**Issue by curantes** [minio/minio#6818]
When we are starting a `mc mirror --watch` to sync our 16 node minio cluster to local disk the servers get approx 500 in load and according to haproxy health checks timeouts and after a few seconds comes back up randomly between the minio nodes. After approx 10 minutes one of the minio servers crash and we decided to interrupt the `mc mirror --watch`. The attached logs are from the minio that crashed. I get a feeling that our cluster is now too big to be able to initiate a `mc mirror --watch` without issues.

[minio_log-2018-11-15.log](https://github.com/minio/minio/files/2584664/minio_log-2018-11-15.log)

## Expected Behavior

Should be able to initiate a `mc mirror --watch` without causing extensive load and crash of minio server

## Current Behavior

High load on minio cluster causing internal health checks in minio to timeout so minio think some disks are not available.

## Steps to Reproduce (for bugs)

1. have a very large minio cluster (16 nodes 1,8 TB used per node (df -h) and 1000 buckets)
2. initiate a mirror sync with mc `mc mirror --watch` to a local disk
3.
4.

## Context

This is part of our backup solution where we mirror cluster to freenas and make periodic zfs snapshots.

## Your Environment

* Version used (`minio version`): Version: 2018-10-25T01:27:03Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: VM CentOS 7
* Operating System and version (`uname -a`): Linux prod-arkivplats14.fnox.se 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by vadmeste** [comment]
@curantes, the crash seems to be duplicated to this (https://github.com/minio/minio/issues/6483)

Do you still have a high usage of go routines number ? Can you tell me how do you do to get the number of go routines ?

**Comment by curantes** [comment]
Issue #6483 is a symptom of this issue as the load peaked at 889 5-10 minutes after starting `mc mirror --watch`  

according to mino webui we have a usage of: `Used: 28.27 TB`

`df -h` for one server
```
Filesystem                     Size  Used Avail Use% Mounted on
/dev/mapper/vg_minio-lv_minio  2,5T  1,8T  691G  73% /minio/data
```

You should be able to reproduce this with similar amout of data in a 16 node cluster.

I checked the goroutines and we have as follow:
```
$ ./goroutines.sh 
01:
go_goroutines 2839
02:
go_goroutines 2841
03:
go_goroutines 2894
04:
go_goroutines 2876
05:
go_goroutines 2887
06:
go_goroutines 2874
07:
go_goroutines 2883
08:
go_goroutines 2875
09:
go_goroutines 2877
10:
go_goroutines 2896
11:
go_goroutines 2851
12:
go_goroutines 2892
13:
go_goroutines 2882
14:
go_goroutines 2883
15:
go_goroutines 2893
16:
go_goroutines 2854
```

**Comment by vadmeste** [comment]
@curantes can you paste the content of your goroutines.sh script ?

**Comment by curantes** [comment]
```
#!/bin/bash

for i in {01..16}; do 
	echo $i:$a
	curl -v --silent  "http://prod-arkivplats$i:9091/minio/prometheus/metrics" 2>&1 | grep -E "^go_goroutines "
done
```

**Comment by curantes** [comment]
df -i for one node:
```
Filesystem                       Inodes     IUsed    IFree IUse% Mounted on
/dev/mapper/vg_minio-lv_minio 262143584 169811564 92332020   65% /minio/data
```

**Comment by vadmeste** [comment]
@curantes I've finally found the bug, it is the call of minio/prometheus/metrics API which increases the number of goroutines but surprisingly only in case of a distributed setup.

Will make further investigation and send the fix hopefully today.
