### ISSUE TITLE
Unit test to detect change in Storage REST API and mandate storage REST upgrade

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#6821]
## Expected Behavior
Storage REST API is a crucial part of Minio code, a test in Minio code or in tests should be there to detect API change

## Current Behavior
There is no such code which detects change in API

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
NA

## Context
Avoid regression

## Regression
No

## Your Environment
All

**Comment by harshavardhana** [comment]
how do you propose we do this @vadmeste ?

**Comment by kannappanr** [comment]
ping @vadmeste . How do you think we add a unit test for this? If we do not know, should we add some sort of test setup for this. What will the different version types look like?

**Comment by vadmeste** [comment]
> ping @vadmeste . How do you think we add a unit test for this? If we do not know, should we add some sort of test setup for this. What will the different version types look like?

Well, I think we can do some reflect on storage interface here, reflect will iterate on function names and arguments type and position and compare it to the one hardcoded in the unit test, so we can remember to increase REST version each time we change the API

**Comment by harshavardhana** [comment]
any proposal that you have to test this @vadmeste ?
