### ISSUE TITLE
Can't get HTTPS connection to work

### ISSUE THREAD

**Issue by labnewbie** [minio/minio#6822]
Minio was working fine using HTTP.  The application that I am using to write to Minio requires HTTPS.  I used GnuTLS to create my cert files.  Placed them into the .minio/certs folder and restarted the server.

The conf file is pretty basic:
# X.509 Certificate options
#
# DN options

# The organization of the subject.
organization = "LAB"

# The organizational unit of the subject.
#unit = "IT"

# The state of the certificate owner.
state = "MA"

# The country of the subject. Two letter code.
country = "US"

# The common name of the certificate owner.
cn = "LABNOOB"

# In how many days, counting from today, this certificate will expire.
expiration_days = 365

# X.509 v3 extensions

# DNS name(s) of the server
dns_name = "localhost"

# (Optional) Server IP address
ip_address = "127.0.0.1"

# Whether this certificate will be used for a TLS server
tls_www_server

# Whether this certificate will be used to encrypt data (needed
# in TLS RSA cipher suites). Note that it is preferred to use different
# keys for encryption and signing.
encryption_key
## Expected Behavior

The server started fine:
c:\Minio>minio.exe server C:\Minio\Data

Endpoint:  https://198.186.100.133:9000  https://127.0.0.1:9000
AccessKey: 1E226M8L70WLE7PNHM0U
SecretKey: nTxZAVen80SWcY3K3iwlGdwdQgK7sjZCFGPuPRyj

Browser Access:
   https://198.186.100.133:9000  https://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc.exe config host add myminio https://198.186.100.133:9000 1E226M8L70WLE7PNHM0U nTxZAVen80SWcY3K3iwlGdwdQgK7sjZCFGPuPRyj

## Current Behavior

When I try to add 

mc.exe config host add myminio https://198.186.100.133:9000 1E226M8L70WLE7PNHM0U nTxZAVen80SWcY3K3iwlGdwdQgK7sjZCFGPuPRyj
mc.exe: <ERROR> Unable to initialize new config from the provided credentials. Get https://198.186.100.133:9000/probe-bucket-sign-cvp1vinlns4t/?location=: x509: certificate signed by unknown authority

This is what I see on the server side:
API: SYSTEM()
Time: 16:04:30 EST 11/15/2018
Error: [31m[1mremote error: tls: bad certificate[0m[0m
       remoteAddr=198.186.100.133:50323, localAddr=198.186.100.133:9000
       1: cmd\http\listener.go:255:http.(*httpListener).start.func2()

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@labnewbie `mc.exe config host add --insecure myminio https://198.186.100.133:9000 1E226M8L70WLE7PNHM0U nTxZAVen80SWcY3K3iwlGdwdQgK7sjZCFGPuPRyj` should work

**Comment by labnewbie** [comment]
Thank you @kannappanr that worked.

so now that the server is running in a "secured" mode, it seems I need to use the --insecure for all my command line entries.  Is that true?

PS C:\Users\administrator.HOMELAB> mc admin service status myminio
mc : mc.exe: <ERROR> Cannot get service status. Get https://192.186.100.133:9000/minio/admin/v1/service: 
x509: certificate signed by unknown authority
At line:1 char:1
+ mc admin service status myminio
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (mc.exe: <ERROR>...known authority:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Using --insecure works
PS C:\Users\administrator.HOMELAB> mc admin service status myminio --insecure
Uptime: 5 minutes 27 seconds.

**Comment by harshavardhana** [comment]
You can trust your certs by copying public.crt to `.mc/certs/CAs`  this way you don't have to use --insecure

**Comment by labnewbie** [comment]
thanks @harshavardhana 

I had both private.key and public.crt in %%USERPROFILE%%\.minio\certs.  I copied public.crt into %%USERPROFILE%%\.minio\certs\CA

Still need to use --insecure though.  As noted earlier i used GnuTLS to create the certs.

The cert.cnf has only the following values.  I wonder if the key is bad?
organization = "Lab"
state = "MA"
country = "US"
cn = "Labnoob"
expiration_days = 365
dns_name = "localhost"
ip_address = "127.0.0.1"
tls_www_server
encryption_key

PS C:\Users\administrator.HOMELAB> mc admin service status myminio --insecure
Uptime: 1 minutes 23 seconds.

PS C:\Users\administrator.HOMELAB> mc admin service status myminio
mc : mc.exe: <ERROR> Cannot get service status. Get https://198.186.100.133:9000/minio/admin/v1/service: 
x509: certificate signed by unknown authority
At line:1 char:1
+ mc admin service status myminio
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (mc.exe: <ERROR>...known authority:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by harshavardhana** [comment]
Note I said `mc/certs/CAs` not `.minio/certs/CAs`

**Comment by labnewbie** [comment]
@harshavardhana my apologies.  Been staring at my screen so long im seeing things

public.crt is now in the correct location.  I restarted the minio server and the error has changed:

PS C:\Users\administrator.HOMELAB> mc admin service status myminio
mc : mc.exe: <ERROR> Cannot get service status. Get https://198.186.100.133:9000/minio/admin/v1/service: 
x509: certificate is valid for 127.0.0.1, not 198.186.100.133
At line:1 char:1
+ mc admin service status myminio
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (mc.exe: <ERROR>... 198.186.100.133:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by harshavardhana** [comment]
Here are the steps @labnewbie to get SSL working 

- SSL has been generated properly for a given IP address you have to use this IP always when talking over SSL otherwise generate a cert with domain name only
- Make sure you have `private.key and public.crt` are in `.minio/certs/` no need to copy anything yet into `.minio/certs/CAs` - avoid copying `private.key` into `.minio/certs/CAs` its not a CA its a private key for your cert. 
- Make sure to copy the `public.crt` to `.mc/certs/CAs` 
- `mc config host https://<ip>`  - the IP here should point to the IP for which the cert is generated from your error it looks like it is 127.0.0.1, not 198.186.100.133

**Comment by labnewbie** [comment]
Thank you @harshavardhana   Changing the ip address in the cert.cnf file as well as your latest instructions made it work as expected:

PS C:\GnuTLS\win64-build> mc admin service status myminio
Uptime: 22 minutes 15 seconds.

Now that I seems to have all the wrinkles ironed out, its time to see if the backup app will finally write to minio!!!!!

**Comment by harshavardhana** [comment]
@labnewbie let us know how it goes, feel free to close this bug.

**Comment by labnewbie** [comment]
Seems to be working fine.   Thanks for all the help.
