### ISSUE TITLE
Unable to initialize disk caching: Unsupported cache format [fs] found.

### ISSUE THREAD

**Issue by itarch** [minio/minio#6824]
Get Minio Server running by executing  
`$ ./minio server /mnt/minio `

However, would like to change the following params
Read the config via mc ... and change following params to
```
                "drives": [ "/mnt/minio" ],
                "expiry": 3,
                "maxuse": 60,
                "exclude": []
```

Set the new config via mc ... successfully
Restart service (as recommended), which output  
```
Restart command successfully sent to `nsaminio`.

API: SYSTEM()
Time: 12:05:11 CET 11/16/2018
Error: Unsupported cache format [fs] found
       1: cmd/format-disk-cache.go:283:cmd.validateCacheFormats()
       2: cmd/format-disk-cache.go:320:cmd.loadAndValidateCacheFormat()
       3: cmd/disk-cache.go:900:cmd.newCache()
       4: cmd/disk-cache.go:954:cmd.newServerCacheObjects()
       5: cmd/server-main.go:361:cmd.serverMain()
ERROR Unable to initialize disk caching: Unsupported cache format [fs] found.
Failed to restart `nsaminio`. error: Get http://192.168.1.176:9000/minio/admin/v1/service: dial tcp 192.168.1.176:9000: connect: connection refused
[1]+  Done                    ./minio server /mnt/minio
```

Changed into /mnt/minio/.minio.sys/config and removed value for driver in config.json to 
           `"drives":[]`   

And get Minio server starting again
What do I wrong here?

## Possible Solution
dont know

## Steps to Reproduce (for bugs)
as described before

## Your Environment
OS VERSION 
$ uname -a
Linux XXXXXX 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

MINIO RELEASE
$ ./minio version
Version: 2018-11-15T01:26:07Z
Release-Tag: RELEASE.2018-11-15T01-26-07Z
Commit-ID: 7e1661f4fabba77eae534f2af7e5ad5e847d6e10

MC RELEASE
$ ./mc version
Version: 2018-11-12T14:51:02Z
Release-tag: DEVELOPMENT.2018-11-12T14-51-02Z
Commit-id: 2fc5413002d81f424b651fce155125dd8b3d77bc

**Comment by nitisht** [comment]
@itarch the cache directory should be something other than the Minio server mount path that is used. So can you try another directory like so

```
 "drives": [ "/mnt/minio-cache" ],
```

**Comment by itarch** [comment]
@nitisht thank you for the fast feedback/advice

obviously i do not understand right the section "cache" of config.json. 
I thought by setting these values I would restrict retention limit and space limit. 
Following your segusstion, would it lead to what I intend?

**Comment by nitisht** [comment]
@itarch cache is meant to store content closer to the tenants and improve the time to first byte. It has no effect on Minio server's space limit etc.

**Comment by itarch** [comment]
@nitisht 
however, setting the cache dir as recomended works fine. 
But how can I restrict retentention and space limits in Minio.

**Comment by itarch** [comment]
Is the only  option that I have ...

`mc rm --older-than 60 nsaminio/nsabuck`

where 60 is 60 days
nsaminio: Minio Server
nsabuck: the Bucket on the Minio Server nsaminio

**Comment by nitisht** [comment]
> Is the only option that I have ...

`mc rm --older-than 60 nsaminio/nsabuck`

This is the recommended approach for now. We are working on Bucket Lifecycle support - #5139 , once that is available you can use that to manage this scenario.

**Comment by itarch** [comment]
@nitisht 

thank you so much...
I'm fine with that, since its only a Lab installation (see below)  with Grafana/Thanos/Prometheus. 
I adviced Prometheus to retent only 1 day and wanted to rentent some days more in Minio. 
To understand how things work/behave.   


![labgrafthaprom](https://user-images.githubusercontent.com/14290953/48623797-0c4f4080-e9ab-11e8-9905-131e4613bd9b.png)

**Comment by nitisht** [comment]
Understood, thanks @itarch . Feel free to join us on Slack https://slack.minio.io to talk more about your use case. Closing this issue as answered..
