### ISSUE TITLE
Not find a way to continue iterate items by `ListObjectsV2` if iterate failed in halfway

### ISSUE THREAD

**Issue by AlloVince** [minio/minio#6825]
Hi guys

I have a bucket stored over 100k items, currently I use `ListObjectsV2` API to iterate items and push items info into message queue.

However, I didn't found any solution to continue an iteration in halfway, which means when I iterate 100K items, if the task failed in 50k'th item, I have to re-start the whole iteration from the first item. It is really unacceptable for a large bucket.

I think a solution is adding a param `startCursor`  to `ListObjectsV2`, also `ListObjectsV2` required to return current `cursor` to each item, for example

``` python

objects = minioClient.list_objects_v2('mybucket', prefix='my-prefixname',
                              recursive=True)
for obj in objects:
    last_cursor = obj.cursor

# if iteration failed in halfway
# input start_cursor could continue interrupted iteration
objects = minioClient.list_objects_v2('mybucket', prefix='my-prefixname',
                              recursive=True, start_cursor=last_cursor)
```

Please consider my suggestion, it is really important.

Best regards

**Comment by kannappanr** [comment]
@AlloVince Can you clarify, if your request is to add this parameter to the `list_objects_v2` api in `minio-py` SDK? If yes, can you please open this under `minio-py` repo?

**Comment by AlloVince** [comment]
> @AlloVince Can you clarify, if your request is to add this parameter to the `list_objects_v2` api in `minio-py` SDK? If yes, can you please open this under `minio-py` repo?

Actually I hope all SDK could have this parameter. For my project, I need both python and nodejs SDK change.

As I understand, other languages SDK are wrappers of go lang core API,  I found a `startAfter` parameter in go source code, so you mean go core API already had this feature, just this parameter ignored by all SDK, is it?

If so, I will open issues under SDK repos, thanks

**Comment by kannappanr** [comment]
@AlloVince Minio does support `start-after` token. As far as exposing this in our SDKs, we have kept our APIs simple and have not exposed these options in our SDKs. Will talk internally and get back to you on this request.

**Comment by kannappanr** [comment]
@AlloVince We will implement this in our SDKs. Can you please go ahead and file those issues in minio-js and minio-py repositories?

**Comment by AlloVince** [comment]
@kannappanr opened 2 issues here:

- https://github.com/minio/minio-js/issues/733
- https://github.com/minio/minio-py/issues/718

**Comment by kannappanr** [comment]
Thanks @AlloVince . Will close this issue now.
