### ISSUE TITLE
ERROR Unable to initialize gateway backend: b2 error: net/http: TLS handshake timeout.

### ISSUE THREAD

**Issue by mnajamudinridha** [minio/minio#6830]
hi, i cant connect anymore to backblaze with minio docker, ERROR Unable to initialize gateway backend: b2 error: net/http: TLS handshake timeout.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
This looks like your network error - we cannot establish a connection remotely.

**Comment by nitisht** [comment]
@najcardboyz closing this as looks like gateway is not able to connect to remote backend. Feel free to reopen if there are still problems.
