### ISSUE TITLE
Minio browser: secret key field in the login page always empty

### ISSUE THREAD

**Issue by Latifa-tity** [minio/minio#6836]
## Expected Behavior
Entering secret key in the login page should show some asterisks

## Current Behavior
Secret key field is always empty no matter how many characters I enter

## Possible Solution
Show asteriks 

## Steps to Reproduce (for bugs)
1. Open Minio Browser in Chromium 70 under Windows 7
2. Enter an access key and a secret key

## Regression
I don't know

## Your Environment

* Version used (`minio version`): Version: 2018-11-17T01:23:48Z

**Comment by kannappanr** [comment]
@Latifa-tity Thanks for reaching out to us. It does show up in the browsers that we normally test. not sure what is going on there. Will definitely take a look and get back to you with further questions.

**Comment by kanagarajkm** [comment]
@Latifa-tity i don't have the required environment (Win 7 + Chrome) to reproduce this issue. Could you give a screenshot of the page?

**Comment by Latifa-tity** [comment]
@kanagarajkm, find attached the screenshot:
![screenshot](https://user-images.githubusercontent.com/11868927/49081211-5a373480-f246-11e8-97a6-e506b786420a.png)

**Comment by kanagarajkm** [comment]
@Latifa-tity thank you, i am looking into it

**Comment by kanagarajkm** [comment]
@Latifa-tity i tried to re-produce it in Win 7 + Chrome 70, but i see dots in password field

![chrome](https://user-images.githubusercontent.com/42696688/49149078-26840980-f32f-11e8-8ac8-d82ab33055dd.png)

To undestand the environment better, can you send the details by opening this url https://www.whatsmybrowser.org/

**Comment by Latifa-tity** [comment]
"Windows 7 operating system
IP address 213.150.178.14
Javascript enabled Yes
Cookies enabled Yes
Flash Version Not Installed
Java version Not installed
Supported Websockets Yes
Size of the browser 1349 x 657
Screen size 1366 x 768
24 bit color depth"
@kanagarajkm  i used another computer and always the same problem, 
but I do not see any points in the password field.

**Comment by kanagarajkm** [comment]
@Latifa-tity sorry i could not reproduce this problem. Will you able to do a screen share on slack or using some other service to debug this problem?

**Comment by kanagarajkm** [comment]
@Latifa-tity do you still face this problem? Can you try it on the lastest minio version?

**Comment by harshavardhana** [comment]
Closing this as stale issue, please re-open if seen again.
