### ISSUE TITLE
storage class needs to be rendered as HTML

### ISSUE THREAD

**Issue by jamesneimanconsulting** [minio/minio#6840]
We need to find a place for a gluegun-rendered version of this and include it in the site.yml or have a feature where items like this can still be rendered without having to be specified in site.yml.

**Comment by deekoder** [comment]
@jamesneimanconsulting  can you add more details like a picture of what you are proposing. It can be hand drawn if needed, nothing fancy. It will help us understand what you are proposing.

**Comment by deekoder** [comment]
Moving this to minio/gluegun. Closing it here.
