### ISSUE TITLE
presigned form uploads fail against minio if "hidden input fields" have Content-Type header set in multipart/form-data

### ISSUE THREAD

**Issue by ztane** [minio/minio#6844]
We're using Flurl (A popular .NET / C# library) to submit a file upload using presigned form. The file uploads did not work, resulting in HTTP 400 with `Missing fields in request` as the explanation.
While the fix was easy, it felt wrong because works against S3, and some browsers might be generating those headers (Windows Phone rumoured to)?

The POST had the format:

```
POST /bucket-files/ HTTP/1.1
Content-Type: multipart/form-data; boundary="d85d818a-48ca-4af6-ae86-7e23975bfd03"
Host: 192.168.1.41:9000
Content-Length: 232589
Expect: 100-continue
Accept-Encoding: gzip, deflate

--d85d818a-48ca-4af6-ae86-7e23975bfd03
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=x-amz-storage-class

STANDARD
--d85d818a-48ca-4af6-ae86-7e23975bfd03
... (rest of the fields omitted for brevity) ...
``` 

When the `Content-Type` header was *set* for *each part*, Minio doesn't think these are plain form fields.

It is notable that HTML 5.2 says that `Content-Type` field *must not be sent* for form fields, but earlier texts, for example RFC 1867 says that the `Content-Type` is just "optional", defaulting to `text/plain`.

## Expected Behavior

Presigned form submission should perhaps work with `Content-Type` set to `text/plain` with characters set for the fields.

## Current Behavior

400 Bad request, with `Missing fields in request`

## Steps to Reproduce (for bugs)

Use Flurl to post a presigned form

```
using System.IO;
using Flurl;
using Flurl.Http;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var fs = File.OpenRead("some_file");

            var response = "http://minio.localdomain"
                .AppendPathSegment("bucket/")
                .PostMultipartAsync(mp => mp
                    .AddString("x-amz-storage-class", "STANDARD")
                    .AddString("AWSAccessKeyId", "AKI12345678")
                    // other fields from the presigned form...
                    .AddFile("file", fs, "my-filename.txt")
                ).Result;
        }
    }
}
```

## Context

This took 4-5 hours to debug.

## Suggested solution

Minio should consider fields *without* `Content-Disposition` and *with* `Content-Type: text/plain; charset=...` as valid input form fields for presigned forms, just like S3 does.

Note that `<input type=file>` might be also submitted *without* `Content-Disposition` and it could be a plain-text file so a blind either-or wouldn't work either.

## My Environment

* Version used (`minio version`): 2018-11-17T01:23:48Z
* Server type and version: Minio Docker (minio/minio:latest)

**Comment by nitisht** [comment]
thanks @ztane we’ll take a look

**Comment by balamurugana** [comment]
@ztane Could you share errors printed on server console and the client?

**Comment by balamurugana** [comment]
@ztane 

For Presigned Post to work, you would need headers `x-amz-signature`, `x-amz-algorithm`, `x-amz-credential` etc.  For example below is `curl` command;
```bash
curl -X POST \
    -F bucket=abc \
    -F x-amz-date=20181124T090003Z \
    -F x-amz-signature=333c0a9cff7f856bfd0f8300c43439100b25d95c32dacda3c539c472bae19be5 \
    -F key=hello.txt \
    -F x-amz-algorithm=AWS4-HMAC-SHA256 \
    -F x-amz-credential=Q3AM3UQ867SPQQA43P2F/20181124/us-east-1/s3/aws4_request \
    -F policy=eyJleHBpcmF0aW9uIjoiMjAxOC0xMi0wMVQwODo1OTo1OC40MjZaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwiYWJjIl0sWyJlcSIsIiRrZXkiLCJoZWxsby50eHQiXSxbImVxIiwiJHgtYW16LWFsZ29yaXRobSIsIkFXUzQtSE1BQy1TSEEyNTYiXSxbImVxIiwiJHgtYW16LWNyZWRlbnRpYWwiLCJRM0FNM1VRODY3U1BRUUE0M1AyRi8yMDE4MTEyNC91cy1lYXN0LTEvczMvYXdzNF9yZXF1ZXN0Il0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAxODExMjRUMDkwMDAzWiJdXX0= \
    -F file=@/tmp/hello.txt \
    https://play.minio.io:9000/abc
```

In your pasted code, I don't see any such header creation.  I think you are not using Presigned Post instead it is just plain POST.

Please add/share more information about the problem you are facing.

**Comment by harshavardhana** [comment]
@ztane can you provide us with more information? as requested by @balamurugana

**Comment by ztane** [comment]
Hi, sorry, the POST body in my issue is just a small excerpt - if you compare it with the one generated by `curl`, the `curl` code would send

```
--------------------------0debf61b2aa697f5
Content-Disposition: form-data; name="bucket"

abc
--------------------------0debf61b2aa697f5
```

whereas the C# code (and the Windows phone browsers, for `<input type=hidden>` I presume) would generate

```
--------------------------0debf61b2aa697f5
Content-Disposition: form-data; name="bucket"
Content-Type: text/plain;charset=utf-8

abc
--------------------------0debf61b2aa697f5
```

i.e. each form-data part would have a `Content-Type: text/plain;charset=utf-8` header.

I could make the post work by capturing the full request with `nc`, then carefully *removing* all `Content-Type: text/plain;charset=UTF-8` part headers and adjusting `Content-Length` header appropriately subtracting the amount of bytes that I removed - when I used netcat to submit *that* request payload to minio, minio accepted it.

**Comment by ztane** [comment]
Sorry, now I know how to produce this easily. The clients we're using generate a request as if by

```
curl -X POST \
    -F 'bucket="abc";type=text/plain;charset=utf-8' \
    -F 'x-amz-date="20181124T090003Z";type=text/plain;charset=utf-8' \
    -F 'x-amz-signature="333c0a9cff7f856bfd0f8300c43439100b25d95c32dacda3c539c472bae19be5";type=text/plain;charset=utf-8' \
    -F 'key="hello.txt";type=text/plain;charset=utf-8' \
    -F 'x-amz-algorithm="AWS4-HMAC-SHA256";type=text/plain;charset=utf-8' \
    -F 'x-amz-credential="Q3AM3UQ867SPQQA43P2F/20181124/us-east-1/s3/aws4_request";type=text/plain;charset=utf-8' \
    -F 'policy="eyJleHBpcmF0aW9uIjoiMjAxOC0xMi0wMVQwODo1OTo1OC40MjZaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwiYWJjIl0sWyJlcSIsIiRrZXkiLCJoZWxsby50eHQiXSxbImVxIiwiJHgtYW16LWFsZ29yaXRobSIsIkFXUzQtSE1BQy1TSEEyNTYiXSxbImVxIiwiJHgtYW16LWNyZWRlbnRpYWwiLCJRM0FNM1VRODY3U1BRUUE0M1AyRi8yMDE4MTEyNC91cy1lYXN0LTEvczMvYXdzNF9yZXF1ZXN0Il0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAxODExMjRUMDkwMDAzWiJdXX0=";type=text/plain;charset=utf-8' \
    -F file=@/tmp/hello.txt \
    https://play.minio.io:9000/abc
```

From `curl` manuals:

> 
>  You can also tell curl what Content-Type to use by using 'type=', in a manner similar to:
>
> ```
> curl -F "name=daniel;type=text/foo" example.com
> ```

**Comment by harshavardhana** [comment]
Fixed by #6852

**Comment by ztane** [comment]
Hmm, is this in play.minio.io yet?

**Comment by harshavardhana** [comment]
We made a release so you can download the latest. Play is not updated yet.
