### ISSUE TITLE
Corrupted backend

### ISSUE THREAD

**Issue by mschroeder223** [minio/minio#6851]
This issue presented itself after a go application attempted to delete a bunch of objects that didn't exist followed by the bucket (which did exist). It received an error while removing the bucket because it was not empty (although the objects in it should have been removed). This immediately made minio's web ui throw "corrupted backend" errors.

I created an additional bucket and uploaded several small files into it prior to trying to remove the bucket that caused the error on removal.

When I dug into the issue further, I noticed on each node the same pattern appeared.
The first bucket, was removed from sda/b/c/d but the folder still existed on sde/f/g/h/i/j. The minio client did not list the bucket. I stopped all three nodes and manually removed the bucket's folder from all of the drives and restarted minio. The error still persisted but only when interacting with the second bucket I had created. All existing buckets were seemingly unaffected.

I tried removing the second bucket with the minio client but every request resulted in 500 errors. I again stopped all three servers, manually went through all 30 disks and removed the second bucket and the few files. Restarted the servers and the error/issue seems to have been resolved.

I spoke with kp on slack and it was suggested that I open a ticket for further analysis.

## Expected Behavior
I would have expected the first bucket removal attempt to have succeeded as each object should have been removed.

## Steps to Reproduce (for bugs)
This is the go code that might have caused the issue: https://gist.github.com/mschroeder223/042cf5f32ecee2650fef90c06ae2a26e

This is the debug output when trying to interact with the second bucket: https://gist.github.com/mschroeder223/66779e6eea1e7afc96ec0c535b813966

## Your Environment

* Version used (`minio version`): 2018-11-06T01:01:02Z
* Operating System and version (`uname -a`): Ubuntu 16.04
* 10 x 10TB disks - 3 Nodes
* Xeon E5-1650 v3 hex core - 128GB of memory

**Comment by nitisht** [comment]
Thanks @mschroeder223 we'll take a look soon

**Comment by harshavardhana** [comment]
Most probably this issue is fixed in #6855

**Comment by harshavardhana** [comment]
Closing this as fixed in #6855  - please upgrade and let us know.
