### ISSUE TITLE
copy to minio buckets very slow

### ISSUE THREAD

**Issue by Klojo** [minio/minio#6854]
## Context
The copy starts with 175mb/s and in 2 minuts is 6,5mb/s. 3 weeks ago its works fine 100mb/s...
now with the new release it fails. or it is the capi version or Minio

## Your Environment
VMWare 6.5
CloudFoundry

releases:
- name: minio
 version: v2018-11-22T02-51-56Z (https://bosh.io/releases/github.com/minio/minio-boshrelease?all=1)
- name: capi
 version: latest

stemcells:
- alias: default
 os: ubuntu-xenial
 version: latest

**Comment by harshavardhana** [comment]
How are you uploading ? Can you provide sample application ? Also can you tell what is the disk speed ? What is the backend filesystem ?

**Comment by nitisht** [comment]
closing due to no response, feel free to reopen once you have the requested information
