### ISSUE TITLE
automated test against play.minio.io?

### ISSUE THREAD

**Issue by mickael-kerjean** [minio/minio#6857]
Hello guys,

I'm maintaining [this project](https://github.com/mickael-kerjean/nuage) that's providing a nice web interface to quite a few backends including minio.
I had some report of regressions on some user's minio instance and wanted to created some integration test to minimise those. Can I perform my integration test against your play.minio.io instance?

**Comment by harshavardhana** [comment]
You can just be mindful that play.minio.io gets upgraded every week and you might see a short downtime of few secs.

**Comment by mickael-kerjean** [comment]
Sounds good to me then!
