### ISSUE TITLE
MINIO_PUBLIC_IPS doesn't accept SRV records

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#6862]
MINIO_PUBLIC_IPS requires the public IPs of the Minio cluster and doesn't accept SRV records or domains. knowing that, In CaaS based environment, the IPs are automatically assigned by docker, kubernetes, etc ...

## Current Behavior
MINIO_PUBLIC_IPS does not accept SRV records and through the following error "ERROR Unable to initialize Minio server with invalid MINIO_PUBLIC_IPS[0]: minio-cluster1: Invalid arguments specified"

## Possible Solution
MINIO_PUBLIC_IPS should accept SRV records or a new environment variable should be introduced.

## Your Environment
docker version
Client: Docker Engine - Community
Version: 18.09.0
API version: 1.39
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:47:51 2018
OS/Arch: windows/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.0
API version: 1.39 (minimum version 1.12)
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:55:00 2018
OS/Arch: linux/amd64
Experimental: false

docker run minio/minio version
Version: 2018-11-22T02:51:56Z
Release-Tag: RELEASE.2018-11-22T02-51-56Z
Commit-ID: eddf468

mc.exe version
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

**Comment by nitisht** [comment]
can you give us an example of SRV record you're passing @ahmedabt

**Comment by aeltawela** [comment]
> can you give us an example of SRV record you're passing @ahmedabt 
The error was for "minio-cluster1" but it also fails for any domain name. For example, "xyz.com"

**Comment by nitisht** [comment]
@ahmedabt `MINIO_PUBLIC_IPS` is an optional argument to allow users pass an IP address that they want Minio server(s) to assume in case they do not want to use the IPs assigned by the CaaS platform. 

So, if you leave the `MINIO_PUBLIC_IPS` field empty, Minio will automatically use the IPs assigned to the container by the CaaS platform. If you want to override these CaaS assigned IPs then use `MINIO_PUBLIC_IPS` field to pass an IP that will be used in DNS records that are fed to `etcd`

**Comment by aeltawela** [comment]
@harshavardhana @nitisht

I made an experiment now using minio client on the same docker network

Scenario 1 (without setting MINIO_PUBLIC_IPS):

/ # mc mb cluster_2/bucket2
Bucket created successfully `cluster_2/bucket2`.

/ # mc mb cluster_1/bucket1
Bucket created successfully `cluster_1/bucket1`.

/ # mc ls cluster_2
[2018-11-26 23:02:51 UTC]     0B bucket2/

/ # mc ls cluster_1
[2018-11-26 23:02:58 UTC]     0B bucket1/

---- The behavior is not as expected ----

Scenario 2 (MINIO_PUBLIC_IPS are set):

/ # mc mb cluster_2/bucket2_2
Bucket created successfully `cluster_2/bucket2_2`.

/ # mc mb cluster_1/bucket1_2
Bucket created successfully `cluster_1/bucket1_2`.

/ # mc ls cluster_1
[2018-11-26 23:05:10 UTC]     0B bucket1_2/
[2018-11-26 23:05:04 UTC]     0B bucket2_2/

/ # mc ls cluster_2
[2018-11-26 23:05:10 UTC]     0B bucket1_2/
[2018-11-26 23:05:04 UTC]     0B bucket2_2/

---- The behavior is as expected ----

**Comment by harshavardhana** [comment]
Thanks @ahmedabt

**Comment by vadmeste** [comment]
@nitisht I am able to reproduce this using my testing docker-compose file, which is similar to @ahmedabt's one, going to debug more

**Comment by nitisht** [comment]
Thanks @vadmeste

**Comment by vadmeste** [comment]
In case of gateway mode, there is no calculation of current server IP address as it is done with the distributed mode. In the distributed mode, Minio inspects the arguments list (endpoints) and can deduce the IP address of the current server, but in case of federating multiple Minio gateway instances, there is no such information.

What we can do, is that we make Minio gateway inspects all interfaces, eliminates loopbacks, and if there is one single remaining interface, we can use it.. Otherwise it should show an error.. and asks the user to explicitly set the public ip address (of course when MINIO_ETCD_ENDPOINTS is set) 

But still, it looks like it is okay if users can use domain names, probably in a new environment variable ?

**Comment by harshavardhana** [comment]
I thought the latter was already done i.e looking at interfaces and getting the IPs. Infact we have this information already in a global variable. We should always fallback when no endpoints on command line are provided.

Domain names might not be needed if you fix the current implementation properly.

**Comment by aeltawela** [comment]
@harshavardhana: it is good to failback when no endpoints are provided. On the other hand, providing domain names instead of public IPs are still necessary because the other Minio cluster could be in a completely different network that is reachable using the domain/public IP.

**Comment by harshavardhana** [comment]
> @harshavardhana: it is good to failback when no endpoints are provided. On the other hand, providing domain names instead of public IPs are still necessary because the other Minio cluster could be in a completely different network that is reachable using the domain/public IP.

Definitely, that is necessary, but we need to first fix the issue of basic requirement of not providing PUBLIC_IPS explicitly and not depending on the command line options.

**Comment by aeltawela** [comment]
@harshavardhana: question, does this PR cover the request to use domain name instead of public IP? If not, is it tracked with another ticket?

PR: https://github.com/minio/minio/pull/6918

**Comment by harshavardhana** [comment]
Adding domain names directly will not work, it requires other changes in etcd + coreDNS. Will re-open this for now.
