### ISSUE TITLE
Minio, ARQ and Synology for Backups

### ISSUE THREAD

**Issue by springsman** [minio/minio#6865]
I am new to Minio and I am using Using Minio with ARQ Backup on a Synology NAS ( https://www.arqbackup.com/blog/backup-to-synology-nas-using-minio-and-arq/ ). The issue I have is that the files and folders do not show up on the Synology interface. I cannot back up these files on the Synology if they are not selected for backup. So if they are not visible, I cannot select them. Is there a way to have the Folders/Buckets to show up in the Shared Folders in Synology? I can only see them using the Minio Browser, and that that tool is not very helpful.

The only instructions from ARQ are in the hyperlink above. When I asked for help their answer was:
"I don't know how to do that.
In any case, the Arq backup data is encrypted, compressed and de-duplicated. It's not a browsable copy of your files."

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@springsman Can you please check if https://github.com/minio/minio/issues/5561 is helpful

**Comment by springsman** [comment]
Thanks for pointing me to the link. However, I did enter the Docker Container creation commands via CLI, as the GUI does not work. Basically it is the same instructions as what I included in the Link on my original post. The issue is that after doing this the Folders do not show up on the Synology Interface. They look like they are Hidden, and I changed the Permissions, but they are still not visible. Only through the Minio Browser.

**Comment by harshavardhana** [comment]
From what it looks like @springsman Arq backup is not designed - this is according to their answer

> "I don't know how to do that.
In any case, the Arq backup data is encrypted, compressed and de-duplicated. It's not a browsable copy of your files."

**Comment by deekoder** [comment]
@springsman there is no further action on our end for this issue. I will go ahead and close this issue as a won't fix. Please feel free to reopen this issue if you want to discuss this further.
