### ISSUE TITLE
Minio goes into crash loop if mqtt credentials fail

### ISSUE THREAD

**Issue by cbluth** [minio/minio#6870]
I have minio running in kubernetes v1.12
The k8s manifest can be seen here: https://gist.github.com/cbluth/442bea8b6b9e3955bdca973db54360ee#file-minio-deployment-yaml

## Expected Behavior

I expected the minio server to run without crashing, even if it cannot connect to mqtt.
I would expect an error in the log, and the application to continue working like "normal".

## Current Behavior

It goes into crash loop.

## Possible Solution

log the error, and then ignore mqtt events.

## Steps to Reproduce (for bugs)

1. setup minio, here is a sample manifest: https://gist.github.com/cbluth/442bea8b6b9e3955bdca973db54360ee#file-minio-deployment-yaml
2. configure events for mqtt as explained here: https://docs.minio.io/docs/minio-bucket-notification-guide.html#MQTT
3. miss-spell the mqtt credentials in previous step.
4. minio crashes with this error:
```
cbluth@dl7490:~$ kubectl --context=dev -n storage logs minio-7b5bbcc968-94nc4


API: SYSTEM()
Time: 13:04:09 UTC 11/27/2018
Error: Not Authorized
       1: cmd/config-current.go:691:cmd.getNotificationTargets()
       2: cmd/notification.go:462:cmd.NewNotificationSys()
       3: cmd/server-main.go:380:cmd.serverMain()

API: SYSTEM(bucket=cbluth)
Time: 13:04:09 UTC 11/27/2018
Error: ARN 'arn:minio:sqs::1:mqtt' not found
       1: cmd/notification.go:578:cmd.readNotificationConfig()
       2: cmd/notification.go:315:cmd.(*NotificationSys).refresh()
       3: cmd/notification.go:347:cmd.(*NotificationSys).Init()
       4: cmd/server-main.go:383:cmd.serverMain()
ERROR Unable to initialize notification system: ARN 'arn:minio:sqs::1:mqtt' not found.
cbluth@dl7490:~$
```

## Context

I want minio events on my mqtt topic.

## Your Environment

* Version used (`minio version`): `minio/minio:latest`
* Environment name and version (e.g. nginx 1.9.1): k8s v1.12
* Server type and version:
* Operating System and version (`uname -a`): ubuntu 16.0 LTS
* Link to your project:

**Comment by nitisht** [comment]
> I would expect an error in the log, and the application to continue working like "normal".

@cbluth ignoring an event notification configuration and continuing like normal will give impression to users that everything is working fine (even if they made a genuine mistake and entered incorrect credentials) and then they find out that they lost event data because Minio was running - this is a bigger problem than Minio asking for correct credentials before starting up successfully. 

So, this is intended behaviour. IMHO you need to either provide correct creds or remove the event notification configuration

**Comment by nitisht** [comment]
On further discussion with @kannappanr looks like we may as well allow this, please give us some time before we discuss this internally and make a decision

**Comment by vadmeste** [comment]
@nitisht on the other side, you will lose controlling of Minio server using mc admin commands, let's discuss this in more detail

**Comment by harshavardhana** [comment]
In the new config model it is already decided we will not crash the server.

**Comment by nitisht** [comment]
> In the new config model it is already decided we will not crash the server.

Missed this somehow.

**Comment by Praveenrajmani** [comment]
Minio does not allow to set an invalid notification config. For eg, if we mis-spell the username/password and then do a `mc set`, mc fails with `mc: <ERROR> Cannot set server configuration file. mqtt(1): Not Authorized. 

We pre-check the notification targets before setting the config. [https://github.com/minio/minio/blob/f930ffe9e2fd698b8df3a38fb2bb5e1af22faacf/cmd/admin-handlers.go#L1162](url)

This happens in such cases where the notification server is down and minio tries to restart. We should not let the server crash here. Will send a PR
`
