### ISSUE TITLE
[gateway] Is it possible to use minio gateway / caching with Chinese AWS regions such as for cn-north-1?

### ISSUE THREAD

**Issue by frittentheke** [minio/minio#6873]
I would like to use _minio gateway s3_ with the Chinese AWS regions such as _cn-north-1__ or __cn-northwest-1_ but receive errors when starting up.

## Expected Behavior
I expected to require to define, apart from AWS_ACCESS_KEY and AWS_SECRET_KEY, a custom endpoint as this is different for the Chinese regions:

_cn-north-1- s3.cn-north-1.amazonaws.com.cn_
_cn-northwest-1 - s3.cn-northwest-1.amazonaws.com.cn_

mc does know the distinction as well, https://github.com/minio/mc/blob/master/vendor/github.com/minio/minio-go/s3-endpoints.go

## Current Behavior
Whatever I tried, adding or leaving out AWS_REGION or MINIO_REGION or the custom endpoint I received either:

> ERROR Unable to initialize gateway backend: The specified bucket does not exist.

>  "ERROR Unable to initialize gateway backend: The AWS Access Key Id you provided does not exist in our records.."

or even 

> ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'cn-north-1'.

when adding port 443, as in _https://s3.cn-north-1.amazonaws.com.cn:443_ to the endpoint.

## Steps to Reproduce (for bugs)

```
docker run --rm -p 9000:9000 --name minio-s3 \
-e "AWS_ACCESS_KEY_ID=redacted" \
-e "AWS_SECRET_KEY=redacted" \
-e "MINIO_ACCESS_KEY=youraccess" \
-e "MINIO_SECRET_KEY=wasgranted" \
 -e "AWS_REGION=cn-north-1" \
 -e "MINIO_REGION=cn-north-1" \
minio/minio gateway s3 https://s3.cn-north-1.amazonaws.com.cn    

```

## Context
Since the connectivity between Europe and China is quite affected by latency and also packet loss, a remote S3 bucket in cn-north-1 that needs to be accessed from across the globe would greatly benefit from the gateway and caching abilities of minio.

## Your Environment
* Version used (`minio version`): docker image with tag RELEASE.2018-11-22T02-51-56Z

**Comment by harshavardhana** [comment]
> docker run --rm -p 9000:9000 --name minio-s3 \ -e "AWS_ACCESS_KEY_ID=redacted" \ -e "AWS_SECRET_KEY=redacted" \ -e "MINIO_ACCESS_KEY=youraccess" \ -e "MINIO_SECRET_KEY=wasgranted" \ -e "AWS_REGION=cn-north-1" \ -e "MINIO_REGION=cn-north-1" \ minio/minio gateway s3 https://s3.cn-north-1.amazonaws.com.cn

Your envs are wrong @frittentheke they should be - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

**Comment by deekoder** [comment]
Hope this solves it @frittentheke Let us know.

**Comment by frittentheke** [comment]
@deekoder urgh ... sorry for not spotting this myself :-(
I could only kindly ask to maybe throw an error telling incompetent documentation readers as myself to get his variables straight.

But, unfortunately it's still not working, but the error has changed to:

> ERROR Unable to initialize gateway backend: The specified bucket does not exist..


Am I doing anything wrong regarding the endpoint for cn-north1? 
What about setting or not setting the regions for AWS and MINIO? I played with all those settings already and that seems not to be the issue.

Is there any way to get full http request logging going easily?

**Comment by kannappanr** [comment]
@frittentheke  We do not have logging for gateway backend requests currently. Will look into it and get back to you.

**Comment by kannappanr** [comment]
@frittentheke Have a fix for this.  A PR needs to be sent to `minio-go` repo first and then vendorized in minio.

**Comment by kannappanr** [comment]
Seems like the fix is already in minio-go. So, vendorizing to latest `minio-go` will fix this issue.

**Comment by kannappanr** [comment]
@frittentheke I do not have a way to test this specifically on a Chinese endpoint. But did test the fix on a different endpoint `https://s3.ca-central-1.amazonaws.com`. Can you please test the fix against one of the Chinese endpoints and let us know if it doesn't work? We expect this to work though.

**Comment by frittentheke** [comment]
@kannappanr I just ran a test using your "RELEASE.2018-11-30T03-56-59Z" version and it just works! Thanks very very much for looking into this and fixing it this quickly!
