### ISSUE TITLE
Minio WebUI does not support federation setup

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#6882]
In Minio federation mode, WebUI doesn't allow you to download/upload/browse the files which exist in the other clusters. it lists the buckets only.

## Expected Behavior
In Minio federation mode, WebUI should allow you to download/upload/browse the files which exist in the other clusters. The same way Minio client does.

## Your Environment
docker version
Client: Docker Engine - Community
Version: 18.09.0
API version: 1.39
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:47:51 2018
OS/Arch: windows/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.0
API version: 1.39 (minimum version 1.12)
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:55:00 2018
OS/Arch: linux/amd64
Experimental: false

docker run minio/minio version
Version: 2018-11-22T02:51:56Z
Release-Tag: RELEASE.2018-11-22T02-51-56Z
Commit-ID: eddf468

mc.exe version
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

**Comment by nitisht** [comment]
Thanks @ahmedabt we'll take a look and fix this.

**Comment by harshavardhana** [comment]
Was able to reproduce this. The issue is actually quite simple since for some reason we never completed the support for federation in our previous fixes.

**Comment by harshavardhana** [comment]
This is not a regression but a missing functionality, PR is sent here for the initial work - https://github.com/minio/minio/pull/6891

**Comment by nitisht** [comment]
fixed by #6891
