### ISSUE TITLE
Minio events do not work when MINIO_ETCD_ENDPOINTS is set

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#6885]
When "MINIO_ETCD_ENDPOINTS" is set in a federation mode, Minio events cannot be added.

## Current Behavior
mc events add minio/bucket1 arn:minio:sqs::1:elasticsearch
mc: <ERROR> Cannot enable notification on the specified bucket. A header you provided implies functionality that is not implemented

## Your Environment
docker version
Client: Docker Engine - Community
Version: 18.09.0
API version: 1.39
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:47:51 2018
OS/Arch: windows/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.0
API version: 1.39 (minimum version 1.12)
Go version: go1.10.4
Git commit: 4d60db4
Built: Wed Nov 7 00:55:00 2018
OS/Arch: linux/amd64
Experimental: false

docker run minio/minio version
Version: 2018-11-22T02:51:56Z
Release-Tag: RELEASE.2018-11-22T02-51-56Z
Commit-ID: eddf468

mc.exe version
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

**Comment by harshavardhana** [comment]
The minio setup here is gateway NAS which currently doesn't support notifications.
