### ISSUE TITLE
Allow free and/or total disk space to be collected

### ISSUE THREAD

**Issue by kbolino** [minio/minio#6888]
This is the inverse of #5763. That request was to remove free space info *if desired*. However, the fix removed free space info *no matter what*. I'd like to have those numbers back; it's possible to get them another way (e.g., telegraf) but that adds complication.

## Expected Behavior
Minio reports free space and/or total space on its disks, both in the UI and through prometheus metrics.

## Current Behavior
Minio reports used space on its disks (including non-minio uses of space) in the UI and through prometheus metrics, but not free or total space.

## Possible Solution
- Opt-out: report free and total space in the UI and prometheus metrics with an option to turn it off, as I would think more users would want this info than not
- Opt-in: don't report free and total space by default, but provide an option to enable them
- Automatic: detect somehow when two disks actually share the same volume and only disable free/total space metrics when this case occurs (or better yet, keep the metrics but don't double-count the space)

## Context
The lack of this info is is the number 1 complaint when users look at the web UI. I've augmented the UI with a grafana dashboard, but that means using two different UIs.

## Regression
No

## Your Environment

* Version used (`minio version`):
    ```
Version: 2018-09-12T18:49:56Z
Release-Tag: RELEASE.2018-09-12T18-49-56Z
Commit-ID: ce419c98352324caa4c79b159a9f840ca714c3d5
```
* Environment name and version (e.g. nginx 1.9.1): docker 17.09.0-ce
* Server type and version: CentOS 7
* Operating System and version (`uname -a`): Linux 4.18.12-1.el7.elrepo.x86_64 #1 SMP Thu Oct 4 09:36:51 EDT 2018 x86_64 Linux
* Link to your project: N/A

**Comment by kbolino** [comment]
My organization is still on FF 52 and the preview tab and edit button don't work. I will fix the Markdown formatting when I'm able to.

**Comment by harshavardhana** [comment]
> Minio reports used space on its disks (including non-minio uses of space) in the UI and through prometheus metrics, but not free or total space.

We cannot do that @kbolino - current UI behavior is on purpose and we cannot provide this information from our end.  Our users run Minio multiple instances sharing the same disk and information about free/total space is meaningless when such a setup is in question.

**Comment by kbolino** [comment]
I don't disagree that, for the specific case of multiple "disks" sharing the same actual volume, the metrics as previously implemented were meaningless/misleading. However, I tried to accomodate that case in my request, and provided 3 possible solutions that don't contradict what was asked for in #5763. Indeed, I am not asking for a reversion to the status quo, I am asking for the presence of a useful feature.

Moreover, I am led to question how this can be considered "intended" and "on purpose" as a primary use case when minio uses erasure coding. There is no point to erasure coding if all the disks will fail at the same time. So, while multiple disks sharing the same volume may be *a* supported use case, it seems to me that it shouldn't be the *only* use case under consideration. Putting erasure coding to good use requires disks on distinct volumes, and in that case, even the most naively collected free space metrics are useful. Of course, more sophisticated metrics would be appreciated, but not required.

**Comment by kbolino** [comment]
I may have been too hasty in my response above, and I assumed that minio's erasure coding works somewhat like RAID 6. Erasure coding may not be pointless on a single volume, if e.g. it is done at a block level and the volume itself is prone to block-level errors.

**Comment by harshavardhana** [comment]
> Moreover, I am led to question how this can be considered "intended" and "on purpose" as a primary use case when minio uses erasure coding. There is no point to erasure coding if all the disks will fail at the same time. So, while multiple disks sharing the same volume may be _a_ supported use case, it seems to me that it shouldn't be the _only_ use case under consideration. Putting erasure coding to good use requires disks on distinct volumes, and in that case, even the most naively collected free space metrics are useful. Of course, more sophisticated metrics would be appreciated, but not required.

There is no set requirement for Minio to use the entire disk a minio user can run many erasure coded deployments for the same set of disks some with using all the disks some with using a lesser number. This is called a multi-tenant deployment model. 

It is not Minio's responsibility to give disk statistics since we don't own the disk, we are not a block storage solution. If you want disk statistics run other services such as snmp etc to monitor them and give you better statistics than what we can provide.

**Comment by harshavardhana** [comment]
> There is no set requirement for Minio to use the entire disk a minio user can run many erasure coded deployments for the same set of disks some with using all the disks some with using a lesser number. This is called a multi-tenant deployment model.

As the disks get denser this has been sometimes a common deployment model as well. Minio doesn't care if you give it a full disk (mounted on a directory) or a directory inside a mounted partition. In the end, Minio is using simply a directory on the backend. It can be a mounted partition on a disk or simply a directory inside it.  These directories are either local or remote.

Total disk space and free is a disk level concept which we do not adhere to, we have no way to know what kind of disks that you use, filesystem etc (most of this information are not cross-platform friendly). It is better to run other monitoring which is specific to disks - which is perfectly capable of giving more granular information.

**Comment by kbolino** [comment]
That is fair, and I had not thought of it from that perspective. However, right now, minio does report used space, and that seems to include space not used by minio itself. Maybe that measurement needs to be dropped as well, or replaced with a "space used by the tenant" measurement?

I can start another request for this if you'd like, but if having multiple tenants on the same disk is supported, then shouldn't there be quota support also so the tenants don't clobber each other? That would also allow free/total space to be reported per-tenant.

**Comment by kbolino** [comment]
By "quota support" I mean a configuration in minio that would cap the space a tenant can use on a single disk, not necessarily or even desirably something to do with O/S disk quotas.

**Comment by harshavardhana** [comment]
> That is fair, and I had not thought of it from that perspective. However, right now, minio does report used space, and that seems to include space not used by minio itself. Maybe that measurement needs to be dropped as well, or replaced with a "space used by the tenant" measurement?

Minio calculates used space by calculating all the space that it uses on the disks, i.e including object data, metadata, parity etc.

> I can start another request for this if you'd like, but if having multiple tenants on the same disk is supported, then shouldn't there be quota support also so the tenants don't clobber each other? That would also allow free/total space to be reported per-tenant.

This is something we have tabled to be implemented in future.

**Comment by kbolino** [comment]
OK, I think I have a better understanding of minio's intended uses and why these metrics don't exist currently. Hopefully, when you implemented the tabled feature, you can also provide total/free metrics again and they will be meaningful.
