### ISSUE TITLE
Error: Invalid combination of marker ':' and prefix 'some/prefix/withMarker:'

### ISSUE THREAD

**Issue by kterusaki** [minio/minio#6896]
When running a ListObjects request and using a marker, the server throws an error.

## Expected Behavior

The server should return a result where the key has the prefix 'some/prefix/withMarker:'. For example,
something like the following result would be returned: 'some/prefix/withTrailing:andTheFollowingExt.txt`

## Current Behavior
The server throws an error with following response: `com.amazonaws.services.s3.model.AmazonS3Exception: A header you provided implies functionality that is not implemented (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented;`

## Steps to Reproduce (for bugs)
Code snippet in scala:
```
val amazonS3: AmazonS3 = new AmazonS3Client(new DefaultAWSCredentialsProviderChain)
val request = new ListObjectsRequest()
  .withBucketName("myBucket")  
  .withPrefix("some/prefix/withMarker:")
  .withMarker(":")
  .withMaxKeys(500)
val results = amazonS3.listObjects(request).getObjectSummaries.map(_.getKey).toList
```

## Context
I'm using the minio docker container as a development / testing environment.

## Your Environment

* Version used (`minio version`): RELEASE.2018-11-30T03-56-59Z
* Operating System and version: Darwin Kernel Version 17.7.0
* Link to your project:

**Comment by harshavardhana** [comment]
This is expected marker is a full object not an opaque string, marker should have the common prefix with input prefix.

**Comment by nitisht** [comment]
closing this as answered @kterusaki feel free to reopen if there are any further issues

**Comment by kterusaki** [comment]
Thanks for the response, after closer inspection it looks like we're misusing the s3 marker in our applications. I've corrected this on our end, but I'd still like to reopen the issue since the behavior when using a marker in this way still returns a 200 and results from s3. Whereas the minio s3 server returns a 501.

**Comment by harshavardhana** [comment]
> Thanks for the response, after closer inspection it looks like we're misusing the s3 marker in our applications. I've corrected this on our end, but I'd still like to reopen the issue since the behavior when using a marker in this way still returns a 200 and results from s3. Whereas the minio s3 server returns a 501.

Returning 200 is wrong because that means the request was a success, we would like to differ here and return something which is unexpected such that you can fix your application.  So we would prefer to keep it current style rather than returning 200 (which means success) and can result in silent bugs.
