### ISSUE TITLE
does minio's bucket,object have max count limit ？

### ISSUE THREAD

**Issue by miaobyte** [minio/minio#6897]
does minio's bucket,object have max count limit ？

**Comment by kannappanr** [comment]
@timeloveboy No, As far as I know, minio does not have a max limit.

**Comment by harshavardhana** [comment]
There is no max count limit, but it is advised to not use more than 100 buckets. Instead, use object prefixes to maintain the hierarchy.

**Comment by harshavardhana** [comment]
Closing as answered ..
