### ISSUE TITLE
Oracle RMAN hangs when using Minio for Azure

### ISSUE THREAD

**Issue by mariamkupa** [minio/minio#6898]
1. Created Minio application service using the steps described here https://open.microsoft.com/2017/11/09/s3cmd-amazon-s3-compatible-apps-azure-storage/

```
$ az appservice plan create \
    --name "MinioAppPlan" \
    --is-linux \
    --sku B1 \
    --resource-group "mari184V2" \
    --location "CentralUS"
```

```
$ az webapp create \
    --name "aleminio" \
    --deployment-container-image-name "minio/minio" \
    --plan "MinioAppPlan" \
    --resource-group "mari184V2"
```
	
```
$ az webapp config appsettings set \
    --settings "MINIO_ACCESS_KEY=..." "MINIO_SECRET_KEY=..." "PORT=9000" \
    --name "aleminio" \
    --resource-group "mari184V2"
```

```
$ az webapp config set \
    --startup-file "gateway azure" \
    --name "aleminio" \
    --resource-group "mari184V2"
```
	
2. Installed Oracle Secure Backup module using the following steps: https://blog.pythian.com/backup-oracle-databases-aws-s3/

`$ /u01/app/oracle/product/18.3.0/dbhome_1/jdk/bin/java -jar osbws_install.jar -AWSID ... -AWSKey ... -otnUser mariam.kupa@gmail.com     -walletDir $ORACLE_HOME/dbs/osbws_wallet     -libDir $ORACLE_HOME/lib -awsEndPoint aleminio.azurewebsites.net  -location maribucket
`
The same module works with AWS and I am able to back up the database. But it hangs when using Minio.

RMAN script that is working with AWS but hangs with Minio is the following:

```
run{
  allocate channel c1 device type sbt parms='SBT_LIBRARY=libosbws.so,SBT_PARMS=(OSB_WS_PFILE=/u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbwsorcl1.ora)';
  backup current controlfile;
  }
```
  
Where /u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbwsorcl1.ora file contains:

```
OSB_WS_HOST=http://aleminio.azurewebsites.net
#OSB_WS_LOCATION=maribucket
OSB_WS_BUCKET=maribucket
OSB_WS_VIRTUAL_HOST=FALSE
OSB_WS_WALLET='location=file:/u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbws_wallet CREDENTIAL_ALIAS=_aws'
```

After some time the following error is returned by RMAN:

```
ORA-27192: skgfcls: sbtclose2 returned error - failed to close file
ORA-19511: non RMAN, but media manager or vendor specific failure, error text:
   LHT-00027: Key not found in hash table.
LHT-00027: Key not found in hash table.
LHT-00027: Key not found in hash table.
```

During RMAN backup I have noticed that metadata files are created in the Azure container through Minio, moreover from database I see that RMAN reads datafile but is not able to write backup into Azure container. 

How can I trace what happens on Minio application service, why it hangs?

**Comment by kannappanr** [comment]
@mariamkupa We will look into this issue and get back to you. 

The REST API calls that are received by `Minio` can be logged by setting the environment variable `MINIO_HTTP_TRACE=/path/to/log/file` and then restarting minio.

**Comment by vadmeste** [comment]
@mariamkupa also are you seeing any log in Minio server output ?

**Comment by mariamkupa** [comment]
> @mariamkupa We will look into this issue and get back to you.
> 
> The REST API calls that are received by `Minio` can be logged by setting the environment variable `MINIO_HTTP_TRACE=/path/to/log/file` and then restarting minio.

@kannappanr where should I describe/put this variable?

**Comment by kannappanr** [comment]
@mariamkupa Can you try modifying

```
$ az webapp config appsettings set \
    --settings "MINIO_ACCESS_KEY=..." "MINIO_SECRET_KEY=..." "PORT=9000" \
    --name "aleminio" \
    --resource-group "mari184V2"

```
to

```
$ az webapp config appsettings set \
    --settings "MINIO_ACCESS_KEY=..." "MINIO_SECRET_KEY=..."  "MINIO_HTTP_TRACE=..." "PORT=9000" \
    --name "aleminio" \
    --resource-group "mari184V2"
```

**Comment by mariamkupa** [comment]
I am not able to ssh yet :)  getting this from web ssh console

![image](https://user-images.githubusercontent.com/7306748/49375647-67f52a00-f71e-11e8-9998-7b57792b397c.png)

I've even tried by this way:

```
[root@rac1 ~]# az webapp remote-connection create -g mari184V2 -n aleminio 
Auto-selecting port: 32155
WARNING - Remote debugging may not be setup properly. Reponse content: FAILURE:2222:Unable to connect to WebApp
SSH is available { username: root, password: Docker! }
Start your favorite client and connect to port 32155
Websocket tracing disabled, use --verbose flag to enable
```
```
[root@rac1 ~]# ssh root@localhost -p 32155
ssh_exchange_identification: Connection closed by remote host
```

I will try to solve this first and will come back for the main problem..

Thank you for helping!

**Comment by mariamkupa** [comment]
@kannappanr @vadmeste have you ever had the above problem during connection to Minio Application service?  I mean problem during "sshing" to Minio app service? 
Is there any other way to retrieve this log file that was set by MINIO_HTTP_TRACE parameter?

**Comment by mariamkupa** [comment]
I was not able to solve ssh problem but I got the following logs: 

> 2018-12-03T22:30:42.735467236Z 
> 2018-12-03T22:30:42.735525138Z API: SYSTEM()
> 2018-12-03T22:30:42.735534438Z Time: 22:30:42 UTC 12/03/2018
> 2018-12-03T22:30:42.735542238Z Error: xml: encoding "US-ASCII" declared but Decoder.CharsetReader is nil
> 2018-12-03T22:30:42.735550138Z        1: cmd/handler-utils.go:44:cmd.parseLocationConstraint()
> 2018-12-03T22:30:42.735557539Z        2: cmd/auth-handler.go:272:cmd.checkRequestAuthType()
> 2018-12-03T22:30:42.735565739Z        3: cmd/bucket-handlers.go:411:cmd.objectAPIHandlers.PutBucketHandler()
> 2018-12-03T22:30:42.735573239Z        4: cmd/api-router.go:100:cmd.(objectAPIHandlers).PutBucketHandler-fm()
> 2018-12-03T22:30:42.735580839Z        5: pkg/handlers/http-tracer.go:144:handlers.TraceReqHandlerFunc.func1()
> 2018-12-03T22:30:42.735588240Z        6: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()


![image](https://user-images.githubusercontent.com/7306748/49405757-d6f96f80-f76c-11e8-85da-1e707b939767.png)

**Comment by kannappanr** [comment]
@mariamkupa Will look into this and get back to you. Is it possible for you to test with a regular minio binary instead of one on Azure?

**Comment by mariamkupa** [comment]
@kannappanr Thank you!

Good news is that if I do by the following way:

```
# ./minio  gateway azure
...
Endpoint: ...  http://127.0.0.1:9000 ...
```

and then change osbwsorcl1.ora file that is used by RMAN for contacting media library:

> #OSB_WS_HOST=http://aleminio.azurewebsites.net
> **OSB_WS_HOST=http://127.0.0.1:9000**
> #OSB_WS_LOCATION=maribucket
> OSB_WS_BUCKET=maribucket
> OSB_WS_VIRTUAL_HOST=FALSE
> OSB_WS_WALLET='location=file:/u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbws_wallet CREDENTIAL_ALIAS=_aws'

Then it works:

```
RMAN> run{
  allocate channel c1 device type sbt parms='SBT_LIBRARY=libosbws.so,SBT_PARMS=(OSB_WS_PFILE=/u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbwsorcl1.ora)';
  backup current controlfile;
  }2> 3> 4> 

allocated channel: c1
channel c1: SID=153 instance=orcl1 device type=SBT_TAPE
channel c1: Oracle Secure Backup Web Services Library VER=12.2.0.2
...
Finished backup at 04-DEC-18
```
Which is great of course!!

But before this step there is one more step to install this media libary(2nd step in my initial post) that works when using Minio App Service and does not work with Minio binary:

#Minio App Service

```
[oracle@rac1 swtmp]$ /u01/app/oracle/product/18.3.0/dbhome_1/jdk/bin/java -jar osbws_install.jar     -AWSID ...     -AWSKey ...     -otnUser mari@gmail.com     -walletDir $ORACLE_HOME/dbs/osbws_wallet     -libDir $ORACLE_HOME/lib -awsEndPoint aleminio.azurewebsites.net  -location maribucket
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
AWS credentials are valid.
Oracle Secure Backup Web Service wallet created in directory /u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbws_wallet.
Oracle Secure Backup Web Service initialization file /u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbwsorcl1.ora created.
Downloading Oracle Secure Backup Web Service Software Library from file osbws_linux64.zip.
Download complete.
```

##Minio binary

First try using **-awsEndPoint http://127.0.0.1 -awsPort 9000** option:

```
[oracle@rac1 swtmp]$ /u01/app/oracle/product/18.3.0/dbhome_1/jdk/bin/java -jar osbws_install.jar     -AWSID ...     -AWSKey ...    -otnUser mari@gmail.com     -walletDir $ORACLE_HOME/dbs/osbws_wallet     -libDir $ORACLE_HOME/lib -awsEndPoint http://127.0.0.1 -awsPort 9000  -location maribucket
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: URI can't be null.
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1506)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3036)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at com.amazon.s3.ListBucketResponse.<init>(ListBucketResponse.java:113)
	at com.amazon.s3.AWSAuthConnection.listBucket(AWSAuthConnection.java:283)
	at com.amazon.s3.AWSAuthConnection.listBucket(AWSAuthConnection.java:261)
	at com.amazon.s3.AWSAuthConnection.connect(AWSAuthConnection.java:825)
	at oracle.backup.s3.install.S3Config.s3Connect(S3Config.java:447)
	at oracle.backup.s3.install.S3Config.doConfig(S3Config.java:228)
	at oracle.backup.s3.install.S3Config.main(S3Config.java:212)
Caused by: java.lang.IllegalArgumentException: URI can't be null.
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 7 more
```
The second try with  **-awsEndPoint http://127.0.0.1:9000** 

```
[oracle@rac1 swtmp]$ /u01/app/oracle/product/18.3.0/dbhome_1/jdk/bin/java -jar osbws_install.jar     -AWSID ...     -AWSKey ...     -otnUser mari@gmail.com     -walletDir $ORACLE_HOME/dbs/osbws_wallet     -libDir $ORACLE_HOME/lib -awsEndPoint http://127.0.0.1:9000  -location maribucket
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: URI can't be null.
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1506)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3036)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at com.amazon.s3.ListBucketResponse.<init>(ListBucketResponse.java:113)
	at com.amazon.s3.AWSAuthConnection.listBucket(AWSAuthConnection.java:283)
	at com.amazon.s3.AWSAuthConnection.listBucket(AWSAuthConnection.java:261)
	at com.amazon.s3.AWSAuthConnection.connect(AWSAuthConnection.java:825)
	at oracle.backup.s3.install.S3Config.s3Connect(S3Config.java:447)
	at oracle.backup.s3.install.S3Config.doConfig(S3Config.java:228)
	at oracle.backup.s3.install.S3Config.main(S3Config.java:212)
Caused by: java.lang.IllegalArgumentException: URI can't be null.
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 7 more
```

**Comment by vadmeste** [comment]
@mariamkupa it looks like more a setup issue with Oracle, I will try to run it on my end.

**Comment by mariamkupa** [comment]
@vadmeste thank you.

By the way how to pronounce Minio? :) Is it [minio] or [minaio]?

You are just great!

**Comment by mariamkupa** [comment]
How to start minio binary on https instead of http?

**Comment by vadmeste** [comment]
@mariamkupa, basically I believe this is a bug in oracle installer itself,

 `Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: URI can't be null.` 

The error happens when you pass an url -awsEndPoint http://127.0.0.1:9000, so you need to drop http and the port number from that argument

I didn't successfully 
```
✔ ~/work/oracle-install
19:04 $ java -jar osbws_install.jar -AWSID xxx -AWSKey xxx -walletDir $ORACLE_HOME/osbws_wallet -libDir $ORACLE_HOME/lib -awsEndPoint xxxx.azurewebsites.net -location "us-east-1" -otnUser xxxx@gmail.com -otnPass
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
  Warning: Could not determine current platform:
           os.name = linux, os.arch = unknown
AWS credentials are valid.
Oracle Secure Backup Web Service wallet created in directory /home/vadmeste/work/oracle/osbws_wallet.
Oracle Secure Backup Web Service initialization file /home/vadmeste/work/oracle/dbs/osbwse6721a76-f97d-11e8-89bb-abf92d000d83.ora created.
Skipping library download because platform cannot be determined.
Please use option -libplatform to specify the platform if to download the library.
```

To use HTTPS, you can following this link: https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls.html

**Comment by mariamkupa** [comment]
@vadmeste the best solution would be if Minio App Service works. Not binary but App Service, that will be simplest solution. 

What have you indicated here? "xxxx.azurewebsites.net" did you setup App service ? 

I will try using https.

**Comment by mariamkupa** [comment]
@vadmeste, please tell me if I am doing something wrong:

1. Generated a Certificate using generate_cert.go:
```
# go run generate_cert.go -ca --host "192.168.1.1"
2018/12/06 19:42:08 wrote cert.pem
2018/12/06 19:42:08 wrote key.pem
```

2. Renamed cert.pem to public.crt and key.pem to private.key:

```
# mv cert.pem public.crt
# mv key.pem  private.key
```

3. Placed certificates in ~/.minio/certs/CAs/

```
# mv public.crt ~/.minio/certs/CAs/
# mv private.key   ~/.minio/certs/CAs/
```

4. Started minio binary:

```
# export MINIO_ACCESS_KEY=...
# export MINIO_SECRET_KEY=...
# ./minio  gateway azure

Endpoint:  http://<some ip>:9000  http://<some ip>:9000  http://<some ip>:9000  http://192.168.1.1:9000  http://127.0.0.1:9000
```

so it still started on http, but I need https, am I doing anything wrong?

**Comment by mariamkupa** [comment]
There is one more interesting point that I should mention. 

As I said previously:
1. media library installation works with **Minio App Service**, but does not work with **Minio binary**. 
2. RMAN backup works with **binary** but does not work with **App Service**, but let's stop here:

If after the 1st step I do not change the following parameter in `/u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbwsorcl1.ora`

from 

`OSB_WS_LOCATION=maribucket`

to 

`OSB_WS_BUCKET=maribucket`

Then RMAN will not work(I mean even with binary). During that time running Minio binary writes the following error in the console:

> API: SYSTEM()
> Time: 20:06:17 UTC 12/06/2018
> Error: xml: encoding "US-ASCII" declared but Decoder.CharsetReader is nil
>        1: cmd/handler-utils.go:43:cmd.parseLocationConstraint()
>        2: cmd/auth-handler.go:250:cmd.checkRequestAuthType()
>        3: cmd/bucket-handlers.go:411:cmd.objectAPIHandlers.PutBucketHandler()
>        4: cmd/api-router.go:100:cmd.(objectAPIHandlers).PutBucketHandler-fm()
>        5: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

![image](https://user-images.githubusercontent.com/7306748/49609112-06e68400-f9b4-11e8-91d1-45fe6a00daed.png)

So if after the 1st step I modify this parameter and also OSB_WS_HOST parameter to indicate Minio binary then everything is ok. 

And if we recall what error is returned when App service is used during RMAN backup(2nd step) we notice that the error is the same as I mention here with even correct OSB_WS_BUCKET parameter. 

So I think this should be related with Minio and not with Oracle, when Minio returns this error Oracle is not able to backup. 

P.S. I am talking about backup procedure should be related with Minio not Oracle. But the library installation is completely different.  The library installation may need https endpoint and not http, that is why I am trying to configure https.

**Comment by vadmeste** [comment]
>     1. Placed certificates in ~/.minio/certs/CAs/

You should put certificates in ~/.minio/certs/, not CAs/

I am still trying to reproduce: 
`Error: xml: encoding "US-ASCII" declared but Decoder.CharsetReader is nil`

and it is weird to have this error because your tool seems to be using AWS SDK, which is known to work perfectly with Minio, we didn't see this before. I will investigate further and update you

**Comment by vadmeste** [comment]
> What have you indicated here? "xxxx.azurewebsites.net" did you setup App service ?

By the way, yes, I did setup the App service, and I have an Minio endpoint which points to Azure blob storage, it works fine with mc

**Comment by mariamkupa** [comment]
@vadmeste I was able to configure https endpoint by your advice thank you. 

```
[root@rac1 ~]# ./minio  gateway azure 
Endpoint: ...https://127.0.0.1:9000...
```

But still not able to indicate it in Library download script getting the same error. Trying to find correct parameters. 

I do appreciate your help about `Error: xml: encoding "US-ASCII" declared but Decoder.CharsetReader is nil `

**Comment by mariamkupa** [comment]
I am almost close to the solution:

1. I have started minio on http again instead of https, because with App service I have found using netstat that the connection is established on port 80. 

2. Instead of 9000 I used port :80

```
[root@rac1 ~]# ./minio  gateway azure --address :80
...http://127.0.0.1..
```

3. Now I see that AWS credentials are valid but getting Connection refused error. 

```
[oracle@rac1 swtmp]$ /u01/app/oracle/product/18.3.0/dbhome_1/jdk/bin/java -jar osbws_install.jar     -AWSID ...     -AWSKey ...     -otnUser mari@gmail.com     -walletDir $ORACLE_HOME/dbs/osbws_wallet     -libDir $ORACLE_HOME/lib -awsEndPoint 127.0.0.1 -location maribucket 
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
AWS credentials are valid.
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at oracle.backup.util.FileDownload.getCertificates(FileDownload.java:305)
	at oracle.backup.util.CreateWallet.getCertificate(CreateWallet.java:242)
	at oracle.backup.util.CreateWallet.createWallet(CreateWallet.java:157)
	at oracle.backup.s3.install.S3Config.createWallet(S3Config.java:535)
	at oracle.backup.s3.install.S3Config.doConfig(S3Config.java:234)
	at oracle.backup.s3.install.S3Config.main(S3Config.java:212)
```

Error has changed 💪  😄

**Comment by vadmeste** [comment]
For this error `Error: xml: encoding "US-ASCII" declared but Decoder.CharsetReader is nil `, can you test this image instead `vadmeste/minio:oracle` ? I believe this would fix that error you are seeing

**Comment by mariamkupa** [comment]
1. I created App Service by indicating image `vadmeste/minio:oracle`
	
	az webapp create \
    --name "aleminio" \
    --deployment-container-image-name "vadmeste/minio:oracle" \
    --plan "MinioAppPlan" \
    --resource-group "mari184V2"

2. I do not see error on App Service but RMAN still hangs on the same step.

**Comment by vadmeste** [comment]
@mariamkupa it looks like osbws installer has a bug and really needs https even if -useHTTPS flag is not passed.

Running local Minio gateway:

```
MINIO_ACCESS_KEY="xxxx" MINIO_SECRET_KEY="xxxx" minio gateway azure --address ":443"
```

Running osbws_install
```
19:51 $ java -jar osbws_install.jar -AWSID "xxx" -AWSKey "xxx" -walletDir $ORACLE_HOME/osbws_wallet -libPlatform linux64 -libDir $ORACLE_HOME/lib -awsEndPoint minio -awsPort 443 -useHTTPS -location "us-east-1" -otnUser xxxx@gmail.com -otnPass
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
AWS credentials are valid.
Oracle Secure Backup Web Service wallet created in directory /home/xxx/work/oracle/osbws_wallet.
Oracle Secure Backup Web Service initialization file /home/xxx/work/oracle/dbs/osbws04b814a4-fa3c-11e8-ba72-9b65aaac46e1.ora created.
Downloading Oracle Secure Backup Web Service Software Library from file osbws_linux64.zip.
```

However, you need to ask java to trust Minio certificate (since it is self signed), in my system, I do this way:
```
sudo keytool -import -trustcacerts -alias minio-ca -file ~/.minio/certs/public.crt -keystore /usr/lib/jvm/default-java/jre/lib/security/cacerts
``` 
(by default, the asked password is `changeit`)

**Comment by mariamkupa** [comment]
I was searching that, to make self-signed certificate trusted, Thank you!!! I will try and write to you soon. You are rock @vadmeste !

**Comment by mariamkupa** [comment]
@vadmeste downloading library works definitely. Thank you for that! 

But now RMAN does not work:

> RMAN> run{
>   allocate channel c1 device type sbt parms='SBT_LIBRARY=libosbws.so,SBT_PARMS=(OSB_WS_PFILE=/u01/app/oracle/product/18.3.0/dbhome_1/dbs/osbwsorcl1.ora)';
>   backup current controlfile;
>   }2> 3> 4> 
> 
> RMAN-00571: ===========================================================
> RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
> RMAN-00571: ===========================================================
> RMAN-03009: failure of allocate command on c1 channel at 12/07/2018 20:58:11
> ORA-19554: error allocating device, device type: SBT_TAPE, device name: 
> ORA-27023: skgfqsbi: media manager protocol error
> ORA-19511: non RMAN, but media manager or vendor specific failure, error text:
>    KBHS-00715: HTTP error occurred 'oracle-error'
> KBHS-00712: ORA-24263 received from local HTTP service
> 

So RMAN tries to use HTTP connection, unfortunately. It is not Minio problem definitely. But I would ask you if it is possible to start Minio on http and https at the same time, I may be asking strange thing but see what happens when App Service is used during download:

```
1.  # nslookup aleminio.azurewebsites.net

<some public ip address>
```

2. During downloading library with `-awsEndPoint aleminio.azurewebsites.net` option,  netstat has the following output:
```
[root@rac1 ~]# netstat -na -c |grep <some public ip address>
tcp        0      0 <my ip address>:38386       <some public ip address>:80       ESTABLISHED
tcp        0      0 <my ip address>:18913       <some public ip address>:443      ESTABLISHED
tcp        0      0 <my ip address>:38386      <some public ip address>:80       ESTABLISHED
tcp        0      0 <my ip address>:18913       <some public ip address>:443      ESTABLISHED
tcp        0       0<my ip address>:38386       <some public ip address>:80       ESTABLISHED
tcp        0      0 <my ip address>:18913       <some public ip address>:443      ESTABLISHED
```

It uses one by one http and https.

**Comment by mariamkupa** [comment]
@vadmeste let's say we are using http instead of https(because RMAN works with minio binary started on http ). 

1. `[root@rac1 ~]# ./minio  gateway azure --address :80`

For simplicity I will take one of the ip address not localhost  from endpoints(because on localhost there is a lot of traffic). 

`http://192.168.1.1`

3. Trying to download

```
[oracle@rac1 swtmp]$ /u01/app/oracle/product/18.3.0/dbhome_1/jdk/bin/java -jar osbws_install.jar -AWSID ...  -AWSKey ...     -otnUser mari@gmail.com     -walletDir $ORACLE_HOME/dbs/osbws_wallet     -libDir $ORACLE_HOME/lib -awsEndPoint 192.168.1.1  -location maribucket
Oracle Secure Backup Web Service Install Tool, build 12.2.0.1.0DBBKPCSBP_2018-06-12
AWS credentials are valid.
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at oracle.backup.util.FileDownload.getCertificates(FileDownload.java:305)
	at oracle.backup.util.CreateWallet.getCertificate(CreateWallet.java:242)
	at oracle.backup.util.CreateWallet.createWallet(CreateWallet.java:157)
	at oracle.backup.s3.install.S3Config.createWallet(S3Config.java:535)
	at oracle.backup.s3.install.S3Config.doConfig(S3Config.java:234)
	at oracle.backup.s3.install.S3Config.main(S3Config.java:212)
```

getting `Connection refused` error.

4. netstat shows the following ports:

```
# netstat -na -c |grep 192.168.1.1

tcp        0      0 192.168.1.1:31797       192.168.1.1:80          ESTABLISHED
tcp        0      0 192.168.1.1:80          192.168.1.1:31797       ESTABLISHED
tcp        0      0 192.168.1.1:31797       192.168.1.1:80          TIME_WAIT  
tcp        0      0 192.168.1.1:31797       192.168.1.1:80          TIME_WAIT  
tcp        0      0 192.168.1.1:31797       192.168.1.1:80          TIME_WAIT
```

**Comment by vadmeste** [comment]
Basically, there is no problem to run two Minio *gateway* instances and point to the same Azure blob storage (it is possible only because it is a Minio gateway and not a Minio server)

So currently, let's run two instances at the same time:
`minio gateway --address ":80" azure`
`minio gateway --address ":443" azure`

**Comment by mariamkupa** [comment]
@vadmeste it works now. As I see to start minio on HTTP I must remove certificate and key from ~/.minio/certs, correct? 

1.  I have certificate and key in place and running minio:

`# ./minio  gateway azure --address :443
`
started on https

2. Removed certificate/key from ~/.minio/certs, otherwise minio starts on https again

`# ./minio gateway --address ":80" azure
`
started on HTTP

3. For download used `-useHttps` option, the download was successful.

4. For RMAN backup changed the following parameter:

From: `OSB_WS_HOST=https://192.168.1.1`

to: `OSB_WS_HOST=http://192.168.1.1`

Now RMAN also works. 

Thank you for your quick answers and such a great effort. 

What I don't like is that I must remove certificate  manually to start minio on http.. do you know any simple way, like indicating minio to start on HTTP as parameter/option?

**Comment by kannappanr** [comment]
@mariamkupa You do not have to remove the certificate. By default the `certs` are stored in `~/.minio/certs` folder. But you can specify a custom folder `./minio --config-dir /path/custom/ gateway --address ":80" azure `

**Comment by mariamkupa** [comment]
@vadmeste @kannappanr Thank you very much! 

I am satisfied with the workaround. We can close this issue. 

In conclusion:

1. We start Minio on HTTPS and use this endpoint for library download. 
2. Another Minio will be started on HTTP that will be used by RMAN
3. We can stop HTTPS Minio, because it is only necessary for the initial download. 

I will post detailed instructions on my blog also, it will be interesting. Thank you!

**Comment by vadmeste** [comment]
Reopening this since we probably need to support different encoding.. I need to see if AWS SDK supports setting xml encoding
