### ISSUE TITLE
Infinite redirect with MINIO_BROWSER=off to http(s)://host/minio/minio/minio/minio/minio/...

### ISSUE THREAD

**Issue by tilpner** [minio/minio#6907]
With `MINIO_BROWSER=off`, accessing non-existing locations with a browser results in a "Too many redirects" error, after being redirected to `http(s)://host/minio/minio/minio/...`.

## Expected Behavior

With `MINIO_BROWSER=off`, accessing non-existing locations should result in an "Access denied"/"Not found" or similar error. Like it happened in previous versions.

## Current Behavior

With `MINIO_BROWSER=off`, accessing non-existing locations with a browser results in a "Too many redirects" error, after being redirected to `http(s)://host/minio/minio/minio/...`.

## Possible Solution

Don't redirect at all, when the browsing UI is off.

## Steps to Reproduce (for bugs)

1. Install minio 2018-11-30T03-56-59Z
2. Set MINIO_BROWSER=off
3. Navigate with a browser (not curl!) to a non-existing locations (e.g. /)

## Context

This infinite redirect is much more confusing to an end-user than a simple error.

## Regression

Yes, #6848 may have caused this, and it may be a recurrence of #2837.

## Your Environment

* Version used (`minio version`): 2018-11-30T03-56-59Z
* Operating System and version: NixOS 19.03pre

**Comment by hebra** [comment]
I can confirm this behaviour with ```MINIO_BROWSER=off``` and a public bucket policy sets ```s3:ListBucket``` to Deny but ```s3:GetObject``` (for accessing an object directly via link) to Allow.

**Comment by harshavardhana** [comment]
this should be already fixed with #6909
