### ISSUE TITLE
deploy minio on server

### ISSUE THREAD

**Issue by Danbuth** [minio/minio#6911]
The scene is：
deploy minio services with docker swarm(like 1*4), and I want the disk space on each node server is large enough.
the disk on the node server build with RAID. Which type of  RAID suitable for the scene.

I have no idea, thinks.

**Comment by nitisht** [comment]
> deploy minio services with docker swarm(like 1*4), and I want the disk space on each node server is large enough.

If you deploy Minio in this manner, Minio uses erasure coding [https://docs.minio.io/docs/minio-erasure-code-quickstart-guide.html] to protect the data, hence RAID is not required in this scenario

**Comment by Danbuth** [comment]
> > deploy minio services with docker swarm(like 1*4), and I want the disk space on each node server is large enough.
> 
> If you deploy Minio in this manner, Minio uses erasure coding [https://docs.minio.io/docs/minio-erasure-code-quickstart-guide.html] to protect the data, hence RAID is not required in this scenario

thinks at first.
Yes, I know this type of deployment.
But the situation is : 
Each disk may only have 1T of space. With distributed Minio on swarm need to start 1024 services of minio to form a 1PB minio service. Is this unreasonable?

**Comment by nitisht** [comment]
> Each disk may only have 1T of space. With distributed Minio on swarm need to start 1024 services of minio to form a 1PB minio service. Is this unreasonable?

You can achieve this using a single service or multiple Minio services - depending on the architecture you like. A single Minio distributed service with 32 Nodes and 64 drives each (1T / drive) will have 1 PB of usable storage space (with default N/2 erasure coding).

**Comment by Danbuth** [comment]
thinks very much
