### ISSUE TITLE
When send a DELETE request to tusd with minio s3 storage backend, how do I remove associated multipart and tmp resources?

### ISSUE THREAD

**Issue by dcs3spp** [minio/minio#6913]
Hi,

I am a newbie using tusd for serving uploaded files on minio S3 storage with uppy incorporated into the front end with the tus plugin. So far, finding all of these excellent, they have made development much easier. The details of the environment are as follows:

- MacOs High Sierra 10.13.6
- Tusd running within a docker container behind an nginx proxy. Tusd is configured to use minio S3 storage backend.
- Minio RELEASE.2017-10-27T18-59-02Z running within a docker container.

I am struggling with the process of implementing removal of associated resources for an uploaded file. I have used the Rested plugin in Opera browser to send a DELETE request to tusd which then sends request to minio to delete associated object and meta data. Both the file object and associated metadata info file are removed for the DELETE request as expected.

However, upon inspecting the minio /data folder there are two folders: multipart and tmp located within .minio.sys. Each upload seems to create a subfolder within multipart and sometimes tmp. The subfolders appear to be empty after a successful upload and do not appear to be removed with a DELETE request. I have noticed that upon restarting minio the subfolders in tmp are removed.

Is there any way that I can remove these folder resources when a DELETE request is issued? How can I trigger the removal of these empty subfolders without restarting minio?

Kind regards

dcs3spp

**Comment by harshavardhana** [comment]
tmp and multipart are only cleared upon bucket deletes explicitly. Not object deletes, tmp and multipart directories are also cleared once every two weeks automatically.

**Comment by kannappanr** [comment]
@dcs3spp sub-directories in `tmp` and `multipart` folders are not deleted upon bucket removal in `fs` mode currently. This could be regression. We will take a look into this and fix it.

**Comment by dcs3spp** [comment]
Thanks for responding, @harshavardhana and @kannappanr.

So to confirm, ```tmp``` and ```multipart``` folders are deleted only when their owner bucket is removed. There is currently no mechanism to delete these associated folders directly as part of a DELETE request for an object in a bucket. The current practice is that the  subfolders in _multipart_ and _tmp_ are deleted automatically every two weeks. @kannappanr has raised the issue that  the ```tmp``` and ```multipart``` subfolders are not automatically deleted when a bucket is removed. Is that correct?

Is the time period of two weeks configurable and are the empty sub folders deleted/purged automatically every two weeks?

Is it possible/feasible in the future to purge/delete associated multipart and tmp subfolders upon DELETE request for an object?

Apologies, @kannappanr, not sure how, but according to issue history it seems that I have accidentally unassigned @sinhaashish, somehow?? Not sure how this happened. Is it possible to reassign him?

Kind regards,

dcs3spp

**Comment by kannappanr** [comment]
@dcs3spp `tmp` and `multipart` folders themselves will not be deleted. The `subfolders` (`inactive uploads`) in `multipart` and `tmp` are deleted every two weeks.

I don't think the time period is configurable.

We will check if we can delete the folder upon successful upload of an object.

**Comment by dcs3spp** [comment]
Many thanks @kannappanr 👍 
For info, I originally raised question/issue on tusd github [here](https://github.com/tus/tusd/issues/221). 

I am sending the DELETE request to tusd, which then deletes the associated object from minio backend. Tusd has completed the upload since there are no incomplete uploads listed with
```mc ls --incomplete```. Furthermore, the object file is deleted from minio. Just the empty subfolders for that object, in ```multipart``` and ```tmp```, remain.

Kind regards

dcs3spp

**Comment by nitisht** [comment]
Closing as fixed by https://github.com/minio/minio/pull/6961 . @dcs3spp can you try latest Minio release and confirm if it works.

Feel free to reopen if there are further issues

**Comment by dcs3spp** [comment]
Many thanks @nitisht,

Have just tried performing an upload using the latest version of minio, 2019-01-23T23:18:58Z

When the upload has completed there is now no empty subfolder in `multipart`. Looking good....
Upon startup there is an empty folder in */data/.minio.sys/tmp*, however this was the case when running with older version, e.g. 2018-11-30T03:56:59Z. 

So far, no new empty subfolders being created under */data/.minio.sys/tmp* after uploading.
 Will keep monitoring this over time and will notify if any issues.

Many thanks to @sinhaashish and @kannappanr. Appreciated 👍 

Kind regards

dcs3spp
