### ISSUE TITLE
Cannot start large number of disks with docker-compose

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#6915]
When starting docker-compose with a large amount of disks, minio never starts (just continually shows "Waiting for <n> disks to come online"
## Expected Behavior

Minio should be able to start regardless of amount of disks added, or should error out properly
## Current Behavior

Continual printing of error messages like:
```
minio6_1   | Waiting for a minimum of 192 disks to come online (elapsed 5m33s)
minio6_1   | 
minio15_1  | Waiting for a minimum of 192 disks to come online (elapsed 5m36s)
minio15_1  | 
minio6_1   | Waiting for a minimum of 192 disks to come online (elapsed 5m34s)
minio6_1   | 
minio5_1   | Waiting for a minimum of 192 disks to come online (elapsed 5m35s)
minio5_1   | 
minio2_1   | Waiting for a minimum of 192 disks to come online (elapsed 5m35s)
minio2_1   | 
minio1_1   | Waiting for a minimum of 192 disks to come online (elapsed 5m37s)
minio1_1   | 
minio9_1   | Waiting for a minimum of 192 disks to come online (elapsed 5m39s)
```
## Possible Solution

Unsure
## Steps to Reproduce (for bugs)

1.  Create docker compose file with large amount of disks (tested with 2 nodes / 64 disks each)
2. `docker-compose up`

## Regression

Unsure
## Your Environment

* Version used (`minio version`):  minio/minio:RELEASE.2018-11-30T03-56-59Z
* Operating System and version (`uname -a`):
Tested with RHEL 7.6 and Ubuntu 18.04.  Ubuntu system has 4 cores / 8GB RAM , RHEL system has 88 cores, 256GB RAM
docker-compose file:
[docker-compose.txt](https://github.com/minio/minio/files/2641738/docker-compose.txt)

This works if you increase the amount of containers and decrease the amount of disks, note that the volumes presented are all the same backend disk, not physically unique

**Comment by harshavardhana** [comment]
Reproduced this @eco-minio looks like a bug
