### ISSUE TITLE
cache on download does not work in federation mode

### ISSUE THREAD

**Issue by poornas** [minio/minio#6916]
## Expected Behavior

In a federated setup, with cluster 1 and cluster 2, where cluster 2 has disk cache enabled, downloading a file that exists in cluster 1 from cluster 2 should cache the object locally.
## Current Behavior

This is not happening because the bucket forwarding handler middleware routes the request to the cluster that has the bucket (cluster 1) and this never touches the caching layer.
## Steps to Reproduce (for bugs)

1. start etcd by following https://github.com/minio/minio/blob/master/docs/sts/etcd.md
2. Follow https://github.com/minio/minio/tree/master/docs/federation/lookup to set up 2 clusters 
3. Start cluster 2 with MINIO_CACHE_DRIVES set
4. create bucket1 on cluster 1 and upload object1 via mc. 
5. Then ```mc cat cluster2/bucket1/object1```  from cluster 2. 
object1 should be on the cache folder, but is not.hand version (`uname -a`):

## Regression
  No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by aeltawela** [comment]
@poornas: also it makes sense to have a flag dedicated to caching remote files in federation setup only because I noticed it caches everything including the local mount points.

**Comment by harshavardhana** [comment]
We have decided to not implement caching in this manner when federation is involved, caching implementation is currently behaving correctly under federation.
