### ISSUE TITLE
Deleting bulk objects could lead to panic

### ISSUE THREAD

**Issue by Kenblair1226** [minio/minio#6917]
## Expected Behavior
I am using docker-compose to build an environment with an object storage. There is a sidecar container that will check periodically for objects to be deleted and delete them in bulk of size 1000. Minio should successfully delete all objects without problem. 

## Current Behavior
Sometimes, minio seems to hang for a while and docker logs are flooded with goroutine dump messages before docker restart minio container. 

> 2018-11-26T04:34:36.359027924Z Endpoint:  http://192.168.87.182:9000  http://172.17.0.1:9000  http://172.66.66.1:9000  http://192.168.101.1:9000  http://127.0.0.1:9000
> 2018-11-26T04:34:36.359047636Z 
> 2018-11-26T04:34:36.359049471Z Browser Access:
> 2018-11-26T04:34:36.359051356Z    http://192.168.87.182:9000  http://172.17.0.1:9000  http://172.66.66.1:9000  http://192.168.101.1:9000  http://127.0.0.1:9000
> 2018-11-26T04:34:36.359053279Z 
> 2018-11-26T04:34:36.359054956Z Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
> 2018-11-26T04:34:36.359056725Z    $ mc config host add myminio http://192.168.87.182:9000
> 2018-11-26T04:34:36.359058412Z 
> 2018-11-26T04:34:36.359060103Z Object API (Amazon S3 compatible):
> 2018-11-26T04:34:36.359061809Z    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
> 2018-11-26T04:34:36.359063575Z    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
> 2018-11-26T04:34:36.359065247Z    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
> 2018-11-26T04:34:36.359066938Z    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
> 2018-11-26T04:34:36.359068670Z    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
> 2018-11-26T06:00:03.675936443Z runtime: failed to create new OS thread (have 31655 already; errno=11)
> 2018-11-26T06:00:04.152612343Z runtime: may need to increase max user processes (ulimit -u)
> 2018-11-26T06:00:04.152627647Z fatal error: newosproc
> 2018-11-26T06:00:04.152640733Z 
> 2018-11-26T06:00:04.152643715Z runtime stack:
> 2018-11-26T06:00:04.152646126Z runtime.throw(0x1137fc6, 0x9)
> 2018-11-26T06:00:04.152648526Z 	/opt/go/src/runtime/panic.go:616 +0x81
> 2018-11-26T06:00:04.152651038Z runtime.newosproc(0xc484a4c400, 0xc484a48000)
> 2018-11-26T06:00:04.152653380Z 	/opt/go/src/runtime/os_linux.go:164 +0x1af
> 2018-11-26T06:00:04.152655852Z runtime.newm1(0xc484a4c400)
> 2018-11-26T06:00:04.152658286Z 	/opt/go/src/runtime/proc.go:1879 +0x113
> 2018-11-26T06:00:04.152660502Z runtime.newm(0x1185028, 0xc42003a000)
> 2018-11-26T06:00:04.152662852Z 	/opt/go/src/runtime/proc.go:1858 +0x9b
> 2018-11-26T06:00:04.152665213Z runtime.startm(0xc42003a000, 0x1b35501)
> 2018-11-26T06:00:04.152672574Z 	/opt/go/src/runtime/proc.go:2002 +0x138
> 2018-11-26T06:00:04.152675377Z runtime.handoffp(0xc42003a000)
> 2018-11-26T06:00:04.152677477Z 	/opt/go/src/runtime/proc.go:2040 +0x29a
> 2018-11-26T06:00:04.152679675Z runtime.retake(0x7ad8041858d11, 0xd00000001)
> 2018-11-26T06:00:04.152681700Z 	/opt/go/src/runtime/proc.go:4363 +0x13b
> 2018-11-26T06:00:04.152683685Z runtime.sysmon()
> 2018-11-26T06:00:04.152685691Z 	/opt/go/src/runtime/proc.go:4281 +0x233
> 2018-11-26T06:00:04.152687836Z runtime.mstart1(0x0)
> 2018-11-26T06:00:04.152689922Z 	/opt/go/src/runtime/proc.go:1227 +0xe7
> 2018-11-26T06:00:04.152691925Z runtime.mstart()
> 2018-11-26T06:00:04.152693984Z 	/opt/go/src/runtime/proc.go:1193 +0x76
> 2018-11-26T06:00:04.152696094Z 
> 2018-11-26T06:00:04.152698127Z goroutine 1 [select, 85 minutes]:
> 2018-11-26T06:00:04.152700361Z github.com/minio/minio/cmd.handleSignals()
> 2018-11-26T06:00:04.152702492Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/signals.go:63 +0x12d
> 2018-11-26T06:00:04.152704720Z github.com/minio/minio/cmd.serverMain(0xc420111ce0)
> 2018-11-26T06:00:04.152706854Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:316 +0x853
> 2018-11-26T06:00:04.152709104Z github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xf319c0, 0x11831a0, 0xc420111ce0, 0xc420085c00, 0x0)
> 2018-11-26T06:00:04.152711247Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
> 2018-11-26T06:00:04.152713694Z github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0x1134bf6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x114fd84, 0x1c, 0x0, ...)
> 2018-11-26T06:00:04.152715970Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xa35
> 2018-11-26T06:00:04.152718258Z github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc420370680, 0xc42002e090, 0x3, 0x3, 0x0, 0x0)
> 2018-11-26T06:00:04.152720575Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x700
> 2018-11-26T06:00:04.152722694Z github.com/minio/minio/cmd.Main(0xc42002e090, 0x3, 0x3)
> 2018-11-26T06:00:04.152724893Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:155 +0x8d
> 2018-11-26T06:00:04.152727021Z main.main()
> 2018-11-26T06:00:04.152729108Z 	/q/.q/sources/gopath/src/github.com/minio/minio/main.go:70 +0xd7
> 2018-11-26T06:00:04.152731364Z 
> 2018-11-26T06:00:04.152733530Z goroutine 5 [chan receive, 25 minutes]:
> 2018-11-26T06:00:04.152735814Z github.com/minio/minio/cmd/logger.(*logOnceType).cleanupRoutine(0xc420078e50)
> 2018-11-26T06:00:04.152739571Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logonce.go:60 +0x60
> 2018-11-26T06:00:04.152742044Z created by github.com/minio/minio/cmd/logger.newLogOnceType
> 2018-11-26T06:00:04.152747244Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/logger/logonce.go:71 +0x78
> 2018-11-26T06:00:04.152749895Z 
> 2018-11-26T06:00:04.152752168Z goroutine 6 [syscall, 85 minutes]:
> 2018-11-26T06:00:04.152754247Z os/signal.signal_recv(0x0)
> 2018-11-26T06:00:04.152756882Z 	/opt/go/src/runtime/sigqueue.go:139 +0xa6
> 2018-11-26T06:00:04.152759249Z os/signal.loop()
> 2018-11-26T06:00:04.152761556Z 	/opt/go/src/os/signal/signal_unix.go:22 +0x22
> 2018-11-26T06:00:04.152763919Z created by os/signal.init.0
> 2018-11-26T06:00:04.152766173Z 	/opt/go/src/os/signal/signal_unix.go:28 +0x41
> 2018-11-26T06:00:04.152768412Z 
> 2018-11-26T06:00:04.152770471Z goroutine 7 [chan receive, 85 minutes]:
> 2018-11-26T06:00:04.152772612Z github.com/minio/minio/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc420084ae0, 0xc420084a20)
> 2018-11-26T06:00:04.152775148Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
> 2018-11-26T06:00:04.152777782Z created by github.com/minio/minio/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
> 2018-11-26T06:00:04.152780124Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xf2
> 2018-11-26T06:00:04.152782744Z 
> 2018-11-26T06:00:04.152785411Z goroutine 8 [chan receive, 85 minutes]:
> 2018-11-26T06:00:04.152787712Z github.com/minio/minio/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc420084ae0, 0xc420084a80)
> 2018-11-26T06:00:04.152790305Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
> 2018-11-26T06:00:04.152792926Z created by github.com/minio/minio/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
> 2018-11-26T06:00:04.152795725Z 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x11e
> 2018-11-26T06:00:04.152798298Z 
> 2018-11-26T06:00:04.152800554Z goroutine 24 [select]:
> 2018-11-26T06:00:04.152803005Z github.com/minio/minio/cmd.(*PolicySys).Init.func1(0xc420493d20, 0x1246b40, 0xc42058c1c0)
> 2018-11-26T06:00:04.152805493Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/policy.go:144 +0x135
> 2018-11-26T06:00:04.152807895Z created by github.com/minio/minio/cmd.(*PolicySys).Init
> 2018-11-26T06:00:04.152810241Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/policy.go:140 +0xa5
> 2018-11-26T06:00:04.152812679Z 
> 2018-11-26T06:00:04.152814977Z goroutine 58 [IO wait]:
> 2018-11-26T06:00:04.152817351Z internal/poll.runtime_pollWait(0x7f898bee3e30, 0x72, 0x0)
> 2018-11-26T06:00:04.152819746Z 	/opt/go/src/runtime/netpoll.go:173 +0x57
> 2018-11-26T06:00:04.152822122Z internal/poll.(*pollDesc).wait(0xc420302018, 0x72, 0xc420038000, 0x0, 0x0)
> 2018-11-26T06:00:04.152826430Z 	/opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
> 2018-11-26T06:00:04.152829085Z internal/poll.(*pollDesc).waitRead(0xc420302018, 0xffffffffffffff00, 0x0, 0x0)
> 2018-11-26T06:00:04.152831994Z 	/opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> 2018-11-26T06:00:04.152834384Z internal/poll.(*FD).Accept(0xc420302000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 2018-11-26T06:00:04.152836724Z 	/opt/go/src/internal/poll/fd_unix.go:372 +0x1a8
> 2018-11-26T06:00:04.152839092Z net.(*netFD).accept(0xc420302000, 0xc420662090, 0x0, 0x0)
> 2018-11-26T06:00:04.152841158Z 	/opt/go/src/net/fd_unix.go:238 +0x42
> 2018-11-26T06:00:04.152843236Z net.(*TCPListener).accept(0xc420662000, 0x454d30, 0xc42064cf88, 0xc42064cf90)
> 2018-11-26T06:00:04.152845415Z 	/opt/go/src/net/tcpsock_posix.go:136 +0x2e
> 2018-11-26T06:00:04.152847550Z net.(*TCPListener).AcceptTCP(0xc420662000, 0xc42048a040, 0xc420662090, 0xc42008e180)
> 2018-11-26T06:00:04.152849782Z 	/opt/go/src/net/tcpsock.go:246 +0x49
> 2018-11-26T06:00:04.152851903Z github.com/minio/minio/cmd/http.(*httpListener).start.func3(0xc420662000, 0xc42008e180)
> 2018-11-26T06:00:04.152854119Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/listener.go:220 +0x41
> 2018-11-26T06:00:04.152856404Z created by github.com/minio/minio/cmd/http.(*httpListener).start
> 2018-11-26T06:00:04.152858669Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/listener.go:234 +0x1af
> 2018-11-26T06:00:04.152860894Z 
> 2018-11-26T06:00:04.152863122Z goroutine 57 [IO wait, 85 minutes]:
> 2018-11-26T06:00:04.152865364Z internal/poll.runtime_pollWait(0x7f898bee3f00, 0x72, 0xc42064d858)
> 2018-11-26T06:00:04.152867578Z 	/opt/go/src/runtime/netpoll.go:173 +0x57
> 2018-11-26T06:00:04.152870021Z internal/poll.(*pollDesc).wait(0xc420302c98, 0x72, 0xffffffffffffff00, 0x1225160, 0x1816598)
> 2018-11-26T06:00:04.152872440Z 	/opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
> 2018-11-26T06:00:04.152874597Z internal/poll.(*pollDesc).waitRead(0xc420302c98, 0xc4203f4400, 0x400, 0x400)
> 2018-11-26T06:00:04.152876662Z 	/opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> 2018-11-26T06:00:04.152879045Z internal/poll.(*FD).Read(0xc420302c80, 0xc4203f4400, 0x400, 0x400, 0x0, 0x0, 0x0)
> 2018-11-26T06:00:04.152881154Z 	/opt/go/src/internal/poll/fd_unix.go:157 +0x17d
> 2018-11-26T06:00:04.152883274Z net.(*netFD).Read(0xc420302c80, 0xc4203f4400, 0x400, 0x400, 0x8, 0x8, 0x3f3)
> 2018-11-26T06:00:04.152885375Z 	/opt/go/src/net/fd_unix.go:202 +0x4f
> 2018-11-26T06:00:04.152887440Z net.(*conn).Read(0xc420172058, 0xc4203f4400, 0x400, 0x400, 0x0, 0x0, 0x0)
> 2018-11-26T06:00:04.152889759Z 	/opt/go/src/net/net.go:176 +0x6a
> 2018-11-26T06:00:04.152891996Z crypto/tls.(*block).readFromUntil(0xc4202baff0, 0x7f898be9f120, 0xc420172058, 0x5, 0xc420172058, 0x0)
> 2018-11-26T06:00:04.152894385Z 	/opt/go/src/crypto/tls/conn.go:493 +0x96
> 2018-11-26T06:00:04.152898527Z crypto/tls.(*Conn).readRecord(0xc4202ae700, 0x1185117, 0xc4202ae820, 0x0)
> 2018-11-26T06:00:04.152901227Z 	/opt/go/src/crypto/tls/conn.go:595 +0xe0
> 2018-11-26T06:00:04.152903752Z crypto/tls.(*Conn).Read(0xc4202ae700, 0xc42060e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> 2018-11-26T06:00:04.152906058Z 	/opt/go/src/crypto/tls/conn.go:1156 +0x100
> 2018-11-26T06:00:04.152908259Z bufio.(*Reader).Read(0xc420084420, 0xc420230d58, 0x9, 0x9, 0x30, 0x28, 0x105a820)
> 2018-11-26T06:00:04.152911691Z 	/opt/go/src/bufio/bufio.go:216 +0x238
> 2018-11-26T06:00:04.152913877Z io.ReadAtLeast(0x1221620, 0xc420084420, 0xc420230d58, 0x9, 0x9, 0x9, 0xc42064dcd8, 0x40126e, 0xc42064dd87)
> 2018-11-26T06:00:04.152916222Z 	/opt/go/src/io/io.go:309 +0x86
> 2018-11-26T06:00:04.152918307Z io.ReadFull(0x1221620, 0xc420084420, 0xc420230d58, 0x9, 0x9, 0x685384, 0xc4202ba2a0, 0xc4202b0004)
> 2018-11-26T06:00:04.152920522Z 	/opt/go/src/io/io.go:327 +0x58
> 2018-11-26T06:00:04.152922636Z net/http.http2readFrameHeader(0xc420230d58, 0x9, 0x9, 0x1221620, 0xc420084420, 0x0, 0xc400000000, 0x42a244, 0x11851f8)
> 2018-11-26T06:00:04.152924782Z 	/opt/go/src/net/http/h2_bundle.go:1517 +0x7b
> 2018-11-26T06:00:04.152926838Z net/http.(*http2Framer).ReadFrame(0xc420230d20, 0xc4202ba2a0, 0x0, 0x0, 0x0)
> 2018-11-26T06:00:04.152928946Z 	/opt/go/src/net/http/h2_bundle.go:1775 +0xa4
> 2018-11-26T06:00:04.152930958Z net/http.(*http2clientConnReadLoop).run(0xc42064dfb8, 0x1184a98, 0xc420384fb8)
> 2018-11-26T06:00:04.152933277Z 	/opt/go/src/net/http/h2_bundle.go:8028 +0x90
> 2018-11-26T06:00:04.152935340Z net/http.(*http2ClientConn).readLoop(0xc4206541c0)
> 2018-11-26T06:00:04.152937493Z 	/opt/go/src/net/http/h2_bundle.go:7956 +0x68
> 2018-11-26T06:00:04.152939556Z created by net/http.(*http2Transport).newClientConn
> 2018-11-26T06:00:04.152941551Z 	/opt/go/src/net/http/h2_bundle.go:7143 +0x65c
> 2018-11-26T06:00:04.152943619Z 
> 2018-11-26T06:00:04.152945767Z goroutine 42 [chan receive]:
> 2018-11-26T06:00:04.152947808Z github.com/minio/minio/cmd/http.(*httpListener).Accept(0xc42016a1e0, 0x1184a50, 0xc4202f7220, 0x122f7c0, 0xc420640120)
> 2018-11-26T06:00:04.152950637Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/listener.go:240 +0x57
> 2018-11-26T06:00:04.152952860Z net/http.(*Server).Serve(0xc420308120, 0x122b180, 0xc42016a1e0, 0x0, 0x0)
> 2018-11-26T06:00:04.152955075Z 	/opt/go/src/net/http/server.go:2770 +0x1a5
> 2018-11-26T06:00:04.152957564Z github.com/minio/minio/cmd/http.(*Server).Start(0xc420308120, 0x1184f58, 0x0)
> 2018-11-26T06:00:04.152959978Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:118 +0x23a
> 2018-11-26T06:00:04.152962164Z github.com/minio/minio/cmd.serverMain.func1()
> 2018-11-26T06:00:04.152964237Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:288 +0x2d
> 2018-11-26T06:00:04.152966707Z created by github.com/minio/minio/cmd.serverMain
> 2018-11-26T06:00:04.152970670Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:287 +0x6c4
> 2018-11-26T06:00:04.152973060Z 
> 2018-11-26T06:00:04.152975032Z goroutine 54171 [syscall]:
> 2018-11-26T06:00:04.152977026Z syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc445b4d3b0, 0x181002, 0x1b6, 0x0, 0x0, 0x10, 0x10, 0xc4276f3ac8)
> 2018-11-26T06:00:04.152979182Z 	/opt/go/src/syscall/asm_linux_amd64.s:44 +0x5
> 2018-11-26T06:00:04.152981387Z syscall.openat(0xffffffffffffff9c, 0xc445b4d340, 0x6f, 0x181002, 0x1b6, 0xc446115800, 0xc4457f0520, 0x7f898bf40458)
> 2018-11-26T06:00:04.152983680Z 	/opt/go/src/syscall/zsyscall_linux_amd64.go:38 +0xae
> 2018-11-26T06:00:04.152986245Z syscall.Open(0xc445b4d340, 0x6f, 0x181002, 0xc4000001b6, 0x44526f, 0xc445b4d340, 0xc445b4d2d0)
> 2018-11-26T06:00:04.152988571Z 	/opt/go/src/syscall/syscall_linux.go:51 +0x50
> 2018-11-26T06:00:04.152990972Z os.openFileNolog(0xc445b4d340, 0x6f, 0x101002, 0x1b6, 0x0, 0x2f6100000000006f, 0x4)
> 2018-11-26T06:00:04.152993405Z 	/opt/go/src/os/file_unix.go:168 +0x7a
> 2018-11-26T06:00:04.152995778Z os.OpenFile(0xc445b4d340, 0x6f, 0x101002, 0x1b6, 0x0, 0x0, 0x1)
> 2018-11-26T06:00:04.152998206Z 	/opt/go/src/os/file.go:269 +0x5f
> 2018-11-26T06:00:04.153000633Z github.com/minio/minio/pkg/lock.lockedOpenFile(0xc445b4d340, 0x6f, 0x2, 0x1b6, 0x2, 0x4, 0x1, 0xc445b4d340)
> 2018-11-26T06:00:04.153003127Z 	/q/.q/sources/gopath/src/github.com/minio/minio/pkg/lock/lock_nix.go:45 +0x81
> 2018-11-26T06:00:04.153005614Z github.com/minio/minio/pkg/lock.LockedOpenFile(0xc445b4d340, 0x6f, 0x2, 0x1b6, 0x0, 0xc445b4d340, 0x6f)
> 2018-11-26T06:00:04.153008175Z 	/q/.q/sources/gopath/src/github.com/minio/minio/pkg/lock/lock_nix.go:91 +0x50
> 2018-11-26T06:00:04.153010591Z github.com/minio/minio/cmd.(*fsIOPool).Write(0xc42047c010, 0xc445b4d340, 0x6f, 0xc445b4d340, 0x6f, 0x1235160)
> 2018-11-26T06:00:04.153013099Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1-rwpool.go:149 +0x75
> 2018-11-26T06:00:04.153015556Z github.com/minio/minio/cmd.(*FSObjects).DeleteObject(0xc42058c1c0, 0x122f7c0, 0xc42044af60, 0xc4202cf3b6, 0xb, 0xc420c43310, 0x42, 0x0, 0x0)
> 2018-11-26T06:00:04.153018256Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1.go:924 +0x322
> 2018-11-26T06:00:04.153020657Z github.com/minio/minio/cmd.(ObjectLayer).DeleteObject-fm(0x122f7c0, 0xc42044af60, 0xc4202cf3b6, 0xb, 0xc420c43310, 0x42, 0x0, 0x0)
> 2018-11-26T06:00:04.153023312Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/bucket-handlers.go:256 +0x72
> 2018-11-26T06:00:04.153025863Z github.com/minio/minio/cmd.objectAPIHandlers.DeleteMultipleObjectsHandler.func1(0xc4204c90d0, 0xc4204c8450, 0xc4202cf3b6, 0xb, 0xc421b1e000, 0xc903, 0xc903, 0x1246b40, 0xc42058c1c0, 0x11830d8, ...)
> 2018-11-26T06:00:04.153028698Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/bucket-handlers.go:260 +0x1f3
> 2018-11-26T06:00:04.153031076Z created by github.com/minio/minio/cmd.objectAPIHandlers.DeleteMultipleObjectsHandler
> 2018-11-26T06:00:04.153035297Z 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/bucket-handlers.go:245 +0x4de
> 
---omitted---

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
1.  setup docker-compose environment to run minio in container
2.  generate objects of size about 5MB each constantly
3.  having a cronjob to delete large amount of objects perodically
4.  check docker log to see if minio panic and dump goroutine logs.

## Your Environment
* Version used (`minio version`): RELEASE.2018-06-08T03-49-38Z
* Environment name and version (e.g. nginx 1.9.1): Docker version 18.03.1-ce, build 9ee9f40
* Server type and version:
* Operating System and version (`uname -a`): ubuntu 16.04 LTS

**Comment by kannappanr** [comment]
@Kenblair1226 We will try to reproduce this issue and get back to you with more questions.

**Comment by harshavardhana** [comment]
> * Version used (`minio version`): RELEASE.2018-06-08T03-49-38Z

We have fixed this already @Kenblair1226 @kannappanr you need to upgrade your Minio.

**Comment by kannappanr** [comment]
@Kenblair1226 Can you please try the latest version as suggested by @harshavardhana

**Comment by Kenblair1226** [comment]
Will do and report back! Thanks!

**Comment by harshavardhana** [comment]
@Kenblair1226 were you able to validate this?

**Comment by Kenblair1226** [comment]
We’ve already updated to the latest version, but this issue happens not very often and seems require a long run to reproduce. So far in our test env everything runs smoothly. Feel free to close it, will reopen it if I see it happen again.
