### ISSUE TITLE
[gateway] Sends unencrypted files to backblaze b2

### ISSUE THREAD

**Issue by sam2kb** [minio/minio#6919]
Minio gateway sends unencrypted files to backblaze b2 backend

Gateway setup
```
docker run -d \
  --name fqdn.tld \
  --restart unless-stopped \
  --network web \
  -v /home/ssl/cert.pem:/root/.minio/certs/public.crt \
  -v /home/ssl/key.pem:/root/.minio/certs/private.key \
  -e MINIO_ACCESS_KEY=B2-KEY \
  -e MINIO_SECRET_KEY=B2-SECRET \
 minio/minio gateway b2
```

Upload command
```
/usr/bin/docker run -it \
  --network web \
  -v /home/backup:/source \
  -e MC_HOSTS_b2="https://B2-KEY:B2-SECRET@fqdn.tld:9000" \
  -e MC_ENCRYPT_KEY="b2/b2-bucket/mail/=ENCRYPTION-KEY" \
  minio/mc cp --recursive /source/ b2/b2-bucket/mail/
```

The files are transferred successfully but unencrypted. Note that I use a FQDN with a valid SSL certificate.

**Comment by harshavardhana** [comment]
We do not support encryption for B2 gateway, We only support encryption for S3 gateway. @sam2kb  - This is expected and might not be fixed any time soon.

**Comment by sam2kb** [comment]
This is so sad

**Comment by harshavardhana** [comment]
Happy to see PRs and we are willing to accept contributions... this might become easier once https://github.com/minio/minio/tree/new-features is merged.

**Comment by nitisht** [comment]
closing this as answered @sam2kb
