### ISSUE TITLE
Multi-user not working with nas gateway

### ISSUE THREAD

**Issue by mlsedu** [minio/minio#6921]
I'm attempting to run minio as a distributed gateway to a backend nfs host, and am unable to get the multi-user functionality to work.

## Expected Behavior
1. Create the desired policy
2. Create the desired user and associate with the policy
3. List users or operate using new user

## Current Behavior
When attempting to list the users, I see:
**mc: <ERROR> Cannot list user sio: unsupported version**
Logins do not work, with the following error:
**mc: <ERROR> Unable to list folder. The access key ID you provided does not exist in our records.**

## Steps to Reproduce (for bugs)
1.  Startup a minio instance in gateway nas mode using an nfs mount as the backend
2.  Create a policy and user, associating the user to the policy
3.  Attempt an operation against the server as that user

## Context
I require the ability to control access on a per bucket basis in order to bring this into my environment.

## Regression
No idea if this is a regression

## Your Environment

* Version used (`minio version`):
Version: 2018-11-30T03:56:59Z
Release-Tag: RELEASE.2018-11-30T03-56-59Z
Commit-ID: 26120d7838a76cc878ad4e12bf3dd44ce9872e81
* Server type and version:
CentOS Linux release 7.4.1708 (Core)
* Version used (`mc version`):
Version: 2018-11-30T01:52:08Z
Release-tag: RELEASE.2018-11-30T01-52-08Z
Commit-id: a91204ea6fb507b62253a6b1cee4583cdfc53115
* Operating System and version (`uname -a`):
Linux \<redacted> 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
NAS gateway doesn't support it unless you are using etcd - we only support Multi-user with etcd.

So you will have to enable MINIO_ETCD_ENDPOINTS

**Comment by harshavardhana** [comment]
You would need something like this, setup etcd https://github.com/minio/minio/blob/master/docs/sts/etcd.md

Setup nas gateway
```
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_ETCD_ENDPOINTS=http://localhost:2379
minio gateway nas /mnt/nfs
```

**Comment by mlsedu** [comment]
Thank you very much for the information.
