### ISSUE TITLE
failed to start docker container panic: runtime error: index out of range

### ISSUE THREAD

**Issue by yeleaveszi** [minio/minio#6923]
failed to start docker container panic: runtime error: index out of range

[root@MyLinux64 /home]# docker run -p 9000:9000 minio/minio server /data
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/minio/minio/cmd.makeAdminPeers(0xc4204a4d00, 0x1, 0x1, 0xc42035abd0, 0xc4205a0960, 0xc4205d2660)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-rpc-client.go:150 +0x536
github.com/minio/minio/cmd.initGlobalAdminPeers(0xc4204a4d00, 0x1, 0x1)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-rpc-client.go:194 +0x3f
github.com/minio/minio/cmd.serverMain(0xc420137600)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:314 +0x50b
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0x12a8640, 0x159b8a0, 0xc420137600, 0xc4204a6300, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0x1536a8e, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1557469, 0x1b, 0x0, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xa35
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc4204944e0, 0xc420038090, 0x3, 0x3, 0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x700
github.com/minio/minio/cmd.Main(0xc420038090, 0x3, 0x3)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:155 +0x8d
main.main()
	/q/.q/sources/gopath/src/github.com/minio/minio/main.go:70 +0xd7

The os is linux.
Anyone can help?

**Comment by harshavardhana** [comment]
Just tested I don't see an issue

```
docker run --rm -p 9000:9000 minio/minio server /data

Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

**Comment by yeleaveszi** [comment]
> Just tested I don't see an issue
> 
> ```
> docker run --rm -p 9000:9000 minio/minio server /data
> 
> Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
> 
> Browser Access:
>    http://172.17.0.2:9000  http://127.0.0.1:9000
> 
> Object API (Amazon S3 compatible):
>    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
>    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
> ```

Yes, I think in most case, it is OK. And I start minio server very smoothly in my iMac.
I read the related source code : admin-rpc-client.go:150
`localAddr = net.JoinHostPort(sortIPs(localIP4.ToSlice())[0], globalMinioPort)`
This cause the "index out of range". It's about the IP. 
Maybe it is the network config cause this problem?
Do you have any clue?
Thank you very much.

**Comment by harshavardhana** [comment]
No i don't, I am not able to reproduce this though. Feel free to close if you cannot.
