### ISSUE TITLE
the num of objects in a bucket

### ISSUE THREAD

**Issue by Danbuth** [minio/minio#6932]
Maximum number of objects per bucket in  Limits of S3 API is no-limit.
In actual use, how many objetcs will affect performance.
In my test, I already have 5 million objetcs and It still has no effect.

**Comment by harshavardhana** [comment]
It depends on your backend filesystem

**Comment by harshavardhana** [comment]
Closing this as incomplete issue

**Comment by harshavardhana** [comment]
Closing this issue as answered..
