### ISSUE TITLE
GLIBC relocation error in 18.04 -- snap only problem (wrong author addressed, major user error epic fail)

### ISSUE THREAD

**Issue by averyfreeman** [minio/minio#6933]
$ snap run minio server

minio: relocation error: /snap/minio/1186/lib/x86_64-linux-gnu/libpthread.so.0:symbol __mmap, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

## Expected Behavior

Should run? 

other posted issues re: glibc say wrong version if not using 17.10 - 

## Current Behavior

not shit

## Possible Solution

if you're going to post a snap that only works with one version of Ubuntu, why not put it in the description on the store website?

## Steps to Reproduce (for bugs)

already posted above

## Context

just wanted to test as alternative to NC.

## Regression

Nobody knows, one post says 'use LTS' (assuming 16.04) and the next post has someone saying they're having the same problem using 16.04.  

Another post says 'use 17.10' - this is obviously going to break on the next update regardless of what OS release it's being run on. 

(suggestion) Is there a way to introduce glibc version independence, or package a specific version with it?  (a snap IS a container, after all...)

## Your Environment

$ uname -a
Linux lxd-box 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

**Comment by harshavardhana** [comment]
We don't support snap, neither we officially build one. Just use the official binaries that we release.

We don't have any plans to support snap either.

**Comment by averyfreeman** [comment]
I'm so sorry!  I feel like an idiot - I had too many tabs open and thought this was the snap author's git page.

Trying out the docker image now - any problems running on rkt?
