### ISSUE TITLE
`CopyObject` fails when "?versionId=null" is included in "X-Amz-Copy-Source" (BOSH Backup and Restore + PCF)

### ISSUE THREAD

**Issue by coffee-squirrel** [minio/minio#6935]
When using [BOSH Backup and Restore SDK](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release) with any unversioned blobstore (e.g. Minio) [`?versionId=null` is included](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/blob/8eae90caee9f43abfcc371278a724d9d28c4e991/src/github.com/cloudfoundry-incubator/s3-blobstore-backup-restore/s3/bucket.go#L151) at the end of the `X-Amz-Copy-Source` header value (following the bucket+object).

Minio includes `?versionId=null` as part of the source object file name, which causes an error on Windows (where [`?` is invalid](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file)) and potentially strange behavior on other OS.

## Expected Behavior

Requests (anything extracting `object`; e.g. `CopyObject`, `HeadObject`) succeed even if a query string like `?versionId=null` is passed.

## Current Behavior

Minio includes anything after the bucket prefix (e.g. an optional query string) as part of the object filename.

* https://github.com/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/object-handlers.go#L683
* https://github.com/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/handler-utils.go#L95
* https://github.com/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/object-handlers.go#L730
* https://github.com/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/fs-v1.go#L696

This results in an error like:
```
API: CopyObject(bucket=backups-sandbox-buildpacks, object=2018_11_26_16_52_48/buildpacks/98/de/98debc09-e29b-41f2-9924-f41b076a31ac_75121c310490fa56b75b57fe59dc1b8f7f03b1a4cf333a6881d6bdaa5de0939b) 
Time: 10:52:48 CST 11/26/2018 
RequestID: 156ABAC2FA94DC00 
RemoteHost: 10.1.2.3
UserAgent: aws-sdk-go/1.12.33 (go1.9.6; linux; amd64) 
Error: The filename, directory name, or volume label syntax is incorrect. 
 1: cmd\fs-v1.go:735:cmd.(*FSObjects).getObjectInfo() 
 2: cmd\fs-v1.go:512:cmd.(*FSObjects).GetObjectNInfo() 
 3: cmd\object-handlers.go:162:cmd.(ObjectLayer).GetObjectNInfo-fm() 
 4: cmd\object-handlers.go:730:cmd.objectAPIHandlers.CopyObjectHandler() 
 5: cmd\api-router.go:70:cmd.(objectAPIHandlers).CopyObjectHandler-fm() 
 6: net\http\server.go:1947:http.HandlerFunc.ServeHTTP() 
 ```

## Possible Solution

Minio either ignores the query when determining the bucket and object, or treats `versionId == null` as the only valid option, in the value of `X-Amz-Copy-Source`.

After checking with the Backup and Restore SDK team, they referenced the following from the [Object Versioning](https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectVersioning.html) page in the AWS S3 docs:
> Regardless of whether you have enabled versioning, each object in your bucket has a version ID. If you have not enabled versioning, Amazon S3 sets the value of the version ID to null. If you have enabled versioning, Amazon S3 assigns a unique version ID value for the object

I believe that team is investigating whether omitting `versionId` for unversioned blobstores is something they could safely do, but ideally Minio would handle a potential query string.

## Steps to Reproduce (for bugs)

1. Attempt to back up a PCF PAS deployment that uses Minio as the blobstore (i.e. `bbr deployment backup`)
2. Note errors (and a failed backup) when the Backup and Restore SDK issues `CopyObject` requests with `?versionId=null` in the `X-Amz-Copy-Source` header value.

_...or something like..._

1. Create a `RELEASE.2018-11-22T02-51-56Z` Minio instance with buckets `source` and `backup`
2. Define the host `blobstore` for `mc` (i.e. `mc config host add blobstore ...`)
2. Create a test file to "back up" `mc cp ./hello.txt blobstore/source/hello.txt`
3. Run `mc cp blobstore/source/hello.txt?versionId=null blobstore/backup/hello.txt`
4. Note `Error: The filename, directory name, or volume label syntax is incorrect.`

## Context

We're using Minio in conjunction with PCF, and are working on utilizing `bbr` to back things up.

## Regression

No

## Your Environment

* Version used (`minio version`): `RELEASE.2018-11-22T02-51-56Z`
* Operating System and version (`uname -a`): Windows Server 2016 Datacenter

**Comment by harshavardhana** [comment]
We do not support versioning @coffee-squirrel so it won't work.

**Comment by coffee-squirrel** [comment]
@harshavardhana Yes, understood.  I believe the BOSH Backup and Restore SDK team is indicating that including `?versionId=null` as part of the `X-Amz-Copy-Source` header value (indicating "no version") is valid according to AWS S3 API, though.  Thoughts on that?

**Comment by harshavardhana** [comment]
It might be but we don't support anything related to versions. We might enable this one off since it means no version anyways. But I doubt this is the only fix that would be needed.

**Comment by coffee-squirrel** [comment]
@harshavardhana Would stripping the query string altogether when splitting the bucket and object ([CopyObject](/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/handler-utils.go#L95), [HeadObject](/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/object-handlers.go#L488), etc.) be a better option?  No special handling of `versionId`, etc.

We're successfully using Minio as the blobstore for PCF (PAS) itself.

**Comment by harshavardhana** [comment]
> @harshavardhana Would stripping the query string altogether when splitting the bucket and object ([CopyObject](/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/handler-utils.go#L95), [HeadObject](/minio/minio/blob/RELEASE.2018-11-22T02-51-56Z/cmd/object-handlers.go#L488), etc.) be a better option? No special handling of `versionId`, etc.
> 
> We're successfully using Minio as the blobstore for PCF (PAS) itself.

Yes but all of those are simply workarounds. We should interpret them properly. Let's see what we can do.

**Comment by coffee-squirrel** [comment]
@harshavardhana thank you for getting the related PR into `RELEASE.2018-12-13T02-04-19Z`.  After testing that release out in conjunction with BBR (verifying `CopyObject` worked), it seems `CopyObjectPart` is also impacted in the same way as `CopyObject`, etc.  Would you prefer a new issue?

```
API: CopyObjectPart(bucket=backups-sandbox-buildpacks, object=2018_12_13_21_06_47/buildpacks/f0/6b/f06be899-35b7-4e08-86d2-c44edfd7ef34_c2ec63cba701165cbb342e24127b440e913dccd74b4574102583ebfa031f0235)
Time: 15:06:47 CST 12/13/2018
RequestID: 1570007C9E302BCC
RemoteHost: 10.1.2.3
UserAgent: aws-sdk-go/1.12.33 (go1.10.3; linux; amd64)
Error: The filename, directory name, or volume label syntax is incorrect.
       1: cmd\fs-v1.go:725:cmd.(*FSObjects).getObjectInfo()
       2: cmd\fs-v1.go:502:cmd.(*FSObjects).GetObjectNInfo()
       3: cmd\object-handlers.go:162:cmd.(ObjectLayer).GetObjectNInfo-fm()
       4: cmd\object-handlers.go:1515:cmd.objectAPIHandlers.CopyObjectPartHandler()
       5: cmd\api-router.go:52:cmd.(objectAPIHandlers).CopyObjectPartHandler-fm()
       6: net\http\server.go:1947:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
Sent a PR to fix it as well https://github.com/minio/minio/pull/6972
