### ISSUE TITLE
corruption at disk level gets healed silently

### ISSUE THREAD

**Issue by tiasarea** [minio/minio#6937]
Setup:
2 servers with 4 disks each (logical volumes 3.8GB each)
/srv/minio/data{1,2,3,4}

CentOS Linux release 7.5.1804 (Core)
kernel 3.10.0-862.3.3.el7.x86_64

minio server version:
minio.RELEASE.2018-12-06T01-27-43Z

ip of servers: 192.168.97.221 and 192.168.97.222

config:
MINIO_VOLUMES="http://192.168.97.222/srv/minio/data1 http://192.168.97.222/srv/minio/data2 http://192.168.97.222/srv/minio/data3 http://192.168.97.222/srv/minio/data4 http://192.168.97.221/srv/minio/data1 http://192.168.97.221/srv/minio/data2 http://192.168.97.221/srv/minio/data3 http://192.168.97.221/srv/minio/data4"

creating bucket "mybucket"
upload 1,000 files of 1MB each to bucket.

setup done, now simulating corruption of 1 disk:
changing one byte into a file part.1 inside a folder named after a filename.

## Expected Behavior
mc admin heal detects corruption (dry-run should say something and real run should also say something)
i.e. at least 1 object not green (yellow, red or grey)

## Current Behavior
dry run:

~/mc.RELEASE.2018-11-06T01-12-20Z admin heal -n -r test_minio
 ◓  mybucket/1mbfile1000
    0/1,000 objects; 1000 MiB in 13s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,003 │ 100.0% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     0 │   0.0%              │
    └────────┴───────┴─────────────────────┘

real heal:
 ~/mc.RELEASE.2018-11-06T01-12-20Z admin heal -r test_minio
 ◑  mybucket/1mbfile0998
    1/1,000 objects; 1000 MiB in 10s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,003 │ 100.0% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     0 │   0.0%              │
    └────────┴───────┴─────────────────────┘

all objects green, nothing detected or advertised, healing occurs though completely silent.

the folder named after the filename (containing the corrupted file) got deleted alltogether (good) and recreated (good),
however not in dry-run mode and without specifying healing action anywhere.

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
see above

## Context
disk/block corruption have to be detected

## Your Environment
see above

**Comment by tiasarea** [comment]
I realized there was a newer version of mc, however results stay the same.

 ~/mc.RELEASE.2018-12-05T22-59-07Z admin heal -r test_minio
 ◓  mybucket/1mbfile0998
    1/1,000 objects; 1000 MiB in 9s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,003 │ 100.0% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     0 │   0.0%              │
    └────────┴───────┴─────────────────────┘

**Comment by kannappanr** [comment]
@tiasarea The green color might suggest that more than 80% of the disks have correct data for the object. As far as dry run itself is healing the object, we will try to reproduce it here.

**Comment by tiasarea** [comment]
@kannappanr 
dry-run does not heal the object. 
neither dry-run does let user know there is an issue wit the object, which is my problem.

another problem is that heal (not dry-run this time) does not let user know that it found a problem and fixes it, instead it silently fixes the problem.
which is an issue because you want to know when your storage starts to die, you want to move out asap in this case.

thank you for considering updating the priority of this bug, as this is to me a show stopper for as far as minio can be considered entreprise grade software.

**Comment by kannappanr** [comment]
@tiasarea There are two modes of operation in `mc`. One is how you did it. The other is using a `--json` flag. If you really want exact information of what is missing etc, you should use the `json` flag.

Here is an output 
```
{
  "status": "success",
  "type": "object",
  "name": "test/issue",
  "before": {
    "color": "green",
    "offline": 1,
    "online": 7,
    "missing": 0,
    "corrupted": 0,
    "drives": [
      {
        "uuid": "",
        "endpoint": "/tmp/f1",
        "state": "offline"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f2",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f3",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f4",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f5",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f6",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f7",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f8",
        "state": "ok"
      }
    ]
  },
  "after": {
    "color": "green",
    "offline": 1,
    "online": 7,
    "missing": 0,
    "corrupted": 0,
    "drives": [
      {
        "uuid": "",
        "endpoint": "/tmp/f1",
        "state": "offline"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f2",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f3",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f4",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f5",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f6",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f7",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/tmp/f8",
        "state": "ok"
      }
    ]
  },
  "size": 20
}
{
  "status": "success",
  "type": "summary",
  "objects_scanned": 1,
  "objects_healed": 0,
  "items_scanned": 4,
  "items_healed": 0,
  "size": 20,
  "duration": 1
}
```
This tells you that the first disk is missing this particular part. The idea is displaying with `color` codes is to abstract it out. There is no way for us to display the exact details in UI. 

If you are worried about tracking these information, you should be using the `json` flag.

**Comment by tiasarea** [comment]
Ohh!!!
very interesting indeed.
I will be able to test on my test cluster only on next monday.
I will definitely switch to json and parse the result and see if corruption is detected.
thank you for the heads up.

**Comment by tiasarea** [comment]
I realized there was a newer version of mc, however results stay the same.

 ~/mc.RELEASE.2018-12-05T22-59-07Z admin heal -r test_minio
 ◓  mybucket/1mbfile0998
    1/1,000 objects; 1000 MiB in 9s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,003 │ 100.0% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     0 │   0.0%              │
    └────────┴───────┴─────────────────────┘

**Comment by tiasarea** [comment]
dear @kannappanr ,

I have indeed tested with the json flag, and even though object corrupted is marked green after and before, I can see that a property "corrupted" has been raised to 1.

so indeed block corruption is detected, and I appreciate it very much.

I would still bring to your attention the fact that color codes associated to object were a bit confusing at least to me.

For the specifics of this report, I would say we can close this.

thank you and best regards
