### ISSUE TITLE
Objects in buckets with capitalized names can be listed with AWS cli, but not with mc

### ISSUE THREAD

**Issue by dmolesUC** [minio/minio#6938]
## Expected Behavior

Minio should consistently provide, or consistently not provide, access to buckets with invalid names (e.g. containing capital letters).

Note this may be somehow related to running on case-insensitive (but case-preserving) APFS, or to running on macOS.

## Current Behavior

`mc` doesn't list buckets with capitalized names, or their contents, but Minio does expose them to `aws cli`, at least when listing the bucket contents.

## Possible Solution

- preferred: go ahead and expose invalid bucket names in all cases, just don't let people create them
- less optimal: figure out what's different between `list-buckets` and `list-objects`, and make sure Minio doesn't expose invalid bucket names to AWS in the `list-buckets` operation

## Steps to Reproduce (for bugs)

1. Create the following directory tree, where the leaf nodes are files.

   ```
   foo
   ├── Bar
   │   └── baz
   └── qux
       └── quux
   ```

   E.g.,

   ```
   $ mkdir foo
   $ mkdir foo/Bar        # capital letter, not a valid bucket name
   $ touch foo/Bar/baz
   $ mkdir foo/qux
   $ touch foo/qux/quux
   ```

2. Start a Minio server against the specified directory.

   ```
   $ MINIO_ACCESS_KEY=123 MINIO_SECRET_KEY=abcdefgh minio server foo
   ```

3. Add the new server to the `mc` client configuration.

   ```
   mc config host add foo http://127.0.0.1:9000 123 abcdefgh
   ```

4. List the available buckets with both `mc` and `aws s3`:

   ```
   $ mc ls foo
   [2018-12-07 11:28:48 PST]     0B qux/
   $ AWS_ACCESS_KEY_ID=123 AWS_SECRET_ACCESS_KEY=abcdefgh aws --endpoint-url http://localhost:9000 s3 ls
   2018-12-07 11:28:48 qux
   ```

   Note that the bucket with the capital letter is not listed by either client.

5. Attempt to list the bucket with the invalid name, using both `mc` and `aws s3`:

   ```
   $ mc ls foo/Bar        # appears to be empty
   $ AWS_ACCESS_KEY_ID=123 AWS_SECRET_ACCESS_KEY=abcdefgh aws --endpoint-url http://localhost:9000 s3 ls Bar
   2018-12-07 11:28:29          0 baz
   ```

   Note that `mc` appears unable to list the bucket contents, but `aws s3` can.

## Context

Trying to use Minio to provide access to an existing directory, which has capitalized subdirectories. As a workaround, I've created a separate "minio" directory, with an all-lower-case symlink to the original directory, which lets me treat the directory as a single bucket. (Subdirectories with capital letters, spaces, etc. appear to be fine.) Not ideal for all cases, but works for this one.

## Your Environment

* Version used (`minio version`):

   Version: 2018-12-06T01:27:43Z
   Release-Tag: RELEASE.2018-12-06T01-27-43Z
   Commit-ID: 40852801ea63d0e10f220c0d7d2a8d6a8efa5688

* Operating System and version (`uname -a`):

  ```
  Darwin Anachronic.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
  ```

  (Mac OS X 10.14.1)

* Filesystem: APFS (case-insensitive)

**Comment by kannappanr** [comment]
@dmolesUC3 Thanks for filing this issue. The tentative fix will be such that if you create a bucket with `Captialized letters` you will receive `InvalidBucketName` error back. I believe this already is the case.
In the case of pre-existing buckets, we might list those buckets and that will solve your issue. 

The difference you are seeing between `mc` and `awscli` is due to the fact that both are doing different calls to list objects under this bucket. `mc` is also calling `listBuckets` before `listObjects` is called. Since the bucket doesn't exist,  it doesn't display the objects under that bucket.

Will confirm the behavior internally and get back to you.
