### ISSUE TITLE
Unable to initialize the server in distributed mode: Credentials missing.

### ISSUE THREAD

**Issue by msinj** [minio/minio#6939]
## Expected Behavior
Should start the distributed minio. I already change the accesskey and secret key manually on the `/data1/.minio.sys/config/config.json` . Also, used the 
`export MINIO_ACCESS_KEY=<ACCESS_KEY>`
`export MINIO_SECRET_KEY=<SECRET_KEY>`

## Current Behavior
ERROR Unable to initialize the server in distributed mode: Credentials missing.
      > Please set your credentials in the environment.
      HELP:
        In distributed server mode, access and secret keys should be specified via environment variables MINIO_ACCESS_KEY and MINIO_SECRET_KEY respectively.

## Possible Solution
`sudo nano  /data1/.minio.sys/config/config.json`
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
We have four minio server with one data partition name `/data1`
OS Versio 16.0.5 LTS
IP: 192.168.1.11, 192.168.1.12, 192.168.1.13, 192.168.1.14

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
> ##
> Should start the distributed minio. I already change the accesskey and secret key manually on the `/data1/.minio.sys/config/config.json` . Also, used the
> `export MINIO_ACCESS_KEY=<ACCESS_KEY>`
> `export MINIO_SECRET_KEY=<SECRET_KEY>`

You should never modify the backend here @msinj most probably modifying backend config.json you have corrupted the backend. 

Please remove `/data1/.minio.sys/config/config.json` and let Minio create.  Also make sure that when minio server is running envs are set and they are inherited.

**Comment by msinj** [comment]
Hello,
I have tried just using the export command. It's not working. 
Giving below error:
`sudo ./minio server http://192.168.1.144/data1 http://192.168.1.145/data1 http://192.168.1.216/data1 http://192.168.1.217/data1`
![image](https://user-images.githubusercontent.com/35358239/49809349-a85f3400-fd2c-11e8-90ed-4ac61857949a.png)

**Comment by kannappanr** [comment]
@msinj can you try this 
```
sudo MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio server http://192.168.1.144/data1 http://192.168.1.145/data1 http://192.168.1.216/data1 http://192.168.1.217/data1
```

or

```
MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio server http://192.168.1.144/data1 http://192.168.1.145/data1 http://192.168.1.216/data1 http://192.168.1.217/data1
```

**Comment by msinj** [comment]
The first command worked. Although, it gave below error, I have removed the /data1/.minio.sys to fix the error.
`ERROR Unable to initialize backend: Disk /data1: found backend fs, expected xl.`
Thank you

**Comment by kannappanr** [comment]
@msinj Yes you cannot use the same directory used to run different mode of minio. Will close this issue as answered. Please feel free to reach out to us if you have more questions.
