### ISSUE TITLE
Mint tests on a s390x minio server container fails on minio-py tests

### ISSUE THREAD

**Issue by tomerzel87** [minio/minio#6944]
We are testing the usage of minio on a s390x linux server.
We've built a container based on version 2018-11-22T02:51:56Z and ran it successfully on SUSE 12.3 s390x.
Started running mint on a "regular" x86 server pointing to the s390x container endpoint.
Got the following error:
Exception: Presigned get url failed to expire!

## Current Behavior

Full trace:
(11/13) Running minio-py tests ... FAILED in 13 minutes and 45 seconds
{
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "bucket_name": "minio-py-test-8f3d22c5-39f4-40a4-b9df-6d95ed62256d",
    "object_name": "9cdc71be-ea0a-4981-878f-5985d05cdfa1"
  },
  "duration": 6281,
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "Presigned get url failed to expire!",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1200, in test_presigned_get_object_expiry_5sec\n    raise ValueError('Presigned get url failed to expire!')\nValueError: Presigned get url failed to expire!\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1785, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1202, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: Presigned get url failed to expire!\n"
}

## Your Environment

* Version used (`minio version`): 2018-11-22T02:51:56Z 
* Server type and version: SUSE 12.3 s390x 
* Operating System and version (`uname -a`): Linux host0001 4.4.138-94.39-default #1 SMP Mon Jun 18 13:27:26 UTC 2018 (baa07f9) s390x s390x s390x GNU/Linux

**Comment by nitisht** [comment]
@tomerzel87 do you see any server side logs? 
Also, can you enable `MINIO_HTTP_TRACE` and run only the `minio-py` tests in mint, and give us the output.

**Comment by tomerzel87** [comment]
Server side logs that we saw:
API: SYSTEM()
Time: 12:46:58 UTC 12/09/2018
Error: malformed HTTP request from '174.25.0.3:9000'
       remoteAddr=172.24.92.41:47418, localAddr=174.25.0.3:9000
       1: cmd/http/listener.go:274:http.(*httpListener).start.func2()

API: SYSTEM()
Time: 12:46:58 UTC 12/09/2018
Error: malformed HTTP request from '174.25.0.3:9000'
       remoteAddr=172.24.92.41:47420, localAddr=174.25.0.3:9000
       1: cmd/http/listener.go:274:http.(*httpListener).start.func2()

API: SYSTEM()
Time: 12:46:59 UTC 12/09/2018
Error: malformed HTTP request from '174.25.0.3:9000'
       remoteAddr=172.24.92.41:47422, localAddr=174.25.0.3:9000
       1: cmd/http/listener.go:274:http.(*httpListener).start.func2()

API: SYSTEM()
Time: 12:46:59 UTC 12/09/2018
Error: malformed HTTP request, invalid HTTP method '��b���O:5�=��' from '174.25.0.3:9000'
       remoteAddr=172.24.92.41:47424, localAddr=174.25.0.3:9000
       1: cmd/http/listener.go:274:http.(*httpListener).start.func2()

I'll rerun with HTTP trace and will update.

**Comment by tomerzel87** [comment]
Attaching the http trace output:
[output.log.gz](https://github.com/minio/minio/files/2662619/output.log.gz)

Let us know if you need anything else.

**Comment by nitisht** [comment]
@tomerzel87 I checked the logs and looks like server allowed the request. Can you confirm if server and mint machine have same time?

To investigate further, could you try simulating the issue with `mc`.  

- Configure mc alias to your Minio server endpoint. 
- Create a bucket `mc mb myminio/testbucket`
- Upload a file `mc cp <local-file-path> myminio/testbucket/object`
- Create presigned URL by `mc share download --expire=5s myminio/testbucket/object`
- Click on this link after 5s of URL generation. The request should be rejected.

**Comment by nitisht** [comment]
Closing due to no response @tomerzel87 . Feel free to reopen when you have further info.
