### ISSUE TITLE
server: Support ipv6 with minio server

### ISSUE THREAD

**Issue by ruben-herold** [minio/minio#6946]
hi,

starting minio server on an ipv6 only system shows:
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      18402/minio

[root@store01 conf.d]# /opt/minio/bin/minio version
Version: 2018-12-06T01:27:43Z
Release-Tag: RELEASE.2018-12-06T01-27-43Z
Commit-ID: 40852801ea63d0e10f220c0d7d2a8d6a8efa5688
[root@store01 conf.d]# 

I found no way to let it listen on ipv6. We have heer an ipv6 only network and can't use it without ipv6 support.

**Comment by nitisht** [comment]
@ruben-herold please refer https://github.com/minio/minio/issues/3359

**Comment by ruben-herold** [comment]
@nitisht ok looks bad for us. We have no chance to use ipv4 so seems minio is death for us. It is very bad that at end 2018 software still only support legacy ip.

**Comment by ruben-herold** [comment]
@nitisht @harshavardhana could please add a big notice to the readme and to the documentation that minio supports only legacy ip? This could save hours of work for many people.

**Comment by harshavardhana** [comment]
IPv6 never came across as a hard requirement for us from our users. We indeed listen on all ports, I am not sure when this has changed - i.e when we stopped listening on IPv6.

If IPv6 is a hard requirement it is something quite easy for us to address.

**Comment by ruben-herold** [comment]
@harshavardhana  please rember ipv4 is out since years.Only limited resources are available, the prices for ipv4 space got higher every year.  Also ipv4 is deprecated. So in 2018 should be no software exists without ipv6 support.  For example in Germany we have an ipv6 adoption rate from current more then 40% (https://www.google.de/ipv6/statistics.html#tab=per-country-ipv6-adoption).

I don't know if it is easy to address from your side. Cause as far as I can see there are some changes more required then just listen also on ipv6. For example #4368.

I was ask from a friend to find a solution for a small s3 store (local install) for his webside.
 minio look awesome. 

So I took the time read the documentation how to install, scale and so on. Put this all into ansible playbooks and try to deploy only to see that it's impossible to use in an ipv6 environment and the documentation does not mention this at any place. 

So please please document this behavior  to prevent other people running in the same problem.  Or even better make a version with ipv6 support.

**Comment by harshavardhana** [comment]
All our documents only talk about ipv4 so in essence that part should be fine.

Minio is largely deployed as an on prem on an internal network, so we have never seen ipv6 being used with Minio and needed as a hard requirement.

I agree that IPv6 support is a must and we never really prioritized it until we see our first user. So thank you for the reminder we can now prioritize it soon.

**Comment by ruben-herold** [comment]
@harshavardhana thx for the feedback

> All our documents only talk about ipv4 so in essence that part should be fine.

Here you see the problem. ipv4 is deprecated since years so nobody really would think that in 2018 a software has no proper ipv6 support even if it is not explicit  documented.

**Comment by ruben-herold** [comment]
@harshavardhana your pull request does not help. I compiled a minio with your patch and without 
--address it still listen only on ipv4 and if I pass a ipv6 only hostname to --address I got:

ERROR Unable to validate passed arguments: host in server address should be this server.

**Comment by harshavardhana** [comment]
I updated the PR

Here are a few ways I tested and how it's working 

Basic test
```
~ minio server ~/test

Endpoint:  http://10.0.0.17:9000  http://172.17.0.1:9000  http://172.20.0.1:9000  http://127.0.0.1:9000
AccessKey: minio 
SecretKey: minio123 
```

```
~ sudo netstat -ntlp |grep 9000
[sudo] password for harsha: 
tcp6       0      0 :::9000                 :::*                    LISTEN      17255/minio       
```

```
#!/bin/bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

rm -rf /tmp/export{01..24}
for i in {01..24}; do
    minio server --address ":90${i}" http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9001/tmp/export01 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9002/tmp/export02 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9003/tmp/export03 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9004/tmp/export04 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9005/tmp/export05 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9006/tmp/export06 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9007/tmp/export07 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9008/tmp/export08 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9009/tmp/export09 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9010/tmp/export10 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9011/tmp/export11 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9012/tmp/export12 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9013/tmp/export13 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9014/tmp/export14 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9015/tmp/export15 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9016/tmp/export16 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9017/tmp/export17 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9018/tmp/export18 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9019/tmp/export19 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9020/tmp/export20 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9021/tmp/export21 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9022/tmp/export22 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9023/tmp/export23 http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9024/tmp/export24 &
done

...
....
Status:         24 Online, 0 Offline. 
Endpoint:  http://10.0.0.17:9005  http://172.17.0.1:9005  http://127.0.0.1:9005  http://10.0.0.17:9005  http://127.0.0.1:9005  http://172.17.0.1:9005  http://[2001:db8:1::1]:9005  http://[2601:646:c403:8df0:1a1d:eaff:fe02:f4a4]:9005  http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9005  http://[2601:646:c403:8df0:e592:b564:405e:df93]:9005  http://[::1]:9005  http://[fe80::1]:9005  http://[fe80::f8b0:5b2:8f35:e7cc]:9005
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://10.0.0.17:9005  http://172.17.0.1:9005  http://127.0.0.1:9005  http://10.0.0.17:9005  http://127.0.0.1:9005  http://172.17.0.1:9005  http://[2001:db8:1::1]:9005  http://[2601:646:c403:8df0:1a1d:eaff:fe02:f4a4]:9005  http://[2601:646:c403:8df0:581e:2368:c22a:4a98]:9005  http://[2601:646:c403:8df0:e592:b564:405e:df93]:9005  http://[::1]:9005  http://[fe80::1]:9005  http://[fe80::f8b0:5b2:8f35:e7cc]:9005

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.17:9005 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

```

Please test again @ruben-herold

**Comment by ruben-herold** [comment]
@harshavardhana  ok now it works here. It was a failure during patching the source code

**Comment by jumpswitch** [comment]
I kindly ask if someone can rebuild binary for linux-arm as I'm having issue. Also tried with linux-armv6l binary.

rpiv3# wget https://dl.minio.io/server/minio/release/linux-arm/minio
rpiv3# chmod +x minio 
rpiv3# ./minio server --address [::]:9000 /DATA/
FATA[0000] Invalid address ‘[::]:9000’ in command line argument.  cause=host in server address should be this server source=[server-main.go:90:serverHandleCmdArgs()]
rpiv3# ./minio version
Version: 2017-08-05T00:00:53Z
Release-Tag: RELEASE.2017-08-05T00-00-53Z
Commit-ID: aeafe668d8b6d25caac671d59e2b0f0473ce35d0

**Comment by harshavardhana** [comment]
You can build from source, we don't build official released arm binaries.

We support source compiled binaries for these systems.
