### ISSUE TITLE
suspicious duplicated switch case clause in cmd/object-api-error.go

### ISSUE THREAD

**Issue by quasilyte** [minio/minio#6948]
## Expected Behavior

Switch doesn't have duplicated case clauses.

## Current Behavior

Switch statement has duplicated case clauses.

## Possible Solution

Remove duplicated case clause, as it's effectively a dead code.

## Steps to Reproduce (for bugs)

Look at the code:

https://github.com/minio/minio/blob/master/cmd/object-api-errors.go#L43-L56

Attaching a screenshot with highlighting of important sections:

![image](https://user-images.githubusercontent.com/6286655/49757165-c5fcb100-fccc-11e8-8c87-9b1cc2116bce.png)

## Context

The second `errFileAccessDenied` case will never be executed.
The solution is just to remove it.

## Your Environment

Not applicable, not important.

**Comment by kannappanr** [comment]
@Quasilyte Thanks for filing this issue. We will send in a PR to fix this issue.
