### ISSUE TITLE
Bug in Null condition function?

### ISSUE THREAD

**Issue by roengram** [minio/minio#6955]
According to [AWS document](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_Null), it seems that value `true` means that the specified key should be NULL - i.e. nonexistent. But [the code](https://github.com/minio/minio/blob/21d8c0fd13cfb775c1c5ddd05e01feea07d81674/pkg/policy/condition/nullfunc.go#L39) is implemented the other way around.

**Comment by nitisht** [comment]
Thanks for noticing this @roengram we'll take a look and fix if needed

**Comment by harshavardhana** [comment]
> According to [AWS document](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_Null), it seems that value `true` means that the specified key should be NULL - i.e. nonexistent. But [the code](https://github.com/minio/minio/blob/21d8c0fd13cfb775c1c5ddd05e01feea07d81674/pkg/policy/condition/nullfunc.go#L39) is implemented the other way around.

Do you have an example reproducer where this is violated? @roengram

**Comment by roengram** [comment]
I've created a simple test function as follows. Just add this code snippet at the end of [statement_test.go](https://github.com/minio/minio/blob/master/pkg/policy/statement_test.go) and run. I've used [RELEASE.2018-12-13T02-04-19Z](https://github.com/minio/minio/tree/RELEASE.2018-12-13T02-04-19Z) by the way.
```go
func TestStatement_NullFunc(t *testing.T) {
	bucket := "bkt"
	object := "object"
	action := Action(PutObjectAction)
	principal := "Q3AM3UQ867SPQQA43P2F"
	condKey := condition.Key(condition.S3XAmzServerSideEncryption)
	condVal := "AES256"

	f, _ := condition.NewNullFunc(
		condKey,
		true,
	)

	stmt := NewStatement(
		Deny,
		NewPrincipal(principal),
		NewActionSet(action),
		NewResourceSet(NewResource(bucket, object)),
		condition.NewFunctions(f),
	)
	pol, _ := json.MarshalIndent(&stmt, "", "  ")
	t.Logf("%s", pol)

	args := Args{
		AccountName: principal,
		Action:      action,
		BucketName:  bucket,
		ConditionValues: map[string][]string{
			condKey.Name(): {condVal},
		},
		ObjectName: object,
		IsOwner: false,
	}
	res := stmt.IsAllowed(args)
	expected := true
	if expected != res {
		t.Fatalf("expected: %v, got: %v", expected, res)
	}
}
```

The execution results are as follows:
```
=== RUN   TestStatement_NullFunc
--- FAIL: TestStatement_NullFunc (0.00s)
	statement_test.go:597: {
		  "Effect": "Deny",
		  "Principal": {
		    "AWS": [
		      "Q3AM3UQ867SPQQA43P2F"
		    ]
		  },
		  "Action": [
		    "s3:PutObject"
		  ],
		  "Resource": [
		    "arn:aws:s3:::bkt/object"
		  ],
		  "Condition": {
		    "Null": {
		      "s3:x-amz-server-side-encryption": [
		        true
		      ]
		    }
		  }
		}
	statement_test.go:612: expected: true, got: false
FAIL
```
The policy prescribes that a PutObject request will be DENIED if it does NOT have server-side encryption header `x-amz-server-side-encryption`. But test results say a request with that header present is not allowed. After a short debugging I'm no suspecting the following code snippet:
```go
pkg/policy/condition/nullfunc.go:

func (f nullFunc) evaluate(values map[string][]string) bool {
	requestValue := values[f.k.Name()]

	if f.value {
		return len(requestValue) != 0
	}

	return len(requestValue) == 0
}
```
In my opinion, the `if` condition should be negated, so that the evaluation results in true if the value is NOT exists. Negating it makes the test passing.

**Comment by harshavardhana** [comment]
Understood @roengram will fix it.
