### ISSUE TITLE
Deleting bucket fails

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#6956]
Deleting bucket fails in a federation setup in gateway nas mode.

## Expected Behavior
It should be deleted normally.

## Current Behavior
It returns error mc.exe: <ERROR> Failed to remove `yyy/xxx`. Bucket `xxx` does not exist.

## Steps to Reproduce (for bugs)

1. Start 2 cluster in a federation setup.
2. Create a dummy bucket
3. Try to delete it

## Regression

I recall it was working normally before, at least it was working in server mode.

## Your Environment
Minio server: commit 21d8c0fd13cfb775c1c5ddd05e01feea07d81674

**Comment by harshavardhana** [comment]
This is fixed in https://github.com/minio/minio/pull/6936

**Comment by harshavardhana** [comment]
Fixed by #6936
