### ISSUE TITLE
Creation of user returns error in swarm mode with load balancing

### ISSUE THREAD

**Issue by Lisiadito** [minio/minio#6957]
I run a 3 node docker swarm setup with an nginx for load balancing and tls. 
## Expected Behavior

I can create an user with an policy attached.
## Current Behavior

When I run 
`./mc admin user add minio newuser newuser123 customPolicy `
I get following Error
`mc: <ERROR> Cannot set user policy for new user The specified user does not exist.`

According to my conversation in slack it is caused by my nginx which does round robin load balancing. 
 
## Your Environment

* Version used (`minio version`):
Version: 2018-12-06T01:27:43Z
Release-Tag: RELEASE.2018-12-06T01-27-43Z
Commit-ID: 40852801ea63d0e10f220c0d7d2a8d6a8efa5688

* Environment name and version (e.g. nginx 1.9.1): 
nginx/1.15.7

* Operating System and version (`uname -a`):
 Linux 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@Lisiadito Thanks for filing this issue. We will send in a fix for this issue soon.

**Comment by ihamouda** [comment]
@harshavardhana Any chance this can be resolved soon?

**Comment by harshavardhana** [comment]
@ihamouda a PR has been sent already

**Comment by Lisiadito** [comment]
@ihamouda I set the load balancing on my nginx from round robin to ip_hash which works well as a workaround until this pull request is through.

**Comment by harshavardhana** [comment]
Fixed by #6975

**Comment by ihamouda** [comment]
@Lisiadito hat will be fine in development, but if the created user tries to login from another IP right away, might get error message

**Comment by harshavardhana** [comment]
This is fixed by #6975
