### ISSUE TITLE
NAS gateway setup not properly documented

### ISSUE THREAD

**Issue by sdes1480** [minio/minio#6965]
NAS gateway setup not properly documented

## Expected Behavior
The expected behavior of the command as documented by Minio docs is to be able to store objects passed through the Minio S3 gateway to a NAS mountpoint and also to be access data already in place on the NAS mountpoint.  
The NAS mountpoint was pre-created and mounted to the host running the container under /testmnt, data could be writen and read from that mountpoint. 

docker run -p 9000:9000 --name minio1 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  minio/minio gateway nas /testmnt

## Current Behavior
The current command does not work as there is no mapping between the internal container mountpoint and the host's NAS mountpoint . The command creates a /testmnt mointpoint within the container but it remains unrelated to the NAS mountpoint and instead stores the data locally in the container.
Proof points : 
- After creating the container, i created a bucket and uploaded data in the bucket using the Minio browser. This operation succeeded but when reading /testmnt directory from the host,  the data was not present. Doing an ls from the container showed the uploaded data hence a discrepancy between the 2 mountpoints.

## Possible Solution
I adapted the command as follows :  
docker run -p 9000:9000 --name minio1 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -v /testmnt:testmnt minio/minio gateway nas /testmnt

This command does a mapping between the host mount point /testmnt and the internal container mount point thanks to the -v /testmnt:testmnt . 

This command provides the expected behavior. I created buckets and uploaded data that was visible both from the container internal path and from the host level (or any other host mounting the NAS backend). 
Conversely, I created some files and directories from the host side which  were visible from the container and through the minio browser so again this is the expected behavior

## Your Environment
Linux server (tested several versions) with a NetApp NFS mount pre-populated with some data .
* Version used (`minio version`): latest docker minio version
* Server type and version: docker containers running on Lubuntu 18.04 and 18.10 / also tested on Centos7

**Comment by nitisht** [comment]
Thanks for reporting @sdes1480 we'll take a look soon
