### ISSUE TITLE
Docs: Explain how SSE-S3 key-rotation for Vault works 

### ISSUE THREAD

**Issue by aead** [minio/minio#6973]
The server supports rotation of key-encryption-keys for SSE-S3 encrypted objects.
It should be documented how this works.

## Expected Behavior
There should be documentation about how to rotate a SSE-S3 encrypted object.

## Current Behavior
No such documentation exists

## Possible Solution
Assuming Vault is configured as KMS and the key-name/key-id is `my-minio-key`
Key rotation for SSE-S3 objects `object` work like this:
 1. Create a new key `my-minio-key-2` at the Vault using the vault CLI.
 2. Update the minio server configuration such that `MINIO_SSE_VAULT_KEY_NAME` points to `my-minio-key-2` and restart the server.
 3. Execute a COPY where `src=object` and `dst=object` and add the SSE-S3 header to that COPY request. 

## Steps to Reproduce (for bugs)
https://github.com/minio/minio/tree/master/docs/kms

## Context
#6755 

## Regression
no

## Your Environment
master

**Comment by harshavardhana** [comment]
This is fixed in master and can be closed..

**Comment by kannappanr** [comment]
closing this issue as corresponding PR has been reviewed and merged
