### ISSUE TITLE
Health check timeout is too low

### ISSUE THREAD

**Issue by kbolino** [minio/minio#6974]
## Expected Behavior
Running `docker exec <container> ps -o stat,comm | grep ^Z` returns empty output

## Current Behavior
Running `docker exec <container> ps -o stat,comm | grep ^Z` returns many lines (e.g. 815 on one minio instance that's been up for a little over 24 hours), all of which are from command `healthcheck.sh`

## Possible Solutions
- Increase the health check timeout in the Dockerfile, which is currently set to 5 seconds, or remove the option entirely to use the default of 30 seconds
- Run [tini](https://github.com/krallin/tini) or another init replacement as PID 1 so that orphaned processes get removed from the PID table when they go defunct
- Improve response times for the health check endpoint `/minio/health/live` even when under heavy load so that it never takes more time to return than the configured timeout
- Add a SIGCHLD handler to minio that reaps zombie processes

## Steps to Reproduce (for bugs)
1. Start minio in distributed mode (e.g. 32 nodes with 128 total disks) using the docker image
2. Slam it with requests
3. Wait a while
4. Run `docker exec <container> ps -o stat,comm | grep ^Z` and count the zombie PIDs

## Context
This is eventually going to fill up the PID table on the host machine. As a workaround, we will have to restart the containers periodically, which impacts availability. I have opened [a question on Stackoverflow](https://stackoverflow.com/questions/53772248/how-to-modify-docker-health-check-without-rebuilding-image) about changing the health check parameters at run time but I don't think it's possible.

## Regression
No. Although, we didn't have this problem on 2018-09-12 release. It seems to have started, or at least gotten at lot worse and become noticeable, as of 2018-11-22 release.

## Your Environment
* Version used (`minio version`):
    Version: 2018-11-22T02:51:56Z
    Release-Tag: RELEASE.2018-11-22T02-51-56Z
    Commit-ID: eddf468aef34e14ba1fac0c911b2fc9b47789d88
* Environment name and version (e.g. nginx 1.9.1): docker 17.09.0-ce
* Server type and version: CentOS 7
* Operating System and version (`uname -a`): Linux 4.18.12-1.el7.elrepo.x86_64 #1 SMP Thu Oct 4 09:36:51 EDT 2018 x86_64 GNU/Linux
* Link to your project: N/A

**Comment by nitisht** [comment]
Thanks for reporting @kbolino we will see how to address it best
