### ISSUE TITLE
Does minio support resuming broken downloads/uploads?

### ISSUE THREAD

**Issue by dawsongzhao** [minio/minio#6976]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by dawsongzhao** [comment]
In some case,The network environment is bad, and the Object/file is upload or download is large size . so  most time it will be broken. Does minio support resuming broken downloads/uploads?

**Comment by nitisht** [comment]
@dawsongzhao yes, Minio does support multi part upload - as specified in AWS S3 spec: https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html

Closing this issue as answered, do join us on slack : https://slack.minio.io for further such questions
