### ISSUE TITLE
Expanding large-bucket deployment by adding deployment sets to the namespace

### ISSUE THREAD

**Issue by cbenhagen** [minio/minio#6977]
There are several older issues on this topic and I kinda hope the addition of large-bucket support changed the situation. Is this what you [mentioned was planned back in January 2017](https://news.ycombinator.com/item?id=13453991)? Unfortunately the documentation does not say anything about this.

I understand that by design a single deployment set can not be expanded. Now Large-bucket deployments consist of multiple smaller erasure coded deployment sets combined into a single namespace. Is there a way to add a new deployment set into that namespace to expand its total size?

**Comment by nitisht** [comment]
@cbenhagen Minio Federation is the way we have added a namespace layer on top of multiple heterogeneous Minio instances. Please ref the documentation here: https://docs.minio.io/docs/minio-federation-quickstart-guide.html

> Is there a way to add a new deployment set into that namespace to expand its total size?

So, to answer the question, you can create a new Minio instance and add it to the existing namespace using Minio federation. Each of these Minio instances can themselves be running in different modes (large bucket / single node single drive / single node multiple drives).

**Comment by cbenhagen** [comment]
Well as far as I understand, this will not allow a bucket to span multiple clusters right? So in the case of a cluster becoming too small / bucket becoming too big this would not help.

Currently the only options we see is to highly overprovision a cluster or to make the application aware of the cluster size and have it create new buckets and decide on which bucket to put its data. Both options look quite ugly. I wish there was a layer above the cluster which would abstract that. So to the applications the storage seems to be of infinite size.

**Comment by nitisht** [comment]
> Well as far as I understand, this will not allow a bucket to span multiple clusters right?

Yes, that is right. 

> I wish there was a layer above the cluster which would abstract that. So to the applications the storage seems to be of infinite size.

Our production users do not really see a problem in keeping buckets in a single cluster as it keeps failure domain limited to buckets and capacity is generally added way earlier than it is getting exhausted. Creating a bucket is trivial and application can choose which cluster to create the bucket on. 

But we do have plans to do this as well. No ETA as of now though.

Closing this for now, feel free to reopen or reach out on Slack for further questions. (https://slack.minio.io)
