### ISSUE TITLE
Error running minio gateway as a windows service

### ISSUE THREAD

**Issue by theerebuss** [minio/minio#6979]
Running minio gateway as a windows service, using NSSM, fails.
Executing through command line works without issues.
Tried using Local System and admin user to run the service.

## Expected Behavior
Minio should connect to the server successfully.

## Current Behavior
When I start the Windows service, minio outputs this error:
```
panic: nuid: failed generating crypto random number: CryptAcquireContext: Provider DLL failed to initialize correctly.


goroutine 1 [running]:
github.com/minio/minio/vendor/github.com/nats-io/nuid.(*NUID).RandomizePrefix(0xc04223e5d0)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/nats-io/nuid/nuid.go:118 +0x191
github.com/minio/minio/vendor/github.com/nats-io/nuid.New(0x15704aecd0722ad0)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/nats-io/nuid/nuid.go:70 +0xf9
github.com/minio/minio/vendor/github.com/nats-io/nuid.init.0()
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/nats-io/nuid/nuid.go:59 +0xac
```

## Steps to Reproduce

1. Run server on machine 1 _minio server C:\minio\data_
2. Create windows user _minio_ on machine 1
3. Share _C:\minio\data_ folder as _minio_ to the created user on machine 1
4. Use setx command to add global variables on machine 2
setx -m MINIO_ACCESS_KEY minio
setx -m MINIO_SECRET_KEY password
5. Run command _minio gateway nas \\\\machine1\minio_ on machine 2
Minio works as expected
6. Install minio as a service with NSSM with the same command on machine 2
Service starts and pauses. Rerouting output to log file with NSSM shows the following error:
```
panic: nuid: failed generating crypto random number: CryptAcquireContext: Provider DLL failed to initialize correctly.


goroutine 1 [running]:
github.com/minio/minio/vendor/github.com/nats-io/nuid.(*NUID).RandomizePrefix(0xc04223e5d0)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/nats-io/nuid/nuid.go:118 +0x191
github.com/minio/minio/vendor/github.com/nats-io/nuid.New(0x15704aecd0722ad0)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/nats-io/nuid/nuid.go:70 +0xf9
github.com/minio/minio/vendor/github.com/nats-io/nuid.init.0()
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/nats-io/nuid/nuid.go:59 +0xac
```

## Context
Trying to implement a distributed minio server configuration on two Windows machines, hosting the data on machine 1

## Your Environment (both machines)
* Version used:
```
Version: 2018-12-13T02:04:19Z
Release-Tag: RELEASE.2018-12-13T02-04-19Z
Commit-ID: 6f7c99a33325bb11431dd56a1d261a18e5293de3
```
* Operating System and version:
```
OS Name	Microsoft Windows Server 2016 Standard
Version	10.0.14393 Build 14393
```

**Comment by kannappanr** [comment]
@andrefilipedias most probably, `minio` service is getting started before the `crypto` related services startup or the user account running minio service does not have access to the crypto modules. 

Local system and admin user should have privileges to access crypto modules.

Are you manually starting the service or is it started as part of system startup?

We will look into reproducing it and get back to you for more information.

**Comment by harshavardhana** [comment]
Looks like a Go runtime issue due to some missing environment variable https://github.com/golang/go/issues/25210

**Comment by theerebuss** [comment]
@kannappanr, the service is being started automatically on boot. Starting it manually still produces the same error.

**Comment by harshavardhana** [comment]
I thought you said

> Executing through command line works without issues.

Is this not true ?

**Comment by theerebuss** [comment]
@harshavardhana that's correct. The issue is only while running it as a service.

By manually, I meant starting the service manually.

**Comment by harshavardhana** [comment]
Is it possible to get the list of envs set for this service when the service is being started ? . From the original Go runtime issue attached - they specifically mention SYSTEMROOT not set.

**Comment by theerebuss** [comment]
I set up an NSSM service with a batch file that runs _set_ so I could have the available variables while running as a service.

```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Windows\system32\config\systemprofile\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=[HOSTNAME]
ComSpec=C:\Windows\system32\cmd.exe
LOCALAPPDATA=C:\Windows\system32\config\systemprofile\AppData\Local
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=[PASSWORD]
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d07
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Windows\TEMP
TMP=C:\Windows\TEMP
USERDOMAIN=WORKGROUP
USERNAME=[USERNAME]$
USERPROFILE=C:\Windows\system32\config\systemprofile
windir=C:\Windows
```

Let me know if I can be of further assistance.

**Comment by harshavardhana** [comment]
Can we get the list of envs when you start it on cmd or powershell ?

**Comment by theerebuss** [comment]
Here are the environment variables for my user:

```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\andre.dias\AppData\Roaming
CLIENTNAME=ET-051
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=[HOSTNAME]
ComSpec=C:\Windows\system32\cmd.exe
HOMEDRIVE=C:
HOMEPATH=\Users\andre.dias
LOCALAPPDATA=C:\Users\andre.dias\AppData\Local
LOGONSERVER=\\[HOSTNAME]
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=[PASSWORD]
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Users\andre.dias\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d07
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=RDP-Tcp#9
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\ANDRE~1.DIA\AppData\Local\Temp\2
TMP=C:\Users\ANDRE~1.DIA\AppData\Local\Temp\2
USERDOMAIN=[HOSTNAME]
USERDOMAIN_ROAMINGPROFILE=[HOSTNAME]
USERNAME=andre.dias
USERPROFILE=C:\Users\andre.dias
windir=C:\Windows
```

**Comment by ebozduman** [comment]
@theerebuss ,
One more question and a suggestion :
What version of NSSM were you running?

There is the following explanation at nssm web site [download](https://nssm.cc/download) page:
```
Windows 10 Creators Update
2017-04-26: Users of Windows 10 Creators Update should use prelease build 2.2.4-101 to
avoid an issue with services failing to start. If for some reason you cannot use that
build you can also set AppNoConsole=1 in the registry, noting that applications which
expect a console window may behave unexpectedly.
```

Since you have Windows 10, could you please give it a try to nssm `prelease build 2.2.4-101` if you haven't already tried it out?
You can also try setting `AppNoConsole=1 in the registry`.

**Comment by ebozduman** [comment]
@andrefilipedias,
Ping!
Could you please let us know your thoughts about my previous comment?
Thanks...

**Comment by deekoder** [comment]
@theerebuss - Can you help us further in this repro?

**Comment by kannappanr** [comment]
@theerebuss Closing this issue as stale. Please re-open the issue when you have more information for us.
