### ISSUE TITLE
madmin rest api documentation

### ISSUE THREAD

**Issue by siamackSeifi** [minio/minio#6984]
Hi.

I'm trying to send http request to minio server for admin management(add-user, set-user-policy etc)
the request that i made is something like this:

curl -X PUT \
  'http://{IP}/minio/admin/v1/add-user?accessKey=myAccessKey' \
  -H 'Authorization: AWS4-HMAC-SHA256 Credential=xxx, SignedHeaders=cache-control;content-type;host;postman-token;x-amz-content-sha256;x-amz-date, Signature={signature}' \
  -H 'Content-Type: application/json' \
  -H 'Host: {IP} \
  -H 'Postman-Token: a981bf9e-2b57-40ad-8975-bfd511909a51' \
  -H 'X-Amz-Content-Sha256: {xxx}' \
  -H 'X-Amz-Date: 20181216T101601Z' \
  -H 'cache-control: no-cache'

this returns the following error:
{
    "Code": "XMinioAdminConfigBadJSON",
    "Message": "JSON configuration provided is of incorrect format",
    "Resource": "/minio/admin/v1/add-user",
    "RequestId": "1570C8B7293CB70C",
    "HostId": "3L137"
}

I think there must be a body which I can't figure out its format.
Could you help me with this?
And if possible provide me with all madmin request syntaxes?

Thanks in advance

**Comment by harshavardhana** [comment]
You cannot use postman like clients for admin API especially for add users which are end to end encrypted calls

Here is the documentation 
https://github.com/minio/minio/blob/master/pkg/madmin/API.md

**Comment by harshavardhana** [comment]
Closing this as answered, please reach out to us on https://slack.minio.io for further questions.
