### ISSUE TITLE
mc admin is failing for multiple commands on Azure Gateway

### ISSUE THREAD

**Issue by sgandon** [minio/minio#6987]
When using some `mc admin` commands such as `user list` they fail.

## Expected Behavior

`mc admin user list minio-azure` should list the users
`mc --debug admin policy list minio-azure` should list the policies
## Current Behavior

I have an error such as
```mc: <ERROR> Cannot list user sio: unsupported version
 (1) admin-user-list.go:73 cmd.mainAdminUserList(..) Tags: [minio-azure]
 (0) admin-user-list.go:73 cmd.mainAdminUserList(..)
 Commit:69f967b3f32c | Release-Tag:RELEASE.2018-12-12T19-02-22Z | Host:tlnd-sgandon2018 | OS:darwin | Arch:amd64 | Lang:go1.10.2 | Mem:68MB/78MB | Heap:68MB/72MB
```
or
```
mc --debug admin policy list minio-azure
mc: <DEBUG> GET /minio/admin/v1/list-canned-policies HTTP/1.1
Host: minio:1122
User-Agent: Minio (darwin; amd64) madmin-go/0.0.1 mc/2018-12-12T19:02:22Z
Authorization: AWS4-HMAC-SHA256 Credential=xx/20181217//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: xx
X-Amz-Date: 20181217T094427Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1979
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: text/html; charset=utf-8
Date: Mon, 17 Dec 2018 09:44:28 GMT
Last-Modified: Wed, 14 Nov 2018 00:11:24 GMT
Vary: Origin
X-Amz-Request-Id: 15711592EFFCA76E
X-Minio-Deployment-Id:
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  288.871769ms

mc: <ERROR> Cannot list policy invalid character '<' looking for beginning of value
 (1) admin-policy-list.go:76 cmd.mainAdminPolicyList(..) Tags: [minio-azure]
 (0) admin-policy-list.go:76 cmd.mainAdminPolicyList(..)
 Release-Tag:RELEASE.2018-12-12T19-02-22Z | Commit:69f967b3f32c | Host:tlnd-sgandon2018 | OS:darwin | Arch:amd64 | Lang:go1.10.2 | Mem:1.7MB/7.2MB | Heap:1.7MB/3.6MB
```
## Steps to Reproduce (for bugs)

1. create an AKS cluster on Azure and a Blob Storage.
2.launch the helm chart 2.1 with the image.tag=RELEASE.2018-12-13T02-04-19Z and one single instance
3.portforward to local host.
4.create a minio config and use it !

## Your Environment

* Version used (`minio version`):```minio version
Version: 2018-12-13T02:04:19Z
Release-Tag: RELEASE.2018-12-13T02-04-19Z
Commit-ID: 6f7c99a33325bb11431dd56a1d261a18e5293de3```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Minio RELEASE.2018-12-13T02-04-19Z using as Azure Gateway
* Operating System and version (`uname -a`): docker image
* Link to your project:

**Comment by harshavardhana** [comment]
Without etcd admin API is disabled on Gateways, especially multi-user.

**Comment by sgandon** [comment]
ok thanks, the doc is not mentioning this clearly. I'll try to setup an etcd for this.

**Comment by harshavardhana** [comment]
> ok thanks, the doc is not mentioning this clearly. I'll try to setup an etcd for this.

We will do it @sgandon

**Comment by nitisht** [comment]
keeping this open to track doc fix
