### ISSUE TITLE
Minio with NGINX

### ISSUE THREAD

**Issue by msinj** [minio/minio#6990]
## Expected Behavior

Connect 4 minio instances with NGINX proxy server
## Current Behavior

Individual link to 4 different minio
## Possible Solution

Using NGINX, we can have one link for all 4 minio
## Steps to Reproduce (for bugs)

1. Installed NGINX
2. Installed 4 minio
3.
4.

## Context

We have installed 4 minio and a NGIX proxy server. Need help on configuring the proxy to load-balance with 4 minio server. IP for minio is 192.168.1.11, 192.168.1.12, 192.168.1.13, 192.168.1.14. Proxy server IP is 192.168.1.221 with Ubuntu 18.04 LTS
Minios are running on Ubuntu 16.04 LTS.
## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Have you not looked at https://www.nginx.com/blog/enterprise-grade-cloud-storage-nginx-plus-minio/ ?

**Comment by nitisht** [comment]
closing this @msinj please refer to our documentation. Do let us know if something is not working specifically.

**Comment by kannappanr** [comment]
Closing this issue now. Please feel free to reach out to us on slack.minio.io if you have further questions.
