### ISSUE TITLE
failing to launch minio as Azure gateway with etcd on K8s

### ISSUE THREAD

**Issue by sgandon** [minio/minio#6993]
In AKS with etcd installed to have handling of user and policies launch minio as Azure gateway with `MINIO_ETCD_ENDPOINTS` set and then try to connect to minio and see it fails.

## Expected Behavior

should be up and running
## Current Behavior

minio pod restarts endlessly and create error logs when liveliness probe or any other request is done.
```
[RESPONSE] [154515006.531514] [2018-12-18 16:21:05 +0000]
503 Service Unavailable
X-Amz-Request-Id: 157179CC3FC51280
X-Minio-Deployment-Id:
Retry-After: 120
Content-Type: application/xml
Vary: Origin
Content-Security-Policy: block-all-mixed-content
Accept-Ranges: bytes
X-Xss-Protection: 1; mode=block
Server: Minio/RELEASE.2018-12-13T02-04-19Z (linux; amd64)

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Resource>/probe-bucket-sign-uj9p0b4d6sa1/</Resource><RequestId>157179CC3FC51280</RequestId><HostId>3L137</HostId></Error>
```

## Steps to Reproduce (for bugs)

1. create a AKS cluster and a Blob Storage.
2. launch etcd on the cluster:
`helm install --name etcd incubator/etcd --set replicas=1`

3. launch minio using helm too:
`helm install --name minio --set azuregateway.enabled=true --set accessKey=yourblobstorage --set secretKey=secret --set image.tag=RELEASE.2018-12-13T02-04-19Z --set azuregateway.replicas=1  --set persistence.enabled=false stable/minio --version 2.2.0  --set environment.MINIO_ETCD_ENDPOINTS="http://etcd:2379",environment.MINIO_HTTP_TRACE="tmp/minio.log"  --debug`
4. use kubefwd to forward the dns names and port locally.
5. try to create host config using
`mc config host add minio-azure-9000 http://minio:9000 yourblobstorage secret S3v4``

## Your Environment

* Version used (`minio version`):```minio version
Version: 2018-12-13T02:04:19Z
Release-Tag: RELEASE.2018-12-13T02-04-19Z
Commit-ID: 6f7c99a33325bb11431dd56a1d261a18e5293de3```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Minio RELEASE.2018-12-13T02-04-19Z using as Azure Gateway
* Operating System and version (`uname -a`): docker image
* Link to your project:

**Comment by nitisht** [comment]
we'll take a look @sgandon

**Comment by harshavardhana** [comment]
Is this still reproducible @sgandon ??

**Comment by harshavardhana** [comment]
Is this still reproducible @sgandon ??

**Comment by harshavardhana** [comment]
Closing this as stale issue
