### ISSUE TITLE
putObject hangs with AWS SDK version 2

### ISSUE THREAD

**Issue by Katona** [minio/minio#6997]
`putObject` seems to hang when using AWS S3 SDK version `2.1.4` with Mino Server version `2018-12-13T02:04:19Z`.

Here is a test project to reproduce the issue:
https://github.com/Katona/minio-server-with-aws-sdk

**Comment by kannappanr** [comment]
@Katona Will try to reproduce this issue. Can you also tell us how you started minio?

**Comment by Katona** [comment]
I launched it as a docker container with `docker-compose`. You can check the compose file in the repo I created.

**Comment by harshavardhana** [comment]
This looks like a bug in aws-sdk-java 2 i just upgraded your build.gradle to use latest release and it seems to work fine. 

```
git diff
diff --git a/build.gradle b/build.gradle
index 8dce1ab..3b1fd5d 100644
--- a/build.gradle
+++ b/build.gradle
@@ -11,7 +11,7 @@ plugins {
 }
 
 dependencies {
-    implementation 'software.amazon.awssdk:s3:2.1.4'
+    implementation 'software.amazon.awssdk:s3:2.2.0'
 
     // This dependency is used internally, and not exposed to consumers on their own compile classpath.
     implementation 'com.google.guava:guava:23.0'
```

The issue was perhaps here https://github.com/aws/aws-sdk-java-v2/commit/472f5bfbce08038653b641b070e3ac09ae846313 which was fixed in 2.2.0

**Comment by Katona** [comment]
Indeed, I confirm that version `2.2.0` works well. Thanks for the help!

**Comment by Katona** [comment]
However, I can not download the content because of the checksum is invalid. It seems Minio calculates a different checksum than the SDK. I updated my test project to demonstrate the issue.

**Comment by Katona** [comment]
Ah, never mind, I turned off checksum calculation of the API.
