### ISSUE TITLE
Cannot configure minio to push events to mysql 8.x

### ISSUE THREAD

**Issue by gbarton** [minio/minio#6999]
## Expected Behavior
When configuring minio to push events to mysql 8.x for event notification it should succeed.

## Current Behavior
When submitting updated config to minio server it fails with reasons:
trying to use user with caching_sha2_password:
mc: <ERROR> Cannot set server configuration file. mysql(1): this authentication plugin is not supported
or
trying user with mysql_native_password set:
mv: <ERROR> Cannot set server configuration file. mysql(1): this user requires mysql native password authentication.

## Possible Solution

It looks like the copy of go-sql-driver pulled into vendor is quite old.  Driver now supports caching sha2 password since ~May timeframe: https://github.com/go-sql-driver/mysql/pull/794
Perhaps a simple update would fix it?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 2018-11-22T02:51:56Z 
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Docker
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@gbarton Thanks for reporting this issue. We will try to reproduce this issue. We will also vendorize the latest source of https://github.com/go-sql-driver/mysql .

**Comment by krisis** [comment]
@gbarton Could you share a sample configuration that isn't working for you in the released minio version? It would help in testing if simply updating the `go-sql-driver/mysql` package fixes this issue.

**Comment by nitisht** [comment]
@gbarton we have updated the `go-sql-driver/mysql` in master, can you try it out? or if possible share a sample configuration so we can confirm

**Comment by gbarton** [comment]
I reverted to 5.x in the short term to get a project out the door.  I
should have time next week to see if it works. Thank you!

**Comment by nitisht** [comment]
@gbarton closing this for now, feel free to reopen if it doesn't work as expected.
