### ISSUE TITLE
Py4JAuthenticationError: Failed to authenticate with gateway server from Zeppelin 

### ISSUE THREAD

**Issue by Ftagn92** [minio/minio#7001]
Hello,
I'm using Hadoop 2.8.3 (port 8999) / Minio:edge (port 9000) Spark 2.2.1 without hadoop, and zeppelin 0.8.0
When i run a tiny script on my local cluster (1 master / 3 workers), it works
I upgrade to Spark 2.3.2, running the same script from zeppelin fails with the error message
Py4JAuthenticationError: Failed to authenticate with gateway server.

## Expected Behavior
Same result as spark 2.2.1

## Steps to Reproduce (for bugs)
hadoop 2.8.3
core-site.xml contains references to Minio
`<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:8999</value>
    </property>
    <property>
        <name>fs.s3a.endpoint</name>
        <description>AWS S3 endpoint to connect to. An up-to-date list is
          provided in the AWS Documentation: regions and endpoints. Without this
          property, the standard region (s3.amazonaws.com) is assumed.
        </description>
        <value>http://127.0.0.1:9000</value>
    </property>
    <property>
        <name>fs.s3a.access.key</name>
        <description>AWS access key ID.</description>
        <value>localKey</value>
    </property>
   <property>
        <name>fs.s3a.secret.key</name>
        <description>AWS secret key.</description>
        <value>localSecret</value>
    </property>
</configuration>`

Minio is a docker container
`version: '2'
services:

  minio:
    image: minio/minio:edge
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: localKey
      MINIO_SECRET_KEY: localSecret`

Here is the docker network of Minio : 

`[
    {
        "Name": "minio_default",
        "Id": "7c342a36579cfeb8438bcb23089229ed2fba1ae102400bc14dac3c11363948f2",
        "Created": "2018-12-19T16:30:47.373965475+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.21.0.0/16",
                    "Gateway": "172.21.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "2178a1fc5a651f196f535b27165fcd94a6aa7aa7a70f2b1fd475144ff8caf6eb": {
                "Name": "minio",
                "EndpointID": "fa04c8a25d4720ef35b4d28cac61deec804e0ad765b77c0d9be2a0565274ad84",
                "MacAddress": "02:42:ac:15:00:02",
                "IPv4Address": "172.21.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
`

Spark 2.3.2 contains no special values
Zeppelin contains no special values, except in spark interpreter : 
- Address of the master (localhost:7077)
- artifact : org.apache.hadoop:hadoop-aws:2.8.3
- exclude com.fasterxml.jackson.core,javax.servlet,org.mortbay.jetty

I tried with some environnement variables : 

`HADOOP_PREFIX=/usr/local/hadoop-2.8.3
HADOOP_HOME=/usr/local/hadoop-2.8.3
SPARK_HOME=/usr/local/spark-2.3.2-bin-without-hadoop
AWS_ACCESS_KEY_ID=localKey
AWS_SECRET_ACCESS_KEY=localSecret
PYSPARK_PYTHON=ipython3
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
AWS_PROFILE=minio
`
.aws/config : 
[profile minio]
output = json
region = us-east-1

.aws/credentials : 
[minio]
aws_access_key_id = localKey
aws_secret_access_key = localSecret

1. running this script works on Spark 2.2.1 : 
`%pyspark
from pyspark.sql import SparkSession                                                                                                                              
spark = SparkSession.builder.appName("appName").getOrCreate() 
sc = spark.sparkContext                         
rdd = sc.parallelize([1,2,3,4,5,6,7])     
print(rdd.count())        `

2. Running the same script on Spark 2.3.2 fails with : 

`ITraceback (most recent call last):
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 929, in _get_connection

IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:
Traceback (most recent call last):

  File "/tmp/zeppelin_pyspark-1928709633240924604.py", line 279, in <module>
    java_import(gateway.jvm, "org.apache.spark.SparkEnv")
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 179, in java_import
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 983, in send_command
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 931, in _get_connection
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 937, in _create_connection
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1071, in start
  File "/usr/local/spark-2.3.2-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1094, in _authenticate_connection
py4j.protocol.Py4JAuthenticationError: Failed to authenticate with gateway server.
pyspark is not responding
`

I can find minio connection tries in zeppelin log : 

` INFO [2018-12-20 01:28:12,069] ({pool-3-thread-2} Py4JUtils.java[createGatewayServer]:44) - Launching GatewayServer at 127.0.0.1:45585
 INFO [2018-12-20 01:28:12,078] ({pool-3-thread-2} PySparkInterpreter.java[createGatewayServerAndStartScript]:265) - pythonExec: ipython3
`

`INFO [2018-12-20 01:27:56,422] ({pool-2-thread-3} RemoteInterpreterManagedProcess.java[start]:190) - Run interpreter process [/usr/local/zeppelin-0.8.0-bin-all/bin/interpreter.sh, -d, /usr/local/zeppelin-0.8.0-bin-all/interpreter/spark, -c, 172.21.0.1, -p, 37767, -r, :, -l, /usr/local/zeppelin-0.8.0-bin-all/local-repo/spark, -g, spark]
 INFO [2018-12-20 01:27:58,621] ({pool-9-thread-1} RemoteInterpreterManagedProcess.java[callback]:123) - RemoteInterpreterServer Registered: CallbackInfo(host:172.21.0.1, port:45747)
 `

## Your Environment
Ubuntu 16.04 LTS
Minio Edge on docker
Spark 2.3.2-without-hadoop
zeppelin 0.8.0

Thanks for your help :*

**Comment by nitisht** [comment]
We'll try this locally and see what is wrong @Ftagn92

**Comment by Ftagn92** [comment]
Hello, thanks for your message
I upgraded Hadoop fron 2.8.3 to 3.1.1 (and org.apache.hadoop:hadoop-aws:3.1.1 artifact) and it works now 
Dependencies are worst than the DLL's hell in the 90's :)

**Comment by nitisht** [comment]
That is great news, do feel free to close the issue @Ftagn92

**Comment by Ftagn92** [comment]
Yes, just typing my final setup : 

Ubuntu 16.04 LTS
Python 3.5 by default (and PYSPARK_PYTHON value)

Minio/minio:edge as a container, exposing port 9000

Hadoop 3.1.1 (for the framework) with core-site.xml pointing to http://127.0.0.1:9000 as fs.s3a.endpoint

Spark 2.3.2-without-hadoop (to link to my v3.1.1)
local spark cluster launched with ./start-master.sh and SPARK_WORKER_INSTANCES=3 SPARK_WORKER_CORES=2 ./start-slave.sh spark://localhost:7077

Zeppelin 0.8.0 with 2 artifacts : 
org.apache.hadoop:hadoop-aws:3.1.1 (exclude com.fasterxml.jackson.core)
com.amazonaws:aws-java-sdk-s3:1.11.474 (exclude com.fasterxml.jackson.core too)
and Python3 as internal interpreter
linked to spark with SPARK_HOME value in zeppelin-env.sh
master set to spark://localhost:7077

Scripts pyspark beginning with : 
    AWS_ID='localKey'
    AWS_KEY='localSecret'
    sc._jsc.hadoopConfiguration().set("fs.s3a.access.key", AWS_ID)
    sc._jsc.hadoopConfiguration().set("fs.s3a.secret.key", AWS_KEY)
    sc._jsc.hadoopConfiguration().set("fs.s3a.endpoint", 'http://localhost:9000')
    sc._jsc.hadoopConfiguration().set("fs.s3a.connection.ssl.enabled", "false")
    sc._jsc.hadoopConfiguration().set("fs.s3a.connection.timeout", "10000")
    sc._jsc.hadoopConfiguration().set("fs.s3a.connection.establish.timeout", "5000")
    sc._jsc.hadoopConfiguration().set("fs.s3a.attempts.maximum", "3")
    sc._jsc.hadoopConfiguration().set("fs.s3a.path.style.access", "true")
    sc._jsc.hadoopConfiguration().set("fs.s3a.disable.chunked.encoding", "true")

Thanks for this amazing tool
