### ISSUE TITLE
Cannot set bucket notification(A specified destination ARN does not exist or is not well-formed. Verify the destination ARN)

### ISSUE THREAD

**Issue by Grapefruit-Shu** [minio/minio#7006]
old version 2017-09-29T19:16:56Z it can work,,but the new version 2018-12-13T02:04:19Z it didn't work.
the config.json did not create in the default directory, when i create a new directory and put a old config.json, i us this command to start it (nohup ./minio server --address xx.xx.xx.xx:9000 --config-dir=/ete/minio /home/data &)  the log is (Configuration file /ete/minio/config.json migrated from version '19' to '20' successfully.
Configuration file /ete/minio/config.json migrated from version '20' to '21' successfully.
Configuration file /ete/minio/config.json migrated from version '21' to '22' successfully.
Configuration file /ete/minio/config.json migrated from version '22' to '23' successfully.
Configuration file /ete/minio/config.json migrated from version '23' to '24' successfully.
Configuration file /ete/minio/config.json migrated from version '24' to '25' successfully.
Configuration file /ete/minio/config.json migrated from version '25' to '26' successfully.
Configuration file /ete/minio/config.json migrated from version '26' to '27' successfully.
Configuration file /ete/minio/config.json migrated from version '27' to '28' successfully.)

and the config file name has rename to config.json.deprecated .
I change the config.json.deprecated and start it again, i find it did not work.

the notification is {
        'QueueConfigurations': [
            {
                'Id': '1',
                'Arn': 'arn:minio:sqs::1:webhook',
                'Events': [
                    's3:ObjectCreated:*'
                ]
            },
        ],
    }
when i transfer set_bucket_notification api it will return Invalid Argument.
i debug find is <Code>InvalidArgument</Code><Message>A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.</Message>

**Comment by nitisht** [comment]
@Grapefruit-Shu Minio server behaviour with respect to `config.json` has changed. Please refer documentation https://docs.minio.io/docs/minio-bucket-notification-guide.html and try accordingly.

**Comment by kannappanr** [comment]
@Grapefruit-Shu Adding to the above comment, the ARN names are printed when the server starts up and you need to use that ARN. Can you also please paste the output of `mc admin info myminio`, `mc admin config get myminio` after redacting the `accesskey` and `secretkey`? Also, can you make sure that service to receive notification is running.

**Comment by Grapefruit-Shu** [comment]
@nitisht According to what you said i have did it ,thank you. yesterday i ignored the top message.
@kannappanr thank you too, with you said i find the ARN
