### ISSUE TITLE
cannot upload file into given minio bucket

### ISSUE THREAD

**Issue by drook** [minio/minio#7013]
I have a minio server, and a bucket that I made out of the existing directory. This directory already hold about 3/5 millions of subdirectories. I'm trying to upload the file into it using both web-client and minio-client. I'm receiving different error both ways, no erroe is logged in the logs.

## Expected Behavior

Expected behavior: I'm able to upload the file using both web-client and minio-client into a preexisting bucket.

## Current Behavior

Web-client: I'm getting the error "Rename across devices not allowed, please fix your backend configuration (/usr/local/public/.minio.sys/tmp/ad5b3e75-a98a-4485-aaa7-0b04fb642710/811e7e7f-3e0c-49b7-ac07-0385c1706e64)->(/usr/local/public/profiles/AdobeReader.desktop)". Minio is the current owner of /usr/local/public/profiles and is able to create the files/directories inside it:

````shell
profiler1% touch /usr/local/public/profiles/1
profiler1% rm /usr/local/public/profiles/1  
profiler1% id
uid=473(minio) gid=473(minio) groups=473(minio)
````

Looks like the error I'm getting in the browser is a false positive, the root cause is somewhere else.

Minio-client:

````mc
[root@profiler1:local/public]# minio-client cp /home/emz/delete.log miniolocal/profiles/
minio-client: <ERROR> Failed to copy `/home/emz/delete.log`. We encountered an internal error, please try again.
minio-client: <ERROR> Session safely terminated. To resume session `mc session resume VzYCjGLf`
````

The file is not uploaded too. Looks like there's a connection or some limit imposed on the number of entities in the bucket (just a wild guess).

## Possible Solution

In the same time I'm able to upload the file into a bucket that I've just created, (created using either web-interface or manually as a directory).

## Your Environment

* Version used (`minio version`): Version: 2018-12-13T02:04:19Z
Release-Tag: RELEASE.2018-12-13T02-04-19Z
Commit-ID: 6f7c99a33325bb11431dd56a1d261a18e5293de3
* Environment name and version (e.g. nginx 1.9.1): standalone minio
* Server type and version: VERSION: 2018-12-13T02:04:19Z
* Operating System and version (`uname -a`): FreeBSD profiler1.bsh.playkey.net 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335884: Tue Jul  3 14:26:10 MSK 2018     emz@profiler1.bsh.playkey.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by drook** [comment]
I also got some logging for two attempts:

````log
Error: Rename across devices not allowed, please fix your backend configuration (/usr/local/public/.minio.sys/tmp/1b706e
7b-e4f9-4f82-8e10-3d75baaaa353/2874bf77-e6a5-47fa-8aea-96793956daff)->(/usr/local/public/profiles/Crutch.jpg)
       1: cmd/fs-v1-helpers.go:404:cmd.fsRenameFile()
       2: cmd/fs-v1.go:937:cmd.(*FSObjects).putObject()
       3: cmd/fs-v1.go:818:cmd.(*FSObjects).PutObject()
       4: cmd/object-handlers.go:1163:cmd.ObjectLayer.PutObject-fm()
       5: cmd/web-handlers.go:838:cmd.(*webAPIHandlers).Upload()

API: SYSTEM()
Time: 09:50:11 MSK 12/21/2018
Error: Rename across devices not allowed, please fix your backend configuration (/usr/local/public/.minio.sys/tmp/1b706e
7b-e4f9-4f82-8e10-3d75baaaa353/2874bf77-e6a5-47fa-8aea-96793956daff)->(/usr/local/public/profiles/Crutch.jpg)
       1: cmd/web-handlers.go:1677:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1687:cmd.writeWebErrorResponse()
       3: cmd/web-handlers.go:840:cmd.(*webAPIHandlers).Upload()
Exiting on signal: TERMINATED
````

**Comment by nitisht** [comment]
how did you start the Minio server? Looks like the error you're getting is [EXDEV](http://man7.org/linux/man-pages/man2/rename.2.html) - have you mounted a different FS to bucket location?

**Comment by drook** [comment]
minio is started as 

````cli
/usr/local/bin/minio -C /usr/local/etc/minio server --address=:9000 --quiet /usr/local/public
````

and yes - /usr/local/public/profiles is a different filesystem mountpoint.

**Comment by nitisht** [comment]
It won’t work that way, as Linux doesn’t allow renames across mounts. Can you try starting minio on /usr/local/public/profiles

**Comment by drook** [comment]
Okay, thanks. Didn't know that.
