### ISSUE TITLE
minio server -h output includes a default Path to a deprecated configuration directory. ("/Users/Administrator/.minio")

### ISSUE THREAD

**Issue by crcjs** [minio/minio#7016]
minio server -h output includes the -C option which shows the path to a configuration directory. The configuration directory has been moved so this statement is no longer valid.

I minio server with the -C option and a valid path. It created the directory, but did not use that directory to hold the configuration files. Perhaps this portion of the code also needs to be removed?

FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/Users/Administrator/.minio")

## Your Environment
mc version RELEASE.2018-12-12T19-02-22Z

$ minio version
Version: 2018-12-19T23:46:24Z
Release-Tag: RELEASE.2018-12-19T23-46-24Z
Commit-ID: 7881791a913dacef9562e7a33a8186503d7967bf

**Comment by kannappanr** [comment]
@crcjs We are still maintaining certs in that directory. Will talk internally and see if we can rename the flag.

**Comment by harshavardhana** [comment]
It is also kept to honor previous config.json in situations where we need to preserve it. We cannot remove it so issue is sort of invalid we will have to change the wording to indicate that the cofig-dir is a legacy option.
