### ISSUE TITLE
Does Minio support search?

### ISSUE THREAD

**Issue by suryas18** [minio/minio#7025]
Does Minio offer apis for search?If not are there any options for integrating search tools with Minio Sever?If yes what are the search tools supported?Can Elastic Search be integrated with Minio?What about HIVE?Please revert.

Thanks and Regards
Surya

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
@suryas18 S3 API doesn't have a search functionality, accordingly Minio doesn't have search APIs. You can integrate Elasticsearch - follow the docs [here](https://docs.minio.io/docs/minio-bucket-notification-guide.html#Elasticsearch)

Closing this issue, feel free to reach out on [Slack](https://slack.minio.io) for further such questions.
