### ISSUE TITLE
Minio throws exception during image upload

### ISSUE THREAD

**Issue by suryas18** [minio/minio#7029]
Hi,
   I have minio server Version: go1.10.2 running from a  docker container on an ubuntu VM.

 I have made the required configuration changes in minio server for integrating an elastic search endpoint which synchronizes a .jpg file upload in minio as per the following documentation.
https://docs.minio.io/docs/minio-bucket-notification-guide.html#Elasticsearch.

The Elastic server is hosted in Windows 10 environment with version 6.5.4

The minio server is started using the following command as data and configuration needs to be persisted.
docker run -i -t -p 9000:9000 --name minio1 \
  -v /mnt/data:/data \
  -v /mnt/config:/root/.minio \
  minio/minio server /data

Uploaded an image file to minio using Java code  below which uses the minio java api maven dependency version 5.0.5

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.Map;
import java.security.InvalidKeyException;
import org.xmlpull.v1.XmlPullParserException;
import io.minio.MinioClient;
import io.minio.ObjectStat;
import io.minio.errors.MinioException;

public class ElasticSearchMetadataAdder{  
   
    /**
     * @param args
     */
    public static void main(String[] args)  throws NoSuchAlgorithmException, IOException, InvalidKeyException, XmlPullParserException{
	
	// TODO Auto-generated method stub
	
	 try {
	      
	      //Create a minioClient with the Minio Server name, Port, Access key and Secret key.    
	      
	      MinioClient minioClient = new MinioClient("http://192.168.1.102:9000", "EJW4XHRXPG2VUBLTU0YZ", "n9oNGVnx5VIYqBYyps+ShZBlarKQ+U+by+cZKKLh");	      
	      
	      // Check if the bucket already exists.
	      boolean isExist = minioClient.bucketExists("images");
	      
	      if(isExist) {
		  
	        System.out.println("Bucket already exists.");
	        
	      } else {
		  
	        // Make a new bucket called miniodemo
	        minioClient.makeBucket("images");
	        
	      }
	      
	      File file = new File("D:\\Evaluation\\Minio\\SampleFiles\\flowers.jpg");
	      byte[] content = new byte[(int) file.length()];     
	      
	      // read file into bytes[]
	      FileInputStream fileInputStream = new FileInputStream(file);
	      fileInputStream.read(content);

	      InputStream istream = new ByteArrayInputStream(content);	      
	      Map<String,String> headerMap=new HashMap();  
	      headerMap.put("patientname","Joseph");
	      headerMap.put("accounttype","100");      
	        
	      

	      System.out.println("Printing Map---"+headerMap);
	      
	      // Upload the  file to the bucket with putObject
	      minioClient.putObject("images","floral.jpg",istream,istream.available(),headerMap);
	      istream.close();
	      System.out.println("File successfully uploaded to images bucket.");	    	      
	      
	      //To retrieve the metadata information of an uploaded file
	      ObjectStat objStat = minioClient.statObject("miniodemo","floral.jpg"); 
	      	      
	      System.out.println("---Printing Metadata---"+ objStat.httpHeaders());     
	          
	     
	      
	      
	    } catch(MinioException e) {
	      System.out.println("Error occurred: " + e);
	    }

    }
}

## Expected Behavior
Using the same code i could upload a .txt file to a different bucket which is not synchronized with elastic search without any exceptions thrown.
## Current Behavior
The image file got uploaded successfully and got synchronized to the elastic server index configured.This line of code System.out.println("---Printing Metadata---"+ objStat.httpHeaders()) is not getting executed.
Alongside I am  getting the following exception.

Error occurred: error occurred
ErrorResponse(code=NoSuchKey, message=Object does not exist, bucketName=miniodemo, objectName=floral.jpg, resource=/miniodemo/floral.jpg, requestId=15747DBF60C90E6A, hostId=null)
request={method=HEAD, url=http://192.168.1.102:9000/miniodemo/floral.jpg, headers=Host: 192.168.1.102:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20181228T120714Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20181228/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=404, headers=Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2018-12-19T23-46-24Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 15747DBF60C90E6A
X-Minio-Deployment-Id: ac1fb996-e335-4b03-9de3-0c32446f5ee4
X-Xss-Protection: 1; mode=block
Date: Fri, 28 Dec 2018 12:07:13 GMT
}

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Minio server Version: go1.10.2 running from a  docker container on an Ubuntu 16.04.3 LTS VM.
The Elastic Search server is hosted in Windows 10 environment with version 6.5.4
Minio Java API maven dependency version 5.0.5

Please revert

Thanks
Surya

**Comment by harshavardhana** [comment]
> // Upload the file to the bucket with putObject minioClient.putObject("images","floral.jpg",istream,istream.available(),headerMap); istream.close(); System.out.println("File successfully uploaded to images bucket.");	//To retrieve the metadata information of an uploaded file ObjectStat objStat = minioClient.statObject("miniodemo","floral.jpg");

Here the object was uploaded to `images` bucket but you are doing a statObject on `miniodemo`  bucket - this is a bug in your code, can you check?

**Comment by suryas18** [comment]
@harshavardhana,  thanks for the support.doing a statObject on **images** bucket solved the issue.

**Comment by harshavardhana** [comment]
> @harshavardhana, thanks for the support.doing a statObject on **images** bucket solved the issue.

@suryas18 please close the issue if there is nothing else pending.
