### ISSUE TITLE
configure minio instance documentation

### ISSUE THREAD

**Issue by Gibheer** [minio/minio#7032]
Some time ago the configuration `config.json` was moved into the data directory. This leads to some confusion on my side. I don't know if it is even supposed to work the way it was documented in the past.

The [configuration guide](https://docs.minio.io/docs/minio-server-configuration-guide.html) states that the access key and secret key can be given in the `config.json`. As this file was moved into the data directory, it isn't read. But after the data directory was created with the environment variables supplied, the access key and secret key in the configuration are ignored. So there is just no way to set these variables. Maybe this should be removed in the configuration guide.
There is also no hint anywhere, that the secret and access key need to be provided using environment variables, as the service starts fine without them. I think the best way to handle that case would be to just exit 1 when configuration options are not provided.

After some testing I found minio also listening on all interfaces on port 9000. This can lead to the same problem mongodb had some time ago with being deployed on a server and being open to all requests.

Is it possible to provide add a configuration file which can be written using a configuration management system and minio using this as a base to start all other operations? For me, the most important options at the moment are the other instances, the listening address and secret/access key.
At the same time all config options should be made configurable through all mechanisms. At the moment command line parameters and environment variables are support for some but not all options and need to be collected in the init/rc/systemd script in different ways, which makes the configuration harder than necessary.

## Expected Behavior
Minio should be configurable through a config file and all options should be possible to be provided through command line options and environment variables.

## Current Behavior
At the moment secret and access key can only be provided using environment variables. When monio starts and these variables are missing, it does not crash or hint that these are missing, the cluster is just inaccessible. Normally, this wouldn't regarded as a proper start.

## Possible Solution
One option would be to provide a configuration file which handles the node specific configuration data, like the access and secret key, listening address and peers to use.

## Steps to Reproduce (for bugs)
1. start an instance of minio with config-dir set and no environment variables defined.
2. netstat -ln shows a listening service on port 9000 on all interfaces
3. mc can't connect because of missing credentials

## Context
I am trying to build a minio cluster to get started trying it out and hit this error. I am using a self compiled minio. The plan is to generate the configuration based on documentation, which is  not possible with how minio works at the moment.

## Regression
No idea if this is a regression. But seeing the documentation on config.json, I would say it is.

## Your Environment
* Version used (`minio version`): `root@store1a:/ # minio version
Version: 2018-12-13T02:04:19Z
Release-Tag: RELEASE.2018-12-13T02-04-19Z
Commit-ID: 6f7c99a33325bb11431dd56a1d261a18e5293de3`
* Environment name and version (e.g. nginx 1.9.1): nothing specific, just starting minio
* Server type and version: bare metal server
* Operating System and version (`uname -a`): FreeBSD 12.0-RELEASE

**Comment by harshavardhana** [comment]
config.json carrying credentials is incidental and historical .. distributed setup requires environment keys such as MINIO_ACCESS_KEY and MINIO_SECRET_KEY

We are not going back to old ways of configuring Minio where each server brings it's own config.json, this part is centralized.

The way to configure Minio after it's setup is to use `mc admin config get/set` , there are some options which are env only which are also documented.

**Comment by harshavardhana** [comment]
`--config-dir` is still provided such that we can migrate your existing config to latest and move it to the data directory. So we cannot deprecate that option. Instead we are going to mention that this option is legacy and will be removed in future.

If env is not provided in distributed setup and we see an old config file, we still try to use it but indicate that this style is deprecated.

**Comment by Gibheer** [comment]
Hi,

thank you for answering. I have no problems with the mc admin config get/set functionality for setting cluster wide options. But it already contains functionality, that isn't supported with the way you want things to work.

For example when using mc admin config get I can see the access key, which would mean, I would be able to change that setting with the `set` command. But that option is only provided using environment variables, so any change there would be meaning less.

Also you can't set the directories and other nodes using pure environment variables. I think having the keys and more options which are only needed to get the node up and running were in a nice spot in the config.json.

I also tried to figure out why you were removing the config.json completely as it seemed to be the way to configure minio for a long time, but there was just no reason given. I understand that there were some options which were meant for the cluster as a whole. Moving these into the the mc admin config command was a good move. But the node configuration like the listening address, keys, certificates and data peers would be good in a config.json.

Moving back to config.json now (again from what I gathered), would be very confusing for the people running minio in production, I understand that.
Would it be an option to provide a flag --node-config to point to a json file which contains the most important node specific configuration options? That way people without etcd, docker, kubernetes and so on would be able to persist their configuration, other would still be able to use the environment variables. If you would be okay with this change, I would try to come up with a pull request to support this behavior.

**Comment by harshavardhana** [comment]
> I also tried to figure out why you were removing the config.json completely as it seemed to be the way to configure minio for a long time, but there was just no reason given. I understand that there were some options which were meant for the cluster as a whole. Moving these into the the mc admin config command was a good move. But the node configuration like the listening address, keys, certificates and data peers would be good in a config.json.

config.json is going through a drastic change where we are even moving aware from json to a flat model where there are only keys and values. So we will be deprecating all that you know till now anyways. 

The point was simply to provide a more controlled deployment style, basically `config.json` maintenance across the nodes was a hindrance to many of our users and made deployment quite tricky. We saw most deployments simply used envs for credentials. Minio server once moved to flat model will come up regardless but can be configured outside using `mc admin` commands - like enabling disabling certain types for features. Each config value will also have a env equivalent such that users can override them.

This is a common framework written such that we can move away from json style.

> Moving back to config.json now (again from what I gathered), would be very confusing for the people running minio in production, I understand that.
> Would it be an option to provide a flag --node-config to point to a json file which contains the most important node specific configuration options? That way people without etcd, docker, kubernetes and so on would be able to persist their configuration, other would still be able to use the environment variables. If you would be okay with this change, I would try to come up with a pull request to support this behavior.

No this is not correct config.json is already persisted in the backend with erasure coding, nothing is more safer than that. Also, there is no node specific configuration we want all nodes/servers in a cluster to be the same - we do not entertain heterogenous deployments. This was the case even in the past differences in `config.json` wouldn't allow cluster to be setup.  Right now since `config.json` is centralized to the backend it means that all nodes know and see the same configuration.


> For example when using mc admin config get I can see the access key, which would mean, I would be able to change that setting with the `set` command. But that option is only provided using environment variables, so any change there would be meaning less.

As I said it is incidental and purely historical, we didn't change much because we are refactoring the entire configuration management to be moved away from `json` style to a more flat model. in the new flat model the keys which cannot be set using `mc admin` will never be displayed such as credentials.
