### ISSUE TITLE
What is XMinioServerTimedOut and how to prevent it?

### ISSUE THREAD

**Issue by Joozty** [minio/minio#7034]
I use Minio for storing files and sometimes when I send a big file to Minio I receive "XMinioServerTimedOut". Which is error on server side I think. Could somebody please descibe me what is it and how to increase it?

My understanding is that it's some timeout set on server and if the request doesn't send data within that time server close connection. Is it correct?

I found Pull Request which introduced this feature but couldn't understand it. 

https://github.com/minio/minio/pull/4377

Thanks

**Comment by nitisht** [comment]
@Joozty please use the issue template while creating issues - it helps avoid repetitive questions like what is the minio version, a minimal way to reproduce your issue and other details about your environment. 

Please give more details for us to help you better

**Comment by harshavardhana** [comment]
XMinioServerTimedOut is when you are trying to take WriteLock on an existing ReadLock or another WriteLock on the same resource. This usually points to a bug in your application. 

Closing this issue as answered...
