### ISSUE TITLE
Is default port 9000 intended? It conflicts with PHP XDebug

### ISSUE THREAD

**Issue by tomekit** [minio/minio#7036]
This is not an issue, I've thought I will just share it.

I've noticed that minio default port conflicts with the PHP XDebug's default listening port which is 9000.

Is port `9000` intended? Do you think it might make sense to change it to something else, so it doesn't conflict? I believe PHP XDebug is pretty much standard nowadays, at least within the PHP community (which isn't small I think).

My solution is to run minio on different port. I've decided to use 8000 (which is S3 Scality default)

New `Dockerfile`
```
FROM minio/minio
EXPOSE 8000
```
and by adding this to command: `--address ":8000"`

Note: Additional `Dockerfile` might not be needed if you override the listening ports using the e.g. `-P 127.0.0.1:8000:8000`

**Comment by nitisht** [comment]
> Is port 9000 intended? 

Yes, it is intended @tomekit . 

> Do you think it might make sense to change it to something else, so it doesn't conflict?

Changing to something else may conflict with some other application's port. Hence as you rightly noted, the way to avoid this is running Minio on a port of your choice using the `--address` flag. 

Closing this issue as there is no action from our side.
