### ISSUE TITLE
CopyObjectPart not implemented for azure-gateway

### ISSUE THREAD

**Issue by PascalVA** [minio/minio#7042]
I am working on a go application that uses minio-go to perform a multi-part upload of a data stream of unknown size, followed by a server-side compose to create the final object. The code I wrote appears to be working on AWS S3 and on Minio as a server, but when on Minio as an Azure gateway.

I've discussed with nitish on slack and he found that `CopyObjectPart` was not implemented.

## Expected Behavior
Create one single file out of a list of uploaded parts.

## Current Behavior
Returns an error:
> 2019/01/07 10:44:43 845152256 A header you provided implies functionality that is not implemented exit status 1

MINIO_HTTP_TRACE of the problem:
```
[REQUEST (objectAPIHandlers).CopyObjectPartHandler-fm] [154661821.575983] [2019-01-04 16:10:15 +0000]
PUT /somebucket/ubuntu-18.04-live-server-amd64.iso?partNumber=1&uploadId=7ac687c79c91bdd7
Host: localhost:9000
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Copy-Source-If-Match: 0x8D6725EC1CC7E86-1
X-Amz-Date: 20190104T161015Z
Authorization: AWS4-HMAC-SHA256 Credential=somebucket/20190104/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=ffa1bcdcb9de5a775100b6de74fff61c217251586fa89e9a1dc4fffd21a24de5
X-Amz-Copy-Source: somebucket/ubuntu-18.04-live-server-amd64.iso-parts-1546618050234392897/0
X-Amz-Copy-Source-Range: bytes=0-104857599
User-Agent: Minio (linux; amd64) minio-go/v6.0.12
Content-Length: 0


[RESPONSE] [154661821.575983] [2019-01-04 16:10:16 +0000]
501 Not Implemented
X-Amz-Request-Id: 1576B112A9813000
Server: Minio/RELEASE.2018-12-27T18-33-08Z (linux; amd64)
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Resource>/somebucket/ubuntu-18.04-live-server-amd64.iso</Resource><RequestId>1576B112A9813000</RequestId><HostId>3L137</HostId></Error>
```

## Steps to Reproduce (for bugs)
1. Start Minio as an azure gateway
2. Create a multi-part upload using the code below (replace the ubuntu iso with anything you like that is bigger than 100MB or change the chunks/chunkSize to test with a smaller file:
```
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"time"

	minio "github.com/minio/minio-go"
)

func main() {

	fileName := "ubuntu-18.04-live-server-amd64.iso"
	src, _ := os.Open(fileName)
	defer src.Close()

	var (
		chunkCount = 0
		chunkSize  = int64(100 * 1024 * 1024)
		buf        = make([]byte, chunkSize)
		maxChunks  = 10000 // Maximum allowed by s3
		partsPath  = fmt.Sprintf("%s-parts-%d", fileName, time.Now().UnixNano())
		srcObjects = make([]minio.SourceInfo, maxChunks)
		totalSize  int64

		endpoint  = "minio-gateway-endpont"
		accessKey = "azure-access-key"
		secretKey = "azure-secret-key"
		useSSL    = false
		bucket    = "azure-bucket"
	)

	c, _ := minio.New(endpoint, accessKey, secretKey, useSSL)

	for chunkCount < maxChunks {
		n, err := io.ReadFull(src, buf)
		if err == io.EOF {
			break
		}
		totalSize += int64(n)
		if err != nil && err != io.ErrUnexpectedEOF {
			log.Fatal(totalSize, err)
		}

		chunkName := fmt.Sprintf("%s/%d", partsPath, chunkCount)
		if _, err = c.PutObject(bucket, chunkName, bytes.NewReader(buf[:n]), int64(len(buf[:n])),
			minio.PutObjectOptions{ContentType: "application/octet-stream"}); err != nil {
			log.Fatal(totalSize, err)
		}

		srcObjects[chunkCount] = minio.NewSourceInfo(bucket, chunkName, nil)

		chunkCount++
	}

	dstObject, err := minio.NewDestinationInfo(bucket, fileName, nil, nil)
	if err != nil {
		log.Fatal(totalSize, err)
	}

	//Error happens here:
	if err = c.ComposeObject(dstObject, srcObjects[:chunkCount]); err != nil {
		log.Fatal(totalSize, err)
	}
}
```

## Context
I am trying to create an multi-part upload solution that works across AWS, Azure, GCP and minio server.

## Regression
No

## Your Environment
go version go1.11.4 linux/amd64
mino RELEASE.2018-12-27T18-33-08Z

**Comment by harshavardhana** [comment]
It is not implemented on purpose @PascalVA because of the complications it brings in. We can relook at implementing this and see what were the technical challenges.

**Comment by PascalVA** [comment]
@harshavardhana Ok thanks! In the meantime is there a workaround I should use for multipart uploads?

**Comment by harshavardhana** [comment]
> @harshavardhana Ok thanks! In the meantime is there a workaround I should use for multipart uploads?

There is no workaround @PascalVA unfortunately

**Comment by mishak87** [comment]
This is requirement to have minio gateway azure for docker registry (distribution).
Image pushes fail on upload because registry is expecting blob `data` and gets blobs
`startedat` and `hashstates/*` instead.

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
