### ISSUE TITLE
Misleading implementation of minio-java:putObject

### ISSUE THREAD

**Issue by marcadella** [minio/minio#7053]
putObject should take an OutputStream and not an InputStream. It works ok with IS, but it is misleading. In addition the SDK doc does not mention that one should close the IS (as it is done for getObject).

**Comment by harshavardhana** [comment]
Please open an issue at https://github.com/minio/minio-java

**Comment by kannappanr** [comment]
Closing this issue here. Created a new issue in minio-java https://github.com/minio/minio-java/issues/746
