### ISSUE TITLE
Support OpenID configuration URL

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#7055]
## Expected Behavior
All OIDC compliant implementations provide a configuration URL which provides all the necessary URLs for OpenID token generation, token validation certs, and additional user metadata URLs

Such as 
https://accounts.google.com/.well-known/openid-configuration

```json
{
  "issuer": "https://accounts.google.com",
  "authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
  "token_endpoint": "https://oauth2.googleapis.com/token",
  "userinfo_endpoint": "https://openidconnect.googleapis.com/v1/userinfo",
  "revocation_endpoint": "https://oauth2.googleapis.com/revoke",
  "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs",
  "response_types_supported": [
    "code",
    "token",
    "id_token",
    "code token",
    "code id_token",
    "token id_token",
    "code token id_token",
    "none"
  ],
...
```

## Current Behavior
No such support today makes it harder to provide multiple such URLs one for each endpoints.

## Possible Solution
Support parsing and caching OpenID configuration URLs

## Steps to Reproduce (for bugs)
There is no such way, this is a new feature.

## Context
OpenID compliance this is part of the OpenID standard

## Regression
No

## Your Environment
master

**Comment by harshavardhana** [comment]
PR #8075 is adding this support as well, added by @kanagarajkm

**Comment by jonasscherer** [comment]
I would like to try your new OICD feature. Is there a way to set the configuration for JWKS_URL and CONFIG_URL using environment variables in the Docker container? 
thanks

**Comment by harshavardhana** [comment]
Yes after the new release is done, it will be available.

**Comment by harshavardhana** [comment]
This is fixed in master, closing this issue as fixed.
