### ISSUE TITLE
Publish docker images for ppc64le platform

### ISSUE THREAD

**Issue by mkumatag** [minio/minio#7062]
Currently, only amd64 architecture binaries and docker images are published part of minio release process, this issue is for requesting to build and publish them for ppc64le platform as well.

**Comment by harshavardhana** [comment]
We already publish ppc64le binaries - if docker hub provides a way to build ppc64le images we can definitely build one.

**Comment by mkumatag** [comment]
> We already publish ppc64le binaries - if docker hub provides a way to build ppc64le images we can definitely build one.

That's fantastic, I'm not really sure whether we can build the image from dockerhub but we can build docker image for power via Travis.

**Comment by harshavardhana** [comment]
Yeah we did try that but Travis CI is is flaky and failed to run optimally as expected. Since our CIs need to be consistent we had to remove it.

**Comment by kannappanr** [comment]
@mkumatag Closing this issue as we already publish the binaries. Please feel free to open issues if you have any other question.

**Comment by mkumatag** [comment]
@kannappanr but docker image is not present, hence I want to still track that work in this issue, so can you please reopen it?

**Comment by kannappanr** [comment]
@mkumatag Will investigate if if docker hub provides a way to build ppc64le image.

**Comment by harshavardhana** [comment]
It's not possible to publish ppc64le images on docker hub automatically,  if docker provides this feature we can use it too. Until then I don't see what else we can do here..

**Comment by J0WI** [comment]
How about contributing to the standard library which supports all major architectures out of the box?
https://github.com/docker-library/official-images#contributing-to-the-standard-library

**Comment by kannappanr** [comment]
Closing this issue for now. Once docker add support, we can publish docker images for ppc64le.
