### ISSUE TITLE
Update readme file with ppc64le binary

### ISSUE THREAD

**Issue by mkumatag** [minio/minio#7063]
Currently I see minio binary is already published for ppc64le but readme is not updated with the relevent link, this task is for updating the readme file with proper link.

Reference: https://github.com/minio/minio/issues/7062#issuecomment-452970812

Readme link - https://github.com/minio/minio#gnulinux

**Comment by kannappanr** [comment]
@mkumatag We will update the readme with a link to the ppc64le binary.
