### ISSUE TITLE
Can't download file as non admin user

### ISSUE THREAD

**Issue by Carlj28** [minio/minio#7066]
I have minio server with one bucket and two files in it:
![2019-01-10 15_13_39-](https://user-images.githubusercontent.com/4525831/50973983-83f0a600-14ea-11e9-9903-fc0952ca62f3.png)
Next i have created policy to have acces only for this bucket:
` "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "s3:GetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Resource": "arn:aws:s3:::sylwester/*",
      "Sid": "New01"
    }
  ]
}
`
Added this policy:
`./mc admin policy add minio/ getonly getonly.json`
And added user with that policy:
`./mc admin user add minio sylwester18 pass getonly`
Now when i log in as this user I can see this files:
![2019-01-10 15_18_49-](https://user-images.githubusercontent.com/4525831/50974242-15f8ae80-14eb-11e9-97ae-b06ff659f24f.png)
But after selecting **only one** file and clicking **Download object** page is refreshed, file is not downloading and now user can't see any files (i nead to login as admin and as user again to see them):
![2019-01-10 15_21_18-pulpit - freecommander xe](https://user-images.githubusercontent.com/4525831/50974396-725bce00-14eb-11e9-8c3b-8b5f2d19c6f4.png)
Selecting two files and clicking **Download all as zip** gives no result, nothing is happening, no error:
![2019-01-10 15_23_52-](https://user-images.githubusercontent.com/4525831/50974558-cebeed80-14eb-11e9-85a6-2fbd42a9bd13.png)

*Files can be downloaded when I'm logged in as admin
*Edit
I seems that when I am logged in as admin and switch account to other user files list are cached? After clearing cache ctrl + shift + r files are disappearing again...

So my config file is wrong?
## Expected Behavior
File(s) are downloaded.

## Your Environment
* Version used:
Version: 2019-01-10T00:38:22Z
Release-tag: RELEASE.2019-01-10T00-38-22Z
Commit-id: 0854af6e6d3e9f79e8d9c98db5e0d133a527923b
* Operating System and version:
Linux vps579996 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Comment by poornas** [comment]
@Carlj28 , you will also need to give s3:ListBucket permission in your bucket policy

**Comment by kannappanr** [comment]
@Carlj28 Closing this issue as answered. Please feel free to reach out to us if you have any questions.
