### ISSUE TITLE
Policy in sub-directory not working

### ISSUE THREAD

**Issue by marcadella** [minio/minio#7068]
## Expected Behavior
When I set a user with the following policy `{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::my-bucket/user1/*"]}]}` I expect to be able to put/get an object under `my-bucket/user1/` and not anywhere else.

## Current Behavior
When I try to set-up such a user (after having created `my-bucket` with my admin credentials), and open the GUI, `my-bucket` is not listed to the left (there are no buckets there). I cannot upload objects or do anything. I tried with the Java API as well but I get `access denied` when I try to upload a file under `my-bucket/user1/`.
Everything works as expected however when I set the policy to `"arn:aws:s3:::my-bucket/*"`

## Steps to Reproduce (for bugs)
1. Create a bucket my-bucket as admin
2. Create the following policy: `{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::my-bucket/user1/*"]}]}`
3. Create a user with that policy: `mc admin user add X user1 XXX my-policy`
4. Try to upload a file to my-bucket/user1/ via the GUI or via java sdk.

## Context
I have one bucket per project and I divided each bucket into user spaces (so my-project-bucket/my-user-name) and I want to limit the read/write for each users to its own user-space only (so I create a policy for each user where the resource is "arn:aws:s3:::my-project-bucket/my-user-name/*"). Because of the bug, the users cannot read/write to their own user-space.

## Regression
I don't know

## Your Environment
VERSION
2018-12-27T18:33:08Z
MEMORY
Used: 7.6 MB | Allocated: 44 GB | Used-Heap: 7.6 MB | Allocated-Heap: 154 MB
PLATFORM
Host: ea250a18f3c9 | OS: linux | Arch: amd64
RUNTIME
Version: go1.10.7 | CPUs: 4

**Comment by nitisht** [comment]
we'll take a look @marcadella

**Comment by krisis** [comment]
@marcadella I was able to upload a file as `user1` in the setup described above. Could you paste your java SDK based code to help us recreate the issue locally? 

Moreover, I was unable to list entries under `my-bucket/user1` on the browser, as you mentioned. But this is expected with the policy definition. Listing of objects (and prefixes) under a bucket require permissions for `s3:ListBucket` operation at the bucket-level. This can be controlled at a per user level to the appropriate prefix, like `my-bucket/user1` for `user1` etc. https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/ explains the process in detail. Let us know if this works for you.

**Comment by marcadella** [comment]
Ok, I guess I was using the wrong policy then. I opened a new ticket however because the policy provided in your link cannot be loaded by mc (https://github.com/minio/minio/issues/7076).

**Comment by marcadella** [comment]
I tried the policy provided in your link and it still doesn't work.

##Steps
1. I add a user called 'user1' and assign it the following policy:
```
{  
   "Version":"2012-10-17",
   "Statement":[  
      {  
         "Sid":"AllowGroupToSeeBucketListInTheConsole",
         "Effect":"Allow",
         "Action":[  
            "s3:GetBucketLocation",
            "s3:ListAllMyBuckets"
         ],
         "Resource":[  
            "arn:aws:s3:::*"
         ]
      },
      {  
         "Sid":"AllowRootAndUserListingInBucket",
         "Effect":"Allow",
         "Action":[  
            "s3:ListBucket"
         ],
         "Resource":[  
            "arn:aws:s3:::bucket-test"
         ],
         "Condition":{  
            "StringEquals":{  
               "s3:prefix":[  
                  "",
                  "users/"
               ]
            }
         }
      },
      {  
         "Sid":"AllowListingOfUserFolder",
         "Effect":"Allow",
         "Action":[  
            "s3:ListBucket"
         ],
         "Resource":[  
            "arn:aws:s3:::bucket-test"
         ],
         "Condition":{  
            "StringLike":{  
               "s3:prefix":[  
                  "users/${aws:username}",
                  "users/${aws:username}/*"
               ]
            }
         }
      },
      {  
         "Sid":"AllowAllS3ActionsInUserFolder",
         "Effect":"Allow",
         "Action":[  
            "s3:*"
         ],
         "Resource":[  
            "arn:aws:s3:::bucket-test/users/${aws:username}/*"
         ]
      }
   ]
}
```
2. I check that the policy for user1 matches the one above (because it is not always the case, cf: https://github.com/minio/minio/issues/7078)

3. I put an object into bucket-test::users/user1/
```
val client =
      new MinioClient(endpoint,
                      "user1",
                      "password1")

    client.putObject("bucket-test",
                     "users/user1/blah",
                     pathToFile)
```

**Comment by marcadella** [comment]
It seems to work if I replace ${aws:username} with the user name (and create a policy for each user). Doesn't Minio support ${aws:username} or an equivalent?
HOWEVER: Even with the policy above, and even though I can put and get object under user/user1 via java SDK, I still cannot do anything from the GUI when logged as user1 (the list of buckets is empty, none of the files I uploaded is displayed, and I cannot upload any files).

**Comment by harshavardhana** [comment]
> It seems to work if I replace ${aws:username} with the user name (and create a policy for each user). Doesn't Minio support ${aws:username} or an equivalent?
> HOWEVER: Even with the policy above, and even though I can put and get object under user/user1 via java SDK, I still cannot do anything from the GUI when logged as user1 (the list of buckets is empty, none of the files I uploaded is displayed, and I cannot upload any files).

No we don't @marcadella we can support it in future, for now, we don't

**Comment by marcadella** [comment]
Ok thanks for your reply. What about "Even with the policy above, and even though I can put and get object under user/user1 via java SDK, I still cannot do anything from the GUI when logged as user1 (the list of buckets is empty, none of the files I uploaded is displayed, and I cannot upload any files)."?

**Comment by harshavardhana** [comment]
> HOWEVER: Even with the policy above, and even though I can put and get object under user/user1 via java SDK, I still cannot do anything from the GUI when logged as user1 (the list of buckets is empty, none of the files I uploaded is displayed, and I cannot upload any files).

GUI requires a lot of specific access it is not an S3 frontend so don't expect everything to work similar to how an S3 API SDK would work, and we have no intention on making it compliant with every single S3 feature. It is meant for minimal uses it is not meant for Dropbox-like replacement and we have no intention of moving towards Dropbox-like UI. 

Use a frontend which implements S3 API all of this would work automatically without much of issues.

**Comment by harshavardhana** [comment]
Now that I explained the browser implementation requirement, what you are attempting should work and is currently supported.

Will look at the policy evaluation.

**Comment by harshavardhana** [comment]
@marcadella I tested browser requires some extra features for ListBuckets etc to get this working properly. Currently, it is only supported to list an entire bucket. For users listing other buckets is explicitly disabled unless they have explicit access.

Your policy is a bit more involved it requires more work on browser to support this scenario. As I said before the browser is not fully ready for complex policies, we will take this as a feature and try to implement it. 

Regarding the issue of using `aws:username` sent a PR to support policy variables - https://github.com/minio/minio/pull/7085

**Comment by marcadella** [comment]
Thanks for the quick answers and help provided. I'll keep an eye on the new feature releases then :)
