### ISSUE TITLE
Minio rollback failed "ERROR Unable to initialize config system"

### ISSUE THREAD

**Issue by lcnsir** [minio/minio#7069]
Whe I upgrade minio (from )in k8s cluster with helm upgrade, the mino upgrade successfully, but when I rollback it, the error shows 

ERROR Unable to initialize config system: configuration version mismatch. Expected: ‘28’, Got: ‘32’.
      > Please ensure a valid value in the configuration file.
      HELP:
        For more details, refer to https://docs.minio.io/docs/minio-server-configuration-guide

Then minio can not start , unless I manually edit the file minio/.minio.sys/config/config.json in the host.

## Expected Behavior
A more grace method to rollback minio that no need to edit file of minio/.minio.sys/config/config.json

**Comment by harshavardhana** [comment]
Rollback is never supported @lcnsir we always move forward, if you wish to rollback then you can delete the entries manually at `minio/.minio.sys/config/` on all nodes and all disks.

**Comment by lcnsir** [comment]
Thanks @harshavardhana

**Comment by nitisht** [comment]
Closing this as working as intended @lcnsir
