### ISSUE TITLE
Command line  cound not Copy multiple local folders recursively to Minio cloud storage.

### ISSUE THREAD

**Issue by chenyu85** [minio/minio#7070]
## Expected Behavior
I want create a folders in my minio of the bucket "test",so i use the command line tools 
`/mc.exe cp --recursive backup/2014/ backup/2015/  - play/test`
## Current Behavior
`./mc.exe cp --recursive backup/2014/ backup/2015/ play/test
Total: 0 B, Transferred: 0 B, Speed: 0 B/s` 
` ./mc.exe ls play/test
[2019-01-12 10:33:54 CST]     6B file2.txt
[2019-01-12 10:58:14 CST]    16B file222222.txt
`
 There's no folders was created with the CML  or the UI browser.

## Possible Solution
Is the stroage Object system not support file folders ?

## Steps to Reproduce (for bugs)
1. create local folders:"backup/2014、backup/2015"
2. excute the command `/mc.exe cp --recursive backup/2014/ backup/2015/ play/test`
## Your Environment
VERSION
2018-12-15 T 22:14:08Z
PLATFORM
OS: Windows | Arch: amd64
RUNTIME
go version go1.11.2 windows/amd64

**Comment by kannappanr** [comment]
@chenyu85 I tried this option on Ubuntu and it worked.

We will try this on a windows machine and see why this is not working.

Meanwhile, can you try `mc.exe cp --recursive backup/ play/test`

**Comment by chenyu85** [comment]
Thanks for your suggestion, and I've tried with command `mc.exe cp --recursive backup/ play/test` ,no error occurred,as follows：
` ./mc.exe cp --recursive backup/ play/test
Total: 0 B, Transferred: 0 B, Speed: 0 B/s`
there's no folders created.
Is that mean it can not create folders in the bucket? Also I found I can not create folders on the  UI browser.

**Comment by chenyu85** [comment]
I tried this  on Ubuntu and it worked,maybe this a bug in windows.
