### ISSUE TITLE
I really hope to add the ability to create a new folder in the browser. Can it be achieved?

### ISSUE THREAD

**Issue by xiaomaiyun** [minio/minio#7072]
I really hope to add the ability to create a new folder in the browser. Can it be achieved?

**Comment by vadmeste** [comment]
> I really hope to add the ability to create a new folder in the browser. Can it be achieved?

If you want to upload a file under a specific hierarchy, you can choose the path even if it doesn't exist yet, but you cannot create an empty directory yet using the browser, although it is possible to do with mc command, something like, `mc mb alias/bucket/empty_dir/`
