### ISSUE TITLE
MINIO_DOMAIN not working as expected

### ISSUE THREAD

**Issue by zefie** [minio/minio#7073]
After a bunch of researching for vhost style buckets on Minio, I found that you settled on requiring the MINIO_DOMAIN environment variable set.

I have the following setup:
(all references to "mydomain.fake" are a replacement for a real, working domain in reality, actual details can be given in private if needed)

```
export MINIO_DOMAIN=storage.mydomain.fake
/usr/local/bin/minio server --address storage.mydomain.fake:443 /home/zefie/minio
```

On the DNS end, a wildcard record has been added and is functional.
On the SSL end, a cert for storage.mydomain.fake AND *.storage.mydomain.fake has been obtained from LetsEncrypt

## Expected Behavior

visiting bucketname.storage.mydomain.fake should load the contents of bucketname

## Current Behavior

visiting bucketname.storage.mydomain.fake loads the root contents, as if was accessed by standard storage.mydomain.fake

## Possible Solution

Perhaps has to do with MINIO_DOMAIN being a subdomain? Unable to test with root domain.

## Steps to Reproduce (for bugs)

1. Set up domain with wildcard DNS
2. Optional SSL config (issue happens with or without TLS anyway, so not important)
3. Run server with MINIO_DOMAIN=thedomain and include thedomain in --address
4. vhost doesn't work

## Context

I am trying to use vhost style bucket names

## Regression

Maybe? Others said it worked in September, latest info I found was #6437 

## Your Environment

* Version used (`minio version`): minio dev 9a71f2fdfa6d721b6f1fd54362c25ec7995d33bd
* Environment name and version (e.g. nginx 1.9.1): no proxy (although tried with nginx/1.14.1 with the same result)
* Server type and version: ARM armada375 (forced to build my own binaries, produced by using  ```go get -u github.com/minio/minio``` followed by ```go build -o minio github.com/minio/minio```)
* Operating System and version (`uname -a`): Linux storage.mydomain.fake 4.9.142-kc375 #27 SMP Mon Dec 3 11:15:18 CET 2018 armv7l armv7l armv7l GNU/Linux
* Link to your project: n/a

**Comment by harshavardhana** [comment]
Assuming you are talking about Minio browser. Minio browser doesn't support such nuances of S3 API, since it is not an S3 API frontend. It is a custom implementation which uses a custom json rpc protocol to provide a UI. 

It you are talking about Minio browser this is out of scope at the moment.

**Comment by zefie** [comment]
Alright, understandable.

Although turning off ```use_path_style_endpoint``` in the aws php sdk in my working application breaks it, but more debugging would have to be done on my end for that.

**Comment by zefie** [comment]
Apparently it was my end. So since you addressed the issue with the Browser, technically there is no issue, thus I will close this.
