### ISSUE TITLE
Uploading the file successfully using Dropzone, however, downloading the file does not open correctly.

### ISSUE THREAD

**Issue by xiaomaiyun** [minio/minio#7075]
## Expected Behavior
Use XMLHttpRequest to upload the file (XMLHttpRequestUploadToMinio.jpg) to minio in js, and use Dropzone(or plupload)  to upload the file (DropzoneUploadToMinio.jpg) to minio in js. The effect I expect is to enter https://play.minio.io:9000/xiaomaiyun/XMLHttpRequestUploadToMinio.jpg and https://play.minio.io:9000/xiaomaiyun/DropzoneUploadToMinio.jpg can be accessed correctly in the form of pictures.

## Current Behavior
https://play.minio.io:9000/xiaomaiyun/XMLHttpRequestUploadToMinio.jpg is correctly accessed as a picture, but https://play.minio.io:9000/xiaomaiyun/DropzoneUploadToMinio.jpg cannot be accessed correctly as a picture. Even though XMLHttpRequestUploadToMinio.jpg and DropzoneUploadToMinio.jpg are the same image, only the file names are different.

## Possible Solution
Maybe I missed the parameters that should be set when I use Dropzone (or plupload) to upload files, but I can't set it up, I hope to get your help. Can you provide an example? Thank you!

## Steps to Reproduce (for bugs)
This is the html and js files used.https://github.com/xiaomaiyun/uploadToMinio/tree/master/src/main/resources/static.In addition, I want to know, uploading files to minio in js, can only use the 'PUT' method, but can't use 'POST'?

## Your Environment
Dropzone(or plupload)

**Comment by harshavardhana** [comment]
You need to set the content-type during upload @xiaomaiyun

**Comment by xiaomaiyun** [comment]
> You need to set the content-type during upload @xiaomaiyun

I am very sorry, I don't know how to set it up. I am not very familiar with js. I will be very grateful if you can give me a simple example. The address of this html file is: https://github.com/xiaomaiyun/uploadToMinio/blob/master/src/main/resources/static/dropzoneUploadToMinio.html

**Comment by harshavardhana** [comment]
https://www.dropzonejs.com/#configuration you need to set headers with `content-type: image/jgeg`

**Comment by xiaomaiyun** [comment]
> https://www.dropzonejs.com/#configuration you need to set headers with `content-type: image/jgeg`

Okay, I understand. Thank you!
