### ISSUE TITLE
File access permission question

### ISSUE THREAD

**Issue by xiaomaiyun** [minio/minio#7077]
## Expected Behavior
I have three pictures at https://play.minio.io:9000/xiaomaiyun/, favicon.ico and xiaomaigou_favicon.ico and xiaomaigoulogo.png, my buckets 'xiaomaiyun' didn't set any prefix, but when I was at When accessing an unauthenticated browser, the following occurs: When accessing https://play.minio.io:9000/xiaomaiyun/favicon.ico, normal access; when visiting https://play.minio.io: 9000/xiaomaiyun/xiaomaigou_favicon.ico, 500 Internal Server Error, and when visiting https://play.minio.io:9000/xiaomaiyun/xiaomaigoulogo.png, login is required, why? Why not all require login?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@xiaomaiyun Thanks for reporting this issue. Will take a look at what is going on.

**Comment by donatello** [comment]
@xiaomaiyun I can reproduce this locally - thanks for the bug report. I will get back on this as I debug this further.

**Comment by donatello** [comment]
The linked pull request fixes this issue. After this fix is released, the browser will prompt for login for all cases.

**Comment by xiaomaiyun** [comment]
> The linked pull request fixes this issue. After this fix is released, the browser will prompt for login for all cases.

OK,Thank you!
