### ISSUE TITLE
mc policy parser truncate line when s3:delimiter option is used

### ISSUE THREAD

**Issue by marcadella** [minio/minio#7078]
## Expected Behavior
When you add a policy via `mc policy add X Y file.json`, and then print it with `mc policy list X Y`, the output should be equal to the original policy file. 

## Current Behavior
When uploading a policy containing s3:delimiter option the line is truncated.
Example json file:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowGroupToSeeBucketListInTheConsole",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::*"
      ]
    },
    {
      "Sid": "AllowRootAndHomeListingOfCompanyBucket",
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::my-company"
      ],
      "Condition": {
        "StringEquals": {
          "s3:prefix": [
            "",
            "home/"
          ],
          "s3:delimiter": [
            "/"
          ]
        }
      }
    }
  ]
}
```

yields:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowGroupToSeeBucketListInTheConsole",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListAllMyBuckets"
      ],
      "Resource": [
        "arn:aws:s3:::*"
      ]
    },
    {
      "Sid": "AllowRootAndHomeListingOfCompanyBucket",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::my-company"
      ],
      "Condition": {
        "StringEquals": {
          "s3:delimiter": [
            "/"
          ]
        }
      }
    }
  ]
}
```

Notice how the condition of statement 2 has been truncated.
Note: If you remove the first statement is also truncated but this time it looks like: `"Condition":{"StringEquals":{"s3:prefix":["","home/"]}}`...

## Your Environment
VERSION
2018-12-27T18:33:08Z
MEMORY
Used: 13 MB | Allocated: 82 GB | Used-Heap: 13 MB | Allocated-Heap: 154 MB
PLATFORM
Host: ea250a18f3c9 | OS: linux | Arch: amd64
RUNTIME
Version: go1.10.7 | CPUs: 4

**Comment by kannappanr** [comment]
@marcadella Thanks for the steps to reproduce the issue. We will try to reproduce the issue and get back to you.
