### ISSUE TITLE
Minio Internal Blobstore for PCF (No SSL) - Improvement Request

### ISSUE THREAD

**Issue by jessedye** [minio/minio#7087]
Feature Request:
Currently on Minio Internal Blobstore for PCF v 1.0.3 there is no way to configure an SSL certificate via the tile. Adding this functionality to the tile would greatly benefit users from manually having to configure a SSL certificate and improve security of the tile. Can a feature for security tab be added to the PCF "Minio Internal Blobstore for PCF" to support SSL? This would allow you to add private and public PEM keys for SSL.

**Comment by harshavardhana** [comment]
Closing this as stale @krishnasrinivas please reply if this issue needs to be kept open or if its fixed.
