### ISSUE TITLE
Minio Internal Blobstore for PCF - Static IP Address for Load Balancer

### ISSUE THREAD

**Issue by jessedye** [minio/minio#7088]
Feature Request:
Currently the Minio Internal Blobstore for PCF tile does not have a way to assign a static IP address to the Minio load balancer. Currently you can add IPs for the Minio nodes but not the load balancer. This makes it a problem when you redeploy and the load balancer IP address may change. It would be better to be able to assign a static ip address to the load balancer.

![image](https://user-images.githubusercontent.com/17808103/51209927-7159e080-18df-11e9-9f77-deb5532e7bbb.png)

**Comment by kannappanr** [comment]
@jessedye We will take a look at this and get back to you.

**Comment by harshavardhana** [comment]
@krishnasrinivas are you planning to fix it?

**Comment by harshavardhana** [comment]
> @krishnasrinivas are you planning to fix it?

Closing this as stale @krishnasrinivas please reply if this issue needs to be kept open or if its fixed.
