### ISSUE TITLE
[FEATURE-REQUEST] Pluggable KMS

### ISSUE THREAD

**Issue by alonbl** [minio/minio#7093]
Hi,

The vault KMS support is hardcoded into the project, it was at first in k8s as well up to the 3rd implementation they were asked to merge, and then created a plugin for KMS[1].

The k8s API is very limited as no context is provided, we need at least the bucket name to be available to the provider, maybe a patch to k8s can be sent to add a key/value context and once merged the same providers may be used by both projects.

Thanks,

[1] https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/

**Comment by kannappanr** [comment]
cc @aead We will see if there are standard ways to access KMS APIs.

**Comment by aead** [comment]
If I understand your FR correctly , you're asking whether we can:
1. Open an issue / send a PR to k8s for adding a key-value pair context argument to k8s's KMS plugin API.
2. Add an implementation of Minio's `crypto.KMS` interface that can talk to any gRPC service providing the same / a compatible API as k8s's KMS plugin.

The rationale behind this is unifying the "external" KMS API and allowing users to use other KMS implementations.  So the connections would be:  
 `Minio + KMS-plugin-config` <----> `KMS-plugin + KMS-config` <----->  `KMS`

Am I inferring this correctly from your FR @alonbl ?

**Comment by alonbl** [comment]
Hi aead,

The cooperation with k8s teams is optional of course, doing so will benefit the community as the k8s is popular and reusing its components makes sense.

The end goal is to provide plugin interface to KMS, your sequence is correct.

Two docker images may share the same tmpfs volume that has a unix domain socketto perform gRPC.

Thanks!

**Comment by harshavardhana** [comment]
We have started supporting https://github.com/minio/kes which is a common endpoint for all other third party KMS tools. 

Feel free to send a PR there to ensure support for your KMS requirements. Closing this issue as sufficiently addressed.

**Comment by alonbl** [comment]
Thank you!!!
