### ISSUE TITLE
SSE-S3 encryption not reported to (most?) S3 clients

### ISSUE THREAD

**Issue by zefie** [minio/minio#7094]
See repro section for setup. When uploading a file to Minio with SSE-S3 encryption, the file is encrypted, but other clients (such as Cyberduck and S3 Browser) are not made aware the file is encrypted, and when downloading said file, you get the raw encrypted gibberish. So far only rclone seems compatible, tested in specific "Minio" mode (Minio option when setting up S3 compatible)

## Expected Behavior

Minio server to tell client file is SSE-S3 encrypted, or decrypt before sending.

## Current Behavior

Minio server sends client encrypted gibberish data

## Possible Solution

Implement proper headers so that clients know file is encrypted.

## Steps to Reproduce (for bugs)

1. Set up minio server with temporarly MINIO_SSE_MASTER_KEY
2. Leave MINIO_SSE_AUTO_ENCRYPTION off
3. Use rclone to upload a file to Minio with --s3-server-side-encryption AES256
4. verify file was encrypted with mc stat
5. attempt to download file in any other client (my tests: Cloudberry Explorer, Cyberduck, S3 Browser)

Note: "encryption" option in info dialog is greyed out on Cyberduck, even with "SSE-S3 (AES256)" enabled in the options. Tested with Cyebrduck v6.8.3

## Alternative Steps to Reproduce (for bugs)
1. Set up minio server with temporarly MINIO_SSE_MASTER_KEY
2. Leave MINIO_SSE_AUTO_ENCRYPTION off
3. Try to upload file with SSE-S3 encryption with most S3 clients (other than rclone and mc)

## Context

Cannot secure data on remote rented servers if data will be unusable in most clients

## Your Environment

* Version used (`minio version`): 63d2583e91dbb392811bef2bbce82e1ecf367f22
* Environment name and version (e.g. nginx 1.9.1): minio direct (via iptables redirect external 443 -> internal secret port .. irrelevant)
* Operating System and version (`uname -a`):  Linux storage 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
SSE means server encryt and decrypt - I cant reproduce this. Don't see any gibberish data. 

Is there more details about your setup?

**Comment by kannappanr** [comment]
@zefie, If you are able to download an object that was encrypted on the server side using `SSE-S3` and uploaded using `mc`, that would mean that the whole setup is working properly. The only thing that I can think of is that, you are probably doing `Client` side encryption using other tools and then trying to download.

Can you do `mc stat` on say an object uploaded using `mc` and `cyberduck` (where you see the problem) and paste it here?

**Comment by zefie** [comment]
Alright, I have determined that the "gibberish data" issue was in fact on my end, and have resolved it.

However, a segue to probably another ticket would be my "alternative steps to reproduce", fact is even with the master key, the server does not report SSE-S3 support to the client, it acts transparent. From what I understand of S3 and the options in the client, Minio should be telling clients such as S3 Browser and Cyberduck that they can encrypt, but instead S3 Browser fails (something about signature) and Cyberduck's encryption options are greyed out (their docs says something about kms:ListKeys)

right now the only ways I know to make Minio encrypt data is either rclone, mc client, or force all encrypt.

**Comment by harshavardhana** [comment]
> However, a segue to probably another ticket would be my "alternative steps to reproduce", fact is even with the master key, the server does not report SSE-S3 support to the client, it acts transparent. From what I understand of S3 and the options in the client, Minio should be telling clients such as S3 Browser and Cyberduck that they can encrypt, but instead S3 Browser fails (something about signature) and Cyberduck's encryption options are greyed out (their docs says something about kms:ListKeys)

No,  there is no such thing in the API to tell clients that you can encrypt. Cyberduck themselves perhaps are not implementing this feature for non-S3 endpoints (guessing). 

if rclone, s3cmd, aws cli and `mc` can do it. Cyberduck can do it too. There is nothing to indicate a client that we support encryption just set the header with "x-amz-server-side-encryption: AES256" - server will encrypt it transparently.  

Interesting part is you can even use `curl` so this means that Cyberduck is not implementing this correctly.

**Comment by zefie** [comment]
Do you know of a Windows GUI client that properly supports Minio, and will let me encrypt only files I choose, as intended by S3? Cyberduck is not the only one with errors. I have also been trying S3 Browser and Cloudberry Explorer. Not opposed to paying (after a trial) for a client that can properly work with Minio.

**Comment by harshavardhana** [comment]
> Do you know of a Windows GUI client that properly supports Minio, and will let me encrypt only files I choose, as intended by S3? Cyberduck is not the only one with errors. I have also been trying S3 Browser and Cloudberry Explorer. Not opposed to paying (after a trial) for a client that can properly work with Minio.

I don't know @zefie unfortunately  - I don't know why they don't implement it properly either. This is the simplest form of encryption implemented and supported by S3 API.

**Comment by zefie** [comment]
Please do not take offense to this, but I find it hard to believe that 3 different clients that work with the S3 service as intended are at fault when it comes to communicating with an emulator (basically). I love this project, but can we really blame the clients, when it is Minio that is trying to meet the spec?

**Comment by harshavardhana** [comment]
> Please do not take offense to this, but I find it hard to believe that 3 different clients that work with the S3 service as intended are at fault when it comes to communicating with an emulator (basically). I love this project, but can we really blame the clients, when it is Minio that is trying to be the spec?

Minio is following AWS S3 spec its the clients which don't implement it correctly let me elaborate why. The reasoning is simple if popular tools such as `rclone`, `s3cmd`, `mc` even `aws` official CLI, AWS SDKs work fine. The only assumption we can make is they don't support what we support. 

There are three known server encryption styles in AWS S3

- SSE-C
- SSE-S3
- SSE-KMS

Minio implements the first two but not `SSE-KMS`. `SSE-KMS` requires AWS KMS service and it is tied to AWS KMS implementation. You may need to ask the upstream authors on what they support, do they even support custom S3 endpoints with encryption features.

- Now S3 browser might have some other compatibility issue with Minio, they may never support custom S3 endpoints. There are some assumptions clients make when talking to AWS, for example, sticking to Virtual DNS style by default. So Minio is not at fault here it is just that S3 browser was never meant to be used with services anything other than AWS S3.  In our experience, we have seen many such client implementations which make such assumptions. 

- Cyberduck might rely on KMS feature which we don't implement. 

- CBB might be implementing it also based on KMS which we don't implement. 

So I would simply suggest talk to upstream authors and see what they implement - ask them if they even support custom endpoints with SSE-S3 encryption. If they don't you know why it is not working. If they do we can jointly figure out what might be going wrong.

If you don't have a hard requirement on using GUI then you can use tools such as `rclone` which provide more richer functionality.

**Comment by zefie** [comment]
Thank you for the detailed explanation. I can understand why the clients don't work as expected now. I will close this. :)
