### ISSUE TITLE
Unable to create policy condition for root folder

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio#7095]
When creating a policy with StringEquals "" it doesn't seem to match for the root of a bucket.
The policy I'm using for example:
``` json
{
  "Version": "2012-10-17",
  "Statement": [
    {
     "Sid": "",
     "Action": [
       "s3:*"
     ],
     "Effect": "Allow",
     "Resource": [
       "arn:aws:s3:::bucket",
       "arn:aws:s3:::bucket/*"
     ],
     "Condition": {
		"StringEquals": {
			"s3:prefix": [
				"",
				"/",
				"data",
				"data/"
			]
		}
	 }
    }
  ]
}
```

## Expected Behavior
User with that policy can access / and /data/ but nothing else.

## Current Behavior
User can access /data/ directly but isn't able to access /
```mc ls minio/bucket/data/``` is successful
```mc ls minio/bucket/``` results in:
```
mc: <ERROR> Unable to stat `minio/bucket/`. Access Denied.
```
Minio Browser is empty. (Doesn't show any bucket)

## Possible Solution
Make "s3:prefix": "" match the root folder

It might also be related that if I use
```
     "Action": [
       "s3:ListBucket",
       "s3:GetObject"
     ],
```
instead of s3:*, then I get a:
```
mc: <ERROR> Cannot add new policy. Policy has invalid resource.
```

## Steps to Reproduce (for bugs)

1. Use above policy on a user (replace bucket and folder)
2. Create the folder.
3. mc ls minio/bucket/data/ (Is successful)
4. mc ls minio/bucket/ (fails)

## Context
I need the user to see what folders are available.

## Regression
No (I think)

## Your Environment

* Version used (`minio version`): 2019-01-10T00:21:20Z
* Environment name and version (e.g. nginx 1.9.1): docker
* Server type and version: Docker under Ubuntu Linux for Server / Windows with mc client

**Comment by harshavardhana** [comment]
PR https://github.com/minio/minio/pull/7079 might fix this issue.

**Comment by kannappanr** [comment]
@WolfspiritM Can you please try out PR #7079 as suggested above?

**Comment by WolfspiritM** [comment]
@harshavardhana @kannappanr I gave it a "go". It seems to not be fixed with that PR.
Also it seems to not be possible to add a host with the userdata if the root isn't available that's why I had to give the user readwrite before switching the policy back to testpolicy

Here is what I tried (policy.json is copied just as a testfile...):

```
> mc config host add minio http://192.168.178.123:9000 HX4OBAN38VW39BYB5KS5 ydmDD0AqRPTfqV0ZbAmsgMJl6+G2gfFkb9wKcuyc
> mc admin info minio
?  127.0.0.1:9000
   Uptime : online since 10 minutes ago
  Version : DEVELOPMENT.GOGET
   Region :
 SQS ARNs : <none>
    Stats : Incoming 23KiB, Outgoing 28KiB
  Storage : Used 6.1KiB

> mc mb minio/bucket
> mc cp policy.json minio/bucket/data/policy.json
> mc admin policy add minio testpolicy policy.json
> mc admin user add minio test test123! testpolicy

> mc config host add miniotest http://192.168.178.123:9000 test test123!
mc: <ERROR> Unable to initialize new config from the provided credentials. Access Denied.

> mc admin user policy minio test readwrite
Set a policy `readwrite` for user `test` successfully.

> mc config host add miniotest http://192.168.178.123:9000 test test123!
Added `miniotest` successfully.

> mc admin user policy minio test testpolicy
Set a policy `testpolicy` for user `test` successfully.

> mc ls miniotest/bucket/
mc: <ERROR> Unable to stat `miniotest/bucket/`. Access Denied.

> mc ls miniotest/bucket/data/
[2019-01-16 20:23:34 CET]   367B policy.json
```

**Comment by harshavardhana** [comment]
Thanks for testing will fix it @WolfspiritM

**Comment by harshavardhana** [comment]
@WolfspiritM so I tested this behavior with AWS S3 IAM and we are in compliance. The reason is that List operation directly on a bucket doesn't translate prefix == "" and there is is a no concept of root folder name "/" since this is a flat namespace there is no "/" like filesystem hierarchy.

Are you trying to allow a user to be able to list the top level folders? but not access them? AFAICS that style is not supported in AWS or Minio.

**Comment by WolfspiritM** [comment]
@harshavardhana If you take a look at:
https://docs.aws.amazon.com/AmazonS3/latest/dev/example-policies-s3.html

There is a sample policy called "AllowRootLevelListingOfTheBucket":
```
{
      "Sid": "AllowRootLevelListingOfTheBucket",
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::examplebucket"],
      "Condition":{ 
            "StringEquals":{
                    "s3:prefix":[""], "s3:delimiter":["/"]
                           }
                 }
    }
```

I don't have S3 to test it but according to that rule s3 does support that or am I missing something?

The "/" was a test by me to see if maybe minio is handling it differently.
The correct one should be the empty one.

Yes I'm trying to prevent the user from accessing the folders except for "data".

EDIT:
Also here is a sample that does exactly what I need:
https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/

```
   {
     "Sid": "AllowRootAndHomeListingOfCompanyBucket",
     "Action": ["s3:ListBucket"],
     "Effect": "Allow",
     "Resource": ["arn:aws:s3:::my-company"],
     "Condition":{"StringEquals":{"s3:prefix":["","home/", "home/David"],"s3:delimiter":["/"]}}
    }
```

**Comment by harshavardhana** [comment]
yep, this works as expected @WolfspiritM  AWS IAM policy returns

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowRootAndHomeListingOfCompanyBucket",
            "Action": [
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::sjm-airlines-1"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "",
                        "data/",
                        "data"
                    ],
                    "s3:delimiter": [
                        "/"
                    ]
                }
            }
        }
    ]
}
```

With AWS S3
```
~  mc ls testuser/sjm-airlines-1/
mc: <ERROR> Unable to stat `testuser/sjm-airlines-1/`. Access Denied.
```
```
~ mc ls testuser/sjm-airlines-1/data/
[2019-01-16 21:31:45 PST]   224B hosts
```

Using this with Minio has same behavior @WolfspiritM .

Now I started looking at the query params a little deeper, looks like when a top-level bucket is provided `mc` doesn't send prefix="" (empty) value. This actually causes AWS S3 to not honor the policy.

So after modifying `mc` query params set `prefix=""` listing completes properly. 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowRootAndHomeListingOfCompanyBucket",
            "Action": [
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::sjm-airlines-1"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "",
                        "data/",
                        "data"
                    ],
                    "s3:delimiter": [
                        "/"
                    ]
                }
            }
        },
        {
            "Sid": "AllowAllActions",
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::sjm-airlines-1/data/*"
            ]
        },
        {
            "Sid": "AllowAllBucketActionsRead",
            "Action": [
                "s3:GetBucketLocation"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::sjm-airlines-1"
            ]
        }
    ]
}
```

Here is the final policy which works properly but requires some fixes in `mc` to pass the appropriate values.

This works with both Minio and AWS IAM. Looks like only fix needed is in `mc`.

**Comment by harshavardhana** [comment]
Feel free to track the client issue at minio/mc#2647 @WolfspiritM

**Comment by WolfspiritM** [comment]
@harshavardhana Thanks! However I think the browser also needs a fix for that.
**Web.ListBuckets** does not return the bucket at all cause the Prefix check fails.
I would consider a bucket to be "Listable" if the root is able to be listed.
Therefor I suggest to set the header before checking the policy like that:
```go
func (web *webAPIHandlers) ListBuckets(r *http.Request, args *WebGenericArgs, reply *ListBucketsRep) error {
	.....
	r.Header.Set("prefix", "")
```


**Web.ListObjects** also does not set the Prefix even if the frontend does set it to ""
This results in root objects not being visible.
Therefor I suggest a change to remove the if clause around all appearances of:
``` go
		if args.Prefix != "" {
			r.Header.Set("prefix", args.Prefix)
		}
```

I think the same should be done for delimiter aswell

**Comment by harshavardhana** [comment]
Thanks @WolfspiritM - good suggestions. Sending a PR for minio server as well.
