### ISSUE TITLE
Backblaze aws-sdk-ruby mint test fails

### ISSUE THREAD

**Issue by jefvel** [minio/minio#7103]
## Expected Behavior
The `aws-sdk-ruby` Mint test should pass without errors when using the `b2` gateway.

## Current Behavior
The test will fail when running `presignedPut(bucket_name,file_name)`.
This is the Mint test error:
```
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-4ac2e664ca4a",
    "file_name": "datafile-1-MB"
  },
  "duration": 5427.67,
  "error": "Expected to be created object does NOT exist",
  "status": "FAIL"
}
```

Here's the error log from Minio:
```
API: PutObject(bucket=aws-sdk-ruby-bucket-4ac2e664ca4a, object=datafile-1-MB)
Time: 12:44:56 CET 01/17/2019
RequestID: 157AA0231D2872E3
RemoteHost: ::1
UserAgent: Ruby
Error: b2_upload_file: 408: request_timeout: Error reading uploaded data: EOFException(Length to read: 61691 actual: 163)
       1: cmd/gateway/b2/gateway-b2.go:558:b2.(*b2Objects).PutObject()
       2: cmd/object-handlers.go:1159:cmd.ObjectLayer.PutObject-fm()
       3: cmd/object-handlers.go:1280:cmd.objectAPIHandlers.PutObjectHandler()
       4: cmd/api-router.go:77:cmd.objectAPIHandlers.PutObjectHandler-fm()
       5: net/http/server.go:1964:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)

1. Run Minio with the backblaze backend: `minio gateway b2`
2. Run The mint test against Minio

## Context
I'm trying to get the mint tests to pass for Backblaze

## Regression
I am not sure

## Your Environment

* Version used (`minio version`): DEVELOPMENT.GOGET
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version:
* Operating System and version (`uname -a`): Linux archlinux 4.19.10-arch1-1-ARCH #1 SMP PREEMPT Tue Dec 18 00:04:08 UTC 2018 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
We are most probably going to revamp our Gateway implementations @jefvel and perhaps remove B2, Sia, and Manta implementations. They are not actively maintained and perhaps have bugs. 

Thank you for opening an issue though. We will close this once we have finalized on removing B2 implementation.

**Comment by kannappanr** [comment]
Closing this issue based on the previous comment.
