### ISSUE TITLE
Bitrot Detection/Healing Fails when using Highwayhash256 after recent changes

### ISSUE THREAD

**Issue by keirafadams** [minio/minio#7121]
If I set the default bitrot detection algorithm to highwayhash256 (the legacy, not the current 256S), I receive "unexpected EOF" errors when running healing, including on the hidden .config buckets.

Version: 74c2048ea9ad0982123623d5e0a184f42490762b

## Expected Behavior
Expected behavior is with a support bitrot detection algorithm, the mc admin heal command should run to completion, and there should be no errors reported on any servers.

## Current Behavior

Instead, when I run mc admin heal --recursive myminio/buck using highwayhash256 as the default algorithm, I receive sometimes on the client (e.g. insufficient space for rebuild) and, and consistently on the target.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Set the default bitrot algorithm on each server to HighwayHash256 (not HighwayHash256S), can be hard coded in cmd/bitrot.go
2.   Start a cluster of 2 servers, each with 2 disks
3.  Upload some data
4. Run mc admin heal on the bucket where data was uploaded

```
ifadams@anchor:~/minio_d1/buck/5MB$ mc admin heal --recursive myminio
 ◓  buck/5MB
    0/1 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │  75.0% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  25.0% ███          │
    └────────┴───┴─────────────────────┘

Server Side Log:
API: Heal(bucket=buck, object=5MB)
Time: 14:14:42 PST 01/18/2019
RemoteHost: 192.168.1.160
Error: unexpected EOF
       1: cmd/xl-v1-healing-common.go:188:cmd.disksWithAllParts()
       2: cmd/xl-v1-healing.go:278:cmd.healObject()
       3: cmd/xl-v1-healing.go:671:cmd.xlObjects.HealObject()
       4: cmd/xl-sets.go:1259:cmd.(*xlSets).HealObject()
       5: cmd/admin-heal-ops.go:778:cmd.(*healSequence).healObject()
       6: cmd/admin-heal-ops.go:750:cmd.(*healSequence).healBucket.func1()
       7: pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()

<occurs 3 more times>
```
And here is an example xl.json

```
{"version":"1.0.1","format":"xl","stat":{"size":5242880,"modTime":"2019-01-18T21:55:21.32338001Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":3,"distribution":[3,4,1,2],"checksum":[{"name":"part.1","algorithm":"highwayhash256","hash":"a46aaa059334c0e00dc82c6d9ab995daa2d1bac1a987fd7b8db26758d874875e"}]},"minio":{"release":"DEVELOPMENT.GOGET"},"meta":{"content-type":"application/octet-stream","etag":"0d2d1bff0e7921709424c6920b3c605a"},"parts":[{"number":1,"name":"part.1","etag":"","size":5242880,"actualSize":5242880}]}i
```

## Context
Impacting R&D that uses Minio as a target system

## Your Environment

DEVELOPMENT.GOGET
Ubuntu 16.04

**Comment by krishnasrinivas** [comment]
Thanks for reporting @ifadams we will send in the fix soon.
