### ISSUE TITLE
minio gateway s3 /  maps accesskey / secretkey

### ISSUE THREAD

**Issue by limbo127** [minio/minio#7130]
We want to use minio gateway s3 service without configuring aws cred.
We have a lot of user, each with own access/secretKey  and we want to knonw how pass this cred directly, without need or minio gateway cred.

Example : 
user1 : acceskey1/ secret1
user2 : acceskey2  / secret2

with minio client for example  
 "play1": {
                        "url": "http://xx.x.x.x:9000",
                        "accessKey": "accesskey1",
                        "secretKey": "secretkey1",
                        "api": "S3v4",
                        "lookup": "auto"
                },
 "play2": {
                        "url": "http://xx.x.x.x:9000",
                        "accessKey": "accesskey2",
                        "secretKey": "secretkey2",
                        "api": "S3v4",
                        "lookup": "auto"
                },

x.x.x.x:9000  a minio gateway s3   , accesskey1|2  are known at s3 endpoind iam
Regards, 
Nicolas Prochazka

**Comment by harshavardhana** [comment]
You don't need to @limbo127 - are you trying to use S3 gateway against AWS S3 ?

**Comment by limbo127** [comment]
Yes against AWS S3 ?
is there any tricks ?
regards, 
Nicolas

**Comment by harshavardhana** [comment]
Yes you may refer to these docs https://github.com/minio/minio/blob/master/docs/gateway/s3.md

**Comment by limbo127** [comment]
sorry but i do not understand,

export MINIO_ACCESS_KEY=aws_s3_access_key
export MINIO_SECRET_KEY=aws_s3_secret_key

in all cases MINIO_ACCESS_KEY must me export, how acceskey1 and accesskey2
can be uses for two différent users ?




Le mar. 22 janv. 2019 à 12:04, Harshavardhana <notifications@github.com> a
écrit :

**Comment by harshavardhana** [comment]
> sorry but i do not understand, export MINIO_ACCESS_KEY=aws_s3_access_key export MINIO_SECRET_KEY=aws_s3_secret_key in all cases MINIO_ACCESS_KEY must me export, how acceskey1 and accesskey2 can be uses for two différent users ?

You have to run one gateway per user @limbo127 - are you saying you want to use multi-user with Minio gateway?

**Comment by limbo127** [comment]
Ok, Yes we think about multi-user with Minio gateway, where minio gateway
user are just mapping of real aws credential, in fact cred are passe
directly to aws s3
regards,


Le mar. 22 janv. 2019 à 14:15, Harshavardhana <notifications@github.com> a
écrit :

**Comment by harshavardhana** [comment]
> Ok, Yes we think about multi-user with Minio gateway, where minio gateway user are just mapping of real aws credential, in fact cred are passe directly to aws s3 regards,

then you need to start multiple minio gateways one per user @limbo127

**Comment by limbo127** [comment]
ok, thank for the explanation
regards, 
Nicolas

**Comment by kannappanr** [comment]
@limbo127 Closing this issue as answered. Please feel free to reach out to us if you have more questions.
