### ISSUE TITLE
Can't login in fresh install

### ISSUE THREAD

**Issue by entekhabgroup** [minio/minio#7137]
## Expected behavior
login in fresh install

## Actual behavior
not login at all

## Steps to reproduce the behavior
install from [here](https://linuxhint.com/install_minio_ubuntu_1804/) and all steps done.
service activated.
open http://localhost:9000
enter access & secret key
show an error: **The access key ID you provided does not exist in our records**

## mc version
Release-tag: RELEASE.2019-01-10T00-38-22Z
Commit-id: 0854af6e6d3e9f79e8d9c98db5e0d133a527923b

## System information
Ubuntu 18.4 Bionic server

**Comment by nitisht** [comment]
@entekhabgroup have you tried `mc` as explained in the https://linuxhint.com/install_minio_ubuntu_1804/ document? Does that work?

Also, please refer our official documentation https://docs.minio.io/ - because unofficial docs may be outdated and can cause confusion

**Comment by nitisht** [comment]
@entekhabgroup were you able to try `mc` ?

**Comment by deekoder** [comment]
I just tried it and I am able to login. @entekhabgroup  can you check if you got access/secret key right?

**Comment by kannappanr** [comment]
@entekhabgroup Closing this issue as answered. Please feel to reopen if you are still seeing this issue.
