### ISSUE TITLE
Policy doesn't support DNS style bucket addressing

### ISSUE THREAD

**Issue by siamackSeifi** [minio/minio#7138]
In the following issue, DNS style bucket addressing was discussed.
https://github.com/minio/minio/issues/4681

Now minio supports DNS style bucket addressing, but when I create a new user with canned policy (https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html) I get access denied when addressing bucket DNS style from minio. but the path style is ok.

**Comment by harshavardhana** [comment]
Any reproducible steps that you can help us with ?

**Comment by siamackSeifi** [comment]
I used "export MINIO_DOMAIN=domaintest.dev" to add such domain to minio.
Then I added a new user: "mc admin user add myminio newuser newuser123 mypolicy" using the following canned policy:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject",
        "s3:ListBucket"
      ],
      "Resource": ["arn:aws:s3:::mybucket/*"],
      "Sid": ""
    }
  ]
}

now in order to access {mybucket} I create a get request on 
"mybucket.domaintest.dev" and I get access denied!
but when sending a get request to server using "domaintest.dev/mybucket" as url everything is fine.

I hope these where the information you needed.

**Comment by harshavardhana** [comment]
Thanks this should help.

**Comment by harshavardhana** [comment]
I was able to test this from what it looks like your policy is wrong @siamackSeifi here is what I tested. 

My envs before starting minio
```
~ env | grep MINIO
MINIO_SECRET_KEY=minio123
MINIO_ACCESS_KEY=minio
MINIO_DOMAIN=localhost
```

```
~ mc config host add foobar http://localhost:9000 foobar foo12345 --lookup dns --api s3v4
```

```
~ mc admin user list myminio 
enabled    foobar                testpolicy          
```

```
~ mc admin policy list myminio testpolicy | jq .
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowRootAndHomeListingOfCompanyBucket",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::sjm-airlines"
      ],
      "Condition": {
        "StringEquals": {
          "s3:delimiter": [
            "/"
          ],
          "s3:prefix": [
            "data",
            "data/",
            ""
          ]
        }
      }
    },
    {
      "Sid": "AllowAllActions",
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::sjm-airlines/data/*"
      ]
    },
    {
      "Sid": "AllowAllBucketActionsRead",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation"
      ],
      "Resource": [
        "arn:aws:s3:::sjm-airlines"
      ]
    }
  ]
}
```

```
~ mc ls foobar/
mc: <ERROR> Unable to list folder. Access Denied.
```
```
~ mc ls foobar/sjm-airlines/
[2018-12-12 17:06:20 PST]   224B hosts
[2019-01-17 07:23:18 PST]    79B nested.json
[2019-01-11 19:08:42 PST]    38B people.csv
[2019-01-11 19:08:42 PST]    86B people.json
[2019-01-11 19:08:42 PST]   556B people.parquet
[2019-01-11 01:55:37 PST] 1.5KiB testdata.parquet
[2019-01-11 01:58:13 PST] 111KiB userdata1.parquet
[2019-01-23 22:37:21 PST]     0B data/
[2019-01-23 22:37:21 PST]     0B data1/
```

From debug output you can see `mc` is using DNS style for bucket addressing
```
mc: <DEBUG> GET /?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: sjm-airlines.localhost:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.14 mc/2019-01-24T05:47:32Z
Authorization: AWS4-HMAC-SHA256 Credential=foobar/20190124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190124T063746Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 24 Jan 2019 06:37:46 GMT
Server: Minio/RELEASE.2019-01-23T23-18-58Z
Vary: Origin
X-Amz-Request-Id: 157CB570900D1F19
X-Minio-Deployment-Id: 7564a643-0505-4c84-87fc-5095d5389967
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  5.975794ms
...
...
```

**Comment by harshavardhana** [comment]
Also tested the policy you posted which seems to be correct policy and is working as expected with DNS addressing too 

```
~ mc admin policy add myminio testp /tmp/1.json
```

```
~ mc mb myminio/mybucket/
Bucket created successfully `myminio/mybucket/`.
```

```
~  mc admin user add myminio test test12345 testp
Added user `test` successfully.
```

```
~ mc config host add test http://localhost:9000 test test12345 --api s3v4 --lookup dns
Added `test` successfully.
```
```
~ mc ls test/
mc: <ERROR> Unable to list folder. Access Denied.
```
```
~ mc ls test/mybucket/
```
```
~ mc ls --debug test/mybucket
...
...
mc: <DEBUG> GET /?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: mybucket.localhost:9000
```

**Comment by harshavardhana** [comment]
May be you need update your Minio server to latest and test again @siamackSeifi .

**Comment by siamackSeifi** [comment]
I took your advice and updated my minio and mc to latest version @harshavardhana , but still i cant reach my bucket through dns style addressing.
I created a test user and a test2. Their difference is (--lookup dns) which test2 has but test doesnt have it.
So its as follows:

```
mc config host add test http://localhost:9000 test test12345 --api s3v4

$ mc ls test/mybucket/
[2019-01-26 18:24:58 +0330]  18KiB xml.xml



mc config host add test2 http://localhost:9000 test test12345 --api s3v4 --lookup dns

$ mc ls test2/mybucket/
mc: <ERROR> Unable to stat `test2/ttt/`. 405 Method Not Allowed.
```

**Comment by harshavardhana** [comment]
From 405 method not allowed, it means that server is not configured for DNS style addressing.

How did you setup DNS style addressing?

**Comment by siamackSeifi** [comment]
I started server with `./minio server --address "localhost:9000" /data`
I don't know if theres other setting up to do

**Comment by harshavardhana** [comment]
> I started server with `./minio server --address "localhost:9000" /data`
> I don't know if theres other setting up to do

Yeah if you started in that manner and you are using a DNS name which is not localhost? what are values for your Minio ENVs such as `MINIO_DOMAIN`?

**Comment by siamackSeifi** [comment]
It worked!
I set my `minio_domain` to localhost and now it works. But Im sure I did it before.
maybe I didn't do them all after updating my minio.
thanks for the help.

**Comment by harshavardhana** [comment]
Thanks feel free to close this issue @siamackSeifi

**Comment by kannappanr** [comment]
@siamackSeifi Closing this issue as answered. Please feel free to reach out to us if you have more questions.
