### ISSUE TITLE
minio gateway b2 not found after update minio 2019-01-23T23:18:58Z

### ISSUE THREAD

**Issue by mnajamudinridha** [minio/minio#7140]
hi, my minio gateway b2 not work on my server, 
‘b2’ is not a minio sub-command. See ‘minio --help’.

**Comment by kannappanr** [comment]
@najcardboyz We have removed support for b2. PTAL at the release notes
https://github.com/minio/minio/releases/tag/RELEASE.2019-01-23T23-18-58Z

**Comment by harshavardhana** [comment]
We have officially removed support for b2 gateway @najcardboyz -  https://dl.minio.io/server/minio/release/linux-amd64/archive/ use one of the older releases.

**Comment by mnajamudinridha** [comment]
ok, thank you for the information, I think, I have to downgrade my minio version

**Comment by kannappanr** [comment]
@najcardboyz Thanks for reaching out to us. Closing this issue now as won't fix.

**Comment by manigandham** [comment]
What exactly is the maintenance requirement for the gateway code? The B2 API is stable and has been working well, is it blocking some other development to keep it?

**Comment by harshavardhana** [comment]
> What exactly is the maintenance requirement for the gateway code? The B2 API is stable and has been working well, is it blocking some other development to keep it?

It is quite simple our test suites do not complete on this gateway, it was not close to where we wanted our gateway implementations better examples as s3, gcs, azure, Alibaba OSS. 

Also, we lack the bandwidth to maintain myriad of gateway implementations in our codebase to meet our quality requirements. The community is free to fork and maintain its own version as needed. You can use older Minio releases to get the same functionality, we haven't made any bugfixes on B2 implementation for over a year so any release in the past would work.
