### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by rHermes** [minio/minio#7141]
It seems that there is a parser error in the select part of the code. I try to run select over it, but it doesn't work. It also seems to be tied to number of entries, as it will go from returning all successfully to returning none successfully.

The file in question when you see bug.json is [https://gist.github.com/rHermes/007dddb88d5ad23f7c4365eb66adff22](url)

## Expected Behavior
```
$ for i in $(seq 10 10 100); do head -$i bug.json | mc pipe m1/test/bug-$i.json ; done
$ for i in $(seq 10 10 100); do  mc sql --query 'SELECT * FROM S3Object' m1/test/bug-$i.json | wc -l ; done
10
20
30
40
50
60
70
80
90
100
```

## Current Behavior

```
$ for i in $(seq 10 10 100); do head -$i bug.json | mc pipe m1/test/bug-$i.json ; done
$ for i in $(seq 10 10 100); do  mc sql --query 'SELECT * FROM S3Object' m1/test/bug-$i.json | wc -l ; done
10
20
30
40
50
60
70
mc: <ERROR> Unable to run sql Error Type of  Encountered an error parsing the JSON file. Check the file and try again.
28
mc: <ERROR> Unable to run sql Error Type of  Encountered an error parsing the JSON file. Check the file and try again.
32
mc: <ERROR> Unable to run sql Error Type of  Encountered an error parsing the JSON file. Check the file and try again.
35
```
## Possible Solution

I do not know where in the code this occurs, I've only just started using minio.

## Steps to Reproduce (for bugs)

1. `wget -O bug.json https://gist.githubusercontent.com/rHermes/007dddb88d5ad23f7c4365eb66adff22/raw/121b9362e2bde0beeee9cf9d063e705aef45c283/bug.json`
2. `mc mb m1/test`

## Context

I'm trying to use the Select API that minio provides.

## Regression

I don't know if it is.

## Your Environment

* Version used (`minio version`): Version : 2019-01-16T21:44:08Z
* Environment name and version (e.g. nginx 1.9.1): traefik setup with docker compose and 6 minio nodes
* Server type and version: Version : 2019-01-16T21:44:08Z
* Operating System and version (`uname -a`): `Linux mellow 4.19.11-arch1-1-ARCH #1 SMP PREEMPT Thu Dec 20 03:40:28 UTC 2018 x86_64 GNU/Linux`

**Comment by nitisht** [comment]
Thanks, we'll take a look @rHermes
