### ISSUE TITLE
Minio config cannot parse IPv6 address for PostgreSQL

### ISSUE THREAD

**Issue by Karimerto** [minio/minio#7145]
As the title says, minio config cannot handle IPv6 addresses in the config file. I was following the instructions on [Minio Bucket Notification Guide](https://docs.minio.io/docs/minio-bucket-notification-guide.html) for enabling events in PostgreSQL.

I extracted the current config with `mc admin config get`, modified the relevant section for `postgresql` and tried to upload it but it was not accepted. If I set the `host` key as a pure IPv6 address (e.g. `fd12:3456:7890::1234`), the error is:

    mc: <ERROR> Cannot set server configuration file. scheme appears with empty host

And if I set it similar to how http handles it (e.g. `[fd12:3456:7890::1234]`), the error is:

    mc: <ERROR> Cannot set server configuration file. parse [fd12:3456:7890::1234]: first path segment in URL cannot contain colon

## Expected Behavior
I expected a pure IPv6 address to work as-is.

## Current Behavior
Neither IPv6 format is parsed correctly.

## Possible Solution
The error is somewhere in the URL parsing library. It should be improved to correctly handle IPv6 addresses in all situations. I think it does work fine for a regular http address, such as http://[fd12:3456::78]:9000/ but not for a lone IPv6 address. Or it should not even be parsed as a URL in the first place, since it can only be either a hostname, or an IP address, be that v4 or v6.

## Steps to Reproduce (for bugs)

1. Extract config with `mc admin config get somekey > myconfig.json`
2. Modify `postgresql` config and set host to an IPv6 address
3. Try uploading new config with `mc admin config set somekey < myconfig.json`
4. Fail!

## Context
As it it, I cannot use IPv6 addresses for host definition.

## Your Environment

* Version used (`minio version`):

    Version: 2019-01-23T23:18:58Z
    Release-Tag: RELEASE.2019-01-23T23-18-58Z
    Commit-ID: bd25f31100f44646cffae99dfec23179366593e2

* Operating System and version (`uname -a`):

    Linux my-host-name 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Network: is entirely IPv6 only

**Comment by kannappanr** [comment]
@Karimerto Thanks for filing this issue. We will take a look at this and try to fix it soon.

**Comment by Karimerto** [comment]
Good to know that this has been fixed, thank you!
