### ISSUE TITLE
Heal operation is too slow

### ISSUE THREAD

**Issue by nullne** [minio/minio#7150]
## Expected Behavior

Heal operation should be faster than the writing rate  at leat, or it will never be finished.

## Current Behavior
Heal operation is very slow on the minio cluster. i have set up an 6 node cluster. each is equipted with 12 6T disks. I stopped all requests to the cluster and strarted to heal the whole cluster recursively(with flag `-r`).

guess what, about 10k objects are healed in rough 24 hours! There will be billions of objects on the prodution. we won't make sure the data correctness with such slow speed. 

## Possible Solution

i have not idea, i am not diving into the  code and find out why it's slow

## Your Environment

* Version used (`minio version`):2018-12-27T18:33:08Z
* Environment name and version (e.g. nginx 1.9.1): no nginx
* Operating System and version (`uname -a`): 3.10.0-327.el7.x86_64

**Comment by krishnasrinivas** [comment]
@nullimne 

we will be implementing `--scan=[normal/deep]` `normal` being the faster version which does not do bitrot check (which takes a long time)

**Comment by nullne** [comment]
is there any progress on this issue?

**Comment by harshavardhana** [comment]
Yes there two PRs already to address this should be merged soon.

**Comment by jaceksan** [comment]
any progress?

**Comment by vadmeste** [comment]
> any progress?

Fixed by https://github.com/minio/minio/pull/7251
