### ISSUE TITLE
ubuntu+docker+nginx+gateway:azure + form.io 405 method not allowed

### ISSUE THREAD

**Issue by miguelguadarrama** [minio/minio#7151]
I'm using a service called Form.IO to create a form. One of their components is file upload and they support S3/minio server for file storage. I followed their guides to set up the environment from here:
https://help.form.io/tutorials/deployment/azure/

And how to set up minio here:
https://help.form.io/integrations/filestorage/#minio

So this is what I did:
1. Create Azure VM + ubuntu
2. Install docker
3. Create 2 containers, 1 for minio and one for the formio server
`docker run -itd \
 -e "MINIO_ACCESS_KEY=myblob" \
 -e "MINIO_SECRET_KEY=MY_SECRET_KEY" \
 -e "MINIO_HTTP_TRACE=/dev/stdout" \
 --network formio \
 --name formio-minio \
 --restart unless-stopped \
 -p 9000:9000 \
 minio/minio gateway azure;`
4. Configure nginx for proxy / to http://localhost:9000
5. Attach my subdomain to this VM
6. All is working as expected, even SSL. https://minio.mydomain.org successfully shows the minio browser. I can even upload files from here to azure.

However, on file uploads I receive a 405 Method not allowed error.

## Expected Behavior
HTTP 200 success, and file is uploaded 

## Current Behavior
HTTP 405 Method not allowed

## Steps to Reproduce (for bugs)
File upload from form.io to my minio server.
From chrome dev tools I can see the request is sent to:
POST https://minio.mydomain.com/

## Context
Can't upload any file

## Regression
Not sure, but I've seen others have this issue before, according to google.

## Your Environment

* Version used: tried both LATEST and EDGE
* Environment name and version: ubuntu 18.04 nginx

**Comment by miguelguadarrama** [comment]
UPDATE:
I got it working. It seems that you can't make requests to "/", at least for azure. You must add the bucket name to make the URL endpoint:

https://minio.mydomain.org/bucketname/

By doing this, I was able to upload files to Azure from form.io upload file component.

**Comment by nitisht** [comment]
feel free to close the issue   @miguelguadarrama
