### ISSUE TITLE
anonymous http https post produces 403 error

### ISSUE THREAD

**Issue by stopher2** [minio/minio#7153]
## Expected Behavior
http/https POST should store the object and return a 200

RECOMMENDATION: Add documentation to describe  generic http post client signature to a bucket having a "none" policy 
## Current Behavior

works fine with mc, a browser,  but a singular line java http post client with a simple URI does not authenticate to an anonymous bucket.  

desire to use a java object which posts a URL to an old s3 compatible store....so i won't have to change that client code.

it appears currently that only "anonymous" and "share" use-case capabilities "should" do this.

i'd like to use anonymous since it is a persistent capability, but using java http post produces a 403 HTTP ERROR in minio logs.

generally, to achieve this i'd like to post an object to minio using java http post. this could be done without keys or with keys in header.  

my plan is to authenticate with the proxy using keys, so anonymous connection will remain somewhat secure to the dedicated buckets of the app.

is there a sample http/https post header example that does not implement the temporary capability that "share access" does and allows header inclusion of access key and security key ?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by stopher2** [comment]
version:   2018-09-12T18:49:56Z

**Comment by stopher2** [comment]
RECOMMENDATION:  either change "none" authentication algorithm or add an "anonymous" security state which the server will validate keys in clear in httpPOST.

**Comment by krishnasrinivas** [comment]
@stopher2 I am finding it hard to understand the issue here.

> i'd like to use anonymous since it is a persistent capability, but using java http post produces a 403 HTTP ERROR in minio logs.

Can you post your java code here?

What are you trying to do? Are you trying to upload an object?

**Comment by stopher2** [comment]
yes.  but i get a 403 error when attempting a simple http POST without
authentication.

i've set the server to allow anonymous "blank" but it still fails.  perhaps
it's my uri or header....which shouldn't be checking for authentication.

using nifi client postHTTP.   have tried s3PUT as well, but same problem.

**Comment by stopher2** [comment]
i'd like to do it  in java, but this client uses 
curl -X POST http://xyz.com:80  
to minio and minio complains 403 authentication.    i recognize it needs secret/access codes; but can't i add them as a header ?  How would i do this and the hashing of the access code for that curl ?

**Comment by stopher2** [comment]
ideally would like have to POST to minio with access, secret in URL....a good alternative is to has the secret and put that into the curl POST.

**Comment by stopher2** [comment]
ideally would like have to POST to minio with access, secret in URL....a good alternative is to hash the secret and put that into the curl POST header.

**Comment by kannappanr** [comment]
@stopher2 Please take a look at http://usefulangle.com/post/34/aws-s3-upload-api-php-curl for more information and http://www.tothenew.com/blog/file-upload-on-amazon-s3-server-using-curl-request/  . Please feel free to reach out to us at https://slack.min.io for further questions. Closing this issue now.
