### ISSUE TITLE
Can not add new policy

### ISSUE THREAD

**Issue by vermaden** [minio/minio#7163]
Hi,

I am following this guide:
https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html

What I need:
**Add new policy with read/write access to only one bucket and using only one user for that role.**

These are the instructions I have done:

```
# minio-client config host list
testDEV:  http://10.20.30.100:9000        asd                   asd                                       s3v4   auto
gcs    :  https://storage.googleapis.com  YOUR-ACCESS-KEY-HERE  YOUR-SECRET-KEY-HERE                      S3v2   dns
local  :  http://localhost:9000                                                                                  auto
play   :  https://play.minio.io:9000      Q3AM3UQ867SPQQA43P2F  zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG  S3v4   auto
s3     :  https://s3.amazonaws.com        YOUR-ACCESS-KEY-HERE  YOUR-SECRET-KEY-HERE                      S3v4   dns
 
# minio-client admin policy add testDEV testpolicy testpolicy.json
minio-client: <ERROR> Cannot add new policy. Policy has invalid resource.
 
# cat testpolicy.json
{
  "Version": "2019-01-28",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:*"],
      "Resource": ["arn:aws:s3:::testbucket/*"]
    }
  ]
}
# 

```

For the record, the **testbucket** already exists and 'works'.

Doing the example in point 2. of the guide works:

```

# cat > getonly.json << EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::my-bucketname/*"
      ],
      "Sid": ""
    }
  ]
}
EOF

# minio-client admin policy add myminio getonly getonly.json

```

I use 2019.01.16 Minio on FreeBSD 11.2-RELEASE-p8 system.

Regards.

**Comment by nitisht** [comment]
@vermaden the resource field 

```
"Version": "2019-01-28"
``` 

is incorrect, please refer https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html

Can you set it to 

```
"Version": "2012-10-17"
```

and try again?

**Comment by kannappanr** [comment]
@vermaden Please let us know if the suggestion worked.

**Comment by vermaden** [comment]
I was able to test it just now. yes that works.

Thank you very much for fast and accurate help.

I thought that 'Version' applies to contents of the JSON config file like Serial field in DNS to know that contents changed.

Regards,
vermaden
