### ISSUE TITLE
policy works via cli but not via web interface

### ISSUE THREAD

**Issue by flixr** [minio/minio#7165]
I'm having some trouble with the recently introduced variable support for policies: it works for the cli (`mc`) but not the web interface... are there special actions I have to allow for web access?

My policy for allowing each "user" access  to their own bucket:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid":"AllowGroupToSeeBucketListInTheConsole",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListAllMyBuckets"
      ],
      "Resource": [
        "arn:aws:s3:::*"
      ]
    },
    {
      "Sid":"AllowListingInBucket",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}/*"
      ]
    },
    {
      "Sid":"AllowReadWriteInBucket",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
```

## Expected Behavior
Policy should work the same for cli access as for web interface.

## Current Behavior

While it works in the cli, in the minio web interface I get : `Do not have enough permissions to access this resource`
I can even upload a file in the web interface (checked with cli, it's actually there), but just can't see anything.

Looking at the web requests/responses:

looking at the requests:

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "Web.ListObjects",
    "params": {
        "bucketName": "foobar",
        "marker": "",
        "prefix": ""
    }
}
```

I get

```
{
    "error": {
        "code": -32000,
        "data": null,
        "message": "Do not have enough permissions to access this resource"
    },
    "id": 1,
    "jsonrpc": "2.0"
}
```

## Steps to Reproduce (for bugs)

1. add policy as described above
2. add user with this new policy
3. upload/list objects via `mc` -> works
4. open minio web interface -> access denied

## Context
Trying to give each user read/write access to their own bucket (bucket name == user name).

## Regression
Looks like it might be a regression...

## Your Environment
* Version used (`minio version`): minio/minio:RELEASE.2019-01-23T23-18-58Z
* Environment name and version (e.g. nginx 1.9.1): proxied with traefik
* Operating System and version (`uname -a`): Linux x86_64 using official docker image

**Comment by nitisht** [comment]
thanks for reporting @flixr we'll take a look

**Comment by flixr** [comment]
Thanks a lot for the quick response and fix guys!
