### ISSUE TITLE
Link to a Media Glasses article is broken in the Community blogs section

### ISSUE THREAD

**Issue by doz10us** [minio/minio#7166]
[Playing with Docker 1.13 & Minio](https://media-glass.es/playing-with-docker-1-13-minio-9b38a36e88b)

## Expected Behavior
An article should open after a click to [Playing with Docker 1.13 & Minio](https://media-glass.es/playing-with-docker-1-13-minio-9b38a36e88b)

## Current Behavior
The link leads to a 404 page.

## Possible Solution
Adjust the link to point to a (new?) [direct URL](https://mediaglasses.blog/2017/01/21/playing-with-docker-1-13-minio/).

## Steps to Reproduce (for bugs)
1. Visit the https://minio.io
2. Scroll down to the footer
3. Click on the 'Playing with Docker 1.13 & Minio' under the Community blogs section
4. 404

## Context
I tried to get a basic overview of Minios' possibilities.

## Regression
Don't know

## Your Environment
Not relevant

**Comment by nitisht** [comment]
Thanks for reporting @doz10us we'll remove the link

**Comment by kannappanr** [comment]
The new link appears to be https://mediaglasses.blog/2017/01/21/playing-with-docker-1-13-minio/

**Comment by kannappanr** [comment]
@doz10us the link has been fixed.
