### ISSUE TITLE
Setting up mirroring with an S3 compatible object store

### ISSUE THREAD

**Issue by wowselim** [minio/minio#7167]
On the minio website, [the features page](https://www.minio.io/features.html) says the following:

> In addition, you may configure Minio server to continuously mirror data between Minio and any Amazon S3 compatible server.

I looked into the documentation but couldn't find any further information about this. I would like my Minio instance to be in sync with my DigitalOcean Spaces instance, which is also S3 compatible.

Am I missing something or is there no information regarding this available?

**Comment by sgandon** [comment]
I believe you can do that with the minio client using the mirror command
`mc mirror`

**Comment by nitisht** [comment]
@wowselim here is the documentation on `mc mirror` https://docs.minio.io/docs/minio-client-complete-guide.html#mirror

Closing this issue as answered, feel free to join us on Slack (https://slack.minio.io) for more such questions

**Comment by YanzheL** [comment]
> @wowselim here is the documentation on `mc mirror` https://docs.minio.io/docs/minio-client-complete-guide.html#mirror
> 
> Closing this issue as answered, feel free to join us on Slack (https://slack.minio.io) for more such questions

This is client-side mirror, but what we need is server-side mirror.

The `mc mirror SRC DST` command will download files from `SRC` and then send it to `TARGET`, which is not efficient and slow.

We need a method to configure continuous mirroring on minio server, so files are sent directly from server.

**Comment by harshavardhana** [comment]
@YanzheL we would really appreciate if old issues are left alone and not discussed. Please open newer issues to have fresh discussions.
