### ISSUE TITLE
high cpu usage 

### ISSUE THREAD

**Issue by adelmonora** [minio/minio#7180]
## Current Behavior

My server is unresponsive because minio process use  all the cpu 

## Steps to Reproduce (for bugs)

](url)
1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

My minio version is 2018-11-06T01:01:02Z
My server is Linux Ubuntu  4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

![minio-cpu](https://user-images.githubusercontent.com/42206209/52053483-bcb7f400-2559-11e9-9eb6-0b0e2f3d50d6.jpg)

**Comment by nitisht** [comment]
this is a fairly old release @adelmonora , we have made many fixes to improve CPU utilisation. can you try with latest release

**Comment by adelmonora** [comment]
Hi Nitisht,  i update minio to the last version, but it appear the issue is the same.

**Comment by kannappanr** [comment]
@adelmonora We have a PR (https://github.com/minio/mc/pull/2657) in mc that will help us get more info on issues like this. Hopefully this will be merged in a day or two. You could either build `mc` by checking out this PR or wait for the release.

**Comment by harshavardhana** [comment]
@adelmonora would you mind collecting profile output for us you can use `mc admin profile` command to do that.

**Comment by harshavardhana** [comment]
> @adelmonora would you mind collecting profile output for us you can use `mc admin profile` command to do that.

checking back @adelmonora to see if you were able to capture the `mc admin` profile output?

**Comment by nitisht** [comment]
Closing this due to no response @adelmonora , feel free to reopen when you have the requested info

**Comment by ahmadalli** [comment]
I'm having the same issue with distributed minio
After using `mc mirror` I'm seeing high cpu usage on 2 of my 3 servers. I didn't restart minio service from last night and now they have load average of `340` and htop shows way more minio processes on the 2 servers with 340 load.

**Comment by harshavardhana** [comment]
Please open a new issue @ahmadalli 

How are you running MinIO server - have you provided MinIO entire disk or just a sub-path inside a mount point ?

**Comment by ahmadalli** [comment]
@harshavardhana I've created new issue: https://github.com/minio/minio/issues/8049
