### ISSUE TITLE
Unable to get the metadata for an object for browser based application

### ISSUE THREAD

**Issue by ranjeetkowel** [minio/minio#7181]
When using the `getObject` API from a browser based application using the `aws-sdk-js` the `metadata` field returned is empty. However using the same API from a non-browser based application, returns the appropriate metadata.

## Expected Behavior

The `getObject` API should have the same behavior across various `aws-sdk`s.

## Current Behavior

The SDK does not return the `metadata` for a browser based application.
## Possible Solution

On looking through the code and the behavior, we observed the following:
1. The CORS ExposedHeaders only returns a certain fixed set of headers, and does not acknowledge any metadata headers.
2. Even though the API returns the headers in the `x-amz-meta-*` headers, this header is not exposed, preventing the SDK to catch it.
3. If custom `exposedHeaders` can be set for a bucket this can be resolved.
## Steps to Reproduce (for bugs)

1. Upload an object to minio using the `putObject` API
2. Retrieve the object through a browser UI application using `getObject` API

## Context

We obfuscate the file name of the object stored on minio, and keep that in the metadata. A user with only the valid permissions can download the file, and on downlaod the file name should be the original file name.
## Regression

No
## Your Environment

* Version used (`minio version`): RELEASE.2019-01-10T00-21-20Z
* Environment name and version (e.g. nginx 1.9.1): kubernetes
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@ranjeetkowel Thanks for the issue and the possible solution. That is how we will try to resolve this issue. Will try to send a fix soon.
