### ISSUE TITLE
GCS gateway + ETCD = Doesn't list existing buckets

### ISSUE THREAD

**Issue by markmarijnissen** [minio/minio#7191]
## Expected Behavior
`mc ls myminio` should return a list of all buckets in GCS.

## Current Behavior

GCS gateway with etcd
1. `mc ls myminio` shows no existing buckets (0)
2. `mc mb myminio test`
3. `mc ls myminio` shows only test bucket (1)

GCS gateway without etcd
1. `my ls myminio` shows all existing buckets (3)

Some further facts:
1. I have confirmed my GCS credentials are correct.
2. etcd is up and running. I can add and retrieve users using `mc`
3. Logs of minio docker image:

```
API: SYSTEM()
Time: 19:25:29 UTC 02/04/2019
Error: No entries found for this key
       1: cmd/web-handlers.go:1904:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1765:cmd.toJSONError()
       3: cmd/web-handlers.go:300:cmd.(*webAPIHandlers).ListBuckets()
```

Hypothesis:
1. When minio is (re)started, it does not sync the existing bucket list from GCS with ETCD.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. Start minio gateway gcs with an ETCD_ENDPOINT env variable defined.
2. List buckets.

## Context

Setup minio.

## Regression

Don't know if this worked before.

## Your Environment

* Version used: RELEASE.2019-01-10T00-21-20Z
* Environment name and version: using helm chart minio-2.3.6   .
* Server type and version: GKE (Google Kubernetes Engine)
* Operating System and version: Linux
* Link to your project: private

**Comment by kannappanr** [comment]
@markmarijnissen Thanks for reporting this issue. We will try to reproduce this error and see what is going on.

**Comment by markmarijnissen** [comment]
Thanks. Let me know if I can help by giving more info.

**Comment by markmarijnissen** [comment]
Solved!

1. I set the "MINIO_DOMAIN" ENV variable.
2. In **cmd/common-main.go:297**, there is both `globalDomainName` and `globalEtcdClient`, which enables the `globalDnsConfig` (https://github.com/minio/minio/blob/master/cmd/common-main.go#L297)
3. in **cmd/web-handlers.go:297**, bucket retrieval happens using the DNS instead of the normal command.  (https://github.com/minio/minio/blob/master/cmd/web-handlers.go#L297)

The reason for this misconfiguration is because I assumed "MINIO_DOMAIN" was required for to enable the browser. The values are listed together in the Helm chart (https://github.com/helm/charts/blob/master/stable/minio/values.yaml#L217)
