### ISSUE TITLE
Support partial listing of buckets

### ISSUE THREAD

**Issue by Vynce** [minio/minio#7194]
Could a user policy restrict the `ListAllMyBuckets` API to only return certain buckets?

## Expected Behavior
For example, I'd like this policy to only allow a user to see their own bucket:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "BucketList",
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}"
      ]
    },
    {
      "Sid": "BucketOperations",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}"
      ]
    },
    {
      "Sid": "ObjectOperations",
      "Effect": "Allow",
      "Action": [
         "s3:AbortMultipartUpload",
         "s3:ListMultipartUploadParts",
         "s3:DeleteObject",
         "s3:GetObject",
         "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
```

## Current Behavior
Currently, I either need to block listing buckets or allow users to list all of them:
```
  "Statement": [
    {
      "Sid": "BucketList",
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation"
      ],
      "Resource": [
        "arn:aws:s3:::*"
      ]
    },
```

## Possible Solution
Make it possible to specify a list of resources that the `ListAllMyBuckets` API can return.

## Context
[Arq](https://www.arqbackup.com/) uses the `ListAllMyBuckets` API to return the list of buckets that it can back up to. I would like to limit that list to the individual user's bucket that they actually have access to.

**Comment by kannappanr** [comment]
@Vynce Not sure if S3 spec allows this. Please take a look at https://stackoverflow.com/questions/6615168/is-there-an-s3-policy-for-limiting-access-to-only-see-access-one-bucket/18089783#18089783

**Comment by harshavardhana** [comment]
S3 spec doesn't allow partial listing. If S3 doesn't allow it we don't either. Closing this issue as out of scope.

**Comment by Vynce** [comment]
@kannappanr, that's unfortunate, but thanks for the useful link!
