### ISSUE TITLE
Scaling, performance and behavior inside a docker container

### ISSUE THREAD

**Issue by MarcinAman** [minio/minio#7195]
Hi,
i have a few questions about minio:

## Question
(Questions are related to distributed minio, I am especially interested the one in docker containers)
1) In documentation I have read how locking works, but how minio propagates changes / uploads? I assume that every node holds a data or parity block of a single file, but what if i upload a new file or update the old one? How does the cluster behave?

2) Which strategy do you advise:
- a lot of buckets with one or two small files each
- limited amount of buckets but with a lot of files

I've read that for the [Amazon version](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) it doesn't really matter too much but how does Minio behave in those scenarios? Does any of those yield a significant performance benefit?

3) Am I allowed to dynamically scale my cluster? I am thinking about a situation where one node goes down and i want to dynamically add a replacing container. 
While reading your Kubernetes files I came to conclusion that you simply kill the whole cluster and replace it with a new one.

## Your Environment

* Version used (`minio version`): docker image: minio/minio:RELEASE.2019-01-31T00-31-19Z
* Environment name and version (e.g. nginx 1.9.1): Docker version 18.06.1-ce, build e68fc7a
* Operating System and version (`uname -a`): Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MarcinAman** [comment]
Also you are writting in the [docs](https://github.com/minio/minio/blob/master/docs/sts/README.md) that using KeyCloak i am able to get an admin-like credentials, but how about the limited ones (for users)?

**Comment by kannappanr** [comment]
@MarcinAman 
```
1. In documentation I have read how locking works, but how minio propagates changes / uploads? I assume that every node holds a data or parity block of a single file, but what if i upload a new file or update the old one? How does the cluster behave?
```
As far as S3 is concerned, there is no concept of updating the old one, it is always a variation of PUT object call. If you want to upload a new file to update an existing object on minio, the old data on all the nodes get overwritten. 

``` 
2. Which strategy do you advise:

* a lot of buckets with one or two small files each
* limited amount of buckets but with a lot of files 
```
We would advise having a limited amount of buckets. You can have lots of files with shared prefixes.

```
3. Am I allowed to dynamically scale my cluster? I am thinking about a situation where one node goes down and i want to dynamically add a replacing container.
   While reading your Kubernetes files I came to conclusion that you simply kill the whole cluster and replace it with a new one.
```

You cannot dynamically scale your cluster. If one node goes down, you can replace the node, you do not have to kill the whole cluster.

**Comment by nitisht** [comment]
closing as answered @MarcinAman . Do join us on slack (https://slack.minio.io) for more questions like this.
