### ISSUE TITLE
Provide public access to the server

### ISSUE THREAD

**Issue by mitya-multiplayer** [minio/minio#7196]
How do I start Minio service in public mode? 

## Expected Behavior
Is that possible to disable credentials somehow? 

## Current Behavior
In `config.json` I tried to set `credential.status` to `disabled`, I tried to set empty values to access and secret keys but nothing work. 

## Context
I run minio in a private cloud which already has all required authorization and I don't need an extra layer of authorization for Minio, so I would like to disable it alltogether.

**Comment by nitisht** [comment]
This is not possible at server level @yateam . You can do this at bucket level using policies https://docs.minio.io/docs/minio-client-complete-guide.html#policy

**Comment by nitisht** [comment]
closing as answered @yateam  . Do join us on slack (https://slack.minio.io) for more questions like this.

**Comment by yateam** [comment]
@nitisht Does that work for Minio running over filesystem storage? It seems like that works only for s3. Is that true?
