### ISSUE TITLE
Nexus & Minio Status Code: 501; Error Code: NotImplemented

### ISSUE THREAD

**Issue by schmitch** [minio/minio#7200]
Hello, I'm trying to use minio as a backend for Nexus,  however I always get the following exception in nexus:

```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: A header you provided implies functionality that is not implemented (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: /nexus/content/directpath/nexus-repository-docker/673312cf-226e-44ed-9904-43c4aa6acbea/0.bytes; S3 Extended Request ID: 3L137)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.setObjectTagging(AmazonS3Client.java:1546)
	at org.sonatype.nexus.blobstore.s3.internal.S3BlobStore.doDelete(S3BlobStore.java:375)
	... 150 common frames omitted
```

What's really curious is the minio HTTP TRACE it never returns a 501.

I actually use minio in NAS gateway mode.
I also have the http trace attached, as a txt file, here:

**Comment by harshavardhana** [comment]
> 	at com.amazonaws.services.s3.AmazonS3Client.setObjectTagging(AmazonS3Client.java:1546)

We don't support Object tagging https://docs.minio.io/docs/minio-server-limits-per-tenant.html @schmitch

**Comment by schmitch** [comment]
Oh ok. Thanks.

**Comment by lukasmrtvy** [comment]
@harshavardhana I tried latest minio `RELEASE.2020-03-25T07-03-04Z`, but I am getting same error as above.

ObjectTagging should be merged and relased tho:
https://github.com/minio/minio/pull/8754
https://github.com/minio/minio/pull/8971

**Comment by harshavardhana** [comment]
> @harshavardhana I tried latest minio `RELEASE.2020-03-25T07-03-04Z`, but I am getting same error as above.

Run `mc admin trace` and show us what the error you are getting.

**Comment by lukasmrtvy** [comment]
nvm, seems its not related to ObjectTagging
```
19:00:18.261 [200 OK] s3.GetBucketACL runners-cache:9000/nexus/?acl  172.18.0.5        7.25ms       ↑ 137 B ↓ 445 B
19:00:18.269 [200 OK] s3.GetBucketACL runners-cache:9000/nexus/?acl  172.18.0.5        6.181ms      ↑ 137 B ↓ 445 B
19:00:18.277 [200 OK] s3.GetBucketACL runners-cache:9000/nexus/?acl  172.18.0.5        6.793ms      ↑ 137 B ↓ 445 B
19:00:18.285 [200 OK] s3.GetBucketACL runners-cache:9000/nexus/?acl  172.18.0.5        6.52ms       ↑ 137 B ↓ 445 B
19:00:18.290 [501 Not Implemented] s3.GetBucketLifecycle runners-cache:9000/nexus/?lifecycle  172.18.0.5        3.635ms      ↑ 137 B ↓ 580 B
```

**Comment by harshavardhana** [comment]
> ```
> 19:00:18.290 [501 Not Implemented] s3.GetBucketLifecycle runners-cache:9000/nexus/?lifecycle  172.18.0.5        3.635ms      ↑ 137 B ↓ 580 B
> ```

That looks incorrect too @lukasmrtvy we already support lifecycle

**Comment by lukasmrtvy** [comment]
@harshavardhana  isnt renamed ? https://github.com/minio/minio/pull/8698

**Comment by harshavardhana** [comment]
> @harshavardhana isnt renamed ? #8698

No that has nothing to do with the handlers @lukasmrtvy we have functional tests running with AWS SDKs

```
~ aws --profile minio --endpoint-url http://localhost:9000 s3api put-bucket-lifecycle-configuration --bucket testbucket --lifecycle-configuration file:///tmp/lifecycle.json
```

```
~ aws --profile minio --endpoint-url http://localhost:9000 s3api get-bucket-lifecycle-configuration --bucket testbucket
{
    "Rules": [
        {
            "Filter": {
                "And": {}, 
                "Prefix": "logs/2014/", 
                "Tag": {}
            }, 
            "Status": "Enabled", 
            "Expiration": {
                "Date": "2020-01-01T00:00:00Z"
            }, 
            "ID": "Delete 2014 logs in 2016."
        }
    ]
}
```

**Comment by harshavardhana** [comment]
```
~ mc admin trace myminio
19:40:21.655 [200 OK] s3.GetBucketLifecycle localhost:9000/testbucket?lifecycle  127.0.0.1         684µs       ↑ 93 B ↓ 529 B
```

**Comment by ftong2020** [comment]
Well, actually this issue still exists in "nas gateway" mode.

I used to run nexus with minio in server mode(8 ssd, started with server /data{0...7}), everything works just fine.

Yesterday I moved data to a NAS to save some space(erasure coding options are quite limited in minio, and I don't need that much performance anyways), and ran minio in docker with "NAS Gateway" mode. After that, nexus won't be able to  connect to my s3-blobs backed by minio any more.

Initially I thought it is some issue with traefik which serves as a reverse proxy, but it turns out not. Now I just switch back to "server mode" and everything works just fine.

**Comment by harshavardhana** [comment]
> Well, actually this issue still exists in "nas gateway" mode.
> 
> I used to run nexus with minio in server mode(8 ssd, started with server /data{0...7}), everything works just fine.
> 
> Yesterday I moved data to a NAS to save some space(erasure coding options are quite limited in minio, and I don't need that much performance anyways), and ran minio in docker with "NAS Gateway" mode. After that, nexus won't be able to connect to my s3-blobs backed by minio any more.
> 
> Initially I thought it is some issue with traefik which serves as a reverse proxy, but it turns out not. Now I just switch back to "server mode" and everything works just fine.

NAS gateway mode won't support everything that you need from S3 API @ftong2020 - it is meant to support situations where legacy products are taking time to move out. 

If you are starting fresh use Erasure coding which MinIO intends to support all meaningful S3 APIs

**Comment by ftong2020** [comment]
> > Well, actually this issue still exists in "nas gateway" mode.
> > I used to run nexus with minio in server mode(8 ssd, started with server /data{0...7}), everything works just fine.
> > Yesterday I moved data to a NAS to save some space(erasure coding options are quite limited in minio, and I don't need that much performance anyways), and ran minio in docker with "NAS Gateway" mode. After that, nexus won't be able to connect to my s3-blobs backed by minio any more.
> > Initially I thought it is some issue with traefik which serves as a reverse proxy, but it turns out not. Now I just switch back to "server mode" and everything works just fine.
> 
> NAS gateway mode won't support everything that you need from S3 API @ftong2020 - it is meant to support situations where legacy products are taking time to move out.
> 
> If you are starting fresh use Erasure coding which MinIO intends to support all meaningful S3 APIs

Indeed, server mode works flawlessly
