### ISSUE TITLE
Complete Multipart fails with GCS backend for large files (~10GB) -- the number of source components provided (64) exceeds the maximum (32), invalid

### ISSUE THREAD

**Issue by challarao** [minio/minio#7201]
I'm trying to upload a file of 10GB with multipart upload to a minio backed by GCS gateway and seeing this error in MINIO_HTTP_TRACE:

> The number of source components provided (64) exceeds the maximum (32), invalid

I'm not sure if I need to infer this as number of total parts. But for 10GB, numparts is 10GB/5MB = 2048. So, it's not that.

## Expected Behavior
Upload Should be completed successfully.

## Current Behavior
1. #CompleteMultipartUpload call fails with an error giving a google api related error:

`Error: googleapi: Error 400: The number of source components provided (64) exceeds the maximum (32), invalid
       1: cmd/gateway/gcs/gateway-gcs.go:1324:gcs.(*gcsGateway).CompleteMultipartUpload()
       2: cmd/object-handlers.go:2286:cmd.ObjectLayer.CompleteMultipartUpload-fm()
       3: cmd/object-handlers.go:2291:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       4: cmd/api-router.go:63:cmd.objectAPIHandlers.CompleteMultipartUploadHandler-fm()
       5: pkg/handlers/http-tracer.go:144:handlers.TraceReqHandlerFunc.func1()
       6: net/http/server.go:1964:http.HandlerFunc.ServeHTTP()
2019-02-06 10:41:54.076114 I | http: multiple response.WriteHeader calls`

2. To client, it's sending a misleading description of error:
    It says "InvalidBucket", where as the error is #1
3. I increased each part to 350 MB or 60 MB, then the upload succeeds. But the 350 MB is too large to be a part size.

  File Size   Part Size     Concurrency            Result
- 10 GB         5 MB            30                       Failure
- 10 GB         60 MB          30                       Success
- 10 GB         350 MB        4                         Success       

## Possible Solution
Not sure. If there are limitations with regards to component size etc with gcs gateway, it should be transparent to user?

## Steps to Reproduce (for bugs)
1. Use minio/minio:edge backed by GCS bucket
2. Use aws-sdk-go library
3. The default part size in aws-sdk-go library is 5 MB by default
4. Use 10GB file for upload.

## Context
It's preventing us from using multipart with GCS backend.
We are dealing with files 20GB-300 GB.

## Your Environment

* minio:edge (2019-02-06)
* Linux

**Comment by nitisht** [comment]
we’ll take a look @challarao

**Comment by challarao** [comment]
Any update on this?

**Comment by ghost** [comment]
I think it is not a surprise that it fails with 5 MB chunk size.
Like here https://github.com/minio/minio/issues/7206 .
As the network latency increases and maybe also CPU load, it may fail there (socket getting closed on inactivity from remote - here GCS).
So maybe it is also a duplicate of it.

**Comment by harshavardhana** [comment]
This is not related to #7206 @gustopn

**Comment by challarao** [comment]
Any updates on this?

**Comment by harshavardhana** [comment]
@challarao few questions 

- what is the issue in setting higher part size? 
- what is the issue with just using single Put() - MinIO supports up to 5TiB in the single-stream upload? 
- Per part of up-to 5TiB is supported by MinIO, unlike AWS S3 which limits itself to 5GiB?

The reason we would like to avoid fixing this on our end because of the limitations of GCS, it may over complicate our gateway implementation which is simple and avoids overworking the limitations of GCS.

Technically It doesn't look like we may want to fix this issue @challarao

**Comment by harshavardhana** [comment]
Closing this issue as we haven't heard back anything new on this issue - the technical issue https://github.com/minio/minio/issues/7201#issuecomment-515795108 here explains why we don't need to address this and clients can change their behavior appropriately.

**Comment by jlebrijo** [comment]
I am having the same error:
* 5 MB chunks: googleapi: Error 400: The number of source components provided (37) exceeds the maximum (32), invalid
* 100 MB chunks: googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid

Total file is 6 GB so first case we have 1200 chunks, and second 60 chuncks. So there is no relation with this 36-37. Seems like with the last chunks minion tries to merge without taking care of Google Storage limitation of 32.
