### ISSUE TITLE
Pre-signed urls are generated with virtual domains locally

### ISSUE THREAD

**Issue by alexgurr** [minio/minio#7209]
When running Minio locally and using S3's sign urls call, Minio returns invalid URLs in the format:

https://BUCKET.localhost:9000/KEY?AWSAccessKeyId=accesskey&Expires=1549605699&Signature=%2FVkKRmgQMMu40WrkOsaDyx1Fp%2B8%3D

You can't have sub domains/virtual hosts on localhost and by default Minio is running on http. 

The docs say the default is paths: 

```
By default, Minio supports path-style requests that are of the format http://mydomain.com/bucket/object. MINIO_DOMAIN environment variable is used to enable virtual-host-style requests.
```

## Expected Behavior

Should generate valid urls.

## Possible Solution
Generate urls the original way with domain/bucket/key/....

## Steps to Reproduce (for bugs)
1. Start up Minio in docker with defaults (localhost:9000)
2. Create a bucket
3. Use the S3 sdk to generate a signed url

## Context
Trying to mock S3 locally so that I can get valid urls on my development environment.

## Your Environment
* Version used (`minio version`): @latest
* Environment name and version (e.g. nginx 1.9.1): Docker
* Server type and version: @latest
* Operating System and version (`uname -a`): macOS@latest

**Comment by nitisht** [comment]
@alexgurr do you have `MINIO_DOMAIN` or any other Minio specific env vars set before starting minio? Can you paste the output of `env` command?

Also, please provide a code snippet to help us reproduce the issue

**Comment by alexgurr** [comment]
I'm starting the server with:

```
docker run -p 9000:9000 --name minio \
  -e "MINIO_ACCESS_KEY=accesskey" \
  -e "MINIO_SECRET_KEY=secretkey" \
  -v /Users/alexgurr/Documents/work/minio/data:/data \
  -v /Users/alexgurr/Documents/work/minio/config:/root/.minio \
  minio/minio server /data 
```

No MINIO specific env vars set.

My code is extremely simple:

```
const AWS = require('aws-sdk');
const s3Endpoint = 'localhost:9000',
const s3Credentials: {
  accessKeyId: 'accesskey',
  secretAccessKey: 'secretKey'
}
const SYDNEY_REGION = 'ap-southeast-2';
const endpoint = new AWS.Endpoint(s3Endpoint);

AWS.config.update({ region: SYDNEY_REGION, ...s3Credentials });

const s3Client = new AWS.S3({ apiVersion: '2006-03-01', endpoint });

function getSignedUrl(action, clientId, key) {
  const params = { Bucket: SYDNEY, Key: key };

  return new Promise((resolve, reject) => {
    s3Client.getSignedUrl(action, params, (err, url) => {
      if (err) { return void reject(err); }

      resolve(url);
    });
  });
}
```

where bucket is one I've previously created through the web client and key is some string.

**Comment by harshavardhana** [comment]
You are missing following param in your constructor it's mentioned here https://docs.minio.io/docs/how-to-use-aws-sdk-for-javascript-with-minio-server.html

```
s3ForcePathStyle: true, // needed with minio?
```

**Comment by kannappanr** [comment]
@alexgurr closing this issue now. Please feel free to reopen the issue if the suggestion not work for you.

**Comment by alexgurr** [comment]
@kannappanr can you please reopen this?

@harshavardhana 

URLs are now being generated in the correct format, but still with **https**:// which isn't working with localhost. How can I turn off https signed urls?

According to this article (https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls) you have to enable TLS manually. So why are pre-signed URLs generated with https even when the server is running on http?

https://puu.sh/CKQVt/998778d506.png

When I change https to http I get progress but now get:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <Resource>/hubdatastore-shootsta-sydney-663842070690/foo/bar.jpg</Resource>
    <RequestId>15827961D4C0FA53</RequestId>
    <HostId>3L137</HostId>
</Error>
```
