### ISSUE TITLE
minio distributed file store mode

### ISSUE THREAD

**Issue by emadghav** [minio/minio#7221]
hi
in distributed mode i using 4 node ,when i upload a file ,Divided to 2 part and save 2 instance on 4 node for example part 1 on node 1 ,part 2 on node 2 ,part 1 on node 3 and part 2 on node 4 but i dont need to save 2 instance because i using raid.
can i change it ?
for example dont save 2 instance of a file ,just save 1 instance that divided 4 parts or save files in 1 node (file 1 on node 1 . . . . file 4 on node 4).
it is impossible?

**Comment by harshavardhana** [comment]
Yes it is impossible .. you can modify the code yourself to make static. Choice of part.1 to node1 or nodeN is automatic.
