### ISSUE TITLE
Share button icon is not intuitive

### ISSUE THREAD

**Issue by icholy** [minio/minio#7226]
## Expected Behavior
The share button's icon should communicate it's purpose.

## Current Behavior
The icon looks like a "copy" icon. 

## Possible Solution
Something like this https://fontawesome.com/icons/link?style=solid

## Context
The share functionality was hard to find (I ended up asking on slack). I assumed the share button duplicated the object.

## Your Environment
* Version used: RELEASE.2019-02-06T21-16-36Z

**Comment by kannappanr** [comment]
@icholy Thanks for filing this issue. We will take a look at it.

**Comment by deekoder** [comment]
Agreed @icholy. We can change it to https://fontawesome.com/icons/share-alt?style=solid.  I will discuss here and we will PR for it.

**Comment by icholy** [comment]
I just checked and google drive uses https://fontawesome.com/icons/user-plus?style=light

**Comment by minio-trusted** [comment]
we will address this @icholy
