### ISSUE TITLE
minio distributed

### ISSUE THREAD

**Issue by emadghav** [minio/minio#7228]
hi
i have 4 node that each node have 1 TB hard ,i run minio in distributed mode when i create a bucket and put object ,minio create 4 instance of file , i want save 2 TB data on minio although i have 4 TB hard i cant save them because minio save 4 instance of files.
how reduce this redundancy ? and just save 1 instance of files?

**Comment by kannappanr** [comment]
@emadghav Currently, there will be some amount of redundancy in the case of erasure coded setup. By default it is half. One thing you can do is to reduce the amount of redundancy.  Please take a look at https://github.com/minio/minio/tree/master/docs/erasure/storage-class for further information.

**Comment by emadghav** [comment]
ok
and how add new node to cluster ?

**Comment by nitisht** [comment]
> and how add new node to cluster ?

By design Minio clusters dont allow adding new nodes to existing cluster, to scale / add storage capacity simply create a new Minio cluster and if needed combine different clusters into a single namespace using Minio federation [https://docs.minio.io/docs/minio-federation-quickstart-guide.html]

**Comment by nitisht** [comment]
closing the issue as answered @emadghav . Feel free to join us on Slack for more such questions [https://slack.minio.io]
