### ISSUE TITLE
CORS : Access-Control-Max-Age is not set

### ISSUE THREAD

**Issue by olevitt** [minio/minio#7231]
Hi,  
I'm using minio and allow my users to upload files within a JS webapp.  
When I upload big files, it's sent in chunks using filename?partNumber=x&uploadId=x endpoint.  
The webapp is on a separate domain so it's using CORS.  
I'm wondering why minio is not replying with a Access-Control-Max-Age header.  
Is that intended ? Is there a reason not to ? It would avoid a lot of preflight requests.  
  
I checked the code and there are no max_age option set. The CORS lib minio is using appears to already support Access-Control-Max-Age so enabling it should not be to hard if wanted. From my limited knowledge on minio codebase, the option could be set in generic-handlers.go file but I'm not confident enough in go to make it a PR, sorry :(
  
Thx !

**Comment by nitisht** [comment]
Thanks for reporting @olevitt we'll take a look

**Comment by harshavardhana** [comment]
> I'm wondering why minio is not replying with a Access-Control-Max-Age header.

Access-Control-Max-Age is unlimited there is no requirement for MinIO to have this header.

**Comment by neben** [comment]
> > I'm wondering why minio is not replying with a Access-Control-Max-Age header.
> 
> Access-Control-Max-Age is unlimited there is no requirement for MinIO to have this header.

What do you mean by "unlimited"? If this header is not set, clients will not cache or only briefly cache preflight responses (e.g., [5 seconds for Chrome](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age)).

Also, for future reference, minio now *does* seem to set this header, to 1h:
```
access-control-max-age: 3600
```
