### ISSUE TITLE
ssl protocol error

### ISSUE THREAD

**Issue by petacube** [minio/minio#7237]
environment local laptop running macos latest version

steps
brew install minio

minio server /tmp/minio_data
Endpoint:  http://<ip>:9000  http://127.0.0.1:9000        
AccessKey: XXX
SecretKey: YYY

Browser Access:
   http://<ip>:9000  http://127.0.0.1:9000   

access via browser works, although complaints ssl cert is invalid. expected. 

python 3.6 anaconda version. 

pip install minio     
     
install no problem.

python                                                                                                    
from minio import Minio
client=Minio(‘<ip>:9000',access_key=“XXX",secret_key="YYY",secure=True)
client.list_buckets()

   397         if new_retry.is_exhausted():
--> 398             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    399 
    400         log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host=‘<ip>', port=9000): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)'),))

this shows on console

API: SYSTEM()
Time: 23:52:51 EST 02/12/2019
Error: malformed HTTP request from '<ip>:9000'
       remoteAddr=1<ip>:51140, localAddr=<ip>:9000
       1: /private/tmp/minio-20190204-8314-17eknct/src/github.com/minio/minio/cmd/http/listener.go:278:http.(*httpListener).start.func2()

what am i doing wrong??

**Comment by nitisht** [comment]
@petacube based on the steps you've provided looks like TLS is not configured at all. To configure TLS with Minio pls refer https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls.html

**Comment by kannappanr** [comment]
@petacube If you do not want `TLS`, then you can set `secure=False` in `minio-py`.

**Comment by petacube** [comment]
got it
thank you both

i had been following examples here https://docs.minio.io/docs/minio-quickstart-guide.html <https://docs.minio.io/docs/minio-quickstart-guide.html> and i did not link TLS config with secure=True in python api.

Secure=False works.
pls close the issue

**Comment by nitisht** [comment]
Thanks @petacube
