### ISSUE TITLE
CopyObject with metadata replace will override ContentType

### ISSUE THREAD

**Issue by diddiman-zz** [minio/minio#7238]
## Expected Behavior

When doing a CopyObject, like this:
```
aws s3api copy-object --copy-source "bucket/source" --key dst --bucket bucket --metadata meta-int=1 --metadata-directive REPLACE
```
the content-type from the source object should not be copied, instead it should mirror aws behavior and default to binary/octet-stream, as long as a new content-type is not passed

## Current Behavior
As it works now, minio will copy the content-type from the source object, and i would expect same behavior as going straight to amazon

## Possible Solution
Skip copying the content-type when copying an object. And also change the minio-py test so the test that fails either passes a new content-type or assumes that binary/octet-stream will be used

## Steps to Reproduce (for bugs)
Run the mint tests against aws.

1. Run the mint tests against aws.
2. Should fail on `minio-py:test_copy_object_with_metadata`

## Your Environment

* Version used (`minio version`): master
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting, we'll take a look @diddiman

**Comment by kannappanr** [comment]
@diddiman The difference between `minio` and `AWS` is that `minio` sets the default `content-type` to `application/octet-stream` while `AWS` sets it to `binary/octet-stream`. Will talk internally and decide what we should do.

**Comment by harshavardhana** [comment]
Both are accepted for octet-stream under mime RFC

**Comment by kannappanr** [comment]
Then the solution would be to fix the test in `minio-py` to treat `binary/octet-stream` as `application/octet-stream` and then compare
