### ISSUE TITLE
reuse minio package to create s3 proxy

### ISSUE THREAD

**Issue by vtolstov** [minio/minio#7239]
Does it possibe to reuse some parts of minio to create s3 proxy package? I want to hook download and upload, and provide own implementation.

**Comment by nitisht** [comment]
you can probably take a look at implementation here https://github.com/minio/minio/tree/master/cmd/gateway @vtolstov

**Comment by nitisht** [comment]
@vtolstov closing this as answered, feel free to reopen or join us on Slack [https://slack.minio.io] for more such questions
