### ISSUE TITLE
Support Avro and ORC with SELECT API

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#7242]
** not using the template on purpose **

https://github.com/linkedin/goavro to support AVRO files format with SELECT API

https://github.com/scritchley/orc to support ORC files format with Select API

**Comment by kannappanr** [comment]
@harshavardhana Can this be closed and re-opened when we cycles to look at this

**Comment by harshavardhana** [comment]
Yes we can close it after confirming once with @abperiasamy

**Comment by harshavardhana** [comment]
Closing since we not be interested in adding this, we can re-open in future.
