### ISSUE TITLE
minio单点部署如何升级为分布式部署

### ISSUE THREAD

**Issue by 18810630600** [minio/minio#7247]
之前的minio一直是单点部署的，里面存储了大量的数据，现在计划将其升级为分布式部署，如何实现，同时保证历史数据不会丢失

**Comment by kannappanr** [comment]
Here is what Google Translate said 
```

The previous minio has been deployed on a single point, which stores a large amount of data, and now plans to upgrade it to a distributed deployment, how to achieve it, while ensuring that historical data will not be lost.

```

**Comment by kannappanr** [comment]
You will have to deploy another `minio` and mirror from `old minio` to the new one using `mc`

**Comment by kannappanr** [comment]
You cannot upgrade from single node minio deployment (fs) to distributed.

**Comment by kannappanr** [comment]
@18810630600 Closing this issue as answered. Please feel free to reach out to us if you have further questions.
