### ISSUE TITLE
Sort files and directories in listing

### ISSUE THREAD

**Issue by uzsolt** [minio/minio#7252]
It would be nice ability to choice the sorting order. For example sort by name increaising/decreasing, sort by time, etc. Would better when can set in command line or configuration file.

Thanks for your work!

**Comment by harshavardhana** [comment]
Lexical ordering is AWS S3 standard we cannot change that for compatibility reasons.

**Comment by uzsolt** [comment]
Oh, sad :( And can't change only on the web interface?

**Comment by harshavardhana** [comment]
Yes Web interface is ours and it's done on the client side.. we can't change the fact of S3 API behavior here.

**Comment by uzsolt** [comment]
Bad news. So I think should close this issue :(
