### ISSUE TITLE
Sending Minio Logs to Kibana

### ISSUE THREAD

**Issue by Hanrahank** [minio/minio#7254]
I've been trying to find ways of pushing logs from Minio through ELK stack to be viewed in Kibana. Does anyone know if there is a way of this to be done in Kubernetes?

I've been looking at possibly creating a snapshot in elasticsearch with https://github.com/minio/cookbook/blob/master/docs/elasticsearch-snapshots-on-minio.md

**Comment by nitisht** [comment]
@Hanrahank as discussed on Slack, Logstash input plugin that can fetch data from S3 / compatible services and push that to Logstash https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html should work in this case..

Can you please confirm?

**Comment by nitisht** [comment]
@Hanrahank closing this for now, as there is nothing specific to be done from Minio perspective. Feel free to reopen or get back on Slack if you feel otherwise.
