### ISSUE TITLE
Is there any way to continue multipart upload of a large file? (after pause or loosing the connection)

### ISSUE THREAD

**Issue by EvgenyKislyy** [minio/minio#7255]
Is there any way to continue multipart upload of a large file? (after pause or loosing the connection)
I saw it on version 3.0.7 of a java-client, and on a documentation
Now I cannot see anything like this.
Was this feature removed?
Any alternatives maybe?

**Comment by nitisht** [comment]
This is a planned approach @EvgenyKislyy here is the logic behind this change: https://github.com/minio/minio-java/pull/741

**Comment by EvgenyKislyy** [comment]
@nitisht what is the current alternative if I want to upload a large file, and I cannot be sure it will happen without any fails for the first time? 

And I want to have an ability to resume :) for faster uploading

**Comment by harshavardhana** [comment]
There are no alternatives, S3 API was never meant for resumable uploads. You can write a custom client if you still wish to, but there are known holes in the approach and it will never be full proof implementation.

**Comment by EvgenyKislyy** [comment]
Really? But how about this?
https://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html

**Comment by harshavardhana** [comment]
Yep even Multipart API is not designed, we did get this clarified from AWS team - if you can write a custom client it is possible where you tightly control the behavior. But an SDK should never have such a feature.

This is true with even all AWS SDKs

**Comment by nitisht** [comment]
Closing this as answered @EvgenyKislyy feel free to reach out on Slack for more questions

**Comment by EvgenyKislyy** [comment]
Sorry, and what will happen if I just will take a SDK version with this feature (continue multipart upliadings) included (the old one) and will use it? @harshavardhana

**Comment by harshavardhana** [comment]
You are simply exposing yourself to implementation with holes and potential unexpected issues, feel free to use it - but if you have a concurrent uploads to same object in multipart then the behavior is undefined and going to be inconsistent.

We will never recommend such endeavors.
