### ISSUE TITLE
Degraded read performance in distributed mode

### ISSUE THREAD

**Issue by stokowski** [minio/minio#7261]
Minio running in distributed mode has degraded read performance compared to standalone server or even distributed setup with offline disks/nodes.

## Expected Behavior
In distributed mode we should have more redundancy, syncing between nodes. Also reads should be faster if minio is able to read objects in parallel from many nodes/disks.

## Current Behavior
Read performance (listing objects for example) is much slower when using distributed mode that standalone server.

## Possible Solution
Hard to say - in distributed mode when listing objects cpu load can increase drasticaly

## Steps to Reproduce (for bugs)

1. Start minio in distributed mode - 2 nodes 5 disks each
2. Create bucket, sub folders, upload content (in my case video chunks)
3. List recursively objects under subfolder (mc client locally on two nodes - nodeA and nodeB)

```
Test 1: 2 nodes, 10 disk online

nodeA:
time mc ls --recursive localhost/bucket/subfolder/ > list.txt

real	6m27.538s
user	0m1.392s
sys	0m0.156s

wc -l list.txt
17089 list.txt (in all next tests result was the same)

nodeB:
time mc ls --recursive localhost/bucket/subfolder/ > list.txt

real	7m1.088s
user	0m1.348s
sys	  0m0.208s


Test2 : turn off minio on nodeB

nodeA:
time mc ls --recursive localhost/bucket/subfolder/ > list.txt

real	0m5.894s
user	0m0.720s
sys	  0m0.076s


nodeB:
time mc ls --recursive nodeA/bucket/subfolder/ > list.txt

real	0m6.335s
user	0m1.788s
sys	  0m0.272s


Test 3: turn off minio on nodeA, turn on nodeB

nodeA:
time mc ls --recursive nodeB/filmleihe/trailer/ > list.txt

real	1m7.763s     <- longer but still not 6-7 mins
user	0m1.784s
sys	0m0.264s


nodeB:
time mc ls --recursive localhost/bucket/subfolder/ > list.txt

real	0m3.999s
user	0m0.708s
sys	  0m0.052s


Test 4: again 2 nodes, 10 disks online

nodeA:
time mc ls --recursive localhost/bucket/subfolder/ > list.txt

real	6m39.753s
user	0m1.448s
sys	  0m0.180s


nodeB:
time mc ls --recursive localhost/bucket/subfolder/ > list.txt

real	6m52.800s
user	0m1.340s
sys	  0m0.200s
```

## Context
Building Minio instance in distributed mode with 2 nodes for redundancy and performance. Many TBs, +1m objects in bucket.

## Regression
-

## Your Environment
* Version used (`minio version`): RELEASE.2019-02-14T00-21-45Z (observed similar behavior on few before also)
* Environment name and version (e.g. nginx 1.9.1): Kubernetes with hostNetwork:true without ingress with direct connection to minio (tested also binary minio -> similar results)
* Server type and version: Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz, 6 x HDD (5 for minio data with zfs), nodes interconnected with 1gbps interface
* Operating System and version (`uname -a`): Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-142-generic x86_64)

```
iperf:

[  3] local 172.20.30.1 port 44906 connected with 172.20.30.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.10 GBytes   941 Mbits/sec
```

```

dd O_SYNC:

1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.395885 s, 2.7 GB/s
```

Also I'm able to reproduce this behavior on two other nodes in different dc/region with similar setup/data. Also when running 1 instance in standalone mode I've got results similar to 1/2 node online from this case.

**Comment by harshavardhana** [comment]
> Read performance (listing objects for example) is much slower when using distributed mode that standalone server.

Listing is slower because of metadata lookups over the network and also sorting in memory.  Increase in CPU usage is also expected. 

- How is your data laid out on the disk? do you have like a million entries at a single prefix parent with no heirarchy?
- Does your application List all the time? if yes how often and why? 

Here are some interesting points

> iperf:
> 
> [  3] local 172.20.30.1 port 44906 connected with 172.20.30.2 port 5001
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-10.0 sec  1.10 GBytes   941 Mbits/sec

- Your network is too slow compared to your disk speed if your disk is giving 2.5GiB/sec
- Your network speed peaks at 120MiB/sec - NOTE `iperf` gives you Mbits not Mbytes. 
- So it doesn't matter how fast your disk is - you are bottlenecked by 1Gig, you need 10gig or higher network speed to fully utilize your disk performance.

> Building Minio instance in distributed mode with 2 nodes for redundancy and performance. Many TBs, +1m objects in bucket.

- Building Minio on two nodes is not recommended a minimum of 3 nodes are needed for distributed locking quorum requirements. With 2 nodes if you loose 1 node you will not be able to access your data. 
- NOTE: In minio there are two quorum requirements one is disk quorum and another is node level quorum for locking.

> In distributed mode we should have more redundancy, syncing between nodes. Also reads should be faster if minio is able to read objects in parallel from many nodes/disks.

- This is only true if you have a faster interconnect 1Gig is not sufficient for expected performance here.

**Comment by stokowski** [comment]
Hi harshavardhana, thanks for reply.

> > Read performance (listing objects for example) is much slower when using distributed mode that standalone server.
> 
> Listing is slower because of metadata lookups over the network and also sorting in memory. Increase in CPU usage is also expected.
> 
>     * How is your data laid out on the disk? do you have like a million entries at a single prefix parent with no heirarchy?
> 
>     * Does your application List all the time? if yes how often and why?
> 

No, there is a tree hierarchy, but inside folder can be several thousand other folders, where on the end will be couple hundred files.

This would be mainly a vod storage, where listing will be on demand - I would like to see what objects/video assets I have and play. Also random access to objects when I would like to play. Read performance is more important to me than write.


> Here are some interesting points
> 
> > iperf:
> > [  3] local 172.20.30.1 port 44906 connected with 172.20.30.2 port 5001
> > [ ID] Interval       Transfer     Bandwidth
> > [  3]  0.0-10.0 sec  1.10 GBytes   941 Mbits/sec
> 
>     * Your network is too slow compared to your disk speed if your disk is giving 2.5GiB/sec
> 
>     * Your network speed peaks at 120MiB/sec - NOTE `iperf` gives you Mbits not Mbytes.
> 
>     * So it doesn't matter how fast your disk is - you are bottlenecked by 1Gig, you need 10gig or higher network speed to fully utilize your disk performance.
> 

Yes, I used `dd`:

```
sudo dd if=/dev/zero of=/data/store01/testfile bs=1M count=1024 oflag=sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.45934 s, 2.3 GB/s
```

O_DIRECT is not supported on zfs

Even this throughput is unbelievable, so I've prepared tmpfs and downloaded some video and retest:

```
dd if=/testfs/tearsofsteel_4k.mov  of=/data/store01/testfile bs=1M count=1024 oflag=sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.697378 s, 1.5 GB/s
```

which is funny on SATA disk, especially when compare to XFS:

```
dd if=/testfs/tearsofsteel_4k.mov  of=/data/store00/testfile bs=1M count=1024 oflag=sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 25.8939 s, 41.5 MB/s
```

And before I switched from xfs to zfs I had the same issue with reads/listing in this setup. 

> > Building Minio instance in distributed mode with 2 nodes for redundancy and performance. Many TBs, +1m objects in bucket.
> 
>     * Building Minio on two nodes is not recommended a minimum of 3 nodes are needed for distributed locking quorum requirements. With 2 nodes if you loose 1 node you will not be able to access your data.
> 
>     * NOTE: In minio there are two quorum requirements one is disk quorum and another is node level quorum for locking.
> 

Probably I missed something in docs and focused on disks. Its not a big deal to add another node, thanks.


> > In distributed mode we should have more redundancy, syncing between nodes. Also reads should be faster if minio is able to read objects in parallel from many nodes/disks.
> 
>     * This is only true if you have a faster interconnect 1Gig is not sufficient for expected performance here.

I dont have possibility to test that on 10Gig. Decreasing the disks number from 4 to 2 per node (+ add 3rd node) could help here ?

**Comment by stokowski** [comment]
I have repeated test and checked network utilization via atop - its around 2500-5xxx Kbps,

Also nothing special on disks:

```
02/21/2019 07:00:03 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.62    0.00    3.32    0.08    0.00   92.98

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     1.00    0.00    1.00     0.00     6.67    13.33     0.00    4.00    0.00    4.00   4.00   0.40
sdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdc               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdd               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sde               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdf               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-homelv         0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-varlv          0.00     0.00    0.00    1.67     0.00     6.67     8.00     0.00    2.40    0.00    2.40   2.40   0.40
vg-dockerlv       0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-tmplv          0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-store00lv      0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

02/21/2019 07:00:06 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.27    0.00    3.10    0.54    0.00   92.08

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00    0.00   10.67     0.00   198.67    37.25     0.01    1.12    0.00    1.12   1.12   1.20
sdc               0.00     0.00    0.00   10.67     0.00   186.67    35.00     0.01    1.38    0.00    1.38   1.25   1.33
sdd               0.00     0.00    0.00   13.33     0.00   206.67    31.00     0.01    1.00    0.00    1.00   0.70   0.93
sde               0.00     0.00    0.00   10.67     0.00   198.67    37.25     0.01    0.50    0.00    0.50   0.50   0.53
sdf               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-homelv         0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-varlv          0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-dockerlv       0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-tmplv          0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vg-store00lv      0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

**Comment by stokowski** [comment]
Hi,
Any ideas or any other tests that I can do ?

**Comment by stokowski** [comment]
I've noticed when stracing that minio tried to do tcpv6 connections even ipv6 is disabled:

```
7626 accept4(3, {sa_family=AF_INET6, sin6_port=htons(35962), inet_pton(AF_INET6, "::ffff:172.20.30.1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28], SOCK_CLOEXEC|SOCK_NONBLOCK) = 110
17626 getsockname(110, {sa_family=AF_INET6, sin6_port=htons(9000), inet_pton(AF_INET6, "::ffff:172.20.30.2", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
17626 setsockopt(110, SOL_TCP, TCP_NODELAY, [1], 4) = 0
17626 accept4(3, 0xc000646cd8, 0xc000646cbc, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
```

I've changed `--address` to internal one those errors dissappeared, but nothing changed about time listings. Btw. is it possible to run minio on 2 interfaces ?

Also I've noticed many:

```
epoll_ctl(4, EPOLL_CTL_ADD, 41, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1465079328, u64=139755405923872}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 41, 0xc00209c364) = -1 EPERM (Operation not permitted)
```

on dirs and files.

Still without solution.

**Comment by harshavardhana** [comment]
> I've changed `--address` to internal one those errors dissappeared, but nothing changed about time listings. Btw. is it possible to run minio on 2 interfaces ?

yes you can

```
minio server http://internal-ip/ ... 
```

and access your clients using `external-ip` pointing to `mc ls`. 

```
mc ls <alias>
```

**Comment by harshavardhana** [comment]
Can you provide the output of `fio` with random I/O across all your disks?

```
fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75
```

**Comment by stokowski** [comment]
Hi,

I've changed my setup and nodes - SATA to SAS, more cpu etc. Currently I'm mirroring content. When I will be able I will put here new set of tests and results.

**Comment by harshavardhana** [comment]
> I've changed my setup and nodes - SATA to SAS, more cpu etc. Currently I'm mirroring content. When I will be able I will put here new set of tests and results.

Were you able to further do your tests?

**Comment by stokowski** [comment]
I've tried this test. I'm using zfs (zol) so O_DIRECT is not supported here. I've also turned off O_SYNC, so when tried for sync writes I get a results like this:

```
fio --randrepeat=1 --ioengine=libaio --sync=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75
test: (g=0): rw=randrw, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=64
fio-2.2.10
Starting 1 process
Jobs: 1 (f=1): [m(1)] [100.0% done] [138.1MB/47912KB/0KB /s] [35.6K/11.1K/0 iops] [eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=447459: Mon Apr 15 22:39:26 2019
  read : io=3071.7MB, bw=130753KB/s, iops=32688, runt= 24056msec
  write: io=1024.4MB, bw=43603KB/s, iops=10900, runt= 24056msec
  cpu          : usr=6.78%, sys=53.84%, ctx=87746, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=786347/w=262229/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: io=3071.7MB, aggrb=130752KB/s, minb=130752KB/s, maxb=130752KB/s, mint=24056msec, maxt=24056msec
  WRITE: io=1024.4MB, aggrb=43603KB/s, minb=43603KB/s, maxb=43603KB/s, mint=24056msec, maxt=24056msec
```

In meantime there was release that improved listing objects, now its faster, but still what I see is that the disks are the bottleneck in this type of read. I'm thinking how I could improve that, but this issue can be closed. Thanks.

**Comment by harshavardhana** [comment]
> In meantime there was release that improved listing objects, now its faster, but still what I see is that the disks are the bottleneck in this type of read. I'm thinking how I could improve that, but this issue can be closed. Thanks.

Thanks for letting us know @stokowski we are making further improvements here #7541

**Comment by harshavardhana** [comment]
Closing as per last comment.

**Comment by matejzero** [comment]
I know this is closed, but I can add some info too if it helps.

My system:
- 2 nodes (dual-cpu CPU E5-2630, 64GB memory)
- each node has 2 SSD drives (fast drives with 180k write IOPS)
- nodes are interconnected with 10GBit

I created a bucket with 20k files in it. Running `time mc ls local/test > output`:
single mode: real  0m1.941s
distributed mode: real 0m11.103s

**Comment by stokowski** [comment]
I will repeat tests for standalone next week. I hope also that new fix will get in to next release. Also, maybe there is a way to monitor some minio internals and see where is hanging on ?

**Comment by matejzero** [comment]
My tests were made with latest release and fast enough drives for them to not be the bottleneck. If I can do any other testing, let me know.
