### ISSUE TITLE
minio hardware usage

### ISSUE THREAD

**Issue by emadghav** [minio/minio#7264]
i using a minio cluster with 4 server and 8 disk and 1m file that have size 30kb_200kb  when i start minio after 5 minute increase memory and cpu usage after a minute reduce speed and afte 3 or 4 minio crash

**Comment by nitisht** [comment]
@emadghav please use the issue template to report the issue - otherwise it is just redundant to ask for the details that are already mentioned in the issue template. 

Please provide minio version, your hardware specifications and also `mc admin monitor myminio` output

**Comment by emadghav** [comment]
i using windows server 2016 ,1tb ssd hard(7200) ,12 processor intel xenon 2.2gh ,32GB memory and 1GB network that this server hosted on hp G9 server

Version: 2019-02-20T22:44:29Z
Release-Tag: RELEASE.2019-02-20T22-44-29Z
Commit-ID: 6dd26b82317c543b3c59fb85b02204547340e8ca

when start minio 
●  192.168.16.21:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    211MiB
   historic   130MiB


●  192.168.16.22:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    173MiB
   historic   109MiB


●  192.168.16.23:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    164MiB
   historic   115MiB


●  192.168.16.24:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    168MiB
   historic   96MiB
after a few minute without any put object
●  192.168.16.21:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    2.6GiB
   historic   1.4GiB


●  192.168.16.22:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    2.4GiB
   historic   1.3GiB


●  192.168.16.23:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    2.3GiB
   historic   1.3GiB


●  192.168.16.24:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    2.5GiB
   historic   1.3GiB
and cupu up to 70%

**Comment by emadghav** [comment]
> i using windows server 2016 ,1tb ssd hard(7200) ,12 processor intel xenon 2.2gh ,32GB memory and 1GB network that this server hosted on hp G9 server
> when start minio
> ● 192.168.16.21:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 211MiB
> historic 130MiB
> 
> ● 192.168.16.22:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 173MiB
> historic 109MiB
> 
> ● 192.168.16.23:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 164MiB
> historic 115MiB
> 
> ● 192.168.16.24:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 168MiB
> historic 96MiB
> after a few minute without any put object
> ● 192.168.16.21:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 2.6GiB
> historic 1.4GiB
> 
> ● 192.168.16.22:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 2.4GiB
> historic 1.3GiB
> 
> ● 192.168.16.23:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 2.3GiB
> historic 1.3GiB
> 
> ● 192.168.16.24:9001
> 
> CPU min avg max
> current 0.00% 0.00% 0.00%
> historic 0.00% 0.00% 0.00%
> 
> MEM usage
> current 2.5GiB
> historic 1.3GiB
> and cupu up to 70%

**Comment by emadghav** [comment]
after 40 minute
●  192.168.16.21:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    12.2GiB
   historic   6.3GiB


●  192.168.16.22:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    12.2GiB
   historic   6.1GiB


●  192.168.16.23:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    12.7GiB
   historic   6.2GiB


●  192.168.16.24:9001

   CPU        min        avg      max
   current    0.00%      0.00%    0.00%
   historic   0.00%      0.00%    0.00%

   MEM        usage
   current    12.1GiB
   historic   6.1GiB

**Comment by nitisht** [comment]
@emadghav at this point does it still crash? Can you join us on Slack (https://slack.min.io) for quicker conversation/resolution

**Comment by emadghav** [comment]
ok i join slack
yes when i put object after a time crashed,

for 2 day dont put any object but minio not responce and print this log


goroutine 20216 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x5c02c10, 0x72, 0x17d5140)
        /opt/go/src/runtime/netpoll.go:173 +0x6d
internal/poll.(*pollDesc).wait(0xc591b5fa88, 0x72, 0x230c700, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_poll_runtime.go:85 +0xa1
internal/poll.(*ioSrv).ExecIO(0x2627540, 0xc591b5f8d8, 0x1649510, 0x0, 0xc32f497b48, 0x5dc8a2)
        /opt/go/src/internal/poll/fd_windows.go:222 +0x137
internal/poll.(*FD).Read(0xc591b5f8c0, 0xc5c955a000, 0x100000, 0x100000, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_windows.go:487 +0x252
net.(*netFD).Read(0xc591b5f8c0, 0xc5c955a000, 0x100000, 0x100000, 0xed401aa92, 0x0, 0x0)
        /opt/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc690184950, 0xc5c955a000, 0x100000, 0x100000, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:177 +0x6f
bufio.(*Reader).Read(0xc08a0ddce0, 0xc0015bf000, 0x1000, 0x1000, 0x262d740, 0xc32f497ca0, 0x6ddc51)
        /opt/go/src/bufio/bufio.go:216 +0x236
github.com/minio/minio/cmd/http.(*BufConn).Read(0xc000166180, 0xc0015bf000, 0x1000, 0x1000, 0xc32f497d20, 0x5ef3bf, 0xc591b5f8c0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/bufconn.go:71 +0x66
net/http.(*connReader).Read(0xc21647f0e0, 0xc0015bf000, 0x1000, 0x1000, 0xc690184950, 0xbf140ac4b95695f8, 0x948b10caf8d)
        /opt/go/src/net/http/server.go:786 +0x103
bufio.(*Reader).fill(0xc08a0ddd40)
        /opt/go/src/bufio/bufio.go:100 +0x116
bufio.(*Reader).Peek(0xc08a0ddd40, 0x4, 0x948b10caf8d, 0x262d740, 0x0, 0x0, 0x262d740)
        /opt/go/src/bufio/bufio.go:132 +0x46
net/http.(*conn).serve(0xc00051b180, 0x17e37a0, 0xc0001661c0)
        /opt/go/src/net/http/server.go:1872 +0x7c1
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2851 +0x2fc

goroutine 20531 [runnable]:
net.(*netFD).connect.func2(0x17e3820, 0xc0077f7c80, 0xc000033600, 0xc753021b00)
        /opt/go/src/net/fd_windows.go:106 +0xbe
created by net.(*netFD).connect
        /opt/go/src/net/fd_windows.go:105 +0x1ba

goroutine 20446 [select]:
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func2(0xc00006c140, 0xc0003048a0, 0xc761ccd2a0, 0xc72c3ae600, 0x26, 0xc76277c59c, 0xc76277c5c0, 0x1)
        /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:227 +0x13f
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
        /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:213 +0x2aa

**Comment by emadghav** [comment]
goroutine 16192188 [sleep]:
time.Sleep(0x3b9aca00)
        /opt/go/src/runtime/time.go:105 +0x164
github.com/minio/minio/cmd.(*posix).diskUsage.func1(0x17e37e0, 0xc000034ac0, 0xc484a42040, 0xc, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:392 +0x6b
github.com/minio/minio/cmd.walk(0x17e37e0, 0xc000034ac0, 0xc484a42040, 0xc, 0xc44c1a8440, 0xc484a42040, 0xc)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-usage.go:33 +0x68
github.com/minio/minio/cmd.getDiskUsage(0x17e37e0, 0xc000034ac0, 0xc4c6c96d90, 0xb, 0xc44c1a8440, 0xc41cf06120, 0xc1cd015ef8)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-usage.go:26 +0x94
github.com/minio/minio/cmd.(*posix).diskUsage(0xc259e48780, 0xc000076840)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:414 +0xe7
created by github.com/minio/minio/cmd.newPosix
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:210 +0x1d1

goroutine 16219440 [sleep]:
time.Sleep(0x3b9aca00)
        /opt/go/src/runtime/time.go:105 +0x164
github.com/minio/minio/cmd.(*posix).diskUsage.func1(0x17e37e0, 0xc000034ac0, 0xc3d9c6aca0, 0xc, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:392 +0x6b
github.com/minio/minio/cmd.walk(0x17e37e0, 0xc000034ac0, 0xc3d9c6aca0, 0xc, 0xc5185d0580, 0xc3d9c6aca0, 0xc)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-usage.go:33 +0x68
github.com/minio/minio/cmd.getDiskUsage(0x17e37e0, 0xc000034ac0, 0xc666b3e3d0, 0xb, 0xc5185d0580, 0xc61def0900, 0x24)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-usage.go:26 +0x94
github.com/minio/minio/cmd.(*posix).diskUsage(0xc3d6d65860, 0xc000076840)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:414 +0xe7
created by github.com/minio/minio/cmd.newPosix
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:210 +0x1d1

**Comment by harshavardhana** [comment]
Proper disk detection PR is sent here #7288

**Comment by harshavardhana** [comment]
Closing this after confirmation on slack... Closing this issue here.
