### ISSUE TITLE
server: mc fails to mirror over Nginx reverse proxy to Minio

### ISSUE THREAD

**Issue by leshik** [minio/minio#7271]
## Expected Behavior

Mirror all files completely without a GOAWAY result.

## Current Behavior

`Minio` server instance is behind the HTTPS nginx reverse proxy as per `minio` docs. I'm mirroring a lot of small files (`svg` images, `mp3` files, etc.) with `minio` client, all over LAN. Mirroring fails with HTTP/2 GOAWAY error:

```
Total: 67.33 MB, Transferred: 67.33 MB, Speed: 5.10 MB/s
mc: <ERROR> Unable to mirror. http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
```

Related to #4056.

## Your Environment
* Version used (`minio version`):
```
Version: 2019-02-20T22:44:29Z
Release-Tag: RELEASE.2019-02-20T22-44-29Z
Commit-ID: 6dd26b82317c543b3c59fb85b02204547340e8ca
```
* Environment name and version (e.g. nginx 1.9.1): `nginx/1.14.2`
```
server {
    listen [::]:443 ssl http2;
    listen 443 ssl http2;
    ...
    ignore_invalid_headers off;

    location /learn21-assets/ {
        proxy_pass http://minio:9000;
        proxy_set_header Host $http_host;
        proxy_buffering off;
    }
}
```
* Server type and version: all services are in Docker Swarm containers
* Operating System and version (`uname -a`): `Linux cbe2728e185d 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
can you add MINIO_HTTP_TRACE=/dev/stdout to Minio and provide the trace? @leshik

**Comment by leshik** [comment]
@harshavardhana I just realized that this might be the issue with `mc` client, as Nginx doesn's support HTTP/2 in proxy_pass, and the error obviously comes from `go/net`.

Anyway, I enabled tracing as you suggested, and also used the `--debug` flag in `mc`. Turns out, terminal output drastically slows down the mirror operation performance, thus I'm unable to reproduce it with debugging on.

What else can I try?

**Comment by harshavardhana** [comment]
> @harshavardhana I just realized that this might be the issue with `mc` client, as Nginx doesn's support HTTP/2 in proxy_pass, and the error obviously comes from `go/net`.
> 
> Anyway, I enabled tracing as you suggested, and also used the `--debug` flag in `mc`. Turns out, terminal output drastically slows down the mirror operation performance, thus I'm unable to reproduce it with debugging on.
> 
> What else can I try?

I am not able to understand are you saying its an nginx issue or `mc` issue?

**Comment by leshik** [comment]
The issue is with `mc` apparently.

**Comment by harshavardhana** [comment]
> The issue is with `mc` apparently.

how with `mc` ? - mc does support HTTP2 - @leshik

**Comment by leshik** [comment]
@harshavardhana well, the issue is with `go` maybe as I’m seeing  exactly that is described here: https://github.com/golang/go/issues/18112

Should’ve been fixed in Go 1.8, but the issue is still here.

**Comment by harshavardhana** [comment]
> @harshavardhana well, the issue is with `go` maybe as I’m seeing exactly that is described here: [golang/go#18112](https://github.com/golang/go/issues/18112)
> 
> Should’ve been fixed in Go 1.8, but the issue is still here.

@leshik is it always reproducible or does it reproduce after a while during I/O ?

**Comment by leshik** [comment]
@harshavardhana It reproduces after a while. E.g. I was mirroring 1Gb of files, and got this error after about ~100Mb (there is no particular amount of data it has to send, I was able to see the error after ~30Mb of transfer sometimes).

**Comment by harshavardhana** [comment]
Can you reproduce this without the proxy ?

**Comment by leshik** [comment]
@harshavardhana no, I see this issue only when using Nginx proxy.

**Comment by harshavardhana** [comment]
Then the problem is perhaps in Nginx configuration.. have you tried any other proxies like traefik?

**Comment by leshik** [comment]
@harshavardhana my Nginx config is trivial and is almost copy-and-paste from Minio documentation. I didn't try traefik, but I think it will obscure the issue as it's written in Go too. Maybe I'll create the `docker-compose` file that reproduces the issue when I have time.

**Comment by harshavardhana** [comment]
I suspect this a Go bug or nginx interaction issue. Not sure what Minio can do at this situation. If you can provide a compose file perhaps reproducing this might help me pursue this upstream.

**Comment by harshavardhana** [comment]
> I suspect this a Go bug or nginx interaction issue. Not sure what Minio can do at this situation. If you can provide a compose file perhaps reproducing this might help me pursue this upstream.

@leshik ^^

**Comment by leshik** [comment]
Sorry, this issue is not of high priority to me thus I had no time yet to reproduce it in compose. Maybe someday later...

**Comment by harshavardhana** [comment]
Then perhaps let's close this and move forward @leshik , as I have no way to reproduce this right now.

**Comment by leshik** [comment]
@harshavardhana ok, I'll reopen this after I create some reproducible environment.

**Comment by harshavardhana** [comment]
Thanks @leshik
