### ISSUE TITLE
Implement deadlines for POSIX open fd's

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#7283]
*** Not using template ***

https://golang.org/pkg/os/#File.SetReadDeadline 
https://golang.org/pkg/os/#File.SetWriteDeadline

Use deadline for all open fd's at posix layer, this is to ensure that when disks go bad or offline suddenly. There are timeouts implemented at POSIX layer to timeout any hun i/o. 

Currently master branch will hang indefinitely at posix layer.

**Comment by krishnasrinivas** [comment]
os.SetReadDeadline is not supported for ordinary files, its supported for pipes/sockets though:
```
krishna@escape:~/dev/goprogs$ cat deadline.go
package main

import (
    "io"
    "log"
    "os"
    "time"
)

func main() {
    f, err := os.Open("/etc/passwd")
    if err != nil {
        log.Fatal(err)
    }
    err = f.SetDeadline(time.Now().Add(time.Second))
    if err != nil {
        log.Fatal(err)
    }
    io.Copy(os.Stdout, f)
}
krishna@escape:~/dev/goprogs$ go run deadline.go
2019/02/28 11:46:23 file type does not support deadline
exit status 1
krishna@escape:~/dev/goprogs$ 
```

**Comment by harshavardhana** [comment]
Thanks, @krishnasrinivas we should still proceed to implement a deadline based on some form of contexts, otherwise disk timeouts are too long and we have network timeouts are way longer. 

https://github.com/golang/go/issues/22114 states the intention of the implementation

We need a way to actively put a deadline on the FD's such that we can close the FD and disconnect the call quickly when the disks go down. Linux kernel is a bit notorious in hanging backends on their filesystems.

**Comment by krishnasrinivas** [comment]
this is how timeout was done for KV:
```
func (k *kvssd) Put(container, key string, value []byte) error {
        kvKey := kvKeyName(container, key)
        timer := time.NewTimer(5 * time.Second)
        doneCh := make(chan struct{})
        go func() {
                C.minio_kvs_put(k.kvContainerHandle, unsafe.Pointer(&kvKey[0]), C.int(len(kvKey)), unsafe.Pointer(&value[0]), C.int(len(value)))
                close(doneCh)
        }()
        select {
        case <-timer.C:
                fmt.Printf("put(%s) timedout\n", key)
                return errors.New("timeout")
        case <-doneCh:
                timer.Stop()
                break
        }
        return nil
}
```

something similar may be needed for posix calls

**Comment by harshavardhana** [comment]
This is good start @krishnasrinivas

**Comment by harshavardhana** [comment]
This is not possible and not easy to implement. Contexts on POSIX are hard and hard to provide such deadlines. 

Closing this issue as technically not feasible at the moment.
