### ISSUE TITLE
Presigned localhost URLs have https even though TLS hasn't been configured

### ISSUE THREAD

**Issue by alexgurr** [minio/minio#7284]
Environment information and perquisites can be found @ https://github.com/minio/minio/issues/7209.

----------------

Presigned URLs are being generated in the correct format, but with **https**:// which isn't working with localhost. How can I turn off https signed urls?

According to this article (https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls) you have to enable TLS manually. So why are pre-signed URLs generated with https even when the server is running on http?

https://puu.sh/CKQVt/998778d506.png

When I change https to http I get progress but now get:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <Resource>/hubdatastore-shootsta-sydney-663842070690/foo/bar.jpg</Resource>
    <RequestId>15827961D4C0FA53</RequestId>
    <HostId>3L137</HostId>
</Error>
```

**Comment by harshavardhana** [comment]
Perhaps because you are not turning off https in your AWS Sdk constructor. 

Presigned URLs are generated by client side not server.

**Comment by nitisht** [comment]
@alexgurr can you pls confirm if it works after the recommendation in https://github.com/minio/minio/issues/7284#issuecomment-466853745

**Comment by kannappanr** [comment]
@alexgurr Closing this issue based on the previous comments. Please feel free to let us know if you have any further questions.
